Analysis Software: Acts::Test::LayerCreatorFixture Struct Reference
Acts::Test::LayerCreatorFixture Struct Reference
Public Member Functions
LayerCreatorFixture ()
template<typename... Args>
bool checkBinning (Args &&...args)
bool checkBinContentSize (const SurfaceArray *sArray, size_t n)
SrfVec fullPhiTestSurfacesEC (size_t n=10, double shift=0, double zbase=0, double r=10)
SrfVec fullPhiTestSurfacesBRL (int n=10, double shift=0, double zbase=0, double incl=M_PI/9., double w=2, double h=1.5)
SrfVec makeBarrel (int nPhi, int nZ, double w, double h)
std::pair< SrfVec, std::vector
< std::pair< const Surface
*, const Surface * > > > makeBarrelStagger (int nPhi, int nZ, double shift=0, double incl=M_PI/9., double w=2, double h=1.5)
Public Attributes
std::shared_ptr< const
SurfaceArrayCreator > p_SAC
std::shared_ptr< LayerCreator > p_LC
std::vector< std::shared_ptr
< const Surface > > m_surfaces
Detailed Description
Definition at line 98 of file LayerCreatorTests.cpp.
View newest version in sPHENIX GitHub at line 98 of file LayerCreatorTests.cpp
Constructor & Destructor Documentation
Acts::Test::LayerCreatorFixture::LayerCreatorFixture () inline
Definition at line 104 of file LayerCreatorTests.cpp.
View newest version in sPHENIX GitHub at line 104 of file LayerCreatorTests.cpp
References cfg, filter::Config, Acts::getDefaultLogger(), p_LC, p_SAC, and Acts::Logging::VERBOSE.
Member Function Documentation
bool Acts::Test::LayerCreatorFixture::checkBinContentSize (const SurfaceArray * sArray, size_t n) inline
Definition at line 119 of file LayerCreatorTests.cpp.
View newest version in sPHENIX GitHub at line 119 of file LayerCreatorTests.cpp
References Acts::SurfaceArray::at(), i, Acts::SurfaceArray::isValidBin(), n, and Acts::SurfaceArray::size().
template<typename... Args> bool Acts::Test::LayerCreatorFixture::checkBinning (Args &&... args) inline
Definition at line 115 of file LayerCreatorTests.cpp.
View newest version in sPHENIX GitHub at line 115 of file LayerCreatorTests.cpp
References check_smearing_config::args, and p_LC.
SrfVec Acts::Test::LayerCreatorFixture::fullPhiTestSurfacesBRL (int n = 10, double shift = 0, double zbase = 0, double incl = M_PI / 9., double w = 2, double h = 1.5) inline
Definition at line 160 of file LayerCreatorTests.cpp.
View newest version in sPHENIX GitHub at line 160 of file LayerCreatorTests.cpp
References bounds, h, i, m_surfaces, testing::internal::move(), n, and physmon_track_finding_ttbar::z.
Referenced by makeBarrel().
SrfVec Acts::Test::LayerCreatorFixture::fullPhiTestSurfacesEC (size_t n = 10, double shift = 0, double zbase = 0, double r = 10) inline
Definition at line 135 of file LayerCreatorTests.cpp.
View newest version in sPHENIX GitHub at line 135 of file LayerCreatorTests.cpp
References bounds, i, m_surfaces, testing::internal::move(), n, physmon_track_finding_ttbar::r, and physmon_track_finding_ttbar::z.
SrfVec Acts::Test::LayerCreatorFixture::makeBarrel (int nPhi, int nZ, double w, double h) inline
Definition at line 188 of file LayerCreatorTests.cpp.
View newest version in sPHENIX GitHub at line 188 of file LayerCreatorTests.cpp
References fullPhiTestSurfacesBRL(), i, and physmon_track_finding_ttbar::z.
std::pair<SrfVec, std::vector<std::pair<const Surface*, const Surface*> > > Acts::Test::LayerCreatorFixture::makeBarrelStagger (int nPhi, int nZ, double shift = 0, double incl = M_PI / 9., double w = 2, double h = 1.5) inline
Definition at line 203 of file LayerCreatorTests.cpp.
View newest version in sPHENIX GitHub at line 203 of file LayerCreatorTests.cpp
References bounds, h, i, j, m_surfaces, testing::internal::move(), Acts::Test::tgContext, and physmon_track_finding_ttbar::z.
Member Data Documentation
std::vector<std::shared_ptr<const Surface> > Acts::Test::LayerCreatorFixture::m_surfaces
Definition at line 102 of file LayerCreatorTests.cpp.
View newest version in sPHENIX GitHub at line 102 of file LayerCreatorTests.cpp
Referenced by fullPhiTestSurfacesBRL(), fullPhiTestSurfacesEC(), and makeBarrelStagger().
std::shared_ptr<LayerCreator> Acts::Test::LayerCreatorFixture::p_LC
Definition at line 100 of file LayerCreatorTests.cpp.
View newest version in sPHENIX GitHub at line 100 of file LayerCreatorTests.cpp
Referenced by checkBinning(), and LayerCreatorFixture().
std::shared_ptr<const SurfaceArrayCreator> Acts::Test::LayerCreatorFixture::p_SAC
Definition at line 99 of file LayerCreatorTests.cpp.
View newest version in sPHENIX GitHub at line 99 of file LayerCreatorTests.cpp
Referenced by LayerCreatorFixture().
The documentation for this struct was generated from the following file:
acts/blob/sPHENIX/Tests/UnitTests/Core/Geometry/LayerCreatorTests.cpp