Analysis Software: Acts::PlanarModuleCluster Class Reference
Acts::PlanarModuleCluster Class Reference
#include <acts/blob/sPHENIX/Plugins/Digitization/include/Acts/Plugins/Digitization/PlanarModuleCluster.hpp>
Public Member Functions
PlanarModuleCluster (std::shared_ptr< const Surface > mSurface, const Identifier &identifier, ActsSymMatrixD< 3 > cov, double loc0, double loc1, double t, std::vector< DigitizationCell > dCells, const DigitizationModule *dModule=nullptr)
const std::vector
< DigitizationCell > & digitizationCells () const
const DigitizationModule * digitizationModule () const
Public Member Functions inherited from Acts::Measurement< source_link_t, parameter_indices_t, params >
Measurement ()=delete
Delete the default constructor.
template<typename... Tail>
Measurement (std::shared_ptr< const RefObject > referenceObject, const source_link_t &source, CovarianceMatrix cov, typename std::enable_if< sizeof...(Tail)+1==sizeof...(params), Scalar >::type head, Tail...values)
standard constructor for surface/volume measurements
Measurement (std::shared_ptr< const RefObject > referenceObject, const source_link_t &source, CovarianceMatrix cov, ParametersVector vec)
standard constructor for surface/volume measurements
virtual ~Measurement ()=default
Measurement (const Measurement< source_link_t, parameter_indices_t, params...> &copy)
copy constructor
Measurement (Measurement< source_link_t, parameter_indices_t, params...> &&other)
move constructor
Measurement< source_link_t,
parameter_indices_t, params...> & operator= (const Measurement< source_link_t, parameter_indices_t, params...> &rhs)
copy assignment operator
Measurement< source_link_t,
parameter_indices_t, params...> & operator= (Measurement< source_link_t, parameter_indices_t, params...> &&rhs)
move assignment operator
template<parameter_indices_t parameter>
Scalar get () const
retrieve stored value for given parameter
const ParametersVector & parameters () const
access vector with measured parameter values
const CovarianceMatrix & covariance () const
access covariance matrix of the measured parameter values
template<parameter_indices_t parameter>
Scalar uncertainty () const
retrieve stored uncertainty for given parameter
const RefObject & referenceObject () const
access associated object
const source_link_t & sourceLink () const
link access to the source of the measurement.
ParametersVector residual (const FullParametersVector &trackPars) const
calculate residual with respect to given track parameters
virtual bool operator== (const Measurement< source_link_t, parameter_indices_t, params...> &rhs) const
equality operator
bool operator!= (const Measurement< source_link_t, parameter_indices_t, params...> &rhs) const
inequality operator
Private Attributes
std::vector< DigitizationCell > m_digitizationCells
const DigitizationModule * m_digitizationModule
the digitization cells
Additional Inherited Members
Public Types inherited from Acts::Measurement< source_link_t, parameter_indices_t, params >
using Scalar = typename ParamSet::Scalar
using ParametersVector = typename ParamSet::ParametersVector
type of the vector containing the parameter values
using FullParametersVector = typename ParamSet::FullParametersVector
Vector type containing all parameters from the same space.
using CovarianceMatrix = typename ParamSet::CovarianceMatrix
type of the covariance matrix of the measurement
using ProjectionMatrix = typename ParamSet::ProjectionMatrix
matrix type for projecting full parameter vector onto measured parameters
using RefObject = typename detail::ReferenceObject< parameter_indices_t >::type
Object type that corresponds to the measurement.
Static Public Member Functions inherited from Acts::Measurement< source_link_t, parameter_indices_t, params >
static constexpr unsigned int size ()
number of measured parameters
static const ProjectionMatrix & projector ()
operator
Protected Member Functions inherited from Acts::Measurement< source_link_t, parameter_indices_t, params >
virtual std::ostream & print (std::ostream &out) const
Detailed Description
Definition at line 31 of file PlanarModuleCluster.hpp.
View newest version in sPHENIX GitHub at line 31 of file PlanarModuleCluster.hpp
Constructor & Destructor Documentation
Acts::PlanarModuleCluster::PlanarModuleCluster (std::shared_ptr< const Surface > mSurface, const Identifier & identifier, ActsSymMatrixD< 3 > cov, double loc0, double loc1, double t, std::vector< DigitizationCell > dCells, const DigitizationModule * dModule = nullptr) inline
Constructor from DigitizationCells
Parameters
[in] mSurface is the module surface
[in] cIdentifier is the channel identifier of the local position
[in] cov is the covariance matrix
[in] loc0 is the local position in the first coordinate
[in] loc1 is the local position in the second coordinate
[in] t Timestamp of the cluster
[in] dCells is the vector of digitization cells
Definition at line 44 of file PlanarModuleCluster.hpp.
View newest version in sPHENIX GitHub at line 44 of file PlanarModuleCluster.hpp
Member Function Documentation
const std::vector< DigitizationCell > & Acts::PlanarModuleCluster::digitizationCells () const inline
access to the digitization cells
Returns
the vector to the digitization cells
Definition at line 73 of file PlanarModuleCluster.hpp.
View newest version in sPHENIX GitHub at line 73 of file PlanarModuleCluster.hpp
References m_digitizationCells.
Referenced by ActsExamples::PrintHits::execute(), ActsExamples::CsvPlanarClusterWriter::writeT(), and ActsExamples::RootPlanarClusterWriter::writeT().
const DigitizationModule * Acts::PlanarModuleCluster::digitizationModule () const inline
access to the digitization module
Returns
the pointer to the digitization module
Definition at line 77 of file PlanarModuleCluster.hpp.
View newest version in sPHENIX GitHub at line 77 of file PlanarModuleCluster.hpp
References m_digitizationModule.
Member Data Documentation
std::vector<DigitizationCell> Acts::PlanarModuleCluster::m_digitizationCells private
Definition at line 68 of file PlanarModuleCluster.hpp.
View newest version in sPHENIX GitHub at line 68 of file PlanarModuleCluster.hpp
Referenced by digitizationCells().
const DigitizationModule* Acts::PlanarModuleCluster::m_digitizationModule private
the digitization cells
Definition at line 69 of file PlanarModuleCluster.hpp.
View newest version in sPHENIX GitHub at line 69 of file PlanarModuleCluster.hpp
Referenced by digitizationModule().
The documentation for this class was generated from the following file:
acts/blob/sPHENIX/Plugins/Digitization/include/Acts/Plugins/Digitization/PlanarModuleCluster.hpp