Analysis Software: coresoftware/blob/master/generators/JEWEL/jewel-2.2.0.f File Reference
jewel-2.2.0.f File Reference
Functions/Subroutines
program jewel
subroutine init ()
subroutine initpythia (beam1, beam2)
subroutine genevent (j, b1, b2)
subroutine makestrings (WHICH)
subroutine makestrings_vac
subroutine makestrings_minl
subroutine cleanup (NFIRST)
subroutine makecascade
subroutine makebranch (L)
subroutine makesplitting (L)
subroutine makeinsplit (L, X, TSUM, VIRT, TYPI, TIME, TAURAD)
subroutine doinstatescat (L, X, TYPI, Q, TSTART, DELTAT, OVERQ0, RETRYSPLIT)
subroutine dofistatescat (L, TNOW, DTLEFT, DELTAT, NEWMASS, OVERQ0, Z, QQBAR)
DOUBLE PRECISION function getnewmass (L, Q2, QOLD2, MASS, IN, X, ZDEC, QQBARDEC)
DOUBLE PRECISION function getpnorad1 (LINE, x, y, z, t)
subroutine getqvec (L, J, DT, X)
subroutine dokinematics (L, lold, N1, N2, NEWM, RETRYSPLIT, TIME, X, Z, QQBAR)
DOUBLE PRECISION function getproba (QI, QF, QAA, ZAA, EBB, TYPE, T1, INS2)
DOUBLE PRECISION function getsudakov (QMAX1, QA1, QB1, ZA1, EB1, TYPE3, T2, INS)
DOUBLE PRECISION function getinsudakov (QB, QMAX1, TYPE3)
DOUBLE PRECISION function deriv (XVAL, W4)
DOUBLE PRECISION function getspliti (QA, QB, ZETA, EB, TYPE1)
DOUBLE PRECISION function getinspliti (QB, TYPE1)
DOUBLE PRECISION function getpdf (X, Q, TYP)
DOUBLE PRECISION function getpdfxint (Q, TYP)
DOUBLE PRECISION function getpdfxintexact (Q, TYP)
DOUBLE PRECISION function getxsecint (TM, MD, TYP2)
DOUBLE PRECISION function getinsudafast (Q1, Q2, TYP)
DOUBLE PRECISION function getinsudared (Q, TYP2)
DOUBLE PRECISION function getsscat (EN, px, py, PZ, MP, LW, TYPE1, TYPE2, x, y, z, t, mode)
DOUBLE PRECISION function getmass (QBMIN, QBMAX, THETA, EP, TYPE, MAX2, INS, ZDEC, QQBARDEC)
DOUBLE PRECISION function generatez (TI, EA, EPSI, TYPE)
DOUBLE PRECISION function scatprimfunc (T, MDEB)
DOUBLE PRECISION function intpqq (Z, Q)
DOUBLE PRECISION function intpgglow (Z, Q)
DOUBLE PRECISION function intpgghigh (Z, Q)
DOUBLE PRECISION function intpqglow (Z, Q)
DOUBLE PRECISION function intpqghigh (Z, Q)
DOUBLE PRECISION function gett (MINT, MAXT, MDEB)
DOUBLE PRECISION function ei (X)
DOUBLE PRECISION function pqq (Z)
DOUBLE PRECISION function pgq (Z)
DOUBLE PRECISION function pgg (Z)
DOUBLE PRECISION function pqg (Z)
DOUBLE PRECISION function alphas (T, LAMBDA)
subroutine splitfncint (EMAX)
subroutine pdfint (EMAX)
subroutine xsecint (EMAX)
subroutine insudaint (EMAX)
subroutine eixint
subroutine odeint (ystart, a, b, eps, h1, hmin, w1)
subroutine rkstepper (x, y, dydx, htest, hdid, hnew, yscale, eps, w1)
double precision function rk4step (x, y, dydx, h, w1)
LOGICAL function getdeltat (LINE, TSTART, DTMAX1, DELTAT)
integer function poissonian (lambda)
LOGICAL function ishadron (ID)
LOGICAL function isdiquark (ID)
LOGICAL function islepton (ID)
LOGICAL function isparton (ID)
logical function isprimstring (l)
logical function issecstring (l)
logical function isprimhadron (l)
logical function compressevent (l1)
subroutine pevrec (NUM, COL)
subroutine converttohepmc (J, EVNUM, PID, beam1, beam2)
subroutine printlogo (fid)
subroutine printtime
Function/Subroutine Documentation
DOUBLE PRECISION function alphas (double precision T, double precision LAMBDA)
Definition at line 5766 of file jewel-2.2.0.f.
View newest version in sPHENIX GitHub at line 5766 of file jewel-2.2.0.f
References RawTowerContainer::compress(), Acts::Logger::log(), ActsFatras::LandauDistribution::param(), pi, and t.
Referenced by LBT::alphasHQ(), deriv(), Matter::DoEnergyLoss(), doinstatescat(), Matter::fillQhatTab(), getmass(), gett(), Matter::Init(), LBT::Init(), LBT::LBT0(), Matter::Matter(), Matter::ModifiedProbability(), pystbh(), pytbbc(), pytbbn(), pytbhb(), pytbhg(), pytbhq(), pyxued(), and Matter::RunningAlphaS().
subroutine cleanup (integer NFIRST)
Definition at line 2001 of file jewel-2.2.0.f.
View newest version in sPHENIX GitHub at line 2001 of file jewel-2.2.0.f
References i, j, k, n, npad, p, pyjets, and v.
Referenced by RunToTimePg::getRunNumber(), handle_this_child(), main(), makestrings_minl(), makestrings_vac(), mg_http_common_url_parse(), and mg_send_dns_query().
logical function compressevent (integer l1)
Definition at line 6512 of file jewel-2.2.0.f.
View newest version in sPHENIX GitHub at line 6512 of file jewel-2.2.0.f
References false, i, j, k, n, npad, p, pyjets, true, and v.
Referenced by makebranch(), makestrings_minl(), and makestrings_vac().
subroutine converttohepmc (integer J, integer EVNUM, integer PID, character*2 beam1, character*2 beam2)
Definition at line 6640 of file jewel-2.2.0.f.
View newest version in sPHENIX GitHub at line 6640 of file jewel-2.2.0.f
References channel(), RawTowerContainer::compress(), i, ValueGen1::i2(), ValueGen1::i3(), ishadron(), isparton(), isprimhadron(), isprimstring(), issecstring(), j, k, msti, mstp, n, npad, npart(), offset, p, ActsFatras::LandauDistribution::param(), pari, parp, pyjets, pypars, and v.
Referenced by genevent().
DOUBLE PRECISION function deriv (double precision XVAL, integer W4)
Definition at line 4430 of file jewel-2.2.0.f.
View newest version in sPHENIX GitHub at line 4430 of file jewel-2.2.0.f
References alphas(), RawTowerContainer::compress(), getinspliti(), getinsudafast(), getspliti(), medderiv(), ActsFatras::LandauDistribution::param(), pgg(), pgq(), pi, pqg(), pqq(), scatprimfunc(), t, xmax, and z.
Referenced by MakeMilleFiles::getLocalVtxDerivativesXY(), getproba(), odeint(), pypole(), rk4step(), and rkstepper().
subroutine dofistatescat (integer L, double precision TNOW, double precision DTLEFT, double precision DELTAT, double precision NEWMASS, logical OVERQ0, double precision Z, logical QQBAR)
Definition at line 3284 of file jewel-2.2.0.f.
View newest version in sPHENIX GitHub at line 3284 of file jewel-2.2.0.f
References MARTINIUserInfo::coherent(), RawTowerContainer::compress(), false, getdeltat(), getnewmass(), getqvec(), k, Acts::Logger::log(), ActsExamples::PlotHelpers::Binning::low(), n, npad, p, ActsFatras::LandauDistribution::param(), phi, pyjets, pyp(), pyr(), true, v, and z.
Referenced by makebranch().
subroutine doinstatescat (integer L, double precision X, integer TYPI, double precision Q, double precision TSTART, double precision DELTAT, logical OVERQ0, logical RETRYSPLIT)
Definition at line 2882 of file jewel-2.2.0.f.
View newest version in sPHENIX GitHub at line 2882 of file jewel-2.2.0.f
References alphas(), MARTINIUserInfo::coherent(), RawTowerContainer::compress(), PHTFileServer::SafeTFile::counter(), ValueGen1::dt(), false, generatez(), getdeltat(), getmd(), getms(), getneff(), getnewmass(), getpdf(), getpnorad1(), getqvec(), getsscat(), gettemp(), k, Acts::Logger::log(), ActsExamples::PlotHelpers::Binning::low(), n, npad, p, ActsFatras::LandauDistribution::param(), pgg(), pgq(), phi, pi, pqg(), pqq(), pyjets, pyp(), pyr(), Fatras::Test::Particle::q(), sign(), true, v, Acts::MultiEigenStepperLoop< extensionlist_t, component_reducer_t, auctioneer_t >::ComponentProxyBase< component_t >::weight(), x, and xmax.
Referenced by makebranch().
subroutine dokinematics (integer L, integer lold, integer N1, integer N2, double precision NEWM, logical RETRYSPLIT, double precision TIME, double precision X, double precision Z, logical QQBAR)
Definition at line 3790 of file jewel-2.2.0.f.
View newest version in sPHENIX GitHub at line 3790 of file jewel-2.2.0.f
References Fatras::Test::Particle::beta(), MARTINIUserInfo::coherent(), RawTowerContainer::compress(), Acts::Frustum< value_t, DIM, SIDES >::dir(), false, gettemp(), j, k, line, Acts::Logger::log(), Acts::detail::PhiBoundParameterLimits::max(), n, npad, p, ActsFatras::LandauDistribution::param(), phi, pi, Jetscape::JetScapeParticleBase::pl(), pt, PseudoJet::pt2(), pyjets, pyp(), pyr(), pyrobo(), sign(), t, true, v, Acts::MultiEigenStepperLoop< extensionlist_t, component_reducer_t, auctioneer_t >::ComponentProxyBase< component_t >::weight(), x, and z.
Referenced by makebranch().
DOUBLE PRECISION function ei (double precision X)
Definition at line 5667 of file jewel-2.2.0.f.
View newest version in sPHENIX GitHub at line 5667 of file jewel-2.2.0.f
References e, k, line, Acts::detail::PhiBoundParameterLimits::max(), x, and y.
Referenced by AdSCFT::DoEnergyLoss(), eix(), eixint(), getinspliti(), intpqghigh(), intpqglow(), ActsExamples::measurementConstituents(), pycjdc(), pyglui(), pyhext(), pyhiresd(), pyhisigh(), pyhiwidt(), pynjdc(), pyptfs(), pyresd(), pysfdc(), pysgex(), pysghg(), pysgqc(), pysgsu(), pysgtc(), pysgwz(), pyshow(), pytbdy(), pywidt(), scatprimfunc(), and testing::internal::UnorderedElementsAreMatcherImplBase::VerifyAllElementsAndMatchersAreMatched().
subroutine eixint ()
Definition at line 6062 of file jewel-2.2.0.f.
View newest version in sPHENIX GitHub at line 6062 of file jewel-2.2.0.f
References ei(), go(), i, k, odeint(), r, genfit::GFRavePropagator::to(), and x.
Referenced by init().
DOUBLE PRECISION function generatez (double precision TI, double precision EA, double precision EPSI, character*2 TYPE)
Definition at line 5451 of file jewel-2.2.0.f.
View newest version in sPHENIX GitHub at line 5451 of file jewel-2.2.0.f
References RawTowerContainer::compress(), eps, Acts::detail::PhiBoundParameterLimits::max(), ActsFatras::LandauDistribution::param(), pyr(), r, r1, and x.
Referenced by doinstatescat(), makesplitting(), and makestrings_minl().
subroutine genevent (integer j, character*2 b1, character*2 b2)
Definition at line 983 of file jewel-2.2.0.f.
View newest version in sPHENIX GitHub at line 983 of file jewel-2.2.0.f
References b1, Fatras::Test::Particle::beta(), channel(), RawTowerContainer::compress(), converttohepmc(), etamax, false, getltimemax(), getmass(), i, isdiquark(), j, k, Acts::Logger::log(), makecascade(), makestrings(), Acts::detail::PhiBoundParameterLimits::max(), mednextevt(), msti, mstp, n, npad, npart(), offset, p, ActsFatras::LandauDistribution::param(), pari, parp, pi, pickvtx(), pydat1, pydat3, pydatr, pyevnt(), pyexec(), pyjets, pyp(), pypars, pyr(), pyrobo(), pysubs, true, v, Acts::MultiEigenStepperLoop< extensionlist_t, component_reducer_t, auctioneer_t >::ComponentProxyBase< component_t >::weight(), and x0.
Referenced by Fun4AllDstPileupMerger::copy_background_event(), EpFinderEval::fill_tree(), PHHepMCGenHelper::insert_event(), Fun4AllHepMCPileupInputManager::InsertEvent(), jewel(), PHSartre::process_event(), and PHPythia8::process_event().
LOGICAL function getdeltat (integer LINE, double precision TSTART, double precision DTMAX1, double precision DELTAT)
Definition at line 6222 of file jewel-2.2.0.f.
View newest version in sPHENIX GitHub at line 6222 of file jewel-2.2.0.f
References RawTowerContainer::compress(), etamax, false, getmd(), getmdmax(), getmdmin(), getms(), getmsmax(), getnatmdmin(), getneff(), getneffmax(), getsscat(), i, k, line, Acts::Logger::log(), Acts::detail::PhiBoundParameterLimits::max(), n, npad, p, ActsFatras::LandauDistribution::param(), pyjets, pyr(), r, sigma, tau, true, ValueGen1::ts(), v, and Acts::MultiEigenStepperLoop< extensionlist_t, component_reducer_t, auctioneer_t >::ComponentProxyBase< component_t >::weight().
Referenced by dofistatescat(), and doinstatescat().
DOUBLE PRECISION function getinspliti (double precision QB, character*2 TYPE1)
Definition at line 4673 of file jewel-2.2.0.f.
View newest version in sPHENIX GitHub at line 4673 of file jewel-2.2.0.f
References RawTowerContainer::compress(), ei(), Acts::Logger::log(), ActsExamples::PlotHelpers::Binning::low(), ActsFatras::LandauDistribution::param(), pi, and y.
Referenced by deriv(), and getmass().
DOUBLE PRECISION function getinsudafast (double precision Q1, double precision Q2, character*2 TYP)
Definition at line 5071 of file jewel-2.2.0.f.
View newest version in sPHENIX GitHub at line 5071 of file jewel-2.2.0.f
References RawTowerContainer::compress(), getinsudared(), and ActsFatras::LandauDistribution::param().
Referenced by deriv(), and getsudakov().
DOUBLE PRECISION function getinsudakov (double precision QB, double precision QMAX1, character*2 TYPE3)
Definition at line 4390 of file jewel-2.2.0.f.
View newest version in sPHENIX GitHub at line 4390 of file jewel-2.2.0.f
References RawTowerContainer::compress(), odeint(), ActsFatras::LandauDistribution::param(), and t.
Referenced by insudaint().
DOUBLE PRECISION function getinsudared (double precision Q, character*2 TYP2)
Definition at line 5105 of file jewel-2.2.0.f.
View newest version in sPHENIX GitHub at line 5105 of file jewel-2.2.0.f
References RawTowerContainer::compress(), i, Acts::Logger::log(), Acts::detail::PhiBoundParameterLimits::max(), ActsFatras::LandauDistribution::param(), Fatras::Test::Particle::q(), and y.
Referenced by getinsudafast().
DOUBLE PRECISION function getmass (double precision QBMIN, double precision QBMAX, double precision THETA, double precision EP, character*2 TYPE, double precision MAX2, logical INS, double precision ZDEC, logical QQBARDEC)
Definition at line 5275 of file jewel-2.2.0.f.
View newest version in sPHENIX GitHub at line 5275 of file jewel-2.2.0.f
References alphas(), RawTowerContainer::compress(), e, eps, false, getinspliti(), gmax, gmin(), k, Acts::Logger::log(), n, npad, p, ActsFatras::LandauDistribution::param(), pgg(), pi, pqg(), pqq(), pydat1, pydat3, pyjets, pyr(), r, r2, true, v, Acts::MultiEigenStepperLoop< extensionlist_t, component_reducer_t, auctioneer_t >::ComponentProxyBase< component_t >::weight(), and z.
Referenced by genevent(), getnewmass(), makebranch(), makeinsplit(), and makesplitting().
DOUBLE PRECISION function getnewmass (integer L, double precision Q2, double precision QOLD2, double precision MASS, logical IN, double precision X, double precision ZDEC, logical QQBARDEC)
Definition at line 3445 of file jewel-2.2.0.f.
View newest version in sPHENIX GitHub at line 3445 of file jewel-2.2.0.f
References RawTowerContainer::compress(), false, getmass(), getsudakov(), in, k, mass, Acts::detail::PhiBoundParameterLimits::max(), n, npad, p, ActsFatras::LandauDistribution::param(), pyjets, pyr(), v, x, and z.
Referenced by dofistatescat(), and doinstatescat().
DOUBLE PRECISION function getpdf (double precision X, double precision Q, character*2 TYP)
Definition at line 4761 of file jewel-2.2.0.f.
View newest version in sPHENIX GitHub at line 4761 of file jewel-2.2.0.f
References RawTowerContainer::compress(), Acts::detail::PhiBoundParameterLimits::max(), odeint(), ActsFatras::LandauDistribution::param(), Fatras::Test::Particle::q(), x, xmax, and z.
Referenced by doinstatescat().
DOUBLE PRECISION function getpdfxint (double precision Q, character*2 TYP)
Definition at line 4857 of file jewel-2.2.0.f.
View newest version in sPHENIX GitHub at line 4857 of file jewel-2.2.0.f
References j, Acts::Logger::log(), Acts::detail::PhiBoundParameterLimits::max(), Fatras::Test::Particle::q(), and y.
Referenced by getsscat().
DOUBLE PRECISION function getpdfxintexact (double precision Q, character*2 TYP)
Definition at line 4926 of file jewel-2.2.0.f.
View newest version in sPHENIX GitHub at line 4926 of file jewel-2.2.0.f
References RawTowerContainer::compress(), odeint(), ActsFatras::LandauDistribution::param(), Fatras::Test::Particle::q(), xmax, and z.
Referenced by pdfint().
DOUBLE PRECISION function getpnorad1 (integer LINE, double precision x, double precision y, double precision z, double precision t)
Definition at line 3555 of file jewel-2.2.0.f.
View newest version in sPHENIX GitHub at line 3555 of file jewel-2.2.0.f
References avscatcen(), RawTowerContainer::compress(), getmd(), getsscat(), getxsecint(), k, line, ActsExamples::PlotHelpers::Binning::low(), n, npad, p, ActsFatras::LandauDistribution::param(), pyjets, scatprimfunc(), t, v, x, y, and z.
Referenced by doinstatescat().
DOUBLE PRECISION function getproba (double precision QI, double precision QF, double precision QAA, double precision ZAA, double precision EBB, character*2 TYPE, double precision T1, logical INS2)
Definition at line 4307 of file jewel-2.2.0.f.
View newest version in sPHENIX GitHub at line 4307 of file jewel-2.2.0.f
References deriv(), getsudakov(), t, and t1().
subroutine getqvec (integer L, integer J, double precision DT, double precision X)
Definition at line 3623 of file jewel-2.2.0.f.
View newest version in sPHENIX GitHub at line 3623 of file jewel-2.2.0.f
References avscatcen(), Fatras::Test::Particle::beta(), MARTINIUserInfo::coherent(), RawTowerContainer::compress(), PHTFileServer::SafeTFile::counter(), ValueGen1::dt(), getmd(), getms(), getscatterer(), gett(), i, j, k, PseudoJet::kt2(), Acts::detail::PhiBoundParameterLimits::max(), n, npad, p, ActsFatras::LandauDistribution::param(), phi, pi, pt, PseudoJet::pt2(), pyjets, pyp(), pyr(), pyrobo(), PseudoJet::pz(), t, true, v, and x.
Referenced by dofistatescat(), and doinstatescat().
DOUBLE PRECISION function getspliti (double precision QA, double precision QB, double precision ZETA, double precision EB, character*2 TYPE1)
Definition at line 4531 of file jewel-2.2.0.f.
View newest version in sPHENIX GitHub at line 4531 of file jewel-2.2.0.f
References RawTowerContainer::compress(), i, j, Acts::Logger::log(), ActsExamples::PlotHelpers::Binning::low(), Acts::detail::PhiBoundParameterLimits::max(), ActsFatras::LandauDistribution::param(), and y.
Referenced by deriv().
DOUBLE PRECISION function getsscat (double precision EN, double precision px, double precision py, double precision PZ, double precision MP, double precision LW, character TYPE1, character TYPE2, double precision x, double precision y, double precision z, double precision t, integer mode)
Definition at line 5183 of file jewel-2.2.0.f.
View newest version in sPHENIX GitHub at line 5183 of file jewel-2.2.0.f
References avscatcen(), RawTowerContainer::compress(), getmd(), getmdmax(), getmdmin(), getpdfxint(), gettemp(), getxsecint(), ActsExamples::PlotHelpers::Binning::low(), Acts::detail::PhiBoundParameterLimits::max(), maxscatcen(), ActsFatras::LandauDistribution::param(), PseudoJet::px(), PseudoJet::py(), PseudoJet::pz(), scatprimfunc(), t, x, y, and z.
Referenced by doinstatescat(), getdeltat(), and getpnorad1().
DOUBLE PRECISION function getsudakov (double precision QMAX1, double precision QA1, double precision QB1, double precision ZA1, double precision EB1, character*2 TYPE3, double precision T2, logical INS)
Definition at line 4334 of file jewel-2.2.0.f.
View newest version in sPHENIX GitHub at line 4334 of file jewel-2.2.0.f
References RawTowerContainer::compress(), false, getinsudafast(), odeint(), ActsFatras::LandauDistribution::param(), and t.
Referenced by getnewmass(), and getproba().
DOUBLE PRECISION function gett (double precision MINT, double precision MAXT, double precision MDEB)
Definition at line 5632 of file jewel-2.2.0.f.
View newest version in sPHENIX GitHub at line 5632 of file jewel-2.2.0.f
References alphas(), RawTowerContainer::compress(), mint, ActsFatras::LandauDistribution::param(), pi, pyr(), r1, r2, and t.
Referenced by getqvec().
DOUBLE PRECISION function getxsecint (double precision TM, double precision MD, character*2 TYP2)
Definition at line 4962 of file jewel-2.2.0.f.
View newest version in sPHENIX GitHub at line 4962 of file jewel-2.2.0.f
References RawTowerContainer::compress(), i, j, Acts::Logger::log(), Acts::detail::PhiBoundParameterLimits::max(), ActsFatras::LandauDistribution::param(), tline, and y.
Referenced by getpnorad1(), and getsscat().
subroutine init ()
Definition at line 290 of file jewel-2.2.0.f.
View newest version in sPHENIX GitHub at line 290 of file jewel-2.2.0.f
References channel(), RawTowerContainer::compress(), eix(), eixint(), etamax, ParameterReader::exist(), false, file, filename, i, insudaint(), j, k, mass, medinit(), mednextevt(), msti, mstp, n, HiMain1::np(), npad, npart(), offset, p, ActsFatras::LandauDistribution::param(), pari, parp, noiPads::pdf(), pdfint(), pdfset(), pos, printlogo(), printtime(), pydat1, pydat3, pydatr, pyjets, pypars, pyr(), pysubs, r, splitfncint(), true, v, value, Acts::MultiEigenStepperLoop< extensionlist_t, component_reducer_t, auctioneer_t >::ComponentProxyBase< component_t >::weight(), and xsecint().
subroutine initpythia (character*2 beam1, character*2 beam2)
Definition at line 783 of file jewel-2.2.0.f.
View newest version in sPHENIX GitHub at line 783 of file jewel-2.2.0.f
References channel(), RawTowerContainer::compress(), k, mass, Acts::detail::PhiBoundParameterLimits::max(), msti, mstp, n, npad, npart(), offset, p, ActsFatras::LandauDistribution::param(), pari, parp, noiPads::pdf(), pdfset(), pycomp, pydat1, pydat3, pydatr, pyinit(), pyjets, pypars, pysubs, v, and Acts::MultiEigenStepperLoop< extensionlist_t, component_reducer_t, auctioneer_t >::ComponentProxyBase< component_t >::weight().
Referenced by jewel().
subroutine insudaint (double precision EMAX)
Definition at line 6018 of file jewel-2.2.0.f.
View newest version in sPHENIX GitHub at line 6018 of file jewel-2.2.0.f
References RawTowerContainer::compress(), etamax, getinsudakov(), i, Acts::Logger::log(), maxscatcen(), ActsFatras::LandauDistribution::param(), and Fatras::Test::Particle::q().
Referenced by init().
DOUBLE PRECISION function intpgghigh (double precision Z, double precision Q)
Definition at line 5569 of file jewel-2.2.0.f.
View newest version in sPHENIX GitHub at line 5569 of file jewel-2.2.0.f
References RawTowerContainer::compress(), Acts::Logger::log(), ActsFatras::LandauDistribution::param(), Fatras::Test::Particle::q(), and z.
DOUBLE PRECISION function intpgglow (double precision Z, double precision Q)
Definition at line 5550 of file jewel-2.2.0.f.
View newest version in sPHENIX GitHub at line 5550 of file jewel-2.2.0.f
References RawTowerContainer::compress(), Acts::Logger::log(), ActsFatras::LandauDistribution::param(), Fatras::Test::Particle::q(), and z.
DOUBLE PRECISION function intpqghigh (double precision Z, double precision Q)
Definition at line 5610 of file jewel-2.2.0.f.
View newest version in sPHENIX GitHub at line 5610 of file jewel-2.2.0.f
References RawTowerContainer::compress(), ei(), Acts::Logger::log(), ActsFatras::LandauDistribution::param(), Fatras::Test::Particle::q(), and z.
DOUBLE PRECISION function intpqglow (double precision Z, double precision Q)
Definition at line 5588 of file jewel-2.2.0.f.
View newest version in sPHENIX GitHub at line 5588 of file jewel-2.2.0.f
References RawTowerContainer::compress(), ei(), Acts::Logger::log(), ActsFatras::LandauDistribution::param(), Fatras::Test::Particle::q(), and z.
DOUBLE PRECISION function intpqq (double precision Z, double precision Q)
Definition at line 5530 of file jewel-2.2.0.f.
View newest version in sPHENIX GitHub at line 5530 of file jewel-2.2.0.f
References RawTowerContainer::compress(), Acts::Logger::log(), ActsFatras::LandauDistribution::param(), Fatras::Test::Particle::q(), and z.
LOGICAL function isdiquark (integer ID)
Definition at line 6388 of file jewel-2.2.0.f.
View newest version in sPHENIX GitHub at line 6388 of file jewel-2.2.0.f
References false, id, and true.
Referenced by genevent(), isparton(), and makestrings_vac().
LOGICAL function ishadron (integer ID)
Definition at line 6368 of file jewel-2.2.0.f.
View newest version in sPHENIX GitHub at line 6368 of file jewel-2.2.0.f
References false, id, and true.
Referenced by converttohepmc().
LOGICAL function islepton (integer ID)
Definition at line 6406 of file jewel-2.2.0.f.
View newest version in sPHENIX GitHub at line 6406 of file jewel-2.2.0.f
References false, id, and true.
LOGICAL function isparton (integer ID)
Definition at line 6420 of file jewel-2.2.0.f.
View newest version in sPHENIX GitHub at line 6420 of file jewel-2.2.0.f
References false, id, isdiquark(), and true.
Referenced by converttohepmc(), isprimhadron(), isprimstring(), and issecstring().
logical function isprimhadron (integer l)
Definition at line 6489 of file jewel-2.2.0.f.
View newest version in sPHENIX GitHub at line 6489 of file jewel-2.2.0.f
References false, isparton(), isprimstring(), k, n, npad, p, pyjets, true, and v.
Referenced by converttohepmc().
logical function isprimstring (integer l)
Definition at line 6437 of file jewel-2.2.0.f.
View newest version in sPHENIX GitHub at line 6437 of file jewel-2.2.0.f
References false, isparton(), k, n, npad, p, pyjets, true, and v.
Referenced by converttohepmc(), isprimhadron(), and issecstring().
logical function issecstring (integer l)
Definition at line 6461 of file jewel-2.2.0.f.
View newest version in sPHENIX GitHub at line 6461 of file jewel-2.2.0.f
References false, isparton(), isprimstring(), k, n, npad, p, pyjets, true, and v.
Referenced by converttohepmc().
program jewel ()
Definition at line 61 of file jewel-2.2.0.f.
View newest version in sPHENIX GitHub at line 61 of file jewel-2.2.0.f
References b1, channel(), genevent(), init(), initpythia(), j, k, mass, msti, mstp, n, HiMain1::np(), npad, npart(), offset, p, pari, parp, poissonian(), printtime(), pydat1, pydat3, pydatr, pyjets, pypars, pysubs, v, and Acts::MultiEigenStepperLoop< extensionlist_t, component_reducer_t, auctioneer_t >::ComponentProxyBase< component_t >::weight().
subroutine makebranch (integer L)
Definition at line 2069 of file jewel-2.2.0.f.
View newest version in sPHENIX GitHub at line 2069 of file jewel-2.2.0.f
References MARTINIUserInfo::coherent(), RawTowerContainer::compress(), compressevent(), dofistatescat(), doinstatescat(), dokinematics(), false, getmass(), getms(), k, line, makeinsplit(), makesplitting(), Acts::detail::PhiBoundParameterLimits::max(), n, npad, p, ActsFatras::LandauDistribution::param(), phi, pyjets, pyp(), pyrobo(), Fatras::Test::Particle::q(), true, v, Acts::MultiEigenStepperLoop< extensionlist_t, component_reducer_t, auctioneer_t >::ComponentProxyBase< component_t >::weight(), and x.
Referenced by makecascade().
subroutine makecascade ()
Definition at line 2026 of file jewel-2.2.0.f.
View newest version in sPHENIX GitHub at line 2026 of file jewel-2.2.0.f
References RawTowerContainer::compress(), false, i, k, makebranch(), n, npad, p, ActsFatras::LandauDistribution::param(), pyjets, true, and v.
Referenced by genevent().
subroutine makeinsplit (integer L, double precision X, double precision TSUM, double precision VIRT, integer TYPI, double precision TIME, double precision TAURAD)
Definition at line 2628 of file jewel-2.2.0.f.
View newest version in sPHENIX GitHub at line 2628 of file jewel-2.2.0.f
References RawTowerContainer::compress(), Acts::Frustum< value_t, DIM, SIDES >::dir(), false, getmass(), k, PseudoJet::kt2(), Acts::Logger::log(), Acts::detail::PhiBoundParameterLimits::max(), n, npad, p, ActsFatras::LandauDistribution::param(), phi, pi, pyjets, pyp(), pyr(), pyrobo(), PseudoJet::pz(), r, true, v, Acts::MultiEigenStepperLoop< extensionlist_t, component_reducer_t, auctioneer_t >::ComponentProxyBase< component_t >::weight(), and x.
Referenced by makebranch().
subroutine makesplitting (integer L)
Definition at line 2353 of file jewel-2.2.0.f.
View newest version in sPHENIX GitHub at line 2353 of file jewel-2.2.0.f
References RawTowerContainer::compress(), Acts::Frustum< value_t, DIM, SIDES >::dir(), eps, false, generatez(), getmass(), gettemp(), k, Acts::Logger::log(), n, npad, p, ActsFatras::LandauDistribution::param(), pi, pyjets, pylist(), pyr(), PseudoJet::pz(), r, true, v, Acts::MultiEigenStepperLoop< extensionlist_t, component_reducer_t, auctioneer_t >::ComponentProxyBase< component_t >::weight(), and z.
Referenced by makebranch().
subroutine makestrings (integer WHICH)
Definition at line 1513 of file jewel-2.2.0.f.
View newest version in sPHENIX GitHub at line 1513 of file jewel-2.2.0.f
References makestrings_minl(), and makestrings_vac().
Referenced by genevent().
subroutine makestrings_minl ()
Definition at line 1762 of file jewel-2.2.0.f.
View newest version in sPHENIX GitHub at line 1762 of file jewel-2.2.0.f
References cleanup(), RawTowerContainer::compress(), compressevent(), Acts::Frustum< value_t, DIM, SIDES >::dir(), generatez(), i, j, k, n, npad, p, ActsFatras::LandauDistribution::param(), pyjets, pyp(), pyr(), true, v, and z.
Referenced by makestrings().
subroutine makestrings_vac ()
Definition at line 1532 of file jewel-2.2.0.f.
View newest version in sPHENIX GitHub at line 1532 of file jewel-2.2.0.f
References cleanup(), RawTowerContainer::compress(), compressevent(), i, isdiquark(), j, k, n, npad, p, ActsFatras::LandauDistribution::param(), pyjets, true, and v.
Referenced by makestrings().
subroutine odeint (double precision ystart, double precision a, double precision b, double precision eps, double precision h1, double precision hmin, integer w1)
Definition at line 6114 of file jewel-2.2.0.f.
View newest version in sPHENIX GitHub at line 6114 of file jewel-2.2.0.f
References deriv(), e, eps, h, h1, rkstepper(), sign(), x, and y.
Referenced by calcta(), eixint(), getinsudakov(), getpdf(), getpdfxintexact(), getsudakov(), splitfncint(), and xsecint().
subroutine pdfint (double precision EMAX)
Definition at line 5871 of file jewel-2.2.0.f.
View newest version in sPHENIX GitHub at line 5871 of file jewel-2.2.0.f
References RawTowerContainer::compress(), etamax, getpdfxintexact(), j, Acts::Logger::log(), maxscatcen(), ActsFatras::LandauDistribution::param(), xmax, and z.
Referenced by init().
subroutine pevrec (integer NUM, logical COL)
Definition at line 6600 of file jewel-2.2.0.f.
View newest version in sPHENIX GitHub at line 6600 of file jewel-2.2.0.f
References col, i, k, n, npad, HybridHadronization::parton_collection::num(), p, pyjets, pylist(), and v.
DOUBLE PRECISION function pgg (double precision Z)
Definition at line 5744 of file jewel-2.2.0.f.
View newest version in sPHENIX GitHub at line 5744 of file jewel-2.2.0.f
References z.
Referenced by deriv(), doinstatescat(), and getmass().
DOUBLE PRECISION function pgq (double precision Z)
Definition at line 5733 of file jewel-2.2.0.f.
View newest version in sPHENIX GitHub at line 5733 of file jewel-2.2.0.f
References z.
Referenced by deriv(), and doinstatescat().
integer function poissonian (double precision lambda)
Definition at line 6340 of file jewel-2.2.0.f.
View newest version in sPHENIX GitHub at line 6340 of file jewel-2.2.0.f
References Acts::Logger::log(), n, p, pi, pyr(), and v.
Referenced by jewel().
DOUBLE PRECISION function pqg (double precision Z)
Definition at line 5755 of file jewel-2.2.0.f.
View newest version in sPHENIX GitHub at line 5755 of file jewel-2.2.0.f
References z.
Referenced by deriv(), doinstatescat(), and getmass().
DOUBLE PRECISION function pqq (double precision Z)
Definition at line 5722 of file jewel-2.2.0.f.
View newest version in sPHENIX GitHub at line 5722 of file jewel-2.2.0.f
References z.
Referenced by deriv(), doinstatescat(), and getmass().
subroutine printlogo (integer fid)
Definition at line 6940 of file jewel-2.2.0.f.
View newest version in sPHENIX GitHub at line 6940 of file jewel-2.2.0.f
References fid.
Referenced by init().
subroutine printtime ()
Definition at line 7021 of file jewel-2.2.0.f.
View newest version in sPHENIX GitHub at line 7021 of file jewel-2.2.0.f
References ValueGen1::i2(), and ValueGen1::i4().
Referenced by init(), and jewel().
double precision function rk4step (double precision x, double precision y, double precision dydx, double precision h, integer w1)
Definition at line 6206 of file jewel-2.2.0.f.
View newest version in sPHENIX GitHub at line 6206 of file jewel-2.2.0.f
References deriv(), h, Acts::StepperExtensionList< extensions >::k1(), Acts::SolenoidBField::k2(), Acts::StepperExtensionList< extensions >::k4(), x, and y.
Referenced by rkstepper().
subroutine rkstepper (double precision x, double precision y, double precision dydx, double precision htest, double precision hdid, double precision hnew, double precision yscale, double precision eps, integer w1)
Definition at line 6153 of file jewel-2.2.0.f.
View newest version in sPHENIX GitHub at line 6153 of file jewel-2.2.0.f
References deriv(), eps, false, h, Acts::detail::PhiBoundParameterLimits::max(), hLabHelper::reject(), rk4step(), true, x, and y.
Referenced by odeint().
DOUBLE PRECISION function scatprimfunc (double precision T, double precision MDEB)
Definition at line 5508 of file jewel-2.2.0.f.
View newest version in sPHENIX GitHub at line 5508 of file jewel-2.2.0.f
References RawTowerContainer::compress(), ei(), Acts::Logger::log(), ActsFatras::LandauDistribution::param(), pi, and t.
Referenced by deriv(), getpnorad1(), and getsscat().
subroutine splitfncint (double precision EMAX)
Definition at line 5786 of file jewel-2.2.0.f.
View newest version in sPHENIX GitHub at line 5786 of file jewel-2.2.0.f
References RawTowerContainer::compress(), etamax, getmsmax(), i, j, Acts::Logger::log(), Acts::detail::PhiBoundParameterLimits::max(), maxscatcen(), odeint(), ActsFatras::LandauDistribution::param(), and Fatras::Test::Particle::q().
Referenced by init().
subroutine xsecint (double precision EMAX)
Definition at line 5928 of file jewel-2.2.0.f.
View newest version in sPHENIX GitHub at line 5928 of file jewel-2.2.0.f
References RawTowerContainer::compress(), etamax, getmdmax(), getmdmin(), getmsmax(), j, k, Acts::Logger::log(), Acts::detail::PhiBoundParameterLimits::max(), maxscatcen(), odeint(), and ActsFatras::LandauDistribution::param().
Referenced by init().