Analysis Software: TrackingIterationCounter Class Reference
TrackingIterationCounter Class Reference
#include <coresoftware/blob/master/offline/packages/trackreco/TrackingIterationCounter.h>
Public Member Functions
TrackingIterationCounter (const std::string &name="TrackingIterationCounter")
~TrackingIterationCounter () override
int Init (PHCompositeNode *topNode) override
int InitRun (PHCompositeNode *topNode) override
int process_event (PHCompositeNode *topNode) override
int End (PHCompositeNode *topNode) override
Called at the end of all processing.
void iteration (const short int iter)
Public Member Functions inherited from SubsysReco
~SubsysReco () override
virtual int EndRun (const int)
Called at the end of each run.
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
void Print (const std::string &="ALL") const override
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Private Member Functions
int getNodes (PHCompositeNode *topNode)
int createNodes (PHCompositeNode *topNode)
void addClustersToIterationMap (TrackSeed *seed)
Private Attributes
short int m_iteration = 1
SvtxTrackMap * m_trackMap = nullptr
TrkrClusterIterationMap * m_iterMap = nullptr
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = std::numeric_limits<int>::max() - 10
}
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Detailed Description
Definition at line 15 of file TrackingIterationCounter.h.
View newest version in sPHENIX GitHub at line 15 of file TrackingIterationCounter.h
Constructor & Destructor Documentation
TrackingIterationCounter::TrackingIterationCounter (const std::string & name = "TrackingIterationCounter")
Definition at line 20 of file TrackingIterationCounter.cc.
View newest version in sPHENIX GitHub at line 20 of file TrackingIterationCounter.cc
TrackingIterationCounter::~TrackingIterationCounter () override
Definition at line 26 of file TrackingIterationCounter.cc.
View newest version in sPHENIX GitHub at line 26 of file TrackingIterationCounter.cc
Member Function Documentation
void TrackingIterationCounter::addClustersToIterationMap (TrackSeed * seed) private
Definition at line 69 of file TrackingIterationCounter.cc.
View newest version in sPHENIX GitHub at line 69 of file TrackingIterationCounter.cc
References TrkrClusterIterationMap::addIteration(), TrackSeed::begin_cluster_keys(), TrackSeed::end_cluster_keys(), m_iteration, and m_iterMap.
Referenced by process_event().
int TrackingIterationCounter::createNodes (PHCompositeNode * topNode) private
Definition at line 85 of file TrackingIterationCounter.cc.
View newest version in sPHENIX GitHub at line 85 of file TrackingIterationCounter.cc
References PHCompositeNode::addNode(), Fun4AllReturnCodes::EVENT_OK, PHNodeIterator::findFirst(), and m_iterMap.
Referenced by InitRun().
int TrackingIterationCounter::End (PHCompositeNode *) override virtual
Called at the end of all processing.
Reimplemented from SubsysReco.
Definition at line 81 of file TrackingIterationCounter.cc.
View newest version in sPHENIX GitHub at line 81 of file TrackingIterationCounter.cc
References Fun4AllReturnCodes::EVENT_OK.
int TrackingIterationCounter::getNodes (PHCompositeNode * topNode) private
Definition at line 117 of file TrackingIterationCounter.cc.
View newest version in sPHENIX GitHub at line 117 of file TrackingIterationCounter.cc
References Fun4AllReturnCodes::ABORTEVENT, Fun4AllReturnCodes::EVENT_OK, m_trackMap, and PHWHERE.
Referenced by InitRun().
int TrackingIterationCounter::Init (PHCompositeNode *) override virtual
Called during initialization. Typically this is where you can book histograms, and e.g. register them to Fun4AllServer (so they can be output to file using Fun4AllServer::dumpHistos() method).
Reimplemented from SubsysReco.
Definition at line 31 of file TrackingIterationCounter.cc.
View newest version in sPHENIX GitHub at line 31 of file TrackingIterationCounter.cc
References Fun4AllReturnCodes::EVENT_OK.
int TrackingIterationCounter::InitRun (PHCompositeNode *) override virtual
Called for first event when run number is known. Typically this is where you may want to fetch data from database, because you know the run number.
Reimplemented from SubsysReco.
Definition at line 37 of file TrackingIterationCounter.cc.
View newest version in sPHENIX GitHub at line 37 of file TrackingIterationCounter.cc
References Fun4AllReturnCodes::ABORTEVENT, createNodes(), Fun4AllReturnCodes::EVENT_OK, and getNodes().
void TrackingIterationCounter::iteration (const short int iter) inline
Definition at line 27 of file TrackingIterationCounter.h.
View newest version in sPHENIX GitHub at line 27 of file TrackingIterationCounter.h
References m_iteration.
Referenced by Tracking_Reco_TrackSeed_pass1().
int TrackingIterationCounter::process_event (PHCompositeNode *) override virtual
Called for each event. This is where you do the real work.
Reimplemented from SubsysReco.
Definition at line 50 of file TrackingIterationCounter.cc.
View newest version in sPHENIX GitHub at line 50 of file TrackingIterationCounter.cc
References addClustersToIterationMap(), Fun4AllReturnCodes::EVENT_OK, and m_trackMap.
Member Data Documentation
short int TrackingIterationCounter::m_iteration = 1 private
Definition at line 33 of file TrackingIterationCounter.h.
View newest version in sPHENIX GitHub at line 33 of file TrackingIterationCounter.h
Referenced by addClustersToIterationMap(), and iteration().
TrkrClusterIterationMap* TrackingIterationCounter::m_iterMap = nullptr private
Definition at line 36 of file TrackingIterationCounter.h.
View newest version in sPHENIX GitHub at line 36 of file TrackingIterationCounter.h
Referenced by addClustersToIterationMap(), and createNodes().
SvtxTrackMap* TrackingIterationCounter::m_trackMap = nullptr private
Definition at line 35 of file TrackingIterationCounter.h.
View newest version in sPHENIX GitHub at line 35 of file TrackingIterationCounter.h
Referenced by getNodes(), and process_event().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/trackreco/TrackingIterationCounter.h
coresoftware/blob/master/offline/packages/trackreco/TrackingIterationCounter.cc