Analysis Software: Jetscape::FourVector Class Reference
Jetscape::FourVector Class Reference
#include <JETSCAPE/blob/main/src/framework/FourVector.h>
Public Member Functions
FourVector ()
FourVector (const FourVector &srv)
FourVector (double a[4])
FourVector (double x_in, double y_in, double z_in, double t_in)
void clear ()
void Set (double x_in, double y_in, double z_in, double t_in)
void Set (double a[4])
double x () const
double y () const
double z () const
double t () const
const double comp (int i) const
double plus ()
double minus ()
double rapidity ()
double phi ()
double operator* (FourVector &c)
FourVector & operator+= (FourVector &c)
FourVector & operator-= (FourVector &c)
FourVector & operator= (FourVector &c)
FourVector & operator= (const FourVector &c)
void rotate_around_z (double theta)
Private Attributes
double xv
double yv
double zv
double tv
Detailed Description
Definition at line 31 of file FourVector.h.
View newest version in sPHENIX GitHub at line 31 of file FourVector.h
Constructor & Destructor Documentation
Jetscape::FourVector::FourVector () inline
Definition at line 35 of file FourVector.h.
View newest version in sPHENIX GitHub at line 35 of file FourVector.h
References tv, xv, yv, and zv.
Jetscape::FourVector::FourVector (const FourVector & srv) inline
Definition at line 40 of file FourVector.h.
View newest version in sPHENIX GitHub at line 40 of file FourVector.h
Jetscape::FourVector::FourVector (double a[4]) inline
Definition at line 43 of file FourVector.h.
View newest version in sPHENIX GitHub at line 43 of file FourVector.h
References tv, xv, yv, and zv.
Jetscape::FourVector::FourVector (double x_in, double y_in, double z_in, double t_in) inline
Definition at line 51 of file FourVector.h.
View newest version in sPHENIX GitHub at line 51 of file FourVector.h
References tv, xv, yv, and zv.
Member Function Documentation
void Jetscape::FourVector::clear () inline
Definition at line 60 of file FourVector.h.
View newest version in sPHENIX GitHub at line 60 of file FourVector.h
References tv, xv, yv, and zv.
const double Jetscape::FourVector::comp (int i) const inline
Definition at line 87 of file FourVector.h.
View newest version in sPHENIX GitHub at line 87 of file FourVector.h
References Jetscape::a_very_large_number, tv, xv, yv, and zv.
Referenced by Jetscape::JetScapeParticleBase::pl(), and Jetscape::Parton::set_t().
double Jetscape::FourVector::minus () inline
Definition at line 110 of file FourVector.h.
View newest version in sPHENIX GitHub at line 110 of file FourVector.h
References tv, and zv.
Referenced by rapidity().
double Jetscape::FourVector::operator* (FourVector & c) inline
Definition at line 131 of file FourVector.h.
View newest version in sPHENIX GitHub at line 131 of file FourVector.h
References t(), tv, x(), xv, y(), yv, z(), and zv.
FourVector& Jetscape::FourVector::operator+= (FourVector & c) inline
Definition at line 135 of file FourVector.h.
View newest version in sPHENIX GitHub at line 135 of file FourVector.h
References t(), tv, x(), xv, y(), yv, z(), and zv.
FourVector& Jetscape::FourVector::operator-= (FourVector & c) inline
Definition at line 144 of file FourVector.h.
View newest version in sPHENIX GitHub at line 144 of file FourVector.h
References t(), tv, x(), xv, y(), yv, z(), and zv.
FourVector& Jetscape::FourVector::operator= (FourVector & c) inline
Definition at line 153 of file FourVector.h.
View newest version in sPHENIX GitHub at line 153 of file FourVector.h
References t(), tv, x(), xv, y(), yv, z(), and zv.
FourVector& Jetscape::FourVector::operator= (const FourVector & c) inline
Definition at line 161 of file FourVector.h.
View newest version in sPHENIX GitHub at line 161 of file FourVector.h
References tv, xv, yv, and zv.
double Jetscape::FourVector::phi () inline
Definition at line 121 of file FourVector.h.
View newest version in sPHENIX GitHub at line 121 of file FourVector.h
References Jetscape::pi, Jetscape::rounding_error, x(), and y().
double Jetscape::FourVector::plus () inline
Definition at line 108 of file FourVector.h.
View newest version in sPHENIX GitHub at line 108 of file FourVector.h
References tv, and zv.
Referenced by rapidity().
double Jetscape::FourVector::rapidity () inline
Definition at line 112 of file FourVector.h.
View newest version in sPHENIX GitHub at line 112 of file FourVector.h
References minus(), and plus().
void Jetscape::FourVector::rotate_around_z (double theta) inline
Definition at line 169 of file FourVector.h.
View newest version in sPHENIX GitHub at line 169 of file FourVector.h
References xv, and yv.
void Jetscape::FourVector::Set (double x_in, double y_in, double z_in, double t_in) inline
Definition at line 64 of file FourVector.h.
View newest version in sPHENIX GitHub at line 64 of file FourVector.h
References tv, xv, yv, and zv.
Referenced by HybridHadronization::bring_hadrons_to_mass_shell(), Martini::DoEnergyLoss(), Martini::getNewMomentumElas(), Martini::getThermalVec(), HybridHadronization::gluon_decay(), HybridHadronization::HHboost(), HybridHadronization::recomb(), HybridHadronization::set_initial_parton_masses(), Jetscape::JetScapeParticleBase::set_x(), HybridHadronization::stringprep(), and Jetscape::Vertex::Vertex().
void Jetscape::FourVector::Set (double a[4]) inline
Definition at line 71 of file FourVector.h.
View newest version in sPHENIX GitHub at line 71 of file FourVector.h
References tv, xv, yv, and zv.
double Jetscape::FourVector::t () const inline
Definition at line 85 of file FourVector.h.
View newest version in sPHENIX GitHub at line 85 of file FourVector.h
References tv.
Referenced by Jetscape::LiquefierBase::add_hydro_sources(), HybridHadronization::bring_hadrons_to_mass_shell(), Jetscape::LiquefierBase::check_energy_momentum_conservation(), Martini::DoEnergyLoss(), Jetscape::Afterburner::GetFragmentationHadrons(), Martini::getNewMomentumElas(), Martini::getThermalVec(), HybridHadronization::gluon_decay(), Jetscape::Hadron::has_no_position(), HybridHadronization::HHboost(), Martini::isCoherent(), AfterburnerModus::JS_hadrons_to_smash_particles(), operator*(), operator+=(), operator-=(), Jetscape::operator<<(), operator=(), HybridHadronization::HHparton::pos(), HybridHadronization::HHhadron::pos(), HybridHadronization::recomb(), Jetscape::JetScapeParticleBase::reset_momentum(), HybridHadronization::set_initial_parton_masses(), HybridHadronization::stringprep(), TEST(), and Jetscape::JetScapeParticleBase::time().
double Jetscape::FourVector::x () const inline
Definition at line 79 of file FourVector.h.
View newest version in sPHENIX GitHub at line 79 of file FourVector.h
References xv.
Referenced by Jetscape::LiquefierBase::add_hydro_sources(), HybridHadronization::bring_hadrons_to_mass_shell(), Jetscape::LiquefierBase::check_energy_momentum_conservation(), HybridHadronization::dif2(), Martini::DoEnergyLoss(), Jetscape::Afterburner::GetFragmentationHadrons(), Martini::getNewMomentumElas(), Martini::getThermalVec(), HybridHadronization::gluon_decay(), Jetscape::Hadron::has_no_position(), HybridHadronization::HHboost(), Martini::isCoherent(), AfterburnerModus::JS_hadrons_to_smash_particles(), operator*(), operator+=(), operator-=(), Jetscape::operator<<(), operator=(), phi(), Jetscape::JetScapeParticleBase::pl(), HybridHadronization::HHparton::pos(), HybridHadronization::HHhadron::pos(), HybridHadronization::recomb(), Jetscape::JetScapeParticleBase::reset_momentum(), HybridHadronization::set_initial_parton_masses(), HybridHadronization::stringprep(), and TEST().
double Jetscape::FourVector::y () const inline
Definition at line 81 of file FourVector.h.
View newest version in sPHENIX GitHub at line 81 of file FourVector.h
References yv.
Referenced by Jetscape::LiquefierBase::add_hydro_sources(), HybridHadronization::bring_hadrons_to_mass_shell(), Jetscape::LiquefierBase::check_energy_momentum_conservation(), HybridHadronization::dif2(), Martini::DoEnergyLoss(), Jetscape::Afterburner::GetFragmentationHadrons(), Martini::getNewMomentumElas(), Martini::getThermalVec(), HybridHadronization::gluon_decay(), Jetscape::Hadron::has_no_position(), HybridHadronization::HHboost(), Martini::isCoherent(), AfterburnerModus::JS_hadrons_to_smash_particles(), operator*(), operator+=(), operator-=(), Jetscape::operator<<(), operator=(), phi(), Jetscape::JetScapeParticleBase::pl(), HybridHadronization::HHparton::pos(), HybridHadronization::HHhadron::pos(), HybridHadronization::recomb(), Jetscape::JetScapeParticleBase::reset_momentum(), HybridHadronization::set_initial_parton_masses(), and HybridHadronization::stringprep().
double Jetscape::FourVector::z () const inline
Definition at line 83 of file FourVector.h.
View newest version in sPHENIX GitHub at line 83 of file FourVector.h
References zv.
Referenced by Jetscape::LiquefierBase::add_hydro_sources(), HybridHadronization::bring_hadrons_to_mass_shell(), Jetscape::LiquefierBase::check_energy_momentum_conservation(), HybridHadronization::dif2(), Martini::DoEnergyLoss(), Jetscape::Afterburner::GetFragmentationHadrons(), Martini::getNewMomentumElas(), Martini::getThermalVec(), HybridHadronization::gluon_decay(), Jetscape::Hadron::has_no_position(), HybridHadronization::HHboost(), Martini::isCoherent(), AfterburnerModus::JS_hadrons_to_smash_particles(), operator*(), operator+=(), operator-=(), Jetscape::operator<<(), operator=(), Jetscape::JetScapeParticleBase::pl(), HybridHadronization::HHparton::pos(), HybridHadronization::HHhadron::pos(), HybridHadronization::recomb(), Jetscape::JetScapeParticleBase::reset_momentum(), HybridHadronization::set_initial_parton_masses(), and HybridHadronization::stringprep().
Member Data Documentation
double Jetscape::FourVector::tv private
Definition at line 178 of file FourVector.h.
View newest version in sPHENIX GitHub at line 178 of file FourVector.h
Referenced by clear(), comp(), FourVector(), minus(), operator*(), operator+=(), operator-=(), operator=(), plus(), Set(), and t().
double Jetscape::FourVector::xv private
Definition at line 178 of file FourVector.h.
View newest version in sPHENIX GitHub at line 178 of file FourVector.h
Referenced by clear(), comp(), FourVector(), operator*(), operator+=(), operator-=(), operator=(), rotate_around_z(), Set(), and x().
double Jetscape::FourVector::yv private
Definition at line 178 of file FourVector.h.
View newest version in sPHENIX GitHub at line 178 of file FourVector.h
Referenced by clear(), comp(), FourVector(), operator*(), operator+=(), operator-=(), operator=(), rotate_around_z(), Set(), and y().
double Jetscape::FourVector::zv private
Definition at line 178 of file FourVector.h.
View newest version in sPHENIX GitHub at line 178 of file FourVector.h
Referenced by clear(), comp(), FourVector(), minus(), operator*(), operator+=(), operator-=(), operator=(), plus(), Set(), and z().
The documentation for this class was generated from the following file:
JETSCAPE/blob/main/src/framework/FourVector.h