Analysis Software: Acts::NavigationLayer Class Reference
Acts::NavigationLayer Class Reference
#include <acts/blob/sPHENIX/Core/include/Acts/Geometry/NavigationLayer.hpp>
Public Member Functions
~NavigationLayer () override
Destructor.
Vector3 binningPosition (const GeometryContext &gctx, BinningValue bValue) const final
NavigationLayer ()=delete
Default Constructor - deleted.
NavigationLayer (const NavigationLayer &)=delete
Copy Constructor - deleted.
NavigationLayer & operator= (const NavigationLayer &)=delete
Assignment operator - deleted.
const Surface & surfaceRepresentation () const final
Surface & surfaceRepresentation () final
bool isOnLayer (const GeometryContext &gctx, const Vector3 &gp, const BoundaryCheck &bcheck=true) const final
bool resolve (bool resolveSensitive, bool resolveMaterial, bool resolvePassive) const final
Public Member Functions inherited from Acts::Layer
Layer ()=delete
Default Constructor - deleted.
Layer (const Layer &)=delete
Copy Constructor - deleted.
virtual ~Layer ()=default
Destructor.
Layer & operator= (const Layer &layer)=delete
const SurfaceArray * surfaceArray () const
Return the entire SurfaceArray, returns a nullptr if no SurfaceArray.
SurfaceArray * surfaceArray ()
Non-const version.
double thickness () const
const ApproachDescriptor * approachDescriptor () const
Return method for the approach descriptor, can be nullptr.
ApproachDescriptor * approachDescriptor ()
Non-const version of the approach descriptor.
template<typename options_t >
bool resolve (const options_t &options) const
boost::container::small_vector
< SurfaceIntersection, 10 > compatibleSurfaces (const GeometryContext &gctx, const Vector3 &position, const Vector3 &direction, const NavigationOptions< Surface > &options) const
Decompose Layer into (compatible) surfaces.
SurfaceIntersection surfaceOnApproach (const GeometryContext &gctx, const Vector3 &position, const Vector3 &direction, const NavigationOptions< Layer > &options) const
const Layer * nextLayer (const GeometryContext &gctx, const Vector3 &position, const Vector3 &direction) const
const TrackingVolume * trackingVolume () const
const AbstractVolume * representingVolume () const
LayerType layerType () const
return the LayerType
Public Member Functions inherited from Acts::GeometryObject
GeometryObject ()=default
Defaulted constructor.
GeometryObject (const GeometryObject &)=default
Defaulted copy constructor.
GeometryObject (const GeometryIdentifier &geometryId)
GeometryObject & operator= (const GeometryObject &geometryId)
const GeometryIdentifier & geometryId () const
virtual double binningPositionValue (const GeometryContext &gctx, BinningValue bValue) const
void assignGeometryId (const GeometryIdentifier &geometryId)
Static Public Member Functions
static LayerPtr create (std::shared_ptr< const Surface > sRepresentation, double thickness=0.)
Protected Member Functions
NavigationLayer (std::shared_ptr< const Surface > surfaceRepresentation, double thickness)
Protected Member Functions inherited from Acts::Layer
Layer (std::unique_ptr< SurfaceArray > surfaceArray, double thickness=0., std::unique_ptr< ApproachDescriptor > ades=nullptr, LayerType laytyp=passive)
void encloseTrackingVolume (const TrackingVolume &tvol)
Protected Attributes
std::shared_ptr< const Surface > m_surfaceRepresentation
Protected Attributes inherited from Acts::Layer
NextLayers m_nextLayers
the previous Layer according to BinGenUtils
const BinUtility * m_nextLayerUtility = nullptr
std::unique_ptr< const
SurfaceArray > m_surfaceArray = nullptr
double m_layerThickness = 0.
Thickness of the Layer.
std::unique_ptr< const
ApproachDescriptor > m_approachDescriptor = nullptr
const TrackingVolume * m_trackingVolume = nullptr
the enclosing TrackingVolume
std::unique_ptr< AbstractVolume > m_representingVolume = nullptr
LayerType m_layerType
make a passive/active either way
int m_ssRepresentingSurface = 0
sub structure indication
int m_ssSensitiveSurfaces = 0
int m_ssApproachSurfaces = 0
Protected Attributes inherited from Acts::GeometryObject
GeometryIdentifier m_geometryId
Detailed Description
Class to be used for gaps in Volumes as a navigational link. Navigation Layers have a surface representation, but should usually never be propagated to.
Definition at line 30 of file NavigationLayer.hpp.
View newest version in sPHENIX GitHub at line 30 of file NavigationLayer.hpp
Constructor & Destructor Documentation
Acts::NavigationLayer::~NavigationLayer () override default
Destructor.
Acts::NavigationLayer::NavigationLayer () delete
Default Constructor - deleted.
Referenced by create().
Acts::NavigationLayer::NavigationLayer (const NavigationLayer &) delete
Copy Constructor - deleted.
Acts::NavigationLayer::NavigationLayer (std::shared_ptr< const Surface > surfaceRepresentation, double thickness) protected
Private Constructor
this is called by the creat(args*) method passed spacer layer if needed
Parameters
surfaceRepresentation is the surface of the layer
thickness ithe layer thickness
Definition at line 13 of file NavigationLayer.cpp.
View newest version in sPHENIX GitHub at line 13 of file NavigationLayer.cpp
References Acts::Layer::m_layerThickness, Acts::Layer::m_layerType, Acts::navigation, and Acts::Layer::thickness().
Member Function Documentation
Vector3 Acts::NavigationLayer::binningPosition (const GeometryContext & gctx, BinningValue bValue) const inline final virtual
The binning position method
Parameters
gctx The current geometry context object, e.g. alignment
bValue is the value for which the binning position is requested
as default the center is given, but may be overloaded
Returns
The return vector can be used for binning in a TrackingVolume
Implements Acts::GeometryObject.
Definition at line 120 of file NavigationLayer.hpp.
View newest version in sPHENIX GitHub at line 120 of file NavigationLayer.hpp
References m_surfaceRepresentation.
static LayerPtr Acts::NavigationLayer::create (std::shared_ptr< const Surface > sRepresentation, double thickness = 0.) inline static
Factory Constructor - the surface representation is given by pointer (ownership passed)
Parameters
sRepresentation is the representation for extrapolation
thickness is the thickness for the binning
Definition at line 37 of file NavigationLayer.hpp.
View newest version in sPHENIX GitHub at line 37 of file NavigationLayer.hpp
References testing::internal::move(), NavigationLayer(), and Acts::Layer::thickness().
Referenced by Acts::Test::Layers::BOOST_AUTO_TEST_CASE(), and Acts::LayerArrayCreator::layerArray().
bool Acts::NavigationLayer::isOnLayer (const GeometryContext & gctx, const Vector3 & gp, const BoundaryCheck & bcheck = true) const inline final virtual
Geometric isOnLayer() method using isOnSurface() with Layer specific tolerance
Parameters
gctx The current geometry context object, e.g. alignment
gp is the global position for the check
bcheck is the boundary check directive
Returns
boolean that indicates if the position is on surface
Reimplemented from Acts::Layer.
Definition at line 125 of file NavigationLayer.hpp.
View newest version in sPHENIX GitHub at line 125 of file NavigationLayer.hpp
References m_surfaceRepresentation.
NavigationLayer& Acts::NavigationLayer::operator= (const NavigationLayer &) delete
Assignment operator - deleted.
bool Acts::NavigationLayer::resolve (bool resolveSensitive, bool resolveMaterial, bool resolvePassive) const inline final virtual
Accept layer according to the following collection directives
Parameters
resolveSensitive is the prescription to find the sensitive surfaces
resolveMaterial is the precription to find material surfaces
resolvePassive is the prescription to find all passive surfaces
Note
navigation layers are never accepted
Returns
a boolean whether the layer is accepted for processing
Reimplemented from Acts::Layer.
Definition at line 132 of file NavigationLayer.hpp.
View newest version in sPHENIX GitHub at line 132 of file NavigationLayer.hpp
const Surface & Acts::NavigationLayer::surfaceRepresentation () const inline final virtual
Transforms the layer into a Surface representation for extrapolation In general, extrapolation to a surface should be avoided
Implements Acts::Layer.
Definition at line 112 of file NavigationLayer.hpp.
View newest version in sPHENIX GitHub at line 112 of file NavigationLayer.hpp
Surface & Acts::NavigationLayer::surfaceRepresentation () inline final virtual
Implements Acts::Layer.
Definition at line 116 of file NavigationLayer.hpp.
View newest version in sPHENIX GitHub at line 116 of file NavigationLayer.hpp
References m_surfaceRepresentation.
Member Data Documentation
std::shared_ptr<const Surface> Acts::NavigationLayer::m_surfaceRepresentation protected
for the navigation Volume the surface
We will need to mutate this surface during the geometry building process, but the C++ type system has no const-correct way of expressing this.
Definition at line 109 of file NavigationLayer.hpp.
View newest version in sPHENIX GitHub at line 109 of file NavigationLayer.hpp
Referenced by binningPosition(), isOnLayer(), and surfaceRepresentation().
The documentation for this class was generated from the following files:
acts/blob/sPHENIX/Core/include/Acts/Geometry/NavigationLayer.hpp
acts/blob/sPHENIX/Core/src/Geometry/NavigationLayer.cpp