Analysis Software: PHTpcEventExporter Class Reference
PHTpcEventExporter Class Reference
#include <coresoftware/blob/master/offline/packages/PHTpcTracker/PHTpcEventExporter.h>
Public Member Functions
PHTpcEventExporter ()
virtual ~PHTpcEventExporter ()
void exportEvent (TrkrClusterContainer *cluster_map, TrkrHitSetContainer *hitsets, std::vector< kdfinder::TrackCandidate< double > * > candidates, double B, const std::string &filename)
void exportEvent (TrkrClusterContainer *cluster_map, TrkrHitSetContainer *hitsets, std::vector< PHGenFit2::Track * > gtracks, double B, const std::string &filename)
void exportEvent (std::vector< PHGenFit2::Track * > gtracks, double B, const std::string &filename)
Detailed Description
Definition at line 30 of file PHTpcEventExporter.h.
View newest version in sPHENIX GitHub at line 30 of file PHTpcEventExporter.h
Constructor & Destructor Documentation
PHTpcEventExporter::PHTpcEventExporter ()
Definition at line 28 of file PHTpcEventExporter.cc.
View newest version in sPHENIX GitHub at line 28 of file PHTpcEventExporter.cc
virtual PHTpcEventExporter::~PHTpcEventExporter () inline virtual
Definition at line 34 of file PHTpcEventExporter.h.
View newest version in sPHENIX GitHub at line 34 of file PHTpcEventExporter.h
Member Function Documentation
void PHTpcEventExporter::exportEvent (TrkrClusterContainer * cluster_map, TrkrHitSetContainer * hitsets, std::vector< kdfinder::TrackCandidate< double > * > candidates, double B, const std::string & filename)
Definition at line 32 of file PHTpcEventExporter.cc.
View newest version in sPHENIX GitHub at line 32 of file PHTpcEventExporter.cc
References color, filename, TrkrClusterContainer::getClusters(), TrkrHitSetContainer::getHitSets(), TrkrCluster::getPosition(), i, it, G4PLUGDOOR::length, LOG_DEBUG, separator, sign(), and TrkrDefs::tpcId.
void PHTpcEventExporter::exportEvent (TrkrClusterContainer * cluster_map, TrkrHitSetContainer * hitsets, std::vector< PHGenFit2::Track * > gtracks, double B, const std::string & filename)
Definition at line 140 of file PHTpcEventExporter.cc.
View newest version in sPHENIX GitHub at line 140 of file PHTpcEventExporter.cc
References charge, color, filename, TrkrClusterContainer::getClusters(), TrkrHitSetContainer::getHitSets(), TrkrCluster::getPosition(), i, it, G4PLUGDOOR::length, LOG_DEBUG, LOG_WARN, Acts::Test::pos, separator, and TrkrDefs::tpcId.
void PHTpcEventExporter::exportEvent (std::vector< PHGenFit2::Track * > gtracks, double B, const std::string & filename)
Definition at line 261 of file PHTpcEventExporter.cc.
View newest version in sPHENIX GitHub at line 261 of file PHTpcEventExporter.cc
References charge, color, filename, i, G4PLUGDOOR::length, LOG_DEBUG, and Acts::Test::pos.
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/PHTpcTracker/PHTpcEventExporter.h
coresoftware/blob/master/offline/packages/PHTpcTracker/PHTpcEventExporter.cc