Analysis Software: upload.MercurialVCS Class Reference
upload.MercurialVCS Class Reference
Public Member Functions
def __init__
def GenerateDiff
def GetUnknownFiles
def GetBaseFile
def __init__
def GenerateDiff
def GetUnknownFiles
def GetBaseFile
Public Member Functions inherited from upload.VersionControlSystem
def __init__
def GenerateDiff
def GetUnknownFiles
def CheckForUnknownFiles
def GetBaseFile
def GetBaseFiles
def UploadBaseFiles
def IsImage
def __init__
def GenerateDiff
def GetUnknownFiles
def CheckForUnknownFiles
def GetBaseFile
def GetBaseFiles
def UploadBaseFiles
def IsImage
Public Attributes
repo_dir
subdir
base_rev
Public Attributes inherited from upload.VersionControlSystem
options
Private Member Functions
def _GetRelPath
def _GetRelPath
Detailed Description
Implementation of the VersionControlSystem interface for Mercurial.
Definition at line 1042 of file upload.py.
View newest version in sPHENIX GitHub at line 1042 of file upload.py
Constructor & Destructor Documentation
def upload.MercurialVCS.__init__ (self, options, repo_dir)
Definition at line 1045 of file upload.py.
View newest version in sPHENIX GitHub at line 1045 of file upload.py
Referenced by upload.MercurialVCS.__init__().
def upload.MercurialVCS.__init__ (self, options, repo_dir)
Definition at line 1045 of file upload.py.
View newest version in sPHENIX GitHub at line 1045 of file upload.py
References upload.MercurialVCS.__init__(), upload.MercurialVCS.base_rev, upload.MercurialVCS.repo_dir, upload.RunShell(), and upload.MercurialVCS.subdir.
Member Function Documentation
def upload.MercurialVCS._GetRelPath (self, filename) private
Get relative path of a file according to the current directory,
given its logical path in the repo.
Definition at line 1058 of file upload.py.
View newest version in sPHENIX GitHub at line 1058 of file upload.py
References upload.MercurialVCS.subdir.
Referenced by upload.MercurialVCS._GetRelPath(), and upload.MercurialVCS.GetBaseFile().
def upload.MercurialVCS._GetRelPath (self, filename) private
Get relative path of a file according to the current directory,
given its logical path in the repo.
Definition at line 1058 of file upload.py.
View newest version in sPHENIX GitHub at line 1058 of file upload.py
References upload.MercurialVCS._GetRelPath(), and upload.MercurialVCS.subdir.
def upload.MercurialVCS.GenerateDiff (self, extra_args)
Definition at line 1064 of file upload.py.
View newest version in sPHENIX GitHub at line 1064 of file upload.py
References upload.MercurialVCS.base_rev, upload.ErrorExit(), join(), and upload.RunShell().
Referenced by upload.MercurialVCS.GenerateDiff().
def upload.MercurialVCS.GenerateDiff (self, extra_args)
Definition at line 1064 of file upload.py.
View newest version in sPHENIX GitHub at line 1064 of file upload.py
References upload.MercurialVCS.base_rev, upload.ErrorExit(), upload.MercurialVCS.GenerateDiff(), join(), and upload.RunShell().
def upload.MercurialVCS.GetBaseFile (self, filename)
Definition at line 1102 of file upload.py.
View newest version in sPHENIX GitHub at line 1102 of file upload.py
References upload.MercurialVCS._GetRelPath(), upload.MercurialVCS.base_rev, test_fpe.count, upload.EncodeMultipartFormData(), upload.ErrorExit(), upload.MercurialVCS.GetBaseFile(), upload.GetRpcServer(), upload.GuessVCS(), upload.VersionControlSystem.IsImage(), join(), upload.main(), Acts.open, ActsExamples::JsonSurfacesReader.read(), upload.RealMain(), upload.RunShell(), upload.RunShellWithReturnCode(), upload.SplitPatch(), upload.StatusUpdate(), str, and upload.UploadSeparatePatches().
def upload.MercurialVCS.GetBaseFile (self, filename)
Definition at line 1102 of file upload.py.
View newest version in sPHENIX GitHub at line 1102 of file upload.py
References upload.MercurialVCS._GetRelPath(), upload.MercurialVCS.base_rev, upload.VersionControlSystem.IsImage(), Acts.open, ActsExamples::JsonSurfacesReader.read(), and upload.RunShell().
Referenced by upload.MercurialVCS.GetBaseFile().
def upload.MercurialVCS.GetUnknownFiles (self)
Return a list of files unknown to the VCS.
Definition at line 1090 of file upload.py.
View newest version in sPHENIX GitHub at line 1090 of file upload.py
References upload.MercurialVCS.base_rev, and upload.RunShell().
Referenced by upload.MercurialVCS.GetUnknownFiles().
def upload.MercurialVCS.GetUnknownFiles (self)
Return a list of files unknown to the VCS.
Definition at line 1090 of file upload.py.
View newest version in sPHENIX GitHub at line 1090 of file upload.py
References upload.MercurialVCS.base_rev, upload.MercurialVCS.GetUnknownFiles(), and upload.RunShell().
Member Data Documentation
upload.MercurialVCS.base_rev
Definition at line 1054 of file upload.py.
View newest version in sPHENIX GitHub at line 1054 of file upload.py
Referenced by upload.MercurialVCS.__init__(), upload.MercurialVCS.GenerateDiff(), upload.MercurialVCS.GetBaseFile(), and upload.MercurialVCS.GetUnknownFiles().
upload.MercurialVCS.repo_dir
Definition at line 1048 of file upload.py.
View newest version in sPHENIX GitHub at line 1048 of file upload.py
Referenced by upload.MercurialVCS.__init__().
upload.MercurialVCS.subdir
Definition at line 1052 of file upload.py.
View newest version in sPHENIX GitHub at line 1052 of file upload.py
Referenced by upload.MercurialVCS.__init__(), and upload.MercurialVCS._GetRelPath().
The documentation for this class was generated from the following files:
JETSCAPE/blob/main/external_packages/googletest/googlemock/scripts/upload.py
JETSCAPE/blob/main/external_packages/googletest/googletest/scripts/upload.py