Analysis Software: Acts::EventDataView3DTest Namespace Reference
Acts::EventDataView3DTest Namespace Reference
Typedefs
using Covariance = BoundSquareMatrix
Functions
std::normal_distribution< double > gauss (0., 1.)
std::default_random_engine generator (42)
void createDetector (GeometryContext &tgContext, std::vector< const Surface * > &surfaces, std::shared_ptr< const TrackingGeometry > &detector, const size_t nSurfaces=7)
static std::string testBoundTrackParameters (IVisualization3D &helper)
static std::string testMeasurement (IVisualization3D &helper)
static std::string testMultiTrajectory (IVisualization3D &helper)
Typedef Documentation
using Acts::EventDataView3DTest::Covariance = typedef BoundSquareMatrix
Definition at line 53 of file EventDataView3DBase.hpp.
View newest version in sPHENIX GitHub at line 53 of file EventDataView3DBase.hpp
Function Documentation
void Acts::EventDataView3DTest::createDetector (GeometryContext & tgContext, std::vector< const Surface * > & surfaces, std::shared_ptr< const TrackingGeometry > & detector, const size_t nSurfaces = 7)
A function that creates a simple telescope detector with surfaces for the EventDataView3D tests
Parameters
helper The visualization helper
surfaces Reference to the surfaces, because we need them outside
detector The tracking geometry that will be filled
nSurfaces Number of surfaces to generate
Returns
an overall string including all written output
Definition at line 67 of file EventDataView3DBase.hpp.
View newest version in sPHENIX GitHub at line 67 of file EventDataView3DBase.hpp
References Acts::Surface::associatedDetectorElement(), bounds, Acts::Surface::center(), Acts::CuboidVolumeBuilder::SurfaceConfig::detElementConstructor, Acts::GeometryObject::geometryId(), i, Acts::Test::makeSilicon(), Acts::CuboidVolumeBuilder::SurfaceConfig::position, Acts::CuboidVolumeBuilder::VolumeConfig::position, Acts::CuboidVolumeBuilder::Config::position, rBounds, Acts::CuboidVolumeBuilder::SurfaceConfig::rBounds, Acts::CuboidVolumeBuilder::SurfaceConfig::rotation, Acts::CuboidVolumeBuilder::setConfig(), writeMapConfig::surface, Acts::CuboidVolumeBuilder::LayerConfig::surfaceCfg, Acts::CuboidVolumeBuilder::SurfaceConfig::surMat, thickness, Acts::CuboidVolumeBuilder::SurfaceConfig::thickness, Acts::TrackingGeometryBuilder::trackingGeometry(), and Acts::TrackingGeometryBuilder::Config::trackingVolumeBuilders.
Referenced by testMeasurement(), and testMultiTrajectory().
std::normal_distribution<double> Acts::EventDataView3DTest::gauss (0. , 1.)
Referenced by ActsExamples::Contextual::AlignmentDecorator::applyTransform(), BOOST_AUTO_TEST_CASE(), boundParamResolution(), eicsmear_dvmp_plot(), ActsExamples::HelloRandomAlgorithm::execute(), ActsExamples::PropagationAlgorithm::execute(), ActsExamples::PropagationAlgorithm::generateCovariance(), PHField2D::GetFieldCyl(), PHField3DCylindrical::GetFieldCyl(), PHField2D::PHField2D(), PHField3DCylindrical::PHField3DCylindrical(), PHField3DCylindrical::print_map(), testMeasurement(), and testMultiTrajectory().
std::default_random_engine Acts::EventDataView3DTest::generator (42)
Referenced by testMeasurement(), and testMultiTrajectory().
static std::string Acts::EventDataView3DTest::testBoundTrackParameters (IVisualization3D & helper) inline static
Helper method to visualize all types of surfaces
Parameters
helper The visualization helper
Returns
an overall string including all written output
Definition at line 167 of file EventDataView3DBase.hpp.
View newest version in sPHENIX GitHub at line 167 of file EventDataView3DBase.hpp
References Acts::Test::cov, Acts::EventDataView3D::drawBoundTrackParameters(), gctx, Acts::PrimitivesView3DTest::identity, testing::internal::move(), pars, Acts::ParticleHypothesis::pion(), Acts::PrimitivesView3DTest::plane, Acts::PrimitivesView3DTest::rectangle, and Acts::IVisualization3D::write().
Referenced by Acts::Test::BOOST_AUTO_TEST_CASE().
static std::string Acts::EventDataView3DTest::testMeasurement (IVisualization3D & helper) inline static
Helper method to visualize measurements
Parameters
helper The visualization helper
Returns
an overall string including all written output
Definition at line 219 of file EventDataView3DBase.hpp.
View newest version in sPHENIX GitHub at line 219 of file EventDataView3DBase.hpp
References Acts::Test::cov, createDetector(), Acts::EventDataView3D::drawMeasurement(), Acts::eBoundLoc0, Acts::eBoundLoc1, gauss(), generator(), loc, Acts::ViewConfig::offset, surf(), writeMapConfig::surface, Acts::tgContext, and Acts::IVisualization3D::write().
Referenced by Acts::Test::BOOST_AUTO_TEST_CASE().
static std::string Acts::EventDataView3DTest::testMultiTrajectory (IVisualization3D & helper) inline static
Helper method to visualize a MultiTrajectory
Parameters
helper The visualization helper
Returns
an overall string including all written output
Definition at line 278 of file EventDataView3DBase.hpp.
View newest version in sPHENIX GitHub at line 278 of file EventDataView3DBase.hpp
References Acts::IntegrationTest::bField, cfg, Acts::Test::cov, createDetector(), Acts::EventDataView3D::drawMultiTrajectory(), Acts::eBoundLoc0, Acts::eBoundLoc1, conf::extensions, Acts::KalmanFitter< propagator_t, traj_t >::fit(), gauss(), generator(), Acts::getDefaultLogger(), loc, logger(), Acts::VectorHelpers::makeVector4(), Acts::IntegrationTest::mfContext, Acts::ViewConfig::offset, Acts::ParticleHypothesis::pion(), Acts::GenericBoundTrackParameters< particle_hypothesis_t >::referenceSurface(), writeMapConfig::surface, Acts::tgContext, tracks(), Acts::Logging::WARNING, and Acts::IVisualization3D::write().
Referenced by Acts::Test::BOOST_AUTO_TEST_CASE().