Analysis Software: ResidualOutlierFinder Struct Reference
ResidualOutlierFinder Struct Reference
#include <coresoftware/blob/master/offline/packages/trackbase/ResidualOutlierFinder.h>
Public Member Functions
bool operator() (Acts::MultiTrajectory< Acts::VectorMultiTrajectory >::ConstTrackStateProxy state) const
Public Attributes
int verbosity = 0
std::map< long unsigned int,
float > chi2Cuts
Detailed Description
Definition at line 10 of file ResidualOutlierFinder.h.
View newest version in sPHENIX GitHub at line 10 of file ResidualOutlierFinder.h
Member Function Documentation
bool ResidualOutlierFinder::operator() (Acts::MultiTrajectory< Acts::VectorMultiTrajectory >::ConstTrackStateProxy state) const inline
Definition at line 15 of file ResidualOutlierFinder.h.
View newest version in sPHENIX GitHub at line 15 of file ResidualOutlierFinder.h
References Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::calibratedSize(), chi2Cuts, configureMap::data, distance(), Acts::GeometryObject::geometryId(), H, Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::hasCalibrated(), Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::hasPredicted(), Acts::GeometryIdentifier::layer(), layer, N, Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::predicted(), Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::predictedCovariance(), Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::projector(), Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::referenceSurface(), value, verbosity, Acts::visit_measurement(), and Acts::GeometryIdentifier::volume().
Member Data Documentation
std::map<long unsigned int, float> ResidualOutlierFinder::chi2Cuts
Definition at line 13 of file ResidualOutlierFinder.h.
View newest version in sPHENIX GitHub at line 13 of file ResidualOutlierFinder.h
Referenced by PHCosmicsTrkFitter::InitRun(), PHActsTrkFitter::InitRun(), and operator()().
int ResidualOutlierFinder::verbosity = 0
Definition at line 12 of file ResidualOutlierFinder.h.
View newest version in sPHENIX GitHub at line 12 of file ResidualOutlierFinder.h
Referenced by PHCosmicsTrkFitter::InitRun(), PHActsTrkFitter::InitRun(), and operator()().
The documentation for this struct was generated from the following file:
coresoftware/blob/master/offline/packages/trackbase/ResidualOutlierFinder.h