Analysis Software: acts/blob/sPHENIX/Examples/Io/Json/src/JsonMaterialWriter.cpp File Reference
JsonMaterialWriter.cpp File Reference
#include "ActsExamples/Io/Json/JsonMaterialWriter.hpp"
#include "Acts/Utilities/Helpers.hpp"
#include <fstream>
#include <iomanip>
#include <ios>
#include <vector>
#include <nlohmann/json.hpp>
Functions
m_cfg (config)
Variables
m_converter
Function Documentation
m_cfg (config)
Referenced by Acts::AdaptiveMultiVertexFinder< vfitter_t, sfinder_t >::addCompatibleTracksToVertex(), ActsExamples::HoughTransformSeeder::addMeasurements(), ActsExamples::HoughTransformSeeder::addSpacePoints(), Acts::GaussianGridTrackDensity< mainGridSize, trkGridSize >::addTrack(), Acts::AdaptiveGridTrackDensity< spatialTrkGridSize, temporalTrkGridSize >::addTrack(), Acts::GaussianTrackDensity< input_track_t >::addTracks(), Acts::CylinderVolumeBuilder::analyzeContent(), Acts::Experimental::GeometryIdGenerator::assignGeometryId(), Acts::SolenoidBField::B_r(), Acts::SolenoidBField::B_z(), ActsExamples::EffPlotTool::book(), ActsExamples::TrackSummaryPlotTool::book(), ActsExamples::DuplicationPlotTool::book(), ActsExamples::FakeRatePlotTool::book(), ActsExamples::ResPlotTool::book(), Acts::TGeoLayerBuilder::buildLayers(), Acts::PassiveLayerBuilder::centralLayers(), ActsExamples::Generic::LayerBuilderT< detector_element_t >::centralLayers(), Acts::DD4hepLayerBuilder::centralLayers(), ActsExamples::Generic::ProtoLayerCreatorT< detector_element_t >::centralProtoLayers(), Acts::DD4hepVolumeBuilder::centralVolumes(), Acts::SurfaceMaterialMapper::checkAndInsert(), Acts::AdaptiveMultiVertexFitter< input_track_t, linearizer_t >::checkSmallShift(), Acts::AdaptiveMultiVertexFinder< vfitter_t, sfinder_t >::checkVertexAndCompatibleTracks(), ActsExamples::ResPlotTool::clear(), ActsExamples::RootMaterialWriter::collectMaterial(), Acts::TorchEdgeClassifier::config(), Acts::TorchMetricLearning::config(), ActsExamples::CsvMultiTrajectoryWriter::config(), ActsExamples::JsonMaterialWriter::config(), ActsExamples::Telescope::TelescopeG4DetectorConstruction::Construct(), Acts::Experimental::DetectorBuilder::construct(), Acts::Experimental::DetectorVolumeBuilder::construct(), Acts::Experimental::VolumeStructureBuilder::construct(), Acts::Experimental::CylindricalContainerBuilder::construct(), Acts::Experimental::LayerStructureBuilder::construct(), ActsExamples::Generic::LayerBuilderT< detector_element_t >::constructEndcapLayers(), Acts::MaterialMapJsonConverter::convertToHierarchy(), Acts::IterativeVertexFinder< vfitter_t, sfinder_t >::countSignificantTracks(), Acts::CylinderVolumeHelper::createContainerTrackingVolume(), Acts::SurfaceArrayCreator::createEquidistantAxis(), Acts::VolumeMaterialMapper::createExtraHits(), Acts::CylinderVolumeHelper::createGapTrackingVolume(), ActsExamples::HoughTransformSeeder::createHoughHist(), ActsExamples::HoughTransformSeeder::createLayerHoughHist(), ActsExamples::Generic::ProtoLayerCreatorT< detector_element_t >::createProtoLayers(), Acts::GaussianGridTrackDensity< mainGridSize, trkGridSize >::createTrackGrid(), Acts::AdaptiveGridTrackDensity< spatialTrkGridSize, temporalTrkGridSize >::createTrackGrid(), Acts::SurfaceArrayCreator::createVariableAxis(), Acts::LayerCreator::cylinderLayer(), ActsExamples::ScalableBFieldService::decorate(), ActsExamples::Contextual::ExternalAlignmentDecorator::decorate(), ActsExamples::Contextual::InternalAlignmentDecorator::decorate(), Acts::AdaptiveMultiVertexFinder< vfitter_t, sfinder_t >::deleteLastVertex(), Acts::SurfaceArrayCreator::determineBinCount(), Acts::LayerCreator::discLayer(), Acts::AdaptiveGridDensityVertexFinder< trkGridSize, vfitter_t >::doesPassTrackSelection(), Acts::GridDensityVertexFinder< mainGridSize, trkGridSize, vfitter_t >::doesPassTrackSelection(), Acts::AdaptiveMultiVertexFinder< vfitter_t, sfinder_t >::doSeeding(), Acts::AdaptiveMultiVertexFitter< input_track_t, linearizer_t >::doVertexSmoothing(), Acts::PassiveLayerBuilder::endcapLayers(), Acts::DD4hepLayerBuilder::endcapLayers(), Acts::ImpactPointEstimator< input_track_t, propagator_t, propagator_options_t >::estimate3DImpactParameters(), Acts::GaussianGridTrackDensity< mainGridSize, trkGridSize >::estimateSeedWidth(), Acts::AdaptiveGridTrackDensity< spatialTrkGridSize, temporalTrkGridSize >::estimateSeedWidth(), ActsExamples::ParticlesPrinter::execute(), ActsExamples::TrackParametersPrinter::execute(), ActsExamples::HelloWhiteBoardAlgorithm::execute(), ActsExamples::TruthVertexFinder::execute(), ActsExamples::TrackSelectorAlgorithm::execute(), ActsExamples::HelloRandomAlgorithm::execute(), ActsExamples::RefittingAlgorithm::execute(), ActsExamples::AmbiguityResolutionMLAlgorithm::execute(), ActsExamples::TrackModifier::execute(), ActsExamples::TrackParameterSelector::execute(), ActsExamples::VolumeAssociationTest::execute(), ActsExamples::AmbiguityResolutionMLDBScanAlgorithm::execute(), ActsExamples::HepMCProcessExtractor::execute(), ActsExamples::HitsPrinter::execute(), ActsExamples::SeedingOrthogonalAlgorithm::execute(), ActsExamples::SeedingFTFAlgorithm::execute(), ActsExamples::EventRecording::execute(), ActsExamples::DigitizationAlgorithm::execute(), ActsExamples::TrackFittingAlgorithm::execute(), ActsExamples::ParticleSmearing::execute(), ActsExamples::ParticleSelector::execute(), ActsExamples::SpacePointMaker::execute(), ActsExamples::TruthSeedingAlgorithm::execute(), ActsExamples::SeedingAlgorithm::execute(), ActsExamples::PlanarSteppingAlgorithm::execute(), ActsExamples::TrackFindingAlgorithmExaTrkX::execute(), ActsExamples::IterativeVertexFinderAlgorithm::execute(), ActsExamples::AdaptiveMultiVertexFinderAlgorithm::execute(), ActsExamples::VertexFitterAlgorithm::execute(), ActsExamples::TrackParamsEstimationAlgorithm::execute(), ActsExamples::AlignmentAlgorithm::execute(), ActsExamples::FatrasSimulation::execute(), ActsExamples::TrackFindingAlgorithm::execute(), ActsExamples::MaterialMapping::execute(), ActsExamples::HoughTransformSeeder::execute(), ActsExamples::AdaptiveMultiVertexFinderAlgorithm::executeAfterSeederChoice(), ActsExamples::Telescope::TelescopeG4DetectorConstructionFactory::factorize(), ActsExamples::ResPlotTool::fill(), Acts::IterativeVertexFinder< vfitter_t, sfinder_t >::fillTracksToFit(), Acts::SeedFilter< external_spacepoint_t >::filterSeeds_1SpFixed(), Acts::SeedFilter< external_spacepoint_t >::filterSeeds_2SpFixed(), ActsExamples::RootSimHitWriter::finalize(), ActsExamples::RootParticleWriter::finalize(), ActsExamples::RootSpacepointWriter::finalize(), ActsExamples::RootPropagationStepsWriter::finalize(), ActsExamples::RootNuclearInteractionParametersWriter::finalize(), ActsExamples::RootPlanarClusterWriter::finalize(), ActsExamples::RootTrackParameterWriter::finalize(), ActsExamples::RootTrajectorySummaryWriter::finalize(), ActsExamples::RootMaterialTrackWriter::finalize(), ActsExamples::RootTrajectoryStatesWriter::finalize(), Acts::TrackDensityVertexFinder< vfitter_t, track_density_t >::find(), Acts::AdaptiveGridDensityVertexFinder< trkGridSize, vfitter_t >::find(), Acts::GridDensityVertexFinder< mainGridSize, trkGridSize, vfitter_t >::find(), Acts::ZScanVertexFinder< vfitter_t >::find(), Acts::IterativeVertexFinder< vfitter_t, sfinder_t >::find(), Acts::AdaptiveMultiVertexFinder< vfitter_t, sfinder_t >::find(), Acts::SingleSeedVertexFinder< spacepoint_t >::findClosestPointFromPlanes(), Acts::SingleSeedVertexFinder< spacepoint_t >::findClosestPointFromRays(), Acts::SingleSeedVertexFinder< spacepoint_t >::findTriplets(), Acts::SingleSeedVertexFinder< spacepoint_t >::findVertex(), Acts::GaussianSumFitter< propagator_t, bethe_heitler_approx_t, traj_t >::fit(), Acts::FullBilloirVertexFitter< input_track_t, linearizer_t >::fit(), Acts::AdaptiveMultiVertexFitter< input_track_t, linearizer_t >::fitImpl(), ActsExamples::Sequencer::fpeMaskCount(), ActsExamples::Sequencer::fpeReport(), ActsExamples::SimParticleTranslation::GeneratePrimaries(), ActsExamples::RandomNumbers::generateSeed(), Acts::ImpactPointEstimator< input_track_t, propagator_t, propagator_options_t >::get3DLifetimeSignOfTrack(), Acts::IterativeVertexFinder< vfitter_t, sfinder_t >::getCompatibility(), Acts::TrackingGeometryBuilder::getConfiguration(), Acts::ImpactPointEstimator< input_track_t, propagator_t, propagator_options_t >::getDistanceAndMomentum(), ActsExamples::HoughTransformSeeder::getExtension(), ActsExamples::MagneticFieldWrapper::GetFieldValue(), Acts::GaussianGridTrackDensity< mainGridSize, trkGridSize >::getHighestSumZPosition(), Acts::ImpactPointEstimator< input_track_t, propagator_t, propagator_options_t >::getImpactParameters(), Acts::AdaptiveMultiVertexFinder< vfitter_t, sfinder_t >::getIPSignificance(), Acts::ImpactPointEstimator< input_track_t, propagator_t, propagator_options_t >::getLifetimeSignOfTrack(), Acts::GaussianGridTrackDensity< mainGridSize, trkGridSize >::getMaxZPosition(), Acts::AdaptiveGridTrackDensity< spatialTrkGridSize, temporalTrkGridSize >::getMaxZTPosition(), Acts::IterativeVertexFinder< vfitter_t, sfinder_t >::getVertexSeed(), Acts::AnnealingUtility::getWeight(), Acts::AdaptiveGridTrackDensity< spatialTrkGridSize, temporalTrkGridSize >::highestDensitySumBin(), if(), Acts::Experimental::DetectorNavigator::inactive(), ActsExamples::TGeoITkModuleSplitter::initSplitCategories(), Acts::CylinderVolumeHelper::interGlueTrackingVolume(), Acts::AdaptiveMultiVertexFinder< vfitter_t, sfinder_t >::isMergedVertex(), Acts::SolenoidBField::k2(), Acts::AdaptiveMultiVertexFinder< vfitter_t, sfinder_t >::keepNewVertex(), ActsExamples::SeedingFTFAlgorithm::LayerNumbering(), m_cfg(), ActsExamples::SeedingFTFAlgorithm::Make_ACTS_FTF_Map(), Acts::SurfaceMaterialMapper::mapInteraction(), Acts::SurfaceMaterialMapper::mapSurfaceInteraction(), Acts::SolenoidBField::multiCoilField(), Acts::DD4hepLayerBuilder::negativeLayers(), ActsExamples::Pythia8Generator::operator()(), ActsExamples::ParametricParticleGenerator::operator()(), Fatras::LandauDist::operator==(), ActsExamples::HoughTransformSeeder::passThreshold(), Acts::ImpactPointEstimator< input_track_t, propagator_t, propagator_options_t >::performNewtonOptimization(), Acts::LayerCreator::planeLayer(), Acts::DD4hepLayerBuilder::positiveLayers(), ActsExamples::ParticleTrackingAction::PostUserTrackingAction(), Acts::AdaptiveMultiVertexFitter< input_track_t, linearizer_t >::prepareVertexForFit(), ActsExamples::SeedingOrthogonalAlgorithm::printConfig(), ActsExamples::SeedingOrthogonalAlgorithm::printOptions(), ActsExamples::HepMC3AsciiReader::read(), ActsExamples::CsvParticleReader::read(), ActsExamples::CsvSimHitReader::read(), ActsExamples::CsvTrackParameterReader::read(), ActsExamples::CsvSpacePointReader::read(), ActsExamples::RootParticleReader::read(), ActsExamples::RootTrajectorySummaryReader::read(), ActsExamples::RootMaterialTrackReader::read(), ActsExamples::CsvPlanarClusterReader::read(), ActsExamples::CsvMeasurementReader::read(), ActsExamples::EventGenerator::read(), Acts::IterativeVertexFinder< vfitter_t, sfinder_t >::reassignTracksToNewVertex(), ActsExamples::ResPlotTool::refinement(), ActsExamples::SensitiveSurfaceMapper::remapSensitiveNames(), Acts::AdaptiveMultiVertexFinder< vfitter_t, sfinder_t >::removeCompatibleTracksFromSeedTracks(), Acts::IterativeVertexFinder< vfitter_t, sfinder_t >::removeUsedCompatibleTracks(), ActsExamples::MaterialMapping::scoringParameters(), Acts::AdaptiveMultiVertexFitter< input_track_t, linearizer_t >::setAllVertexCompatibilities(), Acts::DD4hepVolumeBuilder::setConfiguration(), Acts::TrackingGeometryBuilder::setConfiguration(), Acts::PassiveLayerBuilder::setConfiguration(), Acts::DD4hepLayerBuilder::setConfiguration(), Acts::TGeoLayerBuilder::setConfiguration(), Acts::CylinderVolumeHelper::setConfiguration(), Acts::LayerCreator::setConfiguration(), Acts::CylinderVolumeBuilder::setConfiguration(), Acts::AdaptiveMultiVertexFinder< vfitter_t, sfinder_t >::setConstraintAfterSeeding(), Acts::detail::GsfActor< bethe_heitler_approx_t, traj_t >::setOptions(), Acts::AdaptiveMultiVertexFitter< input_track_t, linearizer_t >::setWeightsAndUpdate(), Acts::SingleSeedVertexFinder< spacepoint_t >::sortSpacepoints(), Acts::TGeoCylinderDiscSplitter::split(), ActsExamples::TGeoITkModuleSplitter::split(), Acts::GaussianTrackDensity< input_track_t >::stepSize(), Acts::SurfaceArrayCreator::surfaceArrayOnDisc(), Acts::TrackingGeometryBuilder::trackingGeometry(), Acts::KDTreeTrackingGeometryBuilder::trackingGeometry(), Acts::CuboidVolumeBuilder::trackingVolume(), Acts::CylinderVolumeBuilder::trackingVolume(), Acts::KDTreeTrackingGeometryBuilder::translateLayer(), Acts::KDTreeTrackingGeometryBuilder::translateVolume(), Acts::SingleSeedVertexFinder< spacepoint_t >::tripletValidationAndUpdate(), ActsExamples::MaterialSteppingAction::UserSteppingAction(), ActsExamples::SensitiveSteppingAction::UserSteppingAction(), ActsExamples::ParticleKillAction::UserSteppingAction(), Acts::Experimental::GeometryIdGenerator::volumeId(), while(), ActsExamples::SvgTrackingGeometryWriter::write(), ActsExamples::CsvTrackParameterWriter::write(), ActsExamples::ObjTrackingGeometryWriter::write(), ActsExamples::JsonMaterialWriter::write(), ActsExamples::ResPlotTool::write(), ActsExamples::JsonMaterialWriter::writeMaterial(), ActsExamples::RootMaterialWriter::writeMaterial(), ActsExamples::ObjSpacePointWriter< T >::writeT(), ActsExamples::HepMC3AsciiWriter::writeT(), ActsExamples::JsonSpacePointWriter< T >::writeT(), ActsExamples::CsvProtoTrackWriter::writeT(), ActsExamples::CsvSimHitWriter::writeT(), ActsExamples::CsvParticleWriter::writeT(), ActsExamples::CsvSpacepointWriter::writeT(), ActsExamples::CsvMeasurementWriter::writeT(), ActsExamples::CsvPlanarClusterWriter::writeT(), ActsExamples::RootPlanarClusterWriter::writeT(), ActsExamples::CKFPerformanceWriter::writeT(), ActsExamples::RootTrajectorySummaryWriter::writeT(), ActsExamples::RootMaterialTrackWriter::writeT(), ActsExamples::VertexPerformanceWriter::writeT(), ActsExamples::SvgPointWriter< T, Acc >::writeT(), ActsExamples::RootMeasurementWriter::writeT(), ActsExamples::HoughTransformSeeder::yToX(), ActsExamples::HoughTransformSeeder::yToXBins(), and ActsExamples::MaterialMapping::~MaterialMapping().
Variable Documentation
m_converter
Initial value:
{std::make_unique<Acts::MaterialMapJsonConverter>(
          m_cfg.converterCfg, level)} {}
ActsExamples::JsonMaterialWriter::~JsonMaterialWriter() = default
Definition at line 25 of file JsonMaterialWriter.cpp.
View newest version in sPHENIX GitHub at line 25 of file JsonMaterialWriter.cpp
Referenced by ActsExamples::JsonMaterialWriter::write(), and ActsExamples::JsonMaterialWriter::writeMaterial().