Analysis Software: ActsFatras::FreeParametersSmearer< generator_t, kSize > Struct Template Reference
ActsFatras::FreeParametersSmearer< generator_t, kSize > Struct Template Reference
#include <acts/blob/sPHENIX/Fatras/include/ActsFatras/Digitization/UncorrelatedHitSmearer.hpp>
Public Types
using Scalar = Acts::ActsScalar
using ParametersVector = Acts::ActsVector< kSize >
using CovarianceMatrix = Acts::ActsSquareMatrix< kSize >
using Result = Acts::Result< std::pair< ParametersVector, CovarianceMatrix >>
Public Member Functions
Result operator() (generator_t &rng, const Hit &hit) const
Static Public Member Functions
static constexpr size_t size ()
Public Attributes
std::array< Acts::FreeIndices,
kSize > indices {}
Parameter indices that will be used to create the smeared measurements.
std::array
< SingleParameterSmearFunction
< generator_t >, kSize > smearFunctions
Detailed Description
template<typename generator_t, size_t kSize>
struct ActsFatras::FreeParametersSmearer< generator_t, kSize >
Uncorrelated smearing algorithm for fast digitisation of free parameters.
Template Parameters
generator_t Random number generator type
kSize Number of smeared parameters
The smearer takes a single simulated Hit and generates a smeared parameter vector and associated covariance matrix.
Note
Uncorrelated smearing of the direction using each components individually is not recommended
Definition at line 114 of file UncorrelatedHitSmearer.hpp.
View newest version in sPHENIX GitHub at line 114 of file UncorrelatedHitSmearer.hpp
Member Typedef Documentation
template<typename generator_t, size_t kSize> using ActsFatras::FreeParametersSmearer< generator_t, kSize >::CovarianceMatrix = Acts::ActsSquareMatrix<kSize>
Definition at line 117 of file UncorrelatedHitSmearer.hpp.
View newest version in sPHENIX GitHub at line 117 of file UncorrelatedHitSmearer.hpp
template<typename generator_t, size_t kSize> using ActsFatras::FreeParametersSmearer< generator_t, kSize >::ParametersVector = Acts::ActsVector<kSize>
Definition at line 116 of file UncorrelatedHitSmearer.hpp.
View newest version in sPHENIX GitHub at line 116 of file UncorrelatedHitSmearer.hpp
template<typename generator_t, size_t kSize> using ActsFatras::FreeParametersSmearer< generator_t, kSize >::Result = Acts::Result<std::pair<ParametersVector, CovarianceMatrix>>
Definition at line 118 of file UncorrelatedHitSmearer.hpp.
View newest version in sPHENIX GitHub at line 118 of file UncorrelatedHitSmearer.hpp
template<typename generator_t, size_t kSize> using ActsFatras::FreeParametersSmearer< generator_t, kSize >::Scalar = Acts::ActsScalar
Definition at line 115 of file UncorrelatedHitSmearer.hpp.
View newest version in sPHENIX GitHub at line 115 of file UncorrelatedHitSmearer.hpp
Member Function Documentation
template<typename generator_t, size_t kSize> Result ActsFatras::FreeParametersSmearer< generator_t, kSize >::operator() (generator_t & rng, const Hit & hit) const inline
Generate smeared measured for configured parameters.
Parameters
rng Random number generator
hit Simulated hit
Returns
Smeared free parameter set wrapped in a Result<...> object
Return values
Smeared parameters vector and associated covariance on success
Error code for failure
Definition at line 133 of file UncorrelatedHitSmearer.hpp.
View newest version in sPHENIX GitHub at line 133 of file UncorrelatedHitSmearer.hpp
References Acts::Test::cov, ActsFatras::Hit::direction(), Acts::eFreeDir0, Acts::eFreePos0, Acts::eFreeQOverP, Acts::eFreeTime, i, ActsFatras::FreeParametersSmearer< generator_t, kSize >::indices, ActsFatras::Hit::position(), conftest::rng(), ActsFatras::FreeParametersSmearer< generator_t, kSize >::smearFunctions, ActsFatras::Hit::time(), and value.
template<typename generator_t, size_t kSize> static constexpr size_t ActsFatras::FreeParametersSmearer< generator_t, kSize >::size (void) inline static
Definition at line 124 of file UncorrelatedHitSmearer.hpp.
View newest version in sPHENIX GitHub at line 124 of file UncorrelatedHitSmearer.hpp
Member Data Documentation
template<typename generator_t, size_t kSize> std::array<Acts::FreeIndices, kSize> ActsFatras::FreeParametersSmearer< generator_t, kSize >::indices {}
Parameter indices that will be used to create the smeared measurements.
Definition at line 121 of file UncorrelatedHitSmearer.hpp.
View newest version in sPHENIX GitHub at line 121 of file UncorrelatedHitSmearer.hpp
Referenced by BOOST_AUTO_TEST_CASE(), BOOST_DATA_TEST_CASE(), and ActsFatras::FreeParametersSmearer< generator_t, kSize >::operator()().
template<typename generator_t, size_t kSize> std::array<SingleParameterSmearFunction<generator_t>, kSize> ActsFatras::FreeParametersSmearer< generator_t, kSize >::smearFunctions
Definition at line 122 of file UncorrelatedHitSmearer.hpp.
View newest version in sPHENIX GitHub at line 122 of file UncorrelatedHitSmearer.hpp
Referenced by BOOST_AUTO_TEST_CASE(), BOOST_DATA_TEST_CASE(), and ActsFatras::FreeParametersSmearer< generator_t, kSize >::operator()().
The documentation for this struct was generated from the following file:
acts/blob/sPHENIX/Fatras/include/ActsFatras/Digitization/UncorrelatedHitSmearer.hpp