Analysis Software: MbdPmtContainer Class Reference
MbdPmtContainer Class Reference
#include <coresoftware/blob/master/offline/packages/mbd/MbdPmtContainer.h>
Public Member Functions
virtual ~MbdPmtContainer ()
dtor
virtual void identify (std::ostream &os=std::cout) const override
virtual void Reset () override
Clear Event.
virtual int isValid () const override
isValid returns non zero if object contains valid data
virtual void set_npmt (const short ival)
virtual Short_t get_npmt () const
get Number of Mbd Pmt's
virtual MbdPmtHit * get_pmt (const int ipmt) const
get MbdPmtHit Object
Public Member Functions inherited from PHObject
PHObject ()
ctor
~PHObject () override
dtor
virtual PHObject * CloneMe () const
Virtual copy constructor.
virtual PHObject * clone () const final
PHObject * Clone (const char *newname="") const final
void Copy (TObject &object) const final
virtual int Integrate () const
virtual int Integrate (PHObject *)
virtual void CopyFrom (const PHObject *obj)
Private Member Functions
void virtual_warning (const std::string &funcname) const
Detailed Description
Definition at line 14 of file MbdPmtContainer.h.
View newest version in sPHENIX GitHub at line 14 of file MbdPmtContainer.h
Constructor & Destructor Documentation
virtual MbdPmtContainer::~MbdPmtContainer () inline virtual
dtor
Definition at line 18 of file MbdPmtContainer.h.
View newest version in sPHENIX GitHub at line 18 of file MbdPmtContainer.h
Member Function Documentation
Short_t MbdPmtContainer::get_npmt () const virtual
get Number of Mbd Pmt's
Reimplemented in MbdPmtContainerV1.
Definition at line 32 of file MbdPmtContainer.cc.
View newest version in sPHENIX GitHub at line 32 of file MbdPmtContainer.cc
References MbdReturnCodes::MBD_INVALID_SHORT, and virtual_warning().
Referenced by BbcCheck::CheckDST(), EventPlaneReco::process_event(), DumpMbdPmtContainer::process_Node(), CaloAna::process_towers(), and CaloValid::process_towers().
MbdPmtHit * MbdPmtContainer::get_pmt (const int ipmt) const virtual
get MbdPmtHit Object
Reimplemented in MbdPmtContainerV1.
Definition at line 38 of file MbdPmtContainer.cc.
View newest version in sPHENIX GitHub at line 38 of file MbdPmtContainer.cc
References virtual_warning().
Referenced by MbdEvent::Calculate(), BbcCheck::CheckDST(), EventPlaneReco::process_event(), MbdDigitization::process_event(), DumpMbdPmtContainer::process_Node(), CaloAna::process_towers(), CaloValid::process_towers(), and MbdEvent::SetRawData().
void MbdPmtContainer::identify (std::ostream & os = std::cout) const override virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from PHObject.
Reimplemented in MbdPmtContainerV1.
Definition at line 8 of file MbdPmtContainer.cc.
View newest version in sPHENIX GitHub at line 8 of file MbdPmtContainer.cc
int MbdPmtContainer::isValid () const override virtual
isValid returns non zero if object contains valid data
Reimplemented from PHObject.
Reimplemented in MbdPmtContainerV1.
Definition at line 20 of file MbdPmtContainer.cc.
View newest version in sPHENIX GitHub at line 20 of file MbdPmtContainer.cc
References virtual_warning().
Referenced by DumpMbdPmtContainer::process_Node().
void MbdPmtContainer::Reset () override virtual
Clear Event.
Reimplemented from PHObject.
Reimplemented in MbdPmtContainerV1.
Definition at line 14 of file MbdPmtContainer.cc.
View newest version in sPHENIX GitHub at line 14 of file MbdPmtContainer.cc
References PHWHERE.
void MbdPmtContainer::set_npmt (const short ival) virtual
set number of PMTs for Mbd
Parameters
ival Number of Mbd Pmt's
Definition at line 26 of file MbdPmtContainer.cc.
View newest version in sPHENIX GitHub at line 26 of file MbdPmtContainer.cc
References virtual_warning().
Referenced by MbdEvent::SetRawData().
void MbdPmtContainer::virtual_warning (const std::string & funcname) const private
Definition at line 44 of file MbdPmtContainer.cc.
View newest version in sPHENIX GitHub at line 44 of file MbdPmtContainer.cc
Referenced by get_npmt(), get_pmt(), isValid(), and set_npmt().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/mbd/MbdPmtContainer.h
coresoftware/blob/master/offline/packages/mbd/MbdPmtContainer.cc