Analysis Software: JetMap Class Reference
JetMap Class Reference
#include <coresoftware/blob/master/simulation/g4simulation/g4jets/JetMap.h>
Public Types
typedef std::map< unsigned int,
Jet * > typ_JetMap
typedef typ_JetMap::const_iterator ConstIter
typedef typ_JetMap::iterator Iter
typedef std::set< Jet::SRC >
::const_iterator ConstSrcIter
typedef std::set< Jet::SRC >
::iterator SrcIter
Public Member Functions
JetMap ()
~JetMap () override
void identify (std::ostream &os=std::cout) const override
int isValid () const override
isValid returns non zero if object contains vailid data
PHObject * CloneMe () const override
Virtual copy constructor.
virtual void set_algo (Jet::ALGO algo)
virtual Jet::ALGO get_algo () const
virtual void set_par (float par)
virtual float get_par () const
virtual bool empty_src () const
virtual void insert_src (Jet::SRC src)
virtual ConstSrcIter begin_src () const
virtual ConstSrcIter find_src (Jet::SRC src) const
virtual ConstSrcIter end_src () const
virtual SrcIter begin_src ()
virtual SrcIter find_src (Jet::SRC src)
virtual SrcIter end_src ()
virtual bool empty () const
virtual size_t size () const
virtual size_t count (unsigned int idkey) const
virtual void clear ()
virtual const Jet * get (unsigned int idkey) const
virtual Jet * get (unsigned int idkey)
virtual Jet * insert (Jet *jet)
virtual size_t erase (unsigned int idkey)
virtual ConstIter begin () const
virtual ConstIter find (unsigned int idkey) const
virtual ConstIter end () const
virtual Iter begin ()
virtual Iter find (unsigned int idkey)
virtual Iter end ()
Public Member Functions inherited from PHObject
PHObject ()
ctor
~PHObject () override
dtor
virtual PHObject * clone () const final
PHObject * Clone (const char *newname="") const final
void Copy (TObject &object) const final
virtual void Reset ()
Clear Event.
virtual int isValid (const float) const
virtual int isValid (const double) const
virtual int isValid (const int) const
virtual int isValid (const unsigned int) const
virtual int isImplemented (const float f) const
virtual int isImplemented (const double f) const
virtual int isImplemented (const int i) const
virtual int isImplemented (const unsigned int i) const
virtual int Integrate () const
virtual int Integrate (PHObject *obj)
virtual void CopyFrom (const PHObject *obj)
Private Member Functions
ClassDefOverride (JetMap, 1)
Detailed Description
Definition at line 14 of file JetMap.h.
View newest version in sPHENIX GitHub at line 14 of file JetMap.h
Member Typedef Documentation
typedef typ_JetMap::const_iterator JetMap::ConstIter
Definition at line 19 of file JetMap.h.
View newest version in sPHENIX GitHub at line 19 of file JetMap.h
typedef std::set<Jet::SRC>::const_iterator JetMap::ConstSrcIter
Definition at line 23 of file JetMap.h.
View newest version in sPHENIX GitHub at line 23 of file JetMap.h
typedef typ_JetMap::iterator JetMap::Iter
Definition at line 20 of file JetMap.h.
View newest version in sPHENIX GitHub at line 20 of file JetMap.h
typedef std::set<Jet::SRC>::iterator JetMap::SrcIter
Definition at line 24 of file JetMap.h.
View newest version in sPHENIX GitHub at line 24 of file JetMap.h
typedef std::map<unsigned int, Jet*> JetMap::typ_JetMap
Definition at line 18 of file JetMap.h.
View newest version in sPHENIX GitHub at line 18 of file JetMap.h
Constructor & Destructor Documentation
JetMap::JetMap () inline
Definition at line 26 of file JetMap.h.
View newest version in sPHENIX GitHub at line 26 of file JetMap.h
JetMap::~JetMap () inline override
Definition at line 27 of file JetMap.h.
View newest version in sPHENIX GitHub at line 27 of file JetMap.h
Member Function Documentation
JetMap::ConstIter JetMap::begin () const virtual
Reimplemented in JetMapv1.
Definition at line 44 of file JetMap.cc.
View newest version in sPHENIX GitHub at line 44 of file JetMap.cc
References DummyJetMapMap.
Referenced by JetRecoEval::all_jets_from(), JetEvaluator::fillOutputNtuples(), JetEnergies::fillOutputNtuples(), JetTruthEval::get_truth_jet(), PhotonJet::GetRecoHadronsAndJets(), PhotonJet::GetRecoHadronsAndJetsAA(), TreeMaker::GetRecoJets(), AnaTutorial::getReconstructedJets(), TreeMaker::GetTruthJets(), AnaTutorial::getTruthJets(), JetMapv1::JetMapv1(), BJetModule::process_event(), HFJetTruthTrigger::process_event(), DetermineTowerBackground::process_event(), TruthPhotonJet::process_event(), PHG4DSTReader::process_event(), MyJetAnalysis::process_event(), PhotonJet::process_event(), LeptoquarksReco::process_event(), BDiJetModule::process_event(), DumpJetMap::process_Node(), QAG4SimulationJet::process_Spectrum(), SoftLeptonTaggingTruth::process_Spectrum(), and QAG4SimulationJet::process_TruthMatching().
JetMap::Iter JetMap::begin () virtual
Reimplemented in JetMapv1.
Definition at line 59 of file JetMap.cc.
View newest version in sPHENIX GitHub at line 59 of file JetMap.cc
References DummyJetMapMap.
JetMap::ConstSrcIter JetMap::begin_src () const virtual
Reimplemented in JetMapv1.
Definition at line 14 of file JetMap.cc.
View newest version in sPHENIX GitHub at line 14 of file JetMap.cc
Referenced by JetMapv1::JetMapv1().
JetMap::SrcIter JetMap::begin_src () virtual
Reimplemented in JetMapv1.
Definition at line 29 of file JetMap.cc.
View newest version in sPHENIX GitHub at line 29 of file JetMap.cc
JetMap::ClassDefOverride (JetMap , 1) private
virtual void JetMap::clear () inline virtual
Reimplemented in JetMapv1.
Definition at line 59 of file JetMap.h.
View newest version in sPHENIX GitHub at line 59 of file JetMap.h
PHObject* JetMap::CloneMe () const inline override virtual
Virtual copy constructor.
Reimplemented from PHObject.
Reimplemented in JetMapv1.
Definition at line 31 of file JetMap.h.
View newest version in sPHENIX GitHub at line 31 of file JetMap.h
virtual size_t JetMap::count (unsigned int idkey) const inline virtual
Reimplemented in JetMapv1.
Definition at line 58 of file JetMap.h.
View newest version in sPHENIX GitHub at line 58 of file JetMap.h
virtual bool JetMap::empty () const inline virtual
Reimplemented in JetMapv1.
Definition at line 56 of file JetMap.h.
View newest version in sPHENIX GitHub at line 56 of file JetMap.h
virtual bool JetMap::empty_src () const inline virtual
Reimplemented in JetMapv1.
Definition at line 43 of file JetMap.h.
View newest version in sPHENIX GitHub at line 43 of file JetMap.h
JetMap::ConstIter JetMap::end () const virtual
Reimplemented in JetMapv1.
Definition at line 54 of file JetMap.cc.
View newest version in sPHENIX GitHub at line 54 of file JetMap.cc
References DummyJetMapMap.
Referenced by JetRecoEval::all_jets_from(), JetEvaluator::fillOutputNtuples(), JetEnergies::fillOutputNtuples(), JetTruthEval::get_truth_jet(), PhotonJet::GetRecoHadronsAndJets(), PhotonJet::GetRecoHadronsAndJetsAA(), TreeMaker::GetRecoJets(), AnaTutorial::getReconstructedJets(), TreeMaker::GetTruthJets(), AnaTutorial::getTruthJets(), JetMapv1::JetMapv1(), BJetModule::process_event(), HFJetTruthTrigger::process_event(), DetermineTowerBackground::process_event(), TruthPhotonJet::process_event(), PHG4DSTReader::process_event(), MyJetAnalysis::process_event(), PhotonJet::process_event(), LeptoquarksReco::process_event(), BDiJetModule::process_event(), DumpJetMap::process_Node(), QAG4SimulationJet::process_Spectrum(), SoftLeptonTaggingTruth::process_Spectrum(), and QAG4SimulationJet::process_TruthMatching().
JetMap::Iter JetMap::end () virtual
Reimplemented in JetMapv1.
Definition at line 69 of file JetMap.cc.
View newest version in sPHENIX GitHub at line 69 of file JetMap.cc
References DummyJetMapMap.
JetMap::ConstSrcIter JetMap::end_src () const virtual
Reimplemented in JetMapv1.
Definition at line 24 of file JetMap.cc.
View newest version in sPHENIX GitHub at line 24 of file JetMap.cc
Referenced by JetMapv1::JetMapv1().
JetMap::SrcIter JetMap::end_src () virtual
Reimplemented in JetMapv1.
Definition at line 39 of file JetMap.cc.
View newest version in sPHENIX GitHub at line 39 of file JetMap.cc
virtual size_t JetMap::erase (unsigned int idkey) inline virtual
Reimplemented in JetMapv1.
Definition at line 65 of file JetMap.h.
View newest version in sPHENIX GitHub at line 65 of file JetMap.h
JetMap::ConstIter JetMap::find (unsigned int idkey) const virtual
Reimplemented in JetMapv1.
Definition at line 49 of file JetMap.cc.
View newest version in sPHENIX GitHub at line 49 of file JetMap.cc
References DummyJetMapMap.
JetMap::Iter JetMap::find (unsigned int idkey) virtual
Reimplemented in JetMapv1.
Definition at line 64 of file JetMap.cc.
View newest version in sPHENIX GitHub at line 64 of file JetMap.cc
References DummyJetMapMap.
JetMap::ConstSrcIter JetMap::find_src (Jet::SRC src) const virtual
Reimplemented in JetMapv1.
Definition at line 19 of file JetMap.cc.
View newest version in sPHENIX GitHub at line 19 of file JetMap.cc
JetMap::SrcIter JetMap::find_src (Jet::SRC src) virtual
Reimplemented in JetMapv1.
Definition at line 34 of file JetMap.cc.
View newest version in sPHENIX GitHub at line 34 of file JetMap.cc
virtual const Jet* JetMap::get (unsigned int idkey) const inline virtual
Reimplemented in JetMapv1.
Definition at line 61 of file JetMap.h.
View newest version in sPHENIX GitHub at line 61 of file JetMap.h
Referenced by LeptoquarksReco::AddJetInformation().
virtual Jet* JetMap::get (unsigned int idkey) inline virtual
Reimplemented in JetMapv1.
Definition at line 62 of file JetMap.h.
View newest version in sPHENIX GitHub at line 62 of file JetMap.h
virtual Jet::ALGO JetMap::get_algo () const inline virtual
Reimplemented in JetMapv1.
Definition at line 36 of file JetMap.h.
View newest version in sPHENIX GitHub at line 36 of file JetMap.h
References Jet::NONE.
Referenced by DumpJetMap::process_Node().
virtual float JetMap::get_par () const inline virtual
Reimplemented in JetMapv1.
Definition at line 39 of file JetMap.h.
View newest version in sPHENIX GitHub at line 39 of file JetMap.h
Referenced by HFJetTruthTrigger::process_event(), LeptoquarksReco::process_event(), and DumpJetMap::process_Node().
void JetMap::identify (std::ostream & os = std::cout) const override virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from PHObject.
Reimplemented in JetMapv1.
Definition at line 8 of file JetMap.cc.
View newest version in sPHENIX GitHub at line 8 of file JetMap.cc
virtual Jet* JetMap::insert (Jet * jet) inline virtual
Reimplemented in JetMapv1.
Definition at line 64 of file JetMap.h.
View newest version in sPHENIX GitHub at line 64 of file JetMap.h
Referenced by JetReco::FillJetNode(), PHFlowJetMaker::process_event(), and JetHepMCLoader::process_event().
virtual void JetMap::insert_src (Jet::SRC src) inline virtual
Reimplemented in JetMapv1.
Definition at line 44 of file JetMap.h.
View newest version in sPHENIX GitHub at line 44 of file JetMap.h
Referenced by JetReco::FillJetNode(), PHFlowJetMaker::process_event(), and JetHepMCLoader::process_event().
int JetMap::isValid () const inline override virtual
isValid returns non zero if object contains vailid data
Reimplemented from PHObject.
Reimplemented in JetMapv1.
Definition at line 30 of file JetMap.h.
View newest version in sPHENIX GitHub at line 30 of file JetMap.h
virtual void JetMap::set_algo (Jet::ALGO algo) inline virtual
Reimplemented in JetMapv1.
Definition at line 35 of file JetMap.h.
View newest version in sPHENIX GitHub at line 35 of file JetMap.h
Referenced by JetReco::FillJetNode(), PHFlowJetMaker::process_event(), and JetHepMCLoader::process_event().
virtual void JetMap::set_par (float par) inline virtual
Reimplemented in JetMapv1.
Definition at line 38 of file JetMap.h.
View newest version in sPHENIX GitHub at line 38 of file JetMap.h
Referenced by JetReco::FillJetNode(), PHFlowJetMaker::process_event(), and JetHepMCLoader::process_event().
virtual size_t JetMap::size (void) const inline virtual
Reimplemented in JetMapv1.
Definition at line 57 of file JetMap.h.
View newest version in sPHENIX GitHub at line 57 of file JetMap.h
Referenced by TreeMaker::CopyAndMakeJets(), HFJetTruthTrigger::process_event(), PHG4DSTReader::process_event(), DumpJetMap::process_Node(), QAG4SimulationJet::process_Spectrum(), and SoftLeptonTaggingTruth::process_Spectrum().
The documentation for this class was generated from the following files:
coresoftware/blob/master/simulation/g4simulation/g4jets/JetMap.h
coresoftware/blob/master/simulation/g4simulation/g4jets/JetMap.cc