Analysis Software: Acts::Experimental::DD4hepVolumeStructure Class Reference
Acts::Experimental::DD4hepVolumeStructure Class Reference
This class allows to generate volumes structure builders for dd4hep sub detectors, together with an internal structure builder, this is sufficient to build the new DetectorVolume objects.
#include <acts/blob/sPHENIX/Plugins/DD4hep/include/Acts/Plugins/DD4hep/DD4hepVolumeStructure.hpp>
Classes
struct Options
nested options struct
Public Member Functions
DD4hepVolumeStructure (std::unique_ptr< const Logger > mlogger=getDefaultLogger("DD4hepVolumeStructure", Acts::Logging::INFO))
DD4hepVolumeStructure ()=delete
std::shared_ptr
< VolumeStructureBuilder > builder (const dd4hep::DetElement &dd4hepElement, const Options &options) const
This method generates a VolumeStructureBuilder, which extends the IExternalStructureBuilder to create DetectorVolume objects.
Private Member Functions
bool recursiveParse (VolumeStructureBuilder::Config &vsbConfig, const dd4hep::DetElement &dd4hepElement) const
Method to recursively parse through the detector element and grep the volume structure information.
const Logger & logger () const
Private access to the logger.
Private Attributes
std::unique_ptr< const Logger > m_logger
Logging instance.
Static Private Attributes
static constexpr ActsScalar unitLength
auto-calculate the unit length conversion
Detailed Description
This class allows to generate volumes structure builders for dd4hep sub detectors, together with an internal structure builder, this is sufficient to build the new DetectorVolume objects.
Definition at line 33 of file DD4hepVolumeStructure.hpp.
View newest version in sPHENIX GitHub at line 33 of file DD4hepVolumeStructure.hpp
Constructor & Destructor Documentation
Acts::Experimental::DD4hepVolumeStructure::DD4hepVolumeStructure (std::unique_ptr< const Logger > mlogger = getDefaultLogger("DD4hepVolumeStructure", Acts::Logging::INFO))
Constructor with arguments
Parameters
mlogger is the screen output logger
Definition at line 15 of file DD4hepVolumeStructure.cpp.
View newest version in sPHENIX GitHub at line 15 of file DD4hepVolumeStructure.cpp
References ACTS_DEBUG, and unitLength.
Acts::Experimental::DD4hepVolumeStructure::DD4hepVolumeStructure () delete
Member Function Documentation
std::shared_ptr< Acts::Experimental::VolumeStructureBuilder > Acts::Experimental::DD4hepVolumeStructure::builder (const dd4hep::DetElement & dd4hepElement, const Options & options) const
This method generates a VolumeStructureBuilder, which extends the IExternalStructureBuilder to create DetectorVolume objects.
It takes the detector element from DD4hep and some optional parameters
Parameters
dd4hepElement the dd4hep detector element
options containing the optional descriptions
Returns
a VolumeStructureBuilder
Definition at line 22 of file DD4hepVolumeStructure.cpp.
View newest version in sPHENIX GitHub at line 22 of file DD4hepVolumeStructure.cpp
References ACTS_DEBUG, Acts::getDefaultLogger(), Acts::Experimental::DD4hepVolumeStructure::Options::logLevel, and Acts::Experimental::DD4hepVolumeStructure::Options::name.
Referenced by BOOST_AUTO_TEST_CASE().
const Logger& Acts::Experimental::DD4hepVolumeStructure::logger () const inline private
Private access to the logger.
Definition at line 86 of file DD4hepVolumeStructure.hpp.
View newest version in sPHENIX GitHub at line 86 of file DD4hepVolumeStructure.hpp
References m_logger.
bool Acts::Experimental::DD4hepVolumeStructure::recursiveParse (VolumeStructureBuilder::Config & vsbConfig, const dd4hep::DetElement & dd4hepElement) const private
Method to recursively parse through the detector element and grep the volume structure information.
Parameters
vsbConfig
dd4hepElement
Returns
a boolean break condition
Definition at line 34 of file DD4hepVolumeStructure.cpp.
View newest version in sPHENIX GitHub at line 34 of file DD4hepVolumeStructure.cpp
References Acts::ACTS_VERBOSE(), Acts::Experimental::VolumeStructureBuilder::Config::boundsType, Acts::Experimental::VolumeStructureBuilder::Config::boundValues, gtest_filter_unittest::child, Acts::extractTransform(), and Acts::Experimental::VolumeStructureBuilder::Config::transform.
Member Data Documentation
std::unique_ptr<const Logger> Acts::Experimental::DD4hepVolumeStructure::m_logger private
Logging instance.
Definition at line 83 of file DD4hepVolumeStructure.hpp.
View newest version in sPHENIX GitHub at line 83 of file DD4hepVolumeStructure.hpp
Referenced by logger().
constexpr ActsScalar Acts::Experimental::DD4hepVolumeStructure::unitLength static private
Initial value:
=
      Acts::UnitConstants::mm / dd4hep::millimeter
auto-calculate the unit length conversion
Definition at line 69 of file DD4hepVolumeStructure.hpp.
View newest version in sPHENIX GitHub at line 69 of file DD4hepVolumeStructure.hpp
Referenced by DD4hepVolumeStructure().
The documentation for this class was generated from the following files:
acts/blob/sPHENIX/Plugins/DD4hep/include/Acts/Plugins/DD4hep/DD4hepVolumeStructure.hpp
acts/blob/sPHENIX/Plugins/DD4hep/src/DD4hepVolumeStructure.cpp