Analysis Software: analysis/blob/master/JS-Jet/JetUESize-v2Psi2Centrality/DrawUECentralityPlots.C File Reference
DrawUECentralityPlots.C File Reference
Functions
void SetHist (TH2 *h, string xt="", string yt="", int color=4, int marker=20, int width=3, float size=1.0)
void SetHist (TH2 *h, int color=4)
void SetLeg (TLegend *l, float txtsize=0.03)
void DrawUECentralityPlots (string infile="UEvsEtaCentrality.root")
Function Documentation
void DrawUECentralityPlots (string infile = "UEvsEtaCentrality.root")
Definition at line 6 of file DrawUECentralityPlots.C.
View newest version in sPHENIX GitHub at line 6 of file DrawUECentralityPlots.C
References _file0, infile, SetHist(), and SetLeg().
void SetHist (TH2 * h, string xt = "", string yt = "", int color = 4, int marker = 20, int width = 3, float size = 1.0)
Definition at line 239 of file DrawUECentralityPlots.C.
View newest version in sPHENIX GitHub at line 239 of file DrawUECentralityPlots.C
References color, and width.
Referenced by DrawUECentralityPlots().
void SetHist (TH2 * h, int color = 4)
Definition at line 251 of file DrawUECentralityPlots.C.
View newest version in sPHENIX GitHub at line 251 of file DrawUECentralityPlots.C
References color.
void SetLeg (TLegend * l, float txtsize = 0.03)
Definition at line 262 of file DrawUECentralityPlots.C.
View newest version in sPHENIX GitHub at line 262 of file DrawUECentralityPlots.C
Referenced by DrawUECentralityPlots().