Analysis Software: itk_seeding Namespace Reference
itk_seeding Namespace Reference
Functions
def runITkSeedingFromCsv
Variables
u acts.UnitConstants
tuple rnd acts.examples.RandomNumbers(seed=42)
tuple p
tuple geo_dir pathlib.Path("acts-itk")
tuple outputDir pathlib.Path.cwd()
tuple field
Function Documentation
def itk_seeding.runITkSeedingFromCsv (detector, trackingGeometry, field, outputDir)
Definition at line 25 of file itk_seeding.py.
View newest version in sPHENIX GitHub at line 25 of file itk_seeding.py
References acts.examples.reconstruction.addStandardSeeding(), acts.examples.itk.itkSeedingAlgConfig(), Acts.open, and print().
Variable Documentation
tuple itk_seeding.field
Initial value:
 acts.examples.MagneticFieldMapXyz(
         str(geo_dir / "bfield/ATLAS-BField-xyz.root")
     )
Definition at line 155 of file itk_seeding.py.
View newest version in sPHENIX GitHub at line 155 of file itk_seeding.py
tuple itk_seeding.geo_dir pathlib.Path("acts-itk")
Definition at line 151 of file itk_seeding.py.
View newest version in sPHENIX GitHub at line 151 of file itk_seeding.py
tuple itk_seeding.outputDir pathlib.Path.cwd()
Definition at line 152 of file itk_seeding.py.
View newest version in sPHENIX GitHub at line 152 of file itk_seeding.py
tuple itk_seeding.p
Initial value:
 argparse.ArgumentParser(
         description="Example script to run ITk seed finding based on CSV spacepoints",
     )
Definition at line 147 of file itk_seeding.py.
View newest version in sPHENIX GitHub at line 147 of file itk_seeding.py
tuple itk_seeding.rnd acts.examples.RandomNumbers(seed=42)
Definition at line 22 of file itk_seeding.py.
View newest version in sPHENIX GitHub at line 22 of file itk_seeding.py
itk_seeding.u acts.UnitConstants
Definition at line 21 of file itk_seeding.py.
View newest version in sPHENIX GitHub at line 21 of file itk_seeding.py