Analysis Software: pythia6/blob/master/pythiaeRHIC/radgen/radgen.f File Reference
radgen.f File Reference
Functions/Subroutines
subroutine radgen (e1, q2l, nul, ys, xs, phil, PhRAD, q2tr, anutr, WEIGHT)
subroutine phidst_pol
subroutine radgam_pol (erad, yrad, xrad, genphi, ixytest, itagen, q2tr, anutr)
double precision function dfufi_pol (dx)
subroutine radquad_pol (dfunct, dlow, dup, dx, dy, dz, dh, ndim)
subroutine mpolrad (e1curr, yscurr, xscurr, uncurr, plcurr, pncurr, itagen)
subroutine conk2 (e1, xs, ys, iittaa)
subroutine conkin (e1, xss, yss)
subroutine bornin (sibor, siamm)
subroutine deltas (delta, delinf, tr)
double precision function vacpol (y)
double precision function fspens (x)
double precision function fspen (x)
subroutine qqt (bo, tai)
subroutine tails (ta, tm)
subroutine ffu (n, bb, bis, bir, bi12, bi1pi2, sir, sis, si12, eis, eir, ei12, ei1pi2, ta)
double precision function podinl (r)
double precision function rv2 (ta)
subroutine strf (ta, rr, sfm)
subroutine ffpro (t, gep, gmp)
subroutine ffdeu (t, gc, gm, gq)
subroutine ffhe3 (t, ge, gm)
subroutine ffhe4 (dq2, ge, gm)
REAL function forgetp (Q2)
subroutine fordop
REAL function forintp (R)
REAL function forrhop (R)
subroutine ffquas (t, geun, gmun, gepo, gmpo)
double precision function supst (t)
double precision function ddexp (x)
subroutine dqn32 (xl, xu, fct, y)
subroutine intbtk2 (dbtk, nbtk, dtkmax)
subroutine inttk2 (isumtk, dbtk1, dbtk2, dsumtk, derrtk)
subroutine itafun (ys, xs, pl, pn, ixytest, itagen)
subroutine xytabl (tname, e1, plrun, pnrun, ixytest, ire)
Function/Subroutine Documentation
subroutine bornin (sibor, siamm)
Definition at line 759 of file radgen.f.
View newest version in sPHENIX GitHub at line 759 of file radgen.f
References Jetscape::JetScapeParticleBase::pl(), s, strf(), x, and y.
Referenced by mpolrad().
subroutine conk2 (e1, xs, ys, iittaa)
Definition at line 654 of file radgen.f.
View newest version in sPHENIX GitHub at line 654 of file radgen.f
References conkin().
Referenced by mpolrad(), and radgam_pol().
subroutine conkin (e1, xss, yss)
Definition at line 676 of file radgen.f.
View newest version in sPHENIX GitHub at line 676 of file radgen.f
References EoS::cs(), Acts::detail::PhiBoundParameterLimits::max(), pi, s, x, and y.
Referenced by conk2().
double precision function ddexp (x)
Definition at line 1987 of file radgen.f.
View newest version in sPHENIX GitHub at line 1987 of file radgen.f
References x.
Referenced by ffhe3().
subroutine deltas (delta, delinf, tr)
Definition at line 813 of file radgen.f.
View newest version in sPHENIX GitHub at line 813 of file radgen.f
References fspen(), i, Acts::Logger::log(), pi, s, small, sum(), vacpol(), x, and y.
Referenced by Fluid::calcTotals(), and mpolrad().
double precision function dfufi_pol (dx)
Definition at line 375 of file radgen.f.
View newest version in sPHENIX GitHub at line 375 of file radgen.f
References pi, podinl(), and tails().
Referenced by phidst_pol().
subroutine dqn32 (double precision xl, double precision xu, double precision, external fct, double precision y)
Definition at line 2002 of file radgen.f.
View newest version in sPHENIX GitHub at line 2002 of file radgen.f
References c, and y.
Referenced by rv2().
subroutine ffdeu (t, gc, gm, gq)
Definition at line 1610 of file radgen.f.
View newest version in sPHENIX GitHub at line 1610 of file radgen.f
References c, eta, i, and t.
Referenced by strf().
subroutine ffhe3 (t, ge, gm)
Definition at line 1721 of file radgen.f.
View newest version in sPHENIX GitHub at line 1721 of file radgen.f
References c, ddexp(), p, and t.
Referenced by strf().
subroutine ffhe4 (dq2, ge, gm)
Definition at line 1748 of file radgen.f.
View newest version in sPHENIX GitHub at line 1748 of file radgen.f
References i.
Referenced by strf().
subroutine ffpro (t, gep, gmp)
Definition at line 1592 of file radgen.f.
View newest version in sPHENIX GitHub at line 1592 of file radgen.f
References t.
Referenced by ffquas(), and strf().
subroutine ffquas (t, geun, gmun, gepo, gmpo)
Definition at line 1920 of file radgen.f.
View newest version in sPHENIX GitHub at line 1920 of file radgen.f
References ffpro(), supst(), t, and tau.
Referenced by strf().
subroutine ffu (n, bb, bis, bir, bi12, bi1pi2, sir, sis, si12, eis, eir, ei12, ei1pi2, ta)
Definition at line 1183 of file radgen.f.
View newest version in sPHENIX GitHub at line 1183 of file radgen.f
References n, and y.
Referenced by tails().
subroutine fordop ()
Definition at line 1807 of file radgen.f.
View newest version in sPHENIX GitHub at line 1807 of file radgen.f
References e, eps, and forintp().
Referenced by radgen_init().
REAL function forgetp (real Q2)
Definition at line 1789 of file radgen.f.
View newest version in sPHENIX GitHub at line 1789 of file radgen.f
Referenced by strf().
REAL function forintp (real R)
Definition at line 1844 of file radgen.f.
View newest version in sPHENIX GitHub at line 1844 of file radgen.f
References e, forrhop(), and r.
Referenced by fordop(), and strf().
REAL function forrhop (real R)
Definition at line 1865 of file radgen.f.
View newest version in sPHENIX GitHub at line 1865 of file radgen.f
References r.
Referenced by forintp().
double precision function fspen (x)
Definition at line 989 of file radgen.f.
View newest version in sPHENIX GitHub at line 989 of file radgen.f
References fspens(), and x.
Referenced by deltas().
double precision function fspens (x)
Definition at line 963 of file radgen.f.
View newest version in sPHENIX GitHub at line 963 of file radgen.f
References f, and x.
Referenced by fspen().
subroutine intbtk2 (dimension(8) dbtk, nbtk, dtkmax)
Definition at line 2052 of file radgen.f.
View newest version in sPHENIX GitHub at line 2052 of file radgen.f
References pi, s, x, and y.
Referenced by qqt().
subroutine inttk2 (isumtk, dbtk1, dbtk2, dsumtk, derrtk)
Definition at line 2111 of file radgen.f.
View newest version in sPHENIX GitHub at line 2111 of file radgen.f
References pi, and rv2().
Referenced by qqt().
subroutine itafun (ys, xs, pl, pn, ixytest, itagen)
Definition at line 2169 of file radgen.f.
View newest version in sPHENIX GitHub at line 2169 of file radgen.f
References i, HiMain1::nt(), print(), r1, rlu(), small, Acts::ExaTrkXTimer::stop(), x, and y.
Referenced by radgen().
subroutine mpolrad (real e1curr, real yscurr, real xscurr, real uncurr, real plcurr, real pncurr, itagen)
Definition at line 435 of file radgen.f.
View newest version in sPHENIX GitHub at line 435 of file radgen.f
References bornin(), conk2(), deltas(), in, Acts::Logger::log(), Jetscape::JetScapeParticleBase::pl(), qqt(), and small.
Referenced by radgen(), and xytabl().
subroutine phidst_pol ()
Definition at line 119 of file radgen.f.
View newest version in sPHENIX GitHub at line 119 of file radgen.f
References dfufi_pol(), dy, dz, i, j, k, pi, and radquad_pol().
Referenced by radgam_pol().
double precision function podinl (r)
Definition at line 1244 of file radgen.f.
View newest version in sPHENIX GitHub at line 1244 of file radgen.f
References ValueGen1::i1(), ValueGen1::i2(), pi, Jetscape::JetScapeParticleBase::pl(), HiStrng::pp(), r, strf(), vacpol(), and y.
Referenced by dfufi_pol(), radgam_pol(), and rv2().
subroutine qqt (bo, tai)
Definition at line 1021 of file radgen.f.
View newest version in sPHENIX GitHub at line 1021 of file radgen.f
References intbtk2(), inttk2(), Acts::detail::PhiBoundParameterLimits::max(), pi, and rv2().
Referenced by mpolrad().
subroutine radgam_pol (erad, yrad, xrad, genphi, ixytest, itagen, q2tr, anutr)
Definition at line 164 of file radgen.f.
View newest version in sPHENIX GitHub at line 164 of file radgen.f
References conk2(), deg, e, phidst_pol(), podinl(), r1, r2, r3, rlu(), sngl, tails(), and y.
Referenced by radgen().
subroutine radgen (real e1, real q2l, real nul, real ys, real xs, real phil, real, dimension(*) PhRAD, real q2tr, real anutr, real WEIGHT)
Definition at line 40 of file radgen.f.
View newest version in sPHENIX GitHub at line 40 of file radgen.f
References itafun(), mpolrad(), radgam_pol(), sngl, and Acts::MultiEigenStepperLoop< extensionlist_t, component_reducer_t, auctioneer_t >::ComponentProxyBase< component_t >::weight().
Referenced by radgen_event().
subroutine radquad_pol (external dfunct, dlow, dup, dimension(31) dx, dimension(31) dy, dimension(31) dz, dh, ndim)
Definition at line 401 of file radgen.f.
View newest version in sPHENIX GitHub at line 401 of file radgen.f
References dy, dz, and i.
Referenced by phidst_pol().
double precision function rv2 (ta)
Definition at line 1293 of file radgen.f.
View newest version in sPHENIX GitHub at line 1293 of file radgen.f
References dqn32(), Acts::Logger::log(), podinl(), PHHepMCGenEventMap::rend(), strf(), tails(), and y.
Referenced by inttk2(), and qqt().
subroutine strf (ta, rr, dimension(8) sfm)
Definition at line 1358 of file radgen.f.
View newest version in sPHENIX GitHub at line 1358 of file radgen.f
References b1, f2(), fc, fdilut(), ffdeu(), ffhe3(), ffhe4(), ffpro(), ffquas(), forgetp(), forintp(), gen(), mkasym(), mkf2(), mkr(), mstp, sngl, t, tau, and y.
Referenced by bornin(), podinl(), and rv2().
double precision function supst (t)
Definition at line 1962 of file radgen.f.
View newest version in sPHENIX GitHub at line 1962 of file radgen.f
References t.
Referenced by ffquas().
subroutine tails (ta, dimension(8,6) tm)
Definition at line 1068 of file radgen.f.
View newest version in sPHENIX GitHub at line 1068 of file radgen.f
References b1, c2, EoS::cs(), ffu(), i, ValueGen1::i1(), ValueGen1::i2(), j, k, pi, s, x, and y.
Referenced by dfufi_pol(), radgam_pol(), and rv2().
double precision function vacpol (y)
Definition at line 915 of file radgen.f.
View newest version in sPHENIX GitHub at line 915 of file radgen.f
References c, i, k, Acts::Logger::log(), pi, Acts::ExaTrkXTimer::stop(), and y.
Referenced by deltas(), and podinl().
subroutine xytabl (character*256 tname, e1, plrun, pnrun, ixytest, ire)
Definition at line 2327 of file radgen.f.
View newest version in sPHENIX GitHub at line 2327 of file radgen.f
References e, file, mpolrad(), small, step, Acts::ExaTrkXTimer::stop(), width, x, y, and ylim.
Referenced by radgen_init().