Analysis Software: QAG4SimulationUpsilon Class Reference
QAG4SimulationUpsilon Class Reference
#include <coresoftware/blob/master/offline/QA/modules/QAG4SimulationUpsilon.h>
Public Member Functions
QAG4SimulationUpsilon (const std::string &name="QAG4SimulationUpsilon")
virtual ~QAG4SimulationUpsilon ()
int Init (PHCompositeNode *topNode)
int InitRun (PHCompositeNode *topNode)
int process_event (PHCompositeNode *topNode)
std::string get_histo_prefix ()
void addEmbeddingID (int embeddingID)
void setEtaRange (double low, double high)
void setQuarkoniaPID (const int pid)
void setDaughterAbsPID (const int pid)
Public Member Functions inherited from SubsysReco
~SubsysReco () override
virtual int End (PHCompositeNode *)
Called at the end of all processing.
virtual int EndRun (const int)
Called at the end of each run.
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
void Print (const std::string &="ALL") const override
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Private Attributes
std::shared_ptr< SvtxEvalStack > _svtxEvalStack
std::set< int > m_embeddingIDs
std::pair< double, double > m_etaRange
PHG4TruthInfoContainer * _truthContainer
int m_quarkoniaPID = 553
int m_daughterAbsPID = 11
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = std::numeric_limits<int>::max() - 10
}
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Detailed Description
Definition at line 16 of file QAG4SimulationUpsilon.h.
View newest version in sPHENIX GitHub at line 16 of file QAG4SimulationUpsilon.h
Constructor & Destructor Documentation
QAG4SimulationUpsilon::QAG4SimulationUpsilon (const std::string & name = "QAG4SimulationUpsilon")
Definition at line 39 of file QAG4SimulationUpsilon.cc.
View newest version in sPHENIX GitHub at line 39 of file QAG4SimulationUpsilon.cc
virtual QAG4SimulationUpsilon::~QAG4SimulationUpsilon () inline virtual
Definition at line 20 of file QAG4SimulationUpsilon.h.
View newest version in sPHENIX GitHub at line 20 of file QAG4SimulationUpsilon.h
Member Function Documentation
void QAG4SimulationUpsilon::addEmbeddingID (int embeddingID)
If added, only process truth particle associated with the selected list of EmbeddingIDs Call multiple times to add multiple EmbeddingIDs For EmbeddingID<0, all negative embedding IDs are accepted for pile up events.
Definition at line 134 of file QAG4SimulationUpsilon.cc.
View newest version in sPHENIX GitHub at line 134 of file QAG4SimulationUpsilon.cc
References m_embeddingIDs.
Referenced by Tracking_QA().
std::string QAG4SimulationUpsilon::get_histo_prefix ()
Definition at line 404 of file QAG4SimulationUpsilon.cc.
View newest version in sPHENIX GitHub at line 404 of file QAG4SimulationUpsilon.cc
References Fun4AllBase::Name().
Referenced by Init(), and process_event().
int QAG4SimulationUpsilon::Init (PHCompositeNode *) virtual
Called during initialization. Typically this is where you can book histograms, and e.g. register them to Fun4AllServer (so they can be output to file using Fun4AllServer::dumpHistos() method).
Reimplemented from SubsysReco.
Definition at line 69 of file QAG4SimulationUpsilon.cc.
View newest version in sPHENIX GitHub at line 69 of file QAG4SimulationUpsilon.cc
References assert, Fun4AllReturnCodes::EVENT_OK, get_histo_prefix(), QAHistManagerDef::getHistoManager(), h, i, Fun4AllHistoManager::registerHisto(), and QAHistManagerDef::useLogBins().
int QAG4SimulationUpsilon::InitRun (PHCompositeNode *) virtual
Called for first event when run number is known. Typically this is where you may want to fetch data from database, because you know the run number.
Reimplemented from SubsysReco.
Definition at line 47 of file QAG4SimulationUpsilon.cc.
View newest version in sPHENIX GitHub at line 47 of file QAG4SimulationUpsilon.cc
References _svtxEvalStack, _truthContainer, assert, Fun4AllReturnCodes::EVENT_OK, and Fun4AllBase::Verbosity().
int QAG4SimulationUpsilon::process_event (PHCompositeNode *) virtual
Called for each event. This is where you do the real work.
Reimplemented from SubsysReco.
Definition at line 139 of file QAG4SimulationUpsilon.cc.
View newest version in sPHENIX GitHub at line 139 of file QAG4SimulationUpsilon.cc
References _svtxEvalStack, _truthContainer, Fun4AllReturnCodes::ABORTRUN, assert, SvtxTrackEval::best_track_from(), Acts::UnitConstants::e, Fun4AllReturnCodes::EVENT_OK, SvtxTruthEval::get_embed(), get_histo_prefix(), PHG4Particle::get_pid(), PHG4Particle::get_px(), SvtxTrack::get_px(), PHG4Particle::get_py(), SvtxTrack::get_py(), PHG4Particle::get_pz(), SvtxTrack::get_pz(), geta, Fun4AllHistoManager::getHisto(), QAHistManagerDef::getHistoManager(), PHG4TruthInfoContainer::GetPrimaryParticleRange(), gpx, gpy, gpz, PHG4Particle::identify(), m_daughterAbsPID, m_embeddingIDs, m_etaRange, m_quarkoniaPID, train_ambiguity_solver::pid, physmon_track_finding_ttbar::pt, testSigmaEff::v, and Fun4AllBase::Verbosity().
void QAG4SimulationUpsilon::setDaughterAbsPID (const int pid) inline
Definition at line 45 of file QAG4SimulationUpsilon.h.
View newest version in sPHENIX GitHub at line 45 of file QAG4SimulationUpsilon.h
References m_daughterAbsPID, and train_ambiguity_solver::pid.
void QAG4SimulationUpsilon::setEtaRange (double low, double high) inline
Definition at line 34 of file QAG4SimulationUpsilon.h.
View newest version in sPHENIX GitHub at line 34 of file QAG4SimulationUpsilon.h
References m_etaRange.
void QAG4SimulationUpsilon::setQuarkoniaPID (const int pid) inline
Definition at line 40 of file QAG4SimulationUpsilon.h.
View newest version in sPHENIX GitHub at line 40 of file QAG4SimulationUpsilon.h
References m_quarkoniaPID, and train_ambiguity_solver::pid.
Member Data Documentation
std::shared_ptr<SvtxEvalStack> QAG4SimulationUpsilon::_svtxEvalStack private
Definition at line 51 of file QAG4SimulationUpsilon.h.
View newest version in sPHENIX GitHub at line 51 of file QAG4SimulationUpsilon.h
Referenced by InitRun(), and process_event().
PHG4TruthInfoContainer* QAG4SimulationUpsilon::_truthContainer private
Definition at line 55 of file QAG4SimulationUpsilon.h.
View newest version in sPHENIX GitHub at line 55 of file QAG4SimulationUpsilon.h
Referenced by InitRun(), and process_event().
int QAG4SimulationUpsilon::m_daughterAbsPID = 11 private
Definition at line 58 of file QAG4SimulationUpsilon.h.
View newest version in sPHENIX GitHub at line 58 of file QAG4SimulationUpsilon.h
Referenced by process_event(), and setDaughterAbsPID().
std::set<int> QAG4SimulationUpsilon::m_embeddingIDs private
Definition at line 52 of file QAG4SimulationUpsilon.h.
View newest version in sPHENIX GitHub at line 52 of file QAG4SimulationUpsilon.h
Referenced by addEmbeddingID(), and process_event().
std::pair<double, double> QAG4SimulationUpsilon::m_etaRange private
Definition at line 53 of file QAG4SimulationUpsilon.h.
View newest version in sPHENIX GitHub at line 53 of file QAG4SimulationUpsilon.h
Referenced by process_event(), and setEtaRange().
int QAG4SimulationUpsilon::m_quarkoniaPID = 553 private
Definition at line 57 of file QAG4SimulationUpsilon.h.
View newest version in sPHENIX GitHub at line 57 of file QAG4SimulationUpsilon.h
Referenced by process_event(), and setQuarkoniaPID().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/QA/modules/QAG4SimulationUpsilon.h
coresoftware/blob/master/offline/QA/modules/QAG4SimulationUpsilon.cc