Analysis Software: HelixHoughBin Class Reference
HelixHoughBin Class Reference
#include <coresoftware/blob/master/offline/packages/trackreco/HelixHoughBin.h>
Public Types
typedef std::set< unsigned int > ClusterSet
typedef std::set< unsigned int >
::const_iterator ConstClusterIter
typedef std::set< unsigned int >
::iterator ClusterIter
Public Member Functions
~HelixHoughBin () override
void identify (std::ostream &os=std::cout) const override
int isValid () const override
isValid returns non zero if object contains vailid data
PHObject * CloneMe () const override
Virtual copy constructor.
virtual void init ()
virtual void add_cluster_ID (unsigned int cluster_ID)
virtual unsigned int get_count () const
virtual void clear_clusters ()
virtual bool empty_clusters ()
virtual size_t erase_cluster (unsigned int cluster_id)
virtual ConstClusterIter begin_clusters () const
virtual ConstClusterIter find_cluster (unsigned int cluster_id) const
virtual ConstClusterIter end_clusters () const
virtual ClusterIter begin_clusters ()
virtual ClusterIter find_cluster (unsigned int cluster_id)
virtual ClusterIter end_clusters ()
virtual unsigned int get_bin (unsigned int zoomlevel) const
virtual void set_bin (unsigned int zoomlevel, unsigned int bin)
virtual unsigned int get_zoomlevel () const
virtual void set_zoomlevel (unsigned int zoomlevel)
virtual unsigned int get_kappa_bin (unsigned int zoomlevel) const
virtual void set_kappa_bin (unsigned int zoomlevel, unsigned int kappa_bin)
virtual unsigned int get_phi_bin (unsigned int zoomlevel) const
virtual void set_phi_bin (unsigned int zoomlevel, unsigned int phi_bin)
virtual unsigned int get_phi_high_bin (unsigned int zoomlevel) const
virtual void set_phi_high_bin (unsigned int zoomlevel)
virtual void set_phi_high_bin (unsigned int zoomlevel, unsigned int phi_high_bin)
virtual unsigned int get_phi_low_bin (unsigned int zoomlevel) const
virtual void set_phi_low_bin (unsigned int zoomlevel)
virtual void set_phi_low_bin (unsigned int zoomlevel, unsigned int phi_low_bin)
virtual unsigned int get_d_bin (unsigned int zoomlevel) const
virtual void set_d_bin (unsigned int zoomlevel, unsigned int d_bin)
virtual unsigned int get_dzdl_bin (unsigned int zoomlevel) const
virtual void set_dzdl_bin (unsigned int zoomlevel, unsigned int dzdl_bin)
virtual unsigned int get_dzdl_high_bin (unsigned int zoomlevel) const
virtual void set_dzdl_high_bin (unsigned int zoomlevel)
virtual void set_dzdl_high_bin (unsigned int zoomlevel, unsigned int dzdl_high_bin)
virtual unsigned int get_dzdl_low_bin (unsigned int zoomlevel) const
virtual void set_dzdl_low_bin (unsigned int zoomlevel)
virtual void set_dzdl_low_bin (unsigned int zoomlevel, unsigned int dzdl_low_bin)
virtual unsigned int get_z0_bin (unsigned int zoomlevel) const
virtual void set_z0_bin (unsigned int zoomlevel, unsigned int z0_bin)
virtual void set_hough_space (HelixHoughSpace *hough_space)
virtual void set_bins (unsigned int zoomlevel, unsigned int bin)
virtual unsigned int get_global_bin (unsigned int zoomlevel)
virtual void set_global_bin (unsigned int zoomlevel)
virtual unsigned int get_neighbors_global_bin (unsigned int zoomlevel, unsigned int var, unsigned int bit_sign)
virtual float get_kappa_center (unsigned int zoomlevel)
virtual float get_phi_center (unsigned int zoomlevel)
virtual float get_d_center (unsigned int zoomlevel)
virtual float get_dzdl_center (unsigned int zoomlevel)
virtual float get_z0_center (unsigned int zoomlevel)
Public Member Functions inherited from PHObject
PHObject ()
ctor
~PHObject () override
dtor
virtual PHObject * clone () const final
PHObject * Clone (const char *newname="") const final
void Copy (TObject &object) const final
virtual void Reset ()
Clear Event.
virtual int isValid (const float) const
virtual int isValid (const double) const
virtual int isValid (const int) const
virtual int isValid (const unsigned int) const
virtual int isImplemented (const float f) const
virtual int isImplemented (const double f) const
virtual int isImplemented (const int i) const
virtual int isImplemented (const unsigned int i) const
virtual int Integrate () const
virtual int Integrate (PHObject *obj)
virtual void CopyFrom (const PHObject *obj)
Protected Member Functions
HelixHoughBin ()
ClassDefOverride (HelixHoughBin, 1)
Detailed Description
Definition at line 19 of file HelixHoughBin.h.
View newest version in sPHENIX GitHub at line 19 of file HelixHoughBin.h
Member Typedef Documentation
typedef std::set<unsigned int>::iterator HelixHoughBin::ClusterIter
Definition at line 24 of file HelixHoughBin.h.
View newest version in sPHENIX GitHub at line 24 of file HelixHoughBin.h
typedef std::set<unsigned int> HelixHoughBin::ClusterSet
Definition at line 22 of file HelixHoughBin.h.
View newest version in sPHENIX GitHub at line 22 of file HelixHoughBin.h
typedef std::set<unsigned int>::const_iterator HelixHoughBin::ConstClusterIter
Definition at line 23 of file HelixHoughBin.h.
View newest version in sPHENIX GitHub at line 23 of file HelixHoughBin.h
Constructor & Destructor Documentation
HelixHoughBin::~HelixHoughBin () inline override
Definition at line 26 of file HelixHoughBin.h.
View newest version in sPHENIX GitHub at line 26 of file HelixHoughBin.h
HelixHoughBin::HelixHoughBin () inline protected
Definition at line 95 of file HelixHoughBin.h.
View newest version in sPHENIX GitHub at line 95 of file HelixHoughBin.h
Member Function Documentation
virtual void HelixHoughBin::add_cluster_ID (unsigned int cluster_ID) inline virtual
Reimplemented in HelixHoughBin_v1.
Definition at line 39 of file HelixHoughBin.h.
View newest version in sPHENIX GitHub at line 39 of file HelixHoughBin.h
Referenced by PHInitZVertexing::prune_xy(), PHPatternReco::prune_xy(), PHInitZVertexing::prune_z(), PHPatternReco::prune_z(), PHInitZVertexing::vote_xy(), PHPatternReco::vote_xy(), PHInitZVertexing::vote_z(), and PHPatternReco::vote_z().
HelixHoughBin::ConstClusterIter HelixHoughBin::begin_clusters () const virtual
Reimplemented in HelixHoughBin_v1.
Definition at line 5 of file HelixHoughBin.cc.
View newest version in sPHENIX GitHub at line 5 of file HelixHoughBin.cc
References HelixHoughBinClusterSet.
Referenced by PHInitZVertexing::bins_to_SimpleTrack3D(), PHPatternReco::bins_to_SimpleTrack3D(), PHInitZVertexing::vote_xy(), and PHPatternReco::vote_xy().
HelixHoughBin::ClusterIter HelixHoughBin::begin_clusters () virtual
Reimplemented in HelixHoughBin_v1.
Definition at line 19 of file HelixHoughBin.cc.
View newest version in sPHENIX GitHub at line 19 of file HelixHoughBin.cc
References HelixHoughBinClusterSet.
HelixHoughBin::ClassDefOverride (HelixHoughBin , 1) protected
virtual void HelixHoughBin::clear_clusters () inline virtual
Reimplemented in HelixHoughBin_v1.
Definition at line 41 of file HelixHoughBin.h.
View newest version in sPHENIX GitHub at line 41 of file HelixHoughBin.h
Referenced by PHInitZVertexing::vote_xy(), PHPatternReco::vote_xy(), PHInitZVertexing::vote_z(), and PHPatternReco::vote_z().
PHObject* HelixHoughBin::CloneMe () const inline override virtual
Virtual copy constructor.
Reimplemented from PHObject.
Reimplemented in HelixHoughBin_v1.
Definition at line 34 of file HelixHoughBin.h.
View newest version in sPHENIX GitHub at line 34 of file HelixHoughBin.h
Referenced by PHInitZVertexing::vote_xy(), and PHInitZVertexing::vote_z().
virtual bool HelixHoughBin::empty_clusters () inline virtual
Reimplemented in HelixHoughBin_v1.
Definition at line 42 of file HelixHoughBin.h.
View newest version in sPHENIX GitHub at line 42 of file HelixHoughBin.h
HelixHoughBin::ConstClusterIter HelixHoughBin::end_clusters () const virtual
Reimplemented in HelixHoughBin_v1.
Definition at line 14 of file HelixHoughBin.cc.
View newest version in sPHENIX GitHub at line 14 of file HelixHoughBin.cc
References HelixHoughBinClusterSet.
Referenced by PHInitZVertexing::bins_to_SimpleTrack3D(), PHPatternReco::bins_to_SimpleTrack3D(), PHInitZVertexing::vote_xy(), and PHPatternReco::vote_xy().
HelixHoughBin::ClusterIter HelixHoughBin::end_clusters () virtual
Reimplemented in HelixHoughBin_v1.
Definition at line 29 of file HelixHoughBin.cc.
View newest version in sPHENIX GitHub at line 29 of file HelixHoughBin.cc
References HelixHoughBinClusterSet.
virtual size_t HelixHoughBin::erase_cluster (unsigned int cluster_id) inline virtual
Reimplemented in HelixHoughBin_v1.
Definition at line 43 of file HelixHoughBin.h.
View newest version in sPHENIX GitHub at line 43 of file HelixHoughBin.h
HelixHoughBin::ConstClusterIter HelixHoughBin::find_cluster (unsigned int cluster_id) const virtual
Reimplemented in HelixHoughBin_v1.
Definition at line 10 of file HelixHoughBin.cc.
View newest version in sPHENIX GitHub at line 10 of file HelixHoughBin.cc
References HelixHoughBinClusterSet.
HelixHoughBin::ClusterIter HelixHoughBin::find_cluster (unsigned int cluster_id) virtual
Reimplemented in HelixHoughBin_v1.
Definition at line 24 of file HelixHoughBin.cc.
View newest version in sPHENIX GitHub at line 24 of file HelixHoughBin.cc
References HelixHoughBinClusterSet.
virtual unsigned int HelixHoughBin::get_bin (unsigned int zoomlevel) const inline virtual
Reimplemented in HelixHoughBin_v1.
Definition at line 51 of file HelixHoughBin.h.
View newest version in sPHENIX GitHub at line 51 of file HelixHoughBin.h
virtual unsigned int HelixHoughBin::get_count () const inline virtual
Reimplemented in HelixHoughBin_v1.
Definition at line 40 of file HelixHoughBin.h.
View newest version in sPHENIX GitHub at line 40 of file HelixHoughBin.h
Referenced by PHInitZVertexing::bins_to_SimpleTrack3D(), PHPatternReco::bins_to_SimpleTrack3D(), PHInitZVertexing::find_track_candidates_xy(), PHPatternReco::find_track_candidates_xy(), PHInitZVertexing::find_track_candidates_z(), PHPatternReco::find_track_candidates_z(), PHInitZVertexing::prune_xy(), PHPatternReco::prune_xy(), PHInitZVertexing::prune_z(), PHPatternReco::prune_z(), PHInitZVertexing::vote_xy(), and PHPatternReco::vote_xy().
virtual unsigned int HelixHoughBin::get_d_bin (unsigned int zoomlevel) const inline virtual
Reimplemented in HelixHoughBin_v1.
Definition at line 67 of file HelixHoughBin.h.
View newest version in sPHENIX GitHub at line 67 of file HelixHoughBin.h
Referenced by PHInitZVertexing::find_track_candidates_xy(), PHPatternReco::find_track_candidates_xy(), PHInitZVertexing::prune_xy(), PHPatternReco::prune_xy(), PHInitZVertexing::prune_z(), PHPatternReco::prune_z(), PHInitZVertexing::vote_xy(), and PHPatternReco::vote_xy().
virtual float HelixHoughBin::get_d_center (unsigned int zoomlevel) inline virtual
Reimplemented in HelixHoughBin_v1.
Definition at line 90 of file HelixHoughBin.h.
View newest version in sPHENIX GitHub at line 90 of file HelixHoughBin.h
Referenced by PHInitZVertexing::vote_xy(), PHPatternReco::vote_xy(), PHInitZVertexing::vote_z(), and PHPatternReco::vote_z().
virtual unsigned int HelixHoughBin::get_dzdl_bin (unsigned int zoomlevel) const inline virtual
Reimplemented in HelixHoughBin_v1.
Definition at line 69 of file HelixHoughBin.h.
View newest version in sPHENIX GitHub at line 69 of file HelixHoughBin.h
Referenced by PHInitZVertexing::find_track_candidates_xy(), PHPatternReco::find_track_candidates_xy(), PHInitZVertexing::find_track_candidates_z(), PHPatternReco::find_track_candidates_z(), PHInitZVertexing::prune_xy(), PHPatternReco::prune_xy(), PHInitZVertexing::prune_z(), PHPatternReco::prune_z(), PHInitZVertexing::vote_xy(), PHPatternReco::vote_xy(), and PHInitZVertexing::vote_z().
virtual float HelixHoughBin::get_dzdl_center (unsigned int zoomlevel) inline virtual
Reimplemented in HelixHoughBin_v1.
Definition at line 91 of file HelixHoughBin.h.
View newest version in sPHENIX GitHub at line 91 of file HelixHoughBin.h
Referenced by PHInitZVertexing::bins_to_SimpleTrack3D(), PHPatternReco::bins_to_SimpleTrack3D(), PHInitZVertexing::vote_z(), and PHPatternReco::vote_z().
virtual unsigned int HelixHoughBin::get_dzdl_high_bin (unsigned int zoomlevel) const inline virtual
Reimplemented in HelixHoughBin_v1.
Definition at line 71 of file HelixHoughBin.h.
View newest version in sPHENIX GitHub at line 71 of file HelixHoughBin.h
virtual unsigned int HelixHoughBin::get_dzdl_low_bin (unsigned int zoomlevel) const inline virtual
Reimplemented in HelixHoughBin_v1.
Definition at line 74 of file HelixHoughBin.h.
View newest version in sPHENIX GitHub at line 74 of file HelixHoughBin.h
virtual unsigned int HelixHoughBin::get_global_bin (unsigned int zoomlevel) inline virtual
Reimplemented in HelixHoughBin_v1.
Definition at line 83 of file HelixHoughBin.h.
View newest version in sPHENIX GitHub at line 83 of file HelixHoughBin.h
Referenced by PHInitZVertexing::prune_xy(), PHPatternReco::prune_xy(), PHInitZVertexing::prune_z(), PHPatternReco::prune_z(), PHInitZVertexing::vote_xy(), PHPatternReco::vote_xy(), PHInitZVertexing::vote_z(), and PHPatternReco::vote_z().
virtual unsigned int HelixHoughBin::get_kappa_bin (unsigned int zoomlevel) const inline virtual
Reimplemented in HelixHoughBin_v1.
Definition at line 57 of file HelixHoughBin.h.
View newest version in sPHENIX GitHub at line 57 of file HelixHoughBin.h
Referenced by PHInitZVertexing::find_track_candidates_xy(), PHPatternReco::find_track_candidates_xy(), PHInitZVertexing::prune_xy(), PHPatternReco::prune_xy(), PHInitZVertexing::prune_z(), PHPatternReco::prune_z(), PHInitZVertexing::vote_xy(), and PHPatternReco::vote_xy().
virtual float HelixHoughBin::get_kappa_center (unsigned int zoomlevel) inline virtual
Reimplemented in HelixHoughBin_v1.
Definition at line 88 of file HelixHoughBin.h.
View newest version in sPHENIX GitHub at line 88 of file HelixHoughBin.h
Referenced by PHInitZVertexing::bins_to_SimpleTrack3D(), PHPatternReco::bins_to_SimpleTrack3D(), PHInitZVertexing::vote_xy(), PHPatternReco::vote_xy(), PHInitZVertexing::vote_z(), and PHPatternReco::vote_z().
virtual unsigned int HelixHoughBin::get_neighbors_global_bin (unsigned int zoomlevel, unsigned int var, unsigned int bit_sign) inline virtual
Reimplemented in HelixHoughBin_v1.
Definition at line 86 of file HelixHoughBin.h.
View newest version in sPHENIX GitHub at line 86 of file HelixHoughBin.h
Referenced by PHInitZVertexing::prune_xy(), PHPatternReco::prune_xy(), PHInitZVertexing::prune_z(), and PHPatternReco::prune_z().
virtual unsigned int HelixHoughBin::get_phi_bin (unsigned int zoomlevel) const inline virtual
Reimplemented in HelixHoughBin_v1.
Definition at line 59 of file HelixHoughBin.h.
View newest version in sPHENIX GitHub at line 59 of file HelixHoughBin.h
Referenced by PHInitZVertexing::find_track_candidates_xy(), PHPatternReco::find_track_candidates_xy(), PHInitZVertexing::prune_xy(), PHPatternReco::prune_xy(), PHInitZVertexing::prune_z(), PHPatternReco::prune_z(), PHInitZVertexing::vote_xy(), PHPatternReco::vote_xy(), and PHInitZVertexing::vote_z().
virtual float HelixHoughBin::get_phi_center (unsigned int zoomlevel) inline virtual
Reimplemented in HelixHoughBin_v1.
Definition at line 89 of file HelixHoughBin.h.
View newest version in sPHENIX GitHub at line 89 of file HelixHoughBin.h
Referenced by PHInitZVertexing::bins_to_SimpleTrack3D(), PHPatternReco::bins_to_SimpleTrack3D(), PHInitZVertexing::vote_xy(), PHPatternReco::vote_xy(), PHInitZVertexing::vote_z(), and PHPatternReco::vote_z().
virtual unsigned int HelixHoughBin::get_phi_high_bin (unsigned int zoomlevel) const inline virtual
Reimplemented in HelixHoughBin_v1.
Definition at line 61 of file HelixHoughBin.h.
View newest version in sPHENIX GitHub at line 61 of file HelixHoughBin.h
virtual unsigned int HelixHoughBin::get_phi_low_bin (unsigned int zoomlevel) const inline virtual
Reimplemented in HelixHoughBin_v1.
Definition at line 64 of file HelixHoughBin.h.
View newest version in sPHENIX GitHub at line 64 of file HelixHoughBin.h
virtual unsigned int HelixHoughBin::get_z0_bin (unsigned int zoomlevel) const inline virtual
Reimplemented in HelixHoughBin_v1.
Definition at line 77 of file HelixHoughBin.h.
View newest version in sPHENIX GitHub at line 77 of file HelixHoughBin.h
Referenced by PHInitZVertexing::find_track_candidates_xy(), PHPatternReco::find_track_candidates_xy(), PHInitZVertexing::find_track_candidates_z(), PHPatternReco::find_track_candidates_z(), PHInitZVertexing::prune_xy(), PHPatternReco::prune_xy(), PHInitZVertexing::prune_z(), PHPatternReco::prune_z(), PHInitZVertexing::vote_xy(), PHPatternReco::vote_xy(), and PHInitZVertexing::vote_z().
virtual float HelixHoughBin::get_z0_center (unsigned int zoomlevel) inline virtual
Reimplemented in HelixHoughBin_v1.
Definition at line 92 of file HelixHoughBin.h.
View newest version in sPHENIX GitHub at line 92 of file HelixHoughBin.h
Referenced by PHInitZVertexing::bins_to_SimpleTrack3D(), PHPatternReco::bins_to_SimpleTrack3D(), PHInitZVertexing::vote_z(), and PHPatternReco::vote_z().
virtual unsigned int HelixHoughBin::get_zoomlevel () const inline virtual
Reimplemented in HelixHoughBin_v1.
Definition at line 54 of file HelixHoughBin.h.
View newest version in sPHENIX GitHub at line 54 of file HelixHoughBin.h
void HelixHoughBin::identify (std::ostream & os = std::cout) const inline override virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from PHObject.
Reimplemented in HelixHoughBin_v1.
Definition at line 29 of file HelixHoughBin.h.
View newest version in sPHENIX GitHub at line 29 of file HelixHoughBin.h
References os.
Referenced by PHInitZVertexing::initialize_houghbin(), and PHPatternReco::initialize_houghbin().
virtual void HelixHoughBin::init (void) inline virtual
Reimplemented in HelixHoughBin_v1.
Definition at line 36 of file HelixHoughBin.h.
View newest version in sPHENIX GitHub at line 36 of file HelixHoughBin.h
Referenced by PHInitZVertexing::initialize_houghbin(), and PHPatternReco::initialize_houghbin().
int HelixHoughBin::isValid () const inline override virtual
isValid returns non zero if object contains vailid data
Reimplemented from PHObject.
Reimplemented in HelixHoughBin_v1.
Definition at line 33 of file HelixHoughBin.h.
View newest version in sPHENIX GitHub at line 33 of file HelixHoughBin.h
virtual void HelixHoughBin::set_bin (unsigned int zoomlevel, unsigned int bin) inline virtual
Reimplemented in HelixHoughBin_v1.
Definition at line 52 of file HelixHoughBin.h.
View newest version in sPHENIX GitHub at line 52 of file HelixHoughBin.h
Referenced by PHInitZVertexing::vote_xy(), PHPatternReco::vote_xy(), PHInitZVertexing::vote_z(), and PHPatternReco::vote_z().
virtual void HelixHoughBin::set_bins (unsigned int zoomlevel, unsigned int bin) inline virtual
Reimplemented in HelixHoughBin_v1.
Definition at line 81 of file HelixHoughBin.h.
View newest version in sPHENIX GitHub at line 81 of file HelixHoughBin.h
Referenced by PHInitZVertexing::vote_xy(), PHPatternReco::vote_xy(), PHInitZVertexing::vote_z(), and PHPatternReco::vote_z().
virtual void HelixHoughBin::set_d_bin (unsigned int zoomlevel, unsigned int d_bin) inline virtual
Reimplemented in HelixHoughBin_v1.
Definition at line 68 of file HelixHoughBin.h.
View newest version in sPHENIX GitHub at line 68 of file HelixHoughBin.h
virtual void HelixHoughBin::set_dzdl_bin (unsigned int zoomlevel, unsigned int dzdl_bin) inline virtual
Reimplemented in HelixHoughBin_v1.
Definition at line 70 of file HelixHoughBin.h.
View newest version in sPHENIX GitHub at line 70 of file HelixHoughBin.h
virtual void HelixHoughBin::set_dzdl_high_bin (unsigned int zoomlevel) inline virtual
Definition at line 72 of file HelixHoughBin.h.
View newest version in sPHENIX GitHub at line 72 of file HelixHoughBin.h
virtual void HelixHoughBin::set_dzdl_high_bin (unsigned int zoomlevel, unsigned int dzdl_high_bin) inline virtual
Reimplemented in HelixHoughBin_v1.
Definition at line 73 of file HelixHoughBin.h.
View newest version in sPHENIX GitHub at line 73 of file HelixHoughBin.h
virtual void HelixHoughBin::set_dzdl_low_bin (unsigned int zoomlevel) inline virtual
Definition at line 75 of file HelixHoughBin.h.
View newest version in sPHENIX GitHub at line 75 of file HelixHoughBin.h
virtual void HelixHoughBin::set_dzdl_low_bin (unsigned int zoomlevel, unsigned int dzdl_low_bin) inline virtual
Reimplemented in HelixHoughBin_v1.
Definition at line 76 of file HelixHoughBin.h.
View newest version in sPHENIX GitHub at line 76 of file HelixHoughBin.h
virtual void HelixHoughBin::set_global_bin (unsigned int zoomlevel) inline virtual
Reimplemented in HelixHoughBin_v1.
Definition at line 84 of file HelixHoughBin.h.
View newest version in sPHENIX GitHub at line 84 of file HelixHoughBin.h
virtual void HelixHoughBin::set_hough_space (HelixHoughSpace * hough_space) inline virtual
Reimplemented in HelixHoughBin_v1.
Definition at line 80 of file HelixHoughBin.h.
View newest version in sPHENIX GitHub at line 80 of file HelixHoughBin.h
Referenced by PHInitZVertexing::initialize_houghbin(), and PHPatternReco::initialize_houghbin().
virtual void HelixHoughBin::set_kappa_bin (unsigned int zoomlevel, unsigned int kappa_bin) inline virtual
Reimplemented in HelixHoughBin_v1.
Definition at line 58 of file HelixHoughBin.h.
View newest version in sPHENIX GitHub at line 58 of file HelixHoughBin.h
virtual void HelixHoughBin::set_phi_bin (unsigned int zoomlevel, unsigned int phi_bin) inline virtual
Reimplemented in HelixHoughBin_v1.
Definition at line 60 of file HelixHoughBin.h.
View newest version in sPHENIX GitHub at line 60 of file HelixHoughBin.h
virtual void HelixHoughBin::set_phi_high_bin (unsigned int zoomlevel) inline virtual
Definition at line 62 of file HelixHoughBin.h.
View newest version in sPHENIX GitHub at line 62 of file HelixHoughBin.h
virtual void HelixHoughBin::set_phi_high_bin (unsigned int zoomlevel, unsigned int phi_high_bin) inline virtual
Reimplemented in HelixHoughBin_v1.
Definition at line 63 of file HelixHoughBin.h.
View newest version in sPHENIX GitHub at line 63 of file HelixHoughBin.h
virtual void HelixHoughBin::set_phi_low_bin (unsigned int zoomlevel) inline virtual
Definition at line 65 of file HelixHoughBin.h.
View newest version in sPHENIX GitHub at line 65 of file HelixHoughBin.h
virtual void HelixHoughBin::set_phi_low_bin (unsigned int zoomlevel, unsigned int phi_low_bin) inline virtual
Reimplemented in HelixHoughBin_v1.
Definition at line 66 of file HelixHoughBin.h.
View newest version in sPHENIX GitHub at line 66 of file HelixHoughBin.h
virtual void HelixHoughBin::set_z0_bin (unsigned int zoomlevel, unsigned int z0_bin) inline virtual
Reimplemented in HelixHoughBin_v1.
Definition at line 78 of file HelixHoughBin.h.
View newest version in sPHENIX GitHub at line 78 of file HelixHoughBin.h
virtual void HelixHoughBin::set_zoomlevel (unsigned int zoomlevel) inline virtual
Reimplemented in HelixHoughBin_v1.
Definition at line 55 of file HelixHoughBin.h.
View newest version in sPHENIX GitHub at line 55 of file HelixHoughBin.h
Referenced by PHInitZVertexing::initialize_houghbin(), PHPatternReco::initialize_houghbin(), PHInitZVertexing::vote_xy(), PHPatternReco::vote_xy(), PHInitZVertexing::vote_z(), and PHPatternReco::vote_z().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/trackreco/HelixHoughBin.h
coresoftware/blob/master/offline/packages/trackreco/HelixHoughBin.cc