Analysis Software: acts/blob/sPHENIX/Tests/UnitTests/Core/Utilities/PeriodicTests.cpp File Reference
PeriodicTests.cpp File Reference
#include <boost/test/data/monomorphic.hpp>
#include <boost/test/data/test_case.hpp>
#include <boost/test/unit_test.hpp>
#include "Acts/Tests/CommonHelpers/FloatComparisons.hpp"
#include "Acts/Utilities/detail/periodic.hpp"
#include <cmath>
#include <limits>
#include <tuple>
#include <utility>
Functions
BOOST_DATA_TEST_CASE (DifferencePeriodic, bd::make(kDifferencePeriodicDataset), lhs, rhs, range, diff)
BOOST_DATA_TEST_CASE (RadianPos, bd::xrange(0.25, M_PI, 0.5), delta)
BOOST_DATA_TEST_CASE (RadianSym, bd::xrange(0.25, M_PI, 0.5), delta)
BOOST_DATA_TEST_CASE (NormalizePhiThetaInBounds, bd::xrange(-M_PI, M_PI, M_PI_2)*bd::xrange(0.0, M_PI, M_PI_4), phix, thetax)
BOOST_DATA_TEST_CASE (NormalizePhiThetaCyclicPhi, bd::xrange(0.25, M_PI, 0.5)*bd::xrange(0.0, M_PI, M_PI_4), deltaPhi, thetax)
BOOST_DATA_TEST_CASE (NormalizePhiThetaOutOfBoundsTheta, bd::xrange(0.0, M_PI, 1.0)*bd::xrange(0.25, M_PI, 1.0), positivePhi, deltaTheta)
Function Documentation
BOOST_DATA_TEST_CASE (DifferencePeriodic , bd:: makekDifferencePeriodicDataset, lhs , rhs , range , diff)
Definition at line 60 of file PeriodicTests.cpp.
View newest version in sPHENIX GitHub at line 60 of file PeriodicTests.cpp
References CHECK_CLOSE_ABS, Acts::detail::difference_periodic(), check_smearing_config::lhs, and check_smearing_config::rhs.
BOOST_DATA_TEST_CASE (RadianPos , bd:: xrange0.25, M_PI, 0.5, delta)
Definition at line 66 of file PeriodicTests.cpp.
View newest version in sPHENIX GitHub at line 66 of file PeriodicTests.cpp
References CHECK_CLOSE_ABS, physmon_vertexing::delta, and Acts::detail::radian_pos().
BOOST_DATA_TEST_CASE (RadianSym , bd:: xrange0.25, M_PI, 0.5, delta)
Definition at line 76 of file PeriodicTests.cpp.
View newest version in sPHENIX GitHub at line 76 of file PeriodicTests.cpp
References CHECK_CLOSE_ABS, physmon_vertexing::delta, and Acts::detail::radian_sym().
BOOST_DATA_TEST_CASE (NormalizePhiThetaInBounds , bd:: xrange-M_PI, M_PI, M_PI_2)*bd::xrange(0.0, M_PI, M_PI_4, phix , thetax)
Definition at line 86 of file PeriodicTests.cpp.
View newest version in sPHENIX GitHub at line 86 of file PeriodicTests.cpp
References CHECK_CLOSE_ABS, Acts::detail::normalizePhiTheta(), ActsTests::PropagationDatasets::phi, and ActsTests::PropagationDatasets::theta.
BOOST_DATA_TEST_CASE (NormalizePhiThetaCyclicPhi , bd:: xrange0.25, M_PI, 0.5)*bd::xrange(0.0, M_PI, M_PI_4, deltaPhi , thetax)
Definition at line 96 of file PeriodicTests.cpp.
View newest version in sPHENIX GitHub at line 96 of file PeriodicTests.cpp
References CHECK_CLOSE_ABS, deltaPhi(), Acts::detail::normalizePhiTheta(), ActsTests::PropagationDatasets::phi, and ActsTests::PropagationDatasets::theta.
BOOST_DATA_TEST_CASE (NormalizePhiThetaOutOfBoundsTheta , bd:: xrange0.0, M_PI, 1.0)*bd::xrange(0.25, M_PI, 1.0, positivePhi , deltaTheta)
Definition at line 115 of file PeriodicTests.cpp.
View newest version in sPHENIX GitHub at line 115 of file PeriodicTests.cpp
References CHECK_CLOSE_ABS, Acts::detail::normalizePhiTheta(), ActsTests::PropagationDatasets::phi, and ActsTests::PropagationDatasets::theta.