Analysis Software: MicromegasCombinedDataEvaluation Class Reference
MicromegasCombinedDataEvaluation Class Reference
micromegas raw data decoder
#include <coresoftware/blob/master/offline/packages/micromegas/MicromegasCombinedDataEvaluation.h>
Classes
class Container
class Sample
class Waveform
Public Member Functions
MicromegasCombinedDataEvaluation (const std::string &name="MicromegasCombinedDataEvaluation")
constructor
int Init (PHCompositeNode *) override
global initialization
int InitRun (PHCompositeNode *) override
run initialization
int process_event (PHCompositeNode *) override
event processing
int End (PHCompositeNode *) override
end of processing
void set_calibration_file (const std::string &value)
calibration file
void set_n_sigma (double value)
set number of RMS sigma used to defined static threshold on a given channel
void set_min_adc (double value)
set minimum ADC value, disregarding pedestal and RMS.
void set_sample_min (int value)
set min sample for noise estimation
void set_sample_max (int value)
set min sample for noise estimation
void set_evaluation_outputfile (const std::string &outputfile)
output file name for evaluation histograms
Public Member Functions inherited from SubsysReco
~SubsysReco () override
virtual int EndRun (const int)
Called at the end of each run.
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
void Print (const std::string &="ALL") const override
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Private Types
using bco_map_t = std::map< uint64_t, unsigned int >
map waveforms to bco
Private Attributes
std::string m_rawhitnodename = "MICROMEGASRAWHIT"
raw node
std::string m_calibration_filename = "TPOT_Pedestal_000.root"
calibration filename
MicromegasCalibrationData m_calibration_data
calibration data
MicromegasMapping m_mapping
mapping
double m_n_sigma = 5
number of RMS sigma used to define threshold
double m_min_adc = 50
minimum ADC value, disregarding pedestal and RMS.
int m_sample_min = 0
min sample for signal
int m_sample_max = 100
max sample for signal
std::string m_evaluation_filename = "MicromegasCombinedDataEvaluation.root"
evaluation output filename
std::unique_ptr< TFile > m_evaluation_file
TTree * m_evaluation_tree = nullptr
tree
Container * m_container = nullptr
main branch
bco_map_t m_bco_map
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = std::numeric_limits<int>::max() - 10
}
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Detailed Description
micromegas raw data decoder
Definition at line 29 of file MicromegasCombinedDataEvaluation.h.
View newest version in sPHENIX GitHub at line 29 of file MicromegasCombinedDataEvaluation.h
Member Typedef Documentation
using MicromegasCombinedDataEvaluation::bco_map_t = std::map<uint64_t,unsigned int> private
map waveforms to bco
this is used to count how many waveforms are found for a given lvl1 bco
Definition at line 226 of file MicromegasCombinedDataEvaluation.h.
View newest version in sPHENIX GitHub at line 226 of file MicromegasCombinedDataEvaluation.h
Constructor & Destructor Documentation
MicromegasCombinedDataEvaluation::MicromegasCombinedDataEvaluation (const std::string & name = "MicromegasCombinedDataEvaluation")
constructor
Definition at line 88 of file MicromegasCombinedDataEvaluation.cc.
View newest version in sPHENIX GitHub at line 88 of file MicromegasCombinedDataEvaluation.cc
Member Function Documentation
int MicromegasCombinedDataEvaluation::End (PHCompositeNode *) override virtual
end of processing
Reimplemented from SubsysReco.
Definition at line 252 of file MicromegasCombinedDataEvaluation.cc.
View newest version in sPHENIX GitHub at line 252 of file MicromegasCombinedDataEvaluation.cc
References test_fpe::count, Fun4AllReturnCodes::EVENT_OK, m_bco_map, m_evaluation_file, m_evaluation_tree, and Fun4AllBase::Verbosity().
int MicromegasCombinedDataEvaluation::Init (PHCompositeNode *) override virtual
global initialization
Reimplemented from SubsysReco.
Definition at line 93 of file MicromegasCombinedDataEvaluation.cc.
View newest version in sPHENIX GitHub at line 93 of file MicromegasCombinedDataEvaluation.cc
References Fun4AllReturnCodes::EVENT_OK, m_calibration_data, m_calibration_filename, m_container, m_evaluation_file, m_evaluation_filename, m_evaluation_tree, and MicromegasCalibrationData::read().
int MicromegasCombinedDataEvaluation::InitRun (PHCompositeNode *) override virtual
run initialization
Reimplemented from SubsysReco.
Definition at line 107 of file MicromegasCombinedDataEvaluation.cc.
View newest version in sPHENIX GitHub at line 107 of file MicromegasCombinedDataEvaluation.cc
References Fun4AllReturnCodes::EVENT_OK.
int MicromegasCombinedDataEvaluation::process_event (PHCompositeNode * topNode) override virtual
event processing
Reimplemented from SubsysReco.
Definition at line 111 of file MicromegasCombinedDataEvaluation.cc.
View newest version in sPHENIX GitHub at line 111 of file MicromegasCombinedDataEvaluation.cc
References MicromegasCombinedDataEvaluation::Sample::adc, MicromegasCombinedDataEvaluation::Waveform::adc_max, assert, parse_cmake_options::begin, MicromegasCombinedDataEvaluation::Sample::channel, MicromegasCombinedDataEvaluation::Sample::checksum_error, end, Fun4AllReturnCodes::EVENT_OK, MicromegasCombinedDataEvaluation::Sample::fee_bco, MicromegasCombinedDataEvaluation::Sample::fee_id, MicromegasMapping::get_hitsetkey(), MicromegasCalibrationData::get_pedestal(), MicromegasMapping::get_physical_strip(), MicromegasCalibrationData::get_rms(), TrkrDefs::getLayer(), MicromegasDefs::getTileId(), MicromegasCombinedDataEvaluation::Waveform::is_signal, MicromegasCombinedDataEvaluation::Sample::layer, MicromegasCombinedDataEvaluation::Sample::lvl1_bco, MicromegasCombinedDataEvaluation::Waveform::lvl1_bco, m_bco_map, m_calibration_data, m_container, m_evaluation_tree, m_mapping, m_min_adc, m_n_sigma, MicromegasDefs::m_packet_ids, m_rawhitnodename, m_sample_max, m_sample_min, testing::internal::move(), MicromegasCombinedDataEvaluation::Container::n_waveform, MicromegasCombinedDataEvaluation::Sample::packet_id, pedestal(), MicromegasCombinedDataEvaluation::Sample::pedestal, MicromegasCombinedDataEvaluation::Container::Reset(), MicromegasCombinedDataEvaluation::Sample::rms, rms(), MicromegasCombinedDataEvaluation::Sample::sampa_address, MicromegasCombinedDataEvaluation::Sample::sampa_channel, MicromegasCombinedDataEvaluation::Sample::sample, MicromegasCombinedDataEvaluation::Waveform::sample_max, MicromegasCombinedDataEvaluation::Container::samples, MicromegasCombinedDataEvaluation::Sample::strip, MicromegasCombinedDataEvaluation::Sample::tile, Fun4AllBase::Verbosity(), and MicromegasCombinedDataEvaluation::Container::waveforms.
void MicromegasCombinedDataEvaluation::set_calibration_file (const std::string & value) inline
calibration file
Definition at line 49 of file MicromegasCombinedDataEvaluation.h.
View newest version in sPHENIX GitHub at line 49 of file MicromegasCombinedDataEvaluation.h
References m_calibration_filename, and value.
void MicromegasCombinedDataEvaluation::set_evaluation_outputfile (const std::string & outputfile) inline
output file name for evaluation histograms
Definition at line 65 of file MicromegasCombinedDataEvaluation.h.
View newest version in sPHENIX GitHub at line 65 of file MicromegasCombinedDataEvaluation.h
References m_evaluation_filename.
void MicromegasCombinedDataEvaluation::set_min_adc (double value) inline
set minimum ADC value, disregarding pedestal and RMS.
This removes faulty channels for which calibration has failed
Definition at line 56 of file MicromegasCombinedDataEvaluation.h.
View newest version in sPHENIX GitHub at line 56 of file MicromegasCombinedDataEvaluation.h
References m_min_adc, and value.
void MicromegasCombinedDataEvaluation::set_n_sigma (double value) inline
set number of RMS sigma used to defined static threshold on a given channel
Definition at line 52 of file MicromegasCombinedDataEvaluation.h.
View newest version in sPHENIX GitHub at line 52 of file MicromegasCombinedDataEvaluation.h
References m_n_sigma, and value.
void MicromegasCombinedDataEvaluation::set_sample_max (int value) inline
set min sample for noise estimation
Definition at line 62 of file MicromegasCombinedDataEvaluation.h.
View newest version in sPHENIX GitHub at line 62 of file MicromegasCombinedDataEvaluation.h
References m_sample_max, and value.
void MicromegasCombinedDataEvaluation::set_sample_min (int value) inline
set min sample for noise estimation
Definition at line 59 of file MicromegasCombinedDataEvaluation.h.
View newest version in sPHENIX GitHub at line 59 of file MicromegasCombinedDataEvaluation.h
References m_sample_min, and value.
Member Data Documentation
bco_map_t MicromegasCombinedDataEvaluation::m_bco_map private
Definition at line 227 of file MicromegasCombinedDataEvaluation.h.
View newest version in sPHENIX GitHub at line 227 of file MicromegasCombinedDataEvaluation.h
Referenced by End(), and process_event().
MicromegasCalibrationData MicromegasCombinedDataEvaluation::m_calibration_data private
calibration data
Definition at line 196 of file MicromegasCombinedDataEvaluation.h.
View newest version in sPHENIX GitHub at line 196 of file MicromegasCombinedDataEvaluation.h
Referenced by Init(), and process_event().
std::string MicromegasCombinedDataEvaluation::m_calibration_filename = "TPOT_Pedestal_000.root" private
calibration filename
Definition at line 193 of file MicromegasCombinedDataEvaluation.h.
View newest version in sPHENIX GitHub at line 193 of file MicromegasCombinedDataEvaluation.h
Referenced by Init(), and set_calibration_file().
Container* MicromegasCombinedDataEvaluation::m_container = nullptr private
main branch
Definition at line 222 of file MicromegasCombinedDataEvaluation.h.
View newest version in sPHENIX GitHub at line 222 of file MicromegasCombinedDataEvaluation.h
Referenced by Init(), and process_event().
std::unique_ptr<TFile> MicromegasCombinedDataEvaluation::m_evaluation_file private
Definition at line 216 of file MicromegasCombinedDataEvaluation.h.
View newest version in sPHENIX GitHub at line 216 of file MicromegasCombinedDataEvaluation.h
Referenced by End(), and Init().
std::string MicromegasCombinedDataEvaluation::m_evaluation_filename = "MicromegasCombinedDataEvaluation.root" private
evaluation output filename
Definition at line 215 of file MicromegasCombinedDataEvaluation.h.
View newest version in sPHENIX GitHub at line 215 of file MicromegasCombinedDataEvaluation.h
Referenced by Init(), and set_evaluation_outputfile().
TTree* MicromegasCombinedDataEvaluation::m_evaluation_tree = nullptr private
tree
Definition at line 219 of file MicromegasCombinedDataEvaluation.h.
View newest version in sPHENIX GitHub at line 219 of file MicromegasCombinedDataEvaluation.h
Referenced by End(), Init(), and process_event().
MicromegasMapping MicromegasCombinedDataEvaluation::m_mapping private
mapping
Definition at line 199 of file MicromegasCombinedDataEvaluation.h.
View newest version in sPHENIX GitHub at line 199 of file MicromegasCombinedDataEvaluation.h
Referenced by process_event().
double MicromegasCombinedDataEvaluation::m_min_adc = 50 private
minimum ADC value, disregarding pedestal and RMS.
Definition at line 206 of file MicromegasCombinedDataEvaluation.h.
View newest version in sPHENIX GitHub at line 206 of file MicromegasCombinedDataEvaluation.h
Referenced by process_event(), and set_min_adc().
double MicromegasCombinedDataEvaluation::m_n_sigma = 5 private
number of RMS sigma used to define threshold
Definition at line 202 of file MicromegasCombinedDataEvaluation.h.
View newest version in sPHENIX GitHub at line 202 of file MicromegasCombinedDataEvaluation.h
Referenced by process_event(), and set_n_sigma().
std::string MicromegasCombinedDataEvaluation::m_rawhitnodename = "MICROMEGASRAWHIT" private
raw node
Definition at line 190 of file MicromegasCombinedDataEvaluation.h.
View newest version in sPHENIX GitHub at line 190 of file MicromegasCombinedDataEvaluation.h
Referenced by process_event().
int MicromegasCombinedDataEvaluation::m_sample_max = 100 private
max sample for signal
Definition at line 212 of file MicromegasCombinedDataEvaluation.h.
View newest version in sPHENIX GitHub at line 212 of file MicromegasCombinedDataEvaluation.h
Referenced by process_event(), and set_sample_max().
int MicromegasCombinedDataEvaluation::m_sample_min = 0 private
min sample for signal
Definition at line 209 of file MicromegasCombinedDataEvaluation.h.
View newest version in sPHENIX GitHub at line 209 of file MicromegasCombinedDataEvaluation.h
Referenced by process_event(), and set_sample_min().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/micromegas/MicromegasCombinedDataEvaluation.h
coresoftware/blob/master/offline/packages/micromegas/MicromegasCombinedDataEvaluation.cc