Analysis Software: Acts::IAxis Class Reference
Acts::IAxis Class Reference abstract
#include <acts/blob/sPHENIX/Core/include/Acts/Utilities/IAxis.hpp>
Public Member Functions
virtual bool isEquidistant () const =0
returns whether the axis is equidistant
virtual bool isVariable () const =0
returns whether the axis is variable
virtual detail::AxisBoundaryType getBoundaryType () const =0
returns the boundary type set in the template param
virtual std::vector< ActsScalar > getBinEdges () const =0
Return a vector of bin edges.
virtual ActsScalar getMin () const =0
get minimum of binning range
virtual ActsScalar getMax () const =0
get maximum of binning range
virtual size_t getNBins () const =0
get total number of bins
Detailed Description
Common base class for all Axis instance. This allows generice handling such as for inspection.
Definition at line 20 of file IAxis.hpp.
View newest version in sPHENIX GitHub at line 20 of file IAxis.hpp
Member Function Documentation
virtual std::vector<ActsScalar> Acts::IAxis::getBinEdges () const pure virtual
Return a vector of bin edges.
Returns
Vector which contains the bin edges
Implemented in Acts::detail::Axis< AxisType::Variable, bdt >, Acts::detail::Axis< AxisType::Equidistant, bdt >, and Acts::TestAxis.
Referenced by Acts::AxisJsonConverter::toJson().
virtual detail::AxisBoundaryType Acts::IAxis::getBoundaryType () const pure virtual
returns the boundary type set in the template param
Returns
AxisBoundaryType of this axis
Implemented in Acts::detail::Axis< AxisType::Variable, bdt >, Acts::detail::Axis< AxisType::Equidistant, bdt >, and Acts::TestAxis.
Referenced by Acts::AxisJsonConverter::toJson().
virtual ActsScalar Acts::IAxis::getMax () const pure virtual
get maximum of binning range
Returns
maximum of binning range
Implemented in Acts::detail::Axis< AxisType::Variable, bdt >, Acts::detail::Axis< AxisType::Equidistant, bdt >, and Acts::TestAxis.
Referenced by Acts::AxisJsonConverter::toJson().
virtual ActsScalar Acts::IAxis::getMin () const pure virtual
get minimum of binning range
Returns
minimum of binning range
Implemented in Acts::detail::Axis< AxisType::Variable, bdt >, Acts::detail::Axis< AxisType::Equidistant, bdt >, and Acts::TestAxis.
Referenced by Acts::AxisJsonConverter::toJson().
virtual size_t Acts::IAxis::getNBins () const pure virtual
get total number of bins
Returns
total number of bins (excluding under-/overflow bins)
Implemented in Acts::detail::Axis< AxisType::Variable, bdt >, Acts::detail::Axis< AxisType::Equidistant, bdt >, and Acts::TestAxis.
Referenced by Acts::AxisJsonConverter::toJson().
virtual bool Acts::IAxis::isEquidistant () const pure virtual
returns whether the axis is equidistant
Returns
bool is equidistant
Implemented in Acts::detail::Axis< AxisType::Variable, bdt >, Acts::detail::Axis< AxisType::Equidistant, bdt >, and Acts::TestAxis.
Referenced by Acts::AxisJsonConverter::toJson().
virtual bool Acts::IAxis::isVariable () const pure virtual
returns whether the axis is variable
Returns
bool is variable
Implemented in Acts::detail::Axis< AxisType::Variable, bdt >, Acts::detail::Axis< AxisType::Equidistant, bdt >, and Acts::TestAxis.
The documentation for this class was generated from the following file:
acts/blob/sPHENIX/Core/include/Acts/Utilities/IAxis.hpp