Analysis Software: ActsExamples::PrototracksToParameters Exception Reference
ActsExamples::PrototracksToParameters Exception Reference final
#include <acts/blob/sPHENIX/Examples/Algorithms/TrackFindingExaTrkX/include/ActsExamples/TrackFindingExaTrkX/PrototracksToParameters.hpp>
Classes
struct Config
Public Member Functions
PrototracksToParameters (Config cfg, Acts::Logging::Level lvl)
~PrototracksToParameters ()
ProcessCode execute (const AlgorithmContext &ctx) const final
const Config & config () const
Const access to the config.
Public Member Functions inherited from ActsExamples::IAlgorithm
IAlgorithm (std::string name, Acts::Logging::Level level=Acts::Logging::INFO)
std::string name () const override
The algorithm name.
ProcessCode internalExecute (const AlgorithmContext &context) final
ProcessCode initialize () override
Initialize the algorithm.
ProcessCode finalize () override
Finalize the algorithm.
Private Attributes
Config m_cfg
Acts::BoundSquareMatrix m_covariance = Acts::BoundSquareMatrix::Zero()
WriteDataHandle< SimSeedContainer > m_outputSeeds {this, "OutputSeeds"}
WriteDataHandle
< ProtoTrackContainer > m_outputProtoTracks
WriteDataHandle
< TrackParametersContainer > m_outputParameters
ReadDataHandle
< SimSpacePointContainer > m_inputSpacePoints
ReadDataHandle
< ProtoTrackContainer > m_inputProtoTracks
Additional Inherited Members
Protected Member Functions inherited from ActsExamples::IAlgorithm
const Acts::Logger & logger () const
Detailed Description
This algorithm computes track parameters for prototracks. Unfortunately, it is not possible to create first seeds from prototracks, and then use the more generic TrackParamEstimationAlgorithm.
The reason is, that in the end we need a consistent collection of parameters and prototracks. But if the parameter estimation fails for individual seeds, it is not possible to recover a matching set of prototracks afterwards. Therefore, these two steps must be unified into one algorithm.
Definition at line 30 of file PrototracksToParameters.hpp.
View newest version in sPHENIX GitHub at line 30 of file PrototracksToParameters.hpp
Constructor & Destructor Documentation
ActsExamples::PrototracksToParameters::PrototracksToParameters (Config cfg, Acts::Logging::Level lvl)
Construct the algorithm.
Parameters
cfg is the algorithm configuration
lvl is the logging level
Definition at line 32 of file PrototracksToParameters.cpp.
View newest version in sPHENIX GitHub at line 32 of file PrototracksToParameters.cpp
References Acts::eBoundLoc0, Acts::eBoundSize, ActsExamples::PrototracksToParameters::Config::geometry, i, ActsExamples::WriteDataHandle< T >::initialize(), ActsExamples::ReadDataHandle< T >::initialize(), ActsExamples::PrototracksToParameters::Config::initialSigmas, ActsExamples::PrototracksToParameters::Config::initialVarInflation, ActsExamples::PrototracksToParameters::Config::inputProtoTracks, ActsExamples::PrototracksToParameters::Config::inputSpacePoints, m_cfg, m_covariance, m_inputProtoTracks, m_inputSpacePoints, m_outputParameters, m_outputProtoTracks, m_outputSeeds, ActsExamples::PrototracksToParameters::Config::magneticField, ActsExamples::PrototracksToParameters::Config::outputParameters, ActsExamples::PrototracksToParameters::Config::outputProtoTracks, and ActsExamples::PrototracksToParameters::Config::outputSeeds.
ActsExamples::PrototracksToParameters::~PrototracksToParameters ()
Definition at line 55 of file PrototracksToParameters.cpp.
View newest version in sPHENIX GitHub at line 55 of file PrototracksToParameters.cpp
Member Function Documentation
const Config& ActsExamples::PrototracksToParameters::config () const inline
Const access to the config.
Definition at line 83 of file PrototracksToParameters.hpp.
View newest version in sPHENIX GitHub at line 83 of file PrototracksToParameters.hpp
References m_cfg.
ProcessCode ActsExamples::PrototracksToParameters::execute (const AlgorithmContext & ctx) const final virtual
Run the algorithm.
Parameters
ctx is the algorithm context with event information
Returns
a process code indication success or failure
Implements ActsExamples::IAlgorithm.
Definition at line 57 of file PrototracksToParameters.cpp.
View newest version in sPHENIX GitHub at line 57 of file PrototracksToParameters.cpp
References KFPMath::a, ACTS_DEBUG, ACTS_ERROR, ACTS_VERBOSE, ACTS_WARNING, KFPMath::b, Acts::IntegrationTest::bCache, ActsExamples::PrototracksToParameters::Config::bFieldMin, ActsExamples::PrototracksToParameters::Config::buildTightSeeds, Acts::estimateTrackParamsFromSeed(), ckf::field, ActsExamples::AlgorithmContext::geoContext, ActsExamples::PrototracksToParameters::Config::geometry, i, Acts::UnitConstants::m, m_cfg, m_covariance, m_inputProtoTracks, m_inputSpacePoints, m_outputParameters, m_outputProtoTracks, m_outputSeeds, ActsExamples::AlgorithmContext::magFieldContext, ActsExamples::PrototracksToParameters::Config::magneticField, testing::internal::move(), Dataset::parameters, pars, ActsExamples::PrototracksToParameters::Config::particleHypothesis, physmon_simulation::s, seed, Acts::Experimental::detail::BlueprintHelper::sort(), Acts::Seed< SpacePoint >::sp(), SUCCESS, writeMapConfig::surface, t, and Acts::Test::transform.
Member Data Documentation
Config ActsExamples::PrototracksToParameters::m_cfg private
Definition at line 86 of file PrototracksToParameters.hpp.
View newest version in sPHENIX GitHub at line 86 of file PrototracksToParameters.hpp
Referenced by config(), execute(), and PrototracksToParameters().
Acts::BoundSquareMatrix ActsExamples::PrototracksToParameters::m_covariance = Acts::BoundSquareMatrix::Zero() private
Definition at line 87 of file PrototracksToParameters.hpp.
View newest version in sPHENIX GitHub at line 87 of file PrototracksToParameters.hpp
Referenced by execute(), and PrototracksToParameters().
ReadDataHandle<ProtoTrackContainer> ActsExamples::PrototracksToParameters::m_inputProtoTracks private
Initial value:
{this,
                                                         "InputProtoTracks"}
Definition at line 96 of file PrototracksToParameters.hpp.
View newest version in sPHENIX GitHub at line 96 of file PrototracksToParameters.hpp
Referenced by execute(), and PrototracksToParameters().
ReadDataHandle<SimSpacePointContainer> ActsExamples::PrototracksToParameters::m_inputSpacePoints private
Initial value:
{this,
                                                            "InputSpacePoints"}
Definition at line 94 of file PrototracksToParameters.hpp.
View newest version in sPHENIX GitHub at line 94 of file PrototracksToParameters.hpp
Referenced by execute(), and PrototracksToParameters().
WriteDataHandle<TrackParametersContainer> ActsExamples::PrototracksToParameters::m_outputParameters private
Initial value:
{
      this, "OutputParameters"}
Definition at line 92 of file PrototracksToParameters.hpp.
View newest version in sPHENIX GitHub at line 92 of file PrototracksToParameters.hpp
Referenced by execute(), and PrototracksToParameters().
WriteDataHandle<ProtoTrackContainer> ActsExamples::PrototracksToParameters::m_outputProtoTracks private
Initial value:
{this,
                                                           "OutputProtoTracks"}
Definition at line 90 of file PrototracksToParameters.hpp.
View newest version in sPHENIX GitHub at line 90 of file PrototracksToParameters.hpp
Referenced by execute(), and PrototracksToParameters().
WriteDataHandle<SimSeedContainer> ActsExamples::PrototracksToParameters::m_outputSeeds {this, "OutputSeeds"} private
Definition at line 89 of file PrototracksToParameters.hpp.
View newest version in sPHENIX GitHub at line 89 of file PrototracksToParameters.hpp
Referenced by execute(), and PrototracksToParameters().
The documentation for this exception was generated from the following files:
acts/blob/sPHENIX/Examples/Algorithms/TrackFindingExaTrkX/include/ActsExamples/TrackFindingExaTrkX/PrototracksToParameters.hpp
acts/blob/sPHENIX/Examples/Algorithms/TrackFindingExaTrkX/src/PrototracksToParameters.cpp