Analysis Software: TrkrClusterHitAssoc Class Reference
TrkrClusterHitAssoc Class Reference abstract
Base class for associating clusters to the hits that went into them.
#include <coresoftware/blob/master/offline/packages/trackbase/TrkrClusterHitAssoc.h>
Public Types
using Map = std::multimap< TrkrDefs::cluskey, TrkrDefs::hitkey >
using ConstIterator = Map::const_iterator
using ConstRange = std::pair< Map::const_iterator, Map::const_iterator >
Public Member Functions
void Reset () override
Clear Event.
virtual void addAssoc (TrkrDefs::cluskey ckey, unsigned int hidx)=0
Add association between cluster and hit.
virtual Map * getClusterMap (TrkrDefs::hitsetkey)
get pointer to cluster-to-hit map corresponding to a given hitset id
virtual ConstRange getHits (TrkrDefs::cluskey)=0
Get all the hits associated with a cluster by key.
virtual unsigned int size () const
Public Member Functions inherited from PHObject
PHObject ()
ctor
~PHObject () override
dtor
virtual PHObject * CloneMe () const
Virtual copy constructor.
virtual PHObject * clone () const final
PHObject * Clone (const char *newname="") const final
void Copy (TObject &object) const final
virtual void identify (std::ostream &os=std::cout) const
virtual int isValid () const
isValid returns non zero if object contains vailid data
virtual int Integrate () const
virtual int Integrate (PHObject *)
virtual void CopyFrom (const PHObject *obj)
Protected Member Functions
TrkrClusterHitAssoc ()=default
Private Member Functions
ClassDefOverride (TrkrClusterHitAssoc, 1)
Detailed Description
Base class for associating clusters to the hits that went into them.
Store the associations between clusters and the hits that went into them.
Definition at line 24 of file TrkrClusterHitAssoc.h.
View newest version in sPHENIX GitHub at line 24 of file TrkrClusterHitAssoc.h
Member Typedef Documentation
using TrkrClusterHitAssoc::ConstIterator = Map::const_iterator
Definition at line 28 of file TrkrClusterHitAssoc.h.
View newest version in sPHENIX GitHub at line 28 of file TrkrClusterHitAssoc.h
using TrkrClusterHitAssoc::ConstRange = std::pair<Map::const_iterator, Map::const_iterator>
Definition at line 29 of file TrkrClusterHitAssoc.h.
View newest version in sPHENIX GitHub at line 29 of file TrkrClusterHitAssoc.h
using TrkrClusterHitAssoc::Map = std::multimap<TrkrDefs::cluskey, TrkrDefs::hitkey>
Definition at line 27 of file TrkrClusterHitAssoc.h.
View newest version in sPHENIX GitHub at line 27 of file TrkrClusterHitAssoc.h
Constructor & Destructor Documentation
TrkrClusterHitAssoc::TrkrClusterHitAssoc () protected default
Member Function Documentation
virtual void TrkrClusterHitAssoc::addAssoc (TrkrDefs::cluskey ckey, unsigned int hidx) pure virtual
Add association between cluster and hit.
Parameters
[in] ckey Cluster key
[in] hidx Index of the hit in TrkrHitSet
Implemented in TrkrClusterHitAssocv1, TrkrClusterHitAssocv3, and TrkrClusterHitAssocv2.
Referenced by InttClusterizer::ClusterLadderCells(), MvtxPrototype2Clusterizer::ClusterMvtx(), MvtxClusterizer::ClusterMvtx(), TpcPrototypeClusterizer::process_event(), TpcSimpleClusterizer::process_event(), and TpcClusterizer::process_event().
TrkrClusterHitAssoc::ClassDefOverride (TrkrClusterHitAssoc , 1) private
virtual Map* TrkrClusterHitAssoc::getClusterMap (TrkrDefs::hitsetkey) inline virtual
get pointer to cluster-to-hit map corresponding to a given hitset id
Reimplemented in TrkrClusterHitAssocv3, and TrkrClusterHitAssocv2.
Definition at line 41 of file TrkrClusterHitAssoc.h.
View newest version in sPHENIX GitHub at line 41 of file TrkrClusterHitAssoc.h
virtual ConstRange TrkrClusterHitAssoc::getHits (TrkrDefs::cluskey) pure virtual
Get all the hits associated with a cluster by key.
Parameters
[in] ckey Cluster key
[out] Range over hits associated with ckey
Implemented in TrkrClusterHitAssocv1, TrkrClusterHitAssocv3, and TrkrClusterHitAssocv2.
Referenced by SvtxClusterEval::all_clusters_from(), SvtxClusterEval::all_truth_hits(), SvtxClusterEval::all_truth_hits_by_nhit(), QAG4SimulationMvtx::evaluate_clusters(), QAG4SimulationIntt::evaluate_clusters(), QAG4SimulationMicromegas::evaluate_clusters(), QAG4SimulationTpc::evaluate_clusters(), SvtxEvaluator::fillOutputNtuples(), QAG4SimulationIntt::find_g4hits(), QAG4SimulationMvtx::find_g4hits(), QAG4SimulationMicromegas::find_g4hits(), QAG4SimulationTpc::find_g4hits(), QAG4SimulationTracking::find_g4hits(), DSTEmulator::find_g4hits(), TrackEvaluation::find_g4hits(), PHTruthSiliconAssociation::getG4PrimaryParticle(), PHTruthSiliconAssociation::getSiliconClustersFromParticle(), SvtxClusterEval::gtrackid_and_layer_by_nhit(), and PHSiliconTruthTrackSeeding::Process().
void TrkrClusterHitAssoc::Reset () override virtual
Clear Event.
Reimplemented from PHObject.
Reimplemented in TrkrClusterHitAssocv1, TrkrClusterHitAssocv3, and TrkrClusterHitAssocv2.
Definition at line 6 of file TrkrClusterHitAssoc.cc.
View newest version in sPHENIX GitHub at line 6 of file TrkrClusterHitAssoc.cc
virtual unsigned int TrkrClusterHitAssoc::size (void) const inline virtual
Reimplemented in TrkrClusterHitAssocv3, and TrkrClusterHitAssocv2.
Definition at line 51 of file TrkrClusterHitAssoc.h.
View newest version in sPHENIX GitHub at line 51 of file TrkrClusterHitAssoc.h
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/trackbase/TrkrClusterHitAssoc.h
coresoftware/blob/master/offline/packages/trackbase/TrkrClusterHitAssoc.cc