Analysis Software: ActsExamples::SpacePointMaker Exception Reference
ActsExamples::SpacePointMaker Exception Reference final
#include <acts/blob/sPHENIX/Examples/Algorithms/TrackFinding/include/ActsExamples/TrackFinding/SpacePointMaker.hpp>
Classes
struct Config
Public Member Functions
SpacePointMaker (Config cfg, Acts::Logging::Level lvl)
ProcessCode execute (const AlgorithmContext &ctx) const override
const Config & config () const
Const access to the config.
Public Member Functions inherited from ActsExamples::IAlgorithm
IAlgorithm (std::string name, Acts::Logging::Level level=Acts::Logging::INFO)
std::string name () const override
The algorithm name.
ProcessCode internalExecute (const AlgorithmContext &context) final
ProcessCode initialize () override
Initialize the algorithm.
ProcessCode finalize () override
Finalize the algorithm.
Private Attributes
Config m_cfg
std::optional
< IndexSourceLink::SurfaceAccessor > m_slSurfaceAccessor
Acts::SpacePointBuilder
< SimSpacePoint > m_spacePointBuilder
ReadDataHandle
< IndexSourceLinkContainer > m_inputSourceLinks
ReadDataHandle
< MeasurementContainer > m_inputMeasurements
WriteDataHandle
< SimSpacePointContainer > m_outputSpacePoints
Additional Inherited Members
Protected Member Functions inherited from ActsExamples::IAlgorithm
const Acts::Logger & logger () const
Detailed Description
Create space point representations from measurements.
This implements simple space point construction, where each surface-based measurement translates into one space point using the surface local-to-global transform.
The algorithm takes both the source links and measurements container as input. The source link container is geometry-sorted and each element is small compared to a measurement. The geometry selection is therefore much easier to perform on the source links than on the unsorted measurements.
There are no explicit requirements on the content of the input measurements. If no local positions are measured, the transformed global positions will always be the position of the module origin.
Definition at line 46 of file SpacePointMaker.hpp.
View newest version in sPHENIX GitHub at line 46 of file SpacePointMaker.hpp
Constructor & Destructor Documentation
ActsExamples::SpacePointMaker::SpacePointMaker (Config cfg, Acts::Logging::Level lvl)
Construct the space point maker.
Parameters
cfg is the algorithm configuration
lvl is the logging level
Definition at line 32 of file SpacePointMaker.cpp.
View newest version in sPHENIX GitHub at line 32 of file SpacePointMaker.cpp
References ACTS_INFO, ACTS_WARNING, root_event_diff_np::cmp(), Acts::Test::cov, distance(), ActsExamples::SpacePointMaker::Config::geometrySelection, Acts::getDefaultLogger(), ActsExamples::WriteDataHandle< T >::initialize(), ActsExamples::ReadDataHandle< T >::initialize(), ActsExamples::SpacePointMaker::Config::inputMeasurements, ActsExamples::SpacePointMaker::Config::inputSourceLinks, Acts::GeometryIdentifier::layer(), m_cfg, m_inputMeasurements, m_inputSourceLinks, m_outputSpacePoints, m_slSurfaceAccessor, m_spacePointBuilder, testing::internal::move(), ActsExamples::SpacePointMaker::Config::outputSpacePoints, Acts::Test::pos, check_smearing_config::ref, Acts::Experimental::detail::BlueprintHelper::sort(), ActsExamples::SpacePointMaker::Config::trackingGeometry, physmon_ckf_tracking::u, and Acts::GeometryIdentifier::volume().
Member Function Documentation
const Config& ActsExamples::SpacePointMaker::config () const inline
Const access to the config.
Definition at line 80 of file SpacePointMaker.hpp.
View newest version in sPHENIX GitHub at line 80 of file SpacePointMaker.hpp
References m_cfg.
ActsExamples::ProcessCode ActsExamples::SpacePointMaker::execute (const AlgorithmContext & ctx) const override virtual
Run the space point construction.
Parameters
ctx is the algorithm context with event information
Returns
a process code indication success or failure
Implements ActsExamples::IAlgorithm.
Definition at line 118 of file SpacePointMaker.cpp.
View newest version in sPHENIX GitHub at line 118 of file SpacePointMaker.cpp
References Acts::Test::cov, ActsExamples::AlgorithmContext::geoContext, m_cfg(), ActsExamples::makeGroupBy(), Acts::SpacePointBuilderOptions::paramCovAccessor, and ActsExamples::selectLowestNonZeroGeometryObject().
Member Data Documentation
Config ActsExamples::SpacePointMaker::m_cfg private
Definition at line 83 of file SpacePointMaker.hpp.
View newest version in sPHENIX GitHub at line 83 of file SpacePointMaker.hpp
Referenced by config(), and SpacePointMaker().
ReadDataHandle<MeasurementContainer> ActsExamples::SpacePointMaker::m_inputMeasurements private
Initial value:
{this,
                                                           "InputMeasurements"}
Definition at line 92 of file SpacePointMaker.hpp.
View newest version in sPHENIX GitHub at line 92 of file SpacePointMaker.hpp
Referenced by SpacePointMaker().
ReadDataHandle<IndexSourceLinkContainer> ActsExamples::SpacePointMaker::m_inputSourceLinks private
Initial value:
{
      this, "InputSourceLinks"}
Definition at line 89 of file SpacePointMaker.hpp.
View newest version in sPHENIX GitHub at line 89 of file SpacePointMaker.hpp
Referenced by SpacePointMaker().
WriteDataHandle<SimSpacePointContainer> ActsExamples::SpacePointMaker::m_outputSpacePoints private
Initial value:
{
      this, "OutputSpacePoints"}
Definition at line 95 of file SpacePointMaker.hpp.
View newest version in sPHENIX GitHub at line 95 of file SpacePointMaker.hpp
Referenced by SpacePointMaker().
std::optional<IndexSourceLink::SurfaceAccessor> ActsExamples::SpacePointMaker::m_slSurfaceAccessor private
Definition at line 85 of file SpacePointMaker.hpp.
View newest version in sPHENIX GitHub at line 85 of file SpacePointMaker.hpp
Referenced by SpacePointMaker().
Acts::SpacePointBuilder<SimSpacePoint> ActsExamples::SpacePointMaker::m_spacePointBuilder private
Definition at line 87 of file SpacePointMaker.hpp.
View newest version in sPHENIX GitHub at line 87 of file SpacePointMaker.hpp
Referenced by SpacePointMaker().
The documentation for this exception was generated from the following files:
acts/blob/sPHENIX/Examples/Algorithms/TrackFinding/include/ActsExamples/TrackFinding/SpacePointMaker.hpp
acts/blob/sPHENIX/Examples/Algorithms/TrackFinding/src/SpacePointMaker.cpp