Analysis Software: NNH< BJ, I >::NNBJ Class Reference
NNH< BJ, I >::NNBJ Class Reference
Public Member Functions
void init (const PseudoJet &jet, int index_in)
void init (const PseudoJet &jet, int index_in, I *info)
void other_init (int index_in)
int index () const
Public Attributes
double NN_dist
NNBJ * NN
Private Attributes
int _index
Detailed Description
template<class BJ, class I = _NoInfo>
class NNH< BJ, I >::NNBJ
Definition at line 1786 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 1786 of file fjcore.hh
Member Function Documentation
template<class BJ , class I = _NoInfo> int NNH< BJ, I >::NNBJ::index () const inline
Definition at line 1801 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 1801 of file fjcore.hh
References NNH< BJ, I >::NNBJ::_index.
Referenced by NNH< BJ, I >::dij_min(), NNH< BJ, I >::merge_jets(), and NNH< BJ, I >::remove_jet().
template<class BJ , class I = _NoInfo> void NNH< BJ, I >::NNBJ::init (const PseudoJet & jet, int index_in) inline
Definition at line 1788 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 1788 of file fjcore.hh
References myAnalysis::init(), and NNH< BJ, I >::NNBJ::other_init().
template<class BJ , class I = _NoInfo> void NNH< BJ, I >::NNBJ::init (const PseudoJet & jet, int index_in, I * info) inline
Definition at line 1792 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 1792 of file fjcore.hh
References myAnalysis::init(), and NNH< BJ, I >::NNBJ::other_init().
template<class BJ , class I = _NoInfo> void NNH< BJ, I >::NNBJ::other_init (int index_in) inline
Definition at line 1796 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 1796 of file fjcore.hh
References NNH< BJ, I >::NNBJ::_index, NNH< BJ, I >::NNBJ::NN, and NNH< BJ, I >::NNBJ::NN_dist.
Referenced by NNH< BJ, I >::NNBJ::init().
Member Data Documentation
template<class BJ , class I = _NoInfo> int NNH< BJ, I >::NNBJ::_index private
Definition at line 1805 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 1805 of file fjcore.hh
Referenced by NNH< BJ, I >::NNBJ::index(), and NNH< BJ, I >::NNBJ::other_init().
template<class BJ , class I = _NoInfo> NNBJ* NNH< BJ, I >::NNBJ::NN
Definition at line 1803 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 1803 of file fjcore.hh
Referenced by NNH< BJ, I >::dij_min(), NNH< BJ, I >::merge_jets(), NNH< BJ, I >::NNBJ::other_init(), NNH< BJ, I >::set_NN_crosscheck(), and NNH< BJ, I >::set_NN_nocross().
template<class BJ , class I = _NoInfo> double NNH< BJ, I >::NNBJ::NN_dist
Definition at line 1802 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 1802 of file fjcore.hh
Referenced by NNH< BJ, I >::merge_jets(), NNH< BJ, I >::NNBJ::other_init(), NNH< BJ, I >::set_NN_crosscheck(), and NNH< BJ, I >::set_NN_nocross().
The documentation for this class was generated from the following file:
JETSCAPE/blob/main/external_packages/fjcore.hh