Analysis Software: Jetscape::Vertex Class Reference
Jetscape::Vertex Class Reference
#include <JETSCAPE/blob/main/src/framework/JetClass.h>
Public Member Functions
Vertex ()
Vertex (double x, double y, double z, double t)
Vertex (FourVector &x)
virtual ~Vertex ()
void set_location (FourVector &x)
FourVector & x_in ()
Protected Attributes
FourVector x_in_
Friends
ostream & operator<< (ostream &output, Vertex &vertex)
Detailed Description
Definition at line 58 of file JetClass.h.
View newest version in sPHENIX GitHub at line 58 of file JetClass.h
Constructor & Destructor Documentation
Jetscape::Vertex::Vertex () inline
Definition at line 61 of file JetClass.h.
View newest version in sPHENIX GitHub at line 61 of file JetClass.h
References Jetscape::FourVector::Set(), and x_in_.
Jetscape::Vertex::Vertex (double x, double y, double z, double t) inline
Definition at line 62 of file JetClass.h.
View newest version in sPHENIX GitHub at line 62 of file JetClass.h
References Jetscape::FourVector::Set(), and x_in_.
Jetscape::Vertex::Vertex (FourVector & x) inline
Definition at line 63 of file JetClass.h.
View newest version in sPHENIX GitHub at line 63 of file JetClass.h
References set_location().
Vertex::~Vertex () virtual
Definition at line 27 of file JetClass.cc.
View newest version in sPHENIX GitHub at line 27 of file JetClass.cc
References VERBOSESHOWER.
Member Function Documentation
void Jetscape::Vertex::set_location (FourVector & x) inline
Definition at line 66 of file JetClass.h.
View newest version in sPHENIX GitHub at line 66 of file JetClass.h
References ambiguity_solver_full_chain::x, and x_in_.
Referenced by Vertex().
FourVector& Jetscape::Vertex::x_in () inline
Definition at line 68 of file JetClass.h.
View newest version in sPHENIX GitHub at line 68 of file JetClass.h
References x_in_.
Friends And Related Function Documentation
ostream& operator<< (ostream & output, Vertex & vertex) friend
Definition at line 70 of file JetClass.h.
View newest version in sPHENIX GitHub at line 70 of file JetClass.h
Member Data Documentation
FourVector Jetscape::Vertex::x_in_ protected
Definition at line 77 of file JetClass.h.
View newest version in sPHENIX GitHub at line 77 of file JetClass.h
Referenced by set_location(), Vertex(), and x_in().
The documentation for this class was generated from the following files:
JETSCAPE/blob/main/src/framework/JetClass.h
JETSCAPE/blob/main/src/framework/JetClass.cc