Analysis Software: macros/blob/master/common/G4_CEmc_Albedo.C File Reference
G4_CEmc_Albedo.C File Reference
#include <GlobalVariables.C>
#include <g4detectors/PHG4CylinderSubsystem.h>
#include <g4main/PHG4Reco.h>
Namespaces
namespace Enable
namespace G4CEMCALBEDO
Macros
#define MACRO_G4CEMCALBEDO_C
Functions
void CEmcAlbedoInit ()
void CEmcAlbedo (PHG4Reco *g4Reco)
Variables
bool Enable::CEMCALBEDO = false
bool Enable::CEMCALBEDO_ABSORBER = false
double G4CEMCALBEDO::teflon_cylinder_thickness = 1.5
double G4CEMCALBEDO::inner_radius = 95. - teflon_cylinder_thickness
double G4CEMCALBEDO::albedo_thickness = 2.
Macro Definition Documentation
#define MACRO_G4CEMCALBEDO_C
Definition at line 2 of file G4_CEmc_Albedo.C.
View newest version in sPHENIX GitHub at line 2 of file G4_CEmc_Albedo.C
Function Documentation
void CEmcAlbedo (PHG4Reco * g4Reco)
Definition at line 30 of file G4_CEmc_Albedo.C.
View newest version in sPHENIX GitHub at line 30 of file G4_CEmc_Albedo.C
References Enable::ABSORBER, G4CEMCALBEDO::albedo_thickness, Enable::CEMCALBEDO_ABSORBER, G4CEMCALBEDO::inner_radius, PHG4Reco::registerSubsystem(), PHG4DetectorSubsystem::set_double_param(), PHG4DetectorSubsystem::set_string_param(), PHG4DetectorSubsystem::SetActive(), PHG4DetectorSubsystem::SuperDetector(), and G4CEMCALBEDO::teflon_cylinder_thickness.
Referenced by G4Setup().
void CEmcAlbedoInit ()
Definition at line 23 of file G4_CEmc_Albedo.C.
View newest version in sPHENIX GitHub at line 23 of file G4_CEmc_Albedo.C
References G4CEMCALBEDO::albedo_thickness, G4CEMCALBEDO::inner_radius, BlackHoleGeometry::max_radius, BlackHoleGeometry::max_z, Acts::UnitConstants::min, BlackHoleGeometry::min_z, and G4CEMCALBEDO::teflon_cylinder_thickness.
Referenced by G4Init().