Analysis Software: macros/blob/master/calibrations/calo/tower_slope_macro/G4_HcalOut_ref.C File Reference
G4_HcalOut_ref.C File Reference
#include <GlobalVariables.C>
#include <QA.C>
#include <g4calo/HcalRawTowerBuilder.h>
#include <g4calo/RawTowerDigitizer.h>
#include <g4detectors/PHG4HcalCellReco.h>
#include <g4detectors/PHG4OuterHcalSubsystem.h>
#include <g4eval/CaloEvaluator.h>
#include <g4main/PHG4Reco.h>
#include <caloreco/RawClusterBuilderGraph.h>
#include <caloreco/RawClusterBuilderTemplate.h>
#include <caloreco/RawTowerCalibration.h>
#include <qa_modules/QAG4SimulationCalorimeter.h>
#include <fun4all/Fun4AllServer.h>
Namespaces
namespace Enable
namespace G4HCALOUT
Macros
#define MACRO_G4HCALOUTREF_C
Enumerations
enum G4HCALOUT::enu_HCalOut_clusterizer { G4HCALOUT::kHCalOutGraphClusterizer, G4HCALOUT::kHCalOutTemplateClusterizer, G4HCALOUT::kHCalOutGraphClusterizer, G4HCALOUT::kHCalOutTemplateClusterizer }
Functions
void HCalOuterInit ()
double HCalOuter (PHG4Reco *g4Reco, double radius, const int crossings)
void HCALOuter_Cells ()
void HCALOuter_Towers ()
void HCALOuter_Clusters ()
void HCALOuter_Eval (const std::string &outputfile)
void HCALOuter_QA ()
Variables
bool Enable::HCALOUT = false
bool Enable::HCALOUT_ABSORBER = false
bool Enable::HCALOUT_OVERLAPCHECK = false
bool Enable::HCALOUT_CELL = false
bool Enable::HCALOUT_TOWER = false
bool Enable::HCALOUT_CLUSTER = false
bool Enable::HCALOUT_EVAL = false
bool Enable::HCALOUT_QA = false
int Enable::HCALOUT_VERBOSITY = 0
double G4HCALOUT::outer_radius = 264.71
double G4HCALOUT::size_z = 304.91 * 2
RawTowerDigitizer::enu_digi_algorithm G4HCALOUT::TowerDigi = RawTowerDigitizer::kSimple_photon_digitization
enu_HCalOut_clusterizer G4HCALOUT::HCalOut_clusterizer = kHCalOutTemplateClusterizer
template clusterizer, RawClusterBuilderTemplate, as developed by Sasha Bazilevsky
Macro Definition Documentation
#define MACRO_G4HCALOUTREF_C
Definition at line 2 of file G4_HcalOut_ref.C.
View newest version in sPHENIX GitHub at line 2 of file G4_HcalOut_ref.C
Function Documentation
double HCalOuter (PHG4Reco * g4Reco, double radius, const int crossings)
Definition at line 77 of file G4_HcalOut_ref.C.
View newest version in sPHENIX GitHub at line 77 of file G4_HcalOut_ref.C
References Enable::ABSORBER, PHG4DetectorSubsystem::get_double_param(), Enable::HCALOUT_ABSORBER, Enable::HCALOUT_OVERLAPCHECK, Enable::HCALOUT_VERBOSITY, no_overlapp, PHG4DetectorSubsystem::OverlapCheck(), Enable::OVERLAPCHECK, PHG4Reco::registerSubsystem(), PHG4DetectorSubsystem::SetAbsorberActive(), PHG4DetectorSubsystem::SetActive(), PHG4DetectorSubsystem::SuperDetector(), verbosity, and Enable::VERBOSITY.
void HCALOuter_Cells ()
Definition at line 139 of file G4_HcalOut_ref.C.
View newest version in sPHENIX GitHub at line 139 of file G4_HcalOut_ref.C
References PHG4HcalCellReco::Detector(), Enable::HCALOUT_VERBOSITY, Fun4AllServer::instance(), Fun4AllServer::registerSubsystem(), verbosity, and Enable::VERBOSITY.
void HCALOuter_Clusters ()
Definition at line 229 of file G4_HcalOut_ref.C.
View newest version in sPHENIX GitHub at line 229 of file G4_HcalOut_ref.C
References RawClusterBuilderGraph::Detector(), RawClusterBuilderTemplate::Detector(), G4HCALOUT::HCalOut_clusterizer, Enable::HCALOUT_VERBOSITY, Fun4AllServer::instance(), G4HCALOUT::kHCalOutGraphClusterizer, G4HCALOUT::kHCalOutTemplateClusterizer, Fun4AllServer::registerSubsystem(), RawClusterBuilderTemplate::SetCylindricalGeometry(), verbosity, Enable::VERBOSITY, and Fun4AllBase::Verbosity().
void HCALOuter_Eval (const std::string & outputfile)
Definition at line 259 of file G4_HcalOut_ref.C.
View newest version in sPHENIX GitHub at line 259 of file G4_HcalOut_ref.C
References Enable::HCALOUT_VERBOSITY, Fun4AllServer::instance(), Fun4AllServer::registerSubsystem(), verbosity, Enable::VERBOSITY, and Fun4AllBase::Verbosity().
void HCALOuter_QA ()
Definition at line 272 of file G4_HcalOut_ref.C.
View newest version in sPHENIX GitHub at line 272 of file G4_HcalOut_ref.C
References Enable::HCALOUT_VERBOSITY, Fun4AllServer::instance(), Enable::QA_VERBOSITY, Fun4AllServer::registerSubsystem(), verbosity, and Fun4AllBase::Verbosity().
Referenced by Fun4All_AnaTutorial_sPHENIX(), Fun4All_AnaTutorial_sPHENIX_Jets(), Fun4All_G4_sPHENIX(), Fun4All_G4_sPHENIX_ForTrackCutStudy(), Fun4All_G4_sPHENIX_ForTrackCutStudy_EmbedScanOff(), Fun4All_G4_sPHENIX_ForTrackCutStudy_EmbedScanOn(), Fun4All_G4_sPHENIX_ForTrackCutStudy_WithPileup_EmbedScanOff(), Fun4All_G4_sPHENIX_ForTrackCutStudy_WithPileup_EmbedScanOn(), Fun4All_Pi0Gen_sPHENIX(), Fun4All_pi0tbt_SIMPLE_EMBED(), Fun4All_RunNewTruthMatcher(), Fun4All_SinglePhotonGen_sPHENIX(), and Fun4All_SinglePi0Gen_sPHENIX().
void HCALOuter_Towers ()
Definition at line 163 of file G4_HcalOut_ref.C.
View newest version in sPHENIX GitHub at line 163 of file G4_HcalOut_ref.C
References HcalRawTowerBuilder::Detector(), RawTowerCalibration::Detector(), RawTowerDigitizer::Detector(), Acts::UnitConstants::e, Enable::HCALOUT_VERBOSITY, Fun4AllServer::instance(), RawTowerCalibration::kDbfile_tbt_gain_corr, RawTowerDigitizer::kNo_digitization, Fun4AllServer::registerSubsystem(), RawTowerCalibration::set_calib_algorithm(), RawTowerCalibration::set_calib_const_GeV_ADC(), RawTowerCalibration::set_CalibrationFileName(), RawTowerDigitizer::set_digi_algorithm(), RawTowerCalibration::set_pedstal_ADC(), RawTowerDigitizer::set_pedstal_central_ADC(), RawTowerDigitizer::set_pedstal_width_ADC(), RawTowerDigitizer::set_photonelec_ADC(), RawTowerDigitizer::set_photonelec_yield_visible_GeV(), HcalRawTowerBuilder::set_sim_tower_node_prefix(), RawTowerCalibration::set_UseConditionsDB(), RawTowerDigitizer::set_zero_suppression_ADC(), G4HCALOUT::TowerDigi, verbosity, Enable::VERBOSITY, and Fun4AllBase::Verbosity().
void HCalOuterInit ()
Definition at line 70 of file G4_HcalOut_ref.C.
View newest version in sPHENIX GitHub at line 70 of file G4_HcalOut_ref.C
References BlackHoleGeometry::max_radius, BlackHoleGeometry::max_z, Acts::UnitConstants::min, BlackHoleGeometry::min_z, G4HCALOUT::outer_radius, and G4HCALOUT::size_z.