Analysis Software: TpcSpaceChargeReconstructionHelper Class Reference
TpcSpaceChargeReconstructionHelper Class Reference
#include <coresoftware/blob/master/offline/packages/tpccalib/TpcSpaceChargeReconstructionHelper.h>
Static Public Member Functions
static void extrapolate_z (TH3 *hin)
z extrapolation
static std::tuple< double, double > get_zref_range (double r)
get reference z range used for phi extrapolation normalization at a given radius
static void extrapolate_phi1 (TH3 *hin)
first phi extrapolation
static void extrapolate_phi2 (TH3 *hin)
second phi extrapolation
static std::tuple< TH3 *, TH3 * > split (TH3 *hin)
separate positive and negative z histograms
static TH3 * copy_histogram (TH3 *hin, const TString &name)
Detailed Description
Definition at line 15 of file TpcSpaceChargeReconstructionHelper.h.
View newest version in sPHENIX GitHub at line 15 of file TpcSpaceChargeReconstructionHelper.h
Member Function Documentation
TH3 * TpcSpaceChargeReconstructionHelper::copy_histogram (TH3 * hin, const TString & name) static
copy input histogram into output, with new name, while adding two "guarding bins" on each axis, with identical content and error as the first and last bin of the original histogram this is necessary for being able to call TH3->Interpolate() when using these histograms to correct for the space charge distortions. TODO: is this really necessary ? Possibly one could just use the bin content for the correction rather than using TH3->Interpolate, in which case the "guarding bins" would be unnecessary. Should check if it leads to a significant deterioration of the momentum resolution
Definition at line 289 of file TpcSpaceChargeReconstructionHelper.cc.
View newest version in sPHENIX GitHub at line 289 of file TpcSpaceChargeReconstructionHelper.cc
References bins, index, and MATSCAN::phibins.
Referenced by TpcSpaceChargeMatrixInversion::calculate_distortions().
void TpcSpaceChargeReconstructionHelper::extrapolate_phi1 (TH3 * hin) static
first phi extrapolation
copy the full z dependence of reference sector to all other sectors, separately for positive and negative z, normalized by the measurement from provided micromegas, at the appropriate z
Definition at line 113 of file TpcSpaceChargeReconstructionHelper.cc.
View newest version in sPHENIX GitHub at line 113 of file TpcSpaceChargeReconstructionHelper.cc
References configureMap::ibin, myAnalysis::phi_max, myAnalysis::phi_min, and myAnalysis::phibin_max.
Referenced by TpcSpaceChargeMatrixInversion::calculate_distortions().
void TpcSpaceChargeReconstructionHelper::extrapolate_phi2 (TH3 * hin) static
second phi extrapolation
for each r, z and phi bin, linearly extrapolate between neighbor phi sector measurements
Definition at line 186 of file TpcSpaceChargeReconstructionHelper.cc.
View newest version in sPHENIX GitHub at line 186 of file TpcSpaceChargeReconstructionHelper.cc
References acts::error, ActsTests::PropagationDatasets::phi, myAnalysis::phi_max, myAnalysis::phi_min, myAnalysis::phibin_max, and square().
Referenced by TpcSpaceChargeMatrixInversion::calculate_distortions().
void TpcSpaceChargeReconstructionHelper::extrapolate_z (TH3 * hin) static
z extrapolation
interpolate between micromegas in the fully equiped sector
Definition at line 58 of file TpcSpaceChargeReconstructionHelper.cc.
View newest version in sPHENIX GitHub at line 58 of file TpcSpaceChargeReconstructionHelper.cc
References acts::error, physmon_track_finding_ttbar::r, square(), and physmon_track_finding_ttbar::z.
Referenced by TpcSpaceChargeMatrixInversion::calculate_distortions().
static std::tuple<double, double> TpcSpaceChargeReconstructionHelper::get_zref_range (double r) static
get reference z range used for phi extrapolation normalization at a given radius
std::tuple< TH3 *, TH3 * > TpcSpaceChargeReconstructionHelper::split (TH3 * hin) static
separate positive and negative z histograms
split histograms in two, the first with negative z values only, the second with positive z values this must be done before adding guarding bins around each axis, in order to prevent artifacts during calls to Interpolate at the central membrane (z = 0)
Definition at line 237 of file TpcSpaceChargeReconstructionHelper.cc.
View newest version in sPHENIX GitHub at line 237 of file TpcSpaceChargeReconstructionHelper.cc
References acts::error, h, configureMap::ibin, and std::tr1::make_tuple().
Referenced by TpcSpaceChargeMatrixInversion::calculate_distortions().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/tpccalib/TpcSpaceChargeReconstructionHelper.h
coresoftware/blob/master/offline/packages/tpccalib/TpcSpaceChargeReconstructionHelper.cc