Analysis Software: GlobalVertexMap Class Reference
GlobalVertexMap Class Reference
#include <coresoftware/blob/master/offline/packages/globalvertex/GlobalVertexMap.h>
Public Types
typedef std::map< unsigned int,
GlobalVertex * >
::const_iterator ConstIter
typedef std::map< unsigned int,
GlobalVertex * >::iterator Iter
Public Member Functions
~GlobalVertexMap () override
void identify (std::ostream &os=std::cout) const override
int isValid () const override
isValid returns non zero if object contains vailid data
virtual bool empty () const
virtual size_t size () const
virtual size_t count (unsigned int) const
virtual void clear ()
virtual const GlobalVertex * get (unsigned int) const
virtual GlobalVertex * get (unsigned int)
virtual GlobalVertex * insert (GlobalVertex *)
virtual size_t erase (unsigned int)
virtual ConstIter begin () const
virtual ConstIter find (unsigned int idkey) const
virtual ConstIter end () const
virtual Iter begin ()
virtual Iter find (unsigned int idkey)
virtual Iter end ()
Public Member Functions inherited from PHObject
PHObject ()
ctor
~PHObject () override
dtor
virtual PHObject * CloneMe () const
Virtual copy constructor.
virtual PHObject * clone () const final
PHObject * Clone (const char *newname="") const final
void Copy (TObject &object) const final
virtual void Reset ()
Clear Event.
virtual int Integrate () const
virtual int Integrate (PHObject *)
virtual void CopyFrom (const PHObject *obj)
Protected Member Functions
GlobalVertexMap ()
Private Member Functions
ClassDefOverride (GlobalVertexMap, 1)
Detailed Description
Definition at line 13 of file GlobalVertexMap.h.
View newest version in sPHENIX GitHub at line 13 of file GlobalVertexMap.h
Member Typedef Documentation
typedef std::map<unsigned int, GlobalVertex*>::const_iterator GlobalVertexMap::ConstIter
Definition at line 16 of file GlobalVertexMap.h.
View newest version in sPHENIX GitHub at line 16 of file GlobalVertexMap.h
typedef std::map<unsigned int, GlobalVertex*>::iterator GlobalVertexMap::Iter
Definition at line 17 of file GlobalVertexMap.h.
View newest version in sPHENIX GitHub at line 17 of file GlobalVertexMap.h
Constructor & Destructor Documentation
GlobalVertexMap::~GlobalVertexMap () inline override
Definition at line 19 of file GlobalVertexMap.h.
View newest version in sPHENIX GitHub at line 19 of file GlobalVertexMap.h
GlobalVertexMap::GlobalVertexMap () inline protected
Definition at line 43 of file GlobalVertexMap.h.
View newest version in sPHENIX GitHub at line 43 of file GlobalVertexMap.h
Member Function Documentation
GlobalVertexMap::ConstIter GlobalVertexMap::begin (void) const virtual
Reimplemented in GlobalVertexMapv1.
Definition at line 5 of file GlobalVertexMap.cc.
View newest version in sPHENIX GitHub at line 5 of file GlobalVertexMap.cc
Referenced by ResonanceJetTagging::addClusters(), BbcCheck::CheckDST(), MinimumBiasClassifier::FillMinimumBiasInfo(), CaloEvaluator::fillOutputNtuples(), TowerJetInput::get_input(), ClusterJetInput::get_input(), AnaTutorial::getEMCalClusters(), MultiDetectorMultiplicity::isVertexAccepted(), CaloEvaluator::printOutputInfo(), RawClusterZVertexRecorrect::process_event(), RawClusterBuilderTemplate::process_event(), FilterEvents::process_event(), FilterEventsUpsilon::process_event(), ClusterIso::process_event(), ParticleFlowReco::process_event(), Forward_pi0s::process_event(), PJTranslator::process_event(), Pi0MassAnalysis::process_event(), CaloCalibEmc_Pi0::process_event(), isoCluster::process_event(), pi0ClusterAna::process_event(), singlePhotonClusterAna::process_event(), pythiaEMCalAna::process_event(), PhotonJet::process_event(), pi0Efficiency::process_event(), MyJetAnalysis::process_event(), cemcReco::process_event(), JetValidation::process_event(), sPHAnalysis::process_event_notracking(), sPHAnalysis_calo::process_event_test(), sPHAnalysis::process_event_test(), sPHAnalysis::process_event_upsilons(), DumpGlobalVertexMap::process_Node(), CaloAna::process_towers(), CaloValid::process_towers(), and pi0EtaByEta::process_towers().
GlobalVertexMap::Iter GlobalVertexMap::begin (void) virtual
Reimplemented in GlobalVertexMapv1.
Definition at line 20 of file GlobalVertexMap.cc.
View newest version in sPHENIX GitHub at line 20 of file GlobalVertexMap.cc
GlobalVertexMap::ClassDefOverride (GlobalVertexMap , 1) private
virtual void GlobalVertexMap::clear () inline virtual
Reimplemented in GlobalVertexMapv1.
Definition at line 27 of file GlobalVertexMap.h.
View newest version in sPHENIX GitHub at line 27 of file GlobalVertexMap.h
virtual size_t GlobalVertexMap::count (unsigned int) const inline virtual
Reimplemented in GlobalVertexMapv1.
Definition at line 26 of file GlobalVertexMap.h.
View newest version in sPHENIX GitHub at line 26 of file GlobalVertexMap.h
virtual bool GlobalVertexMap::empty () const inline virtual
Reimplemented in GlobalVertexMapv1.
Definition at line 24 of file GlobalVertexMap.h.
View newest version in sPHENIX GitHub at line 24 of file GlobalVertexMap.h
Referenced by ResonanceJetTagging::addClusters(), BbcCheck::CheckDST(), MinimumBiasClassifier::FillMinimumBiasInfo(), CaloEvaluator::fillOutputNtuples(), TowerJetInput::get_input(), ClusterJetInput::get_input(), AnaTutorial::getEMCalClusters(), MultiDetectorMultiplicity::isVertexAccepted(), CaloEvaluator::printOutputInfo(), RawClusterZVertexRecorrect::process_event(), RawClusterBuilderTemplate::process_event(), ClusterIso::process_event(), ParticleFlowReco::process_event(), Forward_pi0s::process_event(), PJTranslator::process_event(), Pi0MassAnalysis::process_event(), CaloCalibEmc_Pi0::process_event(), isoCluster::process_event(), pi0ClusterAna::process_event(), singlePhotonClusterAna::process_event(), pythiaEMCalAna::process_event(), PhotonJet::process_event(), pi0Efficiency::process_event(), FullJetFinder::process_event(), cemcReco::process_event(), CaloAna::process_towers(), CaloValid::process_towers(), and pi0EtaByEta::process_towers().
GlobalVertexMap::ConstIter GlobalVertexMap::end (void) const virtual
Reimplemented in GlobalVertexMapv1.
Definition at line 15 of file GlobalVertexMap.cc.
View newest version in sPHENIX GitHub at line 15 of file GlobalVertexMap.cc
Referenced by AnaTutorial::getEMCalClusters(), FilterEvents::process_event(), FilterEventsUpsilon::process_event(), GlobalVertexReco::process_event(), sPHAnalysis::process_event_notracking(), sPHAnalysis_calo::process_event_test(), sPHAnalysis::process_event_test(), sPHAnalysis::process_event_upsilons(), and DumpGlobalVertexMap::process_Node().
GlobalVertexMap::Iter GlobalVertexMap::end (void) virtual
Reimplemented in GlobalVertexMapv1.
Definition at line 30 of file GlobalVertexMap.cc.
View newest version in sPHENIX GitHub at line 30 of file GlobalVertexMap.cc
virtual size_t GlobalVertexMap::erase (unsigned int) inline virtual
Reimplemented in GlobalVertexMapv1.
Definition at line 32 of file GlobalVertexMap.h.
View newest version in sPHENIX GitHub at line 32 of file GlobalVertexMap.h
GlobalVertexMap::ConstIter GlobalVertexMap::find (unsigned int idkey) const virtual
Reimplemented in GlobalVertexMapv1.
Definition at line 10 of file GlobalVertexMap.cc.
View newest version in sPHENIX GitHub at line 10 of file GlobalVertexMap.cc
Referenced by GlobalVertexReco::process_event().
GlobalVertexMap::Iter GlobalVertexMap::find (unsigned int idkey) virtual
Reimplemented in GlobalVertexMapv1.
Definition at line 25 of file GlobalVertexMap.cc.
View newest version in sPHENIX GitHub at line 25 of file GlobalVertexMap.cc
virtual const GlobalVertex* GlobalVertexMap::get (unsigned int) const inline virtual
Reimplemented in GlobalVertexMapv1.
Definition at line 29 of file GlobalVertexMap.h.
View newest version in sPHENIX GitHub at line 29 of file GlobalVertexMap.h
Referenced by TrkrNtuplizer::fillOutputNtuples(), QAG4SimulationTracking::get_dca(), KFParticle_truthAndDetTools::getVertex(), JetBkgdSub::process_event(), and PairMaker::process_event_test().
virtual GlobalVertex* GlobalVertexMap::get (unsigned int) inline virtual
Reimplemented in GlobalVertexMapv1.
Definition at line 30 of file GlobalVertexMap.h.
View newest version in sPHENIX GitHub at line 30 of file GlobalVertexMap.h
void GlobalVertexMap::identify (std::ostream & os = std::cout) const inline override virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from PHObject.
Reimplemented in GlobalVertexMapv1.
Definition at line 21 of file GlobalVertexMap.h.
View newest version in sPHENIX GitHub at line 21 of file GlobalVertexMap.h
References os.
Referenced by GlobalVertexReco::process_event().
virtual GlobalVertex* GlobalVertexMap::insert (GlobalVertex *) inline virtual
Reimplemented in GlobalVertexMapv1.
Definition at line 31 of file GlobalVertexMap.h.
View newest version in sPHENIX GitHub at line 31 of file GlobalVertexMap.h
Referenced by Emcal_Tower_Masking::process_event(), GlobalVertexReco::process_event(), and GlobalVertexFastSimReco::process_event().
int GlobalVertexMap::isValid () const inline override virtual
isValid returns non zero if object contains vailid data
Reimplemented from PHObject.
Reimplemented in GlobalVertexMapv1.
Definition at line 22 of file GlobalVertexMap.h.
View newest version in sPHENIX GitHub at line 22 of file GlobalVertexMap.h
virtual size_t GlobalVertexMap::size (void) const inline virtual
Reimplemented in GlobalVertexMapv1.
Definition at line 25 of file GlobalVertexMap.h.
View newest version in sPHENIX GitHub at line 25 of file GlobalVertexMap.h
Referenced by Emcal_Tower_Masking::process_event(), GlobalVertexReco::process_event(), PairMaker::process_event_test(), and DumpGlobalVertexMap::process_Node().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/globalvertex/GlobalVertexMap.h
coresoftware/blob/master/offline/packages/globalvertex/GlobalVertexMap.cc