Analysis Software: TowerInfov3 Class Reference
TowerInfov3 Class Reference
#include <coresoftware/blob/master/offline/packages/CaloBase/TowerInfov3.h>
Public Member Functions
TowerInfov3 ()
~TowerInfov3 () override
void Reset () override
Clear Event.
void Clear (Option_t *="") override
int get_nsample () const override
int16_t get_waveform_value (int index) const override
void set_waveform_value (int index, int16_t value) override
void copy_tower (TowerInfo *tower) override
Public Member Functions inherited from TowerInfov2
TowerInfov2 ()
~TowerInfov2 () override
void Clear (Option_t *="") override
void set_time (short t) override
short get_time () override
void set_time_float (float t) override
float get_time_float () override
void set_chi2 (float chi2) override
float get_chi2 () override
void set_pedestal (float pedestal) override
float get_pedestal () override
void set_isHot (bool isHot) override
bool get_isHot () const override
void set_isBadTime (bool isBadTime) override
bool get_isBadTime () const override
void set_isBadChi2 (bool isBadChi2) override
bool get_isBadChi2 () const override
void set_isNotInstr (bool isNotInstr) override
bool get_isNotInstr () const override
void set_isNoCalib (bool isNoCalib) override
bool get_isNoCalib () const override
bool get_isGood () const override
uint8_t get_status () const override
void set_status (uint8_t status) override
Public Member Functions inherited from TowerInfov1
TowerInfov1 ()
TowerInfov1 (TowerInfo &tower)
~TowerInfov1 () override
void Clear (Option_t *="") override
Clear is used by TClonesArray to reset the tower to initial state without calling destructor/constructor.
void set_energy (float energy) override
float get_energy () override
Public Member Functions inherited from TowerInfo
TowerInfo ()=default
~TowerInfo () override=default
Public Member Functions inherited from PHObject
PHObject ()
ctor
~PHObject () override
dtor
virtual PHObject * CloneMe () const
Virtual copy constructor.
virtual PHObject * clone () const final
PHObject * Clone (const char *newname="") const final
void Copy (TObject &object) const final
virtual void identify (std::ostream &os=std::cout) const
virtual int isValid () const
isValid returns non zero if object contains vailid data
virtual int Integrate () const
virtual int Integrate (PHObject *)
virtual void CopyFrom (const PHObject *obj)
Private Member Functions
ClassDefOverride (TowerInfov3, 1)
Private Attributes
int16_t _waveform [nsample] = {0}
Static Private Attributes
static const int nsample = 31
Detailed Description
Definition at line 9 of file TowerInfov3.h.
View newest version in sPHENIX GitHub at line 9 of file TowerInfov3.h
Constructor & Destructor Documentation
TowerInfov3::TowerInfov3 () inline
Definition at line 12 of file TowerInfov3.h.
View newest version in sPHENIX GitHub at line 12 of file TowerInfov3.h
TowerInfov3::~TowerInfov3 () inline override
Definition at line 13 of file TowerInfov3.h.
View newest version in sPHENIX GitHub at line 13 of file TowerInfov3.h
Member Function Documentation
TowerInfov3::ClassDefOverride (TowerInfov3 , 1) private
void TowerInfov3::Clear (Option_t * = "") override
Definition at line 14 of file TowerInfov3.cc.
View newest version in sPHENIX GitHub at line 14 of file TowerInfov3.cc
References _waveform, TowerInfov2::Clear(), i, and nsample.
void TowerInfov3::copy_tower (TowerInfo * tower) override virtual
Reimplemented from TowerInfov2.
Definition at line 41 of file TowerInfov3.cc.
View newest version in sPHENIX GitHub at line 41 of file TowerInfov3.cc
References TowerInfov2::copy_tower(), TowerInfo::get_waveform_value(), i, nsample, and set_waveform_value().
int TowerInfov3::get_nsample () const inline override virtual
Reimplemented from TowerInfo.
Definition at line 19 of file TowerInfov3.h.
View newest version in sPHENIX GitHub at line 19 of file TowerInfov3.h
References nsample.
int16_t TowerInfov3::get_waveform_value (int index) const override virtual
Reimplemented from TowerInfo.
Definition at line 23 of file TowerInfov3.cc.
View newest version in sPHENIX GitHub at line 23 of file TowerInfov3.cc
References _waveform, index, and nsample.
void TowerInfov3::Reset () override virtual
Clear Event.
Reimplemented from TowerInfov2.
Definition at line 5 of file TowerInfov3.cc.
View newest version in sPHENIX GitHub at line 5 of file TowerInfov3.cc
References _waveform, i, nsample, and TowerInfov2::Reset().
void TowerInfov3::set_waveform_value (int index, int16_t value) override virtual
Reimplemented from TowerInfo.
Definition at line 32 of file TowerInfov3.cc.
View newest version in sPHENIX GitHub at line 32 of file TowerInfov3.cc
References _waveform, index, nsample, and value.
Referenced by copy_tower().
Member Data Documentation
int16_t TowerInfov3::_waveform[nsample] = {0} private
Definition at line 27 of file TowerInfov3.h.
View newest version in sPHENIX GitHub at line 27 of file TowerInfov3.h
Referenced by Clear(), get_waveform_value(), Reset(), and set_waveform_value().
const int TowerInfov3::nsample = 31 static private
Definition at line 26 of file TowerInfov3.h.
View newest version in sPHENIX GitHub at line 26 of file TowerInfov3.h
Referenced by Clear(), copy_tower(), get_nsample(), get_waveform_value(), Reset(), and set_waveform_value().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/CaloBase/TowerInfov3.h
coresoftware/blob/master/offline/packages/CaloBase/TowerInfov3.cc