Analysis Software: G4Example02Detector Class Reference
G4Example02Detector Class Reference
#include <g4exampledetector/blob/master/parameter/source/G4Example02Detector.h>
Public Member Functions
G4Example02Detector (PHG4Subsystem *subsys, PHCompositeNode *Node, PHParameters *parameters, const std::string &dnam)
constructor
virtual ~G4Example02Detector ()
destructor
virtual void ConstructMe (G4LogicalVolume *world)
construct
virtual void Print (const std::string &what="ALL") const
void SuperDetector (const std::string &name)
const std::string SuperDetector () const
volume accessors
int IsInDetector (G4VPhysicalVolume *) const
Public Member Functions inherited from PHG4Detector
PHG4Detector ()=delete
constructor
PHG4Detector (PHG4Subsystem *subsys, PHCompositeNode *Node, const std::string &nam)
virtual ~PHG4Detector (void)
destructor
virtual void Construct (G4LogicalVolume *world) final
construct method
virtual void PostConstruction ()
Optional PostConstruction call after all geometry is constructed.
virtual void Verbosity (const int v)
virtual int Verbosity () const
virtual G4UserSteppingAction * GetSteppingAction ()
virtual std::string GetName () const
virtual void OverlapCheck (const bool chk)
virtual bool OverlapCheck () const
virtual int DisplayVolume (G4VSolid *volume, G4LogicalVolume *logvol, G4RotationMatrix *rotm=nullptr)
virtual int DisplayVolume (G4LogicalVolume *checksolid, G4LogicalVolume *logvol, G4RotationMatrix *rotm=nullptr)
virtual PHCompositeNode * topNode ()
virtual PHG4Subsystem * GetMySubsystem ()
Protected Attributes
PHParameters * m_Params
std::set< G4VPhysicalVolume * > m_PhysicalVolumesSet
std::string m_SuperDetector
Additional Inherited Members
Static Public Member Functions inherited from PHG4Detector
static G4Material * GetDetectorMaterial (const std::string &name, const bool quit=true)
static G4Element * GetDetectorElement (const std::string &name, const bool quit=true)
Detailed Description
Definition at line 17 of file G4Example02Detector.h.
View newest version in sPHENIX GitHub at line 17 of file G4Example02Detector.h
Constructor & Destructor Documentation
G4Example02Detector::G4Example02Detector (PHG4Subsystem * subsys, PHCompositeNode * Node, PHParameters * parameters, const std::string & dnam)
constructor
Definition at line 25 of file G4Example02Detector.cc.
View newest version in sPHENIX GitHub at line 25 of file G4Example02Detector.cc
virtual G4Example02Detector::~G4Example02Detector () inline virtual
destructor
Definition at line 24 of file G4Example02Detector.h.
View newest version in sPHENIX GitHub at line 24 of file G4Example02Detector.h
Member Function Documentation
void G4Example02Detector::ConstructMe (G4LogicalVolume * world) virtual
construct
Implements PHG4Detector.
Definition at line 47 of file G4Example02Detector.cc.
View newest version in sPHENIX GitHub at line 47 of file G4Example02Detector.cc
References Acts::UnitConstants::cm, deg, PHParameters::get_double_param(), m_Params, m_PhysicalVolumesSet, PHG4Detector::OverlapCheck(), and Acts::UnitConstants::rad.
int G4Example02Detector::IsInDetector (G4VPhysicalVolume * volume) const
Definition at line 36 of file G4Example02Detector.cc.
View newest version in sPHENIX GitHub at line 36 of file G4Example02Detector.cc
References m_PhysicalVolumesSet.
Referenced by G4Example02SteppingAction::UserSteppingAction().
void G4Example02Detector::Print (const std::string & what = "ALL") const virtual
Reimplemented from PHG4Detector.
Definition at line 77 of file G4Example02Detector.cc.
View newest version in sPHENIX GitHub at line 77 of file G4Example02Detector.cc
References m_Params, and PHParameters::Print().
Referenced by G4Example02Subsystem::Print().
void G4Example02Detector::SuperDetector (const std::string & name) inline
Definition at line 36 of file G4Example02Detector.h.
View newest version in sPHENIX GitHub at line 36 of file G4Example02Detector.h
References m_SuperDetector, and perf_headwind::name.
const std::string G4Example02Detector::SuperDetector () const inline
Definition at line 37 of file G4Example02Detector.h.
View newest version in sPHENIX GitHub at line 37 of file G4Example02Detector.h
References m_SuperDetector.
Member Data Documentation
PHParameters* G4Example02Detector::m_Params protected
Definition at line 40 of file G4Example02Detector.h.
View newest version in sPHENIX GitHub at line 40 of file G4Example02Detector.h
Referenced by ConstructMe(), and Print().
std::set<G4VPhysicalVolume *> G4Example02Detector::m_PhysicalVolumesSet protected
Definition at line 43 of file G4Example02Detector.h.
View newest version in sPHENIX GitHub at line 43 of file G4Example02Detector.h
Referenced by ConstructMe(), and IsInDetector().
std::string G4Example02Detector::m_SuperDetector protected
Definition at line 45 of file G4Example02Detector.h.
View newest version in sPHENIX GitHub at line 45 of file G4Example02Detector.h
Referenced by SuperDetector().
The documentation for this class was generated from the following files:
g4exampledetector/blob/master/parameter/source/G4Example02Detector.h
g4exampledetector/blob/master/parameter/source/G4Example02Detector.cc