Analysis Software: acts/blob/sPHENIX/Examples/Python/src/ModuleEntry.cpp File Reference
ModuleEntry.cpp File Reference
#include "Acts/ActsVersion.hpp"
#include "Acts/Geometry/GeometryContext.hpp"
#include "Acts/Geometry/GeometryIdentifier.hpp"
#include "Acts/MagneticField/MagneticFieldContext.hpp"
#include "Acts/Plugins/FpeMonitoring/FpeMonitor.hpp"
#include "Acts/Plugins/Python/Utilities.hpp"
#include "Acts/Utilities/CalibrationContext.hpp"
#include "Acts/Utilities/Logger.hpp"
#include <array>
#include <cstdint>
#include <cstdlib>
#include <limits>
#include <memory>
#include <optional>
#include <stdexcept>
#include <string>
#include <tuple>
#include <unordered_map>
#include <vector>
#include <pybind11/detail/common.h>
#include <pybind11/functional.h>
#include <pybind11/operators.h>
#include <pybind11/pybind11.h>
#include <pybind11/pytypes.h>
#include <pybind11/stl.h>
#include <pyerrors.h>
Namespaces
namespace Acts::Python
Functions
void Acts::Python::addUnits (Context &ctx)
void Acts::Python::addFramework (Context &ctx)
void Acts::Python::addLogging (Acts::Python::Context &ctx)
void Acts::Python::addPdgParticle (Acts::Python::Context &ctx)
void Acts::Python::addAlgebra (Acts::Python::Context &ctx)
void Acts::Python::addBinning (Context &ctx)
void Acts::Python::addEventData (Context &ctx)
void Acts::Python::addPropagation (Context &ctx)
void Acts::Python::addGeometry (Context &ctx)
void Acts::Python::addExperimentalGeometry (Context &ctx)
void Acts::Python::addMagneticField (Context &ctx)
void Acts::Python::addMaterial (Context &ctx)
void Acts::Python::addOutput (Context &ctx)
void Acts::Python::addDetector (Context &ctx)
void Acts::Python::addExampleAlgorithms (Context &ctx)
void Acts::Python::addInput (Context &ctx)
void Acts::Python::addGenerators (Context &ctx)
void Acts::Python::addTruthTracking (Context &ctx)
void Acts::Python::addTrackFitting (Context &ctx)
void Acts::Python::addTrackFinding (Context &ctx)
void Acts::Python::addVertexing (Context &ctx)
void Acts::Python::addAmbiguityResolution (Context &ctx)
void Acts::Python::addDigitization (Context &ctx)
void Acts::Python::addPythia8 (Context &ctx)
void Acts::Python::addJson (Context &ctx)
void Acts::Python::addHepMC3 (Context &ctx)
void Acts::Python::addExaTrkXTrackFinding (Context &ctx)
void Acts::Python::addEDM4hep (Context &ctx)
void Acts::Python::addSvg (Context &ctx)
void Acts::Python::addObj (Context &ctx)
void Acts::Python::addOnnx (Context &ctx)
void Acts::Python::addOnnxMlpack (Context &ctx)
void Acts::Python::addOnnxNeuralCalibrator (Context &ctx)
PYBIND11_MODULE (ActsPythonBindings, m)
Function Documentation
PYBIND11_MODULE (ActsPythonBindings , m)
Definition at line 84 of file ModuleEntry.cpp.
View newest version in sPHENIX GitHub at line 84 of file ModuleEntry.cpp
References Acts::Python::addAlgebra(), Acts::Python::addAmbiguityResolution(), Acts::Python::addBinning(), Acts::Python::addDetector(), Acts::Python::addDigitization(), Acts::Python::addEDM4hep(), Acts::Python::addEventData(), Acts::Python::addExampleAlgorithms(), Acts::Python::addExaTrkXTrackFinding(), Acts::Python::addExperimentalGeometry(), Acts::Python::addFramework(), Acts::Python::addGenerators(), Acts::Python::addGeometry(), Acts::Python::addHepMC3(), Acts::Python::addInput(), Acts::Python::addJson(), Acts::Python::addLogging(), Acts::Python::addMagneticField(), Acts::Python::addMaterial(), Acts::Python::addObj(), Acts::Python::addOnnx(), Acts::Python::addOnnxMlpack(), Acts::Python::addOnnxNeuralCalibrator(), Acts::Python::addOutput(), Acts::Python::addPdgParticle(), Acts::Python::addPropagation(), Acts::Python::addPythia8(), Acts::Python::addSvg(), Acts::Python::addTrackFinding(), Acts::Python::addTrackFitting(), Acts::Python::addTruthTracking(), Acts::Python::addUnits(), Acts::Python::addVertexing(), Acts::UnitConstants::m, and Acts::Python::Context::modules.