Analysis Software: analysis/blob/master/AndersonAnalysisModules/TrackStudies/STrackMatchingComparator/macros/QuickTreePlotter.C File Reference
QuickTreePlotter.C File Reference
#include <vector>
#include <iostream>
#include "TH1.h"
#include "TH2.h"
#include "TTree.h"
#include "TFile.h"
#include "TError.h"
#include "TString.h"
#include "TDirectory.h"
Functions
void QuickTreePlotter ()
Function Documentation
void QuickTreePlotter ()
Definition at line 23 of file QuickTreePlotter.C.
View newest version in sPHENIX GitHub at line 23 of file QuickTreePlotter.C
References cd(), Close(), Data, Draw(), and Write().