Analysis Software: SvtxTrack_v4 Class Reference
SvtxTrack_v4 Class Reference
#include <coresoftware/blob/master/offline/packages/trackbase_historic/SvtxTrack_v4.h>
Public Member Functions
SvtxTrack_v4 ()
SvtxTrack_v4 (const SvtxTrack &)
SvtxTrack_v4 (const SvtxTrack_v4 &)
SvtxTrack_v4 & operator= (const SvtxTrack_v4 &track)
~SvtxTrack_v4 () override
void identify (std::ostream &os=std::cout) const override
void Reset () override
Clear Event.
int isValid () const override
isValid returns non zero if object contains vailid data
PHObject * CloneMe () const override
Virtual copy constructor.
void CopyFrom (const SvtxTrack &) override
copy content from base class
void CopyFrom (SvtxTrack *source) override
copy content from base class
unsigned int get_id () const override
void set_id (unsigned int id) override
TrackSeed * get_tpc_seed () const override
void set_tpc_seed (TrackSeed *seed) override
TrackSeed * get_silicon_seed () const override
void set_silicon_seed (TrackSeed *seed) override
short int get_crossing () const override
void set_crossing (short int cross) override
unsigned int get_vertex_id () const override
void set_vertex_id (unsigned int id) override
bool get_positive_charge () const override
void set_positive_charge (bool ispos) override
int get_charge () const override
void set_charge (int charge) override
float get_chisq () const override
void set_chisq (float chisq) override
unsigned int get_ndf () const override
void set_ndf (int ndf) override
float get_quality () const override
float get_x () const override
void set_x (float x) override
float get_y () const override
void set_y (float y) override
float get_z () const override
void set_z (float z) override
float get_pos (unsigned int i) const override
float get_px () const override
void set_px (float px) override
float get_py () const override
void set_py (float py) override
float get_pz () const override
void set_pz (float pz) override
float get_mom (unsigned int i) const override
float get_p () const override
float get_pt () const override
float get_eta () const override
float get_phi () const override
float get_error (int i, int j) const override
void set_error (int i, int j, float value) override
bool empty_states () const override
size_t size_states () const override
size_t count_states (float pathlength) const override
void clear_states () override
const SvtxTrackState * get_state (float pathlength) const override
SvtxTrackState * get_state (float pathlength) override
SvtxTrackState * insert_state (const SvtxTrackState *state) override
size_t erase_state (float pathlength) override
ConstStateIter begin_states () const override
ConstStateIter find_state (float pathlength) const override
ConstStateIter end_states () const override
StateIter begin_states () override
StateIter find_state (float pathlength) override
StateIter end_states () override
Public Member Functions inherited from SvtxTrack
~SvtxTrack () override=default
virtual void clear_cluster_keys ()
virtual bool empty_cluster_keys () const
virtual size_t size_cluster_keys () const
virtual void insert_cluster_key (TrkrDefs::cluskey)
virtual size_t erase_cluster_key (TrkrDefs::cluskey)
virtual ConstClusterKeyIter find_cluster_key (TrkrDefs::cluskey clusterid) const
virtual ConstClusterKeyIter begin_cluster_keys () const
virtual ConstClusterKeyIter end_cluster_keys () const
virtual ClusterKeyIter begin_cluster_keys ()
virtual ClusterKeyIter find_cluster_keys (unsigned int clusterid)
virtual ClusterKeyIter end_cluster_keys ()
virtual void clear_clusters ()
virtual bool empty_clusters () const
virtual size_t size_clusters () const
virtual void insert_cluster (unsigned int)
virtual size_t erase_cluster (unsigned int)
virtual ConstClusterIter begin_clusters () const
virtual ConstClusterIter find_cluster (unsigned int) const
virtual ConstClusterIter end_clusters () const
virtual ClusterIter begin_clusters ()
virtual ClusterIter find_cluster (unsigned int clusterid)
virtual ClusterIter end_clusters ()
virtual float get_cal_dphi (CAL_LAYER) const
virtual void set_cal_dphi (CAL_LAYER, float)
virtual float get_cal_deta (CAL_LAYER) const
virtual void set_cal_deta (CAL_LAYER, float)
virtual float get_cal_energy_3x3 (CAL_LAYER) const
virtual void set_cal_energy_3x3 (CAL_LAYER, float)
virtual float get_cal_energy_5x5 (CAL_LAYER) const
virtual void set_cal_energy_5x5 (CAL_LAYER, float)
virtual unsigned int get_cal_cluster_id (CAL_LAYER) const
virtual void set_cal_cluster_id (CAL_LAYER, unsigned int)
virtual TrkrDefs::cluskey get_cal_cluster_key (CAL_LAYER) const
virtual void set_cal_cluster_key (CAL_LAYER, TrkrDefs::cluskey)
virtual float get_cal_cluster_e (CAL_LAYER) const
virtual void set_cal_cluster_e (CAL_LAYER, float)
virtual float get_acts_covariance (unsigned int, unsigned int) const
virtual void set_acts_covariance (unsigned int, unsigned int, float)
virtual float get_dca () const
virtual void set_dca (float)
virtual float get_dca_error () const
virtual void set_dca_error (float)
virtual float get_dca2d () const
virtual void set_dca2d (float)
virtual float get_dca2d_error () const
virtual void set_dca2d_error (float)
virtual float get_dca3d_xy () const
virtual void set_dca3d_xy (float)
virtual float get_dca3d_xy_error () const
virtual void set_dca3d_xy_error (float)
virtual float get_dca3d_z () const
virtual void set_dca3d_z (float)
virtual float get_dca3d_z_error () const
virtual void set_dca3d_z_error (float)
virtual unsigned int get_truth_track_id () const
virtual void set_truth_track_id (unsigned int)
virtual void set_num_measurements (int)
virtual unsigned int get_num_measurements () const
virtual bool empty_g4hit_id () const
virtual size_t size_g4hit_id () const
virtual void add_g4hit_id (int, PHG4HitDefs::keytype)
virtual HitIdIter begin_g4hit_id ()
virtual HitIdConstIter begin_g4hit_id () const
virtual HitIdIter find_g4hit_id (int)
virtual HitIdConstIter find_g4hit_id (int) const
virtual HitIdIter end_g4hit_id ()
virtual HitIdConstIter end_g4hit_id () const
virtual size_t remove_g4hit_id (int, PHG4HitDefs::keytype)
virtual size_t remove_g4hit_volume (int)
virtual void clear_g4hit_id ()
virtual const HitIdMap & g4hit_ids () const
Public Member Functions inherited from PHObject
PHObject ()
ctor
~PHObject () override
dtor
virtual PHObject * clone () const final
PHObject * Clone (const char *newname="") const final
void Copy (TObject &object) const final
virtual int Integrate () const
virtual int Integrate (PHObject *)
virtual void CopyFrom (const PHObject *obj)
Private Attributes
TrackSeed * _tpc_seed = nullptr
TrackSeed * _silicon_seed = nullptr
unsigned int _track_id = UINT_MAX
unsigned int _vertex_id = UINT_MAX
bool _is_positive_charge = false
float _chisq = NAN
unsigned int _ndf = 0
short int _track_crossing = SHRT_MAX
StateMap _states
Additional Inherited Members
Public Types inherited from SvtxTrack
enum CAL_LAYER {
PRES = 0, CEMC = 1, HCALIN = 2, HCALOUT = 3,
OUTER_CEMC = 4, OUTER_HCALIN = 5, OUTER_HCALOUT = 6
}
typedef std::map< float,
SvtxTrackState * > StateMap
typedef StateMap::const_iterator ConstStateIter
typedef StateMap::iterator StateIter
typedef std::set< unsigned int > ClusterSet
typedef ClusterSet::const_iterator ConstClusterIter
typedef ClusterSet::iterator ClusterIter
typedef std::set
< TrkrDefs::cluskey > ClusterKeySet
typedef
ClusterKeySet::const_iterator ConstClusterKeyIter
typedef ClusterKeySet::iterator ClusterKeyIter
typedef std::map< int,
std::set< PHG4HitDefs::keytype > > HitIdMap
typedef HitIdMap::iterator HitIdIter
typedef HitIdMap::const_iterator HitIdConstIter
Protected Member Functions inherited from SvtxTrack
SvtxTrack ()
ClassDefOverride (SvtxTrack, 1)
Detailed Description
Definition at line 18 of file SvtxTrack_v4.h.
View newest version in sPHENIX GitHub at line 18 of file SvtxTrack_v4.h
Constructor & Destructor Documentation
SvtxTrack_v4::SvtxTrack_v4 ()
Definition at line 13 of file SvtxTrack_v4.cc.
View newest version in sPHENIX GitHub at line 13 of file SvtxTrack_v4.cc
References _states.
Referenced by CloneMe(), and Reset().
SvtxTrack_v4::SvtxTrack_v4 (const SvtxTrack & source)
Definition at line 20 of file SvtxTrack_v4.cc.
View newest version in sPHENIX GitHub at line 20 of file SvtxTrack_v4.cc
References CopyFrom().
SvtxTrack_v4::SvtxTrack_v4 (const SvtxTrack_v4 & source)
Definition at line 26 of file SvtxTrack_v4.cc.
View newest version in sPHENIX GitHub at line 26 of file SvtxTrack_v4.cc
References CopyFrom().
SvtxTrack_v4::~SvtxTrack_v4 () override
Definition at line 32 of file SvtxTrack_v4.cc.
View newest version in sPHENIX GitHub at line 32 of file SvtxTrack_v4.cc
References clear_states().
Member Function Documentation
ConstStateIter SvtxTrack_v4::begin_states () const inline override virtual
Reimplemented from SvtxTrack.
Definition at line 125 of file SvtxTrack_v4.h.
View newest version in sPHENIX GitHub at line 125 of file SvtxTrack_v4.h
References _states.
StateIter SvtxTrack_v4::begin_states () inline override virtual
Reimplemented from SvtxTrack.
Definition at line 129 of file SvtxTrack_v4.h.
View newest version in sPHENIX GitHub at line 129 of file SvtxTrack_v4.h
References _states.
void SvtxTrack_v4::clear_states () override virtual
Reimplemented from SvtxTrack.
Definition at line 100 of file SvtxTrack_v4.cc.
View newest version in sPHENIX GitHub at line 100 of file SvtxTrack_v4.cc
References _states.
Referenced by CopyFrom(), and ~SvtxTrack_v4().
PHObject* SvtxTrack_v4::CloneMe () const inline override virtual
Virtual copy constructor.
Reimplemented from SvtxTrack.
Definition at line 39 of file SvtxTrack_v4.h.
View newest version in sPHENIX GitHub at line 39 of file SvtxTrack_v4.h
References SvtxTrack_v4().
void SvtxTrack_v4::CopyFrom (const SvtxTrack &) override virtual
copy content from base class
Reimplemented from SvtxTrack.
Definition at line 35 of file SvtxTrack_v4.cc.
View newest version in sPHENIX GitHub at line 35 of file SvtxTrack_v4.cc
References _chisq, _is_positive_charge, _ndf, _silicon_seed, _states, _tpc_seed, _track_crossing, _vertex_id, SvtxTrack::begin_states(), clear_states(), SvtxTrack::CopyFrom(), SvtxTrack::end_states(), SvtxTrack::get_chisq(), SvtxTrack::get_crossing(), SvtxTrack::get_ndf(), SvtxTrack::get_positive_charge(), SvtxTrack::get_silicon_seed(), SvtxTrack::get_tpc_seed(), and SvtxTrack::get_vertex_id().
Referenced by operator=(), and SvtxTrack_v4().
void SvtxTrack_v4::CopyFrom (SvtxTrack *) inline override virtual
copy content from base class
Reimplemented from SvtxTrack.
Definition at line 45 of file SvtxTrack_v4.h.
View newest version in sPHENIX GitHub at line 45 of file SvtxTrack_v4.h
References CopyFrom().
Referenced by CopyFrom().
size_t SvtxTrack_v4::count_states (float pathlength) const inline override virtual
Reimplemented from SvtxTrack.
Definition at line 116 of file SvtxTrack_v4.h.
View newest version in sPHENIX GitHub at line 116 of file SvtxTrack_v4.h
References _states.
bool SvtxTrack_v4::empty_states () const inline override virtual
Reimplemented from SvtxTrack.
Definition at line 114 of file SvtxTrack_v4.h.
View newest version in sPHENIX GitHub at line 114 of file SvtxTrack_v4.h
References _states.
ConstStateIter SvtxTrack_v4::end_states () const inline override virtual
Reimplemented from SvtxTrack.
Definition at line 127 of file SvtxTrack_v4.h.
View newest version in sPHENIX GitHub at line 127 of file SvtxTrack_v4.h
References _states.
StateIter SvtxTrack_v4::end_states () inline override virtual
Reimplemented from SvtxTrack.
Definition at line 131 of file SvtxTrack_v4.h.
View newest version in sPHENIX GitHub at line 131 of file SvtxTrack_v4.h
References _states.
size_t SvtxTrack_v4::erase_state (float pathlength) override virtual
Reimplemented from SvtxTrack.
Definition at line 141 of file SvtxTrack_v4.cc.
View newest version in sPHENIX GitHub at line 141 of file SvtxTrack_v4.cc
References _states.
ConstStateIter SvtxTrack_v4::find_state (float pathlength) const inline override virtual
Reimplemented from SvtxTrack.
Definition at line 126 of file SvtxTrack_v4.h.
View newest version in sPHENIX GitHub at line 126 of file SvtxTrack_v4.h
References _states.
StateIter SvtxTrack_v4::find_state (float pathlength) inline override virtual
Reimplemented from SvtxTrack.
Definition at line 130 of file SvtxTrack_v4.h.
View newest version in sPHENIX GitHub at line 130 of file SvtxTrack_v4.h
References _states.
int SvtxTrack_v4::get_charge () const inline override virtual
Reimplemented from SvtxTrack.
Definition at line 70 of file SvtxTrack_v4.h.
View newest version in sPHENIX GitHub at line 70 of file SvtxTrack_v4.h
References get_positive_charge().
Referenced by identify().
float SvtxTrack_v4::get_chisq () const inline override virtual
Reimplemented from SvtxTrack.
Definition at line 73 of file SvtxTrack_v4.h.
View newest version in sPHENIX GitHub at line 73 of file SvtxTrack_v4.h
References _chisq.
Referenced by identify().
short int SvtxTrack_v4::get_crossing () const inline override virtual
Reimplemented from SvtxTrack.
Definition at line 61 of file SvtxTrack_v4.h.
View newest version in sPHENIX GitHub at line 61 of file SvtxTrack_v4.h
References _track_crossing.
float SvtxTrack_v4::get_error (int i, int j) const inline override virtual
Reimplemented from SvtxTrack.
Definition at line 108 of file SvtxTrack_v4.h.
View newest version in sPHENIX GitHub at line 108 of file SvtxTrack_v4.h
References _states.
float SvtxTrack_v4::get_eta () const inline override virtual
Reimplemented from SvtxTrack.
Definition at line 105 of file SvtxTrack_v4.h.
View newest version in sPHENIX GitHub at line 105 of file SvtxTrack_v4.h
References get_pt(), and get_pz().
unsigned int SvtxTrack_v4::get_id () const inline override virtual
Reimplemented from SvtxTrack.
Definition at line 52 of file SvtxTrack_v4.h.
View newest version in sPHENIX GitHub at line 52 of file SvtxTrack_v4.h
References _track_id.
Referenced by identify().
float SvtxTrack_v4::get_mom (unsigned int i) const inline override virtual
Reimplemented from SvtxTrack.
Definition at line 101 of file SvtxTrack_v4.h.
View newest version in sPHENIX GitHub at line 101 of file SvtxTrack_v4.h
References _states.
unsigned int SvtxTrack_v4::get_ndf () const inline override virtual
Reimplemented from SvtxTrack.
Definition at line 76 of file SvtxTrack_v4.h.
View newest version in sPHENIX GitHub at line 76 of file SvtxTrack_v4.h
References _ndf.
Referenced by identify().
float SvtxTrack_v4::get_p () const inline override virtual
Reimplemented from SvtxTrack.
Definition at line 103 of file SvtxTrack_v4.h.
View newest version in sPHENIX GitHub at line 103 of file SvtxTrack_v4.h
References get_px(), get_py(), and get_pz().
float SvtxTrack_v4::get_phi () const inline override virtual
Reimplemented from SvtxTrack.
Definition at line 106 of file SvtxTrack_v4.h.
View newest version in sPHENIX GitHub at line 106 of file SvtxTrack_v4.h
References get_px(), and get_py().
float SvtxTrack_v4::get_pos (unsigned int i) const inline override virtual
Reimplemented from SvtxTrack.
Definition at line 90 of file SvtxTrack_v4.h.
View newest version in sPHENIX GitHub at line 90 of file SvtxTrack_v4.h
References _states.
bool SvtxTrack_v4::get_positive_charge () const inline override virtual
Reimplemented from SvtxTrack.
Definition at line 67 of file SvtxTrack_v4.h.
View newest version in sPHENIX GitHub at line 67 of file SvtxTrack_v4.h
References _is_positive_charge.
Referenced by get_charge().
float SvtxTrack_v4::get_pt () const inline override virtual
Reimplemented from SvtxTrack.
Definition at line 104 of file SvtxTrack_v4.h.
View newest version in sPHENIX GitHub at line 104 of file SvtxTrack_v4.h
References get_px(), and get_py().
Referenced by get_eta().
float SvtxTrack_v4::get_px () const inline override virtual
Reimplemented from SvtxTrack.
Definition at line 92 of file SvtxTrack_v4.h.
View newest version in sPHENIX GitHub at line 92 of file SvtxTrack_v4.h
References _states.
Referenced by get_p(), get_phi(), get_pt(), and identify().
float SvtxTrack_v4::get_py () const inline override virtual
Reimplemented from SvtxTrack.
Definition at line 95 of file SvtxTrack_v4.h.
View newest version in sPHENIX GitHub at line 95 of file SvtxTrack_v4.h
References _states.
Referenced by get_p(), get_phi(), get_pt(), and identify().
float SvtxTrack_v4::get_pz () const inline override virtual
Reimplemented from SvtxTrack.
Definition at line 98 of file SvtxTrack_v4.h.
View newest version in sPHENIX GitHub at line 98 of file SvtxTrack_v4.h
References _states.
Referenced by get_eta(), get_p(), and identify().
float SvtxTrack_v4::get_quality () const inline override virtual
Reimplemented from SvtxTrack.
Definition at line 79 of file SvtxTrack_v4.h.
View newest version in sPHENIX GitHub at line 79 of file SvtxTrack_v4.h
References _chisq, and _ndf.
Referenced by PHActsTrkFitter::loopTracks().
TrackSeed* SvtxTrack_v4::get_silicon_seed () const inline override virtual
Reimplemented from SvtxTrack.
Definition at line 58 of file SvtxTrack_v4.h.
View newest version in sPHENIX GitHub at line 58 of file SvtxTrack_v4.h
References _silicon_seed.
const SvtxTrackState * SvtxTrack_v4::get_state (float pathlength) const override virtual
Reimplemented from SvtxTrack.
Definition at line 113 of file SvtxTrack_v4.cc.
View newest version in sPHENIX GitHub at line 113 of file SvtxTrack_v4.cc
References _states.
SvtxTrackState * SvtxTrack_v4::get_state (float pathlength) override virtual
Reimplemented from SvtxTrack.
Definition at line 119 of file SvtxTrack_v4.cc.
View newest version in sPHENIX GitHub at line 119 of file SvtxTrack_v4.cc
References _states.
TrackSeed* SvtxTrack_v4::get_tpc_seed () const inline override virtual
Reimplemented from SvtxTrack.
Definition at line 55 of file SvtxTrack_v4.h.
View newest version in sPHENIX GitHub at line 55 of file SvtxTrack_v4.h
References _tpc_seed.
unsigned int SvtxTrack_v4::get_vertex_id () const inline override virtual
Reimplemented from SvtxTrack.
Definition at line 64 of file SvtxTrack_v4.h.
View newest version in sPHENIX GitHub at line 64 of file SvtxTrack_v4.h
References _vertex_id.
Referenced by identify().
float SvtxTrack_v4::get_x () const inline override virtual
Reimplemented from SvtxTrack.
Definition at line 81 of file SvtxTrack_v4.h.
View newest version in sPHENIX GitHub at line 81 of file SvtxTrack_v4.h
References _states.
Referenced by identify().
float SvtxTrack_v4::get_y () const inline override virtual
Reimplemented from SvtxTrack.
Definition at line 84 of file SvtxTrack_v4.h.
View newest version in sPHENIX GitHub at line 84 of file SvtxTrack_v4.h
References _states.
Referenced by identify().
float SvtxTrack_v4::get_z () const inline override virtual
Reimplemented from SvtxTrack.
Definition at line 87 of file SvtxTrack_v4.h.
View newest version in sPHENIX GitHub at line 87 of file SvtxTrack_v4.h
References _states.
Referenced by identify().
void SvtxTrack_v4::identify (std::ostream & os = std::cout) const override virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from SvtxTrack.
Definition at line 58 of file SvtxTrack_v4.cc.
View newest version in sPHENIX GitHub at line 58 of file SvtxTrack_v4.cc
References _silicon_seed, _states, _tpc_seed, TrackSeed::begin_cluster_keys(), TrackSeed::end_cluster_keys(), get_charge(), get_chisq(), get_id(), get_ndf(), get_px(), get_py(), get_pz(), get_vertex_id(), get_x(), get_y(), and get_z().
SvtxTrackState * SvtxTrack_v4::insert_state (const SvtxTrackState * state) override virtual
Reimplemented from SvtxTrack.
Definition at line 125 of file SvtxTrack_v4.cc.
View newest version in sPHENIX GitHub at line 125 of file SvtxTrack_v4.cc
References _states, SvtxTrackState::CloneMe(), and SvtxTrackState::get_pathlength().
int SvtxTrack_v4::isValid () const override virtual
isValid returns non zero if object contains vailid data
Reimplemented from SvtxTrack.
Definition at line 108 of file SvtxTrack_v4.cc.
View newest version in sPHENIX GitHub at line 108 of file SvtxTrack_v4.cc
SvtxTrack_v4 & SvtxTrack_v4::operator= (const SvtxTrack_v4 & track)
Definition at line 29 of file SvtxTrack_v4.cc.
View newest version in sPHENIX GitHub at line 29 of file SvtxTrack_v4.cc
References CopyFrom().
void SvtxTrack_v4::Reset () inline override virtual
Clear Event.
Reimplemented from PHObject.
Definition at line 37 of file SvtxTrack_v4.h.
View newest version in sPHENIX GitHub at line 37 of file SvtxTrack_v4.h
References SvtxTrack_v4().
void SvtxTrack_v4::set_charge (int charge) inline override virtual
Reimplemented from SvtxTrack.
Definition at line 71 of file SvtxTrack_v4.h.
View newest version in sPHENIX GitHub at line 71 of file SvtxTrack_v4.h
References set_positive_charge().
Referenced by HelicalFitter::process_event().
void SvtxTrack_v4::set_chisq (float chisq) inline override virtual
Reimplemented from SvtxTrack.
Definition at line 74 of file SvtxTrack_v4.h.
View newest version in sPHENIX GitHub at line 74 of file SvtxTrack_v4.h
References _chisq.
void SvtxTrack_v4::set_crossing (short int cross) inline override virtual
Reimplemented from SvtxTrack.
Definition at line 62 of file SvtxTrack_v4.h.
View newest version in sPHENIX GitHub at line 62 of file SvtxTrack_v4.h
References _track_crossing, and Acts::VectorHelpers::cross().
Referenced by PHCosmicsTrkFitter::loopTracks(), PHActsTrkFitter::loopTracks(), and HelicalFitter::process_event().
void SvtxTrack_v4::set_error (int i, int j, float value) inline override virtual
Reimplemented from SvtxTrack.
Definition at line 109 of file SvtxTrack_v4.h.
View newest version in sPHENIX GitHub at line 109 of file SvtxTrack_v4.h
References _states.
void SvtxTrack_v4::set_id (unsigned int id) inline override virtual
Reimplemented from SvtxTrack.
Definition at line 53 of file SvtxTrack_v4.h.
View newest version in sPHENIX GitHub at line 53 of file SvtxTrack_v4.h
References _track_id, and train_ambiguity_solver::id.
Referenced by PHCosmicsTrkFitter::loopTracks(), PHActsTrkFitter::loopTracks(), and HelicalFitter::process_event().
void SvtxTrack_v4::set_ndf (int ndf) inline override virtual
Reimplemented from SvtxTrack.
Definition at line 77 of file SvtxTrack_v4.h.
View newest version in sPHENIX GitHub at line 77 of file SvtxTrack_v4.h
References _ndf.
void SvtxTrack_v4::set_positive_charge (bool ispos) inline override virtual
Reimplemented from SvtxTrack.
Definition at line 68 of file SvtxTrack_v4.h.
View newest version in sPHENIX GitHub at line 68 of file SvtxTrack_v4.h
References _is_positive_charge.
Referenced by set_charge().
void SvtxTrack_v4::set_px (float px) inline override virtual
Reimplemented from SvtxTrack.
Definition at line 93 of file SvtxTrack_v4.h.
View newest version in sPHENIX GitHub at line 93 of file SvtxTrack_v4.h
References _states.
Referenced by HelicalFitter::process_event().
void SvtxTrack_v4::set_py (float py) inline override virtual
Reimplemented from SvtxTrack.
Definition at line 96 of file SvtxTrack_v4.h.
View newest version in sPHENIX GitHub at line 96 of file SvtxTrack_v4.h
References _states.
Referenced by HelicalFitter::process_event().
void SvtxTrack_v4::set_pz (float pz) inline override virtual
Reimplemented from SvtxTrack.
Definition at line 99 of file SvtxTrack_v4.h.
View newest version in sPHENIX GitHub at line 99 of file SvtxTrack_v4.h
References _states.
Referenced by HelicalFitter::process_event().
void SvtxTrack_v4::set_silicon_seed (TrackSeed * seed) inline override virtual
Reimplemented from SvtxTrack.
Definition at line 59 of file SvtxTrack_v4.h.
View newest version in sPHENIX GitHub at line 59 of file SvtxTrack_v4.h
References _silicon_seed, and seed.
Referenced by PHCosmicsTrkFitter::loopTracks(), PHActsTrkFitter::loopTracks(), and HelicalFitter::process_event().
void SvtxTrack_v4::set_tpc_seed (TrackSeed * seed) inline override virtual
Reimplemented from SvtxTrack.
Definition at line 56 of file SvtxTrack_v4.h.
View newest version in sPHENIX GitHub at line 56 of file SvtxTrack_v4.h
References _tpc_seed, and seed.
Referenced by PHCosmicsTrkFitter::loopTracks(), PHActsTrkFitter::loopTracks(), and HelicalFitter::process_event().
void SvtxTrack_v4::set_vertex_id (unsigned int id) inline override virtual
Reimplemented from SvtxTrack.
Definition at line 65 of file SvtxTrack_v4.h.
View newest version in sPHENIX GitHub at line 65 of file SvtxTrack_v4.h
References _vertex_id, and train_ambiguity_solver::id.
void SvtxTrack_v4::set_x (float x) inline override virtual
Reimplemented from SvtxTrack.
Definition at line 82 of file SvtxTrack_v4.h.
View newest version in sPHENIX GitHub at line 82 of file SvtxTrack_v4.h
References _states.
Referenced by HelicalFitter::process_event().
void SvtxTrack_v4::set_y (float y) inline override virtual
Reimplemented from SvtxTrack.
Definition at line 85 of file SvtxTrack_v4.h.
View newest version in sPHENIX GitHub at line 85 of file SvtxTrack_v4.h
References _states.
Referenced by HelicalFitter::process_event().
void SvtxTrack_v4::set_z (float z) inline override virtual
Reimplemented from SvtxTrack.
Definition at line 88 of file SvtxTrack_v4.h.
View newest version in sPHENIX GitHub at line 88 of file SvtxTrack_v4.h
References _states.
Referenced by HelicalFitter::process_event().
size_t SvtxTrack_v4::size_states () const inline override virtual
Reimplemented from SvtxTrack.
Definition at line 115 of file SvtxTrack_v4.h.
View newest version in sPHENIX GitHub at line 115 of file SvtxTrack_v4.h
References _states.
Member Data Documentation
float SvtxTrack_v4::_chisq = NAN private
Definition at line 141 of file SvtxTrack_v4.h.
View newest version in sPHENIX GitHub at line 141 of file SvtxTrack_v4.h
Referenced by CopyFrom(), get_chisq(), get_quality(), and set_chisq().
bool SvtxTrack_v4::_is_positive_charge = false private
Definition at line 140 of file SvtxTrack_v4.h.
View newest version in sPHENIX GitHub at line 140 of file SvtxTrack_v4.h
Referenced by CopyFrom(), get_positive_charge(), and set_positive_charge().
unsigned int SvtxTrack_v4::_ndf = 0 private
Definition at line 142 of file SvtxTrack_v4.h.
View newest version in sPHENIX GitHub at line 142 of file SvtxTrack_v4.h
Referenced by CopyFrom(), get_ndf(), get_quality(), and set_ndf().
TrackSeed* SvtxTrack_v4::_silicon_seed = nullptr private
Definition at line 137 of file SvtxTrack_v4.h.
View newest version in sPHENIX GitHub at line 137 of file SvtxTrack_v4.h
Referenced by CopyFrom(), get_silicon_seed(), identify(), and set_silicon_seed().
StateMap SvtxTrack_v4::_states private
Definition at line 146 of file SvtxTrack_v4.h.
View newest version in sPHENIX GitHub at line 146 of file SvtxTrack_v4.h
Referenced by begin_states(), clear_states(), CopyFrom(), count_states(), empty_states(), end_states(), erase_state(), find_state(), get_error(), get_mom(), get_pos(), get_px(), get_py(), get_pz(), get_state(), get_x(), get_y(), get_z(), identify(), insert_state(), set_error(), set_px(), set_py(), set_pz(), set_x(), set_y(), set_z(), size_states(), and SvtxTrack_v4().
TrackSeed* SvtxTrack_v4::_tpc_seed = nullptr private
Definition at line 136 of file SvtxTrack_v4.h.
View newest version in sPHENIX GitHub at line 136 of file SvtxTrack_v4.h
Referenced by CopyFrom(), get_tpc_seed(), identify(), and set_tpc_seed().
short int SvtxTrack_v4::_track_crossing = SHRT_MAX private
Definition at line 143 of file SvtxTrack_v4.h.
View newest version in sPHENIX GitHub at line 143 of file SvtxTrack_v4.h
Referenced by CopyFrom(), get_crossing(), and set_crossing().
unsigned int SvtxTrack_v4::_track_id = UINT_MAX private
Definition at line 138 of file SvtxTrack_v4.h.
View newest version in sPHENIX GitHub at line 138 of file SvtxTrack_v4.h
Referenced by get_id(), and set_id().
unsigned int SvtxTrack_v4::_vertex_id = UINT_MAX private
Definition at line 139 of file SvtxTrack_v4.h.
View newest version in sPHENIX GitHub at line 139 of file SvtxTrack_v4.h
Referenced by CopyFrom(), get_vertex_id(), and set_vertex_id().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/trackbase_historic/SvtxTrack_v4.h
coresoftware/blob/master/offline/packages/trackbase_historic/SvtxTrack_v4.cc