Analysis Software: PHTrackSeeding Class Reference
PHTrackSeeding Class Reference abstract
Base class for track seeding.
#include <coresoftware/blob/master/offline/packages/trackreco/PHTrackSeeding.h>
Public Member Functions
PHTrackSeeding (const std::string &name="PHTrackSeeding")
~PHTrackSeeding () override
int InitRun (PHCompositeNode *topNode) override
int process_event (PHCompositeNode *topNode) override
int End (PHCompositeNode *topNode) override
Called at the end of all processing.
void set_track_map_name (const std::string &map_name)
void set_do_hit_association (bool do_assoc)
void SetUseTruthClusters (bool setit)
void SetIteration (int iter)
Public Member Functions inherited from SubsysReco
~SubsysReco () override
virtual int EndRun (const int)
Called at the end of each run.
virtual int Init (PHCompositeNode *)
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
void Print (const std::string &="ALL") const override
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Protected Member Functions
virtual int Setup (PHCompositeNode *topNode)
virtual int Process (PHCompositeNode *topNode)=0
virtual int End ()=0
Called in SubsysReco::End.
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Protected Member Functions inherited from Fun4AllBase
Fun4AllBase (const std::string &name="NONAME")
Protected Attributes
TrkrClusterContainer * _cluster_map = nullptr
TrkrClusterHitAssoc * _cluster_hit_map = nullptr
TrkrClusterIterationMapv1 * _iteration_map
int _n_iteration
bool do_hit_assoc = true
SvtxVertexMap * _vertex_map = nullptr
TrackSeedContainer * _track_map = nullptr
TrkrHitSetContainer * _hitsets = nullptr
std::string _track_map_name = "TpcTrackSeedContainer"
bool _use_truth_clusters = false
Private Member Functions
int CreateNodes (PHCompositeNode *topNode)
create new node output pointers
int GetNodes (PHCompositeNode *topNode)
fetch node pointers
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = std::numeric_limits<int>::max() - 10
}
Detailed Description
Base class for track seeding.
Definition at line 32 of file PHTrackSeeding.h.
View newest version in sPHENIX GitHub at line 32 of file PHTrackSeeding.h
Constructor & Destructor Documentation
PHTrackSeeding::PHTrackSeeding (const std::string & name = "PHTrackSeeding")
Definition at line 30 of file PHTrackSeeding.cc.
View newest version in sPHENIX GitHub at line 30 of file PHTrackSeeding.cc
PHTrackSeeding::~PHTrackSeeding () inline override
Definition at line 36 of file PHTrackSeeding.h.
View newest version in sPHENIX GitHub at line 36 of file PHTrackSeeding.h
Member Function Documentation
int PHTrackSeeding::CreateNodes (PHCompositeNode * topNode) private
create new node output pointers
Definition at line 72 of file PHTrackSeeding.cc.
View newest version in sPHENIX GitHub at line 72 of file PHTrackSeeding.cc
References _track_map, _track_map_name, Fun4AllReturnCodes::ABORTEVENT, PHCompositeNode::addNode(), Fun4AllReturnCodes::EVENT_OK, PHNodeIterator::findFirst(), TrackSeedContainer::identify(), PHWHERE, and Fun4AllBase::Verbosity().
Referenced by Setup().
int PHTrackSeeding::End (PHCompositeNode *) override virtual
Called at the end of all processing.
Reimplemented from SubsysReco.
Definition at line 54 of file PHTrackSeeding.cc.
View newest version in sPHENIX GitHub at line 54 of file PHTrackSeeding.cc
References End().
virtual int PHTrackSeeding::End () protected pure virtual
Called in SubsysReco::End.
Implemented in PHCASeeding, PHHybridSeeding, PHTruthTrackSeeding, and PHSiliconTruthTrackSeeding.
Referenced by End().
int PHTrackSeeding::GetNodes (PHCompositeNode * topNode) private
fetch node pointers
Definition at line 116 of file PHTrackSeeding.cc.
View newest version in sPHENIX GitHub at line 116 of file PHTrackSeeding.cc
References _cluster_hit_map, _cluster_map, _track_map, _track_map_name, _use_truth_clusters, Fun4AllReturnCodes::ABORTEVENT, do_hit_assoc, Fun4AllReturnCodes::EVENT_OK, and PHWHERE.
Referenced by Setup().
int PHTrackSeeding::InitRun (PHCompositeNode *) override virtual
Called for first event when run number is known. Typically this is where you may want to fetch data from database, because you know the run number.
Reimplemented from SubsysReco.
Definition at line 37 of file PHTrackSeeding.cc.
View newest version in sPHENIX GitHub at line 37 of file PHTrackSeeding.cc
References Setup().
virtual int PHTrackSeeding::Process (PHCompositeNode * topNode) protected pure virtual
process event interface for trackers, called in process_event. implemented in derived classes
Implemented in PHCASeeding, PHHybridSeeding, PHTruthTrackSeeding, and PHSiliconTruthTrackSeeding.
Referenced by process_event().
int PHTrackSeeding::process_event (PHCompositeNode *) override virtual
Called for each event. This is where you do the real work.
Reimplemented from SubsysReco.
Definition at line 42 of file PHTrackSeeding.cc.
View newest version in sPHENIX GitHub at line 42 of file PHTrackSeeding.cc
References _iteration_map, _n_iteration, Fun4AllReturnCodes::ABORTEVENT, PHWHERE, and Process().
void PHTrackSeeding::set_do_hit_association (bool do_assoc) inline
Definition at line 42 of file PHTrackSeeding.h.
View newest version in sPHENIX GitHub at line 42 of file PHTrackSeeding.h
References do_hit_assoc.
void PHTrackSeeding::set_track_map_name (const std::string & map_name) inline
Definition at line 41 of file PHTrackSeeding.h.
View newest version in sPHENIX GitHub at line 41 of file PHTrackSeeding.h
References _track_map_name.
Referenced by PHSiliconTruthTrackSeeding::Setup().
void PHTrackSeeding::SetIteration (int iter) inline
Definition at line 44 of file PHTrackSeeding.h.
View newest version in sPHENIX GitHub at line 44 of file PHTrackSeeding.h
References _n_iteration.
int PHTrackSeeding::Setup (PHCompositeNode * topNode) protected virtual
setup interface for trackers, called in InitRun, setup things like pointers to nodes. overrided in derived classes
Reimplemented in PHCASeeding, PHHybridSeeding, PHTruthTrackSeeding, and PHSiliconTruthTrackSeeding.
Definition at line 59 of file PHTrackSeeding.cc.
View newest version in sPHENIX GitHub at line 59 of file PHTrackSeeding.cc
References CreateNodes(), Fun4AllReturnCodes::EVENT_OK, and GetNodes().
Referenced by InitRun(), PHSiliconTruthTrackSeeding::Setup(), PHTruthTrackSeeding::Setup(), PHHybridSeeding::Setup(), and PHCASeeding::Setup().
void PHTrackSeeding::SetUseTruthClusters (bool setit) inline
Definition at line 43 of file PHTrackSeeding.h.
View newest version in sPHENIX GitHub at line 43 of file PHTrackSeeding.h
References _use_truth_clusters.
Member Data Documentation
TrkrClusterHitAssoc* PHTrackSeeding::_cluster_hit_map = nullptr protected
Definition at line 58 of file PHTrackSeeding.h.
View newest version in sPHENIX GitHub at line 58 of file PHTrackSeeding.h
Referenced by GetNodes().
TrkrClusterContainer* PHTrackSeeding::_cluster_map = nullptr protected
Definition at line 57 of file PHTrackSeeding.h.
View newest version in sPHENIX GitHub at line 57 of file PHTrackSeeding.h
Referenced by PHCASeeding::FillTree(), GetNodes(), PHSiliconTruthTrackSeeding::Process(), PHHybridSeeding::Process(), PHHybridSeeding::Setup(), and PHCASeeding::Setup().
TrkrHitSetContainer* PHTrackSeeding::_hitsets = nullptr protected
Definition at line 64 of file PHTrackSeeding.h.
View newest version in sPHENIX GitHub at line 64 of file PHTrackSeeding.h
Referenced by PHHybridSeeding::Process().
TrkrClusterIterationMapv1* PHTrackSeeding::_iteration_map protected
Definition at line 59 of file PHTrackSeeding.h.
View newest version in sPHENIX GitHub at line 59 of file PHTrackSeeding.h
Referenced by PHCASeeding::FillTree(), PHCASeeding::Process(), and process_event().
int PHTrackSeeding::_n_iteration protected
Definition at line 60 of file PHTrackSeeding.h.
View newest version in sPHENIX GitHub at line 60 of file PHTrackSeeding.h
Referenced by PHCASeeding::FillTree(), PHCASeeding::Process(), process_event(), and SetIteration().
TrackSeedContainer* PHTrackSeeding::_track_map = nullptr protected
Definition at line 63 of file PHTrackSeeding.h.
View newest version in sPHENIX GitHub at line 63 of file PHTrackSeeding.h
Referenced by CreateNodes(), PHTruthTrackSeeding::CreateNodes(), GetNodes(), PHSiliconTruthTrackSeeding::Process(), PHTruthTrackSeeding::Process(), PHHybridSeeding::publishSeeds(), and PHCASeeding::publishSeeds().
std::string PHTrackSeeding::_track_map_name = "TpcTrackSeedContainer" protected
Definition at line 66 of file PHTrackSeeding.h.
View newest version in sPHENIX GitHub at line 66 of file PHTrackSeeding.h
Referenced by CreateNodes(), GetNodes(), and set_track_map_name().
bool PHTrackSeeding::_use_truth_clusters = false protected
Definition at line 68 of file PHTrackSeeding.h.
View newest version in sPHENIX GitHub at line 68 of file PHTrackSeeding.h
Referenced by GetNodes(), and SetUseTruthClusters().
SvtxVertexMap* PHTrackSeeding::_vertex_map = nullptr protected
Definition at line 62 of file PHTrackSeeding.h.
View newest version in sPHENIX GitHub at line 62 of file PHTrackSeeding.h
Referenced by PHSiliconTruthTrackSeeding::Process(), PHHybridSeeding::Process(), and PHHybridSeeding::Setup().
bool PHTrackSeeding::do_hit_assoc = true protected
Definition at line 61 of file PHTrackSeeding.h.
View newest version in sPHENIX GitHub at line 61 of file PHTrackSeeding.h
Referenced by GetNodes(), and set_do_hit_association().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/trackreco/PHTrackSeeding.h
coresoftware/blob/master/offline/packages/trackreco/PHTrackSeeding.cc