Analysis Software: Matter Class Reference
Matter Class Reference
#include <JETSCAPE/blob/main/src/jet/Matter.h>
Public Member Functions
Matter ()
virtual ~Matter ()
void Init ()
void DoEnergyLoss (double deltaT, double time, double Q2, vector< Parton > &pIn, vector< Parton > &pOut)
void WriteTask (weak_ptr< JetScapeWriter > w)
void Dump_pIn_info (int i, vector< Parton > &pIn)
double generate_L (double form_time)
double sudakov_Pgg (double g0, double g1, double loc_c, double E)
double sud_val_GG (double h0, double h1, double h2, double loc_d, double E1)
double sud_z_GG (double cg, double cg1, double loc_e, double l_fac, double E2)
double P_z_gg_int (double cg, double cg1, double loc_e, double cg3, double l_fac, double E2)
double sudakov_Pqg (double g0, double g1, double loc_c, double E)
double sud_val_QG (double h0, double h1, double h2, double loc_d, double E1)
double sud_z_QG (double cg, double cg1, double loc_e, double l_fac, double E2)
double P_z_qg_int (double cg, double cg1, double loc_e, double cg3, double l_fac, double E2)
double sudakov_Pqg_w_M (double M, double g0, double g1, double loc_c, double E)
double sud_val_QG_w_M (double M, double h0, double h1, double h2, double loc_d, double E1)
double sud_z_QG_w_M (double M, double cg, double cg1, double loc_e, double l_fac, double E2)
double P_z_qg_int_w_M (double M, double cg, double cg1, double loc_e, double cg3, double l_fac, double E2)
double sudakov_Pqq (double q0, double q1, double loc_c, double E)
double sud_val_QQ (double h0, double h1, double h2, double loc_d, double E1)
double sud_z_QQ (double cg, double cg1, double loc_e, double l_fac, double E2)
double P_z_qq_int (double cg, double cg1, double loc_e, double cg3, double l_fac, double E2)
double P_z_qp_int (double cg, double cg1, double loc_e, double cg3, double l_fac, double E2)
double sud_z_QP (double cg, double cg1, double loc_e, double l_fac, double E2)
double sud_val_QP (double h0, double h1, double h2, double loc_d, double E1)
double sudakov_Pqp (double g0, double g1, double loc_c, double E)
double sudakov_Pqq_w_M_vac_only (double M, double q0, double q1, double loc_c, double E)
double sud_val_QQ_w_M_vac_only (double M, double h0, double h1, double h2, double loc_d, double E1)
double sud_z_QQ_w_M_vac_only (double M, double cg, double cg1, double loc_e, double l_fac, double E2)
double P_z_qq_int_w_M_vac_only (double M, double cg, double cg1, double loc_e, double cg3, double l_fac, double E2)
double generate_vac_t (int p_id, double nu, double t0, double t, double loc_a, int isp)
double generate_vac_t_w_M (int p_id, double M, double nu, double t0, double t, double loc_a, int is)
double generate_vac_z (int p_id, double t0, double t, double loc_b, double nu, int is)
double generate_vac_z_w_M (int p_id, double M, double t0, double t, double loc_b, double nu, int is)
double alpha_s (double q2)
double profile (double zeta)
double generate_angle ()
double generate_kt (double local_qhat, double dzeta)
double fillQhatTab (double y)
double fncQhat (double zeta)
double fncAvrQhat (double zeta, double tau)
double GeneralQhatFunction (int QhatParametrization, double Temperature, double EntropyDensity, double FixAlphas, double Qhat0, double E, double muSquare)
double RunningAlphaS (double muSquare)
double VirtualityQhatFunction (int QhatParametrization, double enerLoc, double muSquare)
double ModifiedProbability (int QhatParametrization, double tempLoc, double sdLoc, double enerLoc, double muSquare)
double IntegralPDF (double xB, double a, double b)
void flavor (int &CT, int &KATT0, int &KATT2, int &KATT3, unsigned int &max_color, unsigned int &color0, unsigned int &anti_color0, unsigned int &color2, unsigned int &anti_color2, unsigned int &color3, unsigned int &anti_color3)
void colljet22 (int CT, double temp, double qhat0ud, double v0[4], double p0[4], double p2[4], double p3[4], double p4[4], double &qt)
void trans (double v[4], double p[4])
void transback (double v[4], double p[4])
void rotate (double px, double py, double pz, double pr[4], int icc)
float ran0 (long *idum)
double solve_alphas (double var_qhat, double var_ener, double var_temp)
double fnc0_alphas (double var_alphas, double var_qhat, double var_ener, double var_temp)
double fnc0_derivative_alphas (double var_alphas, double var_qhat, double var_ener, double var_temp)
void read_tables ()
double Mgc2gc (double s, double t, double M)
double Mqc2qc (double s, double t, double M)
void collHQ22 (int CT, double temp, double qhat0ud, double v0[4], double p0[4], double p2[4], double p3[4], double p4[4], double &qt)
Public Member Functions inherited from Jetscape::JetEnergyLossModule< Matter >
virtual shared_ptr< JetEnergyLoss > Clone () const override
Deep copy constructor. The goal is to not have to initialize Modules multiple times.
void SetActive (bool m_active_exec)
Override deactivation.
Public Member Functions inherited from Jetscape::JetEnergyLoss
JetEnergyLoss ()
JetEnergyLoss (const JetEnergyLoss &j)
virtual ~JetEnergyLoss ()
virtual void Exec () final
virtual void Clear ()
void SetQhat (double m_qhat)
const double GetQhat () const
void AddShowerInitiatingParton (shared_ptr< Parton > p)
shared_ptr< Parton > GetShowerInitiatingParton ()
void PrintShowerInitiatingParton ()
double GetDeltaT ()
double GetMaxT ()
shared_ptr< PartonShower > GetShower ()
void SetJetSignalConnected (bool m_jetSignalConnected)
TODO: Remove.
const bool GetJetSignalConnected () const
void SetEdensitySignalConnected (bool m_edensitySignalConnected)
const bool GetEdensitySignalConnected () const
void SetGetHydroCellSignalConnected (bool m_GetHydroCellSignalConnected)
const bool GetGetHydroCellSignalConnected ()
void SetGetHydroTau0SignalConnected (bool m_GetHydroTau0SignalConnected)
const bool GetGetHydroTau0SignalConnected ()
void SetSentInPartonsConnected (bool m_SentInPartonsConnected)
const bool GetSentInPartonsConnected ()
void add_a_liquefier (std::shared_ptr< LiquefierBase > new_liquefier)
std::weak_ptr< LiquefierBase > get_liquefier ()
void SendFinalStatePartons (vector< vector< shared_ptr< Parton >>> &fPartons)
void GetFinalPartonsForEachShower (shared_ptr< PartonShower > shower)
Public Member Functions inherited from Jetscape::JetScapeModuleBase
JetScapeModuleBase ()
JetScapeModuleBase (string m_name)
virtual ~JetScapeModuleBase ()
void SetXMLMainFileName (string m_name)
string GetXMLMainFileName ()
void SetXMLUserFileName (string m_name)
string GetXMLUserFileName ()
shared_ptr< std::mt19937 > GetMt19937Generator ()
tinyxml2::XMLElement * GetXMLElement (std::initializer_list< const char * > path, bool isRequired=true)
std::string GetXMLElementText (std::initializer_list< const char * > path, bool isRequired=true)
int GetXMLElementInt (std::initializer_list< const char * > path, bool isRequired=true)
double GetXMLElementDouble (std::initializer_list< const char * > path, bool isRequired=true)
Public Member Functions inherited from Jetscape::JetScapeTask
JetScapeTask ()
virtual ~JetScapeTask ()
virtual void Finish ()
virtual void ExecuteTasks ()
virtual void ExecuteTask ()
virtual void InitTask ()
virtual void InitTasks ()
virtual void ClearTasks ()
virtual void ClearTask ()
virtual void FinishTask ()
virtual void FinishTasks ()
virtual void WriteTasks (weak_ptr< JetScapeWriter > w)
virtual void CollectHeader (weak_ptr< JetScapeWriter > w)
virtual void CollectHeaders (weak_ptr< JetScapeWriter > w)
virtual void Add (shared_ptr< JetScapeTask > m_tasks)
virtual const int GetMyTaskNumber () const
const vector< shared_ptr
< JetScapeTask > > GetTaskList () const
shared_ptr< JetScapeTask > GetTaskAt (int i)
void EraseTaskLast ()
void EraseTaskAt (int i)
void ResizeTaskList (int i)
void ClearTaskList ()
int GetNumberOfTasks ()
const bool GetActive () const
void SetActive (bool m_active_exec)
void SetId (string m_id)
const string GetId () const
const shared_ptr
< JetScapeModuleMutex > GetMutex () const
void SetMutex (shared_ptr< JetScapeModuleMutex > m_mutex)
Public Member Functions inherited from sigslot::has_slots< sigslot::multi_threaded_local >
has_slots ()
has_slots (const has_slots &hs)
void signal_connect (_signal_base< sigslot::multi_threaded_local > *sender)
void signal_disconnect (_signal_base< sigslot::multi_threaded_local > *sender)
virtual ~has_slots ()
void disconnect_all ()
Public Attributes
double qhat = 0.0
double ehat = 0.0
double e2hat = 0.0
double length = 0.0
unsigned int MaxColor = 0
bool matter_on
bool in_vac
bool brick_med
bool recoil_on
bool broadening_on
double hydro_Tc
double qhat0
double alphas
double brick_length
double vir_factor
double initR0
double initRx
double initRy
double initRz
double initVx
double initVy
double initVz
double initRdotV
double initVdotV
double initEner
double Q00
double Q0
double T0
double qhatTab1D [dimQhatTab] = {0.0}
double qhatTab2D [dimQhatTab][dimQhatTab] = {{0.0}}
double tStart
int iEvent
bool debug_flag = 0
long NUM1
double min_p1 = 0.0
double max_p1 = 1000.0
double bin_p1 = (max_p1 - min_p1) / N_p1
double min_T = 0.1
double max_T = 0.7
double bin_T = (max_T - min_T) / N_T
double min_e2 = 0.0
double max_e2 = 15.0
double bin_e2 = (max_e2 - min_e2) / N_e2
int QhatParametrizationType
double qhatA
double qhatB
double qhatC
double qhatD
Static Public Attributes
static const int dimQhatTab = 151
static const int N_p1 = 500
static const int N_T = 60
static const int N_e2 = 75
static double distFncB [N_T][N_p1][N_e2] = {{{0.0}}}
static double distFncF [N_T][N_p1][N_e2] = {{{0.0}}}
static double distMaxB [N_T][N_p1][N_e2] = {{{0.0}}}
static double distMaxF [N_T][N_p1][N_e2] = {{{0.0}}}
static double distFncBM [N_T][N_p1] = {{0.0}}
static double distFncFM [N_T][N_p1] = {{0.0}}
static double RHQ [60][20] = {{0.0}}
static double RHQ11 [60][20] = {{0.0}}
static double RHQ12 [60][20] = {{0.0}}
static double qhatHQ [60][20] = {{0.0}}
static bool flag_init = 0
Protected Attributes
uniform_real_distribution< double > ZeroOneDistribution
Private Attributes
double tscale
Static Private Attributes
static RegisterJetScapeModule
< Matter > reg
Additional Inherited Members
Static Public Member Functions inherited from Jetscape::JetScapeModuleBase
static int GetCurrentEvent ()
static void IncrementCurrentEvent ()
Protected Member Functions inherited from Jetscape::JetEnergyLossModule< Matter >
bool TakeResponsibilityFor (Parton &p)
Detailed Description
Definition at line 24 of file Matter.h.
View newest version in sPHENIX GitHub at line 24 of file Matter.h
Constructor & Destructor Documentation
Matter::Matter ()
Definition at line 54 of file Matter.cc.
View newest version in sPHENIX GitHub at line 54 of file Matter.cc
References alphas(), G4PLUGDOOR::length, SetId(), and VERBOSE.
Matter::~Matter () virtual
Definition at line 95 of file Matter.cc.
View newest version in sPHENIX GitHub at line 95 of file Matter.cc
References VERBOSE.
Member Function Documentation
double Matter::alpha_s (double q2)
Definition at line 3699 of file Matter.cc.
View newest version in sPHENIX GitHub at line 3699 of file Matter.cc
References KFPMath::a, JSWARN, Jetscape::Lambda_QCD, Jetscape::Nc, Jetscape::nf, and Jetscape::pi.
void Matter::collHQ22 (int CT, double temp, double qhat0ud, double v0[4], double p0[4], double p2[4], double p3[4], double p4[4], double & qt)
Definition at line 4778 of file Matter.cc.
View newest version in sPHENIX GitHub at line 4778 of file Matter.cc
References Acts::UnitConstants::e, generate_files_AA::ff, and Jetscape::pi.
void Matter::colljet22 (int CT, double temp, double qhat0ud, double v0[4], double p0[4], double p2[4], double p3[4], double p4[4], double & qt)
Definition at line 4411 of file Matter.cc.
View newest version in sPHENIX GitHub at line 4411 of file Matter.cc
References std::tr1::f1, std::tr1::f2, generate_files_AA::ff, and Jetscape::pi.
void Matter::DoEnergyLoss (double deltaT, double time, double Q2, vector< Parton > & pIn, vector< Parton > & pOut) virtual
Default function to perform the energy loss for partons at time "time". It should be overridden by different energy loss tasks.
Parameters
deltaT Step-size.
time Current time.
Q2 Current virtuality of the parton.
pIn Vector of current partons.
pOut Vector of partons at time "time+deltaT".
length in GeV-1 will have to changed for hydro
A parton without a virtuality or formation time, must set...
a really large formation time.
STILL a really large formation time.
< gluon splits into two gluons
< (anti-)quark splits into (anti-)quark + gluon, covers both light and heavy quarks (anti-quarks)
< the transverse momentum squared
< the transverse momentum squared
< the transverse momentum squared
< test if negative
< the momentum transverse to the parent parton direction
Reimplemented from Jetscape::JetEnergyLoss.
Definition at line 201 of file Matter.cc.
View newest version in sPHENIX GitHub at line 201 of file Matter.cc
References alphas(), Jetscape::approx, Jetscape::bid, BOLDBLUE, BOLDRED, BOLDYELLOW, Jetscape::Ca, Jetscape::Cf, Jetscape::cid, color, Jetscape::did, Acts::UnitConstants::e, energy, Jetscape::FluidCellInfo::entropy_density, Jetscape::fmToGeVinv, Jetscape::gid, i, j, JSDEBUG, JSINFO, JSWARN, k, Jetscape::Lambda_QCD, G4PLUGDOOR::length, MAGENTA, Jetscape::nf, merge_hashes::p, Jetscape::photonid, Jetscape::pi, train_ambiguity_solver::pid, PythiaFunction(), QS, physmon_track_finding_ttbar::r, r2, Acts::UnitConstants::rad, Jetscape::rounding_error, Jetscape::sid, sign(), t, Jetscape::FluidCellInfo::temperature, Acts::Test::time, Jetscape::uid, VERBOSE, vx, Jetscape::FluidCellInfo::vx, vy, Jetscape::FluidCellInfo::vy, vz, Jetscape::FluidCellInfo::vz, ambiguity_solver_full_chain::x, y, physmon_track_finding_ttbar::z, and Jetscape::zeta3.
void Matter::Dump_pIn_info (int i, vector< Parton > & pIn)
Definition at line 191 of file Matter.cc.
View newest version in sPHENIX GitHub at line 191 of file Matter.cc
References i, and JSWARN.
double Matter::fillQhatTab (double y)
Definition at line 3738 of file Matter.cc.
View newest version in sPHENIX GitHub at line 3738 of file Matter.cc
References alphas(), Jetscape::FluidCellInfo::entropy_density, i, j, JSWARN, MAGENTA, Jetscape::FluidCellInfo::temperature, VERBOSE, Jetscape::FluidCellInfo::vx, Jetscape::FluidCellInfo::vy, and Jetscape::FluidCellInfo::vz.
void Matter::flavor (int & CT, int & KATT0, int & KATT2, int & KATT3, unsigned int & max_color, unsigned int & color0, unsigned int & anti_color0, unsigned int & color2, unsigned int & anti_color2, unsigned int & color3, unsigned int & anti_color3)
Definition at line 4147 of file Matter.cc.
View newest version in sPHENIX GitHub at line 4147 of file Matter.cc
References KFPMath::a, KFPMath::b, R0, R1, R2, R3, and R4.
double Matter::fnc0_alphas (double var_alphas, double var_qhat, double var_ener, double var_temp)
Definition at line 5214 of file Matter.cc.
View newest version in sPHENIX GitHub at line 5214 of file Matter.cc
References Jetscape::Ca, Jetscape::pi, and Jetscape::zeta3.
double Matter::fnc0_derivative_alphas (double var_alphas, double var_qhat, double var_ener, double var_temp)
Definition at line 5224 of file Matter.cc.
View newest version in sPHENIX GitHub at line 5224 of file Matter.cc
References Jetscape::Ca, Jetscape::pi, and Jetscape::zeta3.
double Matter::fncAvrQhat (double zeta, double tau)
Definition at line 4122 of file Matter.cc.
View newest version in sPHENIX GitHub at line 4122 of file Matter.cc
double Matter::fncQhat (double zeta)
Definition at line 4102 of file Matter.cc.
View newest version in sPHENIX GitHub at line 4102 of file Matter.cc
double Matter::GeneralQhatFunction (int QhatParametrization, double Temperature, double EntropyDensity, double FixAlphas, double Qhat0, double E, double muSquare)
Definition at line 3874 of file Matter.cc.
View newest version in sPHENIX GitHub at line 3874 of file Matter.cc
References Jetscape::Ca, JSINFO, and Jetscape::pi.
double Matter::generate_angle ()
Definition at line 1852 of file Matter.cc.
View newest version in sPHENIX GitHub at line 1852 of file Matter.cc
References Jetscape::pi, and physmon_track_finding_ttbar::r.
double Matter::generate_kt (double local_qhat, double dzeta)
Definition at line 1838 of file Matter.cc.
View newest version in sPHENIX GitHub at line 1838 of file Matter.cc
References physmon_track_finding_ttbar::r, width, and ambiguity_solver_full_chain::x.
double Matter::generate_L (double form_time)
Definition at line 2402 of file Matter.cc.
View newest version in sPHENIX GitHub at line 2402 of file Matter.cc
References Jetscape::approx, Jetscape::error, norm, Jetscape::pi, physmon_track_finding_ttbar::r, and ambiguity_solver_full_chain::x.
double Matter::generate_vac_t (int p_id, double nu, double t0, double t, double loc_a, int isp)
Definition at line 1867 of file Matter.cc.
View newest version in sPHENIX GitHub at line 1867 of file Matter.cc
References Jetscape::gid, Jetscape::nf, physmon_track_finding_ttbar::r, Jetscape::s_approx, Jetscape::s_error, t, train_ambiguity_solver::test, and physmon_track_finding_ttbar::z.
double Matter::generate_vac_t_w_M (int p_id, double M, double nu, double t0, double t, double loc_a, int is)
Definition at line 1979 of file Matter.cc.
View newest version in sPHENIX GitHub at line 1979 of file Matter.cc
References Jetscape::bid, BOLDYELLOW, Jetscape::cid, Jetscape::gid, MAGENTA, PythiaFunction(), physmon_track_finding_ttbar::r, Jetscape::s_approx, Jetscape::s_error, t, train_ambiguity_solver::test, VERBOSE, and physmon_track_finding_ttbar::z.
double Matter::generate_vac_z (int p_id, double t0, double t, double loc_b, double nu, int is)
Definition at line 2154 of file Matter.cc.
View newest version in sPHENIX GitHub at line 2154 of file Matter.cc
References Jetscape::approx, double(), Acts::UnitConstants::e, Jetscape::gid, physmon_track_finding_ttbar::r, Jetscape::s_error, t, train_ambiguity_solver::test, and physmon_track_finding_ttbar::z.
double Matter::generate_vac_z_w_M (int p_id, double M, double t0, double t, double loc_b, double nu, int is)
Definition at line 2245 of file Matter.cc.
View newest version in sPHENIX GitHub at line 2245 of file Matter.cc
References Jetscape::approx, Jetscape::bid, Jetscape::cid, Jetscape::did, double(), Acts::UnitConstants::e, Jetscape::gid, physmon_track_finding_ttbar::r, Jetscape::s_error, Jetscape::sid, t, train_ambiguity_solver::test, Jetscape::uid, and physmon_track_finding_ttbar::z.
void Matter::Init () virtual
It reads the input parameters from a XML file under the tag <Eloss>. Sets the Parton class inP and PartonShower class pShower to null. Also initializes the tasks attached to the JetEnergyLoss module.
Reimplemented from Jetscape::JetEnergyLoss.
Definition at line 97 of file Matter.cc.
View newest version in sPHENIX GitHub at line 97 of file Matter.cc
References alphas(), JSINFO, MAGENTA, and Acts::Test::time.
double Matter::IntegralPDF (double xB, double a, double b)
Definition at line 4082 of file Matter.cc.
View newest version in sPHENIX GitHub at line 4082 of file Matter.cc
References i, N, and TauVsDIS_MachineLearning_Differentiation::X.
double Matter::Mgc2gc (double s, double t, double M)
Definition at line 5021 of file Matter.cc.
View newest version in sPHENIX GitHub at line 5021 of file Matter.cc
References t, and physmon_ckf_tracking::u.
double Matter::ModifiedProbability (int QhatParametrization, double tempLoc, double sdLoc, double enerLoc, double muSquare)
Definition at line 4021 of file Matter.cc.
View newest version in sPHENIX GitHub at line 4021 of file Matter.cc
References alphas(), and JSINFO.
double Matter::Mqc2qc (double s, double t, double M)
Definition at line 5009 of file Matter.cc.
View newest version in sPHENIX GitHub at line 5009 of file Matter.cc
References t, and physmon_ckf_tracking::u.
double Matter::P_z_gg_int (double cg, double cg1, double loc_e, double cg3, double l_fac, double E2)
Definition at line 2600 of file Matter.cc.
View newest version in sPHENIX GitHub at line 2600 of file Matter.cc
References G4PLUGDOOR::length, Jetscape::rounding_error, ambiguity_solver_full_chain::t3, ambiguity_solver_full_chain::t4, and tau.
double Matter::P_z_qg_int (double cg, double cg1, double loc_e, double cg3, double l_fac, double E2)
Definition at line 3541 of file Matter.cc.
View newest version in sPHENIX GitHub at line 3541 of file Matter.cc
References G4PLUGDOOR::length, Jetscape::rounding_error, ambiguity_solver_full_chain::t2, and tau.
double Matter::P_z_qg_int_w_M (double M, double cg, double cg1, double loc_e, double cg3, double l_fac, double E2)
Definition at line 3583 of file Matter.cc.
View newest version in sPHENIX GitHub at line 3583 of file Matter.cc
References std::tr1::f1, std::tr1::f2, std::tr1::f3, std::tr1::f4, std::tr1::f6, std::tr1::f7, std::tr1::f8, std::tr1::f9, G4PLUGDOOR::length, Jetscape::rounding_error, ambiguity_solver_full_chain::t2, and tau.
double Matter::P_z_qp_int (double cg, double cg1, double loc_e, double cg3, double l_fac, double E2)
Definition at line 3147 of file Matter.cc.
View newest version in sPHENIX GitHub at line 3147 of file Matter.cc
References G4PLUGDOOR::length, Jetscape::rounding_error, ambiguity_solver_full_chain::t2, and tau.
double Matter::P_z_qq_int (double cg, double cg1, double loc_e, double cg3, double l_fac, double E2)
Definition at line 2921 of file Matter.cc.
View newest version in sPHENIX GitHub at line 2921 of file Matter.cc
References Jetscape::Ca, Jetscape::Cf, G4PLUGDOOR::length, Jetscape::rounding_error, tau, and Jetscape::Tf.
double Matter::P_z_qq_int_w_M_vac_only (double M, double cg, double cg1, double loc_e, double cg3, double l_fac, double E2)
Definition at line 3037 of file Matter.cc.
View newest version in sPHENIX GitHub at line 3037 of file Matter.cc
References Jetscape::Ca, Jetscape::Cf, G4PLUGDOOR::length, Jetscape::rounding_error, tau, and Jetscape::Tf.
double Matter::profile (double zeta)
Definition at line 3726 of file Matter.cc.
View newest version in sPHENIX GitHub at line 3726 of file Matter.cc
float Matter::ran0 (long * idum)
Definition at line 5113 of file Matter.cc.
View newest version in sPHENIX GitHub at line 5113 of file Matter.cc
References j, and k.
void Matter::read_tables ()
Definition at line 5235 of file Matter.cc.
View newest version in sPHENIX GitHub at line 5235 of file Matter.cc
References i, it, j, k, and n.
void Matter::rotate (double px, double py, double pz, double pr[4], int icc)
Definition at line 5061 of file Matter.cc.
View newest version in sPHENIX GitHub at line 5061 of file Matter.cc
References E, and physmon_track_finding_ttbar::pt.
double Matter::RunningAlphaS (double muSquare)
Definition at line 3935 of file Matter.cc.
View newest version in sPHENIX GitHub at line 3935 of file Matter.cc
References alphas(), Jetscape::pi, and VERBOSE.
double Matter::solve_alphas (double var_qhat, double var_ener, double var_temp)
Definition at line 5174 of file Matter.cc.
View newest version in sPHENIX GitHub at line 5174 of file Matter.cc
References Jetscape::Ca, JSINFO, Jetscape::pi, and Jetscape::zeta3.
double Matter::sud_val_GG (double h0, double h1, double h2, double loc_d, double E1)
Definition at line 2478 of file Matter.cc.
View newest version in sPHENIX GitHub at line 2478 of file Matter.cc
References Jetscape::approx, Jetscape::error, h, h1, and h2.
double Matter::sud_val_QG (double h0, double h1, double h2, double loc_d, double E1)
Definition at line 3232 of file Matter.cc.
View newest version in sPHENIX GitHub at line 3232 of file Matter.cc
References Jetscape::approx, Jetscape::error, h, h1, and h2.
double Matter::sud_val_QG_w_M (double M, double h0, double h1, double h2, double loc_d, double E1)
Definition at line 3270 of file Matter.cc.
View newest version in sPHENIX GitHub at line 3270 of file Matter.cc
References Jetscape::approx, Jetscape::error, h, h1, and h2.
double Matter::sud_val_QP (double h0, double h1, double h2, double loc_d, double E1)
Definition at line 2997 of file Matter.cc.
View newest version in sPHENIX GitHub at line 2997 of file Matter.cc
References Jetscape::approx, Jetscape::error, h, h1, and h2.
double Matter::sud_val_QQ (double h0, double h1, double h2, double loc_d, double E1)
Definition at line 2708 of file Matter.cc.
View newest version in sPHENIX GitHub at line 2708 of file Matter.cc
References Jetscape::approx, Jetscape::error, h, h1, and h2.
double Matter::sud_val_QQ_w_M_vac_only (double M, double h0, double h1, double h2, double loc_d, double E1)
Definition at line 2748 of file Matter.cc.
View newest version in sPHENIX GitHub at line 2748 of file Matter.cc
References Jetscape::approx, Jetscape::error, h, h1, and h2.
double Matter::sud_z_GG (double cg, double cg1, double loc_e, double l_fac, double E2)
Definition at line 2520 of file Matter.cc.
View newest version in sPHENIX GitHub at line 2520 of file Matter.cc
References Jetscape::E_minimum, G4PLUGDOOR::length, Jetscape::rounding_error, ambiguity_solver_full_chain::t2, ambiguity_solver_full_chain::t3, and tau.
double Matter::sud_z_QG (double cg, double cg1, double loc_e, double l_fac, double E2)
Definition at line 3314 of file Matter.cc.
View newest version in sPHENIX GitHub at line 3314 of file Matter.cc
References Jetscape::E_minimum, G4PLUGDOOR::length, Jetscape::rounding_error, ambiguity_solver_full_chain::t2, and tau.
double Matter::sud_z_QG_w_M (double M, double cg, double cg1, double loc_e, double l_fac, double E2)
Definition at line 3381 of file Matter.cc.
View newest version in sPHENIX GitHub at line 3381 of file Matter.cc
References Jetscape::E_minimum, std::tr1::f1, std::tr1::f2, std::tr1::f3, std::tr1::f4, std::tr1::f5, std::tr1::f8, std::tr1::f9, JSINFO, G4PLUGDOOR::length, MAGENTA, Jetscape::rounding_error, ambiguity_solver_full_chain::t1, ambiguity_solver_full_chain::t2, ambiguity_solver_full_chain::t4, and tau.
double Matter::sud_z_QP (double cg, double cg1, double loc_e, double l_fac, double E2)
Definition at line 3091 of file Matter.cc.
View newest version in sPHENIX GitHub at line 3091 of file Matter.cc
References Jetscape::Ca, Jetscape::Cf, Jetscape::E_minimum, G4PLUGDOOR::length, Jetscape::rounding_error, ambiguity_solver_full_chain::t2, and tau.
double Matter::sud_z_QQ (double cg, double cg1, double loc_e, double l_fac, double E2)
Definition at line 2791 of file Matter.cc.
View newest version in sPHENIX GitHub at line 2791 of file Matter.cc
References Jetscape::E_minimum, G4PLUGDOOR::length, Jetscape::rounding_error, ambiguity_solver_full_chain::t2, ambiguity_solver_full_chain::t4, and tau.
double Matter::sud_z_QQ_w_M_vac_only (double M, double cg, double cg1, double loc_e, double l_fac, double E2)
Definition at line 2856 of file Matter.cc.
View newest version in sPHENIX GitHub at line 2856 of file Matter.cc
References Jetscape::E_minimum, G4PLUGDOOR::length, Jetscape::rounding_error, ambiguity_solver_full_chain::t1, ambiguity_solver_full_chain::t2, ambiguity_solver_full_chain::t3, and tau.
double Matter::sudakov_Pgg (double g0, double g1, double loc_c, double E)
Definition at line 2453 of file Matter.cc.
View newest version in sPHENIX GitHub at line 2453 of file Matter.cc
References Jetscape::Ca, Acts::UnitConstants::g, and Jetscape::pi.
double Matter::sudakov_Pqg (double g0, double g1, double loc_c, double E)
Definition at line 3189 of file Matter.cc.
View newest version in sPHENIX GitHub at line 3189 of file Matter.cc
References Jetscape::Cf, Acts::UnitConstants::g, JSWARN, and Jetscape::pi.
double Matter::sudakov_Pqg_w_M (double M, double g0, double g1, double loc_c, double E)
Definition at line 3208 of file Matter.cc.
View newest version in sPHENIX GitHub at line 3208 of file Matter.cc
References Jetscape::Cf, Acts::UnitConstants::g, JSWARN, and Jetscape::pi.
double Matter::sudakov_Pqp (double g0, double g1, double loc_c, double E)
Definition at line 2976 of file Matter.cc.
View newest version in sPHENIX GitHub at line 2976 of file Matter.cc
References Acts::UnitConstants::g, JSWARN, and Jetscape::pi.
double Matter::sudakov_Pqq (double q0, double q1, double loc_c, double E)
Definition at line 2667 of file Matter.cc.
View newest version in sPHENIX GitHub at line 2667 of file Matter.cc
References JSWARN, Jetscape::pi, and Jetscape::Tf.
double Matter::sudakov_Pqq_w_M_vac_only (double M, double q0, double q1, double loc_c, double E)
Definition at line 2689 of file Matter.cc.
View newest version in sPHENIX GitHub at line 2689 of file Matter.cc
References JSWARN, Jetscape::pi, and Jetscape::Tf.
void Matter::trans (double v[4], double p[4])
Definition at line 5039 of file Matter.cc.
View newest version in sPHENIX GitHub at line 5039 of file Matter.cc
void Matter::transback (double v[4], double p[4])
Definition at line 5050 of file Matter.cc.
View newest version in sPHENIX GitHub at line 5050 of file Matter.cc
double Matter::VirtualityQhatFunction (int QhatParametrization, double enerLoc, double muSquare)
Definition at line 3947 of file Matter.cc.
View newest version in sPHENIX GitHub at line 3947 of file Matter.cc
References JSINFO.
void Matter::WriteTask (weak_ptr< JetScapeWriter > w) virtual
Write output information for each tasks/subtasks attached to the JetEnergyLoss module using JetScapeWriter functionality.
Parameters
w A pointer of type JetScapeWriter.
Reimplemented from Jetscape::JetEnergyLoss.
Definition at line 182 of file Matter.cc.
View newest version in sPHENIX GitHub at line 182 of file Matter.cc
References f, and VERBOSE.
Member Data Documentation
double Matter::alphas
Definition at line 107 of file Matter.h.
View newest version in sPHENIX GitHub at line 107 of file Matter.h
double Matter::bin_e2 = (max_e2 - min_e2) / N_e2
Definition at line 136 of file Matter.h.
View newest version in sPHENIX GitHub at line 136 of file Matter.h
double Matter::bin_p1 = (max_p1 - min_p1) / N_p1
Definition at line 130 of file Matter.h.
View newest version in sPHENIX GitHub at line 130 of file Matter.h
double Matter::bin_T = (max_T - min_T) / N_T
Definition at line 133 of file Matter.h.
View newest version in sPHENIX GitHub at line 133 of file Matter.h
double Matter::brick_length
Definition at line 107 of file Matter.h.
View newest version in sPHENIX GitHub at line 107 of file Matter.h
bool Matter::brick_med
Definition at line 106 of file Matter.h.
View newest version in sPHENIX GitHub at line 106 of file Matter.h
bool Matter::broadening_on
Definition at line 106 of file Matter.h.
View newest version in sPHENIX GitHub at line 106 of file Matter.h
bool Matter::debug_flag = 0
Definition at line 118 of file Matter.h.
View newest version in sPHENIX GitHub at line 118 of file Matter.h
const int Matter::dimQhatTab = 151 static
Definition at line 112 of file Matter.h.
View newest version in sPHENIX GitHub at line 112 of file Matter.h
double Matter::distFncB = {{{0.0}}} static
Definition at line 125 of file Matter.h.
View newest version in sPHENIX GitHub at line 125 of file Matter.h
double Matter::distFncBM = {{0.0}} static
Definition at line 127 of file Matter.h.
View newest version in sPHENIX GitHub at line 127 of file Matter.h
double Matter::distFncF = {{{0.0}}} static
Definition at line 125 of file Matter.h.
View newest version in sPHENIX GitHub at line 125 of file Matter.h
double Matter::distFncFM = {{0.0}} static
Definition at line 127 of file Matter.h.
View newest version in sPHENIX GitHub at line 127 of file Matter.h
double Matter::distMaxB = {{{0.0}}} static
Definition at line 125 of file Matter.h.
View newest version in sPHENIX GitHub at line 125 of file Matter.h
double Matter::distMaxF = {{{0.0}}} static
Definition at line 125 of file Matter.h.
View newest version in sPHENIX GitHub at line 125 of file Matter.h
double Matter::e2hat = 0.0
Definition at line 96 of file Matter.h.
View newest version in sPHENIX GitHub at line 96 of file Matter.h
double Matter::ehat = 0.0
Definition at line 95 of file Matter.h.
View newest version in sPHENIX GitHub at line 95 of file Matter.h
bool Matter::flag_init = 0 static
Definition at line 144 of file Matter.h.
View newest version in sPHENIX GitHub at line 144 of file Matter.h
double Matter::hydro_Tc
Definition at line 107 of file Matter.h.
View newest version in sPHENIX GitHub at line 107 of file Matter.h
int Matter::iEvent
Definition at line 117 of file Matter.h.
View newest version in sPHENIX GitHub at line 117 of file Matter.h
bool Matter::in_vac
Definition at line 106 of file Matter.h.
View newest version in sPHENIX GitHub at line 106 of file Matter.h
double Matter::initEner
Definition at line 108 of file Matter.h.
View newest version in sPHENIX GitHub at line 108 of file Matter.h
double Matter::initR0
Definition at line 108 of file Matter.h.
View newest version in sPHENIX GitHub at line 108 of file Matter.h
double Matter::initRdotV
Definition at line 108 of file Matter.h.
View newest version in sPHENIX GitHub at line 108 of file Matter.h
double Matter::initRx
Definition at line 108 of file Matter.h.
View newest version in sPHENIX GitHub at line 108 of file Matter.h
double Matter::initRy
Definition at line 108 of file Matter.h.
View newest version in sPHENIX GitHub at line 108 of file Matter.h
double Matter::initRz
Definition at line 108 of file Matter.h.
View newest version in sPHENIX GitHub at line 108 of file Matter.h
double Matter::initVdotV
Definition at line 108 of file Matter.h.
View newest version in sPHENIX GitHub at line 108 of file Matter.h
double Matter::initVx
Definition at line 108 of file Matter.h.
View newest version in sPHENIX GitHub at line 108 of file Matter.h
double Matter::initVy
Definition at line 108 of file Matter.h.
View newest version in sPHENIX GitHub at line 108 of file Matter.h
double Matter::initVz
Definition at line 108 of file Matter.h.
View newest version in sPHENIX GitHub at line 108 of file Matter.h
double Matter::length = 0.0
Definition at line 97 of file Matter.h.
View newest version in sPHENIX GitHub at line 97 of file Matter.h
bool Matter::matter_on
Definition at line 106 of file Matter.h.
View newest version in sPHENIX GitHub at line 106 of file Matter.h
double Matter::max_e2 = 15.0
Definition at line 135 of file Matter.h.
View newest version in sPHENIX GitHub at line 135 of file Matter.h
double Matter::max_p1 = 1000.0
Definition at line 129 of file Matter.h.
View newest version in sPHENIX GitHub at line 129 of file Matter.h
double Matter::max_T = 0.7
Definition at line 132 of file Matter.h.
View newest version in sPHENIX GitHub at line 132 of file Matter.h
unsigned int Matter::MaxColor = 0
Definition at line 99 of file Matter.h.
View newest version in sPHENIX GitHub at line 99 of file Matter.h
double Matter::min_e2 = 0.0
Definition at line 134 of file Matter.h.
View newest version in sPHENIX GitHub at line 134 of file Matter.h
double Matter::min_p1 = 0.0
Definition at line 128 of file Matter.h.
View newest version in sPHENIX GitHub at line 128 of file Matter.h
double Matter::min_T = 0.1
Definition at line 131 of file Matter.h.
View newest version in sPHENIX GitHub at line 131 of file Matter.h
const int Matter::N_e2 = 75 static
Definition at line 124 of file Matter.h.
View newest version in sPHENIX GitHub at line 124 of file Matter.h
const int Matter::N_p1 = 500 static
Definition at line 122 of file Matter.h.
View newest version in sPHENIX GitHub at line 122 of file Matter.h
const int Matter::N_T = 60 static
Definition at line 123 of file Matter.h.
View newest version in sPHENIX GitHub at line 123 of file Matter.h
long Matter::NUM1
Definition at line 119 of file Matter.h.
View newest version in sPHENIX GitHub at line 119 of file Matter.h
double Matter::Q0
Definition at line 110 of file Matter.h.
View newest version in sPHENIX GitHub at line 110 of file Matter.h
double Matter::Q00
Definition at line 110 of file Matter.h.
View newest version in sPHENIX GitHub at line 110 of file Matter.h
double Matter::qhat = 0.0
Definition at line 94 of file Matter.h.
View newest version in sPHENIX GitHub at line 94 of file Matter.h
double Matter::qhat0
Definition at line 107 of file Matter.h.
View newest version in sPHENIX GitHub at line 107 of file Matter.h
double Matter::qhatA
Definition at line 154 of file Matter.h.
View newest version in sPHENIX GitHub at line 154 of file Matter.h
double Matter::qhatB
Definition at line 154 of file Matter.h.
View newest version in sPHENIX GitHub at line 154 of file Matter.h
double Matter::qhatC
Definition at line 154 of file Matter.h.
View newest version in sPHENIX GitHub at line 154 of file Matter.h
double Matter::qhatD
Definition at line 154 of file Matter.h.
View newest version in sPHENIX GitHub at line 154 of file Matter.h
double Matter::qhatHQ = {{0.0}} static
Definition at line 141 of file Matter.h.
View newest version in sPHENIX GitHub at line 141 of file Matter.h
int Matter::QhatParametrizationType
Definition at line 148 of file Matter.h.
View newest version in sPHENIX GitHub at line 148 of file Matter.h
double Matter::qhatTab1D[dimQhatTab] = {0.0}
Definition at line 113 of file Matter.h.
View newest version in sPHENIX GitHub at line 113 of file Matter.h
double Matter::qhatTab2D[dimQhatTab][dimQhatTab] = {{0.0}}
Definition at line 114 of file Matter.h.
View newest version in sPHENIX GitHub at line 114 of file Matter.h
bool Matter::recoil_on
Definition at line 106 of file Matter.h.
View newest version in sPHENIX GitHub at line 106 of file Matter.h
RegisterJetScapeModule< Matter > Matter::reg static private
Definition at line 186 of file Matter.h.
View newest version in sPHENIX GitHub at line 186 of file Matter.h
double Matter::RHQ = {{0.0}} static
Definition at line 138 of file Matter.h.
View newest version in sPHENIX GitHub at line 138 of file Matter.h
double Matter::RHQ11 = {{0.0}} static
Definition at line 139 of file Matter.h.
View newest version in sPHENIX GitHub at line 139 of file Matter.h
double Matter::RHQ12 = {{0.0}} static
Definition at line 140 of file Matter.h.
View newest version in sPHENIX GitHub at line 140 of file Matter.h
double Matter::T0
Definition at line 110 of file Matter.h.
View newest version in sPHENIX GitHub at line 110 of file Matter.h
double Matter::tscale private
Definition at line 187 of file Matter.h.
View newest version in sPHENIX GitHub at line 187 of file Matter.h
double Matter::tStart
Definition at line 116 of file Matter.h.
View newest version in sPHENIX GitHub at line 116 of file Matter.h
double Matter::vir_factor
Definition at line 107 of file Matter.h.
View newest version in sPHENIX GitHub at line 107 of file Matter.h
uniform_real_distribution<double> Matter::ZeroOneDistribution protected
Definition at line 182 of file Matter.h.
View newest version in sPHENIX GitHub at line 182 of file Matter.h
The documentation for this class was generated from the following files:
JETSCAPE/blob/main/src/jet/Matter.h
JETSCAPE/blob/main/src/jet/Matter.cc