Analysis Software: acts/blob/sPHENIX/Examples/Run/Reconstruction/Common/MeasurementsToSpacepoints.cpp File Reference
MeasurementsToSpacepoints.cpp File Reference
#include "Acts/Definitions/Units.hpp"
#include "ActsExamples/Detector/IBaseDetector.hpp"
#include "ActsExamples/Framework/RandomNumbers.hpp"
#include "ActsExamples/Framework/Sequencer.hpp"
#include "ActsExamples/Geometry/CommonGeometry.hpp"
#include "ActsExamples/Io/Csv/CsvParticleReader.hpp"
#include "ActsExamples/Io/Csv/CsvSimHitReader.hpp"
#include "ActsExamples/Io/Csv/CsvSpacepointWriter.hpp"
#include "ActsExamples/Io/Json/JsonDigitizationConfig.hpp"
#include "ActsExamples/Options/CommonOptions.hpp"
#include "ActsExamples/Options/CsvOptionsReader.hpp"
#include "ActsExamples/Options/MagneticFieldOptions.hpp"
#include "ActsExamples/Reconstruction/ReconstructionBase.hpp"
#include "ActsExamples/TrackFinding/SpacePointMaker.hpp"
#include "ActsExamples/TruthTracking/TruthSeedSelector.hpp"
#include "ActsExamples/Utilities/Options.hpp"
#include "ActsExamples/Utilities/Paths.hpp"
#include <Acts/Utilities/Logger.hpp>
#include <iostream>
#include <boost/program_options.hpp>
Functions
const Acts::Logger & logger ()
int runMeasurementsToSP (int argc, char *argv[], const std::shared_ptr< ActsExamples::IBaseDetector > &detector)
Variables
static std::unique_ptr< const
Acts::Logger > m_logger
Function Documentation
const Acts::Logger& logger ()
Definition at line 36 of file MeasurementsToSpacepoints.cpp.
View newest version in sPHENIX GitHub at line 36 of file MeasurementsToSpacepoints.cpp
References m_logger.
Referenced by Acts::addCylinderLayerProtoMaterial(), Acts::addDiscLayerProtoMaterial(), Acts::Python::addLogging(), BOOST_AUTO_TEST_CASE(), Acts::DD4hepLayerBuilder::centralLayers(), Acts::TrackingVolume::compatibleBoundaries(), Acts::Experimental::CylindricalContainerBuilder::construct(), ActsExamples::Geant4::Geant4Detector::constructDetector(), ActsExamples::Geant4::Geant4Detector::constructTrackingGeometry(), Acts::DD4hepLayerBuilder::endcapLayers(), ActsExamples::TrackFindingAlgorithmExaTrkX::execute(), ActsExamples::IterativeVertexFinderAlgorithm::execute(), ActsExamples::VertexFitterAlgorithm::execute(), ActsExamples::TrackParamsEstimationAlgorithm::execute(), ActsExamples::AdaptiveMultiVertexFinderAlgorithm::executeAfterSeederChoice(), PHActsVertexFinder::findVertices(), PHActsInitialVertexFinder::findVertices(), PHActsVertexFitter::fitVertex(), Acts::getDummyLogger(), PHCosmicsTrkFitter::loopTracks(), PHActsTrkFitter::loopTracks(), ActsPropagator::makeFastPropagator(), ActsPropagator::makePropagator(), Acts::TorchTruthGraphMetricsHook::operator()(), Acts::GainMatrixSmoother::operator()(), Acts::MultiStepperSurfaceReached::operator()(), Acts::GainMatrixUpdater::operator()(), Acts::SurfaceReached::operator()(), PHActsGSF::process_event(), Acts::Propagator< stepper_t, navigator_t >::propagate(), Acts::Propagator< stepper_t, navigator_t >::propagate_impl(), PYBIND11_MODULE(), ActsExamples::RootBFieldWriter::run(), Acts::MeasurementSelector::select(), Acts::MultiEigenStepperLoop< extensionlist_t, component_reducer_t, auctioneer_t >::step(), Acts::EventDataView3DTest::testMultiTrajectory(), testTruthTestGraph(), Acts::TrackingGeometryBuilder::trackingGeometry(), Acts::detail::updateSingleSurfaceStatus(), Acts::Test::PropagatorState::Stepper::updateSurfaceStatus(), Acts::StraightLineStepper::updateSurfaceStatus(), Acts::EigenStepper< extensionlist_t, auctioneer_t >::updateSurfaceStatus(), Acts::AtlasStepper::updateSurfaceStatus(), Acts::MultiEigenStepperLoop< extensionlist_t, component_reducer_t, auctioneer_t >::updateSurfaceStatus(), Acts::volumeBuilder_dd4hep(), ActsExamples::RootTrackParameterWriter::writeT(), ActsExamples::RootTrajectoryStatesWriter::writeT(), and ActsExamples::RootMeasurementWriter::writeT().
int runMeasurementsToSP (int argc, char * argv[], const std::shared_ptr< ActsExamples::IBaseDetector > & detector)
Definition at line 39 of file MeasurementsToSpacepoints.cpp.
View newest version in sPHENIX GitHub at line 39 of file MeasurementsToSpacepoints.cpp
References ACTS_INFO, ActsExamples::Sequencer::addAlgorithm(), ActsExamples::Sequencer::addContextDecorator(), ActsExamples::Options::addGeometryOptions(), ActsExamples::Options::addInputOptions(), ActsExamples::Options::addMagneticFieldOptions(), ActsExamples::Options::addMaterialOptions(), ActsExamples::Options::addOutputOptions(), ActsExamples::Options::addRandomNumbersOptions(), ActsExamples::Options::addSequencerOptions(), ActsExamples::Sequencer::addWriter(), ActsExamples::Geometry::build(), ActsExamples::ensureWritableDirectory(), Acts::Test::geometry, ActsExamples::SpacePointMaker::Config::geometrySelection, Acts::getDefaultLogger(), ActsExamples::SpacePointMaker::Config::inputMeasurements, ActsExamples::SpacePointMaker::Config::inputSourceLinks, ActsExamples::CsvSpacepointWriter::Config::inputSpacepoints, telescope_simulation::logLevel, m_logger, ActsTests::PropagationDatasets::magneticField, ActsExamples::Options::makeDefaultOptions(), outputDir, ActsExamples::CsvSpacepointWriter::Config::outputDir, ActsExamples::SpacePointMaker::Config::outputSpacePoints, ActsExamples::Options::parse(), physmon_simulation::randomNumbers, ActsExamples::Options::readLogLevel(), ActsExamples::Options::readMagneticField(), ActsExamples::Options::readRandomNumbersConfig(), ActsExamples::Options::readSequencerConfig(), ActsExamples::Sequencer::run(), ActsExamples::Options::setupMagneticFieldServices(), setupMeasurementReading(), setupParticleReading(), setupSimHitReading(), Acts::GeometryIdentifier::setVolume(), Acts::tGeometry, and ActsExamples::SpacePointMaker::Config::trackingGeometry.
Referenced by main().
Variable Documentation
std::unique_ptr<const Acts::Logger> m_logger static
Definition at line 35 of file MeasurementsToSpacepoints.cpp.
View newest version in sPHENIX GitHub at line 35 of file MeasurementsToSpacepoints.cpp
Referenced by logger(), Acts::TorchEdgeClassifier::logger(), Acts::TorchMetricLearning::logger(), ActsExamples::JsonMaterialWriter::logger(), Acts::DD4hepDetectorSurfaceFactory::logger(), runMeasurementsToSP(), Acts::Cuda::SeedFinder< external_spacepoint_t >::setLogger(), Acts::TrackingGeometryBuilder::setLogger(), Acts::PassiveLayerBuilder::setLogger(), Acts::TGeoLayerBuilder::setLogger(), Acts::CylinderVolumeHelper::setLogger(), Acts::LayerCreator::setLogger(), Acts::CylinderVolumeBuilder::setLogger(), and Acts::MultiEigenStepperLoop< extensionlist_t, component_reducer_t, auctioneer_t >::step().