Analysis Software: Acts::GlueVolumesDescriptor Class Reference
Acts::GlueVolumesDescriptor Class Reference
#include <acts/blob/sPHENIX/Core/include/Acts/Geometry/GlueVolumesDescriptor.hpp>
Public Member Functions
GlueVolumesDescriptor ()=default
Constructor.
GlueVolumesDescriptor (const std::map< BoundarySurfaceFace, std::shared_ptr< const TrackingVolumeArray >> &gvs)
~GlueVolumesDescriptor ()=default
Destructor.
void registerGlueVolumes (Acts::BoundarySurfaceFace bsf, std::shared_ptr< const TrackingVolumeArray > gvs)
std::shared_ptr< const
TrackingVolumeArray > glueVolumes (BoundarySurfaceFace bsf) const
const std::vector
< BoundarySurfaceFace > & glueFaces () const
std::string screenOutput () const
Dump it to the screen.
Private Attributes
std::map< BoundarySurfaceFace,
std::shared_ptr< const
TrackingVolumeArray > > m_glueVolumes
std::vector< BoundarySurfaceFace > m_glueFaces
Detailed Description
Descriptor class to hold GlueVolumes of a TrackingGeometry object. Should ease the wrapping of a TrackingGeometry object describing one Detector by another one.
Definition at line 34 of file GlueVolumesDescriptor.hpp.
View newest version in sPHENIX GitHub at line 34 of file GlueVolumesDescriptor.hpp
Constructor & Destructor Documentation
Acts::GlueVolumesDescriptor::GlueVolumesDescriptor () default
Constructor.
Acts::GlueVolumesDescriptor::GlueVolumesDescriptor (const std::map< BoundarySurfaceFace, std::shared_ptr< const TrackingVolumeArray >> & gvs)
Constructor - with arguments
Parameters
gvs are the glue volume arrays mapped to the volume faces
Definition at line 16 of file GlueVolumesDescriptor.cpp.
View newest version in sPHENIX GitHub at line 16 of file GlueVolumesDescriptor.cpp
References m_glueFaces, and m_glueVolumes.
Acts::GlueVolumesDescriptor::~GlueVolumesDescriptor () default
Destructor.
Member Function Documentation
const std::vector< BoundarySurfaceFace > & Acts::GlueVolumesDescriptor::glueFaces () const inline
Retrieve the available Glue Faces
Returns
the list of faces for which glue information is there
Definition at line 77 of file GlueVolumesDescriptor.hpp.
View newest version in sPHENIX GitHub at line 77 of file GlueVolumesDescriptor.hpp
References m_glueFaces.
std::shared_ptr< const Acts::TrackingVolumeArray > Acts::GlueVolumesDescriptor::glueVolumes (Acts::BoundarySurfaceFace bsf) const
Retrieve the glue volumes
Parameters
bsf is the boundary surface face for which you want to get the array
Returns
the shared pointer to the TrackingVolume array
Definition at line 40 of file GlueVolumesDescriptor.cpp.
View newest version in sPHENIX GitHub at line 40 of file GlueVolumesDescriptor.cpp
Referenced by Acts::CylinderVolumeHelper::addFaceVolumes(), and Acts::CylinderVolumeHelper::glueTrackingVolumes().
void Acts::GlueVolumesDescriptor::registerGlueVolumes (Acts::BoundarySurfaceFace bsf, std::shared_ptr< const TrackingVolumeArray > gvs)
Register the volumes
Parameters
bsf is the boundary surface face where the volume array is attached
gvs is the array of volumes to be attached
<
Definition at line 26 of file GlueVolumesDescriptor.cpp.
View newest version in sPHENIX GitHub at line 26 of file GlueVolumesDescriptor.cpp
References testing::internal::move().
Referenced by Acts::CylinderVolumeHelper::interGlueTrackingVolume().
std::string Acts::GlueVolumesDescriptor::screenOutput () const
Dump it to the screen.
Definition at line 49 of file GlueVolumesDescriptor.cpp.
View newest version in sPHENIX GitHub at line 49 of file GlueVolumesDescriptor.cpp
Referenced by Acts::operator<<().
Member Data Documentation
std::vector<BoundarySurfaceFace> Acts::GlueVolumesDescriptor::m_glueFaces private
Definition at line 73 of file GlueVolumesDescriptor.hpp.
View newest version in sPHENIX GitHub at line 73 of file GlueVolumesDescriptor.hpp
Referenced by glueFaces(), and GlueVolumesDescriptor().
std::map<BoundarySurfaceFace, std::shared_ptr<const TrackingVolumeArray> > Acts::GlueVolumesDescriptor::m_glueVolumes private
Definition at line 72 of file GlueVolumesDescriptor.hpp.
View newest version in sPHENIX GitHub at line 72 of file GlueVolumesDescriptor.hpp
Referenced by GlueVolumesDescriptor().
The documentation for this class was generated from the following files:
acts/blob/sPHENIX/Core/include/Acts/Geometry/GlueVolumesDescriptor.hpp
acts/blob/sPHENIX/Core/src/Geometry/GlueVolumesDescriptor.cpp