Analysis Software: PHG4ParticleGeneratorVectorMeson Class Reference
PHG4ParticleGeneratorVectorMeson Class Reference
#include <coresoftware/blob/master/simulation/g4simulation/g4main/PHG4ParticleGeneratorVectorMeson.h>
Public Types
enum FUNCTION { Uniform, Gaus }
supported function distributions
Public Member Functions
PHG4ParticleGeneratorVectorMeson (const std::string &name="VMESON")
~PHG4ParticleGeneratorVectorMeson () override
int InitRun (PHCompositeNode *topNode) override
int process_event (PHCompositeNode *topNode) override
void add_decay_particles (const std::string &name1, const std::string &name2, const unsigned int decay_id)
interface for adding particles by name
void add_decay_particles (const std::string &name, const unsigned int decay_id)
void set_decay_vertex_offset (double dx, double dy, double dz, const unsigned int decay_id)
void set_eta_range (const double eta_min, const double eta_max)
void set_rapidity_range (const double y_min, const double y_max)
void set_mom_range (const double mom_min, const double mom_max)
void set_pt_range (const double pt_min, const double pt_max)
void set_vertex_distribution_function (FUNCTION x, FUNCTION y, FUNCTION z)
toss a new vertex according to a Uniform or Gaus distribution
void set_vertex_distribution_mean (const double x, const double y, const double z)
set the mean value of the vertex distribution
void set_vertex_distribution_width (const double x, const double y, const double z)
set the width of the vertex distribution function about the mean
void set_existing_vertex_offset_vector (const double x, const double y, const double z)
set an offset vector from the existing vertex
void set_vertex_size_function (FUNCTION r)
set the distribution function of particles about the vertex
void set_vertex_size_parameters (const double mean, const double width)
set the dimensions of the distribution of particles about the vertex
void set_read_vtx_from_hepmc (bool read_vtx)
void set_mass (const double mass_in)
void set_width (const double width_in)
void set_decay_types (const std::string &decay1, const std::string &decay2)
void set_histrand_init (const int initflag)
void set_upsilon_1s ()
void set_upsilon_2s ()
void set_upsilon_3s ()
Public Member Functions inherited from PHG4ParticleGeneratorBase
~PHG4ParticleGeneratorBase () override
virtual void set_name (const std::string &particle="proton")
virtual void set_pid (const int pid)
virtual void set_mom (const double x, const double y, const double z)
virtual void set_vtx (const double x, const double y, const double z)
virtual void set_vtx_z (const double z)
virtual void set_t0 (const double t)
virtual double get_vtx_x () const
virtual double get_vtx_y () const
virtual double get_vtx_z () const
virtual double get_t0 () const
void Print (const std::string &what="ALL") const override
virtual void PrintParticles (const std::string &what="ALL") const
virtual void AddParticle (const std::string &particle, const double x, const double y, const double z)
virtual void AddParticle (const int pid, const double x, const double y, const double z)
virtual void Embed (const int i=1)
virtual int ReuseExistingVertex (PHCompositeNode *topNode)
int get_reuse_existing_vertex () const
void set_reuse_existing_vertex (const int i=1)
void set_seed (const unsigned int iseed)
unsigned int get_seed () const
Public Member Functions inherited from SubsysReco
~SubsysReco () override
virtual int End (PHCompositeNode *)
Called at the end of all processing.
virtual int EndRun (const int)
Called at the end of each run.
virtual int Init (PHCompositeNode *)
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Private Member Functions
double smearvtx (const double position, const double width, FUNCTION dist) const
Private Attributes
std::map< unsigned int, int > decay1_codes
std::map< unsigned int,
std::string > decay1_names
std::map< unsigned int, int > decay2_codes
std::map< unsigned int,
std::string > decay2_names
std::map< unsigned int, double > decay_vtx_offset_x
std::map< unsigned int, double > decay_vtx_offset_y
std::map< unsigned int, double > decay_vtx_offset_z
FUNCTION _vertex_func_x = Uniform
FUNCTION _vertex_func_y = Uniform
FUNCTION _vertex_func_z = Uniform
double _vertex_x = 0.
double _vertex_y = 0.
double _vertex_z = 0.
double _vertex_width_x = 0.
double _vertex_width_y = 0.
double _vertex_width_z = 0.
double _vertex_offset_x = 0.
double _vertex_offset_y = 0.
double _vertex_offset_z = 0.
FUNCTION _vertex_size_func_r = Uniform
double _vertex_size_mean = 0.
double _vertex_size_width = 0.
bool read_vtx_from_hepmc = true
double y_min = 0.
double y_max = 0.
double eta_min = -1.
double eta_max = 1.
double mom_min = 0.
double mom_max = 10.
double pt_min = 4.
double pt_max = 4.
double mass = NAN
double m_Width = NAN
double m1 = NAN
double m2 = NAN
int _histrand_init = 0
std::string decay1 = "e+"
std::string decay2 = "e-"
TF1 * fsin = nullptr
TF1 * frap = nullptr
TF1 * fpt = nullptr
TRandom * trand = nullptr
PHG4InEvent * ineve = nullptr
Additional Inherited Members
Protected Member Functions inherited from PHG4ParticleGeneratorBase
PHG4ParticleGeneratorBase (const std::string &name="GENERATORBASE")
int get_pdgcode (const std::string &name) const
std::string get_pdgname (const int pdgcode) const
double get_mass (const int pdgcode) const
void CheckAndCreateParticleVector ()
void SetParticleId (PHG4Particle *particle, PHG4InEvent *ineve)
gsl_rng * RandomGenerator () const
int EmbedFlag () const
std::vector< PHG4Particle * >
::iterator particlelist_begin ()
std::vector< PHG4Particle * >
::iterator particlelist_end ()
void ResetParticleList ()
Detailed Description
Definition at line 17 of file PHG4ParticleGeneratorVectorMeson.h.
View newest version in sPHENIX GitHub at line 17 of file PHG4ParticleGeneratorVectorMeson.h
Member Enumeration Documentation
enum PHG4ParticleGeneratorVectorMeson::FUNCTION
supported function distributions
Enumerator:
Uniform
Gaus
Definition at line 21 of file PHG4ParticleGeneratorVectorMeson.h.
View newest version in sPHENIX GitHub at line 21 of file PHG4ParticleGeneratorVectorMeson.h
Constructor & Destructor Documentation
PHG4ParticleGeneratorVectorMeson::PHG4ParticleGeneratorVectorMeson (const std::string & name = "VMESON") explicit
Definition at line 31 of file PHG4ParticleGeneratorVectorMeson.cc.
View newest version in sPHENIX GitHub at line 31 of file PHG4ParticleGeneratorVectorMeson.cc
References set_upsilon_1s().
PHG4ParticleGeneratorVectorMeson::~PHG4ParticleGeneratorVectorMeson () override
Definition at line 39 of file PHG4ParticleGeneratorVectorMeson.cc.
View newest version in sPHENIX GitHub at line 39 of file PHG4ParticleGeneratorVectorMeson.cc
References trand.
Member Function Documentation
void PHG4ParticleGeneratorVectorMeson::add_decay_particles (const std::string & name1, const std::string & name2, const unsigned int decay_id)
interface for adding particles by name
Definition at line 62 of file PHG4ParticleGeneratorVectorMeson.cc.
View newest version in sPHENIX GitHub at line 62 of file PHG4ParticleGeneratorVectorMeson.cc
References decay1_names, decay2_names, decay_vtx_offset_x, decay_vtx_offset_y, and decay_vtx_offset_z.
Referenced by add_decay_particles(), Fun4All_G4_EICDetector_LQ(), Fun4All_G4_EICDetector_LQ_reference(), Fun4All_G4_EICDetector_RICH(), Fun4All_G4_sPHENIX_photonjet(), Fun4All_G4_sPHENIX_photons(), Fun4All_G4_sPHENIX_truthphotonjet(), and Fun4All_Generator_Display().
void PHG4ParticleGeneratorVectorMeson::add_decay_particles (const std::string & name, const unsigned int decay_id)
Definition at line 44 of file PHG4ParticleGeneratorVectorMeson.cc.
View newest version in sPHENIX GitHub at line 44 of file PHG4ParticleGeneratorVectorMeson.cc
References add_decay_particles().
int PHG4ParticleGeneratorVectorMeson::InitRun (PHCompositeNode *) override virtual
Called for first event when run number is known. Typically this is where you may want to fetch data from database, because you know the run number.
Reimplemented from PHG4ParticleGeneratorBase.
Definition at line 202 of file PHG4ParticleGeneratorVectorMeson.cc.
View newest version in sPHENIX GitHub at line 202 of file PHG4ParticleGeneratorVectorMeson.cc
References _histrand_init, PHCompositeNode::addNode(), PHNodeIterator::findFirst(), fpt, frap, fsin, ineve, pt_max, pt_min, trand, Fun4AllBase::Verbosity(), y_max, and y_min.
int PHG4ParticleGeneratorVectorMeson::process_event (PHCompositeNode *) override virtual
Called for each event. This is where you do the real work.
Reimplemented from PHG4ParticleGeneratorBase.
Definition at line 250 of file PHG4ParticleGeneratorVectorMeson.cc.
View newest version in sPHENIX GitHub at line 250 of file PHG4ParticleGeneratorVectorMeson.cc
References _vertex_func_x, _vertex_func_y, _vertex_func_z, _vertex_offset_x, _vertex_offset_y, _vertex_offset_z, _vertex_size_func_r, _vertex_size_mean, _vertex_size_width, _vertex_width_x, _vertex_width_y, _vertex_width_z, _vertex_x, _vertex_y, _vertex_z, PHG4InEvent::AddEmbeddedParticle(), PHG4InEvent::AddParticle(), PHG4ParticleGeneratorBase::AddParticle(), PHG4InEvent::AddVtx(), decay1_names, decay2_names, decay_vtx_offset_x, decay_vtx_offset_y, decay_vtx_offset_z, PHG4ParticleGeneratorBase::EmbedFlag(), eta, fpt, frap, fsin, PHG4ParticleGeneratorBase::get_t0(), PHG4ParticleGeneratorBase::get_vtx_x(), PHG4ParticleGeneratorBase::get_vtx_y(), PHG4ParticleGeneratorBase::get_vtx_z(), PHG4InEvent::identify(), ineve, it, m1, m2, m_Width, mass, particle, PHG4ParticleGeneratorBase::particlelist_begin(), PHG4ParticleGeneratorBase::particlelist_end(), ActsTests::PropagationDatasets::phi, PHWHERE, physmon_track_finding_ttbar::pt, pt_max, pt_min, physmon_track_finding_ttbar::r, PHG4ParticleGeneratorBase::RandomGenerator(), PHG4ParticleGeneratorBase::ResetParticleList(), PHG4ParticleGeneratorBase::ReuseExistingVertex(), set_decay_types(), set_existing_vertex_offset_vector(), PHG4ParticleGeneratorBase::set_vtx(), PHG4ParticleGeneratorBase::SetParticleId(), smearvtx(), trand, v1, v2, Fun4AllBase::Verbosity(), y, y_max, and y_min.
void PHG4ParticleGeneratorVectorMeson::set_decay_types (const std::string & decay1, const std::string & decay2)
Definition at line 162 of file PHG4ParticleGeneratorVectorMeson.cc.
View newest version in sPHENIX GitHub at line 162 of file PHG4ParticleGeneratorVectorMeson.cc
References decay1, decay2, m1, and m2.
Referenced by process_event().
void PHG4ParticleGeneratorVectorMeson::set_decay_vertex_offset (double dx, double dy, double dz, const unsigned int decay_id)
Definition at line 81 of file PHG4ParticleGeneratorVectorMeson.cc.
View newest version in sPHENIX GitHub at line 81 of file PHG4ParticleGeneratorVectorMeson.cc
References decay_vtx_offset_x, decay_vtx_offset_y, decay_vtx_offset_z, dy, and dz.
void PHG4ParticleGeneratorVectorMeson::set_eta_range (const double eta_min, const double eta_max)
Definition at line 89 of file PHG4ParticleGeneratorVectorMeson.cc.
View newest version in sPHENIX GitHub at line 89 of file PHG4ParticleGeneratorVectorMeson.cc
References eta_max, eta_min, and Acts::UnitConstants::min.
void PHG4ParticleGeneratorVectorMeson::set_existing_vertex_offset_vector (const double x, const double y, const double z)
set an offset vector from the existing vertex
Definition at line 141 of file PHG4ParticleGeneratorVectorMeson.cc.
View newest version in sPHENIX GitHub at line 141 of file PHG4ParticleGeneratorVectorMeson.cc
References _vertex_offset_x, _vertex_offset_y, _vertex_offset_z, ambiguity_solver_full_chain::x, y, and physmon_track_finding_ttbar::z.
Referenced by process_event().
void PHG4ParticleGeneratorVectorMeson::set_histrand_init (const int initflag) inline
Definition at line 65 of file PHG4ParticleGeneratorVectorMeson.h.
View newest version in sPHENIX GitHub at line 65 of file PHG4ParticleGeneratorVectorMeson.h
References _histrand_init.
void PHG4ParticleGeneratorVectorMeson::set_mass (const double mass_in) inline
Definition at line 62 of file PHG4ParticleGeneratorVectorMeson.h.
View newest version in sPHENIX GitHub at line 62 of file PHG4ParticleGeneratorVectorMeson.h
References mass.
Referenced by Fun4All_G4_EICDetector_LQ(), Fun4All_G4_EICDetector_LQ_reference(), Fun4All_G4_EICDetector_RICH(), Fun4All_G4_sPHENIX_photonjet(), Fun4All_G4_sPHENIX_photons(), Fun4All_G4_sPHENIX_truthphotonjet(), Fun4All_Generator_Display(), set_upsilon_1s(), set_upsilon_2s(), and set_upsilon_3s().
void PHG4ParticleGeneratorVectorMeson::set_mom_range (const double mom_min, const double mom_max)
Definition at line 103 of file PHG4ParticleGeneratorVectorMeson.cc.
View newest version in sPHENIX GitHub at line 103 of file PHG4ParticleGeneratorVectorMeson.cc
References Acts::UnitConstants::min, mom_max, and mom_min.
void PHG4ParticleGeneratorVectorMeson::set_pt_range (const double pt_min, const double pt_max)
Definition at line 110 of file PHG4ParticleGeneratorVectorMeson.cc.
View newest version in sPHENIX GitHub at line 110 of file PHG4ParticleGeneratorVectorMeson.cc
References Acts::UnitConstants::min, pt_max, and pt_min.
Referenced by Fun4All_G4_EICDetector_LQ(), Fun4All_G4_EICDetector_LQ_reference(), Fun4All_G4_EICDetector_RICH(), Fun4All_G4_sPHENIX_photonjet(), Fun4All_G4_sPHENIX_photons(), Fun4All_G4_sPHENIX_truthphotonjet(), and Fun4All_Generator_Display().
void PHG4ParticleGeneratorVectorMeson::set_rapidity_range (const double y_min, const double y_max)
Definition at line 96 of file PHG4ParticleGeneratorVectorMeson.cc.
View newest version in sPHENIX GitHub at line 96 of file PHG4ParticleGeneratorVectorMeson.cc
References Acts::UnitConstants::min, y_max, and y_min.
Referenced by Fun4All_G4_EICDetector_LQ(), Fun4All_G4_EICDetector_LQ_reference(), Fun4All_G4_EICDetector_RICH(), Fun4All_G4_sPHENIX_photonjet(), Fun4All_G4_sPHENIX_photons(), Fun4All_G4_sPHENIX_truthphotonjet(), and Fun4All_Generator_Display().
void PHG4ParticleGeneratorVectorMeson::set_read_vtx_from_hepmc (bool read_vtx) inline
Definition at line 60 of file PHG4ParticleGeneratorVectorMeson.h.
View newest version in sPHENIX GitHub at line 60 of file PHG4ParticleGeneratorVectorMeson.h
References read_vtx_from_hepmc.
void PHG4ParticleGeneratorVectorMeson::set_upsilon_1s ()
Definition at line 489 of file PHG4ParticleGeneratorVectorMeson.cc.
View newest version in sPHENIX GitHub at line 489 of file PHG4ParticleGeneratorVectorMeson.cc
References Acts::UnitConstants::e, set_mass(), and set_width().
Referenced by PHG4ParticleGeneratorVectorMeson().
void PHG4ParticleGeneratorVectorMeson::set_upsilon_2s ()
Definition at line 496 of file PHG4ParticleGeneratorVectorMeson.cc.
View newest version in sPHENIX GitHub at line 496 of file PHG4ParticleGeneratorVectorMeson.cc
References Acts::UnitConstants::e, set_mass(), and set_width().
void PHG4ParticleGeneratorVectorMeson::set_upsilon_3s ()
Definition at line 503 of file PHG4ParticleGeneratorVectorMeson.cc.
View newest version in sPHENIX GitHub at line 503 of file PHG4ParticleGeneratorVectorMeson.cc
References Acts::UnitConstants::e, set_mass(), and set_width().
void PHG4ParticleGeneratorVectorMeson::set_vertex_distribution_function (FUNCTION x, FUNCTION y, FUNCTION z)
toss a new vertex according to a Uniform or Gaus distribution
Definition at line 117 of file PHG4ParticleGeneratorVectorMeson.cc.
View newest version in sPHENIX GitHub at line 117 of file PHG4ParticleGeneratorVectorMeson.cc
References _vertex_func_x, _vertex_func_y, _vertex_func_z, ambiguity_solver_full_chain::x, y, and physmon_track_finding_ttbar::z.
void PHG4ParticleGeneratorVectorMeson::set_vertex_distribution_mean (const double x, const double y, const double z)
set the mean value of the vertex distribution
Definition at line 125 of file PHG4ParticleGeneratorVectorMeson.cc.
View newest version in sPHENIX GitHub at line 125 of file PHG4ParticleGeneratorVectorMeson.cc
References _vertex_x, _vertex_y, _vertex_z, ambiguity_solver_full_chain::x, y, and physmon_track_finding_ttbar::z.
void PHG4ParticleGeneratorVectorMeson::set_vertex_distribution_width (const double x, const double y, const double z)
set the width of the vertex distribution function about the mean
Definition at line 133 of file PHG4ParticleGeneratorVectorMeson.cc.
View newest version in sPHENIX GitHub at line 133 of file PHG4ParticleGeneratorVectorMeson.cc
References _vertex_width_x, _vertex_width_y, _vertex_width_z, ambiguity_solver_full_chain::x, y, and physmon_track_finding_ttbar::z.
void PHG4ParticleGeneratorVectorMeson::set_vertex_size_function (FUNCTION r)
set the distribution function of particles about the vertex
Definition at line 149 of file PHG4ParticleGeneratorVectorMeson.cc.
View newest version in sPHENIX GitHub at line 149 of file PHG4ParticleGeneratorVectorMeson.cc
References _vertex_size_func_r, and physmon_track_finding_ttbar::r.
void PHG4ParticleGeneratorVectorMeson::set_vertex_size_parameters (const double mean, const double width)
set the dimensions of the distribution of particles about the vertex
Definition at line 155 of file PHG4ParticleGeneratorVectorMeson.cc.
View newest version in sPHENIX GitHub at line 155 of file PHG4ParticleGeneratorVectorMeson.cc
References _vertex_size_mean, _vertex_size_width, mean(), and width.
void PHG4ParticleGeneratorVectorMeson::set_width (const double width_in) inline
Definition at line 63 of file PHG4ParticleGeneratorVectorMeson.h.
View newest version in sPHENIX GitHub at line 63 of file PHG4ParticleGeneratorVectorMeson.h
References m_Width.
Referenced by Fun4All_G4_EICDetector_LQ(), Fun4All_G4_EICDetector_LQ_reference(), Fun4All_G4_EICDetector_RICH(), Fun4All_G4_sPHENIX_photonjet(), Fun4All_G4_sPHENIX_photons(), Fun4All_G4_sPHENIX_truthphotonjet(), Fun4All_Generator_Display(), set_upsilon_1s(), set_upsilon_2s(), and set_upsilon_3s().
double PHG4ParticleGeneratorVectorMeson::smearvtx (const double position, const double width, FUNCTION dist) const private
Definition at line 475 of file PHG4ParticleGeneratorVectorMeson.cc.
View newest version in sPHENIX GitHub at line 475 of file PHG4ParticleGeneratorVectorMeson.cc
References Gaus, m_Width, position, PHG4ParticleGeneratorBase::RandomGenerator(), and Uniform.
Referenced by process_event().
Member Data Documentation
int PHG4ParticleGeneratorVectorMeson::_histrand_init = 0 private
Definition at line 109 of file PHG4ParticleGeneratorVectorMeson.h.
View newest version in sPHENIX GitHub at line 109 of file PHG4ParticleGeneratorVectorMeson.h
Referenced by InitRun(), and set_histrand_init().
FUNCTION PHG4ParticleGeneratorVectorMeson::_vertex_func_x = Uniform private
Definition at line 80 of file PHG4ParticleGeneratorVectorMeson.h.
View newest version in sPHENIX GitHub at line 80 of file PHG4ParticleGeneratorVectorMeson.h
Referenced by process_event(), and set_vertex_distribution_function().
FUNCTION PHG4ParticleGeneratorVectorMeson::_vertex_func_y = Uniform private
Definition at line 81 of file PHG4ParticleGeneratorVectorMeson.h.
View newest version in sPHENIX GitHub at line 81 of file PHG4ParticleGeneratorVectorMeson.h
Referenced by process_event(), and set_vertex_distribution_function().
FUNCTION PHG4ParticleGeneratorVectorMeson::_vertex_func_z = Uniform private
Definition at line 82 of file PHG4ParticleGeneratorVectorMeson.h.
View newest version in sPHENIX GitHub at line 82 of file PHG4ParticleGeneratorVectorMeson.h
Referenced by process_event(), and set_vertex_distribution_function().
double PHG4ParticleGeneratorVectorMeson::_vertex_offset_x = 0. private
Definition at line 89 of file PHG4ParticleGeneratorVectorMeson.h.
View newest version in sPHENIX GitHub at line 89 of file PHG4ParticleGeneratorVectorMeson.h
Referenced by process_event(), and set_existing_vertex_offset_vector().
double PHG4ParticleGeneratorVectorMeson::_vertex_offset_y = 0. private
Definition at line 90 of file PHG4ParticleGeneratorVectorMeson.h.
View newest version in sPHENIX GitHub at line 90 of file PHG4ParticleGeneratorVectorMeson.h
Referenced by process_event(), and set_existing_vertex_offset_vector().
double PHG4ParticleGeneratorVectorMeson::_vertex_offset_z = 0. private
Definition at line 91 of file PHG4ParticleGeneratorVectorMeson.h.
View newest version in sPHENIX GitHub at line 91 of file PHG4ParticleGeneratorVectorMeson.h
Referenced by process_event(), and set_existing_vertex_offset_vector().
FUNCTION PHG4ParticleGeneratorVectorMeson::_vertex_size_func_r = Uniform private
Definition at line 92 of file PHG4ParticleGeneratorVectorMeson.h.
View newest version in sPHENIX GitHub at line 92 of file PHG4ParticleGeneratorVectorMeson.h
Referenced by process_event(), and set_vertex_size_function().
double PHG4ParticleGeneratorVectorMeson::_vertex_size_mean = 0. private
Definition at line 93 of file PHG4ParticleGeneratorVectorMeson.h.
View newest version in sPHENIX GitHub at line 93 of file PHG4ParticleGeneratorVectorMeson.h
Referenced by process_event(), and set_vertex_size_parameters().
double PHG4ParticleGeneratorVectorMeson::_vertex_size_width = 0. private
Definition at line 94 of file PHG4ParticleGeneratorVectorMeson.h.
View newest version in sPHENIX GitHub at line 94 of file PHG4ParticleGeneratorVectorMeson.h
Referenced by process_event(), and set_vertex_size_parameters().
double PHG4ParticleGeneratorVectorMeson::_vertex_width_x = 0. private
Definition at line 86 of file PHG4ParticleGeneratorVectorMeson.h.
View newest version in sPHENIX GitHub at line 86 of file PHG4ParticleGeneratorVectorMeson.h
Referenced by process_event(), and set_vertex_distribution_width().
double PHG4ParticleGeneratorVectorMeson::_vertex_width_y = 0. private
Definition at line 87 of file PHG4ParticleGeneratorVectorMeson.h.
View newest version in sPHENIX GitHub at line 87 of file PHG4ParticleGeneratorVectorMeson.h
Referenced by process_event(), and set_vertex_distribution_width().
double PHG4ParticleGeneratorVectorMeson::_vertex_width_z = 0. private
Definition at line 88 of file PHG4ParticleGeneratorVectorMeson.h.
View newest version in sPHENIX GitHub at line 88 of file PHG4ParticleGeneratorVectorMeson.h
Referenced by process_event(), and set_vertex_distribution_width().
double PHG4ParticleGeneratorVectorMeson::_vertex_x = 0. private
Definition at line 83 of file PHG4ParticleGeneratorVectorMeson.h.
View newest version in sPHENIX GitHub at line 83 of file PHG4ParticleGeneratorVectorMeson.h
Referenced by process_event(), and set_vertex_distribution_mean().
double PHG4ParticleGeneratorVectorMeson::_vertex_y = 0. private
Definition at line 84 of file PHG4ParticleGeneratorVectorMeson.h.
View newest version in sPHENIX GitHub at line 84 of file PHG4ParticleGeneratorVectorMeson.h
Referenced by process_event(), and set_vertex_distribution_mean().
double PHG4ParticleGeneratorVectorMeson::_vertex_z = 0. private
Definition at line 85 of file PHG4ParticleGeneratorVectorMeson.h.
View newest version in sPHENIX GitHub at line 85 of file PHG4ParticleGeneratorVectorMeson.h
Referenced by process_event(), and set_vertex_distribution_mean().
std::string PHG4ParticleGeneratorVectorMeson::decay1 = "e+" private
Definition at line 110 of file PHG4ParticleGeneratorVectorMeson.h.
View newest version in sPHENIX GitHub at line 110 of file PHG4ParticleGeneratorVectorMeson.h
Referenced by set_decay_types().
std::map<unsigned int, int> PHG4ParticleGeneratorVectorMeson::decay1_codes private
Definition at line 72 of file PHG4ParticleGeneratorVectorMeson.h.
View newest version in sPHENIX GitHub at line 72 of file PHG4ParticleGeneratorVectorMeson.h
std::map<unsigned int, std::string> PHG4ParticleGeneratorVectorMeson::decay1_names private
Definition at line 73 of file PHG4ParticleGeneratorVectorMeson.h.
View newest version in sPHENIX GitHub at line 73 of file PHG4ParticleGeneratorVectorMeson.h
Referenced by add_decay_particles(), and process_event().
std::string PHG4ParticleGeneratorVectorMeson::decay2 = "e-" private
Definition at line 111 of file PHG4ParticleGeneratorVectorMeson.h.
View newest version in sPHENIX GitHub at line 111 of file PHG4ParticleGeneratorVectorMeson.h
Referenced by set_decay_types().
std::map<unsigned int, int> PHG4ParticleGeneratorVectorMeson::decay2_codes private
Definition at line 74 of file PHG4ParticleGeneratorVectorMeson.h.
View newest version in sPHENIX GitHub at line 74 of file PHG4ParticleGeneratorVectorMeson.h
std::map<unsigned int, std::string> PHG4ParticleGeneratorVectorMeson::decay2_names private
Definition at line 75 of file PHG4ParticleGeneratorVectorMeson.h.
View newest version in sPHENIX GitHub at line 75 of file PHG4ParticleGeneratorVectorMeson.h
Referenced by add_decay_particles(), and process_event().
std::map<unsigned int, double> PHG4ParticleGeneratorVectorMeson::decay_vtx_offset_x private
Definition at line 76 of file PHG4ParticleGeneratorVectorMeson.h.
View newest version in sPHENIX GitHub at line 76 of file PHG4ParticleGeneratorVectorMeson.h
Referenced by add_decay_particles(), process_event(), and set_decay_vertex_offset().
std::map<unsigned int, double> PHG4ParticleGeneratorVectorMeson::decay_vtx_offset_y private
Definition at line 77 of file PHG4ParticleGeneratorVectorMeson.h.
View newest version in sPHENIX GitHub at line 77 of file PHG4ParticleGeneratorVectorMeson.h
Referenced by add_decay_particles(), process_event(), and set_decay_vertex_offset().
std::map<unsigned int, double> PHG4ParticleGeneratorVectorMeson::decay_vtx_offset_z private
Definition at line 78 of file PHG4ParticleGeneratorVectorMeson.h.
View newest version in sPHENIX GitHub at line 78 of file PHG4ParticleGeneratorVectorMeson.h
Referenced by add_decay_particles(), process_event(), and set_decay_vertex_offset().
double PHG4ParticleGeneratorVectorMeson::eta_max = 1. private
Definition at line 100 of file PHG4ParticleGeneratorVectorMeson.h.
View newest version in sPHENIX GitHub at line 100 of file PHG4ParticleGeneratorVectorMeson.h
Referenced by set_eta_range().
double PHG4ParticleGeneratorVectorMeson::eta_min = -1. private
Definition at line 99 of file PHG4ParticleGeneratorVectorMeson.h.
View newest version in sPHENIX GitHub at line 99 of file PHG4ParticleGeneratorVectorMeson.h
Referenced by set_eta_range().
TF1* PHG4ParticleGeneratorVectorMeson::fpt = nullptr private
Definition at line 115 of file PHG4ParticleGeneratorVectorMeson.h.
View newest version in sPHENIX GitHub at line 115 of file PHG4ParticleGeneratorVectorMeson.h
Referenced by InitRun(), and process_event().
TF1* PHG4ParticleGeneratorVectorMeson::frap = nullptr private
Definition at line 114 of file PHG4ParticleGeneratorVectorMeson.h.
View newest version in sPHENIX GitHub at line 114 of file PHG4ParticleGeneratorVectorMeson.h
Referenced by InitRun(), and process_event().
TF1* PHG4ParticleGeneratorVectorMeson::fsin = nullptr private
Definition at line 113 of file PHG4ParticleGeneratorVectorMeson.h.
View newest version in sPHENIX GitHub at line 113 of file PHG4ParticleGeneratorVectorMeson.h
Referenced by InitRun(), and process_event().
PHG4InEvent* PHG4ParticleGeneratorVectorMeson::ineve = nullptr private
Definition at line 118 of file PHG4ParticleGeneratorVectorMeson.h.
View newest version in sPHENIX GitHub at line 118 of file PHG4ParticleGeneratorVectorMeson.h
Referenced by InitRun(), and process_event().
double PHG4ParticleGeneratorVectorMeson::m1 = NAN private
Definition at line 107 of file PHG4ParticleGeneratorVectorMeson.h.
View newest version in sPHENIX GitHub at line 107 of file PHG4ParticleGeneratorVectorMeson.h
Referenced by process_event(), and set_decay_types().
double PHG4ParticleGeneratorVectorMeson::m2 = NAN private
Definition at line 108 of file PHG4ParticleGeneratorVectorMeson.h.
View newest version in sPHENIX GitHub at line 108 of file PHG4ParticleGeneratorVectorMeson.h
Referenced by process_event(), and set_decay_types().
double PHG4ParticleGeneratorVectorMeson::m_Width = NAN private
Definition at line 106 of file PHG4ParticleGeneratorVectorMeson.h.
View newest version in sPHENIX GitHub at line 106 of file PHG4ParticleGeneratorVectorMeson.h
Referenced by process_event(), set_width(), and smearvtx().
double PHG4ParticleGeneratorVectorMeson::mass = NAN private
Definition at line 105 of file PHG4ParticleGeneratorVectorMeson.h.
View newest version in sPHENIX GitHub at line 105 of file PHG4ParticleGeneratorVectorMeson.h
Referenced by process_event(), and set_mass().
double PHG4ParticleGeneratorVectorMeson::mom_max = 10. private
Definition at line 102 of file PHG4ParticleGeneratorVectorMeson.h.
View newest version in sPHENIX GitHub at line 102 of file PHG4ParticleGeneratorVectorMeson.h
Referenced by set_mom_range().
double PHG4ParticleGeneratorVectorMeson::mom_min = 0. private
Definition at line 101 of file PHG4ParticleGeneratorVectorMeson.h.
View newest version in sPHENIX GitHub at line 101 of file PHG4ParticleGeneratorVectorMeson.h
Referenced by set_mom_range().
double PHG4ParticleGeneratorVectorMeson::pt_max = 4. private
Definition at line 104 of file PHG4ParticleGeneratorVectorMeson.h.
View newest version in sPHENIX GitHub at line 104 of file PHG4ParticleGeneratorVectorMeson.h
Referenced by InitRun(), process_event(), and set_pt_range().
double PHG4ParticleGeneratorVectorMeson::pt_min = 4. private
Definition at line 103 of file PHG4ParticleGeneratorVectorMeson.h.
View newest version in sPHENIX GitHub at line 103 of file PHG4ParticleGeneratorVectorMeson.h
Referenced by InitRun(), process_event(), and set_pt_range().
bool PHG4ParticleGeneratorVectorMeson::read_vtx_from_hepmc = true private
Definition at line 95 of file PHG4ParticleGeneratorVectorMeson.h.
View newest version in sPHENIX GitHub at line 95 of file PHG4ParticleGeneratorVectorMeson.h
Referenced by set_read_vtx_from_hepmc().
TRandom* PHG4ParticleGeneratorVectorMeson::trand = nullptr private
Definition at line 116 of file PHG4ParticleGeneratorVectorMeson.h.
View newest version in sPHENIX GitHub at line 116 of file PHG4ParticleGeneratorVectorMeson.h
Referenced by InitRun(), process_event(), and ~PHG4ParticleGeneratorVectorMeson().
double PHG4ParticleGeneratorVectorMeson::y_max = 0. private
Definition at line 98 of file PHG4ParticleGeneratorVectorMeson.h.
View newest version in sPHENIX GitHub at line 98 of file PHG4ParticleGeneratorVectorMeson.h
Referenced by InitRun(), process_event(), and set_rapidity_range().
double PHG4ParticleGeneratorVectorMeson::y_min = 0. private
Definition at line 97 of file PHG4ParticleGeneratorVectorMeson.h.
View newest version in sPHENIX GitHub at line 97 of file PHG4ParticleGeneratorVectorMeson.h
Referenced by InitRun(), process_event(), and set_rapidity_range().
The documentation for this class was generated from the following files:
coresoftware/blob/master/simulation/g4simulation/g4main/PHG4ParticleGeneratorVectorMeson.h
coresoftware/blob/master/simulation/g4simulation/g4main/PHG4ParticleGeneratorVectorMeson.cc