Analysis Software: Acts::Test::SurfaceArrayCreatorFixture Struct Reference
Acts::Test::SurfaceArrayCreatorFixture Struct Reference
Public Member Functions
SurfaceArrayCreatorFixture ()
~SurfaceArrayCreatorFixture ()
template<typename... Args>
SurfaceArrayCreator::ProtoAxis createEquidistantAxis (Args &&...args)
template<typename... Args>
SurfaceArrayCreator::ProtoAxis createVariableAxis (Args &&...args)
template<detail::AxisBoundaryType bdtA, detail::AxisBoundaryType bdtB, typename... Args>
std::unique_ptr
< SurfaceArray::ISurfaceGridLookup > makeSurfaceGridLookup2D (Args &&...args)
SrfVec fullPhiTestSurfacesEC (size_t n=10, double shift=0, double zbase=0, double r=10, double w=2, double h=1)
SrfVec fullPhiTestSurfacesBRL (size_t n=10, double shift=0, double zbase=0, double incl=M_PI/9., double w=2, double h=1.5)
SrfVec straightLineSurfaces (size_t n=10., double step=3, const Vector3 &origin={0, 0, 1.5}, const Transform3 &pretrans=Transform3::Identity(), const Vector3 &dir={0, 0, 1})
SrfVec makeBarrel (int nPhi, int nZ, double w, double h)
std::pair< SrfVec, std::vector
< std::pair< const Surface
*, const Surface * > > > makeBarrelStagger (int nPhi, int nZ, double shift=0, double incl=M_PI/9., double w=2, double h=1.5)
Public Attributes
SurfaceArrayCreator m_SAC
std::vector< std::shared_ptr
< const Surface > > m_surfaces
Detailed Description
Definition at line 71 of file SurfaceArrayCreatorTests.cpp.
View newest version in sPHENIX GitHub at line 71 of file SurfaceArrayCreatorTests.cpp
Constructor & Destructor Documentation
Acts::Test::SurfaceArrayCreatorFixture::SurfaceArrayCreatorFixture () inline
Definition at line 75 of file SurfaceArrayCreatorTests.cpp.
View newest version in sPHENIX GitHub at line 75 of file SurfaceArrayCreatorTests.cpp
Acts::Test::SurfaceArrayCreatorFixture::~SurfaceArrayCreatorFixture () inline
Definition at line 81 of file SurfaceArrayCreatorTests.cpp.
View newest version in sPHENIX GitHub at line 81 of file SurfaceArrayCreatorTests.cpp
Member Function Documentation
template<typename... Args> SurfaceArrayCreator::ProtoAxis Acts::Test::SurfaceArrayCreatorFixture::createEquidistantAxis (Args &&... args) inline
Definition at line 84 of file SurfaceArrayCreatorTests.cpp.
View newest version in sPHENIX GitHub at line 84 of file SurfaceArrayCreatorTests.cpp
References check_smearing_config::args, Acts::SurfaceArrayCreator::createEquidistantAxis(), and m_SAC.
template<typename... Args> SurfaceArrayCreator::ProtoAxis Acts::Test::SurfaceArrayCreatorFixture::createVariableAxis (Args &&... args) inline
Definition at line 89 of file SurfaceArrayCreatorTests.cpp.
View newest version in sPHENIX GitHub at line 89 of file SurfaceArrayCreatorTests.cpp
References check_smearing_config::args, Acts::SurfaceArrayCreator::createVariableAxis(), and m_SAC.
SrfVec Acts::Test::SurfaceArrayCreatorFixture::fullPhiTestSurfacesBRL (size_t n = 10, double shift = 0, double zbase = 0, double incl = M_PI / 9., double w = 2, double h = 1.5) inline
Definition at line 130 of file SurfaceArrayCreatorTests.cpp.
View newest version in sPHENIX GitHub at line 130 of file SurfaceArrayCreatorTests.cpp
References bounds, h, i, m_surfaces, testing::internal::move(), n, ActsTests::PropagationDatasets::phi, and physmon_track_finding_ttbar::z.
Referenced by makeBarrel().
SrfVec Acts::Test::SurfaceArrayCreatorFixture::fullPhiTestSurfacesEC (size_t n = 10, double shift = 0, double zbase = 0, double r = 10, double w = 2, double h = 1) inline
Definition at line 101 of file SurfaceArrayCreatorTests.cpp.
View newest version in sPHENIX GitHub at line 101 of file SurfaceArrayCreatorTests.cpp
References bounds, h, i, m_surfaces, testing::internal::move(), n, ActsTests::PropagationDatasets::phi, physmon_track_finding_ttbar::r, and physmon_track_finding_ttbar::z.
SrfVec Acts::Test::SurfaceArrayCreatorFixture::makeBarrel (int nPhi, int nZ, double w, double h) inline
Definition at line 186 of file SurfaceArrayCreatorTests.cpp.
View newest version in sPHENIX GitHub at line 186 of file SurfaceArrayCreatorTests.cpp
References fullPhiTestSurfacesBRL(), and physmon_track_finding_ttbar::z.
std::pair<SrfVec, std::vector<std::pair<const Surface*, const Surface*> > > Acts::Test::SurfaceArrayCreatorFixture::makeBarrelStagger (int nPhi, int nZ, double shift = 0, double incl = M_PI / 9., double w = 2, double h = 1.5) inline
Definition at line 201 of file SurfaceArrayCreatorTests.cpp.
View newest version in sPHENIX GitHub at line 201 of file SurfaceArrayCreatorTests.cpp
References bounds, h, j, m_surfaces, testing::internal::move(), ActsTests::PropagationDatasets::phi, Acts::Test::tgContext, and physmon_track_finding_ttbar::z.
template<detail::AxisBoundaryType bdtA, detail::AxisBoundaryType bdtB, typename... Args> std::unique_ptr<SurfaceArray::ISurfaceGridLookup> Acts::Test::SurfaceArrayCreatorFixture::makeSurfaceGridLookup2D (Args &&... args) inline
Definition at line 95 of file SurfaceArrayCreatorTests.cpp.
View newest version in sPHENIX GitHub at line 95 of file SurfaceArrayCreatorTests.cpp
References check_smearing_config::args, m_SAC, and Acts::SurfaceArrayCreator::makeSurfaceGridLookup2D().
SrfVec Acts::Test::SurfaceArrayCreatorFixture::straightLineSurfaces (size_t n = 10., double step = 3, const Vector3 & origin = {0, 0, 1.5}, const Transform3 & pretrans = Transform3::Identity(), const Vector3 & dir = {0, 0, 1}) inline
Definition at line 160 of file SurfaceArrayCreatorTests.cpp.
View newest version in sPHENIX GitHub at line 160 of file SurfaceArrayCreatorTests.cpp
Member Data Documentation
SurfaceArrayCreator Acts::Test::SurfaceArrayCreatorFixture::m_SAC
Definition at line 72 of file SurfaceArrayCreatorTests.cpp.
View newest version in sPHENIX GitHub at line 72 of file SurfaceArrayCreatorTests.cpp
Referenced by createEquidistantAxis(), createVariableAxis(), and makeSurfaceGridLookup2D().
std::vector<std::shared_ptr<const Surface> > Acts::Test::SurfaceArrayCreatorFixture::m_surfaces
Definition at line 73 of file SurfaceArrayCreatorTests.cpp.
View newest version in sPHENIX GitHub at line 73 of file SurfaceArrayCreatorTests.cpp
Referenced by fullPhiTestSurfacesBRL(), fullPhiTestSurfacesEC(), and makeBarrelStagger().
The documentation for this struct was generated from the following file:
acts/blob/sPHENIX/Tests/UnitTests/Core/Geometry/SurfaceArrayCreatorTests.cpp