Analysis Software: analysis/blob/master/EICAnalysis/macros/leptoquarks_fun4all/G4_HIJetReco.C File Reference
G4_HIJetReco.C File Reference
Functions
void HIJetReco (int verbosity=0)
Function Documentation
void HIJetReco (int verbosity = 0)
Definition at line 1 of file G4_HIJetReco.C.
View newest version in sPHENIX GitHub at line 1 of file G4_HIJetReco.C
References JetReco::add_algo(), JetReco::add_input(), Jet::ANTIKT, Jet::CEMC_TOWER_RETOWER, Jet::CEMC_TOWER_SUB1, Jet::HCALIN_TOWER, Jet::HCALIN_TOWER_SUB1, Jet::HCALOUT_TOWER, Jet::HCALOUT_TOWER_SUB1, Fun4AllServer::instance(), Fun4AllServer::registerSubsystem(), JetReco::set_algo_node(), JetReco::set_input_node(), DetermineTowerBackground::SetBackgroundOutputName(), DetermineTowerBackground::SetSeedType(), verbosity, and Fun4AllBase::Verbosity().
Referenced by Fun4All(), Fun4All_AnaTutorial_sPHENIX(), Fun4All_AnaTutorial_sPHENIX_Jets(), Fun4All_EMJetVal(), Fun4All_G4_Calo(), Fun4All_G4_EICDetector_LQ_analysis(), Fun4All_G4_EICDetector_LQ_analysis_nf(), Fun4All_G4_EICDetector_LQ_reference(), Fun4All_G4_EICDetector_RICH(), Fun4All_G4_sPHENIX(), Fun4All_G4_sPHENIX_ForTrackCutStudy(), Fun4All_G4_sPHENIX_ForTrackCutStudy_EmbedScanOff(), Fun4All_G4_sPHENIX_ForTrackCutStudy_EmbedScanOn(), Fun4All_G4_sPHENIX_ForTrackCutStudy_WithPileup_EmbedScanOff(), Fun4All_G4_sPHENIX_ForTrackCutStudy_WithPileup_EmbedScanOn(), Fun4All_G4_sPHENIX_photonjet(), Fun4All_G4_sPHENIX_photons(), Fun4All_G4_sPHENIX_truthphotonjet(), Fun4All_JetNconst(), Fun4All_JetRhoMedian(), Fun4All_JetSeedCount(), Fun4All_JetVal(), Fun4All_Pi0Gen_sPHENIX(), Fun4All_pi0tbt_SIMPLE_EMBED(), Fun4All_RhoFluct(), Fun4All_RTrack(), Fun4All_RunNewTruthMatcher(), Fun4All_SinglePhotonGen_sPHENIX(), Fun4All_SinglePi0Gen_sPHENIX(), Fun4All_UE_v2_Psi2(), run_calo_fromMDC2Hits_towslope_Fun4All_G4_Calo(), rundst_spiNo(), and spiNo2().