Analysis Software: TrkrClusterHitAssocv2 Class Reference
TrkrClusterHitAssocv2 Class Reference
Class for associating clusters to the hits that went into them.
#include <coresoftware/blob/master/offline/packages/trackbase/TrkrClusterHitAssocv2.h>
Public Member Functions
TrkrClusterHitAssocv2 ()=default
void Reset () override
Clear Event.
void identify (std::ostream &os=std::cout) const override
void addAssoc (TrkrDefs::cluskey, unsigned int) override
Add association between cluster and hit.
Map * getClusterMap (TrkrDefs::hitsetkey) override
get pointer to cluster-to-hit map corresponding to a given hitset id
ConstRange getHits (TrkrDefs::cluskey) override
Get all the hits associated with a cluster by key.
unsigned int size () const override
Private Member Functions
ClassDefOverride (TrkrClusterHitAssocv2, 1)
Private Attributes
unsigned int max_layer = 57
unsigned int max_phisegment = 12
unsigned int max_zsegment = 8
Map m_map [57][12][8]
Additional Inherited Members
Public Types inherited from TrkrClusterHitAssoc
using Map = std::multimap< TrkrDefs::cluskey, TrkrDefs::hitkey >
using ConstIterator = Map::const_iterator
using ConstRange = std::pair< Map::const_iterator, Map::const_iterator >
Protected Member Functions inherited from TrkrClusterHitAssoc
TrkrClusterHitAssoc ()=default
Detailed Description
Class for associating clusters to the hits that went into them.
Store the associations between clusters and the hits that went into them.
Definition at line 24 of file TrkrClusterHitAssocv2.h.
View newest version in sPHENIX GitHub at line 24 of file TrkrClusterHitAssocv2.h
Constructor & Destructor Documentation
TrkrClusterHitAssocv2::TrkrClusterHitAssocv2 () default
Member Function Documentation
void TrkrClusterHitAssocv2::addAssoc (TrkrDefs::cluskey ckey, unsigned hidx) override virtual
Add association between cluster and hit.
Parameters
[in] ckey Cluster key
[in] hidx Index of the hit in TrkrHitSet
Implements TrkrClusterHitAssoc.
Definition at line 60 of file TrkrClusterHitAssocv2.cc.
View newest version in sPHENIX GitHub at line 60 of file TrkrClusterHitAssocv2.cc
References TrkrDefs::getLayer(), TrkrDefs::getPhiElement(), TrkrDefs::getZElement(), layer, m_map, max_layer, max_phisegment, and max_zsegment.
TrkrClusterHitAssocv2::ClassDefOverride (TrkrClusterHitAssocv2 , 1) private
TrkrClusterHitAssocv2::Map * TrkrClusterHitAssocv2::getClusterMap (TrkrDefs::hitsetkey) override virtual
get pointer to cluster-to-hit map corresponding to a given hitset id
Reimplemented from TrkrClusterHitAssoc.
Definition at line 83 of file TrkrClusterHitAssocv2.cc.
View newest version in sPHENIX GitHub at line 83 of file TrkrClusterHitAssocv2.cc
References TrkrDefs::getLayer(), TrkrDefs::getPhiElement(), TrkrDefs::getZElement(), layer, m_map, max_layer, max_phisegment, and max_zsegment.
TrkrClusterHitAssocv2::ConstRange TrkrClusterHitAssocv2::getHits (TrkrDefs::cluskey) override virtual
Get all the hits associated with a cluster by key.
Parameters
[in] ckey Cluster key
[out] Range over hits associated with ckey
Implements TrkrClusterHitAssoc.
Definition at line 107 of file TrkrClusterHitAssocv2.cc.
View newest version in sPHENIX GitHub at line 107 of file TrkrClusterHitAssocv2.cc
References TrkrDefs::getLayer(), TrkrDefs::getPhiElement(), TrkrDefs::getZElement(), layer, m_map, max_layer, max_phisegment, and max_zsegment.
void TrkrClusterHitAssocv2::identify (std::ostream & os = std::cout) const override virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from PHObject.
Definition at line 34 of file TrkrClusterHitAssocv2.cc.
View newest version in sPHENIX GitHub at line 34 of file TrkrClusterHitAssocv2.cc
References TrkrDefs::getLayer(), layer, m_map, max_layer, max_phisegment, max_zsegment, and size().
void TrkrClusterHitAssocv2::Reset () override virtual
Clear Event.
Reimplemented from TrkrClusterHitAssoc.
Definition at line 19 of file TrkrClusterHitAssocv2.cc.
View newest version in sPHENIX GitHub at line 19 of file TrkrClusterHitAssocv2.cc
References layer, m_map, max_layer, max_phisegment, and max_zsegment.
unsigned int TrkrClusterHitAssocv2::size (void) const override virtual
Reimplemented from TrkrClusterHitAssoc.
Definition at line 131 of file TrkrClusterHitAssocv2.cc.
View newest version in sPHENIX GitHub at line 131 of file TrkrClusterHitAssocv2.cc
References layer, m_map, max_layer, max_phisegment, and max_zsegment.
Referenced by identify().
Member Data Documentation
Map TrkrClusterHitAssocv2::m_map[57][12][8] private
Definition at line 45 of file TrkrClusterHitAssocv2.h.
View newest version in sPHENIX GitHub at line 45 of file TrkrClusterHitAssocv2.h
Referenced by addAssoc(), getClusterMap(), getHits(), identify(), Reset(), and size().
unsigned int TrkrClusterHitAssocv2::max_layer = 57 private
Definition at line 42 of file TrkrClusterHitAssocv2.h.
View newest version in sPHENIX GitHub at line 42 of file TrkrClusterHitAssocv2.h
Referenced by addAssoc(), getClusterMap(), getHits(), identify(), Reset(), and size().
unsigned int TrkrClusterHitAssocv2::max_phisegment = 12 private
Definition at line 43 of file TrkrClusterHitAssocv2.h.
View newest version in sPHENIX GitHub at line 43 of file TrkrClusterHitAssocv2.h
Referenced by addAssoc(), getClusterMap(), getHits(), identify(), Reset(), and size().
unsigned int TrkrClusterHitAssocv2::max_zsegment = 8 private
Definition at line 44 of file TrkrClusterHitAssocv2.h.
View newest version in sPHENIX GitHub at line 44 of file TrkrClusterHitAssocv2.h
Referenced by addAssoc(), getClusterMap(), getHits(), identify(), Reset(), and size().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/trackbase/TrkrClusterHitAssocv2.h
coresoftware/blob/master/offline/packages/trackbase/TrkrClusterHitAssocv2.cc