Analysis Software: cl::BufferGL Class Reference
cl::BufferGL Class Reference
Memory buffer interface for GL interop.
#include <JETSCAPE/blob/main/external_packages/clvisc_wrapper/include/cl.hpp>
Public Member Functions
BufferGL (const Context &context, cl_mem_flags flags, GLuint bufobj, cl_int *err=NULL)
BufferGL ()
BufferGL (const BufferGL &buffer)
BufferGL & operator= (const BufferGL &rhs)
cl_int getObjectInfo (cl_gl_object_type *type, GLuint *gl_object_name)
Public Member Functions inherited from cl::Buffer
Buffer (const Context &context, cl_mem_flags flags,::size_t size, void *host_ptr=NULL, cl_int *err=NULL)
Buffer ()
Buffer (const Buffer &buffer)
Buffer & operator= (const Buffer &rhs)
Public Member Functions inherited from cl::Memory
Memory ()
Memory (const Memory &memory)
Memory & operator= (const Memory &rhs)
template<typename T >
cl_int getInfo (cl_mem_info name, T *param) const
template<cl_int name>
detail::param_traits
< detail::cl_mem_info, name >
::param_type getInfo (cl_int *err=NULL) const
Public Member Functions inherited from cl::detail::Wrapper< cl_mem >
Wrapper ()
Wrapper (const Wrapper< cl_type > &rhs)
~Wrapper ()
Wrapper< cl_type > & operator= (const Wrapper< cl_type > &rhs)
cl_type operator() () const
cl_type & operator() ()
Additional Inherited Members
Public Types inherited from cl::detail::Wrapper< cl_mem >
typedef cl_mem cl_type
Protected Member Functions inherited from cl::detail::Wrapper< cl_mem >
cl_int retain () const
cl_int release () const
Protected Attributes inherited from cl::detail::Wrapper< cl_mem >
cl_type object_
Detailed Description
Memory buffer interface for GL interop.
Definition at line 1845 of file cl.hpp.
View newest version in sPHENIX GitHub at line 1845 of file cl.hpp
Constructor & Destructor Documentation
cl::BufferGL::BufferGL (const Context & context, cl_mem_flags flags, GLuint bufobj, cl_int * err = NULL) inline
Definition at line 1848 of file cl.hpp.
View newest version in sPHENIX GitHub at line 1848 of file cl.hpp
References cl::detail::errHandler(), acts::error, and cl::detail::Wrapper< cl_mem >::object_.
cl::BufferGL::BufferGL () inline
Definition at line 1867 of file cl.hpp.
View newest version in sPHENIX GitHub at line 1867 of file cl.hpp
cl::BufferGL::BufferGL (const BufferGL & buffer) inline
Definition at line 1869 of file cl.hpp.
View newest version in sPHENIX GitHub at line 1869 of file cl.hpp
Member Function Documentation
cl_int cl::BufferGL::getObjectInfo (cl_gl_object_type * type, GLuint * gl_object_name) inline
Definition at line 1879 of file cl.hpp.
View newest version in sPHENIX GitHub at line 1879 of file cl.hpp
References cl::detail::errHandler(), and cl::detail::Wrapper< cl_mem >::object_.
BufferGL& cl::BufferGL::operator= (const BufferGL & rhs) inline
Definition at line 1871 of file cl.hpp.
View newest version in sPHENIX GitHub at line 1871 of file cl.hpp
References cl::Buffer::operator=().
The documentation for this class was generated from the following file:
JETSCAPE/blob/main/external_packages/clvisc_wrapper/include/cl.hpp