Analysis Software: pythia6/blob/master/pythiaeRHIC/pythia/pyscat.f File Reference
pyscat.f File Reference
Functions/Subroutines
subroutine pyscat
Function/Subroutine Documentation
subroutine pyscat ()
Definition at line 8 of file pyscat.f.
View newest version in sPHENIX GitHub at line 8 of file pyscat.f
References c2, i, ValueGen1::i1(), ValueGen1::i2(), ValueGen1::i3(), ValueGen1::i4(), in, j, k, Acts::detail::PhiBoundParameterLimits::max(), mint, msti, mstp, n, ngen, ngenpd, npad, npart(), p, pari, parp, phi, pt, PseudoJet::px(), PseudoJet::py(), pyangl(), pychge(), pycomp, pydat1, pydat2, pydat3, pyint1, pyint2, pyint3, pyint4, pyint5, pyjets, pymass(), pypars, pyr(), pyrobo(), pyssmt, pysubs, pywidt(), PseudoJet::pz(), v, vint, xsec, and z.