Analysis Software: CMFlashDifferencev1 Class Reference
CMFlashDifferencev1 Class Reference
Version 1 of CMFlashDifference.
#include <coresoftware/blob/master/offline/packages/trackbase/CMFlashDifferencev1.h>
Public Member Functions
CMFlashDifferencev1 ()=default
ctor
void identify (std::ostream &os=std::cout) const override
void Reset () override
Clear Event.
int isValid () const override
isValid returns non zero if object contains vailid data
PHObject * CloneMe () const override
Virtual copy constructor.
void CopyFrom (const CMFlashDifference &) override
copy content from base class
void CopyFrom (CMFlashDifference *source) override
copy content from base class
void setNclusters (unsigned int n) override
unsigned int getNclusters () const override
float getTruthPhi () const override
void setTruthPhi (float phi) override
float getRecoPhi () const override
void setRecoPhi (float phi) override
float getTruthR () const override
void setTruthR (float r) override
float getRecoR () const override
void setRecoR (float r) override
float getTruthZ () const override
void setTruthZ (float z) override
float getRecoZ () const override
void setRecoZ (float z) override
Public Member Functions inherited from CMFlashDifference
~CMFlashDifference () override
dtor
Public Member Functions inherited from PHObject
PHObject ()
ctor
~PHObject () override
dtor
virtual PHObject * clone () const final
PHObject * Clone (const char *newname="") const final
void Copy (TObject &object) const final
virtual int Integrate () const
virtual int Integrate (PHObject *)
virtual void CopyFrom (const PHObject *obj)
Protected Attributes
unsigned int m_nclusters = UINT_MAX
float m_Phi [2] = {NAN, NAN}
float m_R [2] = {NAN, NAN}
float m_Z [2] = {NAN, NAN}
Additional Inherited Members
Protected Member Functions inherited from CMFlashDifference
CMFlashDifference ()=default
Detailed Description
Version 1 of CMFlashDifference.
Definition at line 20 of file CMFlashDifferencev1.h.
View newest version in sPHENIX GitHub at line 20 of file CMFlashDifferencev1.h
Constructor & Destructor Documentation
CMFlashDifferencev1::CMFlashDifferencev1 () default
ctor
Referenced by CloneMe().
Member Function Documentation
PHObject* CMFlashDifferencev1::CloneMe () const inline override virtual
Virtual copy constructor.
Reimplemented from PHObject.
Definition at line 30 of file CMFlashDifferencev1.h.
View newest version in sPHENIX GitHub at line 30 of file CMFlashDifferencev1.h
References CMFlashDifferencev1().
void CMFlashDifferencev1::CopyFrom (const CMFlashDifference & source) override virtual
copy content from base class
Reimplemented from CMFlashDifference.
Definition at line 49 of file CMFlashDifferencev1.cc.
View newest version in sPHENIX GitHub at line 49 of file CMFlashDifferencev1.cc
References CMFlashDifference::CopyFrom(), CMFlashDifference::getNclusters(), CMFlashDifference::getRecoPhi(), CMFlashDifference::getRecoR(), CMFlashDifference::getRecoZ(), CMFlashDifference::getTruthPhi(), CMFlashDifference::getTruthR(), CMFlashDifference::getTruthZ(), setNclusters(), setRecoPhi(), setRecoR(), setRecoZ(), setTruthPhi(), setTruthR(), and setTruthZ().
void CMFlashDifferencev1::CopyFrom (CMFlashDifference * source) inline override virtual
copy content from base class
Reimplemented from CMFlashDifference.
Definition at line 36 of file CMFlashDifferencev1.h.
View newest version in sPHENIX GitHub at line 36 of file CMFlashDifferencev1.h
References CopyFrom().
Referenced by CopyFrom().
unsigned int CMFlashDifferencev1::getNclusters () const inline override virtual
Reimplemented from CMFlashDifference.
Definition at line 40 of file CMFlashDifferencev1.h.
View newest version in sPHENIX GitHub at line 40 of file CMFlashDifferencev1.h
References m_nclusters.
float CMFlashDifferencev1::getRecoPhi () const inline override virtual
Reimplemented from CMFlashDifference.
Definition at line 47 of file CMFlashDifferencev1.h.
View newest version in sPHENIX GitHub at line 47 of file CMFlashDifferencev1.h
References m_Phi.
Referenced by isValid().
float CMFlashDifferencev1::getRecoR () const inline override virtual
Reimplemented from CMFlashDifference.
Definition at line 53 of file CMFlashDifferencev1.h.
View newest version in sPHENIX GitHub at line 53 of file CMFlashDifferencev1.h
References m_R.
Referenced by isValid().
float CMFlashDifferencev1::getRecoZ () const inline override virtual
Reimplemented from CMFlashDifference.
Definition at line 59 of file CMFlashDifferencev1.h.
View newest version in sPHENIX GitHub at line 59 of file CMFlashDifferencev1.h
References m_Z.
Referenced by isValid().
float CMFlashDifferencev1::getTruthPhi () const inline override virtual
Reimplemented from CMFlashDifference.
Definition at line 44 of file CMFlashDifferencev1.h.
View newest version in sPHENIX GitHub at line 44 of file CMFlashDifferencev1.h
References m_Phi.
Referenced by isValid().
float CMFlashDifferencev1::getTruthR () const inline override virtual
Reimplemented from CMFlashDifference.
Definition at line 50 of file CMFlashDifferencev1.h.
View newest version in sPHENIX GitHub at line 50 of file CMFlashDifferencev1.h
References m_R.
Referenced by isValid().
float CMFlashDifferencev1::getTruthZ () const inline override virtual
Reimplemented from CMFlashDifference.
Definition at line 56 of file CMFlashDifferencev1.h.
View newest version in sPHENIX GitHub at line 56 of file CMFlashDifferencev1.h
References m_Z.
Referenced by isValid().
void CMFlashDifferencev1::identify (std::ostream & os = std::cout) const override virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from CMFlashDifference.
Definition at line 12 of file CMFlashDifferencev1.cc.
View newest version in sPHENIX GitHub at line 12 of file CMFlashDifferencev1.cc
References m_nclusters, m_Phi, m_R, and m_Z.
int CMFlashDifferencev1::isValid () const override virtual
isValid returns non zero if object contains vailid data
Reimplemented from CMFlashDifference.
Definition at line 33 of file CMFlashDifferencev1.cc.
View newest version in sPHENIX GitHub at line 33 of file CMFlashDifferencev1.cc
References getRecoPhi(), getRecoR(), getRecoZ(), getTruthPhi(), getTruthR(), getTruthZ(), and m_nclusters.
void CMFlashDifferencev1::Reset () inline override virtual
Clear Event.
Reimplemented from CMFlashDifference.
Definition at line 28 of file CMFlashDifferencev1.h.
View newest version in sPHENIX GitHub at line 28 of file CMFlashDifferencev1.h
void CMFlashDifferencev1::setNclusters (unsigned int n) inline override virtual
Reimplemented from CMFlashDifference.
Definition at line 39 of file CMFlashDifferencev1.h.
View newest version in sPHENIX GitHub at line 39 of file CMFlashDifferencev1.h
References m_nclusters, and n.
Referenced by CopyFrom().
void CMFlashDifferencev1::setRecoPhi (float phi) inline override virtual
Reimplemented from CMFlashDifference.
Definition at line 48 of file CMFlashDifferencev1.h.
View newest version in sPHENIX GitHub at line 48 of file CMFlashDifferencev1.h
References m_Phi, and ActsTests::PropagationDatasets::phi.
Referenced by CopyFrom().
void CMFlashDifferencev1::setRecoR (float r) inline override virtual
Reimplemented from CMFlashDifference.
Definition at line 54 of file CMFlashDifferencev1.h.
View newest version in sPHENIX GitHub at line 54 of file CMFlashDifferencev1.h
References m_R, and physmon_track_finding_ttbar::r.
Referenced by CopyFrom().
void CMFlashDifferencev1::setRecoZ (float z) inline override virtual
Reimplemented from CMFlashDifference.
Definition at line 60 of file CMFlashDifferencev1.h.
View newest version in sPHENIX GitHub at line 60 of file CMFlashDifferencev1.h
References m_Z, and physmon_track_finding_ttbar::z.
Referenced by CopyFrom().
void CMFlashDifferencev1::setTruthPhi (float phi) inline override virtual
Reimplemented from CMFlashDifference.
Definition at line 45 of file CMFlashDifferencev1.h.
View newest version in sPHENIX GitHub at line 45 of file CMFlashDifferencev1.h
References m_Phi, and ActsTests::PropagationDatasets::phi.
Referenced by CopyFrom().
void CMFlashDifferencev1::setTruthR (float r) inline override virtual
Reimplemented from CMFlashDifference.
Definition at line 51 of file CMFlashDifferencev1.h.
View newest version in sPHENIX GitHub at line 51 of file CMFlashDifferencev1.h
References m_R, and physmon_track_finding_ttbar::r.
Referenced by CopyFrom().
void CMFlashDifferencev1::setTruthZ (float z) inline override virtual
Reimplemented from CMFlashDifference.
Definition at line 57 of file CMFlashDifferencev1.h.
View newest version in sPHENIX GitHub at line 57 of file CMFlashDifferencev1.h
References m_Z, and physmon_track_finding_ttbar::z.
Referenced by CopyFrom().
Member Data Documentation
unsigned int CMFlashDifferencev1::m_nclusters = UINT_MAX protected
Definition at line 75 of file CMFlashDifferencev1.h.
View newest version in sPHENIX GitHub at line 75 of file CMFlashDifferencev1.h
Referenced by getNclusters(), identify(), isValid(), and setNclusters().
float CMFlashDifferencev1::m_Phi[2] = {NAN, NAN} protected
Definition at line 77 of file CMFlashDifferencev1.h.
View newest version in sPHENIX GitHub at line 77 of file CMFlashDifferencev1.h
Referenced by getRecoPhi(), getTruthPhi(), identify(), setRecoPhi(), and setTruthPhi().
float CMFlashDifferencev1::m_R[2] = {NAN, NAN} protected
Definition at line 78 of file CMFlashDifferencev1.h.
View newest version in sPHENIX GitHub at line 78 of file CMFlashDifferencev1.h
Referenced by getRecoR(), getTruthR(), identify(), setRecoR(), and setTruthR().
float CMFlashDifferencev1::m_Z[2] = {NAN, NAN} protected
Definition at line 79 of file CMFlashDifferencev1.h.
View newest version in sPHENIX GitHub at line 79 of file CMFlashDifferencev1.h
Referenced by getRecoZ(), getTruthZ(), identify(), setRecoZ(), and setTruthZ().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/trackbase/CMFlashDifferencev1.h
coresoftware/blob/master/offline/packages/trackbase/CMFlashDifferencev1.cc