Analysis Software: FastJetAlgo Class Reference
FastJetAlgo Class Reference
#include <coresoftware/blob/master/offline/packages/jetbase/FastJetAlgo.h>
Public Member Functions
FastJetAlgo (const FastJetOptions &options)
~FastJetAlgo () override
void identify (std::ostream &os=std::cout) override
Jet::ALGO get_algo () override
FastJetAlgo (Jet::ALGO algo, float par, int verbosity=0)
void cluster_and_fill (std::vector< Jet * > &part_in, JetContainer *jets_out) override
Public Member Functions inherited from JetAlgo
virtual ~JetAlgo ()
virtual float get_par ()
virtual std::vector< Jet * > get_jets (std::vector< Jet * >)
virtual std::map
< Jet::PROPERTY, unsigned int > & property_indices ()
Private Member Functions
std::vector< fastjet::PseudoJet > jets_to_pseudojets (std::vector< Jet * > &particles)
std::vector< fastjet::PseudoJet > cluster_jets (std::vector< fastjet::PseudoJet > &constituents)
std::vector< fastjet::PseudoJet > cluster_area_jets (std::vector< fastjet::PseudoJet > &constituents)
float calc_rhomeddens (std::vector< fastjet::PseudoJet > &constituents)
fastjet::JetDefinition get_fastjet_definition ()
fastjet::Selector get_selector ()
void first_call_init (JetContainer *_=nullptr)
Private Attributes
FastJetOptions m_opt {}
bool m_first_cluster_call { true }
Jet::PROPERTY m_zg_index { Jet::PROPERTY::no_property }
Jet::PROPERTY m_Rg_index { Jet::PROPERTY::no_property }
Jet::PROPERTY m_mu_index { Jet::PROPERTY::no_property }
Jet::PROPERTY m_area_index { Jet::PROPERTY::no_property }
fastjet::contrib::ConstituentSubtractor * cs_subtractor = nullptr
fastjet::GridMedianBackgroundEstimator * cs_bge_rho = nullptr
fastjet::Selector * cs_sel_max_pt = nullptr
fastjet::ClusterSequence * m_cluseq {nullptr}
fastjet::ClusterSequence * m_cluseqarea {nullptr}
Additional Inherited Members
Protected Member Functions inherited from JetAlgo
JetAlgo ()
Detailed Description
Definition at line 28 of file FastJetAlgo.h.
View newest version in sPHENIX GitHub at line 28 of file FastJetAlgo.h
Constructor & Destructor Documentation
FastJetAlgo::FastJetAlgo (const FastJetOptions & options)
Definition at line 39 of file FastJetAlgo.cc.
View newest version in sPHENIX GitHub at line 39 of file FastJetAlgo.cc
FastJetAlgo::~FastJetAlgo () inline override
Definition at line 32 of file FastJetAlgo.h.
View newest version in sPHENIX GitHub at line 32 of file FastJetAlgo.h
FastJetAlgo::FastJetAlgo (Jet::ALGO algo, float par, int verbosity = 0) inline
Definition at line 41 of file FastJetAlgo.h.
View newest version in sPHENIX GitHub at line 41 of file FastJetAlgo.h
References cluster_and_fill(), FastJetOptions::doSoftDrop, JetAlgo::get_jets(), JET_R, m_opt, particles, FastJetOptions::SD_beta, FastJetOptions::SD_zcut, verbosity, and VERBOSITY.
Member Function Documentation
float FastJetAlgo::calc_rhomeddens (std::vector< fastjet::PseudoJet > & constituents) private
Definition at line 148 of file FastJetAlgo.cc.
View newest version in sPHENIX GitHub at line 148 of file FastJetAlgo.cc
References FastJetOptions::etahardestcut_jetmedbkgdens, FastJetOptions::ghost_area, FastJetOptions::ghost_max_rap, FastJetOptions::jet_R, kt_algorithm, m_opt, FastJetOptions::nhardestcut_jetmedbkgdens, SelectorAbsEtaMax(), and SelectorNHardest().
Referenced by cluster_and_fill().
void FastJetAlgo::cluster_and_fill (std::vector< Jet * > & part_in, JetContainer * jets_out) override virtual
Reimplemented from JetAlgo.
Definition at line 234 of file FastJetAlgo.cc.
View newest version in sPHENIX GitHub at line 234 of file FastJetAlgo.cc
References JetContainer::add_jet(), Acts::PhysicalConstants::c, FastJetOptions::calc_area, FastJetOptions::calc_jetmedbkgdens, calc_rhomeddens(), cluster_area_jets(), cluster_jets(), mvtx_utils::comp(), cs_bge_rho, FastJetOptions::cs_calc_constsub, FastJetOptions::cs_max_eta, cs_subtractor, FastJetOptions::doSoftDrop, Acts::UnitConstants::e, first_call_init(), i, jets_to_pseudojets(), m_area_index, m_cluseq, m_cluseqarea, m_first_cluster_call, m_mu_index, m_opt, m_Rg_index, m_zg_index, testing::internal::move(), CKF_timing_vs_mu::mu, FastJetOptions::save_jet_components, FastJetOptions::SD_beta, FastJetOptions::SD_zcut, SelectorAbsEtaMax(), Jet::set_px(), JetContainer::set_rho_median(), and FastJetOptions::verbosity.
Referenced by FastJetAlgo().
std::vector< fastjet::PseudoJet > FastJetAlgo::cluster_area_jets (std::vector< fastjet::PseudoJet > & constituents) private
Definition at line 125 of file FastJetAlgo.cc.
View newest version in sPHENIX GitHub at line 125 of file FastJetAlgo.cc
References get_fastjet_definition(), get_selector(), FastJetOptions::ghost_area, FastJetOptions::ghost_max_rap, m_cluseqarea, m_opt, sorted_by_pt(), and FastJetOptions::use_jet_selection.
Referenced by cluster_and_fill().
std::vector< fastjet::PseudoJet > FastJetAlgo::cluster_jets (std::vector< fastjet::PseudoJet > & constituents) private
Definition at line 111 of file FastJetAlgo.cc.
View newest version in sPHENIX GitHub at line 111 of file FastJetAlgo.cc
References get_fastjet_definition(), get_selector(), m_cluseq, m_opt, sorted_by_pt(), and FastJetOptions::use_jet_selection.
Referenced by cluster_and_fill().
void FastJetAlgo::first_call_init (JetContainer * _ = nullptr) private
Definition at line 195 of file FastJetAlgo.cc.
View newest version in sPHENIX GitHub at line 195 of file FastJetAlgo.cc
References JetContainer::add_property(), FastJetOptions::algo, FastJetOptions::calc_area, FastJetOptions::cs_alpha, cs_bge_rho, FastJetOptions::cs_calc_constsub, FastJetOptions::cs_ghost_area, FastJetOptions::cs_max_dist, FastJetOptions::cs_max_eta, FastJetOptions::cs_max_pt, cs_sel_max_pt, cs_subtractor, physmon_track_finding_ttbar::deltaR, FastJetOptions::doSoftDrop, FastJetOptions::initialize(), FastJetOptions::jet_R, m_area_index, m_first_cluster_call, m_mu_index, m_opt, m_Rg_index, m_zg_index, JetContainer::property_index(), SelectorPtMax(), JetContainer::set_algo(), JetContainer::set_jetpar_R(), and FastJetOptions::verbosity.
Referenced by cluster_and_fill().
Jet::ALGO FastJetAlgo::get_algo () inline override virtual
Reimplemented from JetAlgo.
Definition at line 35 of file FastJetAlgo.h.
View newest version in sPHENIX GitHub at line 35 of file FastJetAlgo.h
References FastJetOptions::algo, and m_opt.
fastjet::JetDefinition FastJetAlgo::get_fastjet_definition () private
Definition at line 76 of file FastJetAlgo.cc.
View newest version in sPHENIX GitHub at line 76 of file FastJetAlgo.cc
References FastJetOptions::algo, Jet::ANTIKT, antikt_algorithm, Best, Jet::CAMBRIDGE, cambridge_algorithm, E_scheme, FastJetOptions::jet_R, Jet::KT, kt_algorithm, m_opt, and PHWHERE.
Referenced by cluster_area_jets(), and cluster_jets().
fastjet::Selector FastJetAlgo::get_selector () private
Definition at line 99 of file FastJetAlgo.cc.
View newest version in sPHENIX GitHub at line 99 of file FastJetAlgo.cc
References FastJetOptions::jet_max_eta, FastJetOptions::jet_min_pt, m_opt, SelectorAbsRapMax(), SelectorPtMin(), FastJetOptions::use_jet_max_eta, and FastJetOptions::use_jet_min_pt.
Referenced by cluster_area_jets(), and cluster_jets().
void FastJetAlgo::identify (std::ostream & os = std::cout) override virtual
Reimplemented from JetAlgo.
Definition at line 56 of file FastJetAlgo.cc.
View newest version in sPHENIX GitHub at line 56 of file FastJetAlgo.cc
References FastJetOptions::algo, Jet::ANTIKT, Jet::CAMBRIDGE, FastJetOptions::jet_R, Jet::KT, m_opt, and FastJetOptions::print().
std::vector< fastjet::PseudoJet > FastJetAlgo::jets_to_pseudojets (std::vector< Jet * > & particles) private
Definition at line 164 of file FastJetAlgo.cc.
View newest version in sPHENIX GitHub at line 164 of file FastJetAlgo.cc
References FastJetOptions::constituent_min_pt, m_opt, PHWHERE, and FastJetOptions::use_constituent_min_pt.
Referenced by cluster_and_fill().
Member Data Documentation
fastjet::GridMedianBackgroundEstimator* FastJetAlgo::cs_bge_rho = nullptr private
Definition at line 73 of file FastJetAlgo.h.
View newest version in sPHENIX GitHub at line 73 of file FastJetAlgo.h
Referenced by cluster_and_fill(), and first_call_init().
fastjet::Selector* FastJetAlgo::cs_sel_max_pt = nullptr private
Definition at line 74 of file FastJetAlgo.h.
View newest version in sPHENIX GitHub at line 74 of file FastJetAlgo.h
Referenced by first_call_init().
fastjet::contrib::ConstituentSubtractor* FastJetAlgo::cs_subtractor = nullptr private
Definition at line 72 of file FastJetAlgo.h.
View newest version in sPHENIX GitHub at line 72 of file FastJetAlgo.h
Referenced by cluster_and_fill(), and first_call_init().
Jet::PROPERTY FastJetAlgo::m_area_index { Jet::PROPERTY::no_property } private
Definition at line 60 of file FastJetAlgo.h.
View newest version in sPHENIX GitHub at line 60 of file FastJetAlgo.h
Referenced by cluster_and_fill(), and first_call_init().
fastjet::ClusterSequence* FastJetAlgo::m_cluseq {nullptr} private
Definition at line 77 of file FastJetAlgo.h.
View newest version in sPHENIX GitHub at line 77 of file FastJetAlgo.h
Referenced by cluster_and_fill(), and cluster_jets().
fastjet::ClusterSequence* FastJetAlgo::m_cluseqarea {nullptr} private
Definition at line 78 of file FastJetAlgo.h.
View newest version in sPHENIX GitHub at line 78 of file FastJetAlgo.h
Referenced by cluster_and_fill(), and cluster_area_jets().
bool FastJetAlgo::m_first_cluster_call { true } private
Definition at line 54 of file FastJetAlgo.h.
View newest version in sPHENIX GitHub at line 54 of file FastJetAlgo.h
Referenced by cluster_and_fill(), and first_call_init().
Jet::PROPERTY FastJetAlgo::m_mu_index { Jet::PROPERTY::no_property } private
Definition at line 59 of file FastJetAlgo.h.
View newest version in sPHENIX GitHub at line 59 of file FastJetAlgo.h
Referenced by cluster_and_fill(), and first_call_init().
FastJetOptions FastJetAlgo::m_opt {} private
Definition at line 53 of file FastJetAlgo.h.
View newest version in sPHENIX GitHub at line 53 of file FastJetAlgo.h
Referenced by calc_rhomeddens(), cluster_and_fill(), cluster_area_jets(), cluster_jets(), FastJetAlgo(), first_call_init(), get_algo(), get_fastjet_definition(), get_selector(), identify(), and jets_to_pseudojets().
Jet::PROPERTY FastJetAlgo::m_Rg_index { Jet::PROPERTY::no_property } private
Definition at line 58 of file FastJetAlgo.h.
View newest version in sPHENIX GitHub at line 58 of file FastJetAlgo.h
Referenced by cluster_and_fill(), and first_call_init().
Jet::PROPERTY FastJetAlgo::m_zg_index { Jet::PROPERTY::no_property } private
Definition at line 57 of file FastJetAlgo.h.
View newest version in sPHENIX GitHub at line 57 of file FastJetAlgo.h
Referenced by cluster_and_fill(), and first_call_init().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/jetbase/FastJetAlgo.h
coresoftware/blob/master/offline/packages/jetbase/FastJetAlgo.cc