Analysis Software: Acts::StraightLineStepper::State Struct Reference
Acts::StraightLineStepper::State Struct Reference
#include <acts/blob/sPHENIX/Core/include/Acts/Propagator/StraightLineStepper.hpp>
Public Member Functions
State ()=delete
Delete the default constructor.
template<typename parameters_t >
State (std::reference_wrapper< const GeometryContext > gctx, std::reference_wrapper< const MagneticFieldContext >, const parameters_t &par, NavigationDirection ndir=forward, double ssize=std::numeric_limits< double >::max(), double stolerance=s_onSurfaceTolerance)
Public Attributes
BoundToFreeMatrix jacToGlobal = BoundToFreeMatrix::Zero()
Jacobian from local to the global frame.
FreeMatrix jacTransport = FreeMatrix::Identity()
Pure transport jacobian part from runge kutta integration.
Jacobian jacobian = Jacobian::Identity()
The full jacobian of the transport entire transport.
FreeVector derivative = FreeVector::Zero()
The propagation derivative.
bool covTransport = false
Boolean to indiciate if you need covariance transport.
Covariance cov = Covariance::Zero()
Vector3D pos = Vector3D(0., 0., 0.)
Global particle position.
Vector3D dir = Vector3D(1., 0., 0.)
Momentum direction (normalized)
double p = 0.
Momentum.
double q = 0.
Save the charge: neutral as default for SL stepper.
double t = 0.
Propagated time.
NavigationDirection navDir
Navigation direction, this is needed for searching.
double pathAccumulated = 0.
accummulated path length state
ConstrainedStep stepSize = std::numeric_limits<double>::max()
adaptive step size of the runge-kutta integration
double previousStepSize = 0.
double tolerance = s_onSurfaceTolerance
The tolerance for the stepping.
std::reference_wrapper< const
GeometryContext > geoContext
Detailed Description
State for track parameter propagation
Definition at line 46 of file StraightLineStepper.hpp.
View newest version in sPHENIX GitHub at line 46 of file StraightLineStepper.hpp
Constructor & Destructor Documentation
Acts::StraightLineStepper::State::State () delete
Delete the default constructor.
template<typename parameters_t > Acts::StraightLineStepper::State::State (std::reference_wrapper< const GeometryContext > gctx, std::reference_wrapper< const MagneticFieldContext > , const parameters_t & par, NavigationDirection ndir = forward, double ssize = std::numeric_limits<double>::max(), double stolerance = s_onSurfaceTolerance) inline explicit
Constructor from the initial track parameters
Template Parameters
parameters_t the Type of the track parameters
Parameters
[in] gctx is the context object for the geometery
[in] mctx is the context object for the magnetic field
[in] par The track parameters at start
[in] ndir is the navigation direction
[in] ssize is the (absolute) maximum step size
[in] stolerance is the stepping tolerance
Definition at line 61 of file StraightLineStepper.hpp.
View newest version in sPHENIX GitHub at line 61 of file StraightLineStepper.hpp
References cov, covTransport, dir, jacToGlobal, and pos.
Member Data Documentation
Covariance Acts::StraightLineStepper::State::cov = Covariance::Zero()
Definition at line 100 of file StraightLineStepper.hpp.
View newest version in sPHENIX GitHub at line 100 of file StraightLineStepper.hpp
Referenced by Acts::Test::BOOST_AUTO_TEST_CASE(), Acts::StraightLineStepper::boundState(), Acts::StraightLineStepper::covarianceTransport(), Acts::StraightLineStepper::curvilinearState(), State(), and Acts::StraightLineStepper::update().
bool Acts::StraightLineStepper::State::covTransport = false
Boolean to indiciate if you need covariance transport.
Definition at line 99 of file StraightLineStepper.hpp.
View newest version in sPHENIX GitHub at line 99 of file StraightLineStepper.hpp
Referenced by Acts::Test::BOOST_AUTO_TEST_CASE(), Acts::StraightLineStepper::boundState(), Acts::StraightLineStepper::curvilinearState(), and State().
FreeVector Acts::StraightLineStepper::State::derivative = FreeVector::Zero()
The propagation derivative.
Definition at line 96 of file StraightLineStepper.hpp.
View newest version in sPHENIX GitHub at line 96 of file StraightLineStepper.hpp
Referenced by Acts::Test::BOOST_AUTO_TEST_CASE(), Acts::StraightLineStepper::boundState(), Acts::StraightLineStepper::covarianceTransport(), Acts::StraightLineStepper::curvilinearState(), and Acts::StraightLineStepper::resetState().
Vector3D Acts::StraightLineStepper::State::dir = Vector3D(1., 0., 0.)
Momentum direction (normalized)
Definition at line 106 of file StraightLineStepper.hpp.
View newest version in sPHENIX GitHub at line 106 of file StraightLineStepper.hpp
Referenced by Acts::Test::BOOST_AUTO_TEST_CASE(), Acts::StraightLineStepper::boundState(), Acts::StraightLineStepper::covarianceTransport(), Acts::StraightLineStepper::curvilinearState(), Acts::StraightLineStepper::direction(), State(), and Acts::StraightLineStepper::update().
std::reference_wrapper<const GeometryContext> Acts::StraightLineStepper::State::geoContext
Definition at line 133 of file StraightLineStepper.hpp.
View newest version in sPHENIX GitHub at line 133 of file StraightLineStepper.hpp
Referenced by Acts::Test::BOOST_AUTO_TEST_CASE(), Acts::StraightLineStepper::boundState(), Acts::StraightLineStepper::covarianceTransport(), and Acts::StraightLineStepper::resetState().
Jacobian Acts::StraightLineStepper::State::jacobian = Jacobian::Identity()
The full jacobian of the transport entire transport.
Definition at line 93 of file StraightLineStepper.hpp.
View newest version in sPHENIX GitHub at line 93 of file StraightLineStepper.hpp
Referenced by Acts::StraightLineStepper::boundState(), Acts::StraightLineStepper::covarianceTransport(), Acts::StraightLineStepper::curvilinearState(), and Acts::StraightLineStepper::resetState().
BoundToFreeMatrix Acts::StraightLineStepper::State::jacToGlobal = BoundToFreeMatrix::Zero()
Jacobian from local to the global frame.
Definition at line 87 of file StraightLineStepper.hpp.
View newest version in sPHENIX GitHub at line 87 of file StraightLineStepper.hpp
Referenced by Acts::Test::BOOST_AUTO_TEST_CASE(), Acts::StraightLineStepper::boundState(), Acts::StraightLineStepper::covarianceTransport(), Acts::StraightLineStepper::curvilinearState(), Acts::StraightLineStepper::resetState(), and State().
FreeMatrix Acts::StraightLineStepper::State::jacTransport = FreeMatrix::Identity()
Pure transport jacobian part from runge kutta integration.
Definition at line 90 of file StraightLineStepper.hpp.
View newest version in sPHENIX GitHub at line 90 of file StraightLineStepper.hpp
Referenced by Acts::Test::BOOST_AUTO_TEST_CASE(), Acts::StraightLineStepper::boundState(), Acts::StraightLineStepper::covarianceTransport(), Acts::StraightLineStepper::curvilinearState(), and Acts::StraightLineStepper::resetState().
NavigationDirection Acts::StraightLineStepper::State::navDir
Navigation direction, this is needed for searching.
Definition at line 118 of file StraightLineStepper.hpp.
View newest version in sPHENIX GitHub at line 118 of file StraightLineStepper.hpp
Referenced by Acts::Test::BOOST_AUTO_TEST_CASE(), and Acts::StraightLineStepper::resetState().
double Acts::StraightLineStepper::State::p = 0.
Momentum.
Definition at line 109 of file StraightLineStepper.hpp.
View newest version in sPHENIX GitHub at line 109 of file StraightLineStepper.hpp
Referenced by Acts::Test::BOOST_AUTO_TEST_CASE(), Acts::StraightLineStepper::boundState(), Acts::StraightLineStepper::covarianceTransport(), Acts::StraightLineStepper::curvilinearState(), Acts::StraightLineStepper::momentum(), and Acts::StraightLineStepper::update().
double Acts::StraightLineStepper::State::pathAccumulated = 0.
accummulated path length state
Definition at line 121 of file StraightLineStepper.hpp.
View newest version in sPHENIX GitHub at line 121 of file StraightLineStepper.hpp
Referenced by Acts::Test::BOOST_AUTO_TEST_CASE(), Acts::StraightLineStepper::boundState(), Acts::StraightLineStepper::curvilinearState(), and Acts::StraightLineStepper::resetState().
Vector3D Acts::StraightLineStepper::State::pos = Vector3D(0., 0., 0.)
Global particle position.
Definition at line 103 of file StraightLineStepper.hpp.
View newest version in sPHENIX GitHub at line 103 of file StraightLineStepper.hpp
Referenced by Acts::Test::BOOST_AUTO_TEST_CASE(), Acts::StraightLineStepper::boundState(), Acts::StraightLineStepper::covarianceTransport(), Acts::StraightLineStepper::curvilinearState(), Acts::StraightLineStepper::position(), State(), and Acts::StraightLineStepper::update().
double Acts::StraightLineStepper::State::previousStepSize = 0.
Definition at line 127 of file StraightLineStepper.hpp.
View newest version in sPHENIX GitHub at line 127 of file StraightLineStepper.hpp
Referenced by Acts::Test::BOOST_AUTO_TEST_CASE(), and Acts::StraightLineStepper::setStepSize().
double Acts::StraightLineStepper::State::q = 0.
Save the charge: neutral as default for SL stepper.
Definition at line 112 of file StraightLineStepper.hpp.
View newest version in sPHENIX GitHub at line 112 of file StraightLineStepper.hpp
Referenced by Acts::Test::BOOST_AUTO_TEST_CASE(), Acts::StraightLineStepper::boundState(), Acts::StraightLineStepper::charge(), Acts::StraightLineStepper::covarianceTransport(), and Acts::StraightLineStepper::curvilinearState().
ConstrainedStep Acts::StraightLineStepper::State::stepSize = std::numeric_limits<double>::max()
adaptive step size of the runge-kutta integration
Definition at line 124 of file StraightLineStepper.hpp.
View newest version in sPHENIX GitHub at line 124 of file StraightLineStepper.hpp
Referenced by Acts::Test::BOOST_AUTO_TEST_CASE(), Acts::StraightLineStepper::outputStepSize(), Acts::StraightLineStepper::releaseStepSize(), Acts::StraightLineStepper::resetState(), and Acts::StraightLineStepper::setStepSize().
double Acts::StraightLineStepper::State::t = 0.
Propagated time.
Definition at line 115 of file StraightLineStepper.hpp.
View newest version in sPHENIX GitHub at line 115 of file StraightLineStepper.hpp
Referenced by Acts::Test::BOOST_AUTO_TEST_CASE(), Acts::StraightLineStepper::boundState(), Acts::StraightLineStepper::covarianceTransport(), Acts::StraightLineStepper::curvilinearState(), Acts::StraightLineStepper::time(), and Acts::StraightLineStepper::update().
double Acts::StraightLineStepper::State::tolerance = s_onSurfaceTolerance
The tolerance for the stepping.
Definition at line 130 of file StraightLineStepper.hpp.
View newest version in sPHENIX GitHub at line 130 of file StraightLineStepper.hpp
Referenced by Acts::Test::BOOST_AUTO_TEST_CASE().
The documentation for this struct was generated from the following file:
acts/blob/sPHENIX/Core/include/Acts/Propagator/StraightLineStepper.hpp