Analysis Software: ActsExamples::SeedingPerformanceWriter Exception Reference
ActsExamples::SeedingPerformanceWriter Exception Reference final
#include <acts/blob/sPHENIX/Examples/Io/Performance/ActsExamples/Io/Performance/SeedingPerformanceWriter.hpp>
Classes
struct Config
Public Types
using HitParticlesMap = ActsExamples::IndexMultimap< ActsFatras::Barcode >
Public Member Functions
SeedingPerformanceWriter (Config config, Acts::Logging::Level level)
~SeedingPerformanceWriter () override
ProcessCode finalize () override
Finalize plots.
const Config & config () const
Get readonly access to the config parameters.
Public Member Functions inherited from ActsExamples::WriterT< SimSeedContainer >
WriterT (std::string objectName, std::string writerName, Acts::Logging::Level level)
std::string name () const override
Provide the name of the writer.
ProcessCode write (const AlgorithmContext &context) override
Read the object and call the type-specific member function.
ProcessCode finalize () override
No-op default implementation.
Public Member Functions inherited from ActsExamples::IWriter
ProcessCode internalExecute (const AlgorithmContext &context) final
ProcessCode initialize () override
Fulfil the algorithm interface.
Public Member Functions inherited from ActsExamples::SequenceElement
virtual ~SequenceElement ()=default
const std::vector< const
DataHandleBase * > & writeHandles () const
const std::vector< const
DataHandleBase * > & readHandles () const
Private Member Functions
ProcessCode writeT (const AlgorithmContext &ctx, const SimSeedContainer &seeds) override
Private Attributes
Config m_cfg
std::mutex m_writeMutex
Mutex used to protect multi-threaded writes.
TFile * m_outputFile {nullptr}
EffPlotTool m_effPlotTool
Plot tool for efficiency.
EffPlotTool::EffPlotCache m_effPlotCache
DuplicationPlotTool m_duplicationPlotTool
Plot tool for duplication rate.
DuplicationPlotTool::DuplicationPlotCache m_duplicationPlotCache {}
size_t m_nTotalSeeds = 0
size_t m_nTotalMatchedSeeds = 0
size_t m_nTotalParticles = 0
size_t m_nTotalMatchedParticles = 0
size_t m_nTotalDuplicatedParticles = 0
ReadDataHandle
< SimParticleContainer > m_inputParticles {this, "InputParticles"}
ReadDataHandle< HitParticlesMap > m_inputMeasurementParticlesMap
Additional Inherited Members
Protected Member Functions inherited from ActsExamples::WriterT< SimSeedContainer >
const Acts::Logger & logger () const
Detailed Description
Definition at line 35 of file SeedingPerformanceWriter.hpp.
View newest version in sPHENIX GitHub at line 35 of file SeedingPerformanceWriter.hpp
Member Typedef Documentation
using ActsExamples::SeedingPerformanceWriter::HitParticlesMap = ActsExamples::IndexMultimap<ActsFatras::Barcode>
Definition at line 37 of file SeedingPerformanceWriter.hpp.
View newest version in sPHENIX GitHub at line 37 of file SeedingPerformanceWriter.hpp
Constructor & Destructor Documentation
ActsExamples::SeedingPerformanceWriter::SeedingPerformanceWriter (Config config, Acts::Logging::Level level)
Construct from configuration and log level.
Parameters
config The configuration
level
Definition at line 30 of file SeedingPerformanceWriter.cpp.
View newest version in sPHENIX GitHub at line 30 of file SeedingPerformanceWriter.cpp
References ActsExamples::EffPlotTool::book(), ActsExamples::DuplicationPlotTool::book(), ActsExamples::SeedingPerformanceWriter::Config::fileMode, ActsExamples::SeedingPerformanceWriter::Config::filePath, ActsExamples::ReadDataHandle< T >::initialize(), ActsExamples::SeedingPerformanceWriter::Config::inputMeasurementParticlesMap, ActsExamples::SeedingPerformanceWriter::Config::inputParticles, m_cfg, m_duplicationPlotCache, m_duplicationPlotTool, m_effPlotCache, m_effPlotTool, m_inputMeasurementParticlesMap, m_inputParticles, m_outputFile, and path.
ActsExamples::SeedingPerformanceWriter::~SeedingPerformanceWriter () override
Definition at line 63 of file SeedingPerformanceWriter.cpp.
View newest version in sPHENIX GitHub at line 63 of file SeedingPerformanceWriter.cpp
Member Function Documentation
const Config& ActsExamples::SeedingPerformanceWriter::config () const inline
Get readonly access to the config parameters.
Definition at line 66 of file SeedingPerformanceWriter.hpp.
View newest version in sPHENIX GitHub at line 66 of file SeedingPerformanceWriter.hpp
References m_cfg.
ActsExamples::ProcessCode ActsExamples::SeedingPerformanceWriter::finalize () override virtual
Finalize plots.
Implements ActsExamples::SequenceElement.
Definition at line 71 of file SeedingPerformanceWriter.cpp.
View newest version in sPHENIX GitHub at line 71 of file SeedingPerformanceWriter.cpp
References ACTS_DEBUG, ACTS_INFO, and SUCCESS.
ActsExamples::ProcessCode ActsExamples::SeedingPerformanceWriter::writeT (const AlgorithmContext & context, const SimSeedContainer & t) override private virtual
Type-specific write function implementation this method is implemented in the user implementation
Parameters
[in] context is the algorithm context that guarantees event consistency
Template Parameters
[in] is the templated collection to be written
Implements ActsExamples::WriterT< SimSeedContainer >.
Definition at line 107 of file SeedingPerformanceWriter.cpp.
View newest version in sPHENIX GitHub at line 107 of file SeedingPerformanceWriter.cpp
References ACTS_DEBUG, ActsExamples::identifyContributingParticles(), it, particle, particles, seed, ActsExamples::seedToPrototrack(), SUCCESS, and physmon_ckf_tracking::u.
Member Data Documentation
Config ActsExamples::SeedingPerformanceWriter::m_cfg private
Definition at line 72 of file SeedingPerformanceWriter.hpp.
View newest version in sPHENIX GitHub at line 72 of file SeedingPerformanceWriter.hpp
Referenced by config(), and SeedingPerformanceWriter().
DuplicationPlotTool::DuplicationPlotCache ActsExamples::SeedingPerformanceWriter::m_duplicationPlotCache {} private
Definition at line 81 of file SeedingPerformanceWriter.hpp.
View newest version in sPHENIX GitHub at line 81 of file SeedingPerformanceWriter.hpp
Referenced by SeedingPerformanceWriter().
DuplicationPlotTool ActsExamples::SeedingPerformanceWriter::m_duplicationPlotTool private
Plot tool for duplication rate.
Definition at line 80 of file SeedingPerformanceWriter.hpp.
View newest version in sPHENIX GitHub at line 80 of file SeedingPerformanceWriter.hpp
Referenced by SeedingPerformanceWriter().
EffPlotTool::EffPlotCache ActsExamples::SeedingPerformanceWriter::m_effPlotCache private
Definition at line 78 of file SeedingPerformanceWriter.hpp.
View newest version in sPHENIX GitHub at line 78 of file SeedingPerformanceWriter.hpp
Referenced by SeedingPerformanceWriter().
EffPlotTool ActsExamples::SeedingPerformanceWriter::m_effPlotTool private
Plot tool for efficiency.
Definition at line 77 of file SeedingPerformanceWriter.hpp.
View newest version in sPHENIX GitHub at line 77 of file SeedingPerformanceWriter.hpp
Referenced by SeedingPerformanceWriter().
ReadDataHandle<HitParticlesMap> ActsExamples::SeedingPerformanceWriter::m_inputMeasurementParticlesMap private
Initial value:
{
      this, "InputMeasurementParticlesMaps"}
Definition at line 90 of file SeedingPerformanceWriter.hpp.
View newest version in sPHENIX GitHub at line 90 of file SeedingPerformanceWriter.hpp
Referenced by SeedingPerformanceWriter().
ReadDataHandle<SimParticleContainer> ActsExamples::SeedingPerformanceWriter::m_inputParticles {this, "InputParticles"} private
Definition at line 89 of file SeedingPerformanceWriter.hpp.
View newest version in sPHENIX GitHub at line 89 of file SeedingPerformanceWriter.hpp
Referenced by SeedingPerformanceWriter().
size_t ActsExamples::SeedingPerformanceWriter::m_nTotalDuplicatedParticles = 0 private
Definition at line 87 of file SeedingPerformanceWriter.hpp.
View newest version in sPHENIX GitHub at line 87 of file SeedingPerformanceWriter.hpp
size_t ActsExamples::SeedingPerformanceWriter::m_nTotalMatchedParticles = 0 private
Definition at line 86 of file SeedingPerformanceWriter.hpp.
View newest version in sPHENIX GitHub at line 86 of file SeedingPerformanceWriter.hpp
size_t ActsExamples::SeedingPerformanceWriter::m_nTotalMatchedSeeds = 0 private
Definition at line 84 of file SeedingPerformanceWriter.hpp.
View newest version in sPHENIX GitHub at line 84 of file SeedingPerformanceWriter.hpp
size_t ActsExamples::SeedingPerformanceWriter::m_nTotalParticles = 0 private
Definition at line 85 of file SeedingPerformanceWriter.hpp.
View newest version in sPHENIX GitHub at line 85 of file SeedingPerformanceWriter.hpp
size_t ActsExamples::SeedingPerformanceWriter::m_nTotalSeeds = 0 private
Definition at line 83 of file SeedingPerformanceWriter.hpp.
View newest version in sPHENIX GitHub at line 83 of file SeedingPerformanceWriter.hpp
TFile* ActsExamples::SeedingPerformanceWriter::m_outputFile {nullptr} private
Definition at line 75 of file SeedingPerformanceWriter.hpp.
View newest version in sPHENIX GitHub at line 75 of file SeedingPerformanceWriter.hpp
Referenced by SeedingPerformanceWriter().
std::mutex ActsExamples::SeedingPerformanceWriter::m_writeMutex private
Mutex used to protect multi-threaded writes.
Definition at line 74 of file SeedingPerformanceWriter.hpp.
View newest version in sPHENIX GitHub at line 74 of file SeedingPerformanceWriter.hpp
The documentation for this exception was generated from the following files:
acts/blob/sPHENIX/Examples/Io/Performance/ActsExamples/Io/Performance/SeedingPerformanceWriter.hpp
acts/blob/sPHENIX/Examples/Io/Performance/ActsExamples/Io/Performance/SeedingPerformanceWriter.cpp