Analysis Software: Acts::Svg::View Namespace Reference
Acts::Svg::View Namespace Reference
Functions
static actsvg::svg::object xy (const ProtoDetector &detector, const std::string &identification)
static actsvg::svg::object zr (const ProtoDetector &detector, const std::string &identification)
static actsvg::svg::object xy (const ProtoVolume &volume, const std::string &identification, bool displayPortals=true)
static actsvg::svg::object zr (const ProtoVolume &volume, const std::string &identification, bool displayPortals=true)
static actsvg::svg::object xy (const ProtoIndexedSurfaceGrid &pIndexGrid, const std::string &identification)
static actsvg::svg::object zphi (const ProtoIndexedSurfaceGrid &pIndexGrid, const std::string &identification)
static actsvg::svg::object xy (const ProtoPortal &portal, const std::string &identification)
static actsvg::svg::object zr (const ProtoPortal &portal, const std::string &identification)
static actsvg::svg::object xy (const ProtoSurface &pSurface, const std::string &identification)
static actsvg::svg::object zr (const ProtoSurface &pSurface, const std::string &identification)
static actsvg::svg::object zphi (const ProtoSurface &pSurface, const std::string &identification)
static actsvg::svg::object zrphi (const ProtoSurface &pSurface, const std::string &identification)
Function Documentation
static actsvg::svg::object Acts::Svg::View::xy (const ProtoSurface & pSurface, const std::string & identification) inline static
Convert into an acts::svg::object with an x-y view
Parameters
pSurface is the proto object
identification is the to be translated id_ for actsvg
Returns
an svg object that can be written out directly to disc
Definition at line 55 of file SurfaceSvgConverter.hpp.
View newest version in sPHENIX GitHub at line 55 of file SurfaceSvgConverter.hpp
References writeMapConfig::surface.
static actsvg::svg::object Acts::Svg::View::xy (const ProtoDetector & detector, const std::string & identification) inline static
Convert into an acts::svg::object with an XY view
Parameters
detector is the detector (proto representation)
identification is the to be translated id_ for actsvg
Returns
an svg object that can be written out directly to disc
Definition at line 57 of file DetectorSvgConverter.hpp.
View newest version in sPHENIX GitHub at line 57 of file DetectorSvgConverter.hpp
Referenced by Acts::Test::BOOST_AUTO_TEST_CASE(), BOOST_AUTO_TEST_CASE(), trento::Event::compute_observables(), Acts::Svg::SurfaceArrayConverter::convert(), DD4hepTestsHelper::createTransform(), EpInfo::EpInfo(), EmcCluster::GetCorrPos(), EmcCluster::GetE4(), EmcCluster::GetE9(), EmcCluster::GetECore(), EmcCluster::GetECoreCorrected(), cumulant_generating::interp_dsdy(), main(), plot_residuals(), RawClusterBuilderTemplate::process_event(), PHCosmicSiliconPropagator::set_dca_xy_cut(), xy(), and zphi().
static actsvg::svg::object Acts::Svg::View::xy (const ProtoVolume & volume, const std::string & identification, bool displayPortals = true) inline static
Convert into an acts::svg::object with an XY view
Parameters
volume is the DetectorVolume (proto representation)
identification is the to be translated id_ for actsvg
displayPortals is a directory whether portals should be displayed
Returns
an svg object that can be written out directly to disc
Definition at line 68 of file DetectorVolumeSvgConverter.hpp.
View newest version in sPHENIX GitHub at line 68 of file DetectorVolumeSvgConverter.hpp
static actsvg::svg::object Acts::Svg::View::xy (const ProtoPortal & portal, const std::string & identification) inline static
Convert into an acts::svg::object with an XY view
Parameters
portal is the DetectorVolume portal (proto representation)
identification is the to be translated id_ for actsvg
Returns
an svg object that can be written out directly to disc
Definition at line 70 of file PortalSvgConverter.hpp.
View newest version in sPHENIX GitHub at line 70 of file PortalSvgConverter.hpp
static actsvg::svg::object Acts::Svg::View::xy (const ProtoIndexedSurfaceGrid & pIndexGrid, const std::string & identification) inline static
Convert into an acts::svg::object with an XY view
Parameters
pIndexGrid is the proto object
identification is the to be translated id_ for actsvg
Returns
an svg object that can be written out directly
Definition at line 270 of file IndexedSurfacesSvgConverter.hpp.
View newest version in sPHENIX GitHub at line 270 of file IndexedSurfacesSvgConverter.hpp
References Acts::enumerate(), grid(), physmon_simulation::s, to_string(), Acts::Test::transform, physmon_ckf_tracking::u, xmax, xy(), and zrphi().
static actsvg::svg::object Acts::Svg::View::zphi (const ProtoSurface & pSurface, const std::string & identification) inline static
Convert into an acts::svg::object with an z-phi view
Parameters
pSurface is the proto object
identification is the to be translated id_ for actsvg
Returns
an svg object that can be written out directly to disc
Definition at line 79 of file SurfaceSvgConverter.hpp.
View newest version in sPHENIX GitHub at line 79 of file SurfaceSvgConverter.hpp
References writeMapConfig::surface.
static actsvg::svg::object Acts::Svg::View::zphi (const ProtoIndexedSurfaceGrid & pIndexGrid, const std::string & identification) inline static
Fake zphi method, delegate to xy
Parameters
pIndexGrid is the proto object
identification is the to be translated id_ for actsvg
Note
this works, because the actual display at the end is 2D in an x-y plane and the parameters are appropriately defined
Returns
an svg object that can be written out directly
Definition at line 332 of file IndexedSurfacesSvgConverter.hpp.
View newest version in sPHENIX GitHub at line 332 of file IndexedSurfacesSvgConverter.hpp
References xy().
Referenced by BOOST_AUTO_TEST_CASE(), and cluster_resolution().
static actsvg::svg::object Acts::Svg::View::zr (const ProtoSurface & pSurface, const std::string & identification) inline static
Convert into an acts::svg::object with an z-r view
Parameters
pSurface is the proto object
identification is the to be translated id_ for actsvg
Returns
an svg object that can be written out directly to disc
Definition at line 67 of file SurfaceSvgConverter.hpp.
View newest version in sPHENIX GitHub at line 67 of file SurfaceSvgConverter.hpp
References writeMapConfig::surface.
static actsvg::svg::object Acts::Svg::View::zr (const ProtoDetector & detector, const std::string & identification) inline static
Convert into an acts::svg::object with an Zr view
Parameters
detector is the detector (proto representation)
identification is the to be translated id_ for actsvg
Returns
an svg object that can be written out directly to disc
Definition at line 69 of file DetectorSvgConverter.hpp.
View newest version in sPHENIX GitHub at line 69 of file DetectorSvgConverter.hpp
Referenced by BOOST_AUTO_TEST_CASE().
static actsvg::svg::object Acts::Svg::View::zr (const ProtoPortal & portal, const std::string & identification) inline static
Convert into an acts::svg::object with an Zr view
Parameters
portal is the DetectorVolume portal (proto representation)
identification is the to be translated id_ for actsvg
Returns
an svg object that can be written out directly to disc
Definition at line 82 of file PortalSvgConverter.hpp.
View newest version in sPHENIX GitHub at line 82 of file PortalSvgConverter.hpp
static actsvg::svg::object Acts::Svg::View::zr (const ProtoVolume & volume, const std::string & identification, bool displayPortals = true) inline static
Convert into an acts::svg::object with an Zr view
Parameters
volume is the DetectorVolume (proto representation)
identification is the to be translated id_ for actsvg
displayPortals is a directory whether portals should be displayed
Returns
an svg object that can be written out directly to disc
Definition at line 83 of file DetectorVolumeSvgConverter.hpp.
View newest version in sPHENIX GitHub at line 83 of file DetectorVolumeSvgConverter.hpp
static actsvg::svg::object Acts::Svg::View::zrphi (const ProtoSurface & pSurface, const std::string & identification) inline static
Convert into an acts::svg::object with an z-rphi view
Parameters
pSurface is the proto object
identification is the to be translated id_ for actsvg
Note
it captures the radii[0u] element for plotting
Returns
an svg object that can be written out directly to disc
Definition at line 93 of file SurfaceSvgConverter.hpp.
View newest version in sPHENIX GitHub at line 93 of file SurfaceSvgConverter.hpp
References writeMapConfig::surface, and physmon_ckf_tracking::u.
Referenced by xy().