Analysis Software: upload.GitVCS Class Reference
upload.GitVCS Class Reference
Public Member Functions
def __init__
def GenerateDiff
def GetUnknownFiles
def GetBaseFile
def __init__
def GenerateDiff
def GetUnknownFiles
def GetBaseFile
Public Member Functions inherited from upload.VersionControlSystem
def __init__
def GenerateDiff
def GetUnknownFiles
def CheckForUnknownFiles
def GetBaseFile
def GetBaseFiles
def UploadBaseFiles
def IsImage
def __init__
def GenerateDiff
def GetUnknownFiles
def CheckForUnknownFiles
def GetBaseFile
def GetBaseFiles
def UploadBaseFiles
def IsImage
Public Attributes
base_hashes
Public Attributes inherited from upload.VersionControlSystem
options
Detailed Description
Implementation of the VersionControlSystem interface for Git.
Definition at line 985 of file upload.py.
View newest version in sPHENIX GitHub at line 985 of file upload.py
Constructor & Destructor Documentation
def upload.GitVCS.__init__ (self, options)
Definition at line 988 of file upload.py.
View newest version in sPHENIX GitHub at line 988 of file upload.py
Referenced by upload.GitVCS.__init__().
def upload.GitVCS.__init__ (self, options)
Definition at line 988 of file upload.py.
View newest version in sPHENIX GitHub at line 988 of file upload.py
References upload.GitVCS.__init__(), and upload.GitVCS.base_hashes.
Member Function Documentation
def upload.GitVCS.GenerateDiff (self, extra_args)
Definition at line 993 of file upload.py.
View newest version in sPHENIX GitHub at line 993 of file upload.py
References upload.GitVCS.base_hashes, upload.ErrorExit(), join(), and upload.RunShell().
Referenced by upload.GitVCS.GenerateDiff().
def upload.GitVCS.GenerateDiff (self, extra_args)
Definition at line 993 of file upload.py.
View newest version in sPHENIX GitHub at line 993 of file upload.py
References upload.GitVCS.base_hashes, upload.ErrorExit(), upload.GitVCS.GenerateDiff(), join(), and upload.RunShell().
def upload.GitVCS.GetBaseFile (self, filename)
Definition at line 1026 of file upload.py.
View newest version in sPHENIX GitHub at line 1026 of file upload.py
References upload.GitVCS.base_hashes, upload.ErrorExit(), upload.GitVCS.GetBaseFile(), and upload.RunShellWithReturnCode().
def upload.GitVCS.GetBaseFile (self, filename)
Definition at line 1026 of file upload.py.
View newest version in sPHENIX GitHub at line 1026 of file upload.py
References upload.GitVCS.base_hashes, upload.ErrorExit(), and upload.RunShellWithReturnCode().
Referenced by upload.GitVCS.GetBaseFile().
def upload.GitVCS.GetUnknownFiles (self)
Definition at line 1021 of file upload.py.
View newest version in sPHENIX GitHub at line 1021 of file upload.py
References upload.RunShell().
Referenced by upload.GitVCS.GetUnknownFiles().
def upload.GitVCS.GetUnknownFiles (self)
Definition at line 1021 of file upload.py.
View newest version in sPHENIX GitHub at line 1021 of file upload.py
References upload.GitVCS.GetUnknownFiles(), and upload.RunShell().
Member Data Documentation
upload.GitVCS.base_hashes
Definition at line 991 of file upload.py.
View newest version in sPHENIX GitHub at line 991 of file upload.py
Referenced by upload.GitVCS.__init__(), upload.GitVCS.GenerateDiff(), and upload.GitVCS.GetBaseFile().
The documentation for this class was generated from the following files:
JETSCAPE/blob/main/external_packages/googletest/googlemock/scripts/upload.py
JETSCAPE/blob/main/external_packages/googletest/googletest/scripts/upload.py