Analysis Software: ActsExamples::TruthSeedingAlgorithm Exception Reference
ActsExamples::TruthSeedingAlgorithm Exception Reference final
Construct track seeds from particles.
#include <acts/blob/sPHENIX/Examples/Algorithms/TruthTracking/ActsExamples/TruthTracking/TruthSeedingAlgorithm.hpp>
Classes
struct Config
Public Types
using HitParticlesMap = IndexMultimap< ActsFatras::Barcode >
Public Member Functions
TruthSeedingAlgorithm (Config cfg, Acts::Logging::Level lvl)
ProcessCode execute (const AlgorithmContext &ctx) const override
const Config & config () const
Const access to the config.
Public Member Functions inherited from ActsExamples::IAlgorithm
IAlgorithm (std::string name, Acts::Logging::Level level=Acts::Logging::INFO)
std::string name () const override
The algorithm name.
ProcessCode internalExecute (const AlgorithmContext &context) final
ProcessCode initialize () override
Initialize the algorithm.
ProcessCode finalize () override
Finalize the algorithm.
Private Attributes
Config m_cfg
ReadDataHandle
< SimParticleContainer > m_inputParticles {this, "InputParticles"}
ReadDataHandle< HitParticlesMap > m_inputMeasurementParticlesMap
std::vector< std::unique_ptr
< ReadDataHandle
< SimSpacePointContainer > > > m_inputSpacePoints {}
WriteDataHandle
< SimParticleContainer > m_outputParticles
WriteDataHandle
< ProtoTrackContainer > m_outputProtoTracks
WriteDataHandle< SimSeedContainer > m_outputSeeds {this, "OutputSeeds"}
Additional Inherited Members
Protected Member Functions inherited from ActsExamples::IAlgorithm
const Acts::Logger & logger () const
Detailed Description
Construct track seeds from particles.
Definition at line 40 of file TruthSeedingAlgorithm.hpp.
View newest version in sPHENIX GitHub at line 40 of file TruthSeedingAlgorithm.hpp
Member Typedef Documentation
using ActsExamples::TruthSeedingAlgorithm::HitParticlesMap = IndexMultimap<ActsFatras::Barcode>
Definition at line 42 of file TruthSeedingAlgorithm.hpp.
View newest version in sPHENIX GitHub at line 42 of file TruthSeedingAlgorithm.hpp
Constructor & Destructor Documentation
ActsExamples::TruthSeedingAlgorithm::TruthSeedingAlgorithm (Config cfg, Acts::Logging::Level lvl)
Construct the truth seeding algorithm.
Parameters
cfg is the algorithm configuration
lvl is the logging level
Definition at line 32 of file TruthSeedingAlgorithm.cpp.
View newest version in sPHENIX GitHub at line 32 of file TruthSeedingAlgorithm.cpp
References ActsExamples::WriteDataHandle< T >::initialize(), ActsExamples::ReadDataHandle< T >::initialize(), ActsExamples::TruthSeedingAlgorithm::Config::inputMeasurementParticlesMap, ActsExamples::TruthSeedingAlgorithm::Config::inputParticles, ActsExamples::TruthSeedingAlgorithm::Config::inputSpacePoints, m_cfg, m_inputMeasurementParticlesMap, m_inputParticles, m_inputSpacePoints, m_outputParticles, m_outputProtoTracks, m_outputSeeds, ActsExamples::TruthSeedingAlgorithm::Config::outputParticles, ActsExamples::TruthSeedingAlgorithm::Config::outputProtoTracks, ActsExamples::TruthSeedingAlgorithm::Config::outputSeeds, and to_string().
Member Function Documentation
const Config& ActsExamples::TruthSeedingAlgorithm::config () const inline
Const access to the config.
Definition at line 81 of file TruthSeedingAlgorithm.hpp.
View newest version in sPHENIX GitHub at line 81 of file TruthSeedingAlgorithm.hpp
References m_cfg.
ActsExamples::ProcessCode ActsExamples::TruthSeedingAlgorithm::execute (const AlgorithmContext & ctx) const override virtual
Run the truth seeding algorithm.
Parameters
ctx is the algorithm context with event information
Returns
a process code indication success or failure
Implements ActsExamples::IAlgorithm.
Definition at line 75 of file TruthSeedingAlgorithm.cpp.
View newest version in sPHENIX GitHub at line 75 of file TruthSeedingAlgorithm.cpp
References ACTS_VERBOSE, ACTS_WARNING, add_histos_bX::ib, ActsExamples::IndexSourceLink::index(), ActsExamples::invertIndexMultimap(), it, check_smearing_config::lhs, m_cfg(), ActsExamples::makeRange(), Acts::UnitConstants::min, testing::internal::move(), particle, particles, ActsExamples::SimSpacePoint::r(), physmon_track_finding_ttbar::r, check_smearing_config::rhs, seed, size, Acts::Experimental::detail::BlueprintHelper::sort(), SUCCESS, tracks(), and ActsExamples::SimSpacePoint::z().
Member Data Documentation
Config ActsExamples::TruthSeedingAlgorithm::m_cfg private
Definition at line 84 of file TruthSeedingAlgorithm.hpp.
View newest version in sPHENIX GitHub at line 84 of file TruthSeedingAlgorithm.hpp
Referenced by config(), and TruthSeedingAlgorithm().
ReadDataHandle<HitParticlesMap> ActsExamples::TruthSeedingAlgorithm::m_inputMeasurementParticlesMap private
Initial value:
{
      this, "InputMeasurementParticlesMaps"}
Definition at line 87 of file TruthSeedingAlgorithm.hpp.
View newest version in sPHENIX GitHub at line 87 of file TruthSeedingAlgorithm.hpp
Referenced by TruthSeedingAlgorithm().
ReadDataHandle<SimParticleContainer> ActsExamples::TruthSeedingAlgorithm::m_inputParticles {this, "InputParticles"} private
Definition at line 86 of file TruthSeedingAlgorithm.hpp.
View newest version in sPHENIX GitHub at line 86 of file TruthSeedingAlgorithm.hpp
Referenced by TruthSeedingAlgorithm().
std::vector<std::unique_ptr<ReadDataHandle<SimSpacePointContainer> > > ActsExamples::TruthSeedingAlgorithm::m_inputSpacePoints {} private
Definition at line 90 of file TruthSeedingAlgorithm.hpp.
View newest version in sPHENIX GitHub at line 90 of file TruthSeedingAlgorithm.hpp
Referenced by TruthSeedingAlgorithm().
WriteDataHandle<SimParticleContainer> ActsExamples::TruthSeedingAlgorithm::m_outputParticles private
Initial value:
{this,
                                                          "OutputParticles"}
Definition at line 92 of file TruthSeedingAlgorithm.hpp.
View newest version in sPHENIX GitHub at line 92 of file TruthSeedingAlgorithm.hpp
Referenced by TruthSeedingAlgorithm().
WriteDataHandle<ProtoTrackContainer> ActsExamples::TruthSeedingAlgorithm::m_outputProtoTracks private
Initial value:
{this,
                                                           "OutputProtoTracks"}
Definition at line 94 of file TruthSeedingAlgorithm.hpp.
View newest version in sPHENIX GitHub at line 94 of file TruthSeedingAlgorithm.hpp
Referenced by TruthSeedingAlgorithm().
WriteDataHandle<SimSeedContainer> ActsExamples::TruthSeedingAlgorithm::m_outputSeeds {this, "OutputSeeds"} private
Definition at line 96 of file TruthSeedingAlgorithm.hpp.
View newest version in sPHENIX GitHub at line 96 of file TruthSeedingAlgorithm.hpp
Referenced by TruthSeedingAlgorithm().
The documentation for this exception was generated from the following files:
acts/blob/sPHENIX/Examples/Algorithms/TruthTracking/ActsExamples/TruthTracking/TruthSeedingAlgorithm.hpp
acts/blob/sPHENIX/Examples/Algorithms/TruthTracking/ActsExamples/TruthTracking/TruthSeedingAlgorithm.cpp