Analysis Software: EmbRecoMatch Class Reference
EmbRecoMatch Class Reference
#include <coresoftware/blob/master/simulation/g4simulation/g4tracking/EmbRecoMatch.h>
Classes
struct Comp
Public Member Functions
EmbRecoMatch ()
~EmbRecoMatch () override=default
virtual unsigned short idTruthTrack () const
virtual unsigned short nClustersTruth () const
virtual unsigned short nMatches () const
virtual unsigned short idRecoTrack (unsigned short=0) const
virtual unsigned short idTpcTrackSeed (unsigned short=0) const
virtual unsigned short idSvtxTrackSeed (unsigned short=0) const
virtual unsigned short nClustersReco (unsigned short=0) const
virtual unsigned short nClustersMatched (unsigned short=0) const
virtual float nRatioMatched () const
Public Member Functions inherited from PHObject
PHObject ()
ctor
~PHObject () override
dtor
virtual PHObject * CloneMe () const
Virtual copy constructor.
virtual PHObject * clone () const final
PHObject * Clone (const char *newname="") const final
void Copy (TObject &object) const final
virtual void identify (std::ostream &os=std::cout) const
virtual void Reset ()
Clear Event.
virtual int isValid () const
isValid returns non zero if object contains vailid data
virtual int Integrate () const
virtual int Integrate (PHObject *)
virtual void CopyFrom (const PHObject *obj)
Detailed Description
Definition at line 11 of file EmbRecoMatch.h.
View newest version in sPHENIX GitHub at line 11 of file EmbRecoMatch.h
Constructor & Destructor Documentation
EmbRecoMatch::EmbRecoMatch () inline
Definition at line 14 of file EmbRecoMatch.h.
View newest version in sPHENIX GitHub at line 14 of file EmbRecoMatch.h
EmbRecoMatch::~EmbRecoMatch () override default
Member Function Documentation
virtual unsigned short EmbRecoMatch::idRecoTrack (unsigned short = 0) const inline virtual
Reimplemented in EmbRecoMatchv1.
Definition at line 21 of file EmbRecoMatch.h.
View newest version in sPHENIX GitHub at line 21 of file EmbRecoMatch.h
Referenced by EmbRecoMatchContainerv1::addMatch(), and EmbRecoMatch::Comp::operator()().
virtual unsigned short EmbRecoMatch::idSvtxTrackSeed (unsigned short = 0) const inline virtual
Reimplemented in EmbRecoMatchv1.
Definition at line 23 of file EmbRecoMatch.h.
View newest version in sPHENIX GitHub at line 23 of file EmbRecoMatch.h
virtual unsigned short EmbRecoMatch::idTpcTrackSeed (unsigned short = 0) const inline virtual
Reimplemented in EmbRecoMatchv1.
Definition at line 22 of file EmbRecoMatch.h.
View newest version in sPHENIX GitHub at line 22 of file EmbRecoMatch.h
virtual unsigned short EmbRecoMatch::idTruthTrack () const inline virtual
Reimplemented in EmbRecoMatchv1.
Definition at line 17 of file EmbRecoMatch.h.
View newest version in sPHENIX GitHub at line 17 of file EmbRecoMatch.h
Referenced by EmbRecoMatchContainerv1::addMatch(), and EmbRecoMatch::Comp::operator()().
virtual unsigned short EmbRecoMatch::nClustersMatched (unsigned short = 0) const inline virtual
Reimplemented in EmbRecoMatchv1.
Definition at line 26 of file EmbRecoMatch.h.
View newest version in sPHENIX GitHub at line 26 of file EmbRecoMatch.h
virtual unsigned short EmbRecoMatch::nClustersReco (unsigned short = 0) const inline virtual
Reimplemented in EmbRecoMatchv1.
Definition at line 25 of file EmbRecoMatch.h.
View newest version in sPHENIX GitHub at line 25 of file EmbRecoMatch.h
virtual unsigned short EmbRecoMatch::nClustersTruth () const inline virtual
Reimplemented in EmbRecoMatchv1.
Definition at line 18 of file EmbRecoMatch.h.
View newest version in sPHENIX GitHub at line 18 of file EmbRecoMatch.h
virtual unsigned short EmbRecoMatch::nMatches () const inline virtual
Reimplemented in EmbRecoMatchv1.
Definition at line 19 of file EmbRecoMatch.h.
View newest version in sPHENIX GitHub at line 19 of file EmbRecoMatch.h
virtual float EmbRecoMatch::nRatioMatched () const inline virtual
Definition at line 28 of file EmbRecoMatch.h.
View newest version in sPHENIX GitHub at line 28 of file EmbRecoMatch.h
The documentation for this class was generated from the following file:
coresoftware/blob/master/simulation/g4simulation/g4tracking/EmbRecoMatch.h