Analysis Software: JETSCAPE/blob/main/external_packages/googletest/googletest/test/gtest-listener_test.cc File Reference
gtest-listener_test.cc File Reference
#include "gtest/gtest.h"
#include <vector>
Classes
class testing::internal::EventRecordingListener
class testing::internal::EnvironmentInvocationCatcher
class testing::internal::ListenerTest
Namespaces
namespace testing
namespace testing::internal
Functions
testing::internal::TEST_F (ListenerTest, DoesFoo)
testing::internal::TEST_F (ListenerTest, DoesBar)
void VerifyResults (const std::vector< std::string > &data, const char *const *expected_data, size_t expected_data_size)
int main (int argc, char **argv)
Variables
std::vector< std::string > * g_events = NULL
Function Documentation
int main (int argc, char ** argv)
Definition at line 201 of file gtest-listener_test.cc.
View newest version in sPHENIX GitHub at line 201 of file gtest-listener_test.cc
References testing::AddGlobalTestEnvironment(), physmon_vertexing::events, GTEST_CHECK_, GTEST_FLAG, testing::InitGoogleTest(), RUN_ALL_TESTS(), and VerifyResults().
void VerifyResults (const std::vector< std::string > & data, const char *const * expected_data, size_t expected_data_size)
Definition at line 177 of file gtest-listener_test.cc.
View newest version in sPHENIX GitHub at line 177 of file gtest-listener_test.cc
References ASSERT_STREQ, EXPECT_EQ, i, and printf().
Referenced by main().
Variable Documentation
std::vector<std::string>* g_events = NULL
Definition at line 50 of file gtest-listener_test.cc.
View newest version in sPHENIX GitHub at line 50 of file gtest-listener_test.cc