Analysis Software: TowerInfov1 Class Reference
TowerInfov1 Class Reference
#include <coresoftware/blob/master/offline/packages/CaloBase/TowerInfov1.h>
Public Member Functions
TowerInfov1 ()
TowerInfov1 (TowerInfo &tower)
~TowerInfov1 () override
void Reset () override
Clear Event.
void Clear (Option_t *="") override
Clear is used by TClonesArray to reset the tower to initial state without calling destructor/constructor.
void set_time (short t) override
short get_time () override
void set_energy (float energy) override
float get_energy () override
void copy_tower (TowerInfo *tower) override
Public Member Functions inherited from TowerInfo
TowerInfo ()=default
~TowerInfo () override=default
virtual void set_time_float (float)
virtual float get_time_float ()
virtual void set_chi2 (float)
virtual float get_chi2 ()
virtual void set_pedestal (float)
virtual float get_pedestal ()
virtual void set_isHot (bool)
virtual bool get_isHot () const
virtual void set_isBadTime (bool)
virtual bool get_isBadTime () const
virtual void set_isBadChi2 (bool)
virtual bool get_isBadChi2 () const
virtual void set_isNotInstr (bool)
virtual bool get_isNotInstr () const
virtual void set_isNoCalib (bool)
virtual bool get_isNoCalib () const
virtual bool get_isGood () const
virtual uint8_t get_status () const
virtual void set_status (uint8_t)
virtual int get_nsample () const
virtual int16_t get_waveform_value (int) const
virtual void set_waveform_value (int, int16_t)
Public Member Functions inherited from PHObject
PHObject ()
ctor
~PHObject () override
dtor
virtual PHObject * CloneMe () const
Virtual copy constructor.
virtual PHObject * clone () const final
PHObject * Clone (const char *newname="") const final
void Copy (TObject &object) const final
virtual void identify (std::ostream &os=std::cout) const
virtual int isValid () const
isValid returns non zero if object contains vailid data
virtual int Integrate () const
virtual int Integrate (PHObject *)
virtual void CopyFrom (const PHObject *obj)
Private Member Functions
ClassDefOverride (TowerInfov1, 1)
Private Attributes
short _time = 0
float _energy = 0
Detailed Description
Definition at line 10 of file TowerInfov1.h.
View newest version in sPHENIX GitHub at line 10 of file TowerInfov1.h
Constructor & Destructor Documentation
TowerInfov1::TowerInfov1 () inline
Definition at line 13 of file TowerInfov1.h.
View newest version in sPHENIX GitHub at line 13 of file TowerInfov1.h
TowerInfov1::TowerInfov1 (TowerInfo & tower)
Definition at line 3 of file TowerInfov1.cc.
View newest version in sPHENIX GitHub at line 3 of file TowerInfov1.cc
References _energy, _time, TowerInfo::get_energy(), and TowerInfo::get_time().
TowerInfov1::~TowerInfov1 () inline override
Definition at line 15 of file TowerInfov1.h.
View newest version in sPHENIX GitHub at line 15 of file TowerInfov1.h
Member Function Documentation
TowerInfov1::ClassDefOverride (TowerInfov1 , 1) private
void TowerInfov1::Clear (Option_t * = "") override
Clear is used by TClonesArray to reset the tower to initial state without calling destructor/constructor.
Definition at line 15 of file TowerInfov1.cc.
View newest version in sPHENIX GitHub at line 15 of file TowerInfov1.cc
References _energy, and _time.
Referenced by TowerInfov2::Clear().
void TowerInfov1::copy_tower (TowerInfo * tower) override virtual
Reimplemented from TowerInfo.
Reimplemented in TowerInfov2, and TowerInfov3.
Definition at line 21 of file TowerInfov1.cc.
View newest version in sPHENIX GitHub at line 21 of file TowerInfov1.cc
References TowerInfo::get_energy(), TowerInfo::get_time(), set_energy(), and set_time().
Referenced by TowerInfov2::copy_tower().
float TowerInfov1::get_energy () inline override virtual
Reimplemented from TowerInfo.
Definition at line 24 of file TowerInfov1.h.
View newest version in sPHENIX GitHub at line 24 of file TowerInfov1.h
References _energy.
Referenced by RunTowerInfo::process_event().
short TowerInfov1::get_time () inline override virtual
Reimplemented from TowerInfo.
Reimplemented in TowerInfov2.
Definition at line 22 of file TowerInfov1.h.
View newest version in sPHENIX GitHub at line 22 of file TowerInfov1.h
References _time.
Referenced by TowerInfov2::get_time(), TowerInfov2::get_time_float(), and RunTowerInfo::process_event().
void TowerInfov1::Reset () override virtual
Clear Event.
Reimplemented from TowerInfo.
Reimplemented in TowerInfov3, and TowerInfov2.
Definition at line 9 of file TowerInfov1.cc.
View newest version in sPHENIX GitHub at line 9 of file TowerInfov1.cc
References _energy, and _time.
Referenced by TowerInfov2::Reset().
void TowerInfov1::set_energy (float energy) inline override virtual
Reimplemented from TowerInfo.
Definition at line 23 of file TowerInfov1.h.
View newest version in sPHENIX GitHub at line 23 of file TowerInfov1.h
References _energy, and energy.
Referenced by copy_tower(), TowerInfov2::copy_tower(), and SaveTowerInfo::process_event().
void TowerInfov1::set_time (short t) inline override virtual
Reimplemented from TowerInfo.
Reimplemented in TowerInfov2.
Definition at line 21 of file TowerInfov1.h.
View newest version in sPHENIX GitHub at line 21 of file TowerInfov1.h
References _time, and t.
Referenced by copy_tower(), SaveTowerInfo::process_event(), TowerInfov2::set_time(), and TowerInfov2::set_time_float().
Member Data Documentation
float TowerInfov1::_energy = 0 private
Definition at line 29 of file TowerInfov1.h.
View newest version in sPHENIX GitHub at line 29 of file TowerInfov1.h
Referenced by Clear(), get_energy(), Reset(), set_energy(), and TowerInfov1().
short TowerInfov1::_time = 0 private
Definition at line 28 of file TowerInfov1.h.
View newest version in sPHENIX GitHub at line 28 of file TowerInfov1.h
Referenced by Clear(), get_time(), Reset(), set_time(), and TowerInfov1().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/CaloBase/TowerInfov1.h
coresoftware/blob/master/offline/packages/CaloBase/TowerInfov1.cc