Analysis Software: Acts::ATLASCuts< SpacePoint > Class Template Reference
Acts::ATLASCuts< SpacePoint > Class Template Reference
#include <acts/blob/sPHENIX/Tests/UnitTests/Core/Seeding/ATLASCuts.hpp>
Public Member Functions
float seedWeight (const InternalSpacePoint< SpacePoint > &bottom, const InternalSpacePoint< SpacePoint > &middle, const InternalSpacePoint< SpacePoint > &top) const override
bool singleSeedCut (float weight, const InternalSpacePoint< SpacePoint > &bottom, const InternalSpacePoint< SpacePoint > &, const InternalSpacePoint< SpacePoint > &) const override
std::vector< typename
CandidatesForMiddleSp< const
InternalSpacePoint< SpacePoint >
>::value_type > cutPerMiddleSP (std::vector< typename CandidatesForMiddleSp< const InternalSpacePoint< SpacePoint >>::value_type > seedCandidates) const override
float seedWeight (const InternalSpacePoint< SpacePoint > &bottom, const InternalSpacePoint< SpacePoint > &middle, const InternalSpacePoint< SpacePoint > &top) const
bool singleSeedCut (float weight, const InternalSpacePoint< SpacePoint > &bottom, const InternalSpacePoint< SpacePoint > &, const InternalSpacePoint< SpacePoint > &) const
std::vector< typename
CandidatesForMiddleSp< const
InternalSpacePoint< SpacePoint >
>::value_type > cutPerMiddleSP (std::vector< typename CandidatesForMiddleSp< const InternalSpacePoint< SpacePoint >>::value_type > seedCandidates) const override
float seedWeight (const InternalSpacePoint< SpacePoint > &bottom, const InternalSpacePoint< SpacePoint > &middle, const InternalSpacePoint< SpacePoint > &top) const override
bool singleSeedCut (float weight, const InternalSpacePoint< SpacePoint > &bottom, const InternalSpacePoint< SpacePoint > &, const InternalSpacePoint< SpacePoint > &) const override
std::vector< typename
CandidatesForMiddleSp< const
InternalSpacePoint< SpacePoint >
>::value_type > cutPerMiddleSP (std::vector< typename CandidatesForMiddleSp< const InternalSpacePoint< SpacePoint >>::value_type > seedCandidates) const override
Public Member Functions inherited from Acts::IExperimentCuts< SpacePoint >
virtual ~IExperimentCuts ()=default
Detailed Description
template<typename SpacePoint>
class Acts::ATLASCuts< SpacePoint >
Definition at line 17 of file ATLASCuts.hpp.
View newest version in sPHENIX GitHub at line 17 of file ATLASCuts.hpp
Member Function Documentation
template<typename SpacePoint> std::vector<typename CandidatesForMiddleSp< const InternalSpacePoint<SpacePoint> >::value_type> Acts::ATLASCuts< SpacePoint >::cutPerMiddleSP (std::vector< typename CandidatesForMiddleSp< const InternalSpacePoint< SpacePoint >>::value_type > seedCandidates) const override virtual
Parameters
seedCandidates contains collection of seed candidates created for one middle space point in a std::tuple format
Returns
vector of seed candidates that pass the cut
Implements Acts::IExperimentCuts< SpacePoint >.
template<typename SpacePoint> std::vector<typename CandidatesForMiddleSp< const InternalSpacePoint<SpacePoint> >::value_type> Acts::ATLASCuts< SpacePoint >::cutPerMiddleSP (std::vector< typename CandidatesForMiddleSp< const InternalSpacePoint< SpacePoint >>::value_type > seedCandidates) const override virtual
Parameters
seedCandidates contains collection of seed candidates created for one middle space point in a std::tuple format
Returns
vector of seed candidates that pass the cut
Implements Acts::IExperimentCuts< SpacePoint >.
template<typename SpacePoint > std::vector< typename CandidatesForMiddleSp< const InternalSpacePoint< SpacePoint > >::value_type > Acts::ATLASCuts< SpacePoint >::cutPerMiddleSP (std::vector< typename CandidatesForMiddleSp< const InternalSpacePoint< SpacePoint >>::value_type > seedCandidates) const override virtual
Parameters
seedCandidates contains collection of seed candidates created for one middle space point in a std::tuple format
Returns
vector of seeds that pass the cut
Implements Acts::IExperimentCuts< SpacePoint >.
Definition at line 74 of file ATLASCuts.hpp.
View newest version in sPHENIX GitHub at line 74 of file ATLASCuts.hpp
References i, Acts::UnitConstants::min, and testing::internal::move().
template<typename SpacePoint> float Acts::ATLASCuts< SpacePoint >::seedWeight (const InternalSpacePoint< SpacePoint > & bottom, const InternalSpacePoint< SpacePoint > & middle, const InternalSpacePoint< SpacePoint > & top) const override virtual
Returns seed weight bonus/malus depending on detector considerations.
Parameters
bottom bottom space point of the current seed
middle middle space point of the current seed
top top space point of the current seed
Returns
seed weight to be added to the seed's weight
Implements Acts::IExperimentCuts< SpacePoint >.
template<typename SpacePoint> float Acts::ATLASCuts< SpacePoint >::seedWeight (const InternalSpacePoint< SpacePoint > & bottom, const InternalSpacePoint< SpacePoint > & middle, const InternalSpacePoint< SpacePoint > & top) const virtual
Returns seed weight bonus/malus depending on detector considerations.
Parameters
bottom bottom space point of the current seed
middle middle space point of the current seed
top top space point of the current seed
Returns
seed weight to be added to the seed's weight
Implements Acts::IExperimentCuts< SpacePoint >.
template<typename SpacePoint > float Acts::ATLASCuts< SpacePoint >::seedWeight (const InternalSpacePoint< SpacePoint > & bottom, const InternalSpacePoint< SpacePoint > & middle, const InternalSpacePoint< SpacePoint > & top) const override virtual
Returns seed weight bonus/malus depending on detector considerations.
Parameters
bottom bottom space point of the current seed
middle middle space point of the current seed
top top space point of the current seed
Returns
seed weight to be added to the seed's weight
Implements Acts::IExperimentCuts< SpacePoint >.
Definition at line 49 of file ATLASCuts.hpp.
View newest version in sPHENIX GitHub at line 49 of file ATLASCuts.hpp
References Acts::InternalSpacePoint< SpacePoint >::radius().
template<typename SpacePoint> bool Acts::ATLASCuts< SpacePoint >::singleSeedCut (float weight, const InternalSpacePoint< SpacePoint > & bottom, const InternalSpacePoint< SpacePoint > & , const InternalSpacePoint< SpacePoint > &) const override virtual
Parameters
weight the current seed weight
bottom bottom space point of the current seed
middle middle space point of the current seed
top top space point of the current seed
Returns
true if the seed should be kept, false if the seed should be discarded
Implements Acts::IExperimentCuts< SpacePoint >.
template<typename SpacePoint> bool Acts::ATLASCuts< SpacePoint >::singleSeedCut (float weight, const InternalSpacePoint< SpacePoint > & bottom, const InternalSpacePoint< SpacePoint > & , const InternalSpacePoint< SpacePoint > &) const virtual
Parameters
weight the current seed weight
bottom bottom space point of the current seed
middle middle space point of the current seed
top top space point of the current seed
Returns
true if the seed should be kept, false if the seed should be discarded
Implements Acts::IExperimentCuts< SpacePoint >.
template<typename SpacePoint > bool Acts::ATLASCuts< SpacePoint >::singleSeedCut (float weight, const InternalSpacePoint< SpacePoint > & bottom, const InternalSpacePoint< SpacePoint > & , const InternalSpacePoint< SpacePoint > &) const override virtual
Parameters
weight the current seed weight
bottom bottom space point of the current seed
middle middle space point of the current seed
top top space point of the current seed
Returns
true if the seed should be kept, false if the seed should be discarded
Implements Acts::IExperimentCuts< SpacePoint >.
Definition at line 64 of file ATLASCuts.hpp.
View newest version in sPHENIX GitHub at line 64 of file ATLASCuts.hpp
References Acts::InternalSpacePoint< SpacePoint >::radius().
The documentation for this class was generated from the following files:
acts/blob/sPHENIX/Tests/UnitTests/Core/Seeding/ATLASCuts.hpp
acts/blob/sPHENIX/Tests/UnitTests/Plugins/Cuda/Seeding/ATLASCuts.hpp
acts/blob/sPHENIX/Tests/UnitTests/Plugins/Sycl/Seeding/ATLASCuts.hpp