Analysis Software: PHG4CylinderGeomContainer Class Reference
PHG4CylinderGeomContainer Class Reference
#include <coresoftware/blob/master/simulation/g4simulation/g4detectors/PHG4CylinderGeomContainer.h>
Public Types
using Map = std::map< int, PHG4CylinderGeom * >
using Iterator = Map::iterator
using ConstIterator = Map::const_iterator
using Range = std::pair< Iterator, Iterator >
using ConstRange = std::pair< ConstIterator, ConstIterator >
Public Member Functions
PHG4CylinderGeomContainer ()=default
~PHG4CylinderGeomContainer () override
void identify (std::ostream &os=std::cout) const override
int AddLayerGeom (const int i, PHG4CylinderGeom *mygeom)
int AddLayerGeom (PHG4CylinderGeom *mygeom)
PHG4CylinderGeom * GetLayerGeom (const int i)
PHG4CylinderGeom * GetFirstLayerGeom ()
int get_NLayers () const
ConstRange get_begin_end () const
Public Member Functions inherited from PHObject
PHObject ()
ctor
~PHObject () override
dtor
virtual PHObject * CloneMe () const
Virtual copy constructor.
virtual PHObject * clone () const final
PHObject * Clone (const char *newname="") const final
void Copy (TObject &object) const final
virtual void Reset ()
Clear Event.
virtual int isValid () const
isValid returns non zero if object contains vailid data
virtual int Integrate () const
virtual int Integrate (PHObject *)
virtual void CopyFrom (const PHObject *obj)
Protected Attributes
Map layergeoms
float magfield {std::numeric_limits<float>::quiet_NaN()}
Detailed Description
Definition at line 15 of file PHG4CylinderGeomContainer.h.
View newest version in sPHENIX GitHub at line 15 of file PHG4CylinderGeomContainer.h
Member Typedef Documentation
using PHG4CylinderGeomContainer::ConstIterator = Map::const_iterator
Definition at line 20 of file PHG4CylinderGeomContainer.h.
View newest version in sPHENIX GitHub at line 20 of file PHG4CylinderGeomContainer.h
using PHG4CylinderGeomContainer::ConstRange = std::pair<ConstIterator, ConstIterator>
Definition at line 22 of file PHG4CylinderGeomContainer.h.
View newest version in sPHENIX GitHub at line 22 of file PHG4CylinderGeomContainer.h
using PHG4CylinderGeomContainer::Iterator = Map::iterator
Definition at line 19 of file PHG4CylinderGeomContainer.h.
View newest version in sPHENIX GitHub at line 19 of file PHG4CylinderGeomContainer.h
using PHG4CylinderGeomContainer::Map = std::map<int, PHG4CylinderGeom *>
Definition at line 18 of file PHG4CylinderGeomContainer.h.
View newest version in sPHENIX GitHub at line 18 of file PHG4CylinderGeomContainer.h
using PHG4CylinderGeomContainer::Range = std::pair<Iterator, Iterator>
Definition at line 21 of file PHG4CylinderGeomContainer.h.
View newest version in sPHENIX GitHub at line 21 of file PHG4CylinderGeomContainer.h
Constructor & Destructor Documentation
PHG4CylinderGeomContainer::PHG4CylinderGeomContainer () default
PHG4CylinderGeomContainer::~PHG4CylinderGeomContainer () override
Definition at line 6 of file PHG4CylinderGeomContainer.cc.
View newest version in sPHENIX GitHub at line 6 of file PHG4CylinderGeomContainer.cc
References layergeoms.
Member Function Documentation
int PHG4CylinderGeomContainer::AddLayerGeom (const int i, PHG4CylinderGeom * mygeom)
Definition at line 29 of file PHG4CylinderGeomContainer.cc.
View newest version in sPHENIX GitHub at line 29 of file PHG4CylinderGeomContainer.cc
References i, layergeoms, and PHG4CylinderGeom::set_layer().
Referenced by PHG4EICMvtxDetector::AddGeometryNode(), PHG4MvtxDetector::AddGeometryNode(), PHG4InttDetector::AddGeometryNode(), PHG4HcalDetector::ConstructMe(), PHG4SpacalPrototypeDetector::ConstructMe(), PHG4SpacalPrototype4Detector::ConstructMe(), PHG4SpacalDetector::ConstructMe(), and PHG4CylinderSubsystem::InitRunSubsystem().
int PHG4CylinderGeomContainer::AddLayerGeom (PHG4CylinderGeom * mygeom)
Definition at line 41 of file PHG4CylinderGeomContainer.cc.
View newest version in sPHENIX GitHub at line 41 of file PHG4CylinderGeomContainer.cc
References PHG4CylinderGeom::get_layer(), layer, and layergeoms.
ConstRange PHG4CylinderGeomContainer::get_begin_end () const inline
Definition at line 35 of file PHG4CylinderGeomContainer.h.
View newest version in sPHENIX GitHub at line 35 of file PHG4CylinderGeomContainer.h
References layergeoms.
Referenced by PHG4InttDigitizer::CalculateLadderCellADCScale(), InttClusterizer::CalculateLadderThresholds(), PHG4MvtxDigitizer::CalculateMvtxLadderCellADCScale(), PHG4CylinderCellReco::InitRun(), PHActsKDTreeSeeding::InitRun(), PHActsSiliconSeeding::InitRun(), MakeActsGeometry::makeMmMapPairs(), and DumpPHG4CylinderGeomContainer::process_Node().
int PHG4CylinderGeomContainer::get_NLayers () const inline
Definition at line 34 of file PHG4CylinderGeomContainer.h.
View newest version in sPHENIX GitHub at line 34 of file PHG4CylinderGeomContainer.h
References layergeoms.
Referenced by PHMicromegasTpcTrackMatching::InitRun(), and DumpPHG4CylinderGeomContainer::process_Node().
PHG4CylinderGeom * PHG4CylinderGeomContainer::GetFirstLayerGeom ()
Definition at line 66 of file PHG4CylinderGeomContainer.cc.
View newest version in sPHENIX GitHub at line 66 of file PHG4CylinderGeomContainer.cc
References layergeoms.
Referenced by PHG4SpacalDetector::AddCellGeometryNode(), PHG4FullProjSpacalCellReco::InitRun(), PHMicromegasTpcTrackMatching::InitRun(), PHG4FullProjSpacalCellReco::process_event(), CaloWaveformSim::process_event(), EMCalAna::process_event_SF(), CaloWaveFormSim::process_g4hits(), and PHG4SpacalSteppingAction::SetUpGeomNode().
PHG4CylinderGeom * PHG4CylinderGeomContainer::GetLayerGeom (const int i)
Definition at line 54 of file PHG4CylinderGeomContainer.cc.
View newest version in sPHENIX GitHub at line 54 of file PHG4CylinderGeomContainer.cc
References layergeoms.
Referenced by TrackEvaluation::add_trk_information_micromegas(), TrackEvaluation::add_truth_information_micromegas(), PHG4InttHitReco::cluster_truthhits(), PHG4MvtxHitReco::cluster_truthhits(), InttClusterizer::ClusterLadderCells(), InttClusterizer::ClusterLadderCellsRaw(), MvtxClusterizer::ClusterMvtx(), MvtxClusterizer::ClusterMvtxRaw(), QAG4SimulationMicromegas::evaluate_clusters(), TrackResiduals::fillHitTree(), PHTruthClustering::G4ClusterSize(), SvtxTruthEval::G4ClusterSize(), MakeActsGeometry::getInttHitSetKeyFromCoords(), MakeActsGeometry::getMvtxHitSetKeyFromCoords(), TrkrClusterIsMatcher::init(), G4Eval::TrkrClusterComparer::init(), BDiJetModule::MakeGenFitTrack(), SVReco::MakeGenFitTrack(), PHActsKDTreeSeeding::matchInttClusters(), PHActsSiliconSeeding::matchInttClusters(), PHG4GenHit::process_event(), MicromegasClusterizer::process_event(), HFMLTriggerInterface::process_event(), PHG4InttHitReco::process_event(), HFMLTriggerOccupancy::process_event(), and PHMicromegasTpcTrackMatching::process_event().
void PHG4CylinderGeomContainer::identify (std::ostream & os = std::cout) const override virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from PHObject.
Definition at line 16 of file PHG4CylinderGeomContainer.cc.
View newest version in sPHENIX GitHub at line 16 of file PHG4CylinderGeomContainer.cc
References layergeoms, and magfield.
Referenced by PHG4SpacalDetector::AddCellGeometryNode(), PHG4EICMvtxDetector::AddGeometryNode(), PHG4MvtxDetector::AddGeometryNode(), PHG4InttDetector::AddGeometryNode(), PHG4SpacalPrototype4Detector::ConstructMe(), PHG4SpacalPrototypeDetector::ConstructMe(), PHG4CylinderCellReco::InitRun(), PHG4FullProjSpacalCellReco::InitRun(), and PHG4InttHitReco::InitRun().
Member Data Documentation
Map PHG4CylinderGeomContainer::layergeoms protected
Definition at line 38 of file PHG4CylinderGeomContainer.h.
View newest version in sPHENIX GitHub at line 38 of file PHG4CylinderGeomContainer.h
Referenced by AddLayerGeom(), get_begin_end(), get_NLayers(), GetFirstLayerGeom(), GetLayerGeom(), identify(), and ~PHG4CylinderGeomContainer().
float PHG4CylinderGeomContainer::magfield {std::numeric_limits<float>::quiet_NaN()} protected
Definition at line 39 of file PHG4CylinderGeomContainer.h.
View newest version in sPHENIX GitHub at line 39 of file PHG4CylinderGeomContainer.h
Referenced by identify().
The documentation for this class was generated from the following files:
coresoftware/blob/master/simulation/g4simulation/g4detectors/PHG4CylinderGeomContainer.h
coresoftware/blob/master/simulation/g4simulation/g4detectors/PHG4CylinderGeomContainer.cc