Analysis Software: ODBCCallableStatement Class Reference
ODBCCallableStatement Class Reference
#include <RDBC/blob/master/odbc/ODBCCallableStatement.h>
Public Member Functions
virtual ~ODBCCallableStatement ()
void RegisterOutParameter (Int_t parameterIndex, Int_t sqlType)
void RegisterOutParameter (Int_t parameterIndex, Int_t sqlType, Int_t scale)
Bool_t WasNull ()
TString GetString (Int_t parameterIndex)
Bool_t GetBoolean (Int_t parameterIndex)
Char_t GetByte (Int_t parameterIndex)
Short_t GetShort (Int_t parameterIndex)
Int_t GetInt (Int_t parameterIndex)
Long_t GetLong (Int_t parameterIndex)
Float_t GetFloat (Int_t parameterIndex)
Double_t GetDouble (Int_t parameterIndex)
TArrayC GetBytes (Int_t parameterIndex)
TSQLDate GetDate (Int_t parameterIndex)
TSQLTime GetTime (Int_t parameterIndex)
TSQLTimestamp GetTimestamp (Int_t parameterIndex)
void SetNull (Int_t parameterIndex, Int_t sqlType)
void SetBoolean (Int_t parameterIndex, Bool_t x)
void SetByte (Int_t parameterIndex, Char_t x)
void SetShort (Int_t parameterIndex, Short_t x)
void SetInt (Int_t parameterIndex, Int_t x)
void SetLong (Int_t parameterIndex, Long_t x)
void SetFloat (Int_t parameterIndex, Float_t x)
void SetDouble (Int_t parameterIndex, Double_t x)
void SetString (Int_t parameterIndex, const TString &x)
void SetBytes (Int_t parameterIndex, const TArrayC &x)
void SetDate (Int_t parameterIndex, const TSQLDate &x)
void SetTime (Int_t parameterIndex, const TSQLTime &x)
void SetTimestamp (Int_t parameterIndex, const TSQLTimestamp &x)
void SetAsciiStream (Int_t parameterIndex, TBuffer *x, Int_t length)
void SetBinaryStream (Int_t parameterIndex, TBuffer *x, Int_t length)
void SetObject (Int_t parameterIndex, TObject *x)
void ClearParameters ()
virtual Bool_t Execute (const TString &sql="")
virtual TSQLResultSet * ExecuteQuery (const TString &sql="")
virtual Int_t ExecuteUpdate (const TString &sql="")
TSQLResultSet * GetResultSet ()
Bool_t GetMoreResults ()
void Close ()
void Cancel ()
Int_t GetMaxFieldSize ()
void SetMaxFieldSize (Int_t max)
Int_t GetMaxRows ()
void SetMaxRows (Int_t max)
Bool_t GetEscapeProcessing ()
void SetEscapeProcessing (Bool_t enable=kTRUE)
Int_t GetQueryTimeout ()
void SetQueryTimeout (Int_t seconds)
Int_t GetUpdateCount ()
void SetCursorName (const TString &name)
void AddBatch (const TString &sql)
void ClearBatch ()
Int_t * ExecuteBatch ()
Int_t GetFetchDirection ()
void SetFetchDirection (Int_t direction)
Int_t GetFetchSize ()
void SetFetchSize (Int_t rows)
Int_t GetResultSetConcurrency ()
Int_t GetResultSetType ()
Public Member Functions inherited from TSQLCallableStatement
virtual ~TSQLCallableStatement ()
Public Member Functions inherited from TSQLPreparedStatement
virtual ~TSQLPreparedStatement ()
Public Member Functions inherited from TSQLStatement
virtual void Execute (const char *, const char *, int *)
virtual void Execute (TMethod *, TObjArray *, int *)
virtual ~TSQLStatement ()
TSQLConnection * GetConnection () const
Public Member Functions inherited from TSQL
TSQL (void *imp=0)
virtual ~TSQL ()
virtual void Throw (TSQLException *e)
TList * GetWarnings () const
void ClearWarnings ()
virtual Bool_t IsValid () const
Protected Member Functions
ODBCCallableStatement (TSQLConnection *con, void *imp=0)
Protected Member Functions inherited from TSQLCallableStatement
TSQLCallableStatement (TSQLConnection *con, void *imp=0)
Protected Member Functions inherited from TSQLPreparedStatement
TSQLPreparedStatement (TSQLConnection *con, void *imp=0)
Protected Member Functions inherited from TSQLStatement
TSQLStatement (TSQLConnection *con, void *imp=0)
Friends
class ODBCConnection
Additional Inherited Members
Static Public Member Functions inherited from TSQL
static Bool_t SetHandler (const TString &handler)
static Bool_t UnsetHandler (const TString &handler="")
Protected Attributes inherited from TSQLStatement
TList * fBatches
TSQLResultSet * fCurrentResult
TSQLConnection * fConnection
Detailed Description
Definition at line 15 of file ODBCCallableStatement.h.
View newest version in sPHENIX GitHub at line 15 of file ODBCCallableStatement.h
Constructor & Destructor Documentation
ODBCCallableStatement::ODBCCallableStatement (TSQLConnection * con, void * imp = 0) protected
ODBCCallableStatement::~ODBCCallableStatement () virtual
Definition at line 117 of file ODBCCallableStatement.cxx.
View newest version in sPHENIX GitHub at line 117 of file ODBCCallableStatement.cxx
References Acts::UnitConstants::e, TSQLStatement::fCurrentResult, TSQL::fImp, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), ODBCXX_STRING_CSTR, and TSQL::Throw().
Member Function Documentation
void ODBCCallableStatement::AddBatch (const TString & sql) virtual
Implements TSQLStatement.
Definition at line 1890 of file ODBCCallableStatement.cxx.
View newest version in sPHENIX GitHub at line 1890 of file ODBCCallableStatement.cxx
void ODBCCallableStatement::Cancel () virtual
Implements TSQLStatement.
Definition at line 1656 of file ODBCCallableStatement.cxx.
View newest version in sPHENIX GitHub at line 1656 of file ODBCCallableStatement.cxx
References odbc::Statement::cancel(), Acts::UnitConstants::e, TSQL::fImp, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), ODBCXX_STRING_CSTR, and TSQL::Throw().
void ODBCCallableStatement::ClearBatch () virtual
Implements TSQLStatement.
Definition at line 1905 of file ODBCCallableStatement.cxx.
View newest version in sPHENIX GitHub at line 1905 of file ODBCCallableStatement.cxx
void ODBCCallableStatement::ClearParameters () virtual
Implements TSQLPreparedStatement.
Definition at line 1171 of file ODBCCallableStatement.cxx.
View newest version in sPHENIX GitHub at line 1171 of file ODBCCallableStatement.cxx
References odbc::PreparedStatement::clearParameters(), Acts::UnitConstants::e, TSQL::fImp, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), ODBCXX_STRING_CSTR, and TSQL::Throw().
void ODBCCallableStatement::Close () virtual
Implements TSQLStatement.
Definition at line 1679 of file ODBCCallableStatement.cxx.
View newest version in sPHENIX GitHub at line 1679 of file ODBCCallableStatement.cxx
References TSQLStatement::ClearBatch(), Acts::UnitConstants::e, TSQLStatement::fBatches, TSQLStatement::fCurrentResult, TSQL::fImp, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), ODBCXX_STRING_CSTR, and TSQL::Throw().
Bool_t ODBCCallableStatement::Execute (const TString & sql = "") virtual
Implements TSQLStatement.
Definition at line 1240 of file ODBCCallableStatement.cxx.
View newest version in sPHENIX GitHub at line 1240 of file ODBCCallableStatement.cxx
References TSQL::ClearWarnings(), Acts::UnitConstants::e, odbc::PreparedStatement::execute(), odbc::Statement::execute(), TSQL::fImp, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), ODBCXX_STRING_C, ODBCXX_STRING_CSTR, and TSQL::Throw().
Int_t * ODBCCallableStatement::ExecuteBatch () virtual
Implements TSQLStatement.
Definition at line 1917 of file ODBCCallableStatement.cxx.
View newest version in sPHENIX GitHub at line 1917 of file ODBCCallableStatement.cxx
TSQLResultSet * ODBCCallableStatement::ExecuteQuery (const TString & sql = "") virtual
Implements TSQLStatement.
Definition at line 1200 of file ODBCCallableStatement.cxx.
View newest version in sPHENIX GitHub at line 1200 of file ODBCCallableStatement.cxx
References TSQL::ClearWarnings(), Acts::UnitConstants::e, odbc::PreparedStatement::executeQuery(), odbc::Statement::executeQuery(), TSQLStatement::fCurrentResult, TSQL::fImp, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), ODBCXX_STRING_C, ODBCXX_STRING_CSTR, and TSQL::Throw().
Int_t ODBCCallableStatement::ExecuteUpdate (const TString & sql = "") virtual
Implements TSQLStatement.
Definition at line 1289 of file ODBCCallableStatement.cxx.
View newest version in sPHENIX GitHub at line 1289 of file ODBCCallableStatement.cxx
References TSQL::ClearWarnings(), Acts::UnitConstants::e, odbc::PreparedStatement::executeUpdate(), odbc::Statement::executeUpdate(), TSQL::fImp, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), ODBCXX_STRING_C, ODBCXX_STRING_CSTR, and TSQL::Throw().
Bool_t ODBCCallableStatement::GetBoolean (Int_t parameterIndex) virtual
Implements TSQLCallableStatement.
Definition at line 337 of file ODBCCallableStatement.cxx.
View newest version in sPHENIX GitHub at line 337 of file ODBCCallableStatement.cxx
References Acts::UnitConstants::e, TSQL::fImp, odbc::CallableStatement::getBoolean(), odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), ODBCXX_STRING_CSTR, and TSQL::Throw().
Char_t ODBCCallableStatement::GetByte (Int_t parameterIndex) virtual
Implements TSQLCallableStatement.
Definition at line 368 of file ODBCCallableStatement.cxx.
View newest version in sPHENIX GitHub at line 368 of file ODBCCallableStatement.cxx
References Acts::UnitConstants::e, TSQL::fImp, odbc::CallableStatement::getByte(), odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), ODBCXX_STRING_CSTR, and TSQL::Throw().
TArrayC ODBCCallableStatement::GetBytes (Int_t parameterIndex) virtual
Implements TSQLCallableStatement.
Definition at line 554 of file ODBCCallableStatement.cxx.
View newest version in sPHENIX GitHub at line 554 of file ODBCCallableStatement.cxx
References TauVsDIS_MachineLearning_Differentiation::array, KFPMath::b, Acts::UnitConstants::e, TSQL::fImp, odbc::CallableStatement::getBytes(), odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), ODBCXX_BYTES, ODBCXX_BYTES_DATA, ODBCXX_BYTES_SIZE, ODBCXX_STRING_CSTR, and TSQL::Throw().
TSQLDate ODBCCallableStatement::GetDate (Int_t parameterIndex) virtual
Implements TSQLCallableStatement.
Definition at line 588 of file ODBCCallableStatement.cxx.
View newest version in sPHENIX GitHub at line 588 of file ODBCCallableStatement.cxx
References Acts::UnitConstants::e, TSQL::fImp, odbc::CallableStatement::getDate(), odbc::Date::getDay(), odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::Date::getMonth(), odbc::SQLException::getSQLState(), odbc::Date::getYear(), ODBCXX_STRING_CSTR, and TSQL::Throw().
Double_t ODBCCallableStatement::GetDouble (Int_t parameterIndex) virtual
Implements TSQLCallableStatement.
Definition at line 523 of file ODBCCallableStatement.cxx.
View newest version in sPHENIX GitHub at line 523 of file ODBCCallableStatement.cxx
References Acts::UnitConstants::e, TSQL::fImp, odbc::CallableStatement::getDouble(), odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), ODBCXX_STRING_CSTR, and TSQL::Throw().
Bool_t ODBCCallableStatement::GetEscapeProcessing () virtual
Implements TSQLStatement.
Definition at line 1569 of file ODBCCallableStatement.cxx.
View newest version in sPHENIX GitHub at line 1569 of file ODBCCallableStatement.cxx
References Acts::UnitConstants::e, TSQL::fImp, odbc::SQLException::getErrorCode(), odbc::Statement::getEscapeProcessing(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), ODBCXX_STRING_CSTR, and TSQL::Throw().
Int_t ODBCCallableStatement::GetFetchDirection () virtual
Implements TSQLStatement.
Definition at line 1769 of file ODBCCallableStatement.cxx.
View newest version in sPHENIX GitHub at line 1769 of file ODBCCallableStatement.cxx
Int_t ODBCCallableStatement::GetFetchSize () virtual
Implements TSQLStatement.
Definition at line 1805 of file ODBCCallableStatement.cxx.
View newest version in sPHENIX GitHub at line 1805 of file ODBCCallableStatement.cxx
References Acts::UnitConstants::e, TSQL::fImp, odbc::SQLException::getErrorCode(), odbc::Statement::getFetchSize(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), ODBCXX_STRING_CSTR, and TSQL::Throw().
Float_t ODBCCallableStatement::GetFloat (Int_t parameterIndex) virtual
Implements TSQLCallableStatement.
Definition at line 492 of file ODBCCallableStatement.cxx.
View newest version in sPHENIX GitHub at line 492 of file ODBCCallableStatement.cxx
References Acts::UnitConstants::e, TSQL::fImp, odbc::SQLException::getErrorCode(), odbc::CallableStatement::getFloat(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), ODBCXX_STRING_CSTR, and TSQL::Throw().
Int_t ODBCCallableStatement::GetInt (Int_t parameterIndex) virtual
Implements TSQLCallableStatement.
Definition at line 430 of file ODBCCallableStatement.cxx.
View newest version in sPHENIX GitHub at line 430 of file ODBCCallableStatement.cxx
References Acts::UnitConstants::e, TSQL::fImp, odbc::SQLException::getErrorCode(), odbc::CallableStatement::getInt(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), ODBCXX_STRING_CSTR, and TSQL::Throw().
Long_t ODBCCallableStatement::GetLong (Int_t parameterIndex) virtual
Implements TSQLCallableStatement.
Definition at line 461 of file ODBCCallableStatement.cxx.
View newest version in sPHENIX GitHub at line 461 of file ODBCCallableStatement.cxx
References Acts::UnitConstants::e, TSQL::fImp, odbc::SQLException::getErrorCode(), odbc::CallableStatement::getLong(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), ODBCXX_STRING_CSTR, and TSQL::Throw().
Int_t ODBCCallableStatement::GetMaxFieldSize () virtual
Implements TSQLStatement.
Definition at line 1429 of file ODBCCallableStatement.cxx.
View newest version in sPHENIX GitHub at line 1429 of file ODBCCallableStatement.cxx
References Acts::UnitConstants::e, TSQL::fImp, odbc::SQLException::getErrorCode(), odbc::Statement::getMaxFieldSize(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), ODBCXX_STRING_CSTR, and TSQL::Throw().
Int_t ODBCCallableStatement::GetMaxRows () virtual
Implements TSQLStatement.
Definition at line 1488 of file ODBCCallableStatement.cxx.
View newest version in sPHENIX GitHub at line 1488 of file ODBCCallableStatement.cxx
References Acts::UnitConstants::e, TSQL::fImp, odbc::SQLException::getErrorCode(), odbc::Statement::getMaxRows(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), ODBCXX_STRING_CSTR, and TSQL::Throw().
Bool_t ODBCCallableStatement::GetMoreResults () virtual
Implements TSQLStatement.
Definition at line 1395 of file ODBCCallableStatement.cxx.
View newest version in sPHENIX GitHub at line 1395 of file ODBCCallableStatement.cxx
References Acts::UnitConstants::e, TSQL::fImp, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::Statement::getMoreResults(), odbc::SQLException::getSQLState(), ODBCXX_STRING_CSTR, and TSQL::Throw().
Int_t ODBCCallableStatement::GetQueryTimeout () virtual
Implements TSQLStatement.
Definition at line 1602 of file ODBCCallableStatement.cxx.
View newest version in sPHENIX GitHub at line 1602 of file ODBCCallableStatement.cxx
References Acts::UnitConstants::e, TSQL::fImp, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::Statement::getQueryTimeout(), odbc::SQLException::getSQLState(), ODBCXX_STRING_CSTR, and TSQL::Throw().
TSQLResultSet * ODBCCallableStatement::GetResultSet () virtual
Implements TSQLStatement.
Definition at line 1328 of file ODBCCallableStatement.cxx.
View newest version in sPHENIX GitHub at line 1328 of file ODBCCallableStatement.cxx
References Acts::UnitConstants::e, TSQLStatement::fCurrentResult, TSQL::fImp, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::Statement::getResultSet(), odbc::SQLException::getSQLState(), ODBCXX_STRING_CSTR, and TSQL::Throw().
Int_t ODBCCallableStatement::GetResultSetConcurrency () virtual
Implements TSQLStatement.
Definition at line 1836 of file ODBCCallableStatement.cxx.
View newest version in sPHENIX GitHub at line 1836 of file ODBCCallableStatement.cxx
References Acts::UnitConstants::e, TSQL::fImp, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::Statement::getResultSetConcurrency(), odbc::SQLException::getSQLState(), ODBCXX_STRING_CSTR, and TSQL::Throw().
Int_t ODBCCallableStatement::GetResultSetType () virtual
Implements TSQLStatement.
Definition at line 1862 of file ODBCCallableStatement.cxx.
View newest version in sPHENIX GitHub at line 1862 of file ODBCCallableStatement.cxx
References Acts::UnitConstants::e, TSQL::fImp, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::Statement::getResultSetType(), odbc::SQLException::getSQLState(), ODBCXX_STRING_CSTR, and TSQL::Throw().
Short_t ODBCCallableStatement::GetShort (Int_t parameterIndex) virtual
Implements TSQLCallableStatement.
Definition at line 399 of file ODBCCallableStatement.cxx.
View newest version in sPHENIX GitHub at line 399 of file ODBCCallableStatement.cxx
References Acts::UnitConstants::e, TSQL::fImp, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::CallableStatement::getShort(), odbc::SQLException::getSQLState(), ODBCXX_STRING_CSTR, and TSQL::Throw().
TString ODBCCallableStatement::GetString (Int_t parameterIndex) virtual
Implements TSQLCallableStatement.
Definition at line 301 of file ODBCCallableStatement.cxx.
View newest version in sPHENIX GitHub at line 301 of file ODBCCallableStatement.cxx
References Acts::UnitConstants::e, TSQL::fImp, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), odbc::CallableStatement::getString(), ODBCXX_STRING, ODBCXX_STRING_CSTR, physmon_simulation::s, str, and TSQL::Throw().
TSQLTime ODBCCallableStatement::GetTime (Int_t parameterIndex) virtual
Implements TSQLCallableStatement.
Definition at line 623 of file ODBCCallableStatement.cxx.
View newest version in sPHENIX GitHub at line 623 of file ODBCCallableStatement.cxx
References Acts::UnitConstants::e, TSQL::fImp, odbc::SQLException::getErrorCode(), odbc::Time::getHour(), odbc::SQLException::getMessage(), odbc::Time::getMinute(), odbc::Time::getSecond(), odbc::SQLException::getSQLState(), odbc::CallableStatement::getTime(), ODBCXX_STRING_CSTR, and TSQL::Throw().
TSQLTimestamp ODBCCallableStatement::GetTimestamp (Int_t parameterIndex) virtual
Implements TSQLCallableStatement.
Definition at line 658 of file ODBCCallableStatement.cxx.
View newest version in sPHENIX GitHub at line 658 of file ODBCCallableStatement.cxx
References Acts::UnitConstants::e, TSQL::fImp, odbc::Date::getDay(), odbc::SQLException::getErrorCode(), odbc::Time::getHour(), odbc::SQLException::getMessage(), odbc::Time::getMinute(), odbc::Date::getMonth(), odbc::Timestamp::getNanos(), odbc::Time::getSecond(), odbc::SQLException::getSQLState(), odbc::CallableStatement::getTimestamp(), odbc::Date::getYear(), ODBCXX_STRING_CSTR, and TSQL::Throw().
Int_t ODBCCallableStatement::GetUpdateCount () virtual
Implements TSQLStatement.
Definition at line 1364 of file ODBCCallableStatement.cxx.
View newest version in sPHENIX GitHub at line 1364 of file ODBCCallableStatement.cxx
References Acts::UnitConstants::e, TSQL::fImp, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), odbc::Statement::getUpdateCount(), ODBCXX_STRING_CSTR, and TSQL::Throw().
void ODBCCallableStatement::RegisterOutParameter (Int_t parameterIndex, Int_t sqlType) virtual
Implements TSQLCallableStatement.
Definition at line 137 of file ODBCCallableStatement.cxx.
View newest version in sPHENIX GitHub at line 137 of file ODBCCallableStatement.cxx
References Acts::UnitConstants::e, TSQL::fImp, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), ODBCXX_STRING_CSTR, odbc::CallableStatement::registerOutParameter(), and TSQL::Throw().
void ODBCCallableStatement::RegisterOutParameter (Int_t parameterIndex, Int_t sqlType, Int_t scale) virtual
Implements TSQLCallableStatement.
Definition at line 202 of file ODBCCallableStatement.cxx.
View newest version in sPHENIX GitHub at line 202 of file ODBCCallableStatement.cxx
References Acts::UnitConstants::e, TSQL::fImp, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), ODBCXX_STRING_CSTR, odbc::CallableStatement::registerOutParameter(), and TSQL::Throw().
void ODBCCallableStatement::SetAsciiStream (Int_t parameterIndex, TBuffer * x, Int_t length) virtual
Implements TSQLPreparedStatement.
Definition at line 1073 of file ODBCCallableStatement.cxx.
View newest version in sPHENIX GitHub at line 1073 of file ODBCCallableStatement.cxx
References Acts::UnitConstants::e, TSQL::fImp, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), ODBCXX_STRING_CSTR, physmon_simulation::s, odbc::PreparedStatement::setAsciiStream(), and TSQL::Throw().
void ODBCCallableStatement::SetBinaryStream (Int_t parameterIndex, TBuffer * x, Int_t length) virtual
Implements TSQLPreparedStatement.
Definition at line 1111 of file ODBCCallableStatement.cxx.
View newest version in sPHENIX GitHub at line 1111 of file ODBCCallableStatement.cxx
References KFPMath::a, Acts::UnitConstants::e, TSQL::fImp, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), ODBCXX_STRING_CSTR, physmon_simulation::s, odbc::PreparedStatement::setBinaryStream(), and TSQL::Throw().
void ODBCCallableStatement::SetBoolean (Int_t parameterIndex, Bool_t x) virtual
Implements TSQLPreparedStatement.
Definition at line 725 of file ODBCCallableStatement.cxx.
View newest version in sPHENIX GitHub at line 725 of file ODBCCallableStatement.cxx
References Acts::UnitConstants::e, TSQL::fImp, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), ODBCXX_STRING_CSTR, odbc::PreparedStatement::setBoolean(), and TSQL::Throw().
void ODBCCallableStatement::SetByte (Int_t parameterIndex, Char_t x) virtual
Implements TSQLPreparedStatement.
Definition at line 752 of file ODBCCallableStatement.cxx.
View newest version in sPHENIX GitHub at line 752 of file ODBCCallableStatement.cxx
References Acts::UnitConstants::e, TSQL::fImp, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), ODBCXX_STRING_CSTR, odbc::PreparedStatement::setByte(), and TSQL::Throw().
void ODBCCallableStatement::SetBytes (Int_t parameterIndex, const TArrayC & x) virtual
Implements TSQLPreparedStatement.
Definition at line 943 of file ODBCCallableStatement.cxx.
View newest version in sPHENIX GitHub at line 943 of file ODBCCallableStatement.cxx
References Acts::UnitConstants::e, TSQL::fImp, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), ODBCXX_BYTES_C, ODBCXX_STRING_CSTR, odbc::PreparedStatement::setBytes(), and TSQL::Throw().
void ODBCCallableStatement::SetCursorName (const TString & name) virtual
Implements TSQLStatement.
Definition at line 1711 of file ODBCCallableStatement.cxx.
View newest version in sPHENIX GitHub at line 1711 of file ODBCCallableStatement.cxx
References Acts::UnitConstants::e, TSQL::fImp, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), ODBCXX_STRING_C, ODBCXX_STRING_CSTR, odbc::Statement::setCursorName(), and TSQL::Throw().
void ODBCCallableStatement::SetDate (Int_t parameterIndex, const TSQLDate & x) virtual
Implements TSQLPreparedStatement.
Definition at line 973 of file ODBCCallableStatement.cxx.
View newest version in sPHENIX GitHub at line 973 of file ODBCCallableStatement.cxx
References Acts::UnitConstants::e, TSQL::fImp, TSQLDate::GetDay(), odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), TSQLDate::GetMonth(), odbc::SQLException::getSQLState(), TSQLDate::GetYear(), ODBCXX_STRING_CSTR, odbc::PreparedStatement::setDate(), and TSQL::Throw().
void ODBCCallableStatement::SetDouble (Int_t parameterIndex, Double_t x) virtual
Implements TSQLPreparedStatement.
Definition at line 887 of file ODBCCallableStatement.cxx.
View newest version in sPHENIX GitHub at line 887 of file ODBCCallableStatement.cxx
References Acts::UnitConstants::e, TSQL::fImp, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), ODBCXX_STRING_CSTR, odbc::PreparedStatement::setDouble(), and TSQL::Throw().
void ODBCCallableStatement::SetEscapeProcessing (Bool_t enable = kTRUE) virtual
Implements TSQLStatement.
Definition at line 1540 of file ODBCCallableStatement.cxx.
View newest version in sPHENIX GitHub at line 1540 of file ODBCCallableStatement.cxx
References Acts::UnitConstants::e, TSQL::fImp, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), ODBCXX_STRING_CSTR, odbc::Statement::setEscapeProcessing(), and TSQL::Throw().
void ODBCCallableStatement::SetFetchDirection (Int_t direction) virtual
Implements TSQLStatement.
Definition at line 1748 of file ODBCCallableStatement.cxx.
View newest version in sPHENIX GitHub at line 1748 of file ODBCCallableStatement.cxx
References TSQL::fImp.
void ODBCCallableStatement::SetFetchSize (Int_t rows) virtual
Implements TSQLStatement.
Definition at line 1787 of file ODBCCallableStatement.cxx.
View newest version in sPHENIX GitHub at line 1787 of file ODBCCallableStatement.cxx
References TSQL::fImp.
void ODBCCallableStatement::SetFloat (Int_t parameterIndex, Float_t x) virtual
Implements TSQLPreparedStatement.
Definition at line 860 of file ODBCCallableStatement.cxx.
View newest version in sPHENIX GitHub at line 860 of file ODBCCallableStatement.cxx
References Acts::UnitConstants::e, TSQL::fImp, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), ODBCXX_STRING_CSTR, odbc::PreparedStatement::setFloat(), and TSQL::Throw().
void ODBCCallableStatement::SetInt (Int_t parameterIndex, Int_t x) virtual
Implements TSQLPreparedStatement.
Definition at line 806 of file ODBCCallableStatement.cxx.
View newest version in sPHENIX GitHub at line 806 of file ODBCCallableStatement.cxx
References Acts::UnitConstants::e, TSQL::fImp, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), ODBCXX_STRING_CSTR, odbc::PreparedStatement::setInt(), and TSQL::Throw().
void ODBCCallableStatement::SetLong (Int_t parameterIndex, Long_t x) virtual
Implements TSQLPreparedStatement.
Definition at line 833 of file ODBCCallableStatement.cxx.
View newest version in sPHENIX GitHub at line 833 of file ODBCCallableStatement.cxx
References Acts::UnitConstants::e, TSQL::fImp, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), ODBCXX_STRING_CSTR, odbc::PreparedStatement::setLong(), and TSQL::Throw().
void ODBCCallableStatement::SetMaxFieldSize (Int_t max) virtual
Implements TSQLStatement.
Definition at line 1460 of file ODBCCallableStatement.cxx.
View newest version in sPHENIX GitHub at line 1460 of file ODBCCallableStatement.cxx
References Acts::UnitConstants::e, TSQL::fImp, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), ODBCXX_STRING_CSTR, odbc::Statement::setMaxFieldSize(), and TSQL::Throw().
void ODBCCallableStatement::SetMaxRows (Int_t max) virtual
Implements TSQLStatement.
Definition at line 1516 of file ODBCCallableStatement.cxx.
View newest version in sPHENIX GitHub at line 1516 of file ODBCCallableStatement.cxx
References Acts::UnitConstants::e, TSQL::fImp, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), ODBCXX_STRING_CSTR, odbc::Statement::setMaxRows(), and TSQL::Throw().
void ODBCCallableStatement::SetNull (Int_t parameterIndex, Int_t sqlType) virtual
Implements TSQLPreparedStatement.
Definition at line 698 of file ODBCCallableStatement.cxx.
View newest version in sPHENIX GitHub at line 698 of file ODBCCallableStatement.cxx
References Acts::UnitConstants::e, TSQL::fImp, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), ODBCXX_STRING_CSTR, odbc::PreparedStatement::setNull(), and TSQL::Throw().
void ODBCCallableStatement::SetObject (Int_t parameterIndex, TObject * x) virtual
Implements TSQLPreparedStatement.
Definition at line 1149 of file ODBCCallableStatement.cxx.
View newest version in sPHENIX GitHub at line 1149 of file ODBCCallableStatement.cxx
References KFPMath::b, and TSQLPreparedStatement::SetBinaryStream().
void ODBCCallableStatement::SetQueryTimeout (Int_t seconds) virtual
Implements TSQLStatement.
Definition at line 1631 of file ODBCCallableStatement.cxx.
View newest version in sPHENIX GitHub at line 1631 of file ODBCCallableStatement.cxx
References Acts::UnitConstants::e, TSQL::fImp, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), ODBCXX_STRING_CSTR, odbc::Statement::setQueryTimeout(), and TSQL::Throw().
void ODBCCallableStatement::SetShort (Int_t parameterIndex, Short_t x) virtual
Implements TSQLPreparedStatement.
Definition at line 779 of file ODBCCallableStatement.cxx.
View newest version in sPHENIX GitHub at line 779 of file ODBCCallableStatement.cxx
References Acts::UnitConstants::e, TSQL::fImp, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), ODBCXX_STRING_CSTR, odbc::PreparedStatement::setShort(), and TSQL::Throw().
void ODBCCallableStatement::SetString (Int_t parameterIndex, const TString & x) virtual
Implements TSQLPreparedStatement.
Definition at line 914 of file ODBCCallableStatement.cxx.
View newest version in sPHENIX GitHub at line 914 of file ODBCCallableStatement.cxx
References Acts::UnitConstants::e, TSQL::fImp, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), ODBCXX_STRING_C, ODBCXX_STRING_CSTR, odbc::PreparedStatement::setString(), and TSQL::Throw().
void ODBCCallableStatement::SetTime (Int_t parameterIndex, const TSQLTime & x) virtual
Implements TSQLPreparedStatement.
Definition at line 1005 of file ODBCCallableStatement.cxx.
View newest version in sPHENIX GitHub at line 1005 of file ODBCCallableStatement.cxx
References Acts::UnitConstants::e, TSQL::fImp, odbc::SQLException::getErrorCode(), TSQLTime::GetHour(), odbc::SQLException::getMessage(), TSQLTime::GetMinute(), TSQLTime::GetSecond(), odbc::SQLException::getSQLState(), ODBCXX_STRING_CSTR, odbc::PreparedStatement::setTime(), and TSQL::Throw().
void ODBCCallableStatement::SetTimestamp (Int_t parameterIndex, const TSQLTimestamp & x) virtual
Implements TSQLPreparedStatement.
Definition at line 1037 of file ODBCCallableStatement.cxx.
View newest version in sPHENIX GitHub at line 1037 of file ODBCCallableStatement.cxx
References Acts::UnitConstants::e, TSQL::fImp, TSQLTimestamp::GetDay(), odbc::SQLException::getErrorCode(), TSQLTimestamp::GetHour(), odbc::SQLException::getMessage(), TSQLTimestamp::GetMinute(), TSQLTimestamp::GetMonth(), TSQLTimestamp::GetNanos(), TSQLTimestamp::GetSecond(), odbc::SQLException::getSQLState(), TSQLTimestamp::GetYear(), ODBCXX_STRING_CSTR, odbc::PreparedStatement::setTimestamp(), and TSQL::Throw().
Bool_t ODBCCallableStatement::WasNull () virtual
Implements TSQLCallableStatement.
Definition at line 270 of file ODBCCallableStatement.cxx.
View newest version in sPHENIX GitHub at line 270 of file ODBCCallableStatement.cxx
References Acts::UnitConstants::e, TSQL::fImp, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), ODBCXX_STRING_CSTR, TSQL::Throw(), and odbc::CallableStatement::wasNull().
Friends And Related Function Documentation
friend class ODBCConnection friend
Definition at line 17 of file ODBCCallableStatement.h.
View newest version in sPHENIX GitHub at line 17 of file ODBCCallableStatement.h
The documentation for this class was generated from the following files:
RDBC/blob/master/odbc/ODBCCallableStatement.h
RDBC/blob/master/odbc/ODBCCallableStatement.cxx