Analysis Software: tinyxml2::XMLElement Class Reference
tinyxml2::XMLElement Class Reference
#include <JETSCAPE/blob/main/external_packages/tinyxml2.h>
Public Types
enum { OPEN, CLOSED, CLOSING }
Public Member Functions
const char * Name () const
Get the name of an element (which is the Value() of the node.)
void SetName (const char *str, bool staticMem=false)
Set the name of the element.
virtual XMLElement * ToElement ()
Safely cast to an Element, or null.
virtual const XMLElement * ToElement () const
virtual bool Accept (XMLVisitor *visitor) const
const char * Attribute (const char *name, const char *value=0) const
int IntAttribute (const char *name, int defaultValue=0) const
unsigned UnsignedAttribute (const char *name, unsigned defaultValue=0) const
See IntAttribute()
int64_t Int64Attribute (const char *name, int64_t defaultValue=0) const
See IntAttribute()
bool BoolAttribute (const char *name, bool defaultValue=false) const
See IntAttribute()
double DoubleAttribute (const char *name, double defaultValue=0) const
See IntAttribute()
float FloatAttribute (const char *name, float defaultValue=0) const
See IntAttribute()
XMLError QueryIntAttribute (const char *name, int *value) const
XMLError QueryUnsignedAttribute (const char *name, unsigned int *value) const
See QueryIntAttribute()
XMLError QueryInt64Attribute (const char *name, int64_t *value) const
See QueryIntAttribute()
XMLError QueryBoolAttribute (const char *name, bool *value) const
See QueryIntAttribute()
XMLError QueryDoubleAttribute (const char *name, double *value) const
See QueryIntAttribute()
XMLError QueryFloatAttribute (const char *name, float *value) const
See QueryIntAttribute()
int QueryAttribute (const char *name, int *value) const
int QueryAttribute (const char *name, unsigned int *value) const
int QueryAttribute (const char *name, int64_t *value) const
int QueryAttribute (const char *name, bool *value) const
int QueryAttribute (const char *name, double *value) const
int QueryAttribute (const char *name, float *value) const
void SetAttribute (const char *name, const char *value)
Sets the named attribute to value.
void SetAttribute (const char *name, int value)
Sets the named attribute to value.
void SetAttribute (const char *name, unsigned value)
Sets the named attribute to value.
void SetAttribute (const char *name, int64_t value)
Sets the named attribute to value.
void SetAttribute (const char *name, bool value)
Sets the named attribute to value.
void SetAttribute (const char *name, double value)
Sets the named attribute to value.
void SetAttribute (const char *name, float value)
Sets the named attribute to value.
void DeleteAttribute (const char *name)
const XMLAttribute * FirstAttribute () const
Return the first attribute in the list.
const XMLAttribute * FindAttribute (const char *name) const
Query a specific attribute in the list.
const char * GetText () const
void SetText (const char *inText)
void SetText (int value)
Convenience method for setting text inside an element. See SetText() for important limitations.
void SetText (unsigned value)
Convenience method for setting text inside an element. See SetText() for important limitations.
void SetText (int64_t value)
Convenience method for setting text inside an element. See SetText() for important limitations.
void SetText (bool value)
Convenience method for setting text inside an element. See SetText() for important limitations.
void SetText (double value)
Convenience method for setting text inside an element. See SetText() for important limitations.
void SetText (float value)
Convenience method for setting text inside an element. See SetText() for important limitations.
XMLError QueryIntText (int *ival) const
XMLError QueryUnsignedText (unsigned *uval) const
See QueryIntText()
XMLError QueryInt64Text (int64_t *uval) const
See QueryIntText()
XMLError QueryBoolText (bool *bval) const
See QueryIntText()
XMLError QueryDoubleText (double *dval) const
See QueryIntText()
XMLError QueryFloatText (float *fval) const
See QueryIntText()
int IntText (int defaultValue=0) const
unsigned UnsignedText (unsigned defaultValue=0) const
See QueryIntText()
int64_t Int64Text (int64_t defaultValue=0) const
See QueryIntText()
bool BoolText (bool defaultValue=false) const
See QueryIntText()
double DoubleText (double defaultValue=0) const
See QueryIntText()
float FloatText (float defaultValue=0) const
See QueryIntText()
int ClosingType () const
virtual XMLNode * ShallowClone (XMLDocument *document) const
virtual bool ShallowEqual (const XMLNode *compare) const
Public Member Functions inherited from tinyxml2::XMLNode
const XMLDocument * GetDocument () const
Get the XMLDocument that owns this XMLNode.
XMLDocument * GetDocument ()
Get the XMLDocument that owns this XMLNode.
virtual XMLText * ToText ()
Safely cast to Text, or null.
virtual XMLComment * ToComment ()
Safely cast to a Comment, or null.
virtual XMLDocument * ToDocument ()
Safely cast to a Document, or null.
virtual XMLDeclaration * ToDeclaration ()
Safely cast to a Declaration, or null.
virtual XMLUnknown * ToUnknown ()
Safely cast to an Unknown, or null.
virtual const XMLText * ToText () const
virtual const XMLComment * ToComment () const
virtual const XMLDocument * ToDocument () const
virtual const XMLDeclaration * ToDeclaration () const
virtual const XMLUnknown * ToUnknown () const
const char * Value () const
void SetValue (const char *val, bool staticMem=false)
const XMLNode * Parent () const
Get the parent of this node on the DOM.
XMLNode * Parent ()
bool NoChildren () const
Returns true if this node has no children.
const XMLNode * FirstChild () const
Get the first child node, or null if none exists.
XMLNode * FirstChild ()
const XMLElement * FirstChildElement (const char *name=0) const
XMLElement * FirstChildElement (const char *name=0)
const XMLNode * LastChild () const
Get the last child node, or null if none exists.
XMLNode * LastChild ()
const XMLElement * LastChildElement (const char *name=0) const
XMLElement * LastChildElement (const char *name=0)
const XMLNode * PreviousSibling () const
Get the previous (left) sibling node of this node.
XMLNode * PreviousSibling ()
const XMLElement * PreviousSiblingElement (const char *name=0) const
Get the previous (left) sibling element of this node, with an optionally supplied name.
XMLElement * PreviousSiblingElement (const char *name=0)
const XMLNode * NextSibling () const
Get the next (right) sibling node of this node.
XMLNode * NextSibling ()
const XMLElement * NextSiblingElement (const char *name=0) const
Get the next (right) sibling element of this node, with an optionally supplied name.
XMLElement * NextSiblingElement (const char *name=0)
XMLNode * InsertEndChild (XMLNode *addThis)
XMLNode * LinkEndChild (XMLNode *addThis)
XMLNode * InsertFirstChild (XMLNode *addThis)
XMLNode * InsertAfterChild (XMLNode *afterThis, XMLNode *addThis)
void DeleteChildren ()
void DeleteChild (XMLNode *node)
void SetUserData (void *userData)
void * GetUserData () const
Protected Member Functions
char * ParseDeep (char *p, StrPair *endTag)
Protected Member Functions inherited from tinyxml2::XMLNode
XMLNode (XMLDocument *)
virtual ~XMLNode ()
Private Types
enum { BUF_SIZE = 200 }
Private Member Functions
XMLElement (XMLDocument *doc)
virtual ~XMLElement ()
XMLElement (const XMLElement &)
void operator= (const XMLElement &)
XMLAttribute * FindAttribute (const char *name)
XMLAttribute * FindOrCreateAttribute (const char *name)
char * ParseAttributes (char *p)
XMLAttribute * CreateAttribute ()
Static Private Member Functions
static void DeleteAttribute (XMLAttribute *attribute)
Private Attributes
int _closingType
XMLAttribute * _rootAttribute
Friends
class XMLDocument
Additional Inherited Members
Protected Attributes inherited from tinyxml2::XMLNode
XMLDocument * _document
XMLNode * _parent
StrPair _value
XMLNode * _firstChild
XMLNode * _lastChild
XMLNode * _prev
XMLNode * _next
void * _userData
Detailed Description
The element is a container class. It has a value, the element name, and can contain other elements, text, comments, and unknowns. Elements also contain an arbitrary number of attributes.
Definition at line 1189 of file tinyxml2.h.
View newest version in sPHENIX GitHub at line 1189 of file tinyxml2.h
Member Enumeration Documentation
anonymous enum
Enumerator:
OPEN
CLOSED
CLOSING
Definition at line 1539 of file tinyxml2.h.
View newest version in sPHENIX GitHub at line 1539 of file tinyxml2.h
anonymous enum private
Enumerator:
BUF_SIZE
Definition at line 1568 of file tinyxml2.h.
View newest version in sPHENIX GitHub at line 1568 of file tinyxml2.h
Constructor & Destructor Documentation
tinyxml2::XMLElement::XMLElement (XMLDocument * doc) private
Definition at line 1435 of file tinyxml2.cc.
View newest version in sPHENIX GitHub at line 1435 of file tinyxml2.cc
tinyxml2::XMLElement::~XMLElement () private virtual
Definition at line 1442 of file tinyxml2.cc.
View newest version in sPHENIX GitHub at line 1442 of file tinyxml2.cc
References tinyxml2::XMLAttribute::_next, _rootAttribute, DeleteAttribute(), and next.
tinyxml2::XMLElement::XMLElement (const XMLElement &) private
Member Function Documentation
bool tinyxml2::XMLElement::Accept (XMLVisitor * visitor) const virtual
Accept a hierarchical visit of the nodes in the TinyXML-2 DOM. Every node in the XML tree will be conditionally visited and the host will be called back via the XMLVisitor interface.
This is essentially a SAX interface for TinyXML-2. (Note however it doesn't re-parse the XML for the callbacks, so the performance of TinyXML-2 is unchanged by using this interface versus any other.)
The interface has been based on ideas from:
http://www.saxproject.org/
http://c2.com/cgi/wiki?HierarchicalVisitorPattern
Which are both good references for "visiting".
An example of using Accept():
XMLPrinter printer;
tinyxmlDoc.Accept(&printer);
const char* xmlcstr = printer.CStr();
Implements tinyxml2::XMLNode.
Definition at line 1896 of file tinyxml2.cc.
View newest version in sPHENIX GitHub at line 1896 of file tinyxml2.cc
References _rootAttribute, tinyxml2::XMLNode::FirstChild(), TIXMLASSERT, tinyxml2::XMLVisitor::VisitEnter(), and tinyxml2::XMLVisitor::VisitExit().
const char * tinyxml2::XMLElement::Attribute (const char * name, const char * value = 0) const
Given an attribute name, Attribute() returns the value for the attribute of that name, or null if none exists. For example:
const char* value = ele->Attribute("foo");
The 'value' parameter is normally null. However, if specified, the attribute will only be returned if the 'name' and 'value' match. This allow you to write code:
if (ele->Attribute("foo", "bar")) callFooIsBar();
rather than:
if (ele->Attribute("foo")) {
        if ( strcmp( ele->Attribute( "foo" ), "bar" ) == 0 ) callFooIsBar();
}
Definition at line 1463 of file tinyxml2.cc.
View newest version in sPHENIX GitHub at line 1463 of file tinyxml2.cc
References KFPMath::a, FindAttribute(), tinyxml2::XMLUtil::StringEqual(), value, and tinyxml2::XMLAttribute::Value().
Referenced by Brick::InitTask(), and ParseAttributes().
bool tinyxml2::XMLElement::BoolAttribute (const char * name, bool defaultValue = false) const
See IntAttribute()
Definition at line 1496 of file tinyxml2.cc.
View newest version in sPHENIX GitHub at line 1496 of file tinyxml2.cc
References KFPMath::b, and QueryBoolAttribute().
bool tinyxml2::XMLElement::BoolText (bool defaultValue = false) const
See QueryIntText()
Definition at line 1683 of file tinyxml2.cc.
View newest version in sPHENIX GitHub at line 1683 of file tinyxml2.cc
References KFPMath::b, and QueryBoolText().
int tinyxml2::XMLElement::ClosingType () const inline
Definition at line 1544 of file tinyxml2.h.
View newest version in sPHENIX GitHub at line 1544 of file tinyxml2.h
Referenced by tinyxml2::XMLNode::ParseDeep().
XMLAttribute * tinyxml2::XMLElement::CreateAttribute () private
Definition at line 1815 of file tinyxml2.cc.
View newest version in sPHENIX GitHub at line 1815 of file tinyxml2.cc
References tinyxml2::XMLDocument::_attributePool, tinyxml2::XMLNode::_document, tinyxml2::XMLAttribute::_memPool, tinyxml2::MemPoolT< ITEM_SIZE >::Alloc(), tinyxml2::MemPoolT< ITEM_SIZE >::ItemSize(), tinyxml2::MemPoolT< ITEM_SIZE >::SetTracked(), and TIXMLASSERT.
Referenced by FindOrCreateAttribute(), and ParseAttributes().
void tinyxml2::XMLElement::DeleteAttribute (const char * name)
Delete an attribute.
Definition at line 1731 of file tinyxml2.cc.
View newest version in sPHENIX GitHub at line 1731 of file tinyxml2.cc
References tinyxml2::XMLAttribute::_next, _rootAttribute, KFPMath::a, and tinyxml2::XMLUtil::StringEqual().
Referenced by ParseAttributes(), and ~XMLElement().
void tinyxml2::XMLElement::DeleteAttribute (XMLAttribute * attribute) static private
Definition at line 1805 of file tinyxml2.cc.
View newest version in sPHENIX GitHub at line 1805 of file tinyxml2.cc
References tinyxml2::XMLAttribute::_memPool, tinyxml2::MemPool::Free(), and tinyxml2::XMLAttribute::~XMLAttribute().
double tinyxml2::XMLElement::DoubleAttribute (const char * name, double defaultValue = 0) const
See IntAttribute()
Definition at line 1503 of file tinyxml2.cc.
View newest version in sPHENIX GitHub at line 1503 of file tinyxml2.cc
References QueryDoubleAttribute().
double tinyxml2::XMLElement::DoubleText (double defaultValue = 0) const
See QueryIntText()
Definition at line 1690 of file tinyxml2.cc.
View newest version in sPHENIX GitHub at line 1690 of file tinyxml2.cc
References QueryDoubleText().
const XMLAttribute * tinyxml2::XMLElement::FindAttribute (const char * name) const
Query a specific attribute in the list.
Definition at line 1452 of file tinyxml2.cc.
View newest version in sPHENIX GitHub at line 1452 of file tinyxml2.cc
References _rootAttribute, KFPMath::a, perf_headwind::name, and tinyxml2::XMLUtil::StringEqual().
Referenced by Attribute().
XMLAttribute* tinyxml2::XMLElement::FindAttribute (const char * name) inline private
Definition at line 1559 of file tinyxml2.h.
View newest version in sPHENIX GitHub at line 1559 of file tinyxml2.h
XMLAttribute * tinyxml2::XMLElement::FindOrCreateAttribute (const char * name) private
Definition at line 1705 of file tinyxml2.cc.
View newest version in sPHENIX GitHub at line 1705 of file tinyxml2.cc
References tinyxml2::XMLAttribute::_next, _rootAttribute, CreateAttribute(), perf_headwind::name, tinyxml2::XMLAttribute::SetName(), tinyxml2::XMLUtil::StringEqual(), and TIXMLASSERT.
const XMLAttribute* tinyxml2::XMLElement::FirstAttribute () const inline
Return the first attribute in the list.
Definition at line 1403 of file tinyxml2.h.
View newest version in sPHENIX GitHub at line 1403 of file tinyxml2.h
Referenced by ShallowClone(), and ShallowEqual().
float tinyxml2::XMLElement::FloatAttribute (const char * name, float defaultValue = 0) const
See IntAttribute()
Definition at line 1510 of file tinyxml2.cc.
View newest version in sPHENIX GitHub at line 1510 of file tinyxml2.cc
References f, and QueryFloatAttribute().
float tinyxml2::XMLElement::FloatText (float defaultValue = 0) const
See QueryIntText()
Definition at line 1697 of file tinyxml2.cc.
View newest version in sPHENIX GitHub at line 1697 of file tinyxml2.cc
References f, and QueryFloatText().
const char * tinyxml2::XMLElement::GetText () const
Convenience function for easy access to the text inside an element. Although easy and concise, GetText() is limited compared to getting the XMLText child and accessing it directly.
If the first child of 'this' is a XMLText, the GetText() returns the character string of the Text node, else null is returned.
This is a convenient method for getting the text of simple contained text:
<foo>This is text</foo>
        const char* str = fooElement->GetText();
'str' will be a pointer to "This is text".
Note that this function can be misleading. If the element foo was created from this XML:
        <foo><b>This is text</b></foo>
then the value of str would be null. The first child node isn't a text node, it is another element. From this XML:
        <foo>This is <b>text</b></foo>
GetText() will return "This is ".
Definition at line 1517 of file tinyxml2.cc.
View newest version in sPHENIX GitHub at line 1517 of file tinyxml2.cc
References tinyxml2::XMLNode::FirstChild(), tinyxml2::XMLNode::ToText(), and tinyxml2::XMLNode::Value().
Referenced by Jetscape::JetScape::DetermineTaskListFromXML(), Jetscape::JetScapeXML::GetElementText(), HybridHadronization::Init(), and Jetscape::JetScape::SetModuleId().
int64_t tinyxml2::XMLElement::Int64Attribute (const char * name, int64_t defaultValue = 0) const
See IntAttribute()
Definition at line 1489 of file tinyxml2.cc.
View newest version in sPHENIX GitHub at line 1489 of file tinyxml2.cc
References i, and QueryInt64Attribute().
int64_t tinyxml2::XMLElement::Int64Text (int64_t defaultValue = 0) const
See QueryIntText()
Definition at line 1676 of file tinyxml2.cc.
View newest version in sPHENIX GitHub at line 1676 of file tinyxml2.cc
References i, and QueryInt64Text().
int tinyxml2::XMLElement::IntAttribute (const char * name, int defaultValue = 0) const
Given an attribute name, IntAttribute() returns the value of the attribute interpreted as an integer. The default value will be returned if the attribute isn't present, or if there is an error. (For a method with error checking, see QueryIntAttribute()).
Definition at line 1475 of file tinyxml2.cc.
View newest version in sPHENIX GitHub at line 1475 of file tinyxml2.cc
References i, and QueryIntAttribute().
int tinyxml2::XMLElement::IntText (int defaultValue = 0) const
Definition at line 1662 of file tinyxml2.cc.
View newest version in sPHENIX GitHub at line 1662 of file tinyxml2.cc
References i, and QueryIntText().
const char* tinyxml2::XMLElement::Name () const inline
Get the name of an element (which is the Value() of the node.)
Definition at line 1194 of file tinyxml2.h.
View newest version in sPHENIX GitHub at line 1194 of file tinyxml2.h
References testing::Value().
Referenced by Jetscape::JetScape::DetermineTaskListFromXML(), Jetscape::JetScapeXML::GetXMLElementMain(), Jetscape::JetScapeXML::GetXMLElementUser(), HybridHadronization::Init(), ParseAttributes(), tinyxml2::XMLNode::ParseDeep(), Jetscape::JetScape::recurseToBuild(), Jetscape::JetScape::recurseToSearch(), Jetscape::JetScape::SetModuleId(), ShallowEqual(), tinyxml2::XMLNode::ToElementWithName(), and tinyxml2::XMLPrinter::VisitEnter().
void tinyxml2::XMLElement::operator= (const XMLElement &) private
char * tinyxml2::XMLElement::ParseAttributes (char * p) private
Definition at line 1750 of file tinyxml2.cc.
View newest version in sPHENIX GitHub at line 1750 of file tinyxml2.cc
References _closingType, tinyxml2::XMLNode::_document, tinyxml2::XMLAttribute::_next, _rootAttribute, Attribute(), CLOSED, CreateAttribute(), DeleteAttribute(), tinyxml2::XMLUtil::IsNameStartChar(), tinyxml2::XMLAttribute::Name(), Name(), merge_hashes::p, tinyxml2::XMLAttribute::ParseDeep(), tinyxml2::XMLDocument::ProcessEntities(), tinyxml2::XMLDocument::SetError(), tinyxml2::XMLUtil::SkipWhiteSpace(), start, TIXMLASSERT, tinyxml2::XML_ERROR_PARSING_ATTRIBUTE, and tinyxml2::XML_ERROR_PARSING_ELEMENT.
Referenced by ParseDeep().
char * tinyxml2::XMLElement::ParseDeep (char * p, StrPair * endTag) protected virtual
Reimplemented from tinyxml2::XMLNode.
Definition at line 1828 of file tinyxml2.cc.
View newest version in sPHENIX GitHub at line 1828 of file tinyxml2.cc
References _closingType, tinyxml2::XMLNode::_value, CLOSING, tinyxml2::StrPair::Empty(), merge_hashes::p, ParseAttributes(), tinyxml2::XMLNode::ParseDeep(), tinyxml2::StrPair::ParseName(), and tinyxml2::XMLUtil::SkipWhiteSpace().
int tinyxml2::XMLElement::QueryAttribute (const char * name, int * value) const inline
Given an attribute name, QueryAttribute() returns XML_SUCCESS, XML_WRONG_ATTRIBUTE_TYPE if the conversion can't be performed, or XML_NO_ATTRIBUTE if the attribute doesn't exist. It is overloaded for the primitive types, and is a generally more convenient replacement of QueryIntAttribute() and related functions.
If successful, the result of the conversion will be written to 'value'. If not successful, nothing will be written to 'value'. This allows you to provide default value:
int value = 10;
QueryAttribute("foo", &value);                // if "foo" isn't found, value will still be 10
Definition at line 1335 of file tinyxml2.h.
View newest version in sPHENIX GitHub at line 1335 of file tinyxml2.h
int tinyxml2::XMLElement::QueryAttribute (const char * name, unsigned int * value) const inline
Definition at line 1339 of file tinyxml2.h.
View newest version in sPHENIX GitHub at line 1339 of file tinyxml2.h
int tinyxml2::XMLElement::QueryAttribute (const char * name, int64_t * value) const inline
Definition at line 1343 of file tinyxml2.h.
View newest version in sPHENIX GitHub at line 1343 of file tinyxml2.h
int tinyxml2::XMLElement::QueryAttribute (const char * name, bool * value) const inline
Definition at line 1347 of file tinyxml2.h.
View newest version in sPHENIX GitHub at line 1347 of file tinyxml2.h
int tinyxml2::XMLElement::QueryAttribute (const char * name, double * value) const inline
Definition at line 1351 of file tinyxml2.h.
View newest version in sPHENIX GitHub at line 1351 of file tinyxml2.h
int tinyxml2::XMLElement::QueryAttribute (const char * name, float * value) const inline
Definition at line 1355 of file tinyxml2.h.
View newest version in sPHENIX GitHub at line 1355 of file tinyxml2.h
XMLError tinyxml2::XMLElement::QueryBoolAttribute (const char * name, bool * value) const inline
See QueryIntAttribute()
Definition at line 1293 of file tinyxml2.h.
View newest version in sPHENIX GitHub at line 1293 of file tinyxml2.h
References KFPMath::a, tinyxml2::XMLAttribute::QueryBoolValue(), and tinyxml2::XML_NO_ATTRIBUTE.
Referenced by BoolAttribute().
XMLError tinyxml2::XMLElement::QueryBoolText (bool * bval) const
See QueryIntText()
Definition at line 1624 of file tinyxml2.cc.
View newest version in sPHENIX GitHub at line 1624 of file tinyxml2.cc
References tinyxml2::XMLNode::FirstChild(), t, tinyxml2::XMLUtil::ToBool(), tinyxml2::XMLNode::ToText(), tinyxml2::XMLNode::Value(), tinyxml2::XML_CAN_NOT_CONVERT_TEXT, tinyxml2::XML_NO_TEXT_NODE, and tinyxml2::XML_SUCCESS.
Referenced by BoolText().
XMLError tinyxml2::XMLElement::QueryDoubleAttribute (const char * name, double * value) const inline
See QueryIntAttribute()
Definition at line 1301 of file tinyxml2.h.
View newest version in sPHENIX GitHub at line 1301 of file tinyxml2.h
References KFPMath::a, tinyxml2::XMLAttribute::QueryDoubleValue(), and tinyxml2::XML_NO_ATTRIBUTE.
Referenced by DoubleAttribute().
XMLError tinyxml2::XMLElement::QueryDoubleText (double * dval) const
See QueryIntText()
Definition at line 1637 of file tinyxml2.cc.
View newest version in sPHENIX GitHub at line 1637 of file tinyxml2.cc
References tinyxml2::XMLNode::FirstChild(), t, tinyxml2::XMLUtil::ToDouble(), tinyxml2::XMLNode::ToText(), tinyxml2::XMLNode::Value(), tinyxml2::XML_CAN_NOT_CONVERT_TEXT, tinyxml2::XML_NO_TEXT_NODE, and tinyxml2::XML_SUCCESS.
Referenced by DoubleText(), and Jetscape::JetScapeXML::GetElementDouble().
XMLError tinyxml2::XMLElement::QueryFloatAttribute (const char * name, float * value) const inline
See QueryIntAttribute()
Definition at line 1309 of file tinyxml2.h.
View newest version in sPHENIX GitHub at line 1309 of file tinyxml2.h
References KFPMath::a, tinyxml2::XMLAttribute::QueryFloatValue(), and tinyxml2::XML_NO_ATTRIBUTE.
Referenced by FloatAttribute().
XMLError tinyxml2::XMLElement::QueryFloatText (float * fval) const
See QueryIntText()
Definition at line 1650 of file tinyxml2.cc.
View newest version in sPHENIX GitHub at line 1650 of file tinyxml2.cc
References tinyxml2::XMLNode::FirstChild(), t, tinyxml2::XMLUtil::ToFloat(), tinyxml2::XMLNode::ToText(), tinyxml2::XMLNode::Value(), tinyxml2::XML_CAN_NOT_CONVERT_TEXT, tinyxml2::XML_NO_TEXT_NODE, and tinyxml2::XML_SUCCESS.
Referenced by FloatText().
XMLError tinyxml2::XMLElement::QueryInt64Attribute (const char * name, int64_t * value) const inline
See QueryIntAttribute()
Definition at line 1284 of file tinyxml2.h.
View newest version in sPHENIX GitHub at line 1284 of file tinyxml2.h
References KFPMath::a, tinyxml2::XMLAttribute::QueryInt64Value(), and tinyxml2::XML_NO_ATTRIBUTE.
Referenced by Int64Attribute().
XMLError tinyxml2::XMLElement::QueryInt64Text (int64_t * uval) const
See QueryIntText()
Definition at line 1611 of file tinyxml2.cc.
View newest version in sPHENIX GitHub at line 1611 of file tinyxml2.cc
References tinyxml2::XMLNode::FirstChild(), t, tinyxml2::XMLUtil::ToInt64(), tinyxml2::XMLNode::ToText(), tinyxml2::XMLNode::Value(), tinyxml2::XML_CAN_NOT_CONVERT_TEXT, tinyxml2::XML_NO_TEXT_NODE, and tinyxml2::XML_SUCCESS.
Referenced by Int64Text().
XMLError tinyxml2::XMLElement::QueryIntAttribute (const char * name, int * value) const inline
Given an attribute name, QueryIntAttribute() returns XML_SUCCESS, XML_WRONG_ATTRIBUTE_TYPE if the conversion can't be performed, or XML_NO_ATTRIBUTE if the attribute doesn't exist. If successful, the result of the conversion will be written to 'value'. If not successful, nothing will be written to 'value'. This allows you to provide default value:
int value = 10;
QueryIntAttribute("foo", &value);             // if "foo" isn't found, value will still be 10
Definition at line 1266 of file tinyxml2.h.
View newest version in sPHENIX GitHub at line 1266 of file tinyxml2.h
References KFPMath::a, tinyxml2::XMLAttribute::QueryIntValue(), and tinyxml2::XML_NO_ATTRIBUTE.
Referenced by IntAttribute().
XMLError tinyxml2::XMLElement::QueryIntText (int * ival) const
Convenience method to query the value of a child text node. This is probably best shown by example. Given you have a document is this form:
        <point>
                <x>1</x>
                <y>1.4</y>
        </point>
The QueryIntText() and similar functions provide a safe and easier way to get to the "value" of x and y.
        int x = 0;
        float y = 0;    // types of x and y are contrived for example
        const XMLElement* xElement = pointElement->FirstChildElement( "x" );
        const XMLElement* yElement = pointElement->FirstChildElement( "y" );
        xElement->QueryIntText( &x );
        yElement->QueryFloatText( &y );
Returns
XML_SUCCESS (0) on success, XML_CAN_NOT_CONVERT_TEXT if the text cannot be converted to the requested type, and XML_NO_TEXT_NODE if there is no child text to query.
Definition at line 1585 of file tinyxml2.cc.
View newest version in sPHENIX GitHub at line 1585 of file tinyxml2.cc
References tinyxml2::XMLNode::FirstChild(), t, tinyxml2::XMLUtil::ToInt(), tinyxml2::XMLNode::ToText(), tinyxml2::XMLNode::Value(), tinyxml2::XML_CAN_NOT_CONVERT_TEXT, tinyxml2::XML_NO_TEXT_NODE, and tinyxml2::XML_SUCCESS.
Referenced by Jetscape::JetScapeXML::GetElementInt(), and IntText().
XMLError tinyxml2::XMLElement::QueryUnsignedAttribute (const char * name, unsigned int * value) const inline
See QueryIntAttribute()
Definition at line 1275 of file tinyxml2.h.
View newest version in sPHENIX GitHub at line 1275 of file tinyxml2.h
References KFPMath::a, tinyxml2::XMLAttribute::QueryUnsignedValue(), and tinyxml2::XML_NO_ATTRIBUTE.
Referenced by UnsignedAttribute().
XMLError tinyxml2::XMLElement::QueryUnsignedText (unsigned * uval) const
See QueryIntText()
Definition at line 1598 of file tinyxml2.cc.
View newest version in sPHENIX GitHub at line 1598 of file tinyxml2.cc
References tinyxml2::XMLNode::FirstChild(), t, tinyxml2::XMLNode::ToText(), tinyxml2::XMLUtil::ToUnsigned(), tinyxml2::XMLNode::Value(), tinyxml2::XML_CAN_NOT_CONVERT_TEXT, tinyxml2::XML_NO_TEXT_NODE, and tinyxml2::XML_SUCCESS.
Referenced by HybridHadronization::Init(), PythiaGun::InitTask(), epemGun::InitTask(), Jetscape::JetScapeTaskSupport::ReadSeedFromXML(), and UnsignedText().
void tinyxml2::XMLElement::SetAttribute (const char * name, const char * value) inline
Sets the named attribute to value.
Definition at line 1360 of file tinyxml2.h.
View newest version in sPHENIX GitHub at line 1360 of file tinyxml2.h
References KFPMath::a, and tinyxml2::XMLAttribute::SetAttribute().
Referenced by ShallowClone().
void tinyxml2::XMLElement::SetAttribute (const char * name, int value) inline
Sets the named attribute to value.
Definition at line 1365 of file tinyxml2.h.
View newest version in sPHENIX GitHub at line 1365 of file tinyxml2.h
References KFPMath::a, and tinyxml2::XMLAttribute::SetAttribute().
void tinyxml2::XMLElement::SetAttribute (const char * name, unsigned value) inline
Sets the named attribute to value.
Definition at line 1370 of file tinyxml2.h.
View newest version in sPHENIX GitHub at line 1370 of file tinyxml2.h
References KFPMath::a, and tinyxml2::XMLAttribute::SetAttribute().
void tinyxml2::XMLElement::SetAttribute (const char * name, int64_t value) inline
Sets the named attribute to value.
Definition at line 1376 of file tinyxml2.h.
View newest version in sPHENIX GitHub at line 1376 of file tinyxml2.h
References KFPMath::a, and tinyxml2::XMLAttribute::SetAttribute().
void tinyxml2::XMLElement::SetAttribute (const char * name, bool value) inline
Sets the named attribute to value.
Definition at line 1382 of file tinyxml2.h.
View newest version in sPHENIX GitHub at line 1382 of file tinyxml2.h
References KFPMath::a, and tinyxml2::XMLAttribute::SetAttribute().
void tinyxml2::XMLElement::SetAttribute (const char * name, double value) inline
Sets the named attribute to value.
Definition at line 1387 of file tinyxml2.h.
View newest version in sPHENIX GitHub at line 1387 of file tinyxml2.h
References KFPMath::a, and tinyxml2::XMLAttribute::SetAttribute().
void tinyxml2::XMLElement::SetAttribute (const char * name, float value) inline
Sets the named attribute to value.
Definition at line 1392 of file tinyxml2.h.
View newest version in sPHENIX GitHub at line 1392 of file tinyxml2.h
References KFPMath::a, and tinyxml2::XMLAttribute::SetAttribute().
void tinyxml2::XMLElement::SetName (const char * str, bool staticMem = false) inline
Set the name of the element.
Definition at line 1198 of file tinyxml2.h.
View newest version in sPHENIX GitHub at line 1198 of file tinyxml2.h
References SetValue().
void tinyxml2::XMLElement::SetText (const char * inText)
Convenience function for easy access to the text inside an element. Although easy and concise, SetText() is limited compared to creating an XMLText child and mutating it directly.
If the first child of 'this' is a XMLText, SetText() sets its value to the given string, otherwise it will create a first child that is an XMLText.
This is a convenient method for setting the text of simple contained text:
<foo>This is text</foo>
        fooElement->SetText( "Hullaballoo!" );
<foo>Hullaballoo!</foo>
Note that this function can be misleading. If the element foo was created from this XML:
        <foo><b>This is text</b></foo>
then it will not change "This is text", but rather prefix it with a text element:
        <foo>Hullaballoo!<b>This is text</b></foo>
    For this XML:
        <foo />
SetText() will generate
        <foo>Hullaballoo!</foo>
Definition at line 1526 of file tinyxml2.cc.
View newest version in sPHENIX GitHub at line 1526 of file tinyxml2.cc
References tinyxml2::XMLNode::FirstChild(), tinyxml2::XMLNode::GetDocument(), tinyxml2::XMLNode::InsertFirstChild(), tinyxml2::XMLDocument::NewText(), tinyxml2::XMLNode::SetValue(), and tinyxml2::XMLNode::ToText().
Referenced by SetText().
void tinyxml2::XMLElement::SetText (int value)
Convenience method for setting text inside an element. See SetText() for important limitations.
Definition at line 1537 of file tinyxml2.cc.
View newest version in sPHENIX GitHub at line 1537 of file tinyxml2.cc
References BUF_SIZE, SetText(), and tinyxml2::XMLUtil::ToStr().
void tinyxml2::XMLElement::SetText (unsigned value)
Convenience method for setting text inside an element. See SetText() for important limitations.
Definition at line 1545 of file tinyxml2.cc.
View newest version in sPHENIX GitHub at line 1545 of file tinyxml2.cc
References BUF_SIZE, SetText(), and tinyxml2::XMLUtil::ToStr().
void tinyxml2::XMLElement::SetText (int64_t value)
Convenience method for setting text inside an element. See SetText() for important limitations.
Definition at line 1553 of file tinyxml2.cc.
View newest version in sPHENIX GitHub at line 1553 of file tinyxml2.cc
References BUF_SIZE, SetText(), and tinyxml2::XMLUtil::ToStr().
void tinyxml2::XMLElement::SetText (bool value)
Convenience method for setting text inside an element. See SetText() for important limitations.
Definition at line 1561 of file tinyxml2.cc.
View newest version in sPHENIX GitHub at line 1561 of file tinyxml2.cc
References BUF_SIZE, SetText(), and tinyxml2::XMLUtil::ToStr().
void tinyxml2::XMLElement::SetText (double value)
Convenience method for setting text inside an element. See SetText() for important limitations.
Definition at line 1577 of file tinyxml2.cc.
View newest version in sPHENIX GitHub at line 1577 of file tinyxml2.cc
References BUF_SIZE, SetText(), and tinyxml2::XMLUtil::ToStr().
void tinyxml2::XMLElement::SetText (float value)
Convenience method for setting text inside an element. See SetText() for important limitations.
Definition at line 1569 of file tinyxml2.cc.
View newest version in sPHENIX GitHub at line 1569 of file tinyxml2.cc
References BUF_SIZE, SetText(), and tinyxml2::XMLUtil::ToStr().
XMLNode * tinyxml2::XMLElement::ShallowClone (XMLDocument * document) const virtual
Make a copy of this node, but not its children. You may pass in a Document pointer that will be the owner of the new Node. If the 'document' is null, then the node returned will be allocated from the current Document. (this->GetDocument())
Note: if called on a XMLDocument, this will return null.
Implements tinyxml2::XMLNode.
Definition at line 1857 of file tinyxml2.cc.
View newest version in sPHENIX GitHub at line 1857 of file tinyxml2.cc
References tinyxml2::XMLNode::_document, KFPMath::a, fixGDML::element, FirstAttribute(), tinyxml2::XMLDocument::NewElement(), SetAttribute(), and tinyxml2::XMLNode::Value().
bool tinyxml2::XMLElement::ShallowEqual (const XMLNode * compare) const virtual
Test if 2 nodes are the same, but don't test children. The 2 nodes do not need to be in the same Document.
Note: if called on a XMLDocument, this will return false.
Implements tinyxml2::XMLNode.
Definition at line 1870 of file tinyxml2.cc.
View newest version in sPHENIX GitHub at line 1870 of file tinyxml2.cc
References KFPMath::a, KFPMath::b, FirstAttribute(), Name(), tinyxml2::XMLAttribute::Next(), tinyxml2::XMLUtil::StringEqual(), TIXMLASSERT, tinyxml2::XMLNode::ToElement(), and tinyxml2::XMLAttribute::Value().
virtual XMLElement* tinyxml2::XMLElement::ToElement () inline virtual
Safely cast to an Element, or null.
Reimplemented from tinyxml2::XMLNode.
Definition at line 1202 of file tinyxml2.h.
View newest version in sPHENIX GitHub at line 1202 of file tinyxml2.h
virtual const XMLElement* tinyxml2::XMLElement::ToElement () const inline virtual
Reimplemented from tinyxml2::XMLNode.
Definition at line 1205 of file tinyxml2.h.
View newest version in sPHENIX GitHub at line 1205 of file tinyxml2.h
unsigned tinyxml2::XMLElement::UnsignedAttribute (const char * name, unsigned defaultValue = 0) const
See IntAttribute()
Definition at line 1482 of file tinyxml2.cc.
View newest version in sPHENIX GitHub at line 1482 of file tinyxml2.cc
References i, and QueryUnsignedAttribute().
unsigned tinyxml2::XMLElement::UnsignedText (unsigned defaultValue = 0) const
See QueryIntText()
Definition at line 1669 of file tinyxml2.cc.
View newest version in sPHENIX GitHub at line 1669 of file tinyxml2.cc
References i, and QueryUnsignedText().
Friends And Related Function Documentation
friend class XMLDocument friend
Definition at line 1191 of file tinyxml2.h.
View newest version in sPHENIX GitHub at line 1191 of file tinyxml2.h
Member Data Documentation
int tinyxml2::XMLElement::_closingType private
Definition at line 1569 of file tinyxml2.h.
View newest version in sPHENIX GitHub at line 1569 of file tinyxml2.h
Referenced by ParseAttributes(), and ParseDeep().
XMLAttribute* tinyxml2::XMLElement::_rootAttribute private
Definition at line 1573 of file tinyxml2.h.
View newest version in sPHENIX GitHub at line 1573 of file tinyxml2.h
Referenced by Accept(), DeleteAttribute(), FindAttribute(), FindOrCreateAttribute(), ParseAttributes(), and ~XMLElement().
The documentation for this class was generated from the following files:
JETSCAPE/blob/main/external_packages/tinyxml2.h
JETSCAPE/blob/main/external_packages/tinyxml2.cc