Analysis Software: Acts::FpeMonitor::Result Struct Reference
Acts::FpeMonitor::Result Struct Reference
#include <acts/blob/sPHENIX/Plugins/FpeMonitoring/include/Acts/Plugins/FpeMonitoring/FpeMonitor.hpp>
Classes
struct FpeInfo
Public Member Functions
Result merged (const Result &with) const
void merge (const Result &with)
bool encountered (FpeType type) const
unsigned int count (FpeType type) const
const std::vector< FpeInfo > & stackTraces () const
unsigned int numStackTraces () const
void deduplicate ()
bool contains (FpeType type, const boost::stacktrace::stacktrace &st) const
void summary (std::ostream &os, std::size_t depth=std::numeric_limits< std::size_t >::max()) const
Result ()=default
operator bool () const
void add (Acts::FpeType type, void *stackPtr, std::size_t bufferSize)
Private Attributes
std::vector< FpeInfo > m_stracktraces
std::array< unsigned int, 32 > m_counts {}
friend FpeMonitor
Detailed Description
Definition at line 78 of file FpeMonitor.hpp.
View newest version in sPHENIX GitHub at line 78 of file FpeMonitor.hpp
Constructor & Destructor Documentation
Acts::FpeMonitor::Result::Result () default
Member Function Documentation
void Acts::FpeMonitor::Result::add (Acts::FpeType type, void * stackPtr, std::size_t bufferSize)
bool Acts::FpeMonitor::Result::contains (FpeType type, const boost::stacktrace::stacktrace & st) const
unsigned int Acts::FpeMonitor::Result::count (FpeType type) const
Referenced by Acts::Python::addFramework(), and Acts::Test::BOOST_AUTO_TEST_CASE().
void Acts::FpeMonitor::Result::deduplicate ()
Referenced by Acts::Test::BOOST_AUTO_TEST_CASE().
bool Acts::FpeMonitor::Result::encountered (FpeType type) const
Referenced by Acts::Test::BOOST_AUTO_TEST_CASE().
void Acts::FpeMonitor::Result::merge (const Result & with)
Referenced by Acts::Python::addFramework(), and ActsExamples::Sequencer::fpeResult().
Result Acts::FpeMonitor::Result::merged (const Result & with) const
Referenced by Acts::Python::addFramework(), and Acts::Test::BOOST_AUTO_TEST_CASE().
unsigned int Acts::FpeMonitor::Result::numStackTraces () const
Acts::FpeMonitor::Result::operator bool () const inline
Definition at line 108 of file FpeMonitor.hpp.
View newest version in sPHENIX GitHub at line 108 of file FpeMonitor.hpp
const std::vector<FpeInfo>& Acts::FpeMonitor::Result::stackTraces () const
Referenced by Acts::Test::BOOST_AUTO_TEST_CASE().
void Acts::FpeMonitor::Result::summary (std::ostream & os, std::size_t depth = std::numeric_limits< std::size_t >::max()) const
Referenced by Acts::Python::addFramework().
Member Data Documentation
friend Acts::FpeMonitor::Result::FpeMonitor private
Definition at line 116 of file FpeMonitor.hpp.
View newest version in sPHENIX GitHub at line 116 of file FpeMonitor.hpp
std::array<unsigned int, 32> Acts::FpeMonitor::Result::m_counts {} private
Definition at line 114 of file FpeMonitor.hpp.
View newest version in sPHENIX GitHub at line 114 of file FpeMonitor.hpp
std::vector<FpeInfo> Acts::FpeMonitor::Result::m_stracktraces private
Definition at line 113 of file FpeMonitor.hpp.
View newest version in sPHENIX GitHub at line 113 of file FpeMonitor.hpp
The documentation for this struct was generated from the following file:
acts/blob/sPHENIX/Plugins/FpeMonitoring/include/Acts/Plugins/FpeMonitoring/FpeMonitor.hpp