Analysis Software: MicromegasRawHitv1 Class Reference
MicromegasRawHitv1 Class Reference
#include <coresoftware/blob/master/offline/framework/ffarawobjects/MicromegasRawHitv1.h>
Public Member Functions
MicromegasRawHitv1 ()=default
MicromegasRawHitv1 (MicromegasRawHit *)
~MicromegasRawHitv1 () override=default
void identify (std::ostream &os=std::cout) const override
uint64_t get_bco () const override
void set_bco (const uint64_t val) override
uint64_t get_gtm_bco () const override
void set_gtm_bco (const uint64_t val) override
int32_t get_packetid () const override
void set_packetid (const int32_t val) override
uint16_t get_fee () const override
void set_fee (uint16_t const val) override
uint16_t get_channel () const override
void set_channel (uint16_t const val) override
uint16_t get_sampaaddress () const override
void set_sampaaddress (uint16_t const val) override
uint16_t get_sampachannel () const override
void set_sampachannel (uint16_t const val) override
uint16_t get_samples () const override
void set_samples (uint16_t const val) override
uint16_t get_adc (size_t sample) const override
void set_adc (size_t sample, uint16_t val) override
Public Member Functions inherited from MicromegasRawHit
MicromegasRawHit ()=default
virtual ~MicromegasRawHit ()=default
Public Member Functions inherited from PHObject
PHObject ()
ctor
~PHObject () override
dtor
virtual PHObject * CloneMe () const
Virtual copy constructor.
virtual PHObject * clone () const final
PHObject * Clone (const char *newname="") const final
void Copy (TObject &object) const final
virtual void Reset ()
Clear Event.
virtual int isValid () const
isValid returns non zero if object contains vailid data
virtual int Integrate () const
virtual int Integrate (PHObject *)
virtual void CopyFrom (const PHObject *obj)
Private Attributes
uint64_t bco = std::numeric_limits<uint64_t>::max()
uint64_t gtm_bco = std::numeric_limits<uint64_t>::max()
int32_t packetid = std::numeric_limits<int32_t>::max()
uint16_t fee = std::numeric_limits<uint16_t>::max()
uint16_t channel = std::numeric_limits<uint16_t>::max()
uint16_t sampaaddress = std::numeric_limits<uint16_t>::max()
uint16_t sampachannel = std::numeric_limits<uint16_t>::max()
uint16_t samples = std::numeric_limits<uint16_t>::max()
std::vector< uint16_t > adc
adc value for each sample
Detailed Description
Definition at line 11 of file MicromegasRawHitv1.h.
View newest version in sPHENIX GitHub at line 11 of file MicromegasRawHitv1.h
Constructor & Destructor Documentation
MicromegasRawHitv1::MicromegasRawHitv1 () default
MicromegasRawHitv1::MicromegasRawHitv1 (MicromegasRawHit * source)
Definition at line 3 of file MicromegasRawHitv1.cc.
View newest version in sPHENIX GitHub at line 3 of file MicromegasRawHitv1.cc
References MicromegasRawHit::get_adc(), MicromegasRawHit::get_bco(), MicromegasRawHit::get_channel(), MicromegasRawHit::get_fee(), MicromegasRawHit::get_gtm_bco(), MicromegasRawHit::get_packetid(), MicromegasRawHit::get_sampaaddress(), MicromegasRawHit::get_sampachannel(), MicromegasRawHit::get_samples(), i, set_adc(), set_bco(), set_channel(), set_fee(), set_gtm_bco(), set_packetid(), set_sampaaddress(), set_sampachannel(), and set_samples().
MicromegasRawHitv1::~MicromegasRawHitv1 () override default
Member Function Documentation
uint16_t MicromegasRawHitv1::get_adc (size_t sample) const inline override virtual
Reimplemented from MicromegasRawHit.
Definition at line 64 of file MicromegasRawHitv1.h.
View newest version in sPHENIX GitHub at line 64 of file MicromegasRawHitv1.h
References adc, and assert.
uint64_t MicromegasRawHitv1::get_bco () const inline override virtual
Reimplemented from MicromegasRawHit.
Definition at line 25 of file MicromegasRawHitv1.h.
View newest version in sPHENIX GitHub at line 25 of file MicromegasRawHitv1.h
References bco.
uint16_t MicromegasRawHitv1::get_channel () const inline override virtual
Reimplemented from MicromegasRawHit.
Definition at line 41 of file MicromegasRawHitv1.h.
View newest version in sPHENIX GitHub at line 41 of file MicromegasRawHitv1.h
References channel.
uint16_t MicromegasRawHitv1::get_fee () const inline override virtual
Reimplemented from MicromegasRawHit.
Definition at line 37 of file MicromegasRawHitv1.h.
View newest version in sPHENIX GitHub at line 37 of file MicromegasRawHitv1.h
References fee.
uint64_t MicromegasRawHitv1::get_gtm_bco () const inline override virtual
Reimplemented from MicromegasRawHit.
Definition at line 29 of file MicromegasRawHitv1.h.
View newest version in sPHENIX GitHub at line 29 of file MicromegasRawHitv1.h
References gtm_bco.
int32_t MicromegasRawHitv1::get_packetid () const inline override virtual
Reimplemented from MicromegasRawHit.
Definition at line 33 of file MicromegasRawHitv1.h.
View newest version in sPHENIX GitHub at line 33 of file MicromegasRawHitv1.h
References packetid.
uint16_t MicromegasRawHitv1::get_sampaaddress () const inline override virtual
Reimplemented from MicromegasRawHit.
Definition at line 45 of file MicromegasRawHitv1.h.
View newest version in sPHENIX GitHub at line 45 of file MicromegasRawHitv1.h
References sampaaddress.
uint16_t MicromegasRawHitv1::get_sampachannel () const inline override virtual
Reimplemented from MicromegasRawHit.
Definition at line 49 of file MicromegasRawHitv1.h.
View newest version in sPHENIX GitHub at line 49 of file MicromegasRawHitv1.h
References sampachannel.
uint16_t MicromegasRawHitv1::get_samples () const inline override virtual
Reimplemented from MicromegasRawHit.
Definition at line 53 of file MicromegasRawHitv1.h.
View newest version in sPHENIX GitHub at line 53 of file MicromegasRawHitv1.h
References samples.
void MicromegasRawHitv1::identify (std::ostream & os = std::cout) const override virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from PHObject.
Definition at line 18 of file MicromegasRawHitv1.cc.
View newest version in sPHENIX GitHub at line 18 of file MicromegasRawHitv1.cc
References bco, and packetid.
void MicromegasRawHitv1::set_adc (size_t sample, uint16_t val) inline override virtual
Reimplemented from MicromegasRawHit.
Definition at line 71 of file MicromegasRawHitv1.h.
View newest version in sPHENIX GitHub at line 71 of file MicromegasRawHitv1.h
References adc, and assert.
Referenced by MicromegasRawHitv1().
void MicromegasRawHitv1::set_bco (const uint64_t val) inline override virtual
Reimplemented from MicromegasRawHit.
Definition at line 27 of file MicromegasRawHitv1.h.
View newest version in sPHENIX GitHub at line 27 of file MicromegasRawHitv1.h
References bco.
Referenced by MicromegasRawHitv1().
void MicromegasRawHitv1::set_channel (uint16_t const val) inline override virtual
Reimplemented from MicromegasRawHit.
Definition at line 43 of file MicromegasRawHitv1.h.
View newest version in sPHENIX GitHub at line 43 of file MicromegasRawHitv1.h
References channel.
Referenced by MicromegasRawHitv1().
void MicromegasRawHitv1::set_fee (uint16_t const val) inline override virtual
Reimplemented from MicromegasRawHit.
Definition at line 39 of file MicromegasRawHitv1.h.
View newest version in sPHENIX GitHub at line 39 of file MicromegasRawHitv1.h
References fee.
Referenced by MicromegasRawHitv1().
void MicromegasRawHitv1::set_gtm_bco (const uint64_t val) inline override virtual
Reimplemented from MicromegasRawHit.
Definition at line 31 of file MicromegasRawHitv1.h.
View newest version in sPHENIX GitHub at line 31 of file MicromegasRawHitv1.h
References gtm_bco.
Referenced by MicromegasRawHitv1().
void MicromegasRawHitv1::set_packetid (const int32_t val) inline override virtual
Reimplemented from MicromegasRawHit.
Definition at line 35 of file MicromegasRawHitv1.h.
View newest version in sPHENIX GitHub at line 35 of file MicromegasRawHitv1.h
References packetid.
Referenced by MicromegasRawHitv1().
void MicromegasRawHitv1::set_sampaaddress (uint16_t const val) inline override virtual
Reimplemented from MicromegasRawHit.
Definition at line 47 of file MicromegasRawHitv1.h.
View newest version in sPHENIX GitHub at line 47 of file MicromegasRawHitv1.h
References sampaaddress.
Referenced by MicromegasRawHitv1().
void MicromegasRawHitv1::set_sampachannel (uint16_t const val) inline override virtual
Reimplemented from MicromegasRawHit.
Definition at line 51 of file MicromegasRawHitv1.h.
View newest version in sPHENIX GitHub at line 51 of file MicromegasRawHitv1.h
References sampachannel.
Referenced by MicromegasRawHitv1().
void MicromegasRawHitv1::set_samples (uint16_t const val) inline override virtual
Reimplemented from MicromegasRawHit.
Definition at line 55 of file MicromegasRawHitv1.h.
View newest version in sPHENIX GitHub at line 55 of file MicromegasRawHitv1.h
References adc, and samples.
Referenced by MicromegasRawHitv1().
Member Data Documentation
std::vector<uint16_t> MicromegasRawHitv1::adc private
adc value for each sample
Definition at line 89 of file MicromegasRawHitv1.h.
View newest version in sPHENIX GitHub at line 89 of file MicromegasRawHitv1.h
Referenced by get_adc(), set_adc(), and set_samples().
uint64_t MicromegasRawHitv1::bco = std::numeric_limits<uint64_t>::max() private
Definition at line 79 of file MicromegasRawHitv1.h.
View newest version in sPHENIX GitHub at line 79 of file MicromegasRawHitv1.h
Referenced by get_bco(), identify(), and set_bco().
uint16_t MicromegasRawHitv1::channel = std::numeric_limits<uint16_t>::max() private
Definition at line 83 of file MicromegasRawHitv1.h.
View newest version in sPHENIX GitHub at line 83 of file MicromegasRawHitv1.h
Referenced by get_channel(), and set_channel().
uint16_t MicromegasRawHitv1::fee = std::numeric_limits<uint16_t>::max() private
Definition at line 82 of file MicromegasRawHitv1.h.
View newest version in sPHENIX GitHub at line 82 of file MicromegasRawHitv1.h
Referenced by get_fee(), and set_fee().
uint64_t MicromegasRawHitv1::gtm_bco = std::numeric_limits<uint64_t>::max() private
Definition at line 80 of file MicromegasRawHitv1.h.
View newest version in sPHENIX GitHub at line 80 of file MicromegasRawHitv1.h
Referenced by get_gtm_bco(), and set_gtm_bco().
int32_t MicromegasRawHitv1::packetid = std::numeric_limits<int32_t>::max() private
Definition at line 81 of file MicromegasRawHitv1.h.
View newest version in sPHENIX GitHub at line 81 of file MicromegasRawHitv1.h
Referenced by get_packetid(), identify(), and set_packetid().
uint16_t MicromegasRawHitv1::sampaaddress = std::numeric_limits<uint16_t>::max() private
Definition at line 84 of file MicromegasRawHitv1.h.
View newest version in sPHENIX GitHub at line 84 of file MicromegasRawHitv1.h
Referenced by get_sampaaddress(), and set_sampaaddress().
uint16_t MicromegasRawHitv1::sampachannel = std::numeric_limits<uint16_t>::max() private
Definition at line 85 of file MicromegasRawHitv1.h.
View newest version in sPHENIX GitHub at line 85 of file MicromegasRawHitv1.h
Referenced by get_sampachannel(), and set_sampachannel().
uint16_t MicromegasRawHitv1::samples = std::numeric_limits<uint16_t>::max() private
Definition at line 86 of file MicromegasRawHitv1.h.
View newest version in sPHENIX GitHub at line 86 of file MicromegasRawHitv1.h
Referenced by get_samples(), and set_samples().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/framework/ffarawobjects/MicromegasRawHitv1.h
coresoftware/blob/master/offline/framework/ffarawobjects/MicromegasRawHitv1.cc