Analysis Software: TpcPrototypeCluster Class Reference
TpcPrototypeCluster Class Reference
Version 1 of TrkrCluster.
#include <prototype/blob/master/offline/packages/tpc2019/TpcPrototypeCluster.h>
Public Member Functions
TpcPrototypeCluster ()
ctor
virtual ~TpcPrototypeCluster ()
dtor
virtual void identify (std::ostream &os=std::cout) const
virtual void Reset ()
Clear Event.
virtual int isValid () const
isValid returns non zero if object contains vailid data
virtual PHObject * CloneMe () const
Virtual copy constructor.
virtual void setClusKey (TrkrDefs::cluskey id)
virtual TrkrDefs::cluskey getClusKey () const
virtual float getX () const
virtual void setX (float x)
virtual float getY () const
virtual void setY (float y)
virtual float getZ () const
virtual void setZ (float z)
virtual float getPosition (int coor) const
virtual void setPosition (int coor, float xi)
virtual void setGlobal ()
virtual void setLocal ()
virtual bool isGlobal ()
virtual unsigned int getAdc () const
virtual void setAdc (unsigned int adc)
virtual float getSize (unsigned int i, unsigned int j) const
virtual void setSize (unsigned int i, unsigned int j, float value)
virtual float getError (unsigned int i, unsigned int j) const
virtual void setError (unsigned int i, unsigned int j, float value)
virtual float getPhiSize () const
virtual float getZSize () const
virtual float getRPhiError () const
virtual float getPhiError () const
virtual float getZError () const
double getAvgPadAzimuth () const
void setAvgPadAzimuth (double avgPadAzimuth)
int getAvgPadRadial () const
void setAvgPadRadial (int avgPadRadial)
double getDeltaAzimuthBin () const
void setDeltaAzimuthBin (double deltaAzimuthBin)
double getDeltaZ () const
void setDeltaZ (double deltaZ)
int getMaxPadAzimuth () const
void setMaxPadAzimuth (int maxPadAzimuth)
int getMaxSample () const
void setMaxSample (int maxSample)
int getMinPadAzimuth () const
void setMinPadAzimuth (int minPadAzimuth)
int getMinSample () const
void setMinSample (int minSample)
const std::map< int, double > & getPadAzimuthPeaks () const
void setPadAzimuthPeaks (const std::map< int, double > &padAzimuthPeaks)
const std::map< int,
std::vector< double > > & getPadAzimuthSamples () const
void setPadAzimuthSamples (const std::map< int, std::vector< double >> &padAzimuthSamples)
const std::set< int > & getPadAzimuths () const
void setPadAzimuths (const std::set< int > &padAzimuths)
const std::map< int,
std::vector< double > > & getPadRadialSamples () const
void setPadRadialSamples (const std::map< int, std::vector< double >> &padRadialSamples)
const std::set< int > & getPadRadials () const
void setPadRadials (const std::set< int > &padRadials)
double getPeak () const
void setPeak (double peak)
double getPeakSample () const
void setPeakSample (double peakSample)
double getPedstal () const
void setPedstal (double pedstal)
const std::set< int > & getSamples () const
void setSamples (const std::set< int > &samples)
int getSizePadAzimuth () const
void setSizePadAzimuth (int sizePadAzimuth)
int getSizePadRadial () const
void setSizePadRadial (int sizePadRadial)
const std::vector< double > & getSumSamples () const
void setSumSamples (const std::vector< double > &sumSamples)
Public Member Functions inherited from TrkrCluster
~TrkrCluster () override=default
dtor
virtual void CopyFrom (const TrkrCluster &)
copy content from base class
virtual void CopyFrom (TrkrCluster *)
copy content from base class
virtual float getLocalX () const
virtual void setLocalX (float)
virtual float getLocalY () const
virtual void setLocalY (float)
virtual void setMaxAdc (uint16_t)
virtual unsigned int getMaxAdc () const
virtual char getOverlap () const
virtual void setOverlap (char)
virtual char getEdge () const
virtual void setEdge (char)
virtual void setTime (const float)
virtual float getTime () const
virtual char getSize () const
virtual void setActsLocalError (unsigned int, unsigned int, float)
Acts functions, for Acts modules use only.
virtual float getActsLocalError (unsigned int, unsigned int) const
virtual TrkrDefs::subsurfkey getSubSurfKey () const
virtual void setSubSurfKey (TrkrDefs::subsurfkey)
virtual bool isGlobal () const
Public Member Functions inherited from PHObject
PHObject ()
ctor
~PHObject () override
dtor
virtual PHObject * clone () const final
PHObject * Clone (const char *newname="") const final
void Copy (TObject &object) const final
virtual int Integrate () const
virtual int Integrate (PHObject *)
virtual void CopyFrom (const PHObject *obj)
Protected Attributes
TrkrDefs::cluskey m_cluskey
float m_pos [3]
bool m_isGlobal
unsigned int m_adc
float m_size [6]
float m_err [6]
std::set< int > pad_radials
std::set< int > pad_azimuths
std::set< int > samples
std::map< int, std::vector
< double > > pad_radial_samples
std::map< int, std::vector
< double > > pad_azimuth_samples
std::vector< double > sum_samples
int min_sample
int max_sample
int min_pad_azimuth
int max_pad_azimuth
double peak
double peak_sample
double pedstal
std::map< int, double > pad_azimuth_peaks
int avg_pad_radial
pad coordinate
double avg_pad_azimuth
int size_pad_radial
cluster size in units of pad bins
int size_pad_azimuth
double delta_azimuth_bin
double delta_z
z size per ADC sample bin
Additional Inherited Members
Protected Member Functions inherited from TrkrCluster
TrkrCluster ()=default
Detailed Description
Version 1 of TrkrCluster.
Note - D. McGlinchey June 2018: CINT does not like "override", so ignore where CINT complains. Should be checked with ROOT 6 once migration occurs.
Definition at line 28 of file TpcPrototypeCluster.h.
View newest version in sPHENIX GitHub at line 28 of file TpcPrototypeCluster.h
Constructor & Destructor Documentation
TpcPrototypeCluster::TpcPrototypeCluster ()
ctor
Definition at line 43 of file TpcPrototypeCluster.cc.
View newest version in sPHENIX GitHub at line 43 of file TpcPrototypeCluster.cc
References i, j, m_pos, setError(), and setSize().
Referenced by CloneMe().
virtual TpcPrototypeCluster::~TpcPrototypeCluster () inline virtual
dtor
Definition at line 35 of file TpcPrototypeCluster.h.
View newest version in sPHENIX GitHub at line 35 of file TpcPrototypeCluster.h
Member Function Documentation
virtual PHObject* TpcPrototypeCluster::CloneMe () const inline virtual
Virtual copy constructor.
Reimplemented from PHObject.
Definition at line 40 of file TpcPrototypeCluster.h.
View newest version in sPHENIX GitHub at line 40 of file TpcPrototypeCluster.h
References TpcPrototypeCluster().
virtual unsigned int TpcPrototypeCluster::getAdc () const inline virtual
Reimplemented from TrkrCluster.
Definition at line 60 of file TpcPrototypeCluster.h.
View newest version in sPHENIX GitHub at line 60 of file TpcPrototypeCluster.h
References m_adc.
Referenced by identify().
double TpcPrototypeCluster::getAvgPadAzimuth () const inline
Definition at line 80 of file TpcPrototypeCluster.h.
View newest version in sPHENIX GitHub at line 80 of file TpcPrototypeCluster.h
References avg_pad_azimuth.
int TpcPrototypeCluster::getAvgPadRadial () const inline
Definition at line 90 of file TpcPrototypeCluster.h.
View newest version in sPHENIX GitHub at line 90 of file TpcPrototypeCluster.h
References avg_pad_radial.
virtual TrkrDefs::cluskey TpcPrototypeCluster::getClusKey () const inline virtual
Definition at line 42 of file TpcPrototypeCluster.h.
View newest version in sPHENIX GitHub at line 42 of file TpcPrototypeCluster.h
References m_cluskey.
Referenced by identify().
double TpcPrototypeCluster::getDeltaAzimuthBin () const inline
Definition at line 100 of file TpcPrototypeCluster.h.
View newest version in sPHENIX GitHub at line 100 of file TpcPrototypeCluster.h
References delta_azimuth_bin.
double TpcPrototypeCluster::getDeltaZ () const inline
Definition at line 110 of file TpcPrototypeCluster.h.
View newest version in sPHENIX GitHub at line 110 of file TpcPrototypeCluster.h
References delta_z.
float TpcPrototypeCluster::getError (unsigned int i, unsigned int j) const virtual
Reimplemented from TrkrCluster.
Definition at line 239 of file TpcPrototypeCluster.cc.
View newest version in sPHENIX GitHub at line 239 of file TpcPrototypeCluster.cc
References m_err.
Referenced by getZError(), identify(), and isValid().
int TpcPrototypeCluster::getMaxPadAzimuth () const inline
Definition at line 120 of file TpcPrototypeCluster.h.
View newest version in sPHENIX GitHub at line 120 of file TpcPrototypeCluster.h
References max_pad_azimuth.
int TpcPrototypeCluster::getMaxSample () const inline
Definition at line 130 of file TpcPrototypeCluster.h.
View newest version in sPHENIX GitHub at line 130 of file TpcPrototypeCluster.h
References max_sample.
int TpcPrototypeCluster::getMinPadAzimuth () const inline
Definition at line 140 of file TpcPrototypeCluster.h.
View newest version in sPHENIX GitHub at line 140 of file TpcPrototypeCluster.h
References min_pad_azimuth.
int TpcPrototypeCluster::getMinSample () const inline
Definition at line 150 of file TpcPrototypeCluster.h.
View newest version in sPHENIX GitHub at line 150 of file TpcPrototypeCluster.h
References min_sample.
const std::map<int, double>& TpcPrototypeCluster::getPadAzimuthPeaks () const inline
Definition at line 160 of file TpcPrototypeCluster.h.
View newest version in sPHENIX GitHub at line 160 of file TpcPrototypeCluster.h
References pad_azimuth_peaks.
const std::set<int>& TpcPrototypeCluster::getPadAzimuths () const inline
Definition at line 180 of file TpcPrototypeCluster.h.
View newest version in sPHENIX GitHub at line 180 of file TpcPrototypeCluster.h
References pad_azimuths.
const std::map<int, std::vector<double> >& TpcPrototypeCluster::getPadAzimuthSamples () const inline
Definition at line 170 of file TpcPrototypeCluster.h.
View newest version in sPHENIX GitHub at line 170 of file TpcPrototypeCluster.h
References pad_azimuth_samples.
const std::set<int>& TpcPrototypeCluster::getPadRadials () const inline
Definition at line 200 of file TpcPrototypeCluster.h.
View newest version in sPHENIX GitHub at line 200 of file TpcPrototypeCluster.h
References pad_radials.
const std::map<int, std::vector<double> >& TpcPrototypeCluster::getPadRadialSamples () const inline
Definition at line 190 of file TpcPrototypeCluster.h.
View newest version in sPHENIX GitHub at line 190 of file TpcPrototypeCluster.h
References pad_radial_samples.
double TpcPrototypeCluster::getPeak () const inline
Definition at line 210 of file TpcPrototypeCluster.h.
View newest version in sPHENIX GitHub at line 210 of file TpcPrototypeCluster.h
References peak.
double TpcPrototypeCluster::getPeakSample () const inline
Definition at line 220 of file TpcPrototypeCluster.h.
View newest version in sPHENIX GitHub at line 220 of file TpcPrototypeCluster.h
References peak_sample.
double TpcPrototypeCluster::getPedstal () const inline
Definition at line 230 of file TpcPrototypeCluster.h.
View newest version in sPHENIX GitHub at line 230 of file TpcPrototypeCluster.h
References pedstal.
float TpcPrototypeCluster::getPhiError () const virtual
Reimplemented from TrkrCluster.
Definition at line 254 of file TpcPrototypeCluster.cc.
View newest version in sPHENIX GitHub at line 254 of file TpcPrototypeCluster.cc
References getRPhiError(), m_pos, Acts::UnitConstants::rad, and square().
float TpcPrototypeCluster::getPhiSize () const virtual
Reimplemented from TrkrCluster.
Definition at line 244 of file TpcPrototypeCluster.cc.
View newest version in sPHENIX GitHub at line 244 of file TpcPrototypeCluster.cc
Referenced by identify().
virtual float TpcPrototypeCluster::getPosition (int coor) const inline virtual
Reimplemented from TrkrCluster.
Definition at line 52 of file TpcPrototypeCluster.h.
View newest version in sPHENIX GitHub at line 52 of file TpcPrototypeCluster.h
References m_pos.
Referenced by TpcPrototypeUnpacker::exportDSTCluster(), identify(), and isValid().
float TpcPrototypeCluster::getRPhiError () const virtual
Reimplemented from TrkrCluster.
Definition at line 261 of file TpcPrototypeCluster.cc.
View newest version in sPHENIX GitHub at line 261 of file TpcPrototypeCluster.cc
Referenced by getPhiError().
const std::set<int>& TpcPrototypeCluster::getSamples () const inline
Definition at line 240 of file TpcPrototypeCluster.h.
View newest version in sPHENIX GitHub at line 240 of file TpcPrototypeCluster.h
References samples.
float TpcPrototypeCluster::getSize (unsigned int i, unsigned int j) const virtual
Reimplemented from TrkrCluster.
Definition at line 228 of file TpcPrototypeCluster.cc.
View newest version in sPHENIX GitHub at line 228 of file TpcPrototypeCluster.cc
References m_size.
int TpcPrototypeCluster::getSizePadAzimuth () const inline
Definition at line 250 of file TpcPrototypeCluster.h.
View newest version in sPHENIX GitHub at line 250 of file TpcPrototypeCluster.h
References size_pad_azimuth.
int TpcPrototypeCluster::getSizePadRadial () const inline
Definition at line 260 of file TpcPrototypeCluster.h.
View newest version in sPHENIX GitHub at line 260 of file TpcPrototypeCluster.h
References size_pad_radial.
const std::vector<double>& TpcPrototypeCluster::getSumSamples () const inline
Definition at line 270 of file TpcPrototypeCluster.h.
View newest version in sPHENIX GitHub at line 270 of file TpcPrototypeCluster.h
References sum_samples.
virtual float TpcPrototypeCluster::getX (void) const inline virtual
Reimplemented from TrkrCluster.
Definition at line 46 of file TpcPrototypeCluster.h.
View newest version in sPHENIX GitHub at line 46 of file TpcPrototypeCluster.h
References m_pos.
virtual float TpcPrototypeCluster::getY (void) const inline virtual
Reimplemented from TrkrCluster.
Definition at line 48 of file TpcPrototypeCluster.h.
View newest version in sPHENIX GitHub at line 48 of file TpcPrototypeCluster.h
References m_pos.
virtual float TpcPrototypeCluster::getZ (void) const inline virtual
Reimplemented from TrkrCluster.
Definition at line 50 of file TpcPrototypeCluster.h.
View newest version in sPHENIX GitHub at line 50 of file TpcPrototypeCluster.h
References m_pos.
float TpcPrototypeCluster::getZError () const virtual
Reimplemented from TrkrCluster.
Definition at line 266 of file TpcPrototypeCluster.cc.
View newest version in sPHENIX GitHub at line 266 of file TpcPrototypeCluster.cc
References getError().
float TpcPrototypeCluster::getZSize () const virtual
Reimplemented from TrkrCluster.
Definition at line 249 of file TpcPrototypeCluster.cc.
View newest version in sPHENIX GitHub at line 249 of file TpcPrototypeCluster.cc
References TrkrCluster::getSize().
Referenced by identify().
void TpcPrototypeCluster::identify (std::ostream & os = std::cout) const virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from TrkrCluster.
Definition at line 73 of file TpcPrototypeCluster.cc.
View newest version in sPHENIX GitHub at line 73 of file TpcPrototypeCluster.cc
References avg_pad_azimuth, avg_pad_radial, delta_azimuth_bin, delta_z, fixGDML::element, getAdc(), getClusKey(), getError(), getPhiSize(), getPosition(), TrkrCluster::getSize(), getZSize(), m_isGlobal, max_pad_azimuth, max_sample, min_pad_azimuth, min_sample, pad_azimuth_peaks, pad_azimuth_samples, pad_azimuths, pad_radial_samples, pad_radials, peak, peak_sample, pedstal, samples, size_pad_azimuth, size_pad_radial, and sum_samples.
Referenced by TpcPrototypeUnpacker::exportDSTCluster(), and TpcPrototypeGenFitTrkFitter::MakeTpcPrototypeTrack().
virtual bool TpcPrototypeCluster::isGlobal () inline virtual
Definition at line 56 of file TpcPrototypeCluster.h.
View newest version in sPHENIX GitHub at line 56 of file TpcPrototypeCluster.h
References m_isGlobal.
int TpcPrototypeCluster::isValid () const virtual
isValid returns non zero if object contains vailid data
Reimplemented from TrkrCluster.
Definition at line 202 of file TpcPrototypeCluster.cc.
View newest version in sPHENIX GitHub at line 202 of file TpcPrototypeCluster.cc
References getError(), getPosition(), TrkrCluster::getSize(), i, j, m_adc, and m_cluskey.
virtual void TpcPrototypeCluster::Reset () inline virtual
Clear Event.
Reimplemented from TrkrCluster.
Definition at line 38 of file TpcPrototypeCluster.h.
View newest version in sPHENIX GitHub at line 38 of file TpcPrototypeCluster.h
virtual void TpcPrototypeCluster::setAdc (unsigned int adc) inline virtual
Reimplemented from TrkrCluster.
Definition at line 61 of file TpcPrototypeCluster.h.
View newest version in sPHENIX GitHub at line 61 of file TpcPrototypeCluster.h
References m_adc.
Referenced by TpcPrototypeUnpacker::exportDSTCluster().
void TpcPrototypeCluster::setAvgPadAzimuth (double avgPadAzimuth) inline
Definition at line 85 of file TpcPrototypeCluster.h.
View newest version in sPHENIX GitHub at line 85 of file TpcPrototypeCluster.h
References avg_pad_azimuth.
Referenced by TpcPrototypeUnpacker::exportDSTCluster().
void TpcPrototypeCluster::setAvgPadRadial (int avgPadRadial) inline
Definition at line 95 of file TpcPrototypeCluster.h.
View newest version in sPHENIX GitHub at line 95 of file TpcPrototypeCluster.h
References avg_pad_radial.
Referenced by TpcPrototypeUnpacker::exportDSTCluster().
virtual void TpcPrototypeCluster::setClusKey (TrkrDefs::cluskey id) inline virtual
Definition at line 41 of file TpcPrototypeCluster.h.
View newest version in sPHENIX GitHub at line 41 of file TpcPrototypeCluster.h
References train_ambiguity_solver::id, and m_cluskey.
Referenced by TpcPrototypeUnpacker::exportDSTCluster().
void TpcPrototypeCluster::setDeltaAzimuthBin (double deltaAzimuthBin) inline
Definition at line 105 of file TpcPrototypeCluster.h.
View newest version in sPHENIX GitHub at line 105 of file TpcPrototypeCluster.h
References delta_azimuth_bin.
Referenced by TpcPrototypeUnpacker::exportDSTCluster().
void TpcPrototypeCluster::setDeltaZ (double deltaZ) inline
Definition at line 115 of file TpcPrototypeCluster.h.
View newest version in sPHENIX GitHub at line 115 of file TpcPrototypeCluster.h
References delta_z.
Referenced by TpcPrototypeUnpacker::exportDSTCluster().
void TpcPrototypeCluster::setError (unsigned int i, unsigned int j, float value) virtual
Reimplemented from TrkrCluster.
Definition at line 233 of file TpcPrototypeCluster.cc.
View newest version in sPHENIX GitHub at line 233 of file TpcPrototypeCluster.cc
References m_err, and value.
Referenced by TpcPrototypeUnpacker::exportDSTCluster(), and TpcPrototypeCluster().
virtual void TpcPrototypeCluster::setGlobal () inline virtual
Reimplemented from TrkrCluster.
Definition at line 54 of file TpcPrototypeCluster.h.
View newest version in sPHENIX GitHub at line 54 of file TpcPrototypeCluster.h
References m_isGlobal.
Referenced by TpcPrototypeUnpacker::exportDSTCluster().
virtual void TpcPrototypeCluster::setLocal () inline virtual
Reimplemented from TrkrCluster.
Definition at line 55 of file TpcPrototypeCluster.h.
View newest version in sPHENIX GitHub at line 55 of file TpcPrototypeCluster.h
References m_isGlobal.
void TpcPrototypeCluster::setMaxPadAzimuth (int maxPadAzimuth) inline
Definition at line 125 of file TpcPrototypeCluster.h.
View newest version in sPHENIX GitHub at line 125 of file TpcPrototypeCluster.h
References max_pad_azimuth.
Referenced by TpcPrototypeUnpacker::exportDSTCluster().
void TpcPrototypeCluster::setMaxSample (int maxSample) inline
Definition at line 135 of file TpcPrototypeCluster.h.
View newest version in sPHENIX GitHub at line 135 of file TpcPrototypeCluster.h
References max_sample.
Referenced by TpcPrototypeUnpacker::exportDSTCluster().
void TpcPrototypeCluster::setMinPadAzimuth (int minPadAzimuth) inline
Definition at line 145 of file TpcPrototypeCluster.h.
View newest version in sPHENIX GitHub at line 145 of file TpcPrototypeCluster.h
References min_pad_azimuth.
Referenced by TpcPrototypeUnpacker::exportDSTCluster().
void TpcPrototypeCluster::setMinSample (int minSample) inline
Definition at line 155 of file TpcPrototypeCluster.h.
View newest version in sPHENIX GitHub at line 155 of file TpcPrototypeCluster.h
References min_sample.
Referenced by TpcPrototypeUnpacker::exportDSTCluster().
void TpcPrototypeCluster::setPadAzimuthPeaks (const std::map< int, double > & padAzimuthPeaks) inline
Definition at line 165 of file TpcPrototypeCluster.h.
View newest version in sPHENIX GitHub at line 165 of file TpcPrototypeCluster.h
References pad_azimuth_peaks.
Referenced by TpcPrototypeUnpacker::exportDSTCluster().
void TpcPrototypeCluster::setPadAzimuths (const std::set< int > & padAzimuths) inline
Definition at line 185 of file TpcPrototypeCluster.h.
View newest version in sPHENIX GitHub at line 185 of file TpcPrototypeCluster.h
References pad_azimuths.
Referenced by TpcPrototypeUnpacker::exportDSTCluster().
void TpcPrototypeCluster::setPadAzimuthSamples (const std::map< int, std::vector< double >> & padAzimuthSamples) inline
Definition at line 175 of file TpcPrototypeCluster.h.
View newest version in sPHENIX GitHub at line 175 of file TpcPrototypeCluster.h
References pad_azimuth_samples.
Referenced by TpcPrototypeUnpacker::exportDSTCluster().
void TpcPrototypeCluster::setPadRadials (const std::set< int > & padRadials) inline
Definition at line 205 of file TpcPrototypeCluster.h.
View newest version in sPHENIX GitHub at line 205 of file TpcPrototypeCluster.h
References pad_radials.
Referenced by TpcPrototypeUnpacker::exportDSTCluster().
void TpcPrototypeCluster::setPadRadialSamples (const std::map< int, std::vector< double >> & padRadialSamples) inline
Definition at line 195 of file TpcPrototypeCluster.h.
View newest version in sPHENIX GitHub at line 195 of file TpcPrototypeCluster.h
References pad_radial_samples.
Referenced by TpcPrototypeUnpacker::exportDSTCluster().
void TpcPrototypeCluster::setPeak (double peak) inline
Definition at line 215 of file TpcPrototypeCluster.h.
View newest version in sPHENIX GitHub at line 215 of file TpcPrototypeCluster.h
References peak.
Referenced by TpcPrototypeUnpacker::exportDSTCluster().
void TpcPrototypeCluster::setPeakSample (double peakSample) inline
Definition at line 225 of file TpcPrototypeCluster.h.
View newest version in sPHENIX GitHub at line 225 of file TpcPrototypeCluster.h
References peak_sample.
Referenced by TpcPrototypeUnpacker::exportDSTCluster().
void TpcPrototypeCluster::setPedstal (double pedstal) inline
Definition at line 235 of file TpcPrototypeCluster.h.
View newest version in sPHENIX GitHub at line 235 of file TpcPrototypeCluster.h
References pedstal.
Referenced by TpcPrototypeUnpacker::exportDSTCluster().
virtual void TpcPrototypeCluster::setPosition (int coor, float xi) inline virtual
Reimplemented from TrkrCluster.
Definition at line 53 of file TpcPrototypeCluster.h.
View newest version in sPHENIX GitHub at line 53 of file TpcPrototypeCluster.h
References m_pos.
Referenced by TpcPrototypeUnpacker::exportDSTCluster().
void TpcPrototypeCluster::setSamples (const std::set< int > & samples) inline
Definition at line 245 of file TpcPrototypeCluster.h.
View newest version in sPHENIX GitHub at line 245 of file TpcPrototypeCluster.h
References samples.
Referenced by TpcPrototypeUnpacker::exportDSTCluster().
void TpcPrototypeCluster::setSize (unsigned int i, unsigned int j, float value) virtual
Reimplemented from TrkrCluster.
Definition at line 222 of file TpcPrototypeCluster.cc.
View newest version in sPHENIX GitHub at line 222 of file TpcPrototypeCluster.cc
References m_size, and value.
Referenced by TpcPrototypeUnpacker::exportDSTCluster(), and TpcPrototypeCluster().
void TpcPrototypeCluster::setSizePadAzimuth (int sizePadAzimuth) inline
Definition at line 255 of file TpcPrototypeCluster.h.
View newest version in sPHENIX GitHub at line 255 of file TpcPrototypeCluster.h
References size_pad_azimuth.
Referenced by TpcPrototypeUnpacker::exportDSTCluster().
void TpcPrototypeCluster::setSizePadRadial (int sizePadRadial) inline
Definition at line 265 of file TpcPrototypeCluster.h.
View newest version in sPHENIX GitHub at line 265 of file TpcPrototypeCluster.h
References size_pad_radial.
Referenced by TpcPrototypeUnpacker::exportDSTCluster().
void TpcPrototypeCluster::setSumSamples (const std::vector< double > & sumSamples) inline
Definition at line 275 of file TpcPrototypeCluster.h.
View newest version in sPHENIX GitHub at line 275 of file TpcPrototypeCluster.h
References sum_samples.
Referenced by TpcPrototypeUnpacker::exportDSTCluster().
virtual void TpcPrototypeCluster::setX (float x) inline virtual
Reimplemented from TrkrCluster.
Definition at line 47 of file TpcPrototypeCluster.h.
View newest version in sPHENIX GitHub at line 47 of file TpcPrototypeCluster.h
References m_pos, and ambiguity_solver_full_chain::x.
virtual void TpcPrototypeCluster::setY (float y) inline virtual
Reimplemented from TrkrCluster.
Definition at line 49 of file TpcPrototypeCluster.h.
View newest version in sPHENIX GitHub at line 49 of file TpcPrototypeCluster.h
References m_pos, and y.
virtual void TpcPrototypeCluster::setZ (float z) inline virtual
Reimplemented from TrkrCluster.
Definition at line 51 of file TpcPrototypeCluster.h.
View newest version in sPHENIX GitHub at line 51 of file TpcPrototypeCluster.h
References m_pos, and physmon_track_finding_ttbar::z.
Member Data Documentation
double TpcPrototypeCluster::avg_pad_azimuth protected
Definition at line 312 of file TpcPrototypeCluster.h.
View newest version in sPHENIX GitHub at line 312 of file TpcPrototypeCluster.h
Referenced by getAvgPadAzimuth(), identify(), and setAvgPadAzimuth().
int TpcPrototypeCluster::avg_pad_radial protected
pad coordinate
Definition at line 311 of file TpcPrototypeCluster.h.
View newest version in sPHENIX GitHub at line 311 of file TpcPrototypeCluster.h
Referenced by getAvgPadRadial(), identify(), and setAvgPadRadial().
double TpcPrototypeCluster::delta_azimuth_bin protected
pad bin size phi size per pad in rad
Definition at line 320 of file TpcPrototypeCluster.h.
View newest version in sPHENIX GitHub at line 320 of file TpcPrototypeCluster.h
Referenced by getDeltaAzimuthBin(), identify(), and setDeltaAzimuthBin().
double TpcPrototypeCluster::delta_z protected
z size per ADC sample bin
Definition at line 322 of file TpcPrototypeCluster.h.
View newest version in sPHENIX GitHub at line 322 of file TpcPrototypeCluster.h
Referenced by getDeltaZ(), identify(), and setDeltaZ().
unsigned int TpcPrototypeCluster::m_adc protected
Definition at line 284 of file TpcPrototypeCluster.h.
View newest version in sPHENIX GitHub at line 284 of file TpcPrototypeCluster.h
Referenced by getAdc(), isValid(), and setAdc().
TrkrDefs::cluskey TpcPrototypeCluster::m_cluskey protected
Definition at line 281 of file TpcPrototypeCluster.h.
View newest version in sPHENIX GitHub at line 281 of file TpcPrototypeCluster.h
Referenced by getClusKey(), isValid(), and setClusKey().
float TpcPrototypeCluster::m_err[6] protected
Definition at line 286 of file TpcPrototypeCluster.h.
View newest version in sPHENIX GitHub at line 286 of file TpcPrototypeCluster.h
Referenced by getError(), and setError().
bool TpcPrototypeCluster::m_isGlobal protected
Definition at line 283 of file TpcPrototypeCluster.h.
View newest version in sPHENIX GitHub at line 283 of file TpcPrototypeCluster.h
Referenced by identify(), isGlobal(), setGlobal(), and setLocal().
float TpcPrototypeCluster::m_pos[3] protected
Definition at line 282 of file TpcPrototypeCluster.h.
View newest version in sPHENIX GitHub at line 282 of file TpcPrototypeCluster.h
Referenced by getPhiError(), getPosition(), getX(), getY(), getZ(), setPosition(), setX(), setY(), setZ(), and TpcPrototypeCluster().
float TpcPrototypeCluster::m_size[6] protected
Definition at line 285 of file TpcPrototypeCluster.h.
View newest version in sPHENIX GitHub at line 285 of file TpcPrototypeCluster.h
Referenced by getSize(), and setSize().
int TpcPrototypeCluster::max_pad_azimuth protected
Definition at line 301 of file TpcPrototypeCluster.h.
View newest version in sPHENIX GitHub at line 301 of file TpcPrototypeCluster.h
Referenced by getMaxPadAzimuth(), identify(), and setMaxPadAzimuth().
int TpcPrototypeCluster::max_sample protected
Definition at line 299 of file TpcPrototypeCluster.h.
View newest version in sPHENIX GitHub at line 299 of file TpcPrototypeCluster.h
Referenced by getMaxSample(), identify(), and setMaxSample().
int TpcPrototypeCluster::min_pad_azimuth protected
Definition at line 300 of file TpcPrototypeCluster.h.
View newest version in sPHENIX GitHub at line 300 of file TpcPrototypeCluster.h
Referenced by getMinPadAzimuth(), identify(), and setMinPadAzimuth().
int TpcPrototypeCluster::min_sample protected
Definition at line 298 of file TpcPrototypeCluster.h.
View newest version in sPHENIX GitHub at line 298 of file TpcPrototypeCluster.h
Referenced by getMinSample(), identify(), and setMinSample().
std::map<int, double> TpcPrototypeCluster::pad_azimuth_peaks protected
Definition at line 308 of file TpcPrototypeCluster.h.
View newest version in sPHENIX GitHub at line 308 of file TpcPrototypeCluster.h
Referenced by getPadAzimuthPeaks(), identify(), and setPadAzimuthPeaks().
std::map<int, std::vector<double> > TpcPrototypeCluster::pad_azimuth_samples protected
Definition at line 295 of file TpcPrototypeCluster.h.
View newest version in sPHENIX GitHub at line 295 of file TpcPrototypeCluster.h
Referenced by getPadAzimuthSamples(), identify(), and setPadAzimuthSamples().
std::set<int> TpcPrototypeCluster::pad_azimuths protected
Definition at line 291 of file TpcPrototypeCluster.h.
View newest version in sPHENIX GitHub at line 291 of file TpcPrototypeCluster.h
Referenced by getPadAzimuths(), identify(), and setPadAzimuths().
std::map<int, std::vector<double> > TpcPrototypeCluster::pad_radial_samples protected
Definition at line 294 of file TpcPrototypeCluster.h.
View newest version in sPHENIX GitHub at line 294 of file TpcPrototypeCluster.h
Referenced by getPadRadialSamples(), identify(), and setPadRadialSamples().
std::set<int> TpcPrototypeCluster::pad_radials protected
Definition at line 290 of file TpcPrototypeCluster.h.
View newest version in sPHENIX GitHub at line 290 of file TpcPrototypeCluster.h
Referenced by getPadRadials(), identify(), and setPadRadials().
double TpcPrototypeCluster::peak protected
Definition at line 303 of file TpcPrototypeCluster.h.
View newest version in sPHENIX GitHub at line 303 of file TpcPrototypeCluster.h
Referenced by getPeak(), identify(), and setPeak().
double TpcPrototypeCluster::peak_sample protected
Definition at line 304 of file TpcPrototypeCluster.h.
View newest version in sPHENIX GitHub at line 304 of file TpcPrototypeCluster.h
Referenced by getPeakSample(), identify(), and setPeakSample().
double TpcPrototypeCluster::pedstal protected
Definition at line 305 of file TpcPrototypeCluster.h.
View newest version in sPHENIX GitHub at line 305 of file TpcPrototypeCluster.h
Referenced by getPedstal(), identify(), and setPedstal().
std::set<int> TpcPrototypeCluster::samples protected
Definition at line 292 of file TpcPrototypeCluster.h.
View newest version in sPHENIX GitHub at line 292 of file TpcPrototypeCluster.h
Referenced by getSamples(), identify(), and setSamples().
int TpcPrototypeCluster::size_pad_azimuth protected
Definition at line 316 of file TpcPrototypeCluster.h.
View newest version in sPHENIX GitHub at line 316 of file TpcPrototypeCluster.h
Referenced by getSizePadAzimuth(), identify(), and setSizePadAzimuth().
int TpcPrototypeCluster::size_pad_radial protected
cluster size in units of pad bins
Definition at line 315 of file TpcPrototypeCluster.h.
View newest version in sPHENIX GitHub at line 315 of file TpcPrototypeCluster.h
Referenced by getSizePadRadial(), identify(), and setSizePadRadial().
std::vector<double> TpcPrototypeCluster::sum_samples protected
Definition at line 296 of file TpcPrototypeCluster.h.
View newest version in sPHENIX GitHub at line 296 of file TpcPrototypeCluster.h
Referenced by getSumSamples(), identify(), and setSumSamples().
The documentation for this class was generated from the following files:
prototype/blob/master/offline/packages/tpc2019/TpcPrototypeCluster.h
prototype/blob/master/offline/packages/tpc2019/TpcPrototypeCluster.cc