Analysis Software: acts/blob/sPHENIX/Tests/UnitTests/Plugins/ActSVG/DetectorSvgConverterTests.cpp File Reference
DetectorSvgConverterTests.cpp File Reference
#include <boost/test/unit_test.hpp>
#include "Acts/Definitions/Algebra.hpp"
#include "Acts/Detector/CylindricalContainerBuilder.hpp"
#include "Acts/Detector/Detector.hpp"
#include "Acts/Detector/DetectorBuilder.hpp"
#include "Acts/Detector/DetectorComponents.hpp"
#include "Acts/Detector/DetectorVolume.hpp"
#include "Acts/Detector/GeometryIdGenerator.hpp"
#include "Acts/Detector/PortalGenerators.hpp"
#include "Acts/Detector/interface/IDetectorComponentBuilder.hpp"
#include "Acts/Geometry/CylinderVolumeBounds.hpp"
#include "Acts/Geometry/GeometryContext.hpp"
#include "Acts/Navigation/DetectorVolumeFinders.hpp"
#include "Acts/Navigation/SurfaceCandidatesUpdators.hpp"
#include "Acts/Plugins/ActSVG/DetectorSvgConverter.hpp"
#include "Acts/Surfaces/CylinderBounds.hpp"
#include "Acts/Surfaces/CylinderSurface.hpp"
#include "Acts/Surfaces/DiscSurface.hpp"
#include "Acts/Surfaces/RadialBounds.hpp"
#include "Acts/Surfaces/Surface.hpp"
#include "Acts/Utilities/BinningType.hpp"
#include "Acts/Utilities/Enumerate.hpp"
#include "Acts/Utilities/Logger.hpp"
#include <fstream>
#include <memory>
#include <vector>
Classes
class CylindricalVolumeBuilder< surface_type, surface_bounds_type >
A mockup volume builder, it generates volumes with a single surface filled in in order to use the CylindricalContainerBuilder infrastructure.
Functions
BOOST_AUTO_TEST_CASE (CylindricalDetector)
Variables
GeometryContext tContext
Function Documentation
BOOST_AUTO_TEST_CASE (CylindricalDetector)
Definition at line 96 of file DetectorSvgConverterTests.cpp.
View newest version in sPHENIX GitHub at line 96 of file DetectorSvgConverterTests.cpp
References Acts::Experimental::DetectorBuilder::Config::auxiliary, Acts::binR, Acts::binZ, Acts::Test::blue, Acts::Experimental::CylindricalContainerBuilder::Config::builders, Acts::PhysicalConstants::c, color, filter::Config, Acts::Experimental::DetectorBuilder::construct(), Acts::Svg::DetectorConverter::convert(), Acts::getDefaultLogger(), Acts::Test::green, Acts::Test::red, tContext, Acts::Svg::toFile(), Acts::Logging::VERBOSE, and Acts::Svg::View::zr().
Variable Documentation
GeometryContext tContext
Definition at line 41 of file DetectorSvgConverterTests.cpp.
View newest version in sPHENIX GitHub at line 41 of file DetectorSvgConverterTests.cpp