Analysis Software: PHG4TrackFastSim Class Reference
PHG4TrackFastSim Class Reference
#include <analysis/blob/master/ForwardTracking/PHG4HitKalmanFitter.h>
Public Types
enum DETECTOR_TYPE { Vertical_Plane = 0, Cylinder = 1 }
Public Member Functions
PHG4TrackFastSim (const std::string &name="PHG4HitKalmanFitter")
Default constructor.
~PHG4TrackFastSim ()
dtor
int Init (PHCompositeNode *)
Initialization, called for initialization.
int InitRun (PHCompositeNode *)
Initialization Run, called for initialization of a run.
int process_event (PHCompositeNode *)
Process Event, called for each event.
int End (PHCompositeNode *)
End, write and close files.
void Verbosity (int verb)
set verbosity
bool is_do_evt_display () const
void set_do_evt_display (bool doEvtDisplay)
double get_FGEM_phi_resolution () const
void set_FGEM_phi_resolution (double fgemPhiResolution)
double get_FGEM_r_resolution () const
void set_FGEM_r_resolution (double fgemRResolution)
const std::string & get_fit_alg_name () const
void set_fit_alg_name (const std::string &fitAlgName)
double get_pat_rec_hit_finding_eff () const
void set_pat_rec_hit_finding_eff (double patRecHitFindingEff)
double get_pat_rec_nosise_prob () const
void set_pat_rec_nosise_prob (double patRecNosiseProb)
PHG4TrackFastSim (const std::string &name="PHG4TrackFastSim")
Default constructor.
~PHG4TrackFastSim () override
dtor
int InitRun (PHCompositeNode *) override
Initialization Run, called for initialization of a run.
int process_event (PHCompositeNode *) override
Process Event, called for each event.
int End (PHCompositeNode *) override
End, write and close files.
bool is_do_evt_display () const
void set_do_evt_display (bool doEvtDisplay)
const std::string & get_fit_alg_name () const
void set_fit_alg_name (const std::string &fitAlgName)
const std::vector< std::string > & get_phg4hits_names () const
void add_phg4hits (const std::string &phg4hitsNames, const DETECTOR_TYPE phg4dettype, const float radres, const float phires, const float lonres, const float eff, const float noise)
void add_state_name (const std::string &stateName)
void add_zplane_state (const std::string &stateName, const double zplane)
void add_cylinder_state (const std::string &stateName, const double radius)
const std::string & get_trackmap_out_name () const
void set_trackmap_out_name (const std::string &trackmapOutName)
const std::string & get_sub_top_node_name () const
void set_sub_top_node_name (const std::string &subTopNodeName)
bool is_use_vertex_in_fitting () const
void set_use_vertex_in_fitting (bool useVertexInFitting)
double get_vertex_xy_resolution () const
void set_vertex_xy_resolution (double vertexXyResolution)
double get_vertex_z_resolution () const
void set_vertex_z_resolution (double vertexZResolution)
int get_primary_assumption_pid () const
void set_primary_assumption_pid (int primaryAssumptionPid)
void set_primary_tracking (int pTrk)
const std::string & get_vertexing_method () const
https://rave.hepforge.org/trac/wiki/RaveMethods
void set_vertexing_method (const std::string &vertexingMethod)
https://rave.hepforge.org/trac/wiki/RaveMethods
double get_vertex_min_ndf () const
void set_vertex_min_ndf (double vertexMinNdf)
void enable_vertexing (const bool &b=true)
void DisplayEvent () const
void Smearing (const bool b)
Public Member Functions inherited from SubsysReco
~SubsysReco () override
virtual int EndRun (const int)
Called at the end of each run.
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
void Print (const std::string &="ALL") const override
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Protected Attributes
gsl_rng * m_RandomGenerator
random generator that conform with sPHENIX standard
PHGenFit::Fitter * m_Fitter
genfit::GFRaveVertexFactory * m_RaveVertexFactory
PHG4TruthInfoContainer * m_TruthContainer
Input Node pointers.
SvtxTrackMap * m_SvtxTrackMapOut
SvtxVertexMap * m_SvtxVertexMap
std::vector< PHG4HitContainer * > m_PHG4HitContainer
std::vector< std::string > m_PHG4HitsNames
std::vector< DETECTOR_TYPE > m_phg4_detector_type
std::vector< float > m_phg4_detector_radres
std::vector< float > m_phg4_detector_phires
std::vector< float > m_phg4_detector_lonres
std::vector< float > m_phg4_detector_hitfindeff
std::vector< float > m_phg4_detector_noise
std::map< std::string,
std::pair< int, double > > m_ProjectionsMap
std::string m_SubTopnodeName
std::string m_TrackmapOutNodeName
std::string m_VertexingMethod
https://rave.hepforge.org/trac/wiki/RaveMethods
std::string m_FitAlgoName
double m_VertexMinNdf
double m_VertexXYResolution
double m_VertexZResolution
int m_EventCnt
Event counter.
int m_PrimaryAssumptionPid
bool m_SmearingFlag
bool m_DoEvtDisplayFlag
bool m_UseVertexInFittingFlag
int m_PrimaryTrackingFlag
bool m_DoVertexingFlag
PHParameters * m_Parameter = nullptr
Private Types
typedef std::map< const
genfit::Track *, unsigned int > GenFitTrackMap
Private Member Functions
int CreateNodes (PHCompositeNode *)
int GetNodes (PHCompositeNode *)
int PseudoPatternRecognition (const PHG4Particle *particle, std::vector< PHGenFit::Measurement * > &meas_out, TVector3 &seed_pos, TVector3 &seed_mom, TMatrixDSym &seed_cov, const bool do_smearing=true)
PHGenFit::PlanarMeasurement * PHG4HitToMeasurementVerticalPlane (const PHG4Hit *g4hit)
PHGenFit::PlanarMeasurement * VertexMeasurement (const TVector3 &vtx, const double dr, const double dphi)
SvtxTrack * MakeSvtxTrack (const PHGenFit::Track *phgf_track_in)
int CreateNodes (PHCompositeNode *)
int GetNodes (PHCompositeNode *)
int PseudoPatternRecognition (const PHG4Particle *particle, std::vector< PHGenFit::Measurement * > &meas_out, SvtxTrack *track_out, TVector3 &seed_pos, TVector3 &seed_mom, TMatrixDSym &seed_cov, const bool do_smearing=true)
PHGenFit::PlanarMeasurement * PHG4HitToMeasurementVerticalPlane (const PHG4Hit *g4hit, const double phi_resolution, const double r_resolution)
PHGenFit::PlanarMeasurement * PHG4HitToMeasurementCylinder (const PHG4Hit *g4hit, const double phi_resolution, const double z_resolution)
PHGenFit::Measurement * VertexMeasurement (const TVector3 &vtx, double dxy, double dz)
bool MakeSvtxTrack (SvtxTrack *track_out, const PHGenFit::Track *phgf_track_in, const unsigned int truth_track_id=UINT_MAX, const unsigned int nmeas=0, const TVector3 &vtx=TVector3(0.0, 0.0, 0.0))
bool FillSvtxVertexMap (const std::vector< genfit::GFRaveVertex * > &rave_vertices, const GenFitTrackMap &gf_tracks)
Private Attributes
int _event
Event counter.
PHG4TruthInfoContainer * _truth_container
Input Node pointers.
std::vector< PHG4HitContainer * > _phg4hits
std::vector< std::string > _phg4hits_names
SvtxTrackMap * _trackmap_out
Output Node pointers.
PHGenFit::Fitter * _fitter
std::string _fit_alg_name
bool _do_evt_display
double _phi_resolution
double _r_resolution
double _pat_rec_hit_finding_eff
double _pat_rec_nosise_prob
Additional Inherited Members
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Detailed Description
Definition at line 54 of file PHG4HitKalmanFitter.h.
View newest version in sPHENIX GitHub at line 54 of file PHG4HitKalmanFitter.h
Member Typedef Documentation
typedef std::map<const genfit::Track*, unsigned int> PHG4TrackFastSim::GenFitTrackMap private
Definition at line 235 of file PHG4TrackFastSim.h.
View newest version in sPHENIX GitHub at line 235 of file PHG4TrackFastSim.h
Member Enumeration Documentation
enum PHG4TrackFastSim::DETECTOR_TYPE
Enumerator:
Vertical_Plane
Cylinder
Definition at line 57 of file PHG4TrackFastSim.h.
View newest version in sPHENIX GitHub at line 57 of file PHG4TrackFastSim.h
Constructor & Destructor Documentation
PHG4TrackFastSim::PHG4TrackFastSim (const std::string & name = "PHG4HitKalmanFitter")
Default constructor.
Definition at line 48 of file PHG4HitKalmanFitter.cc.
View newest version in sPHENIX GitHub at line 48 of file PHG4HitKalmanFitter.cc
References _event, _N_DETECTOR_LAYER, _phg4hits_names, and i.
PHG4TrackFastSim::~PHG4TrackFastSim ()
dtor
Definition at line 70 of file PHG4HitKalmanFitter.cc.
View newest version in sPHENIX GitHub at line 70 of file PHG4HitKalmanFitter.cc
References _fitter.
PHG4TrackFastSim::PHG4TrackFastSim (const std::string & name = "PHG4TrackFastSim") explicit
Default constructor.
PHG4TrackFastSim::~PHG4TrackFastSim () override
dtor
Member Function Documentation
void PHG4TrackFastSim::add_cylinder_state (const std::string & stateName, const double radius)
Definition at line 1118 of file PHG4TrackFastSim.cc.
View newest version in sPHENIX GitHub at line 1118 of file PHG4TrackFastSim.cc
References m_ProjectionsMap, PHWHERE, reserved_cylinder_projection_names, and reserved_zplane_projection_names.
Referenced by Fun4All_G4_Momentum_Projection(), and Fun4All_G4_Momentum_Projection_Detectors().
void PHG4TrackFastSim::add_phg4hits (const std::string & phg4hitsNames, const DETECTOR_TYPE phg4dettype, const float radres, const float phires, const float lonres, const float eff, const float noise) inline
adding hits from a PHG4Hit node, which usually belong to one detector or a sub group of detectors Orders of adding detectors do not matter as the hits are internally assembled in the time order
Parameters
[in] phg4hitsNames node name such as "G4HIT_SVTX"
[in] PHG4TrackFastSim::Vertical_Plane or PHG4TrackFastSim::Cylinder
[in] radres radial resolution [cm], not used for PHG4TrackFastSim::Cylinder
[in] phires azimuthal resolution [cm]
[in] lonres z-resolution [cm], not used for PHG4TrackFastSim::Vertical_Plane
[in] eff Efficiency [0-1] for a existing hit to be included in the tracking
[in] noise Noise hit propability [0-1]
Definition at line 112 of file PHG4TrackFastSim.h.
View newest version in sPHENIX GitHub at line 112 of file PHG4TrackFastSim.h
References m_phg4_detector_hitfindeff, m_phg4_detector_lonres, m_phg4_detector_noise, m_phg4_detector_phires, m_phg4_detector_radres, m_phg4_detector_type, and m_PHG4HitsNames.
Referenced by Fun4All_G4_Momentum(), Fun4All_G4_Momentum_Projection(), Fun4All_G4_Momentum_Projection_Calorimeters(), and Fun4All_G4_Momentum_Projection_Detectors().
void PHG4TrackFastSim::add_state_name (const std::string & stateName)
Definition at line 1088 of file PHG4TrackFastSim.cc.
View newest version in sPHENIX GitHub at line 1088 of file PHG4TrackFastSim.cc
References m_ProjectionsMap, PHWHERE, reserved_cylinder_projection_names, and reserved_zplane_projection_names.
Referenced by Fun4All_G4_Momentum_Projection_Calorimeters().
void PHG4TrackFastSim::add_zplane_state (const std::string & stateName, const double zplane)
Definition at line 1135 of file PHG4TrackFastSim.cc.
View newest version in sPHENIX GitHub at line 1135 of file PHG4TrackFastSim.cc
References m_ProjectionsMap, PHWHERE, reserved_cylinder_projection_names, and reserved_zplane_projection_names.
Referenced by Fun4All_G4_Momentum_Projection(), and Fun4All_G4_Momentum_Projection_Detectors().
int PHG4TrackFastSim::CreateNodes (PHCompositeNode * topNode) private
Create needed nodes.
Definition at line 193 of file PHG4HitKalmanFitter.cc.
View newest version in sPHENIX GitHub at line 193 of file PHG4HitKalmanFitter.cc
References _trackmap_out, Fun4AllReturnCodes::ABORTEVENT, PHCompositeNode::addNode(), Fun4AllReturnCodes::EVENT_OK, PHNodeIterator::findFirst(), PHWHERE, and verbosity.
Referenced by InitRun().
int PHG4TrackFastSim::CreateNodes (PHCompositeNode *) private
Create needed nodes.
void PHG4TrackFastSim::DisplayEvent () const
Definition at line 1079 of file PHG4TrackFastSim.cc.
View newest version in sPHENIX GitHub at line 1079 of file PHG4TrackFastSim.cc
References PHGenFit::Fitter::displayEvent(), m_DoEvtDisplayFlag, and m_Fitter.
void PHG4TrackFastSim::enable_vertexing (const bool & b = true) inline
Definition at line 225 of file PHG4TrackFastSim.h.
View newest version in sPHENIX GitHub at line 225 of file PHG4TrackFastSim.h
References KFPMath::b, and m_DoVertexingFlag.
int PHG4TrackFastSim::End (PHCompositeNode * topNode) virtual
End, write and close files.
Reimplemented from SubsysReco.
Definition at line 103 of file PHG4HitKalmanFitter.cc.
View newest version in sPHENIX GitHub at line 103 of file PHG4HitKalmanFitter.cc
References Fun4AllReturnCodes::EVENT_OK.
int PHG4TrackFastSim::End (PHCompositeNode *) override virtual
End, write and close files.
Reimplemented from SubsysReco.
bool PHG4TrackFastSim::FillSvtxVertexMap (const std::vector< genfit::GFRaveVertex * > & rave_vertices, const GenFitTrackMap & gf_tracks) private
Definition at line 488 of file PHG4TrackFastSim.cc.
View newest version in sPHENIX GitHub at line 488 of file PHG4TrackFastSim.cc
References i, SvtxVertexMap::insert_clone(), j, LogError, m_SvtxVertexMap, and PHWHERE.
double PHG4TrackFastSim::get_FGEM_phi_resolution () const inline
Definition at line 91 of file PHG4HitKalmanFitter.h.
View newest version in sPHENIX GitHub at line 91 of file PHG4HitKalmanFitter.h
References _phi_resolution.
double PHG4TrackFastSim::get_FGEM_r_resolution () const inline
Definition at line 101 of file PHG4HitKalmanFitter.h.
View newest version in sPHENIX GitHub at line 101 of file PHG4HitKalmanFitter.h
References _r_resolution.
const std::string& PHG4TrackFastSim::get_fit_alg_name () const inline
Definition at line 88 of file PHG4TrackFastSim.h.
View newest version in sPHENIX GitHub at line 88 of file PHG4TrackFastSim.h
References m_FitAlgoName.
const std::string& PHG4TrackFastSim::get_fit_alg_name () const inline
Definition at line 111 of file PHG4HitKalmanFitter.h.
View newest version in sPHENIX GitHub at line 111 of file PHG4HitKalmanFitter.h
References _fit_alg_name.
double PHG4TrackFastSim::get_pat_rec_hit_finding_eff () const inline
Definition at line 121 of file PHG4HitKalmanFitter.h.
View newest version in sPHENIX GitHub at line 121 of file PHG4HitKalmanFitter.h
References _pat_rec_hit_finding_eff.
double PHG4TrackFastSim::get_pat_rec_nosise_prob () const inline
Definition at line 135 of file PHG4HitKalmanFitter.h.
View newest version in sPHENIX GitHub at line 135 of file PHG4HitKalmanFitter.h
References _pat_rec_nosise_prob.
const std::vector<std::string>& PHG4TrackFastSim::get_phg4hits_names () const inline
Definition at line 98 of file PHG4TrackFastSim.h.
View newest version in sPHENIX GitHub at line 98 of file PHG4TrackFastSim.h
References m_PHG4HitsNames.
int PHG4TrackFastSim::get_primary_assumption_pid () const inline
Definition at line 188 of file PHG4TrackFastSim.h.
View newest version in sPHENIX GitHub at line 188 of file PHG4TrackFastSim.h
References m_PrimaryAssumptionPid.
const std::string& PHG4TrackFastSim::get_sub_top_node_name () const inline
Definition at line 148 of file PHG4TrackFastSim.h.
View newest version in sPHENIX GitHub at line 148 of file PHG4TrackFastSim.h
References m_SubTopnodeName.
const std::string& PHG4TrackFastSim::get_trackmap_out_name () const inline
Definition at line 138 of file PHG4TrackFastSim.h.
View newest version in sPHENIX GitHub at line 138 of file PHG4TrackFastSim.h
References m_TrackmapOutNodeName.
double PHG4TrackFastSim::get_vertex_min_ndf () const inline
Definition at line 215 of file PHG4TrackFastSim.h.
View newest version in sPHENIX GitHub at line 215 of file PHG4TrackFastSim.h
References m_VertexMinNdf.
double PHG4TrackFastSim::get_vertex_xy_resolution () const inline
Definition at line 168 of file PHG4TrackFastSim.h.
View newest version in sPHENIX GitHub at line 168 of file PHG4TrackFastSim.h
References m_VertexXYResolution.
double PHG4TrackFastSim::get_vertex_z_resolution () const inline
Definition at line 178 of file PHG4TrackFastSim.h.
View newest version in sPHENIX GitHub at line 178 of file PHG4TrackFastSim.h
References m_VertexZResolution.
const std::string& PHG4TrackFastSim::get_vertexing_method () const inline
https://rave.hepforge.org/trac/wiki/RaveMethods
Definition at line 204 of file PHG4TrackFastSim.h.
View newest version in sPHENIX GitHub at line 204 of file PHG4TrackFastSim.h
References m_VertexingMethod.
int PHG4TrackFastSim::GetNodes (PHCompositeNode * topNode) private
Get all the all the required nodes off the node tree.
Definition at line 229 of file PHG4HitKalmanFitter.cc.
View newest version in sPHENIX GitHub at line 229 of file PHG4HitKalmanFitter.cc
References _event, _N_DETECTOR_LAYER, _phg4hits, _phg4hits_names, _trackmap_out, _truth_container, Fun4AllReturnCodes::ABORTEVENT, Fun4AllReturnCodes::EVENT_OK, i, and PHWHERE.
Referenced by process_event().
int PHG4TrackFastSim::GetNodes (PHCompositeNode *) private
Get all the all the required nodes off the node tree.
int PHG4TrackFastSim::Init (PHCompositeNode * topNode) virtual
Initialization, called for initialization.
Reimplemented from SubsysReco.
Definition at line 78 of file PHG4HitKalmanFitter.cc.
View newest version in sPHENIX GitHub at line 78 of file PHG4HitKalmanFitter.cc
References Fun4AllReturnCodes::EVENT_OK.
int PHG4TrackFastSim::InitRun (PHCompositeNode * topNode) virtual
Initialization Run, called for initialization of a run.
Reimplemented from SubsysReco.
Definition at line 83 of file PHG4HitKalmanFitter.cc.
View newest version in sPHENIX GitHub at line 83 of file PHG4HitKalmanFitter.cc
References _do_evt_display, _fitter, Fun4AllReturnCodes::ABORTRUN, CreateNodes(), Fun4AllReturnCodes::EVENT_OK, ckf::field, PHFieldUtility::GetFieldMapNode(), PHGenFit::Fitter::getInstance(), PHGeomUtility::GetTGeoManager(), and PHWHERE.
int PHG4TrackFastSim::InitRun (PHCompositeNode *) override virtual
Initialization Run, called for initialization of a run.
Reimplemented from SubsysReco.
bool PHG4TrackFastSim::is_do_evt_display () const inline
Definition at line 78 of file PHG4TrackFastSim.h.
View newest version in sPHENIX GitHub at line 78 of file PHG4TrackFastSim.h
References m_DoEvtDisplayFlag.
bool PHG4TrackFastSim::is_do_evt_display () const inline
Definition at line 81 of file PHG4HitKalmanFitter.h.
View newest version in sPHENIX GitHub at line 81 of file PHG4HitKalmanFitter.h
References _do_evt_display.
bool PHG4TrackFastSim::is_use_vertex_in_fitting () const inline
Definition at line 158 of file PHG4TrackFastSim.h.
View newest version in sPHENIX GitHub at line 158 of file PHG4TrackFastSim.h
References m_UseVertexInFittingFlag.
SvtxTrack * PHG4TrackFastSim::MakeSvtxTrack (const PHGenFit::Track * phgf_track_in) private
Make SvtxTrack from PHGenFit::Track
FIXME: check the definition 1/p, u'/z', v'/z', u, v u is defined as mom X beam line at POCA so u is the dca2d direction
Definition at line 340 of file PHG4HitKalmanFitter.cc.
View newest version in sPHENIX GitHub at line 340 of file PHG4HitKalmanFitter.cc
References Acts::Test::cov, PHGenFit::Track::extrapolateToPlane(), genfit::MeasuredStateOnPlane::get6DCov(), PHGenFit::Track::get_charge(), PHGenFit::Track::get_chi2(), PHGenFit::Track::get_ndf(), genfit::MeasuredStateOnPlane::getCov(), genfit::StateOnPlane::getMom(), genfit::StateOnPlane::getPos(), genfit::StateOnPlane::getState(), i, j, Acts::Test::pos, SvtxTrack_v1::set_charge(), SvtxTrack_v1::set_chisq(), SvtxTrack_v1::set_dca(), SvtxTrack_v1::set_dca2d(), SvtxTrack_v1::set_dca2d_error(), SvtxTrack_v1::set_error(), SvtxTrack_v1::set_ndf(), SvtxTrack_v1::set_px(), SvtxTrack_v1::set_py(), SvtxTrack_v1::set_pz(), SvtxTrack_v1::set_x(), SvtxTrack_v1::set_y(), and SvtxTrack_v1::set_z().
Referenced by process_event().
bool PHG4TrackFastSim::MakeSvtxTrack (SvtxTrack * track_out, const PHGenFit::Track * phgf_track_in, const unsigned int truth_track_id = UINT_MAX, const unsigned int nmeas = 0, const TVector3 & vtx = TVector3(0.0, 0.0, 0.0)) private
Make SvtxTrack from PHGenFit::Track
TODO: check the definition 1/p, u'/z', v'/z', u, v u is defined as mom X beam line at POCA so u is the dca2d direction
Definition at line 863 of file PHG4TrackFastSim.cc.
View newest version in sPHENIX GitHub at line 863 of file PHG4TrackFastSim.cc
References assert, SvtxTrack::begin_states(), PHGenFit::Track::extrapolateToCylinder(), PHGenFit::Track::extrapolateToLine(), PHGenFit::Track::extrapolateToPlane(), genfit::MeasuredStateOnPlane::get6DCov(), PHGenFit::Track::get_charge(), PHGenFit::Track::get_chi2(), PHGenFit::Track::get_ndf(), genfit::MeasuredStateOnPlane::getCov(), genfit::StateOnPlane::getMom(), genfit::StateOnPlane::getPos(), genfit::StateOnPlane::getState(), i, SvtxTrack::insert_state(), j, LogError, m_ProjectionsMap, SvtxTrack::set_charge(), SvtxTrack::set_chisq(), SvtxTrack::set_dca(), SvtxTrack::set_dca2d(), SvtxTrack::set_dca2d_error(), SvtxTrackState::set_error(), SvtxTrack::set_error(), SvtxTrackState::set_name(), SvtxTrack::set_ndf(), SvtxTrack::set_num_measurements(), SvtxTrackState::set_px(), SvtxTrack::set_px(), SvtxTrackState::set_py(), SvtxTrack::set_py(), SvtxTrackState::set_pz(), SvtxTrack::set_pz(), SvtxTrack::set_truth_track_id(), SvtxTrackState::set_x(), SvtxTrack::set_x(), SvtxTrackState::set_y(), SvtxTrack::set_y(), SvtxTrackState::set_z(), SvtxTrack::set_z(), filter::state, and Fun4AllBase::Verbosity().
PHGenFit::PlanarMeasurement * PHG4TrackFastSim::PHG4HitToMeasurementCylinder (const PHG4Hit * g4hit, const double phi_resolution, const double z_resolution) private
Definition at line 1025 of file PHG4TrackFastSim.cc.
View newest version in sPHENIX GitHub at line 1025 of file PHG4TrackFastSim.cc
References PHG4Hit::get_avg_x(), PHG4Hit::get_avg_y(), PHG4Hit::get_avg_z(), m_RandomGenerator, m_SmearingFlag, Acts::Test::pos, physmon_ckf_tracking::u, and testSigmaEff::v.
Referenced by PseudoPatternRecognition().
PHGenFit::PlanarMeasurement * PHG4TrackFastSim::PHG4HitToMeasurementVerticalPlane (const PHG4Hit * g4hit) private
Definition at line 391 of file PHG4HitKalmanFitter.cc.
View newest version in sPHENIX GitHub at line 391 of file PHG4HitKalmanFitter.cc
References _phi_resolution, _r_resolution, PHG4Hit::get_avg_x(), PHG4Hit::get_avg_y(), PHG4Hit::get_avg_z(), Acts::Test::pos, physmon_ckf_tracking::u, and testSigmaEff::v.
Referenced by PseudoPatternRecognition().
PHGenFit::PlanarMeasurement * PHG4TrackFastSim::PHG4HitToMeasurementVerticalPlane (const PHG4Hit * g4hit, const double phi_resolution, const double r_resolution) private
Definition at line 989 of file PHG4TrackFastSim.cc.
View newest version in sPHENIX GitHub at line 989 of file PHG4TrackFastSim.cc
References PHG4Hit::get_avg_x(), PHG4Hit::get_avg_y(), PHG4Hit::get_avg_z(), m_RandomGenerator, m_SmearingFlag, Acts::Test::pos, physmon_ckf_tracking::u, and testSigmaEff::v.
int PHG4TrackFastSim::process_event (PHCompositeNode * topNode) virtual
Process Event, called for each event.
Create measurements
Build TrackRep from particle assumption
mu+: -13 mu-: 13 pi+: 211 pi-: -211 e-: 11 e+: -11
Initiallize track with seed from pattern recognition
Add measurements to track
Fit the track
Reimplemented from SubsysReco.
Definition at line 108 of file PHG4HitKalmanFitter.cc.
View newest version in sPHENIX GitHub at line 108 of file PHG4HitKalmanFitter.cc
References _do_evt_display, _fitter, _trackmap_out, _truth_container, Fun4AllReturnCodes::ABORTRUN, PHGenFit::Track::addMeasurements(), SvtxTrackMap::empty(), Fun4AllReturnCodes::EVENT_OK, GetNodes(), PHG4TruthInfoContainer::GetPrimaryParticleRange(), SvtxTrackMap::insert(), LogError, LogWarning, MakeSvtxTrack(), particle, train_ambiguity_solver::pid, PHGenFit::Fitter::processTrack(), PseudoPatternRecognition(), verbosity, and VertexMeasurement().
int PHG4TrackFastSim::process_event (PHCompositeNode *) override virtual
Process Event, called for each event.
Reimplemented from SubsysReco.
int PHG4TrackFastSim::PseudoPatternRecognition (const PHG4Particle * particle, std::vector< PHGenFit::Measurement * > & meas_out, TVector3 & seed_pos, TVector3 & seed_mom, TMatrixDSym & seed_cov, const bool do_smearing = true) private
Definition at line 268 of file PHG4HitKalmanFitter.cc.
View newest version in sPHENIX GitHub at line 268 of file PHG4HitKalmanFitter.cc
References _N_DETECTOR_LAYER, _pat_rec_hit_finding_eff, _pat_rec_nosise_prob, _phg4hits, _phi_resolution, Fun4AllReturnCodes::EVENT_OK, PHG4Particle::get_px(), PHG4Particle::get_py(), PHG4Particle::get_pz(), PHG4Particle::get_track_id(), PHG4Hit::get_trkid(), i, LogDebug, LogError, and PHG4HitToMeasurementVerticalPlane().
Referenced by process_event().
int PHG4TrackFastSim::PseudoPatternRecognition (const PHG4Particle * particle, std::vector< PHGenFit::Measurement * > & meas_out, SvtxTrack * track_out, TVector3 & seed_pos, TVector3 & seed_mom, TMatrixDSym & seed_cov, const bool do_smearing = true) private
Definition at line 693 of file PHG4TrackFastSim.cc.
View newest version in sPHENIX GitHub at line 693 of file PHG4TrackFastSim.cc
References Fun4AllReturnCodes::ABORTEVENT, SvtxTrack::add_g4hit_id(), assert, Cylinder, Fun4AllReturnCodes::EVENT_OK, PHG4Hit::get_avg_t(), PHG4Hit::get_hit_id(), PHG4Particle::get_px(), PHG4Particle::get_py(), PHG4Particle::get_pz(), PHG4Particle::get_track_id(), PHG4Hit::get_trkid(), i, PHG4Particle::identify(), PHG4Hit::identify(), LogDebug, LogError, m_phg4_detector_hitfindeff, m_phg4_detector_lonres, m_phg4_detector_noise, m_phg4_detector_phires, m_phg4_detector_radres, m_phg4_detector_type, m_PHG4HitContainer, m_PHG4HitsNames, m_RandomGenerator, PHG4HitToMeasurementCylinder(), PHG4HitToMeasurementVerticalPlane(), Fun4AllBase::Verbosity(), and Vertical_Plane.
void PHG4TrackFastSim::set_do_evt_display (bool doEvtDisplay) inline
Definition at line 83 of file PHG4TrackFastSim.h.
View newest version in sPHENIX GitHub at line 83 of file PHG4TrackFastSim.h
References m_DoEvtDisplayFlag.
void PHG4TrackFastSim::set_do_evt_display (bool doEvtDisplay) inline
Definition at line 86 of file PHG4HitKalmanFitter.h.
View newest version in sPHENIX GitHub at line 86 of file PHG4HitKalmanFitter.h
References _do_evt_display.
Referenced by EGEM_FastSim_Reco(), FastSim_Reco_EIC(), and FGEM_FastSim_Reco().
void PHG4TrackFastSim::set_FGEM_phi_resolution (double fgemPhiResolution) inline
Definition at line 96 of file PHG4HitKalmanFitter.h.
View newest version in sPHENIX GitHub at line 96 of file PHG4HitKalmanFitter.h
References _phi_resolution.
void PHG4TrackFastSim::set_FGEM_r_resolution (double fgemRResolution) inline
Definition at line 106 of file PHG4HitKalmanFitter.h.
View newest version in sPHENIX GitHub at line 106 of file PHG4HitKalmanFitter.h
References _r_resolution.
void PHG4TrackFastSim::set_fit_alg_name (const std::string & fitAlgName) inline
Definition at line 93 of file PHG4TrackFastSim.h.
View newest version in sPHENIX GitHub at line 93 of file PHG4TrackFastSim.h
References m_FitAlgoName.
void PHG4TrackFastSim::set_fit_alg_name (const std::string & fitAlgName) inline
Definition at line 116 of file PHG4HitKalmanFitter.h.
View newest version in sPHENIX GitHub at line 116 of file PHG4HitKalmanFitter.h
References _fit_alg_name.
Referenced by EGEM_FastSim_Reco(), FastSim_Reco_EIC(), and FGEM_FastSim_Reco().
void PHG4TrackFastSim::set_pat_rec_hit_finding_eff (double patRecHitFindingEff) inline
Definition at line 126 of file PHG4HitKalmanFitter.h.
View newest version in sPHENIX GitHub at line 126 of file PHG4HitKalmanFitter.h
References _pat_rec_hit_finding_eff.
Referenced by EGEM_FastSim_Reco(), FastSim_Reco_EIC(), and FGEM_FastSim_Reco().
void PHG4TrackFastSim::set_pat_rec_nosise_prob (double patRecNosiseProb) inline
Definition at line 140 of file PHG4HitKalmanFitter.h.
View newest version in sPHENIX GitHub at line 140 of file PHG4HitKalmanFitter.h
References _pat_rec_nosise_prob.
void PHG4TrackFastSim::set_primary_assumption_pid (int primaryAssumptionPid) inline
Definition at line 193 of file PHG4TrackFastSim.h.
View newest version in sPHENIX GitHub at line 193 of file PHG4TrackFastSim.h
References m_PrimaryAssumptionPid.
Referenced by EGEM_FastSim_Reco(), FastSim_Reco_EIC(), and FGEM_FastSim_Reco().
void PHG4TrackFastSim::set_primary_tracking (int pTrk) inline
Definition at line 198 of file PHG4TrackFastSim.h.
View newest version in sPHENIX GitHub at line 198 of file PHG4TrackFastSim.h
References m_PrimaryTrackingFlag.
void PHG4TrackFastSim::set_sub_top_node_name (const std::string & subTopNodeName) inline
Definition at line 153 of file PHG4TrackFastSim.h.
View newest version in sPHENIX GitHub at line 153 of file PHG4TrackFastSim.h
References m_SubTopnodeName.
Referenced by EGEM_FastSim_Reco(), FastSim_Reco_EIC(), FGEM_FastSim_Reco(), Fun4All_G4_Momentum(), Fun4All_G4_Momentum_Projection(), Fun4All_G4_Momentum_Projection_Calorimeters(), and Fun4All_G4_Momentum_Projection_Detectors().
void PHG4TrackFastSim::set_trackmap_out_name (const std::string & trackmapOutName) inline
Definition at line 143 of file PHG4TrackFastSim.h.
View newest version in sPHENIX GitHub at line 143 of file PHG4TrackFastSim.h
References m_TrackmapOutNodeName.
Referenced by EGEM_FastSim_Reco(), FastSim_Reco_EIC(), FGEM_FastSim_Reco(), Fun4All_G4_Momentum(), Fun4All_G4_Momentum_Projection(), Fun4All_G4_Momentum_Projection_Calorimeters(), and Fun4All_G4_Momentum_Projection_Detectors().
void PHG4TrackFastSim::set_use_vertex_in_fitting (bool useVertexInFitting) inline
Definition at line 163 of file PHG4TrackFastSim.h.
View newest version in sPHENIX GitHub at line 163 of file PHG4TrackFastSim.h
References m_UseVertexInFittingFlag.
Referenced by EGEM_FastSim_Reco(), FastSim_Reco_EIC(), FGEM_FastSim_Reco(), Fun4All_G4_Momentum(), Fun4All_G4_Momentum_Projection(), Fun4All_G4_Momentum_Projection_Calorimeters(), and Fun4All_G4_Momentum_Projection_Detectors().
void PHG4TrackFastSim::set_vertex_min_ndf (double vertexMinNdf) inline
Definition at line 220 of file PHG4TrackFastSim.h.
View newest version in sPHENIX GitHub at line 220 of file PHG4TrackFastSim.h
References m_VertexMinNdf.
void PHG4TrackFastSim::set_vertex_xy_resolution (double vertexXyResolution) inline
Definition at line 173 of file PHG4TrackFastSim.h.
View newest version in sPHENIX GitHub at line 173 of file PHG4TrackFastSim.h
References m_VertexXYResolution.
Referenced by EGEM_FastSim_Reco(), FastSim_Reco_EIC(), and FGEM_FastSim_Reco().
void PHG4TrackFastSim::set_vertex_z_resolution (double vertexZResolution) inline
Definition at line 183 of file PHG4TrackFastSim.h.
View newest version in sPHENIX GitHub at line 183 of file PHG4TrackFastSim.h
References m_VertexZResolution.
Referenced by EGEM_FastSim_Reco(), FastSim_Reco_EIC(), and FGEM_FastSim_Reco().
void PHG4TrackFastSim::set_vertexing_method (const std::string & vertexingMethod) inline
https://rave.hepforge.org/trac/wiki/RaveMethods
Definition at line 210 of file PHG4TrackFastSim.h.
View newest version in sPHENIX GitHub at line 210 of file PHG4TrackFastSim.h
References m_VertexingMethod.
void PHG4TrackFastSim::Smearing (const bool b) inline
Definition at line 232 of file PHG4TrackFastSim.h.
View newest version in sPHENIX GitHub at line 232 of file PHG4TrackFastSim.h
References KFPMath::b, and m_SmearingFlag.
void PHG4TrackFastSim::Verbosity (int verb) inline virtual
set verbosity
Reimplemented from Fun4AllBase.
Definition at line 76 of file PHG4HitKalmanFitter.h.
View newest version in sPHENIX GitHub at line 76 of file PHG4HitKalmanFitter.h
References verbosity.
Referenced by EGEM_FastSim_Reco(), FastSim_Reco_EIC(), and FGEM_FastSim_Reco().
PHGenFit::Measurement * PHG4TrackFastSim::VertexMeasurement (const TVector3 & vtx, const double dr, const double dphi) private
Definition at line 424 of file PHG4HitKalmanFitter.cc.
View newest version in sPHENIX GitHub at line 424 of file PHG4HitKalmanFitter.cc
References Acts::Test::pos, physmon_ckf_tracking::u, and testSigmaEff::v.
Referenced by process_event().
PHGenFit::Measurement* PHG4TrackFastSim::VertexMeasurement (const TVector3 & vtx, double dxy, double dz) private
Member Data Documentation
bool PHG4TrackFastSim::_do_evt_display private
Definition at line 199 of file PHG4HitKalmanFitter.h.
View newest version in sPHENIX GitHub at line 199 of file PHG4HitKalmanFitter.h
Referenced by InitRun(), is_do_evt_display(), process_event(), and set_do_evt_display().
int PHG4TrackFastSim::_event private
Event counter.
Definition at line 179 of file PHG4HitKalmanFitter.h.
View newest version in sPHENIX GitHub at line 179 of file PHG4HitKalmanFitter.h
Referenced by GetNodes(), and PHG4TrackFastSim().
std::string PHG4TrackFastSim::_fit_alg_name private
Definition at line 196 of file PHG4HitKalmanFitter.h.
View newest version in sPHENIX GitHub at line 196 of file PHG4HitKalmanFitter.h
Referenced by get_fit_alg_name(), and set_fit_alg_name().
PHGenFit::Fitter* PHG4TrackFastSim::_fitter private
GenFit fitter interface
Definition at line 193 of file PHG4HitKalmanFitter.h.
View newest version in sPHENIX GitHub at line 193 of file PHG4HitKalmanFitter.h
Referenced by InitRun(), process_event(), and ~PHG4TrackFastSim().
double PHG4TrackFastSim::_pat_rec_hit_finding_eff private
Definition at line 210 of file PHG4HitKalmanFitter.h.
View newest version in sPHENIX GitHub at line 210 of file PHG4HitKalmanFitter.h
Referenced by get_pat_rec_hit_finding_eff(), PseudoPatternRecognition(), and set_pat_rec_hit_finding_eff().
double PHG4TrackFastSim::_pat_rec_nosise_prob private
Definition at line 213 of file PHG4HitKalmanFitter.h.
View newest version in sPHENIX GitHub at line 213 of file PHG4HitKalmanFitter.h
Referenced by get_pat_rec_nosise_prob(), PseudoPatternRecognition(), and set_pat_rec_nosise_prob().
std::vector<PHG4HitContainer*> PHG4TrackFastSim::_phg4hits private
Definition at line 184 of file PHG4HitKalmanFitter.h.
View newest version in sPHENIX GitHub at line 184 of file PHG4HitKalmanFitter.h
Referenced by GetNodes(), and PseudoPatternRecognition().
std::vector<std::string> PHG4TrackFastSim::_phg4hits_names private
Definition at line 185 of file PHG4HitKalmanFitter.h.
View newest version in sPHENIX GitHub at line 185 of file PHG4HitKalmanFitter.h
Referenced by GetNodes(), and PHG4TrackFastSim().
double PHG4TrackFastSim::_phi_resolution private
For PseudoPatternRecognition function.
Definition at line 205 of file PHG4HitKalmanFitter.h.
View newest version in sPHENIX GitHub at line 205 of file PHG4HitKalmanFitter.h
Referenced by get_FGEM_phi_resolution(), PHG4HitToMeasurementVerticalPlane(), PseudoPatternRecognition(), and set_FGEM_phi_resolution().
double PHG4TrackFastSim::_r_resolution private
Definition at line 207 of file PHG4HitKalmanFitter.h.
View newest version in sPHENIX GitHub at line 207 of file PHG4HitKalmanFitter.h
Referenced by get_FGEM_r_resolution(), PHG4HitToMeasurementVerticalPlane(), and set_FGEM_r_resolution().
SvtxTrackMap* PHG4TrackFastSim::_trackmap_out private
Output Node pointers.
Definition at line 188 of file PHG4HitKalmanFitter.h.
View newest version in sPHENIX GitHub at line 188 of file PHG4HitKalmanFitter.h
Referenced by CreateNodes(), GetNodes(), and process_event().
PHG4TruthInfoContainer* PHG4TrackFastSim::_truth_container private
Input Node pointers.
Definition at line 182 of file PHG4HitKalmanFitter.h.
View newest version in sPHENIX GitHub at line 182 of file PHG4HitKalmanFitter.h
Referenced by GetNodes(), and process_event().
bool PHG4TrackFastSim::m_DoEvtDisplayFlag protected
Definition at line 332 of file PHG4TrackFastSim.h.
View newest version in sPHENIX GitHub at line 332 of file PHG4TrackFastSim.h
Referenced by DisplayEvent(), is_do_evt_display(), and set_do_evt_display().
bool PHG4TrackFastSim::m_DoVertexingFlag protected
Definition at line 343 of file PHG4TrackFastSim.h.
View newest version in sPHENIX GitHub at line 343 of file PHG4TrackFastSim.h
Referenced by enable_vertexing().
int PHG4TrackFastSim::m_EventCnt protected
Event counter.
Definition at line 325 of file PHG4TrackFastSim.h.
View newest version in sPHENIX GitHub at line 325 of file PHG4TrackFastSim.h
std::string PHG4TrackFastSim::m_FitAlgoName protected
Available choices: KalmanFitter KalmanFitterRefTrack DafSimple DafRef
Definition at line 318 of file PHG4TrackFastSim.h.
View newest version in sPHENIX GitHub at line 318 of file PHG4TrackFastSim.h
Referenced by get_fit_alg_name(), and set_fit_alg_name().
PHGenFit::Fitter* PHG4TrackFastSim::m_Fitter protected
GenFit fitter interface
Definition at line 285 of file PHG4TrackFastSim.h.
View newest version in sPHENIX GitHub at line 285 of file PHG4TrackFastSim.h
Referenced by DisplayEvent().
PHParameters* PHG4TrackFastSim::m_Parameter = nullptr protected
Definition at line 345 of file PHG4TrackFastSim.h.
View newest version in sPHENIX GitHub at line 345 of file PHG4TrackFastSim.h
std::vector<float> PHG4TrackFastSim::m_phg4_detector_hitfindeff protected
Definition at line 300 of file PHG4TrackFastSim.h.
View newest version in sPHENIX GitHub at line 300 of file PHG4TrackFastSim.h
Referenced by add_phg4hits(), and PseudoPatternRecognition().
std::vector<float> PHG4TrackFastSim::m_phg4_detector_lonres protected
Definition at line 299 of file PHG4TrackFastSim.h.
View newest version in sPHENIX GitHub at line 299 of file PHG4TrackFastSim.h
Referenced by add_phg4hits(), and PseudoPatternRecognition().
std::vector<float> PHG4TrackFastSim::m_phg4_detector_noise protected
Definition at line 301 of file PHG4TrackFastSim.h.
View newest version in sPHENIX GitHub at line 301 of file PHG4TrackFastSim.h
Referenced by add_phg4hits(), and PseudoPatternRecognition().
std::vector<float> PHG4TrackFastSim::m_phg4_detector_phires protected
Definition at line 298 of file PHG4TrackFastSim.h.
View newest version in sPHENIX GitHub at line 298 of file PHG4TrackFastSim.h
Referenced by add_phg4hits(), and PseudoPatternRecognition().
std::vector<float> PHG4TrackFastSim::m_phg4_detector_radres protected
Definition at line 297 of file PHG4TrackFastSim.h.
View newest version in sPHENIX GitHub at line 297 of file PHG4TrackFastSim.h
Referenced by add_phg4hits(), and PseudoPatternRecognition().
std::vector<DETECTOR_TYPE> PHG4TrackFastSim::m_phg4_detector_type protected
Definition at line 296 of file PHG4TrackFastSim.h.
View newest version in sPHENIX GitHub at line 296 of file PHG4TrackFastSim.h
Referenced by add_phg4hits(), and PseudoPatternRecognition().
std::vector<PHG4HitContainer*> PHG4TrackFastSim::m_PHG4HitContainer protected
Definition at line 294 of file PHG4TrackFastSim.h.
View newest version in sPHENIX GitHub at line 294 of file PHG4TrackFastSim.h
Referenced by PseudoPatternRecognition().
std::vector<std::string> PHG4TrackFastSim::m_PHG4HitsNames protected
Definition at line 295 of file PHG4TrackFastSim.h.
View newest version in sPHENIX GitHub at line 295 of file PHG4TrackFastSim.h
Referenced by add_phg4hits(), get_phg4hits_names(), and PseudoPatternRecognition().
int PHG4TrackFastSim::m_PrimaryAssumptionPid protected
Definition at line 327 of file PHG4TrackFastSim.h.
View newest version in sPHENIX GitHub at line 327 of file PHG4TrackFastSim.h
Referenced by get_primary_assumption_pid(), and set_primary_assumption_pid().
int PHG4TrackFastSim::m_PrimaryTrackingFlag protected
Definition at line 341 of file PHG4TrackFastSim.h.
View newest version in sPHENIX GitHub at line 341 of file PHG4TrackFastSim.h
Referenced by set_primary_tracking().
std::map<std::string, std::pair<int, double> > PHG4TrackFastSim::m_ProjectionsMap protected
Definition at line 304 of file PHG4TrackFastSim.h.
View newest version in sPHENIX GitHub at line 304 of file PHG4TrackFastSim.h
Referenced by add_cylinder_state(), add_state_name(), add_zplane_state(), and MakeSvtxTrack().
gsl_rng* PHG4TrackFastSim::m_RandomGenerator protected
random generator that conform with sPHENIX standard
Definition at line 280 of file PHG4TrackFastSim.h.
View newest version in sPHENIX GitHub at line 280 of file PHG4TrackFastSim.h
Referenced by PHG4HitToMeasurementCylinder(), PHG4HitToMeasurementVerticalPlane(), and PseudoPatternRecognition().
genfit::GFRaveVertexFactory* PHG4TrackFastSim::m_RaveVertexFactory protected
Definition at line 286 of file PHG4TrackFastSim.h.
View newest version in sPHENIX GitHub at line 286 of file PHG4TrackFastSim.h
bool PHG4TrackFastSim::m_SmearingFlag protected
Definition at line 329 of file PHG4TrackFastSim.h.
View newest version in sPHENIX GitHub at line 329 of file PHG4TrackFastSim.h
Referenced by PHG4HitToMeasurementCylinder(), PHG4HitToMeasurementVerticalPlane(), and Smearing().
std::string PHG4TrackFastSim::m_SubTopnodeName protected
Definition at line 306 of file PHG4TrackFastSim.h.
View newest version in sPHENIX GitHub at line 306 of file PHG4TrackFastSim.h
Referenced by get_sub_top_node_name(), and set_sub_top_node_name().
SvtxTrackMap* PHG4TrackFastSim::m_SvtxTrackMapOut protected
Definition at line 291 of file PHG4TrackFastSim.h.
View newest version in sPHENIX GitHub at line 291 of file PHG4TrackFastSim.h
SvtxVertexMap* PHG4TrackFastSim::m_SvtxVertexMap protected
Definition at line 292 of file PHG4TrackFastSim.h.
View newest version in sPHENIX GitHub at line 292 of file PHG4TrackFastSim.h
Referenced by FillSvtxVertexMap().
std::string PHG4TrackFastSim::m_TrackmapOutNodeName protected
Definition at line 307 of file PHG4TrackFastSim.h.
View newest version in sPHENIX GitHub at line 307 of file PHG4TrackFastSim.h
Referenced by get_trackmap_out_name(), and set_trackmap_out_name().
PHG4TruthInfoContainer* PHG4TrackFastSim::m_TruthContainer protected
Input Node pointers.
Definition at line 289 of file PHG4TrackFastSim.h.
View newest version in sPHENIX GitHub at line 289 of file PHG4TrackFastSim.h
bool PHG4TrackFastSim::m_UseVertexInFittingFlag protected
For PseudoPatternRecognition function.
Definition at line 338 of file PHG4TrackFastSim.h.
View newest version in sPHENIX GitHub at line 338 of file PHG4TrackFastSim.h
Referenced by is_use_vertex_in_fitting(), and set_use_vertex_in_fitting().
std::string PHG4TrackFastSim::m_VertexingMethod protected
https://rave.hepforge.org/trac/wiki/RaveMethods
Definition at line 309 of file PHG4TrackFastSim.h.
View newest version in sPHENIX GitHub at line 309 of file PHG4TrackFastSim.h
Referenced by get_vertexing_method(), and set_vertexing_method().
double PHG4TrackFastSim::m_VertexMinNdf protected
Definition at line 320 of file PHG4TrackFastSim.h.
View newest version in sPHENIX GitHub at line 320 of file PHG4TrackFastSim.h
Referenced by get_vertex_min_ndf(), and set_vertex_min_ndf().
double PHG4TrackFastSim::m_VertexXYResolution protected
Definition at line 321 of file PHG4TrackFastSim.h.
View newest version in sPHENIX GitHub at line 321 of file PHG4TrackFastSim.h
Referenced by get_vertex_xy_resolution(), and set_vertex_xy_resolution().
double PHG4TrackFastSim::m_VertexZResolution protected
Definition at line 322 of file PHG4TrackFastSim.h.
View newest version in sPHENIX GitHub at line 322 of file PHG4TrackFastSim.h
Referenced by get_vertex_z_resolution(), and set_vertex_z_resolution().
The documentation for this class was generated from the following files:
analysis/blob/master/ForwardTracking/PHG4HitKalmanFitter.h
coresoftware/blob/master/simulation/g4simulation/g4trackfastsim/PHG4TrackFastSim.h
analysis/blob/master/ForwardTracking/PHG4HitKalmanFitter.cc
coresoftware/blob/master/simulation/g4simulation/g4trackfastsim/PHG4TrackFastSim.cc