Analysis Software: JETSCAPE/blob/main/jail/vhlle/src/ctrl.h File Reference
ctrl.h File Reference
Functions
void redirecterrorshlle_ (char *filename)
void initeoshlle_ (char *filename, int *ncols)
void initeoshlle3f_ (char *filename, double *B, double *volex0, double *delta0, double *aaa, double *bbb)
void initeoshlle1f_ (char *filename)
void inittrcoeff_ (double *etaS, double *zetaS)
void eoshlle_ (double *e, double *nb, double *nq, double *ns, double *T, double *mub, double *muq, double *mus, double *p)
void eosrangeshlle_ (double *emax, double *e0, double *nmax, double *n0, int *ne, int *nn)
void initfluidhlle_ (int *nx, int *ny, int *nz, double *minx, double *maxx, double *miny, double *maxy, double *minz, double *maxz)
void initichlle_ (char *filename, double *tau0)
void icgethlle3f_ (double *x, double *y, double *eta, double *e, double *nb, double *nq, double *ns, double *vx, double *vy, double *vz)
void icgethlle_ (double *x, double *y, double *eta, double *e, double *nb, double *nq, double *ns, double *vx, double *vy, double *vz)
void icsethlle_ (int *ix, int *iy, int *iz, double *tau0, double *e, double *nb, double *nq, double *ns, double *vx, double *vy, double *vz)
void inithydrohlle_ (double *_tau0, double *_tau_max, double *_dtau)
void initoutputhlle_ (char *dir)
int getmaxstephlle_ (void)
void dtauhlle_ (double *dtau)
void makestephlle_ (int *i)
void destroyhlle_ (void)
void destroyeoshlle_ (void)
void getvalueshlle_ (int *ix, int *iy, int *iz, double *e, double *p, double *nb, double *nq, double *ns, double *vx, double *vy, double *vz, double *viscCorrCutFlag)
void getvflaghlle_ (int *ix, int *iy, int *iz, double *viscCorrCutFlag)
void getvischlle_ (int *ix, int *iy, int *iz, double *pi, double *Pi)
double getxhlle_ (int *ix)
double getyhlle_ (int *iy)
double getzhlle_ (int *iz)
double gettimehlle_ (void)
double getenergyhlle_ (void)
Function Documentation
void destroyeoshlle_ (void)
Definition at line 242 of file ctrl.cpp.
View newest version in sPHENIX GitHub at line 242 of file ctrl.cpp
References eos.
void destroyhlle_ (void)
Definition at line 230 of file ctrl.cpp.
View newest version in sPHENIX GitHub at line 230 of file ctrl.cpp
References end, f, h, ofile, start, and Acts::Test::time.
void dtauhlle_ (double * dtau)
Definition at line 156 of file ctrl.cpp.
View newest version in sPHENIX GitHub at line 156 of file ctrl.cpp
References Hydro::setDtau().
void eoshlle_ (double * e, double * nb, double * nq, double * ns, double * T, double * mub, double * muq, double * mus, double * p)
Definition at line 75 of file ctrl.cpp.
View newest version in sPHENIX GitHub at line 75 of file ctrl.cpp
References EoS::eos().
void eosrangeshlle_ (double * emax, double * e0, double * nmax, double * n0, int * ne, int * nn)
Definition at line 81 of file ctrl.cpp.
View newest version in sPHENIX GitHub at line 81 of file ctrl.cpp
double getenergyhlle_ (void)
Definition at line 255 of file ctrl.cpp.
View newest version in sPHENIX GitHub at line 255 of file ctrl.cpp
References Acts::UnitConstants::e, eta, Fluid::getCell(), Fluid::getNX(), Fluid::getNY(), Fluid::getNZ(), Cell::getPrimVar(), Hydro::getTau(), Fluid::getZ(), Acts::UnitConstants::ns, merge_hashes::p, tau, vx, vy, and vz.
int getmaxstephlle_ (void)
Definition at line 170 of file ctrl.cpp.
View newest version in sPHENIX GitHub at line 170 of file ctrl.cpp
References maxstep.
double gettimehlle_ (void)
Definition at line 248 of file ctrl.cpp.
View newest version in sPHENIX GitHub at line 248 of file ctrl.cpp
References end, start, and Acts::Test::time.
void getvalueshlle_ (int * ix, int * iy, int * iz, double * e, double * p, double * nb, double * nq, double * ns, double * vx, double * vy, double * vz, double * viscCorrCutFlag)
Definition at line 184 of file ctrl.cpp.
View newest version in sPHENIX GitHub at line 184 of file ctrl.cpp
References Acts::PhysicalConstants::c, Acts::UnitConstants::e, Fluid::getCell(), Cell::getPrimVar(), Hydro::getTau(), Cell::getViscCorrCutFlag(), Acts::UnitConstants::ns, merge_hashes::p, vx, vy, and vz.
void getvflaghlle_ (int * ix, int * iy, int * iz, double * viscCorrCutFlag)
Definition at line 192 of file ctrl.cpp.
View newest version in sPHENIX GitHub at line 192 of file ctrl.cpp
References Fluid::getCell(), and Cell::getViscCorrCutFlag().
void getvischlle_ (int * ix, int * iy, int * iz, double * pi, double * Pi)
Definition at line 198 of file ctrl.cpp.
View newest version in sPHENIX GitHub at line 198 of file ctrl.cpp
References Acts::PhysicalConstants::c, Fluid::getCell(), Cell::getpi(), Cell::getPi(), i, and j.
double getxhlle_ (int * ix)
Definition at line 212 of file ctrl.cpp.
View newest version in sPHENIX GitHub at line 212 of file ctrl.cpp
References Fluid::getX().
double getyhlle_ (int * iy)
Definition at line 218 of file ctrl.cpp.
View newest version in sPHENIX GitHub at line 218 of file ctrl.cpp
References Fluid::getY().
double getzhlle_ (int * iz)
Definition at line 224 of file ctrl.cpp.
View newest version in sPHENIX GitHub at line 224 of file ctrl.cpp
References Fluid::getZ().
void icgethlle3f_ (double * x, double * y, double * eta, double * e, double * nb, double * nq, double * ns, double * vx, double * vy, double * vz)
Definition at line 101 of file ctrl.cpp.
View newest version in sPHENIX GitHub at line 101 of file ctrl.cpp
References ic_kw, and Acts::UnitConstants::ns.
void icgethlle_ (double * x, double * y, double * eta, double * e, double * nb, double * nq, double * ns, double * vx, double * vy, double * vz)
Definition at line 112 of file ctrl.cpp.
View newest version in sPHENIX GitHub at line 112 of file ctrl.cpp
References ic_kw, and Acts::UnitConstants::ns.
void icsethlle_ (int * ix, int * iy, int * iz, double * tau0, double * e, double * nb, double * nq, double * ns, double * vx, double * vy, double * vz)
Definition at line 120 of file ctrl.cpp.
View newest version in sPHENIX GitHub at line 120 of file ctrl.cpp
References Acts::PhysicalConstants::c, Fluid::getCell(), Cell::saveQprev(), Cell::setAllM(), and Cell::setPrimVar().
void initeoshlle1f_ (char * filename)
Definition at line 64 of file ctrl.cpp.
View newest version in sPHENIX GitHub at line 64 of file ctrl.cpp
void initeoshlle3f_ (char * filename, double * B, double * volex0, double * delta0, double * aaa, double * bbb)
Definition at line 59 of file ctrl.cpp.
View newest version in sPHENIX GitHub at line 59 of file ctrl.cpp
void initeoshlle_ (char * filename, int * ncols)
Definition at line 53 of file ctrl.cpp.
View newest version in sPHENIX GitHub at line 53 of file ctrl.cpp
void initfluidhlle_ (int * nx, int * ny, int * nz, double * minx, double * maxx, double * miny, double * maxy, double * minz, double * maxz)
Definition at line 87 of file ctrl.cpp.
View newest version in sPHENIX GitHub at line 87 of file ctrl.cpp
void inithydrohlle_ (double * _tau0, double * _tau_max, double * _dtau)
Definition at line 142 of file ctrl.cpp.
View newest version in sPHENIX GitHub at line 142 of file ctrl.cpp
References dtau, maxstep, Hydro::setNSvalues(), start, tau0, tau_max, and Acts::Test::time.
void initichlle_ (char * filename, double * tau0)
Definition at line 94 of file ctrl.cpp.
View newest version in sPHENIX GitHub at line 94 of file ctrl.cpp
References ic_kw.
void initoutputhlle_ (char * dir)
Definition at line 162 of file ctrl.cpp.
View newest version in sPHENIX GitHub at line 162 of file ctrl.cpp
References Hydro::getTau(), Fluid::initOutput(), maxstep, and tau0.
void inittrcoeff_ (double * etaS, double * zetaS)
Definition at line 70 of file ctrl.cpp.
View newest version in sPHENIX GitHub at line 70 of file ctrl.cpp
void makestephlle_ (int * i)
Definition at line 176 of file ctrl.cpp.
View newest version in sPHENIX GitHub at line 176 of file ctrl.cpp
References Hydro::getTau(), and Hydro::performStep().
void redirecterrorshlle_ (char * filename)
Definition at line 45 of file ctrl.cpp.
View newest version in sPHENIX GitHub at line 45 of file ctrl.cpp
References handler(), ofile, and signal().