Analysis Software: SubsysReco Class Reference
SubsysReco Class Reference
#include <coresoftware/blob/master/offline/framework/fun4all/SubsysReco.h>
Inherits Fun4AllBase.
Inherited by analysis, AnalyzeSimpleTree, AnaMvtxPrototype1, AnaMvtxTelescopeHits, AnaMvtxTestBeam2019, AnaSvtxTracksForGenFit, AnaTutorial, AntiTrigger, BbcCheck, BBCStudy, BDiJetModule, BJetModule, BuildResonanceJetTaggingTree, Calib, Calib, CaloAna, CaloAna, CaloAna, CaloCalibEmc_Pi0, CaloCalibration, CaloCalibration, CaloCalibration, CaloCalibration, CaloEvaluator, CaloEvaluator, CaloEvaluator, CaloGeomMapping, CaloTemplateFit, CaloTowerBuilder, CaloTowerCalib, caloTowerEmbed, caloTowerEmbed, CaloTowerStatus, caloTreeGen, caloTreeGen, CaloTriggerSim, CaloUnpackPRDF, CaloUnpackPRDF, CaloUnpackPRDF, CaloUnpackPRDF, CaloValid, CaloWaveformProcessing, CaloWaveFormSim, CaloWaveformSim, CDBInterface, cemcReco, CentralityReco, CentralityValid, ClusterIso, CopyAndSubtractJets, CosmicSpray, DeadHotMapLoader, DecayFinder, DetermineTowerBackground, DirectPhotonPythia, DISKinematicsReco, dNdEtaINTT, DSTEmulator, DSTTrackInfoReader, DSTTrackInfoWriter, Dumper, EdepNtuple, ElectronID, Emcal_Tower_Masking, EMCalAna, EMCalCalib, EMCalCalib_TestBeam, EMCalLikelihood, EMJetVal, EpFinderEval, EventCombiner, EventEvaluator, EventInfoSummary, EventInfoSummary, EventInfoSummary, EventNumberCheck, EventPlaneReco, ExampleAnalysisModule, ExampleAnalysisModule, ExclusiveReco, FastPid_RICH, FastTrackingEval, FermimotionAfterburner, FieldMapReadBack, FillClusMatchTree, fillSpaceChargeMaps, FillTruthRecoMatchMap, FillTruthRecoMatchTree, FilterEvents, FilterEventsUpsilon, FlagHandler, Forward_pi0s, FullJetFinder, G4CellNtuple, G4EdepNtuple, G4HitNtuple, g4hitshift, g4hitshift, g4hitshifthcal, G4HitTTree, G4RawTowerTTree, G4ScintillatorSlatTTree, G4ScintillatorTowerTTree, G4SnglNtuple, G4SnglTree, G4TowerNtuple, G4VtxNtuple, GenericUnpackPRDF, GenericUnpackPRDF, GenericUnpackPRDF, GenericUnpackPRDF, GenFitTrackProp, GlobalVertexFastSimReco, GlobalVertexReco, hcal_towerid, HCALAnalysis, HCalCalibTree, HCalib, HCalJetPhiShift, HcalRawTowerBuilder, HeadReco, HelicalFitter, helixResiduals, HepMCCompress, HepMCFlowAfterBurner, HepMCNodeReader, HFFastSim, HFJetTruthTrigger, HFMLTriggerHepMCTrigger, HFMLTriggerHepMCTrigger, HFMLTriggerInterface, HFMLTriggerInterface, HFMLTriggerOccupancy, HFMLTriggerOccupancy, HFTrackEfficiency, HFTrigger, HFTriggerMVA, hijbkg_upc, HijingCountNtuple, HIJINGFlipAfterburner, HijingShowerSize, HitCountEval, HitCountNtuple, InttCheck, InttClusterizer, InttCombinedRawDataConverter, InttCombinedRawDataDecoder, InttRawDataConverter, InttRawDataDecoder, InttVertexFinder, isoCluster, IsolatedTrackAnalysis, JetBkgdSub, JetEnergies, JetEvaluator, JetHepMCLoader, jetHistogrammer, JetKinematicCheck, JetMultSub, JetNconstituents, JetProbeMaker, JetReco, JetRhoMedian, jetrtrack, JetSeedCount, JetUnderlyingEvent, JetValidation, KFParticle_sPHENIX, KshortReconstruction, LEDTowerBuilder, Leptoquarks, LeptoquarksReco, LiteCaloEval, MakeActsGeometry, MakeMilleFiles, MakeSimpleTree, mbdAnalysis, mbdAnalysis, MbdDigitization, MbdReco, MBDStudy, MbdVertexFastSimReco, MicromegasClusterizer, MicromegasCombinedDataDecoder, MicromegasCombinedDataEvaluation, MicromegasRawDataCalibration, MicromegasRawDataDecoder, MicromegasRawDataEvaluation, MinimumBiasClassifier, MomentumEvaluator, MultiDetectorMultiplicity, MvtxAlign, MvtxApplyHotDead, MvtxClusterizer, MvtxClusterizer, MvtxCombinedRawDataDecoder, MvtxHitPruner, MvtxPrototype2Align, MvtxPrototype2Clusterizer, MvtxPrototype2UnpackPRDF, MvtxQAHisto, MvtxRunInfoUnpackPRDF, MvtxUnpackPRDF, MyJetAnalysis, MyJetAnalysis, OnCal, PairMaker, ParticleFlowReco, PH3DVertexing, PHActsGSF, PHActsKDTreeSeeding, PHActsSiliconSeeding, PHActsToSvtxTracks, PHActsTrackProjection, PHActsTrackPropagator, PHActsTrkFitter, PHActsVertexFitter, PHActsVertexPropagator, PHAJMaker, PHAna, PHCosmicSeedCombiner, PHCosmicSeeder, PHCosmicSiliconPropagator, PHCosmicsTrkFitter, PHCosmicTrackMerger, PHFlowJetMaker, PHG4BlockCellReco, PHG4CentralityReco, PHG4ConsistencyCheck, PHG4CylinderCellReco, PHG4DstCompressReco, PHG4DSTReader, PHG4EPDModuleReco, PHG4FullProjSpacalCellReco, PHG4GenHit, PHG4HcalCellReco, PHG4HeadReco, PHG4HitReadBack, PHG4InEventCompress, PHG4InEventReadBack, PHG4InputFilter, PHG4InttDeadMapLoader, PHG4InttDigitizer, PHG4InttHitReco, PHG4MicromegasDigitizer, PHG4MicromegasHitReco, PHG4MvtxDigitizer, PHG4MvtxHitReco, PHG4ParticleGeneratorBase, PHG4Prototype2HcalCellReco, PHG4Reco, PHG4ScoringManager, PHG4Subsystem, PHG4TpcCentralMembrane, PHG4TpcDigitizer, PHG4TpcDirectLaser, PHG4TpcElectronDrift, PHG4TpcPadBaselineShift, PHG4TpcPadPlane, PHG4TrackFastSim, PHG4TrackFastSim, PHG4TrackFastSimEval, PHG4VertexSelection, PHGenFitTrackProjection, PHGenFitTrkFitter, PHGeomFileImport, PHHepMCParticleSelectorDecayProductChain, PHInitVertexing, PHMicromegasTpcTrackMatching, PhotonJet, Photons, PHPythia6, PHPythia6, PHPythia8, PHRaveVertexing, PHSartre, PHSiliconHelicalPropagator, PHSiliconSeedMerger, PHSiliconTpcTrackMatching, PHSimpleKFProp, PHSimpleVertexFinder, PHTpcCentralMembraneClusterizer, PHTpcCentralMembraneMatcher, PHTpcClusterMover, PHTpcDeltaZCorrection, PHTpcResiduals, PHTpcTrackSeedCircleFit, PHTrackCleaner, PHTrackClusterAssociator, PHTrackFitting, PHTrackPropagating, PHTrackSeeding, PHTrackSelector, PHTrackSetMerging, PHTruthClustering, PHTruthSiliconAssociation, pi0ClusterAna, pi0Efficiency, pi0EtaByEta, Pi0MassAnalysis, PJTranslator, PrintTowers, Proto2ShowerCalib, Proto2ShowerCalib, Proto3ShowerCalib, Proto3ShowerCalib, Proto3ShowerCalib, Proto4SampleFrac, Proto4ShowerCalib, Proto4ShowerCalib, Proto4TowerCalib, Prototype2DSTReader, Prototype2RawTowerBuilder, Prototype3DSTReader, Prototype4DSTReader, Prototype4DSTReader, psTOFTimezeroEval, pythiaEMCalAna, QAG4Decayer, QAG4SimulationCalorimeter, QAG4SimulationCalorimeterSum, QAG4SimulationDistortions, QAG4SimulationIntt, QAG4SimulationJet, QAG4SimulationKFParticle, QAG4SimulationMicromegas, QAG4SimulationMvtx, QAG4SimulationTpc, QAG4SimulationTracking, QAG4SimulationTruthDecay, QAG4SimulationUpsilon, QAG4SimulationVertex, Quarkonia2LeptonsMC, quickHIJING, RandomConeAna, RawClusterBuilderGraph, RawClusterBuilderTemplate, RawClusterBuilderTopo, RawClusterDeadHotMask, RawClusterPositionCorrection, RawClusterZVertexRecorrect, RawTowerBuilder, RawTowerBuilderByHitIndex, RawTowerCalibration, RawTowerCombiner, RawTowerDeadTowerInterp, RawTowerDigitizer, ReactionPlaneAfterburner, readDigitalCurrents, ReadEICFiles, ReadSynRadFiles, RecoConversionEval, RecoInfoExport, ResonanceJetTagging, RetowerCEMC, RhoFluct, RICHEvaluator, RICHParticleID, RunInfoUnpackPRDF, RunInfoUnpackPRDF, RunInfoUnpackPRDF, RunInfoUnpackPRDF, RunTowerInfo, SaveTowerInfo, SColdQcdCorrelatorAnalysis::SCheckTrackPairs, SColdQcdCorrelatorAnalysis::SCorrelatorJetTree, SColdQcdCorrelatorAnalysis::SEnergyCorrelator, SColdQcdCorrelatorAnalysis::SLambdaJetHunter, SecondaryVertexFinder, sHEPGen, ShowerSize, SigmaTimingNtuple, SimpleTrackingAnalysis, singlePhotonClusterAna, SoftLeptonTaggingTruth, sPHAnalysis, sPHAnalysis_calo, STACalorimeterCharacterization, StreamingCheck, SubtractTowers, SubtractTowersCS, SvtxEvaluator, SvtxEvaluatorHaiwang, SvtxSimPerformanceCheckReco, SvtxTrackStateRemoval, SvtxTruthRecoTableEval, SyncReco, SynRadAna, TempInfoUnpackPRDF, TempInfoUnpackPRDF, TempInfoUnpackPRDF, TempInfoUnpackPRDF, TemplateCreation, TimerStats, TimingNtuple, towerid, TowerInfoDeadHotMask, TowerTiming, tpc_hits, TpcCheck, TpcClusterCleaner, TpcClusterizer, TpcClusterQA, TpcCombinedRawDataUnpacker, TPCDataStreamEmulator, TpcDirectLaserReconstruction, TPCFEETestRecov1, TPCGemGainCalb, TPCHitTrackDisplay, TPCIntegratedCharge, TpcLoadDistortionCorrection, TPCMLDataInterface, TPCPedestalCalibration, TpcPrototypeClusterizer, TpcPrototypeGenFitTrkFinder, TpcPrototypeGenFitTrkFitter, TpcPrototypeUnpacker, TpcRawDataDecoder, TpcRawDataTree, TPCRawDataTree, TpcRawWriter, TpcSimpleClusterizer, TpcSpaceChargeReconstruction, TrackClusterEvaluator, TrackContainerCombiner, TrackerEventDisplay, TrackEvaluation, TrackingIterationCounter, TrackingPerformanceCheck, TrackResiduals, TrackSeedTrackMapConverter, TracksInJets, TracksInJets, TreeMaker, TrkrNtuplizer, TruthCaloTree, TruthConversionEval, truthDecayTester, TruthJetTagging, TruthPhotonJet, TruthRecoTrackMatching, UEvsEtaCentrality, and VtxTest.
Public Member Functions
~SubsysReco () override
virtual int End (PHCompositeNode *)
Called at the end of all processing.
virtual int EndRun (const int)
Called at the end of each run.
virtual int Init (PHCompositeNode *)
virtual int InitRun (PHCompositeNode *)
virtual int process_event (PHCompositeNode *)
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
void Print (const std::string &="ALL") const override
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Protected Member Functions
SubsysReco (const std::string &name="NONAME")
Protected Member Functions inherited from Fun4AllBase
Fun4AllBase (const std::string &name="NONAME")
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = std::numeric_limits<int>::max() - 10
}
Detailed Description
Base class for all reconstruction and analysis modules to be used under the Fun4All framework.
If you write a reconstruction/analysis module, you must derive from this base class and you have to implement this class methods. None of these are strictly required as far as C++ is concerned, but as far as your job is concerned, at least process_event(), to do the job, and InitRun(), to initialize, should be implemented.
Definition at line 23 of file SubsysReco.h.
View newest version in sPHENIX GitHub at line 23 of file SubsysReco.h
Constructor & Destructor Documentation
SubsysReco::~SubsysReco () inline override
dtor. Does nothing as this is a base class only.
Definition at line 29 of file SubsysReco.h.
View newest version in sPHENIX GitHub at line 29 of file SubsysReco.h
SubsysReco::SubsysReco (const std::string & name = "NONAME") inline protected
ctor.
Parameters
name is the reference used inside the Fun4AllServer
Definition at line 67 of file SubsysReco.h.
View newest version in sPHENIX GitHub at line 67 of file SubsysReco.h
Member Function Documentation
virtual int SubsysReco::End (PHCompositeNode *) inline virtual
Called at the end of all processing.
Reimplemented in SColdQcdCorrelatorAnalysis::SCorrelatorJetTree, SoftLeptonTaggingTruth, EMCalCalib_TestBeam, TpcSpaceChargeReconstruction, PHGenFitTrkFitter, TpcPrototypeGenFitTrkFitter, EMJetVal, dNdEtaINTT, FillClusMatchTree, JetValidation, SColdQcdCorrelatorAnalysis::SCheckTrackPairs, ResonanceJetTagging, FillTruthRecoMatchTree, RawTowerCombiner, PHG4TrackFastSim, cemcReco, PHG4TrackFastSim, JetKinematicCheck, SecondaryVertexFinder, FullJetFinder, PHActsInitialVertexFinder, HFTrackEfficiency, TruthRecoTrackMatching, SColdQcdCorrelatorAnalysis::SEnergyCorrelator, LiteCaloEval, PHTpcCentralMembraneMatcher, KFParticle_sPHENIX, PHActsTrkFitter, analysis, JetBkgdSub, jetrtrack, JetNconstituents, MyJetAnalysis, towerid, PHTruthVertexing, pi0Efficiency, PHCosmicsTrkFitter, caloTreeGen, readDigitalCurrents, DSTEmulator, RandomConeAna, TruthConversionEval, FillTruthRecoMatchMap, BDiJetModule, HFTriggerMVA, JetSeedCount, PHRaveVertexing, PHTpcCentralMembraneClusterizer, SColdQcdCorrelatorAnalysis::SLambdaJetHunter, hcal_towerid, TruthJetTagging, HelicalFitter, EMCalAna, EMCalCalib, AnaMvtxTestBeam2019, pythiaEMCalAna, GenFitTrackProp, TpcRawDataDecoder, PHActsVertexFinder, AnaMvtxTelescopeHits, VtxTest, fillSpaceChargeMaps, TrkrNtuplizer, PHActsGSF, TrackEvaluation, caloTreeGen, AnaMvtxPrototype1, PHFlowJetMaker, SvtxEvaluator, DISKinematicsReco, pi0ClusterAna, quickHIJING, singlePhotonClusterAna, tpc_hits, PHActsTrackProjection, HFTrigger, KshortReconstruction, JetHepMCLoader, TpcPrototypeGenFitTrkFinder, TpcPrototypeUnpacker, hijbkg_upc, isoCluster, JetMultSub, CaloWaveformSim, LeptoquarksReco, JetEnergies, HCalJetPhiShift, JetUnderlyingEvent, ExampleAnalysisModule, jetHistogrammer, UEvsEtaCentrality, TracksInJets, Pi0MassAnalysis, MvtxClusterizer, TpcDirectLaserReconstruction, PHActsSiliconSeeding, AnaTutorial, Calib, Calib, SynRadAna, ElectronID, PrintTowers, mbdAnalysis, mbdAnalysis, PhotonJet, PHTpcResiduals, TPCFEETestRecov1, PHTruthSiliconAssociation, QAG4SimulationTruthDecay, truthDecayTester, MbdDigitization, MyJetAnalysis, ExclusiveReco, Prototype4DSTReader, MicromegasCombinedDataEvaluation, MicromegasRawDataEvaluation, MakeMilleFiles, PHSimpleKFProp, EventEvaluator, PHG4ScoringManager, PHG4TrackFastSimEval, Prototype3DSTReader, Prototype4DSTReader, BBCStudy, EMCalLikelihood, TruthCaloTree, BuildResonanceJetTaggingTree, PHActsTrackPropagator, PHG4DSTReader, IsolatedTrackAnalysis, Proto4ShowerCalib, PHActsVertexFitter, PHMicromegasTpcTrackMatching, PHSiliconTpcTrackMatching, PHTruthClustering, PHG4TpcElectronDrift, Prototype2DSTReader, BbcCheck, MBDStudy, HFMLTriggerInterface, MultiDetectorMultiplicity, Proto4SampleFrac, Proto4TowerCalib, TPCMLDataInterface, CaloCalibEmc_Pi0, MvtxCombinedRawDataDecoder, PHActsToSvtxTracks, ExampleAnalysisModule, SigmaTimingNtuple, EpFinderEval, AntiTrigger, RecoConversionEval, TPCGemGainCalb, HijingShowerSize, CaloEvaluator, CaloEvaluator, TruthPhotonJet, Proto3ShowerCalib, Proto3ShowerCalib, psTOFTimezeroEval, TPCRawDataTree, FastTrackingEval, SvtxEvaluatorHaiwang, DecayFinder, MvtxHitPruner, TpcRawDataTree, PHGenFitTrackProjection, PHTrackSeeding, QAG4Decayer, MvtxPrototype2Align, Proto2ShowerCalib, Proto2ShowerCalib, Proto3ShowerCalib, HitCountEval, ParticleFlowReco, TrackResiduals, CaloEvaluator, HFMLTriggerInterface, HFMLTriggerOccupancy, HFMLTriggerOccupancy, pi0EtaByEta, MicromegasCombinedDataDecoder, MicromegasRawDataCalibration, TPCDataStreamEmulator, PHActsKDTreeSeeding, PHSimpleVertexFinder, PHTpcClusterMover, JetEvaluator, PHG4TpcPadBaselineShift, MvtxAlign, DirectPhotonPythia, HFFastSim, JetRhoMedian, RICHParticleID, Photons, MicromegasRawDataDecoder, TpcClusterizer, PHCosmicSeeder, PHTrackSetMerging, G4SnglTree, TimingNtuple, caloTowerEmbed, RhoFluct, RICHEvaluator, TrackClusterEvaluator, PHG4TpcDigitizer, MvtxApplyHotDead, MvtxPrototype2Clusterizer, EdepNtuple, HijingCountNtuple, HitCountNtuple, ShowerSize, TowerTiming, HFMLTriggerHepMCTrigger, HFMLTriggerHepMCTrigger, Forward_pi0s, PHPythia8, TpcRawWriter, PHActsVertexPropagator, PHCosmicTrackMerger, PHTrackCleaner, PHTrackPropagating, PHTrackSelector, CaloValid, MvtxUnpackPRDF, Quarkonia2LeptonsMC, CaloAna, sPHAnalysis, BJetModule, HFJetTruthTrigger, FastPid_RICH, CopyAndSubtractJets, PHTpcDeltaZCorrection, G4CellNtuple, G4HitNtuple, G4SnglNtuple, G4TowerNtuple, PHG4MvtxDigitizer, CaloAna, CaloWaveFormSim, sHEPGen, ClusterIso, TpcCombinedRawDataUnpacker, TpcSimpleClusterizer, PHTpcTrackSeedCircleFit, PHTrackClusterAssociator, MvtxClusterizer, MvtxPrototype2UnpackPRDF, CentralityValid, Proto4ShowerCalib, TPCPedestalCalibration, caloTowerEmbed, TpcClusterCleaner, G4EdepNtuple, PHPythia6, HCalib, MbdVertexFastSimReco, Leptoquarks, LEDTowerBuilder, HCalCalibTree, TracksInJets, SaveTowerInfo, AnaSvtxTracksForGenFit, InttVertexFinder, RawTowerBuilderByHitIndex, PHG4InttDigitizer, PHAna, SimpleTrackingAnalysis, STACalorimeterCharacterization, RunTowerInfo, RawClusterBuilderTopo, RawTowerCalibration, MbdReco, G4VtxNtuple, MvtxQAHisto, CaloCalibration, PairMaker, FilterEvents, FilterEventsUpsilon, PHSartre, InttCombinedRawDataConverter, InttRawDataConverter, helixResiduals, PHG4CentralityReco, SvtxTruthRecoTableEval, MvtxRunInfoUnpackPRDF, CaloAna, sPHAnalysis_calo, TemplateCreation, EventPlaneReco, TrackSeedTrackMapConverter, PHSiliconSeedMerger, PHPythia6, InttRawDataDecoder, PHCosmicSeedCombiner, TrackerEventDisplay, Emcal_Tower_Masking, g4hitshift, RecoInfoExport, FlagHandler, TpcClusterQA, TPCIntegratedCharge, PHCosmicSiliconPropagator, TrackingIterationCounter, G4HitTTree, CDBInterface, RawClusterPositionCorrection, RawTowerDeadTowerInterp, TrackContainerCombiner, G4RawTowerTTree, G4ScintillatorSlatTTree, G4ScintillatorTowerTTree, PHG4PileupGenerator, TrackingPerformanceCheck, TreeMaker, RawClusterDeadHotMask, TowerInfoDeadHotMask, SvtxTrackStateRemoval, HCALAnalysis, RawClusterZVertexRecorrect, AnalyzeSimpleTree, TimerStats, PHG4InEventCompress, SvtxSimPerformanceCheckReco, OnCal, RawClusterBuilderGraph, MomentumEvaluator, PHG4InEventReadBack, Dumper, and PHSiliconHelicalPropagator.
Definition at line 32 of file SubsysReco.h.
View newest version in sPHENIX GitHub at line 32 of file SubsysReco.h
Referenced by PHG4PileupGenerator::End().
virtual int SubsysReco::EndRun (const int) inline virtual
Called at the end of each run.
Reimplemented in EMJetVal, dNdEtaINTT, JetValidation, cemcReco, JetKinematicCheck, FullJetFinder, analysis, jetrtrack, JetNconstituents, towerid, pi0Efficiency, caloTreeGen, readDigitalCurrents, JetSeedCount, hcal_towerid, TruthJetTagging, pythiaEMCalAna, caloTreeGen, JetMultSub, pi0ClusterAna, quickHIJING, singlePhotonClusterAna, TPCHitTrackDisplay, hijbkg_upc, isoCluster, HCalJetPhiShift, JetUnderlyingEvent, jetHistogrammer, UEvsEtaCentrality, TracksInJets, Pi0MassAnalysis, SynRadAna, mbdAnalysis, mbdAnalysis, PHTruthSiliconAssociation, ParticleFlowReco, TrackClusterEvaluator, OnCal, TPCPedestalCalibration, TemplateCreation, Emcal_Tower_Masking, g4hitshift, TpcClusterQA, and PHG4PileupGenerator.
Definition at line 35 of file SubsysReco.h.
View newest version in sPHENIX GitHub at line 35 of file SubsysReco.h
Referenced by PHG4PileupGenerator::EndRun().
virtual int SubsysReco::Init (PHCompositeNode *) inline virtual
Called during initialization. Typically this is where you can book histograms, and e.g. register them to Fun4AllServer (so they can be output to file using Fun4AllServer::dumpHistos() method).
Reimplemented in SColdQcdCorrelatorAnalysis::SCorrelatorJetTree, SoftLeptonTaggingTruth, QAG4SimulationJet, EMCalCalib_TestBeam, TpcSpaceChargeReconstruction, PHGenFitTrkFitter, FillClusMatchTree, TpcPrototypeGenFitTrkFitter, SColdQcdCorrelatorAnalysis::SCheckTrackPairs, FillTruthRecoMatchTree, PHAJMaker, ResonanceJetTagging, EMJetVal, dNdEtaINTT, MakeActsGeometry, TruthRecoTrackMatching, SColdQcdCorrelatorAnalysis::SEnergyCorrelator, HFTrackEfficiency, PHG4TrackFastSim, JetValidation, JetBkgdSub, KFParticle_sPHENIX, MyJetAnalysis, RandomConeAna, FillTruthRecoMatchMap, BDiJetModule, PHG4Reco, SColdQcdCorrelatorAnalysis::SLambdaJetHunter, cemcReco, HFTriggerMVA, JetKinematicCheck, AnaMvtxTestBeam2019, AnaMvtxTelescopeHits, TrkrNtuplizer, DSTEmulator, AnaMvtxPrototype1, SvtxEvaluator, EMCalAna, EMCalCalib, FullJetFinder, PHFlowJetMaker, PHActsTrackProjection, PHRaveVertexing, pi0Efficiency, HFTrigger, GenFitTrackProp, TpcPrototypeUnpacker, DISKinematicsReco, JetEnergies, LeptoquarksReco, JetMultSub, PhotonJet, PHActsSiliconSeeding, TrackEvaluation, ElectronID, PrintTowers, analysis, jetrtrack, PHTpcResiduals, PHActsToSvtxTracks, EventEvaluator, MyJetAnalysis, JetNconstituents, TPCFEETestRecov1, CaloWaveformSim, TpcPrototypeGenFitTrkFinder, AnaTutorial, towerid, PHActsVertexFitter, PHG4TpcElectronDrift, PHG4HcalPrototypeSubsystem, ExclusiveReco, Prototype4DSTReader, HFMLTriggerInterface, IsolatedTrackAnalysis, TPCMLDataInterface, TPCHitTrackDisplay, PHActsTrackPropagator, Prototype3DSTReader, Prototype4DSTReader, EMCalLikelihood, caloTreeGen, BuildResonanceJetTaggingTree, readDigitalCurrents, fillSpaceChargeMaps, MvtxClusterizer, TpcDirectLaserReconstruction, PHG4DSTReader, G4Example01Subsystem, Calib, Calib, CaloEvaluator, CaloEvaluator, TruthPhotonJet, Prototype2DSTReader, TruthCaloTree, AntiTrigger, JetSeedCount, MultiDetectorMultiplicity, RecoConversionEval, ExampleAnalysisModule, psTOFTimezeroEval, HitCountEval, SvtxEvaluatorHaiwang, MicromegasCombinedDataEvaluation, MicromegasRawDataEvaluation, PHGenFitTrackProjection, QAG4Decayer, QAG4SimulationTruthDecay, truthDecayTester, CaloEvaluator, PHG4TrackFastSimEval, BBCStudy, PJTranslator, DecayFinder, TrackResiduals, PHG4CEmcTestBeamSubsystem, JetEvaluator, SigmaTimingNtuple, hcal_towerid, HFFastSim, HFMLTriggerInterface, HFMLTriggerOccupancy, HFMLTriggerOccupancy, TruthJetTagging, Photons, Proto4ShowerCalib, TPCDataStreamEmulator, PHActsKDTreeSeeding, PHTrackFitting, MbdDigitization, PHG4EnvelopeSubsystem, HijingShowerSize, BbcCheck, MBDStudy, JetRhoMedian, Proto3ShowerCalib, Proto3ShowerCalib, Proto4SampleFrac, Proto4TowerCalib, pythiaEMCalAna, FastTrackingEval, MvtxCombinedRawDataDecoder, TpcRawDataDecoder, PHCosmicSeeder, PHTrackSetMerging, PHTruthSiliconAssociation, QAG4SimulationCalorimeterSum, DirectPhotonPythia, EpFinderEval, RhoFluct, Forward_pi0s, Proto2ShowerCalib, Proto2ShowerCalib, Proto3ShowerCalib, ExampleAnalysisModule, PHPythia8, QAG4SimulationKFParticle, QAG4SimulationTracking, PHG4SectorSubsystem, caloTreeGen, HFMLTriggerHepMCTrigger, HFMLTriggerHepMCTrigger, pi0EtaByEta, PHActsVertexPropagator, PHCosmicTrackMerger, QAG4SimulationCalorimeter, sPHAnalysis, BJetModule, RICHParticleID, pi0ClusterAna, quickHIJING, singlePhotonClusterAna, TrackClusterEvaluator, sHEPGen, ClusterIso, MvtxHitPruner, tpc_hits, PHG4TpcPadBaselineShift, MvtxPrototype2Align, TimingNtuple, Quarkonia2LeptonsMC, HFJetTruthTrigger, RICHEvaluator, TpcCombinedRawDataUnpacker, EdepNtuple, HijingCountNtuple, HitCountNtuple, ShowerSize, TowerTiming, hijbkg_upc, HCalib, isoCluster, Proto4ShowerCalib, MicromegasCombinedDataDecoder, MicromegasRawDataCalibration, ParticleFlowReco, CaloValid, MvtxAlign, CaloAna, HCalJetPhiShift, JetUnderlyingEvent, FastPid_RICH, jetHistogrammer, MicromegasRawDataDecoder, MbdVertexFastSimReco, G4CellNtuple, G4HitNtuple, G4SnglNtuple, G4SnglTree, G4TowerNtuple, CaloAna, CaloWaveFormSim, ReadSynRadFiles, UEvsEtaCentrality, TracksInJets, Pi0MassAnalysis, SimpleTrackingAnalysis, STACalorimeterCharacterization, QAG4SimulationVertex, PHG4DetectorGroupSubsystem, PHG4DetectorSubsystem, PHG4TpcDigitizer, MvtxApplyHotDead, MvtxPrototype2Clusterizer, CentralityValid, SynRadAna, Leptoquarks, HCalCalibTree, TracksInJets, mbdAnalysis, mbdAnalysis, FermimotionAfterburner, CaloGeomMapping, MbdReco, MicromegasClusterizer, QAG4SimulationDistortions, G4EdepNtuple, ReadEICFiles, MvtxUnpackPRDF, PHPythia6, PairMaker, FilterEvents, FilterEventsUpsilon, PHSartre, InttCombinedRawDataConverter, InttRawDataConverter, PHG4MvtxDigitizer, sPHAnalysis_calo, SaveTowerInfo, AnaSvtxTracksForGenFit, EventPlaneReco, MvtxClusterizer, MvtxPrototype2UnpackPRDF, PHAna, RunTowerInfo, EventNumberCheck, InttRawDataDecoder, PHCosmicSeedCombiner, PHSiliconSeedMerger, TrackerEventDisplay, SvtxTruthRecoTableEval, G4VtxNtuple, HepMCNodeReader, MvtxQAHisto, CaloCalibration, TemplateCreation, ReactionPlaneAfterburner, EventCombiner, TPCIntegratedCharge, PHCosmicSiliconPropagator, TrackingIterationCounter, QAG4SimulationUpsilon, CaloAna, RecoInfoExport, TrackingPerformanceCheck, InttCheck, StreamingCheck, TpcCheck, InttVertexFinder, TpcClusterQA, CaloUnpackPRDF, Emcal_Tower_Masking, g4hitshift, TreeMaker, PHPythia6, G4HitTTree, HCALAnalysis, HepMCFlowAfterBurner, SvtxTrackStateRemoval, G4RawTowerTTree, G4ScintillatorSlatTTree, G4ScintillatorTowerTTree, HepMCCompress, MvtxRunInfoUnpackPRDF, PHG4PileupGenerator, SvtxSimPerformanceCheckReco, HeadReco, MomentumEvaluator, PHG4HeadReco, AnalyzeSimpleTree, SyncReco, and MakeSimpleTree.
Definition at line 42 of file SubsysReco.h.
View newest version in sPHENIX GitHub at line 42 of file SubsysReco.h
Referenced by PHG4PileupGenerator::Init(), TpcPrototypeUnpacker::Init(), Fun4AllInputManager::registerSubsystem(), and Fun4AllServer::registerSubsystem().
virtual int SubsysReco::InitRun (PHCompositeNode *) inline virtual
Called for first event when run number is known. Typically this is where you may want to fetch data from database, because you know the run number.
Reimplemented in SoftLeptonTaggingTruth, QAG4SimulationJet, EMCalCalib_TestBeam, TpcSpaceChargeReconstruction, PHGenFitTrkFitter, FillClusMatchTree, TpcPrototypeGenFitTrkFitter, FillTruthRecoMatchTree, EMJetVal, dNdEtaINTT, RawTowerCombiner, JetValidation, PHG4TrackFastSim, MakeActsGeometry, PHActsTrkFitter, SecondaryVertexFinder, PHG4TrackFastSim, TruthRecoTrackMatching, PHCosmicsTrkFitter, KFParticle_sPHENIX, cemcReco, PHTpcCentralMembraneMatcher, MyJetAnalysis, JetKinematicCheck, LiteCaloEval, FillTruthRecoMatchMap, PHG4Reco, BDiJetModule, FullJetFinder, DSTEmulator, AnaMvtxTestBeam2019, TruthConversionEval, AnaMvtxTelescopeHits, HelicalFitter, TrkrNtuplizer, PHActsGSF, PHRaveVertexing, EMCalAna, EMCalCalib, analysis, jetrtrack, AnaMvtxPrototype1, PHTpcCentralMembraneClusterizer, SvtxEvaluator, JetNconstituents, pi0Efficiency, PHActsTrackProjection, GenFitTrackProp, KshortReconstruction, JetHepMCLoader, DISKinematicsReco, towerid, VtxTest, DSTTrackInfoWriter, TrackEvaluation, TpcPrototypeUnpacker, JetEnergies, caloTreeGen, JetMultSub, readDigitalCurrents, fillSpaceChargeMaps, PHActsSiliconSeeding, ElectronID, PrintTowers, JetReco, PHTpcResiduals, PHActsToSvtxTracks, TpcPrototypeGenFitTrkFinder, MyJetAnalysis, JetSeedCount, TPCFEETestRecov1, MakeMilleFiles, PHSimpleKFProp, DSTTrackInfoReader, ExclusiveReco, hcal_towerid, TruthJetTagging, MvtxClusterizer, TpcDirectLaserReconstruction, TPCHitTrackDisplay, PHActsVertexFitter, PHMicromegasTpcTrackMatching, PHTruthClustering, PHG4TpcElectronDrift, EMCalLikelihood, HFMLTriggerInterface, IsolatedTrackAnalysis, ExampleAnalysisModule, pythiaEMCalAna, TPCMLDataInterface, TpcRawDataDecoder, PHActsTrackPropagator, Calib, Calib, MicromegasCombinedDataEvaluation, MicromegasRawDataEvaluation, PHSiliconTpcTrackMatching, PHG4ScoringManager, PHG4TrackFastSimEval, BBCStudy, caloTreeGen, RecoConversionEval, pi0ClusterAna, Proto4ShowerCalib, psTOFTimezeroEval, quickHIJING, singlePhotonClusterAna, SvtxEvaluatorHaiwang, tpc_hits, PHGenFitTrackProjection, PHTrackSeeding, MbdDigitization, BbcCheck, MBDStudy, Proto4SampleFrac, Proto4TowerCalib, MvtxCombinedRawDataDecoder, TrackResiduals, hijbkg_upc, HFMLTriggerInterface, HFMLTriggerOccupancy, HFMLTriggerOccupancy, isoCluster, Proto3ShowerCalib, Proto3ShowerCalib, ExampleAnalysisModule, TPCDataStreamEmulator, PH3DVertexing, PHActsKDTreeSeeding, PHSimpleVertexFinder, PHTpcClusterMover, PHTrackFitting, PHTruthSiliconAssociation, PHG4HcalSubsystem, EpFinderEval, JetRhoMedian, HCalJetPhiShift, JetUnderlyingEvent, Proto2ShowerCalib, Proto2ShowerCalib, Proto3ShowerCalib, jetHistogrammer, CaloCalibEmc_Pi0, TpcClusterizer, PHCosmicSeeder, PHTrackSetMerging, QAG4SimulationCalorimeterSum, PHG4MicromegasHitReco, caloTowerEmbed, RhoFluct, UEvsEtaCentrality, TracksInJets, Pi0MassAnalysis, DetermineTowerBackground, MvtxHitPruner, CaloTriggerSim, QAG4SimulationKFParticle, QAG4SimulationTracking, PHG4InttHitReco, PHG4MvtxHitReco, MvtxPrototype2Align, SynRadAna, HFMLTriggerHepMCTrigger, HFMLTriggerHepMCTrigger, mbdAnalysis, mbdAnalysis, RICHParticleID, TPCGemGainCalb, TpcRawWriter, PHActsVertexPropagator, PHCosmicTrackMerger, PHTrackCleaner, PHTrackPropagating, PHTrackSelector, QAG4SimulationCalorimeter, QAG4SimulationTpc, PHG4TpcPadPlaneReadout, sPHAnalysis, RICHEvaluator, TPCRawDataTree, TrackClusterEvaluator, CopyAndSubtractJets, RetowerCEMC, MicromegasCombinedDataDecoder, MicromegasRawDataCalibration, TpcRawDataTree, PHInitVertexing, PHTpcDeltaZCorrection, QAG4SimulationMicromegas, PHG4TpcPadBaselineShift, MvtxAlign, DeadHotMapLoader, InttClusterizer, SubtractTowers, SubtractTowersCS, MicromegasRawDataDecoder, ParticleFlowReco, TpcCombinedRawDataUnpacker, TpcSimpleClusterizer, RawTowerDigitizer, PHG4InttDeadMapLoader, GlobalVertexFastSimReco, FastPid_RICH, Proto4ShowerCalib, caloTowerEmbed, TpcClusterCleaner, PHTrackClusterAssociator, PHG4FullProjSpacalCellReco, PHG4ParticleGeneratorVectorMeson, PHG4SimpleEventGenerator, PHG4TpcDigitizer, PHG4TpcDirectLaser, PHG4TpcPadPlane, MvtxApplyHotDead, MvtxPrototype2Clusterizer, CaloTemplateFit, GlobalVertexReco, MicromegasClusterizer, PHTpcTrackSeedCircleFit, MbdVertexFastSimReco, PHG4MicromegasDigitizer, PHG4TpcCentralMembrane, MvtxUnpackPRDF, LEDTowerBuilder, MinimumBiasClassifier, QAG4SimulationVertex, PHG4DetectorGroupSubsystem, PHG4DetectorSubsystem, PHG4TruthSubsystem, PHG4MvtxDigitizer, CentralityValid, TracksInJets, CaloTowerCalib, CaloTowerStatus, RawClusterBuilderTopo, RawTowerCalibration, MbdReco, TpcLoadDistortionCorrection, QAG4SimulationDistortions, QAG4SimulationIntt, QAG4SimulationMvtx, MvtxClusterizer, MvtxPrototype2UnpackPRDF, PairMaker, FilterEvents, FilterEventsUpsilon, PHHepMCParticleSelectorDecayProductChain, CaloTowerBuilder, InttCombinedRawDataConverter, InttRawDataConverter, helixResiduals, RawTowerBuilderByHitIndex, PHG4CentralityReco, PHG4CylinderCellReco, PHG4DstCompressReco, sPHAnalysis_calo, EventPlaneReco, TrackSeedTrackMapConverter, PHG4BlockCellReco, PHG4VertexSelection, CaloCalibration, FieldMapReadBack, TPCPedestalCalibration, CentralityReco, InttRawDataDecoder, InttVertexFinder, PHCosmicSeedCombiner, PHSiliconSeedMerger, TrackerEventDisplay, HcalRawTowerBuilder, PHG4EPDModuleReco, SvtxTruthRecoTableEval, PHG4InttDigitizer, CaloCalibration, TemplateCreation, TPCIntegratedCharge, PHCosmicSiliconPropagator, TrackingIterationCounter, QAG4SimulationUpsilon, PHG4HcalCellReco, CaloCalibration, CaloUnpackPRDF, CaloCalibration, FlagHandler, RawClusterPositionCorrection, RawTowerDeadTowerInterp, JetProbeMaker, TpcClusterQA, TrackContainerCombiner, CosmicSpray, PHG4ParticleGeneratorBase, MvtxRunInfoUnpackPRDF, Emcal_Tower_Masking, CaloUnpackPRDF, g4hitshift, TreeMaker, RawClusterBuilderTemplate, CaloUnpackPRDF, CaloUnpackPRDF, GenericUnpackPRDF, TempInfoUnpackPRDF, RawClusterDeadHotMask, TowerInfoDeadHotMask, InttCombinedRawDataDecoder, SvtxTrackStateRemoval, RawTowerBuilder, GenericUnpackPRDF, TempInfoUnpackPRDF, GenericUnpackPRDF, TempInfoUnpackPRDF, GenericUnpackPRDF, TempInfoUnpackPRDF, TpcPrototypeClusterizer, PHG4Prototype2HcalCellReco, RawClusterZVertexRecorrect, PHG4ParticleGeneratorD0, PHG4PileupGenerator, Prototype2RawTowerBuilder, EventInfoSummary, RunInfoUnpackPRDF, HeadReco, TimerStats, PHG4ConsistencyCheck, PHG4InEventCompress, RunInfoUnpackPRDF, EventInfoSummary, RunInfoUnpackPRDF, EventInfoSummary, RunInfoUnpackPRDF, SyncReco, RawClusterBuilderGraph, PHGeomFileImport, PHG4InEventReadBack, PHG4HitReadBack, and PHSiliconHelicalPropagator.
Definition at line 48 of file SubsysReco.h.
View newest version in sPHENIX GitHub at line 48 of file SubsysReco.h
void SubsysReco::Print (const std::string & what = "ALL") const inline override virtual
Print out some info about this module.
Parameters
what can be used to specify what to print exactly.
Reimplemented from Fun4AllBase.
Reimplemented in HcalRawTowerBuilder, PHG4HcalSubsystem, PHG4Reco, PHG4PSTOFSubsystem, PHG4BbcSubsystem, PHG4SpacalSubsystem, PHG4MicromegasSubsystem, G4Example03Subsystem, G4Example02Subsystem, G4Example01Subsystem, PHTruthSiliconAssociation, PHG4InttSubsystem, PHG4TpcEndCapSubsystem, PHG4GDMLSubsystem, PHActsTrackPropagator, PHG4SpacalPrototypeSubsystem, PHG4SpacalPrototype4Subsystem, ParticleFlowReco, PHG4CylinderSubsystem, BeamLineMagnetSubsystem, PHG4BeamlineMagnetSubsystem, PHG4TpcSubsystem, PHG4Prototype2InnerHcalSubsystem, PHG4Prototype2OuterHcalSubsystem, PHG4Prototype3InnerHcalSubsystem, PHG4InnerHcalSubsystem, PHG4IHCalSubsystem, PHG4OuterHcalSubsystem, PHG4OHCalSubsystem, PHG4ParticleGeneratorBase, PHG4IonGun, PHG4ParticleGenerator, and Prototype2RawTowerBuilder.
Definition at line 61 of file SubsysReco.h.
View newest version in sPHENIX GitHub at line 61 of file SubsysReco.h
virtual int SubsysReco::process_event (PHCompositeNode *) inline virtual
Called for each event. This is where you do the real work.
Reimplemented in SColdQcdCorrelatorAnalysis::SCorrelatorJetTree, SoftLeptonTaggingTruth, QAG4SimulationJet, EMCalCalib_TestBeam, TpcSpaceChargeReconstruction, PHGenFitTrkFitter, TpcPrototypeGenFitTrkFitter, FillClusMatchTree, EMJetVal, SColdQcdCorrelatorAnalysis::SCheckTrackPairs, dNdEtaINTT, PHAJMaker, FillTruthRecoMatchTree, ResonanceJetTagging, JetValidation, RawTowerCombiner, PHG4TrackFastSim, PHActsTrkFitter, PHG4TrackFastSim, SecondaryVertexFinder, TruthRecoTrackMatching, HFTrackEfficiency, PHCosmicsTrkFitter, SColdQcdCorrelatorAnalysis::SEnergyCorrelator, cemcReco, JetKinematicCheck, LiteCaloEval, KFParticle_sPHENIX, PHTpcCentralMembraneMatcher, JetBkgdSub, MyJetAnalysis, FullJetFinder, PHG4Reco, PHG4PSTOFSubsystem, RandomConeAna, TruthConversionEval, FillTruthRecoMatchMap, BDiJetModule, DSTEmulator, HFTriggerMVA, analysis, jetrtrack, PHG4BbcSubsystem, SColdQcdCorrelatorAnalysis::SLambdaJetHunter, JetNconstituents, PHRaveVertexing, AnaMvtxTestBeam2019, PHTpcCentralMembraneClusterizer, HelicalFitter, EMCalAna, EMCalCalib, towerid, AnaMvtxTelescopeHits, VtxTest, TrkrNtuplizer, PHActsGSF, AnaMvtxPrototype1, pi0Efficiency, GenFitTrackProp, SvtxEvaluator, caloTreeGen, PHFlowJetMaker, readDigitalCurrents, fillSpaceChargeMaps, PHActsTrackProjection, DSTTrackInfoWriter, TrackEvaluation, DISKinematicsReco, KshortReconstruction, JetHepMCLoader, HFTrigger, JetSeedCount, PHG4SpacalSubsystem, TpcPrototypeUnpacker, JetEnergies, G4Example03Subsystem, TpcPrototypeGenFitTrkFinder, PHG4HcalPrototypeSubsystem, LeptoquarksReco, hcal_towerid, JetMultSub, TruthJetTagging, PHActsSiliconSeeding, DSTTrackInfoReader, PHG4MicromegasSubsystem, CaloWaveformSim, ElectronID, PrintTowers, PhotonJet, pythiaEMCalAna, JetReco, TpcRawDataDecoder, PHTpcResiduals, PHActsToSvtxTracks, PHG4GDMLSubsystem, G4Example02Subsystem, G4Example01Subsystem, MyJetAnalysis, ExampleAnalysisModule, MvtxClusterizer, TpcDirectLaserReconstruction, TPCFEETestRecov1, TPCHitTrackDisplay, MakeMilleFiles, PHSimpleKFProp, EventEvaluator, PHG4TpcEndCapSubsystem, AnaTutorial, ExclusiveReco, caloTreeGen, Calib, Calib, EMCalLikelihood, Prototype4DSTReader, TruthCaloTree, pi0ClusterAna, quickHIJING, singlePhotonClusterAna, MicromegasCombinedDataEvaluation, MicromegasRawDataEvaluation, tpc_hits, PHActsTrackPropagator, PHMicromegasTpcTrackMatching, PHTruthClustering, PHG4CEmcTestBeamSubsystem, PHG4HcalSubsystem, PHG4InttSubsystem, PHG4ScoringManager, PHG4TpcElectronDrift, PHG4TrackFastSimEval, Prototype3DSTReader, Prototype4DSTReader, BBCStudy, HFMLTriggerInterface, IsolatedTrackAnalysis, BuildResonanceJetTaggingTree, TPCMLDataInterface, PHSiliconTpcTrackMatching, QAG4SimulationTruthDecay, truthDecayTester, PHG4DSTReader, hijbkg_upc, isoCluster, Proto4ShowerCalib, MbdDigitization, Prototype2DSTReader, BbcCheck, MBDStudy, HCalJetPhiShift, JetUnderlyingEvent, MultiDetectorMultiplicity, RecoConversionEval, Proto4SampleFrac, Proto4TowerCalib, jetHistogrammer, CaloCalibEmc_Pi0, MvtxCombinedRawDataDecoder, PHActsVertexFitter, PHG4SectorSubsystem, PHG4EICMvtxSubsystem, PHG4MvtxSubsystem, CaloEvaluator, CaloEvaluator, AntiTrigger, UEvsEtaCentrality, TracksInJets, TruthPhotonJet, Pi0MassAnalysis, ExampleAnalysisModule, psTOFTimezeroEval, SvtxEvaluatorHaiwang, PHGenFitTrackProjection, PHTrackSeeding, QAG4Decayer, PHG4BlockSubsystem, PHG4ConeSubsystem, PHG4CylinderSubsystem, PHG4SpacalPrototypeSubsystem, SigmaTimingNtuple, SynRadAna, EpFinderEval, mbdAnalysis, mbdAnalysis, Proto3ShowerCalib, Proto3ShowerCalib, PJTranslator, HitCountEval, DecayFinder, TrackResiduals, PHTruthSiliconAssociation, BeamLineMagnetSubsystem, PHG4BeamlineMagnetSubsystem, PHG4EnvelopeSubsystem, CaloEvaluator, PHG4MicromegasHitReco, PHG4TpcSubsystem, PHG4Prototype2InnerHcalSubsystem, PHG4Prototype2OuterHcalSubsystem, PHG4Prototype3InnerHcalSubsystem, HijingShowerSize, HFMLTriggerInterface, HFMLTriggerOccupancy, HFMLTriggerOccupancy, Proto2ShowerCalib, Proto2ShowerCalib, Proto3ShowerCalib, TPCRawDataTree, FastTrackingEval, MvtxHitPruner, TpcRawDataTree, TPCDataStreamEmulator, PH3DVertexing, PHActsKDTreeSeeding, PHSimpleVertexFinder, PHTpcClusterMover, PHTrackFitting, PHG4InnerHcalSubsystem, JetEvaluator, PHG4IHCalSubsystem, PHG4InttHitReco, PHG4MvtxHitReco, MvtxPrototype2Align, PHG4SpacalPrototype4Subsystem, HFFastSim, JetRhoMedian, Photons, TPCGemGainCalb, TpcClusterizer, PHCosmicSeeder, PHTrackSetMerging, QAG4SimulationCalorimeterSum, PHG4OuterHcalSubsystem, PHG4OHCalSubsystem, caloTowerEmbed, DirectPhotonPythia, RhoFluct, RICHParticleID, pi0EtaByEta, DetermineTowerBackground, MicromegasCombinedDataDecoder, MicromegasRawDataCalibration, CaloTriggerSim, QAG4SimulationKFParticle, QAG4SimulationTracking, MvtxAlign, HFMLTriggerHepMCTrigger, HFMLTriggerHepMCTrigger, RICHEvaluator, Forward_pi0s, PHPythia8, InttClusterizer, MicromegasRawDataDecoder, TpcRawWriter, PHActsVertexPropagator, PHCosmicTrackMerger, PHTrackCleaner, PHTrackPropagating, PHTrackSelector, QAG4SimulationCalorimeter, QAG4SimulationTpc, PHG4ZDCSubsystem, TimingNtuple, sPHAnalysis, BJetModule, TrackClusterEvaluator, CopyAndSubtractJets, RetowerCEMC, ParticleFlowReco, PHInitVertexing, PHTpcDeltaZCorrection, MinimumBiasClassifier, QAG4SimulationMicromegas, PHG4FullProjSpacalCellReco, PHG4TpcDigitizer, PHG4TpcDirectLaser, PHG4TpcPadBaselineShift, MvtxApplyHotDead, MvtxPrototype2Clusterizer, EdepNtuple, HijingCountNtuple, HitCountNtuple, ShowerSize, TowerTiming, Quarkonia2LeptonsMC, HFJetTruthTrigger, FastPid_RICH, sHEPGen, ClusterIso, SubtractTowers, SubtractTowersCS, MicromegasClusterizer, TpcCombinedRawDataUnpacker, TpcSimpleClusterizer, RawTowerDigitizer, PHG4MicromegasDigitizer, PHG4TpcCentralMembrane, GlobalVertexFastSimReco, CaloValid, MvtxUnpackPRDF, CaloAna, CaloTemplateFit, Proto4ShowerCalib, FermimotionAfterburner, caloTowerEmbed, CentralityReco, TpcClusterCleaner, PHTpcTrackSeedCircleFit, PHTrackClusterAssociator, PHG4EPDSubsystem, G4CellNtuple, G4HitNtuple, G4SnglNtuple, G4SnglTree, G4TowerNtuple, PHG4ParticleGeneratorVectorMeson, PHG4SimpleEventGenerator, PHG4TruthSubsystem, PHG4MvtxDigitizer, CaloAna, CaloWaveFormSim, HCalib, GlobalVertexReco, TpcLoadDistortionCorrection, MbdVertexFastSimReco, MvtxClusterizer, MvtxPrototype2UnpackPRDF, FieldMapReadBack, CentralityValid, LEDTowerBuilder, QAG4SimulationVertex, PHG4CylinderCellReco, PHG4DstCompressReco, G4EdepNtuple, ReadSynRadFiles, Leptoquarks, TracksInJets, SimpleTrackingAnalysis, STACalorimeterCharacterization, CaloTowerCalib, CaloTowerStatus, RawClusterBuilderTopo, RawTowerCalibration, MbdReco, QAG4SimulationDistortions, QAG4SimulationIntt, QAG4SimulationMvtx, RawTowerBuilderByHitIndex, PHG4BlockCellReco, PHG4VertexSelection, PHPythia6, PairMaker, FilterEvents, FilterEventsUpsilon, HCalCalibTree, SaveTowerInfo, AnaSvtxTracksForGenFit, PHHepMCParticleSelectorDecayProductChain, CaloTowerBuilder, InttCombinedRawDataConverter, InttRawDataConverter, InttVertexFinder, helixResiduals, PHG4CentralityReco, PHG4EPDModuleReco, PHG4InttDigitizer, ReadEICFiles, CaloCalibration, PHAna, sPHAnalysis_calo, RunTowerInfo, TPCPedestalCalibration, PHSartre, EventPlaneReco, TrackSeedTrackMapConverter, PHG4HcalCellReco, G4VtxNtuple, PHG4TpcPadPlane, MvtxQAHisto, CaloCalibration, ReactionPlaneAfterburner, EventNumberCheck, InttRawDataDecoder, PHCosmicSeedCombiner, PHSiliconSeedMerger, TrackerEventDisplay, HcalRawTowerBuilder, SvtxTruthRecoTableEval, MvtxRunInfoUnpackPRDF, CaloCalibration, CaloUnpackPRDF, CaloCalibration, CaloAna, TemplateCreation, EventCombiner, TPCIntegratedCharge, PHCosmicSiliconPropagator, TrackingIterationCounter, QAG4SimulationUpsilon, HepMCNodeReader, CaloUnpackPRDF, RecoInfoExport, HIJINGFlipAfterburner, InttCheck, StreamingCheck, TpcCheck, RawClusterPositionCorrection, RawTowerDeadTowerInterp, TpcClusterQA, TrackContainerCombiner, G4HitTTree, CosmicSpray, PHG4ParticleGeneratorBase, CaloUnpackPRDF, CaloUnpackPRDF, PHG4Prototype2HcalCellReco, Emcal_Tower_Masking, GenericUnpackPRDF, TempInfoUnpackPRDF, g4hitshift, TrackingPerformanceCheck, TreeMaker, PHPythia6, RawClusterBuilderTemplate, G4RawTowerTTree, G4ScintillatorSlatTTree, G4ScintillatorTowerTTree, GenericUnpackPRDF, TempInfoUnpackPRDF, GenericUnpackPRDF, TempInfoUnpackPRDF, GenericUnpackPRDF, TempInfoUnpackPRDF, RawClusterDeadHotMask, TowerInfoDeadHotMask, InttCombinedRawDataDecoder, JetProbeMaker, SvtxTrackStateRemoval, RawTowerBuilder, PHG4ConsistencyCheck, TpcPrototypeClusterizer, EventInfoSummary, RunInfoUnpackPRDF, HCALAnalysis, HepMCFlowAfterBurner, RawClusterZVertexRecorrect, g4hitshifthcal, HepMCCompress, PHG4ParticleGeneratorD0, PHG4PileupGenerator, RunInfoUnpackPRDF, EventInfoSummary, RunInfoUnpackPRDF, EventInfoSummary, RunInfoUnpackPRDF, Prototype2RawTowerBuilder, HeadReco, TimerStats, g4hitshift, PHG4GenHit, PHG4InEventCompress, PHG4IonGun, PHG4ParticleGenerator, AnalyzeSimpleTree, SvtxSimPerformanceCheckReco, OnCal, SyncReco, RawClusterBuilderGraph, MomentumEvaluator, PHG4HeadReco, PHG4InEventReadBack, PHG4InputFilter, Dumper, PHG4HitReadBack, PHG4ParticleGun, PHSiliconHelicalPropagator, and MakeSimpleTree.
Definition at line 53 of file SubsysReco.h.
View newest version in sPHENIX GitHub at line 53 of file SubsysReco.h
virtual int SubsysReco::Reset (PHCompositeNode *) inline virtual
Reset.
Reimplemented in EMJetVal, dNdEtaINTT, JetValidation, cemcReco, JetKinematicCheck, FullJetFinder, analysis, jetrtrack, JetNconstituents, towerid, pi0Efficiency, caloTreeGen, readDigitalCurrents, JetSeedCount, hcal_towerid, TruthJetTagging, pythiaEMCalAna, caloTreeGen, pi0ClusterAna, quickHIJING, singlePhotonClusterAna, hijbkg_upc, isoCluster, HCalJetPhiShift, JetUnderlyingEvent, jetHistogrammer, JetMultSub, UEvsEtaCentrality, TracksInJets, Pi0MassAnalysis, SynRadAna, mbdAnalysis, mbdAnalysis, PHTruthSiliconAssociation, ParticleFlowReco, TrackClusterEvaluator, OnCal, TemplateCreation, Emcal_Tower_Masking, g4hitshift, and PHG4PileupGenerator.
Definition at line 56 of file SubsysReco.h.
View newest version in sPHENIX GitHub at line 56 of file SubsysReco.h
Referenced by PHG4PileupGenerator::Reset().
virtual int SubsysReco::ResetEvent (PHCompositeNode *) inline virtual
Clean up after each event.
Reimplemented in EMJetVal, dNdEtaINTT, JetValidation, PHActsTrkFitter, cemcReco, PHActsInitialVertexFinder, PHCosmicsTrkFitter, JetKinematicCheck, FullJetFinder, JetBkgdSub, PHG4Reco, analysis, jetrtrack, JetNconstituents, towerid, pi0Efficiency, caloTreeGen, readDigitalCurrents, PHActsVertexFinder, JetSeedCount, hcal_towerid, TruthJetTagging, TpcPrototypeUnpacker, pythiaEMCalAna, JetMultSub, caloTreeGen, PHActsToSvtxTracks, pi0ClusterAna, quickHIJING, singlePhotonClusterAna, TPCFEETestRecov1, hijbkg_upc, isoCluster, IsolatedTrackAnalysis, HCalJetPhiShift, JetUnderlyingEvent, jetHistogrammer, PHActsVertexFitter, UEvsEtaCentrality, TracksInJets, Pi0MassAnalysis, SynRadAna, mbdAnalysis, mbdAnalysis, PHTruthSiliconAssociation, PHG4TruthSubsystem, MinimumBiasClassifier, PHG4FullProjSpacalCellReco, OnCal, ParticleFlowReco, TrackClusterEvaluator, CentralityReco, PHTrackClusterAssociator, PHG4CylinderCellReco, PHG4BlockCellReco, PHG4EPDModuleReco, PHPythia6, HCalCalibTree, TracksInJets, PHSartre, EventCombiner, PHSiliconSeedMerger, SvtxTruthRecoTableEval, TemplateCreation, PHPythia6, Emcal_Tower_Masking, g4hitshift, and PHG4PileupGenerator.
Definition at line 59 of file SubsysReco.h.
View newest version in sPHENIX GitHub at line 59 of file SubsysReco.h
Referenced by PHG4PileupGenerator::ResetEvent().
The documentation for this class was generated from the following file:
coresoftware/blob/master/offline/framework/fun4all/SubsysReco.h