Analysis Software: TpcPrototypeUnpacker Class Reference
TpcPrototypeUnpacker Class Reference
#include <prototype/blob/master/offline/packages/tpc2019/TpcPrototypeUnpacker.h>
Classes
class ChannelHeader
simple channel header class for ROOT file IO
class ClusterData
buffer for a cluster's data
class EventHeader
simple event header class for ROOT file IO
class PadPlaneData
buffer for full event data
Public Member Functions
TpcPrototypeUnpacker (const std::string &outputfilename="TpcPrototypeUnpacker.root")
virtual ~TpcPrototypeUnpacker ()
int Init (PHCompositeNode *topNode)
int InitRun (PHCompositeNode *topNode)
int process_event (PHCompositeNode *topNode)
int ResetEvent (PHCompositeNode *topNode)
Clean up after each event.
int End (PHCompositeNode *topNode)
Called at the end of all processing.
void setClusteringZeroSuppression (int threshold)
void setNPostSample (int nPostSample)
void setNPreSample (int nPreSample)
void registerPadPlane (PHG4TpcPadPlane *padplane)
void setEnableClustering (bool b)
Public Member Functions inherited from SubsysReco
~SubsysReco () override
virtual int EndRun (const int)
Called at the end of each run.
virtual int Reset (PHCompositeNode *)
Reset.
void Print (const std::string &="ALL") const override
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Private Member Functions
int exportDSTCluster (ClusterData &cluster, const int i)
ClusterData &cluster -> DST / TrkrClusterContainer.
int exportDSTHits ()
PadPlaneData m_padPlaneData -> DST / TrkrHitSetContainer.
int InitField (PHCompositeNode *topNode)
Fun4AllHistoManager * getHistoManager ()
int Clustering (void)
Clustering then prepare IOs.
Static Private Member Functions
static std::pair< int, int > roughZeroSuppression (std::vector< int > &data)
Private Attributes
PHG4TpcPadPlane * padplane
PHG4CylinderCellGeomContainer * tpcCylinderCellGeom
TrkrHitSetContainer * hitsetcontainer
TrkrClusterContainer * trkrclusters
std::string m_outputFileName
TTree * m_eventT
EventHeader m_eventHeader
EventHeader * m_peventHeader
int m_nClusters
->m_eventHeader, for filling TTree
TClonesArray * m_IOClusters
TTree * m_chanT
ChannelHeader m_chanHeader
ChannelHeader * m_pchanHeader
std::vector< uint32_t > m_chanData
->m_chanHeader, for filling TTree
PadPlaneData m_padPlaneData
std::map< int, ClusterData > m_clusters
bool enableClustering
int m_clusteringZeroSuppression
int m_nPreSample
int m_nPostSample
int m_XRayLocationX
int m_XRayLocationY
TpcPrototypeDefs::FEEv2::SampleFit_PowerLawDoubleExp_PDFMaker * m_pdfMaker
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = std::numeric_limits<int>::max() - 10
}
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Detailed Description
Definition at line 40 of file TpcPrototypeUnpacker.h.
View newest version in sPHENIX GitHub at line 40 of file TpcPrototypeUnpacker.h
Constructor & Destructor Documentation
TpcPrototypeUnpacker::TpcPrototypeUnpacker (const std::string & outputfilename = "TpcPrototypeUnpacker.root")
Definition at line 83 of file TpcPrototypeUnpacker.cc.
View newest version in sPHENIX GitHub at line 83 of file TpcPrototypeUnpacker.cc
TpcPrototypeUnpacker::~TpcPrototypeUnpacker () virtual
Definition at line 107 of file TpcPrototypeUnpacker.cc.
View newest version in sPHENIX GitHub at line 107 of file TpcPrototypeUnpacker.cc
References m_IOClusters, m_pdfMaker, and padplane.
Member Function Documentation
int TpcPrototypeUnpacker::Clustering (void) private
Clustering then prepare IOs.
Definition at line 630 of file TpcPrototypeUnpacker.cc.
View newest version in sPHENIX GitHub at line 630 of file TpcPrototypeUnpacker.cc
References assert, TpcPrototypeUnpacker::ClusterData::avg_pad_azimuth, TpcPrototypeUnpacker::ClusterData::avg_pad_radial, TpcPrototypeUnpacker::ClusterData::clusterID, TpcPrototypeUnpacker::PadPlaneData::Clustering(), TpcPrototypeUnpacker::EventHeader::event, Fun4AllReturnCodes::EVENT_OK, exportDSTCluster(), material_mapping_optimisation::format, TpcPrototypeUnpacker::PadPlaneData::getGroups(), TpcPrototypeUnpacker::PadPlaneData::getPad(), i, TpcPrototypeUnpacker::PadPlaneData::IsValidPad(), TPCDaqDefs::FEEv1::kMaxPadY, TPCDaqDefs::FEEv1::kSAMPLE_LENGTH, m_clusteringZeroSuppression, m_clusters, m_eventHeader, m_IOClusters, m_nClusters, m_nPostSample, m_nPreSample, m_padPlaneData, m_pdfMaker, TpcPrototypeDefs::FEEv2::SampleFit_PowerLawDoubleExp_PDFMaker::MakeSectionPage(), TpcPrototypeUnpacker::ClusterData::max_pad_azimuth, TpcPrototypeUnpacker::ClusterData::max_sample, Acts::UnitConstants::min, TpcPrototypeUnpacker::ClusterData::min_pad_azimuth, TpcPrototypeUnpacker::ClusterData::min_sample, TpcPrototypeUnpacker::ClusterData::pad_azimuth_peaks, TpcPrototypeUnpacker::ClusterData::pad_azimuth_samples, TpcPrototypeUnpacker::ClusterData::pad_azimuths, TpcPrototypeUnpacker::ClusterData::pad_radial_samples, TpcPrototypeUnpacker::ClusterData::pad_radials, TpcPrototypeUnpacker::ClusterData::peak, TpcPrototypeUnpacker::ClusterData::peak_sample, TpcPrototypeUnpacker::ClusterData::pedstal, PROTOTYPE4_FEM::SampleFit_PowerLawDoubleExp(), TpcPrototypeUnpacker::ClusterData::samples, TpcPrototypeUnpacker::ClusterData::size_pad_azimuth, TpcPrototypeUnpacker::ClusterData::size_pad_radial, str, TpcPrototypeUnpacker::ClusterData::sum_samples, Fun4AllBase::Verbosity(), and Fun4AllBase::VERBOSITY_SOME.
Referenced by process_event().
int TpcPrototypeUnpacker::End (PHCompositeNode *) virtual
Called at the end of all processing.
Reimplemented from SubsysReco.
Definition at line 332 of file TpcPrototypeUnpacker.cc.
View newest version in sPHENIX GitHub at line 332 of file TpcPrototypeUnpacker.cc
References assert, PHTFileServer::cd(), Fun4AllReturnCodes::EVENT_OK, PHTFileServer::get(), Fun4AllHistoManager::getHisto(), getHistoManager(), i, m_chanT, m_eventT, m_outputFileName, m_pdfMaker, Fun4AllHistoManager::nHistos(), Fun4AllBase::Verbosity(), and Fun4AllBase::VERBOSITY_SOME.
int TpcPrototypeUnpacker::exportDSTCluster (ClusterData & cluster, const int i) private
ClusterData &cluster -> DST / TrkrClusterContainer.
Definition at line 803 of file TpcPrototypeUnpacker.cc.
View newest version in sPHENIX GitHub at line 803 of file TpcPrototypeUnpacker.cc
References Fun4AllReturnCodes::ABORTEVENT, assert, TpcPrototypeUnpacker::ClusterData::avg_pad_azimuth, TpcPrototypeUnpacker::ClusterData::avg_pad_radial, TpcPrototypeUnpacker::ClusterData::avg_pos_x, TpcPrototypeUnpacker::ClusterData::avg_pos_y, TpcPrototypeUnpacker::ClusterData::avg_pos_z, TpcPrototypeUnpacker::ClusterData::delta_azimuth_bin, TpcPrototypeUnpacker::ClusterData::delta_z, Acts::UnitConstants::e, Jetscape::ERR, Fun4AllReturnCodes::EVENT_OK, TrkrClusterContainer::findCluster(), TpcDefs::genClusKey(), TpcDefs::genHitSetKey(), PHG4CylinderCellGeom::get_phibins(), PHG4CylinderCellGeom::get_phicenter(), PHG4CylinderCellGeom::get_radius(), PHG4CylinderCellGeom::get_zbins(), PHG4CylinderCellGeom::get_zcenter(), PHG4CylinderCellGeomContainer::GetLayerCellGeom(), TpcPrototypeCluster::getPosition(), TrkrCluster::identify(), TpcPrototypeCluster::identify(), TPCDaqDefs::FEEv1::kMaxPadX, layer, TpcPrototypeUnpacker::ClusterData::max_pad_azimuth, TpcPrototypeUnpacker::ClusterData::max_sample, TpcPrototypeUnpacker::ClusterData::min_pad_azimuth, TpcPrototypeUnpacker::ClusterData::min_sample, TpcPrototypeUnpacker::ClusterData::pad_azimuth_peaks, TpcPrototypeUnpacker::ClusterData::pad_azimuth_samples, TpcPrototypeUnpacker::ClusterData::pad_azimuths, TpcPrototypeUnpacker::ClusterData::pad_radial_samples, TpcPrototypeUnpacker::ClusterData::pad_radials, TpcPrototypeUnpacker::ClusterData::peak, TpcPrototypeUnpacker::ClusterData::peak_sample, TpcPrototypeUnpacker::ClusterData::pedstal, TpcPrototypeUnpacker::ClusterData::samples, TpcPrototypeCluster::setAdc(), TpcPrototypeCluster::setAvgPadAzimuth(), TpcPrototypeCluster::setAvgPadRadial(), TpcPrototypeCluster::setClusKey(), TpcPrototypeCluster::setDeltaAzimuthBin(), TpcPrototypeCluster::setDeltaZ(), TpcPrototypeCluster::setError(), TpcPrototypeCluster::setGlobal(), TpcPrototypeCluster::setMaxPadAzimuth(), TpcPrototypeCluster::setMaxSample(), TpcPrototypeCluster::setMinPadAzimuth(), TpcPrototypeCluster::setMinSample(), TpcPrototypeCluster::setPadAzimuthPeaks(), TpcPrototypeCluster::setPadAzimuths(), TpcPrototypeCluster::setPadAzimuthSamples(), TpcPrototypeCluster::setPadRadials(), TpcPrototypeCluster::setPadRadialSamples(), TpcPrototypeCluster::setPeak(), TpcPrototypeCluster::setPeakSample(), TpcPrototypeCluster::setPedstal(), TpcPrototypeCluster::setPosition(), TpcPrototypeCluster::setSamples(), TpcPrototypeCluster::setSize(), TpcPrototypeCluster::setSizePadAzimuth(), TpcPrototypeCluster::setSizePadRadial(), TpcPrototypeCluster::setSumSamples(), TpcPrototypeUnpacker::ClusterData::size_pad_azimuth, TpcPrototypeUnpacker::ClusterData::size_pad_radial, TpcPrototypeUnpacker::ClusterData::sum_samples, tpcCylinderCellGeom, trkrclusters, and Fun4AllBase::Verbosity().
Referenced by Clustering().
int TpcPrototypeUnpacker::exportDSTHits () private
PadPlaneData m_padPlaneData -> DST / TrkrHitSetContainer.
Definition at line 578 of file TpcPrototypeUnpacker.cc.
View newest version in sPHENIX GitHub at line 578 of file TpcPrototypeUnpacker.cc
References assert, TrkrHitSetContainer::findOrAddHitSet(), TpcDefs::genHitKey(), TpcDefs::genHitSetKey(), TpcPrototypeUnpacker::PadPlaneData::getData(), hitsetcontainer, TPCDaqDefs::FEEv1::kMaxPadX, TPCDaqDefs::FEEv1::kMaxPadY, TPCDaqDefs::FEEv1::kSAMPLE_LENGTH, m_padPlaneData, and TrkrHit::setAdc().
Referenced by process_event().
Fun4AllHistoManager * TpcPrototypeUnpacker::getHistoManager () private
Definition at line 1177 of file TpcPrototypeUnpacker.cc.
View newest version in sPHENIX GitHub at line 1177 of file TpcPrototypeUnpacker.cc
References assert, Fun4AllServer::getHistoManager(), Fun4AllServer::instance(), and Fun4AllServer::registerHistoManager().
Referenced by End(), InitRun(), and process_event().
int TpcPrototypeUnpacker::Init (PHCompositeNode *) virtual
Called during initialization. Typically this is where you can book histograms, and e.g. register them to Fun4AllServer (so they can be output to file using Fun4AllServer::dumpHistos() method).
Reimplemented from SubsysReco.
Definition at line 175 of file TpcPrototypeUnpacker.cc.
View newest version in sPHENIX GitHub at line 175 of file TpcPrototypeUnpacker.cc
References Fun4AllReturnCodes::EVENT_OK, SubsysReco::Init(), and padplane.
int TpcPrototypeUnpacker::InitField (PHCompositeNode * topNode) private
Definition at line 1210 of file TpcPrototypeUnpacker.cc.
View newest version in sPHENIX GitHub at line 1210 of file TpcPrototypeUnpacker.cc
References assert, Fun4AllReturnCodes::EVENT_OK, PHFieldUtility::GetFieldMapNode(), and Fun4AllBase::Verbosity().
Referenced by InitRun().
int TpcPrototypeUnpacker::InitRun (PHCompositeNode *) virtual
Called for first event when run number is known. Typically this is where you may want to fetch data from database, because you know the run number.
Reimplemented from SubsysReco.
Definition at line 183 of file TpcPrototypeUnpacker.cc.
View newest version in sPHENIX GitHub at line 183 of file TpcPrototypeUnpacker.cc
References Fun4AllReturnCodes::ABORTRUN, PHCompositeNode::addNode(), assert, TpcPrototypeUnpacker::EventHeader::event, Fun4AllReturnCodes::EVENT_OK, PHNodeIterator::findFirst(), material_mapping_optimisation::format, PHTFileServer::get(), getHistoManager(), h, hitsetcontainer, i, InitField(), PHG4TpcPadPlane::InitRun(), TPCDaqDefs::FEEv1::kSAMPLE_LENGTH, m_chanData, m_chanT, m_eventHeader, m_eventT, m_IOClusters, m_nClusters, m_outputFileName, m_pchanHeader, m_pdfMaker, m_peventHeader, PHTFileServer::open(), padplane, PHWHERE, Fun4AllHistoManager::registerHisto(), str, tpcCylinderCellGeom, trkrclusters, Fun4AllBase::Verbosity(), and Fun4AllBase::VERBOSITY_SOME.
int TpcPrototypeUnpacker::process_event (PHCompositeNode *) virtual
Called for each event. This is where you do the real work.
Reimplemented from SubsysReco.
Definition at line 361 of file TpcPrototypeUnpacker.cc.
View newest version in sPHENIX GitHub at line 361 of file TpcPrototypeUnpacker.cc
References assert, BEGRUNEVENT, TpcPrototypeUnpacker::EventHeader::bx_counter, TpcPrototypeUnpacker::ChannelHeader::bx_counter, channel(), Clustering(), DATAEVENT, Fun4AllReturnCodes::DISCARDEVENT, Acts::UnitConstants::e, enableClustering, event, TpcPrototypeUnpacker::EventHeader::event, Fun4AllReturnCodes::EVENT_OK, exportDSTHits(), TpcPrototypeUnpacker::ChannelHeader::fee_channel, TpcPrototypeUnpacker::ChannelHeader::fee_id, material_mapping_optimisation::format, Fun4AllHistoManager::getHisto(), getHistoManager(), TpcPrototypeUnpacker::PadPlaneData::getPad(), TPCR2Map::Getphipos(), TPCR2Map::GetRpos(), i, TPCDaqDefs::FEEv1::kN_CHANNELS, TpcPrototypeDefs::FEEv2::kN_FEES, TPCDaqDefs::FEEv1::kPACKET_ID, TPCDaqDefs::FEEv1::kSAMPLE_LENGTH, m_chanData, m_chanHeader, m_chanT, m_eventHeader, m_eventT, m_padPlaneData, m_pdfMaker, TpcPrototypeDefs::FEEv2::SampleFit_PowerLawDoubleExp_PDFMaker::MakeSectionPage(), TpcPrototypeUnpacker::ChannelHeader::max, merge_hashes::p, TpcPrototypeUnpacker::ChannelHeader::packet_type, TpcPrototypeUnpacker::ChannelHeader::pad_x, TpcPrototypeUnpacker::ChannelHeader::pad_y, TpcPrototypeUnpacker::ChannelHeader::pedestal, roughZeroSuppression(), TpcPrototypeUnpacker::EventHeader::run, TpcPrototypeUnpacker::ChannelHeader::sampa_address, TpcPrototypeUnpacker::ChannelHeader::sampa_channel, TpcPrototypeUnpacker::ChannelHeader::size, str, t, TpcPrototypeDefs::FEEv2::TpcR2Map, Fun4AllBase::Verbosity(), Fun4AllBase::VERBOSITY_EVEN_MORE, Fun4AllBase::VERBOSITY_MORE, and Fun4AllBase::VERBOSITY_SOME.
void TpcPrototypeUnpacker::registerPadPlane (PHG4TpcPadPlane * padplane)
Definition at line 1198 of file TpcPrototypeUnpacker.cc.
View newest version in sPHENIX GitHub at line 1198 of file TpcPrototypeUnpacker.cc
References PHG4TpcPadPlane::Detector(), padplane, PHG4TpcPadPlane::UpdateInternalParameters(), and Fun4AllBase::Verbosity().
Referenced by Fun4All_TestBeam_TPC().
int TpcPrototypeUnpacker::ResetEvent (PHCompositeNode *) virtual
Clean up after each event.
Reimplemented from SubsysReco.
Definition at line 124 of file TpcPrototypeUnpacker.cc.
View newest version in sPHENIX GitHub at line 124 of file TpcPrototypeUnpacker.cc
References assert, Fun4AllReturnCodes::EVENT_OK, m_chanHeader, m_clusters, m_eventHeader, m_IOClusters, m_nClusters, m_padPlaneData, and TpcPrototypeUnpacker::PadPlaneData::Reset().
std::pair< int, int > TpcPrototypeUnpacker::roughZeroSuppression (std::vector< int > & data) static private
rough zero suppression by subtracting sample medium value
Returns
pair of pedestal and max
Definition at line 1060 of file TpcPrototypeUnpacker.cc.
View newest version in sPHENIX GitHub at line 1060 of file TpcPrototypeUnpacker.cc
References pedestal(), and Acts::Experimental::detail::BlueprintHelper::sort().
Referenced by process_event().
void TpcPrototypeUnpacker::setClusteringZeroSuppression (int threshold) inline
Definition at line 53 of file TpcPrototypeUnpacker.h.
View newest version in sPHENIX GitHub at line 53 of file TpcPrototypeUnpacker.h
References m_clusteringZeroSuppression.
void TpcPrototypeUnpacker::setEnableClustering (bool b) inline
Definition at line 70 of file TpcPrototypeUnpacker.h.
View newest version in sPHENIX GitHub at line 70 of file TpcPrototypeUnpacker.h
References KFPMath::b, and enableClustering.
void TpcPrototypeUnpacker::setNPostSample (int nPostSample) inline
Definition at line 58 of file TpcPrototypeUnpacker.h.
View newest version in sPHENIX GitHub at line 58 of file TpcPrototypeUnpacker.h
References m_nPostSample.
Referenced by Fun4All_TestBeam_TPC().
void TpcPrototypeUnpacker::setNPreSample (int nPreSample) inline
Definition at line 63 of file TpcPrototypeUnpacker.h.
View newest version in sPHENIX GitHub at line 63 of file TpcPrototypeUnpacker.h
References m_nPreSample.
Referenced by Fun4All_TestBeam_TPC().
Member Data Documentation
bool TpcPrototypeUnpacker::enableClustering private
Definition at line 302 of file TpcPrototypeUnpacker.h.
View newest version in sPHENIX GitHub at line 302 of file TpcPrototypeUnpacker.h
Referenced by process_event(), and setEnableClustering().
TrkrHitSetContainer* TpcPrototypeUnpacker::hitsetcontainer private
Definition at line 262 of file TpcPrototypeUnpacker.h.
View newest version in sPHENIX GitHub at line 262 of file TpcPrototypeUnpacker.h
Referenced by exportDSTHits(), and InitRun().
std::vector<uint32_t> TpcPrototypeUnpacker::m_chanData private
->m_chanHeader, for filling TTree
Definition at line 292 of file TpcPrototypeUnpacker.h.
View newest version in sPHENIX GitHub at line 292 of file TpcPrototypeUnpacker.h
Referenced by InitRun(), and process_event().
ChannelHeader TpcPrototypeUnpacker::m_chanHeader private
Definition at line 290 of file TpcPrototypeUnpacker.h.
View newest version in sPHENIX GitHub at line 290 of file TpcPrototypeUnpacker.h
Referenced by process_event(), and ResetEvent().
TTree* TpcPrototypeUnpacker::m_chanT private
Definition at line 288 of file TpcPrototypeUnpacker.h.
View newest version in sPHENIX GitHub at line 288 of file TpcPrototypeUnpacker.h
Referenced by End(), InitRun(), and process_event().
int TpcPrototypeUnpacker::m_clusteringZeroSuppression private
Definition at line 307 of file TpcPrototypeUnpacker.h.
View newest version in sPHENIX GitHub at line 307 of file TpcPrototypeUnpacker.h
Referenced by Clustering(), and setClusteringZeroSuppression().
std::map<int, ClusterData> TpcPrototypeUnpacker::m_clusters private
Definition at line 296 of file TpcPrototypeUnpacker.h.
View newest version in sPHENIX GitHub at line 296 of file TpcPrototypeUnpacker.h
Referenced by Clustering(), and ResetEvent().
EventHeader TpcPrototypeUnpacker::m_eventHeader private
Definition at line 282 of file TpcPrototypeUnpacker.h.
View newest version in sPHENIX GitHub at line 282 of file TpcPrototypeUnpacker.h
Referenced by Clustering(), InitRun(), process_event(), and ResetEvent().
TTree* TpcPrototypeUnpacker::m_eventT private
Definition at line 280 of file TpcPrototypeUnpacker.h.
View newest version in sPHENIX GitHub at line 280 of file TpcPrototypeUnpacker.h
Referenced by End(), InitRun(), and process_event().
TClonesArray* TpcPrototypeUnpacker::m_IOClusters private
Definition at line 286 of file TpcPrototypeUnpacker.h.
View newest version in sPHENIX GitHub at line 286 of file TpcPrototypeUnpacker.h
Referenced by Clustering(), InitRun(), ResetEvent(), and ~TpcPrototypeUnpacker().
int TpcPrototypeUnpacker::m_nClusters private
->m_eventHeader, for filling TTree
Definition at line 285 of file TpcPrototypeUnpacker.h.
View newest version in sPHENIX GitHub at line 285 of file TpcPrototypeUnpacker.h
Referenced by Clustering(), InitRun(), and ResetEvent().
int TpcPrototypeUnpacker::m_nPostSample private
Definition at line 309 of file TpcPrototypeUnpacker.h.
View newest version in sPHENIX GitHub at line 309 of file TpcPrototypeUnpacker.h
Referenced by Clustering(), and setNPostSample().
int TpcPrototypeUnpacker::m_nPreSample private
Definition at line 308 of file TpcPrototypeUnpacker.h.
View newest version in sPHENIX GitHub at line 308 of file TpcPrototypeUnpacker.h
Referenced by Clustering(), and setNPreSample().
std::string TpcPrototypeUnpacker::m_outputFileName private
Definition at line 278 of file TpcPrototypeUnpacker.h.
View newest version in sPHENIX GitHub at line 278 of file TpcPrototypeUnpacker.h
Referenced by End(), and InitRun().
PadPlaneData TpcPrototypeUnpacker::m_padPlaneData private
Definition at line 295 of file TpcPrototypeUnpacker.h.
View newest version in sPHENIX GitHub at line 295 of file TpcPrototypeUnpacker.h
Referenced by Clustering(), exportDSTHits(), process_event(), and ResetEvent().
ChannelHeader* TpcPrototypeUnpacker::m_pchanHeader private
Definition at line 291 of file TpcPrototypeUnpacker.h.
View newest version in sPHENIX GitHub at line 291 of file TpcPrototypeUnpacker.h
Referenced by InitRun().
TpcPrototypeDefs::FEEv2::SampleFit_PowerLawDoubleExp_PDFMaker* TpcPrototypeUnpacker::m_pdfMaker private
Definition at line 313 of file TpcPrototypeUnpacker.h.
View newest version in sPHENIX GitHub at line 313 of file TpcPrototypeUnpacker.h
Referenced by Clustering(), End(), InitRun(), process_event(), and ~TpcPrototypeUnpacker().
EventHeader* TpcPrototypeUnpacker::m_peventHeader private
Definition at line 283 of file TpcPrototypeUnpacker.h.
View newest version in sPHENIX GitHub at line 283 of file TpcPrototypeUnpacker.h
Referenced by InitRun().
int TpcPrototypeUnpacker::m_XRayLocationX private
Definition at line 310 of file TpcPrototypeUnpacker.h.
View newest version in sPHENIX GitHub at line 310 of file TpcPrototypeUnpacker.h
int TpcPrototypeUnpacker::m_XRayLocationY private
Definition at line 311 of file TpcPrototypeUnpacker.h.
View newest version in sPHENIX GitHub at line 311 of file TpcPrototypeUnpacker.h
PHG4TpcPadPlane* TpcPrototypeUnpacker::padplane private
Definition at line 260 of file TpcPrototypeUnpacker.h.
View newest version in sPHENIX GitHub at line 260 of file TpcPrototypeUnpacker.h
Referenced by Init(), InitRun(), registerPadPlane(), and ~TpcPrototypeUnpacker().
PHG4CylinderCellGeomContainer* TpcPrototypeUnpacker::tpcCylinderCellGeom private
Definition at line 261 of file TpcPrototypeUnpacker.h.
View newest version in sPHENIX GitHub at line 261 of file TpcPrototypeUnpacker.h
Referenced by exportDSTCluster(), and InitRun().
TrkrClusterContainer* TpcPrototypeUnpacker::trkrclusters private
Definition at line 263 of file TpcPrototypeUnpacker.h.
View newest version in sPHENIX GitHub at line 263 of file TpcPrototypeUnpacker.h
Referenced by exportDSTCluster(), and InitRun().
The documentation for this class was generated from the following files:
prototype/blob/master/offline/packages/tpc2019/TpcPrototypeUnpacker.h
prototype/blob/master/offline/packages/tpc2019/TpcPrototypeUnpacker.cc