Analysis Software: noiMsgTree Class Reference
noiMsgTree Class Reference
#include <analysis/blob/master/JS-Jet/FastJetMedianBkg/src_JetMedianTree/macro/loc_lib/noiMsgTree.h>
Public Member Functions
noiMsgTree (bool set_echo)
void msg (string msg)
void msg (vector< string > messages)
void dash ()
void write ()
void slurp_file (const char *which_file)
Static Public Member Functions
static void read_messages (const char *f_name)
Public Attributes
bool echo_to_cout {false}
tree
Private Attributes
string b_msg
TTree tree
Detailed Description
Definition at line 3 of file noiMsgTree.h.
View newest version in sPHENIX GitHub at line 3 of file noiMsgTree.h
Constructor & Destructor Documentation
noiMsgTree::noiMsgTree (bool set_echo) inline
Definition at line 9 of file noiMsgTree.h.
View newest version in sPHENIX GitHub at line 9 of file noiMsgTree.h
Member Function Documentation
void noiMsgTree::dash () inline
Definition at line 31 of file noiMsgTree.h.
View newest version in sPHENIX GitHub at line 31 of file noiMsgTree.h
References b_msg, echo_to_cout, and tree.
void noiMsgTree::msg (string msg) inline
Definition at line 19 of file noiMsgTree.h.
View newest version in sPHENIX GitHub at line 19 of file noiMsgTree.h
References b_msg, echo_to_cout, and tree.
Referenced by msg(), read_messages(), and slurp_file().
void noiMsgTree::msg (vector< string > messages) inline
Definition at line 24 of file noiMsgTree.h.
View newest version in sPHENIX GitHub at line 24 of file noiMsgTree.h
References b_msg, echo_to_cout, msg(), and tree.
static void noiMsgTree::read_messages (const char * f_name) inline static
Definition at line 39 of file noiMsgTree.h.
View newest version in sPHENIX GitHub at line 39 of file noiMsgTree.h
References msg().
void noiMsgTree::slurp_file (const char * which_file) inline
Definition at line 56 of file noiMsgTree.h.
View newest version in sPHENIX GitHub at line 56 of file noiMsgTree.h
References line, and msg().
void noiMsgTree::write () inline
Definition at line 36 of file noiMsgTree.h.
View newest version in sPHENIX GitHub at line 36 of file noiMsgTree.h
References tree.
Member Data Documentation
string noiMsgTree::b_msg private
Definition at line 5 of file noiMsgTree.h.
View newest version in sPHENIX GitHub at line 5 of file noiMsgTree.h
Referenced by dash(), and msg().
bool noiMsgTree::echo_to_cout {false}
Definition at line 8 of file noiMsgTree.h.
View newest version in sPHENIX GitHub at line 8 of file noiMsgTree.h
Referenced by dash(), and msg().
TTree noiMsgTree::tree private
Definition at line 6 of file noiMsgTree.h.
View newest version in sPHENIX GitHub at line 6 of file noiMsgTree.h
Referenced by dash(), msg(), and write().
noiMsgTree::tree
Initial value:
{"Messages", "Tree of messages"}
        {
            tree.Branch("messages", &b_msg);
            dash();
            msg(" Start of msg tree ");
            dash();
            echo_to_cout = set_echo;
        }
Definition at line 11 of file noiMsgTree.h.
View newest version in sPHENIX GitHub at line 11 of file noiMsgTree.h
The documentation for this class was generated from the following file:
analysis/blob/master/JS-Jet/FastJetMedianBkg/src_JetMedianTree/macro/loc_lib/noiMsgTree.h