Analysis Software: EoSs Class Reference
EoSs Class Reference
#include <JETSCAPE/blob/main/jail/vhlle/src/eos.h>
Public Member Functions
EoSs (std::string fname, int ncols)
~EoSs ()
virtual void eos (double e, double nb, double nq, double ns, double &T, double &mub, double &muq, double &mus, double &_p)
virtual double p (double e, double nb, double ns, double nq)
double p (double e)
double dpe (double e)
double t (double e)
double mu (double e)
virtual double cs2 (double e)
Public Member Functions inherited from EoS
virtual ~EoS ()
double s (double e, double nb, double nq, double ns)
double cs2 (void)
double cs (void)
Private Attributes
TGraph * gp
TGraph * gT
TGraph * gmu
Detailed Description
Definition at line 45 of file eos.h.
View newest version in sPHENIX GitHub at line 45 of file eos.h
Constructor & Destructor Documentation
EoSs::EoSs (std::string fname, int ncols)
Definition at line 28 of file eos.cpp.
View newest version in sPHENIX GitHub at line 28 of file eos.cpp
References Acts::UnitConstants::e, and in.
EoSs::~EoSs (void)
Definition at line 65 of file eos.cpp.
View newest version in sPHENIX GitHub at line 65 of file eos.cpp
Member Function Documentation
virtual double EoSs::cs2 (double e) inline virtual
Reimplemented from EoS.
Definition at line 68 of file eos.h.
View newest version in sPHENIX GitHub at line 68 of file eos.h
References dpe().
double EoSs::dpe (double e)
Definition at line 75 of file eos.cpp.
View newest version in sPHENIX GitHub at line 75 of file eos.cpp
Referenced by cs2().
virtual void EoSs::eos (double e, double nb, double nq, double ns, double & T, double & mub, double & muq, double & mus, double & _p) inline virtual
Implements EoS.
Definition at line 53 of file eos.h.
View newest version in sPHENIX GitHub at line 53 of file eos.h
References p(), and t().
double EoSs::mu (double e)
Definition at line 93 of file eos.cpp.
View newest version in sPHENIX GitHub at line 93 of file eos.cpp
virtual double EoSs::p (double e, double nb, double ns, double nq) inline virtual
Implements EoS.
Definition at line 59 of file eos.h.
View newest version in sPHENIX GitHub at line 59 of file eos.h
Referenced by eos().
double EoSs::p (double e)
Definition at line 67 of file eos.cpp.
View newest version in sPHENIX GitHub at line 67 of file eos.cpp
double EoSs::t (double e)
Definition at line 83 of file eos.cpp.
View newest version in sPHENIX GitHub at line 83 of file eos.cpp
References C_PI.
Referenced by eos().
Member Data Documentation
TGraph * EoSs::gmu private
Definition at line 47 of file eos.h.
View newest version in sPHENIX GitHub at line 47 of file eos.h
TGraph* EoSs::gp private
Definition at line 47 of file eos.h.
View newest version in sPHENIX GitHub at line 47 of file eos.h
TGraph * EoSs::gT private
Definition at line 47 of file eos.h.
View newest version in sPHENIX GitHub at line 47 of file eos.h
The documentation for this class was generated from the following files:
JETSCAPE/blob/main/jail/vhlle/src/eos.h
JETSCAPE/blob/main/jail/vhlle/src/eos.cpp