Analysis Software: InttMonDraw Class Reference
InttMonDraw Class Reference
#include <OnlMon/blob/main/subsystems/intt/InttMonDraw.h>
Classes
struct Option_s
Public Types
typedef void(* HeadFunc_t)(std::string const &)
typedef void(* GlobalHistsPrepFunc_t)(std::string const &, TH2D **)
typedef void(* LocalHistPrepFunc_t)(std::string const &, TH2D **, struct INTT::Indexes_s &)
typedef std::map< std::string,
struct Option_s > Options_t
Public Member Functions
InttMonDraw (std::string const &)
~InttMonDraw () override
int Init () override
int Draw (std::string const &="ALL") override
int MakeHtml (std::string const &="ALL") override
int SavePlot (std::string const &="ALL", std::string const &="png") override
Public Member Functions inherited from OnlMonDraw
OnlMonDraw (const std::string &name="NONE")
virtual ~OnlMonDraw ()
virtual int MakePS (const std::string &what="ALL")
const std::string Name () const
void Verbosity (const int i)
int Verbosity () const
Static Public Member Functions
static void GlobalChipLocalChannelHead (std::string const &)
static void DrawGlobalChipMap (std::string const &)
static void InttGlobalChipExec (const std::string &, int)
static void DrawLocalChannelMap (std::string const &, struct INTT::Indexes_s)
static void InttLocalChannelExec (const std::string &, int, int, int, int)
static void GlobalLadderLocalChipHead (std::string const &)
static void DrawGlobalLadderMap (std::string const &)
static void InttGlobalLadderExec (const std::string &, int)
static void DrawLocalChipMap (std::string const &, struct INTT::Indexes_s)
static void InttLocalChipExec (const std::string &, int, int, int)
static void PrepGlobalChipHists_Hitmap (std::string const &, TH2D **)
static void PrepLocalChannelHists_Hitmap (std::string const &, TH2D **, struct INTT::Indexes_s &)
static void PrepGlobalChipHists_NLL (std::string const &, TH2D **)
static void PrepGlobalLadderHists_Interface (std::string const &, TH2D **)
static void PrepLocalChipHists_Hitmap (std::string const &, TH2D **, struct INTT::Indexes_s &)
Static Public Attributes
static Options_t OPTIONS
Static Private Member Functions
static void DrawPad (TPad *, TPad *)
Private Attributes
OnlMonDB * dbvars = nullptr
Static Private Attributes
static constexpr double NUM_SIG = 2.0
static constexpr int CNVS_WIDTH = 1280
static constexpr int CNVS_HEIGHT = 720
static constexpr double T_MARGIN = 0.01
static constexpr double B_MARGIN = 0.01
static constexpr double L_MARGIN = 0.01
static constexpr double R_MARGIN = 0.08
static constexpr double TOP_FRAC = 0.05
static constexpr double DISP_FRAC = 0.1
static constexpr double DISP_TEXT_SIZE = 0.20
static constexpr double KEY_FRAC = 0.0
static constexpr double Y_LABEL_FRAC = 0.05
static constexpr double X_LABEL_FRAC = 0.15
static constexpr double Y_LABEL_TEXT_SIZE = 0.5
static constexpr double X_LABEL_TEXT_SIZE = 0.5
Additional Inherited Members
Protected Member Functions inherited from OnlMonDraw
virtual int DrawDeadServer (TPad *transparent)
Protected Attributes inherited from OnlMonDraw
std::string ThisName
int verbosity = 0
Detailed Description
Definition at line 34 of file InttMonDraw.h.
View newest version in sPHENIX GitHub at line 34 of file InttMonDraw.h
Member Typedef Documentation
typedef void(* InttMonDraw::GlobalHistsPrepFunc_t)(std::string const &, TH2D **)
Definition at line 46 of file InttMonDraw.h.
View newest version in sPHENIX GitHub at line 46 of file InttMonDraw.h
typedef void(* InttMonDraw::HeadFunc_t)(std::string const &)
Definition at line 45 of file InttMonDraw.h.
View newest version in sPHENIX GitHub at line 45 of file InttMonDraw.h
typedef void(* InttMonDraw::LocalHistPrepFunc_t)(std::string const &, TH2D **, struct INTT::Indexes_s &)
Definition at line 47 of file InttMonDraw.h.
View newest version in sPHENIX GitHub at line 47 of file InttMonDraw.h
typedef std::map<std::string, struct Option_s> InttMonDraw::Options_t
Definition at line 54 of file InttMonDraw.h.
View newest version in sPHENIX GitHub at line 54 of file InttMonDraw.h
Constructor & Destructor Documentation
InttMonDraw::InttMonDraw (std::string const & name)
Definition at line 34 of file InttMonDraw.cc.
View newest version in sPHENIX GitHub at line 34 of file InttMonDraw.cc
InttMonDraw::~InttMonDraw () override
Definition at line 40 of file InttMonDraw.cc.
View newest version in sPHENIX GitHub at line 40 of file InttMonDraw.cc
Member Function Documentation
int InttMonDraw::Draw (std::string const & what = "ALL") override virtual
Reimplemented from OnlMonDraw.
Definition at line 51 of file InttMonDraw.cc.
View newest version in sPHENIX GitHub at line 51 of file InttMonDraw.cc
References KFPMath::b, OPTIONS, and physmon_simulation::s.
Referenced by MakeHtml(), and SavePlot().
void InttMonDraw::DrawGlobalChipMap (std::string const & option) static
Definition at line 242 of file InttMonDraw.cc.
View newest version in sPHENIX GitHub at line 242 of file InttMonDraw.cc
References INTT::ARM, B_MARGIN, INTT::CHIP, INTT::CHIP_OFFSET, CNVS_HEIGHT, CNVS_WIDTH, DISP_FRAC, DISP_TEXT_SIZE, DrawPad(), i, OnlMonClient::instance(), KEY_FRAC, L_MARGIN, CKF_timing_vs_mu::label, INTT::LADDER, INTT::LAYER, INTT::LAYER_OFFSET, line, INTT::Indexes_s::lyr, perf_headwind::name, OPTIONS, R_MARGIN, OnlMonClient::RunNumber(), T_MARGIN, Acts::Test::time, TOP_FRAC, X_LABEL_FRAC, X_LABEL_TEXT_SIZE, Y_LABEL_FRAC, and Y_LABEL_TEXT_SIZE.
Referenced by GlobalChipLocalChannelHead().
void InttMonDraw::DrawGlobalLadderMap (std::string const & option) static
Definition at line 739 of file InttMonDraw.cc.
View newest version in sPHENIX GitHub at line 739 of file InttMonDraw.cc
References INTT::ARM, B_MARGIN, CNVS_HEIGHT, CNVS_WIDTH, DISP_FRAC, DISP_TEXT_SIZE, DrawPad(), i, OnlMonClient::instance(), KEY_FRAC, L_MARGIN, CKF_timing_vs_mu::label, INTT::LADDER, INTT::LAYER, INTT::LAYER_OFFSET, line, INTT::Indexes_s::lyr, perf_headwind::name, OPTIONS, R_MARGIN, OnlMonClient::RunNumber(), T_MARGIN, Acts::Test::time, TOP_FRAC, X_LABEL_FRAC, X_LABEL_TEXT_SIZE, Y_LABEL_FRAC, and Y_LABEL_TEXT_SIZE.
Referenced by GlobalLadderLocalChipHead().
void InttMonDraw::DrawLocalChannelMap (std::string const & option, struct INTT::Indexes_s indexes) static
Definition at line 544 of file InttMonDraw.cc.
View newest version in sPHENIX GitHub at line 544 of file InttMonDraw.cc
References INTT::ADC, INTT::Indexes_s::arm, B_MARGIN, INTT::CHANNEL, INTT::Indexes_s::chp, CNVS_HEIGHT, CNVS_WIDTH, DISP_FRAC, DISP_TEXT_SIZE, DrawPad(), i, L_MARGIN, INTT::Indexes_s::ldr, line, INTT::Indexes_s::lyr, perf_headwind::name, OPTIONS, R_MARGIN, and T_MARGIN.
Referenced by InttGlobalChipExec().
void InttMonDraw::DrawLocalChipMap (std::string const & option, struct INTT::Indexes_s indexes) static
Definition at line 1039 of file InttMonDraw.cc.
View newest version in sPHENIX GitHub at line 1039 of file InttMonDraw.cc
References INTT::Indexes_s::arm, B_MARGIN, INTT::CHANNEL, INTT::CHIP, INTT::CHIP_OFFSET, INTT::Indexes_s::chp, CNVS_HEIGHT, CNVS_WIDTH, DISP_FRAC, DISP_TEXT_SIZE, DrawPad(), i, L_MARGIN, INTT::Indexes_s::ldr, line, INTT::Indexes_s::lyr, perf_headwind::name, OPTIONS, R_MARGIN, and T_MARGIN.
Referenced by InttGlobalLadderExec().
void InttMonDraw::DrawPad (TPad * base, TPad * pad) static private
Definition at line 222 of file InttMonDraw.cc.
View newest version in sPHENIX GitHub at line 222 of file InttMonDraw.cc
References B_MARGIN, L_MARGIN, R_MARGIN, and T_MARGIN.
Referenced by DrawGlobalChipMap(), DrawGlobalLadderMap(), DrawLocalChannelMap(), and DrawLocalChipMap().
void InttMonDraw::GlobalChipLocalChannelHead (std::string const & option) static
Definition at line 237 of file InttMonDraw.cc.
View newest version in sPHENIX GitHub at line 237 of file InttMonDraw.cc
References DrawGlobalChipMap().
void InttMonDraw::GlobalLadderLocalChipHead (std::string const & option) static
Definition at line 734 of file InttMonDraw.cc.
View newest version in sPHENIX GitHub at line 734 of file InttMonDraw.cc
References DrawGlobalLadderMap().
int InttMonDraw::Init () override virtual
Reimplemented from OnlMonDraw.
Definition at line 46 of file InttMonDraw.cc.
View newest version in sPHENIX GitHub at line 46 of file InttMonDraw.cc
void InttMonDraw::InttGlobalChipExec (const std::string & option, int layer) static
Definition at line 515 of file InttMonDraw.cc.
View newest version in sPHENIX GitHub at line 515 of file InttMonDraw.cc
References INTT::Indexes_s::arm, INTT::CHIP, INTT::CHIP_OFFSET, INTT::Indexes_s::chp, DrawLocalChannelMap(), INTT::GetIndexesFromGlobalChipBinXY(), INTT::LADDER, layer, INTT::LAYER_OFFSET, INTT::Indexes_s::ldr, INTT::Indexes_s::lyr, and perf_headwind::name.
void InttMonDraw::InttGlobalLadderExec (const std::string & option, int layer) static
Definition at line 1010 of file InttMonDraw.cc.
View newest version in sPHENIX GitHub at line 1010 of file InttMonDraw.cc
References INTT::ARM, INTT::Indexes_s::arm, DrawLocalChipMap(), INTT::GetIndexesFromGlobalLadderBinXY(), INTT::LADDER, layer, INTT::LAYER_OFFSET, INTT::Indexes_s::ldr, INTT::Indexes_s::lyr, and perf_headwind::name.
void InttMonDraw::InttLocalChannelExec (const std::string & option, int layer, int ladder, int northsouth, int chip) static
Definition at line 705 of file InttMonDraw.cc.
View newest version in sPHENIX GitHub at line 705 of file InttMonDraw.cc
References INTT::ADC, INTT::Indexes_s::adc, INTT::Indexes_s::arm, INTT::CHANNEL, INTT::Indexes_s::chn, INTT::Indexes_s::chp, INTT::GetIndexesFromLocalChannelBinXY(), layer, INTT::Indexes_s::ldr, INTT::Indexes_s::lyr, and perf_headwind::name.
void InttMonDraw::InttLocalChipExec (const std::string & option, int layer, int ladder, int arm) static
Definition at line 1200 of file InttMonDraw.cc.
View newest version in sPHENIX GitHub at line 1200 of file InttMonDraw.cc
References INTT::Indexes_s::arm, INTT::CHANNEL, INTT::CHIP, INTT::CHIP_OFFSET, INTT::Indexes_s::chn, INTT::Indexes_s::chp, INTT::GetIndexesFromLocalChipBinXY(), layer, INTT::Indexes_s::ldr, INTT::Indexes_s::lyr, and perf_headwind::name.
int InttMonDraw::MakeHtml (std::string const & what = "ALL") override virtual
Reimplemented from OnlMonDraw.
Definition at line 90 of file InttMonDraw.cc.
View newest version in sPHENIX GitHub at line 90 of file InttMonDraw.cc
References KFPMath::b, OnlMonClient::CanvasToPng(), Draw(), OnlMonClient::htmlRegisterPage(), OnlMonClient::instance(), perf_headwind::name, OPTIONS, OnlMonClient::RunNumber(), physmon_simulation::s, and OnlMonClient::SaveLogFile().
void InttMonDraw::PrepGlobalChipHists_Hitmap (std::string const & option, TH2D ** client_hists) static
Definition at line 1231 of file InttMonDraw.cc.
View newest version in sPHENIX GitHub at line 1231 of file InttMonDraw.cc
References INTT::ADC, INTT::Indexes_s::adc, INTT::Indexes_s::arm, INTT_Felix::Ladder_s::barrel, INTT::CHANNEL, INTT::CHIP, INTT::Indexes_s::chn, INTT::Indexes_s::chp, INTT::FELIX, INTT::FELIX_CHANNEL, INTT_Felix::FelixMap(), INTT::GetFelixBinFromIndexes(), INTT::GetGlobalChipBinXYFromIndexes(), OnlMonClient::instance(), INTT_Felix::Ladder_s::ladder, INTT::LADDER, INTT_Felix::Ladder_s::layer, INTT::LAYER, INTT::Indexes_s::ldr, INTT::Indexes_s::lyr, Acts::UnitConstants::min, and perf_headwind::name.
void InttMonDraw::PrepGlobalChipHists_NLL (std::string const & option, TH2D ** client_hists) static
Definition at line 1439 of file InttMonDraw.cc.
View newest version in sPHENIX GitHub at line 1439 of file InttMonDraw.cc
References INTT::ADC, INTT::Indexes_s::adc, INTT::Indexes_s::arm, INTT_Felix::Ladder_s::barrel, INTT::CHANNEL, INTT::CHANNELS, INTT::CHIP, INTT::Indexes_s::chn, INTT::Indexes_s::chp, INTT::FELIX, INTT::FELIX_CHANNEL, INTT_Felix::FelixMap(), INTT::GetFelixBinFromIndexes(), INTT::GetGlobalChipBinXYFromIndexes(), OnlMonClient::getHisto(), OnlMonClient::instance(), INTT_Felix::Ladder_s::ladder, INTT::LADDER, INTT_Felix::Ladder_s::layer, INTT::LAYER, INTT::Indexes_s::ldr, INTT::Indexes_s::lyr, Acts::UnitConstants::min, and perf_headwind::name.
void InttMonDraw::PrepGlobalLadderHists_Interface (std::string const & option, TH2D ** client_hists) static
Definition at line 1603 of file InttMonDraw.cc.
View newest version in sPHENIX GitHub at line 1603 of file InttMonDraw.cc
References INTT::ARM, INTT::LADDER, INTT::LAYER, INTT::Indexes_s::lyr, n, and perf_headwind::name.
void InttMonDraw::PrepLocalChannelHists_Hitmap (std::string const & option, TH2D ** client_hists, struct INTT::Indexes_s & indexes) static
Definition at line 1350 of file InttMonDraw.cc.
View newest version in sPHENIX GitHub at line 1350 of file InttMonDraw.cc
References INTT::ADC, INTT::Indexes_s::adc, INTT::Indexes_s::arm, INTT_Felix::Ladder_s::barrel, INTT::CHANNEL, INTT::Indexes_s::chn, INTT::Indexes_s::chp, INTT::FELIX, INTT::FELIX_CHANNEL, INTT_Felix::FelixMap(), INTT::GetFelixBinFromIndexes(), OnlMonClient::getHisto(), INTT::GetLocalChannelBinXYFromIndexes(), OnlMonClient::instance(), INTT_Felix::Ladder_s::ladder, INTT_Felix::Ladder_s::layer, INTT::Indexes_s::ldr, INTT::Indexes_s::lyr, and perf_headwind::name.
void InttMonDraw::PrepLocalChipHists_Hitmap (std::string const & option, TH2D ** client_hists, struct INTT::Indexes_s & indexes) static
Definition at line 1647 of file InttMonDraw.cc.
View newest version in sPHENIX GitHub at line 1647 of file InttMonDraw.cc
References INTT::ADC, INTT::Indexes_s::adc, INTT::Indexes_s::arm, INTT_Felix::Ladder_s::barrel, INTT::CHANNEL, INTT::CHIP, INTT::Indexes_s::chn, INTT::Indexes_s::chp, INTT::FELIX, INTT::FELIX_CHANNEL, INTT_Felix::FelixMap(), INTT::GetFelixBinFromIndexes(), OnlMonClient::getHisto(), INTT::GetLocalChipBinXYFromIndexes(), OnlMonClient::instance(), INTT_Felix::Ladder_s::ladder, INTT_Felix::Ladder_s::layer, INTT::Indexes_s::ldr, INTT::Indexes_s::lyr, and perf_headwind::name.
int InttMonDraw::SavePlot (std::string const & what = "ALL", std::string const & type = "png") override virtual
Reimplemented from OnlMonDraw.
Definition at line 164 of file InttMonDraw.cc.
View newest version in sPHENIX GitHub at line 164 of file InttMonDraw.cc
References KFPMath::b, OnlMonClient::CanvasToPng(), Draw(), filename, OnlMonClient::instance(), perf_headwind::name, OPTIONS, OnlMonClient::RunNumber(), physmon_simulation::s, OnlMonDraw::ThisName, and parse_cmake_options::type.
Member Data Documentation
constexpr double InttMonDraw::B_MARGIN = 0.01 static private
Definition at line 90 of file InttMonDraw.h.
View newest version in sPHENIX GitHub at line 90 of file InttMonDraw.h
Referenced by DrawGlobalChipMap(), DrawGlobalLadderMap(), DrawLocalChannelMap(), DrawLocalChipMap(), and DrawPad().
constexpr int InttMonDraw::CNVS_HEIGHT = 720 static private
Definition at line 87 of file InttMonDraw.h.
View newest version in sPHENIX GitHub at line 87 of file InttMonDraw.h
Referenced by DrawGlobalChipMap(), DrawGlobalLadderMap(), DrawLocalChannelMap(), and DrawLocalChipMap().
constexpr int InttMonDraw::CNVS_WIDTH = 1280 static private
Definition at line 86 of file InttMonDraw.h.
View newest version in sPHENIX GitHub at line 86 of file InttMonDraw.h
Referenced by DrawGlobalChipMap(), DrawGlobalLadderMap(), DrawLocalChannelMap(), and DrawLocalChipMap().
OnlMonDB* InttMonDraw::dbvars = nullptr private
Definition at line 81 of file InttMonDraw.h.
View newest version in sPHENIX GitHub at line 81 of file InttMonDraw.h
constexpr double InttMonDraw::DISP_FRAC = 0.1 static private
Definition at line 95 of file InttMonDraw.h.
View newest version in sPHENIX GitHub at line 95 of file InttMonDraw.h
Referenced by DrawGlobalChipMap(), DrawGlobalLadderMap(), DrawLocalChannelMap(), and DrawLocalChipMap().
constexpr double InttMonDraw::DISP_TEXT_SIZE = 0.20 static private
Definition at line 96 of file InttMonDraw.h.
View newest version in sPHENIX GitHub at line 96 of file InttMonDraw.h
Referenced by DrawGlobalChipMap(), DrawGlobalLadderMap(), DrawLocalChannelMap(), and DrawLocalChipMap().
constexpr double InttMonDraw::KEY_FRAC = 0.0 static private
Definition at line 98 of file InttMonDraw.h.
View newest version in sPHENIX GitHub at line 98 of file InttMonDraw.h
Referenced by DrawGlobalChipMap(), and DrawGlobalLadderMap().
constexpr double InttMonDraw::L_MARGIN = 0.01 static private
Definition at line 91 of file InttMonDraw.h.
View newest version in sPHENIX GitHub at line 91 of file InttMonDraw.h
Referenced by DrawGlobalChipMap(), DrawGlobalLadderMap(), DrawLocalChannelMap(), DrawLocalChipMap(), and DrawPad().
constexpr double InttMonDraw::NUM_SIG = 2.0 static private
Definition at line 84 of file InttMonDraw.h.
View newest version in sPHENIX GitHub at line 84 of file InttMonDraw.h
InttMonDraw::Options_t InttMonDraw::OPTIONS static
Initial value:
=
{
        {"chip_hitmap",         (struct Option_s)
                {
                        .head =         &InttMonDraw::GlobalChipLocalChannelHead,
                        .global =       &InttMonDraw::PrepGlobalChipHists_Hitmap,
                        .local =        &InttMonDraw::PrepLocalChannelHists_Hitmap
                }
        },
        {"chip_nll",            (struct Option_s)
                {
                        .head =         &InttMonDraw::GlobalChipLocalChannelHead,
                        .global =       &InttMonDraw::PrepGlobalChipHists_NLL,
                        .local =        &InttMonDraw::PrepLocalChannelHists_Hitmap
                }
        },
        {"ladder_hitmap",               (struct Option_s)
                {
                        .head =         &InttMonDraw::GlobalLadderLocalChipHead,
                        .global =       &InttMonDraw::PrepGlobalLadderHists_Interface,
                        .local =        &InttMonDraw::PrepLocalChipHists_Hitmap
                }
        },
}
Definition at line 55 of file InttMonDraw.h.
View newest version in sPHENIX GitHub at line 55 of file InttMonDraw.h
Referenced by Draw(), DrawGlobalChipMap(), DrawGlobalLadderMap(), DrawLocalChannelMap(), DrawLocalChipMap(), MakeHtml(), and SavePlot().
constexpr double InttMonDraw::R_MARGIN = 0.08 static private
Definition at line 92 of file InttMonDraw.h.
View newest version in sPHENIX GitHub at line 92 of file InttMonDraw.h
Referenced by DrawGlobalChipMap(), DrawGlobalLadderMap(), DrawLocalChannelMap(), DrawLocalChipMap(), and DrawPad().
constexpr double InttMonDraw::T_MARGIN = 0.01 static private
Definition at line 89 of file InttMonDraw.h.
View newest version in sPHENIX GitHub at line 89 of file InttMonDraw.h
Referenced by DrawGlobalChipMap(), DrawGlobalLadderMap(), DrawLocalChannelMap(), DrawLocalChipMap(), and DrawPad().
constexpr double InttMonDraw::TOP_FRAC = 0.05 static private
Definition at line 94 of file InttMonDraw.h.
View newest version in sPHENIX GitHub at line 94 of file InttMonDraw.h
Referenced by DrawGlobalChipMap(), and DrawGlobalLadderMap().
constexpr double InttMonDraw::X_LABEL_FRAC = 0.15 static private
Definition at line 100 of file InttMonDraw.h.
View newest version in sPHENIX GitHub at line 100 of file InttMonDraw.h
Referenced by DrawGlobalChipMap(), and DrawGlobalLadderMap().
constexpr double InttMonDraw::X_LABEL_TEXT_SIZE = 0.5 static private
Definition at line 102 of file InttMonDraw.h.
View newest version in sPHENIX GitHub at line 102 of file InttMonDraw.h
Referenced by DrawGlobalChipMap(), and DrawGlobalLadderMap().
constexpr double InttMonDraw::Y_LABEL_FRAC = 0.05 static private
Definition at line 99 of file InttMonDraw.h.
View newest version in sPHENIX GitHub at line 99 of file InttMonDraw.h
Referenced by DrawGlobalChipMap(), and DrawGlobalLadderMap().
constexpr double InttMonDraw::Y_LABEL_TEXT_SIZE = 0.5 static private
Definition at line 101 of file InttMonDraw.h.
View newest version in sPHENIX GitHub at line 101 of file InttMonDraw.h
Referenced by DrawGlobalChipMap(), and DrawGlobalLadderMap().
The documentation for this class was generated from the following files:
OnlMon/blob/main/subsystems/intt/InttMonDraw.h
OnlMon/blob/main/subsystems/intt/InttMonDraw.cc