Analysis Software: MvtxEventInfov2 Class Reference
MvtxEventInfov2 Class Reference
#include <coresoftware/blob/master/offline/packages/trackbase/MvtxEventInfov2.h>
Public Member Functions
MvtxEventInfov2 ()=default
virtual ~MvtxEventInfov2 ()=default
dtor
PHObject * CloneMe () const override
Virtual copy constructor.
void Reset () override
Clear Event.
void identify (std::ostream &os=std::cout) const override
int isValid () const override
isValid returns non zero if object contains valid data
void set_number_HB (const int) override
int get_number_HB () const override
void set_strobe_BCO (const uint64_t strobe_BCO) override
void set_strobe_BCO_L1_BCO (const uint64_t strobe_BCO, const uint64_t L1_BCO) override
unsigned int get_number_strobes () const override
unsigned int get_number_L1s () const override
std::set< uint64_t > get_strobe_BCOs () const override
std::set< uint64_t > get_L1_BCOs () const override
std::set< uint64_t > get_strobe_BCO_from_L1_BCO (const uint64_t ival) const override
std::set< uint64_t > get_L1_BCO_from_strobe_BCO (const uint64_t ival) const override
Public Member Functions inherited from MvtxEventInfo
MvtxEventInfo ()=default
virtual ~MvtxEventInfo ()=default
dtor
void set_floatval (const std::string &, const float)
float get_floatval (const std::string &) const
void set_intval (const std::string &, const int32_t)
int get_intval (const std::string &) const
void set_int64val (const std::string &, const int64_t)
int get_int64val (const std::string &) const
void set_uintval (const std::string &, const uint32_t)
int get_uintval (const std::string &) const
void set_uint64val (const std::string &, const uint64_t)
int get_uint64val (const std::string &) const
void set_stringval (const std::string &, const std::string &)
std::string get_stringval (const std::string &) const
Public Member Functions inherited from PHObject
PHObject ()
ctor
~PHObject () override
dtor
virtual PHObject * clone () const final
PHObject * Clone (const char *newname="") const final
void Copy (TObject &object) const final
virtual int Integrate () const
virtual int Integrate (PHObject *)
virtual void CopyFrom (const PHObject *obj)
Protected Attributes
std::set< strobe_L1_pair > m_strobe_BCO_L1_BCO
std::set< uint64_t > m_strobe_BCOs
std::string m_number_L1_name = "Number L1"
std::string m_number_HB_name = "Number HB"
Protected Attributes inherited from MvtxEventInfo
std::map< std::string, int32_t > m_IntEventProperties
std::map< std::string, int64_t > m_Int64EventProperties
std::map< std::string, uint32_t > m_UintEventProperties
std::map< std::string, uint64_t > m_Uint64EventProperties
std::map< std::string, float > m_FloatEventProperties
std::map< std::string,
std::string > m_StringEventProperties
Private Member Functions
void warning (const std::string &func) const
Private Attributes
int m_number_HB = -1
Detailed Description
Definition at line 22 of file MvtxEventInfov2.h.
View newest version in sPHENIX GitHub at line 22 of file MvtxEventInfov2.h
Constructor & Destructor Documentation
MvtxEventInfov2::MvtxEventInfov2 () default
virtual MvtxEventInfov2::~MvtxEventInfov2 () virtual default
dtor
Member Function Documentation
PHObject * MvtxEventInfov2::CloneMe () const override virtual
Virtual copy constructor.
Reimplemented from MvtxEventInfo.
Definition at line 5 of file MvtxEventInfov2.cc.
View newest version in sPHENIX GitHub at line 5 of file MvtxEventInfov2.cc
References PHWHERE.
std::set< uint64_t > MvtxEventInfov2::get_L1_BCO_from_strobe_BCO (const uint64_t ival) const override virtual
Reimplemented from MvtxEventInfo.
Definition at line 179 of file MvtxEventInfov2.cc.
View newest version in sPHENIX GitHub at line 179 of file MvtxEventInfov2.cc
References m_strobe_BCO_L1_BCO.
Referenced by identify().
std::set< uint64_t > MvtxEventInfov2::get_L1_BCOs () const override virtual
Reimplemented from MvtxEventInfo.
Definition at line 150 of file MvtxEventInfov2.cc.
View newest version in sPHENIX GitHub at line 150 of file MvtxEventInfov2.cc
References m_strobe_BCO_L1_BCO.
int MvtxEventInfov2::get_number_HB () const override virtual
Reimplemented from MvtxEventInfo.
Definition at line 102 of file MvtxEventInfov2.cc.
View newest version in sPHENIX GitHub at line 102 of file MvtxEventInfov2.cc
References m_number_HB.
Referenced by identify().
unsigned int MvtxEventInfov2::get_number_L1s () const override virtual
Reimplemented from MvtxEventInfo.
Definition at line 131 of file MvtxEventInfov2.cc.
View newest version in sPHENIX GitHub at line 131 of file MvtxEventInfov2.cc
References m_strobe_BCO_L1_BCO.
Referenced by identify().
unsigned int MvtxEventInfov2::get_number_strobes () const override virtual
Reimplemented from MvtxEventInfo.
Definition at line 118 of file MvtxEventInfov2.cc.
View newest version in sPHENIX GitHub at line 118 of file MvtxEventInfov2.cc
References m_strobe_BCO_L1_BCO.
std::set< uint64_t > MvtxEventInfov2::get_strobe_BCO_from_L1_BCO (const uint64_t ival) const override virtual
Reimplemented from MvtxEventInfo.
Definition at line 163 of file MvtxEventInfov2.cc.
View newest version in sPHENIX GitHub at line 163 of file MvtxEventInfov2.cc
References m_strobe_BCO_L1_BCO.
std::set< uint64_t > MvtxEventInfov2::get_strobe_BCOs () const override virtual
Reimplemented from MvtxEventInfo.
Definition at line 144 of file MvtxEventInfov2.cc.
View newest version in sPHENIX GitHub at line 144 of file MvtxEventInfov2.cc
References m_strobe_BCOs.
Referenced by identify().
void MvtxEventInfov2::identify (std::ostream & os = std::cout) const override virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from MvtxEventInfo.
Definition at line 26 of file MvtxEventInfov2.cc.
View newest version in sPHENIX GitHub at line 26 of file MvtxEventInfov2.cc
References get_L1_BCO_from_strobe_BCO(), get_number_HB(), get_number_L1s(), get_strobe_BCOs(), MvtxEventInfo::m_FloatEventProperties, MvtxEventInfo::m_Int64EventProperties, MvtxEventInfo::m_IntEventProperties, m_number_HB_name, m_number_L1_name, MvtxEventInfo::m_StringEventProperties, MvtxEventInfo::m_Uint64EventProperties, and MvtxEventInfo::m_UintEventProperties.
int MvtxEventInfov2::isValid () const override virtual
isValid returns non zero if object contains valid data
Reimplemented from MvtxEventInfo.
Definition at line 91 of file MvtxEventInfov2.cc.
View newest version in sPHENIX GitHub at line 91 of file MvtxEventInfov2.cc
References PHWHERE.
void MvtxEventInfov2::Reset () override virtual
Clear Event.
Reimplemented from MvtxEventInfo.
Definition at line 11 of file MvtxEventInfov2.cc.
View newest version in sPHENIX GitHub at line 11 of file MvtxEventInfov2.cc
References MvtxEventInfo::m_FloatEventProperties, MvtxEventInfo::m_Int64EventProperties, MvtxEventInfo::m_IntEventProperties, MvtxEventInfo::m_StringEventProperties, m_strobe_BCO_L1_BCO, m_strobe_BCOs, MvtxEventInfo::m_Uint64EventProperties, and MvtxEventInfo::m_UintEventProperties.
void MvtxEventInfov2::set_number_HB (const int ival) override virtual
Reimplemented from MvtxEventInfo.
Definition at line 97 of file MvtxEventInfov2.cc.
View newest version in sPHENIX GitHub at line 97 of file MvtxEventInfov2.cc
References m_number_HB.
void MvtxEventInfov2::set_strobe_BCO (const uint64_t strobe_BCO) override virtual
Reimplemented from MvtxEventInfo.
Definition at line 107 of file MvtxEventInfov2.cc.
View newest version in sPHENIX GitHub at line 107 of file MvtxEventInfov2.cc
References m_strobe_BCOs.
void MvtxEventInfov2::set_strobe_BCO_L1_BCO (const uint64_t strobe_BCO, const uint64_t L1_BCO) override virtual
Reimplemented from MvtxEventInfo.
Definition at line 112 of file MvtxEventInfov2.cc.
View newest version in sPHENIX GitHub at line 112 of file MvtxEventInfov2.cc
References m_strobe_BCO_L1_BCO.
void MvtxEventInfov2::warning (const std::string & func) const private
Member Data Documentation
int MvtxEventInfov2::m_number_HB = -1 private
Definition at line 70 of file MvtxEventInfov2.h.
View newest version in sPHENIX GitHub at line 70 of file MvtxEventInfov2.h
Referenced by get_number_HB(), and set_number_HB().
std::string MvtxEventInfov2::m_number_HB_name = "Number HB" protected
Definition at line 65 of file MvtxEventInfov2.h.
View newest version in sPHENIX GitHub at line 65 of file MvtxEventInfov2.h
Referenced by identify().
std::string MvtxEventInfov2::m_number_L1_name = "Number L1" protected
Definition at line 64 of file MvtxEventInfov2.h.
View newest version in sPHENIX GitHub at line 64 of file MvtxEventInfov2.h
Referenced by identify().
std::set<strobe_L1_pair> MvtxEventInfov2::m_strobe_BCO_L1_BCO protected
Definition at line 61 of file MvtxEventInfov2.h.
View newest version in sPHENIX GitHub at line 61 of file MvtxEventInfov2.h
Referenced by get_L1_BCO_from_strobe_BCO(), get_L1_BCOs(), get_number_L1s(), get_number_strobes(), get_strobe_BCO_from_L1_BCO(), Reset(), and set_strobe_BCO_L1_BCO().
std::set<uint64_t> MvtxEventInfov2::m_strobe_BCOs protected
Definition at line 62 of file MvtxEventInfov2.h.
View newest version in sPHENIX GitHub at line 62 of file MvtxEventInfov2.h
Referenced by get_strobe_BCOs(), Reset(), and set_strobe_BCO().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/trackbase/MvtxEventInfov2.h
coresoftware/blob/master/offline/packages/trackbase/MvtxEventInfov2.cc