Analysis Software: MicromegasMapping Class Reference
MicromegasMapping Class Reference
micromegas mapping
#include <coresoftware/blob/master/offline/packages/micromegas/MicromegasMapping.h>
Classes
class DetectorId
contains all relevant detector information
Public Member Functions
MicromegasMapping ()
constructor
std::vector< int > get_fee_id_list () const
get list of fee ids
TrkrDefs::hitsetkey get_hitsetkey (int) const
get hitsetkey from fiber_id (fee_id)
std::string get_detname_saclay (int) const
get detector name (saclay) from fiber_id (fee_id)
std::string get_detname_sphenix (int) const
get detector name (sphenix) from fiber_id (fee_id)
int get_physical_strip (int, int) const
get physical strip number from channel_id
std::string get_detname_saclay_from_hitsetkey (TrkrDefs::hitsetkey) const
get detector name (sphenix) from hitset key
std::string get_detname_sphenix_from_hitsetkey (TrkrDefs::hitsetkey) const
get detector name (saclay) from hitset key
Private Member Functions
void construct_channel_mapping ()
construct fee channel id to physical strip mapping
Private Attributes
std::vector< DetectorId > m_detectors
list of defined detectors
std::map< int, DetectorId > m_detector_map
map detector_id to fee_id
std::array< int,
MicromegasDefs::m_nchannels_fee > m_fee_to_strip_mapping_z = {{0}}
map FEE channel id to physical strip id (z view)
std::array< int,
MicromegasDefs::m_nchannels_fee > m_fee_to_strip_mapping_phi = {{0}}
map FEE channel id to physical strip id (phi view)
Detailed Description
micromegas mapping
Definition at line 19 of file MicromegasMapping.h.
View newest version in sPHENIX GitHub at line 19 of file MicromegasMapping.h
Constructor & Destructor Documentation
MicromegasMapping::MicromegasMapping ()
constructor
Definition at line 81 of file MicromegasMapping.cc.
View newest version in sPHENIX GitHub at line 81 of file MicromegasMapping.cc
References MicromegasDefs::genHitSetKey(), PHG4InttDefs::SEGMENTATION_PHI, and PHG4InttDefs::SEGMENTATION_Z.
Member Function Documentation
void MicromegasMapping::construct_channel_mapping () private
construct fee channel id to physical strip mapping
Definition at line 215 of file MicromegasMapping.cc.
View newest version in sPHENIX GitHub at line 215 of file MicromegasMapping.cc
References assert, m_fee_to_strip_mapping_phi, m_fee_to_strip_mapping_z, and MicromegasDefs::m_nchannels_fee.
std::string MicromegasMapping::get_detname_saclay (int fee_id) const
get detector name (saclay) from fiber_id (fee_id)
saclay detector name are of type MxxP and MxxZ, with xx the module number
Definition at line 145 of file MicromegasMapping.cc.
View newest version in sPHENIX GitHub at line 145 of file MicromegasMapping.cc
References m_detector_map.
std::string MicromegasMapping::get_detname_saclay_from_hitsetkey (TrkrDefs::hitsetkey key) const
get detector name (sphenix) from hitset key
Definition at line 193 of file MicromegasMapping.cc.
View newest version in sPHENIX GitHub at line 193 of file MicromegasMapping.cc
References m_detectors.
std::string MicromegasMapping::get_detname_sphenix (int fee_id) const
get detector name (sphenix) from fiber_id (fee_id)
sphenix detector name are of type SWP, SWZ, etc.
Definition at line 156 of file MicromegasMapping.cc.
View newest version in sPHENIX GitHub at line 156 of file MicromegasMapping.cc
References m_detector_map.
Referenced by TpotMon::Init(), and TpotMonDraw::TpotMonDraw().
std::string MicromegasMapping::get_detname_sphenix_from_hitsetkey (TrkrDefs::hitsetkey key) const
get detector name (saclay) from hitset key
Definition at line 204 of file MicromegasMapping.cc.
View newest version in sPHENIX GitHub at line 204 of file MicromegasMapping.cc
References m_detectors.
std::vector< int > MicromegasMapping::get_fee_id_list () const
get list of fee ids
Definition at line 126 of file MicromegasMapping.cc.
View newest version in sPHENIX GitHub at line 126 of file MicromegasMapping.cc
References m_detectors, out, and Acts::Test::transform.
Referenced by TpotMon::Init(), MicromegasCalibrationData::read(), and TpotMonDraw::TpotMonDraw().
TrkrDefs::hitsetkey MicromegasMapping::get_hitsetkey (int fee_id) const
get hitsetkey from fiber_id (fee_id)
Definition at line 134 of file MicromegasMapping.cc.
View newest version in sPHENIX GitHub at line 134 of file MicromegasMapping.cc
References m_detector_map.
Referenced by get_physical_strip(), TpotMon::Init(), TpotMon::process_event(), MicromegasRawDataDecoder::process_event(), MicromegasCombinedDataDecoder::process_event(), MicromegasCombinedDataEvaluation::process_event(), MicromegasRawDataEvaluation::process_event(), and MicromegasCalibrationData::read().
int MicromegasMapping::get_physical_strip (int fee_id, int channel_id) const
get physical strip number from channel_id
physical strip number correspond to a position in the detector's geant implementation, with increasing number corresponding to strips further away from the detector's edge, as defined in CylinderGeomMicromegas
Definition at line 167 of file MicromegasMapping.cc.
View newest version in sPHENIX GitHub at line 167 of file MicromegasMapping.cc
References get_hitsetkey(), MicromegasDefs::getSegmentationType(), m_fee_to_strip_mapping_phi, m_fee_to_strip_mapping_z, MicromegasDefs::m_nchannels_fee, PHG4InttDefs::SEGMENTATION_PHI, and PHG4InttDefs::SEGMENTATION_Z.
Referenced by TpotMon::process_event(), MicromegasRawDataDecoder::process_event(), MicromegasCombinedDataDecoder::process_event(), MicromegasRawDataEvaluation::process_event(), MicromegasCombinedDataEvaluation::process_event(), and MicromegasCalibrationData::read().
Member Data Documentation
std::map<int, DetectorId> MicromegasMapping::m_detector_map private
map detector_id to fee_id
Definition at line 103 of file MicromegasMapping.h.
View newest version in sPHENIX GitHub at line 103 of file MicromegasMapping.h
Referenced by get_detname_saclay(), get_detname_sphenix(), and get_hitsetkey().
std::vector<DetectorId> MicromegasMapping::m_detectors private
list of defined detectors
Definition at line 100 of file MicromegasMapping.h.
View newest version in sPHENIX GitHub at line 100 of file MicromegasMapping.h
Referenced by get_detname_saclay_from_hitsetkey(), get_detname_sphenix_from_hitsetkey(), and get_fee_id_list().
std::array<int, MicromegasDefs::m_nchannels_fee> MicromegasMapping::m_fee_to_strip_mapping_phi = {{0}} private
map FEE channel id to physical strip id (phi view)
Definition at line 109 of file MicromegasMapping.h.
View newest version in sPHENIX GitHub at line 109 of file MicromegasMapping.h
Referenced by construct_channel_mapping(), and get_physical_strip().
std::array<int, MicromegasDefs::m_nchannels_fee> MicromegasMapping::m_fee_to_strip_mapping_z = {{0}} private
map FEE channel id to physical strip id (z view)
Definition at line 106 of file MicromegasMapping.h.
View newest version in sPHENIX GitHub at line 106 of file MicromegasMapping.h
Referenced by construct_channel_mapping(), and get_physical_strip().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/micromegas/MicromegasMapping.h
coresoftware/blob/master/offline/packages/micromegas/MicromegasMapping.cc