Analysis Software: Acts::ExaTrkXTimer Class Reference
Acts::ExaTrkXTimer Class Reference
#include <acts/blob/sPHENIX/Plugins/ExaTrkX/include/Acts/Plugins/ExaTrkX/ExaTrkXTiming.hpp>
Public Member Functions
ExaTrkXTimer (bool disabled=false)
void start ()
void stop ()
double stopAndGetElapsedTime ()
double elapsed ()
double elapsedSeconds ()
Private Attributes
std::chrono::time_point
< std::chrono::high_resolution_clock > m_start
std::chrono::time_point
< std::chrono::high_resolution_clock > m_end
bool m_running = false
bool m_disabled
Detailed Description
A timer to allow easy timing
Definition at line 45 of file ExaTrkXTiming.hpp.
View newest version in sPHENIX GitHub at line 45 of file ExaTrkXTiming.hpp
Constructor & Destructor Documentation
Acts::ExaTrkXTimer::ExaTrkXTimer (bool disabled = false) inline
Definition at line 47 of file ExaTrkXTiming.hpp.
View newest version in sPHENIX GitHub at line 47 of file ExaTrkXTiming.hpp
Member Function Documentation
double Acts::ExaTrkXTimer::elapsed () inline
Definition at line 65 of file ExaTrkXTiming.hpp.
View newest version in sPHENIX GitHub at line 65 of file ExaTrkXTiming.hpp
References test_fpe::count, end, m_disabled, m_end, m_running, and m_start.
Referenced by elapsedSeconds().
double Acts::ExaTrkXTimer::elapsedSeconds () inline
Definition at line 78 of file ExaTrkXTiming.hpp.
View newest version in sPHENIX GitHub at line 78 of file ExaTrkXTiming.hpp
References elapsed().
Referenced by stopAndGetElapsedTime().
void Acts::ExaTrkXTimer::start () inline
Definition at line 49 of file ExaTrkXTiming.hpp.
View newest version in sPHENIX GitHub at line 49 of file ExaTrkXTiming.hpp
References m_disabled, m_running, and m_start.
void Acts::ExaTrkXTimer::stop () inline
Definition at line 55 of file ExaTrkXTiming.hpp.
View newest version in sPHENIX GitHub at line 55 of file ExaTrkXTiming.hpp
References m_disabled, m_end, and m_running.
Referenced by __example_1.f__(), __example_2.f__(), __example_3.f__(), __example_4.f__(), d1mach(), hijing(), hijset(), itafun(), luerrm(), lutest(), pyhiinit(), pyhiinki(), pyhimaxi(), pyhirand(), pyhitest(), pystop(), pyupev(), radgen_init(), rndmq(), stopAndGetElapsedTime(), vacpol(), and xytabl().
double Acts::ExaTrkXTimer::stopAndGetElapsedTime () inline
Definition at line 61 of file ExaTrkXTiming.hpp.
View newest version in sPHENIX GitHub at line 61 of file ExaTrkXTiming.hpp
References elapsedSeconds(), and stop().
Member Data Documentation
bool Acts::ExaTrkXTimer::m_disabled private
Definition at line 84 of file ExaTrkXTiming.hpp.
View newest version in sPHENIX GitHub at line 84 of file ExaTrkXTiming.hpp
Referenced by elapsed(), start(), and stop().
std::chrono::time_point<std::chrono::high_resolution_clock> Acts::ExaTrkXTimer::m_end private
Definition at line 82 of file ExaTrkXTiming.hpp.
View newest version in sPHENIX GitHub at line 82 of file ExaTrkXTiming.hpp
Referenced by elapsed(), and stop().
bool Acts::ExaTrkXTimer::m_running = false private
Definition at line 83 of file ExaTrkXTiming.hpp.
View newest version in sPHENIX GitHub at line 83 of file ExaTrkXTiming.hpp
Referenced by elapsed(), start(), and stop().
std::chrono::time_point<std::chrono::high_resolution_clock> Acts::ExaTrkXTimer::m_start private
Definition at line 81 of file ExaTrkXTiming.hpp.
View newest version in sPHENIX GitHub at line 81 of file ExaTrkXTiming.hpp
Referenced by elapsed(), and start().
The documentation for this class was generated from the following file:
acts/blob/sPHENIX/Plugins/ExaTrkX/include/Acts/Plugins/ExaTrkX/ExaTrkXTiming.hpp