Analysis Software: acts/blob/sPHENIX/Tests/UnitTests/Plugins/Cuda/Seeding2/main.cpp File Reference
main.cpp File Reference
#include "CommandLineArguments.hpp"
#include "ReadSeedFile.hpp"
#include "TestDeviceCuts.hpp"
#include "TestHostCuts.hpp"
#include "TestSpacePoint.hpp"
#include "Acts/Plugins/Cuda/Seeding2/SeedFinder.hpp"
#include "Acts/Plugins/Cuda/Utilities/Info.hpp"
#include "Acts/Plugins/Cuda/Utilities/MemoryManager.hpp"
#include "Acts/EventData/SpacePointData.hpp"
#include "Acts/Seeding/BinFinder.hpp"
#include "Acts/Seeding/BinnedSPGroup.hpp"
#include "Acts/Seeding/SeedFilterConfig.hpp"
#include "Acts/Seeding/SeedFinder.hpp"
#include "Acts/Seeding/SeedFinderConfig.hpp"
#include <cassert>
#include <chrono>
#include <iomanip>
#include <iostream>
#include <iterator>
#include <memory>
Functions
int main (int argc, char *argv[])
Function Documentation
int main (int argc, char * argv[])
Definition at line 39 of file main.cpp.
View newest version in sPHENIX GitHub at line 39 of file main.cpp
References assert, Acts::SeedFinderOptions::beamPos, Acts::SpacePointGridOptions::bFieldInZ, Acts::SeedFinderOptions::bFieldInZ, Acts::SpacePointGridConfig::cotThetaMax, test_fpe::count, covariance(), Acts::Cuda::SeedFinder< external_spacepoint_t >::createSeedsForGroup(), Acts::SeedFinder< external_spacepoint_t, platform_t >::createSeedsForGroup(), CommandLineArguments::cudaDevice, CommandLineArguments::cudaDeviceMemory, Acts::SpacePointGridConfig::deltaRMax, Acts::Cuda::Info::devices(), Acts::BinnedSPGroup< external_spacepoint_t >::end(), CommandLineArguments::filterDuplicates, grid(), upload::group, CommandLineArguments::groupsToIterate, i, Acts::Cuda::Info::instance(), Acts::Cuda::MemoryManager::instance(), CommandLineArguments::interpret(), TestSpacePoint::m_varianceR, TestSpacePoint::m_varianceZ, Acts::SpacePointGridConfig::minPt, testing::internal::move(), CommandLineArguments::onlyGPU, position, readSeedFile(), Acts::SpacePointData::resize(), Acts::SpacePointGridConfig::rMax, Acts::SeedFinderConfig< SpacePoint >::rMax, Acts::Cuda::MemoryManager::setMemorySize(), size, CommandLineArguments::spFile, filter::state, testDeviceCuts(), to_string(), Acts::SpacePointGridConfig::toInternalUnits(), Acts::SeedFilterConfig::toInternalUnits(), TestSpacePoint::x(), TestSpacePoint::y(), TestSpacePoint::z(), Acts::SpacePointGridConfig::zMax, and Acts::SpacePointGridConfig::zMin.