Analysis Software: KshortReconstruction Class Reference
KshortReconstruction Class Reference
#include <coresoftware/blob/master/offline/packages/TrackingDiagnostics/KshortReconstruction.h>
Public Member Functions
KshortReconstruction (const std::string &name="KshortReconstruction")
virtual ~KshortReconstruction ()
int InitRun (PHCompositeNode *topNode) override
int process_event (PHCompositeNode *topNode) override
int End (PHCompositeNode *) override
Called at the end of all processing.
void setPtCut (double ptcut)
void setTrackQualityCut (double cut)
void setPairDCACut (double cut)
void setTrackDCACut (double cut)
void setRequireMVTX (bool set)
void setDecayMass (Float_t decayMassSet)
void set_output_file (const std::string &outputfile)
Public Member Functions inherited from SubsysReco
~SubsysReco () override
virtual int EndRun (const int)
Called at the end of each run.
virtual int Init (PHCompositeNode *)
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
void Print (const std::string &="ALL") const override
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Private Member Functions
void fillNtp (SvtxTrack *track1, SvtxTrack *track2, Acts::Vector3 dcavals1, Acts::Vector3 dcavals2, Acts::Vector3 pca_rel1, Acts::Vector3 pca_rel2, double pair_dca, double invariantMass, double invariantPt, float rapidity, float pseudorapidity, Eigen::Vector3d projected_pos1, Eigen::Vector3d projected_pos2, Eigen::Vector3d projected_mom1, Eigen::Vector3d projected_mom2, Acts::Vector3 pca_rel1_proj, Acts::Vector3 pca_rel2_proj, double pair_dca_proj)
void fillHistogram (Eigen::Vector3d mom1, Eigen::Vector3d mom2, TH1D *massreco, double &invariantMass, double &invariantPt, float &rapidity, float &pseudorapidity)
void findPcaTwoTracks (Acts::Vector3 pos1, Acts::Vector3 pos2, Acts::Vector3 mom1, Acts::Vector3 mom2, Acts::Vector3 &pca1, Acts::Vector3 &pca2, double &dca)
int getNodes (PHCompositeNode *topNode)
Acts::Vector3 calculateDca (SvtxTrack *track, const Acts::Vector3 &momentum, Acts::Vector3 position)
bool projectTrackToCylinder (SvtxTrack *track, double Radius, Eigen::Vector3d &pos, Eigen::Vector3d &mom)
bool projectTrackToPoint (SvtxTrack *track, Eigen::Vector3d PCA, Eigen::Vector3d &pos, Eigen::Vector3d &mom)
Acts::Vector3 getVertex (SvtxTrack *track)
Private Attributes
TNtuple * ntp_reco_info = nullptr
ActsGeometry * _tGeometry = nullptr
SvtxTrackMap * m_svtxTrackMap = nullptr
SvtxVertexMap * m_vertexMap = nullptr
std::string filepath = ""
Float_t decaymass = 0.13957
bool _require_mvtx = true
double _qual_cut = 10.0
double pair_dca_cut = 0.05
double track_dca_cut = 0.01
double invariant_pt_cut = 0.1
TFile * fout = nullptr
TH1D * recomass = nullptr
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = std::numeric_limits<int>::max() - 10
}
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Detailed Description
Definition at line 43 of file KshortReconstruction.h.
View newest version in sPHENIX GitHub at line 43 of file KshortReconstruction.h
Constructor & Destructor Documentation
KshortReconstruction::KshortReconstruction (const std::string & name = "KshortReconstruction")
Definition at line 404 of file KshortReconstruction.cc.
View newest version in sPHENIX GitHub at line 404 of file KshortReconstruction.cc
virtual KshortReconstruction::~KshortReconstruction () inline virtual
Definition at line 47 of file KshortReconstruction.h.
View newest version in sPHENIX GitHub at line 47 of file KshortReconstruction.h
Member Function Documentation
Acts::Vector3 KshortReconstruction::calculateDca (SvtxTrack * track, const Acts::Vector3 & momentum, Acts::Vector3 position) private
Definition at line 409 of file KshortReconstruction.cc.
View newest version in sPHENIX GitHub at line 409 of file KshortReconstruction.cc
References SvtxVertexMap::get(), SvtxTrack::get_vertex_id(), m_vertexMap, ActsTests::PropagationDatasets::phi, position, physmon_track_finding_ttbar::r, and Fun4AllBase::Verbosity().
Referenced by process_event().
int KshortReconstruction::End (PHCompositeNode *) override virtual
Called at the end of all processing.
Reimplemented from SubsysReco.
Definition at line 474 of file KshortReconstruction.cc.
View newest version in sPHENIX GitHub at line 474 of file KshortReconstruction.cc
References fout, ntp_reco_info, and recomass.
void KshortReconstruction::fillHistogram (Eigen::Vector3d mom1, Eigen::Vector3d mom2, TH1D * massreco, double & invariantMass, double & invariantPt, float & rapidity, float & pseudorapidity) private
Definition at line 207 of file KshortReconstruction.cc.
View newest version in sPHENIX GitHub at line 207 of file KshortReconstruction.cc
References decaymass, invariant_pt_cut, v1, v2, and Fun4AllBase::Verbosity().
Referenced by process_event().
void KshortReconstruction::fillNtp (SvtxTrack * track1, SvtxTrack * track2, Acts::Vector3 dcavals1, Acts::Vector3 dcavals2, Acts::Vector3 pca_rel1, Acts::Vector3 pca_rel2, double pair_dca, double invariantMass, double invariantPt, float rapidity, float pseudorapidity, Eigen::Vector3d projected_pos1, Eigen::Vector3d projected_pos2, Eigen::Vector3d projected_mom1, Eigen::Vector3d projected_mom2, Acts::Vector3 pca_rel1_proj, Acts::Vector3 pca_rel2_proj, double pair_dca_proj) private
Definition at line 167 of file KshortReconstruction.cc.
View newest version in sPHENIX GitHub at line 167 of file KshortReconstruction.cc
References SvtxVertexMap::get(), SvtxTrack::get_charge(), SvtxTrack::get_px(), SvtxTrack::get_py(), SvtxTrack::get_pz(), SvtxTrack::get_quality(), SvtxTrack::get_tpc_seed(), SvtxTrack::get_vertex_id(), SvtxTrack::get_x(), SvtxTrack::get_y(), SvtxTrack::get_z(), m_vertexMap, ntp_reco_info, ActsTests::PropagationDatasets::pathLength, and TrackSeed::size_cluster_keys().
Referenced by process_event().
void KshortReconstruction::findPcaTwoTracks (Acts::Vector3 pos1, Acts::Vector3 pos2, Acts::Vector3 mom1, Acts::Vector3 mom2, Acts::Vector3 & pca1, Acts::Vector3 & pca2, double & dca) private
Definition at line 339 of file KshortReconstruction.cc.
View newest version in sPHENIX GitHub at line 339 of file KshortReconstruction.cc
References KFPMath::a2, b1, Acts::PhysicalConstants::c, decaymass, F, G, testing::internal::move(), v1, v2, TauVsDIS_MachineLearning_Differentiation::X, and TauVsDIS_MachineLearning_Differentiation::Y.
Referenced by process_event().
int KshortReconstruction::getNodes (PHCompositeNode * topNode) private
Definition at line 484 of file KshortReconstruction.cc.
View newest version in sPHENIX GitHub at line 484 of file KshortReconstruction.cc
References _tGeometry, Fun4AllReturnCodes::ABORTEVENT, Fun4AllReturnCodes::EVENT_OK, m_svtxTrackMap, m_vertexMap, and PHWHERE.
Referenced by InitRun().
Acts::Vector3 KshortReconstruction::getVertex (SvtxTrack * track) private
Definition at line 324 of file KshortReconstruction.cc.
View newest version in sPHENIX GitHub at line 324 of file KshortReconstruction.cc
References Acts::UnitConstants::cm, SvtxVertexMap::get(), SvtxTrack::get_vertex_id(), SvtxVertex::get_x(), SvtxVertex::get_y(), SvtxVertex::get_z(), and m_vertexMap.
int KshortReconstruction::InitRun (PHCompositeNode *) override virtual
Called for first event when run number is known. Typically this is where you may want to fetch data from database, because you know the run number.
Reimplemented from SubsysReco.
Definition at line 459 of file KshortReconstruction.cc.
View newest version in sPHENIX GitHub at line 459 of file KshortReconstruction.cc
References filepath, fout, getNodes(), perf_headwind::name, ntp_reco_info, and recomass.
int KshortReconstruction::process_event (PHCompositeNode *) override virtual
Called for each event. This is where you do the real work.
Reimplemented from SubsysReco.
Definition at line 19 of file KshortReconstruction.cc.
View newest version in sPHENIX GitHub at line 19 of file KshortReconstruction.cc
References _qual_cut, _require_mvtx, SvtxTrackMap::begin(), calculateDca(), SvtxTrackMap::end(), fillHistogram(), fillNtp(), findPcaTwoTracks(), m_svtxTrackMap, next, pair_dca_cut, projectTrackToPoint(), recomass, track_dca_cut, and Fun4AllBase::Verbosity().
bool KshortReconstruction::projectTrackToCylinder (SvtxTrack * track, double Radius, Eigen::Vector3d & pos, Eigen::Vector3d & mom) private
Make a cylindrical surface at (0,0,0) aligned along the z axis
Definition at line 280 of file KshortReconstruction.cc.
View newest version in sPHENIX GitHub at line 280 of file KshortReconstruction.cc
References _tGeometry, Acts::UnitConstants::cm, eta, ActsGeometry::geometry(), ActsTrackingGeometry::getGeoContext(), m_vertexMap, momentum, Acts::Test::pos, ActsTests::PropagationDatasets::theta, and Acts::Test::transform.
bool KshortReconstruction::projectTrackToPoint (SvtxTrack * track, Eigen::Vector3d PCA, Eigen::Vector3d & pos, Eigen::Vector3d & mom) private
create perigee surface
Definition at line 237 of file KshortReconstruction.cc.
View newest version in sPHENIX GitHub at line 237 of file KshortReconstruction.cc
References _tGeometry, Acts::UnitConstants::cm, ActsGeometry::geometry(), SvtxTrack::get_px(), SvtxTrack::get_py(), SvtxTrack::get_pz(), SvtxTrack::get_x(), SvtxTrack::get_y(), SvtxTrack::get_z(), ActsTrackingGeometry::getGeoContext(), m_vertexMap, ActsPropagator::makeTrackParams(), ActsPropagator::makeVertexSurface(), momentum, Acts::Test::pos, ActsPropagator::propagateTrack(), and Fun4AllBase::Verbosity().
Referenced by process_event().
void KshortReconstruction::set_output_file (const std::string & outputfile) inline
Definition at line 59 of file KshortReconstruction.h.
View newest version in sPHENIX GitHub at line 59 of file KshortReconstruction.h
References filepath.
Referenced by G4KshortReconstruction().
void KshortReconstruction::setDecayMass (Float_t decayMassSet) inline
Definition at line 58 of file KshortReconstruction.h.
View newest version in sPHENIX GitHub at line 58 of file KshortReconstruction.h
References decaymass.
void KshortReconstruction::setPairDCACut (double cut) inline
Definition at line 55 of file KshortReconstruction.h.
View newest version in sPHENIX GitHub at line 55 of file KshortReconstruction.h
References pair_dca_cut.
void KshortReconstruction::setPtCut (double ptcut) inline
Definition at line 53 of file KshortReconstruction.h.
View newest version in sPHENIX GitHub at line 53 of file KshortReconstruction.h
References invariant_pt_cut.
void KshortReconstruction::setRequireMVTX (bool set) inline
Definition at line 57 of file KshortReconstruction.h.
View newest version in sPHENIX GitHub at line 57 of file KshortReconstruction.h
References _require_mvtx.
void KshortReconstruction::setTrackDCACut (double cut) inline
Definition at line 56 of file KshortReconstruction.h.
View newest version in sPHENIX GitHub at line 56 of file KshortReconstruction.h
References track_dca_cut.
void KshortReconstruction::setTrackQualityCut (double cut) inline
Definition at line 54 of file KshortReconstruction.h.
View newest version in sPHENIX GitHub at line 54 of file KshortReconstruction.h
References _qual_cut.
Member Data Documentation
double KshortReconstruction::_qual_cut = 10.0 private
Definition at line 86 of file KshortReconstruction.h.
View newest version in sPHENIX GitHub at line 86 of file KshortReconstruction.h
Referenced by process_event(), and setTrackQualityCut().
bool KshortReconstruction::_require_mvtx = true private
Definition at line 85 of file KshortReconstruction.h.
View newest version in sPHENIX GitHub at line 85 of file KshortReconstruction.h
Referenced by process_event(), and setRequireMVTX().
ActsGeometry* KshortReconstruction::_tGeometry = nullptr private
Definition at line 79 of file KshortReconstruction.h.
View newest version in sPHENIX GitHub at line 79 of file KshortReconstruction.h
Referenced by getNodes(), projectTrackToCylinder(), and projectTrackToPoint().
Float_t KshortReconstruction::decaymass = 0.13957 private
Definition at line 84 of file KshortReconstruction.h.
View newest version in sPHENIX GitHub at line 84 of file KshortReconstruction.h
Referenced by fillHistogram(), findPcaTwoTracks(), and setDecayMass().
std::string KshortReconstruction::filepath = "" private
Definition at line 83 of file KshortReconstruction.h.
View newest version in sPHENIX GitHub at line 83 of file KshortReconstruction.h
Referenced by InitRun(), and set_output_file().
TFile* KshortReconstruction::fout = nullptr private
Definition at line 90 of file KshortReconstruction.h.
View newest version in sPHENIX GitHub at line 90 of file KshortReconstruction.h
Referenced by End(), and InitRun().
double KshortReconstruction::invariant_pt_cut = 0.1 private
Definition at line 89 of file KshortReconstruction.h.
View newest version in sPHENIX GitHub at line 89 of file KshortReconstruction.h
Referenced by fillHistogram(), and setPtCut().
SvtxTrackMap* KshortReconstruction::m_svtxTrackMap = nullptr private
Definition at line 80 of file KshortReconstruction.h.
View newest version in sPHENIX GitHub at line 80 of file KshortReconstruction.h
Referenced by getNodes(), and process_event().
SvtxVertexMap* KshortReconstruction::m_vertexMap = nullptr private
Definition at line 81 of file KshortReconstruction.h.
View newest version in sPHENIX GitHub at line 81 of file KshortReconstruction.h
Referenced by calculateDca(), fillNtp(), getNodes(), getVertex(), projectTrackToCylinder(), and projectTrackToPoint().
TNtuple* KshortReconstruction::ntp_reco_info = nullptr private
Definition at line 78 of file KshortReconstruction.h.
View newest version in sPHENIX GitHub at line 78 of file KshortReconstruction.h
Referenced by End(), fillNtp(), and InitRun().
double KshortReconstruction::pair_dca_cut = 0.05 private
Definition at line 87 of file KshortReconstruction.h.
View newest version in sPHENIX GitHub at line 87 of file KshortReconstruction.h
Referenced by process_event(), and setPairDCACut().
TH1D* KshortReconstruction::recomass = nullptr private
Definition at line 91 of file KshortReconstruction.h.
View newest version in sPHENIX GitHub at line 91 of file KshortReconstruction.h
Referenced by End(), InitRun(), and process_event().
double KshortReconstruction::track_dca_cut = 0.01 private
Definition at line 88 of file KshortReconstruction.h.
View newest version in sPHENIX GitHub at line 88 of file KshortReconstruction.h
Referenced by process_event(), and setTrackDCACut().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/TrackingDiagnostics/KshortReconstruction.h
coresoftware/blob/master/offline/packages/TrackingDiagnostics/KshortReconstruction.cc