Analysis Software: ActsExamples::HitsPrinter Class Reference
ActsExamples::HitsPrinter Class Reference
Print hits within some geometric region-of-interest.
#include <acts/blob/sPHENIX/Examples/Algorithms/Printers/ActsExamples/Printers/HitsPrinter.hpp>
Classes
struct Config
Public Types
using Clusters = ActsExamples::GeometryIdMultimap< Acts::PlanarModuleCluster >
using HitParticlesMap = ActsExamples::IndexMultimap< ActsFatras::Barcode >
using HitIds = std::vector< size_t >
Public Member Functions
HitsPrinter (const Config &cfg, Acts::Logging::Level level)
ProcessCode execute (const AlgorithmContext &ctx) const override
const Config & config () const
Public Member Functions inherited from ActsExamples::IAlgorithm
IAlgorithm (std::string name, Acts::Logging::Level level=Acts::Logging::INFO)
std::string name () const override
The algorithm name.
ProcessCode internalExecute (const AlgorithmContext &context) final
ProcessCode initialize () override
Initialize the algorithm.
ProcessCode finalize () override
Finalize the algorithm.
Private Attributes
Config m_cfg
ReadDataHandle< Clusters > m_inputClusters {this, "InputClusters"}
ReadDataHandle< HitParticlesMap > m_inputMeasurementParticlesMap
ReadDataHandle< HitIds > m_inputHitIds {this, "InputHitIds"}
Additional Inherited Members
Protected Member Functions inherited from ActsExamples::IAlgorithm
const Acts::Logger & logger () const
Detailed Description
Print hits within some geometric region-of-interest.
Definition at line 35 of file HitsPrinter.hpp.
View newest version in sPHENIX GitHub at line 35 of file HitsPrinter.hpp
Member Typedef Documentation
using ActsExamples::HitsPrinter::Clusters = ActsExamples::GeometryIdMultimap<Acts::PlanarModuleCluster>
Definition at line 37 of file HitsPrinter.hpp.
View newest version in sPHENIX GitHub at line 37 of file HitsPrinter.hpp
using ActsExamples::HitsPrinter::HitIds = std::vector<size_t>
Definition at line 39 of file HitsPrinter.hpp.
View newest version in sPHENIX GitHub at line 39 of file HitsPrinter.hpp
using ActsExamples::HitsPrinter::HitParticlesMap = ActsExamples::IndexMultimap<ActsFatras::Barcode>
Definition at line 38 of file HitsPrinter.hpp.
View newest version in sPHENIX GitHub at line 38 of file HitsPrinter.hpp
Constructor & Destructor Documentation
ActsExamples::HitsPrinter::HitsPrinter (const Config & cfg, Acts::Logging::Level level)
Definition at line 25 of file HitsPrinter.cpp.
View newest version in sPHENIX GitHub at line 25 of file HitsPrinter.cpp
References ActsExamples::ReadDataHandle< T >::initialize(), ActsExamples::HitsPrinter::Config::inputClusters, ActsExamples::HitsPrinter::Config::inputHitIds, ActsExamples::HitsPrinter::Config::inputMeasurementParticlesMap, m_cfg, m_inputClusters, m_inputHitIds, and m_inputMeasurementParticlesMap.
Member Function Documentation
const Config& ActsExamples::HitsPrinter::config () const inline
Definition at line 61 of file HitsPrinter.hpp.
View newest version in sPHENIX GitHub at line 61 of file HitsPrinter.hpp
References m_cfg.
ActsExamples::ProcessCode ActsExamples::HitsPrinter::execute (const AlgorithmContext & context) const override virtual
Execute the algorithm for one event.
This function must be implemented by subclasses.
Implements ActsExamples::IAlgorithm.
Definition at line 44 of file HitsPrinter.cpp.
View newest version in sPHENIX GitHub at line 44 of file HitsPrinter.cpp
References ACTS_ERROR, ACTS_INFO, ACTS_WARNING, Acts::PhysicalConstants::c, clusters, Acts::PlanarModuleCluster::digitizationCells(), ActsExamples::AlgorithmContext::eventNumber, m_cfg(), ActsExamples::makeRange(), Acts::UnitConstants::min, train_ambiguity_solver::pid, ActsExamples::selectLayer(), ActsExamples::selectModule(), ActsExamples::selectVolume(), SUCCESS, and physmon_ckf_tracking::u.
Member Data Documentation
Config ActsExamples::HitsPrinter::m_cfg private
Definition at line 64 of file HitsPrinter.hpp.
View newest version in sPHENIX GitHub at line 64 of file HitsPrinter.hpp
Referenced by config(), and HitsPrinter().
ReadDataHandle<Clusters> ActsExamples::HitsPrinter::m_inputClusters {this, "InputClusters"} private
Definition at line 66 of file HitsPrinter.hpp.
View newest version in sPHENIX GitHub at line 66 of file HitsPrinter.hpp
Referenced by HitsPrinter().
ReadDataHandle<HitIds> ActsExamples::HitsPrinter::m_inputHitIds {this, "InputHitIds"} private
Definition at line 69 of file HitsPrinter.hpp.
View newest version in sPHENIX GitHub at line 69 of file HitsPrinter.hpp
Referenced by HitsPrinter().
ReadDataHandle<HitParticlesMap> ActsExamples::HitsPrinter::m_inputMeasurementParticlesMap private
Initial value:
{
      this, "InputMeasurementParticlesMaps"}
Definition at line 67 of file HitsPrinter.hpp.
View newest version in sPHENIX GitHub at line 67 of file HitsPrinter.hpp
Referenced by HitsPrinter().
The documentation for this class was generated from the following files:
acts/blob/sPHENIX/Examples/Algorithms/Printers/ActsExamples/Printers/HitsPrinter.hpp
acts/blob/sPHENIX/Examples/Algorithms/Printers/ActsExamples/Printers/HitsPrinter.cpp