Analysis Software: Acts::Svg::SurfaceConverter Namespace Reference
Acts::Svg::SurfaceConverter Namespace Reference
Classes
struct Options
Nested Options struct.
Functions
ProtoSurface convert (const GeometryContext &gctx, const Surface &surface, const SurfaceConverter::Options &cOptions)
Function Documentation
Acts::Svg::ProtoSurface Acts::Svg::SurfaceConverter::convert (const GeometryContext & gctx, const Surface & surface, const SurfaceConverter::Options & cOptions)
Convert into a svg::proto surface
Parameters
gtcx is the geometry context of the conversion call
surface is the surface to convert
cOption is the conversion options struct
Returns
a proto surface object
Definition at line 15 of file SurfaceSvgConverter.cpp.
View newest version in sPHENIX GitHub at line 15 of file SurfaceSvgConverter.cpp
References Acts::Surface::bounds(), Acts::Surface::center(), color, Acts::Svg::Style::fillColor, Acts::Svg::Style::fillOpacity, Acts::Svg::Style::highlightColor, Acts::Svg::Style::highlights, Acts::Svg::Style::nSegments, Acts::Surface::polyhedronRepresentation(), pSurface, Acts::Svg::Style::strokeColor, Acts::Svg::Style::strokeWidth, Acts::Svg::SurfaceConverter::Options::style, Acts::Svg::SurfaceConverter::Options::templateSurface, Acts::SurfaceBounds::type(), Acts::Surface::type(), v2, Acts::SurfaceBounds::values(), Acts::PlanarBounds::vertices(), Acts::Polyhedron::vertices, and Acts::AnnulusBounds::vertices().
Referenced by Acts::Svg::SurfaceArrayConverter::convert().