Analysis Software: Acts::PodioUtil Namespace Reference
Acts::PodioUtil Namespace Reference
Classes
class ConversionHelper
Typedefs
using Identifier = uint64_t
Functions
std::shared_ptr< const Surface > convertSurfaceFromPodio (const ConversionHelper &helper, const ActsPodioEdm::Surface &surface)
ActsPodioEdm::Surface convertSurfaceToPodio (const ConversionHelper &helper, const Acts::Surface &surface)
Variables
constexpr Identifier kNoIdentifier = std::numeric_limits<Identifier>::max()
constexpr int kNoSurface = -1
Typedef Documentation
using Acts::PodioUtil::Identifier = typedef uint64_t
Definition at line 25 of file PodioUtil.hpp.
View newest version in sPHENIX GitHub at line 25 of file PodioUtil.hpp
Function Documentation
std::shared_ptr< const Surface > Acts::PodioUtil::convertSurfaceFromPodio (const ConversionHelper & helper, const ActsPodioEdm::Surface & surface)
Definition at line 92 of file PodioUtil.cpp.
View newest version in sPHENIX GitHub at line 92 of file PodioUtil.cpp
References assert, Acts::PodioUtil::ConversionHelper::identifierToSurface(), kNoSurface, N, writeMapConfig::surface, Acts::UnitConstants::T, throw_assert, Acts::Test::transform, and value.
Referenced by BOOST_AUTO_TEST_CASE(), Acts::MutablePodioTrackContainer::getOrCreateSurface(), and Acts::PodioTrackStateContainerBase::populateSurfaceBuffer().
ActsPodioEdm::Surface Acts::PodioUtil::convertSurfaceToPodio (const ConversionHelper & helper, const Acts::Surface & surface)
Definition at line 54 of file PodioUtil.cpp.
View newest version in sPHENIX GitHub at line 54 of file PodioUtil.cpp
References assert, Acts::Surface::associatedDetectorElement(), Acts::Surface::bounds(), gctx, Acts::GeometryObject::geometryId(), i, identifier, kNoIdentifier, Acts::PodioUtil::ConversionHelper::surfaceToIdentifier(), Acts::Surface::transform(), Acts::SurfaceBounds::type(), Acts::Surface::type(), Acts::GeometryIdentifier::value(), Acts::SurfaceBounds::values(), and Acts::Test::values.
Referenced by BOOST_AUTO_TEST_CASE(), Acts::MutablePodioTrackContainer::setReferenceSurface_impl(), and Acts::MutablePodioTrackStateContainer::setReferenceSurface_impl().
Variable Documentation
constexpr Identifier Acts::PodioUtil::kNoIdentifier = std::numeric_limits<Identifier>::max()
Definition at line 26 of file PodioUtil.hpp.
View newest version in sPHENIX GitHub at line 26 of file PodioUtil.hpp
Referenced by Acts::MutablePodioTrackStateContainer::addTrackState_impl(), BOOST_AUTO_TEST_CASE(), convertSurfaceToPodio(), and Acts::PodioTrackStateContainerBase::has_impl().
constexpr int Acts::PodioUtil::kNoSurface = -1
Definition at line 27 of file PodioUtil.hpp.
View newest version in sPHENIX GitHub at line 27 of file PodioUtil.hpp
Referenced by Acts::MutablePodioTrackContainer::addTrack_impl(), Acts::MutablePodioTrackStateContainer::addTrackState_impl(), and convertSurfaceFromPodio().