Analysis Software: SvtxEvalStack Class Reference
SvtxEvalStack Class Reference
#include <coresoftware/blob/master/simulation/g4simulation/g4eval/SvtxEvalStack.h>
Public Member Functions
SvtxEvalStack (PHCompositeNode *topNode)
virtual ~SvtxEvalStack ()
void next_event (PHCompositeNode *topNode)
void do_caching (bool do_cache)
void set_strict (bool strict)
void set_use_initial_vertex (bool use_init_vtx)
void set_use_genfit_vertex (bool use_genfit_vtx)
void set_verbosity (int verbosity)
SvtxVertexEval * get_vertex_eval ()
SvtxTrackEval * get_track_eval ()
SvtxClusterEval * get_cluster_eval ()
SvtxHitEval * get_hit_eval ()
SvtxTruthEval * get_truth_eval ()
unsigned int get_errors ()
void set_track_nodename (const std::string &name)
Private Attributes
SvtxVertexEval _vertexeval
Detailed Description
Definition at line 20 of file SvtxEvalStack.h.
View newest version in sPHENIX GitHub at line 20 of file SvtxEvalStack.h
Constructor & Destructor Documentation
SvtxEvalStack::SvtxEvalStack (PHCompositeNode * topNode)
Definition at line 3 of file SvtxEvalStack.cc.
View newest version in sPHENIX GitHub at line 3 of file SvtxEvalStack.cc
virtual SvtxEvalStack::~SvtxEvalStack () inline virtual
Definition at line 24 of file SvtxEvalStack.h.
View newest version in sPHENIX GitHub at line 24 of file SvtxEvalStack.h
Member Function Documentation
void SvtxEvalStack::do_caching (bool do_cache) inline
Definition at line 27 of file SvtxEvalStack.h.
View newest version in sPHENIX GitHub at line 27 of file SvtxEvalStack.h
References _vertexeval, and SvtxVertexEval::do_caching().
Referenced by JetTruthEval::do_caching().
SvtxClusterEval* SvtxEvalStack::get_cluster_eval () inline
Definition at line 36 of file SvtxEvalStack.h.
View newest version in sPHENIX GitHub at line 36 of file SvtxEvalStack.h
References _vertexeval, and SvtxVertexEval::get_cluster_eval().
Referenced by psTOFTimezeroEval::fillOutputNtuples(), SvtxEvaluatorHaiwang::fillOutputNtuples(), SvtxEvaluator::fillOutputNtuples(), ActsEvaluator::getGlobalTruthHit(), psTOFTimezeroEval::printOutputInfo(), SvtxEvaluatorHaiwang::printOutputInfo(), SvtxEvaluator::printOutputInfo(), HFMLTriggerInterface::process_event(), dNdEtaINTT::process_event(), TrackClusterEvaluator::processRecoTracks(), and TrackClusterEvaluator::processTruthTracks().
unsigned int SvtxEvalStack::get_errors () inline
Definition at line 40 of file SvtxEvalStack.h.
View newest version in sPHENIX GitHub at line 40 of file SvtxEvalStack.h
References _vertexeval, and SvtxVertexEval::get_errors().
Referenced by psTOFTimezeroEval::End(), SvtxEvaluatorHaiwang::End(), SvtxEvaluator::End(), and JetTruthEval::get_errors().
SvtxHitEval* SvtxEvalStack::get_hit_eval () inline
Definition at line 37 of file SvtxEvalStack.h.
View newest version in sPHENIX GitHub at line 37 of file SvtxEvalStack.h
References _vertexeval, and SvtxVertexEval::get_hit_eval().
Referenced by psTOFTimezeroEval::fillOutputNtuples(), SvtxEvaluatorHaiwang::fillOutputNtuples(), SvtxEvaluator::fillOutputNtuples(), HFMLTriggerInterface::process_event(), HFMLTriggerOccupancy::process_event(), TPCMLDataInterface::process_event(), and dNdEtaINTT::process_event().
SvtxTrackEval* SvtxEvalStack::get_track_eval () inline
Definition at line 35 of file SvtxEvalStack.h.
View newest version in sPHENIX GitHub at line 35 of file SvtxEvalStack.h
References _vertexeval, and SvtxVertexEval::get_track_eval().
Referenced by LeptoquarksReco::AddTrackInformation(), JetRecoEval::all_truth_hits(), JetRecoEval::all_truth_particles(), EMCalCalib::eval_photon(), EMCalAna::eval_trk(), ActsEvaluator::evaluateTrackFit(), AnaSvtxTracksForGenFit::fill_tree(), GenFitTrackProp::fill_tree(), psTOFTimezeroEval::fillOutputNtuples(), SvtxEvaluatorHaiwang::fillOutputNtuples(), SvtxEvaluator::fillOutputNtuples(), KFParticle_truthAndDetTools::fillTruthBranch(), JetRecoEval::get_energy_contribution(), AnaTutorial::getTracks(), IsolatedTrackAnalysis::getTracks(), KFParticle_truthAndDetTools::getTruthTrack(), BuildResonanceJetTaggingTree::loopHFHadronic(), psTOFTimezeroEval::printOutputInfo(), SvtxEvaluatorHaiwang::printOutputInfo(), SvtxEvaluator::printOutputInfo(), SvtxSimPerformanceCheckReco::process_event(), TrackingPerformanceCheck::process_event(), STACalorimeterCharacterization::process_event(), SimpleTrackingAnalysis::process_event(), PhotonJet::process_event(), VtxTest::process_event(), TruthConversionEval::process_event(), TrackClusterEvaluator::processRecoTracks(), and TrackClusterEvaluator::processTruthTracks().
SvtxTruthEval* SvtxEvalStack::get_truth_eval () inline
Definition at line 38 of file SvtxEvalStack.h.
View newest version in sPHENIX GitHub at line 38 of file SvtxEvalStack.h
References _vertexeval, and SvtxVertexEval::get_truth_eval().
Referenced by LeptoquarksReco::AddTrackInformation(), JetTruthEval::all_truth_hits(), EMCalCalib::eval_photon(), EMCalAna::eval_trk(), AnaSvtxTracksForGenFit::fill_tree(), ActsEvaluator::fillG4Particle(), SvtxEvaluatorHaiwang::fillOutputNtuples(), psTOFTimezeroEval::fillOutputNtuples(), SvtxEvaluator::fillOutputNtuples(), KFParticle_truthAndDetTools::fillTruthBranch(), KFParticle_truthAndDetTools::getTruthTrack(), psTOFTimezeroEval::printInputInfo(), SvtxEvaluatorHaiwang::printInputInfo(), SvtxEvaluator::printInputInfo(), SvtxEvaluatorHaiwang::printOutputInfo(), psTOFTimezeroEval::printOutputInfo(), SvtxEvaluator::printOutputInfo(), SvtxSimPerformanceCheckReco::process_event(), TrackingPerformanceCheck::process_event(), RecoInfoExport::process_event(), STACalorimeterCharacterization::process_event(), SimpleTrackingAnalysis::process_event(), TPCMLDataInterface::process_event(), dNdEtaINTT::process_event(), TrackClusterEvaluator::processRecoTracks(), and TrackClusterEvaluator::processTruthTracks().
SvtxVertexEval* SvtxEvalStack::get_vertex_eval () inline
Definition at line 34 of file SvtxEvalStack.h.
View newest version in sPHENIX GitHub at line 34 of file SvtxEvalStack.h
References _vertexeval.
Referenced by psTOFTimezeroEval::fillOutputNtuples(), SvtxEvaluatorHaiwang::fillOutputNtuples(), SvtxEvaluator::fillOutputNtuples(), KFParticle_truthAndDetTools::fillTruthBranch(), KFParticle_truthAndDetTools::getTruthTrack(), SvtxSimPerformanceCheckReco::process_event(), and SimpleTrackingAnalysis::process_event().
void SvtxEvalStack::next_event (PHCompositeNode * topNode)
Definition at line 8 of file SvtxEvalStack.cc.
View newest version in sPHENIX GitHub at line 8 of file SvtxEvalStack.cc
References _vertexeval, and SvtxVertexEval::next_event().
Referenced by AnaTutorial::getTracks(), IsolatedTrackAnalysis::getTracks(), KFParticle_truthAndDetTools::getTruthTrack(), BuildResonanceJetTaggingTree::loopHFHadronic(), JetTruthEval::next_event(), ActsEvaluator::next_event(), AnaSvtxTracksForGenFit::process_event(), TracksInJets::process_event(), TrackClusterEvaluator::process_event(), HFMLTriggerOccupancy::process_event(), HFMLTriggerInterface::process_event(), psTOFTimezeroEval::process_event(), SvtxEvaluatorHaiwang::process_event(), TPCMLDataInterface::process_event(), PhotonJet::process_event(), SvtxEvaluator::process_event(), GenFitTrackProp::process_event(), EMCalCalib::process_event(), EMCalAna::process_event(), and dNdEtaINTT::process_event().
void SvtxEvalStack::set_strict (bool strict) inline
Definition at line 28 of file SvtxEvalStack.h.
View newest version in sPHENIX GitHub at line 28 of file SvtxEvalStack.h
References _vertexeval, and SvtxVertexEval::set_strict().
Referenced by EMCalCalib::eval_photon(), EMCalCalib::eval_photon_proj(), EMCalAna::eval_trk(), EMCalAna::eval_trk_proj(), AnaSvtxTracksForGenFit::process_event(), TrackClusterEvaluator::process_event(), HFMLTriggerInterface::process_event(), HFMLTriggerOccupancy::process_event(), psTOFTimezeroEval::process_event(), SvtxEvaluatorHaiwang::process_event(), TPCMLDataInterface::process_event(), SvtxEvaluator::process_event(), EMCalCalib::process_event_MCPhoton(), EMCalAna::process_event_Trk(), EMCalAna::process_event_UpslisonTrig(), and JetTruthEval::set_strict().
void SvtxEvalStack::set_track_nodename (const std::string & name) inline
Definition at line 42 of file SvtxEvalStack.h.
View newest version in sPHENIX GitHub at line 42 of file SvtxEvalStack.h
References _vertexeval, and SvtxVertexEval::set_track_nodename().
Referenced by JetTruthEval::set_track_nodename().
void SvtxEvalStack::set_use_genfit_vertex (bool use_genfit_vtx) inline
Definition at line 31 of file SvtxEvalStack.h.
View newest version in sPHENIX GitHub at line 31 of file SvtxEvalStack.h
References _vertexeval, and SvtxVertexEval::set_use_genfit_vertex().
Referenced by TrackClusterEvaluator::process_event(), TPCMLDataInterface::process_event(), and SvtxEvaluator::process_event().
void SvtxEvalStack::set_use_initial_vertex (bool use_init_vtx) inline
Definition at line 30 of file SvtxEvalStack.h.
View newest version in sPHENIX GitHub at line 30 of file SvtxEvalStack.h
References _vertexeval, and SvtxVertexEval::set_use_initial_vertex().
Referenced by TrackClusterEvaluator::process_event(), TPCMLDataInterface::process_event(), and SvtxEvaluator::process_event().
void SvtxEvalStack::set_verbosity (int verbosity) inline
Definition at line 32 of file SvtxEvalStack.h.
View newest version in sPHENIX GitHub at line 32 of file SvtxEvalStack.h
References _vertexeval, and SvtxVertexEval::set_verbosity().
Referenced by AnaTutorial::getTracks(), AnaSvtxTracksForGenFit::process_event(), TrackClusterEvaluator::process_event(), HFMLTriggerInterface::process_event(), HFMLTriggerOccupancy::process_event(), SvtxEvaluatorHaiwang::process_event(), psTOFTimezeroEval::process_event(), TPCMLDataInterface::process_event(), SvtxEvaluator::process_event(), GenFitTrackProp::process_event(), and JetTruthEval::set_verbosity().
Member Data Documentation
SvtxVertexEval SvtxEvalStack::_vertexeval private
Definition at line 45 of file SvtxEvalStack.h.
View newest version in sPHENIX GitHub at line 45 of file SvtxEvalStack.h
Referenced by do_caching(), get_cluster_eval(), get_errors(), get_hit_eval(), get_track_eval(), get_truth_eval(), get_vertex_eval(), next_event(), set_strict(), set_track_nodename(), set_use_genfit_vertex(), set_use_initial_vertex(), and set_verbosity().
The documentation for this class was generated from the following files:
coresoftware/blob/master/simulation/g4simulation/g4eval/SvtxEvalStack.h
coresoftware/blob/master/simulation/g4simulation/g4eval/SvtxEvalStack.cc