Analysis Software: SvtxEvaluator Class Reference
SvtxEvaluator Class Reference
Compares reconstructed tracks to truth particles.
#include <coresoftware/blob/master/simulation/g4simulation/g4eval/SvtxEvaluator.h>
Public Member Functions
SvtxEvaluator (const std::string &name="SVTXEVALUATOR", const std::string &filename="g4eval.root", const std::string &trackmapname="SvtxTrackMap", unsigned int nlayers_maps=3, unsigned int nlayers_intt=8, unsigned int nlayers_tpc=48, unsigned int nlayers_mms=2)
~SvtxEvaluator () override
int Init (PHCompositeNode *topNode) override
int InitRun (PHCompositeNode *topNode) override
int process_event (PHCompositeNode *topNode) override
int End (PHCompositeNode *topNode) override
Called at the end of all processing.
void set_strict (bool b)
void set_use_initial_vertex (bool use_init_vtx)
void set_use_genfit_vertex (bool use_genfit_vtx)
void do_info_eval (bool b)
void do_vertex_eval (bool b)
void do_gpoint_eval (bool b)
void do_g4hit_eval (bool b)
void do_hit_eval (bool b)
void do_cluster_eval (bool b)
void do_g4cluster_eval (bool b)
void do_gtrack_eval (bool b)
void do_track_eval (bool b)
void do_gseed_eval (bool b)
void do_track_match (bool b)
void do_eval_light (bool b)
void do_vtx_eval_light (bool b)
void scan_for_embedded (bool b)
void scan_for_primaries (bool b)
Public Member Functions inherited from SubsysReco
~SubsysReco () override
virtual int EndRun (const int)
Called at the end of each run.
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
void Print (const std::string &="ALL") const override
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Private Member Functions
TMatrixF calculateClusterError (TrkrCluster *c, float &clusphi)
void get_dca (SvtxTrack *track, GlobalVertexMap *vertexmap, float &dca3dxy, float &dca3dz, float &dca3dxysigma, float &dca3dzsigma)
void fillOutputNtuples (PHCompositeNode *topNode)
dump the evaluator information into ntuple for external analysis
void printInputInfo (PHCompositeNode *topNode)
print out the input object information (debugging upstream components)
void printOutputInfo (PHCompositeNode *topNode)
print out the ancestry information for detailed diagnosis
Private Attributes
unsigned int _ievent = 0
unsigned int _iseed = 0
float m_fSeed = NAN
SvtxEvalStack * _svtxevalstack = nullptr
bool _strict = false
bool _use_initial_vertex = true
bool _use_genfit_vertex = false
unsigned int _errors = 0
bool _do_info_eval = true
bool _do_vertex_eval = true
bool _do_gpoint_eval = true
bool _do_g4hit_eval = true
bool _do_hit_eval = true
bool _do_cluster_eval = true
bool _do_g4cluster_eval = true
bool _do_gtrack_eval = true
bool _do_track_eval = true
bool _do_gseed_eval = false
bool _do_track_match = true
bool _do_eval_light = true
bool _do_vtx_eval_light = true
bool _scan_for_embedded = false
bool _scan_for_primaries = false
unsigned int _nlayers_maps = 3
unsigned int _nlayers_intt = 4
unsigned int _nlayers_tpc = 48
unsigned int _nlayers_mms = 2
TNtuple * _ntp_info = nullptr
TNtuple * _ntp_vertex = nullptr
TNtuple * _ntp_gpoint = nullptr
TNtuple * _ntp_g4hit = nullptr
TNtuple * _ntp_hit = nullptr
TNtuple * _ntp_cluster = nullptr
TNtuple * _ntp_g4cluster = nullptr
TNtuple * _ntp_gtrack = nullptr
TNtuple * _ntp_track = nullptr
TNtuple * _ntp_gseed = nullptr
std::string _filename
std::string _trackmapname
TFile * _tfile = nullptr
PHTimer * _timer = nullptr
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = std::numeric_limits<int>::max() - 10
}
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Detailed Description
Compares reconstructed tracks to truth particles.
Plan: This module will trace the reconstructed tracks back to the greatest contributor Monte Carlo particle and then test one against the other.
Definition at line 38 of file SvtxEvaluator.h.
View newest version in sPHENIX GitHub at line 38 of file SvtxEvaluator.h
Constructor & Destructor Documentation
SvtxEvaluator::SvtxEvaluator (const std::string & name = "SVTXEVALUATOR", const std::string & filename = "g4eval.root", const std::string & trackmapname = "SvtxTrackMap", unsigned int nlayers_maps = 3, unsigned int nlayers_intt = 8, unsigned int nlayers_tpc = 48, unsigned int nlayers_mms = 2)
Definition at line 64 of file SvtxEvaluator.cc.
View newest version in sPHENIX GitHub at line 64 of file SvtxEvaluator.cc
SvtxEvaluator::~SvtxEvaluator () override
Definition at line 79 of file SvtxEvaluator.cc.
View newest version in sPHENIX GitHub at line 79 of file SvtxEvaluator.cc
References _timer.
Member Function Documentation
TMatrixF SvtxEvaluator::calculateClusterError (TrkrCluster * c, float & clusphi) private
Definition at line 4354 of file SvtxEvaluator.cc.
View newest version in sPHENIX GitHub at line 4354 of file SvtxEvaluator.cc
References check_license::err(), and TrkrCluster::getActsLocalError().
void SvtxEvaluator::do_cluster_eval (bool b) inline
Definition at line 64 of file SvtxEvaluator.h.
View newest version in sPHENIX GitHub at line 64 of file SvtxEvaluator.h
References _do_cluster_eval, and KFPMath::b.
Referenced by Fun4All_G4_TPC(), Fun4All_RunNewTruthMatcher(), Svtx_Eval(), and Tracking_Eval().
void SvtxEvaluator::do_eval_light (bool b) inline
Definition at line 71 of file SvtxEvaluator.h.
View newest version in sPHENIX GitHub at line 71 of file SvtxEvaluator.h
References _do_eval_light, and KFPMath::b.
Referenced by Fun4All_G4_TPC(), Fun4All_RunNewTruthMatcher(), and Tracking_Eval().
void SvtxEvaluator::do_g4cluster_eval (bool b) inline
Definition at line 65 of file SvtxEvaluator.h.
View newest version in sPHENIX GitHub at line 65 of file SvtxEvaluator.h
References _do_g4cluster_eval, and KFPMath::b.
void SvtxEvaluator::do_g4hit_eval (bool b) inline
Definition at line 62 of file SvtxEvaluator.h.
View newest version in sPHENIX GitHub at line 62 of file SvtxEvaluator.h
References _do_g4hit_eval, and KFPMath::b.
Referenced by Fun4All_G4_TPC(), Fun4All_RunNewTruthMatcher(), Svtx_Eval(), and Tracking_Eval().
void SvtxEvaluator::do_gpoint_eval (bool b) inline
Definition at line 61 of file SvtxEvaluator.h.
View newest version in sPHENIX GitHub at line 61 of file SvtxEvaluator.h
References _do_gpoint_eval, and KFPMath::b.
Referenced by Fun4All_G4_TPC(), Fun4All_RunNewTruthMatcher(), Svtx_Eval(), and Tracking_Eval().
void SvtxEvaluator::do_gseed_eval (bool b) inline
Definition at line 68 of file SvtxEvaluator.h.
View newest version in sPHENIX GitHub at line 68 of file SvtxEvaluator.h
References _do_gseed_eval, and KFPMath::b.
void SvtxEvaluator::do_gtrack_eval (bool b) inline
Definition at line 66 of file SvtxEvaluator.h.
View newest version in sPHENIX GitHub at line 66 of file SvtxEvaluator.h
References _do_gtrack_eval, and KFPMath::b.
Referenced by Fun4All_RunNewTruthMatcher(), and Tracking_Eval().
void SvtxEvaluator::do_hit_eval (bool b) inline
Definition at line 63 of file SvtxEvaluator.h.
View newest version in sPHENIX GitHub at line 63 of file SvtxEvaluator.h
References _do_hit_eval, and KFPMath::b.
Referenced by Fun4All_G4_TPC(), Fun4All_RunNewTruthMatcher(), Svtx_Eval(), and Tracking_Eval().
void SvtxEvaluator::do_info_eval (bool b) inline
Definition at line 59 of file SvtxEvaluator.h.
View newest version in sPHENIX GitHub at line 59 of file SvtxEvaluator.h
References _do_info_eval, and KFPMath::b.
void SvtxEvaluator::do_track_eval (bool b) inline
Definition at line 67 of file SvtxEvaluator.h.
View newest version in sPHENIX GitHub at line 67 of file SvtxEvaluator.h
References _do_track_eval, and KFPMath::b.
Referenced by Fun4All_RunNewTruthMatcher(), and Tracking_Eval().
void SvtxEvaluator::do_track_match (bool b) inline
Definition at line 70 of file SvtxEvaluator.h.
View newest version in sPHENIX GitHub at line 70 of file SvtxEvaluator.h
References _do_track_match, and KFPMath::b.
Referenced by Fun4All_RunNewTruthMatcher(), and Tracking_Eval().
void SvtxEvaluator::do_vertex_eval (bool b) inline
Definition at line 60 of file SvtxEvaluator.h.
View newest version in sPHENIX GitHub at line 60 of file SvtxEvaluator.h
References _do_vertex_eval, and KFPMath::b.
void SvtxEvaluator::do_vtx_eval_light (bool b) inline
Definition at line 72 of file SvtxEvaluator.h.
View newest version in sPHENIX GitHub at line 72 of file SvtxEvaluator.h
References _do_vtx_eval_light, and KFPMath::b.
Referenced by Fun4All_RunNewTruthMatcher(), and Tracking_Eval().
int SvtxEvaluator::End (PHCompositeNode *) override virtual
Called at the end of all processing.
Reimplemented from SubsysReco.
Definition at line 284 of file SvtxEvaluator.cc.
View newest version in sPHENIX GitHub at line 284 of file SvtxEvaluator.cc
References _errors, _filename, _ievent, _ntp_cluster, _ntp_g4cluster, _ntp_g4hit, _ntp_gpoint, _ntp_gseed, _ntp_gtrack, _ntp_hit, _ntp_info, _ntp_track, _ntp_vertex, _svtxevalstack, _tfile, Fun4AllReturnCodes::EVENT_OK, SvtxEvalStack::get_errors(), and Fun4AllBase::Verbosity().
void SvtxEvaluator::fillOutputNtuples (PHCompositeNode * topNode) private
dump the evaluator information into ntuple for external analysis
this is the global vertex
Definition at line 820 of file SvtxEvaluator.cc.
View newest version in sPHENIX GitHub at line 820 of file SvtxEvaluator.cc
References _do_eval_light, _do_track_match, _do_vtx_eval_light, _ievent, _iseed, _nlayers_intt, _nlayers_maps, _nlayers_mms, _nlayers_tpc, _ntp_cluster, _ntp_g4cluster, _ntp_g4hit, _ntp_gpoint, _ntp_gseed, _ntp_gtrack, _ntp_hit, _ntp_info, _ntp_track, _ntp_vertex, _scan_for_embedded, _scan_for_primaries, _svtxevalstack, _timer, _trackmapname, _use_genfit_vertex, _use_initial_vertex, SvtxClusterEval::all_clusters_from(), SvtxTruthEval::all_truth_clusters(), SvtxTruthEval::all_truth_hits(), SvtxClusterEval::all_truth_particles(), TrackSeed::begin_cluster_keys(), SvtxClusterEval::best_cluster_from(), SvtxTrackEval::best_track_from(), SvtxVertexEval::best_vertex_from(), charge(), clusters, doit(), Acts::UnitConstants::e, efromtruth, TrackSeed::end_cluster_keys(), GlobalVertex::end_vertexes(), ephi, eta, event, GlobalVertex::find_vertexes(), TrkrClusterContainer::findCluster(), g4hitID, PHTimer::get_accumulated_time(), PHG4Hit::get_avg_t(), PHG4Hit::get_avg_x(), PHG4Hit::get_avg_y(), PHG4Hit::get_avg_z(), SvtxTrack::get_charge(), SvtxTrack::get_chisq(), SvtxEvalStack::get_cluster_eval(), ClusterErrorPara::get_clusterv5_modified_error(), SvtxTrack::get_crossing(), TrackAnalysisUtils::get_dca(), PHG4Hit::get_edep(), SvtxTruthEval::get_embed(), SvtxHitEval::get_energy_contribution(), SvtxClusterEval::get_energy_contribution(), SvtxTrack::get_error(), SvtxEvalStack::get_hit_eval(), PHG4Hit::get_hit_id(), PHG4VtxPoint::get_id(), SvtxTrack::get_id(), SvtxTrackEval::get_layer_range_contribution(), SvtxTrackEval::get_nclusters_contribution(), SvtxTrackEval::get_nclusters_contribution_by_layer(), SvtxTrack::get_ndf(), SvtxVertexEval::get_ntracks_contribution(), SvtxTrackEval::get_nwrongclusters_contribution(), SvtxTruthEval::get_outermost_truth_hit(), SvtxTruthEval::get_particle(), TrackSeed::get_phi(), PHG4TpcCylinderGeom::get_phibins(), PHG4TpcCylinderGeom::get_phicenter(), PHG4Particle::get_pid(), PHG4Particle::get_px(), PHG4Hit::get_px(), SvtxTrack::get_px(), PHG4Particle::get_py(), PHG4Hit::get_py(), SvtxTrack::get_py(), PHG4Particle::get_pz(), PHG4Hit::get_pz(), SvtxTrack::get_pz(), TrackSeed::get_qOverR(), SvtxTrack::get_quality(), SvtxTrack::get_silicon_seed(), PHG4VtxPoint::get_t(), TrackSeed::get_theta(), SvtxTrack::get_tpc_seed(), SvtxEvalStack::get_track_eval(), PHG4Particle::get_track_id(), SvtxEvalStack::get_truth_eval(), SvtxTruthEval::get_vertex(), SvtxEvalStack::get_vertex_eval(), SvtxTrack::get_vertex_id(), PHG4VtxPoint::get_x(), PHG4Hit::get_x(), Vertex::get_x(), GlobalVertex::get_x(), SvtxTrack::get_x(), TrackSeed::get_X0(), PHG4VtxPoint::get_y(), PHG4Hit::get_y(), Vertex::get_y(), GlobalVertex::get_y(), SvtxTrack::get_y(), TrackSeed::get_Y0(), PHG4VtxPoint::get_z(), PHG4Hit::get_z(), Vertex::get_z(), GlobalVertex::get_z(), SvtxTrack::get_z(), PHG4TpcCylinderGeom::get_zbins(), PHG4TpcCylinderGeom::get_zcenter(), geta, TrkrHit::getAdc(), TrkrCluster::getAdc(), TrkrDefs::getClusIndex(), TrkrClusterContainer::getClusters(), TrkrCluster::getEdge(), TrkrHit::getEnergy(), ActsGeometry::getGlobalPosition(), TrkrClusterHitAssoc::getHits(), TrkrHitSet::getHits(), TrkrDefs::getHitSetKeyFromClusKey(), TrkrClusterContainer::getHitSetKeys(), TrkrHitSetContainer::getHitSets(), TrkrDefs::getLayer(), PHG4TpcCylinderGeomContainer::GetLayerCellGeom(), TrkrCluster::getMaxAdc(), PHG4TruthInfoContainer::GetNumPrimaryVertexParticles(), TrkrCluster::getOverlap(), TpcDefs::getPad(), PHG4TruthInfoContainer::GetParticleRange(), TrkrCluster::getPhiSize(), PHG4TruthInfoContainer::GetPrimaryParticleRange(), PHG4TruthInfoContainer::GetPrimaryVtxRange(), TpcDefs::getSectorId(), TpcDefs::getSide(), TpcDefs::getTBin(), TrkrCluster::getZSize(), gflavor, gpos, gprimary, gpx, gpy, gpz, gr, gtrackID, gvt, gx, gy, gz, hitID, i, SvtxTruthEval::is_primary(), PHG4TruthInfoContainer::isEmbededVtx(), layer, m_fSeed, Acts::maps, SvtxClusterEval::max_truth_cluster_by_energy(), SvtxHitEval::max_truth_hit_by_energy(), SvtxClusterEval::max_truth_hit_by_energy(), SvtxClusterEval::max_truth_particle_by_cluster_energy(), SvtxTrackEval::max_truth_particle_by_nclusters(), SvtxVertexEval::max_truth_point_by_ntracks(), nbins, ng4hits, nparticles, ntracks, ActsTests::PropagationDatasets::phi, phisize, PHWHERE, Acts::Test::pos, physmon_track_finding_ttbar::pt, physmon_track_finding_ttbar::r, SvtxClusterEval::reco_cluster_from_truth_cluster(), PHTimer::restart(), SvtxTrackMap::size(), TrkrClusterContainer::size(), size, TrackSeed::size_cluster_keys(), Vertex::size_tracks(), PHTimer::stop(), GlobalVertex::SVTX, ActsTests::PropagationDatasets::theta, trackID, testSigmaEff::v, vec, Fun4AllBase::Verbosity(), ActsExamples::HepMC3Event::vertices(), vx, vy, vz, ambiguity_solver_full_chain::x, y, physmon_track_finding_ttbar::z, and zsize.
Referenced by process_event().
void SvtxEvaluator::get_dca (SvtxTrack * track, GlobalVertexMap * vertexmap, float & dca3dxy, float & dca3dz, float & dca3dxysigma, float & dca3dzsigma) private
int SvtxEvaluator::Init (PHCompositeNode *) override virtual
Called during initialization. Typically this is where you can book histograms, and e.g. register them to Fun4AllServer (so they can be output to file using Fun4AllServer::dumpHistos() method).
Reimplemented from SubsysReco.
Definition at line 84 of file SvtxEvaluator.cc.
View newest version in sPHENIX GitHub at line 84 of file SvtxEvaluator.cc
References _do_cluster_eval, _do_g4cluster_eval, _do_g4hit_eval, _do_gpoint_eval, _do_gseed_eval, _do_gtrack_eval, _do_hit_eval, _do_info_eval, _do_track_eval, _do_vertex_eval, _filename, _ievent, _ntp_cluster, _ntp_g4cluster, _ntp_g4hit, _ntp_gpoint, _ntp_gseed, _ntp_gtrack, _ntp_hit, _ntp_info, _ntp_track, _ntp_vertex, _tfile, _timer, Fun4AllReturnCodes::EVENT_OK, and PHTimer::stop().
int SvtxEvaluator::InitRun (PHCompositeNode *) override virtual
Called for first event when run number is known. Typically this is where you may want to fetch data from database, because you know the run number.
Reimplemented from SubsysReco.
Definition at line 219 of file SvtxEvaluator.cc.
View newest version in sPHENIX GitHub at line 219 of file SvtxEvaluator.cc
References Fun4AllReturnCodes::EVENT_OK.
void SvtxEvaluator::printInputInfo (PHCompositeNode * topNode) private
print out the input object information (debugging upstream components)
Definition at line 358 of file SvtxEvaluator.cc.
View newest version in sPHENIX GitHub at line 358 of file SvtxEvaluator.cc
References _ievent, _strict, _svtxevalstack, _trackmapname, _use_genfit_vertex, _use_initial_vertex, SvtxTruthEval::all_truth_hits(), SvtxTrackMap::begin(), SvtxVertexMap::begin(), SvtxTrackMap::end(), SvtxVertexMap::end(), SvtxEvalStack::get_truth_eval(), TrkrClusterContainer::getClusters(), TrkrClusterContainer::getHitSetKeys(), SvtxVertex::identify(), PHG4Hit::identify(), SvtxTrack::identify(), PHWHERE, SvtxTruthEval::set_strict(), SvtxVertexMap::size(), SvtxTrackMap::size(), TrkrClusterContainer::size(), and Fun4AllBase::Verbosity().
Referenced by process_event().
void SvtxEvaluator::printOutputInfo (PHCompositeNode * topNode) private
print out the ancestry information for detailed diagnosis
Definition at line 463 of file SvtxEvaluator.cc.
View newest version in sPHENIX GitHub at line 463 of file SvtxEvaluator.cc
References _ievent, _nlayers_intt, _nlayers_maps, _nlayers_tpc, _svtxevalstack, _trackmapname, _use_genfit_vertex, _use_initial_vertex, SvtxClusterEval::all_clusters_from(), SvtxTrackEval::all_tracks_from(), SvtxTruthEval::all_truth_hits(), SvtxVertexMap::begin(), clusters, distance(), SvtxVertexMap::empty(), SvtxEvalStack::get_cluster_eval(), PHG4Hit::get_hit_id(), SvtxTrackEval::get_nclusters_contribution(), PHG4TpcCylinderGeom::get_phibins(), PHG4Particle::get_px(), PHG4Particle::get_py(), PHG4Particle::get_pz(), SvtxEvalStack::get_track_eval(), PHG4Particle::get_track_id(), PHG4Hit::get_trkid(), SvtxEvalStack::get_truth_eval(), PHG4Particle::get_vtx_id(), PHG4VtxPoint::get_x(), PHG4Hit::get_x(), SvtxVertex::get_x(), PHG4Hit::get_y(), SvtxVertex::get_y(), PHG4Hit::get_z(), SvtxVertex::get_z(), PHG4TpcCylinderGeom::get_zbins(), ActsGeometry::getGlobalPosition(), TrkrHitSetContainer::getHitSets(), TrkrDefs::getLayer(), PHG4TpcCylinderGeomContainer::GetLayerCellGeom(), PHG4TruthInfoContainer::GetPrimaryParticleRange(), PHG4TruthInfoContainer::GetPrimaryVertexIndex(), PHG4TruthInfoContainer::GetPrimaryVtx(), PHG4TruthInfoContainer::GetVtx(), PHG4Particle::identify(), TrkrCluster::identify(), PHG4TruthInfoContainer::isEmbeded(), layer, SvtxClusterEval::max_truth_hit_by_energy(), ng4hits, particle, PHWHERE, SvtxTrackMap::size(), tracks(), Fun4AllBase::Verbosity(), vx, vy, vz, ambiguity_solver_full_chain::x, y, and physmon_track_finding_ttbar::z.
int SvtxEvaluator::process_event (PHCompositeNode *) override virtual
Called for each event. This is where you do the real work.
Reimplemented from SubsysReco.
Definition at line 224 of file SvtxEvaluator.cc.
View newest version in sPHENIX GitHub at line 224 of file SvtxEvaluator.cc
References _ievent, _iseed, _strict, _svtxevalstack, _use_genfit_vertex, _use_initial_vertex, Fun4AllReturnCodes::EVENT_OK, fillOutputNtuples(), PHFlag::FlagExist(), PHFlag::get_IntFlag(), recoConsts::instance(), m_fSeed, SvtxEvalStack::next_event(), printInputInfo(), SvtxEvalStack::set_strict(), SvtxEvalStack::set_use_genfit_vertex(), SvtxEvalStack::set_use_initial_vertex(), SvtxEvalStack::set_verbosity(), and Fun4AllBase::Verbosity().
void SvtxEvaluator::scan_for_embedded (bool b) inline
Definition at line 73 of file SvtxEvaluator.h.
View newest version in sPHENIX GitHub at line 73 of file SvtxEvaluator.h
References _scan_for_embedded, and KFPMath::b.
Referenced by Fun4All_G4_TPC(), Fun4All_RunNewTruthMatcher(), Svtx_Eval(), and Tracking_Eval().
void SvtxEvaluator::scan_for_primaries (bool b) inline
Definition at line 74 of file SvtxEvaluator.h.
View newest version in sPHENIX GitHub at line 74 of file SvtxEvaluator.h
References _scan_for_primaries, and KFPMath::b.
Referenced by Fun4All_RunNewTruthMatcher(), and Tracking_Eval().
void SvtxEvaluator::set_strict (bool b) inline
Definition at line 56 of file SvtxEvaluator.h.
View newest version in sPHENIX GitHub at line 56 of file SvtxEvaluator.h
References _strict, and KFPMath::b.
void SvtxEvaluator::set_use_genfit_vertex (bool use_genfit_vtx) inline
Definition at line 58 of file SvtxEvaluator.h.
View newest version in sPHENIX GitHub at line 58 of file SvtxEvaluator.h
References _use_genfit_vertex.
void SvtxEvaluator::set_use_initial_vertex (bool use_init_vtx) inline
Definition at line 57 of file SvtxEvaluator.h.
View newest version in sPHENIX GitHub at line 57 of file SvtxEvaluator.h
References _use_initial_vertex.
Referenced by Fun4All_RunNewTruthMatcher(), and Tracking_Eval().
Member Data Documentation
bool SvtxEvaluator::_do_cluster_eval = true private
Definition at line 102 of file SvtxEvaluator.h.
View newest version in sPHENIX GitHub at line 102 of file SvtxEvaluator.h
Referenced by do_cluster_eval(), and Init().
bool SvtxEvaluator::_do_eval_light = true private
Definition at line 109 of file SvtxEvaluator.h.
View newest version in sPHENIX GitHub at line 109 of file SvtxEvaluator.h
Referenced by do_eval_light(), and fillOutputNtuples().
bool SvtxEvaluator::_do_g4cluster_eval = true private
Definition at line 103 of file SvtxEvaluator.h.
View newest version in sPHENIX GitHub at line 103 of file SvtxEvaluator.h
Referenced by do_g4cluster_eval(), and Init().
bool SvtxEvaluator::_do_g4hit_eval = true private
Definition at line 100 of file SvtxEvaluator.h.
View newest version in sPHENIX GitHub at line 100 of file SvtxEvaluator.h
Referenced by do_g4hit_eval(), and Init().
bool SvtxEvaluator::_do_gpoint_eval = true private
Definition at line 99 of file SvtxEvaluator.h.
View newest version in sPHENIX GitHub at line 99 of file SvtxEvaluator.h
Referenced by do_gpoint_eval(), and Init().
bool SvtxEvaluator::_do_gseed_eval = false private
Definition at line 106 of file SvtxEvaluator.h.
View newest version in sPHENIX GitHub at line 106 of file SvtxEvaluator.h
Referenced by do_gseed_eval(), and Init().
bool SvtxEvaluator::_do_gtrack_eval = true private
Definition at line 104 of file SvtxEvaluator.h.
View newest version in sPHENIX GitHub at line 104 of file SvtxEvaluator.h
Referenced by do_gtrack_eval(), and Init().
bool SvtxEvaluator::_do_hit_eval = true private
Definition at line 101 of file SvtxEvaluator.h.
View newest version in sPHENIX GitHub at line 101 of file SvtxEvaluator.h
Referenced by do_hit_eval(), and Init().
bool SvtxEvaluator::_do_info_eval = true private
Definition at line 97 of file SvtxEvaluator.h.
View newest version in sPHENIX GitHub at line 97 of file SvtxEvaluator.h
Referenced by do_info_eval(), and Init().
bool SvtxEvaluator::_do_track_eval = true private
Definition at line 105 of file SvtxEvaluator.h.
View newest version in sPHENIX GitHub at line 105 of file SvtxEvaluator.h
Referenced by do_track_eval(), and Init().
bool SvtxEvaluator::_do_track_match = true private
Definition at line 108 of file SvtxEvaluator.h.
View newest version in sPHENIX GitHub at line 108 of file SvtxEvaluator.h
Referenced by do_track_match(), and fillOutputNtuples().
bool SvtxEvaluator::_do_vertex_eval = true private
Definition at line 98 of file SvtxEvaluator.h.
View newest version in sPHENIX GitHub at line 98 of file SvtxEvaluator.h
Referenced by do_vertex_eval(), and Init().
bool SvtxEvaluator::_do_vtx_eval_light = true private
Definition at line 110 of file SvtxEvaluator.h.
View newest version in sPHENIX GitHub at line 110 of file SvtxEvaluator.h
Referenced by do_vtx_eval_light(), and fillOutputNtuples().
unsigned int SvtxEvaluator::_errors = 0 private
Definition at line 95 of file SvtxEvaluator.h.
View newest version in sPHENIX GitHub at line 95 of file SvtxEvaluator.h
Referenced by End().
std::string SvtxEvaluator::_filename private
Definition at line 131 of file SvtxEvaluator.h.
View newest version in sPHENIX GitHub at line 131 of file SvtxEvaluator.h
Referenced by End(), and Init().
unsigned int SvtxEvaluator::_ievent = 0 private
Definition at line 77 of file SvtxEvaluator.h.
View newest version in sPHENIX GitHub at line 77 of file SvtxEvaluator.h
Referenced by End(), fillOutputNtuples(), Init(), printInputInfo(), printOutputInfo(), and process_event().
unsigned int SvtxEvaluator::_iseed = 0 private
Definition at line 78 of file SvtxEvaluator.h.
View newest version in sPHENIX GitHub at line 78 of file SvtxEvaluator.h
Referenced by fillOutputNtuples(), and process_event().
unsigned int SvtxEvaluator::_nlayers_intt = 4 private
Definition at line 115 of file SvtxEvaluator.h.
View newest version in sPHENIX GitHub at line 115 of file SvtxEvaluator.h
Referenced by fillOutputNtuples(), and printOutputInfo().
unsigned int SvtxEvaluator::_nlayers_maps = 3 private
Definition at line 114 of file SvtxEvaluator.h.
View newest version in sPHENIX GitHub at line 114 of file SvtxEvaluator.h
Referenced by fillOutputNtuples(), and printOutputInfo().
unsigned int SvtxEvaluator::_nlayers_mms = 2 private
Definition at line 117 of file SvtxEvaluator.h.
View newest version in sPHENIX GitHub at line 117 of file SvtxEvaluator.h
Referenced by fillOutputNtuples().
unsigned int SvtxEvaluator::_nlayers_tpc = 48 private
Definition at line 116 of file SvtxEvaluator.h.
View newest version in sPHENIX GitHub at line 116 of file SvtxEvaluator.h
Referenced by fillOutputNtuples(), and printOutputInfo().
TNtuple* SvtxEvaluator::_ntp_cluster = nullptr private
Definition at line 124 of file SvtxEvaluator.h.
View newest version in sPHENIX GitHub at line 124 of file SvtxEvaluator.h
Referenced by End(), fillOutputNtuples(), and Init().
TNtuple* SvtxEvaluator::_ntp_g4cluster = nullptr private
Definition at line 125 of file SvtxEvaluator.h.
View newest version in sPHENIX GitHub at line 125 of file SvtxEvaluator.h
Referenced by End(), fillOutputNtuples(), and Init().
TNtuple* SvtxEvaluator::_ntp_g4hit = nullptr private
Definition at line 122 of file SvtxEvaluator.h.
View newest version in sPHENIX GitHub at line 122 of file SvtxEvaluator.h
Referenced by End(), fillOutputNtuples(), and Init().
TNtuple* SvtxEvaluator::_ntp_gpoint = nullptr private
Definition at line 121 of file SvtxEvaluator.h.
View newest version in sPHENIX GitHub at line 121 of file SvtxEvaluator.h
Referenced by End(), fillOutputNtuples(), and Init().
TNtuple* SvtxEvaluator::_ntp_gseed = nullptr private
Definition at line 128 of file SvtxEvaluator.h.
View newest version in sPHENIX GitHub at line 128 of file SvtxEvaluator.h
Referenced by End(), fillOutputNtuples(), and Init().
TNtuple* SvtxEvaluator::_ntp_gtrack = nullptr private
Definition at line 126 of file SvtxEvaluator.h.
View newest version in sPHENIX GitHub at line 126 of file SvtxEvaluator.h
Referenced by End(), fillOutputNtuples(), and Init().
TNtuple* SvtxEvaluator::_ntp_hit = nullptr private
Definition at line 123 of file SvtxEvaluator.h.
View newest version in sPHENIX GitHub at line 123 of file SvtxEvaluator.h
Referenced by End(), fillOutputNtuples(), and Init().
TNtuple* SvtxEvaluator::_ntp_info = nullptr private
Definition at line 119 of file SvtxEvaluator.h.
View newest version in sPHENIX GitHub at line 119 of file SvtxEvaluator.h
Referenced by End(), fillOutputNtuples(), and Init().
TNtuple* SvtxEvaluator::_ntp_track = nullptr private
Definition at line 127 of file SvtxEvaluator.h.
View newest version in sPHENIX GitHub at line 127 of file SvtxEvaluator.h
Referenced by End(), fillOutputNtuples(), and Init().
TNtuple* SvtxEvaluator::_ntp_vertex = nullptr private
Definition at line 120 of file SvtxEvaluator.h.
View newest version in sPHENIX GitHub at line 120 of file SvtxEvaluator.h
Referenced by End(), fillOutputNtuples(), and Init().
bool SvtxEvaluator::_scan_for_embedded = false private
Definition at line 111 of file SvtxEvaluator.h.
View newest version in sPHENIX GitHub at line 111 of file SvtxEvaluator.h
Referenced by fillOutputNtuples(), and scan_for_embedded().
bool SvtxEvaluator::_scan_for_primaries = false private
Definition at line 112 of file SvtxEvaluator.h.
View newest version in sPHENIX GitHub at line 112 of file SvtxEvaluator.h
Referenced by fillOutputNtuples(), and scan_for_primaries().
bool SvtxEvaluator::_strict = false private
Definition at line 92 of file SvtxEvaluator.h.
View newest version in sPHENIX GitHub at line 92 of file SvtxEvaluator.h
Referenced by printInputInfo(), process_event(), and set_strict().
SvtxEvalStack* SvtxEvaluator::_svtxevalstack = nullptr private
Definition at line 81 of file SvtxEvaluator.h.
View newest version in sPHENIX GitHub at line 81 of file SvtxEvaluator.h
Referenced by End(), fillOutputNtuples(), printInputInfo(), printOutputInfo(), and process_event().
TFile* SvtxEvaluator::_tfile = nullptr private
Definition at line 134 of file SvtxEvaluator.h.
View newest version in sPHENIX GitHub at line 134 of file SvtxEvaluator.h
Referenced by End(), and Init().
PHTimer* SvtxEvaluator::_timer = nullptr private
Definition at line 136 of file SvtxEvaluator.h.
View newest version in sPHENIX GitHub at line 136 of file SvtxEvaluator.h
Referenced by fillOutputNtuples(), Init(), and ~SvtxEvaluator().
std::string SvtxEvaluator::_trackmapname private
Definition at line 133 of file SvtxEvaluator.h.
View newest version in sPHENIX GitHub at line 133 of file SvtxEvaluator.h
Referenced by fillOutputNtuples(), printInputInfo(), and printOutputInfo().
bool SvtxEvaluator::_use_genfit_vertex = false private
Definition at line 94 of file SvtxEvaluator.h.
View newest version in sPHENIX GitHub at line 94 of file SvtxEvaluator.h
Referenced by fillOutputNtuples(), printInputInfo(), printOutputInfo(), process_event(), and set_use_genfit_vertex().
bool SvtxEvaluator::_use_initial_vertex = true private
Definition at line 93 of file SvtxEvaluator.h.
View newest version in sPHENIX GitHub at line 93 of file SvtxEvaluator.h
Referenced by fillOutputNtuples(), printInputInfo(), printOutputInfo(), process_event(), and set_use_initial_vertex().
float SvtxEvaluator::m_fSeed = NAN private
Definition at line 79 of file SvtxEvaluator.h.
View newest version in sPHENIX GitHub at line 79 of file SvtxEvaluator.h
Referenced by fillOutputNtuples(), and process_event().
The documentation for this class was generated from the following files:
coresoftware/blob/master/simulation/g4simulation/g4eval/SvtxEvaluator.h
coresoftware/blob/master/simulation/g4simulation/g4eval/SvtxEvaluator.cc