Analysis Software: acts/blob/sPHENIX/Tests/UnitTests/Plugins/ActSVG/DetectorVolumeSvgConverterTests.cpp File Reference
DetectorVolumeSvgConverterTests.cpp File Reference
#include <boost/test/unit_test.hpp>
#include "Acts/Detector/DetectorVolume.hpp"
#include "Acts/Detector/DetectorVolumeBuilder.hpp"
#include "Acts/Detector/LayerStructureBuilder.hpp"
#include "Acts/Detector/PortalGenerators.hpp"
#include "Acts/Detector/VolumeStructureBuilder.hpp"
#include "Acts/Geometry/CylinderVolumeBounds.hpp"
#include "Acts/Geometry/GeometryContext.hpp"
#include "Acts/Navigation/NavigationStateUpdators.hpp"
#include "Acts/Navigation/SurfaceCandidatesUpdators.hpp"
#include "Acts/Plugins/ActSVG/DetectorVolumeSvgConverter.hpp"
#include "Acts/Plugins/ActSVG/IndexedSurfacesSvgConverter.hpp"
#include "Acts/Tests/CommonHelpers/CylindricalTrackingGeometry.hpp"
#include "Acts/Utilities/Enumerate.hpp"
#include "Acts/Utilities/Logger.hpp"
#include <fstream>
#include <memory>
#include <vector>
Functions
BOOST_AUTO_TEST_CASE (TubeCylindricalDetectorVolume)
BOOST_AUTO_TEST_CASE (TubeSectorCylindricalDetectorVolume)
BOOST_AUTO_TEST_CASE (EndcapVolumeWithSurfaces)
BOOST_AUTO_TEST_CASE (BarrelVolumeWithSurfaces)
Variables
Acts::GeometryContext tContext
auto cGeometry = Acts::Test::CylindricalTrackingGeometry(tContext)
auto nominal = Acts::Transform3::Identity()
Function Documentation
BOOST_AUTO_TEST_CASE (TubeCylindricalDetectorVolume)
Definition at line 54 of file DetectorVolumeSvgConverterTests.cpp.
View newest version in sPHENIX GitHub at line 54 of file DetectorVolumeSvgConverterTests.cpp
References color, Acts::Experimental::DetectorVolumeFactory::construct(), Acts::Svg::DetectorVolumeConverter::convert(), Acts::Experimental::defaultPortalGenerator(), Acts::Svg::Style::fillColor, Acts::Svg::Style::fillOpacity, testing::internal::move(), nominal, portalGenerator, Acts::Svg::DetectorVolumeConverter::Options::portalOptions, Acts::Test::red, Acts::Svg::toFile(), Acts::Experimental::tryAllPortals(), physmon_ckf_tracking::u, Acts::Svg::PortalConverter::Options::volumeIndices, zHalfL, and Acts::Svg::View::zr().
BOOST_AUTO_TEST_CASE (TubeSectorCylindricalDetectorVolume)
Definition at line 93 of file DetectorVolumeSvgConverterTests.cpp.
View newest version in sPHENIX GitHub at line 93 of file DetectorVolumeSvgConverterTests.cpp
References Acts::Test::blue, color, Acts::Experimental::DetectorVolumeFactory::construct(), Acts::Svg::DetectorVolumeConverter::convert(), Acts::Experimental::defaultPortalGenerator(), Acts::enumerate(), Acts::Svg::Style::fillColor, Acts::Svg::Style::fillOpacity, testing::internal::move(), nominal, portalGenerator, Acts::Svg::DetectorVolumeConverter::Options::portalOptions, Acts::Svg::toFile(), Acts::Experimental::tryAllPortals(), physmon_ckf_tracking::u, Acts::Svg::PortalConverter::Options::volumeIndices, Acts::Svg::View::xy(), and zHalfL.
BOOST_AUTO_TEST_CASE (EndcapVolumeWithSurfaces)
Definition at line 138 of file DetectorVolumeSvgConverterTests.cpp.
View newest version in sPHENIX GitHub at line 138 of file DetectorVolumeSvgConverterTests.cpp
References Acts::Experimental::DetectorVolumeBuilder::Config::auxiliary, Acts::Experimental::LayerStructureBuilder::Config::auxiliary, Acts::binPhi, Acts::Experimental::VolumeStructureBuilder::Config::boundValues, cGeometry, Acts::Svg::DetectorVolumeConverter::convert(), Acts::Svg::Style::fillColor, Acts::Svg::Style::fillOpacity, Acts::getDefaultLogger(), Acts::Svg::DetectorVolumeConverter::Options::portalOptions, Acts::Svg::SurfaceConverter::Options::style, Acts::Svg::DetectorVolumeConverter::Options::surfaceOptions, Acts::Svg::toFile(), physmon_ckf_tracking::u, Acts::Logging::VERBOSE, Acts::Svg::PortalConverter::Options::volumeIndices, volumes, Acts::Svg::View::xy(), and Acts::Svg::View::zr().
BOOST_AUTO_TEST_CASE (BarrelVolumeWithSurfaces)
Definition at line 207 of file DetectorVolumeSvgConverterTests.cpp.
View newest version in sPHENIX GitHub at line 207 of file DetectorVolumeSvgConverterTests.cpp
References Acts::Experimental::DetectorVolumeBuilder::Config::auxiliary, Acts::Experimental::LayerStructureBuilder::Config::auxiliary, Acts::binPhi, Acts::binZ, Acts::Experimental::VolumeStructureBuilder::Config::boundValues, cGeometry, Acts::Svg::DetectorVolumeConverter::convert(), Acts::Svg::Style::fillColor, Acts::Svg::Style::fillOpacity, Acts::getDefaultLogger(), Acts::Svg::DetectorVolumeConverter::Options::portalOptions, Acts::Svg::SurfaceConverter::Options::style, Acts::Svg::DetectorVolumeConverter::Options::surfaceOptions, Acts::Svg::toFile(), physmon_ckf_tracking::u, Acts::Logging::VERBOSE, Acts::Svg::PortalConverter::Options::volumeIndices, volumes, Acts::Svg::View::xy(), Acts::Svg::View::zphi(), and Acts::Svg::View::zr().
Variable Documentation
auto cGeometry = Acts::Test::CylindricalTrackingGeometry(tContext)
Definition at line 49 of file DetectorVolumeSvgConverterTests.cpp.
View newest version in sPHENIX GitHub at line 49 of file DetectorVolumeSvgConverterTests.cpp
auto nominal = Acts::Transform3::Identity()
Definition at line 50 of file DetectorVolumeSvgConverterTests.cpp.
View newest version in sPHENIX GitHub at line 50 of file DetectorVolumeSvgConverterTests.cpp
Acts::GeometryContext tContext
Definition at line 47 of file DetectorVolumeSvgConverterTests.cpp.
View newest version in sPHENIX GitHub at line 47 of file DetectorVolumeSvgConverterTests.cpp