Analysis Software: Acts::Svg Namespace Reference
Acts::Svg Namespace Reference
Namespaces
namespace DetectorConverter
namespace DetectorVolumeConverter
namespace EventDataConverter
namespace GridConverter
namespace IndexedSurfacesConverter
namespace LayerConverter
namespace PortalConverter
namespace Sheet
namespace SurfaceArrayConverter
namespace SurfaceConverter
namespace TrackingGeometryConverter
namespace TrackingGeometryProjections
namespace View
Classes
struct Style
Typedefs
using ProtoDetector = actsvg::proto::detector< std::vector< Vector3 >>
using ProtoVolume = actsvg::proto::volume< std::vector< Vector3 >>
using ProtoGrid = actsvg::proto::grid
using ProtoSurface = actsvg::proto::surface< std::vector< Vector3 >>
using ProtoIndexedSurfaceGrid = std::tuple< std::vector< ProtoSurface >, ProtoGrid, std::vector< std::vector< std::size_t >>>
using ProtoPortal = actsvg::proto::portal< std::vector< Vector3 >>
using ProtoLink = ProtoPortal::link
using ProtoSurfaces = std::vector< ProtoSurface >
using ProtoAssociations = std::vector< std::vector< size_t >>
Functions
static actsvg::svg::object group (const std::vector< actsvg::svg::object > &objects, const std::string &name)
static actsvg::svg::object measure (ActsScalar xStart, ActsScalar yStart, ActsScalar xEnd, ActsScalar yEnd, const std::string &variable="", ActsScalar value=0., const std::string &unit="")
static actsvg::svg::object axesXY (ActsScalar xMin, ActsScalar xMax, ActsScalar yMin, ActsScalar yMax)
static actsvg::svg::object infoBox (ActsScalar xPos, ActsScalar yPos, const std::string &title, const std::vector< std::string > &info, const Style &infoBoxStyle, const actsvg::svg::object &object)
static void toFile (const std::vector< actsvg::svg::object > &objects, const std::string &fileName)
Variables
static std::array< ActsScalar, 2 > noLimitZ
static std::array< ActsScalar, 2 > noLimitPhi = {-M_PI, M_PI}
Typedef Documentation
using Acts::Svg::ProtoAssociations = typedef std::vector<std::vector<size_t>>
Definition at line 29 of file SurfaceArraySvgConverter.hpp.
View newest version in sPHENIX GitHub at line 29 of file SurfaceArraySvgConverter.hpp
using Acts::Svg::ProtoDetector = typedef actsvg::proto::detector<std::vector<Vector3>>
Definition at line 26 of file DetectorSvgConverter.hpp.
View newest version in sPHENIX GitHub at line 26 of file DetectorSvgConverter.hpp
typedef actsvg::proto::grid Acts::Svg::ProtoGrid
Definition at line 29 of file GridSvgConverter.hpp.
View newest version in sPHENIX GitHub at line 29 of file GridSvgConverter.hpp
using Acts::Svg::ProtoIndexedSurfaceGrid = typedef std::tuple<std::vector<ProtoSurface>, ProtoGrid, std::vector<std::vector<std::size_t>>>
Definition at line 65 of file IndexedSurfacesSvgConverter.hpp.
View newest version in sPHENIX GitHub at line 65 of file IndexedSurfacesSvgConverter.hpp
using Acts::Svg::ProtoLink = typedef ProtoPortal::link
Definition at line 35 of file PortalSvgConverter.hpp.
View newest version in sPHENIX GitHub at line 35 of file PortalSvgConverter.hpp
using Acts::Svg::ProtoPortal = typedef actsvg::proto::portal<std::vector<Vector3>>
Definition at line 34 of file PortalSvgConverter.hpp.
View newest version in sPHENIX GitHub at line 34 of file PortalSvgConverter.hpp
using Acts::Svg::ProtoSurface = typedef actsvg::proto::surface<std::vector<Vector3>>
Definition at line 61 of file IndexedSurfacesSvgConverter.hpp.
View newest version in sPHENIX GitHub at line 61 of file IndexedSurfacesSvgConverter.hpp
using Acts::Svg::ProtoSurfaces = typedef std::vector<ProtoSurface>
Definition at line 27 of file SurfaceArraySvgConverter.hpp.
View newest version in sPHENIX GitHub at line 27 of file SurfaceArraySvgConverter.hpp
using Acts::Svg::ProtoVolume = typedef actsvg::proto::volume<std::vector<Vector3>>
Definition at line 32 of file DetectorVolumeSvgConverter.hpp.
View newest version in sPHENIX GitHub at line 32 of file DetectorVolumeSvgConverter.hpp
Function Documentation
static actsvg::svg::object Acts::Svg::axesXY (ActsScalar xMin, ActsScalar xMax, ActsScalar yMin, ActsScalar yMax) inline static
Parameters
xMin the minimum x value
xMax the maximum x value
yMin the minimum y value
yMax the maximum y value
Returns
an svg object
Definition at line 122 of file SvgUtils.hpp.
View newest version in sPHENIX GitHub at line 122 of file SvgUtils.hpp
Referenced by BOOST_AUTO_TEST_CASE().
static actsvg::svg::object Acts::Svg::group (const std::vector< actsvg::svg::object > & objects, const std::string & name) inline static
Create a group
Parameters
objects are the individual objects to be grouped
name is the name of the group
Returns
a single svg object as a group
Definition at line 70 of file SvgUtils.hpp.
View newest version in sPHENIX GitHub at line 70 of file SvgUtils.hpp
References gr, and perf_headwind::name.
Referenced by Acts::Svg::TrackingGeometryConverter::convert(), and Acts::Svg::TrackingGeometryProjections::convert().
static actsvg::svg::object Acts::Svg::infoBox (ActsScalar xPos, ActsScalar yPos, const std::string & title, const std::vector< std::string > & info, const Style & infoBoxStyle, const actsvg::svg::object & object) inline static
Parameters
xPos the minimum x value
yPos the maximum x value
title the title of the info box
info the text of the info box
infoBoxStyle the style of the info box
object the connected object
Returns
an svg object
Definition at line 140 of file SvgUtils.hpp.
View newest version in sPHENIX GitHub at line 140 of file SvgUtils.hpp
References color, Acts::Svg::Style::fillAndStroke(), Acts::Svg::Style::fontSize, and title.
Referenced by ActsExamples::SvgPointWriter< T, Acc >::writeT().
static actsvg::svg::object Acts::Svg::measure (ActsScalar xStart, ActsScalar yStart, ActsScalar xEnd, ActsScalar yEnd, const std::string & variable = "", ActsScalar value = 0., const std::string & unit = "") inline static
Helper method to a measure
Parameters
xStart the start position x
yStart the start position y
xEnd the end position x
yEnd the end position y
Returns
a single svg object as a measure
Definition at line 89 of file SvgUtils.hpp.
View newest version in sPHENIX GitHub at line 89 of file SvgUtils.hpp
References to_string(), and value.
static void Acts::Svg::toFile (const std::vector< actsvg::svg::object > & objects, const std::string & fileName) inline static
Helper method to write to file
Parameters
objects to be written out
fileName the file name is to be given
Definition at line 167 of file SvgUtils.hpp.
View newest version in sPHENIX GitHub at line 167 of file SvgUtils.hpp
References file, and fout.
Referenced by BOOST_AUTO_TEST_CASE(), ActsExamples::SvgTrackingGeometryWriter::write(), and ActsExamples::SvgPointWriter< T, Acc >::writeT().
Variable Documentation
std::array<ActsScalar, 2> Acts::Svg::noLimitPhi = {-M_PI, M_PI} static
Definition at line 29 of file LayerSvgConverter.hpp.
View newest version in sPHENIX GitHub at line 29 of file LayerSvgConverter.hpp
std::array<ActsScalar, 2> Acts::Svg::noLimitZ static
Initial value:
= {
    std::numeric_limits<Acts::ActsScalar>::lowest(),
    std::numeric_limits<Acts::ActsScalar>::max()}
Definition at line 25 of file LayerSvgConverter.hpp.
View newest version in sPHENIX GitHub at line 25 of file LayerSvgConverter.hpp