Analysis Software: HFTrackEfficiency Class Reference
HFTrackEfficiency Class Reference
#include <coresoftware/blob/master/offline/packages/HFTrackEfficiency/HFTrackEfficiency.h>
Public Member Functions
HFTrackEfficiency (const std::string &name="HFTrackEfficiency")
~HFTrackEfficiency () override
int Init (PHCompositeNode *topNode) override
int process_event (PHCompositeNode *topNode) override
int End (PHCompositeNode *topNode) override
Called at the end of all processing.
void PrintEff ()
void setDFNodeName (const std::string &name)
void setInputTrackMapName (const std::string &what)
void setOutputTrackMapName (const std::string &what)
void writeSelectedTrackMap (bool write)
void writeOutputFile (bool write)
void setOutputFileName (const std::string &what)
void triggerOnDecay (bool trigger)
void setTruthRecoMatchingPercentage (float value)
Public Member Functions inherited from SubsysReco
~SubsysReco () override
virtual int EndRun (const int)
Called at the end of each run.
virtual int InitRun (PHCompositeNode *)
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
void Print (const std::string &="ALL") const override
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Private Types
using Decay = std::vector< std::pair< std::pair< int, int >, int >>
Private Member Functions
bool findTracks (PHCompositeNode *topNode, Decay decay)
void initializeBranches ()
void resetBranches ()
void getDecayDescriptor ()
void getNDaughters ()
std::string getParticleName (const int PDGID)
float getParticleMass (const int PDGID)
Private Attributes
bool m_triggerOnDecay
PHG4TruthInfoContainer * m_truthInfo = nullptr
PHHepMCGenEventMap * m_geneventmap = nullptr
PHHepMCGenEvent * m_genevt = nullptr
PHG4ParticleSvtxMap_v1 * m_dst_truth_reco_map = nullptr
DecayFinderContainer_v1 * m_decayMap = nullptr
std::string m_df_module_name
SvtxTrackMap * m_input_trackMap = nullptr
SvtxTrackMap * m_output_trackMap = nullptr
SvtxTrack * m_dst_track = nullptr
std::string m_input_track_map_node_name
std::string m_output_track_map_node_name
std::string outputNodeName
bool m_write_track_map
std::string m_outfile_name
TFile * m_outfile
TTree * m_tree
bool m_write_nTuple
unsigned int m_counter_allDecays = 0
unsigned int m_counter_acceptedDecays = 0
float m_truthRecoMatchPercent
unsigned int m_nDaughters
std::string m_decay_descriptor
bool m_all_tracks_reconstructed = false
float m_true_mother_mass = std::numeric_limits<float>::quiet_NaN()
float m_reco_mother_mass = std::numeric_limits<float>::quiet_NaN()
float m_true_mother_pT = std::numeric_limits<float>::quiet_NaN()
float m_true_mother_p = std::numeric_limits<float>::quiet_NaN()
float m_true_mother_eta = std::numeric_limits<float>::quiet_NaN()
float m_min_true_track_pT = std::numeric_limits<float>::max()
float m_min_reco_track_pT = std::numeric_limits<float>::max()
float m_max_true_track_pT = -1. * std::numeric_limits<float>::max()
float m_max_reco_track_pT = -1. * std::numeric_limits<float>::max()
bool m_reco_track_exists [m_maxTracks] = {false}
bool m_used_truth_reco_map [m_maxTracks] = {false}
float m_true_track_pT [m_maxTracks] = {std::numeric_limits<float>::quiet_NaN()}
float m_reco_track_pT [m_maxTracks] = {std::numeric_limits<float>::quiet_NaN()}
float m_true_track_eta [m_maxTracks] = {std::numeric_limits<float>::quiet_NaN()}
float m_reco_track_eta [m_maxTracks] = {std::numeric_limits<float>::quiet_NaN()}
float m_true_track_PID [m_maxTracks] = {std::numeric_limits<float>::quiet_NaN()}
float m_reco_track_chi2nDoF [m_maxTracks] = {std::numeric_limits<float>::quiet_NaN()}
int m_reco_track_silicon_seeds [m_maxTracks] = {0}
int m_reco_track_tpc_seeds [m_maxTracks] = {0}
float m_primary_vtx_x = std::numeric_limits<float>::quiet_NaN()
float m_primary_vtx_y = std::numeric_limits<float>::quiet_NaN()
float m_primary_vtx_z = std::numeric_limits<float>::quiet_NaN()
float m_secondary_vtx_x = std::numeric_limits<float>::quiet_NaN()
float m_secondary_vtx_y = std::numeric_limits<float>::quiet_NaN()
float m_secondary_vtx_z = std::numeric_limits<float>::quiet_NaN()
Static Private Attributes
static const int m_maxTracks = 5
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = std::numeric_limits<int>::max() - 10
}
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Detailed Description
Definition at line 58 of file HFTrackEfficiency.h.
View newest version in sPHENIX GitHub at line 58 of file HFTrackEfficiency.h
Member Typedef Documentation
using HFTrackEfficiency::Decay = std::vector<std::pair<std::pair<int, int>, int>> private
Definition at line 83 of file HFTrackEfficiency.h.
View newest version in sPHENIX GitHub at line 83 of file HFTrackEfficiency.h
Constructor & Destructor Documentation
HFTrackEfficiency::HFTrackEfficiency (const std::string & name = "HFTrackEfficiency") explicit
Definition at line 4 of file HFTrackEfficiency.cc.
View newest version in sPHENIX GitHub at line 4 of file HFTrackEfficiency.cc
HFTrackEfficiency::~HFTrackEfficiency () override default
Member Function Documentation
int HFTrackEfficiency::End (PHCompositeNode *) override virtual
Called at the end of all processing.
Reimplemented from SubsysReco.
Definition at line 146 of file HFTrackEfficiency.cc.
View newest version in sPHENIX GitHub at line 146 of file HFTrackEfficiency.cc
References Fun4AllReturnCodes::EVENT_OK, m_counter_allDecays, m_outfile, m_write_nTuple, and PrintEff().
bool HFTrackEfficiency::findTracks (PHCompositeNode * topNode, Decay decay) private
Definition at line 160 of file HFTrackEfficiency.cc.
View newest version in sPHENIX GitHub at line 160 of file HFTrackEfficiency.cc
References assert, parse_cmake_options::begin, Acts::UnitConstants::e, end, PHG4ParticleSvtxMap_v1::get(), SvtxTrackMap::get(), PHHepMCGenEventMap::get(), PHG4Particle::get_barcode(), SvtxTrack::get_chisq(), SvtxTrack::get_eta(), SvtxTrack::get_ndf(), PHG4Particle::get_parent_id(), PHG4Particle::get_pid(), SvtxTrack::get_pt(), PHG4Particle::get_px(), SvtxTrack::get_px(), PHG4Particle::get_py(), SvtxTrack::get_py(), PHG4Particle::get_pz(), SvtxTrack::get_pz(), SvtxTrack::get_silicon_seed(), SvtxTrack::get_tpc_seed(), PHG4Particle::get_track_id(), PHG4Particle::get_vtx_id(), PHG4VtxPoint::get_x(), PHG4VtxPoint::get_y(), PHG4VtxPoint::get_z(), PHHepMCGenEvent::getEvent(), PHG4TruthInfoContainer::GetParticle(), getParticleMass(), PHG4TruthInfoContainer::GetParticleRange(), PHG4TruthInfoContainer::GetVtx(), i, PHG4Particle::identify(), SvtxTrack::identify(), SvtxTrackMap::insertWithKey(), m_dst_track, m_dst_truth_reco_map, m_geneventmap, m_genevt, m_input_trackMap, m_max_reco_track_pT, m_max_true_track_pT, m_min_reco_track_pT, m_min_true_track_pT, m_nDaughters, m_output_trackMap, m_primary_vtx_x, m_primary_vtx_y, m_primary_vtx_z, m_reco_mother_mass, m_reco_track_chi2nDoF, m_reco_track_eta, m_reco_track_exists, m_reco_track_pT, m_reco_track_silicon_seeds, m_reco_track_tpc_seeds, m_secondary_vtx_x, m_secondary_vtx_y, m_secondary_vtx_z, m_true_mother_eta, m_true_mother_mass, m_true_mother_p, m_true_mother_pT, m_true_track_eta, m_true_track_PID, m_true_track_pT, m_truthInfo, m_truthRecoMatchPercent, m_used_truth_reco_map, m_write_track_map, Acts::UnitConstants::min, outputNodeName, TrackSeed::size_cluster_keys(), Fun4AllBase::Verbosity(), and Fun4AllBase::VERBOSITY_MORE.
Referenced by process_event().
void HFTrackEfficiency::getDecayDescriptor () private
Definition at line 471 of file HFTrackEfficiency.cc.
View newest version in sPHENIX GitHub at line 471 of file HFTrackEfficiency.cc
References DecayFinderContainer_v1::begin(), getParticleName(), i, m_decay_descriptor, and m_decayMap.
Referenced by process_event().
void HFTrackEfficiency::getNDaughters () private
Definition at line 483 of file HFTrackEfficiency.cc.
View newest version in sPHENIX GitHub at line 483 of file HFTrackEfficiency.cc
References DecayFinderContainer_v1::begin(), parse_cmake_options::begin, end, i, m_decayMap, and m_nDaughters.
Referenced by process_event().
float HFTrackEfficiency::getParticleMass (const int PDGID) private
Definition at line 503 of file HFTrackEfficiency.cc.
View newest version in sPHENIX GitHub at line 503 of file HFTrackEfficiency.cc
Referenced by findTracks().
std::string HFTrackEfficiency::getParticleName (const int PDGID) private
Definition at line 498 of file HFTrackEfficiency.cc.
View newest version in sPHENIX GitHub at line 498 of file HFTrackEfficiency.cc
Referenced by getDecayDescriptor().
int HFTrackEfficiency::Init (PHCompositeNode *) override virtual
Called during initialization. Typically this is where you can book histograms, and e.g. register them to Fun4AllServer (so they can be output to file using Fun4AllServer::dumpHistos() method).
Reimplemented from SubsysReco.
Definition at line 23 of file HFTrackEfficiency.cc.
View newest version in sPHENIX GitHub at line 23 of file HFTrackEfficiency.cc
References PHCompositeNode::addNode(), Fun4AllReturnCodes::EVENT_OK, PHNodeIterator::findFirst(), m_output_track_map_node_name, m_output_trackMap, m_truthRecoMatchPercent, m_write_track_map, and outputNodeName.
void HFTrackEfficiency::initializeBranches () private
Definition at line 396 of file HFTrackEfficiency.cc.
View newest version in sPHENIX GitHub at line 396 of file HFTrackEfficiency.cc
References m_all_tracks_reconstructed, m_max_reco_track_pT, m_max_true_track_pT, m_min_reco_track_pT, m_min_true_track_pT, m_nDaughters, m_outfile, m_outfile_name, m_primary_vtx_x, m_primary_vtx_y, m_primary_vtx_z, m_reco_mother_mass, m_reco_track_chi2nDoF, m_reco_track_eta, m_reco_track_exists, m_reco_track_pT, m_reco_track_silicon_seeds, m_reco_track_tpc_seeds, m_secondary_vtx_x, m_secondary_vtx_y, m_secondary_vtx_z, m_tree, m_true_mother_eta, m_true_mother_mass, m_true_mother_p, m_true_mother_pT, m_true_track_eta, m_true_track_PID, m_true_track_pT, m_used_truth_reco_map, and to_string().
Referenced by process_event().
void HFTrackEfficiency::PrintEff ()
Definition at line 509 of file HFTrackEfficiency.cc.
View newest version in sPHENIX GitHub at line 509 of file HFTrackEfficiency.cc
References m_counter_acceptedDecays, m_counter_allDecays, and m_decay_descriptor.
Referenced by End().
int HFTrackEfficiency::process_event (PHCompositeNode *) override virtual
Called for each event. This is where you do the real work.
Reimplemented from SubsysReco.
Definition at line 50 of file HFTrackEfficiency.cc.
View newest version in sPHENIX GitHub at line 50 of file HFTrackEfficiency.cc
References Fun4AllReturnCodes::ABORTEVENT, Fun4AllReturnCodes::ABORTRUN, assert, DecayFinderContainer_v1::empty(), Fun4AllReturnCodes::EVENT_OK, PHNodeIterator::findFirst(), findTracks(), getDecayDescriptor(), getNDaughters(), initializeBranches(), m_all_tracks_reconstructed, m_counter_acceptedDecays, m_counter_allDecays, m_decay_descriptor, m_decayMap, m_df_module_name, m_dst_truth_reco_map, m_geneventmap, m_input_track_map_node_name, m_input_trackMap, m_tree, m_triggerOnDecay, m_truthInfo, m_write_nTuple, resetBranches(), Fun4AllBase::Verbosity(), and Fun4AllBase::VERBOSITY_MORE.
void HFTrackEfficiency::resetBranches () private
Definition at line 437 of file HFTrackEfficiency.cc.
View newest version in sPHENIX GitHub at line 437 of file HFTrackEfficiency.cc
References m_all_tracks_reconstructed, m_max_reco_track_pT, m_max_true_track_pT, m_min_reco_track_pT, m_min_true_track_pT, m_nDaughters, m_primary_vtx_x, m_primary_vtx_y, m_primary_vtx_z, m_reco_mother_mass, m_reco_track_chi2nDoF, m_reco_track_eta, m_reco_track_exists, m_reco_track_pT, m_reco_track_silicon_seeds, m_reco_track_tpc_seeds, m_secondary_vtx_x, m_secondary_vtx_y, m_secondary_vtx_z, m_true_mother_eta, m_true_mother_mass, m_true_mother_p, m_true_mother_pT, m_true_track_eta, m_true_track_PID, m_true_track_pT, and m_used_truth_reco_map.
Referenced by process_event().
void HFTrackEfficiency::setDFNodeName (const std::string & name) inline
Definition at line 73 of file HFTrackEfficiency.h.
View newest version in sPHENIX GitHub at line 73 of file HFTrackEfficiency.h
References m_df_module_name, and perf_headwind::name.
Referenced by Fun4All_BHG().
void HFTrackEfficiency::setInputTrackMapName (const std::string & what) inline
Definition at line 74 of file HFTrackEfficiency.h.
View newest version in sPHENIX GitHub at line 74 of file HFTrackEfficiency.h
References m_input_track_map_node_name.
void HFTrackEfficiency::setOutputFileName (const std::string & what) inline
Definition at line 78 of file HFTrackEfficiency.h.
View newest version in sPHENIX GitHub at line 78 of file HFTrackEfficiency.h
References m_outfile_name.
void HFTrackEfficiency::setOutputTrackMapName (const std::string & what) inline
Definition at line 75 of file HFTrackEfficiency.h.
View newest version in sPHENIX GitHub at line 75 of file HFTrackEfficiency.h
References m_output_track_map_node_name.
void HFTrackEfficiency::setTruthRecoMatchingPercentage (float value) inline
Definition at line 80 of file HFTrackEfficiency.h.
View newest version in sPHENIX GitHub at line 80 of file HFTrackEfficiency.h
References m_truthRecoMatchPercent, and value.
void HFTrackEfficiency::triggerOnDecay (bool trigger) inline
Definition at line 79 of file HFTrackEfficiency.h.
View newest version in sPHENIX GitHub at line 79 of file HFTrackEfficiency.h
References m_triggerOnDecay.
Referenced by Fun4All_BHG().
void HFTrackEfficiency::writeOutputFile (bool write) inline
Definition at line 77 of file HFTrackEfficiency.h.
View newest version in sPHENIX GitHub at line 77 of file HFTrackEfficiency.h
References m_write_nTuple, and write().
Referenced by Fun4All_BHG().
void HFTrackEfficiency::writeSelectedTrackMap (bool write) inline
Definition at line 76 of file HFTrackEfficiency.h.
View newest version in sPHENIX GitHub at line 76 of file HFTrackEfficiency.h
References m_write_track_map, and write().
Referenced by Fun4All_BHG().
Member Data Documentation
bool HFTrackEfficiency::m_all_tracks_reconstructed = false private
Definition at line 125 of file HFTrackEfficiency.h.
View newest version in sPHENIX GitHub at line 125 of file HFTrackEfficiency.h
Referenced by initializeBranches(), process_event(), and resetBranches().
unsigned int HFTrackEfficiency::m_counter_acceptedDecays = 0 private
Definition at line 110 of file HFTrackEfficiency.h.
View newest version in sPHENIX GitHub at line 110 of file HFTrackEfficiency.h
Referenced by PrintEff(), and process_event().
unsigned int HFTrackEfficiency::m_counter_allDecays = 0 private
Definition at line 109 of file HFTrackEfficiency.h.
View newest version in sPHENIX GitHub at line 109 of file HFTrackEfficiency.h
Referenced by End(), PrintEff(), and process_event().
std::string HFTrackEfficiency::m_decay_descriptor private
Definition at line 114 of file HFTrackEfficiency.h.
View newest version in sPHENIX GitHub at line 114 of file HFTrackEfficiency.h
Referenced by getDecayDescriptor(), PrintEff(), and process_event().
DecayFinderContainer_v1* HFTrackEfficiency::m_decayMap = nullptr private
Definition at line 93 of file HFTrackEfficiency.h.
View newest version in sPHENIX GitHub at line 93 of file HFTrackEfficiency.h
Referenced by getDecayDescriptor(), getNDaughters(), and process_event().
std::string HFTrackEfficiency::m_df_module_name private
Definition at line 94 of file HFTrackEfficiency.h.
View newest version in sPHENIX GitHub at line 94 of file HFTrackEfficiency.h
Referenced by process_event(), and setDFNodeName().
SvtxTrack* HFTrackEfficiency::m_dst_track = nullptr private
Definition at line 98 of file HFTrackEfficiency.h.
View newest version in sPHENIX GitHub at line 98 of file HFTrackEfficiency.h
Referenced by findTracks().
PHG4ParticleSvtxMap_v1* HFTrackEfficiency::m_dst_truth_reco_map = nullptr private
Definition at line 91 of file HFTrackEfficiency.h.
View newest version in sPHENIX GitHub at line 91 of file HFTrackEfficiency.h
Referenced by findTracks(), and process_event().
PHHepMCGenEventMap* HFTrackEfficiency::m_geneventmap = nullptr private
Definition at line 88 of file HFTrackEfficiency.h.
View newest version in sPHENIX GitHub at line 88 of file HFTrackEfficiency.h
Referenced by findTracks(), and process_event().
PHHepMCGenEvent* HFTrackEfficiency::m_genevt = nullptr private
Definition at line 89 of file HFTrackEfficiency.h.
View newest version in sPHENIX GitHub at line 89 of file HFTrackEfficiency.h
Referenced by findTracks().
std::string HFTrackEfficiency::m_input_track_map_node_name private
Definition at line 99 of file HFTrackEfficiency.h.
View newest version in sPHENIX GitHub at line 99 of file HFTrackEfficiency.h
Referenced by process_event(), and setInputTrackMapName().
SvtxTrackMap* HFTrackEfficiency::m_input_trackMap = nullptr private
Definition at line 96 of file HFTrackEfficiency.h.
View newest version in sPHENIX GitHub at line 96 of file HFTrackEfficiency.h
Referenced by findTracks(), and process_event().
float HFTrackEfficiency::m_max_reco_track_pT = -1. * std::numeric_limits<float>::max() private
Definition at line 134 of file HFTrackEfficiency.h.
View newest version in sPHENIX GitHub at line 134 of file HFTrackEfficiency.h
Referenced by findTracks(), initializeBranches(), and resetBranches().
float HFTrackEfficiency::m_max_true_track_pT = -1. * std::numeric_limits<float>::max() private
Definition at line 133 of file HFTrackEfficiency.h.
View newest version in sPHENIX GitHub at line 133 of file HFTrackEfficiency.h
Referenced by findTracks(), initializeBranches(), and resetBranches().
const int HFTrackEfficiency::m_maxTracks = 5 static private
Definition at line 124 of file HFTrackEfficiency.h.
View newest version in sPHENIX GitHub at line 124 of file HFTrackEfficiency.h
float HFTrackEfficiency::m_min_reco_track_pT = std::numeric_limits<float>::max() private
Definition at line 132 of file HFTrackEfficiency.h.
View newest version in sPHENIX GitHub at line 132 of file HFTrackEfficiency.h
Referenced by findTracks(), initializeBranches(), and resetBranches().
float HFTrackEfficiency::m_min_true_track_pT = std::numeric_limits<float>::max() private
Definition at line 131 of file HFTrackEfficiency.h.
View newest version in sPHENIX GitHub at line 131 of file HFTrackEfficiency.h
Referenced by findTracks(), initializeBranches(), and resetBranches().
unsigned int HFTrackEfficiency::m_nDaughters private
Definition at line 113 of file HFTrackEfficiency.h.
View newest version in sPHENIX GitHub at line 113 of file HFTrackEfficiency.h
Referenced by findTracks(), getNDaughters(), initializeBranches(), and resetBranches().
TFile* HFTrackEfficiency::m_outfile private
Definition at line 105 of file HFTrackEfficiency.h.
View newest version in sPHENIX GitHub at line 105 of file HFTrackEfficiency.h
Referenced by End(), and initializeBranches().
std::string HFTrackEfficiency::m_outfile_name private
Definition at line 104 of file HFTrackEfficiency.h.
View newest version in sPHENIX GitHub at line 104 of file HFTrackEfficiency.h
Referenced by initializeBranches(), and setOutputFileName().
std::string HFTrackEfficiency::m_output_track_map_node_name private
Definition at line 100 of file HFTrackEfficiency.h.
View newest version in sPHENIX GitHub at line 100 of file HFTrackEfficiency.h
Referenced by Init(), and setOutputTrackMapName().
SvtxTrackMap* HFTrackEfficiency::m_output_trackMap = nullptr private
Definition at line 97 of file HFTrackEfficiency.h.
View newest version in sPHENIX GitHub at line 97 of file HFTrackEfficiency.h
Referenced by findTracks(), and Init().
float HFTrackEfficiency::m_primary_vtx_x = std::numeric_limits<float>::quiet_NaN() private
Definition at line 145 of file HFTrackEfficiency.h.
View newest version in sPHENIX GitHub at line 145 of file HFTrackEfficiency.h
Referenced by findTracks(), initializeBranches(), and resetBranches().
float HFTrackEfficiency::m_primary_vtx_y = std::numeric_limits<float>::quiet_NaN() private
Definition at line 146 of file HFTrackEfficiency.h.
View newest version in sPHENIX GitHub at line 146 of file HFTrackEfficiency.h
Referenced by findTracks(), initializeBranches(), and resetBranches().
float HFTrackEfficiency::m_primary_vtx_z = std::numeric_limits<float>::quiet_NaN() private
Definition at line 147 of file HFTrackEfficiency.h.
View newest version in sPHENIX GitHub at line 147 of file HFTrackEfficiency.h
Referenced by findTracks(), initializeBranches(), and resetBranches().
float HFTrackEfficiency::m_reco_mother_mass = std::numeric_limits<float>::quiet_NaN() private
Definition at line 127 of file HFTrackEfficiency.h.
View newest version in sPHENIX GitHub at line 127 of file HFTrackEfficiency.h
Referenced by findTracks(), initializeBranches(), and resetBranches().
float HFTrackEfficiency::m_reco_track_chi2nDoF[m_maxTracks] = {std::numeric_limits<float>::quiet_NaN()} private
Definition at line 142 of file HFTrackEfficiency.h.
View newest version in sPHENIX GitHub at line 142 of file HFTrackEfficiency.h
Referenced by findTracks(), initializeBranches(), and resetBranches().
float HFTrackEfficiency::m_reco_track_eta[m_maxTracks] = {std::numeric_limits<float>::quiet_NaN()} private
Definition at line 140 of file HFTrackEfficiency.h.
View newest version in sPHENIX GitHub at line 140 of file HFTrackEfficiency.h
Referenced by findTracks(), initializeBranches(), and resetBranches().
bool HFTrackEfficiency::m_reco_track_exists[m_maxTracks] = {false} private
Definition at line 135 of file HFTrackEfficiency.h.
View newest version in sPHENIX GitHub at line 135 of file HFTrackEfficiency.h
Referenced by findTracks(), initializeBranches(), and resetBranches().
float HFTrackEfficiency::m_reco_track_pT[m_maxTracks] = {std::numeric_limits<float>::quiet_NaN()} private
Definition at line 138 of file HFTrackEfficiency.h.
View newest version in sPHENIX GitHub at line 138 of file HFTrackEfficiency.h
Referenced by findTracks(), initializeBranches(), and resetBranches().
int HFTrackEfficiency::m_reco_track_silicon_seeds[m_maxTracks] = {0} private
Definition at line 143 of file HFTrackEfficiency.h.
View newest version in sPHENIX GitHub at line 143 of file HFTrackEfficiency.h
Referenced by findTracks(), initializeBranches(), and resetBranches().
int HFTrackEfficiency::m_reco_track_tpc_seeds[m_maxTracks] = {0} private
Definition at line 144 of file HFTrackEfficiency.h.
View newest version in sPHENIX GitHub at line 144 of file HFTrackEfficiency.h
Referenced by findTracks(), initializeBranches(), and resetBranches().
float HFTrackEfficiency::m_secondary_vtx_x = std::numeric_limits<float>::quiet_NaN() private
Definition at line 148 of file HFTrackEfficiency.h.
View newest version in sPHENIX GitHub at line 148 of file HFTrackEfficiency.h
Referenced by findTracks(), initializeBranches(), and resetBranches().
float HFTrackEfficiency::m_secondary_vtx_y = std::numeric_limits<float>::quiet_NaN() private
Definition at line 149 of file HFTrackEfficiency.h.
View newest version in sPHENIX GitHub at line 149 of file HFTrackEfficiency.h
Referenced by findTracks(), initializeBranches(), and resetBranches().
float HFTrackEfficiency::m_secondary_vtx_z = std::numeric_limits<float>::quiet_NaN() private
Definition at line 150 of file HFTrackEfficiency.h.
View newest version in sPHENIX GitHub at line 150 of file HFTrackEfficiency.h
Referenced by findTracks(), initializeBranches(), and resetBranches().
TTree* HFTrackEfficiency::m_tree private
Definition at line 106 of file HFTrackEfficiency.h.
View newest version in sPHENIX GitHub at line 106 of file HFTrackEfficiency.h
Referenced by initializeBranches(), and process_event().
bool HFTrackEfficiency::m_triggerOnDecay private
Definition at line 85 of file HFTrackEfficiency.h.
View newest version in sPHENIX GitHub at line 85 of file HFTrackEfficiency.h
Referenced by process_event(), and triggerOnDecay().
float HFTrackEfficiency::m_true_mother_eta = std::numeric_limits<float>::quiet_NaN() private
Definition at line 130 of file HFTrackEfficiency.h.
View newest version in sPHENIX GitHub at line 130 of file HFTrackEfficiency.h
Referenced by findTracks(), initializeBranches(), and resetBranches().
float HFTrackEfficiency::m_true_mother_mass = std::numeric_limits<float>::quiet_NaN() private
Definition at line 126 of file HFTrackEfficiency.h.
View newest version in sPHENIX GitHub at line 126 of file HFTrackEfficiency.h
Referenced by findTracks(), initializeBranches(), and resetBranches().
float HFTrackEfficiency::m_true_mother_p = std::numeric_limits<float>::quiet_NaN() private
Definition at line 129 of file HFTrackEfficiency.h.
View newest version in sPHENIX GitHub at line 129 of file HFTrackEfficiency.h
Referenced by findTracks(), initializeBranches(), and resetBranches().
float HFTrackEfficiency::m_true_mother_pT = std::numeric_limits<float>::quiet_NaN() private
Definition at line 128 of file HFTrackEfficiency.h.
View newest version in sPHENIX GitHub at line 128 of file HFTrackEfficiency.h
Referenced by findTracks(), initializeBranches(), and resetBranches().
float HFTrackEfficiency::m_true_track_eta[m_maxTracks] = {std::numeric_limits<float>::quiet_NaN()} private
Definition at line 139 of file HFTrackEfficiency.h.
View newest version in sPHENIX GitHub at line 139 of file HFTrackEfficiency.h
Referenced by findTracks(), initializeBranches(), and resetBranches().
float HFTrackEfficiency::m_true_track_PID[m_maxTracks] = {std::numeric_limits<float>::quiet_NaN()} private
Definition at line 141 of file HFTrackEfficiency.h.
View newest version in sPHENIX GitHub at line 141 of file HFTrackEfficiency.h
Referenced by findTracks(), initializeBranches(), and resetBranches().
float HFTrackEfficiency::m_true_track_pT[m_maxTracks] = {std::numeric_limits<float>::quiet_NaN()} private
Definition at line 137 of file HFTrackEfficiency.h.
View newest version in sPHENIX GitHub at line 137 of file HFTrackEfficiency.h
Referenced by findTracks(), initializeBranches(), and resetBranches().
PHG4TruthInfoContainer* HFTrackEfficiency::m_truthInfo = nullptr private
Definition at line 87 of file HFTrackEfficiency.h.
View newest version in sPHENIX GitHub at line 87 of file HFTrackEfficiency.h
Referenced by findTracks(), and process_event().
float HFTrackEfficiency::m_truthRecoMatchPercent private
Definition at line 111 of file HFTrackEfficiency.h.
View newest version in sPHENIX GitHub at line 111 of file HFTrackEfficiency.h
Referenced by findTracks(), Init(), and setTruthRecoMatchingPercentage().
bool HFTrackEfficiency::m_used_truth_reco_map[m_maxTracks] = {false} private
Definition at line 136 of file HFTrackEfficiency.h.
View newest version in sPHENIX GitHub at line 136 of file HFTrackEfficiency.h
Referenced by findTracks(), initializeBranches(), and resetBranches().
bool HFTrackEfficiency::m_write_nTuple private
Definition at line 107 of file HFTrackEfficiency.h.
View newest version in sPHENIX GitHub at line 107 of file HFTrackEfficiency.h
Referenced by End(), process_event(), and writeOutputFile().
bool HFTrackEfficiency::m_write_track_map private
Definition at line 102 of file HFTrackEfficiency.h.
View newest version in sPHENIX GitHub at line 102 of file HFTrackEfficiency.h
Referenced by findTracks(), Init(), and writeSelectedTrackMap().
std::string HFTrackEfficiency::outputNodeName private
Definition at line 101 of file HFTrackEfficiency.h.
View newest version in sPHENIX GitHub at line 101 of file HFTrackEfficiency.h
Referenced by findTracks(), and Init().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/HFTrackEfficiency/HFTrackEfficiency.h
coresoftware/blob/master/offline/packages/HFTrackEfficiency/HFTrackEfficiency.cc