var namespaceFatras =
[
    [ "casts", "df/dab/namespaceFatras_1_1casts.html", "df/dab/namespaceFatras_1_1casts" ],
    [ "detail", "d7/d11/namespaceFatras_1_1detail.html", null ],
    [ "Test", "d2/d76/namespaceFatras_1_1Test.html", "d2/d76/namespaceFatras_1_1Test" ],
    [ "LandauDist", "df/d4b/classFatras_1_1LandauDist.html", "df/d4b/classFatras_1_1LandauDist" ],
    [ "VoidSelector", "de/d3d/structFatras_1_1VoidSelector.html", "de/d3d/structFatras_1_1VoidSelector" ],
    [ "Interactor", "dd/df1/structFatras_1_1Interactor.html", "dd/df1/structFatras_1_1Interactor" ],
    [ "PhysicsList", "db/deb/structFatras_1_1PhysicsList.html", "db/deb/structFatras_1_1PhysicsList" ],
    [ "Process", "db/d7c/structFatras_1_1Process.html", "db/d7c/structFatras_1_1Process" ],
    [ "SelectorListAXOR", "d0/da5/structFatras_1_1SelectorListAXOR.html", "d0/da5/structFatras_1_1SelectorListAXOR" ],
    [ "VoidDetector", "df/dd9/structFatras_1_1VoidDetector.html", null ],
    [ "Simulator", "d0/d3f/structFatras_1_1Simulator.html", "d0/d3f/structFatras_1_1Simulator" ],
    [ "BetheBloch", "d6/d6b/structFatras_1_1BetheBloch.html", "d6/d6b/structFatras_1_1BetheBloch" ],
    [ "BetheHeitler", "d5/d16/structFatras_1_1BetheHeitler.html", "d5/d16/structFatras_1_1BetheHeitler" ],
    [ "ParametricNuclearInt", "d3/d89/structFatras_1_1ParametricNuclearInt.html", "d3/d89/structFatras_1_1ParametricNuclearInt" ],
    [ "GaussianMixture", "d4/d95/structFatras_1_1GaussianMixture.html", "d4/d95/structFatras_1_1GaussianMixture" ],
    [ "GeneralMixture", "d5/dde/structFatras_1_1GeneralMixture.html", "d5/dde/structFatras_1_1GeneralMixture" ],
    [ "Highland", "d5/d31/structFatras_1_1Highland.html", "d5/d31/structFatras_1_1Highland" ],
    [ "Scattering", "dd/d96/structFatras_1_1Scattering.html", "dd/d96/structFatras_1_1Scattering" ],
    [ "ChargedSelector", "de/d06/structFatras_1_1ChargedSelector.html", "de/d06/structFatras_1_1ChargedSelector" ],
    [ "NeutralSelector", "d1/d24/structFatras_1_1NeutralSelector.html", "d1/d24/structFatras_1_1NeutralSelector" ],
    [ "PositiveSelector", "d6/d8b/structFatras_1_1PositiveSelector.html", "d6/d8b/structFatras_1_1PositiveSelector" ],
    [ "NegativeSelector", "dc/def/structFatras_1_1NegativeSelector.html", "dc/def/structFatras_1_1NegativeSelector" ],
    [ "X0Limit", "d7/d1c/structFatras_1_1X0Limit.html", "d7/d1c/structFatras_1_1X0Limit" ],
    [ "L0Limit", "dc/d80/structFatras_1_1L0Limit.html", "dc/d80/structFatras_1_1L0Limit" ],
    [ "AbsPdgSelector", "da/d94/structFatras_1_1AbsPdgSelector.html", "da/d94/structFatras_1_1AbsPdgSelector" ],
    [ "PdgSelector", "d8/d69/structFatras_1_1PdgSelector.html", "d8/d69/structFatras_1_1PdgSelector" ],
    [ "AbsPdgExcluder", "d3/d2b/structFatras_1_1AbsPdgExcluder.html", "d3/d2b/structFatras_1_1AbsPdgExcluder" ],
    [ "PdgExcluder", "d5/d18/structFatras_1_1PdgExcluder.html", "d5/d18/structFatras_1_1PdgExcluder" ],
    [ "Min", "d9/d9f/structFatras_1_1Min.html", "d9/d9f/structFatras_1_1Min" ],
    [ "Max", "df/d9e/structFatras_1_1Max.html", "df/d9e/structFatras_1_1Max" ],
    [ "Range", "d8/d01/structFatras_1_1Range.html", "d8/d01/structFatras_1_1Range" ]
];