Analysis Software: GPUTPCTrackLinearisation Class Reference
GPUTPCTrackLinearisation Class Reference
#include <coresoftware/blob/master/offline/packages/trackreco/GPUTPCTrackLinearisation.h>
Public Member Functions
GPUTPCTrackLinearisation ()
GPUTPCTrackLinearisation (double SinPhi1, double CosPhi1, double DzDs1, double QPt1)
GPUTPCTrackLinearisation (const GPUTPCTrackParam &t)
void Set (double SinPhi1, double CosPhi1, double DzDs1, double QPt1)
double SinPhi () const
double CosPhi () const
double DzDs () const
double QPt () const
double GetSinPhi () const
double GetCosPhi () const
double GetDzDs () const
double GetQPt () const
void SetSinPhi (double v)
void SetCosPhi (double v)
void SetDzDs (double v)
void SetQPt (double v)
Private Attributes
double mSinPhi
double mCosPhi
double mDzDs
double mQPt
Detailed Description
GPUTPCTrackLinearisation class describes the parameters which are used to linearise the transport equations for the track trajectory.
The class is used during track (re)fit, when the AliHLTTPCTrackParam track is only partially fitted, and there is some apriory knowledge about trajectory. This apriory knowledge is used to linearise the transport equations.
In case the track is fully fitted, the best linearisation point is the track trajectory itself (GPUTPCTrackLinearisation = AliHLTTPCTrackParam).
Definition at line 33 of file GPUTPCTrackLinearisation.h.
View newest version in sPHENIX GitHub at line 33 of file GPUTPCTrackLinearisation.h
Constructor & Destructor Documentation
GPUTPCTrackLinearisation::GPUTPCTrackLinearisation () inline
Definition at line 36 of file GPUTPCTrackLinearisation.h.
View newest version in sPHENIX GitHub at line 36 of file GPUTPCTrackLinearisation.h
GPUTPCTrackLinearisation::GPUTPCTrackLinearisation (double SinPhi1, double CosPhi1, double DzDs1, double QPt1) inline
Definition at line 37 of file GPUTPCTrackLinearisation.h.
View newest version in sPHENIX GitHub at line 37 of file GPUTPCTrackLinearisation.h
GPUTPCTrackLinearisation::GPUTPCTrackLinearisation (const GPUTPCTrackParam & t) inline
Definition at line 65 of file GPUTPCTrackLinearisation.h.
View newest version in sPHENIX GitHub at line 65 of file GPUTPCTrackLinearisation.h
References GPUCA_MAX_SIN_PHI, mCosPhi, mSinPhi, and GPUTPCTrackParam::SignCosPhi().
Member Function Documentation
double GPUTPCTrackLinearisation::CosPhi () const inline
Definition at line 44 of file GPUTPCTrackLinearisation.h.
View newest version in sPHENIX GitHub at line 44 of file GPUTPCTrackLinearisation.h
References mCosPhi.
Referenced by GPUTPCTrackParam::Rotate(), and GPUTPCTrackParam::TransportToX().
double GPUTPCTrackLinearisation::DzDs () const inline
Definition at line 45 of file GPUTPCTrackLinearisation.h.
View newest version in sPHENIX GitHub at line 45 of file GPUTPCTrackLinearisation.h
References mDzDs.
Referenced by GPUTPCTrackParam::TransportToX().
double GPUTPCTrackLinearisation::GetCosPhi () const inline
Definition at line 49 of file GPUTPCTrackLinearisation.h.
View newest version in sPHENIX GitHub at line 49 of file GPUTPCTrackLinearisation.h
References mCosPhi.
double GPUTPCTrackLinearisation::GetDzDs () const inline
Definition at line 50 of file GPUTPCTrackLinearisation.h.
View newest version in sPHENIX GitHub at line 50 of file GPUTPCTrackLinearisation.h
References mDzDs.
double GPUTPCTrackLinearisation::GetQPt () const inline
Definition at line 51 of file GPUTPCTrackLinearisation.h.
View newest version in sPHENIX GitHub at line 51 of file GPUTPCTrackLinearisation.h
References mQPt.
double GPUTPCTrackLinearisation::GetSinPhi () const inline
Definition at line 48 of file GPUTPCTrackLinearisation.h.
View newest version in sPHENIX GitHub at line 48 of file GPUTPCTrackLinearisation.h
References mSinPhi.
double GPUTPCTrackLinearisation::QPt () const inline
Definition at line 46 of file GPUTPCTrackLinearisation.h.
View newest version in sPHENIX GitHub at line 46 of file GPUTPCTrackLinearisation.h
References mQPt.
Referenced by GPUTPCTrackParam::TransportToX().
void GPUTPCTrackLinearisation::Set (double SinPhi1, double CosPhi1, double DzDs1, double QPt1) inline
Definition at line 78 of file GPUTPCTrackLinearisation.h.
View newest version in sPHENIX GitHub at line 78 of file GPUTPCTrackLinearisation.h
References SetCosPhi(), SetDzDs(), SetQPt(), and SetSinPhi().
void GPUTPCTrackLinearisation::SetCosPhi (double v) inline
Definition at line 54 of file GPUTPCTrackLinearisation.h.
View newest version in sPHENIX GitHub at line 54 of file GPUTPCTrackLinearisation.h
References mCosPhi, and testSigmaEff::v.
Referenced by GPUTPCTrackParam::Rotate(), Set(), and GPUTPCTrackParam::TransportToX().
void GPUTPCTrackLinearisation::SetDzDs (double v) inline
Definition at line 55 of file GPUTPCTrackLinearisation.h.
View newest version in sPHENIX GitHub at line 55 of file GPUTPCTrackLinearisation.h
References mDzDs, and testSigmaEff::v.
Referenced by Set().
void GPUTPCTrackLinearisation::SetQPt (double v) inline
Definition at line 56 of file GPUTPCTrackLinearisation.h.
View newest version in sPHENIX GitHub at line 56 of file GPUTPCTrackLinearisation.h
References mQPt, and testSigmaEff::v.
Referenced by Set().
void GPUTPCTrackLinearisation::SetSinPhi (double v) inline
Definition at line 53 of file GPUTPCTrackLinearisation.h.
View newest version in sPHENIX GitHub at line 53 of file GPUTPCTrackLinearisation.h
References mSinPhi, and testSigmaEff::v.
Referenced by GPUTPCTrackParam::Rotate(), Set(), and GPUTPCTrackParam::TransportToX().
double GPUTPCTrackLinearisation::SinPhi () const inline
Definition at line 43 of file GPUTPCTrackLinearisation.h.
View newest version in sPHENIX GitHub at line 43 of file GPUTPCTrackLinearisation.h
References mSinPhi.
Referenced by GPUTPCTrackParam::Rotate(), and GPUTPCTrackParam::TransportToX().
Member Data Documentation
double GPUTPCTrackLinearisation::mCosPhi private
Definition at line 60 of file GPUTPCTrackLinearisation.h.
View newest version in sPHENIX GitHub at line 60 of file GPUTPCTrackLinearisation.h
Referenced by CosPhi(), GetCosPhi(), GPUTPCTrackLinearisation(), and SetCosPhi().
double GPUTPCTrackLinearisation::mDzDs private
Definition at line 61 of file GPUTPCTrackLinearisation.h.
View newest version in sPHENIX GitHub at line 61 of file GPUTPCTrackLinearisation.h
Referenced by DzDs(), GetDzDs(), and SetDzDs().
double GPUTPCTrackLinearisation::mQPt private
Definition at line 62 of file GPUTPCTrackLinearisation.h.
View newest version in sPHENIX GitHub at line 62 of file GPUTPCTrackLinearisation.h
Referenced by GetQPt(), QPt(), and SetQPt().
double GPUTPCTrackLinearisation::mSinPhi private
Definition at line 59 of file GPUTPCTrackLinearisation.h.
View newest version in sPHENIX GitHub at line 59 of file GPUTPCTrackLinearisation.h
Referenced by GetSinPhi(), GPUTPCTrackLinearisation(), SetSinPhi(), and SinPhi().
The documentation for this class was generated from the following file:
coresoftware/blob/master/offline/packages/trackreco/GPUTPCTrackLinearisation.h