Analysis Software: FluidcellStatistic Class Reference
FluidcellStatistic Class Reference
#include <JETSCAPE/blob/main/external_packages/hydro_from_external_file/FluidcellStatistic.h>
Public Member Functions
FluidcellStatistic (void *hydroinfo_ptr_in, ParameterReader *paraRdr_in)
~FluidcellStatistic ()
void checkFreezeoutSurface (double Tdec)
double compute_local_expansion_rate (double tau_local, double x_local, double y_local)
void output_momentum_anisotropy_vs_tau ()
void output_temperature_vs_tau ()
void output_flowvelocity_vs_tau ()
void output_temperature_vs_avg_utau ()
void outputTempasTauvsX ()
void outputKnudersonNumberasTauvsX ()
void outputinverseReynoldsNumberasTauvsX ()
void outputBulkinverseReynoldsNumberasTauvsX ()
void analysis_hydro_volume_for_photon (double T_cut)
double calculate_spacetime_4volume (double T_cut)
double calculate_average_tau (double T_cut)
double calculate_average_temperature4 (double T_cut)
double calculate_average_integrated_photonRate_parameterization (double T_cut)
double calculate_hypersurface_3volume (double T_cut)
Private Attributes
int hydro_type
Hydroinfo_MUSIC * hydroinfo_MUSIC_ptr
ParameterReader * paraRdr
double T_dec
double hbarC
double grid_dt
double grid_dx
double grid_dy
double grid_tau0
double grid_tauf
double grid_x0
double grid_y0
Detailed Description
Definition at line 27 of file FluidcellStatistic.h.
View newest version in sPHENIX GitHub at line 27 of file FluidcellStatistic.h
Constructor & Destructor Documentation
FluidcellStatistic::FluidcellStatistic (void * hydroinfo_ptr_in, ParameterReader * paraRdr_in)
Definition at line 15 of file FluidcellStatistic.cpp.
View newest version in sPHENIX GitHub at line 15 of file FluidcellStatistic.cpp
References ParameterReader::getVal(), and Jetscape::hbarC.
FluidcellStatistic::~FluidcellStatistic ()
Definition at line 47 of file FluidcellStatistic.cpp.
View newest version in sPHENIX GitHub at line 47 of file FluidcellStatistic.cpp
Member Function Documentation
void FluidcellStatistic::analysis_hydro_volume_for_photon (double T_cut)
Definition at line 629 of file FluidcellStatistic.cpp.
View newest version in sPHENIX GitHub at line 629 of file FluidcellStatistic.cpp
References of, and check_smearing_config::output.
Referenced by main().
double FluidcellStatistic::calculate_average_integrated_photonRate_parameterization (double T_cut)
Definition at line 786 of file FluidcellStatistic.cpp.
View newest version in sPHENIX GitHub at line 786 of file FluidcellStatistic.cpp
References i, j, nx, ny, and hydrofluidCell::temperature.
double FluidcellStatistic::calculate_average_tau (double T_cut)
Definition at line 691 of file FluidcellStatistic.cpp.
View newest version in sPHENIX GitHub at line 691 of file FluidcellStatistic.cpp
References i, j, nx, ny, and hydrofluidCell::temperature.
double FluidcellStatistic::calculate_average_temperature4 (double T_cut)
Definition at line 738 of file FluidcellStatistic.cpp.
View newest version in sPHENIX GitHub at line 738 of file FluidcellStatistic.cpp
References i, j, nx, ny, and hydrofluidCell::temperature.
double FluidcellStatistic::calculate_hypersurface_3volume (double T_cut)
Definition at line 841 of file FluidcellStatistic.cpp.
View newest version in sPHENIX GitHub at line 841 of file FluidcellStatistic.cpp
References SurfaceFinder::Find_full_hypersurface(), surf(), Acts::UnitConstants::T, tau, vx, vy, ambiguity_solver_full_chain::x, and y.
double FluidcellStatistic::calculate_spacetime_4volume (double T_cut)
Definition at line 646 of file FluidcellStatistic.cpp.
View newest version in sPHENIX GitHub at line 646 of file FluidcellStatistic.cpp
References i, j, nx, ny, and hydrofluidCell::temperature.
void FluidcellStatistic::checkFreezeoutSurface (double Tdec)
Definition at line 49 of file FluidcellStatistic.cpp.
View newest version in sPHENIX GitHub at line 49 of file FluidcellStatistic.cpp
References release::app, i, j, nx, ny, check_smearing_config::output, and hydrofluidCell::temperature.
double FluidcellStatistic::compute_local_expansion_rate (double tau_local, double x_local, double y_local)
Definition at line 448 of file FluidcellStatistic.cpp.
View newest version in sPHENIX GitHub at line 448 of file FluidcellStatistic.cpp
References ActsTests::PropagationDatasets::theta, hydrofluidCell::vx, and hydrofluidCell::vy.
void FluidcellStatistic::output_flowvelocity_vs_tau ()
Definition at line 143 of file FluidcellStatistic.cpp.
View newest version in sPHENIX GitHub at line 143 of file FluidcellStatistic.cpp
References release::app, test_fpe::count, i, it, j, nx, ny, check_smearing_config::output, hydrofluidCell::temperature, ActsTests::PropagationDatasets::theta, hydrofluidCell::vx, and hydrofluidCell::vy.
Referenced by main().
void FluidcellStatistic::output_momentum_anisotropy_vs_tau ()
Definition at line 297 of file FluidcellStatistic.cpp.
View newest version in sPHENIX GitHub at line 297 of file FluidcellStatistic.cpp
References Acts::UnitConstants::e, hydrofluidCell::ed, i, it, j, nx, ny, check_smearing_config::output, hydrofluidCell::pi, hydrofluidCell::pressure, hydrofluidCell::temperature, hydrofluidCell::vx, and hydrofluidCell::vy.
void FluidcellStatistic::output_temperature_vs_avg_utau ()
Definition at line 208 of file FluidcellStatistic.cpp.
View newest version in sPHENIX GitHub at line 208 of file FluidcellStatistic.cpp
References Acts::UnitConstants::e, i, it, j, nx, ny, check_smearing_config::output, hydrofluidCell::temperature, hydrofluidCell::vx, and hydrofluidCell::vy.
Referenced by main().
void FluidcellStatistic::output_temperature_vs_tau ()
Definition at line 86 of file FluidcellStatistic.cpp.
View newest version in sPHENIX GitHub at line 86 of file FluidcellStatistic.cpp
References i, it, j, nx, ny, check_smearing_config::output, and hydrofluidCell::temperature.
void FluidcellStatistic::outputBulkinverseReynoldsNumberasTauvsX ()
Definition at line 589 of file FluidcellStatistic.cpp.
View newest version in sPHENIX GitHub at line 589 of file FluidcellStatistic.cpp
References hydrofluidCell::bulkPi, i, nx, check_smearing_config::output, and hydrofluidCell::pressure.
void FluidcellStatistic::outputinverseReynoldsNumberasTauvsX ()
Definition at line 530 of file FluidcellStatistic.cpp.
View newest version in sPHENIX GitHub at line 530 of file FluidcellStatistic.cpp
References Acts::UnitConstants::e, hydrofluidCell::ed, i, Acts::Logging::MAX, nx, check_smearing_config::output, hydrofluidCell::pi, and hydrofluidCell::pressure.
Referenced by main().
void FluidcellStatistic::outputKnudersonNumberasTauvsX ()
Definition at line 401 of file FluidcellStatistic.cpp.
View newest version in sPHENIX GitHub at line 401 of file FluidcellStatistic.cpp
References Acts::UnitConstants::e, eps, Jetscape::hbarC, i, nx, check_smearing_config::output, hydrofluidCell::temperature, and ActsTests::PropagationDatasets::theta.
Referenced by main().
void FluidcellStatistic::outputTempasTauvsX ()
Definition at line 358 of file FluidcellStatistic.cpp.
View newest version in sPHENIX GitHub at line 358 of file FluidcellStatistic.cpp
References i, nx, check_smearing_config::output, and hydrofluidCell::temperature.
Referenced by main().
Member Data Documentation
double FluidcellStatistic::grid_dt private
Definition at line 37 of file FluidcellStatistic.h.
View newest version in sPHENIX GitHub at line 37 of file FluidcellStatistic.h
double FluidcellStatistic::grid_dx private
Definition at line 37 of file FluidcellStatistic.h.
View newest version in sPHENIX GitHub at line 37 of file FluidcellStatistic.h
double FluidcellStatistic::grid_dy private
Definition at line 37 of file FluidcellStatistic.h.
View newest version in sPHENIX GitHub at line 37 of file FluidcellStatistic.h
double FluidcellStatistic::grid_tau0 private
Definition at line 38 of file FluidcellStatistic.h.
View newest version in sPHENIX GitHub at line 38 of file FluidcellStatistic.h
double FluidcellStatistic::grid_tauf private
Definition at line 38 of file FluidcellStatistic.h.
View newest version in sPHENIX GitHub at line 38 of file FluidcellStatistic.h
double FluidcellStatistic::grid_x0 private
Definition at line 39 of file FluidcellStatistic.h.
View newest version in sPHENIX GitHub at line 39 of file FluidcellStatistic.h
double FluidcellStatistic::grid_y0 private
Definition at line 39 of file FluidcellStatistic.h.
View newest version in sPHENIX GitHub at line 39 of file FluidcellStatistic.h
double FluidcellStatistic::hbarC private
Definition at line 36 of file FluidcellStatistic.h.
View newest version in sPHENIX GitHub at line 36 of file FluidcellStatistic.h
int FluidcellStatistic::hydro_type private
Definition at line 29 of file FluidcellStatistic.h.
View newest version in sPHENIX GitHub at line 29 of file FluidcellStatistic.h
Hydroinfo_MUSIC* FluidcellStatistic::hydroinfo_MUSIC_ptr private
Definition at line 33 of file FluidcellStatistic.h.
View newest version in sPHENIX GitHub at line 33 of file FluidcellStatistic.h
ParameterReader* FluidcellStatistic::paraRdr private
Definition at line 34 of file FluidcellStatistic.h.
View newest version in sPHENIX GitHub at line 34 of file FluidcellStatistic.h
double FluidcellStatistic::T_dec private
Definition at line 35 of file FluidcellStatistic.h.
View newest version in sPHENIX GitHub at line 35 of file FluidcellStatistic.h
The documentation for this class was generated from the following files:
JETSCAPE/blob/main/external_packages/hydro_from_external_file/FluidcellStatistic.h
JETSCAPE/blob/main/external_packages/hydro_from_external_file/FluidcellStatistic.cpp