Analysis Software: analysis/blob/master/EMCal-analysis/ThicknessScan/ThicknessScan.m File Reference
ThicknessScan.m File Reference
Functions
"/control/matScan/scan" ApplyCommand ()
while ischar (tline)%disp(tline)[A
Data (i,:)
elseif (strncmpi(tline,'ave.', 5)) disp(tline) end tline
end fclose (fid)
assert (i-1==n_scan *n_scan)
figure ('name','2D','PaperPositionMode','auto',... 'position',[100, 0, 1900, 1000])
subplot (1, 2, 1)
surf (Eta, Phi_Rad, x0)
xlabel ('\eta','FontSize', 18)
ylabel ('\phi[rad]','FontSize', 18)
zlabel ('Radiatiaon Length','FontSize', 18)
subplot (1, 2, 2)
surf (Eta, Phi_Rad, lambda0)
zlabel ('Nuclear Interaction Length','FontSize', 18)
figure ('name','1D-Projections','PaperPositionMode','auto',... 'position',[100, 0, 1900, 1100])
subplot (2, 2, 1)
plot (mean(Eta, 1), mean(x0, 1), 'LineWidth', 2)
ylabel ('Radiatiaon Length','FontSize', 18)
set (gca,'FontSize', 16, 'XMinorTick','off', 'YMinorTick','off')
line (get(gca,'XLim'),[18, 18],'Color',[.5.5.5])
text (mean(get(gca,'XLim')), 18,'18 X_0','VerticalAlignment','top','FontSize', 18,'Color',[.5.5.5])
set (gca,'YLim',[0, 30])
set (gca,'XLim',[0, 1.2])
text (mean(get(gca,'XLim')), mean(get(gca,'YLim'))*.2,...sprintf('sPHENIX EMCal, average%.1f X_0', mean(mean(x0))),... 'HorizontalAlignment','center','FontSize', 18)
subplot (2, 2, 2)
plot (mean(Phi_Rad, 2), mean(x0, 2), 'LineWidth', 2)
xlabel ('\phi[rad]','FontSize', 18)
line ((xlim),[18, 18],'Color',[.5.5.5])
text (mean(xlim)*1.2, 18,'18 X_0','VerticalAlignment','top','FontSize', 18,'Color',[.5.5.5])
set (gca,'XLim', xlim)
subplot (2, 2, 3)
plot (mean(Eta, 1), mean(lambda0, 1), 'LineWidth', 2)
ylabel ('Nuclear Interaction Length','FontSize', 18)
text (mean(get(gca,'XLim')), 0.75,'0.75\Lambda_0','VerticalAlignment','top','FontSize', 18,'Color',[.5.5.5])
text (mean(get(gca,'XLim')), mean(get(gca,'YLim'))*.2,...sprintf('sPHENIX EMCal, average%.1f\\Lambda_0', mean(mean(lambda0))),... 'HorizontalAlignment','center','FontSize', 18)
subplot (2, 2, 4)
plot (mean(Phi_Rad, 2), mean(lambda0, 2), 'LineWidth', 2)
text (mean(xlim)*1.2, 0.75,'0.75\Lambda_0','VerticalAlignment','top','FontSize', 18,'Color',[.5.5.5])
SaveCavas (file, gcf)
figure ('name','1D-Projections-RadiationLength','PaperPositionMode','auto',... 'position',[100, 0, 800, 600])
plot (mean(Eta, 1), mean(x0, 1), 'LineWidth', 3)
text (mean(get(gca,'XLim'))*.1, mean(get(gca,'YLim'))*.6,...sprintf('sPHENIX simulation\n2-D projective SPACAL EMCal\nThickness scan from vertex of(0, 0, 0)&averaged in\\phi\n\nAverage thickness=%.1f X_0,%.2f\\Lambda_0\nMin thickness=%.1f X_0,%.2f\\Lambda_0',...mean(mean(x0)), mean(mean(lambda0)), min(mean(x0, 1)), min(mean(lambda0, 1))),... 'HorizontalAlignment','left','FontSize', 18)
Variables
close all clear all From
Geant4 Material Scans on EMCal
along without support and electronics
mat3 list file = 'mat2.list'
n_scan = 111
Data = zeros(n_scan*n_scan,5)
i = 1
fid = fopen(file)
tline = fgetl(fid)
while n = sscanf(tline,'%f')
n_eta = size(Data,1)/n_scan
Theta = Data(:,1)
Phi_Deg = Data(:,2)
Length = Data(:,3)
x0 = Data(:,4)
lambda0 = Data(:,5)
Eta = -log(tan((90-Theta)/180*pi/2))
Phi_Rad = Phi_Deg/180*pi
xlim = get(gca,'XLim')
Function Documentation
"/control/matScan/scan" ApplyCommand () virtual
assert (i- 1 = =n_scan *n_scan)
Data (i , :)
elseif (strncmpi(tline,'ave.', 5))
end fclose (fid)
Referenced by Bias::Bias(), daq_set_runnumberfile(), daq_write_runnumberfile(), testing::internal::posix::FClose(), Fe55::Fe55(), TSQLImportClient::GET(), TSQLImportClient::Init(), graph::load(), tinyxml2::XMLDocument::LoadFile(), mg_do_ssi_include(), mg_get_ip_address_of_nameserver(), mg_handle_ssi_request(), mg_hexdump_connection(), mg_http_free_proto_data_file(), mg_is_authorized(), mg_resolve_from_hosts_file(), testing::internal::XmlUnitTestResultPrinter::OnTestIterationEnd(), PHmd5File(), plot_matscan(), plot_matscan_tdr(), Fe55::PlotAvHit(), Fe55::PlotXlines(), TSQLUrl::Print(), Hydroinfo_MUSIC::readHydroData(), Martini::readRadiativeRate(), SaveAsCSV(), tinyxml2::XMLDocument::SaveFile(), testing::internal::ScopedPrematureExitFile::ScopedPrematureExitFile(), simulateTimestamps(), testing::internal::WriteToShardStatusFileIfNeeded(), and daq_device_random::~daq_device_random().
figure ('name' , '2D' , 'PaperPositionMode' , 'auto' , ... 'position')
figure ('name' , '1D-Projections' , 'PaperPositionMode' , 'auto' , ... 'position')
figure ('name' , '1D-Projections-RadiationLength' , 'PaperPositionMode' , 'auto' , ... 'position')
while ischar (tline)
line (get(gca,'XLim') , 'Color')
line ((xlim) , 'Color')
plot (mean(Eta, 1) , mean(x0, 1) , 'LineWidth' , 2)
plot (mean(Phi_Rad, 2) , mean(x0, 2) , 'LineWidth' , 2)
plot (mean(Eta, 1) , mean(lambda0, 1) , 'LineWidth' , 2)
plot (mean(Phi_Rad, 2) , mean(lambda0, 2) , 'LineWidth' , 2)
plot (mean(Eta, 1) , mean(x0, 1) , 'LineWidth' , 3)
SaveCavas (file , gcf)
set (gca , 'FontSize' , 16 , 'XMinorTick' , 'off' , 'YMinorTick' , 'off')
set (gca , 'YLim')
set (gca , 'XLim')
set (gca , 'XLim' , xlim)
subplot (1 , 2 , 1)
subplot (1 , 2 , 2)
subplot (2 , 2 , 1)
subplot (2 , 2 , 2)
subplot (2 , 2 , 3)
subplot (2 , 2 , 4)
surf (Eta , Phi_Rad , x0)
Referenced by MakeMilleFiles::addTrackToMilleFile(), FluidcellStatistic::calculate_hypersurface_3volume(), AlignmentTransformation::createMap(), TrackResiduals::fillClusterBranches(), TrackResiduals::fillHitTree(), ActsEvaluator::fillProtoTrack(), TrackResiduals::fillStatesWithLineFit(), PHTruthClustering::G4ClusterSize(), SvtxTruthEval::G4ClusterSize(), PHG4GDMLWriteStructure::GetBorderSurface(), PHCosmicsTrkFitter::getCharge(), MakeMilleFiles::getLocalVtxDerivativesXY(), PHG4GDMLWriteStructure::GetSkinSurface(), MakeSourceLinks::getSourceLinks(), PHActsTrkFitter::getSurfaceVector(), HelicalFitter::getTrackletClusterList(), PHActsTrackProjection::makeCaloSurfacePtrs(), MakeActsGeometry::makeInttMapPairs(), MakeActsGeometry::makeMvtxMapPairs(), MakeActsGeometry::makeTpcMapPairs(), PHActsKDTreeSeeding::matchInttClusters(), PHActsSiliconSeeding::matchInttClusters(), PHG4MvtxHitReco::process_event(), HelicalFitter::process_event(), PHGenFitTrkFitter::ReFitTrack(), and Acts::EventDataView3DTest::testMeasurement().
surf (Eta , Phi_Rad , lambda0)
text (mean(get(gca,'XLim')) , 18 , '18 X_0' , 'VerticalAlignment' , 'top' , 'FontSize' , 18 , 'Color')
Referenced by Fun4AllHepMCOutputManager::AddComment(), BOOST_AUTO_TEST_CASE(), CalculateSigmaDca(), BbcMonDraw::Draw(), TpotMonDraw::draw_detnames_sphenix(), tinyxml2::XMLDocument::Identify(), MakeShowerGraph(), tinyxml2::XMLDocument::NewText(), RejectionCurve_AuAuSummary(), RejectionCurve_AuAuSummary_Compare(), RejectionCurve_AuAuSummary_Compare2(), RejectionCurve_AuAuSummaryPos(), RejectionCurve_PIDComparison(), RejectionCurve_ppSummary(), RejectionCurve_ppSummaryPos(), RejectionCurve_RejMethodComparison(), RejectionCurve_RejMethodComparison_AntiProton(), tinyxml2::XMLText::ShallowClone(), tinyxml2::XMLUnknown::ShallowClone(), tinyxml2::XMLText::ShallowEqual(), Acts::AxisAlignedBoundingBox< entity_t, value_t, DIM >::svg(), testing::gmock_matchers_test::TEST(), TrackProjection_Checks_Comparison(), and write_run_data().
text (mean(get(gca,'XLim')) , mean(get(gca,'YLim'))*. 2, sprintf'sPHENIX EMCal, average%.1f X_0', mean(mean(x0)), ... 'HorizontalAlignment' , 'center' , 'FontSize' , 18)
text (mean(xlim)*1. 2, 18 , '18 X_0' , 'VerticalAlignment' , 'top' , 'FontSize' , 18 , 'Color')
text (mean(get(gca,'XLim')) , 0. 75, '0.75\Lambda_0' , 'VerticalAlignment' , 'top' , 'FontSize' , 18 , 'Color')
text (mean(get(gca,'XLim')) , mean(get(gca,'YLim'))*. 2, sprintf'sPHENIX EMCal, average%.1f\\Lambda_0', mean(mean(lambda0)), ... 'HorizontalAlignment' , 'center' , 'FontSize' , 18)
text (mean(xlim)*1. 2, 0. 75, '0.75\Lambda_0' , 'VerticalAlignment' , 'top' , 'FontSize' , 18 , 'Color')
text (mean(get(gca,'XLim'))*. 1, mean(get(gca,'YLim'))*. 6, sprintf'sPHENIX simulation\n2-D projective SPACAL EMCal\nThickness scan from vertex of(0, 0, 0)&averaged in\\phi\n\nAverage thickness=%.1f X_0,%.2f\\Lambda_0\nMin thickness=%.1f X_0,%.2f\\Lambda_0',...mean(mean(x0)), mean(mean(lambda0)), min(mean(x0, 1)), min(mean(lambda0, 1)), ... 'HorizontalAlignment' , 'left' , 'FontSize' , 18)
xlabel ('\eta' , 'FontSize' , 18)
xlabel ('\phi' [rad], 'FontSize' , 18)
ylabel ('\phi' [rad], 'FontSize' , 18)
ylabel ('Radiatiaon Length' , 'FontSize' , 18)
ylabel ('Nuclear Interaction Length' , 'FontSize' , 18)
zlabel ('Radiatiaon Length' , 'FontSize' , 18)
zlabel ('Nuclear Interaction Length' , 'FontSize' , 18)
Variable Documentation
Data = zeros(n_scan*n_scan,5)
Definition at line 23 of file ThicknessScan.m.
View newest version in sPHENIX GitHub at line 23 of file ThicknessScan.m
Referenced by SDeltaPtCutStudy::CalculateEfficiencies(), catalogInfo(), ClassImpQ(), STrackCutStudy::ConstructPlots(), SDeltaPtCutStudy::CreateSigmaGraphs(), DoPercentDifference(), DrawGraph(), Fun4All_G4_sPHENIX(), generate_distortion_map(), AnnularFieldSim::GenerateSeparateDistortionMaps(), generateTruthIbfGainMap(), TrackingPerformanceCheck::Init(), MvtxMon::Init(), SDeltaPtCutStudy::InitHists(), STrackCutStudy::InitHists(), main(), SDeltaPtCutStudy::MakePlots(), MakePrettyPlot(), MakeRatioComparisonPlot(), QuickDeltaPtExtractor(), QuickTreePlotter(), QuickTuplePlotter(), STrackCutStudy::SaveHists(), and STrackCutStudy::SetHistStyles().
close all clear all From Geant4 Material Scans on EMCal along without support and electronics
Definition at line 4 of file ThicknessScan.m.
View newest version in sPHENIX GitHub at line 4 of file ThicknessScan.m
Eta = -log(tan((90-Theta)/180*pi/2))
Definition at line 74 of file ThicknessScan.m.
View newest version in sPHENIX GitHub at line 74 of file ThicknessScan.m
Referenced by ana_hijbkg(), BOOST_AUTO_TEST_CASE(), STrackMatcherComparator::FillHistogram1D(), STrackMatcherComparator::FillHistogram2D(), MakeNewMatcherPlots(), MakeNewMatcherTuplePlots(), MakeOldEvaluatorPlots(), momentumDistributions(), and PHFlowJetMaker::run_particle_flow().
fid = fopen(file)
Definition at line 27 of file ThicknessScan.m.
View newest version in sPHENIX GitHub at line 27 of file ThicknessScan.m
Referenced by boundParamResolution(), printlogo(), pynjdc(), HybridHadronization::recomb(), and HybridHadronization::stringprep().
file = 'mat2.list'
Definition at line 11 of file ThicknessScan.m.
View newest version in sPHENIX GitHub at line 11 of file ThicknessScan.m
Referenced by eic_bnl_rich::acq(), Acts::Python::addDetector(), Acts::Python::addFramework(), KFPVEfficiencies::AddFromFile(), KFPartEfficiencies::AddFromFile(), Acts::Python::addMagneticField(), testing::internal::FunctionMockerBase< R(A1, A2)>::AddNewExpectation(), testing::internal::FunctionMockerBase< R(A1, A2)>::AddNewOnCallSpec(), AnalyzeResiduals(), BOOST_AUTO_TEST_CASE(), boundParamResolution(), gzstreambuf::close(), collectData(), compare_observables(), compareRootFiles(), convert_sartre2eictree(), groot::CreateZigzags(), cs_log_set_file(), daq_set_runnumberApp(), daq_set_runnumberfile(), testing::internal::ExpectationBase::DescribeLocationTo(), event_topology_reco(), ExampleAnalysisDSTReader(), ExampleAnalysisModulePlot(), testing::internal::Expect(), groot::FillZigzagMaps(), gzstreambuf::flush_buffer(), ActsExamples::Sequencer::fpeMaskCount(), Fun4All_Calo(), Fun4All_EMCal(), Fun4All_EMCal_Hist(), Fun4All_EMCal_sp(), Fun4All_TrkrHitSet_Unpacker(), fuse_gmock_files::FuseGMockAllCcToFile(), fuse_gmock_files::FuseGMockGTestAllCc(), fuse_gmock_files::FuseGMockH(), gen_gtest_pred_impl::GenerateFile(), PHGeomUtility::GenerateGeometryFileName(), hLabHelper::getFileLists(), init(), PHG4InnerHcalSteppingAction::InitWithNode(), PHG4OuterHcalSteppingAction::InitWithNode(), PHG4IHCalSteppingAction::InitWithNode(), PHG4OHCalSteppingAction::InitWithNode(), LaplaceSolution::LaplaceSolution(), likelihood(), likelihood_topology(), graph::load(), Acts::AtlasBetheHeitlerApprox< NComponents, PolyDegree >::loadFromFiles(), TSQLImporter::LoadTable(), main(), pump::main(), make_cemcCDBTree(), make_csv(), testing::internal::FilePath::MakeFileName(), makePlot_track_eval(), makePlot_track_pscan(), medinit(), mergefiles(), PHTFileServer::open(), gzstreambuf::open(), plot(), Fun4AllInputManager::Print(), AZigzag::ReadCalibration(), ActsExamples::Options::readMagneticField(), reconstructionPerformance(), KFPHistogram::Save(), graph::save(), testing::internal::ScopedTrace::ScopedTrace(), MakeMilleFiles::set_constraintfile_name(), MakeMilleFiles::set_datafile_name(), HelicalFitter::set_datafile_name(), TpcPrototypeGenFitTrkFinder::set_eval_filename(), PHGenFitTrkFitter::set_eval_filename(), TpcPrototypeGenFitTrkFitter::set_eval_filename(), PHAna::set_filename(), MvtxQAHisto::set_filename(), AnaSvtxTracksForGenFit::set_filename(), FastTrackingEval::set_filename(), EpFinderEval::set_filename(), PHG4TrackFastSimEval::set_filename(), Calib::set_filename(), GenFitTrackProp::set_filename(), HelicalFitter::set_ntuplefile_name(), MakeMilleFiles::set_steeringfile_name(), HelicalFitter::set_steeringfile_name(), MakeActsGeometry::setMaterialResponseFile(), SColdQcdCorrelatorAnalysis::SBaseQAPlugin< SCheckTrackPairsConfig >::SetOutFile(), TEST_CASE(), Acts::Svg::toFile(), tpythia6_open_fortran_file(), TrackCaloDist(), tsdst_plus_tsfit(), gzstreambuf::underflow(), release_docs.WikiBrancher::UpdateLinksInBranchedFiles(), AZigzag::WriteCalibration(), testing::internal::WriteToShardStatusFileIfNeeded(), and xytabl().
i = 1
Definition at line 25 of file ThicknessScan.m.
View newest version in sPHENIX GitHub at line 25 of file ThicknessScan.m
lambda0 = Data(:,5)
Definition at line 62 of file ThicknessScan.m.
View newest version in sPHENIX GitHub at line 62 of file ThicknessScan.m
Referenced by Acts::EventDataView3D::decomposeCovariance(), Acts::EventDataView3D::drawCovarianceAngular(), Acts::EventDataView3D::drawCovarianceCartesian(), and KFParticleBase::SetMassConstraint().
Length = Data(:,3)
Definition at line 60 of file ThicknessScan.m.
View newest version in sPHENIX GitHub at line 60 of file ThicknessScan.m
Referenced by oncsBuffer::buffer_swap(), ospBuffer::writeout(), and ophBuffer::writeout().
if n = sscanf(tline,'%f')
Definition at line 32 of file ThicknessScan.m.
View newest version in sPHENIX GitHub at line 32 of file ThicknessScan.m
Referenced by ClusterSequence::_CP2DChan_cluster(), ClusterSequence::_CP2DChan_limited_cluster(), ClusterSequence::_delaunay_cluster(), ClusterSequence::_do_Cambridge_inclusive_jets(), ClusterSequence::_faster_tiled_N2_cluster(), SearchTree< T >::_initialize(), ClusterSequence::_minheap_faster_tiled_N2_cluster(), ClusterSequence::_really_dumb_cluster(), ClusterSequence::_simple_N2_cluster(), ClusterSequence::_tiled_N2_cluster(), odbc::Timestamp::_validateNanos(), testing::gmock_generated_actions_test::ACTION_P(), testing::gmock_generated_actions_test::ACTION_P3(), planarity::add_to_embedding(), mvtx::PayLoadCont::addFast(), Acts::Python::addGenerators(), PHDataNodeIterator::AddIODataNode(), Acts::CandidatesForMiddleSp< external_space_point_t >::addToCollection(), planar_embedding::adj_edges_begin(), planar_embedding::adj_edges_end(), planar_embedding::adjacency(), biconnectivity::after_recursive_call_handler(), PHG4TpcDirectLaser::AimToPatternStep(), PHG4TpcDirectLaser::AimToPatternStep_File(), aiz(), ar3jet(), arorie(), atrobo(), attrad(), ActsExamples::averageSimHits(), bfs::bfs_num(), testing::gmock_generated_actions_test::Binary(), testing::gmock_more_actions_test::Binary(), pq_tree::blocked_in_subtree(), BOOST_AUTO_TEST_CASE(), Acts::Test::BOOST_AUTO_TEST_CASE(), sHelix::breakIntoPieces(), bin_heap< T, Pred >::bubble_down(), bin_heap< T, Pred >::bubble_up(), KFParticle_eventReconstruction::buildChain(), oncsSub_idtpcfeev3::cacheIterator(), tpc_pool::cacheIterator(), Polyhedron::calculate_centroid(), PHG4TpcCentralMembrane::CalculateVertices(), planarity::case_A(), planarity::case_C(), planarity::case_D(), planarity::case_E(), CBcalc(), CBcalc_exp(), CBcalc_LL(), CBFunction(), CBFunction_withBG(), graph::center(), bin_heap< T, Pred >::changeKey(), planar_embedding::check(), Acts::Test::LayerCreatorFixture::checkBinContentSize(), Rossegger::CheckZeroes(), testing::internal::ChopLowBits(), cleanup(), Jetscape::HadronizationManager::Clear(), Jetscape::JetEnergyLossManager::Clear(), Acts::AnnulusBounds::closestOnSegment(), dfs::comp_num(), compressevent(), Acts::BoundaryCheck::computeClosestPointOnPolygon(), pathfinder::const_iterator::const_iterator(), converttohepmc(), Selector::count(), crsjet(), Acts::Test::CubicBVHTrackingGeometry::CubicBVHTrackingGeometry(), daq_fake_trigger(), daq_setmaxevents(), EMMaximization::DefaultJ(), graph::del_node(), DecayFinder::deleteElement(), PHG4GenHit::Detector(), planarity::dfs_bushform(), dfs::dfs_num(), NNH< BJ, I >::dij_min(), TpcPrototypeGenFitTrkFitter::DisplayCluster(), bellman_ford::distance(), dijkstra::distance(), Distribution2Efficiency(), dofistatescat(), doinstatescat(), dokinematics(), QueueTest::Double(), Draw_EICRate(), draw_G4_bjet_truth_tagging(), draw_G4_dibjet_truth_tagging(), Draw_HFJetTruth(), Draw_HFJetTruth3yr(), Draw_HFJetTruth_InvMass(), Draw_PHG4DSTReader(), DrawEcal_Likelihood(), DrawEcal_pDST(), DrawEMCalTower(), PktSizeMonDraw::DrawFirst(), MyMonDraw::DrawHistory(), DaqMonDraw::DrawHistory(), MvtxMonDraw::DrawHistory(), DrawPrototype2EMCalTower(), DrawPrototype2MIPAnalysis(), DrawPrototype2ShowerCalib(), DrawPrototype3EMCalTower(), DrawPrototype3ShowerCalib(), DrawPrototype4EMCalTower(), DrawPrototype4ShowerCalib(), DrawTower_Load(), DrawTPCFEE(), DrawTpcPrototypeGenFitTrkFitter(), DrawTpcPrototypeUnpacker(), DrawTrackingEval(), oncsSub_idcstr::dump(), Packet_idcstr::dump(), dvcs_plot(), eicsmear_dvmp_plot(), Rossegger::Ephi(), Rossegger::Ephi_(), LaplaceSolution::Er(), Rossegger::Er(), Rossegger::Er_(), Acts::Legacy::AtlasSeedFinder< SpacePoint >::erase(), mvtx::PayLoadCont::eraseFast(), Jetscape::JetEnergyLossManager::Exec(), expect(), planarity::extend_embedding(), LaplaceSolution::Ez(), Rossegger::Ez(), Rossegger::Ez_(), Factorial(), CaloWaveformFitting::FastMax(), dfs::father(), bfs::father(), FermiMotion(), ffu(), Acts::fieldMapRZ(), Acts::fieldMapXYZ(), Acts::GeometryHierarchyMap< value_t >::fill(), bid_dijkstra::fill_node_edge_lists(), mvtx::PayLoadCont::fillFast(), Acts::Legacy::AtlasSeedFinder< SpacePoint >::fillLists(), find_json_token(), LaplaceSolution::FindBetamn(), Rossegger::FindBetamn(), DecayFinder::findDecay(), ATrace::FindMaximum(), ATrace::FindMaximumMiddle(), Rossegger::FindMunk(), FitProfile(), FitResolution(), fnjet(), msg_buffer::format(), Acts::Test::SurfaceArrayFixture::fullPhiTestSurfacesBRL(), Acts::Test::SurfaceArrayCreatorFixture::fullPhiTestSurfacesBRL(), Acts::Test::LayerCreatorFixture::fullPhiTestSurfacesBRL(), Acts::Test::SurfaceArrayFixture::fullPhiTestSurfacesEC(), Acts::Test::SurfaceArrayCreatorFixture::fullPhiTestSurfacesEC(), Acts::Test::LayerCreatorFixture::fullPhiTestSurfacesEC(), fullRunningMean::fullRunningMean(), Fun4All_FillChargesMap_300evts_MDC2(), Fun4All_FillDCMap(), Fun4All_G4_EICDetector_LQ(), Fun4All_G4_EICDetector_LQ_analysis(), Fun4All_G4_EICDetector_LQ_analysis_nf(), Fun4All_G4_EICDetector_LQ_reference(), G__DirectPhotonPythia_Dict_523_0_20(), G__ExampleAnalysisModule_Dict_577_0_1(), G__ExampleAnalysisModule_Dict_577_0_10(), G__ExampleAnalysisModule_Dict_578_0_1(), G__ExampleAnalysisModule_Dict_578_0_16(), G__ExampleAnalysisModule_Dict_579_0_1(), G__ExampleAnalysisModule_Dict_579_0_17(), G__RecoInfoExport_Dict_244_0_1(), G__RecoInfoExport_Dict_244_0_13(), G__SimpleTrackingAnalysis_Dict_194_0_1(), G__SimpleTrackingAnalysis_Dict_194_0_8(), G__STACalorimeterCharacterization_Dict_194_0_1(), G__STACalorimeterCharacterization_Dict_194_0_14(), genevent(), TpcPrototypeGenFitTrkFitter::get_rotation_matrix(), fm_partition::get_side_of_node(), ratio_cut_partition::get_side_of_node(), KFParticle::GetAngle(), KFParticleSIMD::GetAngle(), KFParticle::GetAngleRZ(), KFParticleSIMD::GetAngleRZ(), KFParticle::GetAngleXY(), KFParticleSIMD::GetAngleXY(), TpcPrototypeGenFitTrkFinder::getChi2Ndf(), getdeltat(), my_graph::GetEdgeValue(), shower2::GetEdgeValue(), shower::GetEdgeValue(), GetEvalHisto(), eventReceiverClient::getEvent(), TrigFTF_GNN_TrackingFilter< external_spacepoint_t >::getLayerType(), getmass(), getnewmass(), OnTheFlyPrimeTable::GetNextPrime(), PreCalculatedPrimeTable::GetNextPrime(), my_graph::GetNodeValue(), shower2::GetNodeValue(), shower::GetNodeValue(), PHG4Sector::Sector_Geometry::GetNumActiveLayers(), shower2::GetPartons(), getpnorad1(), GetQAHisto(), getqvec(), ActsFatras::detail::GeneralMixture::getSemigauss(), Fatras::GeneralMixture::getSemigauss(), Jetscape::PartonShower::GetVertex(), gmin(), genfit::EventDisplay::guiGoto(), genfit::EventDisplay::guiGoto2(), hiboost(), hijcrs(), hijfrg(), hijfst_(), hijhrd(), hijing(), hirobo(), TowerBackgroundv1::identify(), EmbRecoMatchContainerv1::identify(), PHG4CylinderGeom_Spacalv3::ImportParameters(), PHG4CylinderGeom_Spacalv1::ImportParameters(), init(), ne_map< Key, Value, Graph, Alloc >::init(), initpythia(), HcalRawTowerBuilder::InitRun(), PHG4CentralityReco::InitRun(), readDigitalCurrents::InitRun(), fillSpaceChargeMaps::InitRun(), PHTypedNodeIterator< T >::insert(), symlist< T >::insert(), planar_embedding::insert_selfloop(), genfit::Track::insertPoints(), gbl::VSymMatrix::invert(), OnTheFlyPrimeTable::IsPrime(), PreCalculatedPrimeTable::IsPrime(), isprimhadron(), isprimstring(), issecstring(), oncsSub_idcstr::iValue(), oncsSub_idcaenv1742::iValue(), Packet_iddigitizerv2::iValue(), Packet_iddigitizerv3::iValue(), Packet_idcstr::iValue(), oncsSub_idtpcfeev2::iValue(), oncsSub_idmvtxv3::iValue(), jewel(), json_emit_double(), json_emit_long(), json_emit_unquoted_str(), KFParticleSIMD::KFParticleSIMD(), KFPEmcCluster::KFPEmcCluster(), klu(), LambertW(), ActsExamples::SeedingFTFAlgorithm::LayerNumbering(), topsort::leave_handler(), bfs::level(), likelihood(), graph::load(), Load_CurveSet(), Jetscape::PartonShower::load_node_info_handler(), shower2::load_node_info_handler(), InttCombinedRawDataDecoder::LoadHotChannelMapLocal(), InttCombinedRawDataDecoder::LoadHotChannelMapRemote(), Rossegger::LoadZeroes(), biconnectivity::low_number(), lu1ent(), lu2ent(), lu3ent(), lu4ent(), luboei(), lucell(), luclus(), ludecy(), luedit(), lueevt(), luerrm(), luexec(), lufowo(), lugive(), luhepc(), luindf(), lujmas(), lujoin(), lulist(), luonia(), luprep(), lurobo(), lushow(), lusphe(), lustrf(), lutabu(), lutest(), luthru(), luxdif(), oncsSub_idtpcfeev3::lValue(), tpc_pool::lValue(), main(), FieldMaps::Make(), Jetscape::make_unique(), makebranch(), makecascade(), makeDefaultBoundPars(), BDiJetModule::MakeGenFitTrack(), SVReco::MakeGenFitTrack(), makeinsplit(), makePacketV1Hdr(), makesplitting(), makestrings_minl(), makestrings_vac(), TpcPrototypeGenFitTrkFitter::MakeTpcPrototypeTrack(), planarity::mark_all_neighbors_of_leaves(), mbuf_remove(), NNH< BJ, I >::merge_jets(), mg_addenv(), mg_dns_encode_name(), mg_escape(), mg_handle_chunked(), mg_handle_udp_read(), mg_hexdump(), mg_http_parse_chunk(), mg_http_parse_header(), mg_http_send_file2(), mg_http_transfer_file_data(), mg_is_error(), mg_parse_multipart(), mg_read_from_socket(), mg_recvfrom(), mg_rpc_create_error(), mg_rpc_create_reply(), mg_rpc_create_request(), mg_rpc_dispatch(), mg_rpc_parse_reply(), mg_send_file_data(), mg_send_http_chunk(), mg_write_to_socket(), intt_pool::Name(), graph::new_node(), my_graph::new_vertex(), Jetscape::PartonShower::new_vertex(), shower2::new_vertex(), shower::new_vertex(), Acts::Legacy::AtlasSeedFinder< SpacePoint >::newEvent(), noiMakeTGraph(), nran(), Acts::TrigFTF_GNN_DataStorage< external_spacepoint_t >::numberOfNodes(), numericInverse(), biconnectivity::old_adj_node_handler(), testing::gmock_matchers_test::PolymorphicFunctor::operator()(), testing::gmock_matchers_test::ReferencingFunctor::operator()(), Acts::detail_tc::TrackProxyIterator< container_t, proxy_t, ReadOnly >::operator+=(), Acts::detail_tc::TrackProxyIterator< container_t, proxy_t, ReadOnly >::operator-=(), operator<<(), planar_embedding::operator=(), KFPEmcCluster::operator=(), KFPTrackVector::operator=(), genfit::RKMatrix< 7, 7 >::operator[](), Acts::detail_tc::TrackProxyIterator< container_t, proxy_t, ReadOnly >::operator[](), fm_partition::operator[](), bfs::operator[](), dfs::operator[](), ratio_cut_partition::operator[](), st_number::operator[](), msg_buffer::overflow(), parse_net(), parse_string(), parton(), pevrec(), PHmd5Stream(), PHNode::PHNode(), planar_embedding::planar_embedding(), Plot_FastTrack_Efficiency(), Plot_SVTX_Efficiency(), plu(), poissonian(), planar_embedding::pos(), ActsExamples::ParticleTrackingAction::PostUserTrackingAction(), Rossegger::PrecalcDerivedConstants(), Rossegger::PrecalcFreeConstants(), bellman_ford::predecessor_edge(), dijkstra::predecessor_edge(), dijkstra::predecessor_node(), InttMonDraw::PrepGlobalLadderHists_Interface(), SearchTree< T >::print_elements(), mvtx::GBTLink::PrintBlock(), KFPEmcCluster::PrintTrack(), KFPTrackVector::PrintTrack(), BbcMon::process_event(), InttRawDataDecoder::process_event(), InttRawDataConverter::process_event(), RawClusterBuilderTopo::process_event(), SubtractTowersCS::process_event(), TpcCombinedRawDataUnpacker::process_event(), ParticleFlowReco::process_event(), InttMon::process_event(), TpcPrototypeGenFitTrkFinder::process_event(), cl::Program::Program(), ps(), pseudoRunningMean::pseudoRunningMean(), bin_heap< T, Pred >::push(), planar_embedding::push_back(), planar_embedding::push_front(), py1ent(), py2ent(), py2frm(), py3ent(), py4ent(), py4frm(), py4jet(), py4jts(), py4jtw(), py6frm(), pyadsh(), pybesq(), pybksb(), pyboei(), pycba2(), pycbal(), pycell(), pyckbd(), pyclus(), pycmq2(), pycmqr(), pycrth(), pycttr(), pydecy(), pydiff(), pydisg(), pydocu(), pyedit(), pyeevt(), pyeicg(), pyerrm(), pyevnt(), pyevnw(), pyevol(), pyexec(), pyfowo(), pyfscr(), pygaga(), pygive(), pygraw(), pygrvv(), pyhepc(), pyhidiff(), pyhiinki(), pyhimult(), pyhiremn(), pyhiresd(), pyhiscat(), pyhisspa(), pyhitest(), pyhithia(), pyinbm(), pyindf(), pyinki(), pyjmas(), pyjoin(), pyk(), pyklim(), pyldcm(), pylist(), pymemx(), pymewt(), pymign(), pymihg(), pymihk(), pymirm(), pymult(), pyonia(), pyp(), pypdfu(), pyprep(), pyptfs(), pyptis(), pyptmi(), pyreco(), pyremn(), pyresd(), pyrobo(), pyrvgw(), pyrvsb(), pyscat(), pyshow(), pysigh(), pysimp(), pysphe(), pysspa(), pystrf(), pytabu(), pytaud(), pytbdy(), pytest(), pythru(), pyupev(), pyupin(), pyveto(), pywdkk(), pyxdif(), ranums(), bellman_ford::reached(), dijkstra::reached(), bfs::reached(), dfs::reached(), ActsExamples::EventGenerator::read(), Matter::read_tables(), LBT::read_tables(), readBeamXings(), ReconstructTracks(), testing::gmock_matchers_test::ReferencingFunction(), TpcPrototypeGenFitTrkFitter::ReFitTrack(), PHGenFitTrkFitter::ReFitTrack(), NNH< BJ, I >::remove_jet(), BJetModule::reset_tree_vars(), BDiJetModule::ResetVariables(), oncsSub_idtpcfeev2::reverseBits(), oncsSub_idinttv0::reverseBits(), oncsSub_idtpcfeev3::reverseBits(), tpc_pool::reverseBits(), Rossegger::Rmn(), Rossegger::Rmn1(), Rossegger::Rmn2(), LaplaceSolution::Rnk(), Rossegger::Rnk(), Rossegger::Rnk_for_zeroes(), half::round(), Rossegger::RPrime(), LazyTiling9Alt::run(), LazyTiling9::run(), LazyTiling25::run(), trento::Collider::run_events(), st_number::s_node(), sampleFromMultivariate(), SandB_CBFunction(), my_graph::save_edge_info_handler(), shower2::save_edge_info_handler(), shower::save_edge_info_handler(), my_graph::save_node_info_handler(), shower2::save_node_info_handler(), Jetscape::PartonShower::save_node_info_handler(), Jetscape::PartonShower::SaveAsGraphML(), Jetscape::PartonShower::SaveAsGV(), sChargeMap::SaveRho(), Rossegger::SaveZeroes(), CaloCalibEmc_Pi0::set_centrality_nclusters_cut(), PHPy6ForwardElectronTrig::set_combined_required(), PHPy6ForwardElectronTrig::set_electrons_required(), EventPlaneReco::set_Ep_orders(), SVReco::set_n_intt_layer(), SVReco::set_n_maps_layer(), PHRaveVertexing::set_nmvtx_clusters_required(), PHPy6ForwardElectronTrig::set_positrons_required(), PHG4SimpleEventGenerator::set_power_law_n(), Acts::detail::SymmetricKLDistanceMatrix::setAssociated(), testing::internal::ExpectationTester::SetCallCount(), FieldMaps::SetDebugLevel(), QPileUp::SetDebugLevel(), Langevin::SetDebugLevel(), PHG4TpcDirectLaser::SetFileStepping(), PHGeomIOTGeo::SetGeometry(), pmonstate::setIdentifyFlag(), ResonanceJetTagging::setJetContainerName(), KFPTrackVector::SetLastDeuteron(), KFPTrackVector::SetLastElectron(), KFPTrackVector::SetLastHe3(), KFPTrackVector::SetLastHe4(), KFPTrackVector::SetLastKaon(), KFPTrackVector::SetLastMuon(), KFPTrackVector::SetLastPion(), KFPTrackVector::SetLastProton(), KFPTrackVector::SetLastTritium(), genfit::AbsKalmanFitter::setMaxIterations(), genfit::DAF::setMaxIterations(), PHNode::setName(), CMFlashDifferencev1::setNclusters(), CMFlashClusterv1::setNclusters(), CMFlashClusterv2::setNclusters(), CMFlashClusterv3::setNclusters(), PHSimpleVertexFinder::setNmvtxRequired(), pmonstate::setNoevt(), KFMCVertex::SetNReconstructedDaughters(), KFParticleFinder::SetNThreads(), PHHybridSeeding::setNThreads(), KFParticleTopoReconstructor::SetNThreads(), PHNode::setObjectType(), PHG4TpcDirectLaser::SetPhiStepping(), PHG4TpcDirectLaser::SetThetaStepping(), sgmin(), testing::gmock_generated_actions_test::Short(), testing::gmock_more_actions_test::Short(), ActsExamples::WhiteBoard::similarNames(), Tokenizer::Skip(), dijkstra::source(), bellman_ford::source(), NNH< BJ, I >::start(), bfs::start_node(), dfs::start_node(), HybridHadronization::stringprep(), dijkstra::target(), TEST(), testing::gmock_matchers_test::TEST(), testing::gmock_generated_function_mockers_test::TEST(), testing::gmock_generated_actions_test::TEST(), testing::gmock_more_actions_test::TEST(), testing::gtest_printers_test::TEST(), TEST_CASE(), TEST_F(), Acts::Test::MultiTrajectoryTestsCommon< factory_t >::testApplyWithAbort(), topsort::top_num(), TrackCaloDist(), MvtxStandaloneTracking::TrackFitXY(), MvtxStandaloneTracking::TrackFitZY(), KFParticleBase::TransportCBM(), KFParticleBaseSIMD::TransportCBM(), genfit::tools::transposedForwardSubstitution(), TripleCBFunction(), planar_embedding::turn(), AnnularFieldSim::UpdateEveryN(), InttMaskedChannelSetv1::v_LoadFromCDBTTree(), InttSurveyMapv1::v_LoadFromCDBTTree(), Acts::CandidatesForMiddleSp< external_space_point_t >::weight(), while(), planar_embedding::write_st(), ActsExamples::RootMaterialWriter::writeMaterial(), ogzBuffer::writeout(), olzoBuffer::writeout(), ospBuffer::writeout(), and ophBuffer::writeout().
n_eta = size(Data,1)/n_scan
Definition at line 53 of file ThicknessScan.m.
View newest version in sPHENIX GitHub at line 53 of file ThicknessScan.m
Referenced by D0EffScan(), Hydroinfo_MUSIC::readHydroData(), and TEST().
n_scan = 111
Definition at line 14 of file ThicknessScan.m.
View newest version in sPHENIX GitHub at line 14 of file ThicknessScan.m
Phi_Deg = Data(:,2)
Definition at line 59 of file ThicknessScan.m.
View newest version in sPHENIX GitHub at line 59 of file ThicknessScan.m
Phi_Rad = Phi_Deg/180*pi
Definition at line 75 of file ThicknessScan.m.
View newest version in sPHENIX GitHub at line 75 of file ThicknessScan.m
Theta = Data(:,1)
Definition at line 58 of file ThicknessScan.m.
View newest version in sPHENIX GitHub at line 58 of file ThicknessScan.m
Referenced by momentumDistributions().
tline = fgetl(fid)
Definition at line 28 of file ThicknessScan.m.
View newest version in sPHENIX GitHub at line 28 of file ThicknessScan.m
Referenced by display(), myAnalysis::finalize(), and getxsecint().
x0 = Data(:,4)
Definition at line 61 of file ThicknessScan.m.
View newest version in sPHENIX GitHub at line 61 of file ThicknessScan.m
Referenced by aiz(), ALICEKF::ALICEKalmanFilter(), GPUTPCTrackParam::BetheBlochGas(), GPUTPCTrackParam::BetheBlochGeant(), Jetscape::BilinearInt(), biz(), Acts::Test::BOOST_AUTO_TEST_CASE(), AnaMvtxPrototype1::CalcSlope(), AnaMvtxTestBeam2019::CalcSlope(), MvtxStandaloneTracking::CalcSlope(), AnaMvtxTelescopeHits::CalcSlope(), SecondaryVertexFinder::circle_circle_intersection(), TrackSeed_v1::circleFitByTaubin(), PHBBox::ClipLine(), Acts::detail::combineSlabs(), PHG4OuterHcalDetector::ConstructHcalSingleScintillators(), BEmcRecCEMC::CorrectPosition(), ROOTDict::DirectPhotonPythia_Dictionary(), DrawTpcPrototypeGenFitTrkFitter_Summary(), ROOT::ElectronID_Dictionary(), ROOTDict::ExampleAnalysisModule_Dictionary(), CaloWaveformFitting::FastMax(), LaplaceSolution::FindBetamn(), Rossegger::FindNextZero(), Acts::Material::fromMassDensity(), Acts::Material::fromMolarDensity(), genevent(), TrackFitUtils::get_helix_pca(), TrackFitUtils::get_helix_tangent(), PHParameterContainerInterface::get_int_param(), Jetscape::EvolutionHistory::GetAtTimeStep(), GPUTPCTrackParam::GetDCAPoint(), getResolutions(), ROOT::hcalUtil_Dictionary(), ActsFatras::detail::SimulationActor< generator_t, decay_t, interactions_t, hit_surface_selector_t >::interact(), interpCubicMono(), QAG4Util::interpolate(), Acts::detail::IntersectionHelper2D::intersectEllipse(), invertFunc(), Jetscape::JetScapeParticleBase::JetScapeParticleBase(), layerMaterial(), Jetscape::LinearInt(), ROOT::maplEunsignedsPintcOsPHElectronPairv1mUgR_Dictionary(), ROOT::multimaplEunsignedsPintcOunsignedsPintgR_Dictionary(), ROOT::PairMaker_Dictionary(), ROOT::PHAna_Dictionary(), plot_matscan(), plot_matscan_tdr(), PHG4GenHit::process_event(), PHG4SimpleEventGenerator::process_event(), AnaMvtxPrototype1::process_event(), pyinom(), pyrnm3(), pyrnmq(), pysimp(), pytbdy(), ROOTDict::RecoInfoExport_Dictionary(), GPUTPCTrackParam::Rotate(), testing::UnitTest::Run(), Acts::Test::segment(), sHelix::sHelix(), ROOTDict::SimpleTrackingAnalysis_Dictionary(), ROOTDict::STACalorimeterCharacterization_Dictionary(), MvtxStandaloneTracking::TrackFitXY(), Jetscape::TrilinearInt(), while(), and ActsExamples::RootMaterialWriter::writeMaterial().
xlim = get(gca,'XLim')
Definition at line 126 of file ThicknessScan.m.
View newest version in sPHENIX GitHub at line 126 of file ThicknessScan.m
Referenced by pyrvgw().