Analysis Software: TrackResiduals Class Reference
TrackResiduals Class Reference
#include <coresoftware/blob/master/offline/packages/TrackingDiagnostics/TrackResiduals.h>
Public Member Functions
TrackResiduals (const std::string &name="TrackResiduals")
~TrackResiduals () override
int Init (PHCompositeNode *topNode) override
int InitRun (PHCompositeNode *topNode) override
int process_event (PHCompositeNode *topNode) override
int End (PHCompositeNode *topNode) override
Called at the end of all processing.
void outfileName (const std::string &name)
void alignment (bool align)
void alignmentmapName (const std::string &name)
void trackmapName (const std::string &name)
void clusterTree ()
void hitTree ()
void zeroField ()
Public Member Functions inherited from SubsysReco
~SubsysReco () override
virtual int EndRun (const int)
Called at the end of each run.
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
void Print (const std::string &="ALL") const override
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Private Member Functions
void fillStatesWithLineFit (const TrkrDefs::cluskey &ckey, TrkrCluster *cluster, ActsGeometry *geometry)
void clearClusterStateVectors ()
void createBranches ()
float convertTimeToZ (ActsGeometry *geometry, TrkrDefs::cluskey cluster_key, TrkrCluster *cluster)
void fillClusterTree (TrkrClusterContainer *clusters, ActsGeometry *geometry)
void fillHitTree (TrkrHitSetContainer *hitmap, ActsGeometry *geometry, PHG4TpcCylinderGeomContainer *tpcGeom, PHG4CylinderGeomContainer *mvtxGeom, PHG4CylinderGeomContainer *inttGeom, PHG4CylinderGeomContainer *mmGeom)
void fillClusterBranches (TrkrDefs::cluskey ckey, SvtxTrack *track, PHCompositeNode *topNode)
void lineFitClusters (std::vector< TrkrDefs::cluskey > &keys, ActsGeometry *geometry, TrkrClusterContainer *clusters)
Private Attributes
std::string m_outfileName = ""
TFile * m_outfile = nullptr
TTree * m_tree = nullptr
TTree * m_clustree = nullptr
TTree * m_hittree = nullptr
bool m_doClusters = false
bool m_doHits = false
bool m_zeroField = false
ClusterErrorPara m_clusErrPara
std::string m_alignmentMapName = "SvtxAlignmentStateMap"
std::string m_trackMapName = "SvtxTrackMap"
bool m_doAlignment = false
int m_event = 0
uint64_t m_bco = std::numeric_limits<uint64_t>::quiet_NaN()
Track level quantities.
uint64_t m_bcotr = std::numeric_limits<uint64_t>::quiet_NaN()
unsigned int m_trackid = std::numeric_limits<unsigned int>::quiet_NaN()
unsigned int m_crossing = std::numeric_limits<unsigned int>::quiet_NaN()
float m_px = std::numeric_limits<float>::quiet_NaN()
float m_py = std::numeric_limits<float>::quiet_NaN()
float m_pz = std::numeric_limits<float>::quiet_NaN()
float m_pt = std::numeric_limits<float>::quiet_NaN()
float m_eta = std::numeric_limits<float>::quiet_NaN()
float m_phi = std::numeric_limits<float>::quiet_NaN()
float m_deltapt = std::numeric_limits<float>::quiet_NaN()
int m_charge = std::numeric_limits<int>::quiet_NaN()
float m_quality = std::numeric_limits<float>::quiet_NaN()
float m_chisq = std::numeric_limits<float>::quiet_NaN()
float m_ndf = std::numeric_limits<float>::quiet_NaN()
int m_nhits = std::numeric_limits<int>::quiet_NaN()
int m_nmaps = std::numeric_limits<int>::quiet_NaN()
int m_nintt = std::numeric_limits<int>::quiet_NaN()
int m_ntpc = std::numeric_limits<int>::quiet_NaN()
int m_nmms = std::numeric_limits<int>::quiet_NaN()
unsigned int m_vertexid = std::numeric_limits<unsigned int>::quiet_NaN()
float m_vx = std::numeric_limits<float>::quiet_NaN()
float m_vy = std::numeric_limits<float>::quiet_NaN()
float m_vz = std::numeric_limits<float>::quiet_NaN()
float m_pcax = std::numeric_limits<float>::quiet_NaN()
float m_pcay = std::numeric_limits<float>::quiet_NaN()
float m_pcaz = std::numeric_limits<float>::quiet_NaN()
float m_rzslope = std::numeric_limits<float>::quiet_NaN()
float m_rzint = std::numeric_limits<float>::quiet_NaN()
float m_xyslope = std::numeric_limits<float>::quiet_NaN()
float m_xyint = std::numeric_limits<float>::quiet_NaN()
uint32_t m_hitsetkey = std::numeric_limits<uint32_t>::quiet_NaN()
hit tree info
float m_hitgx = std::numeric_limits<float>::quiet_NaN()
float m_hitgy = std::numeric_limits<float>::quiet_NaN()
float m_hitgz = std::numeric_limits<float>::quiet_NaN()
int m_hitlayer = std::numeric_limits<int>::quiet_NaN()
int m_sector = std::numeric_limits<int>::quiet_NaN()
int m_hitpad = std::numeric_limits<int>::quiet_NaN()
int m_hittbin = std::numeric_limits<int>::quiet_NaN()
int m_col = std::numeric_limits<int>::quiet_NaN()
int m_row = std::numeric_limits<int>::quiet_NaN()
int m_strip = std::numeric_limits<int>::quiet_NaN()
float m_sclusgr = std::numeric_limits<float>::quiet_NaN()
cluster tree info
float m_sclusphi = std::numeric_limits<float>::quiet_NaN()
float m_scluseta = std::numeric_limits<float>::quiet_NaN()
float m_adc = std::numeric_limits<float>::quiet_NaN()
float m_clusmaxadc = std::numeric_limits<float>::quiet_NaN()
int m_phisize = std::numeric_limits<int>::quiet_NaN()
int m_zsize = std::numeric_limits<int>::quiet_NaN()
float m_scluslx = std::numeric_limits<float>::quiet_NaN()
float m_scluslz = std::numeric_limits<float>::quiet_NaN()
float m_sclusgx = std::numeric_limits<float>::quiet_NaN()
float m_sclusgy = std::numeric_limits<float>::quiet_NaN()
float m_sclusgz = std::numeric_limits<float>::quiet_NaN()
int m_scluslayer = std::numeric_limits<int>::quiet_NaN()
float m_scluselx = std::numeric_limits<float>::quiet_NaN()
float m_scluselz = std::numeric_limits<float>::quiet_NaN()
int m_clussector = std::numeric_limits<int>::quiet_NaN()
int m_side = std::numeric_limits<int>::quiet_NaN()
int m_staveid = std::numeric_limits<int>::quiet_NaN()
int m_chipid = std::numeric_limits<int>::quiet_NaN()
int m_strobeid = std::numeric_limits<int>::quiet_NaN()
int m_ladderzid = std::numeric_limits<int>::quiet_NaN()
int m_ladderphiid = std::numeric_limits<int>::quiet_NaN()
int m_timebucket = std::numeric_limits<int>::quiet_NaN()
int m_segtype = std::numeric_limits<int>::quiet_NaN()
int m_tileid = std::numeric_limits<int>::quiet_NaN()
std::vector< float > m_cluslx
clusters on track information
std::vector< float > m_cluslz
std::vector< float > m_cluselx
std::vector< float > m_cluselz
std::vector< float > m_clusgx
std::vector< float > m_clusgy
std::vector< float > m_clusgz
std::vector< int > m_cluslayer
std::vector< int > m_clussize
std::vector< int > m_clusedge
std::vector< int > m_clusoverlap
std::vector< uint32_t > m_clushitsetkey
std::vector< uint64_t > m_cluskeys
std::vector< float > m_idealsurfcenterx
std::vector< float > m_idealsurfcentery
std::vector< float > m_idealsurfcenterz
std::vector< float > m_idealsurfnormx
std::vector< float > m_idealsurfnormy
std::vector< float > m_idealsurfnormz
std::vector< float > m_missurfcenterx
std::vector< float > m_missurfcentery
std::vector< float > m_missurfcenterz
std::vector< float > m_missurfnormx
std::vector< float > m_missurfnormy
std::vector< float > m_missurfnormz
std::vector< float > m_clusgxideal
std::vector< float > m_clusgyideal
std::vector< float > m_clusgzideal
std::vector< float > m_idealsurfalpha
std::vector< float > m_idealsurfbeta
std::vector< float > m_idealsurfgamma
std::vector< float > m_missurfalpha
std::vector< float > m_missurfbeta
std::vector< float > m_missurfgamma
std::vector< float > m_statelx
states on track information
std::vector< float > m_statelz
std::vector< float > m_stateelx
std::vector< float > m_stateelz
std::vector< float > m_stategx
std::vector< float > m_stategy
std::vector< float > m_stategz
std::vector< float > m_statepx
std::vector< float > m_statepy
std::vector< float > m_statepz
std::vector< float > m_statepl
std::vector< float > m_statelxglobderivdx
std::vector< float > m_statelxglobderivdy
std::vector< float > m_statelxglobderivdz
std::vector< float > m_statelxglobderivdalpha
std::vector< float > m_statelxglobderivdbeta
std::vector< float > m_statelxglobderivdgamma
std::vector< float > m_statelxlocderivd0
std::vector< float > m_statelxlocderivz0
std::vector< float > m_statelxlocderivphi
std::vector< float > m_statelxlocderivtheta
std::vector< float > m_statelxlocderivqop
std::vector< float > m_statelzglobderivdx
std::vector< float > m_statelzglobderivdy
std::vector< float > m_statelzglobderivdz
std::vector< float > m_statelzglobderivdalpha
std::vector< float > m_statelzglobderivdbeta
std::vector< float > m_statelzglobderivdgamma
std::vector< float > m_statelzlocderivd0
std::vector< float > m_statelzlocderivz0
std::vector< float > m_statelzlocderivphi
std::vector< float > m_statelzlocderivtheta
std::vector< float > m_statelzlocderivqop
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = std::numeric_limits<int>::max() - 10
}
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Detailed Description
Definition at line 29 of file TrackResiduals.h.
View newest version in sPHENIX GitHub at line 29 of file TrackResiduals.h
Constructor & Destructor Documentation
TrackResiduals::TrackResiduals (const std::string & name = "TrackResiduals")
Definition at line 75 of file TrackResiduals.cc.
View newest version in sPHENIX GitHub at line 75 of file TrackResiduals.cc
TrackResiduals::~TrackResiduals () override
Definition at line 81 of file TrackResiduals.cc.
View newest version in sPHENIX GitHub at line 81 of file TrackResiduals.cc
Member Function Documentation
void TrackResiduals::alignment (bool align) inline
Definition at line 41 of file TrackResiduals.h.
View newest version in sPHENIX GitHub at line 41 of file TrackResiduals.h
References m_doAlignment.
void TrackResiduals::alignmentmapName (const std::string & name) inline
Definition at line 42 of file TrackResiduals.h.
View newest version in sPHENIX GitHub at line 42 of file TrackResiduals.h
References m_alignmentMapName, and perf_headwind::name.
void TrackResiduals::clearClusterStateVectors () private
Definition at line 99 of file TrackResiduals.cc.
View newest version in sPHENIX GitHub at line 99 of file TrackResiduals.cc
References m_clusedge, m_cluselx, m_cluselz, m_clusgx, m_clusgxideal, m_clusgy, m_clusgyideal, m_clusgz, m_clusgzideal, m_clushitsetkey, m_cluskeys, m_cluslayer, m_cluslx, m_cluslz, m_clusoverlap, m_clussize, m_idealsurfalpha, m_idealsurfbeta, m_idealsurfcenterx, m_idealsurfcentery, m_idealsurfcenterz, m_idealsurfgamma, m_idealsurfnormx, m_idealsurfnormy, m_idealsurfnormz, m_missurfalpha, m_missurfbeta, m_missurfcenterx, m_missurfcentery, m_missurfcenterz, m_missurfgamma, m_missurfnormx, m_missurfnormy, m_missurfnormz, m_stateelx, m_stateelz, m_stategx, m_stategy, m_stategz, m_statelx, m_statelxglobderivdalpha, m_statelxglobderivdbeta, m_statelxglobderivdgamma, m_statelxglobderivdx, m_statelxglobderivdy, m_statelxglobderivdz, m_statelxlocderivd0, m_statelxlocderivphi, m_statelxlocderivqop, m_statelxlocderivtheta, m_statelxlocderivz0, m_statelz, m_statelzglobderivdalpha, m_statelzglobderivdbeta, m_statelzglobderivdgamma, m_statelzglobderivdx, m_statelzglobderivdy, m_statelzglobderivdz, m_statelzlocderivd0, m_statelzlocderivphi, m_statelzlocderivqop, m_statelzlocderivtheta, m_statelzlocderivz0, m_statepx, m_statepy, and m_statepz.
Referenced by process_event().
void TrackResiduals::clusterTree () inline
Definition at line 44 of file TrackResiduals.h.
View newest version in sPHENIX GitHub at line 44 of file TrackResiduals.h
References m_doClusters.
float TrackResiduals::convertTimeToZ (ActsGeometry * geometry, TrkrDefs::cluskey cluster_key, TrkrCluster * cluster) private
Definition at line 349 of file TrackResiduals.cc.
View newest version in sPHENIX GitHub at line 349 of file TrackResiduals.cc
References ActsGeometry::get_drift_velocity(), TrkrCluster::getLocalY(), TpcDefs::getSide(), and physmon_track_finding_ttbar::z.
Referenced by fillClusterBranches().
void TrackResiduals::createBranches () private
Definition at line 964 of file TrackResiduals.cc.
View newest version in sPHENIX GitHub at line 964 of file TrackResiduals.cc
References m_adc, m_bco, m_bcotr, m_charge, m_chipid, m_clusedge, m_cluselx, m_cluselz, m_clusgx, m_clusgxideal, m_clusgy, m_clusgyideal, m_clusgz, m_clusgzideal, m_clushitsetkey, m_cluskeys, m_cluslayer, m_cluslx, m_cluslz, m_clusmaxadc, m_clusoverlap, m_clussector, m_clussize, m_clustree, m_col, m_crossing, m_deltapt, m_eta, m_event, m_hitgx, m_hitgy, m_hitgz, m_hitlayer, m_hitpad, m_hitsetkey, m_hittbin, m_hittree, m_idealsurfalpha, m_idealsurfbeta, m_idealsurfcenterx, m_idealsurfcentery, m_idealsurfcenterz, m_idealsurfgamma, m_idealsurfnormx, m_idealsurfnormy, m_idealsurfnormz, m_ladderphiid, m_ladderzid, m_missurfalpha, m_missurfbeta, m_missurfcenterx, m_missurfcentery, m_missurfcenterz, m_missurfgamma, m_missurfnormx, m_missurfnormy, m_missurfnormz, m_ndf, m_nhits, m_nintt, m_nmaps, m_nmms, m_ntpc, m_pcax, m_pcay, m_pcaz, m_phi, m_phisize, m_pt, m_px, m_py, m_pz, m_quality, m_row, m_rzint, m_rzslope, m_scluselx, m_scluselz, m_scluseta, m_sclusgr, m_sclusgx, m_sclusgy, m_sclusgz, m_scluslayer, m_scluslx, m_scluslz, m_sclusphi, m_sector, m_segtype, m_side, m_stateelx, m_stateelz, m_stategx, m_stategy, m_stategz, m_statelx, m_statelxglobderivdalpha, m_statelxglobderivdbeta, m_statelxglobderivdgamma, m_statelxglobderivdx, m_statelxglobderivdy, m_statelxglobderivdz, m_statelxlocderivd0, m_statelxlocderivphi, m_statelxlocderivqop, m_statelxlocderivtheta, m_statelxlocderivz0, m_statelz, m_statelzglobderivdalpha, m_statelzglobderivdbeta, m_statelzglobderivdgamma, m_statelzglobderivdx, m_statelzglobderivdy, m_statelzglobderivdz, m_statelzlocderivd0, m_statelzlocderivphi, m_statelzlocderivqop, m_statelzlocderivtheta, m_statelzlocderivz0, m_statepl, m_statepx, m_statepy, m_statepz, m_staveid, m_strip, m_strobeid, m_tileid, m_timebucket, m_trackid, m_tree, m_vertexid, m_vx, m_vy, m_vz, m_xyint, m_xyslope, and m_zsize.
Referenced by InitRun().
int TrackResiduals::End (PHCompositeNode *) override virtual
Called at the end of all processing.
Reimplemented from SubsysReco.
Definition at line 483 of file TrackResiduals.cc.
View newest version in sPHENIX GitHub at line 483 of file TrackResiduals.cc
References Fun4AllReturnCodes::EVENT_OK, m_clustree, m_doClusters, m_doHits, m_hittree, m_outfile, and m_tree.
void TrackResiduals::fillClusterBranches (TrkrDefs::cluskey ckey, SvtxTrack * track, PHCompositeNode * topNode) private
have cluster and state, fill vectors
skip filling the state information if a state is not there or we just ran the seeding. Fill with Nans to maintain the 1-to-1 mapping between cluster/state vectors
Switch to get ideal transforms
These calculations are taken from the wikipedia page for Euler angles, under the Tait-Bryan angle explanation. Formulas for the angles calculated from the rotation matrices depending on what order the rotation matrix is constructed are given They need to be modified to conform to the Acts basis of (x,z,y), for which the wiki page expects (x,y,z). This includes swapping the sign of some elements to account for the permutation https://en.wikipedia.org/wiki/Euler_angles#Conversion_to_other_orientation_representations
manual transform for tpc
Definition at line 697 of file TrackResiduals.cc.
View newest version in sPHENIX GitHub at line 697 of file TrackResiduals.cc
References SvtxTrack::begin_states(), Acts::UnitConstants::cm, convertTimeToZ(), Acts::eBoundLoc0, Acts::eBoundLoc1, SvtxTrack::end_states(), fillStatesWithLineFit(), Acts::Test::geometry, SvtxTrackState::get_cluskey(), ClusterErrorPara::get_clusterv5_modified_error(), SvtxTrackState::get_pathlength(), SvtxTrackState::get_px(), SvtxTrackState::get_py(), SvtxTrackState::get_pz(), SvtxTrackState::get_x(), SvtxTrackState::get_y(), SvtxTrackState::get_z(), TrkrCluster::getEdge(), TrkrDefs::getHitSetKeyFromClusKey(), TrkrDefs::getLayer(), TrkrCluster::getLocalX(), TrkrCluster::getLocalY(), TrkrCluster::getOverlap(), TrkrCluster::getPhiSize(), TrkrDefs::getTrkrId(), TrkrCluster::getZSize(), TrkrDefs::inttId, m_clusedge, m_cluselx, m_cluselz, m_clusErrPara, m_clusgx, m_clusgxideal, m_clusgy, m_clusgyideal, m_clusgz, m_clusgzideal, m_clushitsetkey, m_cluskeys, m_cluslayer, m_cluslx, m_cluslz, m_clusoverlap, m_clussize, m_idealsurfalpha, m_idealsurfbeta, m_idealsurfcenterx, m_idealsurfcentery, m_idealsurfcenterz, m_idealsurfgamma, m_idealsurfnormx, m_idealsurfnormy, m_idealsurfnormz, m_missurfalpha, m_missurfbeta, m_missurfcenterx, m_missurfcentery, m_missurfcenterz, m_missurfgamma, m_missurfnormx, m_missurfnormy, m_missurfnormz, m_nintt, m_nmaps, m_nmms, m_ntpc, m_stateelx, m_stateelz, m_stategx, m_stategy, m_stategz, m_statelx, m_statelz, m_statepl, m_statepx, m_statepy, m_statepz, m_zeroField, TrkrDefs::micromegasId, TrkrDefs::mvtxId, physmon_track_finding_ttbar::r, filter::state, surf(), TrkrDefs::tpcId, alignmentTransformationContainer::use_alignment, and Fun4AllBase::Verbosity().
Referenced by process_event().
void TrackResiduals::fillClusterTree (TrkrClusterContainer * clusters, ActsGeometry * geometry) private
Fill relevant geom info that is specific to subsystem
Definition at line 386 of file TrackResiduals.cc.
View newest version in sPHENIX GitHub at line 386 of file TrackResiduals.cc
References TrkrClusterContainer::findCluster(), ClusterErrorPara::get_clusterv5_modified_error(), MvtxDefs::getChipId(), TrkrClusterContainer::getClusters(), ActsGeometry::getGlobalPosition(), TrkrClusterContainer::getHitSetKeys(), InttDefs::getLadderPhiId(), InttDefs::getLadderZId(), TrkrDefs::getLayer(), TpcDefs::getSectorId(), MicromegasDefs::getSegmentationType(), TpcDefs::getSide(), MvtxDefs::getStaveId(), MvtxDefs::getStrobeId(), MicromegasDefs::getTileId(), InttDefs::getTimeBucketId(), TrkrDefs::inttId, m_adc, m_chipid, m_clusErrPara, m_clusmaxadc, m_clussector, m_clustree, m_ladderphiid, m_ladderzid, m_phisize, m_scluselx, m_scluselz, m_scluseta, m_sclusgr, m_sclusgx, m_sclusgy, m_sclusgz, m_scluslayer, m_scluslx, m_scluslz, m_sclusphi, m_segtype, m_side, m_staveid, m_strobeid, m_tileid, m_timebucket, m_zsize, TrkrDefs::micromegasId, TrkrDefs::mvtxId, physmon_track_finding_ttbar::r, square(), and TrkrDefs::tpcId.
Referenced by process_event().
void TrackResiduals::fillHitTree (TrkrHitSetContainer * hitmap, ActsGeometry * geometry, PHG4TpcCylinderGeomContainer * tpcGeom, PHG4CylinderGeomContainer * mvtxGeom, PHG4CylinderGeomContainer * inttGeom, PHG4CylinderGeomContainer * mmGeom) private
Fill relevant geom info that is specific to subsystem
Definition at line 499 of file TrackResiduals.cc.
View newest version in sPHENIX GitHub at line 499 of file TrackResiduals.cc
References CylinderGeomIntt::find_strip_center_localcoords(), ActsGeometry::get_drift_velocity(), CylinderGeom_Mvtx::get_local_coords_from_pixel(), MvtxDefs::getChipId(), MvtxDefs::getCol(), InttDefs::getCol(), TrkrHitSet::getHits(), TrkrHitSetContainer::getHitSets(), InttDefs::getLadderPhiId(), InttDefs::getLadderZId(), TrkrDefs::getLayer(), PHG4TpcCylinderGeomContainer::GetLayerCellGeom(), PHG4CylinderGeomContainer::GetLayerGeom(), TpcDefs::getPad(), MvtxDefs::getRow(), InttDefs::getRow(), TpcDefs::getSectorId(), MicromegasDefs::getSegmentationType(), TpcDefs::getSide(), ActsSurfaceMaps::getSiliconSurface(), MvtxDefs::getStaveId(), MicromegasDefs::getStrip(), MvtxDefs::getStrobeId(), TpcDefs::getTBin(), MicromegasDefs::getTileId(), InttDefs::getTimeBucketId(), TrkrDefs::getTrkrId(), TrkrDefs::inttId, m_adc, m_chipid, m_col, m_hitgx, m_hitgy, m_hitgz, m_hitlayer, m_hitpad, m_hitsetkey, m_hittbin, m_hittree, m_ladderphiid, m_ladderzid, m_row, m_sector, m_segtype, m_side, m_staveid, m_strip, m_strobeid, m_tileid, m_timebucket, ActsGeometry::maps(), TrkrDefs::micromegasId, TrkrDefs::mvtxId, ActsTests::PropagationDatasets::phi, PHWHERE, surf(), and TrkrDefs::tpcId.
Referenced by process_event().
void TrackResiduals::fillStatesWithLineFit (const TrkrDefs::cluskey & ckey, TrkrCluster * cluster, ActsGeometry * geometry) private
The slope/intercept params for x-y and r-z are already filled. Take two random x points and calculate y and z on the line to find 2 3D points with which to calculate the 3D line
slope/int for r-z is calculated with z as "x" variable, r as "y" variable so swap them around
otherwise the line is parallel to the surface, should not happen if we have a cluster on the surface but just fill the state vecs with nan
Definition at line 898 of file TrackResiduals.cc.
View newest version in sPHENIX GitHub at line 898 of file TrackResiduals.cc
References Acts::UnitConstants::cm, Acts::UnitConstants::e, ActsGeometry::geometry(), ActsTrackingGeometry::getGeoContext(), ActsSurfaceMaps::getSurface(), loc, m_rzint, m_rzslope, m_stategx, m_stategy, m_stategz, m_statelx, m_statelz, m_xyint, m_xyslope, ActsGeometry::maps(), physmon_track_finding_ttbar::r, r1, r2, surf(), physmon_ckf_tracking::u, v1, and v2.
Referenced by fillClusterBranches().
void TrackResiduals::hitTree () inline
Definition at line 45 of file TrackResiduals.h.
View newest version in sPHENIX GitHub at line 45 of file TrackResiduals.h
References m_doHits.
int TrackResiduals::Init (PHCompositeNode *) override virtual
Called during initialization. Typically this is where you can book histograms, and e.g. register them to Fun4AllServer (so they can be output to file using Fun4AllServer::dumpHistos() method).
Reimplemented from SubsysReco.
Definition at line 86 of file TrackResiduals.cc.
View newest version in sPHENIX GitHub at line 86 of file TrackResiduals.cc
References Fun4AllReturnCodes::EVENT_OK.
int TrackResiduals::InitRun (PHCompositeNode *) override virtual
Called for first event when run number is known. Typically this is where you may want to fetch data from database, because you know the run number.
Reimplemented from SubsysReco.
Definition at line 92 of file TrackResiduals.cc.
View newest version in sPHENIX GitHub at line 92 of file TrackResiduals.cc
References createBranches(), Fun4AllReturnCodes::EVENT_OK, m_outfile, and m_outfileName.
void TrackResiduals::lineFitClusters (std::vector< TrkrDefs::cluskey > & keys, ActsGeometry * geometry, TrkrClusterContainer * clusters) private
Definition at line 362 of file TrackResiduals.cc.
View newest version in sPHENIX GitHub at line 362 of file TrackResiduals.cc
References TrackFitUtils::getTrackletClusters(), TrackFitUtils::line_fit(), m_rzint, m_rzslope, m_xyint, m_xyslope, Acts::Test::pos, and physmon_track_finding_ttbar::r.
Referenced by process_event().
void TrackResiduals::outfileName (const std::string & name) inline
Definition at line 40 of file TrackResiduals.h.
View newest version in sPHENIX GitHub at line 40 of file TrackResiduals.h
References m_outfileName, and perf_headwind::name.
int TrackResiduals::process_event (PHCompositeNode *) override virtual
Called for each event. This is where you do the real work.
repopulate with info that is going into alignment
Reimplemented from SubsysReco.
Definition at line 175 of file TrackResiduals.cc.
View newest version in sPHENIX GitHub at line 175 of file TrackResiduals.cc
References Fun4AllReturnCodes::ABORTEVENT, clearClusterStateVectors(), Fun4AllReturnCodes::EVENT_OK, fillClusterBranches(), fillClusterTree(), fillHitTree(), Acts::Test::geometry, SvtxTrack::get_charge(), SvtxTrack::get_chisq(), TrackAnalysisUtils::get_cluster_keys(), SvtxTrack::get_crossing(), SvtxTrack::get_error(), SvtxTrack::get_ndf(), SvtxTrack::get_px(), SvtxTrack::get_py(), SvtxTrack::get_pz(), SvtxTrack::get_quality(), SvtxTrack::get_vertex_id(), SvtxTrack::get_x(), SvtxTrack::get_y(), SvtxTrack::get_z(), TrkrDefs::getTrkrId(), lineFitClusters(), m_alignmentMapName, m_bco, m_bcotr, m_charge, m_chisq, m_crossing, m_deltapt, m_doAlignment, m_doClusters, m_doHits, m_eta, m_event, m_ndf, m_nhits, m_nintt, m_nmaps, m_nmms, m_ntpc, m_pcax, m_pcay, m_pcaz, m_phi, m_pt, m_px, m_py, m_pz, m_quality, m_statelxglobderivdalpha, m_statelxglobderivdbeta, m_statelxglobderivdgamma, m_statelxglobderivdx, m_statelxglobderivdy, m_statelxglobderivdz, m_statelxlocderivd0, m_statelxlocderivphi, m_statelxlocderivqop, m_statelxlocderivtheta, m_statelxlocderivz0, m_statelzglobderivdalpha, m_statelzglobderivdbeta, m_statelzglobderivdgamma, m_statelzglobderivdx, m_statelzglobderivdy, m_statelzglobderivdz, m_statelzlocderivd0, m_statelzlocderivphi, m_statelzlocderivqop, m_statelzlocderivtheta, m_statelzlocderivz0, m_trackid, m_trackMapName, m_tree, m_vertexid, m_vx, m_vy, m_vz, m_zeroField, square(), filter::state, TrkrDefs::tpcId, and Fun4AllBase::Verbosity().
void TrackResiduals::trackmapName (const std::string & name) inline
Definition at line 43 of file TrackResiduals.h.
View newest version in sPHENIX GitHub at line 43 of file TrackResiduals.h
References m_trackMapName, and perf_headwind::name.
void TrackResiduals::zeroField () inline
Definition at line 46 of file TrackResiduals.h.
View newest version in sPHENIX GitHub at line 46 of file TrackResiduals.h
References m_zeroField.
Member Data Documentation
float TrackResiduals::m_adc = std::numeric_limits<float>::quiet_NaN() private
Definition at line 129 of file TrackResiduals.h.
View newest version in sPHENIX GitHub at line 129 of file TrackResiduals.h
Referenced by createBranches(), fillClusterTree(), and fillHitTree().
std::string TrackResiduals::m_alignmentMapName = "SvtxAlignmentStateMap" private
Definition at line 73 of file TrackResiduals.h.
View newest version in sPHENIX GitHub at line 73 of file TrackResiduals.h
Referenced by alignmentmapName(), and process_event().
uint64_t TrackResiduals::m_bco = std::numeric_limits<uint64_t>::quiet_NaN() private
Track level quantities.
Definition at line 80 of file TrackResiduals.h.
View newest version in sPHENIX GitHub at line 80 of file TrackResiduals.h
Referenced by createBranches(), and process_event().
uint64_t TrackResiduals::m_bcotr = std::numeric_limits<uint64_t>::quiet_NaN() private
Definition at line 81 of file TrackResiduals.h.
View newest version in sPHENIX GitHub at line 81 of file TrackResiduals.h
Referenced by createBranches(), and process_event().
int TrackResiduals::m_charge = std::numeric_limits<int>::quiet_NaN() private
Definition at line 91 of file TrackResiduals.h.
View newest version in sPHENIX GitHub at line 91 of file TrackResiduals.h
Referenced by createBranches(), and process_event().
int TrackResiduals::m_chipid = std::numeric_limits<int>::quiet_NaN() private
Definition at line 144 of file TrackResiduals.h.
View newest version in sPHENIX GitHub at line 144 of file TrackResiduals.h
Referenced by createBranches(), fillClusterTree(), and fillHitTree().
float TrackResiduals::m_chisq = std::numeric_limits<float>::quiet_NaN() private
Definition at line 93 of file TrackResiduals.h.
View newest version in sPHENIX GitHub at line 93 of file TrackResiduals.h
Referenced by process_event().
std::vector<int> TrackResiduals::m_clusedge private
Definition at line 162 of file TrackResiduals.h.
View newest version in sPHENIX GitHub at line 162 of file TrackResiduals.h
Referenced by clearClusterStateVectors(), createBranches(), and fillClusterBranches().
std::vector<float> TrackResiduals::m_cluselx private
Definition at line 155 of file TrackResiduals.h.
View newest version in sPHENIX GitHub at line 155 of file TrackResiduals.h
Referenced by clearClusterStateVectors(), createBranches(), and fillClusterBranches().
std::vector<float> TrackResiduals::m_cluselz private
Definition at line 156 of file TrackResiduals.h.
View newest version in sPHENIX GitHub at line 156 of file TrackResiduals.h
Referenced by clearClusterStateVectors(), createBranches(), and fillClusterBranches().
ClusterErrorPara TrackResiduals::m_clusErrPara private
Definition at line 72 of file TrackResiduals.h.
View newest version in sPHENIX GitHub at line 72 of file TrackResiduals.h
Referenced by fillClusterBranches(), and fillClusterTree().
std::vector<float> TrackResiduals::m_clusgx private
Definition at line 157 of file TrackResiduals.h.
View newest version in sPHENIX GitHub at line 157 of file TrackResiduals.h
Referenced by clearClusterStateVectors(), createBranches(), and fillClusterBranches().
std::vector<float> TrackResiduals::m_clusgxideal private
Definition at line 178 of file TrackResiduals.h.
View newest version in sPHENIX GitHub at line 178 of file TrackResiduals.h
Referenced by clearClusterStateVectors(), createBranches(), and fillClusterBranches().
std::vector<float> TrackResiduals::m_clusgy private
Definition at line 158 of file TrackResiduals.h.
View newest version in sPHENIX GitHub at line 158 of file TrackResiduals.h
Referenced by clearClusterStateVectors(), createBranches(), and fillClusterBranches().
std::vector<float> TrackResiduals::m_clusgyideal private
Definition at line 179 of file TrackResiduals.h.
View newest version in sPHENIX GitHub at line 179 of file TrackResiduals.h
Referenced by clearClusterStateVectors(), createBranches(), and fillClusterBranches().
std::vector<float> TrackResiduals::m_clusgz private
Definition at line 159 of file TrackResiduals.h.
View newest version in sPHENIX GitHub at line 159 of file TrackResiduals.h
Referenced by clearClusterStateVectors(), createBranches(), and fillClusterBranches().
std::vector<float> TrackResiduals::m_clusgzideal private
Definition at line 180 of file TrackResiduals.h.
View newest version in sPHENIX GitHub at line 180 of file TrackResiduals.h
Referenced by clearClusterStateVectors(), createBranches(), and fillClusterBranches().
std::vector<uint32_t> TrackResiduals::m_clushitsetkey private
Definition at line 164 of file TrackResiduals.h.
View newest version in sPHENIX GitHub at line 164 of file TrackResiduals.h
Referenced by clearClusterStateVectors(), createBranches(), and fillClusterBranches().
std::vector<uint64_t> TrackResiduals::m_cluskeys private
Definition at line 165 of file TrackResiduals.h.
View newest version in sPHENIX GitHub at line 165 of file TrackResiduals.h
Referenced by clearClusterStateVectors(), createBranches(), and fillClusterBranches().
std::vector<int> TrackResiduals::m_cluslayer private
Definition at line 160 of file TrackResiduals.h.
View newest version in sPHENIX GitHub at line 160 of file TrackResiduals.h
Referenced by clearClusterStateVectors(), createBranches(), and fillClusterBranches().
std::vector<float> TrackResiduals::m_cluslx private
clusters on track information
Definition at line 153 of file TrackResiduals.h.
View newest version in sPHENIX GitHub at line 153 of file TrackResiduals.h
Referenced by clearClusterStateVectors(), createBranches(), and fillClusterBranches().
std::vector<float> TrackResiduals::m_cluslz private
Definition at line 154 of file TrackResiduals.h.
View newest version in sPHENIX GitHub at line 154 of file TrackResiduals.h
Referenced by clearClusterStateVectors(), createBranches(), and fillClusterBranches().
float TrackResiduals::m_clusmaxadc = std::numeric_limits<float>::quiet_NaN() private
Definition at line 130 of file TrackResiduals.h.
View newest version in sPHENIX GitHub at line 130 of file TrackResiduals.h
Referenced by createBranches(), and fillClusterTree().
std::vector<int> TrackResiduals::m_clusoverlap private
Definition at line 163 of file TrackResiduals.h.
View newest version in sPHENIX GitHub at line 163 of file TrackResiduals.h
Referenced by clearClusterStateVectors(), createBranches(), and fillClusterBranches().
int TrackResiduals::m_clussector = std::numeric_limits<int>::quiet_NaN() private
Definition at line 141 of file TrackResiduals.h.
View newest version in sPHENIX GitHub at line 141 of file TrackResiduals.h
Referenced by createBranches(), and fillClusterTree().
std::vector<int> TrackResiduals::m_clussize private
Definition at line 161 of file TrackResiduals.h.
View newest version in sPHENIX GitHub at line 161 of file TrackResiduals.h
Referenced by clearClusterStateVectors(), createBranches(), and fillClusterBranches().
TTree* TrackResiduals::m_clustree = nullptr private
Definition at line 66 of file TrackResiduals.h.
View newest version in sPHENIX GitHub at line 66 of file TrackResiduals.h
Referenced by createBranches(), End(), and fillClusterTree().
int TrackResiduals::m_col = std::numeric_limits<int>::quiet_NaN() private
Definition at line 121 of file TrackResiduals.h.
View newest version in sPHENIX GitHub at line 121 of file TrackResiduals.h
Referenced by createBranches(), and fillHitTree().
unsigned int TrackResiduals::m_crossing = std::numeric_limits<unsigned int>::quiet_NaN() private
Definition at line 83 of file TrackResiduals.h.
View newest version in sPHENIX GitHub at line 83 of file TrackResiduals.h
Referenced by createBranches(), and process_event().
float TrackResiduals::m_deltapt = std::numeric_limits<float>::quiet_NaN() private
Definition at line 90 of file TrackResiduals.h.
View newest version in sPHENIX GitHub at line 90 of file TrackResiduals.h
Referenced by createBranches(), and process_event().
bool TrackResiduals::m_doAlignment = false private
Definition at line 76 of file TrackResiduals.h.
View newest version in sPHENIX GitHub at line 76 of file TrackResiduals.h
Referenced by alignment(), and process_event().
bool TrackResiduals::m_doClusters = false private
Definition at line 68 of file TrackResiduals.h.
View newest version in sPHENIX GitHub at line 68 of file TrackResiduals.h
Referenced by clusterTree(), End(), and process_event().
bool TrackResiduals::m_doHits = false private
Definition at line 69 of file TrackResiduals.h.
View newest version in sPHENIX GitHub at line 69 of file TrackResiduals.h
Referenced by End(), hitTree(), and process_event().
float TrackResiduals::m_eta = std::numeric_limits<float>::quiet_NaN() private
Definition at line 88 of file TrackResiduals.h.
View newest version in sPHENIX GitHub at line 88 of file TrackResiduals.h
Referenced by createBranches(), and process_event().
int TrackResiduals::m_event = 0 private
Definition at line 78 of file TrackResiduals.h.
View newest version in sPHENIX GitHub at line 78 of file TrackResiduals.h
Referenced by createBranches(), and process_event().
float TrackResiduals::m_hitgx = std::numeric_limits<float>::quiet_NaN() private
Definition at line 114 of file TrackResiduals.h.
View newest version in sPHENIX GitHub at line 114 of file TrackResiduals.h
Referenced by createBranches(), and fillHitTree().
float TrackResiduals::m_hitgy = std::numeric_limits<float>::quiet_NaN() private
Definition at line 115 of file TrackResiduals.h.
View newest version in sPHENIX GitHub at line 115 of file TrackResiduals.h
Referenced by createBranches(), and fillHitTree().
float TrackResiduals::m_hitgz = std::numeric_limits<float>::quiet_NaN() private
Definition at line 116 of file TrackResiduals.h.
View newest version in sPHENIX GitHub at line 116 of file TrackResiduals.h
Referenced by createBranches(), and fillHitTree().
int TrackResiduals::m_hitlayer = std::numeric_limits<int>::quiet_NaN() private
Definition at line 117 of file TrackResiduals.h.
View newest version in sPHENIX GitHub at line 117 of file TrackResiduals.h
Referenced by createBranches(), and fillHitTree().
int TrackResiduals::m_hitpad = std::numeric_limits<int>::quiet_NaN() private
Definition at line 119 of file TrackResiduals.h.
View newest version in sPHENIX GitHub at line 119 of file TrackResiduals.h
Referenced by createBranches(), and fillHitTree().
uint32_t TrackResiduals::m_hitsetkey = std::numeric_limits<uint32_t>::quiet_NaN() private
hit tree info
Definition at line 113 of file TrackResiduals.h.
View newest version in sPHENIX GitHub at line 113 of file TrackResiduals.h
Referenced by createBranches(), and fillHitTree().
int TrackResiduals::m_hittbin = std::numeric_limits<int>::quiet_NaN() private
Definition at line 120 of file TrackResiduals.h.
View newest version in sPHENIX GitHub at line 120 of file TrackResiduals.h
Referenced by createBranches(), and fillHitTree().
TTree* TrackResiduals::m_hittree = nullptr private
Definition at line 67 of file TrackResiduals.h.
View newest version in sPHENIX GitHub at line 67 of file TrackResiduals.h
Referenced by createBranches(), End(), and fillHitTree().
std::vector<float> TrackResiduals::m_idealsurfalpha private
Definition at line 181 of file TrackResiduals.h.
View newest version in sPHENIX GitHub at line 181 of file TrackResiduals.h
Referenced by clearClusterStateVectors(), createBranches(), and fillClusterBranches().
std::vector<float> TrackResiduals::m_idealsurfbeta private
Definition at line 182 of file TrackResiduals.h.
View newest version in sPHENIX GitHub at line 182 of file TrackResiduals.h
Referenced by clearClusterStateVectors(), createBranches(), and fillClusterBranches().
std::vector<float> TrackResiduals::m_idealsurfcenterx private
Definition at line 166 of file TrackResiduals.h.
View newest version in sPHENIX GitHub at line 166 of file TrackResiduals.h
Referenced by clearClusterStateVectors(), createBranches(), and fillClusterBranches().
std::vector<float> TrackResiduals::m_idealsurfcentery private
Definition at line 167 of file TrackResiduals.h.
View newest version in sPHENIX GitHub at line 167 of file TrackResiduals.h
Referenced by clearClusterStateVectors(), createBranches(), and fillClusterBranches().
std::vector<float> TrackResiduals::m_idealsurfcenterz private
Definition at line 168 of file TrackResiduals.h.
View newest version in sPHENIX GitHub at line 168 of file TrackResiduals.h
Referenced by clearClusterStateVectors(), createBranches(), and fillClusterBranches().
std::vector<float> TrackResiduals::m_idealsurfgamma private
Definition at line 183 of file TrackResiduals.h.
View newest version in sPHENIX GitHub at line 183 of file TrackResiduals.h
Referenced by clearClusterStateVectors(), createBranches(), and fillClusterBranches().
std::vector<float> TrackResiduals::m_idealsurfnormx private
Definition at line 169 of file TrackResiduals.h.
View newest version in sPHENIX GitHub at line 169 of file TrackResiduals.h
Referenced by clearClusterStateVectors(), createBranches(), and fillClusterBranches().
std::vector<float> TrackResiduals::m_idealsurfnormy private
Definition at line 170 of file TrackResiduals.h.
View newest version in sPHENIX GitHub at line 170 of file TrackResiduals.h
Referenced by clearClusterStateVectors(), createBranches(), and fillClusterBranches().
std::vector<float> TrackResiduals::m_idealsurfnormz private
Definition at line 171 of file TrackResiduals.h.
View newest version in sPHENIX GitHub at line 171 of file TrackResiduals.h
Referenced by clearClusterStateVectors(), createBranches(), and fillClusterBranches().
int TrackResiduals::m_ladderphiid = std::numeric_limits<int>::quiet_NaN() private
Definition at line 147 of file TrackResiduals.h.
View newest version in sPHENIX GitHub at line 147 of file TrackResiduals.h
Referenced by createBranches(), fillClusterTree(), and fillHitTree().
int TrackResiduals::m_ladderzid = std::numeric_limits<int>::quiet_NaN() private
Definition at line 146 of file TrackResiduals.h.
View newest version in sPHENIX GitHub at line 146 of file TrackResiduals.h
Referenced by createBranches(), fillClusterTree(), and fillHitTree().
std::vector<float> TrackResiduals::m_missurfalpha private
Definition at line 184 of file TrackResiduals.h.
View newest version in sPHENIX GitHub at line 184 of file TrackResiduals.h
Referenced by clearClusterStateVectors(), createBranches(), and fillClusterBranches().
std::vector<float> TrackResiduals::m_missurfbeta private
Definition at line 185 of file TrackResiduals.h.
View newest version in sPHENIX GitHub at line 185 of file TrackResiduals.h
Referenced by clearClusterStateVectors(), createBranches(), and fillClusterBranches().
std::vector<float> TrackResiduals::m_missurfcenterx private
Definition at line 172 of file TrackResiduals.h.
View newest version in sPHENIX GitHub at line 172 of file TrackResiduals.h
Referenced by clearClusterStateVectors(), createBranches(), and fillClusterBranches().
std::vector<float> TrackResiduals::m_missurfcentery private
Definition at line 173 of file TrackResiduals.h.
View newest version in sPHENIX GitHub at line 173 of file TrackResiduals.h
Referenced by clearClusterStateVectors(), createBranches(), and fillClusterBranches().
std::vector<float> TrackResiduals::m_missurfcenterz private
Definition at line 174 of file TrackResiduals.h.
View newest version in sPHENIX GitHub at line 174 of file TrackResiduals.h
Referenced by clearClusterStateVectors(), createBranches(), and fillClusterBranches().
std::vector<float> TrackResiduals::m_missurfgamma private
Definition at line 186 of file TrackResiduals.h.
View newest version in sPHENIX GitHub at line 186 of file TrackResiduals.h
Referenced by clearClusterStateVectors(), createBranches(), and fillClusterBranches().
std::vector<float> TrackResiduals::m_missurfnormx private
Definition at line 175 of file TrackResiduals.h.
View newest version in sPHENIX GitHub at line 175 of file TrackResiduals.h
Referenced by clearClusterStateVectors(), createBranches(), and fillClusterBranches().
std::vector<float> TrackResiduals::m_missurfnormy private
Definition at line 176 of file TrackResiduals.h.
View newest version in sPHENIX GitHub at line 176 of file TrackResiduals.h
Referenced by clearClusterStateVectors(), createBranches(), and fillClusterBranches().
std::vector<float> TrackResiduals::m_missurfnormz private
Definition at line 177 of file TrackResiduals.h.
View newest version in sPHENIX GitHub at line 177 of file TrackResiduals.h
Referenced by clearClusterStateVectors(), createBranches(), and fillClusterBranches().
float TrackResiduals::m_ndf = std::numeric_limits<float>::quiet_NaN() private
Definition at line 94 of file TrackResiduals.h.
View newest version in sPHENIX GitHub at line 94 of file TrackResiduals.h
Referenced by createBranches(), and process_event().
int TrackResiduals::m_nhits = std::numeric_limits<int>::quiet_NaN() private
Definition at line 95 of file TrackResiduals.h.
View newest version in sPHENIX GitHub at line 95 of file TrackResiduals.h
Referenced by createBranches(), and process_event().
int TrackResiduals::m_nintt = std::numeric_limits<int>::quiet_NaN() private
Definition at line 97 of file TrackResiduals.h.
View newest version in sPHENIX GitHub at line 97 of file TrackResiduals.h
Referenced by createBranches(), fillClusterBranches(), and process_event().
int TrackResiduals::m_nmaps = std::numeric_limits<int>::quiet_NaN() private
Definition at line 96 of file TrackResiduals.h.
View newest version in sPHENIX GitHub at line 96 of file TrackResiduals.h
Referenced by createBranches(), fillClusterBranches(), and process_event().
int TrackResiduals::m_nmms = std::numeric_limits<int>::quiet_NaN() private
Definition at line 99 of file TrackResiduals.h.
View newest version in sPHENIX GitHub at line 99 of file TrackResiduals.h
Referenced by createBranches(), fillClusterBranches(), and process_event().
int TrackResiduals::m_ntpc = std::numeric_limits<int>::quiet_NaN() private
Definition at line 98 of file TrackResiduals.h.
View newest version in sPHENIX GitHub at line 98 of file TrackResiduals.h
Referenced by createBranches(), fillClusterBranches(), and process_event().
TFile* TrackResiduals::m_outfile = nullptr private
Definition at line 64 of file TrackResiduals.h.
View newest version in sPHENIX GitHub at line 64 of file TrackResiduals.h
Referenced by End(), and InitRun().
std::string TrackResiduals::m_outfileName = "" private
Definition at line 63 of file TrackResiduals.h.
View newest version in sPHENIX GitHub at line 63 of file TrackResiduals.h
Referenced by InitRun(), and outfileName().
float TrackResiduals::m_pcax = std::numeric_limits<float>::quiet_NaN() private
Definition at line 104 of file TrackResiduals.h.
View newest version in sPHENIX GitHub at line 104 of file TrackResiduals.h
Referenced by createBranches(), and process_event().
float TrackResiduals::m_pcay = std::numeric_limits<float>::quiet_NaN() private
Definition at line 105 of file TrackResiduals.h.
View newest version in sPHENIX GitHub at line 105 of file TrackResiduals.h
Referenced by createBranches(), and process_event().
float TrackResiduals::m_pcaz = std::numeric_limits<float>::quiet_NaN() private
Definition at line 106 of file TrackResiduals.h.
View newest version in sPHENIX GitHub at line 106 of file TrackResiduals.h
Referenced by createBranches(), and process_event().
float TrackResiduals::m_phi = std::numeric_limits<float>::quiet_NaN() private
Definition at line 89 of file TrackResiduals.h.
View newest version in sPHENIX GitHub at line 89 of file TrackResiduals.h
Referenced by createBranches(), and process_event().
int TrackResiduals::m_phisize = std::numeric_limits<int>::quiet_NaN() private
Definition at line 131 of file TrackResiduals.h.
View newest version in sPHENIX GitHub at line 131 of file TrackResiduals.h
Referenced by createBranches(), and fillClusterTree().
float TrackResiduals::m_pt = std::numeric_limits<float>::quiet_NaN() private
Definition at line 87 of file TrackResiduals.h.
View newest version in sPHENIX GitHub at line 87 of file TrackResiduals.h
Referenced by createBranches(), and process_event().
float TrackResiduals::m_px = std::numeric_limits<float>::quiet_NaN() private
Definition at line 84 of file TrackResiduals.h.
View newest version in sPHENIX GitHub at line 84 of file TrackResiduals.h
Referenced by createBranches(), and process_event().
float TrackResiduals::m_py = std::numeric_limits<float>::quiet_NaN() private
Definition at line 85 of file TrackResiduals.h.
View newest version in sPHENIX GitHub at line 85 of file TrackResiduals.h
Referenced by createBranches(), and process_event().
float TrackResiduals::m_pz = std::numeric_limits<float>::quiet_NaN() private
Definition at line 86 of file TrackResiduals.h.
View newest version in sPHENIX GitHub at line 86 of file TrackResiduals.h
Referenced by createBranches(), and process_event().
float TrackResiduals::m_quality = std::numeric_limits<float>::quiet_NaN() private
Definition at line 92 of file TrackResiduals.h.
View newest version in sPHENIX GitHub at line 92 of file TrackResiduals.h
Referenced by createBranches(), and process_event().
int TrackResiduals::m_row = std::numeric_limits<int>::quiet_NaN() private
Definition at line 122 of file TrackResiduals.h.
View newest version in sPHENIX GitHub at line 122 of file TrackResiduals.h
Referenced by createBranches(), and fillHitTree().
float TrackResiduals::m_rzint = std::numeric_limits<float>::quiet_NaN() private
Definition at line 108 of file TrackResiduals.h.
View newest version in sPHENIX GitHub at line 108 of file TrackResiduals.h
Referenced by createBranches(), fillStatesWithLineFit(), and lineFitClusters().
float TrackResiduals::m_rzslope = std::numeric_limits<float>::quiet_NaN() private
Definition at line 107 of file TrackResiduals.h.
View newest version in sPHENIX GitHub at line 107 of file TrackResiduals.h
Referenced by createBranches(), fillStatesWithLineFit(), and lineFitClusters().
float TrackResiduals::m_scluselx = std::numeric_limits<float>::quiet_NaN() private
Definition at line 139 of file TrackResiduals.h.
View newest version in sPHENIX GitHub at line 139 of file TrackResiduals.h
Referenced by createBranches(), and fillClusterTree().
float TrackResiduals::m_scluselz = std::numeric_limits<float>::quiet_NaN() private
Definition at line 140 of file TrackResiduals.h.
View newest version in sPHENIX GitHub at line 140 of file TrackResiduals.h
Referenced by createBranches(), and fillClusterTree().
float TrackResiduals::m_scluseta = std::numeric_limits<float>::quiet_NaN() private
Definition at line 128 of file TrackResiduals.h.
View newest version in sPHENIX GitHub at line 128 of file TrackResiduals.h
Referenced by createBranches(), and fillClusterTree().
float TrackResiduals::m_sclusgr = std::numeric_limits<float>::quiet_NaN() private
cluster tree info
Definition at line 126 of file TrackResiduals.h.
View newest version in sPHENIX GitHub at line 126 of file TrackResiduals.h
Referenced by createBranches(), and fillClusterTree().
float TrackResiduals::m_sclusgx = std::numeric_limits<float>::quiet_NaN() private
Definition at line 135 of file TrackResiduals.h.
View newest version in sPHENIX GitHub at line 135 of file TrackResiduals.h
Referenced by createBranches(), and fillClusterTree().
float TrackResiduals::m_sclusgy = std::numeric_limits<float>::quiet_NaN() private
Definition at line 136 of file TrackResiduals.h.
View newest version in sPHENIX GitHub at line 136 of file TrackResiduals.h
Referenced by createBranches(), and fillClusterTree().
float TrackResiduals::m_sclusgz = std::numeric_limits<float>::quiet_NaN() private
Definition at line 137 of file TrackResiduals.h.
View newest version in sPHENIX GitHub at line 137 of file TrackResiduals.h
Referenced by createBranches(), and fillClusterTree().
int TrackResiduals::m_scluslayer = std::numeric_limits<int>::quiet_NaN() private
Definition at line 138 of file TrackResiduals.h.
View newest version in sPHENIX GitHub at line 138 of file TrackResiduals.h
Referenced by createBranches(), and fillClusterTree().
float TrackResiduals::m_scluslx = std::numeric_limits<float>::quiet_NaN() private
Definition at line 133 of file TrackResiduals.h.
View newest version in sPHENIX GitHub at line 133 of file TrackResiduals.h
Referenced by createBranches(), and fillClusterTree().
float TrackResiduals::m_scluslz = std::numeric_limits<float>::quiet_NaN() private
Definition at line 134 of file TrackResiduals.h.
View newest version in sPHENIX GitHub at line 134 of file TrackResiduals.h
Referenced by createBranches(), and fillClusterTree().
float TrackResiduals::m_sclusphi = std::numeric_limits<float>::quiet_NaN() private
Definition at line 127 of file TrackResiduals.h.
View newest version in sPHENIX GitHub at line 127 of file TrackResiduals.h
Referenced by createBranches(), and fillClusterTree().
int TrackResiduals::m_sector = std::numeric_limits<int>::quiet_NaN() private
Definition at line 118 of file TrackResiduals.h.
View newest version in sPHENIX GitHub at line 118 of file TrackResiduals.h
Referenced by createBranches(), and fillHitTree().
int TrackResiduals::m_segtype = std::numeric_limits<int>::quiet_NaN() private
Definition at line 149 of file TrackResiduals.h.
View newest version in sPHENIX GitHub at line 149 of file TrackResiduals.h
Referenced by createBranches(), fillClusterTree(), and fillHitTree().
int TrackResiduals::m_side = std::numeric_limits<int>::quiet_NaN() private
Definition at line 142 of file TrackResiduals.h.
View newest version in sPHENIX GitHub at line 142 of file TrackResiduals.h
Referenced by createBranches(), fillClusterTree(), and fillHitTree().
std::vector<float> TrackResiduals::m_stateelx private
Definition at line 191 of file TrackResiduals.h.
View newest version in sPHENIX GitHub at line 191 of file TrackResiduals.h
Referenced by clearClusterStateVectors(), createBranches(), and fillClusterBranches().
std::vector<float> TrackResiduals::m_stateelz private
Definition at line 192 of file TrackResiduals.h.
View newest version in sPHENIX GitHub at line 192 of file TrackResiduals.h
Referenced by clearClusterStateVectors(), createBranches(), and fillClusterBranches().
std::vector<float> TrackResiduals::m_stategx private
Definition at line 193 of file TrackResiduals.h.
View newest version in sPHENIX GitHub at line 193 of file TrackResiduals.h
Referenced by clearClusterStateVectors(), createBranches(), fillClusterBranches(), and fillStatesWithLineFit().
std::vector<float> TrackResiduals::m_stategy private
Definition at line 194 of file TrackResiduals.h.
View newest version in sPHENIX GitHub at line 194 of file TrackResiduals.h
Referenced by clearClusterStateVectors(), createBranches(), fillClusterBranches(), and fillStatesWithLineFit().
std::vector<float> TrackResiduals::m_stategz private
Definition at line 195 of file TrackResiduals.h.
View newest version in sPHENIX GitHub at line 195 of file TrackResiduals.h
Referenced by clearClusterStateVectors(), createBranches(), fillClusterBranches(), and fillStatesWithLineFit().
std::vector<float> TrackResiduals::m_statelx private
states on track information
Definition at line 189 of file TrackResiduals.h.
View newest version in sPHENIX GitHub at line 189 of file TrackResiduals.h
Referenced by clearClusterStateVectors(), createBranches(), fillClusterBranches(), and fillStatesWithLineFit().
std::vector<float> TrackResiduals::m_statelxglobderivdalpha private
Definition at line 204 of file TrackResiduals.h.
View newest version in sPHENIX GitHub at line 204 of file TrackResiduals.h
Referenced by clearClusterStateVectors(), createBranches(), and process_event().
std::vector<float> TrackResiduals::m_statelxglobderivdbeta private
Definition at line 205 of file TrackResiduals.h.
View newest version in sPHENIX GitHub at line 205 of file TrackResiduals.h
Referenced by clearClusterStateVectors(), createBranches(), and process_event().
std::vector<float> TrackResiduals::m_statelxglobderivdgamma private
Definition at line 206 of file TrackResiduals.h.
View newest version in sPHENIX GitHub at line 206 of file TrackResiduals.h
Referenced by clearClusterStateVectors(), createBranches(), and process_event().
std::vector<float> TrackResiduals::m_statelxglobderivdx private
Definition at line 201 of file TrackResiduals.h.
View newest version in sPHENIX GitHub at line 201 of file TrackResiduals.h
Referenced by clearClusterStateVectors(), createBranches(), and process_event().
std::vector<float> TrackResiduals::m_statelxglobderivdy private
Definition at line 202 of file TrackResiduals.h.
View newest version in sPHENIX GitHub at line 202 of file TrackResiduals.h
Referenced by clearClusterStateVectors(), createBranches(), and process_event().
std::vector<float> TrackResiduals::m_statelxglobderivdz private
Definition at line 203 of file TrackResiduals.h.
View newest version in sPHENIX GitHub at line 203 of file TrackResiduals.h
Referenced by clearClusterStateVectors(), createBranches(), and process_event().
std::vector<float> TrackResiduals::m_statelxlocderivd0 private
Definition at line 208 of file TrackResiduals.h.
View newest version in sPHENIX GitHub at line 208 of file TrackResiduals.h
Referenced by clearClusterStateVectors(), createBranches(), and process_event().
std::vector<float> TrackResiduals::m_statelxlocderivphi private
Definition at line 210 of file TrackResiduals.h.
View newest version in sPHENIX GitHub at line 210 of file TrackResiduals.h
Referenced by clearClusterStateVectors(), createBranches(), and process_event().
std::vector<float> TrackResiduals::m_statelxlocderivqop private
Definition at line 212 of file TrackResiduals.h.
View newest version in sPHENIX GitHub at line 212 of file TrackResiduals.h
Referenced by clearClusterStateVectors(), createBranches(), and process_event().
std::vector<float> TrackResiduals::m_statelxlocderivtheta private
Definition at line 211 of file TrackResiduals.h.
View newest version in sPHENIX GitHub at line 211 of file TrackResiduals.h
Referenced by clearClusterStateVectors(), createBranches(), and process_event().
std::vector<float> TrackResiduals::m_statelxlocderivz0 private
Definition at line 209 of file TrackResiduals.h.
View newest version in sPHENIX GitHub at line 209 of file TrackResiduals.h
Referenced by clearClusterStateVectors(), createBranches(), and process_event().
std::vector<float> TrackResiduals::m_statelz private
Definition at line 190 of file TrackResiduals.h.
View newest version in sPHENIX GitHub at line 190 of file TrackResiduals.h
Referenced by clearClusterStateVectors(), createBranches(), fillClusterBranches(), and fillStatesWithLineFit().
std::vector<float> TrackResiduals::m_statelzglobderivdalpha private
Definition at line 217 of file TrackResiduals.h.
View newest version in sPHENIX GitHub at line 217 of file TrackResiduals.h
Referenced by clearClusterStateVectors(), createBranches(), and process_event().
std::vector<float> TrackResiduals::m_statelzglobderivdbeta private
Definition at line 218 of file TrackResiduals.h.
View newest version in sPHENIX GitHub at line 218 of file TrackResiduals.h
Referenced by clearClusterStateVectors(), createBranches(), and process_event().
std::vector<float> TrackResiduals::m_statelzglobderivdgamma private
Definition at line 219 of file TrackResiduals.h.
View newest version in sPHENIX GitHub at line 219 of file TrackResiduals.h
Referenced by clearClusterStateVectors(), createBranches(), and process_event().
std::vector<float> TrackResiduals::m_statelzglobderivdx private
Definition at line 214 of file TrackResiduals.h.
View newest version in sPHENIX GitHub at line 214 of file TrackResiduals.h
Referenced by clearClusterStateVectors(), createBranches(), and process_event().
std::vector<float> TrackResiduals::m_statelzglobderivdy private
Definition at line 215 of file TrackResiduals.h.
View newest version in sPHENIX GitHub at line 215 of file TrackResiduals.h
Referenced by clearClusterStateVectors(), createBranches(), and process_event().
std::vector<float> TrackResiduals::m_statelzglobderivdz private
Definition at line 216 of file TrackResiduals.h.
View newest version in sPHENIX GitHub at line 216 of file TrackResiduals.h
Referenced by clearClusterStateVectors(), createBranches(), and process_event().
std::vector<float> TrackResiduals::m_statelzlocderivd0 private
Definition at line 221 of file TrackResiduals.h.
View newest version in sPHENIX GitHub at line 221 of file TrackResiduals.h
Referenced by clearClusterStateVectors(), createBranches(), and process_event().
std::vector<float> TrackResiduals::m_statelzlocderivphi private
Definition at line 223 of file TrackResiduals.h.
View newest version in sPHENIX GitHub at line 223 of file TrackResiduals.h
Referenced by clearClusterStateVectors(), createBranches(), and process_event().
std::vector<float> TrackResiduals::m_statelzlocderivqop private
Definition at line 225 of file TrackResiduals.h.
View newest version in sPHENIX GitHub at line 225 of file TrackResiduals.h
Referenced by clearClusterStateVectors(), createBranches(), and process_event().
std::vector<float> TrackResiduals::m_statelzlocderivtheta private
Definition at line 224 of file TrackResiduals.h.
View newest version in sPHENIX GitHub at line 224 of file TrackResiduals.h
Referenced by clearClusterStateVectors(), createBranches(), and process_event().
std::vector<float> TrackResiduals::m_statelzlocderivz0 private
Definition at line 222 of file TrackResiduals.h.
View newest version in sPHENIX GitHub at line 222 of file TrackResiduals.h
Referenced by clearClusterStateVectors(), createBranches(), and process_event().
std::vector<float> TrackResiduals::m_statepl private
Definition at line 199 of file TrackResiduals.h.
View newest version in sPHENIX GitHub at line 199 of file TrackResiduals.h
Referenced by createBranches(), and fillClusterBranches().
std::vector<float> TrackResiduals::m_statepx private
Definition at line 196 of file TrackResiduals.h.
View newest version in sPHENIX GitHub at line 196 of file TrackResiduals.h
Referenced by clearClusterStateVectors(), createBranches(), and fillClusterBranches().
std::vector<float> TrackResiduals::m_statepy private
Definition at line 197 of file TrackResiduals.h.
View newest version in sPHENIX GitHub at line 197 of file TrackResiduals.h
Referenced by clearClusterStateVectors(), createBranches(), and fillClusterBranches().
std::vector<float> TrackResiduals::m_statepz private
Definition at line 198 of file TrackResiduals.h.
View newest version in sPHENIX GitHub at line 198 of file TrackResiduals.h
Referenced by clearClusterStateVectors(), createBranches(), and fillClusterBranches().
int TrackResiduals::m_staveid = std::numeric_limits<int>::quiet_NaN() private
Definition at line 143 of file TrackResiduals.h.
View newest version in sPHENIX GitHub at line 143 of file TrackResiduals.h
Referenced by createBranches(), fillClusterTree(), and fillHitTree().
int TrackResiduals::m_strip = std::numeric_limits<int>::quiet_NaN() private
Definition at line 123 of file TrackResiduals.h.
View newest version in sPHENIX GitHub at line 123 of file TrackResiduals.h
Referenced by createBranches(), and fillHitTree().
int TrackResiduals::m_strobeid = std::numeric_limits<int>::quiet_NaN() private
Definition at line 145 of file TrackResiduals.h.
View newest version in sPHENIX GitHub at line 145 of file TrackResiduals.h
Referenced by createBranches(), fillClusterTree(), and fillHitTree().
int TrackResiduals::m_tileid = std::numeric_limits<int>::quiet_NaN() private
Definition at line 150 of file TrackResiduals.h.
View newest version in sPHENIX GitHub at line 150 of file TrackResiduals.h
Referenced by createBranches(), fillClusterTree(), and fillHitTree().
int TrackResiduals::m_timebucket = std::numeric_limits<int>::quiet_NaN() private
Definition at line 148 of file TrackResiduals.h.
View newest version in sPHENIX GitHub at line 148 of file TrackResiduals.h
Referenced by createBranches(), fillClusterTree(), and fillHitTree().
unsigned int TrackResiduals::m_trackid = std::numeric_limits<unsigned int>::quiet_NaN() private
Definition at line 82 of file TrackResiduals.h.
View newest version in sPHENIX GitHub at line 82 of file TrackResiduals.h
Referenced by createBranches(), and process_event().
std::string TrackResiduals::m_trackMapName = "SvtxTrackMap" private
Definition at line 74 of file TrackResiduals.h.
View newest version in sPHENIX GitHub at line 74 of file TrackResiduals.h
Referenced by process_event(), and trackmapName().
TTree* TrackResiduals::m_tree = nullptr private
Definition at line 65 of file TrackResiduals.h.
View newest version in sPHENIX GitHub at line 65 of file TrackResiduals.h
Referenced by createBranches(), End(), and process_event().
unsigned int TrackResiduals::m_vertexid = std::numeric_limits<unsigned int>::quiet_NaN() private
Definition at line 100 of file TrackResiduals.h.
View newest version in sPHENIX GitHub at line 100 of file TrackResiduals.h
Referenced by createBranches(), and process_event().
float TrackResiduals::m_vx = std::numeric_limits<float>::quiet_NaN() private
Definition at line 101 of file TrackResiduals.h.
View newest version in sPHENIX GitHub at line 101 of file TrackResiduals.h
Referenced by createBranches(), and process_event().
float TrackResiduals::m_vy = std::numeric_limits<float>::quiet_NaN() private
Definition at line 102 of file TrackResiduals.h.
View newest version in sPHENIX GitHub at line 102 of file TrackResiduals.h
Referenced by createBranches(), and process_event().
float TrackResiduals::m_vz = std::numeric_limits<float>::quiet_NaN() private
Definition at line 103 of file TrackResiduals.h.
View newest version in sPHENIX GitHub at line 103 of file TrackResiduals.h
Referenced by createBranches(), and process_event().
float TrackResiduals::m_xyint = std::numeric_limits<float>::quiet_NaN() private
Definition at line 110 of file TrackResiduals.h.
View newest version in sPHENIX GitHub at line 110 of file TrackResiduals.h
Referenced by createBranches(), fillStatesWithLineFit(), and lineFitClusters().
float TrackResiduals::m_xyslope = std::numeric_limits<float>::quiet_NaN() private
Definition at line 109 of file TrackResiduals.h.
View newest version in sPHENIX GitHub at line 109 of file TrackResiduals.h
Referenced by createBranches(), fillStatesWithLineFit(), and lineFitClusters().
bool TrackResiduals::m_zeroField = false private
Definition at line 70 of file TrackResiduals.h.
View newest version in sPHENIX GitHub at line 70 of file TrackResiduals.h
Referenced by fillClusterBranches(), process_event(), and zeroField().
int TrackResiduals::m_zsize = std::numeric_limits<int>::quiet_NaN() private
Definition at line 132 of file TrackResiduals.h.
View newest version in sPHENIX GitHub at line 132 of file TrackResiduals.h
Referenced by createBranches(), and fillClusterTree().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/TrackingDiagnostics/TrackResiduals.h
coresoftware/blob/master/offline/packages/TrackingDiagnostics/TrackResiduals.cc