Analysis Software: MbdEvent Class Reference
MbdEvent Class Reference
#include <coresoftware/blob/master/offline/packages/mbd/MbdEvent.h>
Public Member Functions
MbdEvent ()
virtual ~MbdEvent ()
int SetRawData (Event *event, MbdPmtContainer *mbdpmts)
int Calculate (MbdPmtContainer *mbdpmts, MbdOut *mbdout)
int InitRun ()
void Clear ()
void SetSim (const int s)
float get_bbcz ()
float get_bbczerr ()
float get_bbct0 ()
float get_bbct0err ()
int get_bbcn (const int iarm)
float get_bbcq (const int iarm)
float get_bbct (const int iarm)
float get_bbcte (const int iarm)
int get_pmtq (const int ipmt)
float get_pmttt (const int ipmt)
float get_pmttq (const int ipmt)
int get_EventNumber (void) const
void set_debugintt (const int d)
MbdSig * GetSig (const int ipmt)
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Print (const std::string &what="ALL") const
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Private Member Functions
int Read_Charge_Calib (const std::string &calfname)
int Read_TQ_T0_Offsets (const std::string &calfname)
int Read_TQ_CLK_Offsets (const std::string &calfname)
int Read_TT_CLK_Offsets (const std::string &calfname)
int DoQuickClockOffsetCalib ()
void ReadSyncFile (const char *fname="SYNC_INTTMBD.root")
Private Attributes
MbdGeom * _mbdgeom {nullptr}
MbdCalib * _mbdcal {nullptr}
int debugintt {0}
float gaincorr [MbdDefs::MBD_N_PMT] {}
float tq_t0_offsets [MbdDefs::MBD_N_PMT] {}
float tq_clk_offsets [MbdDefs::MBD_N_PMT] {}
float tt_clk_offsets [MbdDefs::MBD_N_PMT] {}
int _verbose {0}
int _runnum {0}
int _simflag {0}
Packet * p [2] {nullptr, nullptr}
Int_t m_evt {0}
Short_t m_clk {0}
Short_t m_femclk {0}
Float_t m_adc [MbdDefs::MBD_N_FEECH][MbdDefs::MAX_SAMPLES] {}
Float_t m_samp [MbdDefs::MBD_N_FEECH][MbdDefs::MAX_SAMPLES] {}
Float_t m_ampl [MbdDefs::MBD_N_FEECH] {}
std::vector< MbdSig > _mbdsig
Float_t m_pmtq [MbdDefs::MBD_N_PMT] {}
Float_t m_pmttt [MbdDefs::MBD_N_PMT] {}
Float_t m_pmttq [MbdDefs::MBD_N_PMT] {}
int do_templatefit {1}
Short_t m_bbcn [2] {}
Float_t m_bbcq [2] {}
Float_t m_bbct [2] {}
Float_t m_bbcte [2] {}
Float_t m_bbctl [2] {}
Float_t m_bbcz {std::numeric_limits<Float_t>::quiet_NaN()}
Float_t m_bbczerr {std::numeric_limits<Float_t>::quiet_NaN()}
Float_t m_bbct0 {std::numeric_limits<Float_t>::quiet_NaN()}
Float_t m_bbct0err {std::numeric_limits<Float_t>::quiet_NaN()}
Float_t _tres = std::numeric_limits<Float_t>::quiet_NaN()
TH1 * hevt_bbct [2] {}
TF1 * gausfit [2] {nullptr, nullptr}
TH2 * h2_tmax [2] = {}
float TRIG_SAMP [16] {}
TCanvas * ac {nullptr}
std::unique_ptr< TFile > _synctfile {nullptr}
TTree * _syncttree {nullptr}
int _syncevt {0}
std::vector< Int_t > bbevt
std::vector< UShort_t > bbclk
std::vector< Float_t > mybbz
std::vector< Long64_t > bco
std::vector< Double_t > intz
std::vector< Double_t > bbz
Static Private Attributes
static const int NCHPERPKT = 128
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = std::numeric_limits<int>::max() - 10
}
Protected Member Functions inherited from Fun4AllBase
Fun4AllBase (const std::string &name="NONAME")
Detailed Description
Definition at line 23 of file MbdEvent.h.
View newest version in sPHENIX GitHub at line 23 of file MbdEvent.h
Constructor & Destructor Documentation
MbdEvent::MbdEvent ()
NEED TO MAKE THIS FLEXIBLE
Definition at line 27 of file MbdEvent.cc.
View newest version in sPHENIX GitHub at line 27 of file MbdEvent.cc
References _mbdsig, MbdDefs::BBC_N_FEECH, Clear(), debugintt, do_templatefit, PHFlag::FlagExist(), PHFlag::get_IntFlag(), h2_tmax, hevt_bbct, recoConsts::instance(), MbdDefs::MAX_SAMPLES, perf_headwind::name, nsamples, Read_Charge_Calib(), Read_TQ_CLK_Offsets(), Read_TQ_T0_Offsets(), Read_TT_CLK_Offsets(), ReadSyncFile(), title, to_string(), and TRIG_SAMP.
MbdEvent::~MbdEvent () virtual
Definition at line 115 of file MbdEvent.cc.
View newest version in sPHENIX GitHub at line 115 of file MbdEvent.cc
References _mbdcal, _mbdgeom, _syncttree, ac, gausfit, h2_tmax, and hevt_bbct.
Member Function Documentation
int MbdEvent::Calculate (MbdPmtContainer * mbdpmts, MbdOut * mbdout)
Definition at line 389 of file MbdEvent.cc.
View newest version in sPHENIX GitHub at line 389 of file MbdEvent.cc
References _syncevt, _tres, _verbose, ac, MbdDefs::BBC_N_PMT, bbevt, parse_cmake_options::begin, MbdDefs::C, C, Clear(), debugintt, Acts::UnitConstants::e, end, gausfit, get_bbcn(), get_bbcq(), get_bbct(), get_bbct0(), get_bbct0err(), get_bbcz(), get_bbczerr(), MbdPmtContainer::get_pmt(), MbdPmtHit::get_q(), MbdPmtHit::get_time(), hevt_bbct, intz, m_bbcn, m_bbcq, m_bbct, m_bbct0, m_bbct0err, m_bbcte, m_bbctl, m_bbcz, m_bbczerr, m_clk, m_evt, m_femclk, mybbz, perf_headwind::name, MbdOut::Reset(), MbdOut::set_arm(), MbdOut::set_clocks(), MbdOut::set_t0(), MbdOut::set_zvtx(), and Acts::Experimental::detail::BlueprintHelper::sort().
void MbdEvent::Clear (void)
Definition at line 185 of file MbdEvent.cc.
View newest version in sPHENIX GitHub at line 185 of file MbdEvent.cc
References hevt_bbct, m_bbcn, m_bbcq, m_bbct, m_bbct0, m_bbct0err, m_bbcte, m_bbctl, m_bbcz, m_bbczerr, m_pmtq, m_pmttq, and m_pmttt.
Referenced by Calculate(), InitRun(), and MbdEvent().
int MbdEvent::DoQuickClockOffsetCalib () private
Definition at line 636 of file MbdEvent.cc.
View newest version in sPHENIX GitHub at line 636 of file MbdEvent.cc
References _mbdsig, h2_tmax, m_adc, m_samp, perf_headwind::name, TRIG_SAMP, ambiguity_solver_full_chain::x, and y.
int MbdEvent::get_bbcn (const int iarm) inline
Definition at line 41 of file MbdEvent.h.
View newest version in sPHENIX GitHub at line 41 of file MbdEvent.h
References m_bbcn.
Referenced by Calculate().
float MbdEvent::get_bbcq (const int iarm) inline
Definition at line 42 of file MbdEvent.h.
View newest version in sPHENIX GitHub at line 42 of file MbdEvent.h
References m_bbcq.
Referenced by Calculate().
float MbdEvent::get_bbct (const int iarm) inline
Definition at line 43 of file MbdEvent.h.
View newest version in sPHENIX GitHub at line 43 of file MbdEvent.h
References m_bbct.
Referenced by Calculate().
float MbdEvent::get_bbct0 () inline
Definition at line 38 of file MbdEvent.h.
View newest version in sPHENIX GitHub at line 38 of file MbdEvent.h
References m_bbct0.
Referenced by Calculate().
float MbdEvent::get_bbct0err () inline
Definition at line 39 of file MbdEvent.h.
View newest version in sPHENIX GitHub at line 39 of file MbdEvent.h
References m_bbct0err.
Referenced by Calculate().
float MbdEvent::get_bbcte (const int iarm) inline
Definition at line 44 of file MbdEvent.h.
View newest version in sPHENIX GitHub at line 44 of file MbdEvent.h
References m_bbcte.
float MbdEvent::get_bbcz () inline
Definition at line 36 of file MbdEvent.h.
View newest version in sPHENIX GitHub at line 36 of file MbdEvent.h
References m_bbcz.
Referenced by Calculate().
float MbdEvent::get_bbczerr () inline
Definition at line 37 of file MbdEvent.h.
View newest version in sPHENIX GitHub at line 37 of file MbdEvent.h
References m_bbczerr.
Referenced by Calculate().
int MbdEvent::get_EventNumber (void) const inline
Definition at line 50 of file MbdEvent.h.
View newest version in sPHENIX GitHub at line 50 of file MbdEvent.h
References m_evt.
int MbdEvent::get_pmtq (const int ipmt) inline
Definition at line 46 of file MbdEvent.h.
View newest version in sPHENIX GitHub at line 46 of file MbdEvent.h
References m_pmtq.
float MbdEvent::get_pmttq (const int ipmt) inline
Definition at line 48 of file MbdEvent.h.
View newest version in sPHENIX GitHub at line 48 of file MbdEvent.h
References m_pmttq.
float MbdEvent::get_pmttt (const int ipmt) inline
Definition at line 47 of file MbdEvent.h.
View newest version in sPHENIX GitHub at line 47 of file MbdEvent.h
References m_pmttt.
MbdSig* MbdEvent::GetSig (const int ipmt) inline
Definition at line 54 of file MbdEvent.h.
View newest version in sPHENIX GitHub at line 54 of file MbdEvent.h
References _mbdsig.
int MbdEvent::InitRun ()
Definition at line 132 of file MbdEvent.cc.
View newest version in sPHENIX GitHub at line 132 of file MbdEvent.cc
References _mbdcal, _mbdgeom, _mbdsig, _runnum, _simflag, _verbose, MbdDefs::BBC_N_FEECH, Clear(), do_templatefit, MbdCalib::Download_All(), PHFlag::get_IntFlag(), MbdCalib::get_sampmax(), MbdCalib::get_shape(), MbdCalib::get_sherr(), MbdGeom::get_type(), h2_tmax, recoConsts::instance(), and PHWHERE.
int MbdEvent::Read_Charge_Calib (const std::string & calfname) private
Definition at line 670 of file MbdEvent.cc.
View newest version in sPHENIX GitHub at line 670 of file MbdEvent.cc
References gaincorr, and width.
Referenced by MbdEvent().
int MbdEvent::Read_TQ_CLK_Offsets (const std::string & calfname) private
Definition at line 718 of file MbdEvent.cc.
View newest version in sPHENIX GitHub at line 718 of file MbdEvent.cc
References MbdDefs::BBC_N_PMT, and tq_clk_offsets.
Referenced by MbdEvent().
int MbdEvent::Read_TQ_T0_Offsets (const std::string & calfname) private
Definition at line 693 of file MbdEvent.cc.
View newest version in sPHENIX GitHub at line 693 of file MbdEvent.cc
References MbdDefs::BBC_N_PMT, sigma, and tq_t0_offsets.
Referenced by MbdEvent().
int MbdEvent::Read_TT_CLK_Offsets (const std::string & calfname) private
Definition at line 740 of file MbdEvent.cc.
View newest version in sPHENIX GitHub at line 740 of file MbdEvent.cc
References MbdDefs::BBC_N_PMT, and tt_clk_offsets.
Referenced by MbdEvent().
void MbdEvent::ReadSyncFile (const char * fname = "SYNC_INTTMBD.root") private
Definition at line 761 of file MbdEvent.cc.
View newest version in sPHENIX GitHub at line 761 of file MbdEvent.cc
References _synctfile, _syncttree, bbclk, bbevt, bbz, bco, INTTVtxZ::fname, intz, and mybbz.
Referenced by MbdEvent().
void MbdEvent::set_debugintt (const int d) inline
Definition at line 52 of file MbdEvent.h.
View newest version in sPHENIX GitHub at line 52 of file MbdEvent.h
References debugintt.
int MbdEvent::SetRawData (Event * event, MbdPmtContainer * mbdpmts)
Definition at line 211 of file MbdEvent.cc.
View newest version in sPHENIX GitHub at line 211 of file MbdEvent.cc
References _mbdcal, _mbdgeom, _mbdsig, Fun4AllReturnCodes::ABORTEVENT, MbdDefs::BBC_N_FEECH, MbdDefs::BBC_N_PMT, DATAEVENT, Fun4AllReturnCodes::DISCARDEVENT, do_templatefit, feech, MbdGeom::get_pmt(), MbdPmtContainer::get_pmt(), MbdCalib::get_qgain(), MbdCalib::get_sampmax(), MbdCalib::get_tq0(), MbdGeom::get_type(), Packet::iValue(), m_adc, m_ampl, m_clk, m_evt, m_femclk, m_pmtq, m_pmttq, m_pmttt, m_samp, MbdDefs::MAX_SAMPLES, NCHPERPKT, p, PHWHERE, MbdPmtContainer::set_npmt(), MbdPmtHit::set_pmt(), parse_cmake_options::type, and Fun4AllBase::Verbosity().
void MbdEvent::SetSim (const int s) inline
Definition at line 34 of file MbdEvent.h.
View newest version in sPHENIX GitHub at line 34 of file MbdEvent.h
References _simflag, and physmon_simulation::s.
Member Data Documentation
MbdCalib* MbdEvent::_mbdcal {nullptr} private
Definition at line 60 of file MbdEvent.h.
View newest version in sPHENIX GitHub at line 60 of file MbdEvent.h
Referenced by InitRun(), SetRawData(), and ~MbdEvent().
MbdGeom* MbdEvent::_mbdgeom {nullptr} private
Definition at line 59 of file MbdEvent.h.
View newest version in sPHENIX GitHub at line 59 of file MbdEvent.h
Referenced by InitRun(), SetRawData(), and ~MbdEvent().
std::vector<MbdSig> MbdEvent::_mbdsig private
Definition at line 93 of file MbdEvent.h.
View newest version in sPHENIX GitHub at line 93 of file MbdEvent.h
Referenced by DoQuickClockOffsetCalib(), GetSig(), InitRun(), MbdEvent(), and SetRawData().
int MbdEvent::_runnum {0} private
Definition at line 79 of file MbdEvent.h.
View newest version in sPHENIX GitHub at line 79 of file MbdEvent.h
Referenced by InitRun().
int MbdEvent::_simflag {0} private
Definition at line 80 of file MbdEvent.h.
View newest version in sPHENIX GitHub at line 80 of file MbdEvent.h
Referenced by InitRun(), and SetSim().
int MbdEvent::_syncevt {0} private
Definition at line 125 of file MbdEvent.h.
View newest version in sPHENIX GitHub at line 125 of file MbdEvent.h
Referenced by Calculate().
std::unique_ptr<TFile> MbdEvent::_synctfile {nullptr} private
Definition at line 123 of file MbdEvent.h.
View newest version in sPHENIX GitHub at line 123 of file MbdEvent.h
Referenced by ReadSyncFile().
TTree* MbdEvent::_syncttree {nullptr} private
Definition at line 124 of file MbdEvent.h.
View newest version in sPHENIX GitHub at line 124 of file MbdEvent.h
Referenced by ReadSyncFile(), and ~MbdEvent().
Float_t MbdEvent::_tres = std::numeric_limits<Float_t>::quiet_NaN() private
Definition at line 111 of file MbdEvent.h.
View newest version in sPHENIX GitHub at line 111 of file MbdEvent.h
Referenced by Calculate().
int MbdEvent::_verbose {0} private
Definition at line 78 of file MbdEvent.h.
View newest version in sPHENIX GitHub at line 78 of file MbdEvent.h
Referenced by Calculate(), and InitRun().
TCanvas* MbdEvent::ac {nullptr} private
Definition at line 120 of file MbdEvent.h.
View newest version in sPHENIX GitHub at line 120 of file MbdEvent.h
Referenced by Calculate(), and ~MbdEvent().
std::vector<UShort_t> MbdEvent::bbclk private
Definition at line 127 of file MbdEvent.h.
View newest version in sPHENIX GitHub at line 127 of file MbdEvent.h
Referenced by ReadSyncFile().
std::vector<Int_t> MbdEvent::bbevt private
Definition at line 126 of file MbdEvent.h.
View newest version in sPHENIX GitHub at line 126 of file MbdEvent.h
Referenced by Calculate(), and ReadSyncFile().
std::vector<Double_t> MbdEvent::bbz private
Definition at line 131 of file MbdEvent.h.
View newest version in sPHENIX GitHub at line 131 of file MbdEvent.h
Referenced by ReadSyncFile().
std::vector<Long64_t> MbdEvent::bco private
Definition at line 129 of file MbdEvent.h.
View newest version in sPHENIX GitHub at line 129 of file MbdEvent.h
Referenced by ReadSyncFile().
int MbdEvent::debugintt {0} private
Definition at line 68 of file MbdEvent.h.
View newest version in sPHENIX GitHub at line 68 of file MbdEvent.h
Referenced by Calculate(), MbdEvent(), and set_debugintt().
int MbdEvent::do_templatefit {1} private
Definition at line 99 of file MbdEvent.h.
View newest version in sPHENIX GitHub at line 99 of file MbdEvent.h
Referenced by InitRun(), MbdEvent(), and SetRawData().
float MbdEvent::gaincorr[MbdDefs::MBD_N_PMT] {} private
Definition at line 71 of file MbdEvent.h.
View newest version in sPHENIX GitHub at line 71 of file MbdEvent.h
Referenced by Read_Charge_Calib().
TF1* MbdEvent::gausfit[2] {nullptr, nullptr} private
Definition at line 114 of file MbdEvent.h.
View newest version in sPHENIX GitHub at line 114 of file MbdEvent.h
Referenced by Calculate(), and ~MbdEvent().
TH2* MbdEvent::h2_tmax[2] = {} private
Definition at line 116 of file MbdEvent.h.
View newest version in sPHENIX GitHub at line 116 of file MbdEvent.h
Referenced by DoQuickClockOffsetCalib(), InitRun(), MbdEvent(), and ~MbdEvent().
TH1* MbdEvent::hevt_bbct[2] {} private
Definition at line 113 of file MbdEvent.h.
View newest version in sPHENIX GitHub at line 113 of file MbdEvent.h
Referenced by Calculate(), Clear(), MbdEvent(), and ~MbdEvent().
std::vector<Double_t> MbdEvent::intz private
Definition at line 130 of file MbdEvent.h.
View newest version in sPHENIX GitHub at line 130 of file MbdEvent.h
Referenced by Calculate(), and ReadSyncFile().
Float_t MbdEvent::m_adc[MbdDefs::MBD_N_FEECH][MbdDefs::MAX_SAMPLES] {} private
Definition at line 89 of file MbdEvent.h.
View newest version in sPHENIX GitHub at line 89 of file MbdEvent.h
Referenced by DoQuickClockOffsetCalib(), and SetRawData().
Float_t MbdEvent::m_ampl[MbdDefs::MBD_N_FEECH] {} private
Definition at line 91 of file MbdEvent.h.
View newest version in sPHENIX GitHub at line 91 of file MbdEvent.h
Referenced by SetRawData().
Short_t MbdEvent::m_bbcn[2] {} private
Definition at line 102 of file MbdEvent.h.
View newest version in sPHENIX GitHub at line 102 of file MbdEvent.h
Referenced by Calculate(), Clear(), and get_bbcn().
Float_t MbdEvent::m_bbcq[2] {} private
Definition at line 103 of file MbdEvent.h.
View newest version in sPHENIX GitHub at line 103 of file MbdEvent.h
Referenced by Calculate(), Clear(), and get_bbcq().
Float_t MbdEvent::m_bbct[2] {} private
Definition at line 104 of file MbdEvent.h.
View newest version in sPHENIX GitHub at line 104 of file MbdEvent.h
Referenced by Calculate(), Clear(), and get_bbct().
Float_t MbdEvent::m_bbct0 {std::numeric_limits<Float_t>::quiet_NaN()} private
Definition at line 109 of file MbdEvent.h.
View newest version in sPHENIX GitHub at line 109 of file MbdEvent.h
Referenced by Calculate(), Clear(), and get_bbct0().
Float_t MbdEvent::m_bbct0err {std::numeric_limits<Float_t>::quiet_NaN()} private
Definition at line 110 of file MbdEvent.h.
View newest version in sPHENIX GitHub at line 110 of file MbdEvent.h
Referenced by Calculate(), Clear(), and get_bbct0err().
Float_t MbdEvent::m_bbcte[2] {} private
Definition at line 105 of file MbdEvent.h.
View newest version in sPHENIX GitHub at line 105 of file MbdEvent.h
Referenced by Calculate(), Clear(), and get_bbcte().
Float_t MbdEvent::m_bbctl[2] {} private
Definition at line 106 of file MbdEvent.h.
View newest version in sPHENIX GitHub at line 106 of file MbdEvent.h
Referenced by Calculate(), and Clear().
Float_t MbdEvent::m_bbcz {std::numeric_limits<Float_t>::quiet_NaN()} private
Definition at line 107 of file MbdEvent.h.
View newest version in sPHENIX GitHub at line 107 of file MbdEvent.h
Referenced by Calculate(), Clear(), and get_bbcz().
Float_t MbdEvent::m_bbczerr {std::numeric_limits<Float_t>::quiet_NaN()} private
Definition at line 108 of file MbdEvent.h.
View newest version in sPHENIX GitHub at line 108 of file MbdEvent.h
Referenced by Calculate(), Clear(), and get_bbczerr().
Short_t MbdEvent::m_clk {0} private
Definition at line 85 of file MbdEvent.h.
View newest version in sPHENIX GitHub at line 85 of file MbdEvent.h
Referenced by Calculate(), and SetRawData().
Int_t MbdEvent::m_evt {0} private
Definition at line 84 of file MbdEvent.h.
View newest version in sPHENIX GitHub at line 84 of file MbdEvent.h
Referenced by Calculate(), get_EventNumber(), and SetRawData().
Short_t MbdEvent::m_femclk {0} private
Definition at line 86 of file MbdEvent.h.
View newest version in sPHENIX GitHub at line 86 of file MbdEvent.h
Referenced by Calculate(), and SetRawData().
Float_t MbdEvent::m_pmtq[MbdDefs::MBD_N_PMT] {} private
Definition at line 95 of file MbdEvent.h.
View newest version in sPHENIX GitHub at line 95 of file MbdEvent.h
Referenced by Clear(), get_pmtq(), and SetRawData().
Float_t MbdEvent::m_pmttq[MbdDefs::MBD_N_PMT] {} private
Definition at line 97 of file MbdEvent.h.
View newest version in sPHENIX GitHub at line 97 of file MbdEvent.h
Referenced by Clear(), get_pmttq(), and SetRawData().
Float_t MbdEvent::m_pmttt[MbdDefs::MBD_N_PMT] {} private
Definition at line 96 of file MbdEvent.h.
View newest version in sPHENIX GitHub at line 96 of file MbdEvent.h
Referenced by Clear(), get_pmttt(), and SetRawData().
Float_t MbdEvent::m_samp[MbdDefs::MBD_N_FEECH][MbdDefs::MAX_SAMPLES] {} private
Definition at line 90 of file MbdEvent.h.
View newest version in sPHENIX GitHub at line 90 of file MbdEvent.h
Referenced by DoQuickClockOffsetCalib(), and SetRawData().
std::vector<Float_t> MbdEvent::mybbz private
Definition at line 128 of file MbdEvent.h.
View newest version in sPHENIX GitHub at line 128 of file MbdEvent.h
Referenced by Calculate(), and ReadSyncFile().
const int MbdEvent::NCHPERPKT = 128 static private
Definition at line 57 of file MbdEvent.h.
View newest version in sPHENIX GitHub at line 57 of file MbdEvent.h
Referenced by SetRawData().
Packet* MbdEvent::p[2] {nullptr, nullptr} private
Definition at line 81 of file MbdEvent.h.
View newest version in sPHENIX GitHub at line 81 of file MbdEvent.h
Referenced by SetRawData().
float MbdEvent::tq_clk_offsets[MbdDefs::MBD_N_PMT] {} private
Definition at line 73 of file MbdEvent.h.
View newest version in sPHENIX GitHub at line 73 of file MbdEvent.h
Referenced by Read_TQ_CLK_Offsets().
float MbdEvent::tq_t0_offsets[MbdDefs::MBD_N_PMT] {} private
Definition at line 72 of file MbdEvent.h.
View newest version in sPHENIX GitHub at line 72 of file MbdEvent.h
Referenced by Read_TQ_T0_Offsets().
float MbdEvent::TRIG_SAMP[16] {} private
Definition at line 118 of file MbdEvent.h.
View newest version in sPHENIX GitHub at line 118 of file MbdEvent.h
Referenced by DoQuickClockOffsetCalib(), and MbdEvent().
float MbdEvent::tt_clk_offsets[MbdDefs::MBD_N_PMT] {} private
Definition at line 74 of file MbdEvent.h.
View newest version in sPHENIX GitHub at line 74 of file MbdEvent.h
Referenced by Read_TT_CLK_Offsets().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/mbd/MbdEvent.h
coresoftware/blob/master/offline/packages/mbd/MbdEvent.cc