Analysis Software: TpcClusterizer Class Reference
TpcClusterizer Class Reference
#include <coresoftware/blob/master/offline/packages/tpc/TpcClusterizer.h>
Public Member Functions
TpcClusterizer (const std::string &name="TpcClusterizer")
~TpcClusterizer () override=default
int InitRun (PHCompositeNode *topNode) override
int process_event (PHCompositeNode *topNode) override
int End (PHCompositeNode *topNode) override
Called at the end of all processing.
void set_sector_fiducial_cut (const double cut)
void set_store_hits (bool store_hits)
void set_use_nn (bool use_nn)
void set_do_hit_association (bool do_assoc)
void set_do_wedge_emulation (bool do_wedge)
void set_do_sequential (bool do_seq)
void set_do_split (bool split)
void set_pedestal (float val)
void set_seed_threshold (float val)
void set_edge_threshold (float val)
void set_min_err_squared (float val)
void set_min_clus_size (float val)
void set_min_adc_sum (float val)
void set_remove_singles (bool do_sing)
void set_read_raw (bool read_raw)
void set_max_cluster_half_size_phi (unsigned short size)
void set_max_cluster_half_size_z (unsigned short size)
void set_ClusHitsVerbose (bool set=true)
void set_rawdata_reco ()
Public Member Functions inherited from SubsysReco
~SubsysReco () override
virtual int EndRun (const int)
Called at the end of each run.
virtual int Init (PHCompositeNode *)
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
void Print (const std::string &="ALL") const override
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Public Attributes
ClusHitsVerbosev1 * mClusHitsVerbose { nullptr }
Private Member Functions
bool is_in_sector_boundary (int phibin, int sector, PHG4TpcCylinderGeom *layergeom) const
Private Attributes
bool record_ClusHitsVerbose { false }
TrkrHitSetContainer * m_hits = nullptr
RawHitSetContainer * m_rawhits = nullptr
TrkrClusterContainer * m_clusterlist = nullptr
TrkrClusterHitAssoc * m_clusterhitassoc = nullptr
ActsGeometry * m_tGeometry = nullptr
bool _store_hits = false
bool _use_nn = false
bool do_hit_assoc = true
bool do_wedge_emulation = false
bool do_sequential = false
bool do_read_raw = false
bool do_singles = false
bool do_split = true
double pedestal = 74.4
double seed_threshold = 5
double edge_threshold = 0
double min_err_squared = 0.01
double min_clus_size = 1
double min_adc_sum = 10
double SectorFiducialCut = 0.5
unsigned short MaxClusterHalfSizePhi = 3
unsigned short MaxClusterHalfSizeT = 5
double m_tdriftmax = 0
double AdcClockPeriod = 53.0
double m_sampa_tbias = 39.6
TrainingHitsContainer * m_training
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = std::numeric_limits<int>::max() - 10
}
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Detailed Description
Definition at line 29 of file TpcClusterizer.h.
View newest version in sPHENIX GitHub at line 29 of file TpcClusterizer.h
Constructor & Destructor Documentation
TpcClusterizer::TpcClusterizer (const std::string & name = "TpcClusterizer")
Definition at line 781 of file TpcClusterizer.cc.
View newest version in sPHENIX GitHub at line 781 of file TpcClusterizer.cc
TpcClusterizer::~TpcClusterizer () override default
Member Function Documentation
int TpcClusterizer::End (PHCompositeNode *) override virtual
Called at the end of all processing.
Reimplemented from SubsysReco.
Definition at line 1338 of file TpcClusterizer.cc.
View newest version in sPHENIX GitHub at line 1338 of file TpcClusterizer.cc
References Fun4AllReturnCodes::EVENT_OK.
int TpcClusterizer::InitRun (PHCompositeNode *) override virtual
Called for first event when run number is known. Typically this is where you may want to fetch data from database, because you know the run number.
Reimplemented from SubsysReco.
Definition at line 818 of file TpcClusterizer.cc.
View newest version in sPHENIX GitHub at line 818 of file TpcClusterizer.cc
References _store_hits, _use_nn, Fun4AllReturnCodes::ABORTRUN, PHCompositeNode::addNode(), assert, Acts::UnitConstants::e, Fun4AllReturnCodes::EVENT_OK, PHNodeIterator::findFirst(), mClusHitsVerbose, PHWHERE, and record_ClusHitsVerbose.
bool TpcClusterizer::is_in_sector_boundary (int phibin, int sector, PHG4TpcCylinderGeom * layergeom) const private
Definition at line 786 of file TpcClusterizer.cc.
View newest version in sPHENIX GitHub at line 786 of file TpcClusterizer.cc
References double(), PHG4TpcCylinderGeom::get_phibins(), PHG4TpcCylinderGeom::get_radius(), and SectorFiducialCut.
int TpcClusterizer::process_event (PHCompositeNode *) override virtual
Called for each event. This is where you do the real work.
Reimplemented from SubsysReco.
Definition at line 930 of file TpcClusterizer.cc.
View newest version in sPHENIX GitHub at line 930 of file TpcClusterizer.cc
References _store_hits, Fun4AllReturnCodes::ABORTRUN, AdcClockPeriod, TrkrClusterHitAssoc::addAssoc(), TrkrClusterContainer::addClusterSpecifyKey(), ClusHitsVerbosev1::addPhiHit(), ClusHitsVerbosev1::addZHit(), test_fpe::count, configureMap::data, distance(), do_hit_assoc, do_read_raw, do_sequential, do_singles, do_split, do_wedge_emulation, edge_threshold, Fun4AllReturnCodes::EVENT_OK, PHNodeIterator::findFirst(), TrkrDefs::genClusKey(), TpcDefs::genHitSetKey(), ActsGeometry::get_drift_velocity(), PHG4TpcCylinderGeom::get_phibins(), PHG4TpcCylinderGeom::get_radius(), PHG4TpcCylinderGeom::get_zbins(), RawHitSetContainer::getHitSets(), TrkrHitSetContainer::getHitSets(), TrkrDefs::getLayer(), PHG4TpcCylinderGeomContainer::GetLayerCellGeom(), TpcDefs::getSectorId(), TpcDefs::getSide(), index, layer, m_clusterhitassoc, m_clusterlist, m_hits, m_rawhits, m_sampa_tbias, m_tdriftmax, m_tGeometry, m_training, MaxClusterHalfSizePhi, MaxClusterHalfSizeT, mClusHitsVerbose, min_adc_sum, min_clus_size, min_err_squared, pedestal, PHWHERE, printf(), ClusHitsVerbosev1::push_hits(), seed_threshold, TrkrClusterContainer::size(), TrkrDefs::tpcId, alignmentTransformationContainer::use_alignment, TrainingHitsContainer::v_hits, and Fun4AllBase::Verbosity().
void TpcClusterizer::set_ClusHitsVerbose (bool set = true) inline
Definition at line 57 of file TpcClusterizer.h.
View newest version in sPHENIX GitHub at line 57 of file TpcClusterizer.h
References record_ClusHitsVerbose.
void TpcClusterizer::set_do_hit_association (bool do_assoc) inline
Definition at line 42 of file TpcClusterizer.h.
View newest version in sPHENIX GitHub at line 42 of file TpcClusterizer.h
References do_hit_assoc.
Referenced by set_rawdata_reco().
void TpcClusterizer::set_do_sequential (bool do_seq) inline
Definition at line 44 of file TpcClusterizer.h.
View newest version in sPHENIX GitHub at line 44 of file TpcClusterizer.h
References do_sequential.
void TpcClusterizer::set_do_split (bool split) inline
Definition at line 45 of file TpcClusterizer.h.
View newest version in sPHENIX GitHub at line 45 of file TpcClusterizer.h
References do_split.
Referenced by set_rawdata_reco().
void TpcClusterizer::set_do_wedge_emulation (bool do_wedge) inline
Definition at line 43 of file TpcClusterizer.h.
View newest version in sPHENIX GitHub at line 43 of file TpcClusterizer.h
References do_wedge_emulation.
void TpcClusterizer::set_edge_threshold (float val) inline
Definition at line 48 of file TpcClusterizer.h.
View newest version in sPHENIX GitHub at line 48 of file TpcClusterizer.h
References edge_threshold.
Referenced by set_rawdata_reco().
void TpcClusterizer::set_max_cluster_half_size_phi (unsigned short size) inline
Definition at line 54 of file TpcClusterizer.h.
View newest version in sPHENIX GitHub at line 54 of file TpcClusterizer.h
References MaxClusterHalfSizePhi, and size.
Referenced by set_rawdata_reco().
void TpcClusterizer::set_max_cluster_half_size_z (unsigned short size) inline
Definition at line 55 of file TpcClusterizer.h.
View newest version in sPHENIX GitHub at line 55 of file TpcClusterizer.h
References MaxClusterHalfSizeT, and size.
Referenced by set_rawdata_reco().
void TpcClusterizer::set_min_adc_sum (float val) inline
Definition at line 51 of file TpcClusterizer.h.
View newest version in sPHENIX GitHub at line 51 of file TpcClusterizer.h
References min_adc_sum.
Referenced by set_rawdata_reco().
void TpcClusterizer::set_min_clus_size (float val) inline
Definition at line 50 of file TpcClusterizer.h.
View newest version in sPHENIX GitHub at line 50 of file TpcClusterizer.h
References min_clus_size.
Referenced by set_rawdata_reco().
void TpcClusterizer::set_min_err_squared (float val) inline
Definition at line 49 of file TpcClusterizer.h.
View newest version in sPHENIX GitHub at line 49 of file TpcClusterizer.h
References min_err_squared.
Referenced by set_rawdata_reco().
void TpcClusterizer::set_pedestal (float val) inline
Definition at line 46 of file TpcClusterizer.h.
View newest version in sPHENIX GitHub at line 46 of file TpcClusterizer.h
References pedestal.
Referenced by set_rawdata_reco().
void TpcClusterizer::set_rawdata_reco () inline
Definition at line 58 of file TpcClusterizer.h.
View newest version in sPHENIX GitHub at line 58 of file TpcClusterizer.h
References set_do_hit_association(), set_do_split(), set_edge_threshold(), set_max_cluster_half_size_phi(), set_max_cluster_half_size_z(), set_min_adc_sum(), set_min_clus_size(), set_min_err_squared(), set_pedestal(), set_remove_singles(), and set_seed_threshold().
void TpcClusterizer::set_read_raw (bool read_raw) inline
Definition at line 53 of file TpcClusterizer.h.
View newest version in sPHENIX GitHub at line 53 of file TpcClusterizer.h
References do_read_raw.
void TpcClusterizer::set_remove_singles (bool do_sing) inline
Definition at line 52 of file TpcClusterizer.h.
View newest version in sPHENIX GitHub at line 52 of file TpcClusterizer.h
References do_singles.
Referenced by set_rawdata_reco().
void TpcClusterizer::set_sector_fiducial_cut (const double cut) inline
Definition at line 39 of file TpcClusterizer.h.
View newest version in sPHENIX GitHub at line 39 of file TpcClusterizer.h
References SectorFiducialCut.
void TpcClusterizer::set_seed_threshold (float val) inline
Definition at line 47 of file TpcClusterizer.h.
View newest version in sPHENIX GitHub at line 47 of file TpcClusterizer.h
References seed_threshold.
Referenced by set_rawdata_reco().
void TpcClusterizer::set_store_hits (bool store_hits) inline
Definition at line 40 of file TpcClusterizer.h.
View newest version in sPHENIX GitHub at line 40 of file TpcClusterizer.h
References _store_hits.
void TpcClusterizer::set_use_nn (bool use_nn) inline
Definition at line 41 of file TpcClusterizer.h.
View newest version in sPHENIX GitHub at line 41 of file TpcClusterizer.h
References _use_nn.
Member Data Documentation
bool TpcClusterizer::_store_hits = false private
Definition at line 82 of file TpcClusterizer.h.
View newest version in sPHENIX GitHub at line 82 of file TpcClusterizer.h
Referenced by InitRun(), process_event(), and set_store_hits().
bool TpcClusterizer::_use_nn = false private
Definition at line 83 of file TpcClusterizer.h.
View newest version in sPHENIX GitHub at line 83 of file TpcClusterizer.h
Referenced by InitRun(), and set_use_nn().
double TpcClusterizer::AdcClockPeriod = 53.0 private
Definition at line 101 of file TpcClusterizer.h.
View newest version in sPHENIX GitHub at line 101 of file TpcClusterizer.h
Referenced by process_event().
bool TpcClusterizer::do_hit_assoc = true private
Definition at line 84 of file TpcClusterizer.h.
View newest version in sPHENIX GitHub at line 84 of file TpcClusterizer.h
Referenced by process_event(), and set_do_hit_association().
bool TpcClusterizer::do_read_raw = false private
Definition at line 87 of file TpcClusterizer.h.
View newest version in sPHENIX GitHub at line 87 of file TpcClusterizer.h
Referenced by process_event(), and set_read_raw().
bool TpcClusterizer::do_sequential = false private
Definition at line 86 of file TpcClusterizer.h.
View newest version in sPHENIX GitHub at line 86 of file TpcClusterizer.h
Referenced by process_event(), and set_do_sequential().
bool TpcClusterizer::do_singles = false private
Definition at line 88 of file TpcClusterizer.h.
View newest version in sPHENIX GitHub at line 88 of file TpcClusterizer.h
Referenced by process_event(), and set_remove_singles().
bool TpcClusterizer::do_split = true private
Definition at line 89 of file TpcClusterizer.h.
View newest version in sPHENIX GitHub at line 89 of file TpcClusterizer.h
Referenced by process_event(), and set_do_split().
bool TpcClusterizer::do_wedge_emulation = false private
Definition at line 85 of file TpcClusterizer.h.
View newest version in sPHENIX GitHub at line 85 of file TpcClusterizer.h
Referenced by process_event(), and set_do_wedge_emulation().
double TpcClusterizer::edge_threshold = 0 private
Definition at line 92 of file TpcClusterizer.h.
View newest version in sPHENIX GitHub at line 92 of file TpcClusterizer.h
Referenced by process_event(), and set_edge_threshold().
TrkrClusterHitAssoc* TpcClusterizer::m_clusterhitassoc = nullptr private
Definition at line 80 of file TpcClusterizer.h.
View newest version in sPHENIX GitHub at line 80 of file TpcClusterizer.h
Referenced by process_event().
TrkrClusterContainer* TpcClusterizer::m_clusterlist = nullptr private
Definition at line 79 of file TpcClusterizer.h.
View newest version in sPHENIX GitHub at line 79 of file TpcClusterizer.h
Referenced by process_event().
TrkrHitSetContainer* TpcClusterizer::m_hits = nullptr private
Definition at line 77 of file TpcClusterizer.h.
View newest version in sPHENIX GitHub at line 77 of file TpcClusterizer.h
Referenced by process_event().
RawHitSetContainer* TpcClusterizer::m_rawhits = nullptr private
Definition at line 78 of file TpcClusterizer.h.
View newest version in sPHENIX GitHub at line 78 of file TpcClusterizer.h
Referenced by process_event().
double TpcClusterizer::m_sampa_tbias = 39.6 private
Definition at line 105 of file TpcClusterizer.h.
View newest version in sPHENIX GitHub at line 105 of file TpcClusterizer.h
Referenced by process_event().
double TpcClusterizer::m_tdriftmax = 0 private
Definition at line 100 of file TpcClusterizer.h.
View newest version in sPHENIX GitHub at line 100 of file TpcClusterizer.h
Referenced by process_event().
ActsGeometry* TpcClusterizer::m_tGeometry = nullptr private
Definition at line 81 of file TpcClusterizer.h.
View newest version in sPHENIX GitHub at line 81 of file TpcClusterizer.h
Referenced by process_event().
TrainingHitsContainer* TpcClusterizer::m_training private
Definition at line 107 of file TpcClusterizer.h.
View newest version in sPHENIX GitHub at line 107 of file TpcClusterizer.h
Referenced by process_event().
unsigned short TpcClusterizer::MaxClusterHalfSizePhi = 3 private
Definition at line 97 of file TpcClusterizer.h.
View newest version in sPHENIX GitHub at line 97 of file TpcClusterizer.h
Referenced by process_event(), and set_max_cluster_half_size_phi().
unsigned short TpcClusterizer::MaxClusterHalfSizeT = 5 private
Definition at line 98 of file TpcClusterizer.h.
View newest version in sPHENIX GitHub at line 98 of file TpcClusterizer.h
Referenced by process_event(), and set_max_cluster_half_size_z().
ClusHitsVerbosev1* TpcClusterizer::mClusHitsVerbose { nullptr }
Definition at line 71 of file TpcClusterizer.h.
View newest version in sPHENIX GitHub at line 71 of file TpcClusterizer.h
Referenced by InitRun(), and process_event().
double TpcClusterizer::min_adc_sum = 10 private
Definition at line 95 of file TpcClusterizer.h.
View newest version in sPHENIX GitHub at line 95 of file TpcClusterizer.h
Referenced by process_event(), and set_min_adc_sum().
double TpcClusterizer::min_clus_size = 1 private
Definition at line 94 of file TpcClusterizer.h.
View newest version in sPHENIX GitHub at line 94 of file TpcClusterizer.h
Referenced by process_event(), and set_min_clus_size().
double TpcClusterizer::min_err_squared = 0.01 private
Definition at line 93 of file TpcClusterizer.h.
View newest version in sPHENIX GitHub at line 93 of file TpcClusterizer.h
Referenced by process_event(), and set_min_err_squared().
double TpcClusterizer::pedestal = 74.4 private
Definition at line 90 of file TpcClusterizer.h.
View newest version in sPHENIX GitHub at line 90 of file TpcClusterizer.h
Referenced by process_event(), and set_pedestal().
bool TpcClusterizer::record_ClusHitsVerbose { false } private
Definition at line 75 of file TpcClusterizer.h.
View newest version in sPHENIX GitHub at line 75 of file TpcClusterizer.h
Referenced by InitRun(), and set_ClusHitsVerbose().
double TpcClusterizer::SectorFiducialCut = 0.5 private
Definition at line 96 of file TpcClusterizer.h.
View newest version in sPHENIX GitHub at line 96 of file TpcClusterizer.h
Referenced by is_in_sector_boundary(), and set_sector_fiducial_cut().
double TpcClusterizer::seed_threshold = 5 private
Definition at line 91 of file TpcClusterizer.h.
View newest version in sPHENIX GitHub at line 91 of file TpcClusterizer.h
Referenced by process_event(), and set_seed_threshold().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/tpc/TpcClusterizer.h
coresoftware/blob/master/offline/packages/tpc/TpcClusterizer.cc