Analysis Software: PHGenFitTrkFitter Class Reference
PHGenFitTrkFitter Class Reference
Refit SvtxTracks with PHGenFit.
#include <coresoftware/blob/master/offline/packages/trackreco/PHGenFitTrkFitter.h>
Public Types
enum OutPutMode { MakeNewNode, OverwriteOriginalNode, DebugMode }
enum DetectorType {
MIE, MAPS_TPC, MAPS_IT_TPC, LADDER_MAPS_TPC,
LADDER_MAPS_IT_TPC, LADDER_MAPS_LADDER_IT_TPC, MAPS_LADDER_IT_TPC
}
Public Member Functions
PHGenFitTrkFitter (const std::string &name="PHGenFitTrkFitter")
Default constructor.
int Init (PHCompositeNode *) override
Initialization, called for initialization.
int InitRun (PHCompositeNode *) override
Initialization Run, called for initialization of a run.
int process_event (PHCompositeNode *) override
Process Event, called for each event.
int End (PHCompositeNode *) override
End, write and close files.
void set_eval_filename (const char *file)
std::string get_eval_filename () const
void fill_eval_tree (PHCompositeNode *)
void init_eval_tree ()
void reset_eval_variables ()
bool is_do_eval () const
void set_do_eval (bool doEval)
bool is_do_evt_display () const
void set_do_evt_display (bool doEvtDisplay)
const std::string & get_vertexing_method () const
void set_vertexing_method (const std::string &vertexingMethod)
bool is_fit_primary_tracks () const
void set_fit_primary_tracks (bool fitPrimaryTracks)
OutPutMode get_output_mode () const
void set_output_mode (OutPutMode outputMode)
const std::string & get_track_fitting_alg_name () const
void set_track_fitting_alg_name (const std::string &trackFittingAlgName)
int get_primary_pid_guess () const
void set_primary_pid_guess (int primaryPidGuess)
double get_fit_min_pT () const
void set_fit_min_pT (double cutMinPT)
bool is_over_write_svtxtrackmap () const
void set_over_write_svtxtrackmap (bool overWriteSvtxtrackmap)
bool is_use_truth_vertex () const
void set_use_truth_vertex (bool useTruthVertex)
double get_vertex_min_ndf () const
void set_vertex_min_ndf (double vertexMinPT)
void set_fit_silicon_mms (bool)
fit only tracks with silicon+MM hits
void set_use_micromegas (bool value)
require micromegas in SiliconMM fits
disabled layers interface
void disable_layer (int layer, bool disabled=true)
mark layer as disbled
void set_disabled_layers (const std::set< int > &)
set disabled layers
void clear_disabled_layers ()
clear disabled layers
const std::set< int > & get_disabled_layers () const
get disabled layers
Public Member Functions inherited from SubsysReco
~SubsysReco () override
virtual int EndRun (const int)
Called at the end of each run.
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
void Print (const std::string &="ALL") const override
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Private Member Functions
int GetNodes (PHCompositeNode *)
Get all the nodes.
int CreateNodes (PHCompositeNode *)
Create New nodes.
Acts::Vector3 getGlobalPosition (TrkrDefs::cluskey, TrkrCluster *, short int crossing)
get global position for a given cluster
std::shared_ptr< PHGenFit::Track > ReFitTrack (PHCompositeNode *, const SvtxTrack *intrack, const SvtxVertex *invertex=nullptr)
std::shared_ptr< SvtxTrack > MakeSvtxTrack (const SvtxTrack *svtxtrack, const std::shared_ptr< PHGenFit::Track > &genfit_track, const SvtxVertex *vertex=nullptr)
Make SvtxTrack from PHGenFit::Track and SvtxTrack.
bool FillSvtxVertexMap (const std::vector< genfit::GFRaveVertex * > &rave_vertices, const std::vector< genfit::Track * > &gf_tracks)
Fill SvtxVertexMap from GFRaveVertexes and Tracks.
bool pos_cov_XYZ_to_RZ (const TVector3 &n, const TMatrixF &pos_in, const TMatrixF &cov_in, TMatrixF &pos_out, TMatrixF &cov_out) const
Private Attributes
int _event = 0
Event counter.
OutPutMode _output_mode = PHGenFitTrkFitter::MakeNewNode
bool _over_write_svtxtrackmap = true
bool _fit_primary_tracks = false
bool _use_truth_vertex = false
std::set< int > _disabled_layers
disabled layers
bool m_fit_silicon_mms = false
bool m_use_micromegas = true
requires micromegas present when fitting silicon-MM surfaces
std::string _track_fitting_alg_name = "DafRef"
KalmanFitterRefTrack, KalmanFitter, DafSimple, DafRef.
int _primary_pid_guess = 211
double _fit_min_pT = 0.1
double _vertex_min_ndf = 20
std::shared_ptr< PHGenFit::Fitter > _fitter
std::shared_ptr
< genfit::GFRaveVertexFactory > _vertex_finder
std::string _vertexing_method = "avr-smoothing:1-minweight:0.5-primcut:9-seccut:9"
https://rave.hepforge.org/trac/wiki/RaveMethods
ActsGeometry * m_tgeometry = nullptr
acts geometry
PHG4TruthInfoContainer * _truth_container = nullptr
Input Node pointers.
TrkrClusterContainer * m_clustermap = nullptr
TrackSeedContainer * m_seedMap = nullptr
TrackSeedContainer * m_tpcSeeds = nullptr
TrackSeedContainer * m_siliconSeeds = nullptr
SvtxVertexMap * _vertexmap = nullptr
SvtxTrackMap * m_trackMap = nullptr
Output Node pointers.
SvtxTrackMap * m_trackMap_refit = nullptr
SvtxTrackMap * m_primary_trackMap = nullptr
SvtxVertexMap * m_vertexMap_refit = nullptr
TpcClusterZCrossingCorrection m_clusterCrossingCorrection
TpcDistortionCorrectionContainer * m_dcc_static = nullptr
TpcDistortionCorrectionContainer * m_dcc_average = nullptr
TpcDistortionCorrectionContainer * m_dcc_fluctuation = nullptr
TpcDistortionCorrection m_distortionCorrection
tpc distortion correction utility class
ClusterErrorPara m_cluster_error_parametrization
cluster error parametrisation
bool _do_eval = false
std::string _eval_outname = "PHGenFitTrkFitter_eval.root"
eval output filename
TTree * _eval_tree = nullptr
TClonesArray * _tca_particlemap = nullptr
TClonesArray * _tca_vtxmap = nullptr
TClonesArray * _tca_trackmap = nullptr
TClonesArray * _tca_vertexmap = nullptr
TClonesArray * _tca_trackmap_refit = nullptr
TClonesArray * _tca_primtrackmap = nullptr
TClonesArray * _tcam_vertexMap_refit = nullptr
TTree * _cluster_eval_tree = nullptr
float _cluster_eval_tree_x = 0
float _cluster_eval_tree_y = 0
float _cluster_eval_tree_z = 0
float _cluster_eval_tree_gx = 0
float _cluster_eval_tree_gy = 0
float _cluster_eval_tree_gz = 0
bool _do_evt_display = false
std::map< unsigned int,
unsigned int > _rave_vertex_gf_track_map
Additional Inherited Members
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Detailed Description
Refit SvtxTracks with PHGenFit.
Definition at line 65 of file PHGenFitTrkFitter.h.
View newest version in sPHENIX GitHub at line 65 of file PHGenFitTrkFitter.h
Member Enumeration Documentation
enum PHGenFitTrkFitter::DetectorType
Enumerator:
MIE
MAPS_TPC
MAPS_IT_TPC
LADDER_MAPS_TPC
LADDER_MAPS_IT_TPC
LADDER_MAPS_LADDER_IT_TPC
MAPS_LADDER_IT_TPC
Definition at line 80 of file PHGenFitTrkFitter.h.
View newest version in sPHENIX GitHub at line 80 of file PHGenFitTrkFitter.h
enum PHGenFitTrkFitter::OutPutMode
OverwriteOriginalNode: default mode, overwrite original node MakeNewNode: Output extra new refit nodes DebugMode: overwrite original node also make extra new refit nodes
Enumerator:
MakeNewNode
OverwriteOriginalNode
DebugMode
Definition at line 73 of file PHGenFitTrkFitter.h.
View newest version in sPHENIX GitHub at line 73 of file PHGenFitTrkFitter.h
Constructor & Destructor Documentation
PHGenFitTrkFitter::PHGenFitTrkFitter (const std::string & name = "PHGenFitTrkFitter")
Default constructor.
Definition at line 177 of file PHGenFitTrkFitter.cc.
View newest version in sPHENIX GitHub at line 177 of file PHGenFitTrkFitter.cc
References _cluster_eval_tree_gx, _cluster_eval_tree_gy, _cluster_eval_tree_gz, _cluster_eval_tree_x, _cluster_eval_tree_y, _cluster_eval_tree_z, Fun4AllBase::Verbosity(), and WILD_FLOAT.
Member Function Documentation
void PHGenFitTrkFitter::clear_disabled_layers ()
clear disabled layers
Definition at line 794 of file PHGenFitTrkFitter.cc.
View newest version in sPHENIX GitHub at line 794 of file PHGenFitTrkFitter.cc
References _disabled_layers.
int PHGenFitTrkFitter::CreateNodes (PHCompositeNode * topNode) private
Create New nodes.
Definition at line 722 of file PHGenFitTrkFitter.cc.
View newest version in sPHENIX GitHub at line 722 of file PHGenFitTrkFitter.cc
References _fit_primary_tracks, _output_mode, _over_write_svtxtrackmap, Fun4AllReturnCodes::ABORTEVENT, DebugMode, Fun4AllReturnCodes::EVENT_OK, PHNodeIterator::findFirst(), m_primary_trackMap, m_trackMap, m_trackMap_refit, m_vertexMap_refit, PHWHERE, and Fun4AllBase::Verbosity().
Referenced by InitRun().
void PHGenFitTrkFitter::disable_layer (int layer, bool disabled = true)
mark layer as disbled
Definition at line 783 of file PHGenFitTrkFitter.cc.
View newest version in sPHENIX GitHub at line 783 of file PHGenFitTrkFitter.cc
References _disabled_layers.
Referenced by set_fit_silicon_mms().
int PHGenFitTrkFitter::End (PHCompositeNode *) override virtual
End, write and close files.
Reimplemented from SubsysReco.
Definition at line 573 of file PHGenFitTrkFitter.cc.
View newest version in sPHENIX GitHub at line 573 of file PHGenFitTrkFitter.cc
References _cluster_eval_tree, _do_eval, _do_evt_display, _eval_outname, _eval_tree, _fitter, PHTFileServer::cd(), Fun4AllReturnCodes::EVENT_OK, PHTFileServer::get(), PHWHERE, and Fun4AllBase::Verbosity().
void PHGenFitTrkFitter::fill_eval_tree (PHCompositeNode *)
Definition at line 593 of file PHGenFitTrkFitter.cc.
View newest version in sPHENIX GitHub at line 593 of file PHGenFitTrkFitter.cc
References _eval_tree, _fit_primary_tracks, _truth_container, _vertexmap, PHG4TruthInfoContainer::GetPrimaryParticleRange(), PHG4TruthInfoContainer::GetPrimaryVtxRange(), i, m_primary_trackMap, m_trackMap, m_trackMap_refit, m_vertexMap_refit, and reset_eval_variables().
Referenced by process_event().
bool PHGenFitTrkFitter::FillSvtxVertexMap (const std::vector< genfit::GFRaveVertex * > & rave_vertices, const std::vector< genfit::Track * > & gf_tracks) private
Fill SvtxVertexMap from GFRaveVertexes and Tracks.
Definition at line 1657 of file PHGenFitTrkFitter.cc.
View newest version in sPHENIX GitHub at line 1657 of file PHGenFitTrkFitter.cc
References _rave_vertex_gf_track_map, SvtxVertex_v1::get_position(), genfit::GFRaveVertex::getChi2(), genfit::GFRaveVertex::getCov(), genfit::GFRaveVertex::getNdf(), genfit::GFRaveVertex::getNTracks(), genfit::GFRaveVertex::getParameters(), genfit::GFRaveVertex::getPos(), genfit::GFRaveTrackParameters::getTrack(), i, SvtxVertexMap::identify(), SvtxVertexMap::insert_clone(), SvtxVertex_v1::insert_track(), j, LogError, m_vertexMap_refit, PHWHERE, SvtxVertex_v1::set_chisq(), SvtxVertex_v1::set_error(), SvtxVertex_v1::set_ndof(), SvtxVertex_v1::set_position(), and Fun4AllBase::Verbosity().
Referenced by process_event().
const std::set< int > & PHGenFitTrkFitter::get_disabled_layers () const
get disabled layers
Definition at line 798 of file PHGenFitTrkFitter.cc.
View newest version in sPHENIX GitHub at line 798 of file PHGenFitTrkFitter.cc
References _disabled_layers.
std::string PHGenFitTrkFitter::get_eval_filename () const inline
Definition at line 113 of file PHGenFitTrkFitter.h.
View newest version in sPHENIX GitHub at line 113 of file PHGenFitTrkFitter.h
References _eval_outname.
double PHGenFitTrkFitter::get_fit_min_pT () const inline
Definition at line 195 of file PHGenFitTrkFitter.h.
View newest version in sPHENIX GitHub at line 195 of file PHGenFitTrkFitter.h
References _fit_min_pT.
OutPutMode PHGenFitTrkFitter::get_output_mode () const inline
Definition at line 162 of file PHGenFitTrkFitter.h.
View newest version in sPHENIX GitHub at line 162 of file PHGenFitTrkFitter.h
References _output_mode.
int PHGenFitTrkFitter::get_primary_pid_guess () const inline
Definition at line 185 of file PHGenFitTrkFitter.h.
View newest version in sPHENIX GitHub at line 185 of file PHGenFitTrkFitter.h
References _primary_pid_guess.
const std::string& PHGenFitTrkFitter::get_track_fitting_alg_name () const inline
Definition at line 175 of file PHGenFitTrkFitter.h.
View newest version in sPHENIX GitHub at line 175 of file PHGenFitTrkFitter.h
References _track_fitting_alg_name.
double PHGenFitTrkFitter::get_vertex_min_ndf () const inline
Definition at line 225 of file PHGenFitTrkFitter.h.
View newest version in sPHENIX GitHub at line 225 of file PHGenFitTrkFitter.h
References _vertex_min_ndf.
const std::string& PHGenFitTrkFitter::get_vertexing_method () const inline
Definition at line 142 of file PHGenFitTrkFitter.h.
View newest version in sPHENIX GitHub at line 142 of file PHGenFitTrkFitter.h
References _vertexing_method.
Acts::Vector3 PHGenFitTrkFitter::getGlobalPosition (TrkrDefs::cluskey key, TrkrCluster * cluster, short int crossing) private
get global position for a given cluster
uses ActsTransformation to convert cluster local position into global coordinates
Definition at line 941 of file PHGenFitTrkFitter.cc.
View newest version in sPHENIX GitHub at line 941 of file PHGenFitTrkFitter.cc
References TpcClusterZCrossingCorrection::correctZ(), TpcDistortionCorrection::get_corrected_position(), ActsGeometry::getGlobalPosition(), TpcDefs::getSide(), TrkrDefs::getTrkrId(), m_clusterCrossingCorrection, m_dcc_average, m_dcc_fluctuation, m_dcc_static, m_distortionCorrection, m_tgeometry, and TrkrDefs::tpcId.
Referenced by MakeSvtxTrack(), and ReFitTrack().
int PHGenFitTrkFitter::GetNodes (PHCompositeNode * topNode) private
Get all the nodes.
Definition at line 818 of file PHGenFitTrkFitter.cc.
View newest version in sPHENIX GitHub at line 818 of file PHGenFitTrkFitter.cc
References _event, _fit_primary_tracks, _output_mode, _over_write_svtxtrackmap, _truth_container, _vertexmap, Fun4AllReturnCodes::ABORTEVENT, DebugMode, Fun4AllReturnCodes::EVENT_OK, m_clustermap, m_dcc_average, m_dcc_fluctuation, m_dcc_static, m_primary_trackMap, m_seedMap, m_siliconSeeds, m_tgeometry, m_tpcSeeds, m_trackMap, m_trackMap_refit, m_vertexMap_refit, and PHWHERE.
Referenced by process_event().
int PHGenFitTrkFitter::Init (PHCompositeNode *) override virtual
Initialization, called for initialization.
Reimplemented from SubsysReco.
Definition at line 192 of file PHGenFitTrkFitter.cc.
View newest version in sPHENIX GitHub at line 192 of file PHGenFitTrkFitter.cc
References Fun4AllReturnCodes::EVENT_OK.
void PHGenFitTrkFitter::init_eval_tree ()
Definition at line 656 of file PHGenFitTrkFitter.cc.
View newest version in sPHENIX GitHub at line 656 of file PHGenFitTrkFitter.cc
References _cluster_eval_tree, _cluster_eval_tree_gx, _cluster_eval_tree_gy, _cluster_eval_tree_gz, _cluster_eval_tree_x, _cluster_eval_tree_y, _cluster_eval_tree_z, _eval_tree, _fit_primary_tracks, _tca_particlemap, _tca_primtrackmap, _tca_trackmap, _tca_trackmap_refit, _tca_vertexmap, _tca_vtxmap, and _tcam_vertexMap_refit.
Referenced by InitRun().
int PHGenFitTrkFitter::InitRun (PHCompositeNode * topNode) override virtual
Initialization Run, called for initialization of a run.
Reimplemented from SubsysReco.
Definition at line 198 of file PHGenFitTrkFitter.cc.
View newest version in sPHENIX GitHub at line 198 of file PHGenFitTrkFitter.cc
References _disabled_layers, _do_eval, _do_evt_display, _eval_outname, _fitter, _track_fitting_alg_name, _vertex_finder, _vertexing_method, Fun4AllReturnCodes::ABORTRUN, CreateNodes(), Fun4AllReturnCodes::EVENT_OK, ckf::field, PHTFileServer::get(), PHFieldUtility::GetFieldMapNode(), PHGenFit::Fitter::getInstance(), PHGeomUtility::GetTGeoManager(), init_eval_tree(), layer, m_fit_silicon_mms, m_use_micromegas, PHTFileServer::open(), PHWHERE, and Fun4AllBase::Verbosity().
bool PHGenFitTrkFitter::is_do_eval () const inline
Definition at line 122 of file PHGenFitTrkFitter.h.
View newest version in sPHENIX GitHub at line 122 of file PHGenFitTrkFitter.h
References _do_eval.
bool PHGenFitTrkFitter::is_do_evt_display () const inline
Definition at line 132 of file PHGenFitTrkFitter.h.
View newest version in sPHENIX GitHub at line 132 of file PHGenFitTrkFitter.h
References _do_evt_display.
bool PHGenFitTrkFitter::is_fit_primary_tracks () const inline
Definition at line 152 of file PHGenFitTrkFitter.h.
View newest version in sPHENIX GitHub at line 152 of file PHGenFitTrkFitter.h
References _fit_primary_tracks.
bool PHGenFitTrkFitter::is_over_write_svtxtrackmap () const inline
Definition at line 205 of file PHGenFitTrkFitter.h.
View newest version in sPHENIX GitHub at line 205 of file PHGenFitTrkFitter.h
References _over_write_svtxtrackmap.
bool PHGenFitTrkFitter::is_use_truth_vertex () const inline
Definition at line 215 of file PHGenFitTrkFitter.h.
View newest version in sPHENIX GitHub at line 215 of file PHGenFitTrkFitter.h
References _use_truth_vertex.
std::shared_ptr< SvtxTrack > PHGenFitTrkFitter::MakeSvtxTrack (const SvtxTrack * svtxtrack, const std::shared_ptr< PHGenFit::Track > & genfit_track, const SvtxVertex * vertex = nullptr) private
Make SvtxTrack from PHGenFit::Track and SvtxTrack.
1/p, u'/z', v'/z', u, v u is defined as momentum X beam line at POCA of the beam line v is alone the beam line so u is the dca2d direction
Definition at line 1244 of file PHGenFitTrkFitter.cc.
View newest version in sPHENIX GitHub at line 1244 of file PHGenFitTrkFitter.cc
References _disabled_layers, _truth_container, _use_truth_vertex, assert, genfit::calcAverageState(), Acts::Test::cov, genfit::StateOnPlane::extrapolateToPlane(), genfit::StateOnPlane::extrapolateToPoint(), TrkrClusterContainer::findCluster(), genfit::MeasuredStateOnPlane::get6DCov(), genfit::MeasuredStateOnPlane::get6DStateCov(), TrackAnalysisUtils::get_cluster_keys(), SvtxVertex::get_error(), PHG4VtxPoint::get_x(), SvtxVertex::get_x(), PHG4VtxPoint::get_y(), SvtxVertex::get_y(), PHG4VtxPoint::get_z(), SvtxVertex::get_z(), genfit::Track::getCardinalRep(), genfit::MeasuredStateOnPlane::getCov(), genfit::TrackPoint::getFitterInfo(), getGlobalPosition(), TrkrDefs::getLayer(), genfit::StateOnPlane::getMom(), genfit::Track::getNumPointsWithMeasurement(), genfit::StateOnPlane::getPlane(), genfit::Track::getPointWithMeasurementAndFitterInfo(), genfit::StateOnPlane::getPos(), PHG4TruthInfoContainer::GetPrimaryVertexIndex(), PHG4TruthInfoContainer::GetPrimaryVtx(), genfit::StateOnPlane::getState(), i, train_ambiguity_solver::id, j, layer, LogWarning, m_clustermap, ActsTests::PropagationDatasets::phi, PHWHERE, Acts::Test::pos, pos_cov_XYZ_to_RZ(), physmon_track_finding_ttbar::r, square(), filter::state, Acts::Test::tmp(), physmon_ckf_tracking::u, testSigmaEff::v, and Fun4AllBase::Verbosity().
Referenced by process_event().
bool PHGenFitTrkFitter::pos_cov_XYZ_to_RZ (const TVector3 & n, const TMatrixF & pos_in, const TMatrixF & cov_in, TMatrixF & pos_out, TMatrixF & cov_out) const private
Definition at line 1720 of file PHGenFitTrkFitter.cc.
View newest version in sPHENIX GitHub at line 1720 of file PHGenFitTrkFitter.cc
References LogWarning, ActsTests::PropagationDatasets::phi, Acts::IntegrationTest::R, physmon_track_finding_ttbar::r, and Fun4AllBase::Verbosity().
Referenced by MakeSvtxTrack().
int PHGenFitTrkFitter::process_event (PHCompositeNode * topNode) override virtual
Process Event, called for each event.
Optionally fit track as primary track by including collision vertex, This part need to be called after FillSvtxVertexMap
rf_phgf_track stands for Refit_PHGenFit_Track
Reimplemented from SubsysReco.
Definition at line 254 of file PHGenFitTrkFitter.cc.
View newest version in sPHENIX GitHub at line 254 of file PHGenFitTrkFitter.cc
References _do_eval, _do_evt_display, _event, _fit_min_pT, _fit_primary_tracks, _fitter, _output_mode, _over_write_svtxtrackmap, _rave_vertex_gf_track_map, _vertex_finder, _vertex_min_ndf, SvtxTrackMap::begin(), TrackSeedContainer::begin(), SvtxTrack::CopyFrom(), DebugMode, SvtxTrackMap::empty(), SvtxTrackMap::end(), TrackSeedContainer::end(), SvtxTrackMap::erase(), Fun4AllReturnCodes::EVENT_OK, fill_eval_tree(), FillSvtxVertexMap(), SvtxVertexMap::get(), TrackSeedContainer::get(), TrackSeed::get_crossing(), SvtxTrack::get_pt(), TrackSeed::get_silicon_seed_index(), TrackSeed::get_tpc_seed_index(), SvtxVertex::get_x(), SvtxVertex::get_y(), SvtxVertex::get_z(), GetNodes(), i, SvtxTrackMap::insert(), LogDebug, LogError, m_clustermap, m_primary_trackMap, m_seedMap, m_siliconSeeds, m_tgeometry, m_tpcSeeds, m_trackMap, m_trackMap_refit, m_vertexMap_refit, MakeSvtxTrack(), PHWHERE, ReFitTrack(), PHObject::Reset(), TrackSeed::set_crossing(), SvtxVertexMap::size(), t, and Fun4AllBase::Verbosity().
std::shared_ptr< PHGenFit::Track > PHGenFitTrkFitter::ReFitTrack (PHCompositeNode * topNode, const SvtxTrack * intrack, const SvtxVertex * invertex = nullptr) private
mu+: -13 mu-: 13 pi+: 211 pi-: -211 e-: 11 e+: -11
Fit the track ret code 0 means 0 error or good status
Definition at line 980 of file PHGenFitTrkFitter.cc.
View newest version in sPHENIX GitHub at line 980 of file PHGenFitTrkFitter.cc
References _disabled_layers, _fitter, _primary_pid_guess, assert, Acts::Test::cov, TrkrClusterContainer::findCluster(), SvtxVertex::get_chisq(), TrackAnalysisUtils::get_cluster_keys(), SvtxTrack::get_crossing(), SvtxVertex::get_error(), SvtxVertex::get_ndof(), SvtxVertex::get_x(), SvtxVertex::get_y(), SvtxVertex::get_z(), getGlobalPosition(), TrkrDefs::getHitSetKeyFromClusKey(), TrkrDefs::getLayer(), TrkrCluster::getRPhiError(), ActsSurfaceMaps::getSiliconSurface(), MicromegasDefs::getTileId(), TrkrDefs::getTrkrId(), TrkrCluster::getZError(), i, SvtxTrack::identify(), TrkrDefs::inttId, j, layer, LogError, LogWarning, m_clustermap, m_fit_silicon_mms, m_tgeometry, m_use_micromegas, ActsGeometry::maps(), TrkrDefs::micromegasId, TrkrDefs::mvtxId, n, PHWHERE, Acts::Test::pos, physmon_track_finding_ttbar::r, SvtxVertex::size_tracks(), square(), surf(), and Fun4AllBase::Verbosity().
Referenced by process_event().
void PHGenFitTrkFitter::reset_eval_variables ()
Definition at line 702 of file PHGenFitTrkFitter.cc.
View newest version in sPHENIX GitHub at line 702 of file PHGenFitTrkFitter.cc
References _cluster_eval_tree_gx, _cluster_eval_tree_gy, _cluster_eval_tree_gz, _cluster_eval_tree_x, _cluster_eval_tree_y, _cluster_eval_tree_z, _fit_primary_tracks, _tca_particlemap, _tca_primtrackmap, _tca_trackmap, _tca_trackmap_refit, _tca_vertexmap, _tca_vtxmap, _tcam_vertexMap_refit, and WILD_FLOAT.
Referenced by fill_eval_tree().
void PHGenFitTrkFitter::set_disabled_layers (const std::set< int > & layers)
set disabled layers
Definition at line 790 of file PHGenFitTrkFitter.cc.
View newest version in sPHENIX GitHub at line 790 of file PHGenFitTrkFitter.cc
References _disabled_layers.
void PHGenFitTrkFitter::set_do_eval (bool doEval) inline
Definition at line 127 of file PHGenFitTrkFitter.h.
View newest version in sPHENIX GitHub at line 127 of file PHGenFitTrkFitter.h
References _do_eval.
void PHGenFitTrkFitter::set_do_evt_display (bool doEvtDisplay) inline
Definition at line 137 of file PHGenFitTrkFitter.h.
View newest version in sPHENIX GitHub at line 137 of file PHGenFitTrkFitter.h
References _do_evt_display.
void PHGenFitTrkFitter::set_eval_filename (const char * file) inline
For evalution Change eval output filename
Definition at line 108 of file PHGenFitTrkFitter.h.
View newest version in sPHENIX GitHub at line 108 of file PHGenFitTrkFitter.h
References _eval_outname, and file.
void PHGenFitTrkFitter::set_fit_min_pT (double cutMinPT) inline
Definition at line 200 of file PHGenFitTrkFitter.h.
View newest version in sPHENIX GitHub at line 200 of file PHGenFitTrkFitter.h
References _fit_min_pT.
void PHGenFitTrkFitter::set_fit_primary_tracks (bool fitPrimaryTracks) inline
Definition at line 157 of file PHGenFitTrkFitter.h.
View newest version in sPHENIX GitHub at line 157 of file PHGenFitTrkFitter.h
References _fit_primary_tracks.
void PHGenFitTrkFitter::set_fit_silicon_mms (bool value)
fit only tracks with silicon+MM hits
Definition at line 802 of file PHGenFitTrkFitter.cc.
View newest version in sPHENIX GitHub at line 802 of file PHGenFitTrkFitter.cc
References disable_layer(), layer, m_fit_silicon_mms, and value.
void PHGenFitTrkFitter::set_output_mode (OutPutMode outputMode) inline
set output mode, default is OverwriteOriginalNode
Definition at line 170 of file PHGenFitTrkFitter.h.
View newest version in sPHENIX GitHub at line 170 of file PHGenFitTrkFitter.h
References _output_mode.
void PHGenFitTrkFitter::set_over_write_svtxtrackmap (bool overWriteSvtxtrackmap) inline
Definition at line 210 of file PHGenFitTrkFitter.h.
View newest version in sPHENIX GitHub at line 210 of file PHGenFitTrkFitter.h
References _over_write_svtxtrackmap.
void PHGenFitTrkFitter::set_primary_pid_guess (int primaryPidGuess) inline
Definition at line 190 of file PHGenFitTrkFitter.h.
View newest version in sPHENIX GitHub at line 190 of file PHGenFitTrkFitter.h
References _primary_pid_guess.
void PHGenFitTrkFitter::set_track_fitting_alg_name (const std::string & trackFittingAlgName) inline
Definition at line 180 of file PHGenFitTrkFitter.h.
View newest version in sPHENIX GitHub at line 180 of file PHGenFitTrkFitter.h
References _track_fitting_alg_name.
void PHGenFitTrkFitter::set_use_micromegas (bool value) inline
require micromegas in SiliconMM fits
Definition at line 256 of file PHGenFitTrkFitter.h.
View newest version in sPHENIX GitHub at line 256 of file PHGenFitTrkFitter.h
References m_use_micromegas, and value.
void PHGenFitTrkFitter::set_use_truth_vertex (bool useTruthVertex) inline
Definition at line 220 of file PHGenFitTrkFitter.h.
View newest version in sPHENIX GitHub at line 220 of file PHGenFitTrkFitter.h
References _use_truth_vertex.
void PHGenFitTrkFitter::set_vertex_min_ndf (double vertexMinPT) inline
Definition at line 230 of file PHGenFitTrkFitter.h.
View newest version in sPHENIX GitHub at line 230 of file PHGenFitTrkFitter.h
References _vertex_min_ndf.
void PHGenFitTrkFitter::set_vertexing_method (const std::string & vertexingMethod) inline
Definition at line 147 of file PHGenFitTrkFitter.h.
View newest version in sPHENIX GitHub at line 147 of file PHGenFitTrkFitter.h
References _vertexing_method.
Member Data Documentation
TTree* PHGenFitTrkFitter::_cluster_eval_tree = nullptr private
Definition at line 385 of file PHGenFitTrkFitter.h.
View newest version in sPHENIX GitHub at line 385 of file PHGenFitTrkFitter.h
Referenced by End(), and init_eval_tree().
float PHGenFitTrkFitter::_cluster_eval_tree_gx = 0 private
Definition at line 389 of file PHGenFitTrkFitter.h.
View newest version in sPHENIX GitHub at line 389 of file PHGenFitTrkFitter.h
Referenced by init_eval_tree(), PHGenFitTrkFitter(), and reset_eval_variables().
float PHGenFitTrkFitter::_cluster_eval_tree_gy = 0 private
Definition at line 390 of file PHGenFitTrkFitter.h.
View newest version in sPHENIX GitHub at line 390 of file PHGenFitTrkFitter.h
Referenced by init_eval_tree(), PHGenFitTrkFitter(), and reset_eval_variables().
float PHGenFitTrkFitter::_cluster_eval_tree_gz = 0 private
Definition at line 391 of file PHGenFitTrkFitter.h.
View newest version in sPHENIX GitHub at line 391 of file PHGenFitTrkFitter.h
Referenced by init_eval_tree(), PHGenFitTrkFitter(), and reset_eval_variables().
float PHGenFitTrkFitter::_cluster_eval_tree_x = 0 private
Definition at line 386 of file PHGenFitTrkFitter.h.
View newest version in sPHENIX GitHub at line 386 of file PHGenFitTrkFitter.h
Referenced by init_eval_tree(), PHGenFitTrkFitter(), and reset_eval_variables().
float PHGenFitTrkFitter::_cluster_eval_tree_y = 0 private
Definition at line 387 of file PHGenFitTrkFitter.h.
View newest version in sPHENIX GitHub at line 387 of file PHGenFitTrkFitter.h
Referenced by init_eval_tree(), PHGenFitTrkFitter(), and reset_eval_variables().
float PHGenFitTrkFitter::_cluster_eval_tree_z = 0 private
Definition at line 388 of file PHGenFitTrkFitter.h.
View newest version in sPHENIX GitHub at line 388 of file PHGenFitTrkFitter.h
Referenced by init_eval_tree(), PHGenFitTrkFitter(), and reset_eval_variables().
std::set<int> PHGenFitTrkFitter::_disabled_layers private
disabled layers
clusters belonging to disabled layers are not included in track fit
Definition at line 309 of file PHGenFitTrkFitter.h.
View newest version in sPHENIX GitHub at line 309 of file PHGenFitTrkFitter.h
Referenced by clear_disabled_layers(), disable_layer(), get_disabled_layers(), InitRun(), MakeSvtxTrack(), ReFitTrack(), and set_disabled_layers().
bool PHGenFitTrkFitter::_do_eval = false private
Evaluation switch eval out
Definition at line 371 of file PHGenFitTrkFitter.h.
View newest version in sPHENIX GitHub at line 371 of file PHGenFitTrkFitter.h
Referenced by End(), InitRun(), is_do_eval(), process_event(), and set_do_eval().
bool PHGenFitTrkFitter::_do_evt_display = false private
Definition at line 393 of file PHGenFitTrkFitter.h.
View newest version in sPHENIX GitHub at line 393 of file PHGenFitTrkFitter.h
Referenced by End(), InitRun(), is_do_evt_display(), process_event(), and set_do_evt_display().
std::string PHGenFitTrkFitter::_eval_outname = "PHGenFitTrkFitter_eval.root" private
eval output filename
Definition at line 374 of file PHGenFitTrkFitter.h.
View newest version in sPHENIX GitHub at line 374 of file PHGenFitTrkFitter.h
Referenced by End(), get_eval_filename(), InitRun(), and set_eval_filename().
TTree* PHGenFitTrkFitter::_eval_tree = nullptr private
Definition at line 376 of file PHGenFitTrkFitter.h.
View newest version in sPHENIX GitHub at line 376 of file PHGenFitTrkFitter.h
Referenced by End(), fill_eval_tree(), and init_eval_tree().
int PHGenFitTrkFitter::_event = 0 private
Event counter.
Definition at line 261 of file PHGenFitTrkFitter.h.
View newest version in sPHENIX GitHub at line 261 of file PHGenFitTrkFitter.h
Referenced by GetNodes(), and process_event().
double PHGenFitTrkFitter::_fit_min_pT = 0.1 private
Definition at line 322 of file PHGenFitTrkFitter.h.
View newest version in sPHENIX GitHub at line 322 of file PHGenFitTrkFitter.h
Referenced by get_fit_min_pT(), process_event(), and set_fit_min_pT().
bool PHGenFitTrkFitter::_fit_primary_tracks = false private
Definition at line 302 of file PHGenFitTrkFitter.h.
View newest version in sPHENIX GitHub at line 302 of file PHGenFitTrkFitter.h
Referenced by CreateNodes(), fill_eval_tree(), GetNodes(), init_eval_tree(), is_fit_primary_tracks(), process_event(), reset_eval_variables(), and set_fit_primary_tracks().
std::shared_ptr<PHGenFit::Fitter> PHGenFitTrkFitter::_fitter private
Definition at line 329 of file PHGenFitTrkFitter.h.
View newest version in sPHENIX GitHub at line 329 of file PHGenFitTrkFitter.h
Referenced by End(), InitRun(), process_event(), and ReFitTrack().
OutPutMode PHGenFitTrkFitter::_output_mode = PHGenFitTrkFitter::MakeNewNode private
Definition at line 298 of file PHGenFitTrkFitter.h.
View newest version in sPHENIX GitHub at line 298 of file PHGenFitTrkFitter.h
Referenced by CreateNodes(), get_output_mode(), GetNodes(), process_event(), and set_output_mode().
bool PHGenFitTrkFitter::_over_write_svtxtrackmap = true private
Definition at line 300 of file PHGenFitTrkFitter.h.
View newest version in sPHENIX GitHub at line 300 of file PHGenFitTrkFitter.h
Referenced by CreateNodes(), GetNodes(), is_over_write_svtxtrackmap(), process_event(), and set_over_write_svtxtrackmap().
int PHGenFitTrkFitter::_primary_pid_guess = 211 private
Definition at line 321 of file PHGenFitTrkFitter.h.
View newest version in sPHENIX GitHub at line 321 of file PHGenFitTrkFitter.h
Referenced by get_primary_pid_guess(), ReFitTrack(), and set_primary_pid_guess().
std::map<unsigned int, unsigned int> PHGenFitTrkFitter::_rave_vertex_gf_track_map private
Definition at line 395 of file PHGenFitTrkFitter.h.
View newest version in sPHENIX GitHub at line 395 of file PHGenFitTrkFitter.h
Referenced by FillSvtxVertexMap(), and process_event().
TClonesArray* PHGenFitTrkFitter::_tca_particlemap = nullptr private
Definition at line 377 of file PHGenFitTrkFitter.h.
View newest version in sPHENIX GitHub at line 377 of file PHGenFitTrkFitter.h
Referenced by init_eval_tree(), and reset_eval_variables().
TClonesArray* PHGenFitTrkFitter::_tca_primtrackmap = nullptr private
Definition at line 382 of file PHGenFitTrkFitter.h.
View newest version in sPHENIX GitHub at line 382 of file PHGenFitTrkFitter.h
Referenced by init_eval_tree(), and reset_eval_variables().
TClonesArray* PHGenFitTrkFitter::_tca_trackmap = nullptr private
Definition at line 379 of file PHGenFitTrkFitter.h.
View newest version in sPHENIX GitHub at line 379 of file PHGenFitTrkFitter.h
Referenced by init_eval_tree(), and reset_eval_variables().
TClonesArray* PHGenFitTrkFitter::_tca_trackmap_refit = nullptr private
Definition at line 381 of file PHGenFitTrkFitter.h.
View newest version in sPHENIX GitHub at line 381 of file PHGenFitTrkFitter.h
Referenced by init_eval_tree(), and reset_eval_variables().
TClonesArray* PHGenFitTrkFitter::_tca_vertexmap = nullptr private
Definition at line 380 of file PHGenFitTrkFitter.h.
View newest version in sPHENIX GitHub at line 380 of file PHGenFitTrkFitter.h
Referenced by init_eval_tree(), and reset_eval_variables().
TClonesArray* PHGenFitTrkFitter::_tca_vtxmap = nullptr private
Definition at line 378 of file PHGenFitTrkFitter.h.
View newest version in sPHENIX GitHub at line 378 of file PHGenFitTrkFitter.h
Referenced by init_eval_tree(), and reset_eval_variables().
TClonesArray* PHGenFitTrkFitter::_tcam_vertexMap_refit = nullptr private
Definition at line 383 of file PHGenFitTrkFitter.h.
View newest version in sPHENIX GitHub at line 383 of file PHGenFitTrkFitter.h
Referenced by init_eval_tree(), and reset_eval_variables().
std::string PHGenFitTrkFitter::_track_fitting_alg_name = "DafRef" private
KalmanFitterRefTrack, KalmanFitter, DafSimple, DafRef.
Definition at line 319 of file PHGenFitTrkFitter.h.
View newest version in sPHENIX GitHub at line 319 of file PHGenFitTrkFitter.h
Referenced by get_track_fitting_alg_name(), InitRun(), and set_track_fitting_alg_name().
PHG4TruthInfoContainer* PHGenFitTrkFitter::_truth_container = nullptr private
Input Node pointers.
Definition at line 339 of file PHGenFitTrkFitter.h.
View newest version in sPHENIX GitHub at line 339 of file PHGenFitTrkFitter.h
Referenced by fill_eval_tree(), GetNodes(), and MakeSvtxTrack().
bool PHGenFitTrkFitter::_use_truth_vertex = false private
Definition at line 305 of file PHGenFitTrkFitter.h.
View newest version in sPHENIX GitHub at line 305 of file PHGenFitTrkFitter.h
Referenced by is_use_truth_vertex(), MakeSvtxTrack(), and set_use_truth_vertex().
std::shared_ptr<genfit::GFRaveVertexFactory> PHGenFitTrkFitter::_vertex_finder private
Definition at line 330 of file PHGenFitTrkFitter.h.
View newest version in sPHENIX GitHub at line 330 of file PHGenFitTrkFitter.h
Referenced by InitRun(), and process_event().
double PHGenFitTrkFitter::_vertex_min_ndf = 20 private
Definition at line 323 of file PHGenFitTrkFitter.h.
View newest version in sPHENIX GitHub at line 323 of file PHGenFitTrkFitter.h
Referenced by get_vertex_min_ndf(), process_event(), and set_vertex_min_ndf().
std::string PHGenFitTrkFitter::_vertexing_method = "avr-smoothing:1-minweight:0.5-primcut:9-seccut:9" private
https://rave.hepforge.org/trac/wiki/RaveMethods
Definition at line 333 of file PHGenFitTrkFitter.h.
View newest version in sPHENIX GitHub at line 333 of file PHGenFitTrkFitter.h
Referenced by get_vertexing_method(), InitRun(), and set_vertexing_method().
SvtxVertexMap* PHGenFitTrkFitter::_vertexmap = nullptr private
Definition at line 347 of file PHGenFitTrkFitter.h.
View newest version in sPHENIX GitHub at line 347 of file PHGenFitTrkFitter.h
Referenced by fill_eval_tree(), and GetNodes().
ClusterErrorPara PHGenFitTrkFitter::m_cluster_error_parametrization private
cluster error parametrisation
Definition at line 367 of file PHGenFitTrkFitter.h.
View newest version in sPHENIX GitHub at line 367 of file PHGenFitTrkFitter.h
TpcClusterZCrossingCorrection PHGenFitTrkFitter::m_clusterCrossingCorrection private
Definition at line 356 of file PHGenFitTrkFitter.h.
View newest version in sPHENIX GitHub at line 356 of file PHGenFitTrkFitter.h
Referenced by getGlobalPosition().
TrkrClusterContainer* PHGenFitTrkFitter::m_clustermap = nullptr private
Definition at line 340 of file PHGenFitTrkFitter.h.
View newest version in sPHENIX GitHub at line 340 of file PHGenFitTrkFitter.h
Referenced by GetNodes(), MakeSvtxTrack(), process_event(), and ReFitTrack().
TpcDistortionCorrectionContainer* PHGenFitTrkFitter::m_dcc_average = nullptr private
Definition at line 360 of file PHGenFitTrkFitter.h.
View newest version in sPHENIX GitHub at line 360 of file PHGenFitTrkFitter.h
Referenced by getGlobalPosition(), and GetNodes().
TpcDistortionCorrectionContainer* PHGenFitTrkFitter::m_dcc_fluctuation = nullptr private
Definition at line 361 of file PHGenFitTrkFitter.h.
View newest version in sPHENIX GitHub at line 361 of file PHGenFitTrkFitter.h
Referenced by getGlobalPosition(), and GetNodes().
TpcDistortionCorrectionContainer* PHGenFitTrkFitter::m_dcc_static = nullptr private
Definition at line 359 of file PHGenFitTrkFitter.h.
View newest version in sPHENIX GitHub at line 359 of file PHGenFitTrkFitter.h
Referenced by getGlobalPosition(), and GetNodes().
TpcDistortionCorrection PHGenFitTrkFitter::m_distortionCorrection private
tpc distortion correction utility class
Definition at line 364 of file PHGenFitTrkFitter.h.
View newest version in sPHENIX GitHub at line 364 of file PHGenFitTrkFitter.h
Referenced by getGlobalPosition().
bool PHGenFitTrkFitter::m_fit_silicon_mms = false private
Boolean to use normal tracking geometry navigator or the Acts::DirectedNavigator with a list of sorted silicon+MM surfaces
Definition at line 313 of file PHGenFitTrkFitter.h.
View newest version in sPHENIX GitHub at line 313 of file PHGenFitTrkFitter.h
Referenced by InitRun(), ReFitTrack(), and set_fit_silicon_mms().
SvtxTrackMap* PHGenFitTrkFitter::m_primary_trackMap = nullptr private
Definition at line 352 of file PHGenFitTrkFitter.h.
View newest version in sPHENIX GitHub at line 352 of file PHGenFitTrkFitter.h
Referenced by CreateNodes(), fill_eval_tree(), GetNodes(), and process_event().
TrackSeedContainer* PHGenFitTrkFitter::m_seedMap = nullptr private
Definition at line 343 of file PHGenFitTrkFitter.h.
View newest version in sPHENIX GitHub at line 343 of file PHGenFitTrkFitter.h
Referenced by GetNodes(), and process_event().
TrackSeedContainer* PHGenFitTrkFitter::m_siliconSeeds = nullptr private
Definition at line 345 of file PHGenFitTrkFitter.h.
View newest version in sPHENIX GitHub at line 345 of file PHGenFitTrkFitter.h
Referenced by GetNodes(), and process_event().
ActsGeometry* PHGenFitTrkFitter::m_tgeometry = nullptr private
acts geometry
Definition at line 336 of file PHGenFitTrkFitter.h.
View newest version in sPHENIX GitHub at line 336 of file PHGenFitTrkFitter.h
Referenced by getGlobalPosition(), GetNodes(), process_event(), and ReFitTrack().
TrackSeedContainer* PHGenFitTrkFitter::m_tpcSeeds = nullptr private
Definition at line 344 of file PHGenFitTrkFitter.h.
View newest version in sPHENIX GitHub at line 344 of file PHGenFitTrkFitter.h
Referenced by GetNodes(), and process_event().
SvtxTrackMap* PHGenFitTrkFitter::m_trackMap = nullptr private
Output Node pointers.
Definition at line 350 of file PHGenFitTrkFitter.h.
View newest version in sPHENIX GitHub at line 350 of file PHGenFitTrkFitter.h
Referenced by CreateNodes(), fill_eval_tree(), GetNodes(), and process_event().
SvtxTrackMap* PHGenFitTrkFitter::m_trackMap_refit = nullptr private
Definition at line 351 of file PHGenFitTrkFitter.h.
View newest version in sPHENIX GitHub at line 351 of file PHGenFitTrkFitter.h
Referenced by CreateNodes(), fill_eval_tree(), GetNodes(), and process_event().
bool PHGenFitTrkFitter::m_use_micromegas = true private
requires micromegas present when fitting silicon-MM surfaces
Definition at line 316 of file PHGenFitTrkFitter.h.
View newest version in sPHENIX GitHub at line 316 of file PHGenFitTrkFitter.h
Referenced by InitRun(), ReFitTrack(), and set_use_micromegas().
SvtxVertexMap* PHGenFitTrkFitter::m_vertexMap_refit = nullptr private
Definition at line 353 of file PHGenFitTrkFitter.h.
View newest version in sPHENIX GitHub at line 353 of file PHGenFitTrkFitter.h
Referenced by CreateNodes(), fill_eval_tree(), FillSvtxVertexMap(), GetNodes(), and process_event().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/trackreco/PHGenFitTrkFitter.h
coresoftware/blob/master/offline/packages/trackreco/PHGenFitTrkFitter.cc