Analysis Software: cl::Device Class Reference
cl::Device Class Reference
Device interface for cl_device_id.
#include <JETSCAPE/blob/main/external_packages/clvisc_wrapper/include/cl.hpp>
Public Member Functions
Device (cl_device_id device)
Device ()
Device (const Device &device)
Device & operator= (const Device &rhs)
template<typename T >
cl_int getInfo (cl_device_info name, T *param) const
template<cl_int name>
detail::param_traits
< detail::cl_device_info, name >
::param_type getInfo (cl_int *err=NULL) const
Public Member Functions inherited from cl::detail::Wrapper< cl_device_id >
Wrapper ()
Wrapper (const Wrapper< cl_type > &rhs)
~Wrapper ()
Wrapper< cl_type > & operator= (const Wrapper< cl_type > &rhs)
cl_type operator() () const
cl_type & operator() ()
Additional Inherited Members
Public Types inherited from cl::detail::Wrapper< cl_device_id >
typedef cl_device_id cl_type
Protected Member Functions inherited from cl::detail::Wrapper< cl_device_id >
cl_int retain () const
cl_int release () const
Protected Attributes inherited from cl::detail::Wrapper< cl_device_id >
cl_type object_
Detailed Description
Device interface for cl_device_id.
Definition at line 1183 of file cl.hpp.
View newest version in sPHENIX GitHub at line 1183 of file cl.hpp
Constructor & Destructor Documentation
cl::Device::Device (cl_device_id device) inline
Definition at line 1186 of file cl.hpp.
View newest version in sPHENIX GitHub at line 1186 of file cl.hpp
References cl::detail::Wrapper< cl_device_id >::object_.
cl::Device::Device () inline
Definition at line 1188 of file cl.hpp.
View newest version in sPHENIX GitHub at line 1188 of file cl.hpp
cl::Device::Device (const Device & device) inline
Definition at line 1190 of file cl.hpp.
View newest version in sPHENIX GitHub at line 1190 of file cl.hpp
Member Function Documentation
template<typename T > cl_int cl::Device::getInfo (cl_device_info name, T * param) const inline
Definition at line 1201 of file cl.hpp.
View newest version in sPHENIX GitHub at line 1201 of file cl.hpp
References cl::detail::errHandler(), cl::detail::getInfo(), and cl::detail::Wrapper< cl_device_id >::object_.
Referenced by getInfo().
template<cl_int name> detail::param_traits<detail::cl_device_info, name>::param_type cl::Device::getInfo (cl_int * err = NULL) const inline
Definition at line 1210 of file cl.hpp.
View newest version in sPHENIX GitHub at line 1210 of file cl.hpp
References check_license::err(), getInfo(), and perf_headwind::name.
Device& cl::Device::operator= (const Device & rhs) inline
Definition at line 1192 of file cl.hpp.
View newest version in sPHENIX GitHub at line 1192 of file cl.hpp
References cl::detail::Wrapper< T >::operator=().
The documentation for this class was generated from the following file:
JETSCAPE/blob/main/external_packages/clvisc_wrapper/include/cl.hpp