Analysis Software: PHG4Cellv1 Class Reference
PHG4Cellv1 Class Reference
#include <coresoftware/blob/master/simulation/g4simulation/g4detectors/PHG4Cellv1.h>
Classes
union u_property
convert between 32bit inputs and storage type prop_storage_t
Public Member Functions
PHG4Cellv1 ()
PHG4Cellv1 (const PHG4CellDefs::keytype g4cellid)
~PHG4Cellv1 () override
void identify (std::ostream &os=std::cout) const override
void Reset () override
Clear Event.
void set_cellid (const PHG4CellDefs::keytype i) override
PHG4CellDefs::keytype get_cellid () const override
bool has_binning (const PHG4CellDefs::CellBinning binning) const override
short int get_detid () const override
void add_edep (const PHG4HitDefs::keytype g4hitid, const float edep) override
void add_shower_edep (const int g4showerid, const float edep) override
EdepConstRange get_g4hits () override
ShowerEdepConstRange get_g4showers () override
void add_edep (const float f) override
double get_edep () const override
void add_eion (const float f) override
double get_eion () const override
void add_light_yield (const float f) override
float get_light_yield () const override
void add_raw_light_yield (const float f) override
float get_raw_light_yield () const override
void set_chip_index (const int i) override
int get_chip_index () const override
void set_half_stave_index (const int i) override
int get_half_stave_index () const override
void set_ladder_phi_index (const int i) override
int get_ladder_phi_index () const override
void set_ladder_z_index (const int i) override
int get_ladder_z_index () const override
void set_module_index (const int i) override
int get_module_index () const override
void set_phibin (const int i) override
int get_phibin () const override
void set_pixel_index (const int i) override
int get_pixel_index () const override
void set_stave_index (const int i) override
int get_stave_index () const override
void set_zbin (const int i) override
int get_zbin () const override
void print () const override
bool has_property (const PROPERTY prop_id) const override
float get_property_float (const PROPERTY prop_id) const override
int get_property_int (const PROPERTY prop_id) const override
unsigned int get_property_uint (const PROPERTY prop_id) const override
void add_property (const PROPERTY prop_id, const float value)
void add_property (const PROPERTY prop_id, const int value)
void add_property (const PROPERTY prop_id, const unsigned int value)
void set_property (const PROPERTY prop_id, const float value) override
void set_property (const PROPERTY prop_id, const int value) override
void set_property (const PROPERTY prop_id, const unsigned int value) override
Public Member Functions inherited from PHG4Cell
~PHG4Cell () override
void CopyFrom (const PHObject *phobj) override
virtual void add_edep (const PHG4HitDefs::keytype, const float, const float)
virtual void add_edep (const PHG4HitDefs::keytype, const int, const float)
short int get_layer () const
Public Member Functions inherited from PHObject
PHObject ()
ctor
~PHObject () override
dtor
virtual PHObject * CloneMe () const
Virtual copy constructor.
virtual PHObject * clone () const final
PHObject * Clone (const char *newname="") const final
void Copy (TObject &object) const final
virtual int isValid () const
isValid returns non zero if object contains vailid data
virtual int Integrate () const
virtual int Integrate (PHObject *)
Protected Types
typedef uint8_t prop_id_t
storage types for additional property
typedef uint32_t prop_storage_t
typedef std::map< prop_id_t,
prop_storage_t > prop_map_t
Protected Member Functions
unsigned int get_property_nocheck (const PROPERTY prop_id) const override
void set_property_nocheck (const PROPERTY prop_id, const unsigned int ui) override
Protected Member Functions inherited from PHG4Cell
PHG4Cell ()
Protected Attributes
PHG4CellDefs::keytype cellid = ~0x0
EdepMap hitedeps
ShowerEdepMap showeredeps
prop_map_t prop_map
container for additional property
Additional Inherited Members
Public Types inherited from PHG4Cell
enum PROPERTY {
prop_stave_index = 1, prop_half_stave_index = 2, prop_module_index = 3, prop_chip_index = 4,
prop_pixel_index = 5, prop_phibin = 6, prop_zbin = 7, prop_ladder_z_index = 8,
prop_ladder_phi_index = 9, prop_edep = 21, prop_eion = 22, prop_light_yield = 23,
prop_raw_light_yield = 24, prop_MAX_NUMBER = UCHAR_MAX
}
enum PROPERTY_TYPE { type_int = 1, type_uint = 2, type_float = 3, type_unknown = -1 }
typedef std::map
< PHG4HitDefs::keytype, float > EdepMap
typedef EdepMap::iterator EdepIterator
typedef EdepMap::const_iterator EdepConstIterator
typedef std::pair
< EdepIterator, EdepIterator > EdepRange
typedef std::pair
< EdepConstIterator,
EdepConstIterator > EdepConstRange
typedef std::map< int, float > ShowerEdepMap
typedef ShowerEdepMap::iterator ShowerEdepIterator
typedef
ShowerEdepMap::const_iterator ShowerEdepConstIterator
typedef std::pair
< ShowerEdepIterator,
ShowerEdepIterator > ShowerEdepRange
typedef std::pair
< ShowerEdepConstIterator,
ShowerEdepConstIterator > ShowerEdepConstRange
Static Public Member Functions inherited from PHG4Cell
static std::pair< const
std::string, PROPERTY_TYPE > get_property_info (PROPERTY prop_id)
static bool check_property (const PROPERTY prop_id, const PROPERTY_TYPE prop_type)
static std::string get_property_type (const PROPERTY_TYPE prop_type)
Detailed Description
Definition at line 17 of file PHG4Cellv1.h.
View newest version in sPHENIX GitHub at line 17 of file PHG4Cellv1.h
Member Typedef Documentation
typedef uint8_t PHG4Cellv1::prop_id_t protected
storage types for additional property
Definition at line 109 of file PHG4Cellv1.h.
View newest version in sPHENIX GitHub at line 109 of file PHG4Cellv1.h
typedef std::map<prop_id_t, prop_storage_t> PHG4Cellv1::prop_map_t protected
Definition at line 111 of file PHG4Cellv1.h.
View newest version in sPHENIX GitHub at line 111 of file PHG4Cellv1.h
typedef uint32_t PHG4Cellv1::prop_storage_t protected
Definition at line 110 of file PHG4Cellv1.h.
View newest version in sPHENIX GitHub at line 110 of file PHG4Cellv1.h
Constructor & Destructor Documentation
PHG4Cellv1::PHG4Cellv1 () inline
Definition at line 20 of file PHG4Cellv1.h.
View newest version in sPHENIX GitHub at line 20 of file PHG4Cellv1.h
PHG4Cellv1::PHG4Cellv1 (const PHG4CellDefs::keytype g4cellid) explicit
Definition at line 13 of file PHG4Cellv1.cc.
View newest version in sPHENIX GitHub at line 13 of file PHG4Cellv1.cc
PHG4Cellv1::~PHG4Cellv1 () override
Definition at line 18 of file PHG4Cellv1.cc.
View newest version in sPHENIX GitHub at line 18 of file PHG4Cellv1.cc
References hitedeps, prop_map, and showeredeps.
Member Function Documentation
void PHG4Cellv1::add_edep (const PHG4HitDefs::keytype g4hitid, const float edep) override virtual
Reimplemented from PHG4Cell.
Definition at line 26 of file PHG4Cellv1.cc.
View newest version in sPHENIX GitHub at line 26 of file PHG4Cellv1.cc
References hitedeps.
void PHG4Cellv1::add_edep (const float f) inline override virtual
Reimplemented from PHG4Cell.
Definition at line 48 of file PHG4Cellv1.h.
View newest version in sPHENIX GitHub at line 48 of file PHG4Cellv1.h
References add_property(), and PHG4Cell::prop_edep.
void PHG4Cellv1::add_eion (const float f) inline override virtual
Reimplemented from PHG4Cell.
Definition at line 51 of file PHG4Cellv1.h.
View newest version in sPHENIX GitHub at line 51 of file PHG4Cellv1.h
References add_property(), and PHG4Cell::prop_eion.
void PHG4Cellv1::add_light_yield (const float f) inline override virtual
Reimplemented from PHG4Cell.
Definition at line 54 of file PHG4Cellv1.h.
View newest version in sPHENIX GitHub at line 54 of file PHG4Cellv1.h
References add_property(), and PHG4Cell::prop_light_yield.
void PHG4Cellv1::add_property (const PROPERTY prop_id, const float value)
Definition at line 107 of file PHG4Cellv1.cc.
View newest version in sPHENIX GitHub at line 107 of file PHG4Cellv1.cc
References PHG4Cell::check_property(), get_property_float(), PHG4Cell::get_property_info(), PHG4Cell::get_property_type(), PHG4Cellv1::u_property::get_storage(), PHWHERE, prop_map, PHG4Cell::type_float, and value.
Referenced by add_edep(), add_eion(), add_light_yield(), and add_raw_light_yield().
void PHG4Cellv1::add_property (const PROPERTY prop_id, const int value)
Definition at line 125 of file PHG4Cellv1.cc.
View newest version in sPHENIX GitHub at line 125 of file PHG4Cellv1.cc
References PHG4Cell::check_property(), PHG4Cell::get_property_info(), get_property_int(), PHG4Cell::get_property_type(), PHG4Cellv1::u_property::get_storage(), PHWHERE, prop_map, PHG4Cell::type_int, and value.
void PHG4Cellv1::add_property (const PROPERTY prop_id, const unsigned int value)
Definition at line 143 of file PHG4Cellv1.cc.
View newest version in sPHENIX GitHub at line 143 of file PHG4Cellv1.cc
References PHG4Cell::check_property(), PHG4Cell::get_property_info(), PHG4Cell::get_property_type(), get_property_uint(), PHG4Cellv1::u_property::get_storage(), PHWHERE, prop_map, PHG4Cell::type_uint, and value.
void PHG4Cellv1::add_raw_light_yield (const float f) inline override virtual
Reimplemented from PHG4Cell.
Definition at line 57 of file PHG4Cellv1.h.
View newest version in sPHENIX GitHub at line 57 of file PHG4Cellv1.h
References add_property(), and PHG4Cell::prop_raw_light_yield.
void PHG4Cellv1::add_shower_edep (const int g4showerid, const float edep) override virtual
Reimplemented from PHG4Cell.
Definition at line 32 of file PHG4Cellv1.cc.
View newest version in sPHENIX GitHub at line 32 of file PHG4Cellv1.cc
References showeredeps.
PHG4CellDefs::keytype PHG4Cellv1::get_cellid () const inline override virtual
Reimplemented from PHG4Cell.
Definition at line 29 of file PHG4Cellv1.h.
View newest version in sPHENIX GitHub at line 29 of file PHG4Cellv1.h
References cellid.
int PHG4Cellv1::get_chip_index () const inline override virtual
Reimplemented from PHG4Cell.
Definition at line 61 of file PHG4Cellv1.h.
View newest version in sPHENIX GitHub at line 61 of file PHG4Cellv1.h
References get_property_int(), and PHG4Cell::prop_chip_index.
short int PHG4Cellv1::get_detid () const override virtual
Reimplemented from PHG4Cell.
Definition at line 44 of file PHG4Cellv1.cc.
View newest version in sPHENIX GitHub at line 44 of file PHG4Cellv1.cc
References cellid, and PHG4CellDefs::get_detid().
double PHG4Cellv1::get_edep () const inline override virtual
Reimplemented from PHG4Cell.
Definition at line 49 of file PHG4Cellv1.h.
View newest version in sPHENIX GitHub at line 49 of file PHG4Cellv1.h
References get_property_float(), and PHG4Cell::prop_edep.
double PHG4Cellv1::get_eion () const inline override virtual
Reimplemented from PHG4Cell.
Definition at line 52 of file PHG4Cellv1.h.
View newest version in sPHENIX GitHub at line 52 of file PHG4Cellv1.h
References get_property_float(), and PHG4Cell::prop_eion.
EdepConstRange PHG4Cellv1::get_g4hits () inline override virtual
Reimplemented from PHG4Cell.
Definition at line 38 of file PHG4Cellv1.h.
View newest version in sPHENIX GitHub at line 38 of file PHG4Cellv1.h
References hitedeps.
ShowerEdepConstRange PHG4Cellv1::get_g4showers () inline override virtual
Reimplemented from PHG4Cell.
Definition at line 43 of file PHG4Cellv1.h.
View newest version in sPHENIX GitHub at line 43 of file PHG4Cellv1.h
References showeredeps.
int PHG4Cellv1::get_half_stave_index () const inline override virtual
Reimplemented from PHG4Cell.
Definition at line 64 of file PHG4Cellv1.h.
View newest version in sPHENIX GitHub at line 64 of file PHG4Cellv1.h
References get_property_int(), and PHG4Cell::prop_half_stave_index.
int PHG4Cellv1::get_ladder_phi_index () const inline override virtual
Reimplemented from PHG4Cell.
Definition at line 67 of file PHG4Cellv1.h.
View newest version in sPHENIX GitHub at line 67 of file PHG4Cellv1.h
References get_property_int(), and PHG4Cell::prop_ladder_phi_index.
int PHG4Cellv1::get_ladder_z_index () const inline override virtual
Reimplemented from PHG4Cell.
Definition at line 70 of file PHG4Cellv1.h.
View newest version in sPHENIX GitHub at line 70 of file PHG4Cellv1.h
References get_property_int(), and PHG4Cell::prop_ladder_z_index.
float PHG4Cellv1::get_light_yield () const inline override virtual
Reimplemented from PHG4Cell.
Definition at line 55 of file PHG4Cellv1.h.
View newest version in sPHENIX GitHub at line 55 of file PHG4Cellv1.h
References get_property_float(), and PHG4Cell::prop_light_yield.
int PHG4Cellv1::get_module_index () const inline override virtual
Reimplemented from PHG4Cell.
Definition at line 73 of file PHG4Cellv1.h.
View newest version in sPHENIX GitHub at line 73 of file PHG4Cellv1.h
References get_property_int(), and PHG4Cell::prop_module_index.
int PHG4Cellv1::get_phibin () const inline override virtual
Reimplemented from PHG4Cell.
Definition at line 76 of file PHG4Cellv1.h.
View newest version in sPHENIX GitHub at line 76 of file PHG4Cellv1.h
References get_property_int(), and PHG4Cell::prop_phibin.
int PHG4Cellv1::get_pixel_index () const inline override virtual
Reimplemented from PHG4Cell.
Definition at line 79 of file PHG4Cellv1.h.
View newest version in sPHENIX GitHub at line 79 of file PHG4Cellv1.h
References get_property_int(), and PHG4Cell::prop_pixel_index.
float PHG4Cellv1::get_property_float (const PROPERTY prop_id) const override virtual
Reimplemented from PHG4Cell.
Definition at line 55 of file PHG4Cellv1.cc.
View newest version in sPHENIX GitHub at line 55 of file PHG4Cellv1.cc
References PHG4Cell::check_property(), PHG4Cellv1::u_property::fdata, PHG4Cell::get_property_info(), PHG4Cell::get_property_type(), i, PHWHERE, prop_map, and PHG4Cell::type_float.
Referenced by add_property(), get_edep(), get_eion(), get_light_yield(), get_raw_light_yield(), and identify().
int PHG4Cellv1::get_property_int (const PROPERTY prop_id) const override virtual
Reimplemented from PHG4Cell.
Definition at line 72 of file PHG4Cellv1.cc.
View newest version in sPHENIX GitHub at line 72 of file PHG4Cellv1.cc
References PHG4Cell::check_property(), PHG4Cell::get_property_info(), PHG4Cell::get_property_type(), i, PHG4Cellv1::u_property::idata, PHWHERE, prop_map, and PHG4Cell::type_int.
Referenced by add_property(), get_chip_index(), get_half_stave_index(), get_ladder_phi_index(), get_ladder_z_index(), get_module_index(), get_phibin(), get_pixel_index(), get_stave_index(), get_zbin(), and identify().
unsigned int PHG4Cellv1::get_property_nocheck (const PROPERTY prop_id) const override protected virtual
Reimplemented from PHG4Cell.
Definition at line 201 of file PHG4Cellv1.cc.
View newest version in sPHENIX GitHub at line 201 of file PHG4Cellv1.cc
References prop_map.
unsigned int PHG4Cellv1::get_property_uint (const PROPERTY prop_id) const override virtual
Reimplemented from PHG4Cell.
Definition at line 90 of file PHG4Cellv1.cc.
View newest version in sPHENIX GitHub at line 90 of file PHG4Cellv1.cc
References PHG4Cell::check_property(), PHG4Cell::get_property_info(), PHG4Cell::get_property_type(), i, PHWHERE, prop_map, PHG4Cell::type_uint, and PHG4Cellv1::u_property::uidata.
Referenced by add_property(), and identify().
float PHG4Cellv1::get_raw_light_yield () const inline override virtual
Reimplemented from PHG4Cell.
Definition at line 58 of file PHG4Cellv1.h.
View newest version in sPHENIX GitHub at line 58 of file PHG4Cellv1.h
References get_property_float(), and PHG4Cell::prop_raw_light_yield.
int PHG4Cellv1::get_stave_index () const inline override virtual
Reimplemented from PHG4Cell.
Definition at line 82 of file PHG4Cellv1.h.
View newest version in sPHENIX GitHub at line 82 of file PHG4Cellv1.h
References get_property_int(), and PHG4Cell::prop_stave_index.
int PHG4Cellv1::get_zbin () const inline override virtual
Reimplemented from PHG4Cell.
Definition at line 85 of file PHG4Cellv1.h.
View newest version in sPHENIX GitHub at line 85 of file PHG4Cellv1.h
References get_property_int(), and PHG4Cell::prop_zbin.
bool PHG4Cellv1::has_binning (const PHG4CellDefs::CellBinning binning) const override virtual
Reimplemented from PHG4Cell.
Definition at line 38 of file PHG4Cellv1.cc.
View newest version in sPHENIX GitHub at line 38 of file PHG4Cellv1.cc
References cellid, and PHG4CellDefs::has_binning().
bool PHG4Cellv1::has_property (const PROPERTY prop_id) const override virtual
Reimplemented from PHG4Cell.
Definition at line 49 of file PHG4Cellv1.cc.
View newest version in sPHENIX GitHub at line 49 of file PHG4Cellv1.cc
References i, and prop_map.
void PHG4Cellv1::identify (std::ostream & os = std::cout) const override virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from PHG4Cell.
Definition at line 224 of file PHG4Cellv1.cc.
View newest version in sPHENIX GitHub at line 224 of file PHG4Cellv1.cc
References cellid, get_property_float(), PHG4Cell::get_property_info(), get_property_int(), get_property_uint(), hitedeps, i, prop_map, showeredeps, PHG4Cell::type_float, PHG4Cell::type_int, and PHG4Cell::type_uint.
Referenced by print().
void PHG4Cellv1::print () const override virtual
Reimplemented from PHG4Cell.
Definition at line 211 of file PHG4Cellv1.cc.
View newest version in sPHENIX GitHub at line 211 of file PHG4Cellv1.cc
References identify().
void PHG4Cellv1::Reset () override virtual
Clear Event.
Reimplemented from PHG4Cell.
Definition at line 216 of file PHG4Cellv1.cc.
View newest version in sPHENIX GitHub at line 216 of file PHG4Cellv1.cc
References hitedeps, prop_map, and showeredeps.
void PHG4Cellv1::set_cellid (const PHG4CellDefs::keytype i) inline override virtual
Reimplemented from PHG4Cell.
Definition at line 27 of file PHG4Cellv1.h.
View newest version in sPHENIX GitHub at line 27 of file PHG4Cellv1.h
References cellid, and i.
void PHG4Cellv1::set_chip_index (const int i) inline override virtual
Reimplemented from PHG4Cell.
Definition at line 60 of file PHG4Cellv1.h.
View newest version in sPHENIX GitHub at line 60 of file PHG4Cellv1.h
References PHG4Cell::prop_chip_index, and set_property().
void PHG4Cellv1::set_half_stave_index (const int i) inline override virtual
Reimplemented from PHG4Cell.
Definition at line 63 of file PHG4Cellv1.h.
View newest version in sPHENIX GitHub at line 63 of file PHG4Cellv1.h
References PHG4Cell::prop_half_stave_index, and set_property().
void PHG4Cellv1::set_ladder_phi_index (const int i) inline override virtual
Reimplemented from PHG4Cell.
Definition at line 66 of file PHG4Cellv1.h.
View newest version in sPHENIX GitHub at line 66 of file PHG4Cellv1.h
References PHG4Cell::prop_ladder_phi_index, and set_property().
void PHG4Cellv1::set_ladder_z_index (const int i) inline override virtual
Reimplemented from PHG4Cell.
Definition at line 69 of file PHG4Cellv1.h.
View newest version in sPHENIX GitHub at line 69 of file PHG4Cellv1.h
References PHG4Cell::prop_ladder_z_index, and set_property().
void PHG4Cellv1::set_module_index (const int i) inline override virtual
Reimplemented from PHG4Cell.
Definition at line 72 of file PHG4Cellv1.h.
View newest version in sPHENIX GitHub at line 72 of file PHG4Cellv1.h
References PHG4Cell::prop_module_index, and set_property().
void PHG4Cellv1::set_phibin (const int i) inline override virtual
Reimplemented from PHG4Cell.
Definition at line 75 of file PHG4Cellv1.h.
View newest version in sPHENIX GitHub at line 75 of file PHG4Cellv1.h
References PHG4Cell::prop_phibin, and set_property().
void PHG4Cellv1::set_pixel_index (const int i) inline override virtual
Reimplemented from PHG4Cell.
Definition at line 78 of file PHG4Cellv1.h.
View newest version in sPHENIX GitHub at line 78 of file PHG4Cellv1.h
References PHG4Cell::prop_pixel_index, and set_property().
void PHG4Cellv1::set_property (const PROPERTY prop_id, const float value) override virtual
Reimplemented from PHG4Cell.
Definition at line 161 of file PHG4Cellv1.cc.
View newest version in sPHENIX GitHub at line 161 of file PHG4Cellv1.cc
References PHG4Cell::check_property(), PHG4Cell::get_property_info(), PHG4Cell::get_property_type(), PHG4Cellv1::u_property::get_storage(), PHWHERE, prop_map, and PHG4Cell::type_float.
Referenced by set_chip_index(), set_half_stave_index(), set_ladder_phi_index(), set_ladder_z_index(), set_module_index(), set_phibin(), set_pixel_index(), set_stave_index(), and set_zbin().
void PHG4Cellv1::set_property (const PROPERTY prop_id, const int value) override virtual
Reimplemented from PHG4Cell.
Definition at line 174 of file PHG4Cellv1.cc.
View newest version in sPHENIX GitHub at line 174 of file PHG4Cellv1.cc
References PHG4Cell::check_property(), PHG4Cell::get_property_info(), PHG4Cell::get_property_type(), PHG4Cellv1::u_property::get_storage(), PHWHERE, prop_map, and PHG4Cell::type_int.
void PHG4Cellv1::set_property (const PROPERTY prop_id, const unsigned int value) override virtual
Reimplemented from PHG4Cell.
Definition at line 187 of file PHG4Cellv1.cc.
View newest version in sPHENIX GitHub at line 187 of file PHG4Cellv1.cc
References PHG4Cell::check_property(), PHG4Cell::get_property_info(), PHG4Cell::get_property_type(), PHG4Cellv1::u_property::get_storage(), PHWHERE, prop_map, and PHG4Cell::type_uint.
void PHG4Cellv1::set_property_nocheck (const PROPERTY prop_id, const unsigned int ui) inline override protected virtual
Reimplemented from PHG4Cell.
Definition at line 102 of file PHG4Cellv1.h.
View newest version in sPHENIX GitHub at line 102 of file PHG4Cellv1.h
References prop_map.
void PHG4Cellv1::set_stave_index (const int i) inline override virtual
Reimplemented from PHG4Cell.
Definition at line 81 of file PHG4Cellv1.h.
View newest version in sPHENIX GitHub at line 81 of file PHG4Cellv1.h
References PHG4Cell::prop_stave_index, and set_property().
void PHG4Cellv1::set_zbin (const int i) inline override virtual
Reimplemented from PHG4Cell.
Definition at line 84 of file PHG4Cellv1.h.
View newest version in sPHENIX GitHub at line 84 of file PHG4Cellv1.h
References PHG4Cell::prop_zbin, and set_property().
Member Data Documentation
PHG4CellDefs::keytype PHG4Cellv1::cellid = ~0x0 protected
Definition at line 104 of file PHG4Cellv1.h.
View newest version in sPHENIX GitHub at line 104 of file PHG4Cellv1.h
Referenced by get_cellid(), get_detid(), has_binning(), identify(), and set_cellid().
EdepMap PHG4Cellv1::hitedeps protected
Definition at line 105 of file PHG4Cellv1.h.
View newest version in sPHENIX GitHub at line 105 of file PHG4Cellv1.h
Referenced by add_edep(), get_g4hits(), identify(), Reset(), and ~PHG4Cellv1().
prop_map_t PHG4Cellv1::prop_map protected
container for additional property
Definition at line 141 of file PHG4Cellv1.h.
View newest version in sPHENIX GitHub at line 141 of file PHG4Cellv1.h
Referenced by add_property(), get_property_float(), get_property_int(), get_property_nocheck(), get_property_uint(), has_property(), identify(), Reset(), set_property(), set_property_nocheck(), and ~PHG4Cellv1().
ShowerEdepMap PHG4Cellv1::showeredeps protected
Definition at line 106 of file PHG4Cellv1.h.
View newest version in sPHENIX GitHub at line 106 of file PHG4Cellv1.h
Referenced by add_shower_edep(), get_g4showers(), identify(), Reset(), and ~PHG4Cellv1().
The documentation for this class was generated from the following files:
coresoftware/blob/master/simulation/g4simulation/g4detectors/PHG4Cellv1.h
coresoftware/blob/master/simulation/g4simulation/g4detectors/PHG4Cellv1.cc