Analysis Software: G4Eval Namespace Reference
G4Eval Namespace Reference
Classes
class TrkrClusterComparer
struct ClusKeyIter
class ClusCntr
Typedefs
using ClusLoc = std::tuple< int, Eigen::Vector3d, int, int >
Functions
std::vector< int > unmatchedSvtxTrkIds (EmbRecoMatchContainer *matches, SvtxTrackMap *m_SvtxTrackMap)
void write_StringToTFile (const std::string &msg_name, const std::string &msg)
int trklayer_0123 (TrkrDefs::hitsetkey key)
Variables
m_nz_widths {_nz_widths} {}
in_silicon {_track->get_silicon_seed() != nullptr}
has_tpc {_track->get_tpc_seed() != nullptr}
Typedef Documentation
using G4Eval::ClusLoc = typedef std::tuple<int, Eigen::Vector3d, int, int>
Definition at line 29 of file g4evaltools.h.
View newest version in sPHENIX GitHub at line 29 of file g4evaltools.h
Function Documentation
int G4Eval::trklayer_0123 (TrkrDefs::hitsetkey key)
Definition at line 82 of file g4evaltools.cc.
View newest version in sPHENIX GitHub at line 82 of file g4evaltools.cc
References TrkrDefs::getLayer(), and layer.
std::vector< int > G4Eval::unmatchedSvtxTrkIds (EmbRecoMatchContainer * matches, SvtxTrackMap * m_SvtxTrackMap)
Definition at line 34 of file g4evaltools.cc.
View newest version in sPHENIX GitHub at line 34 of file g4evaltools.cc
References EmbRecoMatchContainer::ids_RecoMatched(), and Acts::Experimental::detail::BlueprintHelper::sort().
Referenced by FillTruthRecoMatchTree::process_event().
void G4Eval::write_StringToTFile (const std::string & msg_name, const std::string & msg)
Definition at line 64 of file g4evaltools.cc.
View newest version in sPHENIX GitHub at line 64 of file g4evaltools.cc
References PHWHERE.
Variable Documentation
G4Eval::has_tpc {_track->get_tpc_seed() != nullptr}
Definition at line 281 of file g4evaltools.cc.
View newest version in sPHENIX GitHub at line 281 of file g4evaltools.cc
G4Eval::in_silicon {_track->get_silicon_seed() != nullptr}
Definition at line 280 of file g4evaltools.cc.
View newest version in sPHENIX GitHub at line 280 of file g4evaltools.cc
G4Eval::m_nz_widths {_nz_widths} {}
Definition at line 103 of file g4evaltools.cc.
View newest version in sPHENIX GitHub at line 103 of file g4evaltools.cc