Analysis Software: KFParticle_Container Class Reference
KFParticle_Container Class Reference
KFParticle container object.
#include <coresoftware/blob/master/offline/packages/KFParticle_sPHENIX/KFParticle_Container.h>
Public Types
typedef std::map< unsigned int,
KFParticle * > Map
typedef std::map< unsigned int,
KFParticle * >::const_iterator ConstIter
typedef std::map< unsigned int,
KFParticle * >::iterator Iter
Public Member Functions
KFParticle_Container ()
KFParticle_Container (const KFParticle_Container &kfparticlemap)
KFParticle_Container & operator= (const KFParticle_Container &kfparticlemap)
virtual ~KFParticle_Container ()
void identify (std::ostream &os=std::cout) const override
void Reset () override
Clear Event.
int isValid () const override
isValid returns non zero if object contains vailid data
PHObject * CloneMe () const override
Virtual copy constructor.
bool empty () const
size_t size () const
size_t count (unsigned int key) const
void clear ()
const KFParticle * get (unsigned int key) const
KFParticle * get (unsigned int key)
ConstIter begin () const
ConstIter find (unsigned int key) const
ConstIter end () const
Iter begin ()
Iter find (unsigned int key)
Iter end ()
KFParticle * insert (const KFParticle *particle)
ConstIter addParticle (KFParticle *particle)
ConstIter addParticleSpecifyKey (unsigned int key, KFParticle *particle)
Map returnParticlesByPDGid (int PDGid)
Use the PDG MC ID to return a subset of the KFParticle container, if those particle exist in the container.
size_t erase (unsigned int key)
Public Member Functions inherited from PHObject
PHObject ()
ctor
~PHObject () override
dtor
virtual PHObject * clone () const final
PHObject * Clone (const char *newname="") const final
void Copy (TObject &object) const final
virtual int isValid (const float) const
virtual int isValid (const double) const
virtual int isValid (const int) const
virtual int isValid (const unsigned int) const
virtual int isImplemented (const float f) const
virtual int isImplemented (const double f) const
virtual int isImplemented (const int i) const
virtual int isImplemented (const unsigned int i) const
virtual int Integrate () const
virtual int Integrate (PHObject *obj)
virtual void CopyFrom (const PHObject *obj)
Private Attributes
Map m_kfpmap
Detailed Description
KFParticle container object.
Container for KFParticle objects, based off SvtxTrackMap
Definition at line 19 of file KFParticle_Container.h.
View newest version in sPHENIX GitHub at line 19 of file KFParticle_Container.h
Member Typedef Documentation
typedef std::map<unsigned int, KFParticle*>::const_iterator KFParticle_Container::ConstIter
Definition at line 23 of file KFParticle_Container.h.
View newest version in sPHENIX GitHub at line 23 of file KFParticle_Container.h
typedef std::map<unsigned int, KFParticle*>::iterator KFParticle_Container::Iter
Definition at line 24 of file KFParticle_Container.h.
View newest version in sPHENIX GitHub at line 24 of file KFParticle_Container.h
typedef std::map<unsigned int, KFParticle*> KFParticle_Container::Map
Definition at line 22 of file KFParticle_Container.h.
View newest version in sPHENIX GitHub at line 22 of file KFParticle_Container.h
Constructor & Destructor Documentation
KFParticle_Container::KFParticle_Container ()
Definition at line 21 of file KFParticle_Container.cc.
View newest version in sPHENIX GitHub at line 21 of file KFParticle_Container.cc
Referenced by CloneMe().
KFParticle_Container::KFParticle_Container (const KFParticle_Container & kfparticlemap)
Definition at line 26 of file KFParticle_Container.cc.
View newest version in sPHENIX GitHub at line 26 of file KFParticle_Container.cc
References begin(), end(), KFParticleBase::Id(), m_kfpmap, and particle.
KFParticle_Container::~KFParticle_Container () virtual
Definition at line 51 of file KFParticle_Container.cc.
View newest version in sPHENIX GitHub at line 51 of file KFParticle_Container.cc
References Reset().
Member Function Documentation
KFParticle_Container::ConstIter KFParticle_Container::addParticle (KFParticle * particle)
Definition at line 98 of file KFParticle_Container.cc.
View newest version in sPHENIX GitHub at line 98 of file KFParticle_Container.cc
References addParticleSpecifyKey(), KFParticleBase::Id(), and particle.
KFParticle_Container::ConstIter KFParticle_Container::addParticleSpecifyKey (unsigned int key, KFParticle * particle)
Definition at line 104 of file KFParticle_Container.cc.
View newest version in sPHENIX GitHub at line 104 of file KFParticle_Container.cc
References m_kfpmap.
Referenced by addParticle().
ConstIter KFParticle_Container::begin () const inline
Definition at line 44 of file KFParticle_Container.h.
View newest version in sPHENIX GitHub at line 44 of file KFParticle_Container.h
References m_kfpmap.
Referenced by KFParticle_Container(), operator=(), and KFParticle_DST::printNode().
Iter KFParticle_Container::begin () inline
Definition at line 48 of file KFParticle_Container.h.
View newest version in sPHENIX GitHub at line 48 of file KFParticle_Container.h
References m_kfpmap.
void KFParticle_Container::clear () inline
Definition at line 39 of file KFParticle_Container.h.
View newest version in sPHENIX GitHub at line 39 of file KFParticle_Container.h
References Reset().
PHObject* KFParticle_Container::CloneMe () const inline override virtual
Virtual copy constructor.
Reimplemented from PHObject.
Definition at line 34 of file KFParticle_Container.h.
View newest version in sPHENIX GitHub at line 34 of file KFParticle_Container.h
References KFParticle_Container().
size_t KFParticle_Container::count (unsigned int key) const inline
Definition at line 38 of file KFParticle_Container.h.
View newest version in sPHENIX GitHub at line 38 of file KFParticle_Container.h
References m_kfpmap.
bool KFParticle_Container::empty () const inline
Definition at line 36 of file KFParticle_Container.h.
View newest version in sPHENIX GitHub at line 36 of file KFParticle_Container.h
References m_kfpmap.
ConstIter KFParticle_Container::end () const inline
Definition at line 46 of file KFParticle_Container.h.
View newest version in sPHENIX GitHub at line 46 of file KFParticle_Container.h
References m_kfpmap.
Referenced by KFParticle_Container(), operator=(), and KFParticle_DST::printNode().
Iter KFParticle_Container::end () inline
Definition at line 50 of file KFParticle_Container.h.
View newest version in sPHENIX GitHub at line 50 of file KFParticle_Container.h
References m_kfpmap.
size_t KFParticle_Container::erase (unsigned int key)
Definition at line 130 of file KFParticle_Container.cc.
View newest version in sPHENIX GitHub at line 130 of file KFParticle_Container.cc
References m_kfpmap.
ConstIter KFParticle_Container::find (unsigned int key) const inline
Definition at line 45 of file KFParticle_Container.h.
View newest version in sPHENIX GitHub at line 45 of file KFParticle_Container.h
References m_kfpmap.
Iter KFParticle_Container::find (unsigned int key) inline
Definition at line 49 of file KFParticle_Container.h.
View newest version in sPHENIX GitHub at line 49 of file KFParticle_Container.h
References m_kfpmap.
const KFParticle * KFParticle_Container::get (unsigned int key) const
Definition at line 74 of file KFParticle_Container.cc.
View newest version in sPHENIX GitHub at line 74 of file KFParticle_Container.cc
References m_kfpmap.
KFParticle * KFParticle_Container::get (unsigned int key)
Definition at line 81 of file KFParticle_Container.cc.
View newest version in sPHENIX GitHub at line 81 of file KFParticle_Container.cc
References m_kfpmap.
void KFParticle_Container::identify (std::ostream & os = std::cout) const override virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from PHObject.
Definition at line 68 of file KFParticle_Container.cc.
View newest version in sPHENIX GitHub at line 68 of file KFParticle_Container.cc
References m_kfpmap.
KFParticle * KFParticle_Container::insert (const KFParticle * particle)
Definition at line 88 of file KFParticle_Container.cc.
View newest version in sPHENIX GitHub at line 88 of file KFParticle_Container.cc
References index, and m_kfpmap.
Referenced by KFParticle_DST::fillParticleNode_Particle().
int KFParticle_Container::isValid () const inline override virtual
isValid returns non zero if object contains vailid data
Reimplemented from PHObject.
Definition at line 33 of file KFParticle_Container.h.
View newest version in sPHENIX GitHub at line 33 of file KFParticle_Container.h
KFParticle_Container & KFParticle_Container::operator= (const KFParticle_Container & kfparticlemap)
Definition at line 38 of file KFParticle_Container.cc.
View newest version in sPHENIX GitHub at line 38 of file KFParticle_Container.cc
References begin(), end(), KFParticleBase::Id(), m_kfpmap, particle, and Reset().
void KFParticle_Container::Reset () override virtual
Clear Event.
Reimplemented from PHObject.
Definition at line 56 of file KFParticle_Container.cc.
View newest version in sPHENIX GitHub at line 56 of file KFParticle_Container.cc
References m_kfpmap, and particle.
Referenced by clear(), operator=(), and ~KFParticle_Container().
KFParticle_Container::Map KFParticle_Container::returnParticlesByPDGid (int PDGid)
Use the PDG MC ID to return a subset of the KFParticle container, if those particle exist in the container.
Definition at line 119 of file KFParticle_Container.cc.
View newest version in sPHENIX GitHub at line 119 of file KFParticle_Container.cc
References m_kfpmap.
size_t KFParticle_Container::size (void) const inline
Definition at line 37 of file KFParticle_Container.h.
View newest version in sPHENIX GitHub at line 37 of file KFParticle_Container.h
References m_kfpmap.
Member Data Documentation
Map KFParticle_Container::m_kfpmap private
Definition at line 62 of file KFParticle_Container.h.
View newest version in sPHENIX GitHub at line 62 of file KFParticle_Container.h
Referenced by addParticleSpecifyKey(), begin(), count(), empty(), end(), erase(), find(), get(), identify(), insert(), KFParticle_Container(), operator=(), Reset(), returnParticlesByPDGid(), and size().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/KFParticle_sPHENIX/KFParticle_Container.h
coresoftware/blob/master/offline/packages/KFParticle_sPHENIX/KFParticle_Container.cc