Analysis Software: odbc::DatabaseMetaData Class Reference
odbc::DatabaseMetaData Class Reference
#include <RDBC/blob/master/include/RDBC/odbc++/databasemetadata.h>
Public Types
enum { bestRowTemporary = SQL_SCOPE_CURROW, bestRowTransaction = SQL_SCOPE_TRANSACTION, bestRowSession = SQL_SCOPE_SESSION }
enum { bestRowUnknown = SQL_PC_UNKNOWN, bestRowPseudo = SQL_PC_PSEUDO, bestRowNotPseudo = SQL_PC_NOT_PSEUDO }
enum { versionColumnNotPseudo = SQL_PC_NOT_PSEUDO, versionColumnPseudo = SQL_PC_PSEUDO, versionColumnUnknown = SQL_PC_UNKNOWN }
enum { typeNoNulls = SQL_NO_NULLS, typeNullable = SQL_NULLABLE, typeNullableUnknown = SQL_NULLABLE_UNKNOWN }
enum { columnNoNulls = SQL_NO_NULLS, columnNullable = SQL_NULLABLE, columnNullableUnknown = SQL_NULLABLE_UNKNOWN }
enum { typePredNone = SQL_UNSEARCHABLE, typePredChar = SQL_LIKE_ONLY, typePredBasic = SQL_ALL_EXCEPT_LIKE, typeSearchable = SQL_SEARCHABLE }
enum {
importedKeyCascade = SQL_CASCADE, importedKeySetNull = SQL_SET_NULL, importedKeyRestrict = SQL_RESTRICT, importedKeyNoAction = SQL_RESTRICT,
importedKeySetDefault
}
enum { tableIndexClustered = SQL_INDEX_CLUSTERED, tableIndexHashed = SQL_INDEX_HASHED, tableIndexOther = SQL_INDEX_OTHER, tableIndexStatistic = SQL_TABLE_STAT }
enum {
procedureColumnIn = SQL_PARAM_INPUT, procedureColumnInOut = SQL_PARAM_INPUT_OUTPUT, procedureColumnOut = SQL_PARAM_OUTPUT, procedureColumnResult = SQL_RESULT_COL,
procedureColumnReturn = SQL_RETURN_VALUE, procedureColumnUnknown = SQL_PARAM_TYPE_UNKNOWN
}
enum { procedureNoNulls = SQL_NO_NULLS, procedureNullable = SQL_NULLABLE, procedureNullableUnknown = SQL_NULLABLE_UNKNOWN }
enum { procedureReturnsResult = SQL_PT_FUNCTION, procedureNoResult = SQL_PT_PROCEDURE, procedureResultUnknown = SQL_PT_UNKNOWN }
Public Member Functions
Connection * getConnection ()
ODBCXX_STRING getDatabaseProductName ()
ODBCXX_STRING getDatabaseProductVersion ()
ODBCXX_STRING getDriverName ()
ODBCXX_STRING getDriverVersion ()
int getDriverMajorVersion ()
int getDriverMinorVersion ()
ODBCXX_STRING getIdentifierQuoteString ()
ODBCXX_STRING getCatalogTerm ()
ODBCXX_STRING getSchemaTerm ()
ODBCXX_STRING getTableTerm ()
ODBCXX_STRING getProcedureTerm ()
ODBCXX_STRING getUserName ()
ODBCXX_STRING getCatalogSeparator ()
bool isCatalogAtStart ()
ODBCXX_STRING getSQLKeywords ()
bool supportsTransactions ()
int getDefaultTransactionIsolation ()
bool supportsTransactionIsolationLevel (int lev)
bool supportsDataDefinitionAndDataManipulationTransactions ()
bool supportsDataManipulationTransactionsOnly ()
bool dataDefinitionCausesTransactionCommit ()
bool dataDefinitionIgnoredInTransactions ()
bool supportsTableCorrelationNames ()
bool supportsDifferentTableCorrelationNames ()
bool supportsOrderByUnrelated ()
bool supportsExpressionsInOrderBy ()
bool supportsOpenCursorsAcrossCommit ()
bool supportsOpenCursorsAcrossRollback ()
bool supportsOpenStatementsAcrossCommit ()
bool supportsOpenStatementsAcrossRollback ()
bool supportsResultSetType (int type)
bool supportsResultSetConcurrency (int type, int concurrency)
bool supportsCatalogsInDataManipulation ()
bool supportsCatalogsInProcedureCalls ()
bool supportsCatalogsInTableDefinitions ()
bool supportsCatalogsInIndexDefinitions ()
bool supportsCatalogsInPrivilegeDefinitions ()
bool supportsSchemasInDataManipulation ()
bool supportsSchemasInProcedureCalls ()
bool supportsSchemasInTableDefinitions ()
bool supportsSchemasInIndexDefinitions ()
bool supportsSchemasInPrivilegeDefinitions ()
bool nullPlusNonNullIsNull ()
bool supportsColumnAliasing ()
bool supportsConvert ()
bool supportsConvert (int fromType, int toType)
bool supportsAlterTableWithDropColumn ()
bool supportsAlterTableWithAddColumn ()
ODBCXX_STRING getExtraNameCharacters ()
ODBCXX_STRING getSearchStringEscape ()
ODBCXX_STRING getTimeDateFunctions ()
ODBCXX_STRING getSystemFunctions ()
ODBCXX_STRING getStringFunctions ()
ODBCXX_STRING getNumericFunctions ()
bool supportsLikeEscapeClause ()
bool supportsMultipleResultSets ()
bool supportsMultipleTransactions ()
bool supportsNonNullableColumns ()
bool supportsMinimumSQLGrammar ()
bool supportsCoreSQLGrammar ()
bool supportsExtendedSQLGrammar ()
bool supportsANSI92EntryLevelSQL ()
bool supportsANSI92IntermediateSQL ()
bool supportsANSI92FullSQL ()
bool supportsPositionedDelete ()
bool supportsPositionedUpdate ()
bool supportsSelectForUpdate ()
bool supportsIntegrityEnhancementFacility ()
bool supportsBatchUpdates ()
bool supportsSubqueriesInComparisons ()
bool supportsSubqueriesInExists ()
bool supportsSubqueriesInIns ()
bool supportsSubqueriesInQuantifieds ()
bool supportsCorrelatedSubqueries ()
bool ownUpdatesAreVisible (int type)
bool ownDeletesAreVisible (int type)
bool ownInsertsAreVisible (int type)
bool othersUpdatesAreVisible (int type)
bool othersDeletesAreVisible (int type)
bool othersInsertsAreVisible (int type)
bool deletesAreDetected (int type)
bool insertsAreDetected (int type)
bool updatesAreDetected (int type)
int getMaxBinaryLiteralLength ()
int getMaxCharLiteralLength ()
int getMaxColumnNameLength ()
int getMaxColumnsInGroupBy ()
int getMaxColumnsInIndex ()
int getMaxColumnsInOrderBy ()
int getMaxColumnsInSelect ()
int getMaxColumnsInTable ()
int getMaxCursorNameLength ()
int getMaxIndexLength ()
int getMaxSchemaNameLength ()
int getMaxProcedureNameLength ()
int getMaxCatalogNameLength ()
int getMaxRowSize ()
bool doesMaxRowSizeIncludeBlobs ()
int getMaxStatementLength ()
int getMaxTableNameLength ()
int getMaxTablesInSelect ()
int getMaxUserNameLength ()
int getMaxConnections ()
int getMaxStatements ()
bool supportsMixedCaseIdentifiers ()
bool supportsMixedCaseQuotedIdentifiers ()
bool supportsStoredProcedures ()
bool supportsGroupBy ()
bool supportsGroupByUnrelated ()
bool supportsGroupByBeyondSelect ()
bool supportsUnion ()
bool supportsUnionAll ()
bool supportsOuterJoins ()
bool supportsFullOuterJoins ()
bool supportsLimitedOuterJoins ()
bool usesLocalFilePerTable ()
bool usesLocalFiles ()
bool nullsAreSortedAtStart ()
bool nullsAreSortedAtEnd ()
bool nullsAreSortedHigh ()
bool nullsAreSortedLow ()
bool allProceduresAreCallable ()
bool allTablesAreSelectable ()
bool isReadOnly ()
bool storesLowerCaseIdentifiers ()
bool storesLowerCaseQuotedIdentifiers ()
bool storesMixedCaseIdentifiers ()
bool storesMixedCaseQuotedIdentifiers ()
bool storesUpperCaseIdentifiers ()
bool storesUpperCaseQuotedIdentifiers ()
ResultSet * getTypeInfo ()
ResultSet * getColumns (const ODBCXX_STRING &catalog, const ODBCXX_STRING &schemaPattern, const ODBCXX_STRING &tableNamePattern, const ODBCXX_STRING &columnNamePattern)
ResultSet * getTables (const ODBCXX_STRING &catalog, const ODBCXX_STRING &schemaPattern, const ODBCXX_STRING &tableNamePattern, const std::vector< ODBCXX_STRING > &types)
ResultSet * getTablePrivileges (const ODBCXX_STRING &catalog, const ODBCXX_STRING &schemaPattern, const ODBCXX_STRING &tableNamePattern)
ResultSet * getColumnPrivileges (const ODBCXX_STRING &catalog, const ODBCXX_STRING &schema, const ODBCXX_STRING &table, const ODBCXX_STRING &columnNamePattern)
ResultSet * getPrimaryKeys (const ODBCXX_STRING &catalog, const ODBCXX_STRING &schema, const ODBCXX_STRING &table)
ResultSet * getIndexInfo (const ODBCXX_STRING &catalog, const ODBCXX_STRING &schema, const ODBCXX_STRING &table, bool unique, bool approximate)
ResultSet * getCrossReference (const ODBCXX_STRING &primaryCatalog, const ODBCXX_STRING &primarySchema, const ODBCXX_STRING &primaryTable, const ODBCXX_STRING &foreignCatalog, const ODBCXX_STRING &foreignSchema, const ODBCXX_STRING &foreignTable)
ResultSet * getImportedKeys (const ODBCXX_STRING &catalog, const ODBCXX_STRING &schema, const ODBCXX_STRING &table)
ResultSet * getExportedKeys (const ODBCXX_STRING &catalog, const ODBCXX_STRING &schema, const ODBCXX_STRING &table)
ResultSet * getProcedures (const ODBCXX_STRING &catalog, const ODBCXX_STRING &schemaPattern, const ODBCXX_STRING &procedureNamePattern)
ResultSet * getProcedureColumns (const ODBCXX_STRING &catalog, const ODBCXX_STRING &schemaPattern, const ODBCXX_STRING &procedureNamePattern, const ODBCXX_STRING &columnNamePattern)
ResultSet * getBestRowIdentifier (const ODBCXX_STRING &catalog, const ODBCXX_STRING &schema, const ODBCXX_STRING &table, int scope, bool nullable)
ResultSet * getVersionColumns (const ODBCXX_STRING &catalog, const ODBCXX_STRING &schema, const ODBCXX_STRING &table)
ResultSet * getTableTypes ()
ResultSet * getSchemas ()
ResultSet * getCatalogs ()
Private Member Functions
DatabaseMetaData (Connection *c)
~DatabaseMetaData ()
const DriverInfo * _getDriverInfo () const
SQLUSMALLINT _getNumeric16 (int what)
SQLUINTEGER _getNumeric32 (int what)
ODBCXX_STRING _getStringInfo (int what)
bool _ownXXXAreVisible (int type, int what)
Private Attributes
Connection * connection_
Friends
class Connection
class DriverInfo
Detailed Description
Provides several tons of information about a data source.
Warning
The column names in ResultSets returned by methods of DatabaseMetaData can differ depending on what ODBC version the current driver supports. To avoid problems, columns should be referenced by number, and not by name. Also note that ODBC version 2 drivers do not return some of the specified columns.
Definition at line 43 of file databasemetadata.h.
View newest version in sPHENIX GitHub at line 43 of file databasemetadata.h
Member Enumeration Documentation
anonymous enum
Constants for the ResultSet returned by getBestRowIdentifier
Enumerator:
bestRowTemporary
bestRowTransaction
bestRowSession
Definition at line 76 of file databasemetadata.h.
View newest version in sPHENIX GitHub at line 76 of file databasemetadata.h
anonymous enum
Constants for the ResultSet returned by getBestRowIdentifier
Enumerator:
bestRowUnknown
bestRowPseudo
bestRowNotPseudo
Definition at line 83 of file databasemetadata.h.
View newest version in sPHENIX GitHub at line 83 of file databasemetadata.h
anonymous enum
Version column constants for getVersionColumns()
See Also
getVersionColumns()
Enumerator:
versionColumnNotPseudo
versionColumnPseudo
versionColumnUnknown
Definition at line 93 of file databasemetadata.h.
View newest version in sPHENIX GitHub at line 93 of file databasemetadata.h
anonymous enum
Nullability constants for the resultset returned by getTypes()
See Also
getTypes()
Enumerator:
typeNoNulls
typeNullable
typeNullableUnknown
Definition at line 103 of file databasemetadata.h.
View newest version in sPHENIX GitHub at line 103 of file databasemetadata.h
anonymous enum
Nullability constants for the resultset returned by getColumns().
See Also
getColumns()
Enumerator:
columnNoNulls
columnNullable
columnNullableUnknown
Definition at line 113 of file databasemetadata.h.
View newest version in sPHENIX GitHub at line 113 of file databasemetadata.h
anonymous enum
Searchability constants
Enumerator:
typePredNone
Column is unsearchable
typePredChar
Column can only be used in a LIKE clause
typePredBasic
Column can be used in searches, except in LIKE
typeSearchable
Column is searchable
Definition at line 120 of file databasemetadata.h.
View newest version in sPHENIX GitHub at line 120 of file databasemetadata.h
anonymous enum
Imported key UPDATE_RULE and DELETE_RULE constants.
See Also
getImportedKeys()
Enumerator:
importedKeyCascade
importedKeySetNull
importedKeyRestrict
importedKeyNoAction
importedKeySetDefault
Definition at line 145 of file databasemetadata.h.
View newest version in sPHENIX GitHub at line 145 of file databasemetadata.h
anonymous enum
Index type constants
Enumerator:
tableIndexClustered
tableIndexHashed
tableIndexOther
tableIndexStatistic
Definition at line 169 of file databasemetadata.h.
View newest version in sPHENIX GitHub at line 169 of file databasemetadata.h
anonymous enum
Procedure column type constants for getProcedureColumns()
See Also
getProcedureColumns()
Enumerator:
procedureColumnIn
procedureColumnInOut
procedureColumnOut
procedureColumnResult
procedureColumnReturn
procedureColumnUnknown
Definition at line 179 of file databasemetadata.h.
View newest version in sPHENIX GitHub at line 179 of file databasemetadata.h
anonymous enum
Procedure column nullability constants for getProcedureColumns()
See Also
getProcedureColumns()
Enumerator:
procedureNoNulls
procedureNullable
procedureNullableUnknown
Definition at line 191 of file databasemetadata.h.
View newest version in sPHENIX GitHub at line 191 of file databasemetadata.h
anonymous enum
Procedure type constants for PROCEDURE_TYPE in getProcedures()
See Also
getProcedures()
Enumerator:
procedureReturnsResult
procedureNoResult
procedureResultUnknown
Definition at line 200 of file databasemetadata.h.
View newest version in sPHENIX GitHub at line 200 of file databasemetadata.h
Constructor & Destructor Documentation
odbc::DatabaseMetaData::DatabaseMetaData (Connection * c) private
odbc::DatabaseMetaData::~DatabaseMetaData () private
Member Function Documentation
const DriverInfo* odbc::DatabaseMetaData::_getDriverInfo () const inline private
Definition at line 53 of file databasemetadata.h.
View newest version in sPHENIX GitHub at line 53 of file databasemetadata.h
SQLUSMALLINT odbc::DatabaseMetaData::_getNumeric16 (int what) private
SQLUINTEGER odbc::DatabaseMetaData::_getNumeric32 (int what) private
ODBCXX_STRING odbc::DatabaseMetaData::_getStringInfo (int what) private
bool odbc::DatabaseMetaData::_ownXXXAreVisible (int type, int what) private
bool odbc::DatabaseMetaData::allProceduresAreCallable ()
Returns true if all procedures returned by getProcedures() are callable by the current user.
Referenced by ODBCDatabaseMetaData::AllProceduresAreCallable().
bool odbc::DatabaseMetaData::allTablesAreSelectable ()
Returns true if all tables returned by getTables() are selectable by the current user.
Referenced by ODBCDatabaseMetaData::AllTablesAreSelectable().
bool odbc::DatabaseMetaData::dataDefinitionCausesTransactionCommit ()
Checks if DDL in a transaction will cause the transaction to be committed
Returns
true if the data source only supports data manipulation (eg. UPDATE, INSERT) within a transaction and any data definition (eg. CREATE TABLE) will cause the transaction to be committed.
If this method returns true, supportsDataDefinitionAndDataManipulationTransactions(), supportsDataManipulationTransactionsOnly() and dataDefinitionIgnoredInTransactions() all return false.
Referenced by ODBCDatabaseMetaData::DataDefinitionCausesTransactionCommit().
bool odbc::DatabaseMetaData::dataDefinitionIgnoredInTransactions ()
Checks if DDL in a transaction is ignored
Returns
true if the data source only supports data manipulation (eg. UPDATE, INSERT) within a transaction and any data definition (eg. CREATE TABLE) will be ignored.
If this method returns true, supportsDataDefinitionAndDataManipulationTransactions(), supportsDataManipulationTransactionsOnly() and dataDefinitionCausesTransactionCommit() all return false.
Referenced by ODBCDatabaseMetaData::DataDefinitionIgnoredInTransactions().
bool odbc::DatabaseMetaData::deletesAreDetected (int type)
Returns true if a deleted row can be detected with ResultSet::rowDeleted().
Parameters
type The type of ResultSet of interest
Referenced by ODBCDatabaseMetaData::DeletesAreDetected().
bool odbc::DatabaseMetaData::doesMaxRowSizeIncludeBlobs ()
Returns true if the value returned by getMaxRowSize() includes BLOBs.
Referenced by ODBCDatabaseMetaData::DoesMaxRowSizeIncludeBlobs().
ResultSet* odbc::DatabaseMetaData::getBestRowIdentifier (const ODBCXX_STRING & catalog, const ODBCXX_STRING & schema, const ODBCXX_STRING & table, int scope, bool nullable)
Returns the optimal set of columns that identifies a row.
The returned ResultSet is ordered by SCOPE and has the following columns:
SCOPE - short - scope of this result:
bestRowTemporary - temporary, only while a ResultSet is using the row
bestRowTransaction - valid until the current transaction ends
bestRowSession - valid through the whole session - until the connection is closed
COLUMN_NAME - string - the column name
DATA_TYPE - short - the type of the column from Types
TYPE_NAME - string - native type name (data source dependent)
COLUMN_SIZE - int - the size (precision) of the column.
BUFFER_LENGTH - int - unused
DECIMAL_DIGITS - short - scale if applicable. Can be NULL.
PSEUDO_COLUMN - short - whether this is a pseudo column:
bestRowUnknown - it is unknown whether this is a pseudo column
bestRowNotPseudo - it is definitely not a pseudo column
bestRowPseudo - it is definitely a pseudo column
Parameters
catalog the catalog name
schema the schema name
table the table name
scope the scope of interest, same values as the SCOPE column.
nullable whether nullable columns should be included
Referenced by ODBCDatabaseMetaData::GetBestRowIdentifier().
ResultSet* odbc::DatabaseMetaData::getCatalogs ()
Returns a list of available catalogs in the database.
The returned ResultSet is the same as with getTables(), except that all columns but TABLE_CAT are NULL values.
Referenced by ODBCDatabaseMetaData::GetCatalogs().
ODBCXX_STRING odbc::DatabaseMetaData::getCatalogSeparator ()
Returns the string used to separate a catalog in a fully qualified identifier.
For example Oracle would return a "@", while mysql would say ".".
Referenced by ODBCDatabaseMetaData::GetCatalogSeparator().
ODBCXX_STRING odbc::DatabaseMetaData::getCatalogTerm ()
Returns the term for catalog used by the data source. Can be for example "directory" or "database".
Referenced by ODBCDatabaseMetaData::GetCatalogTerm(), and OnlMonDBodbc::Info().
ResultSet* odbc::DatabaseMetaData::getColumnPrivileges (const ODBCXX_STRING & catalog, const ODBCXX_STRING & schema, const ODBCXX_STRING & table, const ODBCXX_STRING & columnNamePattern)
Fetches a list of access rights for a table's columns.
The returned ResultSet is ordered by COLUMN_NAME and PRIVILEGE. It contains the following columns:
TABLE_CAT - string - table catalog (can be NULL)
TABLE_SCHEM - string - table schema (can be NULL)
TABLE_NAME - string - table name
COLUMN_NAME - string - column name
GRANTOR - string - grantor (can be NULL). If GRANTEE owns the object, GRANTOR is "SYSTEM".
GRANTEE - string - grantee
PRIVILEGE - string - one of "SELECT", "INSERT", "UPDATE", "DELETE", "REFERENCES" or a data source specific value
IS_GRANTABLE - string - "YES" if GRANTEE can grant this privilege to other users. "NO" if not. NULL if unknown.
Referenced by ODBCDatabaseMetaData::GetColumnPrivileges().
ResultSet* odbc::DatabaseMetaData::getColumns (const ODBCXX_STRING & catalog, const ODBCXX_STRING & schemaPattern, const ODBCXX_STRING & tableNamePattern, const ODBCXX_STRING & columnNamePattern)
Fetches the available columns in a catalog.
The returned ResultSet has the following columns:
TABLE_CAT - string - table catalog (can be NULL)
TABLE_SCHEM - string - table schema (can be NULL)
TABLE_NAME - string - table name
COLUMN_NAME - string - column name
COLUMN_TYPE - short - see Types
TYPE_NAME - string - the name of the type. Data source dependent.
COLUMN_SIZE - int - column size. For character and date types, this is the maximum number of characters. For numeric types this is the precision.
BUFFER_LENGTH - not used
DECIMAL_DIGITS - int - the number of fractional digits.
NUM_PREC_RADIX - int - radix
NULLABLE - int - whether the column allows NULLs
columnNoNulls - might not allow NULLs
columnNullable - definitely allows NULLs
columnNullableUnknown - nullability is unknown
REMARKS - string - comments on the column (can be NULL)
COLUMN_DEF - string - default value (can be NULL)
SQL_DATA_TYPE - short -
SQL_DATETIME_SUB - short -
CHAR_OCTET_LENGTH - int - for character data types the maximum number of bytes in the column
ORDINAL_POSITION - int - 1-based index in the table
IS_NULLABLE - string - "NO" means in no way nullable, "YES" means possibly nullable. Empty string means nobody knows.
Referenced by ODBCDatabaseMetaData::GetColumns().
Connection* odbc::DatabaseMetaData::getConnection () inline
Returns the Connection this came from
Definition at line 71 of file databasemetadata.h.
View newest version in sPHENIX GitHub at line 71 of file databasemetadata.h
ResultSet* odbc::DatabaseMetaData::getCrossReference (const ODBCXX_STRING & primaryCatalog, const ODBCXX_STRING & primarySchema, const ODBCXX_STRING & primaryTable, const ODBCXX_STRING & foreignCatalog, const ODBCXX_STRING & foreignSchema, const ODBCXX_STRING & foreignTable)
Figures out in which way a foreign key table references a primary key table. Returns it's findings in a ResultSet, ordered by FKTABLE_CAT, FKTABLE_SCHEM, FKTABLE_NAME and KEY_SEQ. The ResultSet contains the following columns:
PKTABLE_CAT - string - primary key table catalog
PKTABLE_SCHEM - string - primary key table schema
PKTABLE_NAME - string - primary key table name
PKCOLUMN_NAME - string - primary key column name
FKTABLE_CAT - string - foreign key table catalog
FKTABLE_SCHEM - string - foreign key table schema
FKTABLE_NAME - string - foreign key table name
FKCOLUMN_NAME - string - foreign key column name
KEY_SEQ - short - column sequence number in key (1-based)
UPDATE_RULE - short - what happens to the foreign key when the primary is updated:
importedKeyNoAction - nothing happends since the primary key can not be updated
importedKeyCascade - change imported key to match the primary key
importedKeySetNull - update the imported key to NULL
importedKeySetDefault - update the impored key to it's default value
importedKeyRestrict - same as importedKeyNoAction
DELETE_RULE - short - what happens to the foreign key when the primary is deleted:
importedKeyNoAction - nothing happends since the primary key can not be deleted
importedKeyCascade - imported key is deleted as well
importedKeySetNull - imported key is set to NULL
importedKeySetDefault - imported key is set to it's default value
importedKeyRestrict - same as importedKeyNoAction
Referenced by ODBCDatabaseMetaData::GetCrossReference().
ODBCXX_STRING odbc::DatabaseMetaData::getDatabaseProductName ()
Returns the name of the database product.
Referenced by ODBCDatabaseMetaData::GetDatabaseProductName().
ODBCXX_STRING odbc::DatabaseMetaData::getDatabaseProductVersion ()
Returns the version of the database product as a string.
Referenced by OnlMonDBodbc::DropTable(), ODBCDatabaseMetaData::GetDatabaseProductVersion(), and OnlMonDBodbc::Info().
int odbc::DatabaseMetaData::getDefaultTransactionIsolation ()
Returns the default transaction isolation level
See Also
Connection
Referenced by ODBCDatabaseMetaData::GetDefaultTransactionIsolation().
int odbc::DatabaseMetaData::getDriverMajorVersion ()
Returns the major ODBC version of the driver used.
Referenced by ODBCDatabaseMetaData::GetDriverMajorVersion().
int odbc::DatabaseMetaData::getDriverMinorVersion ()
Returns the minor ODBC version of the driver used.
Referenced by ODBCDatabaseMetaData::GetDriverMinorVersion().
ODBCXX_STRING odbc::DatabaseMetaData::getDriverName ()
Returns the name of the ODBC driver used.
Referenced by ODBCDatabaseMetaData::GetDriverName(), and OnlMonDBodbc::Info().
ODBCXX_STRING odbc::DatabaseMetaData::getDriverVersion ()
Returns the version of the ODBC driver used.
Referenced by ODBCDatabaseMetaData::GetDriverVersion().
ResultSet* odbc::DatabaseMetaData::getExportedKeys (const ODBCXX_STRING & catalog, const ODBCXX_STRING & schema, const ODBCXX_STRING & table) inline
Fetches a list of columns that reference a table's primary keys.
The returned ResultSet is identical to the one returned by getCrossReference().
Definition at line 1167 of file databasemetadata.h.
View newest version in sPHENIX GitHub at line 1167 of file databasemetadata.h
Referenced by ODBCDatabaseMetaData::GetExportedKeys().
ODBCXX_STRING odbc::DatabaseMetaData::getExtraNameCharacters ()
Returns the extra characters beyond A-Z, a-z, 0-9 and _ that can be used in unquoted identifier names.
Referenced by ODBCDatabaseMetaData::GetExtraNameCharacters().
ODBCXX_STRING odbc::DatabaseMetaData::getIdentifierQuoteString ()
Returns the string that can be used to quote identifiers. If the data source doesn't support it, returns an empty string.
Referenced by ODBCDatabaseMetaData::GetIdentifierQuoteString().
ResultSet* odbc::DatabaseMetaData::getImportedKeys (const ODBCXX_STRING & catalog, const ODBCXX_STRING & schema, const ODBCXX_STRING & table) inline
Fetches a list of columns that are foreign keys to other tables' primary keys.
The returned ResultSet is identical to the one returned by getCrossReference(), except it's ordered by PKTABLE_CAT, PKTABLE_SCHEM, PKTABLE_NAME and KEY_SEQ.
Definition at line 1155 of file databasemetadata.h.
View newest version in sPHENIX GitHub at line 1155 of file databasemetadata.h
Referenced by ODBCDatabaseMetaData::GetImportedKeys().
ResultSet* odbc::DatabaseMetaData::getIndexInfo (const ODBCXX_STRING & catalog, const ODBCXX_STRING & schema, const ODBCXX_STRING & table, bool unique, bool approximate)
Fetches a list of indices and statistics for a table.
The returned ResultSet is ordered by NON_UNIQUE, TYPE, INDEX_QUALIFIER, INDEX_NAME and ORDINAL_POSITION. It contains the following columns:
TABLE_CAT - string - table catalog (can be NULL)
TABLE_SCHEM - string - table schema (can be NULL)
TABLE_NAME - string - table name
NON_UNIQUE - bool - true if index values can be non-unique. NULL if TYPE is tableIndexStatistic
INDEX_QUALIFIER - string - index catalog, NULL if TYPE is tableIndexStatistic
INDEX_NAME - string - index name, NULL if TYPE is tableIndexStatistic
TYPE - short - index type:
tableIndexStatistic - no real index - a statistic for the table
tableIndexClustered - this index is clustered
tableIndexHashed - this index is hashed
tableIndexOther - this is some other kind of index
ORDINAL_POSITION - short - column sequence number in index (1-based). NULL if TYPE is tableIndexStatistic.
COLUMN_NAME - string - column name. NULL if TYPE is tableIndexStatistic.
ASC_OR_DESC - string - "A" for ascending, "D" for descending index. NULL if TYPE is tableIndexStatistic.
CARDINALITY - int - If TYPE is tableIndexStatistic, the number of rows in the table. Otherwise, the number of unique values in the index.
PAGES - int - Number of pages used for the table if TYPE is tableIndexStatistic. Otherwise the number of pages used for the index.
FILTER_CONDITION - string - filter condition (if any)
Parameters
catalog the catalog name
schema the schema name
table the table name
unique whether only unique indices should be looked at
approximate whether only accurate values should be retrieved
Referenced by ODBCDatabaseMetaData::GetIndexInfo().
int odbc::DatabaseMetaData::getMaxBinaryLiteralLength ()
Returns the max number of hex characters allowed in an inline binary literal.
Referenced by ODBCDatabaseMetaData::GetMaxBinaryLiteralLength().
int odbc::DatabaseMetaData::getMaxCatalogNameLength ()
Returns the maximum length of a catalog name.
Referenced by ODBCDatabaseMetaData::GetMaxCatalogNameLength().
int odbc::DatabaseMetaData::getMaxCharLiteralLength ()
Returns the maximum length of an inline character string.
Referenced by ODBCDatabaseMetaData::GetMaxCharLiteralLength().
int odbc::DatabaseMetaData::getMaxColumnNameLength ()
Returns the maximum length of a column name.
Referenced by ODBCDatabaseMetaData::GetMaxColumnNameLength().
int odbc::DatabaseMetaData::getMaxColumnsInGroupBy ()
Returns the maximum number of columns this data source can have in a GROUP BY clause.
Referenced by ODBCDatabaseMetaData::GetMaxColumnsInGroupBy().
int odbc::DatabaseMetaData::getMaxColumnsInIndex ()
Returns the maximum number of columns allowed in an index.
Referenced by ODBCDatabaseMetaData::GetMaxColumnsInIndex().
int odbc::DatabaseMetaData::getMaxColumnsInOrderBy ()
Returns the maximum number of columns this data source can have in an ORDER BY clause.
Referenced by ODBCDatabaseMetaData::GetMaxColumnsInOrderBy().
int odbc::DatabaseMetaData::getMaxColumnsInSelect ()
Returns the maximum number of columns this data source can SELECT.
Referenced by ODBCDatabaseMetaData::GetMaxColumnsInSelect().
int odbc::DatabaseMetaData::getMaxColumnsInTable ()
Returns the maximum number of columns a table can consist of.
Referenced by ODBCDatabaseMetaData::GetMaxColumnsInTable().
int odbc::DatabaseMetaData::getMaxConnections ()
Returns the maximum number of connections we can have open to this data source.
Referenced by ODBCDatabaseMetaData::GetMaxConnections().
int odbc::DatabaseMetaData::getMaxCursorNameLength ()
Returns the maximum length of a cursor name.
Referenced by ODBCDatabaseMetaData::GetMaxCursorNameLength().
int odbc::DatabaseMetaData::getMaxIndexLength ()
Returns the maximum length of an index in bytes.
Referenced by ODBCDatabaseMetaData::GetMaxIndexLength().
int odbc::DatabaseMetaData::getMaxProcedureNameLength ()
Returns the maximum length of a procedure name.
Referenced by ODBCDatabaseMetaData::GetMaxProcedureNameLength().
int odbc::DatabaseMetaData::getMaxRowSize ()
Returns the maximum size of a row in bytes.
Referenced by ODBCDatabaseMetaData::GetMaxRowSize().
int odbc::DatabaseMetaData::getMaxSchemaNameLength ()
Returns the maximum length of a schema name.
Referenced by ODBCDatabaseMetaData::GetMaxSchemaNameLength().
int odbc::DatabaseMetaData::getMaxStatementLength ()
Returns the maximum length of a statement (query).
Referenced by ODBCDatabaseMetaData::GetMaxStatementLength().
int odbc::DatabaseMetaData::getMaxStatements ()
Returns the maximim number of statements that can be open on this connection.
Referenced by ODBCDatabaseMetaData::GetMaxStatements().
int odbc::DatabaseMetaData::getMaxTableNameLength ()
Returns the maximum length of a table name.
Referenced by ODBCDatabaseMetaData::GetMaxTableNameLength().
int odbc::DatabaseMetaData::getMaxTablesInSelect ()
Returns the maximum number of tables that can be joined at once.
Returns
zero if unknown.
Referenced by ODBCDatabaseMetaData::GetMaxTablesInSelect().
int odbc::DatabaseMetaData::getMaxUserNameLength ()
Returns the maximum length of a username.
Referenced by ODBCDatabaseMetaData::GetMaxUserNameLength().
ODBCXX_STRING odbc::DatabaseMetaData::getNumericFunctions ()
Returns a comma-separated list of all numeric functions supported.
Referenced by ODBCDatabaseMetaData::GetNumericFunctions().
ResultSet* odbc::DatabaseMetaData::getPrimaryKeys (const ODBCXX_STRING & catalog, const ODBCXX_STRING & schema, const ODBCXX_STRING & table)
Fetches a list of primary keys for a table.
The returned ResultSet is ordered by TABLE_CAT, TABLE_SCHEM, TABLE_NAME and KEY_SEQ. It contains the following columns:
TABLE_CAT - string - table catalog (can be NULL)
TABLE_SCHEM - string - table schema (can be NULL)
TABLE_NAME - string - table name
COLUMN_NAME - string - column name
KEY_SEQ - string - sequence number in primary key (1-based)
PK_NAME - string - primary key (constraint) name. Can be NULL.
Referenced by ODBCDatabaseMetaData::GetPrimaryKeys().
ResultSet* odbc::DatabaseMetaData::getProcedureColumns (const ODBCXX_STRING & catalog, const ODBCXX_STRING & schemaPattern, const ODBCXX_STRING & procedureNamePattern, const ODBCXX_STRING & columnNamePattern)
Returns available procedure columns in a catalog.
The returned ResultSet is ordered by PROCEDURE_CAT, PROCEDURE_SCHEM, PROCEDURE_NAME and COLUMN_NAME. It contains the following columns:
PROCEDURE_CAT - string - the procedure catalog
PROCEDURE_SCHEM - string - the procedure schema
PROCEDURE_NAME - string - the procedure name
COLUMN_NAME - string - the column name
COLUMN_TYPE - short - the column type
procedureColumnUnknown - beats the driver
procedureColumnIn - IN parameter
procedureColumnInOut - IN OUT parameter
procedureColumnOut - OUT parameter
procedureColumnReturn - procedure return value (eg. this procedure is actually a function)
procedureColumnResult - this column is part of a ResultSet this procedure returns
DATA_TYPE - int - SQL type of the column
TYPE_NAME - string - native type name
COLUMN_SIZE - int - the precision of the column
BUFFER_LENGTH - int - nothing of interest
DECIMAL_DIGITS - short - scale, if applicable
NUM_PREC_RADIX - short - radix, if applicable
NULLABLE - short - whether the column is nullable
procedureNoNulls - not nullable
procedureNullable - nullable
procedureNullableUnknown - nobody knows
REMARKS - string - comments on the column
Note: more columns can be returned depending on the driver.
Referenced by ODBCDatabaseMetaData::GetProcedureColumns().
ResultSet* odbc::DatabaseMetaData::getProcedures (const ODBCXX_STRING & catalog, const ODBCXX_STRING & schemaPattern, const ODBCXX_STRING & procedureNamePattern)
Returns available procedures in a catalog.
The returned ResultSet is ordered by PROCEDURE_CAT, PROCEDURE_SCHEM and PROCEDURE_NAME. It contains the following columns:
PROCEDURE_CAT - string - the procedure catalog
PROCEDURE_SCHEM - string - the procedure schema
PROCEDURE_NAME - string - the procedure name
NUM_INPUT_PARAMS - reserved for future use
NUM_OUTPUT_PARAMS - reserved for future use
NUM_RESULT_SETS - reserved for future use
REMARKS - string - comments on the procedure
PROCEDURE_TYPE - short - the procedure type:
procedureResultUnknown - can possibly return a result, but nobody is sure
procedureNoResult - does not return a result
procedureReturnsResult - returns a result
Referenced by ODBCDatabaseMetaData::GetProcedures().
ODBCXX_STRING odbc::DatabaseMetaData::getProcedureTerm ()
Returns the term the data source uses for a procedure, for example "stored procedure".
Referenced by ODBCDatabaseMetaData::GetProcedureTerm().
ResultSet* odbc::DatabaseMetaData::getSchemas ()
Returns a list of available schemas in the database.
The returned ResultSet is the same as with getTables(), except that all columns but TABLE_SCHEM contain NULL values.
Referenced by ODBCDatabaseMetaData::GetSchemas().
ODBCXX_STRING odbc::DatabaseMetaData::getSchemaTerm ()
Returns the term for schema used by the data source, for example "owner" or just "schema".
Referenced by ODBCDatabaseMetaData::GetSchemaTerm(), and OnlMonDBodbc::Info().
ODBCXX_STRING odbc::DatabaseMetaData::getSearchStringEscape ()
Returns the string that can be used to escape wildcard characters.
Referenced by ODBCDatabaseMetaData::GetSearchStringEscape().
ODBCXX_STRING odbc::DatabaseMetaData::getSQLKeywords ()
Returns a comma-separated list of all non-ODBC keywords specific to this data source.
Referenced by ODBCDatabaseMetaData::GetSQLKeywords().
ODBCXX_STRING odbc::DatabaseMetaData::getStringFunctions ()
Returns a comma-separated list of all string functions supported.
Referenced by ODBCDatabaseMetaData::GetStringFunctions().
ODBCXX_STRING odbc::DatabaseMetaData::getSystemFunctions ()
Returns a comma-separated list of all system functions supported.
Referenced by ODBCDatabaseMetaData::GetSystemFunctions().
ResultSet* odbc::DatabaseMetaData::getTablePrivileges (const ODBCXX_STRING & catalog, const ODBCXX_STRING & schemaPattern, const ODBCXX_STRING & tableNamePattern)
Fetches a list of access rights for tables in a catalog.
A table privilege applies to one or more columns in a table. Do not assume that this privilege is valid for all columns.
The returned ResultSet is ordered by TABLE_CAT, TABLE_SCHEM, TABLE_NAME and PRIVILEGE. It contains the following columns:
TABLE_CAT - string - table catalog (can be NULL)
TABLE_SCHEM - string - table schema (can be NULL)
TABLE_NAME - string - table name
GRANTOR - string - grantor (can be NULL). If GRANTEE owns the object, GRANTOR is "SYSTEM".
GRANTEE - string - grantee
PRIVILEGE - string - one of "SELECT", "INSERT", "UPDATE", "DELETE", "REFERENCES" or a data source specific value
IS_GRANTABLE - string - "YES" if GRANTEE can grant this privilege to other users. "NO" if not. NULL if unknown.
Referenced by ODBCDatabaseMetaData::GetTablePrivileges().
ResultSet* odbc::DatabaseMetaData::getTables (const ODBCXX_STRING & catalog, const ODBCXX_STRING & schemaPattern, const ODBCXX_STRING & tableNamePattern, const std::vector< ODBCXX_STRING > & types)
Fetches the available tables in the data source. The returned ResultSet has the following columns:
TABLE_CAT - string - table catalog (can be NULL)
TABLE_SCHEM - string - table schema (can be NULL)
TABLE_NAME - string - table name
TABLE_TYPE - string - table type
REMARKS - string - comments on the table
Parameters
catalog the catalog name
schemaPattern schema name search pattern
tableNamePattern table name search pattern
types a list of table types. An empty list returns all table types.
Referenced by ODBCDatabaseMetaData::GetTables(), and OnlMonDBodbc::Info().
ODBCXX_STRING odbc::DatabaseMetaData::getTableTerm ()
Returns the term for table used by the data source.
Referenced by ODBCDatabaseMetaData::GetTableTerm(), and OnlMonDBodbc::Info().
ResultSet* odbc::DatabaseMetaData::getTableTypes ()
Fetches the table types the database supports.
The returned ResultSet is the same as with getTables(), except that all columns but TABLE_TYPE contain NULL values.
Referenced by ODBCDatabaseMetaData::GetTableTypes(), and OnlMonDBodbc::Info().
ODBCXX_STRING odbc::DatabaseMetaData::getTimeDateFunctions ()
Returns a comma-separated list of all time and date functions supported.
Referenced by ODBCDatabaseMetaData::GetTimeDateFunctions().
ResultSet* odbc::DatabaseMetaData::getTypeInfo ()
Fetches a list of data types supported by this data source.
The returned ResultSet is ordered by DATA_TYPE and then by how closely the type maps to the corresponding ODBC SQL type. It contains the following columns:
TYPE_NAME - string - native type name
DATA_TYPE - short - SQL data type from Types
COLUMN_SIZE - int - maximum precision
LITERAL_PREFIX - string - prefix used to quote a literal. Can be NULL.
LITERAL_SUFFIX - string - suffix used to quote a literal. Can be NULL.
CREATE_PARAMS - string - comma separated possible list of parameters to creating a column of this type
NULLABLE - short - whether this type can contain NULLs:
typeNoNulls - no
typeNullable - yes, can be nullable
typeNullableUnknown - nobody knows
CASE_SENSITIVE - bool - whether this type is case sensitive
SEARCHABLE - bool - whether this type can be searched, eg used in WHERE-clauses:
typePredNone - no
typePredChar - yes, but only with a LIKE predicate
typePredBasic - yes, except in a LIKE predicate
typeSearchable - yes
UNSIGNED_ATTRIBUTE - bool - true if this type is unsigned
FIXED_PREC_SCALE - bool - whether this type has predefined fixed precision and scale (eg is useful for money)
AUTO_UNIQUE_VALUE - bool - whether this type can be used for an autoincrementing value. NULL if not applicable.
LOCAL_TYPE_NAME - string - localized native type name. Can be NULL.
MINIMUM_SCALE - short - minimum supported scale, if applicable
MAXIMUM_SCALE - short - maximum supported scale, if applicable
SQL_DATA_TYPE - short - unused
SQL_DATETIME_SUB - short - unused
NUM_PREC_RADIX - int - radix, if applicable
Referenced by ODBCDatabaseMetaData::GetTypeInfo().
ODBCXX_STRING odbc::DatabaseMetaData::getUserName ()
Returns the user name of the connection.
Referenced by ODBCDatabaseMetaData::GetUserName(), and OnlMonDBodbc::Info().
ResultSet* odbc::DatabaseMetaData::getVersionColumns (const ODBCXX_STRING & catalog, const ODBCXX_STRING & schema, const ODBCXX_STRING & table)
Returns a list of columns for a table that are automatically updated when anything in a row is updated.
The returned ResultSet has the following unordered columns:
SCOPE - short - unused
COLUMN_NAME - string - the column name
DATA_TYPE - short - the type of the column from Types
TYPE_NAME - string - native type name (data source dependent)
COLUMN_SIZE - int - the size (precision) of the column.
BUFFER_LENGTH - int - unused
DECIMAL_DIGITS - short - scale if applicable. Can be NULL.
PSEUDO_COLUMN - short - whether this is a pseudo column:
versionColumnUnknown - it is unknown whether this is a pseudo column
versionColumnNotPseudo - it is definitely not a pseudo column
versionColumnPseudo - it is definitely a pseudo column
Referenced by ODBCDatabaseMetaData::GetVersionColumns().
bool odbc::DatabaseMetaData::insertsAreDetected (int type)
Returns true if an inserted row can be detected with ResultSet::rowInserted().
Parameters
type The type of ResultSet of interest
Referenced by ODBCDatabaseMetaData::InsertsAreDetected().
bool odbc::DatabaseMetaData::isCatalogAtStart ()
Returns true if the catalog is positioned at the beginning of a fully qualified identifier.
For example mysql would say true, while oracle would say false.
Referenced by ODBCDatabaseMetaData::IsCatalogAtStart().
bool odbc::DatabaseMetaData::isReadOnly ()
Returns true if the data source or the current connection is in read-only mode.
Referenced by ODBCDatabaseMetaData::IsReadOnly().
bool odbc::DatabaseMetaData::nullPlusNonNullIsNull ()
Returns true if NULL plus a non-NULL value yields NULL.
Referenced by ODBCDatabaseMetaData::NullPlusNonNullIsNull().
bool odbc::DatabaseMetaData::nullsAreSortedAtEnd ()
Returns true if NULL values are sorted last, regardless of the sort order.
Referenced by ODBCDatabaseMetaData::NullsAreSortedAtEnd().
bool odbc::DatabaseMetaData::nullsAreSortedAtStart ()
Returns true if NULL values are sorted first, regardless of the sort order.
Referenced by ODBCDatabaseMetaData::NullsAreSortedAtStart().
bool odbc::DatabaseMetaData::nullsAreSortedHigh ()
Returns true if NULL values are sorted high.
Referenced by ODBCDatabaseMetaData::NullsAreSortedHigh().
bool odbc::DatabaseMetaData::nullsAreSortedLow ()
Returns true if NULL values are sorted low.
Referenced by ODBCDatabaseMetaData::NullsAreSortedLow().
bool odbc::DatabaseMetaData::othersDeletesAreVisible (int type)
Returns true if rows deleted by others disapear from a ResultSet.
Parameters
type The type of ResultSet of interest
Referenced by ODBCDatabaseMetaData::OthersDeletesAreVisible().
bool odbc::DatabaseMetaData::othersInsertsAreVisible (int type)
Returns true if rows inserted by others become available in a ResultSet.
Parameters
type The type of ResultSet of interest
Referenced by ODBCDatabaseMetaData::OthersInsertsAreVisible().
bool odbc::DatabaseMetaData::othersUpdatesAreVisible (int type)
Returns true if rows updated by others are visible with their new values.
Parameters
type The type of ResultSet of interest
Referenced by ODBCDatabaseMetaData::OthersUpdatesAreVisible().
bool odbc::DatabaseMetaData::ownDeletesAreVisible (int type)
Returns true if deleted rows dissapear from a ResultSet
Parameters
type The type of ResultSet of interest
Referenced by ODBCDatabaseMetaData::OwnDeletesAreVisible().
bool odbc::DatabaseMetaData::ownInsertsAreVisible (int type)
Returns true if inserted rows become available in a ResultSet
Parameters
type The type of ResultSet of interest
Referenced by ODBCDatabaseMetaData::OwnInsertsAreVisible().
bool odbc::DatabaseMetaData::ownUpdatesAreVisible (int type)
Returns true if updated rows are available with their new values in the ResultSet.
Parameters
type The type of ResultSet of interest
Referenced by ODBCDatabaseMetaData::OwnUpdatesAreVisible().
bool odbc::DatabaseMetaData::storesLowerCaseIdentifiers ()
Returns true if the data source treats identifiers as case insensitive and stores them in lower case.
Referenced by ODBCDatabaseMetaData::StoresLowerCaseIdentifiers().
bool odbc::DatabaseMetaData::storesLowerCaseQuotedIdentifiers ()
Returns true if the data source treats quoted identifiers as case insensitive and stores them in lower case.
Referenced by ODBCDatabaseMetaData::StoresLowerCaseQuotedIdentifiers().
bool odbc::DatabaseMetaData::storesMixedCaseIdentifiers ()
Returns true if the data source treats identifiers as case insensitive and stores them in mixed case.
Referenced by ODBCDatabaseMetaData::StoresMixedCaseIdentifiers().
bool odbc::DatabaseMetaData::storesMixedCaseQuotedIdentifiers ()
Returns true if the data source treats quoted identifiers as case insensitive and stores them in mixed case.
Referenced by ODBCDatabaseMetaData::StoresMixedCaseQuotedIdentifiers().
bool odbc::DatabaseMetaData::storesUpperCaseIdentifiers ()
Returns true if the data source treats identifiers as case insensitive and stores them in upper case.
Referenced by ODBCDatabaseMetaData::StoresUpperCaseIdentifiers().
bool odbc::DatabaseMetaData::storesUpperCaseQuotedIdentifiers ()
Returns true if the data source treats quoted identifiers as case insensitive and stores them in upper case.
Referenced by ODBCDatabaseMetaData::StoresUpperCaseQuotedIdentifiers().
bool odbc::DatabaseMetaData::supportsAlterTableWithAddColumn ()
Returns true if ALTER TABLE with add column is supported.
Referenced by ODBCDatabaseMetaData::SupportsAlterTableWithAddColumn().
bool odbc::DatabaseMetaData::supportsAlterTableWithDropColumn ()
Returns true if ALTER TABLE with drop column is supported.
Referenced by ODBCDatabaseMetaData::SupportsAlterTableWithDropColumn().
bool odbc::DatabaseMetaData::supportsANSI92EntryLevelSQL ()
Returns true if the data source supports the ANSI92 entry level SQL grammar.
Referenced by ODBCDatabaseMetaData::SupportsANSI92EntryLevelSQL().
bool odbc::DatabaseMetaData::supportsANSI92FullSQL ()
Returns true if the data source supports the full ANSI92 SQL grammar.
bool odbc::DatabaseMetaData::supportsANSI92IntermediateSQL ()
Returns true if the data source supports the ANSI92 intermediate level SQL grammar.
Referenced by ODBCDatabaseMetaData::SupportsANSI92IntermediateSQL().
bool odbc::DatabaseMetaData::supportsBatchUpdates ()
Whether the data source supports batch updates
Referenced by ODBCDatabaseMetaData::SupportsBatchUpdates().
bool odbc::DatabaseMetaData::supportsCatalogsInDataManipulation ()
Returns true if catalogs are supported in DML
Referenced by ODBCDatabaseMetaData::SupportsCatalogsInDataManipulation().
bool odbc::DatabaseMetaData::supportsCatalogsInIndexDefinitions ()
Returns true if catalogs are supported in index definitions
Referenced by ODBCDatabaseMetaData::SupportsCatalogsInIndexDefinitions().
bool odbc::DatabaseMetaData::supportsCatalogsInPrivilegeDefinitions ()
Returns true if catalogs are supported in privilege definition statements
Referenced by ODBCDatabaseMetaData::SupportsCatalogsInPrivilegeDefinitions().
bool odbc::DatabaseMetaData::supportsCatalogsInProcedureCalls ()
Returns true if catalogs are supported in procedure call statements
Referenced by ODBCDatabaseMetaData::SupportsCatalogsInProcedureCalls().
bool odbc::DatabaseMetaData::supportsCatalogsInTableDefinitions ()
Returns true if catalogs are supported in CREATE/ALTER TABLE statements
Referenced by ODBCDatabaseMetaData::SupportsCatalogsInTableDefinitions().
bool odbc::DatabaseMetaData::supportsColumnAliasing ()
Returns true if the data source supports column aliasing, for example SELECT COLUMN1 [AS] C1 FROM TABLE
Referenced by ODBCDatabaseMetaData::SupportsColumnAliasing().
bool odbc::DatabaseMetaData::supportsConvert ()
Returns true if the CONVERT function is supported by the data source.
Referenced by ODBCDatabaseMetaData::SupportsConvert().
bool odbc::DatabaseMetaData::supportsConvert (int fromType, int toType)
Returns true if CONVERT between fromType and toType is supported.
bool odbc::DatabaseMetaData::supportsCoreSQLGrammar ()
Returns true if the data source supports the core ODBC SQL grammar.
Referenced by ODBCDatabaseMetaData::SupportsCoreSQLGrammar().
bool odbc::DatabaseMetaData::supportsCorrelatedSubqueries ()
Returns true if the data source supports correlated subqueries
Referenced by ODBCDatabaseMetaData::SupportsCorrelatedSubqueries().
bool odbc::DatabaseMetaData::supportsDataDefinitionAndDataManipulationTransactions ()
Checks if the data source supports both DML and DDL in transactions
Returns
true if the data source supports both data manipulation (eg. UPDATE, INSERT) and data definition (eg. CREATE TABLE) within a transaction.
If this method returns true, supportsDataManipulationTransactionsOnly(), dataDefinitionCausesTransactionCommit() and dataDefinitionIgnoredInTransactions() all return false.
Referenced by ODBCDatabaseMetaData::SupportsDataDefinitionAndDataManipulationTransactions().
bool odbc::DatabaseMetaData::supportsDataManipulationTransactionsOnly ()
Checks if the data source only supports DML in transactions
Returns
true if the data source only supports data manipulation (eg. UPDATE, INSERT) within a transaction.
Attempts to use data definition (eg. CREATE TABLE) in a transaction will trigger an error.
If this method returns true, supportsDataDefinitionAndDataManipulationTransactions(), dataDefinitionCausesTransactionCommit() and dataDefinitionIgnoredInTransactions() all return false.
Referenced by ODBCDatabaseMetaData::SupportsDataManipulationTransactionsOnly().
bool odbc::DatabaseMetaData::supportsDifferentTableCorrelationNames ()
Referenced by ODBCDatabaseMetaData::SupportsDifferentTableCorrelationNames().
bool odbc::DatabaseMetaData::supportsExpressionsInOrderBy ()
Referenced by ODBCDatabaseMetaData::SupportsExpressionsInOrderBy().
bool odbc::DatabaseMetaData::supportsExtendedSQLGrammar ()
Returns true if the data source supports the ODBC extended SQL grammar.
Referenced by ODBCDatabaseMetaData::SupportsExtendedSQLGrammar().
bool odbc::DatabaseMetaData::supportsFullOuterJoins ()
Returns true if the data source fully supports outer joins.
Referenced by ODBCDatabaseMetaData::SupportsFullOuterJoins().
bool odbc::DatabaseMetaData::supportsGroupBy ()
Returns true if the data source supports the GROUP BY clause.
Referenced by ODBCDatabaseMetaData::SupportsGroupBy().
bool odbc::DatabaseMetaData::supportsGroupByBeyondSelect ()
Returns true if the columns in a GROUP BY don't have to be selected.
Referenced by ODBCDatabaseMetaData::SupportsGroupByBeyondSelect().
bool odbc::DatabaseMetaData::supportsGroupByUnrelated ()
Returns true if the columns in a GROUP BY clause are independent of the selected ones.
Referenced by ODBCDatabaseMetaData::SupportsGroupByUnrelated().
bool odbc::DatabaseMetaData::supportsIntegrityEnhancementFacility ()
Returns true if the data source supports the SQL Integrity Enhancement Facility.
Referenced by ODBCDatabaseMetaData::SupportsIntegrityEnhancementFacility().
bool odbc::DatabaseMetaData::supportsLikeEscapeClause ()
Returns true if the escape character is supported in LIKE clauses.
Referenced by ODBCDatabaseMetaData::SupportsLikeEscapeClause().
bool odbc::DatabaseMetaData::supportsLimitedOuterJoins ()
Returns true if the data source only supports certain types of outer joins.
Referenced by ODBCDatabaseMetaData::SupportsLimitedOuterJoins().
bool odbc::DatabaseMetaData::supportsMinimumSQLGrammar ()
Returns true if the data source supports ODBC minimum SQL grammar.
Referenced by ODBCDatabaseMetaData::SupportsMinimumSQLGrammar().
bool odbc::DatabaseMetaData::supportsMixedCaseIdentifiers ()
Returns true if the data source supports case sensitive mixed case identifiers.
Referenced by ODBCDatabaseMetaData::SupportsMixedCaseIdentifiers().
bool odbc::DatabaseMetaData::supportsMixedCaseQuotedIdentifiers ()
Returns true if the data source supports case sensitive mixed case quoted identifiers.
Referenced by ODBCDatabaseMetaData::SupportsMixedCaseQuotedIdentifiers().
bool odbc::DatabaseMetaData::supportsMultipleResultSets ()
Returns true if a query can return multiple ResultSets.
Referenced by ODBCDatabaseMetaData::SupportsMultipleResultSets().
bool odbc::DatabaseMetaData::supportsMultipleTransactions ()
Returns true if multiple transactions can be open at once on different connections.
Referenced by ODBCDatabaseMetaData::SupportsMultipleTransactions().
bool odbc::DatabaseMetaData::supportsNonNullableColumns ()
Returns true if columns can be defined as non-nullable.
Referenced by ODBCDatabaseMetaData::SupportsNonNullableColumns().
bool odbc::DatabaseMetaData::supportsOpenCursorsAcrossCommit ()
Returns true if the data source and the driver can handle open cursors (eg. ResultSets) across a commit, or false if they are invalidated.
Referenced by ODBCDatabaseMetaData::SupportsOpenCursorsAcrossCommit().
bool odbc::DatabaseMetaData::supportsOpenCursorsAcrossRollback ()
Returns true if the data source and the driver can handle open cursors (eg. ResultSets) across a rollback, or false if they are invalidated.
Referenced by ODBCDatabaseMetaData::SupportsOpenCursorsAcrossRollback().
bool odbc::DatabaseMetaData::supportsOpenStatementsAcrossCommit ()
Returns true if the data source and the driver can handle open statements across a commit, or false if they are invalidated.
Referenced by ODBCDatabaseMetaData::SupportsOpenStatementsAcrossCommit().
bool odbc::DatabaseMetaData::supportsOpenStatementsAcrossRollback ()
Returns true if the data source and the driver can handle open statements across a rollback, or false if they are invalidated.
Referenced by ODBCDatabaseMetaData::SupportsOpenStatementsAcrossRollback().
bool odbc::DatabaseMetaData::supportsOrderByUnrelated ()
Referenced by ODBCDatabaseMetaData::SupportsOrderByUnrelated().
bool odbc::DatabaseMetaData::supportsOuterJoins ()
Returns true if the data source supports some form of outer joins.
Referenced by ODBCDatabaseMetaData::SupportsOuterJoins().
bool odbc::DatabaseMetaData::supportsPositionedDelete ()
Checks if the data source supports positioned delete
Returns
true if ("DELETE WHERE CURRENT OF ...") is supported
Referenced by ODBCDatabaseMetaData::SupportsPositionedDelete().
bool odbc::DatabaseMetaData::supportsPositionedUpdate ()
Checks if the data source supports positioned update
Returns
true if ("UPDATE ... WHERE CURRENT OF ...") is supported
Referenced by ODBCDatabaseMetaData::SupportsPositionedUpdate().
bool odbc::DatabaseMetaData::supportsResultSetConcurrency (int type, int concurrency)
Returns true if the data source supports the given result set concurrency for the given result set type.
Parameters
type The type to check for.
concurrency The concurrency level to check for.
See Also
ResultSet
Referenced by ODBCDatabaseMetaData::SupportsResultSetConcurrency().
bool odbc::DatabaseMetaData::supportsResultSetType (int type)
Returns true if the data source supports the given result set type.
Parameters
type The type to check for
See Also
ResultSet
Referenced by ODBCDatabaseMetaData::SupportsResultSetType().
bool odbc::DatabaseMetaData::supportsSchemasInDataManipulation ()
Returns true if schemas are supported in DML
Referenced by ODBCDatabaseMetaData::SupportsSchemasInDataManipulation().
bool odbc::DatabaseMetaData::supportsSchemasInIndexDefinitions ()
Returns true if schemas are supported in index definitions
Referenced by ODBCDatabaseMetaData::SupportsSchemasInIndexDefinitions().
bool odbc::DatabaseMetaData::supportsSchemasInPrivilegeDefinitions ()
Returns true if schemas are supported in privilege definition statements
Referenced by ODBCDatabaseMetaData::SupportsSchemasInPrivilegeDefinitions().
bool odbc::DatabaseMetaData::supportsSchemasInProcedureCalls ()
Returns true if schemas are supported in procedure call statements
Referenced by ODBCDatabaseMetaData::SupportsSchemasInProcedureCalls().
bool odbc::DatabaseMetaData::supportsSchemasInTableDefinitions ()
Returns true if schemas are supported in CREATE/ALTER TABLE statements
Referenced by ODBCDatabaseMetaData::SupportsSchemasInTableDefinitions().
bool odbc::DatabaseMetaData::supportsSelectForUpdate ()
Checks if the data source supports
Returns
true if ("SELECT ... FOR UPDATE") is supported
bool odbc::DatabaseMetaData::supportsStoredProcedures ()
Returns true if the data source supports some form of stored procedures.
Referenced by ODBCDatabaseMetaData::SupportsSelectForUpdate(), and ODBCDatabaseMetaData::SupportsStoredProcedures().
bool odbc::DatabaseMetaData::supportsSubqueriesInComparisons ()
Returns true if the data source supports subqueries in comparisons
Referenced by ODBCDatabaseMetaData::SupportsSubqueriesInComparisons().
bool odbc::DatabaseMetaData::supportsSubqueriesInExists ()
Returns true if the data source supports subqueries in "EXISTS" expressions.
Referenced by ODBCDatabaseMetaData::SupportsSubqueriesInExists().
bool odbc::DatabaseMetaData::supportsSubqueriesInIns ()
Returns true if the data source supports subqueries in "IN" expressions.
Referenced by ODBCDatabaseMetaData::SupportsSubqueriesInIns().
bool odbc::DatabaseMetaData::supportsSubqueriesInQuantifieds ()
Returns true if the data source supports subqueries in quantified expressions.
Referenced by ODBCDatabaseMetaData::SupportsSubqueriesInQuantifieds().
bool odbc::DatabaseMetaData::supportsTableCorrelationNames ()
Referenced by ODBCDatabaseMetaData::SupportsTableCorrelationNames().
bool odbc::DatabaseMetaData::supportsTransactionIsolationLevel (int lev)
Returns true if the data source supports the specified transaction isolation level.
Parameters
lev The isolation level to check for
Referenced by ODBCDatabaseMetaData::SupportsTransactionIsolationLevel().
bool odbc::DatabaseMetaData::supportsTransactions ()
Returns true if the data source supports transactions.
Referenced by ODBCDatabaseMetaData::SupportsTransactions().
bool odbc::DatabaseMetaData::supportsUnion ()
Returns true if the data source supports UNION joins.
Referenced by ODBCDatabaseMetaData::SupportsUnion().
bool odbc::DatabaseMetaData::supportsUnionAll ()
Returns true if the data source supports UNION ALL joins.
Referenced by ODBCDatabaseMetaData::SupportsUnionAll().
bool odbc::DatabaseMetaData::updatesAreDetected (int type)
Returns true if ResultSet::rowUpdated can determine whether a row has been updated.
Parameters
type The type of ResultSet of interest
Referenced by ODBCDatabaseMetaData::UpdatesAreDetected().
bool odbc::DatabaseMetaData::usesLocalFilePerTable ()
Returns true if the data source uses a file for each table
Referenced by ODBCDatabaseMetaData::UsesLocalFilePerTable().
bool odbc::DatabaseMetaData::usesLocalFiles ()
Returns true if the data source uses local files
Referenced by ODBCDatabaseMetaData::UsesLocalFiles().
Friends And Related Function Documentation
friend class Connection friend
Definition at line 44 of file databasemetadata.h.
View newest version in sPHENIX GitHub at line 44 of file databasemetadata.h
friend class DriverInfo friend
Definition at line 45 of file databasemetadata.h.
View newest version in sPHENIX GitHub at line 45 of file databasemetadata.h
Member Data Documentation
Connection* odbc::DatabaseMetaData::connection_ private
Definition at line 48 of file databasemetadata.h.
View newest version in sPHENIX GitHub at line 48 of file databasemetadata.h
The documentation for this class was generated from the following file:
RDBC/blob/master/include/RDBC/odbc++/databasemetadata.h