Analysis Software: Jetv2 Class Reference
Jetv2 Class Reference
Jetv2.
#include <coresoftware/blob/master/offline/packages/jetbase/Jetv2.h>
Classes
struct CompareSRC
Public Member Functions
Jetv2 ()=default
Jetv2 (unsigned int)
void identify (std::ostream &os=std::cout) const override
void Reset () override
Clear Event.
int isValid () const override
isValid returns non zero if object contains vailid data
PHObject * CloneMe () const override
Virtual copy constructor.
unsigned int get_id () const override
void set_id (unsigned int id) override
float get_px () const override
void set_px (float px) override
float get_py () const override
void set_py (float py) override
float get_pz () const override
void set_pz (float pz) override
float get_e () const override
void set_e (float e) override
float get_p () const override
float get_pt () const override
float get_et () const override
float get_eta () const override
float get_phi () const override
float get_mass () const override
float get_mass2 () const override
void resize_properties (size_t size) override
std::vector< float > & get_property_vec () override
size_t size_properties () const override
float get_property (Jet::PROPERTY index) const override
void set_property (Jet::PROPERTY index, float value) override
size_t size_comp () const override
void clear_comp () override
void insert_comp (SRC iSRC, unsigned int compid) override
void insert_comp (Jet::SRC, unsigned int compid, bool) override
void insert_comp (TYPE_comp_vec &) override
void insert_comp (TYPE_comp_vec &, bool) override
void set_comp_sort_flag (bool f=false) override
void print_comp (std::ostream &os=std::cout, bool single_line=false) override
size_t num_comp (SRC iSRC=Jet::SRC::VOID) override
std::vector< Jet::SRC > comp_src_vec () override
std::map< Jet::SRC, size_t > comp_src_sizemap () override
ITER_comp_vec comp_begin () override
ITER_comp_vec comp_begin (Jet::SRC) override
ITER_comp_vec comp_end () override
ITER_comp_vec comp_end (Jet::SRC) override
TYPE_comp_vec & get_comp_vec () override
void Clear (Option_t *=nullptr) override
Public Member Functions inherited from Jet
Jet ()
~Jet () override
ClassDefOverride (Jet, 1)
Public Member Functions inherited from PHObject
PHObject ()
ctor
~PHObject () override
dtor
virtual PHObject * clone () const final
PHObject * Clone (const char *newname="") const final
void Copy (TObject &object) const final
virtual int Integrate () const
virtual int Integrate (PHObject *)
virtual void CopyFrom (const PHObject *obj)
Private Member Functions
void ensure_sorted ()
bool empty_comp () const override
size_t count_comp (SRC source) const override
void msg_dep_fn (const std::string &method_name) const
bool has_property (Jet::PROPERTY) const override
void print_property (std::ostream &) const override
ConstIter begin_comp () const override
ConstIter lower_bound_comp (SRC source) const override
ConstIter upper_bound_comp (SRC source) const override
ConstIter find (Jet::SRC source) const override
ConstIter end_comp () const override
Iter begin_comp () override
Iter lower_bound_comp (SRC source) override
Iter upper_bound_comp (SRC source) override
Iter find (SRC source) override
Iter end_comp () override
size_t erase_comp (Jet::SRC) override
void erase_comp (Iter) override
void erase_comp (Iter, Iter) override
ClassDefOverride (Jetv2, 1)
Private Attributes
unsigned int _id = ~0x0
unique identifier within container
bool _is_sorted { false }
std::array< float, 3 > _mom {{ NAN, NAN, NAN}}
jet momentum vector (px,py,pz)
float _e = NAN
jet energy
std::vector< std::pair
< Jet::SRC, unsigned int > > _comp_ids
source id -> component id
std::vector< float > _properties {}
Additional Inherited Members
Public Types inherited from Jet
enum ALGO { NONE = 0, ANTIKT = 1, KT = 2, CAMBRIDGE = 3 }
enum SRC {
VOID = 0, PARTICLE = 1, TRACK = 2, CEMC_TOWER = 3,
CEMC_CLUSTER = 4, HCALIN_TOWER = 5, HCALIN_CLUSTER = 6, HCALOUT_TOWER = 7,
HCALOUT_CLUSTER = 8, FEMC_TOWER = 9, FEMC_CLUSTER = 10, FHCAL_TOWER = 11,
FHCAL_CLUSTER = 12, CEMC_TOWER_RETOWER = 13, CEMC_TOWER_SUB1 = 14, HCALIN_TOWER_SUB1 = 15,
HCALOUT_TOWER_SUB1 = 16, CEMC_TOWER_SUB1CS = 17, HCALIN_TOWER_SUB1CS = 18, HCALOUT_TOWER_SUB1CS = 19,
HEPMC_IMPORT = 20, HCAL_TOPO_CLUSTER = 21, ECAL_TOPO_CLUSTER = 22, EEMC_TOWER = 23,
EEMC_CLUSTER = 24, CEMC_TOWERINFO = 25, HCALIN_TOWERINFO = 26, HCALOUT_TOWERINFO = 27,
CEMC_TOWERINFO_RETOWER = 28, CEMC_TOWERINFO_SUB1 = 29, HCALIN_TOWERINFO_SUB1 = 30, HCALOUT_TOWERINFO_SUB1 = 31,
CEMC_TOWERINFO_EMBED = 32, CEMC_TOWERINFO_SIM = 33, HCALIN_TOWERINFO_EMBED = 34, HCALIN_TOWERINFO_SIM = 35,
HCALOUT_TOWERINFO_EMBED = 36, HCALOUT_TOWERINFO_SIM = 37, JET_PROBE = 38
}
enum PROPERTY {
prop_JetCharge = 1, prop_BFrac = 2, prop_SeedD = 3, prop_SeedItr = 4,
prop_zg = 5, prop_Rg = 6, prop_mu = 7, prop_gamma = 8,
prop_JetHadronFlavor = 9, prop_JetHadronZT = 10, prop_area = 11, no_property = 12
}
typedef std::pair< Jet::SRC,
unsigned int > TYPE_comp
typedef std::vector< TYPE_comp > TYPE_comp_vec
typedef TYPE_comp_vec::iterator ITER_comp_vec
typedef std::multimap
< Jet::SRC, unsigned int > typ_comp_ids
typedef
typ_comp_ids::const_iterator ConstIter
typedef typ_comp_ids::iterator Iter
Detailed Description
Jetv2.
Definition at line 26 of file Jetv2.h.
View newest version in sPHENIX GitHub at line 26 of file Jetv2.h
Constructor & Destructor Documentation
Jetv2::Jetv2 () default
Referenced by CloneMe().
Jetv2::Jetv2 (unsigned int n_prop)
Definition at line 18 of file Jetv2.cc.
View newest version in sPHENIX GitHub at line 18 of file Jetv2.cc
Member Function Documentation
Jet::ConstIter Jetv2::begin_comp () const override private virtual
Reimplemented from Jet.
Definition at line 228 of file Jetv2.cc.
View newest version in sPHENIX GitHub at line 228 of file Jetv2.cc
References Jet::begin_comp(), and msg_dep_fn().
Jet::Iter Jetv2::begin_comp () override private virtual
Reimplemented from Jet.
Definition at line 253 of file Jetv2.cc.
View newest version in sPHENIX GitHub at line 253 of file Jetv2.cc
References Jet::begin_comp(), and msg_dep_fn().
Jetv2::ClassDefOverride (Jetv2 , 1) private
void Jetv2::Clear (Option_t * = nullptr) inline override
Definition at line 116 of file Jetv2.h.
View newest version in sPHENIX GitHub at line 116 of file Jetv2.h
References Reset().
void Jetv2::clear_comp () inline override virtual
Reimplemented from Jet.
Definition at line 97 of file Jetv2.h.
View newest version in sPHENIX GitHub at line 97 of file Jetv2.h
References _comp_ids.
PHObject * Jetv2::CloneMe () const override virtual
Virtual copy constructor.
Reimplemented from Jet.
Definition at line 103 of file Jetv2.cc.
View newest version in sPHENIX GitHub at line 103 of file Jetv2.cc
References Jetv2().
ITER_comp_vec Jetv2::comp_begin () inline override virtual
Reimplemented from Jet.
Definition at line 110 of file Jetv2.h.
View newest version in sPHENIX GitHub at line 110 of file Jetv2.h
References _comp_ids.
Referenced by comp_src_sizemap(), comp_src_vec(), num_comp(), and print_comp().
Jetv2::ITER_comp_vec Jetv2::comp_begin (Jet::SRC iSRC) override virtual
Reimplemented from Jet.
Definition at line 184 of file Jetv2.cc.
View newest version in sPHENIX GitHub at line 184 of file Jetv2.cc
References _comp_ids, and ensure_sorted().
ITER_comp_vec Jetv2::comp_end () inline override virtual
Reimplemented from Jet.
Definition at line 112 of file Jetv2.h.
View newest version in sPHENIX GitHub at line 112 of file Jetv2.h
References _comp_ids.
Referenced by comp_src_sizemap(), comp_src_vec(), num_comp(), and print_comp().
Jetv2::ITER_comp_vec Jetv2::comp_end (Jet::SRC iSRC) override virtual
Reimplemented from Jet.
Definition at line 190 of file Jetv2.cc.
View newest version in sPHENIX GitHub at line 190 of file Jetv2.cc
References _comp_ids, and ensure_sorted().
std::map< Jet::SRC, size_t > Jetv2::comp_src_sizemap () override virtual
Reimplemented from Jet.
Definition at line 66 of file Jetv2.cc.
View newest version in sPHENIX GitHub at line 66 of file Jetv2.cc
References comp_begin(), and comp_end().
std::vector< Jet::SRC > Jetv2::comp_src_vec () override virtual
Reimplemented from Jet.
Definition at line 51 of file Jetv2.cc.
View newest version in sPHENIX GitHub at line 51 of file Jetv2.cc
References comp_begin(), comp_end(), and vec.
size_t Jetv2::count_comp (Jet::SRC source) const override private virtual
Reimplemented from Jet.
Definition at line 223 of file Jetv2.cc.
View newest version in sPHENIX GitHub at line 223 of file Jetv2.cc
References msg_dep_fn().
bool Jetv2::empty_comp () const override private virtual
Reimplemented from Jet.
Definition at line 218 of file Jetv2.cc.
View newest version in sPHENIX GitHub at line 218 of file Jetv2.cc
References msg_dep_fn().
Jet::ConstIter Jetv2::end_comp () const override private virtual
Reimplemented from Jet.
Definition at line 248 of file Jetv2.cc.
View newest version in sPHENIX GitHub at line 248 of file Jetv2.cc
References Jet::end_comp(), and msg_dep_fn().
Jet::Iter Jetv2::end_comp () override private virtual
Reimplemented from Jet.
Definition at line 273 of file Jetv2.cc.
View newest version in sPHENIX GitHub at line 273 of file Jetv2.cc
References Jet::end_comp(), and msg_dep_fn().
void Jetv2::ensure_sorted () private
Definition at line 176 of file Jetv2.cc.
View newest version in sPHENIX GitHub at line 176 of file Jetv2.cc
References _comp_ids, _is_sorted, and Acts::Experimental::detail::BlueprintHelper::sort().
Referenced by comp_begin(), and comp_end().
size_t Jetv2::erase_comp (Jet::SRC) override private virtual
Reimplemented from Jet.
Definition at line 278 of file Jetv2.cc.
View newest version in sPHENIX GitHub at line 278 of file Jetv2.cc
References msg_dep_fn().
void Jetv2::erase_comp (Jet::Iter) override private virtual
Reimplemented from Jet.
Definition at line 282 of file Jetv2.cc.
View newest version in sPHENIX GitHub at line 282 of file Jetv2.cc
References msg_dep_fn().
void Jetv2::erase_comp (Jet::Iter , Jet::Iter) override private virtual
Reimplemented from Jet.
Definition at line 286 of file Jetv2.cc.
View newest version in sPHENIX GitHub at line 286 of file Jetv2.cc
References msg_dep_fn().
Jet::ConstIter Jetv2::find (Jet::SRC source) const override private virtual
Reimplemented from Jet.
Definition at line 243 of file Jetv2.cc.
View newest version in sPHENIX GitHub at line 243 of file Jetv2.cc
References Jet::find(), and msg_dep_fn().
Jet::Iter Jetv2::find (Jet::SRC source) override private virtual
Reimplemented from Jet.
Definition at line 268 of file Jetv2.cc.
View newest version in sPHENIX GitHub at line 268 of file Jetv2.cc
References Jet::find(), and msg_dep_fn().
TYPE_comp_vec& Jetv2::get_comp_vec () inline override virtual
Reimplemented from Jet.
Definition at line 114 of file Jetv2.h.
View newest version in sPHENIX GitHub at line 114 of file Jetv2.h
References _comp_ids.
float Jetv2::get_e () const inline override virtual
Reimplemented from Jet.
Definition at line 75 of file Jetv2.h.
View newest version in sPHENIX GitHub at line 75 of file Jetv2.h
References _e.
Referenced by get_et(), get_mass2(), and identify().
float Jetv2::get_et () const override virtual
Reimplemented from Jet.
Definition at line 119 of file Jetv2.cc.
View newest version in sPHENIX GitHub at line 119 of file Jetv2.cc
References get_e(), get_p(), and get_pt().
float Jetv2::get_eta () const override virtual
Reimplemented from Jet.
Definition at line 124 of file Jetv2.cc.
View newest version in sPHENIX GitHub at line 124 of file Jetv2.cc
References get_pt(), and get_pz().
unsigned int Jetv2::get_id () const inline override virtual
Reimplemented from Jet.
Definition at line 63 of file Jetv2.h.
View newest version in sPHENIX GitHub at line 63 of file Jetv2.h
References _id.
Referenced by identify().
float Jetv2::get_mass () const override virtual
Reimplemented from Jet.
Definition at line 134 of file Jetv2.cc.
View newest version in sPHENIX GitHub at line 134 of file Jetv2.cc
References get_mass2().
float Jetv2::get_mass2 () const override virtual
Reimplemented from Jet.
Definition at line 145 of file Jetv2.cc.
View newest version in sPHENIX GitHub at line 145 of file Jetv2.cc
References get_e(), get_px(), get_py(), and get_pz().
Referenced by get_mass().
float Jetv2::get_p () const override virtual
Reimplemented from Jet.
Definition at line 109 of file Jetv2.cc.
View newest version in sPHENIX GitHub at line 109 of file Jetv2.cc
References get_px(), get_py(), and get_pz().
Referenced by get_et().
float Jetv2::get_phi () const override virtual
Reimplemented from Jet.
Definition at line 129 of file Jetv2.cc.
View newest version in sPHENIX GitHub at line 129 of file Jetv2.cc
References get_px(), and get_py().
float Jetv2::get_property (Jet::PROPERTY index) const inline override virtual
Reimplemented from Jet.
Definition at line 91 of file Jetv2.h.
View newest version in sPHENIX GitHub at line 91 of file Jetv2.h
References _properties, and index.
std::vector<float>& Jetv2::get_property_vec () inline override virtual
Reimplemented from Jet.
Definition at line 88 of file Jetv2.h.
View newest version in sPHENIX GitHub at line 88 of file Jetv2.h
References _properties.
float Jetv2::get_pt () const override virtual
Reimplemented from Jet.
Definition at line 114 of file Jetv2.cc.
View newest version in sPHENIX GitHub at line 114 of file Jetv2.cc
References get_px(), and get_py().
Referenced by get_et(), and get_eta().
float Jetv2::get_px () const inline override virtual
Reimplemented from Jet.
Definition at line 66 of file Jetv2.h.
View newest version in sPHENIX GitHub at line 66 of file Jetv2.h
References _mom.
Referenced by get_mass2(), get_p(), get_phi(), get_pt(), and identify().
float Jetv2::get_py () const inline override virtual
Reimplemented from Jet.
Definition at line 69 of file Jetv2.h.
View newest version in sPHENIX GitHub at line 69 of file Jetv2.h
References _mom.
Referenced by get_mass2(), get_p(), get_phi(), get_pt(), and identify().
float Jetv2::get_pz () const inline override virtual
Reimplemented from Jet.
Definition at line 72 of file Jetv2.h.
View newest version in sPHENIX GitHub at line 72 of file Jetv2.h
References _mom.
Referenced by get_eta(), get_mass2(), get_p(), and identify().
bool Jetv2::has_property (Jet::PROPERTY) const override private virtual
Reimplemented from Jet.
Definition at line 200 of file Jetv2.cc.
View newest version in sPHENIX GitHub at line 200 of file Jetv2.cc
References msg_dep_fn().
void Jetv2::identify (std::ostream & os = std::cout) const override virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from Jet.
Definition at line 22 of file Jetv2.cc.
View newest version in sPHENIX GitHub at line 22 of file Jetv2.cc
References _comp_ids, _properties, get_e(), get_id(), get_px(), get_py(), and get_pz().
void Jetv2::insert_comp (SRC iSRC, unsigned int compid) override virtual
Reimplemented from Jet.
Definition at line 157 of file Jetv2.cc.
View newest version in sPHENIX GitHub at line 157 of file Jetv2.cc
References _comp_ids, and _is_sorted.
Referenced by JetProbeMaker::process_event().
void Jetv2::insert_comp (Jet::SRC iSRC, unsigned int compid, bool) override virtual
Reimplemented from Jet.
Definition at line 162 of file Jetv2.cc.
View newest version in sPHENIX GitHub at line 162 of file Jetv2.cc
References _comp_ids.
void Jetv2::insert_comp (Jet::TYPE_comp_vec & added) override virtual
Reimplemented from Jet.
Definition at line 166 of file Jetv2.cc.
View newest version in sPHENIX GitHub at line 166 of file Jetv2.cc
References _comp_ids, and _is_sorted.
void Jetv2::insert_comp (Jet::TYPE_comp_vec & added, bool) override virtual
Reimplemented from Jet.
Definition at line 171 of file Jetv2.cc.
View newest version in sPHENIX GitHub at line 171 of file Jetv2.cc
References _comp_ids.
int Jetv2::isValid () const override virtual
isValid returns non zero if object contains vailid data
Reimplemented from Jet.
Definition at line 91 of file Jetv2.cc.
View newest version in sPHENIX GitHub at line 91 of file Jetv2.cc
References _comp_ids, _e, _id, _mom, and i.
Jet::ConstIter Jetv2::lower_bound_comp (Jet::SRC source) const override private virtual
Reimplemented from Jet.
Definition at line 233 of file Jetv2.cc.
View newest version in sPHENIX GitHub at line 233 of file Jetv2.cc
References Jet::lower_bound_comp(), and msg_dep_fn().
Jet::Iter Jetv2::lower_bound_comp (Jet::SRC source) override private virtual
Reimplemented from Jet.
Definition at line 258 of file Jetv2.cc.
View newest version in sPHENIX GitHub at line 258 of file Jetv2.cc
References Jet::lower_bound_comp(), and msg_dep_fn().
void Jetv2::msg_dep_fn (const std::string & method_name) const private
Definition at line 196 of file Jetv2.cc.
View newest version in sPHENIX GitHub at line 196 of file Jetv2.cc
Referenced by begin_comp(), count_comp(), empty_comp(), end_comp(), erase_comp(), find(), has_property(), lower_bound_comp(), print_property(), and upper_bound_comp().
size_t Jetv2::num_comp (Jet::SRC iSRC = Jet::SRC::VOID) override virtual
Reimplemented from Jet.
Definition at line 151 of file Jetv2.cc.
View newest version in sPHENIX GitHub at line 151 of file Jetv2.cc
References comp_begin(), and comp_end().
void Jetv2::print_comp (std::ostream & os = std::cout, bool single_line = false) override virtual
Reimplemented from Jet.
Definition at line 41 of file Jetv2.cc.
View newest version in sPHENIX GitHub at line 41 of file Jetv2.cc
References comp_begin(), and comp_end().
void Jetv2::print_property (std::ostream &) const override private virtual
Reimplemented from Jet.
Definition at line 214 of file Jetv2.cc.
View newest version in sPHENIX GitHub at line 214 of file Jetv2.cc
References msg_dep_fn().
void Jetv2::Reset () override virtual
Clear Event.
Reimplemented from PHObject.
Definition at line 82 of file Jetv2.cc.
View newest version in sPHENIX GitHub at line 82 of file Jetv2.cc
References _comp_ids, _e, _id, _mom, _properties, parse_cmake_options::begin, and end.
Referenced by Clear().
void Jetv2::resize_properties (size_t size) inline override virtual
Reimplemented from Jet.
Definition at line 87 of file Jetv2.h.
View newest version in sPHENIX GitHub at line 87 of file Jetv2.h
References _properties.
void Jetv2::set_comp_sort_flag (bool f = false) inline override virtual
Reimplemented from Jet.
Definition at line 102 of file Jetv2.h.
View newest version in sPHENIX GitHub at line 102 of file Jetv2.h
References _is_sorted, and f.
void Jetv2::set_e (float e) inline override virtual
Reimplemented from Jet.
Definition at line 76 of file Jetv2.h.
View newest version in sPHENIX GitHub at line 76 of file Jetv2.h
References _e, and Acts::UnitConstants::e.
Referenced by JetProbeMaker::process_event().
void Jetv2::set_id (unsigned int id) inline override virtual
Reimplemented from Jet.
Definition at line 64 of file Jetv2.h.
View newest version in sPHENIX GitHub at line 64 of file Jetv2.h
References _id, and train_ambiguity_solver::id.
void Jetv2::set_property (Jet::PROPERTY index, float value) inline override virtual
Reimplemented from Jet.
Definition at line 92 of file Jetv2.h.
View newest version in sPHENIX GitHub at line 92 of file Jetv2.h
References _properties, and index.
void Jetv2::set_px (float px) inline override virtual
Reimplemented from Jet.
Definition at line 67 of file Jetv2.h.
View newest version in sPHENIX GitHub at line 67 of file Jetv2.h
References _mom.
Referenced by JetProbeMaker::process_event().
void Jetv2::set_py (float py) inline override virtual
Reimplemented from Jet.
Definition at line 70 of file Jetv2.h.
View newest version in sPHENIX GitHub at line 70 of file Jetv2.h
References _mom.
Referenced by JetProbeMaker::process_event().
void Jetv2::set_pz (float pz) inline override virtual
Reimplemented from Jet.
Definition at line 73 of file Jetv2.h.
View newest version in sPHENIX GitHub at line 73 of file Jetv2.h
References _mom.
Referenced by JetProbeMaker::process_event().
size_t Jetv2::size_comp () const inline override virtual
Reimplemented from Jet.
Definition at line 96 of file Jetv2.h.
View newest version in sPHENIX GitHub at line 96 of file Jetv2.h
References _comp_ids.
size_t Jetv2::size_properties () const inline override virtual
Reimplemented from Jet.
Definition at line 89 of file Jetv2.h.
View newest version in sPHENIX GitHub at line 89 of file Jetv2.h
References _properties.
Jet::ConstIter Jetv2::upper_bound_comp (Jet::SRC source) const override private virtual
Reimplemented from Jet.
Definition at line 238 of file Jetv2.cc.
View newest version in sPHENIX GitHub at line 238 of file Jetv2.cc
References msg_dep_fn(), and Jet::upper_bound_comp().
Jet::Iter Jetv2::upper_bound_comp (Jet::SRC source) override private virtual
Reimplemented from Jet.
Definition at line 263 of file Jetv2.cc.
View newest version in sPHENIX GitHub at line 263 of file Jetv2.cc
References msg_dep_fn(), and Jet::upper_bound_comp().
Member Data Documentation
std::vector<std::pair<Jet::SRC, unsigned int> > Jetv2::_comp_ids private
source id -> component id
Definition at line 132 of file Jetv2.h.
View newest version in sPHENIX GitHub at line 132 of file Jetv2.h
Referenced by clear_comp(), comp_begin(), comp_end(), ensure_sorted(), get_comp_vec(), identify(), insert_comp(), isValid(), Reset(), and size_comp().
float Jetv2::_e = NAN private
jet energy
Definition at line 128 of file Jetv2.h.
View newest version in sPHENIX GitHub at line 128 of file Jetv2.h
Referenced by get_e(), isValid(), Reset(), and set_e().
unsigned int Jetv2::_id = ~0x0 private
unique identifier within container
Definition at line 120 of file Jetv2.h.
View newest version in sPHENIX GitHub at line 120 of file Jetv2.h
Referenced by get_id(), isValid(), Reset(), and set_id().
bool Jetv2::_is_sorted { false } private
Definition at line 122 of file Jetv2.h.
View newest version in sPHENIX GitHub at line 122 of file Jetv2.h
Referenced by ensure_sorted(), insert_comp(), and set_comp_sort_flag().
std::array<float,3> Jetv2::_mom {{ NAN, NAN, NAN}} private
jet momentum vector (px,py,pz)
Definition at line 125 of file Jetv2.h.
View newest version in sPHENIX GitHub at line 125 of file Jetv2.h
Referenced by get_px(), get_py(), get_pz(), isValid(), Reset(), set_px(), set_py(), and set_pz().
std::vector<float> Jetv2::_properties {} private
Definition at line 134 of file Jetv2.h.
View newest version in sPHENIX GitHub at line 134 of file Jetv2.h
Referenced by get_property(), get_property_vec(), identify(), Reset(), resize_properties(), set_property(), and size_properties().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/jetbase/Jetv2.h
coresoftware/blob/master/offline/packages/jetbase/Jetv2.cc