Analysis Software: MvtxPrototype2Align Class Reference
MvtxPrototype2Align Class Reference
#include <prototype/blob/master/offline/packages/MvtxPrototype2/MvtxPrototype2Align.h>
Classes
struct AlignmentPar
Public Member Functions
MvtxPrototype2Align (const std::string &name="MvtxAlign")
virtual ~MvtxPrototype2Align ()
int Init (PHCompositeNode *topNode)
module initialization
int InitRun (PHCompositeNode *topNode)
run initialization
int process_event (PHCompositeNode *topNode)
event processing
int End (PHCompositeNode *topNode)
end of process
void AddAlignmentPar (TrkrDefs::hitsetkey key, double dx, double dy, double dz)
put in misalignment by hand
void PrintAlignmentPars (std::ostream &os=std::cout) const
print stored misalignments
void SetAlignmentParFileDir (const std::string fdir)
set the directory for alignment parameter files
void SetAlignmentParFromFile (const bool yn)
set boolean to read from file rather than setting by hand
void SetAlignmentParFileName (const char *name)
set par file name. same for all runs
void SetIsGlobal (const bool yn)
set global coord flag;
bool GetIsGlobal ()
Public Member Functions inherited from SubsysReco
~SubsysReco () override
virtual int EndRun (const int)
Called at the end of each run.
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
void Print (const std::string &="ALL") const override
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Private Member Functions
int ReadAlignmentParFile ()
Private Attributes
TrkrClusterContainer * clusters_
std::map< TrkrDefs::hitsetkey,
AlignmentPar > alignmap_
std::string fdir_
int runnumber_
bool apff_
std::string m_afname
bool m_is_global
PHTimeServer::timer _timer
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = std::numeric_limits<int>::max() - 10
}
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Detailed Description
Definition at line 16 of file MvtxPrototype2Align.h.
View newest version in sPHENIX GitHub at line 16 of file MvtxPrototype2Align.h
Constructor & Destructor Documentation
MvtxPrototype2Align::MvtxPrototype2Align (const std::string & name = "MvtxAlign")
Definition at line 23 of file MvtxPrototype2Align.cc.
View newest version in sPHENIX GitHub at line 23 of file MvtxPrototype2Align.cc
virtual MvtxPrototype2Align::~MvtxPrototype2Align () inline virtual
Definition at line 28 of file MvtxPrototype2Align.h.
View newest version in sPHENIX GitHub at line 28 of file MvtxPrototype2Align.h
Member Function Documentation
void MvtxPrototype2Align::AddAlignmentPar (TrkrDefs::hitsetkey key, double dx, double dy, double dz)
put in misalignment by hand
Definition at line 110 of file MvtxPrototype2Align.cc.
View newest version in sPHENIX GitHub at line 110 of file MvtxPrototype2Align.cc
References alignmap_, MvtxPrototype2Align::AlignmentPar::dx, MvtxPrototype2Align::AlignmentPar::dy, dy, MvtxPrototype2Align::AlignmentPar::dz, dz, PHWHERE, and Fun4AllBase::Verbosity().
Referenced by ReadAlignmentParFile().
int MvtxPrototype2Align::End (PHCompositeNode * topNode) inline virtual
end of process
Reimplemented from SubsysReco.
Definition at line 40 of file MvtxPrototype2Align.h.
View newest version in sPHENIX GitHub at line 40 of file MvtxPrototype2Align.h
bool MvtxPrototype2Align::GetIsGlobal () inline
Definition at line 59 of file MvtxPrototype2Align.h.
View newest version in sPHENIX GitHub at line 59 of file MvtxPrototype2Align.h
References m_is_global.
int MvtxPrototype2Align::Init (PHCompositeNode * topNode) inline virtual
module initialization
Reimplemented from SubsysReco.
Definition at line 31 of file MvtxPrototype2Align.h.
View newest version in sPHENIX GitHub at line 31 of file MvtxPrototype2Align.h
int MvtxPrototype2Align::InitRun (PHCompositeNode * topNode) virtual
run initialization
Reimplemented from SubsysReco.
Definition at line 36 of file MvtxPrototype2Align.cc.
View newest version in sPHENIX GitHub at line 36 of file MvtxPrototype2Align.cc
References apff_, Fun4AllReturnCodes::EVENT_OK, PHFlag::get_IntFlag(), recoConsts::instance(), PHWHERE, ReadAlignmentParFile(), and runnumber_.
void MvtxPrototype2Align::PrintAlignmentPars (std::ostream & os = std::cout) const
print stored misalignments
Definition at line 148 of file MvtxPrototype2Align.cc.
View newest version in sPHENIX GitHub at line 148 of file MvtxPrototype2Align.cc
References alignmap_, dz, and PHWHERE.
Referenced by ReadAlignmentParFile().
int MvtxPrototype2Align::process_event (PHCompositeNode * topNode) virtual
event processing
Reimplemented from SubsysReco.
Definition at line 50 of file MvtxPrototype2Align.cc.
View newest version in sPHENIX GitHub at line 50 of file MvtxPrototype2Align.cc
References _timer, Fun4AllReturnCodes::ABORTRUN, alignmap_, clusters_, dy, dz, Fun4AllReturnCodes::EVENT_OK, TrkrClusterContainer::findCluster(), PHTimeServer::timer::get(), TrkrClusterContainer::getClusters(), TrkrDefs::getHitSetKeyFromClusKey(), TrkrClusterv1::getX(), TrkrClusterv1::getY(), TrkrClusterv1::getZ(), TrkrClusterv1::identify(), PHWHERE, PHTimer::restart(), TrkrClusterv1::setX(), TrkrClusterv1::setY(), TrkrClusterv1::setZ(), PHTimer::stop(), and Fun4AllBase::Verbosity().
int MvtxPrototype2Align::ReadAlignmentParFile () private
Definition at line 169 of file MvtxPrototype2Align.cc.
View newest version in sPHENIX GitHub at line 169 of file MvtxPrototype2Align.cc
References AddAlignmentPar(), fdir_, INTTVtxZ::fname, MvtxDefs::genHitSetKey(), line, m_afname, PHWHERE, PrintAlignmentPars(), runnumber_, and Fun4AllBase::Verbosity().
Referenced by InitRun().
void MvtxPrototype2Align::SetAlignmentParFileDir (const std::string fdir) inline
set the directory for alignment parameter files
Definition at line 49 of file MvtxPrototype2Align.h.
View newest version in sPHENIX GitHub at line 49 of file MvtxPrototype2Align.h
References fdir_.
Referenced by Fun4All_TestBeam().
void MvtxPrototype2Align::SetAlignmentParFileName (const char * name) inline
set par file name. same for all runs
Definition at line 55 of file MvtxPrototype2Align.h.
View newest version in sPHENIX GitHub at line 55 of file MvtxPrototype2Align.h
References m_afname, and perf_headwind::name.
Referenced by Fun4All_TestBeam().
void MvtxPrototype2Align::SetAlignmentParFromFile (const bool yn) inline
set boolean to read from file rather than setting by hand
Definition at line 52 of file MvtxPrototype2Align.h.
View newest version in sPHENIX GitHub at line 52 of file MvtxPrototype2Align.h
References apff_, and yn.
void MvtxPrototype2Align::SetIsGlobal (const bool yn) inline
set global coord flag;
Definition at line 58 of file MvtxPrototype2Align.h.
View newest version in sPHENIX GitHub at line 58 of file MvtxPrototype2Align.h
References m_is_global, and yn.
Member Data Documentation
PHTimeServer::timer MvtxPrototype2Align::_timer private
Definition at line 80 of file MvtxPrototype2Align.h.
View newest version in sPHENIX GitHub at line 80 of file MvtxPrototype2Align.h
Referenced by process_event().
std::map<TrkrDefs::hitsetkey, AlignmentPar> MvtxPrototype2Align::alignmap_ private
Definition at line 70 of file MvtxPrototype2Align.h.
View newest version in sPHENIX GitHub at line 70 of file MvtxPrototype2Align.h
Referenced by AddAlignmentPar(), PrintAlignmentPars(), and process_event().
bool MvtxPrototype2Align::apff_ private
Definition at line 75 of file MvtxPrototype2Align.h.
View newest version in sPHENIX GitHub at line 75 of file MvtxPrototype2Align.h
Referenced by InitRun(), and SetAlignmentParFromFile().
TrkrClusterContainer* MvtxPrototype2Align::clusters_ private
Definition at line 67 of file MvtxPrototype2Align.h.
View newest version in sPHENIX GitHub at line 67 of file MvtxPrototype2Align.h
Referenced by process_event().
std::string MvtxPrototype2Align::fdir_ private
Definition at line 73 of file MvtxPrototype2Align.h.
View newest version in sPHENIX GitHub at line 73 of file MvtxPrototype2Align.h
Referenced by ReadAlignmentParFile(), and SetAlignmentParFileDir().
std::string MvtxPrototype2Align::m_afname private
Definition at line 76 of file MvtxPrototype2Align.h.
View newest version in sPHENIX GitHub at line 76 of file MvtxPrototype2Align.h
Referenced by ReadAlignmentParFile(), and SetAlignmentParFileName().
bool MvtxPrototype2Align::m_is_global private
Definition at line 78 of file MvtxPrototype2Align.h.
View newest version in sPHENIX GitHub at line 78 of file MvtxPrototype2Align.h
Referenced by GetIsGlobal(), and SetIsGlobal().
int MvtxPrototype2Align::runnumber_ private
Definition at line 74 of file MvtxPrototype2Align.h.
View newest version in sPHENIX GitHub at line 74 of file MvtxPrototype2Align.h
Referenced by InitRun(), and ReadAlignmentParFile().
The documentation for this class was generated from the following files:
prototype/blob/master/offline/packages/MvtxPrototype2/MvtxPrototype2Align.h
prototype/blob/master/offline/packages/MvtxPrototype2/MvtxPrototype2Align.cc