Analysis Software: Acts::SurfaceBounds Class Reference
Acts::SurfaceBounds Class Reference abstract
#include <acts/blob/sPHENIX/Core/include/Acts/Surfaces/SurfaceBounds.hpp>
Public Types
enum BoundsType : int {
eCone = 0, eCylinder = 1, eDiamond = 2, eDisc = 3,
eEllipse = 4, eLine = 5, eRectangle = 6, eTrapezoid = 7,
eTriangle = 8, eDiscTrapezoid = 9, eConvexPolygon = 10, eAnnulus = 11,
eBoundless = 12, eOther = 13
}
Public Member Functions
virtual ~SurfaceBounds ()=default
virtual BoundsType type () const =0
virtual std::vector< double > values () const =0
virtual bool inside (const Vector2 &lposition, const BoundaryCheck &bcheck) const =0
virtual std::ostream & toStream (std::ostream &os) const =0
Detailed Description
Interface for surface bounds.
Surface bounds provide:
inside() checks
distance to boundary calculations
the BoundsType and a set of parameters to simplify persistency
Definition at line 26 of file SurfaceBounds.hpp.
View newest version in sPHENIX GitHub at line 26 of file SurfaceBounds.hpp
Member Enumeration Documentation
enum Acts::SurfaceBounds::BoundsType : int
This is nested to the SurfaceBounds, as also VolumeBounds will have Bounds Type.
Enumerator:
eCone
eCylinder
eDiamond
eDisc
eEllipse
eLine
eRectangle
eTrapezoid
eTriangle
eDiscTrapezoid
eConvexPolygon
eAnnulus
eBoundless
eOther
Definition at line 31 of file SurfaceBounds.hpp.
View newest version in sPHENIX GitHub at line 31 of file SurfaceBounds.hpp
Constructor & Destructor Documentation
virtual Acts::SurfaceBounds::~SurfaceBounds () virtual default
Member Function Documentation
virtual bool Acts::SurfaceBounds::inside (const Vector2 & lposition, const BoundaryCheck & bcheck) const pure virtual
Inside check for the bounds object driven by the boundary check directive Each Bounds has a method inside, which checks if a LocalPosition is inside the bounds Inside can be called without/with tolerances.
Parameters
lposition Local position (assumed to be in right surface frame)
bcheck boundary check directive
Returns
boolean indicator for the success of this operation
Implemented in Acts::ConvexPolygonBounds< PolygonDynamic >, Acts::TrapezoidBounds, Acts::ConvexPolygonBounds< N >, Acts::CylinderBounds, Acts::ConeBounds, Acts::AnnulusBounds, Acts::DiamondBounds, Acts::EllipseBounds, Acts::RectangleBounds, Acts::DiscTrapezoidBounds, Acts::RadialBounds, Acts::LineBounds, Acts::SurfaceBoundsStub, and Acts::InfiniteBounds.
Referenced by ActsFatras::PlanarSurfaceMask::apply().
virtual std::ostream& Acts::SurfaceBounds::toStream (std::ostream & os) const pure virtual
Output Method for std::ostream, to be overloaded by child classes
Parameters
os is the outstream in which the string dump is done
Implemented in Acts::TrapezoidBounds, Acts::CylinderBounds, Acts::DiamondBounds, Acts::EllipseBounds, Acts::RectangleBounds, Acts::ConeBounds, Acts::AnnulusBounds, Acts::DiscTrapezoidBounds, Acts::RadialBounds, Acts::LineBounds, Acts::SurfaceBoundsStub, Acts::InfiniteBounds, and Acts::ConvexPolygonBoundsBase.
Referenced by Acts::operator<<().
virtual BoundsType Acts::SurfaceBounds::type () const pure virtual
Return the bounds type - for persistency optimization
Returns
is a BoundsType enum
Implemented in Acts::ConvexPolygonBounds< PolygonDynamic >, Acts::ConvexPolygonBounds< N >, Acts::CylinderBounds, Acts::ConeBounds, Acts::AnnulusBounds, Acts::DiamondBounds, Acts::EllipseBounds, Acts::RectangleBounds, Acts::TrapezoidBounds, Acts::DiscTrapezoidBounds, Acts::RadialBounds, Acts::LineBounds, Acts::SurfaceBoundsStub, and Acts::InfiniteBounds.
Referenced by Acts::adjustBinUtility(), ActsFatras::PlanarSurfaceMask::apply(), Acts::Svg::SurfaceConverter::convert(), Acts::PodioUtil::convertSurfaceToPodio(), Acts::DetrayJsonHelper::maskFromBounds(), ActsExamples::DigitizationConfigurator::operator()(), Acts::operator==(), Acts::TGeoCylinderDiscSplitter::split(), ActsExamples::TGeoITkModuleSplitter::splitBarrelModule(), ActsExamples::TGeoITkModuleSplitter::splitDiscModule(), DD4hepTestsHelper::surfaceToXML(), and Acts::to_json().
virtual std::vector<double> Acts::SurfaceBounds::values () const pure virtual
Access method for bound values, this is a dynamically sized vector containing the parameters needed to describe these bounds
Returns
of the stored values for this SurfaceBounds object
Implemented in Acts::CylinderBounds, Acts::ConeBounds, Acts::AnnulusBounds, Acts::DiamondBounds, Acts::EllipseBounds, Acts::DiscTrapezoidBounds, Acts::RectangleBounds, Acts::TrapezoidBounds, Acts::RadialBounds, Acts::LineBounds, Acts::SurfaceBoundsStub, Acts::ConvexPolygonBoundsBase, and Acts::InfiniteBounds.
Referenced by Acts::Svg::SurfaceConverter::convert(), Acts::PodioUtil::convertSurfaceToPodio(), ActsExamples::SeedingFTFAlgorithm::LayerNumbering(), Acts::DetrayJsonHelper::maskFromBounds(), meanFromFree(), ActsExamples::DigitizationConfigurator::operator()(), Acts::operator==(), Acts::TGeoCylinderDiscSplitter::split(), ActsExamples::TGeoITkModuleSplitter::splitBarrelModule(), ActsExamples::TGeoITkModuleSplitter::splitDiscModule(), DD4hepTestsHelper::surfaceToXML(), and Acts::to_json().
The documentation for this class was generated from the following file:
acts/blob/sPHENIX/Core/include/Acts/Surfaces/SurfaceBounds.hpp