Analysis Software: SvtxTrackState Class Reference
SvtxTrackState Class Reference
#include <coresoftware/blob/master/offline/packages/trackbase_historic/SvtxTrackState.h>
Public Member Functions
~SvtxTrackState () override
void identify (std::ostream &os=std::cout) const override
int isValid () const override
isValid returns non zero if object contains vailid data
PHObject * CloneMe () const override
Virtual copy constructor.
virtual float get_pathlength () const
virtual float get_x () const
virtual void set_x (float)
virtual float get_y () const
virtual void set_y (float)
virtual float get_z () const
virtual void set_z (float)
virtual float get_pos (unsigned int) const
virtual float get_px () const
virtual void set_px (float)
virtual float get_py () const
virtual void set_py (float)
virtual float get_pz () const
virtual void set_pz (float)
virtual float get_mom (unsigned int) const
virtual float get_p () const
virtual float get_pt () const
virtual float get_eta () const
virtual float get_phi () const
virtual float get_error (unsigned int, unsigned int) const
virtual void set_error (unsigned int, unsigned int, float)
virtual TrkrDefs::cluskey get_cluskey () const
virtual void set_cluskey (TrkrDefs::cluskey)
virtual std::string get_name () const
virtual void set_name (const std::string &)
convenience interface, also found in Trkrcluster
virtual float get_rphi_error () const
rphi error
virtual float get_phi_error () const
phi error
virtual float get_z_error () const
z error
Public Member Functions inherited from PHObject
PHObject ()
ctor
~PHObject () override
dtor
virtual PHObject * clone () const final
PHObject * Clone (const char *newname="") const final
void Copy (TObject &object) const final
virtual void Reset ()
Clear Event.
virtual int Integrate () const
virtual int Integrate (PHObject *)
virtual void CopyFrom (const PHObject *obj)
Protected Member Functions
SvtxTrackState (float=0.0)
ClassDefOverride (SvtxTrackState, 1)
Detailed Description
Definition at line 9 of file SvtxTrackState.h.
View newest version in sPHENIX GitHub at line 9 of file SvtxTrackState.h
Constructor & Destructor Documentation
SvtxTrackState::~SvtxTrackState () inline override
Definition at line 12 of file SvtxTrackState.h.
View newest version in sPHENIX GitHub at line 12 of file SvtxTrackState.h
SvtxTrackState::SvtxTrackState (float = 0.0) inline protected
Definition at line 84 of file SvtxTrackState.h.
View newest version in sPHENIX GitHub at line 84 of file SvtxTrackState.h
Member Function Documentation
SvtxTrackState::ClassDefOverride (SvtxTrackState , 1) protected
PHObject* SvtxTrackState::CloneMe () const inline override virtual
Virtual copy constructor.
Reimplemented from PHObject.
Reimplemented in SvtxTrackState_v1, and SvtxTrackState_v2.
Definition at line 20 of file SvtxTrackState.h.
View newest version in sPHENIX GitHub at line 20 of file SvtxTrackState.h
Referenced by SvtxTrack_v4::insert_state(), SvtxTrack_v1::insert_state(), SvtxTrack_v2::insert_state(), and SvtxTrack_v3::insert_state().
virtual TrkrDefs::cluskey SvtxTrackState::get_cluskey () const inline virtual
Reimplemented in SvtxTrackState_v2.
Definition at line 54 of file SvtxTrackState.h.
View newest version in sPHENIX GitHub at line 54 of file SvtxTrackState.h
Referenced by TrackResiduals::fillClusterBranches(), and MakeMilleFiles::getLocalVtxDerivativesXY().
virtual float SvtxTrackState::get_error (unsigned int , unsigned int) const inline virtual
Reimplemented in SvtxTrackState_v1, and SvtxTrackState_v2.
Definition at line 51 of file SvtxTrackState.h.
View newest version in sPHENIX GitHub at line 51 of file SvtxTrackState.h
Referenced by GenFitTrackProp::fill_tree(), PHGenFitTrackProjection::process_event(), TrackProjectorPid::project_track(), TrackProjectorPlaneECAL::project_track(), ActsTransformations::rotateSvtxTrackCovToActs(), and PHRaveVertexing::TranslateSvtxToGenFitTrack().
virtual float SvtxTrackState::get_eta () const inline virtual
Reimplemented in SvtxTrackState_v1, and SvtxTrackState_v2.
Definition at line 48 of file SvtxTrackState.h.
View newest version in sPHENIX GitHub at line 48 of file SvtxTrackState.h
Referenced by TrackProjectionTools::FindClosestTrack(), and FastPid_RICH::process_event().
virtual float SvtxTrackState::get_mom (unsigned int) const inline virtual
Reimplemented in SvtxTrackState_v1, and SvtxTrackState_v2.
Definition at line 44 of file SvtxTrackState.h.
View newest version in sPHENIX GitHub at line 44 of file SvtxTrackState.h
virtual std::string SvtxTrackState::get_name (void) const inline virtual
Reimplemented in SvtxTrackState_v2, and SvtxTrackState_v1.
Definition at line 57 of file SvtxTrackState.h.
View newest version in sPHENIX GitHub at line 57 of file SvtxTrackState.h
Referenced by TrackProjectionTools::FindClosestTrack(), and DISKinematicsReco::InsertCandidateFromCluster().
virtual float SvtxTrackState::get_p () const inline virtual
Reimplemented in SvtxTrackState_v1, and SvtxTrackState_v2.
Definition at line 46 of file SvtxTrackState.h.
View newest version in sPHENIX GitHub at line 46 of file SvtxTrackState.h
Referenced by FastPid_RICH::process_event().
virtual float SvtxTrackState::get_pathlength () const inline virtual
Reimplemented in SvtxTrackState_v1, and SvtxTrackState_v2.
Definition at line 22 of file SvtxTrackState.h.
View newest version in sPHENIX GitHub at line 22 of file SvtxTrackState.h
Referenced by TrackResiduals::fillClusterBranches(), sPHAnalysis::Get_CAL_e3x3(), FilterEventsUpsilon::GetProjectionCEMC(), FilterEvents::GetProjectionCEMC(), sPHAnalysis::GetProjectionToCalorimeter(), SvtxTrack_v4::insert_state(), SvtxTrack_v1::insert_state(), SvtxTrack_v2::insert_state(), SvtxTrack_v3::insert_state(), FilterEventsUpsilon::MatchClusterCEMC(), FilterEvents::MatchClusterCEMC(), sPHAnalysis::MatchClusterCEMC(), and PHRaveVertexing::TranslateSvtxToGenFitTrack().
virtual float SvtxTrackState::get_phi () const inline virtual
Reimplemented in SvtxTrackState_v1, and SvtxTrackState_v2.
Definition at line 49 of file SvtxTrackState.h.
View newest version in sPHENIX GitHub at line 49 of file SvtxTrackState.h
Referenced by TrackProjectionTools::FindClosestTrack().
virtual float SvtxTrackState::get_phi_error () const inline virtual
phi error
Reimplemented in SvtxTrackState_v2, and SvtxTrackState_v1.
Definition at line 70 of file SvtxTrackState.h.
View newest version in sPHENIX GitHub at line 70 of file SvtxTrackState.h
Referenced by TrackEvaluation::add_trk_information(), and TrackEvaluation::add_trk_information_micromegas().
virtual float SvtxTrackState::get_pos (unsigned int) const inline virtual
Reimplemented in SvtxTrackState_v1, and SvtxTrackState_v2.
Definition at line 33 of file SvtxTrackState.h.
View newest version in sPHENIX GitHub at line 33 of file SvtxTrackState.h
virtual float SvtxTrackState::get_pt () const inline virtual
Reimplemented in SvtxTrackState_v1, and SvtxTrackState_v2.
Definition at line 47 of file SvtxTrackState.h.
View newest version in sPHENIX GitHub at line 47 of file SvtxTrackState.h
virtual float SvtxTrackState::get_px () const inline virtual
Reimplemented in SvtxTrackState_v1, and SvtxTrackState_v2.
Definition at line 35 of file SvtxTrackState.h.
View newest version in sPHENIX GitHub at line 35 of file SvtxTrackState.h
Referenced by TrackEvaluation::add_trk_information(), TrackEvaluation::add_trk_information_micromegas(), GenFitTrackProp::fill_tree(), TrackResiduals::fillClusterBranches(), ActsPropagator::makeTrackParams(), FastPid_RICH::process_event(), PHGenFitTrackProjection::process_event(), TrackProjectorPid::project_track(), TrackProjectorPlaneECAL::project_track(), ActsTransformations::rotateSvtxTrackCovToActs(), and PHRaveVertexing::TranslateSvtxToGenFitTrack().
virtual float SvtxTrackState::get_py () const inline virtual
Reimplemented in SvtxTrackState_v1, and SvtxTrackState_v2.
Definition at line 38 of file SvtxTrackState.h.
View newest version in sPHENIX GitHub at line 38 of file SvtxTrackState.h
Referenced by TrackEvaluation::add_trk_information(), TrackEvaluation::add_trk_information_micromegas(), GenFitTrackProp::fill_tree(), TrackResiduals::fillClusterBranches(), ActsPropagator::makeTrackParams(), FastPid_RICH::process_event(), PHGenFitTrackProjection::process_event(), TrackProjectorPid::project_track(), TrackProjectorPlaneECAL::project_track(), ActsTransformations::rotateSvtxTrackCovToActs(), and PHRaveVertexing::TranslateSvtxToGenFitTrack().
virtual float SvtxTrackState::get_pz () const inline virtual
Reimplemented in SvtxTrackState_v1, and SvtxTrackState_v2.
Definition at line 41 of file SvtxTrackState.h.
View newest version in sPHENIX GitHub at line 41 of file SvtxTrackState.h
Referenced by TrackEvaluation::add_trk_information(), TrackEvaluation::add_trk_information_micromegas(), GenFitTrackProp::fill_tree(), TrackResiduals::fillClusterBranches(), ActsPropagator::makeTrackParams(), FastPid_RICH::process_event(), PHGenFitTrackProjection::process_event(), TrackProjectorPid::project_track(), TrackProjectorPlaneECAL::project_track(), ActsTransformations::rotateSvtxTrackCovToActs(), and PHRaveVertexing::TranslateSvtxToGenFitTrack().
virtual float SvtxTrackState::get_rphi_error () const inline virtual
rphi error
Reimplemented in SvtxTrackState_v2, and SvtxTrackState_v1.
Definition at line 64 of file SvtxTrackState.h.
View newest version in sPHENIX GitHub at line 64 of file SvtxTrackState.h
virtual float SvtxTrackState::get_x () const inline virtual
Reimplemented in SvtxTrackState_v1, and SvtxTrackState_v2.
Definition at line 24 of file SvtxTrackState.h.
View newest version in sPHENIX GitHub at line 24 of file SvtxTrackState.h
Referenced by TrackEvaluation::add_trk_information(), TrackEvaluation::add_trk_information_micromegas(), IsolatedTrackAnalysis::calculateProjectionEta(), IsolatedTrackAnalysis::calculateProjectionPhi(), GenFitTrackProp::fill_tree(), ActsAlignmentStates::fillAlignmentStateMap(), TrackResiduals::fillClusterBranches(), TrackProjectionTools::FindClosestTrack(), TrackProjectorPlaneECAL::get_best_state(), TrackProjectorPlaneECAL::get_best_track(), sPHAnalysis::Get_CAL_e3x3(), FilterEventsUpsilon::GetProjectionCEMC(), FilterEvents::GetProjectionCEMC(), sPHAnalysis::GetProjectionToCalorimeter(), DISKinematicsReco::InsertCandidateFromCluster(), ActsPropagator::makeTrackParams(), FilterEventsUpsilon::MatchClusterCEMC(), FilterEvents::MatchClusterCEMC(), sPHAnalysis::MatchClusterCEMC(), PHTrackClusterAssociator::matchTracks(), FastPid_RICH::process_event(), ParticleFlowReco::process_event(), PHGenFitTrackProjection::process_event(), TrackProjectorPid::project_track(), TrackProjectorPlaneECAL::project_track(), and PHRaveVertexing::TranslateSvtxToGenFitTrack().
virtual float SvtxTrackState::get_y () const inline virtual
Reimplemented in SvtxTrackState_v1, and SvtxTrackState_v2.
Definition at line 27 of file SvtxTrackState.h.
View newest version in sPHENIX GitHub at line 27 of file SvtxTrackState.h
Referenced by TrackEvaluation::add_trk_information(), TrackEvaluation::add_trk_information_micromegas(), IsolatedTrackAnalysis::calculateProjectionEta(), IsolatedTrackAnalysis::calculateProjectionPhi(), GenFitTrackProp::fill_tree(), ActsAlignmentStates::fillAlignmentStateMap(), TrackResiduals::fillClusterBranches(), TrackProjectionTools::FindClosestTrack(), TrackProjectorPlaneECAL::get_best_state(), TrackProjectorPlaneECAL::get_best_track(), sPHAnalysis::Get_CAL_e3x3(), FilterEventsUpsilon::GetProjectionCEMC(), FilterEvents::GetProjectionCEMC(), sPHAnalysis::GetProjectionToCalorimeter(), DISKinematicsReco::InsertCandidateFromCluster(), ActsPropagator::makeTrackParams(), FilterEventsUpsilon::MatchClusterCEMC(), FilterEvents::MatchClusterCEMC(), sPHAnalysis::MatchClusterCEMC(), PHTrackClusterAssociator::matchTracks(), FastPid_RICH::process_event(), ParticleFlowReco::process_event(), PHGenFitTrackProjection::process_event(), TrackProjectorPid::project_track(), TrackProjectorPlaneECAL::project_track(), and PHRaveVertexing::TranslateSvtxToGenFitTrack().
virtual float SvtxTrackState::get_z () const inline virtual
Reimplemented in SvtxTrackState_v1, and SvtxTrackState_v2.
Definition at line 30 of file SvtxTrackState.h.
View newest version in sPHENIX GitHub at line 30 of file SvtxTrackState.h
Referenced by TrackEvaluation::add_trk_information(), TrackEvaluation::add_trk_information_micromegas(), IsolatedTrackAnalysis::calculateProjectionEta(), GenFitTrackProp::fill_tree(), TrackResiduals::fillClusterBranches(), TrackProjectorPlaneECAL::get_best_state(), TrackProjectorPlaneECAL::get_best_track(), sPHAnalysis::Get_CAL_e3x3(), FilterEventsUpsilon::GetProjectionCEMC(), FilterEvents::GetProjectionCEMC(), sPHAnalysis::GetProjectionToCalorimeter(), DISKinematicsReco::InsertCandidateFromCluster(), ActsPropagator::makeTrackParams(), FilterEventsUpsilon::MatchClusterCEMC(), FilterEvents::MatchClusterCEMC(), sPHAnalysis::MatchClusterCEMC(), PHTrackClusterAssociator::matchTracks(), FastPid_RICH::process_event(), ParticleFlowReco::process_event(), PHGenFitTrackProjection::process_event(), TrackProjectorPid::project_track(), TrackProjectorPlaneECAL::project_track(), and PHRaveVertexing::TranslateSvtxToGenFitTrack().
virtual float SvtxTrackState::get_z_error () const inline virtual
z error
Reimplemented in SvtxTrackState_v2, and SvtxTrackState_v1.
Definition at line 76 of file SvtxTrackState.h.
View newest version in sPHENIX GitHub at line 76 of file SvtxTrackState.h
Referenced by TrackEvaluation::add_trk_information(), and TrackEvaluation::add_trk_information_micromegas().
void SvtxTrackState::identify (std::ostream & os = std::cout) const inline override virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from PHObject.
Reimplemented in SvtxTrackState_v1, and SvtxTrackState_v2.
Definition at line 14 of file SvtxTrackState.h.
View newest version in sPHENIX GitHub at line 14 of file SvtxTrackState.h
References os.
int SvtxTrackState::isValid () const inline override virtual
isValid returns non zero if object contains vailid data
Reimplemented from PHObject.
Reimplemented in SvtxTrackState_v1, and SvtxTrackState_v2.
Definition at line 19 of file SvtxTrackState.h.
View newest version in sPHENIX GitHub at line 19 of file SvtxTrackState.h
virtual void SvtxTrackState::set_cluskey (TrkrDefs::cluskey) inline virtual
Reimplemented in SvtxTrackState_v2.
Definition at line 55 of file SvtxTrackState.h.
View newest version in sPHENIX GitHub at line 55 of file SvtxTrackState.h
virtual void SvtxTrackState::set_error (unsigned int , unsigned int , float) inline virtual
Reimplemented in SvtxTrackState_v1, and SvtxTrackState_v2.
Definition at line 52 of file SvtxTrackState.h.
View newest version in sPHENIX GitHub at line 52 of file SvtxTrackState.h
Referenced by PHG4TrackFastSim::MakeSvtxTrack().
virtual void SvtxTrackState::set_name (const std::string &) inline virtual
Reimplemented in SvtxTrackState_v2, and SvtxTrackState_v1.
Definition at line 58 of file SvtxTrackState.h.
View newest version in sPHENIX GitHub at line 58 of file SvtxTrackState.h
Referenced by PHG4TrackFastSim::MakeSvtxTrack().
virtual void SvtxTrackState::set_px (float) inline virtual
Reimplemented in SvtxTrackState_v1, and SvtxTrackState_v2.
Definition at line 36 of file SvtxTrackState.h.
View newest version in sPHENIX GitHub at line 36 of file SvtxTrackState.h
Referenced by PHG4TrackFastSim::MakeSvtxTrack().
virtual void SvtxTrackState::set_py (float) inline virtual
Reimplemented in SvtxTrackState_v1, and SvtxTrackState_v2.
Definition at line 39 of file SvtxTrackState.h.
View newest version in sPHENIX GitHub at line 39 of file SvtxTrackState.h
Referenced by PHG4TrackFastSim::MakeSvtxTrack().
virtual void SvtxTrackState::set_pz (float) inline virtual
Reimplemented in SvtxTrackState_v1, and SvtxTrackState_v2.
Definition at line 42 of file SvtxTrackState.h.
View newest version in sPHENIX GitHub at line 42 of file SvtxTrackState.h
Referenced by PHG4TrackFastSim::MakeSvtxTrack().
virtual void SvtxTrackState::set_x (float) inline virtual
Reimplemented in SvtxTrackState_v1, and SvtxTrackState_v2.
Definition at line 25 of file SvtxTrackState.h.
View newest version in sPHENIX GitHub at line 25 of file SvtxTrackState.h
Referenced by PHG4TrackFastSim::MakeSvtxTrack().
virtual void SvtxTrackState::set_y (float) inline virtual
Reimplemented in SvtxTrackState_v1, and SvtxTrackState_v2.
Definition at line 28 of file SvtxTrackState.h.
View newest version in sPHENIX GitHub at line 28 of file SvtxTrackState.h
Referenced by PHG4TrackFastSim::MakeSvtxTrack().
virtual void SvtxTrackState::set_z (float) inline virtual
Reimplemented in SvtxTrackState_v1, and SvtxTrackState_v2.
Definition at line 31 of file SvtxTrackState.h.
View newest version in sPHENIX GitHub at line 31 of file SvtxTrackState.h
Referenced by PHG4TrackFastSim::MakeSvtxTrack().
The documentation for this class was generated from the following file:
coresoftware/blob/master/offline/packages/trackbase_historic/SvtxTrackState.h