Analysis Software: CaloEvaluator Class Reference
CaloEvaluator Class Reference
Compares reconstructed showers to truth particles.
#include <analysis/blob/master/EMCal-position-dependent-calibration/src/ana.354/CaloEvaluator.h>
Public Member Functions
CaloEvaluator (const std::string &name="CALOEVALUATOR", const std::string &caloname="CEMC", const std::string &filename="g4eval_cemc.root")
~CaloEvaluator () override
int Init (PHCompositeNode *topNode) override
int process_event (PHCompositeNode *topNode) override
int End (PHCompositeNode *topNode) override
Called at the end of all processing.
void set_strict (bool b)
void add_truth_tracing_embed_flag (int flag)
void set_truth_tracing_energy_threshold (float thresh)
void set_reco_tracing_energy_threshold (float thresh)
void set_do_gpoint_eval (bool b)
void set_do_gshower_eval (bool b)
void set_do_tower_eval (bool b)
void set_do_cluster_eval (bool b)
CaloEvaluator (const std::string &name="CALOEVALUATOR", const std::string &caloname="CEMC", const std::string &filename="g4eval_cemc.root")
~CaloEvaluator () override
int Init (PHCompositeNode *topNode) override
int process_event (PHCompositeNode *topNode) override
int End (PHCompositeNode *topNode) override
Called at the end of all processing.
void set_strict (bool b)
void add_truth_tracing_embed_flag (int flag)
void set_truth_tracing_energy_threshold (float thresh)
void set_reco_tracing_energy_threshold (float thresh)
void set_do_gpoint_eval (bool b)
void set_do_gshower_eval (bool b)
void set_do_tower_eval (bool b)
void set_do_cluster_eval (bool b)
CaloEvaluator (const std::string &name="CALOEVALUATOR", const std::string &caloname="CEMC", const std::string &filename="g4eval_cemc.root")
~CaloEvaluator () override
int Init (PHCompositeNode *topNode) override
int process_event (PHCompositeNode *topNode) override
int End (PHCompositeNode *topNode) override
Called at the end of all processing.
void set_event (int ievent)
void set_strict (bool b)
void add_truth_tracing_embed_flag (int flag)
void set_truth_tracing_energy_threshold (float thresh)
void set_reco_tracing_energy_threshold (float thresh)
void set_do_gpoint_eval (bool b)
void set_do_gshower_eval (bool b)
void set_do_tower_eval (bool b)
void set_do_cluster_eval (bool b)
Public Member Functions inherited from SubsysReco
~SubsysReco () override
virtual int EndRun (const int)
Called at the end of each run.
virtual int InitRun (PHCompositeNode *)
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
void Print (const std::string &="ALL") const override
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Private Member Functions
void printInputInfo (PHCompositeNode *topNode)
print out the input object information (debugging upstream components)
void fillOutputNtuples (PHCompositeNode *topNode)
dump the evaluator information into ntuple for external analysis
void printOutputInfo (PHCompositeNode *topNode)
print out the ancestry information for detailed diagnosis
void printInputInfo (PHCompositeNode *topNode)
print out the input object information (debugging upstream components)
void fillOutputNtuples (PHCompositeNode *topNode)
dump the evaluator information into ntuple for external analysis
void printOutputInfo (PHCompositeNode *topNode)
print out the ancestry information for detailed diagnosis
void printInputInfo (PHCompositeNode *topNode)
print out the input object information (debugging upstream components)
void fillOutputNtuples (PHCompositeNode *topNode)
dump the evaluator information into ntuple for external analysis
void printOutputInfo (PHCompositeNode *topNode)
print out the ancestry information for detailed diagnosis
Private Attributes
std::string _caloname
unsigned int _ievent = 0
unsigned int _towerID_debug = 0
int _ieta_debug = 0
int _iphi_debug = 0
float _eta_debug = 0.
float _phi_debug = 0.
float _e_debug = 0.
float _x_debug = 0.
float _y_debug = 0.
float _z_debug = 0.
std::set< int > _truth_trace_embed_flags
float _truth_e_threshold = 0.
float _reco_e_threshold = 0.
CaloEvalStack * _caloevalstack = nullptr
std::vector< unsigned char > _towerEtas
std::vector< unsigned char > _towerPhis
std::vector< float > _towerEnergies
bool _strict = false
bool _do_gpoint_eval = true
bool _do_gshower_eval = true
bool _do_tower_eval = true
bool _do_cluster_eval = true
TNtuple * _ntp_gpoint = nullptr
TNtuple * _ntp_gshower = nullptr
TNtuple * _ntp_tower = nullptr
TTree * _tower_debug = nullptr
TTree * _cluster_tower_info
TNtuple * _ntp_cluster = nullptr
std::string _filename
TFile * _tfile = nullptr
unsigned int m_EvtCounter = 0
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = std::numeric_limits<int>::max() - 10
}
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Detailed Description
Compares reconstructed showers to truth particles.
Plan: This module will trace the reconstructed clusters back to the greatest contributor Monte Carlo particle and then test one against the other.
Definition at line 30 of file CaloEvaluator.h.
View newest version in sPHENIX GitHub at line 30 of file CaloEvaluator.h
Constructor & Destructor Documentation
CaloEvaluator::CaloEvaluator (const std::string & name = "CALOEVALUATOR", const std::string & caloname = "CEMC", const std::string & filename = "g4eval_cemc.root")
Definition at line 44 of file CaloEvaluator.cc.
View newest version in sPHENIX GitHub at line 44 of file CaloEvaluator.cc
CaloEvaluator::~CaloEvaluator () inline override
Definition at line 36 of file CaloEvaluator.h.
View newest version in sPHENIX GitHub at line 36 of file CaloEvaluator.h
CaloEvaluator::CaloEvaluator (const std::string & name = "CALOEVALUATOR", const std::string & caloname = "CEMC", const std::string & filename = "g4eval_cemc.root")
CaloEvaluator::~CaloEvaluator () inline override
Definition at line 36 of file CaloEvaluator.h.
View newest version in sPHENIX GitHub at line 36 of file CaloEvaluator.h
CaloEvaluator::CaloEvaluator (const std::string & name = "CALOEVALUATOR", const std::string & caloname = "CEMC", const std::string & filename = "g4eval_cemc.root")
CaloEvaluator::~CaloEvaluator () inline override
Definition at line 35 of file CaloEvaluator.h.
View newest version in sPHENIX GitHub at line 35 of file CaloEvaluator.h
Member Function Documentation
void CaloEvaluator::add_truth_tracing_embed_flag (int flag) inline
Definition at line 51 of file CaloEvaluator.h.
View newest version in sPHENIX GitHub at line 51 of file CaloEvaluator.h
References _truth_trace_embed_flags.
void CaloEvaluator::add_truth_tracing_embed_flag (int flag) inline
Definition at line 51 of file CaloEvaluator.h.
View newest version in sPHENIX GitHub at line 51 of file CaloEvaluator.h
References _truth_trace_embed_flags.
void CaloEvaluator::add_truth_tracing_embed_flag (int flag) inline
Definition at line 58 of file CaloEvaluator.h.
View newest version in sPHENIX GitHub at line 58 of file CaloEvaluator.h
References _truth_trace_embed_flags.
int CaloEvaluator::End (PHCompositeNode *) override virtual
Called at the end of all processing.
Reimplemented from SubsysReco.
int CaloEvaluator::End (PHCompositeNode *) override virtual
Called at the end of all processing.
Reimplemented from SubsysReco.
Definition at line 174 of file CaloEvaluator.cc.
View newest version in sPHENIX GitHub at line 174 of file CaloEvaluator.cc
References _caloevalstack, _cluster_tower_info, _do_cluster_eval, _do_gpoint_eval, _do_gshower_eval, _do_tower_eval, _filename, _ievent, _ntp_cluster, _ntp_gpoint, _ntp_gshower, _ntp_tower, _tfile, _tower_debug, Fun4AllReturnCodes::EVENT_OK, Fun4AllBase::Name(), and Fun4AllBase::Verbosity().
int CaloEvaluator::End (PHCompositeNode *) override virtual
Called at the end of all processing.
Reimplemented from SubsysReco.
void CaloEvaluator::fillOutputNtuples (PHCompositeNode * topNode) private
dump the evaluator information into ntuple for external analysis
void CaloEvaluator::fillOutputNtuples (PHCompositeNode * topNode) private
dump the evaluator information into ntuple for external analysis
void CaloEvaluator::fillOutputNtuples (PHCompositeNode * topNode) private
dump the evaluator information into ntuple for external analysis
Definition at line 404 of file CaloEvaluator.cc.
View newest version in sPHENIX GitHub at line 404 of file CaloEvaluator.cc
References _caloevalstack, _caloname, _cluster_tower_info, _do_cluster_eval, _do_gpoint_eval, _do_tower_eval, _e_debug, _eta_debug, _ieta_debug, _ievent, _iphi_debug, _ntp_cluster, _ntp_gpoint, _ntp_gshower, _ntp_tower, _phi_debug, _reco_e_threshold, _tower_debug, _towerEnergies, _towerEtas, _towerID_debug, _towerPhis, _truth_e_threshold, _truth_trace_embed_flags, _x_debug, _y_debug, _z_debug, GlobalVertexMap::begin(), CaloRawClusterEval::best_cluster_from(), clusters, Acts::UnitConstants::e, efromtruth, GlobalVertexMap::empty(), eta, RawTower::get_bineta(), RawTower::get_binphi(), CaloTruthEval::get_caloid(), RawTowerGeom::get_center_x(), RawTowerGeom::get_center_y(), RawTowerGeom::get_center_z(), PHG4Particle::get_e(), RawCluster::get_ecore(), CaloTruthEval::get_embed(), RawCluster::get_energy(), RawTower::get_energy(), CaloRawTowerEval::get_energy_contribution(), CaloRawClusterEval::get_energy_contribution(), RawTowerGeom::get_eta(), RawCluster::get_id(), RawTower::get_id(), PHG4Shower::get_nhits(), RawCluster::get_phi(), RawTowerGeom::get_phi(), PHG4Particle::get_pid(), CaloTruthEval::get_primary_shower(), PHG4Particle::get_px(), PHG4Particle::get_py(), PHG4Particle::get_pz(), CaloEvalStack::get_rawcluster_eval(), CaloEvalStack::get_rawtower_eval(), CaloTruthEval::get_shower_energy_deposit(), RawTowerGeomContainer::get_tower_geometry(), RawCluster::get_towers(), PHG4Particle::get_track_id(), CaloEvalStack::get_truth_eval(), CaloTruthEval::get_vertex(), PHG4VtxPoint::get_x(), GlobalVertex::get_x(), RawCluster::get_x(), PHG4VtxPoint::get_y(), GlobalVertex::get_y(), RawCluster::get_y(), PHG4VtxPoint::get_z(), GlobalVertex::get_z(), RawCluster::get_z(), geta, RawClusterContainer::getClustersMap(), RawCluster::getNTowers(), PHG4TruthInfoContainer::GetPrimaryVertexIndex(), PHG4TruthInfoContainer::GetPrimaryVtx(), RawClusterUtility::GetPseudorapidity(), RawTowerContainer::getTower(), RawTowerContainer::getTowers(), gflavor, gpx, gpy, gpz, RawTower::identify(), CaloRawClusterEval::max_truth_primary_particle_by_energy(), CaloRawTowerEval::max_truth_primary_particle_by_energy(), Fun4AllBase::Name(), ActsTests::PropagationDatasets::phi, PHWHERE, Fun4AllBase::Verbosity(), vx, vy, vz, ambiguity_solver_full_chain::x, y, and physmon_track_finding_ttbar::z.
Referenced by process_event().
int CaloEvaluator::Init (PHCompositeNode *) override virtual
Called during initialization. Typically this is where you can book histograms, and e.g. register them to Fun4AllServer (so they can be output to file using Fun4AllServer::dumpHistos() method).
Reimplemented from SubsysReco.
int CaloEvaluator::Init (PHCompositeNode *) override virtual
Called during initialization. Typically this is where you can book histograms, and e.g. register them to Fun4AllServer (so they can be output to file using Fun4AllServer::dumpHistos() method).
Reimplemented from SubsysReco.
Definition at line 78 of file CaloEvaluator.cc.
View newest version in sPHENIX GitHub at line 78 of file CaloEvaluator.cc
References _cluster_tower_info, _do_cluster_eval, _do_gpoint_eval, _do_gshower_eval, _do_tower_eval, _e_debug, _eta_debug, _filename, _ieta_debug, _ievent, _iphi_debug, _ntp_cluster, _ntp_gpoint, _ntp_gshower, _ntp_tower, _phi_debug, _tfile, _tower_debug, _towerEnergies, _towerEtas, _towerID_debug, _towerPhis, _x_debug, _y_debug, _z_debug, Fun4AllReturnCodes::EVENT_OK, and set_reco_tracing_energy_threshold().
int CaloEvaluator::Init (PHCompositeNode *) override virtual
Called during initialization. Typically this is where you can book histograms, and e.g. register them to Fun4AllServer (so they can be output to file using Fun4AllServer::dumpHistos() method).
Reimplemented from SubsysReco.
void CaloEvaluator::printInputInfo (PHCompositeNode * topNode) private
print out the input object information (debugging upstream components)
void CaloEvaluator::printInputInfo (PHCompositeNode * topNode) private
print out the input object information (debugging upstream components)
void CaloEvaluator::printInputInfo (PHCompositeNode * topNode) private
print out the input object information (debugging upstream components)
Definition at line 206 of file CaloEvaluator.cc.
View newest version in sPHENIX GitHub at line 206 of file CaloEvaluator.cc
References _ievent, PHG4Particle::get_pid(), PHG4Particle::get_px(), PHG4Particle::get_py(), PHG4TruthInfoContainer::GetParticleRange(), Fun4AllBase::Name(), particle, PHWHERE, and Fun4AllBase::Verbosity().
Referenced by process_event().
void CaloEvaluator::printOutputInfo (PHCompositeNode * topNode) private
print out the ancestry information for detailed diagnosis
void CaloEvaluator::printOutputInfo (PHCompositeNode * topNode) private
print out the ancestry information for detailed diagnosis
void CaloEvaluator::printOutputInfo (PHCompositeNode * topNode) private
print out the ancestry information for detailed diagnosis
Definition at line 243 of file CaloEvaluator.cc.
View newest version in sPHENIX GitHub at line 243 of file CaloEvaluator.cc
References _caloevalstack, _ievent, CaloRawClusterEval::all_clusters_from(), GlobalVertexMap::begin(), clusters, Acts::UnitConstants::e, efromtruth, GlobalVertexMap::empty(), PHG4Particle::get_e(), CaloTruthEval::get_embed(), RawCluster::get_energy(), CaloRawClusterEval::get_energy_contribution(), RawCluster::get_id(), RawCluster::get_phi(), PHG4Particle::get_pid(), PHG4Particle::get_px(), PHG4Particle::get_py(), PHG4Particle::get_pz(), CaloEvalStack::get_rawcluster_eval(), CaloTruthEval::get_shower_energy_deposit(), PHG4Particle::get_track_id(), CaloEvalStack::get_truth_eval(), CaloTruthEval::get_vertex(), PHG4VtxPoint::get_x(), GlobalVertex::get_x(), RawCluster::get_x(), PHG4VtxPoint::get_y(), GlobalVertex::get_y(), RawCluster::get_y(), PHG4VtxPoint::get_z(), GlobalVertex::get_z(), RawCluster::get_z(), geta, RawCluster::getNTowers(), PHG4TruthInfoContainer::GetPrimaryParticleRange(), PHG4TruthInfoContainer::GetPrimaryVertexIndex(), PHG4TruthInfoContainer::GetPrimaryVtx(), gpx, gpy, gpz, ActsTests::PropagationDatasets::phi, PHWHERE, Fun4AllBase::Verbosity(), vx, vy, vz, ambiguity_solver_full_chain::x, y, and physmon_track_finding_ttbar::z.
Referenced by process_event().
int CaloEvaluator::process_event (PHCompositeNode *) override virtual
Called for each event. This is where you do the real work.
Reimplemented from SubsysReco.
int CaloEvaluator::process_event (PHCompositeNode *) override virtual
Called for each event. This is where you do the real work.
Reimplemented from SubsysReco.
Definition at line 138 of file CaloEvaluator.cc.
View newest version in sPHENIX GitHub at line 138 of file CaloEvaluator.cc
References _caloevalstack, _caloname, _ievent, _strict, Fun4AllReturnCodes::EVENT_OK, fillOutputNtuples(), CaloEvalStack::next_event(), printInputInfo(), printOutputInfo(), CaloEvalStack::set_strict(), CaloEvalStack::set_verbosity(), and Fun4AllBase::Verbosity().
int CaloEvaluator::process_event (PHCompositeNode *) override virtual
Called for each event. This is where you do the real work.
Reimplemented from SubsysReco.
void CaloEvaluator::set_do_cluster_eval (bool b) inline
Definition at line 79 of file CaloEvaluator.h.
View newest version in sPHENIX GitHub at line 79 of file CaloEvaluator.h
References _do_cluster_eval, and KFPMath::b.
Referenced by ZDC_Eval().
void CaloEvaluator::set_do_cluster_eval (bool b) inline
Definition at line 79 of file CaloEvaluator.h.
View newest version in sPHENIX GitHub at line 79 of file CaloEvaluator.h
References _do_cluster_eval, and KFPMath::b.
void CaloEvaluator::set_do_cluster_eval (bool b) inline
Definition at line 86 of file CaloEvaluator.h.
View newest version in sPHENIX GitHub at line 86 of file CaloEvaluator.h
References _do_cluster_eval, and KFPMath::b.
void CaloEvaluator::set_do_gpoint_eval (bool b) inline
Definition at line 76 of file CaloEvaluator.h.
View newest version in sPHENIX GitHub at line 76 of file CaloEvaluator.h
References _do_gpoint_eval, and KFPMath::b.
void CaloEvaluator::set_do_gpoint_eval (bool b) inline
Definition at line 76 of file CaloEvaluator.h.
View newest version in sPHENIX GitHub at line 76 of file CaloEvaluator.h
References _do_gpoint_eval, and KFPMath::b.
void CaloEvaluator::set_do_gpoint_eval (bool b) inline
Definition at line 83 of file CaloEvaluator.h.
View newest version in sPHENIX GitHub at line 83 of file CaloEvaluator.h
References _do_gpoint_eval, and KFPMath::b.
void CaloEvaluator::set_do_gshower_eval (bool b) inline
Definition at line 77 of file CaloEvaluator.h.
View newest version in sPHENIX GitHub at line 77 of file CaloEvaluator.h
References _do_gshower_eval, and KFPMath::b.
void CaloEvaluator::set_do_gshower_eval (bool b) inline
Definition at line 77 of file CaloEvaluator.h.
View newest version in sPHENIX GitHub at line 77 of file CaloEvaluator.h
References _do_gshower_eval, and KFPMath::b.
void CaloEvaluator::set_do_gshower_eval (bool b) inline
Definition at line 84 of file CaloEvaluator.h.
View newest version in sPHENIX GitHub at line 84 of file CaloEvaluator.h
References _do_gshower_eval, and KFPMath::b.
void CaloEvaluator::set_do_tower_eval (bool b) inline
Definition at line 78 of file CaloEvaluator.h.
View newest version in sPHENIX GitHub at line 78 of file CaloEvaluator.h
References _do_tower_eval, and KFPMath::b.
void CaloEvaluator::set_do_tower_eval (bool b) inline
Definition at line 78 of file CaloEvaluator.h.
View newest version in sPHENIX GitHub at line 78 of file CaloEvaluator.h
References _do_tower_eval, and KFPMath::b.
void CaloEvaluator::set_do_tower_eval (bool b) inline
Definition at line 85 of file CaloEvaluator.h.
View newest version in sPHENIX GitHub at line 85 of file CaloEvaluator.h
References _do_tower_eval, and KFPMath::b.
void CaloEvaluator::set_event (int ievent) inline
Definition at line 44 of file CaloEvaluator.h.
View newest version in sPHENIX GitHub at line 44 of file CaloEvaluator.h
References _ievent.
Referenced by HCALInner_Eval(), and HCALOuter_Eval().
void CaloEvaluator::set_reco_tracing_energy_threshold (float thresh) inline
Definition at line 68 of file CaloEvaluator.h.
View newest version in sPHENIX GitHub at line 68 of file CaloEvaluator.h
References _reco_e_threshold.
void CaloEvaluator::set_reco_tracing_energy_threshold (float thresh) inline
Definition at line 68 of file CaloEvaluator.h.
View newest version in sPHENIX GitHub at line 68 of file CaloEvaluator.h
References _reco_e_threshold.
Referenced by Init().
void CaloEvaluator::set_reco_tracing_energy_threshold (float thresh) inline
Definition at line 75 of file CaloEvaluator.h.
View newest version in sPHENIX GitHub at line 75 of file CaloEvaluator.h
References _reco_e_threshold.
void CaloEvaluator::set_strict (bool b) inline
Definition at line 42 of file CaloEvaluator.h.
View newest version in sPHENIX GitHub at line 42 of file CaloEvaluator.h
References _strict, and KFPMath::b.
void CaloEvaluator::set_strict (bool b) inline
Definition at line 42 of file CaloEvaluator.h.
View newest version in sPHENIX GitHub at line 42 of file CaloEvaluator.h
References _strict, and KFPMath::b.
void CaloEvaluator::set_strict (bool b) inline
Definition at line 49 of file CaloEvaluator.h.
View newest version in sPHENIX GitHub at line 49 of file CaloEvaluator.h
References _strict, and KFPMath::b.
void CaloEvaluator::set_truth_tracing_energy_threshold (float thresh) inline
Definition at line 60 of file CaloEvaluator.h.
View newest version in sPHENIX GitHub at line 60 of file CaloEvaluator.h
References _truth_e_threshold.
void CaloEvaluator::set_truth_tracing_energy_threshold (float thresh) inline
Definition at line 60 of file CaloEvaluator.h.
View newest version in sPHENIX GitHub at line 60 of file CaloEvaluator.h
References _truth_e_threshold.
void CaloEvaluator::set_truth_tracing_energy_threshold (float thresh) inline
Definition at line 67 of file CaloEvaluator.h.
View newest version in sPHENIX GitHub at line 67 of file CaloEvaluator.h
References _truth_e_threshold.
Member Data Documentation
CaloEvalStack * CaloEvaluator::_caloevalstack = nullptr private
Definition at line 101 of file CaloEvaluator.h.
View newest version in sPHENIX GitHub at line 101 of file CaloEvaluator.h
Referenced by End(), fillOutputNtuples(), printOutputInfo(), and process_event().
std::string CaloEvaluator::_caloname private
Definition at line 82 of file CaloEvaluator.h.
View newest version in sPHENIX GitHub at line 82 of file CaloEvaluator.h
Referenced by fillOutputNtuples(), and process_event().
TTree * CaloEvaluator::_cluster_tower_info private
Definition at line 121 of file CaloEvaluator.h.
View newest version in sPHENIX GitHub at line 121 of file CaloEvaluator.h
Referenced by End(), fillOutputNtuples(), and Init().
bool CaloEvaluator::_do_cluster_eval = true private
Definition at line 115 of file CaloEvaluator.h.
View newest version in sPHENIX GitHub at line 115 of file CaloEvaluator.h
Referenced by End(), fillOutputNtuples(), Init(), and set_do_cluster_eval().
bool CaloEvaluator::_do_gpoint_eval = true private
Definition at line 112 of file CaloEvaluator.h.
View newest version in sPHENIX GitHub at line 112 of file CaloEvaluator.h
Referenced by End(), fillOutputNtuples(), Init(), and set_do_gpoint_eval().
bool CaloEvaluator::_do_gshower_eval = true private
Definition at line 113 of file CaloEvaluator.h.
View newest version in sPHENIX GitHub at line 113 of file CaloEvaluator.h
Referenced by End(), Init(), and set_do_gshower_eval().
bool CaloEvaluator::_do_tower_eval = true private
Definition at line 114 of file CaloEvaluator.h.
View newest version in sPHENIX GitHub at line 114 of file CaloEvaluator.h
Referenced by End(), fillOutputNtuples(), Init(), and set_do_tower_eval().
float CaloEvaluator::_e_debug = 0. private
Definition at line 92 of file CaloEvaluator.h.
View newest version in sPHENIX GitHub at line 92 of file CaloEvaluator.h
Referenced by fillOutputNtuples(), and Init().
float CaloEvaluator::_eta_debug = 0. private
Definition at line 90 of file CaloEvaluator.h.
View newest version in sPHENIX GitHub at line 90 of file CaloEvaluator.h
Referenced by fillOutputNtuples(), and Init().
std::string CaloEvaluator::_filename private
Definition at line 125 of file CaloEvaluator.h.
View newest version in sPHENIX GitHub at line 125 of file CaloEvaluator.h
Referenced by End(), and Init().
int CaloEvaluator::_ieta_debug = 0 private
Definition at line 88 of file CaloEvaluator.h.
View newest version in sPHENIX GitHub at line 88 of file CaloEvaluator.h
Referenced by fillOutputNtuples(), and Init().
unsigned int CaloEvaluator::_ievent = 0 private
Definition at line 84 of file CaloEvaluator.h.
View newest version in sPHENIX GitHub at line 84 of file CaloEvaluator.h
Referenced by End(), fillOutputNtuples(), Init(), printInputInfo(), printOutputInfo(), process_event(), and set_event().
int CaloEvaluator::_iphi_debug = 0 private
Definition at line 89 of file CaloEvaluator.h.
View newest version in sPHENIX GitHub at line 89 of file CaloEvaluator.h
Referenced by fillOutputNtuples(), and Init().
TNtuple * CaloEvaluator::_ntp_cluster = nullptr private
Definition at line 122 of file CaloEvaluator.h.
View newest version in sPHENIX GitHub at line 122 of file CaloEvaluator.h
Referenced by End(), fillOutputNtuples(), and Init().
TNtuple * CaloEvaluator::_ntp_gpoint = nullptr private
Definition at line 117 of file CaloEvaluator.h.
View newest version in sPHENIX GitHub at line 117 of file CaloEvaluator.h
Referenced by End(), fillOutputNtuples(), and Init().
TNtuple * CaloEvaluator::_ntp_gshower = nullptr private
Definition at line 118 of file CaloEvaluator.h.
View newest version in sPHENIX GitHub at line 118 of file CaloEvaluator.h
Referenced by End(), fillOutputNtuples(), and Init().
TNtuple * CaloEvaluator::_ntp_tower = nullptr private
Definition at line 119 of file CaloEvaluator.h.
View newest version in sPHENIX GitHub at line 119 of file CaloEvaluator.h
Referenced by End(), fillOutputNtuples(), and Init().
float CaloEvaluator::_phi_debug = 0. private
Definition at line 91 of file CaloEvaluator.h.
View newest version in sPHENIX GitHub at line 91 of file CaloEvaluator.h
Referenced by fillOutputNtuples(), and Init().
float CaloEvaluator::_reco_e_threshold = 0. private
Definition at line 99 of file CaloEvaluator.h.
View newest version in sPHENIX GitHub at line 99 of file CaloEvaluator.h
Referenced by fillOutputNtuples(), and set_reco_tracing_energy_threshold().
bool CaloEvaluator::_strict = false private
Definition at line 110 of file CaloEvaluator.h.
View newest version in sPHENIX GitHub at line 110 of file CaloEvaluator.h
Referenced by process_event(), and set_strict().
TFile * CaloEvaluator::_tfile = nullptr private
Definition at line 126 of file CaloEvaluator.h.
View newest version in sPHENIX GitHub at line 126 of file CaloEvaluator.h
Referenced by End(), and Init().
TTree * CaloEvaluator::_tower_debug = nullptr private
Definition at line 120 of file CaloEvaluator.h.
View newest version in sPHENIX GitHub at line 120 of file CaloEvaluator.h
Referenced by End(), fillOutputNtuples(), and Init().
std::vector< float > CaloEvaluator::_towerEnergies private
Definition at line 105 of file CaloEvaluator.h.
View newest version in sPHENIX GitHub at line 105 of file CaloEvaluator.h
Referenced by fillOutputNtuples(), and Init().
std::vector< unsigned char > CaloEvaluator::_towerEtas private
Definition at line 103 of file CaloEvaluator.h.
View newest version in sPHENIX GitHub at line 103 of file CaloEvaluator.h
Referenced by fillOutputNtuples(), and Init().
unsigned int CaloEvaluator::_towerID_debug = 0 private
Definition at line 87 of file CaloEvaluator.h.
View newest version in sPHENIX GitHub at line 87 of file CaloEvaluator.h
Referenced by fillOutputNtuples(), and Init().
std::vector< unsigned char > CaloEvaluator::_towerPhis private
Definition at line 104 of file CaloEvaluator.h.
View newest version in sPHENIX GitHub at line 104 of file CaloEvaluator.h
Referenced by fillOutputNtuples(), and Init().
float CaloEvaluator::_truth_e_threshold = 0. private
Definition at line 98 of file CaloEvaluator.h.
View newest version in sPHENIX GitHub at line 98 of file CaloEvaluator.h
Referenced by fillOutputNtuples(), and set_truth_tracing_energy_threshold().
std::set< int > CaloEvaluator::_truth_trace_embed_flags private
Definition at line 97 of file CaloEvaluator.h.
View newest version in sPHENIX GitHub at line 97 of file CaloEvaluator.h
Referenced by add_truth_tracing_embed_flag(), and fillOutputNtuples().
float CaloEvaluator::_x_debug = 0. private
Definition at line 93 of file CaloEvaluator.h.
View newest version in sPHENIX GitHub at line 93 of file CaloEvaluator.h
Referenced by fillOutputNtuples(), and Init().
float CaloEvaluator::_y_debug = 0. private
Definition at line 94 of file CaloEvaluator.h.
View newest version in sPHENIX GitHub at line 94 of file CaloEvaluator.h
Referenced by fillOutputNtuples(), and Init().
float CaloEvaluator::_z_debug = 0. private
Definition at line 95 of file CaloEvaluator.h.
View newest version in sPHENIX GitHub at line 95 of file CaloEvaluator.h
Referenced by fillOutputNtuples(), and Init().
unsigned int CaloEvaluator::m_EvtCounter = 0 private
Definition at line 104 of file CaloEvaluator.h.
View newest version in sPHENIX GitHub at line 104 of file CaloEvaluator.h
The documentation for this class was generated from the following files:
analysis/blob/master/EMCal-position-dependent-calibration/src/ana.354/CaloEvaluator.h
analysis/blob/master/EMCal-position-dependent-calibration/src/ana.357/CaloEvaluator.h
coresoftware/blob/master/simulation/g4simulation/g4eval/CaloEvaluator.h
analysis/blob/master/EMCal-position-dependent-calibration/src/ana.354/CaloEvaluator.cc
analysis/blob/master/EMCal-position-dependent-calibration/src/ana.357/CaloEvaluator.cc
coresoftware/blob/master/simulation/g4simulation/g4eval/CaloEvaluator.cc