Analysis Software: ActsExamples::DuplicationPlotTool Class Reference
ActsExamples::DuplicationPlotTool Class Reference
#include <acts/blob/sPHENIX/Examples/Framework/include/ActsExamples/Validation/DuplicationPlotTool.hpp>
Classes
struct Config
The nested configuration struct.
struct DuplicationPlotCache
Nested Cache struct.
Public Member Functions
DuplicationPlotTool (const Config &cfg, Acts::Logging::Level lvl)
void book (DuplicationPlotCache &duplicationPlotCache) const
book the duplication plots
void fill (DuplicationPlotCache &duplicationPlotCache, const Acts::BoundTrackParameters &fittedParameters, bool status) const
fill duplication rate w.r.t. fitted track parameters
void fill (DuplicationPlotCache &duplicationPlotCache, const ActsFatras::Particle &truthParticle, size_t nDuplicatedTracks) const
fill number of duplicated tracks for a truth particle seed
void write (const DuplicationPlotCache &duplicationPlotCache) const
write the duplication plots to file
void clear (DuplicationPlotCache &duplicationPlotCache) const
delete the duplication plots
Private Member Functions
const Acts::Logger & logger () const
The logger.
Private Attributes
Config m_cfg
The Config class.
std::unique_ptr< const
Acts::Logger > m_logger
The logging instance.
Detailed Description
Definition at line 36 of file DuplicationPlotTool.hpp.
View newest version in sPHENIX GitHub at line 36 of file DuplicationPlotTool.hpp
Constructor & Destructor Documentation
ActsExamples::DuplicationPlotTool::DuplicationPlotTool (const Config & cfg, Acts::Logging::Level lvl)
Constructor
Parameters
cfg Configuration struct
lvl Message level declaration
Definition at line 23 of file DuplicationPlotTool.cpp.
View newest version in sPHENIX GitHub at line 23 of file DuplicationPlotTool.cpp
Member Function Documentation
void ActsExamples::DuplicationPlotTool::book (DuplicationPlotTool::DuplicationPlotCache & duplicationPlotCache) const
book the duplication plots
Parameters
duplicationPlotCache the cache for duplication plots
Definition at line 29 of file DuplicationPlotTool.cpp.
View newest version in sPHENIX GitHub at line 29 of file DuplicationPlotTool.cpp
References ACTS_DEBUG, ActsExamples::PlotHelpers::bookEff(), ActsExamples::PlotHelpers::bookProf(), ActsExamples::DuplicationPlotTool::DuplicationPlotCache::duplicationRate_vs_eta, ActsExamples::DuplicationPlotTool::DuplicationPlotCache::duplicationRate_vs_phi, ActsExamples::DuplicationPlotTool::DuplicationPlotCache::duplicationRate_vs_pT, m_cfg(), ActsExamples::DuplicationPlotTool::DuplicationPlotCache::nDuplicated_vs_eta, ActsExamples::DuplicationPlotTool::DuplicationPlotCache::nDuplicated_vs_phi, and ActsExamples::DuplicationPlotTool::DuplicationPlotCache::nDuplicated_vs_pT.
Referenced by ActsExamples::CKFPerformanceWriter::CKFPerformanceWriter(), and ActsExamples::SeedingPerformanceWriter::SeedingPerformanceWriter().
void ActsExamples::DuplicationPlotTool::clear (DuplicationPlotCache & duplicationPlotCache) const
delete the duplication plots
Parameters
duplicationPlotCache cache object for duplication plots
Definition at line 61 of file DuplicationPlotTool.cpp.
View newest version in sPHENIX GitHub at line 61 of file DuplicationPlotTool.cpp
References ActsExamples::DuplicationPlotTool::DuplicationPlotCache::duplicationRate_vs_eta, ActsExamples::DuplicationPlotTool::DuplicationPlotCache::duplicationRate_vs_phi, ActsExamples::DuplicationPlotTool::DuplicationPlotCache::duplicationRate_vs_pT, ActsExamples::DuplicationPlotTool::DuplicationPlotCache::nDuplicated_vs_eta, ActsExamples::DuplicationPlotTool::DuplicationPlotCache::nDuplicated_vs_phi, and ActsExamples::DuplicationPlotTool::DuplicationPlotCache::nDuplicated_vs_pT.
void ActsExamples::DuplicationPlotTool::fill (DuplicationPlotTool::DuplicationPlotCache & duplicationPlotCache, const Acts::BoundTrackParameters & fittedParameters, bool status) const
fill duplication rate w.r.t. fitted track parameters
Parameters
duplicationPlotCache cache object for duplication plots
fittedParameters fitted track parameters of this track
status the (truth-matched) reconstructed track is duplicated or not
Definition at line 83 of file DuplicationPlotTool.cpp.
View newest version in sPHENIX GitHub at line 83 of file DuplicationPlotTool.cpp
References ActsExamples::DuplicationPlotTool::DuplicationPlotCache::duplicationRate_vs_eta, ActsExamples::DuplicationPlotTool::DuplicationPlotCache::duplicationRate_vs_phi, ActsExamples::DuplicationPlotTool::DuplicationPlotCache::duplicationRate_vs_pT, eta, ActsExamples::PlotHelpers::fillEff(), momentum, Acts::GenericBoundTrackParameters< particle_hypothesis_t >::momentum(), Acts::VectorHelpers::perp(), and ActsTests::PropagationDatasets::phi.
void ActsExamples::DuplicationPlotTool::fill (DuplicationPlotTool::DuplicationPlotCache & duplicationPlotCache, const ActsFatras::Particle & truthParticle, size_t nDuplicatedTracks) const
fill number of duplicated tracks for a truth particle seed
Parameters
duplicationPlotCache cache object for duplication plots
truthParticle the truth Particle
nDuplicatedTracks the number of duplicated tracks
Definition at line 99 of file DuplicationPlotTool.cpp.
View newest version in sPHENIX GitHub at line 99 of file DuplicationPlotTool.cpp
References ActsFatras::Particle::direction(), eta, ActsExamples::PlotHelpers::fillProf(), ActsExamples::DuplicationPlotTool::DuplicationPlotCache::nDuplicated_vs_eta, ActsExamples::DuplicationPlotTool::DuplicationPlotCache::nDuplicated_vs_phi, ActsExamples::DuplicationPlotTool::DuplicationPlotCache::nDuplicated_vs_pT, ActsTests::PropagationDatasets::phi, and ActsFatras::Particle::transverseMomentum().
const Acts::Logger& ActsExamples::DuplicationPlotTool::logger () const inline private
The logger.
Definition at line 101 of file DuplicationPlotTool.hpp.
View newest version in sPHENIX GitHub at line 101 of file DuplicationPlotTool.hpp
References m_logger.
void ActsExamples::DuplicationPlotTool::write (const DuplicationPlotCache & duplicationPlotCache) const
write the duplication plots to file
Parameters
duplicationPlotCache cache object for duplication plots
Definition at line 71 of file DuplicationPlotTool.cpp.
View newest version in sPHENIX GitHub at line 71 of file DuplicationPlotTool.cpp
References ACTS_DEBUG, ActsExamples::DuplicationPlotTool::DuplicationPlotCache::duplicationRate_vs_eta, ActsExamples::DuplicationPlotTool::DuplicationPlotCache::duplicationRate_vs_phi, ActsExamples::DuplicationPlotTool::DuplicationPlotCache::duplicationRate_vs_pT, ActsExamples::DuplicationPlotTool::DuplicationPlotCache::nDuplicated_vs_eta, ActsExamples::DuplicationPlotTool::DuplicationPlotCache::nDuplicated_vs_phi, and ActsExamples::DuplicationPlotTool::DuplicationPlotCache::nDuplicated_vs_pT.
Member Data Documentation
Config ActsExamples::DuplicationPlotTool::m_cfg private
The Config class.
Definition at line 97 of file DuplicationPlotTool.hpp.
View newest version in sPHENIX GitHub at line 97 of file DuplicationPlotTool.hpp
std::unique_ptr<const Acts::Logger> ActsExamples::DuplicationPlotTool::m_logger private
The logging instance.
Definition at line 98 of file DuplicationPlotTool.hpp.
View newest version in sPHENIX GitHub at line 98 of file DuplicationPlotTool.hpp
Referenced by logger().
The documentation for this class was generated from the following files:
acts/blob/sPHENIX/Examples/Framework/include/ActsExamples/Validation/DuplicationPlotTool.hpp
acts/blob/sPHENIX/Examples/Framework/src/Validation/DuplicationPlotTool.cpp