Analysis Software: prototype/blob/master/macros/tpc2019/ConstructGeometry.C File Reference
ConstructGeometry.C File Reference
#include <fun4all/Fun4AllDstOutputManager.h>
#include <fun4all/Fun4AllDummyInputManager.h>
#include <fun4all/Fun4AllInputManager.h>
#include <fun4all/Fun4AllOutputManager.h>
#include <fun4all/Fun4AllServer.h>
#include <fun4all/SubsysReco.h>
#include <g4eval/SvtxEvaluator.h>
#include <g4eval/TrkrEvaluator.h>
#include <g4detectors/PHG4BlockSubsystem.h>
#include <g4detectors/PHG4CylinderSubsystem.h>
#include <g4main/PHG4Reco.h>
#include <g4eval/PHG4DSTReader.h>
#include <g4histos/G4HitNtuple.h>
#include <g4main/PHG4ParticleGenerator.h>
#include <g4main/PHG4ParticleGun.h>
#include <g4main/PHG4SimpleEventGenerator.h>
#include <g4main/PHG4TruthSubsystem.h>
#include <phgeom/PHGeomUtility.h>
#include <phool/recoConsts.h>
#include <TMath.h>
#include <TSystem.h>
Functions
void ConstructGeometry ()
Detailed Description
Author
Jin Huang jhuan.nosp@m.g@bn.nosp@m.l.gov
Version
Revision:
Date
Date:
Definition in file ConstructGeometry.C.
Function Documentation
void ConstructGeometry ()
Definition at line 60 of file ConstructGeometry.C.
View newest version in sPHENIX GitHub at line 60 of file ConstructGeometry.C
References PHG4SimpleEventGenerator::add_particles(), PHG4Reco::ApplyCommand(), PHG4Reco::ApplyDisplayAction(), runCondor_beamspot::cmd, Acts::UnitConstants::e, eta, PHGeomUtility::ExportGeomtry(), PHG4SimpleEventGenerator::Gaus, gen(), i, in, PHG4Reco::InitRun(), recoConsts::instance(), Fun4AllServer::instance(), testing::internal::Log(), momentum, PHG4DetectorSubsystem::OverlapCheck(), ActsTests::PropagationDatasets::phi, Fun4AllServer::registerInputManager(), Fun4AllServer::registerSubsystem(), PHG4Reco::registerSubsystem(), Fun4AllServer::run(), PHG4DetectorSubsystem::set_double_param(), PHG4SimpleEventGenerator::set_eta_range(), PHG4Reco::set_field(), PHG4DetectorSubsystem::set_int_param(), PHG4SimpleEventGenerator::set_p_range(), PHG4SimpleEventGenerator::set_phi_range(), PHG4DetectorSubsystem::set_string_param(), PHG4SimpleEventGenerator::set_vertex_distribution_function(), PHG4SimpleEventGenerator::set_vertex_distribution_mean(), PHG4SimpleEventGenerator::set_vertex_distribution_width(), PHG4DetectorSubsystem::SetActive(), sign(), PHG4DetectorSubsystem::SuperDetector(), ActsTests::PropagationDatasets::theta, Fun4AllServer::topNode(), and Fun4AllBase::Verbosity().