Analysis Software: IC Class Reference
IC Class Reference
#include <JETSCAPE/blob/main/jail/vhlle/src/ic.h>
Public Member Functions
IC (char *icInputFile, double s0ScaleFactor)
~IC (void)
void setIC (Fluid *f, EoS *eos, double tau)
Detailed Description
Definition at line 6 of file ic.h.
View newest version in sPHENIX GitHub at line 6 of file ic.h
Constructor & Destructor Documentation
IC::IC (char * icInputFile, double s0ScaleFactor)
Definition at line 17 of file ic.cpp.
View newest version in sPHENIX GitHub at line 17 of file ic.cpp
References s95p::loadSongIC().
IC::~IC (void)
Definition at line 22 of file ic.cpp.
View newest version in sPHENIX GitHub at line 22 of file ic.cpp
Member Function Documentation
void IC::setIC (Fluid * f, EoS * eos, double tau)
Definition at line 25 of file ic.cpp.
View newest version in sPHENIX GitHub at line 25 of file ic.cpp
References Acts::PhysicalConstants::c, Acts::UnitConstants::e, eta, Fluid::getCell(), Fluid::getDx(), Fluid::getDy(), Fluid::getDz(), Fluid::getNX(), Fluid::getNY(), Fluid::getNZ(), s95p::getSongEps(), Fluid::getX(), Fluid::getY(), Fluid::getZ(), EoS::p(), Cell::saveQprev(), Cell::setAllM(), Cell::setPrimVar(), vx, vy, vz, ambiguity_solver_full_chain::x, and y.
Referenced by main().
The documentation for this class was generated from the following files:
JETSCAPE/blob/main/jail/vhlle/src/ic.h
JETSCAPE/blob/main/jail/vhlle/src/ic.cpp