Analysis Software: tinyxml2::XMLAttribute Class Reference
tinyxml2::XMLAttribute Class Reference
#include <JETSCAPE/blob/main/external_packages/tinyxml2.h>
Public Member Functions
const char * Name () const
The name of the attribute.
const char * Value () const
The value of the attribute.
const XMLAttribute * Next () const
The next attribute in the list.
int IntValue () const
int64_t Int64Value () const
unsigned UnsignedValue () const
Query as an unsigned integer. See IntValue()
bool BoolValue () const
Query as a boolean. See IntValue()
double DoubleValue () const
Query as a double. See IntValue()
float FloatValue () const
Query as a float. See IntValue()
XMLError QueryIntValue (int *value) const
XMLError QueryUnsignedValue (unsigned int *value) const
See QueryIntValue.
XMLError QueryInt64Value (int64_t *value) const
See QueryIntValue.
XMLError QueryBoolValue (bool *value) const
See QueryIntValue.
XMLError QueryDoubleValue (double *value) const
See QueryIntValue.
XMLError QueryFloatValue (float *value) const
See QueryIntValue.
void SetAttribute (const char *value)
Set the attribute to a string value.
void SetAttribute (int value)
Set the attribute to value.
void SetAttribute (unsigned value)
Set the attribute to value.
void SetAttribute (int64_t value)
Set the attribute to value.
void SetAttribute (bool value)
Set the attribute to value.
void SetAttribute (double value)
Set the attribute to value.
void SetAttribute (float value)
Set the attribute to value.
Private Types
enum { BUF_SIZE = 200 }
Private Member Functions
XMLAttribute ()
virtual ~XMLAttribute ()
XMLAttribute (const XMLAttribute &)
void operator= (const XMLAttribute &)
void SetName (const char *name)
char * ParseDeep (char *p, bool processEntities)
Private Attributes
StrPair _name
StrPair _value
XMLAttribute * _next
MemPool * _memPool
Friends
class XMLElement
Detailed Description
An attribute is a name-value pair. Elements have an arbitrary number of attributes, each with a unique name.
Note
The attributes are not XMLNodes. You may only query the Next() attribute in a list.
Definition at line 1079 of file tinyxml2.h.
View newest version in sPHENIX GitHub at line 1079 of file tinyxml2.h
Member Enumeration Documentation
anonymous enum private
Enumerator:
BUF_SIZE
Definition at line 1167 of file tinyxml2.h.
View newest version in sPHENIX GitHub at line 1167 of file tinyxml2.h
Constructor & Destructor Documentation
tinyxml2::XMLAttribute::XMLAttribute () inline private
Definition at line 1169 of file tinyxml2.h.
View newest version in sPHENIX GitHub at line 1169 of file tinyxml2.h
virtual tinyxml2::XMLAttribute::~XMLAttribute () inline private virtual
Definition at line 1170 of file tinyxml2.h.
View newest version in sPHENIX GitHub at line 1170 of file tinyxml2.h
Referenced by tinyxml2::XMLElement::DeleteAttribute().
tinyxml2::XMLAttribute::XMLAttribute (const XMLAttribute &) private
Member Function Documentation
bool tinyxml2::XMLAttribute::BoolValue () const inline
Query as a boolean. See IntValue()
Definition at line 1117 of file tinyxml2.h.
View newest version in sPHENIX GitHub at line 1117 of file tinyxml2.h
References KFPMath::b.
double tinyxml2::XMLAttribute::DoubleValue () const inline
Query as a double. See IntValue()
Definition at line 1123 of file tinyxml2.h.
View newest version in sPHENIX GitHub at line 1123 of file tinyxml2.h
float tinyxml2::XMLAttribute::FloatValue () const inline
Query as a float. See IntValue()
Definition at line 1129 of file tinyxml2.h.
View newest version in sPHENIX GitHub at line 1129 of file tinyxml2.h
References f.
int64_t tinyxml2::XMLAttribute::Int64Value () const inline
Definition at line 1104 of file tinyxml2.h.
View newest version in sPHENIX GitHub at line 1104 of file tinyxml2.h
References i.
int tinyxml2::XMLAttribute::IntValue () const inline
IntValue interprets the attribute as an integer, and returns the value. If the value isn't an integer, 0 will be returned. There is no error checking; use QueryIntValue() if you need error checking.
Definition at line 1098 of file tinyxml2.h.
View newest version in sPHENIX GitHub at line 1098 of file tinyxml2.h
References i.
const char * tinyxml2::XMLAttribute::Name () const
The name of the attribute.
Definition at line 1283 of file tinyxml2.cc.
View newest version in sPHENIX GitHub at line 1283 of file tinyxml2.cc
References _name, and tinyxml2::StrPair::GetStr().
Referenced by tinyxml2::XMLElement::ParseAttributes(), and tinyxml2::XMLPrinter::VisitEnter().
const XMLAttribute* tinyxml2::XMLAttribute::Next () const inline
The next attribute in the list.
Definition at line 1090 of file tinyxml2.h.
View newest version in sPHENIX GitHub at line 1090 of file tinyxml2.h
Referenced by tinyxml2::XMLElement::ShallowEqual(), and tinyxml2::XMLPrinter::VisitEnter().
void tinyxml2::XMLAttribute::operator= (const XMLAttribute &) private
char * tinyxml2::XMLAttribute::ParseDeep (char * p, bool processEntities) private
Definition at line 1293 of file tinyxml2.cc.
View newest version in sPHENIX GitHub at line 1293 of file tinyxml2.cc
References _name, _value, tinyxml2::StrPair::ATTRIBUTE_VALUE, tinyxml2::StrPair::ATTRIBUTE_VALUE_LEAVE_ENTITIES, merge_hashes::p, tinyxml2::StrPair::ParseName(), tinyxml2::StrPair::ParseText(), and tinyxml2::XMLUtil::SkipWhiteSpace().
Referenced by tinyxml2::XMLElement::ParseAttributes().
XMLError tinyxml2::XMLAttribute::QueryBoolValue (bool * value) const
See QueryIntValue.
Definition at line 1354 of file tinyxml2.cc.
View newest version in sPHENIX GitHub at line 1354 of file tinyxml2.cc
References tinyxml2::XMLUtil::ToBool(), Value(), tinyxml2::XML_SUCCESS, and tinyxml2::XML_WRONG_ATTRIBUTE_TYPE.
Referenced by tinyxml2::XMLElement::QueryBoolAttribute().
XMLError tinyxml2::XMLAttribute::QueryDoubleValue (double * value) const
See QueryIntValue.
Definition at line 1372 of file tinyxml2.cc.
View newest version in sPHENIX GitHub at line 1372 of file tinyxml2.cc
References tinyxml2::XMLUtil::ToDouble(), Value(), tinyxml2::XML_SUCCESS, and tinyxml2::XML_WRONG_ATTRIBUTE_TYPE.
Referenced by tinyxml2::XMLElement::QueryDoubleAttribute().
XMLError tinyxml2::XMLAttribute::QueryFloatValue (float * value) const
See QueryIntValue.
Definition at line 1363 of file tinyxml2.cc.
View newest version in sPHENIX GitHub at line 1363 of file tinyxml2.cc
References tinyxml2::XMLUtil::ToFloat(), Value(), tinyxml2::XML_SUCCESS, and tinyxml2::XML_WRONG_ATTRIBUTE_TYPE.
Referenced by tinyxml2::XMLElement::QueryFloatAttribute().
XMLError tinyxml2::XMLAttribute::QueryInt64Value (int64_t * value) const
See QueryIntValue.
Definition at line 1345 of file tinyxml2.cc.
View newest version in sPHENIX GitHub at line 1345 of file tinyxml2.cc
References tinyxml2::XMLUtil::ToInt64(), Value(), tinyxml2::XML_SUCCESS, and tinyxml2::XML_WRONG_ATTRIBUTE_TYPE.
Referenced by tinyxml2::XMLElement::QueryInt64Attribute().
XMLError tinyxml2::XMLAttribute::QueryIntValue (int * value) const
QueryIntValue interprets the attribute as an integer, and returns the value in the provided parameter. The function will return XML_SUCCESS on success, and XML_WRONG_ATTRIBUTE_TYPE if the conversion is not successful.
Definition at line 1327 of file tinyxml2.cc.
View newest version in sPHENIX GitHub at line 1327 of file tinyxml2.cc
References tinyxml2::XMLUtil::ToInt(), Value(), tinyxml2::XML_SUCCESS, and tinyxml2::XML_WRONG_ATTRIBUTE_TYPE.
Referenced by tinyxml2::XMLElement::QueryIntAttribute().
XMLError tinyxml2::XMLAttribute::QueryUnsignedValue (unsigned int * value) const
See QueryIntValue.
Definition at line 1336 of file tinyxml2.cc.
View newest version in sPHENIX GitHub at line 1336 of file tinyxml2.cc
References tinyxml2::XMLUtil::ToUnsigned(), Value(), tinyxml2::XML_SUCCESS, and tinyxml2::XML_WRONG_ATTRIBUTE_TYPE.
Referenced by tinyxml2::XMLElement::QueryUnsignedAttribute().
void tinyxml2::XMLAttribute::SetAttribute (const char * value)
Set the attribute to a string value.
Definition at line 1381 of file tinyxml2.cc.
View newest version in sPHENIX GitHub at line 1381 of file tinyxml2.cc
References _value, and tinyxml2::StrPair::SetStr().
Referenced by tinyxml2::XMLElement::SetAttribute().
void tinyxml2::XMLAttribute::SetAttribute (int value)
Set the attribute to value.
Definition at line 1387 of file tinyxml2.cc.
View newest version in sPHENIX GitHub at line 1387 of file tinyxml2.cc
References _value, BUF_SIZE, tinyxml2::StrPair::SetStr(), and tinyxml2::XMLUtil::ToStr().
void tinyxml2::XMLAttribute::SetAttribute (unsigned value)
Set the attribute to value.
Definition at line 1395 of file tinyxml2.cc.
View newest version in sPHENIX GitHub at line 1395 of file tinyxml2.cc
References _value, BUF_SIZE, tinyxml2::StrPair::SetStr(), and tinyxml2::XMLUtil::ToStr().
void tinyxml2::XMLAttribute::SetAttribute (int64_t value)
Set the attribute to value.
Definition at line 1403 of file tinyxml2.cc.
View newest version in sPHENIX GitHub at line 1403 of file tinyxml2.cc
References _value, BUF_SIZE, tinyxml2::StrPair::SetStr(), and tinyxml2::XMLUtil::ToStr().
void tinyxml2::XMLAttribute::SetAttribute (bool value)
Set the attribute to value.
Definition at line 1412 of file tinyxml2.cc.
View newest version in sPHENIX GitHub at line 1412 of file tinyxml2.cc
References _value, BUF_SIZE, tinyxml2::StrPair::SetStr(), and tinyxml2::XMLUtil::ToStr().
void tinyxml2::XMLAttribute::SetAttribute (double value)
Set the attribute to value.
Definition at line 1419 of file tinyxml2.cc.
View newest version in sPHENIX GitHub at line 1419 of file tinyxml2.cc
References _value, BUF_SIZE, tinyxml2::StrPair::SetStr(), and tinyxml2::XMLUtil::ToStr().
void tinyxml2::XMLAttribute::SetAttribute (float value)
Set the attribute to value.
Definition at line 1426 of file tinyxml2.cc.
View newest version in sPHENIX GitHub at line 1426 of file tinyxml2.cc
References _value, BUF_SIZE, tinyxml2::StrPair::SetStr(), and tinyxml2::XMLUtil::ToStr().
void tinyxml2::XMLAttribute::SetName (const char * name) private
Definition at line 1321 of file tinyxml2.cc.
View newest version in sPHENIX GitHub at line 1321 of file tinyxml2.cc
References _name, and tinyxml2::StrPair::SetStr().
Referenced by tinyxml2::XMLElement::FindOrCreateAttribute().
unsigned tinyxml2::XMLAttribute::UnsignedValue () const inline
Query as an unsigned integer. See IntValue()
Definition at line 1111 of file tinyxml2.h.
View newest version in sPHENIX GitHub at line 1111 of file tinyxml2.h
References i.
const char * tinyxml2::XMLAttribute::Value () const
The value of the attribute.
Definition at line 1288 of file tinyxml2.cc.
View newest version in sPHENIX GitHub at line 1288 of file tinyxml2.cc
References _value, and tinyxml2::StrPair::GetStr().
Referenced by tinyxml2::XMLElement::Attribute(), QueryBoolValue(), QueryDoubleValue(), QueryFloatValue(), QueryInt64Value(), QueryIntValue(), QueryUnsignedValue(), tinyxml2::XMLElement::ShallowEqual(), and tinyxml2::XMLPrinter::VisitEnter().
Friends And Related Function Documentation
friend class XMLElement friend
Definition at line 1081 of file tinyxml2.h.
View newest version in sPHENIX GitHub at line 1081 of file tinyxml2.h
Member Data Documentation
MemPool* tinyxml2::XMLAttribute::_memPool private
Definition at line 1181 of file tinyxml2.h.
View newest version in sPHENIX GitHub at line 1181 of file tinyxml2.h
Referenced by tinyxml2::XMLElement::CreateAttribute(), and tinyxml2::XMLElement::DeleteAttribute().
StrPair tinyxml2::XMLAttribute::_name mutable private
Definition at line 1178 of file tinyxml2.h.
View newest version in sPHENIX GitHub at line 1178 of file tinyxml2.h
Referenced by Name(), ParseDeep(), and SetName().
XMLAttribute* tinyxml2::XMLAttribute::_next private
Definition at line 1180 of file tinyxml2.h.
View newest version in sPHENIX GitHub at line 1180 of file tinyxml2.h
Referenced by tinyxml2::XMLElement::DeleteAttribute(), tinyxml2::XMLElement::FindOrCreateAttribute(), tinyxml2::XMLElement::ParseAttributes(), and tinyxml2::XMLElement::~XMLElement().
StrPair tinyxml2::XMLAttribute::_value mutable private
Definition at line 1179 of file tinyxml2.h.
View newest version in sPHENIX GitHub at line 1179 of file tinyxml2.h
Referenced by ParseDeep(), SetAttribute(), and Value().
The documentation for this class was generated from the following files:
JETSCAPE/blob/main/external_packages/tinyxml2.h
JETSCAPE/blob/main/external_packages/tinyxml2.cc