Analysis Software: TrkrNtuplizer Class Reference
TrkrNtuplizer Class Reference
#include <coresoftware/blob/master/offline/packages/TrackingDiagnostics/TrkrNtuplizer.h>
Public Member Functions
TrkrNtuplizer (const std::string &name="TRKRNTUPLEIZER", const std::string &filename="trkrntuple.root", const std::string &trackmapname="SvtxTrackMap", unsigned int nlayers_maps=3, unsigned int nlayers_intt=8, unsigned int nlayers_tpc=48, unsigned int nlayers_mms=2)
~TrkrNtuplizer () override
int Init (PHCompositeNode *topNode) override
int InitRun (PHCompositeNode *topNode) override
int process_event (PHCompositeNode *topNode) override
int End (PHCompositeNode *topNode) override
Called at the end of all processing.
void do_info_eval (bool b)
void do_vertex_eval (bool b)
void do_hit_eval (bool b)
void do_cluster_eval (bool b)
void do_clus_trk_eval (bool b)
void do_track_eval (bool b)
void do_tpcseed_eval (bool b)
void do_siseed_eval (bool b)
void set_first_event (int value)
void set_trkclus_seed_container (const std::string &name)
SvtxTrack * best_track_from (TrkrDefs::cluskey cluster_key)
std::set< SvtxTrack * > all_tracks_from (TrkrDefs::cluskey cluster_key)
void create_cache_track_from_cluster ()
std::vector< TrkrDefs::cluskey > get_track_ckeys (SvtxTrack *track)
Public Member Functions inherited from SubsysReco
~SubsysReco () override
virtual int EndRun (const int)
Called at the end of each run.
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
void Print (const std::string &="ALL") const override
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Private Member Functions
TMatrixF calculateClusterError (TrkrCluster *c, float &clusphi)
void get_dca (SvtxTrack *track, SvtxVertexMap *vertexmap, float &dca3dxy, float &dca3dz, float &dca3dxysigma, float &dca3dzsigma)
void fillOutputNtuples (PHCompositeNode *topNode)
dump the evaluator information into ntuple for external analysis
void printInputInfo (PHCompositeNode *topNode)
print out the input object information (debugging upstream components)
void printOutputInfo (PHCompositeNode *topNode)
print out the ancestry information for detailed diagnosis
Private Attributes
unsigned int _ievent
unsigned int _iseed
float m_fSeed
bool _do_info_eval
bool _do_vertex_eval
bool _do_hit_eval
bool _do_cluster_eval
bool _do_clus_trk_eval
bool _do_track_eval
bool _do_tpcseed_eval
bool _do_siseed_eval
unsigned int _nlayers_maps = 3
unsigned int _nlayers_intt = 4
unsigned int _nlayers_tpc = 48
unsigned int _nlayers_mms = 2
TNtuple * _ntp_info
TNtuple * _ntp_vertex
TNtuple * _ntp_hit
TNtuple * _ntp_cluster
TNtuple * _ntp_clus_trk
TNtuple * _ntp_track
TNtuple * _ntp_tpcseed
TNtuple * _ntp_siseed
std::string _filename
std::string _trackmapname
SvtxTrackMap * _trackmap = nullptr
std::string _clustrackseedcontainer = "TpcTrackSeedContainer"
TFile * _tfile
PHTimer * _timer
double AdcClockPeriod = 53.0
bool _cache_track_from_cluster_exists = false
std::map< TrkrDefs::cluskey,
std::set< SvtxTrack * > > _cache_all_tracks_from_cluster
std::map< TrkrDefs::cluskey,
SvtxTrack * > _cache_best_track_from_cluster
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = std::numeric_limits<int>::max() - 10
}
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Detailed Description
Definition at line 39 of file TrkrNtuplizer.h.
View newest version in sPHENIX GitHub at line 39 of file TrkrNtuplizer.h
Constructor & Destructor Documentation
TrkrNtuplizer::TrkrNtuplizer (const std::string & name = "TRKRNTUPLEIZER", const std::string & filename = "trkrntuple.root", const std::string & trackmapname = "SvtxTrackMap", unsigned int nlayers_maps = 3, unsigned int nlayers_intt = 8, unsigned int nlayers_tpc = 48, unsigned int nlayers_mms = 2)
Definition at line 59 of file TrkrNtuplizer.cc.
View newest version in sPHENIX GitHub at line 59 of file TrkrNtuplizer.cc
TrkrNtuplizer::~TrkrNtuplizer () override
Definition at line 95 of file TrkrNtuplizer.cc.
View newest version in sPHENIX GitHub at line 95 of file TrkrNtuplizer.cc
References _timer.
Member Function Documentation
std::set< SvtxTrack * > TrkrNtuplizer::all_tracks_from (TrkrDefs::cluskey cluster_key)
Definition at line 1747 of file TrkrNtuplizer.cc.
View newest version in sPHENIX GitHub at line 1747 of file TrkrNtuplizer.cc
References _cache_all_tracks_from_cluster, _cache_track_from_cluster_exists, _trackmap, SvtxTrackMap::begin(), create_cache_track_from_cluster(), SvtxTrackMap::end(), get_track_ckeys(), and tracks().
Referenced by best_track_from().
SvtxTrack * TrkrNtuplizer::best_track_from (TrkrDefs::cluskey cluster_key)
Definition at line 1717 of file TrkrNtuplizer.cc.
View newest version in sPHENIX GitHub at line 1717 of file TrkrNtuplizer.cc
References _cache_best_track_from_cluster, all_tracks_from(), SvtxTrack::get_quality(), and tracks().
TMatrixF TrkrNtuplizer::calculateClusterError (TrkrCluster * c, float & clusphi) private
Definition at line 1833 of file TrkrNtuplizer.cc.
View newest version in sPHENIX GitHub at line 1833 of file TrkrNtuplizer.cc
References check_license::err(), and TrkrCluster::getActsLocalError().
void TrkrNtuplizer::create_cache_track_from_cluster ()
Definition at line 1797 of file TrkrNtuplizer.cc.
View newest version in sPHENIX GitHub at line 1797 of file TrkrNtuplizer.cc
References _cache_all_tracks_from_cluster, _cache_track_from_cluster_exists, _trackmap, SvtxTrackMap::begin(), SvtxTrackMap::end(), get_track_ckeys(), and tracks().
Referenced by all_tracks_from().
void TrkrNtuplizer::do_clus_trk_eval (bool b) inline
Definition at line 61 of file TrkrNtuplizer.h.
View newest version in sPHENIX GitHub at line 61 of file TrkrNtuplizer.h
References _do_clus_trk_eval, and KFPMath::b.
void TrkrNtuplizer::do_cluster_eval (bool b) inline
Definition at line 60 of file TrkrNtuplizer.h.
View newest version in sPHENIX GitHub at line 60 of file TrkrNtuplizer.h
References _do_cluster_eval, and KFPMath::b.
void TrkrNtuplizer::do_hit_eval (bool b) inline
Definition at line 59 of file TrkrNtuplizer.h.
View newest version in sPHENIX GitHub at line 59 of file TrkrNtuplizer.h
References _do_hit_eval, and KFPMath::b.
void TrkrNtuplizer::do_info_eval (bool b) inline
Definition at line 57 of file TrkrNtuplizer.h.
View newest version in sPHENIX GitHub at line 57 of file TrkrNtuplizer.h
References _do_info_eval, and KFPMath::b.
void TrkrNtuplizer::do_siseed_eval (bool b) inline
Definition at line 64 of file TrkrNtuplizer.h.
View newest version in sPHENIX GitHub at line 64 of file TrkrNtuplizer.h
References _do_siseed_eval, and KFPMath::b.
void TrkrNtuplizer::do_tpcseed_eval (bool b) inline
Definition at line 63 of file TrkrNtuplizer.h.
View newest version in sPHENIX GitHub at line 63 of file TrkrNtuplizer.h
References _do_tpcseed_eval, and KFPMath::b.
void TrkrNtuplizer::do_track_eval (bool b) inline
Definition at line 62 of file TrkrNtuplizer.h.
View newest version in sPHENIX GitHub at line 62 of file TrkrNtuplizer.h
References _do_track_eval, and KFPMath::b.
void TrkrNtuplizer::do_vertex_eval (bool b) inline
Definition at line 58 of file TrkrNtuplizer.h.
View newest version in sPHENIX GitHub at line 58 of file TrkrNtuplizer.h
References _do_vertex_eval, and KFPMath::b.
int TrkrNtuplizer::End (PHCompositeNode *) override virtual
Called at the end of all processing.
Reimplemented from SubsysReco.
Definition at line 244 of file TrkrNtuplizer.cc.
View newest version in sPHENIX GitHub at line 244 of file TrkrNtuplizer.cc
References _filename, _ievent, _ntp_clus_trk, _ntp_cluster, _ntp_hit, _ntp_info, _ntp_siseed, _ntp_tpcseed, _ntp_track, _ntp_vertex, _tfile, Fun4AllReturnCodes::EVENT_OK, and Fun4AllBase::Verbosity().
void TrkrNtuplizer::fillOutputNtuples (PHCompositeNode * topNode) private
dump the evaluator information into ntuple for external analysis
Definition at line 511 of file TrkrNtuplizer.cc.
View newest version in sPHENIX GitHub at line 511 of file TrkrNtuplizer.cc
References _clustrackseedcontainer, _ievent, _iseed, _nlayers_intt, _nlayers_maps, _nlayers_mms, _nlayers_tpc, _ntp_clus_trk, _ntp_cluster, _ntp_hit, _ntp_info, _ntp_siseed, _ntp_tpcseed, _ntp_track, _ntp_vertex, _timer, _trackmap, AdcClockPeriod, TrackSeed::begin_cluster_keys(), charge(), doit(), INTTVtxZ::dphi, dz, Acts::UnitConstants::e, TrackSeed::end_cluster_keys(), ephi, eta, event, TrkrClusterContainer::findCluster(), TrackFitUtils::fitClusters(), GlobalVertexMap::get(), TrackSeedContainer::get(), PHTimer::get_accumulated_time(), SvtxTrack::get_charge(), SvtxTrack::get_chisq(), ClusterErrorPara::get_clusterv5_modified_error(), SvtxTrack::get_crossing(), TrackAnalysisUtils::get_dca(), SvtxTrack::get_error(), TrackSeed::get_eta(), TrackFitUtils::get_helix_pca(), SvtxTrack::get_id(), SvtxTrack::get_ndf(), PHG4TpcCylinderGeom::get_pad_float(), TrackSeed::get_phi(), PHG4TpcCylinderGeom::get_phicenter(), TrackSeed::get_pt(), SvtxTrack::get_px(), SvtxTrack::get_py(), SvtxTrack::get_pz(), TrackSeed::get_qOverR(), SvtxTrack::get_quality(), PHG4TpcCylinderGeom::get_radius(), SvtxTrack::get_silicon_seed(), TrackSeed::get_silicon_seed_index(), PHG4TpcCylinderGeom::get_tbin_float(), SvtxTrack::get_tpc_seed(), TrackSeed::get_tpc_seed_index(), SvtxTrack::get_vertex_id(), GlobalVertex::get_x(), SvtxTrack::get_x(), TrackSeed::get_X0(), GlobalVertex::get_y(), SvtxTrack::get_y(), TrackSeed::get_Y0(), GlobalVertex::get_z(), SvtxTrack::get_z(), TrackSeed::get_Z0(), PHG4TpcCylinderGeom::get_zbins(), TrkrHit::getAdc(), TrkrCluster::getAdc(), TrkrClusterContainer::getClusters(), TrkrHit::getEnergy(), ActsGeometry::getGlobalPosition(), TrkrHitSet::getHits(), TrkrDefs::getHitSetKeyFromClusKey(), TrkrClusterContainer::getHitSetKeys(), TrkrHitSetContainer::getHitSets(), TrkrDefs::getLayer(), PHG4TpcCylinderGeomContainer::GetLayerCellGeom(), TrkrCluster::getLocalX(), TrkrCluster::getLocalY(), TrkrCluster::getMaxAdc(), TpcDefs::getPad(), TrkrCluster::getPhiSize(), TpcDefs::getSectorId(), TpcDefs::getSide(), TrkrCluster::getSize(), TpcDefs::getTBin(), TrackFitUtils::getTrackletClusters(), TrkrDefs::getTrkrId(), TrkrCluster::getZSize(), hitID, i, TrkrDefs::inttId, layer, m_fSeed, Acts::maps, TrkrDefs::micromegasId, TrkrDefs::mvtxId, ntracks, ActsTests::PropagationDatasets::phi, phisize, PHWHERE, Acts::Test::pos, position, physmon_track_finding_ttbar::pt, physmon_track_finding_ttbar::r, PHTimer::restart(), SvtxTrackMap::size(), TrackSeedContainer::size(), TrkrClusterContainer::size(), size, TrackSeed::size_cluster_keys(), PHTimer::stop(), teta, ActsTests::PropagationDatasets::theta, TrkrDefs::tpcId, tphi, tpt, trackID, testSigmaEff::v, Fun4AllBase::Verbosity(), vx, vy, vz, ambiguity_solver_full_chain::x, y, physmon_track_finding_ttbar::z, and zsize.
Referenced by process_event().
void TrkrNtuplizer::get_dca (SvtxTrack * track, SvtxVertexMap * vertexmap, float & dca3dxy, float & dca3dz, float & dca3dxysigma, float & dca3dzsigma) private
std::vector< TrkrDefs::cluskey > TrkrNtuplizer::get_track_ckeys (SvtxTrack * track)
Definition at line 1694 of file TrkrNtuplizer.cc.
View newest version in sPHENIX GitHub at line 1694 of file TrkrNtuplizer.cc
References TrackSeed::begin_cluster_keys(), TrackSeed::end_cluster_keys(), SvtxTrack::get_silicon_seed(), and SvtxTrack::get_tpc_seed().
Referenced by all_tracks_from(), and create_cache_track_from_cluster().
int TrkrNtuplizer::Init (PHCompositeNode *) override virtual
Called during initialization. Typically this is where you can book histograms, and e.g. register them to Fun4AllServer (so they can be output to file using Fun4AllServer::dumpHistos() method).
Reimplemented from SubsysReco.
Definition at line 100 of file TrkrNtuplizer.cc.
View newest version in sPHENIX GitHub at line 100 of file TrkrNtuplizer.cc
References _do_clus_trk_eval, _do_cluster_eval, _do_hit_eval, _do_info_eval, _do_siseed_eval, _do_tpcseed_eval, _do_track_eval, _do_vertex_eval, _filename, _ievent, _ntp_clus_trk, _ntp_cluster, _ntp_hit, _ntp_info, _ntp_tpcseed, _ntp_track, _ntp_vertex, _tfile, _timer, Fun4AllReturnCodes::EVENT_OK, and PHTimer::stop().
int TrkrNtuplizer::InitRun (PHCompositeNode *) override virtual
Called for first event when run number is known. Typically this is where you may want to fetch data from database, because you know the run number.
Reimplemented from SubsysReco.
Definition at line 192 of file TrkrNtuplizer.cc.
View newest version in sPHENIX GitHub at line 192 of file TrkrNtuplizer.cc
References Fun4AllReturnCodes::EVENT_OK.
void TrkrNtuplizer::printInputInfo (PHCompositeNode * topNode) private
print out the input object information (debugging upstream components)
Definition at line 295 of file TrkrNtuplizer.cc.
View newest version in sPHENIX GitHub at line 295 of file TrkrNtuplizer.cc
References _ievent, _trackmap, SvtxTrackMap::begin(), SvtxVertexMap::begin(), SvtxTrackMap::end(), SvtxVertexMap::end(), TrkrClusterContainer::getClusters(), TrkrClusterContainer::getHitSetKeys(), SvtxVertex::identify(), SvtxTrack::identify(), PHWHERE, SvtxVertexMap::size(), SvtxTrackMap::size(), TrkrClusterContainer::size(), and Fun4AllBase::Verbosity().
Referenced by process_event().
void TrkrNtuplizer::printOutputInfo (PHCompositeNode * topNode) private
print out the ancestry information for detailed diagnosis
Definition at line 375 of file TrkrNtuplizer.cc.
View newest version in sPHENIX GitHub at line 375 of file TrkrNtuplizer.cc
References _ievent, _nlayers_intt, _nlayers_maps, _nlayers_tpc, _trackmap, SvtxVertexMap::begin(), SvtxVertexMap::empty(), PHG4TpcCylinderGeom::get_phibins(), SvtxVertex::get_x(), SvtxVertex::get_y(), SvtxVertex::get_z(), PHG4TpcCylinderGeom::get_zbins(), TrkrHitSetContainer::getHitSets(), TrkrDefs::getLayer(), PHG4TpcCylinderGeomContainer::GetLayerCellGeom(), layer, PHWHERE, SvtxTrackMap::size(), Fun4AllBase::Verbosity(), vx, vy, and vz.
int TrkrNtuplizer::process_event (PHCompositeNode *) override virtual
Called for each event. This is where you do the real work.
Reimplemented from SubsysReco.
Definition at line 197 of file TrkrNtuplizer.cc.
View newest version in sPHENIX GitHub at line 197 of file TrkrNtuplizer.cc
References _ievent, _iseed, _trackmap, _trackmapname, Fun4AllReturnCodes::EVENT_OK, fillOutputNtuples(), PHFlag::FlagExist(), PHFlag::get_IntFlag(), recoConsts::instance(), m_fSeed, printInputInfo(), and Fun4AllBase::Verbosity().
void TrkrNtuplizer::set_first_event (int value) inline
Definition at line 65 of file TrkrNtuplizer.h.
View newest version in sPHENIX GitHub at line 65 of file TrkrNtuplizer.h
References _ievent, and value.
void TrkrNtuplizer::set_trkclus_seed_container (const std::string & name) inline
Definition at line 66 of file TrkrNtuplizer.h.
View newest version in sPHENIX GitHub at line 66 of file TrkrNtuplizer.h
References _clustrackseedcontainer, and perf_headwind::name.
Member Data Documentation
std::map<TrkrDefs::cluskey, std::set<SvtxTrack*> > TrkrNtuplizer::_cache_all_tracks_from_cluster private
Definition at line 129 of file TrkrNtuplizer.h.
View newest version in sPHENIX GitHub at line 129 of file TrkrNtuplizer.h
Referenced by all_tracks_from(), and create_cache_track_from_cluster().
std::map<TrkrDefs::cluskey, SvtxTrack*> TrkrNtuplizer::_cache_best_track_from_cluster private
Definition at line 130 of file TrkrNtuplizer.h.
View newest version in sPHENIX GitHub at line 130 of file TrkrNtuplizer.h
Referenced by best_track_from().
bool TrkrNtuplizer::_cache_track_from_cluster_exists = false private
Definition at line 128 of file TrkrNtuplizer.h.
View newest version in sPHENIX GitHub at line 128 of file TrkrNtuplizer.h
Referenced by all_tracks_from(), and create_cache_track_from_cluster().
std::string TrkrNtuplizer::_clustrackseedcontainer = "TpcTrackSeedContainer" private
Definition at line 117 of file TrkrNtuplizer.h.
View newest version in sPHENIX GitHub at line 117 of file TrkrNtuplizer.h
Referenced by fillOutputNtuples(), and set_trkclus_seed_container().
bool TrkrNtuplizer::_do_clus_trk_eval private
Definition at line 92 of file TrkrNtuplizer.h.
View newest version in sPHENIX GitHub at line 92 of file TrkrNtuplizer.h
Referenced by do_clus_trk_eval(), and Init().
bool TrkrNtuplizer::_do_cluster_eval private
Definition at line 91 of file TrkrNtuplizer.h.
View newest version in sPHENIX GitHub at line 91 of file TrkrNtuplizer.h
Referenced by do_cluster_eval(), and Init().
bool TrkrNtuplizer::_do_hit_eval private
Definition at line 90 of file TrkrNtuplizer.h.
View newest version in sPHENIX GitHub at line 90 of file TrkrNtuplizer.h
Referenced by do_hit_eval(), and Init().
bool TrkrNtuplizer::_do_info_eval private
Definition at line 88 of file TrkrNtuplizer.h.
View newest version in sPHENIX GitHub at line 88 of file TrkrNtuplizer.h
Referenced by do_info_eval(), and Init().
bool TrkrNtuplizer::_do_siseed_eval private
Definition at line 95 of file TrkrNtuplizer.h.
View newest version in sPHENIX GitHub at line 95 of file TrkrNtuplizer.h
Referenced by do_siseed_eval(), and Init().
bool TrkrNtuplizer::_do_tpcseed_eval private
Definition at line 94 of file TrkrNtuplizer.h.
View newest version in sPHENIX GitHub at line 94 of file TrkrNtuplizer.h
Referenced by do_tpcseed_eval(), and Init().
bool TrkrNtuplizer::_do_track_eval private
Definition at line 93 of file TrkrNtuplizer.h.
View newest version in sPHENIX GitHub at line 93 of file TrkrNtuplizer.h
Referenced by do_track_eval(), and Init().
bool TrkrNtuplizer::_do_vertex_eval private
Definition at line 89 of file TrkrNtuplizer.h.
View newest version in sPHENIX GitHub at line 89 of file TrkrNtuplizer.h
Referenced by do_vertex_eval(), and Init().
std::string TrkrNtuplizer::_filename private
Definition at line 112 of file TrkrNtuplizer.h.
View newest version in sPHENIX GitHub at line 112 of file TrkrNtuplizer.h
Referenced by End(), and Init().
unsigned int TrkrNtuplizer::_ievent private
Definition at line 74 of file TrkrNtuplizer.h.
View newest version in sPHENIX GitHub at line 74 of file TrkrNtuplizer.h
Referenced by End(), fillOutputNtuples(), Init(), printInputInfo(), printOutputInfo(), process_event(), and set_first_event().
unsigned int TrkrNtuplizer::_iseed private
Definition at line 75 of file TrkrNtuplizer.h.
View newest version in sPHENIX GitHub at line 75 of file TrkrNtuplizer.h
Referenced by fillOutputNtuples(), and process_event().
unsigned int TrkrNtuplizer::_nlayers_intt = 4 private
Definition at line 98 of file TrkrNtuplizer.h.
View newest version in sPHENIX GitHub at line 98 of file TrkrNtuplizer.h
Referenced by fillOutputNtuples(), and printOutputInfo().
unsigned int TrkrNtuplizer::_nlayers_maps = 3 private
Definition at line 97 of file TrkrNtuplizer.h.
View newest version in sPHENIX GitHub at line 97 of file TrkrNtuplizer.h
Referenced by fillOutputNtuples(), and printOutputInfo().
unsigned int TrkrNtuplizer::_nlayers_mms = 2 private
Definition at line 100 of file TrkrNtuplizer.h.
View newest version in sPHENIX GitHub at line 100 of file TrkrNtuplizer.h
Referenced by fillOutputNtuples().
unsigned int TrkrNtuplizer::_nlayers_tpc = 48 private
Definition at line 99 of file TrkrNtuplizer.h.
View newest version in sPHENIX GitHub at line 99 of file TrkrNtuplizer.h
Referenced by fillOutputNtuples(), and printOutputInfo().
TNtuple* TrkrNtuplizer::_ntp_clus_trk private
Definition at line 106 of file TrkrNtuplizer.h.
View newest version in sPHENIX GitHub at line 106 of file TrkrNtuplizer.h
Referenced by End(), fillOutputNtuples(), and Init().
TNtuple* TrkrNtuplizer::_ntp_cluster private
Definition at line 105 of file TrkrNtuplizer.h.
View newest version in sPHENIX GitHub at line 105 of file TrkrNtuplizer.h
Referenced by End(), fillOutputNtuples(), and Init().
TNtuple* TrkrNtuplizer::_ntp_hit private
Definition at line 104 of file TrkrNtuplizer.h.
View newest version in sPHENIX GitHub at line 104 of file TrkrNtuplizer.h
Referenced by End(), fillOutputNtuples(), and Init().
TNtuple* TrkrNtuplizer::_ntp_info private
Definition at line 102 of file TrkrNtuplizer.h.
View newest version in sPHENIX GitHub at line 102 of file TrkrNtuplizer.h
Referenced by End(), fillOutputNtuples(), and Init().
TNtuple* TrkrNtuplizer::_ntp_siseed private
Definition at line 109 of file TrkrNtuplizer.h.
View newest version in sPHENIX GitHub at line 109 of file TrkrNtuplizer.h
Referenced by End(), and fillOutputNtuples().
TNtuple* TrkrNtuplizer::_ntp_tpcseed private
Definition at line 108 of file TrkrNtuplizer.h.
View newest version in sPHENIX GitHub at line 108 of file TrkrNtuplizer.h
Referenced by End(), fillOutputNtuples(), and Init().
TNtuple* TrkrNtuplizer::_ntp_track private
Definition at line 107 of file TrkrNtuplizer.h.
View newest version in sPHENIX GitHub at line 107 of file TrkrNtuplizer.h
Referenced by End(), fillOutputNtuples(), and Init().
TNtuple* TrkrNtuplizer::_ntp_vertex private
Definition at line 103 of file TrkrNtuplizer.h.
View newest version in sPHENIX GitHub at line 103 of file TrkrNtuplizer.h
Referenced by End(), fillOutputNtuples(), and Init().
TFile* TrkrNtuplizer::_tfile private
Definition at line 119 of file TrkrNtuplizer.h.
View newest version in sPHENIX GitHub at line 119 of file TrkrNtuplizer.h
Referenced by End(), and Init().
PHTimer* TrkrNtuplizer::_timer private
Definition at line 120 of file TrkrNtuplizer.h.
View newest version in sPHENIX GitHub at line 120 of file TrkrNtuplizer.h
Referenced by fillOutputNtuples(), Init(), and ~TrkrNtuplizer().
SvtxTrackMap* TrkrNtuplizer::_trackmap = nullptr private
Definition at line 115 of file TrkrNtuplizer.h.
View newest version in sPHENIX GitHub at line 115 of file TrkrNtuplizer.h
Referenced by all_tracks_from(), create_cache_track_from_cluster(), fillOutputNtuples(), printInputInfo(), printOutputInfo(), and process_event().
std::string TrkrNtuplizer::_trackmapname private
Definition at line 114 of file TrkrNtuplizer.h.
View newest version in sPHENIX GitHub at line 114 of file TrkrNtuplizer.h
Referenced by process_event().
double TrkrNtuplizer::AdcClockPeriod = 53.0 private
Definition at line 126 of file TrkrNtuplizer.h.
View newest version in sPHENIX GitHub at line 126 of file TrkrNtuplizer.h
Referenced by fillOutputNtuples().
float TrkrNtuplizer::m_fSeed private
Definition at line 76 of file TrkrNtuplizer.h.
View newest version in sPHENIX GitHub at line 76 of file TrkrNtuplizer.h
Referenced by fillOutputNtuples(), and process_event().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/TrackingDiagnostics/TrkrNtuplizer.h
coresoftware/blob/master/offline/packages/TrackingDiagnostics/TrkrNtuplizer.cc