Analysis Software: Acts::Extent Struct Reference
Acts::Extent Struct Reference
#include <acts/blob/sPHENIX/Core/include/Acts/Geometry/Extent.hpp>
Public Member Functions
Extent ()=default
bool intersects (const Extent &other, BinningValue bVal=binValues, double tolerance=s_epsilon)
void extend (const Extent &other)
std::ostream & toStream (std::ostream &sl) const
double & min (BinningValue bval)
double min (BinningValue bval) const
double & max (BinningValue bval)
double max (BinningValue bval) const
double medium (BinningValue bval) const
double range (BinningValue bval) const
void check (const Vector3D &vtx)
Public Attributes
std::vector< Range > ranges {(int)binValues, maxrange}
Static Public Attributes
static constexpr double maxval = std::numeric_limits<double>::max()
Possible maximal value.
static constexpr Range maxrange = {maxval, -maxval}
Start value.
Detailed Description
This is a nested struct to the GeometryObject representation which can be retrieved and used for surface parsing and will give you the maximal extent in 3D space/
Definition at line 28 of file Extent.hpp.
View newest version in sPHENIX GitHub at line 28 of file Extent.hpp
Constructor & Destructor Documentation
Acts::Extent::Extent () default
Member Function Documentation
void Acts::Extent::check (const Vector3D & vtx) inline
Check the vertex
Parameters
vtx the Vertex to be checked
Definition at line 111 of file Extent.hpp.
View newest version in sPHENIX GitHub at line 111 of file Extent.hpp
References Acts::binValues, Acts::VectorHelpers::cast(), max, min, ranges, and value.
Referenced by Acts::Test::BOOST_AUTO_TEST_CASE(), dokinematics(), Acts::Polyhedron::extent(), genevent(), init(), jewel(), makebranch(), makeinsplit(), makesplitting(), pyslha(), and pywidt().
void Acts::Extent::extend (const Extent & other) inline
Extend with another extent
Parameters
other is the source Extent
Definition at line 70 of file Extent.hpp.
View newest version in sPHENIX GitHub at line 70 of file Extent.hpp
References max, min, and ranges.
Referenced by Acts::Test::BOOST_AUTO_TEST_CASE(), Acts::GeometryView3D::drawSurfaceArray(), and Acts::ProtoLayer::measure().
bool Acts::Extent::intersects (const Extent & other, BinningValue bVal = binValues, double tolerance = s_epsilon) inline
Check if it intersects
Parameters
other The source Extent
bValue The binning value for the check (binValues for all)
tolerance An additional tolerance for the intersection check
Definition at line 45 of file Extent.hpp.
View newest version in sPHENIX GitHub at line 45 of file Extent.hpp
References KFPMath::a, KFPMath::b, Acts::binValues, ranges, and Acts::Test::tolerance.
Referenced by Acts::Test::BOOST_AUTO_TEST_CASE().
double& Acts::Extent::max (BinningValue bval) inline
Access the max parameter
Parameters
bval the binning identification
Definition at line 91 of file Extent.hpp.
View newest version in sPHENIX GitHub at line 91 of file Extent.hpp
References ranges.
Referenced by Acts::Test::BOOST_AUTO_TEST_CASE(), and Acts::ProtoLayer::max().
double Acts::Extent::max (BinningValue bval) const inline
Access the max parameter
Parameters
bval the binning identification
Definition at line 95 of file Extent.hpp.
View newest version in sPHENIX GitHub at line 95 of file Extent.hpp
References ranges.
double Acts::Extent::medium (BinningValue bval) const inline
Access the medium parameter
Parameters
bval the binning identification
Definition at line 99 of file Extent.hpp.
View newest version in sPHENIX GitHub at line 99 of file Extent.hpp
References ranges.
Referenced by Acts::GeometryView3D::drawSurfaceArray(), Acts::Polyhedron::extent(), and medinit().
double& Acts::Extent::min (BinningValue bval) inline
Access the minimum parameter
Parameters
bval the binning identification
Definition at line 83 of file Extent.hpp.
View newest version in sPHENIX GitHub at line 83 of file Extent.hpp
References ranges.
Referenced by Acts::Test::BOOST_AUTO_TEST_CASE(), Acts::ProtoLayer::min(), and Acts::SurfaceBinningMatcher::operator()().
double Acts::Extent::min (BinningValue bval) const inline
Access the minimum parameter
Parameters
bval the binning identification
Definition at line 87 of file Extent.hpp.
View newest version in sPHENIX GitHub at line 87 of file Extent.hpp
References ranges.
double Acts::Extent::range (BinningValue bval) const inline
Access the range - always positive
Parameters
bval the binning identification
Definition at line 105 of file Extent.hpp.
View newest version in sPHENIX GitHub at line 105 of file Extent.hpp
References kdfinder::abs(), and ranges.
std::ostream & Acts::Extent::toStream (std::ostream & sl) const
Convert to output stream for screen output
Parameters
sl [in,out] The output stream
Definition at line 13 of file Extent.cpp.
View newest version in sPHENIX GitHub at line 13 of file Extent.cpp
References Acts::binningValueNames, Acts::binValues, and ranges.
Referenced by Acts::operator<<(), and Acts::ProtoLayer::toStream().
Member Data Documentation
constexpr Range Acts::Extent::maxrange = {maxval, -maxval} static
Start value.
Definition at line 33 of file Extent.hpp.
View newest version in sPHENIX GitHub at line 33 of file Extent.hpp
constexpr double Acts::Extent::maxval = std::numeric_limits<double>::max() static
Possible maximal value.
Definition at line 30 of file Extent.hpp.
View newest version in sPHENIX GitHub at line 30 of file Extent.hpp
std::vector<Range> Acts::Extent::ranges {(int)binValues, maxrange}
Definition at line 36 of file Extent.hpp.
View newest version in sPHENIX GitHub at line 36 of file Extent.hpp
Referenced by Acts::Test::BOOST_AUTO_TEST_CASE(), Acts::Test::BOOST_FIXTURE_TEST_CASE(), Acts::DD4hepLayerBuilder::centralLayers(), check(), pump.Env::Clone(), Acts::DD4hepLayerBuilder::endcapLayers(), extend(), Acts::Polyhedron::extent(), pump.Env::GetRange(), intersects(), max(), medium(), min(), pump.Env::PopRange(), pump.Env::PushRange(), range(), and toStream().
The documentation for this struct was generated from the following files:
acts/blob/sPHENIX/Core/include/Acts/Geometry/Extent.hpp
acts/blob/sPHENIX/Core/src/Geometry/Extent.cpp