Analysis Software: CemcMonDraw Class Reference
CemcMonDraw Class Reference
#include <OnlMon/blob/main/subsystems/cemc/CemcMonDraw.h>
Public Member Functions
CemcMonDraw (const std::string &name="CEMCMON")
~CemcMonDraw () override
int Init () override
int Draw (const std::string &what="ALL") override
int MakeHtml (const std::string &what="ALL") override
int SavePlot (const std::string &what="ALL", const std::string &type="png") override
void setSave (int s)
Public Member Functions inherited from OnlMonDraw
OnlMonDraw (const std::string &name="NONE")
virtual ~OnlMonDraw ()
virtual int MakePS (const std::string &what="ALL")
const std::string Name () const
void Verbosity (const int i)
int Verbosity () const
Private Member Functions
int MakeCanvas (const std::string &name)
int DrawFirst (const std::string &what="ALL")
int DrawSecond (const std::string &what="ALL")
int DrawThird (const std::string &what="ALL")
int DrawFourth (const std::string &what="ALL")
int DrawHistory (const std::string &what="ALL")
int FindHotTower (TPad *warn, TH2 *)
time_t getTime ()
std::vector< int > getBadPackets (TH1 *hist, int what, float cutoff)
Private Attributes
const int nTowersEta = 96
const int nTowersPhi = 256
const int templateDepth =10000
int save = 0
TCanvas * TC [9] = {nullptr}
TPad * transparent [9] = {nullptr}
TPad * Pad [18] = {nullptr}
TPad * warning [18] = {nullptr}
TGraphErrors * gr [2] = {nullptr}
TStyle * cemcStyle = nullptr
const int nSEBs = 8
Additional Inherited Members
Protected Member Functions inherited from OnlMonDraw
virtual int DrawDeadServer (TPad *transparent)
Protected Attributes inherited from OnlMonDraw
std::string ThisName
int verbosity = 0
Detailed Description
Definition at line 14 of file CemcMonDraw.h.
View newest version in sPHENIX GitHub at line 14 of file CemcMonDraw.h
Constructor & Destructor Documentation
CemcMonDraw::CemcMonDraw (const std::string & name = "CEMCMON")
Definition at line 28 of file CemcMonDraw.cc.
View newest version in sPHENIX GitHub at line 28 of file CemcMonDraw.cc
CemcMonDraw::~CemcMonDraw () inline override
Definition at line 19 of file CemcMonDraw.h.
View newest version in sPHENIX GitHub at line 19 of file CemcMonDraw.h
Member Function Documentation
int CemcMonDraw::Draw (const std::string & what = "ALL") override virtual
Reimplemented from OnlMonDraw.
Definition at line 145 of file CemcMonDraw.cc.
View newest version in sPHENIX GitHub at line 145 of file CemcMonDraw.cc
References DrawFirst(), DrawFourth(), DrawSecond(), and DrawThird().
Referenced by DrawFirst(), DrawSecond(), DrawThird(), FindHotTower(), MakeCanvas(), MakeHtml(), and SavePlot().
int CemcMonDraw::DrawFirst (const std::string & what = "ALL") private
Definition at line 179 of file CemcMonDraw.cc.
View newest version in sPHENIX GitHub at line 179 of file CemcMonDraw.cc
References cemcStyle, Draw(), OnlMonDraw::DrawDeadServer(), OnlMonClient::EventTime(), FindHotTower(), OnlMonClient::getHisto(), GetZaxis(), i, OnlMonClient::instance(), j, levels, MakeCanvas(), nSEBs, nTowersEta, nTowersPhi, Pad, OnlMonClient::RunNumber(), save, SetBinContent(), SetName(), SetOptStat(), start, TC, templateDepth, transparent, and warning.
Referenced by Draw().
int CemcMonDraw::DrawFourth (const std::string & what = "ALL") private
Definition at line 869 of file CemcMonDraw.cc.
View newest version in sPHENIX GitHub at line 869 of file CemcMonDraw.cc
References OnlMonDraw::DrawDeadServer(), OnlMonClient::EventTime(), OnlMonClient::getHisto(), i, OnlMonClient::instance(), MakeCanvas(), nSEBs, Pad, OnlMonClient::RunNumber(), save, SetName(), start, TC, and transparent.
Referenced by Draw().
int CemcMonDraw::DrawHistory (const std::string & what = "ALL") private
int CemcMonDraw::DrawSecond (const std::string & what = "ALL") private
Definition at line 402 of file CemcMonDraw.cc.
View newest version in sPHENIX GitHub at line 402 of file CemcMonDraw.cc
References AddEntry(), Acts::Test::at, parse_cmake_options::begin, cd(), test_fpe::count, Draw(), OnlMonDraw::DrawDeadServer(), end, OnlMonClient::EventTime(), getBadPackets(), OnlMonClient::getHisto(), GetYaxis(), i, OnlMonClient::instance(), j, leg, MakeCanvas(), nSEBs, Pad, OnlMonClient::RunNumber(), save, SetBorderSize(), SetFillStyle(), SetLineColor(), SetLineStyle(), SetName(), SetOptStat(), SetTextSize(), size, start, TC, title, transparent, and warning.
Referenced by Draw().
int CemcMonDraw::DrawThird (const std::string & what = "ALL") private
Definition at line 697 of file CemcMonDraw.cc.
View newest version in sPHENIX GitHub at line 697 of file CemcMonDraw.cc
References Draw(), OnlMonDraw::DrawDeadServer(), OnlMonClient::EventTime(), OnlMonClient::getHisto(), GetYaxis(), i, OnlMonClient::instance(), MakeCanvas(), nSEBs, Pad, OnlMonClient::RunNumber(), save, SetName(), SetOptStat(), start, TC, and transparent.
Referenced by Draw().
int CemcMonDraw::FindHotTower (TPad * warn, TH2 * hhit) private
Definition at line 1031 of file CemcMonDraw.cc.
View newest version in sPHENIX GitHub at line 1031 of file CemcMonDraw.cc
References Draw(), nTowersEta, nTowersPhi, SetFillColor(), and SetTextSize().
Referenced by DrawFirst().
std::vector< int > CemcMonDraw::getBadPackets (TH1 * hist, int what, float cutoff) private
Definition at line 1155 of file CemcMonDraw.cc.
View newest version in sPHENIX GitHub at line 1155 of file CemcMonDraw.cc
References i.
Referenced by DrawSecond().
time_t CemcMonDraw::getTime () private
Definition at line 1172 of file CemcMonDraw.cc.
View newest version in sPHENIX GitHub at line 1172 of file CemcMonDraw.cc
References OnlMonClient::EventTime(), and OnlMonClient::instance().
int CemcMonDraw::Init () override virtual
Reimplemented from OnlMonDraw.
Definition at line 35 of file CemcMonDraw.cc.
View newest version in sPHENIX GitHub at line 35 of file CemcMonDraw.cc
References cemcStyle.
int CemcMonDraw::MakeCanvas (const std::string & name) private
Definition at line 59 of file CemcMonDraw.cc.
View newest version in sPHENIX GitHub at line 59 of file CemcMonDraw.cc
References Draw(), OnlMonClient::GetDisplaySizeX(), OnlMonClient::GetDisplaySizeY(), OnlMonClient::instance(), Pad, SetFillStyle(), TC, transparent, and warning.
Referenced by DrawFirst(), DrawFourth(), DrawSecond(), and DrawThird().
int CemcMonDraw::MakeHtml (const std::string & what = "ALL") override virtual
Reimplemented from OnlMonDraw.
Definition at line 1113 of file CemcMonDraw.cc.
View newest version in sPHENIX GitHub at line 1113 of file CemcMonDraw.cc
References OnlMonClient::CanvasToPng(), Draw(), OnlMonClient::htmlRegisterPage(), OnlMonClient::instance(), TC, and to_string().
int CemcMonDraw::SavePlot (const std::string & what = "ALL", const std::string & type = "png") override virtual
Reimplemented from OnlMonDraw.
Definition at line 1090 of file CemcMonDraw.cc.
View newest version in sPHENIX GitHub at line 1090 of file CemcMonDraw.cc
References OnlMonClient::CanvasToPng(), Draw(), filename, OnlMonClient::instance(), OnlMonClient::RunNumber(), TC, OnlMonDraw::ThisName, and to_string().
void CemcMonDraw::setSave (int s) inline
Definition at line 25 of file CemcMonDraw.h.
View newest version in sPHENIX GitHub at line 25 of file CemcMonDraw.h
References physmon_simulation::s, and save.
Member Data Documentation
TStyle* CemcMonDraw::cemcStyle = nullptr private
Definition at line 48 of file CemcMonDraw.h.
View newest version in sPHENIX GitHub at line 48 of file CemcMonDraw.h
Referenced by DrawFirst(), and Init().
TGraphErrors* CemcMonDraw::gr[2] = {nullptr} private
Definition at line 47 of file CemcMonDraw.h.
View newest version in sPHENIX GitHub at line 47 of file CemcMonDraw.h
const int CemcMonDraw::nSEBs = 8 private
Definition at line 49 of file CemcMonDraw.h.
View newest version in sPHENIX GitHub at line 49 of file CemcMonDraw.h
Referenced by DrawFirst(), DrawFourth(), DrawSecond(), and DrawThird().
const int CemcMonDraw::nTowersEta = 96 private
Definition at line 39 of file CemcMonDraw.h.
View newest version in sPHENIX GitHub at line 39 of file CemcMonDraw.h
Referenced by DrawFirst(), and FindHotTower().
const int CemcMonDraw::nTowersPhi = 256 private
Definition at line 40 of file CemcMonDraw.h.
View newest version in sPHENIX GitHub at line 40 of file CemcMonDraw.h
Referenced by DrawFirst(), and FindHotTower().
TPad* CemcMonDraw::Pad[18] = {nullptr} private
Definition at line 45 of file CemcMonDraw.h.
View newest version in sPHENIX GitHub at line 45 of file CemcMonDraw.h
Referenced by DrawFirst(), DrawFourth(), DrawSecond(), DrawThird(), and MakeCanvas().
int CemcMonDraw::save = 0 private
Definition at line 42 of file CemcMonDraw.h.
View newest version in sPHENIX GitHub at line 42 of file CemcMonDraw.h
Referenced by DrawFirst(), DrawFourth(), DrawSecond(), DrawThird(), and setSave().
TCanvas* CemcMonDraw::TC[9] = {nullptr} private
Definition at line 43 of file CemcMonDraw.h.
View newest version in sPHENIX GitHub at line 43 of file CemcMonDraw.h
Referenced by DrawFirst(), DrawFourth(), DrawSecond(), DrawThird(), MakeCanvas(), MakeHtml(), and SavePlot().
const int CemcMonDraw::templateDepth =10000 private
Definition at line 41 of file CemcMonDraw.h.
View newest version in sPHENIX GitHub at line 41 of file CemcMonDraw.h
Referenced by DrawFirst().
TPad* CemcMonDraw::transparent[9] = {nullptr} private
Definition at line 44 of file CemcMonDraw.h.
View newest version in sPHENIX GitHub at line 44 of file CemcMonDraw.h
Referenced by DrawFirst(), DrawFourth(), DrawSecond(), DrawThird(), and MakeCanvas().
TPad* CemcMonDraw::warning[18] = {nullptr} private
Definition at line 46 of file CemcMonDraw.h.
View newest version in sPHENIX GitHub at line 46 of file CemcMonDraw.h
Referenced by DrawFirst(), DrawSecond(), and MakeCanvas().
The documentation for this class was generated from the following files:
OnlMon/blob/main/subsystems/cemc/CemcMonDraw.h
OnlMon/blob/main/subsystems/cemc/CemcMonDraw.cc