Analysis Software: BEmcRecCEMC Class Reference
BEmcRecCEMC Class Reference
#include <coresoftware/blob/master/offline/packages/CaloReco/BEmcRecCEMC.h>
Public Member Functions
BEmcRecCEMC ()
~BEmcRecCEMC () override
void CorrectEnergy (float energy, float x, float y, float &ecorr) override
void CorrectECore (float ecore, float x, float y, float &ecorecorr) override
void CorrectPosition (float energy, float x, float y, float &xcorr, float &ycorr) override
void CorrectShowerDepth (float energy, float x, float y, float z, float &xc, float &yc, float &zc) override
void LoadProfile (const std::string &fname) override
void GetImpactThetaPhi (float xg, float yg, float zg, float &theta, float &phi) override
Public Member Functions inherited from BEmcRec
BEmcRec ()
BEmcRec & operator= (const BEmcRec &)=delete
virtual ~BEmcRec ()
void SetVertex (const float *vv)
void SetDim (int nx, int ny)
bool SetTowerGeometry (int ix, int iy, float xx, float yy, float zz)
bool GetTowerGeometry (int ix, int iy, TowerGeom &geom)
bool CompleteTowerGeometry ()
void PrintTowerGeometry (const std::string &fname)
void SetPlanarGeometry ()
void SetCylindricalGeometry ()
bool isCylindrical () const
void SetProfileProb (bool bprob)
void SetCalotype (int caloid)
void SetScinSize (float S_S)
int GetNx () const
int GetNy () const
int GetCalotype () const
float GetScinSize () const
float GetVx () const
float GetVy () const
float GetVz () const
void SetPeakThreshold (float Thresh)
float GetPeakThreshold ()
void SetTowerThreshold (float Thresh)
float GetTowerThreshold ()
void SetModules (const std::vector< EmcModule > *modules)
std::vector< EmcModule > * GetModules ()
std::vector< EmcCluster > * GetClusters ()
int iTowerDist (int ix1, int ix2)
float fTowerDist (float x1, float x2)
int FindClusters ()
void Momenta (std::vector< EmcModule > *, float &, float &, float &, float &, float &, float &, float thresh=0)
void Tower2Global (float E, float xC, float yC, float &xA, float &yA, float &zA)
float GetTowerEnergy (int iy, int iz, std::vector< EmcModule > *plist)
float PredictEnergy (float, float, float, int, int)
float PredictEnergyProb (float en, float xcg, float ycg, int ix, int iy)
virtual float PredictEnergyParam (float, float, float)
float GetProb (std::vector< EmcModule > HitList, float e, float xg, float yg, float zg, float &chi2, int &ndf)
void SetProbNoiseParam (float rn)
float GetProbNoiseParam ()
virtual std::string Name () const
virtual void Name (const std::string &name)
Additional Inherited Members
Static Public Member Functions inherited from BEmcRec
static int HitNCompare (const void *, const void *)
static int HitACompare (const void *, const void *)
static void CopyVector (const int *, int *, int)
static void CopyVector (const EmcModule *, EmcModule *, int)
static void ZeroVector (int *, int)
static void ZeroVector (float *, int)
static void ZeroVector (EmcModule *, int)
Protected Attributes inherited from BEmcRec
bool bCYL = true
bool bProfileProb = false
int fNx = -1
int fNy = -1
std::map< int, TowerGeom > fTowerGeom
float fVx = 0.
float fVy = 0.
float fVz = 0.
std::vector< EmcModule > * fModules
std::vector< EmcCluster > * fClusters
float fgProbNoiseParam = 0.04
float fgTowerThresh = 0.01
float fgMinPeakEnergy = 0.08
BEmcProfile * _emcprof = nullptr
Static Protected Attributes inherited from BEmcRec
static int const fgMaxLen = 1000
Detailed Description
Definition at line 12 of file BEmcRecCEMC.h.
View newest version in sPHENIX GitHub at line 12 of file BEmcRecCEMC.h
Constructor & Destructor Documentation
BEmcRecCEMC::BEmcRecCEMC ()
Definition at line 9 of file BEmcRecCEMC.cc.
View newest version in sPHENIX GitHub at line 9 of file BEmcRecCEMC.cc
References BEmcRec::Name(), and BEmcRec::SetCylindricalGeometry().
BEmcRecCEMC::~BEmcRecCEMC () override
Definition at line 16 of file BEmcRecCEMC.cc.
View newest version in sPHENIX GitHub at line 16 of file BEmcRecCEMC.cc
Member Function Documentation
void BEmcRecCEMC::CorrectECore (float ecore, float x, float y, float & ecorecorr) override virtual
Reimplemented from BEmcRec.
Definition at line 319 of file BEmcRecCEMC.cc.
View newest version in sPHENIX GitHub at line 319 of file BEmcRecCEMC.cc
void BEmcRecCEMC::CorrectEnergy (float energy, float x, float y, float & ecorr) override virtual
Reimplemented from BEmcRec.
Definition at line 293 of file BEmcRecCEMC.cc.
View newest version in sPHENIX GitHub at line 293 of file BEmcRecCEMC.cc
void BEmcRecCEMC::CorrectPosition (float energy, float x, float y, float & xcorr, float & ycorr) override virtual
Reimplemented from BEmcRec.
Definition at line 330 of file BEmcRecCEMC.cc.
View newest version in sPHENIX GitHub at line 330 of file BEmcRecCEMC.cc
References EmcCluster::ABS(), BEmcRec::fNx, EmcCluster::lowint(), t, ambiguity_solver_full_chain::x, x0, KFPMath::xZero, y, and KFPMath::yZero.
void BEmcRecCEMC::CorrectShowerDepth (float energy, float x, float y, float z, float & xc, float & yc, float & zc) override virtual
Reimplemented from BEmcRec.
Definition at line 244 of file BEmcRecCEMC.cc.
View newest version in sPHENIX GitHub at line 244 of file BEmcRecCEMC.cc
References dz, BEmcRec::fVz, Acts::IntegrationTest::L, and ActsTests::PropagationDatasets::phi.
void BEmcRecCEMC::GetImpactThetaPhi (float xg, float yg, float zg, float & theta, float & phi) override virtual
Reimplemented from BEmcRec.
Definition at line 28 of file BEmcRecCEMC.cc.
View newest version in sPHENIX GitHub at line 28 of file BEmcRecCEMC.cc
References BEmcRec::fVz.
void BEmcRecCEMC::LoadProfile (const std::string & fname) override virtual
Reimplemented from BEmcRec.
Definition at line 22 of file BEmcRecCEMC.cc.
View newest version in sPHENIX GitHub at line 22 of file BEmcRecCEMC.cc
References BEmcRec::_emcprof.
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/CaloReco/BEmcRecCEMC.h
coresoftware/blob/master/offline/packages/CaloReco/BEmcRecCEMC.cc