Analysis Software: shower Class Reference
shower Class Reference
Public Member Functions
shower ()
node new_vertex (int x)
void new_parton (node s, node t, parton p)
int GetNodeValue (node n) const
void save_edge_info_handler (ostream *o, edge n) const
double GetEdgeValue (edge n) const
shower ()
~shower ()
node new_vertex (int x)
void new_parton (node s, node t, parton p)
int GetNodeValue (node n) const
void save_edge_info_handler (ostream *o, edge n) const
double GetEdgeValue (edge n) const
Public Member Functions inherited from graph
graph ()
graph (const graph &G)
graph (const graph &G, const list< node > &nodes)
graph (const graph &G, list< node >::const_iterator it, list< node >::const_iterator end)
virtual ~graph ()
void make_directed ()
void make_undirected ()
bool is_directed () const
bool is_undirected () const
bool is_bidirected (edge_map< edge > &rev) const
bool is_connected () const
bool is_acyclic () const
int number_of_nodes () const
int number_of_edges () const
node center () const
virtual node new_node ()
virtual edge new_edge (node s, node t)
virtual edge new_edge (const list< node > &sources, const list< node > &targets)
void del_node (node n)
void del_all_nodes ()
void del_edge (edge e)
void del_all_edges ()
void clear ()
node_iterator nodes_begin () const
node_iterator nodes_end () const
edge_iterator edges_begin () const
edge_iterator edges_end () const
list< node > all_nodes () const
list< edge > all_edges () const
node choose_node () const
void hide_edge (edge e)
void restore_edge (edge e)
list< edge > hide_node (node n)
void restore_node (node n)
void induced_subgraph (list< node > &subgraph_nodes)
void restore_graph ()
list< edge > insert_reverse_edges ()
GML_error load (const string &filename, bool preserve_ids=false)
GML_error load (const char *filename, bool preserve_ids=false)
int save (const char *filename) const
void save (ostream *file=&cout) const
virtual void pre_new_node_handler ()
virtual void post_new_node_handler (node n)
virtual void pre_del_node_handler (node n)
virtual void post_del_node_handler ()
virtual void pre_hide_node_handler (node n)
virtual void post_hide_node_handler (node n)
virtual void pre_restore_node_handler (node n)
virtual void post_restore_node_handler (node n)
virtual void pre_new_edge_handler (node s, node t)
virtual void post_new_edge_handler (edge e)
virtual void pre_del_edge_handler (edge e)
virtual void post_del_edge_handler (node, node)
virtual void pre_hide_edge_handler (edge e)
virtual void post_hide_edge_handler (edge e)
virtual void pre_restore_edge_handler (edge e)
virtual void post_restore_edge_handler (edge e)
virtual void pre_clear_handler ()
virtual void post_clear_handler ()
virtual void pre_make_directed_handler ()
virtual void post_make_directed_handler ()
virtual void pre_make_undirected_handler ()
virtual void post_make_undirected_handler ()
virtual void pre_graph_save_handler (ostream *os) const
virtual void save_graph_info_handler (ostream *) const
virtual void save_node_info_handler (ostream *, node) const
virtual void after_graph_save_handler (ostream *) const
virtual void top_level_key_handler (GML_pair *list)
virtual void load_node_info_handler (node n, GML_pair *list)
virtual void load_edge_info_handler (edge e, GML_pair *list)
virtual void load_graph_info_handler (GML_pair *list)
int number_of_ids (node) const
int number_of_ids (edge) const
Private Attributes
node_map< int > XX
edge_map< parton > PP
Additional Inherited Members
Public Types inherited from graph
typedef list< node >
::const_iterator node_iterator
typedef list< edge >
::const_iterator edge_iterator
Detailed Description
Definition at line 60 of file my_test.cc.
View newest version in sPHENIX GitHub at line 60 of file my_test.cc
Constructor & Destructor Documentation
shower::shower () inline
Definition at line 64 of file my_test.cc.
View newest version in sPHENIX GitHub at line 64 of file my_test.cc
shower::shower () inline
Definition at line 52 of file my_test2.cc.
View newest version in sPHENIX GitHub at line 52 of file my_test2.cc
shower::~shower () inline
Definition at line 53 of file my_test2.cc.
View newest version in sPHENIX GitHub at line 53 of file my_test2.cc
Member Function Documentation
double shower::GetEdgeValue (edge n) const inline
Definition at line 59 of file my_test2.cc.
View newest version in sPHENIX GitHub at line 59 of file my_test2.cc
References n, and PP.
double shower::GetEdgeValue (edge n) const inline
Definition at line 70 of file my_test.cc.
View newest version in sPHENIX GitHub at line 70 of file my_test.cc
References n, and PP.
Referenced by main().
int shower::GetNodeValue (node n) const inline
Definition at line 57 of file my_test2.cc.
View newest version in sPHENIX GitHub at line 57 of file my_test2.cc
References n, and XX.
int shower::GetNodeValue (node n) const inline
Definition at line 68 of file my_test.cc.
View newest version in sPHENIX GitHub at line 68 of file my_test.cc
References n, and XX.
Referenced by main().
void shower::new_parton (node s, node t, parton p) inline
Definition at line 56 of file my_test2.cc.
View newest version in sPHENIX GitHub at line 56 of file my_test2.cc
References Acts::UnitConstants::e, graph::new_edge(), merge_hashes::p, and PP.
void shower::new_parton (node s, node t, parton p) inline
Definition at line 67 of file my_test.cc.
View newest version in sPHENIX GitHub at line 67 of file my_test.cc
References Acts::UnitConstants::e, graph::new_edge(), merge_hashes::p, and PP.
Referenced by main().
node shower::new_vertex (int x) inline
Definition at line 55 of file my_test2.cc.
View newest version in sPHENIX GitHub at line 55 of file my_test2.cc
References n, graph::new_node(), ambiguity_solver_full_chain::x, and XX.
node shower::new_vertex (int x) inline
Definition at line 66 of file my_test.cc.
View newest version in sPHENIX GitHub at line 66 of file my_test.cc
References n, graph::new_node(), ambiguity_solver_full_chain::x, and XX.
Referenced by main().
void shower::save_edge_info_handler (ostream * , edge) const inline virtual
Called before the closing bracket of the list belonging to the key of edge e is written. This can be used to write information belonging to the edge e and thus should appear within the list associated with this edge.
Parameters
<code>os</code> output stream.
See Also
graph::save
Reimplemented from graph.
Definition at line 58 of file my_test2.cc.
View newest version in sPHENIX GitHub at line 58 of file my_test2.cc
References n, and PP.
void shower::save_edge_info_handler (ostream * , edge) const inline virtual
Called before the closing bracket of the list belonging to the key of edge e is written. This can be used to write information belonging to the edge e and thus should appear within the list associated with this edge.
Parameters
<code>os</code> output stream.
See Also
graph::save
Reimplemented from graph.
Definition at line 69 of file my_test.cc.
View newest version in sPHENIX GitHub at line 69 of file my_test.cc
References n, and PP.
Member Data Documentation
edge_map< parton > shower::PP private
Definition at line 75 of file my_test.cc.
View newest version in sPHENIX GitHub at line 75 of file my_test.cc
Referenced by GetEdgeValue(), new_parton(), and save_edge_info_handler().
node_map< int > shower::XX private
Definition at line 74 of file my_test.cc.
View newest version in sPHENIX GitHub at line 74 of file my_test.cc
Referenced by GetNodeValue(), and new_vertex().
The documentation for this class was generated from the following files:
JETSCAPE/blob/main/external_packages/gtl/tests/my_test.cc
JETSCAPE/blob/main/external_packages/gtl/tests/my_test2.cc