Analysis Software: MbdGeom Class Reference
MbdGeom Class Reference
#include <coresoftware/blob/master/offline/packages/mbd/MbdGeom.h>
Public Member Functions
MbdGeom ()=default
~MbdGeom () override
virtual float get_x (const unsigned int) const
virtual float get_y (const unsigned int) const
virtual float get_z (const unsigned int) const
virtual float get_r (const unsigned int) const
virtual float get_phi (const unsigned int) const
virtual int get_arm (const unsigned int) const
virtual int get_feech (const unsigned int) const
virtual void set_xyz (const unsigned int, const float, const float, const float)
virtual int get_arm_feech (const unsigned int) const
virtual int get_pmt (const unsigned int) const
virtual int get_type (const unsigned int) const
virtual void Reset () override
Clear Event.
Public Member Functions inherited from PHObject
PHObject ()
ctor
~PHObject () override
dtor
virtual PHObject * CloneMe () const
Virtual copy constructor.
virtual PHObject * clone () const final
PHObject * Clone (const char *newname="") const final
void Copy (TObject &object) const final
virtual void identify (std::ostream &os=std::cout) const
virtual int isValid () const
isValid returns non zero if object contains vailid data
virtual int Integrate () const
virtual int Integrate (PHObject *)
virtual void CopyFrom (const PHObject *obj)
Private Member Functions
ClassDefOverride (MbdGeom, 1)
Detailed Description
Definition at line 12 of file MbdGeom.h.
View newest version in sPHENIX GitHub at line 12 of file MbdGeom.h
Constructor & Destructor Documentation
MbdGeom::MbdGeom () default
MbdGeom::~MbdGeom () inline override
Definition at line 16 of file MbdGeom.h.
View newest version in sPHENIX GitHub at line 16 of file MbdGeom.h
Member Function Documentation
MbdGeom::ClassDefOverride (MbdGeom , 1) private
virtual int MbdGeom::get_arm (const unsigned int) const inline virtual
Reimplemented in MbdGeomV1.
Definition at line 23 of file MbdGeom.h.
View newest version in sPHENIX GitHub at line 23 of file MbdGeom.h
Referenced by EventPlaneReco::process_event(), BBCStudy::process_event(), and DumpMbdGeom::process_Node().
virtual int MbdGeom::get_arm_feech (const unsigned int) const inline virtual
Reimplemented in MbdGeomV1.
Definition at line 28 of file MbdGeom.h.
View newest version in sPHENIX GitHub at line 28 of file MbdGeom.h
Referenced by DumpMbdGeom::process_Node().
virtual int MbdGeom::get_feech (const unsigned int) const inline virtual
Reimplemented in MbdGeomV1.
Definition at line 24 of file MbdGeom.h.
View newest version in sPHENIX GitHub at line 24 of file MbdGeom.h
virtual float MbdGeom::get_phi (const unsigned int) const inline virtual
Reimplemented in MbdGeomV1.
Definition at line 22 of file MbdGeom.h.
View newest version in sPHENIX GitHub at line 22 of file MbdGeom.h
Referenced by EventPlaneReco::process_event(), mbdAnalysis::process_event(), and DumpMbdGeom::process_Node().
virtual int MbdGeom::get_pmt (const unsigned int) const inline virtual
Reimplemented in MbdGeomV1.
Definition at line 29 of file MbdGeom.h.
View newest version in sPHENIX GitHub at line 29 of file MbdGeom.h
Referenced by DumpMbdGeom::process_Node(), and MbdEvent::SetRawData().
virtual float MbdGeom::get_r (const unsigned int) const inline virtual
Reimplemented in MbdGeomV1.
Definition at line 21 of file MbdGeom.h.
View newest version in sPHENIX GitHub at line 21 of file MbdGeom.h
Referenced by mbdAnalysis::process_event(), and DumpMbdGeom::process_Node().
virtual int MbdGeom::get_type (const unsigned int) const inline virtual
Reimplemented in MbdGeomV1.
Definition at line 30 of file MbdGeom.h.
View newest version in sPHENIX GitHub at line 30 of file MbdGeom.h
Referenced by MbdEvent::InitRun(), DumpMbdGeom::process_Node(), and MbdEvent::SetRawData().
virtual float MbdGeom::get_x (const unsigned int) const inline virtual
Reimplemented in MbdGeomV1.
Definition at line 18 of file MbdGeom.h.
View newest version in sPHENIX GitHub at line 18 of file MbdGeom.h
Referenced by mbdAnalysis::process_event(), BBCStudy::process_event(), and DumpMbdGeom::process_Node().
virtual float MbdGeom::get_y (const unsigned int) const inline virtual
Reimplemented in MbdGeomV1.
Definition at line 19 of file MbdGeom.h.
View newest version in sPHENIX GitHub at line 19 of file MbdGeom.h
Referenced by mbdAnalysis::process_event(), BBCStudy::process_event(), and DumpMbdGeom::process_Node().
virtual float MbdGeom::get_z (const unsigned int) const inline virtual
Reimplemented in MbdGeomV1.
Definition at line 20 of file MbdGeom.h.
View newest version in sPHENIX GitHub at line 20 of file MbdGeom.h
Referenced by mbdAnalysis::process_event(), and DumpMbdGeom::process_Node().
virtual void MbdGeom::Reset () inline override virtual
Clear Event.
Reimplemented from PHObject.
Reimplemented in MbdGeomV1.
Definition at line 32 of file MbdGeom.h.
View newest version in sPHENIX GitHub at line 32 of file MbdGeom.h
virtual void MbdGeom::set_xyz (const unsigned int , const float , const float , const float) inline virtual
Reimplemented in MbdGeomV1.
Definition at line 25 of file MbdGeom.h.
View newest version in sPHENIX GitHub at line 25 of file MbdGeom.h
The documentation for this class was generated from the following file:
coresoftware/blob/master/offline/packages/mbd/MbdGeom.h