Analysis Software: ActsExamples::MockupSectorBuilder Class Reference
ActsExamples::MockupSectorBuilder Class Reference
#include <acts/blob/sPHENIX/Examples/Detectors/MuonSpectrometerMockupDetector/include/ActsExamples/MuonSpectrometerMockupDetector/MockupSectorBuilder.hpp>
Classes
struct ChamberConfig
Nested configuration struct for chamber.
struct Config
Nested configuration struct.
Public Member Functions
MockupSectorBuilder (const Config &config)
~MockupSectorBuilder ()=default
Destructor.
std::shared_ptr
< Acts::Experimental::DetectorVolume > buildChamber (const ChamberConfig &chamberConfig)
std::shared_ptr
< Acts::Experimental::DetectorVolume > buildSector (std::vector< std::shared_ptr< Acts::Experimental::DetectorVolume >> detVolumes)
void drawSector (const std::shared_ptr< Acts::Experimental::DetectorVolume > &detectorVolumeSector, const std::string &nameObjFile)
Private Attributes
Config mCfg
G4VPhysicalVolume * g4World = nullptr
int maxNumberOfSectors = 8
Detailed Description
Definition at line 33 of file MockupSectorBuilder.hpp.
View newest version in sPHENIX GitHub at line 33 of file MockupSectorBuilder.hpp
Constructor & Destructor Documentation
ActsExamples::MockupSectorBuilder::MockupSectorBuilder (const Config & config)
Constructor
Parameters
config The configuration struct
Definition at line 46 of file MockupSectorBuilder.cpp.
View newest version in sPHENIX GitHub at line 46 of file MockupSectorBuilder.cpp
References filter::config, ActsExamples::GdmlDetectorConstruction::Construct(), g4World, ActsExamples::MockupSectorBuilder::Config::gdmlPath, and mCfg.
ActsExamples::MockupSectorBuilder::~MockupSectorBuilder () default
Destructor.
Member Function Documentation
std::shared_ptr< Acts::Experimental::DetectorVolume > ActsExamples::MockupSectorBuilder::buildChamber (const ChamberConfig & chamberConfig)
Build chamber
Parameters
gctx The current geometry context object
chamber_config The configuration chamber struct
Definition at line 54 of file MockupSectorBuilder.cpp.
View newest version in sPHENIX GitHub at line 54 of file MockupSectorBuilder.cpp
References filter::Config, Acts::Experimental::DetectorVolumeFactory::construct(), Acts::Experimental::defaultPortalAndSubPortalGenerator(), gctx, Acts::getDummyLogger(), Acts::Test::hx, Acts::Test::hy, Acts::Test::hz, Acts::UnitConstants::min, Acts::min_max(), testing::internal::move(), ActsExamples::MockupSectorBuilder::ChamberConfig::name, ActsExamples::MockupSectorBuilder::ChamberConfig::PassiveNames, ActsExamples::MockupSectorBuilder::ChamberConfig::SensitiveNames, Acts::Experimental::tryAllPortalsAndSurfaces(), and Acts::Experimental::tryAllSubVolumes().
Referenced by main().
std::shared_ptr< Acts::Experimental::DetectorVolume > ActsExamples::MockupSectorBuilder::buildSector (std::vector< std::shared_ptr< Acts::Experimental::DetectorVolume >> detVolumes)
Build Sector
Parameters
det_volumes The vector that contains the detector volumes of the Sector
gctx The current geometry context object
Definition at line 160 of file MockupSectorBuilder.cpp.
View newest version in sPHENIX GitHub at line 160 of file MockupSectorBuilder.cpp
References bounds, Acts::Experimental::DetectorVolumeFactory::construct(), Acts::Experimental::defaultPortalAndSubPortalGenerator(), gctx, i, testing::internal::move(), Acts::VectorHelpers::phi(), Acts::Test::pos, Acts::Experimental::detail::BlueprintHelper::sort(), to_string(), Acts::Test::transform, Acts::Experimental::tryAllPortalsAndSurfaces(), and Acts::Experimental::tryAllSubVolumes().
Referenced by main().
void ActsExamples::MockupSectorBuilder::drawSector (const std::shared_ptr< Acts::Experimental::DetectorVolume > & detectorVolumeSector, const std::string & nameObjFile)
Draw the sector in an obj file
Parameters
nameObjFile The name of the obj file where the sector will be saved
Definition at line 321 of file MockupSectorBuilder.cpp.
View newest version in sPHENIX GitHub at line 321 of file MockupSectorBuilder.cpp
References Acts::GeometryView3D::drawDetectorVolume(), Acts::s_viewSensitive, and Acts::ObjVisualization3D< T >::write().
Referenced by main().
Member Data Documentation
G4VPhysicalVolume* ActsExamples::MockupSectorBuilder::g4World = nullptr private
Definition at line 87 of file MockupSectorBuilder.hpp.
View newest version in sPHENIX GitHub at line 87 of file MockupSectorBuilder.hpp
Referenced by MockupSectorBuilder().
int ActsExamples::MockupSectorBuilder::maxNumberOfSectors = 8 private
Definition at line 89 of file MockupSectorBuilder.hpp.
View newest version in sPHENIX GitHub at line 89 of file MockupSectorBuilder.hpp
Config ActsExamples::MockupSectorBuilder::mCfg private
Definition at line 85 of file MockupSectorBuilder.hpp.
View newest version in sPHENIX GitHub at line 85 of file MockupSectorBuilder.hpp
Referenced by MockupSectorBuilder().
The documentation for this class was generated from the following files:
acts/blob/sPHENIX/Examples/Detectors/MuonSpectrometerMockupDetector/include/ActsExamples/MuonSpectrometerMockupDetector/MockupSectorBuilder.hpp
acts/blob/sPHENIX/Examples/Detectors/MuonSpectrometerMockupDetector/src/MockupSectorBuilder.cpp