Analysis Software: cl::CommandQueue Class Reference
cl::CommandQueue Class Reference
CommandQueue interface for cl_command_queue.
#include <JETSCAPE/blob/main/external_packages/clvisc_wrapper/include/cl.hpp>
Public Member Functions
CommandQueue (const Context &context, const Device &device, cl_command_queue_properties properties=0, cl_int *err=NULL)
CommandQueue ()
CommandQueue (const CommandQueue &commandQueue)
CommandQueue & operator= (const CommandQueue &rhs)
template<typename T >
cl_int getInfo (cl_command_queue_info name, T *param) const
template<cl_int name>
detail::param_traits
< detail::cl_command_queue_info,
name >::param_type getInfo (cl_int *err=NULL) const
cl_int enqueueReadBuffer (const Buffer &buffer, cl_bool blocking,::size_t offset,::size_t size, void *ptr, const VECTOR_CLASS< Event > *events=NULL, Event *event=NULL) const
cl_int enqueueWriteBuffer (const Buffer &buffer, cl_bool blocking,::size_t offset,::size_t size, const void *ptr, const VECTOR_CLASS< Event > *events=NULL, Event *event=NULL) const
cl_int enqueueCopyBuffer (const Buffer &src, const Buffer &dst,::size_t src_offset,::size_t dst_offset,::size_t size, const VECTOR_CLASS< Event > *events=NULL, Event *event=NULL) const
cl_int enqueueReadImage (const Image &image, cl_bool blocking, const size_t< 3 > &origin, const size_t< 3 > &region,::size_t row_pitch,::size_t slice_pitch, void *ptr, const VECTOR_CLASS< Event > *events=NULL, Event *event=NULL) const
cl_int enqueueWriteImage (const Image &image, cl_bool blocking, const size_t< 3 > &origin, const size_t< 3 > &region,::size_t row_pitch,::size_t slice_pitch, void *ptr, const VECTOR_CLASS< Event > *events=NULL, Event *event=NULL) const
cl_int enqueueCopyImage (const Image &src, const Image &dst, const size_t< 3 > &src_origin, const size_t< 3 > &dst_origin, const size_t< 3 > &region, const VECTOR_CLASS< Event > *events=NULL, Event *event=NULL) const
cl_int enqueueCopyImageToBuffer (const Image &src, const Buffer &dst, const size_t< 3 > &src_origin, const size_t< 3 > &region,::size_t dst_offset, const VECTOR_CLASS< Event > *events=NULL, Event *event=NULL) const
cl_int enqueueCopyBufferToImage (const Buffer &src, const Image &dst,::size_t src_offset, const size_t< 3 > &dst_origin, const size_t< 3 > &region, const VECTOR_CLASS< Event > *events=NULL, Event *event=NULL) const
void * enqueueMapBuffer (const Buffer &buffer, cl_bool blocking, cl_map_flags flags,::size_t offset,::size_t size, const VECTOR_CLASS< Event > *events=NULL, Event *event=NULL, cl_int *err=NULL) const
void * enqueueMapImage (const Image &buffer, cl_bool blocking, cl_map_flags flags, const size_t< 3 > &origin, const size_t< 3 > &region,::size_t *row_pitch,::size_t *slice_pitch, const VECTOR_CLASS< Event > *events=NULL, Event *event=NULL, cl_int *err=NULL) const
cl_int enqueueUnmapMemObject (const Memory &memory, void *mapped_ptr, const VECTOR_CLASS< Event > *events=NULL, Event *event=NULL) const
cl_int enqueueNDRangeKernel (const Kernel &kernel, const NDRange &offset, const NDRange &global, const NDRange &local, const VECTOR_CLASS< Event > *events=NULL, Event *event=NULL) const
cl_int enqueueTask (const Kernel &kernel, const VECTOR_CLASS< Event > *events=NULL, Event *event=NULL) const
cl_int enqueueNativeKernel (void(*userFptr)(void *), std::pair< void *,::size_t > args, const VECTOR_CLASS< Memory > *mem_objects=NULL, const VECTOR_CLASS< const void * > *mem_locs=NULL, const VECTOR_CLASS< Event > *events=NULL, Event *event=NULL) const
cl_int enqueueMarker (Event *event=NULL) const
cl_int enqueueWaitForEvents (const VECTOR_CLASS< Event > &events) const
cl_int enqueueAcquireGLObjects (const VECTOR_CLASS< Memory > *mem_objects=NULL, const VECTOR_CLASS< Event > *events=NULL, Event *event=NULL) const
cl_int enqueueReleaseGLObjects (const VECTOR_CLASS< Memory > *mem_objects=NULL, const VECTOR_CLASS< Event > *events=NULL, Event *event=NULL) const
cl_int enqueueBarrier () const
cl_int flush () const
cl_int finish () const
Public Member Functions inherited from cl::detail::Wrapper< cl_command_queue >
Wrapper ()
Wrapper (const Wrapper< cl_type > &rhs)
~Wrapper ()
Wrapper< cl_type > & operator= (const Wrapper< cl_type > &rhs)
cl_type operator() () const
cl_type & operator() ()
Additional Inherited Members
Public Types inherited from cl::detail::Wrapper< cl_command_queue >
typedef cl_command_queue cl_type
Protected Member Functions inherited from cl::detail::Wrapper< cl_command_queue >
cl_int retain () const
cl_int release () const
Protected Attributes inherited from cl::detail::Wrapper< cl_command_queue >
cl_type object_
Detailed Description
CommandQueue interface for cl_command_queue.
Definition at line 2559 of file cl.hpp.
View newest version in sPHENIX GitHub at line 2559 of file cl.hpp
Constructor & Destructor Documentation
cl::CommandQueue::CommandQueue (const Context & context, const Device & device, cl_command_queue_properties properties = 0, cl_int * err = NULL) inline
Definition at line 2562 of file cl.hpp.
View newest version in sPHENIX GitHub at line 2562 of file cl.hpp
References cl::detail::errHandler(), acts::error, and cl::detail::Wrapper< cl_command_queue >::object_.
cl::CommandQueue::CommandQueue () inline
Definition at line 2578 of file cl.hpp.
View newest version in sPHENIX GitHub at line 2578 of file cl.hpp
cl::CommandQueue::CommandQueue (const CommandQueue & commandQueue) inline
Definition at line 2580 of file cl.hpp.
View newest version in sPHENIX GitHub at line 2580 of file cl.hpp
Member Function Documentation
cl_int cl::CommandQueue::enqueueAcquireGLObjects (const VECTOR_CLASS< Memory > * mem_objects = NULL, const VECTOR_CLASS< Event > * events = NULL, Event * event = NULL) const inline
Definition at line 3017 of file cl.hpp.
View newest version in sPHENIX GitHub at line 3017 of file cl.hpp
References cl::detail::errHandler(), event, physmon_vertexing::events, and cl::detail::Wrapper< cl_command_queue >::object_.
cl_int cl::CommandQueue::enqueueBarrier () const inline
Definition at line 3098 of file cl.hpp.
View newest version in sPHENIX GitHub at line 3098 of file cl.hpp
References cl::detail::errHandler(), and cl::detail::Wrapper< cl_command_queue >::object_.
cl_int cl::CommandQueue::enqueueCopyBuffer (const Buffer & src, const Buffer & dst, ::size_t src_offset, ::size_t dst_offset, ::size_t size, const VECTOR_CLASS< Event > * events = NULL, Event * event = NULL) const inline
Definition at line 2650 of file cl.hpp.
View newest version in sPHENIX GitHub at line 2650 of file cl.hpp
References cl::detail::errHandler(), event, physmon_vertexing::events, and cl::detail::Wrapper< cl_command_queue >::object_.
Referenced by clvisc::OpenclBackend::enqueue_copy().
cl_int cl::CommandQueue::enqueueCopyBufferToImage (const Buffer & src, const Image & dst, ::size_t src_offset, const size_t< 3 > & dst_origin, const size_t< 3 > & region, const VECTOR_CLASS< Event > * events = NULL, Event * event = NULL) const inline
Definition at line 2848 of file cl.hpp.
View newest version in sPHENIX GitHub at line 2848 of file cl.hpp
References cl::detail::errHandler(), event, physmon_vertexing::events, and cl::detail::Wrapper< cl_command_queue >::object_.
cl_int cl::CommandQueue::enqueueCopyImage (const Image & src, const Image & dst, const size_t< 3 > & src_origin, const size_t< 3 > & dst_origin, const size_t< 3 > & region, const VECTOR_CLASS< Event > * events = NULL, Event * event = NULL) const inline
Definition at line 2810 of file cl.hpp.
View newest version in sPHENIX GitHub at line 2810 of file cl.hpp
References cl::detail::errHandler(), event, physmon_vertexing::events, and cl::detail::Wrapper< cl_command_queue >::object_.
cl_int cl::CommandQueue::enqueueCopyImageToBuffer (const Image & src, const Buffer & dst, const size_t< 3 > & src_origin, const size_t< 3 > & region, ::size_t dst_offset, const VECTOR_CLASS< Event > * events = NULL, Event * event = NULL) const inline
Definition at line 2829 of file cl.hpp.
View newest version in sPHENIX GitHub at line 2829 of file cl.hpp
References cl::detail::errHandler(), event, physmon_vertexing::events, and cl::detail::Wrapper< cl_command_queue >::object_.
void* cl::CommandQueue::enqueueMapBuffer (const Buffer & buffer, cl_bool blocking, cl_map_flags flags, ::size_t offset, ::size_t size, const VECTOR_CLASS< Event > * events = NULL, Event * event = NULL, cl_int * err = NULL) const inline
Definition at line 2867 of file cl.hpp.
View newest version in sPHENIX GitHub at line 2867 of file cl.hpp
References cl::detail::errHandler(), acts::error, event, physmon_vertexing::events, and cl::detail::Wrapper< cl_command_queue >::object_.
void* cl::CommandQueue::enqueueMapImage (const Image & buffer, cl_bool blocking, cl_map_flags flags, const size_t< 3 > & origin, const size_t< 3 > & region, ::size_t * row_pitch, ::size_t * slice_pitch, const VECTOR_CLASS< Event > * events = NULL, Event * event = NULL, cl_int * err = NULL) const inline
Definition at line 2892 of file cl.hpp.
View newest version in sPHENIX GitHub at line 2892 of file cl.hpp
References cl::detail::errHandler(), acts::error, event, physmon_vertexing::events, and cl::detail::Wrapper< cl_command_queue >::object_.
cl_int cl::CommandQueue::enqueueMarker (Event * event = NULL) const inline
Definition at line 3000 of file cl.hpp.
View newest version in sPHENIX GitHub at line 3000 of file cl.hpp
References cl::detail::errHandler(), event, and cl::detail::Wrapper< cl_command_queue >::object_.
cl_int cl::CommandQueue::enqueueNativeKernel (void(*)(void *) userFptr, std::pair< void *,::size_t > args, const VECTOR_CLASS< Memory > * mem_objects = NULL, const VECTOR_CLASS< const void * > * mem_locs = NULL, const VECTOR_CLASS< Event > * events = NULL, Event * event = NULL) const inline
Definition at line 2970 of file cl.hpp.
View newest version in sPHENIX GitHub at line 2970 of file cl.hpp
References cl::detail::errHandler(), event, physmon_vertexing::events, i, and cl::detail::Wrapper< cl_command_queue >::object_.
cl_int cl::CommandQueue::enqueueNDRangeKernel (const Kernel & kernel, const NDRange & offset, const NDRange & global, const NDRange & local, const VECTOR_CLASS< Event > * events = NULL, Event * event = NULL) const inline
Definition at line 2936 of file cl.hpp.
View newest version in sPHENIX GitHub at line 2936 of file cl.hpp
References cl::NDRange::dimensions(), cl::detail::errHandler(), event, physmon_vertexing::events, and cl::detail::Wrapper< cl_command_queue >::object_.
Referenced by clvisc::OpenclBackend::enqueue_run(), and cl::KernelFunctor::operator()().
cl_int cl::CommandQueue::enqueueReadBuffer (const Buffer & buffer, cl_bool blocking, ::size_t offset, ::size_t size, void * ptr, const VECTOR_CLASS< Event > * events = NULL, Event * event = NULL) const inline
Definition at line 2612 of file cl.hpp.
View newest version in sPHENIX GitHub at line 2612 of file cl.hpp
References cl::detail::errHandler(), event, physmon_vertexing::events, and cl::detail::Wrapper< cl_command_queue >::object_.
Referenced by clvisc::OpenclBackend::enqueue_copy().
cl_int cl::CommandQueue::enqueueReadImage (const Image & image, cl_bool blocking, const size_t< 3 > & origin, const size_t< 3 > & region, ::size_t row_pitch, ::size_t slice_pitch, void * ptr, const VECTOR_CLASS< Event > * events = NULL, Event * event = NULL) const inline
Definition at line 2768 of file cl.hpp.
View newest version in sPHENIX GitHub at line 2768 of file cl.hpp
References cl::detail::errHandler(), event, physmon_vertexing::events, and cl::detail::Wrapper< cl_command_queue >::object_.
cl_int cl::CommandQueue::enqueueReleaseGLObjects (const VECTOR_CLASS< Memory > * mem_objects = NULL, const VECTOR_CLASS< Event > * events = NULL, Event * event = NULL) const inline
Definition at line 3033 of file cl.hpp.
View newest version in sPHENIX GitHub at line 3033 of file cl.hpp
References cl::detail::errHandler(), event, physmon_vertexing::events, and cl::detail::Wrapper< cl_command_queue >::object_.
cl_int cl::CommandQueue::enqueueTask (const Kernel & kernel, const VECTOR_CLASS< Event > * events = NULL, Event * event = NULL) const inline
Definition at line 2956 of file cl.hpp.
View newest version in sPHENIX GitHub at line 2956 of file cl.hpp
References cl::detail::errHandler(), event, physmon_vertexing::events, and cl::detail::Wrapper< cl_command_queue >::object_.
cl_int cl::CommandQueue::enqueueUnmapMemObject (const Memory & memory, void * mapped_ptr, const VECTOR_CLASS< Event > * events = NULL, Event * event = NULL) const inline
Definition at line 2921 of file cl.hpp.
View newest version in sPHENIX GitHub at line 2921 of file cl.hpp
References cl::detail::errHandler(), event, physmon_vertexing::events, makeCondorJobs::memory, and cl::detail::Wrapper< cl_command_queue >::object_.
cl_int cl::CommandQueue::enqueueWaitForEvents (const VECTOR_CLASS< Event > & events) const inline
Definition at line 3007 of file cl.hpp.
View newest version in sPHENIX GitHub at line 3007 of file cl.hpp
References cl::detail::errHandler(), and cl::detail::Wrapper< cl_command_queue >::object_.
cl_int cl::CommandQueue::enqueueWriteBuffer (const Buffer & buffer, cl_bool blocking, ::size_t offset, ::size_t size, const void * ptr, const VECTOR_CLASS< Event > * events = NULL, Event * event = NULL) const inline
Definition at line 2631 of file cl.hpp.
View newest version in sPHENIX GitHub at line 2631 of file cl.hpp
References cl::detail::errHandler(), event, physmon_vertexing::events, and cl::detail::Wrapper< cl_command_queue >::object_.
Referenced by clvisc::OpenclBackend::enqueue_copy().
cl_int cl::CommandQueue::enqueueWriteImage (const Image & image, cl_bool blocking, const size_t< 3 > & origin, const size_t< 3 > & region, ::size_t row_pitch, ::size_t slice_pitch, void * ptr, const VECTOR_CLASS< Event > * events = NULL, Event * event = NULL) const inline
Definition at line 2789 of file cl.hpp.
View newest version in sPHENIX GitHub at line 2789 of file cl.hpp
References cl::detail::errHandler(), event, physmon_vertexing::events, and cl::detail::Wrapper< cl_command_queue >::object_.
cl_int cl::CommandQueue::finish () const inline
Definition at line 3110 of file cl.hpp.
View newest version in sPHENIX GitHub at line 3110 of file cl.hpp
References cl::detail::errHandler(), and cl::detail::Wrapper< cl_command_queue >::object_.
cl_int cl::CommandQueue::flush () const inline
Definition at line 3105 of file cl.hpp.
View newest version in sPHENIX GitHub at line 3105 of file cl.hpp
References cl::detail::errHandler(), and cl::detail::Wrapper< cl_command_queue >::object_.
template<typename T > cl_int cl::CommandQueue::getInfo (cl_command_queue_info name, T * param) const inline
Definition at line 2591 of file cl.hpp.
View newest version in sPHENIX GitHub at line 2591 of file cl.hpp
References cl::detail::errHandler(), cl::detail::getInfo(), and cl::detail::Wrapper< cl_command_queue >::object_.
Referenced by getInfo().
template<cl_int name> detail::param_traits<detail::cl_command_queue_info, name>::param_type cl::CommandQueue::getInfo (cl_int * err = NULL) const inline
Definition at line 2601 of file cl.hpp.
View newest version in sPHENIX GitHub at line 2601 of file cl.hpp
References getInfo(), and perf_headwind::name.
CommandQueue& cl::CommandQueue::operator= (const CommandQueue & rhs) inline
Definition at line 2582 of file cl.hpp.
View newest version in sPHENIX GitHub at line 2582 of file cl.hpp
References cl::detail::Wrapper< T >::operator=().
The documentation for this class was generated from the following file:
JETSCAPE/blob/main/external_packages/clvisc_wrapper/include/cl.hpp