Analysis Software: Acts::Logging::DefaultFilterPolicy Exception Reference
Acts::Logging::DefaultFilterPolicy Exception Reference final
default filter policy for debug messages
#include <acts/blob/sPHENIX/Core/include/Acts/Utilities/Logger.hpp>
Public Member Functions
DefaultFilterPolicy (Level lvl)
constructor
~DefaultFilterPolicy () override=default
virtual default destructor
bool doPrint (const Level &lvl) const override
decide whether a debug message should be processed
Level level () const override
std::unique_ptr
< OutputFilterPolicy > clone (Level level) const override
Public Member Functions inherited from Acts::Logging::OutputFilterPolicy
virtual ~OutputFilterPolicy ()=default
virtual default destructor
Private Attributes
Level m_level
threshold debug level for messages to be processed
Detailed Description
default filter policy for debug messages
All debug messages with a debug level equal or larger to the specified threshold level are processed.
Definition at line 293 of file Logger.hpp.
View newest version in sPHENIX GitHub at line 293 of file Logger.hpp
Constructor & Destructor Documentation
Acts::Logging::DefaultFilterPolicy::DefaultFilterPolicy (Level lvl) inline explicit
constructor
Parameters
[in] lvl threshold debug level
Definition at line 298 of file Logger.hpp.
View newest version in sPHENIX GitHub at line 298 of file Logger.hpp
References Acts::Logging::getFailureThreshold(), and Acts::Logging::levelName().
Acts::Logging::DefaultFilterPolicy::~DefaultFilterPolicy () override default
virtual default destructor
Member Function Documentation
std::unique_ptr<OutputFilterPolicy> Acts::Logging::DefaultFilterPolicy::clone (Level level) const inline override virtual
Make a copy of this filter policy with a new level
Parameters
level the new level
Returns
the new copy
Implements Acts::Logging::OutputFilterPolicy.
Definition at line 327 of file Logger.hpp.
View newest version in sPHENIX GitHub at line 327 of file Logger.hpp
References level().
bool Acts::Logging::DefaultFilterPolicy::doPrint (const Level & lvl) const inline override virtual
decide whether a debug message should be processed
Parameters
[in] lvl debug level of debug message
Returns
true if lvl >= m_level, otherwise false
Implements Acts::Logging::OutputFilterPolicy.
Definition at line 318 of file Logger.hpp.
View newest version in sPHENIX GitHub at line 318 of file Logger.hpp
References m_level.
Level Acts::Logging::DefaultFilterPolicy::level () const inline override virtual
Get the level of this filter policy
Returns
the levele
Implements Acts::Logging::OutputFilterPolicy.
Definition at line 322 of file Logger.hpp.
View newest version in sPHENIX GitHub at line 322 of file Logger.hpp
References m_level.
Referenced by clone().
Member Data Documentation
Level Acts::Logging::DefaultFilterPolicy::m_level private
threshold debug level for messages to be processed
Definition at line 333 of file Logger.hpp.
View newest version in sPHENIX GitHub at line 333 of file Logger.hpp
Referenced by doPrint(), and level().
The documentation for this exception was generated from the following file:
acts/blob/sPHENIX/Core/include/Acts/Utilities/Logger.hpp