Analysis Software: PHGenFit2::Track Class Reference
PHGenFit2::Track Class Reference
#include <coresoftware/blob/master/offline/packages/PHTpcTracker/Track.h>
Public Member Functions
Track (genfit::AbsTrackRep *rep, TVector3 seed_pos, TVector3 seed_mom, TMatrixDSym seed_cov, const int v=0)
Default ctor.
Track (const PHGenFit2::Track &t)
Copy constructor.
~Track ()
Default dtor.
int addMeasurement (PHGenFit::Measurement *measurement, int id=-1)
Add measurement.
int addMeasurements (std::vector< PHGenFit::Measurement * > &measurements, int id=-1)
int deleteLastMeasurement ()
int updateOneMeasurementKalman (const std::vector< PHGenFit::Measurement * > &measurements, std::map< double, std::shared_ptr< PHGenFit2::Track > > &incr_chi2s_new_tracks, const int base_tp_idx=-1, const int direction=1, const float blowup_factor=1., const bool use_fitted_state=false) const
double extrapolateToPlane (genfit::MeasuredStateOnPlane &state, TVector3 O, TVector3 n, const int tr_point_id=0) const
double extrapolateToLine (genfit::MeasuredStateOnPlane &state, TVector3 line_point, TVector3 line_direction, const int tr_point_id=0) const
double extrapolateToCylinder (genfit::MeasuredStateOnPlane &state, double radius, TVector3 line_point, TVector3 line_direction, const int tr_point_id=0, const int direction=1) const
double extrapolateToPoint (genfit::MeasuredStateOnPlane &state, TVector3 P, const int tr_point_id=0) const
genfit::MeasuredStateOnPlane * extrapolateToPlane (TVector3 O, TVector3 n, const int tr_point_id=0) const
genfit::MeasuredStateOnPlane * extrapolateToLine (TVector3 line_point, TVector3 line_direction, const int tr_point_id=0) const
genfit::MeasuredStateOnPlane * extrapolateToCylinder (double radius, TVector3 line_point, TVector3 line_direction, const int tr_point_id=0, const int direction=1) const
genfit::MeasuredStateOnPlane * extrapolateToPoint (TVector3 P, const int tr_point_id=0) const
genfit::Track * getGenFitTrack ()
genfit::Track * getGenFitTrack () const
double get_chi2 () const
double get_ndf () const
double get_charge () const
TVector3 get_mom () const
bool get_track_info (TVector3 &pos, TVector3 &mom, double &charge, int &nhits, double &length)
const std::vector< unsigned int > & get_cluster_IDs () const
void set_cluster_IDs (const std::vector< unsigned int > &clusterIDs)
const std::vector
< TrkrDefs::cluskey > & get_cluster_keys () const
void set_cluster_keys (const std::vector< TrkrDefs::cluskey > &clusterkeys)
void set_vertex_id (const unsigned int vert_id)
unsigned int get_vertex_id () const
int get_verbosity () const
void set_verbosity (int verbosity)
Private Member Functions
Track operator= (Track &trk)=delete
Private Attributes
int verbosity
genfit::Track * _track
std::vector< unsigned int > _clusterIDs
std::vector< TrkrDefs::cluskey > _clusterkeys
unsigned int _vertex_id
Detailed Description
Definition at line 34 of file Track.h.
View newest version in sPHENIX GitHub at line 34 of file Track.h
Constructor & Destructor Documentation
PHGenFit2::Track::Track (genfit::AbsTrackRep * rep, TVector3 seed_pos, TVector3 seed_mom, TMatrixDSym seed_cov, const int v = 0)
Default ctor.
Definition at line 62 of file Track.cc.
View newest version in sPHENIX GitHub at line 62 of file Track.cc
References _track, genfit::MeasuredStateOnPlane::get6DStateCov(), genfit::MeasuredStateOnPlane::setPosMomCov(), v, and verbosity.
PHGenFit2::Track::Track (const PHGenFit2::Track & t)
Copy constructor.
Definition at line 81 of file Track.cc.
View newest version in sPHENIX GitHub at line 81 of file Track.cc
References _clusterIDs, _clusterkeys, _track, _vertex_id, get_cluster_IDs(), get_cluster_keys(), get_vertex_id(), getGenFitTrack(), and verbosity.
PHGenFit2::Track::~Track ()
Default dtor.
Definition at line 140 of file Track.cc.
View newest version in sPHENIX GitHub at line 140 of file Track.cc
References _clusterIDs, _clusterkeys, and _track.
Member Function Documentation
int PHGenFit2::Track::addMeasurement (PHGenFit::Measurement * measurement, int id = -1)
Add measurement.
Definition at line 90 of file Track.cc.
View newest version in sPHENIX GitHub at line 90 of file Track.cc
References _clusterIDs, _clusterkeys, _track, PHGenFit::Measurement::get_cluster_ID(), PHGenFit::Measurement::get_cluster_key(), PHGenFit::Measurement::getMeasurement(), id, and genfit::Track::insertMeasurement().
Referenced by addMeasurements(), and PHTpcTrackFollower::followTrack().
int PHGenFit2::Track::addMeasurements (std::vector< PHGenFit::Measurement * > & measurements, int id = -1)
Definition at line 107 of file Track.cc.
View newest version in sPHENIX GitHub at line 107 of file Track.cc
References addMeasurement().
Referenced by PHTpcTrackFollower::candidate_to_genfit().
int PHGenFit2::Track::deleteLastMeasurement ()
Definition at line 130 of file Track.cc.
View newest version in sPHENIX GitHub at line 130 of file Track.cc
References _clusterIDs, _clusterkeys, _track, and genfit::Track::deletePoint().
double PHGenFit2::Track::extrapolateToCylinder (genfit::MeasuredStateOnPlane & state, double radius, TVector3 line_point, TVector3 line_direction, const int tr_point_id = 0, const int direction = 1) const
Definition at line 251 of file Track.cc.
View newest version in sPHENIX GitHub at line 251 of file Track.cc
References _track, assert, Acts::UnitConstants::e, genfit::AbsTrackRep::extrapolateToCylinder(), genfit::Track::getCardinalRep(), genfit::Track::getCovSeed(), genfit::TrackPoint::getFitterInfo(), genfit::Track::getNumPointsWithMeasurement(), genfit::Track::getPointWithMeasurement(), genfit::Track::getStateSeed(), LogError, LogWarning, genfit::AbsTrackRep::setPosMomCov(), verbosity, genfit::Exception::what(), and WILD_DOUBLE.
Referenced by extrapolateToCylinder().
genfit::MeasuredStateOnPlane * PHGenFit2::Track::extrapolateToCylinder (double radius, TVector3 line_point, TVector3 line_direction, const int tr_point_id = 0, const int direction = 1) const
Definition at line 353 of file Track.cc.
View newest version in sPHENIX GitHub at line 353 of file Track.cc
References assert, extrapolateToCylinder(), and WILD_DOUBLE.
double PHGenFit2::Track::extrapolateToLine (genfit::MeasuredStateOnPlane & state, TVector3 line_point, TVector3 line_direction, const int tr_point_id = 0) const
Definition at line 204 of file Track.cc.
View newest version in sPHENIX GitHub at line 204 of file Track.cc
References _track, Acts::UnitConstants::e, genfit::AbsTrackRep::extrapolateToLine(), genfit::Track::getCardinalRep(), genfit::TrackPoint::getFitterInfo(), genfit::Track::getPointWithMeasurementAndFitterInfo(), genfit::Exception::what(), and WILD_DOUBLE.
Referenced by extrapolateToLine().
genfit::MeasuredStateOnPlane * PHGenFit2::Track::extrapolateToLine (TVector3 line_point, TVector3 line_direction, const int tr_point_id = 0) const
Definition at line 238 of file Track.cc.
View newest version in sPHENIX GitHub at line 238 of file Track.cc
References extrapolateToLine(), and WILD_DOUBLE.
double PHGenFit2::Track::extrapolateToPlane (genfit::MeasuredStateOnPlane & state, TVector3 O, TVector3 n, const int tr_point_id = 0) const
track_point 0 is the first one, and -1 is the last one
Definition at line 155 of file Track.cc.
View newest version in sPHENIX GitHub at line 155 of file Track.cc
References _track, Acts::UnitConstants::e, genfit::AbsTrackRep::extrapolateToPlane(), genfit::Track::getCardinalRep(), genfit::TrackPoint::getFitterInfo(), genfit::Track::getPointWithMeasurementAndFitterInfo(), genfit::Exception::what(), and WILD_DOUBLE.
Referenced by extrapolateToPlane().
genfit::MeasuredStateOnPlane * PHGenFit2::Track::extrapolateToPlane (TVector3 O, TVector3 n, const int tr_point_id = 0) const
Definition at line 191 of file Track.cc.
View newest version in sPHENIX GitHub at line 191 of file Track.cc
References extrapolateToPlane(), and WILD_DOUBLE.
double PHGenFit2::Track::extrapolateToPoint (genfit::MeasuredStateOnPlane & state, TVector3 P, const int tr_point_id = 0) const
Definition at line 726 of file Track.cc.
View newest version in sPHENIX GitHub at line 726 of file Track.cc
References _track, Acts::UnitConstants::e, genfit::AbsTrackRep::extrapolateToPoint(), genfit::Track::getCardinalRep(), genfit::TrackPoint::getFitterInfo(), genfit::Track::getPointWithMeasurementAndFitterInfo(), genfit::Exception::what(), and WILD_DOUBLE.
Referenced by extrapolateToPoint().
genfit::MeasuredStateOnPlane * PHGenFit2::Track::extrapolateToPoint (TVector3 P, const int tr_point_id = 0) const
Definition at line 759 of file Track.cc.
View newest version in sPHENIX GitHub at line 759 of file Track.cc
References extrapolateToPoint(), and WILD_DOUBLE.
double PHGenFit2::Track::get_charge () const
Definition at line 800 of file Track.cc.
View newest version in sPHENIX GitHub at line 800 of file Track.cc
References _track, charge, genfit::Track::getCardinalRep(), genfit::AbsTrackRep::getCharge(), genfit::KalmanFitterInfo::getFittedState(), genfit::TrackPoint::getFitterInfo(), genfit::Track::getNumPointsWithMeasurement(), genfit::Track::getPointWithMeasurement(), and verbosity.
double PHGenFit2::Track::get_chi2 () const
Definition at line 772 of file Track.cc.
View newest version in sPHENIX GitHub at line 772 of file Track.cc
References _track, Acts::UnitConstants::fs, genfit::Track::getCardinalRep(), genfit::FitStatus::getChi2(), and genfit::Track::getFitStatus().
const std::vector<unsigned int>& PHGenFit2::Track::get_cluster_IDs () const inline
Definition at line 96 of file Track.h.
View newest version in sPHENIX GitHub at line 96 of file Track.h
References _clusterIDs.
Referenced by Track().
const std::vector<TrkrDefs::cluskey>& PHGenFit2::Track::get_cluster_keys () const inline
Definition at line 106 of file Track.h.
View newest version in sPHENIX GitHub at line 106 of file Track.h
References _clusterkeys.
Referenced by PHTpcTrackFollower::followTracks(), and Track().
TVector3 PHGenFit2::Track::get_mom () const
Definition at line 841 of file Track.cc.
View newest version in sPHENIX GitHub at line 841 of file Track.cc
References _track, genfit::Track::getCardinalRep(), genfit::KalmanFitterInfo::getFittedState(), genfit::TrackPoint::getFitterInfo(), genfit::StateOnPlane::getMom(), genfit::Track::getNumPointsWithMeasurement(), and genfit::Track::getPointWithMeasurement().
double PHGenFit2::Track::get_ndf () const
Definition at line 786 of file Track.cc.
View newest version in sPHENIX GitHub at line 786 of file Track.cc
References _track, Acts::UnitConstants::fs, genfit::Track::getCardinalRep(), genfit::Track::getFitStatus(), and genfit::FitStatus::getNdf().
bool PHGenFit2::Track::get_track_info (TVector3 & pos, TVector3 & mom, double & charge, int & nhits, double & length)
Definition at line 872 of file Track.cc.
View newest version in sPHENIX GitHub at line 872 of file Track.cc
References _track, genfit::StateOnPlane::getCharge(), genfit::KalmanFitterInfo::getFittedState(), genfit::TrackPoint::getKalmanFitterInfo(), genfit::Track::getNumPoints(), genfit::Track::getPointWithMeasurementAndFitterInfo(), genfit::StateOnPlane::getPosMom(), and genfit::Track::getTrackLen().
int PHGenFit2::Track::get_verbosity () const inline
Definition at line 126 of file Track.h.
View newest version in sPHENIX GitHub at line 126 of file Track.h
References verbosity.
unsigned int PHGenFit2::Track::get_vertex_id () const inline
Definition at line 120 of file Track.h.
View newest version in sPHENIX GitHub at line 120 of file Track.h
References _vertex_id.
Referenced by Track().
genfit::Track* PHGenFit2::Track::getGenFitTrack () inline
Definition at line 81 of file Track.h.
View newest version in sPHENIX GitHub at line 81 of file Track.h
References _track.
Referenced by PHTpcTrackFollower::followTrack(), PHTpcTrackFollower::followTracks(), PHTpcTrackFollower::get_track_layer(), PHGenFit2::Fitter::processTrack1(), PHGenFit2::Fitter::processTrack5(), PHGenFit2::Fitter::processTrackPartially(), PHTpcTrackFollower::propagateTrack(), and Track().
genfit::Track* PHGenFit2::Track::getGenFitTrack () const inline
Definition at line 83 of file Track.h.
View newest version in sPHENIX GitHub at line 83 of file Track.h
References _track.
Track PHGenFit2::Track::operator= (Track & trk) private delete
void PHGenFit2::Track::set_cluster_IDs (const std::vector< unsigned int > & clusterIDs) inline
Definition at line 100 of file Track.h.
View newest version in sPHENIX GitHub at line 100 of file Track.h
References _clusterIDs.
void PHGenFit2::Track::set_cluster_keys (const std::vector< TrkrDefs::cluskey > & clusterkeys) inline
Definition at line 110 of file Track.h.
View newest version in sPHENIX GitHub at line 110 of file Track.h
References _clusterkeys.
void PHGenFit2::Track::set_verbosity (int verbosity) inline
Definition at line 131 of file Track.h.
View newest version in sPHENIX GitHub at line 131 of file Track.h
References verbosity.
void PHGenFit2::Track::set_vertex_id (const unsigned int vert_id) inline
Definition at line 115 of file Track.h.
View newest version in sPHENIX GitHub at line 115 of file Track.h
References _vertex_id.
int PHGenFit2::Track::updateOneMeasurementKalman (const std::vector< PHGenFit::Measurement * > & measurements, std::map< double, std::shared_ptr< PHGenFit2::Track > > & incr_chi2s_new_tracks, const int base_tp_idx = -1, const int direction = 1, const float blowup_factor = 1., const bool use_fitted_state = false) const
A new TrackPoint created in addMeasurement PHGenFit: clusterID also registerd
Get the pointer of the TrackPoint just created
Definition at line 367 of file Track.cc.
View newest version in sPHENIX GitHub at line 367 of file Track.cc
References genfit::KalmanFitterInfo::addMeasurementsOnPlane(), genfit::MeasuredStateOnPlane::blowUpCov(), genfit::MeasuredStateOnPlane::clone(), Acts::Test::cov, Acts::UnitConstants::e, genfit::AbsTrackRep::extrapolateToPlane(), genfit::StateOnPlane::getAuxInfo(), genfit::MeasuredStateOnPlane::getCov(), genfit::KalmanFitterInfo::getFittedState(), genfit::TrackPoint::getFitterInfo(), genfit::MeasurementOnPlane::getHMatrix(), genfit::KalmanFitterInfo::getMeasurementsOnPlane(), genfit::KalmanFitterInfo::getPrediction(), genfit::TrackPoint::getRawMeasurements(), genfit::StateOnPlane::getState(), genfit::KalmanFitterInfo::getUpdate(), H, genfit::TrackPoint::hasFitterInfo(), genfit::tools::invertMatrix(), it, LogDebug, LogWarning, Acts::PrimitivesView3DTest::plane, genfit::StateOnPlane::setAuxInfo(), genfit::TrackPoint::setFitterInfo(), genfit::AbsTrackRep::setPosMomCov(), genfit::KalmanFitterInfo::setPrediction(), genfit::MeasuredStateOnPlane::setStateCovPlane(), genfit::KalmanFitterInfo::setUpdate(), Acts::KalmanVertexTrackUpdater::update(), verbosity, and genfit::Exception::what().
Member Data Documentation
std::vector<unsigned int> PHGenFit2::Track::_clusterIDs private
Definition at line 143 of file Track.h.
View newest version in sPHENIX GitHub at line 143 of file Track.h
Referenced by addMeasurement(), deleteLastMeasurement(), get_cluster_IDs(), set_cluster_IDs(), Track(), and ~Track().
std::vector<TrkrDefs::cluskey> PHGenFit2::Track::_clusterkeys private
Definition at line 144 of file Track.h.
View newest version in sPHENIX GitHub at line 144 of file Track.h
Referenced by addMeasurement(), deleteLastMeasurement(), get_cluster_keys(), set_cluster_keys(), Track(), and ~Track().
genfit::Track* PHGenFit2::Track::_track private
Definition at line 141 of file Track.h.
View newest version in sPHENIX GitHub at line 141 of file Track.h
Referenced by addMeasurement(), deleteLastMeasurement(), extrapolateToCylinder(), extrapolateToLine(), extrapolateToPlane(), extrapolateToPoint(), get_charge(), get_chi2(), get_mom(), get_ndf(), get_track_info(), getGenFitTrack(), Track(), and ~Track().
unsigned int PHGenFit2::Track::_vertex_id private
Definition at line 145 of file Track.h.
View newest version in sPHENIX GitHub at line 145 of file Track.h
Referenced by get_vertex_id(), set_vertex_id(), and Track().
int PHGenFit2::Track::verbosity private
Definition at line 139 of file Track.h.
View newest version in sPHENIX GitHub at line 139 of file Track.h
Referenced by extrapolateToCylinder(), get_charge(), get_verbosity(), set_verbosity(), Track(), and updateOneMeasurementKalman().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/PHTpcTracker/Track.h
coresoftware/blob/master/offline/packages/PHTpcTracker/Track.cc