Analysis Software: ActsExamples::EventRecording Exception Reference
ActsExamples::EventRecording Exception Reference final
#include <acts/blob/sPHENIX/Examples/Algorithms/Geant4HepMC/include/ActsExamples/Geant4HepMC/EventRecording.hpp>
Classes
class Config
Public Member Functions
EventRecording (const Config &config, Acts::Logging::Level level)
~EventRecording () override
ActsExamples::ProcessCode execute (const AlgorithmContext &context) const override
const Config & config () const
Readonly access to the config.
Public Member Functions inherited from ActsExamples::IAlgorithm
IAlgorithm (std::string name, Acts::Logging::Level level=Acts::Logging::INFO)
std::string name () const override
The algorithm name.
ProcessCode internalExecute (const AlgorithmContext &context) final
ProcessCode initialize () override
Initialize the algorithm.
ProcessCode finalize () override
Finalize the algorithm.
Private Attributes
Config m_cfg
The config object.
std::unique_ptr< G4RunManager > m_runManager
G4 run manager.
ReadDataHandle
< SimParticleContainer > m_inputParticles {this, "InputParticles"}
WriteDataHandle< std::vector
< HepMC3::GenEvent > > m_outputEvents
std::mutex m_runManagerLock
Additional Inherited Members
Protected Member Functions inherited from ActsExamples::IAlgorithm
const Acts::Logger & logger () const
Detailed Description
Definition at line 31 of file EventRecording.hpp.
View newest version in sPHENIX GitHub at line 31 of file EventRecording.hpp
Constructor & Destructor Documentation
ActsExamples::EventRecording::EventRecording (const Config & config, Acts::Logging::Level level)
Constructor
Parameters
config the configuration
level the log level
Definition at line 33 of file EventRecording.cpp.
View newest version in sPHENIX GitHub at line 33 of file EventRecording.cpp
References ActsExamples::EventRecording::Config::detectorConstructionFactory, ActsExamples::WriteDataHandle< T >::initialize(), ActsExamples::ReadDataHandle< T >::initialize(), ActsExamples::EventRecording::Config::inputParticles, m_cfg, m_inputParticles, m_outputEvents, m_runManager, ActsExamples::EventRecording::Config::outputHepMcTracks, ActsExamples::EventRecording::Config::processesCombine, ActsExamples::EventRecording::Config::processesReject, ActsExamples::EventRecording::Config::seed1, and ActsExamples::EventRecording::Config::seed2.
ActsExamples::EventRecording::~EventRecording () override
Definition at line 29 of file EventRecording.cpp.
View newest version in sPHENIX GitHub at line 29 of file EventRecording.cpp
References m_runManager.
Member Function Documentation
const Config& ActsExamples::EventRecording::config () const inline
Readonly access to the config.
Definition at line 67 of file EventRecording.hpp.
View newest version in sPHENIX GitHub at line 67 of file EventRecording.hpp
References m_cfg.
ActsExamples::ProcessCode ActsExamples::EventRecording::execute (const AlgorithmContext & context) const override virtual
Execute the algorithm for one event.
This function must be implemented by subclasses.
Implements ActsExamples::IAlgorithm.
Definition at line 69 of file EventRecording.cpp.
View newest version in sPHENIX GitHub at line 69 of file EventRecording.cpp
References ACTS_INFO, event, ActsExamples::Geant4::HepMC3::EventAction::event(), physmon_vertexing::events, Acts::UnitConstants::GeV, vertex::id, ActsExamples::Geant4::HepMC3::SteppingAction::instance(), ActsExamples::Geant4::HepMC3::EventAction::instance(), ActsExamples::Geant4::HepMC3::PrimaryGeneratorAction::instance(), m_cfg(), Acts::UnitConstants::mm, testing::internal::move(), merge_hashes::p, ActsExamples::Geant4::HepMC3::PrimaryGeneratorAction::prepareParticleGun(), SUCCESS, testSigmaEff::v, and value.
Member Data Documentation
Config ActsExamples::EventRecording::m_cfg private
The config object.
Definition at line 71 of file EventRecording.hpp.
View newest version in sPHENIX GitHub at line 71 of file EventRecording.hpp
Referenced by config(), and EventRecording().
ReadDataHandle<SimParticleContainer> ActsExamples::EventRecording::m_inputParticles {this, "InputParticles"} private
Definition at line 75 of file EventRecording.hpp.
View newest version in sPHENIX GitHub at line 75 of file EventRecording.hpp
Referenced by EventRecording().
WriteDataHandle<std::vector<HepMC3::GenEvent> > ActsExamples::EventRecording::m_outputEvents private
Initial value:
{this,
                                                                "OutputEvents"}
Definition at line 76 of file EventRecording.hpp.
View newest version in sPHENIX GitHub at line 76 of file EventRecording.hpp
Referenced by EventRecording().
std::unique_ptr<G4RunManager> ActsExamples::EventRecording::m_runManager private
G4 run manager.
Definition at line 73 of file EventRecording.hpp.
View newest version in sPHENIX GitHub at line 73 of file EventRecording.hpp
Referenced by EventRecording(), and ~EventRecording().
std::mutex ActsExamples::EventRecording::m_runManagerLock mutable private
Definition at line 80 of file EventRecording.hpp.
View newest version in sPHENIX GitHub at line 80 of file EventRecording.hpp
The documentation for this exception was generated from the following files:
acts/blob/sPHENIX/Examples/Algorithms/Geant4HepMC/include/ActsExamples/Geant4HepMC/EventRecording.hpp
acts/blob/sPHENIX/Examples/Algorithms/Geant4HepMC/src/EventRecording.cpp