Analysis Software: JETSCAPE/blob/main/external_packages/fjcore.hh File Reference
fjcore.hh File Reference
#include <cstdlib>
#include <iostream>
#include <string>
#include <list>
#include <vector>
#include <valarray>
#include <cassert>
#include <cmath>
#include <limits>
#include <memory>
#include <map>
#include <set>
Classes
struct integral_type< T, _t >
struct __inheritance_helper< B, D >
struct IsBaseAndDerived< B, D >
struct IsBaseAndDerived< B, D >::Host
class SharedPtr< T >
class SharedPtr< T >::__SharedCountingPtr
class LimitedWarning
class Error
class InternalError
class PseudoJetStructureBase
class PseudoJet
class PseudoJet::UserInfoBase
class PseudoJet::InexistentUserInfo
class IndexedSortHelper
class FunctionOfPseudoJet< TOut >
class SelectorWorker
class Selector
class Selector::InvalidWorker
class Selector::InvalidArea
class JetDefinition
class JetDefinition::Recombiner
class JetDefinition::DefaultRecombiner
class JetDefinition::Plugin
class CompositeJetStructure
class ClusterSequenceStructure
class ClusterSequence
class ClusterSequence::Extras
struct ClusterSequence::history_element
class ClusterSequence::_Parabola
class ClusterSequence::_Line
struct ClusterSequence::BriefJet
class ClusterSequence::TiledJet
struct ClusterSequence::Tile
struct ClusterSequence::EEBriefJet
class _NoInfo
class NNInfo< I >
class NNInfo< _NoInfo >
class NNBase< I >
class NNH< BJ, I >
class NNH< BJ, I >::NNBJ
Macros
#define __FJCORE__
#define __FJCORE_DROP_CGAL
#define _INCLUDE_FJCORE_CONFIG_AUTO_H 1
#define FJCORE_HAVE_DLFCN_H 1
#define FJCORE_HAVE_INTTYPES_H 1
#define FJCORE_HAVE_LIBM 1
#define FJCORE_HAVE_MEMORY_H 1
#define FJCORE_HAVE_STDINT_H 1
#define FJCORE_HAVE_STDLIB_H 1
#define FJCORE_HAVE_STRINGS_H 1
#define FJCORE_HAVE_STRING_H 1
#define FJCORE_HAVE_SYS_STAT_H 1
#define FJCORE_HAVE_SYS_TYPES_H 1
#define FJCORE_HAVE_UNISTD_H 1
#define FJCORE_LT_OBJDIR ".libs/"
#define FJCORE_PACKAGE "fastjet"
#define FJCORE_PACKAGE_BUGREPORT ""
#define FJCORE_PACKAGE_NAME "FastJet"
#define FJCORE_PACKAGE_STRING "FastJet 3.2.1"
#define FJCORE_PACKAGE_TARNAME "fastjet"
#define FJCORE_PACKAGE_URL ""
#define FJCORE_PACKAGE_VERSION "3.2.1"
#define FJCORE_STDC_HEADERS 1
#define FJCORE_VERSION "3.2.1"
#define FJCORE_VERSION_MAJOR 3
#define FJCORE_VERSION_MINOR 2
#define FJCORE_VERSION_NUMBER 30201
#define FJCORE_VERSION_PATCHLEVEL 1
#define __FJCORE_CONFIG_H__
#define __FJCORE_FASTJET_BASE_HH__
#define FJCORE_BEGIN_NAMESPACE namespace fjcore {
#define FJCORE_END_NAMESPACE }
#define FJCORE_OVERRIDE
#define __FJCORE_NUMCONSTS__
#define __FJCORE_INTERNAL_IS_BASE_HH__
#define __FJCORE_FJCORE_DEPRECATED_HH__
#define FJCORE_DEPRECATED
#define FJCORE_DEPRECATED_MSG(message)
#define __FJCORE_SHARED_PTR_HH__
#define __FJCORE_LIMITEDWARNING_HH__
#define __FJCORE_ERROR_HH__
#define __FJCORE_PSEUDOJET_STRUCTURE_BASE_HH__
#define __FJCORE_PSEUDOJET_HH__
#define __FJCORE_FUNCTION_OF_PSEUDOJET_HH__
#define __FJCORE_SELECTOR_HH__
#define __FJCORE_JETDEFINITION_HH__
#define __FJCORE_COMPOSITEJET_STRUCTURE_HH__
#define __FJCORE_CLUSTER_SEQUENCE_STRUCTURE_HH__
#define __FJCORE_CLUSTERSEQUENCE_HH__
#define __FJCORE_NNBASE_HH__
#define __FJCORE_NNH_HH__
Typedefs
typedef integral_type< bool, true > true_type
the bool 'true' value promoted to a type
typedef integral_type< bool,
false > false_type
the bool 'false' value promoted to a type
typedef char(& __yes_type)[1]
typedef char(& __no_type)[2]
typedef JetAlgorithm JetFinder
Enumerations
enum Strategy {
N2MHTLazy9AntiKtSeparateGhosts = -10, N2MHTLazy9 = -7, N2MHTLazy25 = -6, N2MHTLazy9Alt = -5,
N2MinHeapTiled = -4, N2Tiled = -3, N2PoorTiled = -2, N2Plain = -1,
N3Dumb = 0, Best = 1, NlnN = 2, NlnN3pi = 3,
NlnN4pi = 4, NlnNCam4pi = 14, NlnNCam2pi2R = 13, NlnNCam = 12,
BestFJ30 = 21, plugin_strategy = 999
}
enum JetAlgorithm {
kt_algorithm =0, cambridge_algorithm =1, antikt_algorithm =2, genkt_algorithm =3,
cambridge_for_passive_algorithm =11, genkt_for_passive_algorithm =13, ee_kt_algorithm =50, ee_genkt_algorithm =53,
plugin_algorithm = 99, undefined_jet_algorithm = 999
}
enum RecombinationScheme {
E_scheme =0, pt_scheme =1, pt2_scheme =2, Et_scheme =3,
Et2_scheme =4, BIpt_scheme =5, BIpt2_scheme =6, WTA_pt_scheme =7,
WTA_modp_scheme =8, external_scheme = 99
}
Functions
template<class B , class D >
B * cast_if_derived (D *d)
template<class T , class U >
bool operator== (SharedPtr< T > const &t, SharedPtr< U > const &u)
template<class T , class U >
bool operator!= (SharedPtr< T > const &t, SharedPtr< U > const &u)
template<class T , class U >
bool operator< (SharedPtr< T > const &t, SharedPtr< U > const &u)
template<class T >
void swap (SharedPtr< T > &a, SharedPtr< T > &b)
template<class T >
T * get_pointer (SharedPtr< T > const &t)
PseudoJet operator+ (const PseudoJet &, const PseudoJet &)
PseudoJet operator- (const PseudoJet &, const PseudoJet &)
PseudoJet operator* (double, const PseudoJet &)
PseudoJet operator* (const PseudoJet &, double)
PseudoJet operator/ (const PseudoJet &, double)
bool operator== (const PseudoJet &, const PseudoJet &)
bool operator!= (const PseudoJet &a, const PseudoJet &b)
bool operator== (const PseudoJet &jet, const double val)
bool operator== (const double val, const PseudoJet &jet)
bool operator!= (const PseudoJet &a, const double val)
bool operator!= (const double val, const PseudoJet &a)
double dot_product (const PseudoJet &a, const PseudoJet &b)
bool have_same_momentum (const PseudoJet &, const PseudoJet &)
PseudoJet PtYPhiM (double pt, double y, double phi, double m=0.0)
std::vector< PseudoJet > sorted_by_pt (const std::vector< PseudoJet > &jets)
std::vector< PseudoJet > sorted_by_rapidity (const std::vector< PseudoJet > &jets)
std::vector< PseudoJet > sorted_by_E (const std::vector< PseudoJet > &jets)
std::vector< PseudoJet > sorted_by_pz (const std::vector< PseudoJet > &jets)
void sort_indices (std::vector< int > &indices, const std::vector< double > &values)
template<class T >
std::vector< T > objects_sorted_by_values (const std::vector< T > &objects, const std::vector< double > &values)
PseudoJet join (const std::vector< PseudoJet > &pieces)
PseudoJet join (const PseudoJet &j1)
PseudoJet join (const PseudoJet &j1, const PseudoJet &j2)
PseudoJet join (const PseudoJet &j1, const PseudoJet &j2, const PseudoJet &j3)
PseudoJet join (const PseudoJet &j1, const PseudoJet &j2, const PseudoJet &j3, const PseudoJet &j4)
Selector SelectorIdentity ()
Selector operator! (const Selector &s)
Selector operator|| (const Selector &s1, const Selector &s2)
Selector operator&& (const Selector &s1, const Selector &s2)
Selector operator* (const Selector &s1, const Selector &s2)
Selector SelectorPtMin (double ptmin)
select objects with pt >= ptmin
Selector SelectorPtMax (double ptmax)
select objects with pt <= ptmax
Selector SelectorPtRange (double ptmin, double ptmax)
select objects with ptmin <= pt <= ptmax
Selector SelectorEtMin (double Etmin)
select objects with Et >= Etmin
Selector SelectorEtMax (double Etmax)
select objects with Et <= Etmax
Selector SelectorEtRange (double Etmin, double Etmax)
select objects with Etmin <= Et <= Etmax
Selector SelectorEMin (double Emin)
select objects with E >= Emin
Selector SelectorEMax (double Emax)
select objects with E <= Emax
Selector SelectorERange (double Emin, double Emax)
select objects with Emin <= E <= Emax
Selector SelectorMassMin (double Mmin)
select objects with Mass >= Mmin
Selector SelectorMassMax (double Mmax)
select objects with Mass <= Mmax
Selector SelectorMassRange (double Mmin, double Mmax)
select objects with Mmin <= Mass <= Mmax
Selector SelectorRapMin (double rapmin)
select objects with rap >= rapmin
Selector SelectorRapMax (double rapmax)
select objects with rap <= rapmax
Selector SelectorRapRange (double rapmin, double rapmax)
select objects with rapmin <= rap <= rapmax
Selector SelectorAbsRapMin (double absrapmin)
select objects with |rap| >= absrapmin
Selector SelectorAbsRapMax (double absrapmax)
select objects with |rap| <= absrapmax
Selector SelectorAbsRapRange (double absrapmin, double absrapmax)
select objects with absrapmin <= |rap| <= absrapmax
Selector SelectorEtaMin (double etamin)
select objects with eta >= etamin
Selector SelectorEtaMax (double etamax)
select objects with eta <= etamax
Selector SelectorEtaRange (double etamin, double etamax)
select objects with etamin <= eta <= etamax
Selector SelectorAbsEtaMin (double absetamin)
select objects with |eta| >= absetamin
Selector SelectorAbsEtaMax (double absetamax)
select objects with |eta| <= absetamax
Selector SelectorAbsEtaRange (double absetamin, double absetamax)
select objects with absetamin <= |eta| <= absetamax
Selector SelectorPhiRange (double phimin, double phimax)
select objects with phimin <= phi <= phimax
Selector SelectorRapPhiRange (double rapmin, double rapmax, double phimin, double phimax)
Selector SelectorNHardest (unsigned int n)
Selector SelectorCircle (const double radius)
Selector SelectorDoughnut (const double radius_in, const double radius_out)
Selector SelectorStrip (const double half_width)
Selector SelectorRectangle (const double half_rap_width, const double half_phi_width)
Selector SelectorPtFractionMin (double fraction)
Selector SelectorIsZero ()
FJCORE_BEGIN_NAMESPACE std::string fastjet_version_string ()
PseudoJet join (const std::vector< PseudoJet > &pieces, const JetDefinition::Recombiner &recombiner)
PseudoJet join (const PseudoJet &j1, const JetDefinition::Recombiner &recombiner)
PseudoJet join (const PseudoJet &j1, const PseudoJet &j2, const JetDefinition::Recombiner &recombiner)
PseudoJet join (const PseudoJet &j1, const PseudoJet &j2, const PseudoJet &j3, const JetDefinition::Recombiner &recombiner)
PseudoJet join (const PseudoJet &j1, const PseudoJet &j2, const PseudoJet &j3, const PseudoJet &j4, const JetDefinition::Recombiner &recombiner)
Variables
FJCORE_BEGIN_NAMESPACE const double pi = 3.141592653589793238462643383279502884197
const double twopi = 6.283185307179586476925286766559005768394
const double pisq = 9.869604401089358618834490999876151135314
const double zeta2 = 1.644934066848226436472415166646025189219
const double zeta3 = 1.202056903159594285399738161511449990765
const double eulergamma = 0.577215664901532860606512090082402431042
const double ln2 = 0.693147180559945309417232121458176568076
FJCORE_BEGIN_NAMESPACE const double MaxRap = 1e5
const double pseudojet_invalid_phi = -100.0
const double pseudojet_invalid_rap = -1e200
const JetAlgorithm aachen_algorithm = cambridge_algorithm
const JetAlgorithm cambridge_aachen_algorithm = cambridge_algorithm
Macro Definition Documentation
#define __FJCORE__
Definition at line 80 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 80 of file fjcore.hh
#define __FJCORE_CLUSTER_SEQUENCE_STRUCTURE_HH__
Definition at line 1297 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 1297 of file fjcore.hh
#define __FJCORE_CLUSTERSEQUENCE_HH__
Definition at line 1337 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 1337 of file fjcore.hh
#define __FJCORE_COMPOSITEJET_STRUCTURE_HH__
Definition at line 1193 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 1193 of file fjcore.hh
#define __FJCORE_CONFIG_H__
Definition at line 167 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 167 of file fjcore.hh
#define __FJCORE_DROP_CGAL
Definition at line 81 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 81 of file fjcore.hh
#define __FJCORE_ERROR_HH__
Definition at line 442 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 442 of file fjcore.hh
#define __FJCORE_FASTJET_BASE_HH__
Definition at line 170 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 170 of file fjcore.hh
#define __FJCORE_FJCORE_DEPRECATED_HH__
Definition at line 244 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 244 of file fjcore.hh
#define __FJCORE_FUNCTION_OF_PSEUDOJET_HH__
Definition at line 809 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 809 of file fjcore.hh
#define __FJCORE_INTERNAL_IS_BASE_HH__
Definition at line 192 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 192 of file fjcore.hh
#define __FJCORE_JETDEFINITION_HH__
Definition at line 978 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 978 of file fjcore.hh
#define __FJCORE_LIMITEDWARNING_HH__
Definition at line 409 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 409 of file fjcore.hh
#define __FJCORE_NNBASE_HH__
Definition at line 1735 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 1735 of file fjcore.hh
#define __FJCORE_NNH_HH__
Definition at line 1765 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 1765 of file fjcore.hh
#define __FJCORE_NUMCONSTS__
Definition at line 180 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 180 of file fjcore.hh
#define __FJCORE_PSEUDOJET_HH__
Definition at line 510 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 510 of file fjcore.hh
#define __FJCORE_PSEUDOJET_STRUCTURE_BASE_HH__
Definition at line 475 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 475 of file fjcore.hh
#define __FJCORE_SELECTOR_HH__
Definition at line 829 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 829 of file fjcore.hh
#define __FJCORE_SHARED_PTR_HH__
Definition at line 257 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 257 of file fjcore.hh
#define _INCLUDE_FJCORE_CONFIG_AUTO_H 1
Definition at line 83 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 83 of file fjcore.hh
#define FJCORE_BEGIN_NAMESPACE namespace fjcore {
Definition at line 171 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 171 of file fjcore.hh
#define FJCORE_DEPRECATED
Definition at line 252 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 252 of file fjcore.hh
#define FJCORE_DEPRECATED_MSG (message)
Definition at line 253 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 253 of file fjcore.hh
#define FJCORE_END_NAMESPACE }
Definition at line 172 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 172 of file fjcore.hh
#define FJCORE_HAVE_DLFCN_H 1
Definition at line 87 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 87 of file fjcore.hh
#define FJCORE_HAVE_INTTYPES_H 1
Definition at line 94 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 94 of file fjcore.hh
#define FJCORE_HAVE_LIBM 1
Definition at line 97 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 97 of file fjcore.hh
#define FJCORE_HAVE_MEMORY_H 1
Definition at line 100 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 100 of file fjcore.hh
#define FJCORE_HAVE_STDINT_H 1
Definition at line 103 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 103 of file fjcore.hh
#define FJCORE_HAVE_STDLIB_H 1
Definition at line 106 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 106 of file fjcore.hh
#define FJCORE_HAVE_STRING_H 1
Definition at line 112 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 112 of file fjcore.hh
#define FJCORE_HAVE_STRINGS_H 1
Definition at line 109 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 109 of file fjcore.hh
#define FJCORE_HAVE_SYS_STAT_H 1
Definition at line 115 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 115 of file fjcore.hh
#define FJCORE_HAVE_SYS_TYPES_H 1
Definition at line 118 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 118 of file fjcore.hh
#define FJCORE_HAVE_UNISTD_H 1
Definition at line 121 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 121 of file fjcore.hh
#define FJCORE_LT_OBJDIR ".libs/"
Definition at line 124 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 124 of file fjcore.hh
#define FJCORE_OVERRIDE
Definition at line 176 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 176 of file fjcore.hh
#define FJCORE_PACKAGE "fastjet"
Definition at line 127 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 127 of file fjcore.hh
#define FJCORE_PACKAGE_BUGREPORT ""
Definition at line 130 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 130 of file fjcore.hh
#define FJCORE_PACKAGE_NAME "FastJet"
Definition at line 133 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 133 of file fjcore.hh
#define FJCORE_PACKAGE_STRING "FastJet 3.2.1"
Definition at line 136 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 136 of file fjcore.hh
#define FJCORE_PACKAGE_TARNAME "fastjet"
Definition at line 139 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 139 of file fjcore.hh
#define FJCORE_PACKAGE_URL ""
Definition at line 142 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 142 of file fjcore.hh
#define FJCORE_PACKAGE_VERSION "3.2.1"
Definition at line 145 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 145 of file fjcore.hh
#define FJCORE_STDC_HEADERS 1
Definition at line 148 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 148 of file fjcore.hh
#define FJCORE_VERSION "3.2.1"
Definition at line 151 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 151 of file fjcore.hh
#define FJCORE_VERSION_MAJOR 3
Definition at line 154 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 154 of file fjcore.hh
#define FJCORE_VERSION_MINOR 2
Definition at line 157 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 157 of file fjcore.hh
#define FJCORE_VERSION_NUMBER 30201
Definition at line 160 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 160 of file fjcore.hh
#define FJCORE_VERSION_PATCHLEVEL 1
Definition at line 163 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 163 of file fjcore.hh
Typedef Documentation
typedef char(& __no_type)[2]
Definition at line 205 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 205 of file fjcore.hh
typedef char(& __yes_type)[1]
Definition at line 204 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 204 of file fjcore.hh
typedef integral_type<bool, false> false_type
the bool 'false' value promoted to a type
Definition at line 203 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 203 of file fjcore.hh
typedef JetAlgorithm JetFinder
Definition at line 1016 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 1016 of file fjcore.hh
typedef integral_type<bool, true> true_type
the bool 'true' value promoted to a type
Definition at line 202 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 202 of file fjcore.hh
Enumeration Type Documentation
enum JetAlgorithm
Enumerator:
kt_algorithm
cambridge_algorithm
antikt_algorithm
genkt_algorithm
cambridge_for_passive_algorithm
genkt_for_passive_algorithm
ee_kt_algorithm
ee_genkt_algorithm
plugin_algorithm
undefined_jet_algorithm
Definition at line 1004 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 1004 of file fjcore.hh
enum RecombinationScheme
Enumerator:
E_scheme
pt_scheme
pt2_scheme
Et_scheme
Et2_scheme
BIpt_scheme
BIpt2_scheme
WTA_pt_scheme
WTA_modp_scheme
external_scheme
Definition at line 1019 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 1019 of file fjcore.hh
enum Strategy
Enumerator:
N2MHTLazy9AntiKtSeparateGhosts
N2MHTLazy9
N2MHTLazy25
N2MHTLazy9Alt
N2MinHeapTiled
N2Tiled
N2PoorTiled
N2Plain
N3Dumb
Best
NlnN
NlnN3pi
NlnN4pi
NlnNCam4pi
NlnNCam2pi2R
NlnNCam
BestFJ30
plugin_strategy
Definition at line 984 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 984 of file fjcore.hh
Function Documentation
template<class B , class D > B* cast_if_derived (D * d)
Definition at line 238 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 238 of file fjcore.hh
double dot_product (const PseudoJet & a, const PseudoJet & b) inline
Definition at line 713 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 713 of file fjcore.hh
References PseudoJet::E(), PseudoJet::px(), PseudoJet::py(), and PseudoJet::pz().
Referenced by GeneralElement::check_normal_direction().
FJCORE_BEGIN_NAMESPACE std::string fastjet_version_string ()
Definition at line 1547 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 1547 of file fjcore.cc
References fastjet_version.
template<class T > T* get_pointer (SharedPtr< T > const & t) inline
Definition at line 402 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 402 of file fjcore.hh
References SharedPtr< T >::get().
bool have_same_momentum (const PseudoJet & , const PseudoJet &)
Definition at line 3900 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 3900 of file fjcore.cc
PseudoJet join (const std::vector< PseudoJet > & pieces)
PseudoJet join (const PseudoJet & j1)
PseudoJet join (const PseudoJet & j1, const PseudoJet & j2)
PseudoJet join (const PseudoJet & j1, const PseudoJet & j2, const PseudoJet & j3)
PseudoJet join (const PseudoJet & j1, const PseudoJet & j2, const PseudoJet & j3, const PseudoJet & j4)
PseudoJet join (const std::vector< PseudoJet > & pieces, const JetDefinition::Recombiner & recombiner)
PseudoJet join (const PseudoJet & j1, const JetDefinition::Recombiner & recombiner)
PseudoJet join (const PseudoJet & j1, const PseudoJet & j2, const JetDefinition::Recombiner & recombiner)
PseudoJet join (const PseudoJet & j1, const PseudoJet & j2, const PseudoJet & j3, const JetDefinition::Recombiner & recombiner)
PseudoJet join (const PseudoJet & j1, const PseudoJet & j2, const PseudoJet & j3, const PseudoJet & j4, const JetDefinition::Recombiner & recombiner)
template<class T > std::vector<T> objects_sorted_by_values (const std::vector< T > & objects, const std::vector< double > & values)
Definition at line 724 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 724 of file fjcore.hh
References i, and sort_indices().
Referenced by sorted_by_E(), sorted_by_pt(), sorted_by_pz(), and sorted_by_rapidity().
Selector operator! (const Selector & s)
Definition at line 4317 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 4317 of file fjcore.cc
template<class T , class U > bool operator!= (SharedPtr< T > const & t, SharedPtr< U > const & u) inline
Definition at line 390 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 390 of file fjcore.hh
References SharedPtr< T >::get().
bool operator!= (const PseudoJet & a, const PseudoJet & b) inline
Definition at line 708 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 708 of file fjcore.hh
References KFPMath::b.
bool operator!= (const PseudoJet & a, const double val) inline
Definition at line 711 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 711 of file fjcore.hh
bool operator!= (const double val, const PseudoJet & a) inline
Definition at line 712 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 712 of file fjcore.hh
Selector operator&& (const Selector & s1, const Selector & s2)
Definition at line 4376 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 4376 of file fjcore.cc
PseudoJet operator* (double , const PseudoJet &)
Definition at line 3816 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 3816 of file fjcore.cc
PseudoJet operator* (const PseudoJet & , double)
Definition at line 3822 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 3822 of file fjcore.cc
Selector operator* (const Selector & s1, const Selector & s2)
Definition at line 4437 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 4437 of file fjcore.cc
PseudoJet operator+ (const PseudoJet & , const PseudoJet &)
Definition at line 3804 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 3804 of file fjcore.cc
PseudoJet operator- (const PseudoJet & , const PseudoJet &)
Definition at line 3810 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 3810 of file fjcore.cc
PseudoJet operator/ (const PseudoJet & , double)
Definition at line 3825 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 3825 of file fjcore.cc
template<class T , class U > bool operator< (SharedPtr< T > const & t, SharedPtr< U > const & u) inline
Definition at line 394 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 394 of file fjcore.hh
References physmon_ckf_tracking::u.
template<class T , class U > bool operator== (SharedPtr< T > const & t, SharedPtr< U > const & u) inline
Definition at line 386 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 386 of file fjcore.hh
References SharedPtr< T >::get().
bool operator== (const PseudoJet & , const PseudoJet &)
Definition at line 3853 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 3853 of file fjcore.cc
bool operator== (const PseudoJet & jet, const double val)
Definition at line 3864 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 3864 of file fjcore.cc
bool operator== (const double val, const PseudoJet & jet) inline
Definition at line 710 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 710 of file fjcore.hh
Selector operator|| (const Selector & s1, const Selector & s2)
Definition at line 4416 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 4416 of file fjcore.cc
PseudoJet PtYPhiM (double pt, double y, double phi, double m = 0.0)
Definition at line 3922 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 3922 of file fjcore.cc
References assert, and twopi.
Selector SelectorAbsEtaMax (double absetamax)
select objects with |eta| <= absetamax
Definition at line 4676 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 4676 of file fjcore.cc
Referenced by FastJetAlgo::calc_rhomeddens(), FastJetAlgo::cluster_and_fill(), RandomConeAna::EstimateRhos(), main(), and JetBkgdSub::process_event().
Selector SelectorAbsEtaMin (double absetamin)
select objects with |eta| >= absetamin
Definition at line 4673 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 4673 of file fjcore.cc
Selector SelectorAbsEtaRange (double absetamin, double absetamax)
select objects with absetamin <= |eta| <= absetamax
Definition at line 4679 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 4679 of file fjcore.cc
Selector SelectorAbsRapMax (double absrapmax)
select objects with |rap| <= absrapmax
Definition at line 4645 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 4645 of file fjcore.cc
Referenced by FastJetAlgo::get_selector(), main(), PHAJMaker::PHAJMaker(), and PHAJMaker::process_event().
Selector SelectorAbsRapMin (double absrapmin)
select objects with |rap| >= absrapmin
Definition at line 4642 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 4642 of file fjcore.cc
Selector SelectorAbsRapRange (double absrapmin, double absrapmax)
select objects with absrapmin <= |rap| <= absrapmax
Definition at line 4648 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 4648 of file fjcore.cc
Selector SelectorCircle (const double radius)
Definition at line 4799 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 4799 of file fjcore.cc
Referenced by PHAJMaker::process_event().
Selector SelectorDoughnut (const double radius_in, const double radius_out)
Definition at line 4833 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 4833 of file fjcore.cc
Selector SelectorEMax (double Emax)
select objects with E <= Emax
Definition at line 4544 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 4544 of file fjcore.cc
Selector SelectorEMin (double Emin)
select objects with E >= Emin
Definition at line 4541 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 4541 of file fjcore.cc
Selector SelectorERange (double Emin, double Emax)
select objects with Emin <= E <= Emax
Definition at line 4547 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 4547 of file fjcore.cc
Selector SelectorEtaMax (double etamax)
select objects with eta <= etamax
Definition at line 4660 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 4660 of file fjcore.cc
Selector SelectorEtaMin (double etamin)
select objects with eta >= etamin
Definition at line 4657 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 4657 of file fjcore.cc
Selector SelectorEtaRange (double etamin, double etamax)
select objects with etamin <= eta <= etamax
Definition at line 4663 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 4663 of file fjcore.cc
Selector SelectorEtMax (double Etmax)
select objects with Et <= Etmax
Definition at line 4529 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 4529 of file fjcore.cc
Selector SelectorEtMin (double Etmin)
select objects with Et >= Etmin
Definition at line 4526 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 4526 of file fjcore.cc
Selector SelectorEtRange (double Etmin, double Etmax)
select objects with Etmin <= Et <= Etmax
Definition at line 4532 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 4532 of file fjcore.cc
Selector SelectorIdentity ()
Definition at line 4282 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 4282 of file fjcore.cc
Referenced by PHAJMaker::PHAJMaker().
Selector SelectorIsZero ()
Definition at line 4929 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 4929 of file fjcore.cc
Selector SelectorMassMax (double Mmax)
select objects with Mass <= Mmax
Definition at line 4559 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 4559 of file fjcore.cc
Selector SelectorMassMin (double Mmin)
select objects with Mass >= Mmin
Definition at line 4556 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 4556 of file fjcore.cc
Selector SelectorMassRange (double Mmin, double Mmax)
select objects with Mmin <= Mass <= Mmax
Definition at line 4562 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 4562 of file fjcore.cc
Selector SelectorNHardest (unsigned int n)
Definition at line 4755 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 4755 of file fjcore.cc
Referenced by FastJetAlgo::calc_rhomeddens(), RandomConeAna::EstimateRhos(), JetBkgdSub::process_event(), and PHAJMaker::process_event().
Selector SelectorPhiRange (double phimin, double phimax)
select objects with phimin <= phi <= phimax
Definition at line 4707 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 4707 of file fjcore.cc
Selector SelectorPtFractionMin (double fraction)
Definition at line 4918 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 4918 of file fjcore.cc
Selector SelectorPtMax (double ptmax)
select objects with pt <= ptmax
Definition at line 4514 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 4514 of file fjcore.cc
Referenced by FastJetAlgo::first_call_init(), and PHAJMaker::PHAJMaker().
Selector SelectorPtMin (double ptmin)
select objects with pt >= ptmin
Definition at line 4511 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 4511 of file fjcore.cc
Referenced by RandomConeAna::EstimateRhos(), FastJetAlgo::get_selector(), main(), and PHAJMaker::PHAJMaker().
Selector SelectorPtRange (double ptmin, double ptmax)
select objects with ptmin <= pt <= ptmax
Definition at line 4517 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 4517 of file fjcore.cc
Referenced by main().
Selector SelectorRapMax (double rapmax)
select objects with rap <= rapmax
Definition at line 4605 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 4605 of file fjcore.cc
Selector SelectorRapMin (double rapmin)
select objects with rap >= rapmin
Definition at line 4602 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 4602 of file fjcore.cc
Selector SelectorRapPhiRange (double rapmin, double rapmax, double phimin, double phimax)
Definition at line 4722 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 4722 of file fjcore.cc
Selector SelectorRapRange (double rapmin, double rapmax)
select objects with rapmin <= rap <= rapmax
Definition at line 4608 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 4608 of file fjcore.cc
Selector SelectorRectangle (const double half_rap_width, const double half_phi_width)
Definition at line 4898 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 4898 of file fjcore.cc
Selector SelectorStrip (const double half_width)
Definition at line 4865 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 4865 of file fjcore.cc
void sort_indices (std::vector< int > & indices, const std::vector< double > & values)
Definition at line 4049 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 4049 of file fjcore.cc
References Acts::Experimental::detail::BlueprintHelper::sort().
Referenced by objects_sorted_by_values().
std::vector<PseudoJet> sorted_by_E (const std::vector< PseudoJet > & jets)
Definition at line 4064 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 4064 of file fjcore.cc
References i, and objects_sorted_by_values().
Referenced by JetDefinition::operator()().
std::vector<PseudoJet> sorted_by_pt (const std::vector< PseudoJet > & jets)
Definition at line 4054 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 4054 of file fjcore.cc
References i, and objects_sorted_by_values().
Referenced by FastJetAlgo::cluster_area_jets(), FastJetAlgo::cluster_jets(), RandomConeAna::EstimateRhos(), main(), JetDefinition::operator()(), JetBkgdSub::process_event(), PHAJMaker::process_event(), EMJetVal::process_event(), and TreeMaker::UseFastJet().
std::vector<PseudoJet> sorted_by_pz (const std::vector< PseudoJet > & jets)
Definition at line 4069 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 4069 of file fjcore.cc
References i, objects_sorted_by_values(), and PseudoJet::pz().
std::vector<PseudoJet> sorted_by_rapidity (const std::vector< PseudoJet > & jets)
Definition at line 4059 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 4059 of file fjcore.cc
References i, and objects_sorted_by_values().
template<class T > void swap (SharedPtr< T > & a, SharedPtr< T > & b) inline
Definition at line 398 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 398 of file fjcore.hh
References SharedPtr< T >::swap().
Referenced by ClusterSequence::_extract_tree_parents(), ClusterSequence::_faster_tiled_N2_cluster(), ClusterSequence::_minheap_faster_tiled_N2_cluster(), ClusterSequence::_simple_N2_cluster(), ClusterSequence::_tiled_N2_cluster(), TrackEvaluation::add_truth_information(), Acts::CandidatesForMiddleSp< external_space_point_t >::bubbledw(), Acts::CandidatesForMiddleSp< external_space_point_t >::bubbleup(), Acts::detail::CantorEdge< int64_t >::CantorEdge(), CleanVec(), ClosestPair2D::closest_pair(), Acts::Svg::GridConverter::convert(), SvtxVertex_v2::covar_index(), SvtxVertex_v1::covar_index(), GlobalVertexv1::covar_index(), PHG4Showerv1::covar_index(), BranchComparisonHarness::create(), Acts::DD4hepLayerBuilder::endcapLayers(), PHTruthClustering::G4ClusterSize(), SvtxTruthEval::G4ClusterSize(), genfit::Track::getTOF(), ClusterSequence::has_parents(), PHTruthClustering::LayerClusterG4Hits(), SvtxTruthEval::LayerClusterG4Hits(), NNH< BJ, I >::merge_jets(), ActsExamples::GroupBy< Iterator, KeyGetter >::GroupIterator::operator++(), testing::AssertionResult::operator=(), nanoflann::KDTreeSingleIndexAdaptor< Distance, DatasetAdaptor, DIM, IndexType >::planeSplit(), Acts::ConeSurface::polyhedronRepresentation(), Acts::CandidatesForMiddleSp< external_space_point_t >::pop(), PHG4InttHitReco::process_event(), quickSort(), LazyTiling9Alt::run(), LazyTiling9::run(), LazyTiling25::run(), Acts::DigitizationModule::segmentationSurfaces(), Acts::MeasurementSelector::select(), selectionSort(), QAG4SimulationJet::set_eta_range(), SoftLeptonTaggingTruth::set_eta_range(), HybridHadronization::set_meson_id(), PHPy8JetTrigger::SetEtaHighLow(), PHPy6JetTrigger::SetEtaHighLow(), testing::internal::ShuffleRange(), Acts::DigitizationModule::stepSurfaces(), HybridHadronization::stringprep(), genfit::KalmanFittedStateOnPlane::swap(), genfit::MeasuredStateOnPlane::swap(), genfit::MeasurementOnPlane::swap(), genfit::StateOnPlane::swap(), genfit::ReferenceStateOnPlane::swap(), genfit::GFRaveVertex::swap(), genfit::TrackPoint::swap(), mvtx::ChipPixelData::swap(), genfit::DetPlane::swap(), genfit::TrackCand::swap(), genfit::Track::swap(), HybridHadronization::parton_collection::swap(), testing::AssertionResult::swap(), boost::shared_ptr< TClonesArray >::swap(), PHHepMCGenEvent::swapEvent(), and ActsExamples::HoughTransformSeeder::yToXBins().
Variable Documentation
const JetAlgorithm aachen_algorithm = cambridge_algorithm
Definition at line 1017 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 1017 of file fjcore.hh
const JetAlgorithm cambridge_aachen_algorithm = cambridge_algorithm
Definition at line 1018 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 1018 of file fjcore.hh
const double eulergamma = 0.577215664901532860606512090082402431042
Definition at line 187 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 187 of file fjcore.hh
const double ln2 = 0.693147180559945309417232121458176568076
Definition at line 188 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 188 of file fjcore.hh
Referenced by TpcMonDraw::DrawTPCXYclusters(), and TpcMonDraw::DrawTPCXYclusters_unweighted().
FJCORE_BEGIN_NAMESPACE const double MaxRap = 1e5
Definition at line 517 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 517 of file fjcore.hh
Referenced by PseudoJet::_set_rap_phi(), and PseudoJet::pseudorapidity().
FJCORE_BEGIN_NAMESPACE const double pi = 3.141592653589793238462643383279502884197
Definition at line 182 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 182 of file fjcore.hh
Referenced by KFPMath::__attribute__(), __example_6.f__(), __example_7.f__(), __example_8.f__(), ClusterSequence::_best_strategy(), LazyTiling9Alt::_bj_dist(), LazyTiling9::_bj_dist(), LazyTiling25::_bj_dist(), ClusterSequence::_bj_dist(), ClusterSequence::_CP2DChan_limited_cluster(), LazyTiling9::_distance_to_tile(), LazyTiling25::_distance_to_tile(), ClusterSequence::_initialise_and_run_no_decant(), aiz(), epemGun::alpha_s(), alphas(), biz(), Cell::Cell(), conkin(), PHG4SpacalPrototype4Detector::Construct_AzimuthalSeg(), PHG4SpacalPrototypeDetector::Construct_AzimuthalSeg(), PHG4FullProjTiltedSpacalDetector::Construct_AzimuthalSeg(), PHG4FullProjSpacalDetector::Construct_AzimuthalSeg(), PHG4Sector::PHG4SectorConstructor::Construct_Sectors(), PHG4Sector::PHG4SectorConstructor::Construct_Sectors_Plane(), PseudoJet::delta_phi_to(), deltas(), deriv(), dfufi_pol(), doinstatescat(), dokinematics(), LaplaceSolution::Ephi(), LaplaceSolution::Er(), Glasma::EvolvePreequilibrium(), epemGun::Exec(), LaplaceSolution::Ez(), f2pyth(), LaplaceSolution::FindBetamn(), genevent(), PHG4Sector::Sector_Geometry::get_max_R(), PHG4CylinderGeom_Spacalv2::get_sec_azimuthal_width(), getinspliti(), getmass(), getnatmdmin(), getneff(), getneffmax(), getqvec(), getscatterer(), gett(), gettemp(), PIDplots::inputpars(), intbtk2(), AnnularFieldSim::interpolatedFieldIntegral(), inttk2(), Hydro::ISformal(), SW_Circle::known_area(), SW_Doughnut::known_area(), PseudoJet::kt_distance(), LaplaceSolution::LaplaceSolution(), main(), makeinsplit(), makesplitting(), phase(), PseudoJet::phi_std(), phidst_pol(), PseudoJet::plain_distance(), podinl(), poissonian(), PHG4TpcPadBaselineShift::process_event(), jetrtrack::process_event(), analysis::process_event(), PseudoJet::pseudorapidity(), pycjdc(), pygfxx(), pyglui(), pygram(), pygraw(), pynjdc(), pypole(), pyreco(), pyrghm(), pyrnmq(), pysfdc(), pysubh(), pytbhg(), pytbhq(), pyth_xsec(), pyuedc(), pywdkk(), pyxued(), qqt(), JetDefinition::DefaultRecombiner::recombine(), ReconstructTracks(), EpFinder::Results(), LaplaceSolution::Rmn1(), LaplaceSolution::Rmn2(), LaplaceSolution::Rnk(), LaplaceSolution::RPrime(), scatprimfunc(), PHG4Sector::Sector_Geometry::set_max_polar_angle(), PHG4Sector::Sector_Geometry::set_min_polar_angle(), PHG4Sector::Sector_Geometry::set_normal_polar_angle(), AnnularFieldSim::sum_nonlocal_field_at(), tails(), track_kinematics(), and vacpol().
const double pisq = 9.869604401089358618834490999876151135314
Definition at line 184 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 184 of file fjcore.hh
const double pseudojet_invalid_phi = -100.0
Definition at line 518 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 518 of file fjcore.hh
Referenced by PseudoJet::_finish_init().
const double pseudojet_invalid_rap = -1e200
Definition at line 519 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 519 of file fjcore.hh
Referenced by PseudoJet::_finish_init().
const double twopi = 6.283185307179586476925286766559005768394
Definition at line 183 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 183 of file fjcore.hh
Referenced by LazyTiling9Alt::_bj_dist(), LazyTiling9::_bj_dist(), LazyTiling25::_bj_dist(), ClusterSequence::_bj_dist(), ClusterSequence::_CP2DChan_cluster(), ClusterSequence::_delaunay_cluster(), LazyTiling9::_distance_to_tile(), LazyTiling25::_distance_to_tile(), ClusterSequence::_initialise_and_run_no_decant(), LazyTiling9Alt::_initialise_tiles(), LazyTiling9::_initialise_tiles(), LazyTiling25::_initialise_tiles(), ClusterSequence::_initialise_tiles(), PseudoJet::_set_rap_phi(), LazyTiling9Alt::_tile_index(), LazyTiling9::_tile_index(), LazyTiling25::_tile_index(), PHG4TpcEndCapDetector::AddLayer(), PHG4SpacalPrototypeDetector::Construct_AzimuthalSeg(), PHG4FullProjSpacalDetector::Construct_AzimuthalSeg(), PHG4SpacalDetector::Construct_AzimuthalSeg(), PHG4SpacalPrototype4Detector::Construct_Fiber(), PHG4SpacalPrototypeDetector::Construct_Fiber(), PHG4SpacalDetector::Construct_Fiber(), PHG4TpcEndCapDetector::ConstructElectronics(), PHG4BeamlineMagnetDetector::ConstructMe(), BeamLineMagnetDetector::ConstructMe(), PHG4ZDCDetector::ConstructMe(), PHG4HcalDetector::ConstructMe(), PHG4SpacalPrototypeDetector::ConstructMe(), PHG4SpacalPrototype4Detector::ConstructMe(), PHG4SpacalDetector::ConstructMe(), PHG4TpcEndCapDetector::ConstructWagonWheel(), PseudoJet::delta_phi_to(), PHG4CylinderGeom_Spacalv1::get_azimuthal_distance(), PHG4CylinderGeom_Spacalv1::get_azimuthal_n_sec(), PHG4CylinderGeom_Spacalv2::get_sec_azimuthal_width(), PHG4OuterHcalField::GetFieldValue(), PHG4CylinderGeom_Spacalv1::init_default_sector_map(), SW_RapRange::known_area(), SW_AbsRapMax::known_area(), SW_AbsRapRange::known_area(), SW_Strip::known_area(), PseudoJet::kt_distance(), PHG4CylinderGeom_Spacalv3::load_demo_sector_tower_map4(), Private::make_mirror(), SW_PhiRange::pass(), PseudoJet::phi_std(), PseudoJet::plain_distance(), PtYPhiM(), pyjurf(), radgen_event(), JetDefinition::DefaultRecombiner::recombine(), PseudoJet::reset_momentum_PtYPhiM(), EtaPhi::sanitize(), PseudoJet::set_cached_rap_phi(), SW_PhiRange::SW_PhiRange(), and SW_RapPhiRange::SW_RapPhiRange().
const double zeta2 = 1.644934066848226436472415166646025189219
Definition at line 185 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 185 of file fjcore.hh
const double zeta3 = 1.202056903159594285399738161511449990765
Definition at line 186 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 186 of file fjcore.hh
Referenced by calcta(), calcxsection(), getltimemax(), getmdmin(), getnatmdmin(), getneff(), getneffmax(), getscatterer(), gettemp(), gettempmax(), medderiv(), medinit(), mednextevt(), npart(), nthick(), and pyuedc().