Analysis Software: OnlMon/blob/master/onlmonserver/HistoServer.cc File Reference
HistoServer.cc File Reference
#include "HistoServer.h"
#include "OnlMonServer.h"
#include <TClass.h>
#include <TH1.h>
#include <TMessage.h>
#include <TServerSocket.h>
#include <TSocket.h>
#include <TROOT.h>
#include <sstream>
#include <string>
#include <pthread.h>
Macros
#define SERVER
Functions
static void * server (void *)
int setup_server ()
void handletest (void *arg)
void handleconnection (void *arg)
void send_test_message ()
Variables
int ServerThread = 0
pthread_mutex_t mutex
static int MONIPORT =9081
static int NUMMONIPORT =5
Macro Definition Documentation
#define SERVER
Definition at line 19 of file HistoServer.cc.
View newest version in sPHENIX GitHub at line 19 of file HistoServer.cc
Function Documentation
void handleconnection (void * arg)
Definition at line 157 of file HistoServer.cc.
View newest version in sPHENIX GitHub at line 157 of file HistoServer.cc
References Fun4AllServer::getHisto(), Fun4AllServer::getHistoName(), i, OnlMonServer::instance(), TauVsDIS_MachineLearning_Differentiation::msg, printf(), return(), and Fun4AllBase::Verbosity().
Referenced by server().
void handletest (void * arg)
Definition at line 150 of file HistoServer.cc.
View newest version in sPHENIX GitHub at line 150 of file HistoServer.cc
References return().
void send_test_message ()
Definition at line 338 of file HistoServer.cc.
View newest version in sPHENIX GitHub at line 338 of file HistoServer.cc
References MONIPORT.
Referenced by OnlMonServer::testmsg().
static void * server (void * arg) static
Definition at line 68 of file HistoServer.cc.
View newest version in sPHENIX GitHub at line 68 of file HistoServer.cc
References h1, handleconnection(), OnlMonServer::instance(), MONIPORT, TauVsDIS_MachineLearning_Differentiation::msg, mutex, NUMMONIPORT, printf(), Fun4AllServer::registerHisto(), and Fun4AllBase::Verbosity().
Referenced by rcdaqEventiterator::read_next_buffer(), rcdaqEventiterator::setup(), and setup_server().
int setup_server ()
Definition at line 37 of file HistoServer.cc.
View newest version in sPHENIX GitHub at line 37 of file HistoServer.cc
References OnlMonServer::GetMutex(), OnlMonServer::instance(), mutex, server(), ServerThread, OnlMonServer::SetThreadId(), and ThreadId.
Referenced by OnlMonServer::StartServer().
Variable Documentation
int MONIPORT =9081 static
Definition at line 34 of file HistoServer.cc.
View newest version in sPHENIX GitHub at line 34 of file HistoServer.cc
Referenced by send_test_message(), and server().
pthread_mutex_t mutex
Definition at line 32 of file HistoServer.cc.
View newest version in sPHENIX GitHub at line 32 of file HistoServer.cc
Referenced by SeamStress::Seamstress::rest(), SeamStress::Seamstress::Seamstress(), server(), setup_server(), SeamStress::Seamstress::sew(), SeamStress::Seamstress::start(), SeamStress::Seamstress::stop(), and SeamStress::Seamstress::~Seamstress().
int NUMMONIPORT =5 static
Definition at line 35 of file HistoServer.cc.
View newest version in sPHENIX GitHub at line 35 of file HistoServer.cc
Referenced by server().
int ServerThread = 0
Definition at line 24 of file HistoServer.cc.
View newest version in sPHENIX GitHub at line 24 of file HistoServer.cc
Referenced by setup_server().