Analysis Software: EicEventHeader Class Reference
EicEventHeader Class Reference
#include <coresoftware/blob/master/simulation/g4simulation/g4main/EicEventHeader.h>
Public Types
enum PROPERTY {
prop_eventgen = 1, prop_milou_weight = 2, prop_milou_truex = 3, prop_milou_trueq2 = 4,
prop_demp_weight = 5, prop_MAX_NUMBER = UCHAR_MAX
}
enum PROPERTY_TYPE { type_int = 1, type_uint = 2, type_float = 3, type_unknown = -1 }
enum EvtGen { Milou = 1, DEMP = 2 }
Public Member Functions
EicEventHeader ()
~EicEventHeader () override
void identify (std::ostream &os=std::cout) const override
void CopyFrom (const PHObject *phobj) override
void Reset () override
Clear Event.
virtual void set_eventgenerator_type (const int)
virtual int get_eventgenerator_type () const
virtual void set_milou_weight (const float)
virtual float get_milou_weight () const
virtual void set_milou_trueX (const float)
virtual float get_milou_trueX () const
virtual void set_milou_trueQ2 (const float)
virtual float get_milou_trueQ2 () const
virtual void set_demp_weight (const float)
virtual float get_demp_weight () const
virtual bool has_property (const PROPERTY) const
virtual float get_property_float (const PROPERTY) const
virtual int get_property_int (const PROPERTY) const
virtual unsigned int get_property_uint (const PROPERTY) const
virtual void set_property (const PROPERTY, const float)
virtual void set_property (const PROPERTY, const int)
virtual void set_property (const PROPERTY, const unsigned int)
Public Member Functions inherited from PHObject
PHObject ()
ctor
~PHObject () override
dtor
virtual PHObject * CloneMe () const
Virtual copy constructor.
virtual PHObject * clone () const final
PHObject * Clone (const char *newname="") const final
void Copy (TObject &object) const final
virtual int isValid () const
isValid returns non zero if object contains vailid data
virtual int Integrate () const
virtual int Integrate (PHObject *)
Static Public Member Functions
static std::pair< const
std::string, PROPERTY_TYPE > get_property_info (PROPERTY prop_id)
static bool check_property (const PROPERTY prop_id, const PROPERTY_TYPE prop_type)
static std::string get_property_type (const PROPERTY_TYPE prop_type)
Protected Member Functions
virtual unsigned int get_property_nocheck (const PROPERTY) const
virtual void set_property_nocheck (const PROPERTY, const unsigned int)
Protected Attributes
std::map< std::string, double > evInfo
Detailed Description
Definition at line 15 of file EicEventHeader.h.
View newest version in sPHENIX GitHub at line 15 of file EicEventHeader.h
Member Enumeration Documentation
enum EicEventHeader::EvtGen
Enumerator:
Milou
DEMP
Definition at line 70 of file EicEventHeader.h.
View newest version in sPHENIX GitHub at line 70 of file EicEventHeader.h
enum EicEventHeader::PROPERTY
Procedure to add a new PROPERTY tag: 1.add new tag below with unique value, 2.add a short name to EicEventHeader::get_property_info
Enumerator:
prop_eventgen
prop_milou_weight
prop_milou_truex
prop_milou_trueq2
prop_demp_weight
prop_MAX_NUMBER
max limit in order to fit into 8 bit unsigned number
Definition at line 49 of file EicEventHeader.h.
View newest version in sPHENIX GitHub at line 49 of file EicEventHeader.h
enum EicEventHeader::PROPERTY_TYPE
Enumerator:
type_int
type_uint
type_float
type_unknown
Definition at line 62 of file EicEventHeader.h.
View newest version in sPHENIX GitHub at line 62 of file EicEventHeader.h
Constructor & Destructor Documentation
EicEventHeader::EicEventHeader () inline
Definition at line 18 of file EicEventHeader.h.
View newest version in sPHENIX GitHub at line 18 of file EicEventHeader.h
EicEventHeader::~EicEventHeader () override
Definition at line 27 of file EicEventHeader.cc.
View newest version in sPHENIX GitHub at line 27 of file EicEventHeader.cc
Member Function Documentation
bool EicEventHeader::check_property (const PROPERTY prop_id, const PROPERTY_TYPE prop_type) static
Definition at line 61 of file EicEventHeader.cc.
View newest version in sPHENIX GitHub at line 61 of file EicEventHeader.cc
void EicEventHeader::CopyFrom (const PHObject * phobj) override virtual
Reimplemented from PHObject.
Definition at line 10 of file EicEventHeader.cc.
View newest version in sPHENIX GitHub at line 10 of file EicEventHeader.cc
References assert, get_property_nocheck(), and has_property().
virtual float EicEventHeader::get_demp_weight () const inline virtual
Reimplemented in EicEventHeaderv1.
Definition at line 44 of file EicEventHeader.h.
View newest version in sPHENIX GitHub at line 44 of file EicEventHeader.h
virtual int EicEventHeader::get_eventgenerator_type () const inline virtual
Reimplemented in EicEventHeaderv1.
Definition at line 27 of file EicEventHeader.h.
View newest version in sPHENIX GitHub at line 27 of file EicEventHeader.h
virtual float EicEventHeader::get_milou_trueQ2 () const inline virtual
Reimplemented in EicEventHeaderv1.
Definition at line 36 of file EicEventHeader.h.
View newest version in sPHENIX GitHub at line 36 of file EicEventHeader.h
virtual float EicEventHeader::get_milou_trueX () const inline virtual
Reimplemented in EicEventHeaderv1.
Definition at line 34 of file EicEventHeader.h.
View newest version in sPHENIX GitHub at line 34 of file EicEventHeader.h
virtual float EicEventHeader::get_milou_weight () const inline virtual
Reimplemented in EicEventHeaderv1.
Definition at line 32 of file EicEventHeader.h.
View newest version in sPHENIX GitHub at line 32 of file EicEventHeader.h
virtual float EicEventHeader::get_property_float (const PROPERTY) const inline virtual
Reimplemented in EicEventHeaderv1.
Definition at line 77 of file EicEventHeader.h.
View newest version in sPHENIX GitHub at line 77 of file EicEventHeader.h
std::pair< const std::string, EicEventHeader::PROPERTY_TYPE > EicEventHeader::get_property_info (PROPERTY prop_id) static
Definition at line 39 of file EicEventHeader.cc.
View newest version in sPHENIX GitHub at line 39 of file EicEventHeader.cc
References type_float, and type_int.
virtual int EicEventHeader::get_property_int (const PROPERTY) const inline virtual
Reimplemented in EicEventHeaderv1.
Definition at line 78 of file EicEventHeader.h.
View newest version in sPHENIX GitHub at line 78 of file EicEventHeader.h
virtual unsigned int EicEventHeader::get_property_nocheck (const PROPERTY) const inline protected virtual
Reimplemented in EicEventHeaderv1.
Definition at line 88 of file EicEventHeader.h.
View newest version in sPHENIX GitHub at line 88 of file EicEventHeader.h
Referenced by CopyFrom().
string EicEventHeader::get_property_type (const PROPERTY_TYPE prop_type) static
Definition at line 72 of file EicEventHeader.cc.
View newest version in sPHENIX GitHub at line 72 of file EicEventHeader.cc
virtual unsigned int EicEventHeader::get_property_uint (const PROPERTY) const inline virtual
Reimplemented in EicEventHeaderv1.
Definition at line 79 of file EicEventHeader.h.
View newest version in sPHENIX GitHub at line 79 of file EicEventHeader.h
virtual bool EicEventHeader::has_property (const PROPERTY) const inline virtual
Reimplemented in EicEventHeaderv1.
Definition at line 76 of file EicEventHeader.h.
View newest version in sPHENIX GitHub at line 76 of file EicEventHeader.h
Referenced by CopyFrom().
void EicEventHeader::identify (std::ostream & os = std::cout) const override virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from PHObject.
Definition at line 87 of file EicEventHeader.cc.
View newest version in sPHENIX GitHub at line 87 of file EicEventHeader.cc
void EicEventHeader::Reset () override virtual
Clear Event.
Reimplemented from PHObject.
Reimplemented in EicEventHeaderv1.
Definition at line 32 of file EicEventHeader.cc.
View newest version in sPHENIX GitHub at line 32 of file EicEventHeader.cc
virtual void EicEventHeader::set_demp_weight (const float) inline virtual
Reimplemented in EicEventHeaderv1.
Definition at line 43 of file EicEventHeader.h.
View newest version in sPHENIX GitHub at line 43 of file EicEventHeader.h
Referenced by ReadEICFiles::process_event().
virtual void EicEventHeader::set_eventgenerator_type (const int) inline virtual
Reimplemented in EicEventHeaderv1.
Definition at line 26 of file EicEventHeader.h.
View newest version in sPHENIX GitHub at line 26 of file EicEventHeader.h
Referenced by ReadEICFiles::process_event().
virtual void EicEventHeader::set_milou_trueQ2 (const float) inline virtual
Reimplemented in EicEventHeaderv1.
Definition at line 35 of file EicEventHeader.h.
View newest version in sPHENIX GitHub at line 35 of file EicEventHeader.h
Referenced by ReadEICFiles::process_event().
virtual void EicEventHeader::set_milou_trueX (const float) inline virtual
Reimplemented in EicEventHeaderv1.
Definition at line 33 of file EicEventHeader.h.
View newest version in sPHENIX GitHub at line 33 of file EicEventHeader.h
Referenced by ReadEICFiles::process_event().
virtual void EicEventHeader::set_milou_weight (const float) inline virtual
Reimplemented in EicEventHeaderv1.
Definition at line 31 of file EicEventHeader.h.
View newest version in sPHENIX GitHub at line 31 of file EicEventHeader.h
Referenced by ReadEICFiles::process_event().
virtual void EicEventHeader::set_property (const PROPERTY , const float) inline virtual
Reimplemented in EicEventHeaderv1.
Definition at line 80 of file EicEventHeader.h.
View newest version in sPHENIX GitHub at line 80 of file EicEventHeader.h
virtual void EicEventHeader::set_property (const PROPERTY , const int) inline virtual
Reimplemented in EicEventHeaderv1.
Definition at line 81 of file EicEventHeader.h.
View newest version in sPHENIX GitHub at line 81 of file EicEventHeader.h
virtual void EicEventHeader::set_property (const PROPERTY , const unsigned int) inline virtual
Reimplemented in EicEventHeaderv1.
Definition at line 82 of file EicEventHeader.h.
View newest version in sPHENIX GitHub at line 82 of file EicEventHeader.h
virtual void EicEventHeader::set_property_nocheck (const PROPERTY , const unsigned int) inline protected virtual
Reimplemented in EicEventHeaderv1.
Definition at line 89 of file EicEventHeader.h.
View newest version in sPHENIX GitHub at line 89 of file EicEventHeader.h
Member Data Documentation
std::map<std::string, double> EicEventHeader::evInfo protected
Definition at line 91 of file EicEventHeader.h.
View newest version in sPHENIX GitHub at line 91 of file EicEventHeader.h
The documentation for this class was generated from the following files:
coresoftware/blob/master/simulation/g4simulation/g4main/EicEventHeader.h
coresoftware/blob/master/simulation/g4simulation/g4main/EicEventHeader.cc