Analysis Software: PHG4EPDModuleReco Class Reference
PHG4EPDModuleReco Class Reference
#include <coresoftware/blob/master/simulation/g4simulation/g4epd/PHG4EPDModuleReco.h>
Public Member Functions
PHG4EPDModuleReco (const std::string &name="EpdModuleReco")
~PHG4EPDModuleReco () override
int InitRun (PHCompositeNode *topNode) override
module initialization
int process_event (PHCompositeNode *topNode) override
event processing
int ResetEvent (PHCompositeNode *) override
Reset after every event.
void SetDefaultParameters () override
void Detector (const std::string &detector)
std::string get_epd_sim_tower_node_prefix () const
void set_epd_sim_tower_node_prefix (const std::string &epdsimTowerNodePrefix)
std::string get_epd_calib_tower_node_prefix () const
void set_epd_calib_tower_node_prefix (const std::string &epdcalibTowerNodePrefix)
void set_timing_window (const double tmi, const double tma)
Public Member Functions inherited from SubsysReco
~SubsysReco () override
virtual int End (PHCompositeNode *)
Called at the end of all processing.
virtual int EndRun (const int)
Called at the end of each run.
virtual int Init (PHCompositeNode *)
virtual int Reset (PHCompositeNode *)
Reset.
void Print (const std::string &="ALL") const override
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Public Member Functions inherited from PHParameterInterface
PHParameterInterface (const std::string &name)
PHParameterInterface (const PHParameterInterface &)=delete
PHParameterInterface & operator= (PHParameterInterface const &)=delete
virtual ~PHParameterInterface ()
void set_paramname (const std::string &name)
void set_double_param (const std::string &name, const double dval)
double get_double_param (const std::string &name) const
void set_int_param (const std::string &name, const int ival)
int get_int_param (const std::string &name) const
void set_string_param (const std::string &name, const std::string &sval)
std::string get_string_param (const std::string &name) const
void UpdateParametersWithMacro ()
void SaveToNodeTree (PHCompositeNode *runNode, const std::string &nodename)
void PutOnParNode (PHCompositeNode *parNode, const std::string &nodename)
void Print () const
Private Member Functions
int Getrmap (int rindex)
int Getphimap (int phiindex)
float GetTilePhi (int thisphi)
float GetTilePhi0 (int thisphi0)
float GetTileR (int thisr)
float GetTileZ (int thisz)
void CreateNodes (PHCompositeNode *topNode)
Private Attributes
std::string m_Detector
std::string m_Hitnodename
std::string m_EPDSimTowerNodePrefix = "SIM"
std::string m_EPDCalibTowerNodePrefix = "CALIB"
std::string m_TowerInfoNodeName
std::string m_TowerInfoNodeName_calib
std::array< std::array
< std::array< double, 31 >, 12 >, 2 > m_EpdTile_e = {}
std::array< std::array
< std::array< double, 31 >, 12 >, 2 > m_EpdTile_Calib_e = {}
double m_EpdMpv = NAN
double tmin = NAN
double tmax = NAN
double m_DeltaT = NAN
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = std::numeric_limits<int>::max() - 10
}
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Protected Member Functions inherited from PHParameterInterface
void set_default_double_param (const std::string &name, const double dval)
void set_default_int_param (const std::string &name, const int ival)
void set_default_string_param (const std::string &name, const std::string &sval)
void InitializeParameters ()
Detailed Description
Definition at line 16 of file PHG4EPDModuleReco.h.
View newest version in sPHENIX GitHub at line 16 of file PHG4EPDModuleReco.h
Constructor & Destructor Documentation
PHG4EPDModuleReco::PHG4EPDModuleReco (const std::string & name = "EpdModuleReco")
Definition at line 35 of file PHG4EPDModuleReco.cc.
View newest version in sPHENIX GitHub at line 35 of file PHG4EPDModuleReco.cc
References PHParameterInterface::InitializeParameters().
PHG4EPDModuleReco::~PHG4EPDModuleReco () inline override
Definition at line 21 of file PHG4EPDModuleReco.h.
View newest version in sPHENIX GitHub at line 21 of file PHG4EPDModuleReco.h
Member Function Documentation
void PHG4EPDModuleReco::CreateNodes (PHCompositeNode * topNode) private
Definition at line 225 of file PHG4EPDModuleReco.cc.
View newest version in sPHENIX GitHub at line 225 of file PHG4EPDModuleReco.cc
References PHCompositeNode::addNode(), PHNodeIterator::findFirst(), m_Detector, m_EPDCalibTowerNodePrefix, m_EPDSimTowerNodePrefix, m_TowerInfoNodeName, m_TowerInfoNodeName_calib, PHWHERE, and CaloTowerDefs::SEPD.
Referenced by InitRun().
void PHG4EPDModuleReco::Detector (const std::string & detector)
Definition at line 280 of file PHG4EPDModuleReco.cc.
View newest version in sPHENIX GitHub at line 280 of file PHG4EPDModuleReco.cc
References m_Detector, and m_Hitnodename.
Referenced by EPD_Tiles().
std::string PHG4EPDModuleReco::get_epd_calib_tower_node_prefix () const inline
Definition at line 49 of file PHG4EPDModuleReco.h.
View newest version in sPHENIX GitHub at line 49 of file PHG4EPDModuleReco.h
References m_EPDCalibTowerNodePrefix.
std::string PHG4EPDModuleReco::get_epd_sim_tower_node_prefix () const inline
Definition at line 37 of file PHG4EPDModuleReco.h.
View newest version in sPHENIX GitHub at line 37 of file PHG4EPDModuleReco.h
References m_EPDSimTowerNodePrefix.
int PHG4EPDModuleReco::Getphimap (int phiindex) private
Definition at line 194 of file PHG4EPDModuleReco.cc.
View newest version in sPHENIX GitHub at line 194 of file PHG4EPDModuleReco.cc
Referenced by process_event().
int PHG4EPDModuleReco::Getrmap (int rindex) private
Definition at line 187 of file PHG4EPDModuleReco.cc.
View newest version in sPHENIX GitHub at line 187 of file PHG4EPDModuleReco.cc
Referenced by process_event().
float PHG4EPDModuleReco::GetTilePhi (int thisphi) private
Definition at line 201 of file PHG4EPDModuleReco.cc.
View newest version in sPHENIX GitHub at line 201 of file PHG4EPDModuleReco.cc
Referenced by InitRun().
float PHG4EPDModuleReco::GetTilePhi0 (int thisphi0) private
Definition at line 207 of file PHG4EPDModuleReco.cc.
View newest version in sPHENIX GitHub at line 207 of file PHG4EPDModuleReco.cc
Referenced by InitRun().
float PHG4EPDModuleReco::GetTileR (int thisr) private
Definition at line 213 of file PHG4EPDModuleReco.cc.
View newest version in sPHENIX GitHub at line 213 of file PHG4EPDModuleReco.cc
Referenced by InitRun().
float PHG4EPDModuleReco::GetTileZ (int thisz) private
Definition at line 219 of file PHG4EPDModuleReco.cc.
View newest version in sPHENIX GitHub at line 219 of file PHG4EPDModuleReco.cc
Referenced by InitRun().
int PHG4EPDModuleReco::InitRun (PHCompositeNode * topNode) override virtual
module initialization
Reimplemented from SubsysReco.
Definition at line 42 of file PHG4EPDModuleReco.cc.
View newest version in sPHENIX GitHub at line 42 of file PHG4EPDModuleReco.cc
References PHCompositeNode::addNode(), CreateNodes(), TowerInfoDefs::encode_epd(), Fun4AllReturnCodes::EVENT_OK, PHNodeIterator::findFirst(), PHParameterInterface::get_double_param(), TowerInfoDefs::get_epd_arm(), TowerInfoDefs::get_epd_phibin(), TowerInfoDefs::get_epd_rbin(), GetTilePhi(), GetTilePhi0(), GetTileR(), GetTileZ(), m_DeltaT, m_Detector, m_EpdMpv, PHWHERE, EpdGeom::set_phi(), EpdGeom::set_phi0(), EpdGeom::set_r(), EpdGeom::set_z(), tmax, tmin, and PHParameterInterface::UpdateParametersWithMacro().
int PHG4EPDModuleReco::process_event (PHCompositeNode * topNode) override virtual
event processing
Reimplemented from SubsysReco.
Definition at line 97 of file PHG4EPDModuleReco.cc.
View newest version in sPHENIX GitHub at line 97 of file PHG4EPDModuleReco.cc
References TowerInfoContainer::decode_key(), TowerInfoDefs::encode_epd(), Fun4AllReturnCodes::EVENT_OK, EPDDefs::get_arm(), EPDDefs::get_sector(), EPDDefs::get_tileid(), TowerInfoContainer::get_tower_at_channel(), PHG4HitContainer::getHits(), Getphimap(), Getrmap(), PHG4HitDefs::hit_idbits, i, j, k, m_DeltaT, m_EpdMpv, m_EpdTile_Calib_e, m_EpdTile_e, m_Hitnodename, m_TowerInfoNodeName, m_TowerInfoNodeName_calib, PHWHERE, physmon_track_finding_ttbar::r, TowerInfo::set_energy(), tmax, and tmin.
int PHG4EPDModuleReco::ResetEvent (PHCompositeNode *) override virtual
Reset after every event.
Reimplemented from SubsysReco.
Definition at line 264 of file PHG4EPDModuleReco.cc.
View newest version in sPHENIX GitHub at line 264 of file PHG4EPDModuleReco.cc
References Fun4AllReturnCodes::EVENT_OK, m_EpdTile_Calib_e, and m_EpdTile_e.
void PHG4EPDModuleReco::set_epd_calib_tower_node_prefix (const std::string & epdcalibTowerNodePrefix) inline
Definition at line 55 of file PHG4EPDModuleReco.h.
View newest version in sPHENIX GitHub at line 55 of file PHG4EPDModuleReco.h
References m_EPDCalibTowerNodePrefix.
void PHG4EPDModuleReco::set_epd_sim_tower_node_prefix (const std::string & epdsimTowerNodePrefix) inline
Definition at line 43 of file PHG4EPDModuleReco.h.
View newest version in sPHENIX GitHub at line 43 of file PHG4EPDModuleReco.h
References m_EPDSimTowerNodePrefix.
void PHG4EPDModuleReco::set_timing_window (const double tmi, const double tma)
Definition at line 181 of file PHG4EPDModuleReco.cc.
View newest version in sPHENIX GitHub at line 181 of file PHG4EPDModuleReco.cc
References PHParameterInterface::set_double_param().
void PHG4EPDModuleReco::SetDefaultParameters () override virtual
Implements PHParameterInterface.
Definition at line 172 of file PHG4EPDModuleReco.cc.
View newest version in sPHENIX GitHub at line 172 of file PHG4EPDModuleReco.cc
References PHParameterInterface::set_default_double_param().
Member Data Documentation
double PHG4EPDModuleReco::m_DeltaT = NAN private
Definition at line 85 of file PHG4EPDModuleReco.h.
View newest version in sPHENIX GitHub at line 85 of file PHG4EPDModuleReco.h
Referenced by InitRun(), and process_event().
std::string PHG4EPDModuleReco::m_Detector private
Definition at line 71 of file PHG4EPDModuleReco.h.
View newest version in sPHENIX GitHub at line 71 of file PHG4EPDModuleReco.h
Referenced by CreateNodes(), Detector(), and InitRun().
std::string PHG4EPDModuleReco::m_EPDCalibTowerNodePrefix = "CALIB" private
Definition at line 74 of file PHG4EPDModuleReco.h.
View newest version in sPHENIX GitHub at line 74 of file PHG4EPDModuleReco.h
Referenced by CreateNodes(), get_epd_calib_tower_node_prefix(), and set_epd_calib_tower_node_prefix().
double PHG4EPDModuleReco::m_EpdMpv = NAN private
Definition at line 81 of file PHG4EPDModuleReco.h.
View newest version in sPHENIX GitHub at line 81 of file PHG4EPDModuleReco.h
Referenced by InitRun(), and process_event().
std::string PHG4EPDModuleReco::m_EPDSimTowerNodePrefix = "SIM" private
Definition at line 73 of file PHG4EPDModuleReco.h.
View newest version in sPHENIX GitHub at line 73 of file PHG4EPDModuleReco.h
Referenced by CreateNodes(), get_epd_sim_tower_node_prefix(), and set_epd_sim_tower_node_prefix().
std::array<std::array<std::array<double, 31>, 12>, 2> PHG4EPDModuleReco::m_EpdTile_Calib_e = {} private
Definition at line 79 of file PHG4EPDModuleReco.h.
View newest version in sPHENIX GitHub at line 79 of file PHG4EPDModuleReco.h
Referenced by process_event(), and ResetEvent().
std::array<std::array<std::array<double, 31>, 12>, 2> PHG4EPDModuleReco::m_EpdTile_e = {} private
Definition at line 78 of file PHG4EPDModuleReco.h.
View newest version in sPHENIX GitHub at line 78 of file PHG4EPDModuleReco.h
Referenced by process_event(), and ResetEvent().
std::string PHG4EPDModuleReco::m_Hitnodename private
Definition at line 72 of file PHG4EPDModuleReco.h.
View newest version in sPHENIX GitHub at line 72 of file PHG4EPDModuleReco.h
Referenced by Detector(), and process_event().
std::string PHG4EPDModuleReco::m_TowerInfoNodeName private
Definition at line 76 of file PHG4EPDModuleReco.h.
View newest version in sPHENIX GitHub at line 76 of file PHG4EPDModuleReco.h
Referenced by CreateNodes(), and process_event().
std::string PHG4EPDModuleReco::m_TowerInfoNodeName_calib private
Definition at line 77 of file PHG4EPDModuleReco.h.
View newest version in sPHENIX GitHub at line 77 of file PHG4EPDModuleReco.h
Referenced by CreateNodes(), and process_event().
double PHG4EPDModuleReco::tmax = NAN private
Definition at line 84 of file PHG4EPDModuleReco.h.
View newest version in sPHENIX GitHub at line 84 of file PHG4EPDModuleReco.h
Referenced by InitRun(), and process_event().
double PHG4EPDModuleReco::tmin = NAN private
Definition at line 83 of file PHG4EPDModuleReco.h.
View newest version in sPHENIX GitHub at line 83 of file PHG4EPDModuleReco.h
Referenced by InitRun(), and process_event().
The documentation for this class was generated from the following files:
coresoftware/blob/master/simulation/g4simulation/g4epd/PHG4EPDModuleReco.h
coresoftware/blob/master/simulation/g4simulation/g4epd/PHG4EPDModuleReco.cc