Analysis Software: Acts::Svg::PortalConverter Namespace Reference
Acts::Svg::PortalConverter Namespace Reference
Classes
struct Options
Nested Options struct for conversion options.
Functions
ProtoPortal convert (const GeometryContext &gctx, const Experimental::Portal &portal, const PortalConverter::Options &portalOptions)
Function Documentation
Acts::Svg::ProtoPortal Acts::Svg::PortalConverter::convert (const GeometryContext & gctx, const Experimental::Portal & portal, const PortalConverter::Options & portalOptions)
Convert into a ProtoPortal
Parameters
gtcx is the geometry context of the conversion call
portal is the detector portal to convert
portalOptions is the conversion options struct
Returns
a proto portal object
Definition at line 95 of file PortalSvgConverter.cpp.
View newest version in sPHENIX GitHub at line 95 of file PortalSvgConverter.cpp
References Acts::Svg::DetectorConverter::convert(), Acts::Experimental::Portal::detectorVolumeUpdators(), sign(), writeMapConfig::surface, Acts::Experimental::Portal::surface(), Acts::Svg::PortalConverter::Options::surfaceOptions, Acts::Surface::transform(), and physmon_ckf_tracking::u.
Referenced by BOOST_AUTO_TEST_CASE().