Analysis Software: Acts::Experimental::IndexedRootVolumeFinderBuilder Exception Reference
Acts::Experimental::IndexedRootVolumeFinderBuilder Exception Reference final
This is the interface for builders that create root volume finder delegates.
#include <acts/blob/sPHENIX/Core/include/Acts/Detector/IndexedRootVolumeFinderBuilder.hpp>
Public Member Functions
IndexedRootVolumeFinderBuilder (std::vector< Acts::BinningValue > binning)
Constructor with binning casts.
DetectorVolumeUpdator construct (const GeometryContext &gctx, const std::vector< std::shared_ptr< DetectorVolume >> &rootVolumes) const final
Public Member Functions inherited from Acts::Experimental::IRootVolumeFinderBuilder
virtual ~IRootVolumeFinderBuilder ()=default
Private Attributes
std::vector< Acts::BinningValue > m_casts
Detailed Description
This is the interface for builders that create root volume finder delegates.
Definition at line 27 of file IndexedRootVolumeFinderBuilder.hpp.
View newest version in sPHENIX GitHub at line 27 of file IndexedRootVolumeFinderBuilder.hpp
Constructor & Destructor Documentation
Acts::Experimental::IndexedRootVolumeFinderBuilder::IndexedRootVolumeFinderBuilder (std::vector< Acts::BinningValue > binning)
Constructor with binning casts.
Parameters
binning the cast values for the grid binning
Definition at line 51 of file IndexedRootVolumeFinderBuilder.cpp.
View newest version in sPHENIX GitHub at line 51 of file IndexedRootVolumeFinderBuilder.cpp
References Acts::binR, Acts::binZ, and m_casts.
Member Function Documentation
Acts::Experimental::DetectorVolumeUpdator Acts::Experimental::IndexedRootVolumeFinderBuilder::construct (const GeometryContext & gctx, const std::vector< std::shared_ptr< DetectorVolume >> & rootVolumes) const final virtual
The virtual interface definition for root volume finder builders
Parameters
gctx the geometry context at the creation of the internal structure
rootVolumes the root volumes to be used for the finder
Returns
a shared detector object
Implements Acts::Experimental::IRootVolumeFinderBuilder.
Definition at line 59 of file IndexedRootVolumeFinderBuilder.cpp.
View newest version in sPHENIX GitHub at line 59 of file IndexedRootVolumeFinderBuilder.cpp
References grid(), testing::internal::move(), Acts::Experimental::detail::CylindricalDetectorHelper::rzphiBoundaries(), physmon_ckf_tracking::u, and Acts::Experimental::IndexedUpdatorImpl< grid_t, extractor_type, filler_type >::update().
Referenced by BOOST_AUTO_TEST_CASE().
Member Data Documentation
std::vector<Acts::BinningValue> Acts::Experimental::IndexedRootVolumeFinderBuilder::m_casts private
Definition at line 45 of file IndexedRootVolumeFinderBuilder.hpp.
View newest version in sPHENIX GitHub at line 45 of file IndexedRootVolumeFinderBuilder.hpp
Referenced by IndexedRootVolumeFinderBuilder().
The documentation for this exception was generated from the following files:
acts/blob/sPHENIX/Core/include/Acts/Detector/IndexedRootVolumeFinderBuilder.hpp
acts/blob/sPHENIX/Core/src/Detector/IndexedRootVolumeFinderBuilder.cpp