Analysis Software: RawTowerGeomContainer_Cylinderv1 Class Reference
RawTowerGeomContainer_Cylinderv1 Class Reference
With additional description to conveniently use in central calorimeter with eta-phi bins.
#include <coresoftware/blob/master/offline/packages/CaloBase/RawTowerGeomContainer_Cylinderv1.h>
Public Member Functions
RawTowerGeomContainer_Cylinderv1 (RawTowerDefs::CalorimeterId caloid=RawTowerDefs::NONE)
~RawTowerGeomContainer_Cylinderv1 () override
void identify (std::ostream &os=std::cout) const override
void Reset () override
Clear Event.
double get_radius () const override
double get_thickness () const override
int get_phibins () const override
int get_etabins () const override
std::pair< double, double > get_phibounds (const int ibin) const override
std::pair< double, double > get_etabounds (const int ibin) const override
double get_etacenter (const int ibin) const override
double get_phicenter (const int ibin) const override
int get_etabin (const double eta) const override
int get_phibin (const double phi) const override
void set_radius (const double r) override
void set_thickness (const double t) override
void set_phibins (const int i) override
void set_etabins (const int i) override
void set_etabounds (const int ibin, const std::pair< double, double > &bounds) override
void set_phibounds (const int ibin, const std::pair< double, double > &bounds) override
Public Member Functions inherited from RawTowerGeomContainerv1
RawTowerGeomContainerv1 (RawTowerDefs::CalorimeterId caloid=RawTowerDefs::NONE)
~RawTowerGeomContainerv1 () override
void Reset () override
Clear Event.
int isValid () const override
isValid returns non zero if object contains vailid data
void identify (std::ostream &os=std::cout) const override
void set_calorimeter_id (RawTowerDefs::CalorimeterId caloid) override
8-bit calorimeter ID
RawTowerDefs::CalorimeterId get_calorimeter_id () const override
ConstIterator add_tower_geometry (RawTowerGeom *geo) override
go through all towers
RawTowerGeom * get_tower_geometry (RawTowerDefs::keytype key) override
ConstRange get_tower_geometries (void) const override
return all tower geometries
Range get_tower_geometries (void) override
unsigned int size () const override
Public Member Functions inherited from RawTowerGeomContainer
~RawTowerGeomContainer () override
default constructor for ROOT IO
Public Member Functions inherited from PHObject
PHObject ()
ctor
~PHObject () override
dtor
virtual PHObject * CloneMe () const
Virtual copy constructor.
virtual PHObject * clone () const final
PHObject * Clone (const char *newname="") const final
void Copy (TObject &object) const final
virtual int isValid (const float) const
virtual int isValid (const double) const
virtual int isValid (const int) const
virtual int isValid (const unsigned int) const
virtual int isImplemented (const float f) const
virtual int isImplemented (const double f) const
virtual int isImplemented (const int i) const
virtual int isImplemented (const unsigned int i) const
virtual int Integrate () const
virtual int Integrate (PHObject *obj)
virtual void CopyFrom (const PHObject *obj)
Protected Types
typedef std::pair< double, double > bound_t
typedef std::vector< bound_t > bound_map_t
Protected Attributes
double radius
double thickness
bound_map_t eta_bound_map
bound_map_t phi_bound_map
Protected Attributes inherited from RawTowerGeomContainerv1
RawTowerDefs::CalorimeterId _caloid
Map _geoms
Additional Inherited Members
Public Types inherited from RawTowerGeomContainer
typedef std::map
< RawTowerDefs::keytype,
RawTowerGeom * > Map
typedef Map::iterator Iterator
typedef Map::const_iterator ConstIterator
typedef std::pair< Iterator,
Iterator > Range
typedef std::pair
< ConstIterator, ConstIterator > ConstRange
Protected Member Functions inherited from RawTowerGeomContainer
RawTowerGeomContainer ()
this class is not for use. Base class only
Detailed Description
With additional description to conveniently use in central calorimeter with eta-phi bins.
Definition at line 15 of file RawTowerGeomContainer_Cylinderv1.h.
View newest version in sPHENIX GitHub at line 15 of file RawTowerGeomContainer_Cylinderv1.h
Member Typedef Documentation
typedef std::vector<bound_t> RawTowerGeomContainer_Cylinderv1::bound_map_t protected
Definition at line 87 of file RawTowerGeomContainer_Cylinderv1.h.
View newest version in sPHENIX GitHub at line 87 of file RawTowerGeomContainer_Cylinderv1.h
typedef std::pair<double, double> RawTowerGeomContainer_Cylinderv1::bound_t protected
Definition at line 86 of file RawTowerGeomContainer_Cylinderv1.h.
View newest version in sPHENIX GitHub at line 86 of file RawTowerGeomContainer_Cylinderv1.h
Constructor & Destructor Documentation
RawTowerGeomContainer_Cylinderv1::RawTowerGeomContainer_Cylinderv1 (RawTowerDefs::CalorimeterId caloid = RawTowerDefs::NONE)
Definition at line 11 of file RawTowerGeomContainer_Cylinderv1.cc.
View newest version in sPHENIX GitHub at line 11 of file RawTowerGeomContainer_Cylinderv1.cc
RawTowerGeomContainer_Cylinderv1::~RawTowerGeomContainer_Cylinderv1 () inline override
Definition at line 20 of file RawTowerGeomContainer_Cylinderv1.h.
View newest version in sPHENIX GitHub at line 20 of file RawTowerGeomContainer_Cylinderv1.h
References Reset().
Member Function Documentation
int RawTowerGeomContainer_Cylinderv1::get_etabin (const double eta) const override virtual
Reimplemented from RawTowerGeomContainer.
Definition at line 97 of file RawTowerGeomContainer_Cylinderv1.cc.
View newest version in sPHENIX GitHub at line 97 of file RawTowerGeomContainer_Cylinderv1.cc
References eta_bound_map, and i.
Referenced by CaloTriggerSim::process_event().
int RawTowerGeomContainer_Cylinderv1::get_etabins () const inline override virtual
Reimplemented from RawTowerGeomContainer.
Definition at line 43 of file RawTowerGeomContainer_Cylinderv1.h.
View newest version in sPHENIX GitHub at line 43 of file RawTowerGeomContainer_Cylinderv1.h
References eta_bound_map.
Referenced by get_etabounds(), get_etacenter(), identify(), CaloTriggerSim::process_event(), and set_etabounds().
pair< double, double > RawTowerGeomContainer_Cylinderv1::get_etabounds (const int ibin) const override virtual
Reimplemented from RawTowerGeomContainer.
Definition at line 70 of file RawTowerGeomContainer_Cylinderv1.cc.
View newest version in sPHENIX GitHub at line 70 of file RawTowerGeomContainer_Cylinderv1.cc
References eta_bound_map, get_etabins(), and identify().
double RawTowerGeomContainer_Cylinderv1::get_etacenter (const int ibin) const override virtual
Reimplemented from RawTowerGeomContainer.
Definition at line 190 of file RawTowerGeomContainer_Cylinderv1.cc.
View newest version in sPHENIX GitHub at line 190 of file RawTowerGeomContainer_Cylinderv1.cc
References eta_bound_map, and get_etabins().
Referenced by CaloTriggerSim::process_event().
int RawTowerGeomContainer_Cylinderv1::get_phibin (const double phi) const override virtual
Reimplemented from RawTowerGeomContainer.
Definition at line 142 of file RawTowerGeomContainer_Cylinderv1.cc.
View newest version in sPHENIX GitHub at line 142 of file RawTowerGeomContainer_Cylinderv1.cc
References i, M_PI, phi_bound_map, and round().
Referenced by CaloTriggerSim::process_event().
int RawTowerGeomContainer_Cylinderv1::get_phibins () const inline override virtual
Reimplemented from RawTowerGeomContainer.
Definition at line 39 of file RawTowerGeomContainer_Cylinderv1.h.
View newest version in sPHENIX GitHub at line 39 of file RawTowerGeomContainer_Cylinderv1.h
References phi_bound_map.
Referenced by get_phibounds(), get_phicenter(), identify(), CaloTriggerSim::process_event(), and set_phibounds().
pair< double, double > RawTowerGeomContainer_Cylinderv1::get_phibounds (const int ibin) const override virtual
Reimplemented from RawTowerGeomContainer.
Definition at line 84 of file RawTowerGeomContainer_Cylinderv1.cc.
View newest version in sPHENIX GitHub at line 84 of file RawTowerGeomContainer_Cylinderv1.cc
References get_phibins(), identify(), and phi_bound_map.
double RawTowerGeomContainer_Cylinderv1::get_phicenter (const int ibin) const override virtual
Reimplemented from RawTowerGeomContainer.
Definition at line 226 of file RawTowerGeomContainer_Cylinderv1.cc.
View newest version in sPHENIX GitHub at line 226 of file RawTowerGeomContainer_Cylinderv1.cc
References get_phibins(), and phi_bound_map.
Referenced by CaloTriggerSim::process_event().
double RawTowerGeomContainer_Cylinderv1::get_radius () const inline override virtual
Reimplemented from RawTowerGeomContainer.
Definition at line 28 of file RawTowerGeomContainer_Cylinderv1.h.
View newest version in sPHENIX GitHub at line 28 of file RawTowerGeomContainer_Cylinderv1.h
References radius.
double RawTowerGeomContainer_Cylinderv1::get_thickness () const inline override virtual
Reimplemented from RawTowerGeomContainer.
Definition at line 34 of file RawTowerGeomContainer_Cylinderv1.h.
View newest version in sPHENIX GitHub at line 34 of file RawTowerGeomContainer_Cylinderv1.h
References thickness.
void RawTowerGeomContainer_Cylinderv1::identify (std::ostream & os = std::cout) const override virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from RawTowerGeomContainer.
Definition at line 42 of file RawTowerGeomContainer_Cylinderv1.cc.
View newest version in sPHENIX GitHub at line 42 of file RawTowerGeomContainer_Cylinderv1.cc
References eta_bound_map, get_etabins(), get_phibins(), i, phi_bound_map, radius, and thickness.
Referenced by get_etabounds(), and get_phibounds().
void RawTowerGeomContainer_Cylinderv1::Reset () override virtual
Clear Event.
Reimplemented from PHObject.
Definition at line 19 of file RawTowerGeomContainer_Cylinderv1.cc.
View newest version in sPHENIX GitHub at line 19 of file RawTowerGeomContainer_Cylinderv1.cc
References eta_bound_map, phi_bound_map, and RawTowerGeomContainerv1::Reset().
Referenced by ~RawTowerGeomContainer_Cylinderv1().
void RawTowerGeomContainer_Cylinderv1::set_etabins (const int i) override virtual
Reimplemented from RawTowerGeomContainer.
Definition at line 28 of file RawTowerGeomContainer_Cylinderv1.cc.
View newest version in sPHENIX GitHub at line 28 of file RawTowerGeomContainer_Cylinderv1.cc
References assert, and eta_bound_map.
void RawTowerGeomContainer_Cylinderv1::set_etabounds (const int ibin, const std::pair< double, double > & bounds) override virtual
Reimplemented from RawTowerGeomContainer.
Definition at line 203 of file RawTowerGeomContainer_Cylinderv1.cc.
View newest version in sPHENIX GitHub at line 203 of file RawTowerGeomContainer_Cylinderv1.cc
References eta_bound_map, and get_etabins().
void RawTowerGeomContainer_Cylinderv1::set_phibins (const int i) override virtual
Reimplemented from RawTowerGeomContainer.
Definition at line 35 of file RawTowerGeomContainer_Cylinderv1.cc.
View newest version in sPHENIX GitHub at line 35 of file RawTowerGeomContainer_Cylinderv1.cc
References assert, and phi_bound_map.
void RawTowerGeomContainer_Cylinderv1::set_phibounds (const int ibin, const std::pair< double, double > & bounds) override virtual
Reimplemented from RawTowerGeomContainer.
Definition at line 239 of file RawTowerGeomContainer_Cylinderv1.cc.
View newest version in sPHENIX GitHub at line 239 of file RawTowerGeomContainer_Cylinderv1.cc
References get_phibins(), and phi_bound_map.
void RawTowerGeomContainer_Cylinderv1::set_radius (const double r) inline override virtual
Reimplemented from RawTowerGeomContainer.
Definition at line 63 of file RawTowerGeomContainer_Cylinderv1.h.
View newest version in sPHENIX GitHub at line 63 of file RawTowerGeomContainer_Cylinderv1.h
References r, and radius.
void RawTowerGeomContainer_Cylinderv1::set_thickness (const double t) inline override virtual
Reimplemented from RawTowerGeomContainer.
Definition at line 68 of file RawTowerGeomContainer_Cylinderv1.h.
View newest version in sPHENIX GitHub at line 68 of file RawTowerGeomContainer_Cylinderv1.h
References t, and thickness.
Member Data Documentation
bound_map_t RawTowerGeomContainer_Cylinderv1::eta_bound_map protected
Definition at line 89 of file RawTowerGeomContainer_Cylinderv1.h.
View newest version in sPHENIX GitHub at line 89 of file RawTowerGeomContainer_Cylinderv1.h
Referenced by get_etabin(), get_etabins(), get_etabounds(), get_etacenter(), identify(), Reset(), set_etabins(), and set_etabounds().
bound_map_t RawTowerGeomContainer_Cylinderv1::phi_bound_map protected
Definition at line 90 of file RawTowerGeomContainer_Cylinderv1.h.
View newest version in sPHENIX GitHub at line 90 of file RawTowerGeomContainer_Cylinderv1.h
Referenced by get_phibin(), get_phibins(), get_phibounds(), get_phicenter(), identify(), Reset(), set_phibins(), and set_phibounds().
double RawTowerGeomContainer_Cylinderv1::radius protected
Definition at line 83 of file RawTowerGeomContainer_Cylinderv1.h.
View newest version in sPHENIX GitHub at line 83 of file RawTowerGeomContainer_Cylinderv1.h
Referenced by get_radius(), identify(), and set_radius().
double RawTowerGeomContainer_Cylinderv1::thickness protected
Definition at line 84 of file RawTowerGeomContainer_Cylinderv1.h.
View newest version in sPHENIX GitHub at line 84 of file RawTowerGeomContainer_Cylinderv1.h
Referenced by get_thickness(), identify(), and set_thickness().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/CaloBase/RawTowerGeomContainer_Cylinderv1.h
coresoftware/blob/master/offline/packages/CaloBase/RawTowerGeomContainer_Cylinderv1.cc