Analysis Software: MicromegasRawDataDecoder Class Reference
MicromegasRawDataDecoder Class Reference
micromegas raw data decoder
#include <coresoftware/blob/master/offline/packages/micromegas/MicromegasRawDataDecoder.h>
Public Member Functions
MicromegasRawDataDecoder (const std::string &name="MicromegasRawDataDecoder")
constructor
int Init (PHCompositeNode *) override
global initialization
int InitRun (PHCompositeNode *) override
run initialization
int process_event (PHCompositeNode *) override
event processing
int End (PHCompositeNode *) override
end of processing
void set_calibration_file (const std::string &value)
calibration file
void set_n_sigma (double value)
set number of RMS sigma used to defined static threshold on a given channel
void set_min_adc (double value)
set minimum ADC value, disregarding pedestal and RMS.
void set_sample_min (int value)
set min sample for noise estimation
void set_sample_max (int value)
set min sample for noise estimation
Public Member Functions inherited from SubsysReco
~SubsysReco () override
virtual int EndRun (const int)
Called at the end of each run.
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
void Print (const std::string &="ALL") const override
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Private Types
using hitcountmap_t = std::map< TrkrDefs::hitsetkey, int >
keep track of number of hits per hitsetid
Private Attributes
std::string m_calibration_filename = "TPOT_Pedestal_000.root"
calibration filename
MicromegasCalibrationData m_calibration_data
calibration data
MicromegasMapping m_mapping
mapping
double m_n_sigma = 5
number of RMS sigma used to define threshold
double m_min_adc = 50
minimum ADC value, disregarding pedestal and RMS.
int m_sample_min = 0
min sample for signal
int m_sample_max = 100
max sample for signal
hitcountmap_t m_hitcounts
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = std::numeric_limits<int>::max() - 10
}
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Detailed Description
micromegas raw data decoder
Definition at line 20 of file MicromegasRawDataDecoder.h.
View newest version in sPHENIX GitHub at line 20 of file MicromegasRawDataDecoder.h
Member Typedef Documentation
using MicromegasRawDataDecoder::hitcountmap_t = std::map<TrkrDefs::hitsetkey,int> private
keep track of number of hits per hitsetid
Definition at line 80 of file MicromegasRawDataDecoder.h.
View newest version in sPHENIX GitHub at line 80 of file MicromegasRawDataDecoder.h
Constructor & Destructor Documentation
MicromegasRawDataDecoder::MicromegasRawDataDecoder (const std::string & name = "MicromegasRawDataDecoder")
constructor
Definition at line 28 of file MicromegasRawDataDecoder.cc.
View newest version in sPHENIX GitHub at line 28 of file MicromegasRawDataDecoder.cc
Member Function Documentation
int MicromegasRawDataDecoder::End (PHCompositeNode *) override virtual
end of processing
Reimplemented from SubsysReco.
Definition at line 199 of file MicromegasRawDataDecoder.cc.
View newest version in sPHENIX GitHub at line 199 of file MicromegasRawDataDecoder.cc
References test_fpe::count, Fun4AllReturnCodes::EVENT_OK, and m_hitcounts.
int MicromegasRawDataDecoder::Init (PHCompositeNode *) override virtual
global initialization
Reimplemented from SubsysReco.
Definition at line 33 of file MicromegasRawDataDecoder.cc.
View newest version in sPHENIX GitHub at line 33 of file MicromegasRawDataDecoder.cc
References Fun4AllReturnCodes::EVENT_OK, m_calibration_data, m_calibration_filename, and MicromegasCalibrationData::read().
int MicromegasRawDataDecoder::InitRun (PHCompositeNode * topNode) override virtual
run initialization
Reimplemented from SubsysReco.
Definition at line 41 of file MicromegasRawDataDecoder.cc.
View newest version in sPHENIX GitHub at line 41 of file MicromegasRawDataDecoder.cc
References Fun4AllReturnCodes::EVENT_OK, and PHNodeIterator::findFirst().
int MicromegasRawDataDecoder::process_event (PHCompositeNode * topNode) override virtual
event processing
Reimplemented from SubsysReco.
Definition at line 79 of file MicromegasRawDataDecoder.cc.
View newest version in sPHENIX GitHub at line 79 of file MicromegasRawDataDecoder.cc
References assert, channel(), Fun4AllReturnCodes::DISCARDEVENT, event, Fun4AllReturnCodes::EVENT_OK, MicromegasDefs::genHitKey(), MicromegasMapping::get_hitsetkey(), MicromegasCalibrationData::get_pedestal(), MicromegasMapping::get_physical_strip(), MicromegasCalibrationData::get_rms(), TrkrDefs::getLayer(), MicromegasDefs::getTileId(), m_calibration_data, m_hitcounts, m_mapping, m_min_adc, m_n_sigma, MicromegasDefs::m_packet_ids, m_sample_max, m_sample_min, Acts::UnitConstants::min, pedestal(), rms(), TrkrHitv2::setAdc(), and Fun4AllBase::Verbosity().
void MicromegasRawDataDecoder::set_calibration_file (const std::string & value) inline
calibration file
Definition at line 40 of file MicromegasRawDataDecoder.h.
View newest version in sPHENIX GitHub at line 40 of file MicromegasRawDataDecoder.h
References m_calibration_filename, and value.
void MicromegasRawDataDecoder::set_min_adc (double value) inline
set minimum ADC value, disregarding pedestal and RMS.
This removes faulty channels for which calibration has failed
Definition at line 47 of file MicromegasRawDataDecoder.h.
View newest version in sPHENIX GitHub at line 47 of file MicromegasRawDataDecoder.h
References m_min_adc, and value.
void MicromegasRawDataDecoder::set_n_sigma (double value) inline
set number of RMS sigma used to defined static threshold on a given channel
Definition at line 43 of file MicromegasRawDataDecoder.h.
View newest version in sPHENIX GitHub at line 43 of file MicromegasRawDataDecoder.h
References m_n_sigma, and value.
void MicromegasRawDataDecoder::set_sample_max (int value) inline
set min sample for noise estimation
Definition at line 53 of file MicromegasRawDataDecoder.h.
View newest version in sPHENIX GitHub at line 53 of file MicromegasRawDataDecoder.h
References m_sample_max, and value.
void MicromegasRawDataDecoder::set_sample_min (int value) inline
set min sample for noise estimation
Definition at line 50 of file MicromegasRawDataDecoder.h.
View newest version in sPHENIX GitHub at line 50 of file MicromegasRawDataDecoder.h
References m_sample_min, and value.
Member Data Documentation
MicromegasCalibrationData MicromegasRawDataDecoder::m_calibration_data private
calibration data
Definition at line 61 of file MicromegasRawDataDecoder.h.
View newest version in sPHENIX GitHub at line 61 of file MicromegasRawDataDecoder.h
Referenced by Init(), and process_event().
std::string MicromegasRawDataDecoder::m_calibration_filename = "TPOT_Pedestal_000.root" private
calibration filename
Definition at line 58 of file MicromegasRawDataDecoder.h.
View newest version in sPHENIX GitHub at line 58 of file MicromegasRawDataDecoder.h
Referenced by Init(), and set_calibration_file().
hitcountmap_t MicromegasRawDataDecoder::m_hitcounts private
Definition at line 81 of file MicromegasRawDataDecoder.h.
View newest version in sPHENIX GitHub at line 81 of file MicromegasRawDataDecoder.h
Referenced by End(), and process_event().
MicromegasMapping MicromegasRawDataDecoder::m_mapping private
mapping
Definition at line 64 of file MicromegasRawDataDecoder.h.
View newest version in sPHENIX GitHub at line 64 of file MicromegasRawDataDecoder.h
Referenced by process_event().
double MicromegasRawDataDecoder::m_min_adc = 50 private
minimum ADC value, disregarding pedestal and RMS.
Definition at line 71 of file MicromegasRawDataDecoder.h.
View newest version in sPHENIX GitHub at line 71 of file MicromegasRawDataDecoder.h
Referenced by process_event(), and set_min_adc().
double MicromegasRawDataDecoder::m_n_sigma = 5 private
number of RMS sigma used to define threshold
Definition at line 67 of file MicromegasRawDataDecoder.h.
View newest version in sPHENIX GitHub at line 67 of file MicromegasRawDataDecoder.h
Referenced by process_event(), and set_n_sigma().
int MicromegasRawDataDecoder::m_sample_max = 100 private
max sample for signal
Definition at line 77 of file MicromegasRawDataDecoder.h.
View newest version in sPHENIX GitHub at line 77 of file MicromegasRawDataDecoder.h
Referenced by process_event(), and set_sample_max().
int MicromegasRawDataDecoder::m_sample_min = 0 private
min sample for signal
Definition at line 74 of file MicromegasRawDataDecoder.h.
View newest version in sPHENIX GitHub at line 74 of file MicromegasRawDataDecoder.h
Referenced by process_event(), and set_sample_min().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/micromegas/MicromegasRawDataDecoder.h
coresoftware/blob/master/offline/packages/micromegas/MicromegasRawDataDecoder.cc