Analysis Software: AfterburnerModus Class Reference
AfterburnerModus Class Reference
#include <JETSCAPE/blob/main/src/afterburner/SmashWrapper.h>
Public Member Functions
AfterburnerModus (smash::Configuration config, const smash::ExperimentParameters &)
void reset_event_numbering ()
void JS_hadrons_to_smash_particles (const std::vector< shared_ptr< Hadron >> &JS_hadrons, smash::Particles &smash_particles)
double initial_conditions (smash::Particles *particles, const smash::ExperimentParameters &)
Public Attributes
std::vector< std::vector
< shared_ptr< Hadron > > > jetscape_hadrons_
Private Attributes
int event_number_ = 0
Detailed Description
An Afterburner modus, which acts similarly to SMASH ListModus, initializes from Jetscape hadrons, not from file. Needed to use SMASH as a 3rd party Afterburner.
Definition at line 36 of file SmashWrapper.h.
View newest version in sPHENIX GitHub at line 36 of file SmashWrapper.h
Constructor & Destructor Documentation
AfterburnerModus::AfterburnerModus (smash::Configuration config, const smash::ExperimentParameters &) inline
Definition at line 39 of file SmashWrapper.h.
View newest version in sPHENIX GitHub at line 39 of file SmashWrapper.h
References JSINFO.
Member Function Documentation
double AfterburnerModus::initial_conditions (smash::Particles * particles, const smash::ExperimentParameters &) inline
Definition at line 53 of file SmashWrapper.h.
View newest version in sPHENIX GitHub at line 53 of file SmashWrapper.h
void AfterburnerModus::JS_hadrons_to_smash_particles (const std::vector< shared_ptr< Hadron >> & JS_hadrons, smash::Particles & smash_particles)
Definition at line 121 of file SmashWrapper.cc.
View newest version in sPHENIX GitHub at line 121 of file SmashWrapper.cc
References mass, merge_hashes::p, physmon_track_finding_ttbar::r, Jetscape::FourVector::t(), Jetscape::FourVector::x(), Jetscape::FourVector::y(), and Jetscape::FourVector::z().
void AfterburnerModus::reset_event_numbering () inline
Definition at line 43 of file SmashWrapper.h.
View newest version in sPHENIX GitHub at line 43 of file SmashWrapper.h
Referenced by SmashWrapper::ExecuteTask().
Member Data Documentation
int AfterburnerModus::event_number_ = 0 private
Definition at line 63 of file SmashWrapper.h.
View newest version in sPHENIX GitHub at line 63 of file SmashWrapper.h
std::vector<std::vector<shared_ptr<Hadron> > > AfterburnerModus::jetscape_hadrons_
Definition at line 60 of file SmashWrapper.h.
View newest version in sPHENIX GitHub at line 60 of file SmashWrapper.h
Referenced by SmashWrapper::ExecuteTask(), and SmashWrapper::WriteTask().
The documentation for this class was generated from the following files:
JETSCAPE/blob/main/src/afterburner/SmashWrapper.h
JETSCAPE/blob/main/src/afterburner/SmashWrapper.cc