Analysis Software: DSTTrackInfoReader Class Reference
DSTTrackInfoReader Class Reference
#include <coresoftware/blob/master/simulation/g4simulation/g4eval/DSTTrackInfoReader.h>
Public Types
enum Flags { WriteEvent = 1 << 0, WriteClusters = 1 << 1, WriteTracks = 1 << 2 }
Public Member Functions
DSTTrackInfoReader (const std::string &="DSTTrackInfoReader")
constructor
int InitRun (PHCompositeNode *) override
run initialization
int process_event (PHCompositeNode *) override
event processing
void set_flags (int flags)
set flags. Should be a bitwise or of Flags enum
Public Member Functions inherited from SubsysReco
~SubsysReco () override
virtual int End (PHCompositeNode *)
Called at the end of all processing.
virtual int EndRun (const int)
Called at the end of each run.
virtual int Init (PHCompositeNode *)
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
void Print (const std::string &="ALL") const override
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Private Member Functions
int load_nodes (PHCompositeNode *)
load nodes
void evaluate_track_info ()
Private Attributes
TrackInfoContainer_v1 * m_track_info_container = nullptr
int m_flags = WriteEvent | WriteClusters | WriteTracks
flags
Additional Inherited Members
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Detailed Description
Definition at line 37 of file DSTTrackInfoReader.h.
View newest version in sPHENIX GitHub at line 37 of file DSTTrackInfoReader.h
Member Enumeration Documentation
enum DSTTrackInfoReader::Flags
Enumerator:
WriteEvent
WriteClusters
WriteTracks
Definition at line 49 of file DSTTrackInfoReader.h.
View newest version in sPHENIX GitHub at line 49 of file DSTTrackInfoReader.h
Constructor & Destructor Documentation
DSTTrackInfoReader::DSTTrackInfoReader (const std::string & name = "DSTTrackInfoReader")
constructor
Definition at line 46 of file DSTTrackInfoReader.cc.
View newest version in sPHENIX GitHub at line 46 of file DSTTrackInfoReader.cc
Member Function Documentation
void DSTTrackInfoReader::evaluate_track_info () private
Definition at line 104 of file DSTTrackInfoReader.cc.
View newest version in sPHENIX GitHub at line 104 of file DSTTrackInfoReader.cc
References TrackInfoContainer_v1::get_trackinfo(), m_track_info_container, TrackInfoContainer_v1::size(), and Fun4AllBase::Verbosity().
Referenced by process_event().
int DSTTrackInfoReader::InitRun (PHCompositeNode * topNode) override virtual
run initialization
Reimplemented from SubsysReco.
Definition at line 52 of file DSTTrackInfoReader.cc.
View newest version in sPHENIX GitHub at line 52 of file DSTTrackInfoReader.cc
References Fun4AllReturnCodes::EVENT_OK, and m_track_info_container.
int DSTTrackInfoReader::load_nodes (PHCompositeNode * topNode) private
load nodes
Definition at line 94 of file DSTTrackInfoReader.cc.
View newest version in sPHENIX GitHub at line 94 of file DSTTrackInfoReader.cc
References Fun4AllReturnCodes::EVENT_OK, and m_track_info_container.
Referenced by process_event().
int DSTTrackInfoReader::process_event (PHCompositeNode * topNode) override virtual
event processing
Reimplemented from SubsysReco.
Definition at line 75 of file DSTTrackInfoReader.cc.
View newest version in sPHENIX GitHub at line 75 of file DSTTrackInfoReader.cc
References evaluate_track_info(), Fun4AllReturnCodes::EVENT_OK, load_nodes(), m_track_info_container, and TrackInfoContainer_v1::Reset().
void DSTTrackInfoReader::set_flags (int flags) inline
set flags. Should be a bitwise or of Flags enum
Definition at line 57 of file DSTTrackInfoReader.h.
View newest version in sPHENIX GitHub at line 57 of file DSTTrackInfoReader.h
References m_flags.
Member Data Documentation
int DSTTrackInfoReader::m_flags = WriteEvent | WriteClusters | WriteTracks private
flags
Definition at line 76 of file DSTTrackInfoReader.h.
View newest version in sPHENIX GitHub at line 76 of file DSTTrackInfoReader.h
Referenced by set_flags().
TrackInfoContainer_v1* DSTTrackInfoReader::m_track_info_container = nullptr private
Definition at line 72 of file DSTTrackInfoReader.h.
View newest version in sPHENIX GitHub at line 72 of file DSTTrackInfoReader.h
Referenced by evaluate_track_info(), InitRun(), load_nodes(), and process_event().
The documentation for this class was generated from the following files:
coresoftware/blob/master/simulation/g4simulation/g4eval/DSTTrackInfoReader.h
coresoftware/blob/master/simulation/g4simulation/g4eval/DSTTrackInfoReader.cc