Analysis Software: analysis/blob/master/Tracking/BenchmarkingTools/CommonTools.h File Reference
CommonTools.h File Reference
Functions
void myText (Double_t x, Double_t y, Color_t color, const char *text, Double_t tsize=0.05, double angle=-1)
void DivideCanvas (TVirtualPad *p, int npads)
Divide canvas in a given number of pads, with a number of pads in both directions that match the width/height ratio of the canvas.
TGraphErrors * FitProfile (const TH2 *h2)
Fit for profile along the Y direction of TH2F.
TLine * HorizontalLine (TVirtualPad *p, Double_t y)
Draw a horizontal line in a pad at given x coordinate.
TGraphErrors * FitResolution (const TH2F *h2, const bool normalize_mean=true, const int param=2)
Fit for resolution of TH2F.
TH1 * GetBinominalRatio (TH1 *h_pass, TH1 *h_n_trial, bool process_zero_bins=false)
ratio between two histograms with binominal error based on Wilson score interval. Assuming each histogram is count.
TLine * VerticalLine (TVirtualPad *p, Double_t x)
Draw a vertical line in a pad at given x coordinate.
double DrawReference (TH1 *hnew, TH1 *href, bool draw_href_error=false, bool do_kstest=true)
void DrawReference (TGraph *hnew, TGraph *href, bool draw_href_error=true)
Function Documentation
void DivideCanvas (TVirtualPad * p, int npads)
Divide canvas in a given number of pads, with a number of pads in both directions that match the width/height ratio of the canvas.
Definition at line 384 of file CommonTools.h.
View newest version in sPHENIX GitHub at line 384 of file CommonTools.h
References double(), and parse_cmake_options::rows.
Referenced by Draw().
double DrawReference (TH1 * hnew, TH1 * href, bool draw_href_error = false, bool do_kstest = true)
Definition at line 217 of file CommonTools.h.
View newest version in sPHENIX GitHub at line 217 of file CommonTools.h
Referenced by Draw(), Draw_eff(), TrackingQA(), and VertexingQA().
void DrawReference (TGraph * hnew, TGraph * href, bool draw_href_error = true)
Draw 1D TGraph along with its reference as shade
Parameters
[in] draw_href_error whether to draw error band for reference plot. Otherwise, it is a filled histogram (default)
Definition at line 315 of file CommonTools.h.
View newest version in sPHENIX GitHub at line 315 of file CommonTools.h
TGraphErrors* FitProfile (const TH2 * h2)
Fit for profile along the Y direction of TH2F.
TGraphErrors* FitResolution (const TH2F * h2, const bool normalize_mean = true, const int param = 2)
Fit for resolution of TH2F.
Definition at line 39 of file CommonTools.h.
View newest version in sPHENIX GitHub at line 39 of file CommonTools.h
References std::tr1::f2, h1, i, n, norm, ambiguity_solver_full_chain::x, and y.
Referenced by TrackingQA().
TH1* GetBinominalRatio (TH1 * h_pass, TH1 * h_n_trial, bool process_zero_bins = false)
ratio between two histograms with binominal error based on Wilson score interval. Assuming each histogram is count.
Definition at line 154 of file CommonTools.h.
View newest version in sPHENIX GitHub at line 154 of file CommonTools.h
References assert, merge_hashes::p, ambiguity_solver_full_chain::x, y, and physmon_track_finding_ttbar::z.
Referenced by TrackingQA().
TLine* HorizontalLine (TVirtualPad * p, Double_t y)
Draw a horizontal line in a pad at given x coordinate.
Definition at line 17 of file CommonTools.h.
View newest version in sPHENIX GitHub at line 17 of file CommonTools.h
References line.
Referenced by Draw_eff(), TrackingQA(), and VertexingQA().
void myText (Double_t x, Double_t y, Color_t color, const char * text, Double_t tsize = 0.05, double angle = -1)
Definition at line 5 of file CommonTools.h.
View newest version in sPHENIX GitHub at line 5 of file CommonTools.h
TLine* VerticalLine (TVirtualPad * p, Double_t x)
Draw a vertical line in a pad at given x coordinate.
Definition at line 198 of file CommonTools.h.
View newest version in sPHENIX GitHub at line 198 of file CommonTools.h
References line.
Referenced by Draw().