Analysis Software: ActsExamples::TrackParameterSelector Exception Reference
ActsExamples::TrackParameterSelector Exception Reference final
Select tracks by applying some selection cuts.
#include <acts/blob/sPHENIX/Examples/Algorithms/TruthTracking/ActsExamples/TruthTracking/TrackParameterSelector.hpp>
Classes
struct Config
Public Member Functions
TrackParameterSelector (const Config &config, Acts::Logging::Level level)
ProcessCode execute (const AlgorithmContext &ctx) const final
const Config & config () const
Get readonly access to the config parameters.
Public Member Functions inherited from ActsExamples::IAlgorithm
IAlgorithm (std::string name, Acts::Logging::Level level=Acts::Logging::INFO)
std::string name () const override
The algorithm name.
ProcessCode internalExecute (const AlgorithmContext &context) final
ProcessCode initialize () override
Initialize the algorithm.
ProcessCode finalize () override
Finalize the algorithm.
Private Attributes
Config m_cfg
ReadDataHandle
< TrackParametersContainer > m_inputTrackParameters
WriteDataHandle
< TrackParametersContainer > m_outputTrackParameters
Additional Inherited Members
Protected Member Functions inherited from ActsExamples::IAlgorithm
const Acts::Logger & logger () const
Detailed Description
Select tracks by applying some selection cuts.
Definition at line 24 of file TrackParameterSelector.hpp.
View newest version in sPHENIX GitHub at line 24 of file TrackParameterSelector.hpp
Constructor & Destructor Documentation
ActsExamples::TrackParameterSelector::TrackParameterSelector (const Config & config, Acts::Logging::Level level)
Definition at line 22 of file TrackParameterSelector.cpp.
View newest version in sPHENIX GitHub at line 22 of file TrackParameterSelector.cpp
References ActsExamples::WriteDataHandle< T >::initialize(), ActsExamples::ReadDataHandle< T >::initialize(), ActsExamples::TrackParameterSelector::Config::inputTrackParameters, m_cfg, m_inputTrackParameters, m_outputTrackParameters, and ActsExamples::TrackParameterSelector::Config::outputTrackParameters.
Member Function Documentation
const Config& ActsExamples::TrackParameterSelector::config () const inline
Get readonly access to the config parameters.
Definition at line 57 of file TrackParameterSelector.hpp.
View newest version in sPHENIX GitHub at line 57 of file TrackParameterSelector.hpp
References m_cfg.
ActsExamples::ProcessCode ActsExamples::TrackParameterSelector::execute (const AlgorithmContext & context) const final virtual
Execute the algorithm for one event.
This function must be implemented by subclasses.
Implements ActsExamples::IAlgorithm.
Definition at line 36 of file TrackParameterSelector.cpp.
View newest version in sPHENIX GitHub at line 36 of file TrackParameterSelector.cpp
References ACTS_DEBUG, eta, ActsExamples::AlgorithmContext::eventNumber, i, m_cfg(), Acts::UnitConstants::min, testing::internal::move(), SUCCESS, ActsTests::PropagationDatasets::theta, and ambiguity_solver_full_chain::x.
Member Data Documentation
Config ActsExamples::TrackParameterSelector::m_cfg private
Definition at line 60 of file TrackParameterSelector.hpp.
View newest version in sPHENIX GitHub at line 60 of file TrackParameterSelector.hpp
Referenced by config(), and TrackParameterSelector().
ReadDataHandle<TrackParametersContainer> ActsExamples::TrackParameterSelector::m_inputTrackParameters private
Initial value:
{
      this, "InputTrackParameters"}
Definition at line 62 of file TrackParameterSelector.hpp.
View newest version in sPHENIX GitHub at line 62 of file TrackParameterSelector.hpp
Referenced by TrackParameterSelector().
WriteDataHandle<TrackParametersContainer> ActsExamples::TrackParameterSelector::m_outputTrackParameters private
Initial value:
{
      this, "OutputTrackParameters"}
Definition at line 64 of file TrackParameterSelector.hpp.
View newest version in sPHENIX GitHub at line 64 of file TrackParameterSelector.hpp
Referenced by TrackParameterSelector().
The documentation for this exception was generated from the following files:
acts/blob/sPHENIX/Examples/Algorithms/TruthTracking/ActsExamples/TruthTracking/TrackParameterSelector.hpp
acts/blob/sPHENIX/Examples/Algorithms/TruthTracking/ActsExamples/TruthTracking/TrackParameterSelector.cpp