Analysis Software: RawTowerGeomv4 Class Reference
RawTowerGeomv4 Class Reference
#include <coresoftware/blob/master/offline/packages/CaloBase/RawTowerGeomv4.h>
Public Member Functions
RawTowerGeomv4 ()
RawTowerGeomv4 (RawTowerDefs::keytype id)
virtual ~RawTowerGeomv4 ()
void identify (std::ostream &os=std::cout) const override
void set_id (RawTowerDefs::keytype key) override
RawTowerDefs::keytype get_id () const override
int get_bineta () const override
int get_binphi () const override
int get_column () const override
int get_row () const override
void set_center_x (double x) override
void set_center_y (double y) override
void set_center_z (double z) override
void set_roty (double roty) override
void set_rotz (double rotz) override
double get_center_x () const override
double get_center_y () const override
double get_center_z () const override
double get_roty () const override
double get_rotz () const override
TVector3 get_final_position () const
double get_center_radius () const override
double get_eta () const override
double get_phi () const override
double get_theta () const override
void set_tower_type (int tt) override
int get_tower_type () const override
Public Member Functions inherited from RawTowerGeom
~RawTowerGeom () override
virtual int get_binl () const
virtual void set_size_x (double)
virtual void set_size_y (double)
virtual void set_size_z (double)
virtual double get_size_x () const
virtual double get_size_y () const
virtual double get_size_z () const
virtual double get_volume () const
Public Member Functions inherited from PHObject
PHObject ()
ctor
~PHObject () override
dtor
virtual PHObject * CloneMe () const
Virtual copy constructor.
virtual PHObject * clone () const final
PHObject * Clone (const char *newname="") const final
void Copy (TObject &object) const final
virtual void Reset ()
Clear Event.
virtual int isValid () const
isValid returns non zero if object contains vailid data
virtual int Integrate () const
virtual int Integrate (PHObject *)
virtual void CopyFrom (const PHObject *obj)
Protected Attributes
RawTowerDefs::keytype _towerid = ~0
double _center_x = NAN
double _center_y = NAN
double _center_z = NAN
double _roty = NAN
double _rotz = NAN
int _tower_type = -1
Additional Inherited Members
Protected Member Functions inherited from RawTowerGeom
RawTowerGeom ()
Detailed Description
Definition at line 13 of file RawTowerGeomv4.h.
View newest version in sPHENIX GitHub at line 13 of file RawTowerGeomv4.h
Constructor & Destructor Documentation
RawTowerGeomv4::RawTowerGeomv4 () inline
Definition at line 16 of file RawTowerGeomv4.h.
View newest version in sPHENIX GitHub at line 16 of file RawTowerGeomv4.h
RawTowerGeomv4::RawTowerGeomv4 (RawTowerDefs::keytype id)
Definition at line 6 of file RawTowerGeomv4.cc.
View newest version in sPHENIX GitHub at line 6 of file RawTowerGeomv4.cc
virtual RawTowerGeomv4::~RawTowerGeomv4 () inline virtual
Definition at line 18 of file RawTowerGeomv4.h.
View newest version in sPHENIX GitHub at line 18 of file RawTowerGeomv4.h
Member Function Documentation
int RawTowerGeomv4::get_bineta () const inline override virtual
Reimplemented from RawTowerGeom.
Definition at line 25 of file RawTowerGeomv4.h.
View newest version in sPHENIX GitHub at line 25 of file RawTowerGeomv4.h
References _towerid, and RawTowerDefs::decode_index1().
int RawTowerGeomv4::get_binphi () const inline override virtual
Reimplemented from RawTowerGeom.
Definition at line 26 of file RawTowerGeomv4.h.
View newest version in sPHENIX GitHub at line 26 of file RawTowerGeomv4.h
References _towerid, and RawTowerDefs::decode_index2().
double RawTowerGeomv4::get_center_radius () const override virtual
Reimplemented from RawTowerGeom.
Definition at line 11 of file RawTowerGeomv4.cc.
View newest version in sPHENIX GitHub at line 11 of file RawTowerGeomv4.cc
References _center_x, and _center_y.
double RawTowerGeomv4::get_center_x () const inline override virtual
Reimplemented from RawTowerGeom.
Definition at line 56 of file RawTowerGeomv4.h.
View newest version in sPHENIX GitHub at line 56 of file RawTowerGeomv4.h
References _center_x.
Referenced by identify().
double RawTowerGeomv4::get_center_y () const inline override virtual
Reimplemented from RawTowerGeom.
Definition at line 57 of file RawTowerGeomv4.h.
View newest version in sPHENIX GitHub at line 57 of file RawTowerGeomv4.h
References _center_y.
Referenced by identify().
double RawTowerGeomv4::get_center_z () const inline override virtual
Reimplemented from RawTowerGeom.
Definition at line 58 of file RawTowerGeomv4.h.
View newest version in sPHENIX GitHub at line 58 of file RawTowerGeomv4.h
References _center_z.
Referenced by identify().
int RawTowerGeomv4::get_column () const inline override virtual
Reimplemented from RawTowerGeom.
Definition at line 27 of file RawTowerGeomv4.h.
View newest version in sPHENIX GitHub at line 27 of file RawTowerGeomv4.h
References _towerid, and RawTowerDefs::decode_index1().
double RawTowerGeomv4::get_eta () const override virtual
Reimplemented from RawTowerGeom.
Definition at line 24 of file RawTowerGeomv4.cc.
View newest version in sPHENIX GitHub at line 24 of file RawTowerGeomv4.cc
References eta, get_theta(), and ActsTests::PropagationDatasets::theta.
TVector3 RawTowerGeomv4::get_final_position () const
RawTowerDefs::keytype RawTowerGeomv4::get_id () const inline override virtual
Reimplemented from RawTowerGeom.
Definition at line 23 of file RawTowerGeomv4.h.
View newest version in sPHENIX GitHub at line 23 of file RawTowerGeomv4.h
References _towerid.
double RawTowerGeomv4::get_phi () const override virtual
Reimplemented from RawTowerGeom.
Definition at line 31 of file RawTowerGeomv4.cc.
View newest version in sPHENIX GitHub at line 31 of file RawTowerGeomv4.cc
References _center_x, and _center_y.
double RawTowerGeomv4::get_roty () const inline override virtual
Reimplemented from RawTowerGeom.
Definition at line 59 of file RawTowerGeomv4.h.
View newest version in sPHENIX GitHub at line 59 of file RawTowerGeomv4.h
References _roty.
double RawTowerGeomv4::get_rotz () const inline override virtual
Reimplemented from RawTowerGeom.
Definition at line 60 of file RawTowerGeomv4.h.
View newest version in sPHENIX GitHub at line 60 of file RawTowerGeomv4.h
References _rotz.
int RawTowerGeomv4::get_row () const inline override virtual
Reimplemented from RawTowerGeom.
Definition at line 28 of file RawTowerGeomv4.h.
View newest version in sPHENIX GitHub at line 28 of file RawTowerGeomv4.h
References _towerid, and RawTowerDefs::decode_index2().
double RawTowerGeomv4::get_theta () const override virtual
Reimplemented from RawTowerGeom.
Definition at line 17 of file RawTowerGeomv4.cc.
View newest version in sPHENIX GitHub at line 17 of file RawTowerGeomv4.cc
References _center_x, _center_y, _center_z, and ActsTests::PropagationDatasets::theta.
Referenced by get_eta().
int RawTowerGeomv4::get_tower_type () const inline override virtual
Reimplemented from RawTowerGeom.
Definition at line 69 of file RawTowerGeomv4.h.
View newest version in sPHENIX GitHub at line 69 of file RawTowerGeomv4.h
References _tower_type.
void RawTowerGeomv4::identify (std::ostream & os = std::cout) const override virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from RawTowerGeom.
Definition at line 36 of file RawTowerGeomv4.cc.
View newest version in sPHENIX GitHub at line 36 of file RawTowerGeomv4.cc
References _tower_type, get_center_x(), get_center_y(), get_center_z(), RawTowerGeom::get_size_x(), RawTowerGeom::get_size_y(), and RawTowerGeom::get_size_z().
void RawTowerGeomv4::set_center_x (double x) inline override virtual
Reimplemented from RawTowerGeom.
Definition at line 30 of file RawTowerGeomv4.h.
View newest version in sPHENIX GitHub at line 30 of file RawTowerGeomv4.h
References _center_x, and ambiguity_solver_full_chain::x.
void RawTowerGeomv4::set_center_y (double y) inline override virtual
Reimplemented from RawTowerGeom.
Definition at line 35 of file RawTowerGeomv4.h.
View newest version in sPHENIX GitHub at line 35 of file RawTowerGeomv4.h
References _center_y, and y.
void RawTowerGeomv4::set_center_z (double z) inline override virtual
Reimplemented from RawTowerGeom.
Definition at line 40 of file RawTowerGeomv4.h.
View newest version in sPHENIX GitHub at line 40 of file RawTowerGeomv4.h
References _center_z, and physmon_track_finding_ttbar::z.
void RawTowerGeomv4::set_id (RawTowerDefs::keytype key) inline override virtual
Reimplemented from RawTowerGeom.
Definition at line 22 of file RawTowerGeomv4.h.
View newest version in sPHENIX GitHub at line 22 of file RawTowerGeomv4.h
References _towerid.
void RawTowerGeomv4::set_roty (double roty) inline override virtual
Reimplemented from RawTowerGeom.
Definition at line 45 of file RawTowerGeomv4.h.
View newest version in sPHENIX GitHub at line 45 of file RawTowerGeomv4.h
References _roty.
void RawTowerGeomv4::set_rotz (double rotz) inline override virtual
Reimplemented from RawTowerGeom.
Definition at line 50 of file RawTowerGeomv4.h.
View newest version in sPHENIX GitHub at line 50 of file RawTowerGeomv4.h
References _rotz.
void RawTowerGeomv4::set_tower_type (int tt) inline override virtual
Reimplemented from RawTowerGeom.
Definition at line 68 of file RawTowerGeomv4.h.
View newest version in sPHENIX GitHub at line 68 of file RawTowerGeomv4.h
References _tower_type.
Member Data Documentation
double RawTowerGeomv4::_center_x = NAN protected
Definition at line 74 of file RawTowerGeomv4.h.
View newest version in sPHENIX GitHub at line 74 of file RawTowerGeomv4.h
Referenced by get_center_radius(), get_center_x(), get_phi(), get_theta(), and set_center_x().
double RawTowerGeomv4::_center_y = NAN protected
Definition at line 75 of file RawTowerGeomv4.h.
View newest version in sPHENIX GitHub at line 75 of file RawTowerGeomv4.h
Referenced by get_center_radius(), get_center_y(), get_phi(), get_theta(), and set_center_y().
double RawTowerGeomv4::_center_z = NAN protected
Definition at line 76 of file RawTowerGeomv4.h.
View newest version in sPHENIX GitHub at line 76 of file RawTowerGeomv4.h
Referenced by get_center_z(), get_theta(), and set_center_z().
double RawTowerGeomv4::_roty = NAN protected
Definition at line 77 of file RawTowerGeomv4.h.
View newest version in sPHENIX GitHub at line 77 of file RawTowerGeomv4.h
Referenced by get_roty(), and set_roty().
double RawTowerGeomv4::_rotz = NAN protected
Definition at line 78 of file RawTowerGeomv4.h.
View newest version in sPHENIX GitHub at line 78 of file RawTowerGeomv4.h
Referenced by get_rotz(), and set_rotz().
int RawTowerGeomv4::_tower_type = -1 protected
Definition at line 80 of file RawTowerGeomv4.h.
View newest version in sPHENIX GitHub at line 80 of file RawTowerGeomv4.h
Referenced by get_tower_type(), identify(), and set_tower_type().
RawTowerDefs::keytype RawTowerGeomv4::_towerid = ~0 protected
Definition at line 72 of file RawTowerGeomv4.h.
View newest version in sPHENIX GitHub at line 72 of file RawTowerGeomv4.h
Referenced by get_bineta(), get_binphi(), get_column(), get_id(), get_row(), and set_id().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/CaloBase/RawTowerGeomv4.h
coresoftware/blob/master/offline/packages/CaloBase/RawTowerGeomv4.cc