Analysis Software: PHG4InttSteppingAction Class Reference
PHG4InttSteppingAction Class Reference
#include <coresoftware/blob/master/simulation/g4simulation/g4intt/PHG4InttSteppingAction.h>
Public Member Functions
PHG4InttSteppingAction (PHG4InttDetector *, const PHParametersContainer *parameters, const std::pair< std::vector< std::pair< int, int >>::const_iterator, std::vector< std::pair< int, int >>::const_iterator > &layer_begin_end)
~PHG4InttSteppingAction () override
bool UserSteppingAction (const G4Step *, bool) override
stepping action. This defines processing of a single step in a given volume
void SetInterfacePointers (PHCompositeNode *) override
void SetHitNodeName (const std::string &type, const std::string &name) override
Set the G4HIT node names from Subsystem rather than constructing your own.
Public Member Functions inherited from PHG4SteppingAction
PHG4SteppingAction (const std::string &name, const int i=0)
virtual ~PHG4SteppingAction ()
virtual void Verbosity (const int i)
virtual int Verbosity () const
virtual int Init ()
virtual int InitWithNode (PHCompositeNode *)
virtual double GetScintLightYield (const G4Step *step)
get scintillation photon count. It require a custom set SCINTILLATIONYIELD property to work
virtual double GetVisibleEnergyDeposition (const G4Step *step)
get amount of energy that can make scintillation light, in Unit of GeV.
virtual void StoreLocalCoordinate (PHG4Hit *hit, const G4Step *step, const bool do_prepoint, const bool do_postpoint)
Extract local coordinate of the hit and save to PHG4Hit.
virtual void Print (const std::string &) const
std::string GetName () const
void SetName (const std::string &name)
virtual void SetLightCorrection (const double inner_radius, const double inner_corr, const double outer_radius, const double outer_corr)
virtual double GetLightCorrection (const double r) const
virtual double GetLightCorrection (const double xpos, const double ypos) const
virtual bool ValidCorrection () const
Private Attributes
PHG4InttDetector * m_Detector = nullptr
pointer to the detector
PHG4HitContainer * m_HitContainer = nullptr
pointer to hit container
PHG4HitContainer * m_AbsorberHitContainer = nullptr
PHG4Hit * m_Hit = nullptr
PHG4HitContainer * m_SaveHitContainer = nullptr
PHG4Shower * m_SaveShower = nullptr
const PHParametersContainer * m_ParamsContainer = nullptr
std::map< int, int > m_InttToTrackerLayerMap
std::map< int, int > m_LadderTypeMap
std::map< int, double > m_StripYMap
std::map< int, std::pair
< double, double > > m_StripZMap
std::map< int, int > m_nStripsPhiCell
std::map< int, std::pair< int,
int > > m_nStripsZSensor
std::map< int, int > m_IsActiveMap
std::map< int, int > m_IsBlackHoleMap
std::string m_AbsorberNodeName
std::string m_HitNodeName
Detailed Description
Definition at line 21 of file PHG4InttSteppingAction.h.
View newest version in sPHENIX GitHub at line 21 of file PHG4InttSteppingAction.h
Constructor & Destructor Documentation
PHG4InttSteppingAction::PHG4InttSteppingAction (PHG4InttDetector * detector, const PHParametersContainer * parameters, const std::pair< std::vector< std::pair< int, int >>::const_iterator, std::vector< std::pair< int, int >>::const_iterator > & layer_begin_end)
Definition at line 44 of file PHG4InttSteppingAction.cc.
View newest version in sPHENIX GitHub at line 44 of file PHG4InttSteppingAction.cc
References parse_cmake_options::begin, Acts::UnitConstants::cm, PHParameters::get_double_param(), PHParameters::get_int_param(), PHParametersContainer::GetParameters(), layer, m_InttToTrackerLayerMap, m_IsActiveMap, m_IsBlackHoleMap, m_LadderTypeMap, m_nStripsPhiCell, m_nStripsZSensor, m_ParamsContainer, PHG4InttDefs::m_SensorSegmentationSet, m_StripYMap, and m_StripZMap.
PHG4InttSteppingAction::~PHG4InttSteppingAction () override
Definition at line 71 of file PHG4InttSteppingAction.cc.
View newest version in sPHENIX GitHub at line 71 of file PHG4InttSteppingAction.cc
References m_Hit.
Member Function Documentation
void PHG4InttSteppingAction::SetHitNodeName (const std::string & , const std::string &) override virtual
Set the G4HIT node names from Subsystem rather than constructing your own.
Reimplemented from PHG4SteppingAction.
Definition at line 375 of file PHG4InttSteppingAction.cc.
View newest version in sPHENIX GitHub at line 375 of file PHG4InttSteppingAction.cc
References m_AbsorberNodeName, m_HitNodeName, and perf_headwind::name.
void PHG4InttSteppingAction::SetInterfacePointers (PHCompositeNode * topNode) override virtual
Reimplemented from PHG4SteppingAction.
Definition at line 357 of file PHG4InttSteppingAction.cc.
View newest version in sPHENIX GitHub at line 357 of file PHG4InttSteppingAction.cc
References m_AbsorberHitContainer, m_AbsorberNodeName, m_HitContainer, m_HitNodeName, and PHG4SteppingAction::Verbosity().
bool PHG4InttSteppingAction::UserSteppingAction (const G4Step * step, bool was_used) override virtual
stepping action. This defines processing of a single step in a given volume
returns true if hits associated to this step was processed by this detector
Parameters
step pointer to the geant 4 step class
was_used,: true if the hit was already used by a previously registered subsystem
Implements PHG4SteppingAction.
Definition at line 81 of file PHG4InttSteppingAction.cc.
View newest version in sPHENIX GitHub at line 81 of file PHG4InttSteppingAction.cc
References PHG4Shower::add_g4hit_id(), PHG4HitContainer::AddHit(), assert, Acts::UnitConstants::cm, PHG4InttDetector::get_ActiveVolumeTuple(), PHG4Hit::get_edep(), PHG4Hit::get_eion(), PHG4Hit::get_hit_id(), PHG4InttDetector::get_PassiveVolumeTuple(), PHG4HitContainer::GetID(), Acts::UnitConstants::GeV, PHG4InttDetector::IsInIntt(), m_AbsorberHitContainer, m_Detector, m_Hit, m_HitContainer, m_InttToTrackerLayerMap, m_IsActiveMap, m_IsBlackHoleMap, m_SaveHitContainer, m_SaveShower, merge_hashes::p, PHG4Hit::print(), PHG4Hit::Reset(), PHG4Hit::set_edep(), PHG4Hit::set_eion(), PHG4Hit::set_ladder_phi_index(), PHG4Hit::set_ladder_z_index(), PHG4Hit::set_layer(), PHG4Hit::set_px(), PHG4Hit::set_py(), PHG4Hit::set_pz(), PHG4Hit::set_shower_id(), PHG4Hit::set_t(), PHG4Hit::set_trkid(), PHG4Hit::set_x(), PHG4Hit::set_y(), PHG4Hit::set_z(), PHG4SteppingAction::StoreLocalCoordinate(), and PHG4SteppingAction::Verbosity().
Member Data Documentation
PHG4HitContainer* PHG4InttSteppingAction::m_AbsorberHitContainer = nullptr private
Definition at line 40 of file PHG4InttSteppingAction.h.
View newest version in sPHENIX GitHub at line 40 of file PHG4InttSteppingAction.h
Referenced by SetInterfacePointers(), and UserSteppingAction().
std::string PHG4InttSteppingAction::m_AbsorberNodeName private
Definition at line 55 of file PHG4InttSteppingAction.h.
View newest version in sPHENIX GitHub at line 55 of file PHG4InttSteppingAction.h
Referenced by SetHitNodeName(), and SetInterfacePointers().
PHG4InttDetector* PHG4InttSteppingAction::m_Detector = nullptr private
pointer to the detector
Definition at line 36 of file PHG4InttSteppingAction.h.
View newest version in sPHENIX GitHub at line 36 of file PHG4InttSteppingAction.h
Referenced by UserSteppingAction().
PHG4Hit* PHG4InttSteppingAction::m_Hit = nullptr private
Definition at line 41 of file PHG4InttSteppingAction.h.
View newest version in sPHENIX GitHub at line 41 of file PHG4InttSteppingAction.h
Referenced by UserSteppingAction(), and ~PHG4InttSteppingAction().
PHG4HitContainer* PHG4InttSteppingAction::m_HitContainer = nullptr private
pointer to hit container
Definition at line 39 of file PHG4InttSteppingAction.h.
View newest version in sPHENIX GitHub at line 39 of file PHG4InttSteppingAction.h
Referenced by SetInterfacePointers(), and UserSteppingAction().
std::string PHG4InttSteppingAction::m_HitNodeName private
Definition at line 56 of file PHG4InttSteppingAction.h.
View newest version in sPHENIX GitHub at line 56 of file PHG4InttSteppingAction.h
Referenced by SetHitNodeName(), and SetInterfacePointers().
std::map<int, int> PHG4InttSteppingAction::m_InttToTrackerLayerMap private
Definition at line 46 of file PHG4InttSteppingAction.h.
View newest version in sPHENIX GitHub at line 46 of file PHG4InttSteppingAction.h
Referenced by PHG4InttSteppingAction(), and UserSteppingAction().
std::map<int, int> PHG4InttSteppingAction::m_IsActiveMap private
Definition at line 53 of file PHG4InttSteppingAction.h.
View newest version in sPHENIX GitHub at line 53 of file PHG4InttSteppingAction.h
Referenced by PHG4InttSteppingAction(), and UserSteppingAction().
std::map<int, int> PHG4InttSteppingAction::m_IsBlackHoleMap private
Definition at line 54 of file PHG4InttSteppingAction.h.
View newest version in sPHENIX GitHub at line 54 of file PHG4InttSteppingAction.h
Referenced by PHG4InttSteppingAction(), and UserSteppingAction().
std::map<int, int> PHG4InttSteppingAction::m_LadderTypeMap private
Definition at line 47 of file PHG4InttSteppingAction.h.
View newest version in sPHENIX GitHub at line 47 of file PHG4InttSteppingAction.h
Referenced by PHG4InttSteppingAction().
std::map<int, int> PHG4InttSteppingAction::m_nStripsPhiCell private
Definition at line 50 of file PHG4InttSteppingAction.h.
View newest version in sPHENIX GitHub at line 50 of file PHG4InttSteppingAction.h
Referenced by PHG4InttSteppingAction().
std::map<int, std::pair<int, int> > PHG4InttSteppingAction::m_nStripsZSensor private
Definition at line 51 of file PHG4InttSteppingAction.h.
View newest version in sPHENIX GitHub at line 51 of file PHG4InttSteppingAction.h
Referenced by PHG4InttSteppingAction().
const PHParametersContainer* PHG4InttSteppingAction::m_ParamsContainer = nullptr private
Definition at line 44 of file PHG4InttSteppingAction.h.
View newest version in sPHENIX GitHub at line 44 of file PHG4InttSteppingAction.h
Referenced by PHG4InttSteppingAction().
PHG4HitContainer* PHG4InttSteppingAction::m_SaveHitContainer = nullptr private
Definition at line 42 of file PHG4InttSteppingAction.h.
View newest version in sPHENIX GitHub at line 42 of file PHG4InttSteppingAction.h
Referenced by UserSteppingAction().
PHG4Shower* PHG4InttSteppingAction::m_SaveShower = nullptr private
Definition at line 43 of file PHG4InttSteppingAction.h.
View newest version in sPHENIX GitHub at line 43 of file PHG4InttSteppingAction.h
Referenced by UserSteppingAction().
std::map<int, double> PHG4InttSteppingAction::m_StripYMap private
Definition at line 48 of file PHG4InttSteppingAction.h.
View newest version in sPHENIX GitHub at line 48 of file PHG4InttSteppingAction.h
Referenced by PHG4InttSteppingAction().
std::map<int, std::pair<double, double> > PHG4InttSteppingAction::m_StripZMap private
Definition at line 49 of file PHG4InttSteppingAction.h.
View newest version in sPHENIX GitHub at line 49 of file PHG4InttSteppingAction.h
Referenced by PHG4InttSteppingAction().
The documentation for this class was generated from the following files:
coresoftware/blob/master/simulation/g4simulation/g4intt/PHG4InttSteppingAction.h
coresoftware/blob/master/simulation/g4simulation/g4intt/PHG4InttSteppingAction.cc