Analysis Software: Acts::Geant4DetectorSurfaceFactory Class Reference
Acts::Geant4DetectorSurfaceFactory Class Reference
#include <acts/blob/sPHENIX/Plugins/Geant4/include/Acts/Plugins/Geant4/Geant4DetectorSurfaceFactory.hpp>
Classes
struct Cache
Nested cache that records the conversion status.
struct Config
struct Options
Nested option struct that allows per call changeable configuration.
Public Types
using Geant4SensitiveSurface = std::tuple< std::shared_ptr< Geant4DetectorElement >, std::shared_ptr< Surface >>
using Geant4PassiveSurface = std::shared_ptr< Surface >
Public Member Functions
Geant4DetectorSurfaceFactory ()=default
void construct (Cache &cache, const G4Transform3D &g4ToGlobal, const G4VPhysicalVolume &g4PhysVol, const Options &option)
Detailed Description
A factory to convert Geant4 physical volumes into Geant4 detector elements
Definition at line 34 of file Geant4DetectorSurfaceFactory.hpp.
View newest version in sPHENIX GitHub at line 34 of file Geant4DetectorSurfaceFactory.hpp
Member Typedef Documentation
using Acts::Geant4DetectorSurfaceFactory::Geant4PassiveSurface = std::shared_ptr<Surface>
Definition at line 46 of file Geant4DetectorSurfaceFactory.hpp.
View newest version in sPHENIX GitHub at line 46 of file Geant4DetectorSurfaceFactory.hpp
using Acts::Geant4DetectorSurfaceFactory::Geant4SensitiveSurface = std::tuple<std::shared_ptr<Geant4DetectorElement>, std::shared_ptr<Surface>>
Definition at line 43 of file Geant4DetectorSurfaceFactory.hpp.
View newest version in sPHENIX GitHub at line 43 of file Geant4DetectorSurfaceFactory.hpp
Constructor & Destructor Documentation
Acts::Geant4DetectorSurfaceFactory::Geant4DetectorSurfaceFactory () default
The Geant4 detector element factory
Parameters
cfg the configuration struct
Member Function Documentation
void Acts::Geant4DetectorSurfaceFactory::construct (Cache & cache, const G4Transform3D & g4ToGlobal, const G4VPhysicalVolume & g4PhysVol, const Options & option)
Construction method of the detector elements
Parameters
cache [in,out] into which the Elements are filled
g4ToGlobal the transformation to global
g4PhyVol the current physical volume
options the factory creation option
Definition at line 21 of file Geant4DetectorSurfaceFactory.cpp.
View newest version in sPHENIX GitHub at line 21 of file Geant4DetectorSurfaceFactory.cpp
References Acts::Geant4DetectorSurfaceFactory::Cache::convertedMaterials, Acts::Geant4DetectorSurfaceFactory::Options::convertedMaterialThickness, Acts::Geant4DetectorSurfaceFactory::Cache::convertedSurfaces, Acts::Geant4DetectorSurfaceFactory::Options::convertMaterial, Acts::Geant4DetectorSurfaceFactory::Cache::matchedG4Volumes, testing::internal::move(), Acts::passive, Acts::Geant4DetectorSurfaceFactory::Cache::passiveSurfaces, Acts::Geant4DetectorSurfaceFactory::Options::passiveSurfaceSelector, Acts::Geant4DetectorSurfaceFactory::Cache::sensitiveSurfaces, Acts::Geant4DetectorSurfaceFactory::Options::sensitiveSurfaceSelector, writeMapConfig::surface, Acts::Geant4PhysicalVolumeConverter::surface(), and Acts::Geant4AlgebraConverter::transform().
Referenced by BOOST_AUTO_TEST_CASE(), ActsExamples::Geant4::Geant4Detector::convertGeant4Volumes(), and PYBIND11_MODULE().
The documentation for this class was generated from the following files:
acts/blob/sPHENIX/Plugins/Geant4/include/Acts/Plugins/Geant4/Geant4DetectorSurfaceFactory.hpp
acts/blob/sPHENIX/Plugins/Geant4/src/Geant4DetectorSurfaceFactory.cpp