Analysis Software: TrigInDetTriplet< space_point_t > Class Template Reference
TrigInDetTriplet< space_point_t > Class Template Reference
#include <acts/blob/sPHENIX/Core/include/Acts/Seeding/TrigBase.hpp>
Public Member Functions
TrigInDetTriplet ()=delete
TrigInDetTriplet (Acts::FTF_SP< space_point_t > s1, Acts::FTF_SP< space_point_t > s2, Acts::FTF_SP< space_point_t > s3, float Q)
TrigInDetTriplet (TrigInDetTriplet *t)
const Acts::FTF_SP
< space_point_t > & s1 () const
const Acts::FTF_SP
< space_point_t > & s2 () const
const Acts::FTF_SP
< space_point_t > & s3 () const
float Q () const
void Q (double newQ)
Protected Attributes
Acts::FTF_SP< space_point_t > m_s1
Acts::FTF_SP< space_point_t > m_s2
Acts::FTF_SP< space_point_t > m_s3
float m_Q
Detailed Description
template<typename space_point_t>
class TrigInDetTriplet< space_point_t >
Definition at line 22 of file TrigBase.hpp.
View newest version in sPHENIX GitHub at line 22 of file TrigBase.hpp
Constructor & Destructor Documentation
template<typename space_point_t> TrigInDetTriplet< space_point_t >::TrigInDetTriplet () delete
template<typename space_point_t> TrigInDetTriplet< space_point_t >::TrigInDetTriplet (Acts::FTF_SP< space_point_t > s1, Acts::FTF_SP< space_point_t > s2, Acts::FTF_SP< space_point_t > s3, float Q) inline
Definition at line 26 of file TrigBase.hpp.
View newest version in sPHENIX GitHub at line 26 of file TrigBase.hpp
template<typename space_point_t> TrigInDetTriplet< space_point_t >::TrigInDetTriplet (TrigInDetTriplet< space_point_t > * t) inline
Definition at line 31 of file TrigBase.hpp.
View newest version in sPHENIX GitHub at line 31 of file TrigBase.hpp
Member Function Documentation
template<typename space_point_t> float TrigInDetTriplet< space_point_t >::Q () const inline
Definition at line 37 of file TrigBase.hpp.
View newest version in sPHENIX GitHub at line 37 of file TrigBase.hpp
template<typename space_point_t> void TrigInDetTriplet< space_point_t >::Q (double newQ) inline
Definition at line 38 of file TrigBase.hpp.
View newest version in sPHENIX GitHub at line 38 of file TrigBase.hpp
template<typename space_point_t> const Acts::FTF_SP<space_point_t>& TrigInDetTriplet< space_point_t >::s1 () const inline
Definition at line 34 of file TrigBase.hpp.
View newest version in sPHENIX GitHub at line 34 of file TrigBase.hpp
Referenced by airy1(), airy1d(), airy2(), airy2d(), aiz(), biz(), expai(), expaid(), pyeig4(), pymaxi(), pyrand(), and pytecm().
template<typename space_point_t> const Acts::FTF_SP<space_point_t>& TrigInDetTriplet< space_point_t >::s2 () const inline
Definition at line 35 of file TrigBase.hpp.
View newest version in sPHENIX GitHub at line 35 of file TrigBase.hpp
Referenced by airy1(), airy1d(), airy2(), airy2d(), pyeig4(), pygrvd(), pygrvl(), pygrvm(), pygvmd(), pymaxi(), pyrand(), and pytecm().
template<typename space_point_t> const Acts::FTF_SP<space_point_t>& TrigInDetTriplet< space_point_t >::s3 () const inline
Definition at line 36 of file TrigBase.hpp.
View newest version in sPHENIX GitHub at line 36 of file TrigBase.hpp
Referenced by airy1(), airy1d(), airy2(), airy2d(), aiz(), expai(), expaid(), pygrvd(), pygrvl(), pygrvm(), and pygvmd().
Member Data Documentation
template<typename space_point_t> float TrigInDetTriplet< space_point_t >::m_Q protected
Definition at line 44 of file TrigBase.hpp.
View newest version in sPHENIX GitHub at line 44 of file TrigBase.hpp
Referenced by TrigInDetTriplet< external_spacepoint_t >::Q().
template<typename space_point_t> Acts::FTF_SP<space_point_t> TrigInDetTriplet< space_point_t >::m_s1 protected
Definition at line 41 of file TrigBase.hpp.
View newest version in sPHENIX GitHub at line 41 of file TrigBase.hpp
Referenced by TrigInDetTriplet< external_spacepoint_t >::s1().
template<typename space_point_t> Acts::FTF_SP<space_point_t> TrigInDetTriplet< space_point_t >::m_s2 protected
Definition at line 42 of file TrigBase.hpp.
View newest version in sPHENIX GitHub at line 42 of file TrigBase.hpp
Referenced by TrigInDetTriplet< external_spacepoint_t >::s2().
template<typename space_point_t> Acts::FTF_SP<space_point_t> TrigInDetTriplet< space_point_t >::m_s3 protected
Definition at line 43 of file TrigBase.hpp.
View newest version in sPHENIX GitHub at line 43 of file TrigBase.hpp
Referenced by TrigInDetTriplet< external_spacepoint_t >::s3().
The documentation for this class was generated from the following file:
acts/blob/sPHENIX/Core/include/Acts/Seeding/TrigBase.hpp