Analysis Software: PHPy8GenTrigger Class Reference
PHPy8GenTrigger Class Reference
#include <coresoftware/blob/master/generators/PHPythia8/PHPy8GenTrigger.h>
Public Member Functions
virtual ~PHPy8GenTrigger ()
virtual bool Apply (Pythia8::Pythia *)
virtual std::string GetName ()
std::vector< int > convertToInts (std::string s)
int Verbosity () const
void Verbosity (int v)
Protected Member Functions
PHPy8GenTrigger (const std::string &name="PHPy8GenTrigger")
constructor
Private Attributes
int m_Verbosity
std::string m_Name
Detailed Description
Definition at line 13 of file PHPy8GenTrigger.h.
View newest version in sPHENIX GitHub at line 13 of file PHPy8GenTrigger.h
Constructor & Destructor Documentation
PHPy8GenTrigger::PHPy8GenTrigger (const std::string & name = "PHPy8GenTrigger") protected
constructor
Definition at line 8 of file PHPy8GenTrigger.cc.
View newest version in sPHENIX GitHub at line 8 of file PHPy8GenTrigger.cc
virtual PHPy8GenTrigger::~PHPy8GenTrigger () inline virtual
Definition at line 20 of file PHPy8GenTrigger.h.
View newest version in sPHENIX GitHub at line 20 of file PHPy8GenTrigger.h
Member Function Documentation
virtual bool PHPy8GenTrigger::Apply (Pythia8::Pythia *) inline virtual
Reimplemented in PHPy8ParticleTrigger, and PHPy8JetTrigger.
Definition at line 22 of file PHPy8GenTrigger.h.
View newest version in sPHENIX GitHub at line 22 of file PHPy8GenTrigger.h
std::vector< int > PHPy8GenTrigger::convertToInts (std::string s)
Definition at line 15 of file PHPy8GenTrigger.cc.
View newest version in sPHENIX GitHub at line 15 of file PHPy8GenTrigger.cc
References i.
Referenced by PHPy8ParticleTrigger::AddParents(), and PHPy8ParticleTrigger::AddParticles().
virtual std::string PHPy8GenTrigger::GetName () inline virtual
Definition at line 28 of file PHPy8GenTrigger.h.
View newest version in sPHENIX GitHub at line 28 of file PHPy8GenTrigger.h
References m_Name.
Referenced by cpp.ast.AstBuilder::_GetBases(), cpp.ast.AstBuilder::_GetClass(), cpp.ast.AstBuilder::_GetReturnTypeAndClassName(), cpp.ast.AstBuilder::_GetTemplatedTypes(), cpp.ast.AstBuilder::handle_namespace(), cpp.ast.AstBuilder::handle_struct(), and PHPythia8::register_trigger().
int PHPy8GenTrigger::Verbosity () const inline
Definition at line 31 of file PHPy8GenTrigger.h.
View newest version in sPHENIX GitHub at line 31 of file PHPy8GenTrigger.h
References m_Verbosity.
Referenced by PHPy8JetTrigger::Apply(), PHPy8ParticleTrigger::Apply(), Fun4AllPythia(), PHPy8JetTrigger::~PHPy8JetTrigger(), and PHPy8ParticleTrigger::~PHPy8ParticleTrigger().
void PHPy8GenTrigger::Verbosity (int v) inline
Definition at line 32 of file PHPy8GenTrigger.h.
View newest version in sPHENIX GitHub at line 32 of file PHPy8GenTrigger.h
References m_Verbosity, and testSigmaEff::v.
Member Data Documentation
std::string PHPy8GenTrigger::m_Name private
Definition at line 36 of file PHPy8GenTrigger.h.
View newest version in sPHENIX GitHub at line 36 of file PHPy8GenTrigger.h
Referenced by GetName().
int PHPy8GenTrigger::m_Verbosity private
Definition at line 35 of file PHPy8GenTrigger.h.
View newest version in sPHENIX GitHub at line 35 of file PHPy8GenTrigger.h
Referenced by Verbosity().
The documentation for this class was generated from the following files:
coresoftware/blob/master/generators/PHPythia8/PHPy8GenTrigger.h
coresoftware/blob/master/generators/PHPythia8/PHPy8GenTrigger.cc