Analysis Software: PHFlag Class Reference
PHFlag Class Reference
#include <coresoftware/blob/master/offline/framework/phool/PHFlag.h>
Public Member Functions
PHFlag ()
virtual ~PHFlag ()
virtual double get_DoubleFlag (const std::string &name) const
virtual double get_DoubleFlag (const std::string &name, const double defaultval)
virtual void set_DoubleFlag (const std::string &name, const double flag)
virtual float get_FloatFlag (const std::string &name) const
virtual float get_FloatFlag (const std::string &name, const float defaultval)
virtual void set_FloatFlag (const std::string &name, const float flag)
virtual int get_IntFlag (const std::string &name) const
virtual int get_IntFlag (const std::string &name, const int defaultval)
virtual void set_IntFlag (const std::string &name, const int flag)
virtual uint64_t get_uint64Flag (const std::string &name) const
virtual uint64_t get_uint64Flag (const std::string &name, const uint64_t defaultval)
virtual void set_uint64Flag (const std::string &name, const uint64_t flag)
virtual const std::string get_StringFlag (const std::string &name) const
virtual const std::string get_StringFlag (const std::string &name, const std::string &defaultval)
virtual void set_StringFlag (const std::string &name, const std::string &flag)
virtual void Print () const
virtual void PrintDoubleFlags () const
virtual void PrintIntFlags () const
virtual void Printuint64Flags () const
virtual void PrintFloatFlags () const
virtual void PrintStringFlags () const
virtual void ReadFromFile (const std::string &name)
virtual void WriteToFile (const std::string &name)
virtual int FlagExist (const std::string &name) const
virtual const std::map
< std::string, uint64_t > * uint64Map () const
virtual const std::map
< std::string, int > * IntMap () const
virtual const std::map
< std::string, float > * FloatMap () const
virtual const std::map
< std::string, double > * DoubleMap () const
virtual const std::map
< std::string, std::string > * StringMap () const
virtual void PrintStackTrace () const
virtual void ClearFlag (const std::string &name)
virtual void ClearAll ()
Protected Attributes
std::map< std::string, uint64_t > m_UInt64FlagMap
std::map< std::string, int > m_IntFlagMap
std::map< std::string, double > m_DoubleFlagMap
std::map< std::string, float > m_FloatFlagMap
std::map< std::string,
std::string > m_StringFlagMap
Detailed Description
Definition at line 19 of file PHFlag.h.
View newest version in sPHENIX GitHub at line 19 of file PHFlag.h
Constructor & Destructor Documentation
PHFlag::PHFlag () inline
Definition at line 22 of file PHFlag.h.
View newest version in sPHENIX GitHub at line 22 of file PHFlag.h
virtual PHFlag::~PHFlag () inline virtual
Definition at line 23 of file PHFlag.h.
View newest version in sPHENIX GitHub at line 23 of file PHFlag.h
Member Function Documentation
void PHFlag::ClearAll () virtual
Definition at line 441 of file PHFlag.cc.
View newest version in sPHENIX GitHub at line 441 of file PHFlag.cc
References m_DoubleFlagMap, m_FloatFlagMap, m_IntFlagMap, m_StringFlagMap, and m_UInt64FlagMap.
void PHFlag::ClearFlag (const std::string & name) virtual
Definition at line 412 of file PHFlag.cc.
View newest version in sPHENIX GitHub at line 412 of file PHFlag.cc
References m_DoubleFlagMap, m_FloatFlagMap, m_IntFlagMap, m_StringFlagMap, and m_UInt64FlagMap.
virtual const std::map<std::string, double>* PHFlag::DoubleMap () const inline virtual
Definition at line 59 of file PHFlag.h.
View newest version in sPHENIX GitHub at line 59 of file PHFlag.h
References m_DoubleFlagMap.
Referenced by FlagSavev1::FillDoubleFromPHFlag().
int PHFlag::FlagExist (const std::string & name) const virtual
Definition at line 261 of file PHFlag.cc.
View newest version in sPHENIX GitHub at line 261 of file PHFlag.cc
References m_DoubleFlagMap, m_FloatFlagMap, m_IntFlagMap, m_StringFlagMap, and m_UInt64FlagMap.
Referenced by MbdCalib::Download_All(), Fun4AllHistoManager::dumpHistos(), DSTEmulator::evaluate_tracks(), Fun4AllOscarInputManager::fileopen(), Fun4AllHepMCInputManager::fileopen(), ReadCalib::getCalibrationFile(), CDBInterface::getUrl(), PHGeomUtility::GetVerbosity(), Fun4AllPrdfOutputManager::InitPrdfManager(), PHRandomSeed::InitSeed(), InsertCalib::insertcalib(), MbdCalib::MbdCalib(), MbdEvent::MbdEvent(), Fun4AllDstOutputManager::outfile_open_first_write(), SvtxEvaluator::process_event(), TrkrNtuplizer::process_event(), Fun4AllServer::run(), and Fun4AllServer::setRun().
virtual const std::map<std::string, float>* PHFlag::FloatMap () const inline virtual
Definition at line 58 of file PHFlag.h.
View newest version in sPHENIX GitHub at line 58 of file PHFlag.h
References m_FloatFlagMap.
Referenced by FlagSavev1::FillFloatFromPHFlag().
double PHFlag::get_DoubleFlag (const std::string & name) const virtual
Definition at line 50 of file PHFlag.cc.
View newest version in sPHENIX GitHub at line 50 of file PHFlag.cc
References m_DoubleFlagMap, Print(), and PrintStackTrace().
Referenced by get_DoubleFlag(), and FlagSavev1::PutDoubleToPHFlag().
double PHFlag::get_DoubleFlag (const std::string & name, const double defaultval) virtual
Definition at line 64 of file PHFlag.cc.
View newest version in sPHENIX GitHub at line 64 of file PHFlag.cc
References get_DoubleFlag(), m_DoubleFlagMap, and set_DoubleFlag().
float PHFlag::get_FloatFlag (const std::string & name) const virtual
Definition at line 84 of file PHFlag.cc.
View newest version in sPHENIX GitHub at line 84 of file PHFlag.cc
References m_FloatFlagMap, Print(), and PrintStackTrace().
Referenced by get_FloatFlag(), HepMCNodeReader::process_event(), and FlagSavev1::PutFloatToPHFlag().
float PHFlag::get_FloatFlag (const std::string & name, const float defaultval) virtual
Definition at line 98 of file PHFlag.cc.
View newest version in sPHENIX GitHub at line 98 of file PHFlag.cc
References get_FloatFlag(), m_FloatFlagMap, and set_FloatFlag().
int PHFlag::get_IntFlag (const std::string & name) const virtual
Definition at line 118 of file PHFlag.cc.
View newest version in sPHENIX GitHub at line 118 of file PHFlag.cc
References m_IntFlagMap, Print(), and PrintStackTrace().
Referenced by Fun4AllHistoManager::dumpHistos(), Fun4AllServer::End(), DSTEmulator::evaluate_tracks(), Fun4AllOscarInputManager::fileopen(), Fun4AllHepMCInputManager::fileopen(), get_IntFlag(), PHGeomUtility::GetVerbosity(), Fun4AllPrdfOutputManager::InitPrdfManager(), HeadReco::InitRun(), MbdEvent::InitRun(), MvtxAlign::InitRun(), MvtxPrototype2Align::InitRun(), BbcCheck::InitRun(), PHRandomSeed::InitSeed(), MbdCalib::MbdCalib(), MbdEvent::MbdEvent(), Fun4AllDstOutputManager::outfile_open_first_write(), SvtxEvaluator::process_event(), TrkrNtuplizer::process_event(), FlagSavev1::PutIntToPHFlag(), Fun4AllServer::run(), and Fun4AllDummyInputManager::setSyncManager().
int PHFlag::get_IntFlag (const std::string & name, const int defaultval) virtual
Definition at line 132 of file PHFlag.cc.
View newest version in sPHENIX GitHub at line 132 of file PHFlag.cc
References get_IntFlag(), m_IntFlagMap, and set_IntFlag().
const std::string PHFlag::get_StringFlag (const std::string & name) const virtual
Definition at line 15 of file PHFlag.cc.
View newest version in sPHENIX GitHub at line 15 of file PHFlag.cc
References m_StringFlagMap, Print(), and PrintStackTrace().
Referenced by TPCPedestalCalibration::CDBInsert(), PHG4FullProjTiltedSpacalDetector::Construct_AzimuthalSeg(), PHG4FullProjSpacalDetector::Construct_AzimuthalSeg(), PHG4InttDetector::ConstructIntt(), PHG4CEmcTestBeamDetector::ConstructMe(), PHG4BbcDetector::ConstructMe(), PHG4ZDCDetector::ConstructMe(), PHG4IHCalDetector::ConstructMe(), PHG4OHCalDetector::ConstructMe(), PHG4InnerHcalDetector::ConstructMe(), PHG4OuterHcalDetector::ConstructMe(), PHG4BbcDetector::ConstructSupport(), PHG4CEmcTestBeamDetector::ConstructTowerVolume(), MbdCalib::Download_All(), get_StringFlag(), ReadCalib::getCalibrationFile(), CDBInterface::getUrl(), PHG4CylinderSubsystem::InitRunSubsystem(), InsertCalib::insertcalib(), HepMCNodeReader::process_event(), FlagSavev1::PutStringToPHFlag(), and TestCDBInsert().
const std::string PHFlag::get_StringFlag (const std::string & name, const std::string & defaultval) virtual
Definition at line 30 of file PHFlag.cc.
View newest version in sPHENIX GitHub at line 30 of file PHFlag.cc
References get_StringFlag(), m_StringFlagMap, and set_StringFlag().
uint64_t PHFlag::get_uint64Flag (const std::string & name) const virtual
Definition at line 152 of file PHFlag.cc.
View newest version in sPHENIX GitHub at line 152 of file PHFlag.cc
References m_UInt64FlagMap, Print(), and PrintStackTrace().
Referenced by MbdCalib::Download_All(), get_uint64Flag(), CDBInterface::getUrl(), LightCollectionModel::load_data_from_CDB(), FlagSavev1::Putuint64ToPHFlag(), and Fun4AllServer::setRun().
uint64_t PHFlag::get_uint64Flag (const std::string & name, const uint64_t defaultval) virtual
Definition at line 166 of file PHFlag.cc.
View newest version in sPHENIX GitHub at line 166 of file PHFlag.cc
References get_uint64Flag(), m_UInt64FlagMap, and set_uint64Flag().
virtual const std::map<std::string, int>* PHFlag::IntMap () const inline virtual
Definition at line 57 of file PHFlag.h.
View newest version in sPHENIX GitHub at line 57 of file PHFlag.h
References m_IntFlagMap.
Referenced by FlagSavev1::FillIntFromPHFlag().
void PHFlag::Print () const virtual
Reimplemented in recoConsts.
Definition at line 186 of file PHFlag.cc.
View newest version in sPHENIX GitHub at line 186 of file PHFlag.cc
References PrintDoubleFlags(), PrintFloatFlags(), PrintIntFlags(), PrintStringFlags(), and Printuint64Flags().
Referenced by get_DoubleFlag(), get_FloatFlag(), get_IntFlag(), get_StringFlag(), and get_uint64Flag().
void PHFlag::PrintDoubleFlags () const virtual
Definition at line 222 of file PHFlag.cc.
View newest version in sPHENIX GitHub at line 222 of file PHFlag.cc
References m_DoubleFlagMap.
Referenced by Print().
void PHFlag::PrintFloatFlags () const virtual
Definition at line 235 of file PHFlag.cc.
View newest version in sPHENIX GitHub at line 235 of file PHFlag.cc
References m_FloatFlagMap.
Referenced by recoConsts::Print(), and Print().
void PHFlag::PrintIntFlags () const virtual
Definition at line 196 of file PHFlag.cc.
View newest version in sPHENIX GitHub at line 196 of file PHFlag.cc
References m_IntFlagMap.
Referenced by recoConsts::Print(), and Print().
void PHFlag::PrintStackTrace () const virtual
Definition at line 404 of file PHFlag.cc.
View newest version in sPHENIX GitHub at line 404 of file PHFlag.cc
Referenced by get_DoubleFlag(), get_FloatFlag(), get_IntFlag(), get_StringFlag(), and get_uint64Flag().
void PHFlag::PrintStringFlags () const virtual
Definition at line 248 of file PHFlag.cc.
View newest version in sPHENIX GitHub at line 248 of file PHFlag.cc
References m_StringFlagMap.
Referenced by recoConsts::Print(), and Print().
void PHFlag::Printuint64Flags () const virtual
Definition at line 209 of file PHFlag.cc.
View newest version in sPHENIX GitHub at line 209 of file PHFlag.cc
References m_UInt64FlagMap.
Referenced by recoConsts::Print(), and Print().
void PHFlag::ReadFromFile (const std::string & name) virtual
Definition at line 291 of file PHFlag.cc.
View newest version in sPHENIX GitHub at line 291 of file PHFlag.cc
References infile, CKF_timing_vs_mu::label, set_DoubleFlag(), set_FloatFlag(), set_IntFlag(), set_StringFlag(), and set_uint64Flag().
void PHFlag::set_DoubleFlag (const std::string & name, const double flag) virtual
Definition at line 78 of file PHFlag.cc.
View newest version in sPHENIX GitHub at line 78 of file PHFlag.cc
References m_DoubleFlagMap, and perf_headwind::name.
Referenced by get_DoubleFlag(), FlagSavev1::PutDoubleToPHFlag(), and ReadFromFile().
void PHFlag::set_FloatFlag (const std::string & name, const float flag) virtual
Definition at line 112 of file PHFlag.cc.
View newest version in sPHENIX GitHub at line 112 of file PHFlag.cc
References m_FloatFlagMap, and perf_headwind::name.
Referenced by Fun4All_EICAnalysis_Leptoquarks(), Fun4All_MCEventGen(), Fun4All_Pythia6(), get_FloatFlag(), PHG4Reco::InitRun(), FlagSavev1::PutFloatToPHFlag(), and ReadFromFile().
void PHFlag::set_IntFlag (const std::string & name, const int flag) virtual
Definition at line 146 of file PHFlag.cc.
View newest version in sPHENIX GitHub at line 146 of file PHFlag.cc
References m_IntFlagMap, and perf_headwind::name.
Referenced by OnCalServer::BeginRun(), Fun4All_AnaTutorial_sPHENIX(), Fun4All_AnaTutorial_sPHENIX_Jets(), Fun4All_BHG(), Fun4All_EMCalLikelihood(), Fun4All_ExportGeom(), Fun4All_G4_Calos(), Fun4All_G4_Example02(), Fun4All_G4_Example03(), Fun4All_G4_sPHENIX(), Fun4All_G4_sPHENIX_ForTrackCutStudy(), Fun4All_G4_sPHENIX_ForTrackCutStudy_EmbedScanOff(), Fun4All_G4_sPHENIX_ForTrackCutStudy_EmbedScanOn(), Fun4All_G4_sPHENIX_ForTrackCutStudy_WithPileup_EmbedScanOff(), Fun4All_G4_sPHENIX_ForTrackCutStudy_WithPileup_EmbedScanOn(), Fun4All_G4_TPC(), Fun4All_HCalJetPhiShift(), Fun4All_RunNewTruthMatcher(), Fun4All_TestBeam(), Fun4All_TestBeam_TPC(), generate_hepmc_bjet(), get_IntFlag(), MakeTree(), PHGeom_DSTInspection(), FlagSavev1::PutIntToPHFlag(), ReadFromFile(), RunBoth(), Fun4AllServer::setRun(), PHGeomUtility::SetVerbosity(), and Wrapper().
void PHFlag::set_StringFlag (const std::string & name, const std::string & flag) virtual
Definition at line 44 of file PHFlag.cc.
View newest version in sPHENIX GitHub at line 44 of file PHFlag.cc
References m_StringFlagMap, and perf_headwind::name.
Referenced by clus_dst_simple_superfastcalib(), PHG4PhenixDetector::Construct(), dst_simple_towerslope_runmacro(), EMCalDeadmap(), Fun4All_AnaTutorial_sPHENIX(), Fun4All_AnaTutorial_sPHENIX_Jets(), Fun4All_BHG(), Fun4All_Calo(), Fun4All_CaloProduction(), Fun4All_CaloProduction_PreQM23(), Fun4All_CentralityValidation(), Fun4All_EMCal(), Fun4All_EMCal_Hist(), Fun4All_EMCal_sp(), Fun4All_G4_Calo(), Fun4All_G4_sPHENIX(), Fun4All_G4_sPHENIX_ForTrackCutStudy(), Fun4All_G4_sPHENIX_ForTrackCutStudy_EmbedScanOff(), Fun4All_G4_sPHENIX_ForTrackCutStudy_EmbedScanOn(), Fun4All_G4_sPHENIX_ForTrackCutStudy_WithPileup_EmbedScanOff(), Fun4All_G4_sPHENIX_ForTrackCutStudy_WithPileup_EmbedScanOn(), Fun4All_G4_sPHENIX_jobC(), Fun4All_GeoExtract(), Fun4All_HCalCalib(), Fun4All_HCalCalib_sim(), Fun4All_HCalJetPhiShift(), Fun4All_JetBkgd_Embed(), Fun4All_Pi0Gen_sPHENIX(), Fun4All_RTrack(), Fun4All_RunNewTruthMatcher(), Fun4All_SinglePhotonGen_sPHENIX(), Fun4All_SinglePi0Gen_sPHENIX(), Fun4All_Templates(), Fun4All_Year1(), get_StringFlag(), PHG4Reco::InitRun(), FlagSavev1::PutStringToPHFlag(), ReadFromFile(), rundata(), TestCDBInsert(), TestCDBRead(), TestCDBSubsysReco(), tsdst_plus_tsfit(), and wholeIter_Pi0EtaByEta().
void PHFlag::set_uint64Flag (const std::string & name, const uint64_t flag) virtual
Definition at line 180 of file PHFlag.cc.
View newest version in sPHENIX GitHub at line 180 of file PHFlag.cc
References m_UInt64FlagMap, and perf_headwind::name.
Referenced by clus_dst_simple_superfastcalib(), dst_simple_towerslope_runmacro(), EMCalDeadmap(), Fun4All_AnaTutorial_sPHENIX(), Fun4All_AnaTutorial_sPHENIX_Jets(), Fun4All_BHG(), Fun4All_Calo(), Fun4All_CaloProduction(), Fun4All_CaloProduction_PreQM23(), Fun4All_CentralityValidation(), Fun4All_EMCal(), Fun4All_EMCal_Hist(), Fun4All_EMCal_sp(), Fun4All_G4_Calo(), Fun4All_G4_sPHENIX(), Fun4All_G4_sPHENIX_ForTrackCutStudy(), Fun4All_G4_sPHENIX_ForTrackCutStudy_EmbedScanOff(), Fun4All_G4_sPHENIX_ForTrackCutStudy_EmbedScanOn(), Fun4All_G4_sPHENIX_ForTrackCutStudy_WithPileup_EmbedScanOff(), Fun4All_G4_sPHENIX_ForTrackCutStudy_WithPileup_EmbedScanOn(), Fun4All_G4_sPHENIX_jobC(), Fun4All_GeoExtract(), Fun4All_HCalCalib(), Fun4All_HCalCalib_sim(), Fun4All_HCalJetPhiShift(), Fun4All_JetBkgd_Embed(), Fun4All_Pi0Gen_sPHENIX(), Fun4All_RTrack(), Fun4All_RunNewTruthMatcher(), Fun4All_SinglePhotonGen_sPHENIX(), Fun4All_SinglePi0Gen_sPHENIX(), Fun4All_Templates(), Fun4All_Year1(), get_uint64Flag(), FlagSavev1::Putuint64ToPHFlag(), ReadFromFile(), rundata(), Fun4AllServer::setRun(), TestCDBRead(), TestCDBSubsysReco(), tsdst_plus_tsfit(), and wholeIter_Pi0EtaByEta().
virtual const std::map<std::string, std::string>* PHFlag::StringMap () const inline virtual
Definition at line 60 of file PHFlag.h.
View newest version in sPHENIX GitHub at line 60 of file PHFlag.h
References m_StringFlagMap.
Referenced by FlagSavev1::FillStringFromPHFlag().
virtual const std::map<std::string, uint64_t>* PHFlag::uint64Map () const inline virtual
Definition at line 56 of file PHFlag.h.
View newest version in sPHENIX GitHub at line 56 of file PHFlag.h
References m_UInt64FlagMap.
Referenced by FlagSavev1::Filluint64FromPHFlag().
void PHFlag::WriteToFile (const std::string & name) virtual
Definition at line 365 of file PHFlag.cc.
View newest version in sPHENIX GitHub at line 365 of file PHFlag.cc
References m_DoubleFlagMap, m_FloatFlagMap, m_IntFlagMap, m_StringFlagMap, and m_UInt64FlagMap.
Member Data Documentation
std::map<std::string, double> PHFlag::m_DoubleFlagMap protected
Definition at line 69 of file PHFlag.h.
View newest version in sPHENIX GitHub at line 69 of file PHFlag.h
Referenced by ClearAll(), ClearFlag(), DoubleMap(), FlagExist(), get_DoubleFlag(), PrintDoubleFlags(), set_DoubleFlag(), and WriteToFile().
std::map<std::string, float> PHFlag::m_FloatFlagMap protected
Definition at line 70 of file PHFlag.h.
View newest version in sPHENIX GitHub at line 70 of file PHFlag.h
Referenced by ClearAll(), ClearFlag(), FlagExist(), FloatMap(), get_FloatFlag(), PrintFloatFlags(), set_FloatFlag(), and WriteToFile().
std::map<std::string, int> PHFlag::m_IntFlagMap protected
Definition at line 68 of file PHFlag.h.
View newest version in sPHENIX GitHub at line 68 of file PHFlag.h
Referenced by ClearAll(), ClearFlag(), FlagExist(), get_IntFlag(), IntMap(), PrintIntFlags(), set_IntFlag(), and WriteToFile().
std::map<std::string, std::string> PHFlag::m_StringFlagMap protected
Definition at line 71 of file PHFlag.h.
View newest version in sPHENIX GitHub at line 71 of file PHFlag.h
Referenced by ClearAll(), ClearFlag(), FlagExist(), get_StringFlag(), PrintStringFlags(), set_StringFlag(), StringMap(), and WriteToFile().
std::map<std::string, uint64_t> PHFlag::m_UInt64FlagMap protected
Definition at line 67 of file PHFlag.h.
View newest version in sPHENIX GitHub at line 67 of file PHFlag.h
Referenced by ClearAll(), ClearFlag(), FlagExist(), get_uint64Flag(), Printuint64Flags(), set_uint64Flag(), uint64Map(), and WriteToFile().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/framework/phool/PHFlag.h
coresoftware/blob/master/offline/framework/phool/PHFlag.cc