Analysis Software: TrkrHitSetContainerv1 Class Reference
TrkrHitSetContainerv1 Class Reference
#include <coresoftware/blob/master/offline/packages/trackbase/TrkrHitSetContainerv1.h>
Public Member Functions
TrkrHitSetContainerv1 ()=default
~TrkrHitSetContainerv1 () override
void Reset () override
PHObject functions.
void identify (std::ostream &=std::cout) const override
ConstIterator addHitSet (TrkrHitSet *) override
Add a TrkrHitSet to the container.
ConstIterator addHitSetSpecifyKey (const TrkrDefs::hitsetkey, TrkrHitSet *) override
void removeHitSet (TrkrDefs::hitsetkey) override
preferred removal method, key is currently the hit id
void removeHitSet (TrkrHitSet *) override
inefficent, use key where possible instead
Iterator findOrAddHitSet (TrkrDefs::hitsetkey key) override
find or add HitSet
ConstRange getHitSets (const TrkrDefs::TrkrId trackerid) const override
return all HitSets matching a given detid
ConstRange getHitSets (const TrkrDefs::TrkrId trackerid, const uint8_t layer) const override
return all HitSets matching a given detid, layer
ConstRange getHitSets () const override
return all HitSets
TrkrHitSet * findHitSet (TrkrDefs::hitsetkey key) override
return a given HitSet based on its key
unsigned int size () const override
Public Member Functions inherited from TrkrHitSetContainer
~TrkrHitSetContainer () override=default
dtir
Public Member Functions inherited from PHObject
PHObject ()
ctor
~PHObject () override
dtor
virtual PHObject * CloneMe () const
Virtual copy constructor.
virtual PHObject * clone () const final
PHObject * Clone (const char *newname="") const final
void Copy (TObject &object) const final
virtual int isValid () const
isValid returns non zero if object contains vailid data
virtual int Integrate () const
virtual int Integrate (PHObject *)
virtual void CopyFrom (const PHObject *obj)
Private Attributes
Map m_hitmap
Additional Inherited Members
Public Types inherited from TrkrHitSetContainer
using Map = std::map< TrkrDefs::hitsetkey, TrkrHitSet * >
using Iterator = Map::iterator
using ConstIterator = Map::const_iterator
using Range = std::pair< Iterator, Iterator >
using ConstRange = std::pair< ConstIterator, ConstIterator >
Protected Member Functions inherited from TrkrHitSetContainer
TrkrHitSetContainer ()=default
ctor
Detailed Description
Container for TrkrHitSet objects
Definition at line 21 of file TrkrHitSetContainerv1.h.
View newest version in sPHENIX GitHub at line 21 of file TrkrHitSetContainerv1.h
Constructor & Destructor Documentation
TrkrHitSetContainerv1::TrkrHitSetContainerv1 () default
TrkrHitSetContainerv1::~TrkrHitSetContainerv1 () inline override
Definition at line 28 of file TrkrHitSetContainerv1.h.
View newest version in sPHENIX GitHub at line 28 of file TrkrHitSetContainerv1.h
References Reset().
Member Function Documentation
TrkrHitSetContainerv1::ConstIterator TrkrHitSetContainerv1::addHitSet (TrkrHitSet *) override virtual
Add a TrkrHitSet to the container.
Reimplemented from TrkrHitSetContainer.
Definition at line 36 of file TrkrHitSetContainerv1.cc.
View newest version in sPHENIX GitHub at line 36 of file TrkrHitSetContainerv1.cc
References addHitSetSpecifyKey(), and TrkrHitSet::getHitSetKey().
TrkrHitSetContainerv1::ConstIterator TrkrHitSetContainerv1::addHitSetSpecifyKey (const TrkrDefs::hitsetkey key, TrkrHitSet * newhit) override virtual
Reimplemented from TrkrHitSetContainer.
Definition at line 40 of file TrkrHitSetContainerv1.cc.
View newest version in sPHENIX GitHub at line 40 of file TrkrHitSetContainerv1.cc
References m_hitmap.
Referenced by addHitSet().
TrkrHitSet * TrkrHitSetContainerv1::findHitSet (TrkrDefs::hitsetkey) override virtual
return a given HitSet based on its key
Reimplemented from TrkrHitSetContainer.
Definition at line 99 of file TrkrHitSetContainerv1.cc.
View newest version in sPHENIX GitHub at line 99 of file TrkrHitSetContainerv1.cc
References it, and m_hitmap.
TrkrHitSetContainerv1::Iterator TrkrHitSetContainerv1::findOrAddHitSet (TrkrDefs::hitsetkey) override virtual
find or add HitSet
Reimplemented from TrkrHitSetContainer.
Definition at line 87 of file TrkrHitSetContainerv1.cc.
View newest version in sPHENIX GitHub at line 87 of file TrkrHitSetContainerv1.cc
References it, and m_hitmap.
TrkrHitSetContainerv1::ConstRange TrkrHitSetContainerv1::getHitSets (const TrkrDefs::TrkrId) const override virtual
return all HitSets matching a given detid
Reimplemented from TrkrHitSetContainer.
Definition at line 67 of file TrkrHitSetContainerv1.cc.
View newest version in sPHENIX GitHub at line 67 of file TrkrHitSetContainerv1.cc
References TrkrDefs::getHitSetKeyHi(), TrkrDefs::getHitSetKeyLo(), and m_hitmap.
Referenced by AnaMvtxTestBeam2019::process_event().
TrkrHitSetContainerv1::ConstRange TrkrHitSetContainerv1::getHitSets (const TrkrDefs::TrkrId trackerid, const uint8_t layer) const override virtual
return all HitSets matching a given detid, layer
Reimplemented from TrkrHitSetContainer.
Definition at line 75 of file TrkrHitSetContainerv1.cc.
View newest version in sPHENIX GitHub at line 75 of file TrkrHitSetContainerv1.cc
References TrkrDefs::getHitSetKeyHi(), TrkrDefs::getHitSetKeyLo(), and m_hitmap.
TrkrHitSetContainerv1::ConstRange TrkrHitSetContainerv1::getHitSets () const override virtual
return all HitSets
Reimplemented from TrkrHitSetContainer.
Definition at line 83 of file TrkrHitSetContainerv1.cc.
View newest version in sPHENIX GitHub at line 83 of file TrkrHitSetContainerv1.cc
References m_hitmap.
void TrkrHitSetContainerv1::identify (std::ostream & os = std::cout) const override virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from PHObject.
Definition at line 22 of file TrkrHitSetContainerv1.cc.
View newest version in sPHENIX GitHub at line 22 of file TrkrHitSetContainerv1.cc
References TrkrDefs::getLayer(), layer, m_hitmap, and size().
void TrkrHitSetContainerv1::removeHitSet (TrkrDefs::hitsetkey) override virtual
preferred removal method, key is currently the hit id
Reimplemented from TrkrHitSetContainer.
Definition at line 52 of file TrkrHitSetContainerv1.cc.
View newest version in sPHENIX GitHub at line 52 of file TrkrHitSetContainerv1.cc
References m_hitmap.
Referenced by removeHitSet().
void TrkrHitSetContainerv1::removeHitSet (TrkrHitSet *) override virtual
inefficent, use key where possible instead
Reimplemented from TrkrHitSetContainer.
Definition at line 63 of file TrkrHitSetContainerv1.cc.
View newest version in sPHENIX GitHub at line 63 of file TrkrHitSetContainerv1.cc
References TrkrHitSet::getHitSetKey(), and removeHitSet().
void TrkrHitSetContainerv1::Reset () override virtual
PHObject functions.
Reimplemented from TrkrHitSetContainer.
Definition at line 14 of file TrkrHitSetContainerv1.cc.
View newest version in sPHENIX GitHub at line 14 of file TrkrHitSetContainerv1.cc
References m_hitmap.
Referenced by ~TrkrHitSetContainerv1().
unsigned int TrkrHitSetContainerv1::size (void) const inline override virtual
Reimplemented from TrkrHitSetContainer.
Definition at line 53 of file TrkrHitSetContainerv1.h.
View newest version in sPHENIX GitHub at line 53 of file TrkrHitSetContainerv1.h
References m_hitmap.
Referenced by identify().
Member Data Documentation
Map TrkrHitSetContainerv1::m_hitmap private
Definition at line 58 of file TrkrHitSetContainerv1.h.
View newest version in sPHENIX GitHub at line 58 of file TrkrHitSetContainerv1.h
Referenced by addHitSetSpecifyKey(), findHitSet(), findOrAddHitSet(), getHitSets(), identify(), removeHitSet(), Reset(), and size().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/trackbase/TrkrHitSetContainerv1.h
coresoftware/blob/master/offline/packages/trackbase/TrkrHitSetContainerv1.cc