Analysis Software: Acts::PlanarBounds Class Reference
Acts::PlanarBounds Class Reference abstract
#include <acts/blob/sPHENIX/Core/include/Acts/Surfaces/PlanarBounds.hpp>
Public Member Functions
virtual std::vector< Vector2 > vertices (unsigned int lseg=1) const =0
virtual const RectangleBounds & boundingBox () const =0
Public Member Functions inherited from Acts::SurfaceBounds
virtual ~SurfaceBounds ()=default
virtual BoundsType type () const =0
virtual std::vector< double > values () const =0
virtual bool inside (const Vector2 &lposition, const BoundaryCheck &bcheck) const =0
virtual std::ostream & toStream (std::ostream &os) const =0
Additional Inherited Members
Public Types inherited from Acts::SurfaceBounds
enum BoundsType : int {
eCone = 0, eCylinder = 1, eDiamond = 2, eDisc = 3,
eEllipse = 4, eLine = 5, eRectangle = 6, eTrapezoid = 7,
eTriangle = 8, eDiscTrapezoid = 9, eConvexPolygon = 10, eAnnulus = 11,
eBoundless = 12, eOther = 13
}
Detailed Description
common base class for all bounds that are in a local x/y cartesian frame
simply introduced to avoid wrong bound assignments to surfaces
Definition at line 25 of file PlanarBounds.hpp.
View newest version in sPHENIX GitHub at line 25 of file PlanarBounds.hpp
Member Function Documentation
virtual const RectangleBounds& Acts::PlanarBounds::boundingBox () const pure virtual
Bounding box parameters
Returns
rectangle bounds for a bounding box
Implemented in Acts::ConvexPolygonBounds< PolygonDynamic >, Acts::TrapezoidBounds, Acts::ConvexPolygonBounds< N >, Acts::DiamondBounds, Acts::EllipseBounds, and Acts::RectangleBounds.
virtual std::vector<Vector2> Acts::PlanarBounds::vertices (unsigned int lseg = 1) const pure virtual
Return the vertices
Parameters
lseg the number of segments used to approximate and eventually curved line
Note
that the extremas are given, which may slightly alter the number of segments returned
Returns
vector for vertices in 2D
Implemented in Acts::ConvexPolygonBounds< PolygonDynamic >, Acts::TrapezoidBounds, Acts::ConvexPolygonBounds< N >, Acts::DiamondBounds, Acts::EllipseBounds, and Acts::RectangleBounds.
Referenced by ActsFatras::PlanarSurfaceMask::apply(), Acts::Svg::SurfaceConverter::convert(), Acts::SurfaceArrayCreator::createVariableAxis(), and Acts::ConvexPolygonBoundsBase::toStream().
The documentation for this class was generated from the following file:
acts/blob/sPHENIX/Core/include/Acts/Surfaces/PlanarBounds.hpp