Analysis Software: TrkrHitSet Class Reference
TrkrHitSet Class Reference
Container for storing TrkrHit's.
#include <coresoftware/blob/master/offline/packages/trackbase/TrkrHitSet.h>
Public Types
using Map = std::map< TrkrDefs::hitkey, TrkrHit * >
using ConstIterator = Map::const_iterator
using ConstRange = std::pair< ConstIterator, ConstIterator >
Public Member Functions
void identify (std::ostream &=std::cout) const override
TObject functions.
void Reset () override
Clear Event.
virtual void setHitSetKey (const TrkrDefs::hitsetkey)
Set the key for this object.
virtual TrkrDefs::hitsetkey getHitSetKey () const
Get the key for this object.
virtual ConstIterator addHitSpecificKey (const TrkrDefs::hitkey, TrkrHit *)
Add a hit to this container using a specific key.
virtual void removeHit (TrkrDefs::hitkey)
Remove a hit using its key.
virtual TrkrHit * getHit (const TrkrDefs::hitkey) const
Get a specific hit based on its index.
virtual ConstRange getHits () const
Get all hits.
virtual unsigned int size () const
Get the number of hits stored.
Public Member Functions inherited from PHObject
PHObject ()
ctor
~PHObject () override
dtor
virtual PHObject * CloneMe () const
Virtual copy constructor.
virtual PHObject * clone () const final
PHObject * Clone (const char *newname="") const final
void Copy (TObject &object) const final
virtual int isValid () const
isValid returns non zero if object contains vailid data
virtual int Integrate () const
virtual int Integrate (PHObject *)
virtual void CopyFrom (const PHObject *obj)
Protected Member Functions
TrkrHitSet ()=default
ctor, not to be called
Private Member Functions
ClassDefOverride (TrkrHitSet, 1)
Detailed Description
Container for storing TrkrHit's.
Container object which stores a set of TrkrHit objects. A single TrkrHitSet is meant to represent a geometric detector object which bounds clustering. Therefore, a TrkrHitSet should contain all TrkrHits which could belong the the same cluster.
Definition at line 29 of file TrkrHitSet.h.
View newest version in sPHENIX GitHub at line 29 of file TrkrHitSet.h
Member Typedef Documentation
using TrkrHitSet::ConstIterator = Map::const_iterator
Definition at line 34 of file TrkrHitSet.h.
View newest version in sPHENIX GitHub at line 34 of file TrkrHitSet.h
using TrkrHitSet::ConstRange = std::pair<ConstIterator, ConstIterator>
Definition at line 35 of file TrkrHitSet.h.
View newest version in sPHENIX GitHub at line 35 of file TrkrHitSet.h
using TrkrHitSet::Map = std::map<TrkrDefs::hitkey, TrkrHit*>
Definition at line 33 of file TrkrHitSet.h.
View newest version in sPHENIX GitHub at line 33 of file TrkrHitSet.h
Constructor & Destructor Documentation
TrkrHitSet::TrkrHitSet () protected default
ctor, not to be called
Member Function Documentation
TrkrHitSet::ConstIterator TrkrHitSet::addHitSpecificKey (const TrkrDefs::hitkey , TrkrHit *) virtual
Add a hit to this container using a specific key.
Parameters
[in] key Hit key
[in] hit Hit to be added.
NOTE: This TrkrHitSet takes ownership of the passed TrkrHit pointer and will delete it in the Reset() method.
Reimplemented in TrkrHitSetv1.
Definition at line 15 of file TrkrHitSet.cc.
View newest version in sPHENIX GitHub at line 15 of file TrkrHitSet.cc
Referenced by PHG4MvtxHitReco::cluster_truthhits(), and MvtxHitPruner::process_event().
TrkrHitSet::ClassDefOverride (TrkrHitSet , 1) private
virtual TrkrHit* TrkrHitSet::getHit (const TrkrDefs::hitkey) const inline virtual
Get a specific hit based on its index.
Parameters
key of the desired hit
[out] Pointer to the desired hit. nullptr if no hit.
Get a desired hit based on its key.
Reimplemented in TrkrHitSetv1.
Definition at line 88 of file TrkrHitSet.h.
View newest version in sPHENIX GitHub at line 88 of file TrkrHitSet.h
Referenced by SvtxHitEval::all_truth_hits(), PHG4MvtxHitReco::cluster_truthhits(), and MvtxHitPruner::process_event().
TrkrHitSet::ConstRange TrkrHitSet::getHits () const virtual
Get all hits.
Parameters
[out] Pair of iterator to vector begin and end
Reimplemented in TrkrHitSetv1.
Definition at line 19 of file TrkrHitSet.cc.
View newest version in sPHENIX GitHub at line 19 of file TrkrHitSet.cc
Referenced by TpcClusterBuilder::cluster_hits(), PHG4InttHitReco::cluster_truthhits(), PHG4MvtxHitReco::cluster_truthhits(), InttClusterizer::ClusterLadderCells(), MvtxPrototype2Clusterizer::ClusterMvtx(), MvtxClusterizer::ClusterMvtx(), PHG4TpcDigitizer::DigitizeCylinderCells(), PHG4InttDigitizer::DigitizeLadderCells(), PHG4MvtxDigitizer::DigitizeMvtxLadderCells(), QAG4SimulationMicromegas::evaluate_hits(), TrackResiduals::fillHitTree(), TrkrNtuplizer::fillOutputNtuples(), SvtxEvaluator::fillOutputNtuples(), TrackerEventDisplay::makeJsonFile(), TpcPrototypeClusterizer::process_event(), PHG4MicromegasDigitizer::process_event(), MicromegasClusterizer::process_event(), PHG4TpcPadBaselineShift::process_event(), TpcRawWriter::process_event(), MvtxHitPruner::process_event(), SynRadAna::process_event(), TPCMLDataInterface::process_event(), PHG4TpcElectronDrift::process_event(), and DumpTrkrHitSetContainer::process_Node().
virtual TrkrDefs::hitsetkey TrkrHitSet::getHitSetKey () const inline virtual
Get the key for this object.
Parameters
[out] object key
Reimplemented in TrkrHitSetv1.
Definition at line 58 of file TrkrHitSet.h.
View newest version in sPHENIX GitHub at line 58 of file TrkrHitSet.h
Referenced by TrkrHitSetContainerv1::addHitSet(), PHG4InttHitReco::cluster_truthhits(), PHG4MvtxHitReco::cluster_truthhits(), InttClusterizer::ClusterLadderCells(), MvtxPrototype2Clusterizer::ClusterMvtx(), MvtxClusterizer::ClusterMvtx(), TpcPrototypeClusterizer::process_event(), and TrkrHitSetContainerv1::removeHitSet().
void TrkrHitSet::identify (std::ostream & = std::cout) const inline override virtual
TObject functions.
Reimplemented from PHObject.
Reimplemented in TrkrHitSetv1.
Definition at line 38 of file TrkrHitSet.h.
View newest version in sPHENIX GitHub at line 38 of file TrkrHitSet.h
Referenced by PHG4InttHitReco::cluster_truthhits(), PHG4MvtxHitReco::cluster_truthhits(), InttClusterizer::ClusterLadderCells(), MvtxPrototype2Clusterizer::ClusterMvtx(), MvtxClusterizer::ClusterMvtx(), TpcPrototypeClusterizer::process_event(), and TPCMLDataInterface::process_event().
virtual void TrkrHitSet::removeHit (TrkrDefs::hitkey) inline virtual
Remove a hit using its key.
Parameters
[in] key to be removed
Reimplemented in TrkrHitSetv1.
Definition at line 77 of file TrkrHitSet.h.
View newest version in sPHENIX GitHub at line 77 of file TrkrHitSet.h
Referenced by PHG4TpcDigitizer::DigitizeCylinderCells(), PHG4InttDigitizer::DigitizeLadderCells(), PHG4MvtxDigitizer::DigitizeMvtxLadderCells(), and PHG4MicromegasDigitizer::process_event().
void TrkrHitSet::Reset () inline override virtual
Clear Event.
Reimplemented from PHObject.
Reimplemented in TrkrHitSetv1.
Definition at line 42 of file TrkrHitSet.h.
View newest version in sPHENIX GitHub at line 42 of file TrkrHitSet.h
virtual void TrkrHitSet::setHitSetKey (const TrkrDefs::hitsetkey) inline virtual
Set the key for this object.
Parameters
key
Reimplemented in TrkrHitSetv1.
Definition at line 50 of file TrkrHitSet.h.
View newest version in sPHENIX GitHub at line 50 of file TrkrHitSet.h
virtual unsigned int TrkrHitSet::size (void) const inline virtual
Get the number of hits stored.
Parameters
[out] number of hits
Reimplemented in TrkrHitSetv1.
Definition at line 104 of file TrkrHitSet.h.
View newest version in sPHENIX GitHub at line 104 of file TrkrHitSet.h
Referenced by HFTrigger::calculateMultiplicity(), HFTriggerMVA::calculateMultiplicity(), PHG4MvtxHitReco::cluster_truthhits(), MvtxPrototype2UnpackPRDF::process_event(), MvtxHitPruner::process_event(), and TPCMLDataInterface::process_event().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/trackbase/TrkrHitSet.h
coresoftware/blob/master/offline/packages/trackbase/TrkrHitSet.cc