Analysis Software: Jetscape::SurfaceFinder Class Reference
Jetscape::SurfaceFinder Class Reference
#include <JETSCAPE/blob/main/src/framework/SurfaceFinder.h>
Public Member Functions
SurfaceFinder (const Jetscape::real T_in, const EvolutionHistory &bulk_data)
~SurfaceFinder ()
void Find_full_hypersurface ()
int get_number_of_surface_cells () const
SurfaceCellInfo get_surface_cell_with_idx (int idx) const
std::vector< SurfaceCellInfo > get_surface_cells_vector () const
bool check_intersect_3D (Jetscape::real tau, Jetscape::real x, Jetscape::real y, Jetscape::real dt, Jetscape::real dx, Jetscape::real dy, double ***cube)
void Find_full_hypersurface_3D ()
bool check_intersect_4D (Jetscape::real tau, Jetscape::real x, Jetscape::real y, Jetscape::real eta, Jetscape::real dt, Jetscape::real dx, Jetscape::real dy, Jetscape::real deta, double ****cube)
void Find_full_hypersurface_4D ()
SurfaceCellInfo PrepareASurfaceCell (Jetscape::real tau, Jetscape::real x, Jetscape::real y, Jetscape::real eta, Jetscape::real da0, Jetscape::real da1, Jetscape::real da2, Jetscape::real da3, const FluidCellInfo fluid_cell)
Private Attributes
Jetscape::real T_cut
const EvolutionHistory & bulk_info
bool boost_invariant
std::vector< SurfaceCellInfo > surface_cell_list
Detailed Description
Definition at line 28 of file SurfaceFinder.h.
View newest version in sPHENIX GitHub at line 28 of file SurfaceFinder.h
Constructor & Destructor Documentation
SurfaceFinder::SurfaceFinder (const Jetscape::real T_in, const EvolutionHistory & bulk_data)
Definition at line 26 of file SurfaceFinder.cc.
View newest version in sPHENIX GitHub at line 26 of file SurfaceFinder.cc
References boost_invariant, bulk_info, Jetscape::EvolutionHistory::get_data_size(), Jetscape::EvolutionHistory::is_boost_invariant(), JSINFO, and T_cut.
SurfaceFinder::~SurfaceFinder ()
Definition at line 41 of file SurfaceFinder.cc.
View newest version in sPHENIX GitHub at line 41 of file SurfaceFinder.cc
References surface_cell_list.
Member Function Documentation
bool SurfaceFinder::check_intersect_3D (Jetscape::real tau, Jetscape::real x, Jetscape::real y, Jetscape::real dt, Jetscape::real dx, Jetscape::real dy, double *** cube)
Definition at line 53 of file SurfaceFinder.cc.
View newest version in sPHENIX GitHub at line 53 of file SurfaceFinder.cc
References bulk_info, Jetscape::EvolutionHistory::get(), Acts::PlanarHelper::intersect(), T_cut, and Jetscape::FluidCellInfo::temperature.
Referenced by Find_full_hypersurface_3D().
bool SurfaceFinder::check_intersect_4D (Jetscape::real tau, Jetscape::real x, Jetscape::real y, Jetscape::real eta, Jetscape::real dt, Jetscape::real dx, Jetscape::real dy, Jetscape::real deta, double **** cube)
Definition at line 170 of file SurfaceFinder.cc.
View newest version in sPHENIX GitHub at line 170 of file SurfaceFinder.cc
References bulk_info, Jetscape::EvolutionHistory::get(), Acts::PlanarHelper::intersect(), T_cut, and Jetscape::FluidCellInfo::temperature.
Referenced by Find_full_hypersurface_4D().
void SurfaceFinder::Find_full_hypersurface ()
Definition at line 43 of file SurfaceFinder.cc.
View newest version in sPHENIX GitHub at line 43 of file SurfaceFinder.cc
References boost_invariant, Find_full_hypersurface_3D(), Find_full_hypersurface_4D(), JSINFO, and T_cut.
void SurfaceFinder::Find_full_hypersurface_3D ()
Definition at line 92 of file SurfaceFinder.cc.
View newest version in sPHENIX GitHub at line 92 of file SurfaceFinder.cc
References bulk_info, check_intersect_3D(), Acts::Test::dim, Cornelius::find_surface_3d(), Jetscape::EvolutionHistory::get(), Cornelius::get_centroid_elem(), Cornelius::get_Nelements(), Cornelius::get_normal_elem(), i, Cornelius::init(), Acts::PlanarHelper::intersect(), j, k, nx, ny, PrepareASurfaceCell(), surface_cell_list, T_cut, Jetscape::EvolutionHistory::Tau0(), Jetscape::EvolutionHistory::TauMax(), Jetscape::EvolutionHistory::XMin(), and Jetscape::EvolutionHistory::YMin().
Referenced by Find_full_hypersurface().
void SurfaceFinder::Find_full_hypersurface_4D ()
Definition at line 234 of file SurfaceFinder.cc.
View newest version in sPHENIX GitHub at line 234 of file SurfaceFinder.cc
References bulk_info, check_intersect_4D(), Acts::Test::dim, Jetscape::EvolutionHistory::EtaMin(), Cornelius::find_surface_4d(), Jetscape::EvolutionHistory::get(), Cornelius::get_centroid_elem(), Cornelius::get_Nelements(), Cornelius::get_normal_elem(), i, Cornelius::init(), Acts::PlanarHelper::intersect(), j, k, nx, ny, PrepareASurfaceCell(), surface_cell_list, T_cut, Jetscape::EvolutionHistory::Tau0(), Jetscape::EvolutionHistory::TauMax(), Jetscape::EvolutionHistory::XMin(), and Jetscape::EvolutionHistory::YMin().
Referenced by Find_full_hypersurface().
int Jetscape::SurfaceFinder::get_number_of_surface_cells () const inline
Definition at line 42 of file SurfaceFinder.h.
View newest version in sPHENIX GitHub at line 42 of file SurfaceFinder.h
References surface_cell_list.
SurfaceCellInfo Jetscape::SurfaceFinder::get_surface_cell_with_idx (int idx) const inline
Definition at line 43 of file SurfaceFinder.h.
View newest version in sPHENIX GitHub at line 43 of file SurfaceFinder.h
References surface_cell_list.
std::vector<SurfaceCellInfo> Jetscape::SurfaceFinder::get_surface_cells_vector () const inline
Definition at line 46 of file SurfaceFinder.h.
View newest version in sPHENIX GitHub at line 46 of file SurfaceFinder.h
References surface_cell_list.
SurfaceCellInfo SurfaceFinder::PrepareASurfaceCell (Jetscape::real tau, Jetscape::real x, Jetscape::real y, Jetscape::real eta, Jetscape::real da0, Jetscape::real da1, Jetscape::real da2, Jetscape::real da3, const FluidCellInfo fluid_cell)
Definition at line 334 of file SurfaceFinder.cc.
View newest version in sPHENIX GitHub at line 334 of file SurfaceFinder.cc
References Jetscape::FluidCellInfo::bulk_Pi, Jetscape::SurfaceCellInfo::bulk_Pi, Jetscape::SurfaceCellInfo::d3sigma_mu, Jetscape::FluidCellInfo::energy_density, Jetscape::SurfaceCellInfo::energy_density, Jetscape::FluidCellInfo::entropy_density, Jetscape::SurfaceCellInfo::entropy_density, eta, Jetscape::SurfaceCellInfo::eta, i, j, Jetscape::FluidCellInfo::mu_B, Jetscape::SurfaceCellInfo::mu_B, Jetscape::FluidCellInfo::mu_C, Jetscape::SurfaceCellInfo::mu_C, Jetscape::FluidCellInfo::mu_S, Jetscape::SurfaceCellInfo::mu_S, Jetscape::FluidCellInfo::pi, Jetscape::SurfaceCellInfo::pi, Jetscape::FluidCellInfo::pressure, Jetscape::SurfaceCellInfo::pressure, Jetscape::FluidCellInfo::qgp_fraction, Jetscape::SurfaceCellInfo::qgp_fraction, Jetscape::SurfaceCellInfo::tau, tau, Jetscape::FluidCellInfo::temperature, Jetscape::SurfaceCellInfo::temperature, Jetscape::FluidCellInfo::vx, Jetscape::SurfaceCellInfo::vx, Jetscape::FluidCellInfo::vy, Jetscape::SurfaceCellInfo::vy, Jetscape::FluidCellInfo::vz, Jetscape::SurfaceCellInfo::vz, Jetscape::SurfaceCellInfo::x, ambiguity_solver_full_chain::x, y, and Jetscape::SurfaceCellInfo::y.
Referenced by Find_full_hypersurface_3D(), and Find_full_hypersurface_4D().
Member Data Documentation
bool Jetscape::SurfaceFinder::boost_invariant private
Definition at line 32 of file SurfaceFinder.h.
View newest version in sPHENIX GitHub at line 32 of file SurfaceFinder.h
Referenced by Find_full_hypersurface(), and SurfaceFinder().
const EvolutionHistory& Jetscape::SurfaceFinder::bulk_info private
Definition at line 31 of file SurfaceFinder.h.
View newest version in sPHENIX GitHub at line 31 of file SurfaceFinder.h
Referenced by check_intersect_3D(), check_intersect_4D(), Find_full_hypersurface_3D(), Find_full_hypersurface_4D(), and SurfaceFinder().
std::vector<SurfaceCellInfo> Jetscape::SurfaceFinder::surface_cell_list private
Definition at line 34 of file SurfaceFinder.h.
View newest version in sPHENIX GitHub at line 34 of file SurfaceFinder.h
Referenced by Find_full_hypersurface_3D(), Find_full_hypersurface_4D(), get_number_of_surface_cells(), get_surface_cell_with_idx(), get_surface_cells_vector(), and ~SurfaceFinder().
Jetscape::real Jetscape::SurfaceFinder::T_cut private
Definition at line 30 of file SurfaceFinder.h.
View newest version in sPHENIX GitHub at line 30 of file SurfaceFinder.h
Referenced by check_intersect_3D(), check_intersect_4D(), Find_full_hypersurface(), Find_full_hypersurface_3D(), Find_full_hypersurface_4D(), and SurfaceFinder().
The documentation for this class was generated from the following files:
JETSCAPE/blob/main/src/framework/SurfaceFinder.h
JETSCAPE/blob/main/src/framework/SurfaceFinder.cc