Analysis Software: Acts::detail::grid_helper Struct Reference
Acts::detail::grid_helper Struct Reference
helper functions for grid-related operations
#include <acts/blob/sPHENIX/Core/include/Acts/Utilities/detail/grid_helper.hpp>
Static Public Member Functions
template<class... Axes>
static
GlobalNeighborHoodIndices
< sizeof...(Axes)> closestPointsIndices (const std::array< size_t, sizeof...(Axes)> &localIndices, const std::tuple< Axes...> &axes)
get the global indices for closest points on grid
template<class... Axes>
static std::array< ActsScalar,
sizeof...(Axes)> getBinCenter (const std::array< size_t, sizeof...(Axes)> &localIndices, const std::tuple< Axes...> &axes)
retrieve bin center from set of local bin indices
template<class... Axes>
static size_t getGlobalBin (const std::array< size_t, sizeof...(Axes)> &localBins, const std::tuple< Axes...> &axes)
determine global bin index from local indices along each axis
template<class Point , class... Axes>
static std::array< size_t,
sizeof...(Axes)> getLocalBinIndices (const Point &point, const std::tuple< Axes...> &axes)
determine local bin index for each axis from point
template<class... Axes>
static std::array< size_t,
sizeof...(Axes)> getLocalBinIndices (size_t bin, const std::tuple< Axes...> &axes)
determine local bin index for each axis from global bin index
template<class... Axes>
static std::array< ActsScalar,
sizeof...(Axes)> getLowerLeftBinEdge (const std::array< size_t, sizeof...(Axes)> &localIndices, const std::tuple< Axes...> &axes)
retrieve lower-left bin edge from set of local bin indices
template<class... Axes>
static std::array< size_t,
sizeof...(Axes)> getLowerLeftBinIndices (const std::array< size_t, sizeof...(Axes)> &localIndices, const std::tuple< Axes...> &axes)
get local bin indices for lower-left neighboring bin
template<class... Axes>
static std::array< size_t,
sizeof...(Axes)> getNBins (const std::tuple< Axes...> &axes)
calculate number of bins in a grid defined by a set of axes for each axis
template<class... Axes>
static std::array< const IAxis
*, sizeof...(Axes)> getAxes (const std::tuple< Axes...> &axes)
return an array with copies of the axes, converted to type AnyAxis
template<class... Axes>
static std::array< ActsScalar,
sizeof...(Axes)> getUpperRightBinEdge (const std::array< size_t, sizeof...(Axes)> &localIndices, const std::tuple< Axes...> &axes)
retrieve upper-right bin edge from set of local bin indices
template<class... Axes>
static std::array< size_t,
sizeof...(Axes)> getUpperRightBinIndices (const std::array< size_t, sizeof...(Axes)> &localIndices, const std::tuple< Axes...> &axes)
get local bin indices for upper-right neighboring bin
template<class... Axes>
static std::array< ActsScalar,
sizeof...(Axes)> getMin (const std::tuple< Axes...> &axes)
get the minimum value of all axes of one grid
template<class... Axes>
static std::array< ActsScalar,
sizeof...(Axes)> getMax (const std::tuple< Axes...> &axes)
get the maximum value of all axes of one grid
template<class... Axes>
static std::array< ActsScalar,
sizeof...(Axes)> getWidth (const std::tuple< Axes...> &axes)
get the bin width of all axes of one grid
template<class... Axes>
static
GlobalNeighborHoodIndices
< sizeof...(Axes)> neighborHoodIndices (const std::array< size_t, sizeof...(Axes)> &localIndices, std::pair< size_t, size_t > sizes, const std::tuple< Axes...> &axes)
get global bin indices for bins in specified neighborhood
template<class... Axes>
static
GlobalNeighborHoodIndices
< sizeof...(Axes)> neighborHoodIndices (const std::array< size_t, sizeof...(Axes)> &localIndices, size_t size, const std::tuple< Axes...> &axes)
template<class... Axes>
static
GlobalNeighborHoodIndices
< sizeof...(Axes)> neighborHoodIndices (const std::array< size_t, sizeof...(Axes)> &localIndices, std::array< std::pair< int, int >, sizeof...(Axes)> &sizes, const std::tuple< Axes...> &axes)
get global bin indices for bins in specified neighborhood for each axis
template<class... Axes>
static std::set< size_t > exteriorBinIndices (const std::tuple< Axes...> &axes)
get bin indices of all overflow and underflow bins
template<class Point , class... Axes>
static bool isInside (const Point &position, const std::tuple< Axes...> &axes)
check whether given point is inside axes limits
Detailed Description
helper functions for grid-related operations
Definition at line 495 of file grid_helper.hpp.
View newest version in sPHENIX GitHub at line 495 of file grid_helper.hpp
Member Function Documentation
template<class... Axes> static GlobalNeighborHoodIndices<sizeof...(Axes)> Acts::detail::grid_helper::closestPointsIndices (const std::array< size_t, sizeof...(Axes)> & localIndices, const std::tuple< Axes...> & axes) inline static
get the global indices for closest points on grid
Template Parameters
Axes parameter pack of axis types defining the grid
Parameters
[in] bin global bin index for bin of interest
[in] axes actual axis objects spanning the grid
Returns
Sorted collection of global bin indices for bins whose lower-left corners are the closest points on the grid to every point in the given bin
Note
bin must be a valid bin index (excluding under-/overflow bins along any axis).
Definition at line 508 of file grid_helper.hpp.
View newest version in sPHENIX GitHub at line 508 of file grid_helper.hpp
References Acts::Experimental::detail::localIndices(), and neighborHoodIndices().
Referenced by Acts::detail::Grid< external_spacepoint_t >::rawClosestPointsIndices().
template<class... Axes> static std::set<size_t> Acts::detail::grid_helper::exteriorBinIndices (const std::tuple< Axes...> & axes) inline static
get bin indices of all overflow and underflow bins
Template Parameters
Axes parameter pack of axis types defining the grid
Parameters
[in] axes actual axis objects spanning the grid
Returns
set of global bin indices for all over- and underflow bins
Definition at line 856 of file grid_helper.hpp.
View newest version in sPHENIX GitHub at line 856 of file grid_helper.hpp
References TauVsDIS_MachineLearning_Differentiation::array, Acts::detail::grid_helper_impl< N >::exteriorBinIndices(), ambiguity_solver_full_chain::idx, and Acts::Logging::MAX.
Referenced by Acts::detail::Grid< external_spacepoint_t >::setExteriorBins().
template<class... Axes> static std::array<const IAxis*, sizeof...(Axes)> Acts::detail::grid_helper::getAxes (const std::tuple< Axes...> & axes) inline static
return an array with copies of the axes, converted to type AnyAxis
Template Parameters
Axes parameter pack of axis types defining the grid
Parameters
[in] axes actual axis objects spanning the grid
Returns
array with copies of the axis
Definition at line 672 of file grid_helper.hpp.
View newest version in sPHENIX GitHub at line 672 of file grid_helper.hpp
References arr, and TauVsDIS_MachineLearning_Differentiation::array.
Referenced by Acts::detail::Grid< external_spacepoint_t >::axes().
template<class... Axes> static std::array<ActsScalar, sizeof...(Axes)> Acts::detail::grid_helper::getBinCenter (const std::array< size_t, sizeof...(Axes)> & localIndices, const std::tuple< Axes...> & axes) inline static
retrieve bin center from set of local bin indices
Template Parameters
Axes parameter pack of axis types defining the grid
Parameters
[in] localIndices local bin indices along each axis
[in] axes actual axis objects spanning the grid
Returns
center position of bin
Precondition
localIndices must only contain valid bin indices (i.e. excluding under-/overflow bins).
Definition at line 525 of file grid_helper.hpp.
View newest version in sPHENIX GitHub at line 525 of file grid_helper.hpp
References TauVsDIS_MachineLearning_Differentiation::array, Acts::detail::grid_helper_impl< N >::getBinCenter(), Acts::Experimental::detail::localIndices(), and Acts::Logging::MAX.
Referenced by Acts::detail::Grid< external_spacepoint_t >::binCenter().
template<class... Axes> static size_t Acts::detail::grid_helper::getGlobalBin (const std::array< size_t, sizeof...(Axes)> & localBins, const std::tuple< Axes...> & axes) inline static
determine global bin index from local indices along each axis
Template Parameters
Axes parameter pack of axis types defining the grid
Parameters
[in] localBins local bin indices along each axis
[in] axes actual axis objects spanning the grid
Returns
global index for bin defined by the local bin indices
Precondition
All local bin indices must be a valid index for the corresponding axis (including the under-/overflow bin for this axis).
Definition at line 546 of file grid_helper.hpp.
View newest version in sPHENIX GitHub at line 546 of file grid_helper.hpp
References Acts::detail::grid_helper_impl< N >::getGlobalBin(), and Acts::Logging::MAX.
Referenced by Acts::detail::Grid< external_spacepoint_t >::globalBinFromLocalBins().
template<class Point , class... Axes> static std::array<size_t, sizeof...(Axes)> Acts::detail::grid_helper::getLocalBinIndices (const Point & point, const std::tuple< Axes...> & axes) inline static
determine local bin index for each axis from point
Template Parameters
Point any type with point semantics supporting component access through operator[]
Axes parameter pack of axis types defining the grid
Parameters
[in] point point to look up in the grid
[in] axes actual axis objects spanning the grid
Returns
array with local bin indices along each axis (in same order as given axes object)
Precondition
The given Point type must represent a point in d (or higher) dimensions where d is the number of axis objects in the tuple.
Note
This could be a under-/overflow bin along one or more axes.
Definition at line 573 of file grid_helper.hpp.
View newest version in sPHENIX GitHub at line 573 of file grid_helper.hpp
References TauVsDIS_MachineLearning_Differentiation::array, Acts::detail::grid_helper_impl< N >::getLocalBinIndices(), and Acts::Logging::MAX.
Referenced by Acts::detail::Grid< external_spacepoint_t >::localBinsFromGlobalBin(), Acts::detail::Grid< external_spacepoint_t >::localBinsFromLowerLeftEdge(), and Acts::detail::Grid< external_spacepoint_t >::localBinsFromPosition().
template<class... Axes> static std::array<size_t, sizeof...(Axes)> Acts::detail::grid_helper::getLocalBinIndices (size_t bin, const std::tuple< Axes...> & axes) inline static
determine local bin index for each axis from global bin index
Template Parameters
Axes parameter pack of axis types defining the grid
Parameters
[in] bin global bin index
[in] axes actual axis objects spanning the grid
Returns
array with local bin indices along each axis (in same order as given axes object)
Note
Local bin indices can contain under-/overflow bins along any axis.
Definition at line 594 of file grid_helper.hpp.
View newest version in sPHENIX GitHub at line 594 of file grid_helper.hpp
References TauVsDIS_MachineLearning_Differentiation::array, Acts::detail::grid_helper_impl< N >::getLocalBinIndices(), and Acts::Logging::MAX.
template<class... Axes> static std::array<ActsScalar, sizeof...(Axes)> Acts::detail::grid_helper::getLowerLeftBinEdge (const std::array< size_t, sizeof...(Axes)> & localIndices, const std::tuple< Axes...> & axes) inline static
retrieve lower-left bin edge from set of local bin indices
Template Parameters
Axes parameter pack of axis types defining the grid
Parameters
[in] localIndices local bin indices along each axis
[in] axes actual axis objects spanning the grid
Returns
generalized lower-left bin edge
Precondition
localIndices must only contain valid bin indices (excluding underflow bins).
Definition at line 615 of file grid_helper.hpp.
View newest version in sPHENIX GitHub at line 615 of file grid_helper.hpp
References TauVsDIS_MachineLearning_Differentiation::array, Acts::detail::grid_helper_impl< N >::getLowerLeftBinEdge(), Acts::Experimental::detail::localIndices(), and Acts::Logging::MAX.
Referenced by Acts::detail::Grid< external_spacepoint_t >::lowerLeftBinEdge().
template<class... Axes> static std::array<size_t, sizeof...(Axes)> Acts::detail::grid_helper::getLowerLeftBinIndices (const std::array< size_t, sizeof...(Axes)> & localIndices, const std::tuple< Axes...> & axes) inline static
get local bin indices for lower-left neighboring bin
Template Parameters
Axes parameter pack of axis types defining the grid
Parameters
[in] localIndices local bin indices along each axis
[in] axes actual axis objects spanning the grid
Returns
array with local bin indices of lower-left neighbor bin
Precondition
localIndices must only contain valid bin indices (excluding underflow bins).
This function returns the local bin indices for the generalized lower-left neighbor which simply means that all local bin indices are decremented by one.
Definition at line 639 of file grid_helper.hpp.
View newest version in sPHENIX GitHub at line 639 of file grid_helper.hpp
References Acts::detail::grid_helper_impl< N >::getLowerLeftBinIndices(), Acts::Experimental::detail::localIndices(), and Acts::Logging::MAX.
template<class... Axes> static std::array<ActsScalar, sizeof...(Axes)> Acts::detail::grid_helper::getMax (const std::tuple< Axes...> & axes) inline static
get the maximum value of all axes of one grid
Template Parameters
Axes parameter pack of axis types defining the grid
Parameters
[in] axes actual axis objects spanning the grid
Returns
array returning the maxima of all given axes
Definition at line 742 of file grid_helper.hpp.
View newest version in sPHENIX GitHub at line 742 of file grid_helper.hpp
References TauVsDIS_MachineLearning_Differentiation::array.
Referenced by Acts::detail::Grid< external_spacepoint_t >::maxPosition().
template<class... Axes> static std::array<ActsScalar, sizeof...(Axes)> Acts::detail::grid_helper::getMin (const std::tuple< Axes...> & axes) inline static
get the minimum value of all axes of one grid
Template Parameters
Axes parameter pack of axis types defining the grid
Parameters
[in] axes actual axis objects spanning the grid
Returns
array returning the minima of all given axes
Definition at line 729 of file grid_helper.hpp.
View newest version in sPHENIX GitHub at line 729 of file grid_helper.hpp
References TauVsDIS_MachineLearning_Differentiation::array.
Referenced by Acts::detail::Grid< external_spacepoint_t >::minPosition().
template<class... Axes> static std::array<size_t, sizeof...(Axes)> Acts::detail::grid_helper::getNBins (const std::tuple< Axes...> & axes) inline static
calculate number of bins in a grid defined by a set of axes for each axis
Template Parameters
Axes parameter pack of axis types defining the grid
Parameters
[in] axes actual axis objects spanning the grid
Returns
array of number of bins for each axis of the grid
Note
This does not include under-/overflow bins along each axis.
Definition at line 658 of file grid_helper.hpp.
View newest version in sPHENIX GitHub at line 658 of file grid_helper.hpp
References TauVsDIS_MachineLearning_Differentiation::array.
Referenced by neighborHoodIndices(), and Acts::detail::Grid< external_spacepoint_t >::numLocalBins().
template<class... Axes> static std::array<ActsScalar, sizeof...(Axes)> Acts::detail::grid_helper::getUpperRightBinEdge (const std::array< size_t, sizeof...(Axes)> & localIndices, const std::tuple< Axes...> & axes) inline static
retrieve upper-right bin edge from set of local bin indices
Template Parameters
Axes parameter pack of axis types defining the grid
Parameters
[in] localIndices local bin indices along each axis
[in] axes actual axis objects spanning the grid
Returns
generalized upper-right bin edge
Precondition
localIndices must only contain valid bin indices (excluding overflow bins).
Definition at line 689 of file grid_helper.hpp.
View newest version in sPHENIX GitHub at line 689 of file grid_helper.hpp
References TauVsDIS_MachineLearning_Differentiation::array, Acts::detail::grid_helper_impl< N >::getUpperRightBinEdge(), Acts::Experimental::detail::localIndices(), and Acts::Logging::MAX.
Referenced by Acts::detail::Grid< external_spacepoint_t >::upperRightBinEdge().
template<class... Axes> static std::array<size_t, sizeof...(Axes)> Acts::detail::grid_helper::getUpperRightBinIndices (const std::array< size_t, sizeof...(Axes)> & localIndices, const std::tuple< Axes...> & axes) inline static
get local bin indices for upper-right neighboring bin
Template Parameters
Axes parameter pack of axis types defining the grid
Parameters
[in] localIndices local bin indices along each axis
[in] axes actual axis objects spanning the grid
Returns
array with local bin indices of upper-right neighbor bin
Precondition
localIndices must only contain valid bin indices (excluding overflow bins).
This function returns the local bin indices for the generalized upper-right neighbor which simply means that all local bin indices are incremented by one.
Definition at line 713 of file grid_helper.hpp.
View newest version in sPHENIX GitHub at line 713 of file grid_helper.hpp
References Acts::detail::grid_helper_impl< N >::getUpperRightBinIndices(), Acts::Experimental::detail::localIndices(), and Acts::Logging::MAX.
template<class... Axes> static std::array<ActsScalar, sizeof...(Axes)> Acts::detail::grid_helper::getWidth (const std::tuple< Axes...> & axes) inline static
get the bin width of all axes of one grid
Template Parameters
Axes parameter pack of axis types defining the grid
Parameters
[in] axes actual axis objects spanning the grid
Returns
array returning the maxima of all given axes
Definition at line 755 of file grid_helper.hpp.
View newest version in sPHENIX GitHub at line 755 of file grid_helper.hpp
References TauVsDIS_MachineLearning_Differentiation::array.
Referenced by Acts::detail::Grid< external_spacepoint_t >::binWidth(), and Acts::detail::Grid< external_spacepoint_t >::localBinsFromLowerLeftEdge().
template<class Point , class... Axes> static bool Acts::detail::grid_helper::isInside (const Point & position, const std::tuple< Axes...> & axes) inline static
check whether given point is inside axes limits
Template Parameters
Point any type with point semantics supporting component access through operator[]
Axes parameter pack of axis types defining the grid
Parameters
[in] position point to look up in the grid
[in] axes actual axis objects spanning the grid
Returns
true if , otherwise false
Precondition
The given Point type must represent a point in d (or higher) dimensions where d is the number of axis objects in the tuple.
Definition at line 882 of file grid_helper.hpp.
View newest version in sPHENIX GitHub at line 882 of file grid_helper.hpp
References Acts::detail::grid_helper_impl< N >::isInside(), and Acts::Logging::MAX.
Referenced by Acts::detail::Grid< external_spacepoint_t >::isInside().
template<class... Axes> static GlobalNeighborHoodIndices<sizeof...(Axes)> Acts::detail::grid_helper::neighborHoodIndices (const std::array< size_t, sizeof...(Axes)> & localIndices, std::pair< size_t, size_t > sizes, const std::tuple< Axes...> & axes) inline static
get global bin indices for bins in specified neighborhood
Template Parameters
Axes parameter pack of axis types defining the grid
Parameters
[in] localIndices local bin indices along each axis
[in] size size of neighborhood determining how many adjacent bins along each axis are considered
[in] axes actual axis objects spanning the grid
Returns
Sorted collection of global bin indices for all bins in the neighborhood
Note
Over-/underflow bins are included in the neighborhood.
The size parameter sets the range by how many units each local bin index is allowed to be varied. All local bin indices are varied independently, that is diagonal neighbors are included. Ignoring the truncation of the neighborhood size reaching beyond over-/underflow bins, the neighborhood is of size along each dimension.
The concrete bins which are returned depend on the WrappingTypes of the contained axes
Definition at line 783 of file grid_helper.hpp.
View newest version in sPHENIX GitHub at line 783 of file grid_helper.hpp
References TauVsDIS_MachineLearning_Differentiation::array, getNBins(), Acts::Experimental::detail::localIndices(), Acts::Logging::MAX, and Acts::detail::grid_helper_impl< N >::neighborHoodIndices().
Referenced by closestPointsIndices(), Acts::detail::Grid< external_spacepoint_t >::neighborHoodIndices(), and neighborHoodIndices().
template<class... Axes> static GlobalNeighborHoodIndices<sizeof...(Axes)> Acts::detail::grid_helper::neighborHoodIndices (const std::array< size_t, sizeof...(Axes)> & localIndices, size_t size, const std::tuple< Axes...> & axes) inline static
Definition at line 802 of file grid_helper.hpp.
View newest version in sPHENIX GitHub at line 802 of file grid_helper.hpp
References Acts::Experimental::detail::localIndices(), neighborHoodIndices(), and size.
template<class... Axes> static GlobalNeighborHoodIndices<sizeof...(Axes)> Acts::detail::grid_helper::neighborHoodIndices (const std::array< size_t, sizeof...(Axes)> & localIndices, std::array< std::pair< int, int >, sizeof...(Axes)> & sizes, const std::tuple< Axes...> & axes) inline static
get global bin indices for bins in specified neighborhood for each axis
Template Parameters
Axes parameter pack of axis types defining the grid
Parameters
[in] localIndices local bin indices along each axis
[in] size size of neighborhood for each axis, which bins along each axis are considered
[in] axes actual axis objects spanning the grid
Returns
Sorted collection of global bin indices for all bins in the neighborhood
Note
Over-/underflow bins are included in the neighborhood.
The size parameter sets the range by how many units each local bin index is allowed to be varied. All local bin indices are varied independently, that is diagonal neighbors are included. Ignoring the truncation of the neighborhood size reaching beyond over-/underflow bins, the neighborhood is of size along each dimension.
The concrete bins which are returned depend on the WrappingTypes of the contained axes
Definition at line 831 of file grid_helper.hpp.
View newest version in sPHENIX GitHub at line 831 of file grid_helper.hpp
References TauVsDIS_MachineLearning_Differentiation::array, getNBins(), Acts::Experimental::detail::localIndices(), Acts::Logging::MAX, and Acts::detail::grid_helper_impl< N >::neighborHoodIndices().
The documentation for this struct was generated from the following file:
acts/blob/sPHENIX/Core/include/Acts/Utilities/detail/grid_helper.hpp