Analysis Software: odbc::ResultSetMetaData Class Reference
odbc::ResultSetMetaData Class Reference
#include <RDBC/blob/master/include/RDBC/odbc++/resultsetmetadata.h>
Public Types
enum { columnNoNulls = SQL_NO_NULLS, columnNullable = SQL_NULLABLE, columnNullableUnknown = SQL_NULLABLE_UNKNOWN }
Public Member Functions
int getColumnCount () const
const ODBCXX_STRING & getColumnName (int column) const
int getColumnType (int column) const
int getPrecision (int column) const
int getScale (int column) const
int getColumnDisplaySize (int column)
ODBCXX_STRING getCatalogName (int column)
ODBCXX_STRING getColumnLabel (int column)
ODBCXX_STRING getColumnTypeName (int column)
ODBCXX_STRING getSchemaName (int column)
ODBCXX_STRING getTableName (int column)
bool isAutoIncrement (int column)
bool isCaseSensitive (int column)
bool isCurrency (int column)
bool isDefinitelyWritable (int column)
int isNullable (int column)
bool isReadOnly (int column)
bool isSearchable (int column)
bool isSigned (int column)
bool isWritable (int column)
Private Member Functions
ResultSetMetaData (ResultSet *rs)
~ResultSetMetaData ()
const DriverInfo * _getDriverInfo () const
int _getNumericAttribute (unsigned int col, SQLUSMALLINT attr)
ODBCXX_STRING _getStringAttribute (unsigned int col, SQLUSMALLINT attr, unsigned int maxlen=255)
void _fetchColumnInfo ()
Private Attributes
ResultSet * resultSet_
int numCols_
std::vector< ODBCXX_STRING > colNames_
std::vector< int > colTypes_
std::vector< int > colPrecisions_
std::vector< int > colScales_
bool needsGetData_
Friends
class ResultSet
class Statement
Detailed Description
Provides meta data about a result set
Definition at line 35 of file resultsetmetadata.h.
View newest version in sPHENIX GitHub at line 35 of file resultsetmetadata.h
Member Enumeration Documentation
anonymous enum
Nullability constants
Enumerator:
columnNoNulls
columnNullable
columnNullableUnknown
Definition at line 71 of file resultsetmetadata.h.
View newest version in sPHENIX GitHub at line 71 of file resultsetmetadata.h
Constructor & Destructor Documentation
odbc::ResultSetMetaData::ResultSetMetaData (ResultSet * rs) private
odbc::ResultSetMetaData::~ResultSetMetaData () inline private
Definition at line 55 of file resultsetmetadata.h.
View newest version in sPHENIX GitHub at line 55 of file resultsetmetadata.h
Member Function Documentation
void odbc::ResultSetMetaData::_fetchColumnInfo () private
const DriverInfo* odbc::ResultSetMetaData::_getDriverInfo () const inline private
Definition at line 58 of file resultsetmetadata.h.
View newest version in sPHENIX GitHub at line 58 of file resultsetmetadata.h
int odbc::ResultSetMetaData::_getNumericAttribute (unsigned int col, SQLUSMALLINT attr) private
ODBCXX_STRING odbc::ResultSetMetaData::_getStringAttribute (unsigned int col, SQLUSMALLINT attr, unsigned int maxlen = 255) private
ODBCXX_STRING odbc::ResultSetMetaData::getCatalogName (int column)
Get the catalog name for a column.
Parameters
column The column index, starting at 1
Referenced by ODBCResultSetMetaData::GetCatalogName().
int odbc::ResultSetMetaData::getColumnCount () const
Fetch the number of columns in this result set
Referenced by OnCalServer::check_calibrator_in_statustable(), PktSizeDBodbc::CheckAndAddColumns(), OnlMonDBodbc::CheckAndCreateTable(), OnlMonDBodbc::Dump(), ODBCResultSetMetaData::GetColumnCount(), PktSizeDBodbc::GetPacketContent(), and OnlMonDBodbc::Info().
int odbc::ResultSetMetaData::getColumnDisplaySize (int column)
Get the display size of a column.
Parameters
column The column index, starting at 1
Referenced by ODBCResultSetMetaData::GetColumnDisplaySize().
ODBCXX_STRING odbc::ResultSetMetaData::getColumnLabel (int column)
Get the label (if any) for a column.
Parameters
column The column index, starting at 1
Referenced by ODBCResultSetMetaData::GetColumnLabel().
const ODBCXX_STRING& odbc::ResultSetMetaData::getColumnName (int column) const
Get the name of a column
Parameters
column The column index, starting at 1
Referenced by OnCalServer::check_calibrator_in_statustable(), PktSizeDBodbc::CheckAndAddColumns(), OnlMonDBodbc::CheckAndCreateTable(), OnlMonDBodbc::Dump(), ODBCResultSetMetaData::GetColumnName(), and PktSizeDBodbc::GetPacketContent().
int odbc::ResultSetMetaData::getColumnType (int column) const
Get the SQL type of a column
Parameters
column The column index, starting at 1
See Also
Types
Referenced by ODBCResultSetMetaData::GetColumnType().
ODBCXX_STRING odbc::ResultSetMetaData::getColumnTypeName (int column)
Get the name of a columns SQL type
Parameters
column The column index, starting at 1
Referenced by ODBCResultSetMetaData::GetColumnTypeName().
int odbc::ResultSetMetaData::getPrecision (int column) const
Get the precision of a column
Parameters
column The column index, starting at 1
Referenced by ODBCResultSetMetaData::GetPrecision().
int odbc::ResultSetMetaData::getScale (int column) const
Get the scale of a column
Parameters
column The column index, starting at 1
Referenced by ODBCResultSetMetaData::GetScale().
ODBCXX_STRING odbc::ResultSetMetaData::getSchemaName (int column)
Get the schema name for a column
Parameters
column The column index, starting at 1
Referenced by ODBCResultSetMetaData::GetSchemaName().
ODBCXX_STRING odbc::ResultSetMetaData::getTableName (int column)
Get the table name for a column
Parameters
column The column index, starting at 1
Referenced by ODBCResultSetMetaData::GetTableName().
bool odbc::ResultSetMetaData::isAutoIncrement (int column)
Check if a column is autoincrementing
Parameters
column The column index, starting at 1
Referenced by ODBCResultSetMetaData::IsAutoIncrement().
bool odbc::ResultSetMetaData::isCaseSensitive (int column)
Check if a column is case sensitive
Parameters
column The column index, starting at 1
Referenced by ODBCResultSetMetaData::IsCaseSensitive().
bool odbc::ResultSetMetaData::isCurrency (int column)
Check if a column can be a currency (eg fixed precision)
Parameters
column The column index, starting at 1
Referenced by ODBCResultSetMetaData::IsCurrency().
bool odbc::ResultSetMetaData::isDefinitelyWritable (int column)
Check if a column can be updated
Parameters
column The column index, starting at 1
Referenced by ODBCResultSetMetaData::IsDefinitelyWritable().
int odbc::ResultSetMetaData::isNullable (int column)
Check if a column can be set to NULL
Parameters
column The column index, starting at 1
Referenced by ODBCResultSetMetaData::IsNullable().
bool odbc::ResultSetMetaData::isReadOnly (int column)
Check if a column is read only
Parameters
column The column index, starting at 1
Referenced by ODBCResultSetMetaData::IsReadOnly().
bool odbc::ResultSetMetaData::isSearchable (int column)
Check if a column can be used in a where-clause
Parameters
column The column index, starting at 1
Referenced by ODBCResultSetMetaData::IsSearchable().
bool odbc::ResultSetMetaData::isSigned (int column)
Check if a column is signed
Parameters
column The column index, starting at 1
Referenced by ODBCResultSetMetaData::IsSigned().
bool odbc::ResultSetMetaData::isWritable (int column)
Check if a column is 'probably' writeable
Parameters
column The column index, starting at 1
Referenced by ODBCResultSetMetaData::IsWritable().
Friends And Related Function Documentation
friend class ResultSet friend
Definition at line 36 of file resultsetmetadata.h.
View newest version in sPHENIX GitHub at line 36 of file resultsetmetadata.h
friend class Statement friend
Definition at line 37 of file resultsetmetadata.h.
View newest version in sPHENIX GitHub at line 37 of file resultsetmetadata.h
Member Data Documentation
std::vector<ODBCXX_STRING> odbc::ResultSetMetaData::colNames_ private
Definition at line 42 of file resultsetmetadata.h.
View newest version in sPHENIX GitHub at line 42 of file resultsetmetadata.h
std::vector<int> odbc::ResultSetMetaData::colPrecisions_ private
Definition at line 44 of file resultsetmetadata.h.
View newest version in sPHENIX GitHub at line 44 of file resultsetmetadata.h
std::vector<int> odbc::ResultSetMetaData::colScales_ private
Definition at line 45 of file resultsetmetadata.h.
View newest version in sPHENIX GitHub at line 45 of file resultsetmetadata.h
std::vector<int> odbc::ResultSetMetaData::colTypes_ private
Definition at line 43 of file resultsetmetadata.h.
View newest version in sPHENIX GitHub at line 43 of file resultsetmetadata.h
bool odbc::ResultSetMetaData::needsGetData_ private
Definition at line 51 of file resultsetmetadata.h.
View newest version in sPHENIX GitHub at line 51 of file resultsetmetadata.h
int odbc::ResultSetMetaData::numCols_ private
Definition at line 41 of file resultsetmetadata.h.
View newest version in sPHENIX GitHub at line 41 of file resultsetmetadata.h
ResultSet* odbc::ResultSetMetaData::resultSet_ private
Definition at line 39 of file resultsetmetadata.h.
View newest version in sPHENIX GitHub at line 39 of file resultsetmetadata.h
The documentation for this class was generated from the following file:
RDBC/blob/master/include/RDBC/odbc++/resultsetmetadata.h