Analysis Software: RawClusterBuilderTopo Class Reference
RawClusterBuilderTopo Class Reference
#include <coresoftware/blob/master/offline/packages/CaloReco/RawClusterBuilderTopo.h>
Public Member Functions
RawClusterBuilderTopo (const std::string &name="RawClusterBuilderTopo")
~RawClusterBuilderTopo () override
int InitRun (PHCompositeNode *topNode) override
int process_event (PHCompositeNode *topNode) override
int End (PHCompositeNode *topNode) override
Called at the end of all processing.
void set_nodename (const std::string &nodename)
void set_noise (float noise_0=0.0025, float noise_1=0.006, float noise_2=0.03)
void set_significance (float seed, float grow, float peri)
void allow_corner_neighbor (bool allow)
void set_enable_HCal (bool enable_HCal)
void set_enable_EMCal (bool enable_EMCal)
void set_do_split (bool do_split)
void set_minE_local_max (float minE_0=1, float minE_1=1, float minE_2=1)
void set_R_shower (float R_shower)
Public Member Functions inherited from SubsysReco
~SubsysReco () override
virtual int EndRun (const int)
Called at the end of each run.
virtual int Init (PHCompositeNode *)
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
void Print (const std::string &="ALL") const override
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Private Member Functions
void CreateNodes (PHCompositeNode *topNode)
int get_first_matching_EMCal_phi_from_IHCal (int index_hcal_phi)
int get_matching_HCal_phi_from_EMCal (int index_emcal_phi)
std::vector< int > get_adjacent_towers_by_ID (int ID)
float calculate_dR (float, float, float, float)
void export_single_cluster (const std::vector< int > &)
void export_clusters (const std::vector< int > &, std::map< int, std::pair< int, int > >, unsigned int, std::vector< float >, std::vector< float >, std::vector< float >)
int get_ID (int ilayer, int ieta, int iphi)
int get_ilayer_from_ID (int ID)
int get_ieta_from_ID (int ID)
int get_iphi_from_ID (int ID)
int get_status_from_ID (int ID)
float get_E_from_ID (int ID)
void set_status_by_ID (int ID, int status)
Private Attributes
std::vector< std::vector
< std::vector< float > > > _TOWERMAP_E_LAYER_ETA_PHI
std::vector< std::vector
< std::vector< int > > > _TOWERMAP_KEY_LAYER_ETA_PHI
std::vector< std::vector
< std::vector< int > > > _TOWERMAP_STATUS_LAYER_ETA_PHI
std::vector< std::vector< float > > _EMTOWERMAP_E_ETA_PHI
std::vector< std::vector< int > > _EMTOWERMAP_KEY_ETA_PHI
std::vector< std::vector< int > > _EMTOWERMAP_STATUS_ETA_PHI
int _EMCAL_NETA
int _EMCAL_NPHI
int _HCAL_NETA
int _HCAL_NPHI
RawClusterContainer * _clusters = nullptr
RawTowerGeomContainer * _geom_containers [3] {}
float _noise_LAYER [3] {}
float _sigma_seed
float _sigma_grow
float _sigma_peri
bool _allow_corner_neighbor
bool _enable_HCal
bool _enable_EMCal
bool _do_split
float _local_max_minE_LAYER [3] {}
float _R_shower
std::string ClusterNodeName
Static Private Attributes
static int RawClusterBuilderTopo_constants_EMCal_eta_start_given_IHCal []
static int RawClusterBuilderTopo_constants_EMCal_eta_end_given_IHCal []
static int RawClusterBuilderTopo_constants_IHCal_eta_given_EMCal []
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = std::numeric_limits<int>::max() - 10
}
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Detailed Description
Definition at line 21 of file RawClusterBuilderTopo.h.
View newest version in sPHENIX GitHub at line 21 of file RawClusterBuilderTopo.h
Constructor & Destructor Documentation
RawClusterBuilderTopo::RawClusterBuilderTopo (const std::string & name = "RawClusterBuilderTopo") explicit
Definition at line 331 of file RawClusterBuilderTopo.cc.
View newest version in sPHENIX GitHub at line 331 of file RawClusterBuilderTopo.cc
References _allow_corner_neighbor, _do_split, _EMCAL_NETA, _EMCAL_NPHI, _enable_EMCal, _enable_HCal, _geom_containers, _HCAL_NETA, _HCAL_NPHI, _local_max_minE_LAYER, _noise_LAYER, _R_shower, _sigma_grow, _sigma_peri, _sigma_seed, parse_cmake_options::begin, ClusterNodeName, and end.
RawClusterBuilderTopo::~RawClusterBuilderTopo () inline override
Definition at line 25 of file RawClusterBuilderTopo.h.
View newest version in sPHENIX GitHub at line 25 of file RawClusterBuilderTopo.h
Member Function Documentation
void RawClusterBuilderTopo::allow_corner_neighbor (bool allow) inline
Definition at line 50 of file RawClusterBuilderTopo.h.
View newest version in sPHENIX GitHub at line 50 of file RawClusterBuilderTopo.h
References _allow_corner_neighbor.
Referenced by TopoClusterReco().
float RawClusterBuilderTopo::calculate_dR (float eta1, float eta2, float phi1, float phi2) private
Definition at line 58 of file RawClusterBuilderTopo.cc.
View newest version in sPHENIX GitHub at line 58 of file RawClusterBuilderTopo.cc
References INTTVtxZ::dphi.
Referenced by export_clusters(), and process_event().
void RawClusterBuilderTopo::CreateNodes (PHCompositeNode * topNode) private
Definition at line 1415 of file RawClusterBuilderTopo.cc.
View newest version in sPHENIX GitHub at line 1415 of file RawClusterBuilderTopo.cc
References _clusters, PHCompositeNode::addNode(), ClusterNodeName, PHNodeIterator::findFirst(), and PHWHERE.
Referenced by InitRun().
int RawClusterBuilderTopo::End (PHCompositeNode *) override virtual
Called at the end of all processing.
Reimplemented from SubsysReco.
Definition at line 1410 of file RawClusterBuilderTopo.cc.
View newest version in sPHENIX GitHub at line 1410 of file RawClusterBuilderTopo.cc
References Fun4AllReturnCodes::EVENT_OK.
void RawClusterBuilderTopo::export_clusters (const std::vector< int > & original_towers, std::map< int, std::pair< int, int > > tower_ownership, unsigned int n_clusters, std::vector< float > pseudocluster_sumE, std::vector< float > pseudocluster_eta, std::vector< float > pseudocluster_phi) private
Definition at line 215 of file RawClusterBuilderTopo.cc.
View newest version in sPHENIX GitHub at line 215 of file RawClusterBuilderTopo.cc
References _clusters, _EMTOWERMAP_KEY_ETA_PHI, _geom_containers, _R_shower, _TOWERMAP_KEY_LAYER_ETA_PHI, RawClusterContainer::AddCluster(), calculate_dR(), clusters, RawTowerGeom::get_center_x(), RawTowerGeom::get_center_y(), RawTowerGeom::get_center_z(), get_E_from_ID(), RawTowerGeom::get_eta(), get_ieta_from_ID(), get_ilayer_from_ID(), get_iphi_from_ID(), RawTowerGeom::get_phi(), RawTowerGeomContainer::get_tower_geometry(), physmon_track_finding_ttbar::r, and Fun4AllBase::Verbosity().
Referenced by export_single_cluster(), and process_event().
void RawClusterBuilderTopo::export_single_cluster (const std::vector< int > & original_towers) private
Definition at line 198 of file RawClusterBuilderTopo.cc.
View newest version in sPHENIX GitHub at line 198 of file RawClusterBuilderTopo.cc
References export_clusters(), and Fun4AllBase::Verbosity().
Referenced by process_event().
std::vector< int > RawClusterBuilderTopo::get_adjacent_towers_by_ID (int ID) private
Definition at line 73 of file RawClusterBuilderTopo.cc.
View newest version in sPHENIX GitHub at line 73 of file RawClusterBuilderTopo.cc
References _allow_corner_neighbor, _EMCAL_NETA, _EMCAL_NPHI, _enable_EMCal, _enable_HCal, _HCAL_NETA, _HCAL_NPHI, delta_phi(), get_first_matching_EMCal_phi_from_IHCal(), get_ID(), get_ieta_from_ID(), get_ilayer_from_ID(), get_iphi_from_ID(), get_matching_HCal_phi_from_EMCal(), RawClusterBuilderTopo_constants_EMCal_eta_end_given_IHCal, RawClusterBuilderTopo_constants_EMCal_eta_start_given_IHCal, RawClusterBuilderTopo_constants_IHCal_eta_given_EMCal, and Fun4AllBase::Verbosity().
Referenced by process_event().
float RawClusterBuilderTopo::get_E_from_ID (int ID) inline private
Definition at line 180 of file RawClusterBuilderTopo.h.
View newest version in sPHENIX GitHub at line 180 of file RawClusterBuilderTopo.h
References _EMCAL_NETA, _EMCAL_NPHI, _EMTOWERMAP_E_ETA_PHI, _TOWERMAP_E_LAYER_ETA_PHI, get_ieta_from_ID(), get_ilayer_from_ID(), and get_iphi_from_ID().
Referenced by export_clusters(), and process_event().
int RawClusterBuilderTopo::get_first_matching_EMCal_phi_from_IHCal (int index_hcal_phi) inline private
Definition at line 108 of file RawClusterBuilderTopo.h.
View newest version in sPHENIX GitHub at line 108 of file RawClusterBuilderTopo.h
References _EMCAL_NPHI.
Referenced by get_adjacent_towers_by_ID().
int RawClusterBuilderTopo::get_ID (int ilayer, int ieta, int iphi) inline private
Definition at line 126 of file RawClusterBuilderTopo.h.
View newest version in sPHENIX GitHub at line 126 of file RawClusterBuilderTopo.h
References _EMCAL_NETA, _EMCAL_NPHI, _HCAL_NETA, and _HCAL_NPHI.
Referenced by get_adjacent_towers_by_ID(), and process_event().
int RawClusterBuilderTopo::get_ieta_from_ID (int ID) inline private
Definition at line 147 of file RawClusterBuilderTopo.h.
View newest version in sPHENIX GitHub at line 147 of file RawClusterBuilderTopo.h
References _EMCAL_NETA, _EMCAL_NPHI, _HCAL_NETA, and _HCAL_NPHI.
Referenced by export_clusters(), get_adjacent_towers_by_ID(), get_E_from_ID(), get_status_from_ID(), process_event(), and set_status_by_ID().
int RawClusterBuilderTopo::get_ilayer_from_ID (int ID) inline private
Definition at line 135 of file RawClusterBuilderTopo.h.
View newest version in sPHENIX GitHub at line 135 of file RawClusterBuilderTopo.h
References _EMCAL_NETA, _EMCAL_NPHI, _HCAL_NETA, and _HCAL_NPHI.
Referenced by export_clusters(), get_adjacent_towers_by_ID(), get_E_from_ID(), get_status_from_ID(), process_event(), and set_status_by_ID().
int RawClusterBuilderTopo::get_iphi_from_ID (int ID) inline private
Definition at line 159 of file RawClusterBuilderTopo.h.
View newest version in sPHENIX GitHub at line 159 of file RawClusterBuilderTopo.h
References _EMCAL_NETA, _EMCAL_NPHI, and _HCAL_NPHI.
Referenced by export_clusters(), get_adjacent_towers_by_ID(), get_E_from_ID(), get_status_from_ID(), process_event(), and set_status_by_ID().
int RawClusterBuilderTopo::get_matching_HCal_phi_from_EMCal (int index_emcal_phi) inline private
Definition at line 113 of file RawClusterBuilderTopo.h.
View newest version in sPHENIX GitHub at line 113 of file RawClusterBuilderTopo.h
References _EMCAL_NPHI, and _HCAL_NPHI.
Referenced by get_adjacent_towers_by_ID().
int RawClusterBuilderTopo::get_status_from_ID (int ID) inline private
Definition at line 171 of file RawClusterBuilderTopo.h.
View newest version in sPHENIX GitHub at line 171 of file RawClusterBuilderTopo.h
References _EMCAL_NETA, _EMCAL_NPHI, _EMTOWERMAP_STATUS_ETA_PHI, _TOWERMAP_STATUS_LAYER_ETA_PHI, get_ieta_from_ID(), get_ilayer_from_ID(), and get_iphi_from_ID().
Referenced by process_event().
int RawClusterBuilderTopo::InitRun (PHCompositeNode *) override virtual
Called for first event when run number is known. Typically this is where you may want to fetch data from database, because you know the run number.
Reimplemented from SubsysReco.
Definition at line 364 of file RawClusterBuilderTopo.cc.
View newest version in sPHENIX GitHub at line 364 of file RawClusterBuilderTopo.cc
References _allow_corner_neighbor, _do_split, _enable_EMCal, _enable_HCal, _local_max_minE_LAYER, _noise_LAYER, _R_shower, _sigma_grow, _sigma_peri, _sigma_seed, CreateNodes(), Acts::UnitConstants::e, Fun4AllReturnCodes::EVENT_OK, PHWHERE, and Fun4AllBase::Verbosity().
int RawClusterBuilderTopo::process_event (PHCompositeNode *) override virtual
Called for each event. This is where you do the real work.
Reimplemented from SubsysReco.
Definition at line 389 of file RawClusterBuilderTopo.cc.
View newest version in sPHENIX GitHub at line 389 of file RawClusterBuilderTopo.cc
References _clusters, _do_split, _EMCAL_NETA, _EMCAL_NPHI, _EMTOWERMAP_E_ETA_PHI, _EMTOWERMAP_KEY_ETA_PHI, _EMTOWERMAP_STATUS_ETA_PHI, _enable_EMCal, _enable_HCal, _geom_containers, _HCAL_NETA, _HCAL_NPHI, _local_max_minE_LAYER, _noise_LAYER, _sigma_grow, _sigma_peri, _sigma_seed, _TOWERMAP_E_LAYER_ETA_PHI, _TOWERMAP_KEY_LAYER_ETA_PHI, _TOWERMAP_STATUS_LAYER_ETA_PHI, Fun4AllReturnCodes::ABORTEVENT, calculate_dR(), Enable::CEMC, dR(), E, TowerInfoContainer::encode_key(), RawTowerDefs::encode_towerid(), Fun4AllReturnCodes::EVENT_OK, export_clusters(), export_single_cluster(), get_adjacent_towers_by_ID(), get_E_from_ID(), TowerInfo::get_energy(), RawTowerGeom::get_eta(), get_ID(), get_ieta_from_ID(), get_ilayer_from_ID(), get_iphi_from_ID(), RawTowerGeom::get_phi(), get_status_from_ID(), TowerInfoContainer::get_tower_at_channel(), RawClusterContainer::getClusters(), TowerInfoContainer::getTowerEtaBin(), TowerInfoContainer::getTowerPhiBin(), RawTowerDefs::HCALIN, RawTowerDefs::HCALOUT, n, physmon_simulation::s, set_status_by_ID(), TowerInfoContainer::size(), Acts::Experimental::detail::BlueprintHelper::sort(), sort_by_pair_second(), and Fun4AllBase::Verbosity().
void RawClusterBuilderTopo::set_do_split (bool do_split) inline
Definition at line 65 of file RawClusterBuilderTopo.h.
View newest version in sPHENIX GitHub at line 65 of file RawClusterBuilderTopo.h
References _do_split.
Referenced by TopoClusterReco().
void RawClusterBuilderTopo::set_enable_EMCal (bool enable_EMCal) inline
Definition at line 60 of file RawClusterBuilderTopo.h.
View newest version in sPHENIX GitHub at line 60 of file RawClusterBuilderTopo.h
References _enable_EMCal.
Referenced by TopoClusterReco().
void RawClusterBuilderTopo::set_enable_HCal (bool enable_HCal) inline
Definition at line 55 of file RawClusterBuilderTopo.h.
View newest version in sPHENIX GitHub at line 55 of file RawClusterBuilderTopo.h
References _enable_HCal.
Referenced by TopoClusterReco().
void RawClusterBuilderTopo::set_minE_local_max (float minE_0 = 1, float minE_1 = 1, float minE_2 = 1) inline
Definition at line 70 of file RawClusterBuilderTopo.h.
View newest version in sPHENIX GitHub at line 70 of file RawClusterBuilderTopo.h
References _local_max_minE_LAYER.
Referenced by TopoClusterReco().
void RawClusterBuilderTopo::set_nodename (const std::string & nodename) inline
Definition at line 31 of file RawClusterBuilderTopo.h.
View newest version in sPHENIX GitHub at line 31 of file RawClusterBuilderTopo.h
References ClusterNodeName.
Referenced by TopoClusterReco().
void RawClusterBuilderTopo::set_noise (float noise_0 = 0.0025, float noise_1 = 0.006, float noise_2 = 0.03) inline
Definition at line 36 of file RawClusterBuilderTopo.h.
View newest version in sPHENIX GitHub at line 36 of file RawClusterBuilderTopo.h
References _noise_LAYER.
Referenced by TopoClusterReco().
void RawClusterBuilderTopo::set_R_shower (float R_shower) inline
Definition at line 77 of file RawClusterBuilderTopo.h.
View newest version in sPHENIX GitHub at line 77 of file RawClusterBuilderTopo.h
References _R_shower.
Referenced by TopoClusterReco().
void RawClusterBuilderTopo::set_significance (float seed, float grow, float peri) inline
Definition at line 43 of file RawClusterBuilderTopo.h.
View newest version in sPHENIX GitHub at line 43 of file RawClusterBuilderTopo.h
References _sigma_grow, _sigma_peri, _sigma_seed, and seed.
Referenced by TopoClusterReco().
void RawClusterBuilderTopo::set_status_by_ID (int ID, int status) inline private
Definition at line 189 of file RawClusterBuilderTopo.h.
View newest version in sPHENIX GitHub at line 189 of file RawClusterBuilderTopo.h
References _EMCAL_NETA, _EMCAL_NPHI, _EMTOWERMAP_STATUS_ETA_PHI, _TOWERMAP_STATUS_LAYER_ETA_PHI, get_ieta_from_ID(), get_ilayer_from_ID(), get_iphi_from_ID(), and utils::status.
Referenced by process_event().
Member Data Documentation
bool RawClusterBuilderTopo::_allow_corner_neighbor private
Definition at line 211 of file RawClusterBuilderTopo.h.
View newest version in sPHENIX GitHub at line 211 of file RawClusterBuilderTopo.h
Referenced by allow_corner_neighbor(), get_adjacent_towers_by_ID(), InitRun(), and RawClusterBuilderTopo().
RawClusterContainer* RawClusterBuilderTopo::_clusters = nullptr private
Definition at line 201 of file RawClusterBuilderTopo.h.
View newest version in sPHENIX GitHub at line 201 of file RawClusterBuilderTopo.h
Referenced by CreateNodes(), export_clusters(), and process_event().
bool RawClusterBuilderTopo::_do_split private
Definition at line 216 of file RawClusterBuilderTopo.h.
View newest version in sPHENIX GitHub at line 216 of file RawClusterBuilderTopo.h
Referenced by InitRun(), process_event(), RawClusterBuilderTopo(), and set_do_split().
int RawClusterBuilderTopo::_EMCAL_NETA private
Definition at line 101 of file RawClusterBuilderTopo.h.
View newest version in sPHENIX GitHub at line 101 of file RawClusterBuilderTopo.h
Referenced by get_adjacent_towers_by_ID(), get_E_from_ID(), get_ID(), get_ieta_from_ID(), get_ilayer_from_ID(), get_iphi_from_ID(), get_status_from_ID(), process_event(), RawClusterBuilderTopo(), and set_status_by_ID().
int RawClusterBuilderTopo::_EMCAL_NPHI private
Definition at line 102 of file RawClusterBuilderTopo.h.
View newest version in sPHENIX GitHub at line 102 of file RawClusterBuilderTopo.h
Referenced by get_adjacent_towers_by_ID(), get_E_from_ID(), get_first_matching_EMCal_phi_from_IHCal(), get_ID(), get_ieta_from_ID(), get_ilayer_from_ID(), get_iphi_from_ID(), get_matching_HCal_phi_from_EMCal(), get_status_from_ID(), process_event(), RawClusterBuilderTopo(), and set_status_by_ID().
std::vector<std::vector<float> > RawClusterBuilderTopo::_EMTOWERMAP_E_ETA_PHI private
Definition at line 89 of file RawClusterBuilderTopo.h.
View newest version in sPHENIX GitHub at line 89 of file RawClusterBuilderTopo.h
Referenced by get_E_from_ID(), and process_event().
std::vector<std::vector<int> > RawClusterBuilderTopo::_EMTOWERMAP_KEY_ETA_PHI private
Definition at line 90 of file RawClusterBuilderTopo.h.
View newest version in sPHENIX GitHub at line 90 of file RawClusterBuilderTopo.h
Referenced by export_clusters(), and process_event().
std::vector<std::vector<int> > RawClusterBuilderTopo::_EMTOWERMAP_STATUS_ETA_PHI private
Definition at line 91 of file RawClusterBuilderTopo.h.
View newest version in sPHENIX GitHub at line 91 of file RawClusterBuilderTopo.h
Referenced by get_status_from_ID(), process_event(), and set_status_by_ID().
bool RawClusterBuilderTopo::_enable_EMCal private
Definition at line 214 of file RawClusterBuilderTopo.h.
View newest version in sPHENIX GitHub at line 214 of file RawClusterBuilderTopo.h
Referenced by get_adjacent_towers_by_ID(), InitRun(), process_event(), RawClusterBuilderTopo(), and set_enable_EMCal().
bool RawClusterBuilderTopo::_enable_HCal private
Definition at line 213 of file RawClusterBuilderTopo.h.
View newest version in sPHENIX GitHub at line 213 of file RawClusterBuilderTopo.h
Referenced by get_adjacent_towers_by_ID(), InitRun(), process_event(), RawClusterBuilderTopo(), and set_enable_HCal().
RawTowerGeomContainer* RawClusterBuilderTopo::_geom_containers[3] {} private
Definition at line 203 of file RawClusterBuilderTopo.h.
View newest version in sPHENIX GitHub at line 203 of file RawClusterBuilderTopo.h
Referenced by export_clusters(), process_event(), and RawClusterBuilderTopo().
int RawClusterBuilderTopo::_HCAL_NETA private
Definition at line 104 of file RawClusterBuilderTopo.h.
View newest version in sPHENIX GitHub at line 104 of file RawClusterBuilderTopo.h
Referenced by get_adjacent_towers_by_ID(), get_ID(), get_ieta_from_ID(), get_ilayer_from_ID(), process_event(), and RawClusterBuilderTopo().
int RawClusterBuilderTopo::_HCAL_NPHI private
Definition at line 105 of file RawClusterBuilderTopo.h.
View newest version in sPHENIX GitHub at line 105 of file RawClusterBuilderTopo.h
Referenced by get_adjacent_towers_by_ID(), get_ID(), get_ieta_from_ID(), get_ilayer_from_ID(), get_iphi_from_ID(), get_matching_HCal_phi_from_EMCal(), process_event(), and RawClusterBuilderTopo().
float RawClusterBuilderTopo::_local_max_minE_LAYER[3] {} private
Definition at line 217 of file RawClusterBuilderTopo.h.
View newest version in sPHENIX GitHub at line 217 of file RawClusterBuilderTopo.h
Referenced by InitRun(), process_event(), RawClusterBuilderTopo(), and set_minE_local_max().
float RawClusterBuilderTopo::_noise_LAYER[3] {} private
Definition at line 205 of file RawClusterBuilderTopo.h.
View newest version in sPHENIX GitHub at line 205 of file RawClusterBuilderTopo.h
Referenced by InitRun(), process_event(), RawClusterBuilderTopo(), and set_noise().
float RawClusterBuilderTopo::_R_shower private
Definition at line 218 of file RawClusterBuilderTopo.h.
View newest version in sPHENIX GitHub at line 218 of file RawClusterBuilderTopo.h
Referenced by export_clusters(), InitRun(), RawClusterBuilderTopo(), and set_R_shower().
float RawClusterBuilderTopo::_sigma_grow private
Definition at line 208 of file RawClusterBuilderTopo.h.
View newest version in sPHENIX GitHub at line 208 of file RawClusterBuilderTopo.h
Referenced by InitRun(), process_event(), RawClusterBuilderTopo(), and set_significance().
float RawClusterBuilderTopo::_sigma_peri private
Definition at line 209 of file RawClusterBuilderTopo.h.
View newest version in sPHENIX GitHub at line 209 of file RawClusterBuilderTopo.h
Referenced by InitRun(), process_event(), RawClusterBuilderTopo(), and set_significance().
float RawClusterBuilderTopo::_sigma_seed private
Definition at line 207 of file RawClusterBuilderTopo.h.
View newest version in sPHENIX GitHub at line 207 of file RawClusterBuilderTopo.h
Referenced by InitRun(), process_event(), RawClusterBuilderTopo(), and set_significance().
std::vector<std::vector<std::vector<float> > > RawClusterBuilderTopo::_TOWERMAP_E_LAYER_ETA_PHI private
Definition at line 85 of file RawClusterBuilderTopo.h.
View newest version in sPHENIX GitHub at line 85 of file RawClusterBuilderTopo.h
Referenced by get_E_from_ID(), and process_event().
std::vector<std::vector<std::vector<int> > > RawClusterBuilderTopo::_TOWERMAP_KEY_LAYER_ETA_PHI private
Definition at line 86 of file RawClusterBuilderTopo.h.
View newest version in sPHENIX GitHub at line 86 of file RawClusterBuilderTopo.h
Referenced by export_clusters(), and process_event().
std::vector<std::vector<std::vector<int> > > RawClusterBuilderTopo::_TOWERMAP_STATUS_LAYER_ETA_PHI private
Definition at line 87 of file RawClusterBuilderTopo.h.
View newest version in sPHENIX GitHub at line 87 of file RawClusterBuilderTopo.h
Referenced by get_status_from_ID(), process_event(), and set_status_by_ID().
std::string RawClusterBuilderTopo::ClusterNodeName private
Definition at line 220 of file RawClusterBuilderTopo.h.
View newest version in sPHENIX GitHub at line 220 of file RawClusterBuilderTopo.h
Referenced by CreateNodes(), RawClusterBuilderTopo(), and set_nodename().
int RawClusterBuilderTopo::RawClusterBuilderTopo_constants_EMCal_eta_end_given_IHCal static private
Initial value:
=
    {5, 9, 13, 17, 21, 25, 29, 32, 36, 40, 43, 47,
     51, 54, 58, 62, 65, 69, 73, 77, 81, 85, 89, 93}
Definition at line 96 of file RawClusterBuilderTopo.h.
View newest version in sPHENIX GitHub at line 96 of file RawClusterBuilderTopo.h
Referenced by get_adjacent_towers_by_ID().
int RawClusterBuilderTopo::RawClusterBuilderTopo_constants_EMCal_eta_start_given_IHCal static private
Initial value:
=
    {2, 6, 10, 14, 18, 22, 26, 30, 33, 37, 41, 44,
     48, 52, 55, 59, 63, 66, 70, 74, 78, 82, 86, 90}
Definition at line 94 of file RawClusterBuilderTopo.h.
View newest version in sPHENIX GitHub at line 94 of file RawClusterBuilderTopo.h
Referenced by get_adjacent_towers_by_ID().
int RawClusterBuilderTopo::RawClusterBuilderTopo_constants_IHCal_eta_given_EMCal static private
Initial value:
= {
    -1, -1, 0, 0, 0, 0, 1, 1, 1, 1, 2, 2,
    2, 2, 3, 3, 3, 3, 4, 4, 4, 4, 5, 5,
    5, 5, 6, 6, 6, 6, 7, 7, 7, 8, 8, 8,
    8, 9, 9, 9, 9, 10, 10, 10, 11, 11, 11, 11,
    12, 12, 12, 12, 13, 13, 13, 14, 14, 14, 14, 15,
    15, 15, 15, 16, 16, 16, 17, 17, 17, 17, 18, 18,
    18, 18, 19, 19, 19, 19, 20, 20, 20, 20, 21, 21,
    21, 21, 22, 22, 22, 22, 23, 23, 23, 23, -1, -1}
Definition at line 98 of file RawClusterBuilderTopo.h.
View newest version in sPHENIX GitHub at line 98 of file RawClusterBuilderTopo.h
Referenced by get_adjacent_towers_by_ID().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/CaloReco/RawClusterBuilderTopo.h
coresoftware/blob/master/offline/packages/CaloReco/RawClusterBuilderTopo.cc