Analysis Software: macros/blob/master/calibrations/calo/calib_nov23/towerslope/TSCtoCDBTTree.C File Reference
TSCtoCDBTTree.C File Reference
#include <GlobalVariables.C>
#include <cdbobjects/CDBTTree.h>
#include <ffamodules/CDBInterface.h>
#include <phool/recoConsts.h>
#include "TowerInfo.h"
#include "TowerInfoDefs.h"
Functions
void TSCtoCDBTTree (const char *infile, const char *outputfile)
Function Documentation
void TSCtoCDBTTree (const char * infile, const char * outputfile)
Definition at line 15 of file TSCtoCDBTTree.C.
View newest version in sPHENIX GitHub at line 15 of file TSCtoCDBTTree.C
References CDBTTree::Commit(), TowerInfoDefs::encode_emcal(), f, gain, i, j, CDBTTree::SetFloatValue(), and CDBTTree::WriteCDBTTree().
Referenced by doTscFit(), and tsdst_plus_tsfit().