Analysis Software: coresoftware/blob/master/offline/packages/compressor/compressor.h File Reference
compressor.h File Reference
#include <TTree.h>
#include <fstream>
#include <map>
#include <set>
#include <vector>
Functions
Float_t approx (std::vector< UShort_t > *order, std::vector< Float_t > *dict, std::vector< size_t > *cnt, Int_t n_entries, TTree *t, Float_t *gen_, size_t maxNumClusters)
Int_t newLoc (std::vector< Int_t > *loc_vec, std::vector< std::set< Int_t >> *loc_set_vec)
void removeDiff (Float_t distance, Float_t min, std::map< Float_t, std::set< Float_t >> *distance_min_set_map)
void addDiff (Float_t distance, Float_t min, std::map< Float_t, std::set< Float_t >> *distance_min_set_map)
Function Documentation
void addDiff (Float_t distance, Float_t min, std::map< Float_t, std::set< Float_t >> * distance_min_set_map)
Definition at line 157 of file compressor.h.
View newest version in sPHENIX GitHub at line 157 of file compressor.h
References distance().
Referenced by approx().
Float_t approx (std::vector< UShort_t > * order, std::vector< Float_t > * dict, std::vector< size_t > * cnt, Int_t n_entries, TTree * t, Float_t * gen_, size_t maxNumClusters)
Compression algorithm for use in the CMSSW and sPHENIX projects. Using 16-bit short integers to store 32-bit floating-point values. Author: fishy.nosp@m.u@ii.nosp@m.i.org.nosp@m..tw May 22, 2021 approx() compresses data held in t and returns the standard deviation of the differences between the actual and approximated data.
Definition at line 32 of file compressor.h.
View newest version in sPHENIX GitHub at line 32 of file compressor.h
References addDiff(), physmon_vertexing::delta, index, j, loc, Acts::UnitConstants::min, newLoc(), next, removeDiff(), physmon_simulation::s, and sum().
Int_t newLoc (std::vector< Int_t > * loc_vec, std::vector< std::set< Int_t >> * loc_set_vec)
Definition at line 134 of file compressor.h.
View newest version in sPHENIX GitHub at line 134 of file compressor.h
References loc.
Referenced by approx().
void removeDiff (Float_t distance, Float_t min, std::map< Float_t, std::set< Float_t >> * distance_min_set_map)
Definition at line 148 of file compressor.h.
View newest version in sPHENIX GitHub at line 148 of file compressor.h
Referenced by approx().