Analysis Software: Acts::detail::CorrectedFreeToBoundTransformer Struct Reference
Acts::detail::CorrectedFreeToBoundTransformer Struct Reference
Corrected free to bound transform class based on covariance matrix sqrt root in UKF: https://doi.org/10.1117/12.280797.
#include <acts/blob/sPHENIX/Core/include/Acts/EventData/detail/CorrectedTransformationFreeToBound.hpp>
Public Member Functions
CorrectedFreeToBoundTransformer (ActsScalar alpha, ActsScalar beta, ActsScalar cosIncidentAngleMinCutoff, ActsScalar cosIncidentAngleMaxCutoff)
CorrectedFreeToBoundTransformer (const FreeToBoundCorrection &freeToBoundCorrection)
CorrectedFreeToBoundTransformer ()=default
Default constructors.
CorrectedFreeToBoundTransformer (const CorrectedFreeToBoundTransformer &)=default
CorrectedFreeToBoundTransformer (CorrectedFreeToBoundTransformer &&)=default
CorrectedFreeToBoundTransformer & operator= (const CorrectedFreeToBoundTransformer &)=default
CorrectedFreeToBoundTransformer & operator= (CorrectedFreeToBoundTransformer &&)=default
std::optional< std::tuple
< BoundVector,
BoundSquareMatrix > > operator() (const FreeVector &freeParams, const FreeSquareMatrix &freeCovariance, const Surface &surface, const GeometryContext &geoContext, Direction navDir=Direction::Forward, const Logger &logger=getDummyLogger()) const
Private Attributes
ActsScalar m_alpha = 0.1
The parameters to tune the weight in UKF (0 < alpha <=1)
ActsScalar m_beta = 2
ActsScalar m_cosIncidentAngleMinCutoff = 1e-5
ActsScalar m_cosIncidentAngleMaxCutoff = 0.99500417
Detailed Description
Corrected free to bound transform class based on covariance matrix sqrt root in UKF: https://doi.org/10.1117/12.280797.
Definition at line 61 of file CorrectedTransformationFreeToBound.hpp.
View newest version in sPHENIX GitHub at line 61 of file CorrectedTransformationFreeToBound.hpp
Constructor & Destructor Documentation
Acts::detail::CorrectedFreeToBoundTransformer::CorrectedFreeToBoundTransformer (ActsScalar alpha, ActsScalar beta, ActsScalar cosIncidentAngleMinCutoff, ActsScalar cosIncidentAngleMaxCutoff)
Construct from boolean, UKF tuning parameters (alpha, beta) and incident angle cutoff for correction
Parameters
alpha The UKF tuning parameter alpha
beta The UKF tuning parameter beta
cosIncidentAngleMinCutoff The cosine of max incident angle
cosIncidentAngleMaxCutoff The cosine of min incident angle
Definition at line 37 of file CorrectedTransformationFreeToBound.cpp.
View newest version in sPHENIX GitHub at line 37 of file CorrectedTransformationFreeToBound.cpp
Acts::detail::CorrectedFreeToBoundTransformer::CorrectedFreeToBoundTransformer (const FreeToBoundCorrection & freeToBoundCorrection)
Construct from a FreeToBoundCorrection
Parameters
freeToBoundCorrection The freeToBoundCorrection object
Definition at line 45 of file CorrectedTransformationFreeToBound.cpp.
View newest version in sPHENIX GitHub at line 45 of file CorrectedTransformationFreeToBound.cpp
References Acts::FreeToBoundCorrection::alpha, Acts::FreeToBoundCorrection::beta, Acts::FreeToBoundCorrection::cosIncidentAngleMaxCutoff, and Acts::FreeToBoundCorrection::cosIncidentAngleMinCutoff.
Acts::detail::CorrectedFreeToBoundTransformer::CorrectedFreeToBoundTransformer () default
Default constructors.
Acts::detail::CorrectedFreeToBoundTransformer::CorrectedFreeToBoundTransformer (const CorrectedFreeToBoundTransformer &) default
Acts::detail::CorrectedFreeToBoundTransformer::CorrectedFreeToBoundTransformer (CorrectedFreeToBoundTransformer &&) default
Member Function Documentation
std::optional< std::tuple< Acts::BoundVector, Acts::BoundSquareMatrix > > Acts::detail::CorrectedFreeToBoundTransformer::operator() (const FreeVector & freeParams, const FreeSquareMatrix & freeCovariance, const Surface & surface, const GeometryContext & geoContext, Direction navDir = Direction::Forward, const Logger & logger = getDummyLogger()) const
Get the non-linearity corrected bound parameters and its covariance
Parameters
freeParams The free parameters vector
freeCovariance The free parameters covariance
Surface The surface of the bound parameters being represented
geoContext The geometry context
navDir The navigation direction
logger The logger
Definition at line 54 of file CorrectedTransformationFreeToBound.cpp.
View newest version in sPHENIX GitHub at line 54 of file CorrectedTransformationFreeToBound.cpp
References Acts::ACTS_VERBOSE(), ACTS_WARNING, Acts::ObjectMultiIntersection< object_t, representation_t >::closest(), Acts::eFreeDir0, Acts::eFreePos0, Acts::eFreeSize, i, Acts::Surface::intersect(), std::tr1::make_tuple(), Acts::Surface::normal(), Acts::ObjectIntersection< object_t, representation_t >::position(), S(), and Acts::detail::transformFreeToBoundParameters().
CorrectedFreeToBoundTransformer& Acts::detail::CorrectedFreeToBoundTransformer::operator= (const CorrectedFreeToBoundTransformer &) default
CorrectedFreeToBoundTransformer& Acts::detail::CorrectedFreeToBoundTransformer::operator= (CorrectedFreeToBoundTransformer &&) default
Member Data Documentation
ActsScalar Acts::detail::CorrectedFreeToBoundTransformer::m_alpha = 0.1 private
The parameters to tune the weight in UKF (0 < alpha <=1)
Definition at line 105 of file CorrectedTransformationFreeToBound.hpp.
View newest version in sPHENIX GitHub at line 105 of file CorrectedTransformationFreeToBound.hpp
ActsScalar Acts::detail::CorrectedFreeToBoundTransformer::m_beta = 2 private
Definition at line 106 of file CorrectedTransformationFreeToBound.hpp.
View newest version in sPHENIX GitHub at line 106 of file CorrectedTransformationFreeToBound.hpp
ActsScalar Acts::detail::CorrectedFreeToBoundTransformer::m_cosIncidentAngleMaxCutoff = 0.99500417 private
The minimum incident angle (i.e. maximum cos incident angle) cutoff for correction, note cos(0.1) = 0.99500417
Definition at line 114 of file CorrectedTransformationFreeToBound.hpp.
View newest version in sPHENIX GitHub at line 114 of file CorrectedTransformationFreeToBound.hpp
ActsScalar Acts::detail::CorrectedFreeToBoundTransformer::m_cosIncidentAngleMinCutoff = 1e-5 private
The maximum incident angle (i.e. minimum cos incident angle) cutoff for correction
Definition at line 110 of file CorrectedTransformationFreeToBound.hpp.
View newest version in sPHENIX GitHub at line 110 of file CorrectedTransformationFreeToBound.hpp
The documentation for this struct was generated from the following files:
acts/blob/sPHENIX/Core/include/Acts/EventData/detail/CorrectedTransformationFreeToBound.hpp
acts/blob/sPHENIX/Core/src/EventData/CorrectedTransformationFreeToBound.cpp