Analysis Software: PHG4Particle Class Reference
PHG4Particle Class Reference
#include <coresoftware/blob/master/simulation/g4simulation/g4main/PHG4Particle.h>
Public Member Functions
PHG4Particle ()
~PHG4Particle () override
void identify (std::ostream &os=std::cout) const override
virtual bool isIon () const
virtual int get_pid () const
virtual std::string get_name () const
virtual double get_px () const
virtual double get_py () const
virtual double get_pz () const
virtual double get_e () const
virtual int get_track_id () const
virtual int get_vtx_id () const
virtual int get_parent_id () const
virtual int get_primary_id () const
virtual int get_barcode () const
virtual int get_A () const
virtual int get_Z () const
virtual double get_IonCharge () const
virtual double get_ExcitEnergy () const
virtual void set_track_id (const int)
virtual void set_vtx_id (const int)
virtual void set_parent_id (const int)
virtual void set_primary_id (const int)
virtual void set_name (const std::string &)
virtual void set_pid (const int)
virtual void set_px (const double)
virtual void set_py (const double)
virtual void set_pz (const double)
virtual void set_e (const double)
virtual void set_barcode (const int)
virtual void set_A (const int)
virtual void set_Z (const int)
virtual void set_NumCharge (const int)
virtual void set_IonCharge (const double)
virtual void set_ExcitEnergy (const double)
bool operator== (const PHG4Particle &p) const
Public Member Functions inherited from PHObject
PHObject ()
ctor
~PHObject () override
dtor
virtual PHObject * CloneMe () const
Virtual copy constructor.
virtual PHObject * clone () const final
PHObject * Clone (const char *newname="") const final
void Copy (TObject &object) const final
virtual void Reset ()
Clear Event.
virtual int isValid () const
isValid returns non zero if object contains vailid data
virtual int Integrate () const
virtual int Integrate (PHObject *)
virtual void CopyFrom (const PHObject *obj)
Detailed Description
Definition at line 12 of file PHG4Particle.h.
View newest version in sPHENIX GitHub at line 12 of file PHG4Particle.h
Constructor & Destructor Documentation
PHG4Particle::PHG4Particle () inline
Definition at line 15 of file PHG4Particle.h.
View newest version in sPHENIX GitHub at line 15 of file PHG4Particle.h
PHG4Particle::~PHG4Particle () inline override
Definition at line 16 of file PHG4Particle.h.
View newest version in sPHENIX GitHub at line 16 of file PHG4Particle.h
Member Function Documentation
virtual int PHG4Particle::get_A () const inline virtual
Reimplemented in PHG4Particlev3.
Definition at line 36 of file PHG4Particle.h.
View newest version in sPHENIX GitHub at line 36 of file PHG4Particle.h
virtual int PHG4Particle::get_barcode () const inline virtual
Reimplemented in PHG4Particlev1.
Definition at line 34 of file PHG4Particle.h.
View newest version in sPHENIX GitHub at line 34 of file PHG4Particle.h
Referenced by DecayFinder::checkIfCorrectGeant4Particle(), EventEvaluator::fillOutputNtuples(), DecayFinder::findDecay(), BuildResonanceJetTaggingTree::findMatchedTruthD0(), ResonanceJetTagging::findMCTaggedJets(), HFTrackEfficiency::findTracks(), BuildResonanceJetTaggingTree::getMother(), pythiaEMCalAna::isDirectPhoton(), QAG4SimulationKFParticle::makeHepLV(), truthDecayTester::process_event(), QAG4SimulationTruthDecay::process_event(), pythiaEMCalAna::process_event(), FullJetFinder::process_event(), and DecayFinder::searchGeant4Record().
virtual double PHG4Particle::get_e () const inline virtual
Reimplemented in PHG4Particlev2.
Definition at line 27 of file PHG4Particle.h.
View newest version in sPHENIX GitHub at line 27 of file PHG4Particle.h
Referenced by PHG4DSTReader::add_particle(), pythiaEMCalAna::addPrimaryFromGeant(), ActsEvaluator::evaluateTrackFit(), PHAna::fill_truth_ntuple(), KFParticle_truthAndDetTools::fillGeant4Branch(), CaloEvaluator::fillOutputNtuples(), EventEvaluator::fillOutputNtuples(), HCalJetPhiShift::FillTTree(), TruthJetInput::get_input(), IsolatedTrackAnalysis::getAddTruth(), IsolatedTrackAnalysis::getG4Truth(), AnaTutorial::getPHG4Truth(), dNdEtaINTT::GetRecoClusterInfo(), PhotonJet::GetRecoHadronsAndJets(), PhotonJet::GetRecoHadronsAndJetsAA(), AnaTutorial::getTracks(), IsolatedTrackAnalysis::getTracks(), VtxTest::numUnique(), TruthConversionEval::numUnique(), TruthConversionEval::particletoTLV(), CaloEvaluator::printOutputInfo(), PHG4ParticleGenerator::process_event(), SimpleTrackingAnalysis::process_event(), STACalorimeterCharacterization::process_event(), ShowerSize::process_event(), TowerTiming::process_event(), TimingNtuple::process_event(), BJetModule::process_event(), RICHEvaluator::process_event(), Forward_pi0s::process_event(), DetermineTowerBackground::process_event(), Photons::process_event(), SigmaTimingNtuple::process_event(), SynRadAna::process_event(), TruthPhotonJet::process_event(), QAG4Decayer::process_event(), MBDStudy::process_event(), Proto4SampleFrac::process_event(), MbdDigitization::process_event(), hijbkg_upc::process_event(), truthDecayTester::process_event(), BBCStudy::process_event(), QAG4SimulationTruthDecay::process_event(), TruthCaloTree::process_event(), PhotonJet::process_event(), VtxTest::process_event(), jetrtrack::process_event(), QAG4SimulationCalorimeterSum::process_event_Cluster(), QAG4SimulationCalorimeter::process_event_G4Hit(), QAG4SimulationCalorimeterSum::process_event_TrackProj(), CaloWaveFormSim::process_g4hits(), and pythiaEMCalAna::withinAcceptance().
virtual double PHG4Particle::get_ExcitEnergy () const inline virtual
Reimplemented in PHG4Particlev3.
Definition at line 39 of file PHG4Particle.h.
View newest version in sPHENIX GitHub at line 39 of file PHG4Particle.h
virtual double PHG4Particle::get_IonCharge () const inline virtual
Reimplemented in PHG4Particlev3.
Definition at line 38 of file PHG4Particle.h.
View newest version in sPHENIX GitHub at line 38 of file PHG4Particle.h
Referenced by MBDStudy::process_event(), MbdDigitization::process_event(), and BBCStudy::process_event().
virtual std::string PHG4Particle::get_name (void) const inline virtual
Reimplemented in PHG4Particlev1.
Definition at line 23 of file PHG4Particle.h.
View newest version in sPHENIX GitHub at line 23 of file PHG4Particle.h
Referenced by PHG4DSTReader::add_particle(), PHG4TruthInfoContainer::AddParticle(), and PHG4ParticleGeneratorBase::SetParticleId().
virtual int PHG4Particle::get_parent_id () const inline virtual
Reimplemented in PHG4Particlev2.
Definition at line 31 of file PHG4Particle.h.
View newest version in sPHENIX GitHub at line 31 of file PHG4Particle.h
Referenced by PHG4DSTReader::add_particle(), PHG4TruthInfoContainer::AddParticle(), PHG4TruthEventAction::EndOfEventAction(), EventEvaluator::fillOutputNtuples(), ResonanceJetTagging::findMCTaggedJets(), HFTrackEfficiency::findTracks(), IsolatedTrackAnalysis::getAddTruth(), pythiaEMCalAna::getG4EndVtx(), dNdEtaINTT::GetG4PAncestor(), IsolatedTrackAnalysis::getG4Truth(), BaseTruthEval::is_primary(), Forward_pi0s::process_event(), RICHEvaluator::process_event(), QAG4Decayer::process_event(), isoCluster::process_event(), QAG4SimulationTruthDecay::process_event(), truthDecayTester::process_event(), PHTruthClustering::process_event(), TruthCaloTree::process_event(), ElectronID::process_event(), VtxTest::process_event(), TruthConversionEval::process_event(), and DecayFinder::searchGeant4Record().
virtual int PHG4Particle::get_pid () const inline virtual
Reimplemented in PHG4Particlev1.
Definition at line 22 of file PHG4Particle.h.
View newest version in sPHENIX GitHub at line 22 of file PHG4Particle.h
Referenced by PHG4DSTReader::add_particle(), pythiaEMCalAna::addPrimaryFromGeant(), PHTruthSiliconAssociation::buildTrackSeed(), PHTruthTrackSeeding::buildTrackSeed(), RICHEvaluator::calculate_true_emission_angle(), DecayFinder::checkIfCorrectGeant4Particle(), EMCalCalib::eval_photon(), EMCalAna::eval_trk(), QAG4SimulationMicromegas::evaluate_clusters(), QAG4SimulationTpc::evaluate_clusters(), PHG4TrackFastSimEval::fill_track_tree(), AnaSvtxTracksForGenFit::fill_tree(), EpFinderEval::fill_tree(), FastTrackingEval::fill_tree(), GenFitTrackProp::fill_tree(), PHAna::fill_truth_ntuple(), ActsEvaluator::fillG4Particle(), KFParticle_truthAndDetTools::fillGeant4Branch(), psTOFTimezeroEval::fillOutputNtuples(), SvtxEvaluatorHaiwang::fillOutputNtuples(), CaloEvaluator::fillOutputNtuples(), SvtxEvaluator::fillOutputNtuples(), EventEvaluator::fillOutputNtuples(), DecayFinder::findDecay(), ResonanceJetTagging::findMCTaggedJets(), HFTrackEfficiency::findTracks(), TruthJetInput::get_input(), IsolatedTrackAnalysis::getAddTruth(), IsolatedTrackAnalysis::getG4Truth(), AnaTutorial::getPHG4Truth(), dNdEtaINTT::GetRecoClusterInfo(), PhotonJet::GetRecoHadronsAndJets(), PhotonJet::GetRecoHadronsAndJetsAA(), AnaTutorial::getTracks(), IsolatedTrackAnalysis::getTracks(), DISKinematicsReco::InsertCandidateFromCluster(), pythiaEMCalAna::isDirectPhoton(), TruthConversionEval::numUnique(), operator==(), CaloEvaluator::printInputInfo(), CaloEvaluator::printOutputInfo(), PHSiliconTruthTrackSeeding::Process(), RecoInfoExport::process_event(), QAG4SimulationUpsilon::process_event(), SimpleTrackingAnalysis::process_event(), STACalorimeterCharacterization::process_event(), FastPid_RICH::process_event(), BJetModule::process_event(), Forward_pi0s::process_event(), RICHEvaluator::process_event(), QAG4SimulationTracking::process_event(), DetermineTowerBackground::process_event(), Photons::process_event(), HFMLTriggerOccupancy::process_event(), TPCDataStreamEmulator::process_event(), HFMLTriggerInterface::process_event(), SigmaTimingNtuple::process_event(), SynRadAna::process_event(), TruthPhotonJet::process_event(), QAG4Decayer::process_event(), MBDStudy::process_event(), Proto4SampleFrac::process_event(), MbdDigitization::process_event(), hijbkg_upc::process_event(), truthDecayTester::process_event(), QAG4SimulationTruthDecay::process_event(), TPCMLDataInterface::process_event(), BBCStudy::process_event(), PHTruthClustering::process_event(), PHG4ScoringManager::process_event(), TruthCaloTree::process_event(), pythiaEMCalAna::process_event(), PhotonJet::process_event(), ElectronID::process_event(), VtxTest::process_event(), jetrtrack::process_event(), TruthConversionEval::process_event(), QAG4SimulationCalorimeter::process_event_G4Hit(), EMCalAna::process_event_UpslisonTrig(), CaloWaveFormSim::process_g4hits(), SoftLeptonTaggingTruth::process_Spectrum(), TrackClusterEvaluator::processRecoTracks(), PHG4TruthEventAction::ProcessShowers(), TrackClusterEvaluator::processTruthTracks(), DecayFinder::searchGeant4Record(), Conversion::setElectron(), PHG4ParticleGeneratorBase::SetParticleId(), and TruthJetTagging::TruthPhotonTagging().
virtual int PHG4Particle::get_primary_id () const inline virtual
Reimplemented in PHG4Particlev2.
Definition at line 32 of file PHG4Particle.h.
View newest version in sPHENIX GitHub at line 32 of file PHG4Particle.h
Referenced by PHG4DSTReader::add_particle(), DecayFinder::findDecay(), BuildResonanceJetTaggingTree::findMatchedTruthD0(), DSTEmulator::get_embed(), TrackEvaluation::get_embed(), BaseTruthEval::get_primary_particle(), PHG4ConsistencyCheck::process_event(), SynRadAna::process_event(), PHTruthClustering::process_event(), ElectronID::process_event(), TruthConversionEval::process_event(), DecayFinder::searchGeant4Record(), and Conversion::setPrimaryPhoton().
virtual double PHG4Particle::get_px () const inline virtual
Reimplemented in PHG4Particlev1.
Definition at line 24 of file PHG4Particle.h.
View newest version in sPHENIX GitHub at line 24 of file PHG4Particle.h
Referenced by PHG4DSTReader::add_particle(), PHG4TruthInfoContainer::AddParticle(), pythiaEMCalAna::addPrimaryFromGeant(), PHTruthSiliconAssociation::buildTrackSeed(), PHTruthTrackSeeding::buildTrackSeed(), RICHEvaluator::calculate_true_emission_angle(), DecayFinder::checkIfCorrectGeant4Particle(), EMCalCalib::eval_photon(), EMCalCalib::eval_photon_proj(), EMCalAna::eval_trk(), ActsEvaluator::evaluateTrackFit(), PHG4TrackFastSimEval::fill_track_tree(), AnaSvtxTracksForGenFit::fill_tree(), EpFinderEval::fill_tree(), FastTrackingEval::fill_tree(), GenFitTrackProp::fill_tree(), PHAna::fill_truth_ntuple(), ActsEvaluator::fillG4Particle(), KFParticle_truthAndDetTools::fillGeant4Branch(), SvtxEvaluatorHaiwang::fillOutputNtuples(), psTOFTimezeroEval::fillOutputNtuples(), CaloEvaluator::fillOutputNtuples(), SvtxEvaluator::fillOutputNtuples(), EventEvaluator::fillOutputNtuples(), SvtxTruthRecoTableEval::fillTruthMap(), HCalJetPhiShift::FillTTree(), ElectronID::findMCmatch(), HFTrackEfficiency::findTracks(), TruthJetInput::get_input(), SetupDualRICHAnalyzer::get_true_momentum(), IsolatedTrackAnalysis::getAddTruth(), IsolatedTrackAnalysis::getG4Truth(), AnaTutorial::getPHG4Truth(), dNdEtaINTT::GetRecoClusterInfo(), PhotonJet::GetRecoHadronsAndJets(), PhotonJet::GetRecoHadronsAndJetsAA(), AnaTutorial::getTracks(), IsolatedTrackAnalysis::getTracks(), SvtxClusterEval::gtrackid_and_layer_by_nhit(), DISKinematicsReco::InsertCandidateFromCluster(), VtxTest::numUnique(), TruthConversionEval::numUnique(), operator==(), TruthConversionEval::particletoTLV(), CaloEvaluator::printInputInfo(), SvtxEvaluatorHaiwang::printOutputInfo(), psTOFTimezeroEval::printOutputInfo(), CaloEvaluator::printOutputInfo(), SvtxEvaluator::printOutputInfo(), PHSiliconTruthTrackSeeding::Process(), PHTruthTrackSeeding::Process(), MomentumEvaluator::process_event(), SvtxSimPerformanceCheckReco::process_event(), PHG4ParticleGenerator::process_event(), TrackingPerformanceCheck::process_event(), RecoInfoExport::process_event(), QAG4SimulationUpsilon::process_event(), STACalorimeterCharacterization::process_event(), SimpleTrackingAnalysis::process_event(), QAG4SimulationVertex::process_event(), Proto4ShowerCalib::process_event(), ShowerSize::process_event(), TowerTiming::process_event(), TimingNtuple::process_event(), BJetModule::process_event(), RICHEvaluator::process_event(), Forward_pi0s::process_event(), RICHParticleID::process_event(), QAG4SimulationTracking::process_event(), DetermineTowerBackground::process_event(), Photons::process_event(), HFMLTriggerOccupancy::process_event(), TPCDataStreamEmulator::process_event(), Proto2ShowerCalib::process_event(), Proto3ShowerCalib::process_event(), HFMLTriggerInterface::process_event(), SigmaTimingNtuple::process_event(), QAG4Decayer::process_event(), TruthPhotonJet::process_event(), MBDStudy::process_event(), hijbkg_upc::process_event(), MbdDigitization::process_event(), TPCMLDataInterface::process_event(), BBCStudy::process_event(), QAG4SimulationTruthDecay::process_event(), truthDecayTester::process_event(), TruthCaloTree::process_event(), PHG4ScoringManager::process_event(), ExampleAnalysisModule::process_event(), PhotonJet::process_event(), ElectronID::process_event(), VtxTest::process_event(), jetrtrack::process_event(), TruthConversionEval::process_event(), CaloWaveFormSim::process_g4hits(), SoftLeptonTaggingTruth::process_Spectrum(), TrackClusterEvaluator::processRecoTracks(), TrackClusterEvaluator::processTruthTracks(), PHG4TrackFastSim::PseudoPatternRecognition(), TruthJetTagging::TruthPhotonTagging(), and pythiaEMCalAna::withinAcceptance().
virtual double PHG4Particle::get_py () const inline virtual
Reimplemented in PHG4Particlev1.
Definition at line 25 of file PHG4Particle.h.
View newest version in sPHENIX GitHub at line 25 of file PHG4Particle.h
Referenced by PHG4DSTReader::add_particle(), PHG4TruthInfoContainer::AddParticle(), pythiaEMCalAna::addPrimaryFromGeant(), PHTruthSiliconAssociation::buildTrackSeed(), PHTruthTrackSeeding::buildTrackSeed(), RICHEvaluator::calculate_true_emission_angle(), DecayFinder::checkIfCorrectGeant4Particle(), EMCalCalib::eval_photon(), EMCalCalib::eval_photon_proj(), EMCalAna::eval_trk(), ActsEvaluator::evaluateTrackFit(), PHG4TrackFastSimEval::fill_track_tree(), AnaSvtxTracksForGenFit::fill_tree(), EpFinderEval::fill_tree(), FastTrackingEval::fill_tree(), GenFitTrackProp::fill_tree(), PHAna::fill_truth_ntuple(), ActsEvaluator::fillG4Particle(), KFParticle_truthAndDetTools::fillGeant4Branch(), SvtxEvaluatorHaiwang::fillOutputNtuples(), psTOFTimezeroEval::fillOutputNtuples(), CaloEvaluator::fillOutputNtuples(), SvtxEvaluator::fillOutputNtuples(), EventEvaluator::fillOutputNtuples(), SvtxTruthRecoTableEval::fillTruthMap(), HCalJetPhiShift::FillTTree(), ElectronID::findMCmatch(), HFTrackEfficiency::findTracks(), TruthJetInput::get_input(), SetupDualRICHAnalyzer::get_true_momentum(), IsolatedTrackAnalysis::getAddTruth(), IsolatedTrackAnalysis::getG4Truth(), AnaTutorial::getPHG4Truth(), dNdEtaINTT::GetRecoClusterInfo(), PhotonJet::GetRecoHadronsAndJets(), PhotonJet::GetRecoHadronsAndJetsAA(), AnaTutorial::getTracks(), IsolatedTrackAnalysis::getTracks(), SvtxClusterEval::gtrackid_and_layer_by_nhit(), DISKinematicsReco::InsertCandidateFromCluster(), VtxTest::numUnique(), TruthConversionEval::numUnique(), operator==(), TruthConversionEval::particletoTLV(), CaloEvaluator::printInputInfo(), SvtxEvaluatorHaiwang::printOutputInfo(), psTOFTimezeroEval::printOutputInfo(), CaloEvaluator::printOutputInfo(), SvtxEvaluator::printOutputInfo(), PHSiliconTruthTrackSeeding::Process(), PHTruthTrackSeeding::Process(), MomentumEvaluator::process_event(), SvtxSimPerformanceCheckReco::process_event(), PHG4ParticleGenerator::process_event(), TrackingPerformanceCheck::process_event(), RecoInfoExport::process_event(), QAG4SimulationUpsilon::process_event(), STACalorimeterCharacterization::process_event(), SimpleTrackingAnalysis::process_event(), QAG4SimulationVertex::process_event(), Proto4ShowerCalib::process_event(), ShowerSize::process_event(), TowerTiming::process_event(), TimingNtuple::process_event(), BJetModule::process_event(), RICHEvaluator::process_event(), Forward_pi0s::process_event(), RICHParticleID::process_event(), QAG4SimulationTracking::process_event(), DetermineTowerBackground::process_event(), Photons::process_event(), HFMLTriggerOccupancy::process_event(), TPCDataStreamEmulator::process_event(), Proto2ShowerCalib::process_event(), Proto3ShowerCalib::process_event(), HFMLTriggerInterface::process_event(), SigmaTimingNtuple::process_event(), QAG4Decayer::process_event(), TruthPhotonJet::process_event(), MBDStudy::process_event(), hijbkg_upc::process_event(), MbdDigitization::process_event(), TPCMLDataInterface::process_event(), BBCStudy::process_event(), QAG4SimulationTruthDecay::process_event(), truthDecayTester::process_event(), TruthCaloTree::process_event(), PHG4ScoringManager::process_event(), ExampleAnalysisModule::process_event(), PhotonJet::process_event(), ElectronID::process_event(), VtxTest::process_event(), jetrtrack::process_event(), TruthConversionEval::process_event(), CaloWaveFormSim::process_g4hits(), SoftLeptonTaggingTruth::process_Spectrum(), TrackClusterEvaluator::processRecoTracks(), TrackClusterEvaluator::processTruthTracks(), PHG4TrackFastSim::PseudoPatternRecognition(), TruthJetTagging::TruthPhotonTagging(), and pythiaEMCalAna::withinAcceptance().
virtual double PHG4Particle::get_pz () const inline virtual
Reimplemented in PHG4Particlev1.
Definition at line 26 of file PHG4Particle.h.
View newest version in sPHENIX GitHub at line 26 of file PHG4Particle.h
Referenced by PHG4DSTReader::add_particle(), PHG4TruthInfoContainer::AddParticle(), pythiaEMCalAna::addPrimaryFromGeant(), PHTruthSiliconAssociation::buildTrackSeed(), PHTruthTrackSeeding::buildTrackSeed(), RICHEvaluator::calculate_true_emission_angle(), DecayFinder::checkIfCorrectGeant4Particle(), EMCalCalib::eval_photon(), EMCalCalib::eval_photon_proj(), EMCalAna::eval_trk(), ActsEvaluator::evaluateTrackFit(), PHG4TrackFastSimEval::fill_track_tree(), AnaSvtxTracksForGenFit::fill_tree(), EpFinderEval::fill_tree(), FastTrackingEval::fill_tree(), GenFitTrackProp::fill_tree(), PHAna::fill_truth_ntuple(), ActsEvaluator::fillG4Particle(), KFParticle_truthAndDetTools::fillGeant4Branch(), psTOFTimezeroEval::fillOutputNtuples(), SvtxEvaluatorHaiwang::fillOutputNtuples(), CaloEvaluator::fillOutputNtuples(), SvtxEvaluator::fillOutputNtuples(), EventEvaluator::fillOutputNtuples(), SvtxTruthRecoTableEval::fillTruthMap(), HCalJetPhiShift::FillTTree(), ElectronID::findMCmatch(), HFTrackEfficiency::findTracks(), TruthJetInput::get_input(), SetupDualRICHAnalyzer::get_true_momentum(), IsolatedTrackAnalysis::getAddTruth(), IsolatedTrackAnalysis::getG4Truth(), AnaTutorial::getPHG4Truth(), dNdEtaINTT::GetRecoClusterInfo(), PhotonJet::GetRecoHadronsAndJets(), PhotonJet::GetRecoHadronsAndJetsAA(), AnaTutorial::getTracks(), IsolatedTrackAnalysis::getTracks(), SvtxClusterEval::gtrackid_and_layer_by_nhit(), DISKinematicsReco::InsertCandidateFromCluster(), VtxTest::numUnique(), TruthConversionEval::numUnique(), operator==(), TruthConversionEval::particletoTLV(), psTOFTimezeroEval::printOutputInfo(), SvtxEvaluatorHaiwang::printOutputInfo(), CaloEvaluator::printOutputInfo(), SvtxEvaluator::printOutputInfo(), PHSiliconTruthTrackSeeding::Process(), PHTruthTrackSeeding::Process(), MomentumEvaluator::process_event(), PHG4ParticleGenerator::process_event(), TrackingPerformanceCheck::process_event(), RecoInfoExport::process_event(), QAG4SimulationUpsilon::process_event(), QAG4SimulationVertex::process_event(), Proto4ShowerCalib::process_event(), ShowerSize::process_event(), TowerTiming::process_event(), TimingNtuple::process_event(), BJetModule::process_event(), Forward_pi0s::process_event(), RICHEvaluator::process_event(), DetermineTowerBackground::process_event(), QAG4SimulationTracking::process_event(), RICHParticleID::process_event(), Photons::process_event(), HFMLTriggerOccupancy::process_event(), TPCDataStreamEmulator::process_event(), Proto3ShowerCalib::process_event(), HFMLTriggerInterface::process_event(), Proto2ShowerCalib::process_event(), SigmaTimingNtuple::process_event(), QAG4Decayer::process_event(), TruthPhotonJet::process_event(), MBDStudy::process_event(), MbdDigitization::process_event(), hijbkg_upc::process_event(), TPCMLDataInterface::process_event(), BBCStudy::process_event(), truthDecayTester::process_event(), QAG4SimulationTruthDecay::process_event(), PHG4ScoringManager::process_event(), TruthCaloTree::process_event(), ExampleAnalysisModule::process_event(), ElectronID::process_event(), PhotonJet::process_event(), VtxTest::process_event(), jetrtrack::process_event(), CaloWaveFormSim::process_g4hits(), SoftLeptonTaggingTruth::process_Spectrum(), TrackClusterEvaluator::processRecoTracks(), TrackClusterEvaluator::processTruthTracks(), PHG4TrackFastSim::PseudoPatternRecognition(), and pythiaEMCalAna::withinAcceptance().
virtual int PHG4Particle::get_track_id () const inline virtual
Reimplemented in PHG4Particlev2.
Definition at line 29 of file PHG4Particle.h.
View newest version in sPHENIX GitHub at line 29 of file PHG4Particle.h
Referenced by PHG4DSTReader::add_particle(), PHG4TruthInfoContainer::AddParticle(), pythiaEMCalAna::addPrimaryFromGeant(), SvtxHitEval::all_hits_from(), SvtxTrackEval::all_tracks_from(), PHTruthClustering::all_truth_clusters(), SvtxTruthEval::all_truth_clusters(), PHTruthClustering::all_truth_hits(), BaseTruthEval::are_same_particle(), SvtxTrackEval::best_track_from(), EMCalCalib::eval_photon(), EMCalAna::eval_trk(), QAG4SimulationMicromegas::evaluate_clusters(), QAG4SimulationTpc::evaluate_clusters(), PHG4TrackFastSimEval::fill_track_tree(), AnaSvtxTracksForGenFit::fill_tree(), FastTrackingEval::fill_tree(), GenFitTrackProp::fill_tree(), ActsEvaluator::fillG4Particle(), psTOFTimezeroEval::fillOutputNtuples(), SvtxEvaluatorHaiwang::fillOutputNtuples(), CaloEvaluator::fillOutputNtuples(), SvtxEvaluator::fillOutputNtuples(), EventEvaluator::fillOutputNtuples(), SvtxTruthEval::FillTruthHitsFromParticleCache(), SvtxTruthRecoTableEval::fillTruthMap(), ElectronID::findMCmatch(), HFTrackEfficiency::findTracks(), BaseTruthEval::get_embed(), VtxTest::get_embed(), TruthConversionEval::get_embed(), JetRecoEval::get_energy_contribution(), TruthJetInput::get_input(), BaseTruthEval::get_primary_shower(), IsolatedTrackAnalysis::getAddTruth(), IsolatedTrackAnalysis::getG4Truth(), dNdEtaINTT::GetRecoClusterInfo(), PHTruthSiliconAssociation::getSiliconClustersFromParticle(), IsolatedTrackAnalysis::getTracks(), DISKinematicsReco::InsertCandidateFromCluster(), BaseTruthEval::is_g4hit_from_particle(), PHG4TruthInfoContainer::is_primary(), SvtxClusterEval::max_truth_cluster_by_energy(), TruthConversionEval::numUnique(), PHG4TruthTrackingAction::PreUserTrackingAction(), psTOFTimezeroEval::printOutputInfo(), SvtxEvaluatorHaiwang::printOutputInfo(), CaloEvaluator::printOutputInfo(), SvtxEvaluator::printOutputInfo(), Conversion::PrintPhotonRecoInfo(), PHTruthTrackSeeding::Process(), MomentumEvaluator::process_event(), TrackingPerformanceCheck::process_event(), BJetModule::process_event(), RICHEvaluator::process_event(), DetermineTowerBackground::process_event(), QAG4SimulationTracking::process_event(), Photons::process_event(), HFMLTriggerInterface::process_event(), SigmaTimingNtuple::process_event(), QAG4Decayer::process_event(), MBDStudy::process_event(), isoCluster::process_event(), BBCStudy::process_event(), PHTruthClustering::process_event(), TruthCaloTree::process_event(), ElectronID::process_event(), pythiaEMCalAna::process_event(), TruthConversionEval::process_event(), MyJetAnalysis::process_event(), EMCalAna::process_event_UpslisonTrig(), CaloWaveFormSim::process_g4hits(), TrackClusterEvaluator::processRecoTracks(), TrackClusterEvaluator::processTruthTracks(), PHG4TrackFastSim::PseudoPatternRecognition(), Conversion::setElectron(), Conversion::setPrimaryPhoton(), Conversion::setRecoTrack(), and Conversion::setRecoTracks().
virtual int PHG4Particle::get_vtx_id () const inline virtual
Reimplemented in PHG4Particlev2.
Definition at line 30 of file PHG4Particle.h.
View newest version in sPHENIX GitHub at line 30 of file PHG4Particle.h
Referenced by PHG4DSTReader::add_particle(), PHTruthSiliconAssociation::buildTrackSeed(), PHTruthTrackSeeding::buildTrackSeed(), DecayFinder::checkIfCorrectGeant4Particle(), PHG4TruthEventAction::EndOfEventAction(), PHG4TrackFastSimEval::fill_track_tree(), PHG4TrackFastSimEval::fill_vertex_tree(), EventEvaluator::fillOutputNtuples(), KFParticle_truthAndDetTools::fillTruthBranch(), HFTrackEfficiency::findTracks(), SetupDualRICHAnalyzer::get_emission_momentum(), BaseTruthEval::get_vertex(), IsolatedTrackAnalysis::getAddTruth(), pythiaEMCalAna::getG4EndVtx(), TrkrTruthTrackContainerv1::getTruthTrack(), SvtxClusterEval::gtrackid_and_layer_by_nhit(), PHG4TruthTrackingAction::PreUserTrackingAction(), SvtxEvaluatorHaiwang::printOutputInfo(), psTOFTimezeroEval::printOutputInfo(), SvtxEvaluator::printOutputInfo(), PHSiliconTruthTrackSeeding::Process(), MomentumEvaluator::process_event(), PHG4DstCompressReco::process_event(), Proto4ShowerCalib::process_event(), BJetModule::process_event(), RICHEvaluator::process_event(), Proto2ShowerCalib::process_event(), Proto3ShowerCalib::process_event(), SynRadAna::process_event(), QAG4Decayer::process_event(), Proto4TowerCalib::process_event(), QAG4SimulationTruthDecay::process_event(), truthDecayTester::process_event(), singlePhotonClusterAna::process_event(), TruthCaloTree::process_event(), ExampleAnalysisModule::process_event(), VtxTest::process_event(), TruthConversionEval::process_event(), SoftLeptonTaggingTruth::process_Spectrum(), and PHG4TruthEventAction::ProcessShowers().
virtual int PHG4Particle::get_Z () const inline virtual
Reimplemented in PHG4Particlev3.
Definition at line 37 of file PHG4Particle.h.
View newest version in sPHENIX GitHub at line 37 of file PHG4Particle.h
void PHG4Particle::identify (std::ostream & os = std::cout) const override virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from PHObject.
Reimplemented in PHG4Particlev2, PHG4Particlev3, and PHG4Particlev1.
Definition at line 3 of file PHG4Particle.cc.
View newest version in sPHENIX GitHub at line 3 of file PHG4Particle.cc
Referenced by pythiaEMCalAna::addPrimaryFromGeant(), HFTrackEfficiency::findTracks(), SvtxEvaluatorHaiwang::printOutputInfo(), psTOFTimezeroEval::printOutputInfo(), SvtxEvaluator::printOutputInfo(), Conversion::PrintPhotonRecoInfo(), Conversion::printReco(), Conversion::printTruth(), PHSiliconTruthTrackSeeding::Process(), PHTruthTrackSeeding::Process(), PHG4ConsistencyCheck::process_event(), QAG4SimulationUpsilon::process_event(), QAG4SimulationTracking::process_event(), SynRadAna::process_event(), TruthConversionEval::process_event(), SoftLeptonTaggingTruth::process_Spectrum(), and PHG4TrackFastSim::PseudoPatternRecognition().
virtual bool PHG4Particle::isIon () const inline virtual
Reimplemented in PHG4Particlev3.
Definition at line 21 of file PHG4Particle.h.
View newest version in sPHENIX GitHub at line 21 of file PHG4Particle.h
Referenced by MBDStudy::process_event(), MbdDigitization::process_event(), and BBCStudy::process_event().
bool PHG4Particle::operator== (const PHG4Particle & p) const
Definition at line 9 of file PHG4Particle.cc.
View newest version in sPHENIX GitHub at line 9 of file PHG4Particle.cc
References get_pid(), get_px(), get_py(), and get_pz().
virtual void PHG4Particle::set_A (const int) inline virtual
Reimplemented in PHG4Particlev3.
Definition at line 54 of file PHG4Particle.h.
View newest version in sPHENIX GitHub at line 54 of file PHG4Particle.h
Referenced by PHG4TruthTrackingAction::AddParticle(), and PHG4IonGun::UpdateParticle().
virtual void PHG4Particle::set_barcode (const int) inline virtual
Reimplemented in PHG4Particlev1.
Definition at line 52 of file PHG4Particle.h.
View newest version in sPHENIX GitHub at line 52 of file PHG4Particle.h
Referenced by PHG4TruthTrackingAction::PreUserTrackingAction(), and HepMCNodeReader::process_event().
virtual void PHG4Particle::set_e (const double) inline virtual
Reimplemented in PHG4Particlev2.
Definition at line 50 of file PHG4Particle.h.
View newest version in sPHENIX GitHub at line 50 of file PHG4Particle.h
Referenced by PHG4TruthTrackingAction::AddParticle(), PHG4ParticleGenerator::process_event(), CosmicSpray::process_event(), and PHG4SimpleEventGenerator::process_event().
virtual void PHG4Particle::set_ExcitEnergy (const double) inline virtual
Reimplemented in PHG4Particlev3.
Definition at line 58 of file PHG4Particle.h.
View newest version in sPHENIX GitHub at line 58 of file PHG4Particle.h
Referenced by PHG4IonGun::UpdateParticle().
virtual void PHG4Particle::set_IonCharge (const double) inline virtual
Reimplemented in PHG4Particlev3.
Definition at line 57 of file PHG4Particle.h.
View newest version in sPHENIX GitHub at line 57 of file PHG4Particle.h
virtual void PHG4Particle::set_name (const std::string &) inline virtual
Reimplemented in PHG4Particlev1.
Definition at line 45 of file PHG4Particle.h.
View newest version in sPHENIX GitHub at line 45 of file PHG4Particle.h
Referenced by PHG4TruthTrackingAction::AddParticle(), CosmicSpray::process_event(), PHG4SimpleEventGenerator::process_event(), PHG4ParticleGeneratorBase::SetParticleId(), and PHG4IonGun::UpdateParticle().
virtual void PHG4Particle::set_NumCharge (const int) inline virtual
Reimplemented in PHG4Particlev3.
Definition at line 56 of file PHG4Particle.h.
View newest version in sPHENIX GitHub at line 56 of file PHG4Particle.h
Referenced by PHG4IonGun::UpdateParticle().
virtual void PHG4Particle::set_parent_id (const int) inline virtual
Reimplemented in PHG4Particlev2.
Definition at line 43 of file PHG4Particle.h.
View newest version in sPHENIX GitHub at line 43 of file PHG4Particle.h
Referenced by PHG4TruthTrackingAction::AddParticle(), PHG4TruthTrackingAction::PreUserTrackingAction(), CosmicSpray::process_event(), and PHG4SimpleEventGenerator::process_event().
virtual void PHG4Particle::set_pid (const int) inline virtual
Reimplemented in PHG4Particlev1.
Definition at line 46 of file PHG4Particle.h.
View newest version in sPHENIX GitHub at line 46 of file PHG4Particle.h
Referenced by PHG4ParticleGeneratorBase::AddParticle(), PHG4TruthTrackingAction::AddParticle(), PHG4InEventReadBack::process_event(), CosmicSpray::process_event(), HepMCNodeReader::process_event(), PHG4SimpleEventGenerator::process_event(), PHG4ParticleGeneratorBase::SetParticleId(), and PHG4IonGun::UpdateParticle().
virtual void PHG4Particle::set_primary_id (const int) inline virtual
Reimplemented in PHG4Particlev2.
Definition at line 44 of file PHG4Particle.h.
View newest version in sPHENIX GitHub at line 44 of file PHG4Particle.h
Referenced by PHG4TruthTrackingAction::AddParticle(), and PHG4TruthTrackingAction::PreUserTrackingAction().
virtual void PHG4Particle::set_px (const double) inline virtual
Reimplemented in PHG4Particlev1.
Definition at line 47 of file PHG4Particle.h.
View newest version in sPHENIX GitHub at line 47 of file PHG4Particle.h
Referenced by PHG4ParticleGeneratorBase::AddParticle(), PHG4TruthTrackingAction::AddParticle(), PHG4InEventReadBack::process_event(), PHG4ParticleGenerator::process_event(), CosmicSpray::process_event(), HepMCNodeReader::process_event(), PHG4SimpleEventGenerator::process_event(), and PHG4IonGun::UpdateParticle().
virtual void PHG4Particle::set_py (const double) inline virtual
Reimplemented in PHG4Particlev1.
Definition at line 48 of file PHG4Particle.h.
View newest version in sPHENIX GitHub at line 48 of file PHG4Particle.h
Referenced by PHG4ParticleGeneratorBase::AddParticle(), PHG4TruthTrackingAction::AddParticle(), PHG4InEventReadBack::process_event(), PHG4ParticleGenerator::process_event(), CosmicSpray::process_event(), HepMCNodeReader::process_event(), PHG4SimpleEventGenerator::process_event(), and PHG4IonGun::UpdateParticle().
virtual void PHG4Particle::set_pz (const double) inline virtual
Reimplemented in PHG4Particlev1.
Definition at line 49 of file PHG4Particle.h.
View newest version in sPHENIX GitHub at line 49 of file PHG4Particle.h
Referenced by PHG4ParticleGeneratorBase::AddParticle(), PHG4TruthTrackingAction::AddParticle(), PHG4InEventReadBack::process_event(), PHG4ParticleGenerator::process_event(), CosmicSpray::process_event(), HepMCNodeReader::process_event(), PHG4SimpleEventGenerator::process_event(), and PHG4IonGun::UpdateParticle().
virtual void PHG4Particle::set_track_id (const int) inline virtual
Reimplemented in PHG4Particlev2.
Definition at line 41 of file PHG4Particle.h.
View newest version in sPHENIX GitHub at line 41 of file PHG4Particle.h
Referenced by PHG4TruthTrackingAction::AddParticle(), CosmicSpray::process_event(), and PHG4SimpleEventGenerator::process_event().
virtual void PHG4Particle::set_vtx_id (const int) inline virtual
Reimplemented in PHG4Particlev2.
Definition at line 42 of file PHG4Particle.h.
View newest version in sPHENIX GitHub at line 42 of file PHG4Particle.h
Referenced by PHG4TruthTrackingAction::AddParticle(), CosmicSpray::process_event(), and PHG4SimpleEventGenerator::process_event().
virtual void PHG4Particle::set_Z (const int) inline virtual
Reimplemented in PHG4Particlev3.
Definition at line 55 of file PHG4Particle.h.
View newest version in sPHENIX GitHub at line 55 of file PHG4Particle.h
Referenced by PHG4TruthTrackingAction::AddParticle(), and PHG4IonGun::UpdateParticle().
The documentation for this class was generated from the following files:
coresoftware/blob/master/simulation/g4simulation/g4main/PHG4Particle.h
coresoftware/blob/master/simulation/g4simulation/g4main/PHG4Particle.cc