Analysis Software: pi0Efficiency Class Reference
pi0Efficiency Class Reference
#include <analysis/blob/master/pi0Efficiency/src/pi0Efficiency.h>
Public Member Functions
pi0Efficiency (const std::string &name, const std::string &outName)
~pi0Efficiency () override
int Init (PHCompositeNode *topNode) override
int InitRun (PHCompositeNode *topNode) override
int process_event (PHCompositeNode *topNode) override
int ResetEvent (PHCompositeNode *topNode) override
Clean up internals after each event.
int EndRun (const int runnumber) override
Called at the end of each run.
int End (PHCompositeNode *topNode) override
Called at the end of all processing.
int Reset (PHCompositeNode *) override
Reset.
void Print (const std::string &what="ALL") const override
Public Member Functions inherited from SubsysReco
~SubsysReco () override
void Print (const std::string &="ALL") const override
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Private Member Functions
int getEtaBin (float eta)
float getEta (PHG4Particle *particle)
Private Attributes
std::string OutFile
TH3F * ePi0InvMassEcut [nEtaBins]
TH1F * clusterE
TH1F * photonE
TH1F * prim_pi0_E [nEtaBins]
TH2F * pi0EScale
TH2F * unmatchedLocale
TH1F * unmatchedE
TH2F * truthPi0EDeltaR
TH2F * truthPi0EAsym
TH1F * hMassRat
Fun4AllHistoManager * hm = nullptr
TFile * out
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = std::numeric_limits<int>::max() - 10
}
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Detailed Description
Definition at line 39 of file pi0Efficiency.h.
View newest version in sPHENIX GitHub at line 39 of file pi0Efficiency.h
Constructor & Destructor Documentation
pi0Efficiency::pi0Efficiency (const std::string & name, const std::string & outName)
Definition at line 56 of file pi0Efficiency.cc.
View newest version in sPHENIX GitHub at line 56 of file pi0Efficiency.cc
References clusterE, ePi0InvMassEcut, hMassRat, i, j, nEtaBins, photonE, pi0EScale, prim_pi0_E, truthPi0EAsym, and truthPi0EDeltaR.
pi0Efficiency::~pi0Efficiency () override
Definition at line 81 of file pi0Efficiency.cc.
View newest version in sPHENIX GitHub at line 81 of file pi0Efficiency.cc
Member Function Documentation
int pi0Efficiency::End (PHCompositeNode * topNode) override virtual
Called at the end of all processing.
unmatchedLocale -> Write();
Reimplemented from SubsysReco.
Definition at line 519 of file pi0Efficiency.cc.
View newest version in sPHENIX GitHub at line 519 of file pi0Efficiency.cc
References cd(), clusterE, ePi0InvMassEcut, Fun4AllReturnCodes::EVENT_OK, hMassRat, i, j, nEtaBins, out, photonE, pi0EScale, prim_pi0_E, truthPi0EAsym, truthPi0EDeltaR, and Write().
int pi0Efficiency::EndRun (const int runnumber) override virtual
Called at the end of each run.
Reimplemented from SubsysReco.
Definition at line 512 of file pi0Efficiency.cc.
View newest version in sPHENIX GitHub at line 512 of file pi0Efficiency.cc
References Fun4AllReturnCodes::EVENT_OK.
float pi0Efficiency::getEta (PHG4Particle * particle) private
Definition at line 556 of file pi0Efficiency.cc.
View newest version in sPHENIX GitHub at line 556 of file pi0Efficiency.cc
References merge_hashes::p.
Referenced by process_event().
int pi0Efficiency::getEtaBin (float eta) private
Definition at line 566 of file pi0Efficiency.cc.
View newest version in sPHENIX GitHub at line 566 of file pi0Efficiency.cc
References i, and nEtaBins.
Referenced by process_event().
int pi0Efficiency::Init (PHCompositeNode *) override virtual
Called during initialization. Typically this is where you can book histograms, and e.g. register them to Fun4AllServer (so they can be output to file using Fun4AllServer::dumpHistos() method).
Reimplemented from SubsysReco.
Definition at line 87 of file pi0Efficiency.cc.
View newest version in sPHENIX GitHub at line 87 of file pi0Efficiency.cc
References clusterE, ePi0InvMassEcut, Fun4AllReturnCodes::EVENT_OK, hm, hMassRat, i, Fun4AllServer::instance(), j, nEtaBins, out, OutFile, photonE, pi0EScale, prim_pi0_E, Print(), truthPi0EAsym, and truthPi0EDeltaR.
int pi0Efficiency::InitRun (PHCompositeNode *) override virtual
Called for first event when run number is known. Typically this is where you may want to fetch data from database, because you know the run number.
Reimplemented from SubsysReco.
Definition at line 138 of file pi0Efficiency.cc.
View newest version in sPHENIX GitHub at line 138 of file pi0Efficiency.cc
References Fun4AllReturnCodes::EVENT_OK.
void pi0Efficiency::Print (const std::string & what = "ALL") const override virtual
Print out some info about this module.
Parameters
what can be used to specify what to print exactly.
Reimplemented from Fun4AllBase.
Definition at line 551 of file pi0Efficiency.cc.
View newest version in sPHENIX GitHub at line 551 of file pi0Efficiency.cc
Referenced by Init().
int pi0Efficiency::process_event (PHCompositeNode *) override virtual
Called for each event. This is where you do the real work.
Reimplemented from SubsysReco.
Definition at line 145 of file pi0Efficiency.cc.
View newest version in sPHENIX GitHub at line 145 of file pi0Efficiency.cc
References Fun4AllReturnCodes::ABORTEVENT, assert, GlobalVertexMap::begin(), clusterE, physmon_track_finding_ttbar::deltaR, GlobalVertexMap::empty(), ePi0InvMassEcut, Fun4AllReturnCodes::EVENT_OK, Fill(), GlobalVertex::get_x(), GlobalVertex::get_y(), GlobalVertex::get_z(), RawClusterUtility::GetECoreVec(), getEta(), getEtaBin(), PHG4TruthInfoContainer::GetPrimaryParticleRange(), PHG4TruthInfoContainer::GetSecondaryParticleRange(), hMassRat, i, j, Acts::UnitConstants::min, nEtaBins, photonE, PHWHERE, pi0EScale, prim_pi0_E, truthPi0EAsym, and truthPi0EDeltaR.
int pi0Efficiency::Reset (PHCompositeNode * topNode) override virtual
Reset.
Reimplemented from SubsysReco.
Definition at line 544 of file pi0Efficiency.cc.
View newest version in sPHENIX GitHub at line 544 of file pi0Efficiency.cc
References Fun4AllReturnCodes::EVENT_OK.
int pi0Efficiency::ResetEvent (PHCompositeNode * topNode) override virtual
Clean up internals after each event.
Reimplemented from SubsysReco.
Definition at line 506 of file pi0Efficiency.cc.
View newest version in sPHENIX GitHub at line 506 of file pi0Efficiency.cc
References Fun4AllReturnCodes::EVENT_OK.
Member Data Documentation
TH1F* pi0Efficiency::clusterE private
Definition at line 76 of file pi0Efficiency.h.
View newest version in sPHENIX GitHub at line 76 of file pi0Efficiency.h
Referenced by End(), Init(), pi0Efficiency(), and process_event().
TH3F* pi0Efficiency::ePi0InvMassEcut[nEtaBins] private
Definition at line 75 of file pi0Efficiency.h.
View newest version in sPHENIX GitHub at line 75 of file pi0Efficiency.h
Referenced by End(), Init(), pi0Efficiency(), and process_event().
Fun4AllHistoManager* pi0Efficiency::hm = nullptr private
Definition at line 86 of file pi0Efficiency.h.
View newest version in sPHENIX GitHub at line 86 of file pi0Efficiency.h
Referenced by Init().
TH1F* pi0Efficiency::hMassRat private
Definition at line 84 of file pi0Efficiency.h.
View newest version in sPHENIX GitHub at line 84 of file pi0Efficiency.h
Referenced by End(), Init(), pi0Efficiency(), and process_event().
TFile* pi0Efficiency::out private
Definition at line 87 of file pi0Efficiency.h.
View newest version in sPHENIX GitHub at line 87 of file pi0Efficiency.h
Referenced by End(), and Init().
std::string pi0Efficiency::OutFile private
Definition at line 73 of file pi0Efficiency.h.
View newest version in sPHENIX GitHub at line 73 of file pi0Efficiency.h
Referenced by Init().
TH1F* pi0Efficiency::photonE private
Definition at line 77 of file pi0Efficiency.h.
View newest version in sPHENIX GitHub at line 77 of file pi0Efficiency.h
Referenced by End(), Init(), pi0Efficiency(), and process_event().
TH2F* pi0Efficiency::pi0EScale private
Definition at line 79 of file pi0Efficiency.h.
View newest version in sPHENIX GitHub at line 79 of file pi0Efficiency.h
Referenced by End(), Init(), pi0Efficiency(), and process_event().
TH1F* pi0Efficiency::prim_pi0_E[nEtaBins] private
Definition at line 78 of file pi0Efficiency.h.
View newest version in sPHENIX GitHub at line 78 of file pi0Efficiency.h
Referenced by End(), Init(), pi0Efficiency(), and process_event().
TH2F* pi0Efficiency::truthPi0EAsym private
Definition at line 83 of file pi0Efficiency.h.
View newest version in sPHENIX GitHub at line 83 of file pi0Efficiency.h
Referenced by End(), Init(), pi0Efficiency(), and process_event().
TH2F* pi0Efficiency::truthPi0EDeltaR private
Definition at line 82 of file pi0Efficiency.h.
View newest version in sPHENIX GitHub at line 82 of file pi0Efficiency.h
Referenced by End(), Init(), pi0Efficiency(), and process_event().
TH1F* pi0Efficiency::unmatchedE private
Definition at line 81 of file pi0Efficiency.h.
View newest version in sPHENIX GitHub at line 81 of file pi0Efficiency.h
TH2F* pi0Efficiency::unmatchedLocale private
Definition at line 80 of file pi0Efficiency.h.
View newest version in sPHENIX GitHub at line 80 of file pi0Efficiency.h
The documentation for this class was generated from the following files:
analysis/blob/master/pi0Efficiency/src/pi0Efficiency.h
analysis/blob/master/pi0Efficiency/src/pi0Efficiency.cc