Analysis Software: coresoftware/blob/master/calibrations/tpc/generator/generate_distortion_map.C File Reference
generate_distortion_map.C File Reference
#include "AnnularFieldSim.h"
#include "TTree.h"
#include "TCanvas.h"
Functions
AnnularFieldSim * SetupDefaultSphenixTpc (bool twinMe=false, bool useSpacecharge=true)
AnnularFieldSim * SetupDigitalCurrentSphenixTpc (bool twinMe=false, bool useSpacecharge=true)
void TestSpotDistortion (AnnularFieldSim *t)
void SurveyFiles (TFileCollection *filelist)
void generate_distortion_map (const char *inputname, const char *gainName, const char *outputname, const char *ibfName, const char *primName, bool hasSpacecharge=true, bool isAdc=false, int nSteps=500, bool scanSteps=false)
void generate_distortion_map (const char *inputpattern="./evgeny_apr/Smooth*.root", const char *outputfilebase="./apr07_maps/apr07", bool hasSpacecharge=true, bool isDigitalCurrent=false, int nSteps=500)
Variables
char field_string [200]
char lookup_string [200]
Function Documentation
void generate_distortion_map (const char * inputname, const char * gainName, const char * outputname, const char * ibfName, const char * primName, bool hasSpacecharge = true, bool isAdc = false, int nSteps = 500, bool scanSteps = false)
Definition at line 19 of file generate_distortion_map.C.
View newest version in sPHENIX GitHub at line 19 of file generate_distortion_map.C
References Data, AnnularFieldSim::GenerateSeparateDistortionMaps(), AnnularFieldSim::GetInnerEdge(), AnnularFieldSim::GetOuterEdge(), i, infile, AnnularFieldSim::load_digital_current(), AnnularFieldSim::load_spacecharge(), AnnularFieldSim::PlotFieldSlices(), AnnularFieldSim::populate_fieldmap(), Acts::Test::pos, printf(), SetupDefaultSphenixTpc(), and AnnularFieldSim::twin.
void generate_distortion_map (const char * inputpattern = "./evgeny_apr/Smooth*.root", const char * outputfilebase = "./apr07_maps/apr07", bool hasSpacecharge = true, bool isDigitalCurrent = false, int nSteps = 500)
Definition at line 104 of file generate_distortion_map.C.
View newest version in sPHENIX GitHub at line 104 of file generate_distortion_map.C
References field_string, i, infile, j, lookup_string, Acts::Test::pos, printf(), and SetupDefaultSphenixTpc().
AnnularFieldSim * SetupDefaultSphenixTpc (bool twinMe = false, bool useSpacecharge = true)
Definition at line 238 of file generate_distortion_map.C.
View newest version in sPHENIX GitHub at line 238 of file generate_distortion_map.C
References AnnularFieldSim::borrow_epartial_from(), AnnularFieldSim::borrow_rossegger(), field_string, AnnularFieldSim::FromFile, AnnularFieldSim::green, AnnularFieldSim::load3dBfield(), AnnularFieldSim::load_phislice_lookup(), AnnularFieldSim::load_rossegger(), AnnularFieldSim::loadEfield(), lookup_string, AnnularFieldSim::NoSpacecharge, nphi, nz, AnnularFieldSim::PhiSlice, AnnularFieldSim::populate_lookup(), printf(), AnnularFieldSim::save_phislice_lookup(), AnnularFieldSim::set_twin(), AnnularFieldSim::setFlatFields(), and AnnularFieldSim::UpdateEveryN().
Referenced by generate_distortion_map().
AnnularFieldSim * SetupDigitalCurrentSphenixTpc (bool twinMe = false, bool useSpacecharge = true)
Definition at line 381 of file generate_distortion_map.C.
View newest version in sPHENIX GitHub at line 381 of file generate_distortion_map.C
References AnnularFieldSim::borrow_epartial_from(), AnnularFieldSim::borrow_rossegger(), field_string, AnnularFieldSim::FromFile, AnnularFieldSim::green, AnnularFieldSim::load3dBfield(), AnnularFieldSim::load_phislice_lookup(), AnnularFieldSim::load_rossegger(), AnnularFieldSim::loadEfield(), lookup_string, AnnularFieldSim::NoSpacecharge, nphi, nz, AnnularFieldSim::PhiSlice, AnnularFieldSim::populate_lookup(), printf(), AnnularFieldSim::save_phislice_lookup(), AnnularFieldSim::set_twin(), AnnularFieldSim::setFlatFields(), and AnnularFieldSim::UpdateEveryN().
void SurveyFiles (TFileCollection * filelist)
Definition at line 520 of file generate_distortion_map.C.
View newest version in sPHENIX GitHub at line 520 of file generate_distortion_map.C
References i, infile, integral(), j, and printf().
void TestSpotDistortion (AnnularFieldSim * t)
Definition at line 229 of file generate_distortion_map.C.
View newest version in sPHENIX GitHub at line 229 of file generate_distortion_map.C
References dummy, AnnularFieldSim::GetStepDistortion(), and AnnularFieldSim::twin.
Variable Documentation
char field_string[200]
Definition at line 10 of file generate_distortion_map.C.
View newest version in sPHENIX GitHub at line 10 of file generate_distortion_map.C
Referenced by generate_distortion_map(), SetupDefaultSphenixTpc(), and SetupDigitalCurrentSphenixTpc().
char lookup_string[200]
Definition at line 11 of file generate_distortion_map.C.
View newest version in sPHENIX GitHub at line 11 of file generate_distortion_map.C
Referenced by generate_distortion_map(), SetupDefaultSphenixTpc(), and SetupDigitalCurrentSphenixTpc().