Analysis Software: oncsSub_idtpcfeev3 Class Reference
oncsSub_idtpcfeev3 Class Reference
#include <online_distribution/blob/master/newbasic/oncsSub_idtpcfeev3.h>
Classes
struct bco_compare
struct gtm_payload
struct sampa_waveform
Public Member Functions
oncsSub_idtpcfeev3 (subevtdata_ptr)
~oncsSub_idtpcfeev3 ()
int iValue (const int ch, const int sample)
SAMPA waveform interfaces.
int iValue (const int, const char *what)
long long lValue (const int channel, const char *what)
Expose the Level 1 trigger and endat taggers.
void dump (OSTREAM &os=COUT)
Public Member Functions inherited from oncsSubevent_w2
oncsSubevent_w2 (subevtdata_ptr)
virtual void gdump (const int how=EVT_HEXADECIMAL, OSTREAM &os=COUT) const
Public Member Functions inherited from oncsSubevent
oncsSubevent (subevtdata_ptr data)
virtual ~oncsSubevent ()
virtual int getLength () const
virtual int getIdentifier () const
get the packet identifier
virtual int getHitFormat () const
get the hit format; in case of unformatted get the encoding scheme.
virtual int getPadding () const
get the number of padding units in the packet data.
virtual int getDataLength () const
get what the name says...
virtual int getStructure () const
get the structure of the packet data; unformatted, hitlist, etc.
virtual int getDebugLength () const
get the length of the debug block
virtual int getErrorLength () const
virtual void identify (OSTREAM &=COUT) const
virtual int setIdentifier (const int newid)
set a new packet identifier
int iValue (const int)
iValue returns the value of a given channel as an int.
int iValue (const int, const char *)
int iValue (const int, const int)
int iValue (const int, const int, const char *)
int iValue (const int channel, const int iy, const int iz)
int iValue (const int channel, const int iy, const int iz, const char *what)
virtual float rValue (const int)
virtual float rValue (const int, const char *)
virtual float rValue (const int, const int)
virtual int getArraylength (const char *)
virtual int fillIntArray (int[], const int, int *, const char *what="")
virtual int fillFloatArray (float[], const int, int *, const char *what="")
fillFloatArray fills an array of floats
virtual int * getIntArray (int *, const char *what="")
virtual float * getFloatArray (int *, const char *what="")
getFloatArray creates and returns an array of floats
virtual int is_pointer_type () const
find out what type (pointer- or data based) packet object we have
virtual int convert ()
convert from pointer- to data based object, if it is already data-based, do nothing.
virtual int copyMe (int[], const int maxlength) const
int setInternalParameter (const int p1=0, const int p2=0, const char *what="")
Public Member Functions inherited from Packet
virtual ~Packet ()
the virtual destructor
virtual double dValue (const int channel)
virtual double dValue (const int channel, const char *what)
virtual double dValue (const int channel, const int iy)
virtual long long lValue (const int channel)
virtual long long lValue (const int channel, const int iy)
virtual long long lValue (const int channel, const int iy, const char *what)
virtual void * pValue (const int)
virtual void * pValue (const int, const char *)
virtual void * pValue (const int, const int)
virtual void identify (std::ostream &os=std::cout) const =0
see below for comments
virtual void fullIdentify (std::ostream &os=std::cout) const
write an indepth identification message to the supplied OSTREAM.
virtual void dump (std::ostream &os=std::cout)=0
virtual void gdump (const int how=EVT_HEXADECIMAL, std::ostream &os=std::cout) const =0
virtual int getCheckSumStatus () const
Protected Types
typedef std::multiset
< sampa_waveform
*, bco_compare > waveform_set
Protected Member Functions
int tpc_decode ()
unsigned short reverseBits (const unsigned short x) const
unsigned short crc16 (const unsigned int fee, const unsigned int index, const int l) const
int find_header (const unsigned int xx, const std::vector< unsigned short > &orig)
int decode_gtm_data (unsigned short gtm[16])
int cacheIterator (const int n)
Protected Member Functions inherited from oncsSubevent_w2
virtual int * decode (int *)
Protected Attributes
int _broken
int _is_decoded
waveform_set waveforms
std::vector< sampa_waveform * > waveform_vector
int _last_requested_element
sampa_waveform * _last_requested_waveform
std::vector< unsigned short > fee_data [MAX_FEECOUNT]
std::vector< gtm_payload * > gtm_data
Static Protected Attributes
static const unsigned short MAGIC_KEY_0 = 0xfe
static const unsigned short MAGIC_KEY_1 = 0x00
static const unsigned short FEE_MAGIC_KEY = 0xba00
static const unsigned short GTM_MAGIC_KEY = 0xbb00
static const unsigned short GTM_LVL1_ACCEPT_MAGIC_KEY = 0xbbf0
static const unsigned short GTM_ENDAT_MAGIC_KEY = 0xbbf1
static const unsigned short MAX_FEECOUNT = 26
static const unsigned short MAX_CHANNELS = 8*32
static const unsigned short HEADER_LENGTH = 7
Detailed Description
Definition at line 11 of file oncsSub_idtpcfeev3.h.
View newest version in sPHENIX GitHub at line 11 of file oncsSub_idtpcfeev3.h
Member Typedef Documentation
typedef std::multiset< sampa_waveform* , bco_compare> oncsSub_idtpcfeev3::waveform_set protected
Definition at line 94 of file oncsSub_idtpcfeev3.h.
View newest version in sPHENIX GitHub at line 94 of file oncsSub_idtpcfeev3.h
Constructor & Destructor Documentation
oncsSub_idtpcfeev3::oncsSub_idtpcfeev3 (subevtdata_ptr data)
Definition at line 11 of file oncsSub_idtpcfeev3.cc.
View newest version in sPHENIX GitHub at line 11 of file oncsSub_idtpcfeev3.cc
References _is_decoded, _last_requested_element, and _last_requested_waveform.
oncsSub_idtpcfeev3::~oncsSub_idtpcfeev3 ()
Definition at line 21 of file oncsSub_idtpcfeev3.cc.
View newest version in sPHENIX GitHub at line 21 of file oncsSub_idtpcfeev3.cc
References gtm_data, waveform_vector, and waveforms.
Member Function Documentation
int oncsSub_idtpcfeev3::cacheIterator (const int n) protected
Definition at line 45 of file oncsSub_idtpcfeev3.cc.
View newest version in sPHENIX GitHub at line 45 of file oncsSub_idtpcfeev3.cc
References _last_requested_element, _last_requested_waveform, i, n, and waveform_vector.
Referenced by iValue().
unsigned short oncsSub_idtpcfeev3::crc16 (const unsigned int fee, const unsigned int index, const int l) const protected
Definition at line 562 of file oncsSub_idtpcfeev3.cc.
View newest version in sPHENIX GitHub at line 562 of file oncsSub_idtpcfeev3.cc
References fee_data, i, k, reverseBits(), and ambiguity_solver_full_chain::x.
Referenced by tpc_decode().
int oncsSub_idtpcfeev3::decode_gtm_data (unsigned short gtm[16]) protected
Definition at line 64 of file oncsSub_idtpcfeev3.cc.
View newest version in sPHENIX GitHub at line 64 of file oncsSub_idtpcfeev3.cc
References oncsSub_idtpcfeev3::gtm_payload::bco, oncsSub_idtpcfeev3::gtm_payload::endat_count, gtm_data, GTM_ENDAT_MAGIC_KEY, GTM_LVL1_ACCEPT_MAGIC_KEY, oncsSub_idtpcfeev3::gtm_payload::is_endat, oncsSub_idtpcfeev3::gtm_payload::is_lvl1, oncsSub_idtpcfeev3::gtm_payload::last_bco, oncsSub_idtpcfeev3::gtm_payload::lvl1_count, oncsSub_idtpcfeev3::gtm_payload::modebits, and oncsSub_idtpcfeev3::gtm_payload::pkt_type.
Referenced by tpc_decode().
void oncsSub_idtpcfeev3::dump (OSTREAM & os = COUT) virtual
Reimplemented from oncsSubevent_w2.
Definition at line 491 of file oncsSub_idtpcfeev3.cc.
View newest version in sPHENIX GitHub at line 491 of file oncsSub_idtpcfeev3.cc
References i, oncsSubevent::identify(), iValue(), j, k, lValue(), and tpc_decode().
int oncsSub_idtpcfeev3::find_header (const unsigned int xx, const std::vector< unsigned short > & orig) protected
Definition at line 441 of file oncsSub_idtpcfeev3.cc.
View newest version in sPHENIX GitHub at line 441 of file oncsSub_idtpcfeev3.cc
References HEADER_LENGTH, i, MAGIC_KEY_0, MAGIC_KEY_1, and Acts::Test::pos.
Referenced by tpc_decode().
int oncsSub_idtpcfeev3::iValue (const int ch, const int sample) virtual
SAMPA waveform interfaces.
Implements Packet.
Definition at line 328 of file oncsSub_idtpcfeev3.cc.
View newest version in sPHENIX GitHub at line 328 of file oncsSub_idtpcfeev3.cc
References _last_requested_waveform, cacheIterator(), Acts::UnitConstants::m, and tpc_decode().
Referenced by dump().
int oncsSub_idtpcfeev3::iValue (const int , const char *) virtual
with the "what" parameter you can decide which aspect of the data you want to see (for devices which have more than one)
Implements Packet.
Definition at line 347 of file oncsSub_idtpcfeev3.cc.
View newest version in sPHENIX GitHub at line 347 of file oncsSub_idtpcfeev3.cc
References _last_requested_waveform, cacheIterator(), channel(), MAX_FEECOUNT, tpc_decode(), and waveform_vector.
long long oncsSub_idtpcfeev3::lValue (const int channel, const char * what) virtual
Expose the Level 1 trigger and endat taggers.
Reimplemented from Packet.
Definition at line 250 of file oncsSub_idtpcfeev3.cc.
View newest version in sPHENIX GitHub at line 250 of file oncsSub_idtpcfeev3.cc
References gtm_data, i, n, and tpc_decode().
Referenced by dump().
unsigned short oncsSub_idtpcfeev3::reverseBits (const unsigned short x) const protected
Definition at line 549 of file oncsSub_idtpcfeev3.cc.
View newest version in sPHENIX GitHub at line 549 of file oncsSub_idtpcfeev3.cc
References n, and ambiguity_solver_full_chain::x.
Referenced by crc16().
int oncsSub_idtpcfeev3::tpc_decode () protected
Definition at line 106 of file oncsSub_idtpcfeev3.cc.
View newest version in sPHENIX GitHub at line 106 of file oncsSub_idtpcfeev3.cc
References _is_decoded, oncsSub_idtpcfeev3::sampa_waveform::adc_length, oncsSub_idtpcfeev3::sampa_waveform::bx_timestamp, oncsSub_idtpcfeev3::sampa_waveform::channel, oncsSub_idtpcfeev3::sampa_waveform::checksum, crc16(), subevt_data::data, decode_gtm_data(), oncsSub_idtpcfeev3::sampa_waveform::fee, fee_data, FEE_MAGIC_KEY, find_header(), oncsSubevent::getLength(), oncsSubevent::getPadding(), GTM_MAGIC_KEY, HEADER_LENGTH, i, index, it, MAX_FEECOUNT, oncsSub_idtpcfeev3::sampa_waveform::pkt_length, Acts::Test::pos, oncsSub_idtpcfeev3::sampa_waveform::sampa_address, oncsSub_idtpcfeev3::sampa_waveform::sampa_channel, SEVTHEADERLENGTH, size, oncsSubevent::SubeventHdr, oncsSub_idtpcfeev3::sampa_waveform::valid, oncsSub_idtpcfeev3::sampa_waveform::waveform, waveform_vector, waveforms, and while().
Referenced by dump(), iValue(), and lValue().
Member Data Documentation
int oncsSub_idtpcfeev3::_broken protected
Definition at line 52 of file oncsSub_idtpcfeev3.h.
View newest version in sPHENIX GitHub at line 52 of file oncsSub_idtpcfeev3.h
int oncsSub_idtpcfeev3::_is_decoded protected
Definition at line 54 of file oncsSub_idtpcfeev3.h.
View newest version in sPHENIX GitHub at line 54 of file oncsSub_idtpcfeev3.h
Referenced by oncsSub_idtpcfeev3(), and tpc_decode().
int oncsSub_idtpcfeev3::_last_requested_element protected
Definition at line 104 of file oncsSub_idtpcfeev3.h.
View newest version in sPHENIX GitHub at line 104 of file oncsSub_idtpcfeev3.h
Referenced by cacheIterator(), and oncsSub_idtpcfeev3().
sampa_waveform* oncsSub_idtpcfeev3::_last_requested_waveform protected
Definition at line 105 of file oncsSub_idtpcfeev3.h.
View newest version in sPHENIX GitHub at line 105 of file oncsSub_idtpcfeev3.h
Referenced by cacheIterator(), iValue(), and oncsSub_idtpcfeev3().
std::vector<unsigned short> oncsSub_idtpcfeev3::fee_data[MAX_FEECOUNT] protected
Definition at line 107 of file oncsSub_idtpcfeev3.h.
View newest version in sPHENIX GitHub at line 107 of file oncsSub_idtpcfeev3.h
Referenced by crc16(), and tpc_decode().
const unsigned short oncsSub_idtpcfeev3::FEE_MAGIC_KEY = 0xba00 static protected
Definition at line 36 of file oncsSub_idtpcfeev3.h.
View newest version in sPHENIX GitHub at line 36 of file oncsSub_idtpcfeev3.h
Referenced by tpc_decode().
std::vector<gtm_payload *> oncsSub_idtpcfeev3::gtm_data protected
Definition at line 109 of file oncsSub_idtpcfeev3.h.
View newest version in sPHENIX GitHub at line 109 of file oncsSub_idtpcfeev3.h
Referenced by decode_gtm_data(), lValue(), and ~oncsSub_idtpcfeev3().
const unsigned short oncsSub_idtpcfeev3::GTM_ENDAT_MAGIC_KEY = 0xbbf1 static protected
Definition at line 39 of file oncsSub_idtpcfeev3.h.
View newest version in sPHENIX GitHub at line 39 of file oncsSub_idtpcfeev3.h
Referenced by decode_gtm_data().
const unsigned short oncsSub_idtpcfeev3::GTM_LVL1_ACCEPT_MAGIC_KEY = 0xbbf0 static protected
Definition at line 38 of file oncsSub_idtpcfeev3.h.
View newest version in sPHENIX GitHub at line 38 of file oncsSub_idtpcfeev3.h
Referenced by decode_gtm_data().
const unsigned short oncsSub_idtpcfeev3::GTM_MAGIC_KEY = 0xbb00 static protected
Definition at line 37 of file oncsSub_idtpcfeev3.h.
View newest version in sPHENIX GitHub at line 37 of file oncsSub_idtpcfeev3.h
Referenced by tpc_decode().
const unsigned short oncsSub_idtpcfeev3::HEADER_LENGTH = 7 static protected
Definition at line 43 of file oncsSub_idtpcfeev3.h.
View newest version in sPHENIX GitHub at line 43 of file oncsSub_idtpcfeev3.h
Referenced by find_header(), and tpc_decode().
const unsigned short oncsSub_idtpcfeev3::MAGIC_KEY_0 = 0xfe static protected
Definition at line 33 of file oncsSub_idtpcfeev3.h.
View newest version in sPHENIX GitHub at line 33 of file oncsSub_idtpcfeev3.h
Referenced by find_header().
const unsigned short oncsSub_idtpcfeev3::MAGIC_KEY_1 = 0x00 static protected
Definition at line 34 of file oncsSub_idtpcfeev3.h.
View newest version in sPHENIX GitHub at line 34 of file oncsSub_idtpcfeev3.h
Referenced by find_header().
const unsigned short oncsSub_idtpcfeev3::MAX_CHANNELS = 8*32 static protected
Definition at line 42 of file oncsSub_idtpcfeev3.h.
View newest version in sPHENIX GitHub at line 42 of file oncsSub_idtpcfeev3.h
const unsigned short oncsSub_idtpcfeev3::MAX_FEECOUNT = 26 static protected
Definition at line 41 of file oncsSub_idtpcfeev3.h.
View newest version in sPHENIX GitHub at line 41 of file oncsSub_idtpcfeev3.h
Referenced by iValue(), and tpc_decode().
std::vector<sampa_waveform*> oncsSub_idtpcfeev3::waveform_vector protected
Definition at line 100 of file oncsSub_idtpcfeev3.h.
View newest version in sPHENIX GitHub at line 100 of file oncsSub_idtpcfeev3.h
Referenced by cacheIterator(), iValue(), tpc_decode(), and ~oncsSub_idtpcfeev3().
waveform_set oncsSub_idtpcfeev3::waveforms protected
Definition at line 97 of file oncsSub_idtpcfeev3.h.
View newest version in sPHENIX GitHub at line 97 of file oncsSub_idtpcfeev3.h
Referenced by tpc_decode(), and ~oncsSub_idtpcfeev3().
The documentation for this class was generated from the following files:
online_distribution/blob/master/newbasic/oncsSub_idtpcfeev3.h
online_distribution/blob/master/newbasic/oncsSub_idtpcfeev3.cc