Analysis Software: Acts::ConstVectorMultiTrajectory Exception Reference
Acts::ConstVectorMultiTrajectory Exception Reference final
#include <acts/blob/sPHENIX/Core/include/Acts/EventData/VectorMultiTrajectory.hpp>
Public Member Functions
ConstVectorMultiTrajectory ()=default
ConstVectorMultiTrajectory (const ConstVectorMultiTrajectory &other)
Statistics statistics () const
ConstTrackStateProxy::Parameters parameters_impl (IndexType parIdx) const
ConstTrackStateProxy::Covariance covariance_impl (IndexType parIdx) const
ConstTrackStateProxy::Covariance jacobian_impl (IndexType istate) const
template<size_t measdim>
ConstTrackStateProxy::Measurement
< measdim > measurement_impl (IndexType istate) const
template<size_t measdim>
ConstTrackStateProxy::MeasurementCovariance
< measdim > measurementCovariance_impl (IndexType istate) const
constexpr bool has_impl (HashedString key, IndexType istate) const
IndexType size_impl () const
std::any component_impl (HashedString key, IndexType istate) const
constexpr bool hasColumn_impl (HashedString key) const
Public Member Functions inherited from Acts::detail_vmt::VectorMultiTrajectoryBase
template<typename T >
Statistics statistics (T &instance) const
IndexType calibratedSize_impl (IndexType istate) const
SourceLink getUncalibratedSourceLink_impl (IndexType istate) const
const Surface * referenceSurface_impl (IndexType istate) const
Public Member Functions inherited from Acts::MultiTrajectory< derived_t >
ConstTrackStateProxy getTrackState (IndexType istate) const
template<bool RO = ReadOnly, typename = std::enable_if_t<!RO>>
TrackStateProxy getTrackState (IndexType istate)
template<typename F >
void visitBackwards (IndexType iendpoint, F &&callable) const
auto reverseTrackStateRange (IndexType iendpoint) const
template<bool RO = ReadOnly, typename = std::enable_if_t<!RO>>
auto reverseTrackStateRange (IndexType iendpoint)
auto forwardTrackStateRange (IndexType istartpoint) const
template<bool RO = ReadOnly, typename = std::enable_if_t<!RO>>
auto forwardTrackStateRange (IndexType istartpoint)
template<typename F , bool RO = ReadOnly, typename = std::enable_if_t<!RO>>
void applyBackwards (IndexType iendpoint, F &&callable)
auto && convertToReadOnly () const
template<bool RO = ReadOnly, typename = std::enable_if_t<!RO>>
constexpr void clear ()
Clear the MultiTrajectory. Leaves the underlying storage untouched.
constexpr IndexType size () const
Returns the number of track states contained.
template<bool RO = ReadOnly, typename = std::enable_if_t<!RO>>
constexpr IndexType addTrackState (TrackStatePropMask mask=TrackStatePropMask::All, IndexType iprevious=kInvalid)
template<typename T , bool RO = ReadOnly, typename = std::enable_if_t<!RO>>
constexpr void addColumn (const std::string &key)
constexpr bool hasColumn (HashedString key) const
Private Attributes
friend MultiTrajectory< ConstVectorMultiTrajectory >
Additional Inherited Members
Public Types inherited from Acts::MultiTrajectory< derived_t >
using Derived = derived_t
using ConstTrackStateProxy = detail_lt::TrackStateProxy< Derived, MeasurementSizeMax, true >
using TrackStateProxy = detail_lt::TrackStateProxy< Derived, MeasurementSizeMax, false >
using IndexType = typename TrackStateProxy::IndexType
Static Public Attributes inherited from Acts::MultiTrajectory< derived_t >
static constexpr bool ReadOnly = IsReadOnlyMultiTrajectory<Derived>::value
static constexpr unsigned int MeasurementSizeMax
static constexpr IndexType kInvalid = TrackStateProxy::kInvalid
Protected Member Functions inherited from Acts::detail_vmt::VectorMultiTrajectoryBase
VectorMultiTrajectoryBase ()=default
VectorMultiTrajectoryBase (const VectorMultiTrajectoryBase &other)
VectorMultiTrajectoryBase (VectorMultiTrajectoryBase &&other)=default
Protected Member Functions inherited from Acts::MultiTrajectory< derived_t >
MultiTrajectory ()=default
constexpr bool has (HashedString key, IndexType istate) const
template<HashedString key>
constexpr bool has (IndexType istate) const
template<bool RO = ReadOnly, typename = std::enable_if_t<!RO>>
constexpr
TrackStateProxy::Parameters parameters (IndexType parIdx)
constexpr
ConstTrackStateProxy::Parameters parameters (IndexType parIdx) const
template<bool RO = ReadOnly, typename = std::enable_if_t<!RO>>
constexpr
TrackStateProxy::Covariance covariance (IndexType covIdx)
constexpr
ConstTrackStateProxy::Covariance covariance (IndexType covIdx) const
template<bool RO = ReadOnly, typename = std::enable_if_t<!RO>>
constexpr
TrackStateProxy::Covariance jacobian (IndexType jacIdx)
constexpr
ConstTrackStateProxy::Covariance jacobian (IndexType jacIdx) const
template<size_t measdim, bool RO = ReadOnly, typename = std::enable_if_t<!RO>>
constexpr
TrackStateProxy::template
Measurement< measdim > measurement (IndexType measIdx)
template<size_t measdim>
constexpr
ConstTrackStateProxy::template
Measurement< measdim > measurement (IndexType measIdx) const
template<size_t measdim, bool RO = ReadOnly, typename = std::enable_if_t<!RO>>
constexpr
TrackStateProxy::template
MeasurementCovariance< measdim > measurementCovariance (IndexType covIdx)
template<size_t measdim>
constexpr
ConstTrackStateProxy::template
MeasurementCovariance< measdim > measurementCovariance (IndexType covIdx) const
IndexType calibratedSize (IndexType istate) const
template<bool RO = ReadOnly, typename = std::enable_if_t<!RO>>
constexpr void shareFrom (IndexType iself, IndexType iother, TrackStatePropMask shareSource, TrackStatePropMask shareTarget)
template<bool RO = ReadOnly, typename = std::enable_if_t<!RO>>
constexpr void unset (TrackStatePropMask target, IndexType istate)
template<typename T , HashedString key, bool RO = ReadOnly, typename = std::enable_if_t<!RO>>
constexpr T & component (IndexType istate)
template<typename T , bool RO = ReadOnly, typename = std::enable_if_t<!RO>>
constexpr T & component (HashedString key, IndexType istate)
template<typename T , HashedString key>
constexpr const T & component (IndexType istate) const
template<typename T >
constexpr const T & component (HashedString key, IndexType istate) const
void allocateCalibrated (IndexType istate, size_t measdim)
template<bool RO = ReadOnly, typename = std::enable_if_t<!RO>>
void setUncalibratedSourceLink (IndexType istate, SourceLink sourceLink)
SourceLink getUncalibratedSourceLink (IndexType istate) const
const Surface * referenceSurface (IndexType istate) const
template<bool RO = ReadOnly, typename = std::enable_if_t<!RO>>
void setReferenceSurface (IndexType istate, std::shared_ptr< const Surface > surface)
Static Protected Member Functions inherited from Acts::detail_vmt::VectorMultiTrajectoryBase
template<typename T >
static constexpr bool has_impl (T &instance, HashedString key, IndexType istate)
template<bool EnsureConst, typename T >
static std::any component_impl (T &instance, HashedString key, IndexType istate)
template<typename T >
static constexpr bool hasColumn_impl (T &instance, HashedString key)
Protected Attributes inherited from Acts::detail_vmt::VectorMultiTrajectoryBase
m_previous {other.m_previous}
m_next {other.m_next}
m_params {other.m_params}
m_cov {other.m_cov}
m_meas {other.m_meas}
m_measOffset {other.m_measOffset}
m_measCov {other.m_measCov}
m_measCovOffset {other.m_measCovOffset}
m_jac {other.m_jac}
m_sourceLinks {other.m_sourceLinks}
m_projectors {other.m_projectors}
m_referenceSurfaces
std::vector< IndexData > m_index
index to map track states to the corresponding
std::vector< IndexType > m_previous
std::vector< IndexType > m_next
std::vector< typename
detail_lt::Types< eBoundSize >
::Coefficients > m_params
std::vector< typename
detail_lt::Types< eBoundSize >
::Covariance > m_cov
std::vector< double > m_meas
std::vector
< MultiTrajectoryTraits::IndexType > m_measOffset
std::vector< double > m_measCov
std::vector
< MultiTrajectoryTraits::IndexType > m_measCovOffset
std::vector< typename
detail_lt::Types< eBoundSize >
::Covariance > m_jac
std::vector< std::optional
< SourceLink > > m_sourceLinks
std::vector< ProjectorBitset > m_projectors
std::vector< std::shared_ptr
< const Surface > > m_referenceSurfaces
std::unordered_map
< HashedString,
std::unique_ptr
< detail::DynamicColumnBase > > m_dynamic
Detailed Description
Definition at line 496 of file VectorMultiTrajectory.hpp.
View newest version in sPHENIX GitHub at line 496 of file VectorMultiTrajectory.hpp
Constructor & Destructor Documentation
Acts::ConstVectorMultiTrajectory::ConstVectorMultiTrajectory () default
Acts::ConstVectorMultiTrajectory::ConstVectorMultiTrajectory (const ConstVectorMultiTrajectory & other) inline
Definition at line 506 of file VectorMultiTrajectory.hpp.
View newest version in sPHENIX GitHub at line 506 of file VectorMultiTrajectory.hpp
Member Function Documentation
std::any Acts::ConstVectorMultiTrajectory::component_impl (HashedString key, IndexType istate) const inline
Definition at line 559 of file VectorMultiTrajectory.hpp.
View newest version in sPHENIX GitHub at line 559 of file VectorMultiTrajectory.hpp
ConstTrackStateProxy::Covariance Acts::ConstVectorMultiTrajectory::covariance_impl (IndexType parIdx) const inline
Definition at line 527 of file VectorMultiTrajectory.hpp.
View newest version in sPHENIX GitHub at line 527 of file VectorMultiTrajectory.hpp
References Acts::detail_vmt::VectorMultiTrajectoryBase::m_cov.
constexpr bool Acts::ConstVectorMultiTrajectory::has_impl (HashedString key, IndexType istate) const inline
Definition at line 551 of file VectorMultiTrajectory.hpp.
View newest version in sPHENIX GitHub at line 551 of file VectorMultiTrajectory.hpp
References Acts::detail_vmt::VectorMultiTrajectoryBase::has_impl().
constexpr bool Acts::ConstVectorMultiTrajectory::hasColumn_impl (HashedString key) const inline
Definition at line 564 of file VectorMultiTrajectory.hpp.
View newest version in sPHENIX GitHub at line 564 of file VectorMultiTrajectory.hpp
References Acts::detail_vmt::VectorMultiTrajectoryBase::hasColumn_impl().
ConstTrackStateProxy::Covariance Acts::ConstVectorMultiTrajectory::jacobian_impl (IndexType istate) const inline
Definition at line 531 of file VectorMultiTrajectory.hpp.
View newest version in sPHENIX GitHub at line 531 of file VectorMultiTrajectory.hpp
References Acts::detail_vmt::VectorMultiTrajectoryBase::m_index, and Acts::detail_vmt::VectorMultiTrajectoryBase::m_jac.
template<size_t measdim> ConstTrackStateProxy::Measurement<measdim> Acts::ConstVectorMultiTrajectory::measurement_impl (IndexType istate) const inline
Definition at line 537 of file VectorMultiTrajectory.hpp.
View newest version in sPHENIX GitHub at line 537 of file VectorMultiTrajectory.hpp
References Acts::detail_vmt::VectorMultiTrajectoryBase::m_meas, Acts::detail_vmt::VectorMultiTrajectoryBase::m_measOffset, and offset.
template<size_t measdim> ConstTrackStateProxy::MeasurementCovariance<measdim> Acts::ConstVectorMultiTrajectory::measurementCovariance_impl (IndexType istate) const inline
Definition at line 545 of file VectorMultiTrajectory.hpp.
View newest version in sPHENIX GitHub at line 545 of file VectorMultiTrajectory.hpp
References Acts::detail_vmt::VectorMultiTrajectoryBase::m_measCov, Acts::detail_vmt::VectorMultiTrajectoryBase::m_measCovOffset, and offset.
ConstTrackStateProxy::Parameters Acts::ConstVectorMultiTrajectory::parameters_impl (IndexType parIdx) const inline
Definition at line 523 of file VectorMultiTrajectory.hpp.
View newest version in sPHENIX GitHub at line 523 of file VectorMultiTrajectory.hpp
References Acts::detail_vmt::VectorMultiTrajectoryBase::m_params.
IndexType Acts::ConstVectorMultiTrajectory::size_impl () const inline
Definition at line 555 of file VectorMultiTrajectory.hpp.
View newest version in sPHENIX GitHub at line 555 of file VectorMultiTrajectory.hpp
References Acts::detail_vmt::VectorMultiTrajectoryBase::m_index.
Statistics Acts::ConstVectorMultiTrajectory::statistics () const inline
Definition at line 517 of file VectorMultiTrajectory.hpp.
View newest version in sPHENIX GitHub at line 517 of file VectorMultiTrajectory.hpp
References Acts::detail_vmt::VectorMultiTrajectoryBase::statistics().
Member Data Documentation
friend Acts::ConstVectorMultiTrajectory::MultiTrajectory< ConstVectorMultiTrajectory > private
Definition at line 500 of file VectorMultiTrajectory.hpp.
View newest version in sPHENIX GitHub at line 500 of file VectorMultiTrajectory.hpp
The documentation for this exception was generated from the following file:
acts/blob/sPHENIX/Core/include/Acts/EventData/VectorMultiTrajectory.hpp