Analysis Software: TowerInfoDefs Namespace Reference
TowerInfoDefs Namespace Reference
Functions
unsigned int encode_emcal (const unsigned int towerIndex)
unsigned int encode_emcal (const unsigned int etabin, const unsigned int phibin)
unsigned int decode_emcal (const unsigned int tower_key)
unsigned int encode_hcal (const unsigned int towerIndex)
unsigned int encode_hcal (const unsigned int etabin, const unsigned int phibin)
unsigned int decode_hcal (const unsigned int tower_key)
unsigned int encode_epd (const unsigned int towerIndex)
unsigned int encode_epd (const unsigned int arm, const unsigned int rbin, const unsigned int phibin)
unsigned int decode_epd (const unsigned int tower_key)
unsigned int get_epd_arm (unsigned int key)
unsigned int get_epd_sector (unsigned int key)
unsigned int get_epd_rbin (unsigned int key)
unsigned int get_epd_phibin (unsigned int key)
unsigned int getCaloTowerPhiBin (const unsigned int key)
unsigned int getCaloTowerEtaBin (const unsigned int key)
int get_zdc_side (const unsigned int key)
unsigned int get_zdc_module_index (const unsigned int key)
int get_smd_side (const unsigned int key)
int get_smd_xy (const unsigned int key)
int get_smd_finger_index (const unsigned int key)
unsigned int get_mbd_arm (const unsigned int key)
unsigned int get_mbd_side (const unsigned int key)
unsigned int get_mbd_type (const unsigned int key)
unsigned int get_mbd_channel (const unsigned int key)
unsigned int encode_zdc (const unsigned int towerIndex)
unsigned int encode_smd (const unsigned int towerIndex)
unsigned int decode_smd (const unsigned int key)
unsigned int decode_zdc (const unsigned int key)
unsigned int encode_mbd (const unsigned int towerIndex)
unsigned int decode_mbd (const unsigned int key)
RawTowerDefs::keytype get_emcal_geokey_at_channel (const unsigned int towerIndex)
RawTowerDefs::keytype get_hcalin_geokey_at_channel (const unsigned int towerIndex)
RawTowerDefs::keytype get_hcalout_geokey_at_channel (const unsigned int towerIndex)
Function Documentation
unsigned int TowerInfoDefs::decode_emcal (const unsigned int tower_key)
Definition at line 111 of file TowerInfoDefs.cc.
View newest version in sPHENIX GitHub at line 111 of file TowerInfoDefs.cc
References emcadc, KF_timing::etabin, add_histos_bX::ib, and index.
Referenced by TowerInfoContainer::decode_emcal(), display(), and CaloWaveformSim::Init().
unsigned int TowerInfoDefs::decode_epd (const unsigned int tower_key)
Definition at line 275 of file TowerInfoDefs.cc.
View newest version in sPHENIX GitHub at line 275 of file TowerInfoDefs.cc
References channel(), and index.
Referenced by TowerInfoContainer::decode_epd().
unsigned int TowerInfoDefs::decode_hcal (const unsigned int tower_key)
Definition at line 203 of file TowerInfoDefs.cc.
View newest version in sPHENIX GitHub at line 203 of file TowerInfoDefs.cc
References KF_timing::etabin, hcaladc, add_histos_bX::ib, and index.
Referenced by TowerInfoContainer::decode_hcal(), and CaloWaveformSim::Init().
unsigned int TowerInfoDefs::decode_mbd (const unsigned int key)
Definition at line 470 of file TowerInfoDefs.cc.
View newest version in sPHENIX GitHub at line 470 of file TowerInfoDefs.cc
References channel(), index, and parse_cmake_options::type.
Referenced by TowerInfoContainer::decode_mbd().
unsigned int TowerInfoDefs::decode_smd (const unsigned int key)
Definition at line 403 of file TowerInfoDefs.cc.
View newest version in sPHENIX GitHub at line 403 of file TowerInfoDefs.cc
References encode_smd(), i, and index.
unsigned int TowerInfoDefs::decode_zdc (const unsigned int key)
Definition at line 418 of file TowerInfoDefs.cc.
View newest version in sPHENIX GitHub at line 418 of file TowerInfoDefs.cc
References encode_zdc(), i, and index.
Referenced by TowerInfoContainer::decode_zdc(), and ZdcMon::process_event().
unsigned int TowerInfoDefs::encode_emcal (const unsigned int towerIndex)
Definition at line 52 of file TowerInfoDefs.cc.
View newest version in sPHENIX GitHub at line 52 of file TowerInfoDefs.cc
References emcadc, j, and k.
Referenced by myAnalysis::analyze(), convert_channel_to_tower_bin(), display(), EMCalDeadmap(), TowerInfoContainer::encode_emcal(), CaloAna::fitEtaSlices(), pi0EtaByEta::fitEtaSlices(), get_emcal_geokey_at_channel(), CaloWaveformSim::Init(), DeadHotMapLoader::InitRun(), mergeCDBTTrees(), PHG4SpacalSteppingAction::NoHitSteppingAction(), TowerInfoDeadHotMask::process_event(), RawClusterDeadHotMask::process_event(), CemcMon::process_event(), pi0EtaByEta::process_towers(), TSCtoCDBTTree(), and towerid::WriteCDBTree().
unsigned int TowerInfoDefs::encode_emcal (const unsigned int etabin, const unsigned int phibin)
Definition at line 105 of file TowerInfoDefs.cc.
View newest version in sPHENIX GitHub at line 105 of file TowerInfoDefs.cc
unsigned int TowerInfoDefs::encode_epd (const unsigned int towerIndex)
Definition at line 239 of file TowerInfoDefs.cc.
View newest version in sPHENIX GitHub at line 239 of file TowerInfoDefs.cc
References channel().
Referenced by TowerInfoContainer::encode_epd(), PHG4EPDModuleReco::InitRun(), SepdMon::process_event(), EventPlaneReco::process_event(), PHG4EPDModuleReco::process_event(), and DumpEpdGeom::process_Node().
unsigned int TowerInfoDefs::encode_epd (const unsigned int arm, const unsigned int rbin, const unsigned int phibin)
Definition at line 251 of file TowerInfoDefs.cc.
View newest version in sPHENIX GitHub at line 251 of file TowerInfoDefs.cc
References channel(), and epdchnlmap.
unsigned int TowerInfoDefs::encode_hcal (const unsigned int towerIndex)
Definition at line 144 of file TowerInfoDefs.cc.
View newest version in sPHENIX GitHub at line 144 of file TowerInfoDefs.cc
References hcaladc, j, and k.
Referenced by myAnalysis::analyze(), TowerInfoContainer::encode_hcal(), get_hcalin_geokey_at_channel(), get_hcalout_geokey_at_channel(), CaloWaveformSim::Init(), DeadHotMapLoader::InitRun(), PHG4InnerHcalSteppingAction::NoHitSteppingAction(), PHG4OuterHcalSteppingAction::NoHitSteppingAction(), PHG4IHCalSteppingAction::NoHitSteppingAction(), PHG4OHCalSteppingAction::NoHitSteppingAction(), HcalMon::process_event(), and test_hcal().
unsigned int TowerInfoDefs::encode_hcal (const unsigned int etabin, const unsigned int phibin)
Definition at line 197 of file TowerInfoDefs.cc.
View newest version in sPHENIX GitHub at line 197 of file TowerInfoDefs.cc
unsigned int TowerInfoDefs::encode_mbd (const unsigned int towerIndex)
Definition at line 458 of file TowerInfoDefs.cc.
View newest version in sPHENIX GitHub at line 458 of file TowerInfoDefs.cc
References channel(), and parse_cmake_options::type.
Referenced by TowerInfoContainer::encode_mbd().
unsigned int TowerInfoDefs::encode_smd (const unsigned int towerIndex)
Definition at line 359 of file TowerInfoDefs.cc.
View newest version in sPHENIX GitHub at line 359 of file TowerInfoDefs.cc
Referenced by decode_smd().
unsigned int TowerInfoDefs::encode_zdc (const unsigned int towerIndex)
Definition at line 324 of file TowerInfoDefs.cc.
View newest version in sPHENIX GitHub at line 324 of file TowerInfoDefs.cc
Referenced by decode_zdc(), and TowerInfoContainer::encode_zdc().
RawTowerDefs::keytype TowerInfoDefs::get_emcal_geokey_at_channel (const unsigned int towerIndex)
Definition at line 502 of file TowerInfoDefs.cc.
View newest version in sPHENIX GitHub at line 502 of file TowerInfoDefs.cc
References Enable::CEMC, encode_emcal(), RawTowerDefs::encode_towerid(), KF_timing::etabin, getCaloTowerEtaBin(), and getCaloTowerPhiBin().
unsigned int TowerInfoDefs::get_epd_arm (unsigned int key)
Definition at line 287 of file TowerInfoDefs.cc.
View newest version in sPHENIX GitHub at line 287 of file TowerInfoDefs.cc
Referenced by get_epd_phibin(), get_epd_rbin(), get_epd_sector(), EpdGeomV1::get_z(), PHG4EPDModuleReco::InitRun(), SepdMon::process_event(), EventPlaneReco::process_event(), and EpdGeomV1::set_z().
unsigned int TowerInfoDefs::get_epd_phibin (unsigned int key)
Definition at line 309 of file TowerInfoDefs.cc.
View newest version in sPHENIX GitHub at line 309 of file TowerInfoDefs.cc
References channel(), epd_phimap, get_epd_arm(), get_epd_rbin(), and get_epd_sector().
Referenced by EpdGeomV1::get_phi(), PHG4EPDModuleReco::InitRun(), SepdMon::process_event(), EpdGeomV1::set_phi(), and EpdGeomV1::set_phi0().
unsigned int TowerInfoDefs::get_epd_rbin (unsigned int key)
Definition at line 300 of file TowerInfoDefs.cc.
View newest version in sPHENIX GitHub at line 300 of file TowerInfoDefs.cc
References channel(), epd_rmap, get_epd_arm(), and get_epd_sector().
Referenced by get_epd_phibin(), EpdGeomV1::get_phi(), EpdGeomV1::get_r(), PHG4EPDModuleReco::InitRun(), SepdMon::process_event(), and EpdGeomV1::set_r().
unsigned int TowerInfoDefs::get_epd_sector (unsigned int key)
Definition at line 293 of file TowerInfoDefs.cc.
View newest version in sPHENIX GitHub at line 293 of file TowerInfoDefs.cc
References get_epd_arm().
Referenced by get_epd_phibin(), and get_epd_rbin().
RawTowerDefs::keytype TowerInfoDefs::get_hcalin_geokey_at_channel (const unsigned int towerIndex)
Definition at line 512 of file TowerInfoDefs.cc.
View newest version in sPHENIX GitHub at line 512 of file TowerInfoDefs.cc
References encode_hcal(), RawTowerDefs::encode_towerid(), KF_timing::etabin, getCaloTowerEtaBin(), getCaloTowerPhiBin(), and RawTowerDefs::HCALIN.
RawTowerDefs::keytype TowerInfoDefs::get_hcalout_geokey_at_channel (const unsigned int towerIndex)
Definition at line 522 of file TowerInfoDefs.cc.
View newest version in sPHENIX GitHub at line 522 of file TowerInfoDefs.cc
References encode_hcal(), RawTowerDefs::encode_towerid(), KF_timing::etabin, getCaloTowerEtaBin(), getCaloTowerPhiBin(), and RawTowerDefs::HCALOUT.
unsigned int TowerInfoDefs::get_mbd_arm (const unsigned int key)
Definition at line 481 of file TowerInfoDefs.cc.
View newest version in sPHENIX GitHub at line 481 of file TowerInfoDefs.cc
Referenced by get_mbd_side().
unsigned int TowerInfoDefs::get_mbd_channel (const unsigned int key)
Definition at line 496 of file TowerInfoDefs.cc.
View newest version in sPHENIX GitHub at line 496 of file TowerInfoDefs.cc
unsigned int TowerInfoDefs::get_mbd_side (const unsigned int key)
Definition at line 486 of file TowerInfoDefs.cc.
View newest version in sPHENIX GitHub at line 486 of file TowerInfoDefs.cc
References get_mbd_arm().
unsigned int TowerInfoDefs::get_mbd_type (const unsigned int key)
Definition at line 491 of file TowerInfoDefs.cc.
View newest version in sPHENIX GitHub at line 491 of file TowerInfoDefs.cc
int TowerInfoDefs::get_smd_finger_index (const unsigned int key)
Definition at line 452 of file TowerInfoDefs.cc.
View newest version in sPHENIX GitHub at line 452 of file TowerInfoDefs.cc
int TowerInfoDefs::get_smd_side (const unsigned int key)
Definition at line 440 of file TowerInfoDefs.cc.
View newest version in sPHENIX GitHub at line 440 of file TowerInfoDefs.cc
int TowerInfoDefs::get_smd_xy (const unsigned int key)
Definition at line 446 of file TowerInfoDefs.cc.
View newest version in sPHENIX GitHub at line 446 of file TowerInfoDefs.cc
unsigned int TowerInfoDefs::get_zdc_module_index (const unsigned int key)
int TowerInfoDefs::get_zdc_side (const unsigned int key)
Definition at line 433 of file TowerInfoDefs.cc.
View newest version in sPHENIX GitHub at line 433 of file TowerInfoDefs.cc
Referenced by ZdcMon::process_event().
unsigned int TowerInfoDefs::getCaloTowerEtaBin (const unsigned int key)
Definition at line 233 of file TowerInfoDefs.cc.
View newest version in sPHENIX GitHub at line 233 of file TowerInfoDefs.cc
References KF_timing::etabin.
Referenced by myAnalysis::analyze(), convert_channel_to_tower_bin(), display(), EMCalDeadmap(), get_emcal_geokey_at_channel(), get_hcalin_geokey_at_channel(), get_hcalout_geokey_at_channel(), TowerInfoContainer::getTowerEtaBin(), DeadHotMapLoader::InitRun(), CemcMon::process_event(), HcalMon::process_event(), and test_hcal().
unsigned int TowerInfoDefs::getCaloTowerPhiBin (const unsigned int key)
Definition at line 225 of file TowerInfoDefs.cc.
View newest version in sPHENIX GitHub at line 225 of file TowerInfoDefs.cc
References KF_timing::etabin.
Referenced by myAnalysis::analyze(), convert_channel_to_tower_bin(), display(), EMCalDeadmap(), get_emcal_geokey_at_channel(), get_hcalin_geokey_at_channel(), get_hcalout_geokey_at_channel(), TowerInfoContainer::getTowerPhiBin(), DeadHotMapLoader::InitRun(), CemcMon::process_event(), HcalMon::process_event(), and test_hcal().