Analysis Software: QAG4SimulationTpc Class Reference
QAG4SimulationTpc Class Reference
#include <coresoftware/blob/master/offline/QA/modules/QAG4SimulationTpc.h>
Public Member Functions
QAG4SimulationTpc (const std::string &name="QAG4SimulationTpc")
constructor
int InitRun (PHCompositeNode *topNode) override
int process_event (PHCompositeNode *topNode) override
Public Member Functions inherited from SubsysReco
~SubsysReco () override
virtual int End (PHCompositeNode *)
Called at the end of all processing.
virtual int EndRun (const int)
Called at the end of each run.
virtual int Init (PHCompositeNode *)
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
void Print (const std::string &="ALL") const override
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Private Types
using G4HitSet = std::set< PHG4Hit * >
Private Member Functions
std::string get_histo_prefix () const
common prefix for QA histograms
int load_nodes (PHCompositeNode *)
load nodes
void evaluate_clusters ()
evaluate clusters
G4HitSet find_g4hits (TrkrDefs::cluskey) const
Private Attributes
std::unique_ptr< SvtxEvalStack > m_svtxEvalStack
PHG4TruthInfoContainer * m_truthContainer
bool m_initialized = false
true if histograms are initialized
ActsGeometry * m_tGeometry = nullptr
Acts tracking geometry for surface lookup.
TrkrClusterContainer * m_cluster_map = nullptr
cluster map
TrkrClusterHitAssoc * m_cluster_hit_map = nullptr
clusters to hit association
TrkrHitTruthAssoc * m_hit_truth_map = nullptr
hit to g4hit association
PHG4HitContainer * m_g4hits_tpc = nullptr
g4 hits
std::set< int > m_layers
list of relevant layers
std::multimap< int, int > m_layer_region_map
ClusterErrorPara _ClusErrPara
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = std::numeric_limits<int>::max() - 10
}
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Detailed Description
Definition at line 27 of file QAG4SimulationTpc.h.
View newest version in sPHENIX GitHub at line 27 of file QAG4SimulationTpc.h
Member Typedef Documentation
using QAG4SimulationTpc::G4HitSet = std::set<PHG4Hit*> private
Definition at line 50 of file QAG4SimulationTpc.h.
View newest version in sPHENIX GitHub at line 50 of file QAG4SimulationTpc.h
Constructor & Destructor Documentation
QAG4SimulationTpc::QAG4SimulationTpc (const std::string & name = "QAG4SimulationTpc")
constructor
Definition at line 47 of file QAG4SimulationTpc.cc.
View newest version in sPHENIX GitHub at line 47 of file QAG4SimulationTpc.cc
Member Function Documentation
void QAG4SimulationTpc::evaluate_clusters () private
evaluate clusters
Definition at line 261 of file QAG4SimulationTpc.cc.
View newest version in sPHENIX GitHub at line 261 of file QAG4SimulationTpc.cc
References SvtxTruthEval::all_truth_clusters(), assert, TrackFitUtils::circle_fit_by_taubin(), QAG4Util::delta_phi(), distance(), INTTVtxZ::dphi, dz, SvtxTruthEval::get_embed(), get_histo_prefix(), PHG4Particle::get_pid(), QAG4Util::get_r(), PHG4Particle::get_track_id(), ActsGeometry::getGlobalPosition(), QAHistManagerDef::getHistoManager(), TrkrClusterHitAssoc::getHits(), TrkrDefs::getLayer(), TpcDefs::getPad(), PHG4TruthInfoContainer::GetPrimaryParticleRange(), TpcDefs::getTBin(), TrkrDefs::getTrkrId(), gflavor, gprimary, gr, gtrackID, gx, gy, gz, h, SvtxTruthEval::is_primary(), it, layer, m_cluster_hit_map, m_layer_region_map, m_svtxEvalStack, m_tGeometry, m_truthContainer, ng4hits, MATSCAN::phibins, PHWHERE, Acts::IntegrationTest::R, SvtxClusterEval::reco_cluster_from_truth_cluster(), TrkrDefs::tpcId, value, Fun4AllBase::Verbosity(), X0, and Y0.
Referenced by process_event().
QAG4SimulationTpc::G4HitSet QAG4SimulationTpc::find_g4hits (TrkrDefs::cluskey cluster_key) const private
Definition at line 458 of file QAG4SimulationTpc.cc.
View newest version in sPHENIX GitHub at line 458 of file QAG4SimulationTpc.cc
References PHG4HitContainer::findHit(), TrkrHitTruthAssoc::getG4Hits(), TrkrClusterHitAssoc::getHits(), TrkrDefs::getHitSetKeyFromClusKey(), TrkrDefs::getTrkrId(), m_cluster_hit_map, m_g4hits_tpc, m_hit_truth_map, out, and TrkrDefs::tpcId.
std::string QAG4SimulationTpc::get_histo_prefix () const private
common prefix for QA histograms
Definition at line 213 of file QAG4SimulationTpc.cc.
View newest version in sPHENIX GitHub at line 213 of file QAG4SimulationTpc.cc
References Fun4AllBase::Name().
Referenced by evaluate_clusters(), and InitRun().
int QAG4SimulationTpc::InitRun (PHCompositeNode *) override virtual
Called for first event when run number is known. Typically this is where you may want to fetch data from database, because you know the run number.
Reimplemented from SubsysReco.
Definition at line 54 of file QAG4SimulationTpc.cc.
View newest version in sPHENIX GitHub at line 54 of file QAG4SimulationTpc.cc
References Fun4AllReturnCodes::ABORTRUN, assert, Fun4AllReturnCodes::EVENT_OK, PHG4TpcCylinderGeomContainer::get_begin_end(), get_histo_prefix(), QAHistManagerDef::getHistoManager(), h, m_initialized, m_layer_region_map, m_layers, m_svtxEvalStack, m_truthContainer, PHWHERE, and Fun4AllBase::Verbosity().
int QAG4SimulationTpc::load_nodes (PHCompositeNode * topNode) private
load nodes
Definition at line 219 of file QAG4SimulationTpc.cc.
View newest version in sPHENIX GitHub at line 219 of file QAG4SimulationTpc.cc
References Fun4AllReturnCodes::ABORTEVENT, Fun4AllReturnCodes::EVENT_OK, m_cluster_hit_map, m_cluster_map, m_g4hits_tpc, m_hit_truth_map, m_tGeometry, and PHWHERE.
Referenced by process_event().
int QAG4SimulationTpc::process_event (PHCompositeNode *) override virtual
Called for each event. This is where you do the real work.
Reimplemented from SubsysReco.
Definition at line 198 of file QAG4SimulationTpc.cc.
View newest version in sPHENIX GitHub at line 198 of file QAG4SimulationTpc.cc
References evaluate_clusters(), Fun4AllReturnCodes::EVENT_OK, load_nodes(), and m_svtxEvalStack.
Member Data Documentation
ClusterErrorPara QAG4SimulationTpc::_ClusErrPara private
Definition at line 75 of file QAG4SimulationTpc.h.
View newest version in sPHENIX GitHub at line 75 of file QAG4SimulationTpc.h
TrkrClusterHitAssoc* QAG4SimulationTpc::m_cluster_hit_map = nullptr private
clusters to hit association
Definition at line 63 of file QAG4SimulationTpc.h.
View newest version in sPHENIX GitHub at line 63 of file QAG4SimulationTpc.h
Referenced by evaluate_clusters(), find_g4hits(), and load_nodes().
TrkrClusterContainer* QAG4SimulationTpc::m_cluster_map = nullptr private
cluster map
Definition at line 60 of file QAG4SimulationTpc.h.
View newest version in sPHENIX GitHub at line 60 of file QAG4SimulationTpc.h
Referenced by load_nodes().
PHG4HitContainer* QAG4SimulationTpc::m_g4hits_tpc = nullptr private
g4 hits
Definition at line 69 of file QAG4SimulationTpc.h.
View newest version in sPHENIX GitHub at line 69 of file QAG4SimulationTpc.h
Referenced by find_g4hits(), and load_nodes().
TrkrHitTruthAssoc* QAG4SimulationTpc::m_hit_truth_map = nullptr private
hit to g4hit association
Definition at line 66 of file QAG4SimulationTpc.h.
View newest version in sPHENIX GitHub at line 66 of file QAG4SimulationTpc.h
Referenced by find_g4hits(), and load_nodes().
bool QAG4SimulationTpc::m_initialized = false private
true if histograms are initialized
Definition at line 54 of file QAG4SimulationTpc.h.
View newest version in sPHENIX GitHub at line 54 of file QAG4SimulationTpc.h
Referenced by InitRun().
std::multimap<int, int> QAG4SimulationTpc::m_layer_region_map private
Definition at line 74 of file QAG4SimulationTpc.h.
View newest version in sPHENIX GitHub at line 74 of file QAG4SimulationTpc.h
Referenced by evaluate_clusters(), and InitRun().
std::set<int> QAG4SimulationTpc::m_layers private
list of relevant layers
Definition at line 73 of file QAG4SimulationTpc.h.
View newest version in sPHENIX GitHub at line 73 of file QAG4SimulationTpc.h
Referenced by InitRun().
std::unique_ptr<SvtxEvalStack> QAG4SimulationTpc::m_svtxEvalStack private
Definition at line 40 of file QAG4SimulationTpc.h.
View newest version in sPHENIX GitHub at line 40 of file QAG4SimulationTpc.h
Referenced by evaluate_clusters(), InitRun(), and process_event().
ActsGeometry* QAG4SimulationTpc::m_tGeometry = nullptr private
Acts tracking geometry for surface lookup.
Definition at line 57 of file QAG4SimulationTpc.h.
View newest version in sPHENIX GitHub at line 57 of file QAG4SimulationTpc.h
Referenced by evaluate_clusters(), and load_nodes().
PHG4TruthInfoContainer* QAG4SimulationTpc::m_truthContainer private
Definition at line 41 of file QAG4SimulationTpc.h.
View newest version in sPHENIX GitHub at line 41 of file QAG4SimulationTpc.h
Referenced by evaluate_clusters(), and InitRun().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/QA/modules/QAG4SimulationTpc.h
coresoftware/blob/master/offline/QA/modules/QAG4SimulationTpc.cc