Analysis Software: PHTrackClusterAssociator Class Reference
PHTrackClusterAssociator Class Reference
#include <coresoftware/blob/master/offline/packages/trackreco/PHTrackClusterAssociator.h>
Public Member Functions
PHTrackClusterAssociator (const std::string &name="PHTrackClusterAssociator")
~PHTrackClusterAssociator () override
int InitRun (PHCompositeNode *topNode) override
int process_event (PHCompositeNode *topNode) override
int ResetEvent (PHCompositeNode *topNode) override
Clean up after each event.
int End (PHCompositeNode *topNode) override
Called at the end of all processing.
void setCaloRadius (const std::string &name, double rad)
Public Member Functions inherited from SubsysReco
~SubsysReco () override
virtual int EndRun (const int)
Called at the end of each run.
virtual int Init (PHCompositeNode *)
virtual int Reset (PHCompositeNode *)
Reset.
void Print (const std::string &="ALL") const override
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Private Member Functions
int getNodes (PHCompositeNode *topNode)
int createNodes (PHCompositeNode *topNode)
int getCaloNodes (PHCompositeNode *topNode, const int caloLayer)
int matchTracks (PHCompositeNode *topNode, const int caloLayer)
RawCluster * getCluster (double phi, double eta, SvtxVertex *vertex)
Private Attributes
SvtxTrackMap * m_trackMap = nullptr
SvtxVertexMap * m_vertexMap = nullptr
std::vector< std::string > m_caloNames
std::map< std::string, float > m_caloRadii
RawTowerGeomContainer * m_towerGeomContainer = nullptr
TowerInfoContainer * m_towerContainer = nullptr
RawClusterContainer * m_clusterContainer = nullptr
SvtxTrackCaloClusterMap * m_trackClusterMap = nullptr
bool m_useCemcPosRecalib = false
bool m_calosAvailable = true
Static Private Attributes
static const int m_nCaloLayers = 3
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = std::numeric_limits<int>::max() - 10
}
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Detailed Description
Definition at line 23 of file PHTrackClusterAssociator.h.
View newest version in sPHENIX GitHub at line 23 of file PHTrackClusterAssociator.h
Constructor & Destructor Documentation
PHTrackClusterAssociator::PHTrackClusterAssociator (const std::string & name = "PHTrackClusterAssociator")
Definition at line 44 of file PHTrackClusterAssociator.cc.
View newest version in sPHENIX GitHub at line 44 of file PHTrackClusterAssociator.cc
References m_caloNames.
PHTrackClusterAssociator::~PHTrackClusterAssociator () override
Definition at line 53 of file PHTrackClusterAssociator.cc.
View newest version in sPHENIX GitHub at line 53 of file PHTrackClusterAssociator.cc
Member Function Documentation
int PHTrackClusterAssociator::createNodes (PHCompositeNode * topNode) private
Definition at line 247 of file PHTrackClusterAssociator.cc.
View newest version in sPHENIX GitHub at line 247 of file PHTrackClusterAssociator.cc
References PHCompositeNode::addNode(), Fun4AllReturnCodes::EVENT_OK, PHNodeIterator::findFirst(), and m_trackClusterMap.
Referenced by InitRun().
int PHTrackClusterAssociator::End (PHCompositeNode *) override virtual
Called at the end of all processing.
Reimplemented from SubsysReco.
Definition at line 287 of file PHTrackClusterAssociator.cc.
View newest version in sPHENIX GitHub at line 287 of file PHTrackClusterAssociator.cc
References Fun4AllReturnCodes::EVENT_OK.
int PHTrackClusterAssociator::getCaloNodes (PHCompositeNode * topNode, const int caloLayer) private
Definition at line 215 of file PHTrackClusterAssociator.cc.
View newest version in sPHENIX GitHub at line 215 of file PHTrackClusterAssociator.cc
References Fun4AllReturnCodes::ABORTEVENT, Fun4AllReturnCodes::EVENT_OK, m_caloNames, m_calosAvailable, m_clusterContainer, m_towerContainer, m_towerGeomContainer, m_useCemcPosRecalib, and PHWHERE.
Referenced by matchTracks().
RawCluster * PHTrackClusterAssociator::getCluster (double phi, double eta, SvtxVertex * vertex) private
Definition at line 162 of file PHTrackClusterAssociator.cc.
View newest version in sPHENIX GitHub at line 162 of file PHTrackClusterAssociator.cc
References myAnalysis::clusterEta, deltaPhi(), SvtxVertex::get_x(), SvtxVertex::get_y(), SvtxVertex::get_z(), RawClusterContainer::getClustersMap(), RawClusterUtility::GetPseudorapidity(), m_clusterContainer, minR, and physmon_track_finding_ttbar::r.
Referenced by matchTracks().
int PHTrackClusterAssociator::getNodes (PHCompositeNode * topNode) private
Definition at line 196 of file PHTrackClusterAssociator.cc.
View newest version in sPHENIX GitHub at line 196 of file PHTrackClusterAssociator.cc
References Fun4AllReturnCodes::ABORTEVENT, Fun4AllReturnCodes::EVENT_OK, m_trackMap, m_vertexMap, and PHWHERE.
Referenced by InitRun().
int PHTrackClusterAssociator::InitRun (PHCompositeNode *) override virtual
Called for first event when run number is known. Typically this is where you may want to fetch data from database, because you know the run number.
Reimplemented from SubsysReco.
Definition at line 58 of file PHTrackClusterAssociator.cc.
View newest version in sPHENIX GitHub at line 58 of file PHTrackClusterAssociator.cc
References createNodes(), Fun4AllReturnCodes::EVENT_OK, and getNodes().
int PHTrackClusterAssociator::matchTracks (PHCompositeNode * topNode, const int caloLayer) private
Default to using calo radius
Definition at line 114 of file PHTrackClusterAssociator.cc.
View newest version in sPHENIX GitHub at line 114 of file PHTrackClusterAssociator.cc
References Fun4AllReturnCodes::ABORTEVENT, Fun4AllReturnCodes::EVENT_OK, SvtxVertexMap::get(), RawTowerGeomContainer::get_radius(), SvtxTrackState::get_x(), SvtxTrackState::get_y(), SvtxTrackState::get_z(), getCaloNodes(), getCluster(), SvtxTrackCaloClusterMap::insert(), m_caloNames, m_caloRadii, m_towerGeomContainer, m_trackClusterMap, m_trackMap, m_vertexMap, filter::state, and Fun4AllBase::Verbosity().
Referenced by process_event().
int PHTrackClusterAssociator::process_event (PHCompositeNode *) override virtual
Called for each event. This is where you do the real work.
Reimplemented from SubsysReco.
Definition at line 76 of file PHTrackClusterAssociator.cc.
View newest version in sPHENIX GitHub at line 76 of file PHTrackClusterAssociator.cc
References Fun4AllReturnCodes::ABORTEVENT, Fun4AllReturnCodes::EVENT_OK, layer, m_caloNames, m_calosAvailable, m_nCaloLayers, m_trackClusterMap, matchTracks(), and Fun4AllBase::Verbosity().
int PHTrackClusterAssociator::ResetEvent (PHCompositeNode *) override virtual
Clean up after each event.
Reimplemented from SubsysReco.
Definition at line 281 of file PHTrackClusterAssociator.cc.
View newest version in sPHENIX GitHub at line 281 of file PHTrackClusterAssociator.cc
References Fun4AllReturnCodes::EVENT_OK.
void PHTrackClusterAssociator::setCaloRadius (const std::string & name, double rad) inline
Definition at line 35 of file PHTrackClusterAssociator.h.
View newest version in sPHENIX GitHub at line 35 of file PHTrackClusterAssociator.h
References m_caloRadii.
Member Data Documentation
std::vector<std::string> PHTrackClusterAssociator::m_caloNames private
Definition at line 52 of file PHTrackClusterAssociator.h.
View newest version in sPHENIX GitHub at line 52 of file PHTrackClusterAssociator.h
Referenced by getCaloNodes(), matchTracks(), PHTrackClusterAssociator(), and process_event().
std::map<std::string, float> PHTrackClusterAssociator::m_caloRadii private
An optional map that allows projection to an arbitrary radius Results are written to the SvtxTrack based on the provided CAL_LAYER
Definition at line 55 of file PHTrackClusterAssociator.h.
View newest version in sPHENIX GitHub at line 55 of file PHTrackClusterAssociator.h
Referenced by matchTracks(), and setCaloRadius().
bool PHTrackClusterAssociator::m_calosAvailable = true private
Definition at line 64 of file PHTrackClusterAssociator.h.
View newest version in sPHENIX GitHub at line 64 of file PHTrackClusterAssociator.h
Referenced by getCaloNodes(), and process_event().
RawClusterContainer* PHTrackClusterAssociator::m_clusterContainer = nullptr private
Definition at line 59 of file PHTrackClusterAssociator.h.
View newest version in sPHENIX GitHub at line 59 of file PHTrackClusterAssociator.h
Referenced by getCaloNodes(), and getCluster().
const int PHTrackClusterAssociator::m_nCaloLayers = 3 static private
Objects to hold calorimeter information. There are only 3 calo layers
Definition at line 51 of file PHTrackClusterAssociator.h.
View newest version in sPHENIX GitHub at line 51 of file PHTrackClusterAssociator.h
Referenced by process_event().
TowerInfoContainer* PHTrackClusterAssociator::m_towerContainer = nullptr private
Definition at line 58 of file PHTrackClusterAssociator.h.
View newest version in sPHENIX GitHub at line 58 of file PHTrackClusterAssociator.h
Referenced by getCaloNodes().
RawTowerGeomContainer* PHTrackClusterAssociator::m_towerGeomContainer = nullptr private
Definition at line 57 of file PHTrackClusterAssociator.h.
View newest version in sPHENIX GitHub at line 57 of file PHTrackClusterAssociator.h
Referenced by getCaloNodes(), and matchTracks().
SvtxTrackCaloClusterMap* PHTrackClusterAssociator::m_trackClusterMap = nullptr private
Definition at line 61 of file PHTrackClusterAssociator.h.
View newest version in sPHENIX GitHub at line 61 of file PHTrackClusterAssociator.h
Referenced by createNodes(), matchTracks(), and process_event().
SvtxTrackMap* PHTrackClusterAssociator::m_trackMap = nullptr private
Definition at line 46 of file PHTrackClusterAssociator.h.
View newest version in sPHENIX GitHub at line 46 of file PHTrackClusterAssociator.h
Referenced by getNodes(), and matchTracks().
bool PHTrackClusterAssociator::m_useCemcPosRecalib = false private
Definition at line 63 of file PHTrackClusterAssociator.h.
View newest version in sPHENIX GitHub at line 63 of file PHTrackClusterAssociator.h
Referenced by getCaloNodes().
SvtxVertexMap* PHTrackClusterAssociator::m_vertexMap = nullptr private
Definition at line 47 of file PHTrackClusterAssociator.h.
View newest version in sPHENIX GitHub at line 47 of file PHTrackClusterAssociator.h
Referenced by getNodes(), and matchTracks().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/trackreco/PHTrackClusterAssociator.h
coresoftware/blob/master/offline/packages/trackreco/PHTrackClusterAssociator.cc