Analysis Software: ActsExamples::CsvTrackParameterReader Exception Reference
ActsExamples::CsvTrackParameterReader Exception Reference final
#include <acts/blob/sPHENIX/Examples/Io/Csv/include/ActsExamples/Io/Csv/CsvTrackParameterReader.hpp>
Classes
struct Config
Public Member Functions
CsvTrackParameterReader (const Config &config, Acts::Logging::Level level)
std::string name () const final
The algorithm name.
std::pair< size_t, size_t > availableEvents () const final
Return the available events range.
ProcessCode read (const ActsExamples::AlgorithmContext &ctx) final
Read out data from the input stream.
const Config & config () const
Readonly access to the config.
Public Member Functions inherited from ActsExamples::IReader
ProcessCode internalExecute (const AlgorithmContext &context) final
ProcessCode initialize () override
Fulfill the algorithm interface.
ProcessCode finalize () override
Fulfill the algorithm interface.
Public Member Functions inherited from ActsExamples::SequenceElement
virtual ~SequenceElement ()=default
const std::vector< const
DataHandleBase * > & writeHandles () const
const std::vector< const
DataHandleBase * > & readHandles () const
Private Member Functions
const Acts::Logger & logger () const
Private Attributes
Config m_cfg
std::pair< size_t, size_t > m_eventsRange
std::unique_ptr< const
Acts::Logger > m_logger
WriteDataHandle
< TrackParametersContainer > m_outputTrackParameters
Detailed Description
Read track parameters in comma-separated-value format.
This reads one file per event in the configured input directory and filename. Files are assumed to be named using the following schema
event000000001-<stem>.csv
event000000002-<stem>.csv
and each line in the file corresponds to one track parameter.
Definition at line 35 of file CsvTrackParameterReader.hpp.
View newest version in sPHENIX GitHub at line 35 of file CsvTrackParameterReader.hpp
Constructor & Destructor Documentation
ActsExamples::CsvTrackParameterReader::CsvTrackParameterReader (const Config & config, Acts::Logging::Level level)
Construct the track parameter reader.
Parameters
config is the configuration object
level is the logging level
Definition at line 27 of file CsvTrackParameterReader.cpp.
View newest version in sPHENIX GitHub at line 27 of file CsvTrackParameterReader.cpp
References ActsExamples::WriteDataHandle< T >::initialize(), ActsExamples::CsvTrackParameterReader::Config::inputStem, m_cfg, m_outputTrackParameters, and ActsExamples::CsvTrackParameterReader::Config::outputTrackParameters.
Member Function Documentation
std::pair< size_t, size_t > ActsExamples::CsvTrackParameterReader::availableEvents () const final virtual
Return the available events range.
Implements ActsExamples::IReader.
Definition at line 50 of file CsvTrackParameterReader.cpp.
View newest version in sPHENIX GitHub at line 50 of file CsvTrackParameterReader.cpp
const Config& ActsExamples::CsvTrackParameterReader::config () const inline
Readonly access to the config.
Definition at line 64 of file CsvTrackParameterReader.hpp.
View newest version in sPHENIX GitHub at line 64 of file CsvTrackParameterReader.hpp
References m_cfg.
const Acts::Logger& ActsExamples::CsvTrackParameterReader::logger () const inline private
Definition at line 74 of file CsvTrackParameterReader.hpp.
View newest version in sPHENIX GitHub at line 74 of file CsvTrackParameterReader.hpp
References m_logger.
std::string ActsExamples::CsvTrackParameterReader::name () const final virtual
The algorithm name.
Implements ActsExamples::SequenceElement.
ActsExamples::ProcessCode ActsExamples::CsvTrackParameterReader::read (const ActsExamples::AlgorithmContext & ctx) final virtual
Read out data from the input stream.
Implements ActsExamples::IReader.
Definition at line 54 of file CsvTrackParameterReader.cpp.
View newest version in sPHENIX GitHub at line 54 of file CsvTrackParameterReader.cpp
References Acts::Test::cov, Acts::eBoundLoc0, Acts::eBoundLoc1, Acts::eBoundPhi, Acts::eBoundQOverP, Acts::eBoundTheta, Acts::eBoundTime, ActsExamples::AlgorithmContext::eventNumber, m_cfg(), testing::internal::move(), path, ActsExamples::perEventFilepath(), Acts::ParticleHypothesis::pion(), summary::reader, SUCCESS, and writeMapConfig::surface.
Member Data Documentation
Config ActsExamples::CsvTrackParameterReader::m_cfg private
Definition at line 67 of file CsvTrackParameterReader.hpp.
View newest version in sPHENIX GitHub at line 67 of file CsvTrackParameterReader.hpp
Referenced by config(), and CsvTrackParameterReader().
std::pair<size_t, size_t> ActsExamples::CsvTrackParameterReader::m_eventsRange private
Definition at line 68 of file CsvTrackParameterReader.hpp.
View newest version in sPHENIX GitHub at line 68 of file CsvTrackParameterReader.hpp
std::unique_ptr<const Acts::Logger> ActsExamples::CsvTrackParameterReader::m_logger private
Definition at line 69 of file CsvTrackParameterReader.hpp.
View newest version in sPHENIX GitHub at line 69 of file CsvTrackParameterReader.hpp
Referenced by logger().
WriteDataHandle<TrackParametersContainer> ActsExamples::CsvTrackParameterReader::m_outputTrackParameters private
Initial value:
{
      this, "OutputTrackParameters"}
Definition at line 71 of file CsvTrackParameterReader.hpp.
View newest version in sPHENIX GitHub at line 71 of file CsvTrackParameterReader.hpp
Referenced by CsvTrackParameterReader().
The documentation for this exception was generated from the following files:
acts/blob/sPHENIX/Examples/Io/Csv/include/ActsExamples/Io/Csv/CsvTrackParameterReader.hpp
acts/blob/sPHENIX/Examples/Io/Csv/src/CsvTrackParameterReader.cpp