Analysis Software: symlist_iterator< T, Ref > Struct Template Reference
symlist_iterator< T, Ref > Struct Template Reference
#include <JETSCAPE/blob/main/external_packages/gtl/include/GTL/symlist.h>
Public Types
typedef symlist_iterator< T, Ref > self
typedef symnode< T > * linktype
Public Member Functions
symlist_iterator ()
symlist_iterator (const self &it)
symlist_iterator (linktype _act, int _dir)
symlist_iterator (linktype _act, linktype _prev)
self & operator= (const self &it)
bool operator== (const self &it) const
bool operator!= (const self &it) const
Ref operator* ()
self & operator++ ()
self & operator-- ()
void reverse ()
linktype & next ()
linktype & prev ()
Static Public Member Functions
static int where (linktype _act, linktype _prev)
static int where_not (linktype _act, linktype _prev)
Public Attributes
linktype act
int dir
Detailed Description
template<class T, class Ref>
struct symlist_iterator< T, Ref >
Definition at line 53 of file symlist.h.
View newest version in sPHENIX GitHub at line 53 of file symlist.h
Member Typedef Documentation
template<class T, class Ref> typedef symnode<T>* symlist_iterator< T, Ref >::linktype
Definition at line 63 of file symlist.h.
View newest version in sPHENIX GitHub at line 63 of file symlist.h
template<class T, class Ref> typedef symlist_iterator<T, Ref> symlist_iterator< T, Ref >::self
Definition at line 58 of file symlist.h.
View newest version in sPHENIX GitHub at line 58 of file symlist.h
Constructor & Destructor Documentation
template<class T, class Ref> symlist_iterator< T, Ref >::symlist_iterator () inline
Definition at line 68 of file symlist.h.
View newest version in sPHENIX GitHub at line 68 of file symlist.h
template<class T, class Ref> symlist_iterator< T, Ref >::symlist_iterator (const self & it) inline
Definition at line 75 of file symlist.h.
View newest version in sPHENIX GitHub at line 75 of file symlist.h
template<class T, class Ref> symlist_iterator< T, Ref >::symlist_iterator (linktype _act, int _dir) inline
Definition at line 82 of file symlist.h.
View newest version in sPHENIX GitHub at line 82 of file symlist.h
template<class T, class Ref> symlist_iterator< T, Ref >::symlist_iterator (linktype _act, linktype _prev) inline
Definition at line 89 of file symlist.h.
View newest version in sPHENIX GitHub at line 89 of file symlist.h
Member Function Documentation
template<class T, class Ref> linktype& symlist_iterator< T, Ref >::next () inline
Definition at line 166 of file symlist.h.
View newest version in sPHENIX GitHub at line 166 of file symlist.h
Referenced by symlist< T >::attach_sublist(), symlist< T >::detach_sublist(), symlist< T >::erase(), symlist< T >::insert(), and symlist< T >::splice().
template<class T, class Ref> bool symlist_iterator< T, Ref >::operator!= (const self & it) const inline
Definition at line 116 of file symlist.h.
View newest version in sPHENIX GitHub at line 116 of file symlist.h
template<class T, class Ref> Ref symlist_iterator< T, Ref >::operator* () inline
Definition at line 124 of file symlist.h.
View newest version in sPHENIX GitHub at line 124 of file symlist.h
template<class T , class Ref > symlist_iterator< T, Ref > & symlist_iterator< T, Ref >::operator++ ()
Definition at line 467 of file symlist.h.
View newest version in sPHENIX GitHub at line 467 of file symlist.h
References symnode< T >::adj.
template<class T , class Ref > symlist_iterator< T, Ref > & symlist_iterator< T, Ref >::operator-- ()
Definition at line 477 of file symlist.h.
View newest version in sPHENIX GitHub at line 477 of file symlist.h
References symnode< T >::adj.
template<class T, class Ref> self& symlist_iterator< T, Ref >::operator= (const self & it) inline
Definition at line 98 of file symlist.h.
View newest version in sPHENIX GitHub at line 98 of file symlist.h
template<class T, class Ref> bool symlist_iterator< T, Ref >::operator== (const self & it) const inline
Definition at line 108 of file symlist.h.
View newest version in sPHENIX GitHub at line 108 of file symlist.h
template<class T, class Ref> linktype& symlist_iterator< T, Ref >::prev () inline
Definition at line 174 of file symlist.h.
View newest version in sPHENIX GitHub at line 174 of file symlist.h
Referenced by symlist< T >::attach_sublist(), symlist< T >::detach_sublist(), symlist< T >::erase(), symlist< T >::insert(), and symlist< T >::splice().
template<class T, class Ref> void symlist_iterator< T, Ref >::reverse () inline
Definition at line 158 of file symlist.h.
View newest version in sPHENIX GitHub at line 158 of file symlist.h
template<class T, class Ref> static int symlist_iterator< T, Ref >::where (linktype _act, linktype _prev) inline static
Definition at line 142 of file symlist.h.
View newest version in sPHENIX GitHub at line 142 of file symlist.h
template<class T, class Ref> static int symlist_iterator< T, Ref >::where_not (linktype _act, linktype _prev) inline static
Definition at line 150 of file symlist.h.
View newest version in sPHENIX GitHub at line 150 of file symlist.h
Member Data Documentation
template<class T, class Ref> linktype symlist_iterator< T, Ref >::act
Definition at line 182 of file symlist.h.
View newest version in sPHENIX GitHub at line 182 of file symlist.h
Referenced by symlist< T >::attach_sublist(), symlist< T >::detach_sublist(), symlist< T >::erase(), symlist< T >::insert(), symlist_iterator< T, T & >::next(), symlist_iterator< T, T & >::operator!=(), symlist_iterator< T, T & >::operator*(), symlist_iterator< T, T & >::operator=(), symlist_iterator< T, T & >::operator==(), symlist_iterator< T, T & >::prev(), and symlist< T >::splice().
template<class T, class Ref> int symlist_iterator< T, Ref >::dir
Definition at line 187 of file symlist.h.
View newest version in sPHENIX GitHub at line 187 of file symlist.h
Referenced by symlist_iterator< T, T & >::next(), symlist_iterator< T, T & >::operator=(), symlist_iterator< T, T & >::prev(), and symlist_iterator< T, T & >::reverse().
The documentation for this struct was generated from the following file:
JETSCAPE/blob/main/external_packages/gtl/include/GTL/symlist.h