Analysis Software: CMFlashDifferenceContainer Class Reference
CMFlashDifferenceContainer Class Reference abstract
CM cluster difference due to distortions container object.
#include <coresoftware/blob/master/offline/packages/trackbase/CMFlashDifferenceContainer.h>
Public Types
convenient shortuts
using Map = std::map< unsigned int, CMFlashDifference * >
using Iterator = Map::iterator
using ConstIterator = Map::const_iterator
using Range = std::pair< Iterator, Iterator >
using ConstRange = std::pair< ConstIterator, ConstIterator >
Public Member Functions
void Reset () override
reset method
void identify (std::ostream &=std::cout) const override
identify object
virtual void addDifferenceSpecifyKey (const unsigned int, CMFlashDifference *)=0
add a differences with specific key
virtual void removeDifference (unsigned int)
remove differences
virtual ConstRange getDifferences () const =0
return all differences
virtual CMFlashDifference * findDifference (unsigned int) const
find differences matching given key
virtual unsigned int size () const
total number of differences
Public Member Functions inherited from PHObject
PHObject ()
ctor
~PHObject () override
dtor
virtual PHObject * CloneMe () const
Virtual copy constructor.
virtual PHObject * clone () const final
PHObject * Clone (const char *newname="") const final
void Copy (TObject &object) const final
virtual int isValid () const
isValid returns non zero if object contains vailid data
virtual int Integrate () const
virtual int Integrate (PHObject *)
virtual void CopyFrom (const PHObject *obj)
Protected Member Functions
CMFlashDifferenceContainer ()=default
constructor
Detailed Description
CM cluster difference due to distortions container object.
Definition at line 22 of file CMFlashDifferenceContainer.h.
View newest version in sPHENIX GitHub at line 22 of file CMFlashDifferenceContainer.h
Member Typedef Documentation
using CMFlashDifferenceContainer::ConstIterator = Map::const_iterator
Definition at line 30 of file CMFlashDifferenceContainer.h.
View newest version in sPHENIX GitHub at line 30 of file CMFlashDifferenceContainer.h
using CMFlashDifferenceContainer::ConstRange = std::pair<ConstIterator, ConstIterator>
Definition at line 32 of file CMFlashDifferenceContainer.h.
View newest version in sPHENIX GitHub at line 32 of file CMFlashDifferenceContainer.h
using CMFlashDifferenceContainer::Iterator = Map::iterator
Definition at line 29 of file CMFlashDifferenceContainer.h.
View newest version in sPHENIX GitHub at line 29 of file CMFlashDifferenceContainer.h
using CMFlashDifferenceContainer::Map = std::map<unsigned int, CMFlashDifference *>
Definition at line 28 of file CMFlashDifferenceContainer.h.
View newest version in sPHENIX GitHub at line 28 of file CMFlashDifferenceContainer.h
using CMFlashDifferenceContainer::Range = std::pair<Iterator, Iterator>
Definition at line 31 of file CMFlashDifferenceContainer.h.
View newest version in sPHENIX GitHub at line 31 of file CMFlashDifferenceContainer.h
Constructor & Destructor Documentation
CMFlashDifferenceContainer::CMFlashDifferenceContainer () protected default
constructor
Member Function Documentation
virtual void CMFlashDifferenceContainer::addDifferenceSpecifyKey (const unsigned int, CMFlashDifference *) pure virtual
add a differences with specific key
Implemented in CMFlashDifferenceContainerv1.
Referenced by PHTpcCentralMembraneMatcher::process_event().
virtual CMFlashDifference* CMFlashDifferenceContainer::findDifference (unsigned int) const inline virtual
find differences matching given key
Reimplemented in CMFlashDifferenceContainerv1.
Definition at line 51 of file CMFlashDifferenceContainer.h.
View newest version in sPHENIX GitHub at line 51 of file CMFlashDifferenceContainer.h
virtual ConstRange CMFlashDifferenceContainer::getDifferences () const pure virtual
return all differences
Implemented in CMFlashDifferenceContainerv1.
Referenced by PHTpcCentralMembraneMatcher::process_event().
void CMFlashDifferenceContainer::identify (std::ostream & = std::cout) const inline override virtual
identify object
Reimplemented from PHObject.
Reimplemented in CMFlashDifferenceContainerv1.
Definition at line 39 of file CMFlashDifferenceContainer.h.
View newest version in sPHENIX GitHub at line 39 of file CMFlashDifferenceContainer.h
virtual void CMFlashDifferenceContainer::removeDifference (unsigned int) inline virtual
remove differences
Reimplemented in CMFlashDifferenceContainerv1.
Definition at line 45 of file CMFlashDifferenceContainer.h.
View newest version in sPHENIX GitHub at line 45 of file CMFlashDifferenceContainer.h
void CMFlashDifferenceContainer::Reset () inline override virtual
reset method
Reimplemented from PHObject.
Reimplemented in CMFlashDifferenceContainerv1.
Definition at line 36 of file CMFlashDifferenceContainer.h.
View newest version in sPHENIX GitHub at line 36 of file CMFlashDifferenceContainer.h
virtual unsigned int CMFlashDifferenceContainer::size (void) const inline virtual
total number of differences
Reimplemented in CMFlashDifferenceContainerv1.
Definition at line 54 of file CMFlashDifferenceContainer.h.
View newest version in sPHENIX GitHub at line 54 of file CMFlashDifferenceContainer.h
Referenced by PHTpcCentralMembraneMatcher::process_event().
The documentation for this class was generated from the following file:
coresoftware/blob/master/offline/packages/trackbase/CMFlashDifferenceContainer.h