Analysis Software: ActsExamples::TrkrClusterMultiTrajectory Struct Reference
ActsExamples::TrkrClusterMultiTrajectory Struct Reference
Struct for truth track fitting/finding result with Acts::KalmanFitter/Acts::CombinatorialKalmanFilter.
#include <acts/blob/sPHENIX/Examples/Framework/include/ActsExamples/EventData/TrkrClusterMultiTrajectory.hpp>
Public Member Functions
TrkrClusterMultiTrajectory ()=default
Default constructor.
TrkrClusterMultiTrajectory (const Acts::MultiTrajectory< SourceLink > &multiTraj, const std::vector< size_t > &tTips, const IndexedParams &parameters, const int &vertexId)
Constructor from multiTrajectory and fitted track parameters.
TrkrClusterMultiTrajectory (const TrkrClusterMultiTrajectory &rhs)
Copy constructor.
TrkrClusterMultiTrajectory (TrkrClusterMultiTrajectory &&rhs)
Copy move constructor.
~TrkrClusterMultiTrajectory ()=default
Default destructor.
TrkrClusterMultiTrajectory & operator= (const TrkrClusterMultiTrajectory &rhs)
assignment operator
TrkrClusterMultiTrajectory & operator= (TrkrClusterMultiTrajectory &&rhs)
assignment move operator
bool hasTrajectory (const size_t &entryIndex) const
Indicator if a trajectory exists.
bool hasTrackParameters (const size_t &entryIndex) const
Indicator if there is fitted track parameters for one trajectory.
std::pair< std::vector< size_t >
, Acts::MultiTrajectory
< SourceLink > > trajectory () const
Getter for multiTrajectory.
const Acts::BoundTrackParameters & trackParameters (const size_t &entryIndex) const
Getter of fitted track parameters for one trajectory.
Private Attributes
Acts::MultiTrajectory< SourceLink > m_multiTrajectory
std::vector< size_t > m_trackTips = {}
IndexedParams m_trackParameters = {}
unsigned int m_vertexId = 9999
Detailed Description
Struct for truth track fitting/finding result with Acts::KalmanFitter/Acts::CombinatorialKalmanFilter.
It contains a MultiTrajectory with a vector of entry indices for individual trajectories, and a map of fitted parameters indexed by the entry index. In case of track fitting, there is at most one trajectory in the MultiTrajectory; In case of track finding, there could be multiple trajectories in the MultiTrajectory.
Note
The MultiTrajectory is thought to be empty if there is no entry index
Definition at line 33 of file TrkrClusterMultiTrajectory.hpp.
View newest version in sPHENIX GitHub at line 33 of file TrkrClusterMultiTrajectory.hpp
Constructor & Destructor Documentation
ActsExamples::TrkrClusterMultiTrajectory::TrkrClusterMultiTrajectory () default
Default constructor.
ActsExamples::TrkrClusterMultiTrajectory::TrkrClusterMultiTrajectory (const Acts::MultiTrajectory< SourceLink > & multiTraj, const std::vector< size_t > & tTips, const IndexedParams & parameters, const int & vertexId) inline
Constructor from multiTrajectory and fitted track parameters.
Parameters
multiTraj The multiTrajectory
tTips The entry indices for trajectories in multiTrajectory
parameters The fitted track parameters indexed by trajectory entry index
Definition at line 45 of file TrkrClusterMultiTrajectory.hpp.
View newest version in sPHENIX GitHub at line 45 of file TrkrClusterMultiTrajectory.hpp
ActsExamples::TrkrClusterMultiTrajectory::TrkrClusterMultiTrajectory (const TrkrClusterMultiTrajectory & rhs) inline
Copy constructor.
Parameters
rhs The source TrkrClusterMultiTrajectory
Definition at line 57 of file TrkrClusterMultiTrajectory.hpp.
View newest version in sPHENIX GitHub at line 57 of file TrkrClusterMultiTrajectory.hpp
ActsExamples::TrkrClusterMultiTrajectory::TrkrClusterMultiTrajectory (TrkrClusterMultiTrajectory && rhs) inline
Copy move constructor.
Parameters
rhs The source TrkrClusterMultiTrajectory
Definition at line 66 of file TrkrClusterMultiTrajectory.hpp.
View newest version in sPHENIX GitHub at line 66 of file TrkrClusterMultiTrajectory.hpp
ActsExamples::TrkrClusterMultiTrajectory::~TrkrClusterMultiTrajectory () default
Default destructor.
Member Function Documentation
bool ActsExamples::TrkrClusterMultiTrajectory::hasTrackParameters (const size_t & entryIndex) const inline
Indicator if there is fitted track parameters for one trajectory.
Parameters
entryIndex The trajectory entry index
Returns
Whether having fitted track parameters or not
Definition at line 112 of file TrkrClusterMultiTrajectory.hpp.
View newest version in sPHENIX GitHub at line 112 of file TrkrClusterMultiTrajectory.hpp
References m_trackParameters.
Referenced by ActsEvaluator::evaluateTrackFits(), and ActsEvaluator::fillFittedTrackParams().
bool ActsExamples::TrkrClusterMultiTrajectory::hasTrajectory (const size_t & entryIndex) const inline
Indicator if a trajectory exists.
Parameters
entryIndex The trajectory entry index
Returns
Whether there is trajectory with provided entry index
Definition at line 103 of file TrkrClusterMultiTrajectory.hpp.
View newest version in sPHENIX GitHub at line 103 of file TrkrClusterMultiTrajectory.hpp
References count, and m_trackTips.
TrkrClusterMultiTrajectory& ActsExamples::TrkrClusterMultiTrajectory::operator= (const TrkrClusterMultiTrajectory & rhs) inline
assignment operator
Parameters
rhs The source TrkrClusterMultiTrajectory
Definition at line 79 of file TrkrClusterMultiTrajectory.hpp.
View newest version in sPHENIX GitHub at line 79 of file TrkrClusterMultiTrajectory.hpp
References m_multiTrajectory, m_trackParameters, m_trackTips, and m_vertexId.
TrkrClusterMultiTrajectory& ActsExamples::TrkrClusterMultiTrajectory::operator= (TrkrClusterMultiTrajectory && rhs) inline
assignment move operator
Parameters
rhs The source TrkrClusterMultiTrajectory
Definition at line 90 of file TrkrClusterMultiTrajectory.hpp.
View newest version in sPHENIX GitHub at line 90 of file TrkrClusterMultiTrajectory.hpp
References m_multiTrajectory, m_trackParameters, m_trackTips, m_vertexId, and testing::internal::move().
const Acts::BoundTrackParameters& ActsExamples::TrkrClusterMultiTrajectory::trackParameters (const size_t & entryIndex) const inline
Getter of fitted track parameters for one trajectory.
Parameters
entryIndex The trajectory entry index
Returns
The fitted track parameters of the trajectory
Definition at line 131 of file TrkrClusterMultiTrajectory.hpp.
View newest version in sPHENIX GitHub at line 131 of file TrkrClusterMultiTrajectory.hpp
References it, m_trackParameters, and nlohmann::to_string().
Referenced by PHActsToSvtxTracks::createSvtxTrack(), ActsEvaluator::evaluateTrackFits(), ActsEvaluator::fillFittedTrackParams(), and PHActsTrkFitter::updateSvtxTrack().
std::pair<std::vector<size_t>, Acts::MultiTrajectory<SourceLink> > ActsExamples::TrkrClusterMultiTrajectory::trajectory () const inline
Getter for multiTrajectory.
Returns
The multiTrajectory with trajectory entry indices
Note
It could return an empty multiTrajectory
Definition at line 122 of file TrkrClusterMultiTrajectory.hpp.
View newest version in sPHENIX GitHub at line 122 of file TrkrClusterMultiTrajectory.hpp
References m_multiTrajectory, and m_trackTips.
Referenced by PHActsToSvtxTracks::createSvtxTrack(), ActsEvaluator::evaluateTrackFits(), ActsTransformations::fillSvtxTrackStates(), PHActsTrkFitter::updateSvtxTrack(), and ActsEvaluator::visitTrackStates().
Member Data Documentation
Acts::MultiTrajectory<SourceLink> ActsExamples::TrkrClusterMultiTrajectory::m_multiTrajectory private
Definition at line 144 of file TrkrClusterMultiTrajectory.hpp.
View newest version in sPHENIX GitHub at line 144 of file TrkrClusterMultiTrajectory.hpp
Referenced by operator=(), and trajectory().
IndexedParams ActsExamples::TrkrClusterMultiTrajectory::m_trackParameters = {} private
Definition at line 150 of file TrkrClusterMultiTrajectory.hpp.
View newest version in sPHENIX GitHub at line 150 of file TrkrClusterMultiTrajectory.hpp
Referenced by hasTrackParameters(), operator=(), and trackParameters().
std::vector<size_t> ActsExamples::TrkrClusterMultiTrajectory::m_trackTips = {} private
Definition at line 147 of file TrkrClusterMultiTrajectory.hpp.
View newest version in sPHENIX GitHub at line 147 of file TrkrClusterMultiTrajectory.hpp
Referenced by hasTrajectory(), operator=(), and trajectory().
unsigned int ActsExamples::TrkrClusterMultiTrajectory::m_vertexId = 9999 private
Definition at line 152 of file TrkrClusterMultiTrajectory.hpp.
View newest version in sPHENIX GitHub at line 152 of file TrkrClusterMultiTrajectory.hpp
Referenced by operator=().
The documentation for this struct was generated from the following file:
acts/blob/sPHENIX/Examples/Framework/include/ActsExamples/EventData/TrkrClusterMultiTrajectory.hpp