Analysis Software: MvtxPrototype2Geom Class Reference
MvtxPrototype2Geom Class Reference
#include <prototype/blob/master/offline/packages/MvtxPrototype2/MvtxPrototype2Geom.h>
Public Member Functions
MvtxPrototype2Geom ()
~MvtxPrototype2Geom ()=default
MvtxPrototype2Geom (const MvtxPrototype2Geom &src)=delete
MvtxPrototype2Geom & operator= (const MvtxPrototype2Geom &geo)=delete
const MatrixCache< TGeoHMatrix > & getCacheL2G () const
const TGeoHMatrix & getMatrixL2G (int sensID) const
bool isBuilt () const
int getSize () const
void setSize (int s)
int getLastChipIndex (int lay) const
int getFirstChipIndex (int lay) const
int getChipIndex (int lay, int chipInStave)
int getChipIndex (TrkrDefs::hitsetkey _key)
int getLayer (int index) const
int getChipInLay (int index) const
void Build ()
void setVerbose (int v)
int Verbose ()
bool detectorToGlobal (int index, int iCol, int iRow, double *glo)
bool detectorToGlobal (TrkrDefs::hitsetkey, TrkrDefs::hitkey, double *)
Static Public Member Functions
static MvtxPrototype2Geom * Instance ()
Static Public Attributes
static constexpr float s_pitchChip_IB = 100.e-4
nominal chip pitch in IB stave = 100 um.
static constexpr float s_gapLayers_TB = 4.
nominal gap between staves in 2019 TB setup = 4 cm.
Private Member Functions
TGeoHMatrix * extractMatrixSensor (int index)
void fillMatrixCache ()
Static Private Member Functions
static int getNumberOfChipsInLay ()
Private Attributes
int m_verbose
verbosity level
int m_size = 0
prebooked number of sensors
MatrixCache< TGeoHMatrix > m_l2G
Local to Global matrices.
std::vector< int > m_lastChipIndex
Static Private Attributes
static std::unique_ptr
< MvtxPrototype2Geom > s_instance
static constexpr int m_numOfLayers = 4
Number of layers.
static constexpr int m_numOfStaves = 1
Number of staves/layer.
static constexpr int m_numOfChips = 9
Number of Chips/stave.
Detailed Description
Class to create MVTX testbeam setup geometry
Definition at line 61 of file MvtxPrototype2Geom.h.
View newest version in sPHENIX GitHub at line 61 of file MvtxPrototype2Geom.h
Constructor & Destructor Documentation
MvtxPrototype2Geom::MvtxPrototype2Geom () inline
Definition at line 64 of file MvtxPrototype2Geom.h.
View newest version in sPHENIX GitHub at line 64 of file MvtxPrototype2Geom.h
References Build(), and s_instance.
Referenced by Instance().
MvtxPrototype2Geom::~MvtxPrototype2Geom () default
MvtxPrototype2Geom::MvtxPrototype2Geom (const MvtxPrototype2Geom & src) delete
Member Function Documentation
void MvtxPrototype2Geom::Build ()
Definition at line 8 of file MvtxPrototype2Geom.cc.
View newest version in sPHENIX GitHub at line 8 of file MvtxPrototype2Geom.cc
References fillMatrixCache(), isBuilt(), m_lastChipIndex, m_numOfChips, m_numOfLayers, m_numOfStaves, and setSize().
Referenced by fillMatrixCache(), and MvtxPrototype2Geom().
bool MvtxPrototype2Geom::detectorToGlobal (int index, int iCol, int iRow, double * glo) inline
Definition at line 169 of file MvtxPrototype2Geom.h.
View newest version in sPHENIX GitHub at line 169 of file MvtxPrototype2Geom.h
References SegmentationAlpide::detectorToLocal(), getMatrixL2G(), Instance(), loc, SegmentationAlpide::NCols, and SegmentationAlpide::NRows.
Referenced by detectorToGlobal().
bool MvtxPrototype2Geom::detectorToGlobal (TrkrDefs::hitsetkey _hitsetkey, TrkrDefs::hitkey _hitkey, double * glo) inline
Definition at line 183 of file MvtxPrototype2Geom.h.
View newest version in sPHENIX GitHub at line 183 of file MvtxPrototype2Geom.h
References detectorToGlobal(), getChipIndex(), MvtxDefs::getCol(), and MvtxDefs::getRow().
TGeoHMatrix * MvtxPrototype2Geom::extractMatrixSensor (int index) private
Definition at line 42 of file MvtxPrototype2Geom.cc.
View newest version in sPHENIX GitHub at line 42 of file MvtxPrototype2Geom.cc
References SegmentationAlpide::ActiveMatrixSizeCols, dy, dz, getNumberOfChipsInLay(), m_numOfChips, m_numOfLayers, SegmentationAlpide::PassiveEdgeSide, s_gapLayers_TB, s_pitchChip_IB, SegmentationAlpide::SensorLayerThicknessEff, AlignmentDefs::stv, and Verbose().
Referenced by fillMatrixCache().
void MvtxPrototype2Geom::fillMatrixCache () private
Definition at line 26 of file MvtxPrototype2Geom.cc.
View newest version in sPHENIX GitHub at line 26 of file MvtxPrototype2Geom.cc
References Build(), extractMatrixSensor(), i, m_l2G, m_size, MatrixCache< T >::setMatrix(), and MatrixCache< T >::setSize().
Referenced by Build().
const MatrixCache<TGeoHMatrix>& MvtxPrototype2Geom::getCacheL2G () const inline
Definition at line 76 of file MvtxPrototype2Geom.h.
View newest version in sPHENIX GitHub at line 76 of file MvtxPrototype2Geom.h
References m_l2G.
int MvtxPrototype2Geom::getChipIndex (int lay, int chipInStave) inline
Definition at line 91 of file MvtxPrototype2Geom.h.
View newest version in sPHENIX GitHub at line 91 of file MvtxPrototype2Geom.h
References getFirstChipIndex().
Referenced by detectorToGlobal(), and getChipIndex().
int MvtxPrototype2Geom::getChipIndex (TrkrDefs::hitsetkey _key) inline
Definition at line 95 of file MvtxPrototype2Geom.h.
View newest version in sPHENIX GitHub at line 95 of file MvtxPrototype2Geom.h
References MvtxDefs::getChipId(), getChipIndex(), and TrkrDefs::getLayer().
int MvtxPrototype2Geom::getChipInLay (int index) const inline
Definition at line 99 of file MvtxPrototype2Geom.h.
View newest version in sPHENIX GitHub at line 99 of file MvtxPrototype2Geom.h
References m_numOfChips.
int MvtxPrototype2Geom::getFirstChipIndex (int lay) const inline
Definition at line 90 of file MvtxPrototype2Geom.h.
View newest version in sPHENIX GitHub at line 90 of file MvtxPrototype2Geom.h
References m_lastChipIndex.
Referenced by getChipIndex().
int MvtxPrototype2Geom::getLastChipIndex (int lay) const inline
Definition at line 89 of file MvtxPrototype2Geom.h.
View newest version in sPHENIX GitHub at line 89 of file MvtxPrototype2Geom.h
References m_lastChipIndex.
int MvtxPrototype2Geom::getLayer (int index) const inline
Definition at line 98 of file MvtxPrototype2Geom.h.
View newest version in sPHENIX GitHub at line 98 of file MvtxPrototype2Geom.h
References m_numOfChips.
const TGeoHMatrix& MvtxPrototype2Geom::getMatrixL2G (int sensID) const inline
Definition at line 77 of file MvtxPrototype2Geom.h.
View newest version in sPHENIX GitHub at line 77 of file MvtxPrototype2Geom.h
References MatrixCache< T >::getMatrix(), and m_l2G.
Referenced by detectorToGlobal().
static int MvtxPrototype2Geom::getNumberOfChipsInLay () inline static private
Definition at line 124 of file MvtxPrototype2Geom.h.
View newest version in sPHENIX GitHub at line 124 of file MvtxPrototype2Geom.h
References m_numOfChips, and m_numOfStaves.
Referenced by extractMatrixSensor().
int MvtxPrototype2Geom::getSize () const inline
Definition at line 79 of file MvtxPrototype2Geom.h.
View newest version in sPHENIX GitHub at line 79 of file MvtxPrototype2Geom.h
References m_size.
static MvtxPrototype2Geom* MvtxPrototype2Geom::Instance () inline static
Definition at line 101 of file MvtxPrototype2Geom.h.
View newest version in sPHENIX GitHub at line 101 of file MvtxPrototype2Geom.h
References MvtxPrototype2Geom(), and s_instance.
Referenced by MvtxPrototype2Clusterizer::ClusterMvtx(), and detectorToGlobal().
bool MvtxPrototype2Geom::isBuilt () const inline
Definition at line 78 of file MvtxPrototype2Geom.h.
View newest version in sPHENIX GitHub at line 78 of file MvtxPrototype2Geom.h
References m_size.
Referenced by Build().
MvtxPrototype2Geom& MvtxPrototype2Geom::operator= (const MvtxPrototype2Geom & geo) delete
void MvtxPrototype2Geom::setSize (int s) inline
Definition at line 81 of file MvtxPrototype2Geom.h.
View newest version in sPHENIX GitHub at line 81 of file MvtxPrototype2Geom.h
References m_size, and physmon_simulation::s.
Referenced by Build().
void MvtxPrototype2Geom::setVerbose (int v) inline
Definition at line 111 of file MvtxPrototype2Geom.h.
View newest version in sPHENIX GitHub at line 111 of file MvtxPrototype2Geom.h
References m_verbose, and testSigmaEff::v.
int MvtxPrototype2Geom::Verbose () inline
Definition at line 112 of file MvtxPrototype2Geom.h.
View newest version in sPHENIX GitHub at line 112 of file MvtxPrototype2Geom.h
References m_verbose.
Referenced by extractMatrixSensor().
Member Data Documentation
MatrixCache<TGeoHMatrix> MvtxPrototype2Geom::m_l2G private
Local to Global matrices.
Definition at line 135 of file MvtxPrototype2Geom.h.
View newest version in sPHENIX GitHub at line 135 of file MvtxPrototype2Geom.h
Referenced by fillMatrixCache(), getCacheL2G(), and getMatrixL2G().
std::vector<int> MvtxPrototype2Geom::m_lastChipIndex private
Definition at line 141 of file MvtxPrototype2Geom.h.
View newest version in sPHENIX GitHub at line 141 of file MvtxPrototype2Geom.h
Referenced by Build(), getFirstChipIndex(), and getLastChipIndex().
constexpr int MvtxPrototype2Geom::m_numOfChips = 9 static private
Number of Chips/stave.
Definition at line 139 of file MvtxPrototype2Geom.h.
View newest version in sPHENIX GitHub at line 139 of file MvtxPrototype2Geom.h
Referenced by Build(), extractMatrixSensor(), getChipInLay(), getLayer(), and getNumberOfChipsInLay().
constexpr int MvtxPrototype2Geom::m_numOfLayers = 4 static private
Number of layers.
Definition at line 137 of file MvtxPrototype2Geom.h.
View newest version in sPHENIX GitHub at line 137 of file MvtxPrototype2Geom.h
Referenced by Build(), and extractMatrixSensor().
constexpr int MvtxPrototype2Geom::m_numOfStaves = 1 static private
Number of staves/layer.
Definition at line 138 of file MvtxPrototype2Geom.h.
View newest version in sPHENIX GitHub at line 138 of file MvtxPrototype2Geom.h
Referenced by Build(), and getNumberOfChipsInLay().
int MvtxPrototype2Geom::m_size = 0 private
prebooked number of sensors
Definition at line 134 of file MvtxPrototype2Geom.h.
View newest version in sPHENIX GitHub at line 134 of file MvtxPrototype2Geom.h
Referenced by fillMatrixCache(), getSize(), isBuilt(), and setSize().
int MvtxPrototype2Geom::m_verbose private
verbosity level
Definition at line 132 of file MvtxPrototype2Geom.h.
View newest version in sPHENIX GitHub at line 132 of file MvtxPrototype2Geom.h
Referenced by setVerbose(), and Verbose().
constexpr float MvtxPrototype2Geom::s_gapLayers_TB = 4. static
nominal gap between staves in 2019 TB setup = 4 cm.
Definition at line 116 of file MvtxPrototype2Geom.h.
View newest version in sPHENIX GitHub at line 116 of file MvtxPrototype2Geom.h
Referenced by extractMatrixSensor().
std::unique_ptr< MvtxPrototype2Geom > MvtxPrototype2Geom::s_instance static private
Definition at line 133 of file MvtxPrototype2Geom.h.
View newest version in sPHENIX GitHub at line 133 of file MvtxPrototype2Geom.h
Referenced by Instance(), and MvtxPrototype2Geom().
constexpr float MvtxPrototype2Geom::s_pitchChip_IB = 100.e-4 static
nominal chip pitch in IB stave = 100 um.
Definition at line 115 of file MvtxPrototype2Geom.h.
View newest version in sPHENIX GitHub at line 115 of file MvtxPrototype2Geom.h
Referenced by extractMatrixSensor().
The documentation for this class was generated from the following files:
prototype/blob/master/offline/packages/MvtxPrototype2/MvtxPrototype2Geom.h
prototype/blob/master/offline/packages/MvtxPrototype2/MvtxPrototype2Geom.cc