Analysis Software: trento::Nucleon Class Reference
trento::Nucleon Class Reference
#include <JETSCAPE/blob/main/external_packages/trento/src/nucleon.h>
Public Member Functions
Nucleon ()=default
double x () const
The transverse x position.
double y () const
The transverse y position.
double z () const
The longitudinal z position.
bool is_participant () const
Whether or not this nucleon is a participant.
Private Member Functions
void set_position (double x, double y, double z)
Set the position and reset participant status to false.
void set_participant ()
Mark as a participant.
Private Attributes
double x_
Internal storage of the position.
double y_
double z_
bool participant_
Internal storage of participant status.
Friends
class Nucleus
A Nucleus must be able to set its Nucleon positions.
bool NucleonProfile::participate (Nucleon &, Nucleon &) const
Detailed Description
Represents a single nucleon. Stores its position and whether or not it's a participant. These properties are globally readable, but can only be set through Nucleus and NucleonProfile.
Definition at line 95 of file nucleon.h.
View newest version in sPHENIX GitHub at line 95 of file nucleon.h
Constructor & Destructor Documentation
trento::Nucleon::Nucleon () default
Only a default constructor is necessary-–the class is designed to be constructed once and repeatedly updated.
Member Function Documentation
bool trento::Nucleon::is_participant () const inline
Whether or not this nucleon is a participant.
Definition at line 151 of file nucleon.h.
View newest version in sPHENIX GitHub at line 151 of file nucleon.h
References participant_.
Referenced by trento::NucleonProfile::participate().
void trento::Nucleon::set_participant () inline private
Mark as a participant.
Definition at line 162 of file nucleon.h.
View newest version in sPHENIX GitHub at line 162 of file nucleon.h
References participant_.
Referenced by trento::NucleonProfile::participate().
void trento::Nucleon::set_position (double x, double y, double z) inline private
Set the position and reset participant status to false.
Definition at line 155 of file nucleon.h.
View newest version in sPHENIX GitHub at line 155 of file nucleon.h
References participant_, x(), x_, y(), y_, z(), and z_.
double trento::Nucleon::x () const inline
The transverse x position.
Definition at line 139 of file nucleon.h.
View newest version in sPHENIX GitHub at line 139 of file nucleon.h
References x_.
Referenced by trento::Event::accumulate_TAB(), trento::NucleonProfile::participate(), and set_position().
double trento::Nucleon::y () const inline
The transverse y position.
Definition at line 143 of file nucleon.h.
View newest version in sPHENIX GitHub at line 143 of file nucleon.h
References y_.
Referenced by trento::Event::accumulate_TAB(), trento::NucleonProfile::participate(), and set_position().
double trento::Nucleon::z () const inline
The longitudinal z position.
Definition at line 147 of file nucleon.h.
View newest version in sPHENIX GitHub at line 147 of file nucleon.h
References z_.
Referenced by set_position().
Friends And Related Function Documentation
bool NucleonProfile::participate (Nucleon & , Nucleon &) const friend
The NucleonProfile samples participants so must be able to set participation status.
friend class Nucleus friend
A Nucleus must be able to set its Nucleon positions.
Definition at line 115 of file nucleon.h.
View newest version in sPHENIX GitHub at line 115 of file nucleon.h
Member Data Documentation
bool trento::Nucleon::participant_ private
Internal storage of participant status.
Definition at line 131 of file nucleon.h.
View newest version in sPHENIX GitHub at line 131 of file nucleon.h
Referenced by is_participant(), set_participant(), and set_position().
double trento::Nucleon::x_ private
Internal storage of the position.
Definition at line 128 of file nucleon.h.
View newest version in sPHENIX GitHub at line 128 of file nucleon.h
Referenced by set_position(), and x().
double trento::Nucleon::y_ private
Definition at line 128 of file nucleon.h.
View newest version in sPHENIX GitHub at line 128 of file nucleon.h
Referenced by set_position(), and y().
double trento::Nucleon::z_ private
Definition at line 128 of file nucleon.h.
View newest version in sPHENIX GitHub at line 128 of file nucleon.h
Referenced by set_position(), and z().
The documentation for this class was generated from the following file:
JETSCAPE/blob/main/external_packages/trento/src/nucleon.h