Analysis Software: ActsExamples::DataHandleBase Class Reference
ActsExamples::DataHandleBase Class Reference abstract
#include <acts/blob/sPHENIX/Examples/Framework/include/ActsExamples/Framework/DataHandle.hpp>
Inherited by ActsExamples::ReadDataHandle< T >, ActsExamples::WriteDataHandle< T >, ActsExamples::ReadDataHandle< ClusterContainer >, ActsExamples::ReadDataHandle< Clusters >, ActsExamples::ReadDataHandle< ConstTrackContainer >, ActsExamples::ReadDataHandle< ExtractedSimulationProcessContainer >, ActsExamples::ReadDataHandle< GeometryIdMultimap< Acts::PlanarModuleCluster > >, ActsExamples::ReadDataHandle< GeometryIdMultimap< T > >, ActsExamples::ReadDataHandle< GeometryIdMultiset< T > >, ActsExamples::ReadDataHandle< HelloDataCollection >, ActsExamples::ReadDataHandle< HitIds >, ActsExamples::ReadDataHandle< HitParticlesMap >, ActsExamples::ReadDataHandle< HitSimHitsMap >, ActsExamples::ReadDataHandle< IndexMultimap< ActsFatras::Barcode > >, ActsExamples::ReadDataHandle< IndexMultimap< Index > >, ActsExamples::ReadDataHandle< IndexSourceLinkContainer >, ActsExamples::ReadDataHandle< Map >, ActsExamples::ReadDataHandle< MeasurementContainer >, ActsExamples::ReadDataHandle< ProtoTrackContainer >, ActsExamples::ReadDataHandle< ProtoVertexContainer >, ActsExamples::ReadDataHandle< SimHitContainer >, ActsExamples::ReadDataHandle< SimParticleContainer >, ActsExamples::ReadDataHandle< SimSeedContainer >, ActsExamples::ReadDataHandle< SimSpacePointContainer >, ActsExamples::ReadDataHandle< std::unordered_map< size_t, Acts::RecordedMaterialTrack > >, ActsExamples::ReadDataHandle< std::vector< Acts::BoundTrackParameters > >, ActsExamples::ReadDataHandle< std::vector< Acts::Vertex< Acts::BoundTrackParameters > > >, ActsExamples::ReadDataHandle< std::vector< HepMC3::GenEvent > >, ActsExamples::ReadDataHandle< std::vector< PropagationSteps > >, ActsExamples::ReadDataHandle< std::vector< std::vector< step_t > > >, ActsExamples::ReadDataHandle< TrackParametersContainer >, ActsExamples::ReadDataHandle< TrajectoriesContainer >, ActsExamples::ReadDataHandle< write_data_t >, ActsExamples::WriteDataHandle< Acts::Vertex< Acts::BoundTrackParameters > >, ActsExamples::WriteDataHandle< ActsExamples::ExtractedSimulationProcessContainer >, ActsExamples::WriteDataHandle< AlignmentParameters >, ActsExamples::WriteDataHandle< ClusterContainer >, ActsExamples::WriteDataHandle< ConstTrackContainer >, ActsExamples::WriteDataHandle< GeometryIdMultimap< Acts::PlanarModuleCluster > >, ActsExamples::WriteDataHandle< GeometryIdMultiset< IndexSourceLink > >, ActsExamples::WriteDataHandle< HelloDataCollection >, ActsExamples::WriteDataHandle< IndexMultimap< ActsFatras::Barcode > >, ActsExamples::WriteDataHandle< IndexMultimap< Index > >, ActsExamples::WriteDataHandle< IndexSourceLinkContainer >, ActsExamples::WriteDataHandle< Map >, ActsExamples::WriteDataHandle< MeasurementContainer >, ActsExamples::WriteDataHandle< ProtoTrackContainer >, ActsExamples::WriteDataHandle< ProtoVertexContainer >, ActsExamples::WriteDataHandle< SimHitContainer >, ActsExamples::WriteDataHandle< SimParticleContainer >, ActsExamples::WriteDataHandle< SimSeedContainer >, ActsExamples::WriteDataHandle< SimSpacePointContainer >, ActsExamples::WriteDataHandle< std::unordered_map< size_t, Acts::RecordedMaterialTrack > >, ActsExamples::WriteDataHandle< std::vector< Acts::BoundTrackParameters > >, ActsExamples::WriteDataHandle< std::vector< Acts::DigitizationSourceLink > >, ActsExamples::WriteDataHandle< std::vector< Acts::Vector4 > >, ActsExamples::WriteDataHandle< std::vector< Acts::Vertex< Acts::BoundTrackParameters > > >, ActsExamples::WriteDataHandle< std::vector< HepMC3::GenEvent > >, ActsExamples::WriteDataHandle< std::vector< std::vector< Acts::detail::Step > > >, ActsExamples::WriteDataHandle< std::vector< uint32_t > >, ActsExamples::WriteDataHandle< std::vector< uint64_t > >, ActsExamples::WriteDataHandle< TrackParametersContainer >, ActsExamples::WriteDataHandle< TrajectoriesContainer >, and ActsExamples::WriteDataHandle< VertexCollection >.
Public Member Functions
const std::string & key () const
virtual const std::type_info & typeInfo () const =0
bool isInitialized () const
const std::string & name () const
void maybeInitialize (const std::string &key)
virtual bool isCompatible (const DataHandleBase &other) const =0
std::string fullName () const
Protected Member Functions
virtual ~DataHandleBase ()=default
DataHandleBase (SequenceElement *parent, const std::string &name)
DataHandleBase (const DataHandleBase &)=delete
DataHandleBase (DataHandleBase &&)=default
Protected Attributes
SequenceElement * m_parent {nullptr}
std::string m_name
std::optional< std::string > m_key {}
Detailed Description
Definition at line 21 of file DataHandle.hpp.
View newest version in sPHENIX GitHub at line 21 of file DataHandle.hpp
Constructor & Destructor Documentation
virtual ActsExamples::DataHandleBase::~DataHandleBase () protected virtual default
ActsExamples::DataHandleBase::DataHandleBase (SequenceElement * parent, const std::string & name) inline protected
Definition at line 25 of file DataHandle.hpp.
View newest version in sPHENIX GitHub at line 25 of file DataHandle.hpp
ActsExamples::DataHandleBase::DataHandleBase (const DataHandleBase &) protected delete
ActsExamples::DataHandleBase::DataHandleBase (DataHandleBase &&) protected default
Member Function Documentation
std::string ActsExamples::DataHandleBase::fullName () const inline
Definition at line 49 of file DataHandle.hpp.
View newest version in sPHENIX GitHub at line 49 of file DataHandle.hpp
References m_parent, ActsExamples::SequenceElement::name(), and name().
Referenced by ActsExamples::WriteDataHandle< std::vector< Acts::BoundTrackParameters > >::initialize(), ActsExamples::ReadDataHandle< std::vector< Acts::BoundTrackParameters > >::initialize(), ActsExamples::WriteDataHandle< std::vector< Acts::BoundTrackParameters > >::operator()(), and ActsExamples::ReadDataHandle< std::vector< Acts::BoundTrackParameters > >::operator()().
virtual bool ActsExamples::DataHandleBase::isCompatible (const DataHandleBase & other) const pure virtual
Implemented in ActsExamples::ReadDataHandle< T >, ActsExamples::ReadDataHandle< IndexMultimap< Index > >, ActsExamples::ReadDataHandle< GeometryIdMultiset< T > >, ActsExamples::ReadDataHandle< IndexSourceLinkContainer >, ActsExamples::ReadDataHandle< std::vector< PropagationSteps > >, ActsExamples::ReadDataHandle< ProtoTrackContainer >, ActsExamples::ReadDataHandle< SimSeedContainer >, ActsExamples::ReadDataHandle< HitIds >, ActsExamples::ReadDataHandle< IndexMultimap< ActsFatras::Barcode > >, ActsExamples::ReadDataHandle< Map >, ActsExamples::ReadDataHandle< ProtoVertexContainer >, ActsExamples::ReadDataHandle< SimHitContainer >, ActsExamples::ReadDataHandle< HitSimHitsMap >, ActsExamples::ReadDataHandle< TrackParametersContainer >, ActsExamples::ReadDataHandle< std::vector< HepMC3::GenEvent > >, ActsExamples::ReadDataHandle< std::vector< std::vector< step_t > > >, ActsExamples::ReadDataHandle< std::unordered_map< size_t, Acts::RecordedMaterialTrack > >, ActsExamples::ReadDataHandle< TrajectoriesContainer >, ActsExamples::ReadDataHandle< HelloDataCollection >, ActsExamples::ReadDataHandle< SimSpacePointContainer >, ActsExamples::ReadDataHandle< GeometryIdMultimap< T > >, ActsExamples::ReadDataHandle< HitParticlesMap >, ActsExamples::ReadDataHandle< ExtractedSimulationProcessContainer >, ActsExamples::ReadDataHandle< ClusterContainer >, ActsExamples::ReadDataHandle< std::vector< Acts::Vertex< Acts::BoundTrackParameters > > >, ActsExamples::ReadDataHandle< GeometryIdMultimap< Acts::PlanarModuleCluster > >, ActsExamples::ReadDataHandle< SimParticleContainer >, ActsExamples::ReadDataHandle< ConstTrackContainer >, ActsExamples::ReadDataHandle< Clusters >, ActsExamples::ReadDataHandle< write_data_t >, ActsExamples::ReadDataHandle< MeasurementContainer >, ActsExamples::ReadDataHandle< std::vector< Acts::BoundTrackParameters > >, ActsExamples::WriteDataHandle< T >, ActsExamples::WriteDataHandle< std::vector< Acts::Vector4 > >, ActsExamples::WriteDataHandle< IndexMultimap< Index > >, ActsExamples::WriteDataHandle< IndexSourceLinkContainer >, ActsExamples::WriteDataHandle< SimSeedContainer >, ActsExamples::WriteDataHandle< ProtoTrackContainer >, ActsExamples::WriteDataHandle< VertexCollection >, ActsExamples::WriteDataHandle< IndexMultimap< ActsFatras::Barcode > >, ActsExamples::WriteDataHandle< Map >, ActsExamples::WriteDataHandle< SimHitContainer >, ActsExamples::WriteDataHandle< ProtoVertexContainer >, ActsExamples::WriteDataHandle< std::vector< uint32_t > >, ActsExamples::WriteDataHandle< std::vector< uint64_t > >, ActsExamples::WriteDataHandle< TrackParametersContainer >, ActsExamples::WriteDataHandle< std::vector< HepMC3::GenEvent > >, ActsExamples::WriteDataHandle< std::unordered_map< size_t, Acts::RecordedMaterialTrack > >, ActsExamples::WriteDataHandle< AlignmentParameters >, ActsExamples::WriteDataHandle< TrajectoriesContainer >, ActsExamples::WriteDataHandle< SimSpacePointContainer >, ActsExamples::WriteDataHandle< HelloDataCollection >, ActsExamples::WriteDataHandle< GeometryIdMultiset< IndexSourceLink > >, ActsExamples::WriteDataHandle< std::vector< Acts::Vertex< Acts::BoundTrackParameters > > >, ActsExamples::WriteDataHandle< ClusterContainer >, ActsExamples::WriteDataHandle< std::vector< std::vector< Acts::detail::Step > > >, ActsExamples::WriteDataHandle< GeometryIdMultimap< Acts::PlanarModuleCluster > >, ActsExamples::WriteDataHandle< SimParticleContainer >, ActsExamples::WriteDataHandle< ConstTrackContainer >, ActsExamples::WriteDataHandle< MeasurementContainer >, ActsExamples::WriteDataHandle< std::vector< Acts::DigitizationSourceLink > >, ActsExamples::WriteDataHandle< Acts::Vertex< Acts::BoundTrackParameters > >, ActsExamples::WriteDataHandle< ActsExamples::ExtractedSimulationProcessContainer >, and ActsExamples::WriteDataHandle< std::vector< Acts::BoundTrackParameters > >.
bool ActsExamples::DataHandleBase::isInitialized () const inline
Definition at line 37 of file DataHandle.hpp.
View newest version in sPHENIX GitHub at line 37 of file DataHandle.hpp
References m_key.
Referenced by ActsExamples::WriteDataHandle< std::vector< Acts::BoundTrackParameters > >::operator()(), and ActsExamples::ReadDataHandle< std::vector< Acts::BoundTrackParameters > >::operator()().
const std::string& ActsExamples::DataHandleBase::key () const inline
Definition at line 33 of file DataHandle.hpp.
View newest version in sPHENIX GitHub at line 33 of file DataHandle.hpp
References m_key.
Referenced by __example_4.f__(), __example_5.f__(), __example_6.f__(), __example_7.f__(), __example_8.f__(), conftest.RootHashAssertionError::__init__(), ActsExamples::WriteDataHandle< std::vector< Acts::BoundTrackParameters > >::initialize(), ActsExamples::ReadDataHandle< std::vector< Acts::BoundTrackParameters > >::initialize(), and maybeInitialize().
void ActsExamples::DataHandleBase::maybeInitialize (const std::string & key) inline
Definition at line 41 of file DataHandle.hpp.
View newest version in sPHENIX GitHub at line 41 of file DataHandle.hpp
References key(), and m_key.
Referenced by ActsExamples::AdaptiveMultiVertexFinderAlgorithm::AdaptiveMultiVertexFinderAlgorithm(), ActsExamples::CsvMeasurementReader::CsvMeasurementReader(), ActsExamples::CsvMeasurementWriter::CsvMeasurementWriter(), ActsExamples::CsvTrackParameterWriter::CsvTrackParameterWriter(), ActsExamples::EDM4hepMeasurementReader::EDM4hepMeasurementReader(), ActsExamples::EDM4hepMeasurementWriter::EDM4hepMeasurementWriter(), ActsExamples::EDM4hepSimHitReader::EDM4hepSimHitReader(), ActsExamples::EDM4hepSimHitWriter::EDM4hepSimHitWriter(), ActsExamples::IterativeVertexFinderAlgorithm::IterativeVertexFinderAlgorithm(), ActsExamples::RootMeasurementWriter::RootMeasurementWriter(), ActsExamples::RootParticleReader::RootParticleReader(), ActsExamples::TrackFindingAlgorithmExaTrkX::TrackFindingAlgorithmExaTrkX(), ActsExamples::TrackFittingAlgorithm::TrackFittingAlgorithm(), ActsExamples::TrackModifier::TrackModifier(), ActsExamples::TrackParamsEstimationAlgorithm::TrackParamsEstimationAlgorithm(), ActsExamples::TutorialVertexFinderAlgorithm::TutorialVertexFinderAlgorithm(), and ActsExamples::VertexFitterAlgorithm::VertexFitterAlgorithm().
const std::string& ActsExamples::DataHandleBase::name () const inline
Definition at line 39 of file DataHandle.hpp.
View newest version in sPHENIX GitHub at line 39 of file DataHandle.hpp
References m_name.
Referenced by fullName().
virtual const std::type_info& ActsExamples::DataHandleBase::typeInfo () const pure virtual
Implemented in ActsExamples::ReadDataHandle< T >, ActsExamples::ReadDataHandle< IndexMultimap< Index > >, ActsExamples::ReadDataHandle< GeometryIdMultiset< T > >, ActsExamples::ReadDataHandle< IndexSourceLinkContainer >, ActsExamples::ReadDataHandle< std::vector< PropagationSteps > >, ActsExamples::ReadDataHandle< ProtoTrackContainer >, ActsExamples::ReadDataHandle< SimSeedContainer >, ActsExamples::ReadDataHandle< HitIds >, ActsExamples::ReadDataHandle< IndexMultimap< ActsFatras::Barcode > >, ActsExamples::ReadDataHandle< Map >, ActsExamples::ReadDataHandle< ProtoVertexContainer >, ActsExamples::ReadDataHandle< SimHitContainer >, ActsExamples::ReadDataHandle< HitSimHitsMap >, ActsExamples::ReadDataHandle< TrackParametersContainer >, ActsExamples::ReadDataHandle< std::vector< HepMC3::GenEvent > >, ActsExamples::ReadDataHandle< std::vector< std::vector< step_t > > >, ActsExamples::ReadDataHandle< std::unordered_map< size_t, Acts::RecordedMaterialTrack > >, ActsExamples::ReadDataHandle< TrajectoriesContainer >, ActsExamples::ReadDataHandle< HelloDataCollection >, ActsExamples::ReadDataHandle< SimSpacePointContainer >, ActsExamples::ReadDataHandle< GeometryIdMultimap< T > >, ActsExamples::ReadDataHandle< HitParticlesMap >, ActsExamples::ReadDataHandle< ExtractedSimulationProcessContainer >, ActsExamples::ReadDataHandle< ClusterContainer >, ActsExamples::ReadDataHandle< std::vector< Acts::Vertex< Acts::BoundTrackParameters > > >, ActsExamples::ReadDataHandle< GeometryIdMultimap< Acts::PlanarModuleCluster > >, ActsExamples::ReadDataHandle< SimParticleContainer >, ActsExamples::ReadDataHandle< ConstTrackContainer >, ActsExamples::ReadDataHandle< Clusters >, ActsExamples::ReadDataHandle< write_data_t >, ActsExamples::ReadDataHandle< MeasurementContainer >, ActsExamples::ReadDataHandle< std::vector< Acts::BoundTrackParameters > >, ActsExamples::WriteDataHandle< T >, ActsExamples::WriteDataHandle< std::vector< Acts::Vector4 > >, ActsExamples::WriteDataHandle< IndexMultimap< Index > >, ActsExamples::WriteDataHandle< IndexSourceLinkContainer >, ActsExamples::WriteDataHandle< SimSeedContainer >, ActsExamples::WriteDataHandle< ProtoTrackContainer >, ActsExamples::WriteDataHandle< VertexCollection >, ActsExamples::WriteDataHandle< IndexMultimap< ActsFatras::Barcode > >, ActsExamples::WriteDataHandle< Map >, ActsExamples::WriteDataHandle< SimHitContainer >, ActsExamples::WriteDataHandle< ProtoVertexContainer >, ActsExamples::WriteDataHandle< std::vector< uint32_t > >, ActsExamples::WriteDataHandle< std::vector< uint64_t > >, ActsExamples::WriteDataHandle< TrackParametersContainer >, ActsExamples::WriteDataHandle< std::vector< HepMC3::GenEvent > >, ActsExamples::WriteDataHandle< std::unordered_map< size_t, Acts::RecordedMaterialTrack > >, ActsExamples::WriteDataHandle< AlignmentParameters >, ActsExamples::WriteDataHandle< TrajectoriesContainer >, ActsExamples::WriteDataHandle< SimSpacePointContainer >, ActsExamples::WriteDataHandle< HelloDataCollection >, ActsExamples::WriteDataHandle< GeometryIdMultiset< IndexSourceLink > >, ActsExamples::WriteDataHandle< std::vector< Acts::Vertex< Acts::BoundTrackParameters > > >, ActsExamples::WriteDataHandle< ClusterContainer >, ActsExamples::WriteDataHandle< std::vector< std::vector< Acts::detail::Step > > >, ActsExamples::WriteDataHandle< GeometryIdMultimap< Acts::PlanarModuleCluster > >, ActsExamples::WriteDataHandle< SimParticleContainer >, ActsExamples::WriteDataHandle< ConstTrackContainer >, ActsExamples::WriteDataHandle< MeasurementContainer >, ActsExamples::WriteDataHandle< std::vector< Acts::DigitizationSourceLink > >, ActsExamples::WriteDataHandle< Acts::Vertex< Acts::BoundTrackParameters > >, ActsExamples::WriteDataHandle< ActsExamples::ExtractedSimulationProcessContainer >, and ActsExamples::WriteDataHandle< std::vector< Acts::BoundTrackParameters > >.
Member Data Documentation
std::optional<std::string> ActsExamples::DataHandleBase::m_key {} protected
Definition at line 54 of file DataHandle.hpp.
View newest version in sPHENIX GitHub at line 54 of file DataHandle.hpp
Referenced by ActsExamples::WriteDataHandle< std::vector< Acts::BoundTrackParameters > >::initialize(), ActsExamples::ReadDataHandle< std::vector< Acts::BoundTrackParameters > >::initialize(), isInitialized(), key(), maybeInitialize(), ActsExamples::WriteDataHandle< std::vector< Acts::BoundTrackParameters > >::operator()(), and ActsExamples::ReadDataHandle< std::vector< Acts::BoundTrackParameters > >::operator()().
std::string ActsExamples::DataHandleBase::m_name protected
Definition at line 53 of file DataHandle.hpp.
View newest version in sPHENIX GitHub at line 53 of file DataHandle.hpp
Referenced by name().
SequenceElement* ActsExamples::DataHandleBase::m_parent {nullptr} protected
Definition at line 52 of file DataHandle.hpp.
View newest version in sPHENIX GitHub at line 52 of file DataHandle.hpp
Referenced by fullName().
The documentation for this class was generated from the following file:
acts/blob/sPHENIX/Examples/Framework/include/ActsExamples/Framework/DataHandle.hpp