Analysis Software: ActsExamples::TruthVertexFinder Exception Reference
ActsExamples::TruthVertexFinder Exception Reference final
Group particles into proto vertices using truth information.
#include <acts/blob/sPHENIX/Examples/Algorithms/TruthTracking/ActsExamples/TruthTracking/TruthVertexFinder.hpp>
Classes
struct Config
Public Member Functions
TruthVertexFinder (const Config &config, Acts::Logging::Level level)
ProcessCode execute (const AlgorithmContext &ctx) const final
const Config & config () const
Get readonly access to the config parameters.
Public Member Functions inherited from ActsExamples::IAlgorithm
IAlgorithm (std::string name, Acts::Logging::Level level=Acts::Logging::INFO)
std::string name () const override
The algorithm name.
ProcessCode internalExecute (const AlgorithmContext &context) final
ProcessCode initialize () override
Initialize the algorithm.
ProcessCode finalize () override
Finalize the algorithm.
Private Attributes
Config m_cfg
ReadDataHandle
< SimParticleContainer > m_inputParticles {this, "InputParticles"}
WriteDataHandle
< ProtoVertexContainer > m_outputProtoVertices
Additional Inherited Members
Protected Member Functions inherited from ActsExamples::IAlgorithm
const Acts::Logger & logger () const
Detailed Description
Group particles into proto vertices using truth information.
Definition at line 24 of file TruthVertexFinder.hpp.
View newest version in sPHENIX GitHub at line 24 of file TruthVertexFinder.hpp
Constructor & Destructor Documentation
ActsExamples::TruthVertexFinder::TruthVertexFinder (const Config & config, Acts::Logging::Level level)
Definition at line 26 of file TruthVertexFinder.cpp.
View newest version in sPHENIX GitHub at line 26 of file TruthVertexFinder.cpp
References ActsExamples::WriteDataHandle< T >::initialize(), ActsExamples::ReadDataHandle< T >::initialize(), ActsExamples::TruthVertexFinder::Config::inputParticles, m_cfg, m_inputParticles, m_outputProtoVertices, and ActsExamples::TruthVertexFinder::Config::outputProtoVertices.
Member Function Documentation
const Config& ActsExamples::TruthVertexFinder::config () const inline
Get readonly access to the config parameters.
Definition at line 42 of file TruthVertexFinder.hpp.
View newest version in sPHENIX GitHub at line 42 of file TruthVertexFinder.hpp
References m_cfg.
ActsExamples::ProcessCode ActsExamples::TruthVertexFinder::execute (const AlgorithmContext & context) const final virtual
Execute the algorithm for one event.
This function must be implemented by subclasses.
Implements ActsExamples::IAlgorithm.
Definition at line 40 of file TruthVertexFinder.cpp.
View newest version in sPHENIX GitHub at line 40 of file TruthVertexFinder.cpp
References ACTS_VERBOSE, parse_cmake_options::begin, distance(), end, ActsExamples::groupByPrimaryVertex(), ActsExamples::groupBySecondaryVertex(), m_cfg(), testing::internal::move(), particles, SUCCESS, and physmon_ckf_tracking::u.
Member Data Documentation
Config ActsExamples::TruthVertexFinder::m_cfg private
Definition at line 45 of file TruthVertexFinder.hpp.
View newest version in sPHENIX GitHub at line 45 of file TruthVertexFinder.hpp
Referenced by config(), and TruthVertexFinder().
ReadDataHandle<SimParticleContainer> ActsExamples::TruthVertexFinder::m_inputParticles {this, "InputParticles"} private
Definition at line 47 of file TruthVertexFinder.hpp.
View newest version in sPHENIX GitHub at line 47 of file TruthVertexFinder.hpp
Referenced by TruthVertexFinder().
WriteDataHandle<ProtoVertexContainer> ActsExamples::TruthVertexFinder::m_outputProtoVertices private
Initial value:
{
      this, "OutputProtoVertices"}
Definition at line 49 of file TruthVertexFinder.hpp.
View newest version in sPHENIX GitHub at line 49 of file TruthVertexFinder.hpp
Referenced by TruthVertexFinder().
The documentation for this exception was generated from the following files:
acts/blob/sPHENIX/Examples/Algorithms/TruthTracking/ActsExamples/TruthTracking/TruthVertexFinder.hpp
acts/blob/sPHENIX/Examples/Algorithms/TruthTracking/ActsExamples/TruthTracking/TruthVertexFinder.cpp