Analysis Software: Acts::Python::Context Struct Reference
Acts::Python::Context Struct Reference
#include <acts/blob/sPHENIX/Examples/Python/include/Acts/Plugins/Python/Utilities.hpp>
Public Member Functions
pybind11::module_ & get (const std::string &name)
template<typename... Args, typename = std::enable_if_t<sizeof...(Args) >= 2>
auto get (Args &&...args)
Public Attributes
std::unordered_map
< std::string,
pybind11::module_ > modules
Detailed Description
Definition at line 22 of file Utilities.hpp.
View newest version in sPHENIX GitHub at line 22 of file Utilities.hpp
Member Function Documentation
pybind11::module_& Acts::Python::Context::get (const std::string & name) inline
Definition at line 25 of file Utilities.hpp.
View newest version in sPHENIX GitHub at line 25 of file Utilities.hpp
References modules, and perf_headwind::name.
Referenced by Acts::Python::addAmbiguityResolution(), Acts::Python::addDetector(), Acts::Python::addDigitization(), Acts::Python::addEDM4hep(), Acts::Python::addEventData(), Acts::Python::addExampleAlgorithms(), Acts::Python::addExaTrkXTrackFinding(), Acts::Python::addExperimentalGeometry(), Acts::Python::addFramework(), Acts::Python::addGeant4HepMC3(), Acts::Python::addGenerators(), Acts::Python::addGeometry(), Acts::Python::addHepMC3(), Acts::Python::addInput(), Acts::Python::addJson(), Acts::Python::addLogging(), Acts::Python::addMagneticField(), Acts::Python::addMaterial(), Acts::Python::addObj(), Acts::Python::addOnnx(), Acts::Python::addOnnxMlpack(), Acts::Python::addOnnxNeuralCalibrator(), Acts::Python::addOutput(), Acts::Python::addPropagation(), Acts::Python::addPythia8(), Acts::Python::addSvg(), Acts::Python::addTrackFinding(), Acts::Python::addTrackFitting(), Acts::Python::addTruthTracking(), Acts::Python::addUnits(), and Acts::Python::addVertexing().
template<typename... Args, typename = std::enable_if_t<sizeof...(Args) >= 2> auto Acts::Python::Context::get (Args &&... args) inline
Definition at line 28 of file Utilities.hpp.
View newest version in sPHENIX GitHub at line 28 of file Utilities.hpp
References check_smearing_config::args, std::tr1::make_tuple(), and modules.
Member Data Documentation
std::unordered_map<std::string, pybind11::module_> Acts::Python::Context::modules
Definition at line 23 of file Utilities.hpp.
View newest version in sPHENIX GitHub at line 23 of file Utilities.hpp
Referenced by Acts::Python::addOnnx(), Acts::Python::addPythia8(), get(), and PYBIND11_MODULE().
The documentation for this struct was generated from the following file:
acts/blob/sPHENIX/Examples/Python/include/Acts/Plugins/Python/Utilities.hpp