Analysis Software: TrkrHitSetv1 Class Reference
TrkrHitSetv1 Class Reference
#include <coresoftware/blob/master/offline/packages/trackbase/TrkrHitSetv1.h>
Public Member Functions
TrkrHitSetv1 ()=default
~TrkrHitSetv1 () override
void identify (std::ostream &os=std::cout) const override
TObject functions.
void Reset () override
Clear Event.
void setHitSetKey (const TrkrDefs::hitsetkey key) override
Set the key for this object.
TrkrDefs::hitsetkey getHitSetKey () const override
Get the key for this object.
ConstIterator addHitSpecificKey (const TrkrDefs::hitkey, TrkrHit *) override
Add a hit to this container using a specific key.
void removeHit (TrkrDefs::hitkey) override
Remove a hit using its key.
TrkrHit * getHit (const TrkrDefs::hitkey) const override
Get a specific hit based on its index.
ConstRange getHits () const override
Get all hits.
unsigned int size () const override
Get the number of hits stored.
Private Member Functions
ClassDefOverride (TrkrHitSetv1, 1)
Private Attributes
TrkrDefs::hitsetkey m_hitSetKey = TrkrDefs::HITSETKEYMAX
unique key for this object
Map m_hits
storage for TrkrHit objects
Additional Inherited Members
Public Types inherited from TrkrHitSet
using Map = std::map< TrkrDefs::hitkey, TrkrHit * >
using ConstIterator = Map::const_iterator
using ConstRange = std::pair< ConstIterator, ConstIterator >
Protected Member Functions inherited from TrkrHitSet
TrkrHitSet ()=default
ctor, not to be called
Detailed Description
Definition at line 20 of file TrkrHitSetv1.h.
View newest version in sPHENIX GitHub at line 20 of file TrkrHitSetv1.h
Constructor & Destructor Documentation
TrkrHitSetv1::TrkrHitSetv1 () default
TrkrHitSetv1::~TrkrHitSetv1 () inline override
Definition at line 25 of file TrkrHitSetv1.h.
View newest version in sPHENIX GitHub at line 25 of file TrkrHitSetv1.h
References Reset().
Member Function Documentation
TrkrHitSetv1::ConstIterator TrkrHitSetv1::addHitSpecificKey (const TrkrDefs::hitkey , TrkrHit *) override virtual
Add a hit to this container using a specific key.
Parameters
[in] key Hit key
[in] hit Hit to be added.
NOTE: This TrkrHitSet takes ownership of the passed TrkrHit pointer and will delete it in the Reset() method.
Reimplemented from TrkrHitSet.
Definition at line 59 of file TrkrHitSetv1.cc.
View newest version in sPHENIX GitHub at line 59 of file TrkrHitSetv1.cc
References m_hits.
TrkrHitSetv1::ClassDefOverride (TrkrHitSetv1 , 1) private
TrkrHit * TrkrHitSetv1::getHit (const TrkrDefs::hitkey) const override virtual
Get a specific hit based on its index.
Parameters
key of the desired hit
[out] Pointer to the desired hit. nullptr if no hit.
Get a desired hit based on its key.
Reimplemented from TrkrHitSet.
Definition at line 72 of file TrkrHitSetv1.cc.
View newest version in sPHENIX GitHub at line 72 of file TrkrHitSetv1.cc
References it, and m_hits.
TrkrHitSetv1::ConstRange TrkrHitSetv1::getHits () const override virtual
Get all hits.
Parameters
[out] Pair of iterator to vector begin and end
Reimplemented from TrkrHitSet.
Definition at line 81 of file TrkrHitSetv1.cc.
View newest version in sPHENIX GitHub at line 81 of file TrkrHitSetv1.cc
References m_hits.
TrkrDefs::hitsetkey TrkrHitSetv1::getHitSetKey () const inline override virtual
Get the key for this object.
Parameters
[out] object key
Reimplemented from TrkrHitSet.
Definition at line 39 of file TrkrHitSetv1.h.
View newest version in sPHENIX GitHub at line 39 of file TrkrHitSetv1.h
References m_hitSetKey.
Referenced by identify().
void TrkrHitSetv1::identify (std::ostream & = std::cout) const override virtual
TObject functions.
Reimplemented from TrkrHitSet.
Definition at line 25 of file TrkrHitSetv1.cc.
View newest version in sPHENIX GitHub at line 25 of file TrkrHitSetv1.cc
References entry, getHitSetKey(), TrkrDefs::getLayer(), TrkrDefs::getTrkrId(), layer, m_hits, and m_hitSetKey.
Referenced by removeHit().
void TrkrHitSetv1::removeHit (TrkrDefs::hitkey) override virtual
Remove a hit using its key.
Parameters
[in] key to be removed
Reimplemented from TrkrHitSet.
Definition at line 44 of file TrkrHitSetv1.cc.
View newest version in sPHENIX GitHub at line 44 of file TrkrHitSetv1.cc
References identify(), it, and m_hits.
void TrkrHitSetv1::Reset () override virtual
Clear Event.
Reimplemented from TrkrHitSet.
Definition at line 14 of file TrkrHitSetv1.cc.
View newest version in sPHENIX GitHub at line 14 of file TrkrHitSetv1.cc
References m_hits, and m_hitSetKey.
Referenced by ~TrkrHitSetv1().
void TrkrHitSetv1::setHitSetKey (const TrkrDefs::hitsetkey) inline override virtual
Set the key for this object.
Parameters
key
Reimplemented from TrkrHitSet.
Definition at line 34 of file TrkrHitSetv1.h.
View newest version in sPHENIX GitHub at line 34 of file TrkrHitSetv1.h
References m_hitSetKey.
unsigned int TrkrHitSetv1::size (void) const inline override virtual
Get the number of hits stored.
Parameters
[out] number of hits
Reimplemented from TrkrHitSet.
Definition at line 52 of file TrkrHitSetv1.h.
View newest version in sPHENIX GitHub at line 52 of file TrkrHitSetv1.h
References m_hits.
Member Data Documentation
Map TrkrHitSetv1::m_hits private
storage for TrkrHit objects
Definition at line 62 of file TrkrHitSetv1.h.
View newest version in sPHENIX GitHub at line 62 of file TrkrHitSetv1.h
Referenced by addHitSpecificKey(), getHit(), getHits(), identify(), removeHit(), Reset(), and size().
TrkrDefs::hitsetkey TrkrHitSetv1::m_hitSetKey = TrkrDefs::HITSETKEYMAX private
unique key for this object
Definition at line 59 of file TrkrHitSetv1.h.
View newest version in sPHENIX GitHub at line 59 of file TrkrHitSetv1.h
Referenced by getHitSetKey(), identify(), Reset(), and setHitSetKey().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/trackbase/TrkrHitSetv1.h
coresoftware/blob/master/offline/packages/trackbase/TrkrHitSetv1.cc