Analysis Software: rcdaq/blob/master/rcdaq_client.cc File Reference
rcdaq_client.cc File Reference
#include <iostream>
#include <iomanip>
#include <getopt.h>
#include <sstream>
#include "parseargument.h"
#include "rcdaq_rpc.h"
#include "rcdaq_actions.h"
Functions
void rcdaq_client_Init (const char *host, const int servernumber)
void showHelp ()
int handle_device (int argc, char **argv, const int optind)
int command_execute (int argc, char **argv)
int main (int argc, char *argv[])
Variables
CLIENT * clnt
int verbose_flag = 0
Function Documentation
int command_execute (int argc, char ** argv)
Definition at line 186 of file rcdaq_client.cc.
View newest version in sPHENIX GitHub at line 186 of file rcdaq_client.cc
References Acts::PhysicalConstants::c, clnt, DAQ_BEGIN, DAQ_BEGIN_IMMEDIATE, DAQ_CLEARREADLIST, DAQ_CLOSE, DAQ_DEFINERUNTYPE, DAQ_ELOG, DAQ_END, DAQ_END_IMMEDIATE, DAQ_FAKETRIGGER, DAQ_GET_MQTT_HOST, DAQ_GET_RUNCONTROLMODE, DAQ_GETLASTEVENTNUMBER, DAQ_GETLASTFILENAME, DAQ_GETNAME, DAQ_GETRUNTYPE, DAQ_LISTREADLIST, DAQ_LISTRUNTYPES, DAQ_LOAD, DAQ_OPEN, DAQ_ROLLOVERLIMIT, DAQ_RUNNUMBERFILE, DAQ_SET_COMPRESSION, DAQ_SET_MQTT_HOST, DAQ_SET_RUNCONTROLMODE, DAQ_SET_SERVER, DAQ_SETADAPTIVEBUFFER, DAQ_SETEVENTFORMAT, DAQ_SETFILERULE, DAQ_SETMAXBUFFERSIZE, DAQ_SETMAXEVENTS, DAQ_SETMAXVOLUME, DAQ_SETNAME, DAQ_SETRUNNUMBERAPP, DAQ_SETRUNTYPE, DAQ_STATUS, DAQ_SYNC, DAQ_WEBCONTROL, material_mapping_optimisation::flush, get_value(), handle_device(), i, physmon_track_finding_ttbar::r, rcdaq_client_Init(), servernumber, showHelp(), token, and verbose_flag.
Referenced by main().
int handle_device (int argc, char ** argv, const int optind)
Definition at line 102 of file rcdaq_client.cc.
View newest version in sPHENIX GitHub at line 102 of file rcdaq_client.cc
References clnt, material_mapping_optimisation::flush, i, and physmon_track_finding_ttbar::r.
Referenced by command_execute().
int main (int argc, char * argv[])
Definition at line 913 of file rcdaq_client.cc.
View newest version in sPHENIX GitHub at line 913 of file rcdaq_client.cc
References clnt, command_execute(), and utils::status.
void rcdaq_client_Init (const char * host, const int servernumber)
Definition at line 20 of file rcdaq_client.cc.
View newest version in sPHENIX GitHub at line 20 of file rcdaq_client.cc
References clnt.
Referenced by command_execute().
void showHelp ()
Definition at line 40 of file rcdaq_client.cc.
View newest version in sPHENIX GitHub at line 40 of file rcdaq_client.cc
Referenced by command_execute().
Variable Documentation
CLIENT* clnt
Definition at line 14 of file rcdaq_client.cc.
View newest version in sPHENIX GitHub at line 14 of file rcdaq_client.cc
Referenced by command_execute(), handle_device(), main(), and rcdaq_client_Init().
int verbose_flag = 0
Definition at line 17 of file rcdaq_client.cc.
View newest version in sPHENIX GitHub at line 17 of file rcdaq_client.cc
Referenced by command_execute().