Analysis Software: macros/blob/master/calibrations/calo/emc_pi0_tbt/Fun4All_pi0tbt_SIMPLE_EMBED.C File Reference
Fun4All_pi0tbt_SIMPLE_EMBED.C File Reference
#include <GlobalVariables.C>
#include <DisplayOn.C>
#include <G4Setup_sPHENIX.C>
#include <G4_Mbd.C>
#include <G4_CaloTrigger.C>
#include <G4_Centrality.C>
#include <G4_DSTReader.C>
#include <G4_Global.C>
#include <G4_HIJetReco.C>
#include <G4_Input.C>
#include <G4_Jets.C>
#include <G4_KFParticle.C>
#include <G4_ParticleFlow.C>
#include <G4_Production.C>
#include <G4_TopoClusterReco.C>
#include <G4_Tracking.C>
#include <G4_User.C>
#include <QA.C>
#include <fun4all/Fun4AllDstOutputManager.h>
#include <fun4all/Fun4AllOutputManager.h>
#include <fun4all/Fun4AllServer.h>
#include <phool/PHRandomSeed.h>
#include <phool/recoConsts.h>
#include <calib_emc_pi0/CaloCalibEmc_Pi0.h>
Macros
#define MACRO_FUN4ALLG4SPHENIX_C
Functions
int Fun4All_pi0tbt_SIMPLE_EMBED (const int nEvents=3, const int mdc2_4_file_num=1, const string &outputFile="out_jan23.root", const int skip=0, const string &outdir=".")
Macro Definition Documentation
#define MACRO_FUN4ALLG4SPHENIX_C
Definition at line 2 of file Fun4All_pi0tbt_SIMPLE_EMBED.C.
View newest version in sPHENIX GitHub at line 2 of file Fun4All_pi0tbt_SIMPLE_EMBED.C
Function Documentation
int Fun4All_pi0tbt_SIMPLE_EMBED (const int nEvents = 3, const int mdc2_4_file_num = 1, const string & outputFile = "out_jan23.root", const int skip = 0, const string & outdir = ".")
apply sPHENIX nominal beam parameter with 2mrad crossing as defined in sPH-TRG-2020-001
forward flux return plug door. Out of acceptance and off by default.
Definition at line 40 of file Fun4All_pi0tbt_SIMPLE_EMBED.C.
View newest version in sPHENIX GitHub at line 40 of file Fun4All_pi0tbt_SIMPLE_EMBED.C
References Input::ApplysPHENIXBeamParameter(), Enable::BEAMLINE, Enable::CALOTRIGGER, CaloTrigger_Sim(), Enable::CEMC, Enable::CEMC_CELL, CEMC_Cells(), Enable::CEMC_CLUSTER, CEMC_Clusters(), Enable::CEMC_EVAL, CEMC_Eval(), Enable::CEMC_QA, Enable::CEMC_TOWER, CEMC_Towers(), Enable::CENTRALITY, Centrality(), Enable::DISPLAY, DisplayOn(), DstCompress(), Enable::DSTOUT, Enable::DSTOUT_COMPRESS, Enable::DSTREADER, Input::DZERO, Input::EMBED, Fun4AllServer::End(), Enable::EPD, INPUTEMBED::filename, G4DSTreader(), G4Init(), G4Setup(), PHG4SimpleEventGenerator::Gaus, Enable::HCALIN, Enable::HCALIN_ABSORBER, Enable::HCALIN_CELL, Enable::HCALIN_CLUSTER, Enable::HCALIN_EVAL, Enable::HCALIN_QA, Enable::HCALIN_TOWER, HCALInner_Cells(), HCALInner_Clusters(), HCALInner_Eval(), HCALInner_QA(), HCALInner_Towers(), Enable::HCALOUT, Enable::HCALOUT_ABSORBER, Enable::HCALOUT_CELL, Enable::HCALOUT_CLUSTER, Enable::HCALOUT_EVAL, Enable::HCALOUT_QA, Enable::HCALOUT_TOWER, HCALOuter_Cells(), HCALOuter_Clusters(), HCALOuter_Eval(), HCALOuter_QA(), HCALOuter_Towers(), Input::HEPMC, INPUTMANAGER::HepMCPileupInputManager, HIJetReco(), Enable::HIJETS, InputInit(), InputManagers(), InputRegister(), recoConsts::instance(), Fun4AllServer::instance(), Enable::INTT, Enable::INTT_CELL, Intt_Cells(), Enable::INTT_CLUSTER, Intt_Clustering(), Enable::INTT_QA, Intt_QA(), Jet_Eval(), Jet_QA(), Jet_Reco(), Enable::JETS, Enable::JETS_EVAL, Enable::JETS_QA, Enable::KFPARTICLE, KFParticle_D0_Reco(), KFParticle_Upsilon_Reco(), Enable::MAGNET, Enable::MAGNET_ABSORBER, Enable::MBD, Mbd_Reco(), Enable::MBDFAKE, Enable::MICROMEGAS, Enable::MICROMEGAS_CELL, Micromegas_Cells(), Enable::MICROMEGAS_CLUSTER, Micromegas_Clustering(), Enable::MICROMEGAS_QA, Micromegas_QA(), Enable::MVTX_CELL, Mvtx_Cells(), Enable::MVTX_CLUSTER, Mvtx_Clustering(), Enable::MVTX_QA, Mvtx_QA(), out, DstOut::OutputDir, DstOut::OutputFile, Enable::PARTICLEFLOW, ParticleFlow(), Input::PILEUPRATE, Acts::Test::pos, Enable::PRODUCTION, Production_CreateOutputDir(), Enable::QA, QA_G4CaloTracking(), QA_Output(), Input::READHITS, Fun4AllServer::registerOutputManager(), Fun4AllServer::registerSubsystem(), INPUTEMBED::REPEAT, Fun4AllServer::run(), CaloCalibEmc_Pi0::set_centrality_nclusters_cut(), ShowerCompress(), Input::SIMPLE, Input::SIMPLE_VERBOSITY, INPUTGENERATOR::SimpleEventGenerator, Fun4AllServer::skip(), Enable::TOPOCLUSTER, TopoClusterReco(), Enable::TPC, Enable::TPC_ABSORBER, Enable::TPC_CELL, TPC_Cells(), Enable::TPC_CLUSTER, TPC_Clustering(), Enable::TPC_QA, TPC_QA(), Enable::TRACKING_EVAL, Tracking_Eval(), Enable::TRACKING_QA, Tracking_QA(), Tracking_Reco(), Enable::TRACKING_TRACK, TrackingInit(), Input::UPSILON, Enable::USER, UserAnalysisInit(), PHRandomSeed::Verbosity(), Fun4AllBase::Verbosity(), Input::VERBOSITY, Enable::ZDC, Enable::ZDC_EVAL, and Enable::ZDC_TOWER.