Analysis Software: BDTGNode Class Reference
BDTGNode Class Reference
Public Member Functions
BDTGNode (BDTGNode *left, BDTGNode *right, int selector, double cutValue, bool cutType, int nodeType, double purity, double response)
virtual ~BDTGNode ()
virtual bool GoesRight (const std::vector< double > &inputValues) const
BDTGNode * GetRight (void)
virtual bool GoesLeft (const std::vector< double > &inputValues) const
BDTGNode * GetLeft (void)
double GetPurity (void) const
int GetNodeType (void) const
double GetResponse (void) const
Private Attributes
BDTGNode * fLeft
BDTGNode * fRight
int fSelector
double fCutValue
bool fCutType
int fNodeType
double fPurity
double fResponse
Detailed Description
Definition at line 97 of file TMVAClassification_BDTG.class.C.
View newest version in sPHENIX GitHub at line 97 of file TMVAClassification_BDTG.class.C
Constructor & Destructor Documentation
BDTGNode::BDTGNode (BDTGNode * left, BDTGNode * right, int selector, double cutValue, bool cutType, int nodeType, double purity, double response) inline
Definition at line 102 of file TMVAClassification_BDTG.class.C.
View newest version in sPHENIX GitHub at line 102 of file TMVAClassification_BDTG.class.C
BDTGNode::~BDTGNode () virtual
Definition at line 145 of file TMVAClassification_BDTG.class.C.
View newest version in sPHENIX GitHub at line 145 of file TMVAClassification_BDTG.class.C
References fLeft, and fRight.
Member Function Documentation
BDTGNode* BDTGNode::GetLeft (void) inline
Definition at line 123 of file TMVAClassification_BDTG.class.C.
View newest version in sPHENIX GitHub at line 123 of file TMVAClassification_BDTG.class.C
References fLeft.
Referenced by ReadBDTG::GetMvaValue__().
int BDTGNode::GetNodeType (void) const inline
Definition at line 129 of file TMVAClassification_BDTG.class.C.
View newest version in sPHENIX GitHub at line 129 of file TMVAClassification_BDTG.class.C
References fNodeType.
Referenced by ReadBDTG::GetMvaValue__().
double BDTGNode::GetPurity (void) const inline
Definition at line 127 of file TMVAClassification_BDTG.class.C.
View newest version in sPHENIX GitHub at line 127 of file TMVAClassification_BDTG.class.C
References fPurity.
double BDTGNode::GetResponse (void) const inline
Definition at line 130 of file TMVAClassification_BDTG.class.C.
View newest version in sPHENIX GitHub at line 130 of file TMVAClassification_BDTG.class.C
References fResponse.
Referenced by ReadBDTG::GetMvaValue__().
BDTGNode* BDTGNode::GetRight (void) inline
Definition at line 119 of file TMVAClassification_BDTG.class.C.
View newest version in sPHENIX GitHub at line 119 of file TMVAClassification_BDTG.class.C
References fRight.
Referenced by ReadBDTG::GetMvaValue__().
bool BDTGNode::GoesLeft (const std::vector< double > & inputValues) const virtual
Definition at line 162 of file TMVAClassification_BDTG.class.C.
View newest version in sPHENIX GitHub at line 162 of file TMVAClassification_BDTG.class.C
References GoesRight().
bool BDTGNode::GoesRight (const std::vector< double > & inputValues) const virtual
Definition at line 152 of file TMVAClassification_BDTG.class.C.
View newest version in sPHENIX GitHub at line 152 of file TMVAClassification_BDTG.class.C
References fCutType, fCutValue, and fSelector.
Referenced by ReadBDTG::GetMvaValue__(), and GoesLeft().
Member Data Documentation
bool BDTGNode::fCutType private
Definition at line 138 of file TMVAClassification_BDTG.class.C.
View newest version in sPHENIX GitHub at line 138 of file TMVAClassification_BDTG.class.C
Referenced by GoesRight().
double BDTGNode::fCutValue private
Definition at line 137 of file TMVAClassification_BDTG.class.C.
View newest version in sPHENIX GitHub at line 137 of file TMVAClassification_BDTG.class.C
Referenced by GoesRight().
BDTGNode* BDTGNode::fLeft private
Definition at line 134 of file TMVAClassification_BDTG.class.C.
View newest version in sPHENIX GitHub at line 134 of file TMVAClassification_BDTG.class.C
Referenced by GetLeft(), and ~BDTGNode().
int BDTGNode::fNodeType private
Definition at line 139 of file TMVAClassification_BDTG.class.C.
View newest version in sPHENIX GitHub at line 139 of file TMVAClassification_BDTG.class.C
Referenced by GetNodeType().
double BDTGNode::fPurity private
Definition at line 140 of file TMVAClassification_BDTG.class.C.
View newest version in sPHENIX GitHub at line 140 of file TMVAClassification_BDTG.class.C
Referenced by GetPurity().
double BDTGNode::fResponse private
Definition at line 141 of file TMVAClassification_BDTG.class.C.
View newest version in sPHENIX GitHub at line 141 of file TMVAClassification_BDTG.class.C
Referenced by GetResponse().
BDTGNode* BDTGNode::fRight private
Definition at line 135 of file TMVAClassification_BDTG.class.C.
View newest version in sPHENIX GitHub at line 135 of file TMVAClassification_BDTG.class.C
Referenced by GetRight(), and ~BDTGNode().
int BDTGNode::fSelector private
Definition at line 136 of file TMVAClassification_BDTG.class.C.
View newest version in sPHENIX GitHub at line 136 of file TMVAClassification_BDTG.class.C
Referenced by GoesRight().
The documentation for this class was generated from the following file:
analysis/blob/master/HF-Particle/HFTrigger/weights/woutCaloAndMinTrack/TMVAClassification_BDTG.class.C