Analysis Software: ActsExamples::Pythia8Generator Class Reference
ActsExamples::Pythia8Generator Class Reference
#include <acts/blob/sPHENIX/Examples/Algorithms/GeneratorsPythia8/ActsExamples/Generators/Pythia8ProcessGenerator.hpp>
Classes
struct Config
Public Member Functions
Pythia8Generator (const Config &cfg, Acts::Logging::Level lvl)
~Pythia8Generator ()
Pythia8Generator ()=delete
Pythia8Generator (const Pythia8Generator &)=delete
Pythia8Generator (Pythia8Generator &&)=delete
Pythia8Generator & operator= (const Pythia8Generator &)=delete
Pythia8Generator & operator= (Pythia8Generator &&other)=delete
SimParticleContainer operator() (RandomEngine &rng)
Static Public Member Functions
static std::function
< SimParticleContainer(RandomEngine &)> makeFunction (const Config &cfg, Acts::Logging::Level lvl)
Private Member Functions
const Acts::Logger & logger () const
Private access to the logging instance.
Private Attributes
Config m_cfg
std::unique_ptr< const
Acts::Logger > m_logger
std::unique_ptr<::Pythia8::Pythia > m_pythia8
std::mutex m_pythia8Mutex
Detailed Description
Definition at line 26 of file Pythia8ProcessGenerator.hpp.
View newest version in sPHENIX GitHub at line 26 of file Pythia8ProcessGenerator.hpp
Constructor & Destructor Documentation
ActsExamples::Pythia8Generator::Pythia8Generator (const Config & cfg, Acts::Logging::Level lvl)
Definition at line 35 of file Pythia8ProcessGenerator.cpp.
View newest version in sPHENIX GitHub at line 35 of file Pythia8ProcessGenerator.cpp
References ACTS_VERBOSE, ActsExamples::Pythia8Generator::Config::cmsEnergy, Acts::UnitConstants::GeV, m_cfg, m_pythia8, ActsExamples::Pythia8Generator::Config::pdgBeam0, ActsExamples::Pythia8Generator::Config::pdgBeam1, and ActsExamples::Pythia8Generator::Config::settings.
ActsExamples::Pythia8Generator::~Pythia8Generator ()
Definition at line 55 of file Pythia8ProcessGenerator.cpp.
View newest version in sPHENIX GitHub at line 55 of file Pythia8ProcessGenerator.cpp
ActsExamples::Pythia8Generator::Pythia8Generator () delete
ActsExamples::Pythia8Generator::Pythia8Generator (const Pythia8Generator &) delete
ActsExamples::Pythia8Generator::Pythia8Generator (Pythia8Generator &&) delete
Member Function Documentation
const Acts::Logger& ActsExamples::Pythia8Generator::logger () const inline private
Private access to the logging instance.
Definition at line 55 of file Pythia8ProcessGenerator.hpp.
View newest version in sPHENIX GitHub at line 55 of file Pythia8ProcessGenerator.hpp
References m_logger.
std::function< ActsExamples::SimParticleContainer(ActsExamples::RandomEngine &)> ActsExamples::Pythia8Generator::makeFunction (const Config & cfg, Acts::Logging::Level lvl) static
Definition at line 29 of file Pythia8ProcessGenerator.cpp.
View newest version in sPHENIX GitHub at line 29 of file Pythia8ProcessGenerator.cpp
References cfg.
ActsExamples::SimParticleContainer ActsExamples::Pythia8Generator::operator() (RandomEngine & rng)
Definition at line 57 of file Pythia8ProcessGenerator.cpp.
View newest version in sPHENIX GitHub at line 57 of file Pythia8ProcessGenerator.cpp
References ACTS_VERBOSE, charge, it, mass, testing::internal::move(), particle, pdg, Acts::Test::pos, Acts::Test::pos4(), ActsFatras::Particle::setAbsMomentum(), ActsFatras::Particle::setDirection(), ActsFatras::Particle::setPosition4(), and Acts::UnitConstants::u.
Pythia8Generator& ActsExamples::Pythia8Generator::operator= (const Pythia8Generator &) delete
Pythia8Generator& ActsExamples::Pythia8Generator::operator= (Pythia8Generator && other) delete
Member Data Documentation
Config ActsExamples::Pythia8Generator::m_cfg private
Definition at line 57 of file Pythia8ProcessGenerator.hpp.
View newest version in sPHENIX GitHub at line 57 of file Pythia8ProcessGenerator.hpp
Referenced by Pythia8Generator().
std::unique_ptr<const Acts::Logger> ActsExamples::Pythia8Generator::m_logger private
Definition at line 58 of file Pythia8ProcessGenerator.hpp.
View newest version in sPHENIX GitHub at line 58 of file Pythia8ProcessGenerator.hpp
Referenced by logger().
std::unique_ptr<::Pythia8::Pythia> ActsExamples::Pythia8Generator::m_pythia8 private
Definition at line 59 of file Pythia8ProcessGenerator.hpp.
View newest version in sPHENIX GitHub at line 59 of file Pythia8ProcessGenerator.hpp
Referenced by Pythia8Generator().
std::mutex ActsExamples::Pythia8Generator::m_pythia8Mutex private
Definition at line 60 of file Pythia8ProcessGenerator.hpp.
View newest version in sPHENIX GitHub at line 60 of file Pythia8ProcessGenerator.hpp
The documentation for this class was generated from the following files:
acts/blob/sPHENIX/Examples/Algorithms/GeneratorsPythia8/ActsExamples/Generators/Pythia8ProcessGenerator.hpp
acts/blob/sPHENIX/Examples/Algorithms/GeneratorsPythia8/ActsExamples/Generators/Pythia8ProcessGenerator.cpp