Analysis Software: Acts::BinnedSPGroup< external_spacepoint_t > Class Template Reference
Acts::BinnedSPGroup< external_spacepoint_t > Class Template Reference
#include <acts/blob/sPHENIX/Core/include/Acts/Seeding/BinnedSPGroup.hpp>
Public Member Functions
BinnedSPGroup ()=delete
template<typename spacepoint_iterator_t , typename callable_t >
BinnedSPGroup (spacepoint_iterator_t spBegin, spacepoint_iterator_t spEnd, callable_t &&toGlobal, std::shared_ptr< const Acts::BinFinder< external_spacepoint_t >> botBinFinder, std::shared_ptr< const Acts::BinFinder< external_spacepoint_t >> tBinFinder, std::unique_ptr< SpacePointGrid< external_spacepoint_t >> grid, Acts::Extent &rRangeSPExtent, const SeedFinderConfig< external_spacepoint_t > &_config, const SeedFinderOptions &_options)
BinnedSPGroup (const BinnedSPGroup &)=delete
BinnedSPGroup & operator= (const BinnedSPGroup &)=delete
BinnedSPGroup (BinnedSPGroup &&) noexcept=default
BinnedSPGroup & operator= (BinnedSPGroup &&) noexcept=default
~BinnedSPGroup ()=default
size_t size () const
BinnedSPGroupIterator
< external_spacepoint_t > begin ()
BinnedSPGroupIterator
< external_spacepoint_t > end ()
Acts::SpacePointGrid
< external_spacepoint_t > & grid ()
std::size_t skipZMiddleBin ()
Private Attributes
friend BinnedSPGroupIterator< external_spacepoint_t >
std::unique_ptr
< Acts::SpacePointGrid
< external_spacepoint_t > > m_grid
std::shared_ptr< const
BinFinder
< external_spacepoint_t > > m_topBinFinder
std::shared_ptr< const
BinFinder
< external_spacepoint_t > > m_bottomBinFinder
std::vector< size_t > m_bins
std::size_t m_skipZMiddleBin
Detailed Description
template<typename external_spacepoint_t>
class Acts::BinnedSPGroup< external_spacepoint_t >
BinnedSPGroup Provides access to begin and end BinnedSPGroupIterator for given BinFinders and SpacePointGrid. Fulfills the range_expression interface.
Definition at line 79 of file BinnedSPGroup.hpp.
View newest version in sPHENIX GitHub at line 79 of file BinnedSPGroup.hpp
Constructor & Destructor Documentation
template<typename external_spacepoint_t> Acts::BinnedSPGroup< external_spacepoint_t >::BinnedSPGroup () delete
template<typename external_spacepoint_t > template<typename spacepoint_iterator_t , typename callable_t > BinnedSPGroup< external_spacepoint_t >::BinnedSPGroup (spacepoint_iterator_t spBegin, spacepoint_iterator_t spEnd, callable_t && toGlobal, std::shared_ptr< const Acts::BinFinder< external_spacepoint_t >> botBinFinder, std::shared_ptr< const Acts::BinFinder< external_spacepoint_t >> tBinFinder, std::unique_ptr< SpacePointGrid< external_spacepoint_t >> grid, Acts::Extent & rRangeSPExtent, const SeedFinderConfig< external_spacepoint_t > & _config, const SeedFinderOptions & _options)
Definition at line 128 of file BinnedSPGroup.ipp.
View newest version in sPHENIX GitHub at line 128 of file BinnedSPGroup.ipp
References KFPMath::a, KFPMath::b, Acts::SeedFinderOptions::beamPos, Acts::SeedFinderConfig< SpacePoint >::binSizeR, Acts::Extent::extend(), grid(), i, Acts::SeedFinderConfig< SpacePoint >::isInInternalUnits, Acts::SeedFinderOptions::isInInternalUnits, it, testing::internal::move(), Acts::SeedFinderConfig< SpacePoint >::phiMax, Acts::Test::phiMin, Acts::SeedFinderConfig< SpacePoint >::phiMin, Acts::SeedFinderConfig< SpacePoint >::rAlign, Acts::SeedFinderConfig< SpacePoint >::rMax, Acts::SeedFinderConfig< SpacePoint >::sigmaError, Acts::SeedFinderConfig< SpacePoint >::skipZMiddleBinSearch, Acts::Experimental::detail::BlueprintHelper::sort(), value, Acts::SeedFinderConfig< SpacePoint >::zAlign, Acts::SeedFinderConfig< SpacePoint >::zBinsCustomLooping, Acts::SeedFinderConfig< SpacePoint >::zMax, and Acts::SeedFinderConfig< SpacePoint >::zMin.
template<typename external_spacepoint_t> Acts::BinnedSPGroup< external_spacepoint_t >::BinnedSPGroup (const BinnedSPGroup< external_spacepoint_t > &) delete
template<typename external_spacepoint_t> Acts::BinnedSPGroup< external_spacepoint_t >::BinnedSPGroup (BinnedSPGroup< external_spacepoint_t > &&) default noexcept
template<typename external_spacepoint_t> Acts::BinnedSPGroup< external_spacepoint_t >::~BinnedSPGroup () default
Member Function Documentation
template<typename external_spacepoint_t > Acts::BinnedSPGroupIterator< external_spacepoint_t > BinnedSPGroup< external_spacepoint_t >::begin () inline
Definition at line 250 of file BinnedSPGroup.ipp.
View newest version in sPHENIX GitHub at line 250 of file BinnedSPGroup.ipp
template<typename external_spacepoint_t > Acts::BinnedSPGroupIterator< external_spacepoint_t > BinnedSPGroup< external_spacepoint_t >::end () inline
Definition at line 256 of file BinnedSPGroup.ipp.
View newest version in sPHENIX GitHub at line 256 of file BinnedSPGroup.ipp
Referenced by main().
template<typename external_spacepoint_t> Acts::SpacePointGrid<external_spacepoint_t>& Acts::BinnedSPGroup< external_spacepoint_t >::grid () inline
Definition at line 112 of file BinnedSPGroup.hpp.
View newest version in sPHENIX GitHub at line 112 of file BinnedSPGroup.hpp
References Acts::BinnedSPGroup< external_spacepoint_t >::m_grid.
template<typename external_spacepoint_t> BinnedSPGroup& Acts::BinnedSPGroup< external_spacepoint_t >::operator= (const BinnedSPGroup< external_spacepoint_t > &) delete
template<typename external_spacepoint_t> BinnedSPGroup& Acts::BinnedSPGroup< external_spacepoint_t >::operator= (BinnedSPGroup< external_spacepoint_t > &&) default noexcept
template<typename external_spacepoint_t > size_t BinnedSPGroup< external_spacepoint_t >::size () const inline
Definition at line 244 of file BinnedSPGroup.ipp.
View newest version in sPHENIX GitHub at line 244 of file BinnedSPGroup.ipp
Referenced by main().
template<typename external_spacepoint_t> std::size_t Acts::BinnedSPGroup< external_spacepoint_t >::skipZMiddleBin () inline
Definition at line 116 of file BinnedSPGroup.hpp.
View newest version in sPHENIX GitHub at line 116 of file BinnedSPGroup.hpp
References Acts::BinnedSPGroup< external_spacepoint_t >::m_skipZMiddleBin.
Member Data Documentation
template<typename external_spacepoint_t> friend Acts::BinnedSPGroup< external_spacepoint_t >::BinnedSPGroupIterator< external_spacepoint_t > private
Definition at line 81 of file BinnedSPGroup.hpp.
View newest version in sPHENIX GitHub at line 81 of file BinnedSPGroup.hpp
template<typename external_spacepoint_t> std::vector<size_t> Acts::BinnedSPGroup< external_spacepoint_t >::m_bins private
Definition at line 130 of file BinnedSPGroup.hpp.
View newest version in sPHENIX GitHub at line 130 of file BinnedSPGroup.hpp
template<typename external_spacepoint_t> std::shared_ptr<const BinFinder<external_spacepoint_t> > Acts::BinnedSPGroup< external_spacepoint_t >::m_bottomBinFinder private
Definition at line 127 of file BinnedSPGroup.hpp.
View newest version in sPHENIX GitHub at line 127 of file BinnedSPGroup.hpp
template<typename external_spacepoint_t> std::unique_ptr<Acts::SpacePointGrid<external_spacepoint_t> > Acts::BinnedSPGroup< external_spacepoint_t >::m_grid private
Definition at line 122 of file BinnedSPGroup.hpp.
View newest version in sPHENIX GitHub at line 122 of file BinnedSPGroup.hpp
Referenced by Acts::BinnedSPGroup< external_spacepoint_t >::grid().
template<typename external_spacepoint_t> std::size_t Acts::BinnedSPGroup< external_spacepoint_t >::m_skipZMiddleBin private
Definition at line 132 of file BinnedSPGroup.hpp.
View newest version in sPHENIX GitHub at line 132 of file BinnedSPGroup.hpp
Referenced by Acts::BinnedSPGroup< external_spacepoint_t >::skipZMiddleBin().
template<typename external_spacepoint_t> std::shared_ptr<const BinFinder<external_spacepoint_t> > Acts::BinnedSPGroup< external_spacepoint_t >::m_topBinFinder private
Definition at line 126 of file BinnedSPGroup.hpp.
View newest version in sPHENIX GitHub at line 126 of file BinnedSPGroup.hpp
The documentation for this class was generated from the following files:
acts/blob/sPHENIX/Core/include/Acts/Seeding/BinnedSPGroup.hpp
acts/blob/sPHENIX/Core/include/Acts/Seeding/BinnedSPGroup.ipp