Analysis Software: JETSCAPE/blob/main/external_packages/gtl/tests/bellman_ford_test.cpp File Reference
bellman_ford_test.cpp File Reference
#include <iostream>
#include <GTL/graph.h>
#include <GTL/bellman_ford.h>
#include <GTL/edge_map.h>
Functions
int main (int argc, char *argv[])
Function Documentation
int main (int argc, char * argv[])
Definition at line 23 of file bellman_ford_test.cpp.
View newest version in sPHENIX GitHub at line 23 of file bellman_ford_test.cpp
References bellman_ford::check(), bellman_ford::distance(), end, G, algorithm::GTL_OK, it, graph::make_directed(), bellman_ford::negative_cycle(), graph::new_edge(), graph::new_node(), graph::nodes_begin(), graph::nodes_end(), bellman_ford::predecessor_node(), bellman_ford::reset(), bellman_ford::run(), graph::save(), bellman_ford::source(), bellman_ford::store_preds(), and bellman_ford::weights().