Analysis Software: HelixHoughBin_v1 Class Reference
HelixHoughBin_v1 Class Reference
#include <coresoftware/blob/master/offline/packages/trackreco/HelixHoughBin_v1.h>
Public Member Functions
HelixHoughBin_v1 (unsigned int bin)
~HelixHoughBin_v1 () override
void identify (std::ostream &os=std::cout) const override
void Reset () override
Clear Event.
int isValid () const override
isValid returns non zero if object contains vailid data
PHObject * CloneMe () const override
Virtual copy constructor.
void init () override
void add_cluster_ID (unsigned int cluster_ID) override
unsigned int get_count () const override
void clear_clusters () override
bool empty_clusters () override
size_t erase_cluster (unsigned int cluster_id) override
ConstClusterIter begin_clusters () const override
ConstClusterIter find_cluster (unsigned int cluster_id) const override
ConstClusterIter end_clusters () const override
ClusterIter begin_clusters () override
ClusterIter find_cluster (unsigned int cluster_id) override
ClusterIter end_clusters () override
unsigned int get_bin (unsigned int zoomlevel) const override
void set_bin (unsigned int zoomlevel, unsigned int bin) override
unsigned int get_zoomlevel () const override
void set_zoomlevel (unsigned int zoomlevel) override
unsigned int get_kappa_bin (unsigned int zoomlevel) const override
void set_kappa_bin (unsigned int zoomlevel, unsigned int kappa_bin) override
unsigned int get_phi_bin (unsigned int zoomlevel) const override
void set_phi_bin (unsigned int zoomlevel, unsigned int phi_bin) override
unsigned int get_phi_high_bin (unsigned int zoomlevel) const override
void set_phi_high_bin (unsigned int zoomlevel, unsigned int phi_high_bin) override
unsigned int get_phi_low_bin (unsigned int zoomlevel) const override
void set_phi_low_bin (unsigned int zoomlevel, unsigned int phi_low_bin) override
unsigned int get_d_bin (unsigned int zoomlevel) const override
void set_d_bin (unsigned int zoomlevel, unsigned int d_bin) override
unsigned int get_dzdl_bin (unsigned int zoomlevel) const override
void set_dzdl_bin (unsigned int zoomlevel, unsigned int dzdl_bin) override
unsigned int get_dzdl_high_bin (unsigned int zoomlevel) const override
void set_dzdl_high_bin (unsigned int zoomlevel, unsigned int dzdl_high_bin) override
unsigned int get_dzdl_low_bin (unsigned int zoomlevel) const override
void set_dzdl_low_bin (unsigned int zoomlevel, unsigned int dzdl_low_bin) override
unsigned int get_z0_bin (unsigned int zoomlevel) const override
void set_z0_bin (unsigned int zoomlevel, unsigned int z0_bin) override
void set_hough_space (HelixHoughSpace *hough_space) override
void set_bins (unsigned int zoomlevel, unsigned int bin) override
unsigned int get_global_bin (unsigned int zoomlevel) override
void set_global_bin (unsigned int zoomlevel) override
unsigned int get_neighbors_global_bin (unsigned int zoomlevel, unsigned int var, unsigned int bit_sign) override
float get_kappa_center (unsigned int zoomlevel) override
float get_phi_center (unsigned int zoomlevel) override
float get_d_center (unsigned int zoomlevel) override
float get_dzdl_center (unsigned int zoomlevel) override
float get_z0_center (unsigned int zoomlevel) override
Public Member Functions inherited from HelixHoughBin
~HelixHoughBin () override
virtual void set_phi_high_bin (unsigned int zoomlevel)
virtual void set_phi_low_bin (unsigned int zoomlevel)
virtual void set_dzdl_high_bin (unsigned int zoomlevel)
virtual void set_dzdl_low_bin (unsigned int zoomlevel)
Public Member Functions inherited from PHObject
PHObject ()
ctor
~PHObject () override
dtor
virtual PHObject * clone () const final
PHObject * Clone (const char *newname="") const final
void Copy (TObject &object) const final
virtual int isValid (const float) const
virtual int isValid (const double) const
virtual int isValid (const int) const
virtual int isValid (const unsigned int) const
virtual int isImplemented (const float f) const
virtual int isImplemented (const double f) const
virtual int isImplemented (const int i) const
virtual int isImplemented (const unsigned int i) const
virtual int Integrate () const
virtual int Integrate (PHObject *obj)
virtual void CopyFrom (const PHObject *obj)
Private Member Functions
ClassDefOverride (HelixHoughBin_v1, 1)
Private Attributes
ClusterSet _cluster_IDs
unsigned int _global_bin
unsigned int _bin [ZOOMLEVEL_MAX]
unsigned int _kappa_bins [ZOOMLEVEL_MAX]
unsigned int _phi_bins [ZOOMLEVEL_MAX]
unsigned int _phi_high_bins [ZOOMLEVEL_MAX]
unsigned int _phi_low_bins [ZOOMLEVEL_MAX]
unsigned int _d_bins [ZOOMLEVEL_MAX]
unsigned int _dzdl_bins [ZOOMLEVEL_MAX]
unsigned int _dzdl_high_bins [ZOOMLEVEL_MAX]
unsigned int _dzdl_low_bins [ZOOMLEVEL_MAX]
unsigned int _z0_bins [ZOOMLEVEL_MAX]
unsigned int _zoomlevel
HelixHoughSpace * _hough_space
Additional Inherited Members
Public Types inherited from HelixHoughBin
typedef std::set< unsigned int > ClusterSet
typedef std::set< unsigned int >
::const_iterator ConstClusterIter
typedef std::set< unsigned int >
::iterator ClusterIter
Protected Member Functions inherited from HelixHoughBin
HelixHoughBin ()
ClassDefOverride (HelixHoughBin, 1)
Detailed Description
Definition at line 12 of file HelixHoughBin_v1.h.
View newest version in sPHENIX GitHub at line 12 of file HelixHoughBin_v1.h
Constructor & Destructor Documentation
HelixHoughBin_v1::HelixHoughBin_v1 (unsigned int bin)
Definition at line 12 of file HelixHoughBin_v1.cc.
View newest version in sPHENIX GitHub at line 12 of file HelixHoughBin_v1.cc
References _zoomlevel, and set_bin().
Referenced by CloneMe().
HelixHoughBin_v1::~HelixHoughBin_v1 () inline override
Definition at line 16 of file HelixHoughBin_v1.h.
View newest version in sPHENIX GitHub at line 16 of file HelixHoughBin_v1.h
Member Function Documentation
void HelixHoughBin_v1::add_cluster_ID (unsigned int cluster_ID) inline override virtual
Reimplemented from HelixHoughBin.
Definition at line 27 of file HelixHoughBin_v1.h.
View newest version in sPHENIX GitHub at line 27 of file HelixHoughBin_v1.h
References _cluster_IDs.
ConstClusterIter HelixHoughBin_v1::begin_clusters () const inline override virtual
Reimplemented from HelixHoughBin.
Definition at line 33 of file HelixHoughBin_v1.h.
View newest version in sPHENIX GitHub at line 33 of file HelixHoughBin_v1.h
References _cluster_IDs.
ClusterIter HelixHoughBin_v1::begin_clusters () inline override virtual
Reimplemented from HelixHoughBin.
Definition at line 36 of file HelixHoughBin_v1.h.
View newest version in sPHENIX GitHub at line 36 of file HelixHoughBin_v1.h
References _cluster_IDs.
HelixHoughBin_v1::ClassDefOverride (HelixHoughBin_v1 , 1) private
void HelixHoughBin_v1::clear_clusters () inline override virtual
Reimplemented from HelixHoughBin.
Definition at line 29 of file HelixHoughBin_v1.h.
View newest version in sPHENIX GitHub at line 29 of file HelixHoughBin_v1.h
References _cluster_IDs.
PHObject* HelixHoughBin_v1::CloneMe () const inline override virtual
Virtual copy constructor.
Reimplemented from HelixHoughBin.
Definition at line 22 of file HelixHoughBin_v1.h.
View newest version in sPHENIX GitHub at line 22 of file HelixHoughBin_v1.h
References HelixHoughBin_v1().
bool HelixHoughBin_v1::empty_clusters () inline override virtual
Reimplemented from HelixHoughBin.
Definition at line 30 of file HelixHoughBin_v1.h.
View newest version in sPHENIX GitHub at line 30 of file HelixHoughBin_v1.h
References _cluster_IDs.
ConstClusterIter HelixHoughBin_v1::end_clusters () const inline override virtual
Reimplemented from HelixHoughBin.
Definition at line 35 of file HelixHoughBin_v1.h.
View newest version in sPHENIX GitHub at line 35 of file HelixHoughBin_v1.h
References _cluster_IDs.
ClusterIter HelixHoughBin_v1::end_clusters () inline override virtual
Reimplemented from HelixHoughBin.
Definition at line 38 of file HelixHoughBin_v1.h.
View newest version in sPHENIX GitHub at line 38 of file HelixHoughBin_v1.h
References _cluster_IDs.
size_t HelixHoughBin_v1::erase_cluster (unsigned int cluster_id) inline override virtual
Reimplemented from HelixHoughBin.
Definition at line 31 of file HelixHoughBin_v1.h.
View newest version in sPHENIX GitHub at line 31 of file HelixHoughBin_v1.h
References _cluster_IDs.
ConstClusterIter HelixHoughBin_v1::find_cluster (unsigned int cluster_id) const inline override virtual
Reimplemented from HelixHoughBin.
Definition at line 34 of file HelixHoughBin_v1.h.
View newest version in sPHENIX GitHub at line 34 of file HelixHoughBin_v1.h
References _cluster_IDs.
ClusterIter HelixHoughBin_v1::find_cluster (unsigned int cluster_id) inline override virtual
Reimplemented from HelixHoughBin.
Definition at line 37 of file HelixHoughBin_v1.h.
View newest version in sPHENIX GitHub at line 37 of file HelixHoughBin_v1.h
References _cluster_IDs.
unsigned int HelixHoughBin_v1::get_bin (unsigned int zoomlevel) const inline override virtual
Reimplemented from HelixHoughBin.
Definition at line 40 of file HelixHoughBin_v1.h.
View newest version in sPHENIX GitHub at line 40 of file HelixHoughBin_v1.h
References _bin.
unsigned int HelixHoughBin_v1::get_count () const inline override virtual
Reimplemented from HelixHoughBin.
Definition at line 28 of file HelixHoughBin_v1.h.
View newest version in sPHENIX GitHub at line 28 of file HelixHoughBin_v1.h
References _cluster_IDs.
unsigned int HelixHoughBin_v1::get_d_bin (unsigned int zoomlevel) const inline override virtual
Reimplemented from HelixHoughBin.
Definition at line 54 of file HelixHoughBin_v1.h.
View newest version in sPHENIX GitHub at line 54 of file HelixHoughBin_v1.h
References _d_bins.
Referenced by get_neighbors_global_bin(), and identify().
float HelixHoughBin_v1::get_d_center (unsigned int zoomlevel) override virtual
Reimplemented from HelixHoughBin.
Definition at line 182 of file HelixHoughBin_v1.cc.
View newest version in sPHENIX GitHub at line 182 of file HelixHoughBin_v1.cc
References _d_bins, _hough_space, HelixHoughSpace::get_d_bin_size(), HelixHoughSpace::get_d_min(), and i.
unsigned int HelixHoughBin_v1::get_dzdl_bin (unsigned int zoomlevel) const inline override virtual
Reimplemented from HelixHoughBin.
Definition at line 56 of file HelixHoughBin_v1.h.
View newest version in sPHENIX GitHub at line 56 of file HelixHoughBin_v1.h
References _dzdl_bins.
Referenced by get_neighbors_global_bin(), and identify().
float HelixHoughBin_v1::get_dzdl_center (unsigned int zoomlevel) override virtual
Reimplemented from HelixHoughBin.
Definition at line 192 of file HelixHoughBin_v1.cc.
View newest version in sPHENIX GitHub at line 192 of file HelixHoughBin_v1.cc
References _dzdl_bins, _hough_space, HelixHoughSpace::get_dzdl_bin_size(), HelixHoughSpace::get_dzdl_min(), and i.
unsigned int HelixHoughBin_v1::get_dzdl_high_bin (unsigned int zoomlevel) const inline override virtual
Reimplemented from HelixHoughBin.
Definition at line 58 of file HelixHoughBin_v1.h.
View newest version in sPHENIX GitHub at line 58 of file HelixHoughBin_v1.h
References _dzdl_high_bins.
unsigned int HelixHoughBin_v1::get_dzdl_low_bin (unsigned int zoomlevel) const inline override virtual
Reimplemented from HelixHoughBin.
Definition at line 60 of file HelixHoughBin_v1.h.
View newest version in sPHENIX GitHub at line 60 of file HelixHoughBin_v1.h
References _dzdl_low_bins.
unsigned int HelixHoughBin_v1::get_global_bin (unsigned int zoomlevel) override virtual
Reimplemented from HelixHoughBin.
Definition at line 104 of file HelixHoughBin_v1.cc.
View newest version in sPHENIX GitHub at line 104 of file HelixHoughBin_v1.cc
References _global_bin.
unsigned int HelixHoughBin_v1::get_kappa_bin (unsigned int zoomlevel) const inline override virtual
Reimplemented from HelixHoughBin.
Definition at line 46 of file HelixHoughBin_v1.h.
View newest version in sPHENIX GitHub at line 46 of file HelixHoughBin_v1.h
References _kappa_bins.
Referenced by get_neighbors_global_bin(), and identify().
float HelixHoughBin_v1::get_kappa_center (unsigned int zoomlevel) override virtual
Reimplemented from HelixHoughBin.
Definition at line 162 of file HelixHoughBin_v1.cc.
View newest version in sPHENIX GitHub at line 162 of file HelixHoughBin_v1.cc
References _hough_space, _kappa_bins, HelixHoughSpace::get_kappa_bin_size(), HelixHoughSpace::get_kappa_min(), and i.
unsigned int HelixHoughBin_v1::get_neighbors_global_bin (unsigned int zoomlevel, unsigned int var, unsigned int bit_sign) override virtual
Reimplemented from HelixHoughBin.
Definition at line 127 of file HelixHoughBin_v1.cc.
View newest version in sPHENIX GitHub at line 127 of file HelixHoughBin_v1.cc
References _bin, _hough_space, bins, HelixHoughSpace::get_bin(), get_d_bin(), get_dzdl_bin(), get_kappa_bin(), HelixHoughSpace::get_n_d_bins(), HelixHoughSpace::get_n_dzdl_bins(), HelixHoughSpace::get_n_kappa_bins(), HelixHoughSpace::get_n_phi_bins(), HelixHoughSpace::get_n_z0_bins(), get_phi_bin(), get_z0_bin(), i, nbins, and sign().
unsigned int HelixHoughBin_v1::get_phi_bin (unsigned int zoomlevel) const inline override virtual
Reimplemented from HelixHoughBin.
Definition at line 48 of file HelixHoughBin_v1.h.
View newest version in sPHENIX GitHub at line 48 of file HelixHoughBin_v1.h
References _phi_bins.
Referenced by get_neighbors_global_bin(), and identify().
float HelixHoughBin_v1::get_phi_center (unsigned int zoomlevel) override virtual
Reimplemented from HelixHoughBin.
Definition at line 172 of file HelixHoughBin_v1.cc.
View newest version in sPHENIX GitHub at line 172 of file HelixHoughBin_v1.cc
References _hough_space, _phi_bins, HelixHoughSpace::get_phi_bin_size(), HelixHoughSpace::get_phi_min(), and i.
unsigned int HelixHoughBin_v1::get_phi_high_bin (unsigned int zoomlevel) const inline override virtual
Reimplemented from HelixHoughBin.
Definition at line 50 of file HelixHoughBin_v1.h.
View newest version in sPHENIX GitHub at line 50 of file HelixHoughBin_v1.h
References _phi_high_bins.
unsigned int HelixHoughBin_v1::get_phi_low_bin (unsigned int zoomlevel) const inline override virtual
Reimplemented from HelixHoughBin.
Definition at line 52 of file HelixHoughBin_v1.h.
View newest version in sPHENIX GitHub at line 52 of file HelixHoughBin_v1.h
References _phi_low_bins.
unsigned int HelixHoughBin_v1::get_z0_bin (unsigned int zoomlevel) const inline override virtual
Reimplemented from HelixHoughBin.
Definition at line 62 of file HelixHoughBin_v1.h.
View newest version in sPHENIX GitHub at line 62 of file HelixHoughBin_v1.h
References _z0_bins.
Referenced by get_neighbors_global_bin(), and identify().
float HelixHoughBin_v1::get_z0_center (unsigned int zoomlevel) override virtual
Reimplemented from HelixHoughBin.
Definition at line 202 of file HelixHoughBin_v1.cc.
View newest version in sPHENIX GitHub at line 202 of file HelixHoughBin_v1.cc
References _hough_space, _z0_bins, HelixHoughSpace::get_z0_bin_size(), HelixHoughSpace::get_z0_min(), and i.
unsigned int HelixHoughBin_v1::get_zoomlevel () const inline override virtual
Reimplemented from HelixHoughBin.
Definition at line 43 of file HelixHoughBin_v1.h.
View newest version in sPHENIX GitHub at line 43 of file HelixHoughBin_v1.h
References _zoomlevel.
void HelixHoughBin_v1::identify (std::ostream & os = std::cout) const override virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from HelixHoughBin.
Definition at line 32 of file HelixHoughBin_v1.cc.
View newest version in sPHENIX GitHub at line 32 of file HelixHoughBin_v1.cc
References _bin, _zoomlevel, get_d_bin(), get_dzdl_bin(), get_kappa_bin(), get_phi_bin(), and get_z0_bin().
void HelixHoughBin_v1::init (void) override virtual
Reimplemented from HelixHoughBin.
Definition at line 44 of file HelixHoughBin_v1.cc.
View newest version in sPHENIX GitHub at line 44 of file HelixHoughBin_v1.cc
References _bin, _zoomlevel, and set_bins().
int HelixHoughBin_v1::isValid () const inline override virtual
isValid returns non zero if object contains vailid data
Reimplemented from HelixHoughBin.
Definition at line 21 of file HelixHoughBin_v1.h.
View newest version in sPHENIX GitHub at line 21 of file HelixHoughBin_v1.h
void HelixHoughBin_v1::Reset () inline override virtual
Clear Event.
Reimplemented from PHObject.
Definition at line 20 of file HelixHoughBin_v1.h.
View newest version in sPHENIX GitHub at line 20 of file HelixHoughBin_v1.h
void HelixHoughBin_v1::set_bin (unsigned int zoomlevel, unsigned int bin) inline override virtual
Reimplemented from HelixHoughBin.
Definition at line 41 of file HelixHoughBin_v1.h.
View newest version in sPHENIX GitHub at line 41 of file HelixHoughBin_v1.h
References _bin.
Referenced by HelixHoughBin_v1().
void HelixHoughBin_v1::set_bins (unsigned int zoomlevel, unsigned int bin) override virtual
Reimplemented from HelixHoughBin.
Definition at line 58 of file HelixHoughBin_v1.cc.
View newest version in sPHENIX GitHub at line 58 of file HelixHoughBin_v1.cc
References _hough_space, HelixHoughSpace::get_n_d_bins(), HelixHoughSpace::get_n_dzdl_bins(), HelixHoughSpace::get_n_kappa_bins(), HelixHoughSpace::get_n_phi_bins(), PHWHERE, set_d_bin(), set_dzdl_bin(), set_global_bin(), set_kappa_bin(), set_phi_bin(), set_z0_bin(), temp1, and temp2.
Referenced by init().
void HelixHoughBin_v1::set_d_bin (unsigned int zoomlevel, unsigned int d_bin) inline override virtual
Reimplemented from HelixHoughBin.
Definition at line 55 of file HelixHoughBin_v1.h.
View newest version in sPHENIX GitHub at line 55 of file HelixHoughBin_v1.h
References _d_bins.
Referenced by set_bins().
void HelixHoughBin_v1::set_dzdl_bin (unsigned int zoomlevel, unsigned int dzdl_bin) inline override virtual
Reimplemented from HelixHoughBin.
Definition at line 57 of file HelixHoughBin_v1.h.
View newest version in sPHENIX GitHub at line 57 of file HelixHoughBin_v1.h
References _dzdl_bins.
Referenced by set_bins().
void HelixHoughBin_v1::set_dzdl_high_bin (unsigned int zoomlevel, unsigned int dzdl_high_bin) inline override virtual
Reimplemented from HelixHoughBin.
Definition at line 59 of file HelixHoughBin_v1.h.
View newest version in sPHENIX GitHub at line 59 of file HelixHoughBin_v1.h
References _dzdl_high_bins.
void HelixHoughBin_v1::set_dzdl_low_bin (unsigned int zoomlevel, unsigned int dzdl_low_bin) inline override virtual
Reimplemented from HelixHoughBin.
Definition at line 61 of file HelixHoughBin_v1.h.
View newest version in sPHENIX GitHub at line 61 of file HelixHoughBin_v1.h
References _dzdl_low_bins.
void HelixHoughBin_v1::set_global_bin (unsigned int zoomlevel) override virtual
Reimplemented from HelixHoughBin.
Definition at line 109 of file HelixHoughBin_v1.cc.
View newest version in sPHENIX GitHub at line 109 of file HelixHoughBin_v1.cc
References _bin, _global_bin, _hough_space, HelixHoughSpace::get_n_d_bins(), HelixHoughSpace::get_n_dzdl_bins(), HelixHoughSpace::get_n_kappa_bins(), HelixHoughSpace::get_n_phi_bins(), and HelixHoughSpace::get_n_z0_bins().
Referenced by set_bins().
void HelixHoughBin_v1::set_hough_space (HelixHoughSpace * hough_space) override virtual
Reimplemented from HelixHoughBin.
Definition at line 51 of file HelixHoughBin_v1.cc.
View newest version in sPHENIX GitHub at line 51 of file HelixHoughBin_v1.cc
References _hough_space, assert, and HelixHoughSpace::CloneMe().
void HelixHoughBin_v1::set_kappa_bin (unsigned int zoomlevel, unsigned int kappa_bin) inline override virtual
Reimplemented from HelixHoughBin.
Definition at line 47 of file HelixHoughBin_v1.h.
View newest version in sPHENIX GitHub at line 47 of file HelixHoughBin_v1.h
References _kappa_bins.
Referenced by set_bins().
void HelixHoughBin_v1::set_phi_bin (unsigned int zoomlevel, unsigned int phi_bin) inline override virtual
Reimplemented from HelixHoughBin.
Definition at line 49 of file HelixHoughBin_v1.h.
View newest version in sPHENIX GitHub at line 49 of file HelixHoughBin_v1.h
References _phi_bins.
Referenced by set_bins().
void HelixHoughBin_v1::set_phi_high_bin (unsigned int zoomlevel, unsigned int phi_high_bin) inline override virtual
Reimplemented from HelixHoughBin.
Definition at line 51 of file HelixHoughBin_v1.h.
View newest version in sPHENIX GitHub at line 51 of file HelixHoughBin_v1.h
References _phi_high_bins.
void HelixHoughBin_v1::set_phi_low_bin (unsigned int zoomlevel, unsigned int phi_low_bin) inline override virtual
Reimplemented from HelixHoughBin.
Definition at line 53 of file HelixHoughBin_v1.h.
View newest version in sPHENIX GitHub at line 53 of file HelixHoughBin_v1.h
References _phi_low_bins.
void HelixHoughBin_v1::set_z0_bin (unsigned int zoomlevel, unsigned int z0_bin) inline override virtual
Reimplemented from HelixHoughBin.
Definition at line 63 of file HelixHoughBin_v1.h.
View newest version in sPHENIX GitHub at line 63 of file HelixHoughBin_v1.h
References _z0_bins.
Referenced by set_bins().
void HelixHoughBin_v1::set_zoomlevel (unsigned int zoomlevel) inline override virtual
Reimplemented from HelixHoughBin.
Definition at line 44 of file HelixHoughBin_v1.h.
View newest version in sPHENIX GitHub at line 44 of file HelixHoughBin_v1.h
References _zoomlevel.
Member Data Documentation
unsigned int HelixHoughBin_v1::_bin[ZOOMLEVEL_MAX] private
Definition at line 82 of file HelixHoughBin_v1.h.
View newest version in sPHENIX GitHub at line 82 of file HelixHoughBin_v1.h
Referenced by get_bin(), get_neighbors_global_bin(), identify(), init(), set_bin(), and set_global_bin().
ClusterSet HelixHoughBin_v1::_cluster_IDs private
Definition at line 79 of file HelixHoughBin_v1.h.
View newest version in sPHENIX GitHub at line 79 of file HelixHoughBin_v1.h
Referenced by add_cluster_ID(), begin_clusters(), clear_clusters(), empty_clusters(), end_clusters(), erase_cluster(), find_cluster(), and get_count().
unsigned int HelixHoughBin_v1::_d_bins[ZOOMLEVEL_MAX] private
Definition at line 87 of file HelixHoughBin_v1.h.
View newest version in sPHENIX GitHub at line 87 of file HelixHoughBin_v1.h
Referenced by get_d_bin(), get_d_center(), and set_d_bin().
unsigned int HelixHoughBin_v1::_dzdl_bins[ZOOMLEVEL_MAX] private
Definition at line 88 of file HelixHoughBin_v1.h.
View newest version in sPHENIX GitHub at line 88 of file HelixHoughBin_v1.h
Referenced by get_dzdl_bin(), get_dzdl_center(), and set_dzdl_bin().
unsigned int HelixHoughBin_v1::_dzdl_high_bins[ZOOMLEVEL_MAX] private
Definition at line 89 of file HelixHoughBin_v1.h.
View newest version in sPHENIX GitHub at line 89 of file HelixHoughBin_v1.h
Referenced by get_dzdl_high_bin(), and set_dzdl_high_bin().
unsigned int HelixHoughBin_v1::_dzdl_low_bins[ZOOMLEVEL_MAX] private
Definition at line 90 of file HelixHoughBin_v1.h.
View newest version in sPHENIX GitHub at line 90 of file HelixHoughBin_v1.h
Referenced by get_dzdl_low_bin(), and set_dzdl_low_bin().
unsigned int HelixHoughBin_v1::_global_bin private
Definition at line 81 of file HelixHoughBin_v1.h.
View newest version in sPHENIX GitHub at line 81 of file HelixHoughBin_v1.h
Referenced by get_global_bin(), and set_global_bin().
HelixHoughSpace* HelixHoughBin_v1::_hough_space private
Definition at line 94 of file HelixHoughBin_v1.h.
View newest version in sPHENIX GitHub at line 94 of file HelixHoughBin_v1.h
Referenced by get_d_center(), get_dzdl_center(), get_kappa_center(), get_neighbors_global_bin(), get_phi_center(), get_z0_center(), set_bins(), set_global_bin(), and set_hough_space().
unsigned int HelixHoughBin_v1::_kappa_bins[ZOOMLEVEL_MAX] private
Definition at line 83 of file HelixHoughBin_v1.h.
View newest version in sPHENIX GitHub at line 83 of file HelixHoughBin_v1.h
Referenced by get_kappa_bin(), get_kappa_center(), and set_kappa_bin().
unsigned int HelixHoughBin_v1::_phi_bins[ZOOMLEVEL_MAX] private
Definition at line 84 of file HelixHoughBin_v1.h.
View newest version in sPHENIX GitHub at line 84 of file HelixHoughBin_v1.h
Referenced by get_phi_bin(), get_phi_center(), and set_phi_bin().
unsigned int HelixHoughBin_v1::_phi_high_bins[ZOOMLEVEL_MAX] private
Definition at line 85 of file HelixHoughBin_v1.h.
View newest version in sPHENIX GitHub at line 85 of file HelixHoughBin_v1.h
Referenced by get_phi_high_bin(), and set_phi_high_bin().
unsigned int HelixHoughBin_v1::_phi_low_bins[ZOOMLEVEL_MAX] private
Definition at line 86 of file HelixHoughBin_v1.h.
View newest version in sPHENIX GitHub at line 86 of file HelixHoughBin_v1.h
Referenced by get_phi_low_bin(), and set_phi_low_bin().
unsigned int HelixHoughBin_v1::_z0_bins[ZOOMLEVEL_MAX] private
Definition at line 91 of file HelixHoughBin_v1.h.
View newest version in sPHENIX GitHub at line 91 of file HelixHoughBin_v1.h
Referenced by get_z0_bin(), get_z0_center(), and set_z0_bin().
unsigned int HelixHoughBin_v1::_zoomlevel private
Definition at line 92 of file HelixHoughBin_v1.h.
View newest version in sPHENIX GitHub at line 92 of file HelixHoughBin_v1.h
Referenced by get_zoomlevel(), HelixHoughBin_v1(), identify(), init(), and set_zoomlevel().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/trackreco/HelixHoughBin_v1.h
coresoftware/blob/master/offline/packages/trackreco/HelixHoughBin_v1.cc