Analysis Software: TruthJetTagging Class Reference
TruthJetTagging Class Reference
#include <analysis/blob/master/JS-Jet/TruthJetTagging/src/TruthJetTagging.h>
Public Member Functions
TruthJetTagging (const std::string &name="TruthJetTagging")
~TruthJetTagging () override
int Init (PHCompositeNode *topNode) override
int InitRun (PHCompositeNode *topNode) override
int process_event (PHCompositeNode *topNode) override
int ResetEvent (PHCompositeNode *topNode) override
Clean up internals after each event.
int EndRun (const int runnumber) override
Called at the end of each run.
int End (PHCompositeNode *topNode) override
Called at the end of all processing.
int Reset (PHCompositeNode *) override
Reset.
void Print (const std::string &what="ALL") const override
void add_algo (std::string algoname)
void add_radius (float radius)
void do_photon_tagging (bool dotag)
void do_hf_tagging (bool dotag)
void set_embedding_id (int id)
float deltaR (float eta1, float eta2, float phi1, float phi2)
float TruthPhotonTagging (PHG4TruthInfoContainer *truthnode, Jet *tjet)
int hadron_tagging (Jet *this_jet, HepMC::GenEvent *theEvent, const double match_radius)
Public Member Functions inherited from SubsysReco
~SubsysReco () override
void Print (const std::string &="ALL") const override
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Private Attributes
std::vector< std::string > _algorithms
std::vector< float > _radii
bool _do_photon_tagging
bool _do_hf_tagging
int _embedding_id
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = std::numeric_limits<int>::max() - 10
}
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Detailed Description
Definition at line 22 of file TruthJetTagging.h.
View newest version in sPHENIX GitHub at line 22 of file TruthJetTagging.h
Constructor & Destructor Documentation
TruthJetTagging::TruthJetTagging (const std::string & name = "TruthJetTagging")
Definition at line 37 of file TruthJetTagging.cc.
View newest version in sPHENIX GitHub at line 37 of file TruthJetTagging.cc
TruthJetTagging::~TruthJetTagging () override
Definition at line 49 of file TruthJetTagging.cc.
View newest version in sPHENIX GitHub at line 49 of file TruthJetTagging.cc
Member Function Documentation
void TruthJetTagging::add_algo (std::string algoname) inline
Definition at line 65 of file TruthJetTagging.h.
View newest version in sPHENIX GitHub at line 65 of file TruthJetTagging.h
References _algorithms.
Referenced by Fun4All_Condor().
void TruthJetTagging::add_radius (float radius) inline
Definition at line 70 of file TruthJetTagging.h.
View newest version in sPHENIX GitHub at line 70 of file TruthJetTagging.h
References _radii.
Referenced by Fun4All_Condor().
float TruthJetTagging::deltaR (float eta1, float eta2, float phi1, float phi2) inline
Definition at line 88 of file TruthJetTagging.h.
View newest version in sPHENIX GitHub at line 88 of file TruthJetTagging.h
References INTTVtxZ::dphi.
Referenced by hadron_tagging().
void TruthJetTagging::do_hf_tagging (bool dotag) inline
Definition at line 78 of file TruthJetTagging.h.
View newest version in sPHENIX GitHub at line 78 of file TruthJetTagging.h
References _do_hf_tagging.
Referenced by Fun4All_Condor().
void TruthJetTagging::do_photon_tagging (bool dotag) inline
Definition at line 74 of file TruthJetTagging.h.
View newest version in sPHENIX GitHub at line 74 of file TruthJetTagging.h
References _do_photon_tagging.
Referenced by Fun4All_Condor().
int TruthJetTagging::End (PHCompositeNode * topNode) override virtual
Called at the end of all processing.
Reimplemented from SubsysReco.
Definition at line 290 of file TruthJetTagging.cc.
View newest version in sPHENIX GitHub at line 290 of file TruthJetTagging.cc
References Fun4AllReturnCodes::EVENT_OK.
int TruthJetTagging::EndRun (const int runnumber) override virtual
Called at the end of each run.
Reimplemented from SubsysReco.
Definition at line 284 of file TruthJetTagging.cc.
View newest version in sPHENIX GitHub at line 284 of file TruthJetTagging.cc
References Fun4AllReturnCodes::EVENT_OK.
int TruthJetTagging::hadron_tagging (Jet * this_jet, HepMC::GenEvent * theEvent, const double match_radius)
Definition at line 167 of file TruthJetTagging.cc.
View newest version in sPHENIX GitHub at line 167 of file TruthJetTagging.cc
References deltaR(), dR(), Jet::get_eta(), Jet::get_phi(), Jet::get_pt(), merge_hashes::p, Jet::prop_JetHadronZT, and Jet::set_property().
Referenced by process_event().
int TruthJetTagging::Init (PHCompositeNode * topNode) override virtual
Called during initialization. Typically this is where you can book histograms, and e.g. register them to Fun4AllServer (so they can be output to file using Fun4AllServer::dumpHistos() method).
Reimplemented from SubsysReco.
Definition at line 55 of file TruthJetTagging.cc.
View newest version in sPHENIX GitHub at line 55 of file TruthJetTagging.cc
References Fun4AllReturnCodes::EVENT_OK.
int TruthJetTagging::InitRun (PHCompositeNode * topNode) override virtual
Called for first event when run number is known. Typically this is where you may want to fetch data from database, because you know the run number. A place to book histograms which have to know the run number.
Reimplemented from SubsysReco.
Definition at line 61 of file TruthJetTagging.cc.
View newest version in sPHENIX GitHub at line 61 of file TruthJetTagging.cc
References Fun4AllReturnCodes::EVENT_OK.
void TruthJetTagging::Print (const std::string & what = "ALL") const override virtual
Print out some info about this module.
Parameters
what can be used to specify what to print exactly.
Reimplemented from Fun4AllBase.
Definition at line 302 of file TruthJetTagging.cc.
View newest version in sPHENIX GitHub at line 302 of file TruthJetTagging.cc
int TruthJetTagging::process_event (PHCompositeNode * topNode) override virtual
Called for each event. This is where you do the real work.
Reimplemented from SubsysReco.
Definition at line 67 of file TruthJetTagging.cc.
View newest version in sPHENIX GitHub at line 67 of file TruthJetTagging.cc
References _algorithms, _do_hf_tagging, _do_photon_tagging, _embedding_id, _radii, Fun4AllReturnCodes::ABORTRUN, assert, JetMap::begin(), JetMap::end(), Fun4AllReturnCodes::EVENT_OK, PHHepMCGenEventMap::get(), PHHepMCGenEvent::getEvent(), hadron_tagging(), PHHepMCGenEventMap::identify(), PHWHERE, Jet::prop_gamma, Jet::prop_JetHadronFlavor, Jet::set_property(), and TruthPhotonTagging().
int TruthJetTagging::Reset (PHCompositeNode * topNode) override virtual
Reset.
Reimplemented from SubsysReco.
Definition at line 296 of file TruthJetTagging.cc.
View newest version in sPHENIX GitHub at line 296 of file TruthJetTagging.cc
References Fun4AllReturnCodes::EVENT_OK.
int TruthJetTagging::ResetEvent (PHCompositeNode * topNode) override virtual
Clean up internals after each event.
Reimplemented from SubsysReco.
Definition at line 278 of file TruthJetTagging.cc.
View newest version in sPHENIX GitHub at line 278 of file TruthJetTagging.cc
References Fun4AllReturnCodes::EVENT_OK.
void TruthJetTagging::set_embedding_id (int id) inline
Definition at line 82 of file TruthJetTagging.h.
View newest version in sPHENIX GitHub at line 82 of file TruthJetTagging.h
References _embedding_id, and train_ambiguity_solver::id.
Referenced by Fun4All_Condor().
float TruthJetTagging::TruthPhotonTagging (PHG4TruthInfoContainer * truthnode, Jet * tjet)
Definition at line 140 of file TruthJetTagging.cc.
View newest version in sPHENIX GitHub at line 140 of file TruthJetTagging.cc
References assert, Jet::begin_comp(), mvtx_utils::comp(), Jet::end_comp(), PHG4Particle::get_pid(), Jet::get_pt(), PHG4Particle::get_px(), PHG4Particle::get_py(), PHG4TruthInfoContainer::GetParticle(), and particle.
Referenced by process_event().
Member Data Documentation
std::vector<std::string> TruthJetTagging::_algorithms private
Definition at line 109 of file TruthJetTagging.h.
View newest version in sPHENIX GitHub at line 109 of file TruthJetTagging.h
Referenced by add_algo(), and process_event().
bool TruthJetTagging::_do_hf_tagging private
Definition at line 112 of file TruthJetTagging.h.
View newest version in sPHENIX GitHub at line 112 of file TruthJetTagging.h
Referenced by do_hf_tagging(), and process_event().
bool TruthJetTagging::_do_photon_tagging private
Definition at line 111 of file TruthJetTagging.h.
View newest version in sPHENIX GitHub at line 111 of file TruthJetTagging.h
Referenced by do_photon_tagging(), and process_event().
int TruthJetTagging::_embedding_id private
Definition at line 113 of file TruthJetTagging.h.
View newest version in sPHENIX GitHub at line 113 of file TruthJetTagging.h
Referenced by process_event(), and set_embedding_id().
std::vector<float> TruthJetTagging::_radii private
Definition at line 110 of file TruthJetTagging.h.
View newest version in sPHENIX GitHub at line 110 of file TruthJetTagging.h
Referenced by add_radius(), and process_event().
The documentation for this class was generated from the following files:
analysis/blob/master/JS-Jet/TruthJetTagging/src/TruthJetTagging.h
analysis/blob/master/JS-Jet/TruthJetTagging/src/TruthJetTagging.cc