Analysis Software: RandomConeAna Class Reference
RandomConeAna Class Reference
#include <analysis/blob/master/JS-Jet/RandomConeAna/src/RandomConeAna.h>
Public Member Functions
RandomConeAna (const std::string &outputfilename="jettree.root")
~RandomConeAna () override
void setEventSelection (double low, double high)
void addWeight (double w)
void add_input (JetInput *input)
void add_iter_input (JetInput *input)
void set_user_seed (const unsigned int seed)
int Init (PHCompositeNode *topNode) override
int process_event (PHCompositeNode *topNode) override
int End (PHCompositeNode *topNode) override
Called at the end of all processing.
Public Member Functions inherited from SubsysReco
~SubsysReco () override
virtual int EndRun (const int)
Called at the end of each run.
virtual int InitRun (PHCompositeNode *)
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
void Print (const std::string &="ALL") const override
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Private Member Functions
float LeadingR04TruthJet (PHCompositeNode *topNode)
bool EventSelect (PHCompositeNode *topNode)
void GetCentInfo (PHCompositeNode *topNode)
std::pair< float, float > get_leading_jet_eta_phi (PHCompositeNode *topNode)
std::vector< fastjet::PseudoJet > jets_to_pseudojets (std::vector< Jet * > &particles, bool randomize_etaphi)
std::vector< fastjet::PseudoJet > get_psuedojets (PHCompositeNode *topNode)
void EstimateRhos (PHCompositeNode *topNode)
float _percentile (const std::vector< float > &sorted_vec, const float percentile, const float nempty) const
void _median_stddev (const std::vector< float > &vec, float n_empty_jets, float &median, float &std_dev) const
Private Attributes
std::string m_outputfilename
bool _doEventSelection
std::pair< double, double > m_eventSelection
bool _doWeight
bool _doCentrality
bool m_user_set_seed
unsigned int m_seed
std::vector< JetInput * > _inputs
std::vector< JetInput * > _iter_inputs
TRandom3 * m_random { nullptr }
TTree * m_tree
int m_event
double weight
int m_centrality
float m_rho_area
float m_rho_area_sigma
float m_rho_mult
float m_rho_mult_sigma
float m_cone_area
int m_cone_nclustered
float m_cone_pt_raw
float m_cone_pt_iter_sub
float m_randomized_cone_pt_raw
float m_randomized_cone_pt_iter_sub
float m_avoid_leading_cone_pt_raw
float m_avoid_leading_cone_pt_iter_sub
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = std::numeric_limits<int>::max() - 10
}
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Detailed Description
Definition at line 26 of file RandomConeAna.h.
View newest version in sPHENIX GitHub at line 26 of file RandomConeAna.h
Constructor & Destructor Documentation
RandomConeAna::RandomConeAna (const std::string & outputfilename = "jettree.root")
Definition at line 57 of file RandomConeAna.cc.
View newest version in sPHENIX GitHub at line 57 of file RandomConeAna.cc
RandomConeAna::~RandomConeAna () override
Definition at line 68 of file RandomConeAna.cc.
View newest version in sPHENIX GitHub at line 68 of file RandomConeAna.cc
References _inputs, and _iter_inputs.
Member Function Documentation
void RandomConeAna::_median_stddev (const std::vector< float > & vec, float n_empty_jets, float & median, float & std_dev) const private
Definition at line 518 of file RandomConeAna.cc.
View newest version in sPHENIX GitHub at line 518 of file RandomConeAna.cc
References _percentile(), i, Acts::Experimental::detail::BlueprintHelper::sort(), and vec.
Referenced by EstimateRhos().
float RandomConeAna::_percentile (const std::vector< float > & sorted_vec, const float percentile, const float nempty) const private
Definition at line 483 of file RandomConeAna.cc.
View newest version in sPHENIX GitHub at line 483 of file RandomConeAna.cc
References assert.
Referenced by _median_stddev().
void RandomConeAna::add_input (JetInput * input) inline
Definition at line 46 of file RandomConeAna.h.
View newest version in sPHENIX GitHub at line 46 of file RandomConeAna.h
References _inputs.
Referenced by Fun4All().
void RandomConeAna::add_iter_input (JetInput * input) inline
Definition at line 48 of file RandomConeAna.h.
View newest version in sPHENIX GitHub at line 48 of file RandomConeAna.h
References _iter_inputs.
Referenced by Fun4All().
void RandomConeAna::addWeight (double w) inline
Definition at line 41 of file RandomConeAna.h.
View newest version in sPHENIX GitHub at line 41 of file RandomConeAna.h
References _doWeight, and weight.
Referenced by Fun4All().
int RandomConeAna::End (PHCompositeNode *) override virtual
Called at the end of all processing.
Reimplemented from SubsysReco.
Definition at line 316 of file RandomConeAna.cc.
View newest version in sPHENIX GitHub at line 316 of file RandomConeAna.cc
References PHTFileServer::cd(), Fun4AllReturnCodes::EVENT_OK, PHTFileServer::get(), m_outputfilename, and PHTFileServer::write().
void RandomConeAna::EstimateRhos (PHCompositeNode * topNode) private
Definition at line 419 of file RandomConeAna.cc.
View newest version in sPHENIX GitHub at line 419 of file RandomConeAna.cc
References _median_stddev(), Best, E_scheme, get_psuedojets(), kt_algorithm, m_rho_area, m_rho_area_sigma, m_rho_mult, m_rho_mult_sigma, SelectorAbsEtaMax(), SelectorNHardest(), SelectorPtMin(), and sorted_by_pt().
Referenced by process_event().
bool RandomConeAna::EventSelect (PHCompositeNode * topNode) private
Definition at line 330 of file RandomConeAna.cc.
View newest version in sPHENIX GitHub at line 330 of file RandomConeAna.cc
References _doEventSelection, LeadingR04TruthJet(), and m_eventSelection.
Referenced by process_event().
std::pair< float, float > RandomConeAna::get_leading_jet_eta_phi (PHCompositeNode * topNode) private
Definition at line 550 of file RandomConeAna.cc.
View newest version in sPHENIX GitHub at line 550 of file RandomConeAna.cc
References JetMap::begin(), JetMap::end(), Jet::get_eta(), Jet::get_phi(), and Jet::get_pt().
Referenced by process_event().
std::vector< fastjet::PseudoJet > RandomConeAna::get_psuedojets (PHCompositeNode * topNode) private
Definition at line 384 of file RandomConeAna.cc.
View newest version in sPHENIX GitHub at line 384 of file RandomConeAna.cc
References _inputs, i, and merge_hashes::p.
Referenced by EstimateRhos().
void RandomConeAna::GetCentInfo (PHCompositeNode * topNode) private
Definition at line 368 of file RandomConeAna.cc.
View newest version in sPHENIX GitHub at line 368 of file RandomConeAna.cc
References CentralityInfo::get_centile(), and m_centrality.
Referenced by process_event().
int RandomConeAna::Init (PHCompositeNode *) override virtual
Called during initialization. Typically this is where you can book histograms, and e.g. register them to Fun4AllServer (so they can be output to file using Fun4AllServer::dumpHistos() method).
Reimplemented from SubsysReco.
Definition at line 84 of file RandomConeAna.cc.
View newest version in sPHENIX GitHub at line 84 of file RandomConeAna.cc
References _doWeight, Fun4AllReturnCodes::EVENT_OK, PHTFileServer::get(), m_avoid_leading_cone_pt_iter_sub, m_avoid_leading_cone_pt_raw, m_centrality, m_cone_area, m_cone_nclustered, m_cone_pt_iter_sub, m_cone_pt_raw, m_event, m_outputfilename, m_random, m_randomized_cone_pt_iter_sub, m_randomized_cone_pt_raw, m_rho_area, m_rho_area_sigma, m_rho_mult, m_rho_mult_sigma, m_seed, m_tree, m_user_set_seed, PHTFileServer::open(), and weight.
std::vector< fastjet::PseudoJet > RandomConeAna::jets_to_pseudojets (std::vector< Jet * > & particles, bool randomize_etaphi) private
Definition at line 579 of file RandomConeAna.cc.
View newest version in sPHENIX GitHub at line 579 of file RandomConeAna.cc
References E, eta, m_random, ActsTests::PropagationDatasets::phi, PHWHERE, and graph_fancy::pT.
Referenced by process_event().
float RandomConeAna::LeadingR04TruthJet (PHCompositeNode * topNode) private
Definition at line 344 of file RandomConeAna.cc.
View newest version in sPHENIX GitHub at line 344 of file RandomConeAna.cc
References JetMap::begin(), JetMap::end(), and Jet::get_pt().
Referenced by EventSelect().
int RandomConeAna::process_event (PHCompositeNode *) override virtual
Called for each event. This is where you do the real work.
Reimplemented from SubsysReco.
Definition at line 118 of file RandomConeAna.cc.
View newest version in sPHENIX GitHub at line 118 of file RandomConeAna.cc
References _inputs, _iter_inputs, INTTVtxZ::dphi, EstimateRhos(), Fun4AllReturnCodes::EVENT_OK, EventSelect(), get_leading_jet_eta_phi(), GetCentInfo(), jets_to_pseudojets(), m_avoid_leading_cone_pt_iter_sub, m_avoid_leading_cone_pt_raw, m_cone_area, m_cone_nclustered, m_cone_pt_iter_sub, m_cone_pt_raw, m_event, m_random, m_randomized_cone_pt_iter_sub, m_randomized_cone_pt_raw, and m_tree.
void RandomConeAna::set_user_seed (const unsigned int seed) inline
Definition at line 50 of file RandomConeAna.h.
View newest version in sPHENIX GitHub at line 50 of file RandomConeAna.h
References m_seed, m_user_set_seed, and seed.
Referenced by Fun4All().
void RandomConeAna::setEventSelection (double low, double high) inline
Definition at line 35 of file RandomConeAna.h.
View newest version in sPHENIX GitHub at line 35 of file RandomConeAna.h
References _doEventSelection, and m_eventSelection.
Referenced by Fun4All().
Member Data Documentation
bool RandomConeAna::_doCentrality private
Definition at line 90 of file RandomConeAna.h.
View newest version in sPHENIX GitHub at line 90 of file RandomConeAna.h
bool RandomConeAna::_doEventSelection private
Definition at line 86 of file RandomConeAna.h.
View newest version in sPHENIX GitHub at line 86 of file RandomConeAna.h
Referenced by EventSelect(), and setEventSelection().
bool RandomConeAna::_doWeight private
Definition at line 89 of file RandomConeAna.h.
View newest version in sPHENIX GitHub at line 89 of file RandomConeAna.h
Referenced by addWeight(), and Init().
std::vector<JetInput *> RandomConeAna::_inputs private
Definition at line 95 of file RandomConeAna.h.
View newest version in sPHENIX GitHub at line 95 of file RandomConeAna.h
Referenced by add_input(), get_psuedojets(), process_event(), and ~RandomConeAna().
std::vector<JetInput *> RandomConeAna::_iter_inputs private
Definition at line 96 of file RandomConeAna.h.
View newest version in sPHENIX GitHub at line 96 of file RandomConeAna.h
Referenced by add_iter_input(), process_event(), and ~RandomConeAna().
float RandomConeAna::m_avoid_leading_cone_pt_iter_sub private
Definition at line 124 of file RandomConeAna.h.
View newest version in sPHENIX GitHub at line 124 of file RandomConeAna.h
Referenced by Init(), and process_event().
float RandomConeAna::m_avoid_leading_cone_pt_raw private
Definition at line 123 of file RandomConeAna.h.
View newest version in sPHENIX GitHub at line 123 of file RandomConeAna.h
Referenced by Init(), and process_event().
int RandomConeAna::m_centrality private
Definition at line 107 of file RandomConeAna.h.
View newest version in sPHENIX GitHub at line 107 of file RandomConeAna.h
Referenced by GetCentInfo(), and Init().
float RandomConeAna::m_cone_area private
Definition at line 114 of file RandomConeAna.h.
View newest version in sPHENIX GitHub at line 114 of file RandomConeAna.h
Referenced by Init(), and process_event().
int RandomConeAna::m_cone_nclustered private
Definition at line 115 of file RandomConeAna.h.
View newest version in sPHENIX GitHub at line 115 of file RandomConeAna.h
Referenced by Init(), and process_event().
float RandomConeAna::m_cone_pt_iter_sub private
Definition at line 118 of file RandomConeAna.h.
View newest version in sPHENIX GitHub at line 118 of file RandomConeAna.h
Referenced by Init(), and process_event().
float RandomConeAna::m_cone_pt_raw private
Definition at line 117 of file RandomConeAna.h.
View newest version in sPHENIX GitHub at line 117 of file RandomConeAna.h
Referenced by Init(), and process_event().
int RandomConeAna::m_event private
Definition at line 105 of file RandomConeAna.h.
View newest version in sPHENIX GitHub at line 105 of file RandomConeAna.h
Referenced by Init(), and process_event().
std::pair<double, double> RandomConeAna::m_eventSelection private
Definition at line 87 of file RandomConeAna.h.
View newest version in sPHENIX GitHub at line 87 of file RandomConeAna.h
Referenced by EventSelect(), and setEventSelection().
std::string RandomConeAna::m_outputfilename private
Definition at line 85 of file RandomConeAna.h.
View newest version in sPHENIX GitHub at line 85 of file RandomConeAna.h
Referenced by End(), and Init().
TRandom3* RandomConeAna::m_random { nullptr } private
Definition at line 98 of file RandomConeAna.h.
View newest version in sPHENIX GitHub at line 98 of file RandomConeAna.h
Referenced by Init(), jets_to_pseudojets(), and process_event().
float RandomConeAna::m_randomized_cone_pt_iter_sub private
Definition at line 121 of file RandomConeAna.h.
View newest version in sPHENIX GitHub at line 121 of file RandomConeAna.h
Referenced by Init(), and process_event().
float RandomConeAna::m_randomized_cone_pt_raw private
Definition at line 120 of file RandomConeAna.h.
View newest version in sPHENIX GitHub at line 120 of file RandomConeAna.h
Referenced by Init(), and process_event().
float RandomConeAna::m_rho_area private
Definition at line 109 of file RandomConeAna.h.
View newest version in sPHENIX GitHub at line 109 of file RandomConeAna.h
Referenced by EstimateRhos(), and Init().
float RandomConeAna::m_rho_area_sigma private
Definition at line 110 of file RandomConeAna.h.
View newest version in sPHENIX GitHub at line 110 of file RandomConeAna.h
Referenced by EstimateRhos(), and Init().
float RandomConeAna::m_rho_mult private
Definition at line 111 of file RandomConeAna.h.
View newest version in sPHENIX GitHub at line 111 of file RandomConeAna.h
Referenced by EstimateRhos(), and Init().
float RandomConeAna::m_rho_mult_sigma private
Definition at line 112 of file RandomConeAna.h.
View newest version in sPHENIX GitHub at line 112 of file RandomConeAna.h
Referenced by EstimateRhos(), and Init().
unsigned int RandomConeAna::m_seed private
Definition at line 93 of file RandomConeAna.h.
View newest version in sPHENIX GitHub at line 93 of file RandomConeAna.h
Referenced by Init(), and set_user_seed().
TTree* RandomConeAna::m_tree private
Definition at line 103 of file RandomConeAna.h.
View newest version in sPHENIX GitHub at line 103 of file RandomConeAna.h
Referenced by Init(), and process_event().
bool RandomConeAna::m_user_set_seed private
Definition at line 92 of file RandomConeAna.h.
View newest version in sPHENIX GitHub at line 92 of file RandomConeAna.h
Referenced by Init(), and set_user_seed().
double RandomConeAna::weight private
Definition at line 106 of file RandomConeAna.h.
View newest version in sPHENIX GitHub at line 106 of file RandomConeAna.h
Referenced by addWeight(), and Init().
The documentation for this class was generated from the following files:
analysis/blob/master/JS-Jet/RandomConeAna/src/RandomConeAna.h
analysis/blob/master/JS-Jet/RandomConeAna/src/RandomConeAna.cc