Analysis Software: InttMaskedChannelSetv1 Class Reference
InttMaskedChannelSetv1 Class Reference
#include <coresoftware/blob/master/offline/packages/intt/InttMaskedChannelSetv1.h>
Public Member Functions
InttMaskedChannelSetv1 ()=default
~InttMaskedChannelSetv1 () override
void identify (std::ostream &=std::cout) const override
std::size_t size () const override
bool IsDeadChannel (InttMap::Offline_s const &) const override
Public Member Functions inherited from InttMaskedChannelSet
InttMaskedChannelSet ()=default
~InttMaskedChannelSet () override=default
int LoadFromFile (std::string const &="InttMaskedChannelSet.root")
int LoadFromCDB (std::string const &="InttMaskedChannelSet")
bool IsDeadChannel (int const &, int const &, int const &, int const &, int const &) const
Public Member Functions inherited from PHObject
PHObject ()
ctor
~PHObject () override
dtor
virtual PHObject * CloneMe () const
Virtual copy constructor.
virtual PHObject * clone () const final
PHObject * Clone (const char *newname="") const final
void Copy (TObject &object) const final
virtual void Reset ()
Clear Event.
virtual int isValid () const
isValid returns non zero if object contains vailid data
virtual int Integrate () const
virtual int Integrate (PHObject *)
virtual void CopyFrom (const PHObject *obj)
Protected Member Functions
int v_LoadFromCDBTTree (CDBTTree &) override
Private Types
typedef std::set
< InttMap::Offline_s,
InttMap::OfflineWildcardComparator > Set_t
Private Attributes
Set_t * m_HotChannelSet {nullptr}
Detailed Description
Definition at line 13 of file InttMaskedChannelSetv1.h.
View newest version in sPHENIX GitHub at line 13 of file InttMaskedChannelSetv1.h
Member Typedef Documentation
typedef std::set<InttMap::Offline_s, InttMap::OfflineWildcardComparator> InttMaskedChannelSetv1::Set_t private
Definition at line 28 of file InttMaskedChannelSetv1.h.
View newest version in sPHENIX GitHub at line 28 of file InttMaskedChannelSetv1.h
Constructor & Destructor Documentation
InttMaskedChannelSetv1::InttMaskedChannelSetv1 () default
InttMaskedChannelSetv1::~InttMaskedChannelSetv1 () override
Definition at line 7 of file InttMaskedChannelSetv1.cc.
View newest version in sPHENIX GitHub at line 7 of file InttMaskedChannelSetv1.cc
References m_HotChannelSet.
Member Function Documentation
void InttMaskedChannelSetv1::identify (std::ostream & os = std::cout) const override virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from InttMaskedChannelSet.
Definition at line 12 of file InttMaskedChannelSetv1.cc.
View newest version in sPHENIX GitHub at line 12 of file InttMaskedChannelSetv1.cc
References size().
bool InttMaskedChannelSetv1::IsDeadChannel (InttMap::Offline_s const & ofl) const override virtual
Reimplemented from InttMaskedChannelSet.
Definition at line 53 of file InttMaskedChannelSetv1.cc.
View newest version in sPHENIX GitHub at line 53 of file InttMaskedChannelSetv1.cc
References m_HotChannelSet.
std::size_t InttMaskedChannelSetv1::size (void) const override virtual
Reimplemented from InttMaskedChannelSet.
Definition at line 20 of file InttMaskedChannelSetv1.cc.
View newest version in sPHENIX GitHub at line 20 of file InttMaskedChannelSetv1.cc
References m_HotChannelSet.
Referenced by identify().
int InttMaskedChannelSetv1::v_LoadFromCDBTTree (CDBTTree & cdbttree) override protected virtual
Reimplemented from InttMaskedChannelSet.
Definition at line 29 of file InttMaskedChannelSetv1.cc.
View newest version in sPHENIX GitHub at line 29 of file InttMaskedChannelSetv1.cc
References CDBTTree::GetIntValue(), CDBTTree::GetSingleIntValue(), m_HotChannelSet, n, and N.
Member Data Documentation
Set_t* InttMaskedChannelSetv1::m_HotChannelSet {nullptr} private
Definition at line 29 of file InttMaskedChannelSetv1.h.
View newest version in sPHENIX GitHub at line 29 of file InttMaskedChannelSetv1.h
Referenced by IsDeadChannel(), size(), v_LoadFromCDBTTree(), and ~InttMaskedChannelSetv1().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/intt/InttMaskedChannelSetv1.h
coresoftware/blob/master/offline/packages/intt/InttMaskedChannelSetv1.cc