Analysis Software: ActsExamples::HitSmearing Exception Reference
ActsExamples::HitSmearing Exception Reference final
#include <acts/blob/sPHENIX/Examples/Algorithms/Digitization/include/ActsExamples/Digitization/HitSmearing.hpp>
Classes
struct Config
Public Member Functions
HitSmearing (const Config &cfg, Acts::Logging::Level lvl)
ProcessCode execute (const AlgorithmContext &ctx) const finaloverride
Public Member Functions inherited from ActsExamples::BareAlgorithm
BareAlgorithm (std::string name, Acts::Logging::Level level=Acts::Logging::INFO)
std::string name () const finaloverride
The algorithm name.
Private Attributes
Config m_cfg
std::unordered_map
< Acts::GeometryIdentifier,
const Acts::Surface * > m_surfaces
Lookup container for hit surfaces that generate smeared hits.
Additional Inherited Members
Protected Member Functions inherited from ActsExamples::BareAlgorithm
const Acts::Logger & logger () const
Detailed Description
Create fittable measurements using truth smearing.
The truth information is smeared in the local measurement frame using Gaussian noise to generate a fittable measurement, i.e. a source link.
Definition at line 29 of file HitSmearing.hpp.
View newest version in sPHENIX GitHub at line 29 of file HitSmearing.hpp
Constructor & Destructor Documentation
ActsExamples::HitSmearing::HitSmearing (const Config & cfg, Acts::Logging::Level lvl)
Definition at line 18 of file HitSmearing.cpp.
View newest version in sPHENIX GitHub at line 18 of file HitSmearing.cpp
References ActsExamples::HitSmearing::Config::inputSimulatedHits, m_cfg, m_surfaces, ActsExamples::HitSmearing::Config::outputSourceLinks, ActsExamples::HitSmearing::Config::randomNumbers, ActsExamples::HitSmearing::Config::sigmaLoc0, ActsExamples::HitSmearing::Config::sigmaLoc1, and ActsExamples::HitSmearing::Config::trackingGeometry.
Member Function Documentation
ActsExamples::ProcessCode ActsExamples::HitSmearing::execute (const AlgorithmContext & context) const final override virtual
Execute the algorithm for one event.
This function must be implemented by subclasses.
Implements ActsExamples::BareAlgorithm.
Definition at line 46 of file HitSmearing.cpp.
View newest version in sPHENIX GitHub at line 46 of file HitSmearing.cpp
References ACTS_ERROR, ACTS_FATAL, ActsExamples::WhiteBoard::add(), Acts::Test::cov, Acts::eBoundLoc0, Acts::eBoundLoc1, ActsExamples::AlgorithmContext::eventStore, ActsExamples::AlgorithmContext::geoContext, ActsExamples::WhiteBoard::get(), Acts::Surface::globalToLocal(), ActsExamples::groupByModule(), it, loc, testing::internal::move(), next, and SUCCESS.
Member Data Documentation
Config ActsExamples::HitSmearing::m_cfg private
Definition at line 50 of file HitSmearing.hpp.
View newest version in sPHENIX GitHub at line 50 of file HitSmearing.hpp
Referenced by HitSmearing().
std::unordered_map<Acts::GeometryIdentifier, const Acts::Surface*> ActsExamples::HitSmearing::m_surfaces private
Lookup container for hit surfaces that generate smeared hits.
Definition at line 52 of file HitSmearing.hpp.
View newest version in sPHENIX GitHub at line 52 of file HitSmearing.hpp
Referenced by HitSmearing().
The documentation for this exception was generated from the following files:
acts/blob/sPHENIX/Examples/Algorithms/Digitization/include/ActsExamples/Digitization/HitSmearing.hpp
acts/blob/sPHENIX/Examples/Algorithms/Digitization/src/HitSmearing.cpp