Analysis Software: VariableArray Class Reference
VariableArray Class Reference
#include <coresoftware/blob/master/offline/packages/vararray/VariableArray.h>
Public Member Functions
VariableArray (const unsigned int idval=0)
~VariableArray () override
void identify (std::ostream &os=std::cout) const override
void set_val (const std::vector< short > &vec)
const short int * get_array () const
unsigned int get_array_size () const
int Id () const
void Reset () override
Clear Event.
Public Member Functions inherited from PHObject
PHObject ()
ctor
~PHObject () override
dtor
virtual PHObject * CloneMe () const
Virtual copy constructor.
virtual PHObject * clone () const final
PHObject * Clone (const char *newname="") const final
void Copy (TObject &object) const final
virtual int isValid () const
isValid returns non zero if object contains vailid data
virtual int Integrate () const
virtual int Integrate (PHObject *)
virtual void CopyFrom (const PHObject *obj)
Protected Attributes
int id
unsigned int nVal
short * sval
Detailed Description
Definition at line 9 of file VariableArray.h.
View newest version in sPHENIX GitHub at line 9 of file VariableArray.h
Constructor & Destructor Documentation
VariableArray::VariableArray (const unsigned int idval = 0)
Definition at line 7 of file VariableArray.cc.
View newest version in sPHENIX GitHub at line 7 of file VariableArray.cc
VariableArray::~VariableArray () override
Definition at line 15 of file VariableArray.cc.
View newest version in sPHENIX GitHub at line 15 of file VariableArray.cc
References Reset().
Member Function Documentation
const short int* VariableArray::get_array () const inline
Definition at line 19 of file VariableArray.h.
View newest version in sPHENIX GitHub at line 19 of file VariableArray.h
References sval.
Referenced by PHG4InEventReadBack::process_event(), and DumpVariableArray::process_Node().
unsigned int VariableArray::get_array_size () const inline
Definition at line 20 of file VariableArray.h.
View newest version in sPHENIX GitHub at line 20 of file VariableArray.h
References nVal.
Referenced by PHG4InEventReadBack::process_event(), and DumpVariableArray::process_Node().
int VariableArray::Id () const inline
Definition at line 21 of file VariableArray.h.
View newest version in sPHENIX GitHub at line 21 of file VariableArray.h
References id.
Referenced by DumpVariableArray::process_Node().
void VariableArray::identify (std::ostream & os = std::cout) const override virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from PHObject.
Definition at line 21 of file VariableArray.cc.
View newest version in sPHENIX GitHub at line 21 of file VariableArray.cc
References i, nVal, and sval.
void VariableArray::Reset () override virtual
Clear Event.
Reimplemented from PHObject.
Definition at line 44 of file VariableArray.cc.
View newest version in sPHENIX GitHub at line 44 of file VariableArray.cc
References nVal, and sval.
Referenced by ~VariableArray().
void VariableArray::set_val (const std::vector< short > & vec)
Definition at line 31 of file VariableArray.cc.
View newest version in sPHENIX GitHub at line 31 of file VariableArray.cc
References i, nVal, and sval.
Referenced by PHG4InEventCompress::process_event().
Member Data Documentation
int VariableArray::id protected
Definition at line 26 of file VariableArray.h.
View newest version in sPHENIX GitHub at line 26 of file VariableArray.h
Referenced by Id().
unsigned int VariableArray::nVal protected
Definition at line 27 of file VariableArray.h.
View newest version in sPHENIX GitHub at line 27 of file VariableArray.h
Referenced by get_array_size(), identify(), Reset(), and set_val().
short* VariableArray::sval protected
Definition at line 28 of file VariableArray.h.
View newest version in sPHENIX GitHub at line 28 of file VariableArray.h
Referenced by get_array(), identify(), Reset(), and set_val().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/vararray/VariableArray.h
coresoftware/blob/master/offline/packages/vararray/VariableArray.cc