Analysis Software: acts/blob/sPHENIX/Tests/UnitTests/Core/Detector/IndexedSurfaceGridFillerTests.cpp File Reference
IndexedSurfaceGridFillerTests.cpp File Reference
#include <boost/test/unit_test.hpp>
#include "Acts/Definitions/Algebra.hpp"
#include "Acts/Detector/detail/IndexedGridFiller.hpp"
#include "Acts/Detector/detail/ReferenceGenerators.hpp"
#include "Acts/Geometry/GeometryContext.hpp"
#include "Acts/Navigation/NavigationStateUpdators.hpp"
#include "Acts/Navigation/SurfaceCandidatesUpdators.hpp"
#include "Acts/Surfaces/CylinderBounds.hpp"
#include "Acts/Surfaces/CylinderSurface.hpp"
#include "Acts/Surfaces/PlaneSurface.hpp"
#include "Acts/Surfaces/RectangleBounds.hpp"
#include "Acts/Surfaces/Surface.hpp"
#include "Acts/Utilities/BinningType.hpp"
#include "Acts/Utilities/Enumerate.hpp"
#include "Acts/Utilities/Logger.hpp"
#include "Acts/Utilities/TypeTraits.hpp"
#include "Acts/Utilities/detail/Axis.hpp"
#include "Acts/Utilities/detail/AxisFwd.hpp"
#include "Acts/Utilities/detail/Grid.hpp"
#include <array>
#include <cmath>
#include <cstddef>
#include <memory>
#include <ostream>
#include <set>
#include <utility>
#include <vector>
Functions
BOOST_AUTO_TEST_CASE (BinSequence)
BOOST_AUTO_TEST_CASE (IndexGridXYOneSurfaceCenter)
BOOST_AUTO_TEST_CASE (IndexGridXYOneSurfaceBinValue)
BOOST_AUTO_TEST_CASE (IndexGridXYOneSurfacePolyhedron)
BOOST_AUTO_TEST_CASE (IndexGridXYOneSurfacePolyhedronBinExpansion)
BOOST_AUTO_TEST_CASE (IndexGridZPhiYOneSurfacePolyhedronBinExpansion)
BOOST_AUTO_TEST_CASE (IndexGridZPhiYOneSurfaceMPIPolyhedronBinExpansion)
Variables
GeometryContext tContext
Logging::Level logLevel = Logging::VERBOSE
Function Documentation
BOOST_AUTO_TEST_CASE (BinSequence)
Definition at line 66 of file IndexedSurfaceGridFillerTests.cpp.
View newest version in sPHENIX GitHub at line 66 of file IndexedSurfaceGridFillerTests.cpp
References ACTS_INFO, ACTS_LOCAL_LOGGER, Acts::Experimental::detail::binSequence(), Acts::getDefaultLogger(), telescope_simulation::logLevel, and physmon_ckf_tracking::u.
BOOST_AUTO_TEST_CASE (IndexGridXYOneSurfaceCenter)
Definition at line 117 of file IndexedSurfaceGridFillerTests.cpp.
View newest version in sPHENIX GitHub at line 117 of file IndexedSurfaceGridFillerTests.cpp
References ACTS_INFO, ACTS_LOCAL_LOGGER, Acts::binX, Acts::binY, Fatras::Test::generator, Acts::getDefaultLogger(), telescope_simulation::logLevel, testing::internal::move(), Acts::Experimental::detail::IndexedGridFiller::oLogger, pSurface, rBounds, tContext, physmon_ckf_tracking::u, and Acts::Logging::VERBOSE.
BOOST_AUTO_TEST_CASE (IndexGridXYOneSurfaceBinValue)
Definition at line 152 of file IndexedSurfaceGridFillerTests.cpp.
View newest version in sPHENIX GitHub at line 152 of file IndexedSurfaceGridFillerTests.cpp
References ACTS_INFO, ACTS_LOCAL_LOGGER, Acts::binX, Acts::binY, Fatras::Test::generator, Acts::getDefaultLogger(), telescope_simulation::logLevel, testing::internal::move(), Acts::Experimental::detail::IndexedGridFiller::oLogger, pSurface, rBounds, tContext, physmon_ckf_tracking::u, and Acts::Logging::VERBOSE.
BOOST_AUTO_TEST_CASE (IndexGridXYOneSurfacePolyhedron)
Definition at line 188 of file IndexedSurfaceGridFillerTests.cpp.
View newest version in sPHENIX GitHub at line 188 of file IndexedSurfaceGridFillerTests.cpp
References ACTS_INFO, ACTS_LOCAL_LOGGER, Acts::binX, Acts::binY, Acts::Logging::DEBUG, Fatras::Test::generator, Acts::getDefaultLogger(), telescope_simulation::logLevel, testing::internal::move(), pSurface, rBounds, tContext, and physmon_ckf_tracking::u.
BOOST_AUTO_TEST_CASE (IndexGridXYOneSurfacePolyhedronBinExpansion)
Definition at line 225 of file IndexedSurfaceGridFillerTests.cpp.
View newest version in sPHENIX GitHub at line 225 of file IndexedSurfaceGridFillerTests.cpp
References ACTS_INFO, ACTS_LOCAL_LOGGER, Acts::binX, Acts::binY, Acts::Logging::DEBUG, Fatras::Test::generator, Acts::getDefaultLogger(), telescope_simulation::logLevel, testing::internal::move(), pSurface, rBounds, tContext, and physmon_ckf_tracking::u.
BOOST_AUTO_TEST_CASE (IndexGridZPhiYOneSurfacePolyhedronBinExpansion)
Definition at line 262 of file IndexedSurfaceGridFillerTests.cpp.
View newest version in sPHENIX GitHub at line 262 of file IndexedSurfaceGridFillerTests.cpp
References ACTS_INFO, ACTS_LOCAL_LOGGER, Acts::binPhi, Acts::binZ, Acts::Test::cSurface, Acts::Logging::DEBUG, Fatras::Test::generator, Acts::getDefaultLogger(), telescope_simulation::logLevel, testing::internal::move(), tContext, and physmon_ckf_tracking::u.
BOOST_AUTO_TEST_CASE (IndexGridZPhiYOneSurfaceMPIPolyhedronBinExpansion)
Definition at line 300 of file IndexedSurfaceGridFillerTests.cpp.
View newest version in sPHENIX GitHub at line 300 of file IndexedSurfaceGridFillerTests.cpp
References ACTS_INFO, ACTS_LOCAL_LOGGER, Acts::binPhi, Acts::binZ, Acts::Test::cSurface, Acts::Logging::DEBUG, Fatras::Test::generator, Acts::getDefaultLogger(), telescope_simulation::logLevel, testing::internal::move(), tContext, and physmon_ckf_tracking::u.
Variable Documentation
Logging::Level logLevel = Logging::VERBOSE
Definition at line 45 of file IndexedSurfaceGridFillerTests.cpp.
View newest version in sPHENIX GitHub at line 45 of file IndexedSurfaceGridFillerTests.cpp
GeometryContext tContext
Definition at line 44 of file IndexedSurfaceGridFillerTests.cpp.
View newest version in sPHENIX GitHub at line 44 of file IndexedSurfaceGridFillerTests.cpp