Analysis Software: SvtxTrack Class Reference
SvtxTrack Class Reference
#include <coresoftware/blob/master/offline/packages/trackbase_historic/SvtxTrack.h>
Public Types
enum CAL_LAYER {
PRES = 0, CEMC = 1, HCALIN = 2, HCALOUT = 3,
OUTER_CEMC = 4, OUTER_HCALIN = 5, OUTER_HCALOUT = 6
}
typedef std::map< float,
SvtxTrackState * > StateMap
typedef StateMap::const_iterator ConstStateIter
typedef StateMap::iterator StateIter
typedef std::set< unsigned int > ClusterSet
typedef ClusterSet::const_iterator ConstClusterIter
typedef ClusterSet::iterator ClusterIter
typedef std::set
< TrkrDefs::cluskey > ClusterKeySet
typedef
ClusterKeySet::const_iterator ConstClusterKeyIter
typedef ClusterKeySet::iterator ClusterKeyIter
typedef std::map< int,
std::set< PHG4HitDefs::keytype > > HitIdMap
typedef HitIdMap::iterator HitIdIter
typedef HitIdMap::const_iterator HitIdConstIter
Public Member Functions
~SvtxTrack () override=default
void identify (std::ostream &os=std::cout) const override
int isValid () const override
isValid returns non zero if object contains vailid data
PHObject * CloneMe () const override
Virtual copy constructor.
virtual void CopyFrom (const SvtxTrack &)
copy content from base class
virtual void CopyFrom (SvtxTrack *)
copy content from base class
virtual unsigned int get_id () const
virtual void set_id (unsigned int)
virtual TrackSeed * get_tpc_seed () const
virtual void set_tpc_seed (TrackSeed *)
virtual TrackSeed * get_silicon_seed () const
virtual void set_silicon_seed (TrackSeed *)
virtual short int get_crossing () const
virtual void set_crossing (short int)
virtual unsigned int get_vertex_id () const
virtual void set_vertex_id (unsigned int)
virtual bool get_positive_charge () const
virtual void set_positive_charge (bool)
virtual int get_charge () const
virtual void set_charge (int)
virtual float get_chisq () const
virtual void set_chisq (float)
virtual unsigned int get_ndf () const
virtual void set_ndf (int)
virtual float get_quality () const
virtual float get_x () const
virtual void set_x (float)
virtual float get_y () const
virtual void set_y (float)
virtual float get_z () const
virtual void set_z (float)
virtual float get_pos (unsigned int) const
virtual float get_px () const
virtual void set_px (float)
virtual float get_py () const
virtual void set_py (float)
virtual float get_pz () const
virtual void set_pz (float)
virtual float get_mom (unsigned int) const
virtual float get_p () const
virtual float get_pt () const
virtual float get_eta () const
virtual float get_phi () const
virtual float get_error (int, int) const
virtual void set_error (int, int, float)
virtual bool empty_states () const
virtual size_t size_states () const
virtual size_t count_states (float) const
virtual void clear_states ()
virtual const SvtxTrackState * get_state (float) const
virtual SvtxTrackState * get_state (float)
virtual SvtxTrackState * insert_state (const SvtxTrackState *)
virtual size_t erase_state (float)
virtual ConstStateIter begin_states () const
virtual ConstStateIter find_state (float pathlength) const
virtual ConstStateIter end_states () const
virtual StateIter begin_states ()
virtual StateIter find_state (float pathlength)
virtual StateIter end_states ()
virtual void clear_cluster_keys ()
virtual bool empty_cluster_keys () const
virtual size_t size_cluster_keys () const
virtual void insert_cluster_key (TrkrDefs::cluskey)
virtual size_t erase_cluster_key (TrkrDefs::cluskey)
virtual ConstClusterKeyIter find_cluster_key (TrkrDefs::cluskey clusterid) const
virtual ConstClusterKeyIter begin_cluster_keys () const
virtual ConstClusterKeyIter end_cluster_keys () const
virtual ClusterKeyIter begin_cluster_keys ()
virtual ClusterKeyIter find_cluster_keys (unsigned int clusterid)
virtual ClusterKeyIter end_cluster_keys ()
virtual void clear_clusters ()
virtual bool empty_clusters () const
virtual size_t size_clusters () const
virtual void insert_cluster (unsigned int)
virtual size_t erase_cluster (unsigned int)
virtual ConstClusterIter begin_clusters () const
virtual ConstClusterIter find_cluster (unsigned int) const
virtual ConstClusterIter end_clusters () const
virtual ClusterIter begin_clusters ()
virtual ClusterIter find_cluster (unsigned int clusterid)
virtual ClusterIter end_clusters ()
virtual float get_cal_dphi (CAL_LAYER) const
virtual void set_cal_dphi (CAL_LAYER, float)
virtual float get_cal_deta (CAL_LAYER) const
virtual void set_cal_deta (CAL_LAYER, float)
virtual float get_cal_energy_3x3 (CAL_LAYER) const
virtual void set_cal_energy_3x3 (CAL_LAYER, float)
virtual float get_cal_energy_5x5 (CAL_LAYER) const
virtual void set_cal_energy_5x5 (CAL_LAYER, float)
virtual unsigned int get_cal_cluster_id (CAL_LAYER) const
virtual void set_cal_cluster_id (CAL_LAYER, unsigned int)
virtual TrkrDefs::cluskey get_cal_cluster_key (CAL_LAYER) const
virtual void set_cal_cluster_key (CAL_LAYER, TrkrDefs::cluskey)
virtual float get_cal_cluster_e (CAL_LAYER) const
virtual void set_cal_cluster_e (CAL_LAYER, float)
virtual float get_acts_covariance (unsigned int, unsigned int) const
virtual void set_acts_covariance (unsigned int, unsigned int, float)
virtual float get_dca () const
virtual void set_dca (float)
virtual float get_dca_error () const
virtual void set_dca_error (float)
virtual float get_dca2d () const
virtual void set_dca2d (float)
virtual float get_dca2d_error () const
virtual void set_dca2d_error (float)
virtual float get_dca3d_xy () const
virtual void set_dca3d_xy (float)
virtual float get_dca3d_xy_error () const
virtual void set_dca3d_xy_error (float)
virtual float get_dca3d_z () const
virtual void set_dca3d_z (float)
virtual float get_dca3d_z_error () const
virtual void set_dca3d_z_error (float)
virtual unsigned int get_truth_track_id () const
virtual void set_truth_track_id (unsigned int)
virtual void set_num_measurements (int)
virtual unsigned int get_num_measurements () const
virtual bool empty_g4hit_id () const
virtual size_t size_g4hit_id () const
virtual void add_g4hit_id (int, PHG4HitDefs::keytype)
virtual HitIdIter begin_g4hit_id ()
virtual HitIdConstIter begin_g4hit_id () const
virtual HitIdIter find_g4hit_id (int)
virtual HitIdConstIter find_g4hit_id (int) const
virtual HitIdIter end_g4hit_id ()
virtual HitIdConstIter end_g4hit_id () const
virtual size_t remove_g4hit_id (int, PHG4HitDefs::keytype)
virtual size_t remove_g4hit_volume (int)
virtual void clear_g4hit_id ()
virtual const HitIdMap & g4hit_ids () const
Public Member Functions inherited from PHObject
PHObject ()
ctor
~PHObject () override
dtor
virtual PHObject * clone () const final
PHObject * Clone (const char *newname="") const final
void Copy (TObject &object) const final
virtual void Reset ()
Clear Event.
virtual int Integrate () const
virtual int Integrate (PHObject *)
virtual void CopyFrom (const PHObject *obj)
Protected Member Functions
SvtxTrack ()
ClassDefOverride (SvtxTrack, 1)
Detailed Description
Definition at line 18 of file SvtxTrack.h.
View newest version in sPHENIX GitHub at line 18 of file SvtxTrack.h
Member Typedef Documentation
typedef ClusterSet::iterator SvtxTrack::ClusterIter
Definition at line 27 of file SvtxTrack.h.
View newest version in sPHENIX GitHub at line 27 of file SvtxTrack.h
typedef ClusterKeySet::iterator SvtxTrack::ClusterKeyIter
Definition at line 31 of file SvtxTrack.h.
View newest version in sPHENIX GitHub at line 31 of file SvtxTrack.h
typedef std::set<TrkrDefs::cluskey> SvtxTrack::ClusterKeySet
Definition at line 29 of file SvtxTrack.h.
View newest version in sPHENIX GitHub at line 29 of file SvtxTrack.h
typedef std::set<unsigned int> SvtxTrack::ClusterSet
Definition at line 25 of file SvtxTrack.h.
View newest version in sPHENIX GitHub at line 25 of file SvtxTrack.h
typedef ClusterSet::const_iterator SvtxTrack::ConstClusterIter
Definition at line 26 of file SvtxTrack.h.
View newest version in sPHENIX GitHub at line 26 of file SvtxTrack.h
typedef ClusterKeySet::const_iterator SvtxTrack::ConstClusterKeyIter
Definition at line 30 of file SvtxTrack.h.
View newest version in sPHENIX GitHub at line 30 of file SvtxTrack.h
typedef StateMap::const_iterator SvtxTrack::ConstStateIter
Definition at line 22 of file SvtxTrack.h.
View newest version in sPHENIX GitHub at line 22 of file SvtxTrack.h
typedef HitIdMap::const_iterator SvtxTrack::HitIdConstIter
Definition at line 228 of file SvtxTrack.h.
View newest version in sPHENIX GitHub at line 228 of file SvtxTrack.h
typedef HitIdMap::iterator SvtxTrack::HitIdIter
Definition at line 227 of file SvtxTrack.h.
View newest version in sPHENIX GitHub at line 227 of file SvtxTrack.h
typedef std::map<int, std::set<PHG4HitDefs::keytype> > SvtxTrack::HitIdMap
Definition at line 226 of file SvtxTrack.h.
View newest version in sPHENIX GitHub at line 226 of file SvtxTrack.h
typedef StateMap::iterator SvtxTrack::StateIter
Definition at line 23 of file SvtxTrack.h.
View newest version in sPHENIX GitHub at line 23 of file SvtxTrack.h
typedef std::map<float, SvtxTrackState*> SvtxTrack::StateMap
Definition at line 21 of file SvtxTrack.h.
View newest version in sPHENIX GitHub at line 21 of file SvtxTrack.h
Member Enumeration Documentation
enum SvtxTrack::CAL_LAYER
Enumerator:
PRES
CEMC
HCALIN
HCALOUT
OUTER_CEMC
OUTER_HCALIN
OUTER_HCALOUT
Definition at line 33 of file SvtxTrack.h.
View newest version in sPHENIX GitHub at line 33 of file SvtxTrack.h
Constructor & Destructor Documentation
SvtxTrack::~SvtxTrack () override default
SvtxTrack::SvtxTrack () inline protected
Definition at line 245 of file SvtxTrack.h.
View newest version in sPHENIX GitHub at line 245 of file SvtxTrack.h
Member Function Documentation
virtual void SvtxTrack::add_g4hit_id (int , PHG4HitDefs::keytype) inline virtual
Reimplemented in SvtxTrack_FastSim_v2, SvtxTrack_FastSim_v3, and SvtxTrack_FastSim_v1.
Definition at line 232 of file SvtxTrack.h.
View newest version in sPHENIX GitHub at line 232 of file SvtxTrack.h
Referenced by PHG4TrackFastSim::PseudoPatternRecognition().
SvtxTrack::ConstClusterKeyIter SvtxTrack::begin_cluster_keys () const virtual
Reimplemented in SvtxTrack_v3, SvtxTrack_v2, and SvtxTrack_v1.
Definition at line 105 of file SvtxTrack.cc.
View newest version in sPHENIX GitHub at line 105 of file SvtxTrack.cc
References DummyClusterKeySet.
Referenced by SvtxTrack_v1::CopyFrom(), SvtxTrack_v2::CopyFrom(), SvtxTrack_v3::CopyFrom(), Conversion::dist(), KFParticle_truthAndDetTools::fillDetectorBranch(), Conversion::firstLayer(), DSTEmulator::get_max_contributor(), QAG4SimulationKFParticle::getTruthTrack(), RecoConversionEval::hitCuts(), SVReco::InitEvent(), PairMaker::isElectron(), SVReco::MakeGenFitTrack(), TpcPrototypeGenFitTrkFitter::MakeTpcPrototypeTrack(), PHTrackSelector::process_event(), TPCGemGainCalb::process_event(), PHTpcClusterMover::process_event(), ElectronID::process_event(), PHRaveVertexing::process_event(), TpcPrototypeGenFitTrkFitter::process_event(), TruthConversionEval::processTrackBackground(), TpcPrototypeGenFitTrkFitter::ReFitTrack(), sPHElectronv1::sPHElectronv1(), and Conversion::trackDLayer().
SvtxTrack::ClusterKeyIter SvtxTrack::begin_cluster_keys () virtual
Reimplemented in SvtxTrack_v3, SvtxTrack_v2, and SvtxTrack_v1.
Definition at line 116 of file SvtxTrack.cc.
View newest version in sPHENIX GitHub at line 116 of file SvtxTrack.cc
References DummyClusterKeySet.
SvtxTrack::ConstClusterIter SvtxTrack::begin_clusters () const virtual
Reimplemented in SvtxTrack_v3, SvtxTrack_v2, and SvtxTrack_v1.
Definition at line 70 of file SvtxTrack.cc.
View newest version in sPHENIX GitHub at line 70 of file SvtxTrack.cc
References DummyClusterSet.
Referenced by SvtxTrack_v1::CopyFrom(), SvtxTrack_v2::CopyFrom(), SvtxTrack_v3::CopyFrom(), Conversion::dist(), EMCalCalib::eval_photon(), EMCalAna::eval_trk(), AnaSvtxTracksForGenFit::fill_tree(), psTOFTimezeroEval::fillOutputNtuples(), SvtxEvaluatorHaiwang::fillOutputNtuples(), Conversion::firstLayer(), Conversion::hasSilicon(), BDiJetModule::MakeGenFitTrack(), SvtxEvaluatorHaiwang::printOutputInfo(), psTOFTimezeroEval::printOutputInfo(), TrackingPerformanceCheck::process_event(), BDiJetModule::process_event(), and Conversion::trackDLayer().
SvtxTrack::ClusterIter SvtxTrack::begin_clusters () virtual
Reimplemented in SvtxTrack_v3, SvtxTrack_v2, and SvtxTrack_v1.
Definition at line 85 of file SvtxTrack.cc.
View newest version in sPHENIX GitHub at line 85 of file SvtxTrack.cc
References DummyClusterSet.
SvtxTrack::HitIdIter SvtxTrack::begin_g4hit_id () virtual
Reimplemented in SvtxTrack_FastSim_v2, SvtxTrack_FastSim_v3, and SvtxTrack_FastSim_v1.
Definition at line 24 of file SvtxTrack.cc.
View newest version in sPHENIX GitHub at line 24 of file SvtxTrack.cc
References DummyHitIdMap.
SvtxTrack::HitIdConstIter SvtxTrack::begin_g4hit_id () const virtual
Reimplemented in SvtxTrack_FastSim_v2, SvtxTrack_FastSim_v3, and SvtxTrack_FastSim_v1.
Definition at line 8 of file SvtxTrack.cc.
View newest version in sPHENIX GitHub at line 8 of file SvtxTrack.cc
References DummyHitIdMap.
SvtxTrack::ConstStateIter SvtxTrack::begin_states () const virtual
Reimplemented in SvtxTrack_v3, SvtxTrack_v2, SvtxTrack_v1, and SvtxTrack_v4.
Definition at line 40 of file SvtxTrack.cc.
View newest version in sPHENIX GitHub at line 40 of file SvtxTrack.cc
References DummyStateMap.
Referenced by SvtxTrack_v1::CopyFrom(), SvtxTrack_v2::CopyFrom(), SvtxTrack_v3::CopyFrom(), SvtxTrack_v4::CopyFrom(), ActsAlignmentStates::fillAlignmentStateMap(), TrackResiduals::fillClusterBranches(), TrackProjectionTools::FindClosestTrack(), sPHAnalysis::Get_CAL_e3x3(), MakeMilleFiles::getLocalVtxDerivativesXY(), FilterEventsUpsilon::GetProjectionCEMC(), FilterEvents::GetProjectionCEMC(), sPHAnalysis::GetProjectionToCalorimeter(), DISKinematicsReco::InsertCandidateFromCluster(), PHG4TrackFastSim::MakeSvtxTrack(), FilterEventsUpsilon::MatchClusterCEMC(), FilterEvents::MatchClusterCEMC(), sPHAnalysis::MatchClusterCEMC(), TpcSpaceChargeReconstruction::process_track(), and PHRaveVertexing::TranslateSvtxToGenFitTrack().
SvtxTrack::StateIter SvtxTrack::begin_states () virtual
Reimplemented in SvtxTrack_v3, SvtxTrack_v2, SvtxTrack_v1, and SvtxTrack_v4.
Definition at line 55 of file SvtxTrack.cc.
View newest version in sPHENIX GitHub at line 55 of file SvtxTrack.cc
References DummyStateMap.
SvtxTrack::ClassDefOverride (SvtxTrack , 1) protected
virtual void SvtxTrack::clear_cluster_keys () inline virtual
Reimplemented in SvtxTrack_v3, SvtxTrack_v2, and SvtxTrack_v1.
Definition at line 155 of file SvtxTrack.h.
View newest version in sPHENIX GitHub at line 155 of file SvtxTrack.h
Referenced by PHActsToSvtxTracks::createSvtxTrack().
virtual void SvtxTrack::clear_clusters () inline virtual
Reimplemented in SvtxTrack_v3, SvtxTrack_v2, and SvtxTrack_v1.
Definition at line 167 of file SvtxTrack.h.
View newest version in sPHENIX GitHub at line 167 of file SvtxTrack.h
virtual void SvtxTrack::clear_g4hit_id () inline virtual
Reimplemented in SvtxTrack_FastSim_v2, SvtxTrack_FastSim_v3, and SvtxTrack_FastSim_v1.
Definition at line 241 of file SvtxTrack.h.
View newest version in sPHENIX GitHub at line 241 of file SvtxTrack.h
virtual void SvtxTrack::clear_states () inline virtual
Reimplemented in SvtxTrack_v3, SvtxTrack_v2, SvtxTrack_v1, and SvtxTrack_v4.
Definition at line 135 of file SvtxTrack.h.
View newest version in sPHENIX GitHub at line 135 of file SvtxTrack.h
Referenced by PHActsToSvtxTracks::createSvtxTrack(), PHActsGSF::updateSvtxTrack(), and PHActsTrkFitter::updateSvtxTrack().
PHObject* SvtxTrack::CloneMe () const inline override virtual
Virtual copy constructor.
Reimplemented from PHObject.
Reimplemented in SvtxTrack_v4, SvtxTrack_FastSim, SvtxTrack_FastSim_v1, SvtxTrack_v2, SvtxTrack_v3, SvtxTrack_v1, SvtxTrack_FastSim_v2, and SvtxTrack_FastSim_v3.
Definition at line 53 of file SvtxTrack.h.
View newest version in sPHENIX GitHub at line 53 of file SvtxTrack.h
Referenced by SvtxTrackMap_v1::insert(), SvtxTrackMap_v2::insert(), and SvtxTrackMap_v2::insertWithKey().
virtual void SvtxTrack::CopyFrom (const SvtxTrack &) inline virtual
copy content from base class
Reimplemented in SvtxTrack_v4, SvtxTrack_v2, SvtxTrack_v3, SvtxTrack_v1, SvtxTrack_FastSim, SvtxTrack_FastSim_v1, SvtxTrack_FastSim_v2, and SvtxTrack_FastSim_v3.
Definition at line 59 of file SvtxTrack.h.
View newest version in sPHENIX GitHub at line 59 of file SvtxTrack.h
Referenced by SvtxTrack_v1::CopyFrom(), SvtxTrack_v2::CopyFrom(), SvtxTrack_v3::CopyFrom(), SvtxTrack_v4::CopyFrom(), and PHGenFitTrkFitter::process_event().
virtual void SvtxTrack::CopyFrom (SvtxTrack *) inline virtual
copy content from base class
Reimplemented in SvtxTrack_v4, SvtxTrack_v2, SvtxTrack_v3, SvtxTrack_v1, SvtxTrack_FastSim, SvtxTrack_FastSim_v1, SvtxTrack_FastSim_v2, and SvtxTrack_FastSim_v3.
Definition at line 63 of file SvtxTrack.h.
View newest version in sPHENIX GitHub at line 63 of file SvtxTrack.h
virtual size_t SvtxTrack::count_states (float) const inline virtual
Reimplemented in SvtxTrack_v3, SvtxTrack_v2, SvtxTrack_v1, and SvtxTrack_v4.
Definition at line 134 of file SvtxTrack.h.
View newest version in sPHENIX GitHub at line 134 of file SvtxTrack.h
virtual bool SvtxTrack::empty_cluster_keys () const inline virtual
Reimplemented in SvtxTrack_v3, SvtxTrack_v2, and SvtxTrack_v1.
Definition at line 156 of file SvtxTrack.h.
View newest version in sPHENIX GitHub at line 156 of file SvtxTrack.h
virtual bool SvtxTrack::empty_clusters () const inline virtual
Reimplemented in SvtxTrack_v3, SvtxTrack_v2, and SvtxTrack_v1.
Definition at line 168 of file SvtxTrack.h.
View newest version in sPHENIX GitHub at line 168 of file SvtxTrack.h
virtual bool SvtxTrack::empty_g4hit_id () const inline virtual
Reimplemented in SvtxTrack_FastSim_v2, SvtxTrack_FastSim_v3, and SvtxTrack_FastSim_v1.
Definition at line 230 of file SvtxTrack.h.
View newest version in sPHENIX GitHub at line 230 of file SvtxTrack.h
virtual bool SvtxTrack::empty_states () const inline virtual
Reimplemented in SvtxTrack_v3, SvtxTrack_v2, SvtxTrack_v1, and SvtxTrack_v4.
Definition at line 132 of file SvtxTrack.h.
View newest version in sPHENIX GitHub at line 132 of file SvtxTrack.h
SvtxTrack::ConstClusterKeyIter SvtxTrack::end_cluster_keys () const virtual
Reimplemented in SvtxTrack_v3, SvtxTrack_v2, and SvtxTrack_v1.
Definition at line 110 of file SvtxTrack.cc.
View newest version in sPHENIX GitHub at line 110 of file SvtxTrack.cc
References DummyClusterKeySet.
Referenced by SvtxTrack_v1::CopyFrom(), SvtxTrack_v2::CopyFrom(), SvtxTrack_v3::CopyFrom(), KFParticle_truthAndDetTools::fillDetectorBranch(), DSTEmulator::get_max_contributor(), SVReco::InitEvent(), PairMaker::isElectron(), SVReco::MakeGenFitTrack(), TpcPrototypeGenFitTrkFitter::MakeTpcPrototypeTrack(), PHTrackSelector::process_event(), TPCGemGainCalb::process_event(), PHTpcClusterMover::process_event(), ElectronID::process_event(), PHRaveVertexing::process_event(), TpcPrototypeGenFitTrkFitter::process_event(), TruthConversionEval::processTrackBackground(), TpcPrototypeGenFitTrkFitter::ReFitTrack(), and sPHElectronv1::sPHElectronv1().
SvtxTrack::ClusterKeyIter SvtxTrack::end_cluster_keys () virtual
Reimplemented in SvtxTrack_v3, SvtxTrack_v2, and SvtxTrack_v1.
Definition at line 126 of file SvtxTrack.cc.
View newest version in sPHENIX GitHub at line 126 of file SvtxTrack.cc
References DummyClusterKeySet.
SvtxTrack::ConstClusterIter SvtxTrack::end_clusters () const virtual
Reimplemented in SvtxTrack_v3, SvtxTrack_v2, and SvtxTrack_v1.
Definition at line 80 of file SvtxTrack.cc.
View newest version in sPHENIX GitHub at line 80 of file SvtxTrack.cc
References DummyClusterSet.
Referenced by SvtxTrack_v1::CopyFrom(), SvtxTrack_v2::CopyFrom(), SvtxTrack_v3::CopyFrom(), EMCalCalib::eval_photon(), EMCalAna::eval_trk(), AnaSvtxTracksForGenFit::fill_tree(), SvtxEvaluatorHaiwang::fillOutputNtuples(), psTOFTimezeroEval::fillOutputNtuples(), BDiJetModule::MakeGenFitTrack(), SvtxEvaluatorHaiwang::printOutputInfo(), psTOFTimezeroEval::printOutputInfo(), TrackingPerformanceCheck::process_event(), and BDiJetModule::process_event().
SvtxTrack::ClusterIter SvtxTrack::end_clusters () virtual
Reimplemented in SvtxTrack_v3, SvtxTrack_v2, and SvtxTrack_v1.
Definition at line 95 of file SvtxTrack.cc.
View newest version in sPHENIX GitHub at line 95 of file SvtxTrack.cc
References DummyClusterSet.
SvtxTrack::HitIdIter SvtxTrack::end_g4hit_id () virtual
Reimplemented in SvtxTrack_FastSim_v2, SvtxTrack_FastSim_v3, and SvtxTrack_FastSim_v1.
Definition at line 34 of file SvtxTrack.cc.
View newest version in sPHENIX GitHub at line 34 of file SvtxTrack.cc
References DummyHitIdMap.
SvtxTrack::HitIdConstIter SvtxTrack::end_g4hit_id () const virtual
Reimplemented in SvtxTrack_FastSim_v2, SvtxTrack_FastSim_v3, and SvtxTrack_FastSim_v1.
Definition at line 18 of file SvtxTrack.cc.
View newest version in sPHENIX GitHub at line 18 of file SvtxTrack.cc
References DummyHitIdMap.
SvtxTrack::ConstStateIter SvtxTrack::end_states () const virtual
Reimplemented in SvtxTrack_v3, SvtxTrack_v2, SvtxTrack_v1, and SvtxTrack_v4.
Definition at line 50 of file SvtxTrack.cc.
View newest version in sPHENIX GitHub at line 50 of file SvtxTrack.cc
References DummyStateMap.
Referenced by SvtxTrack_v1::CopyFrom(), SvtxTrack_v3::CopyFrom(), SvtxTrack_v2::CopyFrom(), SvtxTrack_v4::CopyFrom(), GenFitTrackProp::fill_tree(), TrackResiduals::fillClusterBranches(), TrackProjectionTools::FindClosestTrack(), sPHAnalysis::Get_CAL_e3x3(), FilterEventsUpsilon::GetProjectionCEMC(), FilterEvents::GetProjectionCEMC(), sPHAnalysis::GetProjectionToCalorimeter(), IsolatedTrackAnalysis::getTracks(), DISKinematicsReco::InsertCandidateFromCluster(), FilterEventsUpsilon::MatchClusterCEMC(), FilterEvents::MatchClusterCEMC(), sPHAnalysis::MatchClusterCEMC(), PHGenFitTrackProjection::process_event(), TpcSpaceChargeReconstruction::process_track(), TrackProjectorPid::project_track(), and PHRaveVertexing::TranslateSvtxToGenFitTrack().
SvtxTrack::StateIter SvtxTrack::end_states () virtual
Reimplemented in SvtxTrack_v3, SvtxTrack_v2, SvtxTrack_v1, and SvtxTrack_v4.
Definition at line 65 of file SvtxTrack.cc.
View newest version in sPHENIX GitHub at line 65 of file SvtxTrack.cc
References DummyStateMap.
virtual size_t SvtxTrack::erase_cluster (unsigned int) inline virtual
Reimplemented in SvtxTrack_v3, SvtxTrack_v2, and SvtxTrack_v1.
Definition at line 171 of file SvtxTrack.h.
View newest version in sPHENIX GitHub at line 171 of file SvtxTrack.h
virtual size_t SvtxTrack::erase_cluster_key (TrkrDefs::cluskey) inline virtual
Reimplemented in SvtxTrack_v3, SvtxTrack_v2, and SvtxTrack_v1.
Definition at line 160 of file SvtxTrack.h.
View newest version in sPHENIX GitHub at line 160 of file SvtxTrack.h
virtual size_t SvtxTrack::erase_state (float) inline virtual
Reimplemented in SvtxTrack_v3, SvtxTrack_v2, SvtxTrack_v1, and SvtxTrack_v4.
Definition at line 140 of file SvtxTrack.h.
View newest version in sPHENIX GitHub at line 140 of file SvtxTrack.h
SvtxTrack::ConstClusterIter SvtxTrack::find_cluster (unsigned int) const virtual
Reimplemented in SvtxTrack_v3, SvtxTrack_v2, and SvtxTrack_v1.
Definition at line 75 of file SvtxTrack.cc.
View newest version in sPHENIX GitHub at line 75 of file SvtxTrack.cc
References DummyClusterSet.
SvtxTrack::ClusterIter SvtxTrack::find_cluster (unsigned int clusterid) virtual
Reimplemented in SvtxTrack_v3, SvtxTrack_v2, and SvtxTrack_v1.
Definition at line 90 of file SvtxTrack.cc.
View newest version in sPHENIX GitHub at line 90 of file SvtxTrack.cc
References DummyClusterSet.
SvtxTrack::ConstClusterKeyIter SvtxTrack::find_cluster_key (TrkrDefs::cluskey clusterid) const virtual
Reimplemented in SvtxTrack_v3, SvtxTrack_v2, and SvtxTrack_v1.
Definition at line 100 of file SvtxTrack.cc.
View newest version in sPHENIX GitHub at line 100 of file SvtxTrack.cc
References DummyClusterKeySet.
SvtxTrack::ClusterKeyIter SvtxTrack::find_cluster_keys (unsigned int clusterid) virtual
Reimplemented in SvtxTrack_v3, SvtxTrack_v2, and SvtxTrack_v1.
Definition at line 121 of file SvtxTrack.cc.
View newest version in sPHENIX GitHub at line 121 of file SvtxTrack.cc
References DummyClusterKeySet.
SvtxTrack::HitIdIter SvtxTrack::find_g4hit_id (int) virtual
Reimplemented in SvtxTrack_FastSim_v2, SvtxTrack_FastSim_v3, and SvtxTrack_FastSim_v1.
Definition at line 29 of file SvtxTrack.cc.
View newest version in sPHENIX GitHub at line 29 of file SvtxTrack.cc
References DummyHitIdMap.
SvtxTrack::HitIdConstIter SvtxTrack::find_g4hit_id (int) const virtual
Reimplemented in SvtxTrack_FastSim_v2, SvtxTrack_FastSim_v3, and SvtxTrack_FastSim_v1.
Definition at line 13 of file SvtxTrack.cc.
View newest version in sPHENIX GitHub at line 13 of file SvtxTrack.cc
References DummyHitIdMap.
SvtxTrack::ConstStateIter SvtxTrack::find_state (float pathlength) const virtual
Reimplemented in SvtxTrack_v3, SvtxTrack_v2, SvtxTrack_v1, and SvtxTrack_v4.
Definition at line 45 of file SvtxTrack.cc.
View newest version in sPHENIX GitHub at line 45 of file SvtxTrack.cc
References DummyStateMap.
Referenced by IsolatedTrackAnalysis::getTracks(), and ActsTransformations::rotateSvtxTrackCovToActs().
SvtxTrack::StateIter SvtxTrack::find_state (float pathlength) virtual
Reimplemented in SvtxTrack_v3, SvtxTrack_v2, SvtxTrack_v1, and SvtxTrack_v4.
Definition at line 60 of file SvtxTrack.cc.
View newest version in sPHENIX GitHub at line 60 of file SvtxTrack.cc
References DummyStateMap.
const SvtxTrack::HitIdMap & SvtxTrack::g4hit_ids () const virtual
Reimplemented in SvtxTrack_FastSim_v2, SvtxTrack_FastSim_v3, and SvtxTrack_FastSim_v1.
Definition at line 131 of file SvtxTrack.cc.
View newest version in sPHENIX GitHub at line 131 of file SvtxTrack.cc
References DummyHitIdMap.
Referenced by SvtxTrack_FastSim_v2::CopyFrom(), SvtxTrack_FastSim_v3::CopyFrom(), SvtxTrack_FastSim_v1::CopyFrom(), and PHG4TrackFastSimEval::fill_track_tree().
virtual float SvtxTrack::get_acts_covariance (unsigned int , unsigned int) const inline virtual
Reimplemented in SvtxTrack_v3, and SvtxTrack_v2.
Definition at line 194 of file SvtxTrack.h.
View newest version in sPHENIX GitHub at line 194 of file SvtxTrack.h
Referenced by SvtxTrack_v2::CopyFrom(), and SvtxTrack_v3::CopyFrom().
virtual float SvtxTrack::get_cal_cluster_e (CAL_LAYER) const inline virtual
Reimplemented in SvtxTrack_v3, and SvtxTrack_v2.
Definition at line 191 of file SvtxTrack.h.
View newest version in sPHENIX GitHub at line 191 of file SvtxTrack.h
Referenced by SvtxTrack_v1::CopyFrom(), SvtxTrack_v2::CopyFrom(), SvtxTrack_v3::CopyFrom(), EMCalCalib::eval_photon(), EMCalAna::eval_trk(), KFParticle_truthAndDetTools::fillCaloBranch(), SvtxEvaluatorHaiwang::fillOutputNtuples(), psTOFTimezeroEval::fillOutputNtuples(), HFTriggerMVA::getMaxEMCalEnergy(), STACalorimeterCharacterization::process_event(), ElectronID::process_event(), PairMaker::process_event_test(), and sPHElectronv1::sPHElectronv1().
virtual unsigned int SvtxTrack::get_cal_cluster_id (CAL_LAYER) const inline virtual
Reimplemented in SvtxTrack_v3, and SvtxTrack_v2.
Definition at line 187 of file SvtxTrack.h.
View newest version in sPHENIX GitHub at line 187 of file SvtxTrack.h
Referenced by SvtxTrack_v1::CopyFrom(), SvtxTrack_v2::CopyFrom(), SvtxTrack_v3::CopyFrom(), Conversion::get_cluster_id(), Conversion::get_cluster_ids(), RecoConversionEval::process_event(), ElectronID::process_event(), PairMaker::process_event_test(), TruthConversionEval::processTrackBackground(), and PHFlowJetMaker::run_particle_flow().
virtual TrkrDefs::cluskey SvtxTrack::get_cal_cluster_key (CAL_LAYER) const inline virtual
Reimplemented in SvtxTrack_v3, and SvtxTrack_v2.
Definition at line 189 of file SvtxTrack.h.
View newest version in sPHENIX GitHub at line 189 of file SvtxTrack.h
Referenced by SvtxTrack_v1::CopyFrom(), SvtxTrack_v3::CopyFrom(), SvtxTrack_v2::CopyFrom(), and PairMaker::process_event_test().
virtual float SvtxTrack::get_cal_deta (CAL_LAYER) const inline virtual
Reimplemented in SvtxTrack_v3, and SvtxTrack_v2.
Definition at line 181 of file SvtxTrack.h.
View newest version in sPHENIX GitHub at line 181 of file SvtxTrack.h
Referenced by SvtxTrack_v1::CopyFrom(), SvtxTrack_v2::CopyFrom(), SvtxTrack_v3::CopyFrom(), EMCalCalib::eval_photon(), EMCalAna::eval_trk(), KFParticle_truthAndDetTools::fillCaloBranch(), psTOFTimezeroEval::fillOutputNtuples(), SvtxEvaluatorHaiwang::fillOutputNtuples(), STACalorimeterCharacterization::process_event(), SimpleTrackingAnalysis::process_event(), and sPHElectronv1::sPHElectronv1().
virtual float SvtxTrack::get_cal_dphi (CAL_LAYER) const inline virtual
Reimplemented in SvtxTrack_v3, and SvtxTrack_v2.
Definition at line 179 of file SvtxTrack.h.
View newest version in sPHENIX GitHub at line 179 of file SvtxTrack.h
Referenced by SvtxTrack_v1::CopyFrom(), SvtxTrack_v2::CopyFrom(), SvtxTrack_v3::CopyFrom(), EMCalCalib::eval_photon(), EMCalAna::eval_trk(), KFParticle_truthAndDetTools::fillCaloBranch(), psTOFTimezeroEval::fillOutputNtuples(), SvtxEvaluatorHaiwang::fillOutputNtuples(), STACalorimeterCharacterization::process_event(), SimpleTrackingAnalysis::process_event(), and sPHElectronv1::sPHElectronv1().
virtual float SvtxTrack::get_cal_energy_3x3 (CAL_LAYER) const inline virtual
Reimplemented in SvtxTrack_v3, and SvtxTrack_v2.
Definition at line 183 of file SvtxTrack.h.
View newest version in sPHENIX GitHub at line 183 of file SvtxTrack.h
Referenced by SvtxTrack_v1::CopyFrom(), SvtxTrack_v2::CopyFrom(), SvtxTrack_v3::CopyFrom(), EMCalCalib::eval_photon(), EMCalAna::eval_trk(), KFParticle_truthAndDetTools::fillCaloBranch(), psTOFTimezeroEval::fillOutputNtuples(), SvtxEvaluatorHaiwang::fillOutputNtuples(), DISKinematicsReco::InsertCandidateFromCluster(), PairMaker::isElectron(), sPHAnalysis::isElectron(), SimpleTrackingAnalysis::process_event(), STACalorimeterCharacterization::process_event(), ElectronID::process_event(), QAG4SimulationCalorimeterSum::process_event_TrackProj(), and sPHElectronv1::sPHElectronv1().
virtual float SvtxTrack::get_cal_energy_5x5 (CAL_LAYER) const inline virtual
Reimplemented in SvtxTrack_v3, and SvtxTrack_v2.
Definition at line 185 of file SvtxTrack.h.
View newest version in sPHENIX GitHub at line 185 of file SvtxTrack.h
Referenced by SvtxTrack_v1::CopyFrom(), SvtxTrack_v2::CopyFrom(), SvtxTrack_v3::CopyFrom(), KFParticle_truthAndDetTools::fillCaloBranch(), QAG4SimulationCalorimeterSum::process_event_TrackProj(), and sPHElectronv1::sPHElectronv1().
virtual int SvtxTrack::get_charge () const inline virtual
Reimplemented in SvtxTrack_v4, SvtxTrack_v3, SvtxTrack_v2, and SvtxTrack_v1.
Definition at line 88 of file SvtxTrack.h.
View newest version in sPHENIX GitHub at line 88 of file SvtxTrack.h
Referenced by ExclusiveReco::AddInvariantMassInformation(), LeptoquarksReco::AddTrackInformation(), EMCalCalib::eval_photon(), EMCalAna::eval_trk(), AnaSvtxTracksForGenFit::fill_tree(), GenFitTrackProp::fill_tree(), KshortReconstruction::fillNtp(), SecondaryVertexFinder::fillNtp(), psTOFTimezeroEval::fillOutputNtuples(), SvtxEvaluatorHaiwang::fillOutputNtuples(), TrkrNtuplizer::fillOutputNtuples(), SvtxEvaluator::fillOutputNtuples(), FilterEvents::get_dca(), SecondaryVertexFinder::getCircleXYTrack(), FullJetFinder::GetDistanceFromVertexXY(), MakeMilleFiles::getLocalVtxDerivativesXY(), PhotonJet::GetRecoHadronsAndJets(), AnaTutorial::getTracks(), IsolatedTrackAnalysis::getTracks(), DISKinematicsReco::InsertCandidateFromCluster(), KFParticle_Tools::makeParticle(), PHActsGSF::makeSeed(), PHActsVertexFitter::makeTrackParam(), ActsPropagator::makeTrackParams(), PHTpcResiduals::makeTrackParams(), TrackResiduals::process_event(), PHGenFitTrackProjection::process_event(), RecoConversionEval::process_event(), MakeMilleFiles::process_event(), PhotonJet::process_event(), ElectronID::process_event(), PairMaker::process_event_test(), sPHAnalysis::process_event_test(), sPHAnalysis::process_event_upsilons(), TPCHitTrackDisplay::SimulationOut(), sPHElectronv1::sPHElectronv1(), and PHRaveVertexing::TranslateSvtxToGenFitTrack().
virtual float SvtxTrack::get_chisq () const inline virtual
Reimplemented in SvtxTrack_v4, SvtxTrack_v3, SvtxTrack_v2, and SvtxTrack_v1.
Definition at line 91 of file SvtxTrack.h.
View newest version in sPHENIX GitHub at line 91 of file SvtxTrack.h
Referenced by SvtxTrack_v1::CopyFrom(), SvtxTrack_v2::CopyFrom(), SvtxTrack_v3::CopyFrom(), SvtxTrack_v4::CopyFrom(), EMCalCalib::eval_photon(), EMCalAna::eval_trk(), psTOFTimezeroEval::fillOutputNtuples(), SvtxEvaluatorHaiwang::fillOutputNtuples(), TrkrNtuplizer::fillOutputNtuples(), SvtxEvaluator::fillOutputNtuples(), HFTrackEfficiency::findTracks(), FilterEvents::get_dca(), FullJetFinder::GetDistanceFromVertexXY(), PhotonJet::GetRecoHadronsAndJets(), AnaTutorial::getTracks(), IsolatedTrackAnalysis::getTracks(), SVReco::InitEvent(), PairMaker::isElectron(), KFParticle_Tools::makeParticle(), TpcPrototypeGenFitTrkFitter::MakeTpcPrototypeTrack(), TrackingPerformanceCheck::process_event(), FilterEvents::process_event(), BJetModule::process_event(), PHTrackSelector::process_event(), PHTrackCleaner::process_event(), TPCGemGainCalb::process_event(), TrackResiduals::process_event(), PhotonJet::process_event(), BDiJetModule::process_event(), FullJetFinder::process_event(), sPHAnalysis::process_event_test(), sPHAnalysis::process_event_upsilons(), sPHElectronv1::sPHElectronv1(), and PHRaveVertexing::TranslateSvtxToGenFitTrack().
virtual short int SvtxTrack::get_crossing () const inline virtual
Reimplemented in SvtxTrack_v4, and SvtxTrack_v3.
Definition at line 79 of file SvtxTrack.h.
View newest version in sPHENIX GitHub at line 79 of file SvtxTrack.h
Referenced by SvtxTrack_v3::CopyFrom(), SvtxTrack_v4::CopyFrom(), TrkrNtuplizer::fillOutputNtuples(), SvtxEvaluator::fillOutputNtuples(), PHTrackCleaner::process_event(), TrackResiduals::process_event(), TpcSpaceChargeReconstruction::process_track(), PHTpcResiduals::processTrack(), and PHGenFitTrkFitter::ReFitTrack().
virtual float SvtxTrack::get_dca () const inline virtual
Reimplemented in SvtxTrack_v3, SvtxTrack_v2, and SvtxTrack_v1.
Definition at line 197 of file SvtxTrack.h.
View newest version in sPHENIX GitHub at line 197 of file SvtxTrack.h
Referenced by SvtxTrack_v1::CopyFrom(), SvtxTrack_v2::CopyFrom(), SvtxTrack_v3::CopyFrom(), EMCalCalib::eval_photon(), EMCalAna::eval_trk(), PhotonJet::GetRecoHadronsAndJets(), AnaTutorial::getTracks(), DISKinematicsReco::InsertCandidateFromCluster(), Conversion::minDca(), PhotonJet::process_event(), and TruthConversionEval::processTrackBackground().
virtual float SvtxTrack::get_dca2d () const inline virtual
Reimplemented in SvtxTrack_v3, SvtxTrack_v2, and SvtxTrack_v1.
Definition at line 201 of file SvtxTrack.h.
View newest version in sPHENIX GitHub at line 201 of file SvtxTrack.h
Referenced by SvtxTrack_v1::CopyFrom(), SvtxTrack_v2::CopyFrom(), SvtxTrack_v3::CopyFrom(), EMCalCalib::eval_photon(), EMCalAna::eval_trk(), AnaSvtxTracksForGenFit::fill_tree(), GenFitTrackProp::fill_tree(), psTOFTimezeroEval::fillOutputNtuples(), SvtxEvaluatorHaiwang::fillOutputNtuples(), SvtxSimPerformanceCheckReco::process_event(), TrackingPerformanceCheck::process_event(), SimpleTrackingAnalysis::process_event(), and sPHElectronv1::sPHElectronv1().
virtual float SvtxTrack::get_dca2d_error () const inline virtual
Reimplemented in SvtxTrack_v3, SvtxTrack_v2, and SvtxTrack_v1.
Definition at line 203 of file SvtxTrack.h.
View newest version in sPHENIX GitHub at line 203 of file SvtxTrack.h
Referenced by SvtxTrack_v1::CopyFrom(), SvtxTrack_v3::CopyFrom(), SvtxTrack_v2::CopyFrom(), EMCalCalib::eval_photon(), EMCalAna::eval_trk(), psTOFTimezeroEval::fillOutputNtuples(), SvtxEvaluatorHaiwang::fillOutputNtuples(), and sPHElectronv1::sPHElectronv1().
virtual float SvtxTrack::get_dca3d_xy () const inline virtual
Reimplemented in SvtxTrack_v3, SvtxTrack_v2, and SvtxTrack_v1.
Definition at line 205 of file SvtxTrack.h.
View newest version in sPHENIX GitHub at line 205 of file SvtxTrack.h
Referenced by SvtxTrack_v1::CopyFrom(), SvtxTrack_v3::CopyFrom(), SvtxTrack_v2::CopyFrom(), SVReco::InitEvent(), TPCGemGainCalb::process_event(), sPHAnalysis::process_event_test(), sPHAnalysis::process_event_upsilons(), and sPHElectronv1::sPHElectronv1().
virtual float SvtxTrack::get_dca3d_xy_error () const inline virtual
Reimplemented in SvtxTrack_v3, SvtxTrack_v2, and SvtxTrack_v1.
Definition at line 207 of file SvtxTrack.h.
View newest version in sPHENIX GitHub at line 207 of file SvtxTrack.h
Referenced by SvtxTrack_v1::CopyFrom(), SvtxTrack_v3::CopyFrom(), and SvtxTrack_v2::CopyFrom().
virtual float SvtxTrack::get_dca3d_z () const inline virtual
Reimplemented in SvtxTrack_v3, SvtxTrack_v2, and SvtxTrack_v1.
Definition at line 209 of file SvtxTrack.h.
View newest version in sPHENIX GitHub at line 209 of file SvtxTrack.h
Referenced by SvtxTrack_v1::CopyFrom(), SvtxTrack_v2::CopyFrom(), SvtxTrack_v3::CopyFrom(), SVReco::InitEvent(), TPCGemGainCalb::process_event(), and sPHElectronv1::sPHElectronv1().
virtual float SvtxTrack::get_dca3d_z_error () const inline virtual
Reimplemented in SvtxTrack_v3, SvtxTrack_v2, and SvtxTrack_v1.
Definition at line 211 of file SvtxTrack.h.
View newest version in sPHENIX GitHub at line 211 of file SvtxTrack.h
Referenced by SvtxTrack_v1::CopyFrom(), SvtxTrack_v3::CopyFrom(), and SvtxTrack_v2::CopyFrom().
virtual float SvtxTrack::get_dca_error () const inline virtual
Reimplemented in SvtxTrack_v3, SvtxTrack_v2, and SvtxTrack_v1.
Definition at line 199 of file SvtxTrack.h.
View newest version in sPHENIX GitHub at line 199 of file SvtxTrack.h
Referenced by SvtxTrack_v1::CopyFrom(), SvtxTrack_v3::CopyFrom(), and SvtxTrack_v2::CopyFrom().
virtual float SvtxTrack::get_error (int , int) const inline virtual
Reimplemented in SvtxTrack_v3, SvtxTrack_v2, SvtxTrack_v1, and SvtxTrack_v4.
Definition at line 126 of file SvtxTrack.h.
View newest version in sPHENIX GitHub at line 126 of file SvtxTrack.h
Referenced by BJetModule::calc3DDCA(), IsolatedTrackAnalysis::calculateDCA(), TrkrNtuplizer::fillOutputNtuples(), SvtxEvaluator::fillOutputNtuples(), TrackAnalysisUtils::get_dca(), FilterEvents::get_dca(), SecondaryVertexFinder::get_dca(), HelicalFitter::get_dca(), FilterEvents::get_dca_SvtxEval(), FullJetFinder::GetDistanceFromVertexXY(), SVReco::MakeGenFitTrack(), KFParticle_Tools::makeParticle(), PHActsVertexFitter::makeTrackParam(), TrackResiduals::process_event(), and PHActsVertexPropagator::setVtxChi2().
virtual float SvtxTrack::get_eta () const inline virtual
Reimplemented in SvtxTrack_v3, SvtxTrack_v2, SvtxTrack_v1, and SvtxTrack_v4.
Definition at line 123 of file SvtxTrack.h.
View newest version in sPHENIX GitHub at line 123 of file SvtxTrack.h
Referenced by ExclusiveReco::AddInvariantMassInformation(), LeptoquarksReco::AddTrackInformation(), cemcReco::coneSum(), PhotonJet::ConeSum(), HFTrackEfficiency::findTracks(), PhotonJet::GetRecoHadronsAndJets(), Conversion::getTrackEtas(), AnaTutorial::getTracks(), IsolatedTrackAnalysis::getTracks(), DISKinematicsReco::InsertCandidateFromCluster(), ResonanceJetTagging::isAcceptableTrack(), SecondaryVertexFinder::outputTrackDetails(), RecoConversionEval::pairCuts(), SecondaryVertexFinder::passConversionElectronCuts(), BJetModule::process_event(), ParticleFlowReco::process_event(), PHGenFitTrackProjection::process_event(), PhotonJet::process_event(), jetrtrack::process_event(), BDiJetModule::process_event(), sPHAnalysis::process_event_test(), sPHAnalysis::process_event_upsilons(), TruthConversionEval::processTrackBackground(), VtxRegressor::regress(), Conversion::trackDEta(), and TruthConversionEval::tracktoTLV().
virtual unsigned int SvtxTrack::get_id () const inline virtual
Reimplemented in SvtxTrack_v4, SvtxTrack_v2, SvtxTrack_v3, and SvtxTrack_v1.
Definition at line 70 of file SvtxTrack.h.
View newest version in sPHENIX GitHub at line 70 of file SvtxTrack.h
Referenced by ResonanceJetTagging::addTracks(), SvtxTrackEval::all_truth_particles(), SvtxTrack_v1::CopyFrom(), SvtxTrack_v2::CopyFrom(), SvtxTrack_v3::CopyFrom(), EMCalCalib::eval_photon(), EMCalAna::eval_trk(), ActsEvaluator::evaluateTrackFit(), AnaSvtxTracksForGenFit::fill_tree(), GenFitTrackProp::fill_tree(), ActsAlignmentStates::fillAlignmentStateMap(), psTOFTimezeroEval::fillOutputNtuples(), SvtxEvaluatorHaiwang::fillOutputNtuples(), TrkrNtuplizer::fillOutputNtuples(), SvtxEvaluator::fillOutputNtuples(), PHSimpleVertexFinder::findDcaTwoTracks(), SVReco::findSecondaryVertex(), FilterEvents::get_dca(), SecondaryVertexFinder::get_dca(), TrackJetInput::get_input(), FullJetFinder::GetDistanceFromVertexXY(), SVReco::getPHGFTrack(), Conversion::getRecoTrack(), PHCosmicsTrkFitter::getTrackFitResult(), PHActsTrkFitter::getTrackFitResult(), KFParticle_truthAndDetTools::getTruthTrack(), SVReco::InitEvent(), DISKinematicsReco::InsertCandidateFromCluster(), ResonanceJetTagging::isDecay(), SVReco::MakeGenFitTrack(), KFParticle_Tools::makeParticle(), TpcPrototypeGenFitTrkFitter::MakeTpcPrototypeTrack(), SvtxTrackEval::max_truth_particle_by_nclusters(), SvtxTrackMap_v1::operator=(), Conversion::PHG4VtxPointToSvtxVertex(), SvtxEvaluatorHaiwang::printOutputInfo(), psTOFTimezeroEval::printOutputInfo(), FastPid_RICH::process_event(), RICHEvaluator::process_event(), QAG4SimulationTracking::process_event(), QAG4SimulationKFParticle::process_event(), RICHParticleID::process_event(), PHGenFitTrackProjection::process_event(), MakeMilleFiles::process_event(), BDiJetModule::process_event(), TruthConversionEval::process_event(), TpcPrototypeGenFitTrkFitter::process_event(), TpcDirectLaserReconstruction::process_track(), Conversion::setRecoTrack(), Conversion::setRecoTracks(), sPHElectronv1::sPHElectronv1(), and SvtxTrackMap_v1::SvtxTrackMap_v1().
virtual float SvtxTrack::get_mom (unsigned int) const inline virtual
Reimplemented in SvtxTrack_v3, SvtxTrack_v2, SvtxTrack_v1, and SvtxTrack_v4.
Definition at line 119 of file SvtxTrack.h.
View newest version in sPHENIX GitHub at line 119 of file SvtxTrack.h
virtual unsigned int SvtxTrack::get_ndf () const inline virtual
Reimplemented in SvtxTrack_v4, SvtxTrack_v3, SvtxTrack_v2, and SvtxTrack_v1.
Definition at line 94 of file SvtxTrack.h.
View newest version in sPHENIX GitHub at line 94 of file SvtxTrack.h
Referenced by SvtxTrack_v1::CopyFrom(), SvtxTrack_v2::CopyFrom(), SvtxTrack_v3::CopyFrom(), SvtxTrack_v4::CopyFrom(), EMCalCalib::eval_photon(), EMCalAna::eval_trk(), psTOFTimezeroEval::fillOutputNtuples(), SvtxEvaluatorHaiwang::fillOutputNtuples(), TrkrNtuplizer::fillOutputNtuples(), SvtxEvaluator::fillOutputNtuples(), HFTrackEfficiency::findTracks(), FilterEvents::get_dca(), FullJetFinder::GetDistanceFromVertexXY(), PhotonJet::GetRecoHadronsAndJets(), AnaTutorial::getTracks(), IsolatedTrackAnalysis::getTracks(), SVReco::InitEvent(), PairMaker::isElectron(), KFParticle_Tools::makeParticle(), TpcPrototypeGenFitTrkFitter::MakeTpcPrototypeTrack(), TrackingPerformanceCheck::process_event(), FilterEvents::process_event(), BJetModule::process_event(), PHTrackSelector::process_event(), PHTrackCleaner::process_event(), TPCGemGainCalb::process_event(), TrackResiduals::process_event(), PhotonJet::process_event(), PHRaveVertexing::process_event(), BDiJetModule::process_event(), FullJetFinder::process_event(), sPHAnalysis::process_event_test(), sPHAnalysis::process_event_upsilons(), sPHElectronv1::sPHElectronv1(), and PHRaveVertexing::TranslateSvtxToGenFitTrack().
virtual unsigned int SvtxTrack::get_num_measurements () const inline virtual
Reimplemented in SvtxTrack_FastSim, SvtxTrack_FastSim_v2, and SvtxTrack_FastSim_v3.
Definition at line 223 of file SvtxTrack.h.
View newest version in sPHENIX GitHub at line 223 of file SvtxTrack.h
Referenced by SvtxTrack_FastSim_v2::CopyFrom(), SvtxTrack_FastSim_v3::CopyFrom(), and SvtxTrack_FastSim::CopyFrom().
virtual float SvtxTrack::get_p () const inline virtual
Reimplemented in SvtxTrack_v3, SvtxTrack_v2, SvtxTrack_v1, and SvtxTrack_v4.
Definition at line 121 of file SvtxTrack.h.
View newest version in sPHENIX GitHub at line 121 of file SvtxTrack.h
Referenced by ExclusiveReco::AddInvariantMassInformation(), LeptoquarksReco::AddTrackInformation(), PHSimpleVertexFinder::findDcaTwoTracks(), JetRecoEval::get_energy_contribution(), TrackJetInput::get_input(), Conversion::getRecoPhoton(), Conversion::getRecoTlvs(), IsolatedTrackAnalysis::getTracks(), DISKinematicsReco::InsertCandidateFromCluster(), PHActsVertexFitter::makeTrackParam(), ActsPropagator::makeTrackParams(), PHTpcResiduals::makeTrackParams(), SimpleTrackingAnalysis::process_event(), ParticleFlowReco::process_event(), ElectronID::process_event(), PHTpcResiduals::processTrack(), RecoConversionEval::reconstructPhoton(), and Conversion::setRecoPhoton().
virtual float SvtxTrack::get_phi () const inline virtual
Reimplemented in SvtxTrack_v3, SvtxTrack_v2, SvtxTrack_v1, and SvtxTrack_v4.
Definition at line 124 of file SvtxTrack.h.
View newest version in sPHENIX GitHub at line 124 of file SvtxTrack.h
Referenced by ExclusiveReco::AddInvariantMassInformation(), LeptoquarksReco::AddTrackInformation(), cemcReco::coneSum(), PhotonJet::ConeSum(), PhotonJet::GetRecoHadronsAndJets(), Conversion::getTrackPhis(), AnaTutorial::getTracks(), IsolatedTrackAnalysis::getTracks(), DISKinematicsReco::InsertCandidateFromCluster(), ParticleFlowReco::process_event(), BJetModule::process_event(), PHTpcClusterMover::process_event(), PHGenFitTrackProjection::process_event(), MakeMilleFiles::process_event(), PhotonJet::process_event(), jetrtrack::process_event(), BDiJetModule::process_event(), VtxRegressor::regress(), Conversion::trackDPhi(), TruthConversionEval::tracktoTLV(), Conversion::vtxTrackRPhi(), and RecoConversionEval::vtxTrackRPhiCut().
virtual float SvtxTrack::get_pos (unsigned int) const inline virtual
Reimplemented in SvtxTrack_v3, SvtxTrack_v2, SvtxTrack_v1, and SvtxTrack_v4.
Definition at line 108 of file SvtxTrack.h.
View newest version in sPHENIX GitHub at line 108 of file SvtxTrack.h
virtual bool SvtxTrack::get_positive_charge () const inline virtual
Reimplemented in SvtxTrack_v4, SvtxTrack_v3, SvtxTrack_v2, and SvtxTrack_v1.
Definition at line 85 of file SvtxTrack.h.
View newest version in sPHENIX GitHub at line 85 of file SvtxTrack.h
Referenced by SvtxTrack_v1::CopyFrom(), SvtxTrack_v2::CopyFrom(), SvtxTrack_v3::CopyFrom(), and SvtxTrack_v4::CopyFrom().
virtual float SvtxTrack::get_pt () const inline virtual
Reimplemented in SvtxTrack_v3, SvtxTrack_v2, SvtxTrack_v1, and SvtxTrack_v4.
Definition at line 122 of file SvtxTrack.h.
View newest version in sPHENIX GitHub at line 122 of file SvtxTrack.h
Referenced by TpcSpaceChargeReconstruction::accept_track(), QAG4SimulationDistortions::checkTrack(), PHTpcResiduals::checkTrack(), PHSimpleVertexFinder::findDcaTwoTracks(), HFTrackEfficiency::findTracks(), SecondaryVertexFinder::getCircleXYTrack(), Conversion::getTrackpTs(), IsolatedTrackAnalysis::getTracks(), SecondaryVertexFinder::getZFromIntersectionXY(), SVReco::InitEvent(), DISKinematicsReco::InsertCandidateFromCluster(), ResonanceJetTagging::isAcceptableTrack(), Conversion::minTrackpT(), SecondaryVertexFinder::outputTrackDetails(), SvtxSimPerformanceCheckReco::process_event(), SimpleTrackingAnalysis::process_event(), STACalorimeterCharacterization::process_event(), ParticleFlowReco::process_event(), BJetModule::process_event(), TPCGemGainCalb::process_event(), PHGenFitTrackProjection::process_event(), RecoConversionEval::process_event(), jetrtrack::process_event(), BDiJetModule::process_event(), TruthConversionEval::process_event(), TpcPrototypeGenFitTrkFitter::process_event(), PHGenFitTrkFitter::process_event(), TruthConversionEval::processTrackBackground(), VtxRegressor::regress(), and TruthConversionEval::tracktoTLV().
virtual float SvtxTrack::get_px () const inline virtual
Reimplemented in SvtxTrack_v3, SvtxTrack_v2, SvtxTrack_v1, and SvtxTrack_v4.
Definition at line 110 of file SvtxTrack.h.
View newest version in sPHENIX GitHub at line 110 of file SvtxTrack.h
Referenced by ResonanceJetTagging::addTracks(), RecoConversionEval::approachDistance(), Conversion::approachDistance(), BJetModule::calc3DDCA(), IsolatedTrackAnalysis::calculateDCA(), cemcReco::coneSum(), PhotonJet::ConeSum(), EMCalCalib::eval_photon(), EMCalAna::eval_trk(), EMCalAna::eval_trk_proj(), QAG4SimulationCalorimeterSum::eval_trk_proj(), AnaSvtxTracksForGenFit::fill_tree(), GenFitTrackProp::fill_tree(), KshortReconstruction::fillNtp(), SecondaryVertexFinder::fillNtp(), psTOFTimezeroEval::fillOutputNtuples(), SvtxEvaluatorHaiwang::fillOutputNtuples(), TrkrNtuplizer::fillOutputNtuples(), SvtxEvaluator::fillOutputNtuples(), PHSimpleVertexFinder::findDcaTwoTracks(), ElectronID::findMCmatch(), HFTrackEfficiency::findTracks(), TrackAnalysisUtils::get_dca(), FilterEvents::get_dca(), SecondaryVertexFinder::get_dca(), HelicalFitter::get_dca(), FilterEvents::get_dca_SvtxEval(), TrackJetInput::get_input(), HelicalFitter::get_projectionVtxXY(), SecondaryVertexFinder::getCircleXYTrack(), FullJetFinder::GetDistanceFromVertexXY(), HelicalFitter::getGlobalVtxDerivativesXY(), HelicalFitter::getLocalVtxDerivativesXY(), MakeMilleFiles::getProjectionVtxXY(), PhotonJet::GetRecoHadronsAndJets(), Conversion::getRecoPhoton(), Conversion::getRecoTlvs(), AnaTutorial::getTracks(), HelicalFitter::globalvtxToLocalvtx(), PairMaker::isElectron(), sPHAnalysis::isElectron(), MakeMilleFiles::localToGlobalVertex(), HelicalFitter::localvtxToGlobalvtx(), SVReco::MakeGenFitTrack(), QAG4SimulationKFParticle::makeHepLV(), KFParticle_Tools::makeParticle(), PHActsGSF::makeSeed(), TpcPrototypeGenFitTrkFitter::MakeTpcPrototypeTrack(), HFTrigger::makeTrack(), HFTriggerMVA::makeTrack(), PHActsVertexFitter::makeTrackParam(), ActsPropagator::makeTrackParams(), PHTpcResiduals::makeTrackParams(), SvtxEvaluatorHaiwang::printOutputInfo(), psTOFTimezeroEval::printOutputInfo(), MomentumEvaluator::process_event(), TrackingPerformanceCheck::process_event(), QAG4SimulationUpsilon::process_event(), FilterEventsUpsilon::process_event(), FilterEvents::process_event(), BJetModule::process_event(), QAG4SimulationTracking::process_event(), TrackResiduals::process_event(), ElectronID::process_event(), PhotonJet::process_event(), PairMaker::process_event_test(), sPHAnalysis::process_event_test(), sPHAnalysis::process_event_upsilons(), TpcDirectLaserReconstruction::process_track(), KshortReconstruction::projectTrackToPoint(), SecondaryVertexFinder::projectTrackToPoint(), RecoConversionEval::reconstructPhoton(), PHFlowJetMaker::run_particle_flow(), Conversion::setRecoPhoton(), TPCHitTrackDisplay::SimulationOut(), sPHElectronv1::sPHElectronv1(), and PHActsGSF::updateSvtxTrack().
virtual float SvtxTrack::get_py () const inline virtual
Reimplemented in SvtxTrack_v3, SvtxTrack_v2, SvtxTrack_v1, and SvtxTrack_v4.
Definition at line 113 of file SvtxTrack.h.
View newest version in sPHENIX GitHub at line 113 of file SvtxTrack.h
Referenced by ResonanceJetTagging::addTracks(), RecoConversionEval::approachDistance(), Conversion::approachDistance(), BJetModule::calc3DDCA(), IsolatedTrackAnalysis::calculateDCA(), cemcReco::coneSum(), PhotonJet::ConeSum(), EMCalCalib::eval_photon(), EMCalAna::eval_trk(), EMCalAna::eval_trk_proj(), QAG4SimulationCalorimeterSum::eval_trk_proj(), AnaSvtxTracksForGenFit::fill_tree(), GenFitTrackProp::fill_tree(), KshortReconstruction::fillNtp(), SecondaryVertexFinder::fillNtp(), psTOFTimezeroEval::fillOutputNtuples(), SvtxEvaluatorHaiwang::fillOutputNtuples(), TrkrNtuplizer::fillOutputNtuples(), SvtxEvaluator::fillOutputNtuples(), PHSimpleVertexFinder::findDcaTwoTracks(), ElectronID::findMCmatch(), HFTrackEfficiency::findTracks(), TrackAnalysisUtils::get_dca(), FilterEvents::get_dca(), SecondaryVertexFinder::get_dca(), HelicalFitter::get_dca(), FilterEvents::get_dca_SvtxEval(), TrackJetInput::get_input(), HelicalFitter::get_projectionVtxXY(), SecondaryVertexFinder::getCircleXYTrack(), FullJetFinder::GetDistanceFromVertexXY(), HelicalFitter::getGlobalVtxDerivativesXY(), HelicalFitter::getLocalVtxDerivativesXY(), MakeMilleFiles::getProjectionVtxXY(), PhotonJet::GetRecoHadronsAndJets(), Conversion::getRecoPhoton(), Conversion::getRecoTlvs(), AnaTutorial::getTracks(), HelicalFitter::globalvtxToLocalvtx(), PairMaker::isElectron(), sPHAnalysis::isElectron(), MakeMilleFiles::localToGlobalVertex(), HelicalFitter::localvtxToGlobalvtx(), SVReco::MakeGenFitTrack(), QAG4SimulationKFParticle::makeHepLV(), KFParticle_Tools::makeParticle(), PHActsGSF::makeSeed(), TpcPrototypeGenFitTrkFitter::MakeTpcPrototypeTrack(), HFTrigger::makeTrack(), HFTriggerMVA::makeTrack(), PHActsVertexFitter::makeTrackParam(), ActsPropagator::makeTrackParams(), PHTpcResiduals::makeTrackParams(), SvtxEvaluatorHaiwang::printOutputInfo(), psTOFTimezeroEval::printOutputInfo(), MomentumEvaluator::process_event(), TrackingPerformanceCheck::process_event(), QAG4SimulationUpsilon::process_event(), FilterEventsUpsilon::process_event(), FilterEvents::process_event(), BJetModule::process_event(), QAG4SimulationTracking::process_event(), TrackResiduals::process_event(), ElectronID::process_event(), PhotonJet::process_event(), PairMaker::process_event_test(), sPHAnalysis::process_event_test(), sPHAnalysis::process_event_upsilons(), TpcDirectLaserReconstruction::process_track(), KshortReconstruction::projectTrackToPoint(), SecondaryVertexFinder::projectTrackToPoint(), RecoConversionEval::reconstructPhoton(), PHFlowJetMaker::run_particle_flow(), Conversion::setRecoPhoton(), TPCHitTrackDisplay::SimulationOut(), sPHElectronv1::sPHElectronv1(), and PHActsGSF::updateSvtxTrack().
virtual float SvtxTrack::get_pz () const inline virtual
Reimplemented in SvtxTrack_v3, SvtxTrack_v2, SvtxTrack_v1, and SvtxTrack_v4.
Definition at line 116 of file SvtxTrack.h.
View newest version in sPHENIX GitHub at line 116 of file SvtxTrack.h
Referenced by ResonanceJetTagging::addTracks(), RecoConversionEval::approachDistance(), Conversion::approachDistance(), BJetModule::calc3DDCA(), IsolatedTrackAnalysis::calculateDCA(), EMCalCalib::eval_photon(), EMCalAna::eval_trk(), EMCalAna::eval_trk_proj(), QAG4SimulationCalorimeterSum::eval_trk_proj(), AnaSvtxTracksForGenFit::fill_tree(), GenFitTrackProp::fill_tree(), KshortReconstruction::fillNtp(), SecondaryVertexFinder::fillNtp(), SvtxEvaluatorHaiwang::fillOutputNtuples(), psTOFTimezeroEval::fillOutputNtuples(), TrkrNtuplizer::fillOutputNtuples(), SvtxEvaluator::fillOutputNtuples(), PHSimpleVertexFinder::findDcaTwoTracks(), ElectronID::findMCmatch(), HFTrackEfficiency::findTracks(), TrackAnalysisUtils::get_dca(), FilterEvents::get_dca(), SecondaryVertexFinder::get_dca(), HelicalFitter::get_dca(), FilterEvents::get_dca_SvtxEval(), TrackJetInput::get_input(), HelicalFitter::get_projectionVtxXY(), FullJetFinder::GetDistanceFromVertexXY(), HelicalFitter::getGlobalVtxDerivativesXY(), HelicalFitter::getLocalVtxDerivativesXY(), MakeMilleFiles::getProjectionVtxXY(), PhotonJet::GetRecoHadronsAndJets(), Conversion::getRecoPhoton(), Conversion::getRecoTlvs(), AnaTutorial::getTracks(), SecondaryVertexFinder::getZFromIntersectionXY(), HelicalFitter::globalvtxToLocalvtx(), PairMaker::isElectron(), sPHAnalysis::isElectron(), MakeMilleFiles::localToGlobalVertex(), HelicalFitter::localvtxToGlobalvtx(), SVReco::MakeGenFitTrack(), QAG4SimulationKFParticle::makeHepLV(), KFParticle_Tools::makeParticle(), PHActsGSF::makeSeed(), TpcPrototypeGenFitTrkFitter::MakeTpcPrototypeTrack(), HFTrigger::makeTrack(), HFTriggerMVA::makeTrack(), PHActsVertexFitter::makeTrackParam(), ActsPropagator::makeTrackParams(), PHTpcResiduals::makeTrackParams(), SvtxEvaluatorHaiwang::printOutputInfo(), psTOFTimezeroEval::printOutputInfo(), MomentumEvaluator::process_event(), TrackingPerformanceCheck::process_event(), QAG4SimulationUpsilon::process_event(), FilterEvents::process_event(), FilterEventsUpsilon::process_event(), BJetModule::process_event(), QAG4SimulationTracking::process_event(), TrackResiduals::process_event(), PhotonJet::process_event(), sPHAnalysis::process_event_test(), sPHAnalysis::process_event_upsilons(), TpcDirectLaserReconstruction::process_track(), KshortReconstruction::projectTrackToPoint(), SecondaryVertexFinder::projectTrackToPoint(), RecoConversionEval::reconstructPhoton(), PHFlowJetMaker::run_particle_flow(), Conversion::setRecoPhoton(), TPCHitTrackDisplay::SimulationOut(), sPHElectronv1::sPHElectronv1(), and PHActsGSF::updateSvtxTrack().
virtual float SvtxTrack::get_quality () const inline virtual
Reimplemented in SvtxTrack_v4, SvtxTrack_v3, SvtxTrack_v2, and SvtxTrack_v1.
Definition at line 97 of file SvtxTrack.h.
View newest version in sPHENIX GitHub at line 97 of file SvtxTrack.h
Referenced by LeptoquarksReco::AddTrackInformation(), TrkrNtuplizer::best_track_from(), EMCalCalib::eval_photon(), EMCalAna::eval_trk(), ActsEvaluator::evaluateTrackFit(), KshortReconstruction::fillNtp(), SecondaryVertexFinder::fillNtp(), psTOFTimezeroEval::fillOutputNtuples(), SvtxEvaluatorHaiwang::fillOutputNtuples(), TrkrNtuplizer::fillOutputNtuples(), SvtxEvaluator::fillOutputNtuples(), MultiDetectorMultiplicity::getFilteredNtracks(), DISKinematicsReco::InsertCandidateFromCluster(), SecondaryVertexFinder::outputTrackDetails(), psTOFTimezeroEval::printOutputInfo(), SvtxEvaluatorHaiwang::printOutputInfo(), MomentumEvaluator::process_event(), SvtxSimPerformanceCheckReco::process_event(), SimpleTrackingAnalysis::process_event(), BJetModule::process_event(), TrackResiduals::process_event(), ElectronID::process_event(), jetrtrack::process_event(), and PHFlowJetMaker::run_particle_flow().
virtual TrackSeed* SvtxTrack::get_silicon_seed () const inline virtual
Reimplemented in SvtxTrack_v4.
Definition at line 76 of file SvtxTrack.h.
View newest version in sPHENIX GitHub at line 76 of file SvtxTrack.h
Referenced by SvtxTrack_v4::CopyFrom(), TrackEvaluation::create_cluster(), ActsAlignmentStates::fillAlignmentStateMap(), TrkrNtuplizer::fillOutputNtuples(), SvtxEvaluator::fillOutputNtuples(), HFTrackEfficiency::findTracks(), QAG4SimulationDistortions::get_cluster_keys(), TrackAnalysisUtils::get_cluster_keys(), TrkrNtuplizer::get_track_ckeys(), SvtxTrackEval::get_track_ckeys(), MultiDetectorMultiplicity::getFilteredNtracks(), PHCosmicsTrkFitter::getTrackFitResult(), PHActsTrkFitter::getTrackFitResult(), IsolatedTrackAnalysis::getTracks(), SecondaryVertexFinder::hasSiliconSeed(), KFParticle_Tools::makeAllDaughterParticles(), SecondaryVertexFinder::outputTrackDetails(), FilterEventsUpsilon::process_event(), FilterEvents::process_event(), QAG4SimulationVertex::process_event(), BJetModule::process_event(), QAG4SimulationTracking::process_event(), jetrtrack::process_event(), sPHAnalysis::process_event_test(), sPHAnalysis::process_event_upsilons(), and TPCHitTrackDisplay::SimulationOut().
virtual const SvtxTrackState* SvtxTrack::get_state (float) const inline virtual
Reimplemented in SvtxTrack_v3, SvtxTrack_v2, SvtxTrack_v1, and SvtxTrack_v4.
Definition at line 137 of file SvtxTrack.h.
View newest version in sPHENIX GitHub at line 137 of file SvtxTrack.h
Referenced by sPHAnalysis::Get_CAL_e3x3(), FilterEventsUpsilon::GetProjectionCEMC(), FilterEvents::GetProjectionCEMC(), sPHAnalysis::GetProjectionToCalorimeter(), FilterEventsUpsilon::MatchClusterCEMC(), FilterEvents::MatchClusterCEMC(), sPHAnalysis::MatchClusterCEMC(), and ParticleFlowReco::process_event().
virtual SvtxTrackState* SvtxTrack::get_state (float) inline virtual
Reimplemented in SvtxTrack_v3, SvtxTrack_v2, SvtxTrack_v1, and SvtxTrack_v4.
Definition at line 138 of file SvtxTrack.h.
View newest version in sPHENIX GitHub at line 138 of file SvtxTrack.h
virtual TrackSeed* SvtxTrack::get_tpc_seed () const inline virtual
Reimplemented in SvtxTrack_v4.
Definition at line 73 of file SvtxTrack.h.
View newest version in sPHENIX GitHub at line 73 of file SvtxTrack.h
Referenced by SvtxTrack_v4::CopyFrom(), TrackEvaluation::create_cluster(), KshortReconstruction::fillNtp(), SecondaryVertexFinder::fillNtp(), TrkrNtuplizer::fillOutputNtuples(), SvtxEvaluator::fillOutputNtuples(), HFTrackEfficiency::findTracks(), QAG4SimulationDistortions::get_cluster_keys(), TrackAnalysisUtils::get_cluster_keys(), TrkrNtuplizer::get_track_ckeys(), SvtxTrackEval::get_track_ckeys(), MultiDetectorMultiplicity::getFilteredNtracks(), PHCosmicsTrkFitter::getTrackFitResult(), PHActsTrkFitter::getTrackFitResult(), KFParticle_Tools::makeAllDaughterParticles(), SecondaryVertexFinder::outputTrackDetails(), SecondaryVertexFinder::passConversionElectronCuts(), FilterEvents::process_event(), FilterEventsUpsilon::process_event(), QAG4SimulationVertex::process_event(), QAG4SimulationTracking::process_event(), sPHAnalysis::process_event_test(), sPHAnalysis::process_event_upsilons(), and TPCHitTrackDisplay::SimulationOut().
virtual unsigned int SvtxTrack::get_truth_track_id () const inline virtual
Reimplemented in SvtxTrack_FastSim, SvtxTrack_FastSim_v2, and SvtxTrack_FastSim_v3.
Definition at line 220 of file SvtxTrack.h.
View newest version in sPHENIX GitHub at line 220 of file SvtxTrack.h
Referenced by RICHEvaluator::calculate_true_emission_angle(), SvtxTrack_FastSim_v3::CopyFrom(), SvtxTrack_FastSim_v2::CopyFrom(), SvtxTrack_FastSim::CopyFrom(), SetupDualRICHAnalyzer::get_true_momentum(), FastPid_RICH::process_event(), and RICHParticleID::process_event().
virtual unsigned int SvtxTrack::get_vertex_id () const inline virtual
Reimplemented in SvtxTrack_v4, SvtxTrack_v3, SvtxTrack_v2, and SvtxTrack_v1.
Definition at line 82 of file SvtxTrack.h.
View newest version in sPHENIX GitHub at line 82 of file SvtxTrack.h
Referenced by BJetModule::calc3DDCA(), KshortReconstruction::calculateDca(), IsolatedTrackAnalysis::calculateDCA(), SvtxTrack_v1::CopyFrom(), SvtxTrack_v2::CopyFrom(), SvtxTrack_v3::CopyFrom(), SvtxTrack_v4::CopyFrom(), PHActsToSvtxTracks::createSvtxTrack(), KshortReconstruction::fillNtp(), SecondaryVertexFinder::fillNtp(), TrkrNtuplizer::fillOutputNtuples(), SvtxEvaluator::fillOutputNtuples(), FilterEvents::get_dca(), QAG4SimulationTracking::get_dca(), SecondaryVertexFinder::get_dca(), FilterEvents::get_dca_SvtxEval(), IsolatedTrackAnalysis::getTracks(), KshortReconstruction::getVertex(), PHActsGSF::makePerigee(), ActsPropagator::makeTrackParams(), SecondaryVertexFinder::outputTrackDetails(), BJetModule::process_event(), TPCGemGainCalb::process_event(), TrackResiduals::process_event(), ElectronID::process_event(), FullJetFinder::process_event(), and PairMaker::process_event_test().
virtual float SvtxTrack::get_x () const inline virtual
Reimplemented in SvtxTrack_v3, SvtxTrack_v2, SvtxTrack_v1, and SvtxTrack_v4.
Definition at line 99 of file SvtxTrack.h.
View newest version in sPHENIX GitHub at line 99 of file SvtxTrack.h
Referenced by RecoConversionEval::approachDistance(), Conversion::approachDistance(), BJetModule::calc3DDCA(), IsolatedTrackAnalysis::calculateDCA(), EMCalCalib::eval_photon(), EMCalAna::eval_trk(), EMCalAna::eval_trk_proj(), QAG4SimulationCalorimeterSum::eval_trk_proj(), KshortReconstruction::fillNtp(), SecondaryVertexFinder::fillNtp(), psTOFTimezeroEval::fillOutputNtuples(), SvtxEvaluatorHaiwang::fillOutputNtuples(), TrkrNtuplizer::fillOutputNtuples(), SvtxEvaluator::fillOutputNtuples(), PHSimpleVertexFinder::findDcaTwoTracks(), TrackAnalysisUtils::get_dca(), FilterEvents::get_dca(), SecondaryVertexFinder::get_dca(), HelicalFitter::get_dca(), FilterEvents::get_dca_SvtxEval(), SecondaryVertexFinder::getCircleXYTrack(), FullJetFinder::GetDistanceFromVertexXY(), MakeMilleFiles::getEventVertex(), HelicalFitter::getGlobalVtxDerivativesXY(), HelicalFitter::getLocalVtxDerivativesXY(), PhotonJet::GetRecoHadronsAndJets(), AnaTutorial::getTracks(), IsolatedTrackAnalysis::getTracks(), SecondaryVertexFinder::getZFromIntersectionXY(), HelicalFitter::globalvtxToLocalvtx(), SVReco::MakeGenFitTrack(), KFParticle_Tools::makeParticle(), PHActsGSF::makeSeed(), TpcPrototypeGenFitTrkFitter::MakeTpcPrototypeTrack(), HFTrigger::makeTrack(), HFTriggerMVA::makeTrack(), PHActsVertexFitter::makeTrackParam(), ActsPropagator::makeTrackParams(), PHTpcResiduals::makeTrackParams(), SecondaryVertexFinder::outputTrackDetails(), MomentumEvaluator::process_event(), BJetModule::process_event(), TPCGemGainCalb::process_event(), TrackResiduals::process_event(), MakeMilleFiles::process_event(), PhotonJet::process_event(), FullJetFinder::process_event(), PairMaker::process_event_test(), sPHAnalysis::process_event_upsilons(), TpcDirectLaserReconstruction::process_track(), PHTpcResiduals::processTrack(), KshortReconstruction::projectTrackToPoint(), SecondaryVertexFinder::projectTrackToPoint(), PHActsVertexPropagator::setVtxChi2(), PHActsInitialVertexFinder::sortTracks(), PHActsVertexPropagator::updateSvtxTrack(), PHActsGSF::updateSvtxTrack(), Conversion::vtxTrackRPhi(), RecoConversionEval::vtxTrackRPhiCut(), Conversion::vtxTrackRZ(), and RecoConversionEval::vtxTrackRZCut().
virtual float SvtxTrack::get_y () const inline virtual
Reimplemented in SvtxTrack_v3, SvtxTrack_v2, SvtxTrack_v1, and SvtxTrack_v4.
Definition at line 102 of file SvtxTrack.h.
View newest version in sPHENIX GitHub at line 102 of file SvtxTrack.h
Referenced by RecoConversionEval::approachDistance(), Conversion::approachDistance(), BJetModule::calc3DDCA(), IsolatedTrackAnalysis::calculateDCA(), EMCalCalib::eval_photon(), EMCalAna::eval_trk(), KshortReconstruction::fillNtp(), SecondaryVertexFinder::fillNtp(), psTOFTimezeroEval::fillOutputNtuples(), SvtxEvaluatorHaiwang::fillOutputNtuples(), TrkrNtuplizer::fillOutputNtuples(), SvtxEvaluator::fillOutputNtuples(), PHSimpleVertexFinder::findDcaTwoTracks(), TrackAnalysisUtils::get_dca(), FilterEvents::get_dca(), SecondaryVertexFinder::get_dca(), HelicalFitter::get_dca(), FilterEvents::get_dca_SvtxEval(), SecondaryVertexFinder::getCircleXYTrack(), FullJetFinder::GetDistanceFromVertexXY(), MakeMilleFiles::getEventVertex(), HelicalFitter::getGlobalVtxDerivativesXY(), HelicalFitter::getLocalVtxDerivativesXY(), PhotonJet::GetRecoHadronsAndJets(), AnaTutorial::getTracks(), IsolatedTrackAnalysis::getTracks(), SecondaryVertexFinder::getZFromIntersectionXY(), HelicalFitter::globalvtxToLocalvtx(), SVReco::MakeGenFitTrack(), KFParticle_Tools::makeParticle(), PHActsGSF::makeSeed(), TpcPrototypeGenFitTrkFitter::MakeTpcPrototypeTrack(), HFTrigger::makeTrack(), HFTriggerMVA::makeTrack(), PHActsVertexFitter::makeTrackParam(), ActsPropagator::makeTrackParams(), PHTpcResiduals::makeTrackParams(), SecondaryVertexFinder::outputTrackDetails(), MomentumEvaluator::process_event(), BJetModule::process_event(), TPCGemGainCalb::process_event(), TrackResiduals::process_event(), MakeMilleFiles::process_event(), PhotonJet::process_event(), FullJetFinder::process_event(), PairMaker::process_event_test(), sPHAnalysis::process_event_upsilons(), TpcDirectLaserReconstruction::process_track(), PHTpcResiduals::processTrack(), KshortReconstruction::projectTrackToPoint(), SecondaryVertexFinder::projectTrackToPoint(), PHActsVertexPropagator::setVtxChi2(), PHActsInitialVertexFinder::sortTracks(), PHActsVertexPropagator::updateSvtxTrack(), PHActsGSF::updateSvtxTrack(), Conversion::vtxTrackRPhi(), RecoConversionEval::vtxTrackRPhiCut(), Conversion::vtxTrackRZ(), and RecoConversionEval::vtxTrackRZCut().
virtual float SvtxTrack::get_z () const inline virtual
Reimplemented in SvtxTrack_v3, SvtxTrack_v2, SvtxTrack_v1, and SvtxTrack_v4.
Definition at line 105 of file SvtxTrack.h.
View newest version in sPHENIX GitHub at line 105 of file SvtxTrack.h
Referenced by RecoConversionEval::approachDistance(), Conversion::approachDistance(), BJetModule::calc3DDCA(), IsolatedTrackAnalysis::calculateDCA(), EMCalCalib::eval_photon(), EMCalAna::eval_trk(), EMCalAna::eval_trk_proj(), QAG4SimulationCalorimeterSum::eval_trk_proj(), KshortReconstruction::fillNtp(), SecondaryVertexFinder::fillNtp(), psTOFTimezeroEval::fillOutputNtuples(), SvtxEvaluatorHaiwang::fillOutputNtuples(), TrkrNtuplizer::fillOutputNtuples(), SvtxEvaluator::fillOutputNtuples(), PHSimpleVertexFinder::findDcaTwoTracks(), TrackAnalysisUtils::get_dca(), FilterEvents::get_dca(), SecondaryVertexFinder::get_dca(), HelicalFitter::get_dca(), FilterEvents::get_dca_SvtxEval(), FullJetFinder::GetDistanceFromVertexXY(), MakeMilleFiles::getEventVertex(), HelicalFitter::getGlobalVtxDerivativesXY(), HelicalFitter::getLocalVtxDerivativesXY(), PhotonJet::GetRecoHadronsAndJets(), AnaTutorial::getTracks(), IsolatedTrackAnalysis::getTracks(), SecondaryVertexFinder::getZFromIntersectionXY(), HelicalFitter::globalvtxToLocalvtx(), SVReco::MakeGenFitTrack(), KFParticle_Tools::makeParticle(), PHActsGSF::makeSeed(), TpcPrototypeGenFitTrkFitter::MakeTpcPrototypeTrack(), HFTrigger::makeTrack(), HFTriggerMVA::makeTrack(), PHActsVertexFitter::makeTrackParam(), ActsPropagator::makeTrackParams(), PHTpcResiduals::makeTrackParams(), SecondaryVertexFinder::outputTrackDetails(), MomentumEvaluator::process_event(), BJetModule::process_event(), TPCGemGainCalb::process_event(), TrackResiduals::process_event(), MakeMilleFiles::process_event(), ElectronID::process_event(), PhotonJet::process_event(), PairMaker::process_event_test(), sPHAnalysis::process_event_upsilons(), TpcDirectLaserReconstruction::process_track(), PHTpcResiduals::processTrack(), KshortReconstruction::projectTrackToPoint(), SecondaryVertexFinder::projectTrackToPoint(), PHActsVertexPropagator::setVtxChi2(), PHActsInitialVertexFinder::sortTracks(), sPHElectronv1::sPHElectronv1(), PHActsVertexPropagator::updateSvtxTrack(), PHActsGSF::updateSvtxTrack(), Conversion::vtxTrackRZ(), and RecoConversionEval::vtxTrackRZCut().
void SvtxTrack::identify (std::ostream & os = std::cout) const inline override virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from PHObject.
Reimplemented in SvtxTrack_v4, SvtxTrack_FastSim, SvtxTrack_v2, SvtxTrack_v3, SvtxTrack_v1, SvtxTrack_FastSim_v1, SvtxTrack_FastSim_v2, and SvtxTrack_FastSim_v3.
Definition at line 47 of file SvtxTrack.h.
View newest version in sPHENIX GitHub at line 47 of file SvtxTrack.h
References os.
Referenced by EMCalAna::eval_trk_proj(), HFTrackEfficiency::findTracks(), TpcPrototypeGenFitTrkFitter::MakeTpcPrototypeTrack(), psTOFTimezeroEval::printInputInfo(), SvtxEvaluatorHaiwang::printInputInfo(), TrkrNtuplizer::printInputInfo(), SvtxEvaluator::printInputInfo(), KFParticle_DST::printNode(), Conversion::PrintPhotonRecoInfo(), Conversion::printReco(), TpcPrototypeGenFitTrkFitter::process_event(), TpcPrototypeGenFitTrkFitter::ReFitTrack(), PHGenFitTrkFitter::ReFitTrack(), PHCosmicsTrkFitter::updateSvtxTrack(), and PHActsTrkFitter::updateSvtxTrack().
virtual void SvtxTrack::insert_cluster (unsigned int) inline virtual
Reimplemented in SvtxTrack_v3, SvtxTrack_v2, and SvtxTrack_v1.
Definition at line 170 of file SvtxTrack.h.
View newest version in sPHENIX GitHub at line 170 of file SvtxTrack.h
virtual void SvtxTrack::insert_cluster_key (TrkrDefs::cluskey) inline virtual
Reimplemented in SvtxTrack_v3, SvtxTrack_v2, and SvtxTrack_v1.
Definition at line 159 of file SvtxTrack.h.
View newest version in sPHENIX GitHub at line 159 of file SvtxTrack.h
Referenced by TrackSeedTrackMapConverter::addKeys().
virtual SvtxTrackState* SvtxTrack::insert_state (const SvtxTrackState *) inline virtual
Reimplemented in SvtxTrack_v3, SvtxTrack_v2, SvtxTrack_v1, and SvtxTrack_v4.
Definition at line 139 of file SvtxTrack.h.
View newest version in sPHENIX GitHub at line 139 of file SvtxTrack.h
Referenced by PHActsTrackPropagator::addTrackState(), PHTpcResiduals::addTrackState(), PHActsToSvtxTracks::createSvtxTrack(), ActsTransformations::fillSvtxTrackStates(), PHG4TrackFastSim::MakeSvtxTrack(), TpcDirectLaserReconstruction::process_track(), PHActsGSF::updateSvtxTrack(), PHActsTrackProjection::updateSvtxTrack(), PHCosmicsTrkFitter::updateSvtxTrack(), and PHActsTrkFitter::updateSvtxTrack().
int SvtxTrack::isValid () const inline override virtual
isValid returns non zero if object contains vailid data
Reimplemented from PHObject.
Reimplemented in SvtxTrack_v4, SvtxTrack_FastSim, SvtxTrack_v2, SvtxTrack_v3, SvtxTrack_v1, SvtxTrack_FastSim_v1, SvtxTrack_FastSim_v2, and SvtxTrack_FastSim_v3.
Definition at line 52 of file SvtxTrack.h.
View newest version in sPHENIX GitHub at line 52 of file SvtxTrack.h
virtual size_t SvtxTrack::remove_g4hit_id (int , PHG4HitDefs::keytype) inline virtual
Reimplemented in SvtxTrack_FastSim_v2, SvtxTrack_FastSim_v3, and SvtxTrack_FastSim_v1.
Definition at line 239 of file SvtxTrack.h.
View newest version in sPHENIX GitHub at line 239 of file SvtxTrack.h
virtual size_t SvtxTrack::remove_g4hit_volume (int) inline virtual
Reimplemented in SvtxTrack_FastSim_v2, SvtxTrack_FastSim_v3, and SvtxTrack_FastSim_v1.
Definition at line 240 of file SvtxTrack.h.
View newest version in sPHENIX GitHub at line 240 of file SvtxTrack.h
virtual void SvtxTrack::set_acts_covariance (unsigned int , unsigned int , float) inline virtual
Reimplemented in SvtxTrack_v3, and SvtxTrack_v2.
Definition at line 195 of file SvtxTrack.h.
View newest version in sPHENIX GitHub at line 195 of file SvtxTrack.h
virtual void SvtxTrack::set_cal_cluster_e (CAL_LAYER , float) inline virtual
Reimplemented in SvtxTrack_v3, and SvtxTrack_v2.
Definition at line 192 of file SvtxTrack.h.
View newest version in sPHENIX GitHub at line 192 of file SvtxTrack.h
Referenced by PHGenFitTrackProjection::process_event().
virtual void SvtxTrack::set_cal_cluster_id (CAL_LAYER , unsigned int) inline virtual
Reimplemented in SvtxTrack_v3, and SvtxTrack_v2.
Definition at line 188 of file SvtxTrack.h.
View newest version in sPHENIX GitHub at line 188 of file SvtxTrack.h
Referenced by PHGenFitTrackProjection::process_event().
virtual void SvtxTrack::set_cal_cluster_key (CAL_LAYER , TrkrDefs::cluskey) inline virtual
Reimplemented in SvtxTrack_v3, and SvtxTrack_v2.
Definition at line 190 of file SvtxTrack.h.
View newest version in sPHENIX GitHub at line 190 of file SvtxTrack.h
virtual void SvtxTrack::set_cal_deta (CAL_LAYER , float) inline virtual
Reimplemented in SvtxTrack_v3, and SvtxTrack_v2.
Definition at line 182 of file SvtxTrack.h.
View newest version in sPHENIX GitHub at line 182 of file SvtxTrack.h
Referenced by PHGenFitTrackProjection::process_event().
virtual void SvtxTrack::set_cal_dphi (CAL_LAYER , float) inline virtual
Reimplemented in SvtxTrack_v3, and SvtxTrack_v2.
Definition at line 180 of file SvtxTrack.h.
View newest version in sPHENIX GitHub at line 180 of file SvtxTrack.h
Referenced by PHGenFitTrackProjection::process_event().
virtual void SvtxTrack::set_cal_energy_3x3 (CAL_LAYER , float) inline virtual
Reimplemented in SvtxTrack_v3, and SvtxTrack_v2.
Definition at line 184 of file SvtxTrack.h.
View newest version in sPHENIX GitHub at line 184 of file SvtxTrack.h
Referenced by PHGenFitTrackProjection::process_event().
virtual void SvtxTrack::set_cal_energy_5x5 (CAL_LAYER , float) inline virtual
Reimplemented in SvtxTrack_v3, and SvtxTrack_v2.
Definition at line 186 of file SvtxTrack.h.
View newest version in sPHENIX GitHub at line 186 of file SvtxTrack.h
Referenced by PHGenFitTrackProjection::process_event().
virtual void SvtxTrack::set_charge (int) inline virtual
Reimplemented in SvtxTrack_v4, SvtxTrack_v3, SvtxTrack_v2, and SvtxTrack_v1.
Definition at line 89 of file SvtxTrack.h.
View newest version in sPHENIX GitHub at line 89 of file SvtxTrack.h
Referenced by KFParticle_DST::buildSvtxTrack(), PHActsToSvtxTracks::createSvtxTrack(), PHG4TrackFastSim::MakeSvtxTrack(), PHActsGSF::updateSvtxTrack(), PHCosmicsTrkFitter::updateSvtxTrack(), and PHActsTrkFitter::updateSvtxTrack().
virtual void SvtxTrack::set_chisq (float) inline virtual
Reimplemented in SvtxTrack_v4, SvtxTrack_v3, SvtxTrack_v2, and SvtxTrack_v1.
Definition at line 92 of file SvtxTrack.h.
View newest version in sPHENIX GitHub at line 92 of file SvtxTrack.h
Referenced by KFParticle_DST::buildSvtxTrack(), PHActsToSvtxTracks::createSvtxTrack(), PHG4TrackFastSim::MakeSvtxTrack(), PHActsGSF::updateSvtxTrack(), PHCosmicsTrkFitter::updateSvtxTrack(), and PHActsTrkFitter::updateSvtxTrack().
virtual void SvtxTrack::set_crossing (short int) inline virtual
Reimplemented in SvtxTrack_v4, and SvtxTrack_v3.
Definition at line 80 of file SvtxTrack.h.
View newest version in sPHENIX GitHub at line 80 of file SvtxTrack.h
virtual void SvtxTrack::set_dca (float) inline virtual
Reimplemented in SvtxTrack_v3, SvtxTrack_v2, and SvtxTrack_v1.
Definition at line 198 of file SvtxTrack.h.
View newest version in sPHENIX GitHub at line 198 of file SvtxTrack.h
Referenced by PHG4TrackFastSim::MakeSvtxTrack().
virtual void SvtxTrack::set_dca2d (float) inline virtual
Reimplemented in SvtxTrack_v3, SvtxTrack_v2, and SvtxTrack_v1.
Definition at line 202 of file SvtxTrack.h.
View newest version in sPHENIX GitHub at line 202 of file SvtxTrack.h
Referenced by PHG4TrackFastSim::MakeSvtxTrack().
virtual void SvtxTrack::set_dca2d_error (float) inline virtual
Reimplemented in SvtxTrack_v3, SvtxTrack_v2, and SvtxTrack_v1.
Definition at line 204 of file SvtxTrack.h.
View newest version in sPHENIX GitHub at line 204 of file SvtxTrack.h
Referenced by PHG4TrackFastSim::MakeSvtxTrack().
virtual void SvtxTrack::set_dca3d_xy (float) inline virtual
Reimplemented in SvtxTrack_v3, SvtxTrack_v2, and SvtxTrack_v1.
Definition at line 206 of file SvtxTrack.h.
View newest version in sPHENIX GitHub at line 206 of file SvtxTrack.h
Referenced by PHActsToSvtxTracks::createSvtxTrack().
virtual void SvtxTrack::set_dca3d_xy_error (float) inline virtual
Reimplemented in SvtxTrack_v3, SvtxTrack_v2, and SvtxTrack_v1.
Definition at line 208 of file SvtxTrack.h.
View newest version in sPHENIX GitHub at line 208 of file SvtxTrack.h
Referenced by PHActsToSvtxTracks::createSvtxTrack().
virtual void SvtxTrack::set_dca3d_z (float) inline virtual
Reimplemented in SvtxTrack_v3, SvtxTrack_v2, and SvtxTrack_v1.
Definition at line 210 of file SvtxTrack.h.
View newest version in sPHENIX GitHub at line 210 of file SvtxTrack.h
Referenced by PHActsToSvtxTracks::createSvtxTrack().
virtual void SvtxTrack::set_dca3d_z_error (float) inline virtual
Reimplemented in SvtxTrack_v3, SvtxTrack_v2, and SvtxTrack_v1.
Definition at line 212 of file SvtxTrack.h.
View newest version in sPHENIX GitHub at line 212 of file SvtxTrack.h
Referenced by PHActsToSvtxTracks::createSvtxTrack().
virtual void SvtxTrack::set_dca_error (float) inline virtual
Reimplemented in SvtxTrack_v3, SvtxTrack_v2, and SvtxTrack_v1.
Definition at line 200 of file SvtxTrack.h.
View newest version in sPHENIX GitHub at line 200 of file SvtxTrack.h
virtual void SvtxTrack::set_error (int , int , float) inline virtual
Reimplemented in SvtxTrack_v3, SvtxTrack_v2, SvtxTrack_v1, and SvtxTrack_v4.
Definition at line 127 of file SvtxTrack.h.
View newest version in sPHENIX GitHub at line 127 of file SvtxTrack.h
Referenced by KFParticle_DST::buildSvtxTrack(), PHActsToSvtxTracks::createSvtxTrack(), PHG4TrackFastSim::MakeSvtxTrack(), PHActsVertexPropagator::updateSvtxTrack(), PHActsGSF::updateSvtxTrack(), PHCosmicsTrkFitter::updateSvtxTrack(), and PHActsTrkFitter::updateSvtxTrack().
virtual void SvtxTrack::set_id (unsigned int) inline virtual
Reimplemented in SvtxTrack_v4, SvtxTrack_v2, SvtxTrack_v3, and SvtxTrack_v1.
Definition at line 71 of file SvtxTrack.h.
View newest version in sPHENIX GitHub at line 71 of file SvtxTrack.h
Referenced by KFParticle_DST::buildSvtxTrack(), SvtxTrackMap_v2::insert(), and SvtxTrackMap_v2::insertWithKey().
virtual void SvtxTrack::set_ndf (int) inline virtual
Reimplemented in SvtxTrack_v4, SvtxTrack_v3, SvtxTrack_v2, and SvtxTrack_v1.
Definition at line 95 of file SvtxTrack.h.
View newest version in sPHENIX GitHub at line 95 of file SvtxTrack.h
Referenced by KFParticle_DST::buildSvtxTrack(), PHActsToSvtxTracks::createSvtxTrack(), PHG4TrackFastSim::MakeSvtxTrack(), PHActsGSF::updateSvtxTrack(), PHCosmicsTrkFitter::updateSvtxTrack(), and PHActsTrkFitter::updateSvtxTrack().
virtual void SvtxTrack::set_num_measurements (int) inline virtual
Reimplemented in SvtxTrack_FastSim_v2, SvtxTrack_FastSim_v3, and SvtxTrack_FastSim.
Definition at line 222 of file SvtxTrack.h.
View newest version in sPHENIX GitHub at line 222 of file SvtxTrack.h
Referenced by PHG4TrackFastSim::MakeSvtxTrack().
virtual void SvtxTrack::set_positive_charge (bool) inline virtual
Reimplemented in SvtxTrack_v4, SvtxTrack_v3, SvtxTrack_v2, and SvtxTrack_v1.
Definition at line 86 of file SvtxTrack.h.
View newest version in sPHENIX GitHub at line 86 of file SvtxTrack.h
virtual void SvtxTrack::set_px (float) inline virtual
Reimplemented in SvtxTrack_v3, SvtxTrack_v2, SvtxTrack_v1, and SvtxTrack_v4.
Definition at line 111 of file SvtxTrack.h.
View newest version in sPHENIX GitHub at line 111 of file SvtxTrack.h
Referenced by KFParticle_DST::buildSvtxTrack(), PHActsToSvtxTracks::createSvtxTrack(), PHG4TrackFastSim::MakeSvtxTrack(), PHActsVertexPropagator::updateSvtxTrack(), PHActsGSF::updateSvtxTrack(), PHCosmicsTrkFitter::updateSvtxTrack(), and PHActsTrkFitter::updateSvtxTrack().
virtual void SvtxTrack::set_py (float) inline virtual
Reimplemented in SvtxTrack_v3, SvtxTrack_v2, SvtxTrack_v1, and SvtxTrack_v4.
Definition at line 114 of file SvtxTrack.h.
View newest version in sPHENIX GitHub at line 114 of file SvtxTrack.h
Referenced by KFParticle_DST::buildSvtxTrack(), PHActsToSvtxTracks::createSvtxTrack(), PHG4TrackFastSim::MakeSvtxTrack(), PHActsVertexPropagator::updateSvtxTrack(), PHActsGSF::updateSvtxTrack(), PHCosmicsTrkFitter::updateSvtxTrack(), and PHActsTrkFitter::updateSvtxTrack().
virtual void SvtxTrack::set_pz (float) inline virtual
Reimplemented in SvtxTrack_v3, SvtxTrack_v2, SvtxTrack_v1, and SvtxTrack_v4.
Definition at line 117 of file SvtxTrack.h.
View newest version in sPHENIX GitHub at line 117 of file SvtxTrack.h
Referenced by KFParticle_DST::buildSvtxTrack(), PHActsToSvtxTracks::createSvtxTrack(), PHG4TrackFastSim::MakeSvtxTrack(), PHActsVertexPropagator::updateSvtxTrack(), PHActsGSF::updateSvtxTrack(), PHCosmicsTrkFitter::updateSvtxTrack(), and PHActsTrkFitter::updateSvtxTrack().
virtual void SvtxTrack::set_silicon_seed (TrackSeed *) inline virtual
Reimplemented in SvtxTrack_v4.
Definition at line 77 of file SvtxTrack.h.
View newest version in sPHENIX GitHub at line 77 of file SvtxTrack.h
virtual void SvtxTrack::set_tpc_seed (TrackSeed *) inline virtual
Reimplemented in SvtxTrack_v4.
Definition at line 74 of file SvtxTrack.h.
View newest version in sPHENIX GitHub at line 74 of file SvtxTrack.h
virtual void SvtxTrack::set_truth_track_id (unsigned int) inline virtual
Reimplemented in SvtxTrack_FastSim_v2, SvtxTrack_FastSim_v3, and SvtxTrack_FastSim.
Definition at line 221 of file SvtxTrack.h.
View newest version in sPHENIX GitHub at line 221 of file SvtxTrack.h
Referenced by PHG4TrackFastSim::MakeSvtxTrack().
virtual void SvtxTrack::set_vertex_id (unsigned int) inline virtual
Reimplemented in SvtxTrack_v4, SvtxTrack_v3, SvtxTrack_v2, and SvtxTrack_v1.
Definition at line 83 of file SvtxTrack.h.
View newest version in sPHENIX GitHub at line 83 of file SvtxTrack.h
Referenced by PHSimpleVertexFinder::process_event().
virtual void SvtxTrack::set_x (float) inline virtual
Reimplemented in SvtxTrack_v3, SvtxTrack_v2, SvtxTrack_v1, and SvtxTrack_v4.
Definition at line 100 of file SvtxTrack.h.
View newest version in sPHENIX GitHub at line 100 of file SvtxTrack.h
Referenced by KFParticle_DST::buildSvtxTrack(), PHActsToSvtxTracks::createSvtxTrack(), PHG4TrackFastSim::MakeSvtxTrack(), PHActsVertexPropagator::updateSvtxTrack(), PHActsGSF::updateSvtxTrack(), PHCosmicsTrkFitter::updateSvtxTrack(), and PHActsTrkFitter::updateSvtxTrack().
virtual void SvtxTrack::set_y (float) inline virtual
Reimplemented in SvtxTrack_v3, SvtxTrack_v2, SvtxTrack_v1, and SvtxTrack_v4.
Definition at line 103 of file SvtxTrack.h.
View newest version in sPHENIX GitHub at line 103 of file SvtxTrack.h
Referenced by KFParticle_DST::buildSvtxTrack(), PHActsToSvtxTracks::createSvtxTrack(), PHG4TrackFastSim::MakeSvtxTrack(), PHActsVertexPropagator::updateSvtxTrack(), PHActsGSF::updateSvtxTrack(), PHCosmicsTrkFitter::updateSvtxTrack(), and PHActsTrkFitter::updateSvtxTrack().
virtual void SvtxTrack::set_z (float) inline virtual
Reimplemented in SvtxTrack_v3, SvtxTrack_v2, SvtxTrack_v1, and SvtxTrack_v4.
Definition at line 106 of file SvtxTrack.h.
View newest version in sPHENIX GitHub at line 106 of file SvtxTrack.h
Referenced by KFParticle_DST::buildSvtxTrack(), PHActsToSvtxTracks::createSvtxTrack(), PHG4TrackFastSim::MakeSvtxTrack(), PHActsVertexPropagator::updateSvtxTrack(), PHActsGSF::updateSvtxTrack(), PHCosmicsTrkFitter::updateSvtxTrack(), and PHActsTrkFitter::updateSvtxTrack().
virtual size_t SvtxTrack::size_cluster_keys () const inline virtual
Reimplemented in SvtxTrack_v3, SvtxTrack_v2, and SvtxTrack_v1.
Definition at line 157 of file SvtxTrack.h.
View newest version in sPHENIX GitHub at line 157 of file SvtxTrack.h
Referenced by BJetModule::process_event(), TPCGemGainCalb::process_event(), and MakeMilleFiles::process_event().
virtual size_t SvtxTrack::size_clusters () const inline virtual
Reimplemented in SvtxTrack_v3, SvtxTrack_v2, and SvtxTrack_v1.
Definition at line 169 of file SvtxTrack.h.
View newest version in sPHENIX GitHub at line 169 of file SvtxTrack.h
Referenced by EMCalCalib::eval_photon(), EMCalAna::eval_trk(), AnaSvtxTracksForGenFit::fill_tree(), GenFitTrackProp::fill_tree(), psTOFTimezeroEval::fillOutputNtuples(), and SvtxEvaluatorHaiwang::fillOutputNtuples().
virtual size_t SvtxTrack::size_g4hit_id () const inline virtual
Reimplemented in SvtxTrack_FastSim_v2, SvtxTrack_FastSim_v3, and SvtxTrack_FastSim_v1.
Definition at line 231 of file SvtxTrack.h.
View newest version in sPHENIX GitHub at line 231 of file SvtxTrack.h
virtual size_t SvtxTrack::size_states () const inline virtual
Reimplemented in SvtxTrack_v3, SvtxTrack_v2, SvtxTrack_v1, and SvtxTrack_v4.
Definition at line 133 of file SvtxTrack.h.
View newest version in sPHENIX GitHub at line 133 of file SvtxTrack.h
Referenced by EMCalAna::eval_trk_proj(), and QAG4SimulationCalorimeterSum::eval_trk_proj().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/trackbase_historic/SvtxTrack.h
coresoftware/blob/master/offline/packages/trackbase_historic/SvtxTrack.cc