Analysis Software: acts/blob/sPHENIX/Tests/UnitTests/Core/Detector/VolumeStructureBuilderTests.cpp File Reference
VolumeStructureBuilderTests.cpp File Reference
#include <boost/test/unit_test.hpp>
#include "Acts/Definitions/Algebra.hpp"
#include "Acts/Detector/VolumeStructureBuilder.hpp"
#include "Acts/Geometry/VolumeBounds.hpp"
#include <memory>
#include <vector>
Functions
BOOST_AUTO_TEST_CASE (VolumeStructureBuilderMisconfigured)
BOOST_AUTO_TEST_CASE (VolumeStructureBuilderCone)
BOOST_AUTO_TEST_CASE (VolumeStructureBuilderCuboid)
BOOST_AUTO_TEST_CASE (VolumeStructureBuilderCutoutCylinder)
BOOST_AUTO_TEST_CASE (VolumeStructureBuilderCylinder)
BOOST_AUTO_TEST_CASE (VolumeStructureBuilderGenericCuboid)
BOOST_AUTO_TEST_CASE (VolumeStructureBuilderTrapezoid)
Variables
GeometryContext tContext
Function Documentation
BOOST_AUTO_TEST_CASE (VolumeStructureBuilderMisconfigured)
Definition at line 26 of file VolumeStructureBuilderTests.cpp.
View newest version in sPHENIX GitHub at line 26 of file VolumeStructureBuilderTests.cpp
References Acts::Experimental::VolumeStructureBuilder::Config::boundValues, Acts::getDefaultLogger(), and Acts::Logging::VERBOSE.
BOOST_AUTO_TEST_CASE (VolumeStructureBuilderCone)
Definition at line 42 of file VolumeStructureBuilderTests.cpp.
View newest version in sPHENIX GitHub at line 42 of file VolumeStructureBuilderTests.cpp
References Acts::Experimental::VolumeStructureBuilder::Config::boundsType, Acts::Experimental::VolumeStructureBuilder::Config::boundValues, Acts::Experimental::VolumeStructureBuilder::construct(), Acts::Experimental::VolumeStructureBuilder::Config::extent, Acts::getDefaultLogger(), tContext, physmon_ckf_tracking::u, and Acts::Logging::VERBOSE.
BOOST_AUTO_TEST_CASE (VolumeStructureBuilderCuboid)
Definition at line 88 of file VolumeStructureBuilderTests.cpp.
View newest version in sPHENIX GitHub at line 88 of file VolumeStructureBuilderTests.cpp
References Acts::binX, Acts::binY, Acts::binZ, Acts::Experimental::VolumeStructureBuilder::Config::boundsType, Acts::Experimental::VolumeStructureBuilder::Config::boundValues, Acts::Experimental::VolumeStructureBuilder::construct(), Acts::Experimental::VolumeStructureBuilder::Config::extent, Acts::getDefaultLogger(), Acts::Extent::set(), tContext, physmon_ckf_tracking::u, and Acts::Logging::VERBOSE.
BOOST_AUTO_TEST_CASE (VolumeStructureBuilderCutoutCylinder)
Definition at line 157 of file VolumeStructureBuilderTests.cpp.
View newest version in sPHENIX GitHub at line 157 of file VolumeStructureBuilderTests.cpp
References Acts::Experimental::VolumeStructureBuilder::Config::boundsType, Acts::Experimental::VolumeStructureBuilder::Config::boundValues, Acts::Experimental::VolumeStructureBuilder::construct(), Acts::Experimental::VolumeStructureBuilder::Config::extent, Acts::getDefaultLogger(), tContext, physmon_ckf_tracking::u, and Acts::Logging::VERBOSE.
BOOST_AUTO_TEST_CASE (VolumeStructureBuilderCylinder)
Definition at line 203 of file VolumeStructureBuilderTests.cpp.
View newest version in sPHENIX GitHub at line 203 of file VolumeStructureBuilderTests.cpp
References Acts::binR, Acts::binZ, Acts::Experimental::VolumeStructureBuilder::Config::boundsType, Acts::Experimental::VolumeStructureBuilder::Config::boundValues, Acts::Experimental::VolumeStructureBuilder::construct(), Acts::Experimental::VolumeStructureBuilder::Config::extent, Acts::getDefaultLogger(), Acts::Extent::set(), tContext, physmon_ckf_tracking::u, and Acts::Logging::VERBOSE.
BOOST_AUTO_TEST_CASE (VolumeStructureBuilderGenericCuboid)
Definition at line 275 of file VolumeStructureBuilderTests.cpp.
View newest version in sPHENIX GitHub at line 275 of file VolumeStructureBuilderTests.cpp
References Acts::Experimental::VolumeStructureBuilder::Config::boundsType, Acts::Experimental::VolumeStructureBuilder::Config::boundValues, Acts::Experimental::VolumeStructureBuilder::construct(), Acts::getDefaultLogger(), tContext, physmon_ckf_tracking::u, and Acts::Logging::VERBOSE.
BOOST_AUTO_TEST_CASE (VolumeStructureBuilderTrapezoid)
Definition at line 315 of file VolumeStructureBuilderTests.cpp.
View newest version in sPHENIX GitHub at line 315 of file VolumeStructureBuilderTests.cpp
References Acts::Experimental::VolumeStructureBuilder::Config::boundsType, Acts::Experimental::VolumeStructureBuilder::Config::boundValues, Acts::Experimental::VolumeStructureBuilder::construct(), Acts::getDefaultLogger(), tContext, physmon_ckf_tracking::u, and Acts::Logging::VERBOSE.
Variable Documentation
GeometryContext tContext
Definition at line 21 of file VolumeStructureBuilderTests.cpp.
View newest version in sPHENIX GitHub at line 21 of file VolumeStructureBuilderTests.cpp