Analysis Software: Fun4AllMonitoring Class Reference
Fun4AllMonitoring Class Reference
#include <coresoftware/blob/master/offline/framework/fun4all/Fun4AllMonitoring.h>
Public Member Functions
~Fun4AllMonitoring () override=default
void Snapshot (const std::string &what="AfterProcessEvent")
void PrintsMaps () const
void Get_Memory ()
void OutFileName (const std::string &fname)
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Print (const std::string &what="ALL") const
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Static Public Member Functions
static Fun4AllMonitoring * instance ()
Private Member Functions
Fun4AllMonitoring ()
Private Attributes
uint64_t mEvent = 0
uint64_t mHeapPss = 0
uint64_t mMMapPSS = 0
uint64_t mOtherPss = 0
std::string mOutFileName
Static Private Attributes
static Fun4AllMonitoring * mInstance = nullptr
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = std::numeric_limits<int>::max() - 10
}
Protected Member Functions inherited from Fun4AllBase
Fun4AllBase (const std::string &name="NONAME")
Detailed Description
Definition at line 11 of file Fun4AllMonitoring.h.
View newest version in sPHENIX GitHub at line 11 of file Fun4AllMonitoring.h
Constructor & Destructor Documentation
Fun4AllMonitoring::~Fun4AllMonitoring () override default
Fun4AllMonitoring::Fun4AllMonitoring () private
Definition at line 20 of file Fun4AllMonitoring.cc.
View newest version in sPHENIX GitHub at line 20 of file Fun4AllMonitoring.cc
Referenced by instance().
Member Function Documentation
void Fun4AllMonitoring::Get_Memory ()
Definition at line 48 of file Fun4AllMonitoring.cc.
View newest version in sPHENIX GitHub at line 48 of file Fun4AllMonitoring.cc
References i, mHeapPss, mMMapPSS, mOtherPss, and trim().
Referenced by Snapshot().
static Fun4AllMonitoring* Fun4AllMonitoring::instance () inline static
Definition at line 14 of file Fun4AllMonitoring.h.
View newest version in sPHENIX GitHub at line 14 of file Fun4AllMonitoring.h
References Fun4AllMonitoring(), and mInstance.
Referenced by Fun4AllServer::InitAll(), and Fun4AllServer::process_event().
void Fun4AllMonitoring::OutFileName (const std::string & fname)
Definition at line 146 of file Fun4AllMonitoring.cc.
View newest version in sPHENIX GitHub at line 146 of file Fun4AllMonitoring.cc
References INTTVtxZ::fname, and mOutFileName.
void Fun4AllMonitoring::PrintsMaps () const
Definition at line 108 of file Fun4AllMonitoring.cc.
View newest version in sPHENIX GitHub at line 108 of file Fun4AllMonitoring.cc
References geant4_parallel::ends, INTTVtxZ::fname, add_histos::outfile, and to_string().
void Fun4AllMonitoring::Snapshot (const std::string & what = "AfterProcessEvent")
Definition at line 25 of file Fun4AllMonitoring.cc.
View newest version in sPHENIX GitHub at line 25 of file Fun4AllMonitoring.cc
References release::app, Get_Memory(), mEvent, mHeapPss, mMMapPSS, mOtherPss, mOutFileName, and add_histos::outfile.
Referenced by Fun4AllServer::InitAll(), and Fun4AllServer::process_event().
Member Data Documentation
uint64_t Fun4AllMonitoring::mEvent = 0 private
Definition at line 31 of file Fun4AllMonitoring.h.
View newest version in sPHENIX GitHub at line 31 of file Fun4AllMonitoring.h
Referenced by Snapshot().
uint64_t Fun4AllMonitoring::mHeapPss = 0 private
Definition at line 32 of file Fun4AllMonitoring.h.
View newest version in sPHENIX GitHub at line 32 of file Fun4AllMonitoring.h
Referenced by Get_Memory(), and Snapshot().
Fun4AllMonitoring * Fun4AllMonitoring::mInstance = nullptr static private
Definition at line 30 of file Fun4AllMonitoring.h.
View newest version in sPHENIX GitHub at line 30 of file Fun4AllMonitoring.h
Referenced by instance().
uint64_t Fun4AllMonitoring::mMMapPSS = 0 private
Definition at line 33 of file Fun4AllMonitoring.h.
View newest version in sPHENIX GitHub at line 33 of file Fun4AllMonitoring.h
Referenced by Get_Memory(), and Snapshot().
uint64_t Fun4AllMonitoring::mOtherPss = 0 private
Definition at line 34 of file Fun4AllMonitoring.h.
View newest version in sPHENIX GitHub at line 34 of file Fun4AllMonitoring.h
Referenced by Get_Memory(), and Snapshot().
std::string Fun4AllMonitoring::mOutFileName private
Definition at line 35 of file Fun4AllMonitoring.h.
View newest version in sPHENIX GitHub at line 35 of file Fun4AllMonitoring.h
Referenced by OutFileName(), and Snapshot().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/framework/fun4all/Fun4AllMonitoring.h
coresoftware/blob/master/offline/framework/fun4all/Fun4AllMonitoring.cc