Analysis Software: Acts::Test::MeasurementCreator Struct Reference
Acts::Test::MeasurementCreator Struct Reference
This struct creates FittableMeasurements on the detector surfaces, according to the given smearing xxparameters.
Classes
struct this_result
Public Types
using result_type = std::vector< FittableMeasurement< SourceLink >>
using result_type = this_result
Public Member Functions
MeasurementCreator ()=default
Constructor.
template<typename propagator_state_t , typename stepper_t >
void operator() (propagator_state_t &state, const stepper_t &stepper, result_type &result) const
Operater that is callable by an ActionList. The function collects the surfaces.
MeasurementCreator ()=default
Constructor.
template<typename propagator_state_t , typename stepper_t >
void operator() (propagator_state_t &state, const stepper_t &stepper, result_type &result) const
Operater that is callable by an ActionList. The function collects the surfaces.
Public Attributes
DetectorResolution detectorResolution
The detector resolution.
Detailed Description
This struct creates FittableMeasurements on the detector surfaces, according to the given smearing xxparameters.
Definition at line 100 of file CombinatorialKalmanFilterTests.cpp.
View newest version in sPHENIX GitHub at line 100 of file CombinatorialKalmanFilterTests.cpp
Member Typedef Documentation
using Acts::Test::MeasurementCreator::result_type = this_result
Definition at line 92 of file KalmanFitterTests.cpp.
View newest version in sPHENIX GitHub at line 92 of file KalmanFitterTests.cpp
using Acts::Test::MeasurementCreator::result_type = std::vector<FittableMeasurement<SourceLink>>
Definition at line 107 of file CombinatorialKalmanFilterTests.cpp.
View newest version in sPHENIX GitHub at line 107 of file CombinatorialKalmanFilterTests.cpp
Constructor & Destructor Documentation
Acts::Test::MeasurementCreator::MeasurementCreator () default
Constructor.
Acts::Test::MeasurementCreator::MeasurementCreator () default
Constructor.
Member Function Documentation
template<typename propagator_state_t , typename stepper_t > void Acts::Test::MeasurementCreator::operator() (propagator_state_t & state, const stepper_t & stepper, result_type & result) const inline
Operater that is callable by an ActionList. The function collects the surfaces.
Template Parameters
propagator_state_t Type of the propagator state
stepper_t Type of the stepper
Parameters
[in] state State of the propagator
[out] result Vector of matching surfaces
Definition at line 102 of file KalmanFitterTests.cpp.
View newest version in sPHENIX GitHub at line 102 of file KalmanFitterTests.cpp
References Acts::Test::cov1D, Acts::Test::cov2D, dx, dy, Acts::eBoundLoc0, Acts::eBoundLoc1, Acts::Test::gauss(), Fatras::Test::generator, testing::internal::move(), and value.
template<typename propagator_state_t , typename stepper_t > void Acts::Test::MeasurementCreator::operator() (propagator_state_t & state, const stepper_t & stepper, result_type & result) const inline
Operater that is callable by an ActionList. The function collects the surfaces.
Template Parameters
propagator_state_t Type of the propagator state
stepper_t Type of the stepper
Parameters
[in] state State of the propagator
[out] result Vector of matching surfaces
Definition at line 117 of file CombinatorialKalmanFilterTests.cpp.
View newest version in sPHENIX GitHub at line 117 of file CombinatorialKalmanFilterTests.cpp
References Acts::Test::cov1D, Acts::Test::cov2D, dx, dy, Acts::eBoundLoc0, Acts::eBoundLoc1, Acts::Test::gauss(), Fatras::Test::generator, and testing::internal::move().
Member Data Documentation
DetectorResolution Acts::Test::MeasurementCreator::detectorResolution
The detector resolution.
Definition at line 105 of file CombinatorialKalmanFilterTests.cpp.
View newest version in sPHENIX GitHub at line 105 of file CombinatorialKalmanFilterTests.cpp
Referenced by Acts::Test::BOOST_AUTO_TEST_CASE().
The documentation for this struct was generated from the following files:
acts/blob/sPHENIX/Tests/UnitTests/Core/TrackFinding/CombinatorialKalmanFilterTests.cpp
acts/blob/sPHENIX/Tests/UnitTests/Core/TrackFitting/KalmanFitterTests.cpp