Analysis Software: tinyxml2::XMLDeclaration Class Reference
tinyxml2::XMLDeclaration Class Reference
#include <JETSCAPE/blob/main/external_packages/tinyxml2.h>
Public Member Functions
virtual XMLDeclaration * ToDeclaration ()
Safely cast to a Declaration, or null.
virtual const XMLDeclaration * ToDeclaration () const
virtual bool Accept (XMLVisitor *visitor) const
virtual XMLNode * ShallowClone (XMLDocument *document) const
virtual bool ShallowEqual (const XMLNode *compare) const
Public Member Functions inherited from tinyxml2::XMLNode
const XMLDocument * GetDocument () const
Get the XMLDocument that owns this XMLNode.
XMLDocument * GetDocument ()
Get the XMLDocument that owns this XMLNode.
virtual XMLElement * ToElement ()
Safely cast to an Element, or null.
virtual XMLText * ToText ()
Safely cast to Text, or null.
virtual XMLComment * ToComment ()
Safely cast to a Comment, or null.
virtual XMLDocument * ToDocument ()
Safely cast to a Document, or null.
virtual XMLUnknown * ToUnknown ()
Safely cast to an Unknown, or null.
virtual const XMLElement * ToElement () const
virtual const XMLText * ToText () const
virtual const XMLComment * ToComment () const
virtual const XMLDocument * ToDocument () const
virtual const XMLUnknown * ToUnknown () const
const char * Value () const
void SetValue (const char *val, bool staticMem=false)
const XMLNode * Parent () const
Get the parent of this node on the DOM.
XMLNode * Parent ()
bool NoChildren () const
Returns true if this node has no children.
const XMLNode * FirstChild () const
Get the first child node, or null if none exists.
XMLNode * FirstChild ()
const XMLElement * FirstChildElement (const char *name=0) const
XMLElement * FirstChildElement (const char *name=0)
const XMLNode * LastChild () const
Get the last child node, or null if none exists.
XMLNode * LastChild ()
const XMLElement * LastChildElement (const char *name=0) const
XMLElement * LastChildElement (const char *name=0)
const XMLNode * PreviousSibling () const
Get the previous (left) sibling node of this node.
XMLNode * PreviousSibling ()
const XMLElement * PreviousSiblingElement (const char *name=0) const
Get the previous (left) sibling element of this node, with an optionally supplied name.
XMLElement * PreviousSiblingElement (const char *name=0)
const XMLNode * NextSibling () const
Get the next (right) sibling node of this node.
XMLNode * NextSibling ()
const XMLElement * NextSiblingElement (const char *name=0) const
Get the next (right) sibling element of this node, with an optionally supplied name.
XMLElement * NextSiblingElement (const char *name=0)
XMLNode * InsertEndChild (XMLNode *addThis)
XMLNode * LinkEndChild (XMLNode *addThis)
XMLNode * InsertFirstChild (XMLNode *addThis)
XMLNode * InsertAfterChild (XMLNode *afterThis, XMLNode *addThis)
void DeleteChildren ()
void DeleteChild (XMLNode *node)
void SetUserData (void *userData)
void * GetUserData () const
Protected Member Functions
XMLDeclaration (XMLDocument *doc)
virtual ~XMLDeclaration ()
char * ParseDeep (char *, StrPair *endTag)
Protected Member Functions inherited from tinyxml2::XMLNode
XMLNode (XMLDocument *)
virtual ~XMLNode ()
Private Member Functions
XMLDeclaration (const XMLDeclaration &)
XMLDeclaration & operator= (const XMLDeclaration &)
Friends
class XMLDocument
Additional Inherited Members
Protected Attributes inherited from tinyxml2::XMLNode
XMLDocument * _document
XMLNode * _parent
StrPair _value
XMLNode * _firstChild
XMLNode * _lastChild
XMLNode * _prev
XMLNode * _next
void * _userData
Detailed Description
In correct XML the declaration is the first entry in the file.
        <?xml version="1.0" standalone="yes"?>
TinyXML-2 will happily read or write files without a declaration, however.
The text of the declaration isn't interpreted. It is parsed and written as a string.
Definition at line 1009 of file tinyxml2.h.
View newest version in sPHENIX GitHub at line 1009 of file tinyxml2.h
Constructor & Destructor Documentation
tinyxml2::XMLDeclaration::XMLDeclaration (XMLDocument * doc) protected
Definition at line 1184 of file tinyxml2.cc.
View newest version in sPHENIX GitHub at line 1184 of file tinyxml2.cc
tinyxml2::XMLDeclaration::~XMLDeclaration () protected virtual
Definition at line 1189 of file tinyxml2.cc.
View newest version in sPHENIX GitHub at line 1189 of file tinyxml2.cc
tinyxml2::XMLDeclaration::XMLDeclaration (const XMLDeclaration &) private
Member Function Documentation
bool tinyxml2::XMLDeclaration::Accept (XMLVisitor * visitor) const virtual
Accept a hierarchical visit of the nodes in the TinyXML-2 DOM. Every node in the XML tree will be conditionally visited and the host will be called back via the XMLVisitor interface.
This is essentially a SAX interface for TinyXML-2. (Note however it doesn't re-parse the XML for the callbacks, so the performance of TinyXML-2 is unchanged by using this interface versus any other.)
The interface has been based on ideas from:
http://www.saxproject.org/
http://c2.com/cgi/wiki?HierarchicalVisitorPattern
Which are both good references for "visiting".
An example of using Accept():
XMLPrinter printer;
tinyxmlDoc.Accept(&printer);
const char* xmlcstr = printer.CStr();
Implements tinyxml2::XMLNode.
Definition at line 1226 of file tinyxml2.cc.
View newest version in sPHENIX GitHub at line 1226 of file tinyxml2.cc
References TIXMLASSERT, and tinyxml2::XMLVisitor::Visit().
XMLDeclaration& tinyxml2::XMLDeclaration::operator= (const XMLDeclaration &) private
char * tinyxml2::XMLDeclaration::ParseDeep (char * p, StrPair * endTag) protected virtual
Reimplemented from tinyxml2::XMLNode.
Definition at line 1195 of file tinyxml2.cc.
View newest version in sPHENIX GitHub at line 1195 of file tinyxml2.cc
References tinyxml2::XMLNode::_document, tinyxml2::XMLNode::_value, tinyxml2::StrPair::NEEDS_NEWLINE_NORMALIZATION, merge_hashes::p, tinyxml2::StrPair::ParseText(), tinyxml2::XMLDocument::SetError(), start, and tinyxml2::XML_ERROR_PARSING_DECLARATION.
XMLNode * tinyxml2::XMLDeclaration::ShallowClone (XMLDocument * document) const virtual
Make a copy of this node, but not its children. You may pass in a Document pointer that will be the owner of the new Node. If the 'document' is null, then the node returned will be allocated from the current Document. (this->GetDocument())
Note: if called on a XMLDocument, this will return null.
Implements tinyxml2::XMLNode.
Definition at line 1207 of file tinyxml2.cc.
View newest version in sPHENIX GitHub at line 1207 of file tinyxml2.cc
References tinyxml2::XMLNode::_document, tinyxml2::XMLDocument::NewDeclaration(), and tinyxml2::XMLNode::Value().
bool tinyxml2::XMLDeclaration::ShallowEqual (const XMLNode * compare) const virtual
Test if 2 nodes are the same, but don't test children. The 2 nodes do not need to be in the same Document.
Note: if called on a XMLDocument, this will return false.
Implements tinyxml2::XMLNode.
Definition at line 1217 of file tinyxml2.cc.
View newest version in sPHENIX GitHub at line 1217 of file tinyxml2.cc
References tinyxml2::XMLUtil::StringEqual(), TIXMLASSERT, tinyxml2::XMLNode::ToDeclaration(), and tinyxml2::XMLNode::Value().
virtual XMLDeclaration* tinyxml2::XMLDeclaration::ToDeclaration () inline virtual
Safely cast to a Declaration, or null.
Reimplemented from tinyxml2::XMLNode.
Definition at line 1013 of file tinyxml2.h.
View newest version in sPHENIX GitHub at line 1013 of file tinyxml2.h
virtual const XMLDeclaration* tinyxml2::XMLDeclaration::ToDeclaration () const inline virtual
Reimplemented from tinyxml2::XMLNode.
Definition at line 1016 of file tinyxml2.h.
View newest version in sPHENIX GitHub at line 1016 of file tinyxml2.h
Friends And Related Function Documentation
friend class XMLDocument friend
Definition at line 1011 of file tinyxml2.h.
View newest version in sPHENIX GitHub at line 1011 of file tinyxml2.h
The documentation for this class was generated from the following files:
JETSCAPE/blob/main/external_packages/tinyxml2.h
JETSCAPE/blob/main/external_packages/tinyxml2.cc