Analysis Software: ClosestPair2DBase Class Reference
ClosestPair2DBase Class Reference abstract
Public Member Functions
virtual void closest_pair (unsigned int &ID1, unsigned int &ID2, double &distance2) const =0
virtual void remove (unsigned int ID)=0
virtual unsigned int insert (const Coord2D &position)=0
virtual unsigned int replace (unsigned int ID1, unsigned int ID2, const Coord2D &position)
virtual void replace_many (const std::vector< unsigned int > &IDs_to_remove, const std::vector< Coord2D > &new_positions, std::vector< unsigned int > &new_IDs)
virtual unsigned int size ()=0
virtual ~ClosestPair2DBase ()
Detailed Description
Definition at line 694 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 694 of file fjcore.cc
Constructor & Destructor Documentation
virtual ClosestPair2DBase::~ClosestPair2DBase () inline virtual
Definition at line 717 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 717 of file fjcore.cc
Member Function Documentation
virtual void ClosestPair2DBase::closest_pair (unsigned int & ID1, unsigned int & ID2, double & distance2) const pure virtual
Implemented in ClosestPair2D.
virtual unsigned int ClosestPair2DBase::insert (const Coord2D & position) pure virtual
Implemented in ClosestPair2D.
Referenced by replace(), and replace_many().
virtual void ClosestPair2DBase::remove (unsigned int ID) pure virtual
Implemented in ClosestPair2D.
virtual unsigned int ClosestPair2DBase::replace (unsigned int ID1, unsigned int ID2, const Coord2D & position) inline virtual
Reimplemented in ClosestPair2D.
Definition at line 700 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 700 of file fjcore.cc
References insert().
virtual void ClosestPair2DBase::replace_many (const std::vector< unsigned int > & IDs_to_remove, const std::vector< Coord2D > & new_positions, std::vector< unsigned int > & new_IDs) inline virtual
Reimplemented in ClosestPair2D.
Definition at line 707 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 707 of file fjcore.cc
References i, and insert().
virtual unsigned int ClosestPair2DBase::size () pure virtual
Implemented in ClosestPair2D.
The documentation for this class was generated from the following file:
JETSCAPE/blob/main/external_packages/fjcore.cc