Analysis Software: Acts::Test::MeasurementsCreator Struct Reference
Acts::Test::MeasurementsCreator Struct Reference
Propagator action to create smeared measurements.
#include <acts/blob/sPHENIX/Tests/CommonHelpers/Acts/Tests/CommonHelpers/MeasurementsCreator.hpp>
Public Types
using result_type = Measurements
Public Member Functions
template<typename propagator_state_t , typename stepper_t , typename navigator_t >
void operator() (propagator_state_t &state, const stepper_t &stepper, const navigator_t &navigator, result_type &result, const Logger &logger) const
Operator that is callable by an ActionList. The function collects the surfaces.
Public Attributes
MeasurementResolutionMap resolutions
std::default_random_engine * rng = nullptr
size_t sourceId = 0
double distanceOutlier = 10 * Acts::UnitConstants::mm
Detailed Description
Propagator action to create smeared measurements.
Definition at line 55 of file MeasurementsCreator.hpp.
View newest version in sPHENIX GitHub at line 55 of file MeasurementsCreator.hpp
Member Typedef Documentation
using Acts::Test::MeasurementsCreator::result_type = Measurements
Definition at line 56 of file MeasurementsCreator.hpp.
View newest version in sPHENIX GitHub at line 56 of file MeasurementsCreator.hpp
Member Function Documentation
template<typename propagator_state_t , typename stepper_t , typename navigator_t > void Acts::Test::MeasurementsCreator::operator() (propagator_state_t & state, const stepper_t & stepper, const navigator_t & navigator, result_type & result, const Logger & logger) const inline
Operator that is callable by an ActionList. The function collects the surfaces.
Template Parameters
propagator_state_t Type of the propagator state
stepper_t Type of the stepper
navigator_t Type of the navigator
Parameters
[out] result Vector of matching surfaces
[in] state State of the propagator
Definition at line 75 of file MeasurementsCreator.hpp.
View newest version in sPHENIX GitHub at line 75 of file MeasurementsCreator.hpp
References Acts::ACTS_VERBOSE(), Acts::Test::cov, distanceOutlier, Acts::eBoundLoc0, Acts::eBoundLoc1, Acts::eBoundPhi, Acts::eBoundQOverP, Acts::eBoundTheta, Acts::eBoundTime, Acts::eFreeQOverP, Acts::eFreeTime, Acts::GeometryHierarchyMap< value_t >::end(), Acts::GeometryHierarchyMap< value_t >::find(), loc, testing::internal::move(), out, Acts::Test::Measurements::outlierSourceLinks, Dataset::parameters, Acts::VectorHelpers::phi(), resolutions, rng, sourceId, Acts::Test::Measurements::sourceLinks, writeMapConfig::surface, Acts::VectorHelpers::theta(), Acts::Test::Measurements::truthParameters, and value.
Member Data Documentation
double Acts::Test::MeasurementsCreator::distanceOutlier = 10 * Acts::UnitConstants::mm
Definition at line 62 of file MeasurementsCreator.hpp.
View newest version in sPHENIX GitHub at line 62 of file MeasurementsCreator.hpp
Referenced by operator()().
MeasurementResolutionMap Acts::Test::MeasurementsCreator::resolutions
Definition at line 58 of file MeasurementsCreator.hpp.
View newest version in sPHENIX GitHub at line 58 of file MeasurementsCreator.hpp
Referenced by Acts::Test::createMeasurements(), and operator()().
std::default_random_engine* Acts::Test::MeasurementsCreator::rng = nullptr
Definition at line 59 of file MeasurementsCreator.hpp.
View newest version in sPHENIX GitHub at line 59 of file MeasurementsCreator.hpp
Referenced by Acts::Test::createMeasurements(), and operator()().
size_t Acts::Test::MeasurementsCreator::sourceId = 0
Definition at line 60 of file MeasurementsCreator.hpp.
View newest version in sPHENIX GitHub at line 60 of file MeasurementsCreator.hpp
Referenced by Acts::Test::createMeasurements(), and operator()().
The documentation for this struct was generated from the following file:
acts/blob/sPHENIX/Tests/CommonHelpers/Acts/Tests/CommonHelpers/MeasurementsCreator.hpp