Analysis Software: analysis/blob/master/EICAnalysis/macros/leptoquarks_analysis/tracks.C File Reference
tracks.C File Reference
Functions
tracks ()
Function Documentation
tracks ()
Definition at line 1 of file tracks.C.
View newest version in sPHENIX GitHub at line 1 of file tracks.C
References c2.
Referenced by Acts::AdaptiveMultiVertexFinder< vfitter_t, sfinder_t >::addCompatibleTracksToVertex(), KFParticlePVReconstructor::AddPV(), SvtxTrackEval::all_tracks_from(), TrkrNtuplizer::all_tracks_from(), SvtxTrackEval::best_track_from(), TrkrNtuplizer::best_track_from(), SvtxVertexEval::best_vertex_from(), Acts::Test::BOOST_AUTO_TEST_CASE(), BOOST_AUTO_TEST_CASE(), CheckDeltaPtWithBoundaryMasks(), RecoConversionEval::correctSecondaryVertex(), Conversion::correctSecondaryVertex(), SvtxTrackEval::create_cache_track_from_cluster(), TrkrNtuplizer::create_cache_track_from_cluster(), ActsExamples::SeedsToPrototracks::execute(), ActsExamples::TracksToTrajectories::execute(), ActsExamples::TrajectoriesToPrototracks::execute(), ActsExamples::RefittingAlgorithm::execute(), ActsExamples::AmbiguityResolutionMLAlgorithm::execute(), ActsExamples::TruthTrackFinder::execute(), ActsExamples::AmbiguityResolutionMLDBScanAlgorithm::execute(), ActsExamples::GreedyAmbiguityResolutionAlgorithm::execute(), ActsExamples::TrackFittingAlgorithm::execute(), ActsExamples::TruthSeedingAlgorithm::execute(), ActsExamples::TrackFindingFromPrototrackAlgorithm::execute(), ActsExamples::TrackFindingAlgorithm::execute(), Acts::CombinatorialKalmanFilter< propagator_t, traj_t >::findTracks(), PHActsGSF::fitTrack(), PHCosmicsTrkFitter::fitTrack(), PHActsTrkFitter::fitTrack(), ActsTrackFittingAlgorithm::fitTrack(), PHActsInitialVertexFinder::getTrackPointers(), PHCosmicsTrkFitter::loopTracks(), PHActsTrkFitter::loopTracks(), main(), HFTrigger::makeAllTracks(), HFTriggerMVA::makeAllTracks(), sPHENIXTrackFitterFunctionImpl::operator()(), Plot_FastTrack_Efficiency(), psTOFTimezeroEval::printOutputInfo(), SvtxEvaluatorHaiwang::printOutputInfo(), SvtxEvaluator::printOutputInfo(), PHActsGSF::process_event(), ActsExamples::EDM4hepTrackReader::read(), Acts::Test::readTracksAndVertexCSV(), KFParticleTopoReconstructor::ReconstructPrimVertex(), Acts::Vertex< input_track_t >::setTracksAtVertex(), FitterTester::test_GlobalCovariance(), FitterTester::test_ZeroFieldNoSurfaceForward(), FitterTester::test_ZeroFieldShuffled(), FitterTester::test_ZeroFieldWithHole(), FitterTester::test_ZeroFieldWithOutliers(), FitterTester::test_ZeroFieldWithReverseFiltering(), FitterTester::test_ZeroFieldWithSurfaceAtExit(), FitterTester::test_ZeroFieldWithSurfaceBackward(), FitterTester::test_ZeroFieldWithSurfaceForward(), and Acts::EventDataView3DTest::testMultiTrajectory().