Analysis Software: daq_device_gauss Class Reference
daq_device_gauss Class Reference
#include <rcdaq/blob/master/daq_device_gauss.h>
Public Member Functions
daq_device_gauss (const int eventtype, const int subeventid, const int trigger_enabled=0)
~daq_device_gauss ()
void identify (std::ostream &os=std::cout) const
int max_length (const int etype) const
int put_data (const int etype, int *adr, const int length)
int init ()
int rearm (const int etype)
Public Member Functions inherited from daq_device
daq_device ()
virtual ~daq_device ()
virtual int endrun ()
virtual int subeventid () const
Protected Attributes
subevtdata_ptr sevt
float _mean
float _sigma
pulserTriggerHandler * th
simpleRandom * R
Protected Attributes inherited from daq_device
long m_subeventid
long m_eventType
Additional Inherited Members
Static Public Member Functions inherited from daq_device
static int formatPacketHdr (int *adr)
Detailed Description
Definition at line 23 of file daq_device_gauss.h.
View newest version in sPHENIX GitHub at line 23 of file daq_device_gauss.h
Constructor & Destructor Documentation
daq_device_gauss::daq_device_gauss (const int eventtype, const int subeventid, const int trigger_enabled = 0)
Definition at line 8 of file daq_device_gauss.cc.
View newest version in sPHENIX GitHub at line 8 of file daq_device_gauss.cc
References Acts::IntegrationTest::R, and registerTriggerHandler().
daq_device_gauss::~daq_device_gauss ()
Definition at line 31 of file daq_device_gauss.cc.
View newest version in sPHENIX GitHub at line 31 of file daq_device_gauss.cc
References clearTriggerHandler(), and Acts::IntegrationTest::R.
Member Function Documentation
void daq_device_gauss::identify (std::ostream & os = std::cout) const virtual
Implements daq_device.
Definition at line 86 of file daq_device_gauss.cc.
View newest version in sPHENIX GitHub at line 86 of file daq_device_gauss.cc
int daq_device_gauss::init (void) virtual
Reimplemented from daq_device.
Definition at line 106 of file daq_device_gauss.cc.
View newest version in sPHENIX GitHub at line 106 of file daq_device_gauss.cc
int daq_device_gauss::max_length (const int etype) const virtual
Implements daq_device.
Definition at line 100 of file daq_device_gauss.cc.
View newest version in sPHENIX GitHub at line 100 of file daq_device_gauss.cc
References SEVTHEADERLENGTH.
int daq_device_gauss::put_data (const int etype, int * adr, const int length) virtual
Implements daq_device.
Definition at line 43 of file daq_device_gauss.cc.
View newest version in sPHENIX GitHub at line 43 of file daq_device_gauss.cc
References for(), ID4EVT, Acts::IntegrationTest::R, and SEVTHEADERLENGTH.
int daq_device_gauss::rearm (const int etype) virtual
Reimplemented from daq_device.
Definition at line 113 of file daq_device_gauss.cc.
View newest version in sPHENIX GitHub at line 113 of file daq_device_gauss.cc
Member Data Documentation
float daq_device_gauss::_mean protected
Definition at line 52 of file daq_device_gauss.h.
View newest version in sPHENIX GitHub at line 52 of file daq_device_gauss.h
float daq_device_gauss::_sigma protected
Definition at line 53 of file daq_device_gauss.h.
View newest version in sPHENIX GitHub at line 53 of file daq_device_gauss.h
simpleRandom* daq_device_gauss::R protected
Definition at line 55 of file daq_device_gauss.h.
View newest version in sPHENIX GitHub at line 55 of file daq_device_gauss.h
subevtdata_ptr daq_device_gauss::sevt protected
Definition at line 51 of file daq_device_gauss.h.
View newest version in sPHENIX GitHub at line 51 of file daq_device_gauss.h
pulserTriggerHandler* daq_device_gauss::th protected
Definition at line 54 of file daq_device_gauss.h.
View newest version in sPHENIX GitHub at line 54 of file daq_device_gauss.h
The documentation for this class was generated from the following files:
rcdaq/blob/master/daq_device_gauss.h
rcdaq/blob/master/daq_device_gauss.cc