Analysis Software: JETSCAPE/blob/main/external_packages/trento/test/test_nucleus.cxx File Reference
test_nucleus.cxx File Reference
#include "../src/nucleus.h"
#include <algorithm>
#include <cmath>
#include <iomanip>
#include <iterator>
#include <map>
#include "catch.hpp"
#include "util.h"
#include "../src/hdf5_utils.h"
#include "../src/random.h"
Functions
TEST_CASE ("proton")
TEST_CASE ("deuteron")
TEST_CASE ("lead nucleus")
TEST_CASE ("copper nucleus")
TEST_CASE ("gold nucleus")
TEST_CASE ("uranium nucleus")
TEST_CASE ("woods-saxon sampling")
TEST_CASE ("deformed woods-saxon sampling")
TEST_CASE ("nuclear radius")
TEST_CASE ("minimum distance")
TEST_CASE ("unknown nucleus species")
Function Documentation
TEST_CASE ("proton")
Definition at line 21 of file test_nucleus.cxx.
View newest version in sPHENIX GitHub at line 21 of file test_nucleus.cxx
References CHECK, trento::Nucleus::create(), distance(), and offset.
TEST_CASE ("deuteron")
Definition at line 47 of file test_nucleus.cxx.
View newest version in sPHENIX GitHub at line 47 of file test_nucleus.cxx
References CHECK, trento::Nucleus::create(), distance(), next, ambiguity_solver_full_chain::x, y, and physmon_track_finding_ttbar::z.
TEST_CASE ("lead nucleus")
Definition at line 64 of file test_nucleus.cxx.
View newest version in sPHENIX GitHub at line 64 of file test_nucleus.cxx
References A, CHECK, trento::Nucleus::create(), distance(), n, offset, Acts::Test::tolerance, ambiguity_solver_full_chain::x, y, and physmon_track_finding_ttbar::z.
TEST_CASE ("copper nucleus")
Definition at line 102 of file test_nucleus.cxx.
View newest version in sPHENIX GitHub at line 102 of file test_nucleus.cxx
References A, CHECK, trento::Nucleus::create(), and distance().
TEST_CASE ("gold nucleus")
Definition at line 117 of file test_nucleus.cxx.
View newest version in sPHENIX GitHub at line 117 of file test_nucleus.cxx
References A, CHECK, trento::Nucleus::create(), and distance().
TEST_CASE ("uranium nucleus")
Definition at line 132 of file test_nucleus.cxx.
View newest version in sPHENIX GitHub at line 132 of file test_nucleus.cxx
References A, CHECK, trento::Nucleus::create(), and distance().
TEST_CASE ("woods-saxon sampling")
Definition at line 206 of file test_nucleus.cxx.
View newest version in sPHENIX GitHub at line 206 of file test_nucleus.cxx
References KFPMath::a, A, CHECK, Acts::UnitConstants::e, f, add_histos::hist, i, Acts::Logging::INFO, n, nbins, nevents(), nsamples, Acts::IntegrationTest::R, physmon_track_finding_ttbar::r, ambiguity_solver_full_chain::x, y, and physmon_track_finding_ttbar::z.
TEST_CASE ("deformed woods-saxon sampling")
Definition at line 275 of file test_nucleus.cxx.
View newest version in sPHENIX GitHub at line 275 of file test_nucleus.cxx
References KFPMath::a, A, CHECK, n, nevents(), and Acts::IntegrationTest::R.
TEST_CASE ("nuclear radius")
Definition at line 314 of file test_nucleus.cxx.
View newest version in sPHENIX GitHub at line 314 of file test_nucleus.cxx
References KFPMath::a, CHECK, and Acts::IntegrationTest::R.
TEST_CASE ("minimum distance")
Definition at line 328 of file test_nucleus.cxx.
View newest version in sPHENIX GitHub at line 328 of file test_nucleus.cxx
References CHECK, trento::Nucleus::create(), dy, dz, and Acts::Logging::INFO.
TEST_CASE ("unknown nucleus species")
Definition at line 350 of file test_nucleus.cxx.
View newest version in sPHENIX GitHub at line 350 of file test_nucleus.cxx
References trento::Nucleus::create().