Analysis Software: RawTowerGeomv2 Class Reference
RawTowerGeomv2 Class Reference
#include <coresoftware/blob/master/offline/packages/CaloBase/RawTowerGeomv2.h>
Public Member Functions
RawTowerGeomv2 ()
RawTowerGeomv2 (RawTowerDefs::keytype id)
~RawTowerGeomv2 () override
void identify (std::ostream &os=std::cout) const override
void set_id (RawTowerDefs::keytype key) override
RawTowerDefs::keytype get_id () const override
int get_bineta () const override
int get_binphi () const override
int get_column () const override
int get_row () const override
void set_center_x (double x) override
void set_center_y (double y) override
void set_center_z (double z) override
void set_size_x (double dx) override
void set_size_y (double dy) override
void set_size_z (double dz) override
double get_center_x () const override
double get_center_y () const override
double get_center_z () const override
double get_size_x () const override
double get_size_y () const override
double get_size_z () const override
double get_volume () const override
double get_center_radius () const override
double get_eta () const override
double get_phi () const override
Public Member Functions inherited from RawTowerGeom
~RawTowerGeom () override
virtual int get_binl () const
virtual double get_theta () const
virtual void set_tower_type (int)
virtual int get_tower_type () const
virtual double get_roty () const
virtual double get_rotz () const
virtual void set_roty (double)
virtual void set_rotz (double)
Public Member Functions inherited from PHObject
PHObject ()
ctor
~PHObject () override
dtor
virtual PHObject * CloneMe () const
Virtual copy constructor.
virtual PHObject * clone () const final
PHObject * Clone (const char *newname="") const final
void Copy (TObject &object) const final
virtual void Reset ()
Clear Event.
virtual int isValid () const
isValid returns non zero if object contains vailid data
virtual int Integrate () const
virtual int Integrate (PHObject *)
virtual void CopyFrom (const PHObject *obj)
Protected Attributes
RawTowerDefs::keytype _towerid = ~0U
double _center_x = 0.
double _center_y = 0.
double _center_z = 0.
double _size_x = 0.
double _size_y = 0.
double _size_z = 0.
Additional Inherited Members
Protected Member Functions inherited from RawTowerGeom
RawTowerGeom ()
Detailed Description
Definition at line 10 of file RawTowerGeomv2.h.
View newest version in sPHENIX GitHub at line 10 of file RawTowerGeomv2.h
Constructor & Destructor Documentation
RawTowerGeomv2::RawTowerGeomv2 () inline
Definition at line 13 of file RawTowerGeomv2.h.
View newest version in sPHENIX GitHub at line 13 of file RawTowerGeomv2.h
RawTowerGeomv2::RawTowerGeomv2 (RawTowerDefs::keytype id)
Definition at line 6 of file RawTowerGeomv2.cc.
View newest version in sPHENIX GitHub at line 6 of file RawTowerGeomv2.cc
RawTowerGeomv2::~RawTowerGeomv2 () inline override
Definition at line 15 of file RawTowerGeomv2.h.
View newest version in sPHENIX GitHub at line 15 of file RawTowerGeomv2.h
Member Function Documentation
int RawTowerGeomv2::get_bineta () const inline override virtual
Reimplemented from RawTowerGeom.
Definition at line 22 of file RawTowerGeomv2.h.
View newest version in sPHENIX GitHub at line 22 of file RawTowerGeomv2.h
References _towerid, and RawTowerDefs::decode_index1().
int RawTowerGeomv2::get_binphi () const inline override virtual
Reimplemented from RawTowerGeom.
Definition at line 23 of file RawTowerGeomv2.h.
View newest version in sPHENIX GitHub at line 23 of file RawTowerGeomv2.h
References _towerid, and RawTowerDefs::decode_index2().
double RawTowerGeomv2::get_center_radius () const override virtual
Reimplemented from RawTowerGeom.
Definition at line 11 of file RawTowerGeomv2.cc.
View newest version in sPHENIX GitHub at line 11 of file RawTowerGeomv2.cc
References _center_x, and _center_y.
double RawTowerGeomv2::get_center_x () const inline override virtual
Reimplemented from RawTowerGeom.
Definition at line 59 of file RawTowerGeomv2.h.
View newest version in sPHENIX GitHub at line 59 of file RawTowerGeomv2.h
References _center_x.
Referenced by identify().
double RawTowerGeomv2::get_center_y () const inline override virtual
Reimplemented from RawTowerGeom.
Definition at line 60 of file RawTowerGeomv2.h.
View newest version in sPHENIX GitHub at line 60 of file RawTowerGeomv2.h
References _center_y.
Referenced by identify().
double RawTowerGeomv2::get_center_z () const inline override virtual
Reimplemented from RawTowerGeom.
Definition at line 61 of file RawTowerGeomv2.h.
View newest version in sPHENIX GitHub at line 61 of file RawTowerGeomv2.h
References _center_z.
Referenced by identify().
int RawTowerGeomv2::get_column () const inline override virtual
Reimplemented from RawTowerGeom.
Definition at line 24 of file RawTowerGeomv2.h.
View newest version in sPHENIX GitHub at line 24 of file RawTowerGeomv2.h
References _towerid, and RawTowerDefs::decode_index1().
double RawTowerGeomv2::get_eta () const override virtual
Reimplemented from RawTowerGeom.
Definition at line 17 of file RawTowerGeomv2.cc.
View newest version in sPHENIX GitHub at line 17 of file RawTowerGeomv2.cc
References _center_x, _center_y, _center_z, eta, and ActsTests::PropagationDatasets::theta.
RawTowerDefs::keytype RawTowerGeomv2::get_id () const inline override virtual
Reimplemented from RawTowerGeom.
Definition at line 20 of file RawTowerGeomv2.h.
View newest version in sPHENIX GitHub at line 20 of file RawTowerGeomv2.h
References _towerid.
double RawTowerGeomv2::get_phi () const override virtual
Reimplemented from RawTowerGeom.
Definition at line 29 of file RawTowerGeomv2.cc.
View newest version in sPHENIX GitHub at line 29 of file RawTowerGeomv2.cc
References _center_x, and _center_y.
int RawTowerGeomv2::get_row () const inline override virtual
Reimplemented from RawTowerGeom.
Definition at line 25 of file RawTowerGeomv2.h.
View newest version in sPHENIX GitHub at line 25 of file RawTowerGeomv2.h
References _towerid, and RawTowerDefs::decode_index2().
double RawTowerGeomv2::get_size_x () const inline override virtual
Reimplemented from RawTowerGeom.
Definition at line 63 of file RawTowerGeomv2.h.
View newest version in sPHENIX GitHub at line 63 of file RawTowerGeomv2.h
References _size_x.
Referenced by identify().
double RawTowerGeomv2::get_size_y () const inline override virtual
Reimplemented from RawTowerGeom.
Definition at line 64 of file RawTowerGeomv2.h.
View newest version in sPHENIX GitHub at line 64 of file RawTowerGeomv2.h
References _size_y.
Referenced by identify().
double RawTowerGeomv2::get_size_z () const inline override virtual
Reimplemented from RawTowerGeom.
Definition at line 65 of file RawTowerGeomv2.h.
View newest version in sPHENIX GitHub at line 65 of file RawTowerGeomv2.h
References _size_z.
Referenced by identify().
double RawTowerGeomv2::get_volume () const inline override virtual
Reimplemented from RawTowerGeom.
Definition at line 66 of file RawTowerGeomv2.h.
View newest version in sPHENIX GitHub at line 66 of file RawTowerGeomv2.h
References _size_x, _size_y, and _size_z.
void RawTowerGeomv2::identify (std::ostream & os = std::cout) const override virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from RawTowerGeom.
Definition at line 34 of file RawTowerGeomv2.cc.
View newest version in sPHENIX GitHub at line 34 of file RawTowerGeomv2.cc
References get_center_x(), get_center_y(), get_center_z(), get_size_x(), get_size_y(), and get_size_z().
void RawTowerGeomv2::set_center_x (double x) inline override virtual
Reimplemented from RawTowerGeom.
Definition at line 27 of file RawTowerGeomv2.h.
View newest version in sPHENIX GitHub at line 27 of file RawTowerGeomv2.h
References _center_x, and ambiguity_solver_full_chain::x.
void RawTowerGeomv2::set_center_y (double y) inline override virtual
Reimplemented from RawTowerGeom.
Definition at line 32 of file RawTowerGeomv2.h.
View newest version in sPHENIX GitHub at line 32 of file RawTowerGeomv2.h
References _center_y, and y.
void RawTowerGeomv2::set_center_z (double z) inline override virtual
Reimplemented from RawTowerGeom.
Definition at line 37 of file RawTowerGeomv2.h.
View newest version in sPHENIX GitHub at line 37 of file RawTowerGeomv2.h
References _center_z, and physmon_track_finding_ttbar::z.
void RawTowerGeomv2::set_id (RawTowerDefs::keytype key) inline override virtual
Reimplemented from RawTowerGeom.
Definition at line 19 of file RawTowerGeomv2.h.
View newest version in sPHENIX GitHub at line 19 of file RawTowerGeomv2.h
References _towerid.
void RawTowerGeomv2::set_size_x (double dx) inline override virtual
Reimplemented from RawTowerGeom.
Definition at line 43 of file RawTowerGeomv2.h.
View newest version in sPHENIX GitHub at line 43 of file RawTowerGeomv2.h
References _size_x.
void RawTowerGeomv2::set_size_y (double dy) inline override virtual
Reimplemented from RawTowerGeom.
Definition at line 48 of file RawTowerGeomv2.h.
View newest version in sPHENIX GitHub at line 48 of file RawTowerGeomv2.h
References _size_y, and dy.
void RawTowerGeomv2::set_size_z (double dz) inline override virtual
Reimplemented from RawTowerGeom.
Definition at line 53 of file RawTowerGeomv2.h.
View newest version in sPHENIX GitHub at line 53 of file RawTowerGeomv2.h
References _size_z, and dz.
Member Data Documentation
double RawTowerGeomv2::_center_x = 0. protected
Definition at line 75 of file RawTowerGeomv2.h.
View newest version in sPHENIX GitHub at line 75 of file RawTowerGeomv2.h
Referenced by get_center_radius(), get_center_x(), get_eta(), get_phi(), and set_center_x().
double RawTowerGeomv2::_center_y = 0. protected
Definition at line 76 of file RawTowerGeomv2.h.
View newest version in sPHENIX GitHub at line 76 of file RawTowerGeomv2.h
Referenced by get_center_radius(), get_center_y(), get_eta(), get_phi(), and set_center_y().
double RawTowerGeomv2::_center_z = 0. protected
Definition at line 77 of file RawTowerGeomv2.h.
View newest version in sPHENIX GitHub at line 77 of file RawTowerGeomv2.h
Referenced by get_center_z(), get_eta(), and set_center_z().
double RawTowerGeomv2::_size_x = 0. protected
Definition at line 79 of file RawTowerGeomv2.h.
View newest version in sPHENIX GitHub at line 79 of file RawTowerGeomv2.h
Referenced by get_size_x(), get_volume(), and set_size_x().
double RawTowerGeomv2::_size_y = 0. protected
Definition at line 80 of file RawTowerGeomv2.h.
View newest version in sPHENIX GitHub at line 80 of file RawTowerGeomv2.h
Referenced by get_size_y(), get_volume(), and set_size_y().
double RawTowerGeomv2::_size_z = 0. protected
Definition at line 81 of file RawTowerGeomv2.h.
View newest version in sPHENIX GitHub at line 81 of file RawTowerGeomv2.h
Referenced by get_size_z(), get_volume(), and set_size_z().
RawTowerDefs::keytype RawTowerGeomv2::_towerid = ~0U protected
Definition at line 73 of file RawTowerGeomv2.h.
View newest version in sPHENIX GitHub at line 73 of file RawTowerGeomv2.h
Referenced by get_bineta(), get_binphi(), get_column(), get_id(), get_row(), and set_id().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/CaloBase/RawTowerGeomv2.h
coresoftware/blob/master/offline/packages/CaloBase/RawTowerGeomv2.cc