Analysis Software: ActsExamples::SensitiveSteppingAction Class Reference
ActsExamples::SensitiveSteppingAction Class Reference
#include <acts/blob/sPHENIX/Examples/Algorithms/Geant4/include/ActsExamples/Geant4/SensitiveSteppingAction.hpp>
Classes
struct Config
Configuration of the Stepping action.
Public Member Functions
SensitiveSteppingAction (const Config &cfg, std::unique_ptr< const Acts::Logger > logger=Acts::getDefaultLogger("SensitiveSteppingAction", Acts::Logging::INFO))
~SensitiveSteppingAction () override=default
void UserSteppingAction (const G4Step *step) override
Interface Method doing the step and records the data.
Protected Attributes
Config m_cfg
Private Member Functions
const Acts::Logger & logger () const
Private access method to the logging instance.
EventStore & eventStore () const
Private access method to the event store.
Private Attributes
std::unique_ptr< const
Acts::Logger > m_logger
The looging instance.
Detailed Description
The G4SteppingAction that is called for every step in the simulation process.
It checks whether a sensitive volume is present (via string tag) and records (if necessary) the hit.
Definition at line 28 of file SensitiveSteppingAction.hpp.
View newest version in sPHENIX GitHub at line 28 of file SensitiveSteppingAction.hpp
Constructor & Destructor Documentation
ActsExamples::SensitiveSteppingAction::SensitiveSteppingAction (const Config & cfg, std::unique_ptr< const Acts::Logger > logger = Acts::getDefaultLogger("SensitiveSteppingAction", Acts::Logging::INFO))
Construct the stepping action
Parameters
cfg the configuration struct
logger the ACTS logging instance
Definition at line 93 of file SensitiveSteppingAction.cpp.
View newest version in sPHENIX GitHub at line 93 of file SensitiveSteppingAction.cpp
ActsExamples::SensitiveSteppingAction::~SensitiveSteppingAction () override default
Member Function Documentation
EventStore& ActsExamples::SensitiveSteppingAction::eventStore () const inline private
Private access method to the event store.
Definition at line 63 of file SensitiveSteppingAction.hpp.
View newest version in sPHENIX GitHub at line 63 of file SensitiveSteppingAction.hpp
References ActsExamples::SensitiveSteppingAction::Config::eventStore, and m_cfg.
const Acts::Logger& ActsExamples::SensitiveSteppingAction::logger () const inline private
Private access method to the logging instance.
Definition at line 60 of file SensitiveSteppingAction.hpp.
View newest version in sPHENIX GitHub at line 60 of file SensitiveSteppingAction.hpp
References m_logger.
void ActsExamples::SensitiveSteppingAction::UserSteppingAction (const G4Step * step) override
Interface Method doing the step and records the data.
Parameters
step is the Geant4 step of the particle
Definition at line 97 of file SensitiveSteppingAction.cpp.
View newest version in sPHENIX GitHub at line 97 of file SensitiveSteppingAction.cpp
References ACTS_VERBOSE, assert, end, h, m_cfg(), ActsExamples::SensitiveSurfaceMapper::mappingPrefix, Acts::Test::pos4(), print(), physmon_simulation::s, and size.
Member Data Documentation
Config ActsExamples::SensitiveSteppingAction::m_cfg protected
Definition at line 56 of file SensitiveSteppingAction.hpp.
View newest version in sPHENIX GitHub at line 56 of file SensitiveSteppingAction.hpp
Referenced by eventStore().
std::unique_ptr<const Acts::Logger> ActsExamples::SensitiveSteppingAction::m_logger private
The looging instance.
Definition at line 66 of file SensitiveSteppingAction.hpp.
View newest version in sPHENIX GitHub at line 66 of file SensitiveSteppingAction.hpp
Referenced by logger().
The documentation for this class was generated from the following files:
acts/blob/sPHENIX/Examples/Algorithms/Geant4/include/ActsExamples/Geant4/SensitiveSteppingAction.hpp
acts/blob/sPHENIX/Examples/Algorithms/Geant4/src/SensitiveSteppingAction.cpp