Analysis Software: GTL_debug Class Reference
GTL_debug Class Reference
#include <JETSCAPE/blob/main/external_packages/gtl/include/GTL/debug.h>
Static Public Member Functions
static void debug_message (const char *,...)
static void init_debug ()
static void close_debug ()
static ostream & os ()
Static Private Attributes
static ostream * GTLerr = 0
Detailed Description
Definition at line 30 of file debug.h.
View newest version in sPHENIX GitHub at line 30 of file debug.h
Member Function Documentation
void GTL_debug::close_debug () static
Definition at line 55 of file debug.cpp.
View newest version in sPHENIX GitHub at line 55 of file debug.cpp
References GTLerr.
Referenced by pq_tree::integrity_check(), planarity::~planarity(), and pq_tree::~pq_tree().
void GTL_debug::debug_message (const char * message, ...) static
Definition at line 30 of file debug.cpp.
View newest version in sPHENIX GitHub at line 30 of file debug.cpp
References GTLerr, and os().
Referenced by planarity::case_E(), planarity::examine_obstruction(), pq_tree::integrity_check(), pq_tree::reduce(), pq_tree::reset(), and planarity::run().
void GTL_debug::init_debug () static
Definition at line 44 of file debug.cpp.
View newest version in sPHENIX GitHub at line 44 of file debug.cpp
References release::app, GTLerr, and out.
Referenced by planarity::planarity(), and pq_tree::pq_tree().
static ostream& GTL_debug::os () inline static
Definition at line 35 of file debug.h.
View newest version in sPHENIX GitHub at line 35 of file debug.h
Referenced by debug_message(), planarity::examine_obstruction(), planarity::run(), and planarity::run_on_biconnected().
Member Data Documentation
__GTL_BEGIN_NAMESPACE ostream * GTL_debug::GTLerr = 0 static private
Definition at line 39 of file debug.h.
View newest version in sPHENIX GitHub at line 39 of file debug.h
Referenced by close_debug(), debug_message(), and init_debug().
The documentation for this class was generated from the following files:
JETSCAPE/blob/main/external_packages/gtl/include/GTL/debug.h
JETSCAPE/blob/main/external_packages/gtl/src/debug.cpp