Analysis Software: oncsSub_idinttv0 Class Reference
oncsSub_idinttv0 Class Reference
#include <online_distribution/blob/master/newbasic/oncsSub_idinttv0.h>
Classes
struct intt_hit
Public Member Functions
oncsSub_idinttv0 (subevtdata_ptr)
~oncsSub_idinttv0 ()
int iValue (const int hit, const int field)
long long lValue (const int hit, const int field)
int iValue (const int, const int, const char *what)
int iValue (const int hit, const char *what)
long long lValue (const int hit, const char *what)
void dump (OSTREAM &os=COUT)
Public Member Functions inherited from oncsSubevent_w2
oncsSubevent_w2 (subevtdata_ptr)
virtual void gdump (const int how=EVT_HEXADECIMAL, OSTREAM &os=COUT) const
Public Member Functions inherited from oncsSubevent
oncsSubevent (subevtdata_ptr data)
virtual ~oncsSubevent ()
virtual int getLength () const
virtual int getIdentifier () const
get the packet identifier
virtual int getHitFormat () const
get the hit format; in case of unformatted get the encoding scheme.
virtual int getPadding () const
get the number of padding units in the packet data.
virtual int getDataLength () const
get what the name says...
virtual int getStructure () const
get the structure of the packet data; unformatted, hitlist, etc.
virtual int getDebugLength () const
get the length of the debug block
virtual int getErrorLength () const
virtual void identify (OSTREAM &=COUT) const
virtual int setIdentifier (const int newid)
set a new packet identifier
int iValue (const int)
iValue returns the value of a given channel as an int.
int iValue (const int, const char *)
int iValue (const int, const int)
int iValue (const int, const int, const char *)
int iValue (const int channel, const int iy, const int iz)
int iValue (const int channel, const int iy, const int iz, const char *what)
virtual float rValue (const int)
virtual float rValue (const int, const char *)
virtual float rValue (const int, const int)
virtual int getArraylength (const char *)
virtual int fillIntArray (int[], const int, int *, const char *what="")
virtual int fillFloatArray (float[], const int, int *, const char *what="")
fillFloatArray fills an array of floats
virtual int * getIntArray (int *, const char *what="")
virtual float * getFloatArray (int *, const char *what="")
getFloatArray creates and returns an array of floats
virtual int is_pointer_type () const
find out what type (pointer- or data based) packet object we have
virtual int convert ()
convert from pointer- to data based object, if it is already data-based, do nothing.
virtual int copyMe (int[], const int maxlength) const
int setInternalParameter (const int p1=0, const int p2=0, const char *what="")
Public Member Functions inherited from Packet
virtual ~Packet ()
the virtual destructor
virtual double dValue (const int channel)
virtual double dValue (const int channel, const char *what)
virtual double dValue (const int channel, const int iy)
virtual long long lValue (const int channel)
virtual long long lValue (const int channel, const int iy, const char *what)
virtual void * pValue (const int)
virtual void * pValue (const int, const char *)
virtual void * pValue (const int, const int)
virtual void identify (std::ostream &os=std::cout) const =0
see below for comments
virtual void fullIdentify (std::ostream &os=std::cout) const
write an indepth identification message to the supplied OSTREAM.
virtual void dump (std::ostream &os=std::cout)=0
virtual void gdump (const int how=EVT_HEXADECIMAL, std::ostream &os=std::cout) const =0
virtual int getCheckSumStatus () const
Protected Member Functions
int intt_decode ()
unsigned short reverseBits (const unsigned short x) const
unsigned short crc16 (const unsigned int fee, const unsigned int index, const int l) const
int intt_decode_hitlist (std::vector< unsigned int > &hitlist, const int fee)
Protected Member Functions inherited from oncsSubevent_w2
virtual int * decode (int *)
Protected Attributes
int _broken
int _is_decoded
std::vector< unsigned int > fee_data [MAX_FEECOUNT]
std::vector< intt_hit * > intt_hits
Static Protected Attributes
static const int MAX_FEECOUNT =16
Detailed Description
Definition at line 13 of file oncsSub_idinttv0.h.
View newest version in sPHENIX GitHub at line 13 of file oncsSub_idinttv0.h
Constructor & Destructor Documentation
oncsSub_idinttv0::oncsSub_idinttv0 (subevtdata_ptr data)
Definition at line 11 of file oncsSub_idinttv0.cc.
View newest version in sPHENIX GitHub at line 11 of file oncsSub_idinttv0.cc
References _is_decoded.
oncsSub_idinttv0::~oncsSub_idinttv0 ()
Definition at line 20 of file oncsSub_idinttv0.cc.
View newest version in sPHENIX GitHub at line 20 of file oncsSub_idinttv0.cc
References intt_hits.
Member Function Documentation
unsigned short oncsSub_idinttv0::crc16 (const unsigned int fee, const unsigned int index, const int l) const protected
Definition at line 434 of file oncsSub_idinttv0.cc.
View newest version in sPHENIX GitHub at line 434 of file oncsSub_idinttv0.cc
References fee_data, i, index, k, reverseBits(), and ambiguity_solver_full_chain::x.
void oncsSub_idinttv0::dump (OSTREAM & os = COUT) virtual
Reimplemented from oncsSubevent_w2.
Definition at line 388 of file oncsSub_idinttv0.cc.
View newest version in sPHENIX GitHub at line 388 of file oncsSub_idinttv0.cc
References F_ADC, F_AMPLITUDE, F_BCO, F_CHANNEL_ID, F_CHIP_ID, F_DATAWORD, F_FEE, F_FPHX_BCO, F_FULL_FPHX, F_FULL_ROC, i, oncsSubevent::identify(), intt_decode(), iValue(), and lValue().
int oncsSub_idinttv0::intt_decode () protected
Definition at line 83 of file oncsSub_idinttv0.cc.
View newest version in sPHENIX GitHub at line 83 of file oncsSub_idinttv0.cc
References _broken, _is_decoded, coutfl, subevt_data::data, fee_data, oncsSubevent::getLength(), oncsSubevent::getPadding(), i, index, intt_decode_hitlist(), j, k, MAX_FEECOUNT, SEVTHEADERLENGTH, size, oncsSubevent::SubeventHdr, and while().
Referenced by dump(), iValue(), and lValue().
int oncsSub_idinttv0::intt_decode_hitlist (std::vector< unsigned int > & hitlist, const int fee) protected
Definition at line 33 of file oncsSub_idinttv0.cc.
View newest version in sPHENIX GitHub at line 33 of file oncsSub_idinttv0.cc
References oncsSub_idinttv0::intt_hit::adc, oncsSub_idinttv0::intt_hit::amplitude, BCO, oncsSub_idinttv0::intt_hit::bco, oncsSub_idinttv0::intt_hit::channel_id, oncsSub_idinttv0::intt_hit::chip_id, oncsSub_idinttv0::intt_hit::event_counter, oncsSub_idinttv0::intt_hit::fee, oncsSub_idinttv0::intt_hit::FPHX_BCO, oncsSub_idinttv0::intt_hit::full_FPHX, oncsSub_idinttv0::intt_hit::full_ROC, i, intt_hits, oncsSub_idinttv0::intt_hit::word, and ambiguity_solver_full_chain::x.
Referenced by intt_decode().
int oncsSub_idinttv0::iValue (const int , const int) virtual
this supports devices which are inherently organized as two-dimensional data, such as flash ADC's (channel vs time slice)
Implements Packet.
Definition at line 232 of file oncsSub_idinttv0.cc.
View newest version in sPHENIX GitHub at line 232 of file oncsSub_idinttv0.cc
References F_ADC, F_AMPLITUDE, F_CHANNEL_ID, F_CHIP_ID, F_DATAWORD, F_FEE, F_FPHX_BCO, F_FULL_FPHX, F_FULL_ROC, intt_decode(), and intt_hits.
Referenced by dump(), and iValue().
int oncsSub_idinttv0::iValue (const int , const int , const char *) virtual
we have a few recent devices which have one more dimension (such as card, time sample, channel)
Implements Packet.
Definition at line 280 of file oncsSub_idinttv0.cc.
View newest version in sPHENIX GitHub at line 280 of file oncsSub_idinttv0.cc
References fee_data, index, intt_decode(), MAX_FEECOUNT, and size.
int oncsSub_idinttv0::iValue (const int , const char *) virtual
with the "what" parameter you can decide which aspect of the data you want to see (for devices which have more than one)
Implements Packet.
Definition at line 305 of file oncsSub_idinttv0.cc.
View newest version in sPHENIX GitHub at line 305 of file oncsSub_idinttv0.cc
References F_ADC, F_AMPLITUDE, F_CHANNEL_ID, F_CHIP_ID, F_DATAWORD, F_FEE, F_FPHX_BCO, F_FULL_FPHX, F_FULL_ROC, fee_data, intt_decode(), intt_hits, iValue(), and MAX_FEECOUNT.
long long oncsSub_idinttv0::lValue (const int hit, const int field) virtual
Reimplemented from Packet.
Definition at line 289 of file oncsSub_idinttv0.cc.
View newest version in sPHENIX GitHub at line 289 of file oncsSub_idinttv0.cc
References F_BCO, intt_decode(), and intt_hits.
Referenced by dump(), and lValue().
long long oncsSub_idinttv0::lValue (const int hit, const char * what) virtual
Reimplemented from Packet.
Definition at line 376 of file oncsSub_idinttv0.cc.
View newest version in sPHENIX GitHub at line 376 of file oncsSub_idinttv0.cc
References F_BCO, intt_decode(), and lValue().
unsigned short oncsSub_idinttv0::reverseBits (const unsigned short x) const protected
Definition at line 421 of file oncsSub_idinttv0.cc.
View newest version in sPHENIX GitHub at line 421 of file oncsSub_idinttv0.cc
References n, and ambiguity_solver_full_chain::x.
Referenced by crc16().
Member Data Documentation
int oncsSub_idinttv0::_broken protected
Definition at line 44 of file oncsSub_idinttv0.h.
View newest version in sPHENIX GitHub at line 44 of file oncsSub_idinttv0.h
Referenced by intt_decode().
int oncsSub_idinttv0::_is_decoded protected
Definition at line 46 of file oncsSub_idinttv0.h.
View newest version in sPHENIX GitHub at line 46 of file oncsSub_idinttv0.h
Referenced by intt_decode(), and oncsSub_idinttv0().
std::vector<unsigned int> oncsSub_idinttv0::fee_data[MAX_FEECOUNT] protected
Definition at line 65 of file oncsSub_idinttv0.h.
View newest version in sPHENIX GitHub at line 65 of file oncsSub_idinttv0.h
Referenced by crc16(), intt_decode(), and iValue().
std::vector<intt_hit *> oncsSub_idinttv0::intt_hits protected
Definition at line 66 of file oncsSub_idinttv0.h.
View newest version in sPHENIX GitHub at line 66 of file oncsSub_idinttv0.h
Referenced by intt_decode_hitlist(), iValue(), lValue(), and ~oncsSub_idinttv0().
const int oncsSub_idinttv0::MAX_FEECOUNT =16 static protected
Definition at line 38 of file oncsSub_idinttv0.h.
View newest version in sPHENIX GitHub at line 38 of file oncsSub_idinttv0.h
Referenced by intt_decode(), and iValue().
The documentation for this class was generated from the following files:
online_distribution/blob/master/newbasic/oncsSub_idinttv0.h
online_distribution/blob/master/newbasic/oncsSub_idinttv0.cc