Analysis Software: PHG4CylinderSteppingAction Class Reference
PHG4CylinderSteppingAction Class Reference
#include <coresoftware/blob/master/simulation/g4simulation/g4detectors/PHG4CylinderSteppingAction.h>
Public Member Functions
PHG4CylinderSteppingAction (PHG4CylinderSubsystem *subsys, PHG4CylinderDetector *detector, const PHParameters *parameters)
constructor
~PHG4CylinderSteppingAction () override
destructor
bool UserSteppingAction (const G4Step *, bool) override
stepping action
void SetInterfacePointers (PHCompositeNode *) override
reimplemented from base class
void SaveLightYield (const int i=1)
bool hasMotherSubsystem () const
void SaveAllHits (bool i=true)
void HitNodeName (const std::string &name)
Public Member Functions inherited from PHG4SteppingAction
PHG4SteppingAction (const std::string &name, const int i=0)
virtual ~PHG4SteppingAction ()
virtual void Verbosity (const int i)
virtual int Verbosity () const
virtual int Init ()
virtual int InitWithNode (PHCompositeNode *)
virtual double GetScintLightYield (const G4Step *step)
get scintillation photon count. It require a custom set SCINTILLATIONYIELD property to work
virtual double GetVisibleEnergyDeposition (const G4Step *step)
get amount of energy that can make scintillation light, in Unit of GeV.
virtual void StoreLocalCoordinate (PHG4Hit *hit, const G4Step *step, const bool do_prepoint, const bool do_postpoint)
Extract local coordinate of the hit and save to PHG4Hit.
virtual void Print (const std::string &) const
std::string GetName () const
void SetName (const std::string &name)
virtual void SetLightCorrection (const double inner_radius, const double inner_corr, const double outer_radius, const double outer_corr)
virtual double GetLightCorrection (const double r) const
virtual double GetLightCorrection (const double xpos, const double ypos) const
virtual bool ValidCorrection () const
virtual void SetHitNodeName (const std::string &, const std::string &)
Set the G4HIT node names from Subsystem rather than constructing your own.
Private Attributes
PHG4CylinderSubsystem * m_Subsystem
pointer to the Subsystem
PHG4CylinderDetector * m_Detector
pointer to the detector
const PHParameters * m_Params
PHG4HitContainer * m_HitContainer
pointer to hit container
PHG4Hit * m_Hit
PHG4Shower * m_SaveShower
G4VPhysicalVolume * m_SaveVolPre
G4VPhysicalVolume * m_SaveVolPost
bool m_SaveAllHitsFlag = false
int m_SaveLightYieldFlag
int m_SaveTrackId
int m_SavePreStepStatus
int m_SavePostStepStatus
int m_ActiveFlag
int m_BlackHoleFlag
int m_UseG4StepsFlag
double m_Zmin
double m_Zmax
double m_Tmin
double m_Tmax
std::string m_HitNodeName
Detailed Description
Definition at line 20 of file PHG4CylinderSteppingAction.h.
View newest version in sPHENIX GitHub at line 20 of file PHG4CylinderSteppingAction.h
Constructor & Destructor Documentation
PHG4CylinderSteppingAction::PHG4CylinderSteppingAction (PHG4CylinderSubsystem * subsys, PHG4CylinderDetector * detector, const PHParameters * parameters)
constructor
Definition at line 49 of file PHG4CylinderSteppingAction.cc.
View newest version in sPHENIX GitHub at line 49 of file PHG4CylinderSteppingAction.cc
References Acts::UnitConstants::cm, autodiff::detail::copysign(), m_Zmax, and m_Zmin.
PHG4CylinderSteppingAction::~PHG4CylinderSteppingAction () override
destructor
Definition at line 76 of file PHG4CylinderSteppingAction.cc.
View newest version in sPHENIX GitHub at line 76 of file PHG4CylinderSteppingAction.cc
References m_Hit.
Member Function Documentation
bool PHG4CylinderSteppingAction::hasMotherSubsystem () const
Definition at line 346 of file PHG4CylinderSteppingAction.cc.
View newest version in sPHENIX GitHub at line 346 of file PHG4CylinderSteppingAction.cc
References PHG4Subsystem::GetMotherSubsystem(), and m_Subsystem.
Referenced by UserSteppingAction().
void PHG4CylinderSteppingAction::HitNodeName (const std::string & name) inline
Definition at line 48 of file PHG4CylinderSteppingAction.h.
View newest version in sPHENIX GitHub at line 48 of file PHG4CylinderSteppingAction.h
References m_HitNodeName, and perf_headwind::name.
void PHG4CylinderSteppingAction::SaveAllHits (bool i = true) inline
Definition at line 46 of file PHG4CylinderSteppingAction.h.
View newest version in sPHENIX GitHub at line 46 of file PHG4CylinderSteppingAction.h
References i, and m_SaveAllHitsFlag.
void PHG4CylinderSteppingAction::SaveLightYield (const int i = 1) inline
Definition at line 35 of file PHG4CylinderSteppingAction.h.
View newest version in sPHENIX GitHub at line 35 of file PHG4CylinderSteppingAction.h
References i, and m_SaveLightYieldFlag.
void PHG4CylinderSteppingAction::SetInterfacePointers (PHCompositeNode * topNode) override virtual
reimplemented from base class
Reimplemented from PHG4SteppingAction.
Definition at line 333 of file PHG4CylinderSteppingAction.cc.
View newest version in sPHENIX GitHub at line 333 of file PHG4CylinderSteppingAction.cc
References m_BlackHoleFlag, m_HitContainer, and m_HitNodeName.
bool PHG4CylinderSteppingAction::UserSteppingAction (const G4Step * aStep, bool) override virtual
stepping action
Implements PHG4SteppingAction.
Definition at line 86 of file PHG4CylinderSteppingAction.cc.
View newest version in sPHENIX GitHub at line 86 of file PHG4CylinderSteppingAction.cc
References PHG4Shower::add_g4hit_id(), PHG4HitContainer::AddHit(), Acts::UnitConstants::cm, PHG4Hit::get_edep(), PHG4Hit::get_eion(), PHG4Hit::get_hit_id(), PHG4CylinderDetector::get_Layer(), PHG4Hit::get_light_yield(), PHG4Hit::get_x(), PHG4Hit::get_z(), PHG4HitContainer::GetID(), PHG4SteppingAction::GetName(), PHG4StepStatusDecode::GetStepStatus(), PHG4SteppingAction::GetVisibleEnergyDeposition(), Acts::UnitConstants::GeV, hasMotherSubsystem(), PHG4CylinderDetector::IsInCylinder(), m_ActiveFlag, m_BlackHoleFlag, m_Detector, m_Hit, m_HitContainer, m_SaveAllHitsFlag, m_SaveLightYieldFlag, m_SavePostStepStatus, m_SavePreStepStatus, m_SaveShower, m_SaveTrackId, m_SaveVolPost, m_SaveVolPre, m_Tmax, m_Tmin, m_UseG4StepsFlag, m_Zmax, m_Zmin, merge_hashes::p, PHG4Hit::Reset(), PHG4Hit::set_edep(), PHG4Hit::set_eion(), PHG4Hit::set_layer(), PHG4Hit::set_light_yield(), PHG4Hit::set_px(), PHG4Hit::set_py(), PHG4Hit::set_pz(), PHG4Hit::set_shower_id(), PHG4Hit::set_t(), PHG4Hit::set_trkid(), PHG4Hit::set_x(), PHG4Hit::set_y(), PHG4Hit::set_z(), and PHG4CylinderDetector::SuperDetector().
Member Data Documentation
int PHG4CylinderSteppingAction::m_ActiveFlag private
Definition at line 68 of file PHG4CylinderSteppingAction.h.
View newest version in sPHENIX GitHub at line 68 of file PHG4CylinderSteppingAction.h
Referenced by UserSteppingAction().
int PHG4CylinderSteppingAction::m_BlackHoleFlag private
Definition at line 69 of file PHG4CylinderSteppingAction.h.
View newest version in sPHENIX GitHub at line 69 of file PHG4CylinderSteppingAction.h
Referenced by SetInterfacePointers(), and UserSteppingAction().
PHG4CylinderDetector* PHG4CylinderSteppingAction::m_Detector private
pointer to the detector
Definition at line 54 of file PHG4CylinderSteppingAction.h.
View newest version in sPHENIX GitHub at line 54 of file PHG4CylinderSteppingAction.h
Referenced by UserSteppingAction().
PHG4Hit* PHG4CylinderSteppingAction::m_Hit private
Definition at line 59 of file PHG4CylinderSteppingAction.h.
View newest version in sPHENIX GitHub at line 59 of file PHG4CylinderSteppingAction.h
Referenced by UserSteppingAction(), and ~PHG4CylinderSteppingAction().
PHG4HitContainer* PHG4CylinderSteppingAction::m_HitContainer private
pointer to hit container
Definition at line 58 of file PHG4CylinderSteppingAction.h.
View newest version in sPHENIX GitHub at line 58 of file PHG4CylinderSteppingAction.h
Referenced by SetInterfacePointers(), and UserSteppingAction().
std::string PHG4CylinderSteppingAction::m_HitNodeName private
Definition at line 75 of file PHG4CylinderSteppingAction.h.
View newest version in sPHENIX GitHub at line 75 of file PHG4CylinderSteppingAction.h
Referenced by HitNodeName(), and SetInterfacePointers().
const PHParameters* PHG4CylinderSteppingAction::m_Params private
Definition at line 55 of file PHG4CylinderSteppingAction.h.
View newest version in sPHENIX GitHub at line 55 of file PHG4CylinderSteppingAction.h
bool PHG4CylinderSteppingAction::m_SaveAllHitsFlag = false private
Definition at line 63 of file PHG4CylinderSteppingAction.h.
View newest version in sPHENIX GitHub at line 63 of file PHG4CylinderSteppingAction.h
Referenced by SaveAllHits(), and UserSteppingAction().
int PHG4CylinderSteppingAction::m_SaveLightYieldFlag private
Definition at line 64 of file PHG4CylinderSteppingAction.h.
View newest version in sPHENIX GitHub at line 64 of file PHG4CylinderSteppingAction.h
Referenced by SaveLightYield(), and UserSteppingAction().
int PHG4CylinderSteppingAction::m_SavePostStepStatus private
Definition at line 67 of file PHG4CylinderSteppingAction.h.
View newest version in sPHENIX GitHub at line 67 of file PHG4CylinderSteppingAction.h
Referenced by UserSteppingAction().
int PHG4CylinderSteppingAction::m_SavePreStepStatus private
Definition at line 66 of file PHG4CylinderSteppingAction.h.
View newest version in sPHENIX GitHub at line 66 of file PHG4CylinderSteppingAction.h
Referenced by UserSteppingAction().
PHG4Shower* PHG4CylinderSteppingAction::m_SaveShower private
Definition at line 60 of file PHG4CylinderSteppingAction.h.
View newest version in sPHENIX GitHub at line 60 of file PHG4CylinderSteppingAction.h
Referenced by UserSteppingAction().
int PHG4CylinderSteppingAction::m_SaveTrackId private
Definition at line 65 of file PHG4CylinderSteppingAction.h.
View newest version in sPHENIX GitHub at line 65 of file PHG4CylinderSteppingAction.h
Referenced by UserSteppingAction().
G4VPhysicalVolume* PHG4CylinderSteppingAction::m_SaveVolPost private
Definition at line 62 of file PHG4CylinderSteppingAction.h.
View newest version in sPHENIX GitHub at line 62 of file PHG4CylinderSteppingAction.h
Referenced by UserSteppingAction().
G4VPhysicalVolume* PHG4CylinderSteppingAction::m_SaveVolPre private
Definition at line 61 of file PHG4CylinderSteppingAction.h.
View newest version in sPHENIX GitHub at line 61 of file PHG4CylinderSteppingAction.h
Referenced by UserSteppingAction().
PHG4CylinderSubsystem* PHG4CylinderSteppingAction::m_Subsystem private
pointer to the Subsystem
Definition at line 52 of file PHG4CylinderSteppingAction.h.
View newest version in sPHENIX GitHub at line 52 of file PHG4CylinderSteppingAction.h
Referenced by hasMotherSubsystem().
double PHG4CylinderSteppingAction::m_Tmax private
Definition at line 74 of file PHG4CylinderSteppingAction.h.
View newest version in sPHENIX GitHub at line 74 of file PHG4CylinderSteppingAction.h
Referenced by UserSteppingAction().
double PHG4CylinderSteppingAction::m_Tmin private
Definition at line 73 of file PHG4CylinderSteppingAction.h.
View newest version in sPHENIX GitHub at line 73 of file PHG4CylinderSteppingAction.h
Referenced by UserSteppingAction().
int PHG4CylinderSteppingAction::m_UseG4StepsFlag private
Definition at line 70 of file PHG4CylinderSteppingAction.h.
View newest version in sPHENIX GitHub at line 70 of file PHG4CylinderSteppingAction.h
Referenced by UserSteppingAction().
double PHG4CylinderSteppingAction::m_Zmax private
Definition at line 72 of file PHG4CylinderSteppingAction.h.
View newest version in sPHENIX GitHub at line 72 of file PHG4CylinderSteppingAction.h
Referenced by PHG4CylinderSteppingAction(), and UserSteppingAction().
double PHG4CylinderSteppingAction::m_Zmin private
Definition at line 71 of file PHG4CylinderSteppingAction.h.
View newest version in sPHENIX GitHub at line 71 of file PHG4CylinderSteppingAction.h
Referenced by PHG4CylinderSteppingAction(), and UserSteppingAction().
The documentation for this class was generated from the following files:
coresoftware/blob/master/simulation/g4simulation/g4detectors/PHG4CylinderSteppingAction.h
coresoftware/blob/master/simulation/g4simulation/g4detectors/PHG4CylinderSteppingAction.cc