Analysis Software: analysis/blob/master/Tracking/BenchmarkingTools/PhysicsPerformanceTools/InttQA.C File Reference
InttQA.C File Reference
#include "../CommonTools.h"
#include <sPhenixStyle.C>
Functions
TCanvas * Draw (TFile *qa_file_new, TFile *qa_file_ref, const TString &hist_name_prefix, const TString &tag)
void InttQA (std::string reffile, std::string newfile, std::string outfile)
Variables
const char * hist_name_prefix = "QAG4SimulationIntt"
static constexpr int first_layer_intt = 3
static constexpr int nlayers_intt = 4
Function Documentation
TCanvas * Draw (TFile * qa_file_new, TFile * qa_file_ref, const TString & hist_name_prefix, const TString & tag)
Definition at line 43 of file InttQA.C.
View newest version in sPHENIX GitHub at line 43 of file InttQA.C
References DivideCanvas(), DrawReference(), first_layer_intt, layer, line, nlayers_intt, prefix, and VerticalLine().
void InttQA (std::string reffile, std::string newfile, std::string outfile)
Definition at line 12 of file InttQA.C.
View newest version in sPHENIX GitHub at line 12 of file InttQA.C
References c2, Draw(), hist_name_prefix, and SetsPhenixStyle().
Variable Documentation
constexpr int first_layer_intt = 3 static
Definition at line 9 of file InttQA.C.
View newest version in sPHENIX GitHub at line 9 of file InttQA.C
Referenced by Draw().
const char* hist_name_prefix = "QAG4SimulationIntt"
Definition at line 6 of file InttQA.C.
View newest version in sPHENIX GitHub at line 6 of file InttQA.C
Referenced by InttQA(), MvtxQA(), TpcQA(), TpotQA(), TrackingQA(), and VertexingQA().
constexpr int nlayers_intt = 4 static
Definition at line 10 of file InttQA.C.
View newest version in sPHENIX GitHub at line 10 of file InttQA.C
Referenced by Draw().