Analysis Software: Acts::Experimental::DetectorBuilder Exception Reference
Acts::Experimental::DetectorBuilder Exception Reference final
Standard generic Detector builder that calls the top level component builder and transfers the result into a detector object.
#include <acts/blob/sPHENIX/Core/include/Acts/Detector/DetectorBuilder.hpp>
Classes
struct Config
Nested configuration object.
Public Member Functions
DetectorBuilder (const Config &cfg, std::unique_ptr< const Logger > mlogger=getDefaultLogger("DetectorBuilder", Logging::INFO))
std::shared_ptr< const Detector > construct (const GeometryContext &gctx) const final
Public Member Functions inherited from Acts::Experimental::IDetectorBuilder
virtual ~IDetectorBuilder ()=default
Private Member Functions
const Logger & logger () const
Private access method to the logger.
Private Attributes
Config m_cfg
configuration object
std::unique_ptr< const Logger > m_logger
logging instance
Detailed Description
Standard generic Detector builder that calls the top level component builder and transfers the result into a detector object.
Note
This is the last builder in the chain and the the returned detector object is const and cannot be modified anymore.
Definition at line 30 of file DetectorBuilder.hpp.
View newest version in sPHENIX GitHub at line 30 of file DetectorBuilder.hpp
Constructor & Destructor Documentation
Acts::Experimental::DetectorBuilder::DetectorBuilder (const Config & cfg, std::unique_ptr< const Logger > mlogger = getDefaultLogger("DetectorBuilder", Logging::INFO))
Constructor with configuration arguments
Parameters
cfg is the configuration struct
mlogger logging instance for screen output
Definition at line 18 of file DetectorBuilder.cpp.
View newest version in sPHENIX GitHub at line 18 of file DetectorBuilder.cpp
References Acts::Experimental::DetectorBuilder::Config::builder, and m_cfg.
Member Function Documentation
std::shared_ptr< const Acts::Experimental::Detector > Acts::Experimental::DetectorBuilder::construct (const GeometryContext & gctx) const final virtual
Final implementation of a volume builder that is purely defined by an internal and external structure builder
Parameters
gctx The geometry context for this call
Returns
an outgoing detector component
Implements Acts::Experimental::IDetectorBuilder.
Definition at line 29 of file DetectorBuilder.cpp.
View newest version in sPHENIX GitHub at line 29 of file DetectorBuilder.cpp
References ACTS_DEBUG, m_cfg(), Acts::Experimental::Detector::makeShared(), testing::internal::move(), testSigmaEff::v, and volumes.
Referenced by BOOST_AUTO_TEST_CASE().
const Logger& Acts::Experimental::DetectorBuilder::logger () const inline private
Private access method to the logger.
Definition at line 66 of file DetectorBuilder.hpp.
View newest version in sPHENIX GitHub at line 66 of file DetectorBuilder.hpp
References m_logger.
Member Data Documentation
Config Acts::Experimental::DetectorBuilder::m_cfg private
configuration object
Definition at line 63 of file DetectorBuilder.hpp.
View newest version in sPHENIX GitHub at line 63 of file DetectorBuilder.hpp
Referenced by DetectorBuilder().
std::unique_ptr<const Logger> Acts::Experimental::DetectorBuilder::m_logger private
logging instance
Definition at line 69 of file DetectorBuilder.hpp.
View newest version in sPHENIX GitHub at line 69 of file DetectorBuilder.hpp
Referenced by logger().
The documentation for this exception was generated from the following files:
acts/blob/sPHENIX/Core/include/Acts/Detector/DetectorBuilder.hpp
acts/blob/sPHENIX/Core/src/Detector/DetectorBuilder.cpp