Analysis Software: Acts::Test::float_compare_internal Namespace Reference
Acts::Test::float_compare_internal Namespace Reference
Typedefs
using predicate_result = boost::test_tools::predicate_result
using ScalarComparison = std::function< predicate_result(double, double)>
template<typename T >
using has_begin_t = decltype(std::declval< T >().cbegin())
template<typename T >
using has_end_t = decltype(std::declval< T >().cend())
template<typename T >
using has_eval_t = decltype(std::declval< T >().eval())
Functions
ScalarComparison closeOrSmall (double reltol, double small)
ScalarComparison closeAbs (double abstol)
template<typename Derived1 , typename Derived2 >
predicate_result matrixCompare (const Eigen::DenseBase< Derived1 > &val, const Eigen::DenseBase< Derived2 > &ref, ScalarComparison &&compareImpl)
template<typename Container , typename = std::enable_if_t< !Acts::Concepts::exists<has_eval_t, Container> && Acts::Concepts::exists<has_begin_t, Container> && Acts::Concepts::exists<has_end_t, Container>, int>>
predicate_result compare (const Container &val, const Container &ref, ScalarComparison &&compareImpl)
template<typename T , typename U >
predicate_result compare (const Eigen::DenseBase< T > &val, const Eigen::DenseBase< U > &ref, ScalarComparison &&compareImpl)
predicate_result compare (const Transform3 &val, const Transform3 &ref, ScalarComparison &&compareImpl)
predicate_result compare (double val, double ref, ScalarComparison &&compareImpl)
Typedef Documentation
template<typename T > using Acts::Test::float_compare_internal::has_begin_t = typedef decltype(std::declval<T>().cbegin())
Definition at line 159 of file FloatComparisons.hpp.
View newest version in sPHENIX GitHub at line 159 of file FloatComparisons.hpp
template<typename T > using Acts::Test::float_compare_internal::has_end_t = typedef decltype(std::declval<T>().cend())
Definition at line 161 of file FloatComparisons.hpp.
View newest version in sPHENIX GitHub at line 161 of file FloatComparisons.hpp
template<typename T > using Acts::Test::float_compare_internal::has_eval_t = typedef decltype(std::declval<T>().eval())
Definition at line 163 of file FloatComparisons.hpp.
View newest version in sPHENIX GitHub at line 163 of file FloatComparisons.hpp
using Acts::Test::float_compare_internal::predicate_result = typedef boost::test_tools::predicate_result
Definition at line 65 of file FloatComparisons.hpp.
View newest version in sPHENIX GitHub at line 65 of file FloatComparisons.hpp
using Acts::Test::float_compare_internal::ScalarComparison = typedef std::function<predicate_result(double, double)>
Definition at line 67 of file FloatComparisons.hpp.
View newest version in sPHENIX GitHub at line 67 of file FloatComparisons.hpp
Function Documentation
ScalarComparison Acts::Test::float_compare_internal::closeAbs (double abstol)
Definition at line 96 of file FloatComparisons.hpp.
View newest version in sPHENIX GitHub at line 96 of file FloatComparisons.hpp
References check_smearing_config::ref.
Referenced by Acts::Test::checkCloseAbs().
ScalarComparison Acts::Test::float_compare_internal::closeOrSmall (double reltol, double small)
Definition at line 69 of file FloatComparisons.hpp.
View newest version in sPHENIX GitHub at line 69 of file FloatComparisons.hpp
References check_smearing_config::ref, and small.
Referenced by Acts::Test::checkCloseOrSmall(), Acts::Test::checkCloseRel(), and Acts::Test::checkSmall().
template<typename Container , typename = std::enable_if_t< !Acts::Concepts::exists<has_eval_t, Container> && Acts::Concepts::exists<has_begin_t, Container> && Acts::Concepts::exists<has_end_t, Container>, int>> predicate_result Acts::Test::float_compare_internal::compare (const Container & val, const Container & ref, ScalarComparison && compareImpl)
Definition at line 176 of file FloatComparisons.hpp.
View newest version in sPHENIX GitHub at line 176 of file FloatComparisons.hpp
References distance().
Referenced by Acts::Test::checkCloseAbs(), Acts::Test::checkCloseOrSmall(), Acts::Test::checkCloseRel(), and Acts::Test::checkSmall().
template<typename T , typename U > predicate_result Acts::Test::float_compare_internal::compare (const Eigen::DenseBase< T > & val, const Eigen::DenseBase< U > & ref, ScalarComparison && compareImpl)
Definition at line 222 of file FloatComparisons.hpp.
View newest version in sPHENIX GitHub at line 222 of file FloatComparisons.hpp
References matrixCompare(), and testing::internal::move().
predicate_result Acts::Test::float_compare_internal::compare (const Transform3 & val, const Transform3 & ref, ScalarComparison && compareImpl)
Definition at line 229 of file FloatComparisons.hpp.
View newest version in sPHENIX GitHub at line 229 of file FloatComparisons.hpp
References matrixCompare(), and testing::internal::move().
predicate_result Acts::Test::float_compare_internal::compare (double val, double ref, ScalarComparison && compareImpl)
Definition at line 235 of file FloatComparisons.hpp.
View newest version in sPHENIX GitHub at line 235 of file FloatComparisons.hpp
template<typename Derived1 , typename Derived2 > predicate_result Acts::Test::float_compare_internal::matrixCompare (const Eigen::DenseBase< Derived1 > & val, const Eigen::DenseBase< Derived2 > & ref, ScalarComparison && compareImpl)
Definition at line 116 of file FloatComparisons.hpp.
View newest version in sPHENIX GitHub at line 116 of file FloatComparisons.hpp
References col, and check_smearing_config::ref.
Referenced by compare().