Analysis Software: acts/blob/sPHENIX/Tests/Benchmarks/RayFrustumBenchmark.cpp File Reference
RayFrustumBenchmark.cpp File Reference
#include "Acts/Definitions/Algebra.hpp"
#include "Acts/Definitions/Units.hpp"
#include "Acts/Surfaces/BoundaryCheck.hpp"
#include "Acts/Tests/CommonHelpers/BenchmarkTools.hpp"
#include "Acts/Utilities/BoundingBox.hpp"
#include "Acts/Utilities/Frustum.hpp"
#include "Acts/Utilities/Ray.hpp"
#include <algorithm>
#include <chrono>
#include <functional>
#include <iostream>
#include <map>
#include <random>
#include <vector>
Classes
struct O
Typedefs
using Box = Acts::AxisAlignedBoundingBox< O, float, 3 >
using VertexType = Box::VertexType
using vertex_array_type = Box::vertex_array_type
using value_type = Box::value_type
using Frustum3 = Frustum< float, 3, 4 >
using Ray3 = Ray< float, 3 >
Functions
int main (int, char **)
Typedef Documentation
using Box = Acts::AxisAlignedBoundingBox<O, float, 3>
Definition at line 28 of file RayFrustumBenchmark.cpp.
View newest version in sPHENIX GitHub at line 28 of file RayFrustumBenchmark.cpp
using Frustum3 = Frustum<float, 3, 4>
Definition at line 32 of file RayFrustumBenchmark.cpp.
View newest version in sPHENIX GitHub at line 32 of file RayFrustumBenchmark.cpp
using Ray3 = Ray<float, 3>
Definition at line 33 of file RayFrustumBenchmark.cpp.
View newest version in sPHENIX GitHub at line 33 of file RayFrustumBenchmark.cpp
using value_type = Box::value_type
Definition at line 31 of file RayFrustumBenchmark.cpp.
View newest version in sPHENIX GitHub at line 31 of file RayFrustumBenchmark.cpp
using vertex_array_type = Box::vertex_array_type
Definition at line 30 of file RayFrustumBenchmark.cpp.
View newest version in sPHENIX GitHub at line 30 of file RayFrustumBenchmark.cpp
using VertexType = Box::VertexType
Definition at line 29 of file RayFrustumBenchmark.cpp.
View newest version in sPHENIX GitHub at line 29 of file RayFrustumBenchmark.cpp
Function Documentation
int main (int , char **)
Definition at line 35 of file RayFrustumBenchmark.cpp.
View newest version in sPHENIX GitHub at line 35 of file RayFrustumBenchmark.cpp
References i, Acts::AxisAlignedBoundingBox< entity_t, value_t, DIM >::intersect(), loc, Acts::AxisAlignedBoundingBox< entity_t, value_t, DIM >::max(), Acts::Test::microBenchmark(), Acts::UnitConstants::min, Acts::AxisAlignedBoundingBox< entity_t, value_t, DIM >::min(), n, perf_headwind::name, Acts::Test::origin(), merge_hashes::p, physmon_track_finding_ttbar::r, TauVsDIS_MachineLearning_Differentiation::results, conftest::rng(), ambiguity_solver_full_chain::t1, ambiguity_solver_full_chain::t2, Acts::Test::transform, ambiguity_solver_full_chain::x, y, and physmon_track_finding_ttbar::z.