Analysis Software: MvtxPrototype2UnpackPRDF Class Reference
MvtxPrototype2UnpackPRDF Class Reference
#include <prototype/blob/master/offline/packages/MvtxPrototype2/MvtxPrototype2UnpackPRDF.h>
Public Member Functions
MvtxPrototype2UnpackPRDF ()
int Init (PHCompositeNode *topNode)
int InitRun (PHCompositeNode *topNode)
int process_event (PHCompositeNode *topNode)
int End (PHCompositeNode *topNode)
Called at the end of all processing.
void CreateNodeTree (PHCompositeNode *topNode)
void MakeHits ()
int DecodeRow (int val) const
int DecodeCol (int val) const
Public Member Functions inherited from SubsysReco
~SubsysReco () override
virtual int EndRun (const int)
Called at the end of each run.
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
void Print (const std::string &="ALL") const override
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Private Attributes
PHCompositeNode * dstNode
Event * _event
Packet_hbd_fpgashort * _packet
TrkrHitSetContainer * _hitsetcon
int _nevents
int _verbosity
bool _first
int _nevent_per_chip [NLAYER][NCHIP]
int _npixel_per_chip [NLAYER][NCHIP]
Static Private Attributes
static std::map< std::pair
< int, int >, std::pair< int,
int > > s_map_chips
static std::map< int, int > s_map_layers = { {0,0}, {1,1}, {2,2}, {3,3} }
<stave, layer> stave to layer index
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = std::numeric_limits<int>::max() - 10
}
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Detailed Description
Definition at line 18 of file MvtxPrototype2UnpackPRDF.h.
View newest version in sPHENIX GitHub at line 18 of file MvtxPrototype2UnpackPRDF.h
Constructor & Destructor Documentation
MvtxPrototype2UnpackPRDF::MvtxPrototype2UnpackPRDF ()
Definition at line 85 of file MvtxPrototype2UnpackPRDF.cc.
View newest version in sPHENIX GitHub at line 85 of file MvtxPrototype2UnpackPRDF.cc
References _nevent_per_chip, _npixel_per_chip, NCHIP, and NLAYER.
Member Function Documentation
void MvtxPrototype2UnpackPRDF::CreateNodeTree (PHCompositeNode * topNode)
Definition at line 215 of file MvtxPrototype2UnpackPRDF.cc.
View newest version in sPHENIX GitHub at line 215 of file MvtxPrototype2UnpackPRDF.cc
References PHCompositeNode::addNode(), dstNode, and PHNodeIterator::findFirst().
Referenced by InitRun().
int MvtxPrototype2UnpackPRDF::DecodeCol (int val) const
Definition at line 430 of file MvtxPrototype2UnpackPRDF.cc.
View newest version in sPHENIX GitHub at line 430 of file MvtxPrototype2UnpackPRDF.cc
Referenced by MakeHits().
int MvtxPrototype2UnpackPRDF::DecodeRow (int val) const
Definition at line 423 of file MvtxPrototype2UnpackPRDF.cc.
View newest version in sPHENIX GitHub at line 423 of file MvtxPrototype2UnpackPRDF.cc
Referenced by MakeHits().
int MvtxPrototype2UnpackPRDF::End (PHCompositeNode *) virtual
Called at the end of all processing.
Reimplemented from SubsysReco.
Definition at line 437 of file MvtxPrototype2UnpackPRDF.cc.
View newest version in sPHENIX GitHub at line 437 of file MvtxPrototype2UnpackPRDF.cc
References _nevent_per_chip, _npixel_per_chip, Fun4AllReturnCodes::EVENT_OK, NCHIP, NLAYER, Fun4AllBase::Verbosity(), and Fun4AllBase::VERBOSITY_SOME.
int MvtxPrototype2UnpackPRDF::Init (PHCompositeNode *) virtual
Called during initialization. Typically this is where you can book histograms, and e.g. register them to Fun4AllServer (so they can be output to file using Fun4AllServer::dumpHistos() method).
Reimplemented from SubsysReco.
Definition at line 103 of file MvtxPrototype2UnpackPRDF.cc.
View newest version in sPHENIX GitHub at line 103 of file MvtxPrototype2UnpackPRDF.cc
References Fun4AllReturnCodes::EVENT_OK.
int MvtxPrototype2UnpackPRDF::InitRun (PHCompositeNode *) virtual
Called for first event when run number is known. Typically this is where you may want to fetch data from database, because you know the run number.
Reimplemented from SubsysReco.
Definition at line 112 of file MvtxPrototype2UnpackPRDF.cc.
View newest version in sPHENIX GitHub at line 112 of file MvtxPrototype2UnpackPRDF.cc
References CreateNodeTree(), and Fun4AllReturnCodes::EVENT_OK.
void MvtxPrototype2UnpackPRDF::MakeHits ()
Definition at line 260 of file MvtxPrototype2UnpackPRDF.cc.
View newest version in sPHENIX GitHub at line 260 of file MvtxPrototype2UnpackPRDF.cc
References _event, _nevent_per_chip, _nevents, _npixel_per_chip, DecodeCol(), DecodeRow(), MicromegasDefs::genHitKey(), MicromegasDefs::genHitSetKey(), Event::getPacket(), Packet::iValue(), NCOL, NMAXRU, NMAXRUCHN, NROW, merge_hashes::p, PHWHERE, s_map_chips, and s_map_layers.
Referenced by process_event().
int MvtxPrototype2UnpackPRDF::process_event (PHCompositeNode *) virtual
Called for each event. This is where you do the real work.
Reimplemented from SubsysReco.
Definition at line 123 of file MvtxPrototype2UnpackPRDF.cc.
View newest version in sPHENIX GitHub at line 123 of file MvtxPrototype2UnpackPRDF.cc
References _event, _hitsetcon, _nevents, Fun4AllReturnCodes::ABORTEVENT, BEGRUNEVENT, DATAEVENT, Fun4AllReturnCodes::EVENT_OK, TrkrHitSetContainer::findHitSet(), MvtxDefs::genHitSetKey(), Event::getEvtType(), MakeHits(), NCHIP, NLAYER, TrkrHitSet::size(), Fun4AllBase::Verbosity(), and Fun4AllBase::VERBOSITY_MORE.
Member Data Documentation
Event* MvtxPrototype2UnpackPRDF::_event private
Definition at line 47 of file MvtxPrototype2UnpackPRDF.h.
View newest version in sPHENIX GitHub at line 47 of file MvtxPrototype2UnpackPRDF.h
Referenced by MakeHits(), and process_event().
bool MvtxPrototype2UnpackPRDF::_first private
Definition at line 56 of file MvtxPrototype2UnpackPRDF.h.
View newest version in sPHENIX GitHub at line 56 of file MvtxPrototype2UnpackPRDF.h
TrkrHitSetContainer* MvtxPrototype2UnpackPRDF::_hitsetcon private
Definition at line 49 of file MvtxPrototype2UnpackPRDF.h.
View newest version in sPHENIX GitHub at line 49 of file MvtxPrototype2UnpackPRDF.h
Referenced by process_event().
int MvtxPrototype2UnpackPRDF::_nevent_per_chip[NLAYER][NCHIP] private
Definition at line 58 of file MvtxPrototype2UnpackPRDF.h.
View newest version in sPHENIX GitHub at line 58 of file MvtxPrototype2UnpackPRDF.h
Referenced by End(), MakeHits(), and MvtxPrototype2UnpackPRDF().
int MvtxPrototype2UnpackPRDF::_nevents private
Definition at line 54 of file MvtxPrototype2UnpackPRDF.h.
View newest version in sPHENIX GitHub at line 54 of file MvtxPrototype2UnpackPRDF.h
Referenced by MakeHits(), and process_event().
int MvtxPrototype2UnpackPRDF::_npixel_per_chip[NLAYER][NCHIP] private
Definition at line 59 of file MvtxPrototype2UnpackPRDF.h.
View newest version in sPHENIX GitHub at line 59 of file MvtxPrototype2UnpackPRDF.h
Referenced by End(), MakeHits(), and MvtxPrototype2UnpackPRDF().
Packet_hbd_fpgashort* MvtxPrototype2UnpackPRDF::_packet private
Definition at line 48 of file MvtxPrototype2UnpackPRDF.h.
View newest version in sPHENIX GitHub at line 48 of file MvtxPrototype2UnpackPRDF.h
int MvtxPrototype2UnpackPRDF::_verbosity private
Definition at line 55 of file MvtxPrototype2UnpackPRDF.h.
View newest version in sPHENIX GitHub at line 55 of file MvtxPrototype2UnpackPRDF.h
PHCompositeNode* MvtxPrototype2UnpackPRDF::dstNode private
Definition at line 45 of file MvtxPrototype2UnpackPRDF.h.
View newest version in sPHENIX GitHub at line 45 of file MvtxPrototype2UnpackPRDF.h
Referenced by CreateNodeTree().
map< pair< int, int >, pair< int, int > > MvtxPrototype2UnpackPRDF::s_map_chips static private
Definition at line 51 of file MvtxPrototype2UnpackPRDF.h.
View newest version in sPHENIX GitHub at line 51 of file MvtxPrototype2UnpackPRDF.h
Referenced by MakeHits().
map< int, int > MvtxPrototype2UnpackPRDF::s_map_layers = { {0,0}, {1,1}, {2,2}, {3,3} } static private
<stave, layer> stave to layer index
Layers order in geom A105 -> layer 0, stave 0 C104 -> layer 1, stave 0 C105 -> layer 2, stave 0 E103 -> layer 3, stave 0 <{stave_from_map_chips, layers_in_geom}
Definition at line 52 of file MvtxPrototype2UnpackPRDF.h.
View newest version in sPHENIX GitHub at line 52 of file MvtxPrototype2UnpackPRDF.h
Referenced by MakeHits().
The documentation for this class was generated from the following files:
prototype/blob/master/offline/packages/MvtxPrototype2/MvtxPrototype2UnpackPRDF.h
prototype/blob/master/offline/packages/MvtxPrototype2/MvtxPrototype2UnpackPRDF.cc