Analysis Software: PHGenFit2::Fitter Class Reference
PHGenFit2::Fitter Class Reference
#include <coresoftware/blob/master/offline/packages/PHTpcTracker/Fitter.h>
Public Member Functions
Fitter (TGeoManager *tgeo_manager, PHField *field)
~Fitter ()
genfit::KalmanFitter * getFitter5 ()
genfit::KalmanFitter * getFitter1 ()
void processTrack5 (PHGenFit2::Track *track)
void processTrack1 (PHGenFit2::Track *track)
void processTrack5 (genfit::Track *track)
void processTrack1 (genfit::Track *track)
void processTrackPartially (PHGenFit2::Track *track, int startId=0, int endId=-1)
void processTrackPartially (genfit::Track *track, int startId=0, int endId=-1)
Private Attributes
genfit::KalmanFitter * _fitter5
genfit::KalmanFitter * _fitter1
Detailed Description
Definition at line 20 of file Fitter.h.
View newest version in sPHENIX GitHub at line 20 of file Fitter.h
Constructor & Destructor Documentation
PHGenFit2::Fitter::Fitter (TGeoManager * tgeo_manager, PHField * field)
Definition at line 22 of file Fitter.cc.
View newest version in sPHENIX GitHub at line 22 of file Fitter.cc
References _fitter1, _fitter5, testing::Field(), genfit::MaterialEffects::getInstance(), genfit::FieldManager::getInstance(), genfit::MaterialEffects::init(), genfit::FieldManager::init(), and genfit::Exception::quiet().
PHGenFit2::Fitter::~Fitter ()
Definition at line 38 of file Fitter.cc.
View newest version in sPHENIX GitHub at line 38 of file Fitter.cc
References _fitter1, and _fitter5.
Member Function Documentation
genfit::KalmanFitter* PHGenFit2::Fitter::getFitter1 () inline
Definition at line 27 of file Fitter.h.
View newest version in sPHENIX GitHub at line 27 of file Fitter.h
References _fitter5.
genfit::KalmanFitter* PHGenFit2::Fitter::getFitter5 () inline
Definition at line 26 of file Fitter.h.
View newest version in sPHENIX GitHub at line 26 of file Fitter.h
References _fitter5.
void PHGenFit2::Fitter::processTrack1 (PHGenFit2::Track * track) inline
Definition at line 30 of file Fitter.h.
View newest version in sPHENIX GitHub at line 30 of file Fitter.h
References PHGenFit2::Track::getGenFitTrack(), and processTrack1().
Referenced by processTrack1(), and PHTpcTrackFollower::propagateTrack().
void PHGenFit2::Fitter::processTrack1 (genfit::Track * track) inline
Definition at line 33 of file Fitter.h.
View newest version in sPHENIX GitHub at line 33 of file Fitter.h
References _fitter1, and genfit::AbsFitter::processTrack().
void PHGenFit2::Fitter::processTrack5 (PHGenFit2::Track * track) inline
Definition at line 29 of file Fitter.h.
View newest version in sPHENIX GitHub at line 29 of file Fitter.h
References PHGenFit2::Track::getGenFitTrack(), and processTrack5().
Referenced by processTrack5(), and PHTpcTrackFollower::propagateTrack().
void PHGenFit2::Fitter::processTrack5 (genfit::Track * track) inline
Definition at line 32 of file Fitter.h.
View newest version in sPHENIX GitHub at line 32 of file Fitter.h
References _fitter5, and genfit::AbsFitter::processTrack().
void PHGenFit2::Fitter::processTrackPartially (PHGenFit2::Track * track, int startId = 0, int endId = -1) inline
Definition at line 35 of file Fitter.h.
View newest version in sPHENIX GitHub at line 35 of file Fitter.h
References PHGenFit2::Track::getGenFitTrack().
Referenced by PHTpcTrackFollower::followTrack().
void PHGenFit2::Fitter::processTrackPartially (genfit::Track * track, int startId = 0, int endId = -1) inline
Definition at line 39 of file Fitter.h.
View newest version in sPHENIX GitHub at line 39 of file Fitter.h
References _fitter1, genfit::Track::getCardinalRep(), and genfit::KalmanFitter::processTrackPartially().
Member Data Documentation
genfit::KalmanFitter* PHGenFit2::Fitter::_fitter1 private
Definition at line 48 of file Fitter.h.
View newest version in sPHENIX GitHub at line 48 of file Fitter.h
Referenced by Fitter(), processTrack1(), processTrackPartially(), and ~Fitter().
genfit::KalmanFitter* PHGenFit2::Fitter::_fitter5 private
Definition at line 47 of file Fitter.h.
View newest version in sPHENIX GitHub at line 47 of file Fitter.h
Referenced by Fitter(), getFitter1(), getFitter5(), processTrack5(), and ~Fitter().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/PHTpcTracker/Fitter.h
coresoftware/blob/master/offline/packages/PHTpcTracker/Fitter.cc