Analysis Software: analysis/blob/master/AndersonAnalysisModules/ColdQcdCorrelatorAnalysis/SEnergyCorrelator/macros/DoPercentDifference.C File Reference
DoPercentDifference.C File Reference
#include <iostream>
#include "TH1.h"
#include "TPad.h"
#include "TFile.h"
#include "TMath.h"
#include "TLine.h"
#include "TError.h"
#include "TString.h"
#include "TCanvas.h"
#include "TLegend.h"
#include "TPaveText.h"
Functions
static const UInt_t NModes (4)
static const UInt_t NRange (2)
static const UInt_t NComp (7)
static const UInt_t NPlot (2)
static const UInt_t NPad (2)
static const UInt_t NVtx (4)
static const UInt_t NTxt (3)
static const UInt_t FSubMode (0)
static const Bool_t DoRebin (false)
static const Bool_t DoIntNorm (true)
static const Bool_t DoFluctuationRemoval (true)
void DoPercentDifference ()
Function Documentation
static const Bool_t DoFluctuationRemoval (true) static
Referenced by DoPercentDifference().
static const Bool_t DoIntNorm (true) static
Referenced by DoPercentDifference().
void DoPercentDifference ()
Definition at line 50 of file DoPercentDifference.C.
View newest version in sPHENIX GitHub at line 50 of file DoPercentDifference.C
References AddEntry(), cd(), Close(), Data, DoFluctuationRemoval(), DoIntNorm(), DoRebin(), Draw(), FSubMode(), GetXaxis(), GetYaxis(), testing::internal::kWarning, leg, line, testing::internal::Log(), NComp(), NModes(), NPad(), NPlot(), NRange(), NTxt(), NVtx(), Reset(), SetBinContent(), SetBinError(), SetBorderMode(), SetBorderSize(), SetBottomMargin(), SetFillColor(), SetFillStyle(), SetFrameBorderMode(), SetLeftMargin(), SetLineColor(), SetLineStyle(), SetLineWidth(), SetLogy(), SetMarkerColor(), SetMarkerStyle(), SetName(), SetRightMargin(), SetTextFont(), SetTitle(), SetTopMargin(), width, and Write().
static const Bool_t DoRebin (false) static
Referenced by DoPercentDifference().
static const UInt_t FSubMode (0) static
Referenced by DoPercentDifference().
static const UInt_t NComp (7) static
Referenced by DoPercentDifference().
static const UInt_t NModes (4) static
Referenced by DoPercentDifference().
static const UInt_t NPad (2) static
Referenced by DoPercentDifference().
static const UInt_t NPlot (2) static
Referenced by DoPercentDifference().
static const UInt_t NRange (2) static
Referenced by DoPercentDifference().
static const UInt_t NTxt (3) static
Referenced by DoPercentDifference().
static const UInt_t NVtx (4) static
Referenced by DoPercentDifference().