Analysis Software: DSTTrackInfoWriter Class Reference
DSTTrackInfoWriter Class Reference
#include <coresoftware/blob/master/simulation/g4simulation/g4eval/DSTTrackInfoWriter.h>
Public Types
enum Flags { WriteEvent = 1 << 0, WriteClusters = 1 << 1, WriteTracks = 1 << 2 }
Public Member Functions
DSTTrackInfoWriter (const std::string &="DSTTrackInfoWriter")
constructor
int InitRun (PHCompositeNode *topNode) override
global initialization
int process_event (PHCompositeNode *topNode) override
event processing
void set_flags (int flags)
set flags. Should be a bitwise or of Flags enum
Public Member Functions inherited from SubsysReco
~SubsysReco () override
virtual int End (PHCompositeNode *)
Called at the end of all processing.
virtual int EndRun (const int)
Called at the end of each run.
virtual int Init (PHCompositeNode *)
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
void Print (const std::string &="ALL") const override
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Private Member Functions
int load_nodes (PHCompositeNode *)
load nodes
void evaluate_track_info ()
evaluate track info
Private Attributes
TrackInfoContainer_v1 * m_track_info_container = nullptr
int m_flags = WriteEvent | WriteClusters | WriteTracks
flags
SvtxTrackMap * m_track_map = nullptr
tracks
Additional Inherited Members
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Detailed Description
Definition at line 41 of file DSTTrackInfoWriter.h.
View newest version in sPHENIX GitHub at line 41 of file DSTTrackInfoWriter.h
Member Enumeration Documentation
enum DSTTrackInfoWriter::Flags
Enumerator:
WriteEvent
WriteClusters
WriteTracks
Definition at line 53 of file DSTTrackInfoWriter.h.
View newest version in sPHENIX GitHub at line 53 of file DSTTrackInfoWriter.h
Constructor & Destructor Documentation
DSTTrackInfoWriter::DSTTrackInfoWriter (const std::string & name = "DSTTrackInfoWriter")
constructor
Definition at line 53 of file DSTTrackInfoWriter.cc.
View newest version in sPHENIX GitHub at line 53 of file DSTTrackInfoWriter.cc
Member Function Documentation
void DSTTrackInfoWriter::evaluate_track_info () private
evaluate track info
Definition at line 160 of file DSTTrackInfoWriter.cc.
View newest version in sPHENIX GitHub at line 160 of file DSTTrackInfoWriter.cc
References TrackInfoContainer_v1::add_trackinfo(), TrackSeed::begin_cluster_keys(), TrackSeed::end_cluster_keys(), SvtxTrackInfo_v1::get_chisq(), SvtxTrackInfo_v1::get_crossing(), SvtxTrackInfo_v1::get_hitbitmap(), SvtxTrackInfo_v1::get_ndf(), SvtxTrackInfo_v1::get_z(), TrkrDefs::getLayer(), i, j, layer, m_track_info_container, m_track_map, TrackInfoContainer_v1::Reset(), SvtxTrackInfo_v1::set_chisq(), SvtxTrackInfo_v1::set_covariance(), SvtxTrackInfo_v1::set_crossing(), SvtxTrackInfo_v1::set_hitbitmap(), SvtxTrackInfo_v1::set_ndf(), SvtxTrackInfo_v1::set_px(), SvtxTrackInfo_v1::set_py(), SvtxTrackInfo_v1::set_pz(), SvtxTrackInfo_v1::set_x(), SvtxTrackInfo_v1::set_y(), SvtxTrackInfo_v1::set_z(), and Fun4AllBase::Verbosity().
Referenced by process_event().
int DSTTrackInfoWriter::InitRun (PHCompositeNode * topNode) override virtual
global initialization
Reimplemented from SubsysReco.
Definition at line 59 of file DSTTrackInfoWriter.cc.
View newest version in sPHENIX GitHub at line 59 of file DSTTrackInfoWriter.cc
References Fun4AllReturnCodes::ABORTEVENT, Fun4AllReturnCodes::EVENT_OK, PHNodeIterator::findFirst(), and Fun4AllBase::Verbosity().
int DSTTrackInfoWriter::load_nodes (PHCompositeNode * topNode) private
load nodes
Definition at line 149 of file DSTTrackInfoWriter.cc.
View newest version in sPHENIX GitHub at line 149 of file DSTTrackInfoWriter.cc
References Fun4AllReturnCodes::EVENT_OK, m_track_info_container, and m_track_map.
Referenced by process_event().
int DSTTrackInfoWriter::process_event (PHCompositeNode * topNode) override virtual
event processing
Reimplemented from SubsysReco.
Definition at line 112 of file DSTTrackInfoWriter.cc.
View newest version in sPHENIX GitHub at line 112 of file DSTTrackInfoWriter.cc
References evaluate_track_info(), Fun4AllReturnCodes::EVENT_OK, load_nodes(), m_track_info_container, TrackInfoContainer_v1::Reset(), and Fun4AllBase::Verbosity().
void DSTTrackInfoWriter::set_flags (int flags) inline
set flags. Should be a bitwise or of Flags enum
Definition at line 61 of file DSTTrackInfoWriter.h.
View newest version in sPHENIX GitHub at line 61 of file DSTTrackInfoWriter.h
References m_flags.
Member Data Documentation
int DSTTrackInfoWriter::m_flags = WriteEvent | WriteClusters | WriteTracks private
flags
Definition at line 76 of file DSTTrackInfoWriter.h.
View newest version in sPHENIX GitHub at line 76 of file DSTTrackInfoWriter.h
Referenced by set_flags().
TrackInfoContainer_v1* DSTTrackInfoWriter::m_track_info_container = nullptr private
Definition at line 73 of file DSTTrackInfoWriter.h.
View newest version in sPHENIX GitHub at line 73 of file DSTTrackInfoWriter.h
Referenced by evaluate_track_info(), load_nodes(), and process_event().
SvtxTrackMap* DSTTrackInfoWriter::m_track_map = nullptr private
tracks
Definition at line 79 of file DSTTrackInfoWriter.h.
View newest version in sPHENIX GitHub at line 79 of file DSTTrackInfoWriter.h
Referenced by evaluate_track_info(), and load_nodes().
The documentation for this class was generated from the following files:
coresoftware/blob/master/simulation/g4simulation/g4eval/DSTTrackInfoWriter.h
coresoftware/blob/master/simulation/g4simulation/g4eval/DSTTrackInfoWriter.cc