Analysis Software: analysis/blob/master/dNdEta_Run2023/analysis_INTT/src/pdgidfunc.h File Reference
pdgidfunc.h File Reference
#include <iostream>
#include <fstream>
#include <vector>
#include <string>
#include <sstream>
#include <cmath>
#include <stdio.h>
Enumerations
enum Location {
Nj = 1, Nq3 = 2, Nq2 = 3, Nq1 = 4,
Nl = 5, Nr = 6, N = 7, N8 = 8,
N9 = 9, N10 = 10
}
Functions
int abspid (int pdgid)
int _digit (int pdgid, int loc)
int _extra_bits (int pdgid)
int _fundamental_id (int pdgid)
bool is_quark (int pdgid)
bool is_meson (int pdgid)
bool is_baryon (int pdgid)
bool is_SUSY (int pdgid)
bool is_Rhadron (int pdgid)
bool is_hadron (int pdgid)
int A (int pdgid)
int Z (int pdgid)
bool is_nucleus (int pdgid)
bool is_Qball (int pdgid)
bool is_dyon (int pdgid)
bool is_diquark (int pdgid)
bool is_generator_specific (int pdgid)
bool is_technicolor (int pdgid)
bool is_excited_quark_or_lepton (int pdgid)
bool is_gauge_boson_or_higgs (int pdgid)
bool is_pentaquark (int pdgid)
bool is_valid (int pdgid)
int three_charge (int pdgid)
float charge (int pdgid)
bool is_chargedHadron (int pdgid)
Enumeration Type Documentation
enum Location
Enumerator:
Nj
Nq3
Nq2
Nq1
Nl
Nr
N
N8
N9
N10
Definition at line 14 of file pdgidfunc.h.
View newest version in sPHENIX GitHub at line 14 of file pdgidfunc.h
Function Documentation
int _digit (int pdgid, int loc)
Definition at line 32 of file pdgidfunc.h.
View newest version in sPHENIX GitHub at line 32 of file pdgidfunc.h
References abspid(), loc, Jetscape::sid, and to_string().
Referenced by _fundamental_id(), A(), is_baryon(), is_diquark(), is_dyon(), is_excited_quark_or_lepton(), is_meson(), is_nucleus(), is_pentaquark(), is_Qball(), is_Rhadron(), is_SUSY(), is_technicolor(), three_charge(), and Z().
int _extra_bits (int pdgid)
Definition at line 40 of file pdgidfunc.h.
View newest version in sPHENIX GitHub at line 40 of file pdgidfunc.h
References abspid().
Referenced by _fundamental_id(), is_baryon(), is_diquark(), is_dyon(), is_excited_quark_or_lepton(), is_hadron(), is_meson(), is_pentaquark(), is_Qball(), is_Rhadron(), is_SUSY(), is_technicolor(), is_valid(), and three_charge().
int _fundamental_id (int pdgid)
Definition at line 45 of file pdgidfunc.h.
View newest version in sPHENIX GitHub at line 45 of file pdgidfunc.h
References _digit(), _extra_bits(), and abspid().
Referenced by is_baryon(), is_diquark(), is_excited_quark_or_lepton(), is_meson(), is_SUSY(), is_valid(), and three_charge().
int A (int pdgid)
Definition at line 210 of file pdgidfunc.h.
View newest version in sPHENIX GitHub at line 210 of file pdgidfunc.h
References _digit(), and abspid().
int abspid (int pdgid)
Definition at line 28 of file pdgidfunc.h.
View newest version in sPHENIX GitHub at line 28 of file pdgidfunc.h
Referenced by _digit(), _extra_bits(), _fundamental_id(), A(), is_baryon(), is_diquark(), is_generator_specific(), is_meson(), is_nucleus(), is_Qball(), is_quark(), three_charge(), and Z().
float charge (int pdgid)
Definition at line 588 of file pdgidfunc.h.
View newest version in sPHENIX GitHub at line 588 of file pdgidfunc.h
References is_Qball(), and three_charge().
Referenced by Acts::Python::addGenerators(), ana_hijbkg(), AnalyzeResiduals(), Acts::Test::BOOST_AUTO_TEST_CASE(), BOOST_AUTO_TEST_CASE(), Acts::Test::BOOST_DATA_TEST_CASE(), PHTruthSiliconAssociation::buildTrackSeed(), PHTruthTrackSeeding::buildTrackSeed(), DVMPHelper::calculateInvariantMass_1(), DVMPHelper::calculateInvariantMass_3(), DVMPHelper::calculateInvariantMass_4(), Acts::MultiEigenStepperLoop< extensionlist_t, component_reducer_t, auctioneer_t >::charge(), DISKinematicsReco::CollectEmCandidatesFromTruth(), FieldMapsLaplace::ComputeE(), ActsExamples::ParticleTrackingAction::convert(), genfit::EventDisplay::drawEvent(), EMCalCalib::eval_photon(), EMCalAna::eval_trk(), ActsExamples::PropagationAlgorithm::execute(), genfit::RKTrackRep::extrapolateBy(), genfit::RKTrackRep::extrapolateToCone(), genfit::RKTrackRep::extrapolateToCylinder(), genfit::RKTrackRep::extrapolateToLine(), genfit::RKTrackRep::extrapolateToSphere(), genfit::RKTrackRep::extrapToPoint(), psTOFTimezeroEval::fillOutputNtuples(), SvtxEvaluatorHaiwang::fillOutputNtuples(), TrkrNtuplizer::fillOutputNtuples(), SvtxEvaluator::fillOutputNtuples(), DVMPHelper::find_positron(), Acts::findCharge(), Fun4All_EMCalLikelihood(), PHGenFit::Track::get_charge(), SecondaryVertexFinder::getCircleXYTrack(), TrackSeedTrackMapConverter::getCosmicCharge(), SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::GetNumFinalStatePars(), SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::GetParticleCharge(), SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::GetParticleCharge(), DVMPHelper::GetParticleReco(), SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::GetSumFinalStateParEne(), STrackCutStudy::InitTuples(), is_chargedHadron(), IsNeutralBaryon(), IsNeutralMeson(), ActsExamples::DigitizationAlgorithm::localParameters(), PHCosmicsTrkFitter::loopTracks(), PHActsTrkFitter::loopTracks(), main(), PHActsGSF::makeSeed(), ActsExamples::Pythia8Generator::operator()(), PHSiliconTruthTrackSeeding::Process(), TrackSeedTrackMapConverter::process_event(), MBDStudy::process_event(), MbdDigitization::process_event(), BBCStudy::process_event(), ElectronID::process_event(), PairMaker::process_event_test(), sPHAnalysis::process_event_test(), sPHAnalysis::process_event_upsilons(), genfit::KalmanFitterRefTrack::processTrackWithRep(), genfit::KalmanFitter::processTrackWithRep(), project_quarkonium_mass(), EMCalTrk::Reset(), MCPhoton::Reset(), SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::ParInfo::Reset(), Acts::Test::runTest(), genfit::TrackCand::set6DSeed(), MbdOutV2::set_arm(), BbcOutV2::set_arm(), BbcOutV1::set_arm(), MbdOutV1::set_arm(), sPHElectronv1::set_charge(), genfit::FitStatus::setCharge(), SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::ParInfo::SetInfo(), genfit::TrackCand::setPosMomSeed(), three_charge(), and PHG4ZDCSteppingAction::UserSteppingAction().
bool is_baryon (int pdgid)
Definition at line 111 of file pdgidfunc.h.
View newest version in sPHENIX GitHub at line 111 of file pdgidfunc.h
References _digit(), _extra_bits(), _fundamental_id(), and abspid().
Referenced by is_chargedHadron(), is_hadron(), is_valid(), and three_charge().
bool is_chargedHadron (int pdgid)
Definition at line 603 of file pdgidfunc.h.
View newest version in sPHENIX GitHub at line 603 of file pdgidfunc.h
References charge(), is_baryon(), is_hadron(), and is_meson().
Referenced by main().
bool is_diquark (int pdgid)
Definition at line 333 of file pdgidfunc.h.
View newest version in sPHENIX GitHub at line 333 of file pdgidfunc.h
References _digit(), _extra_bits(), _fundamental_id(), and abspid().
Referenced by is_valid().
bool is_dyon (int pdgid)
Definition at line 304 of file pdgidfunc.h.
View newest version in sPHENIX GitHub at line 304 of file pdgidfunc.h
References _digit(), _extra_bits(), N, and Nr.
Referenced by is_valid(), and three_charge().
bool is_excited_quark_or_lepton (int pdgid)
Definition at line 385 of file pdgidfunc.h.
View newest version in sPHENIX GitHub at line 385 of file pdgidfunc.h
References _digit(), _extra_bits(), _fundamental_id(), N, and Nr.
Referenced by is_valid().
bool is_gauge_boson_or_higgs (int pdgid)
Definition at line 399 of file pdgidfunc.h.
View newest version in sPHENIX GitHub at line 399 of file pdgidfunc.h
References false.
Referenced by is_valid().
bool is_generator_specific (int pdgid)
Definition at line 351 of file pdgidfunc.h.
View newest version in sPHENIX GitHub at line 351 of file pdgidfunc.h
References abspid().
Referenced by is_valid().
bool is_hadron (int pdgid)
Definition at line 190 of file pdgidfunc.h.
View newest version in sPHENIX GitHub at line 190 of file pdgidfunc.h
References _extra_bits(), is_baryon(), is_meson(), and is_Rhadron().
Referenced by is_chargedHadron().
bool is_meson (int pdgid)
Definition at line 68 of file pdgidfunc.h.
View newest version in sPHENIX GitHub at line 68 of file pdgidfunc.h
References _digit(), _extra_bits(), _fundamental_id(), and abspid().
Referenced by is_chargedHadron(), is_hadron(), and is_valid().
bool is_nucleus (int pdgid)
Definition at line 255 of file pdgidfunc.h.
View newest version in sPHENIX GitHub at line 255 of file pdgidfunc.h
References _digit(), A, abspid(), and SVM_v1::Z.
Referenced by is_valid(), and three_charge().
bool is_pentaquark (int pdgid)
Definition at line 409 of file pdgidfunc.h.
View newest version in sPHENIX GitHub at line 409 of file pdgidfunc.h
References _digit(), _extra_bits(), N, and Nr.
Referenced by is_valid(), and three_charge().
bool is_Qball (int pdgid)
Definition at line 284 of file pdgidfunc.h.
View newest version in sPHENIX GitHub at line 284 of file pdgidfunc.h
References _digit(), _extra_bits(), abspid(), N, and Nr.
Referenced by charge(), is_valid(), and three_charge().
bool is_quark (int pdgid)
Definition at line 63 of file pdgidfunc.h.
View newest version in sPHENIX GitHub at line 63 of file pdgidfunc.h
References abspid().
bool is_Rhadron (int pdgid)
Definition at line 169 of file pdgidfunc.h.
View newest version in sPHENIX GitHub at line 169 of file pdgidfunc.h
References _digit(), _extra_bits(), is_SUSY(), N, and Nr.
Referenced by is_hadron(), is_valid(), and three_charge().
bool is_SUSY (int pdgid)
Definition at line 154 of file pdgidfunc.h.
View newest version in sPHENIX GitHub at line 154 of file pdgidfunc.h
References _digit(), _extra_bits(), _fundamental_id(), N, and Nr.
Referenced by is_Rhadron(), and is_valid().
bool is_technicolor (int pdgid)
Definition at line 377 of file pdgidfunc.h.
View newest version in sPHENIX GitHub at line 377 of file pdgidfunc.h
References _digit(), _extra_bits(), and N.
Referenced by is_valid().
bool is_valid (int pdgid)
Definition at line 443 of file pdgidfunc.h.
View newest version in sPHENIX GitHub at line 443 of file pdgidfunc.h
References _extra_bits(), _fundamental_id(), is_baryon(), is_diquark(), is_dyon(), is_excited_quark_or_lepton(), is_gauge_boson_or_higgs(), is_generator_specific(), is_meson(), is_nucleus(), is_pentaquark(), is_Qball(), is_Rhadron(), is_SUSY(), and is_technicolor().
Referenced by PHCosmicsTrkFitter::loopTracks(), PHActsTrkFitter::loopTracks(), and three_charge().
int three_charge (int pdgid)
Definition at line 487 of file pdgidfunc.h.
View newest version in sPHENIX GitHub at line 487 of file pdgidfunc.h
References _digit(), _extra_bits(), _fundamental_id(), abspid(), charge(), is_baryon(), is_dyon(), is_nucleus(), is_pentaquark(), is_Qball(), is_Rhadron(), is_valid(), Jetscape::sid, and SVM_v1::Z.
Referenced by charge().
int Z (int pdgid)
Definition at line 230 of file pdgidfunc.h.
View newest version in sPHENIX GitHub at line 230 of file pdgidfunc.h
References _digit(), and abspid().