Analysis Software: CMFlashCluster Class Reference
CMFlashCluster Class Reference
Base class for Central Membrane flassh combined cluster object.
#include <coresoftware/blob/master/offline/packages/trackbase/CMFlashCluster.h>
Public Member Functions
~CMFlashCluster () override
dtor
void identify (std::ostream &os=std::cout) const override
void Reset () override
Clear Event.
int isValid () const override
isValid returns non zero if object contains vailid data
virtual void CopyFrom (const CMFlashCluster &)
copy content from base class
virtual void CopyFrom (CMFlashCluster *)
copy content from base class
virtual float getX () const
virtual void setX (float)
virtual float getY () const
virtual void setY (float)
virtual float getZ () const
virtual void setZ (float)
virtual float getX1 () const
virtual void setX1 (float)
virtual float getY1 () const
virtual void setY1 (float)
virtual float getZ1 () const
virtual void setZ1 (float)
virtual float getX2 () const
virtual void setX2 (float)
virtual float getY2 () const
virtual void setY2 (float)
virtual float getZ2 () const
virtual void setZ2 (float)
virtual void setLayer1 (unsigned int)
virtual unsigned int getLayer1 () const
virtual void setLayer2 (unsigned int)
virtual unsigned int getLayer2 () const
virtual void setAdc (unsigned int)
virtual unsigned int getAdc () const
virtual void setAdc1 (unsigned int)
virtual unsigned int getAdc1 () const
virtual void setAdc2 (unsigned int)
virtual unsigned int getAdc2 () const
virtual unsigned int getNclusters () const
virtual void setNclusters (unsigned int)
virtual void setIsRGap (bool)
virtual bool getIsRGap () const
virtual void setIsPhiGap (bool)
virtual bool getIsPhiGap () const
Public Member Functions inherited from PHObject
PHObject ()
ctor
~PHObject () override
dtor
virtual PHObject * CloneMe () const
Virtual copy constructor.
virtual PHObject * clone () const final
PHObject * Clone (const char *newname="") const final
void Copy (TObject &object) const final
virtual int Integrate () const
virtual int Integrate (PHObject *)
virtual void CopyFrom (const PHObject *obj)
Protected Member Functions
CMFlashCluster ()=default
Detailed Description
Base class for Central Membrane flassh combined cluster object.
Virtual base class for TPC CM flash cluster object
Definition at line 23 of file CMFlashCluster.h.
View newest version in sPHENIX GitHub at line 23 of file CMFlashCluster.h
Constructor & Destructor Documentation
CMFlashCluster::~CMFlashCluster () inline override
dtor
Definition at line 27 of file CMFlashCluster.h.
View newest version in sPHENIX GitHub at line 27 of file CMFlashCluster.h
CMFlashCluster::CMFlashCluster () protected default
Member Function Documentation
virtual void CMFlashCluster::CopyFrom (const CMFlashCluster &) inline virtual
copy content from base class
Reimplemented in CMFlashClusterv2, CMFlashClusterv1, and CMFlashClusterv3.
Definition at line 41 of file CMFlashCluster.h.
View newest version in sPHENIX GitHub at line 41 of file CMFlashCluster.h
Referenced by CMFlashClusterv3::CopyFrom(), CMFlashClusterv1::CopyFrom(), and CMFlashClusterv2::CopyFrom().
virtual void CMFlashCluster::CopyFrom (CMFlashCluster *) inline virtual
copy content from base class
Reimplemented in CMFlashClusterv2, CMFlashClusterv1, and CMFlashClusterv3.
Definition at line 44 of file CMFlashCluster.h.
View newest version in sPHENIX GitHub at line 44 of file CMFlashCluster.h
virtual unsigned int CMFlashCluster::getAdc () const inline virtual
Reimplemented in CMFlashClusterv3, CMFlashClusterv2, and CMFlashClusterv1.
Definition at line 81 of file CMFlashCluster.h.
View newest version in sPHENIX GitHub at line 81 of file CMFlashCluster.h
Referenced by CMFlashClusterv3::CopyFrom(), CMFlashClusterv1::CopyFrom(), CMFlashClusterv2::CopyFrom(), and PHTpcCentralMembraneMatcher::process_event().
virtual unsigned int CMFlashCluster::getAdc1 () const inline virtual
Reimplemented in CMFlashClusterv3.
Definition at line 85 of file CMFlashCluster.h.
View newest version in sPHENIX GitHub at line 85 of file CMFlashCluster.h
Referenced by CMFlashClusterv3::CopyFrom(), and PHTpcCentralMembraneMatcher::process_event().
virtual unsigned int CMFlashCluster::getAdc2 () const inline virtual
Reimplemented in CMFlashClusterv3.
Definition at line 88 of file CMFlashCluster.h.
View newest version in sPHENIX GitHub at line 88 of file CMFlashCluster.h
Referenced by CMFlashClusterv3::CopyFrom(), and PHTpcCentralMembraneMatcher::process_event().
virtual bool CMFlashCluster::getIsPhiGap () const inline virtual
Reimplemented in CMFlashClusterv3, and CMFlashClusterv2.
Definition at line 95 of file CMFlashCluster.h.
View newest version in sPHENIX GitHub at line 95 of file CMFlashCluster.h
Referenced by CMFlashClusterv3::CopyFrom(), and CMFlashClusterv2::CopyFrom().
virtual bool CMFlashCluster::getIsRGap () const inline virtual
Reimplemented in CMFlashClusterv3, and CMFlashClusterv2.
Definition at line 93 of file CMFlashCluster.h.
View newest version in sPHENIX GitHub at line 93 of file CMFlashCluster.h
Referenced by CMFlashClusterv3::CopyFrom(), CMFlashClusterv2::CopyFrom(), and PHTpcCentralMembraneMatcher::process_event().
virtual unsigned int CMFlashCluster::getLayer1 () const inline virtual
Reimplemented in CMFlashClusterv3.
Definition at line 72 of file CMFlashCluster.h.
View newest version in sPHENIX GitHub at line 72 of file CMFlashCluster.h
Referenced by CMFlashClusterv3::CopyFrom(), and PHTpcCentralMembraneMatcher::process_event().
virtual unsigned int CMFlashCluster::getLayer2 () const inline virtual
Reimplemented in CMFlashClusterv3.
Definition at line 75 of file CMFlashCluster.h.
View newest version in sPHENIX GitHub at line 75 of file CMFlashCluster.h
Referenced by CMFlashClusterv3::CopyFrom(), and PHTpcCentralMembraneMatcher::process_event().
virtual unsigned int CMFlashCluster::getNclusters () const inline virtual
Reimplemented in CMFlashClusterv3, CMFlashClusterv2, and CMFlashClusterv1.
Definition at line 90 of file CMFlashCluster.h.
View newest version in sPHENIX GitHub at line 90 of file CMFlashCluster.h
Referenced by PHTpcCentralMembraneMatcher::process_event().
virtual float CMFlashCluster::getX () const inline virtual
Reimplemented in CMFlashClusterv2, CMFlashClusterv1, and CMFlashClusterv3.
Definition at line 49 of file CMFlashCluster.h.
View newest version in sPHENIX GitHub at line 49 of file CMFlashCluster.h
Referenced by CMFlashClusterv3::CopyFrom(), CMFlashClusterv1::CopyFrom(), CMFlashClusterv2::CopyFrom(), and PHTpcCentralMembraneMatcher::process_event().
virtual float CMFlashCluster::getX1 () const inline virtual
Reimplemented in CMFlashClusterv3.
Definition at line 56 of file CMFlashCluster.h.
View newest version in sPHENIX GitHub at line 56 of file CMFlashCluster.h
Referenced by CMFlashClusterv3::CopyFrom(), and PHTpcCentralMembraneMatcher::process_event().
virtual float CMFlashCluster::getX2 () const inline virtual
Reimplemented in CMFlashClusterv3.
Definition at line 63 of file CMFlashCluster.h.
View newest version in sPHENIX GitHub at line 63 of file CMFlashCluster.h
Referenced by CMFlashClusterv3::CopyFrom(), and PHTpcCentralMembraneMatcher::process_event().
virtual float CMFlashCluster::getY () const inline virtual
Reimplemented in CMFlashClusterv2, CMFlashClusterv1, and CMFlashClusterv3.
Definition at line 51 of file CMFlashCluster.h.
View newest version in sPHENIX GitHub at line 51 of file CMFlashCluster.h
Referenced by CMFlashClusterv3::CopyFrom(), CMFlashClusterv1::CopyFrom(), CMFlashClusterv2::CopyFrom(), and PHTpcCentralMembraneMatcher::process_event().
virtual float CMFlashCluster::getY1 () const inline virtual
Reimplemented in CMFlashClusterv3.
Definition at line 58 of file CMFlashCluster.h.
View newest version in sPHENIX GitHub at line 58 of file CMFlashCluster.h
Referenced by CMFlashClusterv3::CopyFrom(), and PHTpcCentralMembraneMatcher::process_event().
virtual float CMFlashCluster::getY2 () const inline virtual
Reimplemented in CMFlashClusterv3.
Definition at line 65 of file CMFlashCluster.h.
View newest version in sPHENIX GitHub at line 65 of file CMFlashCluster.h
Referenced by CMFlashClusterv3::CopyFrom(), and PHTpcCentralMembraneMatcher::process_event().
virtual float CMFlashCluster::getZ () const inline virtual
Reimplemented in CMFlashClusterv2, CMFlashClusterv1, and CMFlashClusterv3.
Definition at line 53 of file CMFlashCluster.h.
View newest version in sPHENIX GitHub at line 53 of file CMFlashCluster.h
Referenced by CMFlashClusterv3::CopyFrom(), CMFlashClusterv1::CopyFrom(), CMFlashClusterv2::CopyFrom(), and PHTpcCentralMembraneMatcher::process_event().
virtual float CMFlashCluster::getZ1 () const inline virtual
Reimplemented in CMFlashClusterv3.
Definition at line 60 of file CMFlashCluster.h.
View newest version in sPHENIX GitHub at line 60 of file CMFlashCluster.h
Referenced by CMFlashClusterv3::CopyFrom(), and PHTpcCentralMembraneMatcher::process_event().
virtual float CMFlashCluster::getZ2 () const inline virtual
Reimplemented in CMFlashClusterv3.
Definition at line 67 of file CMFlashCluster.h.
View newest version in sPHENIX GitHub at line 67 of file CMFlashCluster.h
Referenced by CMFlashClusterv3::CopyFrom(), and PHTpcCentralMembraneMatcher::process_event().
void CMFlashCluster::identify (std::ostream & os = std::cout) const inline override virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from PHObject.
Reimplemented in CMFlashClusterv2, CMFlashClusterv1, and CMFlashClusterv3.
Definition at line 29 of file CMFlashCluster.h.
View newest version in sPHENIX GitHub at line 29 of file CMFlashCluster.h
References os.
int CMFlashCluster::isValid () const inline override virtual
isValid returns non zero if object contains vailid data
Reimplemented from PHObject.
Reimplemented in CMFlashClusterv2, CMFlashClusterv1, and CMFlashClusterv3.
Definition at line 34 of file CMFlashCluster.h.
View newest version in sPHENIX GitHub at line 34 of file CMFlashCluster.h
void CMFlashCluster::Reset () inline override virtual
Clear Event.
Reimplemented from PHObject.
Reimplemented in CMFlashClusterv2, CMFlashClusterv1, and CMFlashClusterv3.
Definition at line 33 of file CMFlashCluster.h.
View newest version in sPHENIX GitHub at line 33 of file CMFlashCluster.h
virtual void CMFlashCluster::setAdc (unsigned int) inline virtual
Reimplemented in CMFlashClusterv3, CMFlashClusterv2, and CMFlashClusterv1.
Definition at line 80 of file CMFlashCluster.h.
View newest version in sPHENIX GitHub at line 80 of file CMFlashCluster.h
virtual void CMFlashCluster::setAdc1 (unsigned int) inline virtual
Reimplemented in CMFlashClusterv3.
Definition at line 84 of file CMFlashCluster.h.
View newest version in sPHENIX GitHub at line 84 of file CMFlashCluster.h
virtual void CMFlashCluster::setAdc2 (unsigned int) inline virtual
Reimplemented in CMFlashClusterv3.
Definition at line 87 of file CMFlashCluster.h.
View newest version in sPHENIX GitHub at line 87 of file CMFlashCluster.h
virtual void CMFlashCluster::setIsPhiGap (bool) inline virtual
Reimplemented in CMFlashClusterv3, and CMFlashClusterv2.
Definition at line 94 of file CMFlashCluster.h.
View newest version in sPHENIX GitHub at line 94 of file CMFlashCluster.h
virtual void CMFlashCluster::setIsRGap (bool) inline virtual
Reimplemented in CMFlashClusterv3, and CMFlashClusterv2.
Definition at line 92 of file CMFlashCluster.h.
View newest version in sPHENIX GitHub at line 92 of file CMFlashCluster.h
virtual void CMFlashCluster::setLayer1 (unsigned int) inline virtual
Reimplemented in CMFlashClusterv3.
Definition at line 71 of file CMFlashCluster.h.
View newest version in sPHENIX GitHub at line 71 of file CMFlashCluster.h
virtual void CMFlashCluster::setLayer2 (unsigned int) inline virtual
Reimplemented in CMFlashClusterv3.
Definition at line 74 of file CMFlashCluster.h.
View newest version in sPHENIX GitHub at line 74 of file CMFlashCluster.h
virtual void CMFlashCluster::setNclusters (unsigned int) inline virtual
Reimplemented in CMFlashClusterv3, CMFlashClusterv2, and CMFlashClusterv1.
Definition at line 91 of file CMFlashCluster.h.
View newest version in sPHENIX GitHub at line 91 of file CMFlashCluster.h
virtual void CMFlashCluster::setX (float) inline virtual
Reimplemented in CMFlashClusterv2, CMFlashClusterv1, and CMFlashClusterv3.
Definition at line 50 of file CMFlashCluster.h.
View newest version in sPHENIX GitHub at line 50 of file CMFlashCluster.h
virtual void CMFlashCluster::setX1 (float) inline virtual
Reimplemented in CMFlashClusterv3.
Definition at line 57 of file CMFlashCluster.h.
View newest version in sPHENIX GitHub at line 57 of file CMFlashCluster.h
virtual void CMFlashCluster::setX2 (float) inline virtual
Reimplemented in CMFlashClusterv3.
Definition at line 64 of file CMFlashCluster.h.
View newest version in sPHENIX GitHub at line 64 of file CMFlashCluster.h
virtual void CMFlashCluster::setY (float) inline virtual
Reimplemented in CMFlashClusterv2, CMFlashClusterv1, and CMFlashClusterv3.
Definition at line 52 of file CMFlashCluster.h.
View newest version in sPHENIX GitHub at line 52 of file CMFlashCluster.h
virtual void CMFlashCluster::setY1 (float) inline virtual
Reimplemented in CMFlashClusterv3.
Definition at line 59 of file CMFlashCluster.h.
View newest version in sPHENIX GitHub at line 59 of file CMFlashCluster.h
virtual void CMFlashCluster::setY2 (float) inline virtual
Reimplemented in CMFlashClusterv3.
Definition at line 66 of file CMFlashCluster.h.
View newest version in sPHENIX GitHub at line 66 of file CMFlashCluster.h
virtual void CMFlashCluster::setZ (float) inline virtual
Reimplemented in CMFlashClusterv2, CMFlashClusterv1, and CMFlashClusterv3.
Definition at line 54 of file CMFlashCluster.h.
View newest version in sPHENIX GitHub at line 54 of file CMFlashCluster.h
virtual void CMFlashCluster::setZ1 (float) inline virtual
Reimplemented in CMFlashClusterv3.
Definition at line 61 of file CMFlashCluster.h.
View newest version in sPHENIX GitHub at line 61 of file CMFlashCluster.h
virtual void CMFlashCluster::setZ2 (float) inline virtual
Reimplemented in CMFlashClusterv3.
Definition at line 68 of file CMFlashCluster.h.
View newest version in sPHENIX GitHub at line 68 of file CMFlashCluster.h
The documentation for this class was generated from the following file:
coresoftware/blob/master/offline/packages/trackbase/CMFlashCluster.h