Analysis Software: analysis/blob/master/EICAnalysis/macros/leptoquarks_fun4all/G4_HcalOut_ref.C File Reference
G4_HcalOut_ref.C File Reference
Enumerations
enum enu_HCalOut_clusterizer { kHCalOutGraphClusterizer, kHCalOutTemplateClusterizer }
Functions
void HCalOuterInit ()
graph clusterizer, RawClusterBuilderGraph
double HCalOuter (PHG4Reco *g4Reco, double radius, const int crossings, const int absorberactive=0, int verbosity=0)
void HCALOuter_Cells (int verbosity=0)
void HCALOuter_Towers (int verbosity=0)
void HCALOuter_Clusters (int verbosity=0)
void HCALOuter_Eval (std::string outputfile, int verbosity=0)
Variables
enu_HCalOut_clusterizer HCalOut_clusterizer = kHCalOutTemplateClusterizer
template clusterizer, RawClusterBuilderTemplate, as developed by Sasha Bazilevsky
Enumeration Type Documentation
enum enu_HCalOut_clusterizer
Enumerator:
kHCalOutGraphClusterizer
kHCalOutTemplateClusterizer
Definition at line 3 of file G4_HcalOut_ref.C.
View newest version in sPHENIX GitHub at line 3 of file G4_HcalOut_ref.C
Function Documentation
double HCalOuter (PHG4Reco * g4Reco, double radius, const int crossings, const int absorberactive = 0, int verbosity = 0)
Definition at line 18 of file G4_HcalOut_ref.C.
View newest version in sPHENIX GitHub at line 18 of file G4_HcalOut_ref.C
References PHG4DetectorSubsystem::get_double_param(), no_overlapp, overlapcheck, PHG4DetectorSubsystem::OverlapCheck(), PHG4Reco::registerSubsystem(), PHG4DetectorSubsystem::SetAbsorberActive(), PHG4DetectorSubsystem::SetActive(), and PHG4DetectorSubsystem::SuperDetector().
Referenced by G4Setup().
void HCALOuter_Cells (int verbosity = 0)
Definition at line 82 of file G4_HcalOut_ref.C.
View newest version in sPHENIX GitHub at line 82 of file G4_HcalOut_ref.C
References PHG4HcalCellReco::Detector(), Fun4AllServer::instance(), and Fun4AllServer::registerSubsystem().
Referenced by ConfigureDetectors(), Fun4All_AnaTutorial_sPHENIX(), Fun4All_AnaTutorial_sPHENIX_Jets(), Fun4All_G4_Calo(), Fun4All_G4_EICDetector_AnaTutorial(), Fun4All_G4_EICDetector_LQ(), Fun4All_G4_EICDetector_LQ_reference(), Fun4All_G4_EICDetector_RICH(), Fun4All_G4_fsPHENIX_FastSim(), Fun4All_G4_fsPHENIX_pi0(), Fun4All_G4_sPHENIX(), Fun4All_G4_sPHENIX_AnaGenFit(), Fun4All_G4_sPHENIX_ForTrackCutStudy(), Fun4All_G4_sPHENIX_ForTrackCutStudy_EmbedScanOff(), Fun4All_G4_sPHENIX_ForTrackCutStudy_EmbedScanOn(), Fun4All_G4_sPHENIX_ForTrackCutStudy_WithPileup_EmbedScanOff(), Fun4All_G4_sPHENIX_ForTrackCutStudy_WithPileup_EmbedScanOn(), Fun4All_G4_sPHENIX_photonjet(), Fun4All_G4_sPHENIX_photons(), Fun4All_G4_sPHENIX_truthphotonjet(), Fun4All_HCalJetPhiShift(), Fun4All_Pi0Gen_sPHENIX(), Fun4All_pi0tbt_SIMPLE_EMBED(), Fun4All_RunNewTruthMatcher(), Fun4All_single_particle(), Fun4All_SinglePhotonGen_sPHENIX(), Fun4All_SinglePi0Gen_sPHENIX(), Jin_BJet(), run_calo_fromMDC2Hits_towslope_Fun4All_G4_Calo(), rundst_spiNo(), spiNo2(), and Wrapper().
void HCALOuter_Clusters (int verbosity = 0)
Definition at line 144 of file G4_HcalOut_ref.C.
View newest version in sPHENIX GitHub at line 144 of file G4_HcalOut_ref.C
References RawClusterBuilderGraph::Detector(), RawClusterBuilderTemplate::Detector(), HCalOut_clusterizer, Fun4AllServer::instance(), kHCalOutGraphClusterizer, kHCalOutTemplateClusterizer, Fun4AllServer::registerSubsystem(), verbosity, and Fun4AllBase::Verbosity().
Referenced by ConfigureDetectors(), Fun4All_AnaTutorial_sPHENIX(), Fun4All_AnaTutorial_sPHENIX_Jets(), Fun4All_G4_Calo(), Fun4All_G4_EICDetector_AnaTutorial(), Fun4All_G4_EICDetector_LQ(), Fun4All_G4_EICDetector_LQ_reference(), Fun4All_G4_EICDetector_RICH(), Fun4All_G4_fsPHENIX_FastSim(), Fun4All_G4_fsPHENIX_pi0(), Fun4All_G4_sPHENIX(), Fun4All_G4_sPHENIX_AnaGenFit(), Fun4All_G4_sPHENIX_ForTrackCutStudy(), Fun4All_G4_sPHENIX_ForTrackCutStudy_EmbedScanOff(), Fun4All_G4_sPHENIX_ForTrackCutStudy_EmbedScanOn(), Fun4All_G4_sPHENIX_ForTrackCutStudy_WithPileup_EmbedScanOff(), Fun4All_G4_sPHENIX_ForTrackCutStudy_WithPileup_EmbedScanOn(), Fun4All_G4_sPHENIX_photonjet(), Fun4All_G4_sPHENIX_photons(), Fun4All_G4_sPHENIX_truthphotonjet(), Fun4All_HCalJetPhiShift(), Fun4All_Pi0Gen_sPHENIX(), Fun4All_pi0tbt_SIMPLE_EMBED(), Fun4All_RunNewTruthMatcher(), Fun4All_single_particle(), Fun4All_SinglePhotonGen_sPHENIX(), Fun4All_SinglePi0Gen_sPHENIX(), Jin_BJet(), run_calo_fromMDC2Hits_towslope_Fun4All_G4_Calo(), rundst_spiNo(), spiNo2(), and Wrapper().
void HCALOuter_Eval (std::string outputfile, int verbosity = 0)
Definition at line 174 of file G4_HcalOut_ref.C.
View newest version in sPHENIX GitHub at line 174 of file G4_HcalOut_ref.C
References Fun4AllServer::instance(), Fun4AllServer::registerSubsystem(), verbosity, and Fun4AllBase::Verbosity().
Referenced by ConfigureDetectors(), Fun4All_AnaTutorial_sPHENIX(), Fun4All_AnaTutorial_sPHENIX_Jets(), Fun4All_G4_EICDetector_AnaTutorial(), Fun4All_G4_EICDetector_LQ_reference(), Fun4All_G4_EICDetector_RICH(), Fun4All_G4_fsPHENIX_FastSim(), Fun4All_G4_fsPHENIX_pi0(), Fun4All_G4_sPHENIX(), Fun4All_G4_sPHENIX_AnaGenFit(), Fun4All_G4_sPHENIX_ForTrackCutStudy(), Fun4All_G4_sPHENIX_ForTrackCutStudy_EmbedScanOff(), Fun4All_G4_sPHENIX_ForTrackCutStudy_EmbedScanOn(), Fun4All_G4_sPHENIX_ForTrackCutStudy_WithPileup_EmbedScanOff(), Fun4All_G4_sPHENIX_ForTrackCutStudy_WithPileup_EmbedScanOn(), Fun4All_G4_sPHENIX_photonjet(), Fun4All_G4_sPHENIX_photons(), Fun4All_G4_sPHENIX_truthphotonjet(), Fun4All_Pi0Gen_sPHENIX(), Fun4All_pi0tbt_SIMPLE_EMBED(), Fun4All_RunNewTruthMatcher(), Fun4All_single_particle(), Fun4All_SinglePhotonGen_sPHENIX(), Fun4All_SinglePi0Gen_sPHENIX(), Jin_BJet(), and Wrapper().
void HCALOuter_Towers (int verbosity = 0)
Definition at line 104 of file G4_HcalOut_ref.C.
View newest version in sPHENIX GitHub at line 104 of file G4_HcalOut_ref.C
References HcalRawTowerBuilder::Detector(), RawTowerCalibration::Detector(), RawTowerDigitizer::Detector(), Acts::UnitConstants::e, Fun4AllServer::instance(), RawTowerCalibration::kSimple_linear_calibration, RawTowerDigitizer::kSimple_photon_digitalization, Fun4AllServer::registerSubsystem(), RawTowerCalibration::set_calib_algorithm(), RawTowerCalibration::set_calib_const_GeV_ADC(), RawTowerDigitizer::set_digi_algorithm(), RawTowerCalibration::set_pedstal_ADC(), RawTowerDigitizer::set_pedstal_central_ADC(), RawTowerDigitizer::set_pedstal_width_ADC(), RawTowerDigitizer::set_photonelec_ADC(), RawTowerDigitizer::set_photonelec_yield_visible_GeV(), HcalRawTowerBuilder::set_sim_tower_node_prefix(), RawTowerDigitizer::set_zero_suppression_ADC(), RawTowerCalibration::set_zero_suppression_GeV(), verbosity, and Fun4AllBase::Verbosity().
Referenced by ConfigureDetectors(), Fun4All_AnaTutorial_sPHENIX(), Fun4All_AnaTutorial_sPHENIX_Jets(), Fun4All_G4_Calo(), Fun4All_G4_EICDetector_AnaTutorial(), Fun4All_G4_EICDetector_LQ(), Fun4All_G4_EICDetector_LQ_reference(), Fun4All_G4_EICDetector_RICH(), Fun4All_G4_fsPHENIX_FastSim(), Fun4All_G4_fsPHENIX_pi0(), Fun4All_G4_sPHENIX(), Fun4All_G4_sPHENIX_AnaGenFit(), Fun4All_G4_sPHENIX_ForTrackCutStudy(), Fun4All_G4_sPHENIX_ForTrackCutStudy_EmbedScanOff(), Fun4All_G4_sPHENIX_ForTrackCutStudy_EmbedScanOn(), Fun4All_G4_sPHENIX_ForTrackCutStudy_WithPileup_EmbedScanOff(), Fun4All_G4_sPHENIX_ForTrackCutStudy_WithPileup_EmbedScanOn(), Fun4All_G4_sPHENIX_photonjet(), Fun4All_G4_sPHENIX_photons(), Fun4All_G4_sPHENIX_truthphotonjet(), Fun4All_HCalJetPhiShift(), Fun4All_Pi0Gen_sPHENIX(), Fun4All_pi0tbt_SIMPLE_EMBED(), Fun4All_RunNewTruthMatcher(), Fun4All_single_particle(), Fun4All_SinglePhotonGen_sPHENIX(), Fun4All_SinglePi0Gen_sPHENIX(), Jin_BJet(), run_calo_fromMDC2Hits_towslope_Fun4All_G4_Calo(), rundst_spiNo(), spiNo2(), and Wrapper().
void HCalOuterInit ()
graph clusterizer, RawClusterBuilderGraph
Definition at line 16 of file G4_HcalOut_ref.C.
View newest version in sPHENIX GitHub at line 16 of file G4_HcalOut_ref.C
Referenced by G4Init().
Variable Documentation
enu_HCalOut_clusterizer HCalOut_clusterizer = kHCalOutTemplateClusterizer
template clusterizer, RawClusterBuilderTemplate, as developed by Sasha Bazilevsky
Definition at line 11 of file G4_HcalOut_ref.C.
View newest version in sPHENIX GitHub at line 11 of file G4_HcalOut_ref.C
Referenced by HCALOuter_Clusters().