Analysis Software: SvtxTrackMap_v1 Class Reference
SvtxTrackMap_v1 Class Reference
#include <coresoftware/blob/master/offline/packages/trackbase_historic/SvtxTrackMap_v1.h>
Public Member Functions
SvtxTrackMap_v1 ()
SvtxTrackMap_v1 (const SvtxTrackMap_v1 &trackmap)
SvtxTrackMap_v1 & operator= (const SvtxTrackMap_v1 &trackmap)
~SvtxTrackMap_v1 () override
void identify (std::ostream &os=std::cout) const override
void Reset () override
Clear Event.
int isValid () const override
isValid returns non zero if object contains vailid data
PHObject * CloneMe () const override
Virtual copy constructor.
bool empty () const override
size_t size () const override
size_t count (unsigned int idkey) const override
void clear () override
const SvtxTrack * get (unsigned int idkey) const override
SvtxTrack * get (unsigned int idkey) override
SvtxTrack * insert (const SvtxTrack *track) override
size_t erase (unsigned int idkey) override
ConstIter begin () const override
ConstIter find (unsigned int idkey) const override
ConstIter end () const override
Iter begin () override
Iter find (unsigned int idkey) override
Iter end () override
Public Member Functions inherited from SvtxTrackMap
~SvtxTrackMap () override
virtual SvtxTrack * insertWithKey (const SvtxTrack *, unsigned int)
Public Member Functions inherited from PHObject
PHObject ()
ctor
~PHObject () override
dtor
virtual PHObject * clone () const final
PHObject * Clone (const char *newname="") const final
void Copy (TObject &object) const final
virtual int Integrate () const
virtual int Integrate (PHObject *)
virtual void CopyFrom (const PHObject *obj)
Private Member Functions
ClassDefOverride (SvtxTrackMap_v1, 1)
Private Attributes
TrackMap _map
Additional Inherited Members
Public Types inherited from SvtxTrackMap
typedef std::map< unsigned int,
SvtxTrack * > TrackMap
typedef std::map< unsigned int,
SvtxTrack * >::const_iterator ConstIter
typedef std::map< unsigned int,
SvtxTrack * >::iterator Iter
Protected Member Functions inherited from SvtxTrackMap
SvtxTrackMap ()
Detailed Description
Definition at line 12 of file SvtxTrackMap_v1.h.
View newest version in sPHENIX GitHub at line 12 of file SvtxTrackMap_v1.h
Constructor & Destructor Documentation
SvtxTrackMap_v1::SvtxTrackMap_v1 ()
Definition at line 15 of file SvtxTrackMap_v1.cc.
View newest version in sPHENIX GitHub at line 15 of file SvtxTrackMap_v1.cc
Referenced by CloneMe().
SvtxTrackMap_v1::SvtxTrackMap_v1 (const SvtxTrackMap_v1 & trackmap)
Definition at line 20 of file SvtxTrackMap_v1.cc.
View newest version in sPHENIX GitHub at line 20 of file SvtxTrackMap_v1.cc
References _map, begin(), end(), and SvtxTrack::get_id().
SvtxTrackMap_v1::~SvtxTrackMap_v1 () override
Definition at line 45 of file SvtxTrackMap_v1.cc.
View newest version in sPHENIX GitHub at line 45 of file SvtxTrackMap_v1.cc
References Reset().
Member Function Documentation
ConstIter SvtxTrackMap_v1::begin (void) const inline override virtual
Reimplemented from SvtxTrackMap.
Definition at line 36 of file SvtxTrackMap_v1.h.
View newest version in sPHENIX GitHub at line 36 of file SvtxTrackMap_v1.h
References _map.
Referenced by operator=(), and SvtxTrackMap_v1().
Iter SvtxTrackMap_v1::begin (void) inline override virtual
Reimplemented from SvtxTrackMap.
Definition at line 40 of file SvtxTrackMap_v1.h.
View newest version in sPHENIX GitHub at line 40 of file SvtxTrackMap_v1.h
References _map.
SvtxTrackMap_v1::ClassDefOverride (SvtxTrackMap_v1 , 1) private
void SvtxTrackMap_v1::clear () inline override virtual
Reimplemented from SvtxTrackMap.
Definition at line 29 of file SvtxTrackMap_v1.h.
View newest version in sPHENIX GitHub at line 29 of file SvtxTrackMap_v1.h
References Reset().
PHObject* SvtxTrackMap_v1::CloneMe () const inline override virtual
Virtual copy constructor.
Reimplemented from SvtxTrackMap.
Definition at line 24 of file SvtxTrackMap_v1.h.
View newest version in sPHENIX GitHub at line 24 of file SvtxTrackMap_v1.h
References SvtxTrackMap_v1().
size_t SvtxTrackMap_v1::count (unsigned int idkey) const inline override virtual
Reimplemented from SvtxTrackMap.
Definition at line 28 of file SvtxTrackMap_v1.h.
View newest version in sPHENIX GitHub at line 28 of file SvtxTrackMap_v1.h
References _map.
bool SvtxTrackMap_v1::empty () const inline override virtual
Reimplemented from SvtxTrackMap.
Definition at line 26 of file SvtxTrackMap_v1.h.
View newest version in sPHENIX GitHub at line 26 of file SvtxTrackMap_v1.h
References _map.
ConstIter SvtxTrackMap_v1::end (void) const inline override virtual
Reimplemented from SvtxTrackMap.
Definition at line 38 of file SvtxTrackMap_v1.h.
View newest version in sPHENIX GitHub at line 38 of file SvtxTrackMap_v1.h
References _map.
Referenced by operator=(), and SvtxTrackMap_v1().
Iter SvtxTrackMap_v1::end (void) inline override virtual
Reimplemented from SvtxTrackMap.
Definition at line 42 of file SvtxTrackMap_v1.h.
View newest version in sPHENIX GitHub at line 42 of file SvtxTrackMap_v1.h
References _map.
size_t SvtxTrackMap_v1::erase (unsigned int idkey) override virtual
Reimplemented from SvtxTrackMap.
Definition at line 91 of file SvtxTrackMap_v1.cc.
View newest version in sPHENIX GitHub at line 91 of file SvtxTrackMap_v1.cc
References _map.
ConstIter SvtxTrackMap_v1::find (unsigned int idkey) const inline override virtual
Reimplemented from SvtxTrackMap.
Definition at line 37 of file SvtxTrackMap_v1.h.
View newest version in sPHENIX GitHub at line 37 of file SvtxTrackMap_v1.h
References _map.
Iter SvtxTrackMap_v1::find (unsigned int idkey) inline override virtual
Reimplemented from SvtxTrackMap.
Definition at line 41 of file SvtxTrackMap_v1.h.
View newest version in sPHENIX GitHub at line 41 of file SvtxTrackMap_v1.h
References _map.
const SvtxTrack * SvtxTrackMap_v1::get (unsigned int idkey) const override virtual
Reimplemented from SvtxTrackMap.
Definition at line 68 of file SvtxTrackMap_v1.cc.
View newest version in sPHENIX GitHub at line 68 of file SvtxTrackMap_v1.cc
References _map.
SvtxTrack * SvtxTrackMap_v1::get (unsigned int idkey) override virtual
Reimplemented from SvtxTrackMap.
Definition at line 75 of file SvtxTrackMap_v1.cc.
View newest version in sPHENIX GitHub at line 75 of file SvtxTrackMap_v1.cc
References _map.
void SvtxTrackMap_v1::identify (std::ostream & os = std::cout) const override virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from SvtxTrackMap.
Definition at line 62 of file SvtxTrackMap_v1.cc.
View newest version in sPHENIX GitHub at line 62 of file SvtxTrackMap_v1.cc
References _map.
SvtxTrack * SvtxTrackMap_v1::insert (const SvtxTrack * track) override virtual
Reimplemented from SvtxTrackMap.
Definition at line 82 of file SvtxTrackMap_v1.cc.
View newest version in sPHENIX GitHub at line 82 of file SvtxTrackMap_v1.cc
References _map, SvtxTrack::CloneMe(), and index.
int SvtxTrackMap_v1::isValid () const inline override virtual
isValid returns non zero if object contains vailid data
Reimplemented from SvtxTrackMap.
Definition at line 23 of file SvtxTrackMap_v1.h.
View newest version in sPHENIX GitHub at line 23 of file SvtxTrackMap_v1.h
SvtxTrackMap_v1 & SvtxTrackMap_v1::operator= (const SvtxTrackMap_v1 & trackmap)
Definition at line 32 of file SvtxTrackMap_v1.cc.
View newest version in sPHENIX GitHub at line 32 of file SvtxTrackMap_v1.cc
References _map, begin(), end(), SvtxTrack::get_id(), and Reset().
void SvtxTrackMap_v1::Reset () override virtual
Clear Event.
Reimplemented from PHObject.
Definition at line 50 of file SvtxTrackMap_v1.cc.
View newest version in sPHENIX GitHub at line 50 of file SvtxTrackMap_v1.cc
References _map.
Referenced by clear(), operator=(), and ~SvtxTrackMap_v1().
size_t SvtxTrackMap_v1::size (void) const inline override virtual
Reimplemented from SvtxTrackMap.
Definition at line 27 of file SvtxTrackMap_v1.h.
View newest version in sPHENIX GitHub at line 27 of file SvtxTrackMap_v1.h
References _map.
Member Data Documentation
TrackMap SvtxTrackMap_v1::_map private
Definition at line 45 of file SvtxTrackMap_v1.h.
View newest version in sPHENIX GitHub at line 45 of file SvtxTrackMap_v1.h
Referenced by begin(), count(), empty(), end(), erase(), find(), get(), identify(), insert(), operator=(), Reset(), size(), and SvtxTrackMap_v1().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/trackbase_historic/SvtxTrackMap_v1.h
coresoftware/blob/master/offline/packages/trackbase_historic/SvtxTrackMap_v1.cc