Analysis Software: HybridHadronization::hadron_collection Class Reference
HybridHadronization::hadron_collection Class Reference
Public Member Functions
hadron_collection ()
hadron_collection (HHhadron had)
void add (HHhadron had)
void add (hadron_collection hads)
int num ()
void clear ()
HHhadron & operator[] (int i)
const HHhadron & operator[] (int i) const
Public Attributes
std::vector< HHhadron > hadrons
Detailed Description
Definition at line 300 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 300 of file HybridHadronization.h
Constructor & Destructor Documentation
HybridHadronization::hadron_collection::hadron_collection () inline
Definition at line 305 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 305 of file HybridHadronization.h
HybridHadronization::hadron_collection::hadron_collection (HHhadron had) inline
Definition at line 307 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 307 of file HybridHadronization.h
Member Function Documentation
void HybridHadronization::hadron_collection::add (HHhadron had) inline
Definition at line 309 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 309 of file HybridHadronization.h
void HybridHadronization::hadron_collection::add (hadron_collection hads) inline
Definition at line 311 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 311 of file HybridHadronization.h
References i, and num().
void HybridHadronization::hadron_collection::clear () inline
Definition at line 315 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 315 of file HybridHadronization.h
int HybridHadronization::hadron_collection::num () inline
Definition at line 313 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 313 of file HybridHadronization.h
Referenced by add(), HybridHadronization::bring_hadrons_to_mass_shell(), and HybridHadronization::scale_kinematics_negative_hadrons().
HHhadron& HybridHadronization::hadron_collection::operator[] (int i) inline
Definition at line 331 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 331 of file HybridHadronization.h
References i.
const HHhadron& HybridHadronization::hadron_collection::operator[] (int i) const inline
Definition at line 333 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 333 of file HybridHadronization.h
References i.
Member Data Documentation
std::vector<HHhadron> HybridHadronization::hadron_collection::hadrons
Definition at line 303 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 303 of file HybridHadronization.h
The documentation for this class was generated from the following file:
JETSCAPE/blob/main/src/hadronization/HybridHadronization.h