Analysis Software: daq_device_deadtime Class Reference
daq_device_deadtime Class Reference
#include <rcdaq/blob/master/daq_device_deadtime.h>
Public Member Functions
daq_device_deadtime (const int eventtype, const int subeventid, const int n_ticks=100, const int n_words=0, const int trigger_enabled=0)
~daq_device_deadtime ()
void identify (std::ostream &os=std::cout) const
int max_length (const int etype) const
int put_data (const int etype, int *adr, const int length)
int init ()
int rearm (const int etype)
Public Member Functions inherited from daq_device
daq_device ()
virtual ~daq_device ()
virtual int endrun ()
virtual int subeventid () const
Protected Attributes
subevtdata_ptr sevt
unsigned int number_of_ticks
unsigned int number_of_words
pulserTriggerHandler * th
Protected Attributes inherited from daq_device
long m_subeventid
long m_eventType
Additional Inherited Members
Static Public Member Functions inherited from daq_device
static int formatPacketHdr (int *adr)
Detailed Description
Definition at line 10 of file daq_device_deadtime.h.
View newest version in sPHENIX GitHub at line 10 of file daq_device_deadtime.h
Constructor & Destructor Documentation
daq_device_deadtime::daq_device_deadtime (const int eventtype, const int subeventid, const int n_ticks = 100, const int n_words = 0, const int trigger_enabled = 0)
Definition at line 9 of file daq_device_deadtime.cc.
View newest version in sPHENIX GitHub at line 9 of file daq_device_deadtime.cc
References registerTriggerHandler().
daq_device_deadtime::~daq_device_deadtime ()
Definition at line 31 of file daq_device_deadtime.cc.
View newest version in sPHENIX GitHub at line 31 of file daq_device_deadtime.cc
References clearTriggerHandler().
Member Function Documentation
void daq_device_deadtime::identify (std::ostream & os = std::cout) const virtual
Implements daq_device.
Definition at line 96 of file daq_device_deadtime.cc.
View newest version in sPHENIX GitHub at line 96 of file daq_device_deadtime.cc
int daq_device_deadtime::init (void) virtual
Reimplemented from daq_device.
Definition at line 123 of file daq_device_deadtime.cc.
View newest version in sPHENIX GitHub at line 123 of file daq_device_deadtime.cc
int daq_device_deadtime::max_length (const int etype) const virtual
Implements daq_device.
Definition at line 111 of file daq_device_deadtime.cc.
View newest version in sPHENIX GitHub at line 111 of file daq_device_deadtime.cc
References SEVTHEADERLENGTH.
int daq_device_deadtime::put_data (const int etype, int * adr, const int length) virtual
Implements daq_device.
Definition at line 44 of file daq_device_deadtime.cc.
View newest version in sPHENIX GitHub at line 44 of file daq_device_deadtime.cc
References daq_getEventFormat(), ID4EVT, SEVTHEADERLENGTH, packet_data::structureinfo, packet_data::sub_decoding, packet_data::sub_id, packet_data::sub_length, and packet_data::sub_type.
int daq_device_deadtime::rearm (const int etype) virtual
Reimplemented from daq_device.
Definition at line 130 of file daq_device_deadtime.cc.
View newest version in sPHENIX GitHub at line 130 of file daq_device_deadtime.cc
Member Data Documentation
unsigned int daq_device_deadtime::number_of_ticks protected
Definition at line 39 of file daq_device_deadtime.h.
View newest version in sPHENIX GitHub at line 39 of file daq_device_deadtime.h
unsigned int daq_device_deadtime::number_of_words protected
Definition at line 40 of file daq_device_deadtime.h.
View newest version in sPHENIX GitHub at line 40 of file daq_device_deadtime.h
subevtdata_ptr daq_device_deadtime::sevt protected
Definition at line 38 of file daq_device_deadtime.h.
View newest version in sPHENIX GitHub at line 38 of file daq_device_deadtime.h
pulserTriggerHandler* daq_device_deadtime::th protected
Definition at line 41 of file daq_device_deadtime.h.
View newest version in sPHENIX GitHub at line 41 of file daq_device_deadtime.h
The documentation for this class was generated from the following files:
rcdaq/blob/master/daq_device_deadtime.h
rcdaq/blob/master/daq_device_deadtime.cc