Analysis Software: Acts::Material Class Reference
Acts::Material Class Reference
#include <acts/blob/sPHENIX/Core/include/Acts/Material/Material.hpp>
Public Types
using ParametersVector = Eigen::Matrix< float, 5, 1 >
Public Member Functions
Material ()=default
Construct a vacuum representation.
Material (const ParametersVector &parameters)
Construct from an encoded parameters vector.
Material (Material &&mat)=default
Material (const Material &mat)=default
~Material ()=default
Material & operator= (Material &&mat)=default
Material & operator= (const Material &mat)=default
constexpr operator bool () const
Check if the material is valid, i.e. it is not vacuum.
constexpr float X0 () const
Return the radition length. Infinity in case of vacuum.
constexpr float L0 () const
Return the nuclear interaction length. Infinity in case of vacuum.
constexpr float Ar () const
Return the relative atomic mass.
constexpr float Z () const
Return the nuclear charge number.
constexpr float molarDensity () const
Return the molar density.
constexpr float molarElectronDensity () const
Return the molar electron density.
float massDensity () const
Return the mass density.
float meanExcitationEnergy () const
Return the mean electron excitation energy.
ParametersVector parameters () const
Encode the properties into an opaque parameters vector.
Static Public Member Functions
static Material fromMolarDensity (float x0, float l0, float ar, float z, float molarRho)
static Material fromMassDensity (float x0, float l0, float ar, float z, float massRho)
Private Attributes
float m_x0 = std::numeric_limits<float>::infinity()
float m_l0 = std::numeric_limits<float>::infinity()
float m_ar = 0.0f
float m_z = 0.0f
float m_molarRho = 0.0f
Friends
constexpr bool operator== (const Material &lhs, const Material &rhs)
constexpr bool operator!= (const Material &lhs, const Material &rhs)
Detailed Description
Material description for interactions with matter.
The following parameters are used to specify the material and its interactions with traversing particles:
radiation length X0 (native length units)
nuclear interaction length L0 (native length units)
relative atomic mass Ar (unitless number)
nuclear charge number Z (elementary charge e)
molar density (native amount-of-substance unit / (native length unit)³)
The parameters can be effective or average parameters e.g. when a mixture of materials is described.
Note
Always use the opaque parameters vector to serialize/deserialize the material information. Since the internal storage might be different from the external accessors, this ensures that always the numerically optimal parameters are stored. Use the ParametersVector type and do not assume any particular size since we might consider to store more parameters in the future.
Definition at line 39 of file Material.hpp.
View newest version in sPHENIX GitHub at line 39 of file Material.hpp
Member Typedef Documentation
using Acts::Material::ParametersVector = Eigen::Matrix<float, 5, 1>
Definition at line 41 of file Material.hpp.
View newest version in sPHENIX GitHub at line 41 of file Material.hpp
Constructor & Destructor Documentation
Acts::Material::Material () default
Construct a vacuum representation.
Acts::Material::Material (const ParametersVector & parameters)
Construct from an encoded parameters vector.
Definition at line 65 of file Material.cpp.
View newest version in sPHENIX GitHub at line 65 of file Material.cpp
Acts::Material::Material (Material && mat) default
Acts::Material::Material (const Material & mat) default
Acts::Material::~Material () default
Member Function Documentation
constexpr float Acts::Material::Ar () const inline
Return the relative atomic mass.
Definition at line 92 of file Material.hpp.
View newest version in sPHENIX GitHub at line 92 of file Material.hpp
References m_ar.
Referenced by Acts::Test::BOOST_AUTO_TEST_CASE(), BOOST_AUTO_TEST_CASE(), and Acts::operator<<().
Acts::Material Acts::Material::fromMassDensity (float x0, float l0, float ar, float z, float massRho) static
Construct from material parameters using the mass density.
Parameters
x0 is the radiation length
l0 is the nuclear interaction length
ar is the relative atomic mass
z is the nuclear charge number
massRho is the mass density
Warning
Due to the choice of native mass units, using the mass density can lead to numerical problems. Typical mass densities lead to computations with values differing by 20+ orders of magnitude.
Definition at line 29 of file Material.cpp.
View newest version in sPHENIX GitHub at line 29 of file Material.cpp
References m_x0, x0, and physmon_track_finding_ttbar::z.
Referenced by BOOST_AUTO_TEST_CASE(), ActsExamples::Generic::buildDetector(), main(), Acts::Geant4MaterialConverter::material(), Acts::TGeoMaterialConverter::materialSlab(), ActsExamples::RootMaterialTrackReader::read(), ActsExamples::MaterialSteppingAction::UserSteppingAction(), and while().
Acts::Material Acts::Material::fromMolarDensity (float x0, float l0, float ar, float z, float molarRho) static
Construct from material parameters using the molar density.
Parameters
x0 is the radiation length
l0 is the nuclear interaction length
ar is the relative atomic mass
z is the nuclear charge number
molarRho is the molar density
Definition at line 54 of file Material.cpp.
View newest version in sPHENIX GitHub at line 54 of file Material.cpp
References m_ar, m_l0, m_molarRho, m_x0, m_z, x0, and physmon_track_finding_ttbar::z.
Referenced by Acts::Test::BOOST_AUTO_TEST_CASE(), BOOST_AUTO_TEST_CASE(), BOOST_DATA_TEST_CASE(), Acts::Test::makeBeryllium(), Acts::Test::makeSilicon(), and Acts::Test::makeUnitSlab().
constexpr float Acts::Material::L0 () const inline
Return the nuclear interaction length. Infinity in case of vacuum.
Definition at line 90 of file Material.hpp.
View newest version in sPHENIX GitHub at line 90 of file Material.hpp
References m_l0.
Referenced by Acts::Test::BOOST_AUTO_TEST_CASE(), BOOST_AUTO_TEST_CASE(), and Acts::operator<<().
float Acts::Material::massDensity () const
Return the mass density.
Definition at line 72 of file Material.cpp.
View newest version in sPHENIX GitHub at line 72 of file Material.cpp
Referenced by Acts::Test::BOOST_AUTO_TEST_CASE(), and BOOST_AUTO_TEST_CASE().
float Acts::Material::meanExcitationEnergy () const
Return the mean electron excitation energy.
Definition at line 81 of file Material.cpp.
View newest version in sPHENIX GitHub at line 81 of file Material.cpp
References f.
Referenced by BOOST_AUTO_TEST_CASE().
constexpr float Acts::Material::molarDensity () const inline
Return the molar density.
Definition at line 96 of file Material.hpp.
View newest version in sPHENIX GitHub at line 96 of file Material.hpp
References m_molarRho.
Referenced by Acts::Test::BOOST_AUTO_TEST_CASE(), BOOST_AUTO_TEST_CASE(), and Acts::operator<<().
constexpr float Acts::Material::molarElectronDensity () const inline
Return the molar electron density.
Definition at line 98 of file Material.hpp.
View newest version in sPHENIX GitHub at line 98 of file Material.hpp
References m_molarRho, and m_z.
Referenced by BOOST_AUTO_TEST_CASE().
constexpr Acts::Material::operator bool () const inline
Check if the material is valid, i.e. it is not vacuum.
Definition at line 85 of file Material.hpp.
View newest version in sPHENIX GitHub at line 85 of file Material.hpp
References m_ar.
Material& Acts::Material::operator= (Material && mat) default
Material& Acts::Material::operator= (const Material & mat) default
Acts::Material::ParametersVector Acts::Material::parameters () const
Encode the properties into an opaque parameters vector.
Definition at line 88 of file Material.cpp.
View newest version in sPHENIX GitHub at line 88 of file Material.cpp
References Dataset::parameters.
Referenced by Acts::Test::BOOST_AUTO_TEST_CASE(), Acts::to_json(), and while().
constexpr float Acts::Material::X0 () const inline
Return the radition length. Infinity in case of vacuum.
Definition at line 88 of file Material.hpp.
View newest version in sPHENIX GitHub at line 88 of file Material.hpp
References m_x0.
Referenced by Acts::Test::BOOST_AUTO_TEST_CASE(), BOOST_AUTO_TEST_CASE(), Acts::operator<<(), and Acts::AccumulatedMaterialSlab::trackVariance().
constexpr float Acts::Material::Z () const inline
Return the nuclear charge number.
Definition at line 94 of file Material.hpp.
View newest version in sPHENIX GitHub at line 94 of file Material.hpp
References m_z.
Referenced by Acts::Test::BOOST_AUTO_TEST_CASE(), BOOST_AUTO_TEST_CASE(), ActsFatras::detail::GaussianMixture::operator()(), ActsFatras::detail::GeneralMixture::operator()(), and Acts::operator<<().
Friends And Related Function Documentation
constexpr bool operator!= (const Material & lhs, const Material & rhs) friend
Definition at line 119 of file Material.hpp.
View newest version in sPHENIX GitHub at line 119 of file Material.hpp
constexpr bool operator== (const Material & lhs, const Material & rhs) friend
Definition at line 114 of file Material.hpp.
View newest version in sPHENIX GitHub at line 114 of file Material.hpp
Member Data Documentation
float Acts::Material::m_ar = 0.0f private
Definition at line 110 of file Material.hpp.
View newest version in sPHENIX GitHub at line 110 of file Material.hpp
Referenced by Ar(), fromMolarDensity(), and operator bool().
float Acts::Material::m_l0 = std::numeric_limits<float>::infinity() private
Definition at line 109 of file Material.hpp.
View newest version in sPHENIX GitHub at line 109 of file Material.hpp
Referenced by fromMolarDensity(), and L0().
float Acts::Material::m_molarRho = 0.0f private
Definition at line 112 of file Material.hpp.
View newest version in sPHENIX GitHub at line 112 of file Material.hpp
Referenced by fromMolarDensity(), molarDensity(), and molarElectronDensity().
float Acts::Material::m_x0 = std::numeric_limits<float>::infinity() private
Definition at line 108 of file Material.hpp.
View newest version in sPHENIX GitHub at line 108 of file Material.hpp
Referenced by fromMassDensity(), fromMolarDensity(), and X0().
float Acts::Material::m_z = 0.0f private
Definition at line 111 of file Material.hpp.
View newest version in sPHENIX GitHub at line 111 of file Material.hpp
Referenced by fromMolarDensity(), molarElectronDensity(), and Z().
The documentation for this class was generated from the following files:
acts/blob/sPHENIX/Core/include/Acts/Material/Material.hpp
acts/blob/sPHENIX/Core/src/Material/Material.cpp