Analysis Software: Acts::EventDataView3D Struct Reference
Acts::EventDataView3D Struct Reference
#include <acts/blob/sPHENIX/Core/include/Acts/Visualization/EventDataView3D.hpp>
Static Public Member Functions
static std::array< double, 3 > decomposeCovariance (const ActsSquareMatrix< 2 > &covariance)
static std::vector< Vector3 > createEllipse (double lambda0, double lambda1, double theta, size_t lseg, double offset, const Vector2 &lposition=Vector2(0., 0.), const Transform3 &transform=Transform3::Identity())
static void drawCovarianceCartesian (IVisualization3D &helper, const Vector2 &lposition, const SquareMatrix2 &covariance, const Transform3 &transform, double locErrorScale=1, const ViewConfig &viewConfig=s_viewParameter)
static void drawCovarianceAngular (IVisualization3D &helper, const Vector3 &position, const Vector3 &direction, const ActsSquareMatrix< 2 > &covariance, double directionScale=1, double angularErrorScale=1, const ViewConfig &viewConfig=s_viewParameter)
template<typename parameters_t >
static void drawBoundTrackParameters (IVisualization3D &helper, const parameters_t &parameters, const GeometryContext &gctx=GeometryContext(), double momentumScale=1., double locErrorScale=1., double angularErrorScale=1., const ViewConfig &parConfig=s_viewParameter, const ViewConfig &covConfig=s_viewParameter, const ViewConfig &surfConfig=s_viewSensitive)
static void drawMeasurement (IVisualization3D &helper, const Vector2 &lposition, const SquareMatrix2 &covariance, const Transform3 &transform, const double locErrorScale=1., const ViewConfig &measurementConfig=s_viewMeasurement)
template<typename traj_t >
static void drawMultiTrajectory (IVisualization3D &helper, const traj_t &multiTraj, const size_t &entryIndex, const GeometryContext &gctx=GeometryContext(), double momentumScale=1., double locErrorScale=1., double angularErrorScale=1., const ViewConfig &surfaceConfig=s_viewSensitive, const ViewConfig &measurementConfig=s_viewMeasurement, const ViewConfig &predictedConfig=s_viewPredicted, const ViewConfig &filteredConfig=s_viewFiltered, const ViewConfig &smoothedConfig=s_viewSmoothed)
Detailed Description
Definition at line 41 of file EventDataView3D.hpp.
View newest version in sPHENIX GitHub at line 41 of file EventDataView3D.hpp
Member Function Documentation
static std::vector<Vector3> Acts::EventDataView3D::createEllipse (double lambda0, double lambda1, double theta, size_t lseg, double offset, const Vector2 & lposition = Vector2(0., 0.), const Transform3 & transform = Transform3::Identity()) inline static
Helper method to draw the ellipse points
Parameters
lambda0 The Eigenvalue in 0
lambda1 The Eigenvalue in 1
theta The angle between the x/y frame and EV frame
lseg The number of segments
offset The out of plane offset for visibility
lposition The local anker point of the ellipse
transform The transform to global
Definition at line 71 of file EventDataView3D.hpp.
View newest version in sPHENIX GitHub at line 71 of file EventDataView3D.hpp
References it, ActsTests::PropagationDatasets::phi, Acts::Test::transform, ambiguity_solver_full_chain::x, and y.
Referenced by drawCovarianceCartesian().
static std::array<double, 3> Acts::EventDataView3D::decomposeCovariance (const ActsSquareMatrix< 2 > & covariance) inline static
Helper to find the eigen values and corr angle
Parameters
covariance The covariance matrix
Definition at line 45 of file EventDataView3D.hpp.
View newest version in sPHENIX GitHub at line 45 of file EventDataView3D.hpp
References covariance(), Acts::eBoundLoc0, Acts::eBoundLoc1, lambda0, and ActsTests::PropagationDatasets::theta.
Referenced by Acts::Test::BOOST_AUTO_TEST_CASE(), and drawCovarianceCartesian().
template<typename parameters_t > static void Acts::EventDataView3D::drawBoundTrackParameters (IVisualization3D & helper, const parameters_t & parameters, const GeometryContext & gctx = GeometryContext(), double momentumScale = 1., double locErrorScale = 1., double angularErrorScale = 1., const ViewConfig & parConfig = s_viewParameter, const ViewConfig & covConfig = s_viewParameter, const ViewConfig & surfConfig = s_viewSensitive) inline static
Helper method to draw bound parameters object
Parameters
helper [in, out] The visualization helper
parameters The bound parameters to be drawn
gctx The geometry context for which it is drawn
momentumScale The scale of the momentum
locErrorScale The scale of the local error
angularErrorScale The scale of the angular error
parConfig The visualization options for the parameter
covConfig The visualization option for the covariance
surfConfig The visualization option for the surface
Definition at line 136 of file EventDataView3D.hpp.
View newest version in sPHENIX GitHub at line 136 of file EventDataView3D.hpp
References covariance(), Acts::GeometryView3D::drawArrowBackward(), Acts::GeometryView3D::drawArrowForward(), drawCovarianceAngular(), drawCovarianceCartesian(), Acts::GeometryView3D::drawSurface(), gctx, Acts::ViewConfig::lineThickness, merge_hashes::p, and position.
Referenced by drawMultiTrajectory(), and Acts::EventDataView3DTest::testBoundTrackParameters().
void Acts::EventDataView3D::drawCovarianceAngular (IVisualization3D & helper, const Vector3 & position, const Vector3 & direction, const ActsSquareMatrix< 2 > & covariance, double directionScale = 1, double angularErrorScale = 1, const ViewConfig & viewConfig = s_viewParameter) static
Helper method to draw error cone of a direction
Parameters
helper [in, out] The visualization helper
position Where the cone originates from
direction The direction parameters
covariance The 2x2 covariance matrix for phi/theta
directionScale The direction arrow length
angularErrorScale The local Error scale
viewConfig The visualization parameters
Definition at line 39 of file EventDataView3D.cpp.
View newest version in sPHENIX GitHub at line 39 of file EventDataView3D.cpp
References INTTVtxZ::dphi, lambda0, Acts::ViewConfig::nSegments, Acts::VectorHelpers::phi(), ActsTests::PropagationDatasets::theta, and Acts::VectorHelpers::theta().
Referenced by drawBoundTrackParameters(), and Acts::PrimitivesView3DTest::run().
void Acts::EventDataView3D::drawCovarianceCartesian (IVisualization3D & helper, const Vector2 & lposition, const SquareMatrix2 & covariance, const Transform3 & transform, double locErrorScale = 1, const ViewConfig & viewConfig = s_viewParameter) static
Helper method to draw error ellipse
Parameters
helper [in, out] The visualization helper
lposition The local position
covariance The covariance matrix
transform The reference Frame transform
locErrorScale The local Error scale
viewConfig The visualization parameters
Definition at line 22 of file EventDataView3D.cpp.
View newest version in sPHENIX GitHub at line 22 of file EventDataView3D.cpp
References Acts::detail::FacesHelper::convexFaceMesh(), createEllipse(), decomposeCovariance(), Acts::GeometryView3D::drawPolyhedron(), lambda0, Acts::ViewConfig::nSegments, Acts::ViewConfig::offset, and ActsTests::PropagationDatasets::theta.
Referenced by drawBoundTrackParameters(), drawMeasurement(), and Acts::PrimitivesView3DTest::run().
static void Acts::EventDataView3D::drawMeasurement (IVisualization3D & helper, const Vector2 & lposition, const SquareMatrix2 & covariance, const Transform3 & transform, const double locErrorScale = 1., const ViewConfig & measurementConfig = s_viewMeasurement) inline static
Helper method to draw a single measurement
Parameters
helper [in, out] The visualization helper
lposition calibrated measurement
covariance calibrated covariance
transform reference surface transformed with the geometry context
locErrorScale The scale of the local error
measurementConfig The visualization options for the measurement
TODO: Expand to 1D measurements
Definition at line 191 of file EventDataView3D.hpp.
View newest version in sPHENIX GitHub at line 191 of file EventDataView3D.hpp
References drawCovarianceCartesian().
Referenced by drawMultiTrajectory(), and Acts::EventDataView3DTest::testMeasurement().
template<typename traj_t > static void Acts::EventDataView3D::drawMultiTrajectory (IVisualization3D & helper, const traj_t & multiTraj, const size_t & entryIndex, const GeometryContext & gctx = GeometryContext(), double momentumScale = 1., double locErrorScale = 1., double angularErrorScale = 1., const ViewConfig & surfaceConfig = s_viewSensitive, const ViewConfig & measurementConfig = s_viewMeasurement, const ViewConfig & predictedConfig = s_viewPredicted, const ViewConfig & filteredConfig = s_viewFiltered, const ViewConfig & smoothedConfig = s_viewSmoothed) inline static
Helper method to draw one trajectory stored in a MultiTrajectory object
Parameters
helper [in, out] The visualization helper
multiTraj The MultiTrajectory storing the trajectory to be drawn
entryIndex The trajectory entry index
gctx The geometry context for which it is drawn
momentumScale The scale of the momentum
locErrorScale The scale of the local error
angularErrorScale The scale of the angular error
surfaceConfig The visualization options for the surface
measurementConfig The visualization options for the measurement
predictedConfig The visualization options for the predicted measurement
filteredConfig The visualization options for the filtered parameters
smoothedConfig The visualization options for the smoothed parameters
Definition at line 223 of file EventDataView3D.hpp.
View newest version in sPHENIX GitHub at line 223 of file EventDataView3D.hpp
References covariance(), drawBoundTrackParameters(), drawMeasurement(), Acts::GeometryView3D::drawSurface(), gctx, Acts::MeasurementFlag, particleHypothesis, Acts::ParticleHypothesis::pion(), and filter::state.
Referenced by Acts::EventDataView3DTest::testMultiTrajectory().
The documentation for this struct was generated from the following files:
acts/blob/sPHENIX/Core/include/Acts/Visualization/EventDataView3D.hpp
acts/blob/sPHENIX/Core/src/Visualization/EventDataView3D.cpp