Analysis Software: oncsSub_idtpcfeev2 Class Reference
oncsSub_idtpcfeev2 Class Reference
#include <online_distribution/blob/master/newbasic/oncsSub_idtpcfeev2.h>
Classes
struct tpc_sample
Public Member Functions
oncsSub_idtpcfeev2 (subevtdata_ptr)
~oncsSub_idtpcfeev2 ()
int iValue (const int fee, const int ch, const int sample)
int iValue (const int fee, const int ch, const int sample, const char *what)
int iValue (const int ch, const int sample)
int iValue (const int, const int, const char *what)
int iValue (const int, const char *what)
void dump (OSTREAM &os=COUT)
Public Member Functions inherited from oncsSubevent_w2
oncsSubevent_w2 (subevtdata_ptr)
virtual void gdump (const int how=EVT_HEXADECIMAL, OSTREAM &os=COUT) const
Public Member Functions inherited from oncsSubevent
oncsSubevent (subevtdata_ptr data)
virtual ~oncsSubevent ()
virtual int getLength () const
virtual int getIdentifier () const
get the packet identifier
virtual int getHitFormat () const
get the hit format; in case of unformatted get the encoding scheme.
virtual int getPadding () const
get the number of padding units in the packet data.
virtual int getDataLength () const
get what the name says...
virtual int getStructure () const
get the structure of the packet data; unformatted, hitlist, etc.
virtual int getDebugLength () const
get the length of the debug block
virtual int getErrorLength () const
virtual void identify (OSTREAM &=COUT) const
virtual int setIdentifier (const int newid)
set a new packet identifier
int iValue (const int)
iValue returns the value of a given channel as an int.
int iValue (const int, const char *)
int iValue (const int, const int)
int iValue (const int, const int, const char *)
int iValue (const int channel, const int iy, const int iz)
int iValue (const int channel, const int iy, const int iz, const char *what)
virtual float rValue (const int)
virtual float rValue (const int, const char *)
virtual float rValue (const int, const int)
virtual int getArraylength (const char *)
virtual int fillIntArray (int[], const int, int *, const char *what="")
virtual int fillFloatArray (float[], const int, int *, const char *what="")
fillFloatArray fills an array of floats
virtual int * getIntArray (int *, const char *what="")
virtual float * getFloatArray (int *, const char *what="")
getFloatArray creates and returns an array of floats
virtual int is_pointer_type () const
find out what type (pointer- or data based) packet object we have
virtual int convert ()
convert from pointer- to data based object, if it is already data-based, do nothing.
virtual int copyMe (int[], const int maxlength) const
int setInternalParameter (const int p1=0, const int p2=0, const char *what="")
Public Member Functions inherited from Packet
virtual ~Packet ()
the virtual destructor
virtual double dValue (const int channel)
virtual double dValue (const int channel, const char *what)
virtual double dValue (const int channel, const int iy)
virtual long long lValue (const int channel)
virtual long long lValue (const int channel, const char *what)
virtual long long lValue (const int channel, const int iy)
virtual long long lValue (const int channel, const int iy, const char *what)
virtual void * pValue (const int)
virtual void * pValue (const int, const char *)
virtual void * pValue (const int, const int)
virtual void identify (std::ostream &os=std::cout) const =0
see below for comments
virtual void fullIdentify (std::ostream &os=std::cout) const
write an indepth identification message to the supplied OSTREAM.
virtual void dump (std::ostream &os=std::cout)=0
virtual void gdump (const int how=EVT_HEXADECIMAL, std::ostream &os=std::cout) const =0
virtual int getCheckSumStatus () const
Protected Member Functions
int tpc_decode ()
unsigned short reverseBits (const unsigned short x) const
unsigned short crc16 (const unsigned int fee, const unsigned int index, const int l) const
Protected Member Functions inherited from oncsSubevent_w2
virtual int * decode (int *)
Protected Attributes
int _broken
int _is_decoded
unsigned int _max_samples [MAX_FEECOUNT]
unsigned int _lowest_bx [MAX_FEECOUNT]
unsigned int _highest_bx [MAX_FEECOUNT]
std::vector< unsigned short > fee_data [MAX_FEECOUNT]
std::vector< tpc_sample > fee_samples [MAX_FEECOUNT][MAX_FEECHANNELS]
Static Protected Attributes
static const int MAX_FEECOUNT =8
static const int MAX_FEECHANNELS =256
Detailed Description
Definition at line 11 of file oncsSub_idtpcfeev2.h.
View newest version in sPHENIX GitHub at line 11 of file oncsSub_idtpcfeev2.h
Constructor & Destructor Documentation
oncsSub_idtpcfeev2::oncsSub_idtpcfeev2 (subevtdata_ptr data)
Definition at line 11 of file oncsSub_idtpcfeev2.cc.
View newest version in sPHENIX GitHub at line 11 of file oncsSub_idtpcfeev2.cc
References _highest_bx, _is_decoded, _lowest_bx, _max_samples, i, and MAX_FEECOUNT.
oncsSub_idtpcfeev2::~oncsSub_idtpcfeev2 ()
Definition at line 26 of file oncsSub_idtpcfeev2.cc.
View newest version in sPHENIX GitHub at line 26 of file oncsSub_idtpcfeev2.cc
Member Function Documentation
unsigned short oncsSub_idtpcfeev2::crc16 (const unsigned int fee, const unsigned int index, const int l) const protected
Definition at line 445 of file oncsSub_idtpcfeev2.cc.
View newest version in sPHENIX GitHub at line 445 of file oncsSub_idtpcfeev2.cc
References fee_data, i, index, k, reverseBits(), and ambiguity_solver_full_chain::x.
Referenced by tpc_decode().
void oncsSub_idtpcfeev2::dump (OSTREAM & os = COUT) virtual
Reimplemented from oncsSubevent_w2.
Definition at line 367 of file oncsSub_idtpcfeev2.cc.
View newest version in sPHENIX GitHub at line 367 of file oncsSub_idtpcfeev2.cc
References i, oncsSubevent::identify(), iValue(), MAX_FEECHANNELS, and physmon_simulation::s.
int oncsSub_idtpcfeev2::iValue (const int , const int , const int) virtual
this supports devices organized as three-dimensional data (card vs channel vs time slice)
Implements Packet.
Definition at line 269 of file oncsSub_idtpcfeev2.cc.
View newest version in sPHENIX GitHub at line 269 of file oncsSub_idtpcfeev2.cc
References fee_samples, MAX_FEECHANNELS, MAX_FEECOUNT, size, and tpc_decode().
Referenced by dump().
int oncsSub_idtpcfeev2::iValue (const int , const int , const int , const char *) virtual
this supports devices organized as three-dimensional data (card vs channel vs time slice, with a "what" selection)
Implements Packet.
Definition at line 281 of file oncsSub_idtpcfeev2.cc.
View newest version in sPHENIX GitHub at line 281 of file oncsSub_idtpcfeev2.cc
References fee_samples, MAX_FEECHANNELS, MAX_FEECOUNT, size, and tpc_decode().
int oncsSub_idtpcfeev2::iValue (const int , const int) virtual
this supports devices which are inherently organized as two-dimensional data, such as flash ADC's (channel vs time slice)
Implements Packet.
Definition at line 262 of file oncsSub_idtpcfeev2.cc.
View newest version in sPHENIX GitHub at line 262 of file oncsSub_idtpcfeev2.cc
References tpc_decode().
int oncsSub_idtpcfeev2::iValue (const int , const int , const char *) virtual
we have a few recent devices which have one more dimension (such as card, time sample, channel)
Implements Packet.
Definition at line 301 of file oncsSub_idtpcfeev2.cc.
View newest version in sPHENIX GitHub at line 301 of file oncsSub_idtpcfeev2.cc
References fee_samples, MAX_FEECHANNELS, MAX_FEECOUNT, and tpc_decode().
int oncsSub_idtpcfeev2::iValue (const int , const char *) virtual
with the "what" parameter you can decide which aspect of the data you want to see (for devices which have more than one)
Implements Packet.
Definition at line 317 of file oncsSub_idtpcfeev2.cc.
View newest version in sPHENIX GitHub at line 317 of file oncsSub_idtpcfeev2.cc
References _broken, _highest_bx, _lowest_bx, _max_samples, MAX_FEECOUNT, n, and tpc_decode().
unsigned short oncsSub_idtpcfeev2::reverseBits (const unsigned short x) const protected
Definition at line 432 of file oncsSub_idtpcfeev2.cc.
View newest version in sPHENIX GitHub at line 432 of file oncsSub_idtpcfeev2.cc
References n, and ambiguity_solver_full_chain::x.
Referenced by crc16().
int oncsSub_idtpcfeev2::tpc_decode () protected
Definition at line 38 of file oncsSub_idtpcfeev2.cc.
View newest version in sPHENIX GitHub at line 38 of file oncsSub_idtpcfeev2.cc
References _highest_bx, _is_decoded, _lowest_bx, _max_samples, KFPMath::a, Acts::Test::at, cerrfl, channel(), crc16(), subevt_data::data, fee_data, fee_samples, oncsSubevent::getLength(), oncsSubevent::getPadding(), HEADER_LENGTH, ambiguity_solver_full_chain::idx, index, MAX_FEECHANNELS, MAX_FEECOUNT, physmon_simulation::s, SEVTHEADERLENGTH, size, oncsSubevent::SubeventHdr, while(), and ambiguity_solver_full_chain::x.
Referenced by iValue().
Member Data Documentation
int oncsSub_idtpcfeev2::_broken protected
Definition at line 39 of file oncsSub_idtpcfeev2.h.
View newest version in sPHENIX GitHub at line 39 of file oncsSub_idtpcfeev2.h
Referenced by iValue().
unsigned int oncsSub_idtpcfeev2::_highest_bx[MAX_FEECOUNT] protected
Definition at line 53 of file oncsSub_idtpcfeev2.h.
View newest version in sPHENIX GitHub at line 53 of file oncsSub_idtpcfeev2.h
Referenced by iValue(), oncsSub_idtpcfeev2(), and tpc_decode().
int oncsSub_idtpcfeev2::_is_decoded protected
Definition at line 41 of file oncsSub_idtpcfeev2.h.
View newest version in sPHENIX GitHub at line 41 of file oncsSub_idtpcfeev2.h
Referenced by oncsSub_idtpcfeev2(), and tpc_decode().
unsigned int oncsSub_idtpcfeev2::_lowest_bx[MAX_FEECOUNT] protected
Definition at line 52 of file oncsSub_idtpcfeev2.h.
View newest version in sPHENIX GitHub at line 52 of file oncsSub_idtpcfeev2.h
Referenced by iValue(), oncsSub_idtpcfeev2(), and tpc_decode().
unsigned int oncsSub_idtpcfeev2::_max_samples[MAX_FEECOUNT] protected
Definition at line 51 of file oncsSub_idtpcfeev2.h.
View newest version in sPHENIX GitHub at line 51 of file oncsSub_idtpcfeev2.h
Referenced by iValue(), oncsSub_idtpcfeev2(), and tpc_decode().
std::vector<unsigned short> oncsSub_idtpcfeev2::fee_data[MAX_FEECOUNT] protected
Definition at line 55 of file oncsSub_idtpcfeev2.h.
View newest version in sPHENIX GitHub at line 55 of file oncsSub_idtpcfeev2.h
Referenced by crc16(), and tpc_decode().
std::vector<tpc_sample> oncsSub_idtpcfeev2::fee_samples[MAX_FEECOUNT][MAX_FEECHANNELS] protected
Definition at line 58 of file oncsSub_idtpcfeev2.h.
View newest version in sPHENIX GitHub at line 58 of file oncsSub_idtpcfeev2.h
Referenced by iValue(), and tpc_decode().
const int oncsSub_idtpcfeev2::MAX_FEECHANNELS =256 static protected
Definition at line 33 of file oncsSub_idtpcfeev2.h.
View newest version in sPHENIX GitHub at line 33 of file oncsSub_idtpcfeev2.h
Referenced by dump(), iValue(), and tpc_decode().
const int oncsSub_idtpcfeev2::MAX_FEECOUNT =8 static protected
Definition at line 32 of file oncsSub_idtpcfeev2.h.
View newest version in sPHENIX GitHub at line 32 of file oncsSub_idtpcfeev2.h
Referenced by iValue(), oncsSub_idtpcfeev2(), and tpc_decode().
The documentation for this class was generated from the following files:
online_distribution/blob/master/newbasic/oncsSub_idtpcfeev2.h
online_distribution/blob/master/newbasic/oncsSub_idtpcfeev2.cc