Analysis Software: ODBCResultSet Class Reference
ODBCResultSet Class Reference
#include <RDBC/blob/master/odbc/ODBCResultSet.h>
Public Member Functions
virtual ~ODBCResultSet ()
Bool_t WasNull ()
TString GetString (Int_t columnIndex)
Bool_t GetBoolean (Int_t columnIndex)
Char_t GetByte (Int_t columnIndex)
Short_t GetShort (Int_t columnIndex)
Int_t GetInt (Int_t columnIndex)
Long_t GetLong (Int_t columnIndex)
Float_t GetFloat (Int_t columnIndex)
Double_t GetDouble (Int_t columnIndex)
TArrayC GetBytes (Int_t columnIndex)
TSQLDate GetDate (Int_t columnIndex)
TSQLTime GetTime (Int_t columnIndex)
TSQLTimestamp GetTimestamp (Int_t columnIndex)
TBuffer * GetAsciiStream (Int_t columnIndex)
TBuffer * GetBinaryStream (Int_t columnIndex)
TObject * GetObject (Int_t columnIndex)
TString GetString (const TString &columnName)
Bool_t GetBoolean (const TString &columnName)
Char_t GetByte (const TString &columnName)
Short_t GetShort (const TString &columnName)
Int_t GetInt (const TString &columnName)
Long_t GetLong (const TString &columnName)
Float_t GetFloat (const TString &columnName)
Double_t GetDouble (const TString &columnName)
TArrayC GetBytes (const TString &columnName)
TSQLDate GetDate (const TString &columnName)
TSQLTime GetTime (const TString &columnName)
TSQLTimestamp GetTimestamp (const TString &columnName)
TBuffer * GetAsciiStream (const TString &columnName)
TBuffer * GetBinaryStream (const TString &columnName)
TObject * GetObject (const TString &columnName)
TString GetCursorName ()
TSQLResultSetMetaData * GetMetaData ()
Int_t FindColumn (const TString &columnName)
Bool_t IsBeforeFirst ()
Bool_t IsAfterLast ()
Bool_t IsFirst ()
Bool_t IsLast ()
void BeforeFirst ()
void AfterLast ()
void SetFetchDirection (Int_t direction)
Int_t GetFetchDirection ()
Int_t GetRow ()
void SetFetchSize (Int_t rows)
Int_t GetFetchSize ()
Int_t GetType ()
Int_t GetConcurrency ()
void UpdateNull (Int_t columnIndex)
void UpdateBoolean (Int_t columnIndex, Bool_t x)
void UpdateByte (Int_t columnIndex, Char_t x)
void UpdateShort (Int_t columnIndex, Short_t x)
void UpdateInt (Int_t columnIndex, Int_t x)
void UpdateLong (Int_t columnIndex, Long_t x)
void UpdateFloat (Int_t columnIndex, Float_t x)
void UpdateDouble (Int_t columnIndex, Double_t x)
void UpdateString (Int_t columnIndex, const TString &x)
void UpdateBytes (Int_t columnIndex, const TArrayC &x)
void UpdateDate (Int_t columnIndex, const TSQLDate &x)
void UpdateTime (Int_t columnIndex, const TSQLTime &x)
void UpdateTimestamp (Int_t columnIndex, const TSQLTimestamp &x)
void UpdateAsciiStream (Int_t columnIndex, TBuffer *x, Int_t length)
void UpdateBinaryStream (Int_t columnIndex, TBuffer *x, Int_t length)
void UpdateObject (Int_t columnIndex, TObject *x)
void UpdateNull (const TString &columnName)
void UpdateBoolean (const TString &columnName, Bool_t x)
void UpdateByte (const TString &columnName, Char_t x)
void UpdateShort (const TString &columnName, Short_t x)
void UpdateInt (const TString &columnName, Int_t x)
void UpdateLong (const TString &columnName, Long_t x)
void UpdateFloat (const TString &columnName, Float_t x)
void UpdateDouble (const TString &columnName, Double_t x)
void UpdateString (const TString &columnName, const TString &x)
void UpdateBytes (const TString &columnName, const TArrayC &x)
void UpdateDate (const TString &columnName, const TSQLDate &x)
void UpdateTime (const TString &columnName, const TSQLTime &x)
void UpdateTimestamp (const TString &columnName, const TSQLTimestamp &x)
void UpdateAsciiStream (const TString &columnName, TBuffer *x, Int_t length)
void UpdateBinaryStream (const TString &columnName, TBuffer *x, Int_t length)
void UpdateObject (const TString &columnName, TObject *x)
Bool_t RowUpdated ()
Bool_t RowInserted ()
Bool_t RowDeleted ()
void InsertRow ()
void UpdateRow ()
void DeleteRow ()
void RefreshRow ()
void CancelRowUpdates ()
void MoveToInsertRow ()
void MoveToCurrentRow ()
void Close (Option_t *option="")
TSQLRow * Next ()
TSQLRow * Previous ()
TSQLRow * First ()
TSQLRow * Last ()
TSQLRow * Absolute (Int_t row)
TSQLRow * Relative (Int_t rows)
Public Member Functions inherited from TSQLResultSet
virtual ~TSQLResultSet ()
virtual void Close (const Option_t *option="")=0
virtual TSQLStatement * GetStatement () const
virtual Int_t GetFieldCount ()
virtual const char * GetFieldName (Int_t field)
virtual void Print (Option_t *option="") const
virtual TTree * Tree (Int_t begin=0, Int_t end=0)
Public Member Functions inherited from TSQL
TSQL (void *imp=0)
virtual ~TSQL ()
virtual void Throw (TSQLException *e)
TList * GetWarnings () const
void ClearWarnings ()
virtual Bool_t IsValid () const
Protected Member Functions
ODBCResultSet (TSQLStatement *stmt=0, void *imp=0)
Protected Member Functions inherited from TSQLResultSet
TSQLResultSet (TSQLStatement *stmt=0, void *imp=0)
Friends
class ODBCStatement
class ODBCPreparedStatement
class ODBCCallableStatement
class ODBCDatabaseMetaData
Additional Inherited Members
Static Public Member Functions inherited from TSQL
static Bool_t SetHandler (const TString &handler)
static Bool_t UnsetHandler (const TString &handler="")
Protected Attributes inherited from TSQLResultSet
RDBCRow * fRow
TSQLStatement * fStatement
TSQLResultSetMetaData * fMetaData
Detailed Description
Definition at line 17 of file ODBCResultSet.h.
View newest version in sPHENIX GitHub at line 17 of file ODBCResultSet.h
Constructor & Destructor Documentation
ODBCResultSet::ODBCResultSet (TSQLStatement * stmt = 0, void * imp = 0) protected
Definition at line 177 of file ODBCResultSet.cxx.
View newest version in sPHENIX GitHub at line 177 of file ODBCResultSet.cxx
References Acts::UnitConstants::e, TSQL::fImp, TSQLResultSet::fMetaData, TSQLResultSet::fRow, TSQLResultSet::fStatement, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::ResultSet::getMetaData(), odbc::SQLException::getSQLState(), ODBCXX_STRING_CSTR, and TSQL::Throw().
Referenced by ODBCStatement::ExecuteQuery(), and ODBCStatement::GetResultSet().
ODBCResultSet::~ODBCResultSet () virtual
Definition at line 199 of file ODBCResultSet.cxx.
View newest version in sPHENIX GitHub at line 199 of file ODBCResultSet.cxx
References Acts::UnitConstants::e, TSQLStatement::fCurrentResult, TSQL::fImp, TSQLResultSet::fMetaData, TSQLResultSet::fRow, TSQLResultSet::fStatement, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), ODBCXX_STRING_CSTR, and TSQL::Throw().
Member Function Documentation
TSQLRow * ODBCResultSet::Absolute (Int_t row) virtual
Implements TSQLResultSet.
Definition at line 2592 of file ODBCResultSet.cxx.
View newest version in sPHENIX GitHub at line 2592 of file ODBCResultSet.cxx
References odbc::ResultSet::absolute(), Acts::UnitConstants::e, TSQL::fImp, TSQLResultSet::fRow, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), ODBCXX_STRING_CSTR, and TSQL::Throw().
void ODBCResultSet::AfterLast () virtual
Implements TSQLResultSet.
Definition at line 1263 of file ODBCResultSet.cxx.
View newest version in sPHENIX GitHub at line 1263 of file ODBCResultSet.cxx
References odbc::ResultSet::afterLast(), Acts::UnitConstants::e, TSQL::fImp, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), ODBCXX_STRING_CSTR, and TSQL::Throw().
void ODBCResultSet::BeforeFirst () virtual
Implements TSQLResultSet.
Definition at line 1239 of file ODBCResultSet.cxx.
View newest version in sPHENIX GitHub at line 1239 of file ODBCResultSet.cxx
References odbc::ResultSet::beforeFirst(), Acts::UnitConstants::e, TSQL::fImp, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), ODBCXX_STRING_CSTR, and TSQL::Throw().
void ODBCResultSet::CancelRowUpdates () virtual
Implements TSQLResultSet.
Definition at line 2443 of file ODBCResultSet.cxx.
View newest version in sPHENIX GitHub at line 2443 of file ODBCResultSet.cxx
References odbc::ResultSet::cancelRowUpdates(), Acts::UnitConstants::e, TSQL::fImp, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), ODBCXX_STRING_CSTR, and TSQL::Throw().
void ODBCResultSet::Close (Option_t * option = "")
Definition at line 2740 of file ODBCResultSet.cxx.
View newest version in sPHENIX GitHub at line 2740 of file ODBCResultSet.cxx
References Acts::UnitConstants::e, TSQL::fImp, TSQLResultSet::fMetaData, TSQLResultSet::fRow, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), ODBCXX_STRING_CSTR, and TSQL::Throw().
void ODBCResultSet::DeleteRow () virtual
Implements TSQLResultSet.
Definition at line 2385 of file ODBCResultSet.cxx.
View newest version in sPHENIX GitHub at line 2385 of file ODBCResultSet.cxx
References odbc::ResultSet::deleteRow(), Acts::UnitConstants::e, TSQL::fImp, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), ODBCXX_STRING_CSTR, and TSQL::Throw().
Int_t ODBCResultSet::FindColumn (const TString & columnName) virtual
Implements TSQLResultSet.
Definition at line 1085 of file ODBCResultSet.cxx.
View newest version in sPHENIX GitHub at line 1085 of file ODBCResultSet.cxx
References Acts::UnitConstants::e, TSQL::fImp, odbc::ResultSet::findColumn(), odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), ODBCXX_STRING_C, ODBCXX_STRING_CSTR, and TSQL::Throw().
Referenced by GetAsciiStream(), GetBinaryStream(), GetBoolean(), GetByte(), GetBytes(), GetDate(), GetDouble(), GetFloat(), GetInt(), GetLong(), GetObject(), GetShort(), GetString(), GetTime(), GetTimestamp(), UpdateAsciiStream(), UpdateBinaryStream(), UpdateBoolean(), UpdateByte(), UpdateBytes(), UpdateDate(), UpdateDouble(), UpdateFloat(), UpdateInt(), UpdateLong(), UpdateNull(), UpdateObject(), UpdateShort(), UpdateString(), UpdateTime(), and UpdateTimestamp().
TSQLRow * ODBCResultSet::First () virtual
Implements TSQLResultSet.
Definition at line 2562 of file ODBCResultSet.cxx.
View newest version in sPHENIX GitHub at line 2562 of file ODBCResultSet.cxx
References Acts::UnitConstants::e, TSQL::fImp, odbc::ResultSet::first(), TSQLResultSet::fRow, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), ODBCXX_STRING_CSTR, and TSQL::Throw().
TBuffer * ODBCResultSet::GetAsciiStream (Int_t columnIndex) virtual
Implements TSQLResultSet.
Definition at line 634 of file ODBCResultSet.cxx.
View newest version in sPHENIX GitHub at line 634 of file ODBCResultSet.cxx
References Acts::PhysicalConstants::c, Acts::UnitConstants::e, TSQL::fImp, odbc::ResultSet::getAsciiStream(), odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), ODBCXX_STREAM, ODBCXX_STRING_CSTR, and TSQL::Throw().
Referenced by GetAsciiStream().
TBuffer * ODBCResultSet::GetAsciiStream (const TString & columnName) virtual
Implements TSQLResultSet.
Definition at line 961 of file ODBCResultSet.cxx.
View newest version in sPHENIX GitHub at line 961 of file ODBCResultSet.cxx
References FindColumn(), and GetAsciiStream().
TBuffer * ODBCResultSet::GetBinaryStream (Int_t columnIndex) virtual
Implements TSQLResultSet.
Definition at line 689 of file ODBCResultSet.cxx.
View newest version in sPHENIX GitHub at line 689 of file ODBCResultSet.cxx
References Acts::PhysicalConstants::c, Acts::UnitConstants::e, TSQL::fImp, odbc::ResultSet::getBinaryStream(), odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), ODBCXX_STREAM, ODBCXX_STRING_CSTR, and TSQL::Throw().
Referenced by GetBinaryStream(), and GetObject().
TBuffer * ODBCResultSet::GetBinaryStream (const TString & columnName) virtual
Implements TSQLResultSet.
Definition at line 988 of file ODBCResultSet.cxx.
View newest version in sPHENIX GitHub at line 988 of file ODBCResultSet.cxx
References FindColumn(), and GetBinaryStream().
Bool_t ODBCResultSet::GetBoolean (Int_t columnIndex) virtual
Implements TSQLResultSet.
Definition at line 287 of file ODBCResultSet.cxx.
View newest version in sPHENIX GitHub at line 287 of file ODBCResultSet.cxx
References Acts::UnitConstants::e, TSQL::fImp, odbc::ResultSet::getBoolean(), odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), ODBCXX_STRING_CSTR, and TSQL::Throw().
Referenced by GetBoolean().
Bool_t ODBCResultSet::GetBoolean (const TString & columnName) virtual
Implements TSQLResultSet.
Definition at line 780 of file ODBCResultSet.cxx.
View newest version in sPHENIX GitHub at line 780 of file ODBCResultSet.cxx
References FindColumn(), and GetBoolean().
Char_t ODBCResultSet::GetByte (Int_t columnIndex) virtual
Implements TSQLResultSet.
Definition at line 317 of file ODBCResultSet.cxx.
View newest version in sPHENIX GitHub at line 317 of file ODBCResultSet.cxx
References Acts::UnitConstants::e, TSQL::fImp, odbc::ResultSet::getByte(), odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), ODBCXX_STRING_CSTR, and TSQL::Throw().
Referenced by GetByte().
Char_t ODBCResultSet::GetByte (const TString & columnName) virtual
Implements TSQLResultSet.
Definition at line 796 of file ODBCResultSet.cxx.
View newest version in sPHENIX GitHub at line 796 of file ODBCResultSet.cxx
References FindColumn(), and GetByte().
TArrayC ODBCResultSet::GetBytes (Int_t columnIndex) virtual
Implements TSQLResultSet.
Definition at line 497 of file ODBCResultSet.cxx.
View newest version in sPHENIX GitHub at line 497 of file ODBCResultSet.cxx
References TauVsDIS_MachineLearning_Differentiation::array, KFPMath::b, Acts::UnitConstants::e, TSQL::fImp, odbc::ResultSet::getBytes(), odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), ODBCXX_BYTES, ODBCXX_BYTES_DATA, ODBCXX_BYTES_SIZE, ODBCXX_STRING_CSTR, and TSQL::Throw().
Referenced by GetBytes().
TArrayC ODBCResultSet::GetBytes (const TString & columnName) virtual
Implements TSQLResultSet.
Definition at line 892 of file ODBCResultSet.cxx.
View newest version in sPHENIX GitHub at line 892 of file ODBCResultSet.cxx
References FindColumn(), and GetBytes().
Int_t ODBCResultSet::GetConcurrency () virtual
Implements TSQLResultSet.
Definition at line 1429 of file ODBCResultSet.cxx.
View newest version in sPHENIX GitHub at line 1429 of file ODBCResultSet.cxx
References Acts::UnitConstants::e, TSQL::fImp, odbc::ResultSet::getConcurrency(), odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), ODBCXX_STRING_CSTR, and TSQL::Throw().
TString ODBCResultSet::GetCursorName () virtual
Implements TSQLResultSet.
Definition at line 1031 of file ODBCResultSet.cxx.
View newest version in sPHENIX GitHub at line 1031 of file ODBCResultSet.cxx
References Acts::UnitConstants::e, TSQL::fImp, odbc::ResultSet::getCursorName(), odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), ODBCXX_STRING_CSTR, str, and TSQL::Throw().
TSQLDate ODBCResultSet::GetDate (Int_t columnIndex) virtual
Implements TSQLResultSet.
Definition at line 530 of file ODBCResultSet.cxx.
View newest version in sPHENIX GitHub at line 530 of file ODBCResultSet.cxx
References Acts::UnitConstants::e, TSQL::fImp, odbc::ResultSet::getDate(), odbc::Date::getDay(), odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::Date::getMonth(), odbc::SQLException::getSQLState(), odbc::Date::getYear(), ODBCXX_STRING_CSTR, and TSQL::Throw().
Referenced by GetDate().
TSQLDate ODBCResultSet::GetDate (const TString & columnName) virtual
Implements TSQLResultSet.
Definition at line 910 of file ODBCResultSet.cxx.
View newest version in sPHENIX GitHub at line 910 of file ODBCResultSet.cxx
References FindColumn(), and GetDate().
Double_t ODBCResultSet::GetDouble (Int_t columnIndex) virtual
Implements TSQLResultSet.
Definition at line 467 of file ODBCResultSet.cxx.
View newest version in sPHENIX GitHub at line 467 of file ODBCResultSet.cxx
References Acts::UnitConstants::e, TSQL::fImp, odbc::ResultSet::getDouble(), odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), ODBCXX_STRING_CSTR, and TSQL::Throw().
Referenced by GetDouble().
Double_t ODBCResultSet::GetDouble (const TString & columnName) virtual
Implements TSQLResultSet.
Definition at line 876 of file ODBCResultSet.cxx.
View newest version in sPHENIX GitHub at line 876 of file ODBCResultSet.cxx
References FindColumn(), and GetDouble().
Int_t ODBCResultSet::GetFetchDirection () virtual
Implements TSQLResultSet.
Definition at line 1330 of file ODBCResultSet.cxx.
View newest version in sPHENIX GitHub at line 1330 of file ODBCResultSet.cxx
Int_t ODBCResultSet::GetFetchSize () virtual
Implements TSQLResultSet.
Definition at line 1373 of file ODBCResultSet.cxx.
View newest version in sPHENIX GitHub at line 1373 of file ODBCResultSet.cxx
References Acts::UnitConstants::e, TSQL::fImp, odbc::SQLException::getErrorCode(), odbc::ResultSet::getFetchSize(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), ODBCXX_STRING_CSTR, and TSQL::Throw().
Float_t ODBCResultSet::GetFloat (Int_t columnIndex) virtual
Implements TSQLResultSet.
Definition at line 437 of file ODBCResultSet.cxx.
View newest version in sPHENIX GitHub at line 437 of file ODBCResultSet.cxx
References Acts::UnitConstants::e, TSQL::fImp, odbc::SQLException::getErrorCode(), odbc::ResultSet::getFloat(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), ODBCXX_STRING_CSTR, and TSQL::Throw().
Referenced by GetFloat().
Float_t ODBCResultSet::GetFloat (const TString & columnName) virtual
Implements TSQLResultSet.
Definition at line 860 of file ODBCResultSet.cxx.
View newest version in sPHENIX GitHub at line 860 of file ODBCResultSet.cxx
References FindColumn(), and GetFloat().
Int_t ODBCResultSet::GetInt (Int_t columnIndex) virtual
Implements TSQLResultSet.
Definition at line 377 of file ODBCResultSet.cxx.
View newest version in sPHENIX GitHub at line 377 of file ODBCResultSet.cxx
References Acts::UnitConstants::e, TSQL::fImp, odbc::SQLException::getErrorCode(), odbc::ResultSet::getInt(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), ODBCXX_STRING_CSTR, and TSQL::Throw().
Referenced by GetInt().
Int_t ODBCResultSet::GetInt (const TString & columnName) virtual
Implements TSQLResultSet.
Definition at line 828 of file ODBCResultSet.cxx.
View newest version in sPHENIX GitHub at line 828 of file ODBCResultSet.cxx
References FindColumn(), and GetInt().
Long_t ODBCResultSet::GetLong (Int_t columnIndex) virtual
Implements TSQLResultSet.
Definition at line 407 of file ODBCResultSet.cxx.
View newest version in sPHENIX GitHub at line 407 of file ODBCResultSet.cxx
References Acts::UnitConstants::e, TSQL::fImp, odbc::SQLException::getErrorCode(), odbc::ResultSet::getLong(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), ODBCXX_STRING_CSTR, and TSQL::Throw().
Referenced by GetLong().
Long_t ODBCResultSet::GetLong (const TString & columnName) virtual
Implements TSQLResultSet.
Definition at line 844 of file ODBCResultSet.cxx.
View newest version in sPHENIX GitHub at line 844 of file ODBCResultSet.cxx
References FindColumn(), and GetLong().
TSQLResultSetMetaData * ODBCResultSet::GetMetaData () virtual
Implements TSQLResultSet.
Definition at line 1071 of file ODBCResultSet.cxx.
View newest version in sPHENIX GitHub at line 1071 of file ODBCResultSet.cxx
References TSQLResultSet::fMetaData.
TObject * ODBCResultSet::GetObject (Int_t columnIndex) virtual
Implements TSQLResultSet.
Definition at line 742 of file ODBCResultSet.cxx.
View newest version in sPHENIX GitHub at line 742 of file ODBCResultSet.cxx
References KFPMath::b, and GetBinaryStream().
Referenced by GetObject().
TObject * ODBCResultSet::GetObject (const TString & columnName) virtual
Implements TSQLResultSet.
Definition at line 1016 of file ODBCResultSet.cxx.
View newest version in sPHENIX GitHub at line 1016 of file ODBCResultSet.cxx
References FindColumn(), and GetObject().
Int_t ODBCResultSet::GetRow () virtual
Implements TSQLResultSet.
Definition at line 1287 of file ODBCResultSet.cxx.
View newest version in sPHENIX GitHub at line 1287 of file ODBCResultSet.cxx
References Acts::UnitConstants::e, TSQL::fImp, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::ResultSet::getRow(), odbc::SQLException::getSQLState(), ODBCXX_STRING_CSTR, and TSQL::Throw().
Short_t ODBCResultSet::GetShort (Int_t columnIndex) virtual
Implements TSQLResultSet.
Definition at line 347 of file ODBCResultSet.cxx.
View newest version in sPHENIX GitHub at line 347 of file ODBCResultSet.cxx
References Acts::UnitConstants::e, TSQL::fImp, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::ResultSet::getShort(), odbc::SQLException::getSQLState(), ODBCXX_STRING_CSTR, and TSQL::Throw().
Referenced by GetShort().
Short_t ODBCResultSet::GetShort (const TString & columnName) virtual
Implements TSQLResultSet.
Definition at line 812 of file ODBCResultSet.cxx.
View newest version in sPHENIX GitHub at line 812 of file ODBCResultSet.cxx
References FindColumn(), and GetShort().
TString ODBCResultSet::GetString (Int_t columnIndex) virtual
Implements TSQLResultSet.
Definition at line 257 of file ODBCResultSet.cxx.
View newest version in sPHENIX GitHub at line 257 of file ODBCResultSet.cxx
References Acts::UnitConstants::e, TSQL::fImp, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), odbc::ResultSet::getString(), ODBCXX_STRING_CSTR, str, and TSQL::Throw().
Referenced by GetString().
TString ODBCResultSet::GetString (const TString & columnName) virtual
Implements TSQLResultSet.
Definition at line 764 of file ODBCResultSet.cxx.
View newest version in sPHENIX GitHub at line 764 of file ODBCResultSet.cxx
References FindColumn(), and GetString().
TSQLTime ODBCResultSet::GetTime (Int_t columnIndex) virtual
Implements TSQLResultSet.
Definition at line 563 of file ODBCResultSet.cxx.
View newest version in sPHENIX GitHub at line 563 of file ODBCResultSet.cxx
References Acts::UnitConstants::e, TSQL::fImp, odbc::SQLException::getErrorCode(), odbc::Time::getHour(), odbc::SQLException::getMessage(), odbc::Time::getMinute(), odbc::Time::getSecond(), odbc::SQLException::getSQLState(), odbc::ResultSet::getTime(), ODBCXX_STRING_CSTR, and TSQL::Throw().
Referenced by GetTime().
TSQLTime ODBCResultSet::GetTime (const TString & columnName) virtual
Implements TSQLResultSet.
Definition at line 927 of file ODBCResultSet.cxx.
View newest version in sPHENIX GitHub at line 927 of file ODBCResultSet.cxx
References FindColumn(), and GetTime().
TSQLTimestamp ODBCResultSet::GetTimestamp (Int_t columnIndex) virtual
Implements TSQLResultSet.
Definition at line 597 of file ODBCResultSet.cxx.
View newest version in sPHENIX GitHub at line 597 of file ODBCResultSet.cxx
References Acts::UnitConstants::e, TSQL::fImp, odbc::Date::getDay(), odbc::SQLException::getErrorCode(), odbc::Time::getHour(), odbc::SQLException::getMessage(), odbc::Time::getMinute(), odbc::Date::getMonth(), odbc::Timestamp::getNanos(), odbc::Time::getSecond(), odbc::SQLException::getSQLState(), odbc::ResultSet::getTimestamp(), odbc::Date::getYear(), ODBCXX_STRING_CSTR, and TSQL::Throw().
Referenced by GetTimestamp().
TSQLTimestamp ODBCResultSet::GetTimestamp (const TString & columnName) virtual
Implements TSQLResultSet.
Definition at line 944 of file ODBCResultSet.cxx.
View newest version in sPHENIX GitHub at line 944 of file ODBCResultSet.cxx
References FindColumn(), and GetTimestamp().
Int_t ODBCResultSet::GetType () virtual
Implements TSQLResultSet.
Definition at line 1400 of file ODBCResultSet.cxx.
View newest version in sPHENIX GitHub at line 1400 of file ODBCResultSet.cxx
References Acts::UnitConstants::e, TSQL::fImp, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), odbc::ResultSet::getType(), ODBCXX_STRING_CSTR, and TSQL::Throw().
void ODBCResultSet::InsertRow () virtual
Implements TSQLResultSet.
Definition at line 2336 of file ODBCResultSet.cxx.
View newest version in sPHENIX GitHub at line 2336 of file ODBCResultSet.cxx
References Acts::UnitConstants::e, TSQL::fImp, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), odbc::ResultSet::insertRow(), ODBCXX_STRING_CSTR, and TSQL::Throw().
Bool_t ODBCResultSet::IsAfterLast () virtual
Implements TSQLResultSet.
Definition at line 1146 of file ODBCResultSet.cxx.
View newest version in sPHENIX GitHub at line 1146 of file ODBCResultSet.cxx
References Acts::UnitConstants::e, TSQL::fImp, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), odbc::ResultSet::isAfterLast(), ODBCXX_STRING_CSTR, and TSQL::Throw().
Bool_t ODBCResultSet::IsBeforeFirst () virtual
Implements TSQLResultSet.
Definition at line 1116 of file ODBCResultSet.cxx.
View newest version in sPHENIX GitHub at line 1116 of file ODBCResultSet.cxx
References Acts::UnitConstants::e, TSQL::fImp, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), odbc::ResultSet::isBeforeFirst(), ODBCXX_STRING_CSTR, and TSQL::Throw().
Bool_t ODBCResultSet::IsFirst () virtual
Implements TSQLResultSet.
Definition at line 1176 of file ODBCResultSet.cxx.
View newest version in sPHENIX GitHub at line 1176 of file ODBCResultSet.cxx
References Acts::UnitConstants::e, TSQL::fImp, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), odbc::ResultSet::isFirst(), ODBCXX_STRING_CSTR, and TSQL::Throw().
Bool_t ODBCResultSet::IsLast () virtual
Implements TSQLResultSet.
Definition at line 1205 of file ODBCResultSet.cxx.
View newest version in sPHENIX GitHub at line 1205 of file ODBCResultSet.cxx
References Acts::UnitConstants::e, TSQL::fImp, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), odbc::ResultSet::isLast(), ODBCXX_STRING_CSTR, and TSQL::Throw().
TSQLRow * ODBCResultSet::Last () virtual
Implements TSQLResultSet.
Definition at line 2710 of file ODBCResultSet.cxx.
View newest version in sPHENIX GitHub at line 2710 of file ODBCResultSet.cxx
References Acts::UnitConstants::e, TSQL::fImp, TSQLResultSet::fRow, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), odbc::ResultSet::last(), ODBCXX_STRING_CSTR, and TSQL::Throw().
void ODBCResultSet::MoveToCurrentRow () virtual
Implements TSQLResultSet.
Definition at line 2502 of file ODBCResultSet.cxx.
View newest version in sPHENIX GitHub at line 2502 of file ODBCResultSet.cxx
References Acts::UnitConstants::e, TSQL::fImp, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), odbc::ResultSet::moveToCurrentRow(), ODBCXX_STRING_CSTR, and TSQL::Throw().
void ODBCResultSet::MoveToInsertRow () virtual
Implements TSQLResultSet.
Definition at line 2469 of file ODBCResultSet.cxx.
View newest version in sPHENIX GitHub at line 2469 of file ODBCResultSet.cxx
References Acts::UnitConstants::e, TSQL::fImp, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), odbc::ResultSet::moveToInsertRow(), ODBCXX_STRING_CSTR, and TSQL::Throw().
TSQLRow * ODBCResultSet::Next () virtual
Implements TSQLResultSet.
Definition at line 2526 of file ODBCResultSet.cxx.
View newest version in sPHENIX GitHub at line 2526 of file ODBCResultSet.cxx
References Acts::UnitConstants::e, TSQL::fImp, TSQLResultSet::fRow, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), odbc::ResultSet::next(), ODBCXX_STRING_CSTR, and TSQL::Throw().
TSQLRow * ODBCResultSet::Previous () virtual
Implements TSQLResultSet.
Definition at line 2677 of file ODBCResultSet.cxx.
View newest version in sPHENIX GitHub at line 2677 of file ODBCResultSet.cxx
References Acts::UnitConstants::e, TSQL::fImp, TSQLResultSet::fRow, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), ODBCXX_STRING_CSTR, odbc::ResultSet::previous(), and TSQL::Throw().
void ODBCResultSet::RefreshRow () virtual
Implements TSQLResultSet.
Definition at line 2408 of file ODBCResultSet.cxx.
View newest version in sPHENIX GitHub at line 2408 of file ODBCResultSet.cxx
References Acts::UnitConstants::e, TSQL::fImp, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), ODBCXX_STRING_CSTR, odbc::ResultSet::refreshRow(), and TSQL::Throw().
TSQLRow * ODBCResultSet::Relative (Int_t rows) virtual
Implements TSQLResultSet.
Definition at line 2638 of file ODBCResultSet.cxx.
View newest version in sPHENIX GitHub at line 2638 of file ODBCResultSet.cxx
References Acts::UnitConstants::e, TSQL::fImp, TSQLResultSet::fRow, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), ODBCXX_STRING_CSTR, odbc::ResultSet::relative(), and TSQL::Throw().
Bool_t ODBCResultSet::RowDeleted () virtual
Implements TSQLResultSet.
Definition at line 1523 of file ODBCResultSet.cxx.
View newest version in sPHENIX GitHub at line 1523 of file ODBCResultSet.cxx
References Acts::UnitConstants::e, TSQL::fImp, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), ODBCXX_STRING_CSTR, odbc::ResultSet::rowDeleted(), and TSQL::Throw().
Bool_t ODBCResultSet::RowInserted () virtual
Implements TSQLResultSet.
Definition at line 1491 of file ODBCResultSet.cxx.
View newest version in sPHENIX GitHub at line 1491 of file ODBCResultSet.cxx
References Acts::UnitConstants::e, TSQL::fImp, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), ODBCXX_STRING_CSTR, odbc::ResultSet::rowInserted(), and TSQL::Throw().
Bool_t ODBCResultSet::RowUpdated () virtual
Implements TSQLResultSet.
Definition at line 1459 of file ODBCResultSet.cxx.
View newest version in sPHENIX GitHub at line 1459 of file ODBCResultSet.cxx
References Acts::UnitConstants::e, TSQL::fImp, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), ODBCXX_STRING_CSTR, odbc::ResultSet::rowUpdated(), and TSQL::Throw().
void ODBCResultSet::SetFetchDirection (Int_t direction) virtual
Implements TSQLResultSet.
Definition at line 1315 of file ODBCResultSet.cxx.
View newest version in sPHENIX GitHub at line 1315 of file ODBCResultSet.cxx
void ODBCResultSet::SetFetchSize (Int_t rows) virtual
Implements TSQLResultSet.
Definition at line 1343 of file ODBCResultSet.cxx.
View newest version in sPHENIX GitHub at line 1343 of file ODBCResultSet.cxx
References Acts::UnitConstants::e, TSQL::fImp, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), ODBCXX_STRING_CSTR, odbc::ResultSet::setFetchSize(), and TSQL::Throw().
void ODBCResultSet::UpdateAsciiStream (Int_t columnIndex, TBuffer * x, Int_t length) virtual
Implements TSQLResultSet.
Definition at line 1943 of file ODBCResultSet.cxx.
View newest version in sPHENIX GitHub at line 1943 of file ODBCResultSet.cxx
References Acts::UnitConstants::e, TSQL::fImp, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), G4PLUGDOOR::length, ODBCXX_STRING_CSTR, physmon_simulation::s, TSQL::Throw(), and odbc::ResultSet::updateAsciiStream().
Referenced by UpdateAsciiStream().
void ODBCResultSet::UpdateAsciiStream (const TString & columnName, TBuffer * x, Int_t length) virtual
Implements TSQLResultSet.
Definition at line 2275 of file ODBCResultSet.cxx.
View newest version in sPHENIX GitHub at line 2275 of file ODBCResultSet.cxx
References FindColumn(), and UpdateAsciiStream().
void ODBCResultSet::UpdateBinaryStream (Int_t columnIndex, TBuffer * x, Int_t length) virtual
Implements TSQLResultSet.
Definition at line 1976 of file ODBCResultSet.cxx.
View newest version in sPHENIX GitHub at line 1976 of file ODBCResultSet.cxx
References Acts::UnitConstants::e, TSQL::fImp, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), G4PLUGDOOR::length, ODBCXX_STRING_CSTR, physmon_simulation::s, TSQL::Throw(), and odbc::ResultSet::updateBinaryStream().
Referenced by UpdateBinaryStream(), and UpdateObject().
void ODBCResultSet::UpdateBinaryStream (const TString & columnName, TBuffer * x, Int_t length) virtual
Implements TSQLResultSet.
Definition at line 2296 of file ODBCResultSet.cxx.
View newest version in sPHENIX GitHub at line 2296 of file ODBCResultSet.cxx
References FindColumn(), and UpdateBinaryStream().
void ODBCResultSet::UpdateBoolean (Int_t columnIndex, Bool_t x) virtual
Implements TSQLResultSet.
Definition at line 1583 of file ODBCResultSet.cxx.
View newest version in sPHENIX GitHub at line 1583 of file ODBCResultSet.cxx
References Acts::UnitConstants::e, TSQL::fImp, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), ODBCXX_STRING_CSTR, TSQL::Throw(), and odbc::ResultSet::updateBoolean().
Referenced by UpdateBoolean().
void ODBCResultSet::UpdateBoolean (const TString & columnName, Bool_t x) virtual
Implements TSQLResultSet.
Definition at line 2054 of file ODBCResultSet.cxx.
View newest version in sPHENIX GitHub at line 2054 of file ODBCResultSet.cxx
References FindColumn(), and UpdateBoolean().
void ODBCResultSet::UpdateByte (Int_t columnIndex, Char_t x) virtual
Implements TSQLResultSet.
Definition at line 1611 of file ODBCResultSet.cxx.
View newest version in sPHENIX GitHub at line 1611 of file ODBCResultSet.cxx
References Acts::UnitConstants::e, TSQL::fImp, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), ODBCXX_STRING_CSTR, TSQL::Throw(), and odbc::ResultSet::updateByte().
Referenced by UpdateByte().
void ODBCResultSet::UpdateByte (const TString & columnName, Char_t x) virtual
Implements TSQLResultSet.
Definition at line 2072 of file ODBCResultSet.cxx.
View newest version in sPHENIX GitHub at line 2072 of file ODBCResultSet.cxx
References FindColumn(), and UpdateByte().
void ODBCResultSet::UpdateBytes (Int_t columnIndex, const TArrayC & x) virtual
Implements TSQLResultSet.
Definition at line 1810 of file ODBCResultSet.cxx.
View newest version in sPHENIX GitHub at line 1810 of file ODBCResultSet.cxx
References KFPMath::b, Acts::UnitConstants::e, TSQL::fImp, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), ODBCXX_BYTES, ODBCXX_BYTES_C, ODBCXX_STRING_CSTR, TSQL::Throw(), and odbc::ResultSet::updateBytes().
Referenced by UpdateBytes().
void ODBCResultSet::UpdateBytes (const TString & columnName, const TArrayC & x) virtual
Implements TSQLResultSet.
Definition at line 2199 of file ODBCResultSet.cxx.
View newest version in sPHENIX GitHub at line 2199 of file ODBCResultSet.cxx
References FindColumn(), and UpdateBytes().
void ODBCResultSet::UpdateDate (Int_t columnIndex, const TSQLDate & x) virtual
Implements TSQLResultSet.
Definition at line 1840 of file ODBCResultSet.cxx.
View newest version in sPHENIX GitHub at line 1840 of file ODBCResultSet.cxx
References Acts::UnitConstants::e, TSQL::fImp, TSQLDate::GetDay(), odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), TSQLDate::GetMonth(), odbc::SQLException::getSQLState(), TSQLDate::GetYear(), ODBCXX_STRING_CSTR, TSQL::Throw(), and odbc::ResultSet::updateDate().
Referenced by UpdateDate().
void ODBCResultSet::UpdateDate (const TString & columnName, const TSQLDate & x) virtual
Implements TSQLResultSet.
Definition at line 2218 of file ODBCResultSet.cxx.
View newest version in sPHENIX GitHub at line 2218 of file ODBCResultSet.cxx
References FindColumn(), and UpdateDate().
void ODBCResultSet::UpdateDouble (Int_t columnIndex, Double_t x) virtual
Implements TSQLResultSet.
Definition at line 1751 of file ODBCResultSet.cxx.
View newest version in sPHENIX GitHub at line 1751 of file ODBCResultSet.cxx
References Acts::UnitConstants::e, TSQL::fImp, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), ODBCXX_STRING_CSTR, TSQL::Throw(), and odbc::ResultSet::updateDouble().
Referenced by UpdateDouble().
void ODBCResultSet::UpdateDouble (const TString & columnName, Double_t x) virtual
Implements TSQLResultSet.
Definition at line 2162 of file ODBCResultSet.cxx.
View newest version in sPHENIX GitHub at line 2162 of file ODBCResultSet.cxx
References FindColumn(), and UpdateDouble().
void ODBCResultSet::UpdateFloat (Int_t columnIndex, Float_t x) virtual
Implements TSQLResultSet.
Definition at line 1723 of file ODBCResultSet.cxx.
View newest version in sPHENIX GitHub at line 1723 of file ODBCResultSet.cxx
References Acts::UnitConstants::e, TSQL::fImp, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), ODBCXX_STRING_CSTR, TSQL::Throw(), and odbc::ResultSet::updateFloat().
Referenced by UpdateFloat().
void ODBCResultSet::UpdateFloat (const TString & columnName, Float_t x) virtual
Implements TSQLResultSet.
Definition at line 2144 of file ODBCResultSet.cxx.
View newest version in sPHENIX GitHub at line 2144 of file ODBCResultSet.cxx
References FindColumn(), and UpdateFloat().
void ODBCResultSet::UpdateInt (Int_t columnIndex, Int_t x) virtual
Implements TSQLResultSet.
Definition at line 1667 of file ODBCResultSet.cxx.
View newest version in sPHENIX GitHub at line 1667 of file ODBCResultSet.cxx
References Acts::UnitConstants::e, TSQL::fImp, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), ODBCXX_STRING_CSTR, TSQL::Throw(), and odbc::ResultSet::updateInt().
Referenced by UpdateInt().
void ODBCResultSet::UpdateInt (const TString & columnName, Int_t x) virtual
Implements TSQLResultSet.
Definition at line 2108 of file ODBCResultSet.cxx.
View newest version in sPHENIX GitHub at line 2108 of file ODBCResultSet.cxx
References FindColumn(), and UpdateInt().
void ODBCResultSet::UpdateLong (Int_t columnIndex, Long_t x) virtual
Implements TSQLResultSet.
Definition at line 1695 of file ODBCResultSet.cxx.
View newest version in sPHENIX GitHub at line 1695 of file ODBCResultSet.cxx
References Acts::UnitConstants::e, TSQL::fImp, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), ODBCXX_STRING_CSTR, TSQL::Throw(), and odbc::ResultSet::updateLong().
Referenced by UpdateLong().
void ODBCResultSet::UpdateLong (const TString & columnName, Long_t x) virtual
Implements TSQLResultSet.
Definition at line 2126 of file ODBCResultSet.cxx.
View newest version in sPHENIX GitHub at line 2126 of file ODBCResultSet.cxx
References FindColumn(), and UpdateLong().
void ODBCResultSet::UpdateNull (Int_t columnIndex) virtual
Implements TSQLResultSet.
Definition at line 1556 of file ODBCResultSet.cxx.
View newest version in sPHENIX GitHub at line 1556 of file ODBCResultSet.cxx
References Acts::UnitConstants::e, TSQL::fImp, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), ODBCXX_STRING_CSTR, TSQL::Throw(), and odbc::ResultSet::updateNull().
Referenced by UpdateNull().
void ODBCResultSet::UpdateNull (const TString & columnName) virtual
Implements TSQLResultSet.
Definition at line 2036 of file ODBCResultSet.cxx.
View newest version in sPHENIX GitHub at line 2036 of file ODBCResultSet.cxx
References FindColumn(), and UpdateNull().
void ODBCResultSet::UpdateObject (Int_t columnIndex, TObject * x) virtual
Implements TSQLResultSet.
Definition at line 2009 of file ODBCResultSet.cxx.
View newest version in sPHENIX GitHub at line 2009 of file ODBCResultSet.cxx
References KFPMath::b, and UpdateBinaryStream().
Referenced by UpdateObject().
void ODBCResultSet::UpdateObject (const TString & columnName, TObject * x) virtual
Implements TSQLResultSet.
Definition at line 2317 of file ODBCResultSet.cxx.
View newest version in sPHENIX GitHub at line 2317 of file ODBCResultSet.cxx
References FindColumn(), and UpdateObject().
void ODBCResultSet::UpdateRow () virtual
Implements TSQLResultSet.
Definition at line 2362 of file ODBCResultSet.cxx.
View newest version in sPHENIX GitHub at line 2362 of file ODBCResultSet.cxx
References Acts::UnitConstants::e, TSQL::fImp, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), ODBCXX_STRING_CSTR, TSQL::Throw(), and odbc::ResultSet::updateRow().
void ODBCResultSet::UpdateShort (Int_t columnIndex, Short_t x) virtual
Implements TSQLResultSet.
Definition at line 1639 of file ODBCResultSet.cxx.
View newest version in sPHENIX GitHub at line 1639 of file ODBCResultSet.cxx
References Acts::UnitConstants::e, TSQL::fImp, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), ODBCXX_STRING_CSTR, TSQL::Throw(), and odbc::ResultSet::updateShort().
Referenced by UpdateShort().
void ODBCResultSet::UpdateShort (const TString & columnName, Short_t x) virtual
Implements TSQLResultSet.
Definition at line 2090 of file ODBCResultSet.cxx.
View newest version in sPHENIX GitHub at line 2090 of file ODBCResultSet.cxx
References FindColumn(), and UpdateShort().
void ODBCResultSet::UpdateString (Int_t columnIndex, const TString & x) virtual
Implements TSQLResultSet.
Definition at line 1780 of file ODBCResultSet.cxx.
View newest version in sPHENIX GitHub at line 1780 of file ODBCResultSet.cxx
References Acts::UnitConstants::e, TSQL::fImp, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), ODBCXX_STRING, ODBCXX_STRING_C, ODBCXX_STRING_CSTR, physmon_simulation::s, TSQL::Throw(), and odbc::ResultSet::updateString().
Referenced by UpdateString().
void ODBCResultSet::UpdateString (const TString & columnName, const TString & x) virtual
Implements TSQLResultSet.
Definition at line 2180 of file ODBCResultSet.cxx.
View newest version in sPHENIX GitHub at line 2180 of file ODBCResultSet.cxx
References FindColumn(), and UpdateString().
void ODBCResultSet::UpdateTime (Int_t columnIndex, const TSQLTime & x) virtual
Implements TSQLResultSet.
Definition at line 1873 of file ODBCResultSet.cxx.
View newest version in sPHENIX GitHub at line 1873 of file ODBCResultSet.cxx
References Acts::UnitConstants::e, TSQL::fImp, odbc::SQLException::getErrorCode(), TSQLTime::GetHour(), odbc::SQLException::getMessage(), TSQLTime::GetMinute(), TSQLTime::GetSecond(), odbc::SQLException::getSQLState(), ODBCXX_STRING_CSTR, TSQL::Throw(), and odbc::ResultSet::updateTime().
Referenced by UpdateTime().
void ODBCResultSet::UpdateTime (const TString & columnName, const TSQLTime & x) virtual
Implements TSQLResultSet.
Definition at line 2237 of file ODBCResultSet.cxx.
View newest version in sPHENIX GitHub at line 2237 of file ODBCResultSet.cxx
References FindColumn(), and UpdateTime().
void ODBCResultSet::UpdateTimestamp (Int_t columnIndex, const TSQLTimestamp & x) virtual
Implements TSQLResultSet.
Definition at line 1906 of file ODBCResultSet.cxx.
View newest version in sPHENIX GitHub at line 1906 of file ODBCResultSet.cxx
References Acts::UnitConstants::e, TSQL::fImp, TSQLTimestamp::GetDay(), odbc::SQLException::getErrorCode(), TSQLTimestamp::GetHour(), odbc::SQLException::getMessage(), TSQLTimestamp::GetMinute(), TSQLTimestamp::GetMonth(), TSQLTimestamp::GetNanos(), TSQLTimestamp::GetSecond(), odbc::SQLException::getSQLState(), TSQLTimestamp::GetYear(), ODBCXX_STRING_CSTR, TSQL::Throw(), and odbc::ResultSet::updateTimestamp().
Referenced by UpdateTimestamp().
void ODBCResultSet::UpdateTimestamp (const TString & columnName, const TSQLTimestamp & x) virtual
Implements TSQLResultSet.
Definition at line 2256 of file ODBCResultSet.cxx.
View newest version in sPHENIX GitHub at line 2256 of file ODBCResultSet.cxx
References FindColumn(), and UpdateTimestamp().
Bool_t ODBCResultSet::WasNull () virtual
Implements TSQLResultSet.
Definition at line 226 of file ODBCResultSet.cxx.
View newest version in sPHENIX GitHub at line 226 of file ODBCResultSet.cxx
References Acts::UnitConstants::e, TSQL::fImp, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), ODBCXX_STRING_CSTR, TSQL::Throw(), and odbc::ResultSet::wasNull().
Friends And Related Function Documentation
friend class ODBCCallableStatement friend
Definition at line 21 of file ODBCResultSet.h.
View newest version in sPHENIX GitHub at line 21 of file ODBCResultSet.h
friend class ODBCDatabaseMetaData friend
Definition at line 22 of file ODBCResultSet.h.
View newest version in sPHENIX GitHub at line 22 of file ODBCResultSet.h
friend class ODBCPreparedStatement friend
Definition at line 20 of file ODBCResultSet.h.
View newest version in sPHENIX GitHub at line 20 of file ODBCResultSet.h
friend class ODBCStatement friend
Definition at line 19 of file ODBCResultSet.h.
View newest version in sPHENIX GitHub at line 19 of file ODBCResultSet.h
The documentation for this class was generated from the following files:
RDBC/blob/master/odbc/ODBCResultSet.h
RDBC/blob/master/odbc/ODBCResultSet.cxx