Analysis Software: MbdVertexMap Class Reference
MbdVertexMap Class Reference
#include <coresoftware/blob/master/offline/packages/globalvertex/MbdVertexMap.h>
Public Types
typedef std::map< unsigned int,
MbdVertex * >::const_iterator ConstIter
typedef std::map< unsigned int,
MbdVertex * >::iterator Iter
Public Member Functions
~MbdVertexMap () override
void identify (std::ostream &os=std::cout) const override
int isValid () const override
isValid returns non zero if object contains vailid data
virtual bool empty () const
virtual size_t size () const
virtual size_t count (unsigned int) const
virtual void clear ()
virtual const MbdVertex * get (unsigned int) const
virtual MbdVertex * get (unsigned int)
virtual MbdVertex * insert (MbdVertex *)
virtual size_t erase (unsigned int)
virtual ConstIter begin () const
virtual ConstIter find (unsigned int idkey) const
virtual ConstIter end () const
virtual Iter begin ()
virtual Iter find (unsigned int idkey)
virtual Iter end ()
Public Member Functions inherited from PHObject
PHObject ()
ctor
~PHObject () override
dtor
virtual PHObject * CloneMe () const
Virtual copy constructor.
virtual PHObject * clone () const final
PHObject * Clone (const char *newname="") const final
void Copy (TObject &object) const final
virtual void Reset ()
Clear Event.
virtual int Integrate () const
virtual int Integrate (PHObject *)
virtual void CopyFrom (const PHObject *obj)
Protected Member Functions
MbdVertexMap ()
Private Member Functions
ClassDefOverride (MbdVertexMap, 1)
Detailed Description
Definition at line 12 of file MbdVertexMap.h.
View newest version in sPHENIX GitHub at line 12 of file MbdVertexMap.h
Member Typedef Documentation
typedef std::map<unsigned int, MbdVertex*>::const_iterator MbdVertexMap::ConstIter
Definition at line 15 of file MbdVertexMap.h.
View newest version in sPHENIX GitHub at line 15 of file MbdVertexMap.h
typedef std::map<unsigned int, MbdVertex*>::iterator MbdVertexMap::Iter
Definition at line 16 of file MbdVertexMap.h.
View newest version in sPHENIX GitHub at line 16 of file MbdVertexMap.h
Constructor & Destructor Documentation
MbdVertexMap::~MbdVertexMap () inline override
Definition at line 18 of file MbdVertexMap.h.
View newest version in sPHENIX GitHub at line 18 of file MbdVertexMap.h
MbdVertexMap::MbdVertexMap () inline protected
Definition at line 42 of file MbdVertexMap.h.
View newest version in sPHENIX GitHub at line 42 of file MbdVertexMap.h
Member Function Documentation
MbdVertexMap::ConstIter MbdVertexMap::begin (void) const virtual
Reimplemented in MbdVertexMapv1.
Definition at line 7 of file MbdVertexMap.cc.
View newest version in sPHENIX GitHub at line 7 of file MbdVertexMap.cc
Referenced by RawClusterZVertexRecorrect::process_event(), RawClusterBuilderTemplate::process_event(), and DumpMbdVertexMap::process_Node().
MbdVertexMap::Iter MbdVertexMap::begin (void) virtual
Reimplemented in MbdVertexMapv1.
Definition at line 22 of file MbdVertexMap.cc.
View newest version in sPHENIX GitHub at line 22 of file MbdVertexMap.cc
MbdVertexMap::ClassDefOverride (MbdVertexMap , 1) private
virtual void MbdVertexMap::clear () inline virtual
Reimplemented in MbdVertexMapv1.
Definition at line 26 of file MbdVertexMap.h.
View newest version in sPHENIX GitHub at line 26 of file MbdVertexMap.h
virtual size_t MbdVertexMap::count (unsigned int) const inline virtual
Reimplemented in MbdVertexMapv1.
Definition at line 25 of file MbdVertexMap.h.
View newest version in sPHENIX GitHub at line 25 of file MbdVertexMap.h
virtual bool MbdVertexMap::empty () const inline virtual
Reimplemented in MbdVertexMapv1.
Definition at line 23 of file MbdVertexMap.h.
View newest version in sPHENIX GitHub at line 23 of file MbdVertexMap.h
MbdVertexMap::ConstIter MbdVertexMap::end (void) const virtual
Reimplemented in MbdVertexMapv1.
Definition at line 17 of file MbdVertexMap.cc.
View newest version in sPHENIX GitHub at line 17 of file MbdVertexMap.cc
Referenced by RawClusterZVertexRecorrect::process_event(), RawClusterBuilderTemplate::process_event(), and DumpMbdVertexMap::process_Node().
MbdVertexMap::Iter MbdVertexMap::end (void) virtual
Reimplemented in MbdVertexMapv1.
Definition at line 32 of file MbdVertexMap.cc.
View newest version in sPHENIX GitHub at line 32 of file MbdVertexMap.cc
virtual size_t MbdVertexMap::erase (unsigned int) inline virtual
Reimplemented in MbdVertexMapv1.
Definition at line 31 of file MbdVertexMap.h.
View newest version in sPHENIX GitHub at line 31 of file MbdVertexMap.h
MbdVertexMap::ConstIter MbdVertexMap::find (unsigned int idkey) const virtual
Reimplemented in MbdVertexMapv1.
Definition at line 12 of file MbdVertexMap.cc.
View newest version in sPHENIX GitHub at line 12 of file MbdVertexMap.cc
MbdVertexMap::Iter MbdVertexMap::find (unsigned int idkey) virtual
Reimplemented in MbdVertexMapv1.
Definition at line 27 of file MbdVertexMap.cc.
View newest version in sPHENIX GitHub at line 27 of file MbdVertexMap.cc
virtual const MbdVertex* MbdVertexMap::get (unsigned int) const inline virtual
Reimplemented in MbdVertexMapv1.
Definition at line 28 of file MbdVertexMap.h.
View newest version in sPHENIX GitHub at line 28 of file MbdVertexMap.h
virtual MbdVertex* MbdVertexMap::get (unsigned int) inline virtual
Reimplemented in MbdVertexMapv1.
Definition at line 29 of file MbdVertexMap.h.
View newest version in sPHENIX GitHub at line 29 of file MbdVertexMap.h
void MbdVertexMap::identify (std::ostream & os = std::cout) const inline override virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from PHObject.
Reimplemented in MbdVertexMapv1.
Definition at line 20 of file MbdVertexMap.h.
View newest version in sPHENIX GitHub at line 20 of file MbdVertexMap.h
References os.
virtual MbdVertex* MbdVertexMap::insert (MbdVertex *) inline virtual
Reimplemented in MbdVertexMapv1.
Definition at line 30 of file MbdVertexMap.h.
View newest version in sPHENIX GitHub at line 30 of file MbdVertexMap.h
Referenced by MbdReco::process_event(), and MbdVertexFastSimReco::process_event().
int MbdVertexMap::isValid () const inline override virtual
isValid returns non zero if object contains vailid data
Reimplemented from PHObject.
Reimplemented in MbdVertexMapv1.
Definition at line 21 of file MbdVertexMap.h.
View newest version in sPHENIX GitHub at line 21 of file MbdVertexMap.h
virtual size_t MbdVertexMap::size (void) const inline virtual
Reimplemented in MbdVertexMapv1.
Definition at line 24 of file MbdVertexMap.h.
View newest version in sPHENIX GitHub at line 24 of file MbdVertexMap.h
Referenced by DumpMbdVertexMap::process_Node().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/globalvertex/MbdVertexMap.h
coresoftware/blob/master/offline/packages/globalvertex/MbdVertexMap.cc