Analysis Software: InputFileHandler Class Reference
InputFileHandler Class Reference
#include <coresoftware/blob/master/offline/framework/fun4all/InputFileHandler.h>
Public Member Functions
InputFileHandler ()=default
virtual ~InputFileHandler ()=default
virtual int fileopen (const std::string &)
virtual int fileclose ()
int OpenNextFile ()
int AddListFile (const std::string &filename)
int AddFile (const std::string &filename)
void AddToFileOpened (const std::string &filename)
void Print (const std::string &what="ALL") const
int IsOpen () const
void IsOpen (const int i)
void SetVerbosity (const int i)
int GetVerbosity () const
void UpdateFileList ()
void FileName (const std::string &fn)
const std::string FileName () const
Private Attributes
int m_IsOpen = 0
int m_Repeat = 0
int m_Verbosity = 0
std::string m_FileName
std::list< std::string > m_FileList
std::list< std::string > m_FileListCopy
std::list< std::string > m_FileListOpened
Detailed Description
Definition at line 7 of file InputFileHandler.h.
View newest version in sPHENIX GitHub at line 7 of file InputFileHandler.h
Constructor & Destructor Documentation
InputFileHandler::InputFileHandler () default
virtual InputFileHandler::~InputFileHandler () virtual default
Member Function Documentation
int InputFileHandler::AddFile (const std::string & filename)
Definition at line 10 of file InputFileHandler.cc.
View newest version in sPHENIX GitHub at line 10 of file InputFileHandler.cc
References GetVerbosity(), m_FileList, and m_FileListCopy.
Referenced by AddListFile(), and Fun4AllPrdfInputPoolManager::AddPrdfInputFile().
int InputFileHandler::AddListFile (const std::string & filename)
Definition at line 21 of file InputFileHandler.cc.
View newest version in sPHENIX GitHub at line 21 of file InputFileHandler.cc
References AddFile(), Acts::Concepts::exists, GetVerbosity(), in, infile, and PHWHERE.
Referenced by Fun4AllPrdfInputPoolManager::AddPrdfInputList(), Fun4All_Intt_Combiner(), Fun4All_Mvtx_Combiner(), Fun4All_SingleMvtx(), Fun4All_Stream_Combiner(), and Fun4All_Tpc_Combiner().
void InputFileHandler::AddToFileOpened (const std::string & filename) inline
Definition at line 17 of file InputFileHandler.h.
View newest version in sPHENIX GitHub at line 17 of file InputFileHandler.h
References m_FileListOpened.
Referenced by SinglePrdfInput::fileopen(), and SingleStreamingInput::fileopen().
virtual int InputFileHandler::fileclose () inline virtual
Reimplemented in SinglePrdfInput, and SingleStreamingInput.
Definition at line 13 of file InputFileHandler.h.
View newest version in sPHENIX GitHub at line 13 of file InputFileHandler.h
void InputFileHandler::FileName (const std::string & fn) inline
Definition at line 24 of file InputFileHandler.h.
View newest version in sPHENIX GitHub at line 24 of file InputFileHandler.h
References m_FileName.
const std::string InputFileHandler::FileName () const inline
Definition at line 25 of file InputFileHandler.h.
View newest version in sPHENIX GitHub at line 25 of file InputFileHandler.h
References m_FileName.
Referenced by SinglePrdfInput::fileopen(), and SingleStreamingInput::fileopen().
virtual int InputFileHandler::fileopen (const std::string &) inline virtual
Reimplemented in SinglePrdfInput, and SingleStreamingInput.
Definition at line 12 of file InputFileHandler.h.
View newest version in sPHENIX GitHub at line 12 of file InputFileHandler.h
Referenced by OpenNextFile().
int InputFileHandler::GetVerbosity () const inline
Definition at line 22 of file InputFileHandler.h.
View newest version in sPHENIX GitHub at line 22 of file InputFileHandler.h
References m_Verbosity.
Referenced by AddFile(), AddListFile(), SingleGl1PoolInput::FillPool(), SingleTpcPoolInput::FillPool(), SingleInttPoolInput::FillPool(), SingleMvtxPoolInput::FillPool(), and OpenNextFile().
int InputFileHandler::IsOpen () const inline
Definition at line 19 of file InputFileHandler.h.
View newest version in sPHENIX GitHub at line 19 of file InputFileHandler.h
References m_IsOpen.
Referenced by SinglePrdfInput::fileclose(), SingleStreamingInput::fileclose(), SingleStreamingInput::fileopen(), and SinglePrdfInput::fileopen().
void InputFileHandler::IsOpen (const int i) inline
Definition at line 20 of file InputFileHandler.h.
View newest version in sPHENIX GitHub at line 20 of file InputFileHandler.h
References i, and m_IsOpen.
int InputFileHandler::OpenNextFile ()
Definition at line 82 of file InputFileHandler.cc.
View newest version in sPHENIX GitHub at line 82 of file InputFileHandler.cc
References fileopen(), GetVerbosity(), m_FileList, and PHWHERE.
Referenced by SingleGl1PoolInput::FillPool(), SingleTpcPoolInput::FillPool(), SingleMicromegasPoolInput::FillPool(), SingleZdcInput::FillPool(), SingleInttPoolInput::FillPool(), SinglePrdfInput::FillPool(), and SingleMvtxPoolInput::FillPool().
void InputFileHandler::Print (const std::string & what = "ALL") const
Definition at line 104 of file InputFileHandler.cc.
View newest version in sPHENIX GitHub at line 104 of file InputFileHandler.cc
References m_FileList.
void InputFileHandler::SetVerbosity (const int i) inline
Definition at line 21 of file InputFileHandler.h.
View newest version in sPHENIX GitHub at line 21 of file InputFileHandler.h
References i, and m_Verbosity.
void InputFileHandler::UpdateFileList ()
Definition at line 113 of file InputFileHandler.cc.
View newest version in sPHENIX GitHub at line 113 of file InputFileHandler.cc
References m_FileList, and m_Repeat.
Referenced by SinglePrdfInput::fileclose(), and SingleStreamingInput::fileclose().
Member Data Documentation
std::list<std::string> InputFileHandler::m_FileList private
Definition at line 32 of file InputFileHandler.h.
View newest version in sPHENIX GitHub at line 32 of file InputFileHandler.h
Referenced by AddFile(), OpenNextFile(), Print(), and UpdateFileList().
std::list<std::string> InputFileHandler::m_FileListCopy private
Definition at line 33 of file InputFileHandler.h.
View newest version in sPHENIX GitHub at line 33 of file InputFileHandler.h
Referenced by AddFile().
std::list<std::string> InputFileHandler::m_FileListOpened private
Definition at line 34 of file InputFileHandler.h.
View newest version in sPHENIX GitHub at line 34 of file InputFileHandler.h
Referenced by AddToFileOpened().
std::string InputFileHandler::m_FileName private
Definition at line 31 of file InputFileHandler.h.
View newest version in sPHENIX GitHub at line 31 of file InputFileHandler.h
Referenced by FileName().
int InputFileHandler::m_IsOpen = 0 private
Definition at line 28 of file InputFileHandler.h.
View newest version in sPHENIX GitHub at line 28 of file InputFileHandler.h
Referenced by IsOpen().
int InputFileHandler::m_Repeat = 0 private
Definition at line 29 of file InputFileHandler.h.
View newest version in sPHENIX GitHub at line 29 of file InputFileHandler.h
Referenced by UpdateFileList().
int InputFileHandler::m_Verbosity = 0 private
Definition at line 30 of file InputFileHandler.h.
View newest version in sPHENIX GitHub at line 30 of file InputFileHandler.h
Referenced by GetVerbosity(), and SetVerbosity().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/framework/fun4all/InputFileHandler.h
coresoftware/blob/master/offline/framework/fun4all/InputFileHandler.cc