Analysis Software: macros/blob/master/common/CDBUtils.C File Reference
CDBUtils.C File Reference
#include <sphenixnpc/CDBUtils.h>
#include <sphenixnpc/SphenixClient.h>
#include <phool/recoConsts.h>
Macros
#define CDBUTILS_C
Functions
CDBUtils * getCDBUtils ()
void listGlobalTags ()
void listPayloadTypes ()
void listPayloadIOVs (uint64_t iov)
void createGlobalTag (const std::string &tagname)
void deleteGlobalTag (const std::string &tagname)
void lockGlobalTag (const std::string &tagname)
void unlockGlobalTag (const std::string &tagname)
int setGlobalTag (const std::string &tagname)
int cloneGlobalTag (const std::string &source, const std::string &target)
int createPayloadType (const std::string &pt)
int insertPayload (const std::string &pl_type, const std::string &file_url, uint64_t iov_start)
int insertPayload (const std::string &pl_type, const std::string &file_url, uint64_t iov_start, uint64_t iov_end)
std::string getCalibration (const std::string &pl_type, uint64_t iov)
void clearCache ()
void Verbosity (int verb)
int deletePayloadIOV (const std::string &pl_type, uint64_t iov_start)
int deletePayloadIOV (const std::string &pl_type, uint64_t iov_start, uint64_t iov_end)
Variables
CDBUtils * uti = nullptr
Macro Definition Documentation
#define CDBUTILS_C
Definition at line 2 of file CDBUtils.C.
View newest version in sPHENIX GitHub at line 2 of file CDBUtils.C
Function Documentation
void clearCache ()
Definition at line 116 of file CDBUtils.C.
View newest version in sPHENIX GitHub at line 116 of file CDBUtils.C
References CDBUtils::clearCache(), and uti.
int cloneGlobalTag (const std::string & source, const std::string & target)
Definition at line 75 of file CDBUtils.C.
View newest version in sPHENIX GitHub at line 75 of file CDBUtils.C
References CDBUtils::cloneGlobalTag(), and uti.
void createGlobalTag (const std::string & tagname)
Definition at line 40 of file CDBUtils.C.
View newest version in sPHENIX GitHub at line 40 of file CDBUtils.C
References CDBUtils::createGlobalTag(), and uti.
int createPayloadType (const std::string & pt)
Definition at line 83 of file CDBUtils.C.
View newest version in sPHENIX GitHub at line 83 of file CDBUtils.C
References CDBUtils::createPayloadType(), and uti.
void deleteGlobalTag (const std::string & tagname)
Definition at line 47 of file CDBUtils.C.
View newest version in sPHENIX GitHub at line 47 of file CDBUtils.C
References CDBUtils::deleteGlobalTag(), and uti.
int deletePayloadIOV (const std::string & pl_type, uint64_t iov_start)
Definition at line 128 of file CDBUtils.C.
View newest version in sPHENIX GitHub at line 128 of file CDBUtils.C
References CDBUtils::deletePayloadIOV(), and uti.
int deletePayloadIOV (const std::string & pl_type, uint64_t iov_start, uint64_t iov_end)
Definition at line 134 of file CDBUtils.C.
View newest version in sPHENIX GitHub at line 134 of file CDBUtils.C
References CDBUtils::deletePayloadIOV(), and uti.
std::string getCalibration (const std::string & pl_type, uint64_t iov)
Definition at line 110 of file CDBUtils.C.
View newest version in sPHENIX GitHub at line 110 of file CDBUtils.C
References CDBUtils::getUrl(), and uti.
CDBUtils* getCDBUtils ()
Definition at line 14 of file CDBUtils.C.
View newest version in sPHENIX GitHub at line 14 of file CDBUtils.C
References uti.
int insertPayload (const std::string & pl_type, const std::string & file_url, uint64_t iov_start)
Definition at line 90 of file CDBUtils.C.
View newest version in sPHENIX GitHub at line 90 of file CDBUtils.C
References CDBUtils::insertPayload(), CDBUtils::isGlobalTagSet(), and uti.
int insertPayload (const std::string & pl_type, const std::string & file_url, uint64_t iov_start, uint64_t iov_end)
Definition at line 100 of file CDBUtils.C.
View newest version in sPHENIX GitHub at line 100 of file CDBUtils.C
References CDBUtils::insertPayload(), CDBUtils::isGlobalTagSet(), and uti.
void listGlobalTags ()
Definition at line 19 of file CDBUtils.C.
View newest version in sPHENIX GitHub at line 19 of file CDBUtils.C
References CDBUtils::listGlobalTags(), and uti.
void listPayloadIOVs (uint64_t iov)
Definition at line 33 of file CDBUtils.C.
View newest version in sPHENIX GitHub at line 33 of file CDBUtils.C
References CDBUtils::listPayloadIOVs(), and uti.
void listPayloadTypes ()
Definition at line 26 of file CDBUtils.C.
View newest version in sPHENIX GitHub at line 26 of file CDBUtils.C
References CDBUtils::listPayloadTypes(), and uti.
void lockGlobalTag (const std::string & tagname)
Definition at line 54 of file CDBUtils.C.
View newest version in sPHENIX GitHub at line 54 of file CDBUtils.C
References CDBUtils::lockGlobalTag(), and uti.
int setGlobalTag (const std::string & tagname)
Definition at line 68 of file CDBUtils.C.
View newest version in sPHENIX GitHub at line 68 of file CDBUtils.C
References CDBUtils::setGlobalTag(), and uti.
void unlockGlobalTag (const std::string & tagname)
Definition at line 61 of file CDBUtils.C.
View newest version in sPHENIX GitHub at line 61 of file CDBUtils.C
References CDBUtils::unlockGlobalTag(), and uti.
void Verbosity (int verb)
Definition at line 122 of file CDBUtils.C.
View newest version in sPHENIX GitHub at line 122 of file CDBUtils.C
References uti, and CDBUtils::Verbosity().
Variable Documentation
CDBUtils* uti = nullptr
Definition at line 12 of file CDBUtils.C.
View newest version in sPHENIX GitHub at line 12 of file CDBUtils.C