Analysis Software: RawTowerGeomContainerv1 Class Reference
RawTowerGeomContainerv1 Class Reference
Generic tower geometry class, store each tower's geometry individually.
#include <coresoftware/blob/master/offline/packages/CaloBase/RawTowerGeomContainerv1.h>
Public Member Functions
RawTowerGeomContainerv1 (RawTowerDefs::CalorimeterId caloid=RawTowerDefs::NONE)
~RawTowerGeomContainerv1 () override
void Reset () override
Clear Event.
int isValid () const override
isValid returns non zero if object contains vailid data
void identify (std::ostream &os=std::cout) const override
void set_calorimeter_id (RawTowerDefs::CalorimeterId caloid) override
8-bit calorimeter ID
RawTowerDefs::CalorimeterId get_calorimeter_id () const override
ConstIterator add_tower_geometry (RawTowerGeom *geo) override
go through all towers
RawTowerGeom * get_tower_geometry (RawTowerDefs::keytype key) override
ConstRange get_tower_geometries (void) const override
return all tower geometries
Range get_tower_geometries (void) override
unsigned int size () const override
Public Member Functions inherited from RawTowerGeomContainer
~RawTowerGeomContainer () override
default constructor for ROOT IO
virtual double get_radius () const
virtual double get_thickness () const
virtual int get_phibins () const
virtual int get_etabins () const
virtual std::pair< double, double > get_phibounds (const int) const
virtual std::pair< double, double > get_etabounds (const int) const
virtual double get_etacenter (const int) const
virtual double get_phicenter (const int) const
virtual int get_etabin (const double) const
virtual int get_phibin (const double) const
virtual void set_radius (const double)
virtual void set_thickness (const double)
virtual void set_phibins (const int)
virtual void set_etabins (const int)
virtual void set_etabounds (const int, const std::pair< double, double > &)
virtual void set_phibounds (const int, const std::pair< double, double > &)
Public Member Functions inherited from PHObject
PHObject ()
ctor
~PHObject () override
dtor
virtual PHObject * CloneMe () const
Virtual copy constructor.
virtual PHObject * clone () const final
PHObject * Clone (const char *newname="") const final
void Copy (TObject &object) const final
virtual int Integrate () const
virtual int Integrate (PHObject *)
virtual void CopyFrom (const PHObject *obj)
Protected Attributes
RawTowerDefs::CalorimeterId _caloid
Map _geoms
Additional Inherited Members
Public Types inherited from RawTowerGeomContainer
typedef std::map
< RawTowerDefs::keytype,
RawTowerGeom * > Map
typedef Map::iterator Iterator
typedef Map::const_iterator ConstIterator
typedef std::pair< Iterator,
Iterator > Range
typedef std::pair
< ConstIterator, ConstIterator > ConstRange
Protected Member Functions inherited from RawTowerGeomContainer
RawTowerGeomContainer ()
this class is not for use. Base class only
Detailed Description
Generic tower geometry class, store each tower's geometry individually.
Definition at line 15 of file RawTowerGeomContainerv1.h.
View newest version in sPHENIX GitHub at line 15 of file RawTowerGeomContainerv1.h
Constructor & Destructor Documentation
RawTowerGeomContainerv1::RawTowerGeomContainerv1 (RawTowerDefs::CalorimeterId caloid = RawTowerDefs::NONE)
Definition at line 13 of file RawTowerGeomContainerv1.cc.
View newest version in sPHENIX GitHub at line 13 of file RawTowerGeomContainerv1.cc
RawTowerGeomContainerv1::~RawTowerGeomContainerv1 () override
Definition at line 18 of file RawTowerGeomContainerv1.cc.
View newest version in sPHENIX GitHub at line 18 of file RawTowerGeomContainerv1.cc
References Reset().
Member Function Documentation
RawTowerGeomContainerv1::ConstIterator RawTowerGeomContainerv1::add_tower_geometry (RawTowerGeom * geo) override virtual
go through all towers
Reimplemented from RawTowerGeomContainer.
Definition at line 36 of file RawTowerGeomContainerv1.cc.
View newest version in sPHENIX GitHub at line 36 of file RawTowerGeomContainerv1.cc
References _geoms, assert, RawTowerDefs::decode_caloid(), get_calorimeter_id(), RawTowerGeom::get_id(), RawTowerGeom::identify(), and it.
RawTowerDefs::CalorimeterId RawTowerGeomContainerv1::get_calorimeter_id () const inline override virtual
Reimplemented from RawTowerGeomContainer.
Definition at line 27 of file RawTowerGeomContainerv1.h.
View newest version in sPHENIX GitHub at line 27 of file RawTowerGeomContainerv1.h
References _caloid.
Referenced by add_tower_geometry().
RawTowerGeomContainerv1::Range RawTowerGeomContainerv1::get_tower_geometries (void) const override virtual
return all tower geometries
Reimplemented from RawTowerGeomContainer.
Definition at line 24 of file RawTowerGeomContainerv1.cc.
View newest version in sPHENIX GitHub at line 24 of file RawTowerGeomContainerv1.cc
References _geoms.
Range RawTowerGeomContainerv1::get_tower_geometries (void) override virtual
Reimplemented from RawTowerGeomContainer.
RawTowerGeom * RawTowerGeomContainerv1::get_tower_geometry (RawTowerDefs::keytype key) override virtual
Reimplemented from RawTowerGeomContainer.
Definition at line 68 of file RawTowerGeomContainerv1.cc.
View newest version in sPHENIX GitHub at line 68 of file RawTowerGeomContainerv1.cc
References _geoms, and it.
void RawTowerGeomContainerv1::identify (std::ostream & os = std::cout) const override virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from RawTowerGeomContainer.
Definition at line 92 of file RawTowerGeomContainerv1.cc.
View newest version in sPHENIX GitHub at line 92 of file RawTowerGeomContainerv1.cc
References size().
int RawTowerGeomContainerv1::isValid () const override virtual
isValid returns non zero if object contains vailid data
Reimplemented from PHObject.
Definition at line 78 of file RawTowerGeomContainerv1.cc.
View newest version in sPHENIX GitHub at line 78 of file RawTowerGeomContainerv1.cc
References _geoms.
void RawTowerGeomContainerv1::Reset () override virtual
Clear Event.
Reimplemented from PHObject.
Definition at line 83 of file RawTowerGeomContainerv1.cc.
View newest version in sPHENIX GitHub at line 83 of file RawTowerGeomContainerv1.cc
References _geoms.
Referenced by RawTowerGeomContainer_Cylinderv1::Reset(), and ~RawTowerGeomContainerv1().
void RawTowerGeomContainerv1::set_calorimeter_id (RawTowerDefs::CalorimeterId) inline override virtual
8-bit calorimeter ID
Reimplemented from RawTowerGeomContainer.
Definition at line 26 of file RawTowerGeomContainerv1.h.
View newest version in sPHENIX GitHub at line 26 of file RawTowerGeomContainerv1.h
References _caloid.
unsigned int RawTowerGeomContainerv1::size (void) const inline override virtual
Reimplemented from RawTowerGeomContainer.
Definition at line 36 of file RawTowerGeomContainerv1.h.
View newest version in sPHENIX GitHub at line 36 of file RawTowerGeomContainerv1.h
References _geoms.
Referenced by identify().
Member Data Documentation
RawTowerDefs::CalorimeterId RawTowerGeomContainerv1::_caloid protected
Definition at line 39 of file RawTowerGeomContainerv1.h.
View newest version in sPHENIX GitHub at line 39 of file RawTowerGeomContainerv1.h
Referenced by get_calorimeter_id(), and set_calorimeter_id().
Map RawTowerGeomContainerv1::_geoms protected
Definition at line 40 of file RawTowerGeomContainerv1.h.
View newest version in sPHENIX GitHub at line 40 of file RawTowerGeomContainerv1.h
Referenced by add_tower_geometry(), get_tower_geometries(), get_tower_geometry(), isValid(), Reset(), and size().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/CaloBase/RawTowerGeomContainerv1.h
coresoftware/blob/master/offline/packages/CaloBase/RawTowerGeomContainerv1.cc