Analysis Software: RawTower_Temperature Class Reference
RawTower_Temperature Class Reference
#include <analysis/blob/master/EMCTemplateFitting/src/RawTower_Temperature.h>
Public Member Functions
RawTower_Temperature ()
RawTower_Temperature (const unsigned int icol, const unsigned int irow)
RawTower_Temperature (RawTowerDefs::keytype id)
virtual ~RawTower_Temperature ()
void Reset () override
Clear Event.
int isValid () const override
isValid returns non zero if object contains vailid data
void identify (std::ostream &os=std::cout) const override
void print (std::ostream &os=std::cout) const
int get_column () const override
int get_row () const override
void set_id (RawTowerDefs::keytype id) override
RawTowerDefs::keytype get_id () const override
int get_nr_entries () const
int add_entry (const int eventnr, const time_t t, const float temp)
float get_temperature_from_entry (const unsigned int entry) const
time_t get_time_from_entry (const unsigned int entry) const
int get_eventnumber_from_entry (const unsigned int entry) const
float get_temperature_from_time (const time_t t) const
RawTower_Temperature ()
RawTower_Temperature (const unsigned int icol, const unsigned int irow)
RawTower_Temperature (RawTowerDefs::keytype id)
virtual ~RawTower_Temperature ()
void Reset () override
Clear Event.
int isValid () const override
isValid returns non zero if object contains vailid data
void identify (std::ostream &os=std::cout) const override
void print (std::ostream &os=std::cout) const
int get_column () const override
int get_row () const override
void set_id (RawTowerDefs::keytype id) override
RawTowerDefs::keytype get_id () const override
int get_nr_entries () const
int add_entry (const int eventnr, const time_t t, const float temp)
float get_temperature_from_entry (const unsigned int entry) const
time_t get_time_from_entry (const unsigned int entry) const
int get_eventnumber_from_entry (const unsigned int entry) const
float get_temperature_from_time (const time_t t) const
RawTower_Temperature ()
RawTower_Temperature (const unsigned int icol, const unsigned int irow)
RawTower_Temperature (RawTowerDefs::keytype id)
virtual ~RawTower_Temperature ()
void Reset () override
Clear Event.
int isValid () const override
isValid returns non zero if object contains vailid data
void identify (std::ostream &os=std::cout) const override
void print (std::ostream &os=std::cout) const
int get_column () const override
int get_row () const override
void set_id (RawTowerDefs::keytype id) override
RawTowerDefs::keytype get_id () const override
int get_nr_entries () const
int add_entry (const int eventnr, const time_t t, const float temp)
float get_temperature_from_entry (const unsigned int entry) const
time_t get_time_from_entry (const unsigned int entry) const
int get_eventnumber_from_entry (const unsigned int entry) const
float get_temperature_from_time (const time_t t) const
RawTower_Temperature ()
RawTower_Temperature (const unsigned int icol, const unsigned int irow)
RawTower_Temperature (RawTowerDefs::keytype id)
virtual ~RawTower_Temperature ()
void Reset () override
Clear Event.
int isValid () const override
isValid returns non zero if object contains vailid data
void identify (std::ostream &os=std::cout) const override
void print (std::ostream &os=std::cout) const
int get_column () const override
int get_row () const override
void set_id (RawTowerDefs::keytype id) override
RawTowerDefs::keytype get_id () const override
int get_nr_entries () const
int add_entry (const int eventnr, const time_t t, const float temp)
float get_temperature_from_entry (const unsigned int entry) const
time_t get_time_from_entry (const unsigned int entry) const
int get_eventnumber_from_entry (const unsigned int entry) const
float get_temperature_from_time (const time_t t) const
Public Member Functions inherited from RawTower
~RawTower () override
virtual void set_key (RawTowerDefs::keytype id)
virtual RawTowerDefs::keytype get_key () const
virtual int get_bineta () const
virtual int get_bintheta () const
virtual int get_binphi () const
virtual int get_binl () const
return layer ID assigned to tower
virtual double get_energy () const
energy assigned to the tower. Depending on stage of process and DST node name, it could be energy deposition, light yield or calibrated energies
virtual void set_energy (const double)
energy assigned to the tower. Depending on stage of process and DST node name, it could be energy deposition, light yield or calibrated energies
virtual double get_scint_gammas () const
energy assigned to the tower. Depending on stage of process and DST node name, it could be energy deposition, light yield or calibrated energies
virtual void set_scint_gammas (const double)
scint_gammas assigned to the tower. Depending on stage of process and DST node name, it could be scint_gammas deposition, light yield or calibrated energies
virtual double get_cerenkov_gammas () const
energy assigned to the tower. Depending on stage of process and DST node name, it could be energy deposition, light yield or calibrated energies
virtual void set_cerenkov_gammas (const double)
cerenkov_gammas assigned to the tower. Depending on stage of process and DST node name, it could be cerenkov_gammas deposition, light yield or calibrated energies
virtual float get_time () const
Time stamp assigned to the tower. Depending on the tower maker, it could be rise time or peak time.
virtual void set_time (const float)
Time stamp assigned to the tower. Depending on the tower maker, it could be rise time or peak time.
virtual bool empty_g4cells () const
virtual size_t size_g4cells () const
virtual CellConstRange get_g4cells () const
virtual CellIterator find_g4cell (CellKeyType id)
virtual CellConstIterator find_g4cell (CellKeyType id) const
virtual void add_ecell (const CellKeyType, const float)
virtual void clear_g4cells ()
virtual bool empty_g4showers () const
virtual size_t size_g4showers () const
virtual ShowerConstRange get_g4showers () const
virtual ShowerIterator find_g4shower (int)
virtual ShowerConstIterator find_g4shower (int) const
virtual void add_eshower (const int, const float)
virtual void clear_g4showers ()
virtual bool has_property (const PROPERTY) const
virtual double get_property (const PROPERTY) const
virtual void set_property (const PROPERTY, const double)
Public Member Functions inherited from PHObject
PHObject ()
ctor
~PHObject () override
dtor
virtual PHObject * CloneMe () const
Virtual copy constructor.
virtual PHObject * clone () const final
PHObject * Clone (const char *newname="") const final
void Copy (TObject &object) const final
virtual int Integrate () const
virtual int Integrate (PHObject *)
virtual void CopyFrom (const PHObject *obj)
Protected Attributes
RawTowerDefs::keytype towerid
std::vector< int > eventnumbers
std::vector< time_t > times
std::vector< float > temperatures
Additional Inherited Members
Public Types inherited from RawTower
enum PROPERTY { prop_scint_gammas = 1, prop_cerenkov_gammas = 2, prop_MAX_NUMBER = UCHAR_MAX }
typedef unsigned long long CellKeyType
key type for cell map which should be consistent with CellKeyType
typedef std::map< CellKeyType,
float > CellMap
typedef CellMap::iterator CellIterator
typedef CellMap::const_iterator CellConstIterator
typedef std::pair
< CellIterator, CellIterator > CellRange
typedef std::pair
< CellConstIterator,
CellConstIterator > CellConstRange
typedef std::map< int, float > ShowerMap
typedef ShowerMap::iterator ShowerIterator
typedef ShowerMap::const_iterator ShowerConstIterator
typedef std::pair
< ShowerIterator,
ShowerIterator > ShowerRange
typedef std::pair
< ShowerConstIterator,
ShowerConstIterator > ShowerConstRange
Static Public Member Functions inherited from RawTower
static const std::string get_property_info (PROPERTY prop_id)
Protected Member Functions inherited from RawTower
RawTower ()
virtual unsigned int get_property_nocheck (const PROPERTY) const
virtual void set_property_nocheck (const PROPERTY, const unsigned int)
Detailed Description
Definition at line 13 of file RawTower_Temperature.h.
View newest version in sPHENIX GitHub at line 13 of file RawTower_Temperature.h
Constructor & Destructor Documentation
RawTower_Temperature::RawTower_Temperature ()
Definition at line 10 of file RawTower_Temperature.cc.
View newest version in sPHENIX GitHub at line 10 of file RawTower_Temperature.cc
RawTower_Temperature::RawTower_Temperature (const unsigned int icol, const unsigned int irow)
Definition at line 20 of file RawTower_Temperature.cc.
View newest version in sPHENIX GitHub at line 20 of file RawTower_Temperature.cc
References RawTowerDefs::encode_towerid(), and RawTowerDefs::NONE.
RawTower_Temperature::RawTower_Temperature (RawTowerDefs::keytype id)
Definition at line 15 of file RawTower_Temperature.cc.
View newest version in sPHENIX GitHub at line 15 of file RawTower_Temperature.cc
virtual RawTower_Temperature::~RawTower_Temperature () inline virtual
Definition at line 19 of file RawTower_Temperature.h.
View newest version in sPHENIX GitHub at line 19 of file RawTower_Temperature.h
RawTower_Temperature::RawTower_Temperature ()
RawTower_Temperature::RawTower_Temperature (const unsigned int icol, const unsigned int irow)
RawTower_Temperature::RawTower_Temperature (RawTowerDefs::keytype id)
virtual RawTower_Temperature::~RawTower_Temperature () inline virtual
Definition at line 20 of file RawTower_Temperature.h.
View newest version in sPHENIX GitHub at line 20 of file RawTower_Temperature.h
RawTower_Temperature::RawTower_Temperature ()
RawTower_Temperature::RawTower_Temperature (const unsigned int icol, const unsigned int irow)
RawTower_Temperature::RawTower_Temperature (RawTowerDefs::keytype id)
virtual RawTower_Temperature::~RawTower_Temperature () inline virtual
Definition at line 20 of file RawTower_Temperature.h.
View newest version in sPHENIX GitHub at line 20 of file RawTower_Temperature.h
RawTower_Temperature::RawTower_Temperature ()
RawTower_Temperature::RawTower_Temperature (const unsigned int icol, const unsigned int irow)
RawTower_Temperature::RawTower_Temperature (RawTowerDefs::keytype id)
virtual RawTower_Temperature::~RawTower_Temperature () inline virtual
Definition at line 19 of file RawTower_Temperature.h.
View newest version in sPHENIX GitHub at line 19 of file RawTower_Temperature.h
Member Function Documentation
int RawTower_Temperature::add_entry (const int eventnr, const time_t t, const float temp) inline
Definition at line 34 of file RawTower_Temperature.h.
View newest version in sPHENIX GitHub at line 34 of file RawTower_Temperature.h
References eventnumbers, get_nr_entries(), temperatures, and times.
Referenced by TempInfoUnpackPRDF::addPacketInfo().
int RawTower_Temperature::add_entry (const int eventnr, const time_t t, const float temp) inline
Definition at line 34 of file RawTower_Temperature.h.
View newest version in sPHENIX GitHub at line 34 of file RawTower_Temperature.h
References eventnumbers, get_nr_entries(), temperatures, and times.
int RawTower_Temperature::add_entry (const int eventnr, const time_t t, const float temp) inline
Definition at line 35 of file RawTower_Temperature.h.
View newest version in sPHENIX GitHub at line 35 of file RawTower_Temperature.h
References eventnumbers, get_nr_entries(), temperatures, and times.
int RawTower_Temperature::add_entry (const int eventnr, const time_t t, const float temp) inline
Definition at line 35 of file RawTower_Temperature.h.
View newest version in sPHENIX GitHub at line 35 of file RawTower_Temperature.h
References eventnumbers, get_nr_entries(), temperatures, and times.
int RawTower_Temperature::get_column () const inline override virtual
Reimplemented from RawTower.
Definition at line 26 of file RawTower_Temperature.h.
View newest version in sPHENIX GitHub at line 26 of file RawTower_Temperature.h
References RawTowerDefs::decode_index1().
Referenced by identify().
int RawTower_Temperature::get_column () const inline override virtual
Reimplemented from RawTower.
Definition at line 26 of file RawTower_Temperature.h.
View newest version in sPHENIX GitHub at line 26 of file RawTower_Temperature.h
References RawTowerDefs::decode_index1().
int RawTower_Temperature::get_column () const inline override virtual
Reimplemented from RawTower.
Definition at line 27 of file RawTower_Temperature.h.
View newest version in sPHENIX GitHub at line 27 of file RawTower_Temperature.h
References RawTowerDefs::decode_index1().
int RawTower_Temperature::get_column () const inline override virtual
Reimplemented from RawTower.
Definition at line 27 of file RawTower_Temperature.h.
View newest version in sPHENIX GitHub at line 27 of file RawTower_Temperature.h
References RawTowerDefs::decode_index1().
int RawTower_Temperature::get_eventnumber_from_entry (const unsigned int entry) const inline
Definition at line 56 of file RawTower_Temperature.h.
View newest version in sPHENIX GitHub at line 56 of file RawTower_Temperature.h
References entry, and eventnumbers.
Referenced by print().
int RawTower_Temperature::get_eventnumber_from_entry (const unsigned int entry) const inline
Definition at line 56 of file RawTower_Temperature.h.
View newest version in sPHENIX GitHub at line 56 of file RawTower_Temperature.h
References entry, and eventnumbers.
int RawTower_Temperature::get_eventnumber_from_entry (const unsigned int entry) const inline
Definition at line 57 of file RawTower_Temperature.h.
View newest version in sPHENIX GitHub at line 57 of file RawTower_Temperature.h
References entry, and eventnumbers.
int RawTower_Temperature::get_eventnumber_from_entry (const unsigned int entry) const inline
Definition at line 57 of file RawTower_Temperature.h.
View newest version in sPHENIX GitHub at line 57 of file RawTower_Temperature.h
References entry, and eventnumbers.
RawTowerDefs::keytype RawTower_Temperature::get_id () const inline override virtual
Reimplemented from RawTower.
Definition at line 30 of file RawTower_Temperature.h.
View newest version in sPHENIX GitHub at line 30 of file RawTower_Temperature.h
References towerid.
RawTowerDefs::keytype RawTower_Temperature::get_id () const inline override virtual
Reimplemented from RawTower.
Definition at line 30 of file RawTower_Temperature.h.
View newest version in sPHENIX GitHub at line 30 of file RawTower_Temperature.h
References towerid.
RawTowerDefs::keytype RawTower_Temperature::get_id () const inline override virtual
Reimplemented from RawTower.
Definition at line 31 of file RawTower_Temperature.h.
View newest version in sPHENIX GitHub at line 31 of file RawTower_Temperature.h
References towerid.
RawTowerDefs::keytype RawTower_Temperature::get_id () const inline override virtual
Reimplemented from RawTower.
Definition at line 31 of file RawTower_Temperature.h.
View newest version in sPHENIX GitHub at line 31 of file RawTower_Temperature.h
References towerid.
int RawTower_Temperature::get_nr_entries () const inline
Definition at line 32 of file RawTower_Temperature.h.
View newest version in sPHENIX GitHub at line 32 of file RawTower_Temperature.h
References temperatures.
Referenced by add_entry(), get_temperature_from_time(), isValid(), print(), Prototype2DSTReader::process_event(), Prototype3DSTReader::process_event(), and Prototype4DSTReader::process_event().
int RawTower_Temperature::get_nr_entries () const inline
Definition at line 32 of file RawTower_Temperature.h.
View newest version in sPHENIX GitHub at line 32 of file RawTower_Temperature.h
References temperatures.
int RawTower_Temperature::get_nr_entries () const inline
Definition at line 33 of file RawTower_Temperature.h.
View newest version in sPHENIX GitHub at line 33 of file RawTower_Temperature.h
References temperatures.
int RawTower_Temperature::get_nr_entries () const inline
Definition at line 33 of file RawTower_Temperature.h.
View newest version in sPHENIX GitHub at line 33 of file RawTower_Temperature.h
References temperatures.
int RawTower_Temperature::get_row () const inline override virtual
Reimplemented from RawTower.
Definition at line 27 of file RawTower_Temperature.h.
View newest version in sPHENIX GitHub at line 27 of file RawTower_Temperature.h
References RawTowerDefs::decode_index2().
Referenced by identify().
int RawTower_Temperature::get_row () const inline override virtual
Reimplemented from RawTower.
Definition at line 27 of file RawTower_Temperature.h.
View newest version in sPHENIX GitHub at line 27 of file RawTower_Temperature.h
References RawTowerDefs::decode_index2().
int RawTower_Temperature::get_row () const inline override virtual
Reimplemented from RawTower.
Definition at line 28 of file RawTower_Temperature.h.
View newest version in sPHENIX GitHub at line 28 of file RawTower_Temperature.h
References RawTowerDefs::decode_index2().
int RawTower_Temperature::get_row () const inline override virtual
Reimplemented from RawTower.
Definition at line 28 of file RawTower_Temperature.h.
View newest version in sPHENIX GitHub at line 28 of file RawTower_Temperature.h
References RawTowerDefs::decode_index2().
float RawTower_Temperature::get_temperature_from_entry (const unsigned int entry) const inline
Definition at line 42 of file RawTower_Temperature.h.
View newest version in sPHENIX GitHub at line 42 of file RawTower_Temperature.h
References entry, and temperatures.
Referenced by get_temperature_from_time(), print(), Prototype2DSTReader::process_event(), Prototype3DSTReader::process_event(), and Prototype4DSTReader::process_event().
float RawTower_Temperature::get_temperature_from_entry (const unsigned int entry) const inline
Definition at line 42 of file RawTower_Temperature.h.
View newest version in sPHENIX GitHub at line 42 of file RawTower_Temperature.h
References entry, and temperatures.
float RawTower_Temperature::get_temperature_from_entry (const unsigned int entry) const inline
Definition at line 43 of file RawTower_Temperature.h.
View newest version in sPHENIX GitHub at line 43 of file RawTower_Temperature.h
References entry, and temperatures.
float RawTower_Temperature::get_temperature_from_entry (const unsigned int entry) const inline
Definition at line 43 of file RawTower_Temperature.h.
View newest version in sPHENIX GitHub at line 43 of file RawTower_Temperature.h
References entry, and temperatures.
float RawTower_Temperature::get_temperature_from_time (const time_t t) const
Definition at line 33 of file RawTower_Temperature.cc.
View newest version in sPHENIX GitHub at line 33 of file RawTower_Temperature.cc
References get_nr_entries(), get_temperature_from_entry(), get_time_from_entry(), i, isValid(), Acts::UnitConstants::m, and t.
Referenced by Proto2ShowerCalib::process_event().
float RawTower_Temperature::get_temperature_from_time (const time_t t) const
float RawTower_Temperature::get_temperature_from_time (const time_t t) const
float RawTower_Temperature::get_temperature_from_time (const time_t t) const
time_t RawTower_Temperature::get_time_from_entry (const unsigned int entry) const inline
Definition at line 49 of file RawTower_Temperature.h.
View newest version in sPHENIX GitHub at line 49 of file RawTower_Temperature.h
References entry, and times.
Referenced by get_temperature_from_time(), and print().
time_t RawTower_Temperature::get_time_from_entry (const unsigned int entry) const inline
Definition at line 49 of file RawTower_Temperature.h.
View newest version in sPHENIX GitHub at line 49 of file RawTower_Temperature.h
References entry, and times.
time_t RawTower_Temperature::get_time_from_entry (const unsigned int entry) const inline
Definition at line 50 of file RawTower_Temperature.h.
View newest version in sPHENIX GitHub at line 50 of file RawTower_Temperature.h
References entry, and times.
time_t RawTower_Temperature::get_time_from_entry (const unsigned int entry) const inline
Definition at line 50 of file RawTower_Temperature.h.
View newest version in sPHENIX GitHub at line 50 of file RawTower_Temperature.h
References entry, and times.
void RawTower_Temperature::identify (std::ostream & os = std::cout) const override virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from PHObject.
Definition at line 73 of file RawTower_Temperature.cc.
View newest version in sPHENIX GitHub at line 73 of file RawTower_Temperature.cc
References get_column(), get_row(), and temperatures.
Referenced by print().
void RawTower_Temperature::identify (std::ostream & os = std::cout) const override virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from RawTower.
void RawTower_Temperature::identify (std::ostream & os = std::cout) const override virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from RawTower.
void RawTower_Temperature::identify (std::ostream & os = std::cout) const override virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from RawTower.
int RawTower_Temperature::isValid () const inline override virtual
isValid returns non zero if object contains vailid data
Reimplemented from RawTower.
Definition at line 22 of file RawTower_Temperature.h.
View newest version in sPHENIX GitHub at line 22 of file RawTower_Temperature.h
References get_nr_entries().
int RawTower_Temperature::isValid () const inline override virtual
isValid returns non zero if object contains vailid data
Reimplemented from PHObject.
Definition at line 22 of file RawTower_Temperature.h.
View newest version in sPHENIX GitHub at line 22 of file RawTower_Temperature.h
References get_nr_entries().
Referenced by get_temperature_from_time().
int RawTower_Temperature::isValid () const inline override virtual
isValid returns non zero if object contains vailid data
Reimplemented from RawTower.
Definition at line 23 of file RawTower_Temperature.h.
View newest version in sPHENIX GitHub at line 23 of file RawTower_Temperature.h
References get_nr_entries().
int RawTower_Temperature::isValid () const inline override virtual
isValid returns non zero if object contains vailid data
Reimplemented from RawTower.
Definition at line 23 of file RawTower_Temperature.h.
View newest version in sPHENIX GitHub at line 23 of file RawTower_Temperature.h
References get_nr_entries().
void RawTower_Temperature::print (std::ostream & os = std::cout) const
void RawTower_Temperature::print (std::ostream & os = std::cout) const
Definition at line 79 of file RawTower_Temperature.cc.
View newest version in sPHENIX GitHub at line 79 of file RawTower_Temperature.cc
References get_eventnumber_from_entry(), get_nr_entries(), get_temperature_from_entry(), get_time_from_entry(), i, and identify().
void RawTower_Temperature::print (std::ostream & os = std::cout) const
void RawTower_Temperature::print (std::ostream & os = std::cout) const
void RawTower_Temperature::Reset () override virtual
Clear Event.
Reimplemented from RawTower.
void RawTower_Temperature::Reset () override virtual
Clear Event.
Reimplemented from PHObject.
Definition at line 26 of file RawTower_Temperature.cc.
View newest version in sPHENIX GitHub at line 26 of file RawTower_Temperature.cc
References eventnumbers, temperatures, and times.
void RawTower_Temperature::Reset () override virtual
Clear Event.
Reimplemented from RawTower.
void RawTower_Temperature::Reset () override virtual
Clear Event.
Reimplemented from RawTower.
void RawTower_Temperature::set_id (RawTowerDefs::keytype id) inline override virtual
Reimplemented from RawTower.
Definition at line 29 of file RawTower_Temperature.h.
View newest version in sPHENIX GitHub at line 29 of file RawTower_Temperature.h
References train_ambiguity_solver::id.
void RawTower_Temperature::set_id (RawTowerDefs::keytype id) inline override virtual
Reimplemented from RawTower.
Definition at line 29 of file RawTower_Temperature.h.
View newest version in sPHENIX GitHub at line 29 of file RawTower_Temperature.h
References train_ambiguity_solver::id.
void RawTower_Temperature::set_id (RawTowerDefs::keytype id) inline override virtual
Reimplemented from RawTower.
Definition at line 30 of file RawTower_Temperature.h.
View newest version in sPHENIX GitHub at line 30 of file RawTower_Temperature.h
References train_ambiguity_solver::id.
void RawTower_Temperature::set_id (RawTowerDefs::keytype id) inline override virtual
Reimplemented from RawTower.
Definition at line 30 of file RawTower_Temperature.h.
View newest version in sPHENIX GitHub at line 30 of file RawTower_Temperature.h
References train_ambiguity_solver::id.
Member Data Documentation
std::vector< int > RawTower_Temperature::eventnumbers protected
Temperature readings since we do not have more than 100 entries per run typically, we trade efficiency for some simplicity and just use some vectors.
Definition at line 75 of file RawTower_Temperature.h.
View newest version in sPHENIX GitHub at line 75 of file RawTower_Temperature.h
Referenced by add_entry(), get_eventnumber_from_entry(), and Reset().
std::vector< float > RawTower_Temperature::temperatures protected
Definition at line 77 of file RawTower_Temperature.h.
View newest version in sPHENIX GitHub at line 77 of file RawTower_Temperature.h
Referenced by add_entry(), get_nr_entries(), get_temperature_from_entry(), identify(), and Reset().
std::vector< time_t > RawTower_Temperature::times protected
Definition at line 76 of file RawTower_Temperature.h.
View newest version in sPHENIX GitHub at line 76 of file RawTower_Temperature.h
Referenced by add_entry(), get_time_from_entry(), and Reset().
RawTowerDefs::keytype RawTower_Temperature::towerid protected
Definition at line 69 of file RawTower_Temperature.h.
View newest version in sPHENIX GitHub at line 69 of file RawTower_Temperature.h
Referenced by get_id().
The documentation for this class was generated from the following files:
analysis/blob/master/EMCTemplateFitting/src/RawTower_Temperature.h
prototype/blob/master/offline/packages/Prototype2/RawTower_Temperature.h
prototype/blob/master/offline/packages/Prototype3/RawTower_Temperature.h
prototype/blob/master/offline/packages/Prototype4/RawTower_Temperature.h
analysis/blob/master/EMCTemplateFitting/src/RawTower_Temperature.cc
prototype/blob/master/offline/packages/Prototype2/RawTower_Temperature.cc
prototype/blob/master/offline/packages/Prototype3/RawTower_Temperature.cc
prototype/blob/master/offline/packages/Prototype4/RawTower_Temperature.cc