Analysis Software: SingleInttPoolInput Class Reference
SingleInttPoolInput Class Reference
#include <coresoftware/blob/master/offline/framework/fun4allraw/SingleInttPoolInput.h>
Public Member Functions
SingleInttPoolInput (const std::string &name)
~SingleInttPoolInput () override
void FillPool (const unsigned int) override
void CleanupUsedPackets (const uint64_t bclk) override
bool CheckPoolDepth (const uint64_t bclk) override
void ClearCurrentEvent () override
bool GetSomeMoreEvents (const uint64_t ibclk)
void Print (const std::string &what="ALL") const override
void CreateDSTNode (PHCompositeNode *topNode) override
void SetBcoRange (const unsigned int value)
void ConfigureStreamingInputManager () override
void SetNegativeBco (const unsigned int value)
Public Member Functions inherited from SingleStreamingInput
SingleStreamingInput (const std::string &name, Fun4AllEvtInputPoolManager *inman)
SingleStreamingInput (const std::string &name)
~SingleStreamingInput () override
virtual Eventiterator * GetEventIterator ()
virtual void FillPool (const uint64_t)
virtual void RunNumber (const int runno)
virtual int RunNumber () const
virtual int fileopen (const std::string &filename) override
virtual int fileclose () override
virtual int AllDone () const
virtual void AllDone (const int i)
virtual void EventNumberOffset (const int i)
virtual Eventiterator * GetEventiterator () const
virtual
Fun4AllEvtInputPoolManager * InputManager ()
virtual void InputManager (Fun4AllEvtInputPoolManager *in)
virtual
Fun4AllStreamingInputManager * StreamingInputManager ()
virtual void StreamingInputManager (Fun4AllStreamingInputManager *in)
virtual void SubsystemEnum (const int id)
virtual int SubsystemEnum () const
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Public Member Functions inherited from InputFileHandler
InputFileHandler ()=default
virtual ~InputFileHandler ()=default
int OpenNextFile ()
int AddListFile (const std::string &filename)
int AddFile (const std::string &filename)
void AddToFileOpened (const std::string &filename)
void Print (const std::string &what="ALL") const
int IsOpen () const
void IsOpen (const int i)
void SetVerbosity (const int i)
int GetVerbosity () const
void UpdateFileList ()
void FileName (const std::string &fn)
const std::string FileName () const
Private Attributes
Packet ** plist {nullptr}
unsigned int m_NumSpecialEvents {0}
unsigned int m_BcoRange {0}
unsigned int m_NegativeBco {0}
std::array< uint64_t, 14 > m_PreviousClock {}
std::array< uint64_t, 14 > m_Rollover {}
std::map< uint64_t, std::set
< int > > m_BeamClockFEE
std::map< uint64_t,
std::vector< InttRawHit * > > m_InttRawHitMap
std::map< int, uint64_t > m_FEEBclkMap
std::set< uint64_t > m_BclkStack
std::map< int, intt_pool * > poolmap
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = std::numeric_limits<int>::max() - 10
}
Protected Member Functions inherited from Fun4AllBase
Fun4AllBase (const std::string &name="NONAME")
Detailed Description
Definition at line 18 of file SingleInttPoolInput.h.
View newest version in sPHENIX GitHub at line 18 of file SingleInttPoolInput.h
Constructor & Destructor Documentation
SingleInttPoolInput::SingleInttPoolInput (const std::string & name) explicit
Definition at line 25 of file SingleInttPoolInput.cc.
View newest version in sPHENIX GitHub at line 25 of file SingleInttPoolInput.cc
References Fun4AllStreamingInputManager::INTT, plist, and SingleStreamingInput::SubsystemEnum().
SingleInttPoolInput::~SingleInttPoolInput () override
Definition at line 32 of file SingleInttPoolInput.cc.
View newest version in sPHENIX GitHub at line 32 of file SingleInttPoolInput.cc
References plist, poolmap, and Fun4AllBase::Verbosity().
Member Function Documentation
bool SingleInttPoolInput::CheckPoolDepth (const uint64_t bclk) override virtual
Reimplemented from SingleStreamingInput.
Definition at line 254 of file SingleInttPoolInput.cc.
View newest version in sPHENIX GitHub at line 254 of file SingleInttPoolInput.cc
References m_FEEBclkMap, and Fun4AllBase::Verbosity().
void SingleInttPoolInput::CleanupUsedPackets (const uint64_t bclk) override virtual
Reimplemented from SingleStreamingInput.
Definition at line 228 of file SingleInttPoolInput.cc.
View newest version in sPHENIX GitHub at line 228 of file SingleInttPoolInput.cc
References m_BclkStack, m_BeamClockFEE, and m_InttRawHitMap.
Referenced by ClearCurrentEvent().
void SingleInttPoolInput::ClearCurrentEvent () override virtual
Reimplemented from SingleStreamingInput.
Definition at line 276 of file SingleInttPoolInput.cc.
View newest version in sPHENIX GitHub at line 276 of file SingleInttPoolInput.cc
References CleanupUsedPackets(), and m_BclkStack.
Referenced by CleanUp().
void SingleInttPoolInput::ConfigureStreamingInputManager () override virtual
Reimplemented from SingleStreamingInput.
Definition at line 346 of file SingleInttPoolInput.cc.
View newest version in sPHENIX GitHub at line 346 of file SingleInttPoolInput.cc
References m_BcoRange, m_NegativeBco, Fun4AllStreamingInputManager::SetInttBcoRange(), Fun4AllStreamingInputManager::SetInttNegativeBco(), and SingleStreamingInput::StreamingInputManager().
void SingleInttPoolInput::CreateDSTNode (PHCompositeNode * topNode) override virtual
Reimplemented from SingleStreamingInput.
Definition at line 320 of file SingleInttPoolInput.cc.
View newest version in sPHENIX GitHub at line 320 of file SingleInttPoolInput.cc
References PHCompositeNode::addNode(), and PHNodeIterator::findFirst().
void SingleInttPoolInput::FillPool (const unsigned int) override virtual
Reimplemented from SingleStreamingInput.
Definition at line 45 of file SingleInttPoolInput.cc.
View newest version in sPHENIX GitHub at line 45 of file SingleInttPoolInput.cc
References Fun4AllStreamingInputManager::AddInttRawHit(), SingleStreamingInput::AllDone(), DATAEVENT, intt_pool::depth_ok(), SingleStreamingInput::fileclose(), InttRawHit::get_channel_id(), SingleStreamingInput::GetEventiterator(), Event::getEvtSequence(), Event::getEvtType(), intt_pool::getIdentifier(), Packet::getIdentifier(), Eventiterator::getNextEvent(), Event::getPacketList(), Event::getRunNumber(), GetSomeMoreEvents(), InputFileHandler::GetVerbosity(), i, Event::identify(), Packet::identify(), intt_pool::iValue(), j, intt_pool::lValue(), m_BclkStack, m_BeamClockFEE, m_FEEBclkMap, m_InttRawHitMap, m_NumSpecialEvents, m_PreviousClock, m_Rollover, intt_pool::next(), InputFileHandler::OpenNextFile(), plist, poolmap, SingleStreamingInput::RunNumber(), InttRawHit::set_adc(), InttRawHit::set_amplitude(), InttRawHit::set_bco(), InttRawHit::set_channel_id(), InttRawHit::set_chip_id(), InttRawHit::set_fee(), InttRawHit::set_FPHX_BCO(), InttRawHit::set_full_FPHX(), InttRawHit::set_full_ROC(), InttRawHit::set_packetid(), InttRawHit::set_word(), SingleStreamingInput::StreamingInputManager(), to_string(), and Fun4AllBase::Verbosity().
Referenced by Run(), and RunBclk().
bool SingleInttPoolInput::GetSomeMoreEvents (const uint64_t ibclk)
Definition at line 287 of file SingleInttPoolInput.cc.
View newest version in sPHENIX GitHub at line 287 of file SingleInttPoolInput.cc
References SingleStreamingInput::AllDone(), m_FEEBclkMap, m_InttRawHitMap, and poolmap.
Referenced by FillPool().
void SingleInttPoolInput::Print (const std::string & what = "ALL") const override virtual
Print out some info about this module.
Parameters
what can be used to specify what to print exactly.
Reimplemented from SingleStreamingInput.
Definition at line 185 of file SingleInttPoolInput.cc.
View newest version in sPHENIX GitHub at line 185 of file SingleInttPoolInput.cc
References m_BclkStack, m_BeamClockFEE, m_FEEBclkMap, and m_InttRawHitMap.
Referenced by Print().
void SingleInttPoolInput::SetBcoRange (const unsigned int value) inline
Definition at line 31 of file SingleInttPoolInput.h.
View newest version in sPHENIX GitHub at line 31 of file SingleInttPoolInput.h
References m_BcoRange, and value.
Referenced by Fun4All_Intt_Combiner(), Fun4All_Mvtx_Combiner(), Fun4All_SingleMvtx(), and Fun4All_Stream_Combiner().
void SingleInttPoolInput::SetNegativeBco (const unsigned int value) inline
Definition at line 33 of file SingleInttPoolInput.h.
View newest version in sPHENIX GitHub at line 33 of file SingleInttPoolInput.h
References m_NegativeBco, and value.
Referenced by Fun4All_Intt_Combiner(), and Fun4All_Stream_Combiner().
Member Data Documentation
std::set<uint64_t> SingleInttPoolInput::m_BclkStack private
Definition at line 46 of file SingleInttPoolInput.h.
View newest version in sPHENIX GitHub at line 46 of file SingleInttPoolInput.h
Referenced by CleanupUsedPackets(), ClearCurrentEvent(), FillPool(), and Print().
unsigned int SingleInttPoolInput::m_BcoRange {0} private
Definition at line 38 of file SingleInttPoolInput.h.
View newest version in sPHENIX GitHub at line 38 of file SingleInttPoolInput.h
Referenced by ConfigureStreamingInputManager(), and SetBcoRange().
std::map<uint64_t, std::set<int> > SingleInttPoolInput::m_BeamClockFEE private
Definition at line 43 of file SingleInttPoolInput.h.
View newest version in sPHENIX GitHub at line 43 of file SingleInttPoolInput.h
Referenced by CleanupUsedPackets(), FillPool(), and Print().
std::map<int, uint64_t> SingleInttPoolInput::m_FEEBclkMap private
Definition at line 45 of file SingleInttPoolInput.h.
View newest version in sPHENIX GitHub at line 45 of file SingleInttPoolInput.h
Referenced by CheckPoolDepth(), FillPool(), GetSomeMoreEvents(), and Print().
std::map<uint64_t, std::vector<InttRawHit *> > SingleInttPoolInput::m_InttRawHitMap private
Definition at line 44 of file SingleInttPoolInput.h.
View newest version in sPHENIX GitHub at line 44 of file SingleInttPoolInput.h
Referenced by CleanupUsedPackets(), FillPool(), GetSomeMoreEvents(), and Print().
unsigned int SingleInttPoolInput::m_NegativeBco {0} private
Definition at line 39 of file SingleInttPoolInput.h.
View newest version in sPHENIX GitHub at line 39 of file SingleInttPoolInput.h
Referenced by ConfigureStreamingInputManager(), and SetNegativeBco().
unsigned int SingleInttPoolInput::m_NumSpecialEvents {0} private
Definition at line 37 of file SingleInttPoolInput.h.
View newest version in sPHENIX GitHub at line 37 of file SingleInttPoolInput.h
Referenced by FillPool().
std::array<uint64_t, 14> SingleInttPoolInput::m_PreviousClock {} private
Definition at line 41 of file SingleInttPoolInput.h.
View newest version in sPHENIX GitHub at line 41 of file SingleInttPoolInput.h
Referenced by FillPool().
std::array<uint64_t, 14> SingleInttPoolInput::m_Rollover {} private
Definition at line 42 of file SingleInttPoolInput.h.
View newest version in sPHENIX GitHub at line 42 of file SingleInttPoolInput.h
Referenced by FillPool().
Packet** SingleInttPoolInput::plist {nullptr} private
Definition at line 36 of file SingleInttPoolInput.h.
View newest version in sPHENIX GitHub at line 36 of file SingleInttPoolInput.h
Referenced by FillPool(), SingleInttPoolInput(), and ~SingleInttPoolInput().
std::map<int, intt_pool *> SingleInttPoolInput::poolmap private
Definition at line 47 of file SingleInttPoolInput.h.
View newest version in sPHENIX GitHub at line 47 of file SingleInttPoolInput.h
Referenced by FillPool(), GetSomeMoreEvents(), and ~SingleInttPoolInput().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/framework/fun4allraw/SingleInttPoolInput.h
coresoftware/blob/master/offline/framework/fun4allraw/SingleInttPoolInput.cc