Analysis Software: JETSCAPE/blob/main/external_packages/gtl/src/gml_scanner.cpp File Reference
gml_scanner.cpp File Reference
#include <GTL/gml_scanner.h>
#include <cstdlib>
#include <cctype>
#include <cassert>
#include <cstring>
Functions
int GML_search_ISO (char *str, int len)
void GML_init ()
struct GML_token GML_scanner (FILE *source)
Variables
__GTL_BEGIN_NAMESPACE const char * GML_table []
unsigned int GML_line
unsigned int GML_column
Function Documentation
void GML_init ()
Definition at line 167 of file gml_scanner.cpp.
View newest version in sPHENIX GitHub at line 167 of file gml_scanner.cpp
References GML_column, and GML_line.
Referenced by graph::load().
struct GML_token GML_scanner (FILE * source) read
Definition at line 175 of file gml_scanner.cpp.
View newest version in sPHENIX GitHub at line 175 of file gml_scanner.cpp
References assert, GML_error::column, test_fpe::count, GML_tok_val::err, GML_error::err_num, GML_tok_val::floating, GML_column, GML_DOUBLE, GML_END, GML_ERROR, GML_INT, GML_KEY, GML_L_BRACKET, GML_line, GML_PREMATURE_EOF, GML_R_BRACKET, GML_scanner(), GML_search_ISO(), GML_STRING, GML_TOO_MANY_DIGITS, GML_UNEXPECTED, INITIAL_SIZE, GML_tok_val::integer, GML_token::kind, GML_error::line, next, parse_cmake_options::source, GML_tok_val::str, Acts::Test::tmp(), token, and GML_token::value.
Referenced by GML_parser(), and GML_scanner().
int GML_search_ISO (char * str, int len)
Definition at line 137 of file gml_scanner.cpp.
View newest version in sPHENIX GitHub at line 137 of file gml_scanner.cpp
References GML_table, and i.
Referenced by GML_scanner().
Variable Documentation
unsigned int GML_column
Definition at line 134 of file gml_scanner.cpp.
View newest version in sPHENIX GitHub at line 134 of file gml_scanner.cpp
Referenced by GML_init(), GML_parser(), and GML_scanner().
unsigned int GML_line
Definition at line 133 of file gml_scanner.cpp.
View newest version in sPHENIX GitHub at line 133 of file gml_scanner.cpp
Referenced by GML_init(), GML_parser(), and GML_scanner().
__GTL_BEGIN_NAMESPACE const char* GML_table[]
Definition at line 33 of file gml_scanner.cpp.
View newest version in sPHENIX GitHub at line 33 of file gml_scanner.cpp
Referenced by GML_search_ISO().