Analysis Software: ReadBDT Class Reference
ReadBDT Class Reference
Public Member Functions
ReadBDT (std::vector< std::string > &theInputVars)
virtual ~ReadBDT ()
double GetMvaValue (const std::vector< double > &inputValues) const override
ReadBDT (std::vector< std::string > &theInputVars)
virtual ~ReadBDT ()
double GetMvaValue (const std::vector< double > &inputValues) const override
ReadBDT (std::vector< std::string > &theInputVars)
virtual ~ReadBDT ()
double GetMvaValue (const std::vector< double > &inputValues) const override
Public Member Functions inherited from IClassifierReader
IClassifierReader ()
virtual ~IClassifierReader ()
bool IsStatusClean () const
IClassifierReader ()
virtual ~IClassifierReader ()
bool IsStatusClean () const
IClassifierReader ()
virtual ~IClassifierReader ()
bool IsStatusClean () const
IClassifierReader ()
virtual ~IClassifierReader ()
bool IsStatusClean () const
IClassifierReader ()
virtual ~IClassifierReader ()
bool IsStatusClean () const
IClassifierReader ()
virtual ~IClassifierReader ()
bool IsStatusClean () const
IClassifierReader ()
virtual ~IClassifierReader ()
bool IsStatusClean () const
IClassifierReader ()
virtual ~IClassifierReader ()
bool IsStatusClean () const
IClassifierReader ()
virtual ~IClassifierReader ()
bool IsStatusClean () const
IClassifierReader ()
virtual ~IClassifierReader ()
bool IsStatusClean () const
IClassifierReader ()
virtual ~IClassifierReader ()
bool IsStatusClean () const
IClassifierReader ()
virtual ~IClassifierReader ()
bool IsStatusClean () const
IClassifierReader ()
virtual ~IClassifierReader ()
bool IsStatusClean () const
IClassifierReader ()
virtual ~IClassifierReader ()
bool IsStatusClean () const
IClassifierReader ()
virtual ~IClassifierReader ()
bool IsStatusClean () const
IClassifierReader ()
virtual ~IClassifierReader ()
bool IsStatusClean () const
IClassifierReader ()
virtual ~IClassifierReader ()
bool IsStatusClean () const
IClassifierReader ()
virtual ~IClassifierReader ()
bool IsStatusClean () const
IClassifierReader ()
virtual ~IClassifierReader ()
bool IsStatusClean () const
IClassifierReader ()
virtual ~IClassifierReader ()
bool IsStatusClean () const
IClassifierReader ()
virtual ~IClassifierReader ()
bool IsStatusClean () const
IClassifierReader ()
virtual ~IClassifierReader ()
bool IsStatusClean () const
IClassifierReader ()
virtual ~IClassifierReader ()
bool IsStatusClean () const
IClassifierReader ()
virtual ~IClassifierReader ()
bool IsStatusClean () const
IClassifierReader ()
virtual ~IClassifierReader ()
bool IsStatusClean () const
IClassifierReader ()
virtual ~IClassifierReader ()
bool IsStatusClean () const
Private Member Functions
void Clear ()
size_t GetNvar () const
char GetType (int ivar) const
double NormVariable (double x, double xmin, double xmax) const
void Initialize ()
double GetMvaValue__ (const std::vector< double > &inputValues) const
void Clear ()
size_t GetNvar () const
char GetType (int ivar) const
double NormVariable (double x, double xmin, double xmax) const
void Initialize ()
double GetMvaValue__ (const std::vector< double > &inputValues) const
void Clear ()
size_t GetNvar () const
char GetType (int ivar) const
double NormVariable (double x, double xmin, double xmax) const
void Initialize ()
double GetMvaValue__ (const std::vector< double > &inputValues) const
Private Attributes
const char * fClassName
const size_t fNvars
double fVmin [3]
double fVmax [3]
char fType [3]
std::vector< BDTNode * > fForest
std::vector< double > fBoostWeights
Additional Inherited Members
Protected Attributes inherited from IClassifierReader
bool fStatusIsClean
Detailed Description
Definition at line 196 of file TMVAClassification_BDT.class.C.
View newest version in sPHENIX GitHub at line 196 of file TMVAClassification_BDT.class.C
Constructor & Destructor Documentation
ReadBDT::ReadBDT (std::vector< std::string > & theInputVars) inline
Definition at line 201 of file TMVAClassification_BDT.class.C.
View newest version in sPHENIX GitHub at line 201 of file TMVAClassification_BDT.class.C
References fClassName, fNvars, IClassifierReader::fStatusIsClean, fType, fVmax, fVmin, and Initialize().
virtual ReadBDT::~ReadBDT () inline virtual
Definition at line 249 of file TMVAClassification_BDT.class.C.
View newest version in sPHENIX GitHub at line 249 of file TMVAClassification_BDT.class.C
References Clear().
ReadBDT::ReadBDT (std::vector< std::string > & theInputVars) inline
Definition at line 201 of file TMVAClassification_BDT.class.C.
View newest version in sPHENIX GitHub at line 201 of file TMVAClassification_BDT.class.C
References fClassName, fNvars, IClassifierReader::fStatusIsClean, fType, fVmax, fVmin, and Initialize().
virtual ReadBDT::~ReadBDT () inline virtual
Definition at line 249 of file TMVAClassification_BDT.class.C.
View newest version in sPHENIX GitHub at line 249 of file TMVAClassification_BDT.class.C
References Clear().
ReadBDT::ReadBDT (std::vector< std::string > & theInputVars) inline
Definition at line 200 of file TMVAClassification_BDT.class.C.
View newest version in sPHENIX GitHub at line 200 of file TMVAClassification_BDT.class.C
References fClassName, fNvars, IClassifierReader::fStatusIsClean, fType, fVmax, fVmin, and Initialize().
virtual ReadBDT::~ReadBDT () inline virtual
Definition at line 251 of file TMVAClassification_BDT.class.C.
View newest version in sPHENIX GitHub at line 251 of file TMVAClassification_BDT.class.C
References Clear().
Member Function Documentation
void ReadBDT::Clear () inline private
Definition at line 26220 of file TMVAClassification_BDT.class.C.
View newest version in sPHENIX GitHub at line 26220 of file TMVAClassification_BDT.class.C
References fForest.
Referenced by ~ReadBDT().
void ReadBDT::Clear () private
void ReadBDT::Clear () private
double ReadBDT::GetMvaValue (const std::vector< double > & inputValues) const inline override virtual
Implements IClassifierReader.
Definition at line 26227 of file TMVAClassification_BDT.class.C.
View newest version in sPHENIX GitHub at line 26227 of file TMVAClassification_BDT.class.C
References fClassName, GetMvaValue__(), and IClassifierReader::IsStatusClean().
double ReadBDT::GetMvaValue (const std::vector< double > & inputValues) const override virtual
Implements IClassifierReader.
double ReadBDT::GetMvaValue (const std::vector< double > & inputValues) const override virtual
Implements IClassifierReader.
double ReadBDT::GetMvaValue__ (const std::vector< double > & inputValues) const private
Definition at line 290 of file TMVAClassification_BDT.class.C.
View newest version in sPHENIX GitHub at line 290 of file TMVAClassification_BDT.class.C
References fBoostWeights, fForest, BDTNode::GetLeft(), BDTNode::GetNodeType(), BDTNode::GetRight(), BDTNode::GoesRight(), and norm.
Referenced by GetMvaValue().
double ReadBDT::GetMvaValue__ (const std::vector< double > & inputValues) const private
double ReadBDT::GetMvaValue__ (const std::vector< double > & inputValues) const private
size_t ReadBDT::GetNvar () const inline private
Definition at line 267 of file TMVAClassification_BDT.class.C.
View newest version in sPHENIX GitHub at line 267 of file TMVAClassification_BDT.class.C
References fNvars.
size_t ReadBDT::GetNvar () const inline private
Definition at line 267 of file TMVAClassification_BDT.class.C.
View newest version in sPHENIX GitHub at line 267 of file TMVAClassification_BDT.class.C
References fNvars.
size_t ReadBDT::GetNvar () const inline private
Definition at line 269 of file TMVAClassification_BDT.class.C.
View newest version in sPHENIX GitHub at line 269 of file TMVAClassification_BDT.class.C
References fNvars.
char ReadBDT::GetType (int ivar) const inline private
Definition at line 268 of file TMVAClassification_BDT.class.C.
View newest version in sPHENIX GitHub at line 268 of file TMVAClassification_BDT.class.C
References fType.
char ReadBDT::GetType (int ivar) const inline private
Definition at line 268 of file TMVAClassification_BDT.class.C.
View newest version in sPHENIX GitHub at line 268 of file TMVAClassification_BDT.class.C
References fType.
char ReadBDT::GetType (int ivar) const inline private
Definition at line 270 of file TMVAClassification_BDT.class.C.
View newest version in sPHENIX GitHub at line 270 of file TMVAClassification_BDT.class.C
References fType.
void ReadBDT::Initialize () private
void ReadBDT::Initialize () private
Definition at line 306 of file TMVAClassification_BDT.class.C.
View newest version in sPHENIX GitHub at line 306 of file TMVAClassification_BDT.class.C
References fBoostWeights, fForest, inf, and NN.
Referenced by ReadBDT().
void ReadBDT::Initialize () private
double ReadBDT::NormVariable (double x, double xmin, double xmax) const inline private
Definition at line 273 of file TMVAClassification_BDT.class.C.
View newest version in sPHENIX GitHub at line 273 of file TMVAClassification_BDT.class.C
References xmin.
double ReadBDT::NormVariable (double x, double xmin, double xmax) const inline private
Definition at line 273 of file TMVAClassification_BDT.class.C.
View newest version in sPHENIX GitHub at line 273 of file TMVAClassification_BDT.class.C
References xmin.
double ReadBDT::NormVariable (double x, double xmin, double xmax) const inline private
Definition at line 275 of file TMVAClassification_BDT.class.C.
View newest version in sPHENIX GitHub at line 275 of file TMVAClassification_BDT.class.C
References xmin.
Member Data Documentation
std::vector< double > ReadBDT::fBoostWeights private
Definition at line 287 of file TMVAClassification_BDT.class.C.
View newest version in sPHENIX GitHub at line 287 of file TMVAClassification_BDT.class.C
Referenced by GetMvaValue__(), and Initialize().
const char * ReadBDT::fClassName private
Definition at line 264 of file TMVAClassification_BDT.class.C.
View newest version in sPHENIX GitHub at line 264 of file TMVAClassification_BDT.class.C
Referenced by GetMvaValue(), and ReadBDT().
std::vector< BDTNode * > ReadBDT::fForest private
Definition at line 286 of file TMVAClassification_BDT.class.C.
View newest version in sPHENIX GitHub at line 286 of file TMVAClassification_BDT.class.C
Referenced by Clear(), GetMvaValue__(), and Initialize().
const size_t ReadBDT::fNvars private
Definition at line 266 of file TMVAClassification_BDT.class.C.
View newest version in sPHENIX GitHub at line 266 of file TMVAClassification_BDT.class.C
Referenced by GetNvar(), and ReadBDT().
char ReadBDT::fType private
Definition at line 279 of file TMVAClassification_BDT.class.C.
View newest version in sPHENIX GitHub at line 279 of file TMVAClassification_BDT.class.C
Referenced by GetType(), and ReadBDT().
double ReadBDT::fVmax private
Definition at line 272 of file TMVAClassification_BDT.class.C.
View newest version in sPHENIX GitHub at line 272 of file TMVAClassification_BDT.class.C
Referenced by ReadBDT().
double ReadBDT::fVmin private
Definition at line 271 of file TMVAClassification_BDT.class.C.
View newest version in sPHENIX GitHub at line 271 of file TMVAClassification_BDT.class.C
Referenced by ReadBDT().
The documentation for this class was generated from the following files:
analysis/blob/master/ElectronID/src/dataset/Weights_negative/TMVAClassification_BDT.class.C
analysis/blob/master/ElectronID/src/dataset/Weights_positive/TMVAClassification_BDT.class.C
analysis/blob/master/HF-Particle/HFTrigger/weights/woutCaloAndMinTrack/TMVAClassification_BDT.class.C