Analysis Software: TSQLStatement Class Reference
TSQLStatement Class Reference abstract
#include <RDBC/blob/master/include/RDBC/TSQLStatement.h>
Public Member Functions
virtual void Execute (const char *, const char *, int *)
virtual void Execute (TMethod *, TObjArray *, int *)
virtual ~TSQLStatement ()
virtual TSQLResultSet * ExecuteQuery (const TString &sql="")=0
virtual Int_t ExecuteUpdate (const TString &sql="")=0
virtual Bool_t Execute (const TString &sql="")=0
virtual TSQLResultSet * GetResultSet ()=0
virtual Bool_t GetMoreResults ()=0
virtual void Close ()=0
virtual void Cancel ()=0
virtual Int_t GetMaxFieldSize ()=0
virtual void SetMaxFieldSize (Int_t max)=0
virtual Int_t GetMaxRows ()=0
virtual void SetMaxRows (Int_t max)=0
virtual Bool_t GetEscapeProcessing ()=0
virtual void SetEscapeProcessing (Bool_t enable=kTRUE)=0
virtual Int_t GetQueryTimeout ()=0
virtual void SetQueryTimeout (Int_t seconds)=0
virtual Int_t GetUpdateCount ()=0
virtual void SetCursorName (const TString &name)=0
virtual void AddBatch (const TString &sql)=0
virtual void ClearBatch ()=0
virtual Int_t * ExecuteBatch ()=0
virtual Int_t GetFetchDirection ()=0
virtual void SetFetchDirection (Int_t direction)=0
virtual Int_t GetFetchSize ()=0
virtual void SetFetchSize (Int_t rows)=0
virtual Int_t GetResultSetConcurrency ()=0
virtual Int_t GetResultSetType ()=0
TSQLConnection * GetConnection () const
Public Member Functions inherited from TSQL
TSQL (void *imp=0)
virtual ~TSQL ()
virtual void Throw (TSQLException *e)
TList * GetWarnings () const
void ClearWarnings ()
virtual Bool_t IsValid () const
Protected Member Functions
TSQLStatement (TSQLConnection *con, void *imp=0)
Protected Attributes
TList * fBatches
TSQLResultSet * fCurrentResult
TSQLConnection * fConnection
Protected Attributes inherited from TSQL
TList * fWarnings
void * fImp
Additional Inherited Members
Static Public Member Functions inherited from TSQL
static Bool_t SetHandler (const TString &handler)
static Bool_t UnsetHandler (const TString &handler="")
Detailed Description
Definition at line 21 of file TSQLStatement.h.
View newest version in sPHENIX GitHub at line 21 of file TSQLStatement.h
Constructor & Destructor Documentation
TSQLStatement::TSQLStatement (TSQLConnection * con, void * imp = 0) protected
TSQLStatement::~TSQLStatement () virtual
Definition at line 96 of file MySQLStatement.cxx.
View newest version in sPHENIX GitHub at line 96 of file MySQLStatement.cxx
References ClearBatch(), fBatches, fConnection, fCurrentResult, TSQL::fImp, and TSQLConnection::GetListOfStatements().
Member Function Documentation
void TSQLStatement::AddBatch (const TString & sql) pure virtual
Implemented in ODBCCallableStatement, ODBCPreparedStatement, and ODBCStatement.
Definition at line 685 of file MySQLStatement.cxx.
View newest version in sPHENIX GitHub at line 685 of file MySQLStatement.cxx
void TSQLStatement::Cancel () pure virtual
Implemented in ODBCCallableStatement, ODBCPreparedStatement, and ODBCStatement.
Definition at line 526 of file MySQLStatement.cxx.
View newest version in sPHENIX GitHub at line 526 of file MySQLStatement.cxx
void TSQLStatement::ClearBatch () pure virtual
Implemented in ODBCCallableStatement, ODBCPreparedStatement, and ODBCStatement.
Definition at line 700 of file MySQLStatement.cxx.
View newest version in sPHENIX GitHub at line 700 of file MySQLStatement.cxx
Referenced by ODBCCallableStatement::Close(), and ~TSQLStatement().
void TSQLStatement::Close () pure virtual
Implemented in ODBCCallableStatement, ODBCPreparedStatement, and ODBCStatement.
Definition at line 539 of file MySQLStatement.cxx.
View newest version in sPHENIX GitHub at line 539 of file MySQLStatement.cxx
References TSQL::fImp.
virtual void TSQLStatement::Execute (const char * , const char * , int *) inline virtual
Definition at line 32 of file TSQLStatement.h.
View newest version in sPHENIX GitHub at line 32 of file TSQLStatement.h
Referenced by TRDBCServer::CreateDataBase(), TRDBCServer::DropDataBase(), RDBCfirst(), TRDBCServer::Reload(), and TRDBCServer::SelectDataBase().
virtual void TSQLStatement::Execute (TMethod * , TObjArray * , int *) inline virtual
Definition at line 33 of file TSQLStatement.h.
View newest version in sPHENIX GitHub at line 33 of file TSQLStatement.h
Bool_t TSQLStatement::Execute (const TString & sql = "") pure virtual
Implemented in ODBCCallableStatement, ODBCPreparedStatement, and ODBCStatement.
Definition at line 192 of file MySQLStatement.cxx.
View newest version in sPHENIX GitHub at line 192 of file MySQLStatement.cxx
References MySQLConnectionPrivate::CheckIfServerIsAlive(), TSQL::ClearWarnings(), TSQLResultSet::Close(), con, fConnection, fCurrentResult, MySQLResultSetPrivate::fCurrentRow, TSQL::fImp, MySQLConnectionPrivate::fMYSQL, MySQLResultSetPrivate::fMYSQL_RES, MySQLResultSetPrivate::fReallyResult, TSQLConnection::GetCatalog(), Acts::IntegrationTest::L, Acts::Test::pos, TSQLConnection::SetCatalog(), TSQL::Throw(), and TSQLResultSetMetaData::TSQLResultSet.
Int_t * TSQLStatement::ExecuteBatch () pure virtual
Implemented in ODBCCallableStatement, ODBCPreparedStatement, and ODBCStatement.
Definition at line 712 of file MySQLStatement.cxx.
View newest version in sPHENIX GitHub at line 712 of file MySQLStatement.cxx
TSQLResultSet * TSQLStatement::ExecuteQuery (const TString & sql = "") pure virtual
Implemented in ODBCCallableStatement, ODBCPreparedStatement, and ODBCStatement.
Definition at line 116 of file MySQLStatement.cxx.
View newest version in sPHENIX GitHub at line 116 of file MySQLStatement.cxx
References MySQLConnectionPrivate::CheckIfServerIsAlive(), TSQL::ClearWarnings(), TSQLResultSet::Close(), con, fConnection, fCurrentResult, MySQLResultSetPrivate::fCurrentRow, TSQL::fImp, MySQLConnectionPrivate::fMYSQL, MySQLResultSetPrivate::fMYSQL_RES, MySQLResultSetPrivate::fReallyResult, TSQLConnection::GetCatalog(), Acts::IntegrationTest::L, Acts::Test::pos, TSQLConnection::SetCatalog(), TSQL::Throw(), and TSQLResultSetMetaData::TSQLResultSet.
Referenced by PgPostBankBackupManager::CleanTable(), Compare(), RDBCBench::DoOne(), PgPostBankBackupManager::dumpTable(), PgPostBankBackupManager::fetchAllBank2TFile(), PgPostBankManager::fetchBank(), PgPostBankBackupManager::fetchBank(), Fill(), PgPostBankBackupManager::getListOfRId(), PgPostBankBackupManager::getTotalRowCount(), TSQLDatabaseMetaData::GetUserName(), DbForm::HandleExecuteQuery(), PgPostCalBankIterator::init(), PgPostBankBackupManager::isRIdExist(), TSQLImporter::LoadCatalog(), TRDBCServer::Query(), RDBCconsumer(), RDBCemp(), RDBCTestInt(), and RDBCTestMetaData().
Int_t TSQLStatement::ExecuteUpdate (const TString & sql = "") pure virtual
Implemented in ODBCCallableStatement, ODBCPreparedStatement, and ODBCStatement.
Definition at line 281 of file MySQLStatement.cxx.
View newest version in sPHENIX GitHub at line 281 of file MySQLStatement.cxx
Referenced by PgPostBankBackupManager::CleanTable(), PgPostBankWrapper::commit(), PgPostBankBackupManager::commit(), PgPostBankBackupManager::commitAllBankfromTFile(), RDBCBench::CreateDatabase(), CreateStuff(), RDBCBench::DoOne(), RDBCBench::DropDatabase(), DropStuff(), TSQLImporter::LoadTable(), PgPostBankBackupLog::Log(), Populate(), and RDBCTestInt().
TSQLConnection* TSQLStatement::GetConnection () const inline
Definition at line 63 of file TSQLStatement.h.
View newest version in sPHENIX GitHub at line 63 of file TSQLStatement.h
References fConnection.
Referenced by DbForm::SetStatement().
Bool_t TSQLStatement::GetEscapeProcessing () pure virtual
Implemented in ODBCCallableStatement, ODBCPreparedStatement, and ODBCStatement.
Definition at line 471 of file MySQLStatement.cxx.
View newest version in sPHENIX GitHub at line 471 of file MySQLStatement.cxx
References TSQL::fImp.
Int_t TSQLStatement::GetFetchDirection () pure virtual
Implemented in ODBCCallableStatement, ODBCPreparedStatement, and ODBCStatement.
Definition at line 601 of file MySQLStatement.cxx.
View newest version in sPHENIX GitHub at line 601 of file MySQLStatement.cxx
Int_t TSQLStatement::GetFetchSize () pure virtual
Implemented in ODBCCallableStatement, ODBCPreparedStatement, and ODBCStatement.
Definition at line 637 of file MySQLStatement.cxx.
View newest version in sPHENIX GitHub at line 637 of file MySQLStatement.cxx
Int_t TSQLStatement::GetMaxFieldSize () pure virtual
Implemented in ODBCCallableStatement, ODBCPreparedStatement, and ODBCStatement.
Definition at line 358 of file MySQLStatement.cxx.
View newest version in sPHENIX GitHub at line 358 of file MySQLStatement.cxx
References TSQL::fImp.
Int_t TSQLStatement::GetMaxRows () pure virtual
Implemented in ODBCCallableStatement, ODBCPreparedStatement, and ODBCStatement.
Definition at line 401 of file MySQLStatement.cxx.
View newest version in sPHENIX GitHub at line 401 of file MySQLStatement.cxx
References TSQL::fImp.
Bool_t TSQLStatement::GetMoreResults () pure virtual
Implemented in ODBCCallableStatement, ODBCPreparedStatement, and ODBCStatement.
Definition at line 337 of file MySQLStatement.cxx.
View newest version in sPHENIX GitHub at line 337 of file MySQLStatement.cxx
Int_t TSQLStatement::GetQueryTimeout () pure virtual
Implemented in ODBCCallableStatement, ODBCPreparedStatement, and ODBCStatement.
Definition at line 492 of file MySQLStatement.cxx.
View newest version in sPHENIX GitHub at line 492 of file MySQLStatement.cxx
References TSQL::fImp.
TSQLResultSet * TSQLStatement::GetResultSet () pure virtual
Implemented in ODBCCallableStatement, ODBCPreparedStatement, and ODBCStatement.
Definition at line 301 of file MySQLStatement.cxx.
View newest version in sPHENIX GitHub at line 301 of file MySQLStatement.cxx
Referenced by RDBCfirst().
Int_t TSQLStatement::GetResultSetConcurrency () pure virtual
Implemented in ODBCCallableStatement, ODBCPreparedStatement, and ODBCStatement.
Definition at line 656 of file MySQLStatement.cxx.
View newest version in sPHENIX GitHub at line 656 of file MySQLStatement.cxx
References kCONCUR_UPDATABLE.
Int_t TSQLStatement::GetResultSetType () pure virtual
Implemented in ODBCCallableStatement, ODBCPreparedStatement, and ODBCStatement.
Definition at line 669 of file MySQLStatement.cxx.
View newest version in sPHENIX GitHub at line 669 of file MySQLStatement.cxx
References TSQL::fImp.
Referenced by TSQLResultSet::Print(), and TSQLResultSet::Tree().
Int_t TSQLStatement::GetUpdateCount () pure virtual
Implemented in ODBCCallableStatement, ODBCPreparedStatement, and ODBCStatement.
Definition at line 319 of file MySQLStatement.cxx.
View newest version in sPHENIX GitHub at line 319 of file MySQLStatement.cxx
void TSQLStatement::SetCursorName (const TString & name) pure virtual
Implemented in ODBCCallableStatement, ODBCPreparedStatement, and ODBCStatement.
Definition at line 554 of file MySQLStatement.cxx.
View newest version in sPHENIX GitHub at line 554 of file MySQLStatement.cxx
void TSQLStatement::SetEscapeProcessing (Bool_t enable = kTRUE) pure virtual
Implemented in ODBCCallableStatement, ODBCPreparedStatement, and ODBCStatement.
Definition at line 450 of file MySQLStatement.cxx.
View newest version in sPHENIX GitHub at line 450 of file MySQLStatement.cxx
References TSQL::fImp.
void TSQLStatement::SetFetchDirection (Int_t direction) pure virtual
Implemented in ODBCCallableStatement, ODBCPreparedStatement, and ODBCStatement.
Definition at line 582 of file MySQLStatement.cxx.
View newest version in sPHENIX GitHub at line 582 of file MySQLStatement.cxx
void TSQLStatement::SetFetchSize (Int_t rows) pure virtual
Implemented in ODBCCallableStatement, ODBCPreparedStatement, and ODBCStatement.
Definition at line 620 of file MySQLStatement.cxx.
View newest version in sPHENIX GitHub at line 620 of file MySQLStatement.cxx
void TSQLStatement::SetMaxFieldSize (Int_t max) pure virtual
Implemented in ODBCCallableStatement, ODBCPreparedStatement, and ODBCStatement.
Definition at line 377 of file MySQLStatement.cxx.
View newest version in sPHENIX GitHub at line 377 of file MySQLStatement.cxx
References TSQL::fImp.
void TSQLStatement::SetMaxRows (Int_t max) pure virtual
Implemented in ODBCCallableStatement, ODBCPreparedStatement, and ODBCStatement.
Definition at line 417 of file MySQLStatement.cxx.
View newest version in sPHENIX GitHub at line 417 of file MySQLStatement.cxx
References TSQL::fImp.
Referenced by PgPostBankBackupManager::fetchAllBank2TFile().
void TSQLStatement::SetQueryTimeout (Int_t seconds) pure virtual
Implemented in ODBCCallableStatement, ODBCPreparedStatement, and ODBCStatement.
Definition at line 509 of file MySQLStatement.cxx.
View newest version in sPHENIX GitHub at line 509 of file MySQLStatement.cxx
References TSQL::fImp.
Member Data Documentation
TList* TSQLStatement::fBatches protected
Definition at line 24 of file TSQLStatement.h.
View newest version in sPHENIX GitHub at line 24 of file TSQLStatement.h
Referenced by ODBCCallableStatement::Close(), and ~TSQLStatement().
TSQLConnection* TSQLStatement::fConnection protected
Definition at line 26 of file TSQLStatement.h.
View newest version in sPHENIX GitHub at line 26 of file TSQLStatement.h
Referenced by Execute(), ExecuteQuery(), TSQLResultSet::First(), GetConnection(), and ~TSQLStatement().
TSQLResultSet* TSQLStatement::fCurrentResult protected
Definition at line 25 of file TSQLStatement.h.
View newest version in sPHENIX GitHub at line 25 of file TSQLStatement.h
Referenced by ODBCCallableStatement::Close(), Execute(), ExecuteQuery(), ODBCCallableStatement::ExecuteQuery(), ODBCCallableStatement::GetResultSet(), ODBCCallableStatement::~ODBCCallableStatement(), ODBCResultSet::~ODBCResultSet(), and ~TSQLStatement().
The documentation for this class was generated from the following files:
RDBC/blob/master/include/RDBC/TSQLStatement.h
RDBC/blob/master/mysql/MySQLStatement.cxx
RDBC/blob/master/rdbc/TSQLStatement.cxx