Analysis Software: Acts::TGeoSurfaceConverter Struct Reference
Acts::TGeoSurfaceConverter Struct Reference
Helper struct to convert TGeoShapes into Surface or Volume Bounds.
#include <acts/blob/sPHENIX/Plugins/TGeo/include/Acts/Plugins/TGeo/TGeoSurfaceConverter.hpp>
Static Public Member Functions
static std::tuple
< std::shared_ptr< const
CylinderBounds >, const
Transform3, double > cylinderComponents (const TGeoShape &tgShape, const Double_t *rotation, const Double_t *translation, const std::string &axes, double scalor=10.) noexcept(false)
static std::tuple
< std::shared_ptr< const
DiscBounds >, const Transform3,
double > discComponents (const TGeoShape &tgShape, const Double_t *rotation, const Double_t *translation, const std::string &axes, double scalor=10.) noexcept(false)
static std::tuple
< std::shared_ptr< const
PlanarBounds >, const
Transform3, double > planeComponents (const TGeoShape &tgShape, const Double_t *rotation, const Double_t *translation, const std::string &axes, double scalor=10.) noexcept(false)
static std::tuple
< std::shared_ptr< Surface >
, ActsScalar > toSurface (const TGeoShape &tgShape, const TGeoMatrix &tgMatrix, const std::string &axes, double scalor=10.) noexcept(false)
static double toRadian (double degree)
Detailed Description
Helper struct to convert TGeoShapes into Surface or Volume Bounds.
Definition at line 32 of file TGeoSurfaceConverter.hpp.
View newest version in sPHENIX GitHub at line 32 of file TGeoSurfaceConverter.hpp
Member Function Documentation
std::tuple< std::shared_ptr< const Acts::CylinderBounds >, const Acts::Transform3, double > Acts::TGeoSurfaceConverter::cylinderComponents (const TGeoShape & tgShape, const Double_t * rotation, const Double_t * translation, const std::string & axes, double scalor = 10.) static noexcept
Convert a TGeoShape into cylinder surface components
Parameters
tgShape The TGeoShape
rotation The rotation matrix as Double_t* from root
translation The translation vector as Double_t* from root
axes The axes definition
scalor The unit scalor between TGeo and Acts
Returns
tuple of DiscBounds, Transform, thickness
Definition at line 51 of file TGeoSurfaceConverter.cpp.
View newest version in sPHENIX GitHub at line 51 of file TGeoSurfaceConverter.cpp
References CKF_timing_vs_mu::ax, bounds, physmon_track_finding_ttbar::deltaR, maxR, Acts::UnitConstants::min, minR, Acts::s_epsilon, t, thickness, Acts::Test::transform, and translation().
Referenced by Acts::TGeoDetectorElement::TGeoDetectorElement().
std::tuple< std::shared_ptr< const Acts::DiscBounds >, const Acts::Transform3, double > Acts::TGeoSurfaceConverter::discComponents (const TGeoShape & tgShape, const Double_t * rotation, const Double_t * translation, const std::string & axes, double scalor = 10.) static noexcept
Convert a TGeoShape into disk surface components
Parameters
tgShape The TGeoShape
rotation The rotation matrix as Double_t* from root
translation The translation vector as Double_t* from root
axes The axes definition
scalor The unit scalor between TGeo and Acts
Returns
tuple of DiscBounds, Transform, thickness
Definition at line 119 of file TGeoSurfaceConverter.cpp.
View newest version in sPHENIX GitHub at line 119 of file TGeoSurfaceConverter.cpp
References KFPMath::a, CKF_timing_vs_mu::ax, KFPMath::b, bounds, i, maxR, Acts::UnitConstants::min, minR, ActsTests::PropagationDatasets::phi, Acts::Test::phiMin, Acts::s_epsilon, t, thickness, Acts::Test::transform, translation(), testSigmaEff::v, and ActsExamples::HepMC3Event::vertices().
Referenced by Acts::TGeoDetectorElement::TGeoDetectorElement().
std::tuple< std::shared_ptr< const Acts::PlanarBounds >, const Acts::Transform3, double > Acts::TGeoSurfaceConverter::planeComponents (const TGeoShape & tgShape, const Double_t * rotation, const Double_t * translation, const std::string & axes, double scalor = 10.) static noexcept
Convert a TGeoShape into plane surface components
Parameters
tgShape The TGeoShape
rotation The rotation matrix as Double_t* from root
translation The translation as a Double_t*
axes The axes definition
scalor The unit scalor between TGeo and Acts
Returns
tuple of PlanarBounds, Transform, thickness
Definition at line 277 of file TGeoSurfaceConverter.cpp.
View newest version in sPHENIX GitHub at line 277 of file TGeoSurfaceConverter.cpp
References CKF_timing_vs_mu::ax, bounds, Acts::s_epsilon, t, thickness, Acts::Test::transform, and translation().
Referenced by Acts::TGeoDetectorElement::TGeoDetectorElement().
static double Acts::TGeoSurfaceConverter::toRadian (double degree) inline static
Translate TGeo degree [0, 360) to radian
will correct to [-pi,pi)
Parameters
degree The input in degree
Returns
angle in radians
Definition at line 94 of file TGeoSurfaceConverter.hpp.
View newest version in sPHENIX GitHub at line 94 of file TGeoSurfaceConverter.hpp
std::tuple< std::shared_ptr< Acts::Surface >, Acts::ActsScalar > Acts::TGeoSurfaceConverter::toSurface (const TGeoShape & tgShape, const TGeoMatrix & tgMatrix, const std::string & axes, double scalor = 10.) static noexcept
Convert a TGeoShape to a Surface
Parameters
tgShape The TGeoShape
tgMatrix The matrix representing the tranbsform
axes The axes definition
scalor The unit scalor between TGeo and Acts
Returns
shared pointer to a surface and the original thickness that has been condensed to the surface
Definition at line 460 of file TGeoSurfaceConverter.cpp.
View newest version in sPHENIX GitHub at line 460 of file TGeoSurfaceConverter.cpp
References translation().
Referenced by Acts::Test::BOOST_AUTO_TEST_CASE(), and Acts::DD4hepDetectorSurfaceFactory::constructPassiveComponents().
The documentation for this struct was generated from the following files:
acts/blob/sPHENIX/Plugins/TGeo/include/Acts/Plugins/TGeo/TGeoSurfaceConverter.hpp
acts/blob/sPHENIX/Plugins/TGeo/src/TGeoSurfaceConverter.cpp