Analysis Software: recoConsts Class Reference
recoConsts Class Reference
#include <coresoftware/blob/master/offline/framework/phool/recoConsts.h>
Public Member Functions
void Print () const override
Public Member Functions inherited from PHFlag
PHFlag ()
virtual ~PHFlag ()
virtual double get_DoubleFlag (const std::string &name) const
virtual double get_DoubleFlag (const std::string &name, const double defaultval)
virtual void set_DoubleFlag (const std::string &name, const double flag)
virtual float get_FloatFlag (const std::string &name) const
virtual float get_FloatFlag (const std::string &name, const float defaultval)
virtual void set_FloatFlag (const std::string &name, const float flag)
virtual int get_IntFlag (const std::string &name) const
virtual int get_IntFlag (const std::string &name, const int defaultval)
virtual void set_IntFlag (const std::string &name, const int flag)
virtual uint64_t get_uint64Flag (const std::string &name) const
virtual uint64_t get_uint64Flag (const std::string &name, const uint64_t defaultval)
virtual void set_uint64Flag (const std::string &name, const uint64_t flag)
virtual const std::string get_StringFlag (const std::string &name) const
virtual const std::string get_StringFlag (const std::string &name, const std::string &defaultval)
virtual void set_StringFlag (const std::string &name, const std::string &flag)
virtual void PrintDoubleFlags () const
virtual void PrintIntFlags () const
virtual void Printuint64Flags () const
virtual void PrintFloatFlags () const
virtual void PrintStringFlags () const
virtual void ReadFromFile (const std::string &name)
virtual void WriteToFile (const std::string &name)
virtual int FlagExist (const std::string &name) const
virtual const std::map
< std::string, uint64_t > * uint64Map () const
virtual const std::map
< std::string, int > * IntMap () const
virtual const std::map
< std::string, float > * FloatMap () const
virtual const std::map
< std::string, double > * DoubleMap () const
virtual const std::map
< std::string, std::string > * StringMap () const
virtual void PrintStackTrace () const
virtual void ClearFlag (const std::string &name)
virtual void ClearAll ()
Static Public Member Functions
static recoConsts * instance ()
Private Member Functions
recoConsts ()
Static Private Attributes
static recoConsts * __instance = nullptr
Additional Inherited Members
Protected Attributes inherited from PHFlag
std::map< std::string, uint64_t > m_UInt64FlagMap
std::map< std::string, int > m_IntFlagMap
std::map< std::string, double > m_DoubleFlagMap
std::map< std::string, float > m_FloatFlagMap
std::map< std::string,
std::string > m_StringFlagMap
Detailed Description
Definition at line 9 of file recoConsts.h.
View newest version in sPHENIX GitHub at line 9 of file recoConsts.h
Constructor & Destructor Documentation
recoConsts::recoConsts () inline private
Definition at line 22 of file recoConsts.h.
View newest version in sPHENIX GitHub at line 22 of file recoConsts.h
Referenced by instance().
Member Function Documentation
static recoConsts* recoConsts::instance () inline static
Definition at line 12 of file recoConsts.h.
View newest version in sPHENIX GitHub at line 12 of file recoConsts.h
References __instance, and recoConsts().
Referenced by OnCalServer::BeginRun(), TPCPedestalCalibration::CDBInsert(), clus_dst_simple_superfastcalib(), PHG4PhenixDetector::Construct(), PHG4FullProjTiltedSpacalDetector::Construct_AzimuthalSeg(), PHG4FullProjSpacalDetector::Construct_AzimuthalSeg(), PHG4MicromegasDetector::construct_fee_board(), PHG4MicromegasDetector::construct_micromegas_tile(), ConstructGeometry(), PHG4InttDetector::ConstructIntt(), PHG4CEmcTestBeamDetector::ConstructMe(), PHG4BbcDetector::ConstructMe(), PHG4ZDCDetector::ConstructMe(), PHG4TpcDetector::ConstructMe(), PHG4OHCalDetector::ConstructMe(), PHG4IHCalDetector::ConstructMe(), PHG4InnerHcalDetector::ConstructMe(), PHG4OuterHcalDetector::ConstructMe(), PHG4SpacalDetector::ConstructMe(), PHG4BbcDetector::ConstructSupport(), PHG4CEmcTestBeamDetector::ConstructTowerVolume(), dst_simple_towerslope_runmacro(), Fun4AllHistoManager::dumpHistos(), EMCalDeadmap(), FlagHandler::End(), Fun4AllServer::End(), DSTEmulator::evaluate_tracks(), Fun4AllOscarInputManager::fileopen(), Fun4AllHepMCInputManager::fileopen(), Fun4All(), Fun4All_Ana(), Fun4All_AnaTutorial_sPHENIX(), Fun4All_AnaTutorial_sPHENIX_Jets(), Fun4All_BHG(), Fun4All_Calo(), Fun4All_CaloProduction(), Fun4All_CaloProduction_PreQM23(), Fun4All_CaloTreeGen(), Fun4All_CentralityValidation(), Fun4All_EICAnalysis_DIS(), Fun4All_EICAnalysis_DISReco(), Fun4All_EICAnalysis_Exclusive(), Fun4All_EICAnalysis_Leptoquarks(), Fun4All_EICAnalysis_Quarkonia(), Fun4All_EICAnalysis_TrackEval(), Fun4All_EMCal(), Fun4All_EMCal_Hist(), Fun4All_EMCal_sp(), Fun4All_EMCalBadTowerID(), Fun4All_EMCalLikelihood(), Fun4All_EMJetVal(), Fun4All_ExportGeom(), Fun4All_G4_block(), Fun4All_G4_Calo(), Fun4All_G4_Calos(), Fun4All_G4_Cylinder(), Fun4All_G4_EICDetector_AnaTutorial(), Fun4All_G4_EICDetector_LQ(), Fun4All_G4_EICDetector_LQ_analysis(), Fun4All_G4_EICDetector_LQ_analysis_nf(), Fun4All_G4_EICDetector_LQ_reference(), Fun4All_G4_EICDetector_RICH(), Fun4All_G4_EICIR(), Fun4All_G4_Example01(), Fun4All_G4_Example02(), Fun4All_G4_Example03(), Fun4All_G4_fsPHENIX_FastSim(), Fun4All_G4_fsPHENIX_pi0(), Fun4All_G4_Geantino(), Fun4All_G4_Momentum(), Fun4All_G4_Momentum_Projection(), Fun4All_G4_Momentum_Projection_Calorimeters(), Fun4All_G4_Momentum_Projection_Detectors(), Fun4All_G4_MyDetector(), Fun4All_G4_Prototype2(), Fun4All_G4_Prototype3(), Fun4All_G4_Prototype4(), Fun4All_G4_sPHENIX(), Fun4All_G4_sPHENIX_AnaGenFit(), Fun4All_G4_sPHENIX_ForTrackCutStudy(), Fun4All_G4_sPHENIX_ForTrackCutStudy_EmbedScanOff(), Fun4All_G4_sPHENIX_ForTrackCutStudy_EmbedScanOn(), Fun4All_G4_sPHENIX_ForTrackCutStudy_WithPileup_EmbedScanOff(), Fun4All_G4_sPHENIX_ForTrackCutStudy_WithPileup_EmbedScanOn(), Fun4All_G4_sPHENIX_jobC(), Fun4All_G4_sPHENIX_photonjet(), Fun4All_G4_sPHENIX_photons(), Fun4All_G4_sPHENIX_truthphotonjet(), Fun4All_G4_TPC(), Fun4All_G4_Write_Dst(), Fun4All_Generator_Display(), Fun4All_GeoExtract(), Fun4All_HCALAnalysis(), Fun4All_HCalCalib(), Fun4All_HCalCalib_sim(), Fun4All_HCalJetPhiShift(), Fun4All_hijbkg(), Fun4All_ImportGeom(), Fun4All_Intt_Combiner(), Fun4All_JetBkgd(), Fun4All_JetBkgd_Embed(), Fun4All_JetNconst(), Fun4All_JetSeedCount(), Fun4All_JetSub(), Fun4All_JetVal(), Fun4All_MBDTreeGen(), Fun4All_MCEventGen(), Fun4All_Mvtx_Combiner(), Fun4All_Pi0Gen_sPHENIX(), Fun4All_pi0tbt_SIMPLE_EMBED(), Fun4All_PRDF(), Fun4All_Pythia6(), Fun4All_quickHijing_Prod(), Fun4All_Read_Dst(), Fun4All_ReadDST_TPCML(), Fun4All_RICHReco(), Fun4All_RTrack(), Fun4All_RunNewTruthMatcher(), Fun4All_single_particle(), Fun4All_SinglePhotonGen_sPHENIX(), Fun4All_SinglePi0Gen_sPHENIX(), Fun4All_Stream_Combiner(), Fun4All_Templates(), Fun4All_TestBeam(), Fun4All_TestBeam_TPC(), Fun4All_testEtIso_Hijing(), Fun4All_testEtIso_Pythia(), Fun4All_Tpc_Combiner(), Fun4All_TrkrClusteringSeeding(), Fun4All_TrkrHitSet_Unpacker(), Fun4All_UE_v2_Psi2(), Fun4All_Year1(), generate_hepmc_bjet(), ReadCalib::getCalibrationFile(), CDBInterface::getUrl(), PHGeomUtility::GetVerbosity(), hcal_toweridmacro(), Fun4AllPrdfOutputManager::InitPrdfManager(), SyncReco::InitRun(), HeadReco::InitRun(), FlagHandler::InitRun(), MbdEvent::InitRun(), MvtxAlign::InitRun(), MvtxPrototype2Align::InitRun(), BbcCheck::InitRun(), PHG4Reco::InitRun(), PHG4CylinderSubsystem::InitRunSubsystem(), PHRandomSeed::InitSeed(), InsertCalib::insertcalib(), Jin_BJet(), LightCollectionModel::load_data_from_CDB(), MakeTree(), MbdCalib::MbdCalib(), MbdEvent::MbdEvent(), Fun4AllDstOutputManager::outfile_open_first_write(), PHGeom_DSTInspection(), FlagHandler::Print(), HepMCNodeReader::process_event(), SvtxEvaluator::process_event(), TrkrNtuplizer::process_event(), RandomSeed(), Fun4AllServer::run(), Run_BbcCheck(), Run_BBCStudy(), run_calo_fromMDC2Hits_towslope_Fun4All_G4_Calo(), run_macro(), run_macro_2(), RunBoth(), rundata(), rundst_spiNo(), Fun4AllServer::setRun(), Fun4AllDummyInputManager::setSyncManager(), PHGeomUtility::SetVerbosity(), spiNo2(), TestCDBInsert(), TestCDBRead(), TestCDBSubsysReco(), toweridmacro(), tsdst_plus_tsfit(), wholeIter_Pi0EtaByEta(), Wrapper(), and Fun4AllServer::~Fun4AllServer().
void recoConsts::Print () const override virtual
Reimplemented from PHFlag.
Definition at line 5 of file recoConsts.cc.
View newest version in sPHENIX GitHub at line 5 of file recoConsts.cc
References PHFlag::PrintFloatFlags(), PHFlag::PrintIntFlags(), PHFlag::PrintStringFlags(), and PHFlag::Printuint64Flags().
Referenced by FlagHandler::Print().
Member Data Documentation
recoConsts * recoConsts::__instance = nullptr static private
Definition at line 23 of file recoConsts.h.
View newest version in sPHENIX GitHub at line 23 of file recoConsts.h
Referenced by instance().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/framework/phool/recoConsts.h
coresoftware/blob/master/offline/framework/phool/recoConsts.cc