Analysis Software: Acts::Test::PropagatorState::Stepper::State Struct Reference
Acts::Test::PropagatorState::Stepper::State Struct Reference
Public Attributes
Vector4 pos4 = Vector4(0., 0., 0., 0.)
Position.
Vector3 dir = Vector3(1., 0., 0.)
Direction.
double p = 0
Momentum.
double q = 0
Charge.
ParticleHypothesis particleHypothesis = ParticleHypothesis::pion()
Particle hypothesis.
double pathAccumulated = 0.
ConstrainedStep stepSize = ConstrainedStep(100_cm)
double previousStepSize = 0.
double tolerance = s_onSurfaceTolerance
The tolerance for the stepping.
GeometryContext geoContext = GeometryContext()
Detailed Description
This is a simple cache struct to mimic the Stepper cache in the propagation
Definition at line 81 of file NavigatorTests.cpp.
View newest version in sPHENIX GitHub at line 81 of file NavigatorTests.cpp
Member Data Documentation
Vector3 Acts::Test::PropagatorState::Stepper::State::dir = Vector3(1., 0., 0.)
Direction.
Definition at line 86 of file NavigatorTests.cpp.
View newest version in sPHENIX GitHub at line 86 of file NavigatorTests.cpp
Referenced by Acts::Test::PropagatorState::Stepper::boundState(), Acts::Test::PropagatorState::Stepper::curvilinearState(), Acts::Test::PropagatorState::Stepper::direction(), and Acts::Test::PropagatorState::Stepper::momentum().
GeometryContext Acts::Test::PropagatorState::Stepper::State::geoContext = GeometryContext()
Definition at line 109 of file NavigatorTests.cpp.
View newest version in sPHENIX GitHub at line 109 of file NavigatorTests.cpp
double Acts::Test::PropagatorState::Stepper::State::p = 0
Momentum.
Definition at line 89 of file NavigatorTests.cpp.
View newest version in sPHENIX GitHub at line 89 of file NavigatorTests.cpp
Referenced by Acts::Test::PropagatorState::Stepper::absoluteMomentum(), Acts::Test::PropagatorState::Stepper::boundState(), Acts::Test::PropagatorState::Stepper::curvilinearState(), Acts::Test::PropagatorState::Stepper::momentum(), and Acts::Test::PropagatorState::Stepper::qOverP().
ParticleHypothesis Acts::Test::PropagatorState::Stepper::State::particleHypothesis = ParticleHypothesis::pion()
Particle hypothesis.
Definition at line 95 of file NavigatorTests.cpp.
View newest version in sPHENIX GitHub at line 95 of file NavigatorTests.cpp
Referenced by Acts::Test::PropagatorState::Stepper::boundState(), and Acts::Test::PropagatorState::Stepper::curvilinearState().
double Acts::Test::PropagatorState::Stepper::State::pathAccumulated = 0.
Definition at line 98 of file NavigatorTests.cpp.
View newest version in sPHENIX GitHub at line 98 of file NavigatorTests.cpp
Referenced by Acts::Test::PropagatorState::Stepper::boundState(), and Acts::Test::PropagatorState::Stepper::curvilinearState().
Vector4 Acts::Test::PropagatorState::Stepper::State::pos4 = Vector4(0., 0., 0., 0.)
Position.
Definition at line 83 of file NavigatorTests.cpp.
View newest version in sPHENIX GitHub at line 83 of file NavigatorTests.cpp
Referenced by Acts::Test::PropagatorState::Stepper::boundState(), Acts::Test::PropagatorState::Stepper::curvilinearState(), Acts::Test::PropagatorState::Stepper::position(), and Acts::Test::PropagatorState::Stepper::time().
double Acts::Test::PropagatorState::Stepper::State::previousStepSize = 0.
Definition at line 104 of file NavigatorTests.cpp.
View newest version in sPHENIX GitHub at line 104 of file NavigatorTests.cpp
Referenced by Acts::Test::PropagatorState::Stepper::setStepSize().
double Acts::Test::PropagatorState::Stepper::State::q = 0
Charge.
Definition at line 92 of file NavigatorTests.cpp.
View newest version in sPHENIX GitHub at line 92 of file NavigatorTests.cpp
Referenced by Acts::Test::PropagatorState::Stepper::boundState(), Acts::Test::PropagatorState::Stepper::charge(), Acts::Test::PropagatorState::Stepper::curvilinearState(), and Acts::Test::PropagatorState::Stepper::qOverP().
ConstrainedStep Acts::Test::PropagatorState::Stepper::State::stepSize = ConstrainedStep(100_cm)
Definition at line 101 of file NavigatorTests.cpp.
View newest version in sPHENIX GitHub at line 101 of file NavigatorTests.cpp
Referenced by Acts::Test::PropagatorState::Stepper::getStepSize(), Acts::Test::PropagatorState::Stepper::outputStepSize(), Acts::Test::PropagatorState::Stepper::releaseStepSize(), and Acts::Test::PropagatorState::Stepper::setStepSize().
double Acts::Test::PropagatorState::Stepper::State::tolerance = s_onSurfaceTolerance
The tolerance for the stepping.
Definition at line 107 of file NavigatorTests.cpp.
View newest version in sPHENIX GitHub at line 107 of file NavigatorTests.cpp
The documentation for this struct was generated from the following file:
acts/blob/sPHENIX/Tests/UnitTests/Core/Propagator/NavigatorTests.cpp