Analysis Software: TpcMonDraw Class Reference
TpcMonDraw Class Reference
#include <OnlMon/blob/main/subsystems/tpc/TpcMonDraw.h>
Public Member Functions
TpcMonDraw (const std::string &name)
~TpcMonDraw () override
int Init () override
int Draw (const std::string &what="ALL") override
int MakeHtml (const std::string &what="ALL") override
int SavePlot (const std::string &what="ALL", const std::string &type="png") override
Public Member Functions inherited from OnlMonDraw
OnlMonDraw (const std::string &name="NONE")
virtual ~OnlMonDraw ()
virtual int MakePS (const std::string &what="ALL")
const std::string Name () const
void Verbosity (const int i)
int Verbosity () const
Protected Member Functions
int MakeCanvas (const std::string &name)
int DrawFirst (const std::string &what="ALL")
int DrawSecond (const std::string &what="ALL")
int DrawTPCModules (const std::string &what="ALL")
int DrawTPCSampleSize (const std::string &what="ALL")
int DrawTPCCheckSum (const std::string &what="ALL")
int DrawTPCADCSample (const std::string &what="ALL")
int DrawTPCADCSampleLarge (const std::string &what="ALL")
int DrawTPCMaxADCModule (const std::string &what="ALL")
int DrawTPCRawADC1D (const std::string &what="ALL")
int DrawTPCMaxADC1D (const std::string &what="ALL")
int DrawTPCPedestSubADC1D (const std::string &what="ALL")
int DrawTPCXYclusters (const std::string &what="ALL")
int DrawTPCXYclusters_unweighted (const std::string &what="ALL")
int DrawTPCZYclusters (const std::string &what="ALL")
int DrawTPCZYclusters_unweighted (const std::string &what="ALL")
int DrawTPCchannelphi_layer_weighted (const std::string &what="ALL")
time_t getTime ()
Protected Member Functions inherited from OnlMonDraw
virtual int DrawDeadServer (TPad *transparent)
Protected Attributes
TCanvas * TC [17] = {nullptr}
TPad * transparent [16] = {nullptr}
TPad * Pad [11] = {nullptr}
TGraphErrors * gr [2] = {nullptr}
TH2 * dummy_his1 = nullptr
TH2 * dummy_his2 = nullptr
TH2 * dummy_his1_XY = nullptr
TH2 * dummy_his2_XY = nullptr
TH2 * dummy_his1_ZY = nullptr
TH2 * dummy_his1_XY_unw = nullptr
TH2 * dummy_his2_XY_unw = nullptr
TH2 * dummy_his1_ZY_unw = nullptr
TH2 * dummy_his1_channelphi_layer_w = nullptr
TPaveLabel * NS18 = nullptr
TPaveLabel * NS17 = nullptr
TPaveLabel * NS16 = nullptr
TPaveLabel * NS15 = nullptr
TPaveLabel * NS14 = nullptr
TPaveLabel * NS13 = nullptr
TPaveLabel * NS12 = nullptr
TPaveLabel * NS23 = nullptr
TPaveLabel * NS22 = nullptr
TPaveLabel * NS21 = nullptr
TPaveLabel * NS20 = nullptr
TPaveLabel * NS19 = nullptr
TPaveLabel * SS00 = nullptr
TPaveLabel * SS01 = nullptr
TPaveLabel * SS02 = nullptr
TPaveLabel * SS03 = nullptr
TPaveLabel * SS04 = nullptr
TPaveLabel * SS05 = nullptr
TPaveLabel * SS06 = nullptr
TPaveLabel * SS07 = nullptr
TPaveLabel * SS08 = nullptr
TPaveLabel * SS09 = nullptr
TPaveLabel * SS10 = nullptr
TPaveLabel * SS11 = nullptr
Protected Attributes inherited from OnlMonDraw
std::string ThisName
int verbosity = 0
Detailed Description
Definition at line 14 of file TpcMonDraw.h.
View newest version in sPHENIX GitHub at line 14 of file TpcMonDraw.h
Constructor & Destructor Documentation
TpcMonDraw::TpcMonDraw (const std::string & name)
Definition at line 35 of file TpcMonDraw.cc.
View newest version in sPHENIX GitHub at line 35 of file TpcMonDraw.cc
TpcMonDraw::~TpcMonDraw () inline override
Definition at line 19 of file TpcMonDraw.h.
View newest version in sPHENIX GitHub at line 19 of file TpcMonDraw.h
Member Function Documentation
int TpcMonDraw::Draw (const std::string & what = "ALL") override virtual
Reimplemented from OnlMonDraw.
Definition at line 264 of file TpcMonDraw.cc.
View newest version in sPHENIX GitHub at line 264 of file TpcMonDraw.cc
References DrawFirst(), DrawSecond(), DrawTPCADCSample(), DrawTPCADCSampleLarge(), DrawTPCchannelphi_layer_weighted(), DrawTPCCheckSum(), DrawTPCMaxADC1D(), DrawTPCMaxADCModule(), DrawTPCModules(), DrawTPCPedestSubADC1D(), DrawTPCRawADC1D(), DrawTPCSampleSize(), DrawTPCXYclusters(), DrawTPCXYclusters_unweighted(), DrawTPCZYclusters(), and DrawTPCZYclusters_unweighted().
Referenced by DrawTPCchannelphi_layer_weighted(), DrawTPCXYclusters(), DrawTPCXYclusters_unweighted(), DrawTPCZYclusters(), DrawTPCZYclusters_unweighted(), MakeHtml(), and SavePlot().
int TpcMonDraw::DrawFirst (const std::string & what = "ALL") protected
Definition at line 357 of file TpcMonDraw.cc.
View newest version in sPHENIX GitHub at line 357 of file TpcMonDraw.cc
References OnlMonDraw::DrawDeadServer(), OnlMonClient::EventTime(), OnlMonClient::getHisto(), OnlMonClient::instance(), MakeCanvas(), Pad, OnlMonClient::RunNumber(), TC, OnlMonDraw::ThisName, and transparent.
Referenced by Draw().
int TpcMonDraw::DrawSecond (const std::string & what = "ALL") protected
Definition at line 405 of file TpcMonDraw.cc.
View newest version in sPHENIX GitHub at line 405 of file TpcMonDraw.cc
References OnlMonDraw::DrawDeadServer(), OnlMonClient::EventTime(), OnlMonClient::getHisto(), OnlMonClient::instance(), MakeCanvas(), Pad, OnlMonClient::RunNumber(), TC, OnlMonDraw::ThisName, and transparent.
Referenced by Draw().
int TpcMonDraw::DrawTPCADCSample (const std::string & what = "ALL") protected
Definition at line 755 of file TpcMonDraw.cc.
View newest version in sPHENIX GitHub at line 755 of file TpcMonDraw.cc
References OnlMonClient::EventTime(), OnlMonClient::getHisto(), i, OnlMonClient::instance(), MakeCanvas(), OnlMonClient::RunNumber(), TC, OnlMonDraw::ThisName, and transparent.
Referenced by Draw().
int TpcMonDraw::DrawTPCADCSampleLarge (const std::string & what = "ALL") protected
Definition at line 1358 of file TpcMonDraw.cc.
View newest version in sPHENIX GitHub at line 1358 of file TpcMonDraw.cc
References OnlMonClient::EventTime(), OnlMonClient::getHisto(), i, OnlMonClient::instance(), MakeCanvas(), OnlMonClient::RunNumber(), TC, OnlMonDraw::ThisName, and transparent.
Referenced by Draw().
int TpcMonDraw::DrawTPCchannelphi_layer_weighted (const std::string & what = "ALL") protected
Definition at line 1610 of file TpcMonDraw.cc.
View newest version in sPHENIX GitHub at line 1610 of file TpcMonDraw.cc
References Draw(), dummy_his1_channelphi_layer_w, OnlMonClient::EventTime(), OnlMonClient::getHisto(), i, OnlMonClient::instance(), MakeCanvas(), OnlMonClient::RunNumber(), TC, OnlMonDraw::ThisName, and transparent.
Referenced by Draw().
int TpcMonDraw::DrawTPCCheckSum (const std::string & what = "ALL") protected
Definition at line 694 of file TpcMonDraw.cc.
View newest version in sPHENIX GitHub at line 694 of file TpcMonDraw.cc
References OnlMonClient::EventTime(), OnlMonClient::getHisto(), i, OnlMonClient::instance(), MakeCanvas(), OnlMonClient::RunNumber(), TC, OnlMonDraw::ThisName, and transparent.
Referenced by Draw().
int TpcMonDraw::DrawTPCMaxADC1D (const std::string & what = "ALL") protected
Definition at line 946 of file TpcMonDraw.cc.
View newest version in sPHENIX GitHub at line 946 of file TpcMonDraw.cc
References OnlMonClient::EventTime(), OnlMonClient::getHisto(), i, OnlMonClient::instance(), j, MakeCanvas(), OnlMonClient::RunNumber(), TC, OnlMonDraw::ThisName, and transparent.
Referenced by Draw().
int TpcMonDraw::DrawTPCMaxADCModule (const std::string & what = "ALL") protected
Definition at line 812 of file TpcMonDraw.cc.
View newest version in sPHENIX GitHub at line 812 of file TpcMonDraw.cc
References OnlMonClient::EventTime(), OnlMonClient::getHisto(), i, OnlMonClient::instance(), MakeCanvas(), OnlMonClient::RunNumber(), TC, OnlMonDraw::ThisName, and transparent.
Referenced by Draw().
int TpcMonDraw::DrawTPCModules (const std::string & what = "ALL") protected
Definition at line 452 of file TpcMonDraw.cc.
View newest version in sPHENIX GitHub at line 452 of file TpcMonDraw.cc
References dummy_his1, dummy_his2, OnlMonClient::EventTime(), OnlMonClient::getHisto(), i, OnlMonClient::instance(), MakeCanvas(), NS12, NS13, NS14, NS15, NS16, NS17, NS18, NS19, NS20, NS21, NS22, NS23, OnlMonClient::RunNumber(), SS00, SS01, SS02, SS03, SS04, SS05, SS06, SS07, SS08, SS09, SS10, SS11, TC, OnlMonDraw::ThisName, and transparent.
Referenced by Draw().
int TpcMonDraw::DrawTPCPedestSubADC1D (const std::string & what = "ALL") protected
Definition at line 1684 of file TpcMonDraw.cc.
View newest version in sPHENIX GitHub at line 1684 of file TpcMonDraw.cc
References OnlMonClient::EventTime(), OnlMonClient::getHisto(), i, OnlMonClient::instance(), j, MakeCanvas(), OnlMonClient::RunNumber(), TC, OnlMonDraw::ThisName, and transparent.
Referenced by Draw().
int TpcMonDraw::DrawTPCRawADC1D (const std::string & what = "ALL") protected
Definition at line 870 of file TpcMonDraw.cc.
View newest version in sPHENIX GitHub at line 870 of file TpcMonDraw.cc
References OnlMonClient::EventTime(), OnlMonClient::getHisto(), i, OnlMonClient::instance(), j, MakeCanvas(), OnlMonClient::RunNumber(), TC, OnlMonDraw::ThisName, and transparent.
Referenced by Draw().
int TpcMonDraw::DrawTPCSampleSize (const std::string & what = "ALL") protected
Definition at line 639 of file TpcMonDraw.cc.
View newest version in sPHENIX GitHub at line 639 of file TpcMonDraw.cc
References OnlMonClient::EventTime(), OnlMonClient::getHisto(), i, OnlMonClient::instance(), MakeCanvas(), OnlMonClient::RunNumber(), TC, OnlMonDraw::ThisName, and transparent.
Referenced by Draw().
int TpcMonDraw::DrawTPCXYclusters (const std::string & what = "ALL") protected
Definition at line 1022 of file TpcMonDraw.cc.
View newest version in sPHENIX GitHub at line 1022 of file TpcMonDraw.cc
References Draw(), dummy_his1_XY, dummy_his2_XY, OnlMonClient::EventTime(), OnlMonClient::getHisto(), i, OnlMonClient::instance(), j, test_fpe::lines, ln2, MakeCanvas(), OnlMonClient::RunNumber(), TC, OnlMonDraw::ThisName, and transparent.
Referenced by Draw().
int TpcMonDraw::DrawTPCXYclusters_unweighted (const std::string & what = "ALL") protected
Definition at line 1190 of file TpcMonDraw.cc.
View newest version in sPHENIX GitHub at line 1190 of file TpcMonDraw.cc
References Draw(), dummy_his1_XY_unw, dummy_his2_XY_unw, OnlMonClient::EventTime(), OnlMonClient::getHisto(), i, OnlMonClient::instance(), j, test_fpe::lines, ln2, MakeCanvas(), OnlMonClient::RunNumber(), TC, OnlMonDraw::ThisName, and transparent.
Referenced by Draw().
int TpcMonDraw::DrawTPCZYclusters (const std::string & what = "ALL") protected
Definition at line 1417 of file TpcMonDraw.cc.
View newest version in sPHENIX GitHub at line 1417 of file TpcMonDraw.cc
References Draw(), dummy_his1_ZY, OnlMonClient::EventTime(), OnlMonClient::getHisto(), i, OnlMonClient::instance(), MakeCanvas(), OnlMonClient::RunNumber(), TC, OnlMonDraw::ThisName, and transparent.
Referenced by Draw().
int TpcMonDraw::DrawTPCZYclusters_unweighted (const std::string & what = "ALL") protected
Definition at line 1514 of file TpcMonDraw.cc.
View newest version in sPHENIX GitHub at line 1514 of file TpcMonDraw.cc
References Draw(), dummy_his1_ZY, dummy_his1_ZY_unw, OnlMonClient::EventTime(), OnlMonClient::getHisto(), i, OnlMonClient::instance(), MakeCanvas(), OnlMonClient::RunNumber(), TC, OnlMonDraw::ThisName, and transparent.
Referenced by Draw().
time_t TpcMonDraw::getTime () protected
Definition at line 1826 of file TpcMonDraw.cc.
View newest version in sPHENIX GitHub at line 1826 of file TpcMonDraw.cc
References OnlMonClient::EventTime(), i, OnlMonClient::instance(), and to_string().
int TpcMonDraw::Init () override virtual
Reimplemented from OnlMonDraw.
Definition at line 41 of file TpcMonDraw.cc.
View newest version in sPHENIX GitHub at line 41 of file TpcMonDraw.cc
int TpcMonDraw::MakeCanvas (const std::string & name) protected
Definition at line 46 of file TpcMonDraw.cc.
View newest version in sPHENIX GitHub at line 46 of file TpcMonDraw.cc
References OnlMonClient::GetDisplaySizeX(), OnlMonClient::GetDisplaySizeY(), OnlMonClient::instance(), Pad, TC, and transparent.
Referenced by DrawFirst(), DrawSecond(), DrawTPCADCSample(), DrawTPCADCSampleLarge(), DrawTPCchannelphi_layer_weighted(), DrawTPCCheckSum(), DrawTPCMaxADC1D(), DrawTPCMaxADCModule(), DrawTPCModules(), DrawTPCPedestSubADC1D(), DrawTPCRawADC1D(), DrawTPCSampleSize(), DrawTPCXYclusters(), DrawTPCXYclusters_unweighted(), DrawTPCZYclusters(), and DrawTPCZYclusters_unweighted().
int TpcMonDraw::MakeHtml (const std::string & what = "ALL") override virtual
Reimplemented from OnlMonDraw.
Definition at line 1785 of file TpcMonDraw.cc.
View newest version in sPHENIX GitHub at line 1785 of file TpcMonDraw.cc
References OnlMonClient::CanvasToPng(), Draw(), OnlMonClient::htmlRegisterPage(), OnlMonClient::instance(), TC, and to_string().
int TpcMonDraw::SavePlot (const std::string & what = "ALL", const std::string & type = "png") override virtual
Reimplemented from OnlMonDraw.
Definition at line 1761 of file TpcMonDraw.cc.
View newest version in sPHENIX GitHub at line 1761 of file TpcMonDraw.cc
References OnlMonClient::CanvasToPng(), Draw(), filename, OnlMonClient::instance(), OnlMonClient::RunNumber(), TC, OnlMonDraw::ThisName, and to_string().
Member Data Documentation
TH2* TpcMonDraw::dummy_his1 = nullptr protected
Definition at line 51 of file TpcMonDraw.h.
View newest version in sPHENIX GitHub at line 51 of file TpcMonDraw.h
Referenced by DrawTPCModules().
TH2* TpcMonDraw::dummy_his1_channelphi_layer_w = nullptr protected
Definition at line 65 of file TpcMonDraw.h.
View newest version in sPHENIX GitHub at line 65 of file TpcMonDraw.h
Referenced by DrawTPCchannelphi_layer_weighted().
TH2* TpcMonDraw::dummy_his1_XY = nullptr protected
Definition at line 55 of file TpcMonDraw.h.
View newest version in sPHENIX GitHub at line 55 of file TpcMonDraw.h
Referenced by DrawTPCXYclusters().
TH2* TpcMonDraw::dummy_his1_XY_unw = nullptr protected
Definition at line 60 of file TpcMonDraw.h.
View newest version in sPHENIX GitHub at line 60 of file TpcMonDraw.h
Referenced by DrawTPCXYclusters_unweighted().
TH2* TpcMonDraw::dummy_his1_ZY = nullptr protected
Definition at line 58 of file TpcMonDraw.h.
View newest version in sPHENIX GitHub at line 58 of file TpcMonDraw.h
Referenced by DrawTPCZYclusters(), and DrawTPCZYclusters_unweighted().
TH2* TpcMonDraw::dummy_his1_ZY_unw = nullptr protected
Definition at line 63 of file TpcMonDraw.h.
View newest version in sPHENIX GitHub at line 63 of file TpcMonDraw.h
Referenced by DrawTPCZYclusters_unweighted().
TH2* TpcMonDraw::dummy_his2 = nullptr protected
Definition at line 52 of file TpcMonDraw.h.
View newest version in sPHENIX GitHub at line 52 of file TpcMonDraw.h
Referenced by DrawTPCModules().
TH2* TpcMonDraw::dummy_his2_XY = nullptr protected
Definition at line 56 of file TpcMonDraw.h.
View newest version in sPHENIX GitHub at line 56 of file TpcMonDraw.h
Referenced by DrawTPCXYclusters().
TH2* TpcMonDraw::dummy_his2_XY_unw = nullptr protected
Definition at line 61 of file TpcMonDraw.h.
View newest version in sPHENIX GitHub at line 61 of file TpcMonDraw.h
Referenced by DrawTPCXYclusters_unweighted().
TGraphErrors* TpcMonDraw::gr[2] = {nullptr} protected
Definition at line 49 of file TpcMonDraw.h.
View newest version in sPHENIX GitHub at line 49 of file TpcMonDraw.h
TPaveLabel* TpcMonDraw::NS12 = nullptr protected
Definition at line 73 of file TpcMonDraw.h.
View newest version in sPHENIX GitHub at line 73 of file TpcMonDraw.h
Referenced by DrawTPCModules().
TPaveLabel* TpcMonDraw::NS13 = nullptr protected
Definition at line 72 of file TpcMonDraw.h.
View newest version in sPHENIX GitHub at line 72 of file TpcMonDraw.h
Referenced by DrawTPCModules().
TPaveLabel* TpcMonDraw::NS14 = nullptr protected
Definition at line 71 of file TpcMonDraw.h.
View newest version in sPHENIX GitHub at line 71 of file TpcMonDraw.h
Referenced by DrawTPCModules().
TPaveLabel* TpcMonDraw::NS15 = nullptr protected
Definition at line 70 of file TpcMonDraw.h.
View newest version in sPHENIX GitHub at line 70 of file TpcMonDraw.h
Referenced by DrawTPCModules().
TPaveLabel* TpcMonDraw::NS16 = nullptr protected
Definition at line 69 of file TpcMonDraw.h.
View newest version in sPHENIX GitHub at line 69 of file TpcMonDraw.h
Referenced by DrawTPCModules().
TPaveLabel* TpcMonDraw::NS17 = nullptr protected
Definition at line 68 of file TpcMonDraw.h.
View newest version in sPHENIX GitHub at line 68 of file TpcMonDraw.h
Referenced by DrawTPCModules().
TPaveLabel* TpcMonDraw::NS18 = nullptr protected
Definition at line 67 of file TpcMonDraw.h.
View newest version in sPHENIX GitHub at line 67 of file TpcMonDraw.h
Referenced by DrawTPCModules().
TPaveLabel* TpcMonDraw::NS19 = nullptr protected
Definition at line 78 of file TpcMonDraw.h.
View newest version in sPHENIX GitHub at line 78 of file TpcMonDraw.h
Referenced by DrawTPCModules().
TPaveLabel* TpcMonDraw::NS20 = nullptr protected
Definition at line 77 of file TpcMonDraw.h.
View newest version in sPHENIX GitHub at line 77 of file TpcMonDraw.h
Referenced by DrawTPCModules().
TPaveLabel* TpcMonDraw::NS21 = nullptr protected
Definition at line 76 of file TpcMonDraw.h.
View newest version in sPHENIX GitHub at line 76 of file TpcMonDraw.h
Referenced by DrawTPCModules().
TPaveLabel* TpcMonDraw::NS22 = nullptr protected
Definition at line 75 of file TpcMonDraw.h.
View newest version in sPHENIX GitHub at line 75 of file TpcMonDraw.h
Referenced by DrawTPCModules().
TPaveLabel* TpcMonDraw::NS23 = nullptr protected
Definition at line 74 of file TpcMonDraw.h.
View newest version in sPHENIX GitHub at line 74 of file TpcMonDraw.h
Referenced by DrawTPCModules().
TPad* TpcMonDraw::Pad[11] = {nullptr} protected
Definition at line 48 of file TpcMonDraw.h.
View newest version in sPHENIX GitHub at line 48 of file TpcMonDraw.h
Referenced by DrawFirst(), DrawSecond(), and MakeCanvas().
TPaveLabel* TpcMonDraw::SS00 = nullptr protected
Definition at line 80 of file TpcMonDraw.h.
View newest version in sPHENIX GitHub at line 80 of file TpcMonDraw.h
Referenced by DrawTPCModules().
TPaveLabel* TpcMonDraw::SS01 = nullptr protected
Definition at line 81 of file TpcMonDraw.h.
View newest version in sPHENIX GitHub at line 81 of file TpcMonDraw.h
Referenced by DrawTPCModules().
TPaveLabel* TpcMonDraw::SS02 = nullptr protected
Definition at line 82 of file TpcMonDraw.h.
View newest version in sPHENIX GitHub at line 82 of file TpcMonDraw.h
Referenced by DrawTPCModules().
TPaveLabel* TpcMonDraw::SS03 = nullptr protected
Definition at line 83 of file TpcMonDraw.h.
View newest version in sPHENIX GitHub at line 83 of file TpcMonDraw.h
Referenced by DrawTPCModules().
TPaveLabel* TpcMonDraw::SS04 = nullptr protected
Definition at line 84 of file TpcMonDraw.h.
View newest version in sPHENIX GitHub at line 84 of file TpcMonDraw.h
Referenced by DrawTPCModules().
TPaveLabel* TpcMonDraw::SS05 = nullptr protected
Definition at line 85 of file TpcMonDraw.h.
View newest version in sPHENIX GitHub at line 85 of file TpcMonDraw.h
Referenced by DrawTPCModules().
TPaveLabel* TpcMonDraw::SS06 = nullptr protected
Definition at line 86 of file TpcMonDraw.h.
View newest version in sPHENIX GitHub at line 86 of file TpcMonDraw.h
Referenced by DrawTPCModules().
TPaveLabel* TpcMonDraw::SS07 = nullptr protected
Definition at line 87 of file TpcMonDraw.h.
View newest version in sPHENIX GitHub at line 87 of file TpcMonDraw.h
Referenced by DrawTPCModules().
TPaveLabel* TpcMonDraw::SS08 = nullptr protected
Definition at line 88 of file TpcMonDraw.h.
View newest version in sPHENIX GitHub at line 88 of file TpcMonDraw.h
Referenced by DrawTPCModules().
TPaveLabel* TpcMonDraw::SS09 = nullptr protected
Definition at line 89 of file TpcMonDraw.h.
View newest version in sPHENIX GitHub at line 89 of file TpcMonDraw.h
Referenced by DrawTPCModules().
TPaveLabel* TpcMonDraw::SS10 = nullptr protected
Definition at line 90 of file TpcMonDraw.h.
View newest version in sPHENIX GitHub at line 90 of file TpcMonDraw.h
Referenced by DrawTPCModules().
TPaveLabel* TpcMonDraw::SS11 = nullptr protected
Definition at line 91 of file TpcMonDraw.h.
View newest version in sPHENIX GitHub at line 91 of file TpcMonDraw.h
Referenced by DrawTPCModules().
TCanvas* TpcMonDraw::TC[17] = {nullptr} protected
Definition at line 46 of file TpcMonDraw.h.
View newest version in sPHENIX GitHub at line 46 of file TpcMonDraw.h
Referenced by DrawFirst(), DrawSecond(), DrawTPCADCSample(), DrawTPCADCSampleLarge(), DrawTPCchannelphi_layer_weighted(), DrawTPCCheckSum(), DrawTPCMaxADC1D(), DrawTPCMaxADCModule(), DrawTPCModules(), DrawTPCPedestSubADC1D(), DrawTPCRawADC1D(), DrawTPCSampleSize(), DrawTPCXYclusters(), DrawTPCXYclusters_unweighted(), DrawTPCZYclusters(), DrawTPCZYclusters_unweighted(), MakeCanvas(), MakeHtml(), and SavePlot().
TPad* TpcMonDraw::transparent[16] = {nullptr} protected
Definition at line 47 of file TpcMonDraw.h.
View newest version in sPHENIX GitHub at line 47 of file TpcMonDraw.h
Referenced by DrawFirst(), DrawSecond(), DrawTPCADCSample(), DrawTPCADCSampleLarge(), DrawTPCchannelphi_layer_weighted(), DrawTPCCheckSum(), DrawTPCMaxADC1D(), DrawTPCMaxADCModule(), DrawTPCModules(), DrawTPCPedestSubADC1D(), DrawTPCRawADC1D(), DrawTPCSampleSize(), DrawTPCXYclusters(), DrawTPCXYclusters_unweighted(), DrawTPCZYclusters(), DrawTPCZYclusters_unweighted(), and MakeCanvas().
The documentation for this class was generated from the following files:
OnlMon/blob/main/subsystems/tpc/TpcMonDraw.h
OnlMon/blob/main/subsystems/tpc/TpcMonDraw.cc