Analysis Software: JETSCAPE/blob/main/external_packages/clvisc_wrapper/test.cc File Reference
test.cc File Reference
#include "include/opencl_backend.h"
#include "include/clideal.h"
#include <iostream>
Functions
clvisc::Config set_hydro_config ()
std::vector< clvisc::cl_real > trivial_initial_condition (const clvisc::Config &cfg)
int main (int argc, char **argv)
Function Documentation
int main (int argc, char ** argv)
Definition at line 39 of file test.cc.
View newest version in sPHENIX GitHub at line 39 of file test.cc
References cfg, clvisc::CLIdeal::evolve(), clvisc::CLIdeal::read_ini(), set_hydro_config(), and trivial_initial_condition().
clvisc::Config set_hydro_config ()
Definition at line 5 of file test.cc.
View newest version in sPHENIX GitHub at line 5 of file test.cc
References clvisc::Config::block_size, cfg, clvisc::Config::dt, clvisc::Config::dx, clvisc::Config::dy, clvisc::Config::dz, clvisc::Config::etaos_left_slop, clvisc::Config::etaos_right_slop, clvisc::Config::etaos_xmin, clvisc::Config::etaos_ymin, clvisc::Config::nx, clvisc::Config::nxskip, clvisc::Config::ny, clvisc::Config::nyskip, clvisc::Config::nz, clvisc::Config::nzskip, clvisc::Config::result_directory, and clvisc::Config::tau0.
Referenced by main().
std::vector<clvisc::cl_real> trivial_initial_condition (const clvisc::Config & cfg)
Definition at line 28 of file test.cc.
View newest version in sPHENIX GitHub at line 28 of file test.cc
References ambiguity_solver_full_chain::idx, clvisc::Config::nx, clvisc::Config::ny, and clvisc::Config::nz.
Referenced by main().