Analysis Software: analysis/blob/master/Calorimeter/macros/sPhenixStyle.C File Reference
sPhenixStyle.C File Reference
#include <iostream>
#include "sPhenixStyle.h"
#include "TROOT.h"
Functions
void SetsPhenixStyle ()
sPHENIX Style, based on a style file from ATLAS by Peter Steinberg
TStyle * sPhenixStyle ()
Function Documentation
void SetsPhenixStyle ()
sPHENIX Style, based on a style file from ATLAS by Peter Steinberg
Definition at line 11 of file sPhenixStyle.C.
View newest version in sPHENIX GitHub at line 11 of file sPhenixStyle.C
Referenced by analyzeClusterEtIso(), calccorr(), Cone_Plots(), Draw_EICRate(), draw_G4_bjet_truth_tagging(), draw_G4_dibjet_truth_tagging(), Draw_HFJetTruth(), Draw_HFJetTruth3yr(), Draw_HFJetTruth_InvMass(), draw_hists(), draw_hists_3D(), drawCorr(), DrawEcal_BlockCalibration(), DrawFieldMap(), DrawFluence(), DrawHadronShowers(), DrawTPCDataStreamEmulator(), DrawTPCFEE(), DrawTPCIntegratedCharge(), DrawTpcPrototypeGenFitTrkFitter(), DrawTpcPrototypeGenFitTrkFitter_Summary(), DrawTpcPrototypeUnpacker(), DrawTrackingEval(), eicsmear_dvmp_plot(), eicsmear_dvmp_tree(), PIDplots::eIDoutput(), figmaker(), han_BUP2020(), HIJING_SubJets(), InttQA(), Jet_reso(), Jet_reso_Iso(), JetSpectra(), jpsi_invariant_mass_plot_exclusiveReco(), LivePlot_Energy_EMC(), look_purity(), main(), makeLcD0_BUP2020(), makeLcD0_BUP2022(), makeV1_BUP2020(), MvtxQA(), numericInverse(), OccupancySim(), plot(), plot_comparisons_clusters(), plot_comparisons_purity(), Plot_FastTrack_Efficiency(), plot_histos(), Plot_Hit_Count(), Plot_Measured_Energy_EMC(), Plot_Measured_Energy_Over_True_Energy_EMC(), plot_sPHENIX_A_N_dp_BUP2020(), Plot_SVTX_Efficiency(), plot_true_false_positive(), plotembed_vscent(), prob_EMC_e_pi_plotMacro(), sPHENIXplots(), TpcQA(), TpotQA(), TrackingQA(), and VertexingQA().
TStyle* sPhenixStyle ()
Definition at line 20 of file sPhenixStyle.C.
View newest version in sPHENIX GitHub at line 20 of file sPhenixStyle.C
Referenced by SetsPhenixStyle().