Analysis Software: tutorials/blob/master/MagneticField/macros/ReadFieldMap.C File Reference
ReadFieldMap.C File Reference
#include <fun4all/Fun4AllInputManager.h>
#include <fun4all/Fun4AllDstInputManager.h>
#include <fun4all/Fun4AllDummyInputManager.h>
#include <fun4all/Fun4AllServer.h>
#include <fieldmapreadback/FieldMapReadBack.h>
Macros
#define MACRO_READFIELDMAP_C
Functions
FieldMapReadBack * ReadFieldMap (const int nEvents=1, const std::string &filename="DST_TRKR_CLUSTER_sHijing_0_20fm_50kHz_bkg_0_20fm-0000000001-04001.root")
Macro Definition Documentation
#define MACRO_READFIELDMAP_C
Definition at line 2 of file ReadFieldMap.C.
View newest version in sPHENIX GitHub at line 2 of file ReadFieldMap.C
Function Documentation
FieldMapReadBack* ReadFieldMap (const int nEvents = 1, const std::string & filename = "DST_TRKR_CLUSTER_sHijing_0_20fm_50kHz_bkg_0_20fm-0000000001-04001.root")
Definition at line 16 of file ReadFieldMap.C.
View newest version in sPHENIX GitHub at line 16 of file ReadFieldMap.C
References filename, Fun4AllInputManager::fileopen(), in, Fun4AllServer::instance(), Fun4AllServer::registerInputManager(), Fun4AllServer::registerSubsystem(), Fun4AllServer::run(), and Fun4AllBase::Verbosity().