Analysis Software: analysis/blob/master/QuarkoniaBG/compiled/ccbb.cc File Reference
ccbb.cc File Reference
#include "TFile.h"
#include "TF1.h"
#include "TH1.h"
#include "TH2.h"
#include "TGraph.h"
#include "TChain.h"
#include "TRandom3.h"
#include "TGraphAsymmErrors.h"
#include "TGraphErrors.h"
#include <fstream>
#include <iostream>
Functions
int ccbb (double eideff, string ofname)
double norm_charm (double *x, double *par)
double norm_charm_nosupp (double *x, double *par)
double norm_bottom (double *x, double *par)
double norm_bottom_nosupp (double *x, double *par)
double norm_hf (double *x, double *par)
double norm_hf_nosupp (double *x, double *par)
int main (int argc, char *argv[])
Variables
TH1D * hcharm_pt
TH1D * hbottom_pt
TH1D * hhf_pt
TH1D * hcharm_pt_nosupp
TH1D * hbottom_pt_nosupp
TH1D * hhf_pt_nosupp
Function Documentation
int ccbb (double eideff, string ofname)
Definition at line 91 of file ccbb.cc.
View newest version in sPHENIX GitHub at line 91 of file ccbb.cc
References double(), eta, Fill(), fout, hbottom_pt, hbottom_pt_nosupp, hcharm_pt, hcharm_pt_nosupp, hhf_pt, hhf_pt_nosupp, i, j, mass, nbins, norm_bottom(), norm_bottom_nosupp(), norm_charm(), norm_charm_nosupp(), norm_hf(), norm_hf_nosupp(), physmon_track_finding_ttbar::pt, and physmon_simulation::rnd.
Referenced by main().
int main (int argc, char * argv[])
Definition at line 77 of file ccbb.cc.
View newest version in sPHENIX GitHub at line 77 of file ccbb.cc
References ccbb().
double norm_bottom (double * x, double * par)
Definition at line 43 of file ccbb.cc.
View newest version in sPHENIX GitHub at line 43 of file ccbb.cc
References hbottom_pt, norm, physmon_track_finding_ttbar::pt, and value.
Referenced by ccbb().
double norm_bottom_nosupp (double * x, double * par)
Definition at line 50 of file ccbb.cc.
View newest version in sPHENIX GitHub at line 50 of file ccbb.cc
References hbottom_pt_nosupp, norm, physmon_track_finding_ttbar::pt, and value.
Referenced by ccbb().
double norm_charm (double * x, double * par)
Definition at line 28 of file ccbb.cc.
View newest version in sPHENIX GitHub at line 28 of file ccbb.cc
References hcharm_pt, norm, physmon_track_finding_ttbar::pt, and value.
Referenced by ccbb().
double norm_charm_nosupp (double * x, double * par)
Definition at line 35 of file ccbb.cc.
View newest version in sPHENIX GitHub at line 35 of file ccbb.cc
References hcharm_pt_nosupp, norm, physmon_track_finding_ttbar::pt, and value.
Referenced by ccbb().
double norm_hf (double * x, double * par)
Definition at line 58 of file ccbb.cc.
View newest version in sPHENIX GitHub at line 58 of file ccbb.cc
References hhf_pt, norm, physmon_track_finding_ttbar::pt, and value.
Referenced by ccbb().
double norm_hf_nosupp (double * x, double * par)
Definition at line 65 of file ccbb.cc.
View newest version in sPHENIX GitHub at line 65 of file ccbb.cc
References hhf_pt_nosupp, norm, physmon_track_finding_ttbar::pt, and value.
Referenced by ccbb().
Variable Documentation
TH1D* hbottom_pt
Definition at line 22 of file ccbb.cc.
View newest version in sPHENIX GitHub at line 22 of file ccbb.cc
Referenced by ccbb(), and norm_bottom().
TH1D* hbottom_pt_nosupp
Definition at line 25 of file ccbb.cc.
View newest version in sPHENIX GitHub at line 25 of file ccbb.cc
Referenced by ccbb(), and norm_bottom_nosupp().
TH1D* hcharm_pt
Definition at line 21 of file ccbb.cc.
View newest version in sPHENIX GitHub at line 21 of file ccbb.cc
Referenced by ccbb(), and norm_charm().
TH1D* hcharm_pt_nosupp
Definition at line 24 of file ccbb.cc.
View newest version in sPHENIX GitHub at line 24 of file ccbb.cc
Referenced by ccbb(), and norm_charm_nosupp().
TH1D* hhf_pt
Definition at line 23 of file ccbb.cc.
View newest version in sPHENIX GitHub at line 23 of file ccbb.cc
Referenced by ccbb(), and norm_hf().
TH1D* hhf_pt_nosupp
Definition at line 26 of file ccbb.cc.
View newest version in sPHENIX GitHub at line 26 of file ccbb.cc
Referenced by ccbb(), and norm_hf_nosupp().