Analysis Software: ActsExamples::TGeoDetectorWithOptions Class Reference
ActsExamples::TGeoDetectorWithOptions Class Reference
#include <acts/blob/sPHENIX/Examples/Run/Common/include/ActsExamples/Detector/TGeoDetectorWithOptions.hpp>
Public Member Functions
void addOptions (boost::program_options::options_description &opt) const override
auto finalize (const boost::program_options::variables_map &vm, std::shared_ptr< const Acts::IMaterialDecorator > mdecorator) -> std::pair< TrackingGeometryPtr, ContextDecorators > override
Public Member Functions inherited from ActsExamples::IBaseDetector
virtual ~IBaseDetector ()=default
Public Attributes
TGeoDetector m_detector
Additional Inherited Members
Public Types inherited from ActsExamples::IBaseDetector
using ContextDecorators = std::vector< std::shared_ptr< ActsExamples::IContextDecorator >>
using TrackingGeometryPtr = std::shared_ptr< const Acts::TrackingGeometry >
Detailed Description
Definition at line 16 of file TGeoDetectorWithOptions.hpp.
View newest version in sPHENIX GitHub at line 16 of file TGeoDetectorWithOptions.hpp
Member Function Documentation
void ActsExamples::TGeoDetectorWithOptions::addOptions (boost::program_options::options_description & opt) const override virtual
Implements ActsExamples::IBaseDetector.
Definition at line 76 of file TGeoDetectorWithOptions.cpp.
View newest version in sPHENIX GitHub at line 76 of file TGeoDetectorWithOptions.cpp
References Acts::Test::tmp(), and value.
Referenced by MakeActsGeometry::makeGeometry().
auto ActsExamples::TGeoDetectorWithOptions::finalize (const boost::program_options::variables_map & vm, std::shared_ptr< const Acts::IMaterialDecorator > mdecorator) -> std::pair<TrackingGeometryPtr, ContextDecorators> override virtual
Implements ActsExamples::IBaseDetector.
Definition at line 91 of file TGeoDetectorWithOptions.cpp.
View newest version in sPHENIX GitHub at line 91 of file TGeoDetectorWithOptions.cpp
References compare(), filter::config, ActsExamples::TGeoDetector::Config::fileName, ActsExamples::TGeoDetector::Config::layerLogLevel, testing::internal::move(), ActsExamples::TGeoDetector::Config::surfaceLogLevel, and ActsExamples::TGeoDetector::Config::volumeLogLevel.
Member Data Documentation
TGeoDetector ActsExamples::TGeoDetectorWithOptions::m_detector
Definition at line 18 of file TGeoDetectorWithOptions.hpp.
View newest version in sPHENIX GitHub at line 18 of file TGeoDetectorWithOptions.hpp
Referenced by MakeActsGeometry::build().
The documentation for this class was generated from the following files:
acts/blob/sPHENIX/Examples/Run/Common/include/ActsExamples/Detector/TGeoDetectorWithOptions.hpp
acts/blob/sPHENIX/Examples/Run/Common/src/TGeoDetectorWithOptions.cpp