Analysis Software: TrkrClusterContainerv3 Class Reference
TrkrClusterContainerv3 Class Reference
Cluster container object.
#include <coresoftware/blob/master/offline/packages/trackbase/TrkrClusterContainerv3.h>
Public Member Functions
TrkrClusterContainerv3 ()=default
void Reset () override
reset method
void identify (std::ostream &os=std::cout) const override
identify object
ConstIterator addCluster (TrkrCluster *) override
add a cluster
ConstIterator addClusterSpecifyKey (const TrkrDefs::cluskey, TrkrCluster *) override
add a cluster with specific key
void removeCluster (TrkrDefs::cluskey) override
remove cluster
void removeCluster (TrkrCluster *) override
remove cluster
Iterator findOrAddCluster (TrkrDefs::cluskey) override
find cluster matching key if any, add a new one otherwise and return cluster
ConstRange getClusters (TrkrDefs::hitsetkey) const override
get all clusters matching hitset
Map * getClusterMap (TrkrDefs::hitsetkey) override
get pointer to map containing clusters mathching hitset
TrkrCluster * findCluster (TrkrDefs::cluskey) const override
find cluster matching given key
unsigned int size (void) const override
total number of clusters
Public Member Functions inherited from TrkrClusterContainer
virtual ConstRange getClusters () const
return all clusters
Public Member Functions inherited from PHObject
PHObject ()
ctor
~PHObject () override
dtor
virtual PHObject * CloneMe () const
Virtual copy constructor.
virtual PHObject * clone () const final
PHObject * Clone (const char *newname="") const final
void Copy (TObject &object) const final
virtual int isValid () const
isValid returns non zero if object contains vailid data
virtual int isValid (const float) const
virtual int isValid (const double) const
virtual int isValid (const int) const
virtual int isValid (const unsigned int) const
virtual int isImplemented (const float f) const
virtual int isImplemented (const double f) const
virtual int isImplemented (const int i) const
virtual int isImplemented (const unsigned int i) const
virtual int Integrate () const
virtual int Integrate (PHObject *obj)
virtual void CopyFrom (const PHObject *obj)
Private Attributes
std::map< TrkrDefs::hitsetkey,
Map > m_clusmap
Additional Inherited Members
Public Types inherited from TrkrClusterContainer
using Map = std::map< TrkrDefs::cluskey, TrkrCluster * >
using Iterator = Map::iterator
using ConstIterator = Map::const_iterator
using Range = std::pair< Iterator, Iterator >
using ConstRange = std::pair< ConstIterator, ConstIterator >
Protected Member Functions inherited from TrkrClusterContainer
TrkrClusterContainer ()=default
constructor
Detailed Description
Cluster container object.
Definition at line 20 of file TrkrClusterContainerv3.h.
View newest version in sPHENIX GitHub at line 20 of file TrkrClusterContainerv3.h
Constructor & Destructor Documentation
TrkrClusterContainerv3::TrkrClusterContainerv3 () default
Member Function Documentation
TrkrClusterContainerv3::ConstIterator TrkrClusterContainerv3::addCluster (TrkrCluster *) override virtual
add a cluster
Reimplemented from TrkrClusterContainer.
Definition at line 71 of file TrkrClusterContainerv3.cc.
View newest version in sPHENIX GitHub at line 71 of file TrkrClusterContainerv3.cc
References addClusterSpecifyKey(), and TrkrCluster::getClusKey().
TrkrClusterContainerv3::ConstIterator TrkrClusterContainerv3::addClusterSpecifyKey (const TrkrDefs::cluskey , TrkrCluster *) override virtual
add a cluster with specific key
Reimplemented from TrkrClusterContainer.
Definition at line 76 of file TrkrClusterContainerv3.cc.
View newest version in sPHENIX GitHub at line 76 of file TrkrClusterContainerv3.cc
References TrkrDefs::getHitSetKeyFromClusKey(), and m_clusmap.
Referenced by addCluster().
TrkrCluster * TrkrClusterContainerv3::findCluster (TrkrDefs::cluskey) const override virtual
find cluster matching given key
Reimplemented from TrkrClusterContainer.
Definition at line 134 of file TrkrClusterContainerv3.cc.
View newest version in sPHENIX GitHub at line 134 of file TrkrClusterContainerv3.cc
References TrkrDefs::getHitSetKeyFromClusKey(), and m_clusmap.
TrkrClusterContainerv3::Iterator TrkrClusterContainerv3::findOrAddCluster (TrkrDefs::cluskey) override virtual
find cluster matching key if any, add a new one otherwise and return cluster
Reimplemented from TrkrClusterContainer.
Definition at line 115 of file TrkrClusterContainerv3.cc.
View newest version in sPHENIX GitHub at line 115 of file TrkrClusterContainerv3.cc
References TrkrDefs::getHitSetKeyFromClusKey(), it, and m_clusmap.
TrkrClusterContainerv3::Map * TrkrClusterContainerv3::getClusterMap (TrkrDefs::hitsetkey) override virtual
get pointer to map containing clusters mathching hitset
Reimplemented from TrkrClusterContainer.
Definition at line 110 of file TrkrClusterContainerv3.cc.
View newest version in sPHENIX GitHub at line 110 of file TrkrClusterContainerv3.cc
References m_clusmap.
TrkrClusterContainerv3::ConstRange TrkrClusterContainerv3::getClusters (TrkrDefs::hitsetkey hitsetkey) const override virtual
get all clusters matching hitset
Reimplemented from TrkrClusterContainer.
Definition at line 96 of file TrkrClusterContainerv3.cc.
View newest version in sPHENIX GitHub at line 96 of file TrkrClusterContainerv3.cc
References m_clusmap.
void TrkrClusterContainerv3::identify (std::ostream & os = std::cout) const override virtual
identify object
Reimplemented from TrkrClusterContainer.
Definition at line 32 of file TrkrClusterContainerv3.cc.
View newest version in sPHENIX GitHub at line 32 of file TrkrClusterContainerv3.cc
References TrkrDefs::getLayer(), layer, m_clusmap, and size().
void TrkrClusterContainerv3::removeCluster (TrkrDefs::cluskey) override virtual
remove cluster
Reimplemented from TrkrClusterContainer.
Definition at line 55 of file TrkrClusterContainerv3.cc.
View newest version in sPHENIX GitHub at line 55 of file TrkrClusterContainerv3.cc
References TrkrDefs::getHitSetKeyFromClusKey(), and m_clusmap.
Referenced by removeCluster().
void TrkrClusterContainerv3::removeCluster (TrkrCluster *) override virtual
remove cluster
Reimplemented from TrkrClusterContainer.
Definition at line 66 of file TrkrClusterContainerv3.cc.
View newest version in sPHENIX GitHub at line 66 of file TrkrClusterContainerv3.cc
References TrkrCluster::getClusKey(), and removeCluster().
void TrkrClusterContainerv3::Reset () override virtual
reset method
Reimplemented from TrkrClusterContainer.
Definition at line 20 of file TrkrClusterContainerv3.cc.
View newest version in sPHENIX GitHub at line 20 of file TrkrClusterContainerv3.cc
References m_clusmap.
unsigned int TrkrClusterContainerv3::size (void) const override virtual
total number of clusters
Reimplemented from TrkrClusterContainer.
Definition at line 156 of file TrkrClusterContainerv3.cc.
View newest version in sPHENIX GitHub at line 156 of file TrkrClusterContainerv3.cc
References m_clusmap.
Referenced by identify().
Member Data Documentation
std::map<TrkrDefs::hitsetkey, Map> TrkrClusterContainerv3::m_clusmap private
Definition at line 50 of file TrkrClusterContainerv3.h.
View newest version in sPHENIX GitHub at line 50 of file TrkrClusterContainerv3.h
Referenced by addClusterSpecifyKey(), findCluster(), findOrAddCluster(), getClusterMap(), getClusters(), identify(), removeCluster(), Reset(), and size().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/trackbase/TrkrClusterContainerv3.h
coresoftware/blob/master/offline/packages/trackbase/TrkrClusterContainerv3.cc