Analysis Software: Acts::detail::SmallObjectCache Class Reference
Acts::detail::SmallObjectCache Class Reference
Small opaque cache type which uses small buffer optimization.
#include <acts/blob/sPHENIX/Core/include/Acts/MagneticField/detail/SmallObjectCache.hpp>
Classes
struct Handler
struct HandlerBase
Public Member Functions
template<typename T >
T & get ()
template<typename T >
const T & get () const
~SmallObjectCache ()
SmallObjectCache (SmallObjectCache &&other)
SmallObjectCache & operator= (SmallObjectCache &&other)
Static Public Member Functions
template<typename T , typename... Args>
static SmallObjectCache make (Args &&...args)
Private Member Functions
SmallObjectCache ()=default
alignas (std::max_align_t) std
Private Attributes
const HandlerBase * m_handler {nullptr}
Detailed Description
Small opaque cache type which uses small buffer optimization.
Definition at line 20 of file SmallObjectCache.hpp.
View newest version in sPHENIX GitHub at line 20 of file SmallObjectCache.hpp
Constructor & Destructor Documentation
Acts::detail::SmallObjectCache::~SmallObjectCache () inline
Definition at line 57 of file SmallObjectCache.hpp.
View newest version in sPHENIX GitHub at line 57 of file SmallObjectCache.hpp
References assert, Acts::detail::SmallObjectCache::HandlerBase::destroy(), and m_handler.
Acts::detail::SmallObjectCache::SmallObjectCache (SmallObjectCache && other) inline
Definition at line 62 of file SmallObjectCache.hpp.
View newest version in sPHENIX GitHub at line 62 of file SmallObjectCache.hpp
References assert, m_handler, and Acts::detail::SmallObjectCache::HandlerBase::moveConstruct().
Acts::detail::SmallObjectCache::SmallObjectCache () private default
Member Function Documentation
Acts::detail::SmallObjectCache::alignas (std::max_align_t) inline private
Definition at line 111 of file SmallObjectCache.hpp.
View newest version in sPHENIX GitHub at line 111 of file SmallObjectCache.hpp
template<typename T > T& Acts::detail::SmallObjectCache::get () inline
Definition at line 42 of file SmallObjectCache.hpp.
View newest version in sPHENIX GitHub at line 42 of file SmallObjectCache.hpp
References Acts::UnitConstants::T.
template<typename T > const T& Acts::detail::SmallObjectCache::get () const inline
Definition at line 50 of file SmallObjectCache.hpp.
View newest version in sPHENIX GitHub at line 50 of file SmallObjectCache.hpp
References Acts::UnitConstants::T.
template<typename T , typename... Args> static SmallObjectCache Acts::detail::SmallObjectCache::make (Args &&... args) inline static
Definition at line 23 of file SmallObjectCache.hpp.
View newest version in sPHENIX GitHub at line 23 of file SmallObjectCache.hpp
References check_smearing_config::args, and Acts::UnitConstants::T.
SmallObjectCache& Acts::detail::SmallObjectCache::operator= (SmallObjectCache && other) inline
Definition at line 68 of file SmallObjectCache.hpp.
View newest version in sPHENIX GitHub at line 68 of file SmallObjectCache.hpp
References assert, m_handler, and Acts::detail::SmallObjectCache::HandlerBase::move().
Member Data Documentation
const HandlerBase* Acts::detail::SmallObjectCache::m_handler {nullptr} private
Definition at line 112 of file SmallObjectCache.hpp.
View newest version in sPHENIX GitHub at line 112 of file SmallObjectCache.hpp
Referenced by operator=(), SmallObjectCache(), and ~SmallObjectCache().
The documentation for this class was generated from the following file:
acts/blob/sPHENIX/Core/include/Acts/MagneticField/detail/SmallObjectCache.hpp