Analysis Software: TrkrHitTruthAssoc Class Reference
TrkrHitTruthAssoc Class Reference
Association object for PHG4Cells contributiong to TrkrHits.
#include <coresoftware/blob/master/offline/packages/trackbase/TrkrHitTruthAssoc.h>
Public Types
using MMap = std::multimap< TrkrDefs::hitsetkey, std::pair< TrkrDefs::hitkey, PHG4HitDefs::keytype > >
typedefs for convenience
using Iterator = MMap::iterator
using ConstIterator = MMap::const_iterator
using Range = std::pair< Iterator, Iterator >
using ConstRange = std::pair< ConstIterator, ConstIterator >
Public Member Functions
void Reset () override
Clear Event.
void identify (std::ostream &os=std::cout) const override
virtual void addAssoc (const TrkrDefs::hitsetkey hitsetkey, const TrkrDefs::hitkey hitkey, const PHG4HitDefs::keytype g4hitkey)
Add an association between hit and cell.
virtual void findOrAddAssoc (const TrkrDefs::hitsetkey hitsetkey, const TrkrDefs::hitkey hitkey, const PHG4HitDefs::keytype g4hitkey)
Add an association between hit and cell if it does not already exist.
virtual void removeAssoc (const TrkrDefs::hitsetkey hitsetkey, const TrkrDefs::hitkey hitkey)
virtual void getG4Hits (const TrkrDefs::hitsetkey hitsetkey, const unsigned int hidx, MMap &temp_map) const
Get cell keys associated with desired hit.
Public Member Functions inherited from PHObject
PHObject ()
ctor
~PHObject () override
dtor
virtual PHObject * CloneMe () const
Virtual copy constructor.
virtual PHObject * clone () const final
PHObject * Clone (const char *newname="") const final
void Copy (TObject &object) const final
virtual int isValid () const
isValid returns non zero if object contains vailid data
virtual int isValid (const float) const
virtual int isValid (const double) const
virtual int isValid (const int) const
virtual int isValid (const unsigned int) const
virtual int isImplemented (const float f) const
virtual int isImplemented (const double f) const
virtual int isImplemented (const int i) const
virtual int isImplemented (const unsigned int i) const
virtual int Integrate () const
virtual int Integrate (PHObject *obj)
virtual void CopyFrom (const PHObject *obj)
Protected Member Functions
TrkrHitTruthAssoc ()=default
ctor
Private Member Functions
ClassDefOverride (TrkrHitTruthAssoc, 1)
Detailed Description
Association object for PHG4Cells contributiong to TrkrHits.
Association object holding a multimap of PHG4Cells associated with a given TrkrHit
Definition at line 25 of file TrkrHitTruthAssoc.h.
View newest version in sPHENIX GitHub at line 25 of file TrkrHitTruthAssoc.h
Member Typedef Documentation
using TrkrHitTruthAssoc::ConstIterator = MMap::const_iterator
Definition at line 33 of file TrkrHitTruthAssoc.h.
View newest version in sPHENIX GitHub at line 33 of file TrkrHitTruthAssoc.h
using TrkrHitTruthAssoc::ConstRange = std::pair<ConstIterator, ConstIterator>
Definition at line 35 of file TrkrHitTruthAssoc.h.
View newest version in sPHENIX GitHub at line 35 of file TrkrHitTruthAssoc.h
using TrkrHitTruthAssoc::Iterator = MMap::iterator
Definition at line 32 of file TrkrHitTruthAssoc.h.
View newest version in sPHENIX GitHub at line 32 of file TrkrHitTruthAssoc.h
using TrkrHitTruthAssoc::MMap = std::multimap< TrkrDefs::hitsetkey, std::pair<TrkrDefs::hitkey, PHG4HitDefs::keytype> >
typedefs for convenience
Definition at line 31 of file TrkrHitTruthAssoc.h.
View newest version in sPHENIX GitHub at line 31 of file TrkrHitTruthAssoc.h
using TrkrHitTruthAssoc::Range = std::pair<Iterator, Iterator>
Definition at line 34 of file TrkrHitTruthAssoc.h.
View newest version in sPHENIX GitHub at line 34 of file TrkrHitTruthAssoc.h
Constructor & Destructor Documentation
TrkrHitTruthAssoc::TrkrHitTruthAssoc () protected default
ctor
Member Function Documentation
virtual void TrkrHitTruthAssoc::addAssoc (const TrkrDefs::hitsetkey hitsetkey, const TrkrDefs::hitkey hitkey, const PHG4HitDefs::keytype g4hitkey) inline virtual
Add an association between hit and cell.
Parameters
[in] hset TrkrHitSet key
[in] hidx TrkrHit index in TrkrHitSet
[in] ckey Key for assocuated g4hit
Reimplemented in TrkrHitTruthAssocv1.
Definition at line 49 of file TrkrHitTruthAssoc.h.
View newest version in sPHENIX GitHub at line 49 of file TrkrHitTruthAssoc.h
Referenced by PHG4TpcElectronDrift::process_event().
TrkrHitTruthAssoc::ClassDefOverride (TrkrHitTruthAssoc , 1) private
virtual void TrkrHitTruthAssoc::findOrAddAssoc (const TrkrDefs::hitsetkey hitsetkey, const TrkrDefs::hitkey hitkey, const PHG4HitDefs::keytype g4hitkey) inline virtual
Add an association between hit and cell if it does not already exist.
Parameters
[in] hset TrkrHitSet key
[in] hidx TrkrHit index in TrkrHitSet
[in] ckey Key for assocuated g4hit
Reimplemented in TrkrHitTruthAssocv1.
Definition at line 58 of file TrkrHitTruthAssoc.h.
View newest version in sPHENIX GitHub at line 58 of file TrkrHitTruthAssoc.h
virtual void TrkrHitTruthAssoc::getG4Hits (const TrkrDefs::hitsetkey hitsetkey, const unsigned int hidx, MMap & temp_map) const inline virtual
Get cell keys associated with desired hit.
Parameters
[in] hset TrkrHitSet key
[in] hidx TrkrHit index in TrkrHitSet
Definition at line 69 of file TrkrHitTruthAssoc.h.
View newest version in sPHENIX GitHub at line 69 of file TrkrHitTruthAssoc.h
Referenced by SvtxHitEval::all_truth_hits(), SvtxClusterEval::all_truth_hits(), SvtxClusterEval::all_truth_hits_by_nhit(), QAG4SimulationIntt::find_g4hits(), QAG4SimulationMvtx::find_g4hits(), QAG4SimulationMicromegas::find_g4hits(), QAG4SimulationTpc::find_g4hits(), QAG4SimulationTracking::find_g4hits(), TrackEvaluation::find_g4hits(), PHTruthSiliconAssociation::getG4PrimaryParticle(), PHTruthSiliconAssociation::getSiliconClustersFromParticle(), SvtxClusterEval::gtrackid_and_layer_by_nhit(), and PHSiliconTruthTrackSeeding::Process().
void TrkrHitTruthAssoc::identify (std::ostream & os = std::cout) const inline override virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from PHObject.
Reimplemented in TrkrHitTruthAssocv1.
Definition at line 40 of file TrkrHitTruthAssoc.h.
View newest version in sPHENIX GitHub at line 40 of file TrkrHitTruthAssoc.h
Referenced by PHG4TpcElectronDrift::process_event().
virtual void TrkrHitTruthAssoc::removeAssoc (const TrkrDefs::hitsetkey hitsetkey, const TrkrDefs::hitkey hitkey) inline virtual
Reimplemented in TrkrHitTruthAssocv1.
Definition at line 61 of file TrkrHitTruthAssoc.h.
View newest version in sPHENIX GitHub at line 61 of file TrkrHitTruthAssoc.h
Referenced by PHG4TpcDigitizer::DigitizeCylinderCells().
void TrkrHitTruthAssoc::Reset () inline override virtual
Clear Event.
Reimplemented from PHObject.
Reimplemented in TrkrHitTruthAssocv1.
Definition at line 37 of file TrkrHitTruthAssoc.h.
View newest version in sPHENIX GitHub at line 37 of file TrkrHitTruthAssoc.h
The documentation for this class was generated from the following file:
coresoftware/blob/master/offline/packages/trackbase/TrkrHitTruthAssoc.h