Analysis Software: common_plotting.SmashStyle Class Reference
common_plotting.SmashStyle Class Reference
Public Member Functions
def __init__
def get_all_figs
def get_all_subplots
def get_all_lines
def update_legends
def set
Public Attributes
params
Detailed Description
Smash style plot template for matplotlib
The smash style provides proper figsize, fontsize, fonttype, linewidth,
color cycles, ticksize and padding and legend style.
Example usage:
If one want to use the basic styles except linesytles, increased title
and plot space, minorticks, one can import the template file in the
beginning of python script:
      from common_plotting import smash_style
or simply:
      import common_plotting
Otherwise, call the set function before plt.legend() if there is one
or before plt.show() or plt.savefig() if there is no plt.legend() like:
      smash_style.set()
Definition at line 68 of file common_plotting.py.
View newest version in sPHENIX GitHub at line 68 of file common_plotting.py
Constructor & Destructor Documentation
def common_plotting.SmashStyle.__init__ (self)
Definition at line 92 of file common_plotting.py.
View newest version in sPHENIX GitHub at line 92 of file common_plotting.py
Member Function Documentation
def common_plotting.SmashStyle.get_all_figs (self)
Definition at line 97 of file common_plotting.py.
View newest version in sPHENIX GitHub at line 97 of file common_plotting.py
Referenced by common_plotting.SmashStyle.set().
def common_plotting.SmashStyle.get_all_lines (self, axes)
Definition at line 108 of file common_plotting.py.
View newest version in sPHENIX GitHub at line 108 of file common_plotting.py
Referenced by common_plotting.SmashStyle.set().
def common_plotting.SmashStyle.get_all_subplots (self, fig)
Definition at line 104 of file common_plotting.py.
View newest version in sPHENIX GitHub at line 104 of file common_plotting.py
Referenced by common_plotting.SmashStyle.set().
def common_plotting.SmashStyle.set (self, line_styles = True, title_padding = 1.03, minorticks_on = True)
Args:
     line_styles (bool, optional): True to use smash line style cycles.
 Defaults to True.
     title_padding (float, optional): To increase padding between title
 and plot. Defaults to 1.03, bigger title_padding to move title
 upper.
     minorticks_on: True to turn on minor ticks. Defaults to True.
 False to switch off minorticks
Definition at line 127 of file common_plotting.py.
View newest version in sPHENIX GitHub at line 127 of file common_plotting.py
References common_plotting.SmashStyle.get_all_figs(), common_plotting.SmashStyle.get_all_lines(), common_plotting.SmashStyle.get_all_subplots(), next, and common_plotting.SmashStyle.update_legends().
def common_plotting.SmashStyle.update_legends (self, ax)
Definition at line 114 of file common_plotting.py.
View newest version in sPHENIX GitHub at line 114 of file common_plotting.py
Referenced by common_plotting.SmashStyle.set().
Member Data Documentation
common_plotting.SmashStyle.params
Definition at line 93 of file common_plotting.py.
View newest version in sPHENIX GitHub at line 93 of file common_plotting.py
The documentation for this class was generated from the following file:
JETSCAPE/blob/master/external_packages/trento/bin/common_plotting.py