Analysis Software: LightCollectionModel Class Reference
LightCollectionModel Class Reference
#include <coresoftware/blob/master/simulation/g4simulation/g4detectors/LightCollectionModel.h>
Public Member Functions
LightCollectionModel ()=default
LightCollectionModel (const LightCollectionModel &)=delete
delete copy ctor and assignment opertor (cppcheck)
LightCollectionModel & operator= (const LightCollectionModel &)=delete
virtual ~LightCollectionModel ()
void load_data_file (const std::string &input_file, const std::string &histogram_light_guide_model, const std::string &histogram_fiber_model)
input data file
void load_data_from_CDB (const std::string &domain, const std::string &histogram_light_guide_model, const std::string &histogram_fiber_model)
load from CDB
bool use_light_guide_model () const
Whether use light collection model.
bool use_fiber_model () const
Whether use Light Transmission Efficiency model for the fiber.
double get_light_guide_efficiency (const double x_fraction, const double y_fraction)
get Light Collection Efficiency for the light guide as function of x,y position in fraction of tower width
double get_fiber_transmission (const double z_distance)
get Light Transmission Efficiency for the fiber as function of z position (cm) in the fiber. Z=0 is at the middle of the fiber
Private Attributes
TH2
*data_grid_light_guide_efficiency nullptr
2-D data grid for Light Collection Efficiency for the light guide as function of x,y position in fraction of tower width
TH1 * data_grid_fiber_trans {nullptr}
1-D data grid for the light transmission efficiency in the fiber as function of distance to location in the fiber. Z=0 is at the middle of the fiber
TH2 * data_grid_light_guide_efficiency_verify {nullptr}
TH1 * data_grid_fiber_trans_verify {nullptr}
Detailed Description
Definition at line 10 of file LightCollectionModel.h.
View newest version in sPHENIX GitHub at line 10 of file LightCollectionModel.h
Constructor & Destructor Documentation
LightCollectionModel::LightCollectionModel () default
LightCollectionModel::LightCollectionModel (const LightCollectionModel &) explicit delete
delete copy ctor and assignment opertor (cppcheck)
LightCollectionModel::~LightCollectionModel () virtual
Definition at line 19 of file LightCollectionModel.cc.
View newest version in sPHENIX GitHub at line 19 of file LightCollectionModel.cc
References data_grid_fiber_trans.
Member Function Documentation
double LightCollectionModel::get_fiber_transmission (const double z_distance)
get Light Transmission Efficiency for the fiber as function of z position (cm) in the fiber. Z=0 is at the middle of the fiber
Definition at line 105 of file LightCollectionModel.cc.
View newest version in sPHENIX GitHub at line 105 of file LightCollectionModel.cc
References assert, data_grid_fiber_trans, data_grid_fiber_trans_verify, Fun4AllServer::instance(), and Fun4AllServer::registerHisto().
Referenced by CaloWaveformSim::maphitetaphi(), PHG4SpacalSteppingAction::NoHitSteppingAction(), and PHG4FullProjSpacalCellReco::process_event().
double LightCollectionModel::get_light_guide_efficiency (const double x_fraction, const double y_fraction)
get Light Collection Efficiency for the light guide as function of x,y position in fraction of tower width
Definition at line 77 of file LightCollectionModel.cc.
View newest version in sPHENIX GitHub at line 77 of file LightCollectionModel.cc
References assert, data_grid_light_guide_efficiency_verify, Fun4AllServer::instance(), and Fun4AllServer::registerHisto().
Referenced by CaloWaveformSim::maphitetaphi(), PHG4SpacalSteppingAction::NoHitSteppingAction(), and PHG4FullProjSpacalCellReco::process_event().
void LightCollectionModel::load_data_file (const std::string & input_file, const std::string & histogram_light_guide_model, const std::string & histogram_fiber_model)
input data file
Definition at line 54 of file LightCollectionModel.cc.
View newest version in sPHENIX GitHub at line 54 of file LightCollectionModel.cc
References assert, and data_grid_fiber_trans.
Referenced by CEMC_Cells(), Fun4All_G4_Prototype2(), Fun4All_G4_Prototype3(), Fun4All_G4_Prototype4(), and PHG4SpacalSubsystem::InitRunSubsystem().
void LightCollectionModel::load_data_from_CDB (const std::string & domain, const std::string & histogram_light_guide_model, const std::string & histogram_fiber_model)
load from CDB
Definition at line 25 of file LightCollectionModel.cc.
View newest version in sPHENIX GitHub at line 25 of file LightCollectionModel.cc
References assert, data_grid_fiber_trans, PHFlag::get_uint64Flag(), CDBInterface::getUrl(), recoConsts::instance(), CDBInterface::instance(), and summary::url.
LightCollectionModel& LightCollectionModel::operator= (const LightCollectionModel &) delete
bool LightCollectionModel::use_fiber_model () const inline
Whether use Light Transmission Efficiency model for the fiber.
Definition at line 31 of file LightCollectionModel.h.
View newest version in sPHENIX GitHub at line 31 of file LightCollectionModel.h
References data_grid_fiber_trans.
Referenced by CaloWaveformSim::maphitetaphi(), PHG4SpacalSteppingAction::NoHitSteppingAction(), and PHG4FullProjSpacalCellReco::process_event().
bool LightCollectionModel::use_light_guide_model () const inline
Whether use light collection model.
Definition at line 28 of file LightCollectionModel.h.
View newest version in sPHENIX GitHub at line 28 of file LightCollectionModel.h
Member Data Documentation
TH1* LightCollectionModel::data_grid_fiber_trans {nullptr} private
1-D data grid for the light transmission efficiency in the fiber as function of distance to location in the fiber. Z=0 is at the middle of the fiber
Definition at line 44 of file LightCollectionModel.h.
View newest version in sPHENIX GitHub at line 44 of file LightCollectionModel.h
Referenced by get_fiber_transmission(), load_data_file(), load_data_from_CDB(), use_fiber_model(), and ~LightCollectionModel().
TH1* LightCollectionModel::data_grid_fiber_trans_verify {nullptr} private
Definition at line 51 of file LightCollectionModel.h.
View newest version in sPHENIX GitHub at line 51 of file LightCollectionModel.h
Referenced by get_fiber_transmission().
TH2* LightCollectionModel::data_grid_light_guide_efficiency_verify {nullptr} private
Definition at line 49 of file LightCollectionModel.h.
View newest version in sPHENIX GitHub at line 49 of file LightCollectionModel.h
Referenced by get_light_guide_efficiency().
TH2* data_grid_light_guide_efficiency LightCollectionModel::nullptr private
2-D data grid for Light Collection Efficiency for the light guide as function of x,y position in fraction of tower width
Definition at line 41 of file LightCollectionModel.h.
View newest version in sPHENIX GitHub at line 41 of file LightCollectionModel.h
The documentation for this class was generated from the following files:
coresoftware/blob/master/simulation/g4simulation/g4detectors/LightCollectionModel.h
coresoftware/blob/master/simulation/g4simulation/g4detectors/LightCollectionModel.cc