Analysis Software: TpcSimpleClusterizer Class Reference
TpcSimpleClusterizer Class Reference
#include <coresoftware/blob/master/offline/packages/tpc/TpcSimpleClusterizer.h>
Public Member Functions
TpcSimpleClusterizer (const std::string &name="TpcSimpleClusterizer")
~TpcSimpleClusterizer () override=default
int InitRun (PHCompositeNode *topNode) override
int process_event (PHCompositeNode *topNode) override
int End (PHCompositeNode *topNode) override
Called at the end of all processing.
void set_sector_fiducial_cut (const double cut)
void set_do_hit_association (bool do_assoc)
Public Member Functions inherited from SubsysReco
~SubsysReco () override
virtual int EndRun (const int)
Called at the end of each run.
virtual int Init (PHCompositeNode *)
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
void Print (const std::string &="ALL") const override
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Private Member Functions
bool is_in_sector_boundary (int phibin, int sector, PHG4TpcCylinderGeom *layergeom) const
Private Attributes
TrkrHitSetContainer * m_hits = nullptr
TrkrClusterContainer * m_clusterlist = nullptr
TrkrClusterHitAssoc * m_clusterhitassoc = nullptr
ActsGeometry * m_tGeometry = nullptr
bool do_hit_assoc = true
double pedestal = 74.4
double SectorFiducialCut = 0.5
double par0_neg = 0.0503
double par0_pos = -0.0503
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = std::numeric_limits<int>::max() - 10
}
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Detailed Description
Definition at line 25 of file TpcSimpleClusterizer.h.
View newest version in sPHENIX GitHub at line 25 of file TpcSimpleClusterizer.h
Constructor & Destructor Documentation
TpcSimpleClusterizer::TpcSimpleClusterizer (const std::string & name = "TpcSimpleClusterizer")
Definition at line 338 of file TpcSimpleClusterizer.cc.
View newest version in sPHENIX GitHub at line 338 of file TpcSimpleClusterizer.cc
TpcSimpleClusterizer::~TpcSimpleClusterizer () override default
Member Function Documentation
int TpcSimpleClusterizer::End (PHCompositeNode *) override virtual
Called at the end of all processing.
Reimplemented from SubsysReco.
Definition at line 604 of file TpcSimpleClusterizer.cc.
View newest version in sPHENIX GitHub at line 604 of file TpcSimpleClusterizer.cc
References Fun4AllReturnCodes::EVENT_OK.
int TpcSimpleClusterizer::InitRun (PHCompositeNode *) override virtual
Called for first event when run number is known. Typically this is where you may want to fetch data from database, because you know the run number.
Reimplemented from SubsysReco.
Definition at line 374 of file TpcSimpleClusterizer.cc.
View newest version in sPHENIX GitHub at line 374 of file TpcSimpleClusterizer.cc
References Fun4AllReturnCodes::ABORTRUN, PHCompositeNode::addNode(), Fun4AllReturnCodes::EVENT_OK, PHNodeIterator::findFirst(), and PHWHERE.
bool TpcSimpleClusterizer::is_in_sector_boundary (int phibin, int sector, PHG4TpcCylinderGeom * layergeom) const private
Definition at line 342 of file TpcSimpleClusterizer.cc.
View newest version in sPHENIX GitHub at line 342 of file TpcSimpleClusterizer.cc
References double(), PHG4TpcCylinderGeom::get_phibins(), PHG4TpcCylinderGeom::get_radius(), and SectorFiducialCut.
int TpcSimpleClusterizer::process_event (PHCompositeNode *) override virtual
Called for each event. This is where you do the real work.
Reimplemented from SubsysReco.
Definition at line 425 of file TpcSimpleClusterizer.cc.
View newest version in sPHENIX GitHub at line 425 of file TpcSimpleClusterizer.cc
References Fun4AllReturnCodes::ABORTRUN, TrkrClusterHitAssoc::addAssoc(), TrkrClusterContainer::addClusterSpecifyKey(), configureMap::data, distance(), do_hit_assoc, Fun4AllReturnCodes::EVENT_OK, PHNodeIterator::findFirst(), TrkrDefs::genClusKey(), TpcDefs::genHitSetKey(), PHG4TpcCylinderGeom::get_phibins(), PHG4TpcCylinderGeom::get_zbins(), TrkrHitSetContainer::getHitSets(), TrkrDefs::getLayer(), PHG4TpcCylinderGeomContainer::GetLayerCellGeom(), TpcDefs::getSectorId(), TpcDefs::getSide(), index, layer, m_clusterhitassoc, m_clusterlist, m_hits, m_tGeometry, par0_neg, par0_pos, pedestal, PHWHERE, printf(), TrkrClusterContainer::size(), TrkrDefs::tpcId, and Fun4AllBase::Verbosity().
void TpcSimpleClusterizer::set_do_hit_association (bool do_assoc) inline
Definition at line 36 of file TpcSimpleClusterizer.h.
View newest version in sPHENIX GitHub at line 36 of file TpcSimpleClusterizer.h
References do_hit_assoc.
void TpcSimpleClusterizer::set_sector_fiducial_cut (const double cut) inline
Definition at line 35 of file TpcSimpleClusterizer.h.
View newest version in sPHENIX GitHub at line 35 of file TpcSimpleClusterizer.h
References SectorFiducialCut.
Member Data Documentation
bool TpcSimpleClusterizer::do_hit_assoc = true private
Definition at line 46 of file TpcSimpleClusterizer.h.
View newest version in sPHENIX GitHub at line 46 of file TpcSimpleClusterizer.h
Referenced by process_event(), and set_do_hit_association().
TrkrClusterHitAssoc* TpcSimpleClusterizer::m_clusterhitassoc = nullptr private
Definition at line 43 of file TpcSimpleClusterizer.h.
View newest version in sPHENIX GitHub at line 43 of file TpcSimpleClusterizer.h
Referenced by process_event().
TrkrClusterContainer* TpcSimpleClusterizer::m_clusterlist = nullptr private
Definition at line 42 of file TpcSimpleClusterizer.h.
View newest version in sPHENIX GitHub at line 42 of file TpcSimpleClusterizer.h
Referenced by process_event().
TrkrHitSetContainer* TpcSimpleClusterizer::m_hits = nullptr private
Definition at line 41 of file TpcSimpleClusterizer.h.
View newest version in sPHENIX GitHub at line 41 of file TpcSimpleClusterizer.h
Referenced by process_event().
ActsGeometry* TpcSimpleClusterizer::m_tGeometry = nullptr private
Definition at line 44 of file TpcSimpleClusterizer.h.
View newest version in sPHENIX GitHub at line 44 of file TpcSimpleClusterizer.h
Referenced by process_event().
double TpcSimpleClusterizer::par0_neg = 0.0503 private
Definition at line 52 of file TpcSimpleClusterizer.h.
View newest version in sPHENIX GitHub at line 52 of file TpcSimpleClusterizer.h
Referenced by process_event().
double TpcSimpleClusterizer::par0_pos = -0.0503 private
Definition at line 53 of file TpcSimpleClusterizer.h.
View newest version in sPHENIX GitHub at line 53 of file TpcSimpleClusterizer.h
Referenced by process_event().
double TpcSimpleClusterizer::pedestal = 74.4 private
Definition at line 47 of file TpcSimpleClusterizer.h.
View newest version in sPHENIX GitHub at line 47 of file TpcSimpleClusterizer.h
Referenced by process_event().
double TpcSimpleClusterizer::SectorFiducialCut = 0.5 private
Definition at line 48 of file TpcSimpleClusterizer.h.
View newest version in sPHENIX GitHub at line 48 of file TpcSimpleClusterizer.h
Referenced by is_in_sector_boundary(), and set_sector_fiducial_cut().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/tpc/TpcSimpleClusterizer.h
coresoftware/blob/master/offline/packages/tpc/TpcSimpleClusterizer.cc