Analysis Software: G4Example03DisplayAction Class Reference
G4Example03DisplayAction Class Reference
#include <g4exampledetector/blob/master/color/source/G4Example03DisplayAction.h>
Public Member Functions
G4Example03DisplayAction (const std::string &name, PHParameters *parameters)
virtual ~G4Example03DisplayAction ()
void ApplyDisplayAction (G4VPhysicalVolume *physvol)
ApplyDisplayAction method.
void SetMyVolume (G4LogicalVolume *vol)
void SetColor (const double red, const double green, const double blue, const double alpha=1.)
Public Member Functions inherited from PHG4DisplayAction
PHG4DisplayAction ()=delete
constructor
PHG4DisplayAction (const std::string &name)
virtual ~PHG4DisplayAction ()
destructor
virtual void SetName (const std::string &name)
virtual std::string GetName () const
virtual void Print (const std::string &="ALL")
Private Attributes
PHParameters * m_Params
G4LogicalVolume * m_MyVolume
G4VisAttributes * m_VisAtt
G4Colour * m_Colour
Additional Inherited Members
Public Types inherited from PHG4DisplayAction
enum CheckReturnCodes { ABORT = -1, FAILED = 0, ACCEPT = 1 }
Protected Member Functions inherited from PHG4DisplayAction
int FindVolumes (G4VPhysicalVolume *physvol)
find FindVolume method
virtual int CheckVolume (G4VPhysicalVolume *)
find CheckVolume method
virtual void ApplyVisAttributes (G4VPhysicalVolume *)
ApplyVisAttributes method.
Detailed Description
Definition at line 16 of file G4Example03DisplayAction.h.
View newest version in sPHENIX GitHub at line 16 of file G4Example03DisplayAction.h
Constructor & Destructor Documentation
G4Example03DisplayAction::G4Example03DisplayAction (const std::string & name, PHParameters * parameters)
Definition at line 16 of file G4Example03DisplayAction.cc.
View newest version in sPHENIX GitHub at line 16 of file G4Example03DisplayAction.cc
G4Example03DisplayAction::~G4Example03DisplayAction () virtual
Definition at line 25 of file G4Example03DisplayAction.cc.
View newest version in sPHENIX GitHub at line 25 of file G4Example03DisplayAction.cc
References m_Colour, and m_VisAtt.
Member Function Documentation
void G4Example03DisplayAction::ApplyDisplayAction (G4VPhysicalVolume * physvol) virtual
ApplyDisplayAction method.
pure virtual - has to be implemented by derived class creates and set VisAttributes for volumes
Parameters
[in] physvol starting volume in hierarchy (typically world volume)
Implements PHG4DisplayAction.
Definition at line 31 of file G4Example03DisplayAction.cc.
View newest version in sPHENIX GitHub at line 31 of file G4Example03DisplayAction.cc
References PHParameters::get_int_param(), PHParameters::get_string_param(), m_Colour, m_MyVolume, m_Params, m_VisAtt, and PHG4Utils::SetColour().
void G4Example03DisplayAction::SetColor (const double red, const double green, const double blue, const double alpha = 1.)
Definition at line 64 of file G4Example03DisplayAction.cc.
View newest version in sPHENIX GitHub at line 64 of file G4Example03DisplayAction.cc
References m_Colour.
Referenced by G4Example03Subsystem::InitRunSubsystem().
void G4Example03DisplayAction::SetMyVolume (G4LogicalVolume * vol) inline
Definition at line 24 of file G4Example03DisplayAction.h.
View newest version in sPHENIX GitHub at line 24 of file G4Example03DisplayAction.h
References m_MyVolume.
Referenced by G4Example03Detector::ConstructMe().
Member Data Documentation
G4Colour* G4Example03DisplayAction::m_Colour private
Definition at line 31 of file G4Example03DisplayAction.h.
View newest version in sPHENIX GitHub at line 31 of file G4Example03DisplayAction.h
Referenced by ApplyDisplayAction(), SetColor(), and ~G4Example03DisplayAction().
G4LogicalVolume* G4Example03DisplayAction::m_MyVolume private
Definition at line 29 of file G4Example03DisplayAction.h.
View newest version in sPHENIX GitHub at line 29 of file G4Example03DisplayAction.h
Referenced by ApplyDisplayAction(), and SetMyVolume().
PHParameters* G4Example03DisplayAction::m_Params private
Definition at line 28 of file G4Example03DisplayAction.h.
View newest version in sPHENIX GitHub at line 28 of file G4Example03DisplayAction.h
Referenced by ApplyDisplayAction().
G4VisAttributes* G4Example03DisplayAction::m_VisAtt private
Definition at line 30 of file G4Example03DisplayAction.h.
View newest version in sPHENIX GitHub at line 30 of file G4Example03DisplayAction.h
Referenced by ApplyDisplayAction(), and ~G4Example03DisplayAction().
The documentation for this class was generated from the following files:
g4exampledetector/blob/master/color/source/G4Example03DisplayAction.h
g4exampledetector/blob/master/color/source/G4Example03DisplayAction.cc