Analysis Software: PHParameterInterface Class Reference
PHParameterInterface Class Reference abstract
#include <coresoftware/blob/master/offline/database/PHParameter/PHParameterInterface.h>
Public Member Functions
PHParameterInterface (const std::string &name)
PHParameterInterface (const PHParameterInterface &)=delete
PHParameterInterface & operator= (PHParameterInterface const &)=delete
virtual ~PHParameterInterface ()
void set_paramname (const std::string &name)
virtual void SetDefaultParameters ()=0
void set_double_param (const std::string &name, const double dval)
double get_double_param (const std::string &name) const
void set_int_param (const std::string &name, const int ival)
int get_int_param (const std::string &name) const
void set_string_param (const std::string &name, const std::string &sval)
std::string get_string_param (const std::string &name) const
void UpdateParametersWithMacro ()
void SaveToNodeTree (PHCompositeNode *runNode, const std::string &nodename)
void PutOnParNode (PHCompositeNode *parNode, const std::string &nodename)
void Print () const
Protected Member Functions
void set_default_double_param (const std::string &name, const double dval)
void set_default_int_param (const std::string &name, const int ival)
void set_default_string_param (const std::string &name, const std::string &sval)
void InitializeParameters ()
Private Attributes
PHParameters * m_Params = nullptr
bool m_Locked = false
std::map< const std::string,
double > m_DoubleParMap
std::map< const std::string, int > m_IntParMap
std::map< const std::string,
std::string > m_StringParMap
std::map< const std::string,
double > m_DefaultDoubleParMap
std::map< const std::string, int > m_DefaultIntParMap
std::map< const std::string,
std::string > m_DefaultStringParMap
Detailed Description
Definition at line 12 of file PHParameterInterface.h.
View newest version in sPHENIX GitHub at line 12 of file PHParameterInterface.h
Constructor & Destructor Documentation
PHParameterInterface::PHParameterInterface (const std::string & name)
Definition at line 13 of file PHParameterInterface.cc.
View newest version in sPHENIX GitHub at line 13 of file PHParameterInterface.cc
PHParameterInterface::PHParameterInterface (const PHParameterInterface &) delete
PHParameterInterface::~PHParameterInterface () virtual
Definition at line 18 of file PHParameterInterface.cc.
View newest version in sPHENIX GitHub at line 18 of file PHParameterInterface.cc
References m_Params.
Member Function Documentation
double PHParameterInterface::get_double_param (const std::string & name) const
Definition at line 93 of file PHParameterInterface.cc.
View newest version in sPHENIX GitHub at line 93 of file PHParameterInterface.cc
References PHParameters::get_double_param(), and m_Params.
Referenced by Prototype2RawTowerBuilder::InitRun(), PHG4Prototype2HcalCellReco::InitRun(), PHG4HcalCellReco::InitRun(), HcalRawTowerBuilder::InitRun(), PHG4EPDModuleReco::InitRun(), PHG4InttDigitizer::InitRun(), PHG4VertexSelection::InitRun(), PHG4MicromegasDigitizer::InitRun(), PHG4TpcCentralMembrane::InitRun(), PHG4FullProjSpacalCellReco::InitRun(), PHG4TpcDirectLaser::InitRun(), PHG4InttHitReco::InitRun(), PHG4MvtxHitReco::InitRun(), PHG4MicromegasHitReco::InitRun(), PHG4TpcElectronDrift::InitRun(), TpcDirectLaserReconstruction::InitRun(), TpcSpaceChargeReconstruction::InitRun(), and PHG4TpcPadPlaneReadout::UpdateInternalParameters().
int PHParameterInterface::get_int_param (const std::string & name) const
Definition at line 118 of file PHParameterInterface.cc.
View newest version in sPHENIX GitHub at line 118 of file PHParameterInterface.cc
References PHParameters::get_int_param(), and m_Params.
Referenced by Prototype2RawTowerBuilder::InitRun(), HcalRawTowerBuilder::InitRun(), PHG4TpcCentralMembrane::InitRun(), PHG4TpcDirectLaser::InitRun(), PHG4MvtxHitReco::InitRun(), and PHG4TpcPadPlaneReadout::UpdateInternalParameters().
std::string PHParameterInterface::get_string_param (const std::string & name) const
Definition at line 144 of file PHParameterInterface.cc.
View newest version in sPHENIX GitHub at line 144 of file PHParameterInterface.cc
References PHParameters::get_string_param(), and m_Params.
void PHParameterInterface::InitializeParameters () protected
Definition at line 180 of file PHParameterInterface.cc.
View newest version in sPHENIX GitHub at line 180 of file PHParameterInterface.cc
References m_DefaultDoubleParMap, m_DefaultIntParMap, m_DefaultStringParMap, m_Params, PHParameters::set_double_param(), PHParameters::set_int_param(), PHParameters::set_string_param(), and SetDefaultParameters().
Referenced by HcalRawTowerBuilder::HcalRawTowerBuilder(), HelicalFitter::HelicalFitter(), PHG4EPDModuleReco::PHG4EPDModuleReco(), PHG4FullProjSpacalCellReco::PHG4FullProjSpacalCellReco(), PHG4HcalCellReco::PHG4HcalCellReco(), PHG4InttDigitizer::PHG4InttDigitizer(), PHG4MicromegasDigitizer::PHG4MicromegasDigitizer(), PHG4MicromegasHitReco::PHG4MicromegasHitReco(), PHG4Prototype2HcalCellReco::PHG4Prototype2HcalCellReco(), PHG4TpcCentralMembrane::PHG4TpcCentralMembrane(), PHG4TpcDirectLaser::PHG4TpcDirectLaser(), PHG4TpcElectronDrift::PHG4TpcElectronDrift(), PHG4TpcPadPlaneReadout::PHG4TpcPadPlaneReadout(), PHG4VertexSelection::PHG4VertexSelection(), PHSiliconTpcTrackMatching::PHSiliconTpcTrackMatching(), PHTpcDeltaZCorrection::PHTpcDeltaZCorrection(), Prototype2RawTowerBuilder::Prototype2RawTowerBuilder(), TpcDirectLaserReconstruction::TpcDirectLaserReconstruction(), and TpcSpaceChargeReconstruction::TpcSpaceChargeReconstruction().
PHParameterInterface& PHParameterInterface::operator= (PHParameterInterface const &) delete
void PHParameterInterface::Print () const
Definition at line 198 of file PHParameterInterface.cc.
View newest version in sPHENIX GitHub at line 198 of file PHParameterInterface.cc
References m_Params, and PHParameters::Print().
Referenced by HcalRawTowerBuilder::Print().
void PHParameterInterface::PutOnParNode (PHCompositeNode * parNode, const std::string & nodename)
Definition at line 173 of file PHParameterInterface.cc.
View newest version in sPHENIX GitHub at line 173 of file PHParameterInterface.cc
References PHCompositeNode::addNode(), m_Locked, m_Params, and PHParameters::Name().
Referenced by Prototype2RawTowerBuilder::InitRun(), PHG4Prototype2HcalCellReco::InitRun(), PHG4HcalCellReco::InitRun(), PHG4InttDigitizer::InitRun(), HcalRawTowerBuilder::InitRun(), PHG4TpcPadPlane::InitRun(), PHG4FullProjSpacalCellReco::InitRun(), PHG4InttHitReco::InitRun(), and PHG4TpcElectronDrift::InitRun().
void PHParameterInterface::SaveToNodeTree (PHCompositeNode * runNode, const std::string & nodename)
Definition at line 166 of file PHParameterInterface.cc.
View newest version in sPHENIX GitHub at line 166 of file PHParameterInterface.cc
References m_Locked, m_Params, and PHParameters::SaveToNodeTree().
Referenced by Prototype2RawTowerBuilder::InitRun(), PHG4Prototype2HcalCellReco::InitRun(), PHG4HcalCellReco::InitRun(), PHG4InttDigitizer::InitRun(), HcalRawTowerBuilder::InitRun(), PHG4TpcPadPlane::InitRun(), PHG4FullProjSpacalCellReco::InitRun(), PHG4InttHitReco::InitRun(), PHG4MvtxHitReco::InitRun(), and PHG4TpcElectronDrift::InitRun().
void PHParameterInterface::set_default_double_param (const std::string & name, const double dval) protected
Definition at line 28 of file PHParameterInterface.cc.
View newest version in sPHENIX GitHub at line 28 of file PHParameterInterface.cc
References m_DefaultDoubleParMap, and perf_headwind::name.
Referenced by Prototype2RawTowerBuilder::SetDefaultParameters(), PHG4Prototype2HcalCellReco::SetDefaultParameters(), PHG4HcalCellReco::SetDefaultParameters(), PHG4VertexSelection::SetDefaultParameters(), PHG4EPDModuleReco::SetDefaultParameters(), PHG4InttDigitizer::SetDefaultParameters(), PHG4MicromegasDigitizer::SetDefaultParameters(), PHG4TpcCentralMembrane::SetDefaultParameters(), PHG4TpcDirectLaser::SetDefaultParameters(), PHG4FullProjSpacalCellReco::SetDefaultParameters(), PHG4InttHitReco::SetDefaultParameters(), PHG4MicromegasHitReco::SetDefaultParameters(), PHG4TpcPadPlaneReadout::SetDefaultParameters(), PHG4MvtxHitReco::SetDefaultParameters(), PHG4TpcElectronDrift::SetDefaultParameters(), TpcDirectLaserReconstruction::SetDefaultParameters(), HcalRawTowerBuilder::SetDefaultParameters(), and TpcSpaceChargeReconstruction::SetDefaultParameters().
void PHParameterInterface::set_default_int_param (const std::string & name, const int ival) protected
Definition at line 43 of file PHParameterInterface.cc.
View newest version in sPHENIX GitHub at line 43 of file PHParameterInterface.cc
References m_DefaultIntParMap, and perf_headwind::name.
Referenced by Prototype2RawTowerBuilder::SetDefaultParameters(), PHG4TpcCentralMembrane::SetDefaultParameters(), PHG4TpcDirectLaser::SetDefaultParameters(), PHG4TpcPadPlaneReadout::SetDefaultParameters(), PHG4MvtxHitReco::SetDefaultParameters(), and HcalRawTowerBuilder::SetDefaultParameters().
void PHParameterInterface::set_default_string_param (const std::string & name, const std::string & sval) protected
Definition at line 58 of file PHParameterInterface.cc.
View newest version in sPHENIX GitHub at line 58 of file PHParameterInterface.cc
References m_DefaultStringParMap, and perf_headwind::name.
void PHParameterInterface::set_double_param (const std::string & name, const double dval)
Definition at line 72 of file PHParameterInterface.cc.
View newest version in sPHENIX GitHub at line 72 of file PHParameterInterface.cc
References m_DefaultDoubleParMap, m_DoubleParMap, m_Locked, perf_headwind::name, and PHWHERE.
Referenced by EPD_Tiles(), Fun4All_G4_TPC(), Fun4All_TestBeam_TPC(), HCALInner_Towers(), HCALOuter_Towers(), Intt_Cells(), Mvtx_Cells(), HcalRawTowerBuilder::ReadParamsFromNodeTree(), PHG4Prototype2HcalCellReco::set_timing_window(), PHG4HcalCellReco::set_timing_window(), PHG4FullProjSpacalCellReco::set_timing_window(), and PHG4EPDModuleReco::set_timing_window().
void PHParameterInterface::set_int_param (const std::string & name, const int ival)
Definition at line 98 of file PHParameterInterface.cc.
View newest version in sPHENIX GitHub at line 98 of file PHParameterInterface.cc
References m_DefaultIntParMap, m_IntParMap, m_Locked, perf_headwind::name, and PHWHERE.
Referenced by Fun4All_G4_TPC(), Fun4All_TestBeam_TPC(), HCALInner_Towers(), HCALOuter_Towers(), Prototype2RawTowerBuilder::ReadParamsFromNodeTree(), and HcalRawTowerBuilder::ReadParamsFromNodeTree().
void PHParameterInterface::set_paramname (const std::string & name)
Definition at line 23 of file PHParameterInterface.cc.
View newest version in sPHENIX GitHub at line 23 of file PHParameterInterface.cc
References m_Params, and PHParameters::set_name().
void PHParameterInterface::set_string_param (const std::string & name, const std::string & sval)
Definition at line 123 of file PHParameterInterface.cc.
View newest version in sPHENIX GitHub at line 123 of file PHParameterInterface.cc
References m_DefaultStringParMap, m_Locked, m_StringParMap, perf_headwind::name, and PHWHERE.
virtual void PHParameterInterface::SetDefaultParameters () pure virtual
Implemented in TpcSpaceChargeReconstruction, HcalRawTowerBuilder, TpcDirectLaserReconstruction, PHG4MvtxHitReco, PHG4TpcElectronDrift, PHG4TpcPadPlaneReadout, HelicalFitter, PHG4MicromegasHitReco, PHG4InttHitReco, PHG4FullProjSpacalCellReco, PHG4TpcDirectLaser, PHTpcDeltaZCorrection, PHG4MicromegasDigitizer, PHG4TpcCentralMembrane, PHG4EPDModuleReco, PHG4InttDigitizer, PHG4VertexSelection, PHSiliconTpcTrackMatching, PHG4HcalCellReco, PHG4Prototype2HcalCellReco, and Prototype2RawTowerBuilder.
Referenced by InitializeParameters().
void PHParameterInterface::UpdateParametersWithMacro ()
Definition at line 149 of file PHParameterInterface.cc.
View newest version in sPHENIX GitHub at line 149 of file PHParameterInterface.cc
References m_DoubleParMap, m_IntParMap, m_Params, m_StringParMap, PHParameters::set_double_param(), PHParameters::set_int_param(), and PHParameters::set_string_param().
Referenced by Prototype2RawTowerBuilder::InitRun(), PHG4Prototype2HcalCellReco::InitRun(), PHG4HcalCellReco::InitRun(), PHG4EPDModuleReco::InitRun(), PHG4InttDigitizer::InitRun(), HcalRawTowerBuilder::InitRun(), PHG4VertexSelection::InitRun(), PHG4TpcCentralMembrane::InitRun(), PHG4MicromegasDigitizer::InitRun(), PHG4TpcDirectLaser::InitRun(), PHG4TpcPadPlane::InitRun(), PHG4FullProjSpacalCellReco::InitRun(), PHTpcDeltaZCorrection::InitRun(), PHG4MvtxHitReco::InitRun(), PHG4InttHitReco::InitRun(), PHG4MicromegasHitReco::InitRun(), PHSiliconTpcTrackMatching::InitRun(), TpcDirectLaserReconstruction::InitRun(), PHG4TpcElectronDrift::InitRun(), HelicalFitter::InitRun(), and TpcSpaceChargeReconstruction::InitRun().
Member Data Documentation
std::map<const std::string, double> PHParameterInterface::m_DefaultDoubleParMap private
Definition at line 53 of file PHParameterInterface.h.
View newest version in sPHENIX GitHub at line 53 of file PHParameterInterface.h
Referenced by InitializeParameters(), set_default_double_param(), and set_double_param().
std::map<const std::string, int> PHParameterInterface::m_DefaultIntParMap private
Definition at line 54 of file PHParameterInterface.h.
View newest version in sPHENIX GitHub at line 54 of file PHParameterInterface.h
Referenced by InitializeParameters(), set_default_int_param(), and set_int_param().
std::map<const std::string, std::string> PHParameterInterface::m_DefaultStringParMap private
Definition at line 55 of file PHParameterInterface.h.
View newest version in sPHENIX GitHub at line 55 of file PHParameterInterface.h
Referenced by InitializeParameters(), set_default_string_param(), and set_string_param().
std::map<const std::string, double> PHParameterInterface::m_DoubleParMap private
Definition at line 49 of file PHParameterInterface.h.
View newest version in sPHENIX GitHub at line 49 of file PHParameterInterface.h
Referenced by set_double_param(), and UpdateParametersWithMacro().
std::map<const std::string, int> PHParameterInterface::m_IntParMap private
Definition at line 50 of file PHParameterInterface.h.
View newest version in sPHENIX GitHub at line 50 of file PHParameterInterface.h
Referenced by set_int_param(), and UpdateParametersWithMacro().
bool PHParameterInterface::m_Locked = false private
Definition at line 48 of file PHParameterInterface.h.
View newest version in sPHENIX GitHub at line 48 of file PHParameterInterface.h
Referenced by PutOnParNode(), SaveToNodeTree(), set_double_param(), set_int_param(), and set_string_param().
PHParameters* PHParameterInterface::m_Params = nullptr private
Definition at line 46 of file PHParameterInterface.h.
View newest version in sPHENIX GitHub at line 46 of file PHParameterInterface.h
Referenced by get_double_param(), get_int_param(), get_string_param(), InitializeParameters(), Print(), PutOnParNode(), SaveToNodeTree(), set_paramname(), UpdateParametersWithMacro(), and ~PHParameterInterface().
std::map<const std::string, std::string> PHParameterInterface::m_StringParMap private
Definition at line 51 of file PHParameterInterface.h.
View newest version in sPHENIX GitHub at line 51 of file PHParameterInterface.h
Referenced by set_string_param(), and UpdateParametersWithMacro().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/database/PHParameter/PHParameterInterface.h
coresoftware/blob/master/offline/database/PHParameter/PHParameterInterface.cc