var namespaceActsFatras =
[
    [ "Casts", "d4/dc8/namespaceActsFatras_1_1Casts.html", "d4/dc8/namespaceActsFatras_1_1Casts" ],
    [ "detail", "db/d63/namespaceActsFatras_1_1detail.html", "db/d63/namespaceActsFatras_1_1detail" ],
    [ "SmearInput", "df/d7a/structActsFatras_1_1SmearInput.html", "df/d7a/structActsFatras_1_1SmearInput" ],
    [ "BoundParametersSmearer", "de/d94/structActsFatras_1_1BoundParametersSmearer.html", "de/d94/structActsFatras_1_1BoundParametersSmearer" ],
    [ "FreeParametersSmearer", "d2/dda/structActsFatras_1_1FreeParametersSmearer.html", "d2/dda/structActsFatras_1_1FreeParametersSmearer" ],
    [ "Barcode", "d2/d46/classActsFatras_1_1Barcode.html", "d2/d46/classActsFatras_1_1Barcode" ],
    [ "Hit", "d9/d47/classActsFatras_1_1Hit.html", "d9/d47/classActsFatras_1_1Hit" ],
    [ "Particle", "db/dfd/classActsFatras_1_1Particle.html", "db/dfd/classActsFatras_1_1Particle" ],
    [ "PhysicsList", "d5/d1e/classActsFatras_1_1PhysicsList.html", "d5/d1e/classActsFatras_1_1PhysicsList" ],
    [ "EveryParticle", "db/df7/structActsFatras_1_1EveryParticle.html", "db/df7/structActsFatras_1_1EveryParticle" ],
    [ "EveryInput", "d5/d7a/structActsFatras_1_1EveryInput.html", "d5/d7a/structActsFatras_1_1EveryInput" ],
    [ "AsInputSelector", "dc/d88/structActsFatras_1_1AsInputSelector.html", "dc/d88/structActsFatras_1_1AsInputSelector" ],
    [ "Process", "db/d42/structActsFatras_1_1Process.html", "db/d42/structActsFatras_1_1Process" ],
    [ "SimulationResult", "d5/d52/structActsFatras_1_1SimulationResult.html", "d5/d52/structActsFatras_1_1SimulationResult" ],
    [ "ParticleSimulator", "d6/d91/structActsFatras_1_1ParticleSimulator.html", "d6/d91/structActsFatras_1_1ParticleSimulator" ],
    [ "Simulator", "de/da0/structActsFatras_1_1Simulator.html", "de/da0/structActsFatras_1_1Simulator" ],
    [ "BetheBloch", "d0/dc9/structActsFatras_1_1BetheBloch.html", "d0/dc9/structActsFatras_1_1BetheBloch" ],
    [ "BetheHeitler", "d5/db5/structActsFatras_1_1BetheHeitler.html", "d5/db5/structActsFatras_1_1BetheHeitler" ],
    [ "NeutralSelector", "d0/d58/structActsFatras_1_1NeutralSelector.html", "d0/d58/structActsFatras_1_1NeutralSelector" ],
    [ "ChargedSelector", "dd/d05/structActsFatras_1_1ChargedSelector.html", "dd/d05/structActsFatras_1_1ChargedSelector" ],
    [ "PositiveSelector", "d2/d28/structActsFatras_1_1PositiveSelector.html", "d2/d28/structActsFatras_1_1PositiveSelector" ],
    [ "NegativeSelector", "d9/da6/structActsFatras_1_1NegativeSelector.html", "d9/da6/structActsFatras_1_1NegativeSelector" ],
    [ "PathLimitX0", "dd/d91/structActsFatras_1_1PathLimitX0.html", "dd/d91/structActsFatras_1_1PathLimitX0" ],
    [ "PathLimitL0", "d6/d32/structActsFatras_1_1PathLimitL0.html", "d6/d32/structActsFatras_1_1PathLimitL0" ],
    [ "PdgSelector", "d8/da7/structActsFatras_1_1PdgSelector.html", "d8/da7/structActsFatras_1_1PdgSelector" ],
    [ "AbsPdgSelector", "db/d13/structActsFatras_1_1AbsPdgSelector.html", "db/d13/structActsFatras_1_1AbsPdgSelector" ],
    [ "PdgExcluder", "d0/d71/structActsFatras_1_1PdgExcluder.html", "d0/d71/structActsFatras_1_1PdgExcluder" ],
    [ "AbsPdgExcluder", "dd/d1d/structActsFatras_1_1AbsPdgExcluder.html", "dd/d1d/structActsFatras_1_1AbsPdgExcluder" ],
    [ "Min", "db/d3c/structActsFatras_1_1Min.html", "db/d3c/structActsFatras_1_1Min" ],
    [ "Max", "dd/dfa/structActsFatras_1_1Max.html", "dd/dfa/structActsFatras_1_1Max" ],
    [ "Range", "de/db3/structActsFatras_1_1Range.html", "de/db3/structActsFatras_1_1Range" ],
    [ "NoSurface", "d8/dc5/structActsFatras_1_1NoSurface.html", "d8/dc5/structActsFatras_1_1NoSurface" ],
    [ "EverySurface", "d7/d8a/structActsFatras_1_1EverySurface.html", "d7/d8a/structActsFatras_1_1EverySurface" ],
    [ "LandauDistribution", "d0/d83/classActsFatras_1_1LandauDistribution.html", "d0/d83/classActsFatras_1_1LandauDistribution" ]
];