Analysis Software: macros/blob/master/calibrations/calo/emc_pi0_tbt/towInfoClustering/srundst_mdc2_clustest.C File Reference
srundst_mdc2_clustest.C File Reference
#include <fun4all/SubsysReco.h>
#include <fun4all/Fun4AllServer.h>
#include <fun4all/Fun4AllInputManager.h>
#include <fun4allraw/Fun4AllPrdfInputManager.h>
#include <fun4all/Fun4AllDstInputManager.h>
#include <fun4all/Fun4AllDstOutputManager.h>
#include <litecaloeval/LiteCaloEval.h>
#include <calib_emc_pi0/CaloCalibEmc_Pi0.h>
#include <caloreco/RawClusterBuilderGraph.h>
#include <caloreco/RawClusterBuilderTemplate.h>
#include <caloreco/RawClusterPositionCorrection.h>
#include <caloreco/RawTowerCalibration.h>
Functions
void srundst_mdc2_clustest (const int nEvents=5, const string &outputFile="secoutput4_raw", const string &inputFile0="ongoing/dstnewoutput5_calo5.root")
Function Documentation
void srundst_mdc2_clustest (const int nEvents = 5, const string & outputFile = "secoutput4_raw", const string & inputFile0 = "ongoing/dstnewoutput5_calo5.root")
Definition at line 30 of file srundst_mdc2_clustest.C.
View newest version in sPHENIX GitHub at line 30 of file srundst_mdc2_clustest.C
References Fun4AllInputManager::AddFile(), LiteCaloEval::CaloType(), LiteCaloEval::CEMC, RawClusterBuilderTemplate::Detector(), Fun4AllServer::End(), in, Fun4AllServer::instance(), RawClusterBuilderTemplate::LoadProfile(), nEvents, Fun4AllServer::PrintTimer(), Fun4AllServer::registerInputManager(), Fun4AllServer::registerSubsystem(), Fun4AllServer::run(), RawClusterBuilderTemplate::set_threshold_energy(), RawClusterBuilderTemplate::set_UseTowerInfo(), RawClusterPositionCorrection::set_UseTowerInfo(), and CaloCalibEmc_Pi0::set_UseTowerInfo().