Analysis Software: PHTrackSelector Class Reference
PHTrackSelector Class Reference
#include <coresoftware/blob/master/offline/packages/trackreco/PHTrackSelector.h>
Public Member Functions
PHTrackSelector (const std::string &name="PHTrackSelector")
Tracking includes.
~PHTrackSelector () override
int InitRun (PHCompositeNode *topNode) override
int process_event (PHCompositeNode *topNode) override
int End (PHCompositeNode *topNode) override
Called at the end of all processing.
void SetMinTPCClusters (int nhits)
void SetMinINTTHits (int nhits)
void SetMinMVTXHits (int nhits)
void SetChi2NDFHits (float max)
void SetIteration (int iter)
void SetTrackMapName (const std::string &map_name)
Public Member Functions inherited from SubsysReco
~SubsysReco () override
virtual int EndRun (const int)
Called at the end of each run.
virtual int Init (PHCompositeNode *)
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
void Print (const std::string &="ALL") const override
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Private Member Functions
int GetNodes (PHCompositeNode *topNode)
Private Attributes
std::string _track_map_name
SvtxTrackMap * _track_map {nullptr}
SvtxTrack * _track {nullptr}
TrkrClusterIterationMapv1 * _iteration_map = nullptr
int _n_iter = 1
unsigned int min_tpc_clusters = 35
unsigned int min_mvtx_hits = 2
unsigned int min_intt_hits = 1
float max_chi2_ndf = 30
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = std::numeric_limits<int>::max() - 10
}
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Detailed Description
Definition at line 25 of file PHTrackSelector.h.
View newest version in sPHENIX GitHub at line 25 of file PHTrackSelector.h
Constructor & Destructor Documentation
PHTrackSelector::PHTrackSelector (const std::string & name = "PHTrackSelector")
Tracking includes.
Definition at line 29 of file PHTrackSelector.cc.
View newest version in sPHENIX GitHub at line 29 of file PHTrackSelector.cc
PHTrackSelector::~PHTrackSelector () override
Definition at line 42 of file PHTrackSelector.cc.
View newest version in sPHENIX GitHub at line 42 of file PHTrackSelector.cc
Member Function Documentation
int PHTrackSelector::End (PHCompositeNode *) override virtual
Called at the end of all processing.
Reimplemented from SubsysReco.
Definition at line 142 of file PHTrackSelector.cc.
View newest version in sPHENIX GitHub at line 142 of file PHTrackSelector.cc
References Fun4AllReturnCodes::EVENT_OK.
int PHTrackSelector::GetNodes (PHCompositeNode * topNode) private
Definition at line 147 of file PHTrackSelector.cc.
View newest version in sPHENIX GitHub at line 147 of file PHTrackSelector.cc
References _iteration_map, _track_map, _track_map_name, Fun4AllReturnCodes::ABORTEVENT, Fun4AllReturnCodes::ABORTRUN, PHCompositeNode::addNode(), Fun4AllReturnCodes::EVENT_OK, PHNodeIterator::findFirst(), and PHWHERE.
Referenced by InitRun().
int PHTrackSelector::InitRun (PHCompositeNode *) override virtual
Called for first event when run number is known. Typically this is where you may want to fetch data from database, because you know the run number.
Reimplemented from SubsysReco.
Definition at line 48 of file PHTrackSelector.cc.
View newest version in sPHENIX GitHub at line 48 of file PHTrackSelector.cc
References Fun4AllReturnCodes::EVENT_OK, and GetNodes().
int PHTrackSelector::process_event (PHCompositeNode *) override virtual
Called for each event. This is where you do the real work.
Reimplemented from SubsysReco.
Definition at line 57 of file PHTrackSelector.cc.
View newest version in sPHENIX GitHub at line 57 of file PHTrackSelector.cc
References _iteration_map, _n_iter, _track, _track_map, TrkrClusterIterationMapv1::addIteration(), SvtxTrackMap::begin(), SvtxTrack::begin_cluster_keys(), SvtxTrackMap::end(), SvtxTrack::end_cluster_keys(), SvtxTrackMap::erase(), Fun4AllReturnCodes::EVENT_OK, SvtxTrack::get_chisq(), SvtxTrack::get_ndf(), TrkrDefs::getTrkrId(), TrkrDefs::inttId, it, max_chi2_ndf, min_intt_hits, min_mvtx_hits, min_tpc_clusters, TrkrDefs::mvtxId, PHWHERE, TrkrClusterIterationMapv1::Reset(), SvtxTrackMap::size(), TrkrDefs::tpcId, and Fun4AllBase::Verbosity().
void PHTrackSelector::SetChi2NDFHits (float max) inline
Definition at line 40 of file PHTrackSelector.h.
View newest version in sPHENIX GitHub at line 40 of file PHTrackSelector.h
References max_chi2_ndf.
void PHTrackSelector::SetIteration (int iter) inline
Definition at line 41 of file PHTrackSelector.h.
View newest version in sPHENIX GitHub at line 41 of file PHTrackSelector.h
References _n_iter.
void PHTrackSelector::SetMinINTTHits (int nhits) inline
Definition at line 38 of file PHTrackSelector.h.
View newest version in sPHENIX GitHub at line 38 of file PHTrackSelector.h
References min_intt_hits.
void PHTrackSelector::SetMinMVTXHits (int nhits) inline
Definition at line 39 of file PHTrackSelector.h.
View newest version in sPHENIX GitHub at line 39 of file PHTrackSelector.h
References min_mvtx_hits.
void PHTrackSelector::SetMinTPCClusters (int nhits) inline
Definition at line 37 of file PHTrackSelector.h.
View newest version in sPHENIX GitHub at line 37 of file PHTrackSelector.h
References min_tpc_clusters.
void PHTrackSelector::SetTrackMapName (const std::string & map_name) inline
Definition at line 43 of file PHTrackSelector.h.
View newest version in sPHENIX GitHub at line 43 of file PHTrackSelector.h
References _track_map_name.
Member Data Documentation
TrkrClusterIterationMapv1* PHTrackSelector::_iteration_map = nullptr private
Definition at line 52 of file PHTrackSelector.h.
View newest version in sPHENIX GitHub at line 52 of file PHTrackSelector.h
Referenced by GetNodes(), and process_event().
int PHTrackSelector::_n_iter = 1 private
Definition at line 54 of file PHTrackSelector.h.
View newest version in sPHENIX GitHub at line 54 of file PHTrackSelector.h
Referenced by process_event(), and SetIteration().
SvtxTrack* PHTrackSelector::_track {nullptr} private
Definition at line 51 of file PHTrackSelector.h.
View newest version in sPHENIX GitHub at line 51 of file PHTrackSelector.h
Referenced by process_event().
SvtxTrackMap* PHTrackSelector::_track_map {nullptr} private
Definition at line 50 of file PHTrackSelector.h.
View newest version in sPHENIX GitHub at line 50 of file PHTrackSelector.h
Referenced by GetNodes(), and process_event().
std::string PHTrackSelector::_track_map_name private
Definition at line 49 of file PHTrackSelector.h.
View newest version in sPHENIX GitHub at line 49 of file PHTrackSelector.h
Referenced by GetNodes(), and SetTrackMapName().
float PHTrackSelector::max_chi2_ndf = 30 private
Definition at line 58 of file PHTrackSelector.h.
View newest version in sPHENIX GitHub at line 58 of file PHTrackSelector.h
Referenced by process_event(), and SetChi2NDFHits().
unsigned int PHTrackSelector::min_intt_hits = 1 private
Definition at line 57 of file PHTrackSelector.h.
View newest version in sPHENIX GitHub at line 57 of file PHTrackSelector.h
Referenced by process_event(), and SetMinINTTHits().
unsigned int PHTrackSelector::min_mvtx_hits = 2 private
Definition at line 56 of file PHTrackSelector.h.
View newest version in sPHENIX GitHub at line 56 of file PHTrackSelector.h
Referenced by process_event(), and SetMinMVTXHits().
unsigned int PHTrackSelector::min_tpc_clusters = 35 private
Definition at line 55 of file PHTrackSelector.h.
View newest version in sPHENIX GitHub at line 55 of file PHTrackSelector.h
Referenced by process_event(), and SetMinTPCClusters().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/trackreco/PHTrackSelector.h
coresoftware/blob/master/offline/packages/trackreco/PHTrackSelector.cc