Analysis Software: Fun4AllBase Class Reference
Fun4AllBase Class Reference
#include <coresoftware/blob/master/offline/framework/fun4all/Fun4AllBase.h>
Public Types
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = std::numeric_limits<int>::max() - 10
}
Public Member Functions
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Print (const std::string &what="ALL") const
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Protected Member Functions
Fun4AllBase (const std::string &name="NONAME")
Private Attributes
std::string m_ThisName
int m_Verbosity = VERBOSITY_QUIET
The verbosity level. 0 means not verbose at all.
Detailed Description
Base class for all Fun4All Classes
It implements the Name, the Verbosity and the print method
Definition at line 14 of file Fun4AllBase.h.
View newest version in sPHENIX GitHub at line 14 of file Fun4AllBase.h
Member Enumeration Documentation
enum Fun4AllBase::enu_Verbosity
Enumerator:
VERBOSITY_QUIET
Quiet mode. Only output critical messages. Intended for batch production mode.
VERBOSITY_SOME
Output some useful messages during manual command line running.
VERBOSITY_MORE
Output more messages.
VERBOSITY_EVEN_MORE
Output even more messages.
VERBOSITY_A_LOT
Output a lot of messages.
VERBOSITY_MAX
Show all messages. Useful for step-by-step debugging.
Definition at line 33 of file Fun4AllBase.h.
View newest version in sPHENIX GitHub at line 33 of file Fun4AllBase.h
Constructor & Destructor Documentation
Fun4AllBase::~Fun4AllBase () virtual
dtor. Does nothing as this is a base class only.
Definition at line 39 of file Fun4AllBase.cc.
View newest version in sPHENIX GitHub at line 39 of file Fun4AllBase.cc
References m_ThisName, m_Verbosity, and VERBOSITY_MORE.
Fun4AllBase::Fun4AllBase (const std::string & name = "NONAME") protected
ctor.
Definition at line 9 of file Fun4AllBase.cc.
View newest version in sPHENIX GitHub at line 9 of file Fun4AllBase.cc
References PHWHERE.
Member Function Documentation
virtual const std::string Fun4AllBase::Name () const inline virtual
Returns the name of this module.
Definition at line 23 of file Fun4AllBase.h.
View newest version in sPHENIX GitHub at line 23 of file Fun4AllBase.h
References m_ThisName.
Referenced by Fun4AllPrdfInputPoolManager::AddBeamClock(), Fun4AllInputManager::AddFile(), Fun4AllInputManager::AddListFile(), OnCalServer::BeginRun(), PHG4Prototype2HcalCellReco::CheckEnergy(), PHG4HcalCellReco::CheckEnergy(), PHG4BlockCellReco::CheckEnergy(), PHG4CylinderCellReco::CheckEnergy(), PHG4FullProjSpacalCellReco::CheckEnergy(), OnCalServer::ClosestGoodRun(), ClusterIso::ClusterIso(), BeamLineMagnetDetector::ConstructMe(), OnCalServer::CreateCalibration(), OnCalServer::CreateCalibrationUpdateStatus(), DecayFinder::createDecayNode(), RawTowerDeadTowerInterp::CreateNodes(), RawTowerBuilder::CreateNodes(), RawTowerCombiner::CreateNodes(), RawTowerCalibration::CreateNodes(), RawTowerDigitizer::CreateNodes(), CaloCalibration::CreateNodeTree(), CaloTowerCalib::CreateNodeTree(), CaloTowerStatus::CreateNodeTree(), TowerInfoDeadHotMask::CreateNodeTree(), CaloTemplateFit::CreateNodeTree(), caloTowerEmbed::CreateNodeTree(), RawClusterDeadHotMask::CreateNodeTree(), RawClusterBuilderTemplate::Detector(), VtxTest::doNodePointers(), TruthConversionEval::doNodePointers(), Fun4AllHistoManager::dumpHistos(), OnCalServer::End(), CaloEvaluator::End(), EventEvaluator::End(), JetHepMCLoader::End(), KFParticle_sPHENIX::End(), EMCalAna::eval_trk_proj(), Fun4AllDstInputManager::fileclose(), Fun4AllPrdfInputManager::fileclose(), Fun4AllOscarInputManager::fileclose(), SinglePrdfInput::fileclose(), SingleStreamingInput::fileclose(), Fun4AllHepMCInputManager::fileclose(), Fun4AllSingleDstPileupInputManager::fileclose(), Fun4AllDstPileupInputManager::fileclose(), Fun4AllDstInputManager::fileopen(), Fun4AllPrdfInputManager::fileopen(), Fun4AllRunNodeInputManager::fileopen(), Fun4AllOscarInputManager::fileopen(), SinglePrdfInput::fileopen(), SingleStreamingInput::fileopen(), Fun4AllHepMCInputManager::fileopen(), Fun4AllSingleDstPileupInputManager::fileopen(), Fun4AllDstPileupInputManager::fileopen(), CaloEvaluator::fillOutputNtuples(), OnCalServer::FixMissingCalibration(), Fun4All_Ana(), Fun4All_EICAnalysis_DIS(), Fun4All_EICAnalysis_DISReco(), Fun4All_EICAnalysis_DVCS(), Fun4All_EICAnalysis_Exclusive(), Fun4All_EICAnalysis_Leptoquarks(), Fun4All_EICAnalysis_Quarkonia(), Fun4All_EICAnalysis_TrackEval(), Fun4All_G4_EICDetector_LQ(), Fun4All_G4_EICDetector_LQ_reference(), Fun4All_G4_EICDetector_RICH(), Fun4All_G4_fsPHENIX_FastSim(), Fun4All_G4_fsPHENIX_pi0(), Fun4All_G4_sPHENIX(), Fun4All_G4_sPHENIX_AnaGenFit(), Fun4All_G4_sPHENIX_photonjet(), Fun4All_G4_sPHENIX_photons(), Fun4All_G4_sPHENIX_truthphotonjet(), Fun4All_Generator_Display(), Fun4All_HCALAnalysis(), Fun4All_single_particle(), QAG4SimulationUpsilon::get_histo_prefix(), QAG4SimulationVertex::get_histo_prefix(), QAG4SimulationDistortions::get_histo_prefix(), QAG4SimulationIntt::get_histo_prefix(), QAG4SimulationMvtx::get_histo_prefix(), QAG4SimulationKFParticle::get_histo_prefix(), QAG4SimulationMicromegas::get_histo_prefix(), QAG4SimulationTpc::get_histo_prefix(), QAG4SimulationTracking::get_histo_prefix(), QAG4SimulationTruthDecay::get_histo_prefix(), truthDecayTester::get_histo_prefix(), SynRadAna::get_histo_prefix(), JetBkgdSub::GetCentInfo(), JetHepMCLoader::getHistoManager(), TpcClusterQA::getHistoPrefix(), Fun4AllSyncManager::getInputManager(), OnCalServer::GetLastGoodRunTS(), HijingShowerSize::HijingShowerSize(), OnCal::identify(), Fun4AllServer::identify(), HepMCNodeReader::Init(), G4VtxNtuple::Init(), HCalCalibTree::Init(), G4EdepNtuple::Init(), CaloAna::Init(), PHG4DetectorGroupSubsystem::Init(), PHG4DetectorSubsystem::Init(), CaloWaveFormSim::Init(), G4TowerNtuple::Init(), G4CellNtuple::Init(), G4HitNtuple::Init(), G4SnglNtuple::Init(), EdepNtuple::Init(), CaloValid::Init(), TowerTiming::Init(), HijingCountNtuple::Init(), HitCountNtuple::Init(), ShowerSize::Init(), TimingNtuple::Init(), pi0EtaByEta::Init(), PHG4SectorSubsystem::Init(), HijingShowerSize::Init(), SigmaTimingNtuple::Init(), PHG4EnvelopeSubsystem::Init(), DecayFinder::Init(), PHG4CEmcTestBeamSubsystem::Init(), AntiTrigger::Init(), G4Example01Subsystem::Init(), PHG4HcalPrototypeSubsystem::Init(), PHActsSiliconSeeding::Init(), Fun4AllServer::InitAll(), PHG4DetectorGroupSubsystem::InitializeParameters(), PHG4ParticleGeneratorD0::InitRun(), RawTowerDeadTowerInterp::InitRun(), CaloCalibration::InitRun(), PHG4HcalCellReco::InitRun(), PHG4BlockCellReco::InitRun(), PHG4CylinderCellReco::InitRun(), CaloTowerCalib::InitRun(), CaloTowerStatus::InitRun(), RawTowerCalibration::InitRun(), PHG4DetectorSubsystem::InitRun(), PHG4DetectorGroupSubsystem::InitRun(), CaloTemplateFit::InitRun(), PHG4TpcDirectLaser::InitRun(), PHG4FullProjSpacalCellReco::InitRun(), DeadHotMapLoader::InitRun(), RawTowerDigitizer::InitRun(), PHG4InttDeadMapLoader::InitRun(), PHG4InttHitReco::InitRun(), PHG4HcalSubsystem::InitRun(), EMCalLikelihood::InitRun(), PHG4TpcElectronDrift::InitRun(), PHG4Reco::InitRun(), LiteCaloEval::InitRun(), PHActsTrkFitter::InitRun(), PHG4EPDSubsystem::InitRunSubsystem(), PHG4OHCalSubsystem::InitRunSubsystem(), PHG4OuterHcalSubsystem::InitRunSubsystem(), PHG4SpacalPrototype4Subsystem::InitRunSubsystem(), PHG4InnerHcalSubsystem::InitRunSubsystem(), PHG4ZDCSubsystem::InitRunSubsystem(), PHG4IHCalSubsystem::InitRunSubsystem(), PHG4TpcSubsystem::InitRunSubsystem(), PHG4Prototype2InnerHcalSubsystem::InitRunSubsystem(), PHG4Prototype3InnerHcalSubsystem::InitRunSubsystem(), PHG4Prototype2OuterHcalSubsystem::InitRunSubsystem(), BeamLineMagnetSubsystem::InitRunSubsystem(), PHG4BeamlineMagnetSubsystem::InitRunSubsystem(), PHG4SpacalPrototypeSubsystem::InitRunSubsystem(), PHG4BlockSubsystem::InitRunSubsystem(), PHG4ConeSubsystem::InitRunSubsystem(), PHG4CylinderSubsystem::InitRunSubsystem(), PHG4EICMvtxSubsystem::InitRunSubsystem(), PHG4MvtxSubsystem::InitRunSubsystem(), PHG4InttSubsystem::InitRunSubsystem(), PHG4TpcEndCapSubsystem::InitRunSubsystem(), G4Example02Subsystem::InitRunSubsystem(), PHG4GDMLSubsystem::InitRunSubsystem(), PHG4MicromegasSubsystem::InitRunSubsystem(), G4Example03Subsystem::InitRunSubsystem(), PHG4SpacalSubsystem::InitRunSubsystem(), PHG4BbcSubsystem::InitRunSubsystem(), PHG4PSTOFSubsystem::InitRunSubsystem(), Jin_BJet(), Fun4AllNoSyncDstInputManager::NoRunTTree(), VtxTest::numUnique(), TruthConversionEval::numUnique(), Fun4AllServer::outfileclose(), DecayFinder::parseDecayDescriptor(), KFParticle_sPHENIX::parseDecayDescriptor(), AntiTrigger::parseParticleList(), PHG4CEmcTestBeamSubsystem::PHG4CEmcTestBeamSubsystem(), PHG4DetectorGroupSubsystem::PHG4DetectorGroupSubsystem(), PHG4DetectorSubsystem::PHG4DetectorSubsystem(), PHG4EICMvtxSubsystem::PHG4EICMvtxSubsystem(), PHG4HcalPrototypeSubsystem::PHG4HcalPrototypeSubsystem(), PHG4HcalSubsystem::PHG4HcalSubsystem(), PHG4InttDigitizer::PHG4InttDigitizer(), PHG4InttSubsystem::PHG4InttSubsystem(), PHG4MvtxDigitizer::PHG4MvtxDigitizer(), PHG4MvtxSubsystem::PHG4MvtxSubsystem(), PHG4PSTOFSubsystem::PHG4PSTOFSubsystem(), PHG4TpcDigitizer::PHG4TpcDigitizer(), Fun4AllHistoManager::Print(), Fun4AllOutputManager::Print(), Fun4AllEventOutputManager::Print(), Fun4AllHepMCOutputManager::Print(), Fun4AllDstInputManager::Print(), Print(), Fun4AllDstOutputManager::Print(), Fun4AllInputManager::Print(), OnCalServer::Print(), Fun4AllHepMCInputManager::Print(), Fun4AllSingleDstPileupInputManager::Print(), Fun4AllDstPileupInputManager::Print(), PHG4InnerHcalSubsystem::Print(), Fun4AllSyncManager::Print(), PHG4IHCalSubsystem::Print(), PHG4Prototype3InnerHcalSubsystem::Print(), PHG4Prototype2InnerHcalSubsystem::Print(), PHG4Prototype2OuterHcalSubsystem::Print(), PHG4BeamlineMagnetSubsystem::Print(), BeamLineMagnetSubsystem::Print(), PHG4TpcSubsystem::Print(), PHG4CylinderSubsystem::Print(), PHG4SpacalPrototype4Subsystem::Print(), PHG4SpacalPrototypeSubsystem::Print(), PHG4GDMLSubsystem::Print(), PHG4BbcSubsystem::Print(), HcalRawTowerBuilder::Print(), AntiTrigger::printInfo(), DecayFinder::printInfo(), CaloEvaluator::printInputInfo(), OnCal::process_event(), TowerInfoDeadHotMask::process_event(), RawClusterDeadHotMask::process_event(), RawClusterBuilderTemplate::process_event(), PHG4ParticleGeneratorBase::process_event(), RawTowerDeadTowerInterp::process_event(), RawClusterPositionCorrection::process_event(), PHG4Prototype2HcalCellReco::process_event(), CaloCalibration::process_event(), HcalRawTowerBuilder::process_event(), PHG4HcalCellReco::process_event(), PHG4BlockCellReco::process_event(), RawTowerCalibration::process_event(), PHG4CylinderCellReco::process_event(), CaloTemplateFit::process_event(), ClusterIso::process_event(), RawTowerDigitizer::process_event(), PHG4FullProjSpacalCellReco::process_event(), HFMLTriggerHepMCTrigger::process_event(), OnCalServer::process_event(), TruthConversionEval::process_event(), RawTowerCombiner::process_event(), CaloAna::process_towers(), CaloValid::process_towers(), pi0EtaByEta::process_towers(), Fun4AllPrdfInputManager::PushBackEvents(), Fun4AllDstInputManager::PushBackEvents(), Fun4AllHepMCInputManager::PushBackEvents(), Fun4AllSingleDstPileupInputManager::PushBackEvents(), Fun4AllDstPileupInputManager::PushBackEvents(), Fun4AllHepMCPileupInputManager::PushBackEvents(), Fun4AllDstInputManager::ReadNextEventSyncObject(), OnCalServer::registerHisto(), Fun4AllServer::registerHistoManager(), Fun4AllSyncManager::registerInputManager(), Fun4AllServer::registerOutputManager(), Fun4AllStreamingInputManager::registerStreamingInput(), Fun4AllInputManager::registerSubsystem(), Fun4AllServer::registerSubsystem(), Fun4AllServer::registerSyncManager(), Fun4AllInputManager::RejectEvent(), Fun4AllInputManager::ResetFileList(), Fun4AllDstInputManager::run(), Fun4AllRunNodeInputManager::run(), Fun4AllHepMCPileupInputManager::run(), Fun4AllPrdfInputManager::run(), Fun4AllSyncManager::run(), Fun4AllOscarInputManager::run(), Fun4AllHepMCInputManager::run(), Fun4AllSingleDstPileupInputManager::run(), Run_BBCStudy(), Fun4AllDstPileupInputManager::runOne(), PHG4ParticleGeneratorBase::set_seed(), Fun4AllDstInputManager::setBranches(), Fun4AllSingleDstPileupInputManager::setBranches(), Fun4AllDstPileupInputManager::setBranches(), PHG4Subsystem::SetMotherSubsystem(), PHG4HcalSubsystem::SetTiltViaNcross(), SigmaTimingNtuple::SigmaTimingNtuple(), RawTowerDigitizer::simple_photon_digitization(), RawTowerDigitizer::sipm_photon_digitization(), OnCalServer::SyncCalibTimeStampsToOnCal(), Fun4AllDstInputManager::SyncIt(), Fun4AllPrdfInputManager::SyncIt(), Fun4AllPrdfInputPoolManager::SyncIt(), Fun4AllStreamingInputManager::SyncIt(), EMCalLikelihood::UpdateEnergyDepositionLikelihood(), Fun4AllDstOutputManager::Write(), Fun4AllFileOutStream::WriteEventOut(), Fun4AllRolloverFileOutStream::WriteEventOut(), and Fun4AllDstOutputManager::WriteNode().
virtual void Fun4AllBase::Name (const std::string & name) inline virtual
Sets the name of this module.
Definition at line 26 of file Fun4AllBase.h.
View newest version in sPHENIX GitHub at line 26 of file Fun4AllBase.h
References m_ThisName, and perf_headwind::name.
void Fun4AllBase::Print (const std::string & what = "ALL") const virtual
Print out some info about this module.
Parameters
what can be used to specify what to print exactly.
Reimplemented in EMJetVal, dNdEtaINTT, JetValidation, HcalRawTowerBuilder, PHG4HcalSubsystem, cemcReco, JetKinematicCheck, FullJetFinder, analysis, jetrtrack, JetNconstituents, towerid, pi0Efficiency, PHG4Reco, caloTreeGen, readDigitalCurrents, PHG4PSTOFSubsystem, PHG4BbcSubsystem, JetSeedCount, hcal_towerid, TruthJetTagging, SubsysReco, pythiaEMCalAna, caloTreeGen, PHG4SpacalSubsystem, pi0ClusterAna, quickHIJING, singlePhotonClusterAna, Fun4AllServer, PHG4MicromegasSubsystem, hijbkg_upc, isoCluster, G4Example03Subsystem, HCalJetPhiShift, JetUnderlyingEvent, jetHistogrammer, UEvsEtaCentrality, TracksInJets, Pi0MassAnalysis, G4Example02Subsystem, G4Example01Subsystem, SynRadAna, JetMultSub, mbdAnalysis, mbdAnalysis, PHTruthSiliconAssociation, PHG4InttSubsystem, PHG4TpcEndCapSubsystem, PHG4GDMLSubsystem, PHActsTrackPropagator, PHG4SpacalPrototypeSubsystem, TrackClusterEvaluator, PHG4SpacalPrototype4Subsystem, ParticleFlowReco, PHG4CylinderSubsystem, Fun4AllStreamingInputManager, BeamLineMagnetSubsystem, PHG4BeamlineMagnetSubsystem, PHG4TpcSubsystem, PHG4Prototype2InnerHcalSubsystem, PHG4Prototype2OuterHcalSubsystem, PHG4Prototype3InnerHcalSubsystem, Fun4AllSyncManager, PHG4InnerHcalSubsystem, PHG4IHCalSubsystem, PHG4OuterHcalSubsystem, PHG4OHCalSubsystem, Fun4AllDstPileupInputManager, Fun4AllSingleDstPileupInputManager, Fun4AllHepMCInputManager, PHG4ParticleGeneratorBase, OnCalServer, Fun4AllInputManager, SingleStreamingInput, Fun4AllPrdfInputPoolManager, Fun4AllDstOutputManager, Fun4AllOscarInputManager, SingleMvtxPoolInput, g4hitshift, Fun4AllDstInputManager, SingleInttPoolInput, Emcal_Tower_Masking, FlagHandler, Fun4AllHepMCOutputManager, CDBInterface, Fun4AllPrdfInputManager, SingleGl1PoolInput, SingleMicromegasPoolInput, SingleTpcPoolInput, PHG4IonGun, PHG4ParticleGenerator, HepMCFlowAfterBurner, Fun4AllOutputManager, Fun4AllEventOutputManager, Prototype2RawTowerBuilder, and Fun4AllHistoManager.
Definition at line 48 of file Fun4AllBase.cc.
View newest version in sPHENIX GitHub at line 48 of file Fun4AllBase.cc
References Name().
virtual void Fun4AllBase::Verbosity (const int ival) inline virtual
Sets the verbosity of this module (0 by default=quiet).
Reimplemented in PHG4TrackFastSim, MvtxUnpackPRDF, FieldMapReadBack, and Fun4AllEventOutputManager.
Definition at line 59 of file Fun4AllBase.h.
View newest version in sPHENIX GitHub at line 59 of file Fun4AllBase.h
References m_Verbosity.
Referenced by ACTSGEOM::ActsGeomInit(), alignment(), BeamLineDefineMagnets(), build_truthreco_tables(), CaloTrigger_Sim(), CEmc_2DProjectiveSpacal(), CEMC_Cells(), CEMC_Clusters(), CEMC_Eval(), CEMC_QA(), CEMC_Towers(), Centrality(), clus_dst_simple_superfastcalib(), ConfigureInput(), ConstructGeometry(), convert_seeds(), doFitAndCalibUpdate(), dst_simple_towerslope_runmacro(), EEMC_Eval(), EEMC_Towers(), FEMC_Eval(), FEMC_Towers(), FHCAL_Eval(), FHCAL_Towers(), Filter_Conversion_Electrons(), Fun(), Fun4All(), Fun4All_Ana(), Fun4All_Analysis(), Fun4All_AnaTutorial_DSTReadBack(), Fun4All_AnaTutorial_sPHENIX(), Fun4All_AnaTutorial_sPHENIX_Jets(), Fun4All_BHG(), Fun4All_Calo(), Fun4All_CaloProduction(), Fun4All_CaloProduction_PreQM23(), Fun4All_CentralityValidation(), Fun4All_Combiner(), Fun4All_Condor(), Fun4All_EICAnalysis_DIS(), Fun4All_EICAnalysis_DISReco(), Fun4All_EICAnalysis_DVCS(), Fun4All_EICAnalysis_Exclusive(), Fun4All_EICAnalysis_Leptoquarks(), Fun4All_EICAnalysis_Quarkonia(), Fun4All_EICAnalysis_TrackEval(), Fun4All_EMCal(), Fun4All_EMCal_Hist(), Fun4All_EMCal_sp(), Fun4All_EMCalLikelihood(), Fun4All_EMJetVal(), Fun4All_ExportGeom(), Fun4All_G4_block(), Fun4All_G4_Calo(), Fun4All_G4_Calos(), Fun4All_G4_Clusters(), Fun4All_G4_Cylinder(), Fun4All_G4_EICDetector_AnaTutorial(), Fun4All_G4_EICDetector_LQ(), Fun4All_G4_EICDetector_LQ_analysis(), Fun4All_G4_EICDetector_LQ_analysis_nf(), Fun4All_G4_EICDetector_LQ_reference(), Fun4All_G4_EICDetector_RICH(), Fun4All_G4_EICIR(), Fun4All_G4_fsPHENIX_FastSim(), Fun4All_G4_fsPHENIX_pi0(), Fun4All_G4_LeadBrick(), Fun4All_G4_Momentum(), Fun4All_G4_Momentum_Projection(), Fun4All_G4_Momentum_Projection_Calorimeters(), Fun4All_G4_Momentum_Projection_Detectors(), Fun4All_G4_Pi0_Tbt(), Fun4All_G4_Prototype3(), Fun4All_G4_Prototype4(), Fun4All_G4_SlopeCal(), Fun4All_G4_sPHENIX(), Fun4All_G4_sPHENIX_AnaGenFit(), Fun4All_G4_sPHENIX_ForTrackCutStudy(), Fun4All_G4_sPHENIX_ForTrackCutStudy_EmbedScanOff(), Fun4All_G4_sPHENIX_ForTrackCutStudy_EmbedScanOn(), Fun4All_G4_sPHENIX_ForTrackCutStudy_WithPileup_EmbedScanOff(), Fun4All_G4_sPHENIX_ForTrackCutStudy_WithPileup_EmbedScanOn(), Fun4All_G4_sPHENIX_photonjet(), Fun4All_G4_sPHENIX_photons(), Fun4All_G4_sPHENIX_truthphotonjet(), Fun4All_G4_TPC(), Fun4All_G4_W(), Fun4All_G4_Write_Dst(), Fun4All_Generator_Display(), Fun4All_GeoExtract(), Fun4All_HCALAnalysis(), Fun4All_HCalCalib(), Fun4All_HCalCalib_sim(), Fun4All_HCalJetPhiShift(), Fun4All_hijbkg(), Fun4All_ImportGeom(), Fun4All_Intt_Combiner(), Fun4All_IsolatedTrackAnalysis(), Fun4All_JetBkgd(), Fun4All_JetBkgd_Embed(), Fun4All_JetNconst(), Fun4All_JetRhoMedian(), Fun4All_JetSeedCount(), Fun4All_JetSub(), Fun4All_JetVal(), Fun4All_LEDTowerBuilder(), Fun4All_MCEventGen(), Fun4All_MDCTreeMaker(), Fun4All_Mvtx_Combiner(), Fun4All_MySimpleReco(), Fun4All_Pi0Gen_sPHENIX(), Fun4All_pi0tbt_SIMPLE_EMBED(), Fun4All_PRDF(), Fun4All_Pythia6(), Fun4All_pythiaEMCalAna(), Fun4All_quickHijing_Prod(), Fun4All_ReadDST_TPCML(), Fun4All_RhoFluct(), Fun4All_RICHReco(), Fun4All_RTrack(), Fun4All_RunEMCReco(), Fun4All_RunNewTruthMatcher(), Fun4All_RunPi0ClusterAna(), Fun4All_RunPi0Efficiency(), Fun4All_RunSinglePhotonClusterAna(), Fun4All_single_particle(), Fun4All_SingleMvtx(), Fun4All_SinglePhotonGen_sPHENIX(), Fun4All_SinglePi0Gen_sPHENIX(), Fun4All_Stream_Combiner(), Fun4All_Templates(), Fun4All_TestBeam(), Fun4All_TestBeam_Ana(), Fun4All_TestBeam_ExampleAnalysisModule(), Fun4All_TestBeam_HCAL_SampleFrac(), Fun4All_TestBeam_HCAL_ShowerCalib(), Fun4All_TestBeam_HCAL_TowerCalib(), Fun4All_TestBeam_ShowerCalib(), Fun4All_TestBeam_TPC(), Fun4All_testEtIso_Hijing(), Fun4All_testEtIso_Pythia(), Fun4All_testingGround(), Fun4All_Tpc_Combiner(), Fun4All_TPC_EventDisplayPrep(), Fun4All_TPC_UnpackPRDF(), Fun4All_TPC_UnpackPRDF_Batch(), Fun4All_TrkrClusteringSeeding(), Fun4All_TrkrHitSet_Unpacker(), Fun4All_UE_v2_Psi2(), Fun4All_Year1(), Fun4AllPythia(), G4_HIJetReco(), G4DSTreader(), G4DSTreader_EICDetector(), G4DSTreader_EICIR(), G4DSTreader_fsPHENIX(), Global_FastSim(), Global_Reco(), HCALInner_Cells(), HCALInner_Clusters(), HCALInner_Eval(), HCALInner_QA(), HCALInner_Towers(), HCALOuter_Cells(), HCALOuter_Clusters(), HCALOuter_Eval(), HCALOuter_QA(), HCALOuter_Towers(), HIJetReco(), InputManagers(), InputRegister(), Intt(), Intt_Cells(), Intt_Clustering(), Intt_QA(), Jet_Eval(), Jet_FwdEval(), Jet_FwdReco(), Jet_QA(), Jet_Reco(), Jin_BJet(), KFParticle_D0_Reco(), KFParticle_Lambdac_Reco(), KFParticle_QA(), HFjets::KFParticle_Set_Reco(), KFParticle_Upsilon_Reco(), Mbd_Reco(), Micromegas_Cells(), Micromegas_QA(), Mvtx(), Mvtx_Cells(), Mvtx_Clustering(), Mvtx_QA(), myDemoReco(), myHeavyFlavorReco(), ParticleFlow(), PHGeom_DSTInspection(), QA_G4CaloTracking(), ReadFieldMap(), run(), Run_BbcCheck(), Run_BBCStudy(), run_calo_fromMDC2Hits_towslope_Fun4All_G4_Calo(), run_macro(), run_macro_2(), runall(), RunBDiJetModule(), RunBJetModule(), rundata(), rundst_spiNo(), RunGenFitTrackProp(), runmb(), runpairs(), spiNo2(), Svtx(), Svtx_Cells(), Svtx_Eval(), TestCDBSubsysReco(), TopoClusterReco(), TPC_Cells(), TPC_Clustering(), TPC_LaserClustering(), TPC_QA(), Tracking_Eval(), Tracking_QA(), Tracking_Reco_CommissioningTrackSeed(), Tracking_Reco_TrackFit(), Tracking_Reco_TrackSeed(), Tracking_Reco_TrackSeed_pass1(), Fun4AllEventOutputManager::Verbosity(), Verbosity(), vertexing(), wholeIter_Pi0EtaByEta(), Wrapper(), ZDC_Eval(), and ZDC_Towers().
virtual void Fun4AllBase::Verbosity (enu_Verbosity ival) inline virtual
Sets the verbosity of this module (0 by default=quiet).
Definition at line 62 of file Fun4AllBase.h.
View newest version in sPHENIX GitHub at line 62 of file Fun4AllBase.h
References m_Verbosity.
virtual int Fun4AllBase::Verbosity () const inline virtual
Gets the verbosity of this module.
Definition at line 65 of file Fun4AllBase.h.
View newest version in sPHENIX GitHub at line 65 of file Fun4AllBase.h
References m_Verbosity.
Referenced by MakeActsGeometry::addActsTpcSurfaces(), MvtxPrototype2Align::AddAlignmentPar(), Fun4AllPrdfInputPoolManager::AddBeamClock(), Fun4AllInputManager::AddFile(), Fun4AllStreamingInputManager::AddGl1RawHit(), Fun4AllStreamingInputManager::AddInttRawHit(), PHCosmicTrackMerger::addKeys(), Fun4AllInputManager::AddListFile(), Fun4AllStreamingInputManager::AddMicromegasRawHit(), Fun4AllStreamingInputManager::AddMvtxFeeId(), Fun4AllStreamingInputManager::AddMvtxL1TrgBco(), Fun4AllStreamingInputManager::AddMvtxRawHit(), Fun4AllPrdfInputPoolManager::AddPacket(), EventCombiner::AddPrdfInputNodeName(), Fun4AllStreamingInputManager::AddTpcRawHit(), PHActsTrackPropagator::addTrackState(), MakeMilleFiles::addTrackToMilleFile(), SingleZdcInput::adjust_eventnumber_offset(), SinglePrdfInput::adjust_eventnumber_offset(), PHG4TpcDirectLaser::AimToPatternStep(), PHG4TpcDirectLaser::AimToPatternStep_File(), PHG4TpcDirectLaser::AimToThetaPhi(), PHTruthClustering::all_truth_clusters(), PHG4TpcDirectLaser::AppendLaserTrack(), PHG4Reco::ApplyDisplayAction(), PHTruthVertexing::assignTracksVertices(), Fun4AllServer::BeginRun(), Fun4AllServer::BeginRunSubsystem(), Fun4AllDstInputManager::BranchSelect(), Fun4AllDstPileupInputManager::BranchSelect(), Fun4AllSingleDstPileupInputManager::BranchSelect(), PHG4DSTReader::build_tree(), MakeActsGeometry::buildActsSurfaces(), MakeActsGeometry::buildAllGeometry(), PHTruthSiliconAssociation::buildTrackSeed(), PHTruthTrackSeeding::buildTrackSeed(), TpcSpaceChargeMatrixInversion::calculate_distortions(), PHTpcCentralMembraneMatcher::CalculateCenters(), KshortReconstruction::calculateDca(), PHG4MvtxDigitizer::CalculateMvtxLadderCellADCScale(), InttVertexFinder::calculateZvertex(), CaloTowerCalib::CaloTowerCalib(), CaloTowerStatus::CaloTowerStatus(), OnCalServer::check_calibrator_in_statustable(), PHSiliconTpcTrackMatching::checkCrossingMatches(), PHSimpleVertexFinder::checkDCAs(), PHG4Prototype2HcalCellReco::CheckEnergy(), PHG4HcalCellReco::CheckEnergy(), PHG4BlockCellReco::CheckEnergy(), PHG4CylinderCellReco::CheckEnergy(), PHG4FullProjSpacalCellReco::CheckEnergy(), EventNumberCheck::CheckFem(), DecayFinder::checkIfCorrectGeant4Particle(), DecayFinder::checkIfCorrectHepMCParticle(), SingleGl1PoolInput::CheckPoolDepth(), SingleTpcPoolInput::CheckPoolDepth(), SingleInttPoolInput::CheckPoolDepth(), SingleMvtxPoolInput::CheckPoolDepth(), SingleStreamingInput::CheckPoolDepth(), PHTpcResiduals::checkTrack(), SecondaryVertexFinder::circle_circle_intersection(), OnCalServer::ClosestGoodRun(), PHG4InttHitReco::cluster_truthhits(), PHG4MvtxHitReco::cluster_truthhits(), TPCFEETestRecov1::Clustering(), TpcPrototypeUnpacker::Clustering(), ClusterIso::ClusterIso(), InttClusterizer::ClusterLadderCells(), InttClusterizer::ClusterLadderCellsRaw(), MvtxPrototype2Clusterizer::ClusterMvtx(), MvtxClusterizer::ClusterMvtx(), MvtxClusterizer::ClusterMvtxRaw(), PHCosmicSeeder::combineSeeds(), DecayFinder::compareDecays(), Fun4AllOscarInputManager::ConvertFromOscar(), Fun4AllHepMCInputManager::ConvertFromOscar(), OnCalServer::CopySnglTableNewBankId(), Fun4AllServer::CountOutNodesRecursive(), PHActsVertexFitter::createActsSvtxVertex(), Fun4AllPrdfInputPoolManager::CreateBclkOffsets(), PHActsInitialVertexFinder::createCentroidMap(), CaloGeomMapping::CreateGeomNode(), PHCASeeding::CreateLinks(), SubtractTowersCS::CreateNode(), RetowerCEMC::CreateNode(), SubtractTowers::CreateNode(), CopyAndSubtractJets::CreateNode(), JetMultSub::CreateNode(), CentralityReco::CreateNodes(), MinimumBiasClassifier::CreateNodes(), RawTowerDeadTowerInterp::CreateNodes(), PHInitVertexing::CreateNodes(), PHTrackSetMerging::CreateNodes(), RawTowerBuilder::CreateNodes(), PHTrackSeeding::CreateNodes(), PHTruthTrackSeeding::CreateNodes(), PHRaveVertexing::CreateNodes(), TpcPrototypeGenFitTrkFinder::CreateNodes(), RawTowerCombiner::CreateNodes(), RawTowerCalibration::CreateNodes(), RawTowerDigitizer::CreateNodes(), TpcPrototypeGenFitTrkFitter::CreateNodes(), PHGenFitTrkFitter::CreateNodes(), GenericUnpackPRDF::CreateNodeTree(), CaloUnpackPRDF::CreateNodeTree(), SecondaryVertexFinder::CreateOutputNode(), PHActsToSvtxTracks::createSvtxTrack(), PHG4TpcDigitizer::DigitizeCylinderCells(), PHG4InttDigitizer::DigitizeLadderCells(), PHG4MvtxDigitizer::DigitizeMvtxLadderCells(), TpcPrototypeGenFitTrkFitter::DisplayCluster(), Fun4AllPrdfInputPoolManager::DitchEvent(), MbdCalib::Download_All(), CentralityReco::Download_centralityDivisions(), CentralityReco::Download_centralityScale(), MbdCalib::Download_Gains(), MbdCalib::Download_SampMax(), MbdCalib::Download_Shapes(), MbdCalib::Download_Slew(), MbdCalib::Download_TQT0(), MbdCalib::Download_TTT0(), Fun4AllHistoManager::dumpHistos(), MakeActsGeometry::editTPCGeometry(), CDBInterface::End(), TPCIntegratedCharge::End(), TrackerEventDisplay::End(), PHSartre::End(), RunTowerInfo::End(), PHG4InttDigitizer::End(), SaveTowerInfo::End(), TPCPedestalCalibration::End(), TpcCombinedRawDataUnpacker::End(), MvtxPrototype2UnpackPRDF::End(), HFJetTruthTrigger::End(), PHPythia8::End(), HFFastSim::End(), JetEvaluator::End(), TPCDataStreamEmulator::End(), ParticleFlowReco::End(), CaloEvaluator::End(), DecayFinder::End(), OnCalServer::End(), AntiTrigger::End(), MultiDetectorMultiplicity::End(), TPCMLDataInterface::End(), PHActsToSvtxTracks::End(), PHG4TpcElectronDrift::End(), PHActsVertexFitter::End(), PHG4DSTReader::End(), BuildResonanceJetTaggingTree::End(), EventEvaluator::End(), MicromegasCombinedDataEvaluation::End(), MicromegasRawDataEvaluation::End(), TPCFEETestRecov1::End(), SynRadAna::End(), AnaTutorial::End(), PHActsSiliconSeeding::End(), TpcPrototypeGenFitTrkFinder::End(), TpcPrototypeUnpacker::End(), SvtxEvaluator::End(), TrkrNtuplizer::End(), PHTpcCentralMembraneClusterizer::End(), HFTriggerMVA::End(), PHCosmicsTrkFitter::End(), Fun4AllServer::End(), PHActsTrkFitter::End(), PHHybridSeeding::End(), FillTruthRecoMatchTree::End(), ResonanceJetTagging::End(), TpcPrototypeGenFitTrkFitter::End(), PHCASeeding::End(), PHGenFitTrkFitter::End(), SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::End(), ParticleFlowReco::EndRun(), SynRadAna::EndRun(), Fun4AllServer::EndRun(), JetMultSub::EstimateRho(), QAG4SimulationCalorimeterSum::eval_trk_proj(), QAG4SimulationMicromegas::evaluate_clusters(), QAG4SimulationTpc::evaluate_clusters(), DSTTrackInfoReader::evaluate_track_info(), DSTTrackInfoWriter::evaluate_track_info(), RawClusterBuilderTopo::export_clusters(), RawClusterBuilderTopo::export_single_cluster(), TpcPrototypeUnpacker::exportDSTCluster(), Fun4AllDstInputManager::fileopen(), Fun4AllPrdfInputManager::fileopen(), Fun4AllRunNodeInputManager::fileopen(), Fun4AllOscarInputManager::fileopen(), SinglePrdfInput::fileopen(), SingleStreamingInput::fileopen(), Fun4AllHepMCInputManager::fileopen(), Fun4AllDstPileupInputManager::fileopen(), Fun4AllSingleDstPileupInputManager::fileopen(), PHG4TrackFastSimEval::fill_track_tree(), CentralityReco::FillCentralityInfo(), TrackResiduals::fillClusterBranches(), Fun4AllStreamingInputManager::FillGl1(), KshortReconstruction::fillHistogram(), Fun4AllStreamingInputManager::FillIntt(), Fun4AllStreamingInputManager::FillInttPool(), Fun4AllStreamingInputManager::FillMicromegas(), Fun4AllStreamingInputManager::FillMicromegasPool(), MinimumBiasClassifier::FillMinimumBiasInfo(), Fun4AllStreamingInputManager::FillMvtx(), Fun4AllStreamingInputManager::FillMvtxPool(), JetEvaluator::fillOutputNtuples(), TrkrNtuplizer::fillOutputNtuples(), CaloEvaluator::fillOutputNtuples(), SvtxEvaluator::fillOutputNtuples(), EventEvaluator::fillOutputNtuples(), SingleGl1PoolInput::FillPool(), SingleTpcPoolInput::FillPool(), SingleMicromegasPoolInput::FillPool(), SingleZdcInput::FillPool(), SingleInttPoolInput::FillPool(), SingleMvtxPoolInput::FillPool(), SinglePrdfInput::FillPool(), SvtxTruthRecoTableEval::fillRecoMap(), PHGenFitTrkFitter::FillSvtxVertexMap(), Fun4AllStreamingInputManager::FillTpc(), Fun4AllStreamingInputManager::FillTpcPool(), PHActsKDTreeSeeding::fillTrackSeedContainer(), PHCASeeding::FillTree(), SvtxTruthRecoTableEval::fillTruthMap(), CentralityReco::FillVars(), PHActsVertexFinder::fillVertexMap(), PHActsInitialVertexFinder::fillVertexMap(), PHCASeeding::FindBiLinks(), VtxTest::findChildren(), PHSimpleVertexFinder::findConnectedTracks(), PHSiliconTpcTrackMatching::findCrossingGeometrically(), PHSimpleVertexFinder::findDcaTwoTracks(), DecayFinder::findDecay(), PHSiliconTpcTrackMatching::findEtaPhiMatches(), PHActsKDTreeSeeding::findInttMatches(), PHActsSiliconSeeding::findInttMatches(), AntiTrigger::findParticle(), DecayFinder::findParticle(), OnCalServer::findRunNumInDB(), PHCASeeding::FindSeedsWithMerger(), HFTrackEfficiency::findTracks(), PHActsVertexFinder::findVertices(), PHActsInitialVertexFinder::findVertices(), PHActsVertexFitter::fitVertex(), PHCASeeding::FollowBiLinks(), PHG4MvtxHitReco::generate_alpide_pulse(), RawClusterBuilderTopo::get_adjacent_towers_by_ID(), PHTpcClusterMover::get_circle_circle_intersection(), SecondaryVertexFinder::get_dca(), HelicalFitter::get_dca(), TPCFEETestRecov1::get_motor_loc(), TpcPrototypeGenFitTrkFitter::get_rotation_matrix(), TpcPrototypeGenFitTrkFitter::get_vertex_error_uvn(), PHSimpleVertexFinder::getAverage(), PHSiliconTpcTrackMatching::getBunchCrossing(), TpcPrototypeGenFitTrkFinder::getChi2Ndf(), PHSiliconTpcTrackMatching::getCrossingIntt(), PHTruthSiliconAssociation::getG4PrimaryParticle(), HelicalFitter::getGlobalDerivativesXY(), AnaTutorial::getHEPMCTruth(), Fun4AllHistoManager::getHisto(), Fun4AllServer::getHistoManager(), PHG4ScoringManager::getHistoManager(), Fun4AllHistoManager::getHistoName(), PHSiliconTpcTrackMatching::getInttCrossings(), PHTruthSiliconAssociation::getInttCrossings(), PHTruthTrackSeeding::getInttCrossings(), MakeActsGeometry::getInttKeyFromNode(), PHActsInitialVertexFinder::getIVFTracks(), HelicalFitter::getLocalDerivativesXY(), MakeMilleFiles::getLocalVtxDerivativesXY(), HelicalFitter::getLocalVtxDerivativesXY(), PHSimpleVertexFinder::getMedian(), JetMultSub::GetMultiplicityCorrection(), MakeActsGeometry::getMvtxKeyFromNode(), PHActsKDTreeSeeding::getMvtxSpacePoints(), CentralityReco::GetNodes(), MinimumBiasClassifier::GetNodes(), TrackSeedTrackMapConverter::getNodes(), PHG4TrackFastSimEval::GetNodes(), ElectronID::GetNodes(), Fun4AllServer::getOutputManager(), PhotonJet::GetRecoHadronsAndJets(), AnaTutorial::getReconstructedJets(), PHActsSiliconSeeding::getSiliconSpacePoints(), SingleGl1PoolInput::GetSomeMoreEvents(), Fun4AllServer::getSubsysReco(), PHG4Reco::getSubsystem(), PHActsTrkFitter::getSurfaceVector(), MakeActsGeometry::getTpcHitSetKeyFromCoords(), PHCosmicsTrkFitter::getTrackFitResult(), PHActsTrkFitter::getTrackFitResult(), PHActsInitialVertexFinder::getTrackPointers(), PHActsVertexFitter::getTracks(), PHActsVertexFinder::getTracks(), AnaTutorial::getTracks(), ReadEICFiles::GetTree(), AnaTutorial::getTruthJets(), CDBInterface::getUrl(), HelicalFitter::getVertexResidual(), SecondaryVertexFinder::getZFromIntersectionXY(), HelicalFitter::globalvtxToLocalvtx(), HFJetTruthTrigger::hadron_tagging(), RunTowerInfo::Init(), SaveTowerInfo::Init(), InttCombinedRawDataConverter::Init(), SynRadAna::Init(), UEvsEtaCentrality::Init(), QAG4SimulationCalorimeter::Init(), QAG4SimulationCalorimeterSum::Init(), MbdDigitization::Init(), DecayFinder::Init(), MultiDetectorMultiplicity::Init(), AntiTrigger::Init(), PHG4DSTReader::Init(), BuildResonanceJetTaggingTree::Init(), PHActsVertexFitter::Init(), CaloWaveformSim::Init(), AnaTutorial::Init(), PhotonJet::Init(), PHActsSiliconSeeding::Init(), PHG4Reco::Init(), FillTruthRecoMatchMap::Init(), MyJetAnalysis::Init(), KFParticle_sPHENIX::Init(), ResonanceJetTagging::Init(), FillTruthRecoMatchTree::Init(), QAG4SimulationJet::Init(), SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::Init(), PHG4Reco::InitField(), TpcPrototypeUnpacker::InitField(), RawClusterZVertexRecorrect::InitRun(), Prototype2RawTowerBuilder::InitRun(), InttCombinedRawDataDecoder::InitRun(), RawTowerBuilder::InitRun(), RawClusterBuilderTemplate::InitRun(), QAG4SimulationUpsilon::InitRun(), TPCIntegratedCharge::InitRun(), CaloCalibration::InitRun(), InttRawDataDecoder::InitRun(), InttVertexFinder::InitRun(), HcalRawTowerBuilder::InitRun(), PHG4InttDigitizer::InitRun(), EventPlaneReco::InitRun(), PHG4BlockCellReco::InitRun(), InttCombinedRawDataConverter::InitRun(), PHG4CentralityReco::InitRun(), PHG4CylinderCellReco::InitRun(), CentralityValid::InitRun(), QAG4SimulationIntt::InitRun(), QAG4SimulationMvtx::InitRun(), TpcLoadDistortionCorrection::InitRun(), CaloTowerCalib::InitRun(), CaloTowerStatus::InitRun(), RawClusterBuilderTopo::InitRun(), MinimumBiasClassifier::InitRun(), QAG4SimulationVertex::InitRun(), PHG4DetectorGroupSubsystem::InitRun(), PHG4DetectorSubsystem::InitRun(), PHG4MvtxDigitizer::InitRun(), GlobalVertexReco::InitRun(), MbdVertexFastSimReco::InitRun(), CaloTemplateFit::InitRun(), PHG4FullProjSpacalCellReco::InitRun(), PHG4ParticleGeneratorVectorMeson::InitRun(), PHG4SimpleEventGenerator::InitRun(), PHG4TpcDigitizer::InitRun(), MvtxPrototype2Clusterizer::InitRun(), InttClusterizer::InitRun(), PHG4InttDeadMapLoader::InitRun(), TpcCombinedRawDataUnpacker::InitRun(), GlobalVertexFastSimReco::InitRun(), DeadHotMapLoader::InitRun(), QAG4SimulationMicromegas::InitRun(), QAG4SimulationCalorimeter::InitRun(), QAG4SimulationTpc::InitRun(), SynRadAna::InitRun(), QAG4SimulationKFParticle::InitRun(), QAG4SimulationTracking::InitRun(), MvtxHitPruner::InitRun(), PHG4InttHitReco::InitRun(), caloTowerEmbed::InitRun(), QAG4SimulationCalorimeterSum::InitRun(), TPCDataStreamEmulator::InitRun(), Proto4TowerCalib::InitRun(), Proto4SampleFrac::InitRun(), PHGenFitTrackProjection::InitRun(), PHG4ScoringManager::InitRun(), PHG4TrackFastSimEval::InitRun(), TPCMLDataInterface::InitRun(), PHTruthClustering::InitRun(), MvtxClusterizer::InitRun(), TpcDirectLaserReconstruction::InitRun(), PHG4TpcElectronDrift::InitRun(), PHSimpleKFProp::InitRun(), TPCFEETestRecov1::InitRun(), TpcPrototypeGenFitTrkFinder::InitRun(), DSTTrackInfoWriter::InitRun(), TpcPrototypeUnpacker::InitRun(), PHActsTrackProjection::InitRun(), PHRaveVertexing::InitRun(), PHActsGSF::InitRun(), PHG4Reco::InitRun(), PHTpcCentralMembraneMatcher::InitRun(), PHCosmicsTrkFitter::InitRun(), MakeActsGeometry::InitRun(), PHActsTrkFitter::InitRun(), TpcPrototypeGenFitTrkFitter::InitRun(), PHGenFitTrkFitter::InitRun(), QAG4SimulationJet::InitRun(), PHG4ZDCSubsystem::InitRunSubsystem(), PHG4SpacalPrototype4Subsystem::InitRunSubsystem(), BeamLineMagnetSubsystem::InitRunSubsystem(), PHG4SpacalPrototypeSubsystem::InitRunSubsystem(), PHG4EICMvtxSubsystem::InitRunSubsystem(), PHG4MvtxSubsystem::InitRunSubsystem(), PHG4InttSubsystem::InitRunSubsystem(), PHG4TpcEndCapSubsystem::InitRunSubsystem(), PHG4MicromegasSubsystem::InitRunSubsystem(), PHG4SpacalSubsystem::InitRunSubsystem(), PHG4BbcSubsystem::InitRunSubsystem(), OnCalServer::insertRunNumInDB(), PHTruthClustering::LayerClusterG4Hits(), PHTpcDeltaZCorrection::load_nodes(), HelicalFitter::localvtxToGlobalvtx(), PHCosmicsTrkFitter::loopTracks(), PHActsTrkFitter::loopTracks(), SingleZdcInput::majority_beamclock(), SinglePrdfInput::majority_beamclock(), PHActsTrackProjection::makeCaloSurfacePtrs(), MakeActsGeometry::makeInttMapPairs(), TrackerEventDisplay::makeJsonFile(), MakeActsGeometry::makeMmMapPairs(), MakeActsGeometry::makeMvtxMapPairs(), PHG4ScoringManager::makeScoringHistograms(), PHCosmicSeeder::makeSeeds(), PHActsKDTreeSeeding::makeSpacePoint(), PHActsSiliconSeeding::makeSpacePoint(), PHG4TrackFastSim::MakeSvtxTrack(), TpcPrototypeGenFitTrkFitter::MakeSvtxTrack(), PHGenFitTrkFitter::MakeSvtxTrack(), PHActsSiliconSeeding::makeSvtxTracks(), MakeActsGeometry::makeTpcMapPairs(), TpcPrototypeGenFitTrkFitter::MakeTpcPrototypeTrack(), PHG4TpcPadPlaneReadout::MapToPadPlane(), PHActsKDTreeSeeding::matchInttClusters(), PHActsSiliconSeeding::matchInttClusters(), PHTrackClusterAssociator::matchTracks(), VtxTest::numUnique(), TruthConversionEval::numUnique(), Fun4AllInputManager::OpenNextFile(), Fun4AllServer::outfileclose(), Fun4AllPrdfOutputManager::outfileopen(), DecayFinder::parseDecayDescriptor(), KFParticle_sPHENIX::parseDecayDescriptor(), AntiTrigger::parseParticleList(), AntiTrigger::particleIsInList(), HFJetTruthTrigger::parton_tagging(), PHActsToSvtxTracks::PHActsToSvtxTracks(), PHG4MvtxDigitizer::PHG4MvtxDigitizer(), PHG4TpcDigitizer::PHG4TpcDigitizer(), PHGenFitTrkFitter::PHGenFitTrkFitter(), PHRaveVertexing::PHRaveVertexing(), PHG4TpcPadPlaneReadout::populate_tbins(), PHG4TpcPadPlaneReadout::populate_zigzag_phibins(), TpcPrototypeGenFitTrkFitter::pos_cov_uvn_to_rz(), PHGenFitTrkFitter::pos_cov_XYZ_to_RZ(), TpcPrototypeGenFitTrkFitter::pos_cov_XYZ_to_RZ(), PHSimpleKFProp::PrepareKDTrees(), JetMultSub::Print(), MvtxPrototype2Clusterizer::PrintClusters(), MvtxClusterizer::PrintClusters(), InttClusterizer::PrintClusters(), TrkrNtuplizer::printInputInfo(), CaloEvaluator::printInputInfo(), SvtxEvaluator::printInputInfo(), TrkrNtuplizer::printOutputInfo(), CaloEvaluator::printOutputInfo(), SvtxEvaluator::printOutputInfo(), PHActsVertexFinder::Process(), PHTruthVertexing::Process(), PHSiliconTruthTrackSeeding::Process(), PHActsInitialVertexFinder::Process(), PHTruthTrackSeeding::Process(), PHHybridSeeding::Process(), PHCASeeding::Process(), PHG4TruthSubsystem::process_after_geant(), HFFastSim::process_D02PiK(), PHSiliconHelicalPropagator::process_event(), PHG4ParticleGun::process_event(), SyncReco::process_event(), PHG4InputFilter::process_event(), PHG4HeadReco::process_event(), RawClusterBuilderGraph::process_event(), HeadReco::process_event(), PHG4GenHit::process_event(), PHG4ParticleGenerator::process_event(), RawClusterZVertexRecorrect::process_event(), EventInfoSummary::process_event(), RunInfoUnpackPRDF::process_event(), PHG4ParticleGeneratorD0::process_event(), HepMCFlowAfterBurner::process_event(), Prototype2RawTowerBuilder::process_event(), RawClusterDeadHotMask::process_event(), TowerInfoDeadHotMask::process_event(), SvtxTrackStateRemoval::process_event(), RawTowerBuilder::process_event(), TpcPrototypeClusterizer::process_event(), GenericUnpackPRDF::process_event(), TempInfoUnpackPRDF::process_event(), RawClusterPositionCorrection::process_event(), RawTowerDeadTowerInterp::process_event(), TpcCheck::process_event(), InttCheck::process_event(), TrackContainerCombiner::process_event(), StreamingCheck::process_event(), CosmicSpray::process_event(), CaloUnpackPRDF::process_event(), PHG4Prototype2HcalCellReco::process_event(), QAG4SimulationUpsilon::process_event(), HepMCNodeReader::process_event(), TPCIntegratedCharge::process_event(), PHCosmicSiliconPropagator::process_event(), MvtxRunInfoUnpackPRDF::process_event(), SvtxTruthRecoTableEval::process_event(), InttRawDataDecoder::process_event(), HcalRawTowerBuilder::process_event(), PHSiliconSeedMerger::process_event(), CaloCalibration::process_event(), PHCosmicSeedCombiner::process_event(), PHSartre::process_event(), EventPlaneReco::process_event(), TrackSeedTrackMapConverter::process_event(), TPCPedestalCalibration::process_event(), RunTowerInfo::process_event(), PHG4HcalCellReco::process_event(), InttCombinedRawDataConverter::process_event(), ReadEICFiles::process_event(), PHG4CentralityReco::process_event(), InttVertexFinder::process_event(), InttRawDataConverter::process_event(), SaveTowerInfo::process_event(), PHHepMCParticleSelectorDecayProductChain::process_event(), RawClusterBuilderTopo::process_event(), RawTowerCalibration::process_event(), PHG4BlockCellReco::process_event(), MbdReco::process_event(), ReadSynRadFiles::process_event(), RawTowerBuilderByHitIndex::process_event(), PHG4CylinderCellReco::process_event(), QAG4SimulationVertex::process_event(), CentralityValid::process_event(), GlobalVertexReco::process_event(), MbdVertexFastSimReco::process_event(), MvtxPrototype2UnpackPRDF::process_event(), TpcClusterCleaner::process_event(), PHG4SimpleEventGenerator::process_event(), CentralityReco::process_event(), PHTpcTrackSeedCircleFit::process_event(), PHTrackClusterAssociator::process_event(), CaloTemplateFit::process_event(), PHG4ParticleGeneratorVectorMeson::process_event(), ClusterIso::process_event(), RawTowerDigitizer::process_event(), SubtractTowers::process_event(), SubtractTowersCS::process_event(), TpcCombinedRawDataUnpacker::process_event(), TpcSimpleClusterizer::process_event(), HFJetTruthTrigger::process_event(), GlobalVertexFastSimReco::process_event(), PHG4TpcCentralMembrane::process_event(), ParticleFlowReco::process_event(), RetowerCEMC::process_event(), PHG4FullProjSpacalCellReco::process_event(), CopyAndSubtractJets::process_event(), PHG4TpcPadBaselineShift::process_event(), MinimumBiasClassifier::process_event(), TrackClusterEvaluator::process_event(), PHPythia8::process_event(), QAG4SimulationCalorimeter::process_event(), PHTrackSelector::process_event(), MicromegasRawDataDecoder::process_event(), PHCosmicTrackMerger::process_event(), PHTrackCleaner::process_event(), HFMLTriggerHepMCTrigger::process_event(), PHActsVertexPropagator::process_event(), Forward_pi0s::process_event(), MicromegasCombinedDataDecoder::process_event(), MicromegasRawDataCalibration::process_event(), QAG4SimulationTracking::process_event(), QAG4SimulationKFParticle::process_event(), caloTowerEmbed::process_event(), DetermineTowerBackground::process_event(), CaloTriggerSim::process_event(), TpcClusterizer::process_event(), HFFastSim::process_event(), PHCosmicSeeder::process_event(), Photons::process_event(), QAG4SimulationCalorimeterSum::process_event(), TPCGemGainCalb::process_event(), PHSimpleVertexFinder::process_event(), PHTpcClusterMover::process_event(), PHG4MvtxHitReco::process_event(), FastTrackingEval::process_event(), TPCDataStreamEmulator::process_event(), PHG4InttHitReco::process_event(), HFMLTriggerInterface::process_event(), JetEvaluator::process_event(), MvtxPrototype2Align::process_event(), HFMLTriggerOccupancy::process_event(), MvtxHitPruner::process_event(), TPCRawDataTree::process_event(), TpcRawDataTree::process_event(), SynRadAna::process_event(), PHTruthSiliconAssociation::process_event(), DecayFinder::process_event(), PHG4MicromegasHitReco::process_event(), TrackResiduals::process_event(), CaloEvaluator::process_event(), TruthPhotonJet::process_event(), PHGenFitTrackProjection::process_event(), Proto4TowerCalib::process_event(), Proto4SampleFrac::process_event(), MultiDetectorMultiplicity::process_event(), MvtxCombinedRawDataDecoder::process_event(), PHActsVertexFitter::process_event(), Prototype2DSTReader::process_event(), MbdDigitization::process_event(), PHG4DSTReader::process_event(), TPCMLDataInterface::process_event(), BuildResonanceJetTaggingTree::process_event(), PHSiliconTpcTrackMatching::process_event(), PHG4TrackFastSimEval::process_event(), MicromegasRawDataEvaluation::process_event(), tpc_hits::process_event(), PHMicromegasTpcTrackMatching::process_event(), PHG4TpcElectronDrift::process_event(), Prototype3DSTReader::process_event(), MicromegasCombinedDataEvaluation::process_event(), PHTruthClustering::process_event(), Prototype4DSTReader::process_event(), PHG4ScoringManager::process_event(), MakeMilleFiles::process_event(), AnaTutorial::process_event(), PHSimpleKFProp::process_event(), EventEvaluator::process_event(), TPCFEETestRecov1::process_event(), PHActsToSvtxTracks::process_event(), PhotonJet::process_event(), ElectronID::process_event(), TpcRawDataDecoder::process_event(), CaloWaveformSim::process_event(), JetMultSub::process_event(), PHActsSiliconSeeding::process_event(), TpcPrototypeGenFitTrkFinder::process_event(), HFTrigger::process_event(), TpcPrototypeUnpacker::process_event(), KshortReconstruction::process_event(), JetHepMCLoader::process_event(), DSTTrackInfoWriter::process_event(), PHActsTrackProjection::process_event(), SvtxEvaluator::process_event(), TrkrNtuplizer::process_event(), PHActsGSF::process_event(), HelicalFitter::process_event(), PHTpcCentralMembraneClusterizer::process_event(), AnaMvtxTestBeam2019::process_event(), PHRaveVertexing::process_event(), HFTriggerMVA::process_event(), TruthConversionEval::process_event(), FillTruthRecoMatchMap::process_event(), PHG4Reco::process_event(), MyJetAnalysis::process_event(), JetBkgdSub::process_event(), PHTpcCentralMembraneMatcher::process_event(), KFParticle_sPHENIX::process_event(), HFTrackEfficiency::process_event(), PHCosmicsTrkFitter::process_event(), Fun4AllServer::process_event(), SecondaryVertexFinder::process_event(), PHActsTrkFitter::process_event(), RawTowerCombiner::process_event(), FillTruthRecoMatchTree::process_event(), TpcPrototypeGenFitTrkFitter::process_event(), PHGenFitTrkFitter::process_event(), QAG4SimulationJet::process_event(), SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::process_event(), QAG4SimulationCalorimeter::process_event_Cluster(), QAG4SimulationCalorimeterSum::process_event_Cluster(), QAG4SimulationCalorimeter::process_event_G4Hit(), EMCalAna::process_event_SF(), QAG4SimulationCalorimeter::process_event_Tower(), QAG4SimulationCalorimeterSum::process_event_TrackProj(), HFFastSim::process_Lc2pPiK(), QAG4SimulationJet::process_Spectrum(), PHTpcDeltaZCorrection::process_track(), TpcDirectLaserReconstruction::process_track(), TpcSpaceChargeReconstruction::process_track(), QAG4SimulationJet::process_TruthMatching(), TrackClusterEvaluator::processRecoTracks(), PHTpcResiduals::processTrack(), PHTpcResiduals::processTracks(), KshortReconstruction::projectTrackToPoint(), SecondaryVertexFinder::projectTrackToPoint(), PHActsVertexPropagator::propagateTrack(), PHActsTrackPropagator::propagateTrack(), PHActsTrackProjection::propagateTrack(), PHSimpleKFProp::PropagateTrack(), Proto4SampleFrac::Proto4SampleFrac(), Proto4TowerCalib::Proto4TowerCalib(), PHG4TrackFastSim::PseudoPatternRecognition(), PHCASeeding::publishSeeds(), Fun4AllPrdfInputManager::PushBackEvents(), Fun4AllHepMCInputManager::PushBackEvents(), PHPythia8::read_config(), MvtxPrototype2Align::ReadAlignmentParFile(), RawTowerBuilderByHitIndex::ReadGeometryFromTable(), Fun4AllDstInputManager::ReadNextEventSyncObject(), TpcPrototypeGenFitTrkFitter::ReFitTrack(), PHGenFitTrkFitter::ReFitTrack(), PHSartre::register_trigger(), PHPythia8::register_trigger(), Fun4AllHistoManager::registerHisto(), Fun4AllServer::registerHistoManager(), Fun4AllSyncManager::registerInputManager(), Fun4AllServer::registerOutputManager(), TpcPrototypeUnpacker::registerPadPlane(), PHG4TpcElectronDrift::registerPadPlane(), Fun4AllStreamingInputManager::registerStreamingInput(), Fun4AllInputManager::registerSubsystem(), Fun4AllServer::registerSubsystem(), Fun4AllServer::registerSyncManager(), Fun4AllInputManager::RejectEvent(), PHSimpleKFProp::RemoveBadClusters(), PHCASeeding::RemoveBadClusters(), PHSimpleVertexFinder::removeOutlierTrackPairs(), ParticleFlowReco::Reset(), SynRadAna::Reset(), JetMultSub::Reset(), Fun4AllServer::Reset(), EventEvaluator::resetBuffer(), SvtxTruthRecoTableEval::ResetEvent(), CentralityReco::ResetEvent(), ParticleFlowReco::ResetEvent(), SynRadAna::ResetEvent(), Fun4AllSyncManager::ResetEvent(), PHCosmicsTrkFitter::ResetEvent(), PHActsTrkFitter::ResetEvent(), Fun4AllServer::ResetNodeTree(), Fun4AllPrdfInputPoolManager::Resynchronize(), PHG4ParticleGeneratorBase::ReuseExistingVertex(), Fun4AllDstInputManager::run(), Fun4AllRunNodeInputManager::run(), Fun4AllDummyInputManager::run(), Fun4AllPrdfInputManager::run(), Fun4AllHepMCPileupInputManager::run(), Fun4AllSyncManager::run(), Fun4AllOscarInputManager::run(), Fun4AllPrdfInputPoolManager::run(), Fun4AllHepMCInputManager::run(), Fun4AllDstPileupInputManager::run(), Fun4AllSingleDstPileupInputManager::run(), Fun4AllServer::run(), Fun4AllDstPileupInputManager::runOne(), PHActsKDTreeSeeding::runSeeder(), HFTrigger::runTrigger(), HFTriggerMVA::runTrigger(), DecayFinder::searchGeant4Record(), DecayFinder::searchHepMCRecord(), SColdQcdCorrelatorAnalysis::SEnergyCorrelator::SEnergyCorrelator(), Fun4AllDstInputManager::setBranches(), Fun4AllDstPileupInputManager::setBranches(), Fun4AllSingleDstPileupInputManager::setBranches(), MakeActsGeometry::setMaterialResponseFile(), MbdEvent::SetRawData(), PHSiliconTruthTrackSeeding::Setup(), PHHybridSeeding::Setup(), PHCASeeding::Setup(), RawTowerDigitizer::simple_photon_digitization(), RawTowerDigitizer::sipm_photon_digitization(), Fun4AllMemoryTracker::Snapshot(), PHActsInitialVertexFinder::sortTracks(), Fun4AllMemoryTracker::Start(), Fun4AllMemoryTracker::Stop(), Fun4AllDstInputManager::SyncIt(), OnCalServer::SyncOncalTimeStampsToRunDB(), SynRadAna::SynRadAna(), TpcPrototypeGenFitTrkFinder::TpcPrototypeGenFitTrkFinder(), TpcPrototypeGenFitTrkFitter::TpcPrototypeGenFitTrkFitter(), PHG4InttHitReco::truthcheck_g4hit(), PHG4MvtxHitReco::truthcheck_g4hit(), MakeActsGeometry::unpackVolumes(), Fun4AllServer::unregisterSubsystemsNow(), OnCalServer::updateDB(), OnCalServer::updateDBRunRange(), Fun4AllServer::UpdateEventSelector(), PHActsVertexPropagator::updateSvtxTrack(), PHActsGSF::updateSvtxTrack(), PHActsTrackProjection::updateSvtxTrack(), PHCosmicsTrkFitter::updateSvtxTrack(), PHActsTrkFitter::updateSvtxTrack(), PHActsVertexFitter::updateSvtxVertex(), PHG4TpcPadPlaneReadout::UseGain(), Fun4AllEventOutputManager::Verbosity(), FieldMapReadBack::Verbosity(), Fun4AllDstOutputManager::Write(), Fun4AllEventOutStream::WriteEvent(), Fun4AllRolloverFileOutStream::WriteEventOut(), Fun4AllDstOutputManager::WriteNode(), CaloTowerCalib::~CaloTowerCalib(), CaloTowerStatus::~CaloTowerStatus(), Fun4AllInputManager::~Fun4AllInputManager(), Fun4AllServer::~Fun4AllServer(), Fun4AllSyncManager::~Fun4AllSyncManager(), PHG4DSTReader::~PHG4DSTReader(), SingleInttPoolInput::~SingleInttPoolInput(), and SynRadAna::~SynRadAna().
Member Data Documentation
std::string Fun4AllBase::m_ThisName private
Definition at line 73 of file Fun4AllBase.h.
View newest version in sPHENIX GitHub at line 73 of file Fun4AllBase.h
Referenced by Name(), and ~Fun4AllBase().
int Fun4AllBase::m_Verbosity = VERBOSITY_QUIET private
The verbosity level. 0 means not verbose at all.
Definition at line 76 of file Fun4AllBase.h.
View newest version in sPHENIX GitHub at line 76 of file Fun4AllBase.h
Referenced by Verbosity(), and ~Fun4AllBase().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/framework/fun4all/Fun4AllBase.h
coresoftware/blob/master/offline/framework/fun4all/Fun4AllBase.cc