Analysis Software: ODBCResultSetMetaData Class Reference
ODBCResultSetMetaData Class Reference
#include <RDBC/blob/master/odbc/ODBCResultSetMetaData.h>
Public Member Functions
Int_t GetColumnCount ()
Bool_t IsAutoIncrement (Int_t column)
Bool_t IsCaseSensitive (Int_t column)
Bool_t IsSearchable (Int_t column)
Bool_t IsCurrency (Int_t column)
Bool_t IsNullable (Int_t column)
Bool_t IsSigned (Int_t column)
Int_t GetColumnDisplaySize (Int_t column)
TString GetColumnLabel (Int_t column)
TString GetColumnName (Int_t column)
TString GetSchemaName (Int_t column)
Int_t GetPrecision (Int_t column)
Int_t GetScale (Int_t column)
TString GetTableName (Int_t column)
TString GetCatalogName (Int_t column)
Int_t GetColumnType (Int_t column)
TString GetColumnTypeName (Int_t column)
Bool_t IsReadOnly (Int_t column)
Bool_t IsWritable (Int_t column)
Bool_t IsDefinitelyWritable (Int_t column)
Protected Member Functions
ODBCResultSetMetaData (TSQLResultSet *rs, void *imp=0)
virtual ~ODBCResultSetMetaData ()
Protected Member Functions inherited from TSQLResultSetMetaData
TSQLResultSetMetaData (TSQLResultSet *rs, void *imp=0)
virtual ~TSQLResultSetMetaData ()
Friends
class ODBCResultSet
Additional Inherited Members
Static Public Member Functions inherited from TSQL
static Bool_t SetHandler (const TString &handler)
static Bool_t UnsetHandler (const TString &handler="")
Protected Attributes inherited from TSQLResultSetMetaData
TSQLResultSet * fResultSet
Detailed Description
Definition at line 16 of file ODBCResultSetMetaData.h.
View newest version in sPHENIX GitHub at line 16 of file ODBCResultSetMetaData.h
Constructor & Destructor Documentation
ODBCResultSetMetaData::ODBCResultSetMetaData (TSQLResultSet * rs, void * imp = 0) protected
ODBCResultSetMetaData::~ODBCResultSetMetaData () protected virtual
Definition at line 57 of file ODBCResultSetMetaData.cxx.
View newest version in sPHENIX GitHub at line 57 of file ODBCResultSetMetaData.cxx
References Acts::UnitConstants::e, TSQL::fImp, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), ODBCXX_STRING_CSTR, and TSQL::Throw().
Member Function Documentation
TString ODBCResultSetMetaData::GetCatalogName (Int_t column) virtual
Implements TSQLResultSetMetaData.
Definition at line 481 of file ODBCResultSetMetaData.cxx.
View newest version in sPHENIX GitHub at line 481 of file ODBCResultSetMetaData.cxx
References Acts::UnitConstants::e, TSQL::fImp, odbc::ResultSetMetaData::getCatalogName(), odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), ODBCXX_STRING_CSTR, str, and TSQL::Throw().
Int_t ODBCResultSetMetaData::GetColumnCount () virtual
Implements TSQLResultSetMetaData.
Definition at line 76 of file ODBCResultSetMetaData.cxx.
View newest version in sPHENIX GitHub at line 76 of file ODBCResultSetMetaData.cxx
References Acts::UnitConstants::e, TSQL::fImp, odbc::ResultSetMetaData::getColumnCount(), odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), ODBCXX_STRING_CSTR, and TSQL::Throw().
Int_t ODBCResultSetMetaData::GetColumnDisplaySize (Int_t column) virtual
Implements TSQLResultSetMetaData.
Definition at line 283 of file ODBCResultSetMetaData.cxx.
View newest version in sPHENIX GitHub at line 283 of file ODBCResultSetMetaData.cxx
References Acts::UnitConstants::e, TSQL::fImp, odbc::ResultSetMetaData::getColumnDisplaySize(), odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), ODBCXX_STRING_CSTR, and TSQL::Throw().
TString ODBCResultSetMetaData::GetColumnLabel (Int_t column) virtual
Implements TSQLResultSetMetaData.
Definition at line 312 of file ODBCResultSetMetaData.cxx.
View newest version in sPHENIX GitHub at line 312 of file ODBCResultSetMetaData.cxx
References Acts::UnitConstants::e, TSQL::fImp, odbc::ResultSetMetaData::getColumnLabel(), odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), ODBCXX_STRING_CSTR, str, and TSQL::Throw().
TString ODBCResultSetMetaData::GetColumnName (Int_t column) virtual
Implements TSQLResultSetMetaData.
Definition at line 341 of file ODBCResultSetMetaData.cxx.
View newest version in sPHENIX GitHub at line 341 of file ODBCResultSetMetaData.cxx
References Acts::UnitConstants::e, TSQL::fImp, odbc::ResultSetMetaData::getColumnName(), odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), ODBCXX_STRING_CSTR, str, and TSQL::Throw().
Int_t ODBCResultSetMetaData::GetColumnType (Int_t column) virtual
Implements TSQLResultSetMetaData.
Definition at line 509 of file ODBCResultSetMetaData.cxx.
View newest version in sPHENIX GitHub at line 509 of file ODBCResultSetMetaData.cxx
References Acts::UnitConstants::e, TSQL::fImp, odbc::ResultSetMetaData::getColumnType(), odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), ODBCXX_STRING_CSTR, and TSQL::Throw().
TString ODBCResultSetMetaData::GetColumnTypeName (Int_t column) virtual
Implements TSQLResultSetMetaData.
Definition at line 564 of file ODBCResultSetMetaData.cxx.
View newest version in sPHENIX GitHub at line 564 of file ODBCResultSetMetaData.cxx
References Acts::UnitConstants::e, TSQL::fImp, odbc::ResultSetMetaData::getColumnTypeName(), odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), ODBCXX_STRING_CSTR, str, and TSQL::Throw().
Int_t ODBCResultSetMetaData::GetPrecision (Int_t column) virtual
Implements TSQLResultSetMetaData.
Definition at line 397 of file ODBCResultSetMetaData.cxx.
View newest version in sPHENIX GitHub at line 397 of file ODBCResultSetMetaData.cxx
References Acts::UnitConstants::e, TSQL::fImp, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::ResultSetMetaData::getPrecision(), odbc::SQLException::getSQLState(), ODBCXX_STRING_CSTR, and TSQL::Throw().
Int_t ODBCResultSetMetaData::GetScale (Int_t column) virtual
Implements TSQLResultSetMetaData.
Definition at line 425 of file ODBCResultSetMetaData.cxx.
View newest version in sPHENIX GitHub at line 425 of file ODBCResultSetMetaData.cxx
References Acts::UnitConstants::e, TSQL::fImp, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::ResultSetMetaData::getScale(), odbc::SQLException::getSQLState(), ODBCXX_STRING_CSTR, and TSQL::Throw().
TString ODBCResultSetMetaData::GetSchemaName (Int_t column) virtual
Implements TSQLResultSetMetaData.
Definition at line 369 of file ODBCResultSetMetaData.cxx.
View newest version in sPHENIX GitHub at line 369 of file ODBCResultSetMetaData.cxx
References Acts::UnitConstants::e, TSQL::fImp, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::ResultSetMetaData::getSchemaName(), odbc::SQLException::getSQLState(), ODBCXX_STRING_CSTR, str, and TSQL::Throw().
TString ODBCResultSetMetaData::GetTableName (Int_t column) virtual
Implements TSQLResultSetMetaData.
Definition at line 453 of file ODBCResultSetMetaData.cxx.
View newest version in sPHENIX GitHub at line 453 of file ODBCResultSetMetaData.cxx
References Acts::UnitConstants::e, TSQL::fImp, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), odbc::ResultSetMetaData::getTableName(), ODBCXX_STRING_CSTR, str, and TSQL::Throw().
Bool_t ODBCResultSetMetaData::IsAutoIncrement (Int_t column) virtual
Implements TSQLResultSetMetaData.
Definition at line 104 of file ODBCResultSetMetaData.cxx.
View newest version in sPHENIX GitHub at line 104 of file ODBCResultSetMetaData.cxx
References Acts::UnitConstants::e, TSQL::fImp, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), odbc::ResultSetMetaData::isAutoIncrement(), ODBCXX_STRING_CSTR, and TSQL::Throw().
Bool_t ODBCResultSetMetaData::IsCaseSensitive (Int_t column) virtual
Implements TSQLResultSetMetaData.
Definition at line 139 of file ODBCResultSetMetaData.cxx.
View newest version in sPHENIX GitHub at line 139 of file ODBCResultSetMetaData.cxx
References Acts::UnitConstants::e, TSQL::fImp, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), odbc::ResultSetMetaData::isCaseSensitive(), ODBCXX_STRING_CSTR, and TSQL::Throw().
Bool_t ODBCResultSetMetaData::IsCurrency (Int_t column) virtual
Implements TSQLResultSetMetaData.
Definition at line 196 of file ODBCResultSetMetaData.cxx.
View newest version in sPHENIX GitHub at line 196 of file ODBCResultSetMetaData.cxx
References Acts::UnitConstants::e, TSQL::fImp, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), odbc::ResultSetMetaData::isCurrency(), ODBCXX_STRING_CSTR, and TSQL::Throw().
Bool_t ODBCResultSetMetaData::IsDefinitelyWritable (Int_t column) virtual
Implements TSQLResultSetMetaData.
Definition at line 652 of file ODBCResultSetMetaData.cxx.
View newest version in sPHENIX GitHub at line 652 of file ODBCResultSetMetaData.cxx
References Acts::UnitConstants::e, TSQL::fImp, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), odbc::ResultSetMetaData::isDefinitelyWritable(), ODBCXX_STRING_CSTR, and TSQL::Throw().
Bool_t ODBCResultSetMetaData::IsNullable (Int_t column) virtual
Implements TSQLResultSetMetaData.
Definition at line 225 of file ODBCResultSetMetaData.cxx.
View newest version in sPHENIX GitHub at line 225 of file ODBCResultSetMetaData.cxx
References Acts::UnitConstants::e, TSQL::fImp, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), odbc::ResultSetMetaData::isNullable(), ODBCXX_STRING_CSTR, and TSQL::Throw().
Bool_t ODBCResultSetMetaData::IsReadOnly (Int_t column) virtual
Implements TSQLResultSetMetaData.
Definition at line 595 of file ODBCResultSetMetaData.cxx.
View newest version in sPHENIX GitHub at line 595 of file ODBCResultSetMetaData.cxx
References Acts::UnitConstants::e, TSQL::fImp, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), odbc::ResultSetMetaData::isReadOnly(), ODBCXX_STRING_CSTR, and TSQL::Throw().
Bool_t ODBCResultSetMetaData::IsSearchable (Int_t column) virtual
Implements TSQLResultSetMetaData.
Definition at line 168 of file ODBCResultSetMetaData.cxx.
View newest version in sPHENIX GitHub at line 168 of file ODBCResultSetMetaData.cxx
References Acts::UnitConstants::e, TSQL::fImp, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), odbc::ResultSetMetaData::isSearchable(), ODBCXX_STRING_CSTR, and TSQL::Throw().
Bool_t ODBCResultSetMetaData::IsSigned (Int_t column) virtual
Implements TSQLResultSetMetaData.
Definition at line 255 of file ODBCResultSetMetaData.cxx.
View newest version in sPHENIX GitHub at line 255 of file ODBCResultSetMetaData.cxx
References Acts::UnitConstants::e, TSQL::fImp, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), odbc::ResultSetMetaData::isSigned(), ODBCXX_STRING_CSTR, and TSQL::Throw().
Bool_t ODBCResultSetMetaData::IsWritable (Int_t column) virtual
Implements TSQLResultSetMetaData.
Definition at line 623 of file ODBCResultSetMetaData.cxx.
View newest version in sPHENIX GitHub at line 623 of file ODBCResultSetMetaData.cxx
References Acts::UnitConstants::e, TSQL::fImp, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), odbc::ResultSetMetaData::isWritable(), ODBCXX_STRING_CSTR, and TSQL::Throw().
Friends And Related Function Documentation
friend class ODBCResultSet friend
Definition at line 18 of file ODBCResultSetMetaData.h.
View newest version in sPHENIX GitHub at line 18 of file ODBCResultSetMetaData.h
The documentation for this class was generated from the following files:
RDBC/blob/master/odbc/ODBCResultSetMetaData.h
RDBC/blob/master/odbc/ODBCResultSetMetaData.cxx