Analysis Software: ZdcMonDraw Class Reference
ZdcMonDraw Class Reference
#include <OnlMon/blob/main/subsystems/zdc/ZdcMonDraw.h>
Public Member Functions
ZdcMonDraw (const std::string &name)
~ZdcMonDraw () override
int Init () override
int Draw (const std::string &what="ALL") override
int MakeHtml (const std::string &what="ALL") override
int SavePlot (const std::string &what="ALL", const std::string &type="png") override
Public Member Functions inherited from OnlMonDraw
OnlMonDraw (const std::string &name="NONE")
virtual ~OnlMonDraw ()
virtual int MakePS (const std::string &what="ALL")
const std::string Name () const
void Verbosity (const int i)
int Verbosity () const
Protected Member Functions
int MakeCanvas (const std::string &name)
int DrawFirst (const std::string &what="ALL")
int DrawSecond (const std::string &what="ALL")
Protected Member Functions inherited from OnlMonDraw
virtual int DrawDeadServer (TPad *transparent)
Protected Attributes
TCanvas * TC [2] = {nullptr}
TPad * transparent [2] = {nullptr}
TPad * Pad [4] = {nullptr}
Protected Attributes inherited from OnlMonDraw
std::string ThisName
int verbosity = 0
Detailed Description
Definition at line 13 of file ZdcMonDraw.h.
View newest version in sPHENIX GitHub at line 13 of file ZdcMonDraw.h
Constructor & Destructor Documentation
ZdcMonDraw::ZdcMonDraw (const std::string & name)
Definition at line 23 of file ZdcMonDraw.cc.
View newest version in sPHENIX GitHub at line 23 of file ZdcMonDraw.cc
ZdcMonDraw::~ZdcMonDraw () inline override
Definition at line 18 of file ZdcMonDraw.h.
View newest version in sPHENIX GitHub at line 18 of file ZdcMonDraw.h
Member Function Documentation
int ZdcMonDraw::Draw (const std::string & what = "ALL") override virtual
Reimplemented from OnlMonDraw.
Definition at line 76 of file ZdcMonDraw.cc.
View newest version in sPHENIX GitHub at line 76 of file ZdcMonDraw.cc
References DrawFirst(), and DrawSecond().
Referenced by MakeHtml(), and SavePlot().
int ZdcMonDraw::DrawFirst (const std::string & what = "ALL") protected
Definition at line 98 of file ZdcMonDraw.cc.
View newest version in sPHENIX GitHub at line 98 of file ZdcMonDraw.cc
References OnlMonDraw::DrawDeadServer(), OnlMonClient::EventTime(), OnlMonClient::getHisto(), OnlMonClient::instance(), MakeCanvas(), Pad, OnlMonClient::RunNumber(), TC, OnlMonDraw::ThisName, and transparent.
Referenced by Draw().
int ZdcMonDraw::DrawSecond (const std::string & what = "ALL") protected
Definition at line 151 of file ZdcMonDraw.cc.
View newest version in sPHENIX GitHub at line 151 of file ZdcMonDraw.cc
References OnlMonDraw::DrawDeadServer(), OnlMonClient::EventTime(), OnlMonClient::getHisto(), OnlMonClient::instance(), MakeCanvas(), Pad, OnlMonClient::RunNumber(), TC, OnlMonDraw::ThisName, and transparent.
Referenced by Draw().
int ZdcMonDraw::Init () override virtual
Reimplemented from OnlMonDraw.
Definition at line 29 of file ZdcMonDraw.cc.
View newest version in sPHENIX GitHub at line 29 of file ZdcMonDraw.cc
int ZdcMonDraw::MakeCanvas (const std::string & name) protected
Definition at line 34 of file ZdcMonDraw.cc.
View newest version in sPHENIX GitHub at line 34 of file ZdcMonDraw.cc
References OnlMonClient::GetDisplaySizeX(), OnlMonClient::GetDisplaySizeY(), OnlMonClient::instance(), Pad, TC, and transparent.
Referenced by DrawFirst(), and DrawSecond().
int ZdcMonDraw::MakeHtml (const std::string & what = "ALL") override virtual
Reimplemented from OnlMonDraw.
Definition at line 222 of file ZdcMonDraw.cc.
View newest version in sPHENIX GitHub at line 222 of file ZdcMonDraw.cc
References OnlMonClient::CanvasToPng(), Draw(), OnlMonClient::htmlRegisterPage(), OnlMonClient::instance(), out, OnlMonClient::RunNumber(), OnlMonClient::SaveLogFile(), utils::status, and TC.
int ZdcMonDraw::SavePlot (const std::string & what = "ALL", const std::string & type = "png") override virtual
Reimplemented from OnlMonDraw.
Definition at line 198 of file ZdcMonDraw.cc.
View newest version in sPHENIX GitHub at line 198 of file ZdcMonDraw.cc
References OnlMonClient::CanvasToPng(), Draw(), filename, OnlMonClient::instance(), OnlMonClient::RunNumber(), TC, OnlMonDraw::ThisName, and to_string().
Member Data Documentation
TPad* ZdcMonDraw::Pad[4] = {nullptr} protected
Definition at line 31 of file ZdcMonDraw.h.
View newest version in sPHENIX GitHub at line 31 of file ZdcMonDraw.h
Referenced by DrawFirst(), DrawSecond(), and MakeCanvas().
TCanvas* ZdcMonDraw::TC[2] = {nullptr} protected
Definition at line 29 of file ZdcMonDraw.h.
View newest version in sPHENIX GitHub at line 29 of file ZdcMonDraw.h
Referenced by DrawFirst(), DrawSecond(), MakeCanvas(), MakeHtml(), and SavePlot().
TPad* ZdcMonDraw::transparent[2] = {nullptr} protected
Definition at line 30 of file ZdcMonDraw.h.
View newest version in sPHENIX GitHub at line 30 of file ZdcMonDraw.h
Referenced by DrawFirst(), DrawSecond(), and MakeCanvas().
The documentation for this class was generated from the following files:
OnlMon/blob/main/subsystems/zdc/ZdcMonDraw.h
OnlMon/blob/main/subsystems/zdc/ZdcMonDraw.cc