Analysis Software: macros/blob/master/common/G4_TPC.C File Reference
G4_TPC.C File Reference
#include <GlobalVariables.C>
#include <QA.C>
#include <G4_Intt.C>
#include <G4_Mvtx.C>
#include <g4tpc/PHG4TpcDigitizer.h>
#include <g4tpc/PHG4TpcDistortion.h>
#include <g4tpc/PHG4TpcElectronDrift.h>
#include <g4tpc/PHG4TpcEndCapSubsystem.h>
#include <g4tpc/PHG4TpcPadPlane.h>
#include <g4tpc/PHG4TpcPadPlaneReadout.h>
#include <g4tpc/PHG4TpcSubsystem.h>
#include <g4main/PHG4Reco.h>
#include <tpc/TpcClusterizer.h>
#include <tpc/TpcClusterCleaner.h>
#include <tpc/TpcSpaceChargeCorrection.h>
#include <qa_modules/QAG4SimulationTpc.h>
#include <fun4all/Fun4AllServer.h>
Namespaces
namespace Enable
namespace G4TPC
Macros
#define MACRO_G4TPC_C
Functions
void TPCInit ()
void TPC_Endcaps (PHG4Reco *g4Reco)
TPC end cap, wagon wheel, electronics.
double TPC (PHG4Reco *g4Reco, double radius)
void TPC_Cells ()
void TPC_Clustering ()
void TPC_QA ()
Variables
bool Enable::TPC = false
bool Enable::TPC_ABSORBER = false
bool Enable::TPC_OVERLAPCHECK = false
bool Enable::TPC_CELL = false
bool Enable::TPC_CLUSTER = false
bool Enable::TPC_QA = false
bool Enable::TPC_ENDCAP = true
int Enable::TPC_VERBOSITY = 0
int G4TPC::n_tpc_layer_inner = 16
int G4TPC::tpc_layer_rphi_count_inner = 1152
int G4TPC::n_tpc_layer_mid = 16
int G4TPC::n_tpc_layer_outer = 16
int G4TPC::n_gas_layer = n_tpc_layer_inner + n_tpc_layer_mid + n_tpc_layer_outer
double G4TPC::tpc_outer_radius = 77. + 2.
bool G4TPC::ENABLE_STATIC_DISTORTIONS = false
auto G4TPC::static_distortion_filename = std::string(getenv("CALIBRATIONROOT")) + "/TPC/DistortionMaps/fluct_average.rev3.1side.3d.file0.h_negz.real_B1.4_E-400.0.ross_phi1_sphenix_phislice_lookup_r26xp40xz40.distortion_map.hist.root"
bool G4TPC::ENABLE_TIME_ORDERED_DISTORTIONS = false
std::string G4TPC::time_ordered_distortion_filename = "/gpfs/mnt/gpfs02/sphenix/user/klest/TimeOrderedDistortions.root"
bool G4TPC::ENABLE_CORRECTIONS = false
auto G4TPC::correction_filename = std::string(getenv("CALIBRATIONROOT")) + "/TPC/DistortionMaps/fluct_average.rev3.1side.3d.file0.h_negz.real_B1.4_E-400.0.ross_phi1_sphenix_phislice_lookup_r26xp40xz40.distortion_map.hist.root"
unsigned int G4TPC::correction_coordinates
Macro Definition Documentation
#define MACRO_G4TPC_C
Definition at line 2 of file G4_TPC.C.
View newest version in sPHENIX GitHub at line 2 of file G4_TPC.C
Function Documentation
double TPC (PHG4Reco * g4Reco, double radius)
Definition at line 123 of file G4_TPC.C.
View newest version in sPHENIX GitHub at line 123 of file G4_TPC.C
References Enable::ABSORBER, no_overlapp, PHG4DetectorSubsystem::OverlapCheck(), Enable::OVERLAPCHECK, PHG4Reco::registerSubsystem(), PHG4DetectorSubsystem::set_double_param(), PHG4DetectorSubsystem::SetAbsorberActive(), PHG4DetectorSubsystem::SetActive(), PHG4DetectorSubsystem::SuperDetector(), Enable::TPC_ABSORBER, Enable::TPC_ENDCAP, TPC_Endcaps(), G4TPC::tpc_outer_radius, and Enable::TPC_OVERLAPCHECK.
void TPC_Cells ()
Definition at line 154 of file G4_TPC.C.
View newest version in sPHENIX GitHub at line 154 of file G4_TPC.C
References PHG4TpcElectronDrift::Detector(), G4TPC::ENABLE_STATIC_DISTORTIONS, G4TPC::ENABLE_TIME_ORDERED_DISTORTIONS, Fun4AllServer::instance(), max, G4INTT::n_intt_layer, G4MVTX::n_maps_layer, G4TPC::n_tpc_layer_inner, PHG4TpcElectronDrift::registerPadPlane(), Fun4AllServer::registerSubsystem(), PHG4TpcDistortion::set_do_static_distortions(), PHParameterInterface::set_int_param(), PHG4TpcDigitizer::SetADCThreshold(), PHG4TpcDigitizer::SetENC(), PHG4TpcElectronDrift::setTpcDistortion(), PHG4TpcDigitizer::SetTpcMinLayer(), G4TPC::static_distortion_filename, G4TPC::time_ordered_distortion_filename, G4TPC::tpc_layer_rphi_count_inner, Enable::TPC_VERBOSITY, verbosity, Enable::VERBOSITY, and Fun4AllBase::Verbosity().
Referenced by Fun4All_AnaTutorial_sPHENIX(), Fun4All_AnaTutorial_sPHENIX_Jets(), and Fun4All_G4_sPHENIX().
void TPC_Clustering ()
Definition at line 212 of file G4_TPC.C.
View newest version in sPHENIX GitHub at line 212 of file G4_TPC.C
References G4TPC::correction_coordinates, G4TPC::correction_filename, G4TPC::ENABLE_CORRECTIONS, Fun4AllServer::instance(), max, Fun4AllServer::registerSubsystem(), TpcSpaceChargeCorrection::set_distortion_filename(), Enable::TPC_VERBOSITY, verbosity, Enable::VERBOSITY, and Fun4AllBase::Verbosity().
Referenced by Fun4All_AnaTutorial_sPHENIX(), Fun4All_AnaTutorial_sPHENIX_Jets(), and Fun4All_G4_sPHENIX().
void TPC_Endcaps (PHG4Reco * g4Reco)
TPC end cap, wagon wheel, electronics.
Definition at line 105 of file G4_TPC.C.
View newest version in sPHENIX GitHub at line 105 of file G4_TPC.C
References Enable::ABSORBER, Enable::OVERLAPCHECK, PHG4DetectorSubsystem::OverlapCheck(), PHG4Reco::registerSubsystem(), PHG4DetectorSubsystem::SetActive(), PHG4DetectorSubsystem::SuperDetector(), Enable::TPC_ABSORBER, and Enable::TPC_OVERLAPCHECK.
Referenced by TPC().
void TPC_QA ()
Definition at line 244 of file G4_TPC.C.
View newest version in sPHENIX GitHub at line 244 of file G4_TPC.C
References Fun4AllServer::instance(), max, Enable::QA_VERBOSITY, Fun4AllServer::registerSubsystem(), Enable::TPC_VERBOSITY, verbosity, and Fun4AllBase::Verbosity().
Referenced by Fun4All_AnaTutorial_sPHENIX(), Fun4All_AnaTutorial_sPHENIX_Jets(), and Fun4All_G4_sPHENIX().
void TPCInit ()
Definition at line 76 of file G4_TPC.C.
View newest version in sPHENIX GitHub at line 76 of file G4_TPC.C
References Enable::INTT, max, BlackHoleGeometry::max_radius, BlackHoleGeometry::max_z, min, BlackHoleGeometry::min_z, Enable::MVTX, G4INTT::n_intt_layer, G4MVTX::n_maps_layer, Enable::TPC_ENDCAP, and G4TPC::tpc_outer_radius.