Analysis Software: analysis/blob/master/EICAnalysis/macros/leptoquarks_fun4all/G4_EEMC.C File Reference
G4_EEMC.C File Reference
Functions
void EEMCInit ()
void EEMC_Cells (int verbosity=0)
void EEMCSetup (PHG4Reco *g4Reco, const int absorberactive=0)
void EEMC_Towers (int verbosity=0)
void EEMC_Clusters (int verbosity=0)
void EEMC_Eval (std::string outputfile, int verbosity=0)
Function Documentation
void EEMC_Cells (int verbosity = 0)
Definition at line 8 of file G4_EEMC.C.
View newest version in sPHENIX GitHub at line 8 of file G4_EEMC.C
References Fun4AllServer::instance(), and Fun4AllServer::registerSubsystem().
Referenced by Fun4All_G4_EICDetector_LQ(), Fun4All_G4_EICDetector_LQ_reference(), and Fun4All_G4_EICDetector_RICH().
void EEMC_Clusters (int verbosity = 0)
Definition at line 97 of file G4_EEMC.C.
View newest version in sPHENIX GitHub at line 97 of file G4_EEMC.C
References Fun4AllServer::instance(), Fun4AllServer::registerSubsystem(), and verbosity.
Referenced by Fun4All_G4_EICDetector_AnaTutorial(), Fun4All_G4_EICDetector_LQ(), Fun4All_G4_EICDetector_LQ_reference(), and Fun4All_G4_EICDetector_RICH().
void EEMC_Eval (std::string outputfile, int verbosity = 0)
Definition at line 111 of file G4_EEMC.C.
View newest version in sPHENIX GitHub at line 111 of file G4_EEMC.C
References Fun4AllServer::instance(), Fun4AllServer::registerSubsystem(), verbosity, and Fun4AllBase::Verbosity().
Referenced by Fun4All_G4_EICDetector_AnaTutorial(), and Fun4All_G4_EICDetector_RICH().
void EEMC_Towers (int verbosity = 0)
Definition at line 47 of file G4_EEMC.C.
View newest version in sPHENIX GitHub at line 47 of file G4_EEMC.C
References RawTowerCalibration::Detector(), RawTowerBuilderByHitIndex::Detector(), RawTowerDigitizer::Detector(), RawTowerBuilderByHitIndex::GeometryTableFile(), Fun4AllServer::instance(), RawTowerCalibration::kSimple_linear_calibration, RawTowerDigitizer::kSimple_photon_digitization, Fun4AllServer::registerSubsystem(), RawTowerCalibration::set_calib_algorithm(), RawTowerCalibration::set_calib_const_GeV_ADC(), RawTowerDigitizer::set_digi_algorithm(), RawTowerCalibration::set_pedstal_ADC(), RawTowerDigitizer::set_pedstal_central_ADC(), RawTowerDigitizer::set_pedstal_width_ADC(), RawTowerDigitizer::set_photonelec_ADC(), RawTowerDigitizer::set_photonelec_yield_visible_GeV(), RawTowerDigitizer::set_raw_tower_node_prefix(), RawTowerBuilderByHitIndex::set_sim_tower_node_prefix(), RawTowerDigitizer::set_zero_suppression_ADC(), verbosity, and Fun4AllBase::Verbosity().
Referenced by Fun4All_G4_EICDetector_AnaTutorial(), Fun4All_G4_EICDetector_LQ(), Fun4All_G4_EICDetector_LQ_reference(), and Fun4All_G4_EICDetector_RICH().
void EEMCInit ()
Definition at line 4 of file G4_EEMC.C.
View newest version in sPHENIX GitHub at line 4 of file G4_EEMC.C
Referenced by G4Init().
void EEMCSetup (PHG4Reco * g4Reco, const int absorberactive = 0)
Use dedicated EEMC module
Definition at line 22 of file G4_EEMC.C.
View newest version in sPHENIX GitHub at line 22 of file G4_EEMC.C
References eemc, overlapcheck, and PHG4Reco::registerSubsystem().
Referenced by G4Setup().