Analysis Software: PHG4ParticleGenerator Class Reference
PHG4ParticleGenerator Class Reference
#include <coresoftware/blob/master/simulation/g4simulation/g4main/PHG4ParticleGenerator.h>
Public Member Functions
PHG4ParticleGenerator (const std::string &name="PGENERATOR")
~PHG4ParticleGenerator () override
int process_event (PHCompositeNode *topNode) override
void set_z_range (const double z_min, const double z_max)
void set_eta_range (const double eta_min, const double eta_max)
void set_phi_range (const double phi_min, const double phi_max)
void set_mom_range (const double mom_min, const double mom_max)
void Print (const std::string &what="ALL") const override
Public Member Functions inherited from PHG4ParticleGeneratorBase
~PHG4ParticleGeneratorBase () override
int InitRun (PHCompositeNode *topNode) override
int process_event (PHCompositeNode *topNode) override
virtual void set_name (const std::string &particle="proton")
virtual void set_pid (const int pid)
virtual void set_mom (const double x, const double y, const double z)
virtual void set_vtx (const double x, const double y, const double z)
virtual void set_vtx_z (const double z)
virtual void set_t0 (const double t)
virtual double get_vtx_x () const
virtual double get_vtx_y () const
virtual double get_vtx_z () const
virtual double get_t0 () const
void Print (const std::string &what="ALL") const override
virtual void PrintParticles (const std::string &what="ALL") const
virtual void AddParticle (const std::string &particle, const double x, const double y, const double z)
virtual void AddParticle (const int pid, const double x, const double y, const double z)
virtual void Embed (const int i=1)
virtual int ReuseExistingVertex (PHCompositeNode *topNode)
int get_reuse_existing_vertex () const
void set_reuse_existing_vertex (const int i=1)
void set_seed (const unsigned int iseed)
unsigned int get_seed () const
Public Member Functions inherited from SubsysReco
~SubsysReco () override
virtual int End (PHCompositeNode *)
Called at the end of all processing.
virtual int EndRun (const int)
Called at the end of each run.
virtual int Init (PHCompositeNode *)
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Protected Attributes
double m_ZMin = -10.
double m_ZMax = 10.
double m_EtaMin = -1.
double m_EtaMax = 1.
double m_PhiMin = -M_PI
double m_PhiMax = M_PI
double m_MomMin = 0.
double m_MomMax = 10.
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = std::numeric_limits<int>::max() - 10
}
Protected Member Functions inherited from PHG4ParticleGeneratorBase
PHG4ParticleGeneratorBase (const std::string &name="GENERATORBASE")
int get_pdgcode (const std::string &name) const
std::string get_pdgname (const int pdgcode) const
double get_mass (const int pdgcode) const
void CheckAndCreateParticleVector ()
void SetParticleId (PHG4Particle *particle, PHG4InEvent *ineve)
gsl_rng * RandomGenerator () const
int EmbedFlag () const
std::vector< PHG4Particle * >
::iterator particlelist_begin ()
std::vector< PHG4Particle * >
::iterator particlelist_end ()
void ResetParticleList ()
Detailed Description
Definition at line 13 of file PHG4ParticleGenerator.h.
View newest version in sPHENIX GitHub at line 13 of file PHG4ParticleGenerator.h
Constructor & Destructor Documentation
PHG4ParticleGenerator::PHG4ParticleGenerator (const std::string & name = "PGENERATOR")
Definition at line 17 of file PHG4ParticleGenerator.cc.
View newest version in sPHENIX GitHub at line 17 of file PHG4ParticleGenerator.cc
PHG4ParticleGenerator::~PHG4ParticleGenerator () inline override
Definition at line 17 of file PHG4ParticleGenerator.h.
View newest version in sPHENIX GitHub at line 17 of file PHG4ParticleGenerator.h
Member Function Documentation
void PHG4ParticleGenerator::Print (const std::string & what = "ALL") const override virtual
Print out some info about this module.
Parameters
what can be used to specify what to print exactly.
Reimplemented from SubsysReco.
Definition at line 91 of file PHG4ParticleGenerator.cc.
View newest version in sPHENIX GitHub at line 91 of file PHG4ParticleGenerator.cc
References m_EtaMax, m_EtaMin, m_MomMax, m_MomMin, m_PhiMax, m_PhiMin, m_ZMax, m_ZMin, and PHG4ParticleGeneratorBase::PrintParticles().
int PHG4ParticleGenerator::process_event (PHCompositeNode *) override virtual
Called for each event. This is where you do the real work.
Reimplemented from SubsysReco.
Definition at line 51 of file PHG4ParticleGenerator.cc.
View newest version in sPHENIX GitHub at line 51 of file PHG4ParticleGenerator.cc
References PHG4InEvent::AddParticle(), PHG4InEvent::AddVtx(), eta, PHG4Particle::get_e(), PHG4Particle::get_px(), PHG4Particle::get_py(), PHG4Particle::get_pz(), PHG4ParticleGeneratorBase::get_t0(), PHG4ParticleGeneratorBase::get_vtx_x(), PHG4ParticleGeneratorBase::get_vtx_y(), PHG4ParticleGeneratorBase::get_vtx_z(), PHG4InEvent::identify(), m_EtaMax, m_EtaMin, m_MomMax, m_MomMin, m_PhiMax, m_PhiMin, m_ZMax, m_ZMin, particle, PHG4ParticleGeneratorBase::particlelist_begin(), PHG4ParticleGeneratorBase::particlelist_end(), ActsTests::PropagationDatasets::phi, physmon_track_finding_ttbar::pt, PHG4ParticleGeneratorBase::RandomGenerator(), PHG4ParticleGeneratorBase::ReuseExistingVertex(), PHG4Particle::set_e(), PHG4Particle::set_px(), PHG4Particle::set_py(), PHG4Particle::set_pz(), PHG4ParticleGeneratorBase::set_vtx_z(), PHG4ParticleGeneratorBase::SetParticleId(), and Fun4AllBase::Verbosity().
void PHG4ParticleGenerator::set_eta_range (const double eta_min, const double eta_max)
Definition at line 30 of file PHG4ParticleGenerator.cc.
View newest version in sPHENIX GitHub at line 30 of file PHG4ParticleGenerator.cc
References m_EtaMax, m_EtaMin, and Acts::UnitConstants::min.
Referenced by Fun4All_EICAnalysis_DVCS(), Fun4All_G4_Calos(), Fun4All_G4_Cylinder(), Fun4All_G4_EICDetector_LQ(), Fun4All_G4_EICDetector_LQ_reference(), Fun4All_G4_EICDetector_RICH(), Fun4All_G4_Geantino(), Fun4All_G4_Momentum(), Fun4All_G4_Momentum_Projection(), Fun4All_G4_Momentum_Projection_Calorimeters(), Fun4All_G4_Momentum_Projection_Detectors(), Fun4All_G4_MyDetector(), Fun4All_G4_Prototype3(), Fun4All_G4_Prototype4(), Fun4All_G4_sPHENIX_photonjet(), Fun4All_G4_sPHENIX_photons(), Fun4All_G4_sPHENIX_truthphotonjet(), Fun4All_G4_Write_Dst(), Fun4All_Generator_Display(), and Fun4All_single_particle().
void PHG4ParticleGenerator::set_mom_range (const double mom_min, const double mom_max)
Definition at line 44 of file PHG4ParticleGenerator.cc.
View newest version in sPHENIX GitHub at line 44 of file PHG4ParticleGenerator.cc
References m_MomMax, m_MomMin, and Acts::UnitConstants::min.
Referenced by Fun4All_EICAnalysis_DVCS(), Fun4All_G4_Calos(), Fun4All_G4_Cylinder(), Fun4All_G4_EICDetector_LQ(), Fun4All_G4_EICDetector_LQ_reference(), Fun4All_G4_EICDetector_RICH(), Fun4All_G4_Geantino(), Fun4All_G4_Momentum(), Fun4All_G4_Momentum_Projection(), Fun4All_G4_Momentum_Projection_Calorimeters(), Fun4All_G4_Momentum_Projection_Detectors(), Fun4All_G4_MyDetector(), Fun4All_G4_Prototype3(), Fun4All_G4_Prototype4(), Fun4All_G4_sPHENIX_photonjet(), Fun4All_G4_sPHENIX_photons(), Fun4All_G4_sPHENIX_truthphotonjet(), Fun4All_G4_Write_Dst(), Fun4All_Generator_Display(), and Fun4All_single_particle().
void PHG4ParticleGenerator::set_phi_range (const double phi_min, const double phi_max)
Definition at line 37 of file PHG4ParticleGenerator.cc.
View newest version in sPHENIX GitHub at line 37 of file PHG4ParticleGenerator.cc
References m_PhiMax, m_PhiMin, and Acts::UnitConstants::min.
Referenced by Fun4All_EICAnalysis_DVCS(), Fun4All_G4_Calos(), Fun4All_G4_Cylinder(), Fun4All_G4_EICDetector_LQ(), Fun4All_G4_EICDetector_LQ_reference(), Fun4All_G4_EICDetector_RICH(), Fun4All_G4_Geantino(), Fun4All_G4_Momentum(), Fun4All_G4_Momentum_Projection(), Fun4All_G4_Momentum_Projection_Calorimeters(), Fun4All_G4_Momentum_Projection_Detectors(), Fun4All_G4_MyDetector(), Fun4All_G4_Prototype3(), Fun4All_G4_Prototype4(), Fun4All_G4_sPHENIX_photonjet(), Fun4All_G4_sPHENIX_photons(), Fun4All_G4_sPHENIX_truthphotonjet(), Fun4All_G4_Write_Dst(), Fun4All_Generator_Display(), and Fun4All_single_particle().
void PHG4ParticleGenerator::set_z_range (const double z_min, const double z_max)
Definition at line 23 of file PHG4ParticleGenerator.cc.
View newest version in sPHENIX GitHub at line 23 of file PHG4ParticleGenerator.cc
References m_ZMax, m_ZMin, and Acts::UnitConstants::min.
Referenced by Fun4All_EICAnalysis_DVCS(), Fun4All_G4_EICDetector_LQ(), Fun4All_G4_EICDetector_LQ_reference(), Fun4All_G4_EICDetector_RICH(), Fun4All_G4_Geantino(), Fun4All_G4_MyDetector(), Fun4All_G4_sPHENIX_photonjet(), Fun4All_G4_sPHENIX_photons(), Fun4All_G4_sPHENIX_truthphotonjet(), Fun4All_G4_Write_Dst(), Fun4All_Generator_Display(), and Fun4All_single_particle().
Member Data Documentation
double PHG4ParticleGenerator::m_EtaMax = 1. protected
Definition at line 30 of file PHG4ParticleGenerator.h.
View newest version in sPHENIX GitHub at line 30 of file PHG4ParticleGenerator.h
Referenced by Print(), process_event(), and set_eta_range().
double PHG4ParticleGenerator::m_EtaMin = -1. protected
Definition at line 29 of file PHG4ParticleGenerator.h.
View newest version in sPHENIX GitHub at line 29 of file PHG4ParticleGenerator.h
Referenced by Print(), process_event(), and set_eta_range().
double PHG4ParticleGenerator::m_MomMax = 10. protected
Definition at line 34 of file PHG4ParticleGenerator.h.
View newest version in sPHENIX GitHub at line 34 of file PHG4ParticleGenerator.h
Referenced by Print(), process_event(), and set_mom_range().
double PHG4ParticleGenerator::m_MomMin = 0. protected
Definition at line 33 of file PHG4ParticleGenerator.h.
View newest version in sPHENIX GitHub at line 33 of file PHG4ParticleGenerator.h
Referenced by Print(), process_event(), and set_mom_range().
double PHG4ParticleGenerator::m_PhiMax = M_PI protected
Definition at line 32 of file PHG4ParticleGenerator.h.
View newest version in sPHENIX GitHub at line 32 of file PHG4ParticleGenerator.h
Referenced by Print(), process_event(), and set_phi_range().
double PHG4ParticleGenerator::m_PhiMin = -M_PI protected
Definition at line 31 of file PHG4ParticleGenerator.h.
View newest version in sPHENIX GitHub at line 31 of file PHG4ParticleGenerator.h
Referenced by Print(), process_event(), and set_phi_range().
double PHG4ParticleGenerator::m_ZMax = 10. protected
Definition at line 28 of file PHG4ParticleGenerator.h.
View newest version in sPHENIX GitHub at line 28 of file PHG4ParticleGenerator.h
Referenced by Print(), process_event(), and set_z_range().
double PHG4ParticleGenerator::m_ZMin = -10. protected
Definition at line 27 of file PHG4ParticleGenerator.h.
View newest version in sPHENIX GitHub at line 27 of file PHG4ParticleGenerator.h
Referenced by Print(), process_event(), and set_z_range().
The documentation for this class was generated from the following files:
coresoftware/blob/master/simulation/g4simulation/g4main/PHG4ParticleGenerator.h
coresoftware/blob/master/simulation/g4simulation/g4main/PHG4ParticleGenerator.cc