Analysis Software: acts/blob/sPHENIX/Tests/UnitTests/Core/Seeding/SeedFinderTest.cpp File Reference
SeedFinderTest.cpp File Reference
#include "Acts/Definitions/Algebra.hpp"
#include "Acts/Definitions/Units.hpp"
#include "Acts/Geometry/Extent.hpp"
#include "Acts/Seeding/BinFinder.hpp"
#include "Acts/Seeding/BinnedSPGroup.hpp"
#include "Acts/Seeding/Seed.hpp"
#include "Acts/Seeding/SeedFilter.hpp"
#include "Acts/Seeding/SeedFilterConfig.hpp"
#include "Acts/Seeding/SeedFinder.hpp"
#include "Acts/Seeding/SeedFinderConfig.hpp"
#include "Acts/Seeding/SpacePointGrid.hpp"
#include "Acts/Utilities/Range1D.hpp"
#include "Acts/Utilities/detail/Grid.hpp"
#include <algorithm>
#include <chrono>
#include <cmath>
#include <cstdlib>
#include <fstream>
#include <iostream>
#include <iterator>
#include <memory>
#include <string>
#include <tuple>
#include <utility>
#include <vector>
#include "ATLASCuts.hpp"
#include "SpacePoint.hpp"
Functions
std::vector< const SpacePoint * > readFile (const std::string &filename)
int main (int argc, char **argv)
Function Documentation
int main (int argc, char ** argv)
Definition at line 82 of file SeedFinderTest.cpp.
View newest version in sPHENIX GitHub at line 82 of file SeedFinderTest.cpp
References KFPMath::a, Acts::SeedFinderOptions::beamPos, Acts::SpacePointGridOptions::bFieldInZ, Acts::SeedFinderOptions::bFieldInZ, Acts::SeedFinderConfig< SpacePoint >::collisionRegionMax, Acts::SeedFinderConfig< SpacePoint >::collisionRegionMin, filter::config, Acts::SeedFinderConfig< SpacePoint >::cotThetaMax, Acts::SpacePointGridConfig::cotThetaMax, covariance(), Acts::SeedFinder< external_spacepoint_t, platform_t >::createSeedsForGroup(), Acts::SpacePointGridConfig::deltaRMax, Acts::SeedFinderConfig< SpacePoint >::deltaRMax, Acts::SeedFinderConfig< SpacePoint >::deltaRMaxBottomSP, Acts::SeedFinderConfig< SpacePoint >::deltaRMaxTopSP, Acts::SeedFinderConfig< SpacePoint >::deltaRMin, Acts::SeedFinderConfig< SpacePoint >::deltaRMinBottomSP, Acts::SeedFinderConfig< SpacePoint >::deltaRMinTopSP, end, f, file, grid(), parse_cmake_options::help, i, Acts::SeedFinderConfig< SpacePoint >::impactMax, SpacePoint::layer, Acts::SeedFinderConfig< SpacePoint >::maxSeedsPerSpM, Acts::SpacePointGridConfig::minPt, Acts::SeedFinderConfig< SpacePoint >::minPt, testing::internal::move(), ckf::options, position, quiet, readFile(), Acts::SpacePointGridConfig::rMax, Acts::SeedFinderConfig< SpacePoint >::rMax, seed, Acts::SeedFinderConfig< SpacePoint >::seedFilter, Acts::SeedFinderConfig< SpacePoint >::sigmaScattering, Acts::BinnedSPGroup< external_spacepoint_t >::size(), Acts::Seed< SpacePoint >::sp(), start, filter::state, Acts::SeedFinderConfig< SpacePoint >::useVariableMiddleSPRange, testSigmaEff::v, SpacePoint::varianceR, SpacePoint::varianceZ, SpacePoint::x, SpacePoint::y, SpacePoint::z, Acts::SpacePointGridConfig::zMax, Acts::SeedFinderConfig< SpacePoint >::zMax, Acts::SpacePointGridConfig::zMin, and Acts::SeedFinderConfig< SpacePoint >::zMin.
std::vector<const SpacePoint*> readFile (const std::string & filename)
Definition at line 41 of file SeedFinderTest.cpp.
View newest version in sPHENIX GitHub at line 41 of file SeedFinderTest.cpp
References Acts::Test::cov, layer, line, physmon_track_finding_ttbar::r, ambiguity_solver_full_chain::x, y, and physmon_track_finding_ttbar::z.
Referenced by main().