Analysis Software: SvtxTrackMap_v2 Class Reference
SvtxTrackMap_v2 Class Reference
#include <coresoftware/blob/master/offline/packages/trackbase_historic/SvtxTrackMap_v2.h>
Public Member Functions
SvtxTrackMap_v2 ()
SvtxTrackMap_v2 (const SvtxTrackMap_v2 &trackmap)
SvtxTrackMap_v2 & operator= (const SvtxTrackMap_v2 &trackmap)
~SvtxTrackMap_v2 () override
void identify (std::ostream &os=std::cout) const override
void Reset () override
Clear Event.
int isValid () const override
isValid returns non zero if object contains vailid data
PHObject * CloneMe () const override
Virtual copy constructor.
bool empty () const override
size_t size () const override
size_t count (unsigned int idkey) const override
void clear () override
const SvtxTrack * get (unsigned int idkey) const override
SvtxTrack * get (unsigned int idkey) override
SvtxTrack * insert (const SvtxTrack *track) override
SvtxTrack * insertWithKey (const SvtxTrack *track, unsigned int index) override
size_t erase (unsigned int idkey) override
ConstIter begin () const override
ConstIter find (unsigned int idkey) const override
ConstIter end () const override
Iter begin () override
Iter find (unsigned int idkey) override
Iter end () override
Public Member Functions inherited from SvtxTrackMap
~SvtxTrackMap () override
Public Member Functions inherited from PHObject
PHObject ()
ctor
~PHObject () override
dtor
virtual PHObject * clone () const final
PHObject * Clone (const char *newname="") const final
void Copy (TObject &object) const final
virtual int Integrate () const
virtual int Integrate (PHObject *)
virtual void CopyFrom (const PHObject *obj)
Private Member Functions
ClassDefOverride (SvtxTrackMap_v2, 2)
Private Attributes
TrackMap _map
Additional Inherited Members
Public Types inherited from SvtxTrackMap
typedef std::map< unsigned int,
SvtxTrack * > TrackMap
typedef std::map< unsigned int,
SvtxTrack * >::const_iterator ConstIter
typedef std::map< unsigned int,
SvtxTrack * >::iterator Iter
Protected Member Functions inherited from SvtxTrackMap
SvtxTrackMap ()
Detailed Description
Definition at line 12 of file SvtxTrackMap_v2.h.
View newest version in sPHENIX GitHub at line 12 of file SvtxTrackMap_v2.h
Constructor & Destructor Documentation
SvtxTrackMap_v2::SvtxTrackMap_v2 ()
Definition at line 12 of file SvtxTrackMap_v2.cc.
View newest version in sPHENIX GitHub at line 12 of file SvtxTrackMap_v2.cc
Referenced by CloneMe().
SvtxTrackMap_v2::SvtxTrackMap_v2 (const SvtxTrackMap_v2 & trackmap)
Definition at line 17 of file SvtxTrackMap_v2.cc.
View newest version in sPHENIX GitHub at line 17 of file SvtxTrackMap_v2.cc
References _map, begin(), and end().
SvtxTrackMap_v2::~SvtxTrackMap_v2 () override
Definition at line 46 of file SvtxTrackMap_v2.cc.
View newest version in sPHENIX GitHub at line 46 of file SvtxTrackMap_v2.cc
References Reset().
Member Function Documentation
ConstIter SvtxTrackMap_v2::begin (void) const inline override virtual
Reimplemented from SvtxTrackMap.
Definition at line 41 of file SvtxTrackMap_v2.h.
View newest version in sPHENIX GitHub at line 41 of file SvtxTrackMap_v2.h
References _map.
Referenced by operator=(), and SvtxTrackMap_v2().
Iter SvtxTrackMap_v2::begin (void) inline override virtual
Reimplemented from SvtxTrackMap.
Definition at line 45 of file SvtxTrackMap_v2.h.
View newest version in sPHENIX GitHub at line 45 of file SvtxTrackMap_v2.h
References _map.
SvtxTrackMap_v2::ClassDefOverride (SvtxTrackMap_v2 , 2) private
void SvtxTrackMap_v2::clear () inline override virtual
Reimplemented from SvtxTrackMap.
Definition at line 29 of file SvtxTrackMap_v2.h.
View newest version in sPHENIX GitHub at line 29 of file SvtxTrackMap_v2.h
References Reset().
PHObject* SvtxTrackMap_v2::CloneMe () const inline override virtual
Virtual copy constructor.
Reimplemented from SvtxTrackMap.
Definition at line 24 of file SvtxTrackMap_v2.h.
View newest version in sPHENIX GitHub at line 24 of file SvtxTrackMap_v2.h
References SvtxTrackMap_v2().
size_t SvtxTrackMap_v2::count (unsigned int idkey) const inline override virtual
Reimplemented from SvtxTrackMap.
Definition at line 28 of file SvtxTrackMap_v2.h.
View newest version in sPHENIX GitHub at line 28 of file SvtxTrackMap_v2.h
References _map.
bool SvtxTrackMap_v2::empty () const inline override virtual
Reimplemented from SvtxTrackMap.
Definition at line 26 of file SvtxTrackMap_v2.h.
View newest version in sPHENIX GitHub at line 26 of file SvtxTrackMap_v2.h
References _map.
ConstIter SvtxTrackMap_v2::end (void) const inline override virtual
Reimplemented from SvtxTrackMap.
Definition at line 43 of file SvtxTrackMap_v2.h.
View newest version in sPHENIX GitHub at line 43 of file SvtxTrackMap_v2.h
References _map.
Referenced by operator=(), and SvtxTrackMap_v2().
Iter SvtxTrackMap_v2::end (void) inline override virtual
Reimplemented from SvtxTrackMap.
Definition at line 47 of file SvtxTrackMap_v2.h.
View newest version in sPHENIX GitHub at line 47 of file SvtxTrackMap_v2.h
References _map.
size_t SvtxTrackMap_v2::erase (unsigned int idkey) inline override virtual
Reimplemented from SvtxTrackMap.
Definition at line 35 of file SvtxTrackMap_v2.h.
View newest version in sPHENIX GitHub at line 35 of file SvtxTrackMap_v2.h
References _map.
ConstIter SvtxTrackMap_v2::find (unsigned int idkey) const inline override virtual
Reimplemented from SvtxTrackMap.
Definition at line 42 of file SvtxTrackMap_v2.h.
View newest version in sPHENIX GitHub at line 42 of file SvtxTrackMap_v2.h
References _map.
Iter SvtxTrackMap_v2::find (unsigned int idkey) inline override virtual
Reimplemented from SvtxTrackMap.
Definition at line 46 of file SvtxTrackMap_v2.h.
View newest version in sPHENIX GitHub at line 46 of file SvtxTrackMap_v2.h
References _map.
const SvtxTrack * SvtxTrackMap_v2::get (unsigned int idkey) const override virtual
Reimplemented from SvtxTrackMap.
Definition at line 69 of file SvtxTrackMap_v2.cc.
View newest version in sPHENIX GitHub at line 69 of file SvtxTrackMap_v2.cc
References _map.
SvtxTrack * SvtxTrackMap_v2::get (unsigned int idkey) override virtual
Reimplemented from SvtxTrackMap.
Definition at line 76 of file SvtxTrackMap_v2.cc.
View newest version in sPHENIX GitHub at line 76 of file SvtxTrackMap_v2.cc
References _map.
void SvtxTrackMap_v2::identify (std::ostream & os = std::cout) const override virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from SvtxTrackMap.
Definition at line 63 of file SvtxTrackMap_v2.cc.
View newest version in sPHENIX GitHub at line 63 of file SvtxTrackMap_v2.cc
References _map.
SvtxTrack * SvtxTrackMap_v2::insert (const SvtxTrack * track) override virtual
Reimplemented from SvtxTrackMap.
Definition at line 83 of file SvtxTrackMap_v2.cc.
View newest version in sPHENIX GitHub at line 83 of file SvtxTrackMap_v2.cc
References _map, SvtxTrack::CloneMe(), index, and SvtxTrack::set_id().
SvtxTrack * SvtxTrackMap_v2::insertWithKey (const SvtxTrack * track, unsigned int index) override virtual
Reimplemented from SvtxTrackMap.
Definition at line 101 of file SvtxTrackMap_v2.cc.
View newest version in sPHENIX GitHub at line 101 of file SvtxTrackMap_v2.cc
References _map, SvtxTrack::CloneMe(), and SvtxTrack::set_id().
int SvtxTrackMap_v2::isValid () const inline override virtual
isValid returns non zero if object contains vailid data
Reimplemented from SvtxTrackMap.
Definition at line 23 of file SvtxTrackMap_v2.h.
View newest version in sPHENIX GitHub at line 23 of file SvtxTrackMap_v2.h
SvtxTrackMap_v2 & SvtxTrackMap_v2::operator= (const SvtxTrackMap_v2 & trackmap)
Definition at line 29 of file SvtxTrackMap_v2.cc.
View newest version in sPHENIX GitHub at line 29 of file SvtxTrackMap_v2.cc
References _map, begin(), end(), and Reset().
void SvtxTrackMap_v2::Reset () override virtual
Clear Event.
Reimplemented from PHObject.
Definition at line 51 of file SvtxTrackMap_v2.cc.
View newest version in sPHENIX GitHub at line 51 of file SvtxTrackMap_v2.cc
References _map.
Referenced by clear(), operator=(), and ~SvtxTrackMap_v2().
size_t SvtxTrackMap_v2::size (void) const inline override virtual
Reimplemented from SvtxTrackMap.
Definition at line 27 of file SvtxTrackMap_v2.h.
View newest version in sPHENIX GitHub at line 27 of file SvtxTrackMap_v2.h
References _map.
Member Data Documentation
TrackMap SvtxTrackMap_v2::_map private
Definition at line 50 of file SvtxTrackMap_v2.h.
View newest version in sPHENIX GitHub at line 50 of file SvtxTrackMap_v2.h
Referenced by begin(), count(), empty(), end(), erase(), find(), get(), identify(), insert(), insertWithKey(), operator=(), Reset(), size(), and SvtxTrackMap_v2().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/trackbase_historic/SvtxTrackMap_v2.h
coresoftware/blob/master/offline/packages/trackbase_historic/SvtxTrackMap_v2.cc