Analysis Software: acts/blob/sPHENIX/Examples/Scripts/MaterialMapping/Mat_map_detector_plot.C File Reference
Mat_map_detector_plot.C File Reference
#include <TROOT.h>
#include "materialPlotHelper.cpp"
#include <fstream>
#include <iostream>
#include <sstream>
Functions
void plot (std::vector< TH2F * > Map, std::vector< int > detectors, const std::string &name)
Draw and save the histograms.
void Initialise_hist (std::vector< TH2F * > &detector_hist)
Initialise the histograms for the detector.
void Fill (std::vector< TH2F * > &detector_hist, const std::string &input_file, std::vector< int > detectors, const int &nbprocess)
Fill the histograms for the detector.
void Mat_map_detector_plot (std::string input_file="", std::vector< int > detectors=vector< int >(), int nbprocess=-1, std::string name="")
Function Documentation
void Fill (std::vector< TH2F * > & detector_hist, const std::string & input_file, std::vector< int > detectors, const int & nbprocess)
Fill the histograms for the detector.
Definition at line 100 of file Mat_map_detector_plot.C.
View newest version in sPHENIX GitHub at line 100 of file Mat_map_detector_plot.C
References i, Initialise_hist(), j, tfile, tree, and Acts::GeometryIdentifier::volume().
Referenced by SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::AddECal(), SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::AddFlow(), SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::AddHCal(), SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::AddParticles(), SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::AddTracks(), analyzeClusterEtIso(), SDeltaPtCutStudy::ApplyFlatDeltaPtCuts(), SDeltaPtCutStudy::ApplyPtDependentDeltaPtCuts(), Fe55::BaLiS(), Bias::Bias(), CalculateSigmaDca(), ccbb(), hLabHelper::collect(), hcalHelper::collectRaw(), tileHelper::collectTileSummary(), crossterms(), SColdQcdCorrelatorAnalysis::SEnergyCorrelator::DoCorrelatorCalculation(), SColdQcdCorrelatorAnalysis::SCheckTrackPairs::DoDoubleTrackLoop(), tileHelper::evLoop(), fakee_invmass(), STrackMatcherComparator::FillHistogram1D(), STrackMatcherComparator::FillHistogram2D(), SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::FillRecoTree(), STrackCutStudy::FillTrackHistograms(), SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::FillTrueTree(), SDeltaPtCutStudy::FillTruthHistograms(), STrackCutStudy::FillTruthHistograms(), stack::getStackImpact(), stack::getStackTime(), stack::getStackTrack(), tileHelper::getYFit(), isIso(), MakeNewMatcherPlots(), MakeNewMatcherTuplePlots(), MakeOldEvaluatorPlots(), Mat_map_detector_plot(), Mat_map_detector_plot_ratio(), Mat_map_surface_plot(), Mat_map_surface_plot_1D(), Mat_map_surface_plot_dist(), Mat_map_surface_plot_ratio(), CemcMon::process_event(), TpcMon::process_event(), LEDTowerBuilder::process_event(), Quarkonia2LeptonsMC::process_event(), DirectPhotonPythia::process_event(), HFMLTriggerOccupancy::process_event(), mbdAnalysis::process_event(), jetHistogrammer::process_event(), isoCluster::process_event(), pi0ClusterAna::process_event(), singlePhotonClusterAna::process_event(), quickHIJING::process_event(), caloTreeGen::process_event(), ElectronID::process_event(), pythiaEMCalAna::process_event(), pi0Efficiency::process_event(), PHTpcCentralMembraneMatcher::process_event(), cemcReco::process_event(), QuickDeltaPtExtractor(), tile(), tileHelper::tileImpact(), tileHelper::tileTrigger(), hcal::update(), stack::update(), and tower::update().
void Initialise_hist (std::vector< TH2F * > & detector_hist)
Initialise the histograms for the detector.
Definition at line 73 of file Mat_map_detector_plot.C.
View newest version in sPHENIX GitHub at line 73 of file Mat_map_detector_plot.C
Referenced by Fill().
void Mat_map_detector_plot (std::string input_file = "", std::vector< int > detectors = vector<int>(), int nbprocess = -1, std::string name = "")
Plot the material as function of eta and phi for a given detector/sub-detector detectors : list of the ID of the volume constitutive of the detector/sub-detector nbprocess : number of parameter to be processed. name : name of the output directory.
Definition at line 177 of file Mat_map_detector_plot.C.
View newest version in sPHENIX GitHub at line 177 of file Mat_map_detector_plot.C
References detectors, Fill(), perf_headwind::input_file, perf_headwind::name, and plot().
void plot (std::vector< TH2F * > Map, std::vector< int > detectors, const std::string & name)
Draw and save the histograms.
Definition at line 19 of file Mat_map_detector_plot.C.
View newest version in sPHENIX GitHub at line 19 of file Mat_map_detector_plot.C
References c2, and to_string().
Referenced by Mat_map_detector_plot(), Mat_map_detector_plot_ratio(), Mat_map_surface_plot(), Mat_map_surface_plot_1D(), Mat_map_surface_plot_dist(), and Mat_map_surface_plot_ratio().