Analysis Software: SVM_v1 Namespace Reference
SVM_v1 Namespace Reference
Variables
tuple csv_e np.genfromtxt('testdata/set001/CalorimeterResponseHijingCentralRapidity_e_8GeV.csv')
tuple csv_pi np.genfromtxt('testdata/set001/CalorimeterResponseHijingCentralRapidity_pi_8GeV.csv')
list data_e_sub csv_e[:,2:5]
list data_pi_sub csv_pi[:,2:5]
list data_e_train data_e_sub[0:500,:]
list data_e_test data_e_sub[500:1000,:]
list data_pi_train data_pi_sub[0:500,:]
list data_pi_test data_pi_sub[500:1000,:]
tuple data_train np.vstack((data_e_train,data_pi_train))
tuple data_test np.vstack((data_pi_test,data_e_test))
int id_pi 0
int id_e 1
tuple pid_train np.vstack((np.ones((500,1)) , np.zeros((500,1))))
tuple pid_test np.vstack((np.zeros((500,1)) , np.ones((500,1))))
list X data_train[:,1:3]
tuple y np.ravel(pid_train)
int h 001
float C 1.0
tuple svc svm.SVC(kernel='linear', C=C)
tuple rbf_svc svm.SVC(kernel='rbf', gamma=0.7, C=C)
tuple poly_svc svm.SVC(kernel='poly', degree=3, C=C)
tuple lin_svc svm.LinearSVC(C=C)
list titles
tuple Z clf.predict(np.c_[xx.ravel(), yy.ravel()])
tuple pid_predict clf.predict(data_test[:,1:3])
int count_all 0
int count_electron_as_electron 0
int count_pion_as_pion 0
int count_electron_as_pion 0
int count_pion_as_electron 0
int count_true_electron 0
int count_true_pion 0
Variable Documentation
float SVM_v1.C 1.0
Definition at line 47 of file SVM_v1.py.
View newest version in sPHENIX GitHub at line 47 of file SVM_v1.py
int SVM_v1.count_all 0
Definition at line 95 of file SVM_v1.py.
View newest version in sPHENIX GitHub at line 95 of file SVM_v1.py
int SVM_v1.count_electron_as_electron 0
Definition at line 96 of file SVM_v1.py.
View newest version in sPHENIX GitHub at line 96 of file SVM_v1.py
int SVM_v1.count_electron_as_pion 0
Definition at line 98 of file SVM_v1.py.
View newest version in sPHENIX GitHub at line 98 of file SVM_v1.py
int SVM_v1.count_pion_as_electron 0
Definition at line 99 of file SVM_v1.py.
View newest version in sPHENIX GitHub at line 99 of file SVM_v1.py
int SVM_v1.count_pion_as_pion 0
Definition at line 97 of file SVM_v1.py.
View newest version in sPHENIX GitHub at line 97 of file SVM_v1.py
int SVM_v1.count_true_electron 0
Definition at line 100 of file SVM_v1.py.
View newest version in sPHENIX GitHub at line 100 of file SVM_v1.py
int SVM_v1.count_true_pion 0
Definition at line 101 of file SVM_v1.py.
View newest version in sPHENIX GitHub at line 101 of file SVM_v1.py
tuple SVM_v1.csv_e np.genfromtxt('testdata/set001/CalorimeterResponseHijingCentralRapidity_e_8GeV.csv')
Definition at line 13 of file SVM_v1.py.
View newest version in sPHENIX GitHub at line 13 of file SVM_v1.py
tuple SVM_v1.csv_pi np.genfromtxt('testdata/set001/CalorimeterResponseHijingCentralRapidity_pi_8GeV.csv')
Definition at line 14 of file SVM_v1.py.
View newest version in sPHENIX GitHub at line 14 of file SVM_v1.py
list SVM_v1.data_e_sub csv_e[:,2:5]
Definition at line 21 of file SVM_v1.py.
View newest version in sPHENIX GitHub at line 21 of file SVM_v1.py
list SVM_v1.data_e_test data_e_sub[500:1000,:]
Definition at line 26 of file SVM_v1.py.
View newest version in sPHENIX GitHub at line 26 of file SVM_v1.py
list SVM_v1.data_e_train data_e_sub[0:500,:]
Definition at line 25 of file SVM_v1.py.
View newest version in sPHENIX GitHub at line 25 of file SVM_v1.py
list SVM_v1.data_pi_sub csv_pi[:,2:5]
Definition at line 22 of file SVM_v1.py.
View newest version in sPHENIX GitHub at line 22 of file SVM_v1.py
list SVM_v1.data_pi_test data_pi_sub[500:1000,:]
Definition at line 29 of file SVM_v1.py.
View newest version in sPHENIX GitHub at line 29 of file SVM_v1.py
list SVM_v1.data_pi_train data_pi_sub[0:500,:]
Definition at line 28 of file SVM_v1.py.
View newest version in sPHENIX GitHub at line 28 of file SVM_v1.py
tuple SVM_v1.data_test np.vstack((data_pi_test,data_e_test))
Definition at line 33 of file SVM_v1.py.
View newest version in sPHENIX GitHub at line 33 of file SVM_v1.py
tuple SVM_v1.data_train np.vstack((data_e_train,data_pi_train))
Definition at line 32 of file SVM_v1.py.
View newest version in sPHENIX GitHub at line 32 of file SVM_v1.py
int SVM_v1.h 001
Definition at line 44 of file SVM_v1.py.
View newest version in sPHENIX GitHub at line 44 of file SVM_v1.py
int SVM_v1.id_e 1
Definition at line 37 of file SVM_v1.py.
View newest version in sPHENIX GitHub at line 37 of file SVM_v1.py
Referenced by fjetResol(), and likelihood().
int SVM_v1.id_pi 0
Definition at line 36 of file SVM_v1.py.
View newest version in sPHENIX GitHub at line 36 of file SVM_v1.py
tuple SVM_v1.lin_svc svm.LinearSVC(C=C)
Definition at line 51 of file SVM_v1.py.
View newest version in sPHENIX GitHub at line 51 of file SVM_v1.py
tuple SVM_v1.pid_predict clf.predict(data_test[:,1:3])
Definition at line 92 of file SVM_v1.py.
View newest version in sPHENIX GitHub at line 92 of file SVM_v1.py
tuple SVM_v1.pid_test np.vstack((np.zeros((500,1)) , np.ones((500,1))))
Definition at line 39 of file SVM_v1.py.
View newest version in sPHENIX GitHub at line 39 of file SVM_v1.py
tuple SVM_v1.pid_train np.vstack((np.ones((500,1)) , np.zeros((500,1))))
Definition at line 38 of file SVM_v1.py.
View newest version in sPHENIX GitHub at line 38 of file SVM_v1.py
tuple SVM_v1.poly_svc svm.SVC(kernel='poly', degree=3, C=C)
Definition at line 50 of file SVM_v1.py.
View newest version in sPHENIX GitHub at line 50 of file SVM_v1.py
tuple SVM_v1.rbf_svc svm.SVC(kernel='rbf', gamma=0.7, C=C)
Definition at line 49 of file SVM_v1.py.
View newest version in sPHENIX GitHub at line 49 of file SVM_v1.py
tuple SVM_v1.svc svm.SVC(kernel='linear', C=C)
Definition at line 48 of file SVM_v1.py.
View newest version in sPHENIX GitHub at line 48 of file SVM_v1.py
list SVM_v1.titles
Initial value:
 ['SVC with linear kernel',
           'LinearSVC (linear kernel)',
           'SVC with RBF kernel',
           'SVC with polynomial (degree 3) kernel']
Definition at line 60 of file SVM_v1.py.
View newest version in sPHENIX GitHub at line 60 of file SVM_v1.py
list SVM_v1.X data_train[:,1:3]
Definition at line 42 of file SVM_v1.py.
View newest version in sPHENIX GitHub at line 42 of file SVM_v1.py
tuple SVM_v1.y np.ravel(pid_train)
Definition at line 43 of file SVM_v1.py.
View newest version in sPHENIX GitHub at line 43 of file SVM_v1.py
tuple SVM_v1.Z clf.predict(np.c_[xx.ravel(), yy.ravel()])
Definition at line 72 of file SVM_v1.py.
View newest version in sPHENIX GitHub at line 72 of file SVM_v1.py
Referenced by Acts::BinnedSPGroupIterator< external_spacepoint_t >.BinnedSPGroupIterator(), Acts::Test.BOOST_AUTO_TEST_CASE(), genfit::MeasurementCreator.create(), Acts::Legacy::AtlasSeedFinder< SpacePoint >.fillLists(), Acts::BinnedSPGroupIterator< external_spacepoint_t >.findNotEmptyBin(), fullMaterial(), ActsAlignmentStates.get_projectionXY(), HelicalFitter.get_projectionXY(), is_nucleus(), layerMaterial(), genfit::EventDisplay.makeLines(), Acts::Geant4MaterialConverter.material(), genfit.MeanExcEnergy_get(), momentumDistributions(), Hydro.NSquant(), Fatras::GeneralMixture.operator()(), PseudoJet.operator()(), Acts::BinnedSPGroupIterator< external_spacepoint_t >.operator*(), Acts::BinnedSPGroupIterator< external_spacepoint_t >.operator++(), Acts::BinnedSPGroupIterator< external_spacepoint_t >.operator==(), KFPInputData.Print(), PHTpcCentralMembraneClusterizer.process_event(), Acts::Legacy::AtlasSeedFinder< SpacePoint >.production3Sp(), KFParticlePVReconstructor.ReconstructPrimVertex(), ALICEKF.repairCovariance(), Acts::SurfaceArrayCreator.surfaceArrayOnDisc(), three_charge(), Acts::AtlasStepper.transportCovarianceToBound(), ActsExamples::MaterialSteppingAction.UserSteppingAction(), while(), and ActsExamples::RootMaterialWriter.writeMaterial().