Analysis Software: RawTower_Prototype4 Class Reference
RawTower_Prototype4 Class Reference
#include <analysis/blob/master/EMCTemplateFitting/src/RawTower_Prototype4.h>
Public Types
enum { NSAMPLES = PROTOTYPE4_FEM::NSAMPLES }
enum { NSAMPLES = PROTOTYPE4_FEM::NSAMPLES }
typedef float signal_type
typedef float signal_type
Public Types inherited from RawTower
enum PROPERTY { prop_scint_gammas = 1, prop_cerenkov_gammas = 2, prop_MAX_NUMBER = UCHAR_MAX }
typedef unsigned long long CellKeyType
key type for cell map which should be consistent with CellKeyType
typedef std::map< CellKeyType,
float > CellMap
typedef CellMap::iterator CellIterator
typedef CellMap::const_iterator CellConstIterator
typedef std::pair
< CellIterator, CellIterator > CellRange
typedef std::pair
< CellConstIterator,
CellConstIterator > CellConstRange
typedef std::map< int, float > ShowerMap
typedef ShowerMap::iterator ShowerIterator
typedef ShowerMap::const_iterator ShowerConstIterator
typedef std::pair
< ShowerIterator,
ShowerIterator > ShowerRange
typedef std::pair
< ShowerConstIterator,
ShowerConstIterator > ShowerConstRange
Public Member Functions
RawTower_Prototype4 ()
RawTower_Prototype4 (const RawTower &tower)
RawTower_Prototype4 (RawTowerDefs::keytype id)
RawTower_Prototype4 (const unsigned int icol, const unsigned int irow)
RawTower_Prototype4 (const RawTowerDefs::CalorimeterId caloid, const unsigned int ieta, const unsigned int iphi)
virtual ~RawTower_Prototype4 ()
void Reset () override
Clear Event.
int isValid () const override
isValid returns non zero if object contains vailid data
void identify (std::ostream &os=std::cout) const override
void set_id (RawTowerDefs::keytype id) override
RawTowerDefs::keytype get_id () const override
int get_bineta () const override
int get_binphi () const override
int get_column () const override
int get_row () const override
double get_energy () const override
energy assigned to the tower. Depending on stage of process and DST node name, it could be energy deposition, light yield or calibrated energies
void set_energy (const double e) override
energy assigned to the tower. Depending on stage of process and DST node name, it could be energy deposition, light yield or calibrated energies
float get_time () const override
Time stamp assigned to the tower. Depending on the tower maker, it could be rise time or peak time.
void set_time (const float t) override
Time stamp assigned to the tower. Depending on the tower maker, it could be rise time or peak time.
void set_signal_samples (int i, signal_type sig)
signal_type get_signal_samples (int i) const
void set_HBD_channel_number (int i)
int get_HBD_channel_number () const
double get_energy_peak_sample (int verbosity=0)
double get_energy_power_law_exp (int verbosity=0)
double get_energy_power_law_double_exp (int verbosity=0)
RawTower_Prototype4 ()
RawTower_Prototype4 (const RawTower &tower)
RawTower_Prototype4 (RawTowerDefs::keytype id)
RawTower_Prototype4 (const unsigned int icol, const unsigned int irow)
RawTower_Prototype4 (const RawTowerDefs::CalorimeterId caloid, const unsigned int ieta, const unsigned int iphi)
virtual ~RawTower_Prototype4 ()
void Reset () override
Clear Event.
int isValid () const override
isValid returns non zero if object contains vailid data
void identify (std::ostream &os=std::cout) const override
void set_id (RawTowerDefs::keytype id) override
RawTowerDefs::keytype get_id () const override
int get_bineta () const override
int get_binphi () const override
int get_column () const override
int get_row () const override
double get_energy () const override
energy assigned to the tower. Depending on stage of process and DST node name, it could be energy deposition, light yield or calibrated energies
void set_energy (const double e) override
energy assigned to the tower. Depending on stage of process and DST node name, it could be energy deposition, light yield or calibrated energies
float get_time () const override
Time stamp assigned to the tower. Depending on the tower maker, it could be rise time or peak time.
void set_time (const float t) override
Time stamp assigned to the tower. Depending on the tower maker, it could be rise time or peak time.
void set_signal_samples (int i, signal_type sig)
signal_type get_signal_samples (int i) const
void set_HBD_channel_number (int i)
int get_HBD_channel_number () const
double get_energy_peak_sample (int verbosity=0)
double get_energy_power_law_exp (int verbosity=0)
double get_energy_power_law_double_exp (int verbosity=0)
Public Member Functions inherited from RawTower
~RawTower () override
virtual void set_key (RawTowerDefs::keytype id)
virtual RawTowerDefs::keytype get_key () const
virtual int get_bintheta () const
virtual int get_binl () const
return layer ID assigned to tower
virtual double get_scint_gammas () const
energy assigned to the tower. Depending on stage of process and DST node name, it could be energy deposition, light yield or calibrated energies
virtual void set_scint_gammas (const double)
scint_gammas assigned to the tower. Depending on stage of process and DST node name, it could be scint_gammas deposition, light yield or calibrated energies
virtual double get_cerenkov_gammas () const
energy assigned to the tower. Depending on stage of process and DST node name, it could be energy deposition, light yield or calibrated energies
virtual void set_cerenkov_gammas (const double)
cerenkov_gammas assigned to the tower. Depending on stage of process and DST node name, it could be cerenkov_gammas deposition, light yield or calibrated energies
virtual bool empty_g4cells () const
virtual size_t size_g4cells () const
virtual CellConstRange get_g4cells () const
virtual CellIterator find_g4cell (CellKeyType id)
virtual CellConstIterator find_g4cell (CellKeyType id) const
virtual void add_ecell (const CellKeyType, const float)
virtual void clear_g4cells ()
virtual bool empty_g4showers () const
virtual size_t size_g4showers () const
virtual ShowerConstRange get_g4showers () const
virtual ShowerIterator find_g4shower (int)
virtual ShowerConstIterator find_g4shower (int) const
virtual void add_eshower (const int, const float)
virtual void clear_g4showers ()
virtual bool has_property (const PROPERTY) const
virtual double get_property (const PROPERTY) const
virtual void set_property (const PROPERTY, const double)
Public Member Functions inherited from PHObject
PHObject ()
ctor
~PHObject () override
dtor
virtual PHObject * CloneMe () const
Virtual copy constructor.
virtual PHObject * clone () const final
PHObject * Clone (const char *newname="") const final
void Copy (TObject &object) const final
virtual int Integrate () const
virtual int Integrate (PHObject *)
virtual void CopyFrom (const PHObject *obj)
Protected Attributes
RawTowerDefs::keytype towerid
double energy
float time
signal_type signal_samples [NSAMPLES]
int HBD_channel
Additional Inherited Members
Static Public Member Functions inherited from RawTower
static const std::string get_property_info (PROPERTY prop_id)
Protected Member Functions inherited from RawTower
RawTower ()
virtual unsigned int get_property_nocheck (const PROPERTY) const
virtual void set_property_nocheck (const PROPERTY, const unsigned int)
Detailed Description
Definition at line 13 of file RawTower_Prototype4.h.
View newest version in sPHENIX GitHub at line 13 of file RawTower_Prototype4.h
Member Typedef Documentation
typedef float RawTower_Prototype4::signal_type
Definition at line 45 of file RawTower_Prototype4.h.
View newest version in sPHENIX GitHub at line 45 of file RawTower_Prototype4.h
typedef float RawTower_Prototype4::signal_type
Definition at line 45 of file RawTower_Prototype4.h.
View newest version in sPHENIX GitHub at line 45 of file RawTower_Prototype4.h
Member Enumeration Documentation
anonymous enum
Enumerator:
NSAMPLES
Definition at line 41 of file RawTower_Prototype4.h.
View newest version in sPHENIX GitHub at line 41 of file RawTower_Prototype4.h
anonymous enum
Enumerator:
NSAMPLES
Definition at line 41 of file RawTower_Prototype4.h.
View newest version in sPHENIX GitHub at line 41 of file RawTower_Prototype4.h
Constructor & Destructor Documentation
RawTower_Prototype4::RawTower_Prototype4 ()
Definition at line 17 of file RawTower_Prototype4.cc.
View newest version in sPHENIX GitHub at line 17 of file RawTower_Prototype4.cc
References NSAMPLES, and signal_samples.
RawTower_Prototype4::RawTower_Prototype4 (const RawTower & tower)
Definition at line 27 of file RawTower_Prototype4.cc.
View newest version in sPHENIX GitHub at line 27 of file RawTower_Prototype4.cc
References energy, RawTower::get_energy(), RawTower::get_id(), RawTower::get_time(), HBD_channel, NSAMPLES, signal_samples, and time.
RawTower_Prototype4::RawTower_Prototype4 (RawTowerDefs::keytype id)
Definition at line 36 of file RawTower_Prototype4.cc.
View newest version in sPHENIX GitHub at line 36 of file RawTower_Prototype4.cc
References NSAMPLES, and signal_samples.
RawTower_Prototype4::RawTower_Prototype4 (const unsigned int icol, const unsigned int irow)
Definition at line 45 of file RawTower_Prototype4.cc.
View newest version in sPHENIX GitHub at line 45 of file RawTower_Prototype4.cc
References RawTowerDefs::encode_towerid(), RawTowerDefs::NONE, NSAMPLES, and signal_samples.
RawTower_Prototype4::RawTower_Prototype4 (const RawTowerDefs::CalorimeterId caloid, const unsigned int ieta, const unsigned int iphi)
Definition at line 56 of file RawTower_Prototype4.cc.
View newest version in sPHENIX GitHub at line 56 of file RawTower_Prototype4.cc
References RawTowerDefs::encode_towerid(), NSAMPLES, and signal_samples.
virtual RawTower_Prototype4::~RawTower_Prototype4 () inline virtual
Definition at line 22 of file RawTower_Prototype4.h.
View newest version in sPHENIX GitHub at line 22 of file RawTower_Prototype4.h
RawTower_Prototype4::RawTower_Prototype4 ()
RawTower_Prototype4::RawTower_Prototype4 (const RawTower & tower)
RawTower_Prototype4::RawTower_Prototype4 (RawTowerDefs::keytype id)
RawTower_Prototype4::RawTower_Prototype4 (const unsigned int icol, const unsigned int irow)
RawTower_Prototype4::RawTower_Prototype4 (const RawTowerDefs::CalorimeterId caloid, const unsigned int ieta, const unsigned int iphi)
virtual RawTower_Prototype4::~RawTower_Prototype4 () inline virtual
Definition at line 22 of file RawTower_Prototype4.h.
View newest version in sPHENIX GitHub at line 22 of file RawTower_Prototype4.h
Member Function Documentation
int RawTower_Prototype4::get_bineta () const inline override virtual
Reimplemented from RawTower.
Definition at line 30 of file RawTower_Prototype4.h.
View newest version in sPHENIX GitHub at line 30 of file RawTower_Prototype4.h
References RawTowerDefs::decode_index1().
Referenced by identify().
int RawTower_Prototype4::get_bineta () const inline override virtual
Reimplemented from RawTower.
Definition at line 30 of file RawTower_Prototype4.h.
View newest version in sPHENIX GitHub at line 30 of file RawTower_Prototype4.h
References RawTowerDefs::decode_index1().
int RawTower_Prototype4::get_binphi () const inline override virtual
Reimplemented from RawTower.
Definition at line 31 of file RawTower_Prototype4.h.
View newest version in sPHENIX GitHub at line 31 of file RawTower_Prototype4.h
References RawTowerDefs::decode_index2().
Referenced by identify().
int RawTower_Prototype4::get_binphi () const inline override virtual
Reimplemented from RawTower.
Definition at line 31 of file RawTower_Prototype4.h.
View newest version in sPHENIX GitHub at line 31 of file RawTower_Prototype4.h
References RawTowerDefs::decode_index2().
int RawTower_Prototype4::get_column () const inline override virtual
Reimplemented from RawTower.
Definition at line 32 of file RawTower_Prototype4.h.
View newest version in sPHENIX GitHub at line 32 of file RawTower_Prototype4.h
References RawTowerDefs::decode_index1().
Referenced by CaloCalibration::process_event().
int RawTower_Prototype4::get_column () const inline override virtual
Reimplemented from RawTower.
Definition at line 32 of file RawTower_Prototype4.h.
View newest version in sPHENIX GitHub at line 32 of file RawTower_Prototype4.h
References RawTowerDefs::decode_index1().
double RawTower_Prototype4::get_energy () const inline override virtual
energy assigned to the tower. Depending on stage of process and DST node name, it could be energy deposition, light yield or calibrated energies
Reimplemented from RawTower.
Definition at line 34 of file RawTower_Prototype4.h.
View newest version in sPHENIX GitHub at line 34 of file RawTower_Prototype4.h
References energy.
Referenced by identify(), isValid(), CaloCalibration::process_event(), CaloTemplateFit::process_event(), and Prototype4DSTReader::process_event().
double RawTower_Prototype4::get_energy () const inline override virtual
energy assigned to the tower. Depending on stage of process and DST node name, it could be energy deposition, light yield or calibrated energies
Reimplemented from RawTower.
Definition at line 34 of file RawTower_Prototype4.h.
View newest version in sPHENIX GitHub at line 34 of file RawTower_Prototype4.h
References energy.
double RawTower_Prototype4::get_energy_peak_sample (int verbosity = 0)
Definition at line 117 of file RawTower_Prototype4.cc.
View newest version in sPHENIX GitHub at line 117 of file RawTower_Prototype4.cc
References i, NSAMPLES, PROTOTYPE4_FEM::SampleFit_PeakSample(), and signal_samples.
double RawTower_Prototype4::get_energy_peak_sample (int verbosity = 0)
double RawTower_Prototype4::get_energy_power_law_double_exp (int verbosity = 0)
Definition at line 135 of file RawTower_Prototype4.cc.
View newest version in sPHENIX GitHub at line 135 of file RawTower_Prototype4.cc
References i, NSAMPLES, PROTOTYPE4_FEM::SampleFit_PowerLawDoubleExp(), and signal_samples.
double RawTower_Prototype4::get_energy_power_law_double_exp (int verbosity = 0)
double RawTower_Prototype4::get_energy_power_law_exp (int verbosity = 0)
Definition at line 99 of file RawTower_Prototype4.cc.
View newest version in sPHENIX GitHub at line 99 of file RawTower_Prototype4.cc
References i, NSAMPLES, PROTOTYPE4_FEM::SampleFit_PowerLawExp(), and signal_samples.
double RawTower_Prototype4::get_energy_power_law_exp (int verbosity = 0)
int RawTower_Prototype4::get_HBD_channel_number () const inline
Definition at line 50 of file RawTower_Prototype4.h.
View newest version in sPHENIX GitHub at line 50 of file RawTower_Prototype4.h
References HBD_channel.
int RawTower_Prototype4::get_HBD_channel_number () const inline
Definition at line 50 of file RawTower_Prototype4.h.
View newest version in sPHENIX GitHub at line 50 of file RawTower_Prototype4.h
References HBD_channel.
RawTowerDefs::keytype RawTower_Prototype4::get_id () const inline override virtual
Reimplemented from RawTower.
Definition at line 29 of file RawTower_Prototype4.h.
View newest version in sPHENIX GitHub at line 29 of file RawTower_Prototype4.h
References towerid.
RawTowerDefs::keytype RawTower_Prototype4::get_id () const inline override virtual
Reimplemented from RawTower.
Definition at line 29 of file RawTower_Prototype4.h.
View newest version in sPHENIX GitHub at line 29 of file RawTower_Prototype4.h
References towerid.
int RawTower_Prototype4::get_row () const inline override virtual
Reimplemented from RawTower.
Definition at line 33 of file RawTower_Prototype4.h.
View newest version in sPHENIX GitHub at line 33 of file RawTower_Prototype4.h
References RawTowerDefs::decode_index2().
int RawTower_Prototype4::get_row () const inline override virtual
Reimplemented from RawTower.
Definition at line 33 of file RawTower_Prototype4.h.
View newest version in sPHENIX GitHub at line 33 of file RawTower_Prototype4.h
References RawTowerDefs::decode_index2().
Referenced by CaloCalibration::process_event().
signal_type RawTower_Prototype4::get_signal_samples (int i) const
RawTower_Prototype4::signal_type RawTower_Prototype4::get_signal_samples (int i) const
Definition at line 92 of file RawTower_Prototype4.cc.
View newest version in sPHENIX GitHub at line 92 of file RawTower_Prototype4.cc
References assert, i, NSAMPLES, and signal_samples.
Referenced by EventInfoSummary::process_event(), CaloUnpackPRDF::process_event(), CaloCalibration::process_event(), and CaloTemplateFit::process_event().
float RawTower_Prototype4::get_time () const inline override virtual
Time stamp assigned to the tower. Depending on the tower maker, it could be rise time or peak time.
Reimplemented from RawTower.
Definition at line 36 of file RawTower_Prototype4.h.
View newest version in sPHENIX GitHub at line 36 of file RawTower_Prototype4.h
References time.
float RawTower_Prototype4::get_time () const inline override virtual
Time stamp assigned to the tower. Depending on the tower maker, it could be rise time or peak time.
Reimplemented from RawTower.
Definition at line 36 of file RawTower_Prototype4.h.
View newest version in sPHENIX GitHub at line 36 of file RawTower_Prototype4.h
References time.
void RawTower_Prototype4::identify (std::ostream & os = std::cout) const override virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from PHObject.
Definition at line 77 of file RawTower_Prototype4.cc.
View newest version in sPHENIX GitHub at line 77 of file RawTower_Prototype4.cc
References get_bineta(), get_binphi(), and get_energy().
Referenced by CaloUnpackPRDF::process_event(), and CaloCalibration::process_event().
void RawTower_Prototype4::identify (std::ostream & os = std::cout) const override virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from RawTower.
int RawTower_Prototype4::isValid () const override virtual
isValid returns non zero if object contains vailid data
Reimplemented from RawTower.
int RawTower_Prototype4::isValid () const override virtual
isValid returns non zero if object contains vailid data
Reimplemented from PHObject.
Definition at line 75 of file RawTower_Prototype4.cc.
View newest version in sPHENIX GitHub at line 75 of file RawTower_Prototype4.cc
References get_energy().
void RawTower_Prototype4::Reset () override virtual
Clear Event.
Reimplemented from RawTower.
void RawTower_Prototype4::Reset () override virtual
Clear Event.
Reimplemented from PHObject.
Definition at line 68 of file RawTower_Prototype4.cc.
View newest version in sPHENIX GitHub at line 68 of file RawTower_Prototype4.cc
References energy, NSAMPLES, signal_samples, and time.
void RawTower_Prototype4::set_energy (const double) inline override virtual
energy assigned to the tower. Depending on stage of process and DST node name, it could be energy deposition, light yield or calibrated energies
Reimplemented from RawTower.
Definition at line 35 of file RawTower_Prototype4.h.
View newest version in sPHENIX GitHub at line 35 of file RawTower_Prototype4.h
References Acts::UnitConstants::e, and energy.
Referenced by GenericUnpackPRDF::process_event(), CaloUnpackPRDF::process_event(), CaloCalibration::process_event(), and CaloTemplateFit::process_event().
void RawTower_Prototype4::set_energy (const double) inline override virtual
energy assigned to the tower. Depending on stage of process and DST node name, it could be energy deposition, light yield or calibrated energies
Reimplemented from RawTower.
Definition at line 35 of file RawTower_Prototype4.h.
View newest version in sPHENIX GitHub at line 35 of file RawTower_Prototype4.h
References Acts::UnitConstants::e, and energy.
void RawTower_Prototype4::set_HBD_channel_number (int i) inline
Definition at line 49 of file RawTower_Prototype4.h.
View newest version in sPHENIX GitHub at line 49 of file RawTower_Prototype4.h
References HBD_channel, and i.
void RawTower_Prototype4::set_HBD_channel_number (int i) inline
Definition at line 49 of file RawTower_Prototype4.h.
View newest version in sPHENIX GitHub at line 49 of file RawTower_Prototype4.h
References HBD_channel, and i.
Referenced by GenericUnpackPRDF::process_event(), and CaloUnpackPRDF::process_event().
void RawTower_Prototype4::set_id (RawTowerDefs::keytype id) inline override virtual
Reimplemented from RawTower.
Definition at line 28 of file RawTower_Prototype4.h.
View newest version in sPHENIX GitHub at line 28 of file RawTower_Prototype4.h
References train_ambiguity_solver::id.
void RawTower_Prototype4::set_id (RawTowerDefs::keytype id) inline override virtual
Reimplemented from RawTower.
Definition at line 28 of file RawTower_Prototype4.h.
View newest version in sPHENIX GitHub at line 28 of file RawTower_Prototype4.h
References train_ambiguity_solver::id.
void RawTower_Prototype4::set_signal_samples (int i, signal_type sig)
void RawTower_Prototype4::set_signal_samples (int i, RawTower_Prototype4::signal_type sig)
Definition at line 83 of file RawTower_Prototype4.cc.
View newest version in sPHENIX GitHub at line 83 of file RawTower_Prototype4.cc
References assert, i, NSAMPLES, and signal_samples.
Referenced by GenericUnpackPRDF::process_event(), CaloUnpackPRDF::process_event(), and CaloCalibration::process_event().
void RawTower_Prototype4::set_time (const float) inline override virtual
Time stamp assigned to the tower. Depending on the tower maker, it could be rise time or peak time.
Reimplemented from RawTower.
Definition at line 37 of file RawTower_Prototype4.h.
View newest version in sPHENIX GitHub at line 37 of file RawTower_Prototype4.h
References t, and time.
void RawTower_Prototype4::set_time (const float) inline override virtual
Time stamp assigned to the tower. Depending on the tower maker, it could be rise time or peak time.
Reimplemented from RawTower.
Definition at line 37 of file RawTower_Prototype4.h.
View newest version in sPHENIX GitHub at line 37 of file RawTower_Prototype4.h
References t, and time.
Referenced by CaloCalibration::process_event(), and CaloTemplateFit::process_event().
Member Data Documentation
double RawTower_Prototype4::energy protected
energy assigned to the tower. Depending on stage of process and DST node name, it could be energy deposition, light yield or calibrated energies
Definition at line 63 of file RawTower_Prototype4.h.
View newest version in sPHENIX GitHub at line 63 of file RawTower_Prototype4.h
Referenced by get_energy(), RawTower_Prototype4(), Reset(), and set_energy().
int RawTower_Prototype4::HBD_channel protected
Definition at line 70 of file RawTower_Prototype4.h.
View newest version in sPHENIX GitHub at line 70 of file RawTower_Prototype4.h
Referenced by get_HBD_channel_number(), RawTower_Prototype4(), and set_HBD_channel_number().
signal_type RawTower_Prototype4::signal_samples protected
Definition at line 69 of file RawTower_Prototype4.h.
View newest version in sPHENIX GitHub at line 69 of file RawTower_Prototype4.h
Referenced by get_energy_peak_sample(), get_energy_power_law_double_exp(), get_energy_power_law_exp(), get_signal_samples(), RawTower_Prototype4(), Reset(), and set_signal_samples().
float RawTower_Prototype4::time protected
Time stamp assigned to the tower. Depending on the tower maker, it could be rise time or peak time.
Definition at line 66 of file RawTower_Prototype4.h.
View newest version in sPHENIX GitHub at line 66 of file RawTower_Prototype4.h
Referenced by get_time(), RawTower_Prototype4(), Reset(), and set_time().
RawTowerDefs::keytype RawTower_Prototype4::towerid protected
Definition at line 59 of file RawTower_Prototype4.h.
View newest version in sPHENIX GitHub at line 59 of file RawTower_Prototype4.h
Referenced by get_id().
The documentation for this class was generated from the following files:
analysis/blob/master/EMCTemplateFitting/src/RawTower_Prototype4.h
prototype/blob/master/offline/packages/Prototype4/RawTower_Prototype4.h
analysis/blob/master/EMCTemplateFitting/src/RawTower_Prototype4.cc
prototype/blob/master/offline/packages/Prototype4/RawTower_Prototype4.cc