Analysis Software: Martini Class Reference
Martini Class Reference
#include <JETSCAPE/blob/main/src/jet/Martini.h>
Classes
struct dGammas
struct Gamma_info
Public Member Functions
Martini ()
virtual ~Martini ()
void Init ()
void DoEnergyLoss (double deltaT, double Time, double Q2, vector< Parton > &pIn, vector< Parton > &pOut)
int DetermineProcess (double p, double T, double deltaTRest, int id)
void WriteTask (weak_ptr< JetScapeWriter > w)
RateRadiative getRateRadTotal (double p, double T)
RateRadiative getRateRadPos (double u, double T)
RateRadiative getRateRadNeg (double u, double T)
double getNewMomentumRad (double p, double T, int process)
double area (double y, double u, int posNegSwitch, int process)
double function (double u, double y, int process)
bool isCoherent (Parton &pIn, int sibling, double T)
RateElastic getRateElasTotal (double p, double T)
RateElastic getRateElasPos (double u, double T)
RateElastic getRateElasNeg (double u, double T)
RateConversion getRateConv (double p, double T)
double getEnergyTransfer (double p, double T, int process)
double getMomentumTransfer (double p, double omega, double T, int process)
double areaOmega (double u, int posNegSwitch, int process)
double areaQ (double u, double omega, int process)
double functionOmega (double u, double y, int process)
double functionQ (double u, double omega, double q, int process)
FourVector getNewMomentumElas (FourVector pVec, double omega, double q)
FourVector getThermalVec (FourVector qVec, double T, int id)
double getThermal (double k_min, double T, int kind)
void readRadiativeRate (Gamma_info *dat, dGammas *Gam)
void readElasticRateOmega ()
void readElasticRateQ ()
double getRate_qqg (double p, double k)
double getRate_gqq (double p, double k)
double getRate_ggg (double p, double k)
double getRate_qqgamma (double p, double k)
double use_table (double p, double k, double dGamma[NP][NK], int which_kind)
double getElasticRateOmega (double u, double omega, int process)
double getElasticRateQ (double u, double omega, double q, int process)
double use_elastic_table_omega (double omega, int which_kind)
double use_elastic_table_q (double u, double omega, int which_kind)
Public Member Functions inherited from Jetscape::JetEnergyLossModule< Martini >
virtual shared_ptr< JetEnergyLoss > Clone () const override
Deep copy constructor. The goal is to not have to initialize Modules multiple times.
void SetActive (bool m_active_exec)
Override deactivation.
Public Member Functions inherited from Jetscape::JetEnergyLoss
JetEnergyLoss ()
JetEnergyLoss (const JetEnergyLoss &j)
virtual ~JetEnergyLoss ()
virtual void Exec () final
virtual void Clear ()
void SetQhat (double m_qhat)
const double GetQhat () const
void AddShowerInitiatingParton (shared_ptr< Parton > p)
shared_ptr< Parton > GetShowerInitiatingParton ()
void PrintShowerInitiatingParton ()
double GetDeltaT ()
double GetMaxT ()
shared_ptr< PartonShower > GetShower ()
void SetJetSignalConnected (bool m_jetSignalConnected)
TODO: Remove.
const bool GetJetSignalConnected () const
void SetEdensitySignalConnected (bool m_edensitySignalConnected)
const bool GetEdensitySignalConnected () const
void SetGetHydroCellSignalConnected (bool m_GetHydroCellSignalConnected)
const bool GetGetHydroCellSignalConnected ()
void SetGetHydroTau0SignalConnected (bool m_GetHydroTau0SignalConnected)
const bool GetGetHydroTau0SignalConnected ()
void SetSentInPartonsConnected (bool m_SentInPartonsConnected)
const bool GetSentInPartonsConnected ()
void add_a_liquefier (std::shared_ptr< LiquefierBase > new_liquefier)
std::weak_ptr< LiquefierBase > get_liquefier ()
void SendFinalStatePartons (vector< vector< shared_ptr< Parton >>> &fPartons)
void GetFinalPartonsForEachShower (shared_ptr< PartonShower > shower)
Public Member Functions inherited from Jetscape::JetScapeModuleBase
JetScapeModuleBase ()
JetScapeModuleBase (string m_name)
virtual ~JetScapeModuleBase ()
void SetXMLMainFileName (string m_name)
string GetXMLMainFileName ()
void SetXMLUserFileName (string m_name)
string GetXMLUserFileName ()
shared_ptr< std::mt19937 > GetMt19937Generator ()
tinyxml2::XMLElement * GetXMLElement (std::initializer_list< const char * > path, bool isRequired=true)
std::string GetXMLElementText (std::initializer_list< const char * > path, bool isRequired=true)
int GetXMLElementInt (std::initializer_list< const char * > path, bool isRequired=true)
double GetXMLElementDouble (std::initializer_list< const char * > path, bool isRequired=true)
Public Member Functions inherited from Jetscape::JetScapeTask
JetScapeTask ()
virtual ~JetScapeTask ()
virtual void Finish ()
virtual void ExecuteTasks ()
virtual void ExecuteTask ()
virtual void InitTask ()
virtual void InitTasks ()
virtual void ClearTasks ()
virtual void ClearTask ()
virtual void FinishTask ()
virtual void FinishTasks ()
virtual void WriteTasks (weak_ptr< JetScapeWriter > w)
virtual void CollectHeader (weak_ptr< JetScapeWriter > w)
virtual void CollectHeaders (weak_ptr< JetScapeWriter > w)
virtual void Add (shared_ptr< JetScapeTask > m_tasks)
virtual const int GetMyTaskNumber () const
const vector< shared_ptr
< JetScapeTask > > GetTaskList () const
shared_ptr< JetScapeTask > GetTaskAt (int i)
void EraseTaskLast ()
void EraseTaskAt (int i)
void ResizeTaskList (int i)
void ClearTaskList ()
int GetNumberOfTasks ()
const bool GetActive () const
void SetActive (bool m_active_exec)
void SetId (string m_id)
const string GetId () const
const shared_ptr
< JetScapeModuleMutex > GetMutex () const
void SetMutex (shared_ptr< JetScapeModuleMutex > m_mutex)
Public Member Functions inherited from sigslot::has_slots< sigslot::multi_threaded_local >
has_slots ()
has_slots (const has_slots &hs)
void signal_connect (_signal_base< sigslot::multi_threaded_local > *sender)
void signal_disconnect (_signal_base< sigslot::multi_threaded_local > *sender)
virtual ~has_slots ()
void disconnect_all ()
Static Public Member Functions
static void IncrementpLable ()
Protected Attributes
uniform_real_distribution< double > ZeroOneDistribution
string PathToTables
Private Member Functions
double RunningAlphaS (double muSquare)
Private Attributes
const double eLossCut = 1.0
double Q0
double alpha_s0
double alpha_s
double alpha_em
double g
double pcut
double hydro_Tc
double tStart
int run_alphas
int recoil_on
Gamma_info dat
dGammas Gam
vector< double > * dGamma_qq
vector< double > * dGamma_qg
vector< double > * dGamma_qq_q
vector< double > * dGamma_qg_q
Static Private Attributes
static constexpr double AMYpCut = 4.01
static const int NP = 230
static const int NK = 381
static const int Nalphas = 11
static const int Nomega = 120
static const int Nq = 60
static constexpr double omegaStep = 0.2
static constexpr double qStep = 0.2
static constexpr double alphaMin = 0.15
static constexpr double alphaStep = 0.03
static int pLabelNew = 0
static RegisterJetScapeModule
< Martini > reg
Additional Inherited Members
Public Attributes inherited from Jetscape::JetEnergyLoss
sigslot::signal5< double,
double, double, double,
std::unique_ptr< FluidCellInfo >
&, multi_threaded_local > GetHydroCellSignal
Core signal to receive information from the medium.
sigslot::signal1< double
&, multi_threaded_local > GetHydroTau0Signal
sigslot::signal2< int, double,
multi_threaded_local > jetSignal
sigslot::signal2< int, double
&, multi_threaded_local > edensitySignal
sigslot::signal5< double,
double, double, vector< Parton >
&, vector< Parton >
&, multi_threaded_local > SentInPartons
Protected Member Functions inherited from Jetscape::JetEnergyLossModule< Martini >
bool TakeResponsibilityFor (Parton &p)
Detailed Description
Definition at line 63 of file Martini.h.
View newest version in sPHENIX GitHub at line 63 of file Martini.h
Constructor & Destructor Documentation
Martini::Martini ()
Definition at line 42 of file Martini.cc.
View newest version in sPHENIX GitHub at line 42 of file Martini.cc
References SetId(), and VERBOSE.
Martini::~Martini () virtual
Definition at line 57 of file Martini.cc.
View newest version in sPHENIX GitHub at line 57 of file Martini.cc
References VERBOSE.
Member Function Documentation
double Martini::area (double y, double u, int posNegSwitch, int process)
Definition at line 1251 of file Martini.cc.
View newest version in sPHENIX GitHub at line 1251 of file Martini.cc
double Martini::areaOmega (double u, int posNegSwitch, int process)
Definition at line 2465 of file Martini.cc.
View newest version in sPHENIX GitHub at line 2465 of file Martini.cc
References JSWARN.
double Martini::areaQ (double u, double omega, int process)
Definition at line 2483 of file Martini.cc.
View newest version in sPHENIX GitHub at line 2483 of file Martini.cc
References A, and JSWARN.
int Martini::DetermineProcess (double p, double T, double deltaTRest, int id)
Definition at line 860 of file Martini.cc.
View newest version in sPHENIX GitHub at line 860 of file Martini.cc
References RateElastic::gg, RateRadiative::ggg, RateElastic::gq, RateConversion::gq, RateRadiative::gqq, hbarc, JSWARN, RateElastic::qg, RateConversion::qg, RateConversion::qgamma, RateElastic::qq, RateRadiative::qqg, RateRadiative::qqgamma, and Acts::UnitConstants::T.
void Martini::DoEnergyLoss (double deltaT, double time, double Q2, vector< Parton > & pIn, vector< Parton > & pOut) virtual
Default function to perform the energy loss for partons at time "time". It should be overridden by different energy loss tasks.
Parameters
deltaT Step-size.
time Current time.
Q2 Current virtuality of the parton.
pIn Vector of current partons.
pOut Vector of partons at time "time+deltaT".
Reimplemented from Jetscape::JetEnergyLoss.
Definition at line 100 of file Martini.cc.
View newest version in sPHENIX GitHub at line 100 of file Martini.cc
References Acts::active, Acts::UnitConstants::e, eta, Acts::UnitConstants::g, i, Id(), k, MAGENTA, Jetscape::mu, tgeo-response2json::process(), physmon_track_finding_ttbar::r, Jetscape::rounding_error, Jetscape::FourVector::Set(), t, Jetscape::FourVector::t(), Acts::UnitConstants::T, Jetscape::FluidCellInfo::temperature, VERBOSE, VERBOSESHOWER, vx, Jetscape::FluidCellInfo::vx, vy, Jetscape::FluidCellInfo::vy, vz, Jetscape::FluidCellInfo::vz, Jetscape::FourVector::x(), Jetscape::FourVector::y(), and Jetscape::FourVector::z().
double Martini::function (double u, double y, int process)
Definition at line 1276 of file Martini.cc.
View newest version in sPHENIX GitHub at line 1276 of file Martini.cc
double Martini::functionOmega (double u, double y, int process) inline
Definition at line 181 of file Martini.h.
View newest version in sPHENIX GitHub at line 181 of file Martini.h
double Martini::functionQ (double u, double omega, double q, int process) inline
Definition at line 184 of file Martini.h.
View newest version in sPHENIX GitHub at line 184 of file Martini.h
double Martini::getElasticRateOmega (double u, double omega, int process)
Definition at line 3005 of file Martini.cc.
View newest version in sPHENIX GitHub at line 3005 of file Martini.cc
double Martini::getElasticRateQ (double u, double omega, double q, int process)
Definition at line 3012 of file Martini.cc.
View newest version in sPHENIX GitHub at line 3012 of file Martini.cc
double Martini::getEnergyTransfer (double p, double T, int process)
Definition at line 2224 of file Martini.cc.
View newest version in sPHENIX GitHub at line 2224 of file Martini.cc
References RateElastic::gg, RateElastic::gq, JSWARN, RateElastic::qg, RateElastic::qq, Acts::UnitConstants::T, physmon_ckf_tracking::u, ambiguity_solver_full_chain::x, and y.
double Martini::getMomentumTransfer (double p, double omega, double T, int process)
Definition at line 2356 of file Martini.cc.
View newest version in sPHENIX GitHub at line 2356 of file Martini.cc
References A, test_fpe::count, Acts::UnitConstants::g, i, JSWARN, Acts::UnitConstants::T, physmon_ckf_tracking::u, ambiguity_solver_full_chain::x, y, and y_max.
FourVector Martini::getNewMomentumElas (FourVector pVec, double omega, double q)
Definition at line 2507 of file Martini.cc.
View newest version in sPHENIX GitHub at line 2507 of file Martini.cc
References ActsTests::PropagationDatasets::phi, physmon_track_finding_ttbar::r, Jetscape::FourVector::Set(), Jetscape::FourVector::t(), physmon_ckf_tracking::u, Jetscape::FourVector::x(), Jetscape::FourVector::y(), and Jetscape::FourVector::z().
double Martini::getNewMomentumRad (double p, double T, int process)
Definition at line 1088 of file Martini.cc.
View newest version in sPHENIX GitHub at line 1088 of file Martini.cc
References RateRadiative::ggg, RateRadiative::gqq, JSWARN, LambertW(), tgeo-response2json::process(), RateRadiative::qqg, Acts::UnitConstants::T, physmon_ckf_tracking::u, ambiguity_solver_full_chain::x, and y.
double Martini::getRate_ggg (double p, double k)
Definition at line 2901 of file Martini.cc.
View newest version in sPHENIX GitHub at line 2901 of file Martini.cc
double Martini::getRate_gqq (double p, double k)
Definition at line 2894 of file Martini.cc.
View newest version in sPHENIX GitHub at line 2894 of file Martini.cc
double Martini::getRate_qqg (double p, double k)
Definition at line 2890 of file Martini.cc.
View newest version in sPHENIX GitHub at line 2890 of file Martini.cc
double Martini::getRate_qqgamma (double p, double k)
Definition at line 2908 of file Martini.cc.
View newest version in sPHENIX GitHub at line 2908 of file Martini.cc
RateConversion Martini::getRateConv (double p, double T)
Definition at line 2210 of file Martini.cc.
View newest version in sPHENIX GitHub at line 2210 of file Martini.cc
References Acts::UnitConstants::g, RateConversion::gq, Jetscape::nf, RateConversion::qg, RateConversion::qgamma, and rate.
RateElastic Martini::getRateElasNeg (double u, double T)
Definition at line 1933 of file Martini.cc.
View newest version in sPHENIX GitHub at line 1933 of file Martini.cc
References Acts::PhysicalConstants::c, RateElastic::gg, RateElastic::gq, i, j, Jetscape::nf, RateElastic::qg, RateElastic::qq, rate, and physmon_ckf_tracking::u.
RateElastic Martini::getRateElasPos (double u, double T)
Definition at line 1656 of file Martini.cc.
View newest version in sPHENIX GitHub at line 1656 of file Martini.cc
References Acts::PhysicalConstants::c, RateElastic::gg, RateElastic::gq, i, j, Jetscape::nf, RateElastic::qg, RateElastic::qq, rate, and physmon_ckf_tracking::u.
RateElastic Martini::getRateElasTotal (double p, double T)
Definition at line 1369 of file Martini.cc.
View newest version in sPHENIX GitHub at line 1369 of file Martini.cc
References Acts::PhysicalConstants::c, RateElastic::gg, RateElastic::gq, i, j, Jetscape::nf, RateElastic::qg, RateElastic::qq, rate, Acts::UnitConstants::T, and physmon_ckf_tracking::u.
RateRadiative Martini::getRateRadNeg (double u, double T)
Definition at line 1072 of file Martini.cc.
View newest version in sPHENIX GitHub at line 1072 of file Martini.cc
References Acts::UnitConstants::g, RateRadiative::ggg, RateRadiative::gqq, Jetscape::nf, RateRadiative::qqg, RateRadiative::qqgamma, rate, Acts::UnitConstants::T, and physmon_ckf_tracking::u.
RateRadiative Martini::getRateRadPos (double u, double T)
Definition at line 1056 of file Martini.cc.
View newest version in sPHENIX GitHub at line 1056 of file Martini.cc
References Acts::UnitConstants::g, RateRadiative::ggg, RateRadiative::gqq, Jetscape::nf, RateRadiative::qqg, RateRadiative::qqgamma, rate, Acts::UnitConstants::T, and physmon_ckf_tracking::u.
RateRadiative Martini::getRateRadTotal (double p, double T)
Definition at line 1020 of file Martini.cc.
View newest version in sPHENIX GitHub at line 1020 of file Martini.cc
References Acts::UnitConstants::g, RateRadiative::ggg, RateRadiative::gqq, Jetscape::nf, RateRadiative::qqg, RateRadiative::qqgamma, rate, Acts::UnitConstants::T, and physmon_ckf_tracking::u.
double Martini::getThermal (double k_min, double T, int kind)
Definition at line 2694 of file Martini.cc.
View newest version in sPHENIX GitHub at line 2694 of file Martini.cc
References gx, merge_hashes::p, and Acts::UnitConstants::T.
FourVector Martini::getThermalVec (FourVector qVec, double T, int id)
Definition at line 2586 of file Martini.cc.
View newest version in sPHENIX GitHub at line 2586 of file Martini.cc
References Acts::UnitConstants::e, k, norm, ActsTests::PropagationDatasets::phi, Jetscape::FourVector::Set(), Jetscape::FourVector::t(), Jetscape::FourVector::x(), Jetscape::FourVector::y(), and Jetscape::FourVector::z().
static void Martini::IncrementpLable () inline static
Definition at line 207 of file Martini.h.
View newest version in sPHENIX GitHub at line 207 of file Martini.h
void Martini::Init () virtual
It reads the input parameters from a XML file under the tag <Eloss>. Sets the Parton class inP and PartonShower class pShower to null. Also initializes the tasks attached to the JetEnergyLoss module.
Reimplemented from Jetscape::JetEnergyLoss.
Definition at line 59 of file Martini.cc.
View newest version in sPHENIX GitHub at line 59 of file Martini.cc
References JSDEBUG, JSINFO, JSWARN, Jetscape::rounding_error, and physmon_simulation::s.
bool Martini::isCoherent (Parton & pIn, int sibling, double T)
Definition at line 1289 of file Martini.cc.
View newest version in sPHENIX GitHub at line 1289 of file Martini.cc
References Acts::UnitConstants::e, graph::edges_begin(), graph::edges_end(), hbarc, JSDEBUG, JSWARN, merge_hashes::p, Jetscape::Parton::shower(), Jetscape::FourVector::t(), Acts::UnitConstants::T, Jetscape::FourVector::x(), Jetscape::JetScapeParticleBase::x_in(), Jetscape::FourVector::y(), and Jetscape::FourVector::z().
void Martini::readElasticRateOmega ()
Definition at line 2782 of file Martini.cc.
View newest version in sPHENIX GitHub at line 2782 of file Martini.cc
References filename, in, JSINFO, and JSWARN.
void Martini::readElasticRateQ ()
Definition at line 2836 of file Martini.cc.
View newest version in sPHENIX GitHub at line 2836 of file Martini.cc
References filename, in, JSINFO, and JSWARN.
void Martini::readRadiativeRate (Gamma_info * dat, dGammas * Gam)
Definition at line 2729 of file Martini.cc.
View newest version in sPHENIX GitHub at line 2729 of file Martini.cc
References Martini::Gamma_info::BDMPS, Martini::Gamma_info::BetheHeitler, Martini::Gamma_info::dca, Martini::Gamma_info::dcf, Martini::Gamma_info::dda, Martini::Gamma_info::ddf, Martini::Gamma_info::dp, fclose(), filename, Martini::dGammas::ggg, Martini::dGammas::gqq, Martini::Gamma_info::include_gluons, JSINFO, JSWARN, Martini::Gamma_info::k_max, Martini::Gamma_info::k_min, Martini::Gamma_info::n_k, Martini::Gamma_info::n_kmin, Martini::Gamma_info::n_p, Martini::Gamma_info::n_pmin, Martini::Gamma_info::Nc, Jetscape::nf, Martini::Gamma_info::Nf, NP, Martini::Gamma_info::p_max, Martini::Gamma_info::p_min, Martini::dGammas::qqg, Martini::dGammas::qqgamma, propagation_timing::rfile, Martini::dGammas::tau_ggg, Martini::dGammas::tau_gqq, Martini::dGammas::tau_qqg, and Martini::dGammas::tau_qqgamma.
double Martini::RunningAlphaS (double muSquare) private
Definition at line 850 of file Martini.cc.
View newest version in sPHENIX GitHub at line 850 of file Martini.cc
double Martini::use_elastic_table_omega (double omega, int which_kind)
Definition at line 3020 of file Martini.cc.
View newest version in sPHENIX GitHub at line 3020 of file Martini.cc
References position, and rate.
double Martini::use_elastic_table_q (double u, double omega, int which_kind)
Definition at line 3123 of file Martini.cc.
View newest version in sPHENIX GitHub at line 3123 of file Martini.cc
References position, and rate.
double Martini::use_table (double p, double k, double dGamma[NP][NK], int which_kind)
Definition at line 2912 of file Martini.cc.
View newest version in sPHENIX GitHub at line 2912 of file Martini.cc
References KFPMath::a, KFPMath::b, k, and merge_hashes::p.
void Martini::WriteTask (weak_ptr< JetScapeWriter > w) inline virtual
Write output information for each tasks/subtasks attached to the JetEnergyLoss module using JetScapeWriter functionality.
Parameters
w A pointer of type JetScapeWriter.
Reimplemented from Jetscape::JetEnergyLoss.
Definition at line 156 of file Martini.h.
View newest version in sPHENIX GitHub at line 156 of file Martini.h
Member Data Documentation
double Martini::alpha_em private
Definition at line 74 of file Martini.h.
View newest version in sPHENIX GitHub at line 74 of file Martini.h
double Martini::alpha_s private
Definition at line 73 of file Martini.h.
View newest version in sPHENIX GitHub at line 73 of file Martini.h
double Martini::alpha_s0 private
Definition at line 73 of file Martini.h.
View newest version in sPHENIX GitHub at line 73 of file Martini.h
constexpr double Martini::alphaMin = 0.15 static private
Definition at line 92 of file Martini.h.
View newest version in sPHENIX GitHub at line 92 of file Martini.h
constexpr double Martini::alphaStep = 0.03 static private
Definition at line 93 of file Martini.h.
View newest version in sPHENIX GitHub at line 93 of file Martini.h
constexpr double Martini::AMYpCut = 4.01 static private
Definition at line 68 of file Martini.h.
View newest version in sPHENIX GitHub at line 68 of file Martini.h
Gamma_info Martini::dat private
Definition at line 132 of file Martini.h.
View newest version in sPHENIX GitHub at line 132 of file Martini.h
vector<double>* Martini::dGamma_qg private
Definition at line 136 of file Martini.h.
View newest version in sPHENIX GitHub at line 136 of file Martini.h
vector<double>* Martini::dGamma_qg_q private
Definition at line 138 of file Martini.h.
View newest version in sPHENIX GitHub at line 138 of file Martini.h
vector<double>* Martini::dGamma_qq private
Definition at line 135 of file Martini.h.
View newest version in sPHENIX GitHub at line 135 of file Martini.h
vector<double>* Martini::dGamma_qq_q private
Definition at line 137 of file Martini.h.
View newest version in sPHENIX GitHub at line 137 of file Martini.h
const double Martini::eLossCut = 1.0 private
Definition at line 70 of file Martini.h.
View newest version in sPHENIX GitHub at line 70 of file Martini.h
double Martini::g private
Definition at line 75 of file Martini.h.
View newest version in sPHENIX GitHub at line 75 of file Martini.h
dGammas Martini::Gam private
Definition at line 133 of file Martini.h.
View newest version in sPHENIX GitHub at line 133 of file Martini.h
double Martini::hydro_Tc private
Definition at line 77 of file Martini.h.
View newest version in sPHENIX GitHub at line 77 of file Martini.h
const int Martini::Nalphas = 11 static private
Definition at line 86 of file Martini.h.
View newest version in sPHENIX GitHub at line 86 of file Martini.h
const int Martini::NK = 381 static private
Definition at line 84 of file Martini.h.
View newest version in sPHENIX GitHub at line 84 of file Martini.h
const int Martini::Nomega = 120 static private
Definition at line 87 of file Martini.h.
View newest version in sPHENIX GitHub at line 87 of file Martini.h
const int Martini::NP = 230 static private
Definition at line 83 of file Martini.h.
View newest version in sPHENIX GitHub at line 83 of file Martini.h
const int Martini::Nq = 60 static private
Definition at line 88 of file Martini.h.
View newest version in sPHENIX GitHub at line 88 of file Martini.h
constexpr double Martini::omegaStep = 0.2 static private
Definition at line 90 of file Martini.h.
View newest version in sPHENIX GitHub at line 90 of file Martini.h
string Martini::PathToTables protected
Definition at line 212 of file Martini.h.
View newest version in sPHENIX GitHub at line 212 of file Martini.h
double Martini::pcut private
Definition at line 76 of file Martini.h.
View newest version in sPHENIX GitHub at line 76 of file Martini.h
int Martini::pLabelNew = 0 static private
Definition at line 140 of file Martini.h.
View newest version in sPHENIX GitHub at line 140 of file Martini.h
double Martini::Q0 private
Definition at line 72 of file Martini.h.
View newest version in sPHENIX GitHub at line 72 of file Martini.h
constexpr double Martini::qStep = 0.2 static private
Definition at line 91 of file Martini.h.
View newest version in sPHENIX GitHub at line 91 of file Martini.h
int Martini::recoil_on private
Definition at line 80 of file Martini.h.
View newest version in sPHENIX GitHub at line 80 of file Martini.h
RegisterJetScapeModule< Martini > Martini::reg static private
Definition at line 143 of file Martini.h.
View newest version in sPHENIX GitHub at line 143 of file Martini.h
int Martini::run_alphas private
Definition at line 79 of file Martini.h.
View newest version in sPHENIX GitHub at line 79 of file Martini.h
double Martini::tStart private
Definition at line 78 of file Martini.h.
View newest version in sPHENIX GitHub at line 78 of file Martini.h
uniform_real_distribution<double> Martini::ZeroOneDistribution protected
Definition at line 210 of file Martini.h.
View newest version in sPHENIX GitHub at line 210 of file Martini.h
The documentation for this class was generated from the following files:
JETSCAPE/blob/main/src/jet/Martini.h
JETSCAPE/blob/main/src/jet/Martini.cc