Analysis Software: OnlMonClient Class Reference
OnlMonClient Class Reference
#include <OnlMon/blob/main/onlmonclient/OnlMonClient.h>
Public Member Functions
~OnlMonClient () override
void Verbosity (const int i) override
int UpdateServerHistoMap (const std::string &hname, const std::string &subsys, const std::string &hostname)
void PutHistoInMap (const std::string &hname, const std::string &subsys, const std::string &hostname, const int port)
void updateHistoMap (const std::string &subsys, const std::string &hname, TH1 *h1d)
int requestMonitorList (const std::string &hostname, const int moniport)
TH1 * getHisto (const std::string &monitor, const std::string &hname)
OnlMonDraw * getDrawer (const std::string &name)
int requestHisto (const std::string &what="ALL", const std::string &hostname="localhost", const int moniport=OnlMonDefs::MONIPORT)
int requestHistoList (const std::string &subsys, const std::string &hostname, const int moniport, std::list< std::string > &histolist)
int requestHistoByName (const std::string &subsystem, const std::string &what="ALL")
int requestHistoBySubSystem (const std::string &subsystem, int getall=0)
void registerHisto (const std::string &hname, const std::string &subsys)
void Print (const char *what="ALL")
void AddServerHost (const std::string &hostname)
void registerDrawer (OnlMonDraw *Drawer)
int ReadHistogramsFromFile (const std::string &filename)
int Draw (const char *who="ALL", const char *what="ALL")
int MakePS (const char *who="ALL", const char *what="ALL")
int MakeHtml (const char *who="ALL", const char *what="ALL")
int SavePlot (const std::string &who="ALL", const std::string &what="ALL")
std::string htmlRegisterPage (const OnlMonDraw &drawer, const std::string &path, const std::string &basefilename, const std::string &ext)
void htmlAddMenu (const OnlMonDraw &drawer, const std::string &path, const std::string &relfilename)
void htmlNamer (const OnlMonDraw &drawer, const std::string &basefilename, const std::string &ext, std::string &fullfilename, std::string &filename)
int LocateHistogram (const std::string &hname, const std::string &subsys)
int RunNumber ()
time_t EventTime (const std::string &which)
time_t EventTime (const std::string &servername, const std::string &which)
int SendCommand (const char *hostname, const int port, const char *cmd)
void SetDisplaySizeX (int xsize)
void SetDisplaySizeY (int ysize)
int GetDisplaySizeX ()
int GetDisplaySizeY ()
int CanvasToPng (TCanvas *canvas, std::string const &filename)
int HistoToPng (TH1 *histo, std::string const &pngfilename, const char *drawopt="", const int statopt=11)
int SaveLogFile (const OnlMonDraw &drawer)
int SetStyleToDefault ()
int isCosmicRun ()
int isStandalone ()
std::string RunType ()
void CacheRunDB (const int runno)
void FindAllMonitors ()
int FindMonitor (const std::string &name)
int IsMonitorRunning (const std::string &name)
std::string ExtractSubsystem (const std::string &filename)
Public Member Functions inherited from OnlMonBase
OnlMonBase (const std::string &name="NONE")
virtual ~OnlMonBase ()
const std::string Name () const
void Name (const std::string &name)
virtual int Verbosity () const
Static Public Member Functions
static OnlMonClient * instance ()
Private Member Functions
OnlMonClient (const std::string &name="ONLMONCLIENT")
int DoSomething (const std::string &who, const std::string &what, const std::string &opt)
void InitAll ()
Private Attributes
OnlMonHtml * fHtml = nullptr
TH1 * clientrunning = nullptr
TStyle * defaultStyle = nullptr
int display_sizex = 0
int display_sizey = 0
int cosmicrun = 0
int standalone = 0
int cachedrun = 0
std::string runtype = "UNKNOWN"
std::set< std::string > m_MonitorFetchedSet
std::map< std::string,
std::map< const std::string,
ClientHistoList * > > SubsysHisto
std::map< std::string,
std::pair< std::string,
unsigned int > > MonitorHostPorts
std::map< const std::string,
ClientHistoList * > Histo
std::map< const std::string,
OnlMonDraw * > DrawerList
std::vector< std::string > MonitorHosts
Static Private Attributes
static OnlMonClient * __instance = nullptr
Additional Inherited Members
Protected Attributes inherited from OnlMonBase
std::string ThisName
int verbosity = 0
Detailed Description
Definition at line 21 of file OnlMonClient.h.
View newest version in sPHENIX GitHub at line 21 of file OnlMonClient.h
Constructor & Destructor Documentation
OnlMonClient::~OnlMonClient () override
Definition at line 127 of file OnlMonClient.cc.
View newest version in sPHENIX GitHub at line 127 of file OnlMonClient.cc
References __instance, clientrunning, defaultStyle, DrawerList, fHtml, Histo, and OnlMonBase::verbosity.
OnlMonClient::OnlMonClient (const std::string & name = "ONLMONCLIENT") private
Definition at line 65 of file OnlMonClient.cc.
View newest version in sPHENIX GitHub at line 65 of file OnlMonClient.cc
References defaultStyle, InitAll(), and SetStyleToDefault().
Referenced by instance().
Member Function Documentation
void OnlMonClient::AddServerHost (const std::string & hostname)
Definition at line 1165 of file OnlMonClient.cc.
View newest version in sPHENIX GitHub at line 1165 of file OnlMonClient.cc
References MonitorHosts.
Referenced by bbcDrawInit(), cemcDrawInit(), CreateHostList(), daqDrawInit(), exampleDrawInit(), ihcalDrawInit(), inttDrawInit(), ll1DrawInit(), ohcalDrawInit(), pktsizeDrawInit(), sepdDrawInit(), tpcDrawInit(), and zdcDrawInit().
void OnlMonClient::CacheRunDB (const int runno)
Definition at line 1480 of file OnlMonClient.cc.
View newest version in sPHENIX GitHub at line 1480 of file OnlMonClient.cc
References cachedrun, runCondor_beamspot::cmd, con, cosmicrun, odbc::Connection::createStatement(), Acts::UnitConstants::e, odbc::Statement::executeQuery(), odbc::DriverManager::getConnection(), odbc::SQLException::getMessage(), odbc::ResultSet::getString(), odbc::ResultSet::next(), printf(), runtype, standalone, and OnlMonBase::verbosity.
Referenced by isCosmicRun(), isStandalone(), and RunType().
int OnlMonClient::CanvasToPng (TCanvas * canvas, std::string const & filename)
Definition at line 1379 of file OnlMonClient.cc.
View newest version in sPHENIX GitHub at line 1379 of file OnlMonClient.cc
Referenced by MyMonDraw::MakeHtml(), LL1MonDraw::MakeHtml(), DaqMonDraw::MakeHtml(), ZdcMonDraw::MakeHtml(), TpcMonDraw::MakeHtml(), CemcMonDraw::MakeHtml(), SepdMonDraw::MakeHtml(), HcalMonDraw::MakeHtml(), PktSizeMonDraw::MakeHtml(), MvtxMonDraw::MakeHtml(), BbcMonDraw::MakeHtml(), InttMonDraw::MakeHtml(), LL1MonDraw::SavePlot(), MyMonDraw::SavePlot(), ZdcMonDraw::SavePlot(), DaqMonDraw::SavePlot(), TpcMonDraw::SavePlot(), CemcMonDraw::SavePlot(), HcalMonDraw::SavePlot(), SepdMonDraw::SavePlot(), PktSizeMonDraw::SavePlot(), MvtxMonDraw::SavePlot(), BbcMonDraw::SavePlot(), and InttMonDraw::SavePlot().
int OnlMonClient::DoSomething (const std::string & who, const std::string & what, const std::string & opt) private
Definition at line 496 of file OnlMonClient.cc.
View newest version in sPHENIX GitHub at line 496 of file OnlMonClient.cc
References DrawerList, Print(), SetStyleToDefault(), and OnlMonBase::verbosity.
Referenced by Draw(), MakeHtml(), MakePS(), and SavePlot().
int OnlMonClient::Draw (const char * who = "ALL", const char * what = "ALL")
Definition at line 438 of file OnlMonClient.cc.
View newest version in sPHENIX GitHub at line 438 of file OnlMonClient.cc
References DoSomething().
Referenced by bbcDraw(), cemcDraw(), daqDraw(), exampleDraw(), ihcalDraw(), inttDraw(), ll1Draw(), mvtxDraw(), ohcalDraw(), pktsizeDraw(), sepdDraw(), tpcDraw(), and zdcDraw().
time_t OnlMonClient::EventTime (const std::string & which)
Definition at line 1204 of file OnlMonClient.cc.
View newest version in sPHENIX GitHub at line 1204 of file OnlMonClient.cc
References m_MonitorFetchedSet, and OnlMonBase::verbosity.
Referenced by BbcMonDraw::Draw(), MyMonDraw::DrawFirst(), LL1MonDraw::DrawFirst(), DaqMonDraw::DrawFirst(), ZdcMonDraw::DrawFirst(), TpcMonDraw::DrawFirst(), CemcMonDraw::DrawFirst(), SepdMonDraw::DrawFirst(), BbcMonDraw::DrawFirst(), CemcMonDraw::DrawFourth(), PktSizeMonDraw::DrawHistory(), PktSizeMonDraw::DrawOldFirst(), MyMonDraw::DrawSecond(), LL1MonDraw::DrawSecond(), DaqMonDraw::DrawSecond(), ZdcMonDraw::DrawSecond(), TpcMonDraw::DrawSecond(), CemcMonDraw::DrawSecond(), SepdMonDraw::DrawSecond(), BbcMonDraw::DrawSecond(), LL1MonDraw::DrawThird(), SepdMonDraw::DrawThird(), CemcMonDraw::DrawThird(), TpcMonDraw::DrawTPCADCSample(), TpcMonDraw::DrawTPCADCSampleLarge(), TpcMonDraw::DrawTPCchannelphi_layer_weighted(), TpcMonDraw::DrawTPCCheckSum(), TpcMonDraw::DrawTPCMaxADC1D(), TpcMonDraw::DrawTPCMaxADCModule(), TpcMonDraw::DrawTPCModules(), TpcMonDraw::DrawTPCPedestSubADC1D(), TpcMonDraw::DrawTPCRawADC1D(), TpcMonDraw::DrawTPCSampleSize(), TpcMonDraw::DrawTPCXYclusters(), TpcMonDraw::DrawTPCXYclusters_unweighted(), TpcMonDraw::DrawTPCZYclusters(), TpcMonDraw::DrawTPCZYclusters_unweighted(), SepdMonDraw::getTime(), CemcMonDraw::getTime(), HcalMonDraw::getTime(), TpcMonDraw::getTime(), MvtxMonDraw::getTime(), and MvtxMonDraw::PublishStatistics().
time_t OnlMonClient::EventTime (const std::string & servername, const std::string & which)
Definition at line 1219 of file OnlMonClient.cc.
View newest version in sPHENIX GitHub at line 1219 of file OnlMonClient.cc
References BORTIMEBIN, CURRENTTIMEBIN, EORTIMEBIN, getHisto(), configureMap::ibin, and OnlMonBase::verbosity.
std::string OnlMonClient::ExtractSubsystem (const std::string & filename)
Definition at line 1687 of file OnlMonClient.cc.
View newest version in sPHENIX GitHub at line 1687 of file OnlMonClient.cc
References m_MonitorFetchedSet, and path.
Referenced by ReadHistogramsFromFile().
void OnlMonClient::FindAllMonitors ()
Definition at line 1601 of file OnlMonClient.cc.
View newest version in sPHENIX GitHub at line 1601 of file OnlMonClient.cc
References OnlMonDefs::MONIPORT, MonitorHosts, OnlMonDefs::NUMMONIPORT, requestMonitorList(), and OnlMonBase::Verbosity().
int OnlMonClient::FindMonitor (const std::string & name)
Definition at line 1617 of file OnlMonClient.cc.
View newest version in sPHENIX GitHub at line 1617 of file OnlMonClient.cc
References OnlMonDefs::MONIPORT, MonitorHostPorts, MonitorHosts, OnlMonDefs::NUMMONIPORT, requestMonitorList(), and OnlMonBase::Verbosity().
Referenced by requestHistoBySubSystem().
int OnlMonClient::GetDisplaySizeX () inline
Definition at line 70 of file OnlMonClient.h.
View newest version in sPHENIX GitHub at line 70 of file OnlMonClient.h
References display_sizex.
Referenced by TpotMonDraw::create_canvas(), PomsMainFrame::Draw(), MyMonDraw::MakeCanvas(), LL1MonDraw::MakeCanvas(), DaqMonDraw::MakeCanvas(), ZdcMonDraw::MakeCanvas(), TpcMonDraw::MakeCanvas(), SepdMonDraw::MakeCanvas(), CemcMonDraw::MakeCanvas(), HcalMonDraw::MakeCanvas(), PktSizeMonDraw::MakeCanvas(), BbcMonDraw::MakeCanvas(), and MvtxMonDraw::MakeCanvas().
int OnlMonClient::GetDisplaySizeY () inline
Definition at line 71 of file OnlMonClient.h.
View newest version in sPHENIX GitHub at line 71 of file OnlMonClient.h
References display_sizey.
Referenced by TpotMonDraw::create_canvas(), PomsMainFrame::Draw(), MyMonDraw::MakeCanvas(), LL1MonDraw::MakeCanvas(), DaqMonDraw::MakeCanvas(), ZdcMonDraw::MakeCanvas(), TpcMonDraw::MakeCanvas(), SepdMonDraw::MakeCanvas(), CemcMonDraw::MakeCanvas(), HcalMonDraw::MakeCanvas(), PktSizeMonDraw::MakeCanvas(), BbcMonDraw::MakeCanvas(), and MvtxMonDraw::MakeCanvas().
OnlMonDraw * OnlMonClient::getDrawer (const std::string & name)
Definition at line 935 of file OnlMonClient.cc.
View newest version in sPHENIX GitHub at line 935 of file OnlMonClient.cc
References DrawerList.
TH1 * OnlMonClient::getHisto (const std::string & monitor, const std::string & hname)
Definition at line 946 of file OnlMonClient.cc.
View newest version in sPHENIX GitHub at line 946 of file OnlMonClient.cc
References SubsysHisto.
Referenced by BbcMonDraw::Draw(), MvtxMonDraw::DrawFEE(), MvtxMonDraw::DrawFHR(), SepdMonDraw::DrawFifth(), HcalMonDraw::DrawFifth(), LL1MonDraw::DrawFirst(), MyMonDraw::DrawFirst(), DaqMonDraw::DrawFirst(), ZdcMonDraw::DrawFirst(), TpcMonDraw::DrawFirst(), SepdMonDraw::DrawFirst(), CemcMonDraw::DrawFirst(), HcalMonDraw::DrawFirst(), PktSizeMonDraw::DrawFirst(), BbcMonDraw::DrawFirst(), CemcMonDraw::DrawFourth(), SepdMonDraw::DrawFourth(), HcalMonDraw::DrawFourth(), MvtxMonDraw::DrawGeneral(), PktSizeMonDraw::DrawHistory(), HcalMonDraw::DrawHitMap(), MvtxMonDraw::DrawHitMap(), MvtxMonDraw::DrawOCC(), PktSizeMonDraw::DrawOldFirst(), MyMonDraw::DrawSecond(), LL1MonDraw::DrawSecond(), DaqMonDraw::DrawSecond(), ZdcMonDraw::DrawSecond(), TpcMonDraw::DrawSecond(), SepdMonDraw::DrawSecond(), CemcMonDraw::DrawSecond(), HcalMonDraw::DrawSecond(), BbcMonDraw::DrawSecond(), LL1MonDraw::DrawThird(), CemcMonDraw::DrawThird(), SepdMonDraw::DrawThird(), HcalMonDraw::DrawThird(), HcalMonDraw::DrawTowerAvg(), TpcMonDraw::DrawTPCADCSample(), TpcMonDraw::DrawTPCADCSampleLarge(), TpcMonDraw::DrawTPCchannelphi_layer_weighted(), TpcMonDraw::DrawTPCCheckSum(), TpcMonDraw::DrawTPCMaxADC1D(), TpcMonDraw::DrawTPCMaxADCModule(), TpcMonDraw::DrawTPCModules(), TpcMonDraw::DrawTPCPedestSubADC1D(), TpcMonDraw::DrawTPCRawADC1D(), TpcMonDraw::DrawTPCSampleSize(), TpcMonDraw::DrawTPCXYclusters(), TpcMonDraw::DrawTPCXYclusters_unweighted(), TpcMonDraw::DrawTPCZYclusters(), TpcMonDraw::DrawTPCZYclusters_unweighted(), EventTime(), HcalMonDraw::HandleEvent(), InttMonDraw::PrepGlobalChipHists_NLL(), InttMonDraw::PrepLocalChannelHists_Hitmap(), InttMonDraw::PrepLocalChipHists_Hitmap(), and RunNumber().
int OnlMonClient::HistoToPng (TH1 * histo, std::string const & pngfilename, const char * drawopt = "", const int statopt = 11)
Definition at line 1413 of file OnlMonClient.cc.
View newest version in sPHENIX GitHub at line 1413 of file OnlMonClient.cc
void OnlMonClient::htmlAddMenu (const OnlMonDraw & drawer, const std::string & path, const std::string & relfilename)
Definition at line 1352 of file OnlMonClient.cc.
View newest version in sPHENIX GitHub at line 1352 of file OnlMonClient.cc
References OnlMonHtml::addMenu(), fHtml, OnlMonDraw::Name(), and path.
void OnlMonClient::htmlNamer (const OnlMonDraw & drawer, const std::string & basefilename, const std::string & ext, std::string & fullfilename, std::string & filename)
Definition at line 1360 of file OnlMonClient.cc.
View newest version in sPHENIX GitHub at line 1360 of file OnlMonClient.cc
References fHtml, filename, OnlMonDraw::Name(), and OnlMonHtml::namer().
std::string OnlMonClient::htmlRegisterPage (const OnlMonDraw & drawer, const std::string & path, const std::string & basefilename, const std::string & ext)
Definition at line 1371 of file OnlMonClient.cc.
View newest version in sPHENIX GitHub at line 1371 of file OnlMonClient.cc
References fHtml, OnlMonDraw::Name(), path, and OnlMonHtml::registerPage().
Referenced by MyMonDraw::MakeHtml(), LL1MonDraw::MakeHtml(), DaqMonDraw::MakeHtml(), ZdcMonDraw::MakeHtml(), CemcMonDraw::MakeHtml(), TpcMonDraw::MakeHtml(), HcalMonDraw::MakeHtml(), SepdMonDraw::MakeHtml(), PktSizeMonDraw::MakeHtml(), MvtxMonDraw::MakeHtml(), BbcMonDraw::MakeHtml(), InttMonDraw::MakeHtml(), and SaveLogFile().
void OnlMonClient::InitAll () private
Definition at line 73 of file OnlMonClient.cc.
View newest version in sPHENIX GitHub at line 73 of file OnlMonClient.cc
References clientrunning, display_sizex, display_sizey, fHtml, and i.
Referenced by OnlMonClient().
OnlMonClient * OnlMonClient::instance () static
Definition at line 55 of file OnlMonClient.cc.
View newest version in sPHENIX GitHub at line 55 of file OnlMonClient.cc
References __instance, and OnlMonClient().
Referenced by bbcDraw(), bbcDrawInit(), bbcHtml(), bbcSavePlot(), cemcDraw(), cemcDrawInit(), cemcHtml(), cemcPS(), cemcSavePlot(), CleanUpClient(), TpotMonDraw::create_canvas(), CreateHostList(), daqDraw(), daqDrawInit(), daqHtml(), daqSavePlot(), BbcMonDraw::Draw(), PomsMainFrame::Draw(), TpotMonDraw::draw_time(), MvtxMonDraw::DrawFEE(), MvtxMonDraw::DrawFHR(), SepdMonDraw::DrawFifth(), HcalMonDraw::DrawFifth(), MyMonDraw::DrawFirst(), LL1MonDraw::DrawFirst(), DaqMonDraw::DrawFirst(), ZdcMonDraw::DrawFirst(), TpcMonDraw::DrawFirst(), SepdMonDraw::DrawFirst(), CemcMonDraw::DrawFirst(), HcalMonDraw::DrawFirst(), PktSizeMonDraw::DrawFirst(), BbcMonDraw::DrawFirst(), SepdMonDraw::DrawFourth(), CemcMonDraw::DrawFourth(), HcalMonDraw::DrawFourth(), MvtxMonDraw::DrawGeneral(), InttMonDraw::DrawGlobalChipMap(), InttMonDraw::DrawGlobalLadderMap(), PktSizeMonDraw::DrawHistory(), HcalMonDraw::DrawHitMap(), MvtxMonDraw::DrawHitMap(), MvtxMonDraw::DrawOCC(), PktSizeMonDraw::DrawOldFirst(), MyMonDraw::DrawSecond(), LL1MonDraw::DrawSecond(), DaqMonDraw::DrawSecond(), ZdcMonDraw::DrawSecond(), TpcMonDraw::DrawSecond(), SepdMonDraw::DrawSecond(), CemcMonDraw::DrawSecond(), HcalMonDraw::DrawSecond(), BbcMonDraw::DrawSecond(), LL1MonDraw::DrawThird(), SepdMonDraw::DrawThird(), CemcMonDraw::DrawThird(), HcalMonDraw::DrawThird(), HcalMonDraw::DrawTowerAvg(), TpcMonDraw::DrawTPCADCSample(), TpcMonDraw::DrawTPCADCSampleLarge(), TpcMonDraw::DrawTPCchannelphi_layer_weighted(), TpcMonDraw::DrawTPCCheckSum(), TpcMonDraw::DrawTPCMaxADC1D(), TpcMonDraw::DrawTPCMaxADCModule(), TpcMonDraw::DrawTPCModules(), TpcMonDraw::DrawTPCPedestSubADC1D(), TpcMonDraw::DrawTPCRawADC1D(), TpcMonDraw::DrawTPCSampleSize(), TpcMonDraw::DrawTPCXYclusters(), TpcMonDraw::DrawTPCXYclusters_unweighted(), TpcMonDraw::DrawTPCZYclusters(), TpcMonDraw::DrawTPCZYclusters_unweighted(), exampleDraw(), exampleDrawInit(), exampleHtml(), exampleSavePlot(), PktSizeMonDraw::FillPacketMap(), TpotMonDraw::get_histogram(), SepdMonDraw::getTime(), CemcMonDraw::getTime(), HcalMonDraw::getTime(), TpcMonDraw::getTime(), MvtxMonDraw::getTime(), HcalMonDraw::HandleEvent(), ihcalDraw(), ihcalDrawInit(), ihcalHtml(), ihcalSavePlot(), inttDraw(), inttDrawInit(), inttHtml(), inttSavePlot(), ll1Draw(), ll1DrawInit(), ll1Html(), ll1SavePlot(), MyMonDraw::MakeCanvas(), LL1MonDraw::MakeCanvas(), DaqMonDraw::MakeCanvas(), ZdcMonDraw::MakeCanvas(), TpcMonDraw::MakeCanvas(), CemcMonDraw::MakeCanvas(), SepdMonDraw::MakeCanvas(), HcalMonDraw::MakeCanvas(), PktSizeMonDraw::MakeCanvas(), BbcMonDraw::MakeCanvas(), MvtxMonDraw::MakeCanvas(), MyMonDraw::MakeHtml(), LL1MonDraw::MakeHtml(), ZdcMonDraw::MakeHtml(), DaqMonDraw::MakeHtml(), TpcMonDraw::MakeHtml(), CemcMonDraw::MakeHtml(), SepdMonDraw::MakeHtml(), HcalMonDraw::MakeHtml(), PktSizeMonDraw::MakeHtml(), MvtxMonDraw::MakeHtml(), makehtml(), TpotMonDraw::MakeHtml(), BbcMonDraw::MakeHtml(), InttMonDraw::MakeHtml(), PktSizeMonDraw::MakeNoisyCandidates(), mvtxDraw(), mvtxDrawInit(), mvtxHtml(), mvtxSavePlot(), ohcalDraw(), ohcalDrawInit(), ohcalHtml(), ohcalSavePlot(), pktsizeDraw(), pktsizeDrawInit(), pktsizeHtml(), pktsizeSavePlot(), InttMonDraw::PrepGlobalChipHists_Hitmap(), InttMonDraw::PrepGlobalChipHists_NLL(), InttMonDraw::PrepLocalChannelHists_Hitmap(), InttMonDraw::PrepLocalChipHists_Hitmap(), MyMonDraw::SavePlot(), LL1MonDraw::SavePlot(), DaqMonDraw::SavePlot(), ZdcMonDraw::SavePlot(), CemcMonDraw::SavePlot(), TpcMonDraw::SavePlot(), SepdMonDraw::SavePlot(), HcalMonDraw::SavePlot(), PktSizeMonDraw::SavePlot(), MvtxMonDraw::SavePlot(), TpotMonDraw::SavePlot(), BbcMonDraw::SavePlot(), InttMonDraw::SavePlot(), sepdDraw(), sepdDrawInit(), sepdHtml(), sepdSavePlot(), tpcDraw(), tpcDrawInit(), tpcHtml(), tpcSavePlot(), tpotDraw(), tpotDrawInit(), tpotHtml(), tpotSavePlot(), zdcDraw(), zdcDrawInit(), zdcHtml(), and zdcSavePlot().
int OnlMonClient::isCosmicRun ()
Definition at line 1582 of file OnlMonClient.cc.
View newest version in sPHENIX GitHub at line 1582 of file OnlMonClient.cc
References CacheRunDB(), cosmicrun, and RunNumber().
int OnlMonClient::IsMonitorRunning (const std::string & name)
Definition at line 1649 of file OnlMonClient.cc.
View newest version in sPHENIX GitHub at line 1649 of file OnlMonClient.cc
References MonitorHostPorts, OnlMonDefs::MSGLEN, perf_headwind::name, str, and OnlMonBase::verbosity.
Referenced by requestHistoBySubSystem().
int OnlMonClient::isStandalone ()
Definition at line 1588 of file OnlMonClient.cc.
View newest version in sPHENIX GitHub at line 1588 of file OnlMonClient.cc
References CacheRunDB(), RunNumber(), and standalone.
int OnlMonClient::LocateHistogram (const std::string & hname, const std::string & subsys)
Definition at line 1178 of file OnlMonClient.cc.
View newest version in sPHENIX GitHub at line 1178 of file OnlMonClient.cc
References MonitorHosts, and UpdateServerHistoMap().
Referenced by requestHistoByName(), and requestHistoBySubSystem().
int OnlMonClient::MakeHtml (const char * who = "ALL", const char * what = "ALL")
Definition at line 469 of file OnlMonClient.cc.
View newest version in sPHENIX GitHub at line 469 of file OnlMonClient.cc
References DoSomething(), fHtml, OnlMonHtml::runNumber(), and RunNumber().
Referenced by bbcHtml(), cemcHtml(), daqHtml(), exampleHtml(), ihcalHtml(), inttHtml(), ll1Html(), makehtml(), mvtxHtml(), ohcalHtml(), pktsizeHtml(), sepdHtml(), tpcHtml(), tpotHtml(), and zdcHtml().
int OnlMonClient::MakePS (const char * who = "ALL", const char * what = "ALL")
Definition at line 462 of file OnlMonClient.cc.
View newest version in sPHENIX GitHub at line 462 of file OnlMonClient.cc
References DoSomething().
Referenced by cemcPS().
void OnlMonClient::Print (const char * what = "ALL")
Definition at line 961 of file OnlMonClient.cc.
View newest version in sPHENIX GitHub at line 961 of file OnlMonClient.cc
References DrawerList, Histo, add_histos::histos, MonitorHostPorts, MonitorHosts, and SubsysHisto.
Referenced by DoSomething().
void OnlMonClient::PutHistoInMap (const std::string & hname, const std::string & subsys, const std::string & hostname, const int port)
Definition at line 1140 of file OnlMonClient.cc.
View newest version in sPHENIX GitHub at line 1140 of file OnlMonClient.cc
References entry, ClientHistoList::ServerHost(), ClientHistoList::ServerPort(), and SubsysHisto.
Referenced by UpdateServerHistoMap().
int OnlMonClient::ReadHistogramsFromFile (const std::string & filename)
Definition at line 1257 of file OnlMonClient.cc.
View newest version in sPHENIX GitHub at line 1257 of file OnlMonClient.cc
References ExtractSubsystem(), save(), updateHistoMap(), and OnlMonBase::verbosity.
Referenced by makehtml().
void OnlMonClient::registerDrawer (OnlMonDraw * Drawer)
Definition at line 421 of file OnlMonClient.cc.
View newest version in sPHENIX GitHub at line 421 of file OnlMonClient.cc
References DrawerList, OnlMonDraw::Init(), OnlMonDraw::Name(), and SetStyleToDefault().
Referenced by bbcDrawInit(), cemcDrawInit(), daqDrawInit(), exampleDrawInit(), ihcalDrawInit(), inttDrawInit(), ll1DrawInit(), makehtml(), mvtxDrawInit(), ohcalDrawInit(), pktsizeDrawInit(), sepdDrawInit(), tpcDrawInit(), and zdcDrawInit().
void OnlMonClient::registerHisto (const std::string & hname, const std::string & subsys)
Definition at line 161 of file OnlMonClient.cc.
View newest version in sPHENIX GitHub at line 161 of file OnlMonClient.cc
References entry, SubsysHisto, ClientHistoList::SubSystem(), and OnlMonBase::Verbosity().
Referenced by bbcDrawInit(), cemcDrawInit(), daqDrawInit(), exampleDrawInit(), ihcalDrawInit(), inttDrawInit(), ll1DrawInit(), mvtxDrawInit(), ohcalDrawInit(), pktsizeDrawInit(), sepdDrawInit(), tpcDrawInit(), and zdcDrawInit().
int OnlMonClient::requestHisto (const std::string & what = "ALL", const std::string & hostname = "localhost", const int moniport = OnlMonDefs::MONIPORT)
Definition at line 710 of file OnlMonClient.cc.
View newest version in sPHENIX GitHub at line 710 of file OnlMonClient.cc
References OnlMonDefs::MSGLEN, str, updateHistoMap(), and OnlMonBase::verbosity.
Referenced by requestHistoBySubSystem().
int OnlMonClient::requestHistoByName (const std::string & subsystem, const std::string & what = "ALL")
Definition at line 587 of file OnlMonClient.cc.
View newest version in sPHENIX GitHub at line 587 of file OnlMonClient.cc
References add_histos::histos, LocateHistogram(), OnlMonDefs::MONIPORT, OnlMonDefs::MSGLEN, str, SubsysHisto, updateHistoMap(), OnlMonBase::Verbosity(), and OnlMonBase::verbosity.
Referenced by requestHistoBySubSystem().
int OnlMonClient::requestHistoBySubSystem (const std::string & subsystem, int getall = 0)
Definition at line 210 of file OnlMonClient.cc.
View newest version in sPHENIX GitHub at line 210 of file OnlMonClient.cc
References FindMonitor(), Histo, add_histos::histos, IsMonitorRunning(), LocateHistogram(), m_MonitorFetchedSet, MonitorHostPorts, requestHisto(), requestHistoByName(), requestHistoList(), SubsysHisto, and OnlMonBase::Verbosity().
Referenced by bbcDraw(), bbcDrawInit(), cemcDraw(), cemcDrawInit(), daqDraw(), daqDrawInit(), exampleDraw(), exampleDrawInit(), ihcalDraw(), ihcalDrawInit(), inttDraw(), inttDrawInit(), ll1Draw(), ll1DrawInit(), mvtxDraw(), mvtxDrawInit(), ohcalDraw(), ohcalDrawInit(), pktsizeDraw(), pktsizeDrawInit(), sepdDraw(), sepdDrawInit(), tpcDraw(), tpcDrawInit(), zdcDraw(), and zdcDrawInit().
int OnlMonClient::requestHistoList (const std::string & subsys, const std::string & hostname, const int moniport, std::list< std::string > & histolist)
Definition at line 821 of file OnlMonClient.cc.
View newest version in sPHENIX GitHub at line 821 of file OnlMonClient.cc
References OnlMonDefs::MSGLEN, str, updateHistoMap(), OnlMonBase::Verbosity(), and OnlMonBase::verbosity.
Referenced by requestHistoBySubSystem().
int OnlMonClient::requestMonitorList (const std::string & hostname, const int moniport)
Definition at line 771 of file OnlMonClient.cc.
View newest version in sPHENIX GitHub at line 771 of file OnlMonClient.cc
References MonitorHostPorts, OnlMonDefs::MSGLEN, str, and OnlMonBase::Verbosity().
Referenced by FindAllMonitors(), and FindMonitor().
int OnlMonClient::RunNumber ()
Definition at line 1190 of file OnlMonClient.cc.
View newest version in sPHENIX GitHub at line 1190 of file OnlMonClient.cc
References getHisto(), m_MonitorFetchedSet, and RUNNUMBERBIN.
Referenced by BbcMonDraw::Draw(), SepdMonDraw::DrawFifth(), HcalMonDraw::DrawFifth(), MyMonDraw::DrawFirst(), LL1MonDraw::DrawFirst(), ZdcMonDraw::DrawFirst(), DaqMonDraw::DrawFirst(), TpcMonDraw::DrawFirst(), CemcMonDraw::DrawFirst(), SepdMonDraw::DrawFirst(), HcalMonDraw::DrawFirst(), BbcMonDraw::DrawFirst(), SepdMonDraw::DrawFourth(), CemcMonDraw::DrawFourth(), HcalMonDraw::DrawFourth(), InttMonDraw::DrawGlobalChipMap(), InttMonDraw::DrawGlobalLadderMap(), PktSizeMonDraw::DrawHistory(), PktSizeMonDraw::DrawOldFirst(), LL1MonDraw::DrawSecond(), MyMonDraw::DrawSecond(), ZdcMonDraw::DrawSecond(), DaqMonDraw::DrawSecond(), TpcMonDraw::DrawSecond(), CemcMonDraw::DrawSecond(), SepdMonDraw::DrawSecond(), HcalMonDraw::DrawSecond(), BbcMonDraw::DrawSecond(), LL1MonDraw::DrawThird(), SepdMonDraw::DrawThird(), CemcMonDraw::DrawThird(), HcalMonDraw::DrawThird(), TpcMonDraw::DrawTPCADCSample(), TpcMonDraw::DrawTPCADCSampleLarge(), TpcMonDraw::DrawTPCchannelphi_layer_weighted(), TpcMonDraw::DrawTPCCheckSum(), TpcMonDraw::DrawTPCMaxADC1D(), TpcMonDraw::DrawTPCMaxADCModule(), TpcMonDraw::DrawTPCModules(), TpcMonDraw::DrawTPCPedestSubADC1D(), TpcMonDraw::DrawTPCRawADC1D(), TpcMonDraw::DrawTPCSampleSize(), TpcMonDraw::DrawTPCXYclusters(), TpcMonDraw::DrawTPCXYclusters_unweighted(), TpcMonDraw::DrawTPCZYclusters(), TpcMonDraw::DrawTPCZYclusters_unweighted(), PktSizeMonDraw::FillPacketMap(), isCosmicRun(), isStandalone(), MyMonDraw::MakeHtml(), DaqMonDraw::MakeHtml(), ZdcMonDraw::MakeHtml(), InttMonDraw::MakeHtml(), MakeHtml(), PktSizeMonDraw::MakeNoisyCandidates(), MvtxMonDraw::PublishStatistics(), RunType(), SaveLogFile(), MyMonDraw::SavePlot(), LL1MonDraw::SavePlot(), DaqMonDraw::SavePlot(), ZdcMonDraw::SavePlot(), TpcMonDraw::SavePlot(), CemcMonDraw::SavePlot(), SepdMonDraw::SavePlot(), HcalMonDraw::SavePlot(), PktSizeMonDraw::SavePlot(), MvtxMonDraw::SavePlot(), BbcMonDraw::SavePlot(), and InttMonDraw::SavePlot().
std::string OnlMonClient::RunType ()
Definition at line 1595 of file OnlMonClient.cc.
View newest version in sPHENIX GitHub at line 1595 of file OnlMonClient.cc
References CacheRunDB(), RunNumber(), and runtype.
int OnlMonClient::SaveLogFile (const OnlMonDraw & drawer)
Definition at line 1444 of file OnlMonClient.cc.
View newest version in sPHENIX GitHub at line 1444 of file OnlMonClient.cc
References htmlRegisterPage(), infile, OnlMonDraw::Name(), add_histos::outfile, and RunNumber().
Referenced by MyMonDraw::MakeHtml(), ZdcMonDraw::MakeHtml(), DaqMonDraw::MakeHtml(), PktSizeMonDraw::MakeHtml(), and InttMonDraw::MakeHtml().
int OnlMonClient::SavePlot (const std::string & who = "ALL", const std::string & what = "ALL")
Definition at line 445 of file OnlMonClient.cc.
View newest version in sPHENIX GitHub at line 445 of file OnlMonClient.cc
References DoSomething(), and OnlMonBase::verbosity.
Referenced by bbcSavePlot(), cemcSavePlot(), daqSavePlot(), exampleSavePlot(), ihcalSavePlot(), inttSavePlot(), ll1SavePlot(), mvtxSavePlot(), ohcalSavePlot(), pktsizeSavePlot(), sepdSavePlot(), tpcSavePlot(), tpotSavePlot(), and zdcSavePlot().
int OnlMonClient::SendCommand (const char * hostname, const int port, const char * cmd)
Definition at line 1296 of file OnlMonClient.cc.
View newest version in sPHENIX GitHub at line 1296 of file OnlMonClient.cc
References OnlMonDefs::MSGLEN, str, and OnlMonBase::verbosity.
void OnlMonClient::SetDisplaySizeX (int xsize) inline
Definition at line 68 of file OnlMonClient.h.
View newest version in sPHENIX GitHub at line 68 of file OnlMonClient.h
References display_sizex.
Referenced by PomsMainFrame::Draw().
void OnlMonClient::SetDisplaySizeY (int ysize) inline
Definition at line 69 of file OnlMonClient.h.
View newest version in sPHENIX GitHub at line 69 of file OnlMonClient.h
References display_sizey.
Referenced by PomsMainFrame::Draw().
int OnlMonClient::SetStyleToDefault ()
Definition at line 1468 of file OnlMonClient.cc.
View newest version in sPHENIX GitHub at line 1468 of file OnlMonClient.cc
References defaultStyle.
Referenced by DoSomething(), OnlMonClient(), and registerDrawer().
void OnlMonClient::updateHistoMap (const std::string & subsys, const std::string & hname, TH1 * h1d)
Definition at line 898 of file OnlMonClient.cc.
View newest version in sPHENIX GitHub at line 898 of file OnlMonClient.cc
References entry, ClientHistoList::Histo(), Histo, SubsysHisto, and OnlMonBase::Verbosity().
Referenced by ReadHistogramsFromFile(), requestHisto(), requestHistoByName(), and requestHistoList().
int OnlMonClient::UpdateServerHistoMap (const std::string & hname, const std::string & subsys, const std::string & hostname)
Definition at line 1060 of file OnlMonClient.cc.
View newest version in sPHENIX GitHub at line 1060 of file OnlMonClient.cc
References OnlMonDefs::MONIPORT, OnlMonDefs::MSGLEN, OnlMonDefs::NUMMONIPORT, PutHistoInMap(), str, and OnlMonBase::verbosity.
Referenced by LocateHistogram().
void OnlMonClient::Verbosity (const int i) override virtual
Reimplemented from OnlMonBase.
Definition at line 1342 of file OnlMonClient.cc.
View newest version in sPHENIX GitHub at line 1342 of file OnlMonClient.cc
References fHtml, testSigmaEff::v, OnlMonBase::verbosity, and OnlMonHtml::verbosity().
Referenced by makehtml().
Member Data Documentation
OnlMonClient * OnlMonClient::__instance = nullptr static private
Definition at line 91 of file OnlMonClient.h.
View newest version in sPHENIX GitHub at line 91 of file OnlMonClient.h
Referenced by instance(), and ~OnlMonClient().
int OnlMonClient::cachedrun = 0 private
Definition at line 100 of file OnlMonClient.h.
View newest version in sPHENIX GitHub at line 100 of file OnlMonClient.h
Referenced by CacheRunDB().
TH1* OnlMonClient::clientrunning = nullptr private
Definition at line 93 of file OnlMonClient.h.
View newest version in sPHENIX GitHub at line 93 of file OnlMonClient.h
Referenced by InitAll(), and ~OnlMonClient().
int OnlMonClient::cosmicrun = 0 private
Definition at line 98 of file OnlMonClient.h.
View newest version in sPHENIX GitHub at line 98 of file OnlMonClient.h
Referenced by CacheRunDB(), and isCosmicRun().
TStyle* OnlMonClient::defaultStyle = nullptr private
Definition at line 94 of file OnlMonClient.h.
View newest version in sPHENIX GitHub at line 94 of file OnlMonClient.h
Referenced by OnlMonClient(), SetStyleToDefault(), and ~OnlMonClient().
int OnlMonClient::display_sizex = 0 private
Definition at line 96 of file OnlMonClient.h.
View newest version in sPHENIX GitHub at line 96 of file OnlMonClient.h
Referenced by GetDisplaySizeX(), InitAll(), and SetDisplaySizeX().
int OnlMonClient::display_sizey = 0 private
Definition at line 97 of file OnlMonClient.h.
View newest version in sPHENIX GitHub at line 97 of file OnlMonClient.h
Referenced by GetDisplaySizeY(), InitAll(), and SetDisplaySizeY().
std::map<const std::string, OnlMonDraw *> OnlMonClient::DrawerList private
Definition at line 107 of file OnlMonClient.h.
View newest version in sPHENIX GitHub at line 107 of file OnlMonClient.h
Referenced by DoSomething(), getDrawer(), Print(), registerDrawer(), and ~OnlMonClient().
OnlMonHtml* OnlMonClient::fHtml = nullptr private
Definition at line 92 of file OnlMonClient.h.
View newest version in sPHENIX GitHub at line 92 of file OnlMonClient.h
Referenced by htmlAddMenu(), htmlNamer(), htmlRegisterPage(), InitAll(), MakeHtml(), Verbosity(), and ~OnlMonClient().
std::map<const std::string, ClientHistoList *> OnlMonClient::Histo private
Definition at line 106 of file OnlMonClient.h.
View newest version in sPHENIX GitHub at line 106 of file OnlMonClient.h
Referenced by Print(), requestHistoBySubSystem(), updateHistoMap(), and ~OnlMonClient().
std::set<std::string> OnlMonClient::m_MonitorFetchedSet private
Definition at line 103 of file OnlMonClient.h.
View newest version in sPHENIX GitHub at line 103 of file OnlMonClient.h
Referenced by EventTime(), ExtractSubsystem(), requestHistoBySubSystem(), and RunNumber().
std::map<std::string, std::pair<std::string, unsigned int> > OnlMonClient::MonitorHostPorts private
Definition at line 105 of file OnlMonClient.h.
View newest version in sPHENIX GitHub at line 105 of file OnlMonClient.h
Referenced by FindMonitor(), IsMonitorRunning(), Print(), requestHistoBySubSystem(), and requestMonitorList().
std::vector<std::string> OnlMonClient::MonitorHosts private
Definition at line 108 of file OnlMonClient.h.
View newest version in sPHENIX GitHub at line 108 of file OnlMonClient.h
Referenced by AddServerHost(), FindAllMonitors(), FindMonitor(), LocateHistogram(), and Print().
std::string OnlMonClient::runtype = "UNKNOWN" private
Definition at line 102 of file OnlMonClient.h.
View newest version in sPHENIX GitHub at line 102 of file OnlMonClient.h
Referenced by CacheRunDB(), and RunType().
int OnlMonClient::standalone = 0 private
Definition at line 99 of file OnlMonClient.h.
View newest version in sPHENIX GitHub at line 99 of file OnlMonClient.h
Referenced by CacheRunDB(), and isStandalone().
std::map<std::string, std::map<const std::string, ClientHistoList *> > OnlMonClient::SubsysHisto private
Definition at line 104 of file OnlMonClient.h.
View newest version in sPHENIX GitHub at line 104 of file OnlMonClient.h
Referenced by getHisto(), Print(), PutHistoInMap(), registerHisto(), requestHistoByName(), requestHistoBySubSystem(), and updateHistoMap().
The documentation for this class was generated from the following files:
OnlMon/blob/main/onlmonclient/OnlMonClient.h
OnlMon/blob/main/onlmonclient/OnlMonClient.cc