Analysis Software: Acts::TGeoMaterialConverter Struct Reference
Acts::TGeoMaterialConverter Struct Reference
#include <acts/blob/sPHENIX/Plugins/TGeo/include/Acts/Plugins/TGeo/TGeoMaterialConverter.hpp>
Classes
struct Options
Nested options struct to steer the conversion process.
Static Public Member Functions
static MaterialSlab materialSlab (const TGeoMaterial &tgMaterial, ActsScalar thicknessIn, ActsScalar thicknessOut, const Options &options)
Helper method to convert a TGeoMaterial into Acts::MaterialSlab.
Detailed Description
Definition at line 23 of file TGeoMaterialConverter.hpp.
View newest version in sPHENIX GitHub at line 23 of file TGeoMaterialConverter.hpp
Member Function Documentation
Acts::MaterialSlab Acts::TGeoMaterialConverter::materialSlab (const TGeoMaterial & tgMaterial, ActsScalar thicknessIn, ActsScalar thicknessOut, const Options & options) static
Helper method to convert a TGeoMaterial into Acts::MaterialSlab.
Parameters
tgMaterial The TGeoMaterial to be converted
thicknessIn The thickness of the ingoing material slab
thicknessOut The thickness of the outgoing material slab
options The conversion options with the unit scalors
Returns
a material slab object
Definition at line 15 of file TGeoMaterialConverter.cpp.
View newest version in sPHENIX GitHub at line 15 of file TGeoMaterialConverter.cpp
References Acts::Material::fromMassDensity(), material, Acts::TGeoMaterialConverter::Options::unitLengthScalor, and Acts::TGeoMaterialConverter::Options::unitMassScalor.
Referenced by Acts::DD4hepDetectorSurfaceFactory::attachSurfaceMaterial(), and Acts::Test::BOOST_AUTO_TEST_CASE().
The documentation for this struct was generated from the following files:
acts/blob/sPHENIX/Plugins/TGeo/include/Acts/Plugins/TGeo/TGeoMaterialConverter.hpp
acts/blob/sPHENIX/Plugins/TGeo/src/TGeoMaterialConverter.cpp