Analysis Software: JetMapv1 Class Reference
JetMapv1 Class Reference
#include <coresoftware/blob/master/simulation/g4simulation/g4jets/JetMapv1.h>
Public Member Functions
JetMapv1 ()
JetMapv1 (const JetMap *jets)
JetMapv1 & operator= (const JetMapv1 &jets)
~JetMapv1 () override
void identify (std::ostream &os=std::cout) const override
void Reset () override
Clear Event.
int isValid () const override
isValid returns non zero if object contains vailid data
PHObject * CloneMe () const override
Virtual copy constructor.
void set_algo (Jet::ALGO algo) override
Jet::ALGO get_algo () const override
void set_par (float par) override
float get_par () const override
bool empty_src () const override
void insert_src (Jet::SRC src) override
ConstSrcIter begin_src () const override
ConstSrcIter find_src (Jet::SRC src) const override
ConstSrcIter end_src () const override
SrcIter begin_src () override
SrcIter find_src (Jet::SRC src) override
SrcIter end_src () override
bool empty () const override
size_t size () const override
size_t count (unsigned int idkey) const override
void clear () override
const Jet * get (unsigned int idkey) const override
Jet * get (unsigned int idkey) override
Jet * insert (Jet *jet) override
insert Jet to the map. Once inserted, the JetMap owns the Jet memory
size_t erase (unsigned int idkey) override
ConstIter begin () const override
ConstIter find (unsigned int idkey) const override
ConstIter end () const override
Iter begin () override
Iter find (unsigned int idkey) override
Iter end () override
Public Member Functions inherited from JetMap
JetMap ()
~JetMap () override
Public Member Functions inherited from PHObject
PHObject ()
ctor
~PHObject () override
dtor
virtual PHObject * clone () const final
PHObject * Clone (const char *newname="") const final
void Copy (TObject &object) const final
virtual int isValid (const float) const
virtual int isValid (const double) const
virtual int isValid (const int) const
virtual int isValid (const unsigned int) const
virtual int isImplemented (const float f) const
virtual int isImplemented (const double f) const
virtual int isImplemented (const int i) const
virtual int isImplemented (const unsigned int i) const
virtual int Integrate () const
virtual int Integrate (PHObject *obj)
virtual void CopyFrom (const PHObject *obj)
Private Member Functions
ClassDefOverride (JetMapv1, 1)
Private Attributes
Jet::ALGO _algo
float _par
std::set< Jet::SRC > _src
typ_JetMap _map
Additional Inherited Members
Public Types inherited from JetMap
typedef std::map< unsigned int,
Jet * > typ_JetMap
typedef typ_JetMap::const_iterator ConstIter
typedef typ_JetMap::iterator Iter
typedef std::set< Jet::SRC >
::const_iterator ConstSrcIter
typedef std::set< Jet::SRC >
::iterator SrcIter
Detailed Description
Definition at line 14 of file JetMapv1.h.
View newest version in sPHENIX GitHub at line 14 of file JetMapv1.h
Constructor & Destructor Documentation
JetMapv1::JetMapv1 ()
Definition at line 15 of file JetMapv1.cc.
View newest version in sPHENIX GitHub at line 15 of file JetMapv1.cc
Referenced by CloneMe().
JetMapv1::JetMapv1 (const JetMap * jets)
Definition at line 23 of file JetMapv1.cc.
View newest version in sPHENIX GitHub at line 23 of file JetMapv1.cc
References _map, _src, assert, JetMap::begin(), JetMap::begin_src(), CloneMe(), JetMap::end(), JetMap::end_src(), and Jet::get_id().
JetMapv1::~JetMapv1 () override
Definition at line 72 of file JetMapv1.cc.
View newest version in sPHENIX GitHub at line 72 of file JetMapv1.cc
References Reset().
Member Function Documentation
ConstIter JetMapv1::begin () const inline override virtual
Reimplemented from JetMap.
Definition at line 62 of file JetMapv1.h.
View newest version in sPHENIX GitHub at line 62 of file JetMapv1.h
References _map.
Referenced by operator=().
Iter JetMapv1::begin () inline override virtual
Reimplemented from JetMap.
Definition at line 66 of file JetMapv1.h.
View newest version in sPHENIX GitHub at line 66 of file JetMapv1.h
References _map.
ConstSrcIter JetMapv1::begin_src () const inline override virtual
Reimplemented from JetMap.
Definition at line 40 of file JetMapv1.h.
View newest version in sPHENIX GitHub at line 40 of file JetMapv1.h
References _src.
Referenced by identify(), and operator=().
SrcIter JetMapv1::begin_src () inline override virtual
Reimplemented from JetMap.
Definition at line 44 of file JetMapv1.h.
View newest version in sPHENIX GitHub at line 44 of file JetMapv1.h
References _src.
JetMapv1::ClassDefOverride (JetMapv1 , 1) private
void JetMapv1::clear () inline override virtual
Reimplemented from JetMap.
Definition at line 53 of file JetMapv1.h.
View newest version in sPHENIX GitHub at line 53 of file JetMapv1.h
References Reset().
PHObject * JetMapv1::CloneMe () const override virtual
Virtual copy constructor.
Reimplemented from JetMap.
Definition at line 90 of file JetMapv1.cc.
View newest version in sPHENIX GitHub at line 90 of file JetMapv1.cc
References JetMapv1().
Referenced by JetMapv1(), and operator=().
size_t JetMapv1::count (unsigned int idkey) const inline override virtual
Reimplemented from JetMap.
Definition at line 52 of file JetMapv1.h.
View newest version in sPHENIX GitHub at line 52 of file JetMapv1.h
References _map.
bool JetMapv1::empty () const inline override virtual
Reimplemented from JetMap.
Definition at line 50 of file JetMapv1.h.
View newest version in sPHENIX GitHub at line 50 of file JetMapv1.h
References _map.
bool JetMapv1::empty_src () const inline override virtual
Reimplemented from JetMap.
Definition at line 37 of file JetMapv1.h.
View newest version in sPHENIX GitHub at line 37 of file JetMapv1.h
References _src.
ConstIter JetMapv1::end () const inline override virtual
Reimplemented from JetMap.
Definition at line 64 of file JetMapv1.h.
View newest version in sPHENIX GitHub at line 64 of file JetMapv1.h
References _map.
Referenced by operator=().
Iter JetMapv1::end () inline override virtual
Reimplemented from JetMap.
Definition at line 68 of file JetMapv1.h.
View newest version in sPHENIX GitHub at line 68 of file JetMapv1.h
References _map.
ConstSrcIter JetMapv1::end_src () const inline override virtual
Reimplemented from JetMap.
Definition at line 42 of file JetMapv1.h.
View newest version in sPHENIX GitHub at line 42 of file JetMapv1.h
References _src.
Referenced by identify(), and operator=().
SrcIter JetMapv1::end_src () inline override virtual
Reimplemented from JetMap.
Definition at line 46 of file JetMapv1.h.
View newest version in sPHENIX GitHub at line 46 of file JetMapv1.h
References _src.
size_t JetMapv1::erase (unsigned int idkey) inline override virtual
Reimplemented from JetMap.
Definition at line 60 of file JetMapv1.h.
View newest version in sPHENIX GitHub at line 60 of file JetMapv1.h
References _map.
ConstIter JetMapv1::find (unsigned int idkey) const inline override virtual
Reimplemented from JetMap.
Definition at line 63 of file JetMapv1.h.
View newest version in sPHENIX GitHub at line 63 of file JetMapv1.h
References _map.
Iter JetMapv1::find (unsigned int idkey) inline override virtual
Reimplemented from JetMap.
Definition at line 67 of file JetMapv1.h.
View newest version in sPHENIX GitHub at line 67 of file JetMapv1.h
References _map.
ConstSrcIter JetMapv1::find_src (Jet::SRC src) const inline override virtual
Reimplemented from JetMap.
Definition at line 41 of file JetMapv1.h.
View newest version in sPHENIX GitHub at line 41 of file JetMapv1.h
References _src.
SrcIter JetMapv1::find_src (Jet::SRC src) inline override virtual
Reimplemented from JetMap.
Definition at line 45 of file JetMapv1.h.
View newest version in sPHENIX GitHub at line 45 of file JetMapv1.h
References _src.
const Jet * JetMapv1::get (unsigned int idkey) const override virtual
Reimplemented from JetMap.
Definition at line 110 of file JetMapv1.cc.
View newest version in sPHENIX GitHub at line 110 of file JetMapv1.cc
References _map.
Jet * JetMapv1::get (unsigned int idkey) override virtual
Reimplemented from JetMap.
Definition at line 117 of file JetMapv1.cc.
View newest version in sPHENIX GitHub at line 117 of file JetMapv1.cc
References _map.
Jet::ALGO JetMapv1::get_algo () const inline override virtual
Reimplemented from JetMap.
Definition at line 30 of file JetMapv1.h.
View newest version in sPHENIX GitHub at line 30 of file JetMapv1.h
References _algo.
Referenced by operator=().
float JetMapv1::get_par () const inline override virtual
Reimplemented from JetMap.
Definition at line 33 of file JetMapv1.h.
View newest version in sPHENIX GitHub at line 33 of file JetMapv1.h
References _par.
Referenced by operator=().
void JetMapv1::identify (std::ostream & os = std::cout) const override virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from JetMap.
Definition at line 96 of file JetMapv1.cc.
View newest version in sPHENIX GitHub at line 96 of file JetMapv1.cc
References _map, _par, begin_src(), end_src(), and i.
Jet * JetMapv1::insert (Jet * jet) override virtual
insert Jet to the map. Once inserted, the JetMap owns the Jet memory
Reimplemented from JetMap.
Definition at line 124 of file JetMapv1.cc.
View newest version in sPHENIX GitHub at line 124 of file JetMapv1.cc
References _map, and index.
void JetMapv1::insert_src (Jet::SRC src) inline override virtual
Reimplemented from JetMap.
Definition at line 38 of file JetMapv1.h.
View newest version in sPHENIX GitHub at line 38 of file JetMapv1.h
References _src.
int JetMapv1::isValid () const inline override virtual
isValid returns non zero if object contains vailid data
Reimplemented from JetMap.
Definition at line 24 of file JetMapv1.h.
View newest version in sPHENIX GitHub at line 24 of file JetMapv1.h
JetMapv1 & JetMapv1::operator= (const JetMapv1 & jets)
Definition at line 46 of file JetMapv1.cc.
View newest version in sPHENIX GitHub at line 46 of file JetMapv1.cc
References _algo, _map, _par, _src, assert, begin(), begin_src(), CloneMe(), end(), end_src(), get_algo(), Jet::get_id(), get_par(), and Reset().
void JetMapv1::Reset () override virtual
Clear Event.
Reimplemented from PHObject.
Definition at line 77 of file JetMapv1.cc.
View newest version in sPHENIX GitHub at line 77 of file JetMapv1.cc
References _algo, _map, _par, _src, and Jet::NONE.
Referenced by clear(), operator=(), and ~JetMapv1().
void JetMapv1::set_algo (Jet::ALGO algo) inline override virtual
Reimplemented from JetMap.
Definition at line 29 of file JetMapv1.h.
View newest version in sPHENIX GitHub at line 29 of file JetMapv1.h
References _algo.
void JetMapv1::set_par (float par) inline override virtual
Reimplemented from JetMap.
Definition at line 32 of file JetMapv1.h.
View newest version in sPHENIX GitHub at line 32 of file JetMapv1.h
References _par.
size_t JetMapv1::size (void) const inline override virtual
Reimplemented from JetMap.
Definition at line 51 of file JetMapv1.h.
View newest version in sPHENIX GitHub at line 51 of file JetMapv1.h
References _map.
Member Data Documentation
Jet::ALGO JetMapv1::_algo private
Definition at line 71 of file JetMapv1.h.
View newest version in sPHENIX GitHub at line 71 of file JetMapv1.h
Referenced by get_algo(), operator=(), Reset(), and set_algo().
typ_JetMap JetMapv1::_map private
Definition at line 74 of file JetMapv1.h.
View newest version in sPHENIX GitHub at line 74 of file JetMapv1.h
Referenced by begin(), count(), empty(), end(), erase(), find(), get(), identify(), insert(), JetMapv1(), operator=(), Reset(), and size().
float JetMapv1::_par private
Definition at line 72 of file JetMapv1.h.
View newest version in sPHENIX GitHub at line 72 of file JetMapv1.h
Referenced by get_par(), identify(), operator=(), Reset(), and set_par().
std::set<Jet::SRC> JetMapv1::_src private
Definition at line 73 of file JetMapv1.h.
View newest version in sPHENIX GitHub at line 73 of file JetMapv1.h
Referenced by begin_src(), empty_src(), end_src(), find_src(), insert_src(), JetMapv1(), operator=(), and Reset().
The documentation for this class was generated from the following files:
coresoftware/blob/master/simulation/g4simulation/g4jets/JetMapv1.h
coresoftware/blob/master/simulation/g4simulation/g4jets/JetMapv1.cc