Analysis Software: TSQLUrl Class Reference
TSQLUrl Class Reference
#include <RDBC/blob/master/include/RDBC/TSQLUrl.h>
Public Member Functions
TSQLUrl ()
TSQLUrl (const TString &url)
TSQLUrl (const TString &dsn, const TString &description)
TSQLUrl (const TSQLUrl &url)
virtual ~TSQLUrl ()
TSQLUrl & operator= (const TSQLUrl &url)
operator const char * ()
TSQLUrl & operator= (const char *s)
TString GetDSN () const
TString GetUrl () const
TString GetProtocol () const
TString GetSubProtocol () const
TString GetDriver () const
TString GetHost () const
TString GetFile () const
TString GetAnchor () const
TString GetOptions () const
TString GetDescription () const
Int_t GetPort () const
Bool_t IsValid () const
Bool_t IsDynamicDSN () const
void AddOption (const TString &opt)
virtual void Print (Option_t *option="") const
virtual void ls (Option_t *option="") const
virtual const char * GetName () const
virtual const char * GetTitle () const
void Throw (TSQLException *e)
Private Attributes
TSQLUrlParser * fParser
Detailed Description
Definition at line 20 of file TSQLUrl.h.
View newest version in sPHENIX GitHub at line 20 of file TSQLUrl.h
Constructor & Destructor Documentation
TSQLUrl::TSQLUrl () inline
Definition at line 26 of file TSQLUrl.h.
View newest version in sPHENIX GitHub at line 26 of file TSQLUrl.h
References fParser.
TSQLUrl::TSQLUrl (const TString & url)
Definition at line 791 of file TSQLUrl.cxx.
View newest version in sPHENIX GitHub at line 791 of file TSQLUrl.cxx
References fParser.
TSQLUrl::TSQLUrl (const TString & dsn, const TString & description)
Definition at line 824 of file TSQLUrl.cxx.
View newest version in sPHENIX GitHub at line 824 of file TSQLUrl.cxx
References description, and fParser.
TSQLUrl::TSQLUrl (const TSQLUrl & url)
Definition at line 844 of file TSQLUrl.cxx.
View newest version in sPHENIX GitHub at line 844 of file TSQLUrl.cxx
References fParser.
TSQLUrl::~TSQLUrl () virtual
Definition at line 835 of file TSQLUrl.cxx.
View newest version in sPHENIX GitHub at line 835 of file TSQLUrl.cxx
References fParser.
Member Function Documentation
void TSQLUrl::AddOption (const TString & opt)
Definition at line 969 of file TSQLUrl.cxx.
View newest version in sPHENIX GitHub at line 969 of file TSQLUrl.cxx
References fParser.
Referenced by TSQLDriverManager::GetConnection().
TString TSQLUrl::GetAnchor () const
Definition at line 920 of file TSQLUrl.cxx.
View newest version in sPHENIX GitHub at line 920 of file TSQLUrl.cxx
References fParser.
Referenced by TSQLDriverManager::GetConnection().
TString TSQLUrl::GetDescription () const
Definition at line 936 of file TSQLUrl.cxx.
View newest version in sPHENIX GitHub at line 936 of file TSQLUrl.cxx
References fParser.
Referenced by GetTitle().
TString TSQLUrl::GetDriver () const
Definition at line 895 of file TSQLUrl.cxx.
View newest version in sPHENIX GitHub at line 895 of file TSQLUrl.cxx
References fParser.
Referenced by TSQLDriverManager::GetConnection().
TString TSQLUrl::GetDSN () const
Definition at line 864 of file TSQLUrl.cxx.
View newest version in sPHENIX GitHub at line 864 of file TSQLUrl.cxx
References fParser.
Referenced by TSQLDriverManager::GetConnection(), and GetName().
TString TSQLUrl::GetFile () const
Definition at line 912 of file TSQLUrl.cxx.
View newest version in sPHENIX GitHub at line 912 of file TSQLUrl.cxx
References fParser.
Referenced by TSQLImportClient::TSQLImportClient().
TString TSQLUrl::GetHost () const
Definition at line 904 of file TSQLUrl.cxx.
View newest version in sPHENIX GitHub at line 904 of file TSQLUrl.cxx
References fParser.
Referenced by TSQLImportClient::TSQLImportClient().
const char * TSQLUrl::GetName () const virtual
Definition at line 983 of file TSQLUrl.cxx.
View newest version in sPHENIX GitHub at line 983 of file TSQLUrl.cxx
References GetDSN().
TString TSQLUrl::GetOptions () const
Definition at line 928 of file TSQLUrl.cxx.
View newest version in sPHENIX GitHub at line 928 of file TSQLUrl.cxx
References fParser.
Int_t TSQLUrl::GetPort () const
Definition at line 944 of file TSQLUrl.cxx.
View newest version in sPHENIX GitHub at line 944 of file TSQLUrl.cxx
References fParser.
Referenced by TSQLDriverManager::GetConnection().
TString TSQLUrl::GetProtocol () const
Definition at line 879 of file TSQLUrl.cxx.
View newest version in sPHENIX GitHub at line 879 of file TSQLUrl.cxx
References fParser.
Referenced by TSQLDriverManager::GetConnection().
TString TSQLUrl::GetSubProtocol () const
Definition at line 887 of file TSQLUrl.cxx.
View newest version in sPHENIX GitHub at line 887 of file TSQLUrl.cxx
References fParser.
Referenced by TSQLDriverManager::GetConnection().
const char * TSQLUrl::GetTitle () const virtual
Definition at line 991 of file TSQLUrl.cxx.
View newest version in sPHENIX GitHub at line 991 of file TSQLUrl.cxx
References GetDescription().
TString TSQLUrl::GetUrl () const
Definition at line 872 of file TSQLUrl.cxx.
View newest version in sPHENIX GitHub at line 872 of file TSQLUrl.cxx
References fParser.
Referenced by TSQLDriverManager::GetConnection(), and operator const char *().
Bool_t TSQLUrl::IsDynamicDSN () const
Definition at line 961 of file TSQLUrl.cxx.
View newest version in sPHENIX GitHub at line 961 of file TSQLUrl.cxx
References fParser.
Referenced by TSQLDriverManager::GetConnection(), and Print().
Bool_t TSQLUrl::IsValid () const
Definition at line 953 of file TSQLUrl.cxx.
View newest version in sPHENIX GitHub at line 953 of file TSQLUrl.cxx
References fParser.
Referenced by ClassImpQ(), and TSQLDriverManager::GetConnection().
void TSQLUrl::ls (Option_t * option = "") const virtual
Definition at line 999 of file TSQLUrl.cxx.
View newest version in sPHENIX GitHub at line 999 of file TSQLUrl.cxx
References Print().
TSQLUrl::operator const char * () inline
Definition at line 33 of file TSQLUrl.h.
View newest version in sPHENIX GitHub at line 33 of file TSQLUrl.h
References GetUrl(), and str.
TSQLUrl & TSQLUrl::operator= (const TSQLUrl & url)
Definition at line 853 of file TSQLUrl.cxx.
View newest version in sPHENIX GitHub at line 853 of file TSQLUrl.cxx
References fParser.
TSQLUrl& TSQLUrl::operator= (const char * s) inline
Definition at line 34 of file TSQLUrl.h.
View newest version in sPHENIX GitHub at line 34 of file TSQLUrl.h
References summary::url.
void TSQLUrl::Print (Option_t * option = "") const virtual
Definition at line 1007 of file TSQLUrl.cxx.
View newest version in sPHENIX GitHub at line 1007 of file TSQLUrl.cxx
References fclose(), fd, fParser, fprintf(), IsDynamicDSN(), conf::stdout, and str.
Referenced by ls(), and TSQLini::TSQLini().
void TSQLUrl::Throw (TSQLException * e) inline
Definition at line 56 of file TSQLUrl.h.
View newest version in sPHENIX GitHub at line 56 of file TSQLUrl.h
Referenced by ClassImpQ().
Member Data Documentation
TSQLUrlParser* TSQLUrl::fParser private
Definition at line 23 of file TSQLUrl.h.
View newest version in sPHENIX GitHub at line 23 of file TSQLUrl.h
Referenced by AddOption(), GetAnchor(), GetDescription(), GetDriver(), GetDSN(), GetFile(), GetHost(), GetOptions(), GetPort(), GetProtocol(), GetSubProtocol(), GetUrl(), IsDynamicDSN(), IsValid(), operator=(), Print(), TSQLUrl(), and ~TSQLUrl().
The documentation for this class was generated from the following files:
RDBC/blob/master/include/RDBC/TSQLUrl.h
RDBC/blob/master/rdbc/TSQLUrl.cxx