Analysis Software: gtest_help_test.GTestHelpTest Class Reference
gtest_help_test.GTestHelpTest Class Reference
Public Member Functions
def TestHelpFlag
def TestNonHelpFlag
def testPrintsHelpWithFullFlag
def testPrintsHelpWithShortFlag
def testPrintsHelpWithQuestionFlag
def testPrintsHelpWithWindowsStyleQuestionFlag
def testPrintsHelpWithUnrecognizedGoogleTestFlag
def testPrintsHelpWithIncorrectFlagStyle
def testRunsTestsWithoutHelpFlag
def testRunsTestsWithGtestInternalFlag
Detailed Description
Tests the --help flag and its equivalent forms.
Definition at line 98 of file gtest_help_test.py.
View newest version in sPHENIX GitHub at line 98 of file gtest_help_test.py
Member Function Documentation
def gtest_help_test.GTestHelpTest.TestHelpFlag (self, flag)
Verifies correct behavior when help flag is specified.
The right message must be printed and the tests must
skipped when the given flag is specified.
Args:
  flag:  A flag to pass to the binary or None.
Definition at line 101 of file gtest_help_test.py.
View newest version in sPHENIX GitHub at line 101 of file gtest_help_test.py
References gtest_help_test.RunWithFlag().
Referenced by gtest_help_test.GTestHelpTest.testPrintsHelpWithFullFlag(), gtest_help_test.GTestHelpTest.testPrintsHelpWithIncorrectFlagStyle(), gtest_help_test.GTestHelpTest.testPrintsHelpWithQuestionFlag(), gtest_help_test.GTestHelpTest.testPrintsHelpWithShortFlag(), gtest_help_test.GTestHelpTest.testPrintsHelpWithUnrecognizedGoogleTestFlag(), and gtest_help_test.GTestHelpTest.testPrintsHelpWithWindowsStyleQuestionFlag().
def gtest_help_test.GTestHelpTest.TestNonHelpFlag (self, flag)
Verifies correct behavior when no help flag is specified.
Verifies that when no help flag is specified, the tests are run
and the help message is not printed.
Args:
  flag:  A flag to pass to the binary or None.
Definition at line 125 of file gtest_help_test.py.
View newest version in sPHENIX GitHub at line 125 of file gtest_help_test.py
References gtest_help_test.RunWithFlag().
Referenced by gtest_help_test.GTestHelpTest.testRunsTestsWithGtestInternalFlag(), and gtest_help_test.GTestHelpTest.testRunsTestsWithoutHelpFlag().
def gtest_help_test.GTestHelpTest.testPrintsHelpWithFullFlag (self)
Definition at line 139 of file gtest_help_test.py.
View newest version in sPHENIX GitHub at line 139 of file gtest_help_test.py
References gtest_help_test.GTestHelpTest.TestHelpFlag().
def gtest_help_test.GTestHelpTest.testPrintsHelpWithIncorrectFlagStyle (self)
Definition at line 154 of file gtest_help_test.py.
View newest version in sPHENIX GitHub at line 154 of file gtest_help_test.py
References gtest_help_test.GTestHelpTest.TestHelpFlag().
def gtest_help_test.GTestHelpTest.testPrintsHelpWithQuestionFlag (self)
Definition at line 145 of file gtest_help_test.py.
View newest version in sPHENIX GitHub at line 145 of file gtest_help_test.py
References gtest_help_test.GTestHelpTest.TestHelpFlag().
def gtest_help_test.GTestHelpTest.testPrintsHelpWithShortFlag (self)
Definition at line 142 of file gtest_help_test.py.
View newest version in sPHENIX GitHub at line 142 of file gtest_help_test.py
References gtest_help_test.GTestHelpTest.TestHelpFlag().
def gtest_help_test.GTestHelpTest.testPrintsHelpWithUnrecognizedGoogleTestFlag (self)
Definition at line 151 of file gtest_help_test.py.
View newest version in sPHENIX GitHub at line 151 of file gtest_help_test.py
References gtest_help_test.GTestHelpTest.TestHelpFlag().
def gtest_help_test.GTestHelpTest.testPrintsHelpWithWindowsStyleQuestionFlag (self)
Definition at line 148 of file gtest_help_test.py.
View newest version in sPHENIX GitHub at line 148 of file gtest_help_test.py
References gtest_help_test.GTestHelpTest.TestHelpFlag().
def gtest_help_test.GTestHelpTest.testRunsTestsWithGtestInternalFlag (self)
Verifies that the tests are run and no help message is printed when
a flag starting with Google Test prefix and 'internal_' is supplied.
Definition at line 164 of file gtest_help_test.py.
View newest version in sPHENIX GitHub at line 164 of file gtest_help_test.py
References gtest_test_utils.Main(), and gtest_help_test.GTestHelpTest.TestNonHelpFlag().
def gtest_help_test.GTestHelpTest.testRunsTestsWithoutHelpFlag (self)
Verifies that when no help flag is specified, the tests are run
and the help message is not printed.
Definition at line 158 of file gtest_help_test.py.
View newest version in sPHENIX GitHub at line 158 of file gtest_help_test.py
References gtest_help_test.GTestHelpTest.TestNonHelpFlag().
The documentation for this class was generated from the following file:
JETSCAPE/blob/main/external_packages/googletest/googletest/test/gtest_help_test.py