Analysis Software: odbc::Time Class Reference
odbc::Time Class Reference
#include <RDBC/blob/master/include/RDBC/odbc++/types.h>
Public Member Functions
Time (int hour, int minute, int second)
Time ()
Time (time_t t)
Time (const ODBCXX_STRING &str)
Time (const Time &t)
Time & operator= (const Time &t)
virtual ~Time ()
virtual void setTime (time_t t)
time_t getTime () const
void parse (const ODBCXX_STRING &str)
int getHour () const
int getMinute () const
int getSecond () const
void setHour (int h)
void setMinute (int m)
void setSecond (int s)
virtual ODBCXX_STRING toString () const
Protected Member Functions
virtual void _invalid (const char *what, int value)
int _validateHour (int h)
int _validateMinute (int m)
int _validateSecond (int s)
Protected Attributes
int hour_
int minute_
int second_
Detailed Description
An SQL TIME
Definition at line 394 of file types.h.
View newest version in sPHENIX GitHub at line 394 of file types.h
Constructor & Destructor Documentation
odbc::Time::Time (int hour, int minute, int second) inline
Constructor
Definition at line 425 of file types.h.
View newest version in sPHENIX GitHub at line 425 of file types.h
odbc::Time::Time () explicit
Constructor.
Sets the time to now.
odbc::Time::Time (time_t t) inline
Constructor.
Sets the time to the specified time_t value.
Definition at line 441 of file types.h.
View newest version in sPHENIX GitHub at line 441 of file types.h
odbc::Time::Time (const ODBCXX_STRING & str) inline
Constructor.
Sets the time to the specified string in the HH:MM:SS format.
Definition at line 449 of file types.h.
View newest version in sPHENIX GitHub at line 449 of file types.h
References ActsExamples::Options::parse().
odbc::Time::Time (const Time & t) inline
Copy constructor
Definition at line 454 of file types.h.
View newest version in sPHENIX GitHub at line 454 of file types.h
virtual odbc::Time::~Time () inline virtual
Destructor
Definition at line 468 of file types.h.
View newest version in sPHENIX GitHub at line 468 of file types.h
Member Function Documentation
virtual void odbc::Time::_invalid (const char * what, int value) protected virtual
Reimplemented in odbc::Timestamp.
int odbc::Time::_validateHour (int h) inline protected
Definition at line 402 of file types.h.
View newest version in sPHENIX GitHub at line 402 of file types.h
References h.
int odbc::Time::_validateMinute (int m) inline protected
Definition at line 409 of file types.h.
View newest version in sPHENIX GitHub at line 409 of file types.h
References Acts::UnitConstants::m.
int odbc::Time::_validateSecond (int s) inline protected
Definition at line 416 of file types.h.
View newest version in sPHENIX GitHub at line 416 of file types.h
References physmon_simulation::s.
int odbc::Time::getHour () const inline
Gets the hour of this time
Definition at line 480 of file types.h.
View newest version in sPHENIX GitHub at line 480 of file types.h
Referenced by ODBCCallableStatement::GetTime(), ODBCResultSet::GetTime(), ODBCCallableStatement::GetTimestamp(), and ODBCResultSet::GetTimestamp().
int odbc::Time::getMinute () const inline
Gets the minute of this time
Definition at line 485 of file types.h.
View newest version in sPHENIX GitHub at line 485 of file types.h
Referenced by ODBCCallableStatement::GetTime(), ODBCResultSet::GetTime(), ODBCCallableStatement::GetTimestamp(), and ODBCResultSet::GetTimestamp().
int odbc::Time::getSecond () const inline
Gets the second of this time
Definition at line 490 of file types.h.
View newest version in sPHENIX GitHub at line 490 of file types.h
Referenced by ODBCCallableStatement::GetTime(), ODBCResultSet::GetTime(), ODBCCallableStatement::GetTimestamp(), and ODBCResultSet::GetTimestamp().
time_t odbc::Time::getTime () const
Returns the time_t value of 1970-01-01 at this time
Referenced by odbc::Timestamp::getTime().
Time& odbc::Time::operator= (const Time & t) inline
Assignment operator
Definition at line 460 of file types.h.
View newest version in sPHENIX GitHub at line 460 of file types.h
References hour_, minute_, and second_.
Referenced by odbc::Timestamp::operator=().
void odbc::Time::parse (const ODBCXX_STRING & str)
Sets this time from a string in the HH:MM:SS format
void odbc::Time::setHour (int h) inline
Sets the hour of this time
Definition at line 495 of file types.h.
View newest version in sPHENIX GitHub at line 495 of file types.h
void odbc::Time::setMinute (int m) inline
Sets the minute of this time
Definition at line 500 of file types.h.
View newest version in sPHENIX GitHub at line 500 of file types.h
void odbc::Time::setSecond (int s) inline
Sets the second of this time
Definition at line 505 of file types.h.
View newest version in sPHENIX GitHub at line 505 of file types.h
virtual void odbc::Time::setTime (time_t t) virtual
Sets the time to the specified time_t value
Reimplemented in odbc::Timestamp.
virtual ODBCXX_STRING odbc::Time::toString () const virtual
Reimplemented in odbc::Timestamp.
Member Data Documentation
int odbc::Time::hour_ protected
Definition at line 396 of file types.h.
View newest version in sPHENIX GitHub at line 396 of file types.h
Referenced by operator=().
int odbc::Time::minute_ protected
Definition at line 397 of file types.h.
View newest version in sPHENIX GitHub at line 397 of file types.h
Referenced by operator=().
int odbc::Time::second_ protected
Definition at line 398 of file types.h.
View newest version in sPHENIX GitHub at line 398 of file types.h
Referenced by operator=().
The documentation for this class was generated from the following file:
RDBC/blob/master/include/RDBC/odbc++/types.h