Analysis Software: helixResiduals Class Reference
helixResiduals Class Reference
#include <coresoftware/blob/master/offline/packages/TrackingDiagnostics/helixResiduals.h>
Public Member Functions
helixResiduals (const std::string &name="helixResiduals")
~helixResiduals ()
int InitRun (PHCompositeNode *topNode) override
int process_event (PHCompositeNode *) override
int End (PHCompositeNode *) override
Called at the end of all processing.
void set_output_file (const std::string &outputfile)
Public Member Functions inherited from SubsysReco
~SubsysReco () override
virtual int EndRun (const int)
Called at the end of each run.
virtual int Init (PHCompositeNode *)
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
void Print (const std::string &="ALL") const override
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Private Member Functions
int getNodes (PHCompositeNode *topNode)
void fill_residuals (TrackSeed *seed, int seed_id, bool isTpc)
Private Attributes
HelicalFitter * _fitter = nullptr
ActsGeometry * tGeometry = nullptr
TNtuple * ntp_residuals = nullptr
SvtxTrackMap * _tracks = nullptr
TrkrClusterContainer * _clusters = nullptr
TrackSeedContainer * _tpc_seeds = nullptr
TrackSeedContainer * _si_seeds = nullptr
TFile * fout = nullptr
std::string filepath = ""
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = std::numeric_limits<int>::max() - 10
}
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Detailed Description
Definition at line 20 of file helixResiduals.h.
View newest version in sPHENIX GitHub at line 20 of file helixResiduals.h
Constructor & Destructor Documentation
helixResiduals::helixResiduals (const std::string & name = "helixResiduals")
Definition at line 11 of file helixResiduals.cc.
View newest version in sPHENIX GitHub at line 11 of file helixResiduals.cc
References _fitter.
helixResiduals::~helixResiduals () inline
Definition at line 24 of file helixResiduals.h.
View newest version in sPHENIX GitHub at line 24 of file helixResiduals.h
Member Function Documentation
int helixResiduals::End (PHCompositeNode *) override virtual
Called at the end of all processing.
Reimplemented from SubsysReco.
Definition at line 29 of file helixResiduals.cc.
View newest version in sPHENIX GitHub at line 29 of file helixResiduals.cc
References _fitter, fout, and ntp_residuals.
void helixResiduals::fill_residuals (TrackSeed * seed, int seed_id, bool isTpc) private
Definition at line 103 of file helixResiduals.cc.
View newest version in sPHENIX GitHub at line 103 of file helixResiduals.cc
References _clusters, _fitter, INTTVtxZ::dphi, dz, HelicalFitter::fitClusters(), TrackSeed::get_crossing(), HelicalFitter::get_helix_pca(), TrackSeed::get_pt(), TrackSeed::get_px(), TrackSeed::get_py(), TrackSeed::get_pz(), TrkrDefs::getLayer(), HelicalFitter::getTrackletClusters(), i, layer, ntp_residuals, position, physmon_track_finding_ttbar::pt, TrackSeed::size_cluster_keys(), and tGeometry.
Referenced by process_event().
int helixResiduals::getNodes (PHCompositeNode * topNode) private
Definition at line 40 of file helixResiduals.cc.
View newest version in sPHENIX GitHub at line 40 of file helixResiduals.cc
References _clusters, _si_seeds, _tpc_seeds, _tracks, Fun4AllReturnCodes::ABORTEVENT, Fun4AllReturnCodes::EVENT_OK, PHWHERE, and tGeometry.
Referenced by InitRun().
int helixResiduals::InitRun (PHCompositeNode *) override virtual
Called for first event when run number is known. Typically this is where you may want to fetch data from database, because you know the run number.
Reimplemented from SubsysReco.
Definition at line 17 of file helixResiduals.cc.
View newest version in sPHENIX GitHub at line 17 of file helixResiduals.cc
References _fitter, filepath, fout, getNodes(), HelicalFitter::InitRun(), and ntp_residuals.
int helixResiduals::process_event (PHCompositeNode *) override virtual
Called for each event. This is where you do the real work.
Reimplemented from SubsysReco.
Definition at line 75 of file helixResiduals.cc.
View newest version in sPHENIX GitHub at line 75 of file helixResiduals.cc
References _si_seeds, _tpc_seeds, TrackSeedContainer::begin(), TrackSeedContainer::end(), Fun4AllReturnCodes::EVENT_OK, fill_residuals(), TrackSeedContainer::get(), and TrackSeedContainer::index().
void helixResiduals::set_output_file (const std::string & outputfile) inline
Definition at line 29 of file helixResiduals.h.
View newest version in sPHENIX GitHub at line 29 of file helixResiduals.h
References filepath.
Referenced by seedResiduals().
Member Data Documentation
TrkrClusterContainer* helixResiduals::_clusters = nullptr private
Definition at line 42 of file helixResiduals.h.
View newest version in sPHENIX GitHub at line 42 of file helixResiduals.h
Referenced by fill_residuals(), and getNodes().
HelicalFitter* helixResiduals::_fitter = nullptr private
Definition at line 36 of file helixResiduals.h.
View newest version in sPHENIX GitHub at line 36 of file helixResiduals.h
Referenced by End(), fill_residuals(), helixResiduals(), and InitRun().
TrackSeedContainer* helixResiduals::_si_seeds = nullptr private
Definition at line 44 of file helixResiduals.h.
View newest version in sPHENIX GitHub at line 44 of file helixResiduals.h
Referenced by getNodes(), and process_event().
TrackSeedContainer* helixResiduals::_tpc_seeds = nullptr private
Definition at line 43 of file helixResiduals.h.
View newest version in sPHENIX GitHub at line 43 of file helixResiduals.h
Referenced by getNodes(), and process_event().
SvtxTrackMap* helixResiduals::_tracks = nullptr private
Definition at line 41 of file helixResiduals.h.
View newest version in sPHENIX GitHub at line 41 of file helixResiduals.h
Referenced by getNodes().
std::string helixResiduals::filepath = "" private
Definition at line 48 of file helixResiduals.h.
View newest version in sPHENIX GitHub at line 48 of file helixResiduals.h
Referenced by InitRun(), and set_output_file().
TFile* helixResiduals::fout = nullptr private
Definition at line 46 of file helixResiduals.h.
View newest version in sPHENIX GitHub at line 46 of file helixResiduals.h
Referenced by End(), and InitRun().
TNtuple* helixResiduals::ntp_residuals = nullptr private
Definition at line 39 of file helixResiduals.h.
View newest version in sPHENIX GitHub at line 39 of file helixResiduals.h
Referenced by End(), fill_residuals(), and InitRun().
ActsGeometry* helixResiduals::tGeometry = nullptr private
Definition at line 37 of file helixResiduals.h.
View newest version in sPHENIX GitHub at line 37 of file helixResiduals.h
Referenced by fill_residuals(), and getNodes().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/TrackingDiagnostics/helixResiduals.h
coresoftware/blob/master/offline/packages/TrackingDiagnostics/helixResiduals.cc