Analysis Software: DSTCompressor Class Reference
DSTCompressor Class Reference
#include <coresoftware/blob/master/simulation/g4simulation/g4eval/DSTCompressor.h>
Public Types
using bit5 = std::bitset< 5 >
using bit8 = std::bitset< 8 >
using bit10 = std::bitset< 10 >
using bstream = std::vector< u_char >
using Dict = std::vector< float >
using Pars = std::array< double, 4 >
Public Member Functions
DSTCompressor (float phiMean=-3e-5, float phiSigma=0.015, float zMean=-0.00063, float zSigma=0.07036, int nBitPhi=8, int nBitZ=8)
Dict compress_gaussian_dist (double mean, double stddev, int numPoints, int numBits)
unsigned short compressPhi (float inPhi)
unsigned short compressZ (float inZ)
float decompressPhi (unsigned short key)
float decompressZ (unsigned short key)
Public Attributes
const bool debug = false
const int earlybreak = 1000 * 1000 * 1000
const float dist_phi = 0.05
const float dist_z = 3
int phiBits
int zBits
const int wordwidth = 8
Dict phiDict
Dict zDict
Detailed Description
Definition at line 10 of file DSTCompressor.h.
View newest version in sPHENIX GitHub at line 10 of file DSTCompressor.h
Member Typedef Documentation
using DSTCompressor::bit10 = std::bitset<10>
Definition at line 25 of file DSTCompressor.h.
View newest version in sPHENIX GitHub at line 25 of file DSTCompressor.h
using DSTCompressor::bit5 = std::bitset<5>
Definition at line 23 of file DSTCompressor.h.
View newest version in sPHENIX GitHub at line 23 of file DSTCompressor.h
using DSTCompressor::bit8 = std::bitset<8>
Definition at line 24 of file DSTCompressor.h.
View newest version in sPHENIX GitHub at line 24 of file DSTCompressor.h
using DSTCompressor::bstream = std::vector<u_char>
Definition at line 26 of file DSTCompressor.h.
View newest version in sPHENIX GitHub at line 26 of file DSTCompressor.h
using DSTCompressor::Dict = std::vector<float>
Definition at line 27 of file DSTCompressor.h.
View newest version in sPHENIX GitHub at line 27 of file DSTCompressor.h
using DSTCompressor::Pars = std::array<double, 4>
Definition at line 31 of file DSTCompressor.h.
View newest version in sPHENIX GitHub at line 31 of file DSTCompressor.h
Constructor & Destructor Documentation
DSTCompressor::DSTCompressor (float phiMean = -3e-5, float phiSigma = 0.015, float zMean = -0.00063, float zSigma = 0.07036, int nBitPhi = 8, int nBitZ = 8) inline
Definition at line 36 of file DSTCompressor.h.
View newest version in sPHENIX GitHub at line 36 of file DSTCompressor.h
References compress_gaussian_dist(), phiBits, phiDict, zBits, and zDict.
Member Function Documentation
Dict DSTCompressor::compress_gaussian_dist (double mean, double stddev, int numPoints, int numBits) inline
Generate the lookup table with a Gaussian model
Definition at line 52 of file DSTCompressor.h.
View newest version in sPHENIX GitHub at line 52 of file DSTCompressor.h
References Jetscape::approx, and Fatras::Test::generator.
Referenced by DSTCompressor().
unsigned short DSTCompressor::compressPhi (float inPhi) inline
Definition at line 68 of file DSTCompressor.h.
View newest version in sPHENIX GitHub at line 68 of file DSTCompressor.h
References phiDict, and residesIn().
Referenced by DSTEmulator::compress_dx().
unsigned short DSTCompressor::compressZ (float inZ) inline
Definition at line 73 of file DSTCompressor.h.
View newest version in sPHENIX GitHub at line 73 of file DSTCompressor.h
References residesIn(), and zDict.
Referenced by DSTEmulator::compress_dy().
float DSTCompressor::decompressPhi (unsigned short key) inline
Definition at line 78 of file DSTCompressor.h.
View newest version in sPHENIX GitHub at line 78 of file DSTCompressor.h
References phiDict.
Referenced by DSTEmulator::compress_dx().
float DSTCompressor::decompressZ (unsigned short key) inline
Definition at line 83 of file DSTCompressor.h.
View newest version in sPHENIX GitHub at line 83 of file DSTCompressor.h
References zDict.
Referenced by DSTEmulator::compress_dy().
Member Data Documentation
const bool DSTCompressor::debug = false
Definition at line 14 of file DSTCompressor.h.
View newest version in sPHENIX GitHub at line 14 of file DSTCompressor.h
const float DSTCompressor::dist_phi = 0.05
Definition at line 18 of file DSTCompressor.h.
View newest version in sPHENIX GitHub at line 18 of file DSTCompressor.h
const float DSTCompressor::dist_z = 3
Definition at line 19 of file DSTCompressor.h.
View newest version in sPHENIX GitHub at line 19 of file DSTCompressor.h
const int DSTCompressor::earlybreak = 1000 * 1000 * 1000
Definition at line 16 of file DSTCompressor.h.
View newest version in sPHENIX GitHub at line 16 of file DSTCompressor.h
int DSTCompressor::phiBits
Definition at line 20 of file DSTCompressor.h.
View newest version in sPHENIX GitHub at line 20 of file DSTCompressor.h
Referenced by DSTCompressor().
Dict DSTCompressor::phiDict
Definition at line 33 of file DSTCompressor.h.
View newest version in sPHENIX GitHub at line 33 of file DSTCompressor.h
Referenced by compressPhi(), decompressPhi(), and DSTCompressor().
const int DSTCompressor::wordwidth = 8
Definition at line 29 of file DSTCompressor.h.
View newest version in sPHENIX GitHub at line 29 of file DSTCompressor.h
int DSTCompressor::zBits
Definition at line 21 of file DSTCompressor.h.
View newest version in sPHENIX GitHub at line 21 of file DSTCompressor.h
Referenced by DSTCompressor().
Dict DSTCompressor::zDict
Definition at line 34 of file DSTCompressor.h.
View newest version in sPHENIX GitHub at line 34 of file DSTCompressor.h
Referenced by compressZ(), decompressZ(), and DSTCompressor().
The documentation for this class was generated from the following file:
coresoftware/blob/master/simulation/g4simulation/g4eval/DSTCompressor.h