Analysis Software: CaloGeomMapping Class Reference
CaloGeomMapping Class Reference
#include <coresoftware/blob/master/offline/packages/CaloReco/CaloGeomMapping.h>
Public Member Functions
CaloGeomMapping (const std::string &name="CaloGeomMapping")
~CaloGeomMapping () override
int Init (PHCompositeNode *topNode) override
void CreateGeomNode (PHCompositeNode *topNode)
Clean up internals after each event.
void set_detector_name (const std::string &name)
std::string get_detector_name ()
Public Member Functions inherited from SubsysReco
~SubsysReco () override
virtual int End (PHCompositeNode *)
Called at the end of all processing.
virtual int EndRun (const int)
Called at the end of each run.
virtual int InitRun (PHCompositeNode *)
virtual int process_event (PHCompositeNode *)
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
void Print (const std::string &="ALL") const override
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Protected Attributes
std::string m_Detector
std::string m_TowerGeomNodeName
RawTowerGeomContainer * m_RawTowerGeomContainer
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = std::numeric_limits<int>::max() - 10
}
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Detailed Description
Definition at line 13 of file CaloGeomMapping.h.
View newest version in sPHENIX GitHub at line 13 of file CaloGeomMapping.h
Constructor & Destructor Documentation
CaloGeomMapping::CaloGeomMapping (const std::string & name = "CaloGeomMapping")
Definition at line 32 of file CaloGeomMapping.cc.
View newest version in sPHENIX GitHub at line 32 of file CaloGeomMapping.cc
CaloGeomMapping::~CaloGeomMapping () override
Definition at line 41 of file CaloGeomMapping.cc.
View newest version in sPHENIX GitHub at line 41 of file CaloGeomMapping.cc
Member Function Documentation
void CaloGeomMapping::CreateGeomNode (PHCompositeNode * topNode)
Clean up internals after each event.
Called for first event when run number is known. Typically this is where you may want to fetch data from database, because you know the run number. A place to book histograms which have to know the run number.Called for each event. This is where you do the real work.Called at the end of each run. Called at the end of all processing. Reset
Definition at line 117 of file CaloGeomMapping.cc.
View newest version in sPHENIX GitHub at line 117 of file CaloGeomMapping.cc
References RawTowerGeomContainer::add_tower_geometry(), PHCompositeNode::addNode(), RawTowerDefs::convert_name_to_caloid(), Acts::UnitConstants::e, RawTowerDefs::encode_towerid(), PHNodeIterator::findFirst(), RawTowerGeom::get_center_x(), RawTowerGeom::get_center_y(), RawTowerGeom::get_center_z(), RawTowerGeomContainer::get_etabins(), RawTowerGeomContainer::get_etacenter(), RawTowerGeomContainer::get_phibins(), RawTowerGeomContainer::get_phicenter(), RawTowerGeomContainer::get_radius(), RawTowerGeomContainer::get_tower_geometry(), CDBTTree::GetDoubleValue(), CDBInterface::getUrl(), configureMap::ibin, CDBInterface::instance(), CDBTTree::LoadCalibrations(), m_Detector, m_RawTowerGeomContainer, m_TowerGeomNodeName, PHWHERE, physmon_track_finding_ttbar::r, RawTowerGeom::set_center_x(), RawTowerGeom::set_center_y(), RawTowerGeom::set_center_z(), RawTowerGeomContainer::set_etabins(), RawTowerGeomContainer::set_etabounds(), RawTowerGeomContainer::set_phibins(), RawTowerGeomContainer::set_phibounds(), RawTowerGeomContainer::set_radius(), RawTowerGeomContainer::set_thickness(), tg, Fun4AllBase::Verbosity(), ambiguity_solver_full_chain::x, y, and physmon_track_finding_ttbar::z.
Referenced by Init().
std::string CaloGeomMapping::get_detector_name ()
Definition at line 278 of file CaloGeomMapping.cc.
View newest version in sPHENIX GitHub at line 278 of file CaloGeomMapping.cc
References m_Detector.
int CaloGeomMapping::Init (PHCompositeNode * topNode) override virtual
Called during initialization. Typically this is where you can book histograms, and e.g. register them to Fun4AllServer (so they can be output to file using Fun4AllServer::dumpHistos() method).
Reimplemented from SubsysReco.
Definition at line 47 of file CaloGeomMapping.cc.
View newest version in sPHENIX GitHub at line 47 of file CaloGeomMapping.cc
References CreateGeomNode(), Acts::UnitConstants::e, and Fun4AllReturnCodes::EVENT_OK.
void CaloGeomMapping::set_detector_name (const std::string & name)
Definition at line 273 of file CaloGeomMapping.cc.
View newest version in sPHENIX GitHub at line 273 of file CaloGeomMapping.cc
References m_Detector, and perf_headwind::name.
Referenced by Fun4All_CaloProduction().
Member Data Documentation
std::string CaloGeomMapping::m_Detector protected
Definition at line 61 of file CaloGeomMapping.h.
View newest version in sPHENIX GitHub at line 61 of file CaloGeomMapping.h
Referenced by CreateGeomNode(), get_detector_name(), and set_detector_name().
RawTowerGeomContainer* CaloGeomMapping::m_RawTowerGeomContainer protected
Definition at line 63 of file CaloGeomMapping.h.
View newest version in sPHENIX GitHub at line 63 of file CaloGeomMapping.h
Referenced by CreateGeomNode().
std::string CaloGeomMapping::m_TowerGeomNodeName protected
Definition at line 62 of file CaloGeomMapping.h.
View newest version in sPHENIX GitHub at line 62 of file CaloGeomMapping.h
Referenced by CreateGeomNode().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/CaloReco/CaloGeomMapping.h
coresoftware/blob/master/offline/packages/CaloReco/CaloGeomMapping.cc