Analysis Software: MvtxApplyHotDead Class Reference
MvtxApplyHotDead Class Reference
#include <prototype/blob/master/offline/packages/MvtxPrototype1/MvtxApplyHotDead.h>
Public Types
typedef std::pair< unsigned
int, unsigned int > Pixel
typedef std::multimap
< TrkrDefs::hitsetkey, Pixel > PixelMap
typedef PixelMap::const_iterator ConstIterator
Public Member Functions
MvtxApplyHotDead (const std::string &name="MvtxApplyHotDead", const std::string file="")
virtual ~MvtxApplyHotDead ()
int Init (PHCompositeNode *topNode)
module initialization
int InitRun (PHCompositeNode *topNode)
run initialization
int process_event (PHCompositeNode *topNode)
event processing
int End (PHCompositeNode *topNode)
end of process
void PrintHotDeadMap (std::ostream &os=std::cout) const
print pixels to be masked
Public Member Functions inherited from SubsysReco
~SubsysReco () override
virtual int EndRun (const int)
Called at the end of each run.
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
void Print (const std::string &="ALL") const override
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Private Member Functions
void ReadHotDeadFile ()
read in the pixels to mask
Private Attributes
TrkrHitSetContainer * hits_
std::string hdfile_
PixelMap hdmap_
PHTimeServer::timer _timer
Additional Inherited Members
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Detailed Description
Definition at line 14 of file MvtxApplyHotDead.h.
View newest version in sPHENIX GitHub at line 14 of file MvtxApplyHotDead.h
Member Typedef Documentation
typedef PixelMap::const_iterator MvtxApplyHotDead::ConstIterator
Definition at line 20 of file MvtxApplyHotDead.h.
View newest version in sPHENIX GitHub at line 20 of file MvtxApplyHotDead.h
typedef std::pair<unsigned int, unsigned int> MvtxApplyHotDead::Pixel
Definition at line 18 of file MvtxApplyHotDead.h.
View newest version in sPHENIX GitHub at line 18 of file MvtxApplyHotDead.h
typedef std::multimap<TrkrDefs::hitsetkey, Pixel> MvtxApplyHotDead::PixelMap
Definition at line 19 of file MvtxApplyHotDead.h.
View newest version in sPHENIX GitHub at line 19 of file MvtxApplyHotDead.h
Constructor & Destructor Documentation
MvtxApplyHotDead::MvtxApplyHotDead (const std::string & name = "MvtxApplyHotDead", const std::string file = "")
Definition at line 32 of file MvtxApplyHotDead.C.
View newest version in sPHENIX GitHub at line 32 of file MvtxApplyHotDead.C
References ReadHotDeadFile().
virtual MvtxApplyHotDead::~MvtxApplyHotDead () inline virtual
Definition at line 24 of file MvtxApplyHotDead.h.
View newest version in sPHENIX GitHub at line 24 of file MvtxApplyHotDead.h
Member Function Documentation
int MvtxApplyHotDead::End (PHCompositeNode * topNode) inline virtual
end of process
Reimplemented from SubsysReco.
Definition at line 36 of file MvtxApplyHotDead.h.
View newest version in sPHENIX GitHub at line 36 of file MvtxApplyHotDead.h
int MvtxApplyHotDead::Init (PHCompositeNode * topNode) inline virtual
module initialization
Reimplemented from SubsysReco.
Definition at line 27 of file MvtxApplyHotDead.h.
View newest version in sPHENIX GitHub at line 27 of file MvtxApplyHotDead.h
int MvtxApplyHotDead::InitRun (PHCompositeNode * topNode) virtual
run initialization
Reimplemented from SubsysReco.
Definition at line 41 of file MvtxApplyHotDead.C.
View newest version in sPHENIX GitHub at line 41 of file MvtxApplyHotDead.C
References Fun4AllReturnCodes::EVENT_OK.
void MvtxApplyHotDead::PrintHotDeadMap (std::ostream & os = std::cout) const
print pixels to be masked
Definition at line 171 of file MvtxApplyHotDead.C.
View newest version in sPHENIX GitHub at line 171 of file MvtxApplyHotDead.C
References hdmap_, and PHWHERE.
Referenced by Fun4All_TestBeam().
int MvtxApplyHotDead::process_event (PHCompositeNode * topNode) virtual
event processing
Reimplemented from SubsysReco.
Definition at line 46 of file MvtxApplyHotDead.C.
View newest version in sPHENIX GitHub at line 46 of file MvtxApplyHotDead.C
References _timer, Fun4AllReturnCodes::ABORTRUN, Fun4AllReturnCodes::EVENT_OK, PHTimeServer::timer::get(), hdmap_, hits_, PHWHERE, PHTimer::restart(), PHTimer::stop(), and verbosity.
void MvtxApplyHotDead::ReadHotDeadFile () private
read in the pixels to mask
Definition at line 117 of file MvtxApplyHotDead.C.
View newest version in sPHENIX GitHub at line 117 of file MvtxApplyHotDead.C
References col, hdfile_, hdmap_, line, PHWHERE, and verbosity.
Referenced by MvtxApplyHotDead().
Member Data Documentation
PHTimeServer::timer MvtxApplyHotDead::_timer private
Definition at line 53 of file MvtxApplyHotDead.h.
View newest version in sPHENIX GitHub at line 53 of file MvtxApplyHotDead.h
Referenced by process_event().
std::string MvtxApplyHotDead::hdfile_ private
Definition at line 49 of file MvtxApplyHotDead.h.
View newest version in sPHENIX GitHub at line 49 of file MvtxApplyHotDead.h
Referenced by ReadHotDeadFile().
PixelMap MvtxApplyHotDead::hdmap_ private
Definition at line 50 of file MvtxApplyHotDead.h.
View newest version in sPHENIX GitHub at line 50 of file MvtxApplyHotDead.h
Referenced by PrintHotDeadMap(), process_event(), and ReadHotDeadFile().
TrkrHitSetContainer* MvtxApplyHotDead::hits_ private
Definition at line 47 of file MvtxApplyHotDead.h.
View newest version in sPHENIX GitHub at line 47 of file MvtxApplyHotDead.h
Referenced by process_event().
The documentation for this class was generated from the following files:
prototype/blob/master/offline/packages/MvtxPrototype1/MvtxApplyHotDead.h
prototype/blob/master/offline/packages/MvtxPrototype1/MvtxApplyHotDead.C