Analysis Software: my_graph Class Reference
my_graph Class Reference
Public Member Functions
my_graph ()
node new_vertex (int x)
void new_parton (node s, node t, int p)
void save_node_info_handler (ostream *o, node n) const
void save_edge_info_handler (ostream *o, edge n) const
int GetNodeValue (node n) const
int GetEdgeValue (edge n) const
my_graph ()
node new_vertex (int x)
void new_parton (node s, node t, int p)
void save_node_info_handler (ostream *o, node n) const
void save_edge_info_handler (ostream *o, edge n) const
int GetNodeValue (node n) const
int GetEdgeValue (edge n) const
Public Member Functions inherited from graph
graph ()
graph (const graph &G)
graph (const graph &G, const list< node > &nodes)
graph (const graph &G, list< node >::const_iterator it, list< node >::const_iterator end)
virtual ~graph ()
void make_directed ()
void make_undirected ()
bool is_directed () const
bool is_undirected () const
bool is_bidirected (edge_map< edge > &rev) const
bool is_connected () const
bool is_acyclic () const
int number_of_nodes () const
int number_of_edges () const
node center () const
virtual node new_node ()
virtual edge new_edge (node s, node t)
virtual edge new_edge (const list< node > &sources, const list< node > &targets)
void del_node (node n)
void del_all_nodes ()
void del_edge (edge e)
void del_all_edges ()
void clear ()
node_iterator nodes_begin () const
node_iterator nodes_end () const
edge_iterator edges_begin () const
edge_iterator edges_end () const
list< node > all_nodes () const
list< edge > all_edges () const
node choose_node () const
void hide_edge (edge e)
void restore_edge (edge e)
list< edge > hide_node (node n)
void restore_node (node n)
void induced_subgraph (list< node > &subgraph_nodes)
void restore_graph ()
list< edge > insert_reverse_edges ()
GML_error load (const string &filename, bool preserve_ids=false)
GML_error load (const char *filename, bool preserve_ids=false)
int save (const char *filename) const
void save (ostream *file=&cout) const
virtual void pre_new_node_handler ()
virtual void post_new_node_handler (node n)
virtual void pre_del_node_handler (node n)
virtual void post_del_node_handler ()
virtual void pre_hide_node_handler (node n)
virtual void post_hide_node_handler (node n)
virtual void pre_restore_node_handler (node n)
virtual void post_restore_node_handler (node n)
virtual void pre_new_edge_handler (node s, node t)
virtual void post_new_edge_handler (edge e)
virtual void pre_del_edge_handler (edge e)
virtual void post_del_edge_handler (node, node)
virtual void pre_hide_edge_handler (edge e)
virtual void post_hide_edge_handler (edge e)
virtual void pre_restore_edge_handler (edge e)
virtual void post_restore_edge_handler (edge e)
virtual void pre_clear_handler ()
virtual void post_clear_handler ()
virtual void pre_make_directed_handler ()
virtual void post_make_directed_handler ()
virtual void pre_make_undirected_handler ()
virtual void post_make_undirected_handler ()
virtual void pre_graph_save_handler (ostream *os) const
virtual void save_graph_info_handler (ostream *) const
virtual void after_graph_save_handler (ostream *) const
virtual void top_level_key_handler (GML_pair *list)
virtual void load_node_info_handler (node n, GML_pair *list)
virtual void load_edge_info_handler (edge e, GML_pair *list)
virtual void load_graph_info_handler (GML_pair *list)
int number_of_ids (node) const
int number_of_ids (edge) const
Private Attributes
node_map< int > X
edge_map< int > P
Additional Inherited Members
Public Types inherited from graph
typedef list< node >
::const_iterator node_iterator
typedef list< edge >
::const_iterator edge_iterator
Detailed Description
Definition at line 24 of file my_test.cc.
View newest version in sPHENIX GitHub at line 24 of file my_test.cc
Constructor & Destructor Documentation
my_graph::my_graph () inline
Definition at line 28 of file my_test.cc.
View newest version in sPHENIX GitHub at line 28 of file my_test.cc
my_graph::my_graph () inline
Definition at line 15 of file my_test2.cc.
View newest version in sPHENIX GitHub at line 15 of file my_test2.cc
Member Function Documentation
int my_graph::GetEdgeValue (edge n) const inline
Definition at line 24 of file my_test2.cc.
View newest version in sPHENIX GitHub at line 24 of file my_test2.cc
References n, and P.
int my_graph::GetEdgeValue (edge n) const inline
Definition at line 37 of file my_test.cc.
View newest version in sPHENIX GitHub at line 37 of file my_test.cc
References n, and P.
Referenced by main().
int my_graph::GetNodeValue (node n) const inline
Definition at line 23 of file my_test2.cc.
View newest version in sPHENIX GitHub at line 23 of file my_test2.cc
References n, and X.
int my_graph::GetNodeValue (node n) const inline
Definition at line 36 of file my_test.cc.
View newest version in sPHENIX GitHub at line 36 of file my_test.cc
References n, and X.
Referenced by main().
void my_graph::new_parton (node s, node t, int p) inline
Definition at line 18 of file my_test2.cc.
View newest version in sPHENIX GitHub at line 18 of file my_test2.cc
References Acts::UnitConstants::e, graph::new_edge(), merge_hashes::p, and P.
void my_graph::new_parton (node s, node t, int p) inline
Definition at line 31 of file my_test.cc.
View newest version in sPHENIX GitHub at line 31 of file my_test.cc
References Acts::UnitConstants::e, graph::new_edge(), merge_hashes::p, and P.
Referenced by main().
node my_graph::new_vertex (int x) inline
Definition at line 17 of file my_test2.cc.
View newest version in sPHENIX GitHub at line 17 of file my_test2.cc
References n, graph::new_node(), X, and ambiguity_solver_full_chain::x.
node my_graph::new_vertex (int x) inline
Definition at line 30 of file my_test.cc.
View newest version in sPHENIX GitHub at line 30 of file my_test.cc
References n, graph::new_node(), X, and ambiguity_solver_full_chain::x.
Referenced by main().
void my_graph::save_edge_info_handler (ostream * , edge) const inline virtual
Called before the closing bracket of the list belonging to the key of edge e is written. This can be used to write information belonging to the edge e and thus should appear within the list associated with this edge.
Parameters
<code>os</code> output stream.
See Also
graph::save
Reimplemented from graph.
Definition at line 21 of file my_test2.cc.
View newest version in sPHENIX GitHub at line 21 of file my_test2.cc
References n, and P.
void my_graph::save_edge_info_handler (ostream * , edge) const inline virtual
Called before the closing bracket of the list belonging to the key of edge e is written. This can be used to write information belonging to the edge e and thus should appear within the list associated with this edge.
Parameters
<code>os</code> output stream.
See Also
graph::save
Reimplemented from graph.
Definition at line 34 of file my_test.cc.
View newest version in sPHENIX GitHub at line 34 of file my_test.cc
References n, and P.
void my_graph::save_node_info_handler (ostream * , node) const inline virtual
Called before the closing bracket of the list belonging to the key of node n is written. This can be used to write information belonging to the node n and thus should appear within the list associated with this node.
Parameters
<code>os</code> output stream.
See Also
graph::save
Reimplemented from graph.
Definition at line 20 of file my_test2.cc.
View newest version in sPHENIX GitHub at line 20 of file my_test2.cc
References n, and X.
void my_graph::save_node_info_handler (ostream * , node) const inline virtual
Called before the closing bracket of the list belonging to the key of node n is written. This can be used to write information belonging to the node n and thus should appear within the list associated with this node.
Parameters
<code>os</code> output stream.
See Also
graph::save
Reimplemented from graph.
Definition at line 33 of file my_test.cc.
View newest version in sPHENIX GitHub at line 33 of file my_test.cc
References n, and X.
Member Data Documentation
edge_map< int > my_graph::P private
Definition at line 42 of file my_test.cc.
View newest version in sPHENIX GitHub at line 42 of file my_test.cc
Referenced by GetEdgeValue(), new_parton(), and save_edge_info_handler().
node_map< int > my_graph::X private
Definition at line 41 of file my_test.cc.
View newest version in sPHENIX GitHub at line 41 of file my_test.cc
Referenced by GetNodeValue(), new_vertex(), and save_node_info_handler().
The documentation for this class was generated from the following files:
JETSCAPE/blob/main/external_packages/gtl/tests/my_test.cc
JETSCAPE/blob/main/external_packages/gtl/tests/my_test2.cc