Analysis Software: ActsExamples::EDM4hepSimHitReader Exception Reference
ActsExamples::EDM4hepSimHitReader Exception Reference final
#include <acts/blob/sPHENIX/Examples/Io/EDM4hep/include/ActsExamples/Io/EDM4hep/EDM4hepSimHitReader.hpp>
Classes
struct Config
Public Member Functions
EDM4hepSimHitReader (const Config &config, Acts::Logging::Level level)
std::string name () const final
The algorithm name.
std::pair< size_t, size_t > availableEvents () const final
Return the available events range.
ProcessCode read (const ActsExamples::AlgorithmContext &ctx) final
Read out data from the input stream.
const Config & config () const
Readonly access to the config.
Public Member Functions inherited from ActsExamples::IReader
ProcessCode internalExecute (const AlgorithmContext &context) final
ProcessCode initialize () override
Fulfill the algorithm interface.
ProcessCode finalize () override
Fulfill the algorithm interface.
Public Member Functions inherited from ActsExamples::SequenceElement
virtual ~SequenceElement ()=default
const std::vector< const
DataHandleBase * > & writeHandles () const
const std::vector< const
DataHandleBase * > & readHandles () const
Private Member Functions
const Acts::Logger & logger () const
Private Attributes
Config m_cfg
std::pair< size_t, size_t > m_eventsRange
std::unique_ptr< const
Acts::Logger > m_logger
podio::ROOTFrameReader m_reader
WriteDataHandle< SimHitContainer > m_outputSimHits {this, "OutputSimHits"}
WriteDataHandle
< SimParticleContainer > m_outputParticles
Detailed Description
Read in a simhit collection from EDM4hep.
Inpersistent information:
particle ID
after4 momentum
hit index
digitization channel
Definition at line 33 of file EDM4hepSimHitReader.hpp.
View newest version in sPHENIX GitHub at line 33 of file EDM4hepSimHitReader.hpp
Constructor & Destructor Documentation
ActsExamples::EDM4hepSimHitReader::EDM4hepSimHitReader (const Config & config, Acts::Logging::Level level)
Construct the simhit reader.
Parameters
config is the configuration object
level is the logging level
Definition at line 23 of file EDM4hepSimHitReader.cpp.
View newest version in sPHENIX GitHub at line 23 of file EDM4hepSimHitReader.cpp
References ActsExamples::WriteDataHandle< T >::initialize(), ActsExamples::EDM4hepSimHitReader::Config::inputPath, m_cfg, m_eventsRange, m_outputParticles, m_outputSimHits, m_reader, ActsExamples::DataHandleBase::maybeInitialize(), ActsExamples::EDM4hepSimHitReader::Config::outputParticles, and ActsExamples::EDM4hepSimHitReader::Config::outputSimHits.
Member Function Documentation
std::pair< size_t, size_t > ActsExamples::EDM4hepSimHitReader::availableEvents () const final virtual
Return the available events range.
Implements ActsExamples::IReader.
Definition at line 39 of file EDM4hepSimHitReader.cpp.
View newest version in sPHENIX GitHub at line 39 of file EDM4hepSimHitReader.cpp
References m_eventsRange.
const Config& ActsExamples::EDM4hepSimHitReader::config () const inline
Readonly access to the config.
Definition at line 65 of file EDM4hepSimHitReader.hpp.
View newest version in sPHENIX GitHub at line 65 of file EDM4hepSimHitReader.hpp
References m_cfg.
const Acts::Logger& ActsExamples::EDM4hepSimHitReader::logger () const inline private
Definition at line 74 of file EDM4hepSimHitReader.hpp.
View newest version in sPHENIX GitHub at line 74 of file EDM4hepSimHitReader.hpp
References m_logger.
std::string ActsExamples::EDM4hepSimHitReader::name () const final virtual
The algorithm name.
Implements ActsExamples::SequenceElement.
ProcessCode ActsExamples::EDM4hepSimHitReader::read (const ActsExamples::AlgorithmContext & ctx) final virtual
Read out data from the input stream.
Implements ActsExamples::IReader.
Definition at line 43 of file EDM4hepSimHitReader.cpp.
View newest version in sPHENIX GitHub at line 43 of file EDM4hepSimHitReader.cpp
References ACTS_ERROR, ActsExamples::EDM4hepSimHitReader::Config::dd4hepDetector, ActsExamples::AlgorithmContext::eventNumber, ActsExamples::EDM4hepSimHitReader::Config::inputParticles, ActsExamples::EDM4hepSimHitReader::Config::inputSimTrackerHits, m_cfg, m_outputParticles, m_outputSimHits, m_reader, testing::internal::move(), ActsExamples::EDM4hepSimHitReader::Config::outputParticles, merge_hashes::p, particle, particles, ActsExamples::EDM4hepUtil::readParticle(), ActsExamples::EDM4hepUtil::readSimHit(), ActsFatras::Barcode::setParticle(), and SUCCESS.
Member Data Documentation
Config ActsExamples::EDM4hepSimHitReader::m_cfg private
Definition at line 68 of file EDM4hepSimHitReader.hpp.
View newest version in sPHENIX GitHub at line 68 of file EDM4hepSimHitReader.hpp
Referenced by config(), EDM4hepSimHitReader(), and read().
std::pair<size_t, size_t> ActsExamples::EDM4hepSimHitReader::m_eventsRange private
Definition at line 69 of file EDM4hepSimHitReader.hpp.
View newest version in sPHENIX GitHub at line 69 of file EDM4hepSimHitReader.hpp
Referenced by availableEvents(), and EDM4hepSimHitReader().
std::unique_ptr<const Acts::Logger> ActsExamples::EDM4hepSimHitReader::m_logger private
Definition at line 70 of file EDM4hepSimHitReader.hpp.
View newest version in sPHENIX GitHub at line 70 of file EDM4hepSimHitReader.hpp
Referenced by logger().
WriteDataHandle<SimParticleContainer> ActsExamples::EDM4hepSimHitReader::m_outputParticles private
Initial value:
{this,
                                                          "OutputParticles"}
Definition at line 77 of file EDM4hepSimHitReader.hpp.
View newest version in sPHENIX GitHub at line 77 of file EDM4hepSimHitReader.hpp
Referenced by EDM4hepSimHitReader(), and read().
WriteDataHandle<SimHitContainer> ActsExamples::EDM4hepSimHitReader::m_outputSimHits {this, "OutputSimHits"} private
Definition at line 76 of file EDM4hepSimHitReader.hpp.
View newest version in sPHENIX GitHub at line 76 of file EDM4hepSimHitReader.hpp
Referenced by EDM4hepSimHitReader(), and read().
podio::ROOTFrameReader ActsExamples::EDM4hepSimHitReader::m_reader private
Definition at line 72 of file EDM4hepSimHitReader.hpp.
View newest version in sPHENIX GitHub at line 72 of file EDM4hepSimHitReader.hpp
Referenced by EDM4hepSimHitReader(), and read().
The documentation for this exception was generated from the following files:
acts/blob/sPHENIX/Examples/Io/EDM4hep/include/ActsExamples/Io/EDM4hep/EDM4hepSimHitReader.hpp
acts/blob/sPHENIX/Examples/Io/EDM4hep/src/EDM4hepSimHitReader.cpp