Analysis Software: Acts::Experimental::Gx2Fitter< propagator_t, traj_t > Class Template Reference
Acts::Experimental::Gx2Fitter< propagator_t, traj_t > Class Template Reference
#include <acts/blob/sPHENIX/Core/include/Acts/TrackFitting/GlobalChiSquareFitter.hpp>
Classes
class Aborter
Aborter can stay like this probably.
class Actor
Propagator Actor plugin for the GX2F.
Public Member Functions
Gx2Fitter (propagator_t pPropagator, std::unique_ptr< const Logger > _logger=getDefaultLogger("Gx2Fitter", Logging::INFO))
const Logger & logger () const
template<typename source_link_iterator_t , typename start_parameters_t , typename parameters_t = BoundTrackParameters, typename track_container_t , template< typename > class holder_t, bool _isdn = isDirectNavigator>
auto fit (source_link_iterator_t it, source_link_iterator_t end, const start_parameters_t &sParameters, const Gx2FitterOptions< traj_t > &gx2fOptions, TrackContainer< track_container_t, traj_t, holder_t > &trackContainer) const -> std::enable_if_t< !_isdn, Result< typename TrackContainer< track_container_t, traj_t, holder_t >::TrackProxy >>
Public Attributes
m_actorLogger
std::unique_ptr< const Logger > m_logger
The logger instance.
std::unique_ptr< const Logger > m_actorLogger
Private Types
using Gx2fNavigator = typename propagator_t::Navigator
The navigator type.
Static Private Attributes
static constexpr bool isDirectNavigator
The navigator has DirectNavigator type or not.
Detailed Description
template<typename propagator_t, typename traj_t>
class Acts::Experimental::Gx2Fitter< propagator_t, traj_t >
Global Chi Square fitter (GX2F) implementation.
Template Parameters
propagator_t Type of the propagation class
TODO Write description
Definition at line 279 of file GlobalChiSquareFitter.hpp.
View newest version in sPHENIX GitHub at line 279 of file GlobalChiSquareFitter.hpp
Member Typedef Documentation
template<typename propagator_t , typename traj_t > using Acts::Experimental::Gx2Fitter< propagator_t, traj_t >::Gx2fNavigator = typename propagator_t::Navigator private
The navigator type.
Definition at line 281 of file GlobalChiSquareFitter.hpp.
View newest version in sPHENIX GitHub at line 281 of file GlobalChiSquareFitter.hpp
Constructor & Destructor Documentation
template<typename propagator_t , typename traj_t > Acts::Experimental::Gx2Fitter< propagator_t, traj_t >::Gx2Fitter (propagator_t pPropagator, std::unique_ptr< const Logger > _logger = getDefaultLogger("Gx2Fitter< propagator_t, traj_t >", Logging::INFO)) inline
Definition at line 288 of file GlobalChiSquareFitter.hpp.
View newest version in sPHENIX GitHub at line 288 of file GlobalChiSquareFitter.hpp
References testing::internal::move().
Member Function Documentation
template<typename propagator_t , typename traj_t > template<typename source_link_iterator_t , typename start_parameters_t , typename parameters_t = BoundTrackParameters, typename track_container_t , template< typename > class holder_t, bool _isdn = isDirectNavigator> auto Acts::Experimental::Gx2Fitter< propagator_t, traj_t >::fit (source_link_iterator_t it, source_link_iterator_t end, const start_parameters_t & sParameters, const Gx2FitterOptions< traj_t > & gx2fOptions, TrackContainer< track_container_t, traj_t, holder_t > & trackContainer) const -> std::enable_if_t< !_isdn, Result<typename TrackContainer<track_container_t, traj_t, holder_t>::TrackProxy>> inline
Fit implementation
Template Parameters
source_link_iterator_t Iterator type used to pass source links
start_parameters_t Type of the initial parameters
parameters_t Type of parameters used for local parameters
track_container_t Type of the track container backend
holder_t Type defining track container backend ownership
Parameters
it Begin iterator for the fittable uncalibrated measurements
end End iterator for the fittable uncalibrated measurements
sParameters The initial track parameters
gx2fOptions Gx2FitterOptions steering the fit
trackContainer Input track container storage to append into
Note
The input measurements are given in the form of SourceLink s. It's the calibrators job to turn them into calibrated measurements used in the fit.
Returns
the output as an output track
Fully understand Aborter, Actor, Result later
Actual Fitting /////////////////////////////////////////////////////////
Finish Fitting /////////////////////////////////////////////////////////
Definition at line 585 of file GlobalChiSquareFitter.hpp.
View newest version in sPHENIX GitHub at line 585 of file GlobalChiSquareFitter.hpp
References Acts::PropagatorOptions< action_list_t, aborter_list_t >::actionList, ACTS_DEBUG, ACTS_ERROR, Acts::ACTS_VERBOSE(), Acts::calculateTrackQuantities(), distance(), end, geoCtx, it, Acts::MultiTrajectoryTraits::kInvalid, Acts::Experimental::Gx2Fitter< propagator_t, traj_t >::m_actorLogger, magCtx, testing::internal::move(), and physmon_track_finding_ttbar::r.
template<typename propagator_t , typename traj_t > const Logger& Acts::Experimental::Gx2Fitter< propagator_t, traj_t >::logger () const inline
Definition at line 303 of file GlobalChiSquareFitter.hpp.
View newest version in sPHENIX GitHub at line 303 of file GlobalChiSquareFitter.hpp
References Acts::Experimental::Gx2Fitter< propagator_t, traj_t >::m_logger.
Member Data Documentation
template<typename propagator_t , typename traj_t > constexpr bool Acts::Experimental::Gx2Fitter< propagator_t, traj_t >::isDirectNavigator static private
Initial value:
=
      std::is_same<Gx2fNavigator, DirectNavigator>::value
The navigator has DirectNavigator type or not.
Definition at line 284 of file GlobalChiSquareFitter.hpp.
View newest version in sPHENIX GitHub at line 284 of file GlobalChiSquareFitter.hpp
Referenced by Acts::Experimental::Gx2Fitter< propagator_t, traj_t >::Actor< parameters_t >::operator()().
template<typename propagator_t , typename traj_t > Acts::Experimental::Gx2Fitter< propagator_t, traj_t >::m_actorLogger
Initial value:
{m_logger->cloneWithSuffix("Actor")} {}
 private:
  propagator_t m_propagator
Definition at line 293 of file GlobalChiSquareFitter.hpp.
View newest version in sPHENIX GitHub at line 293 of file GlobalChiSquareFitter.hpp
Referenced by Acts::Experimental::Gx2Fitter< propagator_t, traj_t >::fit().
template<typename propagator_t , typename traj_t > std::unique_ptr<const Logger> Acts::Experimental::Gx2Fitter< propagator_t, traj_t >::m_actorLogger
Definition at line 301 of file GlobalChiSquareFitter.hpp.
View newest version in sPHENIX GitHub at line 301 of file GlobalChiSquareFitter.hpp
template<typename propagator_t , typename traj_t > std::unique_ptr<const Logger> Acts::Experimental::Gx2Fitter< propagator_t, traj_t >::m_logger
The logger instance.
Definition at line 300 of file GlobalChiSquareFitter.hpp.
View newest version in sPHENIX GitHub at line 300 of file GlobalChiSquareFitter.hpp
Referenced by Acts::Experimental::Gx2Fitter< propagator_t, traj_t >::logger().
The documentation for this class was generated from the following file:
acts/blob/sPHENIX/Core/include/Acts/TrackFitting/GlobalChiSquareFitter.hpp