Analysis Software: PktSizeMon Class Reference
PktSizeMon Class Reference
#include <OnlMon/blob/main/subsystems/pktsize/PktSizeMon.h>
Public Member Functions
PktSizeMon (const std::string &name="PKTSIZEMON")
virtual ~PktSizeMon ()
int Init ()
int process_event (Event *e)
int Reset ()
int EndRun (const int runno)
void Print (const std::string &what="ALL")
int UpdateDB (const int runno=0)
Public Member Functions inherited from OnlMon
OnlMon (const std::string &name="NONE")
~OnlMon () override
virtual int process_event_common (Event *evt)
virtual int InitCommon (OnlMonServer *se)
virtual void identify (std::ostream &out=std::cout) const
virtual int BeginRunCommon (const int runno, OnlMonServer *se)
virtual int BeginRun (const int)
virtual void SetStatus (const int newstatus)
virtual int ResetEvent ()
virtual void SetMonitorServerId (unsigned int i)
virtual unsigned int MonitorServerId () const
Public Member Functions inherited from OnlMonBase
OnlMonBase (const std::string &name="NONE")
virtual ~OnlMonBase ()
const std::string Name () const
void Name (const std::string &name)
virtual void Verbosity (const int i)
virtual int Verbosity () const
Protected Member Functions
int putmapinhisto ()
Protected Attributes
int nevnts
TH1 * sizehist = nullptr
Packet * plist [10000] {}
PktSizeDBodbc * db
std::map< unsigned int,
unsigned int > packetsize
std::map< std::string,
std::pair< unsigned int,
unsigned int > > granulepacketlimits
std::map< unsigned int,
std::string > dcmgroups
std::map< std::string,
unsigned int > dcmgroupsize
std::map< unsigned int,
std::string > fibergroups
std::map< std::string,
unsigned int > fibergroupsize
Protected Attributes inherited from OnlMon
int status
unsigned int m_MonitorServerId = 0
TH1 * m_LocalFrameWorkVars = nullptr
Protected Attributes inherited from OnlMonBase
std::string ThisName
int verbosity = 0
Additional Inherited Members
Public Types inherited from OnlMon
enum { ACTIVE = -1, OK = 0, WARNING = 1, ERROR = 2 }
Detailed Description
Definition at line 14 of file PktSizeMon.h.
View newest version in sPHENIX GitHub at line 14 of file PktSizeMon.h
Constructor & Destructor Documentation
PktSizeMon::PktSizeMon (const std::string & name = "PKTSIZEMON")
Definition at line 21 of file PktSizeMon.cc.
View newest version in sPHENIX GitHub at line 21 of file PktSizeMon.cc
PktSizeMon::~PktSizeMon () virtual
Definition at line 29 of file PktSizeMon.cc.
View newest version in sPHENIX GitHub at line 29 of file PktSizeMon.cc
References db, and Reset().
Member Function Documentation
int PktSizeMon::EndRun (const int runno) virtual
Reimplemented from OnlMon.
Definition at line 121 of file PktSizeMon.cc.
View newest version in sPHENIX GitHub at line 121 of file PktSizeMon.cc
References putmapinhisto(), and UpdateDB().
int PktSizeMon::Init () virtual
Reimplemented from OnlMon.
Definition at line 47 of file PktSizeMon.cc.
View newest version in sPHENIX GitHub at line 47 of file PktSizeMon.cc
References dcmgroups, fibergroups, PktSizeCommon::filldcmgroups(), PktSizeCommon::fillfibergroups(), PktSizeCommon::fillgranules(), granulepacketlimits, histoname, OnlMonServer::instance(), OnlMonServer::registerHisto(), and sizehist.
void PktSizeMon::Print (const std::string & what = "ALL")
Definition at line 152 of file PktSizeMon.cc.
View newest version in sPHENIX GitHub at line 152 of file PktSizeMon.cc
References dcmgroups, dcmgroupsize, double(), end, fibergroups, fibergroupsize, granulepacketlimits, nevnts, and packetsize.
int PktSizeMon::process_event (Event * e) virtual
Reimplemented from OnlMon.
Definition at line 70 of file PktSizeMon.cc.
View newest version in sPHENIX GitHub at line 70 of file PktSizeMon.cc
References DATAEVENT, Event::getEvtType(), Packet::getIdentifier(), Packet::getLength(), Event::getPacketList(), i, OnlMonServer::instance(), MSG_SEV_ERROR, MSG_SOURCE_DAQMON, nevnts, NUPDATE, packetid, packetsize, plist, putmapinhisto(), OnlMonServer::send_message(), size, and OnlMonBase::verbosity.
int PktSizeMon::putmapinhisto () protected
Definition at line 128 of file PktSizeMon.cc.
View newest version in sPHENIX GitHub at line 128 of file PktSizeMon.cc
References double(), histoname, OnlMonServer::instance(), OnlMonBase::Name(), nbin, nevnts, packetsize, OnlMonServer::registerHisto(), and sizehist.
Referenced by EndRun(), and process_event().
int PktSizeMon::Reset () virtual
Reimplemented from OnlMon.
Definition at line 58 of file PktSizeMon.cc.
View newest version in sPHENIX GitHub at line 58 of file PktSizeMon.cc
References histoname, OnlMonServer::instance(), OnlMonBase::Name(), nevnts, packetsize, OnlMonServer::registerHisto(), and sizehist.
Referenced by ~PktSizeMon().
int PktSizeMon::UpdateDB (const int runno = 0)
Definition at line 255 of file PktSizeMon.cc.
View newest version in sPHENIX GitHub at line 255 of file PktSizeMon.cc
References PktSizeDBodbc::AddRow(), db, granulepacketlimits, OnlMonServer::instance(), MSG_SEV_ERROR, MSG_SOURCE_DAQMON, perf_headwind::name, nevnts, packetsize, OnlMonServer::send_message(), and OnlMonBase::verbosity.
Referenced by EndRun().
Member Data Documentation
PktSizeDBodbc* PktSizeMon::db protected
Definition at line 33 of file PktSizeMon.h.
View newest version in sPHENIX GitHub at line 33 of file PktSizeMon.h
Referenced by UpdateDB(), and ~PktSizeMon().
std::map<unsigned int, std::string> PktSizeMon::dcmgroups protected
Definition at line 36 of file PktSizeMon.h.
View newest version in sPHENIX GitHub at line 36 of file PktSizeMon.h
Referenced by Init(), and Print().
std::map<std::string, unsigned int> PktSizeMon::dcmgroupsize protected
Definition at line 37 of file PktSizeMon.h.
View newest version in sPHENIX GitHub at line 37 of file PktSizeMon.h
Referenced by Print().
std::map<unsigned int, std::string> PktSizeMon::fibergroups protected
Definition at line 38 of file PktSizeMon.h.
View newest version in sPHENIX GitHub at line 38 of file PktSizeMon.h
Referenced by Init(), and Print().
std::map<std::string, unsigned int> PktSizeMon::fibergroupsize protected
Definition at line 39 of file PktSizeMon.h.
View newest version in sPHENIX GitHub at line 39 of file PktSizeMon.h
Referenced by Print().
std::map<std::string, std::pair<unsigned int, unsigned int> > PktSizeMon::granulepacketlimits protected
Definition at line 35 of file PktSizeMon.h.
View newest version in sPHENIX GitHub at line 35 of file PktSizeMon.h
Referenced by Init(), Print(), and UpdateDB().
int PktSizeMon::nevnts protected
Definition at line 30 of file PktSizeMon.h.
View newest version in sPHENIX GitHub at line 30 of file PktSizeMon.h
Referenced by Print(), process_event(), putmapinhisto(), Reset(), and UpdateDB().
std::map<unsigned int, unsigned int> PktSizeMon::packetsize protected
Definition at line 34 of file PktSizeMon.h.
View newest version in sPHENIX GitHub at line 34 of file PktSizeMon.h
Referenced by Print(), process_event(), putmapinhisto(), Reset(), and UpdateDB().
Packet* PktSizeMon::plist[10000] {} protected
Definition at line 32 of file PktSizeMon.h.
View newest version in sPHENIX GitHub at line 32 of file PktSizeMon.h
Referenced by process_event().
TH1* PktSizeMon::sizehist = nullptr protected
Definition at line 31 of file PktSizeMon.h.
View newest version in sPHENIX GitHub at line 31 of file PktSizeMon.h
Referenced by Init(), putmapinhisto(), and Reset().
The documentation for this class was generated from the following files:
OnlMon/blob/main/subsystems/pktsize/PktSizeMon.h
OnlMon/blob/main/subsystems/pktsize/PktSizeMon.cc