Analysis Software: CDBHistos Class Reference
CDBHistos Class Reference
#include <coresoftware/blob/master/offline/database/cdbobjects/CDBHistos.h>
Public Member Functions
CDBHistos ()=default
CDBHistos (const std::string &fname)
~CDBHistos ()
void WriteCDBHistos ()
void Print () const
void LoadCalibrations ()
void registerHisto (TH1 *h1)
TH1 * getHisto (const std::string &name)
Private Attributes
std::string m_Filename
std::map< std::string, TH1 * > m_HistoMap
Detailed Description
Definition at line 9 of file CDBHistos.h.
View newest version in sPHENIX GitHub at line 9 of file CDBHistos.h
Constructor & Destructor Documentation
CDBHistos::CDBHistos () default
CDBHistos::CDBHistos (const std::string & fname) explicit
Definition at line 17 of file CDBHistos.cc.
View newest version in sPHENIX GitHub at line 17 of file CDBHistos.cc
CDBHistos::~CDBHistos ()
Definition at line 22 of file CDBHistos.cc.
View newest version in sPHENIX GitHub at line 22 of file CDBHistos.cc
References m_HistoMap.
Member Function Documentation
TH1 * CDBHistos::getHisto (const std::string & name)
Definition at line 105 of file CDBHistos.cc.
View newest version in sPHENIX GitHub at line 105 of file CDBHistos.cc
References m_HistoMap.
Referenced by EventPlaneReco::Init(), RawClusterPositionCorrection::InitRun(), and Read().
void CDBHistos::LoadCalibrations ()
Definition at line 48 of file CDBHistos.cc.
View newest version in sPHENIX GitHub at line 48 of file CDBHistos.cc
References h1, m_Filename, m_HistoMap, and next.
Referenced by EventPlaneReco::Init(), RawClusterPositionCorrection::InitRun(), and Read().
void CDBHistos::Print () const
Definition at line 83 of file CDBHistos.cc.
View newest version in sPHENIX GitHub at line 83 of file CDBHistos.cc
References m_HistoMap.
Referenced by EventPlaneReco::Init(), and Read().
void CDBHistos::registerHisto (TH1 * h1)
Definition at line 93 of file CDBHistos.cc.
View newest version in sPHENIX GitHub at line 93 of file CDBHistos.cc
References h1, and m_HistoMap.
Referenced by EventPlaneReco::Init(), and TestCDBHistos().
void CDBHistos::WriteCDBHistos ()
Definition at line 31 of file CDBHistos.cc.
View newest version in sPHENIX GitHub at line 31 of file CDBHistos.cc
References f, m_Filename, and m_HistoMap.
Referenced by EventPlaneReco::End(), and TestCDBHistos().
Member Data Documentation
std::string CDBHistos::m_Filename private
Definition at line 22 of file CDBHistos.h.
View newest version in sPHENIX GitHub at line 22 of file CDBHistos.h
Referenced by LoadCalibrations(), and WriteCDBHistos().
std::map<std::string, TH1 *> CDBHistos::m_HistoMap private
Definition at line 23 of file CDBHistos.h.
View newest version in sPHENIX GitHub at line 23 of file CDBHistos.h
Referenced by getHisto(), LoadCalibrations(), Print(), registerHisto(), WriteCDBHistos(), and ~CDBHistos().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/database/cdbobjects/CDBHistos.h
coresoftware/blob/master/offline/database/cdbobjects/CDBHistos.cc