Analysis Software: SvtxTrackInfo Class Reference
SvtxTrackInfo Class Reference
#include <coresoftware/blob/master/offline/packages/trackbase_historic/SvtxTrackInfo.h>
Public Member Functions
~SvtxTrackInfo () override=default
void identify (std::ostream &os=std::cout) const override
int isValid () const override
isValid returns non zero if object contains vailid data
PHObject * CloneMe () const override
Virtual copy constructor.
virtual void CopyFrom (const SvtxTrackInfo &)
copy content from base class
virtual void CopyFrom (SvtxTrackInfo *)
copy content from base class
virtual float get_chisq () const
virtual void set_chisq (float)
virtual uint8_t get_ndf () const
virtual void set_ndf (uint8_t)
virtual uint64_t get_hitbitmap () const
virtual void set_hitbitmap (uint64_t)
virtual float get_x () const
virtual void set_x (float)
virtual float get_y () const
virtual void set_y (float)
virtual float get_z () const
virtual void set_z (float)
virtual float get_pos (unsigned int) const
virtual float get_px () const
virtual void set_px (float)
virtual float get_py () const
virtual void set_py (float)
virtual float get_pz () const
virtual void set_pz (float)
virtual float get_mom (unsigned int) const
virtual float get_p () const
virtual float get_pt () const
virtual float get_eta () const
virtual float get_phi () const
virtual float get_covariance (int, int) const
virtual void set_covariance (int, int, float)
virtual short int get_crossing () const
virtual void set_crossing (short int)
Public Member Functions inherited from PHObject
PHObject ()
ctor
~PHObject () override
dtor
virtual PHObject * clone () const final
PHObject * Clone (const char *newname="") const final
void Copy (TObject &object) const final
virtual void Reset ()
Clear Event.
virtual int Integrate () const
virtual int Integrate (PHObject *)
virtual void CopyFrom (const PHObject *obj)
Private Member Functions
ClassDefOverride (SvtxTrackInfo, 1)
Detailed Description
Definition at line 15 of file SvtxTrackInfo.h.
View newest version in sPHENIX GitHub at line 15 of file SvtxTrackInfo.h
Constructor & Destructor Documentation
SvtxTrackInfo::~SvtxTrackInfo () override default
Member Function Documentation
SvtxTrackInfo::ClassDefOverride (SvtxTrackInfo , 1) private
PHObject* SvtxTrackInfo::CloneMe () const inline override virtual
Virtual copy constructor.
Reimplemented from PHObject.
Reimplemented in SvtxTrackInfo_v1.
Definition at line 27 of file SvtxTrackInfo.h.
View newest version in sPHENIX GitHub at line 27 of file SvtxTrackInfo.h
virtual void SvtxTrackInfo::CopyFrom (const SvtxTrackInfo &) inline virtual
copy content from base class
Reimplemented in SvtxTrackInfo_v1.
Definition at line 33 of file SvtxTrackInfo.h.
View newest version in sPHENIX GitHub at line 33 of file SvtxTrackInfo.h
Referenced by TrackInfoContainer_v1::add_trackinfo().
virtual void SvtxTrackInfo::CopyFrom (SvtxTrackInfo *) inline virtual
copy content from base class
Reimplemented in SvtxTrackInfo_v1.
Definition at line 38 of file SvtxTrackInfo.h.
View newest version in sPHENIX GitHub at line 38 of file SvtxTrackInfo.h
virtual float SvtxTrackInfo::get_chisq () const inline virtual
Reimplemented in SvtxTrackInfo_v1.
Definition at line 46 of file SvtxTrackInfo.h.
View newest version in sPHENIX GitHub at line 46 of file SvtxTrackInfo.h
Referenced by SvtxTrackInfo_v1::CopyFrom().
virtual float SvtxTrackInfo::get_covariance (int , int) const inline virtual
Reimplemented in SvtxTrackInfo_v1.
Definition at line 84 of file SvtxTrackInfo.h.
View newest version in sPHENIX GitHub at line 84 of file SvtxTrackInfo.h
Referenced by SvtxTrackInfo_v1::CopyFrom().
virtual short int SvtxTrackInfo::get_crossing () const inline virtual
Reimplemented in SvtxTrackInfo_v1.
Definition at line 87 of file SvtxTrackInfo.h.
View newest version in sPHENIX GitHub at line 87 of file SvtxTrackInfo.h
Referenced by SvtxTrackInfo_v1::CopyFrom().
virtual float SvtxTrackInfo::get_eta () const inline virtual
Reimplemented in SvtxTrackInfo_v1.
Definition at line 81 of file SvtxTrackInfo.h.
View newest version in sPHENIX GitHub at line 81 of file SvtxTrackInfo.h
virtual uint64_t SvtxTrackInfo::get_hitbitmap () const inline virtual
Reimplemented in SvtxTrackInfo_v1.
Definition at line 53 of file SvtxTrackInfo.h.
View newest version in sPHENIX GitHub at line 53 of file SvtxTrackInfo.h
Referenced by SvtxTrackInfo_v1::CopyFrom().
virtual float SvtxTrackInfo::get_mom (unsigned int) const inline virtual
Reimplemented in SvtxTrackInfo_v1.
Definition at line 77 of file SvtxTrackInfo.h.
View newest version in sPHENIX GitHub at line 77 of file SvtxTrackInfo.h
virtual uint8_t SvtxTrackInfo::get_ndf () const inline virtual
Reimplemented in SvtxTrackInfo_v1.
Definition at line 49 of file SvtxTrackInfo.h.
View newest version in sPHENIX GitHub at line 49 of file SvtxTrackInfo.h
Referenced by SvtxTrackInfo_v1::CopyFrom().
virtual float SvtxTrackInfo::get_p () const inline virtual
Reimplemented in SvtxTrackInfo_v1.
Definition at line 79 of file SvtxTrackInfo.h.
View newest version in sPHENIX GitHub at line 79 of file SvtxTrackInfo.h
virtual float SvtxTrackInfo::get_phi () const inline virtual
Reimplemented in SvtxTrackInfo_v1.
Definition at line 82 of file SvtxTrackInfo.h.
View newest version in sPHENIX GitHub at line 82 of file SvtxTrackInfo.h
virtual float SvtxTrackInfo::get_pos (unsigned int) const inline virtual
Reimplemented in SvtxTrackInfo_v1.
Definition at line 66 of file SvtxTrackInfo.h.
View newest version in sPHENIX GitHub at line 66 of file SvtxTrackInfo.h
virtual float SvtxTrackInfo::get_pt () const inline virtual
Reimplemented in SvtxTrackInfo_v1.
Definition at line 80 of file SvtxTrackInfo.h.
View newest version in sPHENIX GitHub at line 80 of file SvtxTrackInfo.h
virtual float SvtxTrackInfo::get_px () const inline virtual
Reimplemented in SvtxTrackInfo_v1.
Definition at line 68 of file SvtxTrackInfo.h.
View newest version in sPHENIX GitHub at line 68 of file SvtxTrackInfo.h
Referenced by SvtxTrackInfo_v1::CopyFrom().
virtual float SvtxTrackInfo::get_py () const inline virtual
Reimplemented in SvtxTrackInfo_v1.
Definition at line 71 of file SvtxTrackInfo.h.
View newest version in sPHENIX GitHub at line 71 of file SvtxTrackInfo.h
Referenced by SvtxTrackInfo_v1::CopyFrom().
virtual float SvtxTrackInfo::get_pz () const inline virtual
Reimplemented in SvtxTrackInfo_v1.
Definition at line 74 of file SvtxTrackInfo.h.
View newest version in sPHENIX GitHub at line 74 of file SvtxTrackInfo.h
Referenced by SvtxTrackInfo_v1::CopyFrom().
virtual float SvtxTrackInfo::get_x () const inline virtual
Reimplemented in SvtxTrackInfo_v1.
Definition at line 57 of file SvtxTrackInfo.h.
View newest version in sPHENIX GitHub at line 57 of file SvtxTrackInfo.h
Referenced by SvtxTrackInfo_v1::CopyFrom().
virtual float SvtxTrackInfo::get_y () const inline virtual
Reimplemented in SvtxTrackInfo_v1.
Definition at line 60 of file SvtxTrackInfo.h.
View newest version in sPHENIX GitHub at line 60 of file SvtxTrackInfo.h
Referenced by SvtxTrackInfo_v1::CopyFrom().
virtual float SvtxTrackInfo::get_z () const inline virtual
Reimplemented in SvtxTrackInfo_v1.
Definition at line 63 of file SvtxTrackInfo.h.
View newest version in sPHENIX GitHub at line 63 of file SvtxTrackInfo.h
Referenced by SvtxTrackInfo_v1::CopyFrom().
void SvtxTrackInfo::identify (std::ostream & os = std::cout) const inline override virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from PHObject.
Reimplemented in SvtxTrackInfo_v1.
Definition at line 21 of file SvtxTrackInfo.h.
View newest version in sPHENIX GitHub at line 21 of file SvtxTrackInfo.h
References os.
int SvtxTrackInfo::isValid () const inline override virtual
isValid returns non zero if object contains vailid data
Reimplemented from PHObject.
Definition at line 26 of file SvtxTrackInfo.h.
View newest version in sPHENIX GitHub at line 26 of file SvtxTrackInfo.h
virtual void SvtxTrackInfo::set_chisq (float) inline virtual
Reimplemented in SvtxTrackInfo_v1.
Definition at line 47 of file SvtxTrackInfo.h.
View newest version in sPHENIX GitHub at line 47 of file SvtxTrackInfo.h
virtual void SvtxTrackInfo::set_covariance (int , int , float) inline virtual
Reimplemented in SvtxTrackInfo_v1.
Definition at line 85 of file SvtxTrackInfo.h.
View newest version in sPHENIX GitHub at line 85 of file SvtxTrackInfo.h
virtual void SvtxTrackInfo::set_crossing (short int) inline virtual
Reimplemented in SvtxTrackInfo_v1.
Definition at line 88 of file SvtxTrackInfo.h.
View newest version in sPHENIX GitHub at line 88 of file SvtxTrackInfo.h
virtual void SvtxTrackInfo::set_hitbitmap (uint64_t) inline virtual
Reimplemented in SvtxTrackInfo_v1.
Definition at line 54 of file SvtxTrackInfo.h.
View newest version in sPHENIX GitHub at line 54 of file SvtxTrackInfo.h
virtual void SvtxTrackInfo::set_ndf (uint8_t) inline virtual
Reimplemented in SvtxTrackInfo_v1.
Definition at line 50 of file SvtxTrackInfo.h.
View newest version in sPHENIX GitHub at line 50 of file SvtxTrackInfo.h
virtual void SvtxTrackInfo::set_px (float) inline virtual
Reimplemented in SvtxTrackInfo_v1.
Definition at line 69 of file SvtxTrackInfo.h.
View newest version in sPHENIX GitHub at line 69 of file SvtxTrackInfo.h
virtual void SvtxTrackInfo::set_py (float) inline virtual
Reimplemented in SvtxTrackInfo_v1.
Definition at line 72 of file SvtxTrackInfo.h.
View newest version in sPHENIX GitHub at line 72 of file SvtxTrackInfo.h
virtual void SvtxTrackInfo::set_pz (float) inline virtual
Reimplemented in SvtxTrackInfo_v1.
Definition at line 75 of file SvtxTrackInfo.h.
View newest version in sPHENIX GitHub at line 75 of file SvtxTrackInfo.h
virtual void SvtxTrackInfo::set_x (float) inline virtual
Reimplemented in SvtxTrackInfo_v1.
Definition at line 58 of file SvtxTrackInfo.h.
View newest version in sPHENIX GitHub at line 58 of file SvtxTrackInfo.h
virtual void SvtxTrackInfo::set_y (float) inline virtual
Reimplemented in SvtxTrackInfo_v1.
Definition at line 61 of file SvtxTrackInfo.h.
View newest version in sPHENIX GitHub at line 61 of file SvtxTrackInfo.h
virtual void SvtxTrackInfo::set_z (float) inline virtual
Reimplemented in SvtxTrackInfo_v1.
Definition at line 64 of file SvtxTrackInfo.h.
View newest version in sPHENIX GitHub at line 64 of file SvtxTrackInfo.h
The documentation for this class was generated from the following file:
coresoftware/blob/master/offline/packages/trackbase_historic/SvtxTrackInfo.h