Analysis Software: MvtxHitPruner Class Reference
MvtxHitPruner Class Reference
Clusterizer for the MVTX.
#include <coresoftware/blob/master/offline/packages/mvtx/MvtxHitPruner.h>
Public Types
typedef std::pair< unsigned
int, unsigned int > pixel
Public Member Functions
MvtxHitPruner (const std::string &name="MvtxHitPruner")
~MvtxHitPruner () override
int Init (PHCompositeNode *) override
module initialization
int InitRun (PHCompositeNode *) override
run initialization
int process_event (PHCompositeNode *) override
event processing
int End (PHCompositeNode *) override
end of process
Public Member Functions inherited from SubsysReco
~SubsysReco () override
virtual int EndRun (const int)
Called at the end of each run.
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
void Print (const std::string &="ALL") const override
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Private Attributes
TrkrHitSetContainer * m_hits
Additional Inherited Members
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Detailed Description
Clusterizer for the MVTX.
Definition at line 22 of file MvtxHitPruner.h.
View newest version in sPHENIX GitHub at line 22 of file MvtxHitPruner.h
Member Typedef Documentation
typedef std::pair<unsigned int, unsigned int> MvtxHitPruner::pixel
Definition at line 25 of file MvtxHitPruner.h.
View newest version in sPHENIX GitHub at line 25 of file MvtxHitPruner.h
Constructor & Destructor Documentation
MvtxHitPruner::MvtxHitPruner (const std::string & name = "MvtxHitPruner")
Definition at line 58 of file MvtxHitPruner.cc.
View newest version in sPHENIX GitHub at line 58 of file MvtxHitPruner.cc
MvtxHitPruner::~MvtxHitPruner () inline override
Definition at line 28 of file MvtxHitPruner.h.
View newest version in sPHENIX GitHub at line 28 of file MvtxHitPruner.h
Member Function Documentation
int MvtxHitPruner::End (PHCompositeNode *) inline override virtual
end of process
Reimplemented from SubsysReco.
Definition at line 40 of file MvtxHitPruner.h.
View newest version in sPHENIX GitHub at line 40 of file MvtxHitPruner.h
int MvtxHitPruner::Init (PHCompositeNode *) inline override virtual
module initialization
Reimplemented from SubsysReco.
Definition at line 31 of file MvtxHitPruner.h.
View newest version in sPHENIX GitHub at line 31 of file MvtxHitPruner.h
int MvtxHitPruner::InitRun (PHCompositeNode *) override virtual
run initialization
Reimplemented from SubsysReco.
Definition at line 64 of file MvtxHitPruner.cc.
View newest version in sPHENIX GitHub at line 64 of file MvtxHitPruner.cc
References Fun4AllReturnCodes::EVENT_OK, and Fun4AllBase::Verbosity().
int MvtxHitPruner::process_event (PHCompositeNode * topNode) override virtual
event processing
Reimplemented from SubsysReco.
Definition at line 82 of file MvtxHitPruner.cc.
View newest version in sPHENIX GitHub at line 82 of file MvtxHitPruner.cc
References Fun4AllReturnCodes::ABORTRUN, TrkrHitSet::addHitSpecificKey(), Fun4AllReturnCodes::EVENT_OK, TrkrHitSetContainer::findHitSet(), TrkrHitSetContainer::findOrAddHitSet(), MvtxDefs::genHitSetKey(), MvtxDefs::getChipId(), TrkrHitSet::getHit(), TrkrHitSet::getHits(), TrkrHitSetContainer::getHitSets(), TrkrDefs::getLayer(), MvtxDefs::getStaveId(), MvtxDefs::getStrobeId(), it, layer, m_hits, TrkrDefs::mvtxId, PHWHERE, TrkrHitSetContainer::removeHitSet(), TrkrHit::setAdc(), TrkrHitSet::size(), and Fun4AllBase::Verbosity().
Member Data Documentation
TrkrHitSetContainer* MvtxHitPruner::m_hits private
Definition at line 45 of file MvtxHitPruner.h.
View newest version in sPHENIX GitHub at line 45 of file MvtxHitPruner.h
Referenced by process_event().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/mvtx/MvtxHitPruner.h
coresoftware/blob/master/offline/packages/mvtx/MvtxHitPruner.cc