Analysis Software: ActsExamples::HelloRandomAlgorithm Class Reference
ActsExamples::HelloRandomAlgorithm Class Reference
An example algorithm that uses the random number generator to generate data.
#include <acts/blob/sPHENIX/Examples/Run/HelloWorld/HelloRandomAlgorithm.hpp>
Classes
struct Config
Public Member Functions
HelloRandomAlgorithm (const Config &cfg, Acts::Logging::Level level=Acts::Logging::INFO)
ActsExamples::ProcessCode execute (const AlgorithmContext &ctx) const override
Public Member Functions inherited from ActsExamples::IAlgorithm
IAlgorithm (std::string name, Acts::Logging::Level level=Acts::Logging::INFO)
std::string name () const override
The algorithm name.
ProcessCode internalExecute (const AlgorithmContext &context) final
ProcessCode initialize () override
Initialize the algorithm.
ProcessCode finalize () override
Finalize the algorithm.
Public Attributes
WriteDataHandle
< HelloDataCollection > m_writeHandle {this, "Output"}
Private Attributes
Config m_cfg
Additional Inherited Members
Protected Member Functions inherited from ActsExamples::IAlgorithm
const Acts::Logger & logger () const
Detailed Description
An example algorithm that uses the random number generator to generate data.
Definition at line 24 of file HelloRandomAlgorithm.hpp.
View newest version in sPHENIX GitHub at line 24 of file HelloRandomAlgorithm.hpp
Constructor & Destructor Documentation
ActsExamples::HelloRandomAlgorithm::HelloRandomAlgorithm (const Config & cfg, Acts::Logging::Level level = Acts::Logging::INFO)
Definition at line 18 of file HelloRandomAlgorithm.cpp.
View newest version in sPHENIX GitHub at line 18 of file HelloRandomAlgorithm.cpp
References ActsExamples::WriteDataHandle< T >::initialize(), m_cfg, m_writeHandle, ActsExamples::HelloRandomAlgorithm::Config::output, and ActsExamples::HelloRandomAlgorithm::Config::randomNumbers.
Member Function Documentation
ActsExamples::ProcessCode ActsExamples::HelloRandomAlgorithm::execute (const AlgorithmContext & context) const override virtual
Execute the algorithm for one event.
This function must be implemented by subclasses.
Implements ActsExamples::IAlgorithm.
Definition at line 30 of file HelloRandomAlgorithm.cpp.
View newest version in sPHENIX GitHub at line 30 of file HelloRandomAlgorithm.cpp
References ACTS_INFO, ACTS_VERBOSE, Acts::EventDataView3DTest::gauss(), m_cfg(), testing::internal::move(), conftest::rng(), SUCCESS, and ambiguity_solver_full_chain::x.
Member Data Documentation
Config ActsExamples::HelloRandomAlgorithm::m_cfg private
Definition at line 47 of file HelloRandomAlgorithm.hpp.
View newest version in sPHENIX GitHub at line 47 of file HelloRandomAlgorithm.hpp
Referenced by HelloRandomAlgorithm().
WriteDataHandle<HelloDataCollection> ActsExamples::HelloRandomAlgorithm::m_writeHandle {this, "Output"}
Definition at line 44 of file HelloRandomAlgorithm.hpp.
View newest version in sPHENIX GitHub at line 44 of file HelloRandomAlgorithm.hpp
Referenced by HelloRandomAlgorithm().
The documentation for this class was generated from the following files:
acts/blob/sPHENIX/Examples/Run/HelloWorld/HelloRandomAlgorithm.hpp
acts/blob/sPHENIX/Examples/Run/HelloWorld/HelloRandomAlgorithm.cpp