Analysis Software: Acts::Test Namespace Reference
Acts::Test Namespace Reference
Namespaces
namespace benchmark_tools_internal
namespace events
namespace float_compare_internal
namespace Layers
namespace states
Classes
struct MicroBenchmarkResult
struct CubicBVHTrackingGeometry
struct CubicTrackingGeometry
struct CylindricalTrackingGeometry
class DetectorElementStub
class LineSurfaceStub
struct MeasurementResolution
Measurement resolution configuration for a single detector type.
struct Measurements
Result struct for generated measurements and outliers.
struct MeasurementsCreator
Propagator action to create smeared measurements.
class MultiTrajectoryTestsCommon
struct TestSourceLink
class TestSpacePoint
Space point representation of a measurement suitable for track seeding.
struct TestTrackState
struct DummySequenceElement
struct GenericReadWriteTool
struct Cell1D
struct Cluster1D
struct Cell2D
struct Cluster2D
class AlignmentContext
class AlignableDetectorElement
struct StepVolumeCollector
struct LayerCreatorFixture
struct SurfaceArrayCreatorFixture
struct CallableHook
class SurfaceMaterialStub
struct MockPropagatorState
Simplified propagator state.
struct MockNavigator
struct PropState
Simplified propagator state.
struct EndOfWorld
Aborter for the case that a particle leaves the detector or reaches a custom made threshold.
struct StepCollector
Data collector while propagation.
struct PlaneSelector
struct StepWiseActor
the bound state propagation
struct SteppingState
mockup of stepping state
struct Stepper
mockup of stepping state
struct NavigationState
mockup of navigation state
struct Options
mockup of the Propagator Options
struct PropagatorState
mockup of propagtor state
struct PerpendicularMeasure
An observer that measures the perpendicular distance.
struct SurfaceObserver
An observer that measures the perpendicular distance.
struct StepperState
Simplified stepper state.
struct NaivgatorState
Simplified navigator.
struct State
Simplified propagator state.
struct Navigator
Simplified navigator.
struct SurfaceArrayFixture
struct Detector
class Object
struct fsm
struct fsm2
struct S1
struct S2
struct S3
struct E1
struct E2
class E3
struct fsm3
struct MyStruct
struct functor
struct TreeFixture1DDoubleInt1
struct TreeFixture1DDoubleInt2
struct TreeFixture2DDoubleInt1
struct TreeFixture3DDoubleInt1
struct TreeFixture3DDoubleInt2
struct TreeFixture3DDoubleInt3
struct TreeFixture10DDoubleInt1
struct TreeFixture3DDoubleString1
struct TreeFixture1DIntInt1
struct TreeFixture2DIntInt1
struct variadic_struct
struct tuple_helper
struct NoCopy
struct E
struct M
struct M2
struct M3
struct M4
class M5
struct N
struct N2
struct N3
struct A
struct A2
struct B
struct C
struct D
struct InputTrack
struct VertexInfo
Helper struct to store reference vertex related information.
struct PlyElement
Ply element struct.
struct RootGeometry
struct to load the global geometry
Typedefs
using MeasurementResolutionMap = Acts::GeometryHierarchyMap< MeasurementResolution >
Measurement resolution configuration for a full detector geometry.
using TestSpacePointContainer = std::vector< TestSpacePoint >
Container of space points.
using Rectangle = std::array< int, 4 >
using SrfVec = std::vector< std::shared_ptr< const Surface >>
using Box = Acts::Volume::BoundingBox
using Ray = Acts::Ray< double, 3 >
using grid_t = detail::Grid< Acts::Material::ParametersVector, detail::EquidistantAxis, detail::EquidistantAxis >
using RecordedMaterial = std::vector< std::pair< Acts::Material, Acts::Vector3 >>
using EAxis = Acts::detail::EquidistantAxis
using Grid2D = Acts::detail::Grid< Acts::AccumulatedVolumeMaterial, EAxis, EAxis >
using Grid3D = Acts::detail::Grid< Acts::AccumulatedVolumeMaterial, EAxis, EAxis, EAxis >
using MaterialGrid2D = Acts::detail::Grid< Acts::Material::ParametersVector, EAxis, EAxis >
using MaterialGrid3D = Acts::detail::Grid< Acts::Material::ParametersVector, EAxis, EAxis, EAxis >
using Covariance = BoundSquareMatrix
using Jacobian = BoundMatrix
using Stepper = Acts::AtlasStepper
using BField = ConstantBField
using ReferencePropagator = Propagator< Stepper, Navigator >
using DirectPropagator = Propagator< Stepper, DirectNavigator >
using path_limit = PathLimitReached
using BFieldType = ConstantBField
using EigenStepperType = EigenStepper<>
using EigenPropagatorType = Propagator< EigenStepperType, Navigator >
using AtlasStepperType = AtlasStepper
using EigenStepper = Acts::EigenStepper<>
using EigenPropagator = Propagator< EigenStepper >
using StraightLinePropagator = Propagator< StraightLineStepper, Navigator >
using StraightPropagator = Propagator< StraightLineStepper, Navigator >
using TestMeasurement = BoundVariantMeasurement
using ConstantFieldStepper = EigenStepper<>
using ConstantFieldPropagator = Propagator< ConstantFieldStepper, Navigator >
using BoundingBoxScalar = ActsScalar
using ObjectBBox = Acts::AxisAlignedBoundingBox< Object, BoundingBoxScalar, 3 >
using Vector2F = Eigen::Matrix< BoundingBoxScalar, 2, 1 >
using Vector3F = Eigen::Matrix< BoundingBoxScalar, 3, 1 >
using AngleAxis3F = Eigen::AngleAxis< BoundingBoxScalar >
using MatrixProductTypes = std::tuple< std::pair< ActsMatrix< 3, 3 >, ActsMatrix< 3, 3 >>, std::pair< ActsMatrix< 4, 4 >, ActsMatrix< 4, 4 >>, std::pair< ActsMatrix< 8, 8 >, ActsMatrix< 8, 8 >>, std::pair< ActsMatrix< 8, 7 >, ActsMatrix< 7, 4 >>>
template<typename T >
using member_a_t = decltype(std::declval< T >().member_a)
template<typename T >
using member_b_t = decltype(std::declval< T >().member_b)
template<typename T >
using nested_a_t = typename T::NestedA
template<typename T >
using nested_b_t = typename T::NestedB
template<typename T >
using member_t = decltype(std::declval< T >().member)
template<typename T >
using nested_t = typename T::Nested
template<typename T >
using meta_t = typename T::template meta< void, void >
using Propagator = Acts::Propagator< EigenStepper<>>
using Linearizer = HelicalTrackLinearizer< Propagator >
using HelicalPropagator = Propagator< EigenStepper<>>
using AnalyticalLinearizer = HelicalTrackLinearizer< HelicalPropagator >
using StraightAnalyticalLinearizer = HelicalTrackLinearizer< StraightPropagator >
using NumericalLinearizer = NumericalTrackLinearizer< HelicalPropagator >
using StraightNumericalLinearizer = NumericalTrackLinearizer< StraightPropagator >
using Linearizer_t = HelicalTrackLinearizer< Propagator >
Enumerations
enum MeasurementType
All supported simulated measurement types.
enum VertexCsvData { BeamSpotData, VerticesData, TracksData }
Functions
Vector3 origin (0., 0., 0.)
Vector3 originStraw (0.3_m,-0.2_m, 11_m)
template<typename surface_t >
MicroBenchmarkResult intersectionTest (const surface_t &surface, double phi, double theta)
BOOST_DATA_TEST_CASE (benchmark_surface_intersections, bdata::random((bdata::seed=21, bdata::distribution=std::uniform_real_distribution<>(-M_PI, M_PI)))^bdata::random((bdata::seed=22, bdata::distribution=std::uniform_real_distribution<>(-0.3, 0.3)))^bdata::xrange(ntests), phi, theta, index)
template<typename T >
void assumeAccessed (T &&clobber)
template<typename T >
void assumeRead (const T &clobber)
template<typename T >
void assumeWritten (T &clobber)
template<typename Callable >
MicroBenchmarkResult microBenchmark (Callable &&iteration, size_t iters_per_run, size_t num_runs=20000, std::chrono::milliseconds warmup_time=std::chrono::milliseconds(2000))
template<typename Callable , typename Input >
MicroBenchmarkResult microBenchmark (Callable &&iterationWithInput, const std::vector< Input > &inputs, size_t num_runs=20000, std::chrono::milliseconds warmup_time=std::chrono::milliseconds(2000))
std::string getDataPath (const std::string &relativePath)
template<typename T , typename U >
boost::test_tools::predicate_result checkCloseRel (const T &val, const U &ref, double reltol)
template<typename T , typename U >
boost::test_tools::predicate_result checkCloseAbs (const T &val, const U &ref, double abstol)
template<typename T >
boost::test_tools::predicate_result checkSmall (const T &val, double small)
template<typename T , typename U >
boost::test_tools::predicate_result checkCloseOrSmall (const T &val, const U &ref, double reltol, double small)
template<typename val_t , typename ref_t >
boost::test_tools::predicate_result checkCloseCovariance (const Eigen::MatrixBase< val_t > &val, const Eigen::MatrixBase< ref_t > &ref, double tol)
template<typename scalar_t , size_t kSize, typename generator_t >
auto generateParametersCovariance (generator_t &rng) -> std::pair< Eigen::Matrix< scalar_t, kSize, 1 >, Eigen::Matrix< scalar_t, kSize, kSize >>
template<typename generator_t >
auto generateBoundParametersCovariance (generator_t &rng)
Generate a random bound parameters vector and covariance matrix.
template<typename generator_t >
auto generateFreeParametersCovariance (generator_t &rng)
Generate a random free parameters vector and covariance matrix.
template<typename propagator_t , typename track_parameters_t >
Measurements createMeasurements (const propagator_t &propagator, const Acts::GeometryContext &geoCtx, const Acts::MagneticFieldContext &magCtx, const track_parameters_t &trackParameters, const MeasurementResolutionMap &resolutions, std::default_random_engine &rng, size_t sourceId=0u)
Propagate the track create smeared measurements from local coordinates.
Material makeBeryllium ()
Material makeSilicon ()
MaterialSlab makeUnitSlab ()
Build material slab corresponding to 1 radiation and interaction length.
MaterialSlab makePercentSlab ()
Build material slab corresponding to 1% of radiation and interaction length.
bool operator== (const TestSourceLink &lhs, const TestSourceLink &rhs)
bool operator!= (const TestSourceLink &lhs, const TestSourceLink &rhs)
std::ostream & operator<< (std::ostream &os, const TestSourceLink &sourceLink)
template<typename trajectory_t >
Acts::BoundVariantMeasurement testSourceLinkCalibratorReturn (const GeometryContext &, const CalibrationContext &, const SourceLink &sourceLink, typename trajectory_t::TrackStateProxy trackState)
template<typename trajectory_t >
void testSourceLinkCalibrator (const GeometryContext &gctx, const CalibrationContext &cctx, const SourceLink &sourceLink, typename trajectory_t::TrackStateProxy trackState)
bool operator== (const TestSpacePoint &lhs, const TestSpacePoint &rhs)
template<typename trajectory_t , typename track_state_t >
void fillTrackState (const TestTrackState &pc, TrackStatePropMask mask, track_state_t &ts)
template<typename T >
void addToWhiteBoard (std::string name, T data, ActsExamples::WhiteBoard &wb)
template<typename T >
T getFromWhiteBoard (std::string name, ActsExamples::WhiteBoard &wb)
BOOST_AUTO_TEST_CASE (assume_accessed)
BOOST_AUTO_TEST_CASE (assume_read)
BOOST_AUTO_TEST_CASE (assume_written)
BOOST_AUTO_TEST_CASE (micro_benchmark_result)
BOOST_AUTO_TEST_CASE (micro_benchmark)
bool cellComp (const Cell1D &left, const Cell1D &right)
Ccl::Label & getCellLabel (Cell1D &cell)
int getCellColumn (const Cell1D &cell)
void clusterAddCell (Cluster1D &cl, const Cell1D &cell)
bool clHashComp (const Cluster1D &left, const Cluster1D &right)
void hash (Cluster1D &cl)
BOOST_AUTO_TEST_CASE (Grid_1D_rand)
std::vector< Rectangle > concat (std::vector< std::vector< Rectangle >> vecs)
template<typename RNG >
std::vector< Rectangle > segment (int x0, int y0, int x1, int y1, RNG &rng)
int getCellRow (const Cell2D &cell)
int getCellColumn (const Cell2D &cell)
Ccl::Label & getCellLabel (Cell2D &cell)
bool operator== (const Cell2D &left, const Cell2D &right)
bool cellComp (const Cell2D &left, const Cell2D &right)
void clusterAddCell (Cluster2D &cl, const Cell2D &cell)
void hash (Cluster2D &cl)
bool clHashComp (const Cluster2D &left, const Cluster2D &right)
template<typename RNG >
void genclusterw (int x, int y, int x0, int y0, int x1, int y1, std::vector< Cell2D > &cells, RNG &rng, double startp=0.5, double decayp=0.9)
template<typename RNG >
Cluster2D gencluster (int x0, int y0, int x1, int y1, RNG &rng, double startp=0.5, double decayp=0.9)
BOOST_AUTO_TEST_CASE (Grid_2D_rand)
BOOST_AUTO_TEST_CASE (ProtoTrackingGeometryTests)
BOOST_AUTO_TEST_CASE (ProtoDetectorTests)
BOOST_AUTO_TEST_CASE (cartesian_segmentation)
Unit test for the Cartesian segmentation.
BOOST_DATA_TEST_CASE (readout_counter_test, bdata::random((bdata::seed=0, bdata::distribution=std::uniform_real_distribution<>(-halfX+sguardX, halfX-sguardX)))^bdata::random((bdata::seed=1, bdata::distribution=std::uniform_real_distribution<>(-halfX+sguardX, halfX-sguardX)))^bdata::random((bdata::seed=2, bdata::distribution=std::uniform_real_distribution<>(-halfY, halfY)))^bdata::random((bdata::seed=3, bdata::distribution=std::uniform_int_distribution<>(-static_cast< int >(halfY), static_cast< int >(halfY))))^bdata::xrange(ntests), entryX, entryY, exitX, exitY, index)
BOOST_AUTO_TEST_CASE (AlignmentContextTests)
Unit test for creating compliant/non-compliant Surface object.
BOOST_AUTO_TEST_CASE (ConeVolumeBoundsTests)
BOOST_AUTO_TEST_CASE (ConeVolumeBoundsSurfaceOrientation)
BOOST_AUTO_TEST_CASE (CuboidVolumeConstruction)
BOOST_AUTO_TEST_CASE (CuboidVolumeRecreation)
BOOST_AUTO_TEST_CASE (CuboidVolumeException)
BOOST_AUTO_TEST_CASE (CuboidVolumeProperties)
BOOST_AUTO_TEST_CASE (CuboidVolumeBoundarySurfaces)
BOOST_AUTO_TEST_CASE (CuboidVolumeBuilderTest)
BOOST_AUTO_TEST_CASE (CutoutCylinderVolumeBoundsConstruction)
BOOST_AUTO_TEST_CASE (CutoutCylinderVolumeBoundsRecreation)
BOOST_AUTO_TEST_CASE (CutoutCylinderVolumeBoundsExceptions)
BOOST_AUTO_TEST_CASE (CutoutCylinderVolumeBoundsAccess)
BOOST_AUTO_TEST_CASE (CutoutCylinderVolumeBoundsInside)
BOOST_AUTO_TEST_CASE (CutoutCylinderVolumeBoundsBoundingBox)
BOOST_AUTO_TEST_CASE (CutoutCylinderVolumeOrientedBoundaries)
BOOST_AUTO_TEST_CASE (CylinderVolumeBoundsConstruction)
BOOST_AUTO_TEST_CASE (CylinderVolumeBoundsRecreation)
BOOST_AUTO_TEST_CASE (CylinderVolumeBoundsExceptions)
BOOST_AUTO_TEST_CASE (CylinderVolumeBoundsAccess)
BOOST_DATA_TEST_CASE (CylinderVolumeBoundsOrientedSurfaces, bdata::random(-M_PI, M_PI)^bdata::random(-M_PI, M_PI)^bdata::random(-M_PI, M_PI)^bdata::random(-10., 10.)^bdata::random(-10., 10.)^bdata::random(-10., 10.)^bdata::xrange(100), alpha, beta, gamma, posX, posY, posZ, index)
Unit test for testing the orientedSurfaces() function.
BOOST_AUTO_TEST_CASE (CylinderVolumeBoundsBoundingBox)
BOOST_AUTO_TEST_CASE (CylinderVolumeOrientedBoundaries)
BOOST_DATA_TEST_CASE (CylinderVolumeBuilder_wraps, bdata::random(-11.,-15.)^bdata::random(11., 15.)^bdata::random(-10., 10.)^bdata::random(0., 4.)^bdata::random(11., 15.)^bdata::random(10., 15.)^bdata::xrange(100), left, right, central, inner, outer, length, index)
Unit test for testing the wraps() function of the CylinderVolumeBuilder.
BOOST_DATA_TEST_CASE (CylinderVolumeBuilder_containes, bdata::random(-11.,-15.)^bdata::random(11., 15.)^bdata::random(-10., 10.)^bdata::random(0., 4.)^bdata::random(10., 15.)^bdata::random(10., 15.)^bdata::xrange(100), left, right, central, inner, outer, length, index)
BOOST_DATA_TEST_CASE (CylinderVolumeBuilder_overlapsInR, bdata::random(0., 4.)^bdata::random(11., 15.)^bdata::xrange(100), inner, outer, index)
BOOST_DATA_TEST_CASE (CylinderVolumeBuilder_overlapsInZ, bdata::random(-11.,-15.)^bdata::random(11., 15.)^bdata::random(0., 4.)^bdata::xrange(100), left, right, inner, index)
BOOST_AUTO_TEST_CASE (ExtentTest)
Unit tests for Polyderon construction & operator +=.
BOOST_AUTO_TEST_CASE (construction_test)
BOOST_AUTO_TEST_CASE (GenericCuboidBoundsOrientedSurfaces)
BOOST_AUTO_TEST_CASE (ply_test)
BOOST_AUTO_TEST_CASE (bounding_box_creation)
BOOST_AUTO_TEST_CASE (GenericCuboidVolumeBoundarySurfaces)
BOOST_AUTO_TEST_CASE (GeometryIdentifier_construct_default)
BOOST_AUTO_TEST_CASE (GeometryIdentifier_construct_encoded)
BOOST_AUTO_TEST_CASE (GeometryIdentifier_max_values)
BOOST_AUTO_TEST_CASE (GeometryIdentifier_order)
BOOST_AUTO_TEST_CASE (KDTreeTrackingGeometryBuilder_simple)
void draw_surfaces (const SrfVec &surfaces, const std::string &fname)
BOOST_FIXTURE_TEST_CASE (LayerCreator_createCylinderLayer, LayerCreatorFixture)
BOOST_FIXTURE_TEST_CASE (LayerCreator_createDiscLayer, LayerCreatorFixture)
BOOST_FIXTURE_TEST_CASE (LayerCreator_barrelStagger, LayerCreatorFixture)
BOOST_AUTO_TEST_CASE (PolyhedronTest)
Unit tests for Polyderon construction & operator +=.
BOOST_AUTO_TEST_CASE (PolyhedronExtent)
Unit tests for Polyderon construction & operator +=.
BOOST_AUTO_TEST_CASE (SimpleGeometryTest)
Unit test for a three layer detector parameters Testing the Tool chain in the geometry building process.
BOOST_FIXTURE_TEST_CASE (SurfaceArrayCreator_createEquidistantAxis_Phi, SurfaceArrayCreatorFixture)
BOOST_FIXTURE_TEST_CASE (SurfaceArrayCreator_createEquidistantAxis_Z, SurfaceArrayCreatorFixture)
BOOST_FIXTURE_TEST_CASE (SurfaceArrayCreator_createEquidistantAxis_R, SurfaceArrayCreatorFixture)
BOOST_FIXTURE_TEST_CASE (SurfaceArrayCreator_dependentBinCounts, SurfaceArrayCreatorFixture)
BOOST_FIXTURE_TEST_CASE (SurfaceArrayCreator_completeBinning, SurfaceArrayCreatorFixture)
BOOST_FIXTURE_TEST_CASE (SurfaceArrayCreator_barrelStagger, SurfaceArrayCreatorFixture)
BOOST_AUTO_TEST_CASE (PlaneSurfaceMatcher)
TrackingGeometry makeTrackingGeometry (const GeometryIdentifierHook &hook)
BOOST_AUTO_TEST_CASE (GeometryIdentifier_closeGeometry_test)
BOOST_AUTO_TEST_CASE (GeometryIdentifier_closeGeometry_test_extra)
BOOST_AUTO_TEST_CASE (TrackingGeometry_testVisitSurfaces)
BOOST_AUTO_TEST_CASE (CylindricalTrackingGeometryTest)
BOOST_AUTO_TEST_CASE (CubicTrackingGeometryTest)
BOOST_AUTO_TEST_CASE (GeometryIdentifier_innervolume_test)
BOOST_AUTO_TEST_CASE (GeometryIdentifier_outervolume_test)
BOOST_AUTO_TEST_CASE (GeometryIdentifier_containervolume_test)
pre-check on GeometryIdentifier
BOOST_DATA_TEST_CASE (bvhnavigation_test, bdata::random((bdata::seed=7, bdata::engine=std::mt19937(), bdata::distribution=std::uniform_real_distribution<>(-5, 5)))^bdata::random((bdata::seed=2, bdata::engine=std::mt19937(), bdata::distribution=std::uniform_real_distribution<>(-M_PI, M_PI)))^bdata::random((bdata::seed=3, bdata::engine=std::mt19937(), bdata::distribution=std::uniform_real_distribution<>(-100, 100)))^bdata::random((bdata::seed=4, bdata::engine=std::mt19937(), bdata::distribution=std::uniform_real_distribution<>(-100, 100)))^bdata::random((bdata::seed=5, bdata::engine=std::mt19937(), bdata::distribution=std::uniform_real_distribution<>(-100, 100)))^bdata::xrange(NTESTS), eta, phi, x, y, z, index)
BOOST_AUTO_TEST_CASE (TrapezoidVolumeBoundarySurfaces)
BOOST_AUTO_TEST_CASE (VolumeBoundsTest)
BOOST_AUTO_TEST_CASE (VolumeTest)
BOOST_DATA_TEST_CASE (ConstantBField_components, bdata::random(-2_T, 2_T)^bdata::random(-1_T, 4_T)^bdata::random(0_T, 10_T)^bdata::random(-10_m, 10_m)^bdata::random(-10_m, 10_m)^bdata::random(-10_m, 10_m)^bdata::xrange(10), x, y, z, bx, by, bz, index)
unit test for construction of constant magnetic field
BOOST_DATA_TEST_CASE (ConstantBField_update, bdata::random(-2_T, 2_T)^bdata::random(-1_T, 4_T)^bdata::random(0_T, 10_T)^bdata::random(-10_m, 10_m)^bdata::random(-10_m, 10_m)^bdata::random(-10_m, 10_m)^bdata::xrange(10), x, y, z, bx, by, bz, index)
unit test for update of constant magnetic field
BOOST_AUTO_TEST_CASE (InterpolatedBFieldMap_rz)
template<class BField_t >
void testInterfaceConsistency (const BField_t &field)
BOOST_AUTO_TEST_CASE (TestConstantBFieldInterfaceConsistency)
BOOST_AUTO_TEST_CASE (TestSolenoidBFieldInterfaceConsistency)
BOOST_AUTO_TEST_CASE (TestInterpolatedBFieldMapInterfaceConsistency)
BOOST_AUTO_TEST_CASE (TypeErasedCacheType)
BOOST_AUTO_TEST_CASE (CacheNonCopyable)
BOOST_AUTO_TEST_CASE (TestSolenoidBField)
BOOST_AUTO_TEST_CASE (AccumulatedSurfaceMaterial_construction_test)
Test the constructors.
BOOST_AUTO_TEST_CASE (AccumulatedSurfaceMaterial_fill_convert_0D)
Test the filling and conversion.
BOOST_AUTO_TEST_CASE (AccumulatedSurfaceMaterial_fill_convert_1D)
Test the filling and conversion.
BOOST_AUTO_TEST_CASE (AccumulatedSurfaceMaterial_variance_0D)
Test the variance.
BOOST_AUTO_TEST_CASE (vacuum)
BOOST_AUTO_TEST_CASE (single_material)
BOOST_AUTO_TEST_CASE (two_materials)
BOOST_AUTO_TEST_CASE (two_materials_different_lengh)
BOOST_AUTO_TEST_CASE (BinnedSurfaceMaterial_construction_test)
Test the constructors.
BOOST_AUTO_TEST_CASE (HomogeneousSurfaceMaterial_construction_test)
Test the constructors.
BOOST_AUTO_TEST_CASE (HomogeneousSurfaceMaterial_scaling_test)
BOOST_AUTO_TEST_CASE (HomogeneousSurfaceMaterial_access_test)
BOOST_AUTO_TEST_CASE (HomogeneousVolumeMaterial_construction_test)
Test the constructors.
BOOST_AUTO_TEST_CASE (HomogeneousVolumeMaterial_access_test)
ActsVector< dim > trafoGlobalToLocal (const Vector3 &global)
BOOST_AUTO_TEST_CASE (InterpolatedMaterialMap_MaterialCell_test)
BOOST_AUTO_TEST_CASE (InterpolatedMaterialMap_MaterialMapper_test)
BOOST_AUTO_TEST_CASE (InterpolatedMaterialMap_test)
BOOST_AUTO_TEST_CASE (ISurfaceMaterial_factor_test)
Test the constructors.
BOOST_AUTO_TEST_CASE (construct_element_fraction)
BOOST_AUTO_TEST_CASE (construct_with_fractions)
BOOST_AUTO_TEST_CASE (construct_with_weights)
BOOST_AUTO_TEST_CASE (Square_Grid_test)
Various test for the Material in the case of a Cuboid volume and 2D Grid.
BOOST_AUTO_TEST_CASE (PhiZ_Grid_test)
Various test for the Material in the case of a Cylindrical volume with a 2D grid.
BOOST_AUTO_TEST_CASE (Cubic_Grid_test)
Various test for the Material in the case of a Cuboid volume.
BOOST_AUTO_TEST_CASE (Cylindrical_Grid_test)
Various test for the Material in the case of a Cylindrical volume.
BOOST_AUTO_TEST_CASE (ProtoSurfaceMaterial_construction_test)
Test the constructors.
BOOST_AUTO_TEST_CASE (ProtoVolumeMaterial_construction_test)
Test the constructors.
BOOST_AUTO_TEST_CASE (SurfaceMaterialMapper_tests)
Test the filling and conversion.
BOOST_AUTO_TEST_CASE (VolumeMaterialMapper_comparison_tests)
Test case for comparison between the mapped material and the associated material by propagation.
static const Vector4 pos4 (1_mm,-1_mm, 2_mm, 2_ns)
BOOST_AUTO_TEST_CASE (ConstructState)
BOOST_AUTO_TEST_CASE (ConstructStateWithCovariance)
BOOST_AUTO_TEST_CASE (Getters)
BOOST_AUTO_TEST_CASE (UpdateFromBound)
BOOST_AUTO_TEST_CASE (UpdateFromComponents)
BOOST_AUTO_TEST_CASE (BuildBound)
BOOST_AUTO_TEST_CASE (BuildCurvilinear)
BOOST_AUTO_TEST_CASE (Step)
BOOST_AUTO_TEST_CASE (StepWithCovariance)
BOOST_AUTO_TEST_CASE (Reset)
BOOST_AUTO_TEST_CASE (StepSize)
BOOST_AUTO_TEST_CASE (StepSizeSurface)
BOOST_AUTO_TEST_CASE (AuctioneerTest_VoidAuctioneer)
BOOST_AUTO_TEST_CASE (AuctioneerTest_FirstValidAuctioneer)
BOOST_AUTO_TEST_CASE (AuctioneerTest_HighestValidAuctioneer)
BOOST_AUTO_TEST_CASE (ConstrainedStepTest)
BOOST_AUTO_TEST_CASE (covariance_engine_test)
BOOST_AUTO_TEST_CASE (covariance_transport_invalid)
BOOST_AUTO_TEST_CASE (covariance_transport_bound_start)
BOOST_AUTO_TEST_CASE (covariance_transport_curvilinear_start)
BOOST_AUTO_TEST_CASE (covariance_transport_free_start)
Navigator navigator ({tGeometry})
ReferencePropagator rpropagator (std::move(estepper), std::move(navigator))
DirectPropagator dpropagator (std::move(dstepper), std::move(dnavigator))
template<typename rpropagator_t , typename dpropagator_t >
void runTest (const rpropagator_t &rprop, const dpropagator_t &dprop, double pT, double phi, double theta, int charge, double time, int index)
BOOST_DATA_TEST_CASE (test_direct_navigator, bdata::random((bdata::seed=20, bdata::distribution=std::uniform_real_distribution<>(0.15_GeV, 10_GeV)))^bdata::random((bdata::seed=21, bdata::distribution=std::uniform_real_distribution<>(-M_PI, M_PI)))^bdata::random((bdata::seed=22, bdata::distribution=std::uniform_real_distribution<>(1.0, M_PI-1.0)))^bdata::random((bdata::seed=23, bdata::distribution=std::uniform_int_distribution<>(0, 1)))^bdata::random((bdata::seed=24, bdata::distribution=std::uniform_int_distribution<>(0, 100)))^bdata::xrange(ntests), pT, phi, theta, charge, time, index)
BOOST_AUTO_TEST_CASE (eigen_stepper_state_test)
These tests are aiming to test whether the state setup is working properly.
BOOST_AUTO_TEST_CASE (eigen_stepper_test)
BOOST_AUTO_TEST_CASE (step_extension_vacuum_test)
This function tests the EigenStepper with the DefaultExtension and the DenseEnvironmentExtension. The focus of this tests lies in the choosing of the right extension for the individual use case. This is performed with three different detectors: a) Pure vacuum -> DefaultExtension needs to act b) Pure Be -> DenseEnvironmentExtension needs to act c) Vacuum - Be - Vacuum -> Both should act and switch during the propagation.
BOOST_AUTO_TEST_CASE (step_extension_material_test)
BOOST_AUTO_TEST_CASE (step_extension_vacmatvac_test)
BOOST_AUTO_TEST_CASE (step_extension_trackercalomdt_test)
CylindricalTrackingGeometry cGeometry (tgContext)
EigenStepperType estepper (bField)
EigenPropagatorType epropagator (std::move(estepper), std::move(navigator))
BOOST_DATA_TEST_CASE (test_extrapolation_, bdata::random((bdata::seed=0, bdata::distribution=std::uniform_real_distribution<>(0.4_GeV, 10_GeV)))^bdata::random((bdata::seed=1, bdata::distribution=std::uniform_real_distribution<>(-M_PI, M_PI)))^bdata::random((bdata::seed=2, bdata::distribution=std::uniform_real_distribution<>(1.0, M_PI-1.0)))^bdata::random((bdata::seed=3, bdata::distribution=std::uniform_int_distribution<>(0, 1)))^bdata::random((bdata::seed=4, bdata::distribution=std::uniform_int_distribution<>(0, 100)))^bdata::xrange(ntests), pT, phi, theta, charge, time, index)
BOOST_DATA_TEST_CASE (test_surface_collection_, bdata::random((bdata::seed=10, bdata::distribution=std::uniform_real_distribution<>(0.4_GeV, 10_GeV)))^bdata::random((bdata::seed=11, bdata::distribution=std::uniform_real_distribution<>(-M_PI, M_PI)))^bdata::random((bdata::seed=12, bdata::distribution=std::uniform_real_distribution<>(1.0, M_PI-1.0)))^bdata::random((bdata::seed=13, bdata::distribution=std::uniform_int_distribution<>(0, 1)))^bdata::random((bdata::seed=14, bdata::distribution=std::uniform_int_distribution<>(0, 100)))^bdata::xrange(ntests), pT, phi, theta, charge, time, index)
BOOST_DATA_TEST_CASE (test_material_interactor_, bdata::random((bdata::seed=20, bdata::distribution=std::uniform_real_distribution<>(0.4_GeV, 10_GeV)))^bdata::random((bdata::seed=21, bdata::distribution=std::uniform_real_distribution<>(-M_PI, M_PI)))^bdata::random((bdata::seed=22, bdata::distribution=std::uniform_real_distribution<>(1.0, M_PI-1.0)))^bdata::random((bdata::seed=23, bdata::distribution=std::uniform_int_distribution<>(0, 1)))^bdata::random((bdata::seed=24, bdata::distribution=std::uniform_int_distribution<>(0, 100)))^bdata::xrange(ntests), pT, phi, theta, charge, time, index)
BOOST_DATA_TEST_CASE (loop_protection_test, bdata::random((bdata::seed=20, bdata::distribution=std::uniform_real_distribution<>(0.1_GeV, 0.5_GeV)))^bdata::random((bdata::seed=21, bdata::distribution=std::uniform_real_distribution<>(-M_PI, M_PI)))^bdata::random((bdata::seed=22, bdata::distribution=std::uniform_real_distribution<>(1.0, M_PI-1.0)))^bdata::random((bdata::seed=23, bdata::distribution=std::uniform_int_distribution<>(0, 1)))^bdata::random((bdata::seed=24, bdata::distribution=std::uniform_int_distribution<>(0, 100)))^bdata::xrange(ntests), pT, phi, theta, charge, time, index)
BOOST_AUTO_TEST_CASE (jacobian_engine_helper)
Helper function tests.
BOOST_AUTO_TEST_CASE (jacobian_engine_to_bound)
BOOST_AUTO_TEST_CASE (jacobian_engine_to_curvilinear)
BOOST_AUTO_TEST_CASE (jacobian_engine_to_free)
Transform3 createCylindricTransform (const Vector3 &nposition, double angleX, double angleY)
Transform3 createPlanarTransform (const Vector3 &nposition, const Vector3 &nnormal, double angleT, double angleU)
BoundToFreeMatrix convertToMatrix (const std::array< double, 60 > P)
template<typename Parameters >
void testJacobianToGlobal (const Parameters &pars)
BOOST_AUTO_TEST_CASE (JacobianCurvilinearToGlobalTest)
This tests the jacobian of local curvilinear -> global.
BOOST_AUTO_TEST_CASE (JacobianCylinderToGlobalTest)
This tests the jacobian of local cylinder -> global.
BOOST_AUTO_TEST_CASE (JacobianDiscToGlobalTest)
This tests the jacobian of local disc -> global.
BOOST_AUTO_TEST_CASE (JacobianPlaneToGlobalTest)
This tests the jacobian of local plane -> global.
BOOST_AUTO_TEST_CASE (JacobianPerigeeToGlobalTest)
This tests the jacobian of local perigee -> global.
BOOST_AUTO_TEST_CASE (JacobianStrawToGlobalTest)
This tests the jacobian of local straw -> global.
BOOST_AUTO_TEST_CASE (kalman_extrapolator)
Unit test for Kalman fitter propagation.
BOOST_DATA_TEST_CASE (loop_aborter_test, bdata::random((bdata::seed=21, bdata::distribution=std::uniform_real_distribution<>(-M_PI, M_PI)))^bdata::random((bdata::seed=22, bdata::distribution=std::uniform_real_distribution<>(-M_PI, M_PI)))^bdata::xrange(1), phi, deltaPhi, index)
BOOST_DATA_TEST_CASE (propagator_loop_protection_test, bdata::random((bdata::seed=20, bdata::distribution=std::uniform_real_distribution<>(0.5_GeV, 10_GeV)))^bdata::random((bdata::seed=21, bdata::distribution=std::uniform_real_distribution<>(-M_PI, M_PI)))^bdata::random((bdata::seed=22, bdata::distribution=std::uniform_real_distribution<>(1.0, M_PI-1.0)))^bdata::random((bdata::seed=23, bdata::distribution=std::uniform_int_distribution<>(0, 1)))^bdata::xrange(ntests), pT, phi, theta, charge, index)
EigenPropagator epropagator (std::move(estepper), std::move(navigatorES))
StraightLinePropagator slpropagator (slstepper, std::move(navigatorSL))
template<typename propagator_t >
void runTest (const propagator_t &prop, double pT, double phi, double theta, int charge, double time, int index)
BOOST_DATA_TEST_CASE (test_material_collector, bdata::random((bdata::seed=20, bdata::distribution=std::uniform_real_distribution<>(0.5_GeV, 10_GeV)))^bdata::random((bdata::seed=21, bdata::distribution=std::uniform_real_distribution<>(-M_PI, M_PI)))^bdata::random((bdata::seed=22, bdata::distribution=std::uniform_real_distribution<>(1.0, M_PI-1.0)))^bdata::random((bdata::seed=23, bdata::distribution=std::uniform_int_distribution<>(0, 1)))^bdata::random((bdata::seed=24, bdata::distribution=std::uniform_int_distribution<>(0, 100)))^bdata::xrange(ntests), pT, phi, theta, charge, time, index)
template<typename stepper_state_t >
void step (stepper_state_t &sstate)
bool testNavigatorStateVectors (Navigator::State &state, size_t navSurf, size_t navLay, size_t navBound, size_t extSurf)
Method for testing vectors in Navigator::State.
bool testNavigatorStatePointers (Navigator::State &state, const TrackingVolume *worldVol, const TrackingVolume *startVol, const Layer *startLay, const Surface *startSurf, const Surface *currSurf, const TrackingVolume *currVol, const TrackingVolume *targetVol, const Layer *targetLay, const Surface *targetSurf)
Method for testing pointers in Navigator::State.
BOOST_AUTO_TEST_CASE (Navigator_status_methods)
BOOST_AUTO_TEST_CASE (Navigator_target_methods)
EigenPropagatorType epropagator (std::move(estepper))
BOOST_AUTO_TEST_CASE (PropagatorOptions_)
BOOST_DATA_TEST_CASE (cylinder_passage_observer_, bdata::random((bdata::seed=0, bdata::distribution=std::uniform_real_distribution<>(0.4_GeV, 10_GeV)))^bdata::random((bdata::seed=1, bdata::distribution=std::uniform_real_distribution<>(-M_PI, M_PI)))^bdata::random((bdata::seed=2, bdata::distribution=std::uniform_real_distribution<>(1.0, M_PI-1.0)))^bdata::random((bdata::seed=3, bdata::distribution=std::uniform_int_distribution<>(0, 1)))^bdata::random((bdata::seed=4, bdata::distribution=std::uniform_int_distribution<>(0, 100)))^bdata::xrange(ntests), pT, phi, theta, charge, time, index)
BOOST_DATA_TEST_CASE (curvilinear_additive_, bdata::random((bdata::seed=0, bdata::distribution=std::uniform_real_distribution<>(0.4_GeV, 10_GeV)))^bdata::random((bdata::seed=1, bdata::distribution=std::uniform_real_distribution<>(-M_PI, M_PI)))^bdata::random((bdata::seed=2, bdata::distribution=std::uniform_real_distribution<>(1.0, M_PI-1.0)))^bdata::random((bdata::seed=3, bdata::distribution=std::uniform_int_distribution<>(0, 1)))^bdata::random((bdata::seed=4, bdata::distribution=std::uniform_int_distribution<>(0, 100)))^bdata::xrange(ntests), pT, phi, theta, charge, time, index)
BOOST_DATA_TEST_CASE (cylinder_additive_, bdata::random((bdata::seed=0, bdata::distribution=std::uniform_real_distribution<>(0.4_GeV, 10_GeV)))^bdata::random((bdata::seed=1, bdata::distribution=std::uniform_real_distribution<>(-M_PI, M_PI)))^bdata::random((bdata::seed=2, bdata::distribution=std::uniform_real_distribution<>(1.0, M_PI-1.0)))^bdata::random((bdata::seed=3, bdata::distribution=std::uniform_int_distribution<>(0, 1)))^bdata::random((bdata::seed=4, bdata::distribution=std::uniform_int_distribution<>(0, 100)))^bdata::xrange(ntests), pT, phi, theta, charge, time, index)
BOOST_AUTO_TEST_CASE (straight_line_stepper_state_test)
These tests are aiming to test whether the state setup is working properly.
BOOST_AUTO_TEST_CASE (straight_line_stepper_test)
BOOST_AUTO_TEST_CASE (volume_material_interaction_test)
CurvilinearTrackParameters makeParameters (double phi, double theta, double p, double q)
std::pair< Vector3, Vector3 > stripEnds (const std::shared_ptr< const TrackingGeometry > &geo, const GeometryContext &gctx, const SourceLink &slink, const double stripFrac=0.4)
static StraightPropagator makeStraightPropagator (std::shared_ptr< const TrackingGeometry > geo)
std::default_random_engine rng (42)
BOOST_DATA_TEST_CASE (SpacePointBuilder_basic, bdata::xrange(1), index)
BOOST_AUTO_TEST_CASE (alignment_helper_test)
Vector2 offset (-2., 2.)
BOOST_AUTO_TEST_CASE (AnnulusBoundsConstruction)
BOOST_AUTO_TEST_CASE (AnnulusBoundsRecreation)
BOOST_AUTO_TEST_CASE (AnnulusBoundsExcpetion)
BOOST_AUTO_TEST_CASE (AnnulusBoundsProperties)
Unit tests for AnnulusBounds properties.
BOOST_AUTO_TEST_CASE (BoundaryCheckBoxSimple)
BOOST_AUTO_TEST_CASE (BoundaryCheckBoxToleranceLoc0)
BOOST_AUTO_TEST_CASE (BoundaryCheckBoxDistance)
BOOST_AUTO_TEST_CASE (BoundaryCheckBoxCovariance)
BOOST_AUTO_TEST_CASE (BoundaryCheckPolyDistance)
BOOST_AUTO_TEST_CASE (BoundaryCheckTriangleSimple)
BOOST_AUTO_TEST_CASE (BoundaryCheckTriangleCovariance)
BOOST_AUTO_TEST_CASE (ConeBoundsConstruction)
Unit test for creating compliant/non-compliant ConeBounds object.
BOOST_AUTO_TEST_CASE (ConeBoundsRecreation)
BOOST_AUTO_TEST_CASE (ConeBoundsExceptions)
BOOST_AUTO_TEST_CASE (ConeBoundsProperties)
Unit tests for properties of ConeBounds object.
BOOST_AUTO_TEST_CASE (ConeBoundsAssignment)
BOOST_AUTO_TEST_CASE (ConeSurfaceConstruction)
Unit test for creating compliant/non-compliant ConeSurface object.
BOOST_AUTO_TEST_CASE (ConeSurfaceProperties)
Unit test for testing ConeSurface properties.
BOOST_AUTO_TEST_CASE (ConeSurfaceEqualityOperators)
BOOST_AUTO_TEST_CASE (ConeSurfaceExtent)
BOOST_AUTO_TEST_CASE (ConeSurfaceAlignment)
Unit test for testing ConeSurface alignment derivatives.
BOOST_AUTO_TEST_CASE (ConvexPolygonBoundsConvexity)
BOOST_AUTO_TEST_CASE (ConvexPolygonBoundsConstruction)
BOOST_AUTO_TEST_CASE (ConvexPolygonBoundsRecreation)
BOOST_AUTO_TEST_CASE (ConvexPolygonBoundsDynamicTest)
BOOST_AUTO_TEST_CASE (CylinderBoundsConstruction)
Unit test for creating compliant/non-compliant CylinderBounds object.
BOOST_AUTO_TEST_CASE (CylinderBoundsRecreation)
BOOST_AUTO_TEST_CASE (CylinderBoundsException)
BOOST_AUTO_TEST_CASE (CylinderBoundsProperties)
Unit tests for CylinderBounds properties.
BOOST_AUTO_TEST_CASE (CylinderBoundsAssignment)
Unit test for testing CylinderBounds assignment.
BOOST_AUTO_TEST_CASE (CylinderSurfaceConstruction)
Unit test for creating compliant/non-compliant CylinderSurface object.
BOOST_AUTO_TEST_CASE (CylinderSurfaceProperties)
Unit test for testing CylinderSurface properties.
BOOST_AUTO_TEST_CASE (CylinderSurfaceEqualityOperators)
BOOST_AUTO_TEST_CASE (CylinderSurfaceExtent)
Unit test for testing CylinderSurface properties.
BOOST_AUTO_TEST_CASE (CylinderSurfaceAlignment)
Unit test for testing CylinderSurface alignment derivatives.
BOOST_AUTO_TEST_CASE (CylinderSurfaceBinningPosition)
BOOST_AUTO_TEST_CASE (DiamondBoundsConstruction)
Unit test for creating compliant/non-compliant DiamondBounds object.
BOOST_AUTO_TEST_CASE (DiamondBoundsProperties)
Unit tests for DiamondBounds properties.
BOOST_AUTO_TEST_CASE (DiamondBoundsAssignment)
Unit test for testing DiamondBounds assignment.
BOOST_AUTO_TEST_CASE (DiscSurfaceConstruction)
Unit tests for creating DiscSurface object.
BOOST_AUTO_TEST_CASE (DiscSurfaceProperties)
Unit tests of all named methods.
BOOST_AUTO_TEST_CASE (DiscSurfaceAssignment)
Unit test for testing DiscSurface assignment and equality.
BOOST_AUTO_TEST_CASE (DiscSurfaceExtent)
Unit test for testing DiscSurface assignment and equality.
BOOST_AUTO_TEST_CASE (DiscSurfaceAlignment)
Unit test for testing DiscSurface alignment derivatives.
BOOST_AUTO_TEST_CASE (DiscSurfaceBinningPosition)
BOOST_AUTO_TEST_CASE (DiscTrapezoidBoundsConstruction)
Unit tests for DiscTrapezoidBounds constrcuctors.
BOOST_AUTO_TEST_CASE (DiscTrapezoidBoundsRecreation)
BOOST_AUTO_TEST_CASE (DiscTrapezoidBoundsExceptions)
BOOST_AUTO_TEST_CASE (DiscTrapezoidBoundsProperties)
Unit tests for DiscTrapezoidBounds properties.
BOOST_AUTO_TEST_CASE (DiscTrapezoidBoundsAssignment)
Unit test for testing DiscTrapezoidBounds assignment.
BOOST_AUTO_TEST_CASE (EllipseBoundsConstruction)
Unit test for creating compliant/non-compliant EllipseBounds object.
BOOST_AUTO_TEST_CASE (EllipseBoundsRecreation)
BOOST_AUTO_TEST_CASE (EllipseBoundsProperties)
Unit tests for EllipseBounds properties.
BOOST_AUTO_TEST_CASE (EllipseBoundsAssignment)
Unit test for testing EllipseBounds assignment.
BOOST_AUTO_TEST_CASE (InfiniteBoundsConstruction)
Unit test for creating compliant/non-compliant InfiniteBounds object.
BOOST_AUTO_TEST_CASE (InfiniteBoundsProperties)
Unit tests for InfiniteBounds properties.
void basicChecks (bool circleCase=false)
BOOST_AUTO_TEST_CASE (LineLineIntersection)
Unit test for creating Ellipse intersection.
BOOST_AUTO_TEST_CASE (EllipseIntersection)
Unit test for creating Ellipse intersection.
BOOST_AUTO_TEST_CASE (CircleIntersection)
Unit test for creating Circle intersection.
BOOST_AUTO_TEST_CASE (LineBoundsConstruction)
Unit test for creating compliant/non-compliant LineBounds object.
BOOST_AUTO_TEST_CASE (LineBoundsRecreation)
Unit test for testing LineBounds recreation from streaming.
BOOST_AUTO_TEST_CASE (LineBoundsExceptions)
Unit test for testing LineBounds exceptions.
BOOST_AUTO_TEST_CASE (LineBoundsAssignment)
Unit test for testing LineBounds assignment.
BOOST_AUTO_TEST_CASE (LineBoundsProperties)
Unit tests for LineBounds properties.
BOOST_AUTO_TEST_CASE (LineSurface_Constructors_test)
Unit test for creating compliant/non-compliant LineSurface object.
BOOST_AUTO_TEST_CASE (LineSurface_allNamedMethods_test)
Unit tests of all named methods.
BOOST_AUTO_TEST_CASE (LineSurface_assignment_test)
Unit test for testing LineSurface assignment.
BOOST_AUTO_TEST_CASE (LineSurfaceAlignment)
Unit test for testing LineSurface alignment derivatives.
BOOST_AUTO_TEST_CASE (LineSurfaceTransformRoundTrip)
BOOST_AUTO_TEST_CASE (LineSurfaceTransformRoundTripEtaStability)
BOOST_AUTO_TEST_CASE (LineSurfaceIntersection)
BOOST_AUTO_TEST_CASE (PerigeeSurfaceConstruction)
Unit test for creating compliant/non-compliant PerigeeSurface object.
BOOST_AUTO_TEST_CASE (PerigeeSurfaceProperties)
Unit test for testing PerigeeSurface properties.
BOOST_AUTO_TEST_CASE (EqualityOperators)
BOOST_AUTO_TEST_CASE (PlaneSurfaceConstruction)
Unit test for creating compliant/non-compliant PlaneSurface object.
BOOST_AUTO_TEST_CASE (PlaneSurfaceProperties)
Unit test for testing PlaneSurface properties.
BOOST_AUTO_TEST_CASE (PlaneSurfaceEqualityOperators)
BOOST_AUTO_TEST_CASE (PlaneSurfaceExtent)
Unit test for testing PlaneSurface extent via Polyhedron representation.
BOOST_AUTO_TEST_CASE (PlaneSurfaceAlignment)
Unit test for testing PlaneSurface alignment derivatives.
BOOST_AUTO_TEST_CASE (ConeSurfacePolyhedrons)
Unit tests for Cone Surfaces.
BOOST_AUTO_TEST_CASE (CylinderSurfacePolyhedrons)
Unit tests for Cylinder Surfaces.
BOOST_AUTO_TEST_CASE (DiscSurfacePolyhedrons)
Unit tests for Disc Surfaces.
BOOST_AUTO_TEST_CASE (PlaneSurfacePolyhedrons)
Unit tests for Plane Surfaces.
BOOST_AUTO_TEST_CASE (RadialBoundsConstruction)
Unit tests for RadialBounds constrcuctors.
BOOST_AUTO_TEST_CASE (RadialBoundsRecreation)
BOOST_AUTO_TEST_CASE (RadialBoundsException)
BOOST_AUTO_TEST_CASE (RadialBoundsProperties)
Unit tests for RadialBounds properties.
BOOST_AUTO_TEST_CASE (RadialBoundsAssignment)
Unit test for testing RadialBounds assignment.
void dumpVertices (const RectangleBounds &r)
bool approximatelyEqual (const Vector2 &a, const Vector2 &b)
BOOST_AUTO_TEST_CASE (RectangleBoundsConstruction)
Unit test for creating compliant/non-compliant RectangleBounds object.
BOOST_AUTO_TEST_CASE (RectangleBoundsRecreation)
Recreation.
BOOST_AUTO_TEST_CASE (RectangleBoundsProperties)
Unit test for testing RectangleBounds properties.
BOOST_AUTO_TEST_CASE (RectangleBoundsAssignment)
BOOST_AUTO_TEST_CASE (StrawSurfaceConstruction)
Unit test for creating compliant/non-compliant StrawSurface object.
BOOST_AUTO_TEST_CASE (StrawSurfaceProperties)
Unit test for testing StrawSurface properties.
BOOST_FIXTURE_TEST_CASE (SurfaceArray_create, SurfaceArrayFixture)
BOOST_AUTO_TEST_CASE (SurfaceArray_singleElement)
BOOST_AUTO_TEST_CASE (SurfaceArray_manyElementsSingleLookup)
BOOST_AUTO_TEST_CASE (SurfaceBoundsConstruction)
Unit test for creating compliant/non-compliant SurfaceBounds object.
BOOST_AUTO_TEST_CASE (SurfaceBoundsProperties)
BOOST_AUTO_TEST_CASE (SurfaceBoundsEquality)
Unit test for testing SurfaceBounds properties.
BOOST_AUTO_TEST_CASE (CylinderIntersectionTests)
BOOST_AUTO_TEST_CASE (ConeIntersectionTest)
BOOST_AUTO_TEST_CASE (PlanarIntersectionTest)
BOOST_AUTO_TEST_CASE (LineIntersectionTest)
BOOST_AUTO_TEST_CASE (SurfaceConstruction)
todo: make test fixture; separate out different cases
BOOST_AUTO_TEST_CASE (SurfaceProperties)
Unit test for testing Surface properties.
BOOST_AUTO_TEST_CASE (TrapezoidBoundsConstruction)
Unit test for creating compliant/non-compliant TrapezoidBounds object.
BOOST_AUTO_TEST_CASE (TrapezoidBoundsRecreated)
Unit test for creating compliant/non-compliant TrapezoidBounds object.
BOOST_AUTO_TEST_CASE (TrapezoidBoundsException)
BOOST_AUTO_TEST_CASE (TrapezoidBoundsProperties)
Unit tests for TrapezoidBounds properties.
BOOST_DATA_TEST_CASE (TrapezoidInsideCheck, bdata::random((bdata::seed=1, bdata::distribution=std::uniform_real_distribution<>(-7, 7)))^bdata::random((bdata::seed=2, bdata::distribution=std::uniform_real_distribution<>(-3, 3)))^bdata::xrange(1000)*bdata::make({0.0, 0.1, 0.2, 0.3}), x, y, index, tol)
BOOST_AUTO_TEST_CASE (TrapezoidBoundsAssignment)
Unit test for testing TrapezoidBounds assignment.
Acts::CurvilinearTrackParameters makeParameters (const ActsScalar x=0.0_m, const ActsScalar y=0.0_m, const ActsScalar z=0.0_m, const ActsScalar w=42_ns, const ActsScalar phi=0_degree, const ActsScalar theta=90_degree, const ActsScalar p=1_GeV, const ActsScalar q=1_e)
static std::vector
< Acts::SourceLink > prepareSourceLinks (const std::vector< TestSourceLink > &sourceLinks)
std::shared_ptr< const
TrackingGeometry > makeToyDetector (const GeometryContext &tgContext, const size_t nSurfaces=5)
BOOST_AUTO_TEST_CASE (NoFit)
BOOST_AUTO_TEST_CASE (Fit5Iterations)
BOOST_AUTO_TEST_CASE (MixedDetector)
BOOST_AUTO_TEST_CASE (annealing_tool_singleChi2_tests)
BOOST_AUTO_TEST_CASE (annealing_tool_multiChi2_tests)
BOOST_AUTO_TEST_CASE (equidistant_axis)
BOOST_AUTO_TEST_CASE (variable_axis)
BOOST_AUTO_TEST_CASE (open_axis)
BOOST_AUTO_TEST_CASE (closed_axis)
BOOST_AUTO_TEST_CASE (neighborhood)
BOOST_AUTO_TEST_CASE (wrapBin)
BOOST_AUTO_TEST_CASE (bfield_creation)
BOOST_AUTO_TEST_CASE (bfield_symmetry)
BOOST_DATA_TEST_CASE (bfield_symmetry_random, bdata::random((bdata::seed=0, bdata::distribution=std::uniform_real_distribution<>(-10., 10.)))^bdata::random((bdata::seed=0, bdata::distribution=std::uniform_real_distribution<>(-10., 10.)))^bdata::random((bdata::seed=0, bdata::distribution=std::uniform_real_distribution<>(-20., 20.)))^bdata::xrange(10), x, y, z, index)
Unit test for symmetric data.
BOOST_AUTO_TEST_CASE (BinAdjustment_Radial)
BOOST_AUTO_TEST_CASE (BinAdjustment_Cylinder)
BOOST_AUTO_TEST_CASE (BinAdjustment_Rectangle)
BOOST_AUTO_TEST_CASE (BinAdjustment_Trapezoid)
BOOST_AUTO_TEST_CASE (BinAdjustmentVolume_Cylinder)
BOOST_AUTO_TEST_CASE (BinAdjustmentVolume_CutoutCylinder)
BOOST_AUTO_TEST_CASE (BinAdjustmentVolume_Cuboid)
Vector3 xyzPosition (0.5, 1.5, 2.5)
Vector3 xyzPositionOutside (30.,-30., 200.)
Vector3 phi0Position (0.5, 0., 2.5)
Vector3 phiPihPosition (0., 1.5, 2.5)
Vector3 eta0Position (0.5, 1.5, 0.)
Vector2 xyPosition (0.5, 1.5)
Vector2 rphizPosition (0.1, 2.5)
Vector2 rphiPosition (3.5, M_PI/8.)
BinningData xData_add (open, binX, main_sstr, std::move(xData_sstr_add))
BOOST_AUTO_TEST_CASE (BinningData_BinningValue)
BOOST_AUTO_TEST_CASE (BinningData_bins)
BOOST_AUTO_TEST_CASE (BinningData_inside_outside)
BOOST_AUTO_TEST_CASE (BinningData_open_close)
BOOST_AUTO_TEST_CASE (BinningData_boundaries)
BOOST_AUTO_TEST_CASE (BinningData_bincenter)
BOOST_AUTO_TEST_CASE (BinningData_phi_modules)
BOOST_AUTO_TEST_CASE (BinUtility_equidistant_binning)
BOOST_AUTO_TEST_CASE (BinUtility_arbitrary_binning)
BOOST_AUTO_TEST_CASE (BinUtility_transform)
std::ofstream tmp (const std::string &path)
BOOST_AUTO_TEST_CASE (box_construction)
BOOST_AUTO_TEST_CASE (intersect_points)
BOOST_AUTO_TEST_CASE (intersect_rays)
BOOST_AUTO_TEST_CASE (ray_obb_intersect)
BOOST_AUTO_TEST_CASE (frustum_intersect)
BOOST_AUTO_TEST_CASE (ostream_operator)
BOOST_AUTO_TEST_CASE (Extendable_)
BOOST_AUTO_TEST_CASE (Transitions)
BOOST_AUTO_TEST_CASE (Terminted)
BOOST_AUTO_TEST_CASE (Arguments)
BOOST_AUTO_TEST_CASE (InternalTransitions)
BOOST_AUTO_TEST_CASE (frustum_construction)
BOOST_AUTO_TEST_CASE (grid_test_1d_equidistant)
BOOST_AUTO_TEST_CASE (grid_test_2d_equidistant)
BOOST_AUTO_TEST_CASE (grid_test_3d_equidistant)
BOOST_AUTO_TEST_CASE (grid_test_1d_variable)
BOOST_AUTO_TEST_CASE (grid_test_2d_variable)
BOOST_AUTO_TEST_CASE (grid_test_3d_variable)
BOOST_AUTO_TEST_CASE (grid_test_2d_mixed)
BOOST_AUTO_TEST_CASE (grid_test_2d_mixed_at)
BOOST_AUTO_TEST_CASE (grid_interpolation)
BOOST_AUTO_TEST_CASE (closestPoints)
BOOST_AUTO_TEST_CASE (string_hashes)
BOOST_AUTO_TEST_CASE (bitset_to_matrix_to_bitset)
BOOST_AUTO_TEST_CASE (phi_helper_test)
BOOST_AUTO_TEST_CASE (perp_helper_test)
BOOST_AUTO_TEST_CASE (theta_eta_test_helper)
BOOST_AUTO_TEST_CASE (cross_test_helper)
BOOST_AUTO_TEST_CASE (toString_test_helper)
BOOST_AUTO_TEST_CASE (shared_vector_helper_test)
BOOST_AUTO_TEST_CASE (VectorHelpersPosition)
BOOST_AUTO_TEST_CASE (test_matrix_dimension_switch)
BOOST_AUTO_TEST_CASE_TEMPLATE (BlockedMatrixMultiplication, Matrices, MatrixProductTypes)
BOOST_AUTO_TEST_CASE (min_max)
BOOST_AUTO_TEST_CASE (range_medium)
BOOST_AUTO_TEST_CASE (safeInverse)
BOOST_AUTO_TEST_CASE (incidentAnglesTest)
BOOST_AUTO_TEST_CASE (interpolation_1d)
BOOST_AUTO_TEST_CASE (interpolation_2d)
BOOST_AUTO_TEST_CASE (interpolation_3d)
BOOST_AUTO_TEST_CASE (interpolation_mixed_point_values)
BOOST_AUTO_TEST_CASE (IntersectionTest)
test of the intersection class
BOOST_AUTO_TEST_CASE (ObjectIntersectionTest)
test of the object intersection class
BOOST_AUTO_TEST_CASE (IntersectionStatusPrinting)
BOOST_FIXTURE_TEST_CASE (size_1, TreeFixture1DDoubleInt1)
BOOST_FIXTURE_TEST_CASE (size_2, TreeFixture1DDoubleInt2)
BOOST_FIXTURE_TEST_CASE (size_3, TreeFixture2DDoubleInt1)
BOOST_FIXTURE_TEST_CASE (size_4, TreeFixture3DDoubleInt1)
BOOST_FIXTURE_TEST_CASE (size_5, TreeFixture10DDoubleInt1)
BOOST_FIXTURE_TEST_CASE (size_6, TreeFixture3DDoubleString1)
BOOST_FIXTURE_TEST_CASE (size_7, TreeFixture1DIntInt1)
BOOST_FIXTURE_TEST_CASE (size_8, TreeFixture3DDoubleInt2)
BOOST_FIXTURE_TEST_CASE (range_search_1, TreeFixture1DDoubleInt2)
BOOST_FIXTURE_TEST_CASE (range_search_2, TreeFixture1DDoubleInt2)
BOOST_FIXTURE_TEST_CASE (range_search_3, TreeFixture1DDoubleInt2)
BOOST_FIXTURE_TEST_CASE (range_search_4, TreeFixture2DDoubleInt1)
BOOST_FIXTURE_TEST_CASE (range_search_5, TreeFixture2DDoubleInt1)
BOOST_FIXTURE_TEST_CASE (range_search_6, TreeFixture10DDoubleInt1)
BOOST_FIXTURE_TEST_CASE (range_search_7, TreeFixture10DDoubleInt1)
BOOST_FIXTURE_TEST_CASE (range_search_8, TreeFixture3DDoubleString1)
BOOST_FIXTURE_TEST_CASE (range_search_9, TreeFixture3DDoubleString1)
BOOST_FIXTURE_TEST_CASE (range_search_10, TreeFixture1DIntInt1)
BOOST_FIXTURE_TEST_CASE (range_search_11, TreeFixture2DIntInt1)
BOOST_FIXTURE_TEST_CASE (range_search_inplace_1, TreeFixture10DDoubleInt1)
BOOST_FIXTURE_TEST_CASE (range_search_inserter_1, TreeFixture10DDoubleInt1)
BOOST_FIXTURE_TEST_CASE (range_search_map_1, TreeFixture10DDoubleInt1)
BOOST_FIXTURE_TEST_CASE (range_search_map_inserter_1, TreeFixture10DDoubleInt1)
BOOST_FIXTURE_TEST_CASE (range_search_map_inserter_2, TreeFixture2DIntInt1)
BOOST_FIXTURE_TEST_CASE (range_search_map_discard_1, TreeFixture2DIntInt1)
BOOST_FIXTURE_TEST_CASE (range_search_map_discard_2, TreeFixture3DDoubleInt2)
BOOST_FIXTURE_TEST_CASE (range_search_combinatorial, TreeFixture3DDoubleInt2)
BOOST_FIXTURE_TEST_CASE (range_search_dominate1, TreeFixture3DDoubleInt3)
BOOST_FIXTURE_TEST_CASE (range_search_dominate2, TreeFixture3DDoubleInt3)
BOOST_AUTO_TEST_CASE (range_search_very_big)
BOOST_AUTO_TEST_CASE (range_search_many_same)
void debug_level_test (const char *output_file, Logging::Level lvl)
unit test for a certain debug level
BOOST_AUTO_TEST_CASE (FATAL_test)
unit test for FATAL debug level
BOOST_AUTO_TEST_CASE (ERROR_test)
unit test for ERROR debug level
BOOST_AUTO_TEST_CASE (WARNING_test)
unit test for WARNING debug level
BOOST_AUTO_TEST_CASE (INFO_test)
unit test for INFO debug level
BOOST_AUTO_TEST_CASE (DEBUG_test)
unit test for DEBUG debug level
BOOST_AUTO_TEST_CASE (VERBOSE_test)
unit test for VERBOSE debug level
BOOST_AUTO_TEST_CASE (materialmap_creation)
BOOST_AUTO_TEST_CASE (all_of_test)
BOOST_AUTO_TEST_CASE (hana_set_union_test)
BOOST_AUTO_TEST_CASE (hana_set_to_tuple_test)
BOOST_AUTO_TEST_CASE (unpack_boost_set_as_template_test)
BOOST_AUTO_TEST_CASE (type_collector_test)
BOOST_AUTO_TEST_CASE (has_duplicates_test)
BOOST_AUTO_TEST_CASE (any_of_test)
BOOST_AUTO_TEST_CASE (are_sorted_helper_tests)
Unit test for Acts::anonymous_namespace{ParameterSet.h}are_sorted helper.
BOOST_AUTO_TEST_CASE (are_within_helper_tests)
Unit test for Acts::anonymous_namespace{ParameterSet.h}are_within helper.
BOOST_AUTO_TEST_CASE (at_index_helper_tests)
Unit test for Acts::details::at_index helper.
BOOST_AUTO_TEST_CASE (infinite_range_int)
BOOST_AUTO_TEST_CASE (infinite_range_double)
BOOST_AUTO_TEST_CASE (constructor_range_int)
BOOST_AUTO_TEST_CASE (constructor_range_double)
BOOST_AUTO_TEST_CASE (constructor_copy_double)
BOOST_AUTO_TEST_CASE (constructor_tuple_double)
BOOST_AUTO_TEST_CASE (assign_double)
BOOST_AUTO_TEST_CASE (shrinkMin_double)
BOOST_AUTO_TEST_CASE (shrinkMax_double)
BOOST_AUTO_TEST_CASE (shrink_both_double)
BOOST_AUTO_TEST_CASE (shrink_double)
BOOST_AUTO_TEST_CASE (shrink_twice_double)
BOOST_AUTO_TEST_CASE (shrink_noop_double)
BOOST_AUTO_TEST_CASE (shrink_noop_min_double)
BOOST_AUTO_TEST_CASE (shrink_noop_max_double)
BOOST_AUTO_TEST_CASE (shrinkMin_noop_double)
BOOST_AUTO_TEST_CASE (shrinkMax_noop_double)
BOOST_AUTO_TEST_CASE (setMin_double)
BOOST_AUTO_TEST_CASE (setMin_twice_double)
BOOST_AUTO_TEST_CASE (setMax_double)
BOOST_AUTO_TEST_CASE (setMax_twice_double)
BOOST_AUTO_TEST_CASE (expandMin_double)
BOOST_AUTO_TEST_CASE (expandMax_double)
BOOST_AUTO_TEST_CASE (expand_both_double)
BOOST_AUTO_TEST_CASE (expand_double)
BOOST_AUTO_TEST_CASE (expand_twice_double)
BOOST_AUTO_TEST_CASE (expand_noop_double)
BOOST_AUTO_TEST_CASE (expand_noop_min_double)
BOOST_AUTO_TEST_CASE (expand_noop_max_double)
BOOST_AUTO_TEST_CASE (expandMin_noop_double)
BOOST_AUTO_TEST_CASE (expandMax_noop_double)
BOOST_AUTO_TEST_CASE (size_double)
BOOST_AUTO_TEST_CASE (size_zero_double)
BOOST_AUTO_TEST_CASE (size_zero2_double)
BOOST_AUTO_TEST_CASE (degenerate_false_double)
BOOST_AUTO_TEST_CASE (degenerate_true_double)
BOOST_AUTO_TEST_CASE (contains_double)
BOOST_AUTO_TEST_CASE (contains_degenerate_double)
BOOST_AUTO_TEST_CASE (intersect_true1_double)
BOOST_AUTO_TEST_CASE (intersect_true2_double)
BOOST_AUTO_TEST_CASE (intersect_true3_double)
BOOST_AUTO_TEST_CASE (intersect_false1_double)
BOOST_AUTO_TEST_CASE (intersect_false2_double)
BOOST_AUTO_TEST_CASE (equals_true_int)
BOOST_AUTO_TEST_CASE (equals_false_int)
BOOST_AUTO_TEST_CASE (subset1_double)
BOOST_AUTO_TEST_CASE (subset2_double)
BOOST_AUTO_TEST_CASE (subset3_double)
BOOST_AUTO_TEST_CASE (subset4_double)
BOOST_AUTO_TEST_CASE (subset5_double)
BOOST_AUTO_TEST_CASE (superset1_double)
BOOST_AUTO_TEST_CASE (superset2_double)
BOOST_AUTO_TEST_CASE (superset3_double)
BOOST_AUTO_TEST_CASE (superset4_double)
BOOST_AUTO_TEST_CASE (superset5_double)
BOOST_AUTO_TEST_CASE (intersection1_double)
BOOST_AUTO_TEST_CASE (intersection2_double)
BOOST_AUTO_TEST_CASE (intersection3_double)
BOOST_AUTO_TEST_CASE (intersection4_double)
BOOST_AUTO_TEST_CASE (intersection5_double)
BOOST_AUTO_TEST_CASE (intersects_edge_int_positive)
BOOST_AUTO_TEST_CASE (intersects_edge_int_negative)
BOOST_AUTO_TEST_CASE (single_value_not_degenerate_int_positive)
BOOST_AUTO_TEST_CASE (single_value_not_degenerate_int_negative)
BOOST_AUTO_TEST_CASE (intersects_implies_non_degenerate_intersection)
BOOST_AUTO_TEST_CASE (degeneracy_implies_size_zero_intersection)
BOOST_AUTO_TEST_CASE (range_inclusive_left)
BOOST_AUTO_TEST_CASE (range_exclusive_right)
BOOST_AUTO_TEST_CASE (default_constructor_double)
BOOST_AUTO_TEST_CASE (mutate_ranges_double)
BOOST_AUTO_TEST_CASE (degenerate_double)
BOOST_AUTO_TEST_CASE (equality_int)
BOOST_AUTO_TEST_CASE (intersection_double)
BOOST_AUTO_TEST_CASE (intersection_false_double)
BOOST_AUTO_TEST_CASE (intersection_false2_double)
BOOST_AUTO_TEST_CASE (ray_construction)
BOOST_AUTO_TEST_CASE (RealQuadraticEquationConstruction)
Unit test for creating RealQuadraticEquation object.
BOOST_AUTO_TEST_CASE (RealQuadraticEquationProperties)
Unit test for RealQuadraticEquation properties.
BOOST_AUTO_TEST_CASE (RealQuadraticEquationAssignment)
Unit test for testing RealQuadraticEquation assignment.
BOOST_AUTO_TEST_CASE (TestConstruction)
BOOST_AUTO_TEST_CASE (TestErrorCodes)
Result< NoCopy > make_nocopy (int i, bool v=true)
BOOST_AUTO_TEST_CASE (CopyBehaviour)
Result< void > void_res_func (int b)
BOOST_AUTO_TEST_CASE (VoidResult)
BOOST_AUTO_TEST_CASE (BoolResult)
METHOD_TRAIT (foo_method_t, foo)
METHOD_TRAIT (bar_method_t, bar)
BOOST_AUTO_TEST_CASE (TypeTraitsMethods)
BOOST_AUTO_TEST_CASE (TypeTraitsMember)
BOOST_AUTO_TEST_CASE (TypeTraitsNestedType)
BOOST_AUTO_TEST_CASE (TypeTraitsConcepts)
Covariance makeRandomCovariance (int seed=31415)
BOOST_AUTO_TEST_CASE (compare_to_analytical_solution_for_single_track)
BOOST_AUTO_TEST_CASE (compare_to_analytical_solution_for_single_track_with_time)
BOOST_AUTO_TEST_CASE (seed_width_estimation)
BOOST_AUTO_TEST_CASE (track_adding)
BOOST_AUTO_TEST_CASE (max_z_t_and_width)
BOOST_AUTO_TEST_CASE (highest_density_sum)
BOOST_AUTO_TEST_CASE (track_removing)
BOOST_AUTO_TEST_CASE (adaptive_multi_vertex_finder_test)
AMVF test with Gaussian seed finder.
BOOST_AUTO_TEST_CASE (adaptive_multi_vertex_finder_usertype_test)
AMVF test with user-defined input track type.
BOOST_AUTO_TEST_CASE (adaptive_multi_vertex_finder_grid_seed_finder_test)
AMVF test with grid seed finder.
BOOST_AUTO_TEST_CASE (adaptive_multi_vertex_finder_adaptive_grid_seed_finder_test)
AMVF test with adaptive grid seed finder.
std::uniform_real_distribution vXYDist (-0.1_mm, 0.1_mm)
std::uniform_real_distribution vZDist (-20_mm, 20_mm)
std::uniform_real_distribution d0Dist (-0.01_mm, 0.01_mm)
std::uniform_real_distribution z0Dist (-0.2_mm, 0.2_mm)
std::uniform_real_distribution pTDist (1._GeV, 30._GeV)
std::uniform_real_distribution phiDist (-M_PI, M_PI)
std::uniform_real_distribution thetaDist (1.0, M_PI-1.0)
std::uniform_real_distribution qDist (-1, 1)
std::uniform_real_distribution resIPDist (0., 100._um)
std::uniform_real_distribution resAngDist (0., 0.1)
std::uniform_real_distribution resQoPDist (-0.1, 0.1)
std::uniform_int_distribution nTracksDist (3, 10)
BOOST_AUTO_TEST_CASE (adaptive_multi_vertex_fitter_test)
Unit test for AdaptiveMultiVertexFitter.
BOOST_AUTO_TEST_CASE (adaptive_multi_vertex_fitter_test_athena)
Unit test for AdaptiveMultiVertexFitter based on Athena unit test, i.e. same setting and test values are used here.
std::uniform_real_distribution vTDist (-1_ns, 1_ns)
std::uniform_real_distribution pTDist (0.4_GeV, 10_GeV)
std::uniform_real_distribution tDist (-0.002_ns, 0.002_ns)
std::uniform_real_distribution resIPDist (0., 100_um)
std::uniform_real_distribution resTDist (0.1_ns, 0.2_ns)
BOOST_AUTO_TEST_CASE (billoir_vertex_fitter_defaulttrack_test)
Unit test for FullBilloirVertexFitter with default input track type (= BoundTrackParameters)
BOOST_AUTO_TEST_CASE (gaussian_grid_density_test)
BOOST_AUTO_TEST_CASE (gaussian_grid_sum_max_densitytest)
Tests the functionality of the useHighestSumZPosition option.
BOOST_AUTO_TEST_CASE (gaussian_grid_seed_width_test)
Tests the seed width.
std::normal_distribution< double > xdist (1_mm, 0.1_mm)
std::normal_distribution< double > ydist (-0.7_mm, 0.1_mm)
std::normal_distribution< double > z1dist (zVertexPos1 *1_mm, 1_mm)
std::normal_distribution< double > z2dist (zVertexPos2 *1_mm, 0.5_mm)
std::uniform_real_distribution
< double > pTDist (0.1_GeV, 100_GeV)
std::uniform_real_distribution
< double > etaDist (-4., 4.)
BOOST_AUTO_TEST_CASE (grid_density_vertex_finder_test)
Unit test for GridDensityVertexFinder without caching of track density values.
BOOST_AUTO_TEST_CASE (grid_density_vertex_finder_track_caching_test)
BOOST_AUTO_TEST_CASE (grid_density_vertex_finder_seed_width_test)
Unit test for GridDensityVertexFinder with seed with estimation.
std::uniform_int_distribution nVertexDist (1, 6)
std::uniform_int_distribution nTracksDist (5, 15)
BOOST_AUTO_TEST_CASE (iterative_finder_test)
Unit test for IterativeVertexFinder for BoundTrackParameters.
BOOST_AUTO_TEST_CASE (iterative_finder_test_user_track_type)
Unit test for IterativeVertexFinder for user defined InputTrack track type.
BOOST_AUTO_TEST_CASE (iterative_finder_test_athena_reference)
Unit test for IterativeVertexFinder with Athena reference data.
BOOST_AUTO_TEST_CASE (Kalman_Vertex_TrackUpdater)
Unit test for KalmanVertexTrackUpdater.
BOOST_AUTO_TEST_CASE (Kalman_Vertex_Updater)
Unit test for KalmanVertexUpdater.
std::uniform_real_distribution resQoPDist (0.0, 0.1)
BOOST_AUTO_TEST_CASE (linearized_track_factory_test)
Test HelicalTrackLinearizer by comparing it to NumericalTrackLinearizer.
BOOST_AUTO_TEST_CASE (track_density_finder_test)
Unit test for TrackDensityVertexFinder using same configuration and values as VertexSeedFinderTestAlg in Athena implementation, i.e. tests if reordering tracks returns the same result.
BOOST_AUTO_TEST_CASE (track_density_finder_constr_test)
Unit test for TrackDensityVertexFinder using same configuration and values as VertexSeedFinderTestAlg in Athena implementation.
std::normal_distribution< double > z1dist (zVertexPos *1_mm, 1_mm)
std::normal_distribution< double > z2dist (-3_mm, 0.5_mm)
BOOST_AUTO_TEST_CASE (track_density_finder_random_test)
Unit test for TrackDensityVertexFinder using same configuration and values as VertexSeedFinderTestAlg in Athena implementation.
BOOST_AUTO_TEST_CASE (track_density_finder_usertrack_test)
Unit test for TrackDensityVertexFinder with user-defined input track type with same values as in other tests.
std::tuple< Vertex
< BoundTrackParameters >
, std::vector< VertexInfo >
, std::vector
< BoundTrackParameters > > readTracksAndVertexCSV (const std::string &toolString, const std::string &fileBase="vertexing_event_mu20")
BOOST_AUTO_TEST_CASE (zscan_finder_test)
Unit test for ZScanVertexFinder.
BOOST_AUTO_TEST_CASE (zscan_finder_usertrack_test)
Unit test for ZScanVertexFinder with user-defined input track type.
BOOST_AUTO_TEST_CASE (BoundTrackParametersVisualizationObj)
BOOST_AUTO_TEST_CASE (BoundTrackParametersVisualizationPly)
BOOST_AUTO_TEST_CASE (MeasurementVisualizationObj)
BOOST_AUTO_TEST_CASE (MeasurementVisualizationPly)
BOOST_AUTO_TEST_CASE (MultiTrajectoryVisualizationObj)
BOOST_AUTO_TEST_CASE (MultiTrajectoryVisualizationPly)
BOOST_AUTO_TEST_CASE (Visualization3DHelpers)
BOOST_AUTO_TEST_CASE (PrimitivesView3DObj)
BOOST_AUTO_TEST_CASE (PrimitivesView3DPly)
BOOST_AUTO_TEST_CASE (SurfaceView3DObj)
This tests if the corresponding obj output is well formatted.
BOOST_AUTO_TEST_CASE (SurfaceView3DPly)
This tests if the corresponding ply output is well formatted.
BOOST_AUTO_TEST_CASE (TrackingGeometryView3DObj)
This tests if the corresponding obj output is well formatted.
static std::vector< std::string > testObjString (const std::string &tString, bool triMesh=false)
static std::vector< std::string > testPlyString (const std::string &tString, bool triMesh=false)
BOOST_AUTO_TEST_CASE (Visualization3DTesterObj)
BOOST_AUTO_TEST_CASE (Visualization3DTesterPly)
BOOST_AUTO_TEST_CASE (Visualization3DConstruction)
BOOST_AUTO_TEST_CASE (PlyOutputTest)
BOOST_AUTO_TEST_CASE (ObjOutputTest)
BOOST_AUTO_TEST_CASE (VolumeView3DObj)
BOOST_AUTO_TEST_CASE (VolumeView3DPly)
BOOST_AUTO_TEST_CASE (Invalid)
BOOST_AUTO_TEST_CASE (DivByZero)
BOOST_AUTO_TEST_CASE (Overflow)
BOOST_AUTO_TEST_CASE (Combinations)
BOOST_AUTO_TEST_CASE (ClearOnEnter)
BOOST_AUTO_TEST_CASE (CheckRearmCount)
BOOST_AUTO_TEST_CASE (Scoping)
BOOST_AUTO_TEST_CASE (MergeDeduplication)
BOOST_AUTO_TEST_CASE (ScopedSuppression)
BOOST_AUTO_TEST_CASE (TGeoArb8_to_PlaneSurface)
Unit test to convert a TGeoTrd2 into a Plane.
ViewConfig red ({200, 0, 0})
ViewConfig green ({0, 200, 0})
ViewConfig blue ({0, 0, 200})
BOOST_AUTO_TEST_CASE (TGeoBBox_to_PlaneSurface)
Unit test to convert a Bbox into a Plane.
BOOST_AUTO_TEST_CASE (TGeoLayerBuilderTests)
Unit test checking the match probability.
BOOST_AUTO_TEST_CASE (TGeoMaterialConverter_materialSlab)
BOOST_AUTO_TEST_CASE (TGeoParser_Pixel)
Unit test Parsing a TGeo geometry.
BOOST_AUTO_TEST_CASE (TGeoParser_Pixel_SelectInnermost)
Unit test Parsing a TGeo geometries.
BOOST_AUTO_TEST_CASE (TGeoPrimitivesHelper_match)
Unit test checking the match probability.
BOOST_AUTO_TEST_CASE (TGeoTrd1_to_PlaneSurface)
Unit test to convert a TGeoTrd1 into a Plane.
BOOST_AUTO_TEST_CASE (TGeoTrd2_xz_to_PlaneSurface)
Unit test to convert a TGeoTrd2 into a Plane.
BOOST_AUTO_TEST_CASE (TGeoTrd2_yz_to_PlaneSurface)
Unit test to convert a TGeoTrd2 into a Plane.
BOOST_AUTO_TEST_CASE (TGeoTube_to_CylinderSurface)
Unit test to convert a TGeoTube into a CylinderSurface.
BOOST_AUTO_TEST_CASE (TGeoTube_to_DiscSurface)
Unit test to convert a TGeoTube into a DiscSurface.
Variables
unsigned int ntests = 10
unsigned int nrepts = 2000
const bool boundaryCheck = false
const bool testPlane = true
const bool testDisc = true
const bool testCylinder = true
const bool testStraw = true
GeometryContext tgContext = GeometryContext()
Transform3 at
auto rb = std::make_shared<RectangleBounds>(1_m, 1_m)
auto aPlane = Surface::makeShared<PlaneSurface>(at, std::move(rb))
auto db = std::make_shared<RadialBounds>(0.2_m, 1.2_m)
auto aDisc = Surface::makeShared<DiscSurface>(at, std::move(db))
auto cb = std::make_shared<CylinderBounds>(10_m, 100_m)
auto aCylinder = Surface::makeShared<CylinderSurface>(at, std::move(cb))
auto aStraw = Surface::makeShared<StrawSurface>(at, 50_cm, 2_m)
constexpr size_t bench_iters = 1'000
size_t nbinsx = 100
size_t nbinsy = 200
double hThickness = 75_um
double lAngle = 0.1
auto moduleBounds = std::make_shared<const RectangleBounds>(5_mm, 10_mm)
CartesianSegmentation cSegmentation (moduleBounds, nbinsx, nbinsy)
double halfX = 5_mm
double halfY = 10_mm
double tanAlpha = tan(lAngle)
double sguardX = 2 * hThickness * abs(tanAlpha)
DigitizationModule pdModule (cSegmentation, hThickness, 1, lAngle, 0., true)
DigitizationModule ndModule (cSegmentation, hThickness,-1, lAngle, 0., true)
std::vector< DigitizationModule > testModules = {pdModule, ndModule}
PlanarModuleStepper pmStepper
The Planar module stepper.
GeometryContext gctx = GeometryContext()
double hx {10.}
double hy {20.}
double hz {30.}
double iVsurfaceHalfLengthZ = 50_mm
double iVsurfaceR = 25_mm
double iVsurfaceRstagger = 5_mm
double iVsurfaceZoverlap = 10_mm
double iVlayerEnvelope = 0.5_mm
double iVvolumeEnvelope = 10_mm
double iVvolumeR
double oVsurfaceHalfLengthZ = 50_mm
the surface radius (will also be the layer radius)
double oVsurfaceR = 100_mm
double oVsurfaceRstagger = 5_mm
double oVsurfaceZoverlap = 10_mm
double oVlayerEnvelope = 0.5_mm
double oVvolumeEnvelope = 10_mm
double oVvolumeR
auto iVolume
inner volume
auto oVolume
outer volume
double oVvolumeHalfZ
auto hVolume
MagneticFieldContext mfContext = MagneticFieldContext()
Test::CubicBVHTrackingGeometry grid (NBOXES, 1000, 5)
auto volumes = grid.volumes
auto tg = grid.trackingGeometry
constexpr unsigned int dim = 2
constexpr float eps = 1.0f / 255u
static constexpr MockNavigator navigator
static constexpr auto stepSize = 10_mm
static constexpr auto tolerance = 10_um
static constexpr Direction navDir = Direction::Backward
static auto magneticField
static const Vector3 pos = pos4.segment<3>(ePos0)
static const auto time = pos4[eTime]
static const Vector3 unitDir = Vector3(-2, 2, 1).normalized()
static constexpr auto absMom = 1_GeV
static constexpr auto charge = -1_e
static const auto particleHypothesis = ParticleHypothesis::pion()
static const Covariance cov = Covariance::Identity()
static const GeometryContext geoCtx = GeometryContext()
static const MagneticFieldContext magCtx
CylindricalTrackingGeometry cGeometry (tgContext)
auto tGeometry = cGeometry()
DirectNavigator dnavigator
const double Bz = 2_T
auto bField = std::make_shared<BField>(Vector3{0, 0, Bz})
Stepper estepper (bField)
Stepper dstepper (bField)
const int skip = 0
bool debugMode = false
bool referenceTiming = false
bool oversteppingTest = false
double oversteppingMaxStepSize = 1_mm
static constexpr MockNavigator mockNavigator
std::vector< std::unique_ptr
< const Surface > > stepState
Navigator navigatorES ({tGeometry})
Navigator navigatorSL ({tGeometry})
StraightLineStepper slstepper
bool debugModeFwd = false
bool debugModeBwd = false
bool debugModeFwdStep = false
bool debugModeBwdStep = false
bool debug = true
auto mCylinder = std::make_shared<CylinderBounds>(10_mm, 1000_mm)
auto mSurface
auto cCylinder = std::make_shared<CylinderBounds>(150_mm, 1000_mm)
auto cSurface
static constexpr MockNavigator mockNavigator
const CalibrationContext calCtx
CubicTrackingGeometry geometryStore (geoCtx)
const auto geometry = geometryStore()
const MeasurementResolution resPixel
const MeasurementResolution resStrip
const MeasurementResolutionMap resolutions
const auto measPropagator = makeStraightPropagator(geometry)
double minRadius = 7.2
double maxRadius = 12.0
double minPhi = 0.74195
double maxPhi = 1.33970
GeometryContext testContext = GeometryContext()
std::vector< std::tuple
< std::string, bool, unsigned
int > > testModes
auto transform = std::make_shared<Transform3>(Transform3::Identity())
BinningData xData_eq (open, binX, 10, 0., 10.)
BinningData yData_eq (open, binY, 10, 0., 10.)
BinningData zData_eq (open, binZ, 10, 0., 10.)
BinningData rData_eq (open, binR, 10, 0., 10.)
BinningData phiData_eq (closed, binPhi, 5,-M_PI, M_PI)
BinningData rPhiData_eq (closed, binRPhi, 5,-M_PI, M_PI)
BinningData hData_eq (open, binH, 5, 0., 10.)
BinningData etaData_eq (open, binEta, 5,-2.5, 2.5)
BinningData xData_eq_copy (open, binX, 10, 0., 10.)
std::vector< float > values = {0., 1., 2., 3., 4., 10.}
BinningData xData_arb (open, binX, values)
BinningData yData_arb (open, binY, values)
std::vector< float > phiValues = {-M_PI, -2., -1., 1., 2., M_PI}
BinningData phiData_arb (closed, binPhi, phiValues)
size_t nBins_binary = 59
double valueMin = 0.
double phiMin = -M_PI
double delta = 0.5
double phiDelta = 0.1064
std::vector< float > sstr = {0., 1., 1.5, 2., 3.}
auto xData_sstr_mult = std::make_unique<const BinningData>(open, binX, sstr)
BinningData xData_mult (open, binX, 3, 0., 9., std::move(xData_sstr_mult))
std::vector< float > main_sstr = {0., 3., 4., 5.}
additive
auto xData_sstr_add = std::make_unique<const BinningData>(open, binX, sstr)
std::filesystem::path tmp_path
template<typename T >
constexpr bool SomeConcept
GeometryContext geoContext = GeometryContext()
MagneticFieldContext magFieldContext = MagneticFieldContext()
const std::string toolString = "AMVF"
const double zVertexPos1 = 12.
const double zVertexPos2 = -3.
const double zVertexPos = 12.
ViewConfig red ({200, 0, 0})
ViewConfig green ({0, 200, 0})
ViewConfig blue ({0, 0, 200})
RootGeometry rGeometry = RootGeometry()
std::vector< std::string > allowedAxes
std::vector< std::string > notAllowedAxes = {"YZ*", "ZX*", "ZY*"}
Typedef Documentation
using Acts::Test::AnalyticalLinearizer = typedef HelicalTrackLinearizer<HelicalPropagator>
Definition at line 54 of file LinearizedTrackFactoryTests.cpp.
View newest version in sPHENIX GitHub at line 54 of file LinearizedTrackFactoryTests.cpp
using Acts::Test::AngleAxis3F = typedef Eigen::AngleAxis<BoundingBoxScalar>
Definition at line 46 of file BoundingBoxTest.cpp.
View newest version in sPHENIX GitHub at line 46 of file BoundingBoxTest.cpp
using Acts::Test::AtlasStepperType = typedef AtlasStepper
Definition at line 48 of file JacobianTests.cpp.
View newest version in sPHENIX GitHub at line 48 of file JacobianTests.cpp
typedef ConstantBField Acts::Test::BField
Definition at line 64 of file DirectNavigatorTests.cpp.
View newest version in sPHENIX GitHub at line 64 of file DirectNavigatorTests.cpp
typedef ConstantBField Acts::Test::BFieldType
Definition at line 68 of file ExtrapolatorTests.cpp.
View newest version in sPHENIX GitHub at line 68 of file ExtrapolatorTests.cpp
using Acts::Test::BoundingBoxScalar = typedef ActsScalar
Definition at line 40 of file BoundingBoxTest.cpp.
View newest version in sPHENIX GitHub at line 40 of file BoundingBoxTest.cpp
using Acts::Test::Box = typedef Acts::Volume::BoundingBox
Definition at line 15 of file TrackingVolumeTests.cpp.
View newest version in sPHENIX GitHub at line 15 of file TrackingVolumeTests.cpp
using Acts::Test::ConstantFieldPropagator = typedef Propagator<ConstantFieldStepper, Navigator>
Definition at line 61 of file SpacePointBuilderTests.cpp.
View newest version in sPHENIX GitHub at line 61 of file SpacePointBuilderTests.cpp
using Acts::Test::ConstantFieldStepper = typedef EigenStepper<>
Definition at line 60 of file SpacePointBuilderTests.cpp.
View newest version in sPHENIX GitHub at line 60 of file SpacePointBuilderTests.cpp
typedef BoundSquareMatrix Acts::Test::Covariance
Definition at line 56 of file AtlasStepperTests.cpp.
View newest version in sPHENIX GitHub at line 56 of file AtlasStepperTests.cpp
using Acts::Test::DirectPropagator = typedef Propagator<Stepper, DirectNavigator>
Definition at line 67 of file DirectNavigatorTests.cpp.
View newest version in sPHENIX GitHub at line 67 of file DirectNavigatorTests.cpp
using Acts::Test::EAxis = typedef Acts::detail::EquidistantAxis
Definition at line 34 of file MaterialGridHelperTests.cpp.
View newest version in sPHENIX GitHub at line 34 of file MaterialGridHelperTests.cpp
typedef Propagator< EigenStepper, Navigator > Acts::Test::EigenPropagator
Definition at line 162 of file LoopProtectionTests.cpp.
View newest version in sPHENIX GitHub at line 162 of file LoopProtectionTests.cpp
typedef Propagator< EigenStepperType > Acts::Test::EigenPropagatorType
Definition at line 70 of file ExtrapolatorTests.cpp.
View newest version in sPHENIX GitHub at line 70 of file ExtrapolatorTests.cpp
typedef Acts::EigenStepper<> Acts::Test::EigenStepper
Definition at line 161 of file LoopProtectionTests.cpp.
View newest version in sPHENIX GitHub at line 161 of file LoopProtectionTests.cpp
typedef EigenStepper<> Acts::Test::EigenStepperType
Definition at line 69 of file ExtrapolatorTests.cpp.
View newest version in sPHENIX GitHub at line 69 of file ExtrapolatorTests.cpp
using Acts::Test::Grid2D = typedef Acts::detail::Grid<Acts::AccumulatedVolumeMaterial, EAxis, EAxis>
Definition at line 36 of file MaterialGridHelperTests.cpp.
View newest version in sPHENIX GitHub at line 36 of file MaterialGridHelperTests.cpp
using Acts::Test::Grid3D = typedef Acts::detail::Grid<Acts::AccumulatedVolumeMaterial, EAxis, EAxis, EAxis>
Definition at line 38 of file MaterialGridHelperTests.cpp.
View newest version in sPHENIX GitHub at line 38 of file MaterialGridHelperTests.cpp
using Acts::Test::grid_t = typedef detail::Grid<Acts::Material::ParametersVector, detail::EquidistantAxis, detail::EquidistantAxis>
Definition at line 37 of file InterpolatedMaterialMapTests.cpp.
View newest version in sPHENIX GitHub at line 37 of file InterpolatedMaterialMapTests.cpp
using Acts::Test::HelicalPropagator = typedef Propagator<EigenStepper<>>
Definition at line 52 of file LinearizedTrackFactoryTests.cpp.
View newest version in sPHENIX GitHub at line 52 of file LinearizedTrackFactoryTests.cpp
typedef BoundMatrix Acts::Test::Jacobian
Definition at line 57 of file AtlasStepperTests.cpp.
View newest version in sPHENIX GitHub at line 57 of file AtlasStepperTests.cpp
typedef HelicalTrackLinearizer< Propagator > Acts::Test::Linearizer
Definition at line 64 of file AdaptiveMultiVertexFinderTests.cpp.
View newest version in sPHENIX GitHub at line 64 of file AdaptiveMultiVertexFinderTests.cpp
using Acts::Test::Linearizer_t = typedef HelicalTrackLinearizer<Propagator>
Definition at line 58 of file ZScanVertexFinderTests.cpp.
View newest version in sPHENIX GitHub at line 58 of file ZScanVertexFinderTests.cpp
using Acts::Test::MaterialGrid2D = typedef Acts::detail::Grid<Acts::Material::ParametersVector, EAxis, EAxis>
Definition at line 40 of file MaterialGridHelperTests.cpp.
View newest version in sPHENIX GitHub at line 40 of file MaterialGridHelperTests.cpp
using Acts::Test::MaterialGrid3D = typedef Acts::detail::Grid<Acts::Material::ParametersVector, EAxis, EAxis, EAxis>
Definition at line 42 of file MaterialGridHelperTests.cpp.
View newest version in sPHENIX GitHub at line 42 of file MaterialGridHelperTests.cpp
using Acts::Test::MatrixProductTypes = typedef std::tuple<std::pair<ActsMatrix<3, 3>, ActsMatrix<3, 3>>, std::pair<ActsMatrix<4, 4>, ActsMatrix<4, 4>>, std::pair<ActsMatrix<8, 8>, ActsMatrix<8, 8>>, std::pair<ActsMatrix<8, 7>, ActsMatrix<7, 4>>>
Definition at line 177 of file HelpersTests.cpp.
View newest version in sPHENIX GitHub at line 177 of file HelpersTests.cpp
using Acts::Test::MeasurementResolutionMap = typedef Acts::GeometryHierarchyMap<MeasurementResolution>
Measurement resolution configuration for a full detector geometry.
Definition at line 45 of file MeasurementsCreator.hpp.
View newest version in sPHENIX GitHub at line 45 of file MeasurementsCreator.hpp
template<typename T > using Acts::Test::member_a_t = typedef decltype(std::declval<T>().member_a)
Definition at line 91 of file TypeTraitsTest.cpp.
View newest version in sPHENIX GitHub at line 91 of file TypeTraitsTest.cpp
template<typename T > using Acts::Test::member_b_t = typedef decltype(std::declval<T>().member_b)
Definition at line 94 of file TypeTraitsTest.cpp.
View newest version in sPHENIX GitHub at line 94 of file TypeTraitsTest.cpp
template<typename T > using Acts::Test::member_t = typedef decltype(std::declval<T>().member)
Definition at line 170 of file TypeTraitsTest.cpp.
View newest version in sPHENIX GitHub at line 170 of file TypeTraitsTest.cpp
template<typename T > using Acts::Test::meta_t = typedef typename T::template meta<void, void>
Definition at line 178 of file TypeTraitsTest.cpp.
View newest version in sPHENIX GitHub at line 178 of file TypeTraitsTest.cpp
template<typename T > using Acts::Test::nested_a_t = typedef typename T::NestedA
Definition at line 140 of file TypeTraitsTest.cpp.
View newest version in sPHENIX GitHub at line 140 of file TypeTraitsTest.cpp
template<typename T > using Acts::Test::nested_b_t = typedef typename T::NestedB
Definition at line 142 of file TypeTraitsTest.cpp.
View newest version in sPHENIX GitHub at line 142 of file TypeTraitsTest.cpp
template<typename T > using Acts::Test::nested_t = typedef typename T::Nested
Definition at line 174 of file TypeTraitsTest.cpp.
View newest version in sPHENIX GitHub at line 174 of file TypeTraitsTest.cpp
using Acts::Test::NumericalLinearizer = typedef NumericalTrackLinearizer<HelicalPropagator>
Definition at line 56 of file LinearizedTrackFactoryTests.cpp.
View newest version in sPHENIX GitHub at line 56 of file LinearizedTrackFactoryTests.cpp
using Acts::Test::ObjectBBox = typedef Acts::AxisAlignedBoundingBox<Object, BoundingBoxScalar, 3>
Definition at line 42 of file BoundingBoxTest.cpp.
View newest version in sPHENIX GitHub at line 42 of file BoundingBoxTest.cpp
typedef PathLimitReached Acts::Test::path_limit
Definition at line 58 of file ExtrapolatorTests.cpp.
View newest version in sPHENIX GitHub at line 58 of file ExtrapolatorTests.cpp
using Acts::Test::Propagator = typedef Acts::Propagator<EigenStepper<>>
Definition at line 63 of file AdaptiveMultiVertexFinderTests.cpp.
View newest version in sPHENIX GitHub at line 63 of file AdaptiveMultiVertexFinderTests.cpp
using Acts::Test::Ray = typedef Acts::Ray<double, 3>
Definition at line 16 of file TrackingVolumeTests.cpp.
View newest version in sPHENIX GitHub at line 16 of file TrackingVolumeTests.cpp
using Acts::Test::RecordedMaterial = typedef std::vector<std::pair<Acts::Material, Acts::Vector3>>
Definition at line 33 of file MaterialGridHelperTests.cpp.
View newest version in sPHENIX GitHub at line 33 of file MaterialGridHelperTests.cpp
using Acts::Test::Rectangle = typedef std::array<int, 4>
Definition at line 30 of file ClusterizationTests2D.cpp.
View newest version in sPHENIX GitHub at line 30 of file ClusterizationTests2D.cpp
using Acts::Test::ReferencePropagator = typedef Propagator<Stepper, Navigator>
Definition at line 66 of file DirectNavigatorTests.cpp.
View newest version in sPHENIX GitHub at line 66 of file DirectNavigatorTests.cpp
using Acts::Test::SrfVec = typedef std::vector<std::shared_ptr<const Surface>>
Definition at line 64 of file LayerCreatorTests.cpp.
View newest version in sPHENIX GitHub at line 64 of file LayerCreatorTests.cpp
typedef EigenStepper<> Acts::Test::Stepper
Definition at line 58 of file AtlasStepperTests.cpp.
View newest version in sPHENIX GitHub at line 58 of file AtlasStepperTests.cpp
using Acts::Test::StraightAnalyticalLinearizer = typedef HelicalTrackLinearizer<StraightPropagator>
Definition at line 55 of file LinearizedTrackFactoryTests.cpp.
View newest version in sPHENIX GitHub at line 55 of file LinearizedTrackFactoryTests.cpp
using Acts::Test::StraightLinePropagator = typedef Propagator<StraightLineStepper, Navigator>
Definition at line 71 of file MaterialCollectionTests.cpp.
View newest version in sPHENIX GitHub at line 71 of file MaterialCollectionTests.cpp
using Acts::Test::StraightNumericalLinearizer = typedef NumericalTrackLinearizer<StraightPropagator>
Definition at line 58 of file LinearizedTrackFactoryTests.cpp.
View newest version in sPHENIX GitHub at line 58 of file LinearizedTrackFactoryTests.cpp
typedef Propagator< StraightLineStepper > Acts::Test::StraightPropagator
Definition at line 57 of file SpacePointBuilderTests.cpp.
View newest version in sPHENIX GitHub at line 57 of file SpacePointBuilderTests.cpp
using Acts::Test::TestMeasurement = typedef BoundVariantMeasurement
Definition at line 59 of file SpacePointBuilderTests.cpp.
View newest version in sPHENIX GitHub at line 59 of file SpacePointBuilderTests.cpp
using Acts::Test::TestSpacePointContainer = typedef std::vector<TestSpacePoint>
Container of space points.
Definition at line 85 of file TestSpacePoint.hpp.
View newest version in sPHENIX GitHub at line 85 of file TestSpacePoint.hpp
using Acts::Test::Vector2F = typedef Eigen::Matrix<BoundingBoxScalar, 2, 1>
Definition at line 44 of file BoundingBoxTest.cpp.
View newest version in sPHENIX GitHub at line 44 of file BoundingBoxTest.cpp
using Acts::Test::Vector3F = typedef Eigen::Matrix<BoundingBoxScalar, 3, 1>
Definition at line 45 of file BoundingBoxTest.cpp.
View newest version in sPHENIX GitHub at line 45 of file BoundingBoxTest.cpp
Enumeration Type Documentation
enum Acts::Test::MeasurementType
All supported simulated measurement types.
Definition at line 30 of file MeasurementsCreator.hpp.
View newest version in sPHENIX GitHub at line 30 of file MeasurementsCreator.hpp
enum Acts::Test::VertexCsvData
Enumerator:
BeamSpotData
VerticesData
TracksData
Definition at line 28 of file VertexingDataHelper.hpp.
View newest version in sPHENIX GitHub at line 28 of file VertexingDataHelper.hpp
Function Documentation
template<typename T > void Acts::Test::addToWhiteBoard (std::string name, T data, ActsExamples::WhiteBoard & wb)
Definition at line 29 of file WhiteBoardUtilities.hpp.
View newest version in sPHENIX GitHub at line 29 of file WhiteBoardUtilities.hpp
References ActsExamples::WriteDataHandle< T >::initialize(), and testing::internal::move().
Referenced by Acts::Test::GenericReadWriteTool< val_tuple_t, str_tuple_t >::write().
bool Acts::Test::approximatelyEqual (const Vector2 & a, const Vector2 & b)
Definition at line 38 of file RectangleBoundsTests.cpp.
View newest version in sPHENIX GitHub at line 38 of file RectangleBoundsTests.cpp
References Acts::UnitConstants::e.
template<typename T > void Acts::Test::assumeAccessed (T && clobber)
Definition at line 128 of file BenchmarkTools.hpp.
View newest version in sPHENIX GitHub at line 128 of file BenchmarkTools.hpp
Referenced by assumeRead(), assumeWritten(), and BOOST_AUTO_TEST_CASE().
template<typename T > void Acts::Test::assumeRead (const T & clobber) inline
Definition at line 151 of file BenchmarkTools.hpp.
View newest version in sPHENIX GitHub at line 151 of file BenchmarkTools.hpp
References assumeAccessed().
Referenced by BOOST_AUTO_TEST_CASE(), Acts::Test::benchmark_tools_internal::MicroBenchmarkIterImpl< Callable, Input, Result >::iter(), and Acts::Test::benchmark_tools_internal::MicroBenchmarkIterImpl< Callable, void, Result >::iter().
template<typename T > void Acts::Test::assumeWritten (T & clobber) inline
Definition at line 167 of file BenchmarkTools.hpp.
View newest version in sPHENIX GitHub at line 167 of file BenchmarkTools.hpp
References assumeAccessed().
Referenced by BOOST_AUTO_TEST_CASE(), Acts::Test::benchmark_tools_internal::MicroBenchmarkIterImpl< Callable, Input, Result >::iter(), Acts::Test::benchmark_tools_internal::MicroBenchmarkIterImpl< Callable, Input, void >::iter(), Acts::Test::benchmark_tools_internal::MicroBenchmarkIterImpl< Callable, void, Result >::iter(), and Acts::Test::benchmark_tools_internal::MicroBenchmarkIterImpl< Callable, void, void >::iter().
void Acts::Test::basicChecks (bool circleCase = false)
Definition at line 27 of file IntersectionHelper2DTests.cpp.
View newest version in sPHENIX GitHub at line 27 of file IntersectionHelper2DTests.cpp
References CHECK_CLOSE_ABS, Acts::detail::IntersectionHelper2D::intersectCircle(), Acts::detail::IntersectionHelper2D::intersectEllipse(), position, Acts::s_epsilon, start, ambiguity_solver_full_chain::x, and y.
Referenced by BOOST_AUTO_TEST_CASE().
ViewConfig Acts::Test::blue ({0, 0, 200})
Acts::Test::BOOST_AUTO_TEST_CASE (GeometryIdentifier_construct_default)
Definition at line 16 of file GeometryIdentifierTests.cpp.
View newest version in sPHENIX GitHub at line 16 of file GeometryIdentifierTests.cpp
References train_ambiguity_solver::id, layer, and physmon_ckf_tracking::u.
Acts::Test::BOOST_AUTO_TEST_CASE (AuctioneerTest_VoidAuctioneer)
Definition at line 18 of file AuctioneerTests.cpp.
View newest version in sPHENIX GitHub at line 18 of file AuctioneerTests.cpp
Acts::Test::BOOST_AUTO_TEST_CASE (ray_construction)
Definition at line 21 of file RayTest.cpp.
View newest version in sPHENIX GitHub at line 21 of file RayTest.cpp
References CHECK_CLOSE_ABS, Acts::UnitConstants::e, and check_smearing_config::output.
Acts::Test::BOOST_AUTO_TEST_CASE (annealing_tool_singleChi2_tests)
Definition at line 21 of file AnnealingUtilityTests.cpp.
View newest version in sPHENIX GitHub at line 21 of file AnnealingUtilityTests.cpp
References Acts::AnnealingUtility::anneal(), filter::config, Acts::AnnealingUtility::State::currentTemperatureIndex, Acts::AnnealingUtility::Config::cutOff, Acts::AnnealingUtility::State::equilibriumReached, Acts::AnnealingUtility::getWeight(), Acts::AnnealingUtility::Config::setOfTemperatures, filter::state, and physmon_ckf_tracking::u.
Acts::Test::BOOST_AUTO_TEST_CASE (CylindricalTrackingGeometryTest)
Definition at line 21 of file TrackingGeometryCreationTests.cpp.
View newest version in sPHENIX GitHub at line 21 of file TrackingGeometryCreationTests.cpp
References cGeometry, tgContext, and tGeometry.
Acts::Test::BOOST_AUTO_TEST_CASE (default_constructor_double)
Definition at line 22 of file RangeXDTests.cpp.
View newest version in sPHENIX GitHub at line 22 of file RangeXDTests.cpp
References Acts::UnitConstants::min, and physmon_track_finding_ttbar::r.
Acts::Test::BOOST_AUTO_TEST_CASE (HomogeneousVolumeMaterial_construction_test)
Test the constructors.
Definition at line 22 of file HomogeneousVolumeMaterialTests.cpp.
View newest version in sPHENIX GitHub at line 22 of file HomogeneousVolumeMaterialTests.cpp
References Acts::Material::fromMolarDensity(), and testing::internal::move().
Acts::Test::BOOST_AUTO_TEST_CASE (ProtoVolumeMaterial_construction_test)
Test the constructors.
Definition at line 22 of file ProtoVolumeMaterialTests.cpp.
View newest version in sPHENIX GitHub at line 22 of file ProtoVolumeMaterialTests.cpp
References Acts::binX, Acts::binY, Acts::binZ, testing::internal::move(), and Acts::open.
Acts::Test::BOOST_AUTO_TEST_CASE (ProtoSurfaceMaterial_construction_test)
Test the constructors.
Definition at line 22 of file ProtoSurfaceMaterialTests.cpp.
View newest version in sPHENIX GitHub at line 22 of file ProtoSurfaceMaterialTests.cpp
References Acts::binX, Acts::binY, testing::internal::move(), and Acts::open.
Acts::Test::BOOST_AUTO_TEST_CASE (string_hashes)
Definition at line 22 of file HashedStringTests.cpp.
View newest version in sPHENIX GitHub at line 22 of file HashedStringTests.cpp
References Acts::hashString(), and physmon_simulation::s.
Acts::Test::BOOST_AUTO_TEST_CASE (VolumeBoundsTest)
Definition at line 22 of file VolumeBoundsTests.cpp.
View newest version in sPHENIX GitHub at line 22 of file VolumeBoundsTests.cpp
References Acts::s_planeXY, Acts::s_planeYZ, and Acts::s_planeZX.
Acts::Test::BOOST_AUTO_TEST_CASE (vacuum)
Definition at line 23 of file AccumulatedVolumeMaterialTests.cpp.
View newest version in sPHENIX GitHub at line 23 of file AccumulatedVolumeMaterialTests.cpp
References Acts::AccumulatedVolumeMaterial::accumulate(), and Acts::AccumulatedVolumeMaterial::average().
Acts::Test::BOOST_AUTO_TEST_CASE (InfiniteBoundsConstruction)
Unit test for creating compliant/non-compliant InfiniteBounds object.
Definition at line 23 of file InfiniteBoundsTests.cpp.
View newest version in sPHENIX GitHub at line 23 of file InfiniteBoundsTests.cpp
References Acts::SurfaceBounds::eBoundless, Acts::InfiniteBounds::type(), physmon_ckf_tracking::u, and testSigmaEff::v.
Acts::Test::BOOST_AUTO_TEST_CASE (TypeErasedCacheType)
Definition at line 23 of file MagneticFieldProviderTests.cpp.
View newest version in sPHENIX GitHub at line 23 of file MagneticFieldProviderTests.cpp
References testSigmaEff::v, v2, and value.
Acts::Test::BOOST_AUTO_TEST_CASE (construct_element_fraction)
Definition at line 23 of file MaterialCompositionTests.cpp.
View newest version in sPHENIX GitHub at line 23 of file MaterialCompositionTests.cpp
References KFPMath::a, KFPMath::b, CHECK_CLOSE_REL, Acts::ElementFraction::element(), eps, Acts::ElementFraction::fraction(), and physmon_ckf_tracking::u.
Acts::Test::BOOST_AUTO_TEST_CASE (equidistant_axis)
Definition at line 24 of file AxesTests.cpp.
View newest version in sPHENIX GitHub at line 24 of file AxesTests.cpp
References KFPMath::a, and physmon_ckf_tracking::u.
Acts::Test::BOOST_AUTO_TEST_CASE (alignment_helper_test)
Test for rotation matrix and calculation of derivative of rotated x/y/z axis w.r.t. rotation parameters
Definition at line 24 of file AlignmentHelperTests.cpp.
View newest version in sPHENIX GitHub at line 24 of file AlignmentHelperTests.cpp
References alpha, CHECK_CLOSE_ABS, Acts::UnitConstants::e, Acts::detail::rotationToLocalAxesDerivative(), transform, and translation().
Acts::Test::BOOST_AUTO_TEST_CASE (BinnedSurfaceMaterial_construction_test)
Test the constructors.
Definition at line 25 of file BinnedSurfaceMaterialTests.cpp.
View newest version in sPHENIX GitHub at line 25 of file BinnedSurfaceMaterialTests.cpp
References Acts::binX, Acts::binY, Acts::Material::fromMolarDensity(), testSigmaEff::l1, testSigmaEff::l2, Acts::UnitConstants::m, testing::internal::move(), and Acts::open.
Acts::Test::BOOST_AUTO_TEST_CASE (TGeoPrimitivesHelper_match)
Unit test checking the match probability.
Definition at line 25 of file TGeoPrimitivesHelperTests.cpp.
View newest version in sPHENIX GitHub at line 25 of file TGeoPrimitivesHelperTests.cpp
References Acts::TGeoPrimitivesHelper::match().
Acts::Test::BOOST_AUTO_TEST_CASE (GeometryIdentifier_construct_encoded)
Definition at line 25 of file GeometryIdentifierTests.cpp.
View newest version in sPHENIX GitHub at line 25 of file GeometryIdentifierTests.cpp
References layer, and physmon_ckf_tracking::u.
Acts::Test::BOOST_AUTO_TEST_CASE (interpolation_1d)
Definition at line 25 of file InterpolationTests.cpp.
View newest version in sPHENIX GitHub at line 25 of file InterpolationTests.cpp
References CHECK_CLOSE_REL, Acts::UnitConstants::e, Acts::interpolate(), and testSigmaEff::v.
Acts::Test::BOOST_AUTO_TEST_CASE (RealQuadraticEquationConstruction)
Unit test for creating RealQuadraticEquation object.
Test construction with parameters
Copy constructor (implicit), void removes 'unused' compiler warning
Definition at line 26 of file RealQuadraticEquationTests.cpp.
View newest version in sPHENIX GitHub at line 26 of file RealQuadraticEquationTests.cpp
References KFPMath::a, KFPMath::b, and Acts::PhysicalConstants::c.
Acts::Test::BOOST_AUTO_TEST_CASE (HomogeneousSurfaceMaterial_construction_test)
Test the constructors.
Definition at line 26 of file HomogeneousSurfaceMaterialTests.cpp.
View newest version in sPHENIX GitHub at line 26 of file HomogeneousSurfaceMaterialTests.cpp
References Acts::Material::fromMolarDensity(), and testing::internal::move().
Acts::Test::BOOST_AUTO_TEST_CASE (BoundTrackParametersVisualizationObj)
Definition at line 26 of file EventDataView3DTests.cpp.
View newest version in sPHENIX GitHub at line 26 of file EventDataView3DTests.cpp
References test_fpe::count, Acts::EventDataView3DTest::testBoundTrackParameters(), and testObjString().
Acts::Test::BOOST_AUTO_TEST_CASE (ConstrainedStepTest)
Definition at line 26 of file ConstrainedStepTests.cpp.
View newest version in sPHENIX GitHub at line 26 of file ConstrainedStepTests.cpp
References Acts::ConstrainedStep::aborter, Acts::ConstrainedStep::accuracy(), Acts::ConstrainedStep::actor, Acts::ConstrainedStep::releaseAccuracy(), Acts::ConstrainedStep::setAccuracy(), Acts::ConstrainedStep::update(), Acts::ConstrainedStep::user, and Acts::ConstrainedStep::value().
Acts::Test::BOOST_AUTO_TEST_CASE (TrackingGeometryView3DObj)
This tests if the corresponding obj output is well formatted.
Definition at line 27 of file TrackingGeometryView3DTests.cpp.
View newest version in sPHENIX GitHub at line 27 of file TrackingGeometryView3DTests.cpp
References Acts::TrackingGeometryView3DTest::run(), and testObjString().
Acts::Test::BOOST_AUTO_TEST_CASE (BinUtility_equidistant_binning)
Definition at line 27 of file BinUtilityTests.cpp.
View newest version in sPHENIX GitHub at line 27 of file BinUtilityTests.cpp
References Acts::BinUtility::bins(), Acts::BinUtility::binTriple(), Acts::binX, Acts::binY, Acts::binZ, Acts::BinUtility::dimensions(), Acts::open, physmon_ckf_tracking::u, and xyzPosition().
Acts::Test::BOOST_AUTO_TEST_CASE (Extendable_)
Definition at line 27 of file ExtendableTests.cpp.
View newest version in sPHENIX GitHub at line 27 of file ExtendableTests.cpp
References Acts::detail::Extendable< extensions_t >::append(), Acts::PhysicalConstants::c, Acts::detail::Extendable< extensions_t >::get(), physmon_ckf_tracking::u, and value.
Acts::Test::BOOST_AUTO_TEST_CASE (CubicTrackingGeometryTest)
Definition at line 27 of file TrackingGeometryCreationTests.cpp.
View newest version in sPHENIX GitHub at line 27 of file TrackingGeometryCreationTests.cpp
References cGeometry, tgContext, and tGeometry.
Acts::Test::BOOST_AUTO_TEST_CASE (AccumulatedSurfaceMaterial_construction_test)
Test the constructors.
Definition at line 28 of file AccumulatedSurfaceMaterialTests.cpp.
View newest version in sPHENIX GitHub at line 28 of file AccumulatedSurfaceMaterialTests.cpp
References Acts::AccumulatedSurfaceMaterial::accumulatedMaterial(), Acts::binX, Acts::binY, add_histos_bX::ib, Acts::open, size, and physmon_ckf_tracking::u.
Acts::Test::BOOST_AUTO_TEST_CASE (DiamondBoundsConstruction)
Unit test for creating compliant/non-compliant DiamondBounds object.
Test construction with dimensions
Copy constructor
Definition at line 28 of file DiamondBoundsTests.cpp.
View newest version in sPHENIX GitHub at line 28 of file DiamondBoundsTests.cpp
References db, Acts::SurfaceBounds::eDiamond, Acts::type, and Acts::DiamondBounds::type().
Acts::Test::BOOST_AUTO_TEST_CASE (LineBoundsConstruction)
Unit test for creating compliant/non-compliant LineBounds object.
test LineBounds(double, double)
test copy construction;
Definition at line 28 of file LineBoundsTests.cpp.
View newest version in sPHENIX GitHub at line 28 of file LineBoundsTests.cpp
References Acts::SurfaceBounds::eLine, and Acts::LineBounds::type().
Acts::Test::BOOST_AUTO_TEST_CASE (SurfaceView3DObj)
This tests if the corresponding obj output is well formatted.
Definition at line 28 of file SurfaceView3DTests.cpp.
View newest version in sPHENIX GitHub at line 28 of file SurfaceView3DTests.cpp
References Acts::SurfaceView3DTest::run(), and testObjString().
Acts::Test::BOOST_AUTO_TEST_CASE (VolumeView3DObj)
Definition at line 28 of file VolumeView3DTests.cpp.
View newest version in sPHENIX GitHub at line 28 of file VolumeView3DTests.cpp
References Acts::VolumeView3DTest::run(), and testObjString().
Acts::Test::BOOST_AUTO_TEST_CASE (TGeoMaterialConverter_materialSlab)
Definition at line 28 of file TGeoMaterialConverterTests.cpp.
View newest version in sPHENIX GitHub at line 28 of file TGeoMaterialConverterTests.cpp
References Acts::Material::Ar(), CHECK_CLOSE_ABS, Acts::UnitConstants::e, Acts::Material::L0(), Acts::Material::massDensity(), Acts::MaterialSlab::material(), Acts::TGeoMaterialConverter::materialSlab(), ckf::options, rho, Acts::MaterialSlab::thickness(), Acts::MaterialSlab::thicknessInL0(), Acts::MaterialSlab::thicknessInX0(), Acts::Material::X0(), SVM_v1::Z, and Acts::Material::Z().
Acts::Test::BOOST_AUTO_TEST_CASE (frustum_construction)
Definition at line 28 of file FrustumTest.cpp.
View newest version in sPHENIX GitHub at line 28 of file FrustumTest.cpp
References CHECK_CLOSE_ABS, Acts::UnitConstants::e, check_smearing_config::output, and physmon_ckf_tracking::u.
Acts::Test::BOOST_AUTO_TEST_CASE (infinite_range_int)
Definition at line 28 of file Range1DTests.cpp.
View newest version in sPHENIX GitHub at line 28 of file Range1DTests.cpp
References Acts::Range1D< Type >::max(), Acts::Range1D< Type >::min(), and physmon_track_finding_ttbar::r.
Acts::Test::BOOST_AUTO_TEST_CASE (assume_accessed)
Definition at line 29 of file BenchmarkTools.cpp.
View newest version in sPHENIX GitHub at line 29 of file BenchmarkTools.cpp
References assumeAccessed(), and ambiguity_solver_full_chain::x.
Acts::Test::BOOST_AUTO_TEST_CASE (covariance_transport_invalid)
Definition at line 29 of file CovarianceTransportTests.cpp.
View newest version in sPHENIX GitHub at line 29 of file CovarianceTransportTests.cpp
References Acts::CovarianceCache::applyTransport.
Acts::Test::BOOST_AUTO_TEST_CASE (BinAdjustmentVolume_Cylinder)
Definition at line 29 of file BinAdjustmentVolumeTests.cpp.
View newest version in sPHENIX GitHub at line 29 of file BinAdjustmentVolumeTests.cpp
References Acts::adjustBinUtility(), Acts::BinUtility::binningData(), Acts::binPhi, Acts::binR, Acts::binZ, and Acts::open.
Acts::Test::BOOST_AUTO_TEST_CASE (jacobian_engine_helper)
Helper function tests.
Definition at line 29 of file JacobianEngineTests.cpp.
View newest version in sPHENIX GitHub at line 29 of file JacobianEngineTests.cpp
References Acts::detail::anglesToDirectionJacobian(), Acts::PhysicalConstants::c, CHECK_CLOSE_REL, Acts::detail::curvilinearToFreeJacobian(), Acts::detail::directionToAnglesJacobian(), Acts::UnitConstants::e, Acts::eBoundLoc0, Acts::eBoundLoc1, Acts::eBoundPhi, Acts::eBoundQOverP, Acts::eBoundTheta, Acts::eBoundTime, Acts::eFreeDir0, Acts::eFreeDir1, Acts::eFreeDir2, Acts::eFreePos0, Acts::eFreePos1, Acts::eFreePos2, Acts::eFreeQOverP, Acts::eFreeTime, Acts::detail::freeToCurvilinearJacobian(), ActsTests::PropagationDatasets::phi, Acts::VectorHelpers::phi(), ActsTests::PropagationDatasets::theta, and Acts::VectorHelpers::theta().
Acts::Test::BOOST_AUTO_TEST_CASE (materialmap_creation)
Definition at line 29 of file MaterialMapUtilsTests.cpp.
View newest version in sPHENIX GitHub at line 29 of file MaterialMapUtilsTests.cpp
References CHECK_CLOSE_ABS, Acts::UnitConstants::e, Acts::Material::fromMolarDensity(), i, Acts::materialMapperRZ(), Acts::materialMapperXYZ(), and Acts::Material::parameters().
Acts::Test::BOOST_AUTO_TEST_CASE (BoundaryCheckBoxSimple)
Definition at line 29 of file BoundaryCheckTests.cpp.
View newest version in sPHENIX GitHub at line 29 of file BoundaryCheckTests.cpp
References check_fpe_masks::check(), and Acts::BoundaryCheck::isInside().
Acts::Test::BOOST_AUTO_TEST_CASE (DiscTrapezoidBoundsConstruction)
Unit tests for DiscTrapezoidBounds constrcuctors.
Test construction with dimensions and default stereo
Test construction with all dimensions
Copy constructor
Definition at line 30 of file DiscTrapezoidBoundsTests.cpp.
View newest version in sPHENIX GitHub at line 30 of file DiscTrapezoidBoundsTests.cpp
References Acts::SurfaceBounds::eDiscTrapezoid, Acts::type, and Acts::DiscTrapezoidBounds::type().
Acts::Test::BOOST_AUTO_TEST_CASE (RadialBoundsConstruction)
Unit tests for RadialBounds constrcuctors.
Test construction with radii and default sector
Test construction with radii and sector half angle
Copy constructor
Definition at line 30 of file RadialBoundsTests.cpp.
View newest version in sPHENIX GitHub at line 30 of file RadialBoundsTests.cpp
References Acts::SurfaceBounds::eDisc, maxRadius, minRadius, and Acts::type.
Acts::Test::BOOST_AUTO_TEST_CASE (Visualization3DTesterObj)
Definition at line 30 of file Visualization3DTests.cpp.
View newest version in sPHENIX GitHub at line 30 of file Visualization3DTests.cpp
References testObjString().
Acts::Test::BOOST_AUTO_TEST_CASE (AuctioneerTest_FirstValidAuctioneer)
Definition at line 30 of file AuctioneerTests.cpp.
View newest version in sPHENIX GitHub at line 30 of file AuctioneerTests.cpp
Acts::Test::BOOST_AUTO_TEST_CASE (BinAdjustment_Radial)
Definition at line 30 of file BinAdjustmentTests.cpp.
View newest version in sPHENIX GitHub at line 30 of file BinAdjustmentTests.cpp
References Acts::adjustBinUtility(), Acts::BinUtility::binningData(), Acts::binPhi, Acts::binR, Acts::closed, and Acts::open.
Acts::Test::BOOST_AUTO_TEST_CASE (VolumeTest)
Definition at line 30 of file VolumeTests.cpp.
View newest version in sPHENIX GitHub at line 30 of file VolumeTests.cpp
References bounds, Acts::Volume::center(), CHECK_CLOSE_ABS, eps, Acts::Volume::inside(), Acts::Volume::itransform(), Acts::Volume::transform(), transform, translation(), and Acts::Volume::volumeBounds().
Acts::Test::BOOST_AUTO_TEST_CASE (CylinderBoundsConstruction)
Unit test for creating compliant/non-compliant CylinderBounds object.
test default construction
test copy construction;
Definition at line 31 of file CylinderBoundsTests.cpp.
View newest version in sPHENIX GitHub at line 31 of file CylinderBoundsTests.cpp
References Acts::SurfaceBounds::eCylinder, and Acts::type.
Acts::Test::BOOST_AUTO_TEST_CASE (TestSolenoidBField)
Definition at line 31 of file SolenoidBFieldTests.cpp.
View newest version in sPHENIX GitHub at line 31 of file SolenoidBFieldTests.cpp
References Acts::IntegrationTest::bField, cfg, CHECK_CLOSE_ABS, Acts::SolenoidBField::getField(), Acts::SolenoidBField::makeCache(), and Acts::IntegrationTest::mfContext.
Acts::Test::BOOST_AUTO_TEST_CASE (EllipseBoundsConstruction)
Unit test for creating compliant/non-compliant EllipseBounds object.
Test construction with dimensions
Copy constructor
Definition at line 31 of file EllipseBoundsTests.cpp.
View newest version in sPHENIX GitHub at line 31 of file EllipseBoundsTests.cpp
References Acts::SurfaceBounds::eEllipse, and Acts::type.
Acts::Test::BOOST_AUTO_TEST_CASE (InfiniteBoundsProperties)
Unit tests for InfiniteBounds properties.
test for type()
test for inside()
test for dump
Definition at line 32 of file InfiniteBoundsTests.cpp.
View newest version in sPHENIX GitHub at line 32 of file InfiniteBoundsTests.cpp
References Acts::SurfaceBounds::eBoundless, Acts::InfiniteBounds::inside(), Acts::InfiniteBounds::toStream(), and Acts::InfiniteBounds::type().
Acts::Test::BOOST_AUTO_TEST_CASE (IntersectionTest)
test of the intersection class
let's make a bunch of negative solution
Definition at line 32 of file IntersectionTests.cpp.
View newest version in sPHENIX GitHub at line 32 of file IntersectionTests.cpp
References Acts::Intersection< 3 >::forwardOrder(), ActsTests::PropagationDatasets::pathLength, and Acts::Experimental::detail::BlueprintHelper::sort().
Acts::Test::BOOST_AUTO_TEST_CASE (CutoutCylinderVolumeBoundsConstruction)
Definition at line 33 of file CutoutCylinderVolumeBoundsTests.cpp.
View newest version in sPHENIX GitHub at line 33 of file CutoutCylinderVolumeBoundsTests.cpp
References Acts::CutoutCylinderVolumeBounds::toStream().
Acts::Test::BOOST_AUTO_TEST_CASE (mutate_ranges_double)
Definition at line 33 of file RangeXDTests.cpp.
View newest version in sPHENIX GitHub at line 33 of file RangeXDTests.cpp
References Acts::UnitConstants::min, and physmon_track_finding_ttbar::r.
Acts::Test::BOOST_AUTO_TEST_CASE (PerigeeSurfaceConstruction)
Unit test for creating compliant/non-compliant PerigeeSurface object.
Constructor with Vector3
Constructor with transform
Copy constructor
Copied and transformed
Definition at line 33 of file PerigeeSurfaceTests.cpp.
View newest version in sPHENIX GitHub at line 33 of file PerigeeSurfaceTests.cpp
References Acts::Surface::Perigee, tgContext, translation(), and Acts::type.
Acts::Test::BOOST_AUTO_TEST_CASE (ExtentTest)
Unit tests for Polyderon construction & operator +=.
Definition at line 33 of file ExtentTests.cpp.
View newest version in sPHENIX GitHub at line 33 of file ExtentTests.cpp
References Acts::Extent::addConstrain(), Acts::binPhi, Acts::binR, Acts::binX, Acts::binY, Acts::binZ, CHECK_CLOSE_ABS, Acts::Extent::constrains(), Acts::UnitConstants::e, Acts::Extent::extend(), Acts::Extent::max(), Acts::Extent::min(), phiMin, Acts::Extent::set(), physmon_ckf_tracking::u, testSigmaEff::v, ActsExamples::HepMC3Event::vertices(), and Acts::zeroEnvelopes.
Acts::Test::BOOST_AUTO_TEST_CASE (grid_test_1d_equidistant)
Definition at line 33 of file GridTests.cpp.
View newest version in sPHENIX GitHub at line 33 of file GridTests.cpp
References KFPMath::a, Acts::UnitConstants::g, Acts::detail::Grid< T, Axes >::globalBinFromLocalBins(), Acts::detail::Grid< T, Axes >::globalBinFromPosition(), Acts::detail::Grid< T, Axes >::localBinsFromGlobalBin(), std::tr1::make_tuple(), testing::internal::move(), Acts::detail::Grid< T, Axes >::numLocalBins(), Acts::detail::Grid< T, Axes >::size(), and physmon_ckf_tracking::u.
Acts::Test::BOOST_AUTO_TEST_CASE (PlaneSurfaceMatcher)
Definition at line 33 of file SurfaceBinningMatcherTests.cpp.
View newest version in sPHENIX GitHub at line 33 of file SurfaceBinningMatcherTests.cpp
References Acts::binPhi, Acts::binR, Acts::binValues, add_histos_bX::ib, Acts::PrimitivesView3DTest::identity, tgContext, and Acts::SurfaceBinningMatcher::tolerances.
Acts::Test::BOOST_AUTO_TEST_CASE (single_material)
Definition at line 34 of file AccumulatedVolumeMaterialTests.cpp.
View newest version in sPHENIX GitHub at line 34 of file AccumulatedVolumeMaterialTests.cpp
References Acts::AccumulatedVolumeMaterial::accumulate(), Acts::Material::Ar(), Acts::AccumulatedVolumeMaterial::average(), CHECK_CLOSE_REL, Acts::UnitConstants::e, Acts::Material::fromMolarDensity(), Acts::Material::L0(), Acts::Material::massDensity(), Acts::Material::molarDensity(), Acts::Material::parameters(), Acts::Material::X0(), and Acts::Material::Z().
Acts::Test::BOOST_AUTO_TEST_CASE (covariance_transport_bound_start)
Definition at line 34 of file CovarianceTransportTests.cpp.
View newest version in sPHENIX GitHub at line 34 of file CovarianceTransportTests.cpp
References Acts::CovarianceCache::applyTransport, Acts::CovarianceCache::atPosition, Acts::CovarianceCache::atSurface, Acts::CovarianceCache::boundToFreeJacobian, Acts::CovarianceCache::covariance, Acts::CovarianceCache::freeToPathDerivatives, Acts::CovarianceCache::freeTransportJacobian, Acts::VectorHelpers::phi(), position, tgContext, Acts::VectorHelpers::theta(), time, Acts::transportCovarianceToBound(), Acts::transportCovarianceToCurvilinear(), and Acts::transportCovarianceToFree().
Acts::Test::BOOST_AUTO_TEST_CASE (assume_read)
Definition at line 35 of file BenchmarkTools.cpp.
View newest version in sPHENIX GitHub at line 35 of file BenchmarkTools.cpp
References assumeRead(), f, std::tr1::make_tuple(), ambiguity_solver_full_chain::x, and y.
Acts::Test::BOOST_AUTO_TEST_CASE (TrapezoidBoundsConstruction)
Unit test for creating compliant/non-compliant TrapezoidBounds object.
Test construction with defining half lengths
Copy constructor
Definition at line 35 of file TrapezoidBoundsTests.cpp.
View newest version in sPHENIX GitHub at line 35 of file TrapezoidBoundsTests.cpp
References Acts::SurfaceBounds::eTrapezoid, halfY, and Acts::type.
Acts::Test::BOOST_AUTO_TEST_CASE (ConeVolumeBoundsTests)
Definition at line 35 of file ConeVolumeBoundsTests.cpp.
View newest version in sPHENIX GitHub at line 35 of file ConeVolumeBoundsTests.cpp
References Acts::ConeVolumeBounds::eAveragePhi, Acts::ConeVolumeBounds::eHalfLengthZ, Acts::ConeVolumeBounds::eHalfPhiSector, Acts::ConeVolumeBounds::eInnerAlpha, Acts::ConeVolumeBounds::eInnerOffsetZ, Acts::ConeVolumeBounds::eOuterAlpha, Acts::ConeVolumeBounds::eOuterOffsetZ, Acts::ConeVolumeBounds::get(), Acts::ConeVolumeBounds::innerRmax(), Acts::ConeVolumeBounds::innerRmin(), Acts::ConeVolumeBounds::innerTanAlpha(), Acts::ConeVolumeBounds::orientedSurfaces(), Acts::ConeVolumeBounds::outerRmax(), Acts::ConeVolumeBounds::outerRmin(), and Acts::ConeVolumeBounds::outerTanAlpha().
Acts::Test::BOOST_AUTO_TEST_CASE (infinite_range_double)
Definition at line 35 of file Range1DTests.cpp.
View newest version in sPHENIX GitHub at line 35 of file Range1DTests.cpp
References Acts::Range1D< Type >::max(), Acts::Range1D< Type >::min(), and physmon_track_finding_ttbar::r.
Acts::Test::BOOST_AUTO_TEST_CASE (ConvexPolygonBoundsConvexity)
Definition at line 36 of file ConvexPolygonBoundsTests.cpp.
View newest version in sPHENIX GitHub at line 36 of file ConvexPolygonBoundsTests.cpp
References ActsExamples::HepMC3Event::vertices().
Acts::Test::BOOST_AUTO_TEST_CASE (Visualization3DHelpers)
The tests in this section are regression tests only in order to catch any unexpected changes in the output format.
Definition at line 36 of file PrimitivesView3DTests.cpp.
View newest version in sPHENIX GitHub at line 36 of file PrimitivesView3DTests.cpp
References CHECK_CLOSE_ABS, covariance(), and Acts::EventDataView3D::decomposeCovariance().
Acts::Test::BOOST_AUTO_TEST_CASE (bfield_creation)
Definition at line 36 of file BFieldMapUtilsTests.cpp.
View newest version in sPHENIX GitHub at line 36 of file BFieldMapUtilsTests.cpp
References CHECK_CLOSE_ABS, Acts::UnitConstants::e, Acts::fieldMapRZ(), Acts::fieldMapXYZ(), i, and Acts::VectorHelpers::perp().
Acts::Test::BOOST_AUTO_TEST_CASE (PolyhedronTest)
Unit tests for Polyderon construction & operator +=.
Definition at line 36 of file PolyhedronTests.cpp.
View newest version in sPHENIX GitHub at line 36 of file PolyhedronTests.cpp
References Acts::ObjVisualization3D< T >::clear(), Acts::GeometryView3D::drawPolyhedron(), Acts::Polyhedron::faces, Acts::Polyhedron::merge(), Acts::PrimitivesView3DTest::rectangle, Acts::Polyhedron::triangularMesh, Acts::Polyhedron::vertices, and Acts::ObjVisualization3D< T >::write().
Acts::Test::BOOST_AUTO_TEST_CASE (CuboidVolumeConstruction)
Definition at line 37 of file CuboidVolumeBoundsTests.cpp.
View newest version in sPHENIX GitHub at line 37 of file CuboidVolumeBoundsTests.cpp
References hx, hy, and hz.
Acts::Test::BOOST_AUTO_TEST_CASE (BoundTrackParametersVisualizationPly)
Definition at line 37 of file EventDataView3DTests.cpp.
View newest version in sPHENIX GitHub at line 37 of file EventDataView3DTests.cpp
References test_fpe::count, Acts::EventDataView3DTest::testBoundTrackParameters(), and testPlyString().
Acts::Test::BOOST_AUTO_TEST_CASE (GeometryIdentifier_max_values)
Definition at line 37 of file GeometryIdentifierTests.cpp.
View newest version in sPHENIX GitHub at line 37 of file GeometryIdentifierTests.cpp
References check_smearing_config::ref, and physmon_ckf_tracking::u.
Acts::Test::BOOST_AUTO_TEST_CASE (covariance_engine_test)
These tests do not test for a correct covariance transport but only for the correct conservation or modification of certain variables. A test suite for the numerical correctness is performed in the integration tests.
Definition at line 38 of file CovarianceEngineTests.cpp.
View newest version in sPHENIX GitHub at line 38 of file CovarianceEngineTests.cpp
References Acts::FreeToBoundCorrection::apply, Acts::detail::boundState(), covariance(), Acts::detail::curvilinearState(), Dataset::parameters, particleHypothesis, Acts::ParticleHypothesis::pion(), position, writeMapConfig::surface, tgContext, time, Acts::detail::transportCovarianceToBound(), and Acts::detail::transportCovarianceToCurvilinear().
Acts::Test::BOOST_AUTO_TEST_CASE (construction_test)
Definition at line 38 of file GenericCuboidVolumeBoundsTests.cpp.
View newest version in sPHENIX GitHub at line 38 of file GenericCuboidVolumeBoundsTests.cpp
References Acts::GenericCuboidVolumeBounds::inside(), and ActsExamples::HepMC3Event::vertices().
Acts::Test::BOOST_AUTO_TEST_CASE (bitset_to_matrix_to_bitset)
Definition at line 38 of file HelpersTests.cpp.
View newest version in sPHENIX GitHub at line 38 of file HelpersTests.cpp
References Acts::matrixToBitset().
Acts::Test::BOOST_AUTO_TEST_CASE (AnnulusBoundsConstruction)
Definition at line 38 of file AnnulusBoundsTests.cpp.
View newest version in sPHENIX GitHub at line 38 of file AnnulusBoundsTests.cpp
Acts::Test::BOOST_AUTO_TEST_CASE (RealQuadraticEquationProperties)
Unit test for RealQuadraticEquation properties.
Test construction with parameters
Test for solutions
Definition at line 39 of file RealQuadraticEquationTests.cpp.
View newest version in sPHENIX GitHub at line 39 of file RealQuadraticEquationTests.cpp
References KFPMath::a, KFPMath::b, Acts::PhysicalConstants::c, CHECK_CLOSE_REL, Acts::UnitConstants::e, Acts::detail::RealQuadraticEquation::first, Acts::detail::RealQuadraticEquation::second, and Acts::detail::RealQuadraticEquation::solutions.
Acts::Test::BOOST_AUTO_TEST_CASE (LineBoundsRecreation)
Unit test for testing LineBounds recreation from streaming.
Definition at line 39 of file LineBoundsTests.cpp.
View newest version in sPHENIX GitHub at line 39 of file LineBoundsTests.cpp
References Acts::LineBounds::eSize, Acts::LineBounds::values(), and values.
Acts::Test::BOOST_AUTO_TEST_CASE (construct_with_fractions)
Definition at line 39 of file MaterialCompositionTests.cpp.
View newest version in sPHENIX GitHub at line 39 of file MaterialCompositionTests.cpp
References CHECK_CLOSE_REL, eps, f, and physmon_ckf_tracking::u.
Acts::Test::BOOST_AUTO_TEST_CASE (BoundaryCheckBoxToleranceLoc0)
Definition at line 39 of file BoundaryCheckTests.cpp.
View newest version in sPHENIX GitHub at line 39 of file BoundaryCheckTests.cpp
References check_fpe_masks::check(), and Acts::BoundaryCheck::isInside().
Acts::Test::BOOST_AUTO_TEST_CASE (ConeBoundsConstruction)
Unit test for creating compliant/non-compliant ConeBounds object.
Definition at line 40 of file ConeBoundsTests.cpp.
View newest version in sPHENIX GitHub at line 40 of file ConeBoundsTests.cpp
References alpha, Acts::SurfaceBounds::eCone, and Acts::ConeBounds::type().
Acts::Test::BOOST_AUTO_TEST_CASE (StrawSurfaceConstruction)
Unit test for creating compliant/non-compliant StrawSurface object.
Constructor with transform, radius and halfZ
Constructor with transform and LineBounds pointer
Constructor with LineBounds ptr, DetectorElement
Copy constructor
Copied and transformed
Definition at line 40 of file StrawSurfaceTests.cpp.
View newest version in sPHENIX GitHub at line 40 of file StrawSurfaceTests.cpp
References merge_hashes::p, Acts::Surface::Straw, tgContext, translation(), and Acts::type.
Acts::Test::BOOST_AUTO_TEST_CASE (CylinderVolumeBoundsConstruction)
Definition at line 41 of file CylinderVolumeBoundsTests.cpp.
View newest version in sPHENIX GitHub at line 41 of file CylinderVolumeBoundsTests.cpp
References Acts::CylinderVolumeBounds::orientedSurfaces(), and rBounds.
Acts::Test::BOOST_AUTO_TEST_CASE (gaussian_grid_density_test)
Definition at line 41 of file GaussianGridTrackDensityTests.cpp.
View newest version in sPHENIX GitHub at line 41 of file GaussianGridTrackDensityTests.cpp
References cfg, filter::Config, grid(), and Acts::ParticleHypothesis::pion().
Acts::Test::BOOST_AUTO_TEST_CASE (SimpleGeometryTest)
Unit test for a three layer detector parameters Testing the Tool chain in the geometry building process.
Definition at line 41 of file SimpleGeometryTests.cpp.
View newest version in sPHENIX GitHub at line 41 of file SimpleGeometryTests.cpp
References Acts::getDefaultLogger(), Acts::Logging::INFO, Acts::CylinderVolumeHelper::Config::layerArrayCreator, Acts::PassiveLayerBuilder::Config::layerIdentification, Acts::LayerCreator::Config::surfaceArrayCreator, Acts::tgContext, Acts::tGeometry, Acts::TrackingGeometryBuilder::trackingGeometry(), Acts::TrackingGeometryBuilder::Config::trackingVolumeBuilders, and Acts::CylinderVolumeBuilder::Config::trackingVolumeHelper.
Acts::Test::BOOST_AUTO_TEST_CASE (TypeTraitsMethods)
Definition at line 42 of file TypeTraitsTest.cpp.
View newest version in sPHENIX GitHub at line 42 of file TypeTraitsTest.cpp
Acts::Test::BOOST_AUTO_TEST_CASE (AuctioneerTest_HighestValidAuctioneer)
Definition at line 42 of file AuctioneerTests.cpp.
View newest version in sPHENIX GitHub at line 42 of file AuctioneerTests.cpp
Acts::Test::BOOST_AUTO_TEST_CASE (interpolation_2d)
Definition at line 42 of file InterpolationTests.cpp.
View newest version in sPHENIX GitHub at line 42 of file InterpolationTests.cpp
References CHECK_CLOSE_REL, Acts::UnitConstants::e, Acts::interpolate(), and testSigmaEff::v.
Acts::Test::BOOST_AUTO_TEST_CASE (constructor_range_int)
Definition at line 42 of file Range1DTests.cpp.
View newest version in sPHENIX GitHub at line 42 of file Range1DTests.cpp
References Acts::Range1D< Type >::max(), Acts::Range1D< Type >::min(), and physmon_track_finding_ttbar::r.
Acts::Test::BOOST_AUTO_TEST_CASE (InterpolatedMaterialMap_MaterialCell_test)
Definition at line 43 of file InterpolatedMaterialMapTests.cpp.
View newest version in sPHENIX GitHub at line 43 of file InterpolatedMaterialMapTests.cpp
References CHECK_CLOSE_REL, Acts::MaterialMapper< G >::MaterialCell::getMaterial(), Acts::MaterialMapper< G >::MaterialCell::isInside(), and trafoGlobalToLocal().
Acts::Test::BOOST_AUTO_TEST_CASE (TGeoParser_Pixel)
Unit test Parsing a TGeo geometry.
Convert into surfaces using the TGeoSurfaceConverter & Draw them
Definition at line 44 of file TGeoParserTests.cpp.
View newest version in sPHENIX GitHub at line 44 of file TGeoParserTests.cpp
References Acts::GeometryView3D::drawSurface(), Acts::TGeoParser::select(), Acts::TGeoParser::State::selectedNodes, shape(), writeMapConfig::surface, Acts::TGeoParser::Options::targetNames, tgContext, thickness, Acts::TGeoSurfaceConverter::toSurface(), transform, physmon_ckf_tracking::u, Acts::TGeoParser::State::volume, and Acts::TGeoParser::Options::volumeNames.
Acts::Test::BOOST_AUTO_TEST_CASE (ConeSurfaceConstruction)
Unit test for creating compliant/non-compliant ConeSurface object.
Constructor with transform, alpha and symmetry indicator
Constructor with transform pointer, alpha,z min and max, halfPhiSector
Constructor with transform and ConeBounds pointer
Copy constructor
Copied and transformed
Construct with nullptr bounds
Definition at line 45 of file ConeSurfaceTests.cpp.
View newest version in sPHENIX GitHub at line 45 of file ConeSurfaceTests.cpp
References alpha, Acts::Surface::Cone, tgContext, translation(), and Acts::type.
Acts::Test::BOOST_AUTO_TEST_CASE (InterpolatedBFieldMap_rz)
Definition at line 45 of file InterpolatedBFieldMapTests.cpp.
View newest version in sPHENIX GitHub at line 45 of file InterpolatedBFieldMapTests.cpp
References KFPMath::b, Acts::IntegrationTest::bCache, check_fpe_masks::check(), ckf::field, Acts::UnitConstants::g, i, j, std::tr1::make_tuple(), mfContext, testing::internal::move(), Acts::VectorHelpers::perp(), pos, physmon_track_finding_ttbar::r, physmon_ckf_tracking::u, value, and physmon_track_finding_ttbar::z.
Acts::Test::BOOST_AUTO_TEST_CASE (BinAdjustment_Cylinder)
Definition at line 45 of file BinAdjustmentTests.cpp.
View newest version in sPHENIX GitHub at line 45 of file BinAdjustmentTests.cpp
References Acts::adjustBinUtility(), Acts::BinUtility::binningData(), Acts::binPhi, Acts::binZ, and Acts::open.
Acts::Test::BOOST_AUTO_TEST_CASE (KDTreeTrackingGeometryBuilder_simple)
Definition at line 45 of file KDTreeTrackingGeometryBuilderTests.cpp.
View newest version in sPHENIX GitHub at line 45 of file KDTreeTrackingGeometryBuilderTests.cpp
References Acts::binR, Acts::binZ, filter::Config, Acts::ProtoVolume::container, Acts::ProtoVolume::extent, Acts::getDefaultLogger(), Acts::Surface::getSharedPtr(), Acts::ProtoVolume::internal, Acts::CylinderVolumeHelper::Config::layerArrayCreator, Acts::KDTreeTrackingGeometryBuilder::Config::layerCreator, telescope_simulation::logLevel, Acts::ProtoVolume::name, Acts::open, Acts::Extent::set(), Acts::LayerCreator::Config::surfaceArrayCreator, Acts::Test::CylindricalTrackingGeometry::surfacesCylinder(), Acts::Test::CylindricalTrackingGeometry::surfacesRing(), tContext, Acts::trackingGeometry(), and Acts::Logging::VERBOSE.
Acts::Test::BOOST_AUTO_TEST_CASE (TestConstruction)
Definition at line 46 of file ResultTests.cpp.
View newest version in sPHENIX GitHub at line 46 of file ResultTests.cpp
Acts::Test::BOOST_AUTO_TEST_CASE (CutoutCylinderVolumeBoundsRecreation)
Definition at line 46 of file CutoutCylinderVolumeBoundsTests.cpp.
View newest version in sPHENIX GitHub at line 46 of file CutoutCylinderVolumeBoundsTests.cpp
References Acts::CutoutCylinderVolumeBounds::eSize, values, and Acts::CutoutCylinderVolumeBounds::values().
Acts::Test::BOOST_AUTO_TEST_CASE (Square_Grid_test)
Various test for the Material in the case of a Cuboid volume and 2D Grid.
Definition at line 46 of file MaterialGridHelperTests.cpp.
View newest version in sPHENIX GitHub at line 46 of file MaterialGridHelperTests.cpp
References Acts::detail::Grid< T, Axes >::atLocalBins(), Acts::BinUtility::binningData(), Acts::binX, Acts::binY, CHECK_CLOSE_REL, Acts::createGrid2D(), Acts::detail::Grid< T, Axes >::dimensions(), Acts::UnitConstants::e, Acts::Material::fromMolarDensity(), i, index, Acts::index1, Acts::index2, Acts::index3, Acts::detail::Grid< T, Axes >::localBinsFromLowerLeftEdge(), Acts::mapMaterialPoints(), Acts::detail::Grid< T, Axes >::maxPosition(), Acts::UnitConstants::min, Acts::detail::Grid< T, Axes >::minPosition(), Acts::detail::Grid< T, Axes >::numLocalBins(), Acts::open, Acts::Material::parameters(), and pos.
Acts::Test::BOOST_AUTO_TEST_CASE (cartesian_segmentation)
Unit test for the Cartesian segmentation.
Definition at line 46 of file CartesianSegmentationTests.cpp.
View newest version in sPHENIX GitHub at line 46 of file CartesianSegmentationTests.cpp
References CHECK_CLOSE_OR_SMALL, CHECK_CLOSE_REL, Acts::CartesianSegmentation::createSegmentationSurfaces(), cSegmentation, Acts::UnitConstants::e, hThickness, lAngle, nbinsx, nbinsy, Acts::tgContext, physmon_ckf_tracking::u, and physmon_track_finding_ttbar::z.
Acts::Test::BOOST_AUTO_TEST_CASE (all_of_test)
Definition at line 46 of file MPLTests.cpp.
View newest version in sPHENIX GitHub at line 46 of file MPLTests.cpp
References Acts::detail::all_of_v.
Acts::Test::BOOST_AUTO_TEST_CASE (AnnulusBoundsRecreation)
Definition at line 46 of file AnnulusBoundsTests.cpp.
View newest version in sPHENIX GitHub at line 46 of file AnnulusBoundsTests.cpp
References Acts::AnnulusBounds::eSize, maxPhi, maxRadius, minPhi, minRadius, offset(), and values.
Acts::Test::BOOST_AUTO_TEST_CASE (assume_written)
Definition at line 47 of file BenchmarkTools.cpp.
View newest version in sPHENIX GitHub at line 47 of file BenchmarkTools.cpp
References assumeWritten(), and Acts::PhysicalConstants::c.
Acts::Test::BOOST_AUTO_TEST_CASE (HomogeneousVolumeMaterial_access_test)
Definition at line 47 of file HomogeneousVolumeMaterialTests.cpp.
View newest version in sPHENIX GitHub at line 47 of file HomogeneousVolumeMaterialTests.cpp
References Acts::Material::fromMolarDensity(), and Acts::HomogeneousVolumeMaterial::material().
Acts::Test::BOOST_AUTO_TEST_CASE (RectangleBoundsConstruction)
Unit test for creating compliant/non-compliant RectangleBounds object.
Definition at line 47 of file RectangleBoundsTests.cpp.
View newest version in sPHENIX GitHub at line 47 of file RectangleBoundsTests.cpp
References Acts::SurfaceBounds::eRectangle, halfX, halfY, inf, and Acts::RectangleBounds::type().
Acts::Test::BOOST_AUTO_TEST_CASE (BinAdjustmentVolume_CutoutCylinder)
Definition at line 47 of file BinAdjustmentVolumeTests.cpp.
View newest version in sPHENIX GitHub at line 47 of file BinAdjustmentVolumeTests.cpp
References Acts::adjustBinUtility(), Acts::BinUtility::binningData(), Acts::binPhi, Acts::binR, Acts::binZ, Acts::closed, and Acts::open.
Acts::Test::BOOST_AUTO_TEST_CASE (degenerate_double)
Definition at line 48 of file RangeXDTests.cpp.
View newest version in sPHENIX GitHub at line 48 of file RangeXDTests.cpp
References Acts::RangeXD< Dims, Type, Vector >::degenerate(), and physmon_track_finding_ttbar::r.
Acts::Test::BOOST_AUTO_TEST_CASE (MeasurementVisualizationObj)
Definition at line 48 of file EventDataView3DTests.cpp.
View newest version in sPHENIX GitHub at line 48 of file EventDataView3DTests.cpp
References test_fpe::count, Acts::EventDataView3DTest::testMeasurement(), and testObjString().
Acts::Test::BOOST_AUTO_TEST_CASE (CylinderIntersectionTests)
This tests the intersection with cylinders and looks for valid, non-valid, solutions
Definition at line 48 of file SurfaceIntersectionTests.cpp.
View newest version in sPHENIX GitHub at line 48 of file SurfaceIntersectionTests.cpp
References aCylinder, Acts::aTransform, CHECK_CLOSE_ABS, ActsTests::PropagationDatasets::pathLength, Acts::s_onSurfaceTolerance, utils::status, Acts::tgContext, and transform.
Acts::Test::BOOST_AUTO_TEST_CASE (PlaneSurfaceConstruction)
Unit test for creating compliant/non-compliant PlaneSurface object.
Constructor with transform and bounds
Copy constructor
Copied and transformed
Construct with nullptr bounds
Definition at line 49 of file PlaneSurfaceTests.cpp.
View newest version in sPHENIX GitHub at line 49 of file PlaneSurfaceTests.cpp
References Acts::Surface::Plane, rBounds, tgContext, translation(), and Acts::type.
Acts::Test::BOOST_AUTO_TEST_CASE (constructor_range_double)
Definition at line 49 of file Range1DTests.cpp.
View newest version in sPHENIX GitHub at line 49 of file Range1DTests.cpp
References Acts::Range1D< Type >::max(), Acts::Range1D< Type >::min(), and physmon_track_finding_ttbar::r.
Acts::Test::BOOST_AUTO_TEST_CASE (CuboidVolumeRecreation)
Definition at line 50 of file CuboidVolumeBoundsTests.cpp.
View newest version in sPHENIX GitHub at line 50 of file CuboidVolumeBoundsTests.cpp
References Acts::CuboidVolumeBounds::eSize, hx, hy, hz, values, and Acts::CuboidVolumeBounds::values().
Acts::Test::BOOST_AUTO_TEST_CASE (RadialBoundsRecreation)
Definition at line 50 of file RadialBoundsTests.cpp.
View newest version in sPHENIX GitHub at line 50 of file RadialBoundsTests.cpp
References Acts::RadialBounds::eSize, maxRadius, minRadius, values, and Acts::RadialBounds::values().
Acts::Test::BOOST_AUTO_TEST_CASE (BoundaryCheckBoxDistance)
Definition at line 50 of file BoundaryCheckTests.cpp.
View newest version in sPHENIX GitHub at line 50 of file BoundaryCheckTests.cpp
References CHECK_CLOSE_REL, distance(), Acts::BoundaryCheck::distance(), Acts::UnitConstants::e, i, rectDimensions, rectDistances, rectShiftedDimensions, rectShiftedDistances, rectShiftedTestPoints, and rectTestPoints.
Acts::Test::BOOST_AUTO_TEST_CASE (compare_to_analytical_solution_for_single_track)
Definition at line 51 of file AdaptiveGridTrackDensityTests.cpp.
View newest version in sPHENIX GitHub at line 51 of file AdaptiveGridTrackDensityTests.cpp
References Acts::AdaptiveGridTrackDensity< spatialTrkGridSize, temporalTrkGridSize >::addTrack(), check_smearing_config::args, cfg, CHECK_CLOSE_OR_SMALL, CHECK_CLOSE_REL, Acts::UnitConstants::e, Acts::AdaptiveGridTrackDensity< spatialTrkGridSize, temporalTrkGridSize >::getBinCenter(), Acts::AdaptiveGridTrackDensity< spatialTrkGridSize, temporalTrkGridSize >::getMaxZTPositionAndWidth(), grid(), it, makeRandomCovariance(), maxZ, Acts::ParticleHypothesis::pion(), and small.
Acts::Test::BOOST_AUTO_TEST_CASE (ISurfaceMaterial_factor_test)
Test the constructors.
Definition at line 51 of file ISurfaceMaterialTests.cpp.
View newest version in sPHENIX GitHub at line 51 of file ISurfaceMaterialTests.cpp
References Acts::Direction::Backward, and Acts::Direction::Forward.
Acts::Test::BOOST_AUTO_TEST_CASE (LineBoundsExceptions)
Unit test for testing LineBounds exceptions.
Definition at line 51 of file LineBoundsTests.cpp.
View newest version in sPHENIX GitHub at line 51 of file LineBoundsTests.cpp
Acts::Test::BOOST_AUTO_TEST_CASE (TrapezoidBoundsRecreated)
Unit test for creating compliant/non-compliant TrapezoidBounds object.
Copy constructor
Definition at line 51 of file TrapezoidBoundsTests.cpp.
View newest version in sPHENIX GitHub at line 51 of file TrapezoidBoundsTests.cpp
References Acts::TrapezoidBounds::eSize, halfY, values, and Acts::TrapezoidBounds::values().
Acts::Test::BOOST_AUTO_TEST_CASE (RealQuadraticEquationAssignment)
Unit test for testing RealQuadraticEquation assignment.
Test assignment (implicit)
equality not written and not implicit
Definition at line 52 of file RealQuadraticEquationTests.cpp.
View newest version in sPHENIX GitHub at line 52 of file RealQuadraticEquationTests.cpp
References KFPMath::a, KFPMath::b, Acts::PhysicalConstants::c, CHECK_CLOSE_REL, Acts::UnitConstants::e, Acts::detail::RealQuadraticEquation::first, Acts::detail::RealQuadraticEquation::second, and Acts::detail::RealQuadraticEquation::solutions.
Acts::Test::BOOST_AUTO_TEST_CASE (HomogeneousSurfaceMaterial_scaling_test)
Definition at line 52 of file HomogeneousSurfaceMaterialTests.cpp.
View newest version in sPHENIX GitHub at line 52 of file HomogeneousSurfaceMaterialTests.cpp
References Acts::Material::fromMolarDensity(), Acts::HomogeneousSurfaceMaterial::materialSlab(), and Acts::MaterialSlab::scaleThickness().
Acts::Test::BOOST_AUTO_TEST_CASE (DiscTrapezoidBoundsRecreation)
Definition at line 52 of file DiscTrapezoidBoundsTests.cpp.
View newest version in sPHENIX GitHub at line 52 of file DiscTrapezoidBoundsTests.cpp
References Acts::DiscTrapezoidBounds::eSize, values, and Acts::DiscTrapezoidBounds::values().
Acts::Test::BOOST_AUTO_TEST_CASE (EllipseBoundsRecreation)
Definition at line 52 of file EllipseBoundsTests.cpp.
View newest version in sPHENIX GitHub at line 52 of file EllipseBoundsTests.cpp
References Acts::EllipseBounds::eSize, values, and Acts::EllipseBounds::values().
Acts::Test::BOOST_AUTO_TEST_CASE (Invalid) static
Definition at line 52 of file FpeMonitorTests.cpp.
View newest version in sPHENIX GitHub at line 52 of file FpeMonitorTests.cpp
References Acts::FpeMonitor::Result::encountered(), and Acts::FpeMonitor::result().
Acts::Test::BOOST_AUTO_TEST_CASE (TGeoArb8_to_PlaneSurface)
Unit test to convert a TGeoTrd2 into a Plane.
The TGeoTrd2 has x/z orientation
Definition at line 52 of file TGeoArb8ConversionTests.cpp.
View newest version in sPHENIX GitHub at line 52 of file TGeoArb8ConversionTests.cpp
References allowedAxes, blue, bounds, Acts::ObjVisualization3D< T >::clear(), Acts::GeometryView3D::drawArrowForward(), Acts::GeometryView3D::drawSurface(), green, Acts::PrimitivesView3DTest::plane, Acts::Surface::Plane, red, tgContext, thickness, to_string(), Acts::TGeoSurfaceConverter::toSurface(), transform, and Acts::ObjVisualization3D< T >::write().
Acts::Test::BOOST_AUTO_TEST_CASE (DiamondBoundsProperties)
Unit tests for DiamondBounds properties.
Test clone
Test type() (redundant; already used in constructor confirmation)
Test the half length at negative y
Test the half length at the x axis
Test the half length at positive y
Test half length into the negative side
Test half length into the positive side
Test boundingBox
Test distanceToBoundary
Test dump
Test inside
Test vertices (does this need to be implemented in this class??
Definition at line 53 of file DiamondBoundsTests.cpp.
View newest version in sPHENIX GitHub at line 53 of file DiamondBoundsTests.cpp
References Acts::DiamondBounds::boundingBox(), Acts::SurfaceBounds::eDiamond, Acts::DiamondBounds::eHalfLengthXnegY, Acts::DiamondBounds::eHalfLengthXposY, Acts::DiamondBounds::eHalfLengthXzeroY, Acts::DiamondBounds::eHalfLengthYneg, Acts::DiamondBounds::eHalfLengthYpos, Acts::DiamondBounds::get(), Acts::DiamondBounds::inside(), origin(), Acts::DiamondBounds::toStream(), Acts::DiamondBounds::type(), and Acts::DiamondBounds::vertices().
Acts::Test::BOOST_AUTO_TEST_CASE (micro_benchmark_result)
Definition at line 53 of file BenchmarkTools.cpp.
View newest version in sPHENIX GitHub at line 53 of file BenchmarkTools.cpp
References CHECK_CLOSE_REL, test_fpe::count, Acts::UnitConstants::e, Acts::Test::MicroBenchmarkResult::iters_per_run, Acts::Test::MicroBenchmarkResult::iterTimeAverage(), Acts::Test::MicroBenchmarkResult::iterTimeError(), os, Acts::Test::MicroBenchmarkResult::run_timings, Acts::Test::MicroBenchmarkResult::runTimeError(), Acts::Test::MicroBenchmarkResult::runTimeMedian(), Acts::Test::MicroBenchmarkResult::runTimeQuartiles(), Acts::Test::MicroBenchmarkResult::runTimeRobustStddev(), Acts::Test::MicroBenchmarkResult::sortedRunTimes(), and Acts::Test::MicroBenchmarkResult::totalTime().
Acts::Test::BOOST_AUTO_TEST_CASE (TGeoBBox_to_PlaneSurface)
Unit test to convert a Bbox into a Plane.
This test also tests:
the "(x/X)(y/Y)(z/Z)" orientations
the scaling functionality
Definition at line 53 of file TGeoBBoxConversionTests.cpp.
View newest version in sPHENIX GitHub at line 53 of file TGeoBBoxConversionTests.cpp
References blue, CHECK_CLOSE_ABS, Acts::GeometryView3D::drawArrowForward(), Acts::GeometryView3D::drawSurface(), Acts::RectangleBounds::eMaxX, Acts::RectangleBounds::eMaxY, Acts::RectangleBounds::eMinX, Acts::RectangleBounds::eMinY, Acts::RectangleBounds::get(), green, Acts::Surface::Plane, red, Acts::s_epsilon, tgContext, Acts::TGeoSurfaceConverter::toSurface(), and Acts::ObjVisualization3D< T >::write().
Acts::Test::BOOST_AUTO_TEST_CASE (CylinderSurfaceConstruction)
Unit test for creating compliant/non-compliant CylinderSurface object.
Constructor with transform, radius and halfZ
Constructor with transform pointer, radius, halfZ and halfPhiSector
Constructor with transform and CylinderBounds pointer
Copy constructor
Copied and transformed
Construct with nullptr bounds
Definition at line 54 of file CylinderSurfaceTests.cpp.
View newest version in sPHENIX GitHub at line 54 of file CylinderSurfaceTests.cpp
References Acts::Surface::Cylinder, testContext, translation(), and Acts::type.
Acts::Test::BOOST_AUTO_TEST_CASE (TGeoLayerBuilderTests)
Unit test checking the match probability.
Definition at line 54 of file TGeoLayerBuilderTests.cpp.
View newest version in sPHENIX GitHub at line 54 of file TGeoLayerBuilderTests.cpp
References Acts::binR, Acts::binZ, Acts::TGeoLayerBuilder::centralLayers(), Acts::ObjVisualization3D< T >::clear(), Acts::TGeoLayerBuilder::Config::configurationName, Acts::TGeoLayerBuilder::detectorElements(), Acts::GeometryView3D::drawSurface(), Acts::getDefaultLogger(), Acts::TGeoLayerBuilder::Config::layerConfigurations, Acts::TGeoLayerBuilder::Config::layerCreator, Acts::TGeoLayerBuilder::positiveLayers(), Acts::TGeoLayerBuilder::Config::protoLayerHelper, writeMapConfig::surface, Acts::LayerCreator::Config::surfaceArrayCreator, Acts::tgContext, to_string(), physmon_ckf_tracking::u, Acts::Logging::VERBOSE, Acts::TGeoLayerBuilder::LayerConfig::volumeName, and Acts::ObjVisualization3D< T >::write().
Acts::Test::BOOST_AUTO_TEST_CASE (DiscSurfaceConstruction)
Unit tests for creating DiscSurface object.
Test DiscSurface constructor with default halfPhiSector
Test DiscSurface constructor with a transform specified
Copy constructed DiscSurface
Copied and transformed DiscSurface
Construct with nullptr bounds
Definition at line 54 of file DiscSurfaceTests.cpp.
View newest version in sPHENIX GitHub at line 54 of file DiscSurfaceTests.cpp
References tgContext, and translation().
Acts::Test::BOOST_AUTO_TEST_CASE (SurfaceView3DPly)
This tests if the corresponding ply output is well formatted.
Definition at line 55 of file SurfaceView3DTests.cpp.
View newest version in sPHENIX GitHub at line 55 of file SurfaceView3DTests.cpp
References Acts::SurfaceView3DTest::run(), and testPlyString().
Acts::Test::BOOST_AUTO_TEST_CASE (CylinderBoundsRecreation)
test default construction
Definition at line 56 of file CylinderBoundsTests.cpp.
View newest version in sPHENIX GitHub at line 56 of file CylinderBoundsTests.cpp
References Acts::CylinderBounds::eSize, and values.
Acts::Test::BOOST_AUTO_TEST_CASE (CutoutCylinderVolumeBoundsExceptions)
Definition at line 56 of file CutoutCylinderVolumeBoundsTests.cpp.
View newest version in sPHENIX GitHub at line 56 of file CutoutCylinderVolumeBoundsTests.cpp
References hz.
Acts::Test::BOOST_AUTO_TEST_CASE (TGeoTrd1_to_PlaneSurface)
Unit test to convert a TGeoTrd1 into a Plane.
The TGeoTrd1 can only have (x/X)(z/Z) orientation
Definition at line 56 of file TGeoTrd1ConversionTests.cpp.
View newest version in sPHENIX GitHub at line 56 of file TGeoTrd1ConversionTests.cpp
References allowedAxes, blue, bounds, CHECK_CLOSE_ABS, Acts::GeometryView3D::drawArrowForward(), Acts::GeometryView3D::drawSurface(), Acts::TrapezoidBounds::eHalfLengthXnegY, Acts::TrapezoidBounds::eHalfLengthXposY, Acts::TrapezoidBounds::eHalfLengthY, green, hy, Acts::UnitConstants::min, offset(), Acts::PrimitivesView3DTest::plane, Acts::Surface::Plane, red, Acts::s_epsilon, tgContext, thickness, Acts::TGeoSurfaceConverter::toSurface(), transform, and Acts::ObjVisualization3D< T >::write().
Acts::Test::BOOST_AUTO_TEST_CASE (TGeoTrd2_xz_to_PlaneSurface)
Unit test to convert a TGeoTrd2 into a Plane.
The TGeoTrd2 has x/z orientation
Definition at line 56 of file TGeoTrd2ConversionTests.cpp.
View newest version in sPHENIX GitHub at line 56 of file TGeoTrd2ConversionTests.cpp
References blue, bounds, CHECK_CLOSE_ABS, Acts::GeometryView3D::drawArrowForward(), Acts::GeometryView3D::drawSurface(), Acts::TrapezoidBounds::eHalfLengthXnegY, Acts::TrapezoidBounds::eHalfLengthXposY, Acts::TrapezoidBounds::eHalfLengthY, green, hy, Acts::UnitConstants::min, offset(), Acts::PrimitivesView3DTest::plane, Acts::Surface::Plane, red, Acts::s_epsilon, tgContext, thickness, Acts::TGeoSurfaceConverter::toSurface(), transform, and Acts::ObjVisualization3D< T >::write().
Acts::Test::BOOST_AUTO_TEST_CASE (TrapezoidVolumeBoundarySurfaces)
Definition at line 56 of file TrapezoidVolumeBoundsTests.cpp.
View newest version in sPHENIX GitHub at line 56 of file TrapezoidVolumeBoundsTests.cpp
References geoCtx, Acts::TrapezoidVolumeBounds::inside(), Acts::negativeFaceXY, Acts::negativeFaceZX, Acts::TrapezoidVolumeBounds::orientedSurfaces(), os, Acts::positiveFaceXY, and Acts::positiveFaceZX.
Acts::Test::BOOST_AUTO_TEST_CASE (constructor_copy_double)
Definition at line 56 of file Range1DTests.cpp.
View newest version in sPHENIX GitHub at line 56 of file Range1DTests.cpp
References Acts::Range1D< Type >::max(), Acts::Range1D< Type >::min(), and physmon_track_finding_ttbar::r.
Acts::Test::BOOST_AUTO_TEST_CASE (TestConstantBFieldInterfaceConsistency)
Definition at line 57 of file MagneticFieldInterfaceConsistencyTests.cpp.
View newest version in sPHENIX GitHub at line 57 of file MagneticFieldInterfaceConsistencyTests.cpp
References ckf::field, and testInterfaceConsistency().
Acts::Test::BOOST_AUTO_TEST_CASE (VolumeView3DPly)
Definition at line 57 of file VolumeView3DTests.cpp.
View newest version in sPHENIX GitHub at line 57 of file VolumeView3DTests.cpp
References Acts::VolumeView3DTest::run(), and testPlyString().
Acts::Test::BOOST_AUTO_TEST_CASE (phi_helper_test)
Definition at line 57 of file HelpersTests.cpp.
View newest version in sPHENIX GitHub at line 57 of file HelpersTests.cpp
References CHECK_CLOSE_ABS, Acts::UnitConstants::e, Acts::VectorHelpers::phi(), physmon_simulation::s, physmon_ckf_tracking::u, and testSigmaEff::v.
Acts::Test::BOOST_AUTO_TEST_CASE (AnnulusBoundsExcpetion)
Definition at line 57 of file AnnulusBoundsTests.cpp.
View newest version in sPHENIX GitHub at line 57 of file AnnulusBoundsTests.cpp
References maxPhi, maxRadius, minPhi, minRadius, and offset().
Acts::Test::BOOST_AUTO_TEST_CASE (CacheNonCopyable)
Definition at line 58 of file MagneticFieldProviderTests.cpp.
View newest version in sPHENIX GitHub at line 58 of file MagneticFieldProviderTests.cpp
References operator=(), and value.
Acts::Test::BOOST_AUTO_TEST_CASE (AccumulatedSurfaceMaterial_fill_convert_0D)
Test the filling and conversion.
Definition at line 58 of file AccumulatedSurfaceMaterialTests.cpp.
View newest version in sPHENIX GitHub at line 58 of file AccumulatedSurfaceMaterialTests.cpp
References Acts::AccumulatedSurfaceMaterial::accumulate(), Acts::Material::fromMolarDensity(), Acts::MaterialSlab::thicknessInX0(), and physmon_ckf_tracking::u.
Acts::Test::BOOST_AUTO_TEST_CASE (TGeoTube_to_CylinderSurface)
Unit test to convert a TGeoTube into a CylinderSurface.
The TGeoTrd1 can only have (x/X)(y/Y) orientation
Definition at line 58 of file TGeoTubeConversionTests.cpp.
View newest version in sPHENIX GitHub at line 58 of file TGeoTubeConversionTests.cpp
References allowedAxes, blue, bounds, CHECK_CLOSE_ABS, Acts::ObjVisualization3D< T >::clear(), Acts::Surface::Cylinder, Acts::GeometryView3D::drawArrowForward(), Acts::GeometryView3D::drawSurface(), Acts::CylinderBounds::eAveragePhi, Acts::CylinderBounds::eHalfLengthZ, Acts::CylinderBounds::eHalfPhiSector, Acts::CylinderBounds::eR, green, hz, notAllowedAxes, MATSCAN::phimin, red, Acts::s_epsilon, tgContext, thickness, to_string(), Acts::TGeoSurfaceConverter::toSurface(), transform, and Acts::ObjVisualization3D< T >::write().
Acts::Test::BOOST_AUTO_TEST_CASE (SurfaceConstruction)
todo: make test fixture; separate out different cases
Unit test for creating compliant/non-compliant Surface object
Definition at line 58 of file SurfaceTests.cpp.
View newest version in sPHENIX GitHub at line 58 of file SurfaceTests.cpp
References Acts::Surface::Other, merge_hashes::p, tgContext, transform, translation(), and Acts::type.
Acts::Test::BOOST_AUTO_TEST_CASE (CuboidVolumeException)
Definition at line 59 of file CuboidVolumeBoundsTests.cpp.
View newest version in sPHENIX GitHub at line 59 of file CuboidVolumeBoundsTests.cpp
References hx, hy, and hz.
Acts::Test::BOOST_AUTO_TEST_CASE (MeasurementVisualizationPly)
Definition at line 59 of file EventDataView3DTests.cpp.
View newest version in sPHENIX GitHub at line 59 of file EventDataView3DTests.cpp
References test_fpe::count, Acts::EventDataView3DTest::testMeasurement(), and testPlyString().
Acts::Test::BOOST_AUTO_TEST_CASE (box_construction)
Definition at line 59 of file BoundingBoxTest.cpp.
View newest version in sPHENIX GitHub at line 59 of file BoundingBoxTest.cpp
References CHECK_CLOSE_ABS, Acts::UnitConstants::e, Acts::AxisAlignedBoundingBox< entity_t, value_t, DIM >::max(), Acts::AxisAlignedBoundingBox< entity_t, value_t, DIM >::min(), and Acts::AxisAlignedBoundingBox< entity_t, value_t, DIM >::transformed().
Acts::Test::BOOST_AUTO_TEST_CASE (BinAdjustment_Rectangle)
Definition at line 60 of file BinAdjustmentTests.cpp.
View newest version in sPHENIX GitHub at line 60 of file BinAdjustmentTests.cpp
References Acts::adjustBinUtility(), Acts::BinUtility::binningData(), Acts::binX, Acts::binY, and Acts::open.
Acts::Test::BOOST_AUTO_TEST_CASE (hana_set_union_test)
Definition at line 60 of file MPLTests.cpp.
View newest version in sPHENIX GitHub at line 60 of file MPLTests.cpp
Acts::Test::BOOST_AUTO_TEST_CASE (PerigeeSurfaceProperties)
Unit test for testing PerigeeSurface properties.
Test clone method
Test type (redundant)
Test name
Test dump
Definition at line 61 of file PerigeeSurfaceTests.cpp.
View newest version in sPHENIX GitHub at line 61 of file PerigeeSurfaceTests.cpp
References Acts::Surface::Perigee, and tgContext.
Acts::Test::BOOST_AUTO_TEST_CASE (TestSolenoidBFieldInterfaceConsistency)
Definition at line 62 of file MagneticFieldInterfaceConsistencyTests.cpp.
View newest version in sPHENIX GitHub at line 62 of file MagneticFieldInterfaceConsistencyTests.cpp
References ckf::field, and testInterfaceConsistency().
Acts::Test::BOOST_AUTO_TEST_CASE (LineSurface_Constructors_test)
Unit test for creating compliant/non-compliant LineSurface object.
Construct with nullptr bounds
Definition at line 62 of file LineSurfaceTests.cpp.
View newest version in sPHENIX GitHub at line 62 of file LineSurfaceTests.cpp
References makePercentSlab(), tgContext, transform, and translation().
Acts::Test::BOOST_AUTO_TEST_CASE (track_density_finder_test)
Unit test for TrackDensityVertexFinder using same configuration and values as VertexSeedFinderTestAlg in Athena implementation, i.e. tests if reordering tracks returns the same result.
Definition at line 62 of file TrackDensityVertexFinderTests.cpp.
View newest version in sPHENIX GitHub at line 62 of file TrackDensityVertexFinderTests.cpp
References Acts::GenericBoundTrackParameters< ParticleHypothesis >::create(), geoContext, magFieldContext, Acts::VectorHelpers::makeVector4(), Acts::ParticleHypothesis::pion(), filter::state, and value.
Acts::Test::BOOST_AUTO_TEST_CASE (RadialBoundsException)
Definition at line 62 of file RadialBoundsTests.cpp.
View newest version in sPHENIX GitHub at line 62 of file RadialBoundsTests.cpp
References maxRadius, and minRadius.
Acts::Test::BOOST_AUTO_TEST_CASE (GenericCuboidBoundsOrientedSurfaces)
Definition at line 62 of file GenericCuboidVolumeBoundsTests.cpp.
View newest version in sPHENIX GitHub at line 62 of file GenericCuboidVolumeBoundsTests.cpp
References checkCloseAbs(), Acts::UnitConstants::e, gctx, Acts::GenericCuboidVolumeBounds::orientedSurfaces(), and ActsExamples::HepMC3Event::vertices().
Acts::Test::BOOST_AUTO_TEST_CASE (GeometryIdentifier_innervolume_test)
Definition at line 62 of file TrackingGeometryGeometryIdTests.cpp.
View newest version in sPHENIX GitHub at line 62 of file TrackingGeometryGeometryIdTests.cpp
References iVolume.
Acts::Test::BOOST_AUTO_TEST_CASE (ConvexPolygonBoundsConstruction)
Definition at line 63 of file ConvexPolygonBoundsTests.cpp.
View newest version in sPHENIX GitHub at line 63 of file ConvexPolygonBoundsTests.cpp
References Acts::ConvexPolygonBounds< N >::boundingBox(), Acts::ConvexPolygonBounds< N >::inside(), Acts::RectangleBounds::max(), Acts::RectangleBounds::min(), and ActsExamples::HepMC3Event::vertices().
Acts::Test::BOOST_AUTO_TEST_CASE (CuboidVolumeBuilderTest)
Definition at line 63 of file CuboidVolumeBuilderTests.cpp.
View newest version in sPHENIX GitHub at line 63 of file CuboidVolumeBuilderTests.cpp
References Acts::active, bounds, Acts::CuboidVolumeBuilder::buildLayer(), Acts::CuboidVolumeBuilder::buildSurface(), Acts::CuboidVolumeBuilder::buildVolume(), cfg, CHECK_CLOSE_ABS, filter::config, Acts::CuboidVolumeBuilder::SurfaceConfig::detElementConstructor, Acts::UnitConstants::e, i, layer, Acts::CuboidVolumeBuilder::VolumeConfig::layerCfg, Acts::CuboidVolumeBuilder::VolumeConfig::layers, Acts::CuboidVolumeBuilder::VolumeConfig::length, Acts::CuboidVolumeBuilder::Config::length, Acts::UnitConstants::m, makeBeryllium(), Acts::CuboidVolumeBuilder::VolumeConfig::name, Acts::CuboidVolumeBuilder::SurfaceConfig::position, Acts::CuboidVolumeBuilder::VolumeConfig::position, Acts::CuboidVolumeBuilder::Config::position, Acts::CuboidVolumeBuilder::SurfaceConfig::rBounds, Acts::CuboidVolumeBuilder::SurfaceConfig::rotation, Acts::CuboidVolumeBuilder::setConfig(), Acts::CuboidVolumeBuilder::LayerConfig::surfaceCfg, Acts::CuboidVolumeBuilder::SurfaceConfig::surMat, Acts::tgContext, thickness, Acts::CuboidVolumeBuilder::SurfaceConfig::thickness, Acts::TrackingGeometryBuilder::trackingGeometry(), Acts::CuboidVolumeBuilder::trackingVolume(), Acts::TrackingGeometryBuilder::Config::trackingVolumeBuilders, physmon_ckf_tracking::u, Acts::CuboidVolumeBuilder::Config::volumeCfg, and Acts::CuboidVolumeBuilder::VolumeConfig::volumeMaterial.
Acts::Test::BOOST_AUTO_TEST_CASE (construct_with_weights)
Definition at line 63 of file MaterialCompositionTests.cpp.
View newest version in sPHENIX GitHub at line 63 of file MaterialCompositionTests.cpp
References CHECK_CLOSE_REL, eps, f, and physmon_ckf_tracking::u.
Acts::Test::BOOST_AUTO_TEST_CASE (GeometryIdentifier_order)
Definition at line 63 of file GeometryIdentifierTests.cpp.
View newest version in sPHENIX GitHub at line 63 of file GeometryIdentifierTests.cpp
References Acts::GeometryIdentifier::setExtra(), Acts::GeometryIdentifier::setLayer(), Acts::GeometryIdentifier::setSensitive(), Acts::GeometryIdentifier::setVolume(), and physmon_ckf_tracking::u.
Acts::Test::BOOST_AUTO_TEST_CASE (TrapezoidBoundsException)
Definition at line 64 of file TrapezoidBoundsTests.cpp.
View newest version in sPHENIX GitHub at line 64 of file TrapezoidBoundsTests.cpp
References halfY.
Acts::Test::BOOST_AUTO_TEST_CASE (constructor_tuple_double)
Definition at line 64 of file Range1DTests.cpp.
View newest version in sPHENIX GitHub at line 64 of file Range1DTests.cpp
References Acts::Range1D< Type >::max(), Acts::Range1D< Type >::min(), and physmon_track_finding_ttbar::r.
Acts::Test::BOOST_AUTO_TEST_CASE (DivByZero)
Definition at line 65 of file FpeMonitorTests.cpp.
View newest version in sPHENIX GitHub at line 65 of file FpeMonitorTests.cpp
References Acts::FpeMonitor::Result::encountered(), and Acts::FpeMonitor::result().
Acts::Test::BOOST_AUTO_TEST_CASE (BinAdjustmentVolume_Cuboid)
Definition at line 65 of file BinAdjustmentVolumeTests.cpp.
View newest version in sPHENIX GitHub at line 65 of file BinAdjustmentVolumeTests.cpp
References Acts::adjustBinUtility(), Acts::BinUtility::binningData(), Acts::binX, Acts::binY, Acts::binZ, and Acts::open.
Acts::Test::BOOST_AUTO_TEST_CASE (perp_helper_test)
Definition at line 65 of file HelpersTests.cpp.
View newest version in sPHENIX GitHub at line 65 of file HelpersTests.cpp
References CHECK_CLOSE_ABS, Acts::UnitConstants::e, Acts::VectorHelpers::perp(), and testSigmaEff::v.
Acts::Test::BOOST_AUTO_TEST_CASE (ConeBoundsRecreation)
Definition at line 66 of file ConeBoundsTests.cpp.
View newest version in sPHENIX GitHub at line 66 of file ConeBoundsTests.cpp
References alpha, Acts::ConeBounds::eSize, values, and Acts::ConeBounds::values().
Acts::Test::BOOST_AUTO_TEST_CASE (two_materials)
Definition at line 66 of file AccumulatedVolumeMaterialTests.cpp.
View newest version in sPHENIX GitHub at line 66 of file AccumulatedVolumeMaterialTests.cpp
References Acts::AccumulatedVolumeMaterial::accumulate(), Acts::AccumulatedVolumeMaterial::average(), CHECK_CLOSE_REL, Acts::UnitConstants::e, and Acts::Material::fromMolarDensity().
Acts::Test::BOOST_AUTO_TEST_CASE (DiscTrapezoidBoundsExceptions)
Definition at line 66 of file DiscTrapezoidBoundsTests.cpp.
View newest version in sPHENIX GitHub at line 66 of file DiscTrapezoidBoundsTests.cpp
Acts::Test::BOOST_AUTO_TEST_CASE (SurfaceBoundsConstruction)
Unit test for creating compliant/non-compliant SurfaceBounds object.
Definition at line 66 of file SurfaceBoundsTests.cpp.
View newest version in sPHENIX GitHub at line 66 of file SurfaceBoundsTests.cpp
References physmon_simulation::s, t, physmon_ckf_tracking::u, and testSigmaEff::v.
Acts::Test::BOOST_AUTO_TEST_CASE (Grid_1D_rand)
Definition at line 66 of file ClusterizationTests1D.cpp.
View newest version in sPHENIX GitHub at line 66 of file ClusterizationTests1D.cpp
References clHashComp(), clusterAddCell(), clusters, col, hash(), i, j, testing::internal::move(), physmon_simulation::rnd, size, and Acts::Experimental::detail::BlueprintHelper::sort().
Acts::Test::BOOST_AUTO_TEST_CASE (TestInterpolatedBFieldMapInterfaceConsistency)
Definition at line 67 of file MagneticFieldInterfaceConsistencyTests.cpp.
View newest version in sPHENIX GitHub at line 67 of file MagneticFieldInterfaceConsistencyTests.cpp
References KFPMath::b, filter::config, Acts::UnitConstants::m, testing::internal::move(), Acts::InterpolatedBFieldMap< grid_t >::Config::scale, and testInterfaceConsistency().
Acts::Test::BOOST_AUTO_TEST_CASE (HomogeneousSurfaceMaterial_access_test)
Definition at line 67 of file HomogeneousSurfaceMaterialTests.cpp.
View newest version in sPHENIX GitHub at line 67 of file HomogeneousSurfaceMaterialTests.cpp
References Acts::Direction::Backward, CHECK_CLOSE_REL, Acts::UnitConstants::e, Acts::ISurfaceMaterial::factor(), Acts::Direction::Forward, Acts::Material::fromMolarDensity(), Acts::HomogeneousSurfaceMaterial::materialSlab(), and Acts::MaterialSlab::scaleThickness().
Acts::Test::BOOST_AUTO_TEST_CASE (LineBoundsAssignment)
Unit test for testing LineBounds assignment.
Definition at line 67 of file LineBoundsTests.cpp.
View newest version in sPHENIX GitHub at line 67 of file LineBoundsTests.cpp
Acts::Test::BOOST_AUTO_TEST_CASE (RectangleBoundsRecreation)
Recreation.
Definition at line 68 of file RectangleBoundsTests.cpp.
View newest version in sPHENIX GitHub at line 68 of file RectangleBoundsTests.cpp
References Acts::RectangleBounds::eSize, halfX, halfY, values, and Acts::RectangleBounds::values().
Acts::Test::BOOST_AUTO_TEST_CASE (CylinderBoundsException)
Definition at line 69 of file CylinderBoundsTests.cpp.
View newest version in sPHENIX GitHub at line 69 of file CylinderBoundsTests.cpp
Acts::Test::BOOST_AUTO_TEST_CASE (InterpolatedMaterialMap_MaterialMapper_test)
Definition at line 69 of file InterpolatedMaterialMapTests.cpp.
View newest version in sPHENIX GitHub at line 69 of file InterpolatedMaterialMapTests.cpp
References CHECK_CLOSE_REL, Acts::MaterialMapper< G >::getMaterial(), grid(), i, std::tr1::make_tuple(), testing::internal::move(), and trafoGlobalToLocal().
Acts::Test::BOOST_AUTO_TEST_CASE (MultiTrajectoryVisualizationObj)
Definition at line 70 of file EventDataView3DTests.cpp.
View newest version in sPHENIX GitHub at line 70 of file EventDataView3DTests.cpp
References test_fpe::count, Acts::EventDataView3DTest::testMultiTrajectory(), and testObjString().
Acts::Test::BOOST_AUTO_TEST_CASE (theta_eta_test_helper)
Definition at line 70 of file HelpersTests.cpp.
View newest version in sPHENIX GitHub at line 70 of file HelpersTests.cpp
References CHECK_CLOSE_ABS, Acts::UnitConstants::e, Acts::VectorHelpers::eta(), Acts::VectorHelpers::theta(), and testSigmaEff::v.
Acts::Test::BOOST_AUTO_TEST_CASE (straight_line_stepper_state_test)
These tests are aiming to test whether the state setup is working properly.
Definition at line 70 of file StraightLineStepperTests.cpp.
View newest version in sPHENIX GitHub at line 70 of file StraightLineStepperTests.cpp
References absMom, Acts::StraightLineStepper::absoluteMomentum(), charge, Acts::StraightLineStepper::charge(), CHECK_CLOSE_OR_SMALL, CHECK_CLOSE_REL, cov, Acts::StraightLineStepper::State::cov, Acts::StraightLineStepper::State::covTransport, Acts::StraightLineStepper::State::derivative, Acts::StraightLineStepper::direction(), eps, Acts::StraightLineStepper::State::jacToGlobal, Acts::StraightLineStepper::State::jacTransport, Acts::VectorHelpers::makeVector4(), mfContext, Acts::StraightLineStepper::State::pathAccumulated, Acts::ParticleHypothesis::pion(), Acts::ParticleHypothesis::pion0(), pos, Acts::StraightLineStepper::position(), Acts::StraightLineStepper::State::previousStepSize, stepSize, Acts::StraightLineStepper::State::stepSize, tgContext, time, Acts::StraightLineStepper::time(), tolerance, Acts::StraightLineStepper::State::tolerance, and Acts::ConstrainedStep::value().
Acts::Test::BOOST_AUTO_TEST_CASE (assign_double)
Definition at line 71 of file Range1DTests.cpp.
View newest version in sPHENIX GitHub at line 71 of file Range1DTests.cpp
References Acts::Range1D< Type >::max(), Acts::Range1D< Type >::min(), and physmon_track_finding_ttbar::r.
Acts::Test::BOOST_AUTO_TEST_CASE (SurfaceBoundsProperties)
Definition at line 72 of file SurfaceBoundsTests.cpp.
View newest version in sPHENIX GitHub at line 72 of file SurfaceBoundsTests.cpp
References writeMapConfig::surface, and Acts::SurfaceBoundsStub::values().
Acts::Test::BOOST_AUTO_TEST_CASE (ConeSurfacePolyhedrons)
Unit tests for Cone Surfaces.
The full cone on one side
The full cone on one side
Definition at line 72 of file PolyhedronSurfacesTests.cpp.
View newest version in sPHENIX GitHub at line 72 of file PolyhedronSurfacesTests.cpp
References alpha, Acts::binR, Acts::binX, Acts::binY, Acts::binZ, CHECK_CLOSE_ABS, Acts::UnitConstants::e, CKF_timing_vs_mu::mode, physmon_track_finding_ttbar::r, testModes, Acts::tgContext, and transform.
Acts::Test::BOOST_AUTO_TEST_CASE (adaptive_multi_vertex_finder_test)
AMVF test with Gaussian seed finder.
Definition at line 73 of file AdaptiveMultiVertexFinderTests.cpp.
View newest version in sPHENIX GitHub at line 73 of file AdaptiveMultiVertexFinderTests.cpp
References bField, CHECK_CLOSE_ABS, filter::Config, test_fpe::count, debugMode, geoContext, i, magFieldContext, testing::internal::move(), readTracksAndVertexCSV(), Acts::AnnealingUtility::Config::setOfTemperatures, filter::state, propagation_timing::stepper, ambiguity_solver_full_chain::t1, ambiguity_solver_full_chain::t2, toolString, and tracks().
Acts::Test::BOOST_AUTO_TEST_CASE (BinUtility_arbitrary_binning)
Definition at line 73 of file BinUtilityTests.cpp.
View newest version in sPHENIX GitHub at line 73 of file BinUtilityTests.cpp
References Acts::BinUtility::bin(), Acts::binX, Acts::open, and physmon_ckf_tracking::u.
Acts::Test::BOOST_AUTO_TEST_CASE (interpolation_3d)
Definition at line 73 of file InterpolationTests.cpp.
View newest version in sPHENIX GitHub at line 73 of file InterpolationTests.cpp
References CHECK_CLOSE_REL, Acts::UnitConstants::e, Acts::interpolate(), and testSigmaEff::v.
Acts::Test::BOOST_AUTO_TEST_CASE (BoundaryCheckBoxCovariance)
Definition at line 73 of file BoundaryCheckTests.cpp.
View newest version in sPHENIX GitHub at line 73 of file BoundaryCheckTests.cpp
References check_fpe_masks::check(), cov, and Acts::BoundaryCheck::isInside().
Acts::Test::BOOST_AUTO_TEST_CASE (BinAdjustment_Trapezoid)
Definition at line 75 of file BinAdjustmentTests.cpp.
View newest version in sPHENIX GitHub at line 75 of file BinAdjustmentTests.cpp
References Acts::adjustBinUtility(), Acts::BinUtility::binningData(), Acts::binX, Acts::binY, and Acts::open.
Acts::Test::BOOST_AUTO_TEST_CASE (CuboidVolumeProperties)
Definition at line 76 of file CuboidVolumeBoundsTests.cpp.
View newest version in sPHENIX GitHub at line 76 of file CuboidVolumeBoundsTests.cpp
References Acts::CuboidVolumeBounds::binningBorder(), Acts::binR, Acts::binX, Acts::binY, Acts::binZ, CHECK_CLOSE_ABS, Acts::VolumeBounds::eCuboid, Acts::CuboidVolumeBounds::eHalfLengthX, Acts::CuboidVolumeBounds::eHalfLengthY, Acts::CuboidVolumeBounds::eHalfLengthZ, Acts::CuboidVolumeBounds::get(), hx, hy, hz, Acts::CuboidVolumeBounds::inside(), Acts::s_epsilon, Acts::s_onSurfaceTolerance, Acts::CuboidVolumeBounds::type(), and Acts::CuboidVolumeBounds::values().
Acts::Test::BOOST_AUTO_TEST_CASE (LineBoundsProperties)
Unit tests for LineBounds properties.
test for type()
test for inside()
Test negative redius inside
test for r()
test for halflengthZ (NOTE: Naming violation)
test for dump
Definition at line 76 of file LineBoundsTests.cpp.
View newest version in sPHENIX GitHub at line 76 of file LineBoundsTests.cpp
References Acts::SurfaceBounds::eLine, Acts::LineBounds::inside(), origin(), and Acts::LineBounds::type().
Acts::Test::BOOST_AUTO_TEST_CASE (SurfaceProperties)
Unit test for testing Surface properties.
Definition at line 76 of file SurfaceTests.cpp.
View newest version in sPHENIX GitHub at line 76 of file SurfaceTests.cpp
References Acts::Surface::assignSurfaceMaterial(), Acts::Surface::associatedDetectorElement(), Acts::Surface::associatedLayer(), Acts::Surface::associateLayer(), Acts::Surface::center(), CHECK_CLOSE_OR_SMALL, Acts::PlaneLayer::create(), Acts::UnitConstants::e, Acts::Surface::insideBounds(), Acts::Surface::isOnSurface(), makePercentSlab(), Acts::Surface::referenceFrame(), writeMapConfig::surface, Acts::Surface::surfaceMaterial(), tgContext, Acts::Surface::transform(), translation(), and KFPMath::zero().
Acts::Test::BOOST_AUTO_TEST_CASE (cross_test_helper)
Definition at line 76 of file HelpersTests.cpp.
View newest version in sPHENIX GitHub at line 76 of file HelpersTests.cpp
References CHECK_CLOSE_ABS, Acts::VectorHelpers::cross(), Acts::UnitConstants::e, and testSigmaEff::v.
Acts::Test::BOOST_AUTO_TEST_CASE (hana_set_to_tuple_test)
Definition at line 76 of file MPLTests.cpp.
View newest version in sPHENIX GitHub at line 76 of file MPLTests.cpp
References std::tr1::make_tuple().
Acts::Test::BOOST_AUTO_TEST_CASE (LineLineIntersection)
Unit test for creating Ellipse intersection.
Definition at line 77 of file IntersectionHelper2DTests.cpp.
View newest version in sPHENIX GitHub at line 77 of file IntersectionHelper2DTests.cpp
References Acts::detail::IntersectionHelper2D::intersectSegment(), and start.
Acts::Test::BOOST_AUTO_TEST_CASE (TGeoParser_Pixel_SelectInnermost)
Unit test Parsing a TGeo geometries.
Convert into surfaces using the TGeoSurfaceConverter & Draw them
Definition at line 77 of file TGeoParserTests.cpp.
View newest version in sPHENIX GitHub at line 77 of file TGeoParserTests.cpp
References Acts::binR, Acts::binZ, Acts::GeometryView3D::drawSurface(), Acts::TGeoParser::Options::parseRanges, Acts::TGeoParser::select(), Acts::TGeoParser::State::selectedNodes, shape(), writeMapConfig::surface, Acts::TGeoParser::Options::targetNames, tgContext, thickness, Acts::TGeoSurfaceConverter::toSurface(), transform, physmon_ckf_tracking::u, Acts::TGeoParser::Options::unit, Acts::TGeoParser::State::volume, and Acts::TGeoParser::Options::volumeNames.
Acts::Test::BOOST_AUTO_TEST_CASE (grid_density_vertex_finder_test)
Unit test for GridDensityVertexFinder without caching of track density values.
Definition at line 78 of file GridDensityVertexFinderTests.cpp.
View newest version in sPHENIX GitHub at line 78 of file GridDensityVertexFinderTests.cpp
References charge(), CHECK_CLOSE_ABS, filter::Config, Acts::GenericBoundTrackParameters< ParticleHypothesis >::create(), debugMode, eta, etaDist(), Acts::eZ, gen(), geoContext, i, magFieldContext, Acts::makeDirectionFromPhiEta(), Acts::VectorHelpers::makeVector4(), ActsTests::PropagationDatasets::phi, phiDist(), Acts::ParticleHypothesis::pion(), pos, physmon_track_finding_ttbar::pt, pTDist(), value, xdist(), ydist(), z1dist(), z2dist(), and zVertexPos1.
Acts::Test::BOOST_AUTO_TEST_CASE (PrimitivesView3DObj)
Definition at line 78 of file PrimitivesView3DTests.cpp.
View newest version in sPHENIX GitHub at line 78 of file PrimitivesView3DTests.cpp
References Acts::PrimitivesView3DTest::run(), and testObjString().
Acts::Test::BOOST_AUTO_TEST_CASE (Overflow)
Definition at line 78 of file FpeMonitorTests.cpp.
View newest version in sPHENIX GitHub at line 78 of file FpeMonitorTests.cpp
References Acts::FpeMonitor::Result::encountered(), and Acts::FpeMonitor::result().
Acts::Test::BOOST_AUTO_TEST_CASE (ConeBoundsExceptions)
Definition at line 79 of file ConeBoundsTests.cpp.
View newest version in sPHENIX GitHub at line 79 of file ConeBoundsTests.cpp
References alpha.
Acts::Test::BOOST_AUTO_TEST_CASE (PolyhedronExtent)
Unit tests for Polyderon construction & operator +=.
Definition at line 79 of file PolyhedronTests.cpp.
View newest version in sPHENIX GitHub at line 79 of file PolyhedronTests.cpp
References Acts::binPhi, Acts::binR, Acts::binX, Acts::binY, Acts::binZ, CHECK_CLOSE_ABS, Acts::UnitConstants::e, Acts::Polyhedron::extent(), Acts::VectorHelpers::perp(), Acts::VectorHelpers::phi(), and Acts::PrimitivesView3DTest::rectangle.
Acts::Test::BOOST_AUTO_TEST_CASE (AnnulusBoundsProperties)
Unit tests for AnnulusBounds properties.
Test construction with radii and default sector
Test type() (redundant; already used in constructor confirmation)
Test positions inside/outside
Definition at line 79 of file AnnulusBoundsTests.cpp.
View newest version in sPHENIX GitHub at line 79 of file AnnulusBoundsTests.cpp
References Acts::SurfaceBounds::eAnnulus, Acts::AnnulusBounds::eMaxPhiRel, Acts::AnnulusBounds::eMaxR, Acts::AnnulusBounds::eMinPhiRel, Acts::AnnulusBounds::eMinR, Acts::AnnulusBounds::get(), Acts::AnnulusBounds::inside(), Acts::AnnulusBounds::insideRadialBounds(), maxPhi, maxRadius, minPhi, minRadius, offset(), Acts::VectorHelpers::perp(), ActsTests::PropagationDatasets::phi, Acts::VectorHelpers::phi(), physmon_track_finding_ttbar::r, Acts::AnnulusBounds::type(), and Acts::Svg::View::xy().
Acts::Test::BOOST_AUTO_TEST_CASE (shrinkMin_double)
Definition at line 79 of file Range1DTests.cpp.
View newest version in sPHENIX GitHub at line 79 of file Range1DTests.cpp
References Acts::Range1D< Type >::max(), Acts::Range1D< Type >::min(), physmon_track_finding_ttbar::r, and Acts::Range1D< Type >::shrinkMin().
Acts::Test::BOOST_AUTO_TEST_CASE (SurfaceBoundsEquality)
Unit test for testing SurfaceBounds properties.
Definition at line 80 of file SurfaceBoundsTests.cpp.
View newest version in sPHENIX GitHub at line 80 of file SurfaceBoundsTests.cpp
References writeMapConfig::surface, and Acts::SurfaceBoundsStub::values().
Acts::Test::BOOST_AUTO_TEST_CASE (EqualityOperators)
Test equality operator
Test assignment
Test equality of assigned to original
Test equality operator
Test assignment
Test equality of assigned to original
Test equality operator
Test assignment
Test equality of assigned to original
Definition at line 81 of file PerigeeSurfaceTests.cpp.
View newest version in sPHENIX GitHub at line 81 of file PerigeeSurfaceTests.cpp
Acts::Test::BOOST_AUTO_TEST_CASE (PlaneSurfaceProperties)
Unit test for testing PlaneSurface properties.
Test clone method
Test type (redundant)
Test binningPosition
Test referenceFrame
Test normal, given 3D position
Test bounds
Test localToGlobal
Testing globalToLocal
Test isOnSurface
Test pathCorrection
Test name
Test dump
Definition at line 81 of file PlaneSurfaceTests.cpp.
View newest version in sPHENIX GitHub at line 81 of file PlaneSurfaceTests.cpp
References Acts::binX, CHECK_CLOSE_OR_SMALL, CHECK_CLOSE_REL, Acts::UnitConstants::e, Acts::SurfaceBounds::eRectangle, acts::error, momentum, Acts::Surface::Plane, rBounds, tgContext, and translation().
Acts::Test::BOOST_AUTO_TEST_CASE (MultiTrajectoryVisualizationPly)
Definition at line 81 of file EventDataView3DTests.cpp.
View newest version in sPHENIX GitHub at line 81 of file EventDataView3DTests.cpp
References test_fpe::count, Acts::EventDataView3DTest::testMultiTrajectory(), and testPlyString().
Acts::Test::BOOST_AUTO_TEST_CASE (CylinderVolumeBoundsRecreation)
Definition at line 83 of file CylinderVolumeBoundsTests.cpp.
View newest version in sPHENIX GitHub at line 83 of file CylinderVolumeBoundsTests.cpp
References Acts::CylinderVolumeBounds::eSize, values, and Acts::CylinderVolumeBounds::values().
Acts::Test::BOOST_AUTO_TEST_CASE (StrawSurfaceProperties)
Unit test for testing StrawSurface properties.
Test clone method
Test type (redundant)
Test name
Test dump
Definition at line 84 of file StrawSurfaceTests.cpp.
View newest version in sPHENIX GitHub at line 84 of file StrawSurfaceTests.cpp
References Acts::Surface::Straw, tgContext, and translation().
Acts::Test::BOOST_AUTO_TEST_CASE (volume_material_interaction_test)
Definition at line 84 of file VolumeMaterialInteractionTests.cpp.
View newest version in sPHENIX GitHub at line 84 of file VolumeMaterialInteractionTests.cpp
References Acts::Test::StepperState::absCharge, Acts::Test::Stepper::absoluteMomentum(), Acts::Direction::Backward, Acts::Test::Stepper::charge(), CHECK_CLOSE_ABS, Acts::Test::StepperState::covTransport, Acts::TrackingVolume::create(), Acts::Test::NaivgatorState::currentVolume, Acts::Test::StepperState::dir, Acts::Test::State::direction, Acts::Test::Stepper::direction(), Acts::UnitConstants::e, makeSilicon(), Acts::Test::State::navigation, navigator, Acts::Test::State::options, Acts::Test::StepperState::p, Acts::Test::StepperState::particleHypothesis, Acts::Test::StepperState::pos, Acts::Test::Stepper::position(), Acts::Test::StepperState::q, Acts::Test::Stepper::qOverP(), filter::state, propagation_timing::stepper, Acts::Test::State::stepping, Acts::Test::StepperState::t, and Acts::Test::Stepper::time().
Acts::Test::BOOST_AUTO_TEST_CASE (two_materials_different_lengh)
Definition at line 85 of file AccumulatedVolumeMaterialTests.cpp.
View newest version in sPHENIX GitHub at line 85 of file AccumulatedVolumeMaterialTests.cpp
References Acts::AccumulatedVolumeMaterial::accumulate(), Acts::AccumulatedVolumeMaterial::average(), CHECK_CLOSE_REL, Acts::UnitConstants::e, and Acts::Material::fromMolarDensity().
Acts::Test::BOOST_AUTO_TEST_CASE (TrapezoidBoundsProperties)
Unit tests for TrapezoidBounds properties.
Test type() (redundant; already used in constructor confirmation)
Test minHalflengthX
Test maxHalfLengthX
Test halflengthY
Test distanceToBoundary
Test vertices
for (auto i: trapezoidBoundsObject.vertices()){ std::cout<<i[0]<<", "<<i[1]<<std::endl; }
Test boundingBox
Test dump
Test inside
Definition at line 85 of file TrapezoidBoundsTests.cpp.
View newest version in sPHENIX GitHub at line 85 of file TrapezoidBoundsTests.cpp
References Acts::TrapezoidBounds::boundingBox(), Acts::TrapezoidBounds::eHalfLengthXnegY, Acts::TrapezoidBounds::eHalfLengthXposY, Acts::TrapezoidBounds::eHalfLengthY, Acts::SurfaceBounds::eTrapezoid, Acts::TrapezoidBounds::get(), halfY, Acts::TrapezoidBounds::inside(), merge_hashes::p, Acts::TrapezoidBounds::toStream(), Acts::TrapezoidBounds::type(), Acts::TrapezoidBounds::vertices(), and ActsExamples::HepMC3Event::vertices().
Acts::Test::BOOST_AUTO_TEST_CASE (BoundaryCheckPolyDistance)
Definition at line 86 of file BoundaryCheckTests.cpp.
View newest version in sPHENIX GitHub at line 86 of file BoundaryCheckTests.cpp
References CHECK_CLOSE_REL, distance(), Acts::BoundaryCheck::distance(), Acts::UnitConstants::e, i, rectDistances, rectShiftedDistances, rectShiftedTestPoints, rectShiftedVertices, rectTestPoints, and rectVertices.
Acts::Test::BOOST_AUTO_TEST_CASE (Kalman_Vertex_TrackUpdater)
Unit test for KalmanVertexTrackUpdater.
Definition at line 86 of file KalmanVertexTrackUpdaterTests.cpp.
View newest version in sPHENIX GitHub at line 86 of file KalmanVertexTrackUpdaterTests.cpp
References Acts::IntegrationTest::bField, filter::Config, d0Dist(), debug, Acts::TrackAtVertex< input_track_t >::fittedParams, gen(), geoContext, i, Acts::TrackAtVertex< input_track_t >::linearizedState, magFieldContext, testing::internal::move(), phiDist(), Acts::ParticleHypothesis::pion(), pTDist(), qDist(), resAngDist(), resIPDist(), resQoPDist(), filter::state, propagation_timing::stepper, thetaDist(), vXYDist(), vZDist(), and z0Dist().
Acts::Test::BOOST_AUTO_TEST_CASE (Visualization3DTesterPly)
Definition at line 86 of file Visualization3DTests.cpp.
View newest version in sPHENIX GitHub at line 86 of file Visualization3DTests.cpp
Acts::Test::BOOST_AUTO_TEST_CASE (AccumulatedSurfaceMaterial_fill_convert_1D)
Test the filling and conversion.
Definition at line 87 of file AccumulatedSurfaceMaterialTests.cpp.
View newest version in sPHENIX GitHub at line 87 of file AccumulatedSurfaceMaterialTests.cpp
References Acts::binX, Acts::binY, Acts::Material::fromMolarDensity(), Acts::open, Acts::MaterialSlab::thicknessInX0(), and physmon_ckf_tracking::u.
Acts::Test::BOOST_AUTO_TEST_CASE (equality_int)
Definition at line 87 of file RangeXDTests.cpp.
View newest version in sPHENIX GitHub at line 87 of file RangeXDTests.cpp
References physmon_track_finding_ttbar::r.
Acts::Test::BOOST_AUTO_TEST_CASE (Kalman_Vertex_Updater)
Unit test for KalmanVertexUpdater.
Definition at line 87 of file KalmanVertexUpdaterTests.cpp.
View newest version in sPHENIX GitHub at line 87 of file KalmanVertexUpdaterTests.cpp
References Acts::IntegrationTest::bField, d0Dist(), debug, gen(), geoContext, i, Acts::TrackAtVertex< input_track_t >::linearizedState, magFieldContext, testing::internal::move(), phiDist(), Acts::ParticleHypothesis::pion(), pTDist(), qDist(), resAngDist(), resIPDist(), resQoPDist(), Acts::Vertex< input_track_t >::setFullCovariance(), filter::state, propagation_timing::stepper, thetaDist(), vXYDist(), vZDist(), and z0Dist().
Acts::Test::BOOST_AUTO_TEST_CASE (GeometryIdentifier_outervolume_test)
Definition at line 87 of file TrackingGeometryGeometryIdTests.cpp.
View newest version in sPHENIX GitHub at line 87 of file TrackingGeometryGeometryIdTests.cpp
References iVolume, and oVolume.
Acts::Test::BOOST_AUTO_TEST_CASE (ConeVolumeBoundsSurfaceOrientation)
Definition at line 88 of file ConeVolumeBoundsTests.cpp.
View newest version in sPHENIX GitHub at line 88 of file ConeVolumeBoundsTests.cpp
References geoCtx, Acts::ConeVolumeBounds::orientedSurfaces(), os, and Acts::tgContext.
Acts::Test::BOOST_AUTO_TEST_CASE (PrimitivesView3DPly)
Definition at line 88 of file PrimitivesView3DTests.cpp.
View newest version in sPHENIX GitHub at line 88 of file PrimitivesView3DTests.cpp
References Acts::PrimitivesView3DTest::run(), and testPlyString().
Acts::Test::BOOST_AUTO_TEST_CASE (shrinkMax_double)
Definition at line 88 of file Range1DTests.cpp.
View newest version in sPHENIX GitHub at line 88 of file Range1DTests.cpp
References Acts::Range1D< Type >::max(), Acts::Range1D< Type >::min(), physmon_track_finding_ttbar::r, and Acts::Range1D< Type >::shrinkMax().
Acts::Test::BOOST_AUTO_TEST_CASE (zscan_finder_test)
Unit test for ZScanVertexFinder.
Definition at line 90 of file ZScanVertexFinderTests.cpp.
View newest version in sPHENIX GitHub at line 90 of file ZScanVertexFinderTests.cpp
References Acts::IntegrationTest::bField, cfg, CHECK_CLOSE_ABS, filter::Config, d0Dist(), Acts::eBoundLoc0, Acts::eBoundLoc1, Acts::eBoundPhi, Acts::eBoundQOverP, Acts::eBoundTheta, Acts::eZ, gen(), geoContext, magFieldContext, testing::internal::move(), phiDist(), Acts::ParticleHypothesis::pion(), pTDist(), qDist(), resAngDist(), resIPDist(), resQoPDist(), filter::state, propagation_timing::stepper, thetaDist(), tracks(), vXYDist(), vZDist(), ambiguity_solver_full_chain::x, y, physmon_track_finding_ttbar::z, and z0Dist().
Acts::Test::BOOST_AUTO_TEST_CASE (Combinations)
Definition at line 90 of file FpeMonitorTests.cpp.
View newest version in sPHENIX GitHub at line 90 of file FpeMonitorTests.cpp
References Acts::FpeMonitor::Result::encountered(), and Acts::FpeMonitor::result().
Acts::Test::BOOST_AUTO_TEST_CASE (toString_test_helper)
Definition at line 90 of file HelpersTests.cpp.
View newest version in sPHENIX GitHub at line 90 of file HelpersTests.cpp
References out, and Acts::toString().
Acts::Test::BOOST_AUTO_TEST_CASE (DiscSurfaceProperties)
Unit tests of all named methods.
Test type
Test normal, no local position specified
Test normal, local position specified
Test binningPosition
Test bounds
Test isOnSurface()
Test localToGlobal
Test globalToLocal
Test localPolarToCartesian
Test localCartesianToPolar
Test localPolarToLocalCartesian
Test localCartesianToGlobal
Test globalToLocalCartesian
Test pathCorrection
intersection test
Test name
Definition at line 91 of file DiscSurfaceTests.cpp.
View newest version in sPHENIX GitHub at line 91 of file DiscSurfaceTests.cpp
References Acts::binRPhi, CHECK_CLOSE_ABS, CHECK_CLOSE_REL, Acts::Surface::Disc, Acts::UnitConstants::e, Acts::SurfaceBounds::eDisc, momentum, and tgContext.
Acts::Test::BOOST_AUTO_TEST_CASE (TestErrorCodes)
Definition at line 91 of file ResultTests.cpp.
View newest version in sPHENIX GitHub at line 91 of file ResultTests.cpp
References physmon_ckf_tracking::u.
Acts::Test::BOOST_AUTO_TEST_CASE (RadialBoundsProperties)
Unit tests for RadialBounds properties.
Test type() (redundant; already used in constructor confirmation)
Test distanceToBoundary
Test dump
Test inside
Test rMin
Test rMax
Test averagePhi (should be a redundant method, this is not configurable)
Test halfPhiSector
Definition at line 91 of file RadialBoundsTests.cpp.
View newest version in sPHENIX GitHub at line 91 of file RadialBoundsTests.cpp
References Acts::RadialBounds::eAveragePhi, Acts::SurfaceBounds::eDisc, Acts::RadialBounds::eHalfPhiSector, Acts::RadialBounds::eMaxR, Acts::RadialBounds::eMinR, Acts::RadialBounds::get(), Acts::RadialBounds::inside(), maxRadius, minRadius, Acts::RadialBounds::toStream(), and Acts::RadialBounds::type().
Acts::Test::BOOST_AUTO_TEST_CASE (CutoutCylinderVolumeBoundsAccess)
Definition at line 92 of file CutoutCylinderVolumeBoundsTests.cpp.
View newest version in sPHENIX GitHub at line 92 of file CutoutCylinderVolumeBoundsTests.cpp
References Acts::CutoutCylinderVolumeBounds::eHalfLengthZ, Acts::CutoutCylinderVolumeBounds::eHalfLengthZcutout, Acts::CutoutCylinderVolumeBounds::eMaxR, Acts::CutoutCylinderVolumeBounds::eMedR, Acts::CutoutCylinderVolumeBounds::eMinR, Acts::CutoutCylinderVolumeBounds::get(), and hz.
Acts::Test::BOOST_AUTO_TEST_CASE (adaptive_multi_vertex_fitter_test)
Unit test for AdaptiveMultiVertexFitter.
Definition at line 92 of file AdaptiveMultiVertexFitterTests.cpp.
View newest version in sPHENIX GitHub at line 92 of file AdaptiveMultiVertexFitterTests.cpp
References Acts::AdaptiveMultiVertexFitter< input_track_t, linearizer_t >::State::addVertexToMultiMap(), Acts::AdaptiveMultiVertexFitter< input_track_t, linearizer_t >::addVtxToFit(), bField, Acts::PhysicalConstants::c, CHECK_CLOSE_ABS, filter::Config, d0Dist(), debugMode, Acts::AdaptiveMultiVertexFitter< input_track_t, linearizer_t >::Config::doSmoothing, gen(), geoContext, magFieldContext, testing::internal::move(), phiDist(), Acts::ParticleHypothesis::pion(), pTDist(), qDist(), resAngDist(), resIPDist(), resQoPDist(), Acts::Vertex< input_track_t >::setFullCovariance(), filter::state, propagation_timing::stepper, thetaDist(), Acts::AdaptiveMultiVertexFitter< input_track_t, linearizer_t >::State::tracksAtVerticesMap, Acts::AdaptiveMultiVertexFitter< input_track_t, linearizer_t >::State::trackToVerticesMultiMap, Acts::AdaptiveMultiVertexFitter< input_track_t, linearizer_t >::State::vtxInfoMap, and z0Dist().
Acts::Test::BOOST_AUTO_TEST_CASE (RectangleBoundsProperties)
Unit test for testing RectangleBounds properties.
Definition at line 92 of file RectangleBoundsTests.cpp.
View newest version in sPHENIX GitHub at line 92 of file RectangleBoundsTests.cpp
References CHECK_CLOSE_ABS, Acts::UnitConstants::e, Acts::RectangleBounds::halfLengthX(), Acts::RectangleBounds::halfLengthY(), halfX, halfY, Acts::RectangleBounds::inside(), Acts::RectangleBounds::max(), Acts::RectangleBounds::min(), rectVertices, and Acts::RectangleBounds::vertices().
Acts::Test::BOOST_AUTO_TEST_CASE (BinUtility_transform)
Definition at line 92 of file BinUtilityTests.cpp.
View newest version in sPHENIX GitHub at line 92 of file BinUtilityTests.cpp
References Acts::BinUtility::bin(), Acts::binPhi, Acts::binR, Acts::binZ, Acts::closed, i, Acts::open, and pos4().
Acts::Test::BOOST_AUTO_TEST_CASE (intersect_points)
Definition at line 93 of file BoundingBoxTest.cpp.
View newest version in sPHENIX GitHub at line 93 of file BoundingBoxTest.cpp
References merge_hashes::p.
Acts::Test::BOOST_AUTO_TEST_CASE (CylinderBoundsProperties)
Unit tests for CylinderBounds properties.
test for type()
test for inside(), 2D coords are r or phi ,z? : needs clarification
test for inside3D() with Vector3 argument
test for r()
test for averagePhi
test for halfPhiSector
test for halflengthZ (NOTE: Naming violation)
test for bevelMinZ/MaxZ
test for dump
Definition at line 94 of file CylinderBoundsTests.cpp.
View newest version in sPHENIX GitHub at line 94 of file CylinderBoundsTests.cpp
References CHECK_CLOSE_OR_SMALL, CHECK_CLOSE_REL, Acts::UnitConstants::e, Acts::CylinderBounds::eAveragePhi, Acts::CylinderBounds::eBevelMaxZ, Acts::CylinderBounds::eBevelMinZ, Acts::SurfaceBounds::eCylinder, Acts::CylinderBounds::eHalfLengthZ, Acts::CylinderBounds::eHalfPhiSector, Acts::CylinderBounds::eR, Acts::CylinderBounds::get(), Acts::CylinderBounds::inside(), Acts::CylinderBounds::inside3D(), origin(), Acts::CylinderBounds::toStream(), and Acts::CylinderBounds::type().
Acts::Test::BOOST_AUTO_TEST_CASE (CylinderVolumeBoundsExceptions)
Definition at line 94 of file CylinderVolumeBoundsTests.cpp.
View newest version in sPHENIX GitHub at line 94 of file CylinderVolumeBoundsTests.cpp
References rBounds.
Acts::Test::BOOST_AUTO_TEST_CASE (ConvexPolygonBoundsRecreation)
Definition at line 95 of file ConvexPolygonBoundsTests.cpp.
View newest version in sPHENIX GitHub at line 95 of file ConvexPolygonBoundsTests.cpp
References Acts::ConvexPolygonBoundsBase::values(), values, and ActsExamples::HepMC3Event::vertices().
Acts::Test::BOOST_AUTO_TEST_CASE (Transitions)
Definition at line 95 of file FiniteStateMachineTests.cpp.
View newest version in sPHENIX GitHub at line 95 of file FiniteStateMachineTests.cpp
Acts::Test::BOOST_AUTO_TEST_CASE (BinningData_BinningValue)
x/y/zData check the global position requests
check the global position requests
check the local position requests
Definition at line 96 of file BinningDataTests.cpp.
View newest version in sPHENIX GitHub at line 96 of file BinningDataTests.cpp
References Acts::binPhi, Acts::BinningData::bins(), Acts::binX, CHECK_CLOSE_REL, CHECK_SMALL, Acts::closed, delta, Acts::UnitConstants::e, eta0Position(), etaData_eq, i, nBins_binary, Acts::open, phi0Position(), phiData_arb, phiData_eq, phiDelta, phiMin, phiPihPosition(), rData_eq, rphiPosition(), rphizPosition(), Acts::BinningData::value(), valueMin, xData_add(), xData_arb, xData_eq, xData_eq_copy, xData_mult, xyPosition(), xyzPosition(), yData_eq, and zData_eq.
Acts::Test::BOOST_AUTO_TEST_CASE (ConeSurfaceProperties)
Unit test for testing ConeSurface properties.
Test clone method
Test type (redundant)
Test binningPosition
Test referenceFrame
Test normal, given 3D position
Test normal given 2D rphi position
Test rotational symmetry axis
Test bounds
Test localToGlobal
Testing globalToLocal
Test isOnSurface
Test pathCorrection
Test name
Test dump
Definition at line 97 of file ConeSurfaceTests.cpp.
View newest version in sPHENIX GitHub at line 97 of file ConeSurfaceTests.cpp
References alpha, Acts::binPhi, CHECK_CLOSE_ABS, CHECK_CLOSE_OR_SMALL, CHECK_CLOSE_REL, Acts::Surface::Cone, Acts::UnitConstants::e, Acts::SurfaceBounds::eCone, momentum, origin(), tgContext, and translation().
Acts::Test::BOOST_AUTO_TEST_CASE (unpack_boost_set_as_template_test)
Definition at line 97 of file MPLTests.cpp.
View newest version in sPHENIX GitHub at line 97 of file MPLTests.cpp
References Acts::type, and value.
Acts::Test::BOOST_AUTO_TEST_CASE (shrink_both_double)
Definition at line 97 of file Range1DTests.cpp.
View newest version in sPHENIX GitHub at line 97 of file Range1DTests.cpp
References Acts::Range1D< Type >::max(), Acts::Range1D< Type >::min(), physmon_track_finding_ttbar::r, Acts::Range1D< Type >::shrinkMax(), and Acts::Range1D< Type >::shrinkMin().
Acts::Test::BOOST_AUTO_TEST_CASE (LineSurface_allNamedMethods_test)
Unit tests of all named methods.
Definition at line 98 of file LineSurfaceTests.cpp.
View newest version in sPHENIX GitHub at line 98 of file LineSurfaceTests.cpp
References Acts::LineSurface::binningPosition(), Acts::binX, bounds, Acts::LineSurface::bounds(), CHECK_CLOSE_ABS, CHECK_CLOSE_OR_SMALL, closest(), Acts::UnitConstants::e, Acts::LineSurface::globalToLocal(), gpos, Acts::LineSurface::intersect(), Acts::Surface::isOnSurface(), line, Acts::LineSurface::localToGlobal(), momentum, Acts::LineSurface::name(), Acts::LineSurface::normal(), check_smearing_config::output, Acts::LineSurface::pathCorrection(), Acts::LineSurface::referenceFrame(), tgContext, transform, translation(), v1, and value.
Acts::Test::BOOST_AUTO_TEST_CASE (CylinderSurfaceProperties)
Unit test for testing CylinderSurface properties.
Test clone method
Test type (redundant)
Test binningPosition
Test referenceFrame
Test normal, given 3D position
Test normal given 2D rphi position
Test rotational symmetry axis
Test bounds
Test localToGlobal
Testing globalToLocal
Test isOnSurface
intersection test
Test pathCorrection
Test name
Test dump
Definition at line 99 of file CylinderSurfaceTests.cpp.
View newest version in sPHENIX GitHub at line 99 of file CylinderSurfaceTests.cpp
References Acts::binPhi, CHECK_CLOSE_ABS, CHECK_CLOSE_OR_SMALL, CHECK_CLOSE_REL, Acts::Surface::Cylinder, Acts::UnitConstants::e, Acts::SurfaceBounds::eCylinder, momentum, origin(), ActsTests::PropagationDatasets::pathLength, position, testContext, and translation().
Acts::Test::BOOST_AUTO_TEST_CASE (linearized_track_factory_test)
Test HelicalTrackLinearizer by comparing it to NumericalTrackLinearizer.
Note
While HelicalTrackLinearizer computes the Jacobians using analytically derived formulae, NumericalTrackLinearizer uses numerical differentiation: f'(x) ~ (f(x+dx) - f(x)) / dx).
Definition at line 100 of file LinearizedTrackFactoryTests.cpp.
View newest version in sPHENIX GitHub at line 100 of file LinearizedTrackFactoryTests.cpp
References CHECK_CLOSE_OR_SMALL, Acts::LinearizedTrack::constantTerm, Acts::LinearizedTrack::covarianceAtPCA, d0Dist(), Acts::UnitConstants::e, gen(), geoContext, Acts::LinearizedTrack::linearizationPoint, magFieldContext, Acts::LinearizedTrack::momentumJacobian, testing::internal::move(), Acts::LinearizedTrack::parametersAtPCA, phiDist(), Acts::ParticleHypothesis::pion(), Acts::VectorHelpers::position(), Acts::LinearizedTrack::positionJacobian, pTDist(), qDist(), resAngDist(), resIPDist(), resQoPDist(), resTDist(), seed, small, propagation_timing::stepper, t, tDist(), thetaDist(), tracks(), vTDist(), vXYDist(), vZDist(), ambiguity_solver_full_chain::x, y, physmon_track_finding_ttbar::z, and z0Dist().
Acts::Test::BOOST_AUTO_TEST_CASE (ConeBoundsProperties)
Unit tests for properties of ConeBounds object.
test for type (redundant)
test for inside
test for r
test for tanAlpha
test for alpha
test for minZ
test for maxZ
test for averagePhi
test for dump
Definition at line 101 of file ConeBoundsTests.cpp.
View newest version in sPHENIX GitHub at line 101 of file ConeBoundsTests.cpp
References alpha, CHECK_CLOSE_REL, Acts::UnitConstants::e, Acts::ConeBounds::eAlpha, Acts::SurfaceBounds::eCone, Acts::ConeBounds::eHalfPhiSector, Acts::ConeBounds::eMaxZ, Acts::ConeBounds::eMinZ, Acts::ConeBounds::get(), Acts::ConeBounds::inside(), origin(), Acts::ConeBounds::r(), Acts::ConeBounds::tanAlpha(), Acts::ConeBounds::toStream(), and Acts::ConeBounds::type().
Acts::Test::BOOST_AUTO_TEST_CASE (variable_axis)
Definition at line 103 of file AxesTests.cpp.
View newest version in sPHENIX GitHub at line 103 of file AxesTests.cpp
References KFPMath::a, and physmon_ckf_tracking::u.
Acts::Test::BOOST_AUTO_TEST_CASE (GeometryIdentifier_closeGeometry_test)
Definition at line 103 of file TrackingGeometryClosureTests.cpp.
View newest version in sPHENIX GitHub at line 103 of file TrackingGeometryClosureTests.cpp
References Acts::BinnedArray< T >::arrayObjects(), Acts::TrackingVolume::boundarySurfaces(), Acts::TrackingVolume::confinedLayers(), Acts::GeometryObject::geometryId(), Acts::TrackingGeometry::highestTrackingVolume(), makeTrackingGeometry(), Acts::tGeometry, and Acts::GeometryIdentifier::volume().
Acts::Test::BOOST_AUTO_TEST_CASE (CutoutCylinderVolumeBoundsInside)
Definition at line 104 of file CutoutCylinderVolumeBoundsTests.cpp.
View newest version in sPHENIX GitHub at line 104 of file CutoutCylinderVolumeBoundsTests.cpp
References Acts::CutoutCylinderVolumeBounds::inside().
Acts::Test::BOOST_AUTO_TEST_CASE (ConstructState)
Definition at line 105 of file AtlasStepperTests.cpp.
View newest version in sPHENIX GitHub at line 105 of file AtlasStepperTests.cpp
References absMom, charge, CHECK_CLOSE_ABS, eps, geoCtx, magCtx, magneticField, particleHypothesis, pos, pos4(), filter::state, stepSize, time, tolerance, and unitDir.
Acts::Test::BOOST_AUTO_TEST_CASE (ProtoTrackingGeometryTests)
Definition at line 105 of file ProtoDetectorTests.cpp.
View newest version in sPHENIX GitHub at line 105 of file ProtoDetectorTests.cpp
References Acts::arbitrary, Acts::binR, Acts::binZ, CHECK_CLOSE_ABS, Acts::ProtoVolume::container, Acts::ProtoVolume::extent, Acts::ProtoVolume::internal, Acts::Extent::max(), Acts::Extent::min(), Acts::ProtoVolume::name, and physmon_ckf_tracking::u.
Acts::Test::BOOST_AUTO_TEST_CASE (micro_benchmark)
Definition at line 106 of file BenchmarkTools.cpp.
View newest version in sPHENIX GitHub at line 106 of file BenchmarkTools.cpp
References digitization_config::input, and microBenchmark().
Acts::Test::BOOST_AUTO_TEST_CASE (BoundaryCheckTriangleSimple)
Definition at line 107 of file BoundaryCheckTests.cpp.
View newest version in sPHENIX GitHub at line 107 of file BoundaryCheckTests.cpp
References check_fpe_masks::check(), Acts::BoundaryCheck::isInside(), and ActsExamples::HepMC3Event::vertices().
Acts::Test::BOOST_AUTO_TEST_CASE (ConvexPolygonBoundsDynamicTest)
Definition at line 107 of file ConvexPolygonBoundsTests.cpp.
View newest version in sPHENIX GitHub at line 107 of file ConvexPolygonBoundsTests.cpp
References Acts::ConvexPolygonBounds< N >::boundingBox(), Acts::ConvexPolygonBounds< N >::inside(), Acts::RectangleBounds::max(), Acts::RectangleBounds::min(), and ActsExamples::HepMC3Event::vertices().
Acts::Test::BOOST_AUTO_TEST_CASE (DiscTrapezoidBoundsProperties)
Unit tests for DiscTrapezoidBounds properties.
Test clone
Test type() (redundant; already used in constructor confirmation)
Test distanceToBoundary
Test dump
Test inside
Test rMin
Test rMax
Test averagePhi
Test rCenter (redundant; not configurable)
Test halfPhiSector (redundant; not configurable)
Test minHalflengthX
Test maxHalflengthX
Test halflengthY
Definition at line 107 of file DiscTrapezoidBoundsTests.cpp.
View newest version in sPHENIX GitHub at line 107 of file DiscTrapezoidBoundsTests.cpp
References CHECK_CLOSE_REL, CHECK_SMALL, Acts::UnitConstants::e, Acts::DiscTrapezoidBounds::eAveragePhi, Acts::SurfaceBounds::eDiscTrapezoid, Acts::DiscTrapezoidBounds::eHalfLengthXmaxR, Acts::DiscTrapezoidBounds::eHalfLengthXminR, Acts::DiscTrapezoidBounds::get(), Acts::DiscTrapezoidBounds::halfLengthY(), Acts::DiscTrapezoidBounds::inside(), origin(), Acts::DiscTrapezoidBounds::rCenter(), Acts::DiscTrapezoidBounds::rMax(), Acts::DiscTrapezoidBounds::rMin(), Acts::DiscTrapezoidBounds::stereo(), Acts::DiscTrapezoidBounds::toStream(), and Acts::DiscTrapezoidBounds::type().
Acts::Test::BOOST_AUTO_TEST_CASE (shared_vector_helper_test)
Definition at line 107 of file HelpersTests.cpp.
View newest version in sPHENIX GitHub at line 107 of file HelpersTests.cpp
References Acts::unpack_shared_vector(), and vec.
Acts::Test::BOOST_AUTO_TEST_CASE (interpolation_mixed_point_values)
Definition at line 107 of file InterpolationTests.cpp.
View newest version in sPHENIX GitHub at line 107 of file InterpolationTests.cpp
References CHECK_CLOSE_REL, Acts::UnitConstants::e, Acts::interpolate(), merge_hashes::p, and testSigmaEff::v.
Acts::Test::BOOST_AUTO_TEST_CASE (shrink_double)
Definition at line 107 of file Range1DTests.cpp.
View newest version in sPHENIX GitHub at line 107 of file Range1DTests.cpp
References Acts::Range1D< Type >::max(), Acts::Range1D< Type >::min(), physmon_track_finding_ttbar::r, and Acts::Range1D< Type >::shrink().
Acts::Test::BOOST_AUTO_TEST_CASE (EllipseIntersection)
Unit test for creating Ellipse intersection.
Definition at line 109 of file IntersectionHelper2DTests.cpp.
View newest version in sPHENIX GitHub at line 109 of file IntersectionHelper2DTests.cpp
References basicChecks(), CHECK_CLOSE_ABS, Acts::detail::IntersectionHelper2D::intersectEllipse(), ActsTests::PropagationDatasets::pathLength, position, start, ambiguity_solver_full_chain::x, and y.
Acts::Test::BOOST_AUTO_TEST_CASE (kalman_extrapolator)
Unit test for Kalman fitter propagation.
Definition at line 110 of file KalmanExtrapolatorTests.cpp.
View newest version in sPHENIX GitHub at line 110 of file KalmanExtrapolatorTests.cpp
References Acts::IntegrationTest::bField, cfg, cGeometry, CHECK_CLOSE_OR_SMALL, CHECK_CLOSE_REL, cov, Acts::UnitConstants::e, j, Acts::IntegrationTest::mfContext, navigator, Acts::ParticleHypothesis::pion(), Acts::Propagator< stepper_t, navigator_t >::propagate(), start, propagation_timing::stepper, and Acts::tgContext.
Acts::Test::BOOST_AUTO_TEST_CASE (SurfaceMaterialMapper_tests)
Test the filling and conversion.
We need a Navigator, Stepper to build a Propagator
The config object
Create some contexts
Now create the mapper state
Test if this is not null
We need a Navigator, Stepper to build a Propagator
The config object
Create some contexts
Now create the mapper state
Test if this is not null
We need a Navigator, Stepper to build a Propagator
The config object
Create some contexts
Now create the mapper state
Test if this is not null
Definition at line 110 of file SurfaceMaterialMapperTests.cpp.
View newest version in sPHENIX GitHub at line 110 of file SurfaceMaterialMapperTests.cpp
References Acts::SurfaceMaterialMapper::createState(), testing::internal::move(), navigator, propagation_timing::stepper, and physmon_ckf_tracking::u.
Acts::Test::BOOST_AUTO_TEST_CASE (annealing_tool_multiChi2_tests)
Definition at line 111 of file AnnealingUtilityTests.cpp.
View newest version in sPHENIX GitHub at line 111 of file AnnealingUtilityTests.cpp
References Acts::AnnealingUtility::anneal(), filter::config, Acts::AnnealingUtility::State::currentTemperatureIndex, Acts::AnnealingUtility::Config::cutOff, Acts::AnnealingUtility::State::equilibriumReached, Acts::AnnealingUtility::getWeight(), Acts::AnnealingUtility::Config::setOfTemperatures, filter::state, and physmon_ckf_tracking::u.
Acts::Test::BOOST_AUTO_TEST_CASE (EllipseBoundsProperties)
Unit tests for EllipseBounds properties.
Test clone
Test type() (redundant; already used in constructor confirmation)
Test distanceToBoundary
Test rMinX
Test rMinY
Test rMaxX
Test rMaxY
Test averagePhi
Test vertices
Test boundingBox
Test halfPhiSector
Test dump
Test inside
Definition at line 112 of file EllipseBoundsTests.cpp.
View newest version in sPHENIX GitHub at line 112 of file EllipseBoundsTests.cpp
References Acts::EllipseBounds::boundingBox(), Acts::EllipseBounds::eAveragePhi, Acts::SurfaceBounds::eEllipse, Acts::EllipseBounds::eHalfPhiSector, Acts::EllipseBounds::eInnerRx, Acts::EllipseBounds::eInnerRy, Acts::EllipseBounds::eOuterRx, Acts::EllipseBounds::eOuterRy, Acts::EllipseBounds::get(), Acts::EllipseBounds::inside(), origin(), Acts::EllipseBounds::toStream(), and Acts::EllipseBounds::type().
Acts::Test::BOOST_AUTO_TEST_CASE (RectangleBoundsAssignment)
Definition at line 112 of file RectangleBoundsTests.cpp.
View newest version in sPHENIX GitHub at line 112 of file RectangleBoundsTests.cpp
References halfX, halfY, and Acts::RectangleBounds::vertices().
Acts::Test::BOOST_AUTO_TEST_CASE (ClearOnEnter)
Definition at line 113 of file FpeMonitorTests.cpp.
View newest version in sPHENIX GitHub at line 113 of file FpeMonitorTests.cpp
References Acts::FpeMonitor::Result::encountered(), and Acts::FpeMonitor::result().
Acts::Test::BOOST_AUTO_TEST_CASE (billoir_vertex_fitter_defaulttrack_test)
Unit test for FullBilloirVertexFitter with default input track type (= BoundTrackParameters)
Definition at line 113 of file FullBilloirVertexFitterTests.cpp.
View newest version in sPHENIX GitHub at line 113 of file FullBilloirVertexFitterTests.cpp
References Acts::IntegrationTest::bField, CHECK_CLOSE_ABS, filter::Config, d0Dist(), fit(), Acts::Vertex< input_track_t >::fullCovariance(), gen(), geoContext, magFieldContext, testing::internal::move(), nEvents, Acts::UnitConstants::ns, nTracksDist(), origin(), phiDist(), Acts::ParticleHypothesis::pion(), Acts::Vertex< input_track_t >::position(), pTDist(), qDist(), resAngDist(), resIPDist(), resQoPDist(), resTDist(), seed, Acts::Vertex< input_track_t >::setFullCovariance(), Acts::Vertex< input_track_t >::setFullPosition(), filter::state, propagation_timing::stepper, t, tDist(), thetaDist(), tracks(), vTDist(), vXYDist(), vZDist(), ambiguity_solver_full_chain::x, y, physmon_track_finding_ttbar::z, and z0Dist().
Acts::Test::BOOST_AUTO_TEST_CASE (GeometryIdentifier_containervolume_test)
pre-check on GeometryIdentifier
let's check that the geometry ID values are all 0
check the boundaries of the hVolume, should also be 0
let's check everything is set to 0
Definition at line 113 of file TrackingGeometryGeometryIdTests.cpp.
View newest version in sPHENIX GitHub at line 113 of file TrackingGeometryGeometryIdTests.cpp
References hVolume.
Acts::Test::BOOST_AUTO_TEST_CASE (CuboidVolumeBoundarySurfaces)
Definition at line 114 of file CuboidVolumeBoundsTests.cpp.
View newest version in sPHENIX GitHub at line 114 of file CuboidVolumeBoundsTests.cpp
References geoCtx, Acts::CuboidVolumeBounds::inside(), Acts::negativeFaceXY, Acts::negativeFaceYZ, Acts::negativeFaceZX, Acts::CuboidVolumeBounds::orientedSurfaces(), os, Acts::positiveFaceXY, Acts::positiveFaceYZ, and Acts::positiveFaceZX.
Acts::Test::BOOST_AUTO_TEST_CASE (Terminted)
Definition at line 115 of file FiniteStateMachineTests.cpp.
View newest version in sPHENIX GitHub at line 115 of file FiniteStateMachineTests.cpp
Acts::Test::BOOST_AUTO_TEST_CASE (grid_test_2d_equidistant)
Definition at line 115 of file GridTests.cpp.
View newest version in sPHENIX GitHub at line 115 of file GridTests.cpp
References KFPMath::a, KFPMath::b, Acts::UnitConstants::g, Acts::detail::Grid< T, Axes >::globalBinFromLocalBins(), Acts::detail::Grid< T, Axes >::globalBinFromPosition(), Acts::detail::Grid< T, Axes >::localBinsFromGlobalBin(), std::tr1::make_tuple(), testing::internal::move(), Acts::detail::Grid< T, Axes >::numLocalBins(), Acts::detail::Grid< T, Axes >::size(), and physmon_ckf_tracking::u.
Acts::Test::BOOST_AUTO_TEST_CASE (shrink_twice_double)
Definition at line 116 of file Range1DTests.cpp.
View newest version in sPHENIX GitHub at line 116 of file Range1DTests.cpp
References Acts::Range1D< Type >::max(), Acts::Range1D< Type >::min(), physmon_track_finding_ttbar::r, and Acts::Range1D< Type >::shrink().
Acts::Test::BOOST_AUTO_TEST_CASE (BoundaryCheckTriangleCovariance)
Definition at line 116 of file BoundaryCheckTests.cpp.
View newest version in sPHENIX GitHub at line 116 of file BoundaryCheckTests.cpp
References check_fpe_masks::check(), cov, Acts::BoundaryCheck::isInside(), and ActsExamples::HepMC3Event::vertices().
Acts::Test::BOOST_AUTO_TEST_CASE (TypeTraitsMember)
Definition at line 117 of file TypeTraitsTest.cpp.
View newest version in sPHENIX GitHub at line 117 of file TypeTraitsTest.cpp
Acts::Test::BOOST_AUTO_TEST_CASE (iterative_finder_test)
Unit test for IterativeVertexFinder for BoundTrackParameters.
Definition at line 117 of file IterativeVertexFinderTests.cpp.
View newest version in sPHENIX GitHub at line 117 of file IterativeVertexFinderTests.cpp
References parse_cmake_options::begin, Acts::IntegrationTest::bField, cfg, CHECK_CLOSE_ABS, filter::Config, test_fpe::count, d0Dist(), debug, end, Acts::eX, Acts::eY, Acts::eZ, gen(), geoContext, magFieldContext, testing::internal::move(), nEvents, nTracksDist(), nVertexDist(), phiDist(), Acts::ParticleHypothesis::pion(), pos, pTDist(), qDist(), resAngDist(), resIPDist(), resQoPDist(), Acts::Vertex< input_track_t >::setTracksAtVertex(), filter::state, propagation_timing::stepper, thetaDist(), tracks(), vXYDist(), vZDist(), ambiguity_solver_full_chain::x, y, physmon_track_finding_ttbar::z, and z0Dist().
Acts::Test::BOOST_AUTO_TEST_CASE (jacobian_engine_to_bound)
These tests do not test for a correct covariance transport but only for the correct conservation or modification of certain variables. A test suite for the numerical correctness is performed in the integration tests.
Definition at line 118 of file JacobianEngineTests.cpp.
View newest version in sPHENIX GitHub at line 118 of file JacobianEngineTests.cpp
References Acts::detail::anglesToDirectionJacobian(), Acts::detail::boundToBoundTransportJacobian(), Acts::detail::directionToAnglesJacobian(), Acts::detail::freeToBoundTransportJacobian(), Acts::VectorHelpers::phi(), position, pSurface, tgContext, Acts::VectorHelpers::theta(), and time.
Acts::Test::BOOST_AUTO_TEST_CASE (covariance_transport_curvilinear_start)
Definition at line 119 of file CovarianceTransportTests.cpp.
View newest version in sPHENIX GitHub at line 119 of file CovarianceTransportTests.cpp
References Acts::CovarianceCache::applyTransport, Acts::CovarianceCache::atPosition, Acts::CovarianceCache::atSurface, Acts::CovarianceCache::boundToFreeJacobian, Acts::CovarianceCache::covariance, Acts::CovarianceCache::freeToPathDerivatives, Acts::CovarianceCache::freeTransportJacobian, position, tgContext, time, Acts::transportCovarianceToBound(), Acts::transportCovarianceToCurvilinear(), and Acts::transportCovarianceToFree().
Acts::Test::BOOST_AUTO_TEST_CASE (DiamondBoundsAssignment)
Unit test for testing DiamondBounds assignment.
Test operator ==
Test assignment
Definition at line 122 of file DiamondBoundsTests.cpp.
View newest version in sPHENIX GitHub at line 122 of file DiamondBoundsTests.cpp
Acts::Test::BOOST_AUTO_TEST_CASE (TGeoTrd2_yz_to_PlaneSurface)
Unit test to convert a TGeoTrd2 into a Plane.
The TGeoTrd2 has y/z orientation
Definition at line 123 of file TGeoTrd2ConversionTests.cpp.
View newest version in sPHENIX GitHub at line 123 of file TGeoTrd2ConversionTests.cpp
References blue, bounds, CHECK_CLOSE_ABS, Acts::GeometryView3D::drawArrowForward(), Acts::GeometryView3D::drawSurface(), Acts::TrapezoidBounds::eHalfLengthXnegY, Acts::TrapezoidBounds::eHalfLengthXposY, Acts::TrapezoidBounds::eHalfLengthY, green, hy, Acts::UnitConstants::min, offset(), Acts::PrimitivesView3DTest::plane, Acts::Surface::Plane, red, Acts::s_epsilon, tgContext, thickness, Acts::TGeoSurfaceConverter::toSurface(), transform, and Acts::ObjVisualization3D< T >::write().
Acts::Test::BOOST_AUTO_TEST_CASE (CheckRearmCount)
Definition at line 124 of file FpeMonitorTests.cpp.
View newest version in sPHENIX GitHub at line 124 of file FpeMonitorTests.cpp
References Acts::FpeMonitor::Result::count(), Acts::FpeMonitor::Result::deduplicate(), Acts::FpeMonitor::rearm(), Acts::FpeMonitor::result(), and Acts::FpeMonitor::Result::stackTraces().
Acts::Test::BOOST_AUTO_TEST_CASE (FATAL_test)
unit test for FATAL debug level
Definition at line 124 of file LoggerTests.cpp.
View newest version in sPHENIX GitHub at line 124 of file LoggerTests.cpp
References debug_level_test(), and Acts::Logging::FATAL.
Acts::Test::BOOST_AUTO_TEST_CASE (AlignmentContextTests)
Unit test for creating compliant/non-compliant Surface object.
Definition at line 125 of file AlignmentContextTests.cpp.
View newest version in sPHENIX GitHub at line 125 of file AlignmentContextTests.cpp
Acts::Test::BOOST_AUTO_TEST_CASE (shrink_noop_double)
Definition at line 126 of file Range1DTests.cpp.
View newest version in sPHENIX GitHub at line 126 of file Range1DTests.cpp
References Acts::Range1D< Type >::max(), Acts::Range1D< Type >::min(), physmon_track_finding_ttbar::r, and Acts::Range1D< Type >::shrink().
Acts::Test::BOOST_AUTO_TEST_CASE (straight_line_stepper_test)
These tests are aiming to test the functions of the StraightLineStepper The numerical correctness of the stepper is tested in the integration tests
Test the state reset
Repeat with surface related methods
Definition at line 126 of file StraightLineStepperTests.cpp.
View newest version in sPHENIX GitHub at line 126 of file StraightLineStepperTests.cpp
References absMom, Acts::StraightLineStepper::absoluteMomentum(), Acts::GenericBoundTrackParameters< particle_hypothesis_t >::absoluteMomentum(), Acts::ConstrainedStep::actor, Acts::Direction::Backward, Acts::detail::boundState(), Acts::StraightLineStepper::boundState(), charge, Acts::StraightLineStepper::charge(), Acts::GenericBoundTrackParameters< particle_hypothesis_t >::charge(), CHECK_CLOSE_ABS, CHECK_CLOSE_COVARIANCE, CHECK_CLOSE_OR_SMALL, closest(), cov, Acts::StraightLineStepper::State::cov, Acts::GenericBoundTrackParameters< particle_hypothesis_t >::covariance(), Acts::StraightLineStepper::State::covTransport, Acts::GenericBoundTrackParameters< ParticleHypothesis >::create(), Acts::StraightLineStepper::curvilinearState(), Acts::StraightLineStepper::State::derivative, Acts::StraightLineStepper::direction(), Acts::UnitConstants::e, Acts::eFreeDir0, Acts::eFreePos0, Acts::eFreeQOverP, Acts::eFreeTime, eps, Acts::Direction::Forward, Acts::StraightLineStepper::State::geoContext, h, h2, Acts::PlanarHelper::intersect(), Acts::StraightLineStepper::State::jacToGlobal, Acts::StraightLineStepper::State::jacTransport, Acts::VectorHelpers::makeVector4(), mfContext, mockNavigator, navDir, Acts::StraightLineStepper::outputStepSize(), Acts::GenericBoundTrackParameters< particle_hypothesis_t >::parameters(), Acts::StraightLineStepper::State::pathAccumulated, Acts::ParticleHypothesis::pion(), Acts::PrimitivesView3DTest::plane, pos, Acts::GenericCurvilinearTrackParameters< particle_hypothesis_t >::position(), Acts::StraightLineStepper::position(), Acts::StraightLineStepper::State::previousStepSize, Acts::UnitConstants::ps, Acts::GenericBoundTrackParameters< particle_hypothesis_t >::referenceSurface(), Acts::StraightLineStepper::releaseStepSize(), Acts::StraightLineStepper::resetState(), Acts::StraightLineStepper::setStepSize(), Acts::ConstrainedStep::setUser(), Acts::StraightLineStepper::step(), stepSize, Acts::StraightLineStepper::State::stepSize, tgContext, time, Acts::GenericBoundTrackParameters< particle_hypothesis_t >::time(), Acts::StraightLineStepper::time(), tolerance, Acts::StraightLineStepper::State::tolerance, Acts::ConstrainedStep::toString(), Acts::detail::transformBoundToFreeParameters(), Acts::StraightLineStepper::transportCovarianceToBound(), Acts::StraightLineStepper::transportCovarianceToCurvilinear(), Acts::StraightLineStepper::update(), Acts::StraightLineStepper::updateStepSize(), Acts::StraightLineStepper::updateSurfaceStatus(), and Acts::ConstrainedStep::value().
Acts::Test::BOOST_AUTO_TEST_CASE (RadialBoundsAssignment)
Unit test for testing RadialBounds assignment.
Test assignment
Definition at line 127 of file RadialBoundsTests.cpp.
View newest version in sPHENIX GitHub at line 127 of file RadialBoundsTests.cpp
References maxRadius, and minRadius.
Acts::Test::BOOST_AUTO_TEST_CASE (InterpolatedMaterialMap_test)
Definition at line 128 of file InterpolatedMaterialMapTests.cpp.
View newest version in sPHENIX GitHub at line 128 of file InterpolatedMaterialMapTests.cpp
References CHECK_CLOSE_REL, grid(), i, std::tr1::make_tuple(), Acts::InterpolatedMaterialMap< Mapper_t >::material(), testing::internal::move(), and trafoGlobalToLocal().
Acts::Test::BOOST_AUTO_TEST_CASE (ply_test)
Definition at line 128 of file GenericCuboidVolumeBoundsTests.cpp.
View newest version in sPHENIX GitHub at line 128 of file GenericCuboidVolumeBoundsTests.cpp
References Acts::GenericCuboidVolumeBounds::draw(), material_mapping_optimisation::flush, os, and ActsExamples::HepMC3Event::vertices().
Acts::Test::BOOST_AUTO_TEST_CASE (ConstructStateWithCovariance)
Definition at line 129 of file AtlasStepperTests.cpp.
View newest version in sPHENIX GitHub at line 129 of file AtlasStepperTests.cpp
References absMom, charge, CHECK_CLOSE_ABS, cov, eps, geoCtx, magCtx, magneticField, particleHypothesis, pos, pos4(), filter::state, stepSize, time, tolerance, and unitDir.
Acts::Test::BOOST_AUTO_TEST_CASE (ERROR_test)
unit test for ERROR debug level
Definition at line 129 of file LoggerTests.cpp.
View newest version in sPHENIX GitHub at line 129 of file LoggerTests.cpp
References debug_level_test(), and Acts::Logging::ERROR.
Acts::Test::BOOST_AUTO_TEST_CASE (track_density_finder_constr_test)
Unit test for TrackDensityVertexFinder using same configuration and values as VertexSeedFinderTestAlg in Athena implementation.
Definition at line 132 of file TrackDensityVertexFinderTests.cpp.
View newest version in sPHENIX GitHub at line 132 of file TrackDensityVertexFinderTests.cpp
References CHECK_CLOSE_ABS, Acts::GenericBoundTrackParameters< ParticleHypothesis >::create(), Acts::eX, Acts::eY, Acts::eZ, geoContext, magFieldContext, Acts::VectorHelpers::makeVector4(), Acts::ParticleHypothesis::pion(), Acts::Vertex< input_track_t >::setCovariance(), filter::state, and value.
Acts::Test::BOOST_AUTO_TEST_CASE (compare_to_analytical_solution_for_single_track_with_time)
Definition at line 132 of file AdaptiveGridTrackDensityTests.cpp.
View newest version in sPHENIX GitHub at line 132 of file AdaptiveGridTrackDensityTests.cpp
References Acts::AdaptiveGridTrackDensity< spatialTrkGridSize, temporalTrkGridSize >::addTrack(), check_smearing_config::args, cfg, CHECK_CLOSE_OR_SMALL, CHECK_CLOSE_REL, Acts::UnitConstants::e, Acts::AdaptiveGridTrackDensity< spatialTrkGridSize, temporalTrkGridSize >::getBinCenter(), Acts::AdaptiveGridTrackDensity< spatialTrkGridSize, temporalTrkGridSize >::getMaxZTPositionAndWidth(), grid(), it, makeRandomCovariance(), maxZ, Acts::ParticleHypothesis::pion(), small, t, and physmon_track_finding_ttbar::z.
Acts::Test::BOOST_AUTO_TEST_CASE (WARNING_test)
unit test for WARNING debug level
Definition at line 134 of file LoggerTests.cpp.
View newest version in sPHENIX GitHub at line 134 of file LoggerTests.cpp
References debug_level_test(), and Acts::Logging::WARNING.
Acts::Test::BOOST_AUTO_TEST_CASE (shrink_noop_min_double)
Definition at line 136 of file Range1DTests.cpp.
View newest version in sPHENIX GitHub at line 136 of file Range1DTests.cpp
References Acts::Range1D< Type >::max(), Acts::Range1D< Type >::min(), physmon_track_finding_ttbar::r, and Acts::Range1D< Type >::shrink().
Acts::Test::BOOST_AUTO_TEST_CASE (PhiZ_Grid_test)
Various test for the Material in the case of a Cylindrical volume with a 2D grid.
Definition at line 137 of file MaterialGridHelperTests.cpp.
View newest version in sPHENIX GitHub at line 137 of file MaterialGridHelperTests.cpp
References Acts::detail::Grid< T, Axes >::atLocalBins(), Acts::BinUtility::binningData(), Acts::binPhi, Acts::binZ, CHECK_CLOSE_REL, Acts::closed, Acts::createGrid2D(), Acts::detail::Grid< T, Axes >::dimensions(), Acts::UnitConstants::e, Acts::Material::fromMolarDensity(), i, index, Acts::index1, Acts::index2, Acts::index3, Acts::detail::Grid< T, Axes >::localBinsFromLowerLeftEdge(), Acts::mapMaterialPoints(), Acts::detail::Grid< T, Axes >::maxPosition(), Acts::UnitConstants::min, Acts::detail::Grid< T, Axes >::minPosition(), Acts::detail::Grid< T, Axes >::numLocalBins(), Acts::open, Acts::Material::parameters(), and pos.
Acts::Test::BOOST_AUTO_TEST_CASE (INFO_test)
unit test for INFO debug level
Definition at line 139 of file LoggerTests.cpp.
View newest version in sPHENIX GitHub at line 139 of file LoggerTests.cpp
References debug_level_test(), and Acts::Logging::INFO.
Acts::Test::BOOST_AUTO_TEST_CASE (type_collector_test)
Definition at line 139 of file MPLTests.cpp.
View newest version in sPHENIX GitHub at line 139 of file MPLTests.cpp
References Acts::detail::has_action_type_v, Acts::detail::has_result_type_v, Acts::detail::type_collector_t, and value.
Acts::Test::BOOST_AUTO_TEST_CASE (CircleIntersection)
Unit test for creating Circle intersection.
Definition at line 140 of file IntersectionHelper2DTests.cpp.
View newest version in sPHENIX GitHub at line 140 of file IntersectionHelper2DTests.cpp
References basicChecks(), CHECK_CLOSE_ABS, Acts::detail::IntersectionHelper2D::intersectCircle(), ActsTests::PropagationDatasets::pathLength, position, start, ambiguity_solver_full_chain::x, and y.
Acts::Test::BOOST_AUTO_TEST_CASE (CylinderVolumeBoundsAccess)
Definition at line 140 of file CylinderVolumeBoundsTests.cpp.
View newest version in sPHENIX GitHub at line 140 of file CylinderVolumeBoundsTests.cpp
References Acts::CylinderVolumeBounds::eAveragePhi, Acts::CylinderVolumeBounds::eHalfLengthZ, Acts::CylinderVolumeBounds::eHalfPhiSector, Acts::CylinderVolumeBounds::eMaxR, Acts::CylinderVolumeBounds::eMinR, and Acts::CylinderVolumeBounds::get().
Acts::Test::BOOST_AUTO_TEST_CASE (ConeBoundsAssignment)
Definition at line 142 of file ConeBoundsTests.cpp.
View newest version in sPHENIX GitHub at line 142 of file ConeBoundsTests.cpp
References alpha.
Acts::Test::BOOST_AUTO_TEST_CASE (intersect_rays)
Definition at line 142 of file BoundingBoxTest.cpp.
View newest version in sPHENIX GitHub at line 142 of file BoundingBoxTest.cpp
References material_mapping_optimisation::flush, os, merge_hashes::p, and tmp().
Acts::Test::BOOST_AUTO_TEST_CASE (ObjectIntersectionTest)
test of the object intersection class
Definition at line 143 of file IntersectionTests.cpp.
View newest version in sPHENIX GitHub at line 143 of file IntersectionTests.cpp
References physmon_ckf_tracking::u.
Acts::Test::BOOST_AUTO_TEST_CASE (DEBUG_test)
unit test for DEBUG debug level
Definition at line 144 of file LoggerTests.cpp.
View newest version in sPHENIX GitHub at line 144 of file LoggerTests.cpp
References DEBUG, and debug_level_test().
Acts::Test::BOOST_AUTO_TEST_CASE (shrink_noop_max_double)
Definition at line 146 of file Range1DTests.cpp.
View newest version in sPHENIX GitHub at line 146 of file Range1DTests.cpp
References Acts::Range1D< Type >::max(), Acts::Range1D< Type >::min(), physmon_track_finding_ttbar::r, and Acts::Range1D< Type >::shrink().
Acts::Test::BOOST_AUTO_TEST_CASE (intersection_double)
Definition at line 146 of file RangeXDTests.cpp.
View newest version in sPHENIX GitHub at line 146 of file RangeXDTests.cpp
References physmon_track_finding_ttbar::r.
Acts::Test::BOOST_AUTO_TEST_CASE (VectorHelpersPosition)
Definition at line 146 of file HelpersTests.cpp.
View newest version in sPHENIX GitHub at line 146 of file HelpersTests.cpp
References Acts::eFreePos0, Acts::eFreePos1, Acts::eFreePos2, Acts::ePos0, Acts::ePos1, Acts::ePos2, pos4(), and Acts::VectorHelpers::position().
Acts::Test::BOOST_AUTO_TEST_CASE (bounding_box_creation)
Definition at line 147 of file GenericCuboidVolumeBoundsTests.cpp.
View newest version in sPHENIX GitHub at line 147 of file GenericCuboidVolumeBoundsTests.cpp
References Acts::GenericCuboidVolumeBounds::boundingBox(), CHECK_CLOSE_ABS, Acts::UnitConstants::e, physmon_ckf_tracking::u, Acts::GenericCuboidVolumeBounds::values(), and ActsExamples::HepMC3Event::vertices().
Acts::Test::BOOST_AUTO_TEST_CASE (VERBOSE_test)
unit test for VERBOSE debug level
Definition at line 149 of file LoggerTests.cpp.
View newest version in sPHENIX GitHub at line 149 of file LoggerTests.cpp
References debug_level_test(), and VERBOSE.
Acts::Test::BOOST_AUTO_TEST_CASE (Scoping)
Definition at line 152 of file FpeMonitorTests.cpp.
View newest version in sPHENIX GitHub at line 152 of file FpeMonitorTests.cpp
References Acts::FpeMonitor::Result::count(), Acts::FpeMonitor::Result::encountered(), ambiguity_solver_perf::merged, Acts::FpeMonitor::Result::merged(), and Acts::FpeMonitor::result().
Acts::Test::BOOST_AUTO_TEST_CASE (bfield_symmetry)
Definition at line 152 of file BFieldMapUtilsTests.cpp.
View newest version in sPHENIX GitHub at line 152 of file BFieldMapUtilsTests.cpp
References CHECK_CLOSE_REL, Acts::UnitConstants::e, Acts::fieldMapRZ(), Acts::fieldMapXYZ(), i, Acts::VectorHelpers::perp(), pos4(), and vec.
Acts::Test::BOOST_AUTO_TEST_CASE (Getters)
Definition at line 153 of file AtlasStepperTests.cpp.
View newest version in sPHENIX GitHub at line 153 of file AtlasStepperTests.cpp
References absMom, Acts::Test::Stepper::absoluteMomentum(), Acts::Test::Stepper::charge(), charge, CHECK_CLOSE_ABS, cov, Acts::Test::Stepper::direction(), eps, geoCtx, magCtx, magneticField, particleHypothesis, pos, pos4(), Acts::Test::Stepper::position(), filter::state, propagation_timing::stepper, stepSize, Acts::Test::Stepper::time(), time, tolerance, and unitDir.
Acts::Test::BOOST_AUTO_TEST_CASE (open_axis)
Definition at line 153 of file AxesTests.cpp.
View newest version in sPHENIX GitHub at line 153 of file AxesTests.cpp
References KFPMath::a, KFPMath::b, and physmon_ckf_tracking::u.
Acts::Test::BOOST_AUTO_TEST_CASE (PropagatorOptions_)
Definition at line 154 of file PropagatorTests.cpp.
View newest version in sPHENIX GitHub at line 154 of file PropagatorTests.cpp
References Acts::IntegrationTest::mfContext, ckf::options, and Acts::tgContext.
Acts::Test::BOOST_AUTO_TEST_CASE (CylinderSurfacePolyhedrons)
Unit tests for Cylinder Surfaces.
The full cone on one side
The full cone on one side
The full cone on one side
Definition at line 155 of file PolyhedronSurfacesTests.cpp.
View newest version in sPHENIX GitHub at line 155 of file PolyhedronSurfacesTests.cpp
References Acts::binR, Acts::binX, Acts::binY, Acts::binZ, CHECK_CLOSE_ABS, Acts::UnitConstants::e, CKF_timing_vs_mu::mode, physmon_track_finding_ttbar::r, testModes, Acts::tgContext, and transform.
Acts::Test::BOOST_AUTO_TEST_CASE (shrinkMin_noop_double)
Definition at line 156 of file Range1DTests.cpp.
View newest version in sPHENIX GitHub at line 156 of file Range1DTests.cpp
References Acts::Range1D< Type >::max(), Acts::Range1D< Type >::min(), physmon_track_finding_ttbar::r, and Acts::Range1D< Type >::shrinkMin().
Acts::Test::BOOST_AUTO_TEST_CASE (JacobianCurvilinearToGlobalTest)
This tests the jacobian of local curvilinear -> global.
Definition at line 156 of file JacobianTests.cpp.
View newest version in sPHENIX GitHub at line 156 of file JacobianTests.cpp
References cov, Acts::ParticleHypothesis::pion(), and testJacobianToGlobal().
Acts::Test::BOOST_AUTO_TEST_CASE (TypeTraitsNestedType)
Definition at line 157 of file TypeTraitsTest.cpp.
View newest version in sPHENIX GitHub at line 157 of file TypeTraitsTest.cpp
Acts::Test::BOOST_AUTO_TEST_CASE (TGeoTube_to_DiscSurface)
Unit test to convert a TGeoTube into a DiscSurface.
The TGeoTrd1 can only have (x/X)(y/Y) orientation
Definition at line 157 of file TGeoTubeConversionTests.cpp.
View newest version in sPHENIX GitHub at line 157 of file TGeoTubeConversionTests.cpp
References allowedAxes, blue, bounds, CHECK_CLOSE_ABS, Acts::ObjVisualization3D< T >::clear(), Acts::Surface::Disc, Acts::GeometryView3D::drawArrowForward(), Acts::GeometryView3D::drawSurface(), Acts::RadialBounds::eAveragePhi, Acts::RadialBounds::eHalfPhiSector, Acts::RadialBounds::eMaxR, Acts::RadialBounds::eMinR, green, hz, notAllowedAxes, MATSCAN::phimin, red, Acts::s_epsilon, tgContext, thickness, to_string(), Acts::TGeoSurfaceConverter::toSurface(), and Acts::ObjVisualization3D< T >::write().
Acts::Test::BOOST_AUTO_TEST_CASE (BinningData_bins)
x/y/zData check the global position requests
check the local position requests
Definition at line 157 of file BinningDataTests.cpp.
View newest version in sPHENIX GitHub at line 157 of file BinningDataTests.cpp
References Acts::binPhi, Acts::binX, Acts::closed, delta, eta0Position(), etaData_eq, i, nBins_binary, Acts::open, phi0Position(), phiData_eq, phiDelta, phiMin, phiPihPosition(), rData_eq, rphiPosition(), rphizPosition(), Acts::BinningData::search(), Acts::BinningData::searchGlobal(), Acts::BinningData::searchLocal(), valueMin, xData_add(), xData_arb, xData_eq, xData_mult, xyPosition(), xyzPosition(), yData_eq, and zData_eq.
Acts::Test::BOOST_AUTO_TEST_CASE (AccumulatedSurfaceMaterial_variance_0D)
Test the variance.
Definition at line 158 of file AccumulatedSurfaceMaterialTests.cpp.
View newest version in sPHENIX GitHub at line 158 of file AccumulatedSurfaceMaterialTests.cpp
References Acts::AccumulatedSurfaceMaterial::accumulate(), Acts::Material::fromMolarDensity(), Acts::MaterialSlab::thicknessInX0(), and physmon_ckf_tracking::u.
Acts::Test::BOOST_AUTO_TEST_CASE (Arguments)
Definition at line 159 of file FiniteStateMachineTests.cpp.
View newest version in sPHENIX GitHub at line 159 of file FiniteStateMachineTests.cpp
Acts::Test::BOOST_AUTO_TEST_CASE (intersection_false_double)
Definition at line 161 of file RangeXDTests.cpp.
View newest version in sPHENIX GitHub at line 161 of file RangeXDTests.cpp
References physmon_track_finding_ttbar::r.
Acts::Test::BOOST_AUTO_TEST_CASE (VolumeMaterialMapper_comparison_tests)
Test case for comparison between the mapped material and the associated material by propagation.
Definition at line 163 of file VolumeMaterialMapperTests.cpp.
View newest version in sPHENIX GitHub at line 163 of file VolumeMaterialMapperTests.cpp
References Acts::detail::Grid< T, Axes >::atLocalBins(), cfg, CHECK_CLOSE_REL, Acts::createGrid(), Acts::UnitConstants::e, gen(), i, index, Acts::detail::Grid< T, Axes >::localBinsFromLowerLeftEdge(), makeSilicon(), Acts::mapMaterialPoints(), material, Acts::MaterialCollector::this_result::matTrue, Acts::PropagatorPlainOptions::maxSteps, Acts::PropagatorPlainOptions::maxStepSize, testing::internal::move(), Acts::ParticleHypothesis::pion0(), pos, pos4(), Acts::CuboidVolumeBuilder::VolumeConfig::position, Acts::Propagator< stepper_t, navigator_t >::propagate(), rd, Acts::TrackingGeometryBuilder::trackingGeometry(), Acts::Navigator::Config::trackingGeometry, Acts::CuboidVolumeBuilder::trackingVolume(), and Acts::TrackingGeometryBuilder::Config::trackingVolumeBuilders.
Acts::Test::BOOST_AUTO_TEST_CASE (Visualization3DConstruction)
Definition at line 163 of file Visualization3DTests.cpp.
View newest version in sPHENIX GitHub at line 163 of file Visualization3DTests.cpp
Acts::Test::BOOST_AUTO_TEST_CASE (ConeIntersectionTest)
This tests the intersection with cylinders and looks for valid, non-valid, solutions
Definition at line 164 of file SurfaceIntersectionTests.cpp.
View newest version in sPHENIX GitHub at line 164 of file SurfaceIntersectionTests.cpp
References alpha, Acts::aTransform, CHECK_CLOSE_ABS, ActsTests::PropagationDatasets::pathLength, Acts::s_onSurfaceTolerance, utils::status, Acts::tgContext, and transform.
Acts::Test::BOOST_AUTO_TEST_CASE (test_matrix_dimension_switch)
Definition at line 165 of file HelpersTests.cpp.
View newest version in sPHENIX GitHub at line 165 of file HelpersTests.cpp
References i.
Acts::Test::BOOST_AUTO_TEST_CASE (shrinkMax_noop_double)
Definition at line 166 of file Range1DTests.cpp.
View newest version in sPHENIX GitHub at line 166 of file Range1DTests.cpp
References Acts::Range1D< Type >::max(), Acts::Range1D< Type >::min(), physmon_track_finding_ttbar::r, and Acts::Range1D< Type >::shrinkMax().
Acts::Test::BOOST_AUTO_TEST_CASE (DiscTrapezoidBoundsAssignment)
Unit test for testing DiscTrapezoidBounds assignment.
Test assignment
Definition at line 167 of file DiscTrapezoidBoundsTests.cpp.
View newest version in sPHENIX GitHub at line 167 of file DiscTrapezoidBoundsTests.cpp
Acts::Test::BOOST_AUTO_TEST_CASE (UpdateFromBound)
Definition at line 169 of file AtlasStepperTests.cpp.
View newest version in sPHENIX GitHub at line 169 of file AtlasStepperTests.cpp
References absMom, Acts::Test::Stepper::absoluteMomentum(), Acts::Test::Stepper::charge(), charge, CHECK_CLOSE_ABS, cov, Acts::GenericBoundTrackParameters< ParticleHypothesis >::create(), Acts::Test::Stepper::direction(), Acts::eFreeDir0, Acts::eFreeDir1, Acts::eFreeDir2, Acts::eFreePos0, Acts::eFreePos1, Acts::eFreePos2, Acts::eFreeQOverP, Acts::eFreeTime, Acts::eMom0, Acts::eMom1, Acts::eMom2, Acts::ePos0, Acts::ePos1, Acts::ePos2, eps, Acts::eTime, geoCtx, magCtx, magneticField, particleHypothesis, Acts::PrimitivesView3DTest::plane, pos4(), Acts::Test::Stepper::position(), filter::state, propagation_timing::stepper, stepSize, Acts::Test::Stepper::time(), tolerance, and unitDir.
Acts::Test::BOOST_AUTO_TEST_CASE (JacobianCylinderToGlobalTest)
This tests the jacobian of local cylinder -> global.
Definition at line 170 of file JacobianTests.cpp.
View newest version in sPHENIX GitHub at line 170 of file JacobianTests.cpp
References cov, createCylindricTransform(), cSurface, testing::internal::move(), pars, Acts::ParticleHypothesis::pion(), and testJacobianToGlobal().
Acts::Test::BOOST_AUTO_TEST_CASE (NoFit)
Definition at line 171 of file Gx2fTests.cpp.
View newest version in sPHENIX GitHub at line 171 of file Gx2fTests.cpp
References ACTS_INFO, ACTS_LOCAL_LOGGER, calCtx, Acts::Experimental::Gx2FitterExtensions< traj_t >::calibrator, createMeasurements(), conf::extensions, geoCtx, Acts::Test::Detector::geometry, Acts::getDefaultLogger(), gx2fLogger, Acts::MultiTrajectoryTraits::kInvalid, telescope_simulation::logLevel, magCtx, makeParameters(), makeStraightPropagator(), makeToyDetector(), prepareSourceLinks(), resolutions, resPixel, conftest::rng(), Acts::GeometryIdentifier::setVolume(), Acts::Experimental::Gx2FitterExtensions< traj_t >::surfaceAccessor, tracks(), and physmon_ckf_tracking::u.
Acts::Test::BOOST_AUTO_TEST_CASE (CylinderBoundsAssignment)
Unit test for testing CylinderBounds assignment.
Definition at line 174 of file CylinderBoundsTests.cpp.
View newest version in sPHENIX GitHub at line 174 of file CylinderBoundsTests.cpp
References Acts::CylinderBounds::eR, and Acts::CylinderBounds::get().
Acts::Test::BOOST_AUTO_TEST_CASE (CutoutCylinderVolumeBoundsBoundingBox)
Definition at line 174 of file CutoutCylinderVolumeBoundsTests.cpp.
View newest version in sPHENIX GitHub at line 174 of file CutoutCylinderVolumeBoundsTests.cpp
References Acts::CutoutCylinderVolumeBounds::boundingBox(), CHECK_CLOSE_ABS, Acts::UnitConstants::e, Acts::CutoutCylinderVolumeBounds::orientedSurfaces(), and tgContext.
Acts::Test::BOOST_AUTO_TEST_CASE (PlyOutputTest)
Definition at line 176 of file Visualization3DTests.cpp.
View newest version in sPHENIX GitHub at line 176 of file Visualization3DTests.cpp
Acts::Test::BOOST_AUTO_TEST_CASE (intersection_false2_double)
Definition at line 176 of file RangeXDTests.cpp.
View newest version in sPHENIX GitHub at line 176 of file RangeXDTests.cpp
References physmon_track_finding_ttbar::r.
Acts::Test::BOOST_AUTO_TEST_CASE (EllipseBoundsAssignment)
Unit test for testing EllipseBounds assignment.
Test operator ==
Test assignment
Definition at line 176 of file EllipseBoundsTests.cpp.
View newest version in sPHENIX GitHub at line 176 of file EllipseBoundsTests.cpp
Acts::Test::BOOST_AUTO_TEST_CASE (setMin_double)
Definition at line 176 of file Range1DTests.cpp.
View newest version in sPHENIX GitHub at line 176 of file Range1DTests.cpp
References Acts::Range1D< Type >::max(), Acts::Range1D< Type >::min(), physmon_track_finding_ttbar::r, and Acts::Range1D< Type >::setMin().
Acts::Test::BOOST_AUTO_TEST_CASE (LineSurface_assignment_test)
Unit test for testing LineSurface assignment.
Definition at line 178 of file LineSurfaceTests.cpp.
View newest version in sPHENIX GitHub at line 178 of file LineSurfaceTests.cpp
References transform, and translation().
Acts::Test::BOOST_AUTO_TEST_CASE (closed_axis)
Definition at line 178 of file AxesTests.cpp.
View newest version in sPHENIX GitHub at line 178 of file AxesTests.cpp
References KFPMath::a, KFPMath::b, and physmon_ckf_tracking::u.
Acts::Test::BOOST_AUTO_TEST_CASE (covariance_transport_free_start)
Definition at line 180 of file CovarianceTransportTests.cpp.
View newest version in sPHENIX GitHub at line 180 of file CovarianceTransportTests.cpp
References Acts::CovarianceCache::applyTransport, Acts::CovarianceCache::atPosition, Acts::CovarianceCache::atSurface, Acts::CovarianceCache::boundToFreeJacobian, Acts::CovarianceCache::covariance, Acts::CovarianceCache::freeToPathDerivatives, Acts::CovarianceCache::freeTransportJacobian, position, tgContext, time, Acts::transportCovarianceToBound(), Acts::transportCovarianceToCurvilinear(), and Acts::transportCovarianceToFree().
Acts::Test::BOOST_AUTO_TEST_CASE (gaussian_grid_sum_max_densitytest)
Tests the functionality of the useHighestSumZPosition option.
Definition at line 181 of file GaussianGridTrackDensityTests.cpp.
View newest version in sPHENIX GitHub at line 181 of file GaussianGridTrackDensityTests.cpp
References cfg, filter::Config, Acts::UnitConstants::e, grid(), and Acts::ParticleHypothesis::pion().
Acts::Test::BOOST_AUTO_TEST_CASE (CutoutCylinderVolumeOrientedBoundaries)
Definition at line 184 of file CutoutCylinderVolumeBoundsTests.cpp.
View newest version in sPHENIX GitHub at line 184 of file CutoutCylinderVolumeBoundsTests.cpp
References Acts::binR, geoCtx, Acts::CutoutCylinderVolumeBounds::inside(), Acts::CutoutCylinderVolumeBounds::orientedSurfaces(), os, and tgContext.
Acts::Test::BOOST_AUTO_TEST_CASE (setMin_twice_double)
Definition at line 185 of file Range1DTests.cpp.
View newest version in sPHENIX GitHub at line 185 of file Range1DTests.cpp
References Acts::Range1D< Type >::max(), Acts::Range1D< Type >::min(), physmon_track_finding_ttbar::r, and Acts::Range1D< Type >::setMin().
Acts::Test::BOOST_AUTO_TEST_CASE (has_duplicates_test)
Definition at line 186 of file MPLTests.cpp.
View newest version in sPHENIX GitHub at line 186 of file MPLTests.cpp
References Acts::detail::has_duplicates_v.
Acts::Test::BOOST_AUTO_TEST_CASE (eigen_stepper_state_test)
These tests are aiming to test whether the state setup is working properly.
Definition at line 186 of file EigenStepperTests.cpp.
View newest version in sPHENIX GitHub at line 186 of file EigenStepperTests.cpp
References absMom, Acts::IntegrationTest::bField, Acts::EigenStepper< extensionlist_t, auctioneer_t >::charge(), charge(), cov, Acts::VectorHelpers::makeVector4(), Acts::IntegrationTest::mfContext, Acts::ParticleHypothesis::pion(), Acts::ParticleHypothesis::pion0(), pos, stepSize, Acts::tgContext, and time.
Acts::Test::BOOST_AUTO_TEST_CASE (LineSurfaceAlignment)
Unit test for testing LineSurface alignment derivatives.
Definition at line 189 of file LineSurfaceTests.cpp.
View newest version in sPHENIX GitHub at line 189 of file LineSurfaceTests.cpp
References Acts::LineSurface::alignmentToPathDerivative(), CHECK_CLOSE_ABS, Acts::UnitConstants::e, Acts::eFreeDir0, line, Acts::LineSurface::localCartesianToBoundLocalDerivative(), momentum, Dataset::parameters, tgContext, transform, translation(), and value.
Acts::Test::BOOST_AUTO_TEST_CASE (JacobianDiscToGlobalTest)
This tests the jacobian of local disc -> global.
Definition at line 190 of file JacobianTests.cpp.
View newest version in sPHENIX GitHub at line 190 of file JacobianTests.cpp
References cov, createPlanarTransform(), testing::internal::move(), pars, Acts::ParticleHypothesis::pion(), and testJacobianToGlobal().
Acts::Test::BOOST_AUTO_TEST_CASE (IntersectionStatusPrinting)
Definition at line 191 of file IntersectionTests.cpp.
View newest version in sPHENIX GitHub at line 191 of file IntersectionTests.cpp
References i.
Acts::Test::BOOST_AUTO_TEST_CASE (ConeSurfaceEqualityOperators)
Test equality operator
Test assignment
Test equality of assigned to original
Definition at line 194 of file ConeSurfaceTests.cpp.
View newest version in sPHENIX GitHub at line 194 of file ConeSurfaceTests.cpp
References alpha, and translation().
Acts::Test::BOOST_AUTO_TEST_CASE (setMax_double)
Definition at line 195 of file Range1DTests.cpp.
View newest version in sPHENIX GitHub at line 195 of file Range1DTests.cpp
References Acts::Range1D< Type >::max(), Acts::Range1D< Type >::min(), physmon_track_finding_ttbar::r, and Acts::Range1D< Type >::setMax().
Acts::Test::BOOST_AUTO_TEST_CASE (grid_density_vertex_finder_track_caching_test)
Definition at line 197 of file GridDensityVertexFinderTests.cpp.
View newest version in sPHENIX GitHub at line 197 of file GridDensityVertexFinderTests.cpp
References cfg, charge(), CHECK_CLOSE_ABS, filter::Config, Acts::GenericBoundTrackParameters< ParticleHypothesis >::create(), debugMode, eta, etaDist(), Acts::eZ, gen(), geoContext, i, magFieldContext, Acts::makeDirectionFromPhiEta(), Acts::VectorHelpers::makeVector4(), ActsTests::PropagationDatasets::phi, phiDist(), Acts::ParticleHypothesis::pion(), pos, physmon_track_finding_ttbar::pt, pTDist(), value, xdist(), ydist(), z1dist(), z2dist(), zVertexPos1, and zVertexPos2.
Acts::Test::BOOST_AUTO_TEST_CASE (min_max)
Definition at line 197 of file HelpersTests.cpp.
View newest version in sPHENIX GitHub at line 197 of file HelpersTests.cpp
References CHECK_CLOSE_ABS, and Acts::min_max().
Acts::Test::BOOST_AUTO_TEST_CASE (PlaneSurfaceEqualityOperators)
Test equality operator
Test assignment
Test equality of assigned to original
Definition at line 199 of file PlaneSurfaceTests.cpp.
View newest version in sPHENIX GitHub at line 199 of file PlaneSurfaceTests.cpp
References rBounds, and translation().
Acts::Test::BOOST_AUTO_TEST_CASE (jacobian_engine_to_curvilinear)
These tests do not test for a correct covariance transport but only for the correct conservation or modification of certain variables. A test suite for the numerical correctness is performed in the integration tests.
Definition at line 200 of file JacobianEngineTests.cpp.
View newest version in sPHENIX GitHub at line 200 of file JacobianEngineTests.cpp
References Acts::detail::anglesToDirectionJacobian(), Acts::detail::boundToCurvilinearTransportJacobian(), Acts::detail::curvilinearToFreeJacobian(), Acts::detail::directionToAnglesJacobian(), Acts::detail::freeToCurvilinearTransportJacobian(), Acts::VectorHelpers::phi(), position, pSurface, tgContext, Acts::VectorHelpers::theta(), and time.
Acts::Test::BOOST_AUTO_TEST_CASE (any_of_test)
Definition at line 200 of file MPLTests.cpp.
View newest version in sPHENIX GitHub at line 200 of file MPLTests.cpp
References Acts::detail::any_of_v.
Acts::Test::BOOST_AUTO_TEST_CASE (neighborhood)
Definition at line 203 of file AxesTests.cpp.
View newest version in sPHENIX GitHub at line 203 of file AxesTests.cpp
References physmon_ckf_tracking::u.
Acts::Test::BOOST_AUTO_TEST_CASE (Grid_2D_rand)
Definition at line 203 of file ClusterizationTests2D.cpp.
View newest version in sPHENIX GitHub at line 203 of file ClusterizationTests2D.cpp
References clHashComp(), gencluster(), hash(), i, physmon_simulation::rnd, segment(), Acts::Experimental::detail::BlueprintHelper::sort(), and x0.
Acts::Test::BOOST_AUTO_TEST_CASE (setMax_twice_double)
Definition at line 204 of file Range1DTests.cpp.
View newest version in sPHENIX GitHub at line 204 of file Range1DTests.cpp
References Acts::Range1D< Type >::max(), Acts::Range1D< Type >::min(), physmon_track_finding_ttbar::r, and Acts::Range1D< Type >::setMax().
Acts::Test::BOOST_AUTO_TEST_CASE (MergeDeduplication)
Definition at line 204 of file FpeMonitorTests.cpp.
View newest version in sPHENIX GitHub at line 204 of file FpeMonitorTests.cpp
References ambiguity_solver_perf::merged, Acts::FpeMonitor::Result::merged(), and Acts::FpeMonitor::result().
Acts::Test::BOOST_AUTO_TEST_CASE (GeometryIdentifier_closeGeometry_test_extra)
Definition at line 207 of file TrackingGeometryClosureTests.cpp.
View newest version in sPHENIX GitHub at line 207 of file TrackingGeometryClosureTests.cpp
References Acts::BinnedArray< T >::arrayObjects(), Acts::TrackingVolume::boundarySurfaces(), Acts::TrackingVolume::confinedLayers(), Acts::GeometryObject::geometryId(), Acts::TrackingGeometry::highestTrackingVolume(), makeTrackingGeometry(), Acts::GeometryIdentifier::setExtra(), Acts::tGeometry, and Acts::GeometryIdentifier::volume().
Acts::Test::BOOST_AUTO_TEST_CASE (TrapezoidBoundsAssignment)
Unit test for testing TrapezoidBounds assignment.
Test assignment
Definition at line 208 of file TrapezoidBoundsTests.cpp.
View newest version in sPHENIX GitHub at line 208 of file TrapezoidBoundsTests.cpp
References halfY.
Acts::Test::BOOST_AUTO_TEST_CASE (GenericCuboidVolumeBoundarySurfaces)
Definition at line 209 of file GenericCuboidVolumeBoundsTests.cpp.
View newest version in sPHENIX GitHub at line 209 of file GenericCuboidVolumeBoundsTests.cpp
References geoCtx, Acts::GenericCuboidVolumeBounds::inside(), Acts::GenericCuboidVolumeBounds::orientedSurfaces(), os, and ActsExamples::HepMC3Event::vertices().
Acts::Test::BOOST_AUTO_TEST_CASE (JacobianPlaneToGlobalTest)
This tests the jacobian of local plane -> global.
Definition at line 211 of file JacobianTests.cpp.
View newest version in sPHENIX GitHub at line 211 of file JacobianTests.cpp
References cov, testing::internal::move(), pars, Acts::ParticleHypothesis::pion(), pSurface, and testJacobianToGlobal().
Acts::Test::BOOST_AUTO_TEST_CASE (range_medium)
Definition at line 211 of file HelpersTests.cpp.
View newest version in sPHENIX GitHub at line 211 of file HelpersTests.cpp
References CHECK_CLOSE_ABS, and Acts::range_medium().
Acts::Test::BOOST_AUTO_TEST_CASE (ProtoDetectorTests)
Definition at line 212 of file ProtoDetectorTests.cpp.
View newest version in sPHENIX GitHub at line 212 of file ProtoDetectorTests.cpp
Acts::Test::BOOST_AUTO_TEST_CASE (UpdateFromComponents)
Definition at line 213 of file AtlasStepperTests.cpp.
View newest version in sPHENIX GitHub at line 213 of file AtlasStepperTests.cpp
References absMom, Acts::Test::Stepper::absoluteMomentum(), Acts::Test::Stepper::charge(), charge, CHECK_CLOSE_ABS, cov, Acts::Test::Stepper::direction(), eps, geoCtx, magCtx, magneticField, particleHypothesis, pos, pos4(), Acts::Test::Stepper::position(), filter::state, propagation_timing::stepper, stepSize, Acts::Test::Stepper::time(), time, tolerance, and unitDir.
Acts::Test::BOOST_AUTO_TEST_CASE (expandMin_double)
Definition at line 214 of file Range1DTests.cpp.
View newest version in sPHENIX GitHub at line 214 of file Range1DTests.cpp
References Acts::Range1D< Type >::expandMin(), Acts::Range1D< Type >::max(), Acts::Range1D< Type >::min(), and physmon_track_finding_ttbar::r.
Acts::Test::BOOST_AUTO_TEST_CASE (PlanarIntersectionTest)
This tests the intersection with planar surfaces (plane, disk) as those share the same PlanarHelper methods, only one test is sufficient
it looks for valid, non-valid, solutions
Forward intersection test
Definition at line 214 of file SurfaceIntersectionTests.cpp.
View newest version in sPHENIX GitHub at line 214 of file SurfaceIntersectionTests.cpp
References aPlane, Acts::aTransform, halfX, halfY, ActsTests::PropagationDatasets::pathLength, Acts::s_onSurfaceTolerance, utils::status, Acts::tgContext, and transform.
Acts::Test::BOOST_AUTO_TEST_CASE (zscan_finder_usertrack_test)
Unit test for ZScanVertexFinder with user-defined input track type.
Definition at line 216 of file ZScanVertexFinderTests.cpp.
View newest version in sPHENIX GitHub at line 216 of file ZScanVertexFinderTests.cpp
References Acts::IntegrationTest::bField, cfg, CHECK_CLOSE_ABS, filter::Config, d0Dist(), Acts::eZ, gen(), geoContext, magFieldContext, testing::internal::move(), phiDist(), Acts::ParticleHypothesis::pion(), pTDist(), qDist(), resAngDist(), resIPDist(), resQoPDist(), filter::state, propagation_timing::stepper, thetaDist(), tracks(), vXYDist(), vZDist(), ambiguity_solver_full_chain::x, y, physmon_track_finding_ttbar::z, and z0Dist().
Acts::Test::BOOST_AUTO_TEST_CASE (ScopedSuppression)
Definition at line 217 of file FpeMonitorTests.cpp.
View newest version in sPHENIX GitHub at line 217 of file FpeMonitorTests.cpp
References Acts::FpeMonitor::Result::count(), Acts::FpeMonitor::Result::encountered(), and Acts::FpeMonitor::result().
Acts::Test::BOOST_AUTO_TEST_CASE (ConeSurfaceExtent)
Definition at line 218 of file ConeSurfaceTests.cpp.
View newest version in sPHENIX GitHub at line 218 of file ConeSurfaceTests.cpp
References alpha, Acts::binR, Acts::binX, Acts::binY, Acts::binZ, CHECK_CLOSE_ABS, Acts::s_onSurfaceTolerance, tgContext, and translation().
Acts::Test::BOOST_AUTO_TEST_CASE (adaptive_multi_vertex_finder_usertype_test)
AMVF test with user-defined input track type.
Definition at line 222 of file AdaptiveMultiVertexFinderTests.cpp.
View newest version in sPHENIX GitHub at line 222 of file AdaptiveMultiVertexFinderTests.cpp
References bField, CHECK_CLOSE_ABS, filter::Config, test_fpe::count, covariance(), debugMode, geoContext, i, magFieldContext, testing::internal::move(), position, readTracksAndVertexCSV(), Acts::Vertex< input_track_t >::setCovariance(), Acts::AnnealingUtility::Config::setOfTemperatures, Acts::Vertex< input_track_t >::setPosition(), filter::state, propagation_timing::stepper, toolString, and tracks().
Acts::Test::BOOST_AUTO_TEST_CASE (expandMax_double)
Definition at line 223 of file Range1DTests.cpp.
View newest version in sPHENIX GitHub at line 223 of file Range1DTests.cpp
References Acts::Range1D< Type >::expandMax(), Acts::Range1D< Type >::max(), Acts::Range1D< Type >::min(), and physmon_track_finding_ttbar::r.
Acts::Test::BOOST_AUTO_TEST_CASE (track_density_finder_random_test)
Unit test for TrackDensityVertexFinder using same configuration and values as VertexSeedFinderTestAlg in Athena implementation.
Definition at line 223 of file TrackDensityVertexFinderTests.cpp.
View newest version in sPHENIX GitHub at line 223 of file TrackDensityVertexFinderTests.cpp
References charge(), CHECK_CLOSE_ABS, Acts::GenericBoundTrackParameters< ParticleHypothesis >::create(), eta, etaDist(), Acts::eZ, gen(), geoContext, i, magFieldContext, Acts::makeDirectionFromPhiEta(), Acts::VectorHelpers::makeVector4(), ActsTests::PropagationDatasets::phi, phiDist(), Acts::ParticleHypothesis::pion(), pos, physmon_track_finding_ttbar::pt, pTDist(), filter::state, value, xdist(), ydist(), z1dist(), z2dist(), and zVertexPos.
Acts::Test::BOOST_AUTO_TEST_CASE (PlaneSurfaceExtent)
Unit test for testing PlaneSurface extent via Polyhedron representation.
Definition at line 223 of file PlaneSurfaceTests.cpp.
View newest version in sPHENIX GitHub at line 223 of file PlaneSurfaceTests.cpp
References alpha, Acts::binR, Acts::binX, Acts::binY, Acts::binZ, CHECK_CLOSE_ABS, Acts::PrimitivesView3DTest::plane, rBounds, Acts::s_onSurfaceTolerance, and tgContext.
Acts::Test::BOOST_AUTO_TEST_CASE (DiscSurfaceAssignment)
Unit test for testing DiscSurface assignment and equality.
Definition at line 224 of file DiscSurfaceTests.cpp.
View newest version in sPHENIX GitHub at line 224 of file DiscSurfaceTests.cpp
Acts::Test::BOOST_AUTO_TEST_CASE (BinningData_inside_outside)
Definition at line 224 of file BinningDataTests.cpp.
View newest version in sPHENIX GitHub at line 224 of file BinningDataTests.cpp
References Acts::binPhi, Acts::binX, Acts::closed, delta, eta0Position(), etaData_eq, i, Acts::BinningData::inside(), nBins_binary, Acts::open, phi0Position(), phiData_eq, phiDelta, phiMin, phiPihPosition(), rphizPosition(), valueMin, xData_add(), xData_arb, xData_eq, xData_mult, xyPosition(), xyzPosition(), xyzPositionOutside(), yData_eq, and zData_eq.
Acts::Test::BOOST_AUTO_TEST_CASE (safeInverse)
Definition at line 225 of file HelpersTests.cpp.
View newest version in sPHENIX GitHub at line 225 of file HelpersTests.cpp
References Acts::UnitConstants::m, and Acts::safeInverse().
Acts::Test::BOOST_AUTO_TEST_CASE (DiscSurfacePolyhedrons)
Unit tests for Disc Surfaces.
Definition at line 226 of file PolyhedronSurfacesTests.cpp.
View newest version in sPHENIX GitHub at line 226 of file PolyhedronSurfacesTests.cpp
References Acts::binR, Acts::binX, Acts::binY, Acts::binZ, CHECK_CLOSE_ABS, Acts::UnitConstants::e, maxPhi, maxRadius, minPhi, minRadius, CKF_timing_vs_mu::mode, offset, testModes, Acts::tgContext, and transform.
Acts::Test::BOOST_AUTO_TEST_CASE (CylinderSurfaceEqualityOperators)
Test equality operator
Test assignment
Test equality of assigned to original
Definition at line 227 of file CylinderSurfaceTests.cpp.
View newest version in sPHENIX GitHub at line 227 of file CylinderSurfaceTests.cpp
References translation().
Acts::Test::BOOST_AUTO_TEST_CASE (Cubic_Grid_test)
Various test for the Material in the case of a Cuboid volume.
Definition at line 228 of file MaterialGridHelperTests.cpp.
View newest version in sPHENIX GitHub at line 228 of file MaterialGridHelperTests.cpp
References Acts::detail::Grid< T, Axes >::atLocalBins(), Acts::BinUtility::binningData(), Acts::binX, Acts::binY, Acts::binZ, CHECK_CLOSE_REL, Acts::createGrid3D(), Acts::detail::Grid< T, Axes >::dimensions(), Acts::UnitConstants::e, Acts::Material::fromMolarDensity(), i, index, Acts::index1, Acts::index2, Acts::index3, Acts::detail::Grid< T, Axes >::localBinsFromLowerLeftEdge(), Acts::mapMaterialPoints(), Acts::detail::Grid< T, Axes >::maxPosition(), Acts::UnitConstants::min, Acts::detail::Grid< T, Axes >::minPosition(), Acts::detail::Grid< T, Axes >::numLocalBins(), Acts::open, Acts::Material::parameters(), and pos.
Acts::Test::BOOST_AUTO_TEST_CASE (TypeTraitsConcepts)
Definition at line 228 of file TypeTraitsTest.cpp.
View newest version in sPHENIX GitHub at line 228 of file TypeTraitsTest.cpp
Acts::Test::BOOST_AUTO_TEST_CASE (LineSurfaceTransformRoundTrip)
Definition at line 229 of file LineSurfaceTests.cpp.
View newest version in sPHENIX GitHub at line 229 of file LineSurfaceTests.cpp
References CHECK_CLOSE_ABS, Acts::ObjectMultiIntersection< object_t, representation_t >::closest(), Acts::UnitConstants::e, Acts::LineSurface::globalToLocal(), Acts::LineSurface::intersect(), Acts::LineSurface::localToGlobal(), std::tr1::make_tuple(), pos, writeMapConfig::surface, and tgContext.
Acts::Test::BOOST_AUTO_TEST_CASE (expand_both_double)
Definition at line 232 of file Range1DTests.cpp.
View newest version in sPHENIX GitHub at line 232 of file Range1DTests.cpp
References Acts::Range1D< Type >::expandMax(), Acts::Range1D< Type >::expandMin(), Acts::Range1D< Type >::max(), Acts::Range1D< Type >::min(), and physmon_track_finding_ttbar::r.
Acts::Test::BOOST_AUTO_TEST_CASE (CylinderVolumeBoundsBoundingBox)
Definition at line 232 of file CylinderVolumeBoundsTests.cpp.
View newest version in sPHENIX GitHub at line 232 of file CylinderVolumeBoundsTests.cpp
References Acts::CylinderVolumeBounds::boundingBox(), CHECK_CLOSE_ABS, Acts::UnitConstants::e, and tgContext.
Acts::Test::BOOST_AUTO_TEST_CASE (seed_width_estimation)
Definition at line 233 of file AdaptiveGridTrackDensityTests.cpp.
View newest version in sPHENIX GitHub at line 233 of file AdaptiveGridTrackDensityTests.cpp
References cfg, Acts::AdaptiveGridTrackDensity< spatialTrkGridSize, temporalTrkGridSize >::getBinCenter(), Acts::AdaptiveGridTrackDensity< spatialTrkGridSize, temporalTrkGridSize >::getMaxZTPositionAndWidth(), grid(), i, and maxZ.
Acts::Test::BOOST_AUTO_TEST_CASE (JacobianPerigeeToGlobalTest)
This tests the jacobian of local perigee -> global.
Definition at line 234 of file JacobianTests.cpp.
View newest version in sPHENIX GitHub at line 234 of file JacobianTests.cpp
References cov, testing::internal::move(), pars, Acts::ParticleHypothesis::pion(), pSurface, and testJacobianToGlobal().
Acts::Test::BOOST_AUTO_TEST_CASE (BuildBound)
Definition at line 235 of file AtlasStepperTests.cpp.
View newest version in sPHENIX GitHub at line 235 of file AtlasStepperTests.cpp
References absMom, charge, CHECK_CLOSE_ABS, cov, eps, geoCtx, magCtx, magneticField, pars, particleHypothesis, ActsTests::PropagationDatasets::pathLength, Acts::PrimitivesView3DTest::plane, pos, pos4(), filter::state, propagation_timing::stepper, stepSize, time, tolerance, and unitDir.
Acts::Test::BOOST_AUTO_TEST_CASE (eigen_stepper_test)
These tests are aiming to test the functions of the EigenStepper The numerical correctness of the stepper is tested in the integration tests
Test the state reset
Repeat with surface related methods
Definition at line 235 of file EigenStepperTests.cpp.
View newest version in sPHENIX GitHub at line 235 of file EigenStepperTests.cpp
References absMom, Acts::EigenStepper< extensionlist_t, auctioneer_t >::absoluteMomentum(), Acts::ConstrainedStep::actor, Acts::Direction::Backward, Acts::IntegrationTest::bCache, Acts::IntegrationTest::bField, Acts::detail::boundState(), Acts::EigenStepper< extensionlist_t, auctioneer_t >::boundState(), Acts::EigenStepper< extensionlist_t, auctioneer_t >::charge(), Acts::GenericBoundTrackParameters< particle_hypothesis_t >::charge(), charge(), CHECK_CLOSE_ABS, CHECK_CLOSE_COVARIANCE, CHECK_CLOSE_OR_SMALL, CHECK_CLOSE_REL, closest(), cov, Acts::EigenStepper< extensionlist_t, auctioneer_t >::State::cov, Acts::GenericBoundTrackParameters< particle_hypothesis_t >::covariance(), Acts::EigenStepper< extensionlist_t, auctioneer_t >::State::covTransport, Acts::GenericBoundTrackParameters< ParticleHypothesis >::create(), Acts::EigenStepper< extensionlist_t, auctioneer_t >::curvilinearState(), Acts::EigenStepper< extensionlist_t, auctioneer_t >::State::derivative, Acts::EigenStepper< extensionlist_t, auctioneer_t >::direction(), Acts::UnitConstants::e, Acts::eFreeDir0, Acts::eFreePos0, Acts::eFreeQOverP, Acts::eFreeTime, eps, ckf::field, Acts::Direction::Forward, Acts::EigenStepper< extensionlist_t, auctioneer_t >::getField(), Acts::PlanarHelper::intersect(), Acts::EigenStepper< extensionlist_t, auctioneer_t >::State::jacToGlobal, Acts::EigenStepper< extensionlist_t, auctioneer_t >::State::jacTransport, Acts::VectorHelpers::makeVector4(), Acts::IntegrationTest::mfContext, mockNavigator, Acts::GenericBoundTrackParameters< particle_hypothesis_t >::momentum(), testing::internal::move(), navDir, Acts::Test::PropState< stepper_state_t >::options, Acts::EigenStepper< extensionlist_t, auctioneer_t >::outputStepSize(), Acts::GenericBoundTrackParameters< particle_hypothesis_t >::parameters(), Acts::EigenStepper< extensionlist_t, auctioneer_t >::State::pathAccumulated, Acts::ParticleHypothesis::pion(), Acts::PrimitivesView3DTest::plane, pos, Acts::GenericCurvilinearTrackParameters< particle_hypothesis_t >::position(), Acts::EigenStepper< extensionlist_t, auctioneer_t >::position(), Acts::EigenStepper< extensionlist_t, auctioneer_t >::State::previousStepSize, Acts::UnitConstants::ps, Acts::GenericBoundTrackParameters< particle_hypothesis_t >::referenceSurface(), Acts::EigenStepper< extensionlist_t, auctioneer_t >::releaseStepSize(), Acts::EigenStepper< extensionlist_t, auctioneer_t >::resetState(), Acts::EigenStepper< extensionlist_t, auctioneer_t >::setStepSize(), filter::state, Acts::EigenStepper< extensionlist_t, auctioneer_t >::step(), Acts::Test::PropState< stepper_state_t >::stepping, stepSize, Acts::EigenStepper< extensionlist_t, auctioneer_t >::State::stepSize, Acts::tgContext, time, Acts::GenericBoundTrackParameters< particle_hypothesis_t >::time(), Acts::EigenStepper< extensionlist_t, auctioneer_t >::time(), Acts::Test::PropState< stepper_state_t >::tolerance, Acts::detail::transformBoundToFreeParameters(), Acts::EigenStepper< extensionlist_t, auctioneer_t >::transportCovarianceToBound(), Acts::EigenStepper< extensionlist_t, auctioneer_t >::transportCovarianceToCurvilinear(), Acts::EigenStepper< extensionlist_t, auctioneer_t >::update(), Acts::EigenStepper< extensionlist_t, auctioneer_t >::updateStepSize(), Acts::EigenStepper< extensionlist_t, auctioneer_t >::updateSurfaceStatus(), and Acts::ConstrainedStep::value().
Acts::Test::BOOST_AUTO_TEST_CASE (are_sorted_helper_tests)
Unit test for Acts::anonymous_namespace{ParameterSet.h}are_sorted helper.
The test checks for correct behavior in the following cases (always using int as value type):
test: ordered strictly ascending, input: ordered strictly ascending
test: ordered strictly ascending, input: unordered
test: ordered strictly ascending, input: ordered weakly ascending
test: ordered weakly ascending, input: ordered strictly ascending
test: ordered weakly ascending, input: unordered
test: ordered weakly ascending, input: ordered weakly ascending
test: ordered strictly descending, input: ordered strictly descending
test: ordered strictly descending, input: unordered
test: ordered strictly descending, input: ordered weakly descending
test: ordered weakly descending, input: ordered strictly descending
test: ordered weakly descending, input: unordered
test: ordered weakly descending, input: ordered weakly descending
Definition at line 235 of file MPLTests.cpp.
View newest version in sPHENIX GitHub at line 235 of file MPLTests.cpp
Acts::Test::BOOST_AUTO_TEST_CASE (incidentAnglesTest)
Definition at line 237 of file HelpersTests.cpp.
View newest version in sPHENIX GitHub at line 237 of file HelpersTests.cpp
References CHECK_CLOSE_ABS, expect(), i, Acts::VectorHelpers::incidentAngles(), and check_smearing_config::ref.
Acts::Test::BOOST_AUTO_TEST_CASE (DiscSurfaceExtent)
Unit test for testing DiscSurface assignment and equality.
Definition at line 237 of file DiscSurfaceTests.cpp.
View newest version in sPHENIX GitHub at line 237 of file DiscSurfaceTests.cpp
References Acts::binPhi, Acts::binR, Acts::binX, Acts::binY, Acts::binZ, CHECK_CLOSE_ABS, Acts::s_onSurfaceTolerance, and tgContext.
Acts::Test::BOOST_AUTO_TEST_CASE (Fit5Iterations)
Definition at line 238 of file Gx2fTests.cpp.
View newest version in sPHENIX GitHub at line 238 of file Gx2fTests.cpp
References ACTS_DEBUG, ACTS_INFO, ACTS_LOCAL_LOGGER, Acts::ACTS_VERBOSE(), createMeasurements(), Acts::UnitConstants::e, Acts::eBoundLoc0, Acts::eBoundLoc1, Acts::eBoundPhi, Acts::eBoundQOverP, Acts::eBoundTheta, Acts::eBoundTime, conf::extensions, geoCtx, Acts::Test::Detector::geometry, Acts::getDefaultLogger(), gx2fLogger, telescope_simulation::logLevel, magCtx, makeParameters(), makeStraightPropagator(), makeToyDetector(), Acts::IntegrationTest::mfContext, prepareSourceLinks(), resolutions, resPixel, conftest::rng(), Acts::GeometryIdentifier::setVolume(), tracks(), and physmon_ckf_tracking::u.
Acts::Test::BOOST_AUTO_TEST_CASE (expand_double)
Definition at line 242 of file Range1DTests.cpp.
View newest version in sPHENIX GitHub at line 242 of file Range1DTests.cpp
References Acts::Range1D< Type >::expand(), Acts::Range1D< Type >::max(), Acts::Range1D< Type >::min(), and physmon_track_finding_ttbar::r.
Acts::Test::BOOST_AUTO_TEST_CASE (gaussian_grid_seed_width_test)
Tests the seed width.
Definition at line 244 of file GaussianGridTrackDensityTests.cpp.
View newest version in sPHENIX GitHub at line 244 of file GaussianGridTrackDensityTests.cpp
References cfg, filter::Config, Acts::UnitConstants::e, grid(), Acts::ParticleHypothesis::pion(), width, and physmon_track_finding_ttbar::z.
Acts::Test::BOOST_AUTO_TEST_CASE (SurfaceArray_singleElement)
Definition at line 250 of file SurfaceArrayTests.cpp.
View newest version in sPHENIX GitHub at line 250 of file SurfaceArrayTests.cpp
References bounds, h, and physmon_ckf_tracking::u.
Acts::Test::BOOST_AUTO_TEST_CASE (CylinderSurfaceExtent)
Unit test for testing CylinderSurface properties.
Definition at line 251 of file CylinderSurfaceTests.cpp.
View newest version in sPHENIX GitHub at line 251 of file CylinderSurfaceTests.cpp
References Acts::binR, Acts::binX, Acts::binY, Acts::binZ, CHECK_CLOSE_ABS, Acts::s_onSurfaceTolerance, testContext, and translation().
Acts::Test::BOOST_AUTO_TEST_CASE (expand_twice_double)
Definition at line 251 of file Range1DTests.cpp.
View newest version in sPHENIX GitHub at line 251 of file Range1DTests.cpp
References Acts::Range1D< Type >::expand(), Acts::Range1D< Type >::max(), Acts::Range1D< Type >::min(), and physmon_track_finding_ttbar::r.
Acts::Test::BOOST_AUTO_TEST_CASE (JacobianStrawToGlobalTest)
This tests the jacobian of local straw -> global.
Definition at line 252 of file JacobianTests.cpp.
View newest version in sPHENIX GitHub at line 252 of file JacobianTests.cpp
References cov, createCylindricTransform(), testing::internal::move(), pars, Acts::ParticleHypothesis::pion(), sTransform, and testJacobianToGlobal().
Acts::Test::BOOST_AUTO_TEST_CASE (InternalTransitions)
Definition at line 252 of file FiniteStateMachineTests.cpp.
View newest version in sPHENIX GitHub at line 252 of file FiniteStateMachineTests.cpp
Acts::Test::BOOST_AUTO_TEST_CASE (ConeSurfaceAlignment)
Unit test for testing ConeSurface alignment derivatives.
Define the track (global) position and direction
Definition at line 253 of file ConeSurfaceTests.cpp.
View newest version in sPHENIX GitHub at line 253 of file ConeSurfaceTests.cpp
References alpha, CHECK_CLOSE_ABS, Acts::UnitConstants::e, tgContext, and translation().
Acts::Test::BOOST_AUTO_TEST_CASE (LineSurfaceTransformRoundTripEtaStability)
Definition at line 259 of file LineSurfaceTests.cpp.
View newest version in sPHENIX GitHub at line 259 of file LineSurfaceTests.cpp
References CHECK_CLOSE_ABS, Acts::ObjectMultiIntersection< object_t, representation_t >::closest(), Acts::UnitConstants::e, eta, etas, Acts::LineSurface::globalToLocal(), Acts::LineSurface::intersect(), Acts::LineSurface::localToGlobal(), Acts::makeDirectionFromPhiEta(), pos, writeMapConfig::surface, and tgContext.
Acts::Test::BOOST_AUTO_TEST_CASE (BuildCurvilinear)
Definition at line 260 of file AtlasStepperTests.cpp.
View newest version in sPHENIX GitHub at line 260 of file AtlasStepperTests.cpp
References absMom, charge, CHECK_CLOSE_ABS, cov, eps, geoCtx, magCtx, magneticField, pars, particleHypothesis, ActsTests::PropagationDatasets::pathLength, pos, pos4(), filter::state, propagation_timing::stepper, stepSize, time, tolerance, and unitDir.
Acts::Test::BOOST_AUTO_TEST_CASE (expand_noop_double)
Definition at line 261 of file Range1DTests.cpp.
View newest version in sPHENIX GitHub at line 261 of file Range1DTests.cpp
References Acts::Range1D< Type >::expand(), Acts::Range1D< Type >::max(), Acts::Range1D< Type >::min(), and physmon_track_finding_ttbar::r.
Acts::Test::BOOST_AUTO_TEST_CASE (CopyBehaviour)
Definition at line 261 of file ResultTests.cpp.
View newest version in sPHENIX GitHub at line 261 of file ResultTests.cpp
References make_nocopy(), testing::internal::move(), n, Acts::Test::NoCopy::num, and value.
Acts::Test::BOOST_AUTO_TEST_CASE (SurfaceArray_manyElementsSingleLookup)
Definition at line 264 of file SurfaceArrayTests.cpp.
View newest version in sPHENIX GitHub at line 264 of file SurfaceArrayTests.cpp
References bounds, h, testing::internal::move(), and physmon_ckf_tracking::u.
Acts::Test::BOOST_AUTO_TEST_CASE (BinningData_open_close)
Definition at line 267 of file BinningDataTests.cpp.
View newest version in sPHENIX GitHub at line 267 of file BinningDataTests.cpp
References Acts::binPhi, Acts::BinningData::bins(), Acts::binX, Acts::closed, delta, i, nBins_binary, Acts::open, phiData_arb, phiData_eq, phiDelta, phiMin, Acts::BinningData::search(), Acts::BinningData::searchGlobal(), valueMin, xData_arb, xData_eq, xyzPositionOutside(), yData_arb, yData_eq, and zData_eq.
Acts::Test::BOOST_AUTO_TEST_CASE (track_adding)
Definition at line 269 of file AdaptiveGridTrackDensityTests.cpp.
View newest version in sPHENIX GitHub at line 269 of file AdaptiveGridTrackDensityTests.cpp
References Acts::AdaptiveGridTrackDensity< spatialTrkGridSize, temporalTrkGridSize >::addTrack(), cfg, grid(), and Acts::ParticleHypothesis::pion().
Acts::Test::BOOST_AUTO_TEST_CASE (jacobian_engine_to_free)
These tests do not test for a correct covariance transport but only for the correct conservation or modification of certain variables. A test suite for the numerical correctness is performed in the integration tests.
Definition at line 270 of file JacobianEngineTests.cpp.
View newest version in sPHENIX GitHub at line 270 of file JacobianEngineTests.cpp
References Acts::detail::boundToFreeTransportJacobian(), Acts::detail::curvilinearToFreeJacobian(), Acts::VectorHelpers::phi(), position, pSurface, tgContext, Acts::VectorHelpers::theta(), and time.
Acts::Test::BOOST_AUTO_TEST_CASE (DiscSurfaceAlignment)
Unit test for testing DiscSurface alignment derivatives.
Definition at line 270 of file DiscSurfaceTests.cpp.
View newest version in sPHENIX GitHub at line 270 of file DiscSurfaceTests.cpp
References CHECK_CLOSE_ABS, Acts::UnitConstants::e, Acts::eFreeDir0, momentum, Dataset::parameters, tgContext, transform, and translation().
Acts::Test::BOOST_AUTO_TEST_CASE (expand_noop_min_double)
Definition at line 271 of file Range1DTests.cpp.
View newest version in sPHENIX GitHub at line 271 of file Range1DTests.cpp
References Acts::Range1D< Type >::expand(), Acts::Range1D< Type >::max(), Acts::Range1D< Type >::min(), and physmon_track_finding_ttbar::r.
Acts::Test::BOOST_AUTO_TEST_CASE (are_within_helper_tests)
Unit test for Acts::anonymous_namespace{ParameterSet.h}are_within helper.
The test checks for correct behavior in the following cases (always using int as value type):
all values within (MIN,MAX)
all values within [MIN,MAX)
one value < MIN
multiple values < MIN
one value > MAX
multiple values > Max
one value == MAX
contains values < MIN and >= MAX
Definition at line 271 of file MPLTests.cpp.
View newest version in sPHENIX GitHub at line 271 of file MPLTests.cpp
Acts::Test::BOOST_AUTO_TEST_CASE (PlaneSurfaceAlignment)
Unit test for testing PlaneSurface alignment derivatives.
Definition at line 273 of file PlaneSurfaceTests.cpp.
View newest version in sPHENIX GitHub at line 273 of file PlaneSurfaceTests.cpp
References CHECK_CLOSE_ABS, Acts::UnitConstants::e, Acts::eAlignmentCenter0, Acts::eBoundLoc0, Acts::eBoundLoc1, Acts::eFreeDir0, momentum, Dataset::parameters, rBounds, tgContext, and translation().
Acts::Test::BOOST_AUTO_TEST_CASE (CylinderSurfaceAlignment)
Unit test for testing CylinderSurface alignment derivatives.
Define the track (global) position and direction
Definition at line 273 of file CylinderSurfaceTests.cpp.
View newest version in sPHENIX GitHub at line 273 of file CylinderSurfaceTests.cpp
References CHECK_CLOSE_ABS, Acts::UnitConstants::e, testContext, and translation().
Acts::Test::BOOST_AUTO_TEST_CASE (CylinderVolumeOrientedBoundaries)
Definition at line 280 of file CylinderVolumeBoundsTests.cpp.
View newest version in sPHENIX GitHub at line 280 of file CylinderVolumeBoundsTests.cpp
References Acts::binR, geoCtx, Acts::CylinderVolumeBounds::inside(), Acts::CylinderVolumeBounds::orientedSurfaces(), os, and tgContext.
Acts::Test::BOOST_AUTO_TEST_CASE (expand_noop_max_double)
Definition at line 281 of file Range1DTests.cpp.
View newest version in sPHENIX GitHub at line 281 of file Range1DTests.cpp
References Acts::Range1D< Type >::expand(), Acts::Range1D< Type >::max(), Acts::Range1D< Type >::min(), and physmon_track_finding_ttbar::r.
Acts::Test::BOOST_AUTO_TEST_CASE (LineSurfaceIntersection)
Definition at line 281 of file LineSurfaceTests.cpp.
View newest version in sPHENIX GitHub at line 281 of file LineSurfaceTests.cpp
References Acts::Direction::Backward, CHECK_CLOSE_ABS, closest(), Acts::UnitConstants::e, eps, Acts::Direction::Forward, ckf::options, Acts::VectorHelpers::phi(), Acts::ParticleHypothesis::pion(), writeMapConfig::surface, tgContext, and Acts::VectorHelpers::theta().
Acts::Test::BOOST_AUTO_TEST_CASE (Step)
Definition at line 283 of file AtlasStepperTests.cpp.
View newest version in sPHENIX GitHub at line 283 of file AtlasStepperTests.cpp
References absMom, Acts::Test::Stepper::absoluteMomentum(), Acts::Test::Stepper::charge(), charge, CHECK_CLOSE_ABS, cov, Acts::AtlasStepper::State::covTransport, Acts::Test::Stepper::direction(), eps, geoCtx, h, magCtx, magneticField, navDir, navigator, particleHypothesis, pos, pos4(), Acts::Test::Stepper::position(), filter::state, propagation_timing::stepper, Acts::Test::MockPropagatorState::stepping, stepSize, Acts::AtlasStepper::State::stepSize, Acts::Test::Stepper::time(), time, tolerance, unitDir, and Acts::ConstrainedStep::value().
Acts::Test::BOOST_AUTO_TEST_CASE (at_index_helper_tests)
Unit test for Acts::details::at_index helper.
Definition at line 286 of file MPLTests.cpp.
View newest version in sPHENIX GitHub at line 286 of file MPLTests.cpp
Acts::Test::BOOST_AUTO_TEST_CASE (grid_test_3d_equidistant)
Definition at line 288 of file GridTests.cpp.
View newest version in sPHENIX GitHub at line 288 of file GridTests.cpp
References KFPMath::a, KFPMath::b, Acts::PhysicalConstants::c, Acts::UnitConstants::g, Acts::detail::Grid< T, Axes >::globalBinFromLocalBins(), Acts::detail::Grid< T, Axes >::globalBinFromPosition(), Acts::detail::Grid< T, Axes >::localBinsFromGlobalBin(), std::tr1::make_tuple(), testing::internal::move(), Acts::detail::Grid< T, Axes >::numLocalBins(), Acts::detail::Grid< T, Axes >::size(), and physmon_ckf_tracking::u.
Acts::Test::BOOST_AUTO_TEST_CASE (expandMin_noop_double)
Definition at line 291 of file Range1DTests.cpp.
View newest version in sPHENIX GitHub at line 291 of file Range1DTests.cpp
References Acts::Range1D< Type >::expandMin(), Acts::Range1D< Type >::max(), Acts::Range1D< Type >::min(), and physmon_track_finding_ttbar::r.
Acts::Test::BOOST_AUTO_TEST_CASE (ObjOutputTest)
Definition at line 295 of file Visualization3DTests.cpp.
View newest version in sPHENIX GitHub at line 295 of file Visualization3DTests.cpp
Acts::Test::BOOST_AUTO_TEST_CASE (VoidResult)
Definition at line 298 of file ResultTests.cpp.
View newest version in sPHENIX GitHub at line 298 of file ResultTests.cpp
References void_res_func().
Acts::Test::BOOST_AUTO_TEST_CASE (BinningData_boundaries)
Definition at line 299 of file BinningDataTests.cpp.
View newest version in sPHENIX GitHub at line 299 of file BinningDataTests.cpp
References Acts::BinningData::boundaries(), CHECK_CLOSE_REL, Acts::UnitConstants::e, phiData_eq, and xData_eq.
Acts::Test::BOOST_AUTO_TEST_CASE (CylinderSurfaceBinningPosition)
Definition at line 300 of file CylinderSurfaceTests.cpp.
View newest version in sPHENIX GitHub at line 300 of file CylinderSurfaceTests.cpp
References KFPMath::b, Acts::binEta, Acts::binH, Acts::binMag, Acts::binR, Acts::binRPhi, Acts::binX, Acts::binY, Acts::binZ, bounds, CHECK_CLOSE_ABS, Acts::UnitConstants::e, Acts::VectorHelpers::perp(), Acts::VectorHelpers::phi(), physmon_track_finding_ttbar::r, physmon_simulation::s, and testContext.
Acts::Test::BOOST_AUTO_TEST_CASE (expandMax_noop_double)
Definition at line 301 of file Range1DTests.cpp.
View newest version in sPHENIX GitHub at line 301 of file Range1DTests.cpp
References Acts::Range1D< Type >::expandMax(), Acts::Range1D< Type >::max(), Acts::Range1D< Type >::min(), and physmon_track_finding_ttbar::r.
Acts::Test::BOOST_AUTO_TEST_CASE (LineIntersectionTest)
This tests the intersection with line like surfaces (straw, perigee) as those share the same methods, only one test is sufficient
it looks for valid, non-valid, solutions
Forward intersection test
Definition at line 303 of file SurfaceIntersectionTests.cpp.
View newest version in sPHENIX GitHub at line 303 of file SurfaceIntersectionTests.cpp
References Acts::aTransform, ActsTests::PropagationDatasets::pathLength, Acts::s_onSurfaceTolerance, utils::status, Acts::tgContext, and transform.
Acts::Test::BOOST_AUTO_TEST_CASE (TrackingGeometry_testVisitSurfaces)
Definition at line 307 of file TrackingGeometryClosureTests.cpp.
View newest version in sPHENIX GitHub at line 307 of file TrackingGeometryClosureTests.cpp
References makeTrackingGeometry(), Acts::tGeometry, physmon_ckf_tracking::u, and Acts::TrackingGeometry::visitSurfaces().
Acts::Test::BOOST_AUTO_TEST_CASE (track_density_finder_usertrack_test)
Unit test for TrackDensityVertexFinder with user-defined input track type with same values as in other tests.
Definition at line 307 of file TrackDensityVertexFinderTests.cpp.
View newest version in sPHENIX GitHub at line 307 of file TrackDensityVertexFinderTests.cpp
References CHECK_CLOSE_ABS, Acts::GenericBoundTrackParameters< ParticleHypothesis >::create(), Acts::eX, Acts::eY, Acts::eZ, geoContext, magFieldContext, Acts::VectorHelpers::makeVector4(), Acts::ParticleHypothesis::pion(), Acts::Vertex< input_track_t >::setCovariance(), filter::state, and value.
Acts::Test::BOOST_AUTO_TEST_CASE (size_double)
Definition at line 311 of file Range1DTests.cpp.
View newest version in sPHENIX GitHub at line 311 of file Range1DTests.cpp
References physmon_track_finding_ttbar::r, and Acts::Range1D< Type >::size().
Acts::Test::BOOST_AUTO_TEST_CASE (DiscSurfaceBinningPosition)
Definition at line 312 of file DiscSurfaceTests.cpp.
View newest version in sPHENIX GitHub at line 312 of file DiscSurfaceTests.cpp
References KFPMath::b, Acts::binEta, Acts::binH, Acts::binMag, Acts::binPhi, Acts::binR, Acts::binRPhi, Acts::binX, Acts::binY, Acts::binZ, bounds, Acts::RadialBounds::eAveragePhi, Acts::AnnulusBounds::eAveragePhi, maxR, minR, origin(), Acts::VectorHelpers::perp(), ActsTests::PropagationDatasets::phi, Acts::VectorHelpers::phi(), physmon_track_finding_ttbar::r, physmon_simulation::s, and tgContext.
Acts::Test::BOOST_AUTO_TEST_CASE (size_zero_double)
Definition at line 317 of file Range1DTests.cpp.
View newest version in sPHENIX GitHub at line 317 of file Range1DTests.cpp
References physmon_track_finding_ttbar::r, and Acts::Range1D< Type >::size().
Acts::Test::BOOST_AUTO_TEST_CASE (StepWithCovariance)
Definition at line 317 of file AtlasStepperTests.cpp.
View newest version in sPHENIX GitHub at line 317 of file AtlasStepperTests.cpp
References absMom, Acts::Test::Stepper::absoluteMomentum(), Acts::Test::Stepper::charge(), charge, CHECK_CLOSE_ABS, cov, Acts::AtlasStepper::State::cov, Acts::AtlasStepper::State::covTransport, Acts::Test::Stepper::direction(), eps, geoCtx, h, magCtx, magneticField, navDir, navigator, particleHypothesis, pos, pos4(), Acts::Test::Stepper::position(), filter::state, propagation_timing::stepper, Acts::Test::MockPropagatorState::stepping, stepSize, Acts::AtlasStepper::State::stepSize, Acts::Test::Stepper::time(), time, tolerance, unitDir, and Acts::ConstrainedStep::value().
Acts::Test::BOOST_AUTO_TEST_CASE (BinningData_bincenter)
check the global position requests
Definition at line 318 of file BinningDataTests.cpp.
View newest version in sPHENIX GitHub at line 318 of file BinningDataTests.cpp
References Acts::binPhi, Acts::binX, Acts::BinningData::center(), CHECK_CLOSE_ABS, Acts::closed, delta, Acts::UnitConstants::e, i, add_histos_bX::ib, nBins_binary, Acts::open, phiData_eq, phiDelta, phiMin, valueMin, xData_add(), xData_arb, xData_eq, and xData_mult.
Acts::Test::BOOST_AUTO_TEST_CASE (Cylindrical_Grid_test)
Various test for the Material in the case of a Cylindrical volume.
Definition at line 322 of file MaterialGridHelperTests.cpp.
View newest version in sPHENIX GitHub at line 322 of file MaterialGridHelperTests.cpp
References Acts::detail::Grid< T, Axes >::atLocalBins(), Acts::BinUtility::binningData(), Acts::binPhi, Acts::binR, Acts::binZ, CHECK_CLOSE_REL, Acts::closed, Acts::createGrid3D(), Acts::detail::Grid< T, Axes >::dimensions(), Acts::UnitConstants::e, Acts::Material::fromMolarDensity(), i, index, Acts::index1, Acts::index2, Acts::index3, Acts::detail::Grid< T, Axes >::localBinsFromLowerLeftEdge(), Acts::mapMaterialPoints(), Acts::detail::Grid< T, Axes >::maxPosition(), Acts::UnitConstants::min, Acts::detail::Grid< T, Axes >::minPosition(), Acts::detail::Grid< T, Axes >::numLocalBins(), Acts::open, Acts::Material::parameters(), and pos.
Acts::Test::BOOST_AUTO_TEST_CASE (BoolResult)
Definition at line 323 of file ResultTests.cpp.
View newest version in sPHENIX GitHub at line 323 of file ResultTests.cpp
Acts::Test::BOOST_AUTO_TEST_CASE (size_zero2_double)
Definition at line 323 of file Range1DTests.cpp.
View newest version in sPHENIX GitHub at line 323 of file Range1DTests.cpp
References physmon_track_finding_ttbar::r, and Acts::Range1D< Type >::size().
Acts::Test::BOOST_AUTO_TEST_CASE (wrapBin)
Definition at line 323 of file AxesTests.cpp.
View newest version in sPHENIX GitHub at line 323 of file AxesTests.cpp
References KFPMath::a2, and physmon_ckf_tracking::u.
Acts::Test::BOOST_AUTO_TEST_CASE (max_z_t_and_width)
Definition at line 328 of file AdaptiveGridTrackDensityTests.cpp.
View newest version in sPHENIX GitHub at line 328 of file AdaptiveGridTrackDensityTests.cpp
References Acts::AdaptiveGridTrackDensity< spatialTrkGridSize, temporalTrkGridSize >::addTrack(), CHECK_CLOSE_OR_SMALL, Acts::UnitConstants::e, Acts::AdaptiveGridTrackDensity< spatialTrkGridSize, temporalTrkGridSize >::getMaxZTPosition(), Acts::AdaptiveGridTrackDensity< spatialTrkGridSize, temporalTrkGridSize >::getMaxZTPositionAndWidth(), and Acts::ParticleHypothesis::pion().
Acts::Test::BOOST_AUTO_TEST_CASE (degenerate_false_double)
Definition at line 329 of file Range1DTests.cpp.
View newest version in sPHENIX GitHub at line 329 of file Range1DTests.cpp
References Acts::Range1D< Type >::degenerate(), and physmon_track_finding_ttbar::r.
Acts::Test::BOOST_AUTO_TEST_CASE (Navigator_status_methods)
Definition at line 331 of file NavigatorTests.cpp.
View newest version in sPHENIX GitHub at line 331 of file NavigatorTests.cpp
References Acts::TrackingVolume::associatedLayer(), Acts::Surface::center(), debug, Acts::ePos0, momentum, navigator, Acts::Test::PropagatorState::Stepper::position(), Acts::Navigator::Config::resolveMaterial, Acts::Navigator::Config::resolvePassive, Acts::Navigator::Config::resolveSensitive, filter::state, propagation_timing::stepper, testNavigatorStatePointers(), testNavigatorStateVectors(), Acts::tGeometry, Acts::Navigator::Config::trackingGeometry, and physmon_ckf_tracking::u.
Acts::Test::BOOST_AUTO_TEST_CASE (MixedDetector)
Definition at line 332 of file Gx2fTests.cpp.
View newest version in sPHENIX GitHub at line 332 of file Gx2fTests.cpp
References ACTS_DEBUG, ACTS_INFO, ACTS_LOCAL_LOGGER, Acts::ACTS_VERBOSE(), createMeasurements(), Acts::UnitConstants::e, Acts::eBoundLoc0, Acts::eBoundLoc1, Acts::eBoundPhi, Acts::eBoundQOverP, Acts::eBoundTheta, Acts::eBoundTime, conf::extensions, geoCtx, Acts::Test::Detector::geometry, Acts::getDefaultLogger(), gx2fLogger, telescope_simulation::logLevel, magCtx, makeParameters(), makeStraightPropagator(), makeToyDetector(), Acts::IntegrationTest::mfContext, prepareSourceLinks(), resolutions, resPixel, conftest::rng(), Acts::GeometryIdentifier::setLayer(), Acts::GeometryIdentifier::setVolume(), tracks(), and physmon_ckf_tracking::u.
Acts::Test::BOOST_AUTO_TEST_CASE (degenerate_true_double)
Definition at line 335 of file Range1DTests.cpp.
View newest version in sPHENIX GitHub at line 335 of file Range1DTests.cpp
References Acts::Range1D< Type >::degenerate(), and physmon_track_finding_ttbar::r.
Acts::Test::BOOST_AUTO_TEST_CASE (iterative_finder_test_user_track_type)
Unit test for IterativeVertexFinder for user defined InputTrack track type.
Definition at line 338 of file IterativeVertexFinderTests.cpp.
View newest version in sPHENIX GitHub at line 338 of file IterativeVertexFinderTests.cpp
References parse_cmake_options::begin, Acts::IntegrationTest::bField, cfg, CHECK_CLOSE_ABS, filter::Config, test_fpe::count, d0Dist(), debug, end, Acts::eX, Acts::eY, Acts::eZ, gen(), geoContext, magFieldContext, testing::internal::move(), nEvents, nTracksDist(), nVertexDist(), phiDist(), Acts::ParticleHypothesis::pion(), pos, pTDist(), qDist(), resAngDist(), resIPDist(), resQoPDist(), Acts::Vertex< input_track_t >::setTracksAtVertex(), filter::state, propagation_timing::stepper, thetaDist(), tracks(), vXYDist(), vZDist(), ambiguity_solver_full_chain::x, y, physmon_track_finding_ttbar::z, and z0Dist().
Acts::Test::BOOST_AUTO_TEST_CASE (contains_double)
Definition at line 341 of file Range1DTests.cpp.
View newest version in sPHENIX GitHub at line 341 of file Range1DTests.cpp
References Acts::Range1D< Type >::contains(), and physmon_track_finding_ttbar::r.
Acts::Test::BOOST_AUTO_TEST_CASE (adaptive_multi_vertex_fitter_test_athena)
Unit test for AdaptiveMultiVertexFitter based on Athena unit test, i.e. same setting and test values are used here.
Definition at line 342 of file AdaptiveMultiVertexFitterTests.cpp.
View newest version in sPHENIX GitHub at line 342 of file AdaptiveMultiVertexFitterTests.cpp
References Acts::AdaptiveMultiVertexFitter< input_track_t, linearizer_t >::State::addVertexToMultiMap(), Acts::AdaptiveMultiVertexFitter< input_track_t, linearizer_t >::Config::annealingTool, bField, CHECK_CLOSE_ABS, filter::Config, Acts::GenericBoundTrackParameters< ParticleHypothesis >::create(), debugMode, Acts::UnitConstants::e, Acts::AdaptiveMultiVertexFitter< input_track_t, linearizer_t >::fit(), geoContext, i, magFieldContext, Acts::VectorHelpers::makeVector4(), testing::internal::move(), Acts::ParticleHypothesis::pion(), Acts::Vertex< input_track_t >::setFitQuality(), Acts::Vertex< input_track_t >::setFullCovariance(), Acts::AnnealingUtility::Config::setOfTemperatures, filter::state, propagation_timing::stepper, Acts::AdaptiveMultiVertexFitter< input_track_t, linearizer_t >::State::tracksAtVerticesMap, value, Acts::AdaptiveMultiVertexFitter< input_track_t, linearizer_t >::State::vertexCollection, and Acts::AdaptiveMultiVertexFitter< input_track_t, linearizer_t >::State::vtxInfoMap.
Acts::Test::BOOST_AUTO_TEST_CASE (contains_degenerate_double)
Definition at line 351 of file Range1DTests.cpp.
View newest version in sPHENIX GitHub at line 351 of file Range1DTests.cpp
References Acts::Range1D< Type >::contains(), and physmon_track_finding_ttbar::r.
Acts::Test::BOOST_AUTO_TEST_CASE (Reset)
Definition at line 354 of file AtlasStepperTests.cpp.
View newest version in sPHENIX GitHub at line 354 of file AtlasStepperTests.cpp
References absMom, Acts::Test::Stepper::absoluteMomentum(), parse_cmake_options::begin, Acts::Test::Stepper::charge(), charge, CHECK_NE_COLLECTIONS, cov, Acts::GenericBoundTrackParameters< particle_hypothesis_t >::covariance(), Acts::AtlasStepper::State::covariance, Acts::AtlasStepper::State::covTransport, Acts::GenericBoundTrackParameters< ParticleHypothesis >::create(), Acts::Test::Stepper::direction(), Acts::eFreeDir0, Acts::eFreePos0, Acts::eFreeQOverP, Acts::eFreeTime, end, ckf::field, Acts::Direction::Forward, geoCtx, magCtx, magneticField, Acts::VectorHelpers::makeVector4(), navDir, navigator, Acts::GenericBoundTrackParameters< particle_hypothesis_t >::parameters(), Acts::AtlasStepper::State::parameters, particleHypothesis, Acts::AtlasStepper::State::pathAccumulated, pos4(), Acts::Test::Stepper::position(), Acts::AtlasStepper::State::previousStepSize, Acts::AtlasStepper::State::pVector, Acts::GenericBoundTrackParameters< particle_hypothesis_t >::referenceSurface(), filter::state, propagation_timing::stepper, Acts::Test::MockPropagatorState::stepping, stepSize, Acts::AtlasStepper::State::stepSize, Acts::Test::Stepper::time(), tolerance, Acts::AtlasStepper::State::tolerance, Acts::detail::transformBoundToFreeParameters(), unitDir, and Acts::ConstrainedStep::value().
Acts::Test::BOOST_AUTO_TEST_CASE (intersect_true1_double)
Definition at line 361 of file Range1DTests.cpp.
View newest version in sPHENIX GitHub at line 361 of file Range1DTests.cpp
References physmon_track_finding_ttbar::r.
Acts::Test::BOOST_AUTO_TEST_CASE (adaptive_multi_vertex_finder_grid_seed_finder_test)
AMVF test with grid seed finder.
Definition at line 363 of file AdaptiveMultiVertexFinderTests.cpp.
View newest version in sPHENIX GitHub at line 363 of file AdaptiveMultiVertexFinderTests.cpp
References bField, CHECK_CLOSE_ABS, filter::Config, test_fpe::count, debugMode, geoContext, i, magFieldContext, testing::internal::move(), position, readTracksAndVertexCSV(), Acts::AnnealingUtility::Config::setOfTemperatures, filter::state, propagation_timing::stepper, ambiguity_solver_full_chain::t1, ambiguity_solver_full_chain::t2, toolString, and tracks().
Acts::Test::BOOST_AUTO_TEST_CASE (grid_density_vertex_finder_seed_width_test)
Unit test for GridDensityVertexFinder with seed with estimation.
Definition at line 364 of file GridDensityVertexFinderTests.cpp.
View newest version in sPHENIX GitHub at line 364 of file GridDensityVertexFinderTests.cpp
References charge(), CHECK_CLOSE_ABS, filter::Config, cov, Acts::Vertex< input_track_t >::covariance(), Acts::GenericBoundTrackParameters< ParticleHypothesis >::create(), debugMode, Acts::UnitConstants::e, eta, etaDist(), Acts::eZ, gen(), geoContext, i, magFieldContext, Acts::makeDirectionFromPhiEta(), Acts::VectorHelpers::makeVector4(), ActsTests::PropagationDatasets::phi, phiDist(), Acts::ParticleHypothesis::pion(), pos, physmon_track_finding_ttbar::pt, pTDist(), Acts::Vertex< input_track_t >::setCovariance(), value, xdist(), ydist(), and z1dist().
Acts::Test::BOOST_AUTO_TEST_CASE (intersect_true2_double)
Definition at line 368 of file Range1DTests.cpp.
View newest version in sPHENIX GitHub at line 368 of file Range1DTests.cpp
References physmon_track_finding_ttbar::r.
Acts::Test::BOOST_AUTO_TEST_CASE (BinningData_phi_modules)
Definition at line 368 of file BinningDataTests.cpp.
View newest version in sPHENIX GitHub at line 368 of file BinningDataTests.cpp
References Acts::binPhi, Acts::BinningData::boundaries(), CHECK_CLOSE_REL, Acts::closed, deltaPhi(), Acts::UnitConstants::e, Acts::BinningData::search(), and Acts::BinningData::searchGlobal().
Acts::Test::BOOST_AUTO_TEST_CASE (intersect_true3_double)
Definition at line 375 of file Range1DTests.cpp.
View newest version in sPHENIX GitHub at line 375 of file Range1DTests.cpp
References physmon_track_finding_ttbar::r.
Acts::Test::BOOST_AUTO_TEST_CASE (PlaneSurfacePolyhedrons)
Unit tests for Plane Surfaces.
Rectangular Plane
Trapezoidal Plane
Ring-like ellispoidal Plane
ConvextPolygonBounds test
Diamond shaped plane
Definition at line 379 of file PolyhedronSurfacesTests.cpp.
View newest version in sPHENIX GitHub at line 379 of file PolyhedronSurfacesTests.cpp
References Acts::binR, Acts::binX, Acts::binY, Acts::binZ, CHECK_CLOSE_ABS, Acts::UnitConstants::e, CKF_timing_vs_mu::mode, testModes, Acts::tgContext, and transform.
Acts::Test::BOOST_AUTO_TEST_CASE (intersect_false1_double)
Definition at line 382 of file Range1DTests.cpp.
View newest version in sPHENIX GitHub at line 382 of file Range1DTests.cpp
References physmon_track_finding_ttbar::r.
Acts::Test::BOOST_AUTO_TEST_CASE (intersect_false2_double)
Definition at line 389 of file Range1DTests.cpp.
View newest version in sPHENIX GitHub at line 389 of file Range1DTests.cpp
References physmon_track_finding_ttbar::r.
Acts::Test::BOOST_AUTO_TEST_CASE (equals_true_int)
Definition at line 396 of file Range1DTests.cpp.
View newest version in sPHENIX GitHub at line 396 of file Range1DTests.cpp
References physmon_track_finding_ttbar::r.
Acts::Test::BOOST_AUTO_TEST_CASE (ray_obb_intersect)
Definition at line 399 of file BoundingBoxTest.cpp.
View newest version in sPHENIX GitHub at line 399 of file BoundingBoxTest.cpp
References Acts::PlyVisualization3D< T >::clear(), Acts::Ray< value_t, DIM >::draw(), Acts::AxisAlignedBoundingBox< entity_t, value_t, DIM >::draw(), norm, Acts::Volume::orientedBoundingBox(), origin(), Acts::Ray< value_t, DIM >::transformed(), and ActsExamples::HepMC3Event::vertices().
Acts::Test::BOOST_AUTO_TEST_CASE (equals_false_int)
Definition at line 403 of file Range1DTests.cpp.
View newest version in sPHENIX GitHub at line 403 of file Range1DTests.cpp
References physmon_track_finding_ttbar::r.
Acts::Test::BOOST_AUTO_TEST_CASE (subset1_double)
Definition at line 410 of file Range1DTests.cpp.
View newest version in sPHENIX GitHub at line 410 of file Range1DTests.cpp
References physmon_track_finding_ttbar::r.
Acts::Test::BOOST_AUTO_TEST_CASE (highest_density_sum)
Definition at line 416 of file AdaptiveGridTrackDensityTests.cpp.
View newest version in sPHENIX GitHub at line 416 of file AdaptiveGridTrackDensityTests.cpp
References Acts::AdaptiveGridTrackDensity< spatialTrkGridSize, temporalTrkGridSize >::addTrack(), cfg, Acts::AdaptiveGridTrackDensity< spatialTrkGridSize, temporalTrkGridSize >::getMaxZTPosition(), grid(), Acts::ParticleHypothesis::pion(), and Acts::AdaptiveGridTrackDensity< spatialTrkGridSize, temporalTrkGridSize >::Config::useHighestSumZPosition.
Acts::Test::BOOST_AUTO_TEST_CASE (subset2_double)
Definition at line 418 of file Range1DTests.cpp.
View newest version in sPHENIX GitHub at line 418 of file Range1DTests.cpp
References physmon_track_finding_ttbar::r.
Acts::Test::BOOST_AUTO_TEST_CASE (subset3_double)
Definition at line 426 of file Range1DTests.cpp.
View newest version in sPHENIX GitHub at line 426 of file Range1DTests.cpp
References physmon_track_finding_ttbar::r.
Acts::Test::BOOST_AUTO_TEST_CASE (subset4_double)
Definition at line 434 of file Range1DTests.cpp.
View newest version in sPHENIX GitHub at line 434 of file Range1DTests.cpp
References physmon_track_finding_ttbar::r.
Acts::Test::BOOST_AUTO_TEST_CASE (subset5_double)
Definition at line 442 of file Range1DTests.cpp.
View newest version in sPHENIX GitHub at line 442 of file Range1DTests.cpp
References physmon_track_finding_ttbar::r.
Acts::Test::BOOST_AUTO_TEST_CASE (grid_test_1d_variable)
Definition at line 446 of file GridTests.cpp.
View newest version in sPHENIX GitHub at line 446 of file GridTests.cpp
References KFPMath::a, Acts::UnitConstants::g, std::tr1::make_tuple(), testing::internal::move(), and physmon_ckf_tracking::u.
Acts::Test::BOOST_AUTO_TEST_CASE (superset1_double)
Definition at line 450 of file Range1DTests.cpp.
View newest version in sPHENIX GitHub at line 450 of file Range1DTests.cpp
References physmon_track_finding_ttbar::r.
Acts::Test::BOOST_AUTO_TEST_CASE (Navigator_target_methods)
Definition at line 456 of file NavigatorTests.cpp.
View newest version in sPHENIX GitHub at line 456 of file NavigatorTests.cpp
References CHECK_CLOSE_ABS, debug, grid(), momentum, navigator, Acts::VectorHelpers::perp(), Acts::Navigator::Config::resolveMaterial, Acts::Navigator::Config::resolvePassive, Acts::Navigator::Config::resolveSensitive, Acts::s_onSurfaceTolerance, filter::state, step, propagation_timing::stepper, Acts::tGeometry, Acts::toString(), Acts::Test::CubicBVHTrackingGeometry::trackingGeometry, Acts::Navigator::Config::trackingGeometry, and physmon_ckf_tracking::u.
Acts::Test::BOOST_AUTO_TEST_CASE (superset2_double)
Definition at line 458 of file Range1DTests.cpp.
View newest version in sPHENIX GitHub at line 458 of file Range1DTests.cpp
References physmon_track_finding_ttbar::r.
Acts::Test::BOOST_AUTO_TEST_CASE (frustum_intersect)
Definition at line 461 of file BoundingBoxTest.cpp.
View newest version in sPHENIX GitHub at line 461 of file BoundingBoxTest.cpp
References Acts::PlyVisualization3D< T >::clear(), color, Acts::Frustum< value_t, DIM, SIDES >::draw(), Acts::AxisAlignedBoundingBox< entity_t, value_t, DIM >::draw(), material_mapping_optimisation::flush, INTTVtxZ::fname, h, i, ambiguity_solver_full_chain::idx, Acts::AxisAlignedBoundingBox< entity_t, value_t, DIM >::intersect(), j, k, Acts::UnitConstants::min, n, os, pos, physmon_simulation::s, size, step(), and tmp().
Acts::Test::BOOST_AUTO_TEST_CASE (superset3_double)
Definition at line 466 of file Range1DTests.cpp.
View newest version in sPHENIX GitHub at line 466 of file Range1DTests.cpp
References physmon_track_finding_ttbar::r.
Acts::Test::BOOST_AUTO_TEST_CASE (superset4_double)
Definition at line 474 of file Range1DTests.cpp.
View newest version in sPHENIX GitHub at line 474 of file Range1DTests.cpp
References physmon_track_finding_ttbar::r.
Acts::Test::BOOST_AUTO_TEST_CASE (track_removing)
Definition at line 477 of file AdaptiveGridTrackDensityTests.cpp.
View newest version in sPHENIX GitHub at line 477 of file AdaptiveGridTrackDensityTests.cpp
References Acts::AdaptiveGridTrackDensity< spatialTrkGridSize, temporalTrkGridSize >::addTrack(), CHECK_CLOSE_ABS, CHECK_CLOSE_REL, Acts::UnitConstants::e, it, makeRandomCovariance(), Acts::ParticleHypothesis::pion(), Acts::AdaptiveGridTrackDensity< spatialTrkGridSize, temporalTrkGridSize >::subtractTrack(), and sum().
Acts::Test::BOOST_AUTO_TEST_CASE (superset5_double)
Definition at line 482 of file Range1DTests.cpp.
View newest version in sPHENIX GitHub at line 482 of file Range1DTests.cpp
References physmon_track_finding_ttbar::r.
Acts::Test::BOOST_AUTO_TEST_CASE (intersection1_double)
Definition at line 490 of file Range1DTests.cpp.
View newest version in sPHENIX GitHub at line 490 of file Range1DTests.cpp
References i, Acts::Range1D< Type >::max(), Acts::Range1D< Type >::min(), and physmon_track_finding_ttbar::r.
Acts::Test::BOOST_AUTO_TEST_CASE (intersection2_double)
Definition at line 499 of file Range1DTests.cpp.
View newest version in sPHENIX GitHub at line 499 of file Range1DTests.cpp
References i, Acts::Range1D< Type >::max(), Acts::Range1D< Type >::min(), and physmon_track_finding_ttbar::r.
Acts::Test::BOOST_AUTO_TEST_CASE (intersection3_double)
Definition at line 508 of file Range1DTests.cpp.
View newest version in sPHENIX GitHub at line 508 of file Range1DTests.cpp
References i, Acts::Range1D< Type >::max(), Acts::Range1D< Type >::min(), and physmon_track_finding_ttbar::r.
Acts::Test::BOOST_AUTO_TEST_CASE (adaptive_multi_vertex_finder_adaptive_grid_seed_finder_test)
AMVF test with adaptive grid seed finder.
Definition at line 509 of file AdaptiveMultiVertexFinderTests.cpp.
View newest version in sPHENIX GitHub at line 509 of file AdaptiveMultiVertexFinderTests.cpp
References bField, CHECK_CLOSE_ABS, filter::Config, test_fpe::count, debugMode, geoContext, i, magFieldContext, testing::internal::move(), position, readTracksAndVertexCSV(), Acts::AnnealingUtility::Config::setOfTemperatures, filter::state, propagation_timing::stepper, ambiguity_solver_full_chain::t1, ambiguity_solver_full_chain::t2, toolString, and tracks().
Acts::Test::BOOST_AUTO_TEST_CASE (grid_test_2d_variable)
Definition at line 514 of file GridTests.cpp.
View newest version in sPHENIX GitHub at line 514 of file GridTests.cpp
References KFPMath::a, KFPMath::b, Acts::UnitConstants::g, std::tr1::make_tuple(), testing::internal::move(), and physmon_ckf_tracking::u.
Acts::Test::BOOST_AUTO_TEST_CASE (intersection4_double)
Definition at line 517 of file Range1DTests.cpp.
View newest version in sPHENIX GitHub at line 517 of file Range1DTests.cpp
References Acts::Range1D< Type >::degenerate(), i, and physmon_track_finding_ttbar::r.
Acts::Test::BOOST_AUTO_TEST_CASE (intersection5_double)
Definition at line 525 of file Range1DTests.cpp.
View newest version in sPHENIX GitHub at line 525 of file Range1DTests.cpp
References Acts::Range1D< Type >::degenerate(), i, and physmon_track_finding_ttbar::r.
Acts::Test::BOOST_AUTO_TEST_CASE (intersects_edge_int_positive)
Definition at line 533 of file Range1DTests.cpp.
View newest version in sPHENIX GitHub at line 533 of file Range1DTests.cpp
References physmon_track_finding_ttbar::r.
Acts::Test::BOOST_AUTO_TEST_CASE (intersects_edge_int_negative)
Definition at line 540 of file Range1DTests.cpp.
View newest version in sPHENIX GitHub at line 540 of file Range1DTests.cpp
References physmon_track_finding_ttbar::r.
Acts::Test::BOOST_AUTO_TEST_CASE (range_search_very_big)
Definition at line 540 of file KDTreeTests.cpp.
View newest version in sPHENIX GitHub at line 540 of file KDTreeTests.cpp
References Acts::PhysicalConstants::c, i, j, testing::internal::move(), Acts::KDTree< Dims, Type, Scalar, Vector, LeafSize >::rangeSearch(), tree, Acts::IntegrationTest::valid(), ambiguity_solver_full_chain::x, xmax, xmin, y, ymax, ymin, and physmon_track_finding_ttbar::z.
Acts::Test::BOOST_AUTO_TEST_CASE (single_value_not_degenerate_int_positive)
Definition at line 547 of file Range1DTests.cpp.
View newest version in sPHENIX GitHub at line 547 of file Range1DTests.cpp
References Acts::Range1D< Type >::degenerate(), and physmon_track_finding_ttbar::r.
Acts::Test::BOOST_AUTO_TEST_CASE (StepSize)
Definition at line 553 of file AtlasStepperTests.cpp.
View newest version in sPHENIX GitHub at line 553 of file AtlasStepperTests.cpp
References absMom, charge, cov, geoCtx, magCtx, magneticField, particleHypothesis, pos4(), filter::state, propagation_timing::stepper, stepSize, tolerance, and unitDir.
Acts::Test::BOOST_AUTO_TEST_CASE (single_value_not_degenerate_int_negative)
Definition at line 553 of file Range1DTests.cpp.
View newest version in sPHENIX GitHub at line 553 of file Range1DTests.cpp
References Acts::Range1D< Type >::degenerate(), and physmon_track_finding_ttbar::r.
Acts::Test::BOOST_AUTO_TEST_CASE (iterative_finder_test_athena_reference)
Unit test for IterativeVertexFinder with Athena reference data.
Definition at line 556 of file IterativeVertexFinderTests.cpp.
View newest version in sPHENIX GitHub at line 556 of file IterativeVertexFinderTests.cpp
References Acts::IntegrationTest::bField, cfg, filter::Config, geoContext, magFieldContext, testing::internal::move(), readTracksAndVertexCSV(), filter::state, propagation_timing::stepper, toolString, and tracks().
Acts::Test::BOOST_AUTO_TEST_CASE (step_extension_vacuum_test)
This function tests the EigenStepper with the DefaultExtension and the DenseEnvironmentExtension. The focus of this tests lies in the choosing of the right extension for the individual use case. This is performed with three different detectors: a) Pure vacuum -> DefaultExtension needs to act b) Pure Be -> DenseEnvironmentExtension needs to act c) Vacuum - Be - Vacuum -> Both should act and switch during the propagation.
Definition at line 556 of file EigenStepperTests.cpp.
View newest version in sPHENIX GitHub at line 556 of file EigenStepperTests.cpp
References Acts::PropagatorOptions< action_list_t, aborter_list_t >::abortList, Acts::PropagatorOptions< action_list_t, aborter_list_t >::actionList, Acts::IntegrationTest::bField, CHECK_CLOSE_ABS, CHECK_SMALL, cov, i, Acts::CuboidVolumeBuilder::VolumeConfig::length, Acts::CuboidVolumeBuilder::Config::length, Acts::makeDirectionFromPhiTheta(), Acts::PropagatorPlainOptions::maxSteps, Acts::PropagatorPlainOptions::maxStepSize, Acts::IntegrationTest::mfContext, Acts::Test::StepCollector::this_result::momentum, Acts::ParticleHypothesis::pion(), pos, Acts::CuboidVolumeBuilder::VolumeConfig::position, Acts::CuboidVolumeBuilder::Config::position, Acts::Test::StepCollector::this_result::position, Acts::Propagator< stepper_t, navigator_t >::propagate(), Acts::CuboidVolumeBuilder::setConfig(), Acts::tgContext, Acts::TrackingGeometryBuilder::trackingGeometry(), Acts::CuboidVolumeBuilder::trackingVolume(), Acts::TrackingGeometryBuilder::Config::trackingVolumeBuilders, and Acts::CuboidVolumeBuilder::Config::volumeCfg.
Acts::Test::BOOST_AUTO_TEST_CASE (intersects_implies_non_degenerate_intersection)
Definition at line 559 of file Range1DTests.cpp.
View newest version in sPHENIX GitHub at line 559 of file Range1DTests.cpp
References Acts::Range1D< Type >::degenerate(), physmon_track_finding_ttbar::r, and testSigmaEff::v.
Acts::Test::BOOST_AUTO_TEST_CASE (StepSizeSurface)
Definition at line 573 of file AtlasStepperTests.cpp.
View newest version in sPHENIX GitHub at line 573 of file AtlasStepperTests.cpp
References absMom, Acts::ConstrainedStep::actor, charge, closest(), cov, Acts::Test::Stepper::direction(), distance(), geoCtx, Acts::PlanarHelper::intersect(), magCtx, magneticField, navDir, particleHypothesis, pos, pos4(), Acts::Test::Stepper::position(), filter::state, propagation_timing::stepper, stepSize, material_mapping_optimisation::target, tolerance, and unitDir.
Acts::Test::BOOST_AUTO_TEST_CASE (degeneracy_implies_size_zero_intersection)
Definition at line 582 of file Range1DTests.cpp.
View newest version in sPHENIX GitHub at line 582 of file Range1DTests.cpp
References Acts::Range1D< Type >::degenerate(), physmon_track_finding_ttbar::r, Acts::Range1D< Type >::size(), and testSigmaEff::v.
Acts::Test::BOOST_AUTO_TEST_CASE (range_search_many_same)
Definition at line 593 of file KDTreeTests.cpp.
View newest version in sPHENIX GitHub at line 593 of file KDTreeTests.cpp
References i, testing::internal::move(), Acts::KDTree< Dims, Type, Scalar, Vector, LeafSize >::rangeSearch(), and tree.
Acts::Test::BOOST_AUTO_TEST_CASE (range_inclusive_left)
Definition at line 596 of file Range1DTests.cpp.
View newest version in sPHENIX GitHub at line 596 of file Range1DTests.cpp
References Acts::Range1D< Type >::contains(), and physmon_track_finding_ttbar::r.
Acts::Test::BOOST_AUTO_TEST_CASE (range_exclusive_right)
Definition at line 604 of file Range1DTests.cpp.
View newest version in sPHENIX GitHub at line 604 of file Range1DTests.cpp
References Acts::Range1D< Type >::contains(), and physmon_track_finding_ttbar::r.
Acts::Test::BOOST_AUTO_TEST_CASE (grid_test_3d_variable)
Definition at line 638 of file GridTests.cpp.
View newest version in sPHENIX GitHub at line 638 of file GridTests.cpp
References KFPMath::a, KFPMath::b, Acts::PhysicalConstants::c, Acts::UnitConstants::g, std::tr1::make_tuple(), testing::internal::move(), and physmon_ckf_tracking::u.
Acts::Test::BOOST_AUTO_TEST_CASE (step_extension_material_test)
Definition at line 661 of file EigenStepperTests.cpp.
View newest version in sPHENIX GitHub at line 661 of file EigenStepperTests.cpp
References Acts::PropagatorOptions< action_list_t, aborter_list_t >::abortList, Acts::PropagatorOptions< action_list_t, aborter_list_t >::actionList, Acts::IntegrationTest::bField, CHECK_CLOSE_ABS, CHECK_SMALL, cov, i, Acts::CuboidVolumeBuilder::VolumeConfig::length, makeBeryllium(), Acts::makeDirectionFromPhiTheta(), material, Acts::PropagatorPlainOptions::maxSteps, Acts::PropagatorPlainOptions::maxStepSize, Acts::IntegrationTest::mfContext, Acts::Test::StepCollector::this_result::momentum, Acts::ParticleHypothesis::pion(), pos, Acts::CuboidVolumeBuilder::VolumeConfig::position, Acts::Test::StepCollector::this_result::position, Acts::Propagator< stepper_t, navigator_t >::propagate(), Acts::CuboidVolumeBuilder::setConfig(), Acts::tgContext, Acts::TrackingGeometryBuilder::trackingGeometry(), Acts::CuboidVolumeBuilder::trackingVolume(), Acts::TrackingGeometryBuilder::Config::trackingVolumeBuilders, Acts::CuboidVolumeBuilder::Config::volumeCfg, and Acts::CuboidVolumeBuilder::VolumeConfig::volumeMaterial.
Acts::Test::BOOST_AUTO_TEST_CASE (grid_test_2d_mixed)
Definition at line 778 of file GridTests.cpp.
View newest version in sPHENIX GitHub at line 778 of file GridTests.cpp
References KFPMath::a, KFPMath::b, Acts::UnitConstants::g, std::tr1::make_tuple(), testing::internal::move(), and physmon_ckf_tracking::u.
Acts::Test::BOOST_AUTO_TEST_CASE (step_extension_vacmatvac_test)
Definition at line 817 of file EigenStepperTests.cpp.
View newest version in sPHENIX GitHub at line 817 of file EigenStepperTests.cpp
References Acts::PropagatorOptions< action_list_t, aborter_list_t >::abortList, KFPMath::b, Acts::IntegrationTest::bField, CHECK_CLOSE_ABS, Acts::UnitConstants::e, i, Acts::CuboidVolumeBuilder::VolumeConfig::length, Acts::CuboidVolumeBuilder::Config::length, makeBeryllium(), Acts::VectorHelpers::makeVector4(), Acts::PropagatorPlainOptions::maxSteps, Acts::PropagatorPlainOptions::maxStepSize, Acts::IntegrationTest::mfContext, Acts::Test::StepCollector::this_result::momentum, Acts::CuboidVolumeBuilder::VolumeConfig::name, Acts::ParticleHypothesis::pion(), Acts::CuboidVolumeBuilder::VolumeConfig::position, Acts::CuboidVolumeBuilder::Config::position, Acts::Test::StepCollector::this_result::position, Acts::Propagator< stepper_t, navigator_t >::propagate(), Acts::CuboidVolumeBuilder::setConfig(), Acts::tgContext, Acts::TrackingGeometryBuilder::trackingGeometry(), Acts::CuboidVolumeBuilder::trackingVolume(), Acts::TrackingGeometryBuilder::Config::trackingVolumeBuilders, Acts::CuboidVolumeBuilder::Config::volumeCfg, and Acts::CuboidVolumeBuilder::VolumeConfig::volumeMaterial.
Acts::Test::BOOST_AUTO_TEST_CASE (grid_test_2d_mixed_at)
Definition at line 937 of file GridTests.cpp.
View newest version in sPHENIX GitHub at line 937 of file GridTests.cpp
References KFPMath::a, KFPMath::b, Acts::UnitConstants::g, std::tr1::make_tuple(), testing::internal::move(), and physmon_ckf_tracking::u.
Acts::Test::BOOST_AUTO_TEST_CASE (grid_interpolation)
Definition at line 972 of file GridTests.cpp.
View newest version in sPHENIX GitHub at line 972 of file GridTests.cpp
References KFPMath::a, Acts::detail::Grid< T, Axes >::atPosition(), KFPMath::b, Acts::PhysicalConstants::c, CHECK_CLOSE_REL, Acts::UnitConstants::e, Acts::UnitConstants::g, Acts::detail::Grid< T, Axes >::interpolate(), std::tr1::make_tuple(), testing::internal::move(), and physmon_ckf_tracking::u.
Acts::Test::BOOST_AUTO_TEST_CASE (step_extension_trackercalomdt_test)
Definition at line 1013 of file EigenStepperTests.cpp.
View newest version in sPHENIX GitHub at line 1013 of file EigenStepperTests.cpp
References Acts::PropagatorOptions< action_list_t, aborter_list_t >::abortList, Acts::IntegrationTest::bField, i, Acts::CuboidVolumeBuilder::VolumeConfig::layerCfg, Acts::CuboidVolumeBuilder::VolumeConfig::length, Acts::CuboidVolumeBuilder::Config::length, makeBeryllium(), Acts::PropagatorPlainOptions::maxSteps, Acts::IntegrationTest::mfContext, Acts::Test::StepCollector::this_result::momentum, Acts::CuboidVolumeBuilder::VolumeConfig::name, Acts::ParticleHypothesis::pion(), Acts::CuboidVolumeBuilder::SurfaceConfig::position, Acts::CuboidVolumeBuilder::VolumeConfig::position, Acts::CuboidVolumeBuilder::Config::position, Acts::Test::StepCollector::this_result::position, Acts::CuboidVolumeBuilder::SurfaceConfig::rBounds, Acts::CuboidVolumeBuilder::SurfaceConfig::rotation, Acts::CuboidVolumeBuilder::setConfig(), Acts::CuboidVolumeBuilder::LayerConfig::surfaceCfg, Acts::CuboidVolumeBuilder::SurfaceConfig::surMat, Acts::tgContext, Acts::CuboidVolumeBuilder::SurfaceConfig::thickness, Acts::TrackingGeometryBuilder::trackingGeometry(), Acts::CuboidVolumeBuilder::trackingVolume(), Acts::TrackingGeometryBuilder::Config::trackingVolumeBuilders, Acts::CuboidVolumeBuilder::VolumeConfig::volumeCfg, Acts::CuboidVolumeBuilder::Config::volumeCfg, and Acts::CuboidVolumeBuilder::VolumeConfig::volumeMaterial.
Acts::Test::BOOST_AUTO_TEST_CASE (closestPoints)
Definition at line 1200 of file GridTests.cpp.
View newest version in sPHENIX GitHub at line 1200 of file GridTests.cpp
References KFPMath::a, KFPMath::b, Acts::PhysicalConstants::c, std::tr1::make_tuple(), testing::internal::move(), and physmon_ckf_tracking::u.
Acts::Test::BOOST_AUTO_TEST_CASE (ostream_operator)
Definition at line 1248 of file BoundingBoxTest.cpp.
View newest version in sPHENIX GitHub at line 1248 of file BoundingBoxTest.cpp
Acts::Test::BOOST_AUTO_TEST_CASE_TEMPLATE (BlockedMatrixMultiplication , Matrices , MatrixProductTypes)
Definition at line 179 of file HelpersTests.cpp.
View newest version in sPHENIX GitHub at line 179 of file HelpersTests.cpp
References KFPMath::a, KFPMath::b, Acts::blockedMult(), i, and check_smearing_config::ref.
Acts::Test::BOOST_DATA_TEST_CASE (CylinderVolumeBuilder_wraps , bdata:: random-11.,-15.)^bdata::random(11., 15.)^bdata::random(-10., 10.)^bdata::random(0., 4.)^bdata::random(11., 15.)^bdata::random(10., 15.)^bdata::xrange(100, left , right , central , inner , outer , length , index)
Unit test for testing the wraps() function of the CylinderVolumeBuilder.
Definition at line 24 of file CylinderVolumeBuilderTests.cpp.
View newest version in sPHENIX GitHub at line 24 of file CylinderVolumeBuilderTests.cpp
References index, left(), G4PLUGDOOR::length, Acts::VolumeConfig::rMax, Acts::VolumeConfig::rMin, Acts::VolumeConfig::wraps(), Acts::VolumeConfig::zMax, and Acts::VolumeConfig::zMin.
Acts::Test::BOOST_DATA_TEST_CASE (ConstantBField_components , bdata:: random-2_T, 2_T)^bdata::random(-1_T, 4_T)^bdata::random(0_T, 10_T)^bdata::random(-10_m, 10_m)^bdata::random(-10_m, 10_m)^bdata::random(-10_m, 10_m)^bdata::xrange(10, x , y , z , bx , by , bz , index)
unit test for construction of constant magnetic field
Tests the correct behavior and consistency of
ConstantBField::ConstantBField(double Bx,double By,double Bz)
ConstantBField::ConstantBField(Vector3 B)
ConstantBField::getField(const double* xyz, double* B) const
ConstantBField::getField(const Vector3& pos) const
Definition at line 39 of file ConstantBFieldTests.cpp.
View newest version in sPHENIX GitHub at line 39 of file ConstantBFieldTests.cpp
References Acts::IntegrationTest::bCache, Acts::ConstantBField::getField(), index, Acts::ConstantBField::makeCache(), Acts::IntegrationTest::mfContext, pos, ambiguity_solver_full_chain::x, y, and physmon_track_finding_ttbar::z.
Acts::Test::BOOST_DATA_TEST_CASE (bvhnavigation_test , bdata:: random(bdata::seed=7, bdata::engine=std::mt19937(),bdata::distribution=std::uniform_real_distribution<>(-5,5)))^bdata::random((bdata::seed=2, bdata::engine=std::mt19937(),bdata::distribution=std::uniform_real_distribution<>(-M_PI, M_PI)))^bdata::random((bdata::seed=3, bdata::engine=std::mt19937(),bdata::distribution=std::uniform_real_distribution<>(-100, 100)))^bdata::random((bdata::seed=4, bdata::engine=std::mt19937(),bdata::distribution=std::uniform_real_distribution<>(-100, 100)))^bdata::random((bdata::seed=5, bdata::engine=std::mt19937(),bdata::distribution=std::uniform_real_distribution<>(-100, 100)))^bdata::xrange(NTESTS, eta , phi , x , y , z , index)
Definition at line 26 of file TrackingVolumeTests.cpp.
View newest version in sPHENIX GitHub at line 26 of file TrackingVolumeTests.cpp
Acts::Test::BOOST_DATA_TEST_CASE (ConstantBField_update , bdata:: random-2_T, 2_T)^bdata::random(-1_T, 4_T)^bdata::random(0_T, 10_T)^bdata::random(-10_m, 10_m)^bdata::random(-10_m, 10_m)^bdata::random(-10_m, 10_m)^bdata::xrange(10, x , y , z , bx , by , bz , index)
unit test for update of constant magnetic field
Tests the correct behavior and consistency of
ConstantBField::setField(double Bx, double By, double Bz)
ConstantBField::setField(const Vector3& B)
ConstantBField::getField(const double* xyz, double* B) const
ConstantBField::getField(const Vector3& pos) const
Definition at line 66 of file ConstantBFieldTests.cpp.
View newest version in sPHENIX GitHub at line 66 of file ConstantBFieldTests.cpp
References Acts::IntegrationTest::bCache, Acts::ConstantBField::getField(), index, Acts::ConstantBField::makeCache(), Acts::IntegrationTest::mfContext, pos, Acts::ConstantBField::setField(), ambiguity_solver_full_chain::x, y, and physmon_track_finding_ttbar::z.
Acts::Test::BOOST_DATA_TEST_CASE (readout_counter_test , bdata:: random(bdata::seed=0,bdata::distribution=std::uniform_real_distribution<>(-halfX+sguardX, halfX-sguardX)))^bdata::random((bdata::seed=1,bdata::distribution=std::uniform_real_distribution<>(-halfX+sguardX, halfX-sguardX)))^bdata::random((bdata::seed=2,bdata::distribution=std::uniform_real_distribution<>(-halfY, halfY)))^bdata::random((bdata::seed=3,bdata::distribution=std::uniform_int_distribution<>(-static_cast< int >(halfY),static_cast< int >(halfY))))^bdata::xrange(ntests, entryX , entryY , exitX , exitY , index)
The following test checks test cases where the entry and exit is guaranteed to be in on the readout/counter plane
Definition at line 66 of file PlanarModuleStepperTests.cpp.
View newest version in sPHENIX GitHub at line 66 of file PlanarModuleStepperTests.cpp
References Acts::PlanarModuleStepper::cellSteps(), CHECK_CLOSE_REL, Acts::UnitConstants::e, entry, exitX, exitY, hThickness, index, pmStepper, testModules, Acts::tgContext, and physmon_track_finding_ttbar::z.
Acts::Test::BOOST_DATA_TEST_CASE (benchmark_surface_intersections , bdata:: random(bdata::seed=21,bdata::distribution=std::uniform_real_distribution<>(-M_PI, M_PI)))^bdata::random((bdata::seed=22,bdata::distribution=std::uniform_real_distribution<>(-0.3, 0.3)))^bdata::xrange(ntests, phi , theta , index)
Definition at line 89 of file SurfaceIntersectionBenchmark.cpp.
View newest version in sPHENIX GitHub at line 89 of file SurfaceIntersectionBenchmark.cpp
References aCylinder, aDisc, aPlane, aStraw, index, ActsTests::PropagationDatasets::phi, testCylinder, testDisc, testPlane, testStraw, and ActsTests::PropagationDatasets::theta.
Acts::Test::BOOST_DATA_TEST_CASE (CylinderVolumeBuilder_containes , bdata:: random-11.,-15.)^bdata::random(11., 15.)^bdata::random(-10., 10.)^bdata::random(0., 4.)^bdata::random(10., 15.)^bdata::random(10., 15.)^bdata::xrange(100, left , right , central , inner , outer , length , index)
Unit test for testing the contains(), containsInR() and containsInZ() function of the CylinderVolumeBuilder
Definition at line 100 of file CylinderVolumeBuilderTests.cpp.
View newest version in sPHENIX GitHub at line 100 of file CylinderVolumeBuilderTests.cpp
References Acts::VolumeConfig::contains(), Acts::VolumeConfig::containsInR(), Acts::VolumeConfig::containsInZ(), index, left(), G4PLUGDOOR::length, Acts::VolumeConfig::rMax, Acts::VolumeConfig::rMin, Acts::VolumeConfig::zMax, and Acts::VolumeConfig::zMin.
Acts::Test::BOOST_DATA_TEST_CASE (test_extrapolation_ , bdata:: random(bdata::seed=0,bdata::distribution=std::uniform_real_distribution<>(0.4_GeV, 10_GeV)))^bdata::random((bdata::seed=1,bdata::distribution=std::uniform_real_distribution<>(-M_PI, M_PI)))^bdata::random((bdata::seed=2,bdata::distribution=std::uniform_real_distribution<>(1.0, M_PI-1.0)))^bdata::random((bdata::seed=3,bdata::distribution=std::uniform_int_distribution<>(0, 1)))^bdata::random((bdata::seed=4,bdata::distribution=std::uniform_int_distribution<>(0, 100)))^bdata::xrange(ntests, pT , phi , theta , charge , time , index)
a covariance matrix to transport
Definition at line 90 of file ExtrapolatorTests.cpp.
View newest version in sPHENIX GitHub at line 90 of file ExtrapolatorTests.cpp
References charge(), cov, Acts::IntegrationTest::epropagator(), index, Acts::PropagatorPlainOptions::maxStepSize, Acts::IntegrationTest::mfContext, ckf::options, merge_hashes::p, Acts::PropagatorPlainOptions::pathLimit, ActsTests::PropagationDatasets::phi, Acts::ParticleHypothesis::pion(), Acts::Propagator< stepper_t, navigator_t >::propagate(), graph_fancy::pT, start, Acts::tgContext, ActsTests::PropagationDatasets::theta, and time.
Acts::Test::BOOST_DATA_TEST_CASE (loop_aborter_test , bdata:: random(bdata::seed=21,bdata::distribution=std::uniform_real_distribution<>(-M_PI, M_PI)))^bdata::random((bdata::seed=22,bdata::distribution=std::uniform_real_distribution<>(-M_PI, M_PI)))^bdata::xrange(1, phi , deltaPhi , index)
Definition at line 129 of file LoopProtectionTests.cpp.
View newest version in sPHENIX GitHub at line 129 of file LoopProtectionTests.cpp
References deltaPhi(), Acts::Test::SteppingState::dir, Acts::getDefaultLogger(), index, Acts::Logging::INFO, Acts::PathLimitReached::internalLimit, Acts::Test::PropagatorState::options, Acts::Test::SteppingState::p, ActsTests::PropagationDatasets::phi, Acts::detail::setupLoopProtection(), and Acts::Test::PropagatorState::stepping.
Acts::Test::BOOST_DATA_TEST_CASE (SpacePointBuilder_basic , bdata:: xrange1, index)
Definition at line 146 of file SpacePointBuilderTests.cpp.
View newest version in sPHENIX GitHub at line 146 of file SpacePointBuilderTests.cpp
References cov, createMeasurements(), Acts::eBoundLoc0, Acts::eBoundLoc1, ckf::field, geoCtx, geometry, index, magCtx, makeParameters(), testing::internal::move(), navigator, merge_hashes::p, Acts::SpacePointBuilderOptions::paramCovAccessor, Acts::StripPairOptions::paramCovAccessor, Acts::Test::TestSourceLink::parameters, ActsTests::PropagationDatasets::phi, pos, resolutions, rng(), start, propagation_timing::stepper, stripEnds(), tgContext, ActsTests::PropagationDatasets::theta, and Acts::SpacePointBuilderOptions::vertex.
Acts::Test::BOOST_DATA_TEST_CASE (test_surface_collection_ , bdata:: random(bdata::seed=10,bdata::distribution=std::uniform_real_distribution<>(0.4_GeV, 10_GeV)))^bdata::random((bdata::seed=11,bdata::distribution=std::uniform_real_distribution<>(-M_PI, M_PI)))^bdata::random((bdata::seed=12,bdata::distribution=std::uniform_real_distribution<>(1.0, M_PI-1.0)))^bdata::random((bdata::seed=13,bdata::distribution=std::uniform_int_distribution<>(0, 1)))^bdata::random((bdata::seed=14,bdata::distribution=std::uniform_int_distribution<>(0, 100)))^bdata::xrange(ntests, pT , phi , theta , charge , time , index)
a covariance matrix to transport
Definition at line 133 of file ExtrapolatorTests.cpp.
View newest version in sPHENIX GitHub at line 133 of file ExtrapolatorTests.cpp
References charge(), cov, Acts::IntegrationTest::epropagator(), index, Acts::PropagatorPlainOptions::maxStepSize, Acts::IntegrationTest::mfContext, ckf::options, merge_hashes::p, Acts::PropagatorPlainOptions::pathLimit, ActsTests::PropagationDatasets::phi, Acts::ParticleHypothesis::pion(), Acts::Propagator< stepper_t, navigator_t >::propagate(), graph_fancy::pT, Acts::GenericBoundTrackParameters< particle_hypothesis_t >::referenceSurface(), start, Acts::tgContext, ActsTests::PropagationDatasets::theta, and time.
Acts::Test::BOOST_DATA_TEST_CASE (CylinderVolumeBoundsOrientedSurfaces , bdata:: random-M_PI, M_PI)^bdata::random(-M_PI, M_PI)^bdata::random(-M_PI, M_PI)^bdata::random(-10., 10.)^bdata::random(-10., 10.)^bdata::random(-10., 10.)^bdata::xrange(100, alpha , beta , gamma , posX , posY , posZ , index)
Unit test for testing the orientedSurfaces() function.
Definition at line 154 of file CylinderVolumeBoundsTests.cpp.
View newest version in sPHENIX GitHub at line 154 of file CylinderVolumeBoundsTests.cpp
References alpha, CHECK_CLOSE_ABS, CHECK_CLOSE_REL, Acts::UnitConstants::e, Acts::CylinderVolumeBounds::eHalfLengthZ, Acts::CylinderVolumeBounds::get(), index, norm, Acts::CylinderVolumeBounds::orientedSurfaces(), pos, tgContext, transform, and physmon_track_finding_ttbar::z.
Acts::Test::BOOST_DATA_TEST_CASE (propagator_loop_protection_test , bdata:: random(bdata::seed=20,bdata::distribution=std::uniform_real_distribution<>(0.5_GeV, 10_GeV)))^bdata::random((bdata::seed=21,bdata::distribution=std::uniform_real_distribution<>(-M_PI, M_PI)))^bdata::random((bdata::seed=22,bdata::distribution=std::uniform_real_distribution<>(1.0, M_PI-1.0)))^bdata::random((bdata::seed=23,bdata::distribution=std::uniform_int_distribution<>(0, 1)))^bdata::xrange(ntests, pT , phi , theta , charge , index)
Definition at line 169 of file LoopProtectionTests.cpp.
View newest version in sPHENIX GitHub at line 169 of file LoopProtectionTests.cpp
References Acts::IntegrationTest::bField, Acts::IntegrationTest::Bz, charge(), CHECK_CLOSE_REL, Acts::UnitConstants::e, Acts::IntegrationTest::epropagator(), Acts::IntegrationTest::estepper, index, Acts::PropagatorPlainOptions::maxSteps, Acts::IntegrationTest::mfContext, testing::internal::move(), ckf::options, merge_hashes::p, ActsTests::PropagationDatasets::phi, Acts::ParticleHypothesis::pion(), Acts::Propagator< stepper_t, navigator_t >::propagate(), graph_fancy::pT, skip, start, Acts::tgContext, and ActsTests::PropagationDatasets::theta.
Acts::Test::BOOST_DATA_TEST_CASE (cylinder_passage_observer_ , bdata:: random(bdata::seed=0,bdata::distribution=std::uniform_real_distribution<>(0.4_GeV, 10_GeV)))^bdata::random((bdata::seed=1,bdata::distribution=std::uniform_real_distribution<>(-M_PI, M_PI)))^bdata::random((bdata::seed=2,bdata::distribution=std::uniform_real_distribution<>(1.0, M_PI-1.0)))^bdata::random((bdata::seed=3,bdata::distribution=std::uniform_int_distribution<>(0, 1)))^bdata::random((bdata::seed=4,bdata::distribution=std::uniform_int_distribution<>(0, 100)))^bdata::xrange(ntests, pT , phi , theta , charge , time , index)
Definition at line 167 of file PropagatorTests.cpp.
View newest version in sPHENIX GitHub at line 167 of file PropagatorTests.cpp
References Acts::PropagatorOptions< action_list_t, aborter_list_t >::actionList, charge(), CHECK_CLOSE_ABS, cSurface, Acts::UnitConstants::e, Acts::IntegrationTest::epropagator(), index, Acts::VectorHelpers::makeVector4(), Acts::PropagatorPlainOptions::maxStepSize, Acts::IntegrationTest::mfContext, mSurface, ckf::options, Acts::PropagatorPlainOptions::pathLimit, ActsTests::PropagationDatasets::phi, Acts::ParticleHypothesis::pion(), pos, Acts::Propagator< stepper_t, navigator_t >::propagate(), graph_fancy::pT, start, writeMapConfig::surface, Acts::tgContext, ActsTests::PropagationDatasets::theta, time, physmon_ckf_tracking::u, ambiguity_solver_full_chain::x, y, and physmon_track_finding_ttbar::z.
Acts::Test::BOOST_DATA_TEST_CASE (CylinderVolumeBuilder_overlapsInR , bdata:: random0., 4.)^bdata::random(11., 15.)^bdata::xrange(100, inner , outer , index)
Unit test for testing the coverlapsInR() function of the CylinderVolumeBuilder
Definition at line 187 of file CylinderVolumeBuilderTests.cpp.
View newest version in sPHENIX GitHub at line 187 of file CylinderVolumeBuilderTests.cpp
References index, Acts::VolumeConfig::overlapsInR(), Acts::VolumeConfig::present, Acts::VolumeConfig::rMax, Acts::VolumeConfig::rMin, Acts::VolumeConfig::zMax, and Acts::VolumeConfig::zMin.
Acts::Test::BOOST_DATA_TEST_CASE (TrapezoidInsideCheck , bdata:: random(bdata::seed=1,bdata::distribution=std::uniform_real_distribution<>(-7,7)))^bdata::random((bdata::seed=2,bdata::distribution=std::uniform_real_distribution<>(-3, 3)))^bdata::xrange(1000)*bdata::make({0.0, 0.1, 0.2, 0.3}, x , y , index , tol)
Definition at line 182 of file TrapezoidBoundsTests.cpp.
View newest version in sPHENIX GitHub at line 182 of file TrapezoidBoundsTests.cpp
Acts::Test::BOOST_DATA_TEST_CASE (test_direct_navigator , bdata:: random(bdata::seed=20,bdata::distribution=std::uniform_real_distribution<>(0.15_GeV, 10_GeV)))^bdata::random((bdata::seed=21,bdata::distribution=std::uniform_real_distribution<>(-M_PI, M_PI)))^bdata::random((bdata::seed=22,bdata::distribution=std::uniform_real_distribution<>(1.0, M_PI-1.0)))^bdata::random((bdata::seed=23,bdata::distribution=std::uniform_int_distribution<>(0, 1)))^bdata::random((bdata::seed=24,bdata::distribution=std::uniform_int_distribution<>(0, 100)))^bdata::xrange(ntests, pT , phi , theta , charge , time , index)
Definition at line 184 of file DirectNavigatorTests.cpp.
View newest version in sPHENIX GitHub at line 184 of file DirectNavigatorTests.cpp
References charge(), dpropagator(), index, ActsTests::PropagationDatasets::phi, graph_fancy::pT, rpropagator(), runTest(), ActsTests::PropagationDatasets::theta, and time.
Acts::Test::BOOST_DATA_TEST_CASE (test_material_interactor_ , bdata:: random(bdata::seed=20,bdata::distribution=std::uniform_real_distribution<>(0.4_GeV, 10_GeV)))^bdata::random((bdata::seed=21,bdata::distribution=std::uniform_real_distribution<>(-M_PI, M_PI)))^bdata::random((bdata::seed=22,bdata::distribution=std::uniform_real_distribution<>(1.0, M_PI-1.0)))^bdata::random((bdata::seed=23,bdata::distribution=std::uniform_int_distribution<>(0, 1)))^bdata::random((bdata::seed=24,bdata::distribution=std::uniform_int_distribution<>(0, 100)))^bdata::xrange(ntests, pT , phi , theta , charge , time , index)
a covariance matrix to transport
Definition at line 199 of file ExtrapolatorTests.cpp.
View newest version in sPHENIX GitHub at line 199 of file ExtrapolatorTests.cpp
References Acts::GenericBoundTrackParameters< particle_hypothesis_t >::absoluteMomentum(), charge(), cov, Acts::IntegrationTest::epropagator(), index, Acts::PropagatorPlainOptions::maxStepSize, Acts::IntegrationTest::mfContext, ckf::options, merge_hashes::p, Acts::PropagatorPlainOptions::pathLimit, ActsTests::PropagationDatasets::phi, Acts::ParticleHypothesis::pion(), Acts::Propagator< stepper_t, navigator_t >::propagate(), graph_fancy::pT, start, Acts::tgContext, ActsTests::PropagationDatasets::theta, and time.
Acts::Test::BOOST_DATA_TEST_CASE (curvilinear_additive_ , bdata:: random(bdata::seed=0,bdata::distribution=std::uniform_real_distribution<>(0.4_GeV, 10_GeV)))^bdata::random((bdata::seed=1,bdata::distribution=std::uniform_real_distribution<>(-M_PI, M_PI)))^bdata::random((bdata::seed=2,bdata::distribution=std::uniform_real_distribution<>(1.0, M_PI-1.0)))^bdata::random((bdata::seed=3,bdata::distribution=std::uniform_int_distribution<>(0, 1)))^bdata::random((bdata::seed=4,bdata::distribution=std::uniform_int_distribution<>(0, 100)))^bdata::xrange(ntests, pT , phi , theta , charge , time , index)
a covariance matrix to transport
Definition at line 226 of file PropagatorTests.cpp.
View newest version in sPHENIX GitHub at line 226 of file PropagatorTests.cpp
References charge(), CHECK_CLOSE_OR_SMALL, CHECK_CLOSE_REL, cov, Acts::UnitConstants::e, Acts::IntegrationTest::epropagator(), i, index, j, Acts::VectorHelpers::makeVector4(), Acts::PropagatorPlainOptions::maxStepSize, Acts::IntegrationTest::mfContext, Acts::PropagatorPlainOptions::pathLimit, ActsTests::PropagationDatasets::phi, Acts::ParticleHypothesis::pion(), pos, Acts::Propagator< stepper_t, navigator_t >::propagate(), graph_fancy::pT, start, Acts::tgContext, ActsTests::PropagationDatasets::theta, time, ambiguity_solver_full_chain::x, y, and physmon_track_finding_ttbar::z.
Acts::Test::BOOST_DATA_TEST_CASE (CylinderVolumeBuilder_overlapsInZ , bdata:: random-11.,-15.)^bdata::random(11., 15.)^bdata::random(0., 4.)^bdata::xrange(100, left , right , inner , index)
Unit test for testing the coverlapsInZ() function of the CylinderVolumeBuilder
Definition at line 249 of file CylinderVolumeBuilderTests.cpp.
View newest version in sPHENIX GitHub at line 249 of file CylinderVolumeBuilderTests.cpp
References index, left(), Acts::VolumeConfig::overlapsInZ(), Acts::VolumeConfig::present, Acts::VolumeConfig::rMax, Acts::VolumeConfig::rMin, Acts::VolumeConfig::zMax, and Acts::VolumeConfig::zMin.
Acts::Test::BOOST_DATA_TEST_CASE (bfield_symmetry_random , bdata:: random(bdata::seed=0,bdata::distribution=std::uniform_real_distribution<>(-10., 10.)))^bdata::random((bdata::seed=0,bdata::distribution=std::uniform_real_distribution<>(-10., 10.)))^bdata::random((bdata::seed=0,bdata::distribution=std::uniform_real_distribution<>(-20., 20.)))^bdata::xrange(10, x , y , z , index)
Unit test for symmetric data.
Definition at line 247 of file BFieldMapUtilsTests.cpp.
View newest version in sPHENIX GitHub at line 247 of file BFieldMapUtilsTests.cpp
References CHECK_CLOSE_ABS, CHECK_CLOSE_REL, Acts::UnitConstants::e, Acts::fieldMapRZ(), Acts::fieldMapXYZ(), i, index, maxR, maxZ, Acts::VectorHelpers::perp(), pos4(), ambiguity_solver_full_chain::x, y, and physmon_track_finding_ttbar::z.
Acts::Test::BOOST_DATA_TEST_CASE (loop_protection_test , bdata:: random(bdata::seed=20,bdata::distribution=std::uniform_real_distribution<>(0.1_GeV, 0.5_GeV)))^bdata::random((bdata::seed=21,bdata::distribution=std::uniform_real_distribution<>(-M_PI, M_PI)))^bdata::random((bdata::seed=22,bdata::distribution=std::uniform_real_distribution<>(1.0, M_PI-1.0)))^bdata::random((bdata::seed=23,bdata::distribution=std::uniform_int_distribution<>(0, 1)))^bdata::random((bdata::seed=24,bdata::distribution=std::uniform_int_distribution<>(0, 100)))^bdata::xrange(ntests, pT , phi , theta , charge , time , index)
a covariance matrix to transport
Definition at line 247 of file ExtrapolatorTests.cpp.
View newest version in sPHENIX GitHub at line 247 of file ExtrapolatorTests.cpp
References Acts::IntegrationTest::bCache, Acts::IntegrationTest::bField, charge(), CHECK_CLOSE_REL, cov, Acts::UnitConstants::e, Acts::IntegrationTest::epropagator(), index, Acts::PropagatorPlainOptions::maxStepSize, Acts::IntegrationTest::mfContext, ckf::options, merge_hashes::p, Acts::PropagatorPlainOptions::pathLimit, ActsTests::PropagationDatasets::phi, Acts::ParticleHypothesis::pion(), Acts::GenericCurvilinearTrackParameters< particle_hypothesis_t >::position(), Acts::Propagator< stepper_t, navigator_t >::propagate(), graph_fancy::pT, start, utils::status, Acts::tgContext, ActsTests::PropagationDatasets::theta, time, and value.
Acts::Test::BOOST_DATA_TEST_CASE (cylinder_additive_ , bdata:: random(bdata::seed=0,bdata::distribution=std::uniform_real_distribution<>(0.4_GeV, 10_GeV)))^bdata::random((bdata::seed=1,bdata::distribution=std::uniform_real_distribution<>(-M_PI, M_PI)))^bdata::random((bdata::seed=2,bdata::distribution=std::uniform_real_distribution<>(1.0, M_PI-1.0)))^bdata::random((bdata::seed=3,bdata::distribution=std::uniform_int_distribution<>(0, 1)))^bdata::random((bdata::seed=4,bdata::distribution=std::uniform_int_distribution<>(0, 100)))^bdata::xrange(ntests, pT , phi , theta , charge , time , index)
a covariance matrix to transport
Definition at line 303 of file PropagatorTests.cpp.
View newest version in sPHENIX GitHub at line 303 of file PropagatorTests.cpp
References charge(), CHECK_CLOSE_OR_SMALL, CHECK_CLOSE_REL, cov, cSurface, Acts::UnitConstants::e, Acts::IntegrationTest::epropagator(), i, index, j, Acts::VectorHelpers::makeVector4(), Acts::PropagatorPlainOptions::maxStepSize, Acts::IntegrationTest::mfContext, mSurface, Acts::PropagatorPlainOptions::pathLimit, ActsTests::PropagationDatasets::phi, Acts::ParticleHypothesis::pion(), pos, Acts::Propagator< stepper_t, navigator_t >::propagate(), graph_fancy::pT, start, Acts::tgContext, ActsTests::PropagationDatasets::theta, time, ambiguity_solver_full_chain::x, y, and physmon_track_finding_ttbar::z.
Acts::Test::BOOST_DATA_TEST_CASE (test_material_collector , bdata:: random(bdata::seed=20,bdata::distribution=std::uniform_real_distribution<>(0.5_GeV, 10_GeV)))^bdata::random((bdata::seed=21,bdata::distribution=std::uniform_real_distribution<>(-M_PI, M_PI)))^bdata::random((bdata::seed=22,bdata::distribution=std::uniform_real_distribution<>(1.0, M_PI-1.0)))^bdata::random((bdata::seed=23,bdata::distribution=std::uniform_int_distribution<>(0, 1)))^bdata::random((bdata::seed=24,bdata::distribution=std::uniform_int_distribution<>(0, 100)))^bdata::xrange(ntests, pT , phi , theta , charge , time , index)
Definition at line 395 of file MaterialCollectionTests.cpp.
View newest version in sPHENIX GitHub at line 395 of file MaterialCollectionTests.cpp
References charge(), Acts::IntegrationTest::epropagator(), index, ActsTests::PropagationDatasets::phi, graph_fancy::pT, runTest(), slpropagator(), ActsTests::PropagationDatasets::theta, and time.
Acts::Test::BOOST_FIXTURE_TEST_CASE (SurfaceArray_create , SurfaceArrayFixture)
Definition at line 189 of file SurfaceArrayTests.cpp.
View newest version in sPHENIX GitHub at line 189 of file SurfaceArrayTests.cpp
References Acts::SurfaceArray::at(), Acts::binR, Acts::SurfaceArray::SurfaceGridLookup< Axes >::completeBinning(), draw_surfaces(), Acts::SurfaceArray::SurfaceGridLookup< Axes >::fill(), loc, std::tr1::make_tuple(), testing::internal::move(), Acts::SurfaceArray::neighbors(), ActsTests::PropagationDatasets::phi, pos, Acts::IntegrationTest::R, tgContext, Acts::SurfaceArray::toStream(), transform, physmon_ckf_tracking::u, and Acts::unpack_shared_vector().
Acts::Test::BOOST_FIXTURE_TEST_CASE (size_1 , TreeFixture1DDoubleInt1)
Definition at line 203 of file KDTreeTests.cpp.
View newest version in sPHENIX GitHub at line 203 of file KDTreeTests.cpp
References tree.
Acts::Test::BOOST_FIXTURE_TEST_CASE (size_2 , TreeFixture1DDoubleInt2)
Definition at line 207 of file KDTreeTests.cpp.
View newest version in sPHENIX GitHub at line 207 of file KDTreeTests.cpp
References tree.
Acts::Test::BOOST_FIXTURE_TEST_CASE (size_3 , TreeFixture2DDoubleInt1)
Definition at line 211 of file KDTreeTests.cpp.
View newest version in sPHENIX GitHub at line 211 of file KDTreeTests.cpp
References tree.
Acts::Test::BOOST_FIXTURE_TEST_CASE (size_4 , TreeFixture3DDoubleInt1)
Definition at line 215 of file KDTreeTests.cpp.
View newest version in sPHENIX GitHub at line 215 of file KDTreeTests.cpp
References tree.
Acts::Test::BOOST_FIXTURE_TEST_CASE (size_5 , TreeFixture10DDoubleInt1)
Definition at line 219 of file KDTreeTests.cpp.
View newest version in sPHENIX GitHub at line 219 of file KDTreeTests.cpp
References tree.
Acts::Test::BOOST_FIXTURE_TEST_CASE (size_6 , TreeFixture3DDoubleString1)
Definition at line 223 of file KDTreeTests.cpp.
View newest version in sPHENIX GitHub at line 223 of file KDTreeTests.cpp
References tree.
Acts::Test::BOOST_FIXTURE_TEST_CASE (size_7 , TreeFixture1DIntInt1)
Definition at line 227 of file KDTreeTests.cpp.
View newest version in sPHENIX GitHub at line 227 of file KDTreeTests.cpp
References tree.
Acts::Test::BOOST_FIXTURE_TEST_CASE (size_8 , TreeFixture3DDoubleInt2)
Definition at line 231 of file KDTreeTests.cpp.
View newest version in sPHENIX GitHub at line 231 of file KDTreeTests.cpp
References tree.
Acts::Test::BOOST_FIXTURE_TEST_CASE (range_search_1 , TreeFixture1DDoubleInt2)
Definition at line 235 of file KDTreeTests.cpp.
View newest version in sPHENIX GitHub at line 235 of file KDTreeTests.cpp
References tree.
Acts::Test::BOOST_FIXTURE_TEST_CASE (LayerCreator_createCylinderLayer , LayerCreatorFixture)
Definition at line 247 of file LayerCreatorTests.cpp.
View newest version in sPHENIX GitHub at line 247 of file LayerCreatorTests.cpp
References Acts::binR, Acts::binZ, bounds, CHECK_CLOSE_REL, draw_surfaces(), boost::dynamic_pointer_cast(), Acts::UnitConstants::e, Acts::CylinderBounds::eHalfLengthZ, Acts::ProtoLayer::envelope, Acts::equidistant, Acts::CylinderBounds::eR, Acts::ProtoLayer::extent, Acts::CylinderBounds::get(), layer, Acts::Extent::range(), Acts::Range1D< Type >::set(), tgContext, and physmon_ckf_tracking::u.
Acts::Test::BOOST_FIXTURE_TEST_CASE (range_search_2 , TreeFixture1DDoubleInt2)
Definition at line 249 of file KDTreeTests.cpp.
View newest version in sPHENIX GitHub at line 249 of file KDTreeTests.cpp
References tree.
Acts::Test::BOOST_FIXTURE_TEST_CASE (range_search_3 , TreeFixture1DDoubleInt2)
Definition at line 264 of file KDTreeTests.cpp.
View newest version in sPHENIX GitHub at line 264 of file KDTreeTests.cpp
References tree.
Acts::Test::BOOST_FIXTURE_TEST_CASE (range_search_4 , TreeFixture2DDoubleInt1)
Definition at line 272 of file KDTreeTests.cpp.
View newest version in sPHENIX GitHub at line 272 of file KDTreeTests.cpp
References tree.
Acts::Test::BOOST_FIXTURE_TEST_CASE (SurfaceArrayCreator_createEquidistantAxis_Phi , SurfaceArrayCreatorFixture)
Definition at line 277 of file SurfaceArrayCreatorTests.cpp.
View newest version in sPHENIX GitHub at line 277 of file SurfaceArrayCreatorTests.cpp
References Acts::binPhi, CHECK_CLOSE_ABS, CHECK_CLOSE_REL, CHECK_SMALL, draw_surfaces(), Acts::UnitConstants::e, Acts::equidistant, i, ActsTests::PropagationDatasets::phi, step(), tgContext, physmon_ckf_tracking::u, Acts::unpack_shared_vector(), and physmon_track_finding_ttbar::z.
Acts::Test::BOOST_FIXTURE_TEST_CASE (range_search_5 , TreeFixture2DDoubleInt1)
Definition at line 282 of file KDTreeTests.cpp.
View newest version in sPHENIX GitHub at line 282 of file KDTreeTests.cpp
References tree.
Acts::Test::BOOST_FIXTURE_TEST_CASE (range_search_6 , TreeFixture10DDoubleInt1)
Definition at line 293 of file KDTreeTests.cpp.
View newest version in sPHENIX GitHub at line 293 of file KDTreeTests.cpp
References tree.
Acts::Test::BOOST_FIXTURE_TEST_CASE (range_search_7 , TreeFixture10DDoubleInt1)
Definition at line 306 of file KDTreeTests.cpp.
View newest version in sPHENIX GitHub at line 306 of file KDTreeTests.cpp
References tree.
Acts::Test::BOOST_FIXTURE_TEST_CASE (range_search_8 , TreeFixture3DDoubleString1)
Definition at line 316 of file KDTreeTests.cpp.
View newest version in sPHENIX GitHub at line 316 of file KDTreeTests.cpp
References tree.
Acts::Test::BOOST_FIXTURE_TEST_CASE (range_search_9 , TreeFixture3DDoubleString1)
Definition at line 328 of file KDTreeTests.cpp.
View newest version in sPHENIX GitHub at line 328 of file KDTreeTests.cpp
References tree.
Acts::Test::BOOST_FIXTURE_TEST_CASE (LayerCreator_createDiscLayer , LayerCreatorFixture)
Definition at line 340 of file LayerCreatorTests.cpp.
View newest version in sPHENIX GitHub at line 340 of file LayerCreatorTests.cpp
References Acts::binR, Acts::binZ, bounds, CHECK_CLOSE_REL, draw_surfaces(), boost::dynamic_pointer_cast(), Acts::UnitConstants::e, Acts::ProtoLayer::envelope, Acts::equidistant, Acts::ProtoLayer::extent, layer, Acts::IntegrationTest::nBinsR, Acts::Extent::range(), Acts::Range1D< Type >::set(), tgContext, and physmon_ckf_tracking::u.
Acts::Test::BOOST_FIXTURE_TEST_CASE (range_search_10 , TreeFixture1DIntInt1)
Definition at line 346 of file KDTreeTests.cpp.
View newest version in sPHENIX GitHub at line 346 of file KDTreeTests.cpp
References tree.
Acts::Test::BOOST_FIXTURE_TEST_CASE (range_search_11 , TreeFixture2DIntInt1)
Definition at line 356 of file KDTreeTests.cpp.
View newest version in sPHENIX GitHub at line 356 of file KDTreeTests.cpp
References tree.
Acts::Test::BOOST_FIXTURE_TEST_CASE (range_search_inplace_1 , TreeFixture10DDoubleInt1)
Definition at line 366 of file KDTreeTests.cpp.
View newest version in sPHENIX GitHub at line 366 of file KDTreeTests.cpp
References tree.
Acts::Test::BOOST_FIXTURE_TEST_CASE (range_search_inserter_1 , TreeFixture10DDoubleInt1)
Definition at line 381 of file KDTreeTests.cpp.
View newest version in sPHENIX GitHub at line 381 of file KDTreeTests.cpp
References tree.
Acts::Test::BOOST_FIXTURE_TEST_CASE (range_search_map_1 , TreeFixture10DDoubleInt1)
Definition at line 396 of file KDTreeTests.cpp.
View newest version in sPHENIX GitHub at line 396 of file KDTreeTests.cpp
References i, and tree.
Acts::Test::BOOST_FIXTURE_TEST_CASE (range_search_map_inserter_1 , TreeFixture10DDoubleInt1)
Definition at line 412 of file KDTreeTests.cpp.
View newest version in sPHENIX GitHub at line 412 of file KDTreeTests.cpp
References i, to_string(), and tree.
Acts::Test::BOOST_FIXTURE_TEST_CASE (LayerCreator_barrelStagger , LayerCreatorFixture)
Definition at line 428 of file LayerCreatorTests.cpp.
View newest version in sPHENIX GitHub at line 428 of file LayerCreatorTests.cpp
References Acts::binR, Acts::binZ, draw_surfaces(), boost::dynamic_pointer_cast(), Acts::ProtoLayer::envelope, Acts::equidistant, Acts::SurfaceArray::getAxes(), layer, Acts::Layer::surfaceArray(), tgContext, and physmon_ckf_tracking::u.
Acts::Test::BOOST_FIXTURE_TEST_CASE (range_search_map_inserter_2 , TreeFixture2DIntInt1)
Definition at line 433 of file KDTreeTests.cpp.
View newest version in sPHENIX GitHub at line 433 of file KDTreeTests.cpp
References Acts::PhysicalConstants::c, i, and tree.
Acts::Test::BOOST_FIXTURE_TEST_CASE (range_search_map_discard_1 , TreeFixture2DIntInt1)
Definition at line 450 of file KDTreeTests.cpp.
View newest version in sPHENIX GitHub at line 450 of file KDTreeTests.cpp
References Acts::PhysicalConstants::c, i, and tree.
Acts::Test::BOOST_FIXTURE_TEST_CASE (SurfaceArrayCreator_createEquidistantAxis_Z , SurfaceArrayCreatorFixture)
Definition at line 455 of file SurfaceArrayCreatorTests.cpp.
View newest version in sPHENIX GitHub at line 455 of file SurfaceArrayCreatorTests.cpp
References Acts::binZ, CHECK_CLOSE_ABS, draw_surfaces(), Acts::UnitConstants::e, Acts::equidistant, material_mapping_optimisation::format, i, str, tgContext, physmon_ckf_tracking::u, and Acts::unpack_shared_vector().
Acts::Test::BOOST_FIXTURE_TEST_CASE (range_search_map_discard_2 , TreeFixture3DDoubleInt2)
Definition at line 464 of file KDTreeTests.cpp.
View newest version in sPHENIX GitHub at line 464 of file KDTreeTests.cpp
References i, and tree.
Acts::Test::BOOST_FIXTURE_TEST_CASE (range_search_combinatorial , TreeFixture3DDoubleInt2)
Definition at line 476 of file KDTreeTests.cpp.
View newest version in sPHENIX GitHub at line 476 of file KDTreeTests.cpp
References Acts::PhysicalConstants::c, i, j, tree, Acts::IntegrationTest::valid(), xmax, xmin, ymax, and ymin.
Acts::Test::BOOST_FIXTURE_TEST_CASE (SurfaceArrayCreator_createEquidistantAxis_R , SurfaceArrayCreatorFixture)
Definition at line 507 of file SurfaceArrayCreatorTests.cpp.
View newest version in sPHENIX GitHub at line 507 of file SurfaceArrayCreatorTests.cpp
References Acts::binR, CHECK_CLOSE_ABS, CHECK_CLOSE_REL, draw_surfaces(), Acts::UnitConstants::e, Acts::equidistant, Acts::VectorHelpers::perp(), tgContext, physmon_ckf_tracking::u, and Acts::unpack_shared_vector().
Acts::Test::BOOST_FIXTURE_TEST_CASE (range_search_dominate1 , TreeFixture3DDoubleInt3)
Definition at line 516 of file KDTreeTests.cpp.
View newest version in sPHENIX GitHub at line 516 of file KDTreeTests.cpp
References tree.
Acts::Test::BOOST_FIXTURE_TEST_CASE (range_search_dominate2 , TreeFixture3DDoubleInt3)
Definition at line 528 of file KDTreeTests.cpp.
View newest version in sPHENIX GitHub at line 528 of file KDTreeTests.cpp
References tree.
Acts::Test::BOOST_FIXTURE_TEST_CASE (SurfaceArrayCreator_dependentBinCounts , SurfaceArrayCreatorFixture)
Definition at line 549 of file SurfaceArrayCreatorTests.cpp.
View newest version in sPHENIX GitHub at line 549 of file SurfaceArrayCreatorTests.cpp
References draw_surfaces(), Acts::GeometryView3D::drawSurfaceArray(), Acts::equidistant, tgContext, and physmon_ckf_tracking::u.
Acts::Test::BOOST_FIXTURE_TEST_CASE (SurfaceArrayCreator_completeBinning , SurfaceArrayCreatorFixture)
Definition at line 573 of file SurfaceArrayCreatorTests.cpp.
View newest version in sPHENIX GitHub at line 573 of file SurfaceArrayCreatorTests.cpp
References Acts::SurfaceArray::at(), Acts::binR, draw_surfaces(), Acts::GeometryView3D::drawSurfaceArray(), Acts::SurfaceArray::SurfaceGridLookup< Axes >::fill(), loc, std::tr1::make_tuple(), testing::internal::move(), ActsTests::PropagationDatasets::phi, pos, Acts::IntegrationTest::R, tgContext, physmon_ckf_tracking::u, Acts::unpack_shared_vector(), and Acts::ObjVisualization3D< T >::write().
Acts::Test::BOOST_FIXTURE_TEST_CASE (SurfaceArrayCreator_barrelStagger , SurfaceArrayCreatorFixture)
Definition at line 615 of file SurfaceArrayCreatorTests.cpp.
View newest version in sPHENIX GitHub at line 615 of file SurfaceArrayCreatorTests.cpp
References Acts::SurfaceArray::at(), Acts::binPhi, Acts::binR, Acts::binZ, CHECK_CLOSE_ABS, draw_surfaces(), Acts::UnitConstants::e, Acts::SurfaceArray::getAxes(), loc, testing::internal::move(), ActsTests::PropagationDatasets::phi, pos, Acts::IntegrationTest::R, tgContext, physmon_ckf_tracking::u, and Acts::unpack_shared_vector().
bool Acts::Test::cellComp (const Cell1D & left, const Cell1D & right)
Definition at line 33 of file ClusterizationTests1D.cpp.
View newest version in sPHENIX GitHub at line 33 of file ClusterizationTests1D.cpp
References Acts::Test::Cell1D::col.
Referenced by hash().
bool Acts::Test::cellComp (const Cell2D & left, const Cell2D & right)
Definition at line 104 of file ClusterizationTests2D.cpp.
View newest version in sPHENIX GitHub at line 104 of file ClusterizationTests2D.cpp
References Acts::Test::Cell2D::col, and Acts::Test::Cell2D::row.
CylindricalTrackingGeometry Acts::Test::cGeometry (tgContext)
template<typename T , typename U > boost::test_tools::predicate_result Acts::Test::checkCloseAbs (const T & val, const U & ref, double abstol)
Definition at line 251 of file FloatComparisons.hpp.
View newest version in sPHENIX GitHub at line 251 of file FloatComparisons.hpp
References Acts::Test::float_compare_internal::closeAbs(), and Acts::Test::float_compare_internal::compare().
Referenced by BOOST_AUTO_TEST_CASE().
template<typename val_t , typename ref_t > boost::test_tools::predicate_result Acts::Test::checkCloseCovariance (const Eigen::MatrixBase< val_t > & val, const Eigen::MatrixBase< ref_t > & ref, double tol)
Definition at line 273 of file FloatComparisons.hpp.
View newest version in sPHENIX GitHub at line 273 of file FloatComparisons.hpp
References assert, col, and check_smearing_config::ref.
template<typename T , typename U > boost::test_tools::predicate_result Acts::Test::checkCloseOrSmall (const T & val, const U & ref, double reltol, double small)
Definition at line 264 of file FloatComparisons.hpp.
View newest version in sPHENIX GitHub at line 264 of file FloatComparisons.hpp
References Acts::Test::float_compare_internal::closeOrSmall(), and Acts::Test::float_compare_internal::compare().
template<typename T , typename U > boost::test_tools::predicate_result Acts::Test::checkCloseRel (const T & val, const U & ref, double reltol)
Definition at line 244 of file FloatComparisons.hpp.
View newest version in sPHENIX GitHub at line 244 of file FloatComparisons.hpp
References Acts::Test::float_compare_internal::closeOrSmall(), and Acts::Test::float_compare_internal::compare().
template<typename T > boost::test_tools::predicate_result Acts::Test::checkSmall (const T & val, double small)
Definition at line 258 of file FloatComparisons.hpp.
View newest version in sPHENIX GitHub at line 258 of file FloatComparisons.hpp
References Acts::Test::float_compare_internal::closeOrSmall(), and Acts::Test::float_compare_internal::compare().
bool Acts::Test::clHashComp (const Cluster1D & left, const Cluster1D & right)
Definition at line 54 of file ClusterizationTests1D.cpp.
View newest version in sPHENIX GitHub at line 54 of file ClusterizationTests1D.cpp
References Acts::Test::Cluster1D::hash.
Referenced by BOOST_AUTO_TEST_CASE().
bool Acts::Test::clHashComp (const Cluster2D & left, const Cluster2D & right)
Definition at line 125 of file ClusterizationTests2D.cpp.
View newest version in sPHENIX GitHub at line 125 of file ClusterizationTests2D.cpp
References Acts::Test::Cluster2D::hash.
void Acts::Test::clusterAddCell (Cluster1D & cl, const Cell1D & cell)
Definition at line 50 of file ClusterizationTests1D.cpp.
View newest version in sPHENIX GitHub at line 50 of file ClusterizationTests1D.cpp
References Acts::Test::Cluster1D::cells.
Referenced by BOOST_AUTO_TEST_CASE().
void Acts::Test::clusterAddCell (Cluster2D & cl, const Cell2D & cell)
Definition at line 113 of file ClusterizationTests2D.cpp.
View newest version in sPHENIX GitHub at line 113 of file ClusterizationTests2D.cpp
References Acts::Test::Cluster2D::cells.
std::vector<Rectangle> Acts::Test::concat (std::vector< std::vector< Rectangle >> vecs)
Definition at line 32 of file ClusterizationTests2D.cpp.
View newest version in sPHENIX GitHub at line 32 of file ClusterizationTests2D.cpp
References testing::internal::move(), and testSigmaEff::v.
Referenced by segment().
BoundToFreeMatrix Acts::Test::convertToMatrix (const std::array< double, 60 > P)
Helper method : convert into Acts matrix It takes the double array from AtlasStepper and transforms it into an ActsMatrixD
Parameters
P is the pointer to the array
Translation is (for lookup) /dL0 /dL1 /dPhi /dThe /dCM /dT X ->P[0] dX / P[ 8] P[16] P[24] P[32] P[40] P[48] Y ->P[1] dY / P[ 9] P[17] P[25] P[33] P[41] P[49] Z ->P[2] dZ / P[10] P[18] P[26] P[34] P[42] P[50] T ->P[3] dT/ P[11] P[19] P[27] P[35] P[43] P[51] Ax ->P[4] dAx/ P[12] P[20] P[28] P[36] P[44] P[52] Ay ->P[5] dAy/ P[13] P[21] P[29] P[37] P[45] P[53] Az ->P[6] dAz/ P[14] P[22] P[30] P[38] P[46] P[54] CM ->P[7] dCM/ P[15] P[23] P[31] P[39] P[47] P[55]
Definition at line 121 of file JacobianTests.cpp.
View newest version in sPHENIX GitHub at line 121 of file JacobianTests.cpp
References Acts::eBoundSize, Acts::eFreeSize, i, and j.
Referenced by testJacobianToGlobal().
Transform3 Acts::Test::createCylindricTransform (const Vector3 & nposition, double angleX, double angleY)
Helper method to create a transform for a plane to mimic detector situations, the plane is roughly perpendicular to the track
Parameters
nnomal The nominal normal direction
angleT Rotation around the norminal normal
angleU Rotation around the original U axis
Definition at line 64 of file JacobianTests.cpp.
View newest version in sPHENIX GitHub at line 64 of file JacobianTests.cpp
Referenced by BOOST_AUTO_TEST_CASE().
template<typename propagator_t , typename track_parameters_t > Measurements Acts::Test::createMeasurements (const propagator_t & propagator, const Acts::GeometryContext & geoCtx, const Acts::MagneticFieldContext & magCtx, const track_parameters_t & trackParameters, const MeasurementResolutionMap & resolutions, std::default_random_engine & rng, size_t sourceId = 0u)
Propagate the track create smeared measurements from local coordinates.
Definition at line 153 of file MeasurementsCreator.hpp.
View newest version in sPHENIX GitHub at line 153 of file MeasurementsCreator.hpp
References Acts::PropagatorOptions< action_list_t, aborter_list_t >::actionList, testing::internal::move(), ckf::options, Acts::Test::MeasurementsCreator::resolutions, Acts::Test::MeasurementsCreator::rng, and Acts::Test::MeasurementsCreator::sourceId.
Referenced by BOOST_AUTO_TEST_CASE(), BOOST_AUTO_TEST_CASE(), BOOST_DATA_TEST_CASE(), FitterTester::test_GlobalCovariance(), FitterTester::test_ZeroFieldNoSurfaceForward(), FitterTester::test_ZeroFieldShuffled(), FitterTester::test_ZeroFieldWithHole(), FitterTester::test_ZeroFieldWithOutliers(), FitterTester::test_ZeroFieldWithReverseFiltering(), FitterTester::test_ZeroFieldWithSurfaceAtExit(), FitterTester::test_ZeroFieldWithSurfaceBackward(), and FitterTester::test_ZeroFieldWithSurfaceForward().
Transform3 Acts::Test::createPlanarTransform (const Vector3 & nposition, const Vector3 & nnormal, double angleT, double angleU)
Helper method to create a transform for a plane to mimic detector situations, the plane is roughly perpendicular to the track
Parameters
nnomal The nominal normal direction
angleT Rotation around the norminal normal
angleU Rotation around the original U axis
Definition at line 81 of file JacobianTests.cpp.
View newest version in sPHENIX GitHub at line 81 of file JacobianTests.cpp
References Acts::UnitConstants::T.
Referenced by BOOST_AUTO_TEST_CASE().
std::uniform_real_distribution Acts::Test::d0Dist (-0. 01_mm, 0. 01_mm)
Referenced by BOOST_AUTO_TEST_CASE().
void Acts::Test::debug_level_test (const char * output_file, Logging::Level lvl)
unit test for a certain debug level
This test checks for the expected output when using the specified debug level as threshold. It also tests
ACTS_LOCAL_LOGGER
Acts::getDefaultLogger
Definition at line 52 of file LoggerTests.cpp.
View newest version in sPHENIX GitHub at line 52 of file LoggerTests.cpp
References ACTS_DEBUG, ACTS_ERROR, ACTS_FATAL, ACTS_INFO, ACTS_LOCAL_LOGGER, Acts::ACTS_VERBOSE(), ACTS_WARNING, DEBUG, Acts::Logging::ERROR, Acts::Logging::FATAL, Acts::Logging::getFailureThreshold(), i, in, infile, Acts::Logging::INFO, line, test_fpe::lines, Acts::Logging::MAX, testing::internal::move(), perf_headwind::name, train_ambiguity_solver::test, test_base::test_logging(), VERBOSE, and Acts::Logging::WARNING.
Referenced by BOOST_AUTO_TEST_CASE().
DirectPropagator Acts::Test::dpropagator (std:: movedstepper, std:: movednavigator)
Referenced by BOOST_DATA_TEST_CASE().
void Acts::Test::draw_surfaces (const SrfVec & surfaces, const std::string & fname)
Definition at line 66 of file LayerCreatorTests.cpp.
View newest version in sPHENIX GitHub at line 66 of file LayerCreatorTests.cpp
References bounds, boost::dynamic_pointer_cast(), i, os, and tgContext.
Referenced by BOOST_FIXTURE_TEST_CASE().
void Acts::Test::dumpVertices (const RectangleBounds & r)
Definition at line 32 of file RectangleBoundsTests.cpp.
View newest version in sPHENIX GitHub at line 32 of file RectangleBoundsTests.cpp
References i, testSigmaEff::v, and Acts::RectangleBounds::vertices().
EigenPropagatorType Acts::Test::epropagator (std:: moveestepper, std:: movenavigator)
EigenPropagator Acts::Test::epropagator (std:: moveestepper, std:: movenavigatorES)
EigenPropagatorType Acts::Test::epropagator (std:: moveestepper)
EigenStepperType Acts::Test::estepper (bField)
Vector3 Acts::Test::eta0Position (0. 5, 1. 5, 0.)
Referenced by BOOST_AUTO_TEST_CASE().
std::uniform_real_distribution< double > Acts::Test::etaDist (- 4., 4.)
Referenced by BOOST_AUTO_TEST_CASE(), BOOST_AUTO_TEST_CASE(), ActsExamples::PropagationAlgorithm::execute(), and ActsExamples::ParametricParticleGenerator::operator()().
template<typename trajectory_t , typename track_state_t > void Acts::Test::fillTrackState (const TestTrackState & pc, TrackStatePropMask mask, track_state_t & ts)
Definition at line 100 of file TestTrackState.hpp.
View newest version in sPHENIX GitHub at line 100 of file TestTrackState.hpp
References ACTS_CHECK_BIT, assert, Acts::Test::TestTrackState::chi2, Acts::GenericBoundTrackParameters< particle_hypothesis_t >::covariance(), Acts::Test::TestTrackState::filtered, Acts::Surface::getSharedPtr(), Acts::Test::TestTrackState::jacobian, Acts::GenericBoundTrackParameters< particle_hypothesis_t >::parameters(), Acts::Test::TestTrackState::pathLength, Acts::Test::TestTrackState::predicted, Acts::GenericBoundTrackParameters< particle_hypothesis_t >::referenceSurface(), Acts::Test::TestTrackState::smoothed, and Acts::Test::TestTrackState::sourceLink.
template<typename RNG > Cluster2D Acts::Test::gencluster (int x0, int y0, int x1, int y1, RNG & rng, double startp = 0.5, double decayp = 0.9)
Definition at line 184 of file ClusterizationTests2D.cpp.
View newest version in sPHENIX GitHub at line 184 of file ClusterizationTests2D.cpp
References Acts::Test::Cluster2D::cells, genclusterw(), testing::internal::move(), rng(), ambiguity_solver_full_chain::x, and y.
Referenced by BOOST_AUTO_TEST_CASE().
template<typename RNG > void Acts::Test::genclusterw (int x, int y, int x0, int y0, int x1, int y1, std::vector< Cell2D > & cells, RNG & rng, double startp = 0.5, double decayp = 0.9)
Definition at line 130 of file ClusterizationTests2D.cpp.
View newest version in sPHENIX GitHub at line 130 of file ClusterizationTests2D.cpp
References Acts::PhysicalConstants::c, x_, and y_.
Referenced by gencluster().
template<typename generator_t > auto Acts::Test::generateBoundParametersCovariance (generator_t & rng) inline
Generate a random bound parameters vector and covariance matrix.
Definition at line 65 of file GenerateParameters.hpp.
View newest version in sPHENIX GitHub at line 65 of file GenerateParameters.hpp
References Acts::eBoundPhi, Acts::eBoundTheta, Acts::detail::normalizePhiTheta(), ActsTests::PropagationDatasets::phi, rng(), and ActsTests::PropagationDatasets::theta.
Referenced by BOOST_AUTO_TEST_CASE(), Acts::Test::TestTrackState::TestTrackState(), and Acts::Test::MultiTrajectoryTestsCommon< factory_t >::testTrackStateProxyCrossTalk().
template<typename generator_t > auto Acts::Test::generateFreeParametersCovariance (generator_t & rng) inline
Generate a random free parameters vector and covariance matrix.
Definition at line 76 of file GenerateParameters.hpp.
View newest version in sPHENIX GitHub at line 76 of file GenerateParameters.hpp
References rng().
Referenced by BOOST_AUTO_TEST_CASE(), and BOOST_DATA_TEST_CASE().
template<typename scalar_t , size_t kSize, typename generator_t > auto Acts::Test::generateParametersCovariance (generator_t & rng) -> std::pair<Eigen::Matrix<scalar_t, kSize, 1>, Eigen::Matrix<scalar_t, kSize, kSize>> inline
Generate a random parameters vector and covariance matrix.
Returns
std:::pair<ParametersVector, CovarianceMatrix>
Definition at line 25 of file GenerateParameters.hpp.
View newest version in sPHENIX GitHub at line 25 of file GenerateParameters.hpp
References corr, cov, i, j, rng(), and physmon_ckf_tracking::u.
int Acts::Test::getCellColumn (const Cell1D & cell)
Definition at line 41 of file ClusterizationTests1D.cpp.
View newest version in sPHENIX GitHub at line 41 of file ClusterizationTests1D.cpp
References Acts::Test::Cell1D::col.
int Acts::Test::getCellColumn (const Cell2D & cell)
Definition at line 92 of file ClusterizationTests2D.cpp.
View newest version in sPHENIX GitHub at line 92 of file ClusterizationTests2D.cpp
References Acts::Test::Cell2D::col.
Ccl::Label& Acts::Test::getCellLabel (Cell1D & cell)
Definition at line 37 of file ClusterizationTests1D.cpp.
View newest version in sPHENIX GitHub at line 37 of file ClusterizationTests1D.cpp
References Acts::Test::Cell1D::label.
Ccl::Label& Acts::Test::getCellLabel (Cell2D & cell)
Definition at line 96 of file ClusterizationTests2D.cpp.
View newest version in sPHENIX GitHub at line 96 of file ClusterizationTests2D.cpp
References Acts::Test::Cell2D::label.
int Acts::Test::getCellRow (const Cell2D & cell)
Definition at line 88 of file ClusterizationTests2D.cpp.
View newest version in sPHENIX GitHub at line 88 of file ClusterizationTests2D.cpp
References Acts::Test::Cell2D::row.
std::string Acts::Test::getDataPath (const std::string & relativePath)
Get the full path to a file in the test data directory.
Parameters
relativePath file path relative to the data directory
Definition at line 13 of file DataDirectory.cpp.
View newest version in sPHENIX GitHub at line 13 of file DataDirectory.cpp
References path.
Referenced by BOOST_AUTO_TEST_CASE(), main(), readTracksAndVertexCSV(), and Acts::Test::RootGeometry::RootGeometry().
template<typename T > T Acts::Test::getFromWhiteBoard (std::string name, ActsExamples::WhiteBoard & wb)
Definition at line 38 of file WhiteBoardUtilities.hpp.
View newest version in sPHENIX GitHub at line 38 of file WhiteBoardUtilities.hpp
References ActsExamples::ReadDataHandle< T >::initialize().
ViewConfig Acts::Test::green ({0, 200, 0})
void Acts::Test::hash (Cluster1D & cl)
Definition at line 58 of file ClusterizationTests1D.cpp.
View newest version in sPHENIX GitHub at line 58 of file ClusterizationTests1D.cpp
References Acts::PhysicalConstants::c, cellComp(), Acts::Test::Cluster1D::cells, Acts::Test::Cell1D::col, Acts::Test::Cluster1D::hash, and Acts::Experimental::detail::BlueprintHelper::sort().
Referenced by BOOST_AUTO_TEST_CASE(), and PHG4Utils::md5sum().
void Acts::Test::hash (Cluster2D & cl)
Definition at line 117 of file ClusterizationTests2D.cpp.
View newest version in sPHENIX GitHub at line 117 of file ClusterizationTests2D.cpp
References Acts::PhysicalConstants::c, cellComp(), Acts::Test::Cluster2D::cells, Acts::Test::Cell2D::col, Acts::Test::Cluster2D::hash, and Acts::Experimental::detail::BlueprintHelper::sort().
template<typename surface_t > MicroBenchmarkResult Acts::Test::intersectionTest (const surface_t & surface, double phi, double theta)
Definition at line 72 of file SurfaceIntersectionBenchmark.cpp.
View newest version in sPHENIX GitHub at line 72 of file SurfaceIntersectionBenchmark.cpp
References boundaryCheck, microBenchmark(), nrepts, origin(), and Acts::tgContext.
Result<NoCopy> Acts::Test::make_nocopy (int i, bool v = true)
Definition at line 254 of file ResultTests.cpp.
View newest version in sPHENIX GitHub at line 254 of file ResultTests.cpp
References i, and testSigmaEff::v.
Referenced by BOOST_AUTO_TEST_CASE().
Material Acts::Test::makeBeryllium () inline
Definition at line 21 of file PredefinedMaterials.hpp.
View newest version in sPHENIX GitHub at line 21 of file PredefinedMaterials.hpp
References Acts::Material::fromMolarDensity().
Referenced by BOOST_AUTO_TEST_CASE(), BOOST_DATA_TEST_CASE(), Acts::Test::CubicTrackingGeometry::CubicTrackingGeometry(), makeToyDetector(), and Acts::Test::CylindricalTrackingGeometry::operator()().
Acts::CurvilinearTrackParameters Acts::Test::makeParameters (const ActsScalar x = 0.0_m, const ActsScalar y = 0.0_m, const ActsScalar z = 0.0_m, const ActsScalar w = 42_ns, const ActsScalar phi = 0_degree, const ActsScalar theta = 90_degree, const ActsScalar p = 1_GeV, const ActsScalar q = 1_e)
Definition at line 48 of file Gx2fTests.cpp.
View newest version in sPHENIX GitHub at line 48 of file Gx2fTests.cpp
References cov, Acts::eBoundLoc0, Acts::eBoundLoc1, Acts::eBoundPhi, Acts::eBoundQOverP, Acts::eBoundTheta, Acts::eBoundTime, merge_hashes::p, ActsTests::PropagationDatasets::phi, Acts::ParticleHypothesis::pion(), ActsTests::PropagationDatasets::theta, ambiguity_solver_full_chain::x, y, and physmon_track_finding_ttbar::z.
CurvilinearTrackParameters Acts::Test::makeParameters (double phi, double theta, double p, double q)
Definition at line 63 of file SpacePointBuilderTests.cpp.
View newest version in sPHENIX GitHub at line 63 of file SpacePointBuilderTests.cpp
References cov, Acts::eBoundLoc0, Acts::eBoundLoc1, Acts::eBoundPhi, Acts::eBoundQOverP, Acts::eBoundTheta, Acts::eBoundTime, and Acts::ParticleHypothesis::pionLike().
Referenced by BOOST_AUTO_TEST_CASE(), BOOST_AUTO_TEST_CASE(), and BOOST_DATA_TEST_CASE().
MaterialSlab Acts::Test::makePercentSlab () inline
Build material slab corresponding to 1% of radiation and interaction length.
Definition at line 43 of file PredefinedMaterials.hpp.
View newest version in sPHENIX GitHub at line 43 of file PredefinedMaterials.hpp
References makeUnitSlab().
Referenced by BOOST_AUTO_TEST_CASE().
Covariance Acts::Test::makeRandomCovariance (int seed = 31415)
Definition at line 40 of file AdaptiveGridTrackDensityTests.cpp.
View newest version in sPHENIX GitHub at line 40 of file AdaptiveGridTrackDensityTests.cpp
References seed.
Referenced by BOOST_AUTO_TEST_CASE().
Material Acts::Test::makeSilicon () inline
Definition at line 27 of file PredefinedMaterials.hpp.
View newest version in sPHENIX GitHub at line 27 of file PredefinedMaterials.hpp
References Acts::Material::fromMolarDensity().
Referenced by BOOST_AUTO_TEST_CASE(), BOOST_AUTO_TEST_CASE(), BOOST_DATA_TEST_CASE(), Acts::EventDataView3DTest::createDetector(), Acts::Test::CylindricalTrackingGeometry::operator()(), Acts::Test::CylindricalTrackingGeometry::surfacesCylinder(), and Acts::Test::CylindricalTrackingGeometry::surfacesRing().
static StraightPropagator Acts::Test::makeStraightPropagator (std::shared_ptr< const TrackingGeometry > geo) static
Definition at line 130 of file SpacePointBuilderTests.cpp.
View newest version in sPHENIX GitHub at line 130 of file SpacePointBuilderTests.cpp
References cfg, testing::internal::move(), navigator, and propagation_timing::stepper.
std::shared_ptr<const TrackingGeometry> Acts::Test::makeToyDetector (const GeometryContext & tgContext, const size_t nSurfaces = 5)
Shape of the surface
Definition at line 77 of file Gx2fTests.cpp.
View newest version in sPHENIX GitHub at line 77 of file Gx2fTests.cpp
References Acts::CuboidVolumeBuilder::LayerConfig::active, bounds, cfg, filter::config, Acts::CuboidVolumeBuilder::SurfaceConfig::detElementConstructor, Acts::CuboidVolumeBuilder::LayerConfig::envelopeX, Acts::CuboidVolumeBuilder::LayerConfig::envelopeY, Acts::CuboidVolumeBuilder::LayerConfig::envelopeZ, i, Acts::CuboidVolumeBuilder::VolumeConfig::layerCfg, Acts::CuboidVolumeBuilder::VolumeConfig::length, Acts::CuboidVolumeBuilder::Config::length, Acts::UnitConstants::m, makeBeryllium(), Acts::CuboidVolumeBuilder::VolumeConfig::name, Acts::CuboidVolumeBuilder::SurfaceConfig::position, Acts::CuboidVolumeBuilder::VolumeConfig::position, Acts::CuboidVolumeBuilder::Config::position, Acts::CuboidVolumeBuilder::SurfaceConfig::rBounds, Acts::CuboidVolumeBuilder::SurfaceConfig::rotation, Acts::CuboidVolumeBuilder::setConfig(), Acts::CuboidVolumeBuilder::LayerConfig::surfaceCfg, Acts::CuboidVolumeBuilder::SurfaceConfig::surMat, thickness, Acts::CuboidVolumeBuilder::SurfaceConfig::thickness, Acts::TrackingGeometryBuilder::trackingGeometry(), Acts::CuboidVolumeBuilder::trackingVolume(), Acts::TrackingGeometryBuilder::Config::trackingVolumeBuilders, and Acts::CuboidVolumeBuilder::Config::volumeCfg.
Referenced by BOOST_AUTO_TEST_CASE().
TrackingGeometry Acts::Test::makeTrackingGeometry (const GeometryIdentifierHook & hook)
we test a two-level hierarchy every deeper level hierarchy is a derivate of this
WorldVolume with volumeID == 1
InnerVolume with volumeID == 2 – InnerInnerVolume with volumeID == 3 – InnerOuterVolume with volumeID == 4
OuterVolume with volumeID == 5
inner outer volume definitions
inner inner volume
inner outer volume
the inner volume
inner outer volume
the inner volume
Definition at line 38 of file TrackingGeometryClosureTests.cpp.
View newest version in sPHENIX GitHub at line 38 of file TrackingGeometryClosureTests.cpp
References Acts::constructContainerVolume(), Acts::constructCylinderVolume(), iVolume, oVolume, Acts::tgContext, and Acts::tGeometry.
Referenced by BOOST_AUTO_TEST_CASE().
MaterialSlab Acts::Test::makeUnitSlab () inline
Build material slab corresponding to 1 radiation and interaction length.
Definition at line 34 of file PredefinedMaterials.hpp.
View newest version in sPHENIX GitHub at line 34 of file PredefinedMaterials.hpp
References Acts::Material::fromMolarDensity().
Referenced by BOOST_AUTO_TEST_CASE(), BOOST_DATA_TEST_CASE(), and makePercentSlab().
Acts::Test::METHOD_TRAIT (foo_method_t , foo)
Acts::Test::METHOD_TRAIT (bar_method_t , bar)
template<typename Callable > MicroBenchmarkResult Acts::Test::microBenchmark (Callable && iteration, size_t iters_per_run, size_t num_runs = 20000, std::chrono::milliseconds warmup_time = std::chrono::milliseconds(2000))
Definition at line 520 of file BenchmarkTools.hpp.
View newest version in sPHENIX GitHub at line 520 of file BenchmarkTools.hpp
References Acts::Test::benchmark_tools_internal::MicroBenchmarkIter< Callable, Input >::iter(), and Acts::Test::benchmark_tools_internal::microBenchmarkImpl().
Referenced by BOOST_AUTO_TEST_CASE(), intersectionTest(), and main().
template<typename Callable , typename Input > MicroBenchmarkResult Acts::Test::microBenchmark (Callable && iterationWithInput, const std::vector< Input > & inputs, size_t num_runs = 20000, std::chrono::milliseconds warmup_time = std::chrono::milliseconds(2000))
Definition at line 540 of file BenchmarkTools.hpp.
View newest version in sPHENIX GitHub at line 540 of file BenchmarkTools.hpp
References digitization_config::input, Acts::Test::benchmark_tools_internal::MicroBenchmarkIter< Callable, Input >::iter(), and Acts::Test::benchmark_tools_internal::microBenchmarkImpl().
Navigator Acts::Test::navigator ({tGeometry})
std::uniform_int_distribution Acts::Test::nTracksDist (3 , 10)
Referenced by BOOST_AUTO_TEST_CASE().
std::uniform_int_distribution Acts::Test::nTracksDist (5 , 15)
std::uniform_int_distribution Acts::Test::nVertexDist (1 , 6)
Referenced by BOOST_AUTO_TEST_CASE().
Vector2 Acts::Test::offset (- 2., 2.)
Referenced by BOOST_AUTO_TEST_CASE(), and Acts::Test::MicroBenchmarkResult::runTimeQuartiles().
bool Acts::Test::operator!= (const TestSourceLink & lhs, const TestSourceLink & rhs)
Definition at line 21 of file TestSourceLink.cpp.
View newest version in sPHENIX GitHub at line 21 of file TestSourceLink.cpp
std::ostream & Acts::Test::operator<< (std::ostream & os, const TestSourceLink & sourceLink)
Definition at line 26 of file TestSourceLink.cpp.
View newest version in sPHENIX GitHub at line 26 of file TestSourceLink.cpp
References Acts::eBoundSize, Acts::Test::TestSourceLink::indices, Acts::Test::TestSourceLink::m_geometryId, os, and Acts::Test::TestSourceLink::sourceId.
bool Acts::Test::operator== (const TestSpacePoint & lhs, const TestSpacePoint & rhs) inline
Definition at line 71 of file TestSpacePoint.hpp.
View newest version in sPHENIX GitHub at line 71 of file TestSpacePoint.hpp
References Acts::Test::TestSpacePoint::sourceLinks(), Acts::Test::TestSpacePoint::varianceR(), Acts::Test::TestSpacePoint::varianceZ(), Acts::Test::TestSpacePoint::x(), Acts::Test::TestSpacePoint::y(), and Acts::Test::TestSpacePoint::z().
bool Acts::Test::operator== (const TestSourceLink & lhs, const TestSourceLink & rhs)
Definition at line 13 of file TestSourceLink.cpp.
View newest version in sPHENIX GitHub at line 13 of file TestSourceLink.cpp
References Acts::Test::TestSourceLink::covariance, Acts::Test::TestSourceLink::indices, Acts::Test::TestSourceLink::m_geometryId, Acts::Test::TestSourceLink::parameters, and Acts::Test::TestSourceLink::sourceId.
bool Acts::Test::operator== (const Cell2D & left, const Cell2D & right)
Definition at line 100 of file ClusterizationTests2D.cpp.
View newest version in sPHENIX GitHub at line 100 of file ClusterizationTests2D.cpp
References Acts::Test::Cell2D::col, and Acts::Test::Cell2D::row.
Vector3 Acts::Test::origin (0. , 0. , 0.)
Referenced by Acts::Test::Layers::BOOST_AUTO_TEST_CASE(), BOOST_AUTO_TEST_CASE(), PHG4EtaPhiParameterization::ComputeTransformation(), PHG4EtaParameterization::ComputeTransformation(), PHG4BeamlineMagnetDetector::ConstructMe(), BeamLineMagnetDetector::ConstructMe(), Acts::Polyhedron::extent(), TrackFitUtils::get_circle_point_pca(), IsolatedTrackAnalysis::getClusters(), Acts::AxisAlignedBoundingBox< entity_t, value_t, DIM >::intersect(), intersectionTest(), main(), PHTpcDeltaZCorrection::process_track(), TpcDirectLaserReconstruction::process_track(), Acts::PrimitivesView3DTest::run(), and ActsFatras::Channelizer::segments().
Vector3 Acts::Test::originStraw (0. 3_m, -0. 2_m, 11_m)
Vector3 Acts::Test::phi0Position (0. 5, 0. , 2. 5)
Referenced by BOOST_AUTO_TEST_CASE().
std::uniform_real_distribution Acts::Test::phiDist (- M_PI, M_PI)
Referenced by BOOST_AUTO_TEST_CASE(), BOOST_AUTO_TEST_CASE(), ActsExamples::VolumeAssociationTest::execute(), ActsExamples::PropagationAlgorithm::execute(), main(), and ActsExamples::ParametricParticleGenerator::operator()().
Vector3 Acts::Test::phiPihPosition (0. , 1. 5, 2. 5)
Referenced by BOOST_AUTO_TEST_CASE().
static const Vector4 Acts::Test::pos4 (1_mm , - 1_mm, 2_mm , 2_ns) static
Referenced by BOOST_AUTO_TEST_CASE(), BOOST_DATA_TEST_CASE(), BOOST_DATA_TEST_CASE(), Acts::AtlasStepper::boundState(), Acts::MultiComponentCurvilinearTrackParameters::construct(), Acts::detail::curvilinearState(), Acts::AtlasStepper::curvilinearState(), Acts::GenericFreeTrackParameters< particle_hypothesis_t >::fourPosition(), Acts::GenericBoundTrackParameters< ParticleHypothesis >::fourPosition(), main(), makeParametersCurvilinear(), makeParametersCurvilinearNeutral(), makeParametersCurvilinearWithCovariance(), makeTestSimhits(), ActsExamples::Pythia8Generator::operator()(), ActsExamples::CsvSimHitReader::read(), ActsExamples::RootSimHitReader::read(), ActsExamples::EventGenerator::read(), ActsExamples::EDM4hepUtil::readSimHit(), ActsFatras::Particle::setPosition4(), ActsExamples::SensitiveSteppingAction::UserSteppingAction(), and ActsExamples::RootMeasurementWriter::writeT().
static std::vector<Acts::SourceLink> Acts::Test::prepareSourceLinks (const std::vector< TestSourceLink > & sourceLinks) static
Definition at line 68 of file Gx2fTests.cpp.
View newest version in sPHENIX GitHub at line 68 of file Gx2fTests.cpp
References transform.
Referenced by BOOST_AUTO_TEST_CASE(), FitterTester::test_GlobalCovariance(), FitterTester::test_ZeroFieldNoSurfaceForward(), FitterTester::test_ZeroFieldShuffled(), FitterTester::test_ZeroFieldWithHole(), FitterTester::test_ZeroFieldWithOutliers(), FitterTester::test_ZeroFieldWithReverseFiltering(), FitterTester::test_ZeroFieldWithSurfaceAtExit(), FitterTester::test_ZeroFieldWithSurfaceBackward(), and FitterTester::test_ZeroFieldWithSurfaceForward().
std::uniform_real_distribution< double > Acts::Test::pTDist (0. 1_GeV, 100_GeV)
std::uniform_real_distribution Acts::Test::pTDist (0. 4_GeV, 10_GeV)
std::uniform_real_distribution Acts::Test::pTDist (1. _GeV, 30. _GeV)
Referenced by BOOST_AUTO_TEST_CASE().
std::uniform_real_distribution Acts::Test::qDist (- 1, 1)
Referenced by BOOST_AUTO_TEST_CASE(), BOOST_AUTO_TEST_CASE(), and ActsExamples::PropagationAlgorithm::execute().
std::tuple<Vertex<BoundTrackParameters>, std::vector<VertexInfo>, std::vector<BoundTrackParameters> > Acts::Test::readTracksAndVertexCSV (const std::string & toolString, const std::string & fileBase = "vertexing_event_mu20") inline
Definition at line 48 of file VertexingDataHelper.hpp.
View newest version in sPHENIX GitHub at line 48 of file VertexingDataHelper.hpp
References cov, Acts::Test::VertexInfo::covariance, getDataPath(), line, std::tr1::make_tuple(), testing::internal::move(), Acts::Test::VertexInfo::nTracks, Acts::ParticleHypothesis::pion(), pos, Acts::Test::VertexInfo::position, Acts::Vertex< input_track_t >::setCovariance(), Acts::Vertex< input_track_t >::setPosition(), tracks(), Acts::Test::VertexInfo::trk1Chi2, Acts::Test::VertexInfo::trk1Comp, Acts::Test::VertexInfo::trk1Weight, and ActsExamples::HepMC3Event::vertices().
Referenced by BOOST_AUTO_TEST_CASE().
ViewConfig Acts::Test::red ({200, 0, 0})
std::uniform_real_distribution Acts::Test::resAngDist (0. , 0. 1)
Referenced by BOOST_AUTO_TEST_CASE().
std::uniform_real_distribution Acts::Test::resIPDist (0. , 100. _um)
Referenced by BOOST_AUTO_TEST_CASE().
std::uniform_real_distribution Acts::Test::resIPDist (0. , 100_um)
std::uniform_real_distribution Acts::Test::resQoPDist (-0. 1, 0. 1)
Referenced by BOOST_AUTO_TEST_CASE().
std::uniform_real_distribution Acts::Test::resQoPDist (0. 0, 0. 1)
std::uniform_real_distribution Acts::Test::resTDist (0. 1_ns, 0. 2_ns)
Referenced by BOOST_AUTO_TEST_CASE().
std::default_random_engine Acts::Test::rng (42)
Referenced by BOOST_DATA_TEST_CASE(), gencluster(), generateBoundParametersCovariance(), generateFreeParametersCovariance(), generateParametersCovariance(), segment(), and Acts::Test::TestTrackState::TestTrackState().
Vector2 Acts::Test::rphiPosition (3. 5, M_PI/ 8.)
Referenced by BOOST_AUTO_TEST_CASE().
Vector2 Acts::Test::rphizPosition (0. 1, 2. 5)
Referenced by BOOST_AUTO_TEST_CASE().
ReferencePropagator Acts::Test::rpropagator (std:: moveestepper, std:: movenavigator)
Referenced by BOOST_DATA_TEST_CASE().
template<typename rpropagator_t , typename dpropagator_t > void Acts::Test::runTest (const rpropagator_t & rprop, const dpropagator_t & dprop, double pT, double phi, double theta, int charge, double time, int index)
The actual test nethod that runs the test can be used with several propagator types
Template Parameters
rpropagator_t is the reference propagator type
dpropagator_t is the direct propagator type
Parameters
rprop is the reference propagator instance
dprop is the direct propagator instance
pT the transverse momentum
phi the azimuthal angle of the track at creation
theta the polar angle of the track at creation
charge is the charge of the particle
index is the run index from the test
Definition at line 98 of file DirectNavigatorTests.cpp.
View newest version in sPHENIX GitHub at line 98 of file DirectNavigatorTests.cpp
References charge(), CHECK_CLOSE_REL, Acts::UnitConstants::e, Acts::IntegrationTest::mfContext, oversteppingMaxStepSize, oversteppingTest, merge_hashes::p, Acts::ParticleHypothesis::pion(), referenceTiming, skip, start, and Acts::tgContext.
Referenced by BOOST_DATA_TEST_CASE(), BOOST_DATA_TEST_CASE(), and Acts::Test::MultiTrajectoryTestsCommon< factory_t >::testMultiTrajectoryExtraColumnsRuntime().
template<typename propagator_t > void Acts::Test::runTest (const propagator_t & prop, double pT, double phi, double theta, int charge, double time, int index)
the actual test nethod that runs the test can be used with several propagator types
Template Parameters
propagator_t is the actual propagator type
Parameters
prop is the propagator instance
pT the transverse momentum
phi the azimuthal angle of the track at creation
theta the polar angle of the track at creation
charge is the charge of the particle
index is the run index from the test
Definition at line 98 of file MaterialCollectionTests.cpp.
View newest version in sPHENIX GitHub at line 98 of file MaterialCollectionTests.cpp
References Acts::Direction::Backward, charge(), CHECK_CLOSE_REL, cov, debugModeBwd, debugModeBwdStep, debugModeFwd, debugModeFwdStep, Acts::Test::Options::direction, Acts::UnitConstants::e, Acts::GeometryObject::geometryId(), Acts::IntegrationTest::mfContext, merge_hashes::p, Acts::Test::Options::pathLimit, Acts::ParticleHypothesis::pion(), Acts::GenericBoundTrackParameters< particle_hypothesis_t >::referenceSurface(), skip, start, Acts::tgContext, and Acts::GeometryIdentifier::value().
template<typename RNG > std::vector<Rectangle> Acts::Test::segment (int x0, int y0, int x1, int y1, RNG & rng)
Definition at line 47 of file ClusterizationTests2D.cpp.
View newest version in sPHENIX GitHub at line 47 of file ClusterizationTests2D.cpp
References concat(), rng(), x0, x_, xmax, xmin, y_, ymax, and ymin.
Referenced by ActsFatras::PlanarSurfaceMask::apply(), ActsFatras::BOOST_AUTO_TEST_CASE(), BOOST_AUTO_TEST_CASE(), ActsFatras::BOOST_DATA_TEST_CASE(), Fun4All_EMCalBadTowerID(), Fun4All_Year1(), Fun4AllUtils::GetRunSegment(), and testing::internal::XmlUnitTestResultPrinter::OutputXmlCDataSection().
StraightLinePropagator Acts::Test::slpropagator (slstepper , std:: movenavigatorSL)
Referenced by BOOST_DATA_TEST_CASE().
template<typename stepper_state_t > void Acts::Test::step (stepper_state_t & sstate)
Definition at line 274 of file NavigatorTests.cpp.
View newest version in sPHENIX GitHub at line 274 of file NavigatorTests.cpp
References Acts::eMom0, Acts::eMom1, Acts::eMom2, Acts::ePos0, Acts::ePos1, and Acts::ePos2.
Referenced by BOOST_AUTO_TEST_CASE(), BOOST_FIXTURE_TEST_CASE(), and Acts::Test::CubicBVHTrackingGeometry::CubicBVHTrackingGeometry().
std::pair<Vector3, Vector3> Acts::Test::stripEnds (const std::shared_ptr< const TrackingGeometry > & geo, const GeometryContext & gctx, const SourceLink & slink, const double stripFrac = 0.4)
Definition at line 80 of file SpacePointBuilderTests.cpp.
View newest version in sPHENIX GitHub at line 80 of file SpacePointBuilderTests.cpp
References Acts::SourceLink::get(), Acts::Surface::localToGlobal(), Acts::Test::TestSourceLink::parameters, and writeMapConfig::surface.
Referenced by BOOST_DATA_TEST_CASE().
std::uniform_real_distribution Acts::Test::tDist (-0. 002_ns, 0. 002_ns)
Referenced by BOOST_AUTO_TEST_CASE().
template<class BField_t > void Acts::Test::testInterfaceConsistency (const BField_t & field)
This is the canonical interface that all field implementations need to comply with. This test group is should include ALL field implementations, to make sure they conform to the interface, even if they are not implicitly tested by some of the other tests (e.g. Propagation) The function does not assert any functionality, it just ensures the interface compiles
Definition at line 41 of file MagneticFieldInterfaceConsistencyTests.cpp.
View newest version in sPHENIX GitHub at line 41 of file MagneticFieldInterfaceConsistencyTests.cpp
References mfContext, and pos.
Referenced by BOOST_AUTO_TEST_CASE().
template<typename Parameters > void Acts::Test::testJacobianToGlobal (const Parameters & pars)
Helper method : tests the jacobian to Global for a templated Parameters object
Template Parameters
Parameters the parameter type
Parameters
pars the parameter object
Definition at line 139 of file JacobianTests.cpp.
View newest version in sPHENIX GitHub at line 139 of file JacobianTests.cpp
References Acts::IntegrationTest::bField, CHECK_CLOSE_OR_SMALL, convertToMatrix(), Acts::UnitConstants::e, Acts::IntegrationTest::mfContext, pars, and Acts::tgContext.
Referenced by BOOST_AUTO_TEST_CASE().
bool Acts::Test::testNavigatorStatePointers (Navigator::State & state, const TrackingVolume * worldVol, const TrackingVolume * startVol, const Layer * startLay, const Surface * startSurf, const Surface * currSurf, const TrackingVolume * currVol, const TrackingVolume * targetVol, const Layer * targetLay, const Surface * targetSurf)
Method for testing pointers in Navigator::State.
Parameters
[in] state Navigation state
[in] worldVol World volume
[in] startVol Start volume
[in] startLay Start layer
[in] startSurf Start surface
[in] currSurf Current surface
[in] currVol Current volume
[in] targetVol Target volume
[in] targetLay Target layer
[in] targetSurf Target surface
Definition at line 310 of file NavigatorTests.cpp.
View newest version in sPHENIX GitHub at line 310 of file NavigatorTests.cpp
References Acts::Navigator::State::currentSurface, Acts::Navigator::State::currentVolume, Acts::Navigator::State::startLayer, Acts::Navigator::State::startSurface, Acts::Navigator::State::startVolume, Acts::Navigator::State::targetLayer, Acts::Navigator::State::targetSurface, Acts::Navigator::State::targetVolume, and Acts::Navigator::State::worldVolume.
Referenced by BOOST_AUTO_TEST_CASE().
bool Acts::Test::testNavigatorStateVectors (Navigator::State & state, size_t navSurf, size_t navLay, size_t navBound, size_t extSurf)
Method for testing vectors in Navigator::State.
Parameters
[in] state Navigator state
[in] navSurf Number of navigation surfaces
[in] navLay Number of navigation layers
[in] navBound Number of navigation boundaries
[in] extSurf Number of external surfaces
Definition at line 290 of file NavigatorTests.cpp.
View newest version in sPHENIX GitHub at line 290 of file NavigatorTests.cpp
References Acts::Navigator::State::externalSurfaces, Acts::Navigator::State::navBoundaries, Acts::Navigator::State::navLayers, and Acts::Navigator::State::navSurfaces.
Referenced by BOOST_AUTO_TEST_CASE().
static std::vector<std::string> Acts::Test::testObjString (const std::string & tString, bool triMesh = false) inline static
This is a test function that tests the validity of an obj stream It tests for special characters that are not allowed to be contained
It checks for:
Allowed as tags: mtllib, usemtl v, vn, vt, l, f, g, o, s comment lines (starting with #)
v, vn, vt are checked for 3 entries
f is checked for integer > 0 entries only
f is also check for being a triplet if triMesh is true
l is checked for integer > 0 entries only
Parameters
tString is the test string
triMesh is the test if only triangular surfaces exist
Returns
a vector of failure messages
Definition at line 39 of file Visualization3DTester.hpp.
View newest version in sPHENIX GitHub at line 39 of file Visualization3DTester.hpp
References line.
Referenced by BOOST_AUTO_TEST_CASE().
static std::vector<std::string> Acts::Test::testPlyString (const std::string & tString, bool triMesh = false) inline static
This is a test function that tests the validity of an obj stream It tests for special characters that are not allowed to be contained
It checks for:
Parameters
tString is the test string
triMesh is the test if only triangular surfaces exist
Returns
a vector of failure messages
Definition at line 123 of file Visualization3DTester.hpp.
View newest version in sPHENIX GitHub at line 123 of file Visualization3DTester.hpp
References Acts::Test::PlyElement::copies, line, perf_headwind::name, Acts::Test::PlyElement::name, Acts::Test::PlyElement::properties, and to_string().
Referenced by BOOST_AUTO_TEST_CASE().
template<typename trajectory_t > void Acts::Test::testSourceLinkCalibrator (const GeometryContext & gctx, const CalibrationContext & cctx, const SourceLink & sourceLink, typename trajectory_t::TrackStateProxy trackState)
Extract the measurement from a TestSourceLink.
Parameters
gctx Unused
trackState TrackState to calibrated
Definition at line 126 of file TestSourceLink.hpp.
View newest version in sPHENIX GitHub at line 126 of file TestSourceLink.hpp
References gctx.
template<typename trajectory_t > Acts::BoundVariantMeasurement Acts::Test::testSourceLinkCalibratorReturn (const GeometryContext & , const CalibrationContext & , const SourceLink & sourceLink, typename trajectory_t::TrackStateProxy trackState)
Extract the measurement from a TestSourceLink.
Parameters
gctx Unused
trackState TrackState to calibrated
Returns
The measurement used
Definition at line 93 of file TestSourceLink.hpp.
View newest version in sPHENIX GitHub at line 93 of file TestSourceLink.hpp
References Acts::Test::TestSourceLink::covariance, Acts::eBoundSize, Acts::Test::TestSourceLink::indices, Acts::makeMeasurement(), and Acts::Test::TestSourceLink::parameters.
std::uniform_real_distribution Acts::Test::thetaDist (1. 0, M_PI-1. 0)
Referenced by BOOST_AUTO_TEST_CASE().
std::ofstream Acts::Test::tmp (const std::string & path)
Definition at line 55 of file BoundingBoxTest.cpp.
View newest version in sPHENIX GitHub at line 55 of file BoundingBoxTest.cpp
References path, and tmp_path.
Referenced by PHNodeDump::AddDumpObject(), ActsExamples::TGeoDetectorWithOptions::addOptions(), biconnectivity::after_recursive_call_handler(), boost::atomic_compare_exchange(), bfs::bfs_sub(), BOOST_AUTO_TEST_CASE(), pq_tree::bubble_up(), c_itoa(), planarity::case_A(), planarity::case_B(), planarity::case_C(), planarity::case_D(), planarity::case_E(), centrality_newplotbg_newsupp(), checkTables(), hLabHelper::collect(), oncsEvent::convert(), oncsSubevent::convert(), A_Event::convert(), Packet_A::convert(), convert_sartre2eictree(), groot::CreateZigzags(), pq_tree::dfs(), pathfinder::dfs_sub(), MvtxMonDraw::DrawOCC(), EnterPassword(), planarity::examine_obstruction(), KFParticleFinder::ExtrapolateToPV(), KFParticleFinder::FindParticles(), G__DirectPhotonPythia_Dict_523_0_19(), G__ExampleAnalysisModule_Dict_577_0_9(), G__ExampleAnalysisModule_Dict_578_0_15(), G__ExampleAnalysisModule_Dict_579_0_16(), G__hcalUtilDict_478_0_13(), G__RecoInfoExport_Dict_244_0_12(), G__SimpleTrackingAnalysis_Dict_194_0_7(), G__STACalorimeterCharacterization_Dict_194_0_13(), GaussLegendre_getWeight(), TrkrDefs::genClusKey(), generic_16bit_genkey(), generic_32bit_genkey(), generic_32bit_key(), generic_lower_16bit_key(), generic_upper_16bit_key(), TpcDefs::genHitKey(), InttDefs::genHitKey(), MvtxDefs::genHitKey(), MicromegasDefs::genHitSetKey(), TrkrDefs::genHitSetKey(), TpcDefs::genHitSetKey(), InttDefs::genHitSetKey(), MvtxDefs::genHitSetKey(), PHG4CellDefs::get_binning(), PHG4CellDefs::get_detid(), PHG4CellDefs::SpacalBinning::get_etabin(), TrkrClusterv4::getAdc(), PHG4CellContainer::getCells(), MvtxDefs::getChipId(), TrkrDefs::getClusKeyHi(), TrkrDefs::getClusKeyLo(), MvtxDefs::getCol(), InttDefs::getCol(), hLabHelper::getDetectorTiming(), MakeActsGeometry::getInttKeyFromNode(), InttDefs::getLadderPhiId(), InttDefs::getLadderZId(), TrkrDefs::getLayer(), TrkrClusterv4::getMaxAdc(), MakeActsGeometry::getMvtxKeyFromNode(), TpcDefs::getPad(), TrkrDefs::getPhiElement(), MvtxDefs::getRow(), InttDefs::getRow(), TpcDefs::getSectorId(), MicromegasDefs::getSegmentationType(), TpcDefs::getSide(), MvtxDefs::getStaveId(), MicromegasDefs::getStrip(), MvtxDefs::getStrobeId(), TpcDefs::getTBin(), MicromegasDefs::getTileId(), InttDefs::getTimeBucketId(), TrkrDefs::getTrkrId(), GetValueFromOption(), TrkrDefs::getZElement(), GML_free_list(), GML_parser(), GML_print_list(), GML_scanner(), PHG4CellDefs::has_binning(), graph::induced_subgraph(), MvtxMon::Init(), TSQLImportClient::Init(), FullJetFinder::Init(), PHG4CylinderSubsystem::InitRunSubsystem(), integral(), pq_tree::integrity_check(), Jetscape::JetScapeEvent::JetScapeEvent(), json_emit_double(), json_emit_long(), shower2::load_edge_info_handler(), Jetscape::PartonShower::load_edge_info_handler(), Jetscape::PartonShower::load_node_info_handler(), shower2::load_node_info_handler(), main(), MakeDCA2DResolution(), MakeActsGeometry::makeInttMapPairs(), ActsExamples::makeMagneticFieldMapRzFromText(), ActsExamples::makeMagneticFieldMapXyzFromText(), MakeActsGeometry::makeMvtxMapPairs(), ActsExamples::makeParameterContainers(), MakePtResolution(), PHGenFitTrkFitter::MakeSvtxTrack(), MakeActsGeometry::makeTpcMapPairs(), mg_http_free_proto_data_endpoints(), mg_mgr_poll(), mg_send_ws_header(), mg_start_process(), EMMaximization::Move(), newplotbg_dAu_vscent_2022(), newplotbg_newsupp(), newplotbg_newsupp_2021(), newplotbg_newsupp_2022(), newplotbg_newsupp_2022_60pct(), newplotbg_vscent_2022(), pathfinder::const_iterator::operator++(), SearchTree< T >::circulator::operator++(), SearchTree< T >::const_circulator::operator++(), KFVertex::operator-(), SearchTree< T >::circulator::operator--(), SearchTree< T >::const_circulator::operator--(), operator<<(), q_node::pertinent(), pq_tree::pq_tree(), EventPlaneReco::process_event(), FilterEvents::process_event(), FilterEventsUpsilon::process_event(), PHHepMCParticleSelectorDecayProductChain::process_event(), PHG4BlockCellReco::process_event(), PHG4CylinderCellReco::process_event(), PHG4MvtxHitReco::process_event(), sPHAnalysis::process_event_bimp(), sPHAnalysis::process_event_notracking(), sPHAnalysis::process_event_pairs(), sPHAnalysis::process_event_pythiaupsilon(), sPHAnalysis_calo::process_event_test(), sPHAnalysis::process_event_upsilons(), CaloWaveFormSim::process_g4hits(), DumpPHG4CylinderCellContainer::process_Node(), pq_tree::Q2(), Acts::IntegrationTest::readFieldXYZ(), pq_tree::reduce(), bellman_ford::relax(), pq_tree::replace_pert(), pq_tree::reset(), InttDefs::resetCrossingHitSetKey(), MvtxDefs::resetStrobeHitSetKey(), graph::restore_graph(), EpFinder::Results(), edge::reverse(), symlist< T >::reverse(), st_number::run(), planarity::run_on_biconnected(), planarity::run_through_partial(), sChargeMap::ScreenShot(), KFParticleTopoReconstructor::SelectParticleCandidates(), TrkrClusterv4::setAdc(), TrkrClusterv4::setMaxAdc(), ElectronID::setPROBcut(), boost::shared_ptr< TClonesArray >::shared_ptr(), Acts::RadialBounds::shifted(), symlist< T >::splice(), PHTimer::test(), toLower(), TSQLResultSet::Tree(), trim(), ActsExamples::CsvTrackParameterWriter::write(), and pq_node::~pq_node().
ActsVector<dim> Acts::Test::trafoGlobalToLocal (const Vector3 & global)
Definition at line 39 of file InterpolatedMaterialMapTests.cpp.
View newest version in sPHENIX GitHub at line 39 of file InterpolatedMaterialMapTests.cpp
Referenced by BOOST_AUTO_TEST_CASE().
Result<void> Acts::Test::void_res_func (int b)
Definition at line 290 of file ResultTests.cpp.
View newest version in sPHENIX GitHub at line 290 of file ResultTests.cpp
Referenced by BOOST_AUTO_TEST_CASE().
std::uniform_real_distribution Acts::Test::vTDist (- 1_ns, 1_ns)
Referenced by BOOST_AUTO_TEST_CASE().
std::uniform_real_distribution Acts::Test::vXYDist (-0. 1_mm, 0. 1_mm)
Referenced by BOOST_AUTO_TEST_CASE().
std::uniform_real_distribution Acts::Test::vZDist (- 20_mm, 20_mm)
Referenced by BOOST_AUTO_TEST_CASE().
BinningData Acts::Test::xData_add (open , binX , main_sstr , std:: movexData_sstr_add)
Referenced by BOOST_AUTO_TEST_CASE().
std::normal_distribution< double > Acts::Test::xdist (1_mm , 0. 1_mm)
Referenced by BOOST_AUTO_TEST_CASE().
Vector2 Acts::Test::xyPosition (0. 5, 1. 5)
Referenced by BOOST_AUTO_TEST_CASE().
Vector3 Acts::Test::xyzPosition (0. 5, 1. 5, 2. 5)
Referenced by BOOST_AUTO_TEST_CASE().
Vector3 Acts::Test::xyzPositionOutside (30. , - 30., 200.)
Referenced by BOOST_AUTO_TEST_CASE().
std::normal_distribution< double > Acts::Test::ydist (-0. 7_mm, 0. 1_mm)
Referenced by BOOST_AUTO_TEST_CASE().
std::uniform_real_distribution Acts::Test::z0Dist (-0. 2_mm, 0. 2_mm)
Referenced by BOOST_AUTO_TEST_CASE().
std::normal_distribution<double> Acts::Test::z1dist (zVertexPos1 * 1_mm, 1_mm)
Referenced by BOOST_AUTO_TEST_CASE().
std::normal_distribution<double> Acts::Test::z1dist (zVertexPos * 1_mm, 1_mm)
std::normal_distribution<double> Acts::Test::z2dist (zVertexPos2 * 1_mm, 0. 5_mm)
Referenced by BOOST_AUTO_TEST_CASE().
std::normal_distribution<double> Acts::Test::z2dist (- 3_mm, 0. 5_mm)
Variable Documentation
constexpr auto Acts::Test::absMom = 1_GeV static
Definition at line 93 of file AtlasStepperTests.cpp.
View newest version in sPHENIX GitHub at line 93 of file AtlasStepperTests.cpp
Referenced by BOOST_AUTO_TEST_CASE().
auto Acts::Test::aCylinder = Surface::makeShared<CylinderSurface>(at, std::move(cb))
Definition at line 60 of file SurfaceIntersectionBenchmark.cpp.
View newest version in sPHENIX GitHub at line 60 of file SurfaceIntersectionBenchmark.cpp
Referenced by BOOST_AUTO_TEST_CASE(), and BOOST_DATA_TEST_CASE().
auto Acts::Test::aDisc = Surface::makeShared<DiscSurface>(at, std::move(db))
Definition at line 56 of file SurfaceIntersectionBenchmark.cpp.
View newest version in sPHENIX GitHub at line 56 of file SurfaceIntersectionBenchmark.cpp
Referenced by BOOST_DATA_TEST_CASE().
std::vector<std::string> Acts::Test::allowedAxes
Initial value:
= {"XY*", "Xy*", "xy*", "xY*",
                                        "YX*", "yx*", "yX*", "Yx*"}
Definition at line 50 of file TGeoTubeConversionTests.cpp.
View newest version in sPHENIX GitHub at line 50 of file TGeoTubeConversionTests.cpp
Referenced by BOOST_AUTO_TEST_CASE().
auto Acts::Test::aPlane = Surface::makeShared<PlaneSurface>(at, std::move(rb))
Definition at line 52 of file SurfaceIntersectionBenchmark.cpp.
View newest version in sPHENIX GitHub at line 52 of file SurfaceIntersectionBenchmark.cpp
Referenced by BOOST_AUTO_TEST_CASE(), and BOOST_DATA_TEST_CASE().
auto Acts::Test::aStraw = Surface::makeShared<StrawSurface>(at, 50_cm, 2_m)
Definition at line 63 of file SurfaceIntersectionBenchmark.cpp.
View newest version in sPHENIX GitHub at line 63 of file SurfaceIntersectionBenchmark.cpp
Referenced by BOOST_DATA_TEST_CASE().
Transform3 Acts::Test::at
Initial value:
= Transform3::Identity() * Translation3(0_m, 0_m, 10_m) *
                AngleAxis3(0.15, Vector3(1.2, 1.2, 0.12).normalized())
Definition at line 47 of file SurfaceIntersectionBenchmark.cpp.
View newest version in sPHENIX GitHub at line 47 of file SurfaceIntersectionBenchmark.cpp
Referenced by Acts::Python::addDetector(), analyzeClusterEtIso(), SColdQcdCorrelatorAnalysis::SEnergyCorrelator::DoCorrelatorCalculation(), CemcMonDraw::DrawSecond(), EMCalTowerRingStudy(), ExploreTTrees(), Acts::TrackingVolume::glueTrackingVolume(), Acts::TrackingVolume::glueTrackingVolumes(), TowerBackgroundv1::identify(), Jet_reso_Iso(), PairMaker::MakeMixedPairs(), AnnularFieldSim::populate_full3d_lookup(), AnnularFieldSim::populate_highres_lookup(), AnnularFieldSim::populate_lowres_lookup(), AnnularFieldSim::populate_phislice_lookup(), DetermineTowerBackground::process_event(), residesIn(), HybridHadronization::stringprep(), oncsSub_idtpcfeev2::tpc_decode(), MvtxStandaloneTracking::TrackFitXY(), MvtxStandaloneTracking::TrackFitZY(), and Acts::AutodiffExtensionWrapper< basic_extension_t >::transportMatrix().
constexpr size_t Acts::Test::bench_iters = 1'000
Definition at line 168 of file BenchmarkTools.cpp.
View newest version in sPHENIX GitHub at line 168 of file BenchmarkTools.cpp
auto Acts::Test::bField = std::make_shared<BField>(Vector3{0, 0, Bz})
Definition at line 70 of file DirectNavigatorTests.cpp.
View newest version in sPHENIX GitHub at line 70 of file DirectNavigatorTests.cpp
Referenced by BOOST_AUTO_TEST_CASE().
ViewConfig Acts::Test::blue ({0, 0, 200})
Referenced by adaptColorPalette(), BOOST_AUTO_TEST_CASE(), BOOST_AUTO_TEST_CASE(), AZigzag::DetermineQ(), printBField(), PHG4ConeSubsystem::set_color(), PHG4BlockSubsystem::set_color(), PHG4CylinderSubsystem::set_color(), G4Example03Subsystem::set_color(), and sPhenixStyle().
const bool Acts::Test::boundaryCheck = false
Definition at line 36 of file SurfaceIntersectionBenchmark.cpp.
View newest version in sPHENIX GitHub at line 36 of file SurfaceIntersectionBenchmark.cpp
Referenced by Acts::Layer::compatibleSurfaces(), Acts::CylinderBounds::inside(), Acts::CylinderSurface::intersect(), and intersectionTest().
const double Acts::Test::Bz = 2_T
Definition at line 69 of file DirectNavigatorTests.cpp.
View newest version in sPHENIX GitHub at line 69 of file DirectNavigatorTests.cpp
const CalibrationContext Acts::Test::calCtx
Definition at line 110 of file SpacePointBuilderTests.cpp.
View newest version in sPHENIX GitHub at line 110 of file SpacePointBuilderTests.cpp
Referenced by BOOST_AUTO_TEST_CASE(), and BOOST_AUTO_TEST_CASE().
auto Acts::Test::cb = std::make_shared<CylinderBounds>(10_m, 100_m)
Definition at line 59 of file SurfaceIntersectionBenchmark.cpp.
View newest version in sPHENIX GitHub at line 59 of file SurfaceIntersectionBenchmark.cpp
Referenced by BOOST_AUTO_TEST_CASE(), mg_broadcast(), mg_resolve_async_opt(), and Acts::ProtoVolume::toString().
auto Acts::Test::cCylinder = std::make_shared<CylinderBounds>(150_mm, 1000_mm)
Definition at line 147 of file PropagatorTests.cpp.
View newest version in sPHENIX GitHub at line 147 of file PropagatorTests.cpp
CylindricalTrackingGeometry Acts::Test::cGeometry (tgContext)
Referenced by BOOST_AUTO_TEST_CASE().
constexpr auto Acts::Test::charge = -1_e static
Definition at line 94 of file AtlasStepperTests.cpp.
View newest version in sPHENIX GitHub at line 94 of file AtlasStepperTests.cpp
Referenced by BOOST_AUTO_TEST_CASE().
const Covariance Acts::Test::cov = Covariance::Identity() static
Definition at line 96 of file AtlasStepperTests.cpp.
View newest version in sPHENIX GitHub at line 96 of file AtlasStepperTests.cpp
Referenced by ActsExamples::HoughTransformSeeder::addMeasurements(), Acts::GaussianGridTrackDensity< mainGridSize, trkGridSize >::addTrack(), Acts::AdaptiveGridTrackDensity< spatialTrkGridSize, temporalTrkGridSize >::addTrack(), ALICEKF::ALICEKalmanFilter(), BOOST_AUTO_TEST_CASE(), BOOST_AUTO_TEST_CASE(), BOOST_AUTO_TEST_CASE_TEMPLATE(), BOOST_DATA_TEST_CASE(), BOOST_DATA_TEST_CASE(), Acts::detail::boundState(), Acts::MultiEigenStepperLoop< extensionlist_t, component_reducer_t, auctioneer_t >::ComponentProxy::boundState(), Acts::SpacePointBuilder< spacepoint_t >::buildSpacePoint(), TpcSpaceChargeMatrixInversion::calculate_distortions(), ActsTransformations::calculateDCA(), Calibrator::calibrate(), Acts::MultiComponentCurvilinearTrackParameters::construct(), Acts::EDM4hepUtil::detail::convertTrackParametersFromEdm4hep(), genfit::Covariance3DToTMatrixDSym(), genfit::Covariance6DToTMatrixDSym(), ActsExamples::createMeasurement(), Acts::AdaptiveGridTrackDensity< spatialTrkGridSize, temporalTrkGridSize >::createTrackGrid(), Acts::detail::curvilinearState(), ActsExamples::TrackModifier::execute(), ActsExamples::DigitizationAlgorithm::execute(), ActsExamples::ParticleSmearing::execute(), ActsExamples::SpacePointMaker::execute(), ActsExamples::PlanarSteppingAlgorithm::execute(), ActsExamples::PropagationAlgorithm::execute(), GenFitTrackProp::fill_tree(), Acts::FullBilloirVertexFitter< input_track_t, linearizer_t >::fit(), Acts::detail::gaussianMixtureCov(), generateParametersCovariance(), genfit::RKTrackRep::get6DCov(), Acts::CovarianceTool::getCovariances(), genfit::KalmanFitterInfo::getResidual(), MakeSourceLinks::getSourceLinks(), PHActsInitialVertexFinder::getTrackPointers(), genfit::GFTrackToTrack(), PHGenFit::SpacepointMeasurement::init(), Acts::detail::visit_measurement_callable< I >::invoke(), isCovMatrix(), PHCosmicsTrkFitter::loopTracks(), PHActsTrkFitter::loopTracks(), main(), makeDefaultBoundPars(), BDiJetModule::MakeGenFitTrack(), SVReco::MakeGenFitTrack(), genfit::EventDisplay::makeLines(), Acts::makeMeasurement(), makeParameters(), makeParametersCurvilinearWithCovariance(), Acts::SingleSeedVertexFinder< spacepoint_t >::makeRayFromTriplet(), PHActsGSF::makeSeed(), SVReco::MakeSvtxTrack(), PHG4TrackFastSim::MakeSvtxTrack(), TpcPrototypeGenFitTrkFitter::MakeSvtxTrack(), PHGenFitTrkFitter::MakeSvtxTrack(), PHActsVertexFitter::makeTrackParam(), ActsPropagator::makeTrackParams(), PHTpcResiduals::makeTrackParams(), ActsExamples::measurementConstituents(), Acts::MultiComponentBoundTrackParameters::MultiComponentBoundTrackParameters(), Acts::GaussianGridTrackDensity< mainGridSize, trkGridSize >::normal2D(), ActsFatras::BoundParametersSmearer< RandomEngine, kSmearDIM >::operator()(), Acts::Test::MeasurementsCreator::operator()(), ActsFatras::FreeParametersSmearer< generator_t, kSize >::operator()(), genfit::MeasuredStateOnPlane::Print(), SVReco::printGenFitTrackKinematics(), PHSimpleVertexFinder::process_event(), PHGenFitTrackProjection::process_event(), genfit::KalmanFitter::processTrackPartially(), genfit::KalmanFitter::processTrackPoint(), genfit::KalmanFitter::processTrackWithRep(), TrackProjectorPid::project_track(), TrackProjectorPlaneECAL::project_track(), Acts::RiddersPropagator< propagator_t >::propagate(), ActsExamples::CsvTrackParameterReader::read(), ActsExamples::CsvPlanarClusterReader::read(), ActsExamples::RootAthenaNTupleReader::read(), readFile(), ActsExamples::EDM4hepUtil::readMeasurement(), readSeedFile(), readTracksAndVertexCSV(), TpcPrototypeGenFitTrkFitter::ReFitTrack(), PHGenFitTrkFitter::ReFitTrack(), ALICEKF::repairCovariance(), KFPTrackVector::RotateXY(), KFPTrack::RotateXY(), Acts::PrimitivesView3DTest::run(), PHActsSiliconSeeding::runSeeder(), runTest(), genfit::MeasuredStateOnPlane::setCov(), PHCosmicsTrkFitter::setDefaultCovariance(), PHActsTrkFitter::setDefaultCovariance(), genfit::RKTrackRep::setPosMomErr(), genfit::AbsMeasurement::setRawHitCov(), ActsExamples::SpacePointMaker::SpacePointMaker(), PHGenFit::SpacepointMeasurement::SpacepointMeasurement(), test_combined_bound_state_function(), test_combined_curvilinear_state_function(), test_multi_stepper_vs_eigen_stepper(), Acts::EventDataView3DTest::testBoundTrackParameters(), Acts::EventDataView3DTest::testMeasurement(), Acts::EventDataView3DTest::testMultiTrajectory(), Acts::Test::TestTrackState::TestTrackState(), Acts::Test::MultiTrajectoryTestsCommon< factory_t >::testTrackStateProxyCrossTalk(), PHRaveVertexing::TranslateSvtxToGenFitTrack(), PHGenFit::Track::updateOneMeasurementKalman(), Acts::detail::GsfActor< bethe_heitler_approx_t, traj_t >::updateStepper(), Acts::visit_measurement(), ActsEvaluator::visitTrackStates(), genfit::WireMeasurementNew::WireMeasurementNew(), and ActsExamples::CsvTrackParameterWriter::write().
auto Acts::Test::cSegmentation
Initial value:
=
    std::make_shared<const CartesianSegmentation>(moduleBounds, nbinsx, nbinsy)
Definition at line 48 of file PlanarModuleStepperTests.cpp.
View newest version in sPHENIX GitHub at line 48 of file PlanarModuleStepperTests.cpp
Referenced by BOOST_AUTO_TEST_CASE().
auto Acts::Test::cSurface
Initial value:
=
    Surface::makeShared<CylinderSurface>(Transform3::Identity(), cCylinder)
Definition at line 148 of file PropagatorTests.cpp.
View newest version in sPHENIX GitHub at line 148 of file PropagatorTests.cpp
Referenced by BOOST_AUTO_TEST_CASE(), BOOST_AUTO_TEST_CASE(), BOOST_DATA_TEST_CASE(), Acts::Svg::SurfaceArrayConverter::convert(), Acts::CylinderVolumeHelper::glueTrackingVolumes(), and Acts::CylinderVolumeBounds::orientedSurfaces().
auto Acts::Test::db = std::make_shared<RadialBounds>(0.2_m, 1.2_m)
Definition at line 55 of file SurfaceIntersectionBenchmark.cpp.
View newest version in sPHENIX GitHub at line 55 of file SurfaceIntersectionBenchmark.cpp
Referenced by BOOST_AUTO_TEST_CASE(), and TSQLDatabaseMetaData::GetTables().
bool Acts::Test::debug = true
Definition at line 329 of file NavigatorTests.cpp.
View newest version in sPHENIX GitHub at line 329 of file NavigatorTests.cpp
Referenced by BOOST_AUTO_TEST_CASE(), calccorr(), Jetscape::JetScapeLogger::Debug(), Jetscape::JetScapeLogger::DebugThread(), eic_sphenix_fill_xq2(), Fun4All_RunCorrelatorQAModules(), G4DSTreader(), G4DSTreader_EICDetector(), G4DSTreader_EICIR(), G4DSTreader_fsPHENIX(), main(), SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::SCorrelatorJetTree(), CaloValid::set_debug(), SColdQcdCorrelatorAnalysis::SBaseQAPlugin< SCheckTrackPairsConfig >::SetDebug(), genfit::MeasurementCreator::setDebug(), and writeTimeOrderedDistortions().
bool Acts::Test::debugMode = false
Definition at line 79 of file DirectNavigatorTests.cpp.
View newest version in sPHENIX GitHub at line 79 of file DirectNavigatorTests.cpp
Referenced by BOOST_AUTO_TEST_CASE().
bool Acts::Test::debugModeBwd = false
Definition at line 83 of file MaterialCollectionTests.cpp.
View newest version in sPHENIX GitHub at line 83 of file MaterialCollectionTests.cpp
Referenced by runTest().
bool Acts::Test::debugModeBwdStep = false
Definition at line 85 of file MaterialCollectionTests.cpp.
View newest version in sPHENIX GitHub at line 85 of file MaterialCollectionTests.cpp
Referenced by runTest().
bool Acts::Test::debugModeFwd = false
Definition at line 82 of file MaterialCollectionTests.cpp.
View newest version in sPHENIX GitHub at line 82 of file MaterialCollectionTests.cpp
Referenced by runTest().
bool Acts::Test::debugModeFwdStep = false
Definition at line 84 of file MaterialCollectionTests.cpp.
View newest version in sPHENIX GitHub at line 84 of file MaterialCollectionTests.cpp
Referenced by runTest().
double Acts::Test::delta = 0.5
Definition at line 78 of file BinningDataTests.cpp.
View newest version in sPHENIX GitHub at line 78 of file BinningDataTests.cpp
Referenced by BOOST_AUTO_TEST_CASE().
constexpr unsigned int Acts::Test::dim = 2
Definition at line 35 of file InterpolatedMaterialMapTests.cpp.
View newest version in sPHENIX GitHub at line 35 of file InterpolatedMaterialMapTests.cpp
Referenced by genfit::MeasuredStateOnPlane::blowUpCov(), BOOST_AUTO_TEST_CASE(), calculateWeights(), genfit::KalmanFitterInfo::checkConsistency(), nanoflann::KDTreeSingleIndexAdaptor< Distance, DatasetAdaptor, DIM, IndexType >::computeBoundingBox(), nanoflann::KDTreeSingleIndexAdaptor< Distance, DatasetAdaptor, DIM, IndexType >::computeInitialDistances(), genfit::GblFitter::constructGblInfo(), nanoflann::KDTreeSingleIndexAdaptor< Distance, DatasetAdaptor, DIM, IndexType >::divideTree(), SurfaceFinder::Find_full_hypersurface(), Jetscape::SurfaceFinder::Find_full_hypersurface_3D(), Jetscape::SurfaceFinder::Find_full_hypersurface_4D(), nanoflann::KDTreeSingleIndexAdaptor< Distance, DatasetAdaptor, DIM, IndexType >::findNeighbors(), genfit::KalmanFitterRefTrack::fitTrack(), genfit::GblFitterInfo::GblFitterInfo(), EMMaximization::Init(), nanoflann::KDTreeSingleIndexAdaptor< Distance, DatasetAdaptor, DIM, IndexType >::KDTreeSingleIndexAdaptor(), nanoflann::KDTreeSingleIndexAdaptor< Distance, DatasetAdaptor, DIM, IndexType >::loadIndex(), Acts::make_octree(), nanoflann::KDTreeSingleIndexAdaptor< Distance, DatasetAdaptor, DIM, IndexType >::middleSplit_(), genfit::KalmanFitterRefTrack::processTrackPoint(), genfit::KalmanFitterRefTrack::processTrackPointSqrt(), genfit::GFGbl::processTrackWithRep(), nanoflann::KDTreeSingleIndexAdaptor< Distance, DatasetAdaptor, DIM, IndexType >::saveIndex(), nanoflann::KDTreeSingleIndexAdaptor< Distance, DatasetAdaptor, DIM, IndexType >::searchLevel(), PHG4Reco::set_field_map(), nanoflann::KDTreeSingleIndexAdaptor< Distance, DatasetAdaptor, DIM, IndexType >::veclen(), Acts::visit_measurement(), and while().
DirectNavigator Acts::Test::dnavigator
Definition at line 62 of file DirectNavigatorTests.cpp.
View newest version in sPHENIX GitHub at line 62 of file DirectNavigatorTests.cpp
Stepper Acts::Test::dstepper(bField)
static constexpr auto Acts::Test::eps = 1.0f / 255u
Definition at line 21 of file MaterialCompositionTests.cpp.
View newest version in sPHENIX GitHub at line 21 of file MaterialCompositionTests.cpp
Referenced by BOOST_AUTO_TEST_CASE(), and Acts::Test::CubicTrackingGeometry::operator()().
EigenStepperType Acts::Test::estepper (bField)
BinningData Acts::Test::etaData_eq(open, binEta, 5,-2.5, 2.5)
Referenced by BOOST_AUTO_TEST_CASE().
GeometryContext Acts::Test::gctx = GeometryContext()
Definition at line 31 of file CuboidVolumeBoundsTests.cpp.
View newest version in sPHENIX GitHub at line 31 of file CuboidVolumeBoundsTests.cpp
Referenced by testSourceLinkCalibrator(), Acts::Test::MultiTrajectoryTestsCommon< factory_t >::testTrackStateProxyStorage(), and Acts::Test::MultiTrajectoryTestsCommon< factory_t >::testTrackStateReassignment().
GeometryContext Acts::Test::geoContext = GeometryContext()
Definition at line 67 of file AdaptiveMultiVertexFinderTests.cpp.
View newest version in sPHENIX GitHub at line 67 of file AdaptiveMultiVertexFinderTests.cpp
Referenced by Acts::Python::addMaterial(), BOOST_AUTO_TEST_CASE(), BOOST_AUTO_TEST_CASE(), BOOST_DATA_TEST_CASE(), and runMaterialMapping().
GeometryContext Acts::Test::geoCtx = GeometryContext() static
Definition at line 99 of file AtlasStepperTests.cpp.
View newest version in sPHENIX GitHub at line 99 of file AtlasStepperTests.cpp
Referenced by BOOST_AUTO_TEST_CASE(), and BOOST_DATA_TEST_CASE().
const auto Acts::Test::geometry = geometryStore()
Definition at line 114 of file SpacePointBuilderTests.cpp.
View newest version in sPHENIX GitHub at line 114 of file SpacePointBuilderTests.cpp
Referenced by Acts::Python::addExaTrkXTrackFinding(), BOOST_AUTO_TEST_CASE(), BOOST_DATA_TEST_CASE(), TrackResiduals::fillClusterBranches(), MakeActsGeometry::makeGeometry(), materialValidationExample(), TrackResiduals::process_event(), processGeometry(), propagationExample(), runDetectorAlignment(), runDigitizationConfigExample(), runDigitizationExample(), runHoughExample(), runMaterialMapping(), runMeasurementsToSP(), runRecCKFTracks(), runRecTruthTracks(), runSeedingExample(), and TPCHitTrackDisplay::SimulationOut().
CubicTrackingGeometry Acts::Test::geometryStore(geoCtx)
ViewConfig Acts::Test::green ({0, 200, 0})
Referenced by adaptColorPalette(), BOOST_AUTO_TEST_CASE(), BOOST_AUTO_TEST_CASE(), printBField(), PHG4ConeSubsystem::set_color(), PHG4BlockSubsystem::set_color(), PHG4CylinderSubsystem::set_color(), G4Example03Subsystem::set_color(), and sPhenixStyle().
Test::CubicBVHTrackingGeometry Acts::Test::grid(NBOXES, 1000, 5)
double Acts::Test::halfX = 5_mm
Definition at line 36 of file PlanarModuleStepperTests.cpp.
View newest version in sPHENIX GitHub at line 36 of file PlanarModuleStepperTests.cpp
Referenced by Acts::adjustBinUtility(), Acts::Test::Layers::BOOST_AUTO_TEST_CASE(), BOOST_AUTO_TEST_CASE(), and Acts::RectangleBounds::m_max().
double Acts::Test::halfY = 10_mm
Definition at line 37 of file PlanarModuleStepperTests.cpp.
View newest version in sPHENIX GitHub at line 37 of file PlanarModuleStepperTests.cpp
Referenced by Acts::adjustBinUtility(), Acts::Test::Layers::BOOST_AUTO_TEST_CASE(), BOOST_AUTO_TEST_CASE(), Acts::RectangleBounds::m_max(), Acts::TrapezoidBounds::TrapezoidBounds(), and Acts::DiscTrapezoidBounds::vertices().
BinningData Acts::Test::hData_eq(open, binH, 5, 0., 10.)
double Acts::Test::hThickness = 75_um
Definition at line 34 of file CartesianSegmentationTests.cpp.
View newest version in sPHENIX GitHub at line 34 of file CartesianSegmentationTests.cpp
Referenced by BOOST_AUTO_TEST_CASE(), and BOOST_DATA_TEST_CASE().
auto Acts::Test::hVolume
Initial value:
= constructContainerVolume(tgContext, iVolume, oVolume, oVvolumeR,
                                        oVvolumeHalfZ, "Container")
Definition at line 109 of file TrackingGeometryGeometryIdTests.cpp.
View newest version in sPHENIX GitHub at line 109 of file TrackingGeometryGeometryIdTests.cpp
Referenced by BOOST_AUTO_TEST_CASE(), Acts::constructContainerVolume(), and ActsExamples::RootMaterialWriter::write().
double Acts::Test::hx {10.}
Definition at line 33 of file CuboidVolumeBoundsTests.cpp.
View newest version in sPHENIX GitHub at line 33 of file CuboidVolumeBoundsTests.cpp
Referenced by BOOST_AUTO_TEST_CASE(), and ActsExamples::MockupSectorBuilder::buildChamber().
double Acts::Test::hy {20.}
Definition at line 33 of file CuboidVolumeBoundsTests.cpp.
View newest version in sPHENIX GitHub at line 33 of file CuboidVolumeBoundsTests.cpp
Referenced by BOOST_AUTO_TEST_CASE(), ActsExamples::MockupSectorBuilder::buildChamber(), and Acts::TrapezoidBounds::vertices().
double Acts::Test::hz {30.}
Definition at line 33 of file CuboidVolumeBoundsTests.cpp.
View newest version in sPHENIX GitHub at line 33 of file CuboidVolumeBoundsTests.cpp
Referenced by BOOST_AUTO_TEST_CASE(), ActsExamples::MockupSectorBuilder::buildChamber(), TpcSpaceChargeMatrixInversion::calculate_distortions(), EmptyDetector::finalize(), and AnnularFieldSim::load_and_resample_spacecharge().
double Acts::Test::iVlayerEnvelope = 0.5_mm
Definition at line 41 of file TrackingGeometryGeometryIdTests.cpp.
View newest version in sPHENIX GitHub at line 41 of file TrackingGeometryGeometryIdTests.cpp
auto Acts::Test::iVolume
Initial value:
= constructCylinderVolume(
    tgContext, iVsurfaceHalfLengthZ, iVsurfaceR, iVsurfaceRstagger,
    iVsurfaceZoverlap, iVlayerEnvelope, iVvolumeEnvelope, 0., iVvolumeR,
    "InnerVolume")
inner volume
Definition at line 57 of file TrackingGeometryGeometryIdTests.cpp.
View newest version in sPHENIX GitHub at line 57 of file TrackingGeometryGeometryIdTests.cpp
Referenced by BOOST_AUTO_TEST_CASE(), Acts::constructContainerVolume(), and makeTrackingGeometry().
double Acts::Test::iVsurfaceHalfLengthZ = 50_mm
create three cylinder surfaces the surface radius (will also be the layer radius)
Definition at line 37 of file TrackingGeometryGeometryIdTests.cpp.
View newest version in sPHENIX GitHub at line 37 of file TrackingGeometryGeometryIdTests.cpp
double Acts::Test::iVsurfaceR = 25_mm
Definition at line 38 of file TrackingGeometryGeometryIdTests.cpp.
View newest version in sPHENIX GitHub at line 38 of file TrackingGeometryGeometryIdTests.cpp
double Acts::Test::iVsurfaceRstagger = 5_mm
Definition at line 39 of file TrackingGeometryGeometryIdTests.cpp.
View newest version in sPHENIX GitHub at line 39 of file TrackingGeometryGeometryIdTests.cpp
double Acts::Test::iVsurfaceZoverlap = 10_mm
Definition at line 40 of file TrackingGeometryGeometryIdTests.cpp.
View newest version in sPHENIX GitHub at line 40 of file TrackingGeometryGeometryIdTests.cpp
double Acts::Test::iVvolumeEnvelope = 10_mm
Definition at line 42 of file TrackingGeometryGeometryIdTests.cpp.
View newest version in sPHENIX GitHub at line 42 of file TrackingGeometryGeometryIdTests.cpp
double Acts::Test::iVvolumeR
Initial value:
=
    iVsurfaceR + 0.5 * iVsurfaceRstagger + iVlayerEnvelope + iVvolumeEnvelope
Definition at line 43 of file TrackingGeometryGeometryIdTests.cpp.
View newest version in sPHENIX GitHub at line 43 of file TrackingGeometryGeometryIdTests.cpp
double Acts::Test::lAngle = 0.1
Definition at line 35 of file CartesianSegmentationTests.cpp.
View newest version in sPHENIX GitHub at line 35 of file CartesianSegmentationTests.cpp
Referenced by BOOST_AUTO_TEST_CASE().
const MagneticFieldContext Acts::Test::magCtx static
Definition at line 100 of file AtlasStepperTests.cpp.
View newest version in sPHENIX GitHub at line 100 of file AtlasStepperTests.cpp
Referenced by BOOST_AUTO_TEST_CASE(), and BOOST_DATA_TEST_CASE().
MagneticFieldContext Acts::Test::magFieldContext = MagneticFieldContext()
Definition at line 68 of file AdaptiveMultiVertexFinderTests.cpp.
View newest version in sPHENIX GitHub at line 68 of file AdaptiveMultiVertexFinderTests.cpp
Referenced by Acts::Python::addMaterial(), BOOST_AUTO_TEST_CASE(), BOOST_AUTO_TEST_CASE(), BOOST_DATA_TEST_CASE(), and main().
auto Acts::Test::magneticField static
Initial value:
=
    std::make_shared<ConstantBField>(Vector3(0.1_T, -0.2_T, 2_T))
Definition at line 85 of file AtlasStepperTests.cpp.
View newest version in sPHENIX GitHub at line 85 of file AtlasStepperTests.cpp
Referenced by BOOST_AUTO_TEST_CASE().
std::vector<float> Acts::Test::main_sstr = {0., 3., 4., 5.}
additive
Definition at line 89 of file BinningDataTests.cpp.
View newest version in sPHENIX GitHub at line 89 of file BinningDataTests.cpp
double Acts::Test::maxPhi = 1.33970
Definition at line 33 of file AnnulusBoundsTests.cpp.
View newest version in sPHENIX GitHub at line 33 of file AnnulusBoundsTests.cpp
Referenced by Acts::Experimental::detail::SupportHelper::addSupport(), Acts::adjustBinUtility(), AZigzag::AZigzag(), BOOST_AUTO_TEST_CASE(), BOOST_AUTO_TEST_CASE(), Acts::SurfaceArrayCreator::createVariableAxis(), Acts::Experimental::detail::SupportHelper::cylindricalSupport(), Acts::Experimental::detail::SupportHelper::discSupport(), STrackMatcherComparator::IsNearSector(), main(), MakeNewMatcherTuplePlots(), MakeOldEvaluatorPlots(), ActsExamples::DigitizationConfigurator::operator()(), and Acts::SeedFinderFTF< external_spacepoint_t >::runGNN_TrackFinder().
double Acts::Test::maxRadius = 12.0
Definition at line 31 of file AnnulusBoundsTests.cpp.
View newest version in sPHENIX GitHub at line 31 of file AnnulusBoundsTests.cpp
Referenced by BOOST_AUTO_TEST_CASE(), BOOST_AUTO_TEST_CASE(), and main().
auto Acts::Test::mCylinder = std::make_shared<CylinderBounds>(10_mm, 1000_mm)
Definition at line 144 of file PropagatorTests.cpp.
View newest version in sPHENIX GitHub at line 144 of file PropagatorTests.cpp
const auto Acts::Test::measPropagator = makeStraightPropagator(geometry)
Definition at line 142 of file SpacePointBuilderTests.cpp.
View newest version in sPHENIX GitHub at line 142 of file SpacePointBuilderTests.cpp
MagneticFieldContext Acts::Test::mfContext = MagneticFieldContext()
Definition at line 19 of file TrackingVolumeTests.cpp.
View newest version in sPHENIX GitHub at line 19 of file TrackingVolumeTests.cpp
Referenced by BOOST_AUTO_TEST_CASE(), and testInterfaceConsistency().
double Acts::Test::minPhi = 0.74195
Definition at line 32 of file AnnulusBoundsTests.cpp.
View newest version in sPHENIX GitHub at line 32 of file AnnulusBoundsTests.cpp
Referenced by Acts::Experimental::detail::SupportHelper::addSupport(), Acts::adjustBinUtility(), AZigzag::AZigzag(), BOOST_AUTO_TEST_CASE(), BOOST_AUTO_TEST_CASE(), Acts::Experimental::detail::SupportHelper::cylindricalSupport(), Acts::Experimental::detail::SupportHelper::discSupport(), STrackMatcherComparator::IsNearSector(), main(), MakeNewMatcherTuplePlots(), MakeOldEvaluatorPlots(), ActsExamples::Generic::modulePositionsCylinder(), Acts::Test::CylindricalTrackingGeometry::modulePositionsCylinder(), ActsExamples::Generic::modulePositionsRing(), ActsExamples::DigitizationConfigurator::operator()(), Acts::SeedFinderFTF< external_spacepoint_t >::runGNN_TrackFinder(), and EMMaximization::SetParameters().
double Acts::Test::minRadius = 7.2
Definition at line 30 of file AnnulusBoundsTests.cpp.
View newest version in sPHENIX GitHub at line 30 of file AnnulusBoundsTests.cpp
Referenced by BOOST_AUTO_TEST_CASE(), BOOST_AUTO_TEST_CASE(), and main().
constexpr MockNavigator Acts::Test::mockNavigator static
Definition at line 65 of file StraightLineStepperTests.cpp.
View newest version in sPHENIX GitHub at line 65 of file StraightLineStepperTests.cpp
constexpr MockNavigator Acts::Test::mockNavigator static
Definition at line 110 of file EigenStepperTests.cpp.
View newest version in sPHENIX GitHub at line 110 of file EigenStepperTests.cpp
Referenced by BOOST_AUTO_TEST_CASE().
auto Acts::Test::moduleBounds = std::make_shared<const RectangleBounds>(5_mm, 10_mm)
Definition at line 38 of file CartesianSegmentationTests.cpp.
View newest version in sPHENIX GitHub at line 38 of file CartesianSegmentationTests.cpp
Referenced by ActsExamples::Generic::ProtoLayerCreatorT< detector_element_t >::centralProtoLayers(), ActsExamples::Generic::ProtoLayerCreatorT< detector_element_t >::createProtoLayers(), and Acts::CartesianSegmentation::createSegmentationSurfaces().
auto Acts::Test::mSurface
Initial value:
=
    Surface::makeShared<CylinderSurface>(Transform3::Identity(), mCylinder)
Definition at line 145 of file PropagatorTests.cpp.
View newest version in sPHENIX GitHub at line 145 of file PropagatorTests.cpp
Referenced by BOOST_DATA_TEST_CASE(), and Acts::SurfaceMaterialMapper::mapInteraction().
constexpr Direction Acts::Test::navDir = Direction::Backward static
Definition at line 84 of file AtlasStepperTests.cpp.
View newest version in sPHENIX GitHub at line 84 of file AtlasStepperTests.cpp
Referenced by BOOST_AUTO_TEST_CASE(), Acts::Test::PropagatorState::Stepper::updateSurfaceStatus(), Acts::StraightLineStepper::updateSurfaceStatus(), Acts::EigenStepper< extensionlist_t, auctioneer_t >::updateSurfaceStatus(), Acts::AtlasStepper::updateSurfaceStatus(), and Acts::MultiEigenStepperLoop< extensionlist_t, component_reducer_t, auctioneer_t >::updateSurfaceStatus().
Navigator Acts::Test::navigator({tGeometry}) static
Definition at line 76 of file AtlasStepperTests.cpp.
View newest version in sPHENIX GitHub at line 76 of file AtlasStepperTests.cpp
Referenced by BOOST_AUTO_TEST_CASE(), BOOST_AUTO_TEST_CASE(), BOOST_DATA_TEST_CASE(), BOOST_DATA_TEST_CASE(), ActsExamples::AlignmentAlgorithm::makeAlignmentFunction(), makeConstantFieldPropagator(), ActsTrackFittingAlgorithm::makeDirectedKalmanFitterFunction(), ActsExamples::makeGlobalChiSquareFitterFunction(), ActsExamples::makeGsfFitterFunction(), ActsGsfTrackFittingAlgorithm::makeGsfFitterFunction(), ActsExamples::makeKalmanFitterFunction(), ActsTrackFittingAlgorithm::makeKalmanFitterFunction(), ActsPropagator::makePropagator(), makeStraightPropagator(), makeStraightPropagator(), ActsExamples::TrackFindingAlgorithm::makeTrackFinderFunction(), Acts::MultiStepperSurfaceReached::operator()(), Acts::SurfaceReached::operator()(), Acts::KalmanFitter< propagator_t, traj_t >::Actor< parameters_t >::operator()(), Acts::CombinatorialKalmanFilter< propagator_t, traj_t >::Actor< source_link_accessor_t, parameters_t >::operator()(), propagationExample(), Acts::CombinatorialKalmanFilter< propagator_t, traj_t >::Actor< source_link_accessor_t, parameters_t >::reset(), Acts::KalmanFitter< propagator_t, traj_t >::Actor< parameters_t >::reverse(), and runMaterialMapping().
Navigator Acts::Test::navigatorES({tGeometry})
Navigator Acts::Test::navigatorSL({tGeometry})
size_t Acts::Test::nBins_binary = 59
Definition at line 75 of file BinningDataTests.cpp.
View newest version in sPHENIX GitHub at line 75 of file BinningDataTests.cpp
Referenced by BOOST_AUTO_TEST_CASE().
size_t Acts::Test::nbinsx = 100
Definition at line 32 of file CartesianSegmentationTests.cpp.
View newest version in sPHENIX GitHub at line 32 of file CartesianSegmentationTests.cpp
Referenced by BOOST_AUTO_TEST_CASE(), SepdMonDraw::DrawFirst(), and plot_checks().
size_t Acts::Test::nbinsy = 200
Definition at line 33 of file CartesianSegmentationTests.cpp.
View newest version in sPHENIX GitHub at line 33 of file CartesianSegmentationTests.cpp
Referenced by BOOST_AUTO_TEST_CASE(), and SepdMonDraw::DrawFirst().
DigitizationModule Acts::Test::ndModule(cSegmentation, hThickness,-1, lAngle, 0., true)
std::vector<std::string> Acts::Test::notAllowedAxes = {"YZ*", "ZX*", "ZY*"}
Definition at line 53 of file TGeoTubeConversionTests.cpp.
View newest version in sPHENIX GitHub at line 53 of file TGeoTubeConversionTests.cpp
Referenced by BOOST_AUTO_TEST_CASE().
unsigned int Acts::Test::nrepts = 2000
Definition at line 35 of file SurfaceIntersectionBenchmark.cpp.
View newest version in sPHENIX GitHub at line 35 of file SurfaceIntersectionBenchmark.cpp
Referenced by intersectionTest().
const int Acts::Test::ntests = 10
Definition at line 34 of file SurfaceIntersectionBenchmark.cpp.
View newest version in sPHENIX GitHub at line 34 of file SurfaceIntersectionBenchmark.cpp
Referenced by Acts::Python::addExperimentalGeometry(), and Acts::Python::addPropagation().
double Acts::Test::oversteppingMaxStepSize = 1_mm
Definition at line 82 of file DirectNavigatorTests.cpp.
View newest version in sPHENIX GitHub at line 82 of file DirectNavigatorTests.cpp
Referenced by runTest().
bool Acts::Test::oversteppingTest = false
Definition at line 81 of file DirectNavigatorTests.cpp.
View newest version in sPHENIX GitHub at line 81 of file DirectNavigatorTests.cpp
Referenced by runTest().
double Acts::Test::oVlayerEnvelope = 0.5_mm
Definition at line 51 of file TrackingGeometryGeometryIdTests.cpp.
View newest version in sPHENIX GitHub at line 51 of file TrackingGeometryGeometryIdTests.cpp
auto Acts::Test::oVolume
Initial value:
= constructCylinderVolume(
    tgContext, oVsurfaceHalfLengthZ, oVsurfaceR, oVsurfaceRstagger,
    oVsurfaceZoverlap, oVlayerEnvelope, oVvolumeEnvelope, iVvolumeR, oVvolumeR,
    "OuterVolume")
outer volume
Definition at line 82 of file TrackingGeometryGeometryIdTests.cpp.
View newest version in sPHENIX GitHub at line 82 of file TrackingGeometryGeometryIdTests.cpp
Referenced by BOOST_AUTO_TEST_CASE(), Acts::constructContainerVolume(), and makeTrackingGeometry().
double Acts::Test::oVsurfaceHalfLengthZ = 50_mm
the surface radius (will also be the layer radius)
Definition at line 47 of file TrackingGeometryGeometryIdTests.cpp.
View newest version in sPHENIX GitHub at line 47 of file TrackingGeometryGeometryIdTests.cpp
double Acts::Test::oVsurfaceR = 100_mm
Definition at line 48 of file TrackingGeometryGeometryIdTests.cpp.
View newest version in sPHENIX GitHub at line 48 of file TrackingGeometryGeometryIdTests.cpp
double Acts::Test::oVsurfaceRstagger = 5_mm
Definition at line 49 of file TrackingGeometryGeometryIdTests.cpp.
View newest version in sPHENIX GitHub at line 49 of file TrackingGeometryGeometryIdTests.cpp
double Acts::Test::oVsurfaceZoverlap = 10_mm
Definition at line 50 of file TrackingGeometryGeometryIdTests.cpp.
View newest version in sPHENIX GitHub at line 50 of file TrackingGeometryGeometryIdTests.cpp
double Acts::Test::oVvolumeEnvelope = 10_mm
Definition at line 52 of file TrackingGeometryGeometryIdTests.cpp.
View newest version in sPHENIX GitHub at line 52 of file TrackingGeometryGeometryIdTests.cpp
double Acts::Test::oVvolumeHalfZ
Initial value:
=
    (4 * oVsurfaceHalfLengthZ - oVsurfaceZoverlap) + oVvolumeEnvelope
Definition at line 106 of file TrackingGeometryGeometryIdTests.cpp.
View newest version in sPHENIX GitHub at line 106 of file TrackingGeometryGeometryIdTests.cpp
double Acts::Test::oVvolumeR
Initial value:
=
    oVsurfaceR + 0.5 * oVsurfaceRstagger + oVlayerEnvelope + oVvolumeEnvelope
Definition at line 53 of file TrackingGeometryGeometryIdTests.cpp.
View newest version in sPHENIX GitHub at line 53 of file TrackingGeometryGeometryIdTests.cpp
const auto Acts::Test::particleHypothesis = ParticleHypothesis::pion() static
Definition at line 95 of file AtlasStepperTests.cpp.
View newest version in sPHENIX GitHub at line 95 of file AtlasStepperTests.cpp
Referenced by BOOST_AUTO_TEST_CASE().
DigitizationModule Acts::Test::pdModule(cSegmentation, hThickness, 1, lAngle, 0., true)
BinningData Acts::Test::phiData_arb(closed, binPhi, phiValues)
Referenced by BOOST_AUTO_TEST_CASE().
BinningData Acts::Test::phiData_eq(closed, binPhi, 5,-M_PI, M_PI)
Referenced by BOOST_AUTO_TEST_CASE().
double Acts::Test::phiDelta = 0.1064
Definition at line 79 of file BinningDataTests.cpp.
View newest version in sPHENIX GitHub at line 79 of file BinningDataTests.cpp
Referenced by BOOST_AUTO_TEST_CASE().
double Acts::Test::phiMin = -M_PI
Definition at line 77 of file BinningDataTests.cpp.
View newest version in sPHENIX GitHub at line 77 of file BinningDataTests.cpp
Referenced by Acts::Python::addExampleAlgorithms(), Acts::Python::addGenerators(), Acts::Python::addTrackFinding(), Acts::Python::addTruthTracking(), Acts::BinnedSPGroup< external_spacepoint_t >::BinnedSPGroup(), BOOST_AUTO_TEST_CASE(), create_cylinder(), create_disc(), Acts::TGeoSurfaceConverter::discComponents(), PHTpcCentralMembraneMatcher::GetNodes(), Acts::TrackSelector::Config::phi(), RandomHit(), Acts::Experimental::detail::CylindricalDetectorHelper::rzphiBoundaries(), and Acts::AnnulusBounds::toStream().
std::vector<float> Acts::Test::phiValues = {-M_PI, -2., -1., 1., 2., M_PI}
Definition at line 70 of file BinningDataTests.cpp.
View newest version in sPHENIX GitHub at line 70 of file BinningDataTests.cpp
Referenced by Acts::GeometryView3D::drawSurfaceArray().
PlanarModuleStepper Acts::Test::pmStepper
The Planar module stepper.
Definition at line 59 of file PlanarModuleStepperTests.cpp.
View newest version in sPHENIX GitHub at line 59 of file PlanarModuleStepperTests.cpp
Referenced by BOOST_DATA_TEST_CASE().
const Vector3 Acts::Test::pos = pos4.segment<3>(ePos0) static
Definition at line 90 of file AtlasStepperTests.cpp.
View newest version in sPHENIX GitHub at line 90 of file AtlasStepperTests.cpp
Referenced by TrackInfoContainer_v1::add_trackinfo(), Acts::AdaptiveMultiVertexFinder< vfitter_t, sfinder_t >::addCompatibleTracksToVertex(), ActsExamples::Sequencer::addElement(), PHG4GDMLWriteStructure::AddVolumeAuxiliary(), PHG4TpcDirectLaser::AppendLaserTrack(), PHG4GDMLWriteSolids::BooleanWrite(), BOOST_AUTO_TEST_CASE(), BOOST_AUTO_TEST_CASE(), Acts::Test::Layers::BOOST_AUTO_TEST_CASE(), BOOST_DATA_TEST_CASE(), Acts::IntegrationTest::BOOST_DATA_TEST_CASE(), BOOST_DATA_TEST_CASE(), BOOST_FIXTURE_TEST_CASE(), bin_heap< T, Pred >::bubble_down(), bin_heap< T, Pred >::bubble_up(), ActsExamples::MockupSectorBuilder::buildSector(), BJetModule::calc3DDCA(), HFTrigger::calcualteTrackVertex2DDCA(), HFTriggerMVA::calcualteTrackVertex2DDCA(), HFTrigger::calcualteTrackVertexDCA(), HFTriggerMVA::calcualteTrackVertexDCA(), ActsTransformations::calculateDCA(), IsolatedTrackAnalysis::calculateDCA(), InttVertexFinder::calculateZvertex(), ChargeMapReader::CanInterpolateAt(), Acts::AdaptiveMultiVertexFinder< vfitter_t, sfinder_t >::canRecoverFromNoCompatibleTracks(), planarity::case_E(), bin_heap< T, Pred >::changeKey(), checkErrorPropagation(), checkExtrapolateBy(), checkExtrapolateToCylinder(), checkExtrapolateToLine(), checkExtrapolateToPoint(), checkExtrapolateToSphere(), checkSetGetPosMom(), checkStopAtBoundary(), TrackSeed_v1::circleFitByTaubin(), collectData(), compareForthBackExtrapolation(), compareForthBackJacNoise(), DecayFinder::createDecayNode(), Acts::createGrid2D(), Acts::createGrid3D(), ResonanceJetTagging::createJetNode(), SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::CreateJetNode(), KFParticle_DST::createParticleNode(), Acts::Test::CubicBVHTrackingGeometry::CubicBVHTrackingGeometry(), oncsSub_idcaenv1742::decode(), oncsSub_idfnalmwpc::decode(), oncsSub_idfnalmwpcv2::decode(), Packet_hbd_fpgashort::decode(), Packet_hbd_fpga::decode(), oncsSub_idmvtxv2::decode(), TpcPrototypeGenFitTrkFitter::DisplayCluster(), doFitAndCalibUpdate(), HybridHadronization::DoHadronization(), doSeries(), doTscFit(), Fun4AllHistoManager::dumpHistos(), EMCalTowerRingStudy(), symlist< T >::erase(), TSQLStatement::Execute(), ActsExamples::VolumeAssociationTest::execute(), TSQLStatement::ExecuteQuery(), ExploreTTrees(), genfit::RKTrackRep::extrapolateBy(), genfit::RKTrackRep::extrapolateToCone(), genfit::RKTrackRep::extrapolateToCylinder(), genfit::RKTrackRep::extrapolateToSphere(), Acts::fieldMapRZ(), Acts::fieldMapXYZ(), Fill(), Acts::SurfaceArray::SurfaceGridLookup< Axes >::fill(), GenFitTrackProp::fill_tree(), Acts::Experimental::detail::BlueprintHelper::fillGaps(), TrkrNtuplizer::fillOutputNtuples(), SvtxEvaluator::fillOutputNtuples(), KFParticle_DST::fillParticleNode_Particle(), KFParticle_DST::fillParticleNode_Track(), PHActsKDTreeSeeding::fillTrackSeedContainer(), oncsSub_idtpcfeev3::find_header(), tpc_pool::find_header(), Cornelius::find_surface_3d(), PHActsKDTreeSeeding::findInttMatches(), PHG4GDMLWriteStructure::FindOpticalSurface(), Fun4All_AnaTutorial_sPHENIX(), Fun4All_AnaTutorial_sPHENIX_Jets(), Fun4All_G4_Calo(), Fun4All_G4_EICDetector_AnaTutorial(), Fun4All_G4_sPHENIX(), Fun4All_G4_sPHENIX_ForTrackCutStudy(), Fun4All_G4_sPHENIX_ForTrackCutStudy_EmbedScanOff(), Fun4All_G4_sPHENIX_ForTrackCutStudy_EmbedScanOn(), Fun4All_G4_sPHENIX_ForTrackCutStudy_WithPileup_EmbedScanOff(), Fun4All_G4_sPHENIX_ForTrackCutStudy_WithPileup_EmbedScanOn(), Fun4All_Pi0Gen_sPHENIX(), Fun4All_pi0tbt_SIMPLE_EMBED(), Fun4All_RunNewTruthMatcher(), Fun4All_SinglePhotonGen_sPHENIX(), Fun4All_SinglePi0Gen_sPHENIX(), Fun4All_TPC_EventDisplayPrep(), Fun4All_TPC_UnpackPRDF(), Fun4All_TPC_UnpackPRDF_Batch(), Fun4All_TrkrClusteringSeeding(), generate_distortion_map(), AnnularFieldSim::GenerateDistortionMaps(), AnnularFieldSim::GenerateSeparateDistortionMaps(), generateTruthIbfGainMap(), genfit::AbsTrackRep::get6DState(), genfit::AbsTrackRep::get6DStateCov(), TrackAnalysisUtils::get_dca(), SecondaryVertexFinder::get_dca(), FilterEvents::get_dca_SvtxEval(), GlobalVertexv2::get_position(), Acts::SurfaceArray::SurfaceGridLookup< Axes >::getBinCenterImpl(), getBinPosition(), PHG4GDMLWriteStructure::GetBorderSurface(), TpcPrototypeGenFitTrkFinder::getChi2Ndf(), Acts::MultiEigenStepperLoop< extensionlist_t, component_reducer_t, auctioneer_t >::getField(), MakeActsGeometry::getInttKeyFromNode(), MakeActsGeometry::getMvtxKeyFromNode(), AnnularFieldSim::GetPhiIndex(), AnnularFieldSim::GetPhiIndexAndCheckBounds(), genfit::HelixTrackModel::getPos(), dNdEtaINTT::GetRecoClusterInfo(), PHG4GDMLWriteStructure::GetSkinSurface(), genfit::GFTrackToTrack(), Acts::globalToLocalFromBin(), Initialise_info(), KFParticle_nTuple::initializeBranches(), TpcRawDataTree::InitRun(), TPCRawDataTree::InitRun(), symlist< T >::insert(), PHPointerList< T >::insertAt(), genfit::GFRaveMagneticField::inTesla(), TrackSeed_v1::lineFit(), TrackResiduals::lineFitClusters(), AnnularFieldSim::load_analytic_spacecharge(), main(), make_piston(), BDiJetModule::MakeGenFitTrack(), SVReco::MakeGenFitTrack(), genfit::EventDisplay::makeLines(), PHCosmicSeeder::makeSeeds(), SVReco::MakeSvtxTrack(), PHG4TrackFastSim::MakeSvtxTrack(), TpcPrototypeGenFitTrkFitter::MakeSvtxTrack(), PHGenFitTrkFitter::MakeSvtxTrack(), TpcPrototypeGenFitTrkFitter::MakeTpcPrototypeTrack(), Acts::materialMapperRZ(), Acts::materialMapperXYZ(), meanw(), mg_dns_encode_name(), mg_dns_encode_record(), mg_parse_multipart(), oncsSub_idmvtxv0::mvtx_decode(), oncsSub_idmvtxv1::mvtx_decode(), ActsExamples::Pythia8Generator::operator()(), ActsExamples::Options::operator>>(), DecayFinder::parseDecayDescriptor(), KFParticle_sPHENIX::parseDecayDescriptor(), PHG4TrackFastSim::PHG4HitToMeasurementCylinder(), PHG4TrackFastSim::PHG4HitToMeasurementVerticalPlane(), PHG4GDMLWriteStructure::PhysvolWrite(), OnlMonHtml::plainHtmlMenu(), Acts::Svg::EventDataConverter::pointXY(), Acts::Svg::EventDataConverter::pointZR(), PosFlip(), ActsExamples::HepMC3Vertex::position(), ActsExamples::Geant4::HepMC3::PrimaryGeneratorAction::prepareParticleGun(), genfit::KalmanFitterRefTrack::prepareTrack(), Fun4AllServer::Print(), genfit::MeasuredStateOnPlane::Print(), genfit::StateOnPlane::Print(), KFParticle_DST::printNode(), printProgress(), PHTruthVertexing::Process(), RecoInfoExport::process_event(), ReactionPlaneAfterburner::process_event(), TrackSeedTrackMapConverter::process_event(), PHCosmicTrackMerger::process_event(), PHSimpleVertexFinder::process_event(), PHGenFitTrackProjection::process_event(), PHSimpleKFProp::process_event(), TpcPrototypeGenFitTrkFinder::process_event(), PHTpcCentralMembraneClusterizer::process_event(), PHTpcCentralMembraneMatcher::process_event(), genfit::KalmanFitter::processTrackPartially(), genfit::KalmanFitterRefTrack::processTrackPoint(), genfit::KalmanFitterRefTrack::processTrackPointSqrt(), genfit::KalmanFitter::processTrackWithRep(), TrackProjectorPid::project_track(), TrackProjectorPlaneECAL::project_track(), KshortReconstruction::projectTrackToCylinder(), KshortReconstruction::projectTrackToPoint(), SecondaryVertexFinder::projectTrackToPoint(), ActsExamples::CsvPlanarClusterReader::read(), ActsExamples::RootAthenaNTupleReader::read(), ActsExamples::EDM4hepUtil::readMeasurement(), readTracksAndVertexCSV(), TpcPrototypeGenFitTrkFitter::ReFitTrack(), PHGenFitTrkFitter::ReFitTrack(), Fun4AllHistoManager::registerHisto(), PHCosmicTrackMerger::removeOutliers(), Acts::AdaptiveMultiVertexFinder< vfitter_t, sfinder_t >::removeTrackIfIncompatible(), Acts::TrackStateType::reset(), ActsExamples::CsvBFieldWriter::run(), run_calo_fromMDC2Hits_towslope_Fun4All_G4_Calo(), rundst_spiNo(), series(), Acts::TrackStateType::set(), genfit::RKTrackRep::setPosMomCov(), ActsExamples::HepMC3Event::shiftPositionTo(), TPCHitTrackDisplay::SimulationOut(), Acts::solenoidFieldMap(), ActsExamples::SpacePointMaker::SpacePointMaker(), spiNo2(), symlist< T >::splice(), testing::internal::SplitString(), ActsExamples::ModuleClusters::squash(), Acts::AtlasStepper::State::State(), Acts::EigenStepper< extensionlist_t, auctioneer_t >::step(), Acts::AtlasStepper::step(), HybridHadronization::stringprep(), AnnularFieldSim::sum_phislice_field_at(), Acts::SurfaceArrayCreator::surfaceArrayOnCylinder(), Acts::SurfaceArrayCreator::surfaceArrayOnDisc(), Acts::SurfaceArrayCreator::surfaceArrayOnPlane(), PHG4GDMLWriteStructure::SurfacesWrite(), remote_msg_buffer::sync(), testInterfaceConsistency(), tile(), ActsFatras::PlanarSurfaceDrift::toReadout(), oncsSub_idtpcfeev3::tpc_decode(), tpc_pool::tpc_decode(), TPCEventDisplay(), TPCEventDisplay_Updated(), TPCEventDisplay_Updated_BCO(), PHRaveVertexing::TranslateSvtxToGenFitTrack(), Acts::AtlasStepper::update(), PHActsVertexFinder::updateTrackDCA(), ActsExamples::ParticleKillAction::UserSteppingAction(), PHG4TrackFastSim::VertexMeasurement(), and ActsExamples::RootPlanarClusterWriter::writeT().
auto Acts::Test::rb = std::make_shared<RectangleBounds>(1_m, 1_m)
Definition at line 51 of file SurfaceIntersectionBenchmark.cpp.
View newest version in sPHENIX GitHub at line 51 of file SurfaceIntersectionBenchmark.cpp
Referenced by Acts::Legacy::AtlasSeedFinder< SpacePoint >::production3Sp().
BinningData Acts::Test::rData_eq(open, binR, 10, 0., 10.)
Referenced by BOOST_AUTO_TEST_CASE().
ViewConfig Acts::Test::red ({200, 0, 0})
Referenced by adaptColorPalette(), BOOST_AUTO_TEST_CASE(), BOOST_AUTO_TEST_CASE(), printBField(), PHG4ConeSubsystem::set_color(), PHG4BlockSubsystem::set_color(), PHG4CylinderSubsystem::set_color(), G4Example03Subsystem::set_color(), and sPhenixStyle().
bool Acts::Test::referenceTiming = false
Definition at line 80 of file DirectNavigatorTests.cpp.
View newest version in sPHENIX GitHub at line 80 of file DirectNavigatorTests.cpp
Referenced by runTest().
const MeasurementResolutionMap Acts::Test::resolutions
Initial value:
= {
    {GeometryIdentifier().setVolume(2), resPixel},
    {GeometryIdentifier().setVolume(3).setLayer(2), resStrip},
    {GeometryIdentifier().setVolume(3).setLayer(4), resStrip},
    {GeometryIdentifier().setVolume(3).setLayer(6), resStrip},
    {GeometryIdentifier().setVolume(3).setLayer(8), resStrip},
}
Definition at line 121 of file SpacePointBuilderTests.cpp.
View newest version in sPHENIX GitHub at line 121 of file SpacePointBuilderTests.cpp
Referenced by BOOST_AUTO_TEST_CASE(), BOOST_AUTO_TEST_CASE(), BOOST_DATA_TEST_CASE(), FitterTester::test_GlobalCovariance(), FitterTester::test_ZeroFieldNoSurfaceForward(), FitterTester::test_ZeroFieldShuffled(), FitterTester::test_ZeroFieldWithHole(), FitterTester::test_ZeroFieldWithOutliers(), FitterTester::test_ZeroFieldWithReverseFiltering(), FitterTester::test_ZeroFieldWithSurfaceAtExit(), FitterTester::test_ZeroFieldWithSurfaceBackward(), and FitterTester::test_ZeroFieldWithSurfaceForward().
const MeasurementResolution Acts::Test::resPixel
Initial value:
= {MeasurementType::eLoc01,
                                        {25_um, 50_um}}
Definition at line 117 of file SpacePointBuilderTests.cpp.
View newest version in sPHENIX GitHub at line 117 of file SpacePointBuilderTests.cpp
Referenced by BOOST_AUTO_TEST_CASE().
const MeasurementResolution Acts::Test::resStrip
Initial value:
= {MeasurementType::eLoc01,
                                        {100_um, 100_um}}
Definition at line 119 of file SpacePointBuilderTests.cpp.
View newest version in sPHENIX GitHub at line 119 of file SpacePointBuilderTests.cpp
RootGeometry Acts::Test::rGeometry = RootGeometry()
Definition at line 49 of file TGeoLayerBuilderTests.cpp.
View newest version in sPHENIX GitHub at line 49 of file TGeoLayerBuilderTests.cpp
BinningData Acts::Test::rPhiData_eq(closed, binRPhi, 5,-M_PI, M_PI)
double Acts::Test::sguardX = 2 * hThickness * abs(tanAlpha)
Definition at line 44 of file PlanarModuleStepperTests.cpp.
View newest version in sPHENIX GitHub at line 44 of file PlanarModuleStepperTests.cpp
const int Acts::Test::skip = 0
Definition at line 78 of file DirectNavigatorTests.cpp.
View newest version in sPHENIX GitHub at line 78 of file DirectNavigatorTests.cpp
Referenced by Acts::Python::addFramework(), BOOST_DATA_TEST_CASE(), draw_corr(), find_json_token(), Fun4All_G4_sPHENIX(), AnnularFieldSim::interpolatedFieldIntegral(), main(), ReconstructTracks(), runTest(), PHG4TpcDigitizer::set_skip_noise_flag(), Acts::AxisAlignedBoundingBox< entity_t, value_t, DIM >::setSkip(), and AnnularFieldSim::sum_nonlocal_field_at().
StraightLineStepper Acts::Test::slstepper
Definition at line 78 of file MaterialCollectionTests.cpp.
View newest version in sPHENIX GitHub at line 78 of file MaterialCollectionTests.cpp
template<typename T > constexpr bool Acts::Test::SomeConcept
Initial value:
=
    require<has_method<T, double, foo_method_t, double, int>,
            has_method<const T, bool, bar_method_t, double&&>,
            has_member<T, member_t, bool>, exists<nested_t, T>,
            exists<meta_t, T>>
Definition at line 182 of file TypeTraitsTest.cpp.
View newest version in sPHENIX GitHub at line 182 of file TypeTraitsTest.cpp
std::vector<float> Acts::Test::sstr = {0., 1., 1.5, 2., 3.}
Definition at line 82 of file BinningDataTests.cpp.
View newest version in sPHENIX GitHub at line 82 of file BinningDataTests.cpp
constexpr auto Acts::Test::stepSize = 10_mm static
Definition at line 82 of file AtlasStepperTests.cpp.
View newest version in sPHENIX GitHub at line 82 of file AtlasStepperTests.cpp
Referenced by BOOST_AUTO_TEST_CASE(), Acts::GaussianTrackDensity< input_track_t >::globalMaximumWithWidth(), ActsFatras::detail::SimulationActor< generator_t, decay_t, interactions_t, hit_surface_selector_t >::operator()(), Acts::AtlasStepper::resetState(), Acts::MultiEigenStepperLoop< extensionlist_t, component_reducer_t, auctioneer_t >::resetState(), and Acts::detail::updateSingleStepSize().
std::vector<std::unique_ptr<const Surface> > Acts::Test::stepState
Definition at line 60 of file ExtrapolatorTests.cpp.
View newest version in sPHENIX GitHub at line 60 of file ExtrapolatorTests.cpp
double Acts::Test::tanAlpha = tan(lAngle)
Definition at line 43 of file PlanarModuleStepperTests.cpp.
View newest version in sPHENIX GitHub at line 43 of file PlanarModuleStepperTests.cpp
Referenced by Acts::ConeVolumeBounds::ConeVolumeBounds().
GeometryContext Acts::Test::testContext = GeometryContext()
Definition at line 50 of file CylinderSurfaceTests.cpp.
View newest version in sPHENIX GitHub at line 50 of file CylinderSurfaceTests.cpp
Referenced by BOOST_AUTO_TEST_CASE().
const bool Acts::Test::testCylinder = true
Definition at line 39 of file SurfaceIntersectionBenchmark.cpp.
View newest version in sPHENIX GitHub at line 39 of file SurfaceIntersectionBenchmark.cpp
Referenced by BOOST_DATA_TEST_CASE().
const bool Acts::Test::testDisc = true
Definition at line 38 of file SurfaceIntersectionBenchmark.cpp.
View newest version in sPHENIX GitHub at line 38 of file SurfaceIntersectionBenchmark.cpp
Referenced by BOOST_DATA_TEST_CASE().
std::vector<std::tuple<std::string, bool, unsigned int> > Acts::Test::testModes
Initial value:
= {
    {"", false, 72}, {"Triangulate", true, 72}, {"Extremas", false, 1}}
Definition at line 64 of file PolyhedronSurfacesTests.cpp.
View newest version in sPHENIX GitHub at line 64 of file PolyhedronSurfacesTests.cpp
Referenced by BOOST_AUTO_TEST_CASE().
std::vector<DigitizationModule> Acts::Test::testModules = {pdModule, ndModule}
Definition at line 56 of file PlanarModuleStepperTests.cpp.
View newest version in sPHENIX GitHub at line 56 of file PlanarModuleStepperTests.cpp
Referenced by BOOST_DATA_TEST_CASE().
const bool Acts::Test::testPlane = true
Definition at line 37 of file SurfaceIntersectionBenchmark.cpp.
View newest version in sPHENIX GitHub at line 37 of file SurfaceIntersectionBenchmark.cpp
Referenced by BOOST_DATA_TEST_CASE().
const bool Acts::Test::testStraw = true
Definition at line 40 of file SurfaceIntersectionBenchmark.cpp.
View newest version in sPHENIX GitHub at line 40 of file SurfaceIntersectionBenchmark.cpp
Referenced by BOOST_DATA_TEST_CASE().
auto Acts::Test::tg = grid.trackingGeometry
Definition at line 24 of file TrackingVolumeTests.cpp.
View newest version in sPHENIX GitHub at line 24 of file TrackingVolumeTests.cpp
GeometryContext Acts::Test::tgContext = GeometryContext()
Definition at line 43 of file SurfaceIntersectionBenchmark.cpp.
View newest version in sPHENIX GitHub at line 43 of file SurfaceIntersectionBenchmark.cpp
Referenced by BOOST_AUTO_TEST_CASE(), BOOST_DATA_TEST_CASE(), BOOST_FIXTURE_TEST_CASE(), draw_surfaces(), Acts::Test::SurfaceArrayFixture::draw_surfaces(), Acts::Test::SurfaceArrayCreatorFixture::makeBarrelStagger(), and Acts::Test::LayerCreatorFixture::makeBarrelStagger().
auto Acts::Test::tGeometry = cGeometry()
Definition at line 58 of file DirectNavigatorTests.cpp.
View newest version in sPHENIX GitHub at line 58 of file DirectNavigatorTests.cpp
Referenced by BOOST_AUTO_TEST_CASE().
const auto Acts::Test::time = pos4[eTime] static
Definition at line 91 of file AtlasStepperTests.cpp.
View newest version in sPHENIX GitHub at line 91 of file AtlasStepperTests.cpp
Referenced by myAnalysis::analyze(), ATrace::ATrace(), BOOST_AUTO_TEST_CASE(), BOOST_AUTO_TEST_CASE(), BOOST_DATA_TEST_CASE(), BOOST_DATA_TEST_CASE(), CaloWaveformFitting::calo_processing_fast(), MySQLConnectionPrivate::CheckIfServerIsAlive(), OnCalServer::CreateCalibrationUpdateStatus(), daq_begin(), daq_end(), daq_generate_json(), daq_get_events_per_second(), daq_get_mb_per_second(), daq_status(), OnlMonDB::DBcommitTest(), destroyhlle_(), ratio_cut_partition::determine_source_node(), Matter::DoEnergyLoss(), LBT::DoEnergyLoss(), Draw_EICRate(), InttMonDraw::DrawGlobalChipMap(), InttMonDraw::DrawGlobalLadderMap(), MyMonDraw::DrawHistory(), DaqMonDraw::DrawHistory(), MvtxMonDraw::DrawHistory(), OnCalServer::End(), ElogHandler::EndrunLog(), clvisc::CLIdeal::evolve(), clvisc::CLVisc::evolve(), ActsExamples::SurfaceSortingAlgorithm::execute(), ActsExamples::ParticleSmearing::execute(), ATrace::FitLeftEdge(), Fun(), get_runduration(), testEventiterator::getNextEvent(), gettimehlle_(), PhDi::GetValue(), handle_this_child(), Matter::Init(), inithydrohlle_(), main(), mg_check_nonce(), mg_hexdump_connection(), mg_http_create_digest_auth_header(), mg_http_send_digest_auth_request(), mg_http_send_file2(), mg_resolve_async_eh(), mg_server(), Acts::Logging::TimedOutputDecorator::now(), PHTimeStamp::PHTimeStamp(), daqONCSEvent::prepare_next(), daqPRDFEvent::prepare_next(), ospEvent::prepare_next(), oEvent::prepare_next(), process_event(), HcalMon::process_event(), HepMCNodeReader::process_event(), CaloTowerStatus::process_event(), PHG4InttHitReco::process_event(), caloTreeGen::process_event(), RawTowerv1::RawTowerv1(), ActsExamples::CsvPlanarClusterReader::read(), readout(), Acts::Vertex< input_track_t >::setPosition(), Acts::Vertex< input_track_t >::setTime(), genfit::RKTrackRep::setTime(), genfit::TrackCand::setTime6DSeed(), genfit::TrackCand::setTime6DSeedAndPdgCode(), genfit::TrackCand::setTimePosMomSeed(), genfit::TrackCand::setTimePosMomSeedAndPdgCode(), genfit::Track::setTimeSeed(), genfit::TrackCand::setTimeSeed(), PHTimeStamp::setToSystemTime(), QuickTest::SetUp(), ActsExamples::HepMC3Event::shiftPositionTo(), fm_partition::shuffle_vector(), simulateTimestamps(), QuickTest::TearDown(), TEST(), testing::gmock_matchers_test::TEST_P(), testEventiterator::testEventiterator(), ActsExamples::HepMC3Vertex::time(), Acts::MultiEigenStepperLoop< extensionlist_t, component_reducer_t, auctioneer_t >::time(), Acts::DetectorJsonConverter::toJson(), Acts::DetectorJsonConverter::toJsonDetray(), Acts::detail::transformFreeToBoundParameters(), Acts::detail::transformFreeToCurvilinearParameters(), Acts::EigenStepper< extensionlist_t, auctioneer_t >::update(), update_process(), ActsExamples::ParticleKillAction::UserSteppingAction(), writebuffers(), PHParametersContainer::WriteToFile(), PdbParameterMapContainer::WriteToFile(), and PHParameters::WriteToFile().
std::filesystem::path Acts::Test::tmp_path
Initial value:
= []() {
  auto p = std::filesystem::temp_directory_path() / "acts_unit_tests";
  std::filesystem::create_directory(p);
  std::cout << "Writing test output to: " << p << std::endl;
  return p;
}()
Definition at line 48 of file BoundingBoxTest.cpp.
View newest version in sPHENIX GitHub at line 48 of file BoundingBoxTest.cpp
Referenced by BOOST_AUTO_TEST_CASE(), and tmp().
constexpr auto Acts::Test::tolerance = 10_um static
Definition at line 83 of file AtlasStepperTests.cpp.
View newest version in sPHENIX GitHub at line 83 of file AtlasStepperTests.cpp
Referenced by Fatras::Test::BOOST_AUTO_TEST_CASE(), Acts::Test::Layers::BOOST_AUTO_TEST_CASE(), BOOST_AUTO_TEST_CASE(), Acts::detail::checkIntersection(), Acts::GenericBoundTrackParameters< ParticleHypothesis >::create(), Acts::CylinderSurface::globalToLocal(), Acts::LineSurface::intersect(), invertFunc(), is_integer(), Acts::isEqual(), Acts::detail::VerticesHelper::onHyperPlane(), Acts::PathLimitReached::operator()(), ActsFatras::BoundParametersSmearer< RandomEngine, kSmearDIM >::operator()(), Acts::Test::SurfaceObserver< Surface >::operator()(), Acts::SurfaceReached::operator()(), Acts::Test::EndOfWorld::operator()(), Acts::Layer::surfaceOnApproach(), TEST_CASE(), and Acts::CylinderVolumeBuilder::trackingVolume().
const std::string Acts::Test::toolString = "AMVF"
Definition at line 70 of file AdaptiveMultiVertexFinderTests.cpp.
View newest version in sPHENIX GitHub at line 70 of file AdaptiveMultiVertexFinderTests.cpp
Referenced by BOOST_AUTO_TEST_CASE().
auto Acts::Test::transform = std::make_shared<Transform3>(Transform3::Identity())
Definition at line 67 of file PolyhedronSurfacesTests.cpp.
View newest version in sPHENIX GitHub at line 67 of file PolyhedronSurfacesTests.cpp
Referenced by Acts::Python::addExperimentalGeometry(), alignmentTransformationContainer::addTransform(), AlgoFromString(), ALICEKF::ALICEKalmanFilter(), ActsAlignment::Alignment< fitter_t >::align(), Acts::Surface::alignmentToBoundDerivativeWithoutCorrection(), Acts::ConeSurface::alignmentToPathDerivative(), Acts::CylinderSurface::alignmentToPathDerivative(), Acts::LineSurface::alignmentToPathDerivative(), Acts::Surface::alignmentToPathDerivative(), BOOST_AUTO_TEST_CASE(), Acts::detail::Test::BOOST_AUTO_TEST_CASE(), BOOST_AUTO_TEST_CASE(), BOOST_DATA_TEST_CASE(), BOOST_FIXTURE_TEST_CASE(), Acts::GenericCuboidVolumeBounds::boundingBox(), Acts::TrapezoidVolumeBounds::boundingBox(), ActsExamples::MockupSectorBuilder::buildSector(), Acts::Surface::center(), Acts::Experimental::DetectorVolume::center(), Acts::DD4hepLayerBuilder::centralLayers(), Acts::DD4hepVolumeBuilder::centralVolumes(), OnCalServer::check_calibrator_in_statustable(), PktSizeDBodbc::CheckAndCreateTable(), OnlMonDBodbc::CheckAndCreateTable(), Acts::Experimental::KdtSurfaces< kDIM, bSize, reference_generator >::cog(), Acts::Experimental::DetectorVolumeBuilder::construct(), Acts::Experimental::DetectorVolume::construct(), PHG4MicromegasDetector::construct_micromegas(), PHG4HcalPrototypeDetector::ConstructDetector(), Acts::PodioUtil::convertSurfaceFromPodio(), TpcSpaceChargeReconstruction::create_histograms(), PHG4MvtxSupport::CreateCable(), Acts::CylinderVolumeHelper::createCylinderLayer(), Acts::CylinderVolumeHelper::createDiscLayer(), Acts::EventDataView3D::createEllipse(), Acts::SurfaceArrayCreator::createEquidistantAxis(), PHCASeeding::CreateLinks(), AlignmentTransformation::createMap(), Acts::detail::VerticesHelper::createSegment(), Acts::SurfaceArrayCreator::createVariableAxis(), Acts::TGeoSurfaceConverter::cylinderComponents(), Acts::TGeoSurfaceConverter::discComponents(), Acts::GeometryView3D::drawVolume(), OnlMonDBodbc::DropTable(), Acts::DD4hepLayerBuilder::endcapLayers(), Acts::estimateTrackParamsFromSeed(), ActsExamples::PrototracksToSeeds::execute(), ActsExamples::SeedsToPrototracks::execute(), ActsExamples::PrototracksToParameters::execute(), Acts::Polyhedron::extent(), Acts::extractTransform(), Acts::ObjVisualization3D< T >::faces(), ActsExamples::Sequencer::fpeReport(), Acts::DetectorVolumeJsonConverter::fromJson(), Acts::IndexedSurfacesJsonConverter::fromJson(), MicromegasMapping::get_fee_id_list(), ALICEKF::GetCircleClusterResiduals(), TrackFitUtils::getCircleClusterResiduals(), TrkrClusterContainerv3::getHitSetKeys(), TrkrClusterContainerv4::getHitSetKeys(), ALICEKF::GetLineClusterResiduals(), TrackFitUtils::getLineClusterResiduals(), PHActsInitialVertexFinder::getTrackPointers(), Acts::PlaneSurface::globalToLocal(), Acts::ConeSurface::globalToLocal(), Acts::CylinderSurface::globalToLocal(), Acts::LineSurface::globalToLocal(), Acts::CylinderVolumeHelper::glueTrackingVolumes(), hijfst_control(), OnlMonDBodbc::Info(), Acts::Volume::inside(), Acts::Experimental::DetectorVolume::inside(), Acts::ConeSurface::intersect(), Acts::PlaneSurface::intersect(), Acts::CylinderSurface::intersect(), Acts::LineSurface::intersect(), Acts::ConeSurface::intersectionSolver(), Acts::LineSurface::lineDirection(), Acts::ConeSurface::localCartesianToBoundLocalDerivative(), Acts::CylinderSurface::localCartesianToBoundLocalDerivative(), Acts::LineSurface::localCartesianToBoundLocalDerivative(), Acts::PlaneSurface::localToGlobal(), Acts::ConeSurface::localToGlobal(), Acts::LineSurface::localToGlobal(), Acts::CylinderSurface::localToGlobal(), main(), PHActsTrackProjection::makeCaloSurfacePtrs(), Acts::Polyhedron::merge(), Acts::AtlasBetheHeitlerApprox< NComponents, PolyDegree >::mixture(), DecayFinder::multiplyVectorByScalarAndSort(), AlignmentTransformation::newMakeTransform(), ActsExamples::Contextual::InternallyAlignedDetectorElement::nominalTransform(), Acts::PlaneSurface::normal(), Acts::ConeSurface::normal(), Acts::CylinderSurface::normal(), OnlMonDBodbc::OnlMonDBodbc(), Acts::CutoutCylinderVolumeBounds::orientedSurfaces(), Acts::ConeVolumeBounds::orientedSurfaces(), Acts::CylinderVolumeBounds::orientedSurfaces(), Acts::ConeSurface::pathCorrection(), Acts::TGeoSurfaceConverter::planeComponents(), Acts::PerigeeSurface::polyhedronRepresentation(), Acts::StrawSurface::polyhedronRepresentation(), Acts::PlaneSurface::polyhedronRepresentation(), Acts::ConeSurface::polyhedronRepresentation(), Acts::CylinderSurface::polyhedronRepresentation(), ambiguity_solver_full_chain::prepareInferenceData(), prepareSourceLinks(), FitterTester::prepareSourceLinks(), train_ambiguity_solver::prepareTrainingData(), HelicalFitter::process_event(), KshortReconstruction::projectTrackToCylinder(), PHSimpleKFProp::PropagateTrack(), ActsExamples::prototrackToSeed(), ActsExamples::CsvMeasurementReader::read(), PHPythia6::ReadConfig(), PHParameters::ReadFromDB(), PHParameters::ReadFromFile(), Acts::Surface::referenceFrame(), OnlMonDB::registerVar(), ActsExamples::SensitiveSurfaceMapper::remapSensitiveNames(), alignmentTransformationContainer::replaceTransform(), MakeSourceLinks::resetTransientTransformMap(), Acts::ConeSurface::rotSymmetryAxis(), Acts::CylinderSurface::rotSymmetryAxis(), Acts::TGeoParser::select(), OnlMonDB::SetVar(), ActsExamples::TGeoITkModuleSplitter::splitBarrelModule(), ActsExamples::TGeoITkModuleSplitter::splitDiscModule(), Acts::AtlasStepper::State::State(), Acts::SurfaceArrayCreator::surfaceArrayOnCylinder(), Acts::SurfaceArrayCreator::surfaceArrayOnDisc(), Acts::SurfaceArrayCreator::surfaceArrayOnPlane(), Acts::PortalJsonConverter::toJsonDetray(), Acts::Surface::toStream(), Acts::CylinderVolumeBuilder::trackingVolume(), sPHENIXActsDetectorElement::transform(), Acts::Geant4AlgebraConverter::transform(), ActsExamples::Contextual::ExternallyAlignedDetectorElement::transform(), Acts::KDTreeTrackingGeometryBuilder::translateLayer(), Acts::AtlasStepper::update(), Acts::AxisAlignedBoundingBox< entity_t, value_t, DIM >::wrap(), PHParametersContainer::WriteToDB(), PHParameters::WriteToDB(), PHParametersContainer::WriteToFile(), PdbParameterMapContainer::WriteToFile(), PHParameters::WriteToFile(), and Acts::Svg::View::xy().
const Vector3 Acts::Test::unitDir = Vector3(-2, 2, 1).normalized() static
Definition at line 92 of file AtlasStepperTests.cpp.
View newest version in sPHENIX GitHub at line 92 of file AtlasStepperTests.cpp
Referenced by BOOST_AUTO_TEST_CASE().
double Acts::Test::valueMin = 0.
Definition at line 76 of file BinningDataTests.cpp.
View newest version in sPHENIX GitHub at line 76 of file BinningDataTests.cpp
Referenced by BOOST_AUTO_TEST_CASE().
std::vector<float> Acts::Test::values = {0., 1., 2., 3., 4., 10.}
Definition at line 64 of file BinningDataTests.cpp.
View newest version in sPHENIX GitHub at line 64 of file BinningDataTests.cpp
Referenced by Acts::Python::addFramework(), BOOST_AUTO_TEST_CASE(), BOOST_AUTO_TEST_CASE(), TpcMon::calculateMedianAndStdDev(), collectData(), Acts::PodioUtil::convertSurfaceToPodio(), Acts::ConvexPolygonBounds< N >::ConvexPolygonBounds(), testing::internal::TuplePrefix< N >::ExplainMatchFailuresTo(), ActsExamples::TelescopeDetectorWithOptions::finalize(), Acts::GridJsonConverter::fromJson(), ParameterReader::getVal(), main(), ActsExamples::Options::operator<<(), ParameterReader::ParameterReader(), Acts::CartesianSegmentation::pitch(), plotTimes(), CaloTemplateFit::process_event(), ActsExamples::Options::readMagneticField(), ActsExamples::Options::readTrackFindingConfig(), ParameterReader::setVal(), ActsExamples::TGeoITkModuleSplitter::splitDiscModule(), Acts::Test::MultiTrajectoryTestsCommon< factory_t >::testTrackStateProxyCopy(), Acts::Test::MultiTrajectoryTestsCommon< factory_t >::testTrackStateProxyCopyDiffMTJ(), Acts::Test::MultiTrajectoryTestsCommon< factory_t >::testTrackStateProxyGetMask(), Acts::ConvexPolygonBoundsBase::values(), Acts::RiddersPropagator< propagator_t >::wiggleParameter(), and ParameterReader::~ParameterReader().
auto Acts::Test::volumes = grid.volumes
Definition at line 23 of file TrackingVolumeTests.cpp.
View newest version in sPHENIX GitHub at line 23 of file TrackingVolumeTests.cpp
BinningData Acts::Test::xData_arb(open, binX, values)
Referenced by BOOST_AUTO_TEST_CASE().
BinningData Acts::Test::xData_eq(open, binX, 10, 0., 10.)
Referenced by BOOST_AUTO_TEST_CASE().
BinningData Acts::Test::xData_eq_copy(open, binX, 10, 0., 10.)
Referenced by BOOST_AUTO_TEST_CASE().
BinningData Acts::Test::xData_mult(open, binX, 3, 0., 9., std::move(xData_sstr_mult))
Referenced by BOOST_AUTO_TEST_CASE().
auto Acts::Test::xData_sstr_add = std::make_unique<const BinningData>(open, binX, sstr)
Definition at line 90 of file BinningDataTests.cpp.
View newest version in sPHENIX GitHub at line 90 of file BinningDataTests.cpp
auto Acts::Test::xData_sstr_mult = std::make_unique<const BinningData>(open, binX, sstr)
Definition at line 84 of file BinningDataTests.cpp.
View newest version in sPHENIX GitHub at line 84 of file BinningDataTests.cpp
BinningData Acts::Test::yData_arb(open, binY, values)
Referenced by BOOST_AUTO_TEST_CASE().
BinningData Acts::Test::yData_eq(open, binY, 10, 0., 10.)
Referenced by BOOST_AUTO_TEST_CASE().
BinningData Acts::Test::zData_eq(open, binZ, 10, 0., 10.)
Referenced by BOOST_AUTO_TEST_CASE().
const double Acts::Test::zVertexPos = 12.
Definition at line 203 of file TrackDensityVertexFinderTests.cpp.
View newest version in sPHENIX GitHub at line 203 of file TrackDensityVertexFinderTests.cpp
Referenced by BOOST_AUTO_TEST_CASE().
const double Acts::Test::zVertexPos1 = 12.
Definition at line 57 of file GridDensityVertexFinderTests.cpp.
View newest version in sPHENIX GitHub at line 57 of file GridDensityVertexFinderTests.cpp
Referenced by BOOST_AUTO_TEST_CASE().
const double Acts::Test::zVertexPos2 = -3.
Definition at line 58 of file GridDensityVertexFinderTests.cpp.
View newest version in sPHENIX GitHub at line 58 of file GridDensityVertexFinderTests.cpp
Referenced by BOOST_AUTO_TEST_CASE().