Analysis Software: ActsExamples::EventGenerator Exception Reference
ActsExamples::EventGenerator Exception Reference final
#include <acts/blob/sPHENIX/Examples/Algorithms/Generators/ActsExamples/Generators/EventGenerator.hpp>
Classes
struct Config
struct Generator
Combined struct which contains all generator components.
struct MultiplicityGenerator
Generator interface for event multiplicity of vertices.
struct ParticlesGenerator
Generator interface particles for a vertex.
struct VertexGenerator
Generator interface for a vertex position.
Public Member Functions
EventGenerator (const Config &cfg, Acts::Logging::Level lvl)
std::string name () const final
Name of the reader.
std::pair< size_t, size_t > availableEvents () const final
Available events range. Always return [0,SIZE_MAX) since we generate them.
ProcessCode read (const AlgorithmContext &ctx) final
Generate an event.
const Config & config () const
Const access to the config.
Public Member Functions inherited from ActsExamples::IReader
ProcessCode internalExecute (const AlgorithmContext &context) final
ProcessCode initialize () override
Fulfill the algorithm interface.
ProcessCode finalize () override
Fulfill the algorithm interface.
Public Member Functions inherited from ActsExamples::SequenceElement
virtual ~SequenceElement ()=default
const std::vector< const
DataHandleBase * > & writeHandles () const
const std::vector< const
DataHandleBase * > & readHandles () const
Private Member Functions
const Acts::Logger & logger () const
Private Attributes
Config m_cfg
std::unique_ptr< const
Acts::Logger > m_logger
WriteDataHandle
< SimParticleContainer > m_outputParticles
Detailed Description
Event generator based on separate particles and vertex generators.
This must be a reader and not just an algorithm since it might read in pre-computed generator samples, e.g. via HepMC, and therefore has an internal state that will be modified.
Definition at line 38 of file EventGenerator.hpp.
View newest version in sPHENIX GitHub at line 38 of file EventGenerator.hpp
Constructor & Destructor Documentation
ActsExamples::EventGenerator::EventGenerator (const Config & cfg, Acts::Logging::Level lvl)
Definition at line 19 of file EventGenerator.cpp.
View newest version in sPHENIX GitHub at line 19 of file EventGenerator.cpp
References ActsExamples::EventGenerator::Config::generators, ActsExamples::WriteDataHandle< T >::initialize(), m_cfg, m_outputParticles, ActsExamples::EventGenerator::Config::outputParticles, and ActsExamples::EventGenerator::Config::randomNumbers.
Member Function Documentation
std::pair< size_t, size_t > ActsExamples::EventGenerator::availableEvents () const final virtual
Available events range. Always return [0,SIZE_MAX) since we generate them.
Implements ActsExamples::IReader.
Definition at line 39 of file EventGenerator.cpp.
View newest version in sPHENIX GitHub at line 39 of file EventGenerator.cpp
References physmon_ckf_tracking::u.
const Config& ActsExamples::EventGenerator::config () const inline
Const access to the config.
Definition at line 114 of file EventGenerator.hpp.
View newest version in sPHENIX GitHub at line 114 of file EventGenerator.hpp
References m_cfg.
Referenced by Acts::Python::addGenerators().
const Acts::Logger& ActsExamples::EventGenerator::logger () const inline private
Definition at line 117 of file EventGenerator.hpp.
View newest version in sPHENIX GitHub at line 117 of file EventGenerator.hpp
References m_logger.
std::string ActsExamples::EventGenerator::name () const final virtual
Name of the reader.
Implements ActsExamples::SequenceElement.
Definition at line 35 of file EventGenerator.cpp.
View newest version in sPHENIX GitHub at line 35 of file EventGenerator.cpp
ActsExamples::ProcessCode ActsExamples::EventGenerator::read (const AlgorithmContext & ctx) final virtual
Generate an event.
Implements ActsExamples::IReader.
Definition at line 44 of file EventGenerator.cpp.
View newest version in sPHENIX GitHub at line 44 of file EventGenerator.cpp
References ACTS_DEBUG, ACTS_VERBOSE, ActsExamples::AlgorithmContext::eventNumber, m_cfg(), testing::internal::move(), n, particle, particles, train_ambiguity_solver::pid, Acts::Test::pos4(), conftest::rng(), and SUCCESS.
Member Data Documentation
Config ActsExamples::EventGenerator::m_cfg private
Definition at line 119 of file EventGenerator.hpp.
View newest version in sPHENIX GitHub at line 119 of file EventGenerator.hpp
Referenced by config(), and EventGenerator().
std::unique_ptr<const Acts::Logger> ActsExamples::EventGenerator::m_logger private
Definition at line 120 of file EventGenerator.hpp.
View newest version in sPHENIX GitHub at line 120 of file EventGenerator.hpp
Referenced by logger().
WriteDataHandle<SimParticleContainer> ActsExamples::EventGenerator::m_outputParticles private
Initial value:
{this,
                                                          "OutputParticles"}
Definition at line 122 of file EventGenerator.hpp.
View newest version in sPHENIX GitHub at line 122 of file EventGenerator.hpp
Referenced by EventGenerator().
The documentation for this exception was generated from the following files:
acts/blob/sPHENIX/Examples/Algorithms/Generators/ActsExamples/Generators/EventGenerator.hpp
acts/blob/sPHENIX/Examples/Algorithms/Generators/ActsExamples/Generators/EventGenerator.cpp