Analysis Software: TrkrHit Class Reference
TrkrHit Class Reference
Base class for hit object.
#include <coresoftware/blob/master/offline/packages/trackbase/TrkrHit.h>
Public Member Functions
~TrkrHit () override
dtor
void identify (std::ostream &os=std::cout) const override
void Reset () override
Clear Event.
int isValid () const override
isValid returns non zero if object contains vailid data
virtual void addEnergy (const double)
virtual double getEnergy ()
virtual void setAdc (const unsigned int)
virtual unsigned int getAdc ()
Public Member Functions inherited from PHObject
PHObject ()
ctor
~PHObject () override
dtor
virtual PHObject * CloneMe () const
Virtual copy constructor.
virtual PHObject * clone () const final
PHObject * Clone (const char *newname="") const final
void Copy (TObject &object) const final
virtual int Integrate () const
virtual int Integrate (PHObject *)
virtual void CopyFrom (const PHObject *obj)
Protected Member Functions
ClassDefOverride (TrkrHit, 1)
Detailed Description
Base class for hit object.
This is the empty virtual base class for a hit object. Each subsystem should implement an inherited version which contains the actual storage information.
Definition at line 25 of file TrkrHit.h.
View newest version in sPHENIX GitHub at line 25 of file TrkrHit.h
Constructor & Destructor Documentation
TrkrHit::~TrkrHit () inline override
dtor
Definition at line 30 of file TrkrHit.h.
View newest version in sPHENIX GitHub at line 30 of file TrkrHit.h
Member Function Documentation
virtual void TrkrHit::addEnergy (const double) inline virtual
Reimplemented in TrkrHitv2, and TrkrHitv1.
Definition at line 40 of file TrkrHit.h.
View newest version in sPHENIX GitHub at line 40 of file TrkrHit.h
Referenced by TpcClusterBuilder::addhitset(), PHG4InttHitReco::addtruthhitset(), PHG4MvtxHitReco::addtruthhitset(), PHG4TpcPadPlaneReadout::MapToPadPlane(), PHG4InttHitReco::process_event(), PHG4MvtxHitReco::process_event(), and PHG4TpcElectronDrift::process_event().
TrkrHit::ClassDefOverride (TrkrHit , 1) protected
virtual unsigned int TrkrHit::getAdc () inline virtual
Reimplemented in TrkrHitv2, and TrkrHitv1.
Definition at line 45 of file TrkrHit.h.
View newest version in sPHENIX GitHub at line 45 of file TrkrHit.h
Referenced by PHG4TpcDigitizer::DigitizeCylinderCells(), PHG4InttDigitizer::DigitizeLadderCells(), TrkrNtuplizer::fillOutputNtuples(), SvtxEvaluator::fillOutputNtuples(), TrackerEventDisplay::makeJsonFile(), SynRadAna::process_event(), readDigitalCurrents::process_event(), and DumpTrkrHitSetContainer::process_Node().
virtual double TrkrHit::getEnergy () inline virtual
Reimplemented in TrkrHitv2, and TrkrHitv1.
Definition at line 41 of file TrkrHit.h.
View newest version in sPHENIX GitHub at line 41 of file TrkrHit.h
Referenced by PHG4InttDigitizer::DigitizeLadderCells(), PHG4MvtxDigitizer::DigitizeMvtxLadderCells(), TrkrNtuplizer::fillOutputNtuples(), SvtxEvaluator::fillOutputNtuples(), PHG4MicromegasDigitizer::process_event(), PHG4TpcPadBaselineShift::process_event(), PHG4MvtxHitReco::process_event(), PHG4InttHitReco::process_event(), PHG4TpcElectronDrift::process_event(), readDigitalCurrents::process_event(), and DumpTrkrHitSetContainer::process_Node().
void TrkrHit::identify (std::ostream & os = std::cout) const inline override virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from PHObject.
Reimplemented in TrkrHitv2, and TrkrHitv1.
Definition at line 32 of file TrkrHit.h.
View newest version in sPHENIX GitHub at line 32 of file TrkrHit.h
References os.
Referenced by PHG4InttDigitizer::DigitizeLadderCells(), and SynRadAna::process_event().
int TrkrHit::isValid () const inline override virtual
isValid returns non zero if object contains vailid data
Reimplemented from PHObject.
Reimplemented in TrkrHitv2, and TrkrHitv1.
Definition at line 37 of file TrkrHit.h.
View newest version in sPHENIX GitHub at line 37 of file TrkrHit.h
void TrkrHit::Reset () inline override virtual
Clear Event.
Reimplemented from PHObject.
Reimplemented in TrkrHitv2, and TrkrHitv1.
Definition at line 36 of file TrkrHit.h.
View newest version in sPHENIX GitHub at line 36 of file TrkrHit.h
virtual void TrkrHit::setAdc (const unsigned int) inline virtual
Reimplemented in TrkrHitv2, and TrkrHitv1.
Definition at line 44 of file TrkrHit.h.
View newest version in sPHENIX GitHub at line 44 of file TrkrHit.h
Referenced by PHG4MvtxHitReco::cluster_truthhits(), PHG4TpcDigitizer::DigitizeCylinderCells(), PHG4InttDigitizer::DigitizeLadderCells(), PHG4MvtxDigitizer::DigitizeMvtxLadderCells(), TpcPrototypeUnpacker::exportDSTHits(), InttCombinedRawDataDecoder::process_event(), InttRawDataDecoder::process_event(), PHG4MicromegasDigitizer::process_event(), TpcCombinedRawDataUnpacker::process_event(), PHG4TpcPadBaselineShift::process_event(), and MvtxHitPruner::process_event().
The documentation for this class was generated from the following file:
coresoftware/blob/master/offline/packages/trackbase/TrkrHit.h