Analysis Software: acts/blob/sPHENIX/Examples/Scripts/MaterialMapping/Mat_map_surface_plot.C File Reference
Mat_map_surface_plot.C File Reference
#include <TROOT.h>
#include "materialPlotHelper.cpp"
#include <fstream>
#include <iostream>
#include <sstream>
Functions
void plot (std::vector< TH2F * > Map, const sinfo &surface_info, const std::string &name)
Draw and save the histograms.
void Initialise_hist (std::vector< TH2F * > &surface_hist, const sinfo &surface_info)
Initialise the histograms for each surface.
void Fill (std::map< uint64_t, std::vector< TH2F * >> &surface_hist, std::map< uint64_t, sinfo > &surface_info, const std::string &input_file, const int &nbprocess)
Fill the histograms for each surfaces.
void Mat_map_surface_plot (std::string input_file="", int nbprocess=-1, std::string name="")
Function Documentation
void Fill (std::map< uint64_t, std::vector< TH2F * >> & surface_hist, std::map< uint64_t, sinfo > & surface_info, const std::string & input_file, const int & nbprocess)
Fill the histograms for each surfaces.
Definition at line 131 of file Mat_map_surface_plot.C.
View newest version in sPHENIX GitHub at line 131 of file Mat_map_surface_plot.C
References i, Initialise_hist(), Initialise_info(), j, Acts::Test::pos, tfile, and tree.
void Initialise_hist (std::vector< TH2F * > & surface_hist, const sinfo & surface_info)
Initialise the histograms for each surface.
Definition at line 85 of file Mat_map_surface_plot.C.
View newest version in sPHENIX GitHub at line 85 of file Mat_map_surface_plot.C
References sinfo::idname, sinfo::range_max, and sinfo::type.
void Mat_map_surface_plot (std::string input_file = "", int nbprocess = -1, std::string name = "")
Plot the material on each surface. nbprocess : number of parameter to be processed. name : name of the output directory.
Definition at line 232 of file Mat_map_surface_plot.C.
View newest version in sPHENIX GitHub at line 232 of file Mat_map_surface_plot.C
References Fill(), add_histos::hist, perf_headwind::input_file, perf_headwind::name, and plot().
void plot (std::vector< TH2F * > Map, const sinfo & surface_info, const std::string & name)
Draw and save the histograms.
Definition at line 19 of file Mat_map_surface_plot.C.
View newest version in sPHENIX GitHub at line 19 of file Mat_map_surface_plot.C
References sinfo::id, sinfo::idname, sinfo::name, sinfo::pos, writeMapConfig::surface, to_string(), and sinfo::type.