Analysis Software: detail Namespace Reference
detail Namespace Reference
Functions
template<typename Array >
size_t fillChargeMatrix (Array &arr, const ActsExamples::Cluster &cluster, size_t size0=7u, size_t size1=7u)
std::pair
< Acts::GeometryIdentifier,
std::string > parseMapKey (const std::string &mapkey)
std::map
< Acts::GeometryIdentifier,
ActsExamples::ScalingCalibrator::MapTuple > readMaps (const std::filesystem::path &path)
std::bitset< 3 > readMask (const std::filesystem::path &path)
Function Documentation
template<typename Array > size_t detail::fillChargeMatrix (Array & arr, const ActsExamples::Cluster & cluster, size_t size0 = 7u, size_t size1 = 7u)
Definition at line 19 of file NeuralCalibrator.cpp.
View newest version in sPHENIX GitHub at line 19 of file NeuralCalibrator.cpp
References ActsFatras::Channelizer::ChannelSegment::activation, arr, ActsFatras::Channelizer::ChannelSegment::bin, ActsExamples::Cluster::channels, i, and index.
std::pair<Acts::GeometryIdentifier, std::string> detail::parseMapKey (const std::string & mapkey)
Definition at line 50 of file ScalingCalibrator.cpp.
View newest version in sPHENIX GitHub at line 50 of file ScalingCalibrator.cpp
References Acts::GeometryIdentifier::setLayer(), Acts::GeometryIdentifier::setSensitive(), Acts::GeometryIdentifier::setVolume(), and str.
Referenced by readMaps().
std::map<Acts::GeometryIdentifier, ActsExamples::ScalingCalibrator::MapTuple> detail::readMaps (const std::filesystem::path & path)
Definition at line 74 of file ScalingCalibrator.cpp.
View newest version in sPHENIX GitHub at line 74 of file ScalingCalibrator.cpp
References assert, add_histos::hist, it, Acts::maps, and parseMapKey().
Referenced by ActsExamples::ScalingCalibrator::ScalingCalibrator().
std::bitset<3> detail::readMask (const std::filesystem::path & path)
Definition at line 110 of file ScalingCalibrator.cpp.
View newest version in sPHENIX GitHub at line 110 of file ScalingCalibrator.cpp