Analysis Software: SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::ParInfo Struct Reference
SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::ParInfo Struct Reference
#include <analysis/blob/master/AndersonAnalysisModules/ColdQcdCorrelatorAnalysis/SCorrelatorUtilities/src/GenTools.h>
Public Member Functions
void SetInfo (const HepMC::GenParticle *particle, const int event)
void Reset ()
ParInfo ()
~ParInfo ()
ParInfo (HepMC::GenParticle *particle, const int event)
Static Public Member Functions
static vector< string > GetListOfMembers ()
Public Attributes
int pid = numeric_limits<int>::max()
int status = numeric_limits<int>::max()
int barcode = numeric_limits<int>::max()
int embedID = numeric_limits<int>::max()
float charge = numeric_limits<float>::max()
double mass = numeric_limits<double>::max()
double eta = numeric_limits<double>::max()
double phi = numeric_limits<double>::max()
double ene = numeric_limits<double>::max()
double px = numeric_limits<double>::max()
double py = numeric_limits<double>::max()
double pz = numeric_limits<double>::max()
double pt = numeric_limits<double>::max()
double vx = numeric_limits<double>::max()
double vy = numeric_limits<double>::max()
double vz = numeric_limits<double>::max()
double vr = numeric_limits<double>::max()
Friends
bool operator< (const ParInfo &lhs, const ParInfo &rhs)
bool operator> (const ParInfo &lhs, const ParInfo &rhs)
bool operator<= (const ParInfo &lhs, const ParInfo &rhs)
bool operator>= (const ParInfo &lhs, const ParInfo &rhs)
Detailed Description
Definition at line 50 of file GenTools.h.
View newest version in sPHENIX GitHub at line 50 of file GenTools.h
Constructor & Destructor Documentation
SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::ParInfo::ParInfo () inline
Definition at line 175 of file GenTools.h.
View newest version in sPHENIX GitHub at line 175 of file GenTools.h
SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::ParInfo::~ParInfo () inline
Definition at line 176 of file GenTools.h.
View newest version in sPHENIX GitHub at line 176 of file GenTools.h
SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::ParInfo::ParInfo (HepMC::GenParticle * particle, const int event) inline
Definition at line 178 of file GenTools.h.
View newest version in sPHENIX GitHub at line 178 of file GenTools.h
Member Function Documentation
static vector<string> SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::ParInfo::GetListOfMembers () inline static
Definition at line 113 of file GenTools.h.
View newest version in sPHENIX GitHub at line 113 of file GenTools.h
void SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::ParInfo::Reset () inline
Definition at line 92 of file GenTools.h.
View newest version in sPHENIX GitHub at line 92 of file GenTools.h
References charge(), eta, mass, ActsTests::PropagationDatasets::phi, train_ambiguity_solver::pid, physmon_track_finding_ttbar::pt, utils::status, vx, vy, and vz.
void SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::ParInfo::SetInfo (const HepMC::GenParticle * particle, const int event) inline
Definition at line 71 of file GenTools.h.
View newest version in sPHENIX GitHub at line 71 of file GenTools.h
References charge(), eta, event, mass, momentum, ActsTests::PropagationDatasets::phi, train_ambiguity_solver::pid, position, physmon_track_finding_ttbar::pt, utils::status, vx, vy, and vz.
Referenced by SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::GetPartonInfo().
Friends And Related Function Documentation
bool operator< (const ParInfo & lhs, const ParInfo & rhs) friend
Definition at line 137 of file GenTools.h.
View newest version in sPHENIX GitHub at line 137 of file GenTools.h
bool operator<= (const ParInfo & lhs, const ParInfo & rhs) friend
Definition at line 171 of file GenTools.h.
View newest version in sPHENIX GitHub at line 171 of file GenTools.h
bool operator> (const ParInfo & lhs, const ParInfo & rhs) friend
Definition at line 154 of file GenTools.h.
View newest version in sPHENIX GitHub at line 154 of file GenTools.h
bool operator>= (const ParInfo & lhs, const ParInfo & rhs) friend
Definition at line 172 of file GenTools.h.
View newest version in sPHENIX GitHub at line 172 of file GenTools.h
Member Data Documentation
int SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::ParInfo::barcode = numeric_limits<int>::max()
Definition at line 55 of file GenTools.h.
View newest version in sPHENIX GitHub at line 55 of file GenTools.h
float SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::ParInfo::charge = numeric_limits<float>::max()
Definition at line 57 of file GenTools.h.
View newest version in sPHENIX GitHub at line 57 of file GenTools.h
int SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::ParInfo::embedID = numeric_limits<int>::max()
Definition at line 56 of file GenTools.h.
View newest version in sPHENIX GitHub at line 56 of file GenTools.h
double SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::ParInfo::ene = numeric_limits<double>::max()
Definition at line 61 of file GenTools.h.
View newest version in sPHENIX GitHub at line 61 of file GenTools.h
double SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::ParInfo::eta = numeric_limits<double>::max()
Definition at line 59 of file GenTools.h.
View newest version in sPHENIX GitHub at line 59 of file GenTools.h
double SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::ParInfo::mass = numeric_limits<double>::max()
Definition at line 58 of file GenTools.h.
View newest version in sPHENIX GitHub at line 58 of file GenTools.h
double SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::ParInfo::phi = numeric_limits<double>::max()
Definition at line 60 of file GenTools.h.
View newest version in sPHENIX GitHub at line 60 of file GenTools.h
int SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::ParInfo::pid = numeric_limits<int>::max()
Definition at line 53 of file GenTools.h.
View newest version in sPHENIX GitHub at line 53 of file GenTools.h
double SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::ParInfo::pt = numeric_limits<double>::max()
Definition at line 65 of file GenTools.h.
View newest version in sPHENIX GitHub at line 65 of file GenTools.h
double SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::ParInfo::px = numeric_limits<double>::max()
Definition at line 62 of file GenTools.h.
View newest version in sPHENIX GitHub at line 62 of file GenTools.h
double SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::ParInfo::py = numeric_limits<double>::max()
Definition at line 63 of file GenTools.h.
View newest version in sPHENIX GitHub at line 63 of file GenTools.h
double SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::ParInfo::pz = numeric_limits<double>::max()
Definition at line 64 of file GenTools.h.
View newest version in sPHENIX GitHub at line 64 of file GenTools.h
int SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::ParInfo::status = numeric_limits<int>::max()
Definition at line 54 of file GenTools.h.
View newest version in sPHENIX GitHub at line 54 of file GenTools.h
double SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::ParInfo::vr = numeric_limits<double>::max()
Definition at line 69 of file GenTools.h.
View newest version in sPHENIX GitHub at line 69 of file GenTools.h
double SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::ParInfo::vx = numeric_limits<double>::max()
Definition at line 66 of file GenTools.h.
View newest version in sPHENIX GitHub at line 66 of file GenTools.h
double SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::ParInfo::vy = numeric_limits<double>::max()
Definition at line 67 of file GenTools.h.
View newest version in sPHENIX GitHub at line 67 of file GenTools.h
double SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::ParInfo::vz = numeric_limits<double>::max()
Definition at line 68 of file GenTools.h.
View newest version in sPHENIX GitHub at line 68 of file GenTools.h
The documentation for this struct was generated from the following file:
analysis/blob/master/AndersonAnalysisModules/ColdQcdCorrelatorAnalysis/SCorrelatorUtilities/src/GenTools.h