Analysis Software: analysis/blob/master/JS-Jet/Calibrations/MC-Calibrations/numericInverse.C File Reference
numericInverse.C File Reference
#include "sPhenixStyle.h"
#include "sPhenixStyle.C"
Functions
string generateFit (int order, string function)
void numericInverse (int save=0, int isUESubtracted=1, int is10GeV=0)
Variables
const int nIso = 1
const int nIter = 6
const float isoParams [] = {0, 1, 1.5, 2, 2.5}
Function Documentation
string generateFit (int order, string function)
Definition at line 348 of file numericInverse.C.
View newest version in sPHENIX GitHub at line 348 of file numericInverse.C
Referenced by numericInverse().
void numericInverse (int save = 0, int isUESubtracted = 1, int is10GeV = 0)
Definition at line 11 of file numericInverse.C.
View newest version in sPHENIX GitHub at line 11 of file numericInverse.C
References AddEntry(), c2, cd(), Close(), Draw(), check_license::err(), fit(), generateFit(), GetNDF(), GetX(), GetXaxis(), GetYaxis(), i, isoParams, j, leg, n, nIso, nIter, Acts::IntegrationTest::R, save(), SetBorderSize(), SetFillStyle(), SetLineColor(), SetLineStyle(), SetMarkerColor(), SetName(), SetPoint(), SetPointError(), SetsPhenixStyle(), SetTitle(), Write(), ambiguity_solver_full_chain::x, and y.
Variable Documentation
const float isoParams[] = {0, 1, 1.5, 2, 2.5}
Definition at line 7 of file numericInverse.C.
View newest version in sPHENIX GitHub at line 7 of file numericInverse.C
Referenced by numericInverse().
const int nIso = 1
Definition at line 4 of file numericInverse.C.
View newest version in sPHENIX GitHub at line 4 of file numericInverse.C
Referenced by numericInverse().
const int nIter = 6
Definition at line 5 of file numericInverse.C.
View newest version in sPHENIX GitHub at line 5 of file numericInverse.C
Referenced by Acts::FullBilloirVertexFitter< input_track_t, linearizer_t >::fit(), Acts::AdaptiveMultiVertexFitter< input_track_t, linearizer_t >::fitImpl(), main(), numericInverse(), and Acts::ImpactPointEstimator< input_track_t, propagator_t, propagator_options_t >::performNewtonOptimization().