Analysis Software: Acts::ParticleHypothesis Class Reference
Acts::ParticleHypothesis Class Reference
#include <acts/blob/sPHENIX/Core/include/Acts/EventData/ParticleHypothesis.hpp>
Public Member Functions
constexpr ParticleHypothesis (PdgParticle absPdg, float mass, AnyCharge chargeType)
ParticleHypothesis (PdgParticle absPdg)
template<typename other_charge_t >
constexpr ParticleHypothesis (const GenericParticleHypothesis< other_charge_t > &other)
Public Member Functions inherited from Acts::GenericParticleHypothesis< AnyCharge >
constexpr GenericParticleHypothesis (PdgParticle absPdg, float mass, ChargeType chargeType)
Static Public Member Functions
static ParticleHypothesis muon ()
static ParticleHypothesis pion ()
static ParticleHypothesis electron ()
static ParticleHypothesis photon ()
static ParticleHypothesis pion0 ()
static ParticleHypothesis pionLike (float absQ)
static ParticleHypothesis geantino ()
static ParticleHypothesis chargedGeantino ()
static ParticleHypothesis chargedGeantino (float absQ)
Additional Inherited Members
Public Types inherited from Acts::GenericParticleHypothesis< AnyCharge >
using ChargeType = charge_t
Public Attributes inherited from Acts::GenericParticleHypothesis< AnyCharge >
m_mass
float m_mass
m_chargeType
ChargeType m_chargeType
Detailed Description
Specialized particle hypothesis for any kind of charged particles.
Note
This serves as a factory for common particles with any kind of charge.
Definition at line 124 of file ParticleHypothesis.hpp.
View newest version in sPHENIX GitHub at line 124 of file ParticleHypothesis.hpp
Constructor & Destructor Documentation
constexpr Acts::ParticleHypothesis::ParticleHypothesis (PdgParticle absPdg, float mass, AnyCharge chargeType) inline
Definition at line 126 of file ParticleHypothesis.hpp.
View newest version in sPHENIX GitHub at line 126 of file ParticleHypothesis.hpp
Referenced by chargedGeantino(), and pionLike().
Acts::ParticleHypothesis::ParticleHypothesis (PdgParticle absPdg) inline
Definition at line 129 of file ParticleHypothesis.hpp.
View newest version in sPHENIX GitHub at line 129 of file ParticleHypothesis.hpp
template<typename other_charge_t > constexpr Acts::ParticleHypothesis::ParticleHypothesis (const GenericParticleHypothesis< other_charge_t > & other) inline
Definition at line 132 of file ParticleHypothesis.hpp.
View newest version in sPHENIX GitHub at line 132 of file ParticleHypothesis.hpp
Member Function Documentation
static ParticleHypothesis Acts::ParticleHypothesis::chargedGeantino () inline static
Definition at line 160 of file ParticleHypothesis.hpp.
View newest version in sPHENIX GitHub at line 160 of file ParticleHypothesis.hpp
References Acts::UnitConstants::e.
Referenced by Acts::Python::addEventData().
static ParticleHypothesis Acts::ParticleHypothesis::chargedGeantino (float absQ) inline static
Definition at line 163 of file ParticleHypothesis.hpp.
View newest version in sPHENIX GitHub at line 163 of file ParticleHypothesis.hpp
References Acts::eInvalid, and ParticleHypothesis().
static ParticleHypothesis Acts::ParticleHypothesis::electron () inline static
Definition at line 142 of file ParticleHypothesis.hpp.
View newest version in sPHENIX GitHub at line 142 of file ParticleHypothesis.hpp
References electron.
Referenced by Acts::Python::addEventData(), PHActsGSF::makeSeed(), and PHActsGSF::updateTrack().
static ParticleHypothesis Acts::ParticleHypothesis::geantino () inline static
Definition at line 157 of file ParticleHypothesis.hpp.
View newest version in sPHENIX GitHub at line 157 of file ParticleHypothesis.hpp
Referenced by Acts::Python::addEventData().
static ParticleHypothesis Acts::ParticleHypothesis::muon () inline static
Definition at line 136 of file ParticleHypothesis.hpp.
View newest version in sPHENIX GitHub at line 136 of file ParticleHypothesis.hpp
Referenced by Acts::Python::addEventData(), and PHCosmicsTrkFitter::loopTracks().
static ParticleHypothesis Acts::ParticleHypothesis::photon () inline static
Definition at line 146 of file ParticleHypothesis.hpp.
View newest version in sPHENIX GitHub at line 146 of file ParticleHypothesis.hpp
static ParticleHypothesis Acts::ParticleHypothesis::pion () inline static
Definition at line 139 of file ParticleHypothesis.hpp.
View newest version in sPHENIX GitHub at line 139 of file ParticleHypothesis.hpp
References pion.
Referenced by Acts::Python::addEventData(), Acts::VectorTrackContainer::addTrack_impl(), Acts::Test::BOOST_AUTO_TEST_CASE(), BOOST_AUTO_TEST_CASE(), BOOST_DATA_TEST_CASE(), Acts::Test::BOOST_DATA_TEST_CASE(), Acts::EventDataView3D::drawMultiTrajectory(), ActsTransformations::fillSvtxTrackStates(), PHActsTrkFitter::loopTracks(), main(), Acts::Test::makeParameters(), ActsPropagator::makeTrackParams(), PHTpcResiduals::makeTrackParams(), pionLike(), ActsExamples::CsvTrackParameterReader::read(), ActsExamples::RootTrajectorySummaryReader::read(), ActsExamples::RootAthenaNTupleReader::read(), Acts::Test::readTracksAndVertexCSV(), Acts::Test::runTest(), FitterTester::test_ZeroFieldWithSurfaceBackward(), Acts::EventDataView3DTest::testBoundTrackParameters(), Acts::EventDataView3DTest::testMultiTrajectory(), Acts::Test::TestTrackState::TestTrackState(), and xPositionsOfPassedSurfaces().
static ParticleHypothesis Acts::ParticleHypothesis::pion0 () inline static
Definition at line 149 of file ParticleHypothesis.hpp.
View newest version in sPHENIX GitHub at line 149 of file ParticleHypothesis.hpp
Referenced by BOOST_AUTO_TEST_CASE(), Acts::Test::BOOST_AUTO_TEST_CASE(), BOOST_DATA_TEST_CASE(), and makeParametersCurvilinearNeutral().
static ParticleHypothesis Acts::ParticleHypothesis::pionLike (float absQ) inline static
Definition at line 153 of file ParticleHypothesis.hpp.
View newest version in sPHENIX GitHub at line 153 of file ParticleHypothesis.hpp
References mass, ParticleHypothesis(), and pion().
Referenced by BOOST_AUTO_TEST_CASE(), BOOST_DATA_TEST_CASE(), Acts::Test::makeParameters(), makeParametersCurvilinear(), and makeParametersCurvilinearWithCovariance().
The documentation for this class was generated from the following file:
acts/blob/sPHENIX/Core/include/Acts/EventData/ParticleHypothesis.hpp