Analysis Software: testing::internal::MockSpec< F > Class Template Reference
testing::internal::MockSpec< F > Class Template Reference
#include <JETSCAPE/blob/main/external_packages/googletest/googlemock/include/gmock/gmock-spec-builders.h>
Public Types
typedef internal::Function< F >
::ArgumentTuple ArgumentTuple
typedef internal::Function< F >
::ArgumentMatcherTuple ArgumentMatcherTuple
Public Member Functions
MockSpec (internal::FunctionMockerBase< F > *function_mocker)
internal::OnCallSpec< F > & InternalDefaultActionSetAt (const char *file, int line, const char *obj, const char *call)
internal::TypedExpectation< F > & InternalExpectedAt (const char *file, int line, const char *obj, const char *call)
Private Member Functions
void SetMatchers (const ArgumentMatcherTuple &matchers)
GTEST_DISALLOW_ASSIGN_ (MockSpec)
Private Attributes
internal::FunctionMockerBase
< F > *const function_mocker_
ArgumentMatcherTuple matchers_
Friends
template<typename Function >
class internal::FunctionMocker
Detailed Description
template<typename F>
class testing::internal::MockSpec< F >
Definition at line 1246 of file gmock-spec-builders.h.
View newest version in sPHENIX GitHub at line 1246 of file gmock-spec-builders.h
Member Typedef Documentation
template<typename F> typedef internal::Function<F>::ArgumentMatcherTuple testing::internal::MockSpec< F >::ArgumentMatcherTuple
Definition at line 1250 of file gmock-spec-builders.h.
View newest version in sPHENIX GitHub at line 1250 of file gmock-spec-builders.h
template<typename F> typedef internal::Function<F>::ArgumentTuple testing::internal::MockSpec< F >::ArgumentTuple
Definition at line 1248 of file gmock-spec-builders.h.
View newest version in sPHENIX GitHub at line 1248 of file gmock-spec-builders.h
Constructor & Destructor Documentation
template<typename F> testing::internal::MockSpec< F >::MockSpec (internal::FunctionMockerBase< F > * function_mocker) inline explicit
Definition at line 1254 of file gmock-spec-builders.h.
View newest version in sPHENIX GitHub at line 1254 of file gmock-spec-builders.h
Member Function Documentation
template<typename F> testing::internal::MockSpec< F >::GTEST_DISALLOW_ASSIGN_ (MockSpec< F >) private
template<typename F> internal::OnCallSpec<F>& testing::internal::MockSpec< F >::InternalDefaultActionSetAt (const char * file, int line, const char * obj, const char * call) inline
Definition at line 1259 of file gmock-spec-builders.h.
View newest version in sPHENIX GitHub at line 1259 of file gmock-spec-builders.h
template<typename F> internal::TypedExpectation<F>& testing::internal::MockSpec< F >::InternalExpectedAt (const char * file, int line, const char * obj, const char * call) inline
Definition at line 1268 of file gmock-spec-builders.h.
View newest version in sPHENIX GitHub at line 1268 of file gmock-spec-builders.h
template<typename F> void testing::internal::MockSpec< F >::SetMatchers (const ArgumentMatcherTuple & matchers) inline private
Definition at line 1280 of file gmock-spec-builders.h.
View newest version in sPHENIX GitHub at line 1280 of file gmock-spec-builders.h
Referenced by testing::internal::FunctionMocker< R(A1, A2, A3)>::With(), testing::internal::FunctionMocker< R(A1, A2, A3, A4)>::With(), testing::internal::FunctionMocker< R(A1, A2, A3, A4, A5)>::With(), testing::internal::FunctionMocker< R(A1, A2, A3, A4, A5, A6)>::With(), testing::internal::FunctionMocker< R(A1, A2, A3, A4, A5, A6, A7)>::With(), testing::internal::FunctionMocker< R(A1, A2, A3, A4, A5, A6, A7, A8)>::With(), testing::internal::FunctionMocker< R(A1, A2, A3, A4, A5, A6, A7, A8, A9)>::With(), and testing::internal::FunctionMocker< R(A1, A2, A3, A4, A5, A6, A7, A8, A9, A10)>::With().
Friends And Related Function Documentation
template<typename F> template<typename Function > friend class internal::FunctionMocker friend
Definition at line 1278 of file gmock-spec-builders.h.
View newest version in sPHENIX GitHub at line 1278 of file gmock-spec-builders.h
Member Data Documentation
template<typename F> internal::FunctionMockerBase<F>* const testing::internal::MockSpec< F >::function_mocker_ private
Definition at line 1285 of file gmock-spec-builders.h.
View newest version in sPHENIX GitHub at line 1285 of file gmock-spec-builders.h
template<typename F> ArgumentMatcherTuple testing::internal::MockSpec< F >::matchers_ private
Definition at line 1287 of file gmock-spec-builders.h.
View newest version in sPHENIX GitHub at line 1287 of file gmock-spec-builders.h
The documentation for this class was generated from the following file:
JETSCAPE/blob/main/external_packages/googletest/googlemock/include/gmock/gmock-spec-builders.h