Analysis Software: HybridHadronization Class Reference
HybridHadronization Class Reference
#include <JETSCAPE/blob/main/src/hadronization/HybridHadronization.h>
Classes
class hadron_collection
class HHhadron
class HHparton
class parton_collection
Public Member Functions
HybridHadronization ()
virtual ~HybridHadronization ()
void Init ()
void DoHadronization (vector< vector< shared_ptr< Parton >>> &shower, vector< shared_ptr< Hadron >> &hOut, vector< shared_ptr< Parton >> &pOut)
void WriteTask (weak_ptr< JetScapeWriter > w)
Public Member Functions inherited from Jetscape::HadronizationModule< HybridHadronization >
virtual shared_ptr< Hadronization > Clone () const override
Public Member Functions inherited from Jetscape::Hadronization
Hadronization ()
virtual ~Hadronization ()
virtual void Exec ()
virtual void Clear ()
void GetHadrons (vector< shared_ptr< Hadron >> &signal)
vector< shared_ptr< Hadron > > GetHadrons ()
vector< shared_ptr< Parton > > GetOutPartons ()
void AddInPartons (vector< vector< shared_ptr< Parton >>> ip)
void SetTransformPartonsConnected (bool m_TransformPartonsConnected)
const bool GetTransformPartonsConnected ()
void SetGetHydroHyperSurfaceConnected (bool m_GetHydroHyperSurfaceConnected)
const bool GetGetHydroHyperSurfaceConnected ()
void SetGetHydroCellSignalConnected (bool m_GetHydroCellSignalConnected)
const bool GetGetHydroCellSignalConnected ()
void AddInHadrons (vector< shared_ptr< Hadron >> ih)
void DeleteHadrons ()
void DeleteRealHadrons ()
Public Member Functions inherited from Jetscape::JetScapeModuleBase
JetScapeModuleBase ()
JetScapeModuleBase (string m_name)
virtual ~JetScapeModuleBase ()
void SetXMLMainFileName (string m_name)
string GetXMLMainFileName ()
void SetXMLUserFileName (string m_name)
string GetXMLUserFileName ()
shared_ptr< std::mt19937 > GetMt19937Generator ()
tinyxml2::XMLElement * GetXMLElement (std::initializer_list< const char * > path, bool isRequired=true)
std::string GetXMLElementText (std::initializer_list< const char * > path, bool isRequired=true)
int GetXMLElementInt (std::initializer_list< const char * > path, bool isRequired=true)
double GetXMLElementDouble (std::initializer_list< const char * > path, bool isRequired=true)
Public Member Functions inherited from Jetscape::JetScapeTask
JetScapeTask ()
virtual ~JetScapeTask ()
virtual void Finish ()
virtual void ExecuteTasks ()
virtual void ExecuteTask ()
virtual void InitTask ()
virtual void InitTasks ()
virtual void ClearTasks ()
virtual void ClearTask ()
virtual void FinishTask ()
virtual void FinishTasks ()
virtual void WriteTasks (weak_ptr< JetScapeWriter > w)
virtual void CollectHeader (weak_ptr< JetScapeWriter > w)
virtual void CollectHeaders (weak_ptr< JetScapeWriter > w)
virtual void Add (shared_ptr< JetScapeTask > m_tasks)
virtual const int GetMyTaskNumber () const
const vector< shared_ptr
< JetScapeTask > > GetTaskList () const
shared_ptr< JetScapeTask > GetTaskAt (int i)
void EraseTaskLast ()
void EraseTaskAt (int i)
void ResizeTaskList (int i)
void ClearTaskList ()
int GetNumberOfTasks ()
const bool GetActive () const
void SetActive (bool m_active_exec)
void SetId (string m_id)
const string GetId () const
const shared_ptr
< JetScapeModuleMutex > GetMutex () const
void SetMutex (shared_ptr< JetScapeModuleMutex > m_mutex)
Public Member Functions inherited from sigslot::has_slots< sigslot::multi_threaded_local >
has_slots ()
has_slots (const has_slots &hs)
void signal_connect (_signal_base< sigslot::multi_threaded_local > *sender)
void signal_disconnect (_signal_base< sigslot::multi_threaded_local > *sender)
virtual ~has_slots ()
void disconnect_all ()
Static Protected Attributes
static Pythia8::Pythia pythia
Private Member Functions
double SigM2_calc (double R2chg, double qm1, double qm2, double qq1, double qq2)
double SigBR2_calc (double R2chg, double qm1, double qm2, double qm3, double qq1, double qq2, double qq3)
double SigBL2_calc (double SigBR2, double qm1, double qm2, double qm3)
double ran ()
void stringform ()
void recomb ()
void set_baryon_id (parton_collection &qrks, HHhadron &had)
void set_meson_id (parton_collection &qrks, HHhadron &had, int l, int k)
void gluon_decay (HHparton &glu, parton_collection &qrks)
int findthermalsibling (int ithm, parton_collection &therm)
int findcloserepl (HHparton ptn, int iptn, bool lbt, bool thm, parton_collection &sh_lbt, parton_collection &therm)
void findcloserepl_glu (HHparton ptn, int iptn, bool lbt, bool thm, parton_collection &sh_lbt, parton_collection &therm, int sel_out[])
void stringprep (parton_collection &SP_remnants, parton_collection &SP_prepremn, bool cutstr)
bool invoke_py ()
void set_spacetime_for_pythia_hadrons (Pythia8::Event &event, int &size_input, std::vector< int > &eve_to_had, int pythia_attempt, bool find_positions, bool is_recohadron, bool recohadron_shsh)
void bring_hadrons_to_mass_shell (hadron_collection &HH_hadrons)
void set_initial_parton_masses (parton_collection &HH_showerptns)
void convert_color_tags_to_int_type (vector< vector< shared_ptr< Parton >>> &shower)
void scale_kinematics_negative_hadrons (hadron_collection &HH_hadrons, double shower_energy, double positive_hadrons_energy)
Static Private Member Functions
static FourVector HHboost (FourVector B, FourVector vec_in)
static double dif2 (FourVector vec1, FourVector vec2)
Private Attributes
double maxM_level
double maxB_level
double gmax
double xmq
double xms
double xmc
double xmb
double hbarc
double dist2cut
double sh_recofactor
double th_recofactor
double p_fake
double had_prop
double part_prop
double delta_t
double hydro_Tc
double eta_max_boost_inv
int number_p_fake
double SigNucR2
double SigNucL2
double SigOmgR2
double SigOmgL2
double SigXiR2
double SigXiL2
double SigSigR2
double SigSigL2
double SigOcccR2
double SigOcccL2
double SigOccR2
double SigOccL2
double SigXiccR2
double SigXiccL2
double SigOcR2
double SigOcL2
double SigXicR2
double SigXicL2
double SigSigcR2
double SigSigcL2
double SigObbbR2
double SigObbbL2
double SigObbcR2
double SigObbcL2
double SigObbR2
double SigObbL2
double SigXibbR2
double SigXibbL2
double SigObccR2
double SigObccL2
double SigObcR2
double SigObcL2
double SigXibcR2
double SigXibcL2
double SigObR2
double SigObL2
double SigXibR2
double SigXibL2
double SigSigbR2
double SigSigbL2
double SigPi2
double SigPhi2
double SigK2
double SigJpi2
double SigDs2
double SigD2
double SigUps2
double SigBc2
double SigB2
bool inbrick
bool inhydro
int nreusehydro
double brickL
double brickT
const double pi = 3.1415926535897932384626433832795
int attempts_max
unsigned int rand_seed
int reco_hadrons_pythia
int additional_pythia_particles
bool goldstonereco
bool torder_reco
bool afterburner_frag_hadrons = false
std::string pythia_decays
vector< vector< vector< int > > > Tempjunctions
vector< vector< int > > JunctionInfo
vector< int > IdColInfo1
vector< int > IdColInfo2
vector< int > IdColInfo3
vector< int > IdColInfo4
std::mt19937_64 eng
parton_collection HH_shower
parton_collection HH_thermal
parton_collection HH_recomb_extrapartons
parton_collection HH_showerptns
parton_collection HH_remnants
parton_collection HH_pyremn
hadron_collection HH_hadrons
hadron_collection HH_pythia_hadrons
Static Private Attributes
static RegisterJetScapeModule
< HybridHadronization > reg
Additional Inherited Members
Static Public Member Functions inherited from Jetscape::JetScapeModuleBase
static int GetCurrentEvent ()
static void IncrementCurrentEvent ()
Public Attributes inherited from Jetscape::Hadronization
sigslot::signal3< vector
< vector< shared_ptr< Parton >
> > &, vector< shared_ptr
< Hadron > > &, vector
< shared_ptr< Parton >
> &, multi_threaded_local > TransformPartons
sigslot::signal2
< Jetscape::real, std::vector
< SurfaceCellInfo >
&, multi_threaded_local > GetHydroHyperSurface
sigslot::signal5< double,
double, double, double,
std::unique_ptr< FluidCellInfo >
&, multi_threaded_local > GetHydroCellSignal
Detailed Description
Definition at line 29 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 29 of file HybridHadronization.h
Constructor & Destructor Documentation
HybridHadronization::HybridHadronization ()
Definition at line 56 of file HybridHadronization.cc.
View newest version in sPHENIX GitHub at line 56 of file HybridHadronization.cc
References SetId(), and VERBOSE.
HybridHadronization::~HybridHadronization () virtual
Definition at line 61 of file HybridHadronization.cc.
View newest version in sPHENIX GitHub at line 61 of file HybridHadronization.cc
References VERBOSE.
Member Function Documentation
void HybridHadronization::bring_hadrons_to_mass_shell (hadron_collection & HH_hadrons) private
Definition at line 6951 of file HybridHadronization.cc.
View newest version in sPHENIX GitHub at line 6951 of file HybridHadronization.cc
References col, Acts::UnitConstants::e, Acts::UnitConstants::m2, HybridHadronization::hadron_collection::num(), Jetscape::FourVector::Set(), Jetscape::FourVector::t(), Jetscape::FourVector::x(), ambiguity_solver_full_chain::x, y, Jetscape::FourVector::y(), Jetscape::FourVector::z(), and physmon_track_finding_ttbar::z.
void HybridHadronization::convert_color_tags_to_int_type (vector< vector< shared_ptr< Parton >>> & shower) private
Definition at line 915 of file HybridHadronization.cc.
View newest version in sPHENIX GitHub at line 915 of file HybridHadronization.cc
References distance(), and Acts::Experimental::detail::BlueprintHelper::sort().
static double HybridHadronization::dif2 (FourVector vec1, FourVector vec2) inline static private
Definition at line 112 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 112 of file HybridHadronization.h
References Jetscape::FourVector::x(), Jetscape::FourVector::y(), and Jetscape::FourVector::z().
void HybridHadronization::DoHadronization (vector< vector< shared_ptr< Parton >>> & shower, vector< shared_ptr< Hadron >> & hOut, vector< shared_ptr< Parton >> & pOut) virtual
Reimplemented from Jetscape::Hadronization.
Definition at line 455 of file HybridHadronization.cc.
View newest version in sPHENIX GitHub at line 455 of file HybridHadronization.cc
References HybridHadronization::HHparton::acol(), HybridHadronization::parton_collection::add(), ThermalPartonSampler::brick_flow(), ThermalPartonSampler::brick_length_width(), ThermalPartonSampler::brick_Tc(), HybridHadronization::parton_collection::clear(), HybridHadronization::HHparton::col(), double(), HybridHadronization::HHparton::e(), eta, Jetscape::JetScapeSignalManager::GetHydroPointer(), i, HybridHadronization::HHparton::id(), HybridHadronization::HHhadron::id(), Jetscape::JetScapeSignalManager::Instance(), Jetscape::EvolutionHistory::is_boost_invariant(), Jetscape::EvolutionHistory::is_Cartesian(), HybridHadronization::HHparton::is_shower(), HybridHadronization::HHparton::is_thermal(), JSDEBUG, JSINFO, JSWARN, mass, HybridHadronization::HHparton::mass(), HybridHadronization::HHhadron::mass(), ThermalPartonSampler::nTot(), HybridHadronization::parton_collection::num(), HybridHadronization::HHparton::orig(), HybridHadronization::HHhadron::orig(), merge_hashes::p, HybridHadronization::HHhadron::P(), P(), Acts::Test::pos, HybridHadronization::HHhadron::pos(), HybridHadronization::HHparton::pos_str(), HybridHadronization::HHparton::px(), HybridHadronization::HHparton::py(), HybridHadronization::HHparton::pz(), ThermalPartonSampler::sample_2p1d(), ThermalPartonSampler::sample_3p1d(), ThermalPartonSampler::samplebrick(), ThermalPartonSampler::set_hypersurface(), writeMapConfig::surface, tau, Jetscape::FluidCellInfo::temperature, ThermalPartonSampler::th_e(), ThermalPartonSampler::th_nL(), ThermalPartonSampler::th_nS(), ThermalPartonSampler::th_pid(), ThermalPartonSampler::th_px(), ThermalPartonSampler::th_py(), ThermalPartonSampler::th_pz(), ThermalPartonSampler::th_t(), ThermalPartonSampler::th_x(), ThermalPartonSampler::th_y(), ThermalPartonSampler::th_z(), vx, vy, vz, HybridHadronization::HHparton::x(), ambiguity_solver_full_chain::x, HybridHadronization::HHparton::x_t(), y, HybridHadronization::HHparton::y(), physmon_track_finding_ttbar::z, and HybridHadronization::HHparton::z().
int HybridHadronization::findcloserepl (HHparton ptn, int iptn, bool lbt, bool thm, parton_collection & sh_lbt, parton_collection & therm) private
Definition at line 3980 of file HybridHadronization.cc.
View newest version in sPHENIX GitHub at line 3980 of file HybridHadronization.cc
References col, i, HybridHadronization::HHparton::id(), HybridHadronization::parton_collection::num(), HybridHadronization::HHparton::posDif2(), HybridHadronization::HHparton::sibling(), and HybridHadronization::HHparton::x_t().
void HybridHadronization::findcloserepl_glu (HHparton ptn, int iptn, bool lbt, bool thm, parton_collection & sh_lbt, parton_collection & therm, int sel_out[]) private
Definition at line 4019 of file HybridHadronization.cc.
View newest version in sPHENIX GitHub at line 4019 of file HybridHadronization.cc
References col, i, HybridHadronization::HHparton::id(), HybridHadronization::HHparton::is_thermal(), HybridHadronization::parton_collection::num(), HybridHadronization::HHparton::posDif2(), and HybridHadronization::HHparton::x_t().
int HybridHadronization::findthermalsibling (int ithm, parton_collection & therm) private
Definition at line 3968 of file HybridHadronization.cc.
View newest version in sPHENIX GitHub at line 3968 of file HybridHadronization.cc
References i, and HybridHadronization::parton_collection::num().
void HybridHadronization::gluon_decay (HHparton & glu, parton_collection & qrks) private
Definition at line 3914 of file HybridHadronization.cc.
View newest version in sPHENIX GitHub at line 3914 of file HybridHadronization.cc
References HybridHadronization::HHparton::acol(), HybridHadronization::parton_collection::add(), HybridHadronization::HHparton::col(), HybridHadronization::HHparton::id(), HybridHadronization::HHparton::mass(), HybridHadronization::HHparton::P(), ActsTests::PropagationDatasets::phi, Jetscape::pi, HybridHadronization::HHparton::pos(), HybridHadronization::HHparton::px(), HybridHadronization::HHparton::py(), HybridHadronization::HHparton::pz(), ran(), Jetscape::FourVector::Set(), Jetscape::FourVector::t(), ActsTests::PropagationDatasets::theta, Jetscape::FourVector::x(), HybridHadronization::HHparton::x(), HybridHadronization::HHparton::x_t(), Jetscape::FourVector::y(), HybridHadronization::HHparton::y(), Jetscape::FourVector::z(), and HybridHadronization::HHparton::z().
static FourVector HybridHadronization::HHboost (FourVector B, FourVector vec_in) inline static private
Definition at line 76 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 76 of file HybridHadronization.h
References Jetscape::FourVector::Set(), Jetscape::FourVector::t(), Jetscape::FourVector::x(), Jetscape::FourVector::y(), and Jetscape::FourVector::z().
void HybridHadronization::Init () virtual
A virtual function for a default initialization of a JetScapeModuleBase. It also checks whether a XML file is loaded or not.
Reimplemented from Jetscape::Hadronization.
Definition at line 79 of file HybridHadronization.cc.
View newest version in sPHENIX GitHub at line 79 of file HybridHadronization.cc
References parse_cmake_options::begin, fixGDML::element, end, tinyxml2::XMLNode::FirstChildElement(), tinyxml2::XMLElement::GetText(), Jetscape::JetScapeXML::GetXMLRootUser(), gmax, hbarc, Jetscape::JetScapeXML::Instance(), JSDEBUG, JSINFO, JSWARN, test_fpe::lines, tinyxml2::XMLElement::Name(), tinyxml2::XMLNode::NextSiblingElement(), tinyxml2::XMLElement::QueryUnsignedText(), rd, check_smearing_config::ref, physmon_simulation::s, to_string(), and VERBOSE.
bool HybridHadronization::invoke_py () private
Definition at line 6239 of file HybridHadronization.cc.
View newest version in sPHENIX GitHub at line 6239 of file HybridHadronization.cc
References col, Acts::UnitConstants::e, event, i, mass, ambiguity_solver_full_chain::x, y, and physmon_track_finding_ttbar::z.
double HybridHadronization::ran () private
Definition at line 51 of file HybridHadronization.cc.
View newest version in sPHENIX GitHub at line 51 of file HybridHadronization.cc
void HybridHadronization::recomb () private
Definition at line 1148 of file HybridHadronization.cc.
View newest version in sPHENIX GitHub at line 1148 of file HybridHadronization.cc
References HybridHadronization::HHparton::acol(), HybridHadronization::parton_collection::add(), HybridHadronization::HHhadron::add_col(), HybridHadronization::HHhadron::add_par(), parse_cmake_options::begin, HybridHadronization::parton_collection::clear(), col, HybridHadronization::HHparton::col(), distance(), double(), HybridHadronization::HHparton::e(), Acts::UnitConstants::e, fixGDML::element, end, fid, hbarc, i, HybridHadronization::HHparton::id(), HybridHadronization::HHhadron::is_excited(), HybridHadronization::HHparton::is_fakeparton(), HybridHadronization::HHhadron::is_recohad(), HybridHadronization::HHparton::is_remnant(), HybridHadronization::HHhadron::is_shsh(), HybridHadronization::HHhadron::is_shth(), j, JSWARN, k, perf_headwind::limit, loc, mass, HybridHadronization::HHparton::mass(), HybridHadronization::HHhadron::mass(), HybridHadronization::parton_collection::num(), HybridHadronization::HHparton::orig(), HybridHadronization::HHhadron::P(), HybridHadronization::HHhadron::parents, HybridHadronization::parton_collection::partons, HybridHadronization::HHhadron::pos(), HybridHadronization::HHparton::px(), HybridHadronization::HHparton::py(), HybridHadronization::HHparton::pz(), ran(), physmon_simulation::s, Jetscape::FourVector::Set(), utils::status, t, Jetscape::FourVector::t(), physmon_ckf_tracking::u, Jetscape::FourVector::x(), ambiguity_solver_full_chain::x, y, Jetscape::FourVector::y(), Jetscape::FourVector::z(), and physmon_track_finding_ttbar::z.
void HybridHadronization::scale_kinematics_negative_hadrons (hadron_collection & HH_hadrons, double shower_energy, double positive_hadrons_energy) private
Definition at line 885 of file HybridHadronization.cc.
View newest version in sPHENIX GitHub at line 885 of file HybridHadronization.cc
References i, JSDEBUG, mass, and HybridHadronization::hadron_collection::num().
void HybridHadronization::set_baryon_id (parton_collection & qrks, HHhadron & had) private
Definition at line 3764 of file HybridHadronization.cc.
View newest version in sPHENIX GitHub at line 3764 of file HybridHadronization.cc
References KFPMath::a, KFPMath::b, HybridHadronization::HHhadron::id(), ran(), and Acts::Experimental::detail::BlueprintHelper::sort().
void HybridHadronization::set_initial_parton_masses (parton_collection & HH_showerptns) private
Definition at line 7118 of file HybridHadronization.cc.
View newest version in sPHENIX GitHub at line 7118 of file HybridHadronization.cc
References col, HybridHadronization::HHparton::e(), Acts::UnitConstants::e, HybridHadronization::HHparton::id(), Acts::UnitConstants::m2, mass, HybridHadronization::HHparton::mass(), HybridHadronization::parton_collection::num(), parton(), HybridHadronization::HHparton::px(), HybridHadronization::HHparton::py(), HybridHadronization::HHparton::pz(), Jetscape::FourVector::Set(), Jetscape::FourVector::t(), Jetscape::FourVector::x(), ambiguity_solver_full_chain::x, y, Jetscape::FourVector::y(), Jetscape::FourVector::z(), and physmon_track_finding_ttbar::z.
void HybridHadronization::set_meson_id (parton_collection & qrks, HHhadron & had, int l, int k) private
Definition at line 3819 of file HybridHadronization.cc.
View newest version in sPHENIX GitHub at line 3819 of file HybridHadronization.cc
References HybridHadronization::HHhadron::id(), ran(), and swap().
void HybridHadronization::set_spacetime_for_pythia_hadrons (Pythia8::Event & event, int & size_input, std::vector< int > & eve_to_had, int pythia_attempt, bool find_positions, bool is_recohadron, bool recohadron_shsh) private
Definition at line 6407 of file HybridHadronization.cc.
View newest version in sPHENIX GitHub at line 6407 of file HybridHadronization.cc
References HybridHadronization::HHhadron::add_par(), col, distance(), double(), Acts::UnitConstants::e, HybridHadronization::HHhadron::e(), HybridHadronization::HHhadron::id(), HybridHadronization::HHhadron::is_final(), HybridHadronization::HHhadron::is_recohad(), HybridHadronization::HHhadron::is_shsh(), HybridHadronization::HHhadron::is_shth(), HybridHadronization::HHhadron::is_strhad(), JSWARN, Acts::IntegrationTest::L, Acts::UnitConstants::m, HybridHadronization::HHhadron::mass(), HybridHadronization::HHhadron::parh(), HybridHadronization::HHhadron::px(), HybridHadronization::HHhadron::py(), HybridHadronization::HHhadron::pz(), Acts::Experimental::detail::BlueprintHelper::sort(), utils::status, VERBOSE, ambiguity_solver_full_chain::x, HybridHadronization::HHhadron::x(), HybridHadronization::HHhadron::x_t(), y, HybridHadronization::HHhadron::y(), physmon_track_finding_ttbar::z, and HybridHadronization::HHhadron::z().
double HybridHadronization::SigBL2_calc (double SigBR2, double qm1, double qm2, double qm3) private
Definition at line 75 of file HybridHadronization.cc.
View newest version in sPHENIX GitHub at line 75 of file HybridHadronization.cc
double HybridHadronization::SigBR2_calc (double R2chg, double qm1, double qm2, double qm3, double qq1, double qq2, double qq3) private
Definition at line 71 of file HybridHadronization.cc.
View newest version in sPHENIX GitHub at line 71 of file HybridHadronization.cc
double HybridHadronization::SigM2_calc (double R2chg, double qm1, double qm2, double qq1, double qq2) private
Definition at line 66 of file HybridHadronization.cc.
View newest version in sPHENIX GitHub at line 66 of file HybridHadronization.cc
void HybridHadronization::stringform () private
Definition at line 969 of file HybridHadronization.cc.
View newest version in sPHENIX GitHub at line 969 of file HybridHadronization.cc
References col, i, j, k, HybridHadronization::HHparton::pos_str(), start, and HybridHadronization::HHparton::string_id().
void HybridHadronization::stringprep (parton_collection & SP_remnants, parton_collection & SP_prepremn, bool cutstr) private
we need to link Tempsorting1 with Transitdijunction1,
Definition at line 4082 of file HybridHadronization.cc.
View newest version in sPHENIX GitHub at line 4082 of file HybridHadronization.cc
References HybridHadronization::HHparton::acol(), HybridHadronization::parton_collection::add(), Acts::Test::at, HybridHadronization::parton_collection::clear(), col, HybridHadronization::HHparton::col(), double(), HybridHadronization::HHparton::e(), Acts::UnitConstants::e, fid, hbarc, i, HybridHadronization::HHparton::id(), HybridHadronization::HHhadron::id(), HybridHadronization::HHparton::is_fakeparton(), HybridHadronization::HHhadron::is_recohad(), HybridHadronization::HHparton::is_remnant(), HybridHadronization::HHhadron::is_shth(), it, j, Acts::UnitConstants::J, JSWARN, loc, Acts::UnitConstants::m2, mass, HybridHadronization::HHparton::mass(), HybridHadronization::HHhadron::mass(), n, HybridHadronization::parton_collection::num(), HybridHadronization::HHparton::orig(), merge_hashes::p, HybridHadronization::HHhadron::P(), P(), Acts::Test::pos, HybridHadronization::HHhadron::pos(), HybridHadronization::HHparton::px(), HybridHadronization::HHparton::py(), HybridHadronization::HHparton::PY_stat(), HybridHadronization::HHparton::PY_tag1(), HybridHadronization::HHparton::PY_tag2(), HybridHadronization::HHparton::PY_tag3(), HybridHadronization::HHparton::pz(), ran(), Jetscape::FourVector::Set(), Jetscape::Parton::set_anti_color(), Jetscape::Parton::set_color(), swap(), t, Jetscape::FourVector::t(), Jetscape::FourVector::x(), ambiguity_solver_full_chain::x, y, Jetscape::FourVector::y(), Jetscape::FourVector::z(), and physmon_track_finding_ttbar::z.
void HybridHadronization::WriteTask (weak_ptr< JetScapeWriter > w) virtual
A virtual function to define a default WriteTask() function for a JetScapeTask. It can be overridden by different modules/tasks. Current setup: Every task gets handed a pointer to the writer and can add any information it likes to it (using predefined functions like WriteComment()) This is maximally flexible but makes it difficult to properly store information for a variety of outputs. E.g., sigmaGen: A HardProcess can easily write the xsec to any stream-type output using WriteComment. But to set it in a HepMC file, either HardProcess needs to make a case-by-case selection, meaning a new file format would need to percolate through multiple base classes, or the writer needs to know this information and implement WriteEvent appropriately. The latter is obviously better, but it's non-trivial to collect this information.
Reimplemented from Jetscape::Hadronization.
Definition at line 447 of file HybridHadronization.cc.
View newest version in sPHENIX GitHub at line 447 of file HybridHadronization.cc
References f, and VERBOSE.
Member Data Documentation
int HybridHadronization::additional_pythia_particles private
Definition at line 61 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 61 of file HybridHadronization.h
bool HybridHadronization::afterburner_frag_hadrons = false private
Definition at line 64 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 64 of file HybridHadronization.h
int HybridHadronization::attempts_max private
Definition at line 58 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 58 of file HybridHadronization.h
double HybridHadronization::brickL private
Definition at line 56 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 56 of file HybridHadronization.h
double HybridHadronization::brickT private
Definition at line 56 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 56 of file HybridHadronization.h
double HybridHadronization::delta_t private
Definition at line 49 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 49 of file HybridHadronization.h
double HybridHadronization::dist2cut private
Definition at line 49 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 49 of file HybridHadronization.h
std::mt19937_64 HybridHadronization::eng private
Definition at line 72 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 72 of file HybridHadronization.h
double HybridHadronization::eta_max_boost_inv private
Definition at line 49 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 49 of file HybridHadronization.h
double HybridHadronization::gmax private
Definition at line 49 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 49 of file HybridHadronization.h
bool HybridHadronization::goldstonereco private
Definition at line 62 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 62 of file HybridHadronization.h
double HybridHadronization::had_prop private
Definition at line 49 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 49 of file HybridHadronization.h
double HybridHadronization::hbarc private
Definition at line 49 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 49 of file HybridHadronization.h
hadron_collection HybridHadronization::HH_hadrons private
Definition at line 340 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 340 of file HybridHadronization.h
parton_collection HybridHadronization::HH_pyremn private
Definition at line 339 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 339 of file HybridHadronization.h
hadron_collection HybridHadronization::HH_pythia_hadrons private
Definition at line 340 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 340 of file HybridHadronization.h
parton_collection HybridHadronization::HH_recomb_extrapartons private
Definition at line 338 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 338 of file HybridHadronization.h
parton_collection HybridHadronization::HH_remnants private
Definition at line 339 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 339 of file HybridHadronization.h
parton_collection HybridHadronization::HH_shower private
Definition at line 337 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 337 of file HybridHadronization.h
parton_collection HybridHadronization::HH_showerptns private
Definition at line 339 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 339 of file HybridHadronization.h
parton_collection HybridHadronization::HH_thermal private
Definition at line 337 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 337 of file HybridHadronization.h
double HybridHadronization::hydro_Tc private
Definition at line 49 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 49 of file HybridHadronization.h
vector<int> HybridHadronization::IdColInfo1 private
Definition at line 70 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 70 of file HybridHadronization.h
vector<int> HybridHadronization::IdColInfo2 private
Definition at line 70 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 70 of file HybridHadronization.h
vector<int> HybridHadronization::IdColInfo3 private
Definition at line 70 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 70 of file HybridHadronization.h
vector<int> HybridHadronization::IdColInfo4 private
Definition at line 70 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 70 of file HybridHadronization.h
bool HybridHadronization::inbrick private
Definition at line 56 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 56 of file HybridHadronization.h
bool HybridHadronization::inhydro private
Definition at line 56 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 56 of file HybridHadronization.h
vector<vector<int> > HybridHadronization::JunctionInfo private
Definition at line 69 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 69 of file HybridHadronization.h
double HybridHadronization::maxB_level private
Definition at line 49 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 49 of file HybridHadronization.h
double HybridHadronization::maxM_level private
Definition at line 49 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 49 of file HybridHadronization.h
int HybridHadronization::nreusehydro private
Definition at line 56 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 56 of file HybridHadronization.h
int HybridHadronization::number_p_fake private
Definition at line 50 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 50 of file HybridHadronization.h
double HybridHadronization::p_fake private
Definition at line 49 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 49 of file HybridHadronization.h
double HybridHadronization::part_prop private
Definition at line 49 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 49 of file HybridHadronization.h
const double HybridHadronization::pi = 3.1415926535897932384626433832795 private
Definition at line 57 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 57 of file HybridHadronization.h
Pythia8::Pythia HybridHadronization::pythia static protected
Definition at line 380 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 380 of file HybridHadronization.h
std::string HybridHadronization::pythia_decays private
Definition at line 65 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 65 of file HybridHadronization.h
unsigned int HybridHadronization::rand_seed private
Definition at line 59 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 59 of file HybridHadronization.h
int HybridHadronization::reco_hadrons_pythia private
Definition at line 60 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 60 of file HybridHadronization.h
RegisterJetScapeModule< HybridHadronization > HybridHadronization::reg static private
Definition at line 42 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 42 of file HybridHadronization.h
double HybridHadronization::sh_recofactor private
Definition at line 49 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 49 of file HybridHadronization.h
double HybridHadronization::SigB2 private
Definition at line 55 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 55 of file HybridHadronization.h
double HybridHadronization::SigBc2 private
Definition at line 55 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 55 of file HybridHadronization.h
double HybridHadronization::SigD2 private
Definition at line 55 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 55 of file HybridHadronization.h
double HybridHadronization::SigDs2 private
Definition at line 55 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 55 of file HybridHadronization.h
double HybridHadronization::SigJpi2 private
Definition at line 55 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 55 of file HybridHadronization.h
double HybridHadronization::SigK2 private
Definition at line 55 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 55 of file HybridHadronization.h
double HybridHadronization::SigNucL2 private
Definition at line 51 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 51 of file HybridHadronization.h
double HybridHadronization::SigNucR2 private
Definition at line 51 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 51 of file HybridHadronization.h
double HybridHadronization::SigObbbL2 private
Definition at line 51 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 51 of file HybridHadronization.h
double HybridHadronization::SigObbbR2 private
Definition at line 51 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 51 of file HybridHadronization.h
double HybridHadronization::SigObbcL2 private
Definition at line 51 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 51 of file HybridHadronization.h
double HybridHadronization::SigObbcR2 private
Definition at line 51 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 51 of file HybridHadronization.h
double HybridHadronization::SigObbL2 private
Definition at line 51 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 51 of file HybridHadronization.h
double HybridHadronization::SigObbR2 private
Definition at line 51 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 51 of file HybridHadronization.h
double HybridHadronization::SigObccL2 private
Definition at line 51 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 51 of file HybridHadronization.h
double HybridHadronization::SigObccR2 private
Definition at line 51 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 51 of file HybridHadronization.h
double HybridHadronization::SigObcL2 private
Definition at line 51 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 51 of file HybridHadronization.h
double HybridHadronization::SigObcR2 private
Definition at line 51 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 51 of file HybridHadronization.h
double HybridHadronization::SigObL2 private
Definition at line 51 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 51 of file HybridHadronization.h
double HybridHadronization::SigObR2 private
Definition at line 51 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 51 of file HybridHadronization.h
double HybridHadronization::SigOcccL2 private
Definition at line 51 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 51 of file HybridHadronization.h
double HybridHadronization::SigOcccR2 private
Definition at line 51 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 51 of file HybridHadronization.h
double HybridHadronization::SigOccL2 private
Definition at line 51 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 51 of file HybridHadronization.h
double HybridHadronization::SigOccR2 private
Definition at line 51 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 51 of file HybridHadronization.h
double HybridHadronization::SigOcL2 private
Definition at line 51 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 51 of file HybridHadronization.h
double HybridHadronization::SigOcR2 private
Definition at line 51 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 51 of file HybridHadronization.h
double HybridHadronization::SigOmgL2 private
Definition at line 51 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 51 of file HybridHadronization.h
double HybridHadronization::SigOmgR2 private
Definition at line 51 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 51 of file HybridHadronization.h
double HybridHadronization::SigPhi2 private
Definition at line 55 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 55 of file HybridHadronization.h
double HybridHadronization::SigPi2 private
Definition at line 55 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 55 of file HybridHadronization.h
double HybridHadronization::SigSigbL2 private
Definition at line 51 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 51 of file HybridHadronization.h
double HybridHadronization::SigSigbR2 private
Definition at line 51 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 51 of file HybridHadronization.h
double HybridHadronization::SigSigcL2 private
Definition at line 51 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 51 of file HybridHadronization.h
double HybridHadronization::SigSigcR2 private
Definition at line 51 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 51 of file HybridHadronization.h
double HybridHadronization::SigSigL2 private
Definition at line 51 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 51 of file HybridHadronization.h
double HybridHadronization::SigSigR2 private
Definition at line 51 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 51 of file HybridHadronization.h
double HybridHadronization::SigUps2 private
Definition at line 55 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 55 of file HybridHadronization.h
double HybridHadronization::SigXibbL2 private
Definition at line 51 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 51 of file HybridHadronization.h
double HybridHadronization::SigXibbR2 private
Definition at line 51 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 51 of file HybridHadronization.h
double HybridHadronization::SigXibcL2 private
Definition at line 51 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 51 of file HybridHadronization.h
double HybridHadronization::SigXibcR2 private
Definition at line 51 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 51 of file HybridHadronization.h
double HybridHadronization::SigXibL2 private
Definition at line 51 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 51 of file HybridHadronization.h
double HybridHadronization::SigXibR2 private
Definition at line 51 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 51 of file HybridHadronization.h
double HybridHadronization::SigXiccL2 private
Definition at line 51 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 51 of file HybridHadronization.h
double HybridHadronization::SigXiccR2 private
Definition at line 51 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 51 of file HybridHadronization.h
double HybridHadronization::SigXicL2 private
Definition at line 51 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 51 of file HybridHadronization.h
double HybridHadronization::SigXicR2 private
Definition at line 51 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 51 of file HybridHadronization.h
double HybridHadronization::SigXiL2 private
Definition at line 51 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 51 of file HybridHadronization.h
double HybridHadronization::SigXiR2 private
Definition at line 51 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 51 of file HybridHadronization.h
vector<vector<vector<int> > > HybridHadronization::Tempjunctions private
Definition at line 68 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 68 of file HybridHadronization.h
double HybridHadronization::th_recofactor private
Definition at line 49 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 49 of file HybridHadronization.h
bool HybridHadronization::torder_reco private
Definition at line 63 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 63 of file HybridHadronization.h
double HybridHadronization::xmb private
Definition at line 49 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 49 of file HybridHadronization.h
double HybridHadronization::xmc private
Definition at line 49 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 49 of file HybridHadronization.h
double HybridHadronization::xmq private
Definition at line 49 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 49 of file HybridHadronization.h
double HybridHadronization::xms private
Definition at line 49 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 49 of file HybridHadronization.h
The documentation for this class was generated from the following files:
JETSCAPE/blob/main/src/hadronization/HybridHadronization.h
JETSCAPE/blob/main/src/hadronization/HybridHadronization.cc