Analysis Software: Acts::DefaultExtension Struct Reference
Acts::DefaultExtension Struct Reference
Default evaluater of the k_i's and elements of the transport matrix D of the RKN4 stepping. This is a pure implementation by textbook.
#include <acts/blob/sPHENIX/Core/include/Acts/Propagator/DefaultExtension.hpp>
Public Member Functions
DefaultExtension ()=default
Default constructor.
template<typename propagator_state_t , typename stepper_t >
int bid (const propagator_state_t &, const stepper_t &) const
Control function if the step evaluation would be valid.
template<typename propagator_state_t , typename stepper_t >
bool k (const propagator_state_t &state, const stepper_t &stepper, Vector3D &knew, const Vector3D &bField, std::array< double, 4 > &kQoP, const int i=0, const double h=0., const Vector3D &kprev=Vector3D())
Evaluater of the k_i's of the RKN4. For the case of i = 0 this step sets up qop, too.
template<typename propagator_state_t , typename stepper_t >
bool finalize (propagator_state_t &state, const stepper_t &stepper, const double h) const
Veto function after a RKN4 step was accepted by judging on the error of the step. Since the textbook does not deliver further vetos, this is a dummy function.
template<typename propagator_state_t , typename stepper_t >
bool finalize (propagator_state_t &state, const stepper_t &stepper, const double h, FreeMatrix &D) const
Veto function after a RKN4 step was accepted by judging on the error of the step. Since the textbook does not deliver further vetos, this is just for the evaluation of the transport matrix.
Private Member Functions
template<typename propagator_state_t , typename stepper_t >
void propagateTime (propagator_state_t &state, const stepper_t &stepper, const double h) const
Propagation function for the time coordinate.
template<typename propagator_state_t , typename stepper_t >
bool transportMatrix (propagator_state_t &state, const stepper_t &stepper, const double h, FreeMatrix &D) const
Calculates the transport matrix D for the jacobian.
Detailed Description
Default evaluater of the k_i's and elements of the transport matrix D of the RKN4 stepping. This is a pure implementation by textbook.
Definition at line 19 of file DefaultExtension.hpp.
View newest version in sPHENIX GitHub at line 19 of file DefaultExtension.hpp
Constructor & Destructor Documentation
Acts::DefaultExtension::DefaultExtension () default
Default constructor.
Member Function Documentation
template<typename propagator_state_t , typename stepper_t > int Acts::DefaultExtension::bid (const propagator_state_t & , const stepper_t &) const inline
Control function if the step evaluation would be valid.
Template Parameters
propagator_state_t Type of the state of the propagator
stepper_t Type of the stepper
Returns
Boolean flag if the step would be valid
Definition at line 29 of file DefaultExtension.hpp.
View newest version in sPHENIX GitHub at line 29 of file DefaultExtension.hpp
template<typename propagator_state_t , typename stepper_t > bool Acts::DefaultExtension::finalize (propagator_state_t & state, const stepper_t & stepper, const double h) const inline
Veto function after a RKN4 step was accepted by judging on the error of the step. Since the textbook does not deliver further vetos, this is a dummy function.
Template Parameters
propagator_state_t Type of the state of the propagator
stepper_t Type of the stepper
Parameters
[in] state State of the propagator
[in] stepper Stepper of the propagation
[in] h Step size
Returns
Boolean flag if the calculation is valid
Definition at line 77 of file DefaultExtension.hpp.
View newest version in sPHENIX GitHub at line 77 of file DefaultExtension.hpp
References propagateTime().
template<typename propagator_state_t , typename stepper_t > bool Acts::DefaultExtension::finalize (propagator_state_t & state, const stepper_t & stepper, const double h, FreeMatrix & D) const inline
Veto function after a RKN4 step was accepted by judging on the error of the step. Since the textbook does not deliver further vetos, this is just for the evaluation of the transport matrix.
Template Parameters
propagator_state_t Type of the state of the propagator
stepper_t Type of the stepper
Parameters
[in] state State of the propagator
[in] stepper Stepper of the propagation
[in] h Step size
[out] D Transport matrix
Returns
Boolean flag if the calculation is valid
Definition at line 95 of file DefaultExtension.hpp.
View newest version in sPHENIX GitHub at line 95 of file DefaultExtension.hpp
References propagateTime(), and transportMatrix().
template<typename propagator_state_t , typename stepper_t > bool Acts::DefaultExtension::k (const propagator_state_t & state, const stepper_t & stepper, Vector3D & knew, const Vector3D & bField, std::array< double, 4 > & kQoP, const int i = 0, const double h = 0., const Vector3D & kprev = Vector3D()) inline
Evaluater of the k_i's of the RKN4. For the case of i = 0 this step sets up qop, too.
Template Parameters
propagator_state_t Type of the state of the propagator
stepper_t Type of the stepper
Parameters
[in] state State of the propagator
[in] stepper Stepper of the propagation
[out] knew Next k_i that is evaluated
[in] bField B-Field at the evaluation position
[out] kQoP k_i elements of the momenta
[in] i Index of the k_i, i = [0, 3]
[in] h Step size (= 0. ^ 0.5 * StepSize ^ StepSize)
[in] kprev Evaluated k_{i - 1}
Returns
Boolean flag if the calculation is valid
Definition at line 49 of file DefaultExtension.hpp.
View newest version in sPHENIX GitHub at line 49 of file DefaultExtension.hpp
References Acts::VectorHelpers::cross(), Acts::UnitConstants::h, and i.
template<typename propagator_state_t , typename stepper_t > void Acts::DefaultExtension::propagateTime (propagator_state_t & state, const stepper_t & stepper, const double h) const inline private
Propagation function for the time coordinate.
Template Parameters
propagator_state_t Type of the state of the propagator
stepper_t Type of the stepper
Parameters
[in,out] state State of the propagator
[in] stepper Stepper of the propagation
[in] h Step size
This evaluation is based on dt/ds = 1/v = 1/(beta * c) with the velocity v, the speed of light c and beta = v/c. This can be re-written as dt/ds = sqrt(m^2/p^2 + c^{-2}) with the mass m and the momentum p.
Definition at line 110 of file DefaultExtension.hpp.
View newest version in sPHENIX GitHub at line 110 of file DefaultExtension.hpp
Referenced by finalize().
template<typename propagator_state_t , typename stepper_t > bool Acts::DefaultExtension::transportMatrix (propagator_state_t & state, const stepper_t & stepper, const double h, FreeMatrix & D) const inline private
Calculates the transport matrix D for the jacobian.
Template Parameters
propagator_state_t Type of the state of the propagator
stepper_t Type of the stepper
Parameters
[in] state State of the propagator
[in] stepper Stepper of the propagation
[in] h Step size
[out] D Transport matrix
Returns
Boolean flag if evaluation is valid
The calculations are based on ATL-SOFT-PUB-2009-002. The update of the Jacobian matrix is requires only the calculation of eq. 17 and 18. Since the terms of eq. 18 are currently 0, this matrix is not needed in the calculation. The matrix A from eq. 17 consists out of 3 different parts. The first one is given by the upper left 3x3 matrix that are calculated by the derivatives dF/dT (called dFdT) and dG/dT (calles dGdT). The second is given by the top 3 lines of the rightmost column. This is calculated by dFdL and dGdL. The remaining non-zero term is calculated directly. The naming of the variables is explained in eq. 11 and are directly related to the initial problem in eq. 7. The evaluation is based by propagating the parameters T and lambda as given in eq. 16 and evaluating the derivations for matrix A.
Note
The translation for u_{n+1} in eq. 7 is in this case a 3-dimensional vector without a dependency of Lambda or lambda neither in u_n nor in u_n'. The second and fourth eq. in eq. 14 have the constant offset matrices h * Id and Id respectively. This involves that the constant offset does not exist for rectangular matrix dGdu' (due to the missing Lambda part) and only exists for dFdu' in dlambda/dlambda.
Definition at line 133 of file DefaultExtension.hpp.
View newest version in sPHENIX GitHub at line 133 of file DefaultExtension.hpp
References Acts::VectorHelpers::cross(), and Acts::UnitConstants::h.
Referenced by finalize().
The documentation for this struct was generated from the following file:
acts/blob/sPHENIX/Core/include/Acts/Propagator/DefaultExtension.hpp