Analysis Software: cl::Platform Class Reference
cl::Platform Class Reference
Platform interface.
#include <JETSCAPE/blob/main/external_packages/clvisc_wrapper/include/cl.hpp>
Public Member Functions
Platform (cl_platform_id platform)
Platform ()
Platform (const Platform &platform)
Platform & operator= (const Platform &rhs)
cl_int getInfo (cl_platform_info name, STRING_CLASS *param) const
template<cl_int name>
detail::param_traits
< detail::cl_platform_info,
name >::param_type getInfo (cl_int *err=NULL) const
cl_int getDevices (cl_device_type type, VECTOR_CLASS< Device > *devices) const
Public Member Functions inherited from cl::detail::Wrapper< cl_platform_id >
Wrapper ()
Wrapper (const Wrapper< cl_type > &rhs)
~Wrapper ()
Wrapper< cl_type > & operator= (const Wrapper< cl_type > &rhs)
cl_type operator() () const
cl_type & operator() ()
Static Public Member Functions
static const Platform null ()
static cl_int get (VECTOR_CLASS< Platform > *platforms)
Additional Inherited Members
Public Types inherited from cl::detail::Wrapper< cl_platform_id >
typedef cl_platform_id cl_type
Protected Member Functions inherited from cl::detail::Wrapper< cl_platform_id >
cl_int retain () const
cl_int release () const
Protected Attributes inherited from cl::detail::Wrapper< cl_platform_id >
cl_type object_
Detailed Description
Platform interface.
Definition at line 1258 of file cl.hpp.
View newest version in sPHENIX GitHub at line 1258 of file cl.hpp
Constructor & Destructor Documentation
cl::Platform::Platform (cl_platform_id platform) inline
Definition at line 1263 of file cl.hpp.
View newest version in sPHENIX GitHub at line 1263 of file cl.hpp
References cl::detail::Wrapper< cl_platform_id >::object_.
cl::Platform::Platform () inline
Definition at line 1265 of file cl.hpp.
View newest version in sPHENIX GitHub at line 1265 of file cl.hpp
cl::Platform::Platform (const Platform & platform) inline
Definition at line 1267 of file cl.hpp.
View newest version in sPHENIX GitHub at line 1267 of file cl.hpp
Member Function Documentation
static cl_int cl::Platform::get (VECTOR_CLASS< Platform > * platforms) inline static
Definition at line 1390 of file cl.hpp.
View newest version in sPHENIX GitHub at line 1390 of file cl.hpp
References cl::detail::errHandler().
Referenced by clvisc::OpenclBackend::CreateContext_().
cl_int cl::Platform::getDevices (cl_device_type type, VECTOR_CLASS< Device > * devices) const inline
Definition at line 1297 of file cl.hpp.
View newest version in sPHENIX GitHub at line 1297 of file cl.hpp
References cl::detail::errHandler(), and cl::detail::Wrapper< cl_platform_id >::object_.
cl_int cl::Platform::getInfo (cl_platform_info name, STRING_CLASS * param) const inline
Definition at line 1277 of file cl.hpp.
View newest version in sPHENIX GitHub at line 1277 of file cl.hpp
References cl::detail::errHandler(), cl::detail::getInfo(), and cl::detail::Wrapper< cl_platform_id >::object_.
Referenced by getInfo().
template<cl_int name> detail::param_traits<detail::cl_platform_info, name>::param_type cl::Platform::getInfo (cl_int * err = NULL) const inline
Definition at line 1286 of file cl.hpp.
View newest version in sPHENIX GitHub at line 1286 of file cl.hpp
References getInfo(), and perf_headwind::name.
static const Platform cl::Platform::null () static
Platform& cl::Platform::operator= (const Platform & rhs) inline
Definition at line 1269 of file cl.hpp.
View newest version in sPHENIX GitHub at line 1269 of file cl.hpp
References cl::detail::Wrapper< T >::operator=().
The documentation for this class was generated from the following file:
JETSCAPE/blob/main/external_packages/clvisc_wrapper/include/cl.hpp