Analysis Software: HcalMonDraw Class Reference
HcalMonDraw Class Reference
#include <OnlMon/blob/main/subsystems/hcal/HcalMonDraw.h>
Public Member Functions
HcalMonDraw (const std::string &name)
~HcalMonDraw () override
int Init () override
int Draw (const std::string &what="ALL") override
int MakeHtml (const std::string &what="ALL") override
int SavePlot (const std::string &what="ALL", const std::string &type="png") override
void HandleEvent (int, int, int, TObject *)
Public Member Functions inherited from OnlMonDraw
OnlMonDraw (const std::string &name="NONE")
virtual ~OnlMonDraw ()
virtual int MakePS (const std::string &what="ALL")
const std::string Name () const
void Verbosity (const int i)
int Verbosity () const
Private Member Functions
int MakeCanvas (const std::string &name)
int DrawFirst (const std::string &what="ALL")
int DrawSecond (const std::string &what="ALL")
int DrawThird (const std::string &what="ALL")
int DrawFourth (const std::string &what="ALL")
int DrawFifth (const std::string &what="ALL")
int FindHotTower (TPad *warn, TH2 *)
void DrawTowerAvg ()
void DrawHitMap ()
time_t getTime ()
Private Attributes
std::string prefix = "HCALMON"
TCanvas * TC [9] = {nullptr}
TPad * transparent [9] = {nullptr}
TPad * Pad [19] = {nullptr}
TPad * warning [18] = {nullptr}
TGraphErrors * gr [2] = {nullptr}
TStyle * hcalStyle = nullptr
Additional Inherited Members
Protected Member Functions inherited from OnlMonDraw
virtual int DrawDeadServer (TPad *transparent)
Protected Attributes inherited from OnlMonDraw
std::string ThisName
int verbosity = 0
Detailed Description
Definition at line 15 of file HcalMonDraw.h.
View newest version in sPHENIX GitHub at line 15 of file HcalMonDraw.h
Constructor & Destructor Documentation
HcalMonDraw::HcalMonDraw (const std::string & name) explicit
Definition at line 29 of file HcalMonDraw.cc.
View newest version in sPHENIX GitHub at line 29 of file HcalMonDraw.cc
References prefix, and OnlMonDraw::ThisName.
HcalMonDraw::~HcalMonDraw () inline override
Definition at line 20 of file HcalMonDraw.h.
View newest version in sPHENIX GitHub at line 20 of file HcalMonDraw.h
Member Function Documentation
int HcalMonDraw::Draw (const std::string & what = "ALL") override virtual
Reimplemented from OnlMonDraw.
Definition at line 190 of file HcalMonDraw.cc.
View newest version in sPHENIX GitHub at line 190 of file HcalMonDraw.cc
References DrawFifth(), DrawFirst(), DrawFourth(), DrawSecond(), and DrawThird().
Referenced by MakeHtml(), and SavePlot().
int HcalMonDraw::DrawFifth (const std::string & what = "ALL") private
Definition at line 1488 of file HcalMonDraw.cc.
View newest version in sPHENIX GitHub at line 1488 of file HcalMonDraw.cc
References OnlMonDraw::DrawDeadServer(), OnlMonClient::getHisto(), getTime(), OnlMonClient::instance(), MakeCanvas(), Pad, prefix, OnlMonClient::RunNumber(), TC, OnlMonDraw::ThisName, and transparent.
Referenced by Draw().
int HcalMonDraw::DrawFirst (const std::string & what = "ALL") private
Definition at line 227 of file HcalMonDraw.cc.
View newest version in sPHENIX GitHub at line 227 of file HcalMonDraw.cc
References OnlMonDraw::DrawDeadServer(), FindHotTower(), OnlMonClient::getHisto(), getTime(), hcalStyle, OnlMonClient::instance(), levels, MakeCanvas(), Pad, prefix, OnlMonClient::RunNumber(), TC, OnlMonDraw::ThisName, transparent, and warning.
Referenced by Draw().
int HcalMonDraw::DrawFourth (const std::string & what = "ALL") private
Definition at line 631 of file HcalMonDraw.cc.
View newest version in sPHENIX GitHub at line 631 of file HcalMonDraw.cc
References OnlMonDraw::DrawDeadServer(), OnlMonClient::getHisto(), getTime(), i, OnlMonClient::instance(), leg, line, MakeCanvas(), Pad, prefix, OnlMonClient::RunNumber(), TC, transparent, warning, xmax, xmin, ymax, and ymin.
Referenced by Draw().
void HcalMonDraw::DrawHitMap () private
Definition at line 1363 of file HcalMonDraw.cc.
View newest version in sPHENIX GitHub at line 1363 of file HcalMonDraw.cc
References OnlMonDraw::DrawDeadServer(), OnlMonClient::getHisto(), OnlMonClient::instance(), MakeCanvas(), Pad, prefix, TC, and transparent.
Referenced by HandleEvent().
int HcalMonDraw::DrawSecond (const std::string & what = "ALL") private
Definition at line 399 of file HcalMonDraw.cc.
View newest version in sPHENIX GitHub at line 399 of file HcalMonDraw.cc
References OnlMonDraw::DrawDeadServer(), OnlMonClient::getHisto(), getTime(), add_histos_bX::ib, OnlMonClient::instance(), MakeCanvas(), Pad, prefix, OnlMonClient::RunNumber(), TC, OnlMonDraw::ThisName, and transparent.
Referenced by Draw().
int HcalMonDraw::DrawThird (const std::string & what = "ALL") private
Definition at line 500 of file HcalMonDraw.cc.
View newest version in sPHENIX GitHub at line 500 of file HcalMonDraw.cc
References OnlMonDraw::DrawDeadServer(), OnlMonClient::getHisto(), getTime(), OnlMonClient::instance(), MakeCanvas(), Pad, prefix, OnlMonClient::RunNumber(), TC, OnlMonDraw::ThisName, and transparent.
Referenced by Draw().
void HcalMonDraw::DrawTowerAvg () private
Definition at line 1293 of file HcalMonDraw.cc.
View newest version in sPHENIX GitHub at line 1293 of file HcalMonDraw.cc
References OnlMonDraw::DrawDeadServer(), OnlMonClient::getHisto(), OnlMonClient::instance(), MakeCanvas(), Pad, prefix, TC, and transparent.
Referenced by HandleEvent().
int HcalMonDraw::FindHotTower (TPad * warn, TH2 * hhit) private
Definition at line 1053 of file HcalMonDraw.cc.
View newest version in sPHENIX GitHub at line 1053 of file HcalMonDraw.cc
Referenced by DrawFirst().
time_t HcalMonDraw::getTime () private
Definition at line 1612 of file HcalMonDraw.cc.
View newest version in sPHENIX GitHub at line 1612 of file HcalMonDraw.cc
References OnlMonClient::EventTime(), and OnlMonClient::instance().
Referenced by DrawFifth(), DrawFirst(), DrawFourth(), DrawSecond(), and DrawThird().
void HcalMonDraw::HandleEvent (int event, int x, int y, TObject * selected)
Definition at line 1424 of file HcalMonDraw.cc.
View newest version in sPHENIX GitHub at line 1424 of file HcalMonDraw.cc
References OnlMonDraw::DrawDeadServer(), DrawHitMap(), DrawTowerAvg(), OnlMonClient::getHisto(), OnlMonClient::instance(), MakeCanvas(), Pad, prefix, TC, and transparent.
int HcalMonDraw::Init () override virtual
Reimplemented from OnlMonDraw.
Definition at line 50 of file HcalMonDraw.cc.
View newest version in sPHENIX GitHub at line 50 of file HcalMonDraw.cc
References hcalStyle.
int HcalMonDraw::MakeCanvas (const std::string & name) private
Definition at line 70 of file HcalMonDraw.cc.
View newest version in sPHENIX GitHub at line 70 of file HcalMonDraw.cc
References OnlMonClient::GetDisplaySizeX(), OnlMonClient::GetDisplaySizeY(), OnlMonClient::instance(), Pad, TC, transparent, and warning.
Referenced by DrawFifth(), DrawFirst(), DrawFourth(), DrawHitMap(), DrawSecond(), DrawThird(), DrawTowerAvg(), and HandleEvent().
int HcalMonDraw::MakeHtml (const std::string & what = "ALL") override virtual
Reimplemented from OnlMonDraw.
Definition at line 1251 of file HcalMonDraw.cc.
View newest version in sPHENIX GitHub at line 1251 of file HcalMonDraw.cc
References OnlMonClient::CanvasToPng(), Draw(), OnlMonClient::htmlRegisterPage(), OnlMonClient::instance(), TC, and to_string().
int HcalMonDraw::SavePlot (const std::string & what = "ALL", const std::string & type = "png") override virtual
Reimplemented from OnlMonDraw.
Definition at line 1227 of file HcalMonDraw.cc.
View newest version in sPHENIX GitHub at line 1227 of file HcalMonDraw.cc
References OnlMonClient::CanvasToPng(), Draw(), filename, OnlMonClient::instance(), OnlMonClient::RunNumber(), TC, OnlMonDraw::ThisName, and to_string().
Member Data Documentation
TGraphErrors* HcalMonDraw::gr[2] = {nullptr} private
Definition at line 47 of file HcalMonDraw.h.
View newest version in sPHENIX GitHub at line 47 of file HcalMonDraw.h
TStyle* HcalMonDraw::hcalStyle = nullptr private
Definition at line 48 of file HcalMonDraw.h.
View newest version in sPHENIX GitHub at line 48 of file HcalMonDraw.h
Referenced by DrawFirst(), and Init().
TPad* HcalMonDraw::Pad[19] = {nullptr} private
Definition at line 45 of file HcalMonDraw.h.
View newest version in sPHENIX GitHub at line 45 of file HcalMonDraw.h
Referenced by DrawFifth(), DrawFirst(), DrawFourth(), DrawHitMap(), DrawSecond(), DrawThird(), DrawTowerAvg(), HandleEvent(), and MakeCanvas().
std::string HcalMonDraw::prefix = "HCALMON" private
Definition at line 42 of file HcalMonDraw.h.
View newest version in sPHENIX GitHub at line 42 of file HcalMonDraw.h
Referenced by DrawFifth(), DrawFirst(), DrawFourth(), DrawHitMap(), DrawSecond(), DrawThird(), DrawTowerAvg(), HandleEvent(), and HcalMonDraw().
TCanvas* HcalMonDraw::TC[9] = {nullptr} private
Definition at line 43 of file HcalMonDraw.h.
View newest version in sPHENIX GitHub at line 43 of file HcalMonDraw.h
Referenced by DrawFifth(), DrawFirst(), DrawFourth(), DrawHitMap(), DrawSecond(), DrawThird(), DrawTowerAvg(), HandleEvent(), MakeCanvas(), MakeHtml(), and SavePlot().
TPad* HcalMonDraw::transparent[9] = {nullptr} private
Definition at line 44 of file HcalMonDraw.h.
View newest version in sPHENIX GitHub at line 44 of file HcalMonDraw.h
Referenced by DrawFifth(), DrawFirst(), DrawFourth(), DrawHitMap(), DrawSecond(), DrawThird(), DrawTowerAvg(), HandleEvent(), and MakeCanvas().
TPad* HcalMonDraw::warning[18] = {nullptr} private
Definition at line 46 of file HcalMonDraw.h.
View newest version in sPHENIX GitHub at line 46 of file HcalMonDraw.h
Referenced by DrawFirst(), DrawFourth(), and MakeCanvas().
The documentation for this class was generated from the following files:
OnlMon/blob/main/subsystems/hcal/HcalMonDraw.h
OnlMon/blob/main/subsystems/hcal/HcalMonDraw.cc