Analysis Software: SynRadAna Class Reference
SynRadAna Class Reference
#include <analysis/blob/master/EIC-SynRad/SynRadAna/SynRadAna.h>
Public Member Functions
SynRadAna (const std::string &filename="SynRadAna.root")
virtual ~SynRadAna ()
int Init (PHCompositeNode *topNode) override
int InitRun (PHCompositeNode *topNode) override
int process_event (PHCompositeNode *topNode) override
int ResetEvent (PHCompositeNode *topNode) override
Clean up internals after each event.
int EndRun (const int runnumber) override
Called at the end of each run.
int End (PHCompositeNode *topNode) override
Called at the end of all processing.
int Reset (PHCompositeNode *) override
Reset.
void Print (const std::string &what="ALL") const override
int get_embedding_id () const
void set_embedding_id (int id)
void AddNode (const std::string &name)
void AddHit (const std::string &name)
void AddTower (const std::string &name)
bool isDoMvtxHits () const
void setDoMvtxHits (bool doMvtxHits)
bool isDoTPCHits () const
void setDoTPCHits (bool doTPCHits)
bool isDoPhoton () const
void setDoPhoton (bool doPhoton)
Public Member Functions inherited from SubsysReco
~SubsysReco () override
void Print (const std::string &="ALL") const override
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Private Member Functions
Fun4AllHistoManager * getHistoManager ()
Get a pointer to the default hist manager for QA modules.
std::string get_histo_prefix ()
Private Attributes
int _embedding_id
double m_eventWeight
bool do_photon
bool do_MVTXHits
bool do_TPCHits
std::string m_outputFIle
std::vector< std::string > _node_postfix
std::vector< std::string > _tower_postfix
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = std::numeric_limits<int>::max() - 10
}
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Detailed Description
Definition at line 14 of file SynRadAna.h.
View newest version in sPHENIX GitHub at line 14 of file SynRadAna.h
Constructor & Destructor Documentation
SynRadAna::SynRadAna (const std::string & filename = "SynRadAna.root")
Definition at line 86 of file SynRadAna.cc.
View newest version in sPHENIX GitHub at line 86 of file SynRadAna.cc
References Fun4AllBase::Verbosity().
SynRadAna::~SynRadAna () virtual
Definition at line 100 of file SynRadAna.cc.
View newest version in sPHENIX GitHub at line 100 of file SynRadAna.cc
References Fun4AllBase::Verbosity().
Member Function Documentation
void SynRadAna::AddHit (const std::string & name) inline
Definition at line 73 of file SynRadAna.h.
View newest version in sPHENIX GitHub at line 73 of file SynRadAna.h
References _node_postfix.
void SynRadAna::AddNode (const std::string & name) inline
Definition at line 67 of file SynRadAna.h.
View newest version in sPHENIX GitHub at line 67 of file SynRadAna.h
References _node_postfix.
void SynRadAna::AddTower (const std::string & name) inline
Definition at line 79 of file SynRadAna.h.
View newest version in sPHENIX GitHub at line 79 of file SynRadAna.h
References _tower_postfix.
int SynRadAna::End (PHCompositeNode * topNode) override virtual
Called at the end of all processing.
Reimplemented from SubsysReco.
Definition at line 570 of file SynRadAna.cc.
View newest version in sPHENIX GitHub at line 570 of file SynRadAna.cc
References Fun4AllHistoManager::dumpHistos(), Fun4AllReturnCodes::EVENT_OK, getHistoManager(), m_outputFIle, and Fun4AllBase::Verbosity().
int SynRadAna::EndRun (const int runnumber) override virtual
Called at the end of each run.
Reimplemented from SubsysReco.
Definition at line 562 of file SynRadAna.cc.
View newest version in sPHENIX GitHub at line 562 of file SynRadAna.cc
References Fun4AllReturnCodes::EVENT_OK, and Fun4AllBase::Verbosity().
int SynRadAna::get_embedding_id () const inline
embedding ID for the event positive ID is the embedded event of interest, e.g. jetty event from pythia negative IDs are backgrounds, .e.g out of time pile up collisions Usually, ID = 0 means the primary Au+Au collision background
Definition at line 58 of file SynRadAna.h.
View newest version in sPHENIX GitHub at line 58 of file SynRadAna.h
References _embedding_id.
string SynRadAna::get_histo_prefix () private
Definition at line 618 of file SynRadAna.cc.
View newest version in sPHENIX GitHub at line 618 of file SynRadAna.cc
References Fun4AllBase::Name().
Referenced by Init(), and process_event().
Fun4AllHistoManager * SynRadAna::getHistoManager () private
Get a pointer to the default hist manager for QA modules.
Definition at line 596 of file SynRadAna.cc.
View newest version in sPHENIX GitHub at line 596 of file SynRadAna.cc
References assert, Fun4AllServer::getHistoManager(), QAHistManagerDef::HistoManagerName, Fun4AllServer::instance(), and Fun4AllServer::registerHistoManager().
Referenced by End(), Init(), and process_event().
int SynRadAna::Init (PHCompositeNode * topNode) override virtual
Called during initialization. Typically this is where you can book histograms, and e.g. register them to Fun4AllServer (so they can be output to file using Fun4AllServer::dumpHistos() method).
Reimplemented from SubsysReco.
Definition at line 107 of file SynRadAna.cc.
View newest version in sPHENIX GitHub at line 107 of file SynRadAna.cc
References _node_postfix, _tower_postfix, assert, do_MVTXHits, do_photon, do_TPCHits, Fun4AllReturnCodes::EVENT_OK, get_histo_prefix(), getHistoManager(), h, h2, i, it, Fun4AllHistoManager::registerHisto(), and Fun4AllBase::Verbosity().
int SynRadAna::InitRun (PHCompositeNode * topNode) override virtual
Called for first event when run number is known. Typically this is where you may want to fetch data from database, because you know the run number. A place to book histograms which have to know the run number.
Reimplemented from SubsysReco.
Definition at line 222 of file SynRadAna.cc.
View newest version in sPHENIX GitHub at line 222 of file SynRadAna.cc
References Fun4AllReturnCodes::EVENT_OK, and Fun4AllBase::Verbosity().
bool SynRadAna::isDoMvtxHits () const inline
Definition at line 84 of file SynRadAna.h.
View newest version in sPHENIX GitHub at line 84 of file SynRadAna.h
References do_MVTXHits.
bool SynRadAna::isDoPhoton () const inline
Definition at line 104 of file SynRadAna.h.
View newest version in sPHENIX GitHub at line 104 of file SynRadAna.h
References do_photon.
bool SynRadAna::isDoTPCHits () const inline
Definition at line 94 of file SynRadAna.h.
View newest version in sPHENIX GitHub at line 94 of file SynRadAna.h
References do_TPCHits.
void SynRadAna::Print (const std::string & what = "ALL") const override virtual
Print out some info about this module.
Parameters
what can be used to specify what to print exactly.
Reimplemented from Fun4AllBase.
Definition at line 589 of file SynRadAna.cc.
View newest version in sPHENIX GitHub at line 589 of file SynRadAna.cc
int SynRadAna::process_event (PHCompositeNode * topNode) override virtual
Called for each event. This is where you do the real work.
Reimplemented from SubsysReco.
Definition at line 231 of file SynRadAna.cc.
View newest version in sPHENIX GitHub at line 231 of file SynRadAna.cc
References _embedding_id, _node_postfix, assert, do_MVTXHits, do_photon, do_TPCHits, Fun4AllReturnCodes::EVENT_OK, PHHepMCGenEventMap::get(), PHG4Particle::get_e(), PHG4Hit::get_eion(), get_histo_prefix(), PHG4Particle::get_pid(), PHG4Particle::get_primary_id(), PHG4Hit::get_trkid(), PHG4Particle::get_vtx_id(), PHG4VtxPoint::get_z(), TrkrHit::getAdc(), findNode::getClass(), PHHepMCGenEvent::getEvent(), Fun4AllHistoManager::getHisto(), getHistoManager(), PHG4HitContainer::getHits(), TrkrHitSet::getHits(), TrkrHitSetContainer::getHitSets(), TrkrDefs::getLayer(), PHG4TruthInfoContainer::GetNumPrimaryVertexParticles(), PHG4TruthInfoContainer::GetNumVertices(), PHG4TruthInfoContainer::GetParticle(), PHG4TruthInfoContainer::GetPrimaryParticleRange(), PHG4TruthInfoContainer::GetVtx(), PHG4Particle::identify(), TrkrHit::identify(), layer, m_eventWeight, TrkrDefs::mvtxId, particle, PHG4HitContainer::size(), PHG4TruthInfoContainer::size(), TrkrDefs::tpcId, and Fun4AllBase::Verbosity().
int SynRadAna::Reset (PHCompositeNode * topNode) override virtual
Reset.
Reimplemented from SubsysReco.
Definition at line 581 of file SynRadAna.cc.
View newest version in sPHENIX GitHub at line 581 of file SynRadAna.cc
References Fun4AllReturnCodes::EVENT_OK, and Fun4AllBase::Verbosity().
int SynRadAna::ResetEvent (PHCompositeNode * topNode) override virtual
Clean up internals after each event.
Reimplemented from SubsysReco.
Definition at line 554 of file SynRadAna.cc.
View newest version in sPHENIX GitHub at line 554 of file SynRadAna.cc
References Fun4AllReturnCodes::EVENT_OK, and Fun4AllBase::Verbosity().
void SynRadAna::set_embedding_id (int id) inline
embedding ID for the event positive ID is the embedded event of interest, e.g. jetty event from pythia negative IDs are backgrounds, .e.g out of time pile up collisions Usually, ID = 0 means the primary Au+Au collision background
Definition at line 64 of file SynRadAna.h.
View newest version in sPHENIX GitHub at line 64 of file SynRadAna.h
References _embedding_id, and train_ambiguity_solver::id.
void SynRadAna::setDoMvtxHits (bool doMvtxHits) inline
Definition at line 89 of file SynRadAna.h.
View newest version in sPHENIX GitHub at line 89 of file SynRadAna.h
References do_MVTXHits.
void SynRadAna::setDoPhoton (bool doPhoton) inline
Definition at line 109 of file SynRadAna.h.
View newest version in sPHENIX GitHub at line 109 of file SynRadAna.h
References do_photon.
void SynRadAna::setDoTPCHits (bool doTPCHits) inline
Definition at line 99 of file SynRadAna.h.
View newest version in sPHENIX GitHub at line 99 of file SynRadAna.h
References do_TPCHits.
Member Data Documentation
int SynRadAna::_embedding_id private
positive ID is the embedded event of interest, e.g. jetty event from pythia negative IDs are backgrounds, .e.g out of time pile up collisions Usually, ID = 0 means the primary Au+Au collision background
Definition at line 118 of file SynRadAna.h.
View newest version in sPHENIX GitHub at line 118 of file SynRadAna.h
Referenced by get_embedding_id(), process_event(), and set_embedding_id().
std::vector<std::string> SynRadAna::_node_postfix private
Definition at line 128 of file SynRadAna.h.
View newest version in sPHENIX GitHub at line 128 of file SynRadAna.h
Referenced by AddHit(), AddNode(), Init(), and process_event().
std::vector<std::string> SynRadAna::_tower_postfix private
Definition at line 129 of file SynRadAna.h.
View newest version in sPHENIX GitHub at line 129 of file SynRadAna.h
Referenced by AddTower(), and Init().
bool SynRadAna::do_MVTXHits private
Definition at line 123 of file SynRadAna.h.
View newest version in sPHENIX GitHub at line 123 of file SynRadAna.h
Referenced by Init(), isDoMvtxHits(), process_event(), and setDoMvtxHits().
bool SynRadAna::do_photon private
Definition at line 122 of file SynRadAna.h.
View newest version in sPHENIX GitHub at line 122 of file SynRadAna.h
Referenced by Init(), isDoPhoton(), process_event(), and setDoPhoton().
bool SynRadAna::do_TPCHits private
Definition at line 124 of file SynRadAna.h.
View newest version in sPHENIX GitHub at line 124 of file SynRadAna.h
Referenced by Init(), isDoTPCHits(), process_event(), and setDoTPCHits().
double SynRadAna::m_eventWeight private
Definition at line 120 of file SynRadAna.h.
View newest version in sPHENIX GitHub at line 120 of file SynRadAna.h
Referenced by process_event().
std::string SynRadAna::m_outputFIle private
Definition at line 126 of file SynRadAna.h.
View newest version in sPHENIX GitHub at line 126 of file SynRadAna.h
Referenced by End().
The documentation for this class was generated from the following files:
analysis/blob/master/EIC-SynRad/SynRadAna/SynRadAna.h
analysis/blob/master/EIC-SynRad/SynRadAna/SynRadAna.cc