Analysis Software: MyTClonesArray Class Reference
MyTClonesArray Class Reference
#include <tutorials/blob/master/MyOwnTTree/src/MyTClonesArray.h>
Public Member Functions
MyTClonesArray ()
~MyTClonesArray () override
void Reset () override
Clear Event.
MySimpleTree * GetNewItem ()
MySimpleTree * GetItem (const unsigned int i) const
int Entries ()
void MyEventInt (const int i)
int MyEventInt () const
void MyEventFloat (const float f)
float MyEventFloat () const
Public Member Functions inherited from PHObject
PHObject ()
ctor
~PHObject () override
dtor
virtual PHObject * CloneMe () const
Virtual copy constructor.
virtual PHObject * clone () const final
PHObject * Clone (const char *newname="") const final
void Copy (TObject &object) const final
virtual void identify (std::ostream &os=std::cout) const
virtual int isValid () const
isValid returns non zero if object contains vailid data
virtual int Integrate () const
virtual int Integrate (PHObject *)
virtual void CopyFrom (const PHObject *obj)
Private Attributes
int myeventint = 0
float myeventfloat = NAN
TClonesArray * MyTCArray = nullptr
Detailed Description
Definition at line 17 of file MyTClonesArray.h.
View newest version in sPHENIX GitHub at line 17 of file MyTClonesArray.h
Constructor & Destructor Documentation
MyTClonesArray::MyTClonesArray ()
Definition at line 22 of file MyTClonesArray.cc.
View newest version in sPHENIX GitHub at line 22 of file MyTClonesArray.cc
References DEFAULTSIZE, and MyTCArray.
MyTClonesArray::~MyTClonesArray () override
Definition at line 28 of file MyTClonesArray.cc.
View newest version in sPHENIX GitHub at line 28 of file MyTClonesArray.cc
References MyTCArray.
Member Function Documentation
int MyTClonesArray::Entries ()
Definition at line 90 of file MyTClonesArray.cc.
View newest version in sPHENIX GitHub at line 90 of file MyTClonesArray.cc
References MyTCArray.
Referenced by AnalyzeSimpleTree::process_event().
MySimpleTree * MyTClonesArray::GetItem (const unsigned int i) const
Definition at line 76 of file MyTClonesArray.cc.
View newest version in sPHENIX GitHub at line 76 of file MyTClonesArray.cc
References MyTCArray, and PHWHERE.
Referenced by AnalyzeSimpleTree::process_event().
MySimpleTree * MyTClonesArray::GetNewItem ()
Definition at line 59 of file MyTClonesArray.cc.
View newest version in sPHENIX GitHub at line 59 of file MyTClonesArray.cc
References DEFAULTSIZE, and MyTCArray.
Referenced by MakeSimpleTree::process_event().
void MyTClonesArray::MyEventFloat (const float f) inline
Definition at line 29 of file MyTClonesArray.h.
View newest version in sPHENIX GitHub at line 29 of file MyTClonesArray.h
References f, and myeventfloat.
Referenced by MakeSimpleTree::process_event().
float MyTClonesArray::MyEventFloat () const inline
Definition at line 30 of file MyTClonesArray.h.
View newest version in sPHENIX GitHub at line 30 of file MyTClonesArray.h
References myeventfloat.
void MyTClonesArray::MyEventInt (const int i) inline
Definition at line 27 of file MyTClonesArray.h.
View newest version in sPHENIX GitHub at line 27 of file MyTClonesArray.h
References i, and myeventint.
Referenced by MakeSimpleTree::process_event().
int MyTClonesArray::MyEventInt () const inline
Definition at line 28 of file MyTClonesArray.h.
View newest version in sPHENIX GitHub at line 28 of file MyTClonesArray.h
References myeventint.
void MyTClonesArray::Reset () override virtual
Clear Event.
Reimplemented from PHObject.
Definition at line 40 of file MyTClonesArray.cc.
View newest version in sPHENIX GitHub at line 40 of file MyTClonesArray.cc
References DEFAULTSIZE, myeventfloat, myeventint, and MyTCArray.
Member Data Documentation
float MyTClonesArray::myeventfloat = NAN private
Definition at line 34 of file MyTClonesArray.h.
View newest version in sPHENIX GitHub at line 34 of file MyTClonesArray.h
Referenced by MyEventFloat(), and Reset().
int MyTClonesArray::myeventint = 0 private
Definition at line 33 of file MyTClonesArray.h.
View newest version in sPHENIX GitHub at line 33 of file MyTClonesArray.h
Referenced by MyEventInt(), and Reset().
TClonesArray* MyTClonesArray::MyTCArray = nullptr private
Definition at line 35 of file MyTClonesArray.h.
View newest version in sPHENIX GitHub at line 35 of file MyTClonesArray.h
Referenced by Entries(), GetItem(), GetNewItem(), MyTClonesArray(), Reset(), and ~MyTClonesArray().
The documentation for this class was generated from the following files:
tutorials/blob/master/MyOwnTTree/src/MyTClonesArray.h
tutorials/blob/master/MyOwnTTree/src/MyTClonesArray.cc