Analysis Software: Jet Class Reference
Jet Class Reference
#include <coresoftware/blob/master/offline/packages/jetbase/Jet.h>
Classes
struct IterJetTCA
Public Types
enum ALGO { NONE = 0, ANTIKT = 1, KT = 2, CAMBRIDGE = 3 }
enum SRC {
VOID = 0, PARTICLE = 1, TRACK = 2, CEMC_TOWER = 3,
CEMC_CLUSTER = 4, HCALIN_TOWER = 5, HCALIN_CLUSTER = 6, HCALOUT_TOWER = 7,
HCALOUT_CLUSTER = 8, FEMC_TOWER = 9, FEMC_CLUSTER = 10, FHCAL_TOWER = 11,
FHCAL_CLUSTER = 12, CEMC_TOWER_RETOWER = 13, CEMC_TOWER_SUB1 = 14, HCALIN_TOWER_SUB1 = 15,
HCALOUT_TOWER_SUB1 = 16, CEMC_TOWER_SUB1CS = 17, HCALIN_TOWER_SUB1CS = 18, HCALOUT_TOWER_SUB1CS = 19,
HEPMC_IMPORT = 20, HCAL_TOPO_CLUSTER = 21, ECAL_TOPO_CLUSTER = 22, EEMC_TOWER = 23,
EEMC_CLUSTER = 24, CEMC_TOWERINFO = 25, HCALIN_TOWERINFO = 26, HCALOUT_TOWERINFO = 27,
CEMC_TOWERINFO_RETOWER = 28, CEMC_TOWERINFO_SUB1 = 29, HCALIN_TOWERINFO_SUB1 = 30, HCALOUT_TOWERINFO_SUB1 = 31,
CEMC_TOWERINFO_EMBED = 32, CEMC_TOWERINFO_SIM = 33, HCALIN_TOWERINFO_EMBED = 34, HCALIN_TOWERINFO_SIM = 35,
HCALOUT_TOWERINFO_EMBED = 36, HCALOUT_TOWERINFO_SIM = 37, JET_PROBE = 38
}
enum PROPERTY {
prop_JetCharge = 1, prop_BFrac = 2, prop_SeedD = 3, prop_SeedItr = 4,
prop_zg = 5, prop_Rg = 6, prop_mu = 7, prop_gamma = 8,
prop_JetHadronFlavor = 9, prop_JetHadronZT = 10, prop_area = 11, no_property = 12
}
typedef std::pair< Jet::SRC,
unsigned int > TYPE_comp
typedef std::vector< TYPE_comp > TYPE_comp_vec
typedef TYPE_comp_vec::iterator ITER_comp_vec
typedef std::multimap
< Jet::SRC, unsigned int > typ_comp_ids
typedef
typ_comp_ids::const_iterator ConstIter
typedef typ_comp_ids::iterator Iter
Public Member Functions
Jet ()
~Jet () override
void identify (std::ostream &os=std::cout) const override
int isValid () const override
isValid returns non zero if object contains vailid data
PHObject * CloneMe () const override
Virtual copy constructor.
virtual unsigned int get_id () const
virtual void set_id (unsigned int)
virtual float get_px () const
virtual void set_px (float)
virtual float get_py () const
virtual void set_py (float)
virtual float get_pz () const
virtual void set_pz (float)
virtual float get_e () const
virtual void set_e (float)
virtual float get_p () const
virtual float get_pt () const
virtual float get_et () const
virtual float get_eta () const
virtual float get_phi () const
virtual float get_mass () const
virtual float get_mass2 () const
virtual float get_property (Jet::PROPERTY) const
virtual void set_property (Jet::PROPERTY, float)
virtual size_t size_properties () const
virtual void resize_properties (size_t)
virtual std::vector< float > & get_property_vec ()
virtual bool has_property (Jet::PROPERTY) const
virtual void print_property (std::ostream &) const
virtual void clear_comp ()
virtual void insert_comp (Jet::SRC, unsigned int)
virtual void insert_comp (Jet::SRC, unsigned int, bool)
virtual void insert_comp (TYPE_comp_vec &)
virtual void insert_comp (TYPE_comp_vec &, bool)
virtual size_t size_comp () const
virtual size_t num_comp (SRC=Jet::SRC::VOID)
virtual void print_comp (std::ostream &, bool)
virtual std::vector< Jet::SRC > comp_src_vec ()
virtual std::map< Jet::SRC,
size_t > comp_src_sizemap ()
virtual void set_comp_sort_flag (bool=false)
virtual ITER_comp_vec comp_begin ()
virtual ITER_comp_vec comp_begin (Jet::SRC)
virtual ITER_comp_vec comp_end ()
virtual ITER_comp_vec comp_end (Jet::SRC)
virtual TYPE_comp_vec & get_comp_vec ()
virtual bool empty_comp () const
virtual size_t count_comp (Jet::SRC) const
virtual ConstIter begin_comp () const
virtual ConstIter lower_bound_comp (Jet::SRC source) const
virtual ConstIter upper_bound_comp (Jet::SRC source) const
virtual ConstIter find (Jet::SRC source) const
virtual ConstIter end_comp () const
virtual Iter begin_comp ()
virtual Iter lower_bound_comp (Jet::SRC source)
virtual Iter upper_bound_comp (Jet::SRC source)
virtual Iter find (Jet::SRC source)
virtual Iter end_comp ()
virtual size_t erase_comp (Jet::SRC)
virtual void erase_comp (Iter)
virtual void erase_comp (Iter, Iter)
ClassDefOverride (Jet, 1)
Public Member Functions inherited from PHObject
PHObject ()
ctor
~PHObject () override
dtor
virtual PHObject * clone () const final
PHObject * Clone (const char *newname="") const final
void Copy (TObject &object) const final
virtual void Reset ()
Clear Event.
virtual int Integrate () const
virtual int Integrate (PHObject *)
virtual void CopyFrom (const PHObject *obj)
Detailed Description
Definition at line 61 of file Jet.h.
View newest version in sPHENIX GitHub at line 61 of file Jet.h
Member Typedef Documentation
typedef typ_comp_ids::const_iterator Jet::ConstIter
Definition at line 233 of file Jet.h.
View newest version in sPHENIX GitHub at line 233 of file Jet.h
typedef typ_comp_ids::iterator Jet::Iter
Definition at line 234 of file Jet.h.
View newest version in sPHENIX GitHub at line 234 of file Jet.h
typedef TYPE_comp_vec::iterator Jet::ITER_comp_vec
Definition at line 202 of file Jet.h.
View newest version in sPHENIX GitHub at line 202 of file Jet.h
typedef std::multimap<Jet::SRC, unsigned int> Jet::typ_comp_ids
Definition at line 230 of file Jet.h.
View newest version in sPHENIX GitHub at line 230 of file Jet.h
typedef std::pair<Jet::SRC, unsigned int> Jet::TYPE_comp
Definition at line 196 of file Jet.h.
View newest version in sPHENIX GitHub at line 196 of file Jet.h
typedef std::vector<TYPE_comp> Jet::TYPE_comp_vec
Definition at line 201 of file Jet.h.
View newest version in sPHENIX GitHub at line 201 of file Jet.h
Member Enumeration Documentation
enum Jet::ALGO
Enumerator:
NONE
ANTIKT
KT
CAMBRIDGE
Definition at line 66 of file Jet.h.
View newest version in sPHENIX GitHub at line 66 of file Jet.h
enum Jet::PROPERTY
Enumerator:
prop_JetCharge
jet charge
prop_BFrac
b-jet fraction
prop_SeedD
discriminator D = max tower E / average E , used to identify seeds in 1st iteration of UE determination
prop_SeedItr
used to tag as seed jet in 1st or 2nd iteration of UE determination
prop_zg
SoftDrop quantities.
prop_Rg
prop_mu
prop_gamma
photon tag property
prop_JetHadronFlavor
prop_JetHadronZT
prop_area
jet area
no_property
Definition at line 117 of file Jet.h.
View newest version in sPHENIX GitHub at line 117 of file Jet.h
enum Jet::SRC
Enumerator:
VOID
PARTICLE
TRACK
CEMC_TOWER
CEMC_CLUSTER
HCALIN_TOWER
HCALIN_CLUSTER
HCALOUT_TOWER
HCALOUT_CLUSTER
FEMC_TOWER
FEMC_CLUSTER
FHCAL_TOWER
FHCAL_CLUSTER
CEMC_TOWER_RETOWER
CEMC_TOWER_SUB1
HCALIN_TOWER_SUB1
HCALOUT_TOWER_SUB1
CEMC_TOWER_SUB1CS
HCALIN_TOWER_SUB1CS
HCALOUT_TOWER_SUB1CS
HEPMC_IMPORT
HCAL_TOPO_CLUSTER
ECAL_TOPO_CLUSTER
EEMC_TOWER
EEMC_CLUSTER
CEMC_TOWERINFO
HCALIN_TOWERINFO
HCALOUT_TOWERINFO
CEMC_TOWERINFO_RETOWER
CEMC_TOWERINFO_SUB1
HCALIN_TOWERINFO_SUB1
HCALOUT_TOWERINFO_SUB1
CEMC_TOWERINFO_EMBED
CEMC_TOWERINFO_SIM
HCALIN_TOWERINFO_EMBED
HCALIN_TOWERINFO_SIM
HCALOUT_TOWERINFO_EMBED
HCALOUT_TOWERINFO_SIM
JET_PROBE
Definition at line 74 of file Jet.h.
View newest version in sPHENIX GitHub at line 74 of file Jet.h
Constructor & Destructor Documentation
Jet::Jet () inline
Definition at line 148 of file Jet.h.
View newest version in sPHENIX GitHub at line 148 of file Jet.h
Jet::~Jet () inline override
Definition at line 149 of file Jet.h.
View newest version in sPHENIX GitHub at line 149 of file Jet.h
Member Function Documentation
Jet::ConstIter Jet::begin_comp () const virtual
Reimplemented in Jetv2, and Jetv1.
Definition at line 46 of file Jet.cc.
View newest version in sPHENIX GitHub at line 46 of file Jet.cc
References DummyJetMap.
Referenced by LeptoquarksReco::AddJetInformation(), Jetv2::begin_comp(), TreeMaker::CopyAndMakeJets(), TracksInJets::process_event(), JetUnderlyingEvent::process_event(), PhotonJet::process_event(), JetNconstituents::process_event(), jetrtrack::process_event(), and TruthJetTagging::TruthPhotonTagging().
Jet::Iter Jet::begin_comp () virtual
Reimplemented in Jetv2, and Jetv1.
Definition at line 63 of file Jet.cc.
View newest version in sPHENIX GitHub at line 63 of file Jet.cc
References DummyJetMap.
Jet::ClassDefOverride (Jet , 1)
virtual void Jet::clear_comp () inline virtual
Reimplemented in Jetv2, and Jetv1.
Definition at line 207 of file Jet.h.
View newest version in sPHENIX GitHub at line 207 of file Jet.h
Referenced by ResonanceJetTagging::findMCTaggedJets(), and ResonanceJetTagging::findTaggedJets().
PHObject* Jet::CloneMe () const inline override virtual
Virtual copy constructor.
Reimplemented from PHObject.
Reimplemented in Jetv2, and Jetv1.
Definition at line 153 of file Jet.h.
View newest version in sPHENIX GitHub at line 153 of file Jet.h
Jet::ITER_comp_vec Jet::comp_begin () virtual
Reimplemented in Jetv1, and Jetv2.
Definition at line 26 of file Jet.cc.
View newest version in sPHENIX GitHub at line 26 of file Jet.cc
References DummyJetCompVec.
Referenced by Jetv1::comp_begin(), and JetRecoEval::get_energy_contribution().
Jet::ITER_comp_vec Jet::comp_begin (Jet::SRC) virtual
Reimplemented in Jetv1, and Jetv2.
Definition at line 18 of file Jet.cc.
View newest version in sPHENIX GitHub at line 18 of file Jet.cc
References DummyJetCompVec.
Jet::ITER_comp_vec Jet::comp_end () virtual
Reimplemented in Jetv1, and Jetv2.
Definition at line 30 of file Jet.cc.
View newest version in sPHENIX GitHub at line 30 of file Jet.cc
References DummyJetCompVec.
Referenced by Jetv1::comp_end(), and JetRecoEval::get_energy_contribution().
Jet::ITER_comp_vec Jet::comp_end (Jet::SRC) virtual
Reimplemented in Jetv1, and Jetv2.
Definition at line 22 of file Jet.cc.
View newest version in sPHENIX GitHub at line 22 of file Jet.cc
References DummyJetCompVec.
virtual std::map<Jet::SRC, size_t> Jet::comp_src_sizemap () inline virtual
Reimplemented in Jetv1, and Jetv2.
Definition at line 218 of file Jet.h.
View newest version in sPHENIX GitHub at line 218 of file Jet.h
virtual std::vector<Jet::SRC> Jet::comp_src_vec () inline virtual
Reimplemented in Jetv1, and Jetv2.
Definition at line 217 of file Jet.h.
View newest version in sPHENIX GitHub at line 217 of file Jet.h
virtual size_t Jet::count_comp (Jet::SRC) const inline virtual
Reimplemented in Jetv1, and Jetv2.
Definition at line 230 of file Jet.h.
View newest version in sPHENIX GitHub at line 230 of file Jet.h
Referenced by LeptoquarksReco::AddJetInformation().
virtual bool Jet::empty_comp () const inline virtual
Reimplemented in Jetv2, and Jetv1.
Definition at line 229 of file Jet.h.
View newest version in sPHENIX GitHub at line 229 of file Jet.h
Jet::ConstIter Jet::end_comp () const virtual
Reimplemented in Jetv2, and Jetv1.
Definition at line 50 of file Jet.cc.
View newest version in sPHENIX GitHub at line 50 of file Jet.cc
References DummyJetMap.
Referenced by LeptoquarksReco::AddJetInformation(), TreeMaker::CopyAndMakeJets(), Jetv2::end_comp(), TracksInJets::process_event(), JetUnderlyingEvent::process_event(), PhotonJet::process_event(), JetNconstituents::process_event(), jetrtrack::process_event(), and TruthJetTagging::TruthPhotonTagging().
Jet::Iter Jet::end_comp () virtual
Reimplemented in Jetv2, and Jetv1.
Definition at line 66 of file Jet.cc.
View newest version in sPHENIX GitHub at line 66 of file Jet.cc
References DummyJetMap.
virtual size_t Jet::erase_comp (Jet::SRC) inline virtual
Reimplemented in Jetv2, and Jetv1.
Definition at line 248 of file Jet.h.
View newest version in sPHENIX GitHub at line 248 of file Jet.h
virtual void Jet::erase_comp (Iter) inline virtual
Reimplemented in Jetv2, and Jetv1.
Definition at line 249 of file Jet.h.
View newest version in sPHENIX GitHub at line 249 of file Jet.h
virtual void Jet::erase_comp (Iter , Iter) inline virtual
Reimplemented in Jetv2, and Jetv1.
Definition at line 250 of file Jet.h.
View newest version in sPHENIX GitHub at line 250 of file Jet.h
Jet::ConstIter Jet::find (Jet::SRC source) const virtual
Reimplemented in Jetv2, and Jetv1.
Definition at line 54 of file Jet.cc.
View newest version in sPHENIX GitHub at line 54 of file Jet.cc
References DummyJetMap.
Referenced by Jetv2::find().
Jet::Iter Jet::find (Jet::SRC source) virtual
Reimplemented in Jetv2, and Jetv1.
Definition at line 69 of file Jet.cc.
View newest version in sPHENIX GitHub at line 69 of file Jet.cc
References DummyJetMap.
Jet::TYPE_comp_vec & Jet::get_comp_vec () virtual
Reimplemented in Jetv1, and Jetv2.
Definition at line 34 of file Jet.cc.
View newest version in sPHENIX GitHub at line 34 of file Jet.cc
References DummyJetCompVec.
Referenced by JetRecoEval::all_truth_hits(), JetRecoEval::all_truth_particles(), JetTruthEval::all_truth_particles(), JetRecoEval::all_truth_showers(), FastJetAlgoSub::cluster_and_fill(), Jetv1::get_comp_vec(), JetRecoEval::get_energy_contribution(), BuildResonanceJetTaggingTree::loopHFHadronic(), and JetBkgdSub::process_event().
virtual float Jet::get_e () const inline virtual
Reimplemented in Jetv2, and Jetv1.
Definition at line 169 of file Jet.h.
View newest version in sPHENIX GitHub at line 169 of file Jet.h
Referenced by LeptoquarksReco::AddJetInformation(), FastJetAlgoSub::cluster_and_fill(), TreeMaker::CopyAndMakeJets(), JetEvaluator::fillOutputNtuples(), JetEnergies::fillOutputNtuples(), JetProbeInput::get_input(), PhotonJet::GetRecoHadronsAndJets(), PhotonJet::GetRecoHadronsAndJetsAA(), TreeMaker::GetRecoJets(), AnaTutorial::getReconstructedJets(), TreeMaker::GetTruthJets(), AnaTutorial::getTruthJets(), BuildResonanceJetTaggingTree::loopHFHadronic(), TracksInJets::process_event(), TruthPhotonJet::process_event(), PhotonJet::process_event(), JetMultSub::process_event(), JetSeedCount::process_event(), MyJetAnalysis::process_event(), JetValidation::process_event(), QAG4SimulationJet::process_Spectrum(), SoftLeptonTaggingTruth::process_Spectrum(), and QAG4SimulationJet::process_TruthMatching().
virtual float Jet::get_et () const inline virtual
Reimplemented in Jetv2, and Jetv1.
Definition at line 174 of file Jet.h.
View newest version in sPHENIX GitHub at line 174 of file Jet.h
Referenced by LeptoquarksReco::AddJetInformation(), JetHepMCLoader::process_event(), QAG4SimulationJet::process_Spectrum(), SoftLeptonTaggingTruth::process_Spectrum(), and QAG4SimulationJet::process_TruthMatching().
virtual float Jet::get_eta () const inline virtual
Reimplemented in Jetv2, and Jetv1.
Definition at line 175 of file Jet.h.
View newest version in sPHENIX GitHub at line 175 of file Jet.h
Referenced by LeptoquarksReco::AddJetInformation(), TreeMaker::CopyAndMakeJets(), JetMultSub::EstimateRho(), JetEvaluator::fillOutputNtuples(), JetEnergies::fillOutputNtuples(), RandomConeAna::get_leading_jet_eta_phi(), PhotonJet::GetRecoHadronsAndJets(), PhotonJet::GetRecoHadronsAndJetsAA(), TreeMaker::GetRecoJets(), AnaTutorial::getReconstructedJets(), TreeMaker::GetTruthJets(), AnaTutorial::getTruthJets(), TruthJetTagging::hadron_tagging(), HFJetTruthTrigger::hadron_tagging(), QAG4SimulationJet::jet_acceptance_cut(), SoftLeptonTaggingTruth::jet_acceptance_cut(), JetProbeInput::JetProbeInput(), BuildResonanceJetTaggingTree::loopHFHadronic(), HFJetTruthTrigger::parton_tagging(), TracksInJets::process_event(), HFJetTruthTrigger::process_event(), BJetModule::process_event(), TruthPhotonJet::process_event(), PhotonJet::process_event(), JetMultSub::process_event(), JetHepMCLoader::process_event(), JetNconstituents::process_event(), jetrtrack::process_event(), analysis::process_event(), BDiJetModule::process_event(), MyJetAnalysis::process_event(), JetBkgdSub::process_event(), JetKinematicCheck::process_event(), JetValidation::process_event(), QAG4SimulationJet::process_Spectrum(), SoftLeptonTaggingTruth::process_Spectrum(), and QAG4SimulationJet::process_TruthMatching().
virtual unsigned int Jet::get_id () const inline virtual
Reimplemented in Jetv2, and Jetv1.
Definition at line 157 of file Jet.h.
View newest version in sPHENIX GitHub at line 157 of file Jet.h
Referenced by JetRecoEval::all_jets_from(), JetMultSub::EstimateRho(), JetEvaluator::fillOutputNtuples(), JetEnergies::fillOutputNtuples(), PhotonJet::GetRecoHadronsAndJets(), PhotonJet::GetRecoHadronsAndJetsAA(), AnaTutorial::getReconstructedJets(), AnaTutorial::getTruthJets(), JetMapv1::JetMapv1(), BuildResonanceJetTaggingTree::loopHFHadronic(), JetMapv1::operator=(), PhotonJet::process_event(), BDiJetModule::process_event(), JetValidation::process_event(), JetRecoEval::unique_reco_jet_from_truth(), and JetRecoEval::unique_truth_jet_from_reco().
virtual float Jet::get_mass () const inline virtual
Reimplemented in Jetv2, and Jetv1.
Definition at line 177 of file Jet.h.
View newest version in sPHENIX GitHub at line 177 of file Jet.h
Referenced by LeptoquarksReco::AddJetInformation(), PhotonJet::GetRecoHadronsAndJets(), PhotonJet::GetRecoHadronsAndJetsAA(), BuildResonanceJetTaggingTree::loopHFHadronic(), TruthPhotonJet::process_event(), PhotonJet::process_event(), QAG4SimulationJet::process_Spectrum(), and SoftLeptonTaggingTruth::process_Spectrum().
virtual float Jet::get_mass2 () const inline virtual
Reimplemented in Jetv2, and Jetv1.
Definition at line 178 of file Jet.h.
View newest version in sPHENIX GitHub at line 178 of file Jet.h
virtual float Jet::get_p () const inline virtual
Reimplemented in Jetv2, and Jetv1.
Definition at line 172 of file Jet.h.
View newest version in sPHENIX GitHub at line 172 of file Jet.h
Referenced by LeptoquarksReco::AddJetInformation(), PhotonJet::GetRecoHadronsAndJets(), PhotonJet::GetRecoHadronsAndJetsAA(), AnaTutorial::getReconstructedJets(), AnaTutorial::getTruthJets(), TruthPhotonJet::process_event(), and PhotonJet::process_event().
virtual float Jet::get_phi () const inline virtual
Reimplemented in Jetv2, and Jetv1.
Definition at line 176 of file Jet.h.
View newest version in sPHENIX GitHub at line 176 of file Jet.h
Referenced by LeptoquarksReco::AddJetInformation(), TreeMaker::CopyAndMakeJets(), JetEvaluator::fillOutputNtuples(), JetEnergies::fillOutputNtuples(), RandomConeAna::get_leading_jet_eta_phi(), PhotonJet::GetRecoHadronsAndJets(), PhotonJet::GetRecoHadronsAndJetsAA(), TreeMaker::GetRecoJets(), AnaTutorial::getReconstructedJets(), TreeMaker::GetTruthJets(), AnaTutorial::getTruthJets(), TruthJetTagging::hadron_tagging(), HFJetTruthTrigger::hadron_tagging(), JetProbeInput::JetProbeInput(), BuildResonanceJetTaggingTree::loopHFHadronic(), HFJetTruthTrigger::parton_tagging(), TracksInJets::process_event(), BJetModule::process_event(), TruthPhotonJet::process_event(), PhotonJet::process_event(), JetMultSub::process_event(), analysis::process_event(), jetrtrack::process_event(), BDiJetModule::process_event(), MyJetAnalysis::process_event(), JetBkgdSub::process_event(), JetKinematicCheck::process_event(), JetValidation::process_event(), QAG4SimulationJet::process_Spectrum(), SoftLeptonTaggingTruth::process_Spectrum(), and QAG4SimulationJet::process_TruthMatching().
virtual float Jet::get_property (Jet::PROPERTY) const inline virtual
Reimplemented in Jetv2, and Jetv1.
Definition at line 184 of file Jet.h.
View newest version in sPHENIX GitHub at line 184 of file Jet.h
Referenced by BJetModule::process_event(), JetSeedCount::process_event(), and BDiJetModule::process_event().
std::vector< float > & Jet::get_property_vec () virtual
Reimplemented in Jetv1, and Jetv2.
Definition at line 12 of file Jet.cc.
View newest version in sPHENIX GitHub at line 12 of file Jet.cc
References DummyJetPropVec.
virtual float Jet::get_pt () const inline virtual
Reimplemented in Jetv2, and Jetv1.
Definition at line 173 of file Jet.h.
View newest version in sPHENIX GitHub at line 173 of file Jet.h
Referenced by LeptoquarksReco::AddJetInformation(), TreeMaker::CopyAndMakeJets(), JetMultSub::EstimateRho(), JetEvaluator::fillOutputNtuples(), JetEnergies::fillOutputNtuples(), RandomConeAna::get_leading_jet_eta_phi(), PhotonJet::GetRecoHadronsAndJets(), PhotonJet::GetRecoHadronsAndJetsAA(), TreeMaker::GetRecoJets(), AnaTutorial::getReconstructedJets(), TreeMaker::GetTruthJets(), AnaTutorial::getTruthJets(), TruthJetTagging::hadron_tagging(), HFJetTruthTrigger::hadron_tagging(), JetProbeInput::JetProbeInput(), JetBkgdSub::LeadingR04TruthJet(), RandomConeAna::LeadingR04TruthJet(), BuildResonanceJetTaggingTree::loopHFHadronic(), HFJetTruthTrigger::parton_tagging(), TracksInJets::process_event(), HFJetTruthTrigger::process_event(), BJetModule::process_event(), TruthPhotonJet::process_event(), JetUnderlyingEvent::process_event(), PhotonJet::process_event(), JetMultSub::process_event(), JetNconstituents::process_event(), analysis::process_event(), jetrtrack::process_event(), BDiJetModule::process_event(), MyJetAnalysis::process_event(), JetBkgdSub::process_event(), JetKinematicCheck::process_event(), JetValidation::process_event(), and TruthJetTagging::TruthPhotonTagging().
virtual float Jet::get_px () const inline virtual
Reimplemented in Jetv2, and Jetv1.
Definition at line 160 of file Jet.h.
View newest version in sPHENIX GitHub at line 160 of file Jet.h
Referenced by FastJetAlgoSub::cluster_and_fill(), TreeMaker::CopyAndMakeJets(), JetProbeInput::get_input(), PhotonJet::GetRecoHadronsAndJets(), PhotonJet::GetRecoHadronsAndJetsAA(), AnaTutorial::getReconstructedJets(), AnaTutorial::getTruthJets(), BuildResonanceJetTaggingTree::loopHFHadronic(), TracksInJets::process_event(), TruthPhotonJet::process_event(), PhotonJet::process_event(), JetMultSub::process_event(), MyJetAnalysis::process_event(), and SoftLeptonTaggingTruth::process_Spectrum().
virtual float Jet::get_py () const inline virtual
Reimplemented in Jetv2, and Jetv1.
Definition at line 163 of file Jet.h.
View newest version in sPHENIX GitHub at line 163 of file Jet.h
Referenced by FastJetAlgoSub::cluster_and_fill(), TreeMaker::CopyAndMakeJets(), JetProbeInput::get_input(), PhotonJet::GetRecoHadronsAndJets(), PhotonJet::GetRecoHadronsAndJetsAA(), AnaTutorial::getReconstructedJets(), AnaTutorial::getTruthJets(), BuildResonanceJetTaggingTree::loopHFHadronic(), TracksInJets::process_event(), TruthPhotonJet::process_event(), PhotonJet::process_event(), JetMultSub::process_event(), MyJetAnalysis::process_event(), and SoftLeptonTaggingTruth::process_Spectrum().
virtual float Jet::get_pz () const inline virtual
Reimplemented in Jetv2, and Jetv1.
Definition at line 166 of file Jet.h.
View newest version in sPHENIX GitHub at line 166 of file Jet.h
Referenced by FastJetAlgoSub::cluster_and_fill(), TreeMaker::CopyAndMakeJets(), JetProbeInput::get_input(), PhotonJet::GetRecoHadronsAndJets(), PhotonJet::GetRecoHadronsAndJetsAA(), AnaTutorial::getReconstructedJets(), AnaTutorial::getTruthJets(), BuildResonanceJetTaggingTree::loopHFHadronic(), TracksInJets::process_event(), TruthPhotonJet::process_event(), PhotonJet::process_event(), JetMultSub::process_event(), MyJetAnalysis::process_event(), and SoftLeptonTaggingTruth::process_Spectrum().
virtual bool Jet::has_property (Jet::PROPERTY) const inline virtual
Reimplemented in Jetv2, and Jetv1.
Definition at line 195 of file Jet.h.
View newest version in sPHENIX GitHub at line 195 of file Jet.h
Referenced by BDiJetModule::process_event().
void Jet::identify (std::ostream & os = std::cout) const override virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from PHObject.
Reimplemented in Jetv2, and Jetv1.
Definition at line 39 of file Jet.cc.
View newest version in sPHENIX GitHub at line 39 of file Jet.cc
Referenced by HFJetTruthTrigger::process_event(), QAG4SimulationJet::process_Spectrum(), SoftLeptonTaggingTruth::process_Spectrum(), and QAG4SimulationJet::process_TruthMatching().
virtual void Jet::insert_comp (Jet::SRC , unsigned int) inline virtual
Reimplemented in Jetv1, and Jetv2.
Definition at line 208 of file Jet.h.
View newest version in sPHENIX GitHub at line 208 of file Jet.h
Referenced by ResonanceJetTagging::findMCTaggedJets(), ResonanceJetTagging::findTaggedJets(), TrackJetInput::get_input(), TowerJetInput::get_input(), ParticleFlowJetInput::get_input(), ClusterJetInput::get_input(), TruthJetInput::get_input(), and JetHepMCLoader::process_event().
virtual void Jet::insert_comp (Jet::SRC , unsigned int , bool) inline virtual
Reimplemented in Jetv1, and Jetv2.
Definition at line 209 of file Jet.h.
View newest version in sPHENIX GitHub at line 209 of file Jet.h
virtual void Jet::insert_comp (TYPE_comp_vec &) inline virtual
Reimplemented in Jetv1, and Jetv2.
Definition at line 210 of file Jet.h.
View newest version in sPHENIX GitHub at line 210 of file Jet.h
virtual void Jet::insert_comp (TYPE_comp_vec & , bool) inline virtual
Reimplemented in Jetv1, and Jetv2.
Definition at line 211 of file Jet.h.
View newest version in sPHENIX GitHub at line 211 of file Jet.h
int Jet::isValid () const inline override virtual
isValid returns non zero if object contains vailid data
Reimplemented from PHObject.
Reimplemented in Jetv2, and Jetv1.
Definition at line 152 of file Jet.h.
View newest version in sPHENIX GitHub at line 152 of file Jet.h
Jet::ConstIter Jet::lower_bound_comp (Jet::SRC source) const virtual
Reimplemented in Jetv2, and Jetv1.
Definition at line 57 of file Jet.cc.
View newest version in sPHENIX GitHub at line 57 of file Jet.cc
References DummyJetMap.
Referenced by Jetv2::lower_bound_comp().
Jet::Iter Jet::lower_bound_comp (Jet::SRC source) virtual
Reimplemented in Jetv2, and Jetv1.
Definition at line 72 of file Jet.cc.
View newest version in sPHENIX GitHub at line 72 of file Jet.cc
References DummyJetMap.
virtual size_t Jet::num_comp (SRC = Jet::SRC::VOID) inline virtual
Reimplemented in Jetv1, and Jetv2.
Definition at line 215 of file Jet.h.
View newest version in sPHENIX GitHub at line 215 of file Jet.h
virtual void Jet::print_comp (std::ostream & , bool) inline virtual
Reimplemented in Jetv1, and Jetv2.
Definition at line 216 of file Jet.h.
View newest version in sPHENIX GitHub at line 216 of file Jet.h
virtual void Jet::print_property (std::ostream &) const inline virtual
Reimplemented in Jetv2, and Jetv1.
Definition at line 196 of file Jet.h.
View newest version in sPHENIX GitHub at line 196 of file Jet.h
virtual void Jet::resize_properties (size_t) inline virtual
Reimplemented in Jetv1, and Jetv2.
Definition at line 189 of file Jet.h.
View newest version in sPHENIX GitHub at line 189 of file Jet.h
virtual void Jet::set_comp_sort_flag (bool = false) inline virtual
Reimplemented in Jetv1, and Jetv2.
Definition at line 219 of file Jet.h.
View newest version in sPHENIX GitHub at line 219 of file Jet.h
virtual void Jet::set_e (float) inline virtual
Reimplemented in Jetv2, and Jetv1.
Definition at line 170 of file Jet.h.
View newest version in sPHENIX GitHub at line 170 of file Jet.h
Referenced by TreeMaker::CopyAndMakeJets(), ResonanceJetTagging::findMCTaggedJets(), ResonanceJetTagging::findTaggedJets(), TrackJetInput::get_input(), TowerJetInput::get_input(), ParticleFlowJetInput::get_input(), JetProbeInput::get_input(), ClusterJetInput::get_input(), TruthJetInput::get_input(), JetUnderlyingEvent::process_event(), JetMultSub::process_event(), JetHepMCLoader::process_event(), and JetBkgdSub::process_event().
virtual void Jet::set_id (unsigned int) inline virtual
Reimplemented in Jetv2, and Jetv1.
Definition at line 158 of file Jet.h.
View newest version in sPHENIX GitHub at line 158 of file Jet.h
Referenced by TreeMaker::CopyAndMakeJets(), ResonanceJetTagging::findMCTaggedJets(), and ResonanceJetTagging::findTaggedJets().
virtual void Jet::set_property (Jet::PROPERTY , float) inline virtual
Reimplemented in Jetv2, and Jetv1.
Definition at line 185 of file Jet.h.
View newest version in sPHENIX GitHub at line 185 of file Jet.h
Referenced by TruthJetTagging::hadron_tagging(), HFJetTruthTrigger::hadron_tagging(), HFJetTruthTrigger::parton_tagging(), and TruthJetTagging::process_event().
virtual void Jet::set_px (float) inline virtual
Reimplemented in Jetv2, and Jetv1.
Definition at line 161 of file Jet.h.
View newest version in sPHENIX GitHub at line 161 of file Jet.h
Referenced by FastJetAlgo::cluster_and_fill(), TreeMaker::CopyAndMakeJets(), ResonanceJetTagging::findMCTaggedJets(), ResonanceJetTagging::findTaggedJets(), TrackJetInput::get_input(), TowerJetInput::get_input(), JetProbeInput::get_input(), ParticleFlowJetInput::get_input(), ClusterJetInput::get_input(), TruthJetInput::get_input(), CopyAndSubtractJets::process_event(), JetUnderlyingEvent::process_event(), JetMultSub::process_event(), JetHepMCLoader::process_event(), and JetBkgdSub::process_event().
virtual void Jet::set_py (float) inline virtual
Reimplemented in Jetv2, and Jetv1.
Definition at line 164 of file Jet.h.
View newest version in sPHENIX GitHub at line 164 of file Jet.h
Referenced by TreeMaker::CopyAndMakeJets(), ResonanceJetTagging::findMCTaggedJets(), ResonanceJetTagging::findTaggedJets(), TrackJetInput::get_input(), TowerJetInput::get_input(), ParticleFlowJetInput::get_input(), JetProbeInput::get_input(), ClusterJetInput::get_input(), TruthJetInput::get_input(), JetUnderlyingEvent::process_event(), JetMultSub::process_event(), JetHepMCLoader::process_event(), and JetBkgdSub::process_event().
virtual void Jet::set_pz (float) inline virtual
Reimplemented in Jetv2, and Jetv1.
Definition at line 167 of file Jet.h.
View newest version in sPHENIX GitHub at line 167 of file Jet.h
Referenced by TreeMaker::CopyAndMakeJets(), ResonanceJetTagging::findMCTaggedJets(), ResonanceJetTagging::findTaggedJets(), TrackJetInput::get_input(), TowerJetInput::get_input(), ParticleFlowJetInput::get_input(), JetProbeInput::get_input(), ClusterJetInput::get_input(), TruthJetInput::get_input(), JetUnderlyingEvent::process_event(), JetMultSub::process_event(), JetHepMCLoader::process_event(), and JetBkgdSub::process_event().
virtual size_t Jet::size_comp () const inline virtual
Reimplemented in Jetv2, and Jetv1.
Definition at line 213 of file Jet.h.
View newest version in sPHENIX GitHub at line 213 of file Jet.h
Referenced by LeptoquarksReco::AddJetInformation(), JetMultSub::EstimateRho(), JetEvaluator::fillOutputNtuples(), JetEnergies::fillOutputNtuples(), TracksInJets::process_event(), JetMultSub::process_event(), JetNconstituents::process_event(), BDiJetModule::process_event(), MyJetAnalysis::process_event(), JetBkgdSub::process_event(), JetValidation::process_event(), QAG4SimulationJet::process_Spectrum(), and SoftLeptonTaggingTruth::process_Spectrum().
virtual size_t Jet::size_properties () const inline virtual
Reimplemented in Jetv1, and Jetv2.
Definition at line 186 of file Jet.h.
View newest version in sPHENIX GitHub at line 186 of file Jet.h
Jet::ConstIter Jet::upper_bound_comp (Jet::SRC source) const virtual
Reimplemented in Jetv2, and Jetv1.
Definition at line 60 of file Jet.cc.
View newest version in sPHENIX GitHub at line 60 of file Jet.cc
References DummyJetMap.
Referenced by Jetv2::upper_bound_comp().
Jet::Iter Jet::upper_bound_comp (Jet::SRC source) virtual
Reimplemented in Jetv2, and Jetv1.
Definition at line 75 of file Jet.cc.
View newest version in sPHENIX GitHub at line 75 of file Jet.cc
References DummyJetMap.
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/jetbase/Jet.h
coresoftware/blob/master/offline/packages/jetbase/Jet.cc