Analysis Software: RawHitSetv1 Class Reference
RawHitSetv1 Class Reference
#include <coresoftware/blob/master/offline/packages/trackbase/RawHitSetv1.h>
Public Member Functions
RawHitSetv1 ()=default
~RawHitSetv1 () override
void identify (std::ostream &os=std::cout) const override
TObject functions.
void Reset () override
Clear Event.
void setHitSetKey (const TrkrDefs::hitsetkey key) override
Set the key for this object.
TrkrDefs::hitsetkey getHitSetKey () const override
Get the key for this object.
void addHit (RawHit *) override
Add a hit to this container using a specific key.
void setTpcPhiBins (unsigned short phibins) override
{
ConstRange getHits () const override
Remove a hit using its key.
unsigned int size () const override
Get the number of hits stored.
unsigned int tpcphibins () const override
Public Attributes
VectorTpc2D m_tpchits
Private Member Functions
ClassDefOverride (RawHitSetv1, 1)
Private Attributes
TrkrDefs::hitsetkey m_hitSetKey = TrkrDefs::HITSETKEYMAX
unique key for this object
Vector m_hits
storage for RawHit objects
Additional Inherited Members
Public Types inherited from RawHitSet
using Vector = std::vector< RawHit * >
using VectorTpc2D = std::vector< std::vector< uint8_t >>
using ConstIterator = Vector::const_iterator
using ConstRange = std::pair< ConstIterator, ConstIterator >
Protected Member Functions inherited from RawHitSet
RawHitSet ()=default
ctor, not to be called
Detailed Description
Definition at line 20 of file RawHitSetv1.h.
View newest version in sPHENIX GitHub at line 20 of file RawHitSetv1.h
Constructor & Destructor Documentation
RawHitSetv1::RawHitSetv1 () default
RawHitSetv1::~RawHitSetv1 () inline override
Definition at line 25 of file RawHitSetv1.h.
View newest version in sPHENIX GitHub at line 25 of file RawHitSetv1.h
References Reset().
Member Function Documentation
void RawHitSetv1::addHit (RawHit *) override virtual
Add a hit to this container using a specific key.
Parameters
[in] key Hit key
[in] hit Hit to be added.
NOTE: This RawHitSet takes ownership of the passed RawHit pointer and will delete it in the Reset() method.
Reimplemented from RawHitSet.
Definition at line 38 of file RawHitSetv1.cc.
View newest version in sPHENIX GitHub at line 38 of file RawHitSetv1.cc
References m_hits.
Referenced by TpcRawWriter::process_event().
RawHitSetv1::ClassDefOverride (RawHitSetv1 , 1) private
RawHitSetv1::ConstRange RawHitSetv1::getHits () const override virtual
Remove a hit using its key.
Parameters
[in] key to be removed Get a specific hit based on its index.
key of the desired hit
[out] Pointer to the desired hit. nullptr if no hit.
Get a desired hit based on its key. Get all hits
Parameters
[out] Pair of iterator to vector begin and end
Reimplemented from RawHitSet.
Definition at line 62 of file RawHitSetv1.cc.
View newest version in sPHENIX GitHub at line 62 of file RawHitSetv1.cc
References m_hits.
TrkrDefs::hitsetkey RawHitSetv1::getHitSetKey () const inline override virtual
Get the key for this object.
Parameters
[out] object key
Reimplemented from RawHitSet.
Definition at line 39 of file RawHitSetv1.h.
View newest version in sPHENIX GitHub at line 39 of file RawHitSetv1.h
References m_hitSetKey.
Referenced by identify().
void RawHitSetv1::identify (std::ostream & = std::cout) const override virtual
TObject functions.
Reimplemented from RawHitSet.
Definition at line 24 of file RawHitSetv1.cc.
View newest version in sPHENIX GitHub at line 24 of file RawHitSetv1.cc
References getHitSetKey(), TrkrDefs::getLayer(), TrkrDefs::getTrkrId(), layer, m_hits, and m_hitSetKey.
void RawHitSetv1::Reset () override virtual
Clear Event.
Reimplemented from RawHitSet.
Definition at line 14 of file RawHitSetv1.cc.
View newest version in sPHENIX GitHub at line 14 of file RawHitSetv1.cc
References m_hits, and m_hitSetKey.
Referenced by ~RawHitSetv1().
void RawHitSetv1::setHitSetKey (const TrkrDefs::hitsetkey) inline override virtual
Set the key for this object.
Parameters
key
Reimplemented from RawHitSet.
Definition at line 34 of file RawHitSetv1.h.
View newest version in sPHENIX GitHub at line 34 of file RawHitSetv1.h
References m_hitSetKey.
void RawHitSetv1::setTpcPhiBins (unsigned short phibins) override virtual
{
Reimplemented from RawHitSet.
Definition at line 48 of file RawHitSetv1.cc.
View newest version in sPHENIX GitHub at line 48 of file RawHitSetv1.cc
References m_tpchits.
Referenced by TpcRawWriter::process_event().
unsigned int RawHitSetv1::size (void) const inline override virtual
Get the number of hits stored.
Parameters
[out] number of hits
Reimplemented from RawHitSet.
Definition at line 54 of file RawHitSetv1.h.
View newest version in sPHENIX GitHub at line 54 of file RawHitSetv1.h
References m_hits.
unsigned int RawHitSetv1::tpcphibins () const inline override virtual
Reimplemented from RawHitSet.
Definition at line 58 of file RawHitSetv1.h.
View newest version in sPHENIX GitHub at line 58 of file RawHitSetv1.h
References m_tpchits.
Member Data Documentation
Vector RawHitSetv1::m_hits private
storage for RawHit objects
Definition at line 69 of file RawHitSetv1.h.
View newest version in sPHENIX GitHub at line 69 of file RawHitSetv1.h
Referenced by addHit(), getHits(), identify(), Reset(), and size().
TrkrDefs::hitsetkey RawHitSetv1::m_hitSetKey = TrkrDefs::HITSETKEYMAX private
unique key for this object
Definition at line 66 of file RawHitSetv1.h.
View newest version in sPHENIX GitHub at line 66 of file RawHitSetv1.h
Referenced by getHitSetKey(), identify(), Reset(), and setHitSetKey().
VectorTpc2D RawHitSetv1::m_tpchits
Definition at line 62 of file RawHitSetv1.h.
View newest version in sPHENIX GitHub at line 62 of file RawHitSetv1.h
Referenced by TpcRawWriter::process_event(), setTpcPhiBins(), and tpcphibins().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/trackbase/RawHitSetv1.h
coresoftware/blob/master/offline/packages/trackbase/RawHitSetv1.cc