Analysis Software: TSQLImportClient Class Reference
TSQLImportClient Class Reference
#include <RDBC/blob/master/include/RDBC/TSQLImportClient.h>
Public Member Functions
TSQLImportClient (const TString &url)
virtual ~TSQLImportClient ()
virtual TString GetLocal ()
virtual TString GetTableName ()
virtual TString GetColumns ()
virtual TString GetLocalFile ()
virtual Bool_t IsValid ()
Int_t GetSkipLines () const
Int_t GetStatus () const
TSQLException * GetException () const
Protected Member Functions
virtual Int_t Init ()
virtual void GET (const TString &url)
virtual void Clean ()
Protected Attributes
TSQLUrl * fUrl
TString fLocalFile
TString fTableName
TString fColumns
Int_t fStatus
Int_t fSkipLines
Private Attributes
Bool_t fMustDeleteLocalFile
TSQLException * fException
Friends
class TSQLImporter
Detailed Description
Definition at line 20 of file TSQLImportClient.h.
View newest version in sPHENIX GitHub at line 20 of file TSQLImportClient.h
Constructor & Destructor Documentation
TSQLImportClient::TSQLImportClient (const TString & url)
Definition at line 22 of file TSQLImportClient.cxx.
View newest version in sPHENIX GitHub at line 22 of file TSQLImportClient.cxx
References fException, fLocalFile, fMustDeleteLocalFile, fSkipLines, fStatus, fUrl, GET(), TSQLUrl::GetFile(), TSQLUrl::GetHost(), and str.
TSQLImportClient::~TSQLImportClient () virtual
Definition at line 45 of file TSQLImportClient.cxx.
View newest version in sPHENIX GitHub at line 45 of file TSQLImportClient.cxx
References Clean().
Member Function Documentation
void TSQLImportClient::Clean () protected virtual
Definition at line 53 of file TSQLImportClient.cxx.
View newest version in sPHENIX GitHub at line 53 of file TSQLImportClient.cxx
References fException, fLocalFile, fMustDeleteLocalFile, and fUrl.
Referenced by ~TSQLImportClient().
void TSQLImportClient::GET (const TString & url) protected virtual
Definition at line 99 of file TSQLImportClient.cxx.
View newest version in sPHENIX GitHub at line 99 of file TSQLImportClient.cxx
References fclose(), fd, filename, fLocalFile, fStatus, HTTP_FORBIDDEN, ambiguity_solver_full_chain::idx, TauVsDIS_MachineLearning_Differentiation::msg, physmon_simulation::s, str, physmon_ckf_tracking::u, and summary::url.
Referenced by TSQLImportClient().
virtual TString TSQLImportClient::GetColumns () inline virtual
Definition at line 46 of file TSQLImportClient.h.
View newest version in sPHENIX GitHub at line 46 of file TSQLImportClient.h
References fColumns.
Referenced by TSQLImporter::LoadTable().
TSQLException* TSQLImportClient::GetException () const inline
Definition at line 52 of file TSQLImportClient.h.
View newest version in sPHENIX GitHub at line 52 of file TSQLImportClient.h
References fException.
Referenced by TSQLImporter::LoadTable().
virtual TString TSQLImportClient::GetLocal () inline virtual
Definition at line 44 of file TSQLImportClient.h.
View newest version in sPHENIX GitHub at line 44 of file TSQLImportClient.h
References fLocalFile.
Referenced by TSQLImporter::LoadTable().
virtual TString TSQLImportClient::GetLocalFile () inline virtual
Definition at line 47 of file TSQLImportClient.h.
View newest version in sPHENIX GitHub at line 47 of file TSQLImportClient.h
References fLocalFile.
Referenced by TSQLImporter::LoadTable().
Int_t TSQLImportClient::GetSkipLines () const inline
Definition at line 50 of file TSQLImportClient.h.
View newest version in sPHENIX GitHub at line 50 of file TSQLImportClient.h
References fSkipLines.
Referenced by TSQLImporter::LoadTable().
Int_t TSQLImportClient::GetStatus () const inline
Definition at line 51 of file TSQLImportClient.h.
View newest version in sPHENIX GitHub at line 51 of file TSQLImportClient.h
References fStatus.
Referenced by TSQLImporter::LoadTable().
virtual TString TSQLImportClient::GetTableName () inline virtual
Definition at line 45 of file TSQLImportClient.h.
View newest version in sPHENIX GitHub at line 45 of file TSQLImportClient.h
References fTableName.
Referenced by TSQLImporter::LoadCatalog(), and TSQLImporter::LoadTable().
Int_t TSQLImportClient::Init () protected virtual
Definition at line 145 of file TSQLImportClient.cxx.
View newest version in sPHENIX GitHub at line 145 of file TSQLImportClient.cxx
References fclose(), fColumns, fd, fException, fLocalFile, fSkipLines, fStatus, fTableName, HTTP_FORBIDDEN, HTTP_NOT_ACCEPTABLE, HTTP_NOT_FOUND, HTTP_OK, i, k, str, Acts::Test::tmp(), and Validate().
Referenced by TSQLImporter::LoadTable().
virtual Bool_t TSQLImportClient::IsValid () inline virtual
Definition at line 48 of file TSQLImportClient.h.
View newest version in sPHENIX GitHub at line 48 of file TSQLImportClient.h
References fStatus.
Referenced by TSQLImporter::LoadTable().
Friends And Related Function Documentation
friend class TSQLImporter friend
Definition at line 22 of file TSQLImportClient.h.
View newest version in sPHENIX GitHub at line 22 of file TSQLImportClient.h
Member Data Documentation
TString TSQLImportClient::fColumns protected
Definition at line 32 of file TSQLImportClient.h.
View newest version in sPHENIX GitHub at line 32 of file TSQLImportClient.h
Referenced by GetColumns(), and Init().
TSQLException* TSQLImportClient::fException private
Definition at line 26 of file TSQLImportClient.h.
View newest version in sPHENIX GitHub at line 26 of file TSQLImportClient.h
Referenced by Clean(), GetException(), Init(), and TSQLImportClient().
TString TSQLImportClient::fLocalFile protected
Definition at line 30 of file TSQLImportClient.h.
View newest version in sPHENIX GitHub at line 30 of file TSQLImportClient.h
Referenced by Clean(), GET(), GetLocal(), GetLocalFile(), Init(), and TSQLImportClient().
Bool_t TSQLImportClient::fMustDeleteLocalFile private
Definition at line 25 of file TSQLImportClient.h.
View newest version in sPHENIX GitHub at line 25 of file TSQLImportClient.h
Referenced by Clean(), and TSQLImportClient().
Int_t TSQLImportClient::fSkipLines protected
Definition at line 34 of file TSQLImportClient.h.
View newest version in sPHENIX GitHub at line 34 of file TSQLImportClient.h
Referenced by GetSkipLines(), Init(), and TSQLImportClient().
Int_t TSQLImportClient::fStatus protected
Definition at line 33 of file TSQLImportClient.h.
View newest version in sPHENIX GitHub at line 33 of file TSQLImportClient.h
Referenced by GET(), GetStatus(), Init(), IsValid(), and TSQLImportClient().
TString TSQLImportClient::fTableName protected
Definition at line 31 of file TSQLImportClient.h.
View newest version in sPHENIX GitHub at line 31 of file TSQLImportClient.h
Referenced by GetTableName(), and Init().
TSQLUrl* TSQLImportClient::fUrl protected
Definition at line 29 of file TSQLImportClient.h.
View newest version in sPHENIX GitHub at line 29 of file TSQLImportClient.h
Referenced by Clean(), and TSQLImportClient().
The documentation for this class was generated from the following files:
RDBC/blob/master/include/RDBC/TSQLImportClient.h
RDBC/blob/master/rdbc/TSQLImportClient.cxx