Analysis Software: cpp.ast Namespace Reference
cpp.ast Namespace Reference
Classes
class _NullDict
class Node
class Define
class Include
class Goto
class Expr
class Return
class Delete
class Friend
class Using
class Parameter
class _GenericDeclaration
class VariableDeclaration
class Typedef
class _NestedType
class Union
class Enum
class Class
class Struct
class Function
class Method
class Type
class TypeConverter
class AstBuilder
Functions
def reversed
def next
def BuilderFromSource
def PrintIndentifiers
def PrintAllIndentifiers
def main
Variables
string __author__ 'nnorwitz@google.com (Neal Norwitz)'
int FUNCTION_NONE 0x00
int FUNCTION_CONST 0x01
int FUNCTION_VIRTUAL 0x02
int FUNCTION_PURE_VIRTUAL 0x04
int FUNCTION_CTOR 0x08
int FUNCTION_DTOR 0x10
int FUNCTION_ATTRIBUTE 0x20
int FUNCTION_UNKNOWN_ANNOTATION 0x40
int FUNCTION_THROW 0x80
int FUNCTION_OVERRIDE 0x100
string _INTERNAL_TOKEN 'internal'
string _NAMESPACE_POP 'ns-pop'
Function Documentation
def cpp.ast.BuilderFromSource (source, filename)
Utility method that returns an AstBuilder from source code.
Args:
  source: 'C++ source code'
  filename: 'file1'
Returns:
  AstBuilder
Definition at line 1663 of file ast.py.
View newest version in sPHENIX GitHub at line 1663 of file ast.py
Referenced by cpp.ast.main(), and cpp.ast.PrintIndentifiers().
def cpp.ast.main (argv)
Definition at line 1711 of file ast.py.
View newest version in sPHENIX GitHub at line 1711 of file ast.py
References cpp.ast.BuilderFromSource(), and print().
def cpp.ast.next (obj)
Definition at line 58 of file ast.py.
View newest version in sPHENIX GitHub at line 58 of file ast.py
Referenced by cpp.ast.AstBuilder._GetNextToken(), and cpp.ast.AstBuilder.GetName().
def cpp.ast.PrintAllIndentifiers (filenames, should_print)
Prints all identifiers for each C++ source file in filenames.
Args:
  filenames: ['file1', 'file2', ...]
  should_print: predicate with signature: bool Function(token)
Definition at line 1700 of file ast.py.
View newest version in sPHENIX GitHub at line 1700 of file ast.py
References cpp.ast.PrintIndentifiers().
def cpp.ast.PrintIndentifiers (filename, should_print)
Prints all identifiers for a C++ source file.
Args:
  filename: 'file1'
  should_print: predicate with signature: bool Function(token)
Definition at line 1676 of file ast.py.
View newest version in sPHENIX GitHub at line 1676 of file ast.py
References cpp.ast.BuilderFromSource(), and print().
Referenced by cpp.ast.PrintAllIndentifiers().
def cpp.ast.reversed (seq)
Definition at line 52 of file ast.py.
View newest version in sPHENIX GitHub at line 52 of file ast.py
Referenced by cpp.ast.AstBuilder._AddBackTokens(), PHCASeeding.FindBiLinks(), cpp.ast.AstBuilder.HandleError(), FitterTester.test_ZeroFieldNoSurfaceForward(), FitterTester.test_ZeroFieldShuffled(), FitterTester.test_ZeroFieldWithHole(), FitterTester.test_ZeroFieldWithOutliers(), FitterTester.test_ZeroFieldWithReverseFiltering(), FitterTester.test_ZeroFieldWithSurfaceAtExit(), FitterTester.test_ZeroFieldWithSurfaceBackward(), and FitterTester.test_ZeroFieldWithSurfaceForward().
Variable Documentation
string cpp.ast.__author__ 'nnorwitz@google.com (Neal Norwitz)'
Definition at line 20 of file ast.py.
View newest version in sPHENIX GitHub at line 20 of file ast.py
string cpp.ast._INTERNAL_TOKEN 'internal'
Definition at line 97 of file ast.py.
View newest version in sPHENIX GitHub at line 97 of file ast.py
string cpp.ast._NAMESPACE_POP 'ns-pop'
Definition at line 98 of file ast.py.
View newest version in sPHENIX GitHub at line 98 of file ast.py
int cpp.ast.FUNCTION_ATTRIBUTE 0x20
Definition at line 70 of file ast.py.
View newest version in sPHENIX GitHub at line 70 of file ast.py
int cpp.ast.FUNCTION_CONST 0x01
Definition at line 65 of file ast.py.
View newest version in sPHENIX GitHub at line 65 of file ast.py
int cpp.ast.FUNCTION_CTOR 0x08
Definition at line 68 of file ast.py.
View newest version in sPHENIX GitHub at line 68 of file ast.py
int cpp.ast.FUNCTION_DTOR 0x10
Definition at line 69 of file ast.py.
View newest version in sPHENIX GitHub at line 69 of file ast.py
int cpp.ast.FUNCTION_NONE 0x00
Definition at line 64 of file ast.py.
View newest version in sPHENIX GitHub at line 64 of file ast.py
int cpp.ast.FUNCTION_OVERRIDE 0x100
Definition at line 73 of file ast.py.
View newest version in sPHENIX GitHub at line 73 of file ast.py
int cpp.ast.FUNCTION_PURE_VIRTUAL 0x04
Definition at line 67 of file ast.py.
View newest version in sPHENIX GitHub at line 67 of file ast.py
int cpp.ast.FUNCTION_THROW 0x80
Definition at line 72 of file ast.py.
View newest version in sPHENIX GitHub at line 72 of file ast.py
int cpp.ast.FUNCTION_UNKNOWN_ANNOTATION 0x40
Definition at line 71 of file ast.py.
View newest version in sPHENIX GitHub at line 71 of file ast.py
int cpp.ast.FUNCTION_VIRTUAL 0x02
Definition at line 66 of file ast.py.
View newest version in sPHENIX GitHub at line 66 of file ast.py