Analysis Software: seeding Namespace Reference
seeding Namespace Reference
Classes
class EnumAction
Functions
def runSeeding
Variables
u acts.UnitConstants
tuple p
action EnumAction,
enum SeedingAlgorithm,
default SeedingAlgorithm.Default,
string help "Select the seeding algorithm to use"
tuple args p.parse_args()
tuple field acts.ConstantBField(acts.Vector3(0, 0, 2 * u.T))
Function Documentation
def seeding.runSeeding (trackingGeometry, field, outputDir, s = None, seedingAlgorithm = SeedingAlgorithm.Default)
Definition at line 52 of file seeding.py.
View newest version in sPHENIX GitHub at line 52 of file seeding.py
References acts.examples.simulation.addDigitization(), acts.examples.simulation.addFatras(), acts.examples.simulation.addParticleGun(), acts.examples.reconstruction.addSeeding(), acts.examples.simulation.EtaConfig, acts.examples.simulation.ParticleConfig, acts.examples.reconstruction.ParticleSmearingSigmas, acts.examples.simulation.PhiConfig, acts.examples.reconstruction.SeedFinderConfigArg, acts.examples.reconstruction.SeedFinderOptionsArg, and acts.examples.reconstruction.TruthSeedRanges.
Referenced by seeding.EnumAction.__call__().
Variable Documentation
seeding.action EnumAction,
Definition at line 144 of file seeding.py.
View newest version in sPHENIX GitHub at line 144 of file seeding.py
tuple seeding.args p.parse_args()
Definition at line 150 of file seeding.py.
View newest version in sPHENIX GitHub at line 150 of file seeding.py
seeding.default SeedingAlgorithm.Default,
Definition at line 146 of file seeding.py.
View newest version in sPHENIX GitHub at line 146 of file seeding.py
seeding.enum SeedingAlgorithm,
Definition at line 145 of file seeding.py.
View newest version in sPHENIX GitHub at line 145 of file seeding.py
tuple seeding.field acts.ConstantBField(acts.Vector3(0, 0, 2 * u.T))
Definition at line 154 of file seeding.py.
View newest version in sPHENIX GitHub at line 154 of file seeding.py
string seeding.help "Select the seeding algorithm to use"
Definition at line 147 of file seeding.py.
View newest version in sPHENIX GitHub at line 147 of file seeding.py
tuple seeding.p
Initial value:
 argparse.ArgumentParser(
         description="Example script to run seed finding",
     )
Definition at line 138 of file seeding.py.
View newest version in sPHENIX GitHub at line 138 of file seeding.py
seeding.u acts.UnitConstants
Definition at line 9 of file seeding.py.
View newest version in sPHENIX GitHub at line 9 of file seeding.py