Analysis Software: ActsExamples::SingleSeedVertexFinderAlgorithm Exception Reference
ActsExamples::SingleSeedVertexFinderAlgorithm Exception Reference final
#include <acts/blob/sPHENIX/Examples/Algorithms/Vertexing/include/ActsExamples/Vertexing/SingleSeedVertexFinderAlgorithm.hpp>
Classes
struct Config
Public Member Functions
SingleSeedVertexFinderAlgorithm (const Config &cfg, Acts::Logging::Level lvl)
ProcessCode execute (const AlgorithmContext &ctx) const final
Find a vertex using spacepoints.
const Config & config () const
Get readonly access to the config parameters.
Public Member Functions inherited from ActsExamples::IAlgorithm
IAlgorithm (std::string name, Acts::Logging::Level level=Acts::Logging::INFO)
std::string name () const override
The algorithm name.
ProcessCode internalExecute (const AlgorithmContext &context) final
ProcessCode initialize () override
Initialize the algorithm.
ProcessCode finalize () override
Finalize the algorithm.
Private Attributes
Config m_cfg
ReadDataHandle
< SimSpacePointContainer > m_inputSpacepoints
WriteDataHandle< std::vector
< Acts::Vertex
< Acts::BoundTrackParameters > > > m_outputVertices {this, "fittedVertices"}
Additional Inherited Members
Protected Member Functions inherited from ActsExamples::IAlgorithm
const Acts::Logger & logger () const
Detailed Description
Definition at line 21 of file SingleSeedVertexFinderAlgorithm.hpp.
View newest version in sPHENIX GitHub at line 21 of file SingleSeedVertexFinderAlgorithm.hpp
Constructor & Destructor Documentation
ActsExamples::SingleSeedVertexFinderAlgorithm::SingleSeedVertexFinderAlgorithm (const Config & cfg, Acts::Logging::Level lvl)
Definition at line 17 of file SingleSeedVertexFinderAlgorithm.cpp.
View newest version in sPHENIX GitHub at line 17 of file SingleSeedVertexFinderAlgorithm.cpp
References ACTS_ERROR, ActsExamples::WriteDataHandle< T >::initialize(), ActsExamples::ReadDataHandle< T >::initialize(), ActsExamples::SingleSeedVertexFinderAlgorithm::Config::inputSpacepoints, m_cfg, m_inputSpacepoints, m_outputVertices, and ActsExamples::SingleSeedVertexFinderAlgorithm::Config::outputVertices.
Member Function Documentation
const Config& ActsExamples::SingleSeedVertexFinderAlgorithm::config () const inline
Get readonly access to the config parameters.
Definition at line 39 of file SingleSeedVertexFinderAlgorithm.hpp.
View newest version in sPHENIX GitHub at line 39 of file SingleSeedVertexFinderAlgorithm.hpp
References m_cfg.
ActsExamples::ProcessCode ActsExamples::SingleSeedVertexFinderAlgorithm::execute (const AlgorithmContext & ctx) const final virtual
Find a vertex using spacepoints.
Parameters
ctx is the algorithm context with event information
Returns
a process code indication success or failure
Implements ActsExamples::IAlgorithm.
Definition at line 32 of file SingleSeedVertexFinderAlgorithm.cpp.
View newest version in sPHENIX GitHub at line 32 of file SingleSeedVertexFinderAlgorithm.cpp
References ACTS_INFO, test_fpe::count, Acts::SingleSeedVertexFinder< spacepoint_t >::findVertex(), testing::internal::move(), SUCCESS, ambiguity_solver_full_chain::t1, and ambiguity_solver_full_chain::t2.
Member Data Documentation
Config ActsExamples::SingleSeedVertexFinderAlgorithm::m_cfg private
Definition at line 42 of file SingleSeedVertexFinderAlgorithm.hpp.
View newest version in sPHENIX GitHub at line 42 of file SingleSeedVertexFinderAlgorithm.hpp
Referenced by config(), and SingleSeedVertexFinderAlgorithm().
ReadDataHandle<SimSpacePointContainer> ActsExamples::SingleSeedVertexFinderAlgorithm::m_inputSpacepoints private
Initial value:
{this,
                                                            "spacepoints"}
Definition at line 44 of file SingleSeedVertexFinderAlgorithm.hpp.
View newest version in sPHENIX GitHub at line 44 of file SingleSeedVertexFinderAlgorithm.hpp
Referenced by SingleSeedVertexFinderAlgorithm().
WriteDataHandle<std::vector<Acts::Vertex<Acts::BoundTrackParameters> > > ActsExamples::SingleSeedVertexFinderAlgorithm::m_outputVertices {this, "fittedVertices"} private
Definition at line 47 of file SingleSeedVertexFinderAlgorithm.hpp.
View newest version in sPHENIX GitHub at line 47 of file SingleSeedVertexFinderAlgorithm.hpp
Referenced by SingleSeedVertexFinderAlgorithm().
The documentation for this exception was generated from the following files:
acts/blob/sPHENIX/Examples/Algorithms/Vertexing/include/ActsExamples/Vertexing/SingleSeedVertexFinderAlgorithm.hpp
acts/blob/sPHENIX/Examples/Algorithms/Vertexing/src/SingleSeedVertexFinderAlgorithm.cpp