Analysis Software: PHGenFitTrkProp Class Reference
PHGenFitTrkProp Class Reference
Propagate tracklet to full track using GenFit.
#include <coresoftware/blob/master/offline/packages/trackreco/PHGenFitTrkProp.h>
Classes
struct TrackQuality
Public Types
typedef std::list< std::pair
< TrackQuality,
std::shared_ptr
< PHGenFit::Track > > > MapPHGenFitTrack
Public Member Functions
PHGenFitTrkProp (const std::string &name="PHGenFitTrkProp", unsigned int nlayers_maps=3, unsigned int nlayers_intt=8, unsigned int nlayers_tpc=60, unsigned int nlayers_micromegas=0)
float get_search_win_phi () const
void set_search_win_phi (float searchWinMultiplier)
bool is_do_evt_display () const
void set_do_evt_display (bool doEvtDisplay)
const std::string & get_track_fitting_alg_name () const
void set_track_fitting_alg_name (const std::string &trackFittingAlgName)
void set_analyzing_mode (bool analyzingMode)
float get_max_merging_deta () const
void set_max_merging_deta (float maxMergingDeta)
float get_max_merging_dphi () const
void set_max_merging_dphi (float maxMergingDphi)
float get_max_merging_dr () const
void set_max_merging_dr (float maxMergingDr)
float get_max_merging_dz () const
void set_max_merging_dz (float maxMergingDz)
float get_search_win_theta () const
void set_search_win_theta (float searchWinZ)
float get_max_incr_chi2 () const
void set_max_incr_chi2 (float maxIncrChi2)
unsigned int get_max_consecutive_missing_layer () const
void set_max_consecutive_missing_layer (unsigned int maxConsecutiveMissingLayer)
unsigned int get_min_good_track_hits () const
void set_min_good_track_hits (unsigned int minGoodTrackHits)
unsigned int get_max_share_hits () const
void set_max_share_hits (unsigned int maxShareHits)
float get_max_splitting_chi2 () const
void set_max_splitting_chi2 (float maxSplittingChi2)
int get_init_direction () const
void set_init_direction (int initDirection)
float get_max_search_win_phi_tpc () const
void set_max_search_win_phi_tpc (float maxSearchWinPhi)
float get_max_search_win_theta_tpc () const
void set_max_search_win_theta_tpc (float maxSearchWinZ)
float get_max_search_win_phi_micromegas (int layer) const
void set_max_search_win_phi_micromegas (int layer, float maxSearchWinPhi)
float get_max_search_win_theta_micromegas (int layer) const
void set_max_search_win_theta_micromegas (int layer, float maxSearchWinZ)
float get_blowup_factor () const
void set_blowup_factor (float blowupFactor)
float get_max_search_win_phi_intt (int inttlayer) const
void set_max_search_win_phi_intt (int inttlayer, float maxSearchWinPhiIntt)
float get_max_search_win_phi_maps () const
void set_max_search_win_phi_maps (float maxSearchWinPhiMaps)
float get_max_search_win_theta_intt (int inttlayer) const
void set_max_search_win_theta_intt (int inttlayer, float maxSearchWinThetaIntt)
float get_max_search_win_theta_maps () const
void set_max_search_win_theta_maps (float maxSearchWinThetaMaps)
float get_min_search_win_phi_intt (int inttlayer) const
void set_min_search_win_phi_intt (int inttlayer, float minSearchWinPhiIntt)
float get_min_search_win_phi_maps () const
void set_min_search_win_phi_maps (float minSearchWinPhiMaps)
float get_min_search_win_phi_tpc () const
void set_min_search_win_phi_tpc (float minSearchWinPhiTpc)
float get_min_search_win_phi_micromegas (int layer) const
void set_min_search_win_phi_micromegas (int layer, float minSearchWinPhimicromegas)
float get_min_search_win_theta_intt (int inttlayer) const
void set_min_search_win_theta_intt (int inttlayer, float minSearchWinThetaIntt)
float get_min_search_win_theta_maps () const
void set_min_search_win_theta_maps (float minSearchWinThetaMaps)
float get_min_search_win_theta_tpc () const
void set_min_search_win_theta_tpc (float minSearchWinThetaTpc)
float get_min_search_win_theta_micromegas (int layer) const
void set_min_search_win_theta_micromegas (int layer, float minSearchWinThetamicromegas)
int get_primary_pid_guess () const
void set_primary_pid_guess (int primaryPidGuess)
void set_beam_constraint (bool beamConstraint)
Public Member Functions inherited from PHTrackPropagating
PHTrackPropagating (const std::string &name="PHTrackPropagating")
~PHTrackPropagating () override
int InitRun (PHCompositeNode *topNode) override
int process_event (PHCompositeNode *topNode) override
int End (PHCompositeNode *topNode) override
Called at the end of all processing.
void set_track_map_name (const std::string &map_name)
void SetUseTruthClusters (bool setit)
Public Member Functions inherited from SubsysReco
~SubsysReco () override
virtual int EndRun (const int)
Called at the end of each run.
virtual int Init (PHCompositeNode *)
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
void Print (const std::string &what="ALL") const override
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Protected Member Functions
int Setup (PHCompositeNode *topNode) override
int Process () override
int End () override
Private Member Functions
int GetNodes (PHCompositeNode *topNode)
fetch node pointers
std::shared_ptr< PHGenFit::Track > ReFitTrack (SvtxTrack *intrack)
int InitializeGeometry (PHCompositeNode *topNode)
Init projection r.
int InitializePHGenFit (PHCompositeNode *topNode)
track propagation
int check_track_exists (MapPHGenFitTrack::iterator, SvtxTrackMap::Iter)
int KalmanTrkProp ()
Main function.
int ExportOutput ()
void print_timers ()
int BuildLayerZPhiHitMap (const unsigned int ivert)
KalmanTrkProp Call.
unsigned int encode_cluster_index (const unsigned int layer, const float z, const float rphi)
layer: 7 bits, z: 11 bits, phi: 14 bits
unsigned int encode_cluster_index (const unsigned int layer, const unsigned int iz, const unsigned int irphi)
int SvtxTrackToPHGenFitTracks (const SvtxTrack *svtxtrack)
KalmanTrkProp Call.
int TrackPropPatRec (const unsigned int ivert, MapPHGenFitTrack::iterator &track_iter, const unsigned int init_layer=0, const unsigned int end_layer=66, const bool use_fitted_state_once=false)
PHGenFit::Measurement * TrkrClusterToPHGenFitMeasurement (const TrkrCluster *cluster)
std::vector< TrkrDefs::cluskey > SearchHitsNearBy (const unsigned int ivert, const unsigned int layer, const float z_center, const float phi_center, const float z_window, const float phi_window)
TrackPropPatRec Call.
int OutputPHGenFitTrack (MapPHGenFitTrack::iterator, SvtxTrackMap::Iter)
ExportOutput Call. Make SvtxTrack from PHGenFit::Track and set of clusters.
float kappaToPt (float kappa)
convert from inverse curvature to momentum
float ptToKappa (float pt)
convert from momentum to inverse curvature
void convertHelixCovarianceToEuclideanCovariance (float B, float phi, float d, float kappa, float z0, float dzdl, Eigen::Matrix< float, 5, 5 > const &input, Eigen::Matrix< float, 6, 6 > &output)
convert the covariance from HelixHough coords to x,y,z,px,py,pz
void shift_coordinate_system (double dx, double dy, double dz)
translate the clusters, tracks, and vertex from one origin to another
bool is_maps_layer (unsigned int layer) const
bool is_intt_layer (unsigned int layer) const
bool is_tpc_layer (unsigned int layer) const
bool is_micromegas_layer (unsigned int layer) const
Private Attributes
int _event = 0
PHTimer * _t_seeds_cleanup = nullptr
PHTimer * _t_translate_to_PHGenFitTrack = nullptr
PHTimer * _t_translate1 = nullptr
PHTimer * _t_translate2 = nullptr
PHTimer * _t_translate3 = nullptr
PHTimer * _t_kalman_pat_rec = nullptr
PHTimer * _t_search_clusters = nullptr
PHTimer * _t_search_clusters_encoding = nullptr
PHTimer * _t_search_clusters_map_iter = nullptr
PHTimer * _t_track_propagation = nullptr
PHTimer * _t_full_fitting = nullptr
PHTimer * _t_output_io = nullptr
std::vector< std::vector< float > > _vertex
working array for collision vertex list
std::vector< std::vector< float > > _vertex_error
sqrt(cov)
BbcVertexMap * _bbc_vertexes = nullptr
std::multimap
< TrkrDefs::cluskey, unsigned
int > _gftrk_hitkey_map
PHG4CylinderGeomContainer * _geom_container_intt = nullptr
PHG4CylinderGeomContainer * _geom_container_maps = nullptr
bool _analyzing_mode = false
TFile * _analyzing_file = nullptr
TNtuple * _analyzing_ntuple = nullptr
float _max_merging_dphi = 0.1
Cleanup Seeds.
float _max_merging_deta = 0.1
float _max_merging_dr = 0.1
float _max_merging_dz = 0.1
unsigned int _max_share_hits = 3
if two seeds have common hits more than this number, merge them
std::unique_ptr< PHGenFit::Fitter > _fitter
std::string _track_fitting_alg_name = "DafRef"
KalmanFitterRefTrack, KalmanFitter, DafSimple, DafRef.
int _primary_pid_guess = 211
double _cut_min_pT = 0.2
bool _do_evt_display = false
unsigned int _nlayers_maps = 3
unsigned int _nlayers_intt = 4
unsigned int _nlayers_tpc = 48
unsigned int _nlayers_micromegas = 0
int _nlayers_all = 55
unsigned int _firstlayer_maps = 0
unsigned int _firstlayer_intt = 3
unsigned int _firstlayer_tpc = 7
unsigned int _firstlayer_micromegas = 55
std::map< int, unsigned int > _layer_ilayer_map_all
std::vector< float > _radii_all
std::array< float, 2 > _max_search_win_phi_micromegas = {{ 0.004, 0.62}}
std::array< float, 2 > _min_search_win_phi_micromegas = {{ 0, 0.31 }}
std::array< float, 2 > _max_search_win_theta_micromegas = {{ 1.24, 0.004}}
std::array< float, 2 > _min_search_win_theta_micromegas = {{ 0.62, 0}}
float _max_search_win_phi_tpc = 0.004
float _min_search_win_phi_tpc = 0
float _max_search_win_theta_tpc = 0.004
float _min_search_win_theta_tpc = 0
std::array< float, 4 > _max_search_win_phi_intt = {{ 0.2, 0.2, 0.005, 0.005 }}
std::array< float, 4 > _min_search_win_phi_intt = {{ 0.2, 0.2, 0, 0 }}
std::array< float, 4 > _max_search_win_theta_intt = {{ 0.01, 0.01, 0.2, 0.2 }}
std::array< float, 4 > _min_search_win_theta_intt = {{ 0, 0, 0.2, 0.2 }}
float _max_search_win_phi_maps = 0.005
float _min_search_win_phi_maps = 0
float _max_search_win_theta_maps = 0.04
float _min_search_win_theta_maps = 0
float _search_win_phi = 20
float _search_win_theta = 20
std::map< int, float > _search_wins_phi
std::map< int, float > _search_wins_theta
std::vector< std::multimap
< unsigned int,
TrkrDefs::cluskey > > _layer_thetaID_phiID_clusterID
float _half_max_theta = M_PI/2
float _half_max_phi = M_PI
float _layer_thetaID_phiID_clusterID_phiSize = 0.12/30
float _layer_thetaID_phiID_clusterID_zSize = 0.17/30
MapPHGenFitTrack _PHGenFitTracks
int _init_direction = -1
+1: inside out; -1: outside in
float _blowup_factor = 1
unsigned int _max_consecutive_missing_layer = 20
float _max_incr_chi2 = 20
std::map< int, float > _max_incr_chi2s
float _max_splitting_chi2 = 20
unsigned int _min_good_track_hits = 30
PHCompositeNode * _topNode = nullptr
int _ntrack = 0
bool _use_beam
Additional Inherited Members
Protected Attributes inherited from PHTrackPropagating
TrkrClusterContainer * _cluster_map
TrkrHitSetContainer * _hitsets
SvtxVertexMap * _vertex_map
SvtxTrackMap * _track_map
AssocInfoContainer * _assoc_container
std::string _track_map_name
bool _use_truth_clusters = false
Detailed Description
Propagate tracklet to full track using GenFit.
Definition at line 54 of file PHGenFitTrkProp.h.
View newest version in sPHENIX GitHub at line 54 of file PHGenFitTrkProp.h
Member Typedef Documentation
typedef std::list<std::pair<TrackQuality, std::shared_ptr<PHGenFit::Track> > > PHGenFitTrkProp::MapPHGenFitTrack
Definition at line 131 of file PHGenFitTrkProp.h.
View newest version in sPHENIX GitHub at line 131 of file PHGenFitTrkProp.h
Constructor & Destructor Documentation
PHGenFitTrkProp::PHGenFitTrkProp (const std::string & name = "PHGenFitTrkProp", unsigned int nlayers_maps = 3, unsigned int nlayers_intt = 8, unsigned int nlayers_tpc = 60, unsigned int nlayers_micromegas = 0)
Definition at line 106 of file PHGenFitTrkProp.cc.
View newest version in sPHENIX GitHub at line 106 of file PHGenFitTrkProp.cc
References _event.
Member Function Documentation
int PHGenFitTrkProp::BuildLayerZPhiHitMap (const unsigned int ivert) private
KalmanTrkProp Call.
Definition at line 1596 of file PHGenFitTrkProp.cc.
View newest version in sPHENIX GitHub at line 1596 of file PHGenFitTrkProp.cc
References PHTrackPropagating::_cluster_map, PHTrackPropagating::_hitsets, _layer_thetaID_phiID_clusterID, _vertex, encode_cluster_index(), Fun4AllReturnCodes::EVENT_OK, TrkrCluster::getClusKey(), TrkrClusterContainer::getClusters(), TrkrHitSetContainer::getHitSets(), TrkrDefs::getLayer(), TrkrCluster::getPosition(), layer, phi, r, ActsTests::PropagationDatasets::theta, x, y, and z.
Referenced by KalmanTrkProp().
int PHGenFitTrkProp::check_track_exists (MapPHGenFitTrack::iterator iter, SvtxTrackMap::Iter phtrk_iter) private
Definition at line 363 of file PHGenFitTrkProp.cc.
View newest version in sPHENIX GitHub at line 363 of file PHGenFitTrkProp.cc
References PHTrackPropagating::_assoc_container, PHTrackPropagating::_cluster_map, _gftrk_hitkey_map, TrkrClusterContainer::findCluster(), TrkrDefs::getLayer(), AssocInfoContainer::GetTracksFromCluster(), TrkrCluster::getX(), TrkrCluster::getY(), n, and Fun4AllBase::Verbosity().
Referenced by KalmanTrkProp().
void PHGenFitTrkProp::convertHelixCovarianceToEuclideanCovariance (float B, float phi, float d, float kappa, float z0, float dzdl, Eigen::Matrix< float, 5, 5 > const & input, Eigen::Matrix< float, 6, 6 > & output) private
convert the covariance from HelixHough coords to x,y,z,px,py,pz
unsigned int PHGenFitTrkProp::encode_cluster_index (const unsigned int layer, const float z, const float rphi) private
layer: 7 bits, z: 11 bits, phi: 14 bits
Definition at line 1746 of file PHGenFitTrkProp.cc.
View newest version in sPHENIX GitHub at line 1746 of file PHGenFitTrkProp.cc
References _half_max_phi, _half_max_theta, _layer_thetaID_phiID_clusterID_phiSize, _layer_thetaID_phiID_clusterID_zSize, and LogError.
Referenced by BuildLayerZPhiHitMap(), and SearchHitsNearBy().
unsigned int PHGenFitTrkProp::encode_cluster_index (const unsigned int layer, const unsigned int iz, const unsigned int irphi) private
Definition at line 1782 of file PHGenFitTrkProp.cc.
View newest version in sPHENIX GitHub at line 1782 of file PHGenFitTrkProp.cc
References index, and LogError.
int PHGenFitTrkProp::End () override protected virtual
Implements PHTrackPropagating.
Definition at line 283 of file PHGenFitTrkProp.cc.
View newest version in sPHENIX GitHub at line 283 of file PHGenFitTrkProp.cc
References _analyzing_file, _analyzing_mode, _analyzing_ntuple, _do_evt_display, _fitter, _t_full_fitting, _t_kalman_pat_rec, _t_output_io, _t_search_clusters, _t_seeds_cleanup, _t_track_propagation, _t_translate1, _t_translate2, _t_translate3, _t_translate_to_PHGenFitTrack, Fun4AllReturnCodes::EVENT_OK, and LogDebug.
int PHGenFitTrkProp::ExportOutput () private
float PHGenFitTrkProp::get_blowup_factor () const inline
Definition at line 318 of file PHGenFitTrkProp.h.
View newest version in sPHENIX GitHub at line 318 of file PHGenFitTrkProp.h
References _blowup_factor.
int PHGenFitTrkProp::get_init_direction () const inline
Definition at line 269 of file PHGenFitTrkProp.h.
View newest version in sPHENIX GitHub at line 269 of file PHGenFitTrkProp.h
References _init_direction.
unsigned int PHGenFitTrkProp::get_max_consecutive_missing_layer () const inline
Definition at line 228 of file PHGenFitTrkProp.h.
View newest version in sPHENIX GitHub at line 228 of file PHGenFitTrkProp.h
References _max_consecutive_missing_layer.
float PHGenFitTrkProp::get_max_incr_chi2 () const inline
Definition at line 218 of file PHGenFitTrkProp.h.
View newest version in sPHENIX GitHub at line 218 of file PHGenFitTrkProp.h
References _max_incr_chi2.
float PHGenFitTrkProp::get_max_merging_deta () const inline
Definition at line 168 of file PHGenFitTrkProp.h.
View newest version in sPHENIX GitHub at line 168 of file PHGenFitTrkProp.h
References _max_merging_deta.
float PHGenFitTrkProp::get_max_merging_dphi () const inline
Definition at line 178 of file PHGenFitTrkProp.h.
View newest version in sPHENIX GitHub at line 178 of file PHGenFitTrkProp.h
References _max_merging_dphi.
float PHGenFitTrkProp::get_max_merging_dr () const inline
Definition at line 188 of file PHGenFitTrkProp.h.
View newest version in sPHENIX GitHub at line 188 of file PHGenFitTrkProp.h
References _max_merging_dr.
float PHGenFitTrkProp::get_max_merging_dz () const inline
Definition at line 198 of file PHGenFitTrkProp.h.
View newest version in sPHENIX GitHub at line 198 of file PHGenFitTrkProp.h
References _max_merging_dz.
float PHGenFitTrkProp::get_max_search_win_phi_intt (int inttlayer) const inline
Definition at line 328 of file PHGenFitTrkProp.h.
View newest version in sPHENIX GitHub at line 328 of file PHGenFitTrkProp.h
References _max_search_win_phi_intt.
float PHGenFitTrkProp::get_max_search_win_phi_maps () const inline
Definition at line 338 of file PHGenFitTrkProp.h.
View newest version in sPHENIX GitHub at line 338 of file PHGenFitTrkProp.h
References _max_search_win_phi_maps.
float PHGenFitTrkProp::get_max_search_win_phi_micromegas (int layer) const inline
Definition at line 298 of file PHGenFitTrkProp.h.
View newest version in sPHENIX GitHub at line 298 of file PHGenFitTrkProp.h
References _max_search_win_phi_micromegas, and layer.
float PHGenFitTrkProp::get_max_search_win_phi_tpc () const inline
Definition at line 279 of file PHGenFitTrkProp.h.
View newest version in sPHENIX GitHub at line 279 of file PHGenFitTrkProp.h
References _max_search_win_phi_tpc.
float PHGenFitTrkProp::get_max_search_win_theta_intt (int inttlayer) const inline
Definition at line 348 of file PHGenFitTrkProp.h.
View newest version in sPHENIX GitHub at line 348 of file PHGenFitTrkProp.h
References _max_search_win_theta_intt.
float PHGenFitTrkProp::get_max_search_win_theta_maps () const inline
Definition at line 358 of file PHGenFitTrkProp.h.
View newest version in sPHENIX GitHub at line 358 of file PHGenFitTrkProp.h
References _max_search_win_theta_maps.
float PHGenFitTrkProp::get_max_search_win_theta_micromegas (int layer) const inline
Definition at line 308 of file PHGenFitTrkProp.h.
View newest version in sPHENIX GitHub at line 308 of file PHGenFitTrkProp.h
References _max_search_win_theta_micromegas, and layer.
float PHGenFitTrkProp::get_max_search_win_theta_tpc () const inline
Definition at line 289 of file PHGenFitTrkProp.h.
View newest version in sPHENIX GitHub at line 289 of file PHGenFitTrkProp.h
References _max_search_win_theta_tpc.
unsigned int PHGenFitTrkProp::get_max_share_hits () const inline
Definition at line 249 of file PHGenFitTrkProp.h.
View newest version in sPHENIX GitHub at line 249 of file PHGenFitTrkProp.h
References _max_share_hits.
float PHGenFitTrkProp::get_max_splitting_chi2 () const inline
Definition at line 259 of file PHGenFitTrkProp.h.
View newest version in sPHENIX GitHub at line 259 of file PHGenFitTrkProp.h
References _max_splitting_chi2.
unsigned int PHGenFitTrkProp::get_min_good_track_hits () const inline
Definition at line 239 of file PHGenFitTrkProp.h.
View newest version in sPHENIX GitHub at line 239 of file PHGenFitTrkProp.h
References _min_good_track_hits.
float PHGenFitTrkProp::get_min_search_win_phi_intt (int inttlayer) const inline
Definition at line 368 of file PHGenFitTrkProp.h.
View newest version in sPHENIX GitHub at line 368 of file PHGenFitTrkProp.h
References _min_search_win_phi_intt.
float PHGenFitTrkProp::get_min_search_win_phi_maps () const inline
Definition at line 378 of file PHGenFitTrkProp.h.
View newest version in sPHENIX GitHub at line 378 of file PHGenFitTrkProp.h
References _min_search_win_phi_maps.
float PHGenFitTrkProp::get_min_search_win_phi_micromegas (int layer) const inline
Definition at line 398 of file PHGenFitTrkProp.h.
View newest version in sPHENIX GitHub at line 398 of file PHGenFitTrkProp.h
References _min_search_win_phi_micromegas, and layer.
float PHGenFitTrkProp::get_min_search_win_phi_tpc () const inline
Definition at line 388 of file PHGenFitTrkProp.h.
View newest version in sPHENIX GitHub at line 388 of file PHGenFitTrkProp.h
References _min_search_win_phi_tpc.
float PHGenFitTrkProp::get_min_search_win_theta_intt (int inttlayer) const inline
Definition at line 408 of file PHGenFitTrkProp.h.
View newest version in sPHENIX GitHub at line 408 of file PHGenFitTrkProp.h
References _min_search_win_theta_intt.
float PHGenFitTrkProp::get_min_search_win_theta_maps () const inline
Definition at line 418 of file PHGenFitTrkProp.h.
View newest version in sPHENIX GitHub at line 418 of file PHGenFitTrkProp.h
References _min_search_win_theta_maps.
float PHGenFitTrkProp::get_min_search_win_theta_micromegas (int layer) const inline
Definition at line 438 of file PHGenFitTrkProp.h.
View newest version in sPHENIX GitHub at line 438 of file PHGenFitTrkProp.h
References _min_search_win_theta_micromegas, and layer.
float PHGenFitTrkProp::get_min_search_win_theta_tpc () const inline
Definition at line 428 of file PHGenFitTrkProp.h.
View newest version in sPHENIX GitHub at line 428 of file PHGenFitTrkProp.h
References _min_search_win_theta_tpc.
int PHGenFitTrkProp::get_primary_pid_guess () const inline
Definition at line 448 of file PHGenFitTrkProp.h.
View newest version in sPHENIX GitHub at line 448 of file PHGenFitTrkProp.h
References _primary_pid_guess.
float PHGenFitTrkProp::get_search_win_phi () const inline
Definition at line 133 of file PHGenFitTrkProp.h.
View newest version in sPHENIX GitHub at line 133 of file PHGenFitTrkProp.h
References _search_win_phi.
float PHGenFitTrkProp::get_search_win_theta () const inline
Definition at line 208 of file PHGenFitTrkProp.h.
View newest version in sPHENIX GitHub at line 208 of file PHGenFitTrkProp.h
References _search_win_theta.
const std::string& PHGenFitTrkProp::get_track_fitting_alg_name () const inline
Definition at line 153 of file PHGenFitTrkProp.h.
View newest version in sPHENIX GitHub at line 153 of file PHGenFitTrkProp.h
References _track_fitting_alg_name.
int PHGenFitTrkProp::GetNodes (PHCompositeNode * topNode) private
fetch node pointers
Definition at line 342 of file PHGenFitTrkProp.cc.
View newest version in sPHENIX GitHub at line 342 of file PHGenFitTrkProp.cc
References _bbc_vertexes, _geom_container_intt, _geom_container_maps, _topNode, Fun4AllReturnCodes::EVENT_OK, and findNode::getClass().
Referenced by Setup().
int PHGenFitTrkProp::InitializeGeometry (PHCompositeNode * topNode) private
Init projection r.
Definition at line 1813 of file PHGenFitTrkProp.cc.
View newest version in sPHENIX GitHub at line 1813 of file PHGenFitTrkProp.cc
References _layer_ilayer_map_all, _nlayers_all, _radii_all, Fun4AllReturnCodes::EVENT_OK, PHG4CylinderCellGeom::get_layer(), PHG4CylinderGeom::get_layer(), PHG4CylinderCellGeom::get_radius(), PHG4CylinderGeom::get_radius(), PHG4CylinderCellGeom::get_thickness(), and PHG4CylinderGeom::get_thickness().
Referenced by Setup().
int PHGenFitTrkProp::InitializePHGenFit (PHCompositeNode * topNode) private
track propagation
Definition at line 321 of file PHGenFitTrkProp.cc.
View newest version in sPHENIX GitHub at line 321 of file PHGenFitTrkProp.cc
References _do_evt_display, _fitter, _track_fitting_alg_name, Fun4AllReturnCodes::ABORTRUN, Fun4AllReturnCodes::EVENT_OK, PHFieldUtility::GetFieldMapNode(), PHGenFit::Fitter::getInstance(), PHGeomUtility::GetTGeoManager(), and PHWHERE.
Referenced by Setup().
bool PHGenFitTrkProp::is_do_evt_display () const inline
Definition at line 143 of file PHGenFitTrkProp.h.
View newest version in sPHENIX GitHub at line 143 of file PHGenFitTrkProp.h
References _do_evt_display.
bool PHGenFitTrkProp::is_intt_layer (unsigned int layer) const inline private
Definition at line 470 of file PHGenFitTrkProp.h.
View newest version in sPHENIX GitHub at line 470 of file PHGenFitTrkProp.h
References _firstlayer_intt, and _nlayers_intt.
Referenced by OutputPHGenFitTrack(), and TrackPropPatRec().
bool PHGenFitTrkProp::is_maps_layer (unsigned int layer) const inline private
Definition at line 467 of file PHGenFitTrkProp.h.
View newest version in sPHENIX GitHub at line 467 of file PHGenFitTrkProp.h
References _firstlayer_maps, and _nlayers_maps.
Referenced by OutputPHGenFitTrack(), and TrackPropPatRec().
bool PHGenFitTrkProp::is_micromegas_layer (unsigned int layer) const inline private
Definition at line 476 of file PHGenFitTrkProp.h.
View newest version in sPHENIX GitHub at line 476 of file PHGenFitTrkProp.h
References _firstlayer_micromegas, and _nlayers_micromegas.
Referenced by OutputPHGenFitTrack(), and TrackPropPatRec().
bool PHGenFitTrkProp::is_tpc_layer (unsigned int layer) const inline private
Definition at line 473 of file PHGenFitTrkProp.h.
View newest version in sPHENIX GitHub at line 473 of file PHGenFitTrkProp.h
References _firstlayer_tpc, and _nlayers_tpc.
Referenced by OutputPHGenFitTrack(), and TrackPropPatRec().
int PHGenFitTrkProp::KalmanTrkProp () private
Main function.
sort clusters
Translate sPHENIX track To PHGenFitTracks
Handle track propagation, termination, output and evt disp.
Definition at line 407 of file PHGenFitTrkProp.cc.
View newest version in sPHENIX GitHub at line 407 of file PHGenFitTrkProp.cc
References _do_evt_display, _event, _fitter, _init_direction, _layer_thetaID_phiID_clusterID, _min_good_track_hits, _nlayers_all, _ntrack, _PHGenFitTracks, _t_translate_to_PHGenFitTrack, PHTrackPropagating::_track_map, _vertex, Fun4AllReturnCodes::ABORTRUN, SvtxTrackMap::begin(), BuildLayerZPhiHitMap(), check_track_exists(), SvtxTrackMap::end(), SvtxTrackMap::erase(), Fun4AllReturnCodes::EVENT_OK, TrkrDefs::getLayer(), i, layer, OutputPHGenFitTrack(), PHWHERE, PHTimer::restart(), SvtxTrackMap::size(), SvtxTrackToPHGenFitTracks(), TrackPropPatRec(), and Fun4AllBase::Verbosity().
Referenced by Process().
float PHGenFitTrkProp::kappaToPt (float kappa) private
convert from inverse curvature to momentum
int PHGenFitTrkProp::OutputPHGenFitTrack (MapPHGenFitTrack::iterator gftrk_iter, SvtxTrackMap::Iter phtrk_iter) private
ExportOutput Call. Make SvtxTrack from PHGenFit::Track and set of clusters.
Definition at line 646 of file PHGenFitTrkProp.cc.
View newest version in sPHENIX GitHub at line 646 of file PHGenFitTrkProp.cc
References PHTrackPropagating::_assoc_container, _fitter, _gftrk_hitkey_map, _t_full_fitting, _t_output_io, PHTrackPropagating::_track_map, _vertex, SvtxTrack::begin_cluster_keys(), Acts::Test::cov, SvtxTrack::end_cluster_keys(), genfit::MeasuredStateOnPlane::get6DCov(), SvtxTrack::get_charge(), SvtxTrack::get_id(), SvtxTrack::get_px(), SvtxTrack::get_py(), SvtxTrack::get_pz(), SvtxTrack::get_quality(), SvtxTrack::get_vertex_id(), TrkrDefs::getLayer(), genfit::StateOnPlane::getMom(), genfit::StateOnPlane::getPos(), i, SvtxTrack::insert_cluster_key(), is_intt_layer(), is_maps_layer(), is_micromegas_layer(), is_tpc_layer(), j, layer, LogWarning, PHWHERE, Acts::Test::pos, PHObject::Reset(), PHTimer::restart(), SvtxTrack::set_charge(), SvtxTrack::set_chisq(), SvtxTrack::set_error(), SvtxTrack::set_id(), SvtxTrack::set_ndf(), SvtxTrack::set_px(), SvtxTrack::set_py(), SvtxTrack::set_pz(), SvtxTrack::set_vertex_id(), SvtxTrack::set_x(), SvtxTrack::set_y(), SvtxTrack::set_z(), AssocInfoContainer::SetClusterTrackAssoc(), SvtxTrackMap::size(), PHTimer::stop(), and Fun4AllBase::Verbosity().
Referenced by KalmanTrkProp().
void PHGenFitTrkProp::print_timers () private
Definition at line 265 of file PHGenFitTrkProp.cc.
View newest version in sPHENIX GitHub at line 265 of file PHGenFitTrkProp.cc
References _t_full_fitting, _t_kalman_pat_rec, _t_output_io, _t_search_clusters, _t_search_clusters_encoding, _t_search_clusters_map_iter, _t_seeds_cleanup, _t_track_propagation, _t_translate1, _t_translate2, _t_translate3, _t_translate_to_PHGenFitTrack, and PHTimer::get_accumulated_time().
Referenced by Process().
int PHGenFitTrkProp::Process () override protected virtual
process event interface for trackers, called in process_event. implemented in derived classes
Implements PHTrackPropagating.
Definition at line 219 of file PHGenFitTrkProp.cc.
View newest version in sPHENIX GitHub at line 219 of file PHGenFitTrkProp.cc
References _event, _gftrk_hitkey_map, _nlayers_intt, _nlayers_maps, _nlayers_tpc, _t_kalman_pat_rec, _vertex, _vertex_error, PHTrackPropagating::_vertex_map, Fun4AllReturnCodes::EVENT_OK, SvtxVertexMap::get(), SvtxVertex::get_error(), SvtxVertex::get_x(), SvtxVertex::get_y(), SvtxVertex::get_z(), KalmanTrkProp(), print_timers(), PHTimer::restart(), SvtxVertexMap::size(), PHTimer::stop(), v, and Fun4AllBase::Verbosity().
float PHGenFitTrkProp::ptToKappa (float pt) private
convert from momentum to inverse curvature
std::shared_ptr< PHGenFit::Track > PHGenFitTrkProp::ReFitTrack (SvtxTrack * intrack) private
mu+: -13 mu-: 13 pi+: 211 pi-: -211 e-: 11 e+: -11
Fit the track ret code 0 means 0 error or good status
Definition at line 789 of file PHGenFitTrkProp.cc.
View newest version in sPHENIX GitHub at line 789 of file PHGenFitTrkProp.cc
References PHTrackPropagating::_cluster_map, _fitter, _ntrack, _primary_pid_guess, _topNode, SvtxTrack::begin_cluster_keys(), SvtxTrack::end_cluster_keys(), CylinderGeomIntt::find_segment_center(), CylinderGeom_Mvtx::find_sensor_center(), TrkrClusterContainer::findCluster(), CylinderGeom_Mvtx::get_stave_phi_tilt(), CylinderGeomIntt::get_strip_phi_tilt(), MvtxDefs::getChipId(), findNode::getClass(), InttDefs::getLadderPhiId(), InttDefs::getLadderZId(), TrkrDefs::getLayer(), PHG4CylinderGeomContainer::GetLayerGeom(), TrkrCluster::getPosition(), TrkrCluster::getRPhiError(), MvtxDefs::getStaveId(), TrkrDefs::getTrkrId(), TrkrCluster::getZError(), i, TrkrDefs::inttId, j, layer, LogError, TrkrDefs::mvtxId, n, PHWHERE, Acts::Test::pos, r, Fun4AllBase::Verbosity(), x, and y.
std::vector< TrkrDefs::cluskey > PHGenFitTrkProp::SearchHitsNearBy (const unsigned int ivert, const unsigned int layer, const float z_center, const float phi_center, const float z_window, const float phi_window) private
TrackPropPatRec Call.
Definition at line 1660 of file PHGenFitTrkProp.cc.
View newest version in sPHENIX GitHub at line 1660 of file PHGenFitTrkProp.cc
References _half_max_phi, _half_max_theta, _layer_thetaID_phiID_clusterID, _layer_thetaID_phiID_clusterID_phiSize, _layer_thetaID_phiID_clusterID_zSize, _t_search_clusters_encoding, _t_search_clusters_map_iter, count, encode_cluster_index(), PHTimer::restart(), PHTimer::stop(), and Fun4AllBase::Verbosity().
Referenced by TrackPropPatRec().
void PHGenFitTrkProp::set_analyzing_mode (bool analyzingMode) inline
Definition at line 163 of file PHGenFitTrkProp.h.
View newest version in sPHENIX GitHub at line 163 of file PHGenFitTrkProp.h
References _analyzing_mode.
void PHGenFitTrkProp::set_beam_constraint (bool beamConstraint) inline
Definition at line 458 of file PHGenFitTrkProp.h.
View newest version in sPHENIX GitHub at line 458 of file PHGenFitTrkProp.h
References _use_beam.
void PHGenFitTrkProp::set_blowup_factor (float blowupFactor) inline
Definition at line 323 of file PHGenFitTrkProp.h.
View newest version in sPHENIX GitHub at line 323 of file PHGenFitTrkProp.h
References _blowup_factor.
void PHGenFitTrkProp::set_do_evt_display (bool doEvtDisplay) inline
Definition at line 148 of file PHGenFitTrkProp.h.
View newest version in sPHENIX GitHub at line 148 of file PHGenFitTrkProp.h
References _do_evt_display.
void PHGenFitTrkProp::set_init_direction (int initDirection) inline
Definition at line 274 of file PHGenFitTrkProp.h.
View newest version in sPHENIX GitHub at line 274 of file PHGenFitTrkProp.h
References _init_direction.
void PHGenFitTrkProp::set_max_consecutive_missing_layer (unsigned int maxConsecutiveMissingLayer) inline
Definition at line 233 of file PHGenFitTrkProp.h.
View newest version in sPHENIX GitHub at line 233 of file PHGenFitTrkProp.h
References _max_consecutive_missing_layer.
void PHGenFitTrkProp::set_max_incr_chi2 (float maxIncrChi2) inline
Definition at line 223 of file PHGenFitTrkProp.h.
View newest version in sPHENIX GitHub at line 223 of file PHGenFitTrkProp.h
References _max_incr_chi2.
void PHGenFitTrkProp::set_max_merging_deta (float maxMergingDeta) inline
Definition at line 173 of file PHGenFitTrkProp.h.
View newest version in sPHENIX GitHub at line 173 of file PHGenFitTrkProp.h
References _max_merging_deta.
void PHGenFitTrkProp::set_max_merging_dphi (float maxMergingDphi) inline
Definition at line 183 of file PHGenFitTrkProp.h.
View newest version in sPHENIX GitHub at line 183 of file PHGenFitTrkProp.h
References _max_merging_dphi.
void PHGenFitTrkProp::set_max_merging_dr (float maxMergingDr) inline
Definition at line 193 of file PHGenFitTrkProp.h.
View newest version in sPHENIX GitHub at line 193 of file PHGenFitTrkProp.h
References _max_merging_dr.
void PHGenFitTrkProp::set_max_merging_dz (float maxMergingDz) inline
Definition at line 203 of file PHGenFitTrkProp.h.
View newest version in sPHENIX GitHub at line 203 of file PHGenFitTrkProp.h
References _max_merging_dz.
void PHGenFitTrkProp::set_max_search_win_phi_intt (int inttlayer, float maxSearchWinPhiIntt) inline
Definition at line 333 of file PHGenFitTrkProp.h.
View newest version in sPHENIX GitHub at line 333 of file PHGenFitTrkProp.h
References _max_search_win_phi_intt.
void PHGenFitTrkProp::set_max_search_win_phi_maps (float maxSearchWinPhiMaps) inline
Definition at line 343 of file PHGenFitTrkProp.h.
View newest version in sPHENIX GitHub at line 343 of file PHGenFitTrkProp.h
References _max_search_win_phi_maps.
void PHGenFitTrkProp::set_max_search_win_phi_micromegas (int layer, float maxSearchWinPhi) inline
Definition at line 303 of file PHGenFitTrkProp.h.
View newest version in sPHENIX GitHub at line 303 of file PHGenFitTrkProp.h
References _max_search_win_phi_micromegas, and layer.
void PHGenFitTrkProp::set_max_search_win_phi_tpc (float maxSearchWinPhi) inline
Definition at line 284 of file PHGenFitTrkProp.h.
View newest version in sPHENIX GitHub at line 284 of file PHGenFitTrkProp.h
References _max_search_win_phi_tpc.
void PHGenFitTrkProp::set_max_search_win_theta_intt (int inttlayer, float maxSearchWinThetaIntt) inline
Definition at line 353 of file PHGenFitTrkProp.h.
View newest version in sPHENIX GitHub at line 353 of file PHGenFitTrkProp.h
References _max_search_win_theta_intt.
void PHGenFitTrkProp::set_max_search_win_theta_maps (float maxSearchWinThetaMaps) inline
Definition at line 363 of file PHGenFitTrkProp.h.
View newest version in sPHENIX GitHub at line 363 of file PHGenFitTrkProp.h
References _max_search_win_theta_maps.
void PHGenFitTrkProp::set_max_search_win_theta_micromegas (int layer, float maxSearchWinZ) inline
Definition at line 313 of file PHGenFitTrkProp.h.
View newest version in sPHENIX GitHub at line 313 of file PHGenFitTrkProp.h
References _max_search_win_theta_micromegas, and layer.
void PHGenFitTrkProp::set_max_search_win_theta_tpc (float maxSearchWinZ) inline
Definition at line 294 of file PHGenFitTrkProp.h.
View newest version in sPHENIX GitHub at line 294 of file PHGenFitTrkProp.h
References _max_search_win_theta_tpc.
void PHGenFitTrkProp::set_max_share_hits (unsigned int maxShareHits) inline
Definition at line 254 of file PHGenFitTrkProp.h.
View newest version in sPHENIX GitHub at line 254 of file PHGenFitTrkProp.h
References _max_share_hits.
void PHGenFitTrkProp::set_max_splitting_chi2 (float maxSplittingChi2) inline
Definition at line 264 of file PHGenFitTrkProp.h.
View newest version in sPHENIX GitHub at line 264 of file PHGenFitTrkProp.h
References _max_splitting_chi2.
void PHGenFitTrkProp::set_min_good_track_hits (unsigned int minGoodTrackHits) inline
Definition at line 244 of file PHGenFitTrkProp.h.
View newest version in sPHENIX GitHub at line 244 of file PHGenFitTrkProp.h
References _min_good_track_hits.
void PHGenFitTrkProp::set_min_search_win_phi_intt (int inttlayer, float minSearchWinPhiIntt) inline
Definition at line 373 of file PHGenFitTrkProp.h.
View newest version in sPHENIX GitHub at line 373 of file PHGenFitTrkProp.h
References _min_search_win_phi_intt.
void PHGenFitTrkProp::set_min_search_win_phi_maps (float minSearchWinPhiMaps) inline
Definition at line 383 of file PHGenFitTrkProp.h.
View newest version in sPHENIX GitHub at line 383 of file PHGenFitTrkProp.h
References _min_search_win_phi_maps.
void PHGenFitTrkProp::set_min_search_win_phi_micromegas (int layer, float minSearchWinPhimicromegas) inline
Definition at line 403 of file PHGenFitTrkProp.h.
View newest version in sPHENIX GitHub at line 403 of file PHGenFitTrkProp.h
References _min_search_win_phi_micromegas, and layer.
void PHGenFitTrkProp::set_min_search_win_phi_tpc (float minSearchWinPhiTpc) inline
Definition at line 393 of file PHGenFitTrkProp.h.
View newest version in sPHENIX GitHub at line 393 of file PHGenFitTrkProp.h
References _min_search_win_phi_tpc.
void PHGenFitTrkProp::set_min_search_win_theta_intt (int inttlayer, float minSearchWinThetaIntt) inline
Definition at line 413 of file PHGenFitTrkProp.h.
View newest version in sPHENIX GitHub at line 413 of file PHGenFitTrkProp.h
References _min_search_win_theta_intt.
void PHGenFitTrkProp::set_min_search_win_theta_maps (float minSearchWinThetaMaps) inline
Definition at line 423 of file PHGenFitTrkProp.h.
View newest version in sPHENIX GitHub at line 423 of file PHGenFitTrkProp.h
References _min_search_win_theta_maps.
void PHGenFitTrkProp::set_min_search_win_theta_micromegas (int layer, float minSearchWinThetamicromegas) inline
Definition at line 443 of file PHGenFitTrkProp.h.
View newest version in sPHENIX GitHub at line 443 of file PHGenFitTrkProp.h
References _min_search_win_theta_micromegas, and layer.
void PHGenFitTrkProp::set_min_search_win_theta_tpc (float minSearchWinThetaTpc) inline
Definition at line 433 of file PHGenFitTrkProp.h.
View newest version in sPHENIX GitHub at line 433 of file PHGenFitTrkProp.h
References _min_search_win_theta_tpc.
void PHGenFitTrkProp::set_primary_pid_guess (int primaryPidGuess) inline
Definition at line 453 of file PHGenFitTrkProp.h.
View newest version in sPHENIX GitHub at line 453 of file PHGenFitTrkProp.h
References _primary_pid_guess.
void PHGenFitTrkProp::set_search_win_phi (float searchWinMultiplier) inline
Definition at line 138 of file PHGenFitTrkProp.h.
View newest version in sPHENIX GitHub at line 138 of file PHGenFitTrkProp.h
References _search_win_phi.
void PHGenFitTrkProp::set_search_win_theta (float searchWinZ) inline
Definition at line 213 of file PHGenFitTrkProp.h.
View newest version in sPHENIX GitHub at line 213 of file PHGenFitTrkProp.h
References _search_win_theta.
void PHGenFitTrkProp::set_track_fitting_alg_name (const std::string & trackFittingAlgName) inline
Definition at line 158 of file PHGenFitTrkProp.h.
View newest version in sPHENIX GitHub at line 158 of file PHGenFitTrkProp.h
References _track_fitting_alg_name.
int PHGenFitTrkProp::Setup (PHCompositeNode * topNode) override protected virtual
setup interface for trackers, called in InitRun, setup things like pointers to nodes. overrided in derived classes
Initilize parameters
Reimplemented from PHTrackPropagating.
Definition at line 127 of file PHGenFitTrkProp.cc.
View newest version in sPHENIX GitHub at line 127 of file PHGenFitTrkProp.cc
References _analyzing_file, _analyzing_mode, _analyzing_ntuple, _max_incr_chi2, _max_incr_chi2s, _nlayers_all, _search_win_phi, _search_win_theta, _search_wins_phi, _search_wins_theta, _t_full_fitting, _t_kalman_pat_rec, _t_output_io, _t_search_clusters, _t_search_clusters_encoding, _t_search_clusters_map_iter, _t_seeds_cleanup, _t_track_propagation, _t_translate1, _t_translate2, _t_translate3, _t_translate_to_PHGenFitTrack, Fun4AllReturnCodes::EVENT_OK, GetNodes(), InitializeGeometry(), InitializePHGenFit(), layer, PHTrackPropagating::Setup(), and PHTimer::stop().
void PHGenFitTrkProp::shift_coordinate_system (double dx, double dy, double dz) private
translate the clusters, tracks, and vertex from one origin to another
int PHGenFitTrkProp::SvtxTrackToPHGenFitTracks (const SvtxTrack * svtxtrack) private
KalmanTrkProp Call.
Definition at line 957 of file PHGenFitTrkProp.cc.
View newest version in sPHENIX GitHub at line 957 of file PHGenFitTrkProp.cc
References PHTrackPropagating::_cluster_map, _fitter, _ntrack, _PHGenFitTracks, _primary_pid_guess, _use_beam, _vertex, SvtxTrack::begin_cluster_keys(), SvtxTrack::end_cluster_keys(), Fun4AllReturnCodes::EVENT_OK, TrkrClusterContainer::findCluster(), SvtxTrack::get_error(), SvtxTrack::get_id(), SvtxTrack::get_px(), SvtxTrack::get_py(), SvtxTrack::get_pz(), SvtxTrack::get_vertex_id(), SvtxTrack::get_x(), SvtxTrack::get_y(), SvtxTrack::get_z(), TrkrDefs::getLayer(), TrkrCluster::getPosition(), i, j, LogError, PHWHERE, Acts::Test::pos, r, PHGenFit::Measurement::set_cluster_key(), SvtxTrack::size_cluster_keys(), TrkrClusterToPHGenFitMeasurement(), and Fun4AllBase::Verbosity().
Referenced by KalmanTrkProp().
int PHGenFitTrkProp::TrackPropPatRec (const unsigned int ivert, MapPHGenFitTrack::iterator & track_iter, const unsigned int init_layer = 0, const unsigned int end_layer = 66, const bool use_fitted_state_once = false) private
Find the last layer of with TrackPoint (TP) Asumming measuremnts are sorted by radius and cluster keys are syncronized with the TP IDs
if miss too many layers terminate track propagating
Track succesfully propagated and return 0
Definition at line 1096 of file PHGenFitTrkProp.cc.
View newest version in sPHENIX GitHub at line 1096 of file PHGenFitTrkProp.cc
References _blowup_factor, PHTrackPropagating::_cluster_map, _event, _firstlayer_intt, _firstlayer_micromegas, _layer_ilayer_map_all, _max_consecutive_missing_layer, _max_incr_chi2s, _max_search_win_phi_intt, _max_search_win_phi_maps, _max_search_win_phi_micromegas, _max_search_win_phi_tpc, _max_search_win_theta_intt, _max_search_win_theta_maps, _max_search_win_theta_micromegas, _max_search_win_theta_tpc, _max_splitting_chi2, _min_good_track_hits, _min_search_win_phi_intt, _min_search_win_phi_maps, _min_search_win_phi_micromegas, _min_search_win_phi_tpc, _min_search_win_theta_intt, _min_search_win_theta_maps, _min_search_win_theta_micromegas, _min_search_win_theta_tpc, _nlayers_all, _nlayers_intt, _nlayers_maps, _PHGenFitTracks, _radii_all, _search_wins_phi, _search_wins_theta, _t_search_clusters, _t_track_propagation, _vertex, Fun4AllReturnCodes::ABORTRUN, assert, PHGenFitTrkProp::TrackQuality::chi2, Acts::Test::cov, Acts::UnitConstants::e, TrkrClusterContainer::findCluster(), genfit::MeasuredStateOnPlane::get6DCov(), TrkrDefs::getLayer(), genfit::StateOnPlane::getPos(), TrkrCluster::getX(), TrkrCluster::getY(), i, is_intt_layer(), is_maps_layer(), is_micromegas_layer(), is_tpc_layer(), layer, LogError, LogWarning, PHGenFitTrkProp::TrackQuality::ndf, PHGenFitTrkProp::TrackQuality::nhits, PHGenFitTrkProp::TrackQuality::nintt, PHGenFitTrkProp::TrackQuality::nmaps, PHGenFitTrkProp::TrackQuality::nmicromegas, PHGenFitTrkProp::TrackQuality::ntpc, PHWHERE, Acts::Test::pos, printf(), PHTimer::restart(), SearchHitsNearBy(), size, PHTimer::stop(), TrkrClusterToPHGenFitMeasurement(), and Fun4AllBase::Verbosity().
Referenced by KalmanTrkProp().
PHGenFit::Measurement * PHGenFitTrkProp::TrkrClusterToPHGenFitMeasurement (const TrkrCluster * cluster) private
Definition at line 1534 of file PHGenFitTrkProp.cc.
View newest version in sPHENIX GitHub at line 1534 of file PHGenFitTrkProp.cc
References _geom_container_intt, _geom_container_maps, CylinderGeomIntt::find_segment_center(), CylinderGeom_Mvtx::find_sensor_center(), MvtxDefs::getChipId(), TrkrCluster::getClusKey(), InttDefs::getLadderPhiId(), InttDefs::getLadderZId(), TrkrDefs::getLayer(), PHG4CylinderGeomContainer::GetLayerGeom(), TrkrCluster::getPosition(), TrkrCluster::getRPhiError(), MvtxDefs::getStaveId(), TrkrDefs::getTrkrId(), TrkrCluster::getZError(), TrkrDefs::inttId, layer, TrkrDefs::mvtxId, n, Acts::Test::pos, and PHGenFit::Measurement::set_cluster_key().
Referenced by SvtxTrackToPHGenFitTracks(), and TrackPropPatRec().
Member Data Documentation
TFile* PHGenFitTrkProp::_analyzing_file = nullptr private
Definition at line 591 of file PHGenFitTrkProp.h.
View newest version in sPHENIX GitHub at line 591 of file PHGenFitTrkProp.h
Referenced by End(), and Setup().
bool PHGenFitTrkProp::_analyzing_mode = false private
Definition at line 590 of file PHGenFitTrkProp.h.
View newest version in sPHENIX GitHub at line 590 of file PHGenFitTrkProp.h
Referenced by End(), set_analyzing_mode(), and Setup().
TNtuple* PHGenFitTrkProp::_analyzing_ntuple = nullptr private
Definition at line 592 of file PHGenFitTrkProp.h.
View newest version in sPHENIX GitHub at line 592 of file PHGenFitTrkProp.h
Referenced by End(), and Setup().
BbcVertexMap* PHGenFitTrkProp::_bbc_vertexes = nullptr private
Definition at line 583 of file PHGenFitTrkProp.h.
View newest version in sPHENIX GitHub at line 583 of file PHGenFitTrkProp.h
Referenced by GetNodes().
float PHGenFitTrkProp::_blowup_factor = 1 private
Definition at line 664 of file PHGenFitTrkProp.h.
View newest version in sPHENIX GitHub at line 664 of file PHGenFitTrkProp.h
Referenced by get_blowup_factor(), set_blowup_factor(), and TrackPropPatRec().
double PHGenFitTrkProp::_cut_min_pT = 0.2 private
Definition at line 609 of file PHGenFitTrkProp.h.
View newest version in sPHENIX GitHub at line 609 of file PHGenFitTrkProp.h
bool PHGenFitTrkProp::_do_evt_display = false private
Definition at line 611 of file PHGenFitTrkProp.h.
View newest version in sPHENIX GitHub at line 611 of file PHGenFitTrkProp.h
Referenced by End(), InitializePHGenFit(), is_do_evt_display(), KalmanTrkProp(), and set_do_evt_display().
int PHGenFitTrkProp::_event = 0 private
Definition at line 563 of file PHGenFitTrkProp.h.
View newest version in sPHENIX GitHub at line 563 of file PHGenFitTrkProp.h
Referenced by KalmanTrkProp(), PHGenFitTrkProp(), Process(), and TrackPropPatRec().
unsigned int PHGenFitTrkProp::_firstlayer_intt = 3 private
Definition at line 621 of file PHGenFitTrkProp.h.
View newest version in sPHENIX GitHub at line 621 of file PHGenFitTrkProp.h
Referenced by is_intt_layer(), and TrackPropPatRec().
unsigned int PHGenFitTrkProp::_firstlayer_maps = 0 private
Definition at line 620 of file PHGenFitTrkProp.h.
View newest version in sPHENIX GitHub at line 620 of file PHGenFitTrkProp.h
Referenced by is_maps_layer().
unsigned int PHGenFitTrkProp::_firstlayer_micromegas = 55 private
Definition at line 623 of file PHGenFitTrkProp.h.
View newest version in sPHENIX GitHub at line 623 of file PHGenFitTrkProp.h
Referenced by is_micromegas_layer(), and TrackPropPatRec().
unsigned int PHGenFitTrkProp::_firstlayer_tpc = 7 private
Definition at line 622 of file PHGenFitTrkProp.h.
View newest version in sPHENIX GitHub at line 622 of file PHGenFitTrkProp.h
Referenced by is_tpc_layer().
std::unique_ptr<PHGenFit::Fitter> PHGenFitTrkProp::_fitter private
Definition at line 603 of file PHGenFitTrkProp.h.
View newest version in sPHENIX GitHub at line 603 of file PHGenFitTrkProp.h
Referenced by End(), InitializePHGenFit(), KalmanTrkProp(), OutputPHGenFitTrack(), ReFitTrack(), and SvtxTrackToPHGenFitTracks().
PHG4CylinderGeomContainer* PHGenFitTrkProp::_geom_container_intt = nullptr private
Definition at line 587 of file PHGenFitTrkProp.h.
View newest version in sPHENIX GitHub at line 587 of file PHGenFitTrkProp.h
Referenced by GetNodes(), and TrkrClusterToPHGenFitMeasurement().
PHG4CylinderGeomContainer* PHGenFitTrkProp::_geom_container_maps = nullptr private
Definition at line 588 of file PHGenFitTrkProp.h.
View newest version in sPHENIX GitHub at line 588 of file PHGenFitTrkProp.h
Referenced by GetNodes(), and TrkrClusterToPHGenFitMeasurement().
std::multimap<TrkrDefs::cluskey, unsigned int> PHGenFitTrkProp::_gftrk_hitkey_map private
Definition at line 585 of file PHGenFitTrkProp.h.
View newest version in sPHENIX GitHub at line 585 of file PHGenFitTrkProp.h
Referenced by check_track_exists(), OutputPHGenFitTrack(), and Process().
float PHGenFitTrkProp::_half_max_phi = M_PI private
Definition at line 657 of file PHGenFitTrkProp.h.
View newest version in sPHENIX GitHub at line 657 of file PHGenFitTrkProp.h
Referenced by encode_cluster_index(), and SearchHitsNearBy().
float PHGenFitTrkProp::_half_max_theta = M_PI/2 private
Definition at line 656 of file PHGenFitTrkProp.h.
View newest version in sPHENIX GitHub at line 656 of file PHGenFitTrkProp.h
Referenced by encode_cluster_index(), and SearchHitsNearBy().
int PHGenFitTrkProp::_init_direction = -1 private
+1: inside out; -1: outside in
Definition at line 663 of file PHGenFitTrkProp.h.
View newest version in sPHENIX GitHub at line 663 of file PHGenFitTrkProp.h
Referenced by get_init_direction(), KalmanTrkProp(), and set_init_direction().
std::map<int, unsigned int> PHGenFitTrkProp::_layer_ilayer_map_all private
Definition at line 625 of file PHGenFitTrkProp.h.
View newest version in sPHENIX GitHub at line 625 of file PHGenFitTrkProp.h
Referenced by InitializeGeometry(), and TrackPropPatRec().
std::vector<std::multimap<unsigned int, TrkrDefs::cluskey> > PHGenFitTrkProp::_layer_thetaID_phiID_clusterID private
Definition at line 654 of file PHGenFitTrkProp.h.
View newest version in sPHENIX GitHub at line 654 of file PHGenFitTrkProp.h
Referenced by BuildLayerZPhiHitMap(), KalmanTrkProp(), and SearchHitsNearBy().
float PHGenFitTrkProp::_layer_thetaID_phiID_clusterID_phiSize = 0.12/30 private
Definition at line 658 of file PHGenFitTrkProp.h.
View newest version in sPHENIX GitHub at line 658 of file PHGenFitTrkProp.h
Referenced by encode_cluster_index(), and SearchHitsNearBy().
float PHGenFitTrkProp::_layer_thetaID_phiID_clusterID_zSize = 0.17/30 private
Definition at line 659 of file PHGenFitTrkProp.h.
View newest version in sPHENIX GitHub at line 659 of file PHGenFitTrkProp.h
Referenced by encode_cluster_index(), and SearchHitsNearBy().
unsigned int PHGenFitTrkProp::_max_consecutive_missing_layer = 20 private
Definition at line 666 of file PHGenFitTrkProp.h.
View newest version in sPHENIX GitHub at line 666 of file PHGenFitTrkProp.h
Referenced by get_max_consecutive_missing_layer(), set_max_consecutive_missing_layer(), and TrackPropPatRec().
float PHGenFitTrkProp::_max_incr_chi2 = 20 private
Definition at line 667 of file PHGenFitTrkProp.h.
View newest version in sPHENIX GitHub at line 667 of file PHGenFitTrkProp.h
Referenced by get_max_incr_chi2(), set_max_incr_chi2(), and Setup().
std::map<int, float> PHGenFitTrkProp::_max_incr_chi2s private
Definition at line 668 of file PHGenFitTrkProp.h.
View newest version in sPHENIX GitHub at line 668 of file PHGenFitTrkProp.h
Referenced by Setup(), and TrackPropPatRec().
float PHGenFitTrkProp::_max_merging_deta = 0.1 private
Definition at line 596 of file PHGenFitTrkProp.h.
View newest version in sPHENIX GitHub at line 596 of file PHGenFitTrkProp.h
Referenced by get_max_merging_deta(), and set_max_merging_deta().
float PHGenFitTrkProp::_max_merging_dphi = 0.1 private
Cleanup Seeds.
Definition at line 595 of file PHGenFitTrkProp.h.
View newest version in sPHENIX GitHub at line 595 of file PHGenFitTrkProp.h
Referenced by get_max_merging_dphi(), and set_max_merging_dphi().
float PHGenFitTrkProp::_max_merging_dr = 0.1 private
Definition at line 597 of file PHGenFitTrkProp.h.
View newest version in sPHENIX GitHub at line 597 of file PHGenFitTrkProp.h
Referenced by get_max_merging_dr(), and set_max_merging_dr().
float PHGenFitTrkProp::_max_merging_dz = 0.1 private
Definition at line 598 of file PHGenFitTrkProp.h.
View newest version in sPHENIX GitHub at line 598 of file PHGenFitTrkProp.h
Referenced by get_max_merging_dz(), and set_max_merging_dz().
std::array<float,4> PHGenFitTrkProp::_max_search_win_phi_intt = {{ 0.2, 0.2, 0.005, 0.005 }} private
Definition at line 639 of file PHGenFitTrkProp.h.
View newest version in sPHENIX GitHub at line 639 of file PHGenFitTrkProp.h
Referenced by get_max_search_win_phi_intt(), set_max_search_win_phi_intt(), and TrackPropPatRec().
float PHGenFitTrkProp::_max_search_win_phi_maps = 0.005 private
Definition at line 644 of file PHGenFitTrkProp.h.
View newest version in sPHENIX GitHub at line 644 of file PHGenFitTrkProp.h
Referenced by get_max_search_win_phi_maps(), set_max_search_win_phi_maps(), and TrackPropPatRec().
std::array<float,2> PHGenFitTrkProp::_max_search_win_phi_micromegas = {{ 0.004, 0.62}} private
Definition at line 629 of file PHGenFitTrkProp.h.
View newest version in sPHENIX GitHub at line 629 of file PHGenFitTrkProp.h
Referenced by get_max_search_win_phi_micromegas(), set_max_search_win_phi_micromegas(), and TrackPropPatRec().
float PHGenFitTrkProp::_max_search_win_phi_tpc = 0.004 private
Definition at line 634 of file PHGenFitTrkProp.h.
View newest version in sPHENIX GitHub at line 634 of file PHGenFitTrkProp.h
Referenced by get_max_search_win_phi_tpc(), set_max_search_win_phi_tpc(), and TrackPropPatRec().
std::array<float,4> PHGenFitTrkProp::_max_search_win_theta_intt = {{ 0.01, 0.01, 0.2, 0.2 }} private
Definition at line 641 of file PHGenFitTrkProp.h.
View newest version in sPHENIX GitHub at line 641 of file PHGenFitTrkProp.h
Referenced by get_max_search_win_theta_intt(), set_max_search_win_theta_intt(), and TrackPropPatRec().
float PHGenFitTrkProp::_max_search_win_theta_maps = 0.04 private
Definition at line 646 of file PHGenFitTrkProp.h.
View newest version in sPHENIX GitHub at line 646 of file PHGenFitTrkProp.h
Referenced by get_max_search_win_theta_maps(), set_max_search_win_theta_maps(), and TrackPropPatRec().
std::array<float,2> PHGenFitTrkProp::_max_search_win_theta_micromegas = {{ 1.24, 0.004}} private
Definition at line 631 of file PHGenFitTrkProp.h.
View newest version in sPHENIX GitHub at line 631 of file PHGenFitTrkProp.h
Referenced by get_max_search_win_theta_micromegas(), set_max_search_win_theta_micromegas(), and TrackPropPatRec().
float PHGenFitTrkProp::_max_search_win_theta_tpc = 0.004 private
Definition at line 636 of file PHGenFitTrkProp.h.
View newest version in sPHENIX GitHub at line 636 of file PHGenFitTrkProp.h
Referenced by get_max_search_win_theta_tpc(), set_max_search_win_theta_tpc(), and TrackPropPatRec().
unsigned int PHGenFitTrkProp::_max_share_hits = 3 private
if two seeds have common hits more than this number, merge them
Definition at line 601 of file PHGenFitTrkProp.h.
View newest version in sPHENIX GitHub at line 601 of file PHGenFitTrkProp.h
Referenced by get_max_share_hits(), and set_max_share_hits().
float PHGenFitTrkProp::_max_splitting_chi2 = 20 private
Definition at line 670 of file PHGenFitTrkProp.h.
View newest version in sPHENIX GitHub at line 670 of file PHGenFitTrkProp.h
Referenced by get_max_splitting_chi2(), set_max_splitting_chi2(), and TrackPropPatRec().
unsigned int PHGenFitTrkProp::_min_good_track_hits = 30 private
Definition at line 672 of file PHGenFitTrkProp.h.
View newest version in sPHENIX GitHub at line 672 of file PHGenFitTrkProp.h
Referenced by get_min_good_track_hits(), KalmanTrkProp(), set_min_good_track_hits(), and TrackPropPatRec().
std::array<float,4> PHGenFitTrkProp::_min_search_win_phi_intt = {{ 0.2, 0.2, 0, 0 }} private
Definition at line 640 of file PHGenFitTrkProp.h.
View newest version in sPHENIX GitHub at line 640 of file PHGenFitTrkProp.h
Referenced by get_min_search_win_phi_intt(), set_min_search_win_phi_intt(), and TrackPropPatRec().
float PHGenFitTrkProp::_min_search_win_phi_maps = 0 private
Definition at line 645 of file PHGenFitTrkProp.h.
View newest version in sPHENIX GitHub at line 645 of file PHGenFitTrkProp.h
Referenced by get_min_search_win_phi_maps(), set_min_search_win_phi_maps(), and TrackPropPatRec().
std::array<float,2> PHGenFitTrkProp::_min_search_win_phi_micromegas = {{ 0, 0.31 }} private
Definition at line 630 of file PHGenFitTrkProp.h.
View newest version in sPHENIX GitHub at line 630 of file PHGenFitTrkProp.h
Referenced by get_min_search_win_phi_micromegas(), set_min_search_win_phi_micromegas(), and TrackPropPatRec().
float PHGenFitTrkProp::_min_search_win_phi_tpc = 0 private
Definition at line 635 of file PHGenFitTrkProp.h.
View newest version in sPHENIX GitHub at line 635 of file PHGenFitTrkProp.h
Referenced by get_min_search_win_phi_tpc(), set_min_search_win_phi_tpc(), and TrackPropPatRec().
std::array<float,4> PHGenFitTrkProp::_min_search_win_theta_intt = {{ 0, 0, 0.2, 0.2 }} private
Definition at line 642 of file PHGenFitTrkProp.h.
View newest version in sPHENIX GitHub at line 642 of file PHGenFitTrkProp.h
Referenced by get_min_search_win_theta_intt(), set_min_search_win_theta_intt(), and TrackPropPatRec().
float PHGenFitTrkProp::_min_search_win_theta_maps = 0 private
Definition at line 647 of file PHGenFitTrkProp.h.
View newest version in sPHENIX GitHub at line 647 of file PHGenFitTrkProp.h
Referenced by get_min_search_win_theta_maps(), set_min_search_win_theta_maps(), and TrackPropPatRec().
std::array<float,2> PHGenFitTrkProp::_min_search_win_theta_micromegas = {{ 0.62, 0}} private
Definition at line 632 of file PHGenFitTrkProp.h.
View newest version in sPHENIX GitHub at line 632 of file PHGenFitTrkProp.h
Referenced by get_min_search_win_theta_micromegas(), set_min_search_win_theta_micromegas(), and TrackPropPatRec().
float PHGenFitTrkProp::_min_search_win_theta_tpc = 0 private
Definition at line 637 of file PHGenFitTrkProp.h.
View newest version in sPHENIX GitHub at line 637 of file PHGenFitTrkProp.h
Referenced by get_min_search_win_theta_tpc(), set_min_search_win_theta_tpc(), and TrackPropPatRec().
int PHGenFitTrkProp::_nlayers_all = 55 private
Definition at line 618 of file PHGenFitTrkProp.h.
View newest version in sPHENIX GitHub at line 618 of file PHGenFitTrkProp.h
Referenced by InitializeGeometry(), KalmanTrkProp(), Setup(), and TrackPropPatRec().
unsigned int PHGenFitTrkProp::_nlayers_intt = 4 private
Definition at line 614 of file PHGenFitTrkProp.h.
View newest version in sPHENIX GitHub at line 614 of file PHGenFitTrkProp.h
Referenced by is_intt_layer(), Process(), and TrackPropPatRec().
unsigned int PHGenFitTrkProp::_nlayers_maps = 3 private
Definition at line 613 of file PHGenFitTrkProp.h.
View newest version in sPHENIX GitHub at line 613 of file PHGenFitTrkProp.h
Referenced by is_maps_layer(), Process(), and TrackPropPatRec().
unsigned int PHGenFitTrkProp::_nlayers_micromegas = 0 private
Definition at line 616 of file PHGenFitTrkProp.h.
View newest version in sPHENIX GitHub at line 616 of file PHGenFitTrkProp.h
Referenced by is_micromegas_layer().
unsigned int PHGenFitTrkProp::_nlayers_tpc = 48 private
Definition at line 615 of file PHGenFitTrkProp.h.
View newest version in sPHENIX GitHub at line 615 of file PHGenFitTrkProp.h
Referenced by is_tpc_layer(), and Process().
int PHGenFitTrkProp::_ntrack = 0 private
Definition at line 675 of file PHGenFitTrkProp.h.
View newest version in sPHENIX GitHub at line 675 of file PHGenFitTrkProp.h
Referenced by KalmanTrkProp(), ReFitTrack(), and SvtxTrackToPHGenFitTracks().
MapPHGenFitTrack PHGenFitTrkProp::_PHGenFitTracks private
Definition at line 661 of file PHGenFitTrkProp.h.
View newest version in sPHENIX GitHub at line 661 of file PHGenFitTrkProp.h
Referenced by KalmanTrkProp(), SvtxTrackToPHGenFitTracks(), and TrackPropPatRec().
int PHGenFitTrkProp::_primary_pid_guess = 211 private
Definition at line 608 of file PHGenFitTrkProp.h.
View newest version in sPHENIX GitHub at line 608 of file PHGenFitTrkProp.h
Referenced by get_primary_pid_guess(), ReFitTrack(), set_primary_pid_guess(), and SvtxTrackToPHGenFitTracks().
std::vector<float> PHGenFitTrkProp::_radii_all private
Definition at line 626 of file PHGenFitTrkProp.h.
View newest version in sPHENIX GitHub at line 626 of file PHGenFitTrkProp.h
Referenced by InitializeGeometry(), and TrackPropPatRec().
float PHGenFitTrkProp::_search_win_phi = 20 private
Definition at line 649 of file PHGenFitTrkProp.h.
View newest version in sPHENIX GitHub at line 649 of file PHGenFitTrkProp.h
Referenced by get_search_win_phi(), set_search_win_phi(), and Setup().
float PHGenFitTrkProp::_search_win_theta = 20 private
Definition at line 650 of file PHGenFitTrkProp.h.
View newest version in sPHENIX GitHub at line 650 of file PHGenFitTrkProp.h
Referenced by get_search_win_theta(), set_search_win_theta(), and Setup().
std::map<int, float> PHGenFitTrkProp::_search_wins_phi private
Definition at line 651 of file PHGenFitTrkProp.h.
View newest version in sPHENIX GitHub at line 651 of file PHGenFitTrkProp.h
Referenced by Setup(), and TrackPropPatRec().
std::map<int, float> PHGenFitTrkProp::_search_wins_theta private
Definition at line 652 of file PHGenFitTrkProp.h.
View newest version in sPHENIX GitHub at line 652 of file PHGenFitTrkProp.h
Referenced by Setup(), and TrackPropPatRec().
PHTimer* PHGenFitTrkProp::_t_full_fitting = nullptr private
Definition at line 574 of file PHGenFitTrkProp.h.
View newest version in sPHENIX GitHub at line 574 of file PHGenFitTrkProp.h
Referenced by End(), OutputPHGenFitTrack(), print_timers(), and Setup().
PHTimer* PHGenFitTrkProp::_t_kalman_pat_rec = nullptr private
Definition at line 569 of file PHGenFitTrkProp.h.
View newest version in sPHENIX GitHub at line 569 of file PHGenFitTrkProp.h
Referenced by End(), print_timers(), Process(), and Setup().
PHTimer* PHGenFitTrkProp::_t_output_io = nullptr private
Definition at line 575 of file PHGenFitTrkProp.h.
View newest version in sPHENIX GitHub at line 575 of file PHGenFitTrkProp.h
Referenced by End(), OutputPHGenFitTrack(), print_timers(), and Setup().
PHTimer* PHGenFitTrkProp::_t_search_clusters = nullptr private
Definition at line 570 of file PHGenFitTrkProp.h.
View newest version in sPHENIX GitHub at line 570 of file PHGenFitTrkProp.h
Referenced by End(), print_timers(), Setup(), and TrackPropPatRec().
PHTimer* PHGenFitTrkProp::_t_search_clusters_encoding = nullptr private
Definition at line 571 of file PHGenFitTrkProp.h.
View newest version in sPHENIX GitHub at line 571 of file PHGenFitTrkProp.h
Referenced by print_timers(), SearchHitsNearBy(), and Setup().
PHTimer* PHGenFitTrkProp::_t_search_clusters_map_iter = nullptr private
Definition at line 572 of file PHGenFitTrkProp.h.
View newest version in sPHENIX GitHub at line 572 of file PHGenFitTrkProp.h
Referenced by print_timers(), SearchHitsNearBy(), and Setup().
PHTimer* PHGenFitTrkProp::_t_seeds_cleanup = nullptr private
Definition at line 564 of file PHGenFitTrkProp.h.
View newest version in sPHENIX GitHub at line 564 of file PHGenFitTrkProp.h
Referenced by End(), print_timers(), and Setup().
PHTimer* PHGenFitTrkProp::_t_track_propagation = nullptr private
Definition at line 573 of file PHGenFitTrkProp.h.
View newest version in sPHENIX GitHub at line 573 of file PHGenFitTrkProp.h
Referenced by End(), print_timers(), Setup(), and TrackPropPatRec().
PHTimer* PHGenFitTrkProp::_t_translate1 = nullptr private
Definition at line 566 of file PHGenFitTrkProp.h.
View newest version in sPHENIX GitHub at line 566 of file PHGenFitTrkProp.h
Referenced by End(), print_timers(), and Setup().
PHTimer* PHGenFitTrkProp::_t_translate2 = nullptr private
Definition at line 567 of file PHGenFitTrkProp.h.
View newest version in sPHENIX GitHub at line 567 of file PHGenFitTrkProp.h
Referenced by End(), print_timers(), and Setup().
PHTimer* PHGenFitTrkProp::_t_translate3 = nullptr private
Definition at line 568 of file PHGenFitTrkProp.h.
View newest version in sPHENIX GitHub at line 568 of file PHGenFitTrkProp.h
Referenced by End(), print_timers(), and Setup().
PHTimer* PHGenFitTrkProp::_t_translate_to_PHGenFitTrack = nullptr private
Definition at line 565 of file PHGenFitTrkProp.h.
View newest version in sPHENIX GitHub at line 565 of file PHGenFitTrkProp.h
Referenced by End(), KalmanTrkProp(), print_timers(), and Setup().
PHCompositeNode* PHGenFitTrkProp::_topNode = nullptr private
Definition at line 674 of file PHGenFitTrkProp.h.
View newest version in sPHENIX GitHub at line 674 of file PHGenFitTrkProp.h
Referenced by GetNodes(), and ReFitTrack().
std::string PHGenFitTrkProp::_track_fitting_alg_name = "DafRef" private
KalmanFitterRefTrack, KalmanFitter, DafSimple, DafRef.
Definition at line 606 of file PHGenFitTrkProp.h.
View newest version in sPHENIX GitHub at line 606 of file PHGenFitTrkProp.h
Referenced by get_track_fitting_alg_name(), InitializePHGenFit(), and set_track_fitting_alg_name().
bool PHGenFitTrkProp::_use_beam private
Definition at line 676 of file PHGenFitTrkProp.h.
View newest version in sPHENIX GitHub at line 676 of file PHGenFitTrkProp.h
Referenced by set_beam_constraint(), and SvtxTrackToPHGenFitTracks().
std::vector<std::vector<float> > PHGenFitTrkProp::_vertex private
working array for collision vertex list
Definition at line 579 of file PHGenFitTrkProp.h.
View newest version in sPHENIX GitHub at line 579 of file PHGenFitTrkProp.h
Referenced by BuildLayerZPhiHitMap(), KalmanTrkProp(), OutputPHGenFitTrack(), Process(), SvtxTrackToPHGenFitTracks(), and TrackPropPatRec().
std::vector<std::vector<float> > PHGenFitTrkProp::_vertex_error private
sqrt(cov)
Definition at line 580 of file PHGenFitTrkProp.h.
View newest version in sPHENIX GitHub at line 580 of file PHGenFitTrkProp.h
Referenced by Process().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/trackreco/PHGenFitTrkProp.h
coresoftware/blob/master/offline/packages/trackreco/PHGenFitTrkProp.cc