Analysis Software: Jetscape::HadronizationManager Class Reference
Jetscape::HadronizationManager Class Reference
#include <JETSCAPE/blob/master/src/framework/HadronizationManager.h>
Public Member Functions
HadronizationManager ()
virtual ~HadronizationManager ()
virtual void Init ()
virtual void Exec ()
virtual void Clear ()
virtual void WriteTask (weak_ptr< JetScapeWriter > w)
int GetNumSignals ()
void CreateSignalSlots ()
void SetGetFinalPartonListConnected (bool m_GetFinalPartonListConnected)
const bool GetGetFinalPartonListConnected ()
void SetGetHadronListConnected (bool m_GetHadronListConnected)
const bool GetGetHadronListConnected ()
Public Member Functions inherited from Jetscape::JetScapeTask
JetScapeTask ()
virtual ~JetScapeTask ()
virtual void Finish ()
virtual void ExecuteTasks ()
virtual void ExecuteTask ()
virtual void InitTask ()
virtual void InitTasks ()
virtual void ClearTasks ()
virtual void ClearTask ()
virtual void FinishTask ()
virtual void FinishTasks ()
virtual void WriteTasks (weak_ptr< JetScapeWriter > w)
virtual void CollectHeader (weak_ptr< JetScapeWriter > w)
virtual void CollectHeaders (weak_ptr< JetScapeWriter > w)
virtual void Add (shared_ptr< JetScapeTask > m_tasks)
virtual const int GetMyTaskNumber () const
const vector< shared_ptr
< JetScapeTask > > GetTaskList () const
shared_ptr< JetScapeTask > GetTaskAt (int i)
void EraseTaskLast ()
void EraseTaskAt (int i)
void ResizeTaskList (int i)
void ClearTaskList ()
int GetNumberOfTasks ()
const bool GetActive () const
void SetActive (bool m_active_exec)
void SetId (string m_id)
const string GetId () const
Public Attributes
sigslot::signal1< vector
< shared_ptr< Hadron > > & > GetHadronList
sigslot::signal1< vector
< vector< shared_ptr< Parton > > > & > GetFinalPartonList
Private Attributes
bool GetFinalPartonListConnected
bool GetHadronListConnected
vector< vector< shared_ptr
< Parton > > > hd
vector< shared_ptr< Hadron > > hadrons
Detailed Description
Definition at line 27 of file HadronizationManager.h.
View newest version in sPHENIX GitHub at line 27 of file HadronizationManager.h
Constructor & Destructor Documentation
Jetscape::HadronizationManager::HadronizationManager ()
Definition at line 32 of file HadronizationManager.cc.
View newest version in sPHENIX GitHub at line 32 of file HadronizationManager.cc
References SetId(), and VERBOSE.
Jetscape::HadronizationManager::~HadronizationManager () virtual
Definition at line 39 of file HadronizationManager.cc.
View newest version in sPHENIX GitHub at line 39 of file HadronizationManager.cc
References Clear().
Member Function Documentation
void Jetscape::HadronizationManager::Clear (void) virtual
A virtual function to define a default Clear() function for a JetScapeTask. It can be overridden by different modules/tasks.
Reimplemented from Jetscape::JetScapeTask.
Definition at line 48 of file HadronizationManager.cc.
View newest version in sPHENIX GitHub at line 48 of file HadronizationManager.cc
References i, JSDEBUG, n, and VERBOSE.
void Jetscape::HadronizationManager::CreateSignalSlots ()
Definition at line 123 of file HadronizationManager.cc.
View newest version in sPHENIX GitHub at line 123 of file HadronizationManager.cc
References it.
void Jetscape::HadronizationManager::Exec () virtual
A virtual function to define a default Exec() function for a JetScapeTask. It can be overridden by different modules/tasks.
Reimplemented from Jetscape::JetScapeTask.
Definition at line 87 of file HadronizationManager.cc.
View newest version in sPHENIX GitHub at line 87 of file HadronizationManager.cc
References boost::dynamic_pointer_cast(), it, JSDEBUG, VERBOSE, and WARN.
const bool Jetscape::HadronizationManager::GetGetFinalPartonListConnected () inline
Definition at line 49 of file HadronizationManager.h.
View newest version in sPHENIX GitHub at line 49 of file HadronizationManager.h
References GetFinalPartonListConnected.
const bool Jetscape::HadronizationManager::GetGetHadronListConnected () inline
Definition at line 52 of file HadronizationManager.h.
View newest version in sPHENIX GitHub at line 52 of file HadronizationManager.h
References GetHadronListConnected.
int Jetscape::HadronizationManager::GetNumSignals ()
void Jetscape::HadronizationManager::Init () virtual
A virtual function to define a default initialization function for a JetScapeTask. It can be overridden by different modules tasks.
Reimplemented from Jetscape::JetScapeTask.
Definition at line 63 of file HadronizationManager.cc.
View newest version in sPHENIX GitHub at line 63 of file HadronizationManager.cc
References INFO, and WARN.
void Jetscape::HadronizationManager::SetGetFinalPartonListConnected (bool m_GetFinalPartonListConnected) inline
Definition at line 48 of file HadronizationManager.h.
View newest version in sPHENIX GitHub at line 48 of file HadronizationManager.h
References GetFinalPartonListConnected.
void Jetscape::HadronizationManager::SetGetHadronListConnected (bool m_GetHadronListConnected) inline
Definition at line 51 of file HadronizationManager.h.
View newest version in sPHENIX GitHub at line 51 of file HadronizationManager.h
References GetHadronListConnected.
void Jetscape::HadronizationManager::WriteTask (weak_ptr< JetScapeWriter > w) virtual
A virtual function to define a default WriteTask() function for a JetScapeTask. It can be overridden by different modules/tasks. Current setup: Every task gets handed a pointer to the writer and can add any information it likes to it (using predefined functions like WriteComment()) This is maximally flexible but makes it difficult to properly store information for a variety of outputs. E.g., sigmaGen: A HardProcess can easily write the xsec to any stream-type output using WriteComment. But to set it in a HepMC file, either HardProcess needs to make a case-by-case selection, meaning a new file format would need to percolate through multiple base classes, or the writer needs to know this information and implement WriteEvent appropriately. The latter is obviously better, but it's non-trivial to collect this information.
Reimplemented from Jetscape::JetScapeTask.
Definition at line 81 of file HadronizationManager.cc.
View newest version in sPHENIX GitHub at line 81 of file HadronizationManager.cc
References VERBOSE.
Member Data Documentation
sigslot::signal1<vector<vector<shared_ptr<Parton> > >& > Jetscape::HadronizationManager::GetFinalPartonList
Definition at line 46 of file HadronizationManager.h.
View newest version in sPHENIX GitHub at line 46 of file HadronizationManager.h
bool Jetscape::HadronizationManager::GetFinalPartonListConnected private
Definition at line 56 of file HadronizationManager.h.
View newest version in sPHENIX GitHub at line 56 of file HadronizationManager.h
Referenced by GetGetFinalPartonListConnected(), and SetGetFinalPartonListConnected().
sigslot::signal1<vector<shared_ptr<Hadron> >& > Jetscape::HadronizationManager::GetHadronList
Definition at line 44 of file HadronizationManager.h.
View newest version in sPHENIX GitHub at line 44 of file HadronizationManager.h
bool Jetscape::HadronizationManager::GetHadronListConnected private
Definition at line 57 of file HadronizationManager.h.
View newest version in sPHENIX GitHub at line 57 of file HadronizationManager.h
Referenced by GetGetHadronListConnected(), and SetGetHadronListConnected().
vector<shared_ptr<Hadron> > Jetscape::HadronizationManager::hadrons private
Definition at line 59 of file HadronizationManager.h.
View newest version in sPHENIX GitHub at line 59 of file HadronizationManager.h
vector<vector<shared_ptr<Parton> > > Jetscape::HadronizationManager::hd private
Definition at line 58 of file HadronizationManager.h.
View newest version in sPHENIX GitHub at line 58 of file HadronizationManager.h
The documentation for this class was generated from the following files:
JETSCAPE/blob/master/src/framework/HadronizationManager.h
JETSCAPE/blob/master/src/framework/HadronizationManager.cc