Analysis Software: OnlMon/blob/main/onlmonserver/pmonitorInterface.cc File Reference
pmonitorInterface.cc File Reference
#include "pmonitorInterface.h"
#include "HistoBinDefs.h"
#include "OnlMon.h"
#include "OnlMonDefs.h"
#include "OnlMonServer.h"
#include <Event/Event.h>
#include <pmonitor.h>
#include <Event/EventTypes.h>
#include <Event/msg_control.h>
#include <Event/msg_profile.h>
#include <Event/packet.h>
#include <MessageTypes.h>
#include <TClass.h>
#include <TH1.h>
#include <TInetAddress.h>
#include <TMessage.h>
#include <TROOT.h>
#include <TServerSocket.h>
#include <TSocket.h>
#include <TSystem.h>
#include <TThread.h>
#include <pthread.h>
#include <sys/types.h>
#include <unistd.h>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <iostream>
#include <sstream>
#include <string>
Macros
#define SERVER
Functions
static void * server (void *)
int pinit ()
int process_event (Event *evt)
int setup_server ()
void handletest (void *)
void handleconnection (void *arg)
int send_message (const int severity, const std::string &msg)
Variables
int ServerThread = 0
TH1 * FrameWorkVars = nullptr
Macro Definition Documentation
#define SERVER
Definition at line 46 of file pmonitorInterface.cc.
View newest version in sPHENIX GitHub at line 46 of file pmonitorInterface.cc
Function Documentation
void handleconnection (void * arg)
Definition at line 333 of file pmonitorInterface.cc.
View newest version in sPHENIX GitHub at line 333 of file pmonitorInterface.cc
References OnlMonServer::getHisto(), add_histos::histos, i, OnlMonServer::instance(), OnlMonServer::monibegin(), OnlMonServer::moniend(), OnlMonServer::monitor_vec_begin(), OnlMonServer::monitor_vec_end(), TauVsDIS_MachineLearning_Differentiation::msg, MSG_SEV_ERROR, OnlMonDefs::MSGLEN, OnlMonServer::nHistos(), printf(), send_message(), str, OnlMonBase::Verbosity(), and OnlMonServer::WriteHistoFile().
Referenced by server().
void handletest (void *)
Definition at line 327 of file pmonitorInterface.cc.
View newest version in sPHENIX GitHub at line 327 of file pmonitorInterface.cc
int pinit ()
Definition at line 67 of file pmonitorInterface.cc.
View newest version in sPHENIX GitHub at line 67 of file pmonitorInterface.cc
References FrameWorkVars, i, OnlMonServer::instance(), NFRAMEWORKBINS, OnlMonServer::registerCommonHisto(), server(), ServerThread, OnlMonServer::SetThreadId(), and ThreadId.
int process_event (Event * evt)
Definition at line 110 of file pmonitorInterface.cc.
View newest version in sPHENIX GitHub at line 110 of file pmonitorInterface.cc
References OnlMonServer::AddBadEvent(), OnlMonServer::BadEvents(), OnlMonServer::BeginRun(), OnlMonServer::BorTicks(), BORTIMEBIN, OnlMonServer::CurrentTicks(), CURRENTTIMEBIN, EARLYEVENTNUMBIN, EARLYEVENTTIMEBIN, OnlMonServer::EndRun(), EORTIMEBIN, OnlMonServer::EventNumber(), FrameWorkVars, Event::getErrorCode(), Event::getEvtLength(), Event::getEvtSequence(), Event::getRunNumber(), Event::getTime(), OnlMonServer::instance(), TauVsDIS_MachineLearning_Differentiation::msg, MSG_SEV_WARNING, OnlMonServer::process_event(), OnlMonServer::Reset(), OnlMonServer::RunNumber(), RUNNUMBERBIN, send_message(), and OnlMonServer::WriteHistoFile().
int send_message (const int severity, const std::string & msg)
Definition at line 552 of file pmonitorInterface.cc.
View newest version in sPHENIX GitHub at line 552 of file pmonitorInterface.cc
References MSG_SOURCE_DAQMON, and MSG_TYPE_MONITORING.
Referenced by handleconnection(), process_event(), and server().
static void * server (void *) static
Definition at line 239 of file pmonitorInterface.cc.
View newest version in sPHENIX GitHub at line 239 of file pmonitorInterface.cc
References handleconnection(), OnlMonServer::instance(), OnlMonDefs::MONIPORT, TauVsDIS_MachineLearning_Differentiation::msg, MSG_SEV_FATAL, OnlMonDefs::NUMMONIPORT, OnlMonServer::PortNumber(), printf(), send_message(), and OnlMonBase::Verbosity().
Referenced by pinit(), rcdaqEventiterator::read_next_buffer(), and rcdaqEventiterator::setup().
int setup_server ()
Definition at line 234 of file pmonitorInterface.cc.
View newest version in sPHENIX GitHub at line 234 of file pmonitorInterface.cc
Variable Documentation
TH1* FrameWorkVars = nullptr
Definition at line 63 of file pmonitorInterface.cc.
View newest version in sPHENIX GitHub at line 63 of file pmonitorInterface.cc
Referenced by pinit(), and process_event().
int ServerThread = 0
Definition at line 51 of file pmonitorInterface.cc.
View newest version in sPHENIX GitHub at line 51 of file pmonitorInterface.cc
Referenced by pinit().