Analysis Software: CylinderGeom_Mvtx Class Reference
CylinderGeom_Mvtx Class Reference
#include <coresoftware/blob/master/offline/packages/mvtx/CylinderGeom_Mvtx.h>
Public Member Functions
CylinderGeom_Mvtx (int layer, int in_Nstaves, double in_layer_nominal_radius, double in_phistep, double in_phitilt, double in_phi0)
CylinderGeom_Mvtx ()
default ctor to allow ROOT stream of this class. Implemented using c++11 feature of delegating constructors
~CylinderGeom_Mvtx () override
void identify (std::ostream &os=std::cout) const override
void set_layer (const int i) override
int get_layer () const override
double get_radius () const override
double get_pixel_x () const override
double get_pixel_z () const override
double get_pixel_thickness () const override
TVector3 get_local_from_world_coords (Surface surface, ActsGeometry *tGeometry, TVector3 world)
TVector3 get_world_from_local_coords (Surface surface, ActsGeometry *tGeometry, TVector2 local)
TVector3 get_world_from_local_coords (Surface surface, ActsGeometry *tGeometry, TVector3 local)
void get_sensor_indices_from_world_coords (std::vector< double > &world, unsigned int &stave, unsigned int &chip)
bool get_pixel_from_local_coords (TVector3 sensor_local, int &iRow, int &iCol)
int get_pixel_from_local_coords (TVector3 sensor_local)
TVector3 get_local_coords_from_pixel (int NXZ)
TVector3 get_local_coords_from_pixel (int iRow, int iCol)
int get_pixel_X_from_pixel_number (int NXZ)
int get_pixel_Z_from_pixel_number (int NXZ)
int get_pixel_number_from_xbin_zbin (int xbin, int zbin)
double get_stave_phi_tilt () const
double get_stave_phi_0 () const
int get_ladder_phi_index (int stave, int, int)
int get_ladder_z_index (int, int chip)
void find_sensor_center (Surface surface, ActsGeometry *tGeometry, double location[])
int get_N_staves () const
int get_N_half_staves () const
int get_NZ () const
int get_NX () const
Public Member Functions inherited from PHG4CylinderGeom
~PHG4CylinderGeom () override
void identify (std::ostream &os=std::cout) const override
virtual double get_thickness () const
virtual double get_zmin () const
virtual double get_zmax () const
virtual int get_nscint () const
virtual double get_tiltangle () const
virtual double get_phi_slat_zero () const
virtual void set_radius (const double)
virtual void set_thickness (const double)
virtual void set_zmin (const double)
virtual void set_zmax (const double)
virtual void set_nscint (const int)
virtual void set_tiltangle (const double)
virtual void set_phi_slat_zero (const double)
virtual void find_segment_center (const int, const int, double[])
virtual void find_strip_center (const int, const int, const int, const int, double[])
virtual void find_strip_index_values (const int, const double, const double, int &, int &)
virtual void find_strip_center_local_coords (const int, const int, const int, double[])
virtual double get_strip_y_spacing () const
virtual double get_strip_z_spacing () const
virtual double get_strip_tilt () const
virtual int get_N_strip_columns () const
virtual int get_N_strips_per_column () const
virtual int get_N_sensors_in_layer () const
virtual void ImportParameters (const PHParameters &)
load parameters from PHParameters, which interface to Database/XML/ROOT files
Public Member Functions inherited from PHObject
PHObject ()
ctor
~PHObject () override
dtor
virtual PHObject * CloneMe () const
Virtual copy constructor.
virtual PHObject * clone () const final
PHObject * Clone (const char *newname="") const final
void Copy (TObject &object) const final
virtual void Reset ()
Clear Event.
virtual int isValid () const
isValid returns non zero if object contains vailid data
virtual int Integrate () const
virtual int Integrate (PHObject *)
virtual void CopyFrom (const PHObject *obj)
Protected Attributes
int layer
int N_staves
int N_half_staves
double layer_radius
double stave_phi_step
double stave_phi_tilt
double stave_phi_0
double loc_sensor_in_chip [3]
double inner_loc_chip_in_module [9][3]
double inner_loc_module_in_halfstave [3]
double inner_loc_halfstave_in_stave [3]
double pixel_x
double pixel_z
double pixel_thickness
Additional Inherited Members
Protected Member Functions inherited from PHG4CylinderGeom
PHG4CylinderGeom ()
Detailed Description
Definition at line 13 of file CylinderGeom_Mvtx.h.
View newest version in sPHENIX GitHub at line 13 of file CylinderGeom_Mvtx.h
Constructor & Destructor Documentation
CylinderGeom_Mvtx::CylinderGeom_Mvtx (int layer, int in_Nstaves, double in_layer_nominal_radius, double in_phistep, double in_phitilt, double in_phi0)
Definition at line 16 of file CylinderGeom_Mvtx.cc.
View newest version in sPHENIX GitHub at line 16 of file CylinderGeom_Mvtx.cc
References i, inner_loc_chip_in_module, inner_loc_halfstave_in_stave, inner_loc_module_in_halfstave, j, and loc_sensor_in_chip.
CylinderGeom_Mvtx::CylinderGeom_Mvtx () inline
default ctor to allow ROOT stream of this class. Implemented using c++11 feature of delegating constructors
Definition at line 26 of file CylinderGeom_Mvtx.h.
View newest version in sPHENIX GitHub at line 26 of file CylinderGeom_Mvtx.h
CylinderGeom_Mvtx::~CylinderGeom_Mvtx () inline override
Definition at line 37 of file CylinderGeom_Mvtx.h.
View newest version in sPHENIX GitHub at line 37 of file CylinderGeom_Mvtx.h
Member Function Documentation
void CylinderGeom_Mvtx::find_sensor_center (Surface surface, ActsGeometry * tGeometry, double location[])
Definition at line 225 of file CylinderGeom_Mvtx.cc.
View newest version in sPHENIX GitHub at line 225 of file CylinderGeom_Mvtx.cc
References get_world_from_local_coords().
Referenced by SVReco::MakeGenFitTrack().
int CylinderGeom_Mvtx::get_ladder_phi_index (int stave, int , int) inline
Definition at line 73 of file CylinderGeom_Mvtx.h.
View newest version in sPHENIX GitHub at line 73 of file CylinderGeom_Mvtx.h
int CylinderGeom_Mvtx::get_ladder_z_index (int , int chip) inline
Definition at line 74 of file CylinderGeom_Mvtx.h.
View newest version in sPHENIX GitHub at line 74 of file CylinderGeom_Mvtx.h
int CylinderGeom_Mvtx::get_layer () const inline override virtual
Reimplemented from PHG4CylinderGeom.
Definition at line 44 of file CylinderGeom_Mvtx.h.
View newest version in sPHENIX GitHub at line 44 of file CylinderGeom_Mvtx.h
References layer.
TVector3 CylinderGeom_Mvtx::get_local_coords_from_pixel (int NXZ)
Definition at line 190 of file CylinderGeom_Mvtx.cc.
View newest version in sPHENIX GitHub at line 190 of file CylinderGeom_Mvtx.cc
References get_NX().
Referenced by TrackResiduals::fillHitTree().
TVector3 CylinderGeom_Mvtx::get_local_coords_from_pixel (int iRow, int iCol)
Definition at line 198 of file CylinderGeom_Mvtx.cc.
View newest version in sPHENIX GitHub at line 198 of file CylinderGeom_Mvtx.cc
References check_fpe_masks::check(), SegmentationAlpide::detectorToLocal(), loc_sensor_in_chip, and PHWHERE.
TVector3 CylinderGeom_Mvtx::get_local_from_world_coords (Surface surface, ActsGeometry * tGeometry, TVector3 world)
The Acts transform swaps a few of the coordinates
Definition at line 76 of file CylinderGeom_Mvtx.cc.
View newest version in sPHENIX GitHub at line 76 of file CylinderGeom_Mvtx.cc
References Acts::UnitConstants::cm, ActsGeometry::geometry(), and ActsTrackingGeometry::getGeoContext().
Referenced by PHTruthClustering::G4ClusterSize(), and SvtxTruthEval::G4ClusterSize().
int CylinderGeom_Mvtx::get_N_half_staves () const inline
Definition at line 79 of file CylinderGeom_Mvtx.h.
View newest version in sPHENIX GitHub at line 79 of file CylinderGeom_Mvtx.h
References N_half_staves.
int CylinderGeom_Mvtx::get_N_staves () const inline
Definition at line 78 of file CylinderGeom_Mvtx.h.
View newest version in sPHENIX GitHub at line 78 of file CylinderGeom_Mvtx.h
References N_staves.
int CylinderGeom_Mvtx::get_NX () const
Definition at line 244 of file CylinderGeom_Mvtx.cc.
View newest version in sPHENIX GitHub at line 244 of file CylinderGeom_Mvtx.cc
References SegmentationAlpide::NRows.
Referenced by get_local_coords_from_pixel(), get_pixel_from_local_coords(), get_pixel_number_from_xbin_zbin(), get_pixel_X_from_pixel_number(), and get_pixel_Z_from_pixel_number().
int CylinderGeom_Mvtx::get_NZ () const
Definition at line 239 of file CylinderGeom_Mvtx.cc.
View newest version in sPHENIX GitHub at line 239 of file CylinderGeom_Mvtx.cc
References SegmentationAlpide::NCols.
Referenced by get_pixel_from_local_coords().
bool CylinderGeom_Mvtx::get_pixel_from_local_coords (TVector3 sensor_local, int & iRow, int & iCol)
Definition at line 148 of file CylinderGeom_Mvtx.cc.
View newest version in sPHENIX GitHub at line 148 of file CylinderGeom_Mvtx.cc
References SegmentationAlpide::ActiveMatrixSizeCols, SegmentationAlpide::ActiveMatrixSizeRows, Acts::UnitConstants::e, f, loc_sensor_in_chip, and SegmentationAlpide::localToDetector().
Referenced by PHTruthClustering::G4ClusterSize(), SvtxTruthEval::G4ClusterSize(), and get_pixel_from_local_coords().
int CylinderGeom_Mvtx::get_pixel_from_local_coords (TVector3 sensor_local)
Definition at line 171 of file CylinderGeom_Mvtx.cc.
View newest version in sPHENIX GitHub at line 171 of file CylinderGeom_Mvtx.cc
References get_NX(), get_NZ(), get_pixel_from_local_coords(), and PHWHERE.
int CylinderGeom_Mvtx::get_pixel_number_from_xbin_zbin (int xbin, int zbin)
Definition at line 259 of file CylinderGeom_Mvtx.cc.
View newest version in sPHENIX GitHub at line 259 of file CylinderGeom_Mvtx.cc
References get_NX().
double CylinderGeom_Mvtx::get_pixel_thickness () const inline override virtual
Reimplemented from PHG4CylinderGeom.
Definition at line 49 of file CylinderGeom_Mvtx.h.
View newest version in sPHENIX GitHub at line 49 of file CylinderGeom_Mvtx.h
References pixel_thickness.
double CylinderGeom_Mvtx::get_pixel_x () const inline override virtual
Reimplemented from PHG4CylinderGeom.
Definition at line 47 of file CylinderGeom_Mvtx.h.
View newest version in sPHENIX GitHub at line 47 of file CylinderGeom_Mvtx.h
References pixel_x.
Referenced by PHTruthClustering::G4ClusterSize(), SvtxTruthEval::G4ClusterSize(), and G4Eval::TrkrClusterComparer::init().
int CylinderGeom_Mvtx::get_pixel_X_from_pixel_number (int NXZ)
Definition at line 249 of file CylinderGeom_Mvtx.cc.
View newest version in sPHENIX GitHub at line 249 of file CylinderGeom_Mvtx.cc
References get_NX().
double CylinderGeom_Mvtx::get_pixel_z () const inline override virtual
Reimplemented from PHG4CylinderGeom.
Definition at line 48 of file CylinderGeom_Mvtx.h.
View newest version in sPHENIX GitHub at line 48 of file CylinderGeom_Mvtx.h
References pixel_z.
Referenced by PHTruthClustering::G4ClusterSize(), and SvtxTruthEval::G4ClusterSize().
int CylinderGeom_Mvtx::get_pixel_Z_from_pixel_number (int NXZ)
Definition at line 254 of file CylinderGeom_Mvtx.cc.
View newest version in sPHENIX GitHub at line 254 of file CylinderGeom_Mvtx.cc
References get_NX().
double CylinderGeom_Mvtx::get_radius () const inline override virtual
Reimplemented from PHG4CylinderGeom.
Definition at line 45 of file CylinderGeom_Mvtx.h.
View newest version in sPHENIX GitHub at line 45 of file CylinderGeom_Mvtx.h
References layer_radius.
void CylinderGeom_Mvtx::get_sensor_indices_from_world_coords (std::vector< double > & world, unsigned int & stave, unsigned int & chip)
Definition at line 95 of file CylinderGeom_Mvtx.cc.
View newest version in sPHENIX GitHub at line 95 of file CylinderGeom_Mvtx.cc
References inner_loc_chip_in_module, ActsTests::PropagationDatasets::phi, round(), stave_phi_0, and stave_phi_step.
Referenced by PHTruthClustering::G4ClusterSize(), SvtxTruthEval::G4ClusterSize(), and MakeActsGeometry::getMvtxHitSetKeyFromCoords().
double CylinderGeom_Mvtx::get_stave_phi_0 () const inline
Definition at line 71 of file CylinderGeom_Mvtx.h.
View newest version in sPHENIX GitHub at line 71 of file CylinderGeom_Mvtx.h
References stave_phi_0.
double CylinderGeom_Mvtx::get_stave_phi_tilt () const inline
Definition at line 70 of file CylinderGeom_Mvtx.h.
View newest version in sPHENIX GitHub at line 70 of file CylinderGeom_Mvtx.h
References stave_phi_tilt.
Referenced by SVReco::MakeGenFitTrack().
TVector3 CylinderGeom_Mvtx::get_world_from_local_coords (Surface surface, ActsGeometry * tGeometry, TVector2 local)
Acts requires a dummy vector to be passed in the arg list
Definition at line 115 of file CylinderGeom_Mvtx.cc.
View newest version in sPHENIX GitHub at line 115 of file CylinderGeom_Mvtx.cc
References Acts::UnitConstants::cm, ActsGeometry::geometry(), and ActsTrackingGeometry::getGeoContext().
Referenced by find_sensor_center().
TVector3 CylinderGeom_Mvtx::get_world_from_local_coords (Surface surface, ActsGeometry * tGeometry, TVector3 local)
Definition at line 137 of file CylinderGeom_Mvtx.cc.
View newest version in sPHENIX GitHub at line 137 of file CylinderGeom_Mvtx.cc
References Acts::UnitConstants::cm, ActsGeometry::geometry(), ActsTrackingGeometry::getGeoContext(), and loc.
void CylinderGeom_Mvtx::identify (std::ostream & os = std::cout) const override virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from PHObject.
Definition at line 212 of file CylinderGeom_Mvtx.cc.
View newest version in sPHENIX GitHub at line 212 of file CylinderGeom_Mvtx.cc
References layer, layer_radius, N_half_staves, N_staves, pixel_thickness, pixel_x, and pixel_z.
void CylinderGeom_Mvtx::set_layer (const int i) inline override virtual
Reimplemented from PHG4CylinderGeom.
Definition at line 43 of file CylinderGeom_Mvtx.h.
View newest version in sPHENIX GitHub at line 43 of file CylinderGeom_Mvtx.h
References i.
Member Data Documentation
double CylinderGeom_Mvtx::inner_loc_chip_in_module[9][3] protected
Definition at line 99 of file CylinderGeom_Mvtx.h.
View newest version in sPHENIX GitHub at line 99 of file CylinderGeom_Mvtx.h
Referenced by CylinderGeom_Mvtx(), and get_sensor_indices_from_world_coords().
double CylinderGeom_Mvtx::inner_loc_halfstave_in_stave[3] protected
Definition at line 101 of file CylinderGeom_Mvtx.h.
View newest version in sPHENIX GitHub at line 101 of file CylinderGeom_Mvtx.h
Referenced by CylinderGeom_Mvtx().
double CylinderGeom_Mvtx::inner_loc_module_in_halfstave[3] protected
Definition at line 100 of file CylinderGeom_Mvtx.h.
View newest version in sPHENIX GitHub at line 100 of file CylinderGeom_Mvtx.h
Referenced by CylinderGeom_Mvtx().
int CylinderGeom_Mvtx::layer protected
Definition at line 85 of file CylinderGeom_Mvtx.h.
View newest version in sPHENIX GitHub at line 85 of file CylinderGeom_Mvtx.h
Referenced by get_layer(), and identify().
double CylinderGeom_Mvtx::layer_radius protected
Definition at line 90 of file CylinderGeom_Mvtx.h.
View newest version in sPHENIX GitHub at line 90 of file CylinderGeom_Mvtx.h
Referenced by get_radius(), and identify().
double CylinderGeom_Mvtx::loc_sensor_in_chip[3] protected
Definition at line 96 of file CylinderGeom_Mvtx.h.
View newest version in sPHENIX GitHub at line 96 of file CylinderGeom_Mvtx.h
Referenced by CylinderGeom_Mvtx(), get_local_coords_from_pixel(), and get_pixel_from_local_coords().
int CylinderGeom_Mvtx::N_half_staves protected
Definition at line 87 of file CylinderGeom_Mvtx.h.
View newest version in sPHENIX GitHub at line 87 of file CylinderGeom_Mvtx.h
Referenced by get_N_half_staves(), and identify().
int CylinderGeom_Mvtx::N_staves protected
Definition at line 86 of file CylinderGeom_Mvtx.h.
View newest version in sPHENIX GitHub at line 86 of file CylinderGeom_Mvtx.h
Referenced by get_N_staves(), and identify().
double CylinderGeom_Mvtx::pixel_thickness protected
Definition at line 105 of file CylinderGeom_Mvtx.h.
View newest version in sPHENIX GitHub at line 105 of file CylinderGeom_Mvtx.h
Referenced by get_pixel_thickness(), and identify().
double CylinderGeom_Mvtx::pixel_x protected
Definition at line 103 of file CylinderGeom_Mvtx.h.
View newest version in sPHENIX GitHub at line 103 of file CylinderGeom_Mvtx.h
Referenced by get_pixel_x(), and identify().
double CylinderGeom_Mvtx::pixel_z protected
Definition at line 104 of file CylinderGeom_Mvtx.h.
View newest version in sPHENIX GitHub at line 104 of file CylinderGeom_Mvtx.h
Referenced by get_pixel_z(), and identify().
double CylinderGeom_Mvtx::stave_phi_0 protected
Definition at line 93 of file CylinderGeom_Mvtx.h.
View newest version in sPHENIX GitHub at line 93 of file CylinderGeom_Mvtx.h
Referenced by get_sensor_indices_from_world_coords(), and get_stave_phi_0().
double CylinderGeom_Mvtx::stave_phi_step protected
Definition at line 91 of file CylinderGeom_Mvtx.h.
View newest version in sPHENIX GitHub at line 91 of file CylinderGeom_Mvtx.h
Referenced by get_sensor_indices_from_world_coords().
double CylinderGeom_Mvtx::stave_phi_tilt protected
Definition at line 92 of file CylinderGeom_Mvtx.h.
View newest version in sPHENIX GitHub at line 92 of file CylinderGeom_Mvtx.h
Referenced by get_stave_phi_tilt().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/mvtx/CylinderGeom_Mvtx.h
coresoftware/blob/master/offline/packages/mvtx/CylinderGeom_Mvtx.cc