Analysis Software: Acts::detail_vmt::VectorMultiTrajectoryBase::Statistics Struct Reference
Acts::detail_vmt::VectorMultiTrajectoryBase::Statistics Struct Reference
#include <acts/blob/sPHENIX/Core/include/Acts/EventData/VectorMultiTrajectory.hpp>
Public Types
using axis_t = boost::histogram::axis::variant< boost::histogram::axis::category< std::string >, boost::histogram::axis::category<>>
using axes_t = std::vector< axis_t >
using hist_t = boost::histogram::histogram< axes_t >
Public Member Functions
void toStream (std::ostream &os, size_t n=1)
Public Attributes
hist_t hist
Detailed Description
Definition at line 50 of file VectorMultiTrajectory.hpp.
View newest version in sPHENIX GitHub at line 50 of file VectorMultiTrajectory.hpp
Member Typedef Documentation
using Acts::detail_vmt::VectorMultiTrajectoryBase::Statistics::axes_t = std::vector<axis_t>
Definition at line 55 of file VectorMultiTrajectory.hpp.
View newest version in sPHENIX GitHub at line 55 of file VectorMultiTrajectory.hpp
using Acts::detail_vmt::VectorMultiTrajectoryBase::Statistics::axis_t = boost::histogram::axis::variant< boost::histogram::axis::category<std::string>, boost::histogram::axis::category<>>
Definition at line 53 of file VectorMultiTrajectory.hpp.
View newest version in sPHENIX GitHub at line 53 of file VectorMultiTrajectory.hpp
using Acts::detail_vmt::VectorMultiTrajectoryBase::Statistics::hist_t = boost::histogram::histogram<axes_t>
Definition at line 56 of file VectorMultiTrajectory.hpp.
View newest version in sPHENIX GitHub at line 56 of file VectorMultiTrajectory.hpp
Member Function Documentation
void Acts::detail_vmt::VectorMultiTrajectoryBase::Statistics::toStream (std::ostream & os, size_t n = 1)
Definition at line 189 of file VectorMultiTrajectory.cpp.
View newest version in sPHENIX GitHub at line 189 of file VectorMultiTrajectory.cpp
References Acts::PhysicalConstants::c, double(), h, hist, histogram(), merge_hashes::p, t, and testSigmaEff::v.
Referenced by BOOST_AUTO_TEST_CASE().
Member Data Documentation
hist_t Acts::detail_vmt::VectorMultiTrajectoryBase::Statistics::hist
Definition at line 58 of file VectorMultiTrajectory.hpp.
View newest version in sPHENIX GitHub at line 58 of file VectorMultiTrajectory.hpp
Referenced by ActsExamples::TrackFindingAlgorithm::finalize(), and toStream().
The documentation for this struct was generated from the following files:
acts/blob/sPHENIX/Core/include/Acts/EventData/VectorMultiTrajectory.hpp
acts/blob/sPHENIX/Core/src/EventData/VectorMultiTrajectory.cpp