Analysis Software: Acts::TrapezoidBounds Class Reference
Acts::TrapezoidBounds Class Reference
#include <acts/blob/sPHENIX/Core/include/Acts/Surfaces/TrapezoidBounds.hpp>
Public Types
enum BoundValues { eHalfLengthXnegY = 0, eHalfLengthXposY = 1, eHalfLengthY = 2, eSize = 3 }
Public Member Functions
TrapezoidBounds ()=delete
TrapezoidBounds (double halfXnegY, double halfXposY, double halfY) noexcept(false)
m_boundingBox (std::max(halfXnegY, halfXposY), halfY)
TrapezoidBounds (const std::array< double, eSize > &values) noexcept(false)
~TrapezoidBounds () override
BoundsType type () const final
std::vector< double > values () const final
bool inside (const Vector2 &lposition, const BoundaryCheck &bcheck) const final
std::vector< Vector2 > vertices (unsigned int lseg=1) const final
const RectangleBounds & boundingBox () const final
std::ostream & toStream (std::ostream &sl) const final
double get (BoundValues bValue) const
Private Member Functions
void checkConsistency () noexcept(false)
Private Attributes
std::array< double, eSize > m_values
RectangleBounds m_boundingBox
Detailed Description
Bounds for a trapezoidal, planar Surface.
Definition at line 34 of file TrapezoidBounds.hpp.
View newest version in sPHENIX GitHub at line 34 of file TrapezoidBounds.hpp
Member Enumeration Documentation
enum Acts::TrapezoidBounds::BoundValues
Enumerator:
eHalfLengthXnegY
eHalfLengthXposY
eHalfLengthY
eSize
Definition at line 36 of file TrapezoidBounds.hpp.
View newest version in sPHENIX GitHub at line 36 of file TrapezoidBounds.hpp
Constructor & Destructor Documentation
Acts::TrapezoidBounds::TrapezoidBounds () delete
Acts::TrapezoidBounds::TrapezoidBounds (double halfXnegY, double halfXposY, double halfY) inline noexcept
Constructor for symmetric Trapezoid
Parameters
halfXnegY minimal half length X, definition at negative Y
halfXposY maximal half length X, definition at positive Y
halfY half length Y - defined at x=0
Definition at line 50 of file TrapezoidBounds.hpp.
View newest version in sPHENIX GitHub at line 50 of file TrapezoidBounds.hpp
References Acts::Test::halfY.
Acts::TrapezoidBounds::TrapezoidBounds (const std::array< double, eSize > & values) inline noexcept
Constructor for symmetric Trapezoid - from fixed size array
Parameters
values the values to be stream in
Definition at line 60 of file TrapezoidBounds.hpp.
View newest version in sPHENIX GitHub at line 60 of file TrapezoidBounds.hpp
References checkConsistency().
Acts::TrapezoidBounds::~TrapezoidBounds () override default
Member Function Documentation
const Acts::RectangleBounds & Acts::TrapezoidBounds::boundingBox () const final virtual
Bounding box parameters
Returns
rectangle bounds for a bounding box
Implements Acts::PlanarBounds.
Definition at line 66 of file TrapezoidBounds.cpp.
View newest version in sPHENIX GitHub at line 66 of file TrapezoidBounds.cpp
Referenced by Acts::Test::BOOST_AUTO_TEST_CASE().
void Acts::TrapezoidBounds::checkConsistency () inline private noexcept
Check the input values for consistency, will throw a logic_exception if consistency is not given
Definition at line 155 of file TrapezoidBounds.hpp.
View newest version in sPHENIX GitHub at line 155 of file TrapezoidBounds.hpp
References eHalfLengthXnegY, eHalfLengthXposY, and eHalfLengthY.
Referenced by m_boundingBox(), and TrapezoidBounds().
double Acts::TrapezoidBounds::get (BoundValues bValue) const inline
Access to the bound values
Parameters
bValue the class nested enum for the array access
Definition at line 138 of file TrapezoidBounds.hpp.
View newest version in sPHENIX GitHub at line 138 of file TrapezoidBounds.hpp
References m_values.
Referenced by Acts::adjustBinUtility(), Acts::MappingMaterialDecorator::binnedSurfaceMaterial(), and Acts::Test::BOOST_AUTO_TEST_CASE().
bool Acts::TrapezoidBounds::inside (const Vector2 & lposition, const BoundaryCheck & bcheck) const final virtual
The orientation of the Trapezoid is according to the figure above, in words: the shorter of the two parallel sides of the trapezoid intersects with the negative - axis of the local frame.
The cases are:
(0) or bounds are 0 || 0
(1) the local position is outside bounds
(2) the local position is inside bounds, but outside maximum bounds
(3) the local position is inside bounds AND inside minimum bounds
(4) the local position is inside bounds AND inside maximum bounds, so that it depends on the coordinate (5) the local position fails test of (4)
The inside check is done using single equations of straight lines and one has to take care if a point lies on the positive half area(I) or the negative one(II). Denoting and as minHalfX respectively maxHalfX, such as as halfY, the equations for the straing lines in (I) and (II) can be written as:
(I):
(II): ,
where
and
Parameters
lposition Local position (assumed to be in right surface frame)
bcheck boundary check directive
Returns
boolean indicator for the success of this operation
Implements Acts::SurfaceBounds.
Definition at line 22 of file TrapezoidBounds.cpp.
View newest version in sPHENIX GitHub at line 22 of file TrapezoidBounds.cpp
References Acts::eBoundLoc0, Acts::eBoundLoc1, eHalfLengthXnegY, eHalfLengthXposY, eHalfLengthY, Acts::BoundaryCheck::isInside(), Acts::UnitConstants::min, Acts::BoundaryCheck::tolerance(), Acts::BoundaryCheck::type(), testSigmaEff::v, ambiguity_solver_full_chain::x, and y.
Referenced by Acts::Test::BOOST_AUTO_TEST_CASE().
Acts::TrapezoidBounds::m_boundingBox (std:: maxhalfXnegY, halfXposY, halfY) inline
Definition at line 53 of file TrapezoidBounds.hpp.
View newest version in sPHENIX GitHub at line 53 of file TrapezoidBounds.hpp
References checkConsistency().
std::ostream & Acts::TrapezoidBounds::toStream (std::ostream & sl) const final virtual
Output Method for std::ostream
Parameters
sl is the ostream to be dumped into
Implements Acts::SurfaceBounds.
Definition at line 70 of file TrapezoidBounds.cpp.
View newest version in sPHENIX GitHub at line 70 of file TrapezoidBounds.cpp
Referenced by Acts::Test::BOOST_AUTO_TEST_CASE().
Acts::SurfaceBounds::BoundsType Acts::TrapezoidBounds::type () const final virtual
Return the bounds type - for persistency optimization
Returns
is a BoundsType enum
Implements Acts::SurfaceBounds.
Definition at line 18 of file TrapezoidBounds.cpp.
View newest version in sPHENIX GitHub at line 18 of file TrapezoidBounds.cpp
References Acts::SurfaceBounds::eTrapezoid.
Referenced by Acts::Test::BOOST_AUTO_TEST_CASE().
std::vector< double > Acts::TrapezoidBounds::values () const inline final virtual
Access method for bound values, this is a dynamically sized vector containing the parameters needed to describe these bounds
Returns
of the stored values for this SurfaceBounds object
Implements Acts::SurfaceBounds.
Definition at line 149 of file TrapezoidBounds.hpp.
View newest version in sPHENIX GitHub at line 149 of file TrapezoidBounds.hpp
References m_values.
Referenced by Acts::Test::BOOST_AUTO_TEST_CASE().
std::vector< Acts::Vector2 > Acts::TrapezoidBounds::vertices (unsigned int lseg = 1) const final virtual
Return the vertices
Parameters
lseg the number of segments used to approximate and eventually curved line
Note
the number of segments is ignored in this representation
Returns
vector for vertices in 2D
Implements Acts::PlanarBounds.
Definition at line 58 of file TrapezoidBounds.cpp.
View newest version in sPHENIX GitHub at line 58 of file TrapezoidBounds.cpp
References eHalfLengthXnegY, eHalfLengthXposY, eHalfLengthY, and Acts::Test::hy.
Referenced by Acts::Test::BOOST_AUTO_TEST_CASE().
Member Data Documentation
RectangleBounds Acts::TrapezoidBounds::m_boundingBox private
Definition at line 142 of file TrapezoidBounds.hpp.
View newest version in sPHENIX GitHub at line 142 of file TrapezoidBounds.hpp
std::array<double, eSize> Acts::TrapezoidBounds::m_values private
Definition at line 141 of file TrapezoidBounds.hpp.
View newest version in sPHENIX GitHub at line 141 of file TrapezoidBounds.hpp
Referenced by get(), and values().
The documentation for this class was generated from the following files:
acts/blob/sPHENIX/Core/include/Acts/Surfaces/TrapezoidBounds.hpp
acts/blob/sPHENIX/Core/src/Surfaces/TrapezoidBounds.cpp