Analysis Software: TpcMap Class Reference
TpcMap Class Reference
#include <coresoftware/blob/master/offline/packages/tpc/TpcMap.h>
Classes
struct tpc_map
Public Member Functions
TpcMap ()=default
virtual ~TpcMap ()=default
virtual unsigned int getLayer (const unsigned int FEE, const unsigned int FEEChannel, const unsigned int packetid=0) const
virtual unsigned int getPad (const unsigned int FEE, const unsigned int FEEChannel, const unsigned int packetid=0) const
virtual double getR (const unsigned int FEE, const unsigned int FEEChannel, const unsigned int packetid=0) const
virtual double getPhi (const unsigned int FEE, const unsigned int FEEChannel, const unsigned int packetid=0) const
virtual void setMapNames (const std::string &r1, const std::string &r2, const std::string &r3)
Private Member Functions
int digest_map (const std::string &fileName, const unsigned int section_offset)
Private Attributes
int _broken = 0
std::map< unsigned int, struct
tpc_map > tmap
Detailed Description
Definition at line 7 of file TpcMap.h.
View newest version in sPHENIX GitHub at line 7 of file TpcMap.h
Constructor & Destructor Documentation
TpcMap::TpcMap () default
virtual TpcMap::~TpcMap () virtual default
Member Function Documentation
int TpcMap::digest_map (const std::string & fileName, const unsigned int section_offset) private
Definition at line 52 of file TpcMap.cc.
View newest version in sPHENIX GitHub at line 52 of file TpcMap.cc
References _broken, TpcMap::tpc_map::FEE, TpcMap::tpc_map::FEEChannel, in, index, infile, TpcMap::tpc_map::layer, line, next, TpcMap::tpc_map::padnr, TpcMap::tpc_map::PadPhi, TpcMap::tpc_map::PadR, tmap, and ambiguity_solver_full_chain::x.
Referenced by setMapNames().
unsigned int TpcMap::getLayer (const unsigned int FEE, const unsigned int FEEChannel, const unsigned int packetid = 0) const virtual
Definition at line 170 of file TpcMap.cc.
View newest version in sPHENIX GitHub at line 170 of file TpcMap.cc
References tmap.
Referenced by TpcMon::process_event(), TpcRawDataTree::process_event(), TPCRawDataTree::process_event(), TPCEventDisplay_Updated(), and TPCEventDisplay_Updated_BCO().
unsigned int TpcMap::getPad (const unsigned int FEE, const unsigned int FEEChannel, const unsigned int packetid = 0) const virtual
Definition at line 186 of file TpcMap.cc.
View newest version in sPHENIX GitHub at line 186 of file TpcMap.cc
References tmap.
Referenced by TpcMon::process_event(), TPCEventDisplay_Updated(), and TPCEventDisplay_Updated_BCO().
double TpcMap::getPhi (const unsigned int FEE, const unsigned int FEEChannel, const unsigned int packetid = 0) const virtual
Definition at line 218 of file TpcMap.cc.
View newest version in sPHENIX GitHub at line 218 of file TpcMap.cc
References tmap.
Referenced by TpcMon::process_event(), TpcRawDataTree::process_event(), TPCRawDataTree::process_event(), TPCEventDisplay_Updated(), and TPCEventDisplay_Updated_BCO().
double TpcMap::getR (const unsigned int FEE, const unsigned int FEEChannel, const unsigned int packetid = 0) const virtual
Definition at line 202 of file TpcMap.cc.
View newest version in sPHENIX GitHub at line 202 of file TpcMap.cc
References tmap.
Referenced by TpcMon::process_event(), TpcRawDataTree::process_event(), TPCRawDataTree::process_event(), TPCEventDisplay_Updated(), and TPCEventDisplay_Updated_BCO().
void TpcMap::setMapNames (const std::string & r1, const std::string & r2, const std::string & r3) virtual
Definition at line 10 of file TpcMap.cc.
View newest version in sPHENIX GitHub at line 10 of file TpcMap.cc
References digest_map(), r1, r2, r3, and utils::status.
Referenced by TPCEventDisplay_Updated(), TPCEventDisplay_Updated_BCO(), TpcMon::TpcMon(), TPCRawDataTree::TPCRawDataTree(), and TpcRawDataTree::TpcRawDataTree().
Member Data Documentation
int TpcMap::_broken = 0 private
Definition at line 23 of file TpcMap.h.
View newest version in sPHENIX GitHub at line 23 of file TpcMap.h
Referenced by digest_map().
std::map<unsigned int, struct tpc_map> TpcMap::tmap private
Definition at line 34 of file TpcMap.h.
View newest version in sPHENIX GitHub at line 34 of file TpcMap.h
Referenced by digest_map(), getLayer(), getPad(), getPhi(), and getR().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/tpc/TpcMap.h
coresoftware/blob/master/offline/packages/tpc/TpcMap.cc