Analysis Software: OnlMon/blob/main/onlmonserver/pmonitorInterface.h File Reference
pmonitorInterface.h File Reference
#include <string>
Functions
int setup_server ()
void handleconnection (void *arg)
void handletest (void *arg)
int send_message (const int severity, const std::string &msg)
Function Documentation
void handleconnection (void * arg)
Definition at line 333 of file pmonitorInterface.cc.
View newest version in sPHENIX GitHub at line 333 of file pmonitorInterface.cc
References OnlMonServer::getHisto(), add_histos::histos, i, OnlMonServer::instance(), OnlMonServer::monibegin(), OnlMonServer::moniend(), OnlMonServer::monitor_vec_begin(), OnlMonServer::monitor_vec_end(), TauVsDIS_MachineLearning_Differentiation::msg, MSG_SEV_ERROR, OnlMonDefs::MSGLEN, OnlMonServer::nHistos(), printf(), send_message(), str, OnlMonBase::Verbosity(), and OnlMonServer::WriteHistoFile().
Referenced by server().
void handletest (void * arg)
Definition at line 327 of file pmonitorInterface.cc.
View newest version in sPHENIX GitHub at line 327 of file pmonitorInterface.cc
int send_message (const int severity, const std::string & msg)
Definition at line 552 of file pmonitorInterface.cc.
View newest version in sPHENIX GitHub at line 552 of file pmonitorInterface.cc
References MSG_SOURCE_DAQMON, and MSG_TYPE_MONITORING.
Referenced by handleconnection(), process_event(), and server().
int setup_server ()
Definition at line 234 of file pmonitorInterface.cc.
View newest version in sPHENIX GitHub at line 234 of file pmonitorInterface.cc