Analysis Software: Acts::Svg::IndexedSurfacesConverter Namespace Reference
Acts::Svg::IndexedSurfacesConverter Namespace Reference
Classes
struct Options
Nested options struct.
Functions
template<typename surface_container , typename index_grid >
ProtoIndexedSurfaceGrid convertImpl (const GeometryContext &gctx, const surface_container &surfaces, const index_grid &indexGrid, const Options &cOptions)
template<typename surface_container , typename instance_type >
void convert (const GeometryContext &gctx, const surface_container &surfaces, const Options &cOptions, ProtoIndexedSurfaceGrid &sgi, const Experimental::SurfaceCandidatesUpdator &delegate,[[maybe_unused]] const instance_type &refInstance)
Convert the single delegate if it is of the type of the reference.
template<typename surface_container , typename tuple_type , std::size_t... I>
void unrollConvert (const GeometryContext &gctx, const surface_container &surfaces, const Options &cOptions, ProtoIndexedSurfaceGrid &sgi, const Experimental::SurfaceCandidatesUpdator &delegate, const tuple_type &axesTuple, std::index_sequence< I...>)
Unrolling function for catching the right instance.
template<typename surface_container >
ProtoIndexedSurfaceGrid convert (const GeometryContext &gctx, const surface_container &surfaces, const Experimental::SurfaceCandidatesUpdator &delegate, const Options &cOptions)
Function Documentation
template<typename surface_container , typename instance_type > void Acts::Svg::IndexedSurfacesConverter::convert (const GeometryContext & gctx, const surface_container & surfaces, const Options & cOptions, ProtoIndexedSurfaceGrid & sgi, const Experimental::SurfaceCandidatesUpdator & delegate, [[maybe_unused] ] const instance_type & refInstance)
Convert the single delegate if it is of the type of the reference.
Note
It will do nothing if the type does not match
Template Parameters
surface_container the surfaces to be drawn
instance_type the reference instance type
Parameters
gctx The Geometry context of this operation
surfaces The surfaces to be converted
cOptions the conversion options
sgi [in,out] the proto indexed grid to be converted
delegate the delegate to be translated
refInstance the reference input type from the reference Axes
Definition at line 192 of file IndexedSurfacesSvgConverter.hpp.
View newest version in sPHENIX GitHub at line 192 of file IndexedSurfacesSvgConverter.hpp
References convertImpl().
template<typename surface_container > ProtoIndexedSurfaceGrid Acts::Svg::IndexedSurfacesConverter::convert (const GeometryContext & gctx, const surface_container & surfaces, const Experimental::SurfaceCandidatesUpdator & delegate, const Options & cOptions)
Convert a surface array into needed constituents
Parameters
gtcx is the geometry context of the conversion call
surfaces the container of surfaces
indexGrid the indexGrid delegate
cOptions the conversion options
Note
this is the entry point of the conversion, i.e. top of the unrolling loop
Returns
a collection of proto surface object and a grid, and associations
Definition at line 242 of file IndexedSurfacesSvgConverter.hpp.
View newest version in sPHENIX GitHub at line 242 of file IndexedSurfacesSvgConverter.hpp
References Acts::Experimental::s_possibleAxes, unrollConvert(), and value.
template<typename surface_container , typename index_grid > ProtoIndexedSurfaceGrid Acts::Svg::IndexedSurfacesConverter::convertImpl (const GeometryContext & gctx, const surface_container & surfaces, const index_grid & indexGrid, const Options & cOptions)
Convert a surface array into needed constituents
Note
actual conversion implementation, bottom of unrolling loop
Parameters
gtcx is the geometry context of the conversion call
surfaces the container of surfaces
indexGrid the indexGrid delegate
cOptions the conversion options
Returns
a collection of proto surface object and a grid, and associations
Definition at line 87 of file IndexedSurfacesSvgConverter.hpp.
View newest version in sPHENIX GitHub at line 87 of file IndexedSurfacesSvgConverter.hpp
References Acts::binPhi, Acts::binR, Acts::Svg::DetectorConverter::convert(), Acts::GeometryHierarchyMap< value_t >::end(), Acts::enumerate(), Acts::Extent::extend(), Acts::GeometryHierarchyMap< value_t >::find(), Acts::Svg::IndexedSurfacesConverter::Options::gridOptions, Acts::Extent::medium(), Acts::Range1D< Type >::min(), Acts::Svg::GridConverter::Options::optionalBound, pSurface, Acts::Extent::range(), physmon_simulation::s, Acts::Svg::SurfaceConverter::Options::style, Acts::Svg::IndexedSurfacesConverter::Options::surfaceStyles, to_string(), and physmon_ckf_tracking::u.
Referenced by convert().
template<typename surface_container , typename tuple_type , std::size_t... I> void Acts::Svg::IndexedSurfacesConverter::unrollConvert (const GeometryContext & gctx, const surface_container & surfaces, const Options & cOptions, ProtoIndexedSurfaceGrid & sgi, const Experimental::SurfaceCandidatesUpdator & delegate, const tuple_type & axesTuple, std::index_sequence< I...>)
Unrolling function for catching the right instance.
Note
parameters are as of the convertImpl method
Definition at line 221 of file IndexedSurfacesSvgConverter.hpp.
View newest version in sPHENIX GitHub at line 221 of file IndexedSurfacesSvgConverter.hpp
References Acts::Svg::DetectorConverter::convert().
Referenced by convert(), and Acts::IndexedSurfacesJsonConverter::toJson().