Analysis Software: acts/blob/sPHENIX/Tests/UnitTests/Plugins/Geant4/Geant4ConvertersTests.cpp File Reference
Geant4ConvertersTests.cpp File Reference
#include <boost/test/unit_test.hpp>
#include "Acts/Definitions/Algebra.hpp"
#include "Acts/Geometry/GeometryContext.hpp"
#include "Acts/Material/ISurfaceMaterial.hpp"
#include "Acts/Material/Material.hpp"
#include "Acts/Material/MaterialSlab.hpp"
#include "Acts/Plugins/Geant4/Geant4Converters.hpp"
#include "Acts/Surfaces/CylinderBounds.hpp"
#include "Acts/Surfaces/LineBounds.hpp"
#include "Acts/Surfaces/RadialBounds.hpp"
#include "Acts/Surfaces/RectangleBounds.hpp"
#include "Acts/Surfaces/Surface.hpp"
#include "Acts/Surfaces/TrapezoidBounds.hpp"
#include "Acts/Tests/CommonHelpers/FloatComparisons.hpp"
#include <array>
#include <cmath>
#include <memory>
#include <stdexcept>
#include <tuple>
#include "G4Box.hh"
#include "G4LogicalVolume.hh"
#include "G4Material.hh"
#include "G4PVPlacement.hh"
#include "G4RotationMatrix.hh"
#include "G4SystemOfUnits.hh"
#include "G4ThreeVector.hh"
#include "G4Trd.hh"
#include "G4Tubs.hh"
#include "G4VPhysicalVolume.hh"
Functions
BOOST_AUTO_TEST_CASE (Geant4AlgebraConversion)
BOOST_AUTO_TEST_CASE (Geant4CylinderConversion)
BOOST_AUTO_TEST_CASE (Geant4RadialConversion)
BOOST_AUTO_TEST_CASE (Geant4LineConversion)
BOOST_AUTO_TEST_CASE (Geant4BoxConversion)
BOOST_AUTO_TEST_CASE (Geant4TrapzoidConversion)
BOOST_AUTO_TEST_CASE (Geant4PlanarConversion)
BOOST_AUTO_TEST_CASE (Geant4BoxVPhysConversion)
BOOST_AUTO_TEST_CASE (Geant4CylVPhysConversion)
BOOST_AUTO_TEST_CASE (Geant4VDiscVPhysConversion)
BOOST_AUTO_TEST_CASE (Geant4LineVPhysConversion)
Variables
Acts::GeometryContext tContext
Acts::ActsScalar rho = 1.2345
G4Material * g4Material = new G4Material("Material", 6., 12., rho)
Function Documentation
BOOST_AUTO_TEST_CASE (Geant4AlgebraConversion)
Definition at line 49 of file Geant4ConvertersTests.cpp.
View newest version in sPHENIX GitHub at line 49 of file Geant4ConvertersTests.cpp
References Acts::Geant4AlgebraConverter::transform().
BOOST_AUTO_TEST_CASE (Geant4CylinderConversion)
Definition at line 66 of file Geant4ConvertersTests.cpp.
View newest version in sPHENIX GitHub at line 66 of file Geant4ConvertersTests.cpp
References bounds, CHECK_CLOSE_ABS, Acts::Geant4ShapeConverter::cylinderBounds(), Acts::UnitConstants::e, eR, and thickness.
BOOST_AUTO_TEST_CASE (Geant4RadialConversion)
Definition at line 83 of file Geant4ConvertersTests.cpp.
View newest version in sPHENIX GitHub at line 83 of file Geant4ConvertersTests.cpp
References bounds, CHECK_CLOSE_ABS, Acts::UnitConstants::e, Acts::Geant4ShapeConverter::radialBounds(), and thickness.
BOOST_AUTO_TEST_CASE (Geant4LineConversion)
Definition at line 98 of file Geant4ConvertersTests.cpp.
View newest version in sPHENIX GitHub at line 98 of file Geant4ConvertersTests.cpp
References bounds, CHECK_CLOSE_ABS, Acts::UnitConstants::e, eR, line, and Acts::Geant4ShapeConverter::lineBounds().
BOOST_AUTO_TEST_CASE (Geant4BoxConversion)
Definition at line 106 of file Geant4ConvertersTests.cpp.
View newest version in sPHENIX GitHub at line 106 of file Geant4ConvertersTests.cpp
References Acts::Svg::axesXY(), CHECK_CLOSE_ABS, Acts::UnitConstants::e, and Acts::Geant4ShapeConverter::rectangleBounds().
BOOST_AUTO_TEST_CASE (Geant4TrapzoidConversion)
Definition at line 146 of file Geant4ConvertersTests.cpp.
View newest version in sPHENIX GitHub at line 146 of file Geant4ConvertersTests.cpp
References Acts::Svg::axesXY(), CHECK_CLOSE_ABS, Acts::UnitConstants::e, and Acts::Geant4ShapeConverter::trapezoidBounds().
BOOST_AUTO_TEST_CASE (Geant4PlanarConversion)
Definition at line 216 of file Geant4ConvertersTests.cpp.
View newest version in sPHENIX GitHub at line 216 of file Geant4ConvertersTests.cpp
References Acts::Geant4ShapeConverter::planarBounds(), and rBounds.
BOOST_AUTO_TEST_CASE (Geant4BoxVPhysConversion)
Definition at line 230 of file Geant4ConvertersTests.cpp.
View newest version in sPHENIX GitHub at line 230 of file Geant4ConvertersTests.cpp
References CHECK_CLOSE_ABS, CHECK_CLOSE_REL, g4Material, material, rho, Acts::Geant4PhysicalVolumeConverter::surface(), and thickness.
BOOST_AUTO_TEST_CASE (Geant4CylVPhysConversion)
CHECK exception throwing
Definition at line 281 of file Geant4ConvertersTests.cpp.
View newest version in sPHENIX GitHub at line 281 of file Geant4ConvertersTests.cpp
References CHECK_CLOSE_ABS, CHECK_CLOSE_REL, g4Material, material, rho, Acts::Geant4PhysicalVolumeConverter::surface(), and thickness.
BOOST_AUTO_TEST_CASE (Geant4VDiscVPhysConversion)
Definition at line 323 of file Geant4ConvertersTests.cpp.
View newest version in sPHENIX GitHub at line 323 of file Geant4ConvertersTests.cpp
References CHECK_CLOSE_ABS, g4Material, material, rho, Acts::Geant4PhysicalVolumeConverter::surface(), and thickness.
BOOST_AUTO_TEST_CASE (Geant4LineVPhysConversion)
Definition at line 355 of file Geant4ConvertersTests.cpp.
View newest version in sPHENIX GitHub at line 355 of file Geant4ConvertersTests.cpp
References g4Material, Acts::Geant4PhysicalVolumeConverter::surface(), and thickness.
Variable Documentation
G4Material* g4Material = new G4Material("Material", 6., 12., rho)
Definition at line 45 of file Geant4ConvertersTests.cpp.
View newest version in sPHENIX GitHub at line 45 of file Geant4ConvertersTests.cpp
Referenced by BOOST_AUTO_TEST_CASE(), and Acts::Geant4PhysicalVolumeConverter::surface().
Acts::ActsScalar rho = 1.2345
Definition at line 44 of file Geant4ConvertersTests.cpp.
View newest version in sPHENIX GitHub at line 44 of file Geant4ConvertersTests.cpp
Referenced by GPUTPCTrackParam::BetheBlochGas(), GPUTPCTrackParam::BetheBlochGeant(), Acts::Test::BOOST_AUTO_TEST_CASE(), BOOST_AUTO_TEST_CASE(), Acts::estimateTrackParamsFromSeed(), ActsExamples::ParticleSelector::execute(), ActsExamples::TruthSeedSelector::execute(), fullMaterial(), Acts::ImpactPointEstimator< input_track_t, propagator_t, propagator_options_t >::getDistanceAndMomentum(), genfit::GblFitter::getScattererFromMatList(), getScattererFromMatList(), ActsFatras::detail::GeneralMixture::getSemigauss(), Fatras::GeneralMixture::getSemigauss(), layerMaterial(), Hydro::NSquant(), JetMultSub::process_event(), pyhixtot(), FieldMaps::ReadCharge(), SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::ClustInfo::Reset(), sChargeMap::SaveRho(), SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::ClustInfo::SetInfo(), ActsExamples::MaterialSteppingAction::UserSteppingAction(), while(), and ActsExamples::RootMaterialWriter::writeMaterial().
Acts::GeometryContext tContext
Definition at line 42 of file Geant4ConvertersTests.cpp.
View newest version in sPHENIX GitHub at line 42 of file Geant4ConvertersTests.cpp