Analysis Software: TowerInfoContainerv3 Class Reference
TowerInfoContainerv3 Class Reference
#include <coresoftware/blob/master/offline/packages/CaloBase/TowerInfoContainerv3.h>
Public Member Functions
TowerInfoContainerv3 (DETECTOR detec)
TowerInfoContainerv3 ()
PHObject * CloneMe () const override
Virtual copy constructor.
TowerInfoContainerv3 (const TowerInfoContainerv3 &)
~TowerInfoContainerv3 () override
void identify (std::ostream &os=std::cout) const override
void Reset () override
Clear Event.
TowerInfov3 * get_tower_at_channel (int pos) override
TowerInfov3 * get_tower_at_key (int pos) override
unsigned int encode_key (unsigned int towerIndex) override
unsigned int decode_key (unsigned int tower_key) override
size_t size () const override
DETECTOR get_detectorid () const override
Public Member Functions inherited from TowerInfoContainer
TowerInfoContainer ()=default
~TowerInfoContainer () override=default
virtual unsigned int encode_epd (unsigned int)
virtual unsigned int encode_hcal (unsigned int)
virtual unsigned int encode_emcal (unsigned int)
virtual unsigned int encode_mbd (unsigned int)
virtual unsigned int encode_zdc (unsigned int)
virtual unsigned int decode_epd (unsigned int)
virtual unsigned int decode_hcal (unsigned int)
virtual unsigned int decode_emcal (unsigned int)
virtual unsigned int decode_mbd (unsigned int)
virtual unsigned int decode_zdc (unsigned int)
virtual unsigned int getTowerPhiBin (unsigned int)
virtual unsigned int getTowerEtaBin (unsigned int)
Public Member Functions inherited from PHObject
PHObject ()
ctor
~PHObject () override
dtor
virtual PHObject * clone () const final
PHObject * Clone (const char *newname="") const final
void Copy (TObject &object) const final
virtual int isValid () const
isValid returns non zero if object contains vailid data
virtual int Integrate () const
virtual int Integrate (PHObject *)
virtual void CopyFrom (const PHObject *obj)
Protected Attributes
TClonesArray * _clones = nullptr
DETECTOR _detector = DETECTOR_INVALID
Private Member Functions
ClassDefOverride (TowerInfoContainerv3, 1)
Additional Inherited Members
Public Types inherited from TowerInfoContainer
enum DETECTOR {
EMCAL = 0, HCAL = 1, SEPD = 2, MBD = 3,
ZDC = 4, DETECTOR_INVALID = 9999
}
typedef std::map< unsigned int,
TowerInfo * > TowerMap
typedef TowerMap::const_iterator ConstIter
typedef TowerMap::iterator Iter
Detailed Description
Definition at line 11 of file TowerInfoContainerv3.h.
View newest version in sPHENIX GitHub at line 11 of file TowerInfoContainerv3.h
Constructor & Destructor Documentation
TowerInfoContainerv3::TowerInfoContainerv3 (DETECTOR detec)
Definition at line 12 of file TowerInfoContainerv3.cc.
View newest version in sPHENIX GitHub at line 12 of file TowerInfoContainerv3.cc
References _clones, _detector, i, Enable::MBD, CaloTowerDefs::SEPD, and RawTowerDefs::ZDC.
TowerInfoContainerv3::TowerInfoContainerv3 () inline
Definition at line 17 of file TowerInfoContainerv3.h.
View newest version in sPHENIX GitHub at line 17 of file TowerInfoContainerv3.h
Referenced by CloneMe().
TowerInfoContainerv3::TowerInfoContainerv3 (const TowerInfoContainerv3 & source)
Definition at line 47 of file TowerInfoContainerv3.cc.
View newest version in sPHENIX GitHub at line 47 of file TowerInfoContainerv3.cc
References _clones, _detector, get_detectorid(), i, and size().
TowerInfoContainerv3::~TowerInfoContainerv3 () override
Definition at line 61 of file TowerInfoContainerv3.cc.
View newest version in sPHENIX GitHub at line 61 of file TowerInfoContainerv3.cc
References _clones.
Member Function Documentation
TowerInfoContainerv3::ClassDefOverride (TowerInfoContainerv3 , 1) private
PHObject* TowerInfoContainerv3::CloneMe () const inline override virtual
Virtual copy constructor.
Reimplemented from PHObject.
Definition at line 18 of file TowerInfoContainerv3.h.
View newest version in sPHENIX GitHub at line 18 of file TowerInfoContainerv3.h
References TowerInfoContainerv3().
unsigned int TowerInfoContainerv3::decode_key (unsigned int tower_key) override virtual
Reimplemented from TowerInfoContainer.
Definition at line 134 of file TowerInfoContainerv3.cc.
View newest version in sPHENIX GitHub at line 134 of file TowerInfoContainerv3.cc
References _detector, TowerInfoContainer::decode_emcal(), TowerInfoContainer::decode_epd(), TowerInfoContainer::decode_hcal(), TowerInfoContainer::decode_mbd(), TowerInfoContainer::decode_zdc(), index, Enable::MBD, CaloTowerDefs::SEPD, and RawTowerDefs::ZDC.
Referenced by get_tower_at_key().
unsigned int TowerInfoContainerv3::encode_key (unsigned int towerIndex) override virtual
Reimplemented from TowerInfoContainer.
Definition at line 108 of file TowerInfoContainerv3.cc.
View newest version in sPHENIX GitHub at line 108 of file TowerInfoContainerv3.cc
References _detector, TowerInfoContainer::encode_emcal(), TowerInfoContainer::encode_epd(), TowerInfoContainer::encode_hcal(), TowerInfoContainer::encode_mbd(), TowerInfoContainer::encode_zdc(), Enable::MBD, CaloTowerDefs::SEPD, and RawTowerDefs::ZDC.
DETECTOR TowerInfoContainerv3::get_detectorid () const inline override virtual
Reimplemented from TowerInfoContainer.
Definition at line 33 of file TowerInfoContainerv3.h.
View newest version in sPHENIX GitHub at line 33 of file TowerInfoContainerv3.h
References _detector.
Referenced by TowerInfoContainerv3().
TowerInfov3 * TowerInfoContainerv3::get_tower_at_channel (int pos) override virtual
Reimplemented from TowerInfoContainer.
Definition at line 97 of file TowerInfoContainerv3.cc.
View newest version in sPHENIX GitHub at line 97 of file TowerInfoContainerv3.cc
References _clones.
TowerInfov3 * TowerInfoContainerv3::get_tower_at_key (int pos) override virtual
Reimplemented from TowerInfoContainer.
Definition at line 102 of file TowerInfoContainerv3.cc.
View newest version in sPHENIX GitHub at line 102 of file TowerInfoContainerv3.cc
References _clones, decode_key(), and index.
void TowerInfoContainerv3::identify (std::ostream & os = std::cout) const override virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from TowerInfoContainer.
Definition at line 66 of file TowerInfoContainerv3.cc.
View newest version in sPHENIX GitHub at line 66 of file TowerInfoContainerv3.cc
References size().
void TowerInfoContainerv3::Reset () override virtual
Clear Event.
Reimplemented from TowerInfoContainer.
Definition at line 71 of file TowerInfoContainerv3.cc.
View newest version in sPHENIX GitHub at line 71 of file TowerInfoContainerv3.cc
References _clones, assert, and i.
size_t TowerInfoContainerv3::size (void) const inline override virtual
Reimplemented from TowerInfoContainer.
Definition at line 32 of file TowerInfoContainerv3.h.
View newest version in sPHENIX GitHub at line 32 of file TowerInfoContainerv3.h
References _clones.
Referenced by identify(), and TowerInfoContainerv3().
Member Data Documentation
TClonesArray* TowerInfoContainerv3::_clones = nullptr protected
Definition at line 36 of file TowerInfoContainerv3.h.
View newest version in sPHENIX GitHub at line 36 of file TowerInfoContainerv3.h
Referenced by get_tower_at_channel(), get_tower_at_key(), Reset(), size(), TowerInfoContainerv3(), and ~TowerInfoContainerv3().
DETECTOR TowerInfoContainerv3::_detector = DETECTOR_INVALID protected
Definition at line 37 of file TowerInfoContainerv3.h.
View newest version in sPHENIX GitHub at line 37 of file TowerInfoContainerv3.h
Referenced by decode_key(), encode_key(), get_detectorid(), and TowerInfoContainerv3().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/CaloBase/TowerInfoContainerv3.h
coresoftware/blob/master/offline/packages/CaloBase/TowerInfoContainerv3.cc