Analysis Software: ActsExamples::CsvSpacePointReader Exception Reference
ActsExamples::CsvSpacePointReader Exception Reference final
#include <acts/blob/sPHENIX/Examples/Io/Csv/include/ActsExamples/Io/Csv/CsvSpacePointReader.hpp>
Classes
struct Config
Public Member Functions
CsvSpacePointReader (const Config &cfg, Acts::Logging::Level lvl)
std::string name () const override
The algorithm name.
std::pair< size_t, size_t > availableEvents () const override
Return the available events range.
ProcessCode read (const ActsExamples::AlgorithmContext &ctx) override
Read out data from the input stream.
const Config & config () const
Readonly access to the config.
Public Member Functions inherited from ActsExamples::IReader
ProcessCode internalExecute (const AlgorithmContext &context) final
ProcessCode initialize () override
Fulfill the algorithm interface.
ProcessCode finalize () override
Fulfill the algorithm interface.
Public Member Functions inherited from ActsExamples::SequenceElement
virtual ~SequenceElement ()=default
const std::vector< const
DataHandleBase * > & writeHandles () const
const std::vector< const
DataHandleBase * > & readHandles () const
Private Member Functions
const Acts::Logger & logger () const
Private Attributes
Config m_cfg
WriteDataHandle
< SimSpacePointContainer > m_outputSpacePoints
std::pair< size_t, size_t > m_eventsRange
std::unique_ptr< const
Acts::Logger > m_logger
Detailed Description
Read in a simhit collection in comma-separated-value format.
This reads one files per event in the configured input directory. By default it reads files in the current working directory. Files are assumed to be named using the following schema
event000000001-<stem>.csv
event000000002-<stem>.csv
and each line in the file corresponds to one simhit.
Definition at line 37 of file CsvSpacePointReader.hpp.
View newest version in sPHENIX GitHub at line 37 of file CsvSpacePointReader.hpp
Constructor & Destructor Documentation
ActsExamples::CsvSpacePointReader::CsvSpacePointReader (const Config & cfg, Acts::Logging::Level lvl)
Construct the simhit reader.
cfg is the configuration object lvl is the logging level
Definition at line 27 of file CsvSpacePointReader.cpp.
View newest version in sPHENIX GitHub at line 27 of file CsvSpacePointReader.cpp
References cfg, ActsExamples::determineEventFilesRange(), filename, Acts::getDefaultLogger(), ActsExamples::WriteDataHandle< T >::initialize(), ActsExamples::CsvSpacePointReader::Config::inputCollection, ActsExamples::CsvSpacePointReader::Config::inputDir, ActsExamples::CsvSpacePointReader::Config::inputStem, m_cfg, m_eventsRange, m_logger, m_outputSpacePoints, and ActsExamples::CsvSpacePointReader::Config::outputSpacePoints.
Member Function Documentation
std::pair< size_t, size_t > ActsExamples::CsvSpacePointReader::availableEvents () const override virtual
Return the available events range.
Implements ActsExamples::IReader.
Definition at line 48 of file CsvSpacePointReader.cpp.
View newest version in sPHENIX GitHub at line 48 of file CsvSpacePointReader.cpp
const Config& ActsExamples::CsvSpacePointReader::config () const inline
Readonly access to the config.
Definition at line 67 of file CsvSpacePointReader.hpp.
View newest version in sPHENIX GitHub at line 67 of file CsvSpacePointReader.hpp
References m_cfg.
const Acts::Logger& ActsExamples::CsvSpacePointReader::logger () const inline private
Definition at line 78 of file CsvSpacePointReader.hpp.
View newest version in sPHENIX GitHub at line 78 of file CsvSpacePointReader.hpp
References m_logger.
std::string ActsExamples::CsvSpacePointReader::name () const override virtual
The algorithm name.
Implements ActsExamples::SequenceElement.
ActsExamples::ProcessCode ActsExamples::CsvSpacePointReader::read (const ActsExamples::AlgorithmContext & ctx) override virtual
Read out data from the input stream.
Implements ActsExamples::IReader.
Definition at line 53 of file CsvSpacePointReader.cpp.
View newest version in sPHENIX GitHub at line 53 of file CsvSpacePointReader.cpp
References ACTS_DEBUG, ACTS_ERROR, configureMap::data, ActsExamples::AlgorithmContext::eventNumber, filename, m_cfg(), testing::internal::move(), path, ActsExamples::perEventFilepath(), summary::reader, ActsExamples::SpacePointData::sp_bottomHalfStripLength, ActsExamples::SpacePointData::sp_bottomStripDirection, ActsExamples::SpacePointData::sp_covr, ActsExamples::SpacePointData::sp_covz, ActsExamples::SpacePointData::sp_stripCenterDistance, ActsExamples::SpacePointData::sp_topHalfStripLength, ActsExamples::SpacePointData::sp_topStripCenterPosition, ActsExamples::SpacePointData::sp_topStripDirection, ActsExamples::SpacePointData::sp_x, ActsExamples::SpacePointData::sp_y, ActsExamples::SpacePointData::sp_z, and SUCCESS.
Member Data Documentation
Config ActsExamples::CsvSpacePointReader::m_cfg private
Definition at line 70 of file CsvSpacePointReader.hpp.
View newest version in sPHENIX GitHub at line 70 of file CsvSpacePointReader.hpp
Referenced by config(), and CsvSpacePointReader().
std::pair<size_t, size_t> ActsExamples::CsvSpacePointReader::m_eventsRange private
Definition at line 75 of file CsvSpacePointReader.hpp.
View newest version in sPHENIX GitHub at line 75 of file CsvSpacePointReader.hpp
Referenced by CsvSpacePointReader().
std::unique_ptr<const Acts::Logger> ActsExamples::CsvSpacePointReader::m_logger private
Definition at line 76 of file CsvSpacePointReader.hpp.
View newest version in sPHENIX GitHub at line 76 of file CsvSpacePointReader.hpp
Referenced by CsvSpacePointReader(), and logger().
WriteDataHandle<SimSpacePointContainer> ActsExamples::CsvSpacePointReader::m_outputSpacePoints private
Initial value:
{
      this, "OutputSpacePoints"}
Definition at line 72 of file CsvSpacePointReader.hpp.
View newest version in sPHENIX GitHub at line 72 of file CsvSpacePointReader.hpp
Referenced by CsvSpacePointReader().
The documentation for this exception was generated from the following files:
acts/blob/sPHENIX/Examples/Io/Csv/include/ActsExamples/Io/Csv/CsvSpacePointReader.hpp
acts/blob/sPHENIX/Examples/Io/Csv/src/CsvSpacePointReader.cpp