Analysis Software: BbcCheck Class Reference
BbcCheck Class Reference
#include <analysis/blob/master/BBCStudy/BbcCheck.h>
Public Member Functions
BbcCheck (const std::string &name="BbcCheck")
int Init (PHCompositeNode *)
int InitRun (PHCompositeNode *)
int process_event (PHCompositeNode *)
int End (PHCompositeNode *)
Called at the end of all processing.
void set_savefile (const char *f)
void set_run (const int r)
Public Member Functions inherited from SubsysReco
~SubsysReco () override
virtual int EndRun (const int)
Called at the end of each run.
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
void Print (const std::string &="ALL") const override
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Private Member Functions
void CheckDST (PHCompositeNode *topNode)
int Getpeaktime (TH1 *h)
void process_zdc (PHCompositeNode *topNode)
void process_emcal (PHCompositeNode *topNode)
void process_ohcal (PHCompositeNode *topNode)
void process_ihcal (PHCompositeNode *topNode)
void GetNodes (PHCompositeNode *)
Private Attributes
std::string _savefname
TFile * _savefile
int nprocessed {0}
TTree * _tree
Int_t f_run
Int_t f_evt
Int_t f_ch
Float_t f_qmean
Float_t f_qmerr
Float_t f_bimp
Int_t f_ncoll
Int_t f_npart
Float_t f_vx
Float_t f_vy
Float_t f_vz
Float_t f_vt
Short_t f_bbcn [2]
Float_t f_bbcq [2]
Float_t f_bbct [2]
Float_t f_bbcte [2]
Float_t f_bbcz
Float_t f_bbct0
TH1 * h_bbcq [128]
TGraphErrors * g_bbcq [128]
TH1 * h_bbcqtot [2]
TH1 * h_bbcqsum
TH2 * h2_bbcqsum
TH1 * h_emcale
TH1 * h_emcaltimecut
TH1 * h_ohcale
TH1 * h_ohcaltimecut
TH1 * h_ihcale
TH1 * h_ihcaltimecut
TH1 * h_zdce
TH1 * h_zdctimecut
TH1 * h_bz
TCanvas * c_bbct
TH1 * hevt_bbct [2]
TF1 * gaussian
std::map< int, int > _pids
TRandom3 * _rndm
Float_t _tres
EventHeader * _evtheader
MbdOut * _bbcout
MbdPmtContainer * _bbcpmts
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = std::numeric_limits<int>::max() - 10
}
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Detailed Description
Definition at line 26 of file BbcCheck.h.
View newest version in sPHENIX GitHub at line 26 of file BbcCheck.h
Constructor & Destructor Documentation
BbcCheck::BbcCheck (const std::string & name = "BbcCheck")
Definition at line 46 of file BbcCheck.cc.
View newest version in sPHENIX GitHub at line 46 of file BbcCheck.cc
Member Function Documentation
void BbcCheck::CheckDST (PHCompositeNode * topNode) private
Definition at line 234 of file BbcCheck.cc.
View newest version in sPHENIX GitHub at line 234 of file BbcCheck.cc
References _bbcout, _bbcpmts, GlobalVertexMap::begin(), GlobalVertexMap::empty(), MbdPmtContainer::get_npmt(), MbdPmtContainer::get_pmt(), MbdPmtHit::get_q(), MbdOut::get_q(), MbdPmtHit::get_time(), GlobalVertex::get_z(), MbdOut::get_zvtx(), h2_bbcqsum, h_bbcq, h_bbcqsum, h_bbcqtot, h_bz, process_emcal(), process_ihcal(), process_ohcal(), process_zdc(), physmon_track_finding_ttbar::r, and t.
Referenced by process_event().
int BbcCheck::End (PHCompositeNode *) virtual
Called at the end of all processing.
Reimplemented from SubsysReco.
Definition at line 199 of file BbcCheck.cc.
View newest version in sPHENIX GitHub at line 199 of file BbcCheck.cc
References _savefile, _tree, BbcDefs::BBC_N_PMT, f_ch, f_qmean, f_qmerr, f_run, g_bbcq, h2_bbcqsum, h_bbcq, h_bbcqsum, h_bbcqtot, nevents(), norm, and nprocessed.
void BbcCheck::GetNodes (PHCompositeNode * topNode) private
Definition at line 181 of file BbcCheck.cc.
View newest version in sPHENIX GitHub at line 181 of file BbcCheck.cc
References _bbcout, _bbcpmts, f_evt, and PHWHERE.
Referenced by InitRun().
int BbcCheck::Getpeaktime (TH1 * h) private
Definition at line 296 of file BbcCheck.cc.
View newest version in sPHENIX GitHub at line 296 of file BbcCheck.cc
References Acts::PhysicalConstants::c.
Referenced by process_emcal(), process_ihcal(), process_ohcal(), and process_zdc().
int BbcCheck::Init (PHCompositeNode *) virtual
Called during initialization. Typically this is where you can book histograms, and e.g. register them to Fun4AllServer (so they can be output to file using Fun4AllServer::dumpHistos() method).
Reimplemented from SubsysReco.
Definition at line 57 of file BbcCheck.cc.
View newest version in sPHENIX GitHub at line 57 of file BbcCheck.cc
References _savefile, _savefname, _tree, c_bbct, f_ch, f_qmean, f_qmerr, f_run, g_bbcq, gaussian, h2_bbcqsum, h_bbcq, h_bbcqsum, h_bbcqtot, h_bz, h_emcale, h_emcaltimecut, h_ihcale, h_ihcaltimecut, h_ohcale, h_ohcaltimecut, h_zdce, h_zdctimecut, hevt_bbct, perf_headwind::name, PHWHERE, and title.
int BbcCheck::InitRun (PHCompositeNode *) virtual
Called for first event when run number is known. Typically this is where you may want to fetch data from database, because you know the run number.
Reimplemented from SubsysReco.
Definition at line 129 of file BbcCheck.cc.
View newest version in sPHENIX GitHub at line 129 of file BbcCheck.cc
References f_run, PHFlag::get_IntFlag(), GetNodes(), and recoConsts::instance().
void BbcCheck::process_emcal (PHCompositeNode * topNode) private
Definition at line 347 of file BbcCheck.cc.
View newest version in sPHENIX GitHub at line 347 of file BbcCheck.cc
References channel(), energy, TowerInfo::get_energy(), TowerInfo::get_time(), TowerInfoContainer::get_tower_at_channel(), Getpeaktime(), h_emcale, h_emcaltimecut, TowerInfoContainer::size(), size, and t.
Referenced by CheckDST().
int BbcCheck::process_event (PHCompositeNode *) virtual
Called for each event. This is where you do the real work.
Reimplemented from SubsysReco.
Definition at line 141 of file BbcCheck.cc.
View newest version in sPHENIX GitHub at line 141 of file BbcCheck.cc
References CheckDST(), f_bbcn, f_bbcq, f_bbct, f_bbct0, f_bbcte, f_bbcz, hevt_bbct, and nprocessed.
void BbcCheck::process_ihcal (PHCompositeNode * topNode) private
Definition at line 401 of file BbcCheck.cc.
View newest version in sPHENIX GitHub at line 401 of file BbcCheck.cc
References channel(), energy, TowerInfo::get_energy(), TowerInfo::get_time(), TowerInfoContainer::get_tower_at_channel(), Getpeaktime(), h_ihcale, h_ihcaltimecut, TowerInfoContainer::size(), size, and t.
Referenced by CheckDST().
void BbcCheck::process_ohcal (PHCompositeNode * topNode) private
Definition at line 374 of file BbcCheck.cc.
View newest version in sPHENIX GitHub at line 374 of file BbcCheck.cc
References channel(), energy, TowerInfo::get_energy(), TowerInfo::get_time(), TowerInfoContainer::get_tower_at_channel(), Getpeaktime(), h_ohcale, h_ohcaltimecut, TowerInfoContainer::size(), size, and t.
Referenced by CheckDST().
void BbcCheck::process_zdc (PHCompositeNode * topNode) private
Definition at line 316 of file BbcCheck.cc.
View newest version in sPHENIX GitHub at line 316 of file BbcCheck.cc
References TowerInfo::get_energy(), TowerInfo::get_time(), TowerInfoContainer::get_tower_at_channel(), Getpeaktime(), h_zdce, h_zdctimecut, TowerInfoContainer::size(), and size.
Referenced by CheckDST().
void BbcCheck::set_run (const int r) inline
Definition at line 48 of file BbcCheck.h.
View newest version in sPHENIX GitHub at line 48 of file BbcCheck.h
References f_run, and physmon_track_finding_ttbar::r.
void BbcCheck::set_savefile (const char * f) inline
Definition at line 46 of file BbcCheck.h.
View newest version in sPHENIX GitHub at line 46 of file BbcCheck.h
References _savefname, and f.
Referenced by Run_BbcCheck().
Member Data Documentation
MbdOut* BbcCheck::_bbcout private
Definition at line 120 of file BbcCheck.h.
View newest version in sPHENIX GitHub at line 120 of file BbcCheck.h
Referenced by CheckDST(), and GetNodes().
MbdPmtContainer* BbcCheck::_bbcpmts private
Definition at line 121 of file BbcCheck.h.
View newest version in sPHENIX GitHub at line 121 of file BbcCheck.h
Referenced by CheckDST(), and GetNodes().
EventHeader* BbcCheck::_evtheader private
Definition at line 119 of file BbcCheck.h.
View newest version in sPHENIX GitHub at line 119 of file BbcCheck.h
std::map<int,int> BbcCheck::_pids private
Definition at line 109 of file BbcCheck.h.
View newest version in sPHENIX GitHub at line 109 of file BbcCheck.h
TRandom3* BbcCheck::_rndm private
Definition at line 112 of file BbcCheck.h.
View newest version in sPHENIX GitHub at line 112 of file BbcCheck.h
TFile* BbcCheck::_savefile private
Definition at line 63 of file BbcCheck.h.
View newest version in sPHENIX GitHub at line 63 of file BbcCheck.h
Referenced by End(), and Init().
std::string BbcCheck::_savefname private
Definition at line 62 of file BbcCheck.h.
View newest version in sPHENIX GitHub at line 62 of file BbcCheck.h
Referenced by Init(), and set_savefile().
TTree* BbcCheck::_tree private
Definition at line 68 of file BbcCheck.h.
View newest version in sPHENIX GitHub at line 68 of file BbcCheck.h
Referenced by End(), and Init().
Float_t BbcCheck::_tres private
Definition at line 113 of file BbcCheck.h.
View newest version in sPHENIX GitHub at line 113 of file BbcCheck.h
TCanvas* BbcCheck::c_bbct private
Definition at line 105 of file BbcCheck.h.
View newest version in sPHENIX GitHub at line 105 of file BbcCheck.h
Referenced by Init().
Short_t BbcCheck::f_bbcn[2] private
Definition at line 82 of file BbcCheck.h.
View newest version in sPHENIX GitHub at line 82 of file BbcCheck.h
Referenced by process_event().
Float_t BbcCheck::f_bbcq[2] private
Definition at line 83 of file BbcCheck.h.
View newest version in sPHENIX GitHub at line 83 of file BbcCheck.h
Referenced by process_event().
Float_t BbcCheck::f_bbct[2] private
Definition at line 84 of file BbcCheck.h.
View newest version in sPHENIX GitHub at line 84 of file BbcCheck.h
Referenced by process_event().
Float_t BbcCheck::f_bbct0 private
Definition at line 87 of file BbcCheck.h.
View newest version in sPHENIX GitHub at line 87 of file BbcCheck.h
Referenced by process_event().
Float_t BbcCheck::f_bbcte[2] private
Definition at line 85 of file BbcCheck.h.
View newest version in sPHENIX GitHub at line 85 of file BbcCheck.h
Referenced by process_event().
Float_t BbcCheck::f_bbcz private
Definition at line 86 of file BbcCheck.h.
View newest version in sPHENIX GitHub at line 86 of file BbcCheck.h
Referenced by process_event().
Float_t BbcCheck::f_bimp private
Definition at line 75 of file BbcCheck.h.
View newest version in sPHENIX GitHub at line 75 of file BbcCheck.h
Int_t BbcCheck::f_ch private
Definition at line 71 of file BbcCheck.h.
View newest version in sPHENIX GitHub at line 71 of file BbcCheck.h
Referenced by End(), and Init().
Int_t BbcCheck::f_evt private
Definition at line 70 of file BbcCheck.h.
View newest version in sPHENIX GitHub at line 70 of file BbcCheck.h
Referenced by GetNodes().
Int_t BbcCheck::f_ncoll private
Definition at line 76 of file BbcCheck.h.
View newest version in sPHENIX GitHub at line 76 of file BbcCheck.h
Int_t BbcCheck::f_npart private
Definition at line 77 of file BbcCheck.h.
View newest version in sPHENIX GitHub at line 77 of file BbcCheck.h
Float_t BbcCheck::f_qmean private
Definition at line 72 of file BbcCheck.h.
View newest version in sPHENIX GitHub at line 72 of file BbcCheck.h
Referenced by End(), and Init().
Float_t BbcCheck::f_qmerr private
Definition at line 73 of file BbcCheck.h.
View newest version in sPHENIX GitHub at line 73 of file BbcCheck.h
Referenced by End(), and Init().
Int_t BbcCheck::f_run private
Definition at line 69 of file BbcCheck.h.
View newest version in sPHENIX GitHub at line 69 of file BbcCheck.h
Referenced by End(), Init(), InitRun(), and set_run().
Float_t BbcCheck::f_vt private
Definition at line 81 of file BbcCheck.h.
View newest version in sPHENIX GitHub at line 81 of file BbcCheck.h
Float_t BbcCheck::f_vx private
Definition at line 78 of file BbcCheck.h.
View newest version in sPHENIX GitHub at line 78 of file BbcCheck.h
Float_t BbcCheck::f_vy private
Definition at line 79 of file BbcCheck.h.
View newest version in sPHENIX GitHub at line 79 of file BbcCheck.h
Float_t BbcCheck::f_vz private
Definition at line 80 of file BbcCheck.h.
View newest version in sPHENIX GitHub at line 80 of file BbcCheck.h
TGraphErrors* BbcCheck::g_bbcq[128] private
Definition at line 90 of file BbcCheck.h.
View newest version in sPHENIX GitHub at line 90 of file BbcCheck.h
Referenced by End(), and Init().
TF1* BbcCheck::gaussian private
Definition at line 107 of file BbcCheck.h.
View newest version in sPHENIX GitHub at line 107 of file BbcCheck.h
Referenced by Init().
TH2* BbcCheck::h2_bbcqsum private
Definition at line 93 of file BbcCheck.h.
View newest version in sPHENIX GitHub at line 93 of file BbcCheck.h
Referenced by CheckDST(), End(), and Init().
TH1* BbcCheck::h_bbcq[128] private
Definition at line 89 of file BbcCheck.h.
View newest version in sPHENIX GitHub at line 89 of file BbcCheck.h
Referenced by CheckDST(), End(), and Init().
TH1* BbcCheck::h_bbcqsum private
Definition at line 92 of file BbcCheck.h.
View newest version in sPHENIX GitHub at line 92 of file BbcCheck.h
Referenced by CheckDST(), End(), and Init().
TH1* BbcCheck::h_bbcqtot[2] private
Definition at line 91 of file BbcCheck.h.
View newest version in sPHENIX GitHub at line 91 of file BbcCheck.h
Referenced by CheckDST(), End(), and Init().
TH1* BbcCheck::h_bz private
Definition at line 103 of file BbcCheck.h.
View newest version in sPHENIX GitHub at line 103 of file BbcCheck.h
Referenced by CheckDST(), and Init().
TH1* BbcCheck::h_emcale private
Definition at line 95 of file BbcCheck.h.
View newest version in sPHENIX GitHub at line 95 of file BbcCheck.h
Referenced by Init(), and process_emcal().
TH1* BbcCheck::h_emcaltimecut private
Definition at line 96 of file BbcCheck.h.
View newest version in sPHENIX GitHub at line 96 of file BbcCheck.h
Referenced by Init(), and process_emcal().
TH1* BbcCheck::h_ihcale private
Definition at line 99 of file BbcCheck.h.
View newest version in sPHENIX GitHub at line 99 of file BbcCheck.h
Referenced by Init(), and process_ihcal().
TH1* BbcCheck::h_ihcaltimecut private
Definition at line 100 of file BbcCheck.h.
View newest version in sPHENIX GitHub at line 100 of file BbcCheck.h
Referenced by Init(), and process_ihcal().
TH1* BbcCheck::h_ohcale private
Definition at line 97 of file BbcCheck.h.
View newest version in sPHENIX GitHub at line 97 of file BbcCheck.h
Referenced by Init(), and process_ohcal().
TH1* BbcCheck::h_ohcaltimecut private
Definition at line 98 of file BbcCheck.h.
View newest version in sPHENIX GitHub at line 98 of file BbcCheck.h
Referenced by Init(), and process_ohcal().
TH1* BbcCheck::h_zdce private
Definition at line 101 of file BbcCheck.h.
View newest version in sPHENIX GitHub at line 101 of file BbcCheck.h
Referenced by Init(), and process_zdc().
TH1* BbcCheck::h_zdctimecut private
Definition at line 102 of file BbcCheck.h.
View newest version in sPHENIX GitHub at line 102 of file BbcCheck.h
Referenced by Init(), and process_zdc().
TH1* BbcCheck::hevt_bbct[2] private
Definition at line 106 of file BbcCheck.h.
View newest version in sPHENIX GitHub at line 106 of file BbcCheck.h
Referenced by Init(), and process_event().
int BbcCheck::nprocessed {0} private
Definition at line 65 of file BbcCheck.h.
View newest version in sPHENIX GitHub at line 65 of file BbcCheck.h
Referenced by End(), and process_event().
The documentation for this class was generated from the following files:
analysis/blob/master/BBCStudy/BbcCheck.h
analysis/blob/master/BBCStudy/BbcCheck.cc