Analysis Software: testing::internal::BeginEndDistanceIsMatcher< DistanceMatcher >::Impl< Container > Class Template Reference
testing::internal::BeginEndDistanceIsMatcher< DistanceMatcher >::Impl< Container > Class Template Reference
#include <JETSCAPE/blob/main/external_packages/googletest/googlemock/include/gmock/gmock-matchers.h>
Public Types
typedef
internal::StlContainerView
< GTEST_REMOVE_REFERENCE_AND_CONST_(Container)> ContainerView
typedef std::iterator_traits
< typename
ContainerView::type::const_iterator >
::difference_type DistanceType
Public Member Functions
Impl (const DistanceMatcher &distance_matcher)
virtual void DescribeTo (::std::ostream *os) const
virtual void DescribeNegationTo (::std::ostream *os) const
virtual bool MatchAndExplain (Container container, MatchResultListener *listener) const
Private Member Functions
GTEST_DISALLOW_ASSIGN_ (Impl)
Private Attributes
const Matcher< DistanceType > distance_matcher_
Detailed Description
template<typename DistanceMatcher>
template<typename Container>
class testing::internal::BeginEndDistanceIsMatcher< DistanceMatcher >::Impl< Container >
Definition at line 2463 of file gmock-matchers.h.
View newest version in sPHENIX GitHub at line 2463 of file gmock-matchers.h
Member Typedef Documentation
template<typename DistanceMatcher > template<typename Container > typedef internal::StlContainerView< GTEST_REMOVE_REFERENCE_AND_CONST_(Container)> testing::internal::BeginEndDistanceIsMatcher< DistanceMatcher >::Impl< Container >::ContainerView
Definition at line 2466 of file gmock-matchers.h.
View newest version in sPHENIX GitHub at line 2466 of file gmock-matchers.h
template<typename DistanceMatcher > template<typename Container > typedef std::iterator_traits< typename ContainerView::type::const_iterator>::difference_type testing::internal::BeginEndDistanceIsMatcher< DistanceMatcher >::Impl< Container >::DistanceType
Definition at line 2469 of file gmock-matchers.h.
View newest version in sPHENIX GitHub at line 2469 of file gmock-matchers.h
Constructor & Destructor Documentation
template<typename DistanceMatcher > template<typename Container > testing::internal::BeginEndDistanceIsMatcher< DistanceMatcher >::Impl< Container >::Impl (const DistanceMatcher & distance_matcher) inline explicit
Definition at line 2470 of file gmock-matchers.h.
View newest version in sPHENIX GitHub at line 2470 of file gmock-matchers.h
Member Function Documentation
template<typename DistanceMatcher > template<typename Container > virtual void testing::internal::BeginEndDistanceIsMatcher< DistanceMatcher >::Impl< Container >::DescribeNegationTo (::std::ostream * os) const inline virtual
Reimplemented from testing::MatcherDescriberInterface.
Definition at line 2477 of file gmock-matchers.h.
View newest version in sPHENIX GitHub at line 2477 of file gmock-matchers.h
References testing::internal::MatcherBase< T >::DescribeNegationTo(), and testing::internal::BeginEndDistanceIsMatcher< DistanceMatcher >::Impl< Container >::distance_matcher_.
template<typename DistanceMatcher > template<typename Container > virtual void testing::internal::BeginEndDistanceIsMatcher< DistanceMatcher >::Impl< Container >::DescribeTo (::std::ostream * os) const inline virtual
Implements testing::MatcherDescriberInterface.
Definition at line 2473 of file gmock-matchers.h.
View newest version in sPHENIX GitHub at line 2473 of file gmock-matchers.h
References testing::internal::MatcherBase< T >::DescribeTo(), and testing::internal::BeginEndDistanceIsMatcher< DistanceMatcher >::Impl< Container >::distance_matcher_.
template<typename DistanceMatcher > template<typename Container > testing::internal::BeginEndDistanceIsMatcher< DistanceMatcher >::Impl< Container >::GTEST_DISALLOW_ASSIGN_ (Impl< Container >) private
template<typename DistanceMatcher > template<typename Container > virtual bool testing::internal::BeginEndDistanceIsMatcher< DistanceMatcher >::Impl< Container >::MatchAndExplain (Container container, MatchResultListener * listener) const inline virtual
Implements testing::MatcherInterface< Container >.
Definition at line 2482 of file gmock-matchers.h.
View newest version in sPHENIX GitHub at line 2482 of file gmock-matchers.h
References parse_cmake_options::begin, distance(), testing::internal::BeginEndDistanceIsMatcher< DistanceMatcher >::Impl< Container >::distance_matcher_, end, testing::internal::MatcherBase< T >::MatchAndExplain(), testing::internal::PrintIfNotEmpty(), and testing::MatchResultListener::stream().
Member Data Documentation
template<typename DistanceMatcher > template<typename Container > const Matcher<DistanceType> testing::internal::BeginEndDistanceIsMatcher< DistanceMatcher >::Impl< Container >::distance_matcher_ private
Definition at line 2501 of file gmock-matchers.h.
View newest version in sPHENIX GitHub at line 2501 of file gmock-matchers.h
Referenced by testing::internal::BeginEndDistanceIsMatcher< DistanceMatcher >::Impl< Container >::DescribeNegationTo(), testing::internal::BeginEndDistanceIsMatcher< DistanceMatcher >::Impl< Container >::DescribeTo(), and testing::internal::BeginEndDistanceIsMatcher< DistanceMatcher >::Impl< Container >::MatchAndExplain().
The documentation for this class was generated from the following file:
JETSCAPE/blob/main/external_packages/googletest/googlemock/include/gmock/gmock-matchers.h