Analysis Software: macros/blob/master/common/G4_Jets.C File Reference
G4_Jets.C File Reference
#include <GlobalVariables.C>
#include <QA.C>
#include <jetbase/ClusterJetInput.h>
#include <jetbase/FastJetAlgo.h>
#include <jetbase/JetReco.h>
#include <jetbase/TowerJetInput.h>
#include <jetbase/TrackJetInput.h>
#include <g4jets/TruthJetInput.h>
#include <g4eval/JetEvaluator.h>
#include <qa_modules/QAG4SimulationJet.h>
#include <fun4all/Fun4AllServer.h>
Namespaces
namespace Enable
Macros
#define MACRO_G4JETS_C
Functions
void JetInit ()
void Jet_Reco ()
void Jet_Eval (const std::string &outfilename="g4jets_eval.root")
void Jet_QA ()
Variables
bool Enable::JETS = false
bool Enable::JETS_EVAL = false
bool Enable::JETS_QA = false
int Enable::JETS_VERBOSITY = 0
Macro Definition Documentation
#define MACRO_G4JETS_C
Definition at line 2 of file G4_Jets.C.
View newest version in sPHENIX GitHub at line 2 of file G4_Jets.C
Function Documentation
void Jet_Eval (const std::string & outfilename = "g4jets_eval.root")
Definition at line 107 of file G4_Jets.C.
View newest version in sPHENIX GitHub at line 107 of file G4_Jets.C
References Fun4AllServer::instance(), Enable::JETS_VERBOSITY, Fun4AllServer::registerSubsystem(), verbosity, Enable::VERBOSITY, and Fun4AllBase::Verbosity().
void Jet_QA ()
Definition at line 124 of file G4_Jets.C.
View newest version in sPHENIX GitHub at line 124 of file G4_Jets.C
References QAG4SimulationJet::add_reco_jet(), Fun4AllServer::instance(), Enable::JETS_VERBOSITY, Enable::QA_VERBOSITY, Fun4AllServer::registerSubsystem(), verbosity, and Fun4AllBase::Verbosity().
Referenced by Fun4All_AnaTutorial_sPHENIX(), Fun4All_AnaTutorial_sPHENIX_Jets(), Fun4All_G4_sPHENIX(), Fun4All_G4_sPHENIX_ForTrackCutStudy(), Fun4All_G4_sPHENIX_ForTrackCutStudy_EmbedScanOff(), Fun4All_G4_sPHENIX_ForTrackCutStudy_EmbedScanOn(), Fun4All_G4_sPHENIX_ForTrackCutStudy_WithPileup_EmbedScanOff(), Fun4All_G4_sPHENIX_ForTrackCutStudy_WithPileup_EmbedScanOn(), Fun4All_Pi0Gen_sPHENIX(), Fun4All_pi0tbt_SIMPLE_EMBED(), Fun4All_RunNewTruthMatcher(), Fun4All_SinglePhotonGen_sPHENIX(), and Fun4All_SinglePi0Gen_sPHENIX().
void Jet_Reco ()
Definition at line 34 of file G4_Jets.C.
View newest version in sPHENIX GitHub at line 34 of file G4_Jets.C
References JetReco::add_algo(), JetReco::add_input(), Jet::ANTIKT, Jet::CEMC_CLUSTER, Jet::CEMC_TOWER, Jet::HCALIN_CLUSTER, Jet::HCALIN_TOWER, Jet::HCALOUT_CLUSTER, Jet::HCALOUT_TOWER, Fun4AllServer::instance(), Enable::JETS_VERBOSITY, Jet::PARTICLE, Fun4AllServer::registerSubsystem(), JetReco::set_algo_node(), JetReco::set_input_node(), Jet::TRACK, TRACKING::TrackNodeName, verbosity, Enable::VERBOSITY, and Fun4AllBase::Verbosity().
void JetInit ()
Definition at line 32 of file G4_Jets.C.
View newest version in sPHENIX GitHub at line 32 of file G4_Jets.C