Analysis Software: ActsFatras::PhysicsList< processes_t > Class Template Reference
ActsFatras::PhysicsList< processes_t > Class Template Reference
#include <acts/blob/sPHENIX/Fatras/include/ActsFatras/Kernel/PhysicsList.hpp>
Classes
struct Index< T, std::tuple< T, Types...> >
struct Index< T, std::tuple< U, Types...> >
Public Member Functions
template<typename generator_t >
bool operator() (generator_t &generator, const Acts::MaterialSlab &slab, Particle &particle, std::vector< Particle > &generated) const
template<size_t I>
std::tuple_element_t< I,
std::tuple< processes_t...> > & get ()
Access a specific process by index.
template<typename process_t >
process_t & get ()
Access a specific process by type.
void disable (std::size_t i)
Disable a specific process by index.
template<typename process_t >
void disable ()
Private Member Functions
template<typename generator_t >
bool impl (std::index_sequence<>, generator_t &, const Acts::MaterialSlab &, Particle &, std::vector< Particle > &) const
template<std::size_t I0, std::size_t... INs, typename generator_t >
bool impl (std::index_sequence< I0, INs...>, generator_t &generator, const Acts::MaterialSlab &slab, Particle &particle, std::vector< Particle > &generated) const
Private Attributes
std::bitset< sizeof...(processes_t)> m_mask
std::tuple< processes_t...> m_processes
Detailed Description
template<typename... processes_t>
class ActsFatras::PhysicsList< processes_t >
Combined set of physics processes and interactions for the simulation.
The physics processes are extendable by the user to be able to accomodate the specific requirements. While the set of available physics processes must be configured at compile-time, within that set processes can be selectively disabled at run-time. By default all processes are applied.
Definition at line 26 of file PhysicsList.hpp.
View newest version in sPHENIX GitHub at line 26 of file PhysicsList.hpp
Member Function Documentation
template<typename... processes_t> void ActsFatras::PhysicsList< processes_t >::disable (std::size_t i) inline
Disable a specific process by index.
Definition at line 62 of file PhysicsList.hpp.
View newest version in sPHENIX GitHub at line 62 of file PhysicsList.hpp
References ActsFatras::PhysicsList< processes_t >::m_mask.
Referenced by BOOST_AUTO_TEST_CASE().
template<typename... processes_t> template<typename process_t > void ActsFatras::PhysicsList< processes_t >::disable () inline
Disable a specific process by type.
Warning
Disables only the first of multiple processes of the same type.
Definition at line 67 of file PhysicsList.hpp.
View newest version in sPHENIX GitHub at line 67 of file PhysicsList.hpp
References value.
template<typename... processes_t> template<size_t I> std::tuple_element_t<I, std::tuple<processes_t...> >& ActsFatras::PhysicsList< processes_t >::get () inline
Access a specific process by index.
Definition at line 52 of file PhysicsList.hpp.
View newest version in sPHENIX GitHub at line 52 of file PhysicsList.hpp
References I, and ActsFatras::PhysicsList< processes_t >::m_processes.
Referenced by BOOST_AUTO_TEST_CASE(), and ActsFatras::makeChargedElectroMagneticPhysicsList().
template<typename... processes_t> template<typename process_t > process_t& ActsFatras::PhysicsList< processes_t >::get () inline
Access a specific process by type.
Definition at line 57 of file PhysicsList.hpp.
View newest version in sPHENIX GitHub at line 57 of file PhysicsList.hpp
References ActsFatras::PhysicsList< processes_t >::m_processes.
template<typename... processes_t> template<typename generator_t > bool ActsFatras::PhysicsList< processes_t >::impl (std::index_sequence<> , generator_t & , const Acts::MaterialSlab & , Particle & , std::vector< Particle > &) const inline private
Definition at line 91 of file PhysicsList.hpp.
View newest version in sPHENIX GitHub at line 91 of file PhysicsList.hpp
Referenced by ActsFatras::PhysicsList< processes_t >::impl(), and ActsFatras::PhysicsList< processes_t >::operator()().
template<typename... processes_t> template<std::size_t I0, std::size_t... INs, typename generator_t > bool ActsFatras::PhysicsList< processes_t >::impl (std::index_sequence< I0, INs...> , generator_t & generator, const Acts::MaterialSlab & slab, Particle & particle, std::vector< Particle > & generated) const inline private
Definition at line 96 of file PhysicsList.hpp.
View newest version in sPHENIX GitHub at line 96 of file PhysicsList.hpp
References ActsFatras::PhysicsList< processes_t >::impl(), ActsFatras::PhysicsList< processes_t >::m_mask, and ActsFatras::PhysicsList< processes_t >::m_processes.
template<typename... processes_t> template<typename generator_t > bool ActsFatras::PhysicsList< processes_t >::operator() (generator_t & generator, const Acts::MaterialSlab & slab, Particle & particle, std::vector< Particle > & generated) const inline
Run the physics list for a given material and particle.
Parameters
[in] generator is the random number generator
[in] slab is the passed material
[in,out] particle is the particle being updated
[out] generated is the container of generated particles
Returns
Break condition, i.e. whether a process stoped the propagation
Template Parameters
generator_t must be a RandomNumberEngine
Definition at line 38 of file PhysicsList.hpp.
View newest version in sPHENIX GitHub at line 38 of file PhysicsList.hpp
References ActsFatras::PhysicsList< processes_t >::impl().
Member Data Documentation
template<typename... processes_t> std::bitset<sizeof...(processes_t)> ActsFatras::PhysicsList< processes_t >::m_mask private
Definition at line 86 of file PhysicsList.hpp.
View newest version in sPHENIX GitHub at line 86 of file PhysicsList.hpp
Referenced by ActsFatras::PhysicsList< processes_t >::disable(), and ActsFatras::PhysicsList< processes_t >::impl().
template<typename... processes_t> std::tuple<processes_t...> ActsFatras::PhysicsList< processes_t >::m_processes private
Definition at line 87 of file PhysicsList.hpp.
View newest version in sPHENIX GitHub at line 87 of file PhysicsList.hpp
Referenced by ActsFatras::PhysicsList< processes_t >::get(), and ActsFatras::PhysicsList< processes_t >::impl().
The documentation for this class was generated from the following file:
acts/blob/sPHENIX/Fatras/include/ActsFatras/Kernel/PhysicsList.hpp