Analysis Software: InttCombinedRawDataConverter Class Reference
InttCombinedRawDataConverter Class Reference
#include <coresoftware/blob/master/offline/packages/intt/InttCombinedRawDataConverter.h>
Public Member Functions
InttCombinedRawDataConverter (std::string const &name="InttRawDataConverter")
int SetOutputFile (std::string const &)
int WriteOutputFile ()
int Init (PHCompositeNode *) override
int InitRun (PHCompositeNode *) override
int process_event (PHCompositeNode *) override
int End (PHCompositeNode *) override
Called at the end of all processing.
Public Member Functions inherited from SubsysReco
~SubsysReco () override
virtual int EndRun (const int)
Called at the end of each run.
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
void Print (const std::string &="ALL") const override
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Private Types
typedef std::map< std::string,
std::vector< Int_t > * > Branches_i_t
typedef std::map< std::string,
std::vector< Long64_t > * > Branches_l_t
typedef std::map< std::string,
std::vector< Double_t > * > Branches_d_t
Private Attributes
std::string m_InttRawNodeName = "INTTRAWHIT"
TFile * file = nullptr
TTree * tree = nullptr
Int_t n_evt = 0
Int_t num_hits = 0
Branches_i_t branches_i
Branches_l_t branches_l
Branches_d_t branches_d
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = std::numeric_limits<int>::max() - 10
}
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Detailed Description
Definition at line 17 of file InttCombinedRawDataConverter.h.
View newest version in sPHENIX GitHub at line 17 of file InttCombinedRawDataConverter.h
Member Typedef Documentation
typedef std::map<std::string, std::vector<Double_t>*> InttCombinedRawDataConverter::Branches_d_t private
Definition at line 41 of file InttCombinedRawDataConverter.h.
View newest version in sPHENIX GitHub at line 41 of file InttCombinedRawDataConverter.h
typedef std::map<std::string, std::vector<Int_t>*> InttCombinedRawDataConverter::Branches_i_t private
Definition at line 39 of file InttCombinedRawDataConverter.h.
View newest version in sPHENIX GitHub at line 39 of file InttCombinedRawDataConverter.h
typedef std::map<std::string, std::vector<Long64_t>*> InttCombinedRawDataConverter::Branches_l_t private
Definition at line 40 of file InttCombinedRawDataConverter.h.
View newest version in sPHENIX GitHub at line 40 of file InttCombinedRawDataConverter.h
Constructor & Destructor Documentation
InttCombinedRawDataConverter::InttCombinedRawDataConverter (std::string const & name = "InttRawDataConverter")
Definition at line 23 of file InttCombinedRawDataConverter.cc.
View newest version in sPHENIX GitHub at line 23 of file InttCombinedRawDataConverter.cc
Member Function Documentation
int InttCombinedRawDataConverter::End (PHCompositeNode *) override virtual
Called at the end of all processing.
Reimplemented from SubsysReco.
Definition at line 261 of file InttCombinedRawDataConverter.cc.
View newest version in sPHENIX GitHub at line 261 of file InttCombinedRawDataConverter.cc
References Fun4AllReturnCodes::EVENT_OK.
int InttCombinedRawDataConverter::Init (PHCompositeNode *) override virtual
Called during initialization. Typically this is where you can book histograms, and e.g. register them to Fun4AllServer (so they can be output to file using Fun4AllServer::dumpHistos() method).
Reimplemented from SubsysReco.
Definition at line 79 of file InttCombinedRawDataConverter.cc.
View newest version in sPHENIX GitHub at line 79 of file InttCombinedRawDataConverter.cc
References branches_d, branches_i, branches_l, file, n_evt, num_hits, tree, and Fun4AllBase::Verbosity().
int InttCombinedRawDataConverter::InitRun (PHCompositeNode *) override virtual
Called for first event when run number is known. Typically this is where you may want to fetch data from database, because you know the run number.
Reimplemented from SubsysReco.
Definition at line 143 of file InttCombinedRawDataConverter.cc.
View newest version in sPHENIX GitHub at line 143 of file InttCombinedRawDataConverter.cc
References branches_d, branches_i, Fun4AllReturnCodes::EVENT_OK, n_evt, and Fun4AllBase::Verbosity().
int InttCombinedRawDataConverter::process_event (PHCompositeNode *) override virtual
Called for each event. This is where you do the real work.
Reimplemented from SubsysReco.
Definition at line 171 of file InttCombinedRawDataConverter.cc.
View newest version in sPHENIX GitHub at line 171 of file InttCombinedRawDataConverter.cc
References InttNameSpace::Online_s::arm, branches_d, branches_i, InttNameSpace::Online_s::chn, InttNameSpace::Online_s::chp, Fun4AllReturnCodes::DISCARDEVENT, Fun4AllReturnCodes::EVENT_OK, InttNameSpace::RawData_s::felix_channel, InttNameSpace::RawData_s::felix_server, InttRawHit::get_adc(), InttRawHit::get_amplitude(), InttRawHit::get_bco(), InttRawHit::get_FPHX_BCO(), InttRawHitContainer::get_hit(), InttRawHitContainer::get_nhits(), i, if(), InttNameSpace::Online_s::ldr, InttNameSpace::Online_s::lyr, m_InttRawNodeName, n_evt, num_hits, PHWHERE, InttNameSpace::RawFromHit(), InttNameSpace::ToOnline(), tree, and Fun4AllBase::Verbosity().
int InttCombinedRawDataConverter::SetOutputFile (std::string const & filename)
Definition at line 29 of file InttCombinedRawDataConverter.cc.
View newest version in sPHENIX GitHub at line 29 of file InttCombinedRawDataConverter.cc
References file, and tree.
int InttCombinedRawDataConverter::WriteOutputFile ()
Definition at line 52 of file InttCombinedRawDataConverter.cc.
View newest version in sPHENIX GitHub at line 52 of file InttCombinedRawDataConverter.cc
References file, and tree.
Member Data Documentation
Branches_d_t InttCombinedRawDataConverter::branches_d private
Definition at line 44 of file InttCombinedRawDataConverter.h.
View newest version in sPHENIX GitHub at line 44 of file InttCombinedRawDataConverter.h
Referenced by Init(), InitRun(), and process_event().
Branches_i_t InttCombinedRawDataConverter::branches_i private
Definition at line 42 of file InttCombinedRawDataConverter.h.
View newest version in sPHENIX GitHub at line 42 of file InttCombinedRawDataConverter.h
Referenced by Init(), InitRun(), and process_event().
Branches_l_t InttCombinedRawDataConverter::branches_l private
Definition at line 43 of file InttCombinedRawDataConverter.h.
View newest version in sPHENIX GitHub at line 43 of file InttCombinedRawDataConverter.h
Referenced by Init().
TFile* InttCombinedRawDataConverter::file = nullptr private
Definition at line 33 of file InttCombinedRawDataConverter.h.
View newest version in sPHENIX GitHub at line 33 of file InttCombinedRawDataConverter.h
Referenced by conftest.RootHashAssertionError::__init__(), Init(), SetOutputFile(), and WriteOutputFile().
std::string InttCombinedRawDataConverter::m_InttRawNodeName = "INTTRAWHIT" private
Definition at line 31 of file InttCombinedRawDataConverter.h.
View newest version in sPHENIX GitHub at line 31 of file InttCombinedRawDataConverter.h
Referenced by process_event().
Int_t InttCombinedRawDataConverter::n_evt = 0 private
Definition at line 36 of file InttCombinedRawDataConverter.h.
View newest version in sPHENIX GitHub at line 36 of file InttCombinedRawDataConverter.h
Referenced by Init(), InitRun(), and process_event().
Int_t InttCombinedRawDataConverter::num_hits = 0 private
Definition at line 37 of file InttCombinedRawDataConverter.h.
View newest version in sPHENIX GitHub at line 37 of file InttCombinedRawDataConverter.h
Referenced by Init(), and process_event().
TTree* InttCombinedRawDataConverter::tree = nullptr private
Definition at line 34 of file InttCombinedRawDataConverter.h.
View newest version in sPHENIX GitHub at line 34 of file InttCombinedRawDataConverter.h
Referenced by Init(), process_event(), SetOutputFile(), and WriteOutputFile().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/intt/InttCombinedRawDataConverter.h
coresoftware/blob/master/offline/packages/intt/InttCombinedRawDataConverter.cc