Analysis Software: plotTracklet Namespace Reference
plotTracklet Namespace Reference
Variables
tuple parser OptionParser(usage="usage: %prog ver [options -n]")
histfname opt.histfname
plotdir opt.plotdir
isdata opt.isdata
tuple hM_NClusLayer1 GetHistogram(histfname, 'hM_NClusLayer1')
tuple hM_NPrototkl GetHistogram(histfname, 'hM_NPrototkl')
tuple hM_NRecotkl_Raw GetHistogram(histfname, 'hM_NRecotkl_Raw')
tuple hM_dEta_proto GetHistogram(histfname, 'hM_dEta_proto')
tuple hM_dPhi_proto GetHistogram(histfname, 'hM_dPhi_proto')
tuple hM_dPhi_proto_altrange GetHistogram(histfname, 'hM_dPhi_proto_altrange')
tuple hM_dR_proto GetHistogram(histfname, 'hM_dR_proto')
tuple hM_dR_proto_altrange GetHistogram(histfname, 'hM_dR_proto_altrange')
tuple hM_dR_proto_LogX GetHistogram(histfname, 'hM_dR_proto_LogX')
tuple hM_Eta_proto GetHistogram(histfname, 'hM_Eta_proto')
tuple hM_Phi_proto GetHistogram(histfname, 'hM_Phi_proto')
tuple hM_dEta_reco GetHistogram(histfname, 'hM_dEta_reco')
tuple hM_dEta_reco_altrange GetHistogram(histfname, 'hM_dEta_reco_altrange')
tuple hM_dPhi_reco GetHistogram(histfname, 'hM_dPhi_reco')
tuple hM_dPhi_reco_altrange GetHistogram(histfname, 'hM_dPhi_reco_altrange')
tuple hM_dR_reco GetHistogram(histfname, 'hM_dR_reco')
tuple hM_dR_reco_altrange GetHistogram(histfname, 'hM_dR_reco_altrange')
tuple hM_dR_reco_LogX GetHistogram(histfname, 'hM_dR_reco_LogX')
tuple hM_Eta_reco GetHistogram(histfname, 'hM_Eta_reco')
tuple hM_Phi_reco GetHistogram(histfname, 'hM_Phi_reco')
tuple hM_Eta_vtxZ_proto_incl GetHistogram(histfname, 'hM_Eta_vtxZ_proto_incl')
tuple hM_Eta_vtxZ_reco_incl GetHistogram(histfname, 'hM_Eta_vtxZ_reco_incl')
tuple hM_clusphi_clusphisize GetHistogram(histfname, 'hM_clusphi_clusphisize')
tuple hM_cluseta_clusphisize GetHistogram(histfname, 'hM_cluseta_clusphisize')
Variable Documentation
plotTracklet.histfname opt.histfname
Definition at line 25 of file plotTracklet.py.
View newest version in sPHENIX GitHub at line 25 of file plotTracklet.py
tuple plotTracklet.hM_cluseta_clusphisize GetHistogram(histfname, 'hM_cluseta_clusphisize')
Definition at line 60 of file plotTracklet.py.
View newest version in sPHENIX GitHub at line 60 of file plotTracklet.py
Referenced by makehist().
tuple plotTracklet.hM_clusphi_clusphisize GetHistogram(histfname, 'hM_clusphi_clusphisize')
Definition at line 59 of file plotTracklet.py.
View newest version in sPHENIX GitHub at line 59 of file plotTracklet.py
Referenced by makehist().
tuple plotTracklet.hM_dEta_proto GetHistogram(histfname, 'hM_dEta_proto')
Definition at line 37 of file plotTracklet.py.
View newest version in sPHENIX GitHub at line 37 of file plotTracklet.py
Referenced by makehist().
tuple plotTracklet.hM_dEta_reco GetHistogram(histfname, 'hM_dEta_reco')
Definition at line 46 of file plotTracklet.py.
View newest version in sPHENIX GitHub at line 46 of file plotTracklet.py
Referenced by makehist().
tuple plotTracklet.hM_dEta_reco_altrange GetHistogram(histfname, 'hM_dEta_reco_altrange')
Definition at line 47 of file plotTracklet.py.
View newest version in sPHENIX GitHub at line 47 of file plotTracklet.py
Referenced by makehist().
tuple plotTracklet.hM_dPhi_proto GetHistogram(histfname, 'hM_dPhi_proto')
Definition at line 38 of file plotTracklet.py.
View newest version in sPHENIX GitHub at line 38 of file plotTracklet.py
Referenced by makehist().
tuple plotTracklet.hM_dPhi_proto_altrange GetHistogram(histfname, 'hM_dPhi_proto_altrange')
Definition at line 39 of file plotTracklet.py.
View newest version in sPHENIX GitHub at line 39 of file plotTracklet.py
Referenced by makehist().
tuple plotTracklet.hM_dPhi_reco GetHistogram(histfname, 'hM_dPhi_reco')
Definition at line 48 of file plotTracklet.py.
View newest version in sPHENIX GitHub at line 48 of file plotTracklet.py
Referenced by makehist().
tuple plotTracklet.hM_dPhi_reco_altrange GetHistogram(histfname, 'hM_dPhi_reco_altrange')
Definition at line 49 of file plotTracklet.py.
View newest version in sPHENIX GitHub at line 49 of file plotTracklet.py
Referenced by makehist().
tuple plotTracklet.hM_dR_proto GetHistogram(histfname, 'hM_dR_proto')
Definition at line 40 of file plotTracklet.py.
View newest version in sPHENIX GitHub at line 40 of file plotTracklet.py
Referenced by makehist().
tuple plotTracklet.hM_dR_proto_altrange GetHistogram(histfname, 'hM_dR_proto_altrange')
Definition at line 41 of file plotTracklet.py.
View newest version in sPHENIX GitHub at line 41 of file plotTracklet.py
Referenced by makehist().
tuple plotTracklet.hM_dR_proto_LogX GetHistogram(histfname, 'hM_dR_proto_LogX')
Definition at line 42 of file plotTracklet.py.
View newest version in sPHENIX GitHub at line 42 of file plotTracklet.py
Referenced by makehist().
tuple plotTracklet.hM_dR_reco GetHistogram(histfname, 'hM_dR_reco')
Definition at line 50 of file plotTracklet.py.
View newest version in sPHENIX GitHub at line 50 of file plotTracklet.py
Referenced by makehist().
tuple plotTracklet.hM_dR_reco_altrange GetHistogram(histfname, 'hM_dR_reco_altrange')
Definition at line 51 of file plotTracklet.py.
View newest version in sPHENIX GitHub at line 51 of file plotTracklet.py
Referenced by makehist().
tuple plotTracklet.hM_dR_reco_LogX GetHistogram(histfname, 'hM_dR_reco_LogX')
Definition at line 52 of file plotTracklet.py.
View newest version in sPHENIX GitHub at line 52 of file plotTracklet.py
Referenced by makehist().
tuple plotTracklet.hM_Eta_proto GetHistogram(histfname, 'hM_Eta_proto')
Definition at line 43 of file plotTracklet.py.
View newest version in sPHENIX GitHub at line 43 of file plotTracklet.py
Referenced by makehist().
tuple plotTracklet.hM_Eta_reco GetHistogram(histfname, 'hM_Eta_reco')
Definition at line 53 of file plotTracklet.py.
View newest version in sPHENIX GitHub at line 53 of file plotTracklet.py
Referenced by makehist().
tuple plotTracklet.hM_Eta_vtxZ_proto_incl GetHistogram(histfname, 'hM_Eta_vtxZ_proto_incl')
Definition at line 56 of file plotTracklet.py.
View newest version in sPHENIX GitHub at line 56 of file plotTracklet.py
Referenced by makehist().
tuple plotTracklet.hM_Eta_vtxZ_reco_incl GetHistogram(histfname, 'hM_Eta_vtxZ_reco_incl')
Definition at line 57 of file plotTracklet.py.
View newest version in sPHENIX GitHub at line 57 of file plotTracklet.py
Referenced by makehist().
tuple plotTracklet.hM_NClusLayer1 GetHistogram(histfname, 'hM_NClusLayer1')
Definition at line 33 of file plotTracklet.py.
View newest version in sPHENIX GitHub at line 33 of file plotTracklet.py
tuple plotTracklet.hM_NPrototkl GetHistogram(histfname, 'hM_NPrototkl')
Definition at line 34 of file plotTracklet.py.
View newest version in sPHENIX GitHub at line 34 of file plotTracklet.py
Referenced by makehist().
tuple plotTracklet.hM_NRecotkl_Raw GetHistogram(histfname, 'hM_NRecotkl_Raw')
Definition at line 35 of file plotTracklet.py.
View newest version in sPHENIX GitHub at line 35 of file plotTracklet.py
Referenced by makehist().
tuple plotTracklet.hM_Phi_proto GetHistogram(histfname, 'hM_Phi_proto')
Definition at line 44 of file plotTracklet.py.
View newest version in sPHENIX GitHub at line 44 of file plotTracklet.py
Referenced by makehist().
tuple plotTracklet.hM_Phi_reco GetHistogram(histfname, 'hM_Phi_reco')
Definition at line 54 of file plotTracklet.py.
View newest version in sPHENIX GitHub at line 54 of file plotTracklet.py
Referenced by makehist().
plotTracklet.isdata opt.isdata
Definition at line 27 of file plotTracklet.py.
View newest version in sPHENIX GitHub at line 27 of file plotTracklet.py
tuple plotTracklet.parser OptionParser(usage="usage: %prog ver [options -n]")
Definition at line 18 of file plotTracklet.py.
View newest version in sPHENIX GitHub at line 18 of file plotTracklet.py
plotTracklet.plotdir opt.plotdir
Definition at line 26 of file plotTracklet.py.
View newest version in sPHENIX GitHub at line 26 of file plotTracklet.py