Analysis Software: TpcSpaceChargeMatrixInversion Class Reference
TpcSpaceChargeMatrixInversion Class Reference
performs space charge distortion reconstruction using tracks
#include <coresoftware/blob/master/offline/packages/tpccalib/TpcSpaceChargeMatrixInversion.h>
Public Member Functions
TpcSpaceChargeMatrixInversion (const std::string &="TPCSPACECHARGEMATRIXINVERSION")
constructor
modifiers
void set_use_micromegas (bool value)
set whether to use only tracks with micromegas or not
void set_outputfile (const std::string &filename)
output file
bool add (const TpcSpaceChargeMatrixContainer &)
add space charge correction matrix to current. Returns true on success
bool add_from_file (const std::string &filename, const std::string &objectname="TpcSpaceChargeMatrixContainer")
add space charge correction matrix, loaded from file, to current. Returns true on success
void calculate_distortions ()
calculate distortions by inverting stored matrices, and save relevant histograms
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Print (const std::string &what="ALL") const
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Private Attributes
std::string m_outputfile = "DistortionCorrections.root"
output file
bool m_use_micromegas = true
true if only tracks with micromegas must be used
std::unique_ptr
< TpcSpaceChargeMatrixContainer > m_matrix_container
matrix container
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = std::numeric_limits<int>::max() - 10
}
Protected Member Functions inherited from Fun4AllBase
Fun4AllBase (const std::string &name="NONAME")
Detailed Description
performs space charge distortion reconstruction using tracks
Definition at line 20 of file TpcSpaceChargeMatrixInversion.h.
View newest version in sPHENIX GitHub at line 20 of file TpcSpaceChargeMatrixInversion.h
Constructor & Destructor Documentation
TpcSpaceChargeMatrixInversion::TpcSpaceChargeMatrixInversion (const std::string & name = "TPCSPACECHARGEMATRIXINVERSION")
constructor
Definition at line 38 of file TpcSpaceChargeMatrixInversion.cc.
View newest version in sPHENIX GitHub at line 38 of file TpcSpaceChargeMatrixInversion.cc
Member Function Documentation
bool TpcSpaceChargeMatrixInversion::add (const TpcSpaceChargeMatrixContainer & source)
add space charge correction matrix to current. Returns true on success
Definition at line 74 of file TpcSpaceChargeMatrixInversion.cc.
View newest version in sPHENIX GitHub at line 74 of file TpcSpaceChargeMatrixInversion.cc
References TpcSpaceChargeMatrixContainer::get_grid_dimensions(), m_matrix_container, and MATSCAN::phibins.
Referenced by add_from_file().
bool TpcSpaceChargeMatrixInversion::add_from_file (const std::string & filename, const std::string & objectname = "TpcSpaceChargeMatrixContainer")
add space charge correction matrix, loaded from file, to current. Returns true on success
Definition at line 47 of file TpcSpaceChargeMatrixInversion.cc.
View newest version in sPHENIX GitHub at line 47 of file TpcSpaceChargeMatrixInversion.cc
References add(), filename, centProxy::inputfile, FROG::location(), and parse_cmake_options::source.
void TpcSpaceChargeMatrixInversion::calculate_distortions ()
calculate distortions by inverting stored matrices, and save relevant histograms
Definition at line 96 of file TpcSpaceChargeMatrixInversion.cc.
View newest version in sPHENIX GitHub at line 96 of file TpcSpaceChargeMatrixInversion.cc
References TpcSpaceChargeReconstructionHelper::copy_histogram(), Acts::Test::cov, TpcSpaceChargeReconstructionHelper::extrapolate_phi1(), TpcSpaceChargeReconstructionHelper::extrapolate_phi2(), TpcSpaceChargeReconstructionHelper::extrapolate_z(), h, Acts::Test::hz, i, j, check_smearing_config::lhs, m_matrix_container, m_outputfile, m_use_micromegas, perf_headwind::name, MATSCAN::phibins, check_smearing_config::rhs, TpcSpaceChargeReconstructionHelper::split(), and Fun4AllBase::Verbosity().
void TpcSpaceChargeMatrixInversion::set_outputfile (const std::string & filename)
output file
this is the file where space charge correction 3D histograms are stored they are suitable for being read by TpcClusterizer
Definition at line 43 of file TpcSpaceChargeMatrixInversion.cc.
View newest version in sPHENIX GitHub at line 43 of file TpcSpaceChargeMatrixInversion.cc
References filename, and m_outputfile.
void TpcSpaceChargeMatrixInversion::set_use_micromegas (bool value) inline
set whether to use only tracks with micromegas or not
Definition at line 31 of file TpcSpaceChargeMatrixInversion.h.
View newest version in sPHENIX GitHub at line 31 of file TpcSpaceChargeMatrixInversion.h
References m_use_micromegas, and value.
Member Data Documentation
std::unique_ptr<TpcSpaceChargeMatrixContainer> TpcSpaceChargeMatrixInversion::m_matrix_container private
matrix container
Definition at line 61 of file TpcSpaceChargeMatrixInversion.h.
View newest version in sPHENIX GitHub at line 61 of file TpcSpaceChargeMatrixInversion.h
Referenced by add(), and calculate_distortions().
std::string TpcSpaceChargeMatrixInversion::m_outputfile = "DistortionCorrections.root" private
output file
Definition at line 55 of file TpcSpaceChargeMatrixInversion.h.
View newest version in sPHENIX GitHub at line 55 of file TpcSpaceChargeMatrixInversion.h
Referenced by calculate_distortions(), and set_outputfile().
bool TpcSpaceChargeMatrixInversion::m_use_micromegas = true private
true if only tracks with micromegas must be used
Definition at line 58 of file TpcSpaceChargeMatrixInversion.h.
View newest version in sPHENIX GitHub at line 58 of file TpcSpaceChargeMatrixInversion.h
Referenced by calculate_distortions(), and set_use_micromegas().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/tpccalib/TpcSpaceChargeMatrixInversion.h
coresoftware/blob/master/offline/packages/tpccalib/TpcSpaceChargeMatrixInversion.cc