Analysis Software: macros/blob/master/common/G4_HcalIn_ref.C File Reference
G4_HcalIn_ref.C File Reference
#include <GlobalVariables.C>
#include <QA.C>
#include <g4calo/HcalRawTowerBuilder.h>
#include <g4calo/RawTowerDigitizer.h>
#include <g4ihcal/PHG4IHCalSubsystem.h>
#include <g4detectors/PHG4CylinderSubsystem.h>
#include <g4detectors/PHG4HcalCellReco.h>
#include <g4detectors/PHG4InnerHcalSubsystem.h>
#include <g4eval/CaloEvaluator.h>
#include <g4main/PHG4Reco.h>
#include <caloreco/RawClusterBuilderGraph.h>
#include <caloreco/RawClusterBuilderTemplate.h>
#include <caloreco/RawTowerCalibration.h>
#include <qa_modules/QAG4SimulationCalorimeter.h>
#include <fun4all/Fun4AllServer.h>
Namespaces
namespace Enable
namespace G4HCALIN
Macros
#define MACRO_G4HCALINREF_C
Enumerations
enum G4HCALIN::enu_HCalIn_clusterizer { G4HCALIN::kHCalInGraphClusterizer, G4HCALIN::kHCalInTemplateClusterizer, G4HCALIN::kHCalInGraphClusterizer, G4HCALIN::kHCalInTemplateClusterizer }
Functions
void HCalInnerInit (const int iflag=0)
double HCalInner (PHG4Reco *g4Reco, double radius, const int crossings)
void HCALInner_Cells ()
void HCALInner_Towers ()
void HCALInner_Clusters ()
void HCALInner_Eval (const std::string &outputfile, int start_event=0)
void HCALInner_QA ()
Variables
bool Enable::HCALIN_OLD = false
bool Enable::HCALIN_G4Hit = true
double G4HCALIN::inch = 2.54
double G4HCALIN::support_ring_z = 175.375 * inch / 2
double G4HCALIN::phistart = NAN
double G4HCALIN::tower_emin = NAN
int G4HCALIN::light_scint_model = -1
int G4HCALIN::tower_energy_source = -1
Macro Definition Documentation
#define MACRO_G4HCALINREF_C
Definition at line 3 of file G4_HcalIn_ref.C.
View newest version in sPHENIX GitHub at line 3 of file G4_HcalIn_ref.C
Function Documentation
double HCalInner (PHG4Reco * g4Reco, double radius, const int crossings)
Definition at line 105 of file G4_HcalIn_ref.C.
View newest version in sPHENIX GitHub at line 105 of file G4_HcalIn_ref.C
References Enable::ABSORBER, PHG4DetectorSubsystem::get_double_param(), Enable::HCALIN_ABSORBER, Enable::HCALIN_G4Hit, Enable::HCALIN_OLD, Enable::HCALIN_OVERLAPCHECK, Enable::HCALIN_VERBOSITY, G4HCALIN::inner_hcal_material_Al, G4HCALIN::light_scint_model, no_overlapp, PHG4DetectorSubsystem::OverlapCheck(), Enable::OVERLAPCHECK, G4HCALIN::phistart, PHG4Reco::registerSubsystem(), PHG4DetectorSubsystem::set_double_param(), PHG4DetectorSubsystem::set_int_param(), PHG4DetectorSubsystem::set_string_param(), PHG4DetectorSubsystem::SetAbsorberActive(), PHG4DetectorSubsystem::SetActive(), PHG4DetectorSubsystem::SuperDetector(), verbosity, and Enable::VERBOSITY.
void HCALInner_Cells ()
Definition at line 222 of file G4_HcalIn_ref.C.
View newest version in sPHENIX GitHub at line 222 of file G4_HcalIn_ref.C
References PHG4HcalCellReco::Detector(), Enable::HCALIN_G4Hit, Enable::HCALIN_VERBOSITY, Fun4AllServer::instance(), Fun4AllServer::registerSubsystem(), verbosity, Enable::VERBOSITY, and Fun4AllBase::Verbosity().
void HCALInner_Clusters ()
Definition at line 325 of file G4_HcalIn_ref.C.
View newest version in sPHENIX GitHub at line 325 of file G4_HcalIn_ref.C
References RawClusterBuilderGraph::Detector(), RawClusterBuilderTemplate::Detector(), G4HCALIN::HCalIn_clusterizer, Enable::HCALIN_G4Hit, Enable::HCALIN_VERBOSITY, Fun4AllServer::instance(), G4HCALIN::kHCalInGraphClusterizer, G4HCALIN::kHCalInTemplateClusterizer, Fun4AllServer::registerSubsystem(), RawClusterBuilderTemplate::set_UseTowerInfo(), RawClusterBuilderTemplate::SetCylindricalGeometry(), verbosity, Enable::VERBOSITY, and Fun4AllBase::Verbosity().
void HCALInner_Eval (const std::string & outputfile, int start_event = 0)
Definition at line 356 of file G4_HcalIn_ref.C.
View newest version in sPHENIX GitHub at line 356 of file G4_HcalIn_ref.C
References Enable::HCALIN_VERBOSITY, Fun4AllServer::instance(), Fun4AllServer::registerSubsystem(), CaloEvaluator::set_event(), verbosity, Enable::VERBOSITY, and Fun4AllBase::Verbosity().
void HCALInner_QA ()
Definition at line 369 of file G4_HcalIn_ref.C.
View newest version in sPHENIX GitHub at line 369 of file G4_HcalIn_ref.C
References Enable::HCALIN_VERBOSITY, Fun4AllServer::instance(), Enable::QA_VERBOSITY, Fun4AllServer::registerSubsystem(), verbosity, and Fun4AllBase::Verbosity().
void HCALInner_Towers ()
Definition at line 247 of file G4_HcalIn_ref.C.
View newest version in sPHENIX GitHub at line 247 of file G4_HcalIn_ref.C
References HcalRawTowerBuilder::Detector(), RawTowerCalibration::Detector(), RawTowerDigitizer::Detector(), Acts::UnitConstants::e, Enable::HCALIN_G4Hit, Enable::HCALIN_OLD, Enable::HCALIN_VERBOSITY, G4HCALIN::inner_hcal_material_Al, Fun4AllServer::instance(), RawTowerDigitizer::kNo_digitization, RawTowerCalibration::kSimple_linear_calibration, G4HCALIN::phistart, Fun4AllServer::registerSubsystem(), RawTowerCalibration::set_calib_algorithm(), RawTowerCalibration::set_calib_const_GeV_ADC(), RawTowerDigitizer::set_digi_algorithm(), PHParameterInterface::set_double_param(), PHParameterInterface::set_int_param(), RawTowerCalibration::set_pedstal_ADC(), RawTowerDigitizer::set_pedstal_central_ADC(), RawTowerDigitizer::set_pedstal_width_ADC(), RawTowerDigitizer::set_photonelec_ADC(), RawTowerDigitizer::set_photonelec_yield_visible_GeV(), HcalRawTowerBuilder::set_sim_tower_node_prefix(), RawTowerCalibration::set_towerinfo(), RawTowerDigitizer::set_towerinfo(), RawTowerDigitizer::set_zero_suppression_ADC(), G4HCALIN::tower_emin, G4HCALIN::tower_energy_source, G4HCALIN::TowerDigi, verbosity, Enable::VERBOSITY, and Fun4AllBase::Verbosity().
void HCalInnerInit (const int iflag = 0)
Definition at line 94 of file G4_HcalIn_ref.C.
View newest version in sPHENIX GitHub at line 94 of file G4_HcalIn_ref.C
References G4HCALIN::dz, G4HCALIN::inner_hcal_eic, BlackHoleGeometry::max_radius, BlackHoleGeometry::max_z, Acts::UnitConstants::min, BlackHoleGeometry::min_z, G4HCALIN::support_ring_outer_radius, and G4HCALIN::support_ring_z.