Analysis Software: odbc::ResultSet Class Reference
odbc::ResultSet Class Reference
#include <RDBC/blob/master/include/RDBC/odbc++/resultset.h>
Public Types
enum { CONCUR_READ_ONLY, CONCUR_UPDATABLE }
enum { TYPE_FORWARD_ONLY, TYPE_SCROLL_INSENSITIVE, TYPE_SCROLL_SENSITIVE }
Public Member Functions
virtual ~ResultSet ()
bool absolute (int row)
bool relative (int rows)
void afterLast ()
void beforeFirst ()
bool isAfterLast ()
bool isBeforeFirst ()
bool isFirst ()
bool isLast ()
int getRow ()
bool next ()
bool previous ()
bool first ()
bool last ()
void moveToInsertRow ()
void moveToCurrentRow ()
void refreshRow ()
void deleteRow ()
void insertRow ()
void updateRow ()
void cancelRowUpdates ()
ResultSetMetaData * getMetaData ()
int findColumn (const ODBCXX_STRING &colName)
bool rowDeleted ()
bool rowInserted ()
bool rowUpdated ()
int getType ()
int getConcurrency ()
int getFetchSize ()
void setFetchSize (int fetchSize)
ODBCXX_STRING getCursorName ()
Statement * getStatement ()
double getDouble (int idx)
bool getBoolean (int idx)
signed char getByte (int idx)
ODBCXX_BYTES getBytes (int idx)
Date getDate (int idx)
float getFloat (int idx)
int getInt (int idx)
Long getLong (int idx)
short getShort (int idx)
ODBCXX_STRING getString (int idx)
Time getTime (int idx)
Timestamp getTimestamp (int idx)
double getDouble (const ODBCXX_STRING &colName)
bool getBoolean (const ODBCXX_STRING &colName)
signed char getByte (const ODBCXX_STRING &colName)
ODBCXX_BYTES getBytes (const ODBCXX_STRING &colName)
Date getDate (const ODBCXX_STRING &colName)
float getFloat (const ODBCXX_STRING &colName)
int getInt (const ODBCXX_STRING &colName)
Long getLong (const ODBCXX_STRING &colName)
short getShort (const ODBCXX_STRING &colName)
ODBCXX_STRING getString (const ODBCXX_STRING &colName)
Time getTime (const ODBCXX_STRING &colName)
Timestamp getTimestamp (const ODBCXX_STRING &colName)
ODBCXX_STREAM * getAsciiStream (int idx)
ODBCXX_STREAM * getAsciiStream (const ODBCXX_STRING &colName)
ODBCXX_STREAM * getBinaryStream (int idx)
ODBCXX_STREAM * getBinaryStream (const ODBCXX_STRING &colName)
bool wasNull ()
void updateDouble (int idx, double val)
void updateBoolean (int idx, bool val)
void updateByte (int idx, signed char val)
void updateBytes (int idx, const ODBCXX_BYTES &val)
void updateDate (int idx, const Date &val)
void updateFloat (int idx, float val)
void updateInt (int idx, int val)
void updateLong (int idx, Long val)
void updateShort (int idx, short val)
void updateString (int idx, const ODBCXX_STRING &val)
void updateTime (int idx, const Time &val)
void updateTimestamp (int idx, const Timestamp &val)
void updateNull (int idx)
void updateDouble (const ODBCXX_STRING &colName, double val)
void updateBoolean (const ODBCXX_STRING &colName, bool val)
void updateByte (const ODBCXX_STRING &colName, signed char val)
void updateBytes (const ODBCXX_STRING &colName, const ODBCXX_BYTES &val)
void updateDate (const ODBCXX_STRING &colName, const Date &val)
void updateFloat (const ODBCXX_STRING &colName, float val)
void updateInt (const ODBCXX_STRING &colName, int val)
void updateLong (const ODBCXX_STRING &colName, Long val)
void updateShort (const ODBCXX_STRING &colName, short val)
void updateString (const ODBCXX_STRING &colName, const ODBCXX_STRING &val)
void updateTime (const ODBCXX_STRING &colName, const Time &val)
void updateTimestamp (const ODBCXX_STRING &colName, const Timestamp &val)
void updateAsciiStream (int idx, ODBCXX_STREAM *s, int len)
void updateAsciiStream (const ODBCXX_STRING &colName, ODBCXX_STREAM *s, int len)
void updateBinaryStream (int idx, ODBCXX_STREAM *s, int len)
void updateBinaryStream (const ODBCXX_STRING &colName, ODBCXX_STREAM *s, int len)
void updateNull (const ODBCXX_STRING &colName)
Public Member Functions inherited from odbc::ErrorHandler
void clearWarnings ()
WarningList * getWarnings ()
virtual ~ErrorHandler ()
Private Member Functions
ResultSet (Statement *stmt, SQLHSTMT hstmt, bool ownStmt)
const DriverInfo * _getDriverInfo () const
void _applyFetchSize ()
void _resetRowset ()
void _prepareForFetch ()
void _doFetch (int fetchType, int rowNum)
SQLRETURN _applyPosition (int mode=SQL_POSITION)
void _bindCols ()
void _unbindCols ()
void _bindStreamedCols ()
void _unbindStreamedCols ()
void _handleStreams (SQLRETURN r)
Private Attributes
Statement * statement_
SQLHSTMT hstmt_
bool ownStatement_
int currentFetchSize_
int newFetchSize_
Rowset * rowset_
SQLUSMALLINT * rowStatus_
SQLUINTEGER rowsInRowset_
bool colsBound_
bool streamedColsBound_
unsigned int bindPos_
ResultSetMetaData * metaData_
int location_
bool lastWasNull_
int rowBeforeInsert_
int locBeforeInsert_
Friends
class Statement
class ResultSetMetaData
Additional Inherited Members
Protected Member Functions inherited from odbc::ErrorHandler
void _postWarning (SQLWarning *w)
void _checkErrorODBC2 (SQLHENV henv, SQLHDBC hdbc, SQLHSTMT hstmt, SQLRETURN r, const ODBCXX_STRING &what)
void _checkStmtError (SQLHSTMT hstmt, SQLRETURN r, const char *what="")
void _checkConError (SQLHDBC hdbc, SQLRETURN r, const char *what="")
void _checkEnvError (SQLHENV henv, SQLRETURN r, const char *what="")
ErrorHandler (bool collectWarnings=true)
Detailed Description
A result set
Definition at line 38 of file resultset.h.
View newest version in sPHENIX GitHub at line 38 of file resultset.h
Member Enumeration Documentation
anonymous enum
ResultSet concurrency constants.
Enumerator:
CONCUR_READ_ONLY
The ResultSet is read only
CONCUR_UPDATABLE
The ResultSet is updatable
Definition at line 113 of file resultset.h.
View newest version in sPHENIX GitHub at line 113 of file resultset.h
anonymous enum
ResultSet type constants
Enumerator:
TYPE_FORWARD_ONLY
The result set only goes forward.
TYPE_SCROLL_INSENSITIVE
The result set is scrollable, but the data in it is not affected by changes in the database.
TYPE_SCROLL_SENSITIVE
The result set is scrollable and sensitive to database changes
Definition at line 123 of file resultset.h.
View newest version in sPHENIX GitHub at line 123 of file resultset.h
Constructor & Destructor Documentation
odbc::ResultSet::ResultSet (Statement * stmt, SQLHSTMT hstmt, bool ownStmt) private
virtual odbc::ResultSet::~ResultSet () virtual
Destructor
Member Function Documentation
void odbc::ResultSet::_applyFetchSize () private
SQLRETURN odbc::ResultSet::_applyPosition (int mode = SQL_POSITION) private
void odbc::ResultSet::_bindCols () private
void odbc::ResultSet::_bindStreamedCols () private
void odbc::ResultSet::_doFetch (int fetchType, int rowNum) private
const DriverInfo* odbc::ResultSet::_getDriverInfo () const inline private
Definition at line 75 of file resultset.h.
View newest version in sPHENIX GitHub at line 75 of file resultset.h
void odbc::ResultSet::_handleStreams (SQLRETURN r) private
void odbc::ResultSet::_prepareForFetch () private
void odbc::ResultSet::_resetRowset () private
void odbc::ResultSet::_unbindCols () private
void odbc::ResultSet::_unbindStreamedCols () private
bool odbc::ResultSet::absolute (int row)
Moves the cursor to a specific row in this result set. If row is negative, the actual row number is calculated from the end of the result set. Calling absolute(0) is equivalent to calling beforeFirst()
Returns
true if the cursor is in the result set
Referenced by ODBCResultSet::Absolute().
void odbc::ResultSet::afterLast ()
Places the cursor after the last row in the result set
Referenced by ODBCResultSet::AfterLast().
void odbc::ResultSet::beforeFirst ()
Places the cursor before the first row in the result set
Referenced by ODBCResultSet::BeforeFirst().
void odbc::ResultSet::cancelRowUpdates ()
Cancels any updates done to the current row
Referenced by ODBCResultSet::CancelRowUpdates().
void odbc::ResultSet::deleteRow ()
Deletes the current row
Referenced by ODBCResultSet::DeleteRow().
int odbc::ResultSet::findColumn (const ODBCXX_STRING & colName)
Find a column index by the column's name
Referenced by OnCalServer::check_create_subsystable(), OnlMonStatusDB::CheckAndCreateMonitor(), and ODBCResultSet::FindColumn().
bool odbc::ResultSet::first ()
Moves to the first row in the result set
Returns
true if the cursor is in the result set
Referenced by OnCalServer::check_create_subsystable(), OnlMonDBodbc::Dump(), and ODBCResultSet::First().
ODBCXX_STREAM* odbc::ResultSet::getAsciiStream (int idx)
Fetches a column's value as a stream. Note that the stream is owned by the result set and should in no case be deleted by the caller. Also, the returned stream is only valid while the cursor remains on this position.
Parameters
idx The column index, starting at 1
Referenced by ODBCResultSet::GetAsciiStream().
ODBCXX_STREAM* odbc::ResultSet::getAsciiStream (const ODBCXX_STRING & colName)
Fetches a column's value as a stream. Note that the stream is owned by the result set and should in no case be deleted by the caller. Also, the returned stream is only valid while the cursor remains on this position.
Parameters
colName The column name
ODBCXX_STREAM* odbc::ResultSet::getBinaryStream (int idx)
Fetches a column's value as a stream. Note that the stream is owned by the result set and should in no case be deleted by the caller. Also, the returned stream is only valid while the cursor remains on this position.
Parameters
idx The column index, starting at 1
Referenced by ODBCResultSet::GetBinaryStream().
ODBCXX_STREAM* odbc::ResultSet::getBinaryStream (const ODBCXX_STRING & colName)
Fetches a column's value as a stream. Note that the stream is owned by the result set and should in no case be deleted by the caller. Also, the returned stream is only valid while the cursor remains on this position.
Parameters
colName The column name
bool odbc::ResultSet::getBoolean (int idx)
Gets a column's value as a bool
Parameters
idx The column index, starting at 1
Referenced by ODBCResultSet::GetBoolean().
bool odbc::ResultSet::getBoolean (const ODBCXX_STRING & colName)
Gets a column's value as a bool
Parameters
colName The name of the column
signed char odbc::ResultSet::getByte (int idx)
Gets a column's value as a signed char
Parameters
idx The column index, starting at 1
Referenced by ODBCResultSet::GetByte().
signed char odbc::ResultSet::getByte (const ODBCXX_STRING & colName)
Gets a column's value as a signed char
Parameters
colName The name of the column
ODBCXX_BYTES odbc::ResultSet::getBytes (int idx)
Gets a column's value as a chunk of bytes.
Parameters
idx The column index, starting at 1
Referenced by ODBCResultSet::GetBytes().
ODBCXX_BYTES odbc::ResultSet::getBytes (const ODBCXX_STRING & colName)
Gets a column's value as a chunk of bytes.
Parameters
colName The name of the column
int odbc::ResultSet::getConcurrency ()
Gets the concurrency of this result set
Referenced by ODBCResultSet::GetConcurrency().
ODBCXX_STRING odbc::ResultSet::getCursorName ()
Gets the cursor name associated with this result set
Referenced by ODBCResultSet::GetCursorName().
Date odbc::ResultSet::getDate (int idx)
Gets a column's value as a Date
Parameters
idx The column index, starting at 1
Referenced by ODBCResultSet::GetDate().
Date odbc::ResultSet::getDate (const ODBCXX_STRING & colName)
Gets a column's value as a Date
Parameters
colName The name of the column
double odbc::ResultSet::getDouble (int idx)
Gets a column's value as a double
Parameters
idx The column index, starting at 1
Referenced by ODBCResultSet::GetDouble().
double odbc::ResultSet::getDouble (const ODBCXX_STRING & colName)
Gets a column's value as a double
Parameters
colName The name of the column
int odbc::ResultSet::getFetchSize () inline
Gets this result set's current fetch size
Definition at line 251 of file resultset.h.
View newest version in sPHENIX GitHub at line 251 of file resultset.h
Referenced by ODBCResultSet::GetFetchSize().
float odbc::ResultSet::getFloat (int idx)
Gets a column's value as a float
Parameters
idx The column index, starting at 1
Referenced by OnlMonDBodbc::AddRow(), OnlMonDBodbc::Dump(), ODBCResultSet::GetFloat(), PktSizeDBodbc::GetPacketContent(), OnlMonDBodbc::GetVar(), and OnlMonDBodbc::Info().
float odbc::ResultSet::getFloat (const ODBCXX_STRING & colName)
Gets a column's value as a float
Parameters
colName The name of the column
int odbc::ResultSet::getInt (int idx)
Gets a column's value as an int
Parameters
idx The column index, starting at 1
Referenced by PktSizeDBodbc::AddRow(), OnlMonDBodbc::AddRow(), OnlMonServer::CacheRunDB(), OnCalServer::ClosestGoodRun(), OnlMonDBodbc::Dump(), OnCalServer::FindClosestCalibratedRun(), OnlMonStatusDB::findRunNumInDB(), OnCalServer::findRunNumInDB(), OnCalServer::GetCalibStatus(), ODBCResultSet::GetInt(), OnCalDBodbc::GetLastCalibratedRun(), OnCalServer::GetLastGoodRunTS(), RunToTimePg::getRunNumber(), RunDBodbc::GetRunNumbers(), RunToTimePg::getTime(), OnlMonDBodbc::GetVar(), OnlMonDBodbc::Info(), RunDBodbc::RunType(), OnCalServer::SyncCalibTimeStampsToOnCal(), and OnCalServer::SyncOncalTimeStampsToRunDB().
int odbc::ResultSet::getInt (const ODBCXX_STRING & colName)
Gets a column's value as an int
Parameters
colName The name of the column
Long odbc::ResultSet::getLong (int idx)
Gets a column's value as a Long
Parameters
idx The column index, starting at 1
Referenced by OnCalServer::ClosestGoodRun(), OnCalServer::FindClosestCalibratedRun(), ODBCResultSet::GetLong(), RunDBodbc::RunType(), OnCalServer::SyncCalibTimeStampsToOnCal(), and OnCalServer::SyncOncalTimeStampsToRunDB().
Long odbc::ResultSet::getLong (const ODBCXX_STRING & colName)
Gets a column's value as a Long
Parameters
colName The name of the column
ResultSetMetaData* odbc::ResultSet::getMetaData () inline
Returns meta data about this result set
See Also
ResultSetMetaData
Definition at line 227 of file resultset.h.
View newest version in sPHENIX GitHub at line 227 of file resultset.h
Referenced by OnCalServer::check_calibrator_in_statustable(), PktSizeDBodbc::CheckAndAddColumns(), OnlMonDBodbc::CheckAndCreateTable(), OnlMonDBodbc::Dump(), PktSizeDBodbc::GetPacketContent(), OnlMonDBodbc::Info(), and ODBCResultSet::ODBCResultSet().
int odbc::ResultSet::getRow ()
Returns the current row number.
Returns
The current row number in the result set, or 0 if it can't be determined.
Referenced by ODBCResultSet::GetRow(), and OnlMonDBodbc::Info().
short odbc::ResultSet::getShort (int idx)
Gets a column's value as a short
Parameters
idx The column index, starting at 1
Referenced by ODBCResultSet::GetShort().
short odbc::ResultSet::getShort (const ODBCXX_STRING & colName)
Gets a column's value as a short
Parameters
colName The name of the column
Statement* odbc::ResultSet::getStatement () inline
Gets the Statement that created this result set
Definition at line 262 of file resultset.h.
View newest version in sPHENIX GitHub at line 262 of file resultset.h
ODBCXX_STRING odbc::ResultSet::getString (int idx)
Gets a column's value as a string
Parameters
idx The column index, starting at 1
Referenced by OnlMonClient::CacheRunDB(), OnlMonServer::CacheRunDB(), FROG::dCacheSearch(), ODBCResultSet::GetString(), OnlMonDBodbc::Info(), FROG::LustreSearch(), FROG::MinIOSearch(), FROG::PGSearch(), RunDBodbc::RunType(), OnCalServer::updateDB(), and FROG::XRootDSearch().
ODBCXX_STRING odbc::ResultSet::getString (const ODBCXX_STRING & colName)
Gets a column's value as a string
Parameters
colName The name of the column
Time odbc::ResultSet::getTime (int idx)
Gets a column's value as a Time
Parameters
idx The column index, starting at 1
Referenced by ODBCResultSet::GetTime().
Time odbc::ResultSet::getTime (const ODBCXX_STRING & colName)
Gets a column's value as a Time
Parameters
colName The name of the column
Timestamp odbc::ResultSet::getTimestamp (int idx)
Gets a column's value as a Timestamp
Parameters
idx The column index, starting at 1
Referenced by OnlMonDBodbc::AddRow(), OnlMonDBodbc::Dump(), ODBCResultSet::GetTimestamp(), and OnlMonDBodbc::GetVar().
Timestamp odbc::ResultSet::getTimestamp (const ODBCXX_STRING & colName)
Gets a column's value as a Timestamp
Parameters
colName The name of the column
int odbc::ResultSet::getType ()
Gets the type of this result set
Referenced by ODBCResultSet::GetType().
void odbc::ResultSet::insertRow ()
Inserts the current row. Only valid while on the insert row.
See Also
moveToInsertRow()
Referenced by ODBCResultSet::InsertRow().
bool odbc::ResultSet::isAfterLast ()
Checks if the cursor is after the last row in the result set
Referenced by ODBCResultSet::IsAfterLast().
bool odbc::ResultSet::isBeforeFirst ()
Checks if the cursor is before the first row in the result set
Referenced by ODBCResultSet::IsBeforeFirst().
bool odbc::ResultSet::isFirst ()
Checks if the cursor is on the first row in the result set
Referenced by ODBCResultSet::IsFirst().
bool odbc::ResultSet::isLast ()
Checks if the cursor is on the last row in the result set.
Referenced by ODBCResultSet::IsLast().
bool odbc::ResultSet::last ()
Moves to the last row in the result set
Returns
true if the cursor is in the result set
Referenced by ODBCResultSet::Last().
void odbc::ResultSet::moveToCurrentRow ()
Moves the cursor back to where it was before it was moved to the insert row
Referenced by ODBCResultSet::MoveToCurrentRow().
void odbc::ResultSet::moveToInsertRow ()
Moves the cursor to the 'insert row' of this result set.
Warning
The only valid methods while on the insert row are updateXXX(), insertRow() and moveToCurrentRow().
See Also
moveToCurrentRow()
Referenced by ODBCResultSet::MoveToInsertRow().
bool odbc::ResultSet::next ()
Moves to the next row in the result set
Returns
true if the cursor is in the result set
Referenced by PktSizeDBodbc::AddRow(), OnlMonDBodbc::AddRow(), OnlMonClient::CacheRunDB(), OnlMonServer::CacheRunDB(), OnlMonStatusDB::CheckAndCreateTable(), PktSizeDBodbc::CheckAndCreateTable(), OnCalServer::ClosestGoodRun(), OnCalServer::CreateCalibration(), OnlMonDBodbc::CreateTable(), FROG::dCacheSearch(), OnlMonDBodbc::Dump(), OnCalServer::FindClosestCalibratedRun(), OnlMonStatusDB::findRunNumInDB(), OnCalServer::findRunNumInDB(), OnCalServer::FixMissingCalibration(), OnCalServer::GetCalibStatus(), OnCalDBodbc::GetLastCalibratedRun(), OnCalServer::GetLastGoodRunTS(), PktSizeDBodbc::GetPacketContent(), RunToTimePg::getRunNumber(), RunDBodbc::GetRunNumbers(), RunToTimePg::getTime(), OnlMonDBodbc::GetVar(), OnlMonDBodbc::Info(), FROG::LustreSearch(), FROG::MinIOSearch(), ODBCResultSet::Next(), FROG::PGSearch(), RunDBodbc::RunType(), OnCalServer::SyncCalibTimeStampsToOnCal(), OnCalServer::SyncOncalTimeStampsToRunDB(), OnCalServer::updateDB(), and FROG::XRootDSearch().
bool odbc::ResultSet::previous ()
Moves to the previous row in the result set
Returns
true if the cursor is in the result set
Referenced by ODBCResultSet::Previous().
void odbc::ResultSet::refreshRow ()
Refreshes the current row
Referenced by ODBCResultSet::RefreshRow().
bool odbc::ResultSet::relative (int rows)
Moves the cursor inside the result set relative to the current row. Negative values are allowed. This call is illegal if there is no current row.
Returns
true if the cursor is in the result set
Referenced by ODBCResultSet::Relative().
bool odbc::ResultSet::rowDeleted ()
Checks if the current row is deleted
Referenced by ODBCResultSet::RowDeleted().
bool odbc::ResultSet::rowInserted ()
Checks if the current row was inserted
Referenced by ODBCResultSet::RowInserted().
bool odbc::ResultSet::rowUpdated ()
Checks if the current row was updated
Referenced by ODBCResultSet::RowUpdated().
void odbc::ResultSet::setFetchSize (int fetchSize)
Sets this result set's fetch size (doesn't apply immediately)
Referenced by ODBCResultSet::SetFetchSize().
void odbc::ResultSet::updateAsciiStream (int idx, ODBCXX_STREAM * s, int len)
Sets the value of a column to a stream
Parameters
idx The column index, starting at 1
s The stream to assign
len The number of bytes in the stream
Referenced by ODBCResultSet::UpdateAsciiStream().
void odbc::ResultSet::updateAsciiStream (const ODBCXX_STRING & colName, ODBCXX_STREAM * s, int len)
Sets the value of a column to the contens of a stream
Parameters
colName The column name
s The stream to assign
len The number of bytes in the stream
void odbc::ResultSet::updateBinaryStream (int idx, ODBCXX_STREAM * s, int len)
Sets the value of a column to the contens of a stream
Parameters
idx The column index, starting at 1
s The stream to assign
len The number of bytes in the stream
Referenced by ODBCResultSet::UpdateBinaryStream().
void odbc::ResultSet::updateBinaryStream (const ODBCXX_STRING & colName, ODBCXX_STREAM * s, int len)
Sets the value of a column to the contens of a stream
Parameters
colName The column name
s The stream to assign
len The number of bytes in the stream
void odbc::ResultSet::updateBoolean (int idx, bool val)
Sets the value of a column to a bool
Parameters
idx The column index, starting at 1
val The value to set
Referenced by ODBCResultSet::UpdateBoolean().
void odbc::ResultSet::updateBoolean (const ODBCXX_STRING & colName, bool val)
Sets the value of a column to a bool
Parameters
colName The name of the column
val The value to set
void odbc::ResultSet::updateByte (int idx, signed char val)
Sets the value of a column to a signed char
Parameters
idx The column index, starting at 1
val The value to set
Referenced by ODBCResultSet::UpdateByte().
void odbc::ResultSet::updateByte (const ODBCXX_STRING & colName, signed char val)
Sets the value of a column to a signed char
Parameters
colName The name of the column
val The value to set
void odbc::ResultSet::updateBytes (int idx, const ODBCXX_BYTES & val)
Sets the value of a column to a chunk of bytes
Parameters
idx The column index, starting at 1
val The value to set
Referenced by ODBCResultSet::UpdateBytes().
void odbc::ResultSet::updateBytes (const ODBCXX_STRING & colName, const ODBCXX_BYTES & val)
Sets the value of a column to a chunk of bytes
Parameters
colName The name of the column
val The value to set
void odbc::ResultSet::updateDate (int idx, const Date & val)
Sets the value of a column to a Date
Parameters
idx The column index, starting at 1
val The value to set
Referenced by ODBCResultSet::UpdateDate().
void odbc::ResultSet::updateDate (const ODBCXX_STRING & colName, const Date & val)
Sets the value of a column to a Date
Parameters
colName The name of the column
val The value to set
void odbc::ResultSet::updateDouble (int idx, double val)
Sets the value of a column to a double
Parameters
idx The column index, starting at 1
val The value to set
Referenced by ODBCResultSet::UpdateDouble().
void odbc::ResultSet::updateDouble (const ODBCXX_STRING & colName, double val)
Sets the value of a column to a double
Parameters
colName The name of the column
val The value to set
void odbc::ResultSet::updateFloat (int idx, float val)
Sets the value of a column to a float
Parameters
idx The column index, starting at 1
val The value to set
Referenced by ODBCResultSet::UpdateFloat().
void odbc::ResultSet::updateFloat (const ODBCXX_STRING & colName, float val)
Sets the value of a column to a float
Parameters
colName The name of the column
val The value to set
void odbc::ResultSet::updateInt (int idx, int val)
Sets the value of a column to an int
Parameters
idx The column index, starting at 1
val The value to set
Referenced by ODBCResultSet::UpdateInt().
void odbc::ResultSet::updateInt (const ODBCXX_STRING & colName, int val)
Sets the value of a column to an int
Parameters
colName The name of the column
val The value to set
void odbc::ResultSet::updateLong (int idx, Long val)
Sets the value of a column to a Long
Parameters
idx The column index, starting at 1
val The value to set
Referenced by ODBCResultSet::UpdateLong().
void odbc::ResultSet::updateLong (const ODBCXX_STRING & colName, Long val)
Sets the value of a column to a Long
Parameters
colName The name of the column
val The value to set
void odbc::ResultSet::updateNull (int idx)
Sets the value of a column to NULL
Parameters
idx The column index, starting at 1
Referenced by ODBCResultSet::UpdateNull().
void odbc::ResultSet::updateNull (const ODBCXX_STRING & colName)
Sets the value of a column to NULL
Parameters
colName The column name
void odbc::ResultSet::updateRow ()
Updates the current row.
Referenced by ODBCResultSet::UpdateRow().
void odbc::ResultSet::updateShort (int idx, short val)
Sets the value of a column to a short
Parameters
idx The column index, starting at 1
val The value to set
Referenced by ODBCResultSet::UpdateShort().
void odbc::ResultSet::updateShort (const ODBCXX_STRING & colName, short val)
Sets the value of a column to a short
Parameters
colName The name of the column
val The value to set
void odbc::ResultSet::updateString (int idx, const ODBCXX_STRING & val)
Sets the value of a column to a string
Parameters
idx The column index, starting at 1
val The value to set
Referenced by ODBCResultSet::UpdateString().
void odbc::ResultSet::updateString (const ODBCXX_STRING & colName, const ODBCXX_STRING & val)
Sets the value of a column to a string
Parameters
colName The name of the column
val The value to set
void odbc::ResultSet::updateTime (int idx, const Time & val)
Sets the value of a column to a Time
Parameters
idx The column index, starting at 1
val The value to set
Referenced by ODBCResultSet::UpdateTime().
void odbc::ResultSet::updateTime (const ODBCXX_STRING & colName, const Time & val)
Sets the value of a column to a Time
Parameters
colName The name of the column
val The value to set
void odbc::ResultSet::updateTimestamp (int idx, const Timestamp & val)
Sets the value of a column to a Timestamp
Parameters
idx The column index, starting at 1
val The value to set
Referenced by ODBCResultSet::UpdateTimestamp().
void odbc::ResultSet::updateTimestamp (const ODBCXX_STRING & colName, const Timestamp & val)
Sets the value of a column to a Timestamp
Parameters
colName The name of the column
val The value to set
bool odbc::ResultSet::wasNull () inline
Checks if the last fetched column value was NULL. Note that if this is true, the returned value was undefined.
Definition at line 428 of file resultset.h.
View newest version in sPHENIX GitHub at line 428 of file resultset.h
Referenced by OnlMonDBodbc::AddRow(), OnlMonDBodbc::Dump(), PktSizeDBodbc::GetPacketContent(), OnlMonDBodbc::GetVar(), and ODBCResultSet::WasNull().
Friends And Related Function Documentation
friend class ResultSetMetaData friend
Definition at line 40 of file resultset.h.
View newest version in sPHENIX GitHub at line 40 of file resultset.h
friend class Statement friend
Definition at line 39 of file resultset.h.
View newest version in sPHENIX GitHub at line 39 of file resultset.h
Member Data Documentation
unsigned int odbc::ResultSet::bindPos_ private
Definition at line 60 of file resultset.h.
View newest version in sPHENIX GitHub at line 60 of file resultset.h
bool odbc::ResultSet::colsBound_ private
Definition at line 56 of file resultset.h.
View newest version in sPHENIX GitHub at line 56 of file resultset.h
int odbc::ResultSet::currentFetchSize_ private
Definition at line 48 of file resultset.h.
View newest version in sPHENIX GitHub at line 48 of file resultset.h
SQLHSTMT odbc::ResultSet::hstmt_ private
Definition at line 44 of file resultset.h.
View newest version in sPHENIX GitHub at line 44 of file resultset.h
bool odbc::ResultSet::lastWasNull_ private
Definition at line 67 of file resultset.h.
View newest version in sPHENIX GitHub at line 67 of file resultset.h
int odbc::ResultSet::location_ private
Definition at line 65 of file resultset.h.
View newest version in sPHENIX GitHub at line 65 of file resultset.h
int odbc::ResultSet::locBeforeInsert_ private
Definition at line 70 of file resultset.h.
View newest version in sPHENIX GitHub at line 70 of file resultset.h
ResultSetMetaData* odbc::ResultSet::metaData_ private
Definition at line 63 of file resultset.h.
View newest version in sPHENIX GitHub at line 63 of file resultset.h
int odbc::ResultSet::newFetchSize_ private
Definition at line 49 of file resultset.h.
View newest version in sPHENIX GitHub at line 49 of file resultset.h
bool odbc::ResultSet::ownStatement_ private
Definition at line 45 of file resultset.h.
View newest version in sPHENIX GitHub at line 45 of file resultset.h
int odbc::ResultSet::rowBeforeInsert_ private
Definition at line 69 of file resultset.h.
View newest version in sPHENIX GitHub at line 69 of file resultset.h
Rowset* odbc::ResultSet::rowset_ private
Definition at line 51 of file resultset.h.
View newest version in sPHENIX GitHub at line 51 of file resultset.h
SQLUINTEGER odbc::ResultSet::rowsInRowset_ private
Definition at line 53 of file resultset.h.
View newest version in sPHENIX GitHub at line 53 of file resultset.h
SQLUSMALLINT* odbc::ResultSet::rowStatus_ private
Definition at line 52 of file resultset.h.
View newest version in sPHENIX GitHub at line 52 of file resultset.h
Statement* odbc::ResultSet::statement_ private
Definition at line 43 of file resultset.h.
View newest version in sPHENIX GitHub at line 43 of file resultset.h
bool odbc::ResultSet::streamedColsBound_ private
Definition at line 57 of file resultset.h.
View newest version in sPHENIX GitHub at line 57 of file resultset.h
The documentation for this class was generated from the following file:
RDBC/blob/master/include/RDBC/odbc++/resultset.h