Analysis Software: SvtxTrackInfo_v1 Class Reference
SvtxTrackInfo_v1 Class Reference
#include <coresoftware/blob/master/offline/packages/trackbase_historic/SvtxTrackInfo_v1.h>
Public Member Functions
SvtxTrackInfo_v1 ()
SvtxTrackInfo_v1 (const SvtxTrackInfo &)
SvtxTrackInfo_v1 (const SvtxTrackInfo_v1 &source)
SvtxTrackInfo_v1 & operator= (const SvtxTrackInfo_v1 &track)
~SvtxTrackInfo_v1 () override
void identify (std::ostream &os=std::cout) const override
void Reset () override
Clear Event.
PHObject * CloneMe () const override
Virtual copy constructor.
void CopyFrom (const SvtxTrackInfo &) override
copy content from base class
void CopyFrom (SvtxTrackInfo *source) override
copy content from base class
float get_chisq () const override
void set_chisq (float chisq) override
uint8_t get_ndf () const override
void set_ndf (uint8_t ndf) override
uint64_t get_hitbitmap () const override
void set_hitbitmap (uint64_t hitbitmap) override
short int get_crossing () const override
void set_crossing (short int crossing) override
float get_x () const override
void set_x (float x) override
float get_y () const override
void set_y (float y) override
float get_z () const override
void set_z (float z) override
float get_pos (unsigned int i) const override
float get_px () const override
void set_px (float px) override
float get_py () const override
void set_py (float py) override
float get_pz () const override
void set_pz (float pz) override
float get_mom (unsigned int i) const override
float get_p () const override
float get_pt () const override
float get_eta () const override
float get_phi () const override
float get_covariance (int i, int j) const override
void set_covariance (int i, int j, float value) override
Public Member Functions inherited from SvtxTrackInfo
~SvtxTrackInfo () override=default
int isValid () const override
isValid returns non zero if object contains vailid data
Public Member Functions inherited from PHObject
PHObject ()
ctor
~PHObject () override
dtor
virtual PHObject * clone () const final
PHObject * Clone (const char *newname="") const final
void Copy (TObject &object) const final
virtual int Integrate () const
virtual int Integrate (PHObject *)
virtual void CopyFrom (const PHObject *obj)
Private Attributes
unsigned int _track_id = std::numeric_limits<unsigned int>::quiet_NaN()
float m_chisq = std::numeric_limits<float>::quiet_NaN()
uint8_t m_ndf = std::numeric_limits<uint8_t>::quiet_NaN()
uint64_t m_hitbitmap = std::numeric_limits<uint64_t>::quiet_NaN()
short int m_crossing = std::numeric_limits<short int>::quiet_NaN()
TrackStateInfo_v1 m_state
Detailed Description
Definition at line 18 of file SvtxTrackInfo_v1.h.
View newest version in sPHENIX GitHub at line 18 of file SvtxTrackInfo_v1.h
Constructor & Destructor Documentation
SvtxTrackInfo_v1::SvtxTrackInfo_v1 () inline
Definition at line 21 of file SvtxTrackInfo_v1.h.
View newest version in sPHENIX GitHub at line 21 of file SvtxTrackInfo_v1.h
Referenced by CloneMe(), and Reset().
SvtxTrackInfo_v1::SvtxTrackInfo_v1 (const SvtxTrackInfo &) inline
Definition at line 24 of file SvtxTrackInfo_v1.h.
View newest version in sPHENIX GitHub at line 24 of file SvtxTrackInfo_v1.h
SvtxTrackInfo_v1::SvtxTrackInfo_v1 (const SvtxTrackInfo_v1 & source) inline
Definition at line 27 of file SvtxTrackInfo_v1.h.
View newest version in sPHENIX GitHub at line 27 of file SvtxTrackInfo_v1.h
References get_chisq(), get_covariance(), get_crossing(), get_hitbitmap(), get_ndf(), get_px(), get_py(), get_pz(), get_x(), get_y(), get_z(), i, j, m_chisq, m_crossing, m_hitbitmap, m_ndf, set_covariance(), set_px(), set_py(), set_pz(), set_x(), set_y(), and set_z().
SvtxTrackInfo_v1::~SvtxTrackInfo_v1 () inline override
Definition at line 54 of file SvtxTrackInfo_v1.h.
View newest version in sPHENIX GitHub at line 54 of file SvtxTrackInfo_v1.h
Member Function Documentation
PHObject* SvtxTrackInfo_v1::CloneMe () const inline override virtual
Virtual copy constructor.
Reimplemented from SvtxTrackInfo.
Definition at line 63 of file SvtxTrackInfo_v1.h.
View newest version in sPHENIX GitHub at line 63 of file SvtxTrackInfo_v1.h
References SvtxTrackInfo_v1().
void SvtxTrackInfo_v1::CopyFrom (const SvtxTrackInfo &) override virtual
copy content from base class
Reimplemented from SvtxTrackInfo.
Definition at line 13 of file SvtxTrackInfo_v1.cc.
View newest version in sPHENIX GitHub at line 13 of file SvtxTrackInfo_v1.cc
References SvtxTrackInfo::get_chisq(), SvtxTrackInfo::get_covariance(), SvtxTrackInfo::get_crossing(), SvtxTrackInfo::get_hitbitmap(), SvtxTrackInfo::get_ndf(), SvtxTrackInfo::get_px(), SvtxTrackInfo::get_py(), SvtxTrackInfo::get_pz(), SvtxTrackInfo::get_x(), SvtxTrackInfo::get_y(), SvtxTrackInfo::get_z(), i, j, set_chisq(), set_covariance(), set_crossing(), set_hitbitmap(), set_ndf(), set_px(), set_py(), set_pz(), set_x(), set_y(), and set_z().
Referenced by CopyFrom(), and operator=().
void SvtxTrackInfo_v1::CopyFrom (SvtxTrackInfo *) inline override virtual
copy content from base class
Reimplemented from SvtxTrackInfo.
Definition at line 69 of file SvtxTrackInfo_v1.h.
View newest version in sPHENIX GitHub at line 69 of file SvtxTrackInfo_v1.h
References CopyFrom().
float SvtxTrackInfo_v1::get_chisq () const inline override virtual
Reimplemented from SvtxTrackInfo.
Definition at line 78 of file SvtxTrackInfo_v1.h.
View newest version in sPHENIX GitHub at line 78 of file SvtxTrackInfo_v1.h
References m_chisq.
Referenced by DSTTrackInfoWriter::evaluate_track_info(), and SvtxTrackInfo_v1().
float SvtxTrackInfo_v1::get_covariance (int i, int j) const inline override virtual
Reimplemented from SvtxTrackInfo.
Definition at line 117 of file SvtxTrackInfo_v1.h.
View newest version in sPHENIX GitHub at line 117 of file SvtxTrackInfo_v1.h
References TrackStateInfo_v1::get_covariance(), and m_state.
Referenced by SvtxTrackInfo_v1().
short int SvtxTrackInfo_v1::get_crossing () const inline override virtual
Reimplemented from SvtxTrackInfo.
Definition at line 87 of file SvtxTrackInfo_v1.h.
View newest version in sPHENIX GitHub at line 87 of file SvtxTrackInfo_v1.h
References m_crossing.
Referenced by DSTTrackInfoWriter::evaluate_track_info(), and SvtxTrackInfo_v1().
float SvtxTrackInfo_v1::get_eta () const inline override virtual
Reimplemented from SvtxTrackInfo.
Definition at line 114 of file SvtxTrackInfo_v1.h.
View newest version in sPHENIX GitHub at line 114 of file SvtxTrackInfo_v1.h
References get_pt(), and get_pz().
uint64_t SvtxTrackInfo_v1::get_hitbitmap () const inline override virtual
Reimplemented from SvtxTrackInfo.
Definition at line 84 of file SvtxTrackInfo_v1.h.
View newest version in sPHENIX GitHub at line 84 of file SvtxTrackInfo_v1.h
References m_hitbitmap.
Referenced by DSTTrackInfoWriter::evaluate_track_info(), and SvtxTrackInfo_v1().
float SvtxTrackInfo_v1::get_mom (unsigned int i) const inline override virtual
Reimplemented from SvtxTrackInfo.
Definition at line 110 of file SvtxTrackInfo_v1.h.
View newest version in sPHENIX GitHub at line 110 of file SvtxTrackInfo_v1.h
References TrackStateInfo_v1::get_mom(), and m_state.
uint8_t SvtxTrackInfo_v1::get_ndf () const inline override virtual
Reimplemented from SvtxTrackInfo.
Definition at line 81 of file SvtxTrackInfo_v1.h.
View newest version in sPHENIX GitHub at line 81 of file SvtxTrackInfo_v1.h
References m_ndf.
Referenced by DSTTrackInfoWriter::evaluate_track_info(), and SvtxTrackInfo_v1().
float SvtxTrackInfo_v1::get_p () const inline override virtual
Reimplemented from SvtxTrackInfo.
Definition at line 112 of file SvtxTrackInfo_v1.h.
View newest version in sPHENIX GitHub at line 112 of file SvtxTrackInfo_v1.h
References get_px(), get_py(), and get_pz().
float SvtxTrackInfo_v1::get_phi () const inline override virtual
Reimplemented from SvtxTrackInfo.
Definition at line 115 of file SvtxTrackInfo_v1.h.
View newest version in sPHENIX GitHub at line 115 of file SvtxTrackInfo_v1.h
References get_px(), and get_py().
float SvtxTrackInfo_v1::get_pos (unsigned int i) const inline override virtual
Reimplemented from SvtxTrackInfo.
Definition at line 99 of file SvtxTrackInfo_v1.h.
View newest version in sPHENIX GitHub at line 99 of file SvtxTrackInfo_v1.h
References TrackStateInfo_v1::get_pos(), and m_state.
float SvtxTrackInfo_v1::get_pt () const inline override virtual
Reimplemented from SvtxTrackInfo.
Definition at line 113 of file SvtxTrackInfo_v1.h.
View newest version in sPHENIX GitHub at line 113 of file SvtxTrackInfo_v1.h
References get_px(), and get_py().
Referenced by get_eta().
float SvtxTrackInfo_v1::get_px () const inline override virtual
Reimplemented from SvtxTrackInfo.
Definition at line 101 of file SvtxTrackInfo_v1.h.
View newest version in sPHENIX GitHub at line 101 of file SvtxTrackInfo_v1.h
References TrackStateInfo_v1::get_px(), and m_state.
Referenced by get_p(), get_phi(), get_pt(), and SvtxTrackInfo_v1().
float SvtxTrackInfo_v1::get_py () const inline override virtual
Reimplemented from SvtxTrackInfo.
Definition at line 104 of file SvtxTrackInfo_v1.h.
View newest version in sPHENIX GitHub at line 104 of file SvtxTrackInfo_v1.h
References TrackStateInfo_v1::get_py(), and m_state.
Referenced by get_p(), get_phi(), get_pt(), and SvtxTrackInfo_v1().
float SvtxTrackInfo_v1::get_pz () const inline override virtual
Reimplemented from SvtxTrackInfo.
Definition at line 107 of file SvtxTrackInfo_v1.h.
View newest version in sPHENIX GitHub at line 107 of file SvtxTrackInfo_v1.h
References TrackStateInfo_v1::get_pz(), and m_state.
Referenced by get_eta(), get_p(), and SvtxTrackInfo_v1().
float SvtxTrackInfo_v1::get_x () const inline override virtual
Reimplemented from SvtxTrackInfo.
Definition at line 90 of file SvtxTrackInfo_v1.h.
View newest version in sPHENIX GitHub at line 90 of file SvtxTrackInfo_v1.h
References TrackStateInfo_v1::get_x(), and m_state.
Referenced by SvtxTrackInfo_v1().
float SvtxTrackInfo_v1::get_y () const inline override virtual
Reimplemented from SvtxTrackInfo.
Definition at line 93 of file SvtxTrackInfo_v1.h.
View newest version in sPHENIX GitHub at line 93 of file SvtxTrackInfo_v1.h
References TrackStateInfo_v1::get_y(), and m_state.
Referenced by SvtxTrackInfo_v1().
float SvtxTrackInfo_v1::get_z () const inline override virtual
Reimplemented from SvtxTrackInfo.
Definition at line 96 of file SvtxTrackInfo_v1.h.
View newest version in sPHENIX GitHub at line 96 of file SvtxTrackInfo_v1.h
References TrackStateInfo_v1::get_z(), and m_state.
Referenced by DSTTrackInfoWriter::evaluate_track_info(), and SvtxTrackInfo_v1().
void SvtxTrackInfo_v1::identify (std::ostream & os = std::cout) const inline override virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from SvtxTrackInfo.
Definition at line 57 of file SvtxTrackInfo_v1.h.
View newest version in sPHENIX GitHub at line 57 of file SvtxTrackInfo_v1.h
References os.
SvtxTrackInfo_v1 & SvtxTrackInfo_v1::operator= (const SvtxTrackInfo_v1 & track)
Definition at line 36 of file SvtxTrackInfo_v1.cc.
View newest version in sPHENIX GitHub at line 36 of file SvtxTrackInfo_v1.cc
References CopyFrom().
void SvtxTrackInfo_v1::Reset () inline override virtual
Clear Event.
Reimplemented from PHObject.
Definition at line 61 of file SvtxTrackInfo_v1.h.
View newest version in sPHENIX GitHub at line 61 of file SvtxTrackInfo_v1.h
References SvtxTrackInfo_v1().
void SvtxTrackInfo_v1::set_chisq (float chisq) inline override virtual
Reimplemented from SvtxTrackInfo.
Definition at line 79 of file SvtxTrackInfo_v1.h.
View newest version in sPHENIX GitHub at line 79 of file SvtxTrackInfo_v1.h
References m_chisq.
Referenced by CopyFrom(), and DSTTrackInfoWriter::evaluate_track_info().
void SvtxTrackInfo_v1::set_covariance (int i, int j, float value) inline override virtual
Reimplemented from SvtxTrackInfo.
Definition at line 118 of file SvtxTrackInfo_v1.h.
View newest version in sPHENIX GitHub at line 118 of file SvtxTrackInfo_v1.h
References m_state, and TrackStateInfo_v1::set_covariance().
Referenced by CopyFrom(), DSTTrackInfoWriter::evaluate_track_info(), and SvtxTrackInfo_v1().
void SvtxTrackInfo_v1::set_crossing (short int crossing) inline override virtual
Reimplemented from SvtxTrackInfo.
Definition at line 88 of file SvtxTrackInfo_v1.h.
View newest version in sPHENIX GitHub at line 88 of file SvtxTrackInfo_v1.h
References m_crossing.
Referenced by CopyFrom(), and DSTTrackInfoWriter::evaluate_track_info().
void SvtxTrackInfo_v1::set_hitbitmap (uint64_t hitbitmap) inline override virtual
Reimplemented from SvtxTrackInfo.
Definition at line 85 of file SvtxTrackInfo_v1.h.
View newest version in sPHENIX GitHub at line 85 of file SvtxTrackInfo_v1.h
References m_hitbitmap.
Referenced by CopyFrom(), and DSTTrackInfoWriter::evaluate_track_info().
void SvtxTrackInfo_v1::set_ndf (uint8_t ndf) inline override virtual
Reimplemented from SvtxTrackInfo.
Definition at line 82 of file SvtxTrackInfo_v1.h.
View newest version in sPHENIX GitHub at line 82 of file SvtxTrackInfo_v1.h
References m_ndf.
Referenced by CopyFrom(), and DSTTrackInfoWriter::evaluate_track_info().
void SvtxTrackInfo_v1::set_px (float px) inline override virtual
Reimplemented from SvtxTrackInfo.
Definition at line 102 of file SvtxTrackInfo_v1.h.
View newest version in sPHENIX GitHub at line 102 of file SvtxTrackInfo_v1.h
References m_state, and TrackStateInfo_v1::set_px().
Referenced by CopyFrom(), DSTTrackInfoWriter::evaluate_track_info(), and SvtxTrackInfo_v1().
void SvtxTrackInfo_v1::set_py (float py) inline override virtual
Reimplemented from SvtxTrackInfo.
Definition at line 105 of file SvtxTrackInfo_v1.h.
View newest version in sPHENIX GitHub at line 105 of file SvtxTrackInfo_v1.h
References m_state, and TrackStateInfo_v1::set_py().
Referenced by CopyFrom(), DSTTrackInfoWriter::evaluate_track_info(), and SvtxTrackInfo_v1().
void SvtxTrackInfo_v1::set_pz (float pz) inline override virtual
Reimplemented from SvtxTrackInfo.
Definition at line 108 of file SvtxTrackInfo_v1.h.
View newest version in sPHENIX GitHub at line 108 of file SvtxTrackInfo_v1.h
References m_state, and TrackStateInfo_v1::set_pz().
Referenced by CopyFrom(), DSTTrackInfoWriter::evaluate_track_info(), and SvtxTrackInfo_v1().
void SvtxTrackInfo_v1::set_x (float x) inline override virtual
Reimplemented from SvtxTrackInfo.
Definition at line 91 of file SvtxTrackInfo_v1.h.
View newest version in sPHENIX GitHub at line 91 of file SvtxTrackInfo_v1.h
References m_state, and TrackStateInfo_v1::set_x().
Referenced by CopyFrom(), DSTTrackInfoWriter::evaluate_track_info(), and SvtxTrackInfo_v1().
void SvtxTrackInfo_v1::set_y (float y) inline override virtual
Reimplemented from SvtxTrackInfo.
Definition at line 94 of file SvtxTrackInfo_v1.h.
View newest version in sPHENIX GitHub at line 94 of file SvtxTrackInfo_v1.h
References m_state, and TrackStateInfo_v1::set_y().
Referenced by CopyFrom(), DSTTrackInfoWriter::evaluate_track_info(), and SvtxTrackInfo_v1().
void SvtxTrackInfo_v1::set_z (float z) inline override virtual
Reimplemented from SvtxTrackInfo.
Definition at line 97 of file SvtxTrackInfo_v1.h.
View newest version in sPHENIX GitHub at line 97 of file SvtxTrackInfo_v1.h
References m_state, and TrackStateInfo_v1::set_z().
Referenced by CopyFrom(), DSTTrackInfoWriter::evaluate_track_info(), and SvtxTrackInfo_v1().
Member Data Documentation
unsigned int SvtxTrackInfo_v1::_track_id = std::numeric_limits<unsigned int>::quiet_NaN() private
Definition at line 122 of file SvtxTrackInfo_v1.h.
View newest version in sPHENIX GitHub at line 122 of file SvtxTrackInfo_v1.h
float SvtxTrackInfo_v1::m_chisq = std::numeric_limits<float>::quiet_NaN() private
Definition at line 124 of file SvtxTrackInfo_v1.h.
View newest version in sPHENIX GitHub at line 124 of file SvtxTrackInfo_v1.h
Referenced by get_chisq(), set_chisq(), and SvtxTrackInfo_v1().
short int SvtxTrackInfo_v1::m_crossing = std::numeric_limits<short int>::quiet_NaN() private
Definition at line 127 of file SvtxTrackInfo_v1.h.
View newest version in sPHENIX GitHub at line 127 of file SvtxTrackInfo_v1.h
Referenced by get_crossing(), set_crossing(), and SvtxTrackInfo_v1().
uint64_t SvtxTrackInfo_v1::m_hitbitmap = std::numeric_limits<uint64_t>::quiet_NaN() private
Definition at line 126 of file SvtxTrackInfo_v1.h.
View newest version in sPHENIX GitHub at line 126 of file SvtxTrackInfo_v1.h
Referenced by get_hitbitmap(), set_hitbitmap(), and SvtxTrackInfo_v1().
uint8_t SvtxTrackInfo_v1::m_ndf = std::numeric_limits<uint8_t>::quiet_NaN() private
Definition at line 125 of file SvtxTrackInfo_v1.h.
View newest version in sPHENIX GitHub at line 125 of file SvtxTrackInfo_v1.h
Referenced by get_ndf(), set_ndf(), and SvtxTrackInfo_v1().
TrackStateInfo_v1 SvtxTrackInfo_v1::m_state private
Definition at line 130 of file SvtxTrackInfo_v1.h.
View newest version in sPHENIX GitHub at line 130 of file SvtxTrackInfo_v1.h
Referenced by get_covariance(), get_mom(), get_pos(), get_px(), get_py(), get_pz(), get_x(), get_y(), get_z(), set_covariance(), set_px(), set_py(), set_pz(), set_x(), set_y(), and set_z().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/trackbase_historic/SvtxTrackInfo_v1.h
coresoftware/blob/master/offline/packages/trackbase_historic/SvtxTrackInfo_v1.cc