Analysis Software: Acts::MaterialCollector Struct Reference
Acts::MaterialCollector Struct Reference
A Material Collector struct.
#include <acts/blob/sPHENIX/Core/include/Acts/Material/MaterialCollector.hpp>
Classes
struct this_result
Public Types
using result_type = this_result
using result_type = this_result
Public Member Functions
template<typename propagator_state_t , typename stepper_t , typename navigator_t >
void operator() (propagator_state_t &state, const stepper_t &stepper, const navigator_t &navigator, result_type &result, const Logger &logger) const
template<typename propagator_state_t , typename stepper_t , typename navigator_t >
void operator() (propagator_state_t &state, const stepper_t &stepper, const navigator_t &navigator, result_type &result, const Logger &) const
Public Attributes
bool detailedCollection = false
Detailed Description
A Material Collector struct.
Collector of material and position along propagation.
Definition at line 30 of file MaterialCollector.hpp.
View newest version in sPHENIX GitHub at line 30 of file MaterialCollector.hpp
Member Typedef Documentation
using Acts::MaterialCollector::result_type = this_result
Definition at line 47 of file MaterialCollector.hpp.
View newest version in sPHENIX GitHub at line 47 of file MaterialCollector.hpp
using Acts::MaterialCollector::result_type = this_result
Definition at line 59 of file VolumeMaterialMapperTests.cpp.
View newest version in sPHENIX GitHub at line 59 of file VolumeMaterialMapperTests.cpp
Member Function Documentation
template<typename propagator_state_t , typename stepper_t , typename navigator_t > void Acts::MaterialCollector::operator() (propagator_state_t & state, const stepper_t & stepper, const navigator_t & navigator, result_type & result, const Logger &) const inline
Definition at line 63 of file VolumeMaterialMapperTests.cpp.
View newest version in sPHENIX GitHub at line 63 of file VolumeMaterialMapperTests.cpp
References Acts::MaterialCollector::this_result::matTrue, Acts::MaterialCollector::this_result::position, and position.
template<typename propagator_state_t , typename stepper_t , typename navigator_t > void Acts::MaterialCollector::operator() (propagator_state_t & state, const stepper_t & stepper, const navigator_t & navigator, result_type & result, const Logger & logger) const inline
Collector action for the ActionList of the Propagator It checks if the state has a current surface, in which case the action is performed:
it records the surface given the configuration
Template Parameters
propagator_state_t is the type of Propagator state
stepper_t Type of the stepper of the propagation
navigator_t Type of the navigator of the propagation
Parameters
state is the mutable propagator state object
stepper The stepper in use
navigator The navigator in use
result is the result object to be filled
logger a logger instance
Definition at line 65 of file MaterialCollector.hpp.
View newest version in sPHENIX GitHub at line 65 of file MaterialCollector.hpp
References Acts::ACTS_VERBOSE(), Acts::MaterialCollector::this_result::collected, detailedCollection, Acts::MaterialHit::direction, Acts::MaterialHit::material, Acts::MaterialSlab::material(), Acts::MaterialCollector::this_result::materialInL0, Acts::MaterialCollector::this_result::materialInX0, Acts::MaterialHit::pathLength, Acts::MaterialHit::position, Acts::MaterialHit::surface, Acts::MaterialSlab::thickness(), Acts::MaterialSlab::thicknessInL0(), and Acts::MaterialSlab::thicknessInX0().
Member Data Documentation
bool Acts::MaterialCollector::detailedCollection = false
In the detailed collection mode the material per surface is collected, otherwise only the total pathlength in X0 or L0 are recorded
Definition at line 34 of file MaterialCollector.hpp.
View newest version in sPHENIX GitHub at line 34 of file MaterialCollector.hpp
Referenced by operator()().
The documentation for this struct was generated from the following files:
acts/blob/sPHENIX/Core/include/Acts/Material/MaterialCollector.hpp
acts/blob/sPHENIX/Tests/UnitTests/Core/Material/VolumeMaterialMapperTests.cpp