Analysis Software: CaloRecoUtility Class Reference
CaloRecoUtility Class Reference
CaloRecoUtility.
#include <coresoftware/blob/master/offline/packages/CaloReco/CaloRecoUtility.h>
Public Member Functions
~CaloRecoUtility ()
CaloRecoUtility ()
CaloRecoUtility (CaloRecoUtility &cru)
CaloRecoUtility & operator= (CaloRecoUtility const &)
void ShowerDepthCorrZVertex (RawCluster *clus, float zvtx)
corrects cluster Z (implicitly also eta) for updated z vertex
void ProbCorrsZVertex (RawCluster *clus, float zvtx)
void LoadProfile ()
Private Attributes
bool _profLoaded
BEmcRec * _bemc = nullptr
Detailed Description
CaloRecoUtility.
Definition at line 22 of file CaloRecoUtility.h.
View newest version in sPHENIX GitHub at line 22 of file CaloRecoUtility.h
Constructor & Destructor Documentation
CaloRecoUtility::~CaloRecoUtility ()
Definition at line 218 of file CaloRecoUtility.cc.
View newest version in sPHENIX GitHub at line 218 of file CaloRecoUtility.cc
References _bemc.
CaloRecoUtility::CaloRecoUtility ()
Definition at line 155 of file CaloRecoUtility.cc.
View newest version in sPHENIX GitHub at line 155 of file CaloRecoUtility.cc
References _bemc, BEmcRec::SetDim(), BEmcRec::SetProbNoiseParam(), and BEmcRec::SetTowerThreshold().
CaloRecoUtility::CaloRecoUtility (CaloRecoUtility & cru)
Definition at line 172 of file CaloRecoUtility.cc.
View newest version in sPHENIX GitHub at line 172 of file CaloRecoUtility.cc
References _bemc, _profLoaded, BEmcRec::SetDim(), BEmcRec::SetProbNoiseParam(), and BEmcRec::SetTowerThreshold().
Member Function Documentation
void CaloRecoUtility::LoadProfile ()
Definition at line 135 of file CaloRecoUtility.cc.
View newest version in sPHENIX GitHub at line 135 of file CaloRecoUtility.cc
References _bemc, _profLoaded, CDBInterface::getUrl(), CDBInterface::instance(), BEmcRec::LoadProfile(), PHWHERE, and summary::url.
Referenced by RawClusterZVertexRecorrect::InitRun(), and ProbCorrsZVertex().
CaloRecoUtility & CaloRecoUtility::operator= (CaloRecoUtility const & cru)
Definition at line 192 of file CaloRecoUtility.cc.
View newest version in sPHENIX GitHub at line 192 of file CaloRecoUtility.cc
References _bemc, _profLoaded, BEmcRec::SetDim(), BEmcRec::SetProbNoiseParam(), and BEmcRec::SetTowerThreshold().
void CaloRecoUtility::ProbCorrsZVertex (RawCluster * clus, float zvtx)
Definition at line 71 of file CaloRecoUtility.cc.
View newest version in sPHENIX GitHub at line 71 of file CaloRecoUtility.cc
References _bemc, _profLoaded, EmcModule::amp, RawTowerDefs::decode_index1(), RawTowerDefs::decode_index2(), RawCluster::get_energy(), RawCluster::get_towers(), RawCluster::get_x(), RawCluster::get_y(), RawCluster::get_z(), BEmcRec::GetProb(), EmcModule::ich, LoadProfile(), RawCluster::set_chi2(), RawCluster::set_prob(), BEmcRec::SetVertex(), EmcModule::tof, and vz.
Referenced by RawClusterZVertexRecorrect::process_event().
void CaloRecoUtility::ShowerDepthCorrZVertex (RawCluster * clus, float zvtx)
corrects cluster Z (implicitly also eta) for updated z vertex
Definition at line 22 of file CaloRecoUtility.cc.
View newest version in sPHENIX GitHub at line 22 of file CaloRecoUtility.cc
References dz, RawCluster::get_energy(), RawCluster::get_x(), RawCluster::get_y(), RawCluster::get_z(), Acts::IntegrationTest::L, and RawCluster::set_z().
Referenced by RawClusterZVertexRecorrect::process_event().
Member Data Documentation
BEmcRec* CaloRecoUtility::_bemc = nullptr private
Definition at line 38 of file CaloRecoUtility.h.
View newest version in sPHENIX GitHub at line 38 of file CaloRecoUtility.h
Referenced by CaloRecoUtility(), LoadProfile(), operator=(), ProbCorrsZVertex(), and ~CaloRecoUtility().
bool CaloRecoUtility::_profLoaded private
Definition at line 37 of file CaloRecoUtility.h.
View newest version in sPHENIX GitHub at line 37 of file CaloRecoUtility.h
Referenced by CaloRecoUtility(), LoadProfile(), operator=(), and ProbCorrsZVertex().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/CaloReco/CaloRecoUtility.h
coresoftware/blob/master/offline/packages/CaloReco/CaloRecoUtility.cc