Analysis Software: Acts::Experimental::MultiLayerSurfacesUpdatorImpl< grid_t, path_generator > Class Template Reference
Acts::Experimental::MultiLayerSurfacesUpdatorImpl< grid_t, path_generator > Class Template Reference
#include <acts/blob/sPHENIX/Core/include/Acts/Navigation/MultiLayerSurfacesUpdator.hpp>
Public Types
using grid_type = grid_t
Broadcast the grid type.
Public Member Functions
MultiLayerSurfacesUpdatorImpl (grid_type &&igrid, const std::array< BinningValue, grid_type::DIM > &icasts, const Transform3 &itr=Transform3::Identity())
Constructor for a grid based surface attacher.
MultiLayerSurfacesUpdatorImpl ()=delete
void update (const GeometryContext &gctx, NavigationState &nState) const
std::array< ActsScalar,
grid_type::DIM > castPosition (const Vector3 &position) const
void resolveDuplicates (const GeometryContext &gctx, std::vector< const Acts::Surface * > &surfaces) const
Public Member Functions inherited from Acts::Experimental::INavigationDelegate
virtual ~INavigationDelegate ()=default
Public Attributes
grid_type grid
The grid where the indices are stored.
path_generator pgenerator
The path generator.
std::array< BinningValue,
grid_type::DIM > casts {}
These are the cast parameters - copied from constructor.
Transform3 transform = Transform3::Identity()
A transform to be applied to the position.
Private Member Functions
template<typename Array , std::size_t... idx>
void fillCasts (const Vector3 &position, Array &a, std::index_sequence< idx...>) const
Detailed Description
template<typename grid_t, typename path_generator>
class Acts::Experimental::MultiLayerSurfacesUpdatorImpl< grid_t, path_generator >
Definition at line 24 of file MultiLayerSurfacesUpdator.hpp.
View newest version in sPHENIX GitHub at line 24 of file MultiLayerSurfacesUpdator.hpp
Member Typedef Documentation
template<typename grid_t , typename path_generator > using Acts::Experimental::MultiLayerSurfacesUpdatorImpl< grid_t, path_generator >::grid_type = grid_t
Broadcast the grid type.
Definition at line 27 of file MultiLayerSurfacesUpdator.hpp.
View newest version in sPHENIX GitHub at line 27 of file MultiLayerSurfacesUpdator.hpp
Constructor & Destructor Documentation
template<typename grid_t , typename path_generator > Acts::Experimental::MultiLayerSurfacesUpdatorImpl< grid_t, path_generator >::MultiLayerSurfacesUpdatorImpl (grid_type && igrid, const std::array< BinningValue, grid_type::DIM > & icasts, const Transform3 & itr = Transform3::Identity()) inline
Constructor for a grid based surface attacher.
Parameters
igrid the grid that is moved into this attacher
icasts is the cast values array
itr a transform applied to the global position
Definition at line 45 of file MultiLayerSurfacesUpdator.hpp.
View newest version in sPHENIX GitHub at line 45 of file MultiLayerSurfacesUpdator.hpp
template<typename grid_t , typename path_generator > Acts::Experimental::MultiLayerSurfacesUpdatorImpl< grid_t, path_generator >::MultiLayerSurfacesUpdatorImpl () delete
Member Function Documentation
template<typename grid_t , typename path_generator > std::array<ActsScalar, grid_type::DIM> Acts::Experimental::MultiLayerSurfacesUpdatorImpl< grid_t, path_generator >::castPosition (const Vector3 & position) const inline
Cast into a lookup position
Parameters
position is the position of the update call
Definition at line 77 of file MultiLayerSurfacesUpdator.hpp.
View newest version in sPHENIX GitHub at line 77 of file MultiLayerSurfacesUpdator.hpp
References Acts::Experimental::MultiLayerSurfacesUpdatorImpl< grid_t, path_generator >::fillCasts(), position, and Acts::Experimental::MultiLayerSurfacesUpdatorImpl< grid_t, path_generator >::transform.
Referenced by Acts::Experimental::MultiLayerSurfacesUpdatorImpl< grid_t, path_generator >::update().
template<typename grid_t , typename path_generator > template<typename Array , std::size_t... idx> void Acts::Experimental::MultiLayerSurfacesUpdatorImpl< grid_t, path_generator >::fillCasts (const Vector3 & position, Array & a, std::index_sequence< idx...>) const inline private
Unroll the cast loop
Parameters
position is the position of the update call
a is the array to be filled
Definition at line 116 of file MultiLayerSurfacesUpdator.hpp.
View newest version in sPHENIX GitHub at line 116 of file MultiLayerSurfacesUpdator.hpp
References Acts::VectorHelpers::cast(), Acts::Experimental::MultiLayerSurfacesUpdatorImpl< grid_t, path_generator >::casts, and ambiguity_solver_full_chain::idx.
Referenced by Acts::Experimental::MultiLayerSurfacesUpdatorImpl< grid_t, path_generator >::castPosition().
template<typename grid_t , typename path_generator > void Acts::Experimental::MultiLayerSurfacesUpdatorImpl< grid_t, path_generator >::resolveDuplicates (const GeometryContext & gctx, std::vector< const Acts::Surface * > & surfaces) const inline
Resolve duplicate on surface candidates
Parameters
gctx The geometry context of the current geometry
surfaces is the surface candidates to check and resolve for duplicates
Definition at line 92 of file MultiLayerSurfacesUpdator.hpp.
View newest version in sPHENIX GitHub at line 92 of file MultiLayerSurfacesUpdator.hpp
References gctx, and Acts::Experimental::detail::BlueprintHelper::sort().
Referenced by Acts::Experimental::MultiLayerSurfacesUpdatorImpl< grid_t, path_generator >::update().
template<typename grid_t , typename path_generator > void Acts::Experimental::MultiLayerSurfacesUpdatorImpl< grid_t, path_generator >::update (const GeometryContext & gctx, NavigationState & nState) const inline
Definition at line 52 of file MultiLayerSurfacesUpdator.hpp.
View newest version in sPHENIX GitHub at line 52 of file MultiLayerSurfacesUpdator.hpp
References Acts::Experimental::MultiLayerSurfacesUpdatorImpl< grid_t, path_generator >::castPosition(), Acts::Experimental::NavigationState::direction, entry, Acts::Experimental::IndexedSurfacesExtractor::extract(), Acts::Experimental::SurfacesFiller::fill(), Acts::Experimental::MultiLayerSurfacesUpdatorImpl< grid_t, path_generator >::grid, merge_hashes::p, path, Acts::Experimental::MultiLayerSurfacesUpdatorImpl< grid_t, path_generator >::pgenerator, Acts::Experimental::NavigationState::position, Acts::Experimental::MultiLayerSurfacesUpdatorImpl< grid_t, path_generator >::resolveDuplicates(), step, and Acts::Experimental::updateCandidates().
Member Data Documentation
template<typename grid_t , typename path_generator > std::array<BinningValue, grid_type::DIM> Acts::Experimental::MultiLayerSurfacesUpdatorImpl< grid_t, path_generator >::casts {}
These are the cast parameters - copied from constructor.
Definition at line 36 of file MultiLayerSurfacesUpdator.hpp.
View newest version in sPHENIX GitHub at line 36 of file MultiLayerSurfacesUpdator.hpp
Referenced by Acts::Experimental::MultiLayerSurfacesUpdatorImpl< grid_t, path_generator >::fillCasts().
template<typename grid_t , typename path_generator > grid_type Acts::Experimental::MultiLayerSurfacesUpdatorImpl< grid_t, path_generator >::grid
The grid where the indices are stored.
Definition at line 30 of file MultiLayerSurfacesUpdator.hpp.
View newest version in sPHENIX GitHub at line 30 of file MultiLayerSurfacesUpdator.hpp
Referenced by Acts::Experimental::MultiLayerSurfacesUpdatorImpl< grid_t, path_generator >::update().
template<typename grid_t , typename path_generator > path_generator Acts::Experimental::MultiLayerSurfacesUpdatorImpl< grid_t, path_generator >::pgenerator
The path generator.
Definition at line 33 of file MultiLayerSurfacesUpdator.hpp.
View newest version in sPHENIX GitHub at line 33 of file MultiLayerSurfacesUpdator.hpp
Referenced by Acts::Experimental::MultiLayerSurfacesUpdatorImpl< grid_t, path_generator >::update().
template<typename grid_t , typename path_generator > Transform3 Acts::Experimental::MultiLayerSurfacesUpdatorImpl< grid_t, path_generator >::transform = Transform3::Identity()
A transform to be applied to the position.
Definition at line 39 of file MultiLayerSurfacesUpdator.hpp.
View newest version in sPHENIX GitHub at line 39 of file MultiLayerSurfacesUpdator.hpp
Referenced by Acts::Experimental::MultiLayerSurfacesUpdatorImpl< grid_t, path_generator >::castPosition().
The documentation for this class was generated from the following file:
acts/blob/sPHENIX/Core/include/Acts/Navigation/MultiLayerSurfacesUpdator.hpp