Analysis Software: SurfaceGeoIdGenerator Class Reference
SurfaceGeoIdGenerator Class Reference
Public Member Functions
Acts::Experimental::IGeometryIdGenerator::GeoIdCache generateCache () const final
Virtual interface method to generata a geometry id cache.
void assignGeometryId (Acts::Experimental::IGeometryIdGenerator::GeoIdCache &, Acts::Experimental::DetectorVolume &dVolume) const final
void assignGeometryId (Acts::Experimental::IGeometryIdGenerator::GeoIdCache &, Acts::Experimental::Portal &) const final
void assignGeometryId (Acts::Experimental::IGeometryIdGenerator::GeoIdCache &, Acts::Surface &) const final
The virtual interface definition for assigning a geometry id to a surface.
Acts::Experimental::IGeometryIdGenerator::GeoIdCache generateCache () const final
Virtual interface method to generata a geometry id cache.
void assignGeometryId (Acts::Experimental::IGeometryIdGenerator::GeoIdCache &, Acts::Experimental::DetectorVolume &dVolume) const final
void assignGeometryId (Acts::Experimental::IGeometryIdGenerator::GeoIdCache &, Acts::Experimental::Portal &) const final
void assignGeometryId (Acts::Experimental::IGeometryIdGenerator::GeoIdCache &, Acts::Surface &) const final
The virtual interface definition for assigning a geometry id to a surface.
Public Member Functions inherited from Acts::Experimental::IGeometryIdGenerator
virtual ~IGeometryIdGenerator ()=default
Additional Inherited Members
Public Types inherited from Acts::Experimental::IGeometryIdGenerator
using GeoIdCache = std::any
Detailed Description
Definition at line 73 of file DetectorBuilderTests.cpp.
View newest version in sPHENIX GitHub at line 73 of file DetectorBuilderTests.cpp
Member Function Documentation
void SurfaceGeoIdGenerator::assignGeometryId (Acts::Experimental::IGeometryIdGenerator::GeoIdCache & cache, Acts::Experimental::DetectorVolume & dVolume) const inline final virtual
The virtual interface definition for assigning a geometry id to a detector volume
Parameters
cache is the cache object for e.g. object counting
dVolume the detector volume to assign the geometry id to
Implements Acts::Experimental::IGeometryIdGenerator.
Definition at line 80 of file DetectorBuilderTests.cpp.
View newest version in sPHENIX GitHub at line 80 of file DetectorBuilderTests.cpp
References Acts::enumerate(), physmon_simulation::s, and Acts::GeometryIdentifier::setSensitive().
void SurfaceGeoIdGenerator::assignGeometryId (Acts::Experimental::IGeometryIdGenerator::GeoIdCache & cache, Acts::Experimental::Portal & portal) const inline final virtual
The virtual interface definition for assigning a geometry id to a portal
Parameters
cache is the cache object for e.g. object counting
portal the portal to assign the geometry id to
Implements Acts::Experimental::IGeometryIdGenerator.
Definition at line 90 of file DetectorBuilderTests.cpp.
View newest version in sPHENIX GitHub at line 90 of file DetectorBuilderTests.cpp
void SurfaceGeoIdGenerator::assignGeometryId (Acts::Experimental::IGeometryIdGenerator::GeoIdCache & cache, Acts::Experimental::DetectorVolume & dVolume) const inline final virtual
The virtual interface definition for assigning a geometry id to a detector volume
Parameters
cache is the cache object for e.g. object counting
dVolume the detector volume to assign the geometry id to
Implements Acts::Experimental::IGeometryIdGenerator.
Definition at line 91 of file DetectorVolumeBuilderTests.cpp.
View newest version in sPHENIX GitHub at line 91 of file DetectorVolumeBuilderTests.cpp
References Acts::enumerate(), physmon_simulation::s, and Acts::GeometryIdentifier::setPassive().
void SurfaceGeoIdGenerator::assignGeometryId (Acts::Experimental::IGeometryIdGenerator::GeoIdCache & cache, Acts::Surface & surface) const inline final virtual
The virtual interface definition for assigning a geometry id to a surface.
Parameters
cache is the cache object for e.g. object counting
surface the surface to assign the geometry id to
Implements Acts::Experimental::IGeometryIdGenerator.
Definition at line 94 of file DetectorBuilderTests.cpp.
View newest version in sPHENIX GitHub at line 94 of file DetectorBuilderTests.cpp
void SurfaceGeoIdGenerator::assignGeometryId (Acts::Experimental::IGeometryIdGenerator::GeoIdCache & cache, Acts::Experimental::Portal & portal) const inline final virtual
The virtual interface definition for assigning a geometry id to a portal
Parameters
cache is the cache object for e.g. object counting
portal the portal to assign the geometry id to
Implements Acts::Experimental::IGeometryIdGenerator.
Definition at line 101 of file DetectorVolumeBuilderTests.cpp.
View newest version in sPHENIX GitHub at line 101 of file DetectorVolumeBuilderTests.cpp
void SurfaceGeoIdGenerator::assignGeometryId (Acts::Experimental::IGeometryIdGenerator::GeoIdCache & cache, Acts::Surface & surface) const inline final virtual
The virtual interface definition for assigning a geometry id to a surface.
Parameters
cache is the cache object for e.g. object counting
surface the surface to assign the geometry id to
Implements Acts::Experimental::IGeometryIdGenerator.
Definition at line 105 of file DetectorVolumeBuilderTests.cpp.
View newest version in sPHENIX GitHub at line 105 of file DetectorVolumeBuilderTests.cpp
Acts::Experimental::IGeometryIdGenerator::GeoIdCache SurfaceGeoIdGenerator::generateCache () const inline final virtual
Virtual interface method to generata a geometry id cache.
Returns
a geometry id cache decorated in a std::any object
Implements Acts::Experimental::IGeometryIdGenerator.
Definition at line 75 of file DetectorBuilderTests.cpp.
View newest version in sPHENIX GitHub at line 75 of file DetectorBuilderTests.cpp
Acts::Experimental::IGeometryIdGenerator::GeoIdCache SurfaceGeoIdGenerator::generateCache () const inline final virtual
Virtual interface method to generata a geometry id cache.
Returns
a geometry id cache decorated in a std::any object
Implements Acts::Experimental::IGeometryIdGenerator.
Definition at line 86 of file DetectorVolumeBuilderTests.cpp.
View newest version in sPHENIX GitHub at line 86 of file DetectorVolumeBuilderTests.cpp
The documentation for this class was generated from the following files:
acts/blob/sPHENIX/Tests/UnitTests/Core/Detector/DetectorBuilderTests.cpp
acts/blob/sPHENIX/Tests/UnitTests/Core/Detector/DetectorVolumeBuilderTests.cpp