Analysis Software: analysis/blob/master/cemcRecoAna/offline/draw_hists_3D.C File Reference
draw_hists_3D.C File Reference
#include "sPhenixStyle.C"
#include "sPhenixStyle.h"
Functions
TPad * getPad (int j, int k, int l, float cw, float ch, const int nEBins, const int nCutBins)
void drawCanvas_invMass (TCanvas *c, TH1F *hCorr, int pad_x, int pad_y, TPad *pad, int isEta, float peakPos, float peakW)
void SetHistoStyle (TH1F *histo, int cutBin, int eBin, float low, float hi, int isEta)
void DrawCutLabel (int x, int y, int isEta)
void GetSubtractedDist (TH1F *histOrig, TH1F *histSub, TF1 *invMassFit, TF1 *invMassBG)
void draw_hists_3D (const char *input)
Variables
float eBins [] = {1,2,3,4,5,6,7,8,9,10,11,12,13}
float eBinsEta [] = {12,14,16,18,20}
float eCuts [] = {0.5,0.6,0.7,0.8,0.9,1.,1.1}
float eCutsEta [] = {3,3.5,4,4.5,5,5.5,6}
const int nEtaBins = 5
Function Documentation
void draw_hists_3D (const char * input)
Definition at line 21 of file draw_hists_3D.C.
View newest version in sPHENIX GitHub at line 21 of file draw_hists_3D.C
References AddEntry(), cd(), Draw(), drawCanvas_invMass(), eBins, eBinsEta, eCuts, eCutsEta, check_license::err(), getPad(), GetParameter(), GetSubtractedDist(), GetXaxis(), GetYaxis(), GetZaxis(), add_histos::hist, i, j, k, mass, nEtaBins, ProjectionY, Range(), SetBorderSize(), SetFillStyle(), SetLineColor(), SetLineWidth(), SetLogy(), SetMarkerColor(), SetParameter(), SetParLimits(), SetPoint(), SetPointError(), SetsPhenixStyle(), SetTitle(), sigma, width, and ambiguity_solver_full_chain::x.
void drawCanvas_invMass (TCanvas * c, TH1F * hCorr, int pad_x, int pad_y, TPad * pad, int isEta, float peakPos, float peakW)
Definition at line 648 of file draw_hists_3D.C.
View newest version in sPHENIX GitHub at line 648 of file draw_hists_3D.C
References cd(), Draw(), DrawCutLabel(), CKF_timing_vs_mu::mode, SetHistoStyle(), SetLineColor(), SetLineStyle(), and SetLogy().
Referenced by draw_hists_3D().
void DrawCutLabel (int x, int y, int isEta)
Definition at line 739 of file draw_hists_3D.C.
View newest version in sPHENIX GitHub at line 739 of file draw_hists_3D.C
References cd(), Draw(), eBins, eBinsEta, eCuts, SetTextFont(), and SetTextSize().
Referenced by drawCanvas_invMass().
TPad * getPad (int j, int k, int l, float cw, float ch, const int nEBins, const int nCutBins)
Definition at line 602 of file draw_hists_3D.C.
View newest version in sPHENIX GitHub at line 602 of file draw_hists_3D.C
References h, Acts::UnitConstants::m, SetBottomMargin(), SetLeftMargin(), SetRightMargin(), SetTopMargin(), and xpos.
Referenced by draw_hists_3D().
void GetSubtractedDist (TH1F * histOrig, TH1F * histSub, TF1 * invMassFit, TF1 * invMassBG)
Definition at line 779 of file draw_hists_3D.C.
View newest version in sPHENIX GitHub at line 779 of file draw_hists_3D.C
References GetParameter(), i, SetBinContent(), and SetParameter().
Referenced by draw_hists_3D().
void SetHistoStyle (TH1F * histo, int cutBin, int eBin, float low, float hi, int isEta)
Definition at line 688 of file draw_hists_3D.C.
View newest version in sPHENIX GitHub at line 688 of file draw_hists_3D.C
References GetXaxis(), GetYaxis(), SetLineColor(), SetMarkerColor(), SetMarkerSize(), SetMarkerStyle(), SetStats(), and SetTitle().
Referenced by Draw(), Draw_hitmap(), Draw_hotmap(), and drawCanvas_invMass().
Variable Documentation
float eBins[] = {1,2,3,4,5,6,7,8,9,10,11,12,13}
Definition at line 16 of file draw_hists_3D.C.
View newest version in sPHENIX GitHub at line 16 of file draw_hists_3D.C
Referenced by analyzeClusterEtIso(), draw_hists_3D(), and DrawCutLabel().
float eBinsEta[] = {12,14,16,18,20}
Definition at line 17 of file draw_hists_3D.C.
View newest version in sPHENIX GitHub at line 17 of file draw_hists_3D.C
Referenced by draw_hists_3D(), and DrawCutLabel().
float eCuts[] = {0.5,0.6,0.7,0.8,0.9,1.,1.1}
Definition at line 18 of file draw_hists_3D.C.
View newest version in sPHENIX GitHub at line 18 of file draw_hists_3D.C
Referenced by draw_hists_3D(), and DrawCutLabel().
float eCutsEta[] = {3,3.5,4,4.5,5,5.5,6}
Definition at line 19 of file draw_hists_3D.C.
View newest version in sPHENIX GitHub at line 19 of file draw_hists_3D.C
Referenced by draw_hists_3D().
const int nEtaBins = 5
Definition at line 20 of file draw_hists_3D.C.
View newest version in sPHENIX GitHub at line 20 of file draw_hists_3D.C
Referenced by Acts::Python::addExampleAlgorithms(), cemcReco::cemcReco(), draw_hists_3D(), jetHistogrammer::End(), pi0Efficiency::End(), cemcReco::End(), Acts::TrackSelector::EtaBinnedConfig::getCuts(), jetHistogrammer::getEtaBin(), pi0Efficiency::getEtaBin(), cemcReco::getEtaBin(), STrackMatcherComparatorHistDef::GetVecHistBins(), jetHistogrammer::Init(), pi0Efficiency::Init(), cemcReco::Init(), SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::InitHists(), STrackCutStudy::InitHists(), main(), MakeNewMatcherPlots(), MakeNewMatcherTuplePlots(), MakeOldEvaluatorPlots(), pi0Efficiency::pi0Efficiency(), jetHistogrammer::process_event(), pi0Efficiency::process_event(), cemcReco::process_event(), and jetHistogrammer::~jetHistogrammer().