Analysis Software: acts/blob/sPHENIX/Tests/UnitTests/Plugins/ActSVG/IndexedSurfacesSvgConverterTests.cpp File Reference
IndexedSurfacesSvgConverterTests.cpp File Reference
#include <boost/test/unit_test.hpp>
#include "Acts/Definitions/Algebra.hpp"
#include "Acts/Detector/detail/GridAxisGenerators.hpp"
#include "Acts/Detector/detail/IndexedGridFiller.hpp"
#include "Acts/Detector/detail/IndexedSurfacesGenerator.hpp"
#include "Acts/Geometry/GeometryContext.hpp"
#include "Acts/Geometry/GeometryIdentifier.hpp"
#include "Acts/Plugins/ActSVG/IndexedSurfacesSvgConverter.hpp"
#include "Acts/Surfaces/DiscSurface.hpp"
#include "Acts/Surfaces/RadialBounds.hpp"
#include "Acts/Tests/CommonHelpers/CylindricalTrackingGeometry.hpp"
#include "Acts/Utilities/detail/Grid.hpp"
#include <tuple>
Functions
IndexedSurfacesConverter::Options generateDrawOptions ()
BOOST_AUTO_TEST_CASE (RingDisc1D)
BOOST_AUTO_TEST_CASE (RingDisc1DWithSupport)
BOOST_AUTO_TEST_CASE (RingDisc2D)
BOOST_AUTO_TEST_CASE (RingDisc2DFine)
BOOST_AUTO_TEST_CASE (RingDisc2DFineExpanded)
BOOST_AUTO_TEST_CASE (Cylinder2D)
Variables
GeometryContext tContext
CylindricalTrackingGeometry cGeometry = CylindricalTrackingGeometry(tContext)
auto drawOptions = generateDrawOptions()
Function Documentation
BOOST_AUTO_TEST_CASE (RingDisc1D)
Definition at line 71 of file IndexedSurfacesSvgConverterTests.cpp.
View newest version in sPHENIX GitHub at line 71 of file IndexedSurfacesSvgConverterTests.cpp
References Acts::binPhi, cGeometry, Acts::Svg::DetectorConverter::convert(), drawOptions, Acts::Test::CylindricalTrackingGeometry::surfacesRing(), tContext, Acts::Svg::toFile(), physmon_ckf_tracking::u, and Acts::Svg::View::xy().
BOOST_AUTO_TEST_CASE (RingDisc1DWithSupport)
Definition at line 91 of file IndexedSurfacesSvgConverterTests.cpp.
View newest version in sPHENIX GitHub at line 91 of file IndexedSurfacesSvgConverterTests.cpp
References Acts::binPhi, cGeometry, Acts::Svg::DetectorConverter::convert(), drawOptions, testing::internal::move(), rBounds, Acts::Test::CylindricalTrackingGeometry::surfacesRing(), tContext, Acts::Svg::toFile(), physmon_ckf_tracking::u, and Acts::Svg::View::xy().
BOOST_AUTO_TEST_CASE (RingDisc2D)
Definition at line 116 of file IndexedSurfacesSvgConverterTests.cpp.
View newest version in sPHENIX GitHub at line 116 of file IndexedSurfacesSvgConverterTests.cpp
References Acts::binPhi, Acts::binR, cGeometry, Acts::Svg::DetectorConverter::convert(), drawOptions, Acts::Test::CylindricalTrackingGeometry::surfacesRing(), tContext, Acts::Svg::toFile(), physmon_ckf_tracking::u, and Acts::Svg::View::xy().
BOOST_AUTO_TEST_CASE (RingDisc2DFine)
Definition at line 144 of file IndexedSurfacesSvgConverterTests.cpp.
View newest version in sPHENIX GitHub at line 144 of file IndexedSurfacesSvgConverterTests.cpp
References Acts::binPhi, Acts::binR, cGeometry, Acts::Svg::DetectorConverter::convert(), drawOptions, Acts::Test::CylindricalTrackingGeometry::surfacesRing(), tContext, Acts::Svg::toFile(), physmon_ckf_tracking::u, and Acts::Svg::View::xy().
BOOST_AUTO_TEST_CASE (RingDisc2DFineExpanded)
Definition at line 176 of file IndexedSurfacesSvgConverterTests.cpp.
View newest version in sPHENIX GitHub at line 176 of file IndexedSurfacesSvgConverterTests.cpp
References Acts::binPhi, Acts::binR, cGeometry, Acts::Svg::DetectorConverter::convert(), drawOptions, Acts::Test::CylindricalTrackingGeometry::surfacesRing(), tContext, Acts::Svg::toFile(), physmon_ckf_tracking::u, and Acts::Svg::View::xy().
BOOST_AUTO_TEST_CASE (Cylinder2D)
Definition at line 208 of file IndexedSurfacesSvgConverterTests.cpp.
View newest version in sPHENIX GitHub at line 208 of file IndexedSurfacesSvgConverterTests.cpp
References Acts::binPhi, Acts::binZ, cGeometry, Acts::Svg::DetectorConverter::convert(), drawOptions, Acts::Test::CylindricalTrackingGeometry::surfacesCylinder(), tContext, Acts::Svg::toFile(), physmon_ckf_tracking::u, and Acts::Svg::View::zphi().
IndexedSurfacesConverter::Options generateDrawOptions ()
Definition at line 34 of file IndexedSurfacesSvgConverterTests.cpp.
View newest version in sPHENIX GitHub at line 34 of file IndexedSurfacesSvgConverterTests.cpp
References Acts::Svg::Style::fillColor, Acts::Svg::Style::fillOpacity, Acts::Svg::IndexedSurfacesConverter::Options::gridOptions, Acts::Svg::Style::highlightColor, Acts::Svg::Style::highlights, Acts::Svg::Style::highlightStrokeColor, Acts::Svg::Style::highlightStrokeWidth, Acts::Svg::Style::nSegments, Acts::Svg::Style::strokeColor, Acts::Svg::Style::strokeWidth, Acts::Svg::GridConverter::Options::style, Acts::Svg::IndexedSurfacesConverter::Options::surfaceStyles, and physmon_ckf_tracking::u.
Variable Documentation
CylindricalTrackingGeometry cGeometry = CylindricalTrackingGeometry(tContext)
Definition at line 32 of file IndexedSurfacesSvgConverterTests.cpp.
View newest version in sPHENIX GitHub at line 32 of file IndexedSurfacesSvgConverterTests.cpp
auto drawOptions = generateDrawOptions()
Definition at line 67 of file IndexedSurfacesSvgConverterTests.cpp.
View newest version in sPHENIX GitHub at line 67 of file IndexedSurfacesSvgConverterTests.cpp
Referenced by BOOST_AUTO_TEST_CASE(), and boundParamResolution().
GeometryContext tContext
Definition at line 31 of file IndexedSurfacesSvgConverterTests.cpp.
View newest version in sPHENIX GitHub at line 31 of file IndexedSurfacesSvgConverterTests.cpp