Analysis Software: MbdCalib Class Reference
MbdCalib Class Reference
#include <coresoftware/blob/master/offline/packages/mbd/MbdCalib.h>
Public Member Functions
MbdCalib ()
virtual ~MbdCalib ()
float get_qgain (const int ipmt) const
float get_tq0 (const int ipmt) const
int get_sampmax (const int ifeech) const
std::vector< float > get_shape (const int ifeech) const
std::vector< float > get_sherr (const int ifeech) const
int Download_Gains (const std::string &dbfile)
int Download_TQT0 (const std::string &dbfile)
int Download_TTT0 (const std::string &dbfile)
int Download_Slew (const std::string &dbfile)
int Download_SampMax (const std::string &dbfile)
int Download_Shapes (const std::string &dbfile)
int Download_All ()
int Write_CDB_SampMax (const std::string &dbfile)
int Write_CDB_Shapes (const std::string &dbfile)
int Write_CDB_All ()
int Write_SampMax (const std::string &dbfile)
int Write_TQT0 (const std::string &dbfile)
void Reset ()
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Print (const std::string &what="ALL") const
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Private Attributes
CDBInterface * _cdb {nullptr}
recoConsts * _rc {nullptr}
std::unique_ptr< MbdGeom > _mbdgeom {nullptr}
int _status {0}
std::string _dbfilename
std::array< float,
MbdDefs::BBC_N_PMT > _qfit_integ {}
std::array< float,
MbdDefs::BBC_N_PMT > _qfit_mpv {}
std::array< float,
MbdDefs::BBC_N_PMT > _qfit_sigma {}
std::array< float,
MbdDefs::BBC_N_PMT > _qfit_integerr {}
std::array< float,
MbdDefs::BBC_N_PMT > _qfit_mpverr {}
std::array< float,
MbdDefs::BBC_N_PMT > _qfit_sigmaerr {}
std::array< float,
MbdDefs::BBC_N_PMT > _qfit_chi2ndf {}
std::array< float,
MbdDefs::BBC_N_PMT > _ttfit_t0mean {}
std::array< float,
MbdDefs::BBC_N_PMT > _ttfit_t0meanerr {}
std::array< float,
MbdDefs::BBC_N_PMT > _ttfit_t0sigma {}
std::array< float,
MbdDefs::BBC_N_PMT > _ttfit_t0sigmaerr {}
std::array< float,
MbdDefs::BBC_N_PMT > _tqfit_t0mean {}
std::array< float,
MbdDefs::BBC_N_PMT > _tqfit_t0meanerr {}
std::array< float,
MbdDefs::BBC_N_PMT > _tqfit_t0sigma {}
std::array< float,
MbdDefs::BBC_N_PMT > _tqfit_t0sigmaerr {}
std::array< int,
MbdDefs::BBC_N_FEECH > _slew_npts {}
std::array< float,
MbdDefs::BBC_N_FEECH > _slew_minrange {}
std::array< float,
MbdDefs::BBC_N_FEECH > _slew_maxrange {}
std::array< std::vector< float >
, MbdDefs::BBC_N_FEECH > _slew_y {}
std::array< int,
MbdDefs::BBC_N_FEECH > _sampmax {}
int do_templatefit {0}
std::array< int,
MbdDefs::BBC_N_FEECH > _shape_npts {}
std::array< float,
MbdDefs::BBC_N_FEECH > _shape_minrange {}
std::array< float,
MbdDefs::BBC_N_FEECH > _shape_maxrange {}
std::array< std::vector< float >
, MbdDefs::BBC_N_FEECH > _shape_y {}
std::array< int,
MbdDefs::BBC_N_FEECH > _sherr_npts {}
std::array< float,
MbdDefs::BBC_N_FEECH > _sherr_minrange {}
std::array< float,
MbdDefs::BBC_N_FEECH > _sherr_maxrange {}
std::array< std::vector< float >
, MbdDefs::BBC_N_FEECH > _sherr_yerr {}
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = std::numeric_limits<int>::max() - 10
}
Protected Member Functions inherited from Fun4AllBase
Fun4AllBase (const std::string &name="NONAME")
Detailed Description
Definition at line 23 of file MbdCalib.h.
View newest version in sPHENIX GitHub at line 23 of file MbdCalib.h
Constructor & Destructor Documentation
MbdCalib::MbdCalib ()
Definition at line 20 of file MbdCalib.cc.
View newest version in sPHENIX GitHub at line 20 of file MbdCalib.cc
References _mbdgeom, _rc, do_templatefit, PHFlag::FlagExist(), PHFlag::get_IntFlag(), recoConsts::instance(), and Reset().
virtual MbdCalib::~MbdCalib () inline virtual
Definition at line 31 of file MbdCalib.h.
View newest version in sPHENIX GitHub at line 31 of file MbdCalib.h
Member Function Documentation
int MbdCalib::Download_All ()
Definition at line 36 of file MbdCalib.cc.
View newest version in sPHENIX GitHub at line 36 of file MbdCalib.cc
References _cdb, _rc, _status, do_templatefit, Download_Gains(), Download_SampMax(), Download_Shapes(), Download_TQT0(), PHFlag::FlagExist(), PHFlag::get_StringFlag(), PHFlag::get_uint64Flag(), CDBInterface::getUrl(), CDBInterface::instance(), PHWHERE, and Fun4AllBase::Verbosity().
Referenced by MbdEvent::InitRun().
int MbdCalib::Download_Gains (const std::string & dbfile)
Definition at line 124 of file MbdCalib.cc.
View newest version in sPHENIX GitHub at line 124 of file MbdCalib.cc
References _qfit_chi2ndf, _qfit_integ, _qfit_integerr, _qfit_mpv, _qfit_mpverr, _qfit_sigma, _qfit_sigmaerr, _status, CDBTTree::GetFloatValue(), infile, CDBTTree::LoadCalibrations(), MbdDefs::MBD_N_PMT, path, PHWHERE, and Fun4AllBase::Verbosity().
Referenced by Download_All().
int MbdCalib::Download_SampMax (const std::string & dbfile)
Definition at line 339 of file MbdCalib.cc.
View newest version in sPHENIX GitHub at line 339 of file MbdCalib.cc
References _sampmax, _status, feech, CDBTTree::GetIntValue(), infile, CDBTTree::LoadCalibrations(), MbdDefs::MBD_N_FEECH, path, PHWHERE, and Fun4AllBase::Verbosity().
Referenced by Download_All().
int MbdCalib::Download_Shapes (const std::string & dbfile)
Definition at line 524 of file MbdCalib.cc.
View newest version in sPHENIX GitHub at line 524 of file MbdCalib.cc
References _mbdgeom, _shape_maxrange, _shape_minrange, _shape_npts, _shape_y, _sherr_maxrange, _sherr_minrange, _sherr_npts, _sherr_yerr, _status, CDBTTree::GetFloatValue(), CDBTTree::GetIntValue(), infile, CDBTTree::LoadCalibrations(), MbdDefs::MBD_N_FEECH, path, PHWHERE, shape(), and Fun4AllBase::Verbosity().
Referenced by Download_All().
int MbdCalib::Download_Slew (const std::string & dbfile)
Definition at line 397 of file MbdCalib.cc.
View newest version in sPHENIX GitHub at line 397 of file MbdCalib.cc
References _mbdgeom, _sherr_maxrange, _sherr_minrange, _sherr_npts, _sherr_yerr, _slew_maxrange, _slew_minrange, _slew_npts, _slew_y, _status, CDBTTree::GetFloatValue(), CDBTTree::GetIntValue(), infile, CDBTTree::LoadCalibrations(), MbdDefs::MBD_N_FEECH, path, PHWHERE, and Fun4AllBase::Verbosity().
int MbdCalib::Download_TQT0 (const std::string & dbfile)
Definition at line 199 of file MbdCalib.cc.
View newest version in sPHENIX GitHub at line 199 of file MbdCalib.cc
References _status, _tqfit_t0mean, _tqfit_t0meanerr, _tqfit_t0sigma, _tqfit_t0sigmaerr, CDBTTree::GetFloatValue(), infile, CDBTTree::LoadCalibrations(), MbdDefs::MBD_N_PMT, path, PHWHERE, and Fun4AllBase::Verbosity().
Referenced by Download_All().
int MbdCalib::Download_TTT0 (const std::string & dbfile)
Definition at line 269 of file MbdCalib.cc.
View newest version in sPHENIX GitHub at line 269 of file MbdCalib.cc
References _status, _ttfit_t0mean, _ttfit_t0meanerr, _ttfit_t0sigma, _ttfit_t0sigmaerr, CDBTTree::GetFloatValue(), infile, CDBTTree::LoadCalibrations(), MbdDefs::MBD_N_PMT, path, PHWHERE, and Fun4AllBase::Verbosity().
float MbdCalib::get_qgain (const int ipmt) const inline
Definition at line 33 of file MbdCalib.h.
View newest version in sPHENIX GitHub at line 33 of file MbdCalib.h
References _qfit_mpv.
Referenced by MbdEvent::SetRawData().
int MbdCalib::get_sampmax (const int ifeech) const inline
Definition at line 35 of file MbdCalib.h.
View newest version in sPHENIX GitHub at line 35 of file MbdCalib.h
References _sampmax.
Referenced by MbdEvent::InitRun(), and MbdEvent::SetRawData().
std::vector<float> MbdCalib::get_shape (const int ifeech) const inline
Definition at line 36 of file MbdCalib.h.
View newest version in sPHENIX GitHub at line 36 of file MbdCalib.h
References _shape_y.
Referenced by MbdEvent::InitRun().
std::vector<float> MbdCalib::get_sherr (const int ifeech) const inline
Definition at line 37 of file MbdCalib.h.
View newest version in sPHENIX GitHub at line 37 of file MbdCalib.h
References _sherr_yerr.
Referenced by MbdEvent::InitRun().
float MbdCalib::get_tq0 (const int ipmt) const inline
Definition at line 34 of file MbdCalib.h.
View newest version in sPHENIX GitHub at line 34 of file MbdCalib.h
References _tqfit_t0mean.
Referenced by MbdEvent::SetRawData().
void MbdCalib::Reset ()
Definition at line 843 of file MbdCalib.cc.
View newest version in sPHENIX GitHub at line 843 of file MbdCalib.cc
References _qfit_chi2ndf, _qfit_integ, _qfit_integerr, _qfit_mpv, _qfit_mpverr, _qfit_sigma, _qfit_sigmaerr, _sampmax, _tqfit_t0mean, _tqfit_t0meanerr, _tqfit_t0sigma, and _tqfit_t0sigmaerr.
Referenced by MbdCalib().
int MbdCalib::Write_CDB_All ()
Definition at line 838 of file MbdCalib.cc.
View newest version in sPHENIX GitHub at line 838 of file MbdCalib.cc
int MbdCalib::Write_CDB_SampMax (const std::string & dbfile)
Definition at line 712 of file MbdCalib.cc.
View newest version in sPHENIX GitHub at line 712 of file MbdCalib.cc
References _sampmax, and MbdDefs::MBD_N_FEECH.
int MbdCalib::Write_CDB_Shapes (const std::string & dbfile)
Definition at line 770 of file MbdCalib.cc.
View newest version in sPHENIX GitHub at line 770 of file MbdCalib.cc
References _mbdgeom, _sampmax, _shape_maxrange, _shape_minrange, _shape_npts, _shape_y, _sherr_maxrange, _sherr_minrange, _sherr_npts, _sherr_yerr, and MbdDefs::MBD_N_FEECH.
int MbdCalib::Write_SampMax (const std::string & dbfile)
Definition at line 743 of file MbdCalib.cc.
View newest version in sPHENIX GitHub at line 743 of file MbdCalib.cc
References _sampmax, and MbdDefs::MBD_N_PMT.
int MbdCalib::Write_TQT0 (const std::string & dbfile)
Definition at line 756 of file MbdCalib.cc.
View newest version in sPHENIX GitHub at line 756 of file MbdCalib.cc
References _tqfit_t0mean, _tqfit_t0meanerr, _tqfit_t0sigma, _tqfit_t0sigmaerr, and MbdDefs::MBD_N_PMT.
Member Data Documentation
CDBInterface* MbdCalib::_cdb {nullptr} private
Definition at line 60 of file MbdCalib.h.
View newest version in sPHENIX GitHub at line 60 of file MbdCalib.h
Referenced by Download_All().
std::string MbdCalib::_dbfilename private
Definition at line 68 of file MbdCalib.h.
View newest version in sPHENIX GitHub at line 68 of file MbdCalib.h
std::unique_ptr<MbdGeom> MbdCalib::_mbdgeom {nullptr} private
Definition at line 63 of file MbdCalib.h.
View newest version in sPHENIX GitHub at line 63 of file MbdCalib.h
Referenced by Download_Shapes(), Download_Slew(), MbdCalib(), and Write_CDB_Shapes().
std::array<float, MbdDefs::BBC_N_PMT> MbdCalib::_qfit_chi2ndf {} private
Definition at line 77 of file MbdCalib.h.
View newest version in sPHENIX GitHub at line 77 of file MbdCalib.h
Referenced by Download_Gains(), and Reset().
std::array<float, MbdDefs::BBC_N_PMT> MbdCalib::_qfit_integ {} private
Definition at line 71 of file MbdCalib.h.
View newest version in sPHENIX GitHub at line 71 of file MbdCalib.h
Referenced by Download_Gains(), and Reset().
std::array<float, MbdDefs::BBC_N_PMT> MbdCalib::_qfit_integerr {} private
Definition at line 74 of file MbdCalib.h.
View newest version in sPHENIX GitHub at line 74 of file MbdCalib.h
Referenced by Download_Gains(), and Reset().
std::array<float, MbdDefs::BBC_N_PMT> MbdCalib::_qfit_mpv {} private
Definition at line 72 of file MbdCalib.h.
View newest version in sPHENIX GitHub at line 72 of file MbdCalib.h
Referenced by Download_Gains(), get_qgain(), and Reset().
std::array<float, MbdDefs::BBC_N_PMT> MbdCalib::_qfit_mpverr {} private
Definition at line 75 of file MbdCalib.h.
View newest version in sPHENIX GitHub at line 75 of file MbdCalib.h
Referenced by Download_Gains(), and Reset().
std::array<float, MbdDefs::BBC_N_PMT> MbdCalib::_qfit_sigma {} private
Definition at line 73 of file MbdCalib.h.
View newest version in sPHENIX GitHub at line 73 of file MbdCalib.h
Referenced by Download_Gains(), and Reset().
std::array<float, MbdDefs::BBC_N_PMT> MbdCalib::_qfit_sigmaerr {} private
Definition at line 76 of file MbdCalib.h.
View newest version in sPHENIX GitHub at line 76 of file MbdCalib.h
Referenced by Download_Gains(), and Reset().
recoConsts* MbdCalib::_rc {nullptr} private
Definition at line 61 of file MbdCalib.h.
View newest version in sPHENIX GitHub at line 61 of file MbdCalib.h
Referenced by Download_All(), and MbdCalib().
std::array<int, MbdDefs::BBC_N_FEECH> MbdCalib::_sampmax {} private
Definition at line 98 of file MbdCalib.h.
View newest version in sPHENIX GitHub at line 98 of file MbdCalib.h
Referenced by Download_SampMax(), get_sampmax(), Reset(), Write_CDB_SampMax(), Write_CDB_Shapes(), and Write_SampMax().
std::array<float, MbdDefs::BBC_N_FEECH> MbdCalib::_shape_maxrange {} private
Definition at line 104 of file MbdCalib.h.
View newest version in sPHENIX GitHub at line 104 of file MbdCalib.h
Referenced by Download_Shapes(), and Write_CDB_Shapes().
std::array<float, MbdDefs::BBC_N_FEECH> MbdCalib::_shape_minrange {} private
Definition at line 103 of file MbdCalib.h.
View newest version in sPHENIX GitHub at line 103 of file MbdCalib.h
Referenced by Download_Shapes(), and Write_CDB_Shapes().
std::array<int, MbdDefs::BBC_N_FEECH> MbdCalib::_shape_npts {} private
Definition at line 102 of file MbdCalib.h.
View newest version in sPHENIX GitHub at line 102 of file MbdCalib.h
Referenced by Download_Shapes(), and Write_CDB_Shapes().
std::array<std::vector<float>, MbdDefs::BBC_N_FEECH> MbdCalib::_shape_y {} private
Definition at line 105 of file MbdCalib.h.
View newest version in sPHENIX GitHub at line 105 of file MbdCalib.h
Referenced by Download_Shapes(), get_shape(), and Write_CDB_Shapes().
std::array<float, MbdDefs::BBC_N_FEECH> MbdCalib::_sherr_maxrange {} private
Definition at line 109 of file MbdCalib.h.
View newest version in sPHENIX GitHub at line 109 of file MbdCalib.h
Referenced by Download_Shapes(), Download_Slew(), and Write_CDB_Shapes().
std::array<float, MbdDefs::BBC_N_FEECH> MbdCalib::_sherr_minrange {} private
Definition at line 108 of file MbdCalib.h.
View newest version in sPHENIX GitHub at line 108 of file MbdCalib.h
Referenced by Download_Shapes(), Download_Slew(), and Write_CDB_Shapes().
std::array<int, MbdDefs::BBC_N_FEECH> MbdCalib::_sherr_npts {} private
Definition at line 107 of file MbdCalib.h.
View newest version in sPHENIX GitHub at line 107 of file MbdCalib.h
Referenced by Download_Shapes(), Download_Slew(), and Write_CDB_Shapes().
std::array<std::vector<float>, MbdDefs::BBC_N_FEECH> MbdCalib::_sherr_yerr {} private
Definition at line 110 of file MbdCalib.h.
View newest version in sPHENIX GitHub at line 110 of file MbdCalib.h
Referenced by Download_Shapes(), Download_Slew(), get_sherr(), and Write_CDB_Shapes().
std::array<float, MbdDefs::BBC_N_FEECH> MbdCalib::_slew_maxrange {} private
Definition at line 94 of file MbdCalib.h.
View newest version in sPHENIX GitHub at line 94 of file MbdCalib.h
Referenced by Download_Slew().
std::array<float, MbdDefs::BBC_N_FEECH> MbdCalib::_slew_minrange {} private
Definition at line 93 of file MbdCalib.h.
View newest version in sPHENIX GitHub at line 93 of file MbdCalib.h
Referenced by Download_Slew().
std::array<int, MbdDefs::BBC_N_FEECH> MbdCalib::_slew_npts {} private
Definition at line 92 of file MbdCalib.h.
View newest version in sPHENIX GitHub at line 92 of file MbdCalib.h
Referenced by Download_Slew().
std::array<std::vector<float>, MbdDefs::BBC_N_FEECH> MbdCalib::_slew_y {} private
Definition at line 95 of file MbdCalib.h.
View newest version in sPHENIX GitHub at line 95 of file MbdCalib.h
Referenced by Download_Slew().
int MbdCalib::_status {0} private
Definition at line 65 of file MbdCalib.h.
View newest version in sPHENIX GitHub at line 65 of file MbdCalib.h
Referenced by Download_All(), Download_Gains(), Download_SampMax(), Download_Shapes(), Download_Slew(), Download_TQT0(), and Download_TTT0().
std::array<float, MbdDefs::BBC_N_PMT> MbdCalib::_tqfit_t0mean {} private
Definition at line 86 of file MbdCalib.h.
View newest version in sPHENIX GitHub at line 86 of file MbdCalib.h
Referenced by Download_TQT0(), get_tq0(), Reset(), and Write_TQT0().
std::array<float, MbdDefs::BBC_N_PMT> MbdCalib::_tqfit_t0meanerr {} private
Definition at line 87 of file MbdCalib.h.
View newest version in sPHENIX GitHub at line 87 of file MbdCalib.h
Referenced by Download_TQT0(), Reset(), and Write_TQT0().
std::array<float, MbdDefs::BBC_N_PMT> MbdCalib::_tqfit_t0sigma {} private
Definition at line 88 of file MbdCalib.h.
View newest version in sPHENIX GitHub at line 88 of file MbdCalib.h
Referenced by Download_TQT0(), Reset(), and Write_TQT0().
std::array<float, MbdDefs::BBC_N_PMT> MbdCalib::_tqfit_t0sigmaerr {} private
Definition at line 89 of file MbdCalib.h.
View newest version in sPHENIX GitHub at line 89 of file MbdCalib.h
Referenced by Download_TQT0(), Reset(), and Write_TQT0().
std::array<float, MbdDefs::BBC_N_PMT> MbdCalib::_ttfit_t0mean {} private
Definition at line 80 of file MbdCalib.h.
View newest version in sPHENIX GitHub at line 80 of file MbdCalib.h
Referenced by Download_TTT0().
std::array<float, MbdDefs::BBC_N_PMT> MbdCalib::_ttfit_t0meanerr {} private
Definition at line 81 of file MbdCalib.h.
View newest version in sPHENIX GitHub at line 81 of file MbdCalib.h
Referenced by Download_TTT0().
std::array<float, MbdDefs::BBC_N_PMT> MbdCalib::_ttfit_t0sigma {} private
Definition at line 82 of file MbdCalib.h.
View newest version in sPHENIX GitHub at line 82 of file MbdCalib.h
Referenced by Download_TTT0().
std::array<float, MbdDefs::BBC_N_PMT> MbdCalib::_ttfit_t0sigmaerr {} private
Definition at line 83 of file MbdCalib.h.
View newest version in sPHENIX GitHub at line 83 of file MbdCalib.h
Referenced by Download_TTT0().
int MbdCalib::do_templatefit {0} private
Definition at line 101 of file MbdCalib.h.
View newest version in sPHENIX GitHub at line 101 of file MbdCalib.h
Referenced by Download_All(), and MbdCalib().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/mbd/MbdCalib.h
coresoftware/blob/master/offline/packages/mbd/MbdCalib.cc