Analysis Software: Acts::ApproachDescriptor Class Reference
Acts::ApproachDescriptor Class Reference abstract
#include <acts/blob/sPHENIX/Core/include/Acts/Geometry/ApproachDescriptor.hpp>
Public Member Functions
ApproachDescriptor ()=default
virtual ~ApproachDescriptor ()=default
virtual void registerLayer (const Layer &lay)=0
Register Layer Links the layer to the approach surfaces.
virtual SurfaceIntersection approachSurface (const GeometryContext &gctx, const Vector3 &position, const Vector3 &direction, const BoundaryCheck &bcheck, double pLimit, double oLimit, double tolerance) const =0
Get the surface on approach.
virtual const std::vector
< const Surface * > & containedSurfaces () const =0
virtual std::vector< const
Surface * > & containedSurfaces ()=0
Non-const version.
Detailed Description
Virtual base class to decide and return which approaching surface to be taken, the surfaces are std::shared_ptr, as they can be the boundary surfaces of the representingVolume of the Layer
Definition at line 29 of file ApproachDescriptor.hpp.
View newest version in sPHENIX GitHub at line 29 of file ApproachDescriptor.hpp
Constructor & Destructor Documentation
Acts::ApproachDescriptor::ApproachDescriptor () default
virtual Acts::ApproachDescriptor::~ApproachDescriptor () virtual default
Member Function Documentation
virtual SurfaceIntersection Acts::ApproachDescriptor::approachSurface (const GeometryContext & gctx, const Vector3 & position, const Vector3 & direction, const BoundaryCheck & bcheck, double pLimit, double oLimit, double tolerance) const pure virtual
Get the surface on approach.
Parameters
gctx The current geometry context object, e.g. alignment
position is the position from start of the search
direction is the direction at the start of the search
bcheck is the boundary check directive
pLimit The path limit
oLimit The overstep limit
tolerance The surface tolerance
Returns
is a surface intersection
Implemented in Acts::GenericApproachDescriptor.
virtual const std::vector<const Surface*>& Acts::ApproachDescriptor::containedSurfaces () const pure virtual
Get all the contained surfaces
Returns
all contained surfaces of this approach descriptor
Implemented in Acts::GenericApproachDescriptor.
Referenced by Acts::addLayerProtoMaterial(), and ActsExamples::RootMaterialWriter::collectMaterial().
virtual std::vector<const Surface*>& Acts::ApproachDescriptor::containedSurfaces () pure virtual
Non-const version.
Implemented in Acts::GenericApproachDescriptor.
virtual void Acts::ApproachDescriptor::registerLayer (const Layer & lay) pure virtual
Register Layer Links the layer to the approach surfaces.
Parameters
lay is the layer to be assigned
Implemented in Acts::GenericApproachDescriptor.
Referenced by Acts::CylinderLayer::CylinderLayer(), Acts::DiscLayer::DiscLayer(), and Acts::PlaneLayer::PlaneLayer().
The documentation for this class was generated from the following file:
acts/blob/sPHENIX/Core/include/Acts/Geometry/ApproachDescriptor.hpp