Analysis Software: analysis/blob/master/EMCal_pi0_Calib_2023/macros/doTscFit.C File Reference
doTscFit.C File Reference
#include <fun4all/SubsysReco.h>
#include <fun4all/Fun4AllServer.h>
#include <fun4all/Fun4AllInputManager.h>
#include <fun4allraw/Fun4AllPrdfInputManager.h>
#include <fun4all/Fun4AllDstInputManager.h>
#include <fun4all/Fun4AllDstOutputManager.h>
#include <fun4all/Fun4AllUtils.h>
#include <cdbobjects/CDBTTree.h>
#include "TowerInfo.h"
#include "TowerInfoDefs.h"
#include <litecaloeval/LiteCaloEval.h>
#include <caloreco/CaloTowerCalib.h>
#include <caloreco/RawClusterBuilderTemplate.h>
#include <phool/recoConsts.h>
#include "/sphenix/u/bseidlitz/work/macros/calibrations/calo/calib_nov23/towerslope/TSCtoCDBTTree.C"
Functions
void mergeCDBTTrees (const char *infile1, const char *infile2, const char *outputfile)
void doTscFit (const std::string &hist_fname="parallel_test/combine_out/out1.root", const std::string &calib_fname="parallel_test/local_cdb_copy.root")
Function Documentation
void doTscFit (const std::string & hist_fname = "parallel_test/combine_out/out1.root", const std::string & calib_fname = "parallel_test/local_cdb_copy.root")
Definition at line 36 of file doTscFit.C.
View newest version in sPHENIX GitHub at line 36 of file doTscFit.C
References LiteCaloEval::CaloType(), LiteCaloEval::CEMC, LiteCaloEval::FitRelativeShifts(), LiteCaloEval::Get_Histos(), LiteCaloEval::m_mymaxbin, LiteCaloEval::m_myminbin, mergeCDBTTrees(), Acts::Test::pos, LiteCaloEval::setFitMax(), LiteCaloEval::setFitMin(), and TSCtoCDBTTree().
void mergeCDBTTrees (const char * infile1, const char * infile2, const char * outputfile)
Definition at line 67 of file doTscFit.C.
View newest version in sPHENIX GitHub at line 67 of file doTscFit.C
References CDBTTree::Commit(), TowerInfoDefs::encode_emcal(), CDBTTree::GetFloatValue(), i, j, CDBTTree::SetFloatValue(), and CDBTTree::WriteCDBTTree().
Referenced by doTscFit(), and tsdst_plus_tsfit().