Analysis Software: ClusterSequence Class Reference
ClusterSequence Class Reference
#include <JETSCAPE/blob/main/external_packages/fjcore.hh>
Classes
class _Line
class _Parabola
struct BriefJet
struct EEBriefJet
class Extras
struct history_element
struct Tile
class TiledJet
Public Types
enum JetType { Invalid =-3, InexistentParent = -2, BeamJet = -1 }
typedef ClusterSequenceStructure StructureType
Public Member Functions
ClusterSequence ()
template<class L >
ClusterSequence (const std::vector< L > &pseudojets, const JetDefinition &jet_def, const bool &writeout_combinations=false)
ClusterSequence (const ClusterSequence &cs)
ClusterSequence & operator= (const ClusterSequence &cs)
virtual ~ClusterSequence ()
std::vector< PseudoJet > inclusive_jets (const double ptmin=0.0) const
int n_exclusive_jets (const double dcut) const
std::vector< PseudoJet > exclusive_jets (const double dcut) const
std::vector< PseudoJet > exclusive_jets (const int njets) const
std::vector< PseudoJet > exclusive_jets_up_to (const int njets) const
double exclusive_dmerge (const int njets) const
double exclusive_dmerge_max (const int njets) const
double exclusive_ymerge (int njets) const
double exclusive_ymerge_max (int njets) const
int n_exclusive_jets_ycut (double ycut) const
std::vector< PseudoJet > exclusive_jets_ycut (double ycut) const
std::vector< PseudoJet > exclusive_subjets (const PseudoJet &jet, const double dcut) const
int n_exclusive_subjets (const PseudoJet &jet, const double dcut) const
std::vector< PseudoJet > exclusive_subjets (const PseudoJet &jet, int nsub) const
std::vector< PseudoJet > exclusive_subjets_up_to (const PseudoJet &jet, int nsub) const
double exclusive_subdmerge (const PseudoJet &jet, int nsub) const
double exclusive_subdmerge_max (const PseudoJet &jet, int nsub) const
double Q () const
double Q2 () const
bool object_in_jet (const PseudoJet &object, const PseudoJet &jet) const
bool has_parents (const PseudoJet &jet, PseudoJet &parent1, PseudoJet &parent2) const
bool has_child (const PseudoJet &jet, PseudoJet &child) const
bool has_child (const PseudoJet &jet, const PseudoJet *&childp) const
bool has_partner (const PseudoJet &jet, PseudoJet &partner) const
std::vector< PseudoJet > constituents (const PseudoJet &jet) const
void print_jets_for_root (const std::vector< PseudoJet > &jets, std::ostream &ostr=std::cout) const
void print_jets_for_root (const std::vector< PseudoJet > &jets, const std::string &filename, const std::string &comment="") const
void add_constituents (const PseudoJet &jet, std::vector< PseudoJet > &subjet_vector) const
Strategy strategy_used () const
std::string strategy_string () const
std::string strategy_string (Strategy strategy_in) const
const JetDefinition & jet_def () const
void delete_self_when_unused ()
bool will_delete_self_when_unused () const
void signal_imminent_self_deletion () const
double jet_scale_for_algorithm (const PseudoJet &jet) const
void plugin_record_ij_recombination (int jet_i, int jet_j, double dij, int &newjet_k)
void plugin_record_ij_recombination (int jet_i, int jet_j, double dij, const PseudoJet &newjet, int &newjet_k)
void plugin_record_iB_recombination (int jet_i, double diB)
void plugin_associate_extras (Extras *extras_in)
bool plugin_activated () const
const Extras * extras () const
template<class GBJ >
void plugin_simple_N2_cluster ()
const std::vector< PseudoJet > & jets () const
const std::vector
< history_element > & history () const
unsigned int n_particles () const
std::vector< int > particle_jet_indices (const std::vector< PseudoJet > &) const
std::vector< int > unique_history_order () const
std::vector< PseudoJet > unclustered_particles () const
std::vector< PseudoJet > childless_pseudojets () const
bool contains (const PseudoJet &object) const
void transfer_from_sequence (const ClusterSequence &from_seq, const FunctionOfPseudoJet< PseudoJet > *action_on_jets=0)
const SharedPtr
< PseudoJetStructureBase > & structure_shared_ptr () const
template<class BJ >
FJCORE_BEGIN_NAMESPACE void _simple_N2_cluster ()
template<>
void _bj_set_jetinfo (EEBriefJet *const jetA, const int _jets_index) const
template<>
double _bj_dist (const EEBriefJet *const jeta, const EEBriefJet *const jetb) const
Static Public Member Functions
static void print_banner ()
static void set_fastjet_banner_stream (std::ostream *ostr)
static std::ostream * fastjet_banner_stream ()
Protected Member Functions
template<class L >
void _transfer_input_jets (const std::vector< L > &pseudojets)
void _initialise_and_run (const JetDefinition &jet_def, const bool &writeout_combinations)
void _initialise_and_run_no_decant ()
void _decant_options (const JetDefinition &jet_def, const bool &writeout_combinations)
void _decant_options_partial ()
void _fill_initial_history ()
void _do_ij_recombination_step (const int jet_i, const int jet_j, const double dij, int &newjet_k)
void _do_iB_recombination_step (const int jet_i, const double diB)
void _set_structure_shared_ptr (PseudoJet &j)
void _update_structure_use_count ()
Strategy _best_strategy () const
void get_subhist_set (std::set< const history_element * > &subhist, const PseudoJet &jet, double dcut, int maxjet) const
Protected Attributes
JetDefinition _jet_def
std::vector< PseudoJet > _jets
std::vector< history_element > _history
bool _writeout_combinations
int _initial_n
double _Rparam
double _R2
double _invR2
double _Qtot
Strategy _strategy
JetAlgorithm _jet_algorithm
SharedPtr< PseudoJetStructureBase > _structure_shared_ptr
int _structure_use_count_after_construction
bool _deletes_self_when_unused
Private Types
typedef std::pair< int, int > TwoVertices
typedef std::pair< double,
TwoVertices > DijEntry
typedef std::multimap< double,
TwoVertices > DistMap
Private Member Functions
void _really_dumb_cluster ()
void _delaunay_cluster ()
template<class BJ >
void _simple_N2_cluster ()
void _tiled_N2_cluster ()
void _faster_tiled_N2_cluster ()
void _minheap_faster_tiled_N2_cluster ()
void _CP2DChan_cluster ()
void _CP2DChan_cluster_2pi2R ()
void _CP2DChan_cluster_2piMultD ()
void _CP2DChan_limited_cluster (double D)
void _do_Cambridge_inclusive_jets ()
void _fast_NsqrtN_cluster ()
void _add_step_to_history (const int parent1, const int parent2, const int jetp_index, const double dij)
void _extract_tree_children (int pos, std::valarray< bool > &, const std::valarray< int > &, std::vector< int > &) const
void _extract_tree_parents (int pos, std::valarray< bool > &, const std::valarray< int > &, std::vector< int > &) const
void _add_ktdistance_to_map (const int ii, DistMap &DijMap, const DynamicNearestNeighbours *DNN)
template<class J >
void _bj_set_jetinfo (J *const jet, const int _jets_index) const
void _bj_remove_from_tiles (TiledJet *const jet) const
template<class J >
double _bj_dist (const J *const jeta, const J *const jetb) const
template<class J >
double _bj_diJ (const J *const jeta) const
template<class J >
J * _bj_of_hindex (const int hist_index, J *const head, J *const tail) const
template<class J >
void _bj_set_NN_nocross (J *const jeta, J *const head, const J *const tail) const
template<class J >
void _bj_set_NN_crosscheck (J *const jeta, J *const head, const J *const tail) const
int _tile_index (int ieta, int iphi) const
int _tile_index (const double eta, const double phi) const
void _tj_set_jetinfo (TiledJet *const jet, const int _jets_index)
void _bj_remove_from_tiles (TiledJet *const jet)
void _initialise_tiles ()
void _print_tiles (TiledJet *briefjets) const
void _add_neighbours_to_tile_union (const int tile_index, std::vector< int > &tile_union, int &n_near_tiles) const
void _add_untagged_neighbours_to_tile_union (const int tile_index, std::vector< int > &tile_union, int &n_near_tiles)
void _simple_N2_cluster_BriefJet ()
void _simple_N2_cluster_EEBriefJet ()
Private Attributes
bool _plugin_activated
SharedPtr< Extras > _extras
std::vector< Tile > _tiles
double _tiles_eta_min
double _tiles_eta_max
double _tile_size_eta
double _tile_size_phi
int _n_tiles_phi
int _tiles_ieta_min
int _tiles_ieta_max
Static Private Attributes
static std::ostream * _fastjet_banner_ostr = &cout
static bool _first_time = true
static LimitedWarning _exclusive_warnings
static LimitedWarning _changed_strategy_warning
static const int n_tile_neighbours = 9
Detailed Description
Definition at line 1349 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 1349 of file fjcore.hh
Member Typedef Documentation
typedef std::pair<double,TwoVertices> ClusterSequence::DijEntry private
Definition at line 1543 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 1543 of file fjcore.hh
typedef std::multimap<double,TwoVertices> ClusterSequence::DistMap private
Definition at line 1544 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 1544 of file fjcore.hh
typedef ClusterSequenceStructure ClusterSequence::StructureType
Definition at line 1469 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 1469 of file fjcore.hh
typedef std::pair<int,int> ClusterSequence::TwoVertices private
Definition at line 1542 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 1542 of file fjcore.hh
Member Enumeration Documentation
enum ClusterSequence::JetType
Enumerator:
Invalid
InexistentParent
BeamJet
Definition at line 1455 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 1455 of file fjcore.hh
Constructor & Destructor Documentation
ClusterSequence::ClusterSequence () inline
Definition at line 1351 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 1351 of file fjcore.hh
template<class L > ClusterSequence::ClusterSequence (const std::vector< L > & pseudojets, const JetDefinition & jet_def, const bool & writeout_combinations = false)
Definition at line 1627 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 1627 of file fjcore.hh
References _decant_options_partial(), _initialise_and_run_no_decant(), and _transfer_input_jets().
ClusterSequence::ClusterSequence (const ClusterSequence & cs) inline
Definition at line 1356 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 1356 of file fjcore.hh
ClusterSequence::~ClusterSequence () virtual
Definition at line 1407 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 1407 of file fjcore.cc
References assert, and ClusterSequenceStructure::set_associated_cs().
Member Function Documentation
void ClusterSequence::_add_ktdistance_to_map (const int ii, DistMap & DijMap, const DynamicNearestNeighbours * DNN) private
Definition at line 2539 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 2539 of file fjcore.cc
References LazyTiling9::_invR2, LazyTiling9::_jets, DynamicNearestNeighbours::NearestNeighbourDistance(), and DynamicNearestNeighbours::NearestNeighbourIndex().
void ClusterSequence::_add_neighbours_to_tile_union (const int tile_index, std::vector< int > & tile_union, int & n_near_tiles) const private
Definition at line 2837 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 2837 of file fjcore.cc
References LazyTiling9::_tiles.
void ClusterSequence::_add_step_to_history (const int parent1, const int parent2, const int jetp_index, const double dij) private
Definition at line 2129 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 2129 of file fjcore.cc
References LazyTiling9::_jets, assert, ClusterSequence::history_element::child, ClusterSequence::history_element::dij, fixGDML::element, testing::internal::Invalid(), ClusterSequence::history_element::jetp_index, ClusterSequence::history_element::max_dij_so_far, ClusterSequence::history_element::parent1, and ClusterSequence::history_element::parent2.
void ClusterSequence::_add_untagged_neighbours_to_tile_union (const int tile_index, std::vector< int > & tile_union, int & n_near_tiles) inline private
Definition at line 2845 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 2845 of file fjcore.cc
References LazyTiling9::_tiles.
Strategy ClusterSequence::_best_strategy () const protected
Definition at line 1671 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 1671 of file fjcore.cc
References LazyTiling9::_jets, LazyTiling9::_Rparam, antikt_algorithm, assert, cambridge_algorithm, cambridge_for_passive_algorithm, genkt_algorithm, kt_algorithm, N, N2MHTLazy25, N2MHTLazy9, N2MinHeapTiled, N2Plain, N2Tiled, NlnN, NlnNCam, merge_hashes::p, and pi.
template<class J > double ClusterSequence::_bj_diJ (const J *const jeta) const inline private
Definition at line 1684 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 1684 of file fjcore.hh
template<class J > double ClusterSequence::_bj_dist (const J *const jeta, const J *const jetb) const inline private
Definition at line 1672 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 1672 of file fjcore.hh
References INTTVtxZ::dphi, pi, and twopi.
Referenced by _bj_set_NN_crosscheck(), and _bj_set_NN_nocross().
template<> double ClusterSequence::_bj_dist (const EEBriefJet *const jeta, const EEBriefJet *const jetb) const
Definition at line 2644 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 2644 of file fjcore.cc
References dist(), ClusterSequence::EEBriefJet::nx, ClusterSequence::EEBriefJet::ny, and ClusterSequence::EEBriefJet::nz.
template<class J > J* ClusterSequence::_bj_of_hindex (const int hist_index, J *const head, J *const tail) const inline private
Definition at line 1571 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 1571 of file fjcore.hh
References Acts::UnitConstants::J.
void ClusterSequence::_bj_remove_from_tiles (TiledJet *const jet) const private
void ClusterSequence::_bj_remove_from_tiles (TiledJet *const jet) private
Definition at line 2745 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 2745 of file fjcore.cc
References LazyTiling9::_tiles, ClusterSequence::Tile::head, ClusterSequence::TiledJet::next, ClusterSequence::TiledJet::previous, tile(), and ClusterSequence::TiledJet::tile_index.
template<class J > void ClusterSequence::_bj_set_jetinfo (J *const jet, const int _jets_index) const inline private
Definition at line 1663 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 1663 of file fjcore.hh
References _jets, _R2, and jet_scale_for_algorithm().
template<> void ClusterSequence::_bj_set_jetinfo (EEBriefJet *const jetA, const int _jets_index) const inline
Definition at line 2612 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 2612 of file fjcore.cc
References LazyTiling9::_jets, ClusterSequence::EEBriefJet::_jets_index, LazyTiling9::_R2, LazyTiling9::_Rparam, assert, E, Acts::UnitConstants::e, ee_genkt_algorithm, ee_kt_algorithm, ClusterSequence::EEBriefJet::kt2, ClusterSequence::EEBriefJet::NN, ClusterSequence::EEBriefJet::NN_dist, norm, ClusterSequence::EEBriefJet::nx, ClusterSequence::EEBriefJet::ny, ClusterSequence::EEBriefJet::nz, and merge_hashes::p.
template<class J > void ClusterSequence::_bj_set_NN_crosscheck (J *const jeta, J *const head, const J *const tail) const inline private
Definition at line 1714 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 1714 of file fjcore.hh
References _bj_dist(), _R2, dist(), Acts::UnitConstants::J, and NN.
template<class J > void ClusterSequence::_bj_set_NN_nocross (J *const jeta, J *const head, const J *const tail) const inline private
Definition at line 1689 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 1689 of file fjcore.hh
References _bj_dist(), _R2, dist(), Acts::UnitConstants::J, and NN.
void ClusterSequence::_CP2DChan_cluster () private
Definition at line 2375 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 2375 of file fjcore.cc
References LazyTiling9::_invR2, LazyTiling9::_jets, assert, cambridge_algorithm, ClosestPair2D::closest_pair(), E, i, testing::internal::Invalid(), Acts::UnitConstants::min, n, ClosestPair2D::replace(), twopi, and ambiguity_solver_full_chain::x.
void ClusterSequence::_CP2DChan_cluster_2pi2R () private
Definition at line 2364 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 2364 of file fjcore.cc
References LazyTiling9::_Rparam, and cambridge_algorithm.
void ClusterSequence::_CP2DChan_cluster_2piMultD () private
Definition at line 2369 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 2369 of file fjcore.cc
References LazyTiling9::_Rparam, and Acts::UnitConstants::min.
void ClusterSequence::_CP2DChan_limited_cluster (double D) private
Definition at line 2295 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 2295 of file fjcore.cc
References LazyTiling9::_invR2, LazyTiling9::_jets, assert, ClosestPair2D::closest_pair(), testing::internal::Invalid(), Private::make_mirror(), Acts::UnitConstants::min, n, pi, ClosestPair2D::replace_many(), and ambiguity_solver_full_chain::x.
void ClusterSequence::_decant_options (const JetDefinition & jet_def, const bool & writeout_combinations) protected
Definition at line 1575 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 1575 of file fjcore.cc
void ClusterSequence::_decant_options_partial () protected
Definition at line 1582 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 1582 of file fjcore.cc
References LazyTiling9::_invR2, LazyTiling9::_R2, LazyTiling9::_Rparam, and print_banner().
Referenced by ClusterSequence().
void ClusterSequence::_delaunay_cluster () private
Definition at line 2458 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 2458 of file fjcore.cc
References LazyTiling9::_jets, LazyTiling9::_Rparam, assert, check_license::err(), SharedPtr< T >::get(), i, it, n, NlnN, NlnN3pi, NlnN4pi, DynamicNearestNeighbours::RemoveCombinedAddCombination(), DynamicNearestNeighbours::RemovePoint(), SharedPtr< T >::reset(), EtaPhi::sanitize(), twopi, DynamicNearestNeighbours::Valid(), and verbose.
void ClusterSequence::_do_Cambridge_inclusive_jets () private
Definition at line 2436 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 2436 of file fjcore.cc
References testing::internal::Invalid(), and n.
void ClusterSequence::_do_iB_recombination_step (const int jet_i, const double diB) protected
Definition at line 2253 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 2253 of file fjcore.cc
References LazyTiling9::_jets, and testing::internal::Invalid().
void ClusterSequence::_do_ij_recombination_step (const int jet_i, const int jet_j, const double dij, int & newjet_k) protected
Definition at line 2238 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 2238 of file fjcore.cc
References LazyTiling9::_jets, and Acts::UnitConstants::min.
void ClusterSequence::_extract_tree_children (int pos, std::valarray< bool > & extracted, const std::valarray< int > & lowest_constituent, std::vector< int > & unique_tree) const private
Definition at line 2185 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 2185 of file fjcore.cc
References position.
void ClusterSequence::_extract_tree_parents (int pos, std::valarray< bool > & extracted, const std::valarray< int > & lowest_constituent, std::vector< int > & unique_tree) const private
Definition at line 2218 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 2218 of file fjcore.cc
References position, and swap().
void ClusterSequence::_fast_NsqrtN_cluster () private
void ClusterSequence::_faster_tiled_N2_cluster () private
Definition at line 3011 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 3011 of file fjcore.cc
References LazyTiling9::_add_untagged_neighbours_to_tile_union(), LazyTiling9::_bj_diJ(), LazyTiling9::_bj_dist(), LazyTiling9::_bj_remove_from_tiles(), LazyTiling9::_initialise_tiles(), LazyTiling9::_invR2, LazyTiling9::_jets, ClusterSequence::TiledJet::_jets_index, LazyTiling9::_R2, LazyTiling9::_tiles, LazyTiling9::_tj_set_jetinfo(), ClusterSequence::Tile::begin_tiles, ClusterSequence::TiledJet::diJ_posn, dist(), ClusterSequence::Tile::end_tiles, ClusterSequence::Tile::head, i, n, ClusterSequence::TiledJet::next, ClusterSequence::TiledJet::NN, ClusterSequence::TiledJet::NN_dist, swap(), ClusterSequence::Tile::tagged, tile(), and ClusterSequence::TiledJet::tile_index.
void ClusterSequence::_fill_initial_history () protected
Definition at line 1590 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 1590 of file fjcore.cc
References LazyTiling9::_jets, ClusterSequence::history_element::child, ClusterSequence::history_element::dij, fixGDML::element, i, testing::internal::Invalid(), ClusterSequence::history_element::jetp_index, ClusterSequence::history_element::max_dij_so_far, ClusterSequence::history_element::parent1, and ClusterSequence::history_element::parent2.
void ClusterSequence::_initialise_and_run (const JetDefinition & jet_def, const bool & writeout_combinations) protected
Definition at line 1422 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 1422 of file fjcore.cc
void ClusterSequence::_initialise_and_run_no_decant () protected
Definition at line 1428 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 1428 of file fjcore.cc
References LazyTiling9::_invR2, LazyTiling9::_jets, LazyTiling9::_R2, LazyTiling9::_Rparam, antikt_algorithm, assert, Best, BestFJ30, cambridge_algorithm, ee_genkt_algorithm, ee_kt_algorithm, check_license::err(), Acts::UnitConstants::min, N, N2MHTLazy25, N2MHTLazy9, N2MHTLazy9Alt, N2MHTLazy9AntiKtSeparateGhosts, N2MinHeapTiled, N2Plain, N2PoorTiled, N2Tiled, N3Dumb, NlnN, NlnN3pi, NlnN4pi, NlnNCam, NlnNCam2pi2R, NlnNCam4pi, pi, plugin_algorithm, LazyTiling9Alt::run(), LazyTiling9::run(), LazyTiling25::run(), twopi, and undefined_jet_algorithm.
Referenced by ClusterSequence().
void ClusterSequence::_initialise_tiles () private
Definition at line 2756 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 2756 of file fjcore.cc
References LazyTiling9::_n_tiles_phi, LazyTiling9::_Rparam, LazyTiling9::_tile_index(), LazyTiling9::_tile_size_eta, LazyTiling9::_tile_size_phi, LazyTiling9::_tiles, LazyTiling9::_tiles_eta_max, LazyTiling9::_tiles_eta_min, LazyTiling9::_tiles_ieta_max, LazyTiling9::_tiles_ieta_min, ClusterSequence::Tile::begin_tiles, ClusterSequence::Tile::end_tiles, ClusterSequence::Tile::head, TilingExtent::maxrap(), TilingExtent::minrap(), ClusterSequence::Tile::RH_tiles, ClusterSequence::Tile::surrounding_tiles, ClusterSequence::Tile::tagged, tile(), and twopi.
void ClusterSequence::_minheap_faster_tiled_N2_cluster () private
Definition at line 3144 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 3144 of file fjcore.cc
References LazyTiling9::_add_untagged_neighbours_to_tile_union(), LazyTiling9::_bj_diJ(), LazyTiling9::_bj_dist(), LazyTiling9::_bj_remove_from_tiles(), LazyTiling9::_initialise_tiles(), LazyTiling9::_invR2, LazyTiling9::_jets, ClusterSequence::TiledJet::_jets_index, LazyTiling9::_R2, LazyTiling9::_tiles, LazyTiling9::_tj_set_jetinfo(), ClusterSequence::Tile::begin_tiles, dist(), ClusterSequence::Tile::end_tiles, ClusterSequence::Tile::head, i, ClusterSequence::TiledJet::label_minheap_update_done(), MinHeap::minloc(), MinHeap::minval(), n, ClusterSequence::TiledJet::next, ClusterSequence::TiledJet::NN, ClusterSequence::TiledJet::NN_dist, MinHeap::remove(), swap(), ClusterSequence::Tile::tagged, tile(), ClusterSequence::TiledJet::tile_index, and MinHeap::update().
void ClusterSequence::_print_tiles (TiledJet * briefjets) const private
Definition at line 2824 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 2824 of file fjcore.cc
References LazyTiling9::_tiles, i, Acts::Experimental::detail::BlueprintHelper::sort(), and tile().
void ClusterSequence::_really_dumb_cluster () private
Definition at line 2567 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 2567 of file fjcore.cc
References LazyTiling9::_invR2, LazyTiling9::_jets, i, j, Acts::UnitConstants::min, n, y, and ymin.
void ClusterSequence::_set_structure_shared_ptr (PseudoJet & j) protected
Definition at line 2259 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 2259 of file fjcore.cc
template<class BJ > FJCORE_BEGIN_NAMESPACE void ClusterSequence::_simple_N2_cluster ()
Definition at line 89 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 89 of file fjcore.cc
References dist(), i, n, and swap().
template<class BJ > void ClusterSequence::_simple_N2_cluster () private
void ClusterSequence::_simple_N2_cluster_BriefJet () private
Definition at line 2654 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 2654 of file fjcore.cc
void ClusterSequence::_simple_N2_cluster_EEBriefJet () private
Definition at line 2657 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 2657 of file fjcore.cc
int ClusterSequence::_tile_index (int ieta, int iphi) const inline private
Definition at line 1598 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 1598 of file fjcore.hh
int ClusterSequence::_tile_index (const double eta, const double phi) const private
void ClusterSequence::_tiled_N2_cluster () private
Definition at line 2857 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 2857 of file fjcore.cc
References LazyTiling9::_add_neighbours_to_tile_union(), LazyTiling9::_bj_diJ(), LazyTiling9::_bj_dist(), LazyTiling9::_bj_remove_from_tiles(), LazyTiling9::_initialise_tiles(), LazyTiling9::_invR2, LazyTiling9::_jets, ClusterSequence::TiledJet::_jets_index, LazyTiling9::_R2, LazyTiling9::_tiles, LazyTiling9::_tj_set_jetinfo(), ClusterSequence::Tile::begin_tiles, dist(), ClusterSequence::Tile::end_tiles, ClusterSequence::Tile::head, i, n, ClusterSequence::TiledJet::next, ClusterSequence::TiledJet::NN, ClusterSequence::TiledJet::NN_dist, ClusterSequence::TiledJet::previous, Acts::Experimental::detail::BlueprintHelper::sort(), swap(), tile(), and ClusterSequence::TiledJet::tile_index.
void ClusterSequence::_tj_set_jetinfo (TiledJet *const jet, const int _jets_index) inline private
Definition at line 2814 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 2814 of file fjcore.cc
References LazyTiling9::_tile_index(), LazyTiling9::_tiles, ClusterSequence::Tile::head, ClusterSequence::TiledJet::next, ClusterSequence::TiledJet::previous, and tile().
template<class L > void ClusterSequence::_transfer_input_jets (const std::vector< L > & pseudojets) protected
Definition at line 1621 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 1621 of file fjcore.hh
References i.
Referenced by ClusterSequence().
void ClusterSequence::_update_structure_use_count () protected
Definition at line 2263 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 2263 of file fjcore.cc
void ClusterSequence::add_constituents (const PseudoJet & jet, std::vector< PseudoJet > & subjet_vector) const
Definition at line 2115 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 2115 of file fjcore.cc
References LazyTiling9::_jets, and i.
vector< PseudoJet > ClusterSequence::childless_pseudojets () const
Definition at line 2204 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 2204 of file fjcore.cc
References LazyTiling9::_jets, i, and testing::internal::Invalid().
vector< PseudoJet > ClusterSequence::constituents (const PseudoJet & jet) const
Definition at line 2070 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 2070 of file fjcore.cc
bool ClusterSequence::contains (const PseudoJet & object) const
Definition at line 2212 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 2212 of file fjcore.cc
void ClusterSequence::delete_self_when_unused ()
Definition at line 2266 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 2266 of file fjcore.cc
Referenced by JetDefinition::operator()().
double ClusterSequence::exclusive_dmerge (const int njets) const
Definition at line 1914 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 1914 of file fjcore.cc
References assert.
double ClusterSequence::exclusive_dmerge_max (const int njets) const
Definition at line 1919 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 1919 of file fjcore.cc
References assert.
std::vector<PseudoJet> ClusterSequence::exclusive_jets (const double dcut) const
std::vector<PseudoJet> ClusterSequence::exclusive_jets (const int njets) const
vector< PseudoJet > ClusterSequence::exclusive_jets_up_to (const int njets) const
Definition at line 1876 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 1876 of file fjcore.cc
References LazyTiling9::_jets, cambridge_algorithm, ee_genkt_algorithm, ee_kt_algorithm, check_license::err(), genkt_algorithm, i, kt_algorithm, Acts::UnitConstants::min, and plugin_algorithm.
std::vector<PseudoJet> ClusterSequence::exclusive_jets_ycut (double ycut) const inline
Definition at line 1371 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 1371 of file fjcore.hh
double ClusterSequence::exclusive_subdmerge (const PseudoJet & jet, int nsub) const
Definition at line 1967 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 1967 of file fjcore.cc
double ClusterSequence::exclusive_subdmerge_max (const PseudoJet & jet, int nsub) const
Definition at line 1974 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 1974 of file fjcore.cc
std::vector<PseudoJet> ClusterSequence::exclusive_subjets (const PseudoJet & jet, const double dcut) const
std::vector<PseudoJet> ClusterSequence::exclusive_subjets (const PseudoJet & jet, int nsub) const
std::vector< PseudoJet > ClusterSequence::exclusive_subjets_up_to (const PseudoJet & jet, int nsub) const
Definition at line 1954 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 1954 of file fjcore.cc
References LazyTiling9::_jets.
double ClusterSequence::exclusive_ymerge (int njets) const inline
Definition at line 1368 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 1368 of file fjcore.hh
double ClusterSequence::exclusive_ymerge_max (int njets) const inline
Definition at line 1369 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 1369 of file fjcore.hh
const Extras* ClusterSequence::extras () const inline
Definition at line 1436 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 1436 of file fjcore.hh
static std::ostream* ClusterSequence::fastjet_banner_stream () inline static
Definition at line 1472 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 1472 of file fjcore.hh
void ClusterSequence::get_subhist_set (std::set< const history_element * > & subhist, const PseudoJet & jet, double dcut, int maxjet) const protected
Definition at line 1981 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 1981 of file fjcore.cc
References assert, ClusterSequence::history_element::max_dij_so_far, ClusterSequence::history_element::parent1, and ClusterSequence::history_element::parent2.
bool ClusterSequence::has_child (const PseudoJet & jet, PseudoJet & child) const
bool ClusterSequence::has_child (const PseudoJet & jet, const PseudoJet *& childp) const
bool ClusterSequence::has_parents (const PseudoJet & jet, PseudoJet & parent1, PseudoJet & parent2) const
Definition at line 2017 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 2017 of file fjcore.cc
References LazyTiling9::_jets, assert, add_histos::hist, ClusterSequence::history_element::parent1, ClusterSequence::history_element::parent2, and swap().
bool ClusterSequence::has_partner (const PseudoJet & jet, PseudoJet & partner) const
Definition at line 2054 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 2054 of file fjcore.cc
References LazyTiling9::_jets, ClusterSequence::history_element::child, ClusterSequence::history_element::parent1, and ClusterSequence::history_element::parent2.
const std::vector< ClusterSequence::history_element > & ClusterSequence::history () const inline
Definition at line 1641 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 1641 of file fjcore.hh
References _history.
vector< PseudoJet > ClusterSequence::inclusive_jets (const double ptmin = 0.0) const
Definition at line 1815 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 1815 of file fjcore.cc
References LazyTiling9::_jets, antikt_algorithm, cambridge_algorithm, cambridge_for_passive_algorithm, ee_genkt_algorithm, ee_kt_algorithm, genkt_algorithm, i, kt_algorithm, and plugin_algorithm.
Referenced by JetDefinition::operator()(), and TreeMaker::UseFastJet().
const JetDefinition& ClusterSequence::jet_def () const inline
Definition at line 1404 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 1404 of file fjcore.hh
double ClusterSequence::jet_scale_for_algorithm (const PseudoJet & jet) const
Definition at line 1651 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 1651 of file fjcore.cc
References antikt_algorithm, cambridge_algorithm, cambridge_for_passive_algorithm, Acts::UnitConstants::e, genkt_algorithm, kt_algorithm, and merge_hashes::p.
Referenced by _bj_set_jetinfo().
const std::vector< PseudoJet > & ClusterSequence::jets () const inline
Definition at line 1638 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 1638 of file fjcore.hh
References _jets.
int ClusterSequence::n_exclusive_jets (const double dcut) const
Definition at line 1853 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 1853 of file fjcore.cc
References i.
int ClusterSequence::n_exclusive_jets_ycut (double ycut) const inline
Definition at line 1370 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 1370 of file fjcore.hh
int ClusterSequence::n_exclusive_subjets (const PseudoJet & jet, const double dcut) const
Definition at line 1936 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 1936 of file fjcore.cc
unsigned int ClusterSequence::n_particles () const inline
Definition at line 1644 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 1644 of file fjcore.hh
References _initial_n.
bool ClusterSequence::object_in_jet (const PseudoJet & object, const PseudoJet & jet) const
Definition at line 2002 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 2002 of file fjcore.cc
References assert.
ClusterSequence & ClusterSequence::operator= (const ClusterSequence & cs)
Definition at line 1767 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 1767 of file fjcore.cc
vector< int > ClusterSequence::particle_jet_indices (const std::vector< PseudoJet > & jets_in) const
Definition at line 2100 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 2100 of file fjcore.cc
bool ClusterSequence::plugin_activated () const inline
Definition at line 1435 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 1435 of file fjcore.hh
void ClusterSequence::plugin_associate_extras (Extras * extras_in) inline
Definition at line 1426 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 1426 of file fjcore.hh
void ClusterSequence::plugin_record_iB_recombination (int jet_i, double diB) inline
Definition at line 1417 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 1417 of file fjcore.hh
References assert.
void ClusterSequence::plugin_record_ij_recombination (int jet_i, int jet_j, double dij, int & newjet_k) inline
Definition at line 1409 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 1409 of file fjcore.hh
References assert.
void ClusterSequence::plugin_record_ij_recombination (int jet_i, int jet_j, double dij, const PseudoJet & newjet, int & newjet_k)
Definition at line 1806 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 1806 of file fjcore.cc
References LazyTiling9::_jets.
template<class GBJ > void ClusterSequence::plugin_simple_N2_cluster () inline
Definition at line 1437 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 1437 of file fjcore.hh
References assert.
void ClusterSequence::print_banner () static
Definition at line 1550 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 1550 of file fjcore.cc
References fastjet_version.
void ClusterSequence::print_jets_for_root (const std::vector< PseudoJet > & jets, std::ostream & ostr = std::cout) const
void ClusterSequence::print_jets_for_root (const std::vector< PseudoJet > & jets, const std::string & filename, const std::string & comment = "") const
double ClusterSequence::Q () const inline
Definition at line 1385 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 1385 of file fjcore.hh
double ClusterSequence::Q2 () const inline
Definition at line 1386 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 1386 of file fjcore.hh
static void ClusterSequence::set_fastjet_banner_stream (std::ostream * ostr) inline static
Definition at line 1471 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 1471 of file fjcore.hh
void ClusterSequence::signal_imminent_self_deletion () const
Definition at line 1418 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 1418 of file fjcore.cc
References assert.
std::string ClusterSequence::strategy_string () const inline
Definition at line 1402 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 1402 of file fjcore.hh
References strategy_string().
Referenced by strategy_string().
std::string ClusterSequence::strategy_string (Strategy strategy_in) const
Strategy ClusterSequence::strategy_used () const inline
Definition at line 1401 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 1401 of file fjcore.hh
const SharedPtr<PseudoJetStructureBase>& ClusterSequence::structure_shared_ptr () const inline
Definition at line 1466 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 1466 of file fjcore.hh
void ClusterSequence::transfer_from_sequence (const ClusterSequence & from_seq, const FunctionOfPseudoJet< PseudoJet > * action_on_jets = 0)
Definition at line 1774 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 1774 of file fjcore.cc
References LazyTiling9::_invR2, LazyTiling9::_jets, LazyTiling9::_R2, LazyTiling9::_Rparam, assert, i, and ClusterSequenceStructure::set_associated_cs().
vector< PseudoJet > ClusterSequence::unclustered_particles () const
Definition at line 2196 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 2196 of file fjcore.cc
References LazyTiling9::_jets, i, and testing::internal::Invalid().
vector< int > ClusterSequence::unique_history_order () const
Definition at line 2164 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 2164 of file fjcore.cc
References i, and Acts::UnitConstants::min.
bool ClusterSequence::will_delete_self_when_unused () const inline
Definition at line 1406 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 1406 of file fjcore.hh
Member Data Documentation
LimitedWarning ClusterSequence::_changed_strategy_warning static private
Definition at line 1550 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 1550 of file fjcore.hh
bool ClusterSequence::_deletes_self_when_unused mutable protected
Definition at line 1518 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 1518 of file fjcore.hh
LimitedWarning ClusterSequence::_exclusive_warnings static private
Definition at line 1549 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 1549 of file fjcore.hh
SharedPtr<Extras> ClusterSequence::_extras private
Definition at line 1521 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 1521 of file fjcore.hh
std::ostream * ClusterSequence::_fastjet_banner_ostr = &cout static private
Definition at line 1474 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 1474 of file fjcore.hh
bool ClusterSequence::_first_time = true static private
Definition at line 1548 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 1548 of file fjcore.hh
std::vector<history_element> ClusterSequence::_history protected
Definition at line 1507 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 1507 of file fjcore.hh
Referenced by history().
int ClusterSequence::_initial_n protected
Definition at line 1511 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 1511 of file fjcore.hh
Referenced by n_particles().
double ClusterSequence::_invR2 protected
Definition at line 1512 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 1512 of file fjcore.hh
JetAlgorithm ClusterSequence::_jet_algorithm protected
Definition at line 1515 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 1515 of file fjcore.hh
JetDefinition ClusterSequence::_jet_def protected
Definition at line 1476 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 1476 of file fjcore.hh
std::vector<PseudoJet> ClusterSequence::_jets protected
Definition at line 1506 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 1506 of file fjcore.hh
Referenced by _bj_set_jetinfo(), and jets().
int ClusterSequence::_n_tiles_phi private
Definition at line 1597 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 1597 of file fjcore.hh
bool ClusterSequence::_plugin_activated private
Definition at line 1520 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 1520 of file fjcore.hh
double ClusterSequence::_Qtot protected
Definition at line 1513 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 1513 of file fjcore.hh
double ClusterSequence::_R2 protected
Definition at line 1512 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 1512 of file fjcore.hh
Referenced by _bj_set_jetinfo(), _bj_set_NN_crosscheck(), and _bj_set_NN_nocross().
double ClusterSequence::_Rparam protected
Definition at line 1512 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 1512 of file fjcore.hh
Strategy ClusterSequence::_strategy protected
Definition at line 1514 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 1514 of file fjcore.hh
SharedPtr<PseudoJetStructureBase> ClusterSequence::_structure_shared_ptr protected
Definition at line 1516 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 1516 of file fjcore.hh
int ClusterSequence::_structure_use_count_after_construction protected
Definition at line 1517 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 1517 of file fjcore.hh
double ClusterSequence::_tile_size_eta private
Definition at line 1596 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 1596 of file fjcore.hh
double ClusterSequence::_tile_size_phi private
Definition at line 1596 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 1596 of file fjcore.hh
std::vector<Tile> ClusterSequence::_tiles private
Definition at line 1594 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 1594 of file fjcore.hh
double ClusterSequence::_tiles_eta_max private
Definition at line 1595 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 1595 of file fjcore.hh
double ClusterSequence::_tiles_eta_min private
Definition at line 1595 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 1595 of file fjcore.hh
int ClusterSequence::_tiles_ieta_max private
Definition at line 1597 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 1597 of file fjcore.hh
int ClusterSequence::_tiles_ieta_min private
Definition at line 1597 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 1597 of file fjcore.hh
bool ClusterSequence::_writeout_combinations protected
Definition at line 1510 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 1510 of file fjcore.hh
const int ClusterSequence::n_tile_neighbours = 9 static private
Definition at line 1585 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 1585 of file fjcore.hh
The documentation for this class was generated from the following files:
JETSCAPE/blob/main/external_packages/fjcore.hh
JETSCAPE/blob/main/external_packages/fjcore.cc