Analysis Software: dfe Namespace Reference
dfe Namespace Reference
Namespaces
namespace dispatcher_impl
namespace histogram_impl
namespace io_dsv_impl
namespace io_npy_impl
namespace io_root_impl
namespace namedtuple_impl
namespace namedtuple_root_impl
Classes
exception Variable
Variable-type value object a.k.a. a poor mans std::variant.
class Dispatcher
class FlatSet
class FlatMap
class UniformAxis
Uniform binning without under/overflow bins.
class OverflowAxis
class VariableAxis
Variable binninng defined by arbitrary bin edges.
class Histogram
class NamedTupleNumpyWriter
class NamedTupleRootWriter
Write records into a ROOT TTree.
class NamedTupleRootReader
Read records from a ROOT TTree.
class SmallVector
Typedefs
using Histogram1 = Histogram< double, OverflowAxis< double >>
using Histogram2 = Histogram< double, OverflowAxis< double >, OverflowAxis< double >>
using CsvWriter = io_dsv_impl::DsvWriter<','>
Write arbitrary data as comma-separated values into as text file.
using TsvWriter = io_dsv_impl::DsvWriter<'\t'>
Write arbitrary data as tab-separated values into as text file.
template<typename T >
using NamedTupleCsvWriter = io_dsv_impl::NamedTupleDsvWriter<',', T >
Write tuple-like records as comma-separated values into a text file.
template<typename T >
using NamedTupleCsvReader = io_dsv_impl::NamedTupleDsvReader<',', T >
Read tuple-like records from a comma-separated file.
template<typename T >
using NamedTupleTsvWriter = io_dsv_impl::NamedTupleDsvWriter<'\t', T >
Write tuple-like records as tab-separated values into a text file.
template<typename T >
using NamedTupleTsvReader = io_dsv_impl::NamedTupleDsvReader<'\t', T >
Read tuple-like records from a tab-separated file.
Functions
std::ostream & operator<< (std::ostream &os, const Variable &v)
static_cast< T > (0))
m_axes (std::move(axes)...)
template<typename T , typename Container >
constexpr T polynomial_val (const T &x, const Container &coeffs)
template<typename T , typename Container >
constexpr std::pair< T, T > polynomial_valder (const T &x, const Container &coeffs)
template<typename T , typename Container >
constexpr T polynomial_der (const T &x, const Container &coeffs)
template<typename T , typename U >
constexpr auto polynomial_val (const T &x, std::initializer_list< U > coeffs)
Evaluate a polynomial with an order fixed at compile time.
template<typename T , typename U >
constexpr auto polynomial_der (const T &x, std::initializer_list< U > coeffs)
Evaluate the derivative of a polynomial with an order fixed at compile time.
template<typename T , typename U >
constexpr auto polynomial_valder (const T &x, std::initializer_list< U > coeffs)
Evaluate the derivative of a polynomial with an order fixed at compile time.
Typedef Documentation
using dfe::CsvWriter = typedef io_dsv_impl::DsvWriter<','>
Write arbitrary data as comma-separated values into as text file.
Definition at line 501 of file dfe_io_dsv.hpp.
View newest version in sPHENIX GitHub at line 501 of file dfe_io_dsv.hpp
using dfe::Histogram1 = typedef Histogram<double, OverflowAxis<double>>
Definition at line 187 of file dfe_histogram.hpp.
View newest version in sPHENIX GitHub at line 187 of file dfe_histogram.hpp
using dfe::Histogram2 = typedef Histogram<double, OverflowAxis<double>, OverflowAxis<double>>
Definition at line 189 of file dfe_histogram.hpp.
View newest version in sPHENIX GitHub at line 189 of file dfe_histogram.hpp
template<typename T > using dfe::NamedTupleCsvReader = typedef io_dsv_impl::NamedTupleDsvReader<',', T>
Read tuple-like records from a comma-separated file.
Definition at line 512 of file dfe_io_dsv.hpp.
View newest version in sPHENIX GitHub at line 512 of file dfe_io_dsv.hpp
template<typename T > using dfe::NamedTupleCsvWriter = typedef io_dsv_impl::NamedTupleDsvWriter<',', T>
Write tuple-like records as comma-separated values into a text file.
Definition at line 508 of file dfe_io_dsv.hpp.
View newest version in sPHENIX GitHub at line 508 of file dfe_io_dsv.hpp
template<typename T > using dfe::NamedTupleTsvReader = typedef io_dsv_impl::NamedTupleDsvReader<'\t', T>
Read tuple-like records from a tab-separated file.
Definition at line 520 of file dfe_io_dsv.hpp.
View newest version in sPHENIX GitHub at line 520 of file dfe_io_dsv.hpp
template<typename T > using dfe::NamedTupleTsvWriter = typedef io_dsv_impl::NamedTupleDsvWriter<'\t', T>
Write tuple-like records as tab-separated values into a text file.
Definition at line 516 of file dfe_io_dsv.hpp.
View newest version in sPHENIX GitHub at line 516 of file dfe_io_dsv.hpp
using dfe::TsvWriter = typedef io_dsv_impl::DsvWriter<'\t'>
Write arbitrary data as tab-separated values into as text file.
Definition at line 504 of file dfe_io_dsv.hpp.
View newest version in sPHENIX GitHub at line 504 of file dfe_io_dsv.hpp
Function Documentation
dfe::m_axes (std::move(axes) ...)
Definition at line 326 of file dfe_histogram.hpp.
View newest version in sPHENIX GitHub at line 326 of file dfe_histogram.hpp
std::ostream& dfe::operator<< (std::ostream & os, const Variable & v) inline
Definition at line 177 of file dfe_dispatcher.hpp.
View newest version in sPHENIX GitHub at line 177 of file dfe_dispatcher.hpp
References dfe::Variable::m_boolean, dfe::Variable::m_float, dfe::Variable::m_integer, dfe::Variable::m_string, dfe::Variable::m_type, os, String, and dfe::Variable::type().
template<typename T , typename Container > constexpr T dfe::polynomial_der (const T & x, const Container & coeffs)
Evaluate the the derivative of a polynomial of arbitrary order.
Parameters
x Where to evaluate the derivative.
coeffs ReversibleContainer with n+1 coefficients.
The coefficients must be given in increasing order. E.g. a second order polynomial has three coefficients c0, c1, c2 that define the derivative
df(x)/dx = 0 + c1 + 2*c2*x
Definition at line 104 of file dfe_poly.hpp.
View newest version in sPHENIX GitHub at line 104 of file dfe_poly.hpp
References polynomial_valder().
template<typename T , typename U > constexpr auto dfe::polynomial_der (const T & x, std::initializer_list< U > coeffs)
Evaluate the derivative of a polynomial with an order fixed at compile time.
Definition at line 118 of file dfe_poly.hpp.
View newest version in sPHENIX GitHub at line 118 of file dfe_poly.hpp
References x.
template<typename T , typename Container > constexpr T dfe::polynomial_val (const T & x, const Container & coeffs)
Evaluate a polynomial of arbitrary order.
Parameters
x Where to evaluate the polynomial.
coeffs ReversibleContainer with n+1 coefficients.
The coefficients must be given in increasing order. E.g. a second order polynomial has three coefficients c0, c1, c2 that define the function
f(x) = c0 + c1*x + c2*x^2
Definition at line 48 of file dfe_poly.hpp.
View newest version in sPHENIX GitHub at line 48 of file dfe_poly.hpp
References c, Acts::UnitConstants::T, value, and x.
template<typename T , typename U > constexpr auto dfe::polynomial_val (const T & x, std::initializer_list< U > coeffs)
Evaluate a polynomial with an order fixed at compile time.
Definition at line 111 of file dfe_poly.hpp.
View newest version in sPHENIX GitHub at line 111 of file dfe_poly.hpp
References x.
template<typename T , typename Container > constexpr std::pair<T, T> dfe::polynomial_valder (const T & x, const Container & coeffs)
Evaluate the value and the derivative of a polynomial of arbitrary order.
Parameters
x Where to evaluate the derivative.
coeffs ReversibleContainer with n+1 coefficients.
The coefficients must be given in increasing order. E.g. a second order polynomial has three coefficients c0, c1, c2 that define the function
f(x) = c0 + c1*x + c2*x^2
and the derivative
df(x)/dx = 0 + c1 + 2*c2*x
Definition at line 78 of file dfe_poly.hpp.
View newest version in sPHENIX GitHub at line 78 of file dfe_poly.hpp
References c, p, Acts::UnitConstants::T, and x.
Referenced by polynomial_der().
template<typename T , typename U > constexpr auto dfe::polynomial_valder (const T & x, std::initializer_list< U > coeffs)
Evaluate the derivative of a polynomial with an order fixed at compile time.
Definition at line 125 of file dfe_poly.hpp.
View newest version in sPHENIX GitHub at line 125 of file dfe_poly.hpp
References x.
dfe::static_cast< T > (0)
Referenced by Acts::SinglyCharged::extractCharge(), Acts::AnyCharge::extractCharge(), Acts::SinglyCharged::extractMomentum(), Acts::AnyCharge::extractMomentum(), and Acts::SinglyCharged::SinglyCharged().