Analysis Software: BEmcRecEEMC Class Reference
BEmcRecEEMC Class Reference
#include <coresoftware/blob/master/offline/packages/CaloReco/BEmcRecEEMC.h>
Public Member Functions
BEmcRecEEMC ()
~BEmcRecEEMC () override
void CorrectEnergy (float energy, float x, float y, float &ecorr) override
void CorrectECore (float ecore, float x, float y, float &ecorecorr) override
void CorrectPosition (float energy, float x, float y, float &xcorr, float &ycorr) override
void CorrectShowerDepth (float energy, float x, float y, float z, float &xc, float &yc, float &zc) override
void LoadProfile (const std::string &fname) override
void GetImpactThetaPhi (float xg, float yg, float zg, float &theta, float &phi) override
Public Member Functions inherited from BEmcRec
BEmcRec ()
virtual ~BEmcRec ()
void SetVertex (float *vv)
void SetDim (int nx, int ny)
bool SetTowerGeometry (int ix, int iy, float xx, float yy, float zz)
bool GetTowerGeometry (int ix, int iy, TowerGeom &geom)
bool CompleteTowerGeometry ()
void PrintTowerGeometry (const std::string &fname)
void SetPlanarGeometry ()
void SetCylindricalGeometry ()
bool isCylindrical () const
void SetProfileProb (bool bprob)
void SetCalotype (int caloid)
void SetScinSize (float S_S)
int GetNx () const
int GetNy () const
int GetCalotype () const
float GetScinSize () const
float GetVx () const
float GetVy () const
float GetVz () const
void SetPeakThreshold (float Thresh)
float GetPeakThreshold ()
void SetTowerThreshold (float Thresh)
float GetTowerThreshold ()
void SetModules (std::vector< EmcModule > const *modules)
std::vector< EmcModule > * GetModules ()
std::vector< EmcCluster > * GetClusters ()
int iTowerDist (int ix1, int ix2)
float fTowerDist (float x1, float x2)
int FindClusters ()
void Momenta (std::vector< EmcModule > *, float &, float &, float &, float &, float &, float &, float thresh=0)
void Tower2Global (float E, float xC, float yC, float &xA, float &yA, float &zA)
float GetTowerEnergy (int iy, int iz, std::vector< EmcModule > *plist)
float PredictEnergy (float, float, float, int, int)
float PredictEnergyProb (float en, float xcg, float ycg, int ix, int iy)
virtual float PredictEnergyParam (float, float, float)
float GetProb (std::vector< EmcModule > HitList, float e, float xg, float yg, float zg, float &chi2, int &ndf)
virtual std::string Name () const
virtual void Name (const std::string &name)
Static Public Member Functions
static float GetImpactAngle (float e, float x, float y)
Static Public Member Functions inherited from BEmcRec
static int HitNCompare (const void *, const void *)
static int HitACompare (const void *, const void *)
static void CopyVector (int *, int *, int)
static void CopyVector (EmcModule *, EmcModule *, int)
static void ZeroVector (int *, int)
static void ZeroVector (float *, int)
static void ZeroVector (EmcModule *, int)
Additional Inherited Members
Protected Attributes inherited from BEmcRec
bool bCYL = true
bool bProfileProb = false
int fNx = -1
int fNy = -1
std::map< int, TowerGeom > fTowerGeom
float fVx = 0.
float fVy = 0.
float fVz = 0.
std::vector< EmcModule > * fModules
std::vector< EmcCluster > * fClusters
float fgTowerThresh = 0.01
float fgMinPeakEnergy = 0.08
BEmcProfile * _emcprof = nullptr
Static Protected Attributes inherited from BEmcRec
static int const fgMaxLen = 1000
Detailed Description
Definition at line 12 of file BEmcRecEEMC.h.
View newest version in sPHENIX GitHub at line 12 of file BEmcRecEEMC.h
Constructor & Destructor Documentation
BEmcRecEEMC::BEmcRecEEMC ()
Definition at line 11 of file BEmcRecEEMC.cc.
View newest version in sPHENIX GitHub at line 11 of file BEmcRecEEMC.cc
References BEmcRec::Name(), and BEmcRec::SetPlanarGeometry().
BEmcRecEEMC::~BEmcRecEEMC () inline override
Definition at line 16 of file BEmcRecEEMC.h.
View newest version in sPHENIX GitHub at line 16 of file BEmcRecEEMC.h
Member Function Documentation
void BEmcRecEEMC::CorrectECore (float ecore, float x, float y, float & ecorecorr) override virtual
Reimplemented from BEmcRec.
Definition at line 102 of file BEmcRecEEMC.cc.
View newest version in sPHENIX GitHub at line 102 of file BEmcRecEEMC.cc
void BEmcRecEEMC::CorrectEnergy (float energy, float x, float y, float & ecorr) override virtual
Reimplemented from BEmcRec.
Definition at line 96 of file BEmcRecEEMC.cc.
View newest version in sPHENIX GitHub at line 96 of file BEmcRecEEMC.cc
void BEmcRecEEMC::CorrectPosition (float energy, float x, float y, float & xcorr, float & ycorr) override virtual
Reimplemented from BEmcRec.
Definition at line 129 of file BEmcRecEEMC.cc.
View newest version in sPHENIX GitHub at line 129 of file BEmcRecEEMC.cc
References EmcCluster::ABS(), BEmcRec::fVz, rotate::log, EmcCluster::lowint(), t, BEmcRec::Tower2Global(), x, x0, KFPMath::xZero, y, and KFPMath::yZero.
void BEmcRecEEMC::CorrectShowerDepth (float energy, float x, float y, float z, float & xc, float & yc, float & zc) override virtual
Reimplemented from BEmcRec.
Definition at line 45 of file BEmcRecEEMC.cc.
View newest version in sPHENIX GitHub at line 45 of file BEmcRecEEMC.cc
References RawTowerDefs::EEMC, RawTowerDefs::EEMC_crystal, RawTowerDefs::EEMC_glass, BEmcRec::fVz, BEmcRec::GetCalotype(), BEmcRec::GetScinSize(), and rotate::log.
float BEmcRecEEMC::GetImpactAngle (float e, float x, float y) static
Definition at line 112 of file BEmcRecEEMC.cc.
View newest version in sPHENIX GitHub at line 112 of file BEmcRecEEMC.cc
void BEmcRecEEMC::GetImpactThetaPhi (float xg, float yg, float zg, float & theta, float & phi) override virtual
Reimplemented from BEmcRec.
Definition at line 23 of file BEmcRecEEMC.cc.
View newest version in sPHENIX GitHub at line 23 of file BEmcRecEEMC.cc
References BEmcRec::fVz.
void BEmcRecEEMC::LoadProfile (const std::string & fname) override virtual
Reimplemented from BEmcRec.
Definition at line 17 of file BEmcRecEEMC.cc.
View newest version in sPHENIX GitHub at line 17 of file BEmcRecEEMC.cc
References BEmcRec::_emcprof.
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/CaloReco/BEmcRecEEMC.h
coresoftware/blob/master/offline/packages/CaloReco/BEmcRecEEMC.cc