Analysis Software: analysis/blob/master/HF-Jet/HFMLTrigger_LANL/macros/OccupancySim.C File Reference
OccupancySim.C File Reference
#include "SaveCanvas.C"
#include "sPhenixStyle.C"
#include <TCanvas.h>
#include <TDatabasePDG.h>
#include <TFile.h>
#include <TH1D.h>
#include <TH1F.h>
#include <TH2F.h>
#include <TH3F.h>
#include <TLegend.h>
#include <TLine.h>
#include <TLorentzVector.h>
#include <TRandom3.h>
#include <TString.h>
#include <TTree.h>
#include <TVirtualFitter.h>
#include <assert.h>
#include <cmath>
#include <cstddef>
#include <iostream>
Typedefs
typedef vector< vector< TH1 * > > chipMultiplicitySet_vec
Functions
chipMultiplicitySet_vec MakeChipMultiplicitySet (TFile *file)
void Check (TFile *file)
TH1 * MakeCDF (TH1 *h)
chipMultiplicitySet_vec TriggerMultiplicity (chipMultiplicitySet_vec cm_MB, chipMultiplicitySet_vec cm_Trigger, const double mu_MB, const int n_Trigger, const double mu_Noise)
void OccupancySim (const TString infile="/sphenix/user/jinhuang/HF-jet/MVTX_Multiplicity/AuAu200MB_30cmVZ_Iter5/AuAu200MB_30cmVZ_Iter5_SUM.xml_HFMLTriggerOccupancy.root", const TString infile_trigger="/sphenix/user/jinhuang/HF-jet/MVTX_Multiplicity/AuAu200MB_10cmVZ_Iter5/AuAu200MB_10cmVZ_Iter5_SUM.xml_HFMLTriggerOccupancy.root", const TString disc="Au+Au MB, #sqrt{s_{NN}} = 200 GeV")
Variables
TFile * _file0 = NULL
TFile * _file_trigger = NULL
TString description
Typedef Documentation
typedef vector<vector<TH1 *> > chipMultiplicitySet_vec
Definition at line 33 of file OccupancySim.C.
View newest version in sPHENIX GitHub at line 33 of file OccupancySim.C
Function Documentation
void Check (TFile * file)
Definition at line 109 of file OccupancySim.C.
View newest version in sPHENIX GitHub at line 109 of file OccupancySim.C
References assert, description, hNormalization, ambiguity_solver_full_chain::idx, leg, norm, merge_hashes::p, and SaveCanvas().
TH1* MakeCDF (TH1 * h)
Definition at line 176 of file OccupancySim.C.
View newest version in sPHENIX GitHub at line 176 of file OccupancySim.C
References assert, and integral().
chipMultiplicitySet_vec MakeChipMultiplicitySet (TFile * file)
Definition at line 35 of file OccupancySim.C.
View newest version in sPHENIX GitHub at line 35 of file OccupancySim.C
References assert, description, h, ambiguity_solver_full_chain::idx, leg, merge_hashes::p, and SaveCanvas().
void OccupancySim (const TString infile = "/sphenix/user/jinhuang/HF-jet/MVTX_Multiplicity/AuAu200MB_30cmVZ_Iter5/AuAu200MB_30cmVZ_Iter5_SUM.xml_HFMLTriggerOccupancy.root", const TString infile_trigger = "/sphenix/user/jinhuang/HF-jet/MVTX_Multiplicity/AuAu200MB_10cmVZ_Iter5/AuAu200MB_10cmVZ_Iter5_SUM.xml_HFMLTriggerOccupancy.root", const TString disc = "Au+Au MB, #sqrt{s_{NN}} = 200 GeV")
Definition at line 361 of file OccupancySim.C.
View newest version in sPHENIX GitHub at line 361 of file OccupancySim.C
References _file0, _file_trigger, assert, Check(), description, Acts::UnitConstants::e, infile, MakeChipMultiplicitySet(), SetsPhenixStyle(), and TriggerMultiplicity().
chipMultiplicitySet_vec TriggerMultiplicity (chipMultiplicitySet_vec cm_MB, chipMultiplicitySet_vec cm_Trigger, const double mu_MB, const int n_Trigger, const double mu_Noise)
Definition at line 199 of file OccupancySim.C.
View newest version in sPHENIX GitHub at line 199 of file OccupancySim.C
References _file0, assert, Acts::UnitConstants::cm, description, Acts::UnitConstants::e, h, i, ambiguity_solver_full_chain::idx, layer, leg, line, MakeCDF(), merge_hashes::p, physmon_simulation::rnd, SaveCanvas(), and size.
Variable Documentation
TFile* _file0 = NULL
Definition at line 29 of file OccupancySim.C.
View newest version in sPHENIX GitHub at line 29 of file OccupancySim.C
TFile* _file_trigger = NULL
Definition at line 30 of file OccupancySim.C.
View newest version in sPHENIX GitHub at line 30 of file OccupancySim.C
TString description
Definition at line 31 of file OccupancySim.C.
View newest version in sPHENIX GitHub at line 31 of file OccupancySim.C