Analysis Software: Acts::MutablePodioTrackContainer Class Reference
Acts::MutablePodioTrackContainer Class Reference
#include <acts/blob/sPHENIX/Plugins/Podio/include/Acts/Plugins/Podio/PodioTrackContainer.hpp>
Public Member Functions
MutablePodioTrackContainer (const PodioUtil::ConversionHelper &helper)
MutablePodioTrackContainer (MutablePodioTrackContainer &&other)=default
MutablePodioTrackContainer (const ConstPodioTrackContainer &other)
std::any component_impl (HashedString key, IndexType itrack)
std::any component_impl (HashedString key, IndexType itrack) const
bool hasColumn_impl (HashedString key) const
std::size_t size_impl () const
const Surface * referenceSurface_impl (IndexType itrack) const
void setReferenceSurface_impl (IndexType itrack, std::shared_ptr< const Surface > surface)
IndexType addTrack_impl ()
void removeTrack_impl (IndexType itrack)
template<typename T >
constexpr void addColumn_impl (const std::string &key)
Parameters parameters (IndexType itrack)
ConstParameters parameters (IndexType itrack) const
Covariance covariance (IndexType itrack)
ConstCovariance covariance (IndexType itrack) const
void copyDynamicFrom_impl (IndexType dstIdx, const MutablePodioTrackContainer &src, IndexType srcIdx)
void ensureDynamicColumns_impl (const MutablePodioTrackContainer &other)
void reserve (IndexType)
ActsPodioEdm::TrackCollection & trackCollection ()
void releaseInto (podio::Frame &frame, const std::string &suffix="")
Public Attributes
m_collection
Private Member Functions
std::shared_ptr< const Surface > getOrCreateSurface (IndexType itrack)
Private Attributes
friend PodioTrackContainerBase
std::unique_ptr
< ActsPodioEdm::TrackCollection > m_collection
std::unordered_map
< HashedString,
std::unique_ptr
< podio_detail::DynamicColumnBase > > m_dynamic
Additional Inherited Members
Public Types inherited from Acts::PodioTrackContainerBase
using IndexType = MultiTrajectoryTraits::IndexType
using Parameters = typename detail_lt::Types< eBoundSize, false >::CoefficientsMap
using Covariance = typename detail_lt::Types< eBoundSize, false >::CovarianceMap
using ConstParameters = typename detail_lt::Types< eBoundSize, true >::CoefficientsMap
using ConstCovariance = typename detail_lt::Types< eBoundSize, true >::CovarianceMap
Static Public Attributes inherited from Acts::PodioTrackContainerBase
static constexpr auto kInvalid = MultiTrajectoryTraits::kInvalid
static constexpr auto MeasurementSizeMax
Protected Member Functions inherited from Acts::PodioTrackContainerBase
PodioTrackContainerBase (const PodioUtil::ConversionHelper &helper)
Protected Attributes inherited from Acts::PodioTrackContainerBase
std::vector< std::shared_ptr
< const Surface > > m_surfaces
Detailed Description
Definition at line 128 of file PodioTrackContainer.hpp.
View newest version in sPHENIX GitHub at line 128 of file PodioTrackContainer.hpp
Constructor & Destructor Documentation
Acts::MutablePodioTrackContainer::MutablePodioTrackContainer (const PodioUtil::ConversionHelper & helper) inline
Definition at line 130 of file PodioTrackContainer.hpp.
View newest version in sPHENIX GitHub at line 130 of file PodioTrackContainer.hpp
Acts::MutablePodioTrackContainer::MutablePodioTrackContainer (MutablePodioTrackContainer && other) default
Acts::MutablePodioTrackContainer::MutablePodioTrackContainer (const ConstPodioTrackContainer & other)
Member Function Documentation
template<typename T > constexpr void Acts::MutablePodioTrackContainer::addColumn_impl (const std::string & key) inline
Definition at line 198 of file PodioTrackContainer.hpp.
View newest version in sPHENIX GitHub at line 198 of file PodioTrackContainer.hpp
References Acts::hashString().
IndexType Acts::MutablePodioTrackContainer::addTrack_impl () inline
Definition at line 185 of file PodioTrackContainer.hpp.
View newest version in sPHENIX GitHub at line 185 of file PodioTrackContainer.hpp
References Acts::PodioUtil::kNoSurface, Acts::PodioTrackContainerBase::m_surfaces, and vec.
std::any Acts::MutablePodioTrackContainer::component_impl (HashedString key, IndexType itrack) inline
Definition at line 155 of file PodioTrackContainer.hpp.
View newest version in sPHENIX GitHub at line 155 of file PodioTrackContainer.hpp
std::any Acts::MutablePodioTrackContainer::component_impl (HashedString key, IndexType itrack) const inline
Definition at line 159 of file PodioTrackContainer.hpp.
View newest version in sPHENIX GitHub at line 159 of file PodioTrackContainer.hpp
void Acts::MutablePodioTrackContainer::copyDynamicFrom_impl (IndexType dstIdx, const MutablePodioTrackContainer & src, IndexType srcIdx)
Covariance Acts::MutablePodioTrackContainer::covariance (IndexType itrack) inline
Definition at line 212 of file PodioTrackContainer.hpp.
View newest version in sPHENIX GitHub at line 212 of file PodioTrackContainer.hpp
ConstCovariance Acts::MutablePodioTrackContainer::covariance (IndexType itrack) const inline
Definition at line 216 of file PodioTrackContainer.hpp.
View newest version in sPHENIX GitHub at line 216 of file PodioTrackContainer.hpp
void Acts::MutablePodioTrackContainer::ensureDynamicColumns_impl (const MutablePodioTrackContainer & other)
std::shared_ptr<const Surface> Acts::MutablePodioTrackContainer::getOrCreateSurface (IndexType itrack) inline private
Definition at line 144 of file PodioTrackContainer.hpp.
View newest version in sPHENIX GitHub at line 144 of file PodioTrackContainer.hpp
References Acts::PodioUtil::convertSurfaceFromPodio(), and Acts::PodioTrackContainerBase::m_surfaces.
bool Acts::MutablePodioTrackContainer::hasColumn_impl (HashedString key) const inline
Definition at line 163 of file PodioTrackContainer.hpp.
View newest version in sPHENIX GitHub at line 163 of file PodioTrackContainer.hpp
Parameters Acts::MutablePodioTrackContainer::parameters (IndexType itrack) inline
Definition at line 203 of file PodioTrackContainer.hpp.
View newest version in sPHENIX GitHub at line 203 of file PodioTrackContainer.hpp
ConstParameters Acts::MutablePodioTrackContainer::parameters (IndexType itrack) const inline
Definition at line 207 of file PodioTrackContainer.hpp.
View newest version in sPHENIX GitHub at line 207 of file PodioTrackContainer.hpp
const Surface* Acts::MutablePodioTrackContainer::referenceSurface_impl (IndexType itrack) const inline
Definition at line 170 of file PodioTrackContainer.hpp.
View newest version in sPHENIX GitHub at line 170 of file PodioTrackContainer.hpp
References Acts::PodioTrackContainerBase::m_surfaces.
void Acts::MutablePodioTrackContainer::releaseInto (podio::Frame & frame, const std::string & suffix = "") inline
Definition at line 232 of file PodioTrackContainer.hpp.
View newest version in sPHENIX GitHub at line 232 of file PodioTrackContainer.hpp
References Acts::PodioTrackContainerBase::m_surfaces, testing::internal::move(), and physmon_simulation::s.
void Acts::MutablePodioTrackContainer::removeTrack_impl (IndexType itrack)
void Acts::MutablePodioTrackContainer::reserve (IndexType) inline
Definition at line 228 of file PodioTrackContainer.hpp.
View newest version in sPHENIX GitHub at line 228 of file PodioTrackContainer.hpp
void Acts::MutablePodioTrackContainer::setReferenceSurface_impl (IndexType itrack, std::shared_ptr< const Surface > surface) inline
Definition at line 174 of file PodioTrackContainer.hpp.
View newest version in sPHENIX GitHub at line 174 of file PodioTrackContainer.hpp
References Acts::PodioUtil::convertSurfaceToPodio(), Acts::PodioTrackContainerBase::m_surfaces, and testing::internal::move().
std::size_t Acts::MutablePodioTrackContainer::size_impl () const inline
Definition at line 167 of file PodioTrackContainer.hpp.
View newest version in sPHENIX GitHub at line 167 of file PodioTrackContainer.hpp
ActsPodioEdm::TrackCollection& Acts::MutablePodioTrackContainer::trackCollection () inline
Definition at line 230 of file PodioTrackContainer.hpp.
View newest version in sPHENIX GitHub at line 230 of file PodioTrackContainer.hpp
Member Data Documentation
Acts::MutablePodioTrackContainer::m_collection
Initial value:
{std::make_unique<ActsPodioEdm::TrackCollection>()} {
    populateSurfaceBuffer(m_helper, *m_collection, m_surfaces);
  }
  MutablePodioTrackContainer(const MutablePodioTrackContainer& other)
Definition at line 132 of file PodioTrackContainer.hpp.
View newest version in sPHENIX GitHub at line 132 of file PodioTrackContainer.hpp
std::unique_ptr<ActsPodioEdm::TrackCollection> Acts::MutablePodioTrackContainer::m_collection private
Definition at line 250 of file PodioTrackContainer.hpp.
View newest version in sPHENIX GitHub at line 250 of file PodioTrackContainer.hpp
std::unordered_map<HashedString, std::unique_ptr<podio_detail::DynamicColumnBase> > Acts::MutablePodioTrackContainer::m_dynamic private
Definition at line 253 of file PodioTrackContainer.hpp.
View newest version in sPHENIX GitHub at line 253 of file PodioTrackContainer.hpp
friend Acts::MutablePodioTrackContainer::PodioTrackContainerBase private
Definition at line 248 of file PodioTrackContainer.hpp.
View newest version in sPHENIX GitHub at line 248 of file PodioTrackContainer.hpp
The documentation for this class was generated from the following file:
acts/blob/sPHENIX/Plugins/Podio/include/Acts/Plugins/Podio/PodioTrackContainer.hpp