Analysis Software: sPHENIXActsDetectorElement Class Reference
sPHENIXActsDetectorElement Class Reference
#include <coresoftware/blob/master/offline/packages/trackbase/sPHENIXActsDetectorElement.h>
Public Member Functions
sPHENIXActsDetectorElement ()=delete
sPHENIXActsDetectorElement (const Identifier &identifier, const TGeoNode &tGeoNode, const TGeoMatrix &tGeoMatrix=TGeoIdentity(), const std::string &axes="XYZ", double scalor=10., std::shared_ptr< const Acts::ISurfaceMaterial > material=nullptr)
sPHENIXActsDetectorElement (const Identifier &identifier, const TGeoNode &tGeoNode, Acts::Transform3 &tgTransform, std::shared_ptr< const Acts::PlanarBounds > tgBounds, double tgThickness=0.)
sPHENIXActsDetectorElement (const Identifier &identifier, const TGeoNode &tGeoNode, Acts::Transform3 &tgTransform, std::shared_ptr< const Acts::DiscBounds > tgBounds, double tgThickness=0.)
~sPHENIXActsDetectorElement () override
const Acts::Transform3 & transform (const Acts::GeometryContext &ctxt) const override
Public Member Functions inherited from Acts::TGeoDetectorElement
TGeoDetectorElement (const Identifier &identifier, const TGeoNode &tGeoNode, const TGeoMatrix &tGeoMatrix=TGeoIdentity(), const std::string &axes="XYZ", double scalor=10., std::shared_ptr< const Acts::ISurfaceMaterial > material=nullptr)
TGeoDetectorElement (const Identifier &identifier, const TGeoNode &tGeoNode, const Transform3 &tgTransform, const std::shared_ptr< const PlanarBounds > &tgBounds, double tgThickness=0.)
TGeoDetectorElement (const Identifier &identifier, const TGeoNode &tGeoNode, const Transform3 &tgTransform, const std::shared_ptr< const DiscBounds > &tgBounds, double tgThickness=0.)
~TGeoDetectorElement () override
Identifier identifier () const final
Retrieve the Identifier.
const Surface & surface () const override
Return surface associated with this detector element.
Surface & surface () override
const std::shared_ptr< const
DigitizationModule > digitizationModule () const final
Retrieve the DigitizationModule.
double thickness () const override
Returns the thickness of the module.
const TGeoNode & tgeoNode () const
Return the TGeoNode for back navigation.
Private Attributes
std::map< unsigned int,
unsigned int > base_layer_map = { {10, 0}, {12,3}, {14,7}, {16,55} }
Additional Inherited Members
Public Types inherited from Acts::TGeoDetectorElement
using ContextType = GeometryContext
Broadcast the context type.
Detailed Description
Definition at line 16 of file sPHENIXActsDetectorElement.h.
View newest version in sPHENIX GitHub at line 16 of file sPHENIXActsDetectorElement.h
Constructor & Destructor Documentation
sPHENIXActsDetectorElement::sPHENIXActsDetectorElement () delete
sPHENIXActsDetectorElement::sPHENIXActsDetectorElement (const Identifier & identifier, const TGeoNode & tGeoNode, const TGeoMatrix & tGeoMatrix = TGeoIdentity(), const std::string & axes = "XYZ", double scalor = 10., std::shared_ptr< const Acts::ISurfaceMaterial > material = nullptr) inline
Definition at line 22 of file sPHENIXActsDetectorElement.h.
View newest version in sPHENIX GitHub at line 22 of file sPHENIXActsDetectorElement.h
sPHENIXActsDetectorElement::sPHENIXActsDetectorElement (const Identifier & identifier, const TGeoNode & tGeoNode, Acts::Transform3 & tgTransform, std::shared_ptr< const Acts::PlanarBounds > tgBounds, double tgThickness = 0.) inline
Definition at line 31 of file sPHENIXActsDetectorElement.h.
View newest version in sPHENIX GitHub at line 31 of file sPHENIXActsDetectorElement.h
sPHENIXActsDetectorElement::sPHENIXActsDetectorElement (const Identifier & identifier, const TGeoNode & tGeoNode, Acts::Transform3 & tgTransform, std::shared_ptr< const Acts::DiscBounds > tgBounds, double tgThickness = 0.) inline
Definition at line 40 of file sPHENIXActsDetectorElement.h.
View newest version in sPHENIX GitHub at line 40 of file sPHENIXActsDetectorElement.h
sPHENIXActsDetectorElement::~sPHENIXActsDetectorElement () override default
Member Function Documentation
const Acts::Transform3 & sPHENIXActsDetectorElement::transform (const Acts::GeometryContext & gctx) const override virtual
Return local to global transform associated with this identifier
Parameters
gctx The current geometry context object, e.g. alignment
Reimplemented from Acts::TGeoDetectorElement.
Definition at line 9 of file sPHENIXActsDetectorElement.cc.
View newest version in sPHENIX GitHub at line 9 of file sPHENIXActsDetectorElement.cc
References base_layer_map, Acts::GeometryObject::geometryId(), alignmentTransformationContainer::getMap(), layer, PHWHERE, Acts::TGeoDetectorElement::surface(), Acts::Test::transform, alignmentTransformationContainer::use_alignment, and Acts::GeometryIdentifier::volume().
Member Data Documentation
std::map<unsigned int, unsigned int> sPHENIXActsDetectorElement::base_layer_map = { {10, 0}, {12,3}, {14,7}, {16,55} } private
Definition at line 55 of file sPHENIXActsDetectorElement.h.
View newest version in sPHENIX GitHub at line 55 of file sPHENIXActsDetectorElement.h
Referenced by transform().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/trackbase/sPHENIXActsDetectorElement.h
coresoftware/blob/master/offline/packages/trackbase/sPHENIXActsDetectorElement.cc