Analysis Software: ActsExamples::HelloWhiteBoardAlgorithm Class Reference
ActsExamples::HelloWhiteBoardAlgorithm Class Reference
Example algorithm that reads/writes data from/to the event store.
#include <acts/blob/sPHENIX/Examples/Run/HelloWorld/HelloWhiteBoardAlgorithm.hpp>
Classes
struct Config
Public Member Functions
HelloWhiteBoardAlgorithm (const Config &cfg, Acts::Logging::Level level=Acts::Logging::INFO)
ActsExamples::ProcessCode execute (const AlgorithmContext &ctx) const override
Read input and copy to the output.
Public Member Functions inherited from ActsExamples::IAlgorithm
IAlgorithm (std::string name, Acts::Logging::Level level=Acts::Logging::INFO)
std::string name () const override
The algorithm name.
ProcessCode internalExecute (const AlgorithmContext &context) final
ProcessCode initialize () override
Initialize the algorithm.
ProcessCode finalize () override
Finalize the algorithm.
Public Attributes
ReadDataHandle
< HelloDataCollection > m_readHandle {this, "Input"}
WriteDataHandle
< HelloDataCollection > m_writeHandle {this, "Output"}
Private Attributes
Config m_cfg
Additional Inherited Members
Protected Member Functions inherited from ActsExamples::IAlgorithm
const Acts::Logger & logger () const
Detailed Description
Example algorithm that reads/writes data from/to the event store.
Definition at line 22 of file HelloWhiteBoardAlgorithm.hpp.
View newest version in sPHENIX GitHub at line 22 of file HelloWhiteBoardAlgorithm.hpp
Constructor & Destructor Documentation
ActsExamples::HelloWhiteBoardAlgorithm::HelloWhiteBoardAlgorithm (const Config & cfg, Acts::Logging::Level level = Acts::Logging::INFO)
Definition at line 15 of file HelloWhiteBoardAlgorithm.cpp.
View newest version in sPHENIX GitHub at line 15 of file HelloWhiteBoardAlgorithm.cpp
References ActsExamples::WriteDataHandle< T >::initialize(), ActsExamples::ReadDataHandle< T >::initialize(), ActsExamples::HelloWhiteBoardAlgorithm::Config::input, m_cfg, m_readHandle, m_writeHandle, and ActsExamples::HelloWhiteBoardAlgorithm::Config::output.
Member Function Documentation
ActsExamples::ProcessCode ActsExamples::HelloWhiteBoardAlgorithm::execute (const AlgorithmContext & ctx) const override virtual
Read input and copy to the output.
Implements ActsExamples::IAlgorithm.
Definition at line 29 of file HelloWhiteBoardAlgorithm.cpp.
View newest version in sPHENIX GitHub at line 29 of file HelloWhiteBoardAlgorithm.cpp
References ACTS_INFO, ACTS_VERBOSE, in, m_cfg(), testing::internal::move(), and SUCCESS.
Member Data Documentation
Config ActsExamples::HelloWhiteBoardAlgorithm::m_cfg private
Definition at line 41 of file HelloWhiteBoardAlgorithm.hpp.
View newest version in sPHENIX GitHub at line 41 of file HelloWhiteBoardAlgorithm.hpp
Referenced by HelloWhiteBoardAlgorithm().
ReadDataHandle<HelloDataCollection> ActsExamples::HelloWhiteBoardAlgorithm::m_readHandle {this, "Input"}
Definition at line 37 of file HelloWhiteBoardAlgorithm.hpp.
View newest version in sPHENIX GitHub at line 37 of file HelloWhiteBoardAlgorithm.hpp
Referenced by HelloWhiteBoardAlgorithm().
WriteDataHandle<HelloDataCollection> ActsExamples::HelloWhiteBoardAlgorithm::m_writeHandle {this, "Output"}
Definition at line 38 of file HelloWhiteBoardAlgorithm.hpp.
View newest version in sPHENIX GitHub at line 38 of file HelloWhiteBoardAlgorithm.hpp
Referenced by HelloWhiteBoardAlgorithm().
The documentation for this class was generated from the following files:
acts/blob/sPHENIX/Examples/Run/HelloWorld/HelloWhiteBoardAlgorithm.hpp
acts/blob/sPHENIX/Examples/Run/HelloWorld/HelloWhiteBoardAlgorithm.cpp