Analysis Software: OnlMon/blob/main/subsystems/ll1/ll1setup.cc File Reference
ll1setup.cc File Reference
#include "LL1HEADER.h"
#include <onlmon/OnlMon.h>
#include <Event/Event.h>
#include <Event/EventTypes.h>
#include <Event/msg_profile.h>
#include <TFile.h>
#include <TTree.h>
#include <TSystem.h>
#include <cstdlib>
#include <cmath>
#include <iostream>
#include <fstream>
#include <sstream>
Functions
void ll1setup (Event *evt, LL1HEADER *&ll1h)
Function Documentation
void ll1setup (Event * evt, LL1HEADER *& ll1h)
Definition at line 23 of file ll1setup.cc.
View newest version in sPHENIX GitHub at line 23 of file ll1setup.cc
References LL1HEADER::channel, LL1HEADER::chargesum_n, LL1HEADER::chargesum_n1, LL1HEADER::chargesum_n2, LL1HEADER::chargesum_s, LL1HEADER::chargesum_s1, LL1HEADER::chargesum_s2, LL1HEADER::clock, LL1HEADER::evtnr, Event::getPacket(), Event::getRunNumber(), LL1HEADER::idxhitn, LL1HEADER::idxhits, LL1HEADER::idxsample, it, Packet::iValue(), NADCSH, NCH, LL1HEADER::nhit_n, LL1HEADER::nhit_n1, LL1HEADER::nhit_n2, LL1HEADER::nhit_s, LL1HEADER::nhit_s1, LL1HEADER::nhit_s2, NHITCHANNEL, NRSAM, NTRIGWORDS, NXMIT, merge_hashes::p, PACKET, LL1HEADER::runnumber, LL1HEADER::timesum_n, LL1HEADER::timesum_n1, LL1HEADER::timesum_n2, LL1HEADER::timesum_s, LL1HEADER::timesum_s1, LL1HEADER::timesum_s2, and LL1HEADER::triggerwords.
Referenced by LL1Mon::process_event().