Analysis Software: JETSCAPE/blob/main/jail/pwg2_reader.cxx File Reference
pwg2_reader.cxx File Reference
#include <iostream>
#include <fstream>
#include <memory>
#include <chrono>
#include <thread>
#include "gzstream.h"
#include "PartonShower.h"
#include "JetScapeLogger.h"
#include "JetScapeReader.h"
#include "JetScapeBanner.h"
#include "fjcore.hh"
#include <GTL/dfs.h>
#include <TH1.h>
#include <TFile.h>
Functions
void AnalyzeGraph (shared_ptr< PartonShower > mS)
ostream & operator<< (ostream &ostr, const PseudoJet &jet)
overloaded jet info output
int main (int argc, char **argv)
Function Documentation
void AnalyzeGraph (shared_ptr< PartonShower > mS)
int main (int argc, char ** argv)
Definition at line 54 of file pwg2_reader.cxx.
View newest version in sPHENIX GitHub at line 54 of file pwg2_reader.cxx
References antikt_algorithm, INTTVtxZ::dphi, dR(), eta, event, fout, i, Acts::Logging::INFO, INFO_NICE, j, line, AjParameters::max_track_rap, igzstream::open(), merge_hashes::p, particles, Jetscape::pi, Acts::Test::pos, physmon_track_finding_ttbar::pt, Acts::IntegrationTest::R, summary::reader, SelectorAbsEtaMax(), SelectorAbsRapMax(), SelectorPtMin(), SelectorPtRange(), Jetscape::sigmaGen, and sorted_by_pt().
ostream & operator<< (ostream & ostr, const PseudoJet & jet)
overloaded jet info output
Definition at line 322 of file pwg2_reader.cxx.
View newest version in sPHENIX GitHub at line 322 of file pwg2_reader.cxx