Analysis Software: kdfinder::LinearFit< T > Class Template Reference
kdfinder::LinearFit< T > Class Template Reference
#include <coresoftware/blob/master/offline/packages/PHTpcTracker/externals/kdfinder.hpp>
Public Member Functions
LinearFit ()
Static Public Member Functions
static Line< T > * RegularFit (const std::vector< std::vector< T >> &hits)
static Line< T > * RobustFit (const std::vector< std::vector< T >> &hits, Line< T > *line=0)
Static Private Member Functions
static T rofunc (T &a, const T b, T &abdev, const std::vector< std::vector< T >> &hits)
static T select (const int k, std::vector< T > &arr)
static T SQR (const T a)
static T SIGN (const T &a, const T &b)
static float SIGN (const float &a, const double &b)
static float SIGN (const double &a, const float &b)
static void SWAP (T &a, T &b)
Detailed Description
template<class T>
class kdfinder::LinearFit< T >
Definition at line 2061 of file kdfinder.hpp.
View newest version in sPHENIX GitHub at line 2061 of file kdfinder.hpp
Constructor & Destructor Documentation
template<class T > kdfinder::LinearFit< T >::LinearFit () inline
Definition at line 2064 of file kdfinder.hpp.
View newest version in sPHENIX GitHub at line 2064 of file kdfinder.hpp
Member Function Documentation
template<class T > static Line<T>* kdfinder::LinearFit< T >::RegularFit (const std::vector< std::vector< T >> & hits) inline static
Definition at line 2066 of file kdfinder.hpp.
View newest version in sPHENIX GitHub at line 2066 of file kdfinder.hpp
References KFPMath::a, KFPMath::b, i, line, n, t, and Acts::UnitConstants::T.
Referenced by kdfinder::LinearFit< T >::RobustFit(), and kdfinder::TrackCandidate< T >::szFit().
template<class T > static Line<T>* kdfinder::LinearFit< T >::RobustFit (const std::vector< std::vector< T >> & hits, Line< T > * line = 0) inline static
Definition at line 2108 of file kdfinder.hpp.
View newest version in sPHENIX GitHub at line 2108 of file kdfinder.hpp
References KFPMath::a, kdfinder::abs(), KFPMath::b, b1, std::tr1::f1, f2(), line, n, kdfinder::LinearFit< T >::RegularFit(), kdfinder::LinearFit< T >::rofunc(), kdfinder::LinearFit< T >::SIGN(), and Acts::UnitConstants::T.
Referenced by kdfinder::TrackCandidate< T >::szFit().
template<class T > static T kdfinder::LinearFit< T >::rofunc (T & a, const T b, T & abdev, const std::vector< std::vector< T >> & hits) inline static private
Definition at line 2173 of file kdfinder.hpp.
View newest version in sPHENIX GitHub at line 2173 of file kdfinder.hpp
References KFPMath::a, kdfinder::abs(), d, j, n, kdfinder::LinearFit< T >::select(), sum(), and Acts::UnitConstants::T.
Referenced by kdfinder::LinearFit< T >::RobustFit().
template<class T > static T kdfinder::LinearFit< T >::select (const int k, std::vector< T > & arr) inline static private
Definition at line 2209 of file kdfinder.hpp.
View newest version in sPHENIX GitHub at line 2209 of file kdfinder.hpp
References KFPMath::a, i, j, k, n, kdfinder::LinearFit< T >::SWAP(), and Acts::UnitConstants::T.
Referenced by kdfinder::LinearFit< T >::rofunc().
template<class T > static T kdfinder::LinearFit< T >::SIGN (const T & a, const T & b) inline static private
Definition at line 2275 of file kdfinder.hpp.
View newest version in sPHENIX GitHub at line 2275 of file kdfinder.hpp
References KFPMath::a.
Referenced by kdfinder::LinearFit< T >::RobustFit().
template<class T > static float kdfinder::LinearFit< T >::SIGN (const float & a, const double & b) inline static private
Definition at line 2276 of file kdfinder.hpp.
View newest version in sPHENIX GitHub at line 2276 of file kdfinder.hpp
References KFPMath::a.
template<class T > static float kdfinder::LinearFit< T >::SIGN (const double & a, const float & b) inline static private
Definition at line 2277 of file kdfinder.hpp.
View newest version in sPHENIX GitHub at line 2277 of file kdfinder.hpp
References KFPMath::a.
template<class T > static T kdfinder::LinearFit< T >::SQR (const T a) inline static private
Definition at line 2274 of file kdfinder.hpp.
View newest version in sPHENIX GitHub at line 2274 of file kdfinder.hpp
References KFPMath::a.
template<class T > static void kdfinder::LinearFit< T >::SWAP (T & a, T & b) inline static private
Definition at line 2278 of file kdfinder.hpp.
View newest version in sPHENIX GitHub at line 2278 of file kdfinder.hpp
References KFPMath::a, KFPMath::b, and Acts::UnitConstants::T.
Referenced by kdfinder::LinearFit< T >::select().
The documentation for this class was generated from the following file:
coresoftware/blob/master/offline/packages/PHTpcTracker/externals/kdfinder.hpp