Analysis Software: Acts::Experimental::DetectorVolumeFactory Class Reference
Acts::Experimental::DetectorVolumeFactory Class Reference
A detector volume factory which first constructs the detector volume and then constructs the portals. This ensures that the std::shared_ptr holding the detector volume is not weak when assigning to the portals.
#include <acts/blob/sPHENIX/Core/include/Acts/Detector/DetectorVolume.hpp>
Static Public Member Functions
static std::shared_ptr
< DetectorVolume > construct (const PortalGenerator &portalGenerator, const GeometryContext &gctx, const std::string &name, const Transform3 &transform, std::shared_ptr< VolumeBounds > bounds, const std::vector< std::shared_ptr< Surface >> &surfaces, const std::vector< std::shared_ptr< DetectorVolume >> &volumes, DetectorVolumeUpdator detectorVolumeUpdator, SurfaceCandidatesUpdator surfaceCandidateUpdator)
Create a detector volume - from factory.
static std::shared_ptr
< DetectorVolume > construct (const PortalGenerator &portalGenerator, const GeometryContext &gctx, std::string name, const Transform3 &transform, std::shared_ptr< VolumeBounds > bounds, SurfaceCandidatesUpdator surfaceCandidateUpdator)
Create a detector volume - from factory.
Detailed Description
A detector volume factory which first constructs the detector volume and then constructs the portals. This ensures that the std::shared_ptr holding the detector volume is not weak when assigning to the portals.
Definition at line 409 of file DetectorVolume.hpp.
View newest version in sPHENIX GitHub at line 409 of file DetectorVolume.hpp
Member Function Documentation
static std::shared_ptr<DetectorVolume> Acts::Experimental::DetectorVolumeFactory::construct (const PortalGenerator & portalGenerator, const GeometryContext & gctx, const std::string & name, const Transform3 & transform, std::shared_ptr< VolumeBounds > bounds, const std::vector< std::shared_ptr< Surface >> & surfaces, const std::vector< std::shared_ptr< DetectorVolume >> & volumes, DetectorVolumeUpdator detectorVolumeUpdator, SurfaceCandidatesUpdator surfaceCandidateUpdator) inline static
Create a detector volume - from factory.
Definition at line 412 of file DetectorVolume.hpp.
View newest version in sPHENIX GitHub at line 412 of file DetectorVolume.hpp
References Acts::Experimental::DetectorVolume::makeShared(), testing::internal::move(), and volumes.
Referenced by BOOST_AUTO_TEST_CASE(), ActsExamples::MockupSectorBuilder::buildChamber(), ActsExamples::MockupSectorBuilder::buildSector(), CompBuilder::construct(), and Acts::Experimental::DetectorVolumeBuilder::construct().
static std::shared_ptr<DetectorVolume> Acts::Experimental::DetectorVolumeFactory::construct (const PortalGenerator & portalGenerator, const GeometryContext & gctx, std::string name, const Transform3 & transform, std::shared_ptr< VolumeBounds > bounds, SurfaceCandidatesUpdator surfaceCandidateUpdator) inline static
Create a detector volume - from factory.
Definition at line 428 of file DetectorVolume.hpp.
View newest version in sPHENIX GitHub at line 428 of file DetectorVolume.hpp
References Acts::Experimental::DetectorVolume::makeShared(), and testing::internal::move().
The documentation for this class was generated from the following file:
acts/blob/sPHENIX/Core/include/Acts/Detector/DetectorVolume.hpp