Analysis Software: InttRawHitv1 Class Reference
InttRawHitv1 Class Reference
#include <coresoftware/blob/master/offline/framework/ffarawobjects/InttRawHitv1.h>
Public Member Functions
InttRawHitv1 ()=default
InttRawHitv1 (InttRawHit *intthit)
~InttRawHitv1 () override=default
void identify (std::ostream &os=std::cout) const override
uint64_t get_bco () const override
void set_bco (const uint64_t val) override
int32_t get_packetid () const override
void set_packetid (const int32_t val) override
uint32_t get_word () const override
void set_word (uint32_t val) override
uint16_t get_fee () const override
void set_fee (uint16_t val) override
uint16_t get_channel_id () const override
void set_channel_id (uint16_t val) override
uint16_t get_chip_id () const override
void set_chip_id (uint16_t val) override
uint16_t get_adc () const override
void set_adc (uint16_t val) override
uint16_t get_FPHX_BCO () const override
void set_FPHX_BCO (uint16_t val) override
uint16_t get_full_FPHX () const override
void set_full_FPHX (uint16_t val) override
uint16_t get_full_ROC () const override
void set_full_ROC (uint16_t val) override
uint16_t get_amplitude () const override
void set_amplitude (uint16_t val) override
Public Member Functions inherited from InttRawHit
InttRawHit ()=default
virtual ~InttRawHit ()=default
Public Member Functions inherited from PHObject
PHObject ()
ctor
~PHObject () override
dtor
virtual PHObject * CloneMe () const
Virtual copy constructor.
virtual PHObject * clone () const final
PHObject * Clone (const char *newname="") const final
void Copy (TObject &object) const final
virtual void Reset ()
Clear Event.
virtual int isValid () const
isValid returns non zero if object contains vailid data
virtual int Integrate () const
virtual int Integrate (PHObject *)
virtual void CopyFrom (const PHObject *obj)
Protected Attributes
uint64_t bco = std::numeric_limits<uint64_t>::max()
int32_t packetid = std::numeric_limits<int32_t>::max()
uint32_t word = std::numeric_limits<uint32_t>::max()
uint16_t fee = std::numeric_limits<uint16_t>::max()
uint16_t channel_id = std::numeric_limits<uint16_t>::max()
uint16_t chip_id = std::numeric_limits<uint16_t>::max()
uint16_t adc = std::numeric_limits<uint16_t>::max()
uint16_t FPHX_BCO = std::numeric_limits<uint16_t>::max()
uint16_t full_FPHX = std::numeric_limits<uint16_t>::max()
uint16_t full_ROC = std::numeric_limits<uint16_t>::max()
uint16_t amplitude = std::numeric_limits<uint16_t>::max()
Detailed Description
Definition at line 9 of file InttRawHitv1.h.
View newest version in sPHENIX GitHub at line 9 of file InttRawHitv1.h
Constructor & Destructor Documentation
InttRawHitv1::InttRawHitv1 () default
InttRawHitv1::InttRawHitv1 (InttRawHit * intthit)
Definition at line 3 of file InttRawHitv1.cc.
View newest version in sPHENIX GitHub at line 3 of file InttRawHitv1.cc
References InttRawHit::get_adc(), InttRawHit::get_amplitude(), InttRawHit::get_bco(), InttRawHit::get_channel_id(), InttRawHit::get_chip_id(), InttRawHit::get_fee(), InttRawHit::get_FPHX_BCO(), InttRawHit::get_full_FPHX(), InttRawHit::get_full_ROC(), InttRawHit::get_packetid(), InttRawHit::get_word(), set_adc(), set_amplitude(), set_bco(), set_channel_id(), set_chip_id(), set_fee(), set_FPHX_BCO(), set_full_FPHX(), set_full_ROC(), set_packetid(), and set_word().
InttRawHitv1::~InttRawHitv1 () override default
Member Function Documentation
uint16_t InttRawHitv1::get_adc () const inline override virtual
Reimplemented from InttRawHit.
Definition at line 47 of file InttRawHitv1.h.
View newest version in sPHENIX GitHub at line 47 of file InttRawHitv1.h
References adc.
uint16_t InttRawHitv1::get_amplitude () const inline override virtual
Reimplemented from InttRawHit.
Definition at line 63 of file InttRawHitv1.h.
View newest version in sPHENIX GitHub at line 63 of file InttRawHitv1.h
References amplitude.
uint64_t InttRawHitv1::get_bco () const inline override virtual
Reimplemented from InttRawHit.
Definition at line 23 of file InttRawHitv1.h.
View newest version in sPHENIX GitHub at line 23 of file InttRawHitv1.h
References bco.
uint16_t InttRawHitv1::get_channel_id () const inline override virtual
Reimplemented from InttRawHit.
Definition at line 39 of file InttRawHitv1.h.
View newest version in sPHENIX GitHub at line 39 of file InttRawHitv1.h
References channel_id.
uint16_t InttRawHitv1::get_chip_id () const inline override virtual
Reimplemented from InttRawHit.
Definition at line 43 of file InttRawHitv1.h.
View newest version in sPHENIX GitHub at line 43 of file InttRawHitv1.h
References chip_id.
uint16_t InttRawHitv1::get_fee () const inline override virtual
Reimplemented from InttRawHit.
Definition at line 35 of file InttRawHitv1.h.
View newest version in sPHENIX GitHub at line 35 of file InttRawHitv1.h
References fee.
uint16_t InttRawHitv1::get_FPHX_BCO () const inline override virtual
Reimplemented from InttRawHit.
Definition at line 51 of file InttRawHitv1.h.
View newest version in sPHENIX GitHub at line 51 of file InttRawHitv1.h
References FPHX_BCO.
uint16_t InttRawHitv1::get_full_FPHX () const inline override virtual
Reimplemented from InttRawHit.
Definition at line 55 of file InttRawHitv1.h.
View newest version in sPHENIX GitHub at line 55 of file InttRawHitv1.h
References full_FPHX.
uint16_t InttRawHitv1::get_full_ROC () const inline override virtual
Reimplemented from InttRawHit.
Definition at line 59 of file InttRawHitv1.h.
View newest version in sPHENIX GitHub at line 59 of file InttRawHitv1.h
References full_ROC.
int32_t InttRawHitv1::get_packetid () const inline override virtual
Reimplemented from InttRawHit.
Definition at line 27 of file InttRawHitv1.h.
View newest version in sPHENIX GitHub at line 27 of file InttRawHitv1.h
References packetid.
uint32_t InttRawHitv1::get_word () const inline override virtual
Reimplemented from InttRawHit.
Definition at line 31 of file InttRawHitv1.h.
View newest version in sPHENIX GitHub at line 31 of file InttRawHitv1.h
References word.
void InttRawHitv1::identify (std::ostream & os = std::cout) const override virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from PHObject.
Definition at line 18 of file InttRawHitv1.cc.
View newest version in sPHENIX GitHub at line 18 of file InttRawHitv1.cc
References bco, and packetid.
void InttRawHitv1::set_adc (uint16_t val) inline override virtual
Reimplemented from InttRawHit.
Definition at line 49 of file InttRawHitv1.h.
View newest version in sPHENIX GitHub at line 49 of file InttRawHitv1.h
References adc.
Referenced by InttRawHitv1().
void InttRawHitv1::set_amplitude (uint16_t val) inline override virtual
Reimplemented from InttRawHit.
Definition at line 65 of file InttRawHitv1.h.
View newest version in sPHENIX GitHub at line 65 of file InttRawHitv1.h
References amplitude.
Referenced by InttRawHitv1().
void InttRawHitv1::set_bco (const uint64_t val) inline override virtual
Reimplemented from InttRawHit.
Definition at line 25 of file InttRawHitv1.h.
View newest version in sPHENIX GitHub at line 25 of file InttRawHitv1.h
References bco.
Referenced by InttRawHitv1().
void InttRawHitv1::set_channel_id (uint16_t val) inline override virtual
Reimplemented from InttRawHit.
Definition at line 41 of file InttRawHitv1.h.
View newest version in sPHENIX GitHub at line 41 of file InttRawHitv1.h
References channel_id.
Referenced by InttRawHitv1().
void InttRawHitv1::set_chip_id (uint16_t val) inline override virtual
Reimplemented from InttRawHit.
Definition at line 45 of file InttRawHitv1.h.
View newest version in sPHENIX GitHub at line 45 of file InttRawHitv1.h
References chip_id.
Referenced by InttRawHitv1().
void InttRawHitv1::set_fee (uint16_t val) inline override virtual
Reimplemented from InttRawHit.
Definition at line 37 of file InttRawHitv1.h.
View newest version in sPHENIX GitHub at line 37 of file InttRawHitv1.h
References fee.
Referenced by InttRawHitv1().
void InttRawHitv1::set_FPHX_BCO (uint16_t val) inline override virtual
Reimplemented from InttRawHit.
Definition at line 53 of file InttRawHitv1.h.
View newest version in sPHENIX GitHub at line 53 of file InttRawHitv1.h
References FPHX_BCO.
Referenced by InttRawHitv1().
void InttRawHitv1::set_full_FPHX (uint16_t val) inline override virtual
Reimplemented from InttRawHit.
Definition at line 57 of file InttRawHitv1.h.
View newest version in sPHENIX GitHub at line 57 of file InttRawHitv1.h
References full_FPHX.
Referenced by InttRawHitv1().
void InttRawHitv1::set_full_ROC (uint16_t val) inline override virtual
Reimplemented from InttRawHit.
Definition at line 61 of file InttRawHitv1.h.
View newest version in sPHENIX GitHub at line 61 of file InttRawHitv1.h
References full_ROC.
Referenced by InttRawHitv1().
void InttRawHitv1::set_packetid (const int32_t val) inline override virtual
Reimplemented from InttRawHit.
Definition at line 29 of file InttRawHitv1.h.
View newest version in sPHENIX GitHub at line 29 of file InttRawHitv1.h
References packetid.
Referenced by InttRawHitv1().
void InttRawHitv1::set_word (uint32_t val) inline override virtual
Reimplemented from InttRawHit.
Definition at line 33 of file InttRawHitv1.h.
View newest version in sPHENIX GitHub at line 33 of file InttRawHitv1.h
References word.
Referenced by InttRawHitv1().
Member Data Documentation
uint16_t InttRawHitv1::adc = std::numeric_limits<uint16_t>::max() protected
Definition at line 75 of file InttRawHitv1.h.
View newest version in sPHENIX GitHub at line 75 of file InttRawHitv1.h
Referenced by get_adc(), and set_adc().
uint16_t InttRawHitv1::amplitude = std::numeric_limits<uint16_t>::max() protected
Definition at line 79 of file InttRawHitv1.h.
View newest version in sPHENIX GitHub at line 79 of file InttRawHitv1.h
Referenced by get_amplitude(), and set_amplitude().
uint64_t InttRawHitv1::bco = std::numeric_limits<uint64_t>::max() protected
Definition at line 69 of file InttRawHitv1.h.
View newest version in sPHENIX GitHub at line 69 of file InttRawHitv1.h
Referenced by get_bco(), identify(), and set_bco().
uint16_t InttRawHitv1::channel_id = std::numeric_limits<uint16_t>::max() protected
Definition at line 73 of file InttRawHitv1.h.
View newest version in sPHENIX GitHub at line 73 of file InttRawHitv1.h
Referenced by get_channel_id(), and set_channel_id().
uint16_t InttRawHitv1::chip_id = std::numeric_limits<uint16_t>::max() protected
Definition at line 74 of file InttRawHitv1.h.
View newest version in sPHENIX GitHub at line 74 of file InttRawHitv1.h
Referenced by get_chip_id(), and set_chip_id().
uint16_t InttRawHitv1::fee = std::numeric_limits<uint16_t>::max() protected
Definition at line 72 of file InttRawHitv1.h.
View newest version in sPHENIX GitHub at line 72 of file InttRawHitv1.h
Referenced by get_fee(), and set_fee().
uint16_t InttRawHitv1::FPHX_BCO = std::numeric_limits<uint16_t>::max() protected
Definition at line 76 of file InttRawHitv1.h.
View newest version in sPHENIX GitHub at line 76 of file InttRawHitv1.h
Referenced by get_FPHX_BCO(), and set_FPHX_BCO().
uint16_t InttRawHitv1::full_FPHX = std::numeric_limits<uint16_t>::max() protected
Definition at line 77 of file InttRawHitv1.h.
View newest version in sPHENIX GitHub at line 77 of file InttRawHitv1.h
Referenced by get_full_FPHX(), and set_full_FPHX().
uint16_t InttRawHitv1::full_ROC = std::numeric_limits<uint16_t>::max() protected
Definition at line 78 of file InttRawHitv1.h.
View newest version in sPHENIX GitHub at line 78 of file InttRawHitv1.h
Referenced by get_full_ROC(), and set_full_ROC().
int32_t InttRawHitv1::packetid = std::numeric_limits<int32_t>::max() protected
Definition at line 70 of file InttRawHitv1.h.
View newest version in sPHENIX GitHub at line 70 of file InttRawHitv1.h
Referenced by get_packetid(), identify(), and set_packetid().
uint32_t InttRawHitv1::word = std::numeric_limits<uint32_t>::max() protected
Definition at line 71 of file InttRawHitv1.h.
View newest version in sPHENIX GitHub at line 71 of file InttRawHitv1.h
Referenced by get_word(), and set_word().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/framework/ffarawobjects/InttRawHitv1.h
coresoftware/blob/master/offline/framework/ffarawobjects/InttRawHitv1.cc