Analysis Software: acts/blob/sPHENIX/Tests/UnitTests/Core/TrackFitting/GsfTests.cpp File Reference
GsfTests.cpp File Reference
#include <boost/test/unit_test.hpp>
#include "Acts/Definitions/Algebra.hpp"
#include "Acts/Definitions/Common.hpp"
#include "Acts/Definitions/Direction.hpp"
#include "Acts/Definitions/TrackParametrization.hpp"
#include "Acts/Definitions/Units.hpp"
#include "Acts/EventData/Charge.hpp"
#include "Acts/EventData/GenericBoundTrackParameters.hpp"
#include "Acts/EventData/GenericCurvilinearTrackParameters.hpp"
#include "Acts/EventData/MultiComponentTrackParameters.hpp"
#include "Acts/EventData/MultiTrajectory.hpp"
#include "Acts/EventData/TrackContainer.hpp"
#include "Acts/EventData/TrackParameters.hpp"
#include "Acts/EventData/TrackProxy.hpp"
#include "Acts/EventData/TrackStatePropMask.hpp"
#include "Acts/EventData/VectorMultiTrajectory.hpp"
#include "Acts/EventData/VectorTrackContainer.hpp"
#include "Acts/EventData/detail/TransformationFreeToBound.hpp"
#include "Acts/Geometry/GeometryIdentifier.hpp"
#include "Acts/Propagator/MultiEigenStepperLoop.hpp"
#include "Acts/Propagator/Navigator.hpp"
#include "Acts/Propagator/Propagator.hpp"
#include "Acts/Propagator/StraightLineStepper.hpp"
#include "Acts/Surfaces/PlaneSurface.hpp"
#include "Acts/Surfaces/Surface.hpp"
#include "Acts/Tests/CommonHelpers/LineSurfaceStub.hpp"
#include "Acts/Tests/CommonHelpers/MeasurementsCreator.hpp"
#include "Acts/Tests/CommonHelpers/TestSourceLink.hpp"
#include "Acts/TrackFitting/BetheHeitlerApprox.hpp"
#include "Acts/TrackFitting/GainMatrixUpdater.hpp"
#include "Acts/TrackFitting/GaussianSumFitter.hpp"
#include "Acts/TrackFitting/GsfMixtureReduction.hpp"
#include "Acts/TrackFitting/GsfOptions.hpp"
#include "Acts/Utilities/Delegate.hpp"
#include "Acts/Utilities/Holders.hpp"
#include "Acts/Utilities/Result.hpp"
#include "Acts/Utilities/UnitVectors.hpp"
#include "Acts/Utilities/Zip.hpp"
#include <algorithm>
#include <array>
#include <functional>
#include <map>
#include <memory>
#include <optional>
#include <random>
#include <string>
#include <string_view>
#include <tuple>
#include <vector>
#include "FitterTestsCommon.hpp"
Functions
BOOST_AUTO_TEST_CASE (ZeroFieldNoSurfaceForward)
BOOST_AUTO_TEST_CASE (ZeroFieldWithSurfaceForward)
BOOST_AUTO_TEST_CASE (ZeroFieldWithSurfaceBackward)
BOOST_AUTO_TEST_CASE (ZeroFieldWithSurfaceAtExit)
BOOST_AUTO_TEST_CASE (ZeroFieldShuffled)
BOOST_AUTO_TEST_CASE (ZeroFieldWithHole)
BOOST_AUTO_TEST_CASE (ZeroFieldWithOutliers)
BOOST_AUTO_TEST_CASE (WithFinalMultiComponentState)
Function Documentation
BOOST_AUTO_TEST_CASE (ZeroFieldNoSurfaceForward)
Definition at line 161 of file GsfTests.cpp.
View newest version in sPHENIX GitHub at line 161 of file GsfTests.cpp
References Acts::Test::makeParameters(), ckf::options, and conftest::rng().
BOOST_AUTO_TEST_CASE (ZeroFieldWithSurfaceForward)
Definition at line 169 of file GsfTests.cpp.
View newest version in sPHENIX GitHub at line 169 of file GsfTests.cpp
References Acts::Test::makeParameters(), ckf::options, and conftest::rng().
BOOST_AUTO_TEST_CASE (ZeroFieldWithSurfaceBackward)
Definition at line 177 of file GsfTests.cpp.
View newest version in sPHENIX GitHub at line 177 of file GsfTests.cpp
References Acts::Test::makeParameters(), ckf::options, and conftest::rng().
BOOST_AUTO_TEST_CASE (ZeroFieldWithSurfaceAtExit)
Definition at line 185 of file GsfTests.cpp.
View newest version in sPHENIX GitHub at line 185 of file GsfTests.cpp
References Acts::Test::makeParameters(), ckf::options, and conftest::rng().
BOOST_AUTO_TEST_CASE (ZeroFieldShuffled)
Definition at line 193 of file GsfTests.cpp.
View newest version in sPHENIX GitHub at line 193 of file GsfTests.cpp
References Acts::Test::makeParameters(), ckf::options, and conftest::rng().
BOOST_AUTO_TEST_CASE (ZeroFieldWithHole)
Definition at line 201 of file GsfTests.cpp.
View newest version in sPHENIX GitHub at line 201 of file GsfTests.cpp
References Acts::Test::makeParameters(), ckf::options, and conftest::rng().
BOOST_AUTO_TEST_CASE (ZeroFieldWithOutliers)
Definition at line 209 of file GsfTests.cpp.
View newest version in sPHENIX GitHub at line 209 of file GsfTests.cpp
References Acts::Test::makeParameters(), ckf::options, and conftest::rng().
BOOST_AUTO_TEST_CASE (WithFinalMultiComponentState)
Definition at line 223 of file GsfTests.cpp.
View newest version in sPHENIX GitHub at line 223 of file GsfTests.cpp
References Acts::Test::createMeasurements(), Acts::GsfConstants::kFinalMultiComponentStateColumn, Acts::Test::makeParameters(), ckf::options, conftest::rng(), and tracks().