Analysis Software: DaqMonDraw Class Reference
DaqMonDraw Class Reference
#include <OnlMon/blob/main/subsystems/daq/DaqMonDraw.h>
Public Member Functions
DaqMonDraw (const std::string &name)
~DaqMonDraw () override
int Init () override
int Draw (const std::string &what="ALL") override
int MakeHtml (const std::string &what="ALL") override
int SavePlot (const std::string &what="ALL", const std::string &type="png") override
Public Member Functions inherited from OnlMonDraw
OnlMonDraw (const std::string &name="NONE")
virtual ~OnlMonDraw ()
virtual int MakePS (const std::string &what="ALL")
const std::string Name () const
void Verbosity (const int i)
int Verbosity () const
Protected Member Functions
int MakeCanvas (const std::string &name)
int DrawFirst (const std::string &what="ALL")
int DrawSecond (const std::string &what="ALL")
int DrawHistory (const std::string &what="ALL")
Protected Member Functions inherited from OnlMonDraw
virtual int DrawDeadServer (TPad *transparent)
Protected Attributes
int TimeOffsetTicks = -1
TCanvas * TC [3] = {nullptr}
TPad * transparent [3] = {nullptr}
TPad * Pad [6] = {nullptr}
TGraphErrors * gr [2] = {nullptr}
OnlMonDB * dbvars = nullptr
Protected Attributes inherited from OnlMonDraw
std::string ThisName
int verbosity = 0
Detailed Description
Definition at line 13 of file DaqMonDraw.h.
View newest version in sPHENIX GitHub at line 13 of file DaqMonDraw.h
Constructor & Destructor Documentation
DaqMonDraw::DaqMonDraw (const std::string & name)
Definition at line 23 of file DaqMonDraw.cc.
View newest version in sPHENIX GitHub at line 23 of file DaqMonDraw.cc
References dbvars, OnlMonDraw::ThisName, and TimeOffsetTicks.
DaqMonDraw::~DaqMonDraw () inline override
Definition at line 18 of file DaqMonDraw.h.
View newest version in sPHENIX GitHub at line 18 of file DaqMonDraw.h
Member Function Documentation
int DaqMonDraw::Draw (const std::string & what = "ALL") override virtual
Reimplemented from OnlMonDraw.
Definition at line 94 of file DaqMonDraw.cc.
View newest version in sPHENIX GitHub at line 94 of file DaqMonDraw.cc
References DrawFirst(), DrawHistory(), and DrawSecond().
Referenced by MakeHtml(), and SavePlot().
int DaqMonDraw::DrawFirst (const std::string & what = "ALL") protected
Definition at line 121 of file DaqMonDraw.cc.
View newest version in sPHENIX GitHub at line 121 of file DaqMonDraw.cc
References OnlMonDraw::DrawDeadServer(), OnlMonClient::EventTime(), OnlMonClient::getHisto(), OnlMonClient::instance(), MakeCanvas(), Pad, OnlMonClient::RunNumber(), TC, OnlMonDraw::ThisName, and transparent.
Referenced by Draw().
int DaqMonDraw::DrawHistory (const std::string & what = "ALL") protected
Definition at line 275 of file DaqMonDraw.cc.
View newest version in sPHENIX GitHub at line 275 of file DaqMonDraw.cc
References parse_cmake_options::begin, dbvars, end, OnlMonDB::GetVar(), gr, i, MakeCanvas(), n, Pad, runnumber, TC, Acts::Test::time, TimeOffsetTicks, CDB::timestamp, ambiguity_solver_full_chain::x, and y.
Referenced by Draw().
int DaqMonDraw::DrawSecond (const std::string & what = "ALL") protected
Definition at line 168 of file DaqMonDraw.cc.
View newest version in sPHENIX GitHub at line 168 of file DaqMonDraw.cc
References OnlMonDraw::DrawDeadServer(), OnlMonClient::EventTime(), OnlMonClient::getHisto(), OnlMonClient::instance(), MakeCanvas(), Pad, OnlMonClient::RunNumber(), TC, OnlMonDraw::ThisName, and transparent.
Referenced by Draw().
int DaqMonDraw::Init () override virtual
Reimplemented from OnlMonDraw.
Definition at line 33 of file DaqMonDraw.cc.
View newest version in sPHENIX GitHub at line 33 of file DaqMonDraw.cc
int DaqMonDraw::MakeCanvas (const std::string & name) protected
Definition at line 38 of file DaqMonDraw.cc.
View newest version in sPHENIX GitHub at line 38 of file DaqMonDraw.cc
References OnlMonClient::GetDisplaySizeX(), OnlMonClient::GetDisplaySizeY(), OnlMonClient::instance(), Pad, TC, and transparent.
Referenced by DrawFirst(), DrawHistory(), and DrawSecond().
int DaqMonDraw::MakeHtml (const std::string & what = "ALL") override virtual
Reimplemented from OnlMonDraw.
Definition at line 239 of file DaqMonDraw.cc.
View newest version in sPHENIX GitHub at line 239 of file DaqMonDraw.cc
References OnlMonClient::CanvasToPng(), Draw(), OnlMonClient::htmlRegisterPage(), OnlMonClient::instance(), out, OnlMonClient::RunNumber(), OnlMonClient::SaveLogFile(), utils::status, and TC.
int DaqMonDraw::SavePlot (const std::string & what = "ALL", const std::string & type = "png") override virtual
Reimplemented from OnlMonDraw.
Definition at line 215 of file DaqMonDraw.cc.
View newest version in sPHENIX GitHub at line 215 of file DaqMonDraw.cc
References OnlMonClient::CanvasToPng(), Draw(), filename, OnlMonClient::instance(), OnlMonClient::RunNumber(), TC, OnlMonDraw::ThisName, and to_string().
Member Data Documentation
OnlMonDB* DaqMonDraw::dbvars = nullptr protected
Definition at line 35 of file DaqMonDraw.h.
View newest version in sPHENIX GitHub at line 35 of file DaqMonDraw.h
Referenced by DaqMonDraw(), and DrawHistory().
TGraphErrors* DaqMonDraw::gr[2] = {nullptr} protected
Definition at line 34 of file DaqMonDraw.h.
View newest version in sPHENIX GitHub at line 34 of file DaqMonDraw.h
Referenced by DrawHistory().
TPad* DaqMonDraw::Pad[6] = {nullptr} protected
Definition at line 33 of file DaqMonDraw.h.
View newest version in sPHENIX GitHub at line 33 of file DaqMonDraw.h
Referenced by DrawFirst(), DrawHistory(), DrawSecond(), and MakeCanvas().
TCanvas* DaqMonDraw::TC[3] = {nullptr} protected
Definition at line 31 of file DaqMonDraw.h.
View newest version in sPHENIX GitHub at line 31 of file DaqMonDraw.h
Referenced by DrawFirst(), DrawHistory(), DrawSecond(), MakeCanvas(), MakeHtml(), and SavePlot().
int DaqMonDraw::TimeOffsetTicks = -1 protected
Definition at line 30 of file DaqMonDraw.h.
View newest version in sPHENIX GitHub at line 30 of file DaqMonDraw.h
Referenced by DaqMonDraw(), and DrawHistory().
TPad* DaqMonDraw::transparent[3] = {nullptr} protected
Definition at line 32 of file DaqMonDraw.h.
View newest version in sPHENIX GitHub at line 32 of file DaqMonDraw.h
Referenced by DrawFirst(), DrawSecond(), and MakeCanvas().
The documentation for this class was generated from the following files:
OnlMon/blob/main/subsystems/daq/DaqMonDraw.h
OnlMon/blob/main/subsystems/daq/DaqMonDraw.cc