Analysis Software: fuse_gmock_files Namespace Reference
fuse_gmock_files Namespace Reference
Functions
def GetGTestRootDir
def ValidateGMockRootDir
def ValidateOutputDir
def FuseGMockH
def FuseGMockAllCcToFile
def FuseGMockGTestAllCc
def FuseGMock
def main
Variables
string __author__ 'wan@google.com (Zhanyong Wan)'
tuple DEFAULT_GMOCK_ROOT_DIR os.path.join(os.path.dirname(__file__), '..')
gtest fuse_gtest_files
tuple INCLUDE_GMOCK_FILE_REGEX re.compile(r'^\s*#\s*include\s*"(gmock/.+)"')
string GMOCK_H_SEED 'include/gmock/gmock.h'
string GMOCK_ALL_CC_SEED 'src/gmock-all.cc'
string GTEST_H_OUTPUT 'gtest/gtest.h'
string GMOCK_H_OUTPUT 'gmock/gmock.h'
string GMOCK_GTEST_ALL_CC_OUTPUT 'gmock-gtest-all.cc'
Function Documentation
def fuse_gmock_files.FuseGMock (gmock_root, output_dir)
Fuses gtest.h, gmock.h, and gmock-gtest-all.h.
Definition at line 215 of file fuse_gmock_files.py.
View newest version in sPHENIX GitHub at line 215 of file fuse_gmock_files.py
References FuseGMockGTestAllCc(), FuseGMockH(), GetGTestRootDir(), ValidateGMockRootDir(), and ValidateOutputDir().
Referenced by main().
def fuse_gmock_files.FuseGMockAllCcToFile (gmock_root, output_file)
Scans folder gmock_root to fuse gmock-all.cc into output_file.
Definition at line 159 of file fuse_gmock_files.py.
View newest version in sPHENIX GitHub at line 159 of file fuse_gmock_files.py
References file.
Referenced by FuseGMockGTestAllCc().
def fuse_gmock_files.FuseGMockGTestAllCc (gmock_root, output_dir)
Scans folder gmock_root to generate gmock-gtest-all.cc in output_dir.
Definition at line 204 of file fuse_gmock_files.py.
View newest version in sPHENIX GitHub at line 204 of file fuse_gmock_files.py
References file, FuseGMockAllCcToFile(), and GetGTestRootDir().
Referenced by FuseGMock().
def fuse_gmock_files.FuseGMockH (gmock_root, output_dir)
Scans folder gmock_root to generate gmock/gmock.h in output_dir.
Definition at line 119 of file fuse_gmock_files.py.
View newest version in sPHENIX GitHub at line 119 of file fuse_gmock_files.py
References file.
Referenced by FuseGMock().
def fuse_gmock_files.GetGTestRootDir (gmock_root)
Returns the root directory of Google Test.
Definition at line 91 of file fuse_gmock_files.py.
View newest version in sPHENIX GitHub at line 91 of file fuse_gmock_files.py
Referenced by FuseGMock(), FuseGMockGTestAllCc(), and ValidateGMockRootDir().
def fuse_gmock_files.main (void)
Definition at line 226 of file fuse_gmock_files.py.
View newest version in sPHENIX GitHub at line 226 of file fuse_gmock_files.py
References FuseGMock().
def fuse_gmock_files.ValidateGMockRootDir (gmock_root)
Makes sure gmock_root points to a valid gmock root directory.
The function aborts the program on failure.
Definition at line 97 of file fuse_gmock_files.py.
View newest version in sPHENIX GitHub at line 97 of file fuse_gmock_files.py
References GetGTestRootDir().
Referenced by FuseGMock().
def fuse_gmock_files.ValidateOutputDir (output_dir)
Makes sure output_dir points to a valid output directory.
The function aborts the program on failure.
Definition at line 108 of file fuse_gmock_files.py.
View newest version in sPHENIX GitHub at line 108 of file fuse_gmock_files.py
Referenced by FuseGMock().
Variable Documentation
string fuse_gmock_files.__author__ 'wan@google.com (Zhanyong Wan)'
Definition at line 62 of file fuse_gmock_files.py.
View newest version in sPHENIX GitHub at line 62 of file fuse_gmock_files.py
tuple fuse_gmock_files.DEFAULT_GMOCK_ROOT_DIR os.path.join(os.path.dirname(__file__), '..')
Definition at line 71 of file fuse_gmock_files.py.
View newest version in sPHENIX GitHub at line 71 of file fuse_gmock_files.py
string fuse_gmock_files.GMOCK_ALL_CC_SEED 'src/gmock-all.cc'
Definition at line 83 of file fuse_gmock_files.py.
View newest version in sPHENIX GitHub at line 83 of file fuse_gmock_files.py
string fuse_gmock_files.GMOCK_GTEST_ALL_CC_OUTPUT 'gmock-gtest-all.cc'
Definition at line 88 of file fuse_gmock_files.py.
View newest version in sPHENIX GitHub at line 88 of file fuse_gmock_files.py
string fuse_gmock_files.GMOCK_H_OUTPUT 'gmock/gmock.h'
Definition at line 87 of file fuse_gmock_files.py.
View newest version in sPHENIX GitHub at line 87 of file fuse_gmock_files.py
string fuse_gmock_files.GMOCK_H_SEED 'include/gmock/gmock.h'
Definition at line 82 of file fuse_gmock_files.py.
View newest version in sPHENIX GitHub at line 82 of file fuse_gmock_files.py
fuse_gmock_files.gtest fuse_gtest_files
Definition at line 76 of file fuse_gmock_files.py.
View newest version in sPHENIX GitHub at line 76 of file fuse_gmock_files.py
string fuse_gmock_files.GTEST_H_OUTPUT 'gtest/gtest.h'
Definition at line 86 of file fuse_gmock_files.py.
View newest version in sPHENIX GitHub at line 86 of file fuse_gmock_files.py
tuple fuse_gmock_files.INCLUDE_GMOCK_FILE_REGEX re.compile(r'^\s*#\s*include\s*"(gmock/.+)"')
Definition at line 79 of file fuse_gmock_files.py.
View newest version in sPHENIX GitHub at line 79 of file fuse_gmock_files.py