Analysis Software: Acts::Geant4ShapeConverter Struct Reference
Acts::Geant4ShapeConverter Struct Reference
#include <acts/blob/sPHENIX/Plugins/Geant4/include/Acts/Plugins/Geant4/Geant4Converters.hpp>
Public Member Functions
std::tuple< std::shared_ptr
< CylinderBounds >, ActsScalar > cylinderBounds (const G4Tubs &g4Tubs)
Convert to cylinder bounds.
std::tuple< std::shared_ptr
< RadialBounds >, ActsScalar > radialBounds (const G4Tubs &g4Tubs)
Convert to radial bounds.
std::shared_ptr< LineBounds > lineBounds (const G4Tubs &g4Tubs)
Convert to line/straw bounds.
std::tuple< std::shared_ptr
< RectangleBounds >
, std::array< int, 2u >, ActsScalar > rectangleBounds (const G4Box &g4Box)
Convert to rectangle bounds.
std::tuple< std::shared_ptr
< TrapezoidBounds >
, std::array< int, 2u >, ActsScalar > trapezoidBounds (const G4Trd &g4Trd)
Convert to trapezoid bounds - from Trap.
std::tuple< std::shared_ptr
< PlanarBounds >, std::array
< int, 2u >, ActsScalar > planarBounds (const G4VSolid &g4Solid)
Convert to general solid into a planar shape.
Public Attributes
ActsScalar scale = 1.
A scale between Geant4 and ACTS.
bool keepAxisOrder = false
Detailed Description
Definition at line 82 of file Geant4Converters.hpp.
View newest version in sPHENIX GitHub at line 82 of file Geant4Converters.hpp
Member Function Documentation
std::tuple< std::shared_ptr< Acts::CylinderBounds >, Acts::ActsScalar > Acts::Geant4ShapeConverter::cylinderBounds (const G4Tubs & g4Tubs)
Convert to cylinder bounds.
Parameters
g4Tubs a Geant4 tube shape
Returns
an Acts Cylinder bounds object, and thickness
Definition at line 91 of file Geant4Converters.cpp.
View newest version in sPHENIX GitHub at line 91 of file Geant4Converters.cpp
References eR, std::tr1::make_tuple(), testing::internal::move(), and thickness.
Referenced by BOOST_AUTO_TEST_CASE(), and Acts::Geant4PhysicalVolumeConverter::surface().
std::shared_ptr< Acts::LineBounds > Acts::Geant4ShapeConverter::lineBounds (const G4Tubs & g4Tubs)
Convert to line/straw bounds.
Parameters
g4Tubs a Geant4 tube shape
Returns
an Acts line bounds object and thickness
Definition at line 140 of file Geant4Converters.cpp.
View newest version in sPHENIX GitHub at line 140 of file Geant4Converters.cpp
References physmon_track_finding_ttbar::r.
Referenced by BOOST_AUTO_TEST_CASE(), and Acts::Geant4PhysicalVolumeConverter::surface().
std::tuple< std::shared_ptr< Acts::PlanarBounds >, std::array< int, 2u >, Acts::ActsScalar > Acts::Geant4ShapeConverter::planarBounds (const G4VSolid & g4Solid)
Convert to general solid into a planar shape.
Parameters
g4Solid a Geant4 solid shape
Returns
an ACTS Planar bounds object, the axes, and the thickness of the compressed dimension
Definition at line 237 of file Geant4Converters.cpp.
View newest version in sPHENIX GitHub at line 237 of file Geant4Converters.cpp
References std::tr1::make_tuple(), testing::internal::move(), rBounds, and thickness.
Referenced by BOOST_AUTO_TEST_CASE().
std::tuple< std::shared_ptr< Acts::RadialBounds >, Acts::ActsScalar > Acts::Geant4ShapeConverter::radialBounds (const G4Tubs & g4Tubs)
Convert to radial bounds.
Parameters
g4Tubs a Geant4 tube shape
Returns
an Acts Radial bounds object and thickness
Definition at line 117 of file Geant4Converters.cpp.
View newest version in sPHENIX GitHub at line 117 of file Geant4Converters.cpp
References std::tr1::make_tuple(), testing::internal::move(), rBounds, and thickness.
Referenced by BOOST_AUTO_TEST_CASE(), and Acts::Geant4PhysicalVolumeConverter::surface().
std::tuple< std::shared_ptr< Acts::RectangleBounds >, std::array< int, 2u >, Acts::ActsScalar > Acts::Geant4ShapeConverter::rectangleBounds (const G4Box & g4Box)
Convert to rectangle bounds.
Parameters
g4Box a Geant4 box shape
Returns
an ACTS Rectangle bounds shape, axis orientation, and thickness
Definition at line 149 of file Geant4Converters.cpp.
View newest version in sPHENIX GitHub at line 149 of file Geant4Converters.cpp
References distance(), std::tr1::make_tuple(), testing::internal::move(), rBounds, thickness, and physmon_ckf_tracking::u.
Referenced by BOOST_AUTO_TEST_CASE(), and Acts::Geant4PhysicalVolumeConverter::surface().
std::tuple< std::shared_ptr< Acts::TrapezoidBounds >, std::array< int, 2u >, Acts::ActsScalar > Acts::Geant4ShapeConverter::trapezoidBounds (const G4Trd & g4Trd)
Convert to trapezoid bounds - from Trap.
Parameters
g4Trd a Geant4 trapezoid shape
Returns
an ACTS Trapezoid bounds object, axis orientation, and thickness
Definition at line 182 of file Geant4Converters.cpp.
View newest version in sPHENIX GitHub at line 182 of file Geant4Converters.cpp
References distance(), std::tr1::make_tuple(), testing::internal::move(), and thickness.
Referenced by BOOST_AUTO_TEST_CASE(), and Acts::Geant4PhysicalVolumeConverter::surface().
Member Data Documentation
bool Acts::Geant4ShapeConverter::keepAxisOrder = false
A description to keep the axis order, if it is set to false cyclic re-ordering will happen, otherwise axis flip if needed in order to keep the system right-handed
Definition at line 88 of file Geant4Converters.hpp.
View newest version in sPHENIX GitHub at line 88 of file Geant4Converters.hpp
ActsScalar Acts::Geant4ShapeConverter::scale = 1.
A scale between Geant4 and ACTS.
Definition at line 84 of file Geant4Converters.hpp.
View newest version in sPHENIX GitHub at line 84 of file Geant4Converters.hpp
The documentation for this struct was generated from the following files:
acts/blob/sPHENIX/Plugins/Geant4/include/Acts/Plugins/Geant4/Geant4Converters.hpp
acts/blob/sPHENIX/Plugins/Geant4/src/Geant4Converters.cpp