Analysis Software: acts/blob/sPHENIX/Tests/UnitTests/Plugins/Podio/PodioTrackStateContainerTest.cpp File Reference
PodioTrackStateContainerTest.cpp File Reference
#include <boost/test/data/test_case.hpp>
#include <boost/test/tools/old/interface.hpp>
#include <boost/test/unit_test.hpp>
#include <boost/test/unit_test_suite.hpp>
#include "Acts/Definitions/TrackParametrization.hpp"
#include "Acts/Definitions/Units.hpp"
#include "Acts/EventData/SourceLink.hpp"
#include "Acts/EventData/TrackStatePropMask.hpp"
#include "Acts/Geometry/GeometryContext.hpp"
#include "Acts/Plugins/Podio/PodioTrackStateContainer.hpp"
#include "Acts/Plugins/Podio/PodioUtil.hpp"
#include "Acts/Surfaces/RectangleBounds.hpp"
#include "Acts/Tests/CommonHelpers/MultiTrajectoryTestsCommon.hpp"
#include "ActsPodioEdm/BoundParametersCollection.h"
#include "ActsPodioEdm/JacobianCollection.h"
#include "ActsPodioEdm/TrackStateCollection.h"
#include <filesystem>
#include <podio/ROOTFrameReader.h>
#include <podio/ROOTFrameWriter.h>
#include <podio/UserDataCollection.h>
Functions
BOOST_AUTO_TEST_CASE (Build)
BOOST_AUTO_TEST_CASE (ConstCorrectness)
BOOST_AUTO_TEST_CASE (Clear)
BOOST_AUTO_TEST_CASE (ApplyWithAbort)
BOOST_AUTO_TEST_CASE (AddTrackStateWithBitMask)
BOOST_AUTO_TEST_CASE (TrackStateProxyCrossTalk)
BOOST_AUTO_TEST_CASE (TrackStateReassignment)
BOOST_DATA_TEST_CASE (TrackStateProxyStorage, bd::make({1u, 2u}), nMeasurements)
BOOST_AUTO_TEST_CASE (TrackStateProxyAllocations)
BOOST_AUTO_TEST_CASE (TrackStateProxyGetMask)
BOOST_AUTO_TEST_CASE (TrackStateProxyCopy)
BOOST_AUTO_TEST_CASE (TrackStateProxyCopyDiffMTJ)
BOOST_AUTO_TEST_CASE (ProxyAssignment)
BOOST_AUTO_TEST_CASE (CopyFromConst)
BOOST_AUTO_TEST_CASE (TrackStateProxyShare)
BOOST_AUTO_TEST_CASE (MultiTrajectoryExtraColumns)
BOOST_AUTO_TEST_CASE (MultiTrajectoryExtraColumnsRuntime)
BOOST_AUTO_TEST_CASE (WriteToPodioFrame)
Function Documentation
BOOST_AUTO_TEST_CASE (Build)
Definition at line 115 of file PodioTrackStateContainerTest.cpp.
View newest version in sPHENIX GitHub at line 115 of file PodioTrackStateContainerTest.cpp
BOOST_AUTO_TEST_CASE (ConstCorrectness)
Definition at line 120 of file PodioTrackStateContainerTest.cpp.
View newest version in sPHENIX GitHub at line 120 of file PodioTrackStateContainerTest.cpp
BOOST_AUTO_TEST_CASE (Clear)
Definition at line 124 of file PodioTrackStateContainerTest.cpp.
View newest version in sPHENIX GitHub at line 124 of file PodioTrackStateContainerTest.cpp
BOOST_AUTO_TEST_CASE (ApplyWithAbort)
Definition at line 129 of file PodioTrackStateContainerTest.cpp.
View newest version in sPHENIX GitHub at line 129 of file PodioTrackStateContainerTest.cpp
BOOST_AUTO_TEST_CASE (AddTrackStateWithBitMask)
Definition at line 134 of file PodioTrackStateContainerTest.cpp.
View newest version in sPHENIX GitHub at line 134 of file PodioTrackStateContainerTest.cpp
BOOST_AUTO_TEST_CASE (TrackStateProxyCrossTalk)
Definition at line 140 of file PodioTrackStateContainerTest.cpp.
View newest version in sPHENIX GitHub at line 140 of file PodioTrackStateContainerTest.cpp
References conftest::rng().
BOOST_AUTO_TEST_CASE (TrackStateReassignment)
Definition at line 145 of file PodioTrackStateContainerTest.cpp.
View newest version in sPHENIX GitHub at line 145 of file PodioTrackStateContainerTest.cpp
References conftest::rng().
BOOST_AUTO_TEST_CASE (TrackStateProxyAllocations)
Definition at line 156 of file PodioTrackStateContainerTest.cpp.
View newest version in sPHENIX GitHub at line 156 of file PodioTrackStateContainerTest.cpp
References conftest::rng().
BOOST_AUTO_TEST_CASE (TrackStateProxyGetMask)
Definition at line 161 of file PodioTrackStateContainerTest.cpp.
View newest version in sPHENIX GitHub at line 161 of file PodioTrackStateContainerTest.cpp
BOOST_AUTO_TEST_CASE (TrackStateProxyCopy)
Definition at line 166 of file PodioTrackStateContainerTest.cpp.
View newest version in sPHENIX GitHub at line 166 of file PodioTrackStateContainerTest.cpp
References conftest::rng().
BOOST_AUTO_TEST_CASE (TrackStateProxyCopyDiffMTJ)
Definition at line 171 of file PodioTrackStateContainerTest.cpp.
View newest version in sPHENIX GitHub at line 171 of file PodioTrackStateContainerTest.cpp
BOOST_AUTO_TEST_CASE (ProxyAssignment)
Definition at line 176 of file PodioTrackStateContainerTest.cpp.
View newest version in sPHENIX GitHub at line 176 of file PodioTrackStateContainerTest.cpp
BOOST_AUTO_TEST_CASE (CopyFromConst)
Definition at line 181 of file PodioTrackStateContainerTest.cpp.
View newest version in sPHENIX GitHub at line 181 of file PodioTrackStateContainerTest.cpp
BOOST_AUTO_TEST_CASE (TrackStateProxyShare)
Definition at line 186 of file PodioTrackStateContainerTest.cpp.
View newest version in sPHENIX GitHub at line 186 of file PodioTrackStateContainerTest.cpp
References conftest::rng().
BOOST_AUTO_TEST_CASE (MultiTrajectoryExtraColumns)
Definition at line 191 of file PodioTrackStateContainerTest.cpp.
View newest version in sPHENIX GitHub at line 191 of file PodioTrackStateContainerTest.cpp
BOOST_AUTO_TEST_CASE (MultiTrajectoryExtraColumnsRuntime)
Definition at line 196 of file PodioTrackStateContainerTest.cpp.
View newest version in sPHENIX GitHub at line 196 of file PodioTrackStateContainerTest.cpp
BOOST_AUTO_TEST_CASE (WriteToPodioFrame)
Definition at line 201 of file PodioTrackStateContainerTest.cpp.
View newest version in sPHENIX GitHub at line 201 of file PodioTrackStateContainerTest.cpp
References Acts::PhysicalConstants::c, f, gctx, add_histos::outfile, rBounds, ambiguity_solver_full_chain::t1, ambiguity_solver_full_chain::t2, ambiguity_solver_full_chain::t3, and Acts::Test::tmp_path.
BOOST_DATA_TEST_CASE (TrackStateProxyStorage , bd:: make{1u, 2u}, nMeasurements)
Definition at line 150 of file PodioTrackStateContainerTest.cpp.
View newest version in sPHENIX GitHub at line 150 of file PodioTrackStateContainerTest.cpp
References physmon_ckf_tracking::u.