Analysis Software: JETSCAPE/blob/main/examples/unittests/fluid_dynamics.cc File Reference
fluid_dynamics.cc File Reference
#include "FluidDynamics.h"
#include "FluidEvolutionHistory.h"
#include "gtest/gtest.h"
Functions
void test_not_in_range (EvolutionHistory hist, real tau, real x, real y, real eta)
TEST (EvolutionHistoryTest, TEST_WRITE)
Function Documentation
TEST (EvolutionHistoryTest , TEST_WRITE)
Definition at line 32 of file fluid_dynamics.cc.
View newest version in sPHENIX GitHub at line 32 of file fluid_dynamics.cc
References ASSERT_NEAR, E, EXPECT_EQ, add_histos::hist, i, j, k, testing::internal::move(), n, and test_not_in_range().
void test_not_in_range (EvolutionHistory hist, real tau, real x, real y, real eta)
Definition at line 22 of file fluid_dynamics.cc.
View newest version in sPHENIX GitHub at line 22 of file fluid_dynamics.cc
References ASSERT_TRUE, Jetscape::EvolutionHistory::CheckInRange(), and Acts::UnitConstants::e.
Referenced by TEST().