Analysis Software: SingleMvtxPoolInput Class Reference
SingleMvtxPoolInput Class Reference
#include <coresoftware/blob/master/offline/framework/fun4allraw/SingleMvtxPoolInput.h>
Public Member Functions
SingleMvtxPoolInput (const std::string &name)
~SingleMvtxPoolInput () override
void FillPool (const unsigned int nevents=1) override
void CleanupUsedPackets (const uint64_t bclk) override
bool CheckPoolDepth (const uint64_t bclk) override
void ClearCurrentEvent () override
bool GetSomeMoreEvents ()
void Print (const std::string &what="ALL") const override
void CreateDSTNode (PHCompositeNode *topNode) override
void SetBcoRange (const unsigned int i)
void ConfigureStreamingInputManager () override
void SetNegativeBco (const unsigned int value)
std::set< int > & getFeeIdSet (const uint64_t &bco)
Public Member Functions inherited from SingleStreamingInput
SingleStreamingInput (const std::string &name, Fun4AllEvtInputPoolManager *inman)
SingleStreamingInput (const std::string &name)
~SingleStreamingInput () override
virtual Eventiterator * GetEventIterator ()
virtual void FillPool (const uint64_t)
virtual void RunNumber (const int runno)
virtual int RunNumber () const
virtual int fileopen (const std::string &filename) override
virtual int fileclose () override
virtual int AllDone () const
virtual void AllDone (const int i)
virtual void EventNumberOffset (const int i)
virtual Eventiterator * GetEventiterator () const
virtual
Fun4AllEvtInputPoolManager * InputManager ()
virtual void InputManager (Fun4AllEvtInputPoolManager *in)
virtual
Fun4AllStreamingInputManager * StreamingInputManager ()
virtual void StreamingInputManager (Fun4AllStreamingInputManager *in)
virtual void SubsystemEnum (const int id)
virtual int SubsystemEnum () const
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Public Member Functions inherited from InputFileHandler
InputFileHandler ()=default
virtual ~InputFileHandler ()=default
int OpenNextFile ()
int AddListFile (const std::string &filename)
int AddFile (const std::string &filename)
void AddToFileOpened (const std::string &filename)
void Print (const std::string &what="ALL") const
int IsOpen () const
void IsOpen (const int i)
void SetVerbosity (const int i)
int GetVerbosity () const
void UpdateFileList ()
void FileName (const std::string &fn)
const std::string FileName () const
Protected Member Functions
LinkId_t DecodeFeeid (const uint16_t &feeid)
Private Attributes
Packet ** plist {nullptr}
unsigned int m_NumSpecialEvents {0}
unsigned int m_BcoRange {0}
unsigned int m_NegativeBco {0}
std::map< uint64_t, std::set
< int > > m_BeamClockFEE
std::map< uint64_t,
std::vector< MvtxRawHit * > > m_MvtxRawHitMap
std::map< int, uint64_t > m_FEEBclkMap
std::map< int, uint64_t > m_FeeStrobeMap
std::set< uint64_t > m_BclkStack
std::set< uint64_t > gtmL1BcoSet
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = std::numeric_limits<int>::max() - 10
}
Detailed Description
Definition at line 20 of file SingleMvtxPoolInput.h.
View newest version in sPHENIX GitHub at line 20 of file SingleMvtxPoolInput.h
Constructor & Destructor Documentation
SingleMvtxPoolInput::SingleMvtxPoolInput (const std::string & name) explicit
Definition at line 25 of file SingleMvtxPoolInput.cc.
View newest version in sPHENIX GitHub at line 25 of file SingleMvtxPoolInput.cc
References plist.
SingleMvtxPoolInput::~SingleMvtxPoolInput () override
Definition at line 31 of file SingleMvtxPoolInput.cc.
View newest version in sPHENIX GitHub at line 31 of file SingleMvtxPoolInput.cc
References plist.
Member Function Documentation
bool SingleMvtxPoolInput::CheckPoolDepth (const uint64_t bclk) override virtual
Reimplemented from SingleStreamingInput.
Definition at line 272 of file SingleMvtxPoolInput.cc.
View newest version in sPHENIX GitHub at line 272 of file SingleMvtxPoolInput.cc
References m_FEEBclkMap, and Fun4AllBase::Verbosity().
void SingleMvtxPoolInput::CleanupUsedPackets (const uint64_t bclk) override virtual
Reimplemented from SingleStreamingInput.
Definition at line 239 of file SingleMvtxPoolInput.cc.
View newest version in sPHENIX GitHub at line 239 of file SingleMvtxPoolInput.cc
References gtmL1BcoSet, m_BclkStack, m_BeamClockFEE, m_FeeStrobeMap, and m_MvtxRawHitMap.
Referenced by ClearCurrentEvent().
void SingleMvtxPoolInput::ClearCurrentEvent () override virtual
Reimplemented from SingleStreamingInput.
Definition at line 301 of file SingleMvtxPoolInput.cc.
View newest version in sPHENIX GitHub at line 301 of file SingleMvtxPoolInput.cc
References CleanupUsedPackets(), and m_BclkStack.
void SingleMvtxPoolInput::ConfigureStreamingInputManager () override virtual
Reimplemented from SingleStreamingInput.
Definition at line 381 of file SingleMvtxPoolInput.cc.
View newest version in sPHENIX GitHub at line 381 of file SingleMvtxPoolInput.cc
References m_BcoRange, m_NegativeBco, Fun4AllStreamingInputManager::SetMvtxBcoRange(), Fun4AllStreamingInputManager::SetMvtxNegativeBco(), and SingleStreamingInput::StreamingInputManager().
void SingleMvtxPoolInput::CreateDSTNode (PHCompositeNode * topNode) override virtual
Reimplemented from SingleStreamingInput.
Definition at line 347 of file SingleMvtxPoolInput.cc.
View newest version in sPHENIX GitHub at line 347 of file SingleMvtxPoolInput.cc
References PHCompositeNode::addNode(), and PHNodeIterator::findFirst().
LinkId_t SingleMvtxPoolInput::DecodeFeeid (const uint16_t & feeid) inline protected
Definition at line 39 of file SingleMvtxPoolInput.h.
View newest version in sPHENIX GitHub at line 39 of file SingleMvtxPoolInput.h
References linkId::gbtid, linkId::layer, and linkId::stave.
Referenced by FillPool().
void SingleMvtxPoolInput::FillPool (const unsigned int nevents = 1) override virtual
Reimplemented from SingleStreamingInput.
Definition at line 36 of file SingleMvtxPoolInput.cc.
View newest version in sPHENIX GitHub at line 36 of file SingleMvtxPoolInput.cc
References Fun4AllStreamingInputManager::AddMvtxFeeId(), Fun4AllStreamingInputManager::AddMvtxL1TrgBco(), Fun4AllStreamingInputManager::AddMvtxRawHit(), SingleStreamingInput::AllDone(), assert, DATAEVENT, DecodeFeeid(), SingleStreamingInput::fileclose(), SingleStreamingInput::GetEventiterator(), Event::getEvtSequence(), Event::getEvtType(), Packet::getIdentifier(), Event::getPacketList(), Event::getRunNumber(), GetSomeMoreEvents(), InputFileHandler::GetVerbosity(), gtmL1BcoSet, i, Event::identify(), Packet::identify(), it, Packet::iValue(), Packet::lValue(), m_BclkStack, m_BeamClockFEE, m_FEEBclkMap, m_FeeStrobeMap, m_MvtxRawHitMap, m_NumSpecialEvents, InputFileHandler::OpenNextFile(), plist, SingleStreamingInput::RunNumber(), MvtxRawHit::set_bco(), MvtxRawHit::set_chip_bc(), MvtxRawHit::set_chip_id(), MvtxRawHit::set_col(), MvtxRawHit::set_layer_id(), MvtxRawHit::set_row(), MvtxRawHit::set_stave_id(), MvtxRawHit::set_strobe_bc(), SingleStreamingInput::StreamingInputManager(), and Fun4AllBase::Verbosity().
std::set<int>& SingleMvtxPoolInput::getFeeIdSet (const uint64_t & bco) inline
Definition at line 36 of file SingleMvtxPoolInput.h.
View newest version in sPHENIX GitHub at line 36 of file SingleMvtxPoolInput.h
References m_BeamClockFEE.
bool SingleMvtxPoolInput::GetSomeMoreEvents ()
Definition at line 312 of file SingleMvtxPoolInput.cc.
View newest version in sPHENIX GitHub at line 312 of file SingleMvtxPoolInput.cc
References SingleStreamingInput::AllDone(), m_BcoRange, m_FEEBclkMap, and m_MvtxRawHitMap.
Referenced by FillPool().
void SingleMvtxPoolInput::Print (const std::string & what = "ALL") const override virtual
Print out some info about this module.
Parameters
what can be used to specify what to print exactly.
Reimplemented from SingleStreamingInput.
Definition at line 189 of file SingleMvtxPoolInput.cc.
View newest version in sPHENIX GitHub at line 189 of file SingleMvtxPoolInput.cc
References m_BclkStack, m_BeamClockFEE, m_FEEBclkMap, m_FeeStrobeMap, and m_MvtxRawHitMap.
void SingleMvtxPoolInput::SetBcoRange (const unsigned int i) inline
Definition at line 32 of file SingleMvtxPoolInput.h.
View newest version in sPHENIX GitHub at line 32 of file SingleMvtxPoolInput.h
References i, and m_BcoRange.
Referenced by Fun4All_Stream_Combiner().
void SingleMvtxPoolInput::SetNegativeBco (const unsigned int value) inline
Definition at line 34 of file SingleMvtxPoolInput.h.
View newest version in sPHENIX GitHub at line 34 of file SingleMvtxPoolInput.h
References m_NegativeBco, and value.
Referenced by Fun4All_Stream_Combiner().
Member Data Documentation
std::set<uint64_t> SingleMvtxPoolInput::gtmL1BcoSet private
Definition at line 59 of file SingleMvtxPoolInput.h.
View newest version in sPHENIX GitHub at line 59 of file SingleMvtxPoolInput.h
Referenced by CleanupUsedPackets(), and FillPool().
std::set<uint64_t> SingleMvtxPoolInput::m_BclkStack private
Definition at line 58 of file SingleMvtxPoolInput.h.
View newest version in sPHENIX GitHub at line 58 of file SingleMvtxPoolInput.h
Referenced by CleanupUsedPackets(), ClearCurrentEvent(), FillPool(), and Print().
unsigned int SingleMvtxPoolInput::m_BcoRange {0} private
Definition at line 51 of file SingleMvtxPoolInput.h.
View newest version in sPHENIX GitHub at line 51 of file SingleMvtxPoolInput.h
Referenced by ConfigureStreamingInputManager(), GetSomeMoreEvents(), and SetBcoRange().
std::map<uint64_t, std::set<int> > SingleMvtxPoolInput::m_BeamClockFEE private
Definition at line 54 of file SingleMvtxPoolInput.h.
View newest version in sPHENIX GitHub at line 54 of file SingleMvtxPoolInput.h
Referenced by CleanupUsedPackets(), FillPool(), getFeeIdSet(), and Print().
std::map<int, uint64_t> SingleMvtxPoolInput::m_FEEBclkMap private
Definition at line 56 of file SingleMvtxPoolInput.h.
View newest version in sPHENIX GitHub at line 56 of file SingleMvtxPoolInput.h
Referenced by CheckPoolDepth(), FillPool(), GetSomeMoreEvents(), and Print().
std::map<int, uint64_t> SingleMvtxPoolInput::m_FeeStrobeMap private
Definition at line 57 of file SingleMvtxPoolInput.h.
View newest version in sPHENIX GitHub at line 57 of file SingleMvtxPoolInput.h
Referenced by CleanupUsedPackets(), FillPool(), and Print().
std::map<uint64_t, std::vector<MvtxRawHit *> > SingleMvtxPoolInput::m_MvtxRawHitMap private
Definition at line 55 of file SingleMvtxPoolInput.h.
View newest version in sPHENIX GitHub at line 55 of file SingleMvtxPoolInput.h
Referenced by CleanupUsedPackets(), FillPool(), GetSomeMoreEvents(), and Print().
unsigned int SingleMvtxPoolInput::m_NegativeBco {0} private
Definition at line 52 of file SingleMvtxPoolInput.h.
View newest version in sPHENIX GitHub at line 52 of file SingleMvtxPoolInput.h
Referenced by ConfigureStreamingInputManager(), and SetNegativeBco().
unsigned int SingleMvtxPoolInput::m_NumSpecialEvents {0} private
Definition at line 50 of file SingleMvtxPoolInput.h.
View newest version in sPHENIX GitHub at line 50 of file SingleMvtxPoolInput.h
Referenced by FillPool().
Packet** SingleMvtxPoolInput::plist {nullptr} private
Definition at line 49 of file SingleMvtxPoolInput.h.
View newest version in sPHENIX GitHub at line 49 of file SingleMvtxPoolInput.h
Referenced by FillPool(), SingleMvtxPoolInput(), and ~SingleMvtxPoolInput().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/framework/fun4allraw/SingleMvtxPoolInput.h
coresoftware/blob/master/offline/framework/fun4allraw/SingleMvtxPoolInput.cc