Analysis Software: TrkrClusterContainerv4 Class Reference
TrkrClusterContainerv4 Class Reference
Cluster container object.
#include <coresoftware/blob/master/offline/packages/trackbase/TrkrClusterContainerv4.h>
Public Member Functions
TrkrClusterContainerv4 ()=default
void Reset () override
reset method
void identify (std::ostream &os=std::cout) const override
identify object
void addClusterSpecifyKey (const TrkrDefs::cluskey, TrkrCluster *) override
add a cluster with specific key
void removeCluster (TrkrDefs::cluskey) override
remove cluster
ConstRange getClusters () const override
return all clusters
ConstRange getClusters (TrkrDefs::hitsetkey) override
get all clusters matching hitset
TrkrCluster * findCluster (TrkrDefs::cluskey) const override
find cluster matching given key
HitSetKeyList getHitSetKeys () const override
get hitset key list
HitSetKeyList getHitSetKeys (const TrkrDefs::TrkrId) const override
get hitset key list for a given detector
HitSetKeyList getHitSetKeys (const TrkrDefs::TrkrId, const uint8_t) const override
get hitset key list for a given detector and layer
unsigned int size (void) const override
total number of clusters
Private Types
using Vector = std::vector< TrkrCluster * >
convenient alias
Private Attributes
std::map< TrkrDefs::hitsetkey,
Vector > m_clusmap
the actual container
Map m_tmpmap
temporary map
Additional Inherited Members
Public Types inherited from TrkrClusterContainer
using Map = std::map< TrkrDefs::cluskey, TrkrCluster * >
using Iterator = Map::iterator
using ConstIterator = Map::const_iterator
using Range = std::pair< Iterator, Iterator >
using ConstRange = std::pair< ConstIterator, ConstIterator >
using HitSetKeyList = std::vector< TrkrDefs::hitsetkey >
Protected Member Functions inherited from TrkrClusterContainer
TrkrClusterContainer ()=default
constructor
Detailed Description
Cluster container object.
Definition at line 20 of file TrkrClusterContainerv4.h.
View newest version in sPHENIX GitHub at line 20 of file TrkrClusterContainerv4.h
Member Typedef Documentation
using TrkrClusterContainerv4::Vector = std::vector<TrkrCluster*> private
convenient alias
Definition at line 49 of file TrkrClusterContainerv4.h.
View newest version in sPHENIX GitHub at line 49 of file TrkrClusterContainerv4.h
Constructor & Destructor Documentation
TrkrClusterContainerv4::TrkrClusterContainerv4 () default
Member Function Documentation
void TrkrClusterContainerv4::addClusterSpecifyKey (const TrkrDefs::cluskey , TrkrCluster *) override virtual
add a cluster with specific key
Reimplemented from TrkrClusterContainer.
Definition at line 94 of file TrkrClusterContainerv4.cc.
View newest version in sPHENIX GitHub at line 94 of file TrkrClusterContainerv4.cc
References TrkrDefs::getClusIndex(), TrkrDefs::getHitSetKeyFromClusKey(), index, and m_clusmap.
Referenced by FilterEvents::process_event().
TrkrCluster * TrkrClusterContainerv4::findCluster (TrkrDefs::cluskey) const override virtual
find cluster matching given key
Reimplemented from TrkrClusterContainer.
Definition at line 179 of file TrkrClusterContainerv4.cc.
View newest version in sPHENIX GitHub at line 179 of file TrkrClusterContainerv4.cc
References TrkrDefs::getClusIndex(), TrkrDefs::getHitSetKeyFromClusKey(), index, and m_clusmap.
Referenced by dNdEtaINTT::GetRecoClusterInfo(), and FilterEvents::process_event().
TrkrClusterContainerv4::ConstRange TrkrClusterContainerv4::getClusters (void) const override virtual
return all clusters
Reimplemented from TrkrClusterContainer.
Definition at line 137 of file TrkrClusterContainerv4.cc.
View newest version in sPHENIX GitHub at line 137 of file TrkrClusterContainerv4.cc
Referenced by dNdEtaINTT::GetRecoClusterInfo().
TrkrClusterContainerv4::ConstRange TrkrClusterContainerv4::getClusters (TrkrDefs::hitsetkey) override virtual
get all clusters matching hitset
Reimplemented from TrkrClusterContainer.
Definition at line 146 of file TrkrClusterContainerv4.cc.
View newest version in sPHENIX GitHub at line 146 of file TrkrClusterContainerv4.cc
References clusters, TrkrDefs::genClusKey(), index, m_clusmap, and m_tmpmap.
TrkrClusterContainer::HitSetKeyList TrkrClusterContainerv4::getHitSetKeys () const override virtual
get hitset key list
Reimplemented from TrkrClusterContainer.
Definition at line 210 of file TrkrClusterContainerv4.cc.
View newest version in sPHENIX GitHub at line 210 of file TrkrClusterContainerv4.cc
References m_clusmap, out, and Acts::Test::transform.
Referenced by dNdEtaINTT::GetRecoClusterInfo().
TrkrClusterContainer::HitSetKeyList TrkrClusterContainerv4::getHitSetKeys (const TrkrDefs::TrkrId) const override virtual
get hitset key list for a given detector
Reimplemented from TrkrClusterContainer.
Definition at line 222 of file TrkrClusterContainerv4.cc.
View newest version in sPHENIX GitHub at line 222 of file TrkrClusterContainerv4.cc
References parse_cmake_options::begin, end, TrkrDefs::getHitSetKeyHi(), TrkrDefs::getHitSetKeyLo(), m_clusmap, out, and Acts::Test::transform.
TrkrClusterContainer::HitSetKeyList TrkrClusterContainerv4::getHitSetKeys (const TrkrDefs::TrkrId , const uint8_t) const override virtual
get hitset key list for a given detector and layer
Reimplemented from TrkrClusterContainer.
Definition at line 243 of file TrkrClusterContainerv4.cc.
View newest version in sPHENIX GitHub at line 243 of file TrkrClusterContainerv4.cc
References parse_cmake_options::begin, end, TrkrDefs::getHitSetKeyHi(), TrkrDefs::getHitSetKeyLo(), m_clusmap, out, and Acts::Test::transform.
void TrkrClusterContainerv4::identify (std::ostream & = std::cout) const override virtual
identify object
Reimplemented from TrkrClusterContainer.
Definition at line 45 of file TrkrClusterContainerv4.cc.
View newest version in sPHENIX GitHub at line 45 of file TrkrClusterContainerv4.cc
References TrkrDefs::getLayer(), layer, m_clusmap, and size().
void TrkrClusterContainerv4::removeCluster (TrkrDefs::cluskey) override virtual
remove cluster
Reimplemented from TrkrClusterContainer.
Definition at line 68 of file TrkrClusterContainerv4.cc.
View newest version in sPHENIX GitHub at line 68 of file TrkrClusterContainerv4.cc
References TrkrDefs::getClusIndex(), TrkrDefs::getHitSetKeyFromClusKey(), index, and m_clusmap.
void TrkrClusterContainerv4::Reset () override virtual
reset method
Reimplemented from TrkrClusterContainer.
Definition at line 19 of file TrkrClusterContainerv4.cc.
View newest version in sPHENIX GitHub at line 19 of file TrkrClusterContainerv4.cc
References m_clusmap, and m_tmpmap.
Referenced by FilterEvents::process_event().
unsigned int TrkrClusterContainerv4::size (void) const override virtual
total number of clusters
Reimplemented from TrkrClusterContainer.
Definition at line 264 of file TrkrClusterContainerv4.cc.
View newest version in sPHENIX GitHub at line 264 of file TrkrClusterContainerv4.cc
References m_clusmap.
Referenced by identify(), and FilterEvents::process_event().
Member Data Documentation
std::map<TrkrDefs::hitsetkey, Vector> TrkrClusterContainerv4::m_clusmap private
the actual container
Definition at line 52 of file TrkrClusterContainerv4.h.
View newest version in sPHENIX GitHub at line 52 of file TrkrClusterContainerv4.h
Referenced by addClusterSpecifyKey(), findCluster(), getClusters(), getHitSetKeys(), identify(), removeCluster(), Reset(), and size().
Map TrkrClusterContainerv4::m_tmpmap private
temporary map
the map is transient. It must not be written to the output. To do this one adds //! after the declaration see https://root.cern.ch/root/htmldoc/guides/users-guide/InputOutput.html for details
Definition at line 60 of file TrkrClusterContainerv4.h.
View newest version in sPHENIX GitHub at line 60 of file TrkrClusterContainerv4.h
Referenced by getClusters(), and Reset().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/trackbase/TrkrClusterContainerv4.h
coresoftware/blob/master/offline/packages/trackbase/TrkrClusterContainerv4.cc