Analysis Software: ICGlauber Class Reference
ICGlauber Class Reference
#include <JETSCAPE/blob/main/jail/vhlle/src/icGlauber.h>
Public Member Functions
ICGlauber (double e, double impactPar, double _tau0)
~ICGlauber (void)
double eProfile (double x, double y)
void setIC (Fluid *f, EoS *eos)
Private Member Functions
void findRPhi (void)
double rPhi (double phi)
double WoodSaxon (double *x, double *p)
double Thickness (double *x, double *p)
Private Attributes
TF1 * iff
double rho0
double prms [4]
double * _rphi
double epsilon
double b
double tau0
Detailed Description
Definition at line 7 of file icGlauber.h.
View newest version in sPHENIX GitHub at line 7 of file icGlauber.h
Constructor & Destructor Documentation
ICGlauber::ICGlauber (double e, double impactPar, double _tau0)
Definition at line 27 of file icGlauber.cpp.
View newest version in sPHENIX GitHub at line 27 of file icGlauber.cpp
References KFPMath::b, Acts::UnitConstants::e, impactPar, and tau0.
ICGlauber::~ICGlauber (void)
Definition at line 33 of file icGlauber.cpp.
View newest version in sPHENIX GitHub at line 33 of file icGlauber.cpp
Member Function Documentation
double ICGlauber::eProfile (double x, double y)
Definition at line 35 of file icGlauber.cpp.
View newest version in sPHENIX GitHub at line 35 of file icGlauber.cpp
References A, KFPMath::b, Acts::UnitConstants::e, Ra, and sigma.
void ICGlauber::findRPhi (void) private
Definition at line 48 of file icGlauber.cpp.
View newest version in sPHENIX GitHub at line 48 of file icGlauber.cpp
References C_PI, nphi, ActsTests::PropagationDatasets::phi, physmon_track_finding_ttbar::r, r1, r2, and Ra.
double ICGlauber::rPhi (double phi) private
Definition at line 65 of file icGlauber.cpp.
View newest version in sPHENIX GitHub at line 65 of file icGlauber.cpp
References C_PI, and nphi.
void ICGlauber::setIC (Fluid * f, EoS * eos)
Definition at line 76 of file icGlauber.cpp.
View newest version in sPHENIX GitHub at line 76 of file icGlauber.cpp
References A, Acts::PhysicalConstants::c, C_PI, dlt, Acts::UnitConstants::e, eta, generate_files_AA::ff, Fluid::getCell(), Fluid::getDx(), Fluid::getDy(), Fluid::getDz(), Fluid::getNX(), Fluid::getNY(), Fluid::getNZ(), Fluid::getX(), Fluid::getY(), Fluid::getZ(), EoS::p(), Ra, Cell::saveQprev(), Cell::setAllM(), Cell::setPrimVar(), sigma, tau0, Thickness(), vx, vy, vz, WoodSaxon(), ambiguity_solver_full_chain::x, and y.
Referenced by main().
double ICGlauber::Thickness (double * x, double * p) private
Definition at line 149 of file icGlauber.cpp.
View newest version in sPHENIX GitHub at line 149 of file icGlauber.cpp
References Acts::UnitConstants::e, and WoodSaxon().
Referenced by setIC().
double ICGlauber::WoodSaxon (double * x, double * p) private
Definition at line 165 of file icGlauber.cpp.
View newest version in sPHENIX GitHub at line 165 of file icGlauber.cpp
Referenced by setIC(), and Thickness().
Member Data Documentation
double* ICGlauber::_rphi private
Definition at line 12 of file icGlauber.h.
View newest version in sPHENIX GitHub at line 12 of file icGlauber.h
double ICGlauber::b private
Definition at line 22 of file icGlauber.h.
View newest version in sPHENIX GitHub at line 22 of file icGlauber.h
double ICGlauber::epsilon private
Definition at line 22 of file icGlauber.h.
View newest version in sPHENIX GitHub at line 22 of file icGlauber.h
TF1* ICGlauber::iff private
Definition at line 8 of file icGlauber.h.
View newest version in sPHENIX GitHub at line 8 of file icGlauber.h
double ICGlauber::prms[4] private
Definition at line 10 of file icGlauber.h.
View newest version in sPHENIX GitHub at line 10 of file icGlauber.h
double ICGlauber::rho0 private
Definition at line 10 of file icGlauber.h.
View newest version in sPHENIX GitHub at line 10 of file icGlauber.h
double ICGlauber::tau0 private
Definition at line 22 of file icGlauber.h.
View newest version in sPHENIX GitHub at line 22 of file icGlauber.h
The documentation for this class was generated from the following files:
JETSCAPE/blob/main/jail/vhlle/src/icGlauber.h
JETSCAPE/blob/main/jail/vhlle/src/icGlauber.cpp