Analysis Software: PHG4EPSteppingAction Class Reference
PHG4EPSteppingAction Class Reference
#include <coresoftware/blob/master/simulation/g4simulation/g4epd/PHG4EPSteppingAction.h>
Public Member Functions
PHG4EPSteppingAction (PHG4EPDetector *, PHParametersContainer const *)
~PHG4EPSteppingAction () override
bool UserSteppingAction (const G4Step *, bool) override
stepping action. This defines processing of a single step in a given volume
void SetInterfacePointers (PHCompositeNode *) override
Public Member Functions inherited from PHG4SteppingAction
PHG4SteppingAction (const std::string &name, const int i=0)
virtual ~PHG4SteppingAction ()
virtual void Verbosity (const int i)
virtual int Verbosity () const
virtual int Init ()
virtual double GetScintLightYield (const G4Step *step)
get scintillation photon count. It require a custom set SCINTILLATIONYIELD property to work
virtual double GetVisibleEnergyDeposition (const G4Step *step)
get amount of energy that can make scintillation light, in Unit of GeV.
virtual void StoreLocalCoordinate (PHG4Hit *hit, const G4Step *step, const bool do_prepoint, const bool do_postpoint)
Extract local coordinate of the hit and save to PHG4Hit.
virtual void Print (const std::string &what) const
std::string GetName () const
void SetName (const std::string &name)
virtual void SetLightCorrection (const double inner_radius, const double inner_corr, const double outer_radius, const double outer_corr)
virtual double GetLightCorrection (const double r) const
virtual double GetLightCorrection (const double xpos, const double ypos) const
virtual bool ValidCorrection () const
Private Attributes
PHG4EPDetector * m_detector
PHG4HitContainer * m_hit_container
PHG4Hit * m_hit
int32_t poststatus
Detailed Description
Definition at line 19 of file PHG4EPSteppingAction.h.
View newest version in sPHENIX GitHub at line 19 of file PHG4EPSteppingAction.h
Constructor & Destructor Documentation
PHG4EPSteppingAction::PHG4EPSteppingAction (PHG4EPDetector * detector, PHParametersContainer const *)
Definition at line 35 of file PHG4EPSteppingAction.cc.
View newest version in sPHENIX GitHub at line 35 of file PHG4EPSteppingAction.cc
PHG4EPSteppingAction::~PHG4EPSteppingAction () override
Definition at line 45 of file PHG4EPSteppingAction.cc.
View newest version in sPHENIX GitHub at line 45 of file PHG4EPSteppingAction.cc
References m_hit.
Member Function Documentation
void PHG4EPSteppingAction::SetInterfacePointers (PHCompositeNode * node) override virtual
Reimplemented from PHG4SteppingAction.
Definition at line 148 of file PHG4EPSteppingAction.cc.
View newest version in sPHENIX GitHub at line 148 of file PHG4EPSteppingAction.cc
References PHG4Detector::GetName(), graph_fancy::label, m_detector, m_hit_container, and PHG4EPDetector::SuperDetector().
Referenced by PHG4EPDSubsystem::process_event().
bool PHG4EPSteppingAction::UserSteppingAction (const G4Step * step, bool was_used) override virtual
stepping action. This defines processing of a single step in a given volume
returns true if hits associated to this step was processed by this detector
Parameters
step pointer to the geant 4 step class
was_used,: true if the hit was already used by a previously registered subsystem
Implements PHG4SteppingAction.
Definition at line 50 of file PHG4EPSteppingAction.cc.
View newest version in sPHENIX GitHub at line 50 of file PHG4EPSteppingAction.cc
References PHG4Shower::add_g4hit_id(), PHG4HitContainer::AddHit(), Acts::UnitConstants::cm, PHG4EPDetector::contains(), PHG4Hit::get_edep(), PHG4Hit::get_eion(), PHG4Hit::get_hit_id(), PHG4Hit::get_light_yield(), PHG4HitContainer::GetID(), PHG4SteppingAction::GetLightCorrection(), PHG4TrackUserInfoV1::GetShower(), PHG4TrackUserInfoV1::GetUserTrackId(), PHG4SteppingAction::GetVisibleEnergyDeposition(), Acts::UnitConstants::GeV, m_detector, m_hit, m_hit_container, PHG4EPDetector::module_id_for(), particle, poststatus, PHG4Hit::Reset(), PHG4Hit::set_edep(), PHG4Hit::set_eion(), PHG4Hit::set_light_yield(), PHG4Hit::set_scint_id(), PHG4Hit::set_t(), PHG4Hit::set_trkid(), PHG4Hit::set_x(), PHG4Hit::set_y(), PHG4Hit::set_z(), PHG4TrackUserInfoV1::SetKeep(), and Acts::Test::volume.
Member Data Documentation
PHG4EPDetector* PHG4EPSteppingAction::m_detector private
Definition at line 30 of file PHG4EPSteppingAction.h.
View newest version in sPHENIX GitHub at line 30 of file PHG4EPSteppingAction.h
Referenced by SetInterfacePointers(), and UserSteppingAction().
PHG4Hit* PHG4EPSteppingAction::m_hit private
Definition at line 33 of file PHG4EPSteppingAction.h.
View newest version in sPHENIX GitHub at line 33 of file PHG4EPSteppingAction.h
Referenced by UserSteppingAction(), and ~PHG4EPSteppingAction().
PHG4HitContainer* PHG4EPSteppingAction::m_hit_container private
Definition at line 32 of file PHG4EPSteppingAction.h.
View newest version in sPHENIX GitHub at line 32 of file PHG4EPSteppingAction.h
Referenced by SetInterfacePointers(), and UserSteppingAction().
int32_t PHG4EPSteppingAction::poststatus private
Definition at line 35 of file PHG4EPSteppingAction.h.
View newest version in sPHENIX GitHub at line 35 of file PHG4EPSteppingAction.h
Referenced by UserSteppingAction().
The documentation for this class was generated from the following files:
coresoftware/blob/master/simulation/g4simulation/g4epd/PHG4EPSteppingAction.h
coresoftware/blob/master/simulation/g4simulation/g4epd/PHG4EPSteppingAction.cc