Analysis Software: JETSCAPE/blob/main/external_packages/trento/test/test_collider.cxx File Reference
test_collider.cxx File Reference
#include "../src/collider.h"
#include "catch.hpp"
#include "util.h"
#include <iostream>
#include "../src/nucleus.h"
Functions
TEST_CASE ("collider")
TEST_CASE ("fixed impact parameter")
TEST_CASE ("random seed")
Function Documentation
TEST_CASE ("collider")
Definition at line 16 of file test_collider.cxx.
View newest version in sPHENIX GitHub at line 16 of file test_collider.cxx
References CHECK, trento::Nucleus::create(), line, make_var_map(), N, npart(), trento::Collider::run_events(), and capture_stdout::stream.
TEST_CASE ("fixed impact parameter")
Definition at line 77 of file test_collider.cxx.
View newest version in sPHENIX GitHub at line 77 of file test_collider.cxx
References KFPMath::b, CHECK, line, make_var_map(), capture_stdout::stream, and ambiguity_solver_full_chain::x.
TEST_CASE ("random seed")
Definition at line 119 of file test_collider.cxx.
View newest version in sPHENIX GitHub at line 119 of file test_collider.cxx
References CHECK, make_var_map(), check_smearing_config::output, physmon_simulation::s, seed, and capture_stdout::stream.