Analysis Software: Acts::Seed< SpacePoint > Class Template Reference
Acts::Seed< SpacePoint > Class Template Reference
#include <acts/blob/sPHENIX/Core/include/Acts/Seeding/Seed.hpp>
Public Member Functions
Seed (const SpacePoint &b, const SpacePoint &m, const SpacePoint &u, float vertex, float seedQuality=-std::numeric_limits< float >::infinity())
Seed (const Seed &)=default
Seed & operator= (const Seed &)=default
const auto & sp () const
double z () const
float seedQuality () const
Private Attributes
boost::container::small_vector
< const SpacePoint *, 3 > m_spacepoints
float m_zvertex
float m_seedQuality
Detailed Description
template<typename SpacePoint>
class Acts::Seed< SpacePoint >
Definition at line 18 of file Seed.hpp.
View newest version in sPHENIX GitHub at line 18 of file Seed.hpp
Constructor & Destructor Documentation
template<typename SpacePoint > Acts::Seed< SpacePoint >::Seed (const SpacePoint & b, const SpacePoint & m, const SpacePoint & u, float vertex, float seedQuality = -std::numeric_limits<float>::infinity())
Definition at line 45 of file Seed.hpp.
View newest version in sPHENIX GitHub at line 45 of file Seed.hpp
template<typename SpacePoint> Acts::Seed< SpacePoint >::Seed (const Seed< SpacePoint > &) default
Member Function Documentation
template<typename SpacePoint> Seed& Acts::Seed< SpacePoint >::operator= (const Seed< SpacePoint > &) default
template<typename SpacePoint> float Acts::Seed< SpacePoint >::seedQuality () const inline
Definition at line 32 of file Seed.hpp.
View newest version in sPHENIX GitHub at line 32 of file Seed.hpp
References Acts::Seed< SpacePoint >::m_seedQuality.
template<typename SpacePoint> const auto& Acts::Seed< SpacePoint >::sp () const inline
Definition at line 30 of file Seed.hpp.
View newest version in sPHENIX GitHub at line 30 of file Seed.hpp
References Acts::Seed< SpacePoint >::m_spacepoints.
Referenced by ActsExamples::PrototracksToParameters::execute(), Acts::SeedFilter< external_spacepoint_t >::filterSeeds_1SpFixed(), main(), and ActsExamples::seedToPrototrack().
template<typename SpacePoint> double Acts::Seed< SpacePoint >::z () const inline
Definition at line 31 of file Seed.hpp.
View newest version in sPHENIX GitHub at line 31 of file Seed.hpp
References Acts::Seed< SpacePoint >::m_zvertex.
Member Data Documentation
template<typename SpacePoint> float Acts::Seed< SpacePoint >::m_seedQuality private
Definition at line 37 of file Seed.hpp.
View newest version in sPHENIX GitHub at line 37 of file Seed.hpp
Referenced by Acts::Seed< SpacePoint >::seedQuality().
template<typename SpacePoint> boost::container::small_vector<const SpacePoint*, 3> Acts::Seed< SpacePoint >::m_spacepoints private
Definition at line 35 of file Seed.hpp.
View newest version in sPHENIX GitHub at line 35 of file Seed.hpp
Referenced by Acts::Seed< SpacePoint >::sp().
template<typename SpacePoint> float Acts::Seed< SpacePoint >::m_zvertex private
Definition at line 36 of file Seed.hpp.
View newest version in sPHENIX GitHub at line 36 of file Seed.hpp
Referenced by Acts::Seed< SpacePoint >::z().
The documentation for this class was generated from the following file:
acts/blob/sPHENIX/Core/include/Acts/Seeding/Seed.hpp