Analysis Software: coresoftware/blob/master/calibrations/tpc/fillDigitalCurrentMaps/macros/Fun4All_FillDCMap.C File Reference
Fun4All_FillDCMap.C File Reference
#include <fun4all/Fun4AllServer.h>
#include <fun4all/Fun4AllInputManager.h>
#include <fun4all/Fun4AllDstInputManager.h>
#include <readDigitalCurrents.h>
#include <stdio.h>
#include <frog/FROG.h>
#include <string>
Functions
std::vector< int > readBeamXings ()
int closest (std::vector< int > const &vec, int value)
void Fun4All_FillDCMap (const int nEvents=1000, const int eventsInFileStart=0, const int eventsBeamCrossing=1508071, const string &fname="/sphenix/user/shulga/Work/IBF/macros/detectors/sPHENIX/Files/DST_G4Hits_sHijing_0-12fm_005000_006000.root", const string &foutputname="./Files/hists_G4Hits_sHijing_0-12fm_000000_001000.root")
Function Documentation
int closest (std::vector< int > const & vec, int value)
Definition at line 49 of file Fun4All_FillDCMap.C.
View newest version in sPHENIX GitHub at line 49 of file Fun4All_FillDCMap.C
References it, and value.
Referenced by Acts::Test::BOOST_AUTO_TEST_CASE(), BOOST_DATA_TEST_CASE(), Acts::BoundaryCheck::computeClosestPointOnPolygon(), Acts::ImpactPointEstimator< input_track_t, propagator_t, propagator_options_t >::estimate3DImpactParameters(), Acts::Polyhedron::extent(), Acts::GaussianSumFitter< propagator_t, bethe_heitler_approx_t, traj_t >::fit_impl(), Acts::ImpactPointEstimator< input_track_t, propagator_t, propagator_options_t >::getImpactParameters(), meanFromFree(), Acts::MultiStepperSurfaceReached::operator()(), Acts::Test::SurfaceObserver< Surface >::operator()(), Acts::SurfaceReached::operator()(), ActsExamples::RootTrajectorySummaryWriter::writeT(), and ActsExamples::VertexPerformanceWriter::writeT().
void Fun4All_FillDCMap (const int nEvents = 1000, const int eventsInFileStart = 0, const int eventsBeamCrossing = 1508071, const string & fname = "/sphenix/user/shulga/Work/IBF/macros/detectors/sPHENIX/Files/DST_G4Hits_sHijing_0-12fm_005000_006000.root", const string & foutputname = "./Files/hists_G4Hits_sHijing_0-12fm_000000_001000.root")
Definition at line 56 of file Fun4All_FillDCMap.C.
View newest version in sPHENIX GitHub at line 56 of file Fun4All_FillDCMap.C
References add_histos::bXs, distance(), Fun4AllServer::End(), Fun4AllInputManager::fileopen(), INTTVtxZ::fname, in, index, Fun4AllServer::instance(), it, FROG::location(), n, nEvents, readBeamXings(), Fun4AllServer::registerInputManager(), Fun4AllServer::registerSubsystem(), Fun4AllServer::run(), readDigitalCurrents::SetBeamXing(), readDigitalCurrents::SetCCGC(), readDigitalCurrents::SetCollSyst(), readDigitalCurrents::SetEvtStart(), readDigitalCurrents::SetIBF(), and to_string().
std::vector< int > readBeamXings ()
Definition at line 20 of file Fun4All_FillDCMap.C.
View newest version in sPHENIX GitHub at line 20 of file Fun4All_FillDCMap.C
References add_histos::bXs, i, line, n, and generate_files_AA::n_line.
Referenced by Fun4All_FillChargesMap_300evts_MDC2(), and Fun4All_FillDCMap().