Analysis Software: ParticleFlowElementContainer Class Reference
ParticleFlowElementContainer Class Reference
#include <coresoftware/blob/master/offline/packages/particleflow/ParticleFlowElementContainer.h>
Public Types
typedef std::map< int,
ParticleFlowElement * > Map
typedef Map::iterator Iterator
typedef Map::const_iterator ConstIterator
typedef std::pair< Iterator,
Iterator > Range
typedef std::pair
< ConstIterator, ConstIterator > ConstRange
Public Member Functions
ParticleFlowElementContainer ()
~ParticleFlowElementContainer () override
void Reset () override
Clear Event.
int isValid () const override
isValid returns non zero if object contains vailid data
void identify (std::ostream &os=std::cout) const override
void AddParticleFlowElement (int index, ParticleFlowElement *pflowElement)
ParticleFlowElement * getParticleFlowElement (int index)
const ParticleFlowElement * getParticleFlowElement (int index) const
ConstRange getParticleFlowElements (void) const
return all elements
Range getParticleFlowElements (void)
unsigned int size () const
Public Member Functions inherited from PHObject
PHObject ()
ctor
~PHObject () override
dtor
virtual PHObject * CloneMe () const
Virtual copy constructor.
virtual PHObject * clone () const final
PHObject * Clone (const char *newname="") const final
void Copy (TObject &object) const final
virtual int Integrate () const
virtual int Integrate (PHObject *)
virtual void CopyFrom (const PHObject *obj)
Protected Attributes
Map _pflowElementMap
Detailed Description
Definition at line 17 of file ParticleFlowElementContainer.h.
View newest version in sPHENIX GitHub at line 17 of file ParticleFlowElementContainer.h
Member Typedef Documentation
typedef Map::const_iterator ParticleFlowElementContainer::ConstIterator
Definition at line 22 of file ParticleFlowElementContainer.h.
View newest version in sPHENIX GitHub at line 22 of file ParticleFlowElementContainer.h
typedef std::pair<ConstIterator, ConstIterator> ParticleFlowElementContainer::ConstRange
Definition at line 24 of file ParticleFlowElementContainer.h.
View newest version in sPHENIX GitHub at line 24 of file ParticleFlowElementContainer.h
typedef Map::iterator ParticleFlowElementContainer::Iterator
Definition at line 21 of file ParticleFlowElementContainer.h.
View newest version in sPHENIX GitHub at line 21 of file ParticleFlowElementContainer.h
typedef std::map<int, ParticleFlowElement *> ParticleFlowElementContainer::Map
Definition at line 20 of file ParticleFlowElementContainer.h.
View newest version in sPHENIX GitHub at line 20 of file ParticleFlowElementContainer.h
typedef std::pair<Iterator, Iterator> ParticleFlowElementContainer::Range
Definition at line 23 of file ParticleFlowElementContainer.h.
View newest version in sPHENIX GitHub at line 23 of file ParticleFlowElementContainer.h
Constructor & Destructor Documentation
ParticleFlowElementContainer::ParticleFlowElementContainer () inline
Definition at line 26 of file ParticleFlowElementContainer.h.
View newest version in sPHENIX GitHub at line 26 of file ParticleFlowElementContainer.h
ParticleFlowElementContainer::~ParticleFlowElementContainer () inline override
Definition at line 31 of file ParticleFlowElementContainer.h.
View newest version in sPHENIX GitHub at line 31 of file ParticleFlowElementContainer.h
Member Function Documentation
void ParticleFlowElementContainer::AddParticleFlowElement (int index, ParticleFlowElement * pflowElement)
Definition at line 23 of file ParticleFlowElementContainer.cc.
View newest version in sPHENIX GitHub at line 23 of file ParticleFlowElementContainer.cc
References _pflowElementMap, and index.
Referenced by ParticleFlowReco::process_event().
ParticleFlowElement * ParticleFlowElementContainer::getParticleFlowElement (int index)
Definition at line 31 of file ParticleFlowElementContainer.cc.
View newest version in sPHENIX GitHub at line 31 of file ParticleFlowElementContainer.cc
References _pflowElementMap, and it.
Referenced by TracksInJets::process_event(), and FullJetFinder::process_event().
const ParticleFlowElement * ParticleFlowElementContainer::getParticleFlowElement (int index) const
Definition at line 42 of file ParticleFlowElementContainer.cc.
View newest version in sPHENIX GitHub at line 42 of file ParticleFlowElementContainer.cc
References _pflowElementMap, and it.
ParticleFlowElementContainer::ConstRange ParticleFlowElementContainer::getParticleFlowElements (void) const
return all elements
Definition at line 11 of file ParticleFlowElementContainer.cc.
View newest version in sPHENIX GitHub at line 11 of file ParticleFlowElementContainer.cc
References _pflowElementMap.
Referenced by ResonanceJetTagging::addParticleFlow(), ParticleFlowJetInput::get_input(), ParticleFlowReco::process_event(), and DumpParticleFlowElementContainer::process_Node().
ParticleFlowElementContainer::Range ParticleFlowElementContainer::getParticleFlowElements (void)
Definition at line 17 of file ParticleFlowElementContainer.cc.
View newest version in sPHENIX GitHub at line 17 of file ParticleFlowElementContainer.cc
References _pflowElementMap.
void ParticleFlowElementContainer::identify (std::ostream & os = std::cout) const override virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from PHObject.
Definition at line 66 of file ParticleFlowElementContainer.cc.
View newest version in sPHENIX GitHub at line 66 of file ParticleFlowElementContainer.cc
References size().
int ParticleFlowElementContainer::isValid () const override virtual
isValid returns non zero if object contains vailid data
Reimplemented from PHObject.
Definition at line 52 of file ParticleFlowElementContainer.cc.
View newest version in sPHENIX GitHub at line 52 of file ParticleFlowElementContainer.cc
References _pflowElementMap.
void ParticleFlowElementContainer::Reset () override virtual
Clear Event.
Reimplemented from PHObject.
Definition at line 57 of file ParticleFlowElementContainer.cc.
View newest version in sPHENIX GitHub at line 57 of file ParticleFlowElementContainer.cc
References _pflowElementMap.
unsigned int ParticleFlowElementContainer::size (void) const inline
Definition at line 45 of file ParticleFlowElementContainer.h.
View newest version in sPHENIX GitHub at line 45 of file ParticleFlowElementContainer.h
References _pflowElementMap.
Referenced by identify(), and DumpParticleFlowElementContainer::process_Node().
Member Data Documentation
Map ParticleFlowElementContainer::_pflowElementMap protected
Definition at line 48 of file ParticleFlowElementContainer.h.
View newest version in sPHENIX GitHub at line 48 of file ParticleFlowElementContainer.h
Referenced by AddParticleFlowElement(), getParticleFlowElement(), getParticleFlowElements(), isValid(), Reset(), and size().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/particleflow/ParticleFlowElementContainer.h
coresoftware/blob/master/offline/packages/particleflow/ParticleFlowElementContainer.cc