Analysis Software: acts/blob/sPHENIX/Tests/UnitTests/Core/Geometry/BVHDataTestCase.hpp File Reference
BVHDataTestCase.hpp File Reference
#include "Acts/Surfaces/Surface.hpp"
Typedefs
using Box = Acts::Volume::BoundingBox
using Ray = Acts::Ray< double, 3 >
Functions
Test::CubicBVHTrackingGeometry grid (NBOXES, 1000, 5)
BOOST_DATA_TEST_CASE (bvhnavigation_test, bdata::random((bdata::seed=7, bdata::engine=std::mt19937(), bdata::distribution=std::uniform_real_distribution<>(-5, 5)))^bdata::random((bdata::seed=2, bdata::engine=std::mt19937(), bdata::distribution=std::uniform_real_distribution<>(-M_PI, M_PI)))^bdata::random((bdata::seed=3, bdata::engine=std::mt19937(), bdata::distribution=std::uniform_real_distribution<>(-100, 100)))^bdata::random((bdata::seed=4, bdata::engine=std::mt19937(), bdata::distribution=std::uniform_real_distribution<>(-100, 100)))^bdata::random((bdata::seed=5, bdata::engine=std::mt19937(), bdata::distribution=std::uniform_real_distribution<>(-100, 100)))^bdata::xrange(NTESTS), eta, phi, x, y, z, index)
Variables
GeometryContext tgContext = GeometryContext()
MagneticFieldContext mfContext = MagneticFieldContext()
auto volumes = grid.volumes
auto tg = grid.trackingGeometry
Typedef Documentation
using Box = Acts::Volume::BoundingBox
Definition at line 14 of file BVHDataTestCase.hpp.
View newest version in sPHENIX GitHub at line 14 of file BVHDataTestCase.hpp
using Ray = Acts::Ray<double, 3>
Definition at line 15 of file BVHDataTestCase.hpp.
View newest version in sPHENIX GitHub at line 15 of file BVHDataTestCase.hpp
Function Documentation
BOOST_DATA_TEST_CASE (bvhnavigation_test , bdata:: random(bdata::seed=7, bdata::engine=std::mt19937(),bdata::distribution=std::uniform_real_distribution<>(-5,5)))^bdata::random((bdata::seed=2, bdata::engine=std::mt19937(),bdata::distribution=std::uniform_real_distribution<>(-M_PI, M_PI)))^bdata::random((bdata::seed=3, bdata::engine=std::mt19937(),bdata::distribution=std::uniform_real_distribution<>(-100, 100)))^bdata::random((bdata::seed=4, bdata::engine=std::mt19937(),bdata::distribution=std::uniform_real_distribution<>(-100, 100)))^bdata::random((bdata::seed=5, bdata::engine=std::mt19937(),bdata::distribution=std::uniform_real_distribution<>(-100, 100)))^bdata::xrange(NTESTS, eta , phi , x , y , z , index)
Definition at line 25 of file BVHDataTestCase.hpp.
View newest version in sPHENIX GitHub at line 25 of file BVHDataTestCase.hpp
References Acts::ePos0, eta, Acts::ObjectIntersection< Surface >::forwardOrder(), i, index, Acts::IntegrationTest::mfContext, Acts::Test::navigator, ckf::options, Acts::PropagatorPlainOptions::pathLimit, ActsTests::PropagationDatasets::phi, Acts::ParticleHypothesis::pion(), Acts::Test::pos4(), Acts::s_onSurfaceTolerance, Acts::Experimental::detail::BlueprintHelper::sort(), step, propagation_timing::stepper, propagation_timing::steps, tg, Acts::tgContext, ActsTests::PropagationDatasets::theta, volumes, ambiguity_solver_full_chain::x, y, and physmon_track_finding_ttbar::z.
Test::CubicBVHTrackingGeometry grid (NBOXES , 1000 , 5)
Referenced by Acts::BinnedSPGroup< external_spacepoint_t >::BinnedSPGroup(), BOOST_AUTO_TEST_CASE(), Acts::Test::BOOST_AUTO_TEST_CASE(), ActsFatras::BOOST_DATA_TEST_CASE(), Acts::Experimental::IndexedRootVolumeFinderBuilder::construct(), Acts::Svg::LayerConverter::convert(), Acts::VolumeMaterialMapper::createExtraHits(), Acts::Cuda::SeedFinder< external_spacepoint_t >::createSeedsForGroup(), Acts::SeedFinder< external_spacepoint_t, platform_t >::createSeedsForGroup(), ActsExamples::SeedingAlgorithm::execute(), Acts::fieldMapRZ(), Acts::fieldMapXYZ(), Acts::VolumeMaterialMapper::finalizeMaps(), Acts::GridJsonConverter::fromJson(), Acts::IndexedSurfacesJsonConverter::fromJson(), main(), Acts::IntegrationTest::makeFieldMap(), Acts::materialMapperRZ(), Acts::materialMapperXYZ(), Acts::Experimental::detail::IndexedSurfacesGenerator< surface_container, indexed_updator >::operator()(), PHActsSiliconSeeding::runSeeder(), Acts::solenoidFieldMap(), while(), ActsExamples::RootMaterialWriter::writeMaterial(), and Acts::Svg::View::xy().
Variable Documentation
MagneticFieldContext mfContext = MagneticFieldContext()
Definition at line 18 of file BVHDataTestCase.hpp.
View newest version in sPHENIX GitHub at line 18 of file BVHDataTestCase.hpp
auto tg = grid.trackingGeometry
Definition at line 23 of file BVHDataTestCase.hpp.
View newest version in sPHENIX GitHub at line 23 of file BVHDataTestCase.hpp
Referenced by PHG4OHCalDetector::AddGeometryNode(), PHG4IHCalDetector::AddGeometryNode(), PHG4OuterHcalDetector::AddGeometryNode(), PHG4InnerHcalDetector::AddGeometryNode(), PHG4SpacalDetector::AddTowerGeometryNode(), BOOST_DATA_TEST_CASE(), CaloGeomMapping::CreateGeomNode(), RawTowerBuilder::CreateNodes(), RawTowerCombiner::CreateNodes(), Prototype2RawTowerBuilder::InitRun(), HcalRawTowerBuilder::InitRun(), and GPUTPCTrackParam::TransportToX().
GeometryContext tgContext = GeometryContext()
Definition at line 17 of file BVHDataTestCase.hpp.
View newest version in sPHENIX GitHub at line 17 of file BVHDataTestCase.hpp
auto volumes = grid.volumes
Definition at line 22 of file BVHDataTestCase.hpp.
View newest version in sPHENIX GitHub at line 22 of file BVHDataTestCase.hpp
Referenced by Acts::Python::addDetector(), Acts::Experimental::DetectorVolume::assignSurfaceCandidatesUpdator(), Acts::Experimental::detail::PortalHelper::attachDetectorVolumesUpdator(), Acts::Experimental::detail::PortalHelper::attachDetectorVolumeUpdators(), Acts::BoundarySurfaceT< volume_t >::attachVolumeArray(), BOOST_AUTO_TEST_CASE(), BOOST_DATA_TEST_CASE(), Acts::DD4hepVolumeBuilder::centralVolumes(), Acts::Experimental::DetectorVolume::checkContainment(), Acts::Experimental::DetectorBuilder::construct(), Acts::Experimental::DetectorVolumeBuilder::construct(), Acts::Experimental::CylindricalContainerBuilder::construct(), Acts::Experimental::DetectorVolumeFactory::construct(), Acts::constructContainerVolume(), Acts::Svg::DetectorConverter::convert(), Acts::MaterialMapJsonConverter::convertToHierarchy(), genfit::EventDisplay::drawEvent(), Acts::Experimental::DetectorVolume::exclusivelyInside(), Acts::Experimental::IndexedDetectorVolumeExtractor::extract(), Acts::Experimental::IndexedSubVolumesExtractor::extract(), Acts::DetectorJsonConverter::fromJson(), Acts::DetectorVolumeJsonConverter::fromJson(), Acts::CylinderVolumeHelper::interGlueTrackingVolume(), Acts::Experimental::DetectorVolume::makeShared(), Acts::DetectorJsonConverter::toJson(), Acts::DetectorJsonConverter::toJsonDetray(), Acts::CuboidVolumeBuilder::trackingVolume(), Acts::TrackingVolumeArrayCreator::trackingVolumeArray(), Acts::Experimental::RootVolumeFinder::update(), Acts::Experimental::TrialAndErrorVolumeFinder::update(), and Acts::MappingMaterialDecorator::volumeLoop().