Analysis Software: GlobalVertexv2 Class Reference
GlobalVertexv2 Class Reference
#include <coresoftware/blob/master/offline/packages/globalvertex/GlobalVertexv2.h>
Public Member Functions
GlobalVertexv2 ()
GlobalVertexv2 (const unsigned int id)
~GlobalVertexv2 () override=default
void identify (std::ostream &os=std::cout) const override
void Reset () override
Clear Event.
int isValid () const override
isValid returns non zero if object contains vailid data
PHObject * CloneMe () const override
Virtual copy constructor.
unsigned int get_id () const override
void set_id (unsigned int id) override
unsigned int get_beam_crossing () const override
void set_beam_crossing (unsigned int bco) override
float get_t () const override
float get_t_err () const override
float get_x () const override
float get_y () const override
float get_z () const override
float get_chisq () const override
unsigned int get_ndof () const override
float get_position (unsigned int coor) const override
float get_error (unsigned int i, unsigned int j) const override
bool empty_vtxs () const override
size_t size_vtxs () const override
size_t count_vtxs (GlobalVertex::VTXTYPE type) const override
void clear_vtxs () override
void insert_vtx (GlobalVertex::VTXTYPE type, const Vertex *vertex) override
size_t erase_vtxs (GlobalVertex::VTXTYPE type) override
void erase_vtxs (GlobalVertex::VertexIter iter) override
GlobalVertex::ConstVertexIter begin_vertexes () const override
GlobalVertex::ConstVertexIter find_vertexes (GlobalVertex::VTXTYPE type) const override
GlobalVertex::ConstVertexIter end_vertexes () const override
GlobalVertex::VertexIter begin_vertexes () override
GlobalVertex::VertexIter find_vertexes (GlobalVertex::VTXTYPE type) override
GlobalVertex::VertexIter end_vertexes () override
Public Member Functions inherited from GlobalVertex
~GlobalVertex () override
virtual void set_t (float)
virtual void set_t_err (float)
virtual void set_x (float)
virtual void set_y (float)
virtual void set_z (float)
virtual void set_chisq (float)
virtual void set_ndof (unsigned int)
virtual void set_position (unsigned int, float)
virtual void set_error (unsigned int, unsigned int, float)
virtual bool empty_vtxids () const
virtual size_t size_vtxids () const
virtual size_t count_vtxids (VTXTYPE) const
virtual void clear_vtxids ()
virtual void insert_vtxids (VTXTYPE, unsigned int)
virtual size_t erase_vtxids (VTXTYPE)
virtual void erase_vtxids (VtxIter)
virtual void erase_vtxids (VtxIter, VtxIter)
virtual ConstVtxIter begin_vtxids () const
virtual ConstVtxIter find_vtxids (VTXTYPE type) const
virtual ConstVtxIter end_vtxids () const
virtual VtxIter begin_vtxids ()
virtual VtxIter find_vtxids (VTXTYPE type)
virtual VtxIter end_vtxids ()
Public Member Functions inherited from PHObject
PHObject ()
ctor
~PHObject () override
dtor
virtual PHObject * clone () const final
PHObject * Clone (const char *newname="") const final
void Copy (TObject &object) const final
virtual int Integrate () const
virtual int Integrate (PHObject *)
virtual void CopyFrom (const PHObject *obj)
Private Member Functions
ClassDefOverride (GlobalVertexv2, 2)
Private Attributes
unsigned int _id
unsigned int _bco
std::map
< GlobalVertex::VTXTYPE,
VertexVector > _vtxs
Additional Inherited Members
Public Types inherited from GlobalVertex
enum VTXTYPE {
UNDEFINED = 0, TRUTH = 100, SMEARED = 200, MBD = 300,
SVTX = 400, SVTX_MBD = 500
}
typedef std::vector< const
Vertex * > VertexVector
typedef std::map
< GlobalVertex::VTXTYPE,
VertexVector >::const_iterator ConstVertexIter
typedef std::map
< GlobalVertex::VTXTYPE,
VertexVector >::iterator VertexIter
typedef std::map
< GlobalVertex::VTXTYPE,
unsigned int >::const_iterator ConstVtxIter
typedef std::map
< GlobalVertex::VTXTYPE,
unsigned int >::iterator VtxIter
Protected Member Functions inherited from GlobalVertex
GlobalVertex ()
Detailed Description
Definition at line 16 of file GlobalVertexv2.h.
View newest version in sPHENIX GitHub at line 16 of file GlobalVertexv2.h
Constructor & Destructor Documentation
GlobalVertexv2::GlobalVertexv2 ()
Definition at line 5 of file GlobalVertexv2.cc.
View newest version in sPHENIX GitHub at line 5 of file GlobalVertexv2.cc
Referenced by CloneMe(), and Reset().
GlobalVertexv2::GlobalVertexv2 (const unsigned int id)
Definition at line 11 of file GlobalVertexv2.cc.
View newest version in sPHENIX GitHub at line 11 of file GlobalVertexv2.cc
GlobalVertexv2::~GlobalVertexv2 () override default
Member Function Documentation
GlobalVertex::ConstVertexIter GlobalVertexv2::begin_vertexes () const inline override virtual
Reimplemented from GlobalVertex.
Definition at line 60 of file GlobalVertexv2.h.
View newest version in sPHENIX GitHub at line 60 of file GlobalVertexv2.h
References _vtxs.
Referenced by identify().
GlobalVertex::VertexIter GlobalVertexv2::begin_vertexes () inline override virtual
Reimplemented from GlobalVertex.
Definition at line 64 of file GlobalVertexv2.h.
View newest version in sPHENIX GitHub at line 64 of file GlobalVertexv2.h
References _vtxs.
GlobalVertexv2::ClassDefOverride (GlobalVertexv2 , 2) private
void GlobalVertexv2::clear_vtxs () inline override virtual
Reimplemented from GlobalVertex.
Definition at line 55 of file GlobalVertexv2.h.
View newest version in sPHENIX GitHub at line 55 of file GlobalVertexv2.h
References _vtxs.
PHObject* GlobalVertexv2::CloneMe () const inline override virtual
Virtual copy constructor.
Reimplemented from GlobalVertex.
Definition at line 28 of file GlobalVertexv2.h.
View newest version in sPHENIX GitHub at line 28 of file GlobalVertexv2.h
References GlobalVertexv2().
size_t GlobalVertexv2::count_vtxs (GlobalVertex::VTXTYPE type) const override virtual
Reimplemented from GlobalVertex.
Definition at line 61 of file GlobalVertexv2.cc.
View newest version in sPHENIX GitHub at line 61 of file GlobalVertexv2.cc
References _vtxs, and it.
bool GlobalVertexv2::empty_vtxs () const inline override virtual
Reimplemented from GlobalVertex.
Definition at line 51 of file GlobalVertexv2.h.
View newest version in sPHENIX GitHub at line 51 of file GlobalVertexv2.h
References _vtxs.
GlobalVertex::ConstVertexIter GlobalVertexv2::end_vertexes () const inline override virtual
Reimplemented from GlobalVertex.
Definition at line 62 of file GlobalVertexv2.h.
View newest version in sPHENIX GitHub at line 62 of file GlobalVertexv2.h
References _vtxs.
Referenced by identify().
GlobalVertex::VertexIter GlobalVertexv2::end_vertexes () inline override virtual
Reimplemented from GlobalVertex.
Definition at line 66 of file GlobalVertexv2.h.
View newest version in sPHENIX GitHub at line 66 of file GlobalVertexv2.h
References _vtxs.
size_t GlobalVertexv2::erase_vtxs (GlobalVertex::VTXTYPE type) inline override virtual
Reimplemented from GlobalVertex.
Definition at line 57 of file GlobalVertexv2.h.
View newest version in sPHENIX GitHub at line 57 of file GlobalVertexv2.h
References _vtxs.
void GlobalVertexv2::erase_vtxs (GlobalVertex::VertexIter iter) inline override virtual
Reimplemented from GlobalVertex.
Definition at line 58 of file GlobalVertexv2.h.
View newest version in sPHENIX GitHub at line 58 of file GlobalVertexv2.h
References _vtxs.
GlobalVertex::ConstVertexIter GlobalVertexv2::find_vertexes (GlobalVertex::VTXTYPE type) const inline override virtual
Reimplemented from GlobalVertex.
Definition at line 61 of file GlobalVertexv2.h.
View newest version in sPHENIX GitHub at line 61 of file GlobalVertexv2.h
References _vtxs.
GlobalVertex::VertexIter GlobalVertexv2::find_vertexes (GlobalVertex::VTXTYPE type) inline override virtual
Reimplemented from GlobalVertex.
Definition at line 65 of file GlobalVertexv2.h.
View newest version in sPHENIX GitHub at line 65 of file GlobalVertexv2.h
References _vtxs.
unsigned int GlobalVertexv2::get_beam_crossing () const inline override virtual
Reimplemented from GlobalVertex.
Definition at line 33 of file GlobalVertexv2.h.
View newest version in sPHENIX GitHub at line 33 of file GlobalVertexv2.h
References _bco.
float GlobalVertexv2::get_chisq () const override virtual
Reimplemented from GlobalVertex.
Definition at line 134 of file GlobalVertexv2.cc.
View newest version in sPHENIX GitHub at line 134 of file GlobalVertexv2.cc
References _vtxs.
float GlobalVertexv2::get_error (unsigned int i, unsigned int j) const override virtual
Reimplemented from GlobalVertex.
Definition at line 180 of file GlobalVertexv2.cc.
View newest version in sPHENIX GitHub at line 180 of file GlobalVertexv2.cc
References _vtxs, check_license::err(), and Enable::MBD.
unsigned int GlobalVertexv2::get_id () const inline override virtual
Reimplemented from GlobalVertex.
Definition at line 30 of file GlobalVertexv2.h.
View newest version in sPHENIX GitHub at line 30 of file GlobalVertexv2.h
References _id.
unsigned int GlobalVertexv2::get_ndof () const override virtual
Reimplemented from GlobalVertex.
Definition at line 157 of file GlobalVertexv2.cc.
View newest version in sPHENIX GitHub at line 157 of file GlobalVertexv2.cc
References _vtxs.
float GlobalVertexv2::get_position (unsigned int coor) const override virtual
Reimplemented from GlobalVertex.
Definition at line 106 of file GlobalVertexv2.cc.
View newest version in sPHENIX GitHub at line 106 of file GlobalVertexv2.cc
References _vtxs, Enable::MBD, and Acts::Test::pos.
Referenced by get_x(), get_y(), and get_z().
float GlobalVertexv2::get_t () const override virtual
Reimplemented from GlobalVertex.
Definition at line 72 of file GlobalVertexv2.cc.
View newest version in sPHENIX GitHub at line 72 of file GlobalVertexv2.cc
References _vtxs, it, and Enable::MBD.
float GlobalVertexv2::get_t_err () const override virtual
Reimplemented from GlobalVertex.
Definition at line 83 of file GlobalVertexv2.cc.
View newest version in sPHENIX GitHub at line 83 of file GlobalVertexv2.cc
References _vtxs, it, and Enable::MBD.
float GlobalVertexv2::get_x () const override virtual
Reimplemented from GlobalVertex.
Definition at line 93 of file GlobalVertexv2.cc.
View newest version in sPHENIX GitHub at line 93 of file GlobalVertexv2.cc
References get_position().
float GlobalVertexv2::get_y () const override virtual
Reimplemented from GlobalVertex.
Definition at line 97 of file GlobalVertexv2.cc.
View newest version in sPHENIX GitHub at line 97 of file GlobalVertexv2.cc
References get_position().
float GlobalVertexv2::get_z () const override virtual
Reimplemented from GlobalVertex.
Definition at line 101 of file GlobalVertexv2.cc.
View newest version in sPHENIX GitHub at line 101 of file GlobalVertexv2.cc
References get_position().
void GlobalVertexv2::identify (std::ostream & os = std::cout) const override virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from GlobalVertex.
Definition at line 17 of file GlobalVertexv2.cc.
View newest version in sPHENIX GitHub at line 17 of file GlobalVertexv2.cc
References begin_vertexes(), and end_vertexes().
void GlobalVertexv2::insert_vtx (GlobalVertex::VTXTYPE type, const Vertex * vertex) override virtual
Reimplemented from GlobalVertex.
Definition at line 46 of file GlobalVertexv2.cc.
View newest version in sPHENIX GitHub at line 46 of file GlobalVertexv2.cc
References _vtxs, and it.
int GlobalVertexv2::isValid () const override virtual
isValid returns non zero if object contains vailid data
Reimplemented from GlobalVertex.
Definition at line 37 of file GlobalVertexv2.cc.
View newest version in sPHENIX GitHub at line 37 of file GlobalVertexv2.cc
References _vtxs.
void GlobalVertexv2::Reset () inline override virtual
Clear Event.
Reimplemented from PHObject.
Definition at line 26 of file GlobalVertexv2.h.
View newest version in sPHENIX GitHub at line 26 of file GlobalVertexv2.h
References GlobalVertexv2().
void GlobalVertexv2::set_beam_crossing (unsigned int bco) inline override virtual
Reimplemented from GlobalVertex.
Definition at line 34 of file GlobalVertexv2.h.
View newest version in sPHENIX GitHub at line 34 of file GlobalVertexv2.h
References _bco.
void GlobalVertexv2::set_id (unsigned int id) inline override virtual
Reimplemented from GlobalVertex.
Definition at line 31 of file GlobalVertexv2.h.
View newest version in sPHENIX GitHub at line 31 of file GlobalVertexv2.h
References _id, and train_ambiguity_solver::id.
size_t GlobalVertexv2::size_vtxs () const inline override virtual
Reimplemented from GlobalVertex.
Definition at line 52 of file GlobalVertexv2.h.
View newest version in sPHENIX GitHub at line 52 of file GlobalVertexv2.h
References _vtxs.
Member Data Documentation
unsigned int GlobalVertexv2::_bco private
Definition at line 70 of file GlobalVertexv2.h.
View newest version in sPHENIX GitHub at line 70 of file GlobalVertexv2.h
Referenced by get_beam_crossing(), and set_beam_crossing().
unsigned int GlobalVertexv2::_id private
Definition at line 69 of file GlobalVertexv2.h.
View newest version in sPHENIX GitHub at line 69 of file GlobalVertexv2.h
Referenced by get_id(), and set_id().
std::map<GlobalVertex::VTXTYPE, VertexVector> GlobalVertexv2::_vtxs private
Definition at line 71 of file GlobalVertexv2.h.
View newest version in sPHENIX GitHub at line 71 of file GlobalVertexv2.h
Referenced by begin_vertexes(), clear_vtxs(), count_vtxs(), empty_vtxs(), end_vertexes(), erase_vtxs(), find_vertexes(), get_chisq(), get_error(), get_ndof(), get_position(), get_t(), get_t_err(), insert_vtx(), isValid(), and size_vtxs().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/globalvertex/GlobalVertexv2.h
coresoftware/blob/master/offline/packages/globalvertex/GlobalVertexv2.cc