Analysis Software: macros/blob/master/common/G4_Intt.C File Reference
G4_Intt.C File Reference
#include <GlobalVariables.C>
#include <QA.C>
#include <G4_Mvtx.C>
#include <g4intt/PHG4InttDefs.h>
#include <g4intt/PHG4InttDigitizer.h>
#include <g4intt/PHG4InttHitReco.h>
#include <g4intt/PHG4InttSubsystem.h>
#include <g4main/PHG4Reco.h>
#include <intt/InttClusterizer.h>
#include <qa_modules/QAG4SimulationIntt.h>
#include <fun4all/Fun4AllServer.h>
#include <cmath>
#include <vector>
Namespaces
namespace Enable
namespace G4INTT
Macros
#define MACRO_G4INTT_C
Enumerations
enum G4INTT::enu_InttDeadMapType { G4INTT::kInttNoDeadMap = 0, G4INTT::kIntt4PercentDeadMap = 4, G4INTT::kIntt8PercentDeadMap = 8 }
Functions
void InttInit ()
double Intt (PHG4Reco *g4Reco, double radius, const int absorberactive=0)
void Intt_Cells ()
void Intt_Clustering ()
void Intt_QA ()
Variables
bool Enable::INTT = false
bool Enable::INTT_OVERLAPCHECK = false
bool Enable::INTT_CELL = false
bool Enable::INTT_CLUSTER = false
bool Enable::INTT_QA = false
int Enable::INTT_VERBOSITY = 0
int G4INTT::n_intt_layer = 4
double G4INTT::intt_radius_max = 140.
int G4INTT::laddertype [4]
int G4INTT::nladder [4] = {12, 12, 16, 16}
double G4INTT::sensor_radius [4] = {7.188 - 36e-4, 7.732 - 36e-4, 9.680 - 36e-4, 10.262 - 36e-4}
double G4INTT::offsetphi [4] = {0.0, 0.5 * 360.0 / nladder[1], 0.0, 0.5 * 360.0 / nladder[3]}
enu_InttDeadMapType G4INTT::InttDeadMapOption = kInttNoDeadMap
Macro Definition Documentation
#define MACRO_G4INTT_C
Definition at line 2 of file G4_Intt.C.
View newest version in sPHENIX GitHub at line 2 of file G4_Intt.C
Function Documentation
double Intt (PHG4Reco * g4Reco, double radius, const int absorberactive = 0)
Definition at line 74 of file G4_Intt.C.
View newest version in sPHENIX GitHub at line 74 of file G4_Intt.C
References i, Enable::INTT_OVERLAPCHECK, G4INTT::intt_radius_max, Enable::INTT_VERBOSITY, G4INTT::laddertype, max, G4INTT::n_intt_layer, G4MVTX::n_maps_layer, G4INTT::nladder, G4INTT::offsetphi, Enable::OVERLAPCHECK, PHG4DetectorGroupSubsystem::OverlapCheck(), PHG4Reco::registerSubsystem(), G4INTT::sensor_radius, PHG4DetectorGroupSubsystem::set_double_param(), PHG4DetectorGroupSubsystem::set_int_param(), PHG4DetectorGroupSubsystem::SetActive(), verbosity, Enable::VERBOSITY, and Fun4AllBase::Verbosity().
Referenced by G4Setup().
void Intt_Cells ()
Definition at line 121 of file G4_Intt.C.
View newest version in sPHENIX GitHub at line 121 of file G4_Intt.C
References i, Fun4AllServer::instance(), Enable::INTT_VERBOSITY, max, G4INTT::n_intt_layer, G4MVTX::n_maps_layer, Fun4AllServer::registerSubsystem(), PHG4InttDigitizer::set_adc_scale(), verbosity, Enable::VERBOSITY, and Fun4AllBase::Verbosity().
Referenced by Fun4All_AnaTutorial_sPHENIX(), Fun4All_AnaTutorial_sPHENIX_Jets(), and Fun4All_G4_sPHENIX().
void Intt_Clustering ()
Definition at line 178 of file G4_Intt.C.
View newest version in sPHENIX GitHub at line 178 of file G4_Intt.C
References i, Fun4AllServer::instance(), Enable::INTT_VERBOSITY, G4INTT::laddertype, max, G4INTT::n_intt_layer, G4MVTX::n_maps_layer, Fun4AllServer::registerSubsystem(), PHG4InttDefs::SEGMENTATION_PHI, InttClusterizer::set_z_clustering(), verbosity, Enable::VERBOSITY, and Fun4AllBase::Verbosity().
Referenced by Fun4All_AnaTutorial_sPHENIX(), Fun4All_AnaTutorial_sPHENIX_Jets(), and Fun4All_G4_sPHENIX().
void Intt_QA ()
Definition at line 198 of file G4_Intt.C.
View newest version in sPHENIX GitHub at line 198 of file G4_Intt.C
References Fun4AllServer::instance(), Enable::INTT_VERBOSITY, max, Enable::QA_VERBOSITY, Fun4AllServer::registerSubsystem(), verbosity, and Fun4AllBase::Verbosity().
Referenced by Fun4All_AnaTutorial_sPHENIX(), Fun4All_AnaTutorial_sPHENIX_Jets(), and Fun4All_G4_sPHENIX().
void InttInit ()
Definition at line 61 of file G4_Intt.C.
View newest version in sPHENIX GitHub at line 61 of file G4_Intt.C
References max, BlackHoleGeometry::max_radius, BlackHoleGeometry::max_z, min, BlackHoleGeometry::min_z, Enable::MVTX, and G4MVTX::n_maps_layer.
Referenced by G4Init().