Analysis Software: InttDefs Namespace Reference
InttDefs Namespace Reference
Utility functions for INTT.
Functions
static const unsigned int
kBitShiftTimeBucketIdOffset __attribute__ ((unused))=0 = 10
uint8_t getLadderZId (TrkrDefs::hitsetkey key)
Get the ladder id from hitsetkey.
uint8_t getLadderZId (TrkrDefs::cluskey key)
Get the ladder id from cluskey.
uint8_t getLadderPhiId (TrkrDefs::hitsetkey key)
Get the sensor id from hitsetkey.
uint8_t getLadderPhiId (TrkrDefs::cluskey key)
Get the sensor id from cluskey.
int getTimeBucketId (TrkrDefs::hitsetkey key)
Generate a hitkey from a strip id.
int getTimeBucketId (TrkrDefs::cluskey key)
Get the time bucket id from the hitsetkey.
uint16_t getCol (TrkrDefs::hitkey key)
Get the time bucket id from the cluskey.
uint16_t getRow (TrkrDefs::hitkey key)
Get the row index from hitkey.
TrkrDefs::hitkey genHitKey (const uint16_t col, const uint16_t row)
TrkrDefs::hitsetkey genHitSetKey (const uint8_t lyr, const uint8_t ladder_z_index, const uint8_t ladder_phi_index, const int time_bucket)
Generate a hitsetkey for the intt.
TrkrDefs::cluskey genClusKey (const uint8_t lyr, const uint8_t ladder_z_index, const uint8_t ladder_phi_index, const int crossing, const uint32_t clusid)
Generate a cluster key from indeces.
TrkrDefs::hitsetkey resetCrossingHitSetKey (const TrkrDefs::hitsetkey hitsetkey)
Zero the crossing bits in a copy of the hitsetkey.
Detailed Description
Utility functions for INTT.
Contains the functions for manipulating the various keys used by the intt for hits, hit sets, and clusters
Function Documentation
static const unsigned int kBitShiftRow InttDefs::__attribute__ ((unused)) = 10 static pure virtual
TrkrDefs::cluskey InttDefs::genClusKey (const uint8_t lyr, const uint8_t ladder_z_index, const uint8_t ladder_phi_index, const int crossing, const uint32_t clusid)
Generate a cluster key from indeces.
Parameters
[in] lyr Layer index
[in] ladder_z_index z index of sensor in ladder
[in] ladder_phi_ndex phi index of ladder in layer
[in] crossing - bunch crossing
[in] clusid Cluster id
[out] cluskey
Definition at line 111 of file InttDefs.cc.
View newest version in sPHENIX GitHub at line 111 of file InttDefs.cc
References TrkrDefs::genClusKey(), and MicromegasDefs::genHitSetKey().
Referenced by PHTruthClustering::all_truth_clusters(), and SvtxTruthEval::all_truth_clusters().
TrkrDefs::hitkey InttDefs::genHitKey (const uint16_t col, const uint16_t row)
Definition at line 81 of file InttDefs.cc.
View newest version in sPHENIX GitHub at line 81 of file InttDefs.cc
References Acts::Test::tmp().
Referenced by InttCombinedRawDataDecoder::process_event(), InttRawDataDecoder::process_event(), and PHG4InttHitReco::process_event().
TrkrDefs::hitsetkey InttDefs::genHitSetKey (const uint8_t lyr, const uint8_t ladder_z_index, const uint8_t ladder_phi_index, const int time_bucket)
Generate a hitsetkey for the intt.
Parameters
[in] lyr Layer index
[in] ladder Ladder index
[in] sensor Sensor index
[out] hitsetkey Generate a hitsetkey for the intt. The tracker id is known implicitly and used in the function.
Definition at line 90 of file InttDefs.cc.
View newest version in sPHENIX GitHub at line 90 of file InttDefs.cc
References TrkrDefs::genHitSetKey(), TrkrDefs::inttId, and Acts::Test::tmp().
Referenced by MakeActsGeometry::getInttHitSetKeyFromCoords(), MakeActsGeometry::getInttKeyFromNode(), InttCombinedRawDataDecoder::process_event(), InttRawDataDecoder::process_event(), and PHG4InttHitReco::process_event().
uint16_t InttDefs::getCol (TrkrDefs::hitkey key)
Get the time bucket id from the cluskey.
Parameters
[in] cluskey
[out] time bucket id Get the column index from hitkey
[in] hitkey
[out] column index
Definition at line 67 of file InttDefs.cc.
View newest version in sPHENIX GitHub at line 67 of file InttDefs.cc
References Acts::Test::tmp().
Referenced by PHG4InttHitReco::cluster_truthhits(), InttClusterizer::ClusterLadderCells(), PHG4InttDigitizer::DigitizeLadderCells(), QAG4SimulationIntt::evaluate_clusters(), TrackResiduals::fillHitTree(), dNdEtaINTT::GetTrkrHitInfo(), InttClusterizer::ladder_are_adjacent(), mvtx::ChipPixelData::print(), and TpcRawWriter::process_event().
uint8_t InttDefs::getLadderPhiId (TrkrDefs::hitsetkey key)
Get the sensor id from hitsetkey.
Parameters
[in] hitsetkey
[out] sensor id
Definition at line 28 of file InttDefs.cc.
View newest version in sPHENIX GitHub at line 28 of file InttDefs.cc
References Acts::Test::tmp().
Referenced by PHG4InttDigitizer::DigitizeLadderCells(), TrackResiduals::fillClusterTree(), KFParticle_truthAndDetTools::fillDetectorBranch(), TrackResiduals::fillHitTree(), getLadderPhiId(), dNdEtaINTT::GetRecoClusterInfo(), dNdEtaINTT::GetTrkrHitInfo(), SVReco::MakeGenFitTrack(), MakeActsGeometry::makeInttMapPairs(), and HelicalFitter::process_event().
uint8_t InttDefs::getLadderPhiId (TrkrDefs::cluskey key)
Get the sensor id from cluskey.
Parameters
[in] cluskey
[out] sensor id
Definition at line 39 of file InttDefs.cc.
View newest version in sPHENIX GitHub at line 39 of file InttDefs.cc
References getLadderPhiId(), and Acts::Test::tmp().
uint8_t InttDefs::getLadderZId (TrkrDefs::hitsetkey key)
Get the ladder id from hitsetkey.
Parameters
[in] hitsetkey
[out] ladder id
Definition at line 10 of file InttDefs.cc.
View newest version in sPHENIX GitHub at line 10 of file InttDefs.cc
References Acts::Test::tmp().
Referenced by PHG4InttHitReco::cluster_truthhits(), InttClusterizer::ClusterLadderCells(), InttClusterizer::ClusterLadderCellsRaw(), PHG4InttDigitizer::DigitizeLadderCells(), TrackResiduals::fillClusterTree(), KFParticle_truthAndDetTools::fillDetectorBranch(), TrackResiduals::fillHitTree(), getLadderZId(), dNdEtaINTT::GetRecoClusterInfo(), dNdEtaINTT::GetTrkrHitInfo(), SVReco::MakeGenFitTrack(), MakeActsGeometry::makeInttMapPairs(), and HelicalFitter::process_event().
uint8_t InttDefs::getLadderZId (TrkrDefs::cluskey key)
Get the ladder id from cluskey.
Parameters
[in] cluskey
[out] ladder id
Definition at line 21 of file InttDefs.cc.
View newest version in sPHENIX GitHub at line 21 of file InttDefs.cc
References getLadderZId(), and Acts::Test::tmp().
uint16_t InttDefs::getRow (TrkrDefs::hitkey key)
Get the row index from hitkey.
Parameters
[in] hitkey
[out] row index
Definition at line 74 of file InttDefs.cc.
View newest version in sPHENIX GitHub at line 74 of file InttDefs.cc
References Acts::Test::tmp().
Referenced by PHG4InttHitReco::cluster_truthhits(), InttClusterizer::ClusterLadderCells(), PHG4InttDigitizer::DigitizeLadderCells(), QAG4SimulationIntt::evaluate_clusters(), TrackResiduals::fillHitTree(), dNdEtaINTT::GetTrkrHitInfo(), InttClusterizer::ladder_are_adjacent(), mvtx::ChipPixelData::print(), and TpcRawWriter::process_event().
int InttDefs::getTimeBucketId (TrkrDefs::hitsetkey key)
Generate a hitkey from a strip id.
Parameters
[in] strip Strip id
[out] hitkey
Definition at line 46 of file InttDefs.cc.
View newest version in sPHENIX GitHub at line 46 of file InttDefs.cc
References Acts::Test::tmp().
Referenced by InttClusterizer::ClusterLadderCells(), InttClusterizer::ClusterLadderCellsRaw(), TrackResiduals::fillClusterTree(), TrackResiduals::fillHitTree(), dNdEtaINTT::GetRecoClusterInfo(), and getTimeBucketId().
int InttDefs::getTimeBucketId (TrkrDefs::cluskey key)
Get the time bucket id from the hitsetkey.
Parameters
[in] hitsetkey
[out] time bucket id
Definition at line 60 of file InttDefs.cc.
View newest version in sPHENIX GitHub at line 60 of file InttDefs.cc
References getTimeBucketId(), and Acts::Test::tmp().
TrkrDefs::hitsetkey InttDefs::resetCrossingHitSetKey (const TrkrDefs::hitsetkey hitsetkey)
Zero the crossing bits in a copy of the hitsetkey.
Parameters
[in] hitsetkey
[out] hitsetkey
Definition at line 118 of file InttDefs.cc.
View newest version in sPHENIX GitHub at line 118 of file InttDefs.cc
References Acts::Test::tmp().
Referenced by ActsSurfaceMaps::getSiliconSurface().