Analysis Software: analysis/blob/master/Prototype2/hcalLab/evDisplay.C File Reference
evDisplay.C File Reference
#include <iomanip>
#include <algorithm>
#include <numeric>
#include <cmath>
#include <ctime>
#include <iostream>
#include <fstream>
#include <cstdlib>
#include <stdint.h>
#include <fileEventiterator.h>
#include <Event.h>
#include <packet.h>
#include <packet_hbd_fpgashort.h>
#include <TROOT.h>
#include <TF1.h>
#include <TH1.h>
#include <TH1F.h>
#include <TCanvas.h>
#include <TGraph.h>
#include <TString.h>
#include <TApplication.h>
#include <TStyle.h>
#include <TSystem.h>
#include <TGClient.h>
#include <TGWindow.h>
Functions
int nevents (0)
int channel (0)
void usage ()
Double_t signal (0.)
Double_t pedestal (0.)
Double_t signalShape (Double_t *x, Double_t *par)
void init ()
void fitShape (int chan)
int main (int argc, char **argv)
Variables
const int NCH = 8
const int NSAMPLES = 24
const int RISETIME = 4
const int FALLTIME = 5
const int feech [] = { 115, 119, 123, 127, 113, 117, 121, 125 }
TGraph * gpulse [NCH]
Double_t shapeD [NCH][NSAMPLES]
TF1 * shapes [NCH]
TCanvas * ev_display
TCanvas * fitFunc
TH1 * fittime
TH1 * fitmax
TH1 * fitwidth
TH1 * fitintegral
TH1 * pedval
TH1 * pedslope
TH1 ** fitPar [6]
Double_t PEDESTAL = 2048
Double_t par0 [] = { 0., 0., 4., 0., 0., 0.}
Double_t par0Max [] = { 1000., NSAMPLES-FALLTIME+1., 5., 1., 2150., 0.2}
Double_t par0Min [] = { 1., RISETIME-1, 3., 2., 1950.,-0.2}
Function Documentation
int channel (0)
Referenced by oncsSub_idsrs_v01::add_report(), fullRunningMean::addChannel(), pseudoRunningMean::addChannel(), myAnalysis::analyze(), caen_correction::caen_corrected(), converttohepmc(), groot::CreateZigzags(), ActsFatras::Geant4Decay::decayParticle(), oncsSub_idcaenv792::decode(), oncsSub_idtpcfeev1::decode(), oncsSub_idsrs_v01::decode(), TowerInfoDefs::decode_epd(), TowerInfoDefs::decode_mbd(), decode_pbsc_dcm0(), decode_tec_dcm0(), display(), TpotMonDraw::Draw(), oncsSub_iddreamv0::dump(), TowerInfoDefs::encode_epd(), TowerInfoDefs::encode_mbd(), fitShape(), G4Pythia6Decayer::ForceHadronicD(), G4Pythia6Decayer::ForceOmega(), G4Pythia6Decayer::ForceParticleDecay(), genevent(), TowerInfoDefs::get_epd_phibin(), TowerInfoDefs::get_epd_rbin(), TowerJetInput::get_input(), runningMean::getReference(), groot::groot(), init(), initpythia(), oncsSub_idtpcfeev3::iValue(), Packet_id4scaler::iValue(), jewel(), main(), BbcCheck::process_emcal(), G4RawTowerTTree::process_event(), G4ScintillatorTowerTTree::process_event(), RawClusterBuilderTemplate::process_event(), Emcal_Tower_Masking::process_event(), GenericUnpackPRDF::process_event(), CemcMon::process_event(), TemplateCreation::process_event(), TpotMon::process_event(), TpcMon::process_event(), CaloTowerBuilder::process_event(), CaloTowerCalib::process_event(), CaloTowerStatus::process_event(), RawTowerCalibration::process_event(), LEDTowerBuilder::process_event(), G4TowerNtuple::process_event(), ClusterIso::process_event(), SubtractTowers::process_event(), TpcCombinedRawDataUnpacker::process_event(), RetowerCEMC::process_event(), MicromegasRawDataDecoder::process_event(), DetermineTowerBackground::process_event(), MicromegasCombinedDataDecoder::process_event(), MicromegasRawDataCalibration::process_event(), caloTowerEmbed::process_event(), CaloTriggerSim::process_event(), tpc_hits::process_event(), TPCFEETestRecov1::process_event(), TpcRawDataDecoder::process_event(), TpcPrototypeUnpacker::process_event(), JetNconstituents::process_event(), JetBkgdSub::process_event(), LiteCaloEval::process_event(), JetValidation::process_event(), EMJetVal::process_event(), sPHAnalysis_calo::process_event_data(), BbcCheck::process_ihcal(), DumpTowerInfoContainer::process_Node(), BbcCheck::process_ohcal(), HCalCalibTree::process_towers(), CaloAna::process_towers(), CaloValid::process_towers(), pi0EtaByEta::process_towers(), MicromegasCalibrationData::read(), CDBTTree::SetDoubleValue(), CDBTTree::SetFloatValue(), CDBTTree::SetIntValue(), runningMean::setRefChannel(), CDBTTree::SetUInt64Value(), test_hcal(), oncsSub_idtpcfeev2::tpc_decode(), and MicromegasCalibrationData::write().
void fitShape (int chan)
Definition at line 94 of file evDisplay.C.
View newest version in sPHENIX GitHub at line 94 of file evDisplay.C
References channel(), ev_display, feech, gpulse, nevents(), NSAMPLES, par0, par0Max, par0Min, PEDESTAL, RISETIME, SetParLimits(), shapeD, shapes, and signalShape().
Referenced by G__hcalUtilDict__0_1609(), hcal::GetNextEvent(), and main().
void init ()
Definition at line 81 of file evDisplay.C.
View newest version in sPHENIX GitHub at line 81 of file evDisplay.C
References fitintegral, fitmax, fittime, fitwidth, pedslope, and pedval.
Referenced by jewel(), pyhistfe(), and pymsin().
int main (int argc, char ** argv)
Definition at line 144 of file evDisplay.C.
View newest version in sPHENIX GitHub at line 144 of file evDisplay.C
References channel(), ev_display, feech, file, fitShape(), Event::getEvtSequence(), Event::getEvtType(), Eventiterator::getNextEvent(), Event::getPacket(), gpulse, it, Packet_hbd_fpgashort::iValue(), perf_headwind::name, NCH, nevents(), NSAMPLES, Packet_hbd_fpgashort::setNumSamples(), shapeD, utils::status, title, and usage().
int nevents (0)
Referenced by ana_starlight(), analysis(), myAnalysis::analyze(), hcal::collect(), create_pythia_dummy(), hcal::Display(), BbcMonDraw::Draw(), dst_simple_towerslope_runmacro(), BbcCheck::End(), event_topology_reco(), hcal::evLoop(), SingleZdcInput::FillPool(), SinglePrdfInput::FillPool(), fitShape(), Fun4All_Calo(), Fun4All_CaloProduction(), generate_hepmc_bjet(), hcal::GetNextEvent(), likelihood_topology(), main(), open_file(), trento::Output::Output(), pprocess(), pstart(), Fun4AllPrdfInputManager::PushBackEvents(), Fun4AllHepMCInputManager::PushBackEvents(), quarkonia_reconstruction_embedded(), read_LEDs(), Fun4AllHepMCPileupInputManager::run(), Fun4AllDummyInputManager::run(), OnlMonServer::run_empty(), runCCPi0Loop(), RunGenFitTrackProp(), runLCELoop(), Fun4AllHepMCPileupInputManager::SkipForThisManager(), TEST_CASE(), towerslope_dst_runner(), tsdst_plus_tsfit(), and wholeIter_Pi0EtaByEta().
Double_t pedestal (0.)
Referenced by CaloTemplateFit::calo_processing_perchnl(), CaloTemplateFit::calo_processing_singlethread(), CaloWaveformFitting::calo_processing_templatefit(), MicromegasRawDataCalibration::End(), hcal::fitShape(), HcalMon::process_event(), TemplateCreation::process_event(), TpotMon::process_event(), TpcMon::process_event(), MicromegasClusterizer::process_event(), MicromegasRawDataDecoder::process_event(), MicromegasCombinedDataDecoder::process_event(), MicromegasCombinedDataEvaluation::process_event(), MicromegasRawDataEvaluation::process_event(), TpcRawDataDecoder::process_event(), MicromegasCalibrationData::read(), TPCFEETestRecov1::roughZeroSuppression(), TpcPrototypeUnpacker::roughZeroSuppression(), PROTOTYPE4_FEM::SampleFit_PeakSample(), PROTOTYPE4_FEM::SampleFit_PowerLawDoubleExp(), TpcPrototypeDefs::FEEv2::SampleFit_PowerLawDoubleExp(), TPCDaqDefs::FEEv1::SampleFit_PowerLawDoubleExp(), PROTOTYPE2_FEM::SampleFit_PowerLawExp(), PROTOTYPE3_FEM::SampleFit_PowerLawExp(), PROTOTYPE4_FEM::SampleFit_PowerLawExp(), TowerInfov2::set_pedestal(), hcal::SignalShape(), signalShape(), PROTOTYPE4_FEM::SignalShape_PowerLawDoubleExp(), TpcPrototypeDefs::FEEv2::SignalShape_PowerLawDoubleExp(), TPCDaqDefs::FEEv1::SignalShape_PowerLawDoubleExp(), PROTOTYPE2_FEM::SignalShape_PowerLawExp(), PROTOTYPE3_FEM::SignalShape_PowerLawExp(), PROTOTYPE4_FEM::SignalShape_PowerLawExp(), TpcPrototypeDefs::FEEv2::SignalShape_PowerLawExp(), TPCDaqDefs::FEEv1::SignalShape_PowerLawExp(), hcal::SignalShapeNegative(), RawTowerDigitizer::simple_photon_digitization(), TPC_Channel_QA_Backup(), and MicromegasCalibrationData::write().
Double_t signal (0.)
Referenced by ExtractRejCurve(), Jetscape::Hadronization::GetHadrons(), Jetscape::HadronizationManager::GetHadrons(), HcalMon::getSignal(), CemcMon::getSignal(), SepdMon::getSignal(), main(), mg_mgr_init(), mg_start_process(), plot_kshort(), SepdMon::process_event(), HcalMon::process_event(), ZdcMon::process_event(), PHG4CentralityReco::process_event(), PHG4MicromegasDigitizer::process_event(), redirecterrorshlle_(), reportBackground(), reportCuts(), hcal::SignalShape(), signalShape(), PROTOTYPE4_FEM::SignalShape_PowerLawDoubleExp(), TPCDaqDefs::FEEv1::SignalShape_PowerLawDoubleExp(), TpcPrototypeDefs::FEEv2::SignalShape_PowerLawDoubleExp(), PROTOTYPE3_FEM::SignalShape_PowerLawExp(), PROTOTYPE2_FEM::SignalShape_PowerLawExp(), PROTOTYPE4_FEM::SignalShape_PowerLawExp(), TpcPrototypeDefs::FEEv2::SignalShape_PowerLawExp(), TPCDaqDefs::FEEv1::SignalShape_PowerLawExp(), hcal::SignalShapeNegative(), and SimX::Simulator().
Double_t signalShape (Double_t * x, Double_t * par)
Definition at line 70 of file evDisplay.C.
View newest version in sPHENIX GitHub at line 70 of file evDisplay.C
Referenced by tileHelper::eventtilesummary::eventtilesummary(), fitShape(), hLabHelper::fitShape(), G__hcalUtilDict__0_1608(), hLabHelper::hLabHelper(), hLabHelper::initPRDFRun(), stack::stack(), and tower::tower().
void usage ()
Definition at line 58 of file evDisplay.C.
View newest version in sPHENIX GitHub at line 58 of file evDisplay.C
Referenced by G__hcalUtilDict__0_1604(), and main().
Variable Documentation
TCanvas* ev_display
Definition at line 49 of file evDisplay.C.
View newest version in sPHENIX GitHub at line 49 of file evDisplay.C
Referenced by fitShape(), and main().
const int FALLTIME = 5
Definition at line 40 of file evDisplay.C.
View newest version in sPHENIX GitHub at line 40 of file evDisplay.C
Referenced by hLabHelper::collect(), hLabHelper::fitShape(), tileHelper::fitTileSignal(), hLabHelper::getDetectorTiming(), and stack::getStackTime().
const int feech[] = { 115, 119, 123, 127, 113, 117, 121, 125 }
Definition at line 44 of file evDisplay.C.
View newest version in sPHENIX GitHub at line 44 of file evDisplay.C
Referenced by MbdCalib::Download_SampMax(), fitShape(), main(), OnlBbcEvent::setRawData(), and MbdEvent::SetRawData().
TCanvas * fitFunc
Definition at line 49 of file evDisplay.C.
View newest version in sPHENIX GitHub at line 49 of file evDisplay.C
Referenced by CaloAna::fitHistogram(), and pi0EtaByEta::fitHistogram().
TH1 * fitintegral
Definition at line 50 of file evDisplay.C.
View newest version in sPHENIX GitHub at line 50 of file evDisplay.C
Referenced by init().
TH1 * fitmax
Definition at line 50 of file evDisplay.C.
View newest version in sPHENIX GitHub at line 50 of file evDisplay.C
Referenced by init().
TH1** fitPar[6]
Definition at line 51 of file evDisplay.C.
View newest version in sPHENIX GitHub at line 51 of file evDisplay.C
TH1* fittime
Definition at line 50 of file evDisplay.C.
View newest version in sPHENIX GitHub at line 50 of file evDisplay.C
Referenced by init().
TH1 * fitwidth
Definition at line 50 of file evDisplay.C.
View newest version in sPHENIX GitHub at line 50 of file evDisplay.C
Referenced by init().
TGraph* gpulse[NCH]
Definition at line 46 of file evDisplay.C.
View newest version in sPHENIX GitHub at line 46 of file evDisplay.C
Referenced by hcal::Clear(), hcal::Display(), hcal::fitShape(), fitShape(), hcal::GetNextEvent(), hcal::Initialize(), main(), PROTOTYPE4_FEM::SampleFit_PowerLawDoubleExp(), TPCDaqDefs::FEEv1::SampleFit_PowerLawDoubleExp(), TpcPrototypeDefs::FEEv2::SampleFit_PowerLawDoubleExp(), PROTOTYPE2_FEM::SampleFit_PowerLawExp(), PROTOTYPE3_FEM::SampleFit_PowerLawExp(), and PROTOTYPE4_FEM::SampleFit_PowerLawExp().
const int NCH = 8
Definition at line 36 of file evDisplay.C.
View newest version in sPHENIX GitHub at line 36 of file evDisplay.C
Referenced by hcalLabTree::clean(), hcal::Clear(), hcal::Display(), hcal::evLoop(), hcal::GetNextEvent(), hcal::Initialize(), ll1setup(), main(), hcal::Save(), and sccalib().
const int NSAMPLES = 24
Definition at line 38 of file evDisplay.C.
View newest version in sPHENIX GitHub at line 38 of file evDisplay.C
Referenced by ac(), stack::clean(), hLabHelper::collect(), hLabHelper::evDisplay(), tileHelper::eventtilesummary::eventtilesummary(), hcalHelper::evLoop(), tileHelper::evLoop(), hcal::fitShape(), fitShape(), hLabHelper::fitShape(), tileHelper::fitTileSignal(), hLabHelper::getDetectorTiming(), hcal::GetNextEvent(), stack::getStackTime(), hcalHelper::hcalHelper(), hcalTree::hcalTree(), hLabHelper::hLabHelper(), hcal::Initialize(), hLabHelper::initPRDFRun(), main(), tileHelper::eventtilesummary::reset(), PROTOTYPE4_FEM::SampleFit_PeakSample(), PROTOTYPE4_FEM::SampleFit_PowerLawDoubleExp(), PROTOTYPE2_FEM::SampleFit_PowerLawExp(), PROTOTYPE3_FEM::SampleFit_PowerLawExp(), PROTOTYPE4_FEM::SampleFit_PowerLawExp(), stack::stack(), tileHelper::tileDisplay(), tileHelper::tileHelper(), tileHelper::tileTiming(), tileTree::tileTree(), tower::tower(), and tower::update().
Double_t par0[] = { 0., 0., 4., 0., 0., 0.}
Definition at line 65 of file evDisplay.C.
View newest version in sPHENIX GitHub at line 65 of file evDisplay.C
Referenced by Fe55::FitG(), fitShape(), hLabHelper::fitShape(), tileHelper::fitTileSignal(), fshapeACorr(), hLabHelper::getDetectorTiming(), stack::getStackTime(), Fe55::PlotXfit(), and Fe55::PlotXlines().
Double_t par0Max[] = { 1000., NSAMPLES-FALLTIME+1., 5., 1., 2150., 0.2}
Definition at line 66 of file evDisplay.C.
View newest version in sPHENIX GitHub at line 66 of file evDisplay.C
Referenced by hLabHelper::collect(), fitShape(), hLabHelper::fitShape(), tileHelper::fitTileSignal(), hLabHelper::getDetectorTiming(), stack::getStackTime(), and hLabHelper::initPRDFRun().
Double_t par0Min[] = { 1., RISETIME-1, 3., 2., 1950.,-0.2}
Definition at line 67 of file evDisplay.C.
View newest version in sPHENIX GitHub at line 67 of file evDisplay.C
Referenced by hLabHelper::collect(), fitShape(), hLabHelper::fitShape(), tileHelper::fitTileSignal(), hLabHelper::getDetectorTiming(), stack::getStackTime(), and hLabHelper::initPRDFRun().
Double_t PEDESTAL = 2048
Definition at line 64 of file evDisplay.C.
View newest version in sPHENIX GitHub at line 64 of file evDisplay.C
Referenced by hLabHelper::collect(), fitShape(), hLabHelper::fitShape(), tileHelper::fitTileSignal(), hLabHelper::getDetectorTiming(), and hcal::hcal().
TH1 * pedslope
Definition at line 50 of file evDisplay.C.
View newest version in sPHENIX GitHub at line 50 of file evDisplay.C
Referenced by init().
TH1 * pedval
Definition at line 50 of file evDisplay.C.
View newest version in sPHENIX GitHub at line 50 of file evDisplay.C
Referenced by init().
const int RISETIME = 4
Definition at line 39 of file evDisplay.C.
View newest version in sPHENIX GitHub at line 39 of file evDisplay.C
Referenced by hLabHelper::collect(), fitShape(), hLabHelper::fitShape(), tileHelper::fitTileSignal(), hLabHelper::getDetectorTiming(), and stack::getStackTime().
Double_t shapeD[NCH][NSAMPLES]
Definition at line 47 of file evDisplay.C.
View newest version in sPHENIX GitHub at line 47 of file evDisplay.C
Referenced by fitShape(), and main().
TF1* shapes[NCH]
Definition at line 48 of file evDisplay.C.
View newest version in sPHENIX GitHub at line 48 of file evDisplay.C
Referenced by fitShape().