Analysis Software: KFParticle_Tools Class Reference
KFParticle_Tools Class Reference
#include <coresoftware/blob/master/offline/packages/KFParticle_sPHENIX/KFParticle_Tools.h>
Public Member Functions
KFParticle_Tools ()
KFParticle constructor.
~KFParticle_Tools () override=default
KFParticle makeVertex (PHCompositeNode *topNode)
std::vector< KFParticle > makeAllPrimaryVertices (PHCompositeNode *topNode, const std::string &vertexMapName)
KFParticle makeParticle (PHCompositeNode *topNode)
Return a KFPTrack from track vector and covariance matrix. No mass or vertex constraints.
std::vector< KFParticle > makeAllDaughterParticles (PHCompositeNode *topNode)
int getTracksFromVertex (PHCompositeNode *topNode, const KFParticle &vertex, const std::string &vertexMapName)
bool isGoodTrack (const KFParticle &particle, const std::vector< KFParticle > &primaryVertices)
int calcMinIP (const KFParticle &track, const std::vector< KFParticle > &PVs, float &minimumIP, float &minimumIPchi2)
std::vector< int > findAllGoodTracks (std::vector< KFParticle > daughterParticles, const std::vector< KFParticle > &primaryVertices)
std::vector< std::vector< int > > findTwoProngs (std::vector< KFParticle > daughterParticles, std::vector< int > goodTrackIndex, int nTracks)
std::vector< std::vector< int > > findNProngs (std::vector< KFParticle > daughterParticles, const std::vector< int > &goodTrackIndex, std::vector< std::vector< int >> goodTracksThatMeet, int nRequiredTracks, unsigned int nProngs)
std::vector< std::vector< int > > appendTracksToIntermediates (KFParticle intermediateResonances[], std::vector< KFParticle > daughterParticles, const std::vector< int > &goodTrackIndex, int num_remaining_tracks)
float eventDIRA (const KFParticle &particle, const KFParticle &vertex)
Calculates the cosine of the angle betweent the flight direction and momentum.
float flightDistanceChi2 (const KFParticle &particle, const KFParticle &vertex)
std::tuple< KFParticle, bool > buildMother (KFParticle vDaughters[], std::string daughterOrder[], bool isIntermediate, int intermediateNumber, int nTracks, bool constrainMass, float required_vertexID)
void constrainToVertex (KFParticle &particle, bool &goodCandidate, KFParticle &vertex)
std::tuple< KFParticle, bool > getCombination (KFParticle vDaughters[], std::string daughterOrder[], KFParticle vertex, bool constrain_to_vertex, bool isIntermediate, int intermediateNumber, int nTracks, bool constrainMass, float required_vertexID)
std::vector< std::vector
< std::string > > findUniqueDaughterCombinations (int start, int end)
double calculateEllipsoidRadius (int posOrNeg, double sigma_ii, double sigma_jj, double sigma_ij)
float calculateEllipsoidVolume (const KFParticle &particle)
float calculateJT (const KFParticle &mother, const KFParticle &daughter)
bool isInRange (float min, float value, float max)
bool findParticle (const std::string &particle)
int getParticleID (const std::string &particle)
float getParticleMass (const std::string &particle)
float getParticleMass (const int PDGID)
void identify (const KFParticle &particle)
Protected Attributes
std::string m_mother_name_Tools
int m_num_intermediate_states = -1
std::vector< int > m_num_tracks_from_intermediate
std::vector< std::string > m_daughter_name
std::vector< int > m_daughter_charge
int m_num_tracks = -1
bool m_has_intermediates
std::vector< std::string > m_intermediate_name
std::vector< int > m_intermediate_charge
std::vector< std::pair< float,
float > > m_intermediate_mass_range
std::vector< float > m_intermediate_min_pt
std::vector< float > m_intermediate_min_dira
std::vector< float > m_intermediate_min_fdchi2
std::vector< float > m_intermediate_min_ip
std::vector< float > m_intermediate_max_ip
std::vector< float > m_intermediate_min_ipchi2
std::vector< float > m_intermediate_max_ipchi2
std::vector< float > m_intermediate_vertex_volume
float m_min_mass = -1
float m_max_mass = -1
float m_min_decayTime = -1
float m_max_decayTime = FLT_MAX
float m_min_decayLength = -1
float m_max_decayLength = FLT_MAX
float m_track_pt = -1
float m_track_ptchi2 = FLT_MAX
float m_track_ip = -1
float m_track_ipchi2 = -1
float m_track_chi2ndof = FLT_MAX
int m_nMVTXHits = 3
int m_nTPCHits = 20
float m_comb_DCA = FLT_MAX
float m_vertex_chi2ndof = FLT_MAX
float m_fdchi2 = -1
float m_dira_min = -1
float m_dira_max = 1
float m_mother_pt = -1
float m_mother_ipchi2 = FLT_MAX
float m_mother_vertex_volume = FLT_MAX
float m_mva_cut_value = -1
bool m_get_charge_conjugate = true
bool m_extrapolateTracksToSV = true
bool m_allowZeroMassTracks = false
std::string m_vtx_map_node_name
std::string m_trk_map_node_name
SvtxVertexMap * m_dst_vertexmap = nullptr
SvtxTrackMap * m_dst_trackmap = nullptr
SvtxVertex * m_dst_vertex = nullptr
SvtxTrack * m_dst_track = nullptr
Private Member Functions
void removeDuplicates (std::vector< double > &v)
void removeDuplicates (std::vector< int > &v)
void removeDuplicates (std::vector< std::vector< int >> &v)
void removeDuplicates (std::vector< std::vector< std::string >> &v)
Additional Inherited Members
Protected Member Functions inherited from KFParticle_MVA
KFParticle_MVA ()=default
virtual ~KFParticle_MVA ()=default
std::tuple< TMVA::Reader
*, std::vector< Float_t > > initMVA ()
Float_t evaluateMVA (TMVA::Reader *reader, std::vector< Float_t > reader_floats, const KFParticle &particle, const KFPVertex &vertex)
Detailed Description
Definition at line 42 of file KFParticle_Tools.h.
View newest version in sPHENIX GitHub at line 42 of file KFParticle_Tools.h
Constructor & Destructor Documentation
KFParticle_Tools::KFParticle_Tools ()
KFParticle constructor.
Definition at line 61 of file KFParticle_Tools.cc.
View newest version in sPHENIX GitHub at line 61 of file KFParticle_Tools.cc
KFParticle_Tools::~KFParticle_Tools () override default
Member Function Documentation
std::vector< std::vector< int > > KFParticle_Tools::appendTracksToIntermediates (KFParticle intermediateResonances[], std::vector< KFParticle > daughterParticles, const std::vector< int > & goodTrackIndex, int num_remaining_tracks)
Definition at line 448 of file KFParticle_Tools.cc.
View newest version in sPHENIX GitHub at line 448 of file KFParticle_Tools.cc
References end, findNProngs(), findTwoProngs(), i, j, k, m_num_intermediate_states, and merge_hashes::p.
Referenced by KFParticle_eventReconstruction::buildChain().
std::tuple< KFParticle, bool > KFParticle_Tools::buildMother (KFParticle vDaughters[], std::string daughterOrder[], bool isIntermediate, int intermediateNumber, int nTracks, bool constrainMass, float required_vertexID)
Definition at line 572 of file KFParticle_Tools.cc.
View newest version in sPHENIX GitHub at line 572 of file KFParticle_Tools.cc
References KFParticle::AddDaughter(), calculateEllipsoidVolume(), KFParticle::Create(), eventDIRA(), flightDistanceChi2(), KFParticle::GetMass(), GetMass(), getParticleID(), getParticleMass(), KFParticle::GetPt(), KFParticle::GetQ(), GetQ(), i, truth_tracking_gsf_refitting::inputTracks, j, k, m_allowZeroMassTracks, m_extrapolateTracksToSV, m_get_charge_conjugate, m_has_intermediates, m_intermediate_mass_range, m_intermediate_min_dira, m_intermediate_min_fdchi2, m_intermediate_min_pt, m_intermediate_name, m_intermediate_vertex_volume, m_max_mass, m_min_mass, m_mother_name_Tools, m_mother_pt, m_mother_vertex_volume, m_num_intermediate_states, m_num_tracks, m_num_tracks_from_intermediate, std::tr1::make_tuple(), KFParticleBase::SetConstructMethod(), KFParticleBase::SetPDG(), and KFParticleBase::SetProductionVertex().
Referenced by getCombination().
int KFParticle_Tools::calcMinIP (const KFParticle & track, const std::vector< KFParticle > & PVs, float & minimumIP, float & minimumIPchi2)
Definition at line 307 of file KFParticle_Tools.cc.
View newest version in sPHENIX GitHub at line 307 of file KFParticle_Tools.cc
References KFParticleBase::GetDeviationFromVertex(), and KFParticleBase::GetDistanceFromVertex().
Referenced by KFParticle_eventReconstruction::getCandidateDecay(), and isGoodTrack().
double KFParticle_Tools::calculateEllipsoidRadius (int posOrNeg, double sigma_ii, double sigma_jj, double sigma_ij)
Definition at line 749 of file KFParticle_Tools.cc.
View newest version in sPHENIX GitHub at line 749 of file KFParticle_Tools.cc
float KFParticle_Tools::calculateEllipsoidVolume (const KFParticle & particle)
Definition at line 762 of file KFParticle_Tools.cc.
View newest version in sPHENIX GitHub at line 762 of file KFParticle_Tools.cc
References KFParticle::GetCovariance(), i, and j.
Referenced by buildMother(), and KFParticle_nTuple::fillBranch().
float KFParticle_Tools::calculateJT (const KFParticle & mother, const KFParticle & daughter)
Definition at line 787 of file KFParticle_Tools.cc.
View newest version in sPHENIX GitHub at line 787 of file KFParticle_Tools.cc
References KFParticle::GetPx(), KFParticle::GetPy(), and KFParticle::GetPz().
Referenced by KFParticle_nTuple::fillBranch().
void KFParticle_Tools::constrainToVertex (KFParticle & particle, bool & goodCandidate, KFParticle & vertex)
Definition at line 677 of file KFParticle_Tools.cc.
View newest version in sPHENIX GitHub at line 677 of file KFParticle_Tools.cc
References eventDIRA(), flightDistanceChi2(), KFParticle::GetDecayLength(), KFParticleBase::GetDeviationFromVertex(), KFParticle::GetLifeTime(), isInRange(), m_dira_max, m_dira_min, m_fdchi2, m_max_decayLength, m_max_decayTime, m_min_decayLength, m_min_decayTime, m_mother_ipchi2, particle, KFParticleBase::SetProductionVertex(), and KFParticleBase::TransportToDecayVertex().
Referenced by getCombination().
float KFParticle_Tools::eventDIRA (const KFParticle & particle, const KFParticle & vertex)
Calculates the cosine of the angle betweent the flight direction and momentum.
Definition at line 519 of file KFParticle_Tools.cc.
View newest version in sPHENIX GitHub at line 519 of file KFParticle_Tools.cc
References KFParticle::GetPx(), KFParticle::GetPy(), KFParticle::GetPz(), KFParticle::GetX(), KFParticle::GetY(), and KFParticle::GetZ().
Referenced by buildMother(), constrainToVertex(), and KFParticle_nTuple::fillBranch().
std::vector< int > KFParticle_Tools::findAllGoodTracks (std::vector< KFParticle > daughterParticles, const std::vector< KFParticle > & primaryVertices)
Definition at line 331 of file KFParticle_Tools.cc.
View newest version in sPHENIX GitHub at line 331 of file KFParticle_Tools.cc
References isGoodTrack(), and removeDuplicates().
Referenced by KFParticle_eventReconstruction::createDecay().
std::vector< std::vector< int > > KFParticle_Tools::findNProngs (std::vector< KFParticle > daughterParticles, const std::vector< int > & goodTrackIndex, std::vector< std::vector< int >> goodTracksThatMeet, int nRequiredTracks, unsigned int nProngs)
Definition at line 382 of file KFParticle_Tools.cc.
View newest version in sPHENIX GitHub at line 382 of file KFParticle_Tools.cc
References KFParticle::GetChi2(), GetDistanceFromParticle(), KFParticle::GetNDF(), i, m_comb_DCA, m_vertex_chi2ndof, removeDuplicates(), and Acts::Experimental::detail::BlueprintHelper::sort().
Referenced by appendTracksToIntermediates(), KFParticle_eventReconstruction::buildBasicChain(), and KFParticle_eventReconstruction::buildChain().
bool KFParticle_Tools::findParticle (const std::string & particle)
Definition at line 844 of file KFParticle_Tools.cc.
View newest version in sPHENIX GitHub at line 844 of file KFParticle_Tools.cc
Referenced by KFParticle_sPHENIX::parseDecayDescriptor().
std::vector< std::vector< int > > KFParticle_Tools::findTwoProngs (std::vector< KFParticle > daughterParticles, std::vector< int > goodTrackIndex, int nTracks)
Definition at line 348 of file KFParticle_Tools.cc.
View newest version in sPHENIX GitHub at line 348 of file KFParticle_Tools.cc
References KFParticle::GetChi2(), GetDistanceFromParticle(), KFParticle::GetNDF(), m_comb_DCA, and m_vertex_chi2ndof.
Referenced by appendTracksToIntermediates(), KFParticle_eventReconstruction::buildBasicChain(), and KFParticle_eventReconstruction::buildChain().
std::vector< std::vector< std::string > > KFParticle_Tools::findUniqueDaughterCombinations (int start, int end)
Definition at line 721 of file KFParticle_Tools.cc.
View newest version in sPHENIX GitHub at line 721 of file KFParticle_Tools.cc
References end, i, m_daughter_name, removeDuplicates(), and start.
Referenced by KFParticle_eventReconstruction::buildChain(), and KFParticle_eventReconstruction::getCandidateDecay().
float KFParticle_Tools::flightDistanceChi2 (const KFParticle & particle, const KFParticle & vertex)
Definition at line 546 of file KFParticle_Tools.cc.
View newest version in sPHENIX GitHub at line 546 of file KFParticle_Tools.cc
References KFParticle::GetCovariance(), KFParticle::GetX(), KFParticle::GetY(), KFParticle::GetZ(), i, and j.
Referenced by buildMother(), constrainToVertex(), KFParticle_MVA::evaluateMVA(), and KFParticle_nTuple::fillBranch().
std::tuple< KFParticle, bool > KFParticle_Tools::getCombination (KFParticle vDaughters[], std::string daughterOrder[], KFParticle vertex, bool constrain_to_vertex, bool isIntermediate, int intermediateNumber, int nTracks, bool constrainMass, float required_vertexID)
Definition at line 706 of file KFParticle_Tools.cc.
View newest version in sPHENIX GitHub at line 706 of file KFParticle_Tools.cc
References buildMother(), constrainToVertex(), and std::tr1::make_tuple().
Referenced by KFParticle_eventReconstruction::buildChain(), and KFParticle_eventReconstruction::getCandidateDecay().
int KFParticle_Tools::getParticleID (const std::string & particle)
Definition at line 857 of file KFParticle_Tools.cc.
View newest version in sPHENIX GitHub at line 857 of file KFParticle_Tools.cc
Referenced by KFParticle_eventReconstruction::buildChain(), buildMother(), KFParticle_eventReconstruction::getCandidateDecay(), and QAG4SimulationKFParticle::QAG4SimulationKFParticle().
float KFParticle_Tools::getParticleMass (const std::string & particle)
Definition at line 862 of file KFParticle_Tools.cc.
View newest version in sPHENIX GitHub at line 862 of file KFParticle_Tools.cc
Referenced by KFParticle_eventReconstruction::buildChain(), buildMother(), KFParticle_nTuple::fillBranch(), KFParticle_eventReconstruction::getCandidateDecay(), and QAG4SimulationKFParticle::makeHepLV().
float KFParticle_Tools::getParticleMass (const int PDGID)
Definition at line 867 of file KFParticle_Tools.cc.
View newest version in sPHENIX GitHub at line 867 of file KFParticle_Tools.cc
int KFParticle_Tools::getTracksFromVertex (PHCompositeNode * topNode, const KFParticle & vertex, const std::string & vertexMapName)
Definition at line 256 of file KFParticle_Tools.cc.
View newest version in sPHENIX GitHub at line 256 of file KFParticle_Tools.cc
References SvtxVertexMap::find(), GlobalVertex::find_vtxids(), KFParticleBase::Id(), m_dst_vertexmap, m_vtx_map_node_name, SvtxVertex::size_tracks(), and GlobalVertex::SVTX.
Referenced by KFParticle_nTuple::fillBranch().
void KFParticle_Tools::identify (const KFParticle & particle)
Definition at line 872 of file KFParticle_Tools.cc.
View newest version in sPHENIX GitHub at line 872 of file KFParticle_Tools.cc
References KFParticle::GetCovariance(), KFParticle::GetMass(), KFParticleBase::GetPDG(), KFParticle::GetPx(), KFParticle::GetPy(), KFParticle::GetPz(), KFParticle::GetQ(), KFParticle::GetX(), KFParticle::GetY(), KFParticle::GetZ(), and KFParticleBase::Id().
Referenced by KFParticle_DST::printNode(), and KFParticle_sPHENIX::printParticles().
bool KFParticle_Tools::isGoodTrack (const KFParticle & particle, const std::vector< KFParticle > & primaryVertices)
Definition at line 278 of file KFParticle_Tools.cc.
View newest version in sPHENIX GitHub at line 278 of file KFParticle_Tools.cc
References calcMinIP(), KFParticle::GetChi2(), KFParticle::GetErrPt(), KFParticle::GetNDF(), KFParticle::GetPt(), m_track_chi2ndof, m_track_ip, m_track_ipchi2, m_track_pt, and physmon_track_finding_ttbar::pt.
Referenced by findAllGoodTracks().
bool KFParticle_Tools::isInRange (float min, float value, float max)
Definition at line 799 of file KFParticle_Tools.cc.
View newest version in sPHENIX GitHub at line 799 of file KFParticle_Tools.cc
Referenced by constrainToVertex(), and KFParticle_eventReconstruction::getCandidateDecay().
std::vector< KFParticle > KFParticle_Tools::makeAllDaughterParticles (PHCompositeNode * topNode)
Turn all dst tracks in KFP tracks
Definition at line 196 of file KFParticle_Tools.cc.
View newest version in sPHENIX GitHub at line 196 of file KFParticle_Tools.cc
References TrackSeed::begin_cluster_keys(), TrackSeed::end_cluster_keys(), SvtxTrack::get_silicon_seed(), SvtxTrack::get_tpc_seed(), TrkrDefs::getTrkrId(), m_dst_track, m_dst_trackmap, m_nMVTXHits, m_nTPCHits, m_trk_map_node_name, makeParticle(), TrkrDefs::mvtxId, TrkrDefs::tpcId, and trackID.
Referenced by KFParticle_eventReconstruction::createDecay().
std::vector< KFParticle > KFParticle_Tools::makeAllPrimaryVertices (PHCompositeNode * topNode, const std::string & vertexMapName)
Definition at line 119 of file KFParticle_Tools.cc.
View newest version in sPHENIX GitHub at line 119 of file KFParticle_Tools.cc
References GlobalVertex::end_vertexes(), SvtxVertexMap::find(), GlobalVertex::find_vertexes(), GlobalVertex::get_id(), m_dst_vertex, m_dst_vertexmap, m_vtx_map_node_name, makeVertex(), and GlobalVertex::SVTX.
Referenced by KFParticle_truthAndDetTools::allPVInfo(), KFParticle_eventReconstruction::createDecay(), and QAG4SimulationKFParticle::process_event().
KFParticle KFParticle_Tools::makeParticle (PHCompositeNode * topNode)
Return a KFPTrack from track vector and covariance matrix. No mass or vertex constraints.
Definition at line 166 of file KFParticle_Tools.cc.
View newest version in sPHENIX GitHub at line 166 of file KFParticle_Tools.cc
References KFParticle::Chi2(), KFParticle::Create(), SvtxTrack::get_charge(), SvtxTrack::get_chisq(), SvtxTrack::get_error(), SvtxTrack::get_id(), SvtxTrack::get_ndf(), SvtxTrack::get_px(), SvtxTrack::get_py(), SvtxTrack::get_pz(), SvtxTrack::get_x(), SvtxTrack::get_y(), SvtxTrack::get_z(), i, j, m_dst_track, KFParticle::NDF(), and KFParticleBase::SetId().
Referenced by makeAllDaughterParticles().
KFParticle KFParticle_Tools::makeVertex (PHCompositeNode * topNode)
Definition at line 94 of file KFParticle_Tools.cc.
View newest version in sPHENIX GitHub at line 94 of file KFParticle_Tools.cc
References KFParticle::Chi2(), KFParticle::Create(), SvtxVertex::get_chisq(), SvtxVertex::get_error(), SvtxVertex::get_ndof(), SvtxVertex::get_x(), SvtxVertex::get_y(), SvtxVertex::get_z(), i, j, m_dst_vertex, and KFParticle::NDF().
Referenced by makeAllPrimaryVertices().
void KFParticle_Tools::removeDuplicates (std::vector< double > & v) private
Definition at line 804 of file KFParticle_Tools.cc.
View newest version in sPHENIX GitHub at line 804 of file KFParticle_Tools.cc
References end, and it.
Referenced by findAllGoodTracks(), findNProngs(), and findUniqueDaughterCombinations().
void KFParticle_Tools::removeDuplicates (std::vector< int > & v) private
Definition at line 814 of file KFParticle_Tools.cc.
View newest version in sPHENIX GitHub at line 814 of file KFParticle_Tools.cc
References end, and it.
void KFParticle_Tools::removeDuplicates (std::vector< std::vector< int >> & v) private
Definition at line 824 of file KFParticle_Tools.cc.
View newest version in sPHENIX GitHub at line 824 of file KFParticle_Tools.cc
References end, it, and testSigmaEff::v.
void KFParticle_Tools::removeDuplicates (std::vector< std::vector< std::string >> & v) private
Definition at line 834 of file KFParticle_Tools.cc.
View newest version in sPHENIX GitHub at line 834 of file KFParticle_Tools.cc
References end, it, and testSigmaEff::v.
Member Data Documentation
bool KFParticle_Tools::m_allowZeroMassTracks = false protected
Definition at line 174 of file KFParticle_Tools.h.
View newest version in sPHENIX GitHub at line 174 of file KFParticle_Tools.h
Referenced by KFParticle_sPHENIX::allowZeroMassTracks(), and buildMother().
float KFParticle_Tools::m_comb_DCA = FLT_MAX protected
Definition at line 152 of file KFParticle_Tools.h.
View newest version in sPHENIX GitHub at line 152 of file KFParticle_Tools.h
Referenced by findNProngs(), findTwoProngs(), and KFParticle_sPHENIX::setMaximumDaughterDCA().
std::vector<int> KFParticle_Tools::m_daughter_charge protected
Definition at line 110 of file KFParticle_Tools.h.
View newest version in sPHENIX GitHub at line 110 of file KFParticle_Tools.h
Referenced by KFParticle_eventReconstruction::buildChain(), KFParticle_eventReconstruction::getCandidateDecay(), and KFParticle_sPHENIX::setDaughters().
std::vector<std::string> KFParticle_Tools::m_daughter_name protected
Definition at line 109 of file KFParticle_Tools.h.
View newest version in sPHENIX GitHub at line 109 of file KFParticle_Tools.h
Referenced by KFParticle_eventReconstruction::buildChain(), findUniqueDaughterCombinations(), KFParticle_eventReconstruction::getCandidateDecay(), and KFParticle_sPHENIX::setDaughters().
float KFParticle_Tools::m_dira_max = 1 protected
Definition at line 160 of file KFParticle_Tools.h.
View newest version in sPHENIX GitHub at line 160 of file KFParticle_Tools.h
Referenced by constrainToVertex(), and KFParticle_sPHENIX::setMaxDIRA().
float KFParticle_Tools::m_dira_min = -1 protected
Definition at line 158 of file KFParticle_Tools.h.
View newest version in sPHENIX GitHub at line 158 of file KFParticle_Tools.h
Referenced by constrainToVertex(), and KFParticle_sPHENIX::setMinDIRA().
SvtxTrack* KFParticle_Tools::m_dst_track = nullptr protected
Definition at line 181 of file KFParticle_Tools.h.
View newest version in sPHENIX GitHub at line 181 of file KFParticle_Tools.h
Referenced by makeAllDaughterParticles(), and makeParticle().
SvtxTrackMap* KFParticle_Tools::m_dst_trackmap = nullptr protected
Definition at line 179 of file KFParticle_Tools.h.
View newest version in sPHENIX GitHub at line 179 of file KFParticle_Tools.h
Referenced by makeAllDaughterParticles().
SvtxVertex* KFParticle_Tools::m_dst_vertex = nullptr protected
Definition at line 180 of file KFParticle_Tools.h.
View newest version in sPHENIX GitHub at line 180 of file KFParticle_Tools.h
Referenced by makeAllPrimaryVertices(), and makeVertex().
SvtxVertexMap* KFParticle_Tools::m_dst_vertexmap = nullptr protected
Definition at line 178 of file KFParticle_Tools.h.
View newest version in sPHENIX GitHub at line 178 of file KFParticle_Tools.h
Referenced by getTracksFromVertex(), and makeAllPrimaryVertices().
bool KFParticle_Tools::m_extrapolateTracksToSV = true protected
Definition at line 172 of file KFParticle_Tools.h.
View newest version in sPHENIX GitHub at line 172 of file KFParticle_Tools.h
Referenced by buildMother(), and KFParticle_sPHENIX::extraolateTracksToSV().
float KFParticle_Tools::m_fdchi2 = -1 protected
Definition at line 156 of file KFParticle_Tools.h.
View newest version in sPHENIX GitHub at line 156 of file KFParticle_Tools.h
Referenced by constrainToVertex(), and KFParticle_sPHENIX::setFlightDistancechi2().
bool KFParticle_Tools::m_get_charge_conjugate = true protected
Definition at line 170 of file KFParticle_Tools.h.
View newest version in sPHENIX GitHub at line 170 of file KFParticle_Tools.h
Referenced by buildMother(), and KFParticle_sPHENIX::getChargeConjugate().
bool KFParticle_Tools::m_has_intermediates protected
Definition at line 113 of file KFParticle_Tools.h.
View newest version in sPHENIX GitHub at line 113 of file KFParticle_Tools.h
Referenced by buildMother(), KFParticle_eventReconstruction::createDecay(), and KFParticle_sPHENIX::hasIntermediateStates().
std::vector<int> KFParticle_Tools::m_intermediate_charge protected
Definition at line 115 of file KFParticle_Tools.h.
View newest version in sPHENIX GitHub at line 115 of file KFParticle_Tools.h
Referenced by KFParticle_eventReconstruction::buildChain(), and KFParticle_sPHENIX::setIntermediateStates().
std::vector<std::pair<float, float> > KFParticle_Tools::m_intermediate_mass_range protected
Definition at line 116 of file KFParticle_Tools.h.
View newest version in sPHENIX GitHub at line 116 of file KFParticle_Tools.h
Referenced by buildMother(), and KFParticle_sPHENIX::setIntermediateMassRange().
std::vector<float> KFParticle_Tools::m_intermediate_max_ip protected
Definition at line 121 of file KFParticle_Tools.h.
View newest version in sPHENIX GitHub at line 121 of file KFParticle_Tools.h
Referenced by KFParticle_eventReconstruction::getCandidateDecay(), and KFParticle_sPHENIX::setIntermediateIPRange().
std::vector<float> KFParticle_Tools::m_intermediate_max_ipchi2 protected
Definition at line 123 of file KFParticle_Tools.h.
View newest version in sPHENIX GitHub at line 123 of file KFParticle_Tools.h
Referenced by KFParticle_eventReconstruction::getCandidateDecay(), and KFParticle_sPHENIX::setIntermediateIPchi2Range().
std::vector<float> KFParticle_Tools::m_intermediate_min_dira protected
Definition at line 118 of file KFParticle_Tools.h.
View newest version in sPHENIX GitHub at line 118 of file KFParticle_Tools.h
Referenced by buildMother(), and KFParticle_sPHENIX::setIntermediateMinDIRA().
std::vector<float> KFParticle_Tools::m_intermediate_min_fdchi2 protected
Definition at line 119 of file KFParticle_Tools.h.
View newest version in sPHENIX GitHub at line 119 of file KFParticle_Tools.h
Referenced by buildMother(), and KFParticle_sPHENIX::setIntermediateMinFDchi2().
std::vector<float> KFParticle_Tools::m_intermediate_min_ip protected
Definition at line 120 of file KFParticle_Tools.h.
View newest version in sPHENIX GitHub at line 120 of file KFParticle_Tools.h
Referenced by KFParticle_eventReconstruction::getCandidateDecay(), KFParticle_sPHENIX::setIntermediateIPRange(), and KFParticle_sPHENIX::setIntermediateMinIP().
std::vector<float> KFParticle_Tools::m_intermediate_min_ipchi2 protected
Definition at line 122 of file KFParticle_Tools.h.
View newest version in sPHENIX GitHub at line 122 of file KFParticle_Tools.h
Referenced by KFParticle_eventReconstruction::getCandidateDecay(), KFParticle_sPHENIX::setIntermediateIPchi2Range(), and KFParticle_sPHENIX::setIntermediateMinIPchi2().
std::vector<float> KFParticle_Tools::m_intermediate_min_pt protected
Definition at line 117 of file KFParticle_Tools.h.
View newest version in sPHENIX GitHub at line 117 of file KFParticle_Tools.h
Referenced by buildMother(), and KFParticle_sPHENIX::setIntermediateMinPT().
std::vector<std::string> KFParticle_Tools::m_intermediate_name protected
Definition at line 114 of file KFParticle_Tools.h.
View newest version in sPHENIX GitHub at line 114 of file KFParticle_Tools.h
Referenced by KFParticle_eventReconstruction::buildChain(), buildMother(), and KFParticle_sPHENIX::setIntermediateStates().
std::vector<float> KFParticle_Tools::m_intermediate_vertex_volume protected
Definition at line 124 of file KFParticle_Tools.h.
View newest version in sPHENIX GitHub at line 124 of file KFParticle_Tools.h
Referenced by buildMother(), and KFParticle_sPHENIX::setIntermediateMaxVertexVolume().
float KFParticle_Tools::m_max_decayLength = FLT_MAX protected
Definition at line 136 of file KFParticle_Tools.h.
View newest version in sPHENIX GitHub at line 136 of file KFParticle_Tools.h
Referenced by constrainToVertex(), and KFParticle_sPHENIX::setDecayLengthRange().
float KFParticle_Tools::m_max_decayTime = FLT_MAX protected
Definition at line 132 of file KFParticle_Tools.h.
View newest version in sPHENIX GitHub at line 132 of file KFParticle_Tools.h
Referenced by constrainToVertex(), and KFParticle_sPHENIX::setDecayTimeRange().
float KFParticle_Tools::m_max_mass = -1 protected
Definition at line 128 of file KFParticle_Tools.h.
View newest version in sPHENIX GitHub at line 128 of file KFParticle_Tools.h
Referenced by buildMother(), and KFParticle_sPHENIX::setMaximumMass().
float KFParticle_Tools::m_min_decayLength = -1 protected
Definition at line 134 of file KFParticle_Tools.h.
View newest version in sPHENIX GitHub at line 134 of file KFParticle_Tools.h
Referenced by constrainToVertex(), and KFParticle_sPHENIX::setDecayLengthRange().
float KFParticle_Tools::m_min_decayTime = -1 protected
Definition at line 130 of file KFParticle_Tools.h.
View newest version in sPHENIX GitHub at line 130 of file KFParticle_Tools.h
Referenced by constrainToVertex(), and KFParticle_sPHENIX::setDecayTimeRange().
float KFParticle_Tools::m_min_mass = -1 protected
Definition at line 126 of file KFParticle_Tools.h.
View newest version in sPHENIX GitHub at line 126 of file KFParticle_Tools.h
Referenced by buildMother(), and KFParticle_sPHENIX::setMinimumMass().
float KFParticle_Tools::m_mother_ipchi2 = FLT_MAX protected
Definition at line 164 of file KFParticle_Tools.h.
View newest version in sPHENIX GitHub at line 164 of file KFParticle_Tools.h
Referenced by constrainToVertex(), and KFParticle_sPHENIX::setMotherIPchi2().
std::string KFParticle_Tools::m_mother_name_Tools protected
Definition at line 106 of file KFParticle_Tools.h.
View newest version in sPHENIX GitHub at line 106 of file KFParticle_Tools.h
Referenced by buildMother(), and KFParticle_sPHENIX::setMotherName().
float KFParticle_Tools::m_mother_pt = -1 protected
Definition at line 162 of file KFParticle_Tools.h.
View newest version in sPHENIX GitHub at line 162 of file KFParticle_Tools.h
Referenced by buildMother(), and KFParticle_sPHENIX::setMotherPT().
float KFParticle_Tools::m_mother_vertex_volume = FLT_MAX protected
Definition at line 166 of file KFParticle_Tools.h.
View newest version in sPHENIX GitHub at line 166 of file KFParticle_Tools.h
Referenced by buildMother(), and KFParticle_sPHENIX::setMaximumMotherVertexVolume().
float KFParticle_Tools::m_mva_cut_value = -1 protected
Definition at line 168 of file KFParticle_Tools.h.
View newest version in sPHENIX GitHub at line 168 of file KFParticle_Tools.h
Referenced by KFParticle_sPHENIX::setMVACutValue().
int KFParticle_Tools::m_nMVTXHits = 3 protected
Definition at line 148 of file KFParticle_Tools.h.
View newest version in sPHENIX GitHub at line 148 of file KFParticle_Tools.h
Referenced by makeAllDaughterParticles(), and KFParticle_sPHENIX::setMinMVTXhits().
int KFParticle_Tools::m_nTPCHits = 20 protected
Definition at line 150 of file KFParticle_Tools.h.
View newest version in sPHENIX GitHub at line 150 of file KFParticle_Tools.h
Referenced by makeAllDaughterParticles(), and KFParticle_sPHENIX::setMinTPChits().
int KFParticle_Tools::m_num_intermediate_states = -1 protected
Definition at line 107 of file KFParticle_Tools.h.
View newest version in sPHENIX GitHub at line 107 of file KFParticle_Tools.h
Referenced by appendTracksToIntermediates(), KFParticle_eventReconstruction::buildChain(), buildMother(), and KFParticle_sPHENIX::setNumberOfIntermediateStates().
int KFParticle_Tools::m_num_tracks = -1 protected
Definition at line 111 of file KFParticle_Tools.h.
View newest version in sPHENIX GitHub at line 111 of file KFParticle_Tools.h
Referenced by KFParticle_eventReconstruction::buildBasicChain(), KFParticle_eventReconstruction::buildChain(), buildMother(), and KFParticle_sPHENIX::setNumberOfTracks().
std::vector<int> KFParticle_Tools::m_num_tracks_from_intermediate protected
Definition at line 108 of file KFParticle_Tools.h.
View newest version in sPHENIX GitHub at line 108 of file KFParticle_Tools.h
Referenced by KFParticle_eventReconstruction::buildChain(), buildMother(), and KFParticle_sPHENIX::setNumberTracksFromIntermeditateState().
float KFParticle_Tools::m_track_chi2ndof = FLT_MAX protected
Definition at line 146 of file KFParticle_Tools.h.
View newest version in sPHENIX GitHub at line 146 of file KFParticle_Tools.h
Referenced by isGoodTrack(), and KFParticle_sPHENIX::setMaximumTrackchi2nDOF().
float KFParticle_Tools::m_track_ip = -1 protected
Definition at line 142 of file KFParticle_Tools.h.
View newest version in sPHENIX GitHub at line 142 of file KFParticle_Tools.h
Referenced by isGoodTrack(), and KFParticle_sPHENIX::setMinimumTrackIP().
float KFParticle_Tools::m_track_ipchi2 = -1 protected
Definition at line 144 of file KFParticle_Tools.h.
View newest version in sPHENIX GitHub at line 144 of file KFParticle_Tools.h
Referenced by isGoodTrack(), and KFParticle_sPHENIX::setMinimumTrackIPchi2().
float KFParticle_Tools::m_track_pt = -1 protected
Definition at line 138 of file KFParticle_Tools.h.
View newest version in sPHENIX GitHub at line 138 of file KFParticle_Tools.h
Referenced by isGoodTrack(), and KFParticle_sPHENIX::setMinimumTrackPT().
float KFParticle_Tools::m_track_ptchi2 = FLT_MAX protected
Definition at line 140 of file KFParticle_Tools.h.
View newest version in sPHENIX GitHub at line 140 of file KFParticle_Tools.h
Referenced by KFParticle_sPHENIX::setMaximumTrackPTchi2().
std::string KFParticle_Tools::m_trk_map_node_name protected
Definition at line 177 of file KFParticle_Tools.h.
View newest version in sPHENIX GitHub at line 177 of file KFParticle_Tools.h
Referenced by makeAllDaughterParticles(), KFParticle_sPHENIX::process_event(), and KFParticle_sPHENIX::setTrackMapNodeName().
float KFParticle_Tools::m_vertex_chi2ndof = FLT_MAX protected
Definition at line 154 of file KFParticle_Tools.h.
View newest version in sPHENIX GitHub at line 154 of file KFParticle_Tools.h
Referenced by findNProngs(), findTwoProngs(), and KFParticle_sPHENIX::setMaximumVertexchi2nDOF().
std::string KFParticle_Tools::m_vtx_map_node_name protected
Definition at line 176 of file KFParticle_Tools.h.
View newest version in sPHENIX GitHub at line 176 of file KFParticle_Tools.h
Referenced by KFParticle_eventReconstruction::createDecay(), getTracksFromVertex(), makeAllPrimaryVertices(), KFParticle_sPHENIX::process_event(), and KFParticle_sPHENIX::setVertexMapNodeName().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/KFParticle_sPHENIX/KFParticle_Tools.h
coresoftware/blob/master/offline/packages/KFParticle_sPHENIX/KFParticle_Tools.cc