Analysis Software: AdSCFT Class Reference
AdSCFT Class Reference
#include <JETSCAPE/blob/main/src/jet/AdSCFT.h>
Public Member Functions
AdSCFT ()
virtual ~AdSCFT ()
void Init ()
void Clear ()
void DoEnergyLoss (double deltaT, double time, double Q2, vector< Parton > &pIn, vector< Parton > &pOut)
double Drag (double f_dist, double deltaT, double Efs, double temp, double CF)
void WriteTask (weak_ptr< JetScapeWriter > w)
Public Member Functions inherited from Jetscape::JetEnergyLossModule< AdSCFT >
virtual shared_ptr< JetEnergyLoss > Clone () const override
Deep copy constructor. The goal is to not have to initialize Modules multiple times.
void SetActive (bool m_active_exec)
Override deactivation.
Public Member Functions inherited from Jetscape::JetEnergyLoss
JetEnergyLoss ()
JetEnergyLoss (const JetEnergyLoss &j)
virtual ~JetEnergyLoss ()
virtual void Exec () final
void SetQhat (double m_qhat)
const double GetQhat () const
void AddShowerInitiatingParton (shared_ptr< Parton > p)
shared_ptr< Parton > GetShowerInitiatingParton ()
void PrintShowerInitiatingParton ()
double GetDeltaT ()
double GetMaxT ()
shared_ptr< PartonShower > GetShower ()
void SetJetSignalConnected (bool m_jetSignalConnected)
TODO: Remove.
const bool GetJetSignalConnected () const
void SetEdensitySignalConnected (bool m_edensitySignalConnected)
const bool GetEdensitySignalConnected () const
void SetGetHydroCellSignalConnected (bool m_GetHydroCellSignalConnected)
const bool GetGetHydroCellSignalConnected ()
void SetGetHydroTau0SignalConnected (bool m_GetHydroTau0SignalConnected)
const bool GetGetHydroTau0SignalConnected ()
void SetSentInPartonsConnected (bool m_SentInPartonsConnected)
const bool GetSentInPartonsConnected ()
void add_a_liquefier (std::shared_ptr< LiquefierBase > new_liquefier)
std::weak_ptr< LiquefierBase > get_liquefier ()
void SendFinalStatePartons (vector< vector< shared_ptr< Parton >>> &fPartons)
void GetFinalPartonsForEachShower (shared_ptr< PartonShower > shower)
Public Member Functions inherited from Jetscape::JetScapeModuleBase
JetScapeModuleBase ()
JetScapeModuleBase (string m_name)
virtual ~JetScapeModuleBase ()
void SetXMLMainFileName (string m_name)
string GetXMLMainFileName ()
void SetXMLUserFileName (string m_name)
string GetXMLUserFileName ()
shared_ptr< std::mt19937 > GetMt19937Generator ()
tinyxml2::XMLElement * GetXMLElement (std::initializer_list< const char * > path, bool isRequired=true)
std::string GetXMLElementText (std::initializer_list< const char * > path, bool isRequired=true)
int GetXMLElementInt (std::initializer_list< const char * > path, bool isRequired=true)
double GetXMLElementDouble (std::initializer_list< const char * > path, bool isRequired=true)
Public Member Functions inherited from Jetscape::JetScapeTask
JetScapeTask ()
virtual ~JetScapeTask ()
virtual void Finish ()
virtual void ExecuteTasks ()
virtual void ExecuteTask ()
virtual void InitTask ()
virtual void InitTasks ()
virtual void ClearTasks ()
virtual void ClearTask ()
virtual void FinishTask ()
virtual void FinishTasks ()
virtual void WriteTasks (weak_ptr< JetScapeWriter > w)
virtual void CollectHeader (weak_ptr< JetScapeWriter > w)
virtual void CollectHeaders (weak_ptr< JetScapeWriter > w)
virtual void Add (shared_ptr< JetScapeTask > m_tasks)
virtual const int GetMyTaskNumber () const
const vector< shared_ptr
< JetScapeTask > > GetTaskList () const
shared_ptr< JetScapeTask > GetTaskAt (int i)
void EraseTaskLast ()
void EraseTaskAt (int i)
void ResizeTaskList (int i)
void ClearTaskList ()
int GetNumberOfTasks ()
const bool GetActive () const
void SetActive (bool m_active_exec)
void SetId (string m_id)
const string GetId () const
const shared_ptr
< JetScapeModuleMutex > GetMutex () const
void SetMutex (shared_ptr< JetScapeModuleMutex > m_mutex)
Public Member Functions inherited from sigslot::has_slots< sigslot::multi_threaded_local >
has_slots ()
has_slots (const has_slots &hs)
void signal_connect (_signal_base< sigslot::multi_threaded_local > *sender)
void signal_disconnect (_signal_base< sigslot::multi_threaded_local > *sender)
virtual ~has_slots ()
void disconnect_all ()
Private Attributes
double tStart = 0.6
double T0
double Q0
bool in_vac
double kappa
Static Private Attributes
static RegisterJetScapeModule
< AdSCFT > reg
Additional Inherited Members
Static Public Member Functions inherited from Jetscape::JetScapeModuleBase
static int GetCurrentEvent ()
static void IncrementCurrentEvent ()
Public Attributes inherited from Jetscape::JetEnergyLoss
sigslot::signal5< double,
double, double, double,
std::unique_ptr< FluidCellInfo >
&, multi_threaded_local > GetHydroCellSignal
Core signal to receive information from the medium.
sigslot::signal1< double
&, multi_threaded_local > GetHydroTau0Signal
sigslot::signal2< int, double,
multi_threaded_local > jetSignal
sigslot::signal2< int, double
&, multi_threaded_local > edensitySignal
sigslot::signal5< double,
double, double, vector< Parton >
&, vector< Parton >
&, multi_threaded_local > SentInPartons
Protected Member Functions inherited from Jetscape::JetEnergyLossModule< AdSCFT >
bool TakeResponsibilityFor (Parton &p)
Protected Attributes inherited from Jetscape::JetEnergyLoss
std::weak_ptr< LiquefierBase > liquefier_ptr
Detailed Description
Definition at line 36 of file AdSCFT.h.
View newest version in sPHENIX GitHub at line 36 of file AdSCFT.h
Constructor & Destructor Documentation
AdSCFT::AdSCFT ()
Definition at line 33 of file AdSCFT.cc.
View newest version in sPHENIX GitHub at line 33 of file AdSCFT.cc
References kappa, Q0, Jetscape::JetScapeTask::SetId(), Jetscape::JetScapeTask::SetMutex(), T0, and VERBOSE.
AdSCFT::~AdSCFT () virtual
Definition at line 46 of file AdSCFT.cc.
View newest version in sPHENIX GitHub at line 46 of file AdSCFT.cc
References VERBOSE.
Member Function Documentation
void AdSCFT::Clear (void) virtual
Reset the parton shower information.
Reimplemented from Jetscape::JetEnergyLoss.
Definition at line 300 of file AdSCFT.cc.
View newest version in sPHENIX GitHub at line 300 of file AdSCFT.cc
void AdSCFT::DoEnergyLoss (double deltaT, double time, double Q2, vector< Parton > & pIn, vector< Parton > & pOut) virtual
Default function to perform the energy loss for partons at time "time". It should be overridden by different energy loss tasks.
Parameters
deltaT Step-size.
time Current time.
Q2 Current virtuality of the parton.
pIn Vector of current partons.
pOut Vector of partons at time "time+deltaT".
Reimplemented from Jetscape::JetEnergyLoss.
Definition at line 80 of file AdSCFT.cc.
View newest version in sPHENIX GitHub at line 80 of file AdSCFT.cc
References KFPMath::a, Jetscape::JetEnergyLoss::deltaT, Drag(), Acts::UnitConstants::e, ei(), Jetscape::JetEnergyLoss::GetHydroCellSignal, Jetscape::JetEnergyLoss::GetJetSignalConnected(), i, Id(), in_vac, j, JSDEBUG, JSWARN, MAGENTA, merge_hashes::p, Jetscape::photonid, train_ambiguity_solver::pid, Q0, QS, Jetscape::rounding_error, t, T0, Jetscape::JetEnergyLossModule< AdSCFT >::TakeResponsibilityFor(), tau, Jetscape::FluidCellInfo::temperature, tStart, testSigmaEff::v, v2, VERBOSE, VERBOSESHOWER, vx, Jetscape::FluidCellInfo::vx, vy, Jetscape::FluidCellInfo::vy, vz, Jetscape::FluidCellInfo::vz, and ambiguity_solver_full_chain::x.
double AdSCFT::Drag (double f_dist, double deltaT, double Efs, double temp, double CF)
Definition at line 279 of file AdSCFT.cc.
View newest version in sPHENIX GitHub at line 279 of file AdSCFT.cc
References kappa.
Referenced by DoEnergyLoss().
void AdSCFT::Init () virtual
It reads the input parameters from a XML file under the tag <Eloss>. Sets the Parton class inP and PartonShower class pShower to null. Also initializes the tasks attached to the JetEnergyLoss module.
Reimplemented from Jetscape::JetEnergyLoss.
Definition at line 48 of file AdSCFT.cc.
View newest version in sPHENIX GitHub at line 48 of file AdSCFT.cc
References Jetscape::JetScapeModuleBase::GetXMLElementDouble(), Jetscape::JetScapeModuleBase::GetXMLElementText(), in_vac, JSDEBUG, JSINFO, kappa, Q0, physmon_simulation::s, and T0.
void AdSCFT::WriteTask (weak_ptr< JetScapeWriter > w) virtual
Write output information for each tasks/subtasks attached to the JetEnergyLoss module using JetScapeWriter functionality.
Parameters
w A pointer of type JetScapeWriter.
Reimplemented from Jetscape::JetEnergyLoss.
Definition at line 71 of file AdSCFT.cc.
View newest version in sPHENIX GitHub at line 71 of file AdSCFT.cc
References f, Jetscape::JetScapeTask::GetId(), and VERBOSE.
Member Data Documentation
bool AdSCFT::in_vac private
Definition at line 53 of file AdSCFT.h.
View newest version in sPHENIX GitHub at line 53 of file AdSCFT.h
Referenced by DoEnergyLoss(), and Init().
double AdSCFT::kappa private
Definition at line 54 of file AdSCFT.h.
View newest version in sPHENIX GitHub at line 54 of file AdSCFT.h
Referenced by AdSCFT(), Drag(), and Init().
double AdSCFT::Q0 private
Definition at line 52 of file AdSCFT.h.
View newest version in sPHENIX GitHub at line 52 of file AdSCFT.h
Referenced by AdSCFT(), DoEnergyLoss(), and Init().
RegisterJetScapeModule< AdSCFT > AdSCFT::reg static private
Definition at line 57 of file AdSCFT.h.
View newest version in sPHENIX GitHub at line 57 of file AdSCFT.h
double AdSCFT::T0 private
Definition at line 51 of file AdSCFT.h.
View newest version in sPHENIX GitHub at line 51 of file AdSCFT.h
Referenced by AdSCFT(), DoEnergyLoss(), and Init().
double AdSCFT::tStart = 0.6 private
Definition at line 50 of file AdSCFT.h.
View newest version in sPHENIX GitHub at line 50 of file AdSCFT.h
Referenced by DoEnergyLoss().
The documentation for this class was generated from the following files:
JETSCAPE/blob/main/src/jet/AdSCFT.h
JETSCAPE/blob/main/src/jet/AdSCFT.cc