Analysis Software: PHTpcLookup Class Reference
PHTpcLookup Class Reference
#include <coresoftware/blob/master/offline/packages/PHTpcTracker/PHTpcLookup.h>
Public Member Functions
PHTpcLookup ()
~PHTpcLookup ()
void init (TrkrClusterContainer *cluster_map, TrkrHitSetContainer *hitsets)
void clear ()
std::vector< std::vector
< double > * > find (double x, double y, double z, double radius, size_t &nMatches)
Protected Attributes
TrkrClusterContainer * mClusterMap
TrkrHitSetContainer * mHitsets
std::vector< std::vector
< double > > mKDhits
kdfinder::KDPointCloud< double > mCloud
nanoflann::KDTreeSingleIndexAdaptor
< nanoflann::L2_Simple_Adaptor
< double,
kdfinder::KDPointCloud< double >
>, kdfinder::KDPointCloud
< double >, 3 > * mKDindex
Detailed Description
Definition at line 23 of file PHTpcLookup.h.
View newest version in sPHENIX GitHub at line 23 of file PHTpcLookup.h
Constructor & Destructor Documentation
PHTpcLookup::PHTpcLookup ()
Definition at line 20 of file PHTpcLookup.cc.
View newest version in sPHENIX GitHub at line 20 of file PHTpcLookup.cc
PHTpcLookup::~PHTpcLookup ()
Definition at line 27 of file PHTpcLookup.cc.
View newest version in sPHENIX GitHub at line 27 of file PHTpcLookup.cc
References mKDindex.
Member Function Documentation
void PHTpcLookup::clear ()
Definition at line 58 of file PHTpcLookup.cc.
View newest version in sPHENIX GitHub at line 58 of file PHTpcLookup.cc
References mCloud, mKDhits, and kdfinder::KDPointCloud< T >::pts.
Referenced by PHTpcTracker::Process().
std::vector< std::vector< double > * > PHTpcLookup::find (double x, double y, double z, double radius, size_t & nMatches)
Definition at line 64 of file PHTpcLookup.cc.
View newest version in sPHENIX GitHub at line 64 of file PHTpcLookup.cc
References i, LOG_DEBUG, LOG_ERROR, mKDhits, mKDindex, nanoflann::KDTreeSingleIndexAdaptor< Distance, DatasetAdaptor, DIM, IndexType >::radiusSearch(), x, and y.
Referenced by PHTpcTrackFollower::followTrack().
void PHTpcLookup::init (TrkrClusterContainer * cluster_map, TrkrHitSetContainer * hitsets)
Definition at line 32 of file PHTpcLookup.cc.
View newest version in sPHENIX GitHub at line 32 of file PHTpcLookup.cc
References nanoflann::KDTreeSingleIndexAdaptor< Distance, DatasetAdaptor, DIM, IndexType >::buildIndex(), PHTpcTrackerUtil::convert_clusters_to_hits(), i, mCloud, mClusterMap, mHitsets, mKDhits, mKDindex, and kdfinder::KDPointCloud< T >::pts.
Referenced by PHTpcTracker::Process().
Member Data Documentation
kdfinder::KDPointCloud<double> PHTpcLookup::mCloud protected
Definition at line 39 of file PHTpcLookup.h.
View newest version in sPHENIX GitHub at line 39 of file PHTpcLookup.h
Referenced by clear(), and init().
TrkrClusterContainer* PHTpcLookup::mClusterMap protected
Definition at line 36 of file PHTpcLookup.h.
View newest version in sPHENIX GitHub at line 36 of file PHTpcLookup.h
Referenced by init().
TrkrHitSetContainer* PHTpcLookup::mHitsets protected
Definition at line 37 of file PHTpcLookup.h.
View newest version in sPHENIX GitHub at line 37 of file PHTpcLookup.h
Referenced by init().
std::vector<std::vector<double> > PHTpcLookup::mKDhits protected
Definition at line 38 of file PHTpcLookup.h.
View newest version in sPHENIX GitHub at line 38 of file PHTpcLookup.h
Referenced by clear(), find(), and init().
nanoflann::KDTreeSingleIndexAdaptor<nanoflann::L2_Simple_Adaptor<double, kdfinder::KDPointCloud<double> >, kdfinder::KDPointCloud<double>, 3>* PHTpcLookup::mKDindex protected
Definition at line 41 of file PHTpcLookup.h.
View newest version in sPHENIX GitHub at line 41 of file PHTpcLookup.h
Referenced by find(), init(), and ~PHTpcLookup().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/PHTpcTracker/PHTpcLookup.h
coresoftware/blob/master/offline/packages/PHTpcTracker/PHTpcLookup.cc