Analysis Software: tinyxml2::XMLUtil Class Reference
tinyxml2::XMLUtil Class Reference
#include <JETSCAPE/blob/main/external_packages/tinyxml2.h>
Static Public Member Functions
static const char * SkipWhiteSpace (const char *p)
static char * SkipWhiteSpace (char *p)
static bool IsWhiteSpace (char p)
static bool IsNameStartChar (unsigned char ch)
static bool IsNameChar (unsigned char ch)
static bool StringEqual (const char *p, const char *q, int nChar=INT_MAX)
static bool IsUTF8Continuation (char p)
static const char * ReadBOM (const char *p, bool *hasBOM)
static const char * GetCharacterRef (const char *p, char *value, int *length)
static void ConvertUTF32ToUTF8 (unsigned long input, char *output, int *length)
static void ToStr (int v, char *buffer, int bufferSize)
static void ToStr (unsigned v, char *buffer, int bufferSize)
static void ToStr (bool v, char *buffer, int bufferSize)
static void ToStr (float v, char *buffer, int bufferSize)
static void ToStr (double v, char *buffer, int bufferSize)
static void ToStr (int64_t v, char *buffer, int bufferSize)
static bool ToInt (const char *str, int *value)
static bool ToUnsigned (const char *str, unsigned *value)
static bool ToBool (const char *str, bool *value)
static bool ToFloat (const char *str, float *value)
static bool ToDouble (const char *str, double *value)
static bool ToInt64 (const char *str, int64_t *value)
Detailed Description
Definition at line 530 of file tinyxml2.h.
View newest version in sPHENIX GitHub at line 530 of file tinyxml2.h
Member Function Documentation
void tinyxml2::XMLUtil::ConvertUTF32ToUTF8 (unsigned long input, char * output, int * length) static
Definition at line 386 of file tinyxml2.cc.
View newest version in sPHENIX GitHub at line 386 of file tinyxml2.cc
References G4PLUGDOOR::length, check_smearing_config::output, and TIXMLASSERT.
Referenced by GetCharacterRef().
const char * tinyxml2::XMLUtil::GetCharacterRef (const char * p, char * value, int * length) static
Definition at line 435 of file tinyxml2.cc.
View newest version in sPHENIX GitHub at line 435 of file tinyxml2.cc
References ConvertUTF32ToUTF8(), physmon_vertexing::delta, merge_hashes::p, and TIXMLASSERT.
Referenced by tinyxml2::StrPair::GetStr().
static bool tinyxml2::XMLUtil::IsNameChar (unsigned char ch) inline static
Definition at line 562 of file tinyxml2.h.
View newest version in sPHENIX GitHub at line 562 of file tinyxml2.h
Referenced by tinyxml2::StrPair::ParseName().
static bool tinyxml2::XMLUtil::IsNameStartChar (unsigned char ch) inline static
Definition at line 551 of file tinyxml2.h.
View newest version in sPHENIX GitHub at line 551 of file tinyxml2.h
Referenced by tinyxml2::XMLElement::ParseAttributes(), and tinyxml2::StrPair::ParseName().
static bool tinyxml2::XMLUtil::IsUTF8Continuation (char p) inline static
Definition at line 579 of file tinyxml2.h.
View newest version in sPHENIX GitHub at line 579 of file tinyxml2.h
static bool tinyxml2::XMLUtil::IsWhiteSpace (char p) inline static
Definition at line 547 of file tinyxml2.h.
View newest version in sPHENIX GitHub at line 547 of file tinyxml2.h
Referenced by tinyxml2::StrPair::CollapseWhitespace().
const char * tinyxml2::XMLUtil::ReadBOM (const char * p, bool * hasBOM) static
Definition at line 368 of file tinyxml2.cc.
View newest version in sPHENIX GitHub at line 368 of file tinyxml2.cc
References merge_hashes::p, TIXML_UTF_LEAD_2, and TIXMLASSERT.
Referenced by tinyxml2::XMLDocument::Parse().
static const char* tinyxml2::XMLUtil::SkipWhiteSpace (const char * p) inline static
Definition at line 533 of file tinyxml2.h.
View newest version in sPHENIX GitHub at line 533 of file tinyxml2.h
References merge_hashes::p, and TIXMLASSERT.
Referenced by tinyxml2::StrPair::CollapseWhitespace(), tinyxml2::XMLDocument::Identify(), tinyxml2::XMLDocument::Parse(), tinyxml2::XMLElement::ParseAttributes(), tinyxml2::XMLAttribute::ParseDeep(), and tinyxml2::XMLElement::ParseDeep().
static char* tinyxml2::XMLUtil::SkipWhiteSpace (char * p) inline static
Definition at line 541 of file tinyxml2.h.
View newest version in sPHENIX GitHub at line 541 of file tinyxml2.h
static bool tinyxml2::XMLUtil::StringEqual (const char * p, const char * q, int nChar = INT_MAX) inline static
Definition at line 569 of file tinyxml2.h.
View newest version in sPHENIX GitHub at line 569 of file tinyxml2.h
References TIXMLASSERT.
Referenced by tinyxml2::XMLElement::Attribute(), tinyxml2::XMLElement::DeleteAttribute(), tinyxml2::XMLElement::FindAttribute(), tinyxml2::XMLElement::FindOrCreateAttribute(), tinyxml2::XMLDocument::Identify(), tinyxml2::XMLNode::ParseDeep(), tinyxml2::XMLText::ShallowEqual(), tinyxml2::XMLComment::ShallowEqual(), tinyxml2::XMLDeclaration::ShallowEqual(), tinyxml2::XMLUnknown::ShallowEqual(), tinyxml2::XMLElement::ShallowEqual(), ToBool(), and tinyxml2::XMLNode::ToElementWithName().
bool tinyxml2::XMLUtil::ToBool (const char * str, bool * value) static
Definition at line 587 of file tinyxml2.cc.
View newest version in sPHENIX GitHub at line 587 of file tinyxml2.cc
References StringEqual(), and ToInt().
Referenced by tinyxml2::XMLElement::QueryBoolText(), and tinyxml2::XMLAttribute::QueryBoolValue().
bool tinyxml2::XMLUtil::ToDouble (const char * str, double * value) static
Definition at line 615 of file tinyxml2.cc.
View newest version in sPHENIX GitHub at line 615 of file tinyxml2.cc
References TIXML_SSCANF.
Referenced by tinyxml2::XMLElement::QueryDoubleText(), and tinyxml2::XMLAttribute::QueryDoubleValue().
bool tinyxml2::XMLUtil::ToFloat (const char * str, float * value) static
Definition at line 606 of file tinyxml2.cc.
View newest version in sPHENIX GitHub at line 606 of file tinyxml2.cc
References TIXML_SSCANF.
Referenced by tinyxml2::XMLElement::QueryFloatText(), and tinyxml2::XMLAttribute::QueryFloatValue().
bool tinyxml2::XMLUtil::ToInt (const char * str, int * value) static
Definition at line 571 of file tinyxml2.cc.
View newest version in sPHENIX GitHub at line 571 of file tinyxml2.cc
References TIXML_SSCANF.
Referenced by tinyxml2::XMLElement::QueryIntText(), tinyxml2::XMLAttribute::QueryIntValue(), and ToBool().
bool tinyxml2::XMLUtil::ToInt64 (const char * str, int64_t * value) static
Definition at line 624 of file tinyxml2.cc.
View newest version in sPHENIX GitHub at line 624 of file tinyxml2.cc
References TIXML_SSCANF, and testSigmaEff::v.
Referenced by tinyxml2::XMLElement::QueryInt64Text(), and tinyxml2::XMLAttribute::QueryInt64Value().
void tinyxml2::XMLUtil::ToStr (int v, char * buffer, int bufferSize) static
Definition at line 531 of file tinyxml2.cc.
View newest version in sPHENIX GitHub at line 531 of file tinyxml2.cc
References TIXML_SNPRINTF.
Referenced by tinyxml2::XMLPrinter::PushAttribute(), tinyxml2::XMLPrinter::PushText(), tinyxml2::XMLAttribute::SetAttribute(), and tinyxml2::XMLElement::SetText().
void tinyxml2::XMLUtil::ToStr (unsigned v, char * buffer, int bufferSize) static
Definition at line 537 of file tinyxml2.cc.
View newest version in sPHENIX GitHub at line 537 of file tinyxml2.cc
References TIXML_SNPRINTF.
void tinyxml2::XMLUtil::ToStr (bool v, char * buffer, int bufferSize) static
Definition at line 543 of file tinyxml2.cc.
View newest version in sPHENIX GitHub at line 543 of file tinyxml2.cc
References TIXML_SNPRINTF.
void tinyxml2::XMLUtil::ToStr (float v, char * buffer, int bufferSize) static
Definition at line 552 of file tinyxml2.cc.
View newest version in sPHENIX GitHub at line 552 of file tinyxml2.cc
References TIXML_SNPRINTF.
void tinyxml2::XMLUtil::ToStr (double v, char * buffer, int bufferSize) static
Definition at line 558 of file tinyxml2.cc.
View newest version in sPHENIX GitHub at line 558 of file tinyxml2.cc
References TIXML_SNPRINTF.
void tinyxml2::XMLUtil::ToStr (int64_t v, char * buffer, int bufferSize) static
Definition at line 564 of file tinyxml2.cc.
View newest version in sPHENIX GitHub at line 564 of file tinyxml2.cc
References TIXML_SNPRINTF.
bool tinyxml2::XMLUtil::ToUnsigned (const char * str, unsigned * value) static
Definition at line 579 of file tinyxml2.cc.
View newest version in sPHENIX GitHub at line 579 of file tinyxml2.cc
References TIXML_SSCANF.
Referenced by tinyxml2::XMLElement::QueryUnsignedText(), and tinyxml2::XMLAttribute::QueryUnsignedValue().
The documentation for this class was generated from the following files:
JETSCAPE/blob/main/external_packages/tinyxml2.h
JETSCAPE/blob/main/external_packages/tinyxml2.cc