Analysis Software: Acts::Experimental::detail::BlueprintHelper Namespace Reference
Acts::Experimental::detail::BlueprintHelper Namespace Reference
Functions
void sort (Blueprint::Node &node, bool recursive=true)
Sort the nodes in the blueprint container node.
void fillGaps (Blueprint::Node &node, bool adjustToParent=true)
Fill the gaps in the blueprint container node.
Function Documentation
void Acts::Experimental::detail::BlueprintHelper::fillGaps (Blueprint::Node & node, bool adjustToParent = true)
Fill the gaps in the blueprint container node.
Parameters
node the node for with the gaps should be filled
adjustToParent nodes, if nodes should be adjusted to parent
Note
currently only cylindrical volumes are supported
Definition at line 66 of file BlueprintHelper.cpp.
View newest version in sPHENIX GitHub at line 66 of file BlueprintHelper.cpp
References Acts::Experimental::Blueprint::Node::add(), Acts::Experimental::Blueprint::Node::binning, Acts::binR, Acts::binZ, Acts::Experimental::Blueprint::Node::boundaryValues, Acts::Experimental::Blueprint::Node::boundsType, gtest_filter_unittest::child, Acts::Experimental::Blueprint::Node::children, BlackHoleGeometry::gap, Acts::Experimental::Blueprint::Node::isLeaf(), testing::internal::move(), Acts::Experimental::Blueprint::Node::name, norm, Acts::Test::pos, Acts::s_onSurfaceTolerance, sort(), to_string(), and Acts::Experimental::Blueprint::Node::transform.
Referenced by BOOST_AUTO_TEST_CASE().
void Acts::Experimental::detail::BlueprintHelper::sort (Blueprint::Node & node, bool recursive = true)
Sort the nodes in the blueprint container node.
Parameters
node the node for which the children should be sorted
recursive if the sorting should be done recursively to children
Definition at line 31 of file BlueprintHelper.cpp.
View newest version in sPHENIX GitHub at line 31 of file BlueprintHelper.cpp
References KFPMath::a, KFPMath::b, Acts::Experimental::Blueprint::Node::binning, Acts::binR, Acts::binX, Acts::binY, Acts::binZ, Acts::Experimental::Blueprint::Node::boundsType, gtest_filter_unittest::child, Acts::Experimental::Blueprint::Node::children, Acts::Experimental::Blueprint::Node::transform, and physmon_ckf_tracking::u.
Referenced by ClosestPair2D::_initialize(), RandomConeAna::_median_stddev(), LazyTiling9Alt::_print_tiles(), LazyTiling9::_print_tiles(), LazyTiling25::_print_tiles(), ClusterSequence::_print_tiles(), ClusterSequence::_tiled_N2_cluster(), TrackClusEvaluator::addClusKeys(), OnlMonHtml::addMenu(), LeptoquarksReco::AddTrackInformation(), Acts::BinnedSPGroup< external_spacepoint_t >::BinnedSPGroup(), Acts::Experimental::detail::binSequence(), Acts::Test::BOOST_AUTO_TEST_CASE(), BOOST_AUTO_TEST_CASE(), BOOST_DATA_TEST_CASE(), ActsExamples::MockupSectorBuilder::buildSector(), OnlBbcEvent::calculate(), MbdEvent::Calculate(), TpcMon::calculateMedianAndStdDev(), Acts::detail::CantorEdge< int64_t >::CantorEdge(), Acts::PlanarModuleStepper::cellSteps(), Acts::DD4hepLayerBuilder::centralLayers(), Acts::BinningData::checkSubStructure(), Jetscape::JetScape::CompareElementsFromXML(), Acts::TrackingVolume::compatibleBoundaries(), Acts::TrackingVolume::compatibleLayers(), Acts::Layer::compatibleSurfaces(), Acts::TrackingVolume::compatibleSurfacesFromHierarchy(), HybridHadronization::convert_color_tags_to_int_type(), Acts::Sycl::SeedFinder< external_spacepoint_t >::createSeedsForGroup(), Acts::SeedFinder< external_spacepoint_t, Acts::Cuda >::createSeedsForGroup(), Acts::Cuda::SeedFinder< external_spacepoint_t >::createSeedsForGroup(), Acts::SurfaceArrayCreator::createVariableAxis(), AZigzag::DetermineCommonMode(), ActsExamples::DigitizationAlgorithm::DigitizationAlgorithm(), Acts::DD4hepLayerBuilder::endcapLayers(), Jetv2::ensure_sorted(), JetMultSub::EstimateRho(), PythiaGun::Exec(), epemGun::Exec(), ActsExamples::TruthSeedingAlgorithm::execute(), ActsExamples::PrototracksToParameters::execute(), Acts::fieldMapRZ(), Acts::fieldMapXYZ(), fillGaps(), FillHoughHist(), Acts::SeedFinder< external_spacepoint_t, platform_t >::filterCandidates(), Acts::SeedFinderOrthogonal< external_spacepoint_t >::filterCandidates(), Acts::SeedFilter< external_spacepoint_t >::filterSeeds_2SpFixed(), ActsExamples::Telescope::TelescopeDetector::finalize(), Acts::SingleSeedVertexFinder< spacepoint_t >::findClosestPointFromPlanes(), Acts::SingleSeedVertexFinder< spacepoint_t >::findClosestPointFromRays(), KFParticle_Tools::findNProngs(), TrigFTF_GNN_TrackingFilter< external_spacepoint_t >::followTrack(), ActsExamples::Sequencer::fpeReport(), Jetscape::TrentoInitial::GenCenTab(), JetBkgdSub::GetMedian(), Acts::FsmwMode1dFinder::getMode(), testing::internal::UnitTestHelper::GetSortedTestCases(), testing::internal::UnitTestHelper::GetSortedTests(), Acts::Test::hash(), ActsExamples::HoughTransformSeeder::HoughTransformSeeder(), Acts::Experimental::DetectorNavigator::initializeTarget(), Acts::KDTree< Dims, Type, Scalar, Vector, LeafSize >::KDTreeNode::KDTreeNode(), Acts::Ccl::labelClusters(), Acts::LayerArrayCreator::layerArray(), graph::load(), main(), testing::internal::WhenSortedByMatcher< Comparator, ContainerMatcher >::Impl< LhsContainer >::MatchAndExplain(), Acts::MaterialComposition::MaterialComposition(), Acts::materialMapperRZ(), Acts::materialMapperXYZ(), Acts::Ccl::mergeClusters(), DecayFinder::multiplyVectorByScalarAndSort(), Acts::Legacy::AtlasSeedFinder< SpacePoint >::newOneSeedWithCurvaturesComparison(), Acts::BoostTrackBuilding::operator()(), KFParticleTopoReconstructor::ParticleHasRepeatingDaughters(), Acts::detail::VerticesHelper::phiSegments(), PHMakeGroups(), RawClusterBuilderTopo::process_event(), ParticleFlowReco::process_event(), PHCosmicSeeder::process_event(), QAG4Decayer::process_event(), MBDStudy::process_event(), BBCStudy::process_event(), PHSimpleKFProp::PropagateTrack(), ActsExamples::prototrackToSeed(), nanoflann::KDTreeSingleIndexAdaptor< Distance, DatasetAdaptor, DIM, IndexType >::radiusSearch(), RecoTracklets(), reduceWithKLDistanceImpl(), Acts::Experimental::MultiLayerSurfacesUpdatorImpl< grid_t, path_generator >::resolveDuplicates(), ActsExamples::RootSimHitReader::RootSimHitReader(), TPCFEETestRecov1::roughZeroSuppression(), TpcPrototypeUnpacker::roughZeroSuppression(), Acts::SeedFinderFTF< external_spacepoint_t >::runGNN_TrackFinder(), trento::DeformedWoodsSaxonNucleus::sample_nucleons_impl(), ActsFatras::Channelizer::segments(), Acts::MeasurementSelector::select(), KFParticleTopoReconstructor::SelectParticleCandidates(), PHG4InttDigitizer::set_adc_scale(), HybridHadronization::set_baryon_id(), HybridHadronization::set_spacetime_for_pythia_hadrons(), ActsExamples::WhiteBoard::similarNames(), EmbRecoMatchContainerv1::sort(), sort_indices(), Acts::GeometryHierarchyMap< value_t >::sortAndCheckDuplicates(), Acts::TrigFTF_GNN_EtaBin< external_spacepoint_t >::sortByPhi(), Acts::sortDetElementsByID(), Acts::Test::MicroBenchmarkResult::sortedRunTimes(), KFParticleTopoReconstructor::SortTracks(), ActsExamples::SpacePointMaker::SpacePointMaker(), SelectorDijetWorker::terminator(), test_random_graph(), Acts::CuboidVolumeBuilder::trackingVolume(), Acts::CylinderVolumeBuilder::trackingVolume(), Acts::TrackingVolumeArrayCreator::trackingVolumeArray(), g4evalfn::unmatchedSvtxTrkIds(), G4Eval::unmatchedSvtxTrkIds(), ActsExamples::CsvMultiTrajectoryWriter::writeT(), and ActsExamples::CKFPerformanceWriter::writeT().