Analysis Software: Acts::LayerArrayCreator Class Reference
Acts::LayerArrayCreator Class Reference
#include <acts/blob/sPHENIX/Core/include/Acts/Geometry/LayerArrayCreator.hpp>
Classes
struct Config
This struct stores the configuration of the tracking geometry.
Public Member Functions
LayerArrayCreator (const Config &, std::unique_ptr< const Logger > logger=getDefaultLogger("LayerArrayCreator", Logging::INFO))
~LayerArrayCreator () override=default
Destructor.
std::unique_ptr< const LayerArray > layerArray (const GeometryContext &gctx, const LayerVector &layersInput, double min, double max, BinningType bType=arbitrary, BinningValue bValue=binX) const override
void setLogger (std::unique_ptr< const Logger > logger)
set logging instance
Public Member Functions inherited from Acts::ILayerArrayCreator
virtual ~ILayerArrayCreator ()=default
Virtual destructor.
Private Member Functions
const Logger & logger () const
Private access method to the logging instance.
std::shared_ptr< Surface > createNavigationSurface (const GeometryContext &gctx, const Layer &layer, BinningValue bValue, double offset) const
Private Attributes
std::unique_ptr< const Logger > m_logger = nullptr
logging instance
Detailed Description
The LayerArrayCreator is a simple Tool that helps to construct LayerArrays from std::vector of Acts::CylinderLayer, Acts::DiscLayer, Acts::PlaneLayer.
It fills the gaps automatically with Acts::NavigationLayer to be processed easily in the Navigation of the Extrapolation process.
Definition at line 34 of file LayerArrayCreator.hpp.
View newest version in sPHENIX GitHub at line 34 of file LayerArrayCreator.hpp
Constructor & Destructor Documentation
Acts::LayerArrayCreator::LayerArrayCreator (const Config & , std::unique_ptr< const Logger > logger = getDefaultLogger("LayerArrayCreator", Logging::INFO)) inline
Constructor
Parameters
logger logging instance
Definition at line 42 of file LayerArrayCreator.hpp.
View newest version in sPHENIX GitHub at line 42 of file LayerArrayCreator.hpp
Acts::LayerArrayCreator::~LayerArrayCreator () override default
Destructor.
Member Function Documentation
std::shared_ptr< Acts::Surface > Acts::LayerArrayCreator::createNavigationSurface (const GeometryContext & gctx, const Layer & layer, BinningValue bValue, double offset) const private
Private helper method for creating a surface for the NavigationLayer, it clones the
Parameters
layer object and thus needs the
gctx geometry context.
bValue is the Binning value for the layer array
offset is the sift for the navigation layer
Definition at line 172 of file LayerArrayCreator.cpp.
View newest version in sPHENIX GitHub at line 172 of file LayerArrayCreator.cpp
References ACTS_WARNING, Acts::binR, Acts::binX, Acts::binY, Acts::binZ, Acts::Surface::bounds(), Acts::Surface::Cylinder, Acts::Surface::Disc, Acts::CylinderBounds::eHalfLengthZ, Acts::CylinderBounds::eR, gctx, Acts::CylinderBounds::get(), offset, Acts::PrimitivesView3DTest::plane, Acts::Surface::Plane, Acts::Layer::surfaceRepresentation(), Acts::Surface::transform(), translation(), and Acts::Surface::type().
Referenced by layerArray().
std::unique_ptr< const Acts::LayerArray > Acts::LayerArrayCreator::layerArray (const GeometryContext & gctx, const LayerVector & layersInput, double min, double max, BinningType bType = arbitrary, BinningValue bValue = binX) const override virtual
LayerArrayCreator interface method
Parameters
gctx is the geometry context for witch the array is built
layersInput are the layers to be moved into an array
min is the minimum value for binning
max is the maximum value for binning
bType is the binning type
bValue is the value in which the binning should be done
Returns
unique pointer to a newly created LayerArray
Implements Acts::ILayerArrayCreator.
Definition at line 31 of file LayerArrayCreator.cpp.
View newest version in sPHENIX GitHub at line 31 of file LayerArrayCreator.cpp
References ACTS_ERROR, Acts::ACTS_VERBOSE(), Acts::arbitrary, Acts::NavigationLayer::create(), createNavigationSurface(), Acts::equidistant, layer, Acts::UnitConstants::min, testing::internal::move(), Acts::open, Acts::Experimental::detail::BlueprintHelper::sort(), ambiguity_solver_full_chain::x, y, and physmon_track_finding_ttbar::z.
Referenced by Acts::CuboidVolumeBuilder::buildVolume(), and Acts::Test::CubicTrackingGeometry::operator()().
const Logger& Acts::LayerArrayCreator::logger () const inline private
Private access method to the logging instance.
Definition at line 72 of file LayerArrayCreator.hpp.
View newest version in sPHENIX GitHub at line 72 of file LayerArrayCreator.hpp
References m_logger.
void Acts::LayerArrayCreator::setLogger (std::unique_ptr< const Logger > logger) inline
set logging instance
Definition at line 66 of file LayerArrayCreator.hpp.
View newest version in sPHENIX GitHub at line 66 of file LayerArrayCreator.hpp
References m_logger, and testing::internal::move().
Member Data Documentation
std::unique_ptr<const Logger> Acts::LayerArrayCreator::m_logger = nullptr private
logging instance
Definition at line 75 of file LayerArrayCreator.hpp.
View newest version in sPHENIX GitHub at line 75 of file LayerArrayCreator.hpp
Referenced by logger(), and setLogger().
The documentation for this class was generated from the following files:
acts/blob/sPHENIX/Core/include/Acts/Geometry/LayerArrayCreator.hpp
acts/blob/sPHENIX/Core/src/Geometry/LayerArrayCreator.cpp