Analysis Software: RawHitSetContainerv1 Class Reference
RawHitSetContainerv1 Class Reference
#include <coresoftware/blob/master/offline/packages/trackbase/RawHitSetContainerv1.h>
Public Member Functions
RawHitSetContainerv1 ()=default
~RawHitSetContainerv1 () override
void Reset () override
PHObject functions.
void identify (std::ostream &=std::cout) const override
ConstIterator addHitSet (RawHitSet *) override
Add a RawHitSet to the container.
ConstIterator addHitSetSpecifyKey (const TrkrDefs::hitsetkey, RawHitSet *) override
void removeHitSet (TrkrDefs::hitsetkey) override
preferred removal method, key is currently the hit id
void removeHitSet (RawHitSet *) override
inefficent, use key where possible instead
Iterator findOrAddHitSet (TrkrDefs::hitsetkey key) override
find or add HitSet
ConstRange getHitSets (const TrkrDefs::TrkrId trackerid) const override
return all HitSets matching a given detid
ConstRange getHitSets (const TrkrDefs::TrkrId trackerid, const uint8_t layer) const override
return all HitSets matching a given detid, layer
ConstRange getHitSets () const override
return all HitSets
RawHitSet * findHitSet (TrkrDefs::hitsetkey key) override
return a given HitSet based on its key
unsigned int size () const override
Public Member Functions inherited from RawHitSetContainer
~RawHitSetContainer () override=default
dtir
Public Member Functions inherited from PHObject
PHObject ()
ctor
~PHObject () override
dtor
virtual PHObject * CloneMe () const
Virtual copy constructor.
virtual PHObject * clone () const final
PHObject * Clone (const char *newname="") const final
void Copy (TObject &object) const final
virtual int isValid () const
isValid returns non zero if object contains vailid data
virtual int Integrate () const
virtual int Integrate (PHObject *)
virtual void CopyFrom (const PHObject *obj)
Private Attributes
Map m_hitmap
Additional Inherited Members
Public Types inherited from RawHitSetContainer
using Map = std::map< TrkrDefs::hitsetkey, RawHitSet * >
using Iterator = Map::iterator
using ConstIterator = Map::const_iterator
using Range = std::pair< Iterator, Iterator >
using ConstRange = std::pair< ConstIterator, ConstIterator >
Protected Member Functions inherited from RawHitSetContainer
RawHitSetContainer ()=default
ctor
Detailed Description
Container for RawHitSet objects
Definition at line 21 of file RawHitSetContainerv1.h.
View newest version in sPHENIX GitHub at line 21 of file RawHitSetContainerv1.h
Constructor & Destructor Documentation
RawHitSetContainerv1::RawHitSetContainerv1 () default
RawHitSetContainerv1::~RawHitSetContainerv1 () inline override
Definition at line 28 of file RawHitSetContainerv1.h.
View newest version in sPHENIX GitHub at line 28 of file RawHitSetContainerv1.h
References Reset().
Member Function Documentation
RawHitSetContainerv1::ConstIterator RawHitSetContainerv1::addHitSet (RawHitSet *) override virtual
Add a RawHitSet to the container.
Reimplemented from RawHitSetContainer.
Definition at line 36 of file RawHitSetContainerv1.cc.
View newest version in sPHENIX GitHub at line 36 of file RawHitSetContainerv1.cc
References addHitSetSpecifyKey(), and RawHitSet::getHitSetKey().
RawHitSetContainerv1::ConstIterator RawHitSetContainerv1::addHitSetSpecifyKey (const TrkrDefs::hitsetkey key, RawHitSet * newhit) override virtual
Reimplemented from RawHitSetContainer.
Definition at line 40 of file RawHitSetContainerv1.cc.
View newest version in sPHENIX GitHub at line 40 of file RawHitSetContainerv1.cc
References m_hitmap.
Referenced by addHitSet().
RawHitSet * RawHitSetContainerv1::findHitSet (TrkrDefs::hitsetkey) override virtual
return a given HitSet based on its key
Reimplemented from RawHitSetContainer.
Definition at line 91 of file RawHitSetContainerv1.cc.
View newest version in sPHENIX GitHub at line 91 of file RawHitSetContainerv1.cc
References it, and m_hitmap.
Referenced by TpcRawWriter::process_event().
RawHitSetContainerv1::Iterator RawHitSetContainerv1::findOrAddHitSet (TrkrDefs::hitsetkey) override virtual
find or add HitSet
Reimplemented from RawHitSetContainer.
Definition at line 79 of file RawHitSetContainerv1.cc.
View newest version in sPHENIX GitHub at line 79 of file RawHitSetContainerv1.cc
References it, and m_hitmap.
Referenced by TpcRawWriter::process_event().
RawHitSetContainerv1::ConstRange RawHitSetContainerv1::getHitSets (const TrkrDefs::TrkrId) const override virtual
return all HitSets matching a given detid
Reimplemented from RawHitSetContainer.
Definition at line 59 of file RawHitSetContainerv1.cc.
View newest version in sPHENIX GitHub at line 59 of file RawHitSetContainerv1.cc
References TrkrDefs::getHitSetKeyHi(), TrkrDefs::getHitSetKeyLo(), and m_hitmap.
RawHitSetContainerv1::ConstRange RawHitSetContainerv1::getHitSets (const TrkrDefs::TrkrId trackerid, const uint8_t layer) const override virtual
return all HitSets matching a given detid, layer
Reimplemented from RawHitSetContainer.
Definition at line 67 of file RawHitSetContainerv1.cc.
View newest version in sPHENIX GitHub at line 67 of file RawHitSetContainerv1.cc
References TrkrDefs::getHitSetKeyHi(), TrkrDefs::getHitSetKeyLo(), and m_hitmap.
RawHitSetContainerv1::ConstRange RawHitSetContainerv1::getHitSets () const override virtual
return all HitSets
Reimplemented from RawHitSetContainer.
Definition at line 75 of file RawHitSetContainerv1.cc.
View newest version in sPHENIX GitHub at line 75 of file RawHitSetContainerv1.cc
References m_hitmap.
void RawHitSetContainerv1::identify (std::ostream & os = std::cout) const override virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from PHObject.
Definition at line 22 of file RawHitSetContainerv1.cc.
View newest version in sPHENIX GitHub at line 22 of file RawHitSetContainerv1.cc
References TrkrDefs::getLayer(), layer, m_hitmap, and size().
void RawHitSetContainerv1::removeHitSet (TrkrDefs::hitsetkey) override virtual
preferred removal method, key is currently the hit id
Reimplemented from RawHitSetContainer.
Definition at line 52 of file RawHitSetContainerv1.cc.
View newest version in sPHENIX GitHub at line 52 of file RawHitSetContainerv1.cc
References m_hitmap.
Referenced by removeHitSet().
void RawHitSetContainerv1::removeHitSet (RawHitSet *) override virtual
inefficent, use key where possible instead
Reimplemented from RawHitSetContainer.
Definition at line 55 of file RawHitSetContainerv1.cc.
View newest version in sPHENIX GitHub at line 55 of file RawHitSetContainerv1.cc
References RawHitSet::getHitSetKey(), and removeHitSet().
void RawHitSetContainerv1::Reset () override virtual
PHObject functions.
Reimplemented from RawHitSetContainer.
Definition at line 14 of file RawHitSetContainerv1.cc.
View newest version in sPHENIX GitHub at line 14 of file RawHitSetContainerv1.cc
References m_hitmap.
Referenced by ~RawHitSetContainerv1().
unsigned int RawHitSetContainerv1::size (void) const inline override virtual
Reimplemented from RawHitSetContainer.
Definition at line 53 of file RawHitSetContainerv1.h.
View newest version in sPHENIX GitHub at line 53 of file RawHitSetContainerv1.h
References m_hitmap.
Referenced by identify().
Member Data Documentation
Map RawHitSetContainerv1::m_hitmap private
Definition at line 58 of file RawHitSetContainerv1.h.
View newest version in sPHENIX GitHub at line 58 of file RawHitSetContainerv1.h
Referenced by addHitSetSpecifyKey(), findHitSet(), findOrAddHitSet(), getHitSets(), identify(), removeHitSet(), Reset(), and size().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/trackbase/RawHitSetContainerv1.h
coresoftware/blob/master/offline/packages/trackbase/RawHitSetContainerv1.cc