Analysis Software: PHG4Showerv1 Class Reference
PHG4Showerv1 Class Reference
#include <coresoftware/blob/master/simulation/g4simulation/g4main/PHG4Showerv1.h>
Public Member Functions
PHG4Showerv1 ()
~PHG4Showerv1 () override
void identify (std::ostream &os=std::cout) const override
PHG4Shower * CloneMe () const override
Virtual copy constructor.
void Reset () override
Clear Event.
int isValid () const override
isValid returns non zero if object contains vailid data
int get_id () const override
void set_id (int id) override
int get_parent_particle_id () const override
void set_parent_particle_id (int parent_particle_id) override
int get_parent_shower_id () const override
void set_parent_shower_id (int parent_shower_id) override
float get_x () const override
void set_x (float x) override
float get_y () const override
void set_y (float y) override
float get_z () const override
void set_z (float z) override
float get_position (unsigned int coor) const override
void set_position (unsigned int coor, float xi) override
float get_covar (unsigned int i, unsigned int j) const override
void set_covar (unsigned int i, unsigned int j, float entry) override
unsigned int get_nhits (int volume) const override
void set_nhits (int volume, unsigned int nhits) override
double get_edep () const override
float get_edep (int volume) const override
void set_edep (int volume, float edep) override
double get_eion () const override
float get_eion (int volume) const override
void set_eion (int volume, float eion) override
float get_light_yield (int volume) const override
void set_light_yield (int volume, float light_yield) override
float get_eh_ratio (int volume) const override
void set_eh_ratio (int volume, float eh_ratio) override
bool empty_g4particle_id () const override
size_t size_g4particle_id () const override
void add_g4particle_id (int id) override
PHG4Shower::ParticleIdIter begin_g4particle_id () override
PHG4Shower::ParticleIdConstIter begin_g4particle_id () const override
PHG4Shower::ParticleIdIter end_g4particle_id () override
PHG4Shower::ParticleIdConstIter end_g4particle_id () const override
size_t remove_g4particle_id (int id) override
void clear_g4particle_id () override
const ParticleIdSet & g4particle_ids () const override
bool empty_g4vertex_id () const override
size_t size_g4vertex_id () const override
void add_g4vertex_id (int id) override
PHG4Shower::VertexIdIter begin_g4vertex_id () override
PHG4Shower::VertexIdConstIter begin_g4vertex_id () const override
PHG4Shower::VertexIdIter end_g4vertex_id () override
PHG4Shower::VertexIdConstIter end_g4vertex_id () const override
size_t remove_g4vertex_id (int id) override
void clear_g4vertex_id () override
const VertexIdSet & g4vertex_ids () const override
bool empty_g4hit_id () const override
size_t size_g4hit_id () const override
void add_g4hit_id (int volume, PHG4HitDefs::keytype id) override
PHG4Shower::HitIdIter begin_g4hit_id () override
PHG4Shower::HitIdConstIter begin_g4hit_id () const override
PHG4Shower::HitIdIter find_g4hit_id (int volume) override
PHG4Shower::HitIdConstIter find_g4hit_id (int volume) const override
PHG4Shower::HitIdIter end_g4hit_id () override
PHG4Shower::HitIdConstIter end_g4hit_id () const override
size_t remove_g4hit_id (int volume, PHG4HitDefs::keytype id) override
size_t remove_g4hit_volume (int volume) override
void clear_g4hit_id () override
const HitIdMap & g4hit_ids () const override
Public Member Functions inherited from PHG4Shower
~PHG4Shower () override
Public Member Functions inherited from PHObject
PHObject ()
ctor
~PHObject () override
dtor
virtual PHObject * clone () const final
PHObject * Clone (const char *newname="") const final
void Copy (TObject &object) const final
virtual int Integrate () const
virtual int Integrate (PHObject *)
virtual void CopyFrom (const PHObject *obj)
Private Member Functions
unsigned int covar_index (unsigned int i, unsigned int j) const
ClassDefOverride (PHG4Showerv1, 1)
Private Attributes
int _id
int _parent_particle_id
int _parent_shower_id
float _pos [3]
float _covar [6]
std::map< int, unsigned int > _nhits
std::map< int, float > _edep
std::map< int, float > _eion
std::map< int, float > _light_yield
std::map< int, float > _eh_ratio
ParticleIdSet _g4particle_ids
VertexIdSet _g4vertex_ids
HitIdMap _g4hit_ids
Additional Inherited Members
Public Types inherited from PHG4Shower
typedef std::set< int > ParticleIdSet
typedef ParticleIdSet::iterator ParticleIdIter
typedef
ParticleIdSet::const_iterator ParticleIdConstIter
typedef std::set< int > VertexIdSet
typedef VertexIdSet::iterator VertexIdIter
typedef VertexIdSet::const_iterator VertexIdConstIter
typedef std::map< int,
std::set< PHG4HitDefs::keytype > > HitIdMap
typedef HitIdMap::iterator HitIdIter
typedef HitIdMap::const_iterator HitIdConstIter
Protected Member Functions inherited from PHG4Shower
PHG4Shower ()
Detailed Description
Definition at line 15 of file PHG4Showerv1.h.
View newest version in sPHENIX GitHub at line 15 of file PHG4Showerv1.h
Constructor & Destructor Documentation
PHG4Showerv1::PHG4Showerv1 ()
Definition at line 13 of file PHG4Showerv1.cc.
View newest version in sPHENIX GitHub at line 13 of file PHG4Showerv1.cc
References _covar, _pos, parse_cmake_options::begin, and end.
Referenced by CloneMe(), and Reset().
PHG4Showerv1::~PHG4Showerv1 () inline override
Definition at line 19 of file PHG4Showerv1.h.
View newest version in sPHENIX GitHub at line 19 of file PHG4Showerv1.h
Member Function Documentation
void PHG4Showerv1::add_g4hit_id (int volume, PHG4HitDefs::keytype id) inline override virtual
Reimplemented from PHG4Shower.
Definition at line 96 of file PHG4Showerv1.h.
View newest version in sPHENIX GitHub at line 96 of file PHG4Showerv1.h
References _g4hit_ids.
void PHG4Showerv1::add_g4particle_id (int id) inline override virtual
Reimplemented from PHG4Shower.
Definition at line 74 of file PHG4Showerv1.h.
View newest version in sPHENIX GitHub at line 74 of file PHG4Showerv1.h
References _g4particle_ids.
void PHG4Showerv1::add_g4vertex_id (int id) inline override virtual
Reimplemented from PHG4Shower.
Definition at line 85 of file PHG4Showerv1.h.
View newest version in sPHENIX GitHub at line 85 of file PHG4Showerv1.h
References _g4vertex_ids.
PHG4Shower::HitIdIter PHG4Showerv1::begin_g4hit_id () inline override virtual
Reimplemented from PHG4Shower.
Definition at line 97 of file PHG4Showerv1.h.
View newest version in sPHENIX GitHub at line 97 of file PHG4Showerv1.h
References _g4hit_ids.
PHG4Shower::HitIdConstIter PHG4Showerv1::begin_g4hit_id () const inline override virtual
Reimplemented from PHG4Shower.
Definition at line 98 of file PHG4Showerv1.h.
View newest version in sPHENIX GitHub at line 98 of file PHG4Showerv1.h
References _g4hit_ids.
PHG4Shower::ParticleIdIter PHG4Showerv1::begin_g4particle_id () inline override virtual
Reimplemented from PHG4Shower.
Definition at line 75 of file PHG4Showerv1.h.
View newest version in sPHENIX GitHub at line 75 of file PHG4Showerv1.h
References _g4particle_ids.
PHG4Shower::ParticleIdConstIter PHG4Showerv1::begin_g4particle_id () const inline override virtual
Reimplemented from PHG4Shower.
Definition at line 76 of file PHG4Showerv1.h.
View newest version in sPHENIX GitHub at line 76 of file PHG4Showerv1.h
References _g4particle_ids.
PHG4Shower::VertexIdIter PHG4Showerv1::begin_g4vertex_id () inline override virtual
Reimplemented from PHG4Shower.
Definition at line 86 of file PHG4Showerv1.h.
View newest version in sPHENIX GitHub at line 86 of file PHG4Showerv1.h
References _g4vertex_ids.
PHG4Shower::VertexIdConstIter PHG4Showerv1::begin_g4vertex_id () const inline override virtual
Reimplemented from PHG4Shower.
Definition at line 87 of file PHG4Showerv1.h.
View newest version in sPHENIX GitHub at line 87 of file PHG4Showerv1.h
References _g4vertex_ids.
PHG4Showerv1::ClassDefOverride (PHG4Showerv1 , 1) private
void PHG4Showerv1::clear_g4hit_id () inline override virtual
Reimplemented from PHG4Shower.
Definition at line 105 of file PHG4Showerv1.h.
View newest version in sPHENIX GitHub at line 105 of file PHG4Showerv1.h
References _g4hit_ids.
void PHG4Showerv1::clear_g4particle_id () inline override virtual
Reimplemented from PHG4Shower.
Definition at line 80 of file PHG4Showerv1.h.
View newest version in sPHENIX GitHub at line 80 of file PHG4Showerv1.h
References _g4particle_ids.
void PHG4Showerv1::clear_g4vertex_id () inline override virtual
Reimplemented from PHG4Shower.
Definition at line 91 of file PHG4Showerv1.h.
View newest version in sPHENIX GitHub at line 91 of file PHG4Showerv1.h
References _g4vertex_ids.
PHG4Shower* PHG4Showerv1::CloneMe () const inline override virtual
Virtual copy constructor.
Reimplemented from PHG4Shower.
Definition at line 24 of file PHG4Showerv1.h.
View newest version in sPHENIX GitHub at line 24 of file PHG4Showerv1.h
References PHG4Showerv1().
unsigned int PHG4Showerv1::covar_index (unsigned int i, unsigned int j) const private
Definition at line 122 of file PHG4Showerv1.cc.
View newest version in sPHENIX GitHub at line 122 of file PHG4Showerv1.cc
References swap().
Referenced by get_covar(), and set_covar().
bool PHG4Showerv1::empty_g4hit_id () const inline override virtual
Reimplemented from PHG4Shower.
Definition at line 94 of file PHG4Showerv1.h.
View newest version in sPHENIX GitHub at line 94 of file PHG4Showerv1.h
References _g4hit_ids.
bool PHG4Showerv1::empty_g4particle_id () const inline override virtual
Reimplemented from PHG4Shower.
Definition at line 72 of file PHG4Showerv1.h.
View newest version in sPHENIX GitHub at line 72 of file PHG4Showerv1.h
References _g4particle_ids.
bool PHG4Showerv1::empty_g4vertex_id () const inline override virtual
Reimplemented from PHG4Shower.
Definition at line 83 of file PHG4Showerv1.h.
View newest version in sPHENIX GitHub at line 83 of file PHG4Showerv1.h
References _g4vertex_ids.
PHG4Shower::HitIdIter PHG4Showerv1::end_g4hit_id () inline override virtual
Reimplemented from PHG4Shower.
Definition at line 101 of file PHG4Showerv1.h.
View newest version in sPHENIX GitHub at line 101 of file PHG4Showerv1.h
References _g4hit_ids.
PHG4Shower::HitIdConstIter PHG4Showerv1::end_g4hit_id () const inline override virtual
Reimplemented from PHG4Shower.
Definition at line 102 of file PHG4Showerv1.h.
View newest version in sPHENIX GitHub at line 102 of file PHG4Showerv1.h
References _g4hit_ids.
PHG4Shower::ParticleIdIter PHG4Showerv1::end_g4particle_id () inline override virtual
Reimplemented from PHG4Shower.
Definition at line 77 of file PHG4Showerv1.h.
View newest version in sPHENIX GitHub at line 77 of file PHG4Showerv1.h
References _g4particle_ids.
PHG4Shower::ParticleIdConstIter PHG4Showerv1::end_g4particle_id () const inline override virtual
Reimplemented from PHG4Shower.
Definition at line 78 of file PHG4Showerv1.h.
View newest version in sPHENIX GitHub at line 78 of file PHG4Showerv1.h
References _g4particle_ids.
PHG4Shower::VertexIdIter PHG4Showerv1::end_g4vertex_id () inline override virtual
Reimplemented from PHG4Shower.
Definition at line 88 of file PHG4Showerv1.h.
View newest version in sPHENIX GitHub at line 88 of file PHG4Showerv1.h
References _g4vertex_ids.
PHG4Shower::VertexIdConstIter PHG4Showerv1::end_g4vertex_id () const inline override virtual
Reimplemented from PHG4Shower.
Definition at line 89 of file PHG4Showerv1.h.
View newest version in sPHENIX GitHub at line 89 of file PHG4Showerv1.h
References _g4vertex_ids.
PHG4Shower::HitIdIter PHG4Showerv1::find_g4hit_id (int volume) inline override virtual
Reimplemented from PHG4Shower.
Definition at line 99 of file PHG4Showerv1.h.
View newest version in sPHENIX GitHub at line 99 of file PHG4Showerv1.h
References _g4hit_ids.
PHG4Shower::HitIdConstIter PHG4Showerv1::find_g4hit_id (int volume) const inline override virtual
Reimplemented from PHG4Shower.
Definition at line 100 of file PHG4Showerv1.h.
View newest version in sPHENIX GitHub at line 100 of file PHG4Showerv1.h
References _g4hit_ids.
const HitIdMap& PHG4Showerv1::g4hit_ids () const inline override virtual
Implements PHG4Shower.
Definition at line 106 of file PHG4Showerv1.h.
View newest version in sPHENIX GitHub at line 106 of file PHG4Showerv1.h
References _g4hit_ids.
const ParticleIdSet& PHG4Showerv1::g4particle_ids () const inline override virtual
Implements PHG4Shower.
Definition at line 81 of file PHG4Showerv1.h.
View newest version in sPHENIX GitHub at line 81 of file PHG4Showerv1.h
References _g4particle_ids.
const VertexIdSet& PHG4Showerv1::g4vertex_ids () const inline override virtual
Implements PHG4Shower.
Definition at line 92 of file PHG4Showerv1.h.
View newest version in sPHENIX GitHub at line 92 of file PHG4Showerv1.h
References _g4vertex_ids.
float PHG4Showerv1::get_covar (unsigned int i, unsigned int j) const override virtual
Reimplemented from PHG4Shower.
Definition at line 117 of file PHG4Showerv1.cc.
View newest version in sPHENIX GitHub at line 117 of file PHG4Showerv1.cc
References _covar, and covar_index().
Referenced by identify(), and isValid().
double PHG4Showerv1::get_edep () const override virtual
Reimplemented from PHG4Shower.
Definition at line 147 of file PHG4Showerv1.cc.
View newest version in sPHENIX GitHub at line 147 of file PHG4Showerv1.cc
References _edep, and sum().
Referenced by identify().
float PHG4Showerv1::get_edep (int volume) const override virtual
Reimplemented from PHG4Shower.
Definition at line 138 of file PHG4Showerv1.cc.
View newest version in sPHENIX GitHub at line 138 of file PHG4Showerv1.cc
References _edep.
float PHG4Showerv1::get_eh_ratio (int volume) const override virtual
Reimplemented from PHG4Shower.
Definition at line 185 of file PHG4Showerv1.cc.
View newest version in sPHENIX GitHub at line 185 of file PHG4Showerv1.cc
References _eh_ratio.
double PHG4Showerv1::get_eion () const override virtual
Reimplemented from PHG4Shower.
Definition at line 166 of file PHG4Showerv1.cc.
View newest version in sPHENIX GitHub at line 166 of file PHG4Showerv1.cc
References _eion, and sum().
Referenced by identify().
float PHG4Showerv1::get_eion (int volume) const override virtual
Reimplemented from PHG4Shower.
Definition at line 157 of file PHG4Showerv1.cc.
View newest version in sPHENIX GitHub at line 157 of file PHG4Showerv1.cc
References _eion.
int PHG4Showerv1::get_id () const inline override virtual
Reimplemented from PHG4Shower.
Definition at line 30 of file PHG4Showerv1.h.
View newest version in sPHENIX GitHub at line 30 of file PHG4Showerv1.h
References _id.
Referenced by identify().
float PHG4Showerv1::get_light_yield (int volume) const override virtual
Reimplemented from PHG4Shower.
Definition at line 176 of file PHG4Showerv1.cc.
View newest version in sPHENIX GitHub at line 176 of file PHG4Showerv1.cc
References _light_yield.
Referenced by identify().
unsigned int PHG4Showerv1::get_nhits (int volume) const override virtual
Reimplemented from PHG4Shower.
Definition at line 129 of file PHG4Showerv1.cc.
View newest version in sPHENIX GitHub at line 129 of file PHG4Showerv1.cc
References _nhits.
int PHG4Showerv1::get_parent_particle_id () const inline override virtual
Reimplemented from PHG4Shower.
Definition at line 33 of file PHG4Showerv1.h.
View newest version in sPHENIX GitHub at line 33 of file PHG4Showerv1.h
References _parent_particle_id.
Referenced by identify().
int PHG4Showerv1::get_parent_shower_id () const inline override virtual
Reimplemented from PHG4Shower.
Definition at line 36 of file PHG4Showerv1.h.
View newest version in sPHENIX GitHub at line 36 of file PHG4Showerv1.h
References _parent_shower_id.
Referenced by identify().
float PHG4Showerv1::get_position (unsigned int coor) const inline override virtual
Reimplemented from PHG4Shower.
Definition at line 48 of file PHG4Showerv1.h.
View newest version in sPHENIX GitHub at line 48 of file PHG4Showerv1.h
References _pos.
float PHG4Showerv1::get_x () const inline override virtual
Reimplemented from PHG4Shower.
Definition at line 39 of file PHG4Showerv1.h.
View newest version in sPHENIX GitHub at line 39 of file PHG4Showerv1.h
References _pos.
Referenced by identify().
float PHG4Showerv1::get_y () const inline override virtual
Reimplemented from PHG4Shower.
Definition at line 42 of file PHG4Showerv1.h.
View newest version in sPHENIX GitHub at line 42 of file PHG4Showerv1.h
References _pos.
Referenced by identify().
float PHG4Showerv1::get_z () const inline override virtual
Reimplemented from PHG4Shower.
Definition at line 45 of file PHG4Showerv1.h.
View newest version in sPHENIX GitHub at line 45 of file PHG4Showerv1.h
References _pos.
Referenced by identify().
void PHG4Showerv1::identify (std::ostream & os = std::cout) const override virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from PHG4Shower.
Definition at line 32 of file PHG4Showerv1.cc.
View newest version in sPHENIX GitHub at line 32 of file PHG4Showerv1.cc
References _edep, _g4hit_ids, _g4particle_ids, get_covar(), get_edep(), get_eion(), get_id(), get_light_yield(), get_parent_particle_id(), get_parent_shower_id(), get_x(), get_y(), and get_z().
int PHG4Showerv1::isValid () const override virtual
isValid returns non zero if object contains vailid data
Reimplemented from PHG4Shower.
Definition at line 91 of file PHG4Showerv1.cc.
View newest version in sPHENIX GitHub at line 91 of file PHG4Showerv1.cc
References _id, _pos, get_covar(), i, and j.
size_t PHG4Showerv1::remove_g4hit_id (int volume, PHG4HitDefs::keytype id) inline override virtual
Reimplemented from PHG4Shower.
Definition at line 103 of file PHG4Showerv1.h.
View newest version in sPHENIX GitHub at line 103 of file PHG4Showerv1.h
References _g4hit_ids.
size_t PHG4Showerv1::remove_g4hit_volume (int volume) inline override virtual
Reimplemented from PHG4Shower.
Definition at line 104 of file PHG4Showerv1.h.
View newest version in sPHENIX GitHub at line 104 of file PHG4Showerv1.h
References _g4hit_ids.
size_t PHG4Showerv1::remove_g4particle_id (int id) inline override virtual
Reimplemented from PHG4Shower.
Definition at line 79 of file PHG4Showerv1.h.
View newest version in sPHENIX GitHub at line 79 of file PHG4Showerv1.h
References _g4particle_ids.
size_t PHG4Showerv1::remove_g4vertex_id (int id) inline override virtual
Reimplemented from PHG4Shower.
Definition at line 90 of file PHG4Showerv1.h.
View newest version in sPHENIX GitHub at line 90 of file PHG4Showerv1.h
References _g4vertex_ids.
void PHG4Showerv1::Reset () inline override virtual
Clear Event.
Reimplemented from PHG4Shower.
Definition at line 25 of file PHG4Showerv1.h.
View newest version in sPHENIX GitHub at line 25 of file PHG4Showerv1.h
References PHG4Showerv1().
void PHG4Showerv1::set_covar (unsigned int i, unsigned int j, float entry) override virtual
Reimplemented from PHG4Shower.
Definition at line 111 of file PHG4Showerv1.cc.
View newest version in sPHENIX GitHub at line 111 of file PHG4Showerv1.cc
References _covar, covar_index(), and value.
void PHG4Showerv1::set_edep (int volume, float edep) inline override virtual
Reimplemented from PHG4Shower.
Definition at line 59 of file PHG4Showerv1.h.
View newest version in sPHENIX GitHub at line 59 of file PHG4Showerv1.h
References _edep.
void PHG4Showerv1::set_eh_ratio (int volume, float eh_ratio) inline override virtual
Reimplemented from PHG4Shower.
Definition at line 69 of file PHG4Showerv1.h.
View newest version in sPHENIX GitHub at line 69 of file PHG4Showerv1.h
References _eh_ratio.
void PHG4Showerv1::set_eion (int volume, float eion) inline override virtual
Reimplemented from PHG4Shower.
Definition at line 63 of file PHG4Showerv1.h.
View newest version in sPHENIX GitHub at line 63 of file PHG4Showerv1.h
References _eion.
void PHG4Showerv1::set_id (int id) inline override virtual
Reimplemented from PHG4Shower.
Definition at line 31 of file PHG4Showerv1.h.
View newest version in sPHENIX GitHub at line 31 of file PHG4Showerv1.h
References _id, and train_ambiguity_solver::id.
Referenced by PHG4TruthTrackingAction::PreUserTrackingAction().
void PHG4Showerv1::set_light_yield (int volume, float light_yield) inline override virtual
Reimplemented from PHG4Shower.
Definition at line 66 of file PHG4Showerv1.h.
View newest version in sPHENIX GitHub at line 66 of file PHG4Showerv1.h
References _light_yield.
void PHG4Showerv1::set_nhits (int volume, unsigned int nhits) inline override virtual
Reimplemented from PHG4Shower.
Definition at line 55 of file PHG4Showerv1.h.
View newest version in sPHENIX GitHub at line 55 of file PHG4Showerv1.h
References _nhits.
void PHG4Showerv1::set_parent_particle_id (int parent_particle_id) inline override virtual
Reimplemented from PHG4Shower.
Definition at line 34 of file PHG4Showerv1.h.
View newest version in sPHENIX GitHub at line 34 of file PHG4Showerv1.h
References _parent_particle_id.
Referenced by PHG4TruthTrackingAction::PreUserTrackingAction().
void PHG4Showerv1::set_parent_shower_id (int parent_shower_id) inline override virtual
Reimplemented from PHG4Shower.
Definition at line 37 of file PHG4Showerv1.h.
View newest version in sPHENIX GitHub at line 37 of file PHG4Showerv1.h
References _parent_shower_id.
Referenced by PHG4TruthTrackingAction::PreUserTrackingAction().
void PHG4Showerv1::set_position (unsigned int coor, float xi) inline override virtual
Reimplemented from PHG4Shower.
Definition at line 49 of file PHG4Showerv1.h.
View newest version in sPHENIX GitHub at line 49 of file PHG4Showerv1.h
References _pos.
void PHG4Showerv1::set_x (float x) inline override virtual
Reimplemented from PHG4Shower.
Definition at line 40 of file PHG4Showerv1.h.
View newest version in sPHENIX GitHub at line 40 of file PHG4Showerv1.h
References _pos, and ambiguity_solver_full_chain::x.
void PHG4Showerv1::set_y (float y) inline override virtual
Reimplemented from PHG4Shower.
Definition at line 43 of file PHG4Showerv1.h.
View newest version in sPHENIX GitHub at line 43 of file PHG4Showerv1.h
References _pos, and y.
void PHG4Showerv1::set_z (float z) inline override virtual
Reimplemented from PHG4Shower.
Definition at line 46 of file PHG4Showerv1.h.
View newest version in sPHENIX GitHub at line 46 of file PHG4Showerv1.h
References _pos, and physmon_track_finding_ttbar::z.
size_t PHG4Showerv1::size_g4hit_id () const inline override virtual
Reimplemented from PHG4Shower.
Definition at line 95 of file PHG4Showerv1.h.
View newest version in sPHENIX GitHub at line 95 of file PHG4Showerv1.h
References _g4hit_ids.
size_t PHG4Showerv1::size_g4particle_id () const inline override virtual
Reimplemented from PHG4Shower.
Definition at line 73 of file PHG4Showerv1.h.
View newest version in sPHENIX GitHub at line 73 of file PHG4Showerv1.h
References _g4particle_ids.
size_t PHG4Showerv1::size_g4vertex_id () const inline override virtual
Reimplemented from PHG4Shower.
Definition at line 84 of file PHG4Showerv1.h.
View newest version in sPHENIX GitHub at line 84 of file PHG4Showerv1.h
References _g4vertex_ids.
Member Data Documentation
float PHG4Showerv1::_covar[6] private
Definition at line 115 of file PHG4Showerv1.h.
View newest version in sPHENIX GitHub at line 115 of file PHG4Showerv1.h
Referenced by get_covar(), PHG4Showerv1(), and set_covar().
std::map<int, float> PHG4Showerv1::_edep private
Definition at line 117 of file PHG4Showerv1.h.
View newest version in sPHENIX GitHub at line 117 of file PHG4Showerv1.h
Referenced by get_edep(), identify(), and set_edep().
std::map<int, float> PHG4Showerv1::_eh_ratio private
Definition at line 120 of file PHG4Showerv1.h.
View newest version in sPHENIX GitHub at line 120 of file PHG4Showerv1.h
Referenced by get_eh_ratio(), and set_eh_ratio().
std::map<int, float> PHG4Showerv1::_eion private
Definition at line 118 of file PHG4Showerv1.h.
View newest version in sPHENIX GitHub at line 118 of file PHG4Showerv1.h
Referenced by get_eion(), and set_eion().
HitIdMap PHG4Showerv1::_g4hit_ids private
Definition at line 125 of file PHG4Showerv1.h.
View newest version in sPHENIX GitHub at line 125 of file PHG4Showerv1.h
Referenced by add_g4hit_id(), begin_g4hit_id(), clear_g4hit_id(), empty_g4hit_id(), end_g4hit_id(), find_g4hit_id(), g4hit_ids(), identify(), remove_g4hit_id(), remove_g4hit_volume(), and size_g4hit_id().
ParticleIdSet PHG4Showerv1::_g4particle_ids private
Definition at line 123 of file PHG4Showerv1.h.
View newest version in sPHENIX GitHub at line 123 of file PHG4Showerv1.h
Referenced by add_g4particle_id(), begin_g4particle_id(), clear_g4particle_id(), empty_g4particle_id(), end_g4particle_id(), g4particle_ids(), identify(), remove_g4particle_id(), and size_g4particle_id().
VertexIdSet PHG4Showerv1::_g4vertex_ids private
Definition at line 124 of file PHG4Showerv1.h.
View newest version in sPHENIX GitHub at line 124 of file PHG4Showerv1.h
Referenced by add_g4vertex_id(), begin_g4vertex_id(), clear_g4vertex_id(), empty_g4vertex_id(), end_g4vertex_id(), g4vertex_ids(), remove_g4vertex_id(), and size_g4vertex_id().
int PHG4Showerv1::_id private
Definition at line 111 of file PHG4Showerv1.h.
View newest version in sPHENIX GitHub at line 111 of file PHG4Showerv1.h
Referenced by get_id(), isValid(), and set_id().
std::map<int, float> PHG4Showerv1::_light_yield private
Definition at line 119 of file PHG4Showerv1.h.
View newest version in sPHENIX GitHub at line 119 of file PHG4Showerv1.h
Referenced by get_light_yield(), and set_light_yield().
std::map<int, unsigned int> PHG4Showerv1::_nhits private
Definition at line 116 of file PHG4Showerv1.h.
View newest version in sPHENIX GitHub at line 116 of file PHG4Showerv1.h
Referenced by get_nhits(), and set_nhits().
int PHG4Showerv1::_parent_particle_id private
Definition at line 112 of file PHG4Showerv1.h.
View newest version in sPHENIX GitHub at line 112 of file PHG4Showerv1.h
Referenced by get_parent_particle_id(), and set_parent_particle_id().
int PHG4Showerv1::_parent_shower_id private
Definition at line 113 of file PHG4Showerv1.h.
View newest version in sPHENIX GitHub at line 113 of file PHG4Showerv1.h
Referenced by get_parent_shower_id(), and set_parent_shower_id().
float PHG4Showerv1::_pos[3] private
Definition at line 114 of file PHG4Showerv1.h.
View newest version in sPHENIX GitHub at line 114 of file PHG4Showerv1.h
Referenced by get_position(), get_x(), get_y(), get_z(), isValid(), PHG4Showerv1(), set_position(), set_x(), set_y(), and set_z().
The documentation for this class was generated from the following files:
coresoftware/blob/master/simulation/g4simulation/g4main/PHG4Showerv1.h
coresoftware/blob/master/simulation/g4simulation/g4main/PHG4Showerv1.cc