Analysis Software: TrigFTF_GNN_TrackingFilter< external_spacepoint_t > Class Template Reference
TrigFTF_GNN_TrackingFilter< external_spacepoint_t > Class Template Reference
#include <acts/blob/sPHENIX/Core/include/Acts/Seeding/GNN_TrackingFilter.hpp>
Public Member Functions
TrigFTF_GNN_TrackingFilter (const std::vector< Acts::TrigInDetSiLayer > &g, std::vector< Acts::TrigFTF_GNN_Edge< external_spacepoint_t >> &sb)
void followTrack (Acts::TrigFTF_GNN_Edge< external_spacepoint_t > *pS, TrigFTF_GNN_EdgeState< external_spacepoint_t > &output)
Protected Member Functions
void propagate (Acts::TrigFTF_GNN_Edge< external_spacepoint_t > *pS, TrigFTF_GNN_EdgeState< external_spacepoint_t > &ts)
bool update (Acts::TrigFTF_GNN_Edge< external_spacepoint_t > *pS, TrigFTF_GNN_EdgeState< external_spacepoint_t > &ts)
int getLayerType (int l)
Protected Attributes
const std::vector
< Acts::TrigInDetSiLayer > & m_geo
std::vector
< Acts::TrigFTF_GNN_Edge
< external_spacepoint_t > > & m_segStore
std::vector
< TrigFTF_GNN_EdgeState
< external_spacepoint_t > * > m_stateVec
TrigFTF_GNN_EdgeState
< external_spacepoint_t > m_stateStore [MAX_EDGE_STATE]
int m_globalStateCounter {0}
Detailed Description
template<typename external_spacepoint_t>
class TrigFTF_GNN_TrackingFilter< external_spacepoint_t >
Definition at line 112 of file GNN_TrackingFilter.hpp.
View newest version in sPHENIX GitHub at line 112 of file GNN_TrackingFilter.hpp
Constructor & Destructor Documentation
template<typename external_spacepoint_t> TrigFTF_GNN_TrackingFilter< external_spacepoint_t >::TrigFTF_GNN_TrackingFilter (const std::vector< Acts::TrigInDetSiLayer > & g, std::vector< Acts::TrigFTF_GNN_Edge< external_spacepoint_t >> & sb) inline
Definition at line 114 of file GNN_TrackingFilter.hpp.
View newest version in sPHENIX GitHub at line 114 of file GNN_TrackingFilter.hpp
Member Function Documentation
template<typename external_spacepoint_t> void TrigFTF_GNN_TrackingFilter< external_spacepoint_t >::followTrack (Acts::TrigFTF_GNN_Edge< external_spacepoint_t > * pS, TrigFTF_GNN_EdgeState< external_spacepoint_t > & output) inline
Definition at line 119 of file GNN_TrackingFilter.hpp.
View newest version in sPHENIX GitHub at line 119 of file GNN_TrackingFilter.hpp
References TrigFTF_GNN_EdgeState< external_spacepoint_t >::clone(), Compare(), TrigFTF_GNN_EdgeState< external_spacepoint_t >::initialize(), TrigFTF_GNN_TrackingFilter< external_spacepoint_t >::m_globalStateCounter, Acts::TrigFTF_GNN_Edge< space_point_t >::m_level, TrigFTF_GNN_TrackingFilter< external_spacepoint_t >::m_stateStore, TrigFTF_GNN_TrackingFilter< external_spacepoint_t >::m_stateVec, TrigFTF_GNN_TrackingFilter< external_spacepoint_t >::propagate(), and Acts::Experimental::detail::BlueprintHelper::sort().
Referenced by Acts::SeedFinderFTF< external_spacepoint_t >::runGNN_TrackFinder().
template<typename external_spacepoint_t> int TrigFTF_GNN_TrackingFilter< external_spacepoint_t >::getLayerType (int l) inline protected
Definition at line 368 of file GNN_TrackingFilter.hpp.
View newest version in sPHENIX GitHub at line 368 of file GNN_TrackingFilter.hpp
References distance(), index, TrigFTF_GNN_TrackingFilter< external_spacepoint_t >::m_geo, and n.
Referenced by TrigFTF_GNN_TrackingFilter< external_spacepoint_t >::update().
template<typename external_spacepoint_t> void TrigFTF_GNN_TrackingFilter< external_spacepoint_t >::propagate (Acts::TrigFTF_GNN_Edge< external_spacepoint_t > * pS, TrigFTF_GNN_EdgeState< external_spacepoint_t > & ts) inline protected
Definition at line 153 of file GNN_TrackingFilter.hpp.
View newest version in sPHENIX GitHub at line 153 of file GNN_TrackingFilter.hpp
References TrigFTF_GNN_EdgeState< external_spacepoint_t >::clone(), physmon_simulation::level, TrigFTF_GNN_TrackingFilter< external_spacepoint_t >::m_globalStateCounter, TrigFTF_GNN_EdgeState< external_spacepoint_t >::m_J, Acts::TrigFTF_GNN_Edge< space_point_t >::m_level, Acts::TrigFTF_GNN_Edge< space_point_t >::m_nNei, TrigFTF_GNN_TrackingFilter< external_spacepoint_t >::m_segStore, TrigFTF_GNN_TrackingFilter< external_spacepoint_t >::m_stateStore, TrigFTF_GNN_TrackingFilter< external_spacepoint_t >::m_stateVec, Acts::TrigFTF_GNN_Edge< space_point_t >::m_vNei, TrigFTF_GNN_EdgeState< external_spacepoint_t >::m_vs, MAX_EDGE_STATE, merge_hashes::p, and TrigFTF_GNN_TrackingFilter< external_spacepoint_t >::update().
Referenced by TrigFTF_GNN_TrackingFilter< external_spacepoint_t >::followTrack().
template<typename external_spacepoint_t> bool TrigFTF_GNN_TrackingFilter< external_spacepoint_t >::update (Acts::TrigFTF_GNN_Edge< external_spacepoint_t > * pS, TrigFTF_GNN_EdgeState< external_spacepoint_t > & ts) inline protected
Definition at line 219 of file GNN_TrackingFilter.hpp.
View newest version in sPHENIX GitHub at line 219 of file GNN_TrackingFilter.hpp
References A, Acts::FTF_SP< space_point_t >::combined_ID, TrigFTF_GNN_TrackingFilter< external_spacepoint_t >::getLayerType(), i, j, TrigFTF_GNN_EdgeState< external_spacepoint_t >::m_c, TrigFTF_GNN_EdgeState< external_spacepoint_t >::m_Cx, TrigFTF_GNN_EdgeState< external_spacepoint_t >::m_Cy, TrigFTF_GNN_EdgeState< external_spacepoint_t >::m_J, Acts::TrigFTF_GNN_Edge< space_point_t >::m_n1, TrigFTF_GNN_EdgeState< external_spacepoint_t >::m_refX, TrigFTF_GNN_EdgeState< external_spacepoint_t >::m_refY, TrigFTF_GNN_EdgeState< external_spacepoint_t >::m_s, Acts::TrigFTF_GNN_Node< space_point_t >::m_sp_FTF, TrigFTF_GNN_EdgeState< external_spacepoint_t >::m_X, TrigFTF_GNN_EdgeState< external_spacepoint_t >::m_Y, physmon_track_finding_ttbar::r, Acts::FTF_SP< space_point_t >::SP, ambiguity_solver_full_chain::t2, parse_cmake_options::type, TauVsDIS_MachineLearning_Differentiation::X, ambiguity_solver_full_chain::x, y, TauVsDIS_MachineLearning_Differentiation::Y, and physmon_track_finding_ttbar::z.
Referenced by TrigFTF_GNN_TrackingFilter< external_spacepoint_t >::propagate().
Member Data Documentation
template<typename external_spacepoint_t> const std::vector<Acts::TrigInDetSiLayer>& TrigFTF_GNN_TrackingFilter< external_spacepoint_t >::m_geo protected
Definition at line 377 of file GNN_TrackingFilter.hpp.
View newest version in sPHENIX GitHub at line 377 of file GNN_TrackingFilter.hpp
Referenced by TrigFTF_GNN_TrackingFilter< external_spacepoint_t >::getLayerType().
template<typename external_spacepoint_t> int TrigFTF_GNN_TrackingFilter< external_spacepoint_t >::m_globalStateCounter {0} protected
Definition at line 385 of file GNN_TrackingFilter.hpp.
View newest version in sPHENIX GitHub at line 385 of file GNN_TrackingFilter.hpp
Referenced by TrigFTF_GNN_TrackingFilter< external_spacepoint_t >::followTrack(), and TrigFTF_GNN_TrackingFilter< external_spacepoint_t >::propagate().
template<typename external_spacepoint_t> std::vector<Acts::TrigFTF_GNN_Edge<external_spacepoint_t> >& TrigFTF_GNN_TrackingFilter< external_spacepoint_t >::m_segStore protected
Definition at line 379 of file GNN_TrackingFilter.hpp.
View newest version in sPHENIX GitHub at line 379 of file GNN_TrackingFilter.hpp
Referenced by TrigFTF_GNN_TrackingFilter< external_spacepoint_t >::propagate().
template<typename external_spacepoint_t> TrigFTF_GNN_EdgeState<external_spacepoint_t> TrigFTF_GNN_TrackingFilter< external_spacepoint_t >::m_stateStore[MAX_EDGE_STATE] protected
Definition at line 383 of file GNN_TrackingFilter.hpp.
View newest version in sPHENIX GitHub at line 383 of file GNN_TrackingFilter.hpp
Referenced by TrigFTF_GNN_TrackingFilter< external_spacepoint_t >::followTrack(), and TrigFTF_GNN_TrackingFilter< external_spacepoint_t >::propagate().
template<typename external_spacepoint_t> std::vector<TrigFTF_GNN_EdgeState<external_spacepoint_t>*> TrigFTF_GNN_TrackingFilter< external_spacepoint_t >::m_stateVec protected
Definition at line 381 of file GNN_TrackingFilter.hpp.
View newest version in sPHENIX GitHub at line 381 of file GNN_TrackingFilter.hpp
Referenced by TrigFTF_GNN_TrackingFilter< external_spacepoint_t >::followTrack(), and TrigFTF_GNN_TrackingFilter< external_spacepoint_t >::propagate().
The documentation for this class was generated from the following file:
acts/blob/sPHENIX/Core/include/Acts/Seeding/GNN_TrackingFilter.hpp