Analysis Software: Acts::AccumulatedVolumeMaterial Class Reference
Acts::AccumulatedVolumeMaterial Class Reference
#include <acts/blob/sPHENIX/Core/include/Acts/Material/AccumulatedVolumeMaterial.hpp>
Public Member Functions
void accumulate (const MaterialSlab &mat)
Add one entry with the given material properties.
const Material & average ()
Private Attributes
MaterialSlab m_average
Detailed Description
Accumulate and average volume-based material properties.
This class is intended to be used during the mapping process.
Definition at line 20 of file AccumulatedVolumeMaterial.hpp.
View newest version in sPHENIX GitHub at line 20 of file AccumulatedVolumeMaterial.hpp
Member Function Documentation
void Acts::AccumulatedVolumeMaterial::accumulate (const MaterialSlab & mat)
Add one entry with the given material properties.
Definition at line 13 of file AccumulatedVolumeMaterial.cpp.
View newest version in sPHENIX GitHub at line 13 of file AccumulatedVolumeMaterial.cpp
References Acts::detail::combineSlabs(), and m_average.
Referenced by Acts::Test::BOOST_AUTO_TEST_CASE().
const Material& Acts::AccumulatedVolumeMaterial::average () inline
Compute the average material collected so far.
Returns
Vacuum properties if no matter has been accumulated yet.
Definition at line 28 of file AccumulatedVolumeMaterial.hpp.
View newest version in sPHENIX GitHub at line 28 of file AccumulatedVolumeMaterial.hpp
References m_average, and Acts::MaterialSlab::material().
Referenced by Acts::Test::BOOST_AUTO_TEST_CASE().
Member Data Documentation
MaterialSlab Acts::AccumulatedVolumeMaterial::m_average private
Definition at line 31 of file AccumulatedVolumeMaterial.hpp.
View newest version in sPHENIX GitHub at line 31 of file AccumulatedVolumeMaterial.hpp
Referenced by accumulate(), and average().
The documentation for this class was generated from the following files:
acts/blob/sPHENIX/Core/include/Acts/Material/AccumulatedVolumeMaterial.hpp
acts/blob/sPHENIX/Core/src/Material/AccumulatedVolumeMaterial.cpp