Analysis Software: PHG4Shower Class Reference
PHG4Shower Class Reference abstract
#include <coresoftware/blob/master/simulation/g4simulation/g4main/PHG4Shower.h>
Public Types
typedef std::set< int > ParticleIdSet
typedef ParticleIdSet::iterator ParticleIdIter
typedef
ParticleIdSet::const_iterator ParticleIdConstIter
typedef std::set< int > VertexIdSet
typedef VertexIdSet::iterator VertexIdIter
typedef VertexIdSet::const_iterator VertexIdConstIter
typedef std::map< int,
std::set< PHG4HitDefs::keytype > > HitIdMap
typedef HitIdMap::iterator HitIdIter
typedef HitIdMap::const_iterator HitIdConstIter
Public Member Functions
~PHG4Shower () override
void identify (std::ostream &os=std::cout) const override
PHG4Shower * CloneMe () const override
Virtual copy constructor.
void Reset () override
Clear Event.
int isValid () const override
isValid returns non zero if object contains vailid data
virtual int get_id () const
virtual void set_id (int id)
virtual int get_parent_particle_id () const
virtual void set_parent_particle_id (int parent_particle_id)
virtual int get_parent_shower_id () const
virtual void set_parent_shower_id (int parent_shower_id)
virtual float get_x () const
virtual void set_x (float x)
virtual float get_y () const
virtual void set_y (float y)
virtual float get_z () const
virtual void set_z (float x)
virtual float get_position (unsigned int coor) const
virtual void set_position (unsigned int coor, float xi)
virtual float get_covar (unsigned int i, unsigned int j) const
virtual void set_covar (unsigned int i, unsigned int j, float entry)
virtual unsigned int get_nhits (int volume) const
virtual void set_nhits (int volume, unsigned int nhits)
virtual double get_edep () const
virtual float get_edep (int volume) const
virtual void set_edep (int volume, float edep)
virtual double get_eion () const
virtual float get_eion (int volume) const
virtual void set_eion (int volume, float eion)
virtual float get_light_yield (int volume) const
virtual void set_light_yield (int volume, float light_yield)
virtual float get_eh_ratio (int volume) const
virtual void set_eh_ratio (int volume, float eh_ratio)
virtual bool empty_g4particle_id () const
virtual size_t size_g4particle_id () const
virtual void add_g4particle_id (int id)
virtual ParticleIdIter begin_g4particle_id ()
virtual ParticleIdConstIter begin_g4particle_id () const
virtual ParticleIdIter end_g4particle_id ()
virtual ParticleIdConstIter end_g4particle_id () const
virtual size_t remove_g4particle_id (int id)
virtual void clear_g4particle_id ()
virtual const ParticleIdSet & g4particle_ids () const =0
virtual bool empty_g4vertex_id () const
virtual size_t size_g4vertex_id () const
virtual void add_g4vertex_id (int id)
virtual VertexIdIter begin_g4vertex_id ()
virtual VertexIdConstIter begin_g4vertex_id () const
virtual VertexIdIter end_g4vertex_id ()
virtual VertexIdConstIter end_g4vertex_id () const
virtual size_t remove_g4vertex_id (int id)
virtual void clear_g4vertex_id ()
virtual const VertexIdSet & g4vertex_ids () const =0
virtual bool empty_g4hit_id () const
virtual size_t size_g4hit_id () const
virtual void add_g4hit_id (int volume, PHG4HitDefs::keytype id)
virtual HitIdIter begin_g4hit_id ()
virtual HitIdConstIter begin_g4hit_id () const
virtual HitIdIter find_g4hit_id (int volume)
virtual HitIdConstIter find_g4hit_id (int volume) const
virtual HitIdIter end_g4hit_id ()
virtual HitIdConstIter end_g4hit_id () const
virtual size_t remove_g4hit_id (int volume, PHG4HitDefs::keytype id)
virtual size_t remove_g4hit_volume (int volume)
virtual void clear_g4hit_id ()
virtual const HitIdMap & g4hit_ids () const =0
Public Member Functions inherited from PHObject
PHObject ()
ctor
~PHObject () override
dtor
virtual PHObject * clone () const final
PHObject * Clone (const char *newname="") const final
void Copy (TObject &object) const final
virtual int isValid (const float) const
virtual int isValid (const double) const
virtual int isValid (const int) const
virtual int isValid (const unsigned int) const
virtual int isImplemented (const float f) const
virtual int isImplemented (const double f) const
virtual int isImplemented (const int i) const
virtual int isImplemented (const unsigned int i) const
virtual int Integrate () const
virtual int Integrate (PHObject *obj)
virtual void CopyFrom (const PHObject *obj)
Protected Member Functions
PHG4Shower ()
Private Member Functions
ClassDefOverride (PHG4Shower, 1)
Detailed Description
Definition at line 15 of file PHG4Shower.h.
View newest version in sPHENIX GitHub at line 15 of file PHG4Shower.h
Member Typedef Documentation
typedef HitIdMap::const_iterator PHG4Shower::HitIdConstIter
Definition at line 28 of file PHG4Shower.h.
View newest version in sPHENIX GitHub at line 28 of file PHG4Shower.h
typedef HitIdMap::iterator PHG4Shower::HitIdIter
Definition at line 27 of file PHG4Shower.h.
View newest version in sPHENIX GitHub at line 27 of file PHG4Shower.h
typedef std::map<int, std::set<PHG4HitDefs::keytype> > PHG4Shower::HitIdMap
Definition at line 26 of file PHG4Shower.h.
View newest version in sPHENIX GitHub at line 26 of file PHG4Shower.h
typedef ParticleIdSet::const_iterator PHG4Shower::ParticleIdConstIter
Definition at line 20 of file PHG4Shower.h.
View newest version in sPHENIX GitHub at line 20 of file PHG4Shower.h
typedef ParticleIdSet::iterator PHG4Shower::ParticleIdIter
Definition at line 19 of file PHG4Shower.h.
View newest version in sPHENIX GitHub at line 19 of file PHG4Shower.h
typedef std::set<int> PHG4Shower::ParticleIdSet
Definition at line 18 of file PHG4Shower.h.
View newest version in sPHENIX GitHub at line 18 of file PHG4Shower.h
typedef VertexIdSet::const_iterator PHG4Shower::VertexIdConstIter
Definition at line 24 of file PHG4Shower.h.
View newest version in sPHENIX GitHub at line 24 of file PHG4Shower.h
typedef VertexIdSet::iterator PHG4Shower::VertexIdIter
Definition at line 23 of file PHG4Shower.h.
View newest version in sPHENIX GitHub at line 23 of file PHG4Shower.h
typedef std::set<int> PHG4Shower::VertexIdSet
Definition at line 22 of file PHG4Shower.h.
View newest version in sPHENIX GitHub at line 22 of file PHG4Shower.h
Constructor & Destructor Documentation
PHG4Shower::~PHG4Shower () inline override
Definition at line 30 of file PHG4Shower.h.
View newest version in sPHENIX GitHub at line 30 of file PHG4Shower.h
PHG4Shower::PHG4Shower () inline protected
Definition at line 119 of file PHG4Shower.h.
View newest version in sPHENIX GitHub at line 119 of file PHG4Shower.h
Member Function Documentation
virtual void PHG4Shower::add_g4hit_id (int volume, PHG4HitDefs::keytype id) inline virtual
Reimplemented in PHG4Showerv1.
Definition at line 106 of file PHG4Shower.h.
View newest version in sPHENIX GitHub at line 106 of file PHG4Shower.h
Referenced by PHG4ConeSteppingAction::UserSteppingAction(), PHG4EPSteppingAction::UserSteppingAction(), PHG4SectorSteppingAction::UserSteppingAction(), PHG4EICMvtxSteppingAction::UserSteppingAction(), PHG4MvtxSteppingAction::UserSteppingAction(), PHG4TpcSteppingAction::UserSteppingAction(), PHG4Prototype2OuterHcalSteppingAction::UserSteppingAction(), PHG4Prototype3InnerHcalSteppingAction::UserSteppingAction(), PHG4Prototype2InnerHcalSteppingAction::UserSteppingAction(), PHG4InttSteppingAction::UserSteppingAction(), PHG4InnerHcalSteppingAction::UserSteppingAction(), PHG4HcalSteppingAction::UserSteppingAction(), PHG4BlockSteppingAction::UserSteppingAction(), PHG4OuterHcalSteppingAction::UserSteppingAction(), PHG4CylinderSteppingAction::UserSteppingAction(), PHG4ZDCSteppingAction::UserSteppingAction(), PHG4SpacalSteppingAction::UserSteppingAction(), PHG4SpacalPrototype4SteppingAction::UserSteppingAction(), and PHG4SpacalPrototypeSteppingAction::UserSteppingAction().
virtual void PHG4Shower::add_g4particle_id (int id) inline virtual
Reimplemented in PHG4Showerv1.
Definition at line 84 of file PHG4Shower.h.
View newest version in sPHENIX GitHub at line 84 of file PHG4Shower.h
virtual void PHG4Shower::add_g4vertex_id (int id) inline virtual
Reimplemented in PHG4Showerv1.
Definition at line 95 of file PHG4Shower.h.
View newest version in sPHENIX GitHub at line 95 of file PHG4Shower.h
PHG4Shower::HitIdIter PHG4Shower::begin_g4hit_id () virtual
Reimplemented in PHG4Showerv1.
Definition at line 62 of file PHG4Shower.cc.
View newest version in sPHENIX GitHub at line 62 of file PHG4Shower.cc
References DummyHitIdMap.
Referenced by PHG4TruthEventAction::ProcessShowers(), and PHG4TruthEventAction::PruneShowers().
PHG4Shower::HitIdConstIter PHG4Shower::begin_g4hit_id () const virtual
Reimplemented in PHG4Showerv1.
Definition at line 47 of file PHG4Shower.cc.
View newest version in sPHENIX GitHub at line 47 of file PHG4Shower.cc
References DummyHitIdMap.
PHG4Shower::ParticleIdIter PHG4Shower::begin_g4particle_id () virtual
Reimplemented in PHG4Showerv1.
Definition at line 17 of file PHG4Shower.cc.
View newest version in sPHENIX GitHub at line 17 of file PHG4Shower.cc
References DummyParticleIdSet.
Referenced by PHG4TruthEventAction::PruneShowers().
PHG4Shower::ParticleIdConstIter PHG4Shower::begin_g4particle_id () const virtual
Reimplemented in PHG4Showerv1.
Definition at line 7 of file PHG4Shower.cc.
View newest version in sPHENIX GitHub at line 7 of file PHG4Shower.cc
References DummyParticleIdSet.
PHG4Shower::VertexIdIter PHG4Shower::begin_g4vertex_id () virtual
Reimplemented in PHG4Showerv1.
Definition at line 37 of file PHG4Shower.cc.
View newest version in sPHENIX GitHub at line 37 of file PHG4Shower.cc
References DummyVertexIdSet.
PHG4Shower::VertexIdConstIter PHG4Shower::begin_g4vertex_id () const virtual
Reimplemented in PHG4Showerv1.
Definition at line 27 of file PHG4Shower.cc.
View newest version in sPHENIX GitHub at line 27 of file PHG4Shower.cc
References DummyVertexIdSet.
PHG4Shower::ClassDefOverride (PHG4Shower , 1) private
virtual void PHG4Shower::clear_g4hit_id () inline virtual
Reimplemented in PHG4Showerv1.
Definition at line 115 of file PHG4Shower.h.
View newest version in sPHENIX GitHub at line 115 of file PHG4Shower.h
Referenced by PHG4DstCompressReco::process_event().
virtual void PHG4Shower::clear_g4particle_id () inline virtual
Reimplemented in PHG4Showerv1.
Definition at line 90 of file PHG4Shower.h.
View newest version in sPHENIX GitHub at line 90 of file PHG4Shower.h
Referenced by PHG4DstCompressReco::process_event().
virtual void PHG4Shower::clear_g4vertex_id () inline virtual
Reimplemented in PHG4Showerv1.
Definition at line 101 of file PHG4Shower.h.
View newest version in sPHENIX GitHub at line 101 of file PHG4Shower.h
Referenced by PHG4DstCompressReco::process_event().
PHG4Shower* PHG4Shower::CloneMe () const inline override virtual
Virtual copy constructor.
Reimplemented from PHObject.
Reimplemented in PHG4Showerv1.
Definition at line 35 of file PHG4Shower.h.
View newest version in sPHENIX GitHub at line 35 of file PHG4Shower.h
virtual bool PHG4Shower::empty_g4hit_id () const inline virtual
Reimplemented in PHG4Showerv1.
Definition at line 104 of file PHG4Shower.h.
View newest version in sPHENIX GitHub at line 104 of file PHG4Shower.h
Referenced by PHG4TruthEventAction::PruneShowers().
virtual bool PHG4Shower::empty_g4particle_id () const inline virtual
Reimplemented in PHG4Showerv1.
Definition at line 82 of file PHG4Shower.h.
View newest version in sPHENIX GitHub at line 82 of file PHG4Shower.h
Referenced by PHG4TruthEventAction::PruneShowers().
virtual bool PHG4Shower::empty_g4vertex_id () const inline virtual
Reimplemented in PHG4Showerv1.
Definition at line 93 of file PHG4Shower.h.
View newest version in sPHENIX GitHub at line 93 of file PHG4Shower.h
PHG4Shower::HitIdIter PHG4Shower::end_g4hit_id () virtual
Reimplemented in PHG4Showerv1.
Definition at line 72 of file PHG4Shower.cc.
View newest version in sPHENIX GitHub at line 72 of file PHG4Shower.cc
References DummyHitIdMap.
Referenced by CaloTruthEval::all_truth_hits(), PHG4TruthEventAction::ProcessShowers(), and PHG4TruthEventAction::PruneShowers().
PHG4Shower::HitIdConstIter PHG4Shower::end_g4hit_id () const virtual
Reimplemented in PHG4Showerv1.
Definition at line 57 of file PHG4Shower.cc.
View newest version in sPHENIX GitHub at line 57 of file PHG4Shower.cc
References DummyHitIdMap.
PHG4Shower::ParticleIdIter PHG4Shower::end_g4particle_id () virtual
Reimplemented in PHG4Showerv1.
Definition at line 22 of file PHG4Shower.cc.
View newest version in sPHENIX GitHub at line 22 of file PHG4Shower.cc
References DummyParticleIdSet.
Referenced by PHG4TruthEventAction::PruneShowers().
PHG4Shower::ParticleIdConstIter PHG4Shower::end_g4particle_id () const virtual
Reimplemented in PHG4Showerv1.
Definition at line 12 of file PHG4Shower.cc.
View newest version in sPHENIX GitHub at line 12 of file PHG4Shower.cc
References DummyParticleIdSet.
PHG4Shower::VertexIdIter PHG4Shower::end_g4vertex_id () virtual
Reimplemented in PHG4Showerv1.
Definition at line 42 of file PHG4Shower.cc.
View newest version in sPHENIX GitHub at line 42 of file PHG4Shower.cc
References DummyVertexIdSet.
PHG4Shower::VertexIdConstIter PHG4Shower::end_g4vertex_id () const virtual
Reimplemented in PHG4Showerv1.
Definition at line 32 of file PHG4Shower.cc.
View newest version in sPHENIX GitHub at line 32 of file PHG4Shower.cc
References DummyVertexIdSet.
PHG4Shower::HitIdIter PHG4Shower::find_g4hit_id (int volume) virtual
Reimplemented in PHG4Showerv1.
Definition at line 67 of file PHG4Shower.cc.
View newest version in sPHENIX GitHub at line 67 of file PHG4Shower.cc
References DummyHitIdMap.
Referenced by CaloTruthEval::all_truth_hits().
PHG4Shower::HitIdConstIter PHG4Shower::find_g4hit_id (int volume) const virtual
Reimplemented in PHG4Showerv1.
Definition at line 52 of file PHG4Shower.cc.
View newest version in sPHENIX GitHub at line 52 of file PHG4Shower.cc
References DummyHitIdMap.
virtual const HitIdMap& PHG4Shower::g4hit_ids () const pure virtual
Implemented in PHG4Showerv1.
Referenced by operator==().
virtual const ParticleIdSet& PHG4Shower::g4particle_ids () const pure virtual
Implemented in PHG4Showerv1.
Referenced by operator==().
virtual const VertexIdSet& PHG4Shower::g4vertex_ids () const pure virtual
Implemented in PHG4Showerv1.
Referenced by operator==().
virtual float PHG4Shower::get_covar (unsigned int i, unsigned int j) const inline virtual
Reimplemented in PHG4Showerv1.
Definition at line 62 of file PHG4Shower.h.
View newest version in sPHENIX GitHub at line 62 of file PHG4Shower.h
virtual double PHG4Shower::get_edep () const inline virtual
Reimplemented in PHG4Showerv1.
Definition at line 68 of file PHG4Shower.h.
View newest version in sPHENIX GitHub at line 68 of file PHG4Shower.h
Referenced by CaloTruthEval::get_shower_energy_deposit(), and PHG4TruthEventAction::PruneShowers().
virtual float PHG4Shower::get_edep (int volume) const inline virtual
Reimplemented in PHG4Showerv1.
Definition at line 69 of file PHG4Shower.h.
View newest version in sPHENIX GitHub at line 69 of file PHG4Shower.h
virtual float PHG4Shower::get_eh_ratio (int volume) const inline virtual
Reimplemented in PHG4Showerv1.
Definition at line 79 of file PHG4Shower.h.
View newest version in sPHENIX GitHub at line 79 of file PHG4Shower.h
Referenced by CaloTruthEval::get_shower_eh_ratio().
virtual double PHG4Shower::get_eion () const inline virtual
Reimplemented in PHG4Showerv1.
Definition at line 72 of file PHG4Shower.h.
View newest version in sPHENIX GitHub at line 72 of file PHG4Shower.h
virtual float PHG4Shower::get_eion (int volume) const inline virtual
Reimplemented in PHG4Showerv1.
Definition at line 73 of file PHG4Shower.h.
View newest version in sPHENIX GitHub at line 73 of file PHG4Shower.h
virtual int PHG4Shower::get_id () const inline virtual
Reimplemented in PHG4Showerv1.
Definition at line 41 of file PHG4Shower.h.
View newest version in sPHENIX GitHub at line 41 of file PHG4Shower.h
Referenced by BaseTruthEval::all_secondary_showers(), CaloRawTowerEval::all_towers_from(), BaseTruthEval::are_same_shower(), CaloRawTowerEval::get_energy_contribution(), BaseTruthEval::is_g4hit_from_primary_shower(), and operator==().
virtual float PHG4Shower::get_light_yield (int volume) const inline virtual
Reimplemented in PHG4Showerv1.
Definition at line 76 of file PHG4Shower.h.
View newest version in sPHENIX GitHub at line 76 of file PHG4Shower.h
virtual unsigned int PHG4Shower::get_nhits (int volume) const inline virtual
Reimplemented in PHG4Showerv1.
Definition at line 65 of file PHG4Shower.h.
View newest version in sPHENIX GitHub at line 65 of file PHG4Shower.h
Referenced by CaloEvaluator::fillOutputNtuples().
virtual int PHG4Shower::get_parent_particle_id () const inline virtual
Reimplemented in PHG4Showerv1.
Definition at line 44 of file PHG4Shower.h.
View newest version in sPHENIX GitHub at line 44 of file PHG4Shower.h
Referenced by BaseTruthEval::get_primary_particle(), BaseTruthEval::get_primary_shower(), and operator==().
virtual int PHG4Shower::get_parent_shower_id () const inline virtual
Reimplemented in PHG4Showerv1.
Definition at line 47 of file PHG4Shower.h.
View newest version in sPHENIX GitHub at line 47 of file PHG4Shower.h
Referenced by BaseTruthEval::all_secondary_showers(), BaseTruthEval::get_primary_shower(), BaseTruthEval::is_primary(), and operator==().
virtual float PHG4Shower::get_position (unsigned int coor) const inline virtual
Reimplemented in PHG4Showerv1.
Definition at line 59 of file PHG4Shower.h.
View newest version in sPHENIX GitHub at line 59 of file PHG4Shower.h
virtual float PHG4Shower::get_x () const inline virtual
Reimplemented in PHG4Showerv1.
Definition at line 50 of file PHG4Shower.h.
View newest version in sPHENIX GitHub at line 50 of file PHG4Shower.h
Referenced by operator==().
virtual float PHG4Shower::get_y () const inline virtual
Reimplemented in PHG4Showerv1.
Definition at line 53 of file PHG4Shower.h.
View newest version in sPHENIX GitHub at line 53 of file PHG4Shower.h
Referenced by operator==().
virtual float PHG4Shower::get_z () const inline virtual
Reimplemented in PHG4Showerv1.
Definition at line 56 of file PHG4Shower.h.
View newest version in sPHENIX GitHub at line 56 of file PHG4Shower.h
Referenced by operator==().
void PHG4Shower::identify (std::ostream & os = std::cout) const inline override virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from PHObject.
Reimplemented in PHG4Showerv1.
Definition at line 34 of file PHG4Shower.h.
View newest version in sPHENIX GitHub at line 34 of file PHG4Shower.h
References os.
int PHG4Shower::isValid () const inline override virtual
isValid returns non zero if object contains vailid data
Reimplemented from PHObject.
Reimplemented in PHG4Showerv1.
Definition at line 37 of file PHG4Shower.h.
View newest version in sPHENIX GitHub at line 37 of file PHG4Shower.h
virtual size_t PHG4Shower::remove_g4hit_id (int volume, PHG4HitDefs::keytype id) inline virtual
Reimplemented in PHG4Showerv1.
Definition at line 113 of file PHG4Shower.h.
View newest version in sPHENIX GitHub at line 113 of file PHG4Shower.h
virtual size_t PHG4Shower::remove_g4hit_volume (int volume) inline virtual
Reimplemented in PHG4Showerv1.
Definition at line 114 of file PHG4Shower.h.
View newest version in sPHENIX GitHub at line 114 of file PHG4Shower.h
Referenced by PHG4TruthEventAction::PruneShowers().
virtual size_t PHG4Shower::remove_g4particle_id (int id) inline virtual
Reimplemented in PHG4Showerv1.
Definition at line 89 of file PHG4Shower.h.
View newest version in sPHENIX GitHub at line 89 of file PHG4Shower.h
Referenced by PHG4TruthEventAction::PruneShowers().
virtual size_t PHG4Shower::remove_g4vertex_id (int id) inline virtual
Reimplemented in PHG4Showerv1.
Definition at line 100 of file PHG4Shower.h.
View newest version in sPHENIX GitHub at line 100 of file PHG4Shower.h
void PHG4Shower::Reset () inline override virtual
Clear Event.
Reimplemented from PHObject.
Reimplemented in PHG4Showerv1.
Definition at line 36 of file PHG4Shower.h.
View newest version in sPHENIX GitHub at line 36 of file PHG4Shower.h
virtual void PHG4Shower::set_covar (unsigned int i, unsigned int j, float entry) inline virtual
Reimplemented in PHG4Showerv1.
Definition at line 63 of file PHG4Shower.h.
View newest version in sPHENIX GitHub at line 63 of file PHG4Shower.h
Referenced by PHG4TruthEventAction::ProcessShowers().
virtual void PHG4Shower::set_edep (int volume, float edep) inline virtual
Reimplemented in PHG4Showerv1.
Definition at line 70 of file PHG4Shower.h.
View newest version in sPHENIX GitHub at line 70 of file PHG4Shower.h
Referenced by PHG4TruthEventAction::ProcessShowers().
virtual void PHG4Shower::set_eh_ratio (int volume, float eh_ratio) inline virtual
Reimplemented in PHG4Showerv1.
Definition at line 80 of file PHG4Shower.h.
View newest version in sPHENIX GitHub at line 80 of file PHG4Shower.h
Referenced by PHG4TruthEventAction::ProcessShowers().
virtual void PHG4Shower::set_eion (int volume, float eion) inline virtual
Reimplemented in PHG4Showerv1.
Definition at line 74 of file PHG4Shower.h.
View newest version in sPHENIX GitHub at line 74 of file PHG4Shower.h
Referenced by PHG4TruthEventAction::ProcessShowers().
virtual void PHG4Shower::set_id (int id) inline virtual
Reimplemented in PHG4Showerv1.
Definition at line 42 of file PHG4Shower.h.
View newest version in sPHENIX GitHub at line 42 of file PHG4Shower.h
Referenced by PHG4TruthInfoContainer::AddShower().
virtual void PHG4Shower::set_light_yield (int volume, float light_yield) inline virtual
Reimplemented in PHG4Showerv1.
Definition at line 77 of file PHG4Shower.h.
View newest version in sPHENIX GitHub at line 77 of file PHG4Shower.h
Referenced by PHG4TruthEventAction::ProcessShowers().
virtual void PHG4Shower::set_nhits (int volume, unsigned int nhits) inline virtual
Reimplemented in PHG4Showerv1.
Definition at line 66 of file PHG4Shower.h.
View newest version in sPHENIX GitHub at line 66 of file PHG4Shower.h
Referenced by PHG4TruthEventAction::ProcessShowers().
virtual void PHG4Shower::set_parent_particle_id (int parent_particle_id) inline virtual
Reimplemented in PHG4Showerv1.
Definition at line 45 of file PHG4Shower.h.
View newest version in sPHENIX GitHub at line 45 of file PHG4Shower.h
virtual void PHG4Shower::set_parent_shower_id (int parent_shower_id) inline virtual
Reimplemented in PHG4Showerv1.
Definition at line 48 of file PHG4Shower.h.
View newest version in sPHENIX GitHub at line 48 of file PHG4Shower.h
virtual void PHG4Shower::set_position (unsigned int coor, float xi) inline virtual
Reimplemented in PHG4Showerv1.
Definition at line 60 of file PHG4Shower.h.
View newest version in sPHENIX GitHub at line 60 of file PHG4Shower.h
virtual void PHG4Shower::set_x (float x) inline virtual
Reimplemented in PHG4Showerv1.
Definition at line 51 of file PHG4Shower.h.
View newest version in sPHENIX GitHub at line 51 of file PHG4Shower.h
Referenced by PHG4TruthEventAction::ProcessShowers().
virtual void PHG4Shower::set_y (float y) inline virtual
Reimplemented in PHG4Showerv1.
Definition at line 54 of file PHG4Shower.h.
View newest version in sPHENIX GitHub at line 54 of file PHG4Shower.h
Referenced by PHG4TruthEventAction::ProcessShowers().
virtual void PHG4Shower::set_z (float x) inline virtual
Reimplemented in PHG4Showerv1.
Definition at line 57 of file PHG4Shower.h.
View newest version in sPHENIX GitHub at line 57 of file PHG4Shower.h
Referenced by PHG4TruthEventAction::ProcessShowers().
virtual size_t PHG4Shower::size_g4hit_id () const inline virtual
Reimplemented in PHG4Showerv1.
Definition at line 105 of file PHG4Shower.h.
View newest version in sPHENIX GitHub at line 105 of file PHG4Shower.h
virtual size_t PHG4Shower::size_g4particle_id () const inline virtual
Reimplemented in PHG4Showerv1.
Definition at line 83 of file PHG4Shower.h.
View newest version in sPHENIX GitHub at line 83 of file PHG4Shower.h
virtual size_t PHG4Shower::size_g4vertex_id () const inline virtual
Reimplemented in PHG4Showerv1.
Definition at line 94 of file PHG4Shower.h.
View newest version in sPHENIX GitHub at line 94 of file PHG4Shower.h
The documentation for this class was generated from the following files:
coresoftware/blob/master/simulation/g4simulation/g4main/PHG4Shower.h
coresoftware/blob/master/simulation/g4simulation/g4main/PHG4Shower.cc