Analysis Software: MbdVertex Class Reference
MbdVertex Class Reference
#include <coresoftware/blob/master/offline/packages/globalvertex/MbdVertex.h>
Public Member Functions
~MbdVertex () override
void identify (std::ostream &os=std::cout) const override
PHObject * CloneMe () const override
Virtual copy constructor.
int isValid () const override
isValid returns non zero if object contains vailid data
virtual unsigned int get_id () const override
virtual void set_id (unsigned int) override
virtual float get_t () const override
virtual void set_t (float) override
virtual float get_t_err () const override
virtual void set_t_err (float) override
virtual float get_z () const override
virtual void set_z (float) override
virtual float get_z_err () const override
virtual void set_z_err (float) override
virtual unsigned int get_beam_crossing () const override
virtual void set_beam_crossing (unsigned int) override
virtual void set_bbc_ns (int, int, float, float) override
virtual int get_bbc_npmt (int) const override
virtual float get_bbc_q (int) const override
virtual float get_bbc_t (int) const override
Public Member Functions inherited from Vertex
~Vertex () override
void identify (std::ostream &os=std::cout) const override
PHObject * CloneMe () const override
Virtual copy constructor.
int isValid () const override
isValid returns non zero if object contains vailid data
virtual float get_t0 () const
virtual void set_t0 (float t0)
virtual float get_x () const
virtual void set_x (float)
virtual float get_y () const
virtual void set_y (float)
virtual float get_chisq () const
virtual void set_chisq (float)
virtual unsigned int get_ndof () const
virtual void set_ndof (unsigned int)
virtual float get_position (unsigned int) const
virtual void set_position (unsigned int, float)
virtual float get_error (unsigned int, unsigned int) const
virtual void set_error (unsigned int, unsigned int, float)
virtual void clear_tracks ()
virtual bool empty_tracks ()
virtual size_t size_tracks () const
virtual void insert_track (unsigned int)
virtual size_t erase_track (unsigned int)
virtual ConstTrackIter begin_tracks () const
virtual ConstTrackIter find_track (unsigned int trackid) const
virtual ConstTrackIter end_tracks () const
virtual TrackIter begin_tracks ()
virtual TrackIter find_track (unsigned int trackid)
virtual TrackIter end_tracks ()
Public Member Functions inherited from PHObject
PHObject ()
ctor
~PHObject () override
dtor
virtual PHObject * clone () const final
PHObject * Clone (const char *newname="") const final
void Copy (TObject &object) const final
virtual void Reset ()
Clear Event.
virtual int Integrate () const
virtual int Integrate (PHObject *)
virtual void CopyFrom (const PHObject *obj)
Protected Member Functions
MbdVertex ()
Private Member Functions
ClassDefOverride (MbdVertex, 1)
Additional Inherited Members
Public Types inherited from Vertex
typedef std::set< unsigned int > TrackSet
typedef std::set< unsigned int >
::const_iterator ConstTrackIter
typedef std::set< unsigned int >
::iterator TrackIter
Detailed Description
Definition at line 9 of file MbdVertex.h.
View newest version in sPHENIX GitHub at line 9 of file MbdVertex.h
Constructor & Destructor Documentation
MbdVertex::~MbdVertex () inline override
Definition at line 12 of file MbdVertex.h.
View newest version in sPHENIX GitHub at line 12 of file MbdVertex.h
MbdVertex::MbdVertex () inline protected
Definition at line 46 of file MbdVertex.h.
View newest version in sPHENIX GitHub at line 46 of file MbdVertex.h
Member Function Documentation
MbdVertex::ClassDefOverride (MbdVertex , 1) private
PHObject* MbdVertex::CloneMe () const inline override virtual
Virtual copy constructor.
Reimplemented from PHObject.
Reimplemented in MbdVertexv1, and MbdVertexv2.
Definition at line 17 of file MbdVertex.h.
View newest version in sPHENIX GitHub at line 17 of file MbdVertex.h
virtual int MbdVertex::get_bbc_npmt (int) const inline override virtual
Reimplemented from Vertex.
Definition at line 41 of file MbdVertex.h.
View newest version in sPHENIX GitHub at line 41 of file MbdVertex.h
virtual float MbdVertex::get_bbc_q (int) const inline override virtual
Reimplemented from Vertex.
Definition at line 42 of file MbdVertex.h.
View newest version in sPHENIX GitHub at line 42 of file MbdVertex.h
virtual float MbdVertex::get_bbc_t (int) const inline override virtual
Reimplemented from Vertex.
Definition at line 43 of file MbdVertex.h.
View newest version in sPHENIX GitHub at line 43 of file MbdVertex.h
virtual unsigned int MbdVertex::get_beam_crossing () const inline override virtual
Reimplemented from Vertex.
Reimplemented in MbdVertexv2.
Definition at line 37 of file MbdVertex.h.
View newest version in sPHENIX GitHub at line 37 of file MbdVertex.h
virtual unsigned int MbdVertex::get_id () const inline override virtual
Reimplemented from Vertex.
Reimplemented in MbdVertexv1, and MbdVertexv2.
Definition at line 22 of file MbdVertex.h.
View newest version in sPHENIX GitHub at line 22 of file MbdVertex.h
Referenced by GlobalVertexReco::process_event().
virtual float MbdVertex::get_t () const inline override virtual
Reimplemented from Vertex.
Reimplemented in MbdVertexv1, and MbdVertexv2.
Definition at line 25 of file MbdVertex.h.
View newest version in sPHENIX GitHub at line 25 of file MbdVertex.h
virtual float MbdVertex::get_t_err () const inline override virtual
Reimplemented from Vertex.
Reimplemented in MbdVertexv1, and MbdVertexv2.
Definition at line 28 of file MbdVertex.h.
View newest version in sPHENIX GitHub at line 28 of file MbdVertex.h
virtual float MbdVertex::get_z () const inline override virtual
Reimplemented from Vertex.
Reimplemented in MbdVertexv2, and MbdVertexv1.
Definition at line 31 of file MbdVertex.h.
View newest version in sPHENIX GitHub at line 31 of file MbdVertex.h
Referenced by RawClusterZVertexRecorrect::process_event(), RawClusterBuilderTemplate::process_event(), and GlobalVertexReco::process_event().
virtual float MbdVertex::get_z_err () const inline override virtual
Reimplemented from Vertex.
Reimplemented in MbdVertexv2, and MbdVertexv1.
Definition at line 34 of file MbdVertex.h.
View newest version in sPHENIX GitHub at line 34 of file MbdVertex.h
Referenced by GlobalVertexReco::process_event().
void MbdVertex::identify (std::ostream & os = std::cout) const inline override virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from PHObject.
Reimplemented in MbdVertexv1, and MbdVertexv2.
Definition at line 16 of file MbdVertex.h.
View newest version in sPHENIX GitHub at line 16 of file MbdVertex.h
References os.
int MbdVertex::isValid () const inline override virtual
isValid returns non zero if object contains vailid data
Reimplemented from PHObject.
Reimplemented in MbdVertexv1, and MbdVertexv2.
Definition at line 18 of file MbdVertex.h.
View newest version in sPHENIX GitHub at line 18 of file MbdVertex.h
virtual void MbdVertex::set_bbc_ns (int , int , float , float) inline override virtual
Reimplemented from Vertex.
Definition at line 40 of file MbdVertex.h.
View newest version in sPHENIX GitHub at line 40 of file MbdVertex.h
virtual void MbdVertex::set_beam_crossing (unsigned int) inline override virtual
Reimplemented from Vertex.
Reimplemented in MbdVertexv2.
Definition at line 38 of file MbdVertex.h.
View newest version in sPHENIX GitHub at line 38 of file MbdVertex.h
virtual void MbdVertex::set_id (unsigned int) inline override virtual
Reimplemented from Vertex.
Reimplemented in MbdVertexv1, and MbdVertexv2.
Definition at line 23 of file MbdVertex.h.
View newest version in sPHENIX GitHub at line 23 of file MbdVertex.h
virtual void MbdVertex::set_t (float) inline override virtual
Reimplemented from Vertex.
Reimplemented in MbdVertexv1, and MbdVertexv2.
Definition at line 26 of file MbdVertex.h.
View newest version in sPHENIX GitHub at line 26 of file MbdVertex.h
Referenced by MbdVertexFastSimReco::process_event().
virtual void MbdVertex::set_t_err (float) inline override virtual
Reimplemented from Vertex.
Reimplemented in MbdVertexv1, and MbdVertexv2.
Definition at line 29 of file MbdVertex.h.
View newest version in sPHENIX GitHub at line 29 of file MbdVertex.h
Referenced by MbdVertexFastSimReco::process_event().
virtual void MbdVertex::set_z (float) inline override virtual
Reimplemented from Vertex.
Reimplemented in MbdVertexv2, and MbdVertexv1.
Definition at line 32 of file MbdVertex.h.
View newest version in sPHENIX GitHub at line 32 of file MbdVertex.h
Referenced by MbdVertexFastSimReco::process_event().
virtual void MbdVertex::set_z_err (float) inline override virtual
Reimplemented from Vertex.
Reimplemented in MbdVertexv2, and MbdVertexv1.
Definition at line 35 of file MbdVertex.h.
View newest version in sPHENIX GitHub at line 35 of file MbdVertex.h
Referenced by MbdVertexFastSimReco::process_event().
The documentation for this class was generated from the following file:
coresoftware/blob/master/offline/packages/globalvertex/MbdVertex.h