Analysis Software: PdbParameterMapContainer Class Reference
PdbParameterMapContainer Class Reference
#include <coresoftware/blob/master/offline/database/pdbcal/base/PdbParameterMapContainer.h>
Public Types
typedef std::map< int,
PdbParameterMap * > parMap
typedef parMap::const_iterator parIter
typedef std::pair< parIter,
parIter > parConstRange
Public Member Functions
PdbParameterMapContainer ()
~PdbParameterMapContainer () override
void print () const override
void Reset () override
Clear Event.
void AddPdbParameterMap (const int layer, PdbParameterMap *params)
const PdbParameterMap * GetParameters (const int layer) const
PdbParameterMap * GetParametersToModify (const int layer)
parConstRange get_ParameterMaps () const
int WriteToFile (const std::string &detector_name, const std::string &extension, const std::string &dir=".")
write PdbParameterMapContainer to an external file with root or xml extension.
Public Member Functions inherited from PdbCalChan
PdbCalChan ()
~PdbCalChan () override
ClassDefOverride (PdbCalChan, 1)
Public Member Functions inherited from PHObject
PHObject ()
ctor
~PHObject () override
dtor
virtual PHObject * CloneMe () const
Virtual copy constructor.
virtual PHObject * clone () const final
PHObject * Clone (const char *newname="") const final
void Copy (TObject &object) const final
virtual void identify (std::ostream &os=std::cout) const
virtual int isValid () const
isValid returns non zero if object contains vailid data
virtual int Integrate () const
virtual int Integrate (PHObject *)
virtual void CopyFrom (const PHObject *obj)
Protected Attributes
std::map< int, PdbParameterMap * > parametermap
Detailed Description
Definition at line 12 of file PdbParameterMapContainer.h.
View newest version in sPHENIX GitHub at line 12 of file PdbParameterMapContainer.h
Member Typedef Documentation
typedef std::pair<parIter, parIter> PdbParameterMapContainer::parConstRange
Definition at line 17 of file PdbParameterMapContainer.h.
View newest version in sPHENIX GitHub at line 17 of file PdbParameterMapContainer.h
typedef parMap::const_iterator PdbParameterMapContainer::parIter
Definition at line 16 of file PdbParameterMapContainer.h.
View newest version in sPHENIX GitHub at line 16 of file PdbParameterMapContainer.h
typedef std::map<int, PdbParameterMap *> PdbParameterMapContainer::parMap
Definition at line 15 of file PdbParameterMapContainer.h.
View newest version in sPHENIX GitHub at line 15 of file PdbParameterMapContainer.h
Constructor & Destructor Documentation
PdbParameterMapContainer::PdbParameterMapContainer () inline
Definition at line 19 of file PdbParameterMapContainer.h.
View newest version in sPHENIX GitHub at line 19 of file PdbParameterMapContainer.h
PdbParameterMapContainer::~PdbParameterMapContainer () override
Definition at line 23 of file PdbParameterMapContainer.cc.
View newest version in sPHENIX GitHub at line 23 of file PdbParameterMapContainer.cc
Member Function Documentation
void PdbParameterMapContainer::AddPdbParameterMap (const int layer, PdbParameterMap * params)
Definition at line 53 of file PdbParameterMapContainer.cc.
View newest version in sPHENIX GitHub at line 53 of file PdbParameterMapContainer.cc
References layer, and PHWHERE.
Referenced by PHParametersContainer::CopyToPdbParameterMapContainer(), and PHParameters::SaveToNodeTree().
parConstRange PdbParameterMapContainer::get_ParameterMaps () const inline
Definition at line 29 of file PdbParameterMapContainer.h.
View newest version in sPHENIX GitHub at line 29 of file PdbParameterMapContainer.h
References parametermap.
Referenced by PHParametersContainer::CreateAndFillFrom(), PHParametersContainer::FillFrom(), and DumpPdbParameterMapContainer::process_Node().
const PdbParameterMap * PdbParameterMapContainer::GetParameters (const int layer) const
Definition at line 69 of file PdbParameterMapContainer.cc.
View newest version in sPHENIX GitHub at line 69 of file PdbParameterMapContainer.cc
Referenced by PHParameters::FillFrom(), and PHParameters::ReadFromFile().
PdbParameterMap * PdbParameterMapContainer::GetParametersToModify (const int layer)
Definition at line 80 of file PdbParameterMapContainer.cc.
View newest version in sPHENIX GitHub at line 80 of file PdbParameterMapContainer.cc
Referenced by PHParameters::SaveToNodeTree(), PHParameters::UpdateNodeTree(), and PHParametersContainer::UpdatePdbParameterMapContainer().
void PdbParameterMapContainer::print () const override virtual
Implements PdbCalChan.
Definition at line 33 of file PdbParameterMapContainer.cc.
View newest version in sPHENIX GitHub at line 33 of file PdbParameterMapContainer.cc
Referenced by PHG4DetectorGroupSubsystem::InitRun(), and PHG4DetectorSubsystem::InitRun().
void PdbParameterMapContainer::Reset () override virtual
Clear Event.
Reimplemented from PHObject.
Definition at line 43 of file PdbParameterMapContainer.cc.
View newest version in sPHENIX GitHub at line 43 of file PdbParameterMapContainer.cc
Referenced by PHParametersContainer::SaveToNodeTree().
int PdbParameterMapContainer::WriteToFile (const std::string & detector_name, const std::string & extension, const std::string & dir = ".")
write PdbParameterMapContainer to an external file with root or xml extension.
Definition at line 90 of file PdbParameterMapContainer.cc.
View newest version in sPHENIX GitHub at line 90 of file PdbParameterMapContainer.cc
References container, extension, f, INTTVtxZ::fname, PdbBankID::getInternalValue(), PHTimeStamp::getTics(), it, Acts::Test::time, and Acts::Test::transform.
Member Data Documentation
std::map<int, PdbParameterMap *> PdbParameterMapContainer::parametermap protected
Definition at line 35 of file PdbParameterMapContainer.h.
View newest version in sPHENIX GitHub at line 35 of file PdbParameterMapContainer.h
Referenced by get_ParameterMaps().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/database/pdbcal/base/PdbParameterMapContainer.h
coresoftware/blob/master/offline/database/pdbcal/base/PdbParameterMapContainer.cc