Analysis Software: PHDataNode< T > Class Template Reference
PHDataNode< T > Class Template Reference
#include <coresoftware/blob/master/offline/framework/phool/PHDataNode.h>
Classes
union tobjcast
Public Member Functions
PHDataNode (T *, const std::string &)
PHDataNode (T *, const std::string &, const std::string &)
~PHDataNode () override
T * getData ()
void setData (T *d)
void prune () override
void forgetMe (PHNode *) override
void print (const std::string &) override
bool write (PHIOManager *, const std::string &="") override
Public Member Functions inherited from PHNode
PHNode (const std::string &)
PHNode (const std::string &, const std::string &)
virtual ~PHNode ()
PHNode * getParent () const
bool isPersistent () const
void makePersistent ()
const std::string getObjectType () const
const std::string getType () const
const std::string getName () const
const std::string getClass () const
void setParent (PHNode *p)
void setName (const std::string &n)
void setObjectType (const std::string &n)
virtual void setResetFlag (const bool b)
virtual bool getResetFlag () const
void makeTransient ()
Protected Member Functions
PHDataNode ()=delete
Protected Attributes
tobjcast data
Protected Attributes inherited from PHNode
PHNode * parent = nullptr
bool persistent = true
std::string type = "PHNode"
std::string objecttype
std::string name
bool reset_able = true
std::string objectclass
Detailed Description
template<class T>
class PHDataNode< T >
Definition at line 13 of file PHDataNode.h.
View newest version in sPHENIX GitHub at line 13 of file PHDataNode.h
Constructor & Destructor Documentation
template<class T> PHDataNode< T >::PHDataNode (T * d, const std::string & n)
Definition at line 41 of file PHDataNode.h.
View newest version in sPHENIX GitHub at line 41 of file PHDataNode.h
References PHDataNode< T >::setData(), and PHNode::type.
template<class T> PHDataNode< T >::PHDataNode (T * d, const std::string & n, const std::string & objtype)
Definition at line 50 of file PHDataNode.h.
View newest version in sPHENIX GitHub at line 50 of file PHDataNode.h
References PHDataNode< T >::setData(), and PHNode::type.
template<class T > PHDataNode< T >::~PHDataNode () override
Definition at line 60 of file PHDataNode.h.
View newest version in sPHENIX GitHub at line 60 of file PHDataNode.h
References configureMap::data.
template<class T> PHDataNode< T >::PHDataNode () protected delete
Member Function Documentation
template<class T> void PHDataNode< T >::forgetMe (PHNode *) inline override virtual
Implements PHNode.
Definition at line 24 of file PHDataNode.h.
View newest version in sPHENIX GitHub at line 24 of file PHDataNode.h
template<class T> T* PHDataNode< T >::getData () inline
Definition at line 21 of file PHDataNode.h.
View newest version in sPHENIX GitHub at line 21 of file PHDataNode.h
Referenced by findNode::getClass(), PHIODataNode< T >::operator*(), DumpCaloTriggerInfo::process_Node(), DumpTowerBackground::process_Node(), DumpTrkrHitTruthAssoc::process_Node(), DumpTrkrHitSetContainer::process_Node(), DumpTrkrClusterHitAssoc::process_Node(), DumpTrkrClusterCrossingAssoc::process_Node(), DumpTrkrClusterContainer::process_Node(), DumpTrackSeedContainer::process_Node(), DumpTpcSeedTrackMap::process_Node(), DumpTpcRawHitContainer::process_Node(), DumpTowerInfoContainer::process_Node(), DumpParticleFlowElementContainer::process_Node(), DumpSyncObject::process_Node(), DumpSvtxVertexMap::process_Node(), DumpCdbUrlSave::process_Node(), DumpInttRawHitContainer::process_Node(), DumpRunHeader::process_Node(), DumpRawTowerGeomContainer::process_Node(), DumpRawTowerContainer::process_Node(), DumpRawClusterContainer::process_Node(), DumpPHHepMCGenEventMap::process_Node(), DumpPHGenIntegral::process_Node(), DumpPHG4TruthInfoContainer::process_Node(), DumpPHG4TpcCylinderGeomContainer::process_Node(), DumpPHG4ScintillatorSlatContainer::process_Node(), DumpPHG4ParticleSvtxMap::process_Node(), DumpPHG4InEvent::process_Node(), DumpPHG4HitContainer::process_Node(), DumpPHG4CylinderGeomContainer::process_Node(), DumpPHG4CellContainer::process_Node(), DumpPHG4CylinderCellContainer::process_Node(), DumpJetContainer::process_Node(), DumpPHG4BlockGeomContainer::process_Node(), DumpPHG4BlockCellGeomContainer::process_Node(), DumpPHFieldConfig::process_Node(), DumpPdbParameterMapContainer::process_Node(), DumpPdbParameterMap::process_Node(), DumpGl1RawHit::process_Node(), DumpMvtxRawHitContainer::process_Node(), DumpSvtxTrackMap::process_Node(), DumpMicromegasRawHitContainer::process_Node(), DumpMbdVertexMap::process_Node(), DumpMbdPmtContainer::process_Node(), DumpMbdOut::process_Node(), DumpMbdGeom::process_Node(), DumpPHG4CylinderCellGeomContainer::process_Node(), DumpCentralityInfo::process_Node(), DumpJetMap::process_Node(), DumpInttDeadMap::process_Node(), DumpGlobalVertexMap::process_Node(), DumpFlagSave::process_Node(), DumpSvtxPHG4ParticleMap::process_Node(), DumpEventHeader::process_Node(), DumpBbcPmtInfoContainer::process_Node(), DumpEpdGeom::process_Node(), DumpVariableArray::process_Node(), DumpBbcVertexMap::process_Node(), DumpMvtxRawEvtHeader::process_Node(), PHNodeIOManager::reconstructNodeTree(), PHG4DstCompressReco::SearchG4HitNodes(), PHG4TruthEventAction::SearchNode(), and PHRawOManager::write().
template<class T > void PHDataNode< T >::print (const std::string & path) override virtual
Implements PHNode.
Definition at line 73 of file PHDataNode.h.
View newest version in sPHENIX GitHub at line 73 of file PHDataNode.h
References perf_headwind::name, and parse_cmake_options::type.
Referenced by tpc_hits::InitRun(), and TpcRawDataDecoder::InitRun().
template<class T> void PHDataNode< T >::prune () inline override virtual
Implements PHNode.
Definition at line 23 of file PHDataNode.h.
View newest version in sPHENIX GitHub at line 23 of file PHDataNode.h
template<class T> void PHDataNode< T >::setData (T * d) inline
Definition at line 22 of file PHDataNode.h.
View newest version in sPHENIX GitHub at line 22 of file PHDataNode.h
Referenced by PHDataNode< T >::PHDataNode(), EventCombiner::process_event(), EventCombiner::ResetEvent(), Fun4AllPrdfInputManager::ResetEvent(), Fun4AllPrdfInputPoolManager::ResetEvent(), Fun4AllPrdfInputManager::run(), and Fun4AllPrdfInputPoolManager::run().
template<class T> bool PHDataNode< T >::write (PHIOManager * , const std::string & = "") inline override virtual
Implements PHNode.
Reimplemented in PHIODataNode< T >.
Definition at line 26 of file PHDataNode.h.
View newest version in sPHENIX GitHub at line 26 of file PHDataNode.h
Member Data Documentation
template<class T> tobjcast PHDataNode< T >::data protected
Definition at line 36 of file PHDataNode.h.
View newest version in sPHENIX GitHub at line 36 of file PHDataNode.h
Referenced by PHDataNode< PHDWORD >::getData(), PHNodeIOManager::reconstructNodeTree(), and PHDataNode< PHDWORD >::setData().
The documentation for this class was generated from the following file:
coresoftware/blob/master/offline/framework/phool/PHDataNode.h