Analysis Software: ParticleFlowElement Class Reference
ParticleFlowElement Class Reference
#include <coresoftware/blob/master/offline/packages/particleflow/ParticleFlowElement.h>
Public Types
enum PFLOWTYPE {
UNASSIGNED = -1, MATCHED_CHARGED_HADRON = 0, UNMATCHED_CHARGED_HADRON = 1, UNMATCHED_EM_PARTICLE = 2,
UNMATCHED_NEUTRAL_HADRON = 3, LEFTOVER_EM_PARTICLE = 4
}
Public Member Functions
ParticleFlowElement ()
~ParticleFlowElement () override
void identify (std::ostream &os=std::cout) const override
int isValid () const override
isValid returns non zero if object contains vailid data
virtual unsigned int get_id () const
virtual void set_id (unsigned int)
virtual
ParticleFlowElement::PFLOWTYPE get_type () const
virtual void set_type (ParticleFlowElement::PFLOWTYPE)
virtual float get_px () const
virtual void set_px (float)
virtual float get_py () const
virtual void set_py (float)
virtual float get_pz () const
virtual void set_pz (float)
virtual float get_e () const
virtual void set_e (float)
virtual SvtxTrack * get_track () const
virtual void set_track (SvtxTrack *)
virtual std::vector< RawCluster * > get_eclusters () const
virtual void set_eclusters (const std::vector< RawCluster * > &)
virtual RawCluster * get_hcluster () const
virtual void set_hcluster (RawCluster *)
virtual float get_p () const
virtual float get_pt () const
virtual float get_et () const
virtual float get_eta () const
virtual float get_phi () const
virtual float get_mass () const
ClassDefOverride (ParticleFlowElement, 1)
Public Member Functions inherited from PHObject
PHObject ()
ctor
~PHObject () override
dtor
virtual PHObject * CloneMe () const
Virtual copy constructor.
virtual PHObject * clone () const final
PHObject * Clone (const char *newname="") const final
void Copy (TObject &object) const final
virtual void Reset ()
Clear Event.
virtual int Integrate () const
virtual int Integrate (PHObject *)
virtual void CopyFrom (const PHObject *obj)
Detailed Description
Definition at line 18 of file ParticleFlowElement.h.
View newest version in sPHENIX GitHub at line 18 of file ParticleFlowElement.h
Member Enumeration Documentation
enum ParticleFlowElement::PFLOWTYPE
Enumerator:
UNASSIGNED
MATCHED_CHARGED_HADRON
UNMATCHED_CHARGED_HADRON
UNMATCHED_EM_PARTICLE
UNMATCHED_NEUTRAL_HADRON
LEFTOVER_EM_PARTICLE
Definition at line 23 of file ParticleFlowElement.h.
View newest version in sPHENIX GitHub at line 23 of file ParticleFlowElement.h
Constructor & Destructor Documentation
ParticleFlowElement::ParticleFlowElement () inline
Definition at line 33 of file ParticleFlowElement.h.
View newest version in sPHENIX GitHub at line 33 of file ParticleFlowElement.h
ParticleFlowElement::~ParticleFlowElement () inline override
Definition at line 34 of file ParticleFlowElement.h.
View newest version in sPHENIX GitHub at line 34 of file ParticleFlowElement.h
Member Function Documentation
ParticleFlowElement::ClassDefOverride (ParticleFlowElement , 1)
virtual float ParticleFlowElement::get_e () const inline virtual
Reimplemented in ParticleFlowElementv1.
Definition at line 54 of file ParticleFlowElement.h.
View newest version in sPHENIX GitHub at line 54 of file ParticleFlowElement.h
Referenced by ResonanceJetTagging::addParticleFlow(), ParticleFlowJetInput::get_input(), TracksInJets::process_event(), FullJetFinder::process_event(), and DumpParticleFlowElementContainer::process_Node().
virtual std::vector<RawCluster*> ParticleFlowElement::get_eclusters () const inline virtual
Reimplemented in ParticleFlowElementv1.
Definition at line 60 of file ParticleFlowElement.h.
View newest version in sPHENIX GitHub at line 60 of file ParticleFlowElement.h
virtual float ParticleFlowElement::get_et () const inline virtual
Reimplemented in ParticleFlowElementv1.
Definition at line 68 of file ParticleFlowElement.h.
View newest version in sPHENIX GitHub at line 68 of file ParticleFlowElement.h
Referenced by DumpParticleFlowElementContainer::process_Node().
virtual float ParticleFlowElement::get_eta () const inline virtual
Reimplemented in ParticleFlowElementv1.
Definition at line 69 of file ParticleFlowElement.h.
View newest version in sPHENIX GitHub at line 69 of file ParticleFlowElement.h
Referenced by ResonanceJetTagging::isAcceptableParticleFlow(), FullJetFinder::process_event(), and DumpParticleFlowElementContainer::process_Node().
virtual RawCluster* ParticleFlowElement::get_hcluster () const inline virtual
Reimplemented in ParticleFlowElementv1.
Definition at line 63 of file ParticleFlowElement.h.
View newest version in sPHENIX GitHub at line 63 of file ParticleFlowElement.h
virtual unsigned int ParticleFlowElement::get_id () const inline virtual
Reimplemented in ParticleFlowElementv1.
Definition at line 39 of file ParticleFlowElement.h.
View newest version in sPHENIX GitHub at line 39 of file ParticleFlowElement.h
Referenced by ResonanceJetTagging::addParticleFlow(), ParticleFlowJetInput::get_input(), and DumpParticleFlowElementContainer::process_Node().
virtual float ParticleFlowElement::get_mass () const inline virtual
Reimplemented in ParticleFlowElementv1.
Definition at line 71 of file ParticleFlowElement.h.
View newest version in sPHENIX GitHub at line 71 of file ParticleFlowElement.h
Referenced by DumpParticleFlowElementContainer::process_Node().
virtual float ParticleFlowElement::get_p () const inline virtual
Reimplemented in ParticleFlowElementv1.
Definition at line 66 of file ParticleFlowElement.h.
View newest version in sPHENIX GitHub at line 66 of file ParticleFlowElement.h
Referenced by DumpParticleFlowElementContainer::process_Node().
virtual float ParticleFlowElement::get_phi () const inline virtual
Reimplemented in ParticleFlowElementv1.
Definition at line 70 of file ParticleFlowElement.h.
View newest version in sPHENIX GitHub at line 70 of file ParticleFlowElement.h
Referenced by FullJetFinder::process_event(), and DumpParticleFlowElementContainer::process_Node().
virtual float ParticleFlowElement::get_pt () const inline virtual
Reimplemented in ParticleFlowElementv1.
Definition at line 67 of file ParticleFlowElement.h.
View newest version in sPHENIX GitHub at line 67 of file ParticleFlowElement.h
Referenced by FullJetFinder::process_event(), and DumpParticleFlowElementContainer::process_Node().
virtual float ParticleFlowElement::get_px () const inline virtual
Reimplemented in ParticleFlowElementv1.
Definition at line 45 of file ParticleFlowElement.h.
View newest version in sPHENIX GitHub at line 45 of file ParticleFlowElement.h
Referenced by ResonanceJetTagging::addParticleFlow(), ParticleFlowJetInput::get_input(), TracksInJets::process_event(), and DumpParticleFlowElementContainer::process_Node().
virtual float ParticleFlowElement::get_py () const inline virtual
Reimplemented in ParticleFlowElementv1.
Definition at line 48 of file ParticleFlowElement.h.
View newest version in sPHENIX GitHub at line 48 of file ParticleFlowElement.h
Referenced by ResonanceJetTagging::addParticleFlow(), ParticleFlowJetInput::get_input(), TracksInJets::process_event(), and DumpParticleFlowElementContainer::process_Node().
virtual float ParticleFlowElement::get_pz () const inline virtual
Reimplemented in ParticleFlowElementv1.
Definition at line 51 of file ParticleFlowElement.h.
View newest version in sPHENIX GitHub at line 51 of file ParticleFlowElement.h
Referenced by ResonanceJetTagging::addParticleFlow(), ParticleFlowJetInput::get_input(), TracksInJets::process_event(), and DumpParticleFlowElementContainer::process_Node().
virtual SvtxTrack* ParticleFlowElement::get_track () const inline virtual
Reimplemented in ParticleFlowElementv1.
Definition at line 57 of file ParticleFlowElement.h.
View newest version in sPHENIX GitHub at line 57 of file ParticleFlowElement.h
Referenced by ResonanceJetTagging::addParticleFlow(), and FullJetFinder::process_event().
virtual ParticleFlowElement::PFLOWTYPE ParticleFlowElement::get_type () const inline virtual
Reimplemented in ParticleFlowElementv1.
Definition at line 42 of file ParticleFlowElement.h.
View newest version in sPHENIX GitHub at line 42 of file ParticleFlowElement.h
Referenced by TracksInJets::process_event(), FullJetFinder::process_event(), and DumpParticleFlowElementContainer::process_Node().
void ParticleFlowElement::identify (std::ostream & os = std::cout) const override virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from PHObject.
Reimplemented in ParticleFlowElementv1.
Definition at line 5 of file ParticleFlowElement.cc.
View newest version in sPHENIX GitHub at line 5 of file ParticleFlowElement.cc
int ParticleFlowElement::isValid () const inline override virtual
isValid returns non zero if object contains vailid data
Reimplemented from PHObject.
Reimplemented in ParticleFlowElementv1.
Definition at line 37 of file ParticleFlowElement.h.
View newest version in sPHENIX GitHub at line 37 of file ParticleFlowElement.h
virtual void ParticleFlowElement::set_e (float) inline virtual
Reimplemented in ParticleFlowElementv1.
Definition at line 55 of file ParticleFlowElement.h.
View newest version in sPHENIX GitHub at line 55 of file ParticleFlowElement.h
Referenced by ParticleFlowReco::process_event().
virtual void ParticleFlowElement::set_eclusters (const std::vector< RawCluster * > &) inline virtual
Reimplemented in ParticleFlowElementv1.
Definition at line 61 of file ParticleFlowElement.h.
View newest version in sPHENIX GitHub at line 61 of file ParticleFlowElement.h
Referenced by ParticleFlowReco::process_event().
virtual void ParticleFlowElement::set_hcluster (RawCluster *) inline virtual
Reimplemented in ParticleFlowElementv1.
Definition at line 64 of file ParticleFlowElement.h.
View newest version in sPHENIX GitHub at line 64 of file ParticleFlowElement.h
Referenced by ParticleFlowReco::process_event().
virtual void ParticleFlowElement::set_id (unsigned int) inline virtual
Reimplemented in ParticleFlowElementv1.
Definition at line 40 of file ParticleFlowElement.h.
View newest version in sPHENIX GitHub at line 40 of file ParticleFlowElement.h
Referenced by ParticleFlowReco::process_event().
virtual void ParticleFlowElement::set_px (float) inline virtual
Reimplemented in ParticleFlowElementv1.
Definition at line 46 of file ParticleFlowElement.h.
View newest version in sPHENIX GitHub at line 46 of file ParticleFlowElement.h
Referenced by ParticleFlowReco::process_event().
virtual void ParticleFlowElement::set_py (float) inline virtual
Reimplemented in ParticleFlowElementv1.
Definition at line 49 of file ParticleFlowElement.h.
View newest version in sPHENIX GitHub at line 49 of file ParticleFlowElement.h
Referenced by ParticleFlowReco::process_event().
virtual void ParticleFlowElement::set_pz (float) inline virtual
Reimplemented in ParticleFlowElementv1.
Definition at line 52 of file ParticleFlowElement.h.
View newest version in sPHENIX GitHub at line 52 of file ParticleFlowElement.h
Referenced by ParticleFlowReco::process_event().
virtual void ParticleFlowElement::set_track (SvtxTrack *) inline virtual
Reimplemented in ParticleFlowElementv1.
Definition at line 58 of file ParticleFlowElement.h.
View newest version in sPHENIX GitHub at line 58 of file ParticleFlowElement.h
Referenced by ParticleFlowReco::process_event().
virtual void ParticleFlowElement::set_type (ParticleFlowElement::PFLOWTYPE) inline virtual
Reimplemented in ParticleFlowElementv1.
Definition at line 43 of file ParticleFlowElement.h.
View newest version in sPHENIX GitHub at line 43 of file ParticleFlowElement.h
Referenced by ParticleFlowReco::process_event().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/particleflow/ParticleFlowElement.h
coresoftware/blob/master/offline/packages/particleflow/ParticleFlowElement.cc