Analysis Software: PHG4ScintillatorSlat Class Reference
PHG4ScintillatorSlat Class Reference abstract
#include <coresoftware/blob/master/simulation/g4simulation/g4detectors/PHG4ScintillatorSlat.h>
Public Member Functions
~PHG4ScintillatorSlat () override
void identify (std::ostream &os=std::cout) const override
virtual void add_edep (const double, const double, const double)
virtual void set_key (const PHG4ScintillatorSlatDefs::keytype)
virtual void add_hit_key (PHG4HitDefs::keytype)
virtual short get_column () const
virtual short get_row () const
virtual
PHG4ScintillatorSlatDefs::keytype get_key () const
virtual double get_edep () const
virtual double get_eion () const
virtual double get_light_yield () const
virtual std::pair< std::set
< PHG4HitDefs::keytype >
::const_iterator, std::set
< PHG4HitDefs::keytype >
::const_iterator > get_hit_ids () const =0
Public Member Functions inherited from PHObject
PHObject ()
ctor
~PHObject () override
dtor
virtual PHObject * CloneMe () const
Virtual copy constructor.
virtual PHObject * clone () const final
PHObject * Clone (const char *newname="") const final
void Copy (TObject &object) const final
virtual void Reset ()
Clear Event.
virtual int isValid () const
isValid returns non zero if object contains vailid data
virtual int Integrate () const
virtual int Integrate (PHObject *)
virtual void CopyFrom (const PHObject *obj)
Protected Member Functions
PHG4ScintillatorSlat ()
Detailed Description
Definition at line 14 of file PHG4ScintillatorSlat.h.
View newest version in sPHENIX GitHub at line 14 of file PHG4ScintillatorSlat.h
Constructor & Destructor Documentation
PHG4ScintillatorSlat::~PHG4ScintillatorSlat () inline override
Definition at line 17 of file PHG4ScintillatorSlat.h.
View newest version in sPHENIX GitHub at line 17 of file PHG4ScintillatorSlat.h
PHG4ScintillatorSlat::PHG4ScintillatorSlat () inline protected
Definition at line 40 of file PHG4ScintillatorSlat.h.
View newest version in sPHENIX GitHub at line 40 of file PHG4ScintillatorSlat.h
Member Function Documentation
virtual void PHG4ScintillatorSlat::add_edep (const double , const double , const double) inline virtual
Reimplemented in PHG4ScintillatorSlatv1.
Definition at line 25 of file PHG4ScintillatorSlat.h.
View newest version in sPHENIX GitHub at line 25 of file PHG4ScintillatorSlat.h
virtual void PHG4ScintillatorSlat::add_hit_key (PHG4HitDefs::keytype) inline virtual
Reimplemented in PHG4ScintillatorSlatv1.
Definition at line 28 of file PHG4ScintillatorSlat.h.
View newest version in sPHENIX GitHub at line 28 of file PHG4ScintillatorSlat.h
virtual short PHG4ScintillatorSlat::get_column () const inline virtual
Reimplemented in PHG4ScintillatorSlatv1.
Definition at line 30 of file PHG4ScintillatorSlat.h.
View newest version in sPHENIX GitHub at line 30 of file PHG4ScintillatorSlat.h
Referenced by Prototype2RawTowerBuilder::process_event(), and HCalib::process_event().
virtual double PHG4ScintillatorSlat::get_edep () const inline virtual
Reimplemented in PHG4ScintillatorSlatv1.
Definition at line 34 of file PHG4ScintillatorSlat.h.
View newest version in sPHENIX GitHub at line 34 of file PHG4ScintillatorSlat.h
Referenced by Prototype2RawTowerBuilder::process_event(), and G4ScintillatorSlatTTree::process_event().
virtual double PHG4ScintillatorSlat::get_eion () const inline virtual
Reimplemented in PHG4ScintillatorSlatv1.
Definition at line 35 of file PHG4ScintillatorSlat.h.
View newest version in sPHENIX GitHub at line 35 of file PHG4ScintillatorSlat.h
Referenced by Prototype2RawTowerBuilder::process_event().
virtual std::pair<std::set<PHG4HitDefs::keytype>::const_iterator, std::set<PHG4HitDefs::keytype>::const_iterator> PHG4ScintillatorSlat::get_hit_ids () const pure virtual
Implemented in PHG4ScintillatorSlatv1.
virtual PHG4ScintillatorSlatDefs::keytype PHG4ScintillatorSlat::get_key () const inline virtual
Reimplemented in PHG4ScintillatorSlatv1.
Definition at line 32 of file PHG4ScintillatorSlat.h.
View newest version in sPHENIX GitHub at line 32 of file PHG4ScintillatorSlat.h
Referenced by Prototype2RawTowerBuilder::process_event().
virtual double PHG4ScintillatorSlat::get_light_yield () const inline virtual
Reimplemented in PHG4ScintillatorSlatv1.
Definition at line 36 of file PHG4ScintillatorSlat.h.
View newest version in sPHENIX GitHub at line 36 of file PHG4ScintillatorSlat.h
Referenced by Prototype2RawTowerBuilder::process_event(), and HCalib::process_event().
virtual short PHG4ScintillatorSlat::get_row () const inline virtual
Reimplemented in PHG4ScintillatorSlatv1.
Definition at line 31 of file PHG4ScintillatorSlat.h.
View newest version in sPHENIX GitHub at line 31 of file PHG4ScintillatorSlat.h
Referenced by Prototype2RawTowerBuilder::process_event(), and HCalib::process_event().
void PHG4ScintillatorSlat::identify (std::ostream & os = std::cout) const inline override virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from PHObject.
Reimplemented in PHG4ScintillatorSlatv1.
Definition at line 20 of file PHG4ScintillatorSlat.h.
View newest version in sPHENIX GitHub at line 20 of file PHG4ScintillatorSlat.h
References os.
Referenced by Prototype2RawTowerBuilder::process_event().
virtual void PHG4ScintillatorSlat::set_key (const PHG4ScintillatorSlatDefs::keytype) inline virtual
Reimplemented in PHG4ScintillatorSlatv1.
Definition at line 27 of file PHG4ScintillatorSlat.h.
View newest version in sPHENIX GitHub at line 27 of file PHG4ScintillatorSlat.h
Referenced by PHG4ScintillatorSlatContainer::AddScintillatorSlat().
The documentation for this class was generated from the following file:
coresoftware/blob/master/simulation/g4simulation/g4detectors/PHG4ScintillatorSlat.h