Analysis Software: Acts::PassiveLayerBuilder Class Reference
Acts::PassiveLayerBuilder Class Reference
#include <acts/blob/sPHENIX/Core/include/Acts/Geometry/PassiveLayerBuilder.hpp>
Classes
struct Config
Public Member Functions
PassiveLayerBuilder (const Config &plConfig, std::unique_ptr< const Logger > logger=getDefaultLogger("PassiveLayerBuilder", Logging::INFO))
~PassiveLayerBuilder () override=default
Destructor.
const LayerVector negativeLayers (const GeometryContext &gctx) const override
const LayerVector centralLayers (const GeometryContext &gctx) const override
const LayerVector positiveLayers (const GeometryContext &gctx) const override
const std::string & identification () const override
void setConfiguration (const Config &plConfig)
Config getConfiguration () const
Get configuration method.
void setLogger (std::unique_ptr< const Logger > newLogger)
Public Member Functions inherited from Acts::ILayerBuilder
virtual ~ILayerBuilder ()=default
Virtual destructor.
Protected Attributes
Config m_cfg
configuration
Private Member Functions
const LayerVector endcapLayers (const GeometryContext &gctx, int side) const
const Logger & logger () const
Private Attributes
std::unique_ptr< const Logger > m_logger
logging instance
Detailed Description
The PassiveLayerBuilder is able to build cylinder & disc layers with given dimensions and material. The specifications of the layers have to be given by the configuration struct.
Definition at line 29 of file PassiveLayerBuilder.hpp.
View newest version in sPHENIX GitHub at line 29 of file PassiveLayerBuilder.hpp
Constructor & Destructor Documentation
Acts::PassiveLayerBuilder::PassiveLayerBuilder (const Config & plConfig, std::unique_ptr< const Logger > logger = getDefaultLogger("PassiveLayerBuilder", Logging::INFO))
Constructor
Parameters
plConfig is the ocnfiguration struct that steers behavior
logger logging instance
Definition at line 28 of file PassiveLayerBuilder.cpp.
View newest version in sPHENIX GitHub at line 28 of file PassiveLayerBuilder.cpp
References setConfiguration().
Acts::PassiveLayerBuilder::~PassiveLayerBuilder () override default
Destructor.
Member Function Documentation
const Acts::LayerVector Acts::PassiveLayerBuilder::centralLayers (const GeometryContext & gctx) const override virtual
LayerBuilder interface method
Parameters
gctx is the geometry context under which the geometry is built
Returns
the layers at the central sector
Implements Acts::ILayerBuilder.
Definition at line 100 of file PassiveLayerBuilder.cpp.
View newest version in sPHENIX GitHub at line 100 of file PassiveLayerBuilder.cpp
References ACTS_DEBUG, Acts::ACTS_VERBOSE(), Acts::CylinderLayer::create(), m_cfg(), material, and physmon_ckf_tracking::u.
const Acts::LayerVector Acts::PassiveLayerBuilder::endcapLayers (const GeometryContext & gctx, int side) const private
Helper interface method
Parameters
gctx is the geometry context under which the geometry is built
side is the side of the layer to be built
Returns
the layers at positive side
Definition at line 56 of file PassiveLayerBuilder.cpp.
View newest version in sPHENIX GitHub at line 56 of file PassiveLayerBuilder.cpp
References ACTS_DEBUG, Acts::ACTS_VERBOSE(), Acts::DiscLayer::create(), m_cfg(), material, and physmon_ckf_tracking::u.
PassiveLayerBuilder::Config Acts::PassiveLayerBuilder::getConfiguration () const inline
Get configuration method.
Definition at line 127 of file PassiveLayerBuilder.hpp.
View newest version in sPHENIX GitHub at line 127 of file PassiveLayerBuilder.hpp
References m_cfg.
const std::string& Acts::PassiveLayerBuilder::identification () const inline override virtual
Name identification
Returns
the string based identification
Implements Acts::ILayerBuilder.
Definition at line 90 of file PassiveLayerBuilder.hpp.
View newest version in sPHENIX GitHub at line 90 of file PassiveLayerBuilder.hpp
References Acts::PassiveLayerBuilder::Config::layerIdentification, and m_cfg.
const Logger& Acts::PassiveLayerBuilder::logger () const inline private
Definition at line 121 of file PassiveLayerBuilder.hpp.
View newest version in sPHENIX GitHub at line 121 of file PassiveLayerBuilder.hpp
References m_logger.
const Acts::LayerVector Acts::PassiveLayerBuilder::negativeLayers (const GeometryContext & gctx) const override virtual
LayerBuilder interface method
Parameters
gctx is the geometry context under which the geometry is built
Returns
the layers at negative side
Implements Acts::ILayerBuilder.
Definition at line 51 of file PassiveLayerBuilder.cpp.
View newest version in sPHENIX GitHub at line 51 of file PassiveLayerBuilder.cpp
const Acts::LayerVector Acts::PassiveLayerBuilder::positiveLayers (const GeometryContext & gctx) const override virtual
LayerBuilder interface method
Parameters
gctx is the geometry context under which the geometry is built
Returns
the layers at positive side
Implements Acts::ILayerBuilder.
Definition at line 46 of file PassiveLayerBuilder.cpp.
View newest version in sPHENIX GitHub at line 46 of file PassiveLayerBuilder.cpp
void Acts::PassiveLayerBuilder::setConfiguration (const Config & plConfig)
Set configuration method
Parameters
plConfig is a configuration struct it overwrites the current configuration
<
Definition at line 35 of file PassiveLayerBuilder.cpp.
View newest version in sPHENIX GitHub at line 35 of file PassiveLayerBuilder.cpp
References m_cfg().
Referenced by PassiveLayerBuilder().
void Acts::PassiveLayerBuilder::setLogger (std::unique_ptr< const Logger > newLogger)
Set logging instance
Parameters
newLogger the logger instance
Definition at line 41 of file PassiveLayerBuilder.cpp.
View newest version in sPHENIX GitHub at line 41 of file PassiveLayerBuilder.cpp
References m_logger, and testing::internal::move().
Member Data Documentation
Config Acts::PassiveLayerBuilder::m_cfg protected
configuration
Definition at line 109 of file PassiveLayerBuilder.hpp.
View newest version in sPHENIX GitHub at line 109 of file PassiveLayerBuilder.hpp
Referenced by getConfiguration(), and identification().
std::unique_ptr<const Logger> Acts::PassiveLayerBuilder::m_logger private
logging instance
Definition at line 124 of file PassiveLayerBuilder.hpp.
View newest version in sPHENIX GitHub at line 124 of file PassiveLayerBuilder.hpp
Referenced by logger().
The documentation for this class was generated from the following files:
acts/blob/sPHENIX/Core/include/Acts/Geometry/PassiveLayerBuilder.hpp
acts/blob/sPHENIX/Core/src/Geometry/PassiveLayerBuilder.cpp