Analysis Software: CMFlashDifferenceContainerv1 Class Reference
CMFlashDifferenceContainerv1 Class Reference
CM flash difference container object.
#include <coresoftware/blob/master/offline/packages/trackbase/CMFlashDifferenceContainerv1.h>
Public Types
typedef std::map< unsigned int,
CMFlashDifference * > Map
typedef Map::iterator Iterator
typedef Map::const_iterator ConstIterator
typedef std::pair< Iterator,
Iterator > Range
typedef std::pair
< ConstIterator, ConstIterator > ConstRange
Public Types inherited from CMFlashDifferenceContainer
using Map = std::map< unsigned int, CMFlashDifference * >
using Iterator = Map::iterator
using ConstIterator = Map::const_iterator
using Range = std::pair< Iterator, Iterator >
using ConstRange = std::pair< ConstIterator, ConstIterator >
Public Member Functions
CMFlashDifferenceContainerv1 ()=default
void Reset () override
reset method
void identify (std::ostream &os=std::cout) const override
identify object
void addDifferenceSpecifyKey (const unsigned int, CMFlashDifference *newClus) override
add a differences with specific key
void removeDifference (unsigned int) override
remove differences
ConstRange getDifferences () const override
return all differences
CMFlashDifference * findDifference (unsigned int key) const override
find differences matching given key
unsigned int size () const override
total number of differences
Private Attributes
Map m_map
Additional Inherited Members
Protected Member Functions inherited from CMFlashDifferenceContainer
CMFlashDifferenceContainer ()=default
constructor
Detailed Description
CM flash difference container object.
Container for CMFlashDifference objects
Definition at line 25 of file CMFlashDifferenceContainerv1.h.
View newest version in sPHENIX GitHub at line 25 of file CMFlashDifferenceContainerv1.h
Member Typedef Documentation
typedef Map::const_iterator CMFlashDifferenceContainerv1::ConstIterator
Definition at line 30 of file CMFlashDifferenceContainerv1.h.
View newest version in sPHENIX GitHub at line 30 of file CMFlashDifferenceContainerv1.h
typedef std::pair<ConstIterator, ConstIterator> CMFlashDifferenceContainerv1::ConstRange
Definition at line 32 of file CMFlashDifferenceContainerv1.h.
View newest version in sPHENIX GitHub at line 32 of file CMFlashDifferenceContainerv1.h
typedef Map::iterator CMFlashDifferenceContainerv1::Iterator
Definition at line 29 of file CMFlashDifferenceContainerv1.h.
View newest version in sPHENIX GitHub at line 29 of file CMFlashDifferenceContainerv1.h
typedef std::map<unsigned int, CMFlashDifference *> CMFlashDifferenceContainerv1::Map
Definition at line 28 of file CMFlashDifferenceContainerv1.h.
View newest version in sPHENIX GitHub at line 28 of file CMFlashDifferenceContainerv1.h
typedef std::pair<Iterator, Iterator> CMFlashDifferenceContainerv1::Range
Definition at line 31 of file CMFlashDifferenceContainerv1.h.
View newest version in sPHENIX GitHub at line 31 of file CMFlashDifferenceContainerv1.h
Constructor & Destructor Documentation
CMFlashDifferenceContainerv1::CMFlashDifferenceContainerv1 () default
Member Function Documentation
void CMFlashDifferenceContainerv1::addDifferenceSpecifyKey (const unsigned int, CMFlashDifference *) override virtual
add a differences with specific key
Implements CMFlashDifferenceContainer.
Definition at line 38 of file CMFlashDifferenceContainerv1.cc.
View newest version in sPHENIX GitHub at line 38 of file CMFlashDifferenceContainerv1.cc
References m_map.
CMFlashDifference * CMFlashDifferenceContainerv1::findDifference (unsigned int) const override virtual
find differences matching given key
Reimplemented from CMFlashDifferenceContainer.
Definition at line 60 of file CMFlashDifferenceContainerv1.cc.
View newest version in sPHENIX GitHub at line 60 of file CMFlashDifferenceContainerv1.cc
References it, and m_map.
Referenced by removeDifference().
CMFlashDifferenceContainer::ConstRange CMFlashDifferenceContainerv1::getDifferences () const override virtual
return all differences
Implements CMFlashDifferenceContainer.
Definition at line 56 of file CMFlashDifferenceContainerv1.cc.
View newest version in sPHENIX GitHub at line 56 of file CMFlashDifferenceContainerv1.cc
References m_map.
void CMFlashDifferenceContainerv1::identify (std::ostream & = std::cout) const override virtual
identify object
Reimplemented from CMFlashDifferenceContainer.
Definition at line 23 of file CMFlashDifferenceContainerv1.cc.
View newest version in sPHENIX GitHub at line 23 of file CMFlashDifferenceContainerv1.cc
References m_map, and size().
void CMFlashDifferenceContainerv1::removeDifference (unsigned int) override virtual
remove differences
Reimplemented from CMFlashDifferenceContainer.
Definition at line 48 of file CMFlashDifferenceContainerv1.cc.
View newest version in sPHENIX GitHub at line 48 of file CMFlashDifferenceContainerv1.cc
References findDifference(), and m_map.
void CMFlashDifferenceContainerv1::Reset () override virtual
reset method
Reimplemented from CMFlashDifferenceContainer.
Definition at line 13 of file CMFlashDifferenceContainerv1.cc.
View newest version in sPHENIX GitHub at line 13 of file CMFlashDifferenceContainerv1.cc
References m_map.
unsigned int CMFlashDifferenceContainerv1::size (void) const override virtual
total number of differences
Reimplemented from CMFlashDifferenceContainer.
Definition at line 66 of file CMFlashDifferenceContainerv1.cc.
View newest version in sPHENIX GitHub at line 66 of file CMFlashDifferenceContainerv1.cc
References m_map.
Referenced by identify().
Member Data Documentation
Map CMFlashDifferenceContainerv1::m_map private
Definition at line 51 of file CMFlashDifferenceContainerv1.h.
View newest version in sPHENIX GitHub at line 51 of file CMFlashDifferenceContainerv1.h
Referenced by addDifferenceSpecifyKey(), findDifference(), getDifferences(), identify(), removeDifference(), Reset(), and size().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/trackbase/CMFlashDifferenceContainerv1.h
coresoftware/blob/master/offline/packages/trackbase/CMFlashDifferenceContainerv1.cc