Analysis Software: jetHistogrammer Class Reference
jetHistogrammer Class Reference
#include <analysis/blob/master/pythiaInfo/src/jetHistogrammer.h>
Public Member Functions
jetHistogrammer (const std::string &name="jetHistogrammer", const std::string &fileout="jetHistogrammer.root")
~jetHistogrammer () override
int Init (PHCompositeNode *topNode) override
int InitRun (PHCompositeNode *topNode) override
int process_event (PHCompositeNode *topNode) override
int ResetEvent (PHCompositeNode *topNode) override
Clean up internals after each event.
int EndRun (const int runnumber) override
Called at the end of each run.
int End (PHCompositeNode *topNode) override
Called at the end of all processing.
int Reset (PHCompositeNode *) override
Reset.
void Print (const std::string &what="ALL") const override
Public Member Functions inherited from SubsysReco
~SubsysReco () override
void Print (const std::string &="ALL") const override
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Private Member Functions
int getEtaBin (float eta)
Private Attributes
TH1F * ptGJet [nEtaBins]
TH1F * ptPJet
std::string m_outputFilename
float etaBins [nEtaBins] = {0,0.7,1.1,1.5}
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = std::numeric_limits<int>::max() - 10
}
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Detailed Description
Definition at line 15 of file jetHistogrammer.h.
View newest version in sPHENIX GitHub at line 15 of file jetHistogrammer.h
Constructor & Destructor Documentation
jetHistogrammer::jetHistogrammer (const std::string & name = "jetHistogrammer", const std::string & fileout = "jetHistogrammer.root")
Definition at line 46 of file jetHistogrammer.cc.
View newest version in sPHENIX GitHub at line 46 of file jetHistogrammer.cc
jetHistogrammer::~jetHistogrammer () override
Definition at line 54 of file jetHistogrammer.cc.
View newest version in sPHENIX GitHub at line 54 of file jetHistogrammer.cc
References i, nEtaBins, ptGJet, and ptPJet.
Member Function Documentation
int jetHistogrammer::End (PHCompositeNode * topNode) override virtual
Called at the end of all processing.
Reimplemented from SubsysReco.
Definition at line 202 of file jetHistogrammer.cc.
View newest version in sPHENIX GitHub at line 202 of file jetHistogrammer.cc
References Fun4AllReturnCodes::EVENT_OK, PHTFileServer::get(), i, m_outputFilename, nEtaBins, PHTFileServer::open(), ptGJet, ptPJet, and Write().
int jetHistogrammer::EndRun (const int runnumber) override virtual
Called at the end of each run.
Reimplemented from SubsysReco.
Definition at line 195 of file jetHistogrammer.cc.
View newest version in sPHENIX GitHub at line 195 of file jetHistogrammer.cc
References Fun4AllReturnCodes::EVENT_OK.
int jetHistogrammer::getEtaBin (float eta) private
Definition at line 227 of file jetHistogrammer.cc.
View newest version in sPHENIX GitHub at line 227 of file jetHistogrammer.cc
References etaBins, i, and nEtaBins.
Referenced by process_event().
int jetHistogrammer::Init (PHCompositeNode * topNode) override virtual
Called during initialization. Typically this is where you can book histograms, and e.g. register them to Fun4AllServer (so they can be output to file using Fun4AllServer::dumpHistos() method).
Reimplemented from SubsysReco.
Definition at line 63 of file jetHistogrammer.cc.
View newest version in sPHENIX GitHub at line 63 of file jetHistogrammer.cc
References bins, Fun4AllReturnCodes::EVENT_OK, i, nEtaBins, ptGJet, and ptPJet.
int jetHistogrammer::InitRun (PHCompositeNode * topNode) override virtual
Called for first event when run number is known. Typically this is where you may want to fetch data from database, because you know the run number. A place to book histograms which have to know the run number.
Reimplemented from SubsysReco.
Definition at line 84 of file jetHistogrammer.cc.
View newest version in sPHENIX GitHub at line 84 of file jetHistogrammer.cc
References Fun4AllReturnCodes::EVENT_OK.
void jetHistogrammer::Print (const std::string & what = "ALL") const override virtual
Print out some info about this module.
Parameters
what can be used to specify what to print exactly.
Reimplemented from Fun4AllBase.
Definition at line 222 of file jetHistogrammer.cc.
View newest version in sPHENIX GitHub at line 222 of file jetHistogrammer.cc
int jetHistogrammer::process_event (PHCompositeNode * topNode) override virtual
Called for each event. This is where you do the real work.
Reimplemented from SubsysReco.
Definition at line 91 of file jetHistogrammer.cc.
View newest version in sPHENIX GitHub at line 91 of file jetHistogrammer.cc
References antikt_algorithm, parse_cmake_options::begin, Best, E_scheme, end, Fun4AllReturnCodes::EVENT_OK, Fill(), getEtaBin(), i, momentum, nEtaBins, merge_hashes::p, physmon_track_finding_ttbar::pt, ptGJet, ptPJet, and utils::status.
int jetHistogrammer::Reset (PHCompositeNode * topNode) override virtual
Reset.
Reimplemented from SubsysReco.
Definition at line 215 of file jetHistogrammer.cc.
View newest version in sPHENIX GitHub at line 215 of file jetHistogrammer.cc
References Fun4AllReturnCodes::EVENT_OK.
int jetHistogrammer::ResetEvent (PHCompositeNode * topNode) override virtual
Clean up internals after each event.
Reimplemented from SubsysReco.
Definition at line 189 of file jetHistogrammer.cc.
View newest version in sPHENIX GitHub at line 189 of file jetHistogrammer.cc
References Fun4AllReturnCodes::EVENT_OK.
Member Data Documentation
float jetHistogrammer::etaBins[nEtaBins] = {0,0.7,1.1,1.5} private
Definition at line 62 of file jetHistogrammer.h.
View newest version in sPHENIX GitHub at line 62 of file jetHistogrammer.h
Referenced by getEtaBin().
std::string jetHistogrammer::m_outputFilename private
Definition at line 60 of file jetHistogrammer.h.
View newest version in sPHENIX GitHub at line 60 of file jetHistogrammer.h
Referenced by End().
TH1F* jetHistogrammer::ptGJet[nEtaBins] private
Definition at line 58 of file jetHistogrammer.h.
View newest version in sPHENIX GitHub at line 58 of file jetHistogrammer.h
Referenced by End(), Init(), process_event(), and ~jetHistogrammer().
TH1F* jetHistogrammer::ptPJet private
Definition at line 59 of file jetHistogrammer.h.
View newest version in sPHENIX GitHub at line 59 of file jetHistogrammer.h
Referenced by End(), Init(), process_event(), and ~jetHistogrammer().
The documentation for this class was generated from the following files:
analysis/blob/master/pythiaInfo/src/jetHistogrammer.h
analysis/blob/master/pythiaInfo/src/jetHistogrammer.cc