Analysis Software: component
component
Typedefs
typedef std::multimap
< Jet::SRC, unsigned int > Jet::typ_comp_ids
typedef
typ_comp_ids::const_iterator Jet::ConstIter
typedef typ_comp_ids::iterator Jet::Iter
Functions
virtual bool Jet::empty_comp () const
virtual size_t Jet::size_comp () const
virtual size_t Jet::count_comp (Jet::SRC source) const
virtual void Jet::clear_comp ()
virtual void Jet::insert_comp (Jet::SRC source, unsigned int compid)
virtual size_t Jet::erase_comp (Jet::SRC source)
virtual void Jet::erase_comp (Iter iter)
virtual void Jet::erase_comp (Iter first, Iter last)
virtual ConstIter Jet::begin_comp () const
virtual ConstIter Jet::lower_bound_comp (Jet::SRC source) const
virtual ConstIter Jet::upper_bound_comp (Jet::SRC source) const
virtual ConstIter Jet::find (Jet::SRC source) const
virtual ConstIter Jet::end_comp () const
virtual Iter Jet::begin_comp ()
virtual Iter Jet::lower_bound_comp (Jet::SRC source)
virtual Iter Jet::upper_bound_comp (Jet::SRC source)
virtual Iter Jet::find (Jet::SRC source)
virtual Iter Jet::end_comp ()
Jet::ClassDefOverride (Jet, 1)
Detailed Description
clustered component methods (multimap interface based) source type id –> unique id within that storage
Typedef Documentation
typedef typ_comp_ids::const_iterator Jet::ConstIter
Definition at line 125 of file Jet.h.
View newest version in sPHENIX GitHub at line 125 of file Jet.h
typedef typ_comp_ids::iterator Jet::Iter
Definition at line 126 of file Jet.h.
View newest version in sPHENIX GitHub at line 126 of file Jet.h
typedef std::multimap<Jet::SRC, unsigned int> Jet::typ_comp_ids
Definition at line 124 of file Jet.h.
View newest version in sPHENIX GitHub at line 124 of file Jet.h
Function Documentation
Jet::ConstIter Jet::begin_comp () const virtual
Reimplemented in Jetv1.
Definition at line 13 of file Jet.cc.
View newest version in sPHENIX GitHub at line 13 of file Jet.cc
References DummyJetMap.
Referenced by LeptoquarksReco::AddJetInformation(), JetRecoEval::all_truth_hits(), JetRecoEval::all_truth_particles(), JetTruthEval::all_truth_particles(), JetRecoEval::all_truth_showers(), TreeMaker::CopyAndMakeJets(), JetRecoEval::get_energy_contribution(), FastJetAlgoSub::get_jets(), FastJetAlgo::get_jets(), JetTruthEval::get_truth_jet(), CopyAndSubtractJets::process_event(), DetermineTowerBackground::process_event(), and PhotonJet::process_event().
Jet::Iter Jet::begin_comp () virtual
Reimplemented in Jetv1.
Definition at line 38 of file Jet.cc.
View newest version in sPHENIX GitHub at line 38 of file Jet.cc
References DummyJetMap.
Jet::ClassDefOverride (Jet , 1)
virtual void Jet::clear_comp () inline virtual
Reimplemented in Jetv1.
Definition at line 132 of file Jet.h.
View newest version in sPHENIX GitHub at line 132 of file Jet.h
virtual size_t Jet::count_comp (Jet::SRC source) const inline virtual
Reimplemented in Jetv1.
Definition at line 130 of file Jet.h.
View newest version in sPHENIX GitHub at line 130 of file Jet.h
Referenced by LeptoquarksReco::AddJetInformation().
virtual bool Jet::empty_comp () const inline virtual
Reimplemented in Jetv1.
Definition at line 128 of file Jet.h.
View newest version in sPHENIX GitHub at line 128 of file Jet.h
Jet::ConstIter Jet::end_comp () const virtual
Reimplemented in Jetv1.
Definition at line 33 of file Jet.cc.
View newest version in sPHENIX GitHub at line 33 of file Jet.cc
References DummyJetMap.
Referenced by LeptoquarksReco::AddJetInformation(), JetRecoEval::all_truth_hits(), JetRecoEval::all_truth_particles(), JetTruthEval::all_truth_particles(), JetRecoEval::all_truth_showers(), TreeMaker::CopyAndMakeJets(), JetRecoEval::get_energy_contribution(), FastJetAlgoSub::get_jets(), FastJetAlgo::get_jets(), JetTruthEval::get_truth_jet(), CopyAndSubtractJets::process_event(), DetermineTowerBackground::process_event(), and PhotonJet::process_event().
Jet::Iter Jet::end_comp () virtual
Reimplemented in Jetv1.
Definition at line 58 of file Jet.cc.
View newest version in sPHENIX GitHub at line 58 of file Jet.cc
References DummyJetMap.
virtual size_t Jet::erase_comp (Jet::SRC source) inline virtual
Reimplemented in Jetv1.
Definition at line 134 of file Jet.h.
View newest version in sPHENIX GitHub at line 134 of file Jet.h
virtual void Jet::erase_comp (Iter iter) inline virtual
Reimplemented in Jetv1.
Definition at line 135 of file Jet.h.
View newest version in sPHENIX GitHub at line 135 of file Jet.h
virtual void Jet::erase_comp (Iter first, Iter last) inline virtual
Reimplemented in Jetv1.
Definition at line 136 of file Jet.h.
View newest version in sPHENIX GitHub at line 136 of file Jet.h
Jet::ConstIter Jet::find (Jet::SRC source) const virtual
Reimplemented in Jetv1.
Definition at line 28 of file Jet.cc.
View newest version in sPHENIX GitHub at line 28 of file Jet.cc
References DummyJetMap.
Jet::Iter Jet::find (Jet::SRC source) virtual
Reimplemented in Jetv1.
Definition at line 53 of file Jet.cc.
View newest version in sPHENIX GitHub at line 53 of file Jet.cc
References DummyJetMap.
virtual void Jet::insert_comp (Jet::SRC source, unsigned int compid) inline virtual
Reimplemented in Jetv1.
Definition at line 133 of file Jet.h.
View newest version in sPHENIX GitHub at line 133 of file Jet.h
Referenced by TowerJetInput::get_input(), TrackJetInput::get_input(), ParticleFlowJetInput::get_input(), ClusterJetInput::get_input(), TruthJetInput::get_input(), FastJetAlgoSub::get_jets(), FastJetAlgo::get_jets(), and JetHepMCLoader::process_event().
Jet::ConstIter Jet::lower_bound_comp (Jet::SRC source) const virtual
Reimplemented in Jetv1.
Definition at line 18 of file Jet.cc.
View newest version in sPHENIX GitHub at line 18 of file Jet.cc
References DummyJetMap.
Referenced by JetRecoEval::get_energy_contribution().
Jet::Iter Jet::lower_bound_comp (Jet::SRC source) virtual
Reimplemented in Jetv1.
Definition at line 43 of file Jet.cc.
View newest version in sPHENIX GitHub at line 43 of file Jet.cc
References DummyJetMap.
virtual size_t Jet::size_comp () const inline virtual
Reimplemented in Jetv1.
Definition at line 129 of file Jet.h.
View newest version in sPHENIX GitHub at line 129 of file Jet.h
Referenced by LeptoquarksReco::AddJetInformation(), JetEvaluator::fillOutputNtuples(), JetEnergies::fillOutputNtuples(), MyJetAnalysis::process_event(), BDiJetModule::process_event(), QAG4SimulationJet::process_Spectrum(), and SoftLeptonTaggingTruth::process_Spectrum().
Jet::ConstIter Jet::upper_bound_comp (Jet::SRC source) const virtual
Reimplemented in Jetv1.
Definition at line 23 of file Jet.cc.
View newest version in sPHENIX GitHub at line 23 of file Jet.cc
References DummyJetMap.
Referenced by JetRecoEval::get_energy_contribution().
Jet::Iter Jet::upper_bound_comp (Jet::SRC source) virtual
Reimplemented in Jetv1.
Definition at line 48 of file Jet.cc.
View newest version in sPHENIX GitHub at line 48 of file Jet.cc
References DummyJetMap.