Analysis Software: acts/blob/sPHENIX/Tests/UnitTests/Core/Utilities/DelegateTests.cpp File Reference
DelegateTests.cpp File Reference
#include <boost/test/data/test_case.hpp>
#include <boost/test/unit_test.hpp>
#include "Acts/Definitions/Algebra.hpp"
#include "Acts/Tests/CommonHelpers/FloatComparisons.hpp"
#include "Acts/Utilities/Delegate.hpp"
#include <memory>
#include <string>
#include <type_traits>
#include <utility>
#include <vector>
Classes
struct Subtractor
struct SignatureTest
struct CheckDestructor
struct DelegateInterface
struct ConcreteDelegate
struct SeparateDelegate
Functions
int sumImpl (int a, int b)
BOOST_AUTO_TEST_CASE (ConnectConstexprLambda)
float multiply (float a, float b)
BOOST_AUTO_TEST_CASE (ConnectFunctionPointer)
BOOST_AUTO_TEST_CASE (ConnectStruct)
int addition (const void *, int a, int b)
BOOST_AUTO_TEST_CASE (ConnectRuntime)
void modify (int &v, int a)
void noModify (int v, int a)
BOOST_AUTO_TEST_CASE (DelegateReference)
BOOST_AUTO_TEST_CASE (DelegateReferenceMember)
BOOST_AUTO_TEST_CASE (StatefullLambdas)
int owningTest ()
int owningTest2 (const void *)
BOOST_AUTO_TEST_CASE (OwningDelegateTest)
BOOST_AUTO_TEST_CASE (NonVoidDelegateTest)
Function Documentation
int addition (const void * , int a, int b)
Definition at line 90 of file DelegateTests.cpp.
View newest version in sPHENIX GitHub at line 90 of file DelegateTests.cpp
References KFPMath::b.
Referenced by BOOST_AUTO_TEST_CASE().
BOOST_AUTO_TEST_CASE (ConnectConstexprLambda)
Definition at line 32 of file DelegateTests.cpp.
View newest version in sPHENIX GitHub at line 32 of file DelegateTests.cpp
References KFPMath::a, KFPMath::b, sum(), and sumImpl().
BOOST_AUTO_TEST_CASE (ConnectFunctionPointer)
Definition at line 55 of file DelegateTests.cpp.
View newest version in sPHENIX GitHub at line 55 of file DelegateTests.cpp
References CHECK_CLOSE_REL, Acts::UnitConstants::e, and multiply().
BOOST_AUTO_TEST_CASE (ConnectStruct)
Definition at line 75 of file DelegateTests.cpp.
View newest version in sPHENIX GitHub at line 75 of file DelegateTests.cpp
References Subtractor::execute(), and physmon_simulation::s.
BOOST_AUTO_TEST_CASE (ConnectRuntime)
Definition at line 94 of file DelegateTests.cpp.
View newest version in sPHENIX GitHub at line 94 of file DelegateTests.cpp
References addition().
BOOST_AUTO_TEST_CASE (DelegateReference)
Definition at line 138 of file DelegateTests.cpp.
View newest version in sPHENIX GitHub at line 138 of file DelegateTests.cpp
References modify(), and testSigmaEff::v.
BOOST_AUTO_TEST_CASE (DelegateReferenceMember)
Definition at line 159 of file DelegateTests.cpp.
View newest version in sPHENIX GitHub at line 159 of file DelegateTests.cpp
References SignatureTest::modify(), physmon_simulation::s, and testSigmaEff::v.
BOOST_AUTO_TEST_CASE (StatefullLambdas)
Definition at line 172 of file DelegateTests.cpp.
View newest version in sPHENIX GitHub at line 172 of file DelegateTests.cpp
References n, and testSigmaEff::v.
BOOST_AUTO_TEST_CASE (OwningDelegateTest)
Definition at line 222 of file DelegateTests.cpp.
View newest version in sPHENIX GitHub at line 222 of file DelegateTests.cpp
References CheckDestructor::func(), SignatureTest::modify(), testing::internal::move(), owningTest(), owningTest2(), physmon_simulation::s, and testSigmaEff::v.
BOOST_AUTO_TEST_CASE (NonVoidDelegateTest)
Definition at line 352 of file DelegateTests.cpp.
View newest version in sPHENIX GitHub at line 352 of file DelegateTests.cpp
References Acts::PhysicalConstants::c, DelegateInterface::func(), and ConcreteDelegate::func().
void modify (int & v, int a)
Definition at line 129 of file DelegateTests.cpp.
View newest version in sPHENIX GitHub at line 129 of file DelegateTests.cpp
References KFPMath::a.
Referenced by BOOST_AUTO_TEST_CASE(), and test_components_modifying_accessors().
float multiply (float a, float b)
Definition at line 51 of file DelegateTests.cpp.
View newest version in sPHENIX GitHub at line 51 of file DelegateTests.cpp
References KFPMath::b.
Referenced by BOOST_AUTO_TEST_CASE(), and compare().
void noModify (int v, int a)
Definition at line 133 of file DelegateTests.cpp.
View newest version in sPHENIX GitHub at line 133 of file DelegateTests.cpp
References KFPMath::a.
int owningTest ()
Definition at line 214 of file DelegateTests.cpp.
View newest version in sPHENIX GitHub at line 214 of file DelegateTests.cpp
Referenced by BOOST_AUTO_TEST_CASE().
int owningTest2 (const void *)
Definition at line 218 of file DelegateTests.cpp.
View newest version in sPHENIX GitHub at line 218 of file DelegateTests.cpp
Referenced by BOOST_AUTO_TEST_CASE().
int sumImpl (int a, int b)
Definition at line 28 of file DelegateTests.cpp.
View newest version in sPHENIX GitHub at line 28 of file DelegateTests.cpp
References KFPMath::b.
Referenced by BOOST_AUTO_TEST_CASE().