Analysis Software: daqBuffer Class Reference
daqBuffer Class Reference
#include <rcdaq/blob/master/daqBuffer.h>
Classes
struct buffer_ptr
Public Member Functions
daqBuffer (const int irun=1, const int length=8 *1024 *1024+2 *8192, const int iseq=1, md5_state_t *md5state=0)
virtual ~daqBuffer ()
int nextEvent (const int etype, const int evtseq, const int maxsize)
int prepare_next (const int iseq, const int irun=-1)
unsigned int addSubevent (daq_device *)
unsigned int addEoB ()
int setCompression (const int flag)
int getCompression () const
unsigned int writeout (int fd)
unsigned int sendout (int fd)
unsigned int sendData (int fd, const int max_length)
int setMaxSize (const int size)
int getMaxSize () const
int getBufSeq () const
unsigned int getLength () const
int setEventFormat (const int f)
int getEventFormat () const
void setMD5State (md5_state_t *md5state)
md5_state_t * getMD5State () const
Protected Member Functions
int compress ()
Protected Attributes
int _broken
buffer_ptr bptr
int * data_ptr
int current_index
int max_length
int max_size
int left
daqEvent * current_event
int current_etype
int has_end
int format
int wants_compression
int currentBufferID
md5_state_t * _md5state
lzo_byte * wrkmem
lzo_uint outputarraylength
unsigned int * outputarray
Static Protected Attributes
static int lzo_initialized = 0
Detailed Description
Definition at line 29 of file daqBuffer.h.
View newest version in sPHENIX GitHub at line 29 of file daqBuffer.h
Constructor & Destructor Documentation
daqBuffer::daqBuffer (const int irun = 1, const int length = 8*1024*1024+2*8192, const int iseq = 1, md5_state_t * md5state = 0)
Definition at line 24 of file daqBuffer.cc.
View newest version in sPHENIX GitHub at line 24 of file daqBuffer.cc
References KFPMath::b, DAQONCSFORMAT, material_mapping_optimisation::format, G4PLUGDOOR::length, md5state, and ONCSBUFFERHEADER.
daqBuffer::~daqBuffer () virtual
Definition at line 52 of file daqBuffer.cc.
View newest version in sPHENIX GitHub at line 52 of file daqBuffer.cc
References KFPMath::b.
Member Function Documentation
unsigned int daqBuffer::addEoB ()
Definition at line 132 of file daqBuffer.cc.
View newest version in sPHENIX GitHub at line 132 of file daqBuffer.cc
Referenced by switch_buffer().
unsigned int daqBuffer::addSubevent (daq_device * dev)
Definition at line 118 of file daqBuffer.cc.
View newest version in sPHENIX GitHub at line 118 of file daqBuffer.cc
References left().
Referenced by readout().
int daqBuffer::compress () protected
Definition at line 288 of file daqBuffer.cc.
View newest version in sPHENIX GitHub at line 288 of file daqBuffer.cc
References BUFFERHEADERLENGTH, and LZO1XBUFFERMARKER.
int daqBuffer::getBufSeq () const inline
Definition at line 70 of file daqBuffer.h.
View newest version in sPHENIX GitHub at line 70 of file daqBuffer.h
References bptr, and daqBuffer::buffer_ptr::Bufseq.
int daqBuffer::getCompression () const inline
Definition at line 52 of file daqBuffer.h.
View newest version in sPHENIX GitHub at line 52 of file daqBuffer.h
References wants_compression.
Referenced by daq_status().
int daqBuffer::getEventFormat () const inline
Definition at line 74 of file daqBuffer.h.
View newest version in sPHENIX GitHub at line 74 of file daqBuffer.h
References format.
Referenced by daq_getEventFormat().
unsigned int daqBuffer::getLength () const inline
Definition at line 71 of file daqBuffer.h.
View newest version in sPHENIX GitHub at line 71 of file daqBuffer.h
References bptr, and daqBuffer::buffer_ptr::Length.
Referenced by switch_buffer().
int daqBuffer::getMaxSize () const
Definition at line 330 of file daqBuffer.cc.
View newest version in sPHENIX GitHub at line 330 of file daqBuffer.cc
Referenced by daq_begin(), and daq_status().
md5_state_t* daqBuffer::getMD5State () const inline
Definition at line 78 of file daqBuffer.h.
View newest version in sPHENIX GitHub at line 78 of file daqBuffer.h
References _md5state.
int daqBuffer::nextEvent (const int etype, const int evtseq, const int maxsize)
Definition at line 86 of file daqBuffer.cc.
View newest version in sPHENIX GitHub at line 86 of file daqBuffer.cc
References EOBLENGTH, EVTHEADERLENGTH, material_mapping_optimisation::format, and left().
Referenced by readout().
int daqBuffer::prepare_next (const int iseq, const int irun = -1)
Definition at line 62 of file daqBuffer.cc.
View newest version in sPHENIX GitHub at line 62 of file daqBuffer.cc
References BUFFERHEADERLENGTH, EOBLENGTH, and left().
Referenced by daq_begin(), and switch_buffer().
unsigned int daqBuffer::sendData (int fd, const int max_length)
Definition at line 224 of file daqBuffer.cc.
View newest version in sPHENIX GitHub at line 224 of file daqBuffer.cc
References merge_hashes::p, utils::status, and writen().
Referenced by sendMonitorData().
unsigned int daqBuffer::sendout (int fd)
Definition at line 192 of file daqBuffer.cc.
View newest version in sPHENIX GitHub at line 192 of file daqBuffer.cc
References CTRL_DATA, CTRL_REMOTESUCCESS, merge_hashes::p, readn(), utils::status, and writen().
Referenced by writebuffers().
int daqBuffer::setCompression (const int flag)
Definition at line 247 of file daqBuffer.cc.
View newest version in sPHENIX GitHub at line 247 of file daqBuffer.cc
Referenced by daq_set_compression().
int daqBuffer::setEventFormat (const int f)
Definition at line 335 of file daqBuffer.cc.
View newest version in sPHENIX GitHub at line 335 of file daqBuffer.cc
References DAQONCSFORMAT, DAQPRDFFORMAT, material_mapping_optimisation::format, ONCSBUFFERHEADER, and PRDFBUFFERHEADER.
Referenced by daq_setEventFormat(), and rcdaq_init().
int daqBuffer::setMaxSize (const int size)
Definition at line 311 of file daqBuffer.cc.
View newest version in sPHENIX GitHub at line 311 of file daqBuffer.cc
Referenced by daq_begin(), and daq_setmaxbuffersize().
void daqBuffer::setMD5State (md5_state_t * md5state) inline
Definition at line 77 of file daqBuffer.h.
View newest version in sPHENIX GitHub at line 77 of file daqBuffer.h
References _md5state, and md5state.
Referenced by rcdaq_init().
unsigned int daqBuffer::writeout (int fd)
Definition at line 155 of file daqBuffer.cc.
View newest version in sPHENIX GitHub at line 155 of file daqBuffer.cc
References md5_append(), and writen().
Referenced by writebuffers().
Member Data Documentation
int daqBuffer::_broken protected
Definition at line 94 of file daqBuffer.h.
View newest version in sPHENIX GitHub at line 94 of file daqBuffer.h
md5_state_t* daqBuffer::_md5state protected
Definition at line 110 of file daqBuffer.h.
View newest version in sPHENIX GitHub at line 110 of file daqBuffer.h
Referenced by getMD5State(), and setMD5State().
buffer_ptr daqBuffer::bptr protected
Definition at line 95 of file daqBuffer.h.
View newest version in sPHENIX GitHub at line 95 of file daqBuffer.h
Referenced by getBufSeq(), and getLength().
int daqBuffer::current_etype protected
Definition at line 102 of file daqBuffer.h.
View newest version in sPHENIX GitHub at line 102 of file daqBuffer.h
daqEvent* daqBuffer::current_event protected
Definition at line 101 of file daqBuffer.h.
View newest version in sPHENIX GitHub at line 101 of file daqBuffer.h
int daqBuffer::current_index protected
Definition at line 97 of file daqBuffer.h.
View newest version in sPHENIX GitHub at line 97 of file daqBuffer.h
int daqBuffer::currentBufferID protected
Definition at line 108 of file daqBuffer.h.
View newest version in sPHENIX GitHub at line 108 of file daqBuffer.h
int* daqBuffer::data_ptr protected
Definition at line 96 of file daqBuffer.h.
View newest version in sPHENIX GitHub at line 96 of file daqBuffer.h
int daqBuffer::format protected
Definition at line 105 of file daqBuffer.h.
View newest version in sPHENIX GitHub at line 105 of file daqBuffer.h
Referenced by getEventFormat().
int daqBuffer::has_end protected
Definition at line 103 of file daqBuffer.h.
View newest version in sPHENIX GitHub at line 103 of file daqBuffer.h
int daqBuffer::left protected
Definition at line 100 of file daqBuffer.h.
View newest version in sPHENIX GitHub at line 100 of file daqBuffer.h
int daqBuffer::lzo_initialized = 0 static protected
Definition at line 112 of file daqBuffer.h.
View newest version in sPHENIX GitHub at line 112 of file daqBuffer.h
int daqBuffer::max_length protected
Definition at line 98 of file daqBuffer.h.
View newest version in sPHENIX GitHub at line 98 of file daqBuffer.h
int daqBuffer::max_size protected
Definition at line 99 of file daqBuffer.h.
View newest version in sPHENIX GitHub at line 99 of file daqBuffer.h
unsigned int* daqBuffer::outputarray protected
Definition at line 115 of file daqBuffer.h.
View newest version in sPHENIX GitHub at line 115 of file daqBuffer.h
lzo_uint daqBuffer::outputarraylength protected
Definition at line 114 of file daqBuffer.h.
View newest version in sPHENIX GitHub at line 114 of file daqBuffer.h
int daqBuffer::wants_compression protected
Definition at line 106 of file daqBuffer.h.
View newest version in sPHENIX GitHub at line 106 of file daqBuffer.h
Referenced by getCompression().
lzo_byte* daqBuffer::wrkmem protected
Definition at line 113 of file daqBuffer.h.
View newest version in sPHENIX GitHub at line 113 of file daqBuffer.h
The documentation for this class was generated from the following files:
rcdaq/blob/master/daqBuffer.h
rcdaq/blob/master/daqBuffer.cc