Analysis Software: ActsExamples::SvgPointWriter< T, Acc > Exception Template Reference
ActsExamples::SvgPointWriter< T, Acc > Exception Template Reference final
#include <acts/blob/sPHENIX/Examples/Io/Svg/include/ActsExamples/Io/Svg/SvgPointWriter.hpp>
Classes
struct Config
Public Member Functions
SvgPointWriter (const Config &cfg, Acts::Logging::Level level=Acts::Logging::INFO)
Public Member Functions inherited from ActsExamples::WriterT< GeometryIdMultiset< T > >
WriterT (std::string objectName, std::string writerName, Acts::Logging::Level level)
std::string name () const override
Provide the name of the writer.
ProcessCode write (const AlgorithmContext &context) override
Read the object and call the type-specific member function.
ProcessCode finalize () override
No-op default implementation.
Public Member Functions inherited from ActsExamples::IWriter
ProcessCode internalExecute (const AlgorithmContext &context) final
ProcessCode initialize () override
Fulfil the algorithm interface.
Public Member Functions inherited from ActsExamples::SequenceElement
virtual ~SequenceElement ()=default
const std::vector< const
DataHandleBase * > & writeHandles () const
const std::vector< const
DataHandleBase * > & readHandles () const
Protected Member Functions
ActsExamples::ProcessCode writeT (const ActsExamples::AlgorithmContext &context, const GeometryIdMultiset< T > &pointCollection) final
Protected Member Functions inherited from ActsExamples::WriterT< GeometryIdMultiset< T > >
const Acts::Logger & logger () const
Private Attributes
Config m_cfg
std::mutex m_writeMutex
Detailed Description
template<typename T, typename Acc = AccessorXYZ>
exception ActsExamples::SvgPointWriter< T, Acc >
Write out any 3D point collection in Svg format.
Template Parameters
TColl is the collection type
Acc is the accessor type for x(), y(), z()
This writes one file per event into the configured output directory. By default it writes to the current working directory. Files are named using the following schema:
event000000001-spacepoints.svg
event000000002-spacepoints.svg
Definition at line 77 of file SvgPointWriter.hpp.
View newest version in sPHENIX GitHub at line 77 of file SvgPointWriter.hpp
Constructor & Destructor Documentation
template<typename T , typename Acc = AccessorXYZ> ActsExamples::SvgPointWriter< T, Acc >::SvgPointWriter (const Config & cfg, Acts::Logging::Level level = Acts::Logging::INFO)
Definition at line 124 of file SvgPointWriter.hpp.
View newest version in sPHENIX GitHub at line 124 of file SvgPointWriter.hpp
References ActsExamples::SvgPointWriter< T, Acc >::Config::inputCollection, and ActsExamples::SvgPointWriter< T, Acc >::m_cfg.
Member Function Documentation
template<typename T , typename Acc > ActsExamples::ProcessCode ActsExamples::SvgPointWriter< T, Acc >::writeT (const ActsExamples::AlgorithmContext & context, const GeometryIdMultiset< T > & t) final protected virtual
Type-specific write function implementation this method is implemented in the user implementation
Parameters
[in] context is the algorithm context that guarantees event consistency
Template Parameters
[in] is the templated collection to be written
Implements ActsExamples::WriterT< GeometryIdMultiset< T > >.
Definition at line 136 of file SvgPointWriter.hpp.
View newest version in sPHENIX GitHub at line 136 of file SvgPointWriter.hpp
References Acts::Svg::TrackingGeometryProjections::convert(), configureMap::data, ActsExamples::AlgorithmContext::eventNumber, ActsExamples::AlgorithmContext::geoContext, train_ambiguity_solver::id, Acts::Svg::infoBox(), m_cfg(), merge_hashes::p, ActsExamples::perEventFilepath(), Acts::Svg::EventDataConverter::pointXY(), Acts::Svg::EventDataConverter::pointZR(), SUCCESS, Acts::Svg::toFile(), Acts::toString(), and Acts::Svg::TrackingGeometryProjections::Options::trackingGeometryOptions.
Member Data Documentation
template<typename T , typename Acc = AccessorXYZ> Config ActsExamples::SvgPointWriter< T, Acc >::m_cfg private
Definition at line 116 of file SvgPointWriter.hpp.
View newest version in sPHENIX GitHub at line 116 of file SvgPointWriter.hpp
Referenced by ActsExamples::SvgPointWriter< T, Acc >::SvgPointWriter().
template<typename T , typename Acc = AccessorXYZ> std::mutex ActsExamples::SvgPointWriter< T, Acc >::m_writeMutex private
Definition at line 118 of file SvgPointWriter.hpp.
View newest version in sPHENIX GitHub at line 118 of file SvgPointWriter.hpp
The documentation for this exception was generated from the following file:
acts/blob/sPHENIX/Examples/Io/Svg/include/ActsExamples/Io/Svg/SvgPointWriter.hpp