Analysis Software: ActsExamples::SimSourceLink Class Reference
ActsExamples::SimSourceLink Class Reference
#include <acts/blob/sPHENIX/Examples/Framework/include/ActsExamples/EventData/SimSourceLink.hpp>
Public Member Functions
SimSourceLink (const Acts::Surface &surface, const ActsFatras::Hit &truthHit, size_t dim, Acts::BoundVector values, Acts::BoundMatrix cov)
SimSourceLink ()=default
Must be default_constructible to satisfy SourceLinkConcept.
SimSourceLink (SimSourceLink &&)=default
SimSourceLink (const SimSourceLink &)=default
SimSourceLink & operator= (SimSourceLink &&)=default
SimSourceLink & operator= (const SimSourceLink &)=default
constexpr Acts::GeometryIdentifier geometryId () const
constexpr const Acts::Surface & referenceSurface () const
constexpr const ActsFatras::Hit & truthHit () const
Acts::FittableMeasurement
< SimSourceLink > operator* () const
Private Attributes
Acts::BoundVector m_values
Acts::BoundMatrix m_cov
size_t m_dim = 0u
Acts::GeometryIdentifier m_geometryId
const Acts::Surface * m_surface
const ActsFatras::Hit * m_truthHit
Friends
constexpr bool operator== (const SimSourceLink &lhs, const SimSourceLink &rhs)
Detailed Description
Source link class for simulation in the acts-framework.
The source link stores the measuremts, surface, and the associated simulated truth hit.
Definition at line 26 of file SimSourceLink.hpp.
View newest version in sPHENIX GitHub at line 26 of file SimSourceLink.hpp
Constructor & Destructor Documentation
ActsExamples::SimSourceLink::SimSourceLink (const Acts::Surface & surface, const ActsFatras::Hit & truthHit, size_t dim, Acts::BoundVector values, Acts::BoundMatrix cov) inline
Definition at line 28 of file SimSourceLink.hpp.
View newest version in sPHENIX GitHub at line 28 of file SimSourceLink.hpp
ActsExamples::SimSourceLink::SimSourceLink () default
Must be default_constructible to satisfy SourceLinkConcept.
Referenced by operator*().
ActsExamples::SimSourceLink::SimSourceLink (SimSourceLink &&) default
ActsExamples::SimSourceLink::SimSourceLink (const SimSourceLink &) default
Member Function Documentation
constexpr Acts::GeometryIdentifier ActsExamples::SimSourceLink::geometryId () const inline
Definition at line 43 of file SimSourceLink.hpp.
View newest version in sPHENIX GitHub at line 43 of file SimSourceLink.hpp
References m_geometryId.
Acts::FittableMeasurement<SimSourceLink> ActsExamples::SimSourceLink::operator* () const inline
Definition at line 47 of file SimSourceLink.hpp.
View newest version in sPHENIX GitHub at line 47 of file SimSourceLink.hpp
References Acts::eBoundLoc0, Acts::eBoundLoc1, Acts::Surface::getSharedPtr(), m_cov, m_dim, m_surface, m_values, SimSourceLink(), and nlohmann::to_string().
SimSourceLink& ActsExamples::SimSourceLink::operator= (SimSourceLink &&) default
SimSourceLink& ActsExamples::SimSourceLink::operator= (const SimSourceLink &) default
constexpr const Acts::Surface& ActsExamples::SimSourceLink::referenceSurface () const inline
Definition at line 44 of file SimSourceLink.hpp.
View newest version in sPHENIX GitHub at line 44 of file SimSourceLink.hpp
References m_surface.
constexpr const ActsFatras::Hit& ActsExamples::SimSourceLink::truthHit () const inline
Definition at line 45 of file SimSourceLink.hpp.
View newest version in sPHENIX GitHub at line 45 of file SimSourceLink.hpp
References m_truthHit.
Friends And Related Function Documentation
constexpr bool operator== (const SimSourceLink & lhs, const SimSourceLink & rhs) friend
Definition at line 76 of file SimSourceLink.hpp.
View newest version in sPHENIX GitHub at line 76 of file SimSourceLink.hpp
Member Data Documentation
Acts::BoundMatrix ActsExamples::SimSourceLink::m_cov private
Definition at line 68 of file SimSourceLink.hpp.
View newest version in sPHENIX GitHub at line 68 of file SimSourceLink.hpp
Referenced by operator*().
size_t ActsExamples::SimSourceLink::m_dim = 0u private
Definition at line 69 of file SimSourceLink.hpp.
View newest version in sPHENIX GitHub at line 69 of file SimSourceLink.hpp
Referenced by operator*().
Acts::GeometryIdentifier ActsExamples::SimSourceLink::m_geometryId private
Definition at line 71 of file SimSourceLink.hpp.
View newest version in sPHENIX GitHub at line 71 of file SimSourceLink.hpp
Referenced by geometryId().
const Acts::Surface* ActsExamples::SimSourceLink::m_surface private
Definition at line 73 of file SimSourceLink.hpp.
View newest version in sPHENIX GitHub at line 73 of file SimSourceLink.hpp
Referenced by operator*(), and referenceSurface().
const ActsFatras::Hit* ActsExamples::SimSourceLink::m_truthHit private
Definition at line 74 of file SimSourceLink.hpp.
View newest version in sPHENIX GitHub at line 74 of file SimSourceLink.hpp
Referenced by truthHit().
Acts::BoundVector ActsExamples::SimSourceLink::m_values private
Definition at line 67 of file SimSourceLink.hpp.
View newest version in sPHENIX GitHub at line 67 of file SimSourceLink.hpp
Referenced by operator*().
The documentation for this class was generated from the following file:
acts/blob/sPHENIX/Examples/Framework/include/ActsExamples/EventData/SimSourceLink.hpp