Analysis Software: PHParametersContainer Class Reference
PHParametersContainer Class Reference
#include <coresoftware/blob/master/offline/database/PHParameter/PHParametersContainer.h>
Public Types
typedef std::map< int,
PHParameters * > Map
typedef Map::iterator Iterator
typedef Map::const_iterator ConstIterator
typedef std::pair< Iterator,
Iterator > Range
typedef std::pair
< ConstIterator, ConstIterator > ConstRange
Public Member Functions
PHParametersContainer (const std::string &name="NONE")
~PHParametersContainer () override
void AddPHParameters (const int detid, PHParameters *params)
const PHParameters * GetParameters (const int detid) const
PHParameters * GetParametersToModify (const int detid)
int WriteToFile (const std::string &extension, const std::string &dir)
int WriteToDB ()
void set_name (const std::string &name)
std::string Name () const
ConstRange GetAllParameters () const
void Print (Option_t *option="") const override
void SaveToNodeTree (PHCompositeNode *topNode, const std::string &nodename)
void UpdateNodeTree (PHCompositeNode *topNode, const std::string &nodename)
int ExistDetid (const int detid) const
void clear ()
void FillFrom (const PdbParameterMapContainer *saveparamcontainer)
void CreateAndFillFrom (const PdbParameterMapContainer *saveparamcontainer, const std::string &name)
Public Member Functions inherited from PHObject
PHObject ()
ctor
~PHObject () override
dtor
virtual PHObject * CloneMe () const
Virtual copy constructor.
virtual PHObject * clone () const final
PHObject * Clone (const char *newname="") const final
void Copy (TObject &object) const final
virtual void identify (std::ostream &os=std::cout) const
virtual void Reset ()
Clear Event.
virtual int isValid () const
isValid returns non zero if object contains vailid data
virtual int Integrate () const
virtual int Integrate (PHObject *)
virtual void CopyFrom (const PHObject *obj)
Private Member Functions
void CopyToPdbParameterMapContainer (PdbParameterMapContainer *myparm)
void UpdatePdbParameterMapContainer (PdbParameterMapContainer *myparm)
Private Attributes
std::string superdetectorname
std::map< int, PHParameters * > parametermap
Detailed Description
Definition at line 16 of file PHParametersContainer.h.
View newest version in sPHENIX GitHub at line 16 of file PHParametersContainer.h
Member Typedef Documentation
typedef Map::const_iterator PHParametersContainer::ConstIterator
Definition at line 21 of file PHParametersContainer.h.
View newest version in sPHENIX GitHub at line 21 of file PHParametersContainer.h
typedef std::pair<ConstIterator, ConstIterator> PHParametersContainer::ConstRange
Definition at line 23 of file PHParametersContainer.h.
View newest version in sPHENIX GitHub at line 23 of file PHParametersContainer.h
typedef Map::iterator PHParametersContainer::Iterator
Definition at line 20 of file PHParametersContainer.h.
View newest version in sPHENIX GitHub at line 20 of file PHParametersContainer.h
typedef std::map<int, PHParameters *> PHParametersContainer::Map
Definition at line 19 of file PHParametersContainer.h.
View newest version in sPHENIX GitHub at line 19 of file PHParametersContainer.h
typedef std::pair<Iterator, Iterator> PHParametersContainer::Range
Definition at line 22 of file PHParametersContainer.h.
View newest version in sPHENIX GitHub at line 22 of file PHParametersContainer.h
Constructor & Destructor Documentation
PHParametersContainer::PHParametersContainer (const std::string & name = "NONE") explicit
Definition at line 35 of file PHParametersContainer.cc.
View newest version in sPHENIX GitHub at line 35 of file PHParametersContainer.cc
PHParametersContainer::~PHParametersContainer () override
Definition at line 40 of file PHParametersContainer.cc.
View newest version in sPHENIX GitHub at line 40 of file PHParametersContainer.cc
References parametermap.
Member Function Documentation
void PHParametersContainer::AddPHParameters (const int detid, PHParameters * params)
Definition at line 87 of file PHParametersContainer.cc.
View newest version in sPHENIX GitHub at line 87 of file PHParametersContainer.cc
References parametermap, and PHWHERE.
Referenced by CreateAndFillFrom(), PHParameterContainerInterface::CreateInitialize(), PHG4DetectorGroupSubsystem::InitializeParameters(), PHG4DetectorGroupSubsystem::InitRun(), PHG4DetectorSubsystem::InitRun(), PHParameterContainerInterface::set_int_param(), and PHParameterContainerInterface::set_string_param().
void PHParametersContainer::clear () inline
Definition at line 42 of file PHParametersContainer.h.
View newest version in sPHENIX GitHub at line 42 of file PHParametersContainer.h
References parametermap.
Referenced by PHG4DetectorGroupSubsystem::InitRun().
void PHParametersContainer::CopyToPdbParameterMapContainer (PdbParameterMapContainer * myparm) private
Definition at line 204 of file PHParametersContainer.cc.
View newest version in sPHENIX GitHub at line 204 of file PHParametersContainer.cc
References PdbParameterMapContainer::AddPdbParameterMap(), and parametermap.
Referenced by SaveToNodeTree(), WriteToDB(), and WriteToFile().
void PHParametersContainer::CreateAndFillFrom (const PdbParameterMapContainer * saveparamcontainer, const std::string & name)
Definition at line 66 of file PHParametersContainer.cc.
View newest version in sPHENIX GitHub at line 66 of file PHParametersContainer.cc
References AddPHParameters(), PHParameters::FillFrom(), PdbParameterMapContainer::get_ParameterMaps(), and parametermap.
int PHParametersContainer::ExistDetid (const int detid) const
Definition at line 270 of file PHParametersContainer.cc.
View newest version in sPHENIX GitHub at line 270 of file PHParametersContainer.cc
References parametermap.
Referenced by PHParameterContainerInterface::ExistDetid().
void PHParametersContainer::FillFrom (const PdbParameterMapContainer * saveparamcontainer)
Definition at line 49 of file PHParametersContainer.cc.
View newest version in sPHENIX GitHub at line 49 of file PHParametersContainer.cc
References PHParameters::FillFrom(), PdbParameterMapContainer::get_ParameterMaps(), and parametermap.
Referenced by PHG4DetectorGroupSubsystem::InitRun().
ConstRange PHParametersContainer::GetAllParameters () const inline
Definition at line 37 of file PHParametersContainer.h.
View newest version in sPHENIX GitHub at line 37 of file PHParametersContainer.h
References parametermap.
Referenced by PHG4DetectorGroupSubsystem::InitRun(), and PHG4MvtxSteppingAction::PHG4MvtxSteppingAction().
const PHParameters * PHParametersContainer::GetParameters (const int detid) const
Definition at line 99 of file PHParametersContainer.cc.
View newest version in sPHENIX GitHub at line 99 of file PHParametersContainer.cc
References parametermap.
Referenced by PHG4InttDetector::AddGeometryNode(), PHG4InttDetector::ConstructIntt(), PHG4PSTOFDetector::ConstructMe(), PHParameterContainerInterface::get_double_param(), PHG4DetectorGroupSubsystem::get_double_param(), PHParameterContainerInterface::get_int_param(), PHG4DetectorGroupSubsystem::get_int_param(), PHParameterContainerInterface::get_string_param(), PHG4DetectorGroupSubsystem::get_string_param(), PHG4MvtxSubsystem::InitRunSubsystem(), PHG4EICMvtxSubsystem::InitRunSubsystem(), PHG4InttSubsystem::InitRunSubsystem(), PHG4EICMvtxDetector::PHG4EICMvtxDetector(), PHG4InttDetector::PHG4InttDetector(), PHG4InttSteppingAction::PHG4InttSteppingAction(), PHG4MvtxDetector::PHG4MvtxDetector(), PHG4MvtxSteppingAction::PHG4MvtxSteppingAction(), and PHG4PSTOFDetector::PHG4PSTOFDetector().
PHParameters * PHParametersContainer::GetParametersToModify (const int detid)
Definition at line 118 of file PHParametersContainer.cc.
View newest version in sPHENIX GitHub at line 118 of file PHParametersContainer.cc
References parametermap.
Referenced by PHParameterContainerInterface::CreateInitialize(), PHG4DetectorGroupSubsystem::InitializeParameters(), PHParameterContainerInterface::UpdateParametersWithMacro(), and PHG4DetectorGroupSubsystem::UpdateParametersWithMacro().
std::string PHParametersContainer::Name () const inline
Definition at line 35 of file PHParametersContainer.h.
View newest version in sPHENIX GitHub at line 35 of file PHParametersContainer.h
References superdetectorname.
Referenced by PHParameterContainerInterface::CreateInitialize(), PHParameterContainerInterface::get_double_param(), PHParameterContainerInterface::get_int_param(), PHParameterContainerInterface::get_string_param(), PHG4BlockCellReco::InitRun(), PHG4CylinderCellReco::InitRun(), PHG4DetectorGroupSubsystem::InitRun(), Print(), PHParameterContainerInterface::set_double_param(), PHParameterContainerInterface::set_int_param(), and PHParameterContainerInterface::set_string_param().
void PHParametersContainer::Print (Option_t * option = "") const override
Definition at line 227 of file PHParametersContainer.cc.
View newest version in sPHENIX GitHub at line 227 of file PHParametersContainer.cc
References Name(), and parametermap.
Referenced by PHG4EICMvtxSubsystem::InitRunSubsystem(), PHG4MvtxSubsystem::InitRunSubsystem(), PHG4InttSubsystem::Print(), and PHG4PSTOFSubsystem::Print().
void PHParametersContainer::SaveToNodeTree (PHCompositeNode * topNode, const std::string & nodename)
Definition at line 239 of file PHParametersContainer.cc.
View newest version in sPHENIX GitHub at line 239 of file PHParametersContainer.cc
References CopyToPdbParameterMapContainer(), and PdbParameterMapContainer::Reset().
Referenced by PHG4DetectorGroupSubsystem::InitRun(), and PHParameterContainerInterface::SaveToNodeTree().
void PHParametersContainer::set_name (const std::string & name) inline
Definition at line 34 of file PHParametersContainer.h.
View newest version in sPHENIX GitHub at line 34 of file PHParametersContainer.h
References perf_headwind::name, and superdetectorname.
Referenced by PHG4DetectorGroupSubsystem::Init(), PHG4BlockCellReco::InitRun(), PHG4CylinderCellReco::InitRun(), and PHParameterContainerInterface::set_name().
void PHParametersContainer::UpdateNodeTree (PHCompositeNode * topNode, const std::string & nodename)
Definition at line 257 of file PHParametersContainer.cc.
View newest version in sPHENIX GitHub at line 257 of file PHParametersContainer.cc
References PHWHERE, and UpdatePdbParameterMapContainer().
Referenced by PHG4DetectorGroupSubsystem::InitRun().
void PHParametersContainer::UpdatePdbParameterMapContainer (PdbParameterMapContainer * myparm) private
Definition at line 216 of file PHParametersContainer.cc.
View newest version in sPHENIX GitHub at line 216 of file PHParametersContainer.cc
References PdbParameterMapContainer::GetParametersToModify(), and parametermap.
Referenced by UpdateNodeTree().
int PHParametersContainer::WriteToDB ()
Definition at line 167 of file PHParametersContainer.cc.
View newest version in sPHENIX GitHub at line 167 of file PHParametersContainer.cc
References PdbApplication::abort(), PdbApplication::commit(), CopyToPdbParameterMapContainer(), PdbBankManager::createBank(), PdbBankManager::getApplication(), PdbBankManager::instance(), PHWHERE, PdbCalBank::setLength(), PdbApplication::startUpdate(), superdetectorname, and Acts::Test::transform.
Referenced by PHG4DetectorGroupSubsystem::SaveParamsToDB(), and PHG4DetectorSubsystem::SaveParamsToDB().
int PHParametersContainer::WriteToFile (const std::string & extension, const std::string & dir)
Definition at line 128 of file PHParametersContainer.cc.
View newest version in sPHENIX GitHub at line 128 of file PHParametersContainer.cc
References CopyToPdbParameterMapContainer(), extension, f, INTTVtxZ::fname, PdbBankID::getInternalValue(), PHTimeStamp::getTics(), superdetectorname, Acts::Test::time, and Acts::Test::transform.
Referenced by PHG4DetectorGroupSubsystem::SaveParamsToFile(), and PHG4DetectorSubsystem::SaveParamsToFile().
Member Data Documentation
std::map<int, PHParameters *> PHParametersContainer::parametermap private
Definition at line 50 of file PHParametersContainer.h.
View newest version in sPHENIX GitHub at line 50 of file PHParametersContainer.h
Referenced by AddPHParameters(), clear(), CopyToPdbParameterMapContainer(), CreateAndFillFrom(), ExistDetid(), FillFrom(), GetAllParameters(), GetParameters(), GetParametersToModify(), Print(), UpdatePdbParameterMapContainer(), and ~PHParametersContainer().
std::string PHParametersContainer::superdetectorname private
Definition at line 49 of file PHParametersContainer.h.
View newest version in sPHENIX GitHub at line 49 of file PHParametersContainer.h
Referenced by Name(), set_name(), WriteToDB(), and WriteToFile().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/database/PHParameter/PHParametersContainer.h
coresoftware/blob/master/offline/database/PHParameter/PHParametersContainer.cc