Analysis Software: MvtxClusterizer Class Reference
MvtxClusterizer Class Reference
Clusterizer for the MVTX.
#include <coresoftware/blob/master/offline/packages/mvtx/MvtxClusterizer.h>
Public Types
typedef std::pair< unsigned
int, unsigned int > pixel
typedef std::pair< unsigned
int, unsigned int > pixel
Public Member Functions
MvtxClusterizer (const std::string &name="MvtxClusterizer")
~MvtxClusterizer () override
int Init (PHCompositeNode *) override
module initialization
int InitRun (PHCompositeNode *topNode) override
run initialization
int process_event (PHCompositeNode *topNode) override
event processing
int End (PHCompositeNode *) override
end of process
void SetZClustering (const bool make_z_clustering)
option to turn off z-dimension clustering
bool GetZClustering () const
void set_do_hit_association (bool do_assoc)
void set_read_raw (bool read_raw)
void set_ClusHitsVerbose (bool set=true)
MvtxClusterizer (const std::string &name="MvtxClusterizer")
virtual ~MvtxClusterizer ()
int Init (PHCompositeNode *topNode)
module initialization
int InitRun (PHCompositeNode *topNode)
run initialization
int process_event (PHCompositeNode *topNode)
event processing
int End (PHCompositeNode *topNode)
end of process
void SetZClustering (const bool make_z_clustering)
option to turn off z-dimension clustering
bool GetZClustering () const
Public Member Functions inherited from SubsysReco
~SubsysReco () override
virtual int EndRun (const int)
Called at the end of each run.
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
void Print (const std::string &="ALL") const override
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Public Attributes
ClusHitsVerbose * mClusHitsVerbose { nullptr }
Private Member Functions
bool are_adjacent (const std::pair< TrkrDefs::hitkey, TrkrHit * > &lhs, const std::pair< TrkrDefs::hitkey, TrkrHit * > &rhs)
bool are_adjacent (RawHit *lhs, RawHit *rhs)
void ClusterMvtx (PHCompositeNode *topNode)
void ClusterMvtxRaw (PHCompositeNode *topNode)
void PrintClusters (PHCompositeNode *topNode)
bool are_adjacent (const pixel lhs, const pixel rhs)
void ClusterMvtx (PHCompositeNode *topNode)
void PrintClusters (PHCompositeNode *topNode)
Private Attributes
bool record_ClusHitsVerbose { false }
TrkrHitSetContainer * m_hits
RawHitSetContainer * m_rawhits
TrkrClusterContainer * m_clusterlist
TrkrClusterHitAssoc * m_clusterhitassoc
bool m_makeZClustering
bool do_hit_assoc = true
bool do_read_raw = false
TrkrHitSetContainer * hits_
TrkrClusterContainer * clusterlist_
bool make_z_clustering_
PHTimeServer::timer _timer
Additional Inherited Members
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Detailed Description
Clusterizer for the MVTX.
Definition at line 30 of file MvtxClusterizer.h.
View newest version in sPHENIX GitHub at line 30 of file MvtxClusterizer.h
Member Typedef Documentation
typedef std::pair<unsigned int, unsigned int> MvtxClusterizer::pixel
Definition at line 18 of file MvtxClusterizer.h.
View newest version in sPHENIX GitHub at line 18 of file MvtxClusterizer.h
typedef std::pair<unsigned int, unsigned int> MvtxClusterizer::pixel
Definition at line 33 of file MvtxClusterizer.h.
View newest version in sPHENIX GitHub at line 33 of file MvtxClusterizer.h
Constructor & Destructor Documentation
MvtxClusterizer::MvtxClusterizer (const std::string & name = "MvtxClusterizer")
Definition at line 126 of file MvtxClusterizer.cc.
View newest version in sPHENIX GitHub at line 126 of file MvtxClusterizer.cc
MvtxClusterizer::~MvtxClusterizer () inline override
Definition at line 36 of file MvtxClusterizer.h.
View newest version in sPHENIX GitHub at line 36 of file MvtxClusterizer.h
MvtxClusterizer::MvtxClusterizer (const std::string & name = "MvtxClusterizer")
virtual MvtxClusterizer::~MvtxClusterizer () inline virtual
Definition at line 21 of file MvtxClusterizer.h.
View newest version in sPHENIX GitHub at line 21 of file MvtxClusterizer.h
Member Function Documentation
bool MvtxClusterizer::are_adjacent (const pixel lhs, const pixel rhs) private
Definition at line 46 of file MvtxClusterizer.C.
View newest version in sPHENIX GitHub at line 46 of file MvtxClusterizer.C
bool MvtxClusterizer::are_adjacent (const std::pair< TrkrDefs::hitkey, TrkrHit * > & lhs, const std::pair< TrkrDefs::hitkey, TrkrHit * > & rhs) private
Definition at line 72 of file MvtxClusterizer.cc.
View newest version in sPHENIX GitHub at line 72 of file MvtxClusterizer.cc
References MvtxDefs::getCol(), and MvtxDefs::getRow().
Referenced by ClusterMvtx(), and ClusterMvtxRaw().
bool MvtxClusterizer::are_adjacent (RawHit * lhs, RawHit * rhs) private
Definition at line 99 of file MvtxClusterizer.cc.
View newest version in sPHENIX GitHub at line 99 of file MvtxClusterizer.cc
References RawHit::getPhiBin(), and RawHit::getTBin().
void MvtxClusterizer::ClusterMvtx (PHCompositeNode * topNode) private
void MvtxClusterizer::ClusterMvtx (PHCompositeNode * topNode) private
Definition at line 280 of file MvtxClusterizer.cc.
View newest version in sPHENIX GitHub at line 280 of file MvtxClusterizer.cc
References TrkrClusterHitAssoc::addAssoc(), TrkrClusterContainer::addClusterSpecifyKey(), ClusHitsVerbose::addPhiHit(), ClusHitsVerbose::addZHit(), are_adjacent(), clusters, col, distance(), Acts::UnitConstants::e, energy, G, TrkrDefs::genClusKey(), MvtxDefs::getChipId(), MvtxDefs::getCol(), TrkrHitSet::getHits(), TrkrHitSet::getHitSetKey(), TrkrHitSetContainer::getHitSets(), TrkrDefs::getLayer(), PHG4CylinderGeomContainer::GetLayerGeom(), MvtxDefs::getRow(), MvtxDefs::getStaveId(), MvtxDefs::getStrobeId(), i, PHObject::identify(), TrkrHitSet::identify(), j, layer, G4PLUGDOOR::length, m_clusterhitassoc, m_clusterlist, m_hits, mClusHitsVerbose, TrkrDefs::mvtxId, MATSCAN::phibins, phisize, ClusHitsVerbose::push_hits(), Fun4AllBase::Verbosity(), and zsize.
Referenced by process_event().
void MvtxClusterizer::ClusterMvtxRaw (PHCompositeNode * topNode) private
Definition at line 523 of file MvtxClusterizer.cc.
View newest version in sPHENIX GitHub at line 523 of file MvtxClusterizer.cc
References TrkrClusterContainer::addClusterSpecifyKey(), are_adjacent(), clusters, col, distance(), Acts::UnitConstants::e, G, TrkrDefs::genClusKey(), MvtxDefs::getChipId(), RawHitSet::getHits(), RawHitSet::getHitSetKey(), RawHitSetContainer::getHitSets(), TrkrDefs::getLayer(), PHG4CylinderGeomContainer::GetLayerGeom(), MvtxDefs::getStaveId(), MvtxDefs::getStrobeId(), TpcDefs::getTBin(), i, PHObject::identify(), RawHitSet::identify(), j, layer, G4PLUGDOOR::length, m_clusterhitassoc, m_clusterlist, m_rawhits, TrkrDefs::mvtxId, MATSCAN::phibins, phisize, Fun4AllBase::Verbosity(), and zsize.
Referenced by process_event().
int MvtxClusterizer::End (PHCompositeNode * topNode) inline virtual
end of process
Reimplemented from SubsysReco.
Definition at line 33 of file MvtxClusterizer.h.
View newest version in sPHENIX GitHub at line 33 of file MvtxClusterizer.h
int MvtxClusterizer::End (PHCompositeNode *) inline override virtual
end of process
Reimplemented from SubsysReco.
Definition at line 48 of file MvtxClusterizer.h.
View newest version in sPHENIX GitHub at line 48 of file MvtxClusterizer.h
bool MvtxClusterizer::GetZClustering () const inline
Definition at line 39 of file MvtxClusterizer.h.
View newest version in sPHENIX GitHub at line 39 of file MvtxClusterizer.h
References make_z_clustering_.
bool MvtxClusterizer::GetZClustering () const inline
Definition at line 55 of file MvtxClusterizer.h.
View newest version in sPHENIX GitHub at line 55 of file MvtxClusterizer.h
References m_makeZClustering.
int MvtxClusterizer::Init (PHCompositeNode * topNode) inline virtual
module initialization
Reimplemented from SubsysReco.
Definition at line 24 of file MvtxClusterizer.h.
View newest version in sPHENIX GitHub at line 24 of file MvtxClusterizer.h
int MvtxClusterizer::Init (PHCompositeNode *) inline override virtual
module initialization
Reimplemented from SubsysReco.
Definition at line 39 of file MvtxClusterizer.h.
View newest version in sPHENIX GitHub at line 39 of file MvtxClusterizer.h
int MvtxClusterizer::InitRun (PHCompositeNode * topNode) virtual
run initialization
Reimplemented from SubsysReco.
int MvtxClusterizer::InitRun (PHCompositeNode * topNode) override virtual
run initialization
Reimplemented from SubsysReco.
Definition at line 136 of file MvtxClusterizer.cc.
View newest version in sPHENIX GitHub at line 136 of file MvtxClusterizer.cc
References Fun4AllReturnCodes::ABORTRUN, PHCompositeNode::addNode(), Fun4AllReturnCodes::EVENT_OK, PHNodeIterator::findFirst(), m_makeZClustering, mClusHitsVerbose, PHWHERE, record_ClusHitsVerbose, and Fun4AllBase::Verbosity().
void MvtxClusterizer::PrintClusters (PHCompositeNode * topNode) private
void MvtxClusterizer::PrintClusters (PHCompositeNode * topNode) private
Definition at line 738 of file MvtxClusterizer.cc.
View newest version in sPHENIX GitHub at line 738 of file MvtxClusterizer.cc
References TrkrClusterContainer::identify(), TrkrClusterContainer::size(), and Fun4AllBase::Verbosity().
Referenced by process_event().
int MvtxClusterizer::process_event (PHCompositeNode * topNode) virtual
event processing
Reimplemented from SubsysReco.
int MvtxClusterizer::process_event (PHCompositeNode * topNode) override virtual
event processing
Reimplemented from SubsysReco.
Definition at line 232 of file MvtxClusterizer.cc.
View newest version in sPHENIX GitHub at line 232 of file MvtxClusterizer.cc
References Fun4AllReturnCodes::ABORTRUN, ClusterMvtx(), ClusterMvtxRaw(), do_read_raw, Fun4AllReturnCodes::EVENT_OK, m_clusterhitassoc, m_clusterlist, m_hits, m_rawhits, PHWHERE, and PrintClusters().
void MvtxClusterizer::set_ClusHitsVerbose (bool set = true) inline
Definition at line 62 of file MvtxClusterizer.h.
View newest version in sPHENIX GitHub at line 62 of file MvtxClusterizer.h
References record_ClusHitsVerbose.
void MvtxClusterizer::set_do_hit_association (bool do_assoc) inline
Definition at line 60 of file MvtxClusterizer.h.
View newest version in sPHENIX GitHub at line 60 of file MvtxClusterizer.h
References do_hit_assoc.
void MvtxClusterizer::set_read_raw (bool read_raw) inline
Definition at line 61 of file MvtxClusterizer.h.
View newest version in sPHENIX GitHub at line 61 of file MvtxClusterizer.h
References do_read_raw.
void MvtxClusterizer::SetZClustering (const bool make_z_clustering) inline
option to turn off z-dimension clustering
Definition at line 36 of file MvtxClusterizer.h.
View newest version in sPHENIX GitHub at line 36 of file MvtxClusterizer.h
References make_z_clustering_.
void MvtxClusterizer::SetZClustering (const bool make_z_clustering) inline
option to turn off z-dimension clustering
Definition at line 51 of file MvtxClusterizer.h.
View newest version in sPHENIX GitHub at line 51 of file MvtxClusterizer.h
References m_makeZClustering.
Member Data Documentation
PHTimeServer::timer MvtxClusterizer::_timer private
Definition at line 58 of file MvtxClusterizer.h.
View newest version in sPHENIX GitHub at line 58 of file MvtxClusterizer.h
TrkrClusterContainer* MvtxClusterizer::clusterlist_ private
Definition at line 53 of file MvtxClusterizer.h.
View newest version in sPHENIX GitHub at line 53 of file MvtxClusterizer.h
bool MvtxClusterizer::do_hit_assoc = true private
Definition at line 84 of file MvtxClusterizer.h.
View newest version in sPHENIX GitHub at line 84 of file MvtxClusterizer.h
Referenced by set_do_hit_association().
bool MvtxClusterizer::do_read_raw = false private
Definition at line 85 of file MvtxClusterizer.h.
View newest version in sPHENIX GitHub at line 85 of file MvtxClusterizer.h
Referenced by process_event(), and set_read_raw().
TrkrHitSetContainer* MvtxClusterizer::hits_ private
Definition at line 52 of file MvtxClusterizer.h.
View newest version in sPHENIX GitHub at line 52 of file MvtxClusterizer.h
TrkrClusterHitAssoc* MvtxClusterizer::m_clusterhitassoc private
Definition at line 80 of file MvtxClusterizer.h.
View newest version in sPHENIX GitHub at line 80 of file MvtxClusterizer.h
Referenced by ClusterMvtx(), ClusterMvtxRaw(), and process_event().
TrkrClusterContainer* MvtxClusterizer::m_clusterlist private
Definition at line 78 of file MvtxClusterizer.h.
View newest version in sPHENIX GitHub at line 78 of file MvtxClusterizer.h
Referenced by ClusterMvtx(), ClusterMvtxRaw(), and process_event().
TrkrHitSetContainer* MvtxClusterizer::m_hits private
Definition at line 76 of file MvtxClusterizer.h.
View newest version in sPHENIX GitHub at line 76 of file MvtxClusterizer.h
Referenced by ClusterMvtx(), and process_event().
bool MvtxClusterizer::m_makeZClustering private
Definition at line 83 of file MvtxClusterizer.h.
View newest version in sPHENIX GitHub at line 83 of file MvtxClusterizer.h
Referenced by GetZClustering(), InitRun(), and SetZClustering().
RawHitSetContainer* MvtxClusterizer::m_rawhits private
Definition at line 77 of file MvtxClusterizer.h.
View newest version in sPHENIX GitHub at line 77 of file MvtxClusterizer.h
Referenced by ClusterMvtxRaw(), and process_event().
bool MvtxClusterizer::make_z_clustering_ private
Definition at line 56 of file MvtxClusterizer.h.
View newest version in sPHENIX GitHub at line 56 of file MvtxClusterizer.h
Referenced by GetZClustering(), and SetZClustering().
ClusHitsVerbose* MvtxClusterizer::mClusHitsVerbose { nullptr }
Definition at line 63 of file MvtxClusterizer.h.
View newest version in sPHENIX GitHub at line 63 of file MvtxClusterizer.h
Referenced by ClusterMvtx(), and InitRun().
bool MvtxClusterizer::record_ClusHitsVerbose { false } private
Definition at line 67 of file MvtxClusterizer.h.
View newest version in sPHENIX GitHub at line 67 of file MvtxClusterizer.h
Referenced by InitRun(), and set_ClusHitsVerbose().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/mvtx/MvtxClusterizer.h
prototype/blob/master/offline/packages/MvtxPrototype1/MvtxClusterizer.h
coresoftware/blob/master/offline/packages/mvtx/MvtxClusterizer.cc
prototype/blob/master/offline/packages/MvtxPrototype1/MvtxClusterizer.C