Analysis Software: CMFlashClusterv2 Class Reference
CMFlashClusterv2 Class Reference
Version 2 of CMFlashCluster.
#include <coresoftware/blob/master/offline/packages/trackbase/CMFlashClusterv2.h>
Public Member Functions
CMFlashClusterv2 ()=default
ctor
void identify (std::ostream &os=std::cout) const override
void Reset () override
Clear Event.
int isValid () const override
isValid returns non zero if object contains vailid data
PHObject * CloneMe () const override
Virtual copy constructor.
void CopyFrom (const CMFlashCluster &) override
copy content from base class
void CopyFrom (CMFlashCluster *source) override
copy content from base class
float getX () const override
void setX (float x) override
float getY () const override
void setY (float y) override
float getZ () const override
void setZ (float z) override
unsigned int getNclusters () const override
void setNclusters (unsigned int n) override
bool getIsRGap () const override
void setIsRGap (bool isRGap) override
bool getIsPhiGap () const override
void setIsPhiGap (bool isPhiGap) override
unsigned int getAdc () const override
void setAdc (unsigned int adc) override
Public Member Functions inherited from CMFlashCluster
~CMFlashCluster () override
dtor
virtual float getX1 () const
virtual void setX1 (float)
virtual float getY1 () const
virtual void setY1 (float)
virtual float getZ1 () const
virtual void setZ1 (float)
virtual float getX2 () const
virtual void setX2 (float)
virtual float getY2 () const
virtual void setY2 (float)
virtual float getZ2 () const
virtual void setZ2 (float)
virtual void setLayer1 (unsigned int)
virtual unsigned int getLayer1 () const
virtual void setLayer2 (unsigned int)
virtual unsigned int getLayer2 () const
virtual void setAdc1 (unsigned int)
virtual unsigned int getAdc1 () const
virtual void setAdc2 (unsigned int)
virtual unsigned int getAdc2 () const
Public Member Functions inherited from PHObject
PHObject ()
ctor
~PHObject () override
dtor
virtual PHObject * clone () const final
PHObject * Clone (const char *newname="") const final
void Copy (TObject &object) const final
virtual int Integrate () const
virtual int Integrate (PHObject *)
virtual void CopyFrom (const PHObject *obj)
Protected Attributes
float m_pos [3] = {NAN, NAN, NAN}
mean cluster position
unsigned int m_adc = 0xFFFFFFFF
cluster sum adc
unsigned int m_nclusters = UINT_MAX
number of TPC clusters used to create this central mebrane cluster
bool m_isRGap = false
bools to identify if meta-cluster is across sector/module gaps
bool m_isPhiGap = false
Additional Inherited Members
Protected Member Functions inherited from CMFlashCluster
CMFlashCluster ()=default
Detailed Description
Version 2 of CMFlashCluster.
Adding bool variables to identify if meta-cluster contains sub-clusters from both sides of sector (phi) or module (R) gaps
Definition at line 25 of file CMFlashClusterv2.h.
View newest version in sPHENIX GitHub at line 25 of file CMFlashClusterv2.h
Constructor & Destructor Documentation
CMFlashClusterv2::CMFlashClusterv2 () default
ctor
Referenced by CloneMe().
Member Function Documentation
PHObject* CMFlashClusterv2::CloneMe () const inline override virtual
Virtual copy constructor.
Reimplemented from PHObject.
Definition at line 35 of file CMFlashClusterv2.h.
View newest version in sPHENIX GitHub at line 35 of file CMFlashClusterv2.h
References CMFlashClusterv2().
void CMFlashClusterv2::CopyFrom (const CMFlashCluster & source) override virtual
copy content from base class
Reimplemented from CMFlashCluster.
Definition at line 39 of file CMFlashClusterv2.cc.
View newest version in sPHENIX GitHub at line 39 of file CMFlashClusterv2.cc
References CMFlashCluster::CopyFrom(), CMFlashCluster::getAdc(), CMFlashCluster::getIsPhiGap(), CMFlashCluster::getIsRGap(), CMFlashCluster::getX(), CMFlashCluster::getY(), CMFlashCluster::getZ(), setAdc(), setIsPhiGap(), setIsRGap(), setX(), setY(), and setZ().
void CMFlashClusterv2::CopyFrom (CMFlashCluster * source) inline override virtual
copy content from base class
Reimplemented from CMFlashCluster.
Definition at line 41 of file CMFlashClusterv2.h.
View newest version in sPHENIX GitHub at line 41 of file CMFlashClusterv2.h
References CopyFrom().
Referenced by CopyFrom().
unsigned int CMFlashClusterv2::getAdc () const inline override virtual
Reimplemented from CMFlashCluster.
Definition at line 63 of file CMFlashClusterv2.h.
View newest version in sPHENIX GitHub at line 63 of file CMFlashClusterv2.h
References m_adc.
Referenced by identify().
bool CMFlashClusterv2::getIsPhiGap () const inline override virtual
Reimplemented from CMFlashCluster.
Definition at line 57 of file CMFlashClusterv2.h.
View newest version in sPHENIX GitHub at line 57 of file CMFlashClusterv2.h
References m_isPhiGap.
bool CMFlashClusterv2::getIsRGap () const inline override virtual
Reimplemented from CMFlashCluster.
Definition at line 55 of file CMFlashClusterv2.h.
View newest version in sPHENIX GitHub at line 55 of file CMFlashClusterv2.h
References m_isRGap.
unsigned int CMFlashClusterv2::getNclusters () const inline override virtual
Reimplemented from CMFlashCluster.
Definition at line 53 of file CMFlashClusterv2.h.
View newest version in sPHENIX GitHub at line 53 of file CMFlashClusterv2.h
References m_nclusters.
float CMFlashClusterv2::getX () const inline override virtual
Reimplemented from CMFlashCluster.
Definition at line 47 of file CMFlashClusterv2.h.
View newest version in sPHENIX GitHub at line 47 of file CMFlashClusterv2.h
References m_pos.
Referenced by isValid().
float CMFlashClusterv2::getY () const inline override virtual
Reimplemented from CMFlashCluster.
Definition at line 49 of file CMFlashClusterv2.h.
View newest version in sPHENIX GitHub at line 49 of file CMFlashClusterv2.h
References m_pos.
Referenced by isValid().
float CMFlashClusterv2::getZ () const inline override virtual
Reimplemented from CMFlashCluster.
Definition at line 51 of file CMFlashClusterv2.h.
View newest version in sPHENIX GitHub at line 51 of file CMFlashClusterv2.h
References m_pos.
Referenced by isValid().
void CMFlashClusterv2::identify (std::ostream & os = std::cout) const override virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from CMFlashCluster.
Definition at line 12 of file CMFlashClusterv2.cc.
View newest version in sPHENIX GitHub at line 12 of file CMFlashClusterv2.cc
References getAdc(), and m_pos.
int CMFlashClusterv2::isValid () const override virtual
isValid returns non zero if object contains vailid data
Reimplemented from CMFlashCluster.
Definition at line 28 of file CMFlashClusterv2.cc.
View newest version in sPHENIX GitHub at line 28 of file CMFlashClusterv2.cc
References getX(), getY(), getZ(), and m_adc.
void CMFlashClusterv2::Reset () inline override virtual
Clear Event.
Reimplemented from CMFlashCluster.
Definition at line 33 of file CMFlashClusterv2.h.
View newest version in sPHENIX GitHub at line 33 of file CMFlashClusterv2.h
void CMFlashClusterv2::setAdc (unsigned int adc) inline override virtual
Reimplemented from CMFlashCluster.
Definition at line 64 of file CMFlashClusterv2.h.
View newest version in sPHENIX GitHub at line 64 of file CMFlashClusterv2.h
References m_adc.
Referenced by CopyFrom().
void CMFlashClusterv2::setIsPhiGap (bool isPhiGap) inline override virtual
Reimplemented from CMFlashCluster.
Definition at line 58 of file CMFlashClusterv2.h.
View newest version in sPHENIX GitHub at line 58 of file CMFlashClusterv2.h
References m_isPhiGap.
Referenced by CopyFrom().
void CMFlashClusterv2::setIsRGap (bool isRGap) inline override virtual
Reimplemented from CMFlashCluster.
Definition at line 56 of file CMFlashClusterv2.h.
View newest version in sPHENIX GitHub at line 56 of file CMFlashClusterv2.h
References m_isRGap.
Referenced by CopyFrom().
void CMFlashClusterv2::setNclusters (unsigned int n) inline override virtual
Reimplemented from CMFlashCluster.
Definition at line 54 of file CMFlashClusterv2.h.
View newest version in sPHENIX GitHub at line 54 of file CMFlashClusterv2.h
References m_nclusters, and n.
void CMFlashClusterv2::setX (float x) inline override virtual
Reimplemented from CMFlashCluster.
Definition at line 48 of file CMFlashClusterv2.h.
View newest version in sPHENIX GitHub at line 48 of file CMFlashClusterv2.h
References m_pos, and ambiguity_solver_full_chain::x.
Referenced by CopyFrom().
void CMFlashClusterv2::setY (float y) inline override virtual
Reimplemented from CMFlashCluster.
Definition at line 50 of file CMFlashClusterv2.h.
View newest version in sPHENIX GitHub at line 50 of file CMFlashClusterv2.h
References m_pos, and y.
Referenced by CopyFrom().
void CMFlashClusterv2::setZ (float z) inline override virtual
Reimplemented from CMFlashCluster.
Definition at line 52 of file CMFlashClusterv2.h.
View newest version in sPHENIX GitHub at line 52 of file CMFlashClusterv2.h
References m_pos, and physmon_track_finding_ttbar::z.
Referenced by CopyFrom().
Member Data Documentation
unsigned int CMFlashClusterv2::m_adc = 0xFFFFFFFF protected
cluster sum adc
Definition at line 72 of file CMFlashClusterv2.h.
View newest version in sPHENIX GitHub at line 72 of file CMFlashClusterv2.h
Referenced by getAdc(), isValid(), and setAdc().
bool CMFlashClusterv2::m_isPhiGap = false protected
Definition at line 79 of file CMFlashClusterv2.h.
View newest version in sPHENIX GitHub at line 79 of file CMFlashClusterv2.h
Referenced by getIsPhiGap(), and setIsPhiGap().
bool CMFlashClusterv2::m_isRGap = false protected
bools to identify if meta-cluster is across sector/module gaps
Definition at line 78 of file CMFlashClusterv2.h.
View newest version in sPHENIX GitHub at line 78 of file CMFlashClusterv2.h
Referenced by getIsRGap(), and setIsRGap().
unsigned int CMFlashClusterv2::m_nclusters = UINT_MAX protected
number of TPC clusters used to create this central mebrane cluster
Definition at line 75 of file CMFlashClusterv2.h.
View newest version in sPHENIX GitHub at line 75 of file CMFlashClusterv2.h
Referenced by getNclusters(), and setNclusters().
float CMFlashClusterv2::m_pos[3] = {NAN, NAN, NAN} protected
mean cluster position
Definition at line 69 of file CMFlashClusterv2.h.
View newest version in sPHENIX GitHub at line 69 of file CMFlashClusterv2.h
Referenced by getX(), getY(), getZ(), identify(), setX(), setY(), and setZ().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/trackbase/CMFlashClusterv2.h
coresoftware/blob/master/offline/packages/trackbase/CMFlashClusterv2.cc