Analysis Software: Acts::Legacy::InternalSeed< SpacePoint > Class Template Reference
Acts::Legacy::InternalSeed< SpacePoint > Class Template Reference
#include <acts/blob/sPHENIX/Plugins/Legacy/include/Acts/Seeding/LegacyInternalSeed.hpp>
Public Member Functions
InternalSeed ()
InternalSeed (SPForSeed< SpacePoint > *&, SPForSeed< SpacePoint > *&, SPForSeed< SpacePoint > *&, float)
InternalSeed (const InternalSeed< SpacePoint > &)
virtual ~InternalSeed ()
InternalSeed< SpacePoint > & operator= (const InternalSeed< SpacePoint > &)
SPForSeed< SpacePoint > * spacepoint0 ()
SPForSeed< SpacePoint > * spacepoint1 ()
SPForSeed< SpacePoint > * spacepoint2 ()
const float & z () const
const float & quality () const
void set (SPForSeed< SpacePoint > *&, SPForSeed< SpacePoint > *&, SPForSeed< SpacePoint > *&, float)
bool setQuality (float)
bool set3 (Acts::Legacy::Seed< SpacePoint > &)
Protected Attributes
SPForSeed< SpacePoint > * m_s0 = nullptr
SPForSeed< SpacePoint > * m_s1 = nullptr
SPForSeed< SpacePoint > * m_s2 = nullptr
float m_z = 0
float m_q = 0
Detailed Description
template<typename SpacePoint>
class Acts::Legacy::InternalSeed< SpacePoint >
Definition at line 20 of file LegacyInternalSeed.hpp.
View newest version in sPHENIX GitHub at line 20 of file LegacyInternalSeed.hpp
Constructor & Destructor Documentation
template<typename SpacePoint> Acts::Legacy::InternalSeed< SpacePoint >::InternalSeed ()
template<typename SpacePoint> Acts::Legacy::InternalSeed< SpacePoint >::InternalSeed (SPForSeed< SpacePoint > *& , SPForSeed< SpacePoint > *& , SPForSeed< SpacePoint > *& , float)
template<typename SpacePoint> Acts::Legacy::InternalSeed< SpacePoint >::InternalSeed (const InternalSeed< SpacePoint > &)
template<typename SpacePoint> virtual Acts::Legacy::InternalSeed< SpacePoint >::~InternalSeed () virtual
Member Function Documentation
template<typename SpacePoint> InternalSeed<SpacePoint>& Acts::Legacy::InternalSeed< SpacePoint >::operator= (const InternalSeed< SpacePoint > &)
template<typename SpacePoint> const float& Acts::Legacy::InternalSeed< SpacePoint >::quality () const inline
Definition at line 37 of file LegacyInternalSeed.hpp.
View newest version in sPHENIX GitHub at line 37 of file LegacyInternalSeed.hpp
References Acts::Legacy::InternalSeed< SpacePoint >::m_q.
template<typename SpacePoint> void Acts::Legacy::InternalSeed< SpacePoint >::set (SPForSeed< SpacePoint > *& , SPForSeed< SpacePoint > *& , SPForSeed< SpacePoint > *& , float)
Referenced by Acts::Legacy::AtlasSeedFinder< SpacePoint >::newOneSeed().
template<typename SpacePoint> bool Acts::Legacy::InternalSeed< SpacePoint >::set3 (Acts::Legacy::Seed< SpacePoint > &)
template<typename SpacePoint> bool Acts::Legacy::InternalSeed< SpacePoint >::setQuality (float)
Referenced by Acts::Legacy::AtlasSeedFinder< SpacePoint >::fillSeeds().
template<typename SpacePoint> SPForSeed<SpacePoint>* Acts::Legacy::InternalSeed< SpacePoint >::spacepoint0 () inline
Definition at line 33 of file LegacyInternalSeed.hpp.
View newest version in sPHENIX GitHub at line 33 of file LegacyInternalSeed.hpp
References Acts::Legacy::InternalSeed< SpacePoint >::m_s0.
Referenced by Acts::Legacy::AtlasSeedFinder< SpacePoint >::fillSeeds().
template<typename SpacePoint> SPForSeed<SpacePoint>* Acts::Legacy::InternalSeed< SpacePoint >::spacepoint1 () inline
Definition at line 34 of file LegacyInternalSeed.hpp.
View newest version in sPHENIX GitHub at line 34 of file LegacyInternalSeed.hpp
References Acts::Legacy::InternalSeed< SpacePoint >::m_s1.
Referenced by Acts::Legacy::AtlasSeedFinder< SpacePoint >::fillSeeds().
template<typename SpacePoint> SPForSeed<SpacePoint>* Acts::Legacy::InternalSeed< SpacePoint >::spacepoint2 () inline
Definition at line 35 of file LegacyInternalSeed.hpp.
View newest version in sPHENIX GitHub at line 35 of file LegacyInternalSeed.hpp
References Acts::Legacy::InternalSeed< SpacePoint >::m_s2.
Referenced by Acts::Legacy::AtlasSeedFinder< SpacePoint >::fillSeeds().
template<typename SpacePoint> const float& Acts::Legacy::InternalSeed< SpacePoint >::z () const inline
Definition at line 36 of file LegacyInternalSeed.hpp.
View newest version in sPHENIX GitHub at line 36 of file LegacyInternalSeed.hpp
References Acts::Legacy::InternalSeed< SpacePoint >::m_z.
Member Data Documentation
template<typename SpacePoint> float Acts::Legacy::InternalSeed< SpacePoint >::m_q = 0 protected
Definition at line 51 of file LegacyInternalSeed.hpp.
View newest version in sPHENIX GitHub at line 51 of file LegacyInternalSeed.hpp
Referenced by Acts::Legacy::InternalSeed< SpacePoint >::quality().
template<typename SpacePoint> SPForSeed<SpacePoint>* Acts::Legacy::InternalSeed< SpacePoint >::m_s0 = nullptr protected
Definition at line 47 of file LegacyInternalSeed.hpp.
View newest version in sPHENIX GitHub at line 47 of file LegacyInternalSeed.hpp
Referenced by Acts::Legacy::InternalSeed< SpacePoint >::spacepoint0().
template<typename SpacePoint> SPForSeed<SpacePoint>* Acts::Legacy::InternalSeed< SpacePoint >::m_s1 = nullptr protected
Definition at line 48 of file LegacyInternalSeed.hpp.
View newest version in sPHENIX GitHub at line 48 of file LegacyInternalSeed.hpp
Referenced by Acts::Legacy::InternalSeed< SpacePoint >::spacepoint1().
template<typename SpacePoint> SPForSeed<SpacePoint>* Acts::Legacy::InternalSeed< SpacePoint >::m_s2 = nullptr protected
Definition at line 49 of file LegacyInternalSeed.hpp.
View newest version in sPHENIX GitHub at line 49 of file LegacyInternalSeed.hpp
Referenced by Acts::Legacy::InternalSeed< SpacePoint >::spacepoint2().
template<typename SpacePoint> float Acts::Legacy::InternalSeed< SpacePoint >::m_z = 0 protected
Definition at line 50 of file LegacyInternalSeed.hpp.
View newest version in sPHENIX GitHub at line 50 of file LegacyInternalSeed.hpp
Referenced by Acts::Legacy::InternalSeed< SpacePoint >::z().
The documentation for this class was generated from the following file:
acts/blob/sPHENIX/Plugins/Legacy/include/Acts/Seeding/LegacyInternalSeed.hpp