Analysis Software: macros/blob/master/common/G4_Tracking.C File Reference
G4_Tracking.C File Reference
#include <GlobalVariables.C>
#include <QA.C>
#include <G4_Intt.C>
#include <G4_Micromegas.C>
#include <G4_Mvtx.C>
#include <G4_TPC.C>
#include <fun4all/Fun4AllServer.h>
#include <g4eval/SvtxEvaluator.h>
#include <trackreco/PHCASeeding.h>
#include <trackreco/PHHybridSeeding.h>
#include <trackreco/PHSimpleKFProp.h>
#include <trackreco/PHGenFitTrackProjection.h>
#include <trackreco/PHGenFitTrkFitter.h>
#include <trackreco/PHGenFitTrkProp.h>
#include <trackreco/PHHoughSeeding.h>
#include <trackreco/PHMicromegasTpcTrackMatching.h>
#include <trackreco/PHRaveVertexing.h>
#include <trackreco/PHSiliconTpcTrackMatching.h>
#include <trackreco/PHTpcTrackSeedVertexAssoc.h>
#include <trackreco/PHTrackCleaner.h>
#include <trackreco/PHTrackSeeding.h>
#include <trackreco/PHTruthSiliconAssociation.h>
#include <trackreco/PHTruthTrackSeeding.h>
#include <trackreco/PHTruthVertexing.h>
#include <trackreco/MakeActsGeometry.h>
#include <trackreco/PHActsSiliconSeeding.h>
#include <trackreco/PHActsTrkFitter.h>
#include <trackreco/PHActsInitialVertexFinder.h>
#include <trackreco/PHActsVertexFinder.h>
#include <tpccalib/TpcSpaceChargeReconstruction.h>
#include <tpccalib/PHTpcResiduals.h>
#include <trackbase/TrkrHitTruthAssoc.h>
#include <phtpctracker/PHTpcTracker.h>
#include <qa_modules/QAG4SimulationTracking.h>
#include <qa_modules/QAG4SimulationUpsilon.h>
#include <qa_modules/QAG4SimulationVertex.h>
Namespaces
namespace Enable
namespace G4TRACKING
Macros
#define MACRO_G4TRACKING_C
Functions
std::string G4TRACKING::vmethod ("avf-smoothing:1")
void TrackingInit ()
void Tracking_Reco ()
void Tracking_Eval (const std::string &outputfile)
void Tracking_QA ()
Variables
std::string G4TRACKING::SC_ROOTOUTPUT_FILENAME = "TpcSpaceChargeMatrices.root"
bool G4TRACKING::use_genfit = false
bool G4TRACKING::use_truth_init_vertexing = false
bool G4TRACKING::use_propagator = true
bool G4TRACKING::add_fake_surfaces = true
bool G4TRACKING::use_truth_silicon_seeding = false
bool G4TRACKING::use_truth_tpc_seeding = false
bool G4TRACKING::use_full_truth_track_seeding = false
Macro Definition Documentation
#define MACRO_G4TRACKING_C
Definition at line 2 of file G4_Tracking.C.
View newest version in sPHENIX GitHub at line 2 of file G4_Tracking.C
Function Documentation
void Tracking_Eval (const std::string & outputfile)
Definition at line 648 of file G4_Tracking.C.
View newest version in sPHENIX GitHub at line 648 of file G4_Tracking.C
References SvtxEvaluator::do_cluster_eval(), SvtxEvaluator::do_eval_light(), SvtxEvaluator::do_g4hit_eval(), SvtxEvaluator::do_gpoint_eval(), SvtxEvaluator::do_hit_eval(), G4TRACKING::g4eval_use_initial_vertex, Fun4AllServer::instance(), max, G4TPC::n_gas_layer, G4INTT::n_intt_layer, G4MVTX::n_maps_layer, G4MICROMEGAS::n_micromegas_layer, Fun4AllServer::registerSubsystem(), SvtxEvaluator::scan_for_embedded(), SvtxEvaluator::set_use_genfit_vertex(), SvtxEvaluator::set_use_initial_vertex(), Enable::TRACKING_VERBOSITY, G4TRACKING::use_genfit, verbosity, Enable::VERBOSITY, and Fun4AllBase::Verbosity().
void Tracking_QA ()
Definition at line 681 of file G4_Tracking.C.
View newest version in sPHENIX GitHub at line 681 of file G4_Tracking.C
References QAG4SimulationUpsilon::addEmbeddingID(), Fun4AllServer::instance(), max, Enable::QA_VERBOSITY, Fun4AllServer::registerSubsystem(), QAG4SimulationVertex::setVertexMapName(), Enable::TRACKING_VERBOSITY, Input::UPSILON, Input::UPSILON_EmbedIds, G4TRACKING::use_genfit, G4TRACKING::use_rave_vertexing, verbosity, and Fun4AllBase::Verbosity().
void Tracking_Reco ()
If running with distortions, fit only the silicon+MMs first
run tpc residual determination with silicon+MM track fit
If running with distortions, fit only the silicon+MMs first
run tpc residual determination with silicon+MM track fit
Definition at line 194 of file G4_Tracking.C.
View newest version in sPHENIX GitHub at line 194 of file G4_Tracking.C
References PHActsTrkFitter::doTimeAnalysis(), PHTpcTracker::enable_json_export(), PHTpcTracker::enable_vertexing(), PHActsTrkFitter::fitSiliconMMs(), i, Fun4AllServer::instance(), layer, M_PI, G4MAGNET::magfield, G4MAGNET::magfield_rescale, max, G4TPC::n_gas_layer, G4INTT::n_intt_layer, G4MVTX::n_maps_layer, G4MICROMEGAS::n_micromegas_layer, Fun4AllServer::registerSubsystem(), G4TRACKING::SC_CALIBMODE, G4TRACKING::SC_COLLISIONRATE, G4TRACKING::SC_ROOTOUTPUT_FILENAME, PHTruthVertexing::set_acts_silicon(), PHMicromegasTpcTrackMatching::set_collision_rate(), PHSiliconTpcTrackMatching::set_collision_rate(), PHSiliconTpcTrackMatching::set_eta_search_window(), PHSiliconTpcTrackMatching::set_field(), PHSiliconTpcTrackMatching::set_field_dir(), PHSimpleKFProp::set_field_dir(), PHHybridSeeding::set_field_dir(), PHTruthTrackSeeding::set_max_layer(), PHSimpleKFProp::set_max_window(), PHTruthTrackSeeding::set_min_layer(), PHMicromegasTpcTrackMatching::set_min_tpc_layer(), TpcSpaceChargeReconstruction::set_outputfile(), PHRaveVertexing::set_over_write_svtxvertexmap(), PHSiliconTpcTrackMatching::set_phi_search_window(), PHMicromegasTpcTrackMatching::set_rphi_search_window_lyr1(), PHMicromegasTpcTrackMatching::set_rphi_search_window_lyr2(), PHMicromegasTpcTrackMatching::set_sc_calib_mode(), PHSiliconTpcTrackMatching::set_sc_calib_mode(), PHTpcTracker::set_seed_finder_optimization_remove_loopers(), PHTpcTracker::set_seed_finder_options(), PHRaveVertexing::set_svtxvertexmaprefit_node_name(), PHMicromegasTpcTrackMatching::set_test_windows_printout(), PHSiliconTpcTrackMatching::set_test_windows_printout(), PHTpcTracker::set_track_follower_optimization_helix(), PHTpcTracker::set_track_follower_optimization_precise_fit(), PHTrackSeeding::set_track_map_name(), PHMicromegasTpcTrackMatching::set_z_search_window_lyr1(), PHMicromegasTpcTrackMatching::set_z_search_window_lyr2(), PHHybridSeeding::setMinTrackSize(), PHHybridSeeding::setNThreads(), PHTpcResiduals::setOutputfile(), PHHybridSeeding::setSearchAngle(), PHHybridSeeding::setSearchRadius(), PHActsInitialVertexFinder::setSvtxTrackMapName(), PHActsInitialVertexFinder::setSvtxVertexMapName(), Enable::TRACKING_VERBOSITY, G4TRACKING::use_full_truth_track_seeding, G4TRACKING::use_genfit, G4TRACKING::use_hybrid_seeding, G4TRACKING::use_PHTpcTracker_seeding, G4TRACKING::use_propagator, G4TRACKING::use_rave_vertexing, G4TRACKING::use_truth_init_vertexing, G4TRACKING::use_truth_si_matching, G4TRACKING::use_truth_silicon_seeding, G4TRACKING::use_truth_tpc_seeding, PHSimpleKFProp::useConstBField(), PHSimpleKFProp::useFixedClusterError(), verbosity, Enable::VERBOSITY, Fun4AllBase::Verbosity(), and G4TRACKING::vmethod().
void TrackingInit ()
Built the Acts geometry
Definition at line 116 of file G4_Tracking.C.
View newest version in sPHENIX GitHub at line 116 of file G4_Tracking.C
References MakeActsGeometry::add_fake_surfaces(), G4TRACKING::add_fake_surfaces, G4TPC::ENABLE_CORRECTIONS, G4TPC::ENABLE_STATIC_DISTORTIONS, G4TPC::ENABLE_TIME_ORDERED_DISTORTIONS, Fun4AllServer::instance(), G4MAGNET::magfield, G4MAGNET::magfield_rescale, max, Enable::MICROMEGAS, G4MICROMEGAS::n_micromegas_layer, Fun4AllServer::registerSubsystem(), G4TRACKING::SC_CALIBMODE, MakeActsGeometry::setMagField(), MakeActsGeometry::setMagFieldRescale(), Enable::TRACKING_VERBOSITY, G4TRACKING::use_genfit, G4TRACKING::use_hybrid_seeding, G4TRACKING::use_PHTpcTracker_seeding, verbosity, Enable::VERBOSITY, and Fun4AllBase::Verbosity().