Analysis Software: PHCASeeding Class Reference
PHCASeeding Class Reference
#include <coresoftware/blob/master/offline/packages/trackreco/PHCASeeding.h>
Public Member Functions
PHCASeeding (const std::string &name="PHCASeeding", unsigned int start_layer=7, unsigned int end_layer=55, unsigned int min_nhits_per_cluster=0, unsigned int min_clusters_per_track=5, const unsigned int nlayers_maps=3, const unsigned int nlayers_intt=4, const unsigned int nlayers_tpc=48, float neighbor_phi_width=.02, float neighbor_eta_width=.01, float maxSinPhi=0.999, float Bz=14 *0.000299792458f, float cosTheta_limit=-0.8)
~PHCASeeding () override
void SetLayerRange (unsigned int layer_low, unsigned int layer_up)
void SetSearchWindow (float eta_width, float phi_width)
void SetMinHitsPerCluster (unsigned int minHits)
void SetMinClustersPerTrack (unsigned int minClus)
void set_field_dir (const double rescale)
void useConstBField (bool opt)
void useFixedClusterError (bool opt)
void setFixedClusterError (int i, double val)
Public Member Functions inherited from PHTrackSeeding
PHTrackSeeding (const std::string &name="PHTrackSeeding")
~PHTrackSeeding () override
int InitRun (PHCompositeNode *topNode) override
int process_event (PHCompositeNode *topNode) override
int End (PHCompositeNode *topNode) override
Called at the end of all processing.
void set_track_map_name (const std::string &map_name)
void SetUseTruthClusters (bool setit)
Public Member Functions inherited from SubsysReco
~SubsysReco () override
virtual int EndRun (const int)
Called at the end of each run.
virtual int Init (PHCompositeNode *)
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
void Print (const std::string &what="ALL") const override
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Protected Member Functions
int Setup (PHCompositeNode *topNode) override
int Process (PHCompositeNode *topNode) override
int InitializeGeometry (PHCompositeNode *topNode)
int FindSeedsLayerSkip (double cosTheta_limit)
int End () override
Called in SubsysReco::End.
Private Member Functions
double phiadd (double phi1, double phi2)
double phidiff (double phi1, double phi2)
void FillTree ()
void FillTree (std::vector< pointKey > clusters)
std::vector< coordKey > FindLinkedClusters ()
int FindSeedsWithMerger ()
std::pair< std::vector
< std::unordered_set< keylink >
>, std::vector
< std::unordered_set< keylink > > > CreateLinks (std::vector< coordKey > clusters, int mode=skip_layers::off)
std::vector< std::vector
< keylink > > FindBiLinks (std::vector< std::unordered_set< keylink >> belowLinks, std::vector< std::unordered_set< keylink >> aboveLinks)
std::vector< keylist > FollowBiLinks (std::vector< std::vector< keylink >> bidirectionalLinks)
void QueryTree (const bgi::rtree< pointKey, bgi::quadratic< 16 >> &rtree, double phimin, double etamin, double lmin, double phimax, double etamax, double lmax, std::vector< pointKey > &returned_values)
pointKey toPointKey (coordKey v)
std::vector< pointKey > toPointKey (std::vector< coordKey > v)
coordKey fromPointKey (pointKey p)
std::vector< coordKey > fromPointKey (std::vector< pointKey > p)
Eigen::Matrix< float, 6, 6 > getEigenCov (SvtxTrack_v2 &track)
std::vector< keylist > MergeSeeds (std::vector< keylist > seeds)
pointKey makepointKey (TrkrDefs::cluskey k)
std::vector< keylist > RemoveBadClusters (std::vector< keylist > seeds)
void publishSeeds (std::vector< SvtxTrack_v2 > seeds)
Private Attributes
SvtxTrackMap * _g4tracks
fetch node pointers
SvtxVertexMap * _g4vertexes
SvtxHitMap * _svtxhitsmap
int * _hit_used_map
int _hit_used_map_size
std::vector< float > _radii_all
std::map< int, unsigned int > _layer_ilayer_map_all
std::map< int, unsigned int > _layer_ilayer_map
SvtxVertex * _vertex
const unsigned int _nlayers_maps
const unsigned int _nlayers_intt
const unsigned int _nlayers_tpc
unsigned int _start_layer
unsigned int _end_layer
unsigned int _min_nhits_per_cluster
unsigned int _min_clusters_per_track
float _neighbor_phi_width
float _neighbor_eta_width
float _max_sin_phi
float _Bz
float _cosTheta_limit
double _rz_outlier_threshold = 0.1
double _xy_outlier_threshold = 0.1
double _fieldDir = -1
bool _use_const_field = false
bool _use_fixed_clus_err = false
std::array< double, 3 > _fixed_clus_err = {.1,.1,.1}
std::shared_ptr< ALICEKF > fitter
std::unique_ptr< PHTimer > t_seed
std::unique_ptr< PHTimer > t_fill
bgi::rtree< pointKey,
bgi::quadratic< 16 > > _rtree
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = INT_MAX - 10
}
Protected Attributes inherited from PHTrackSeeding
TrkrClusterContainer * _cluster_map = nullptr
TrkrClusterHitAssoc * _cluster_hit_map = nullptr
SvtxVertexMap * _vertex_map = nullptr
SvtxTrackMap * _track_map = nullptr
AssocInfoContainer * _assoc_container = nullptr
TrkrHitSetContainer * _hitsets = nullptr
std::string _track_map_name = "SvtxTrackMap"
bool _use_truth_clusters = false
Detailed Description
Definition at line 74 of file PHCASeeding.h.
View newest version in sPHENIX GitHub at line 74 of file PHCASeeding.h
Constructor & Destructor Documentation
PHCASeeding::PHCASeeding (const std::string & name = "PHCASeeding", unsigned int start_layer = 7, unsigned int end_layer = 55, unsigned int min_nhits_per_cluster = 0, unsigned int min_clusters_per_track = 5, const unsigned int nlayers_maps = 3, const unsigned int nlayers_intt = 4, const unsigned int nlayers_tpc = 48, float neighbor_phi_width = .02, float neighbor_eta_width = .01, float maxSinPhi = 0.999, float Bz = 14*0.000299792458f, float cosTheta_limit = -0.8)
Definition at line 135 of file PHCASeeding.cc.
View newest version in sPHENIX GitHub at line 135 of file PHCASeeding.cc
PHCASeeding::~PHCASeeding () inline override
Definition at line 92 of file PHCASeeding.h.
View newest version in sPHENIX GitHub at line 92 of file PHCASeeding.h
Member Function Documentation
pair< vector< unordered_set< keylink > >, vector< unordered_set< keylink > > > PHCASeeding::CreateLinks (std::vector< coordKey > clusters, int mode = skip_layers::off) private
Definition at line 568 of file PHCASeeding.cc.
View newest version in sPHENIX GitHub at line 568 of file PHCASeeding.cc
References PHTrackSeeding::_cluster_map, _cosTheta_limit, _end_layer, _neighbor_eta_width, _neighbor_phi_width, _nlayers_intt, _nlayers_maps, _nlayers_tpc, _rtree, _start_layer, breaking_angle(), TrkrClusterContainer::findCluster(), fromPointKey(), TrkrCluster::getPosition(), LogDebug, on, QueryTree(), t_seed, Acts::Test::transform, and Fun4AllBase::Verbosity().
Referenced by FindLinkedClusters(), and FindSeedsWithMerger().
int PHCASeeding::End () override protected virtual
Called in SubsysReco::End.
Implements PHTrackSeeding.
Definition at line 1063 of file PHCASeeding.cc.
View newest version in sPHENIX GitHub at line 1063 of file PHCASeeding.cc
References Fun4AllReturnCodes::EVENT_OK, and Fun4AllBase::Verbosity().
void PHCASeeding::FillTree () private
Definition at line 335 of file PHCASeeding.cc.
View newest version in sPHENIX GitHub at line 335 of file PHCASeeding.cc
References PHTrackSeeding::_cluster_map, _end_layer, PHTrackSeeding::_hitsets, _rtree, TrkrClusterContainer::getClusters(), TrkrHitSetContainer::getHitSets(), TrkrDefs::getLayer(), TrkrCluster::getPosition(), j, layer, M_PI, QueryTree(), t_fill, TrkrDefs::tpcId, and Fun4AllBase::Verbosity().
Referenced by MergeSeeds(), and Process().
void PHCASeeding::FillTree (std::vector< pointKey > clusters) private
Definition at line 401 of file PHCASeeding.cc.
View newest version in sPHENIX GitHub at line 401 of file PHCASeeding.cc
References PHTrackSeeding::_cluster_hit_map, _end_layer, _min_nhits_per_cluster, _rtree, TrkrClusterHitAssoc::getHits(), TrkrDefs::getLayer(), j, layer, t_fill, and Fun4AllBase::Verbosity().
vector< vector< keylink > > PHCASeeding::FindBiLinks (std::vector< std::unordered_set< keylink >> belowLinks, std::vector< std::unordered_set< keylink >> aboveLinks) private
Definition at line 788 of file PHCASeeding.cc.
View newest version in sPHENIX GitHub at line 788 of file PHCASeeding.cc
References _nlayers_intt, _nlayers_maps, _nlayers_tpc, TrkrDefs::getLayer(), layer, ast::reversed(), t_seed, and Fun4AllBase::Verbosity().
Referenced by FindLinkedClusters(), and FindSeedsWithMerger().
vector< coordKey > PHCASeeding::FindLinkedClusters () private
Definition at line 482 of file PHCASeeding.cc.
View newest version in sPHENIX GitHub at line 482 of file PHCASeeding.cc
References _nlayers_intt, _nlayers_maps, _nlayers_tpc, _rtree, CreateLinks(), FindBiLinks(), fromPointKey(), k, LogDebug, M_PI, QueryTree(), t_seed, and Fun4AllBase::Verbosity().
int PHCASeeding::FindSeedsLayerSkip (double cosTheta_limit) protected
int PHCASeeding::FindSeedsWithMerger () private
Definition at line 521 of file PHCASeeding.cc.
View newest version in sPHENIX GitHub at line 521 of file PHCASeeding.cc
References _end_layer, _nlayers_tpc, _rtree, _start_layer, CreateLinks(), FindBiLinks(), fitter, FollowBiLinks(), fromPointKey(), LogDebug, M_PI, publishSeeds(), QueryTree(), RemoveBadClusters(), t_seed, and Fun4AllBase::Verbosity().
Referenced by Process().
vector< keylist > PHCASeeding::FollowBiLinks (std::vector< std::vector< keylink >> bidirectionalLinks) private
Definition at line 814 of file PHCASeeding.cc.
View newest version in sPHENIX GitHub at line 814 of file PHCASeeding.cc
References PHTrackSeeding::_cluster_map, _nlayers_intt, _nlayers_maps, _nlayers_tpc, TrkrClusterContainer::findCluster(), TrkrDefs::getLayer(), TrkrCluster::getPosition(), i, j, k, layer, LogDebug, M_PI, t_seed, and Fun4AllBase::Verbosity().
Referenced by FindSeedsWithMerger().
coordKey PHCASeeding::fromPointKey (pointKey p) private
Definition at line 443 of file PHCASeeding.cc.
View newest version in sPHENIX GitHub at line 443 of file PHCASeeding.cc
Referenced by CreateLinks(), FindLinkedClusters(), and FindSeedsWithMerger().
vector< coordKey > PHCASeeding::fromPointKey (std::vector< pointKey > p) private
Definition at line 448 of file PHCASeeding.cc.
View newest version in sPHENIX GitHub at line 448 of file PHCASeeding.cc
References gtest_output_test::output.
Eigen::Matrix<float,6,6> PHCASeeding::getEigenCov (SvtxTrack_v2 & track) private
int PHCASeeding::InitializeGeometry (PHCompositeNode * topNode) protected
Definition at line 171 of file PHCASeeding.cc.
View newest version in sPHENIX GitHub at line 171 of file PHCASeeding.cc
References _layer_ilayer_map, _layer_ilayer_map_all, _radii_all, Fun4AllReturnCodes::EVENT_OK, PHG4CylinderCellGeomContainer::get_begin_end(), PHG4CylinderCellGeom::get_layer(), PHG4CylinderGeom::get_layer(), PHG4CylinderCellGeom::get_radius(), PHG4CylinderGeom::get_radius(), PHG4CylinderCellGeom::get_thickness(), PHG4CylinderGeom::get_thickness(), and findNode::getClass().
Referenced by Setup().
pointKey PHCASeeding::makepointKey (TrkrDefs::cluskey k) private
Definition at line 389 of file PHCASeeding.cc.
View newest version in sPHENIX GitHub at line 389 of file PHCASeeding.cc
References PHTrackSeeding::_cluster_map, TrkrClusterContainer::findCluster(), TrkrDefs::getLayer(), TrkrCluster::getPosition(), and M_PI.
Referenced by MergeSeeds().
vector< keylist > PHCASeeding::MergeSeeds (std::vector< keylist > seeds) private
Definition at line 964 of file PHCASeeding.cc.
View newest version in sPHENIX GitHub at line 964 of file PHCASeeding.cc
References _neighbor_eta_width, _neighbor_phi_width, _rtree, Acts::VectorHelpers::eta(), FillTree(), i, k, layer, makepointKey(), phi, QueryTree(), TauVsDIS_MachineLearning_Differentiation::seed, and Fun4AllBase::Verbosity().
double PHCASeeding::phiadd (double phi1, double phi2) private
Definition at line 304 of file PHCASeeding.cc.
View newest version in sPHENIX GitHub at line 304 of file PHCASeeding.cc
References M_PI, and Acts::UnitConstants::s.
double PHCASeeding::phidiff (double phi1, double phi2) private
Definition at line 315 of file PHCASeeding.cc.
View newest version in sPHENIX GitHub at line 315 of file PHCASeeding.cc
References d, and M_PI.
int PHCASeeding::Process (PHCompositeNode * topNode) override protected virtual
process event interface for trackers, called in process_event. implemented in derived classes
Implements PHTrackSeeding.
Definition at line 459 of file PHCASeeding.cc.
View newest version in sPHENIX GitHub at line 459 of file PHCASeeding.cc
References _rtree, Fun4AllReturnCodes::EVENT_OK, FillTree(), FindSeedsWithMerger(), t_seed, and Fun4AllBase::Verbosity().
void PHCASeeding::publishSeeds (std::vector< SvtxTrack_v2 > seeds) private
Definition at line 1031 of file PHCASeeding.cc.
View newest version in sPHENIX GitHub at line 1031 of file PHCASeeding.cc
References PHTrackSeeding::_track_map, i, and SvtxTrackMap::insert().
Referenced by FindSeedsWithMerger().
void PHCASeeding::QueryTree (const bgi::rtree< pointKey, bgi::quadratic< 16 >> & rtree, double phimin, double etamin, double lmin, double phimax, double etamax, double lmax, std::vector< pointKey > & returned_values) private
Definition at line 326 of file PHCASeeding.cc.
View newest version in sPHENIX GitHub at line 326 of file PHCASeeding.cc
References M_PI, and MATSCAN::phimin.
Referenced by CreateLinks(), FillTree(), FindLinkedClusters(), FindSeedsWithMerger(), and MergeSeeds().
vector< keylist > PHCASeeding::RemoveBadClusters (std::vector< keylist > seeds) private
Definition at line 922 of file PHCASeeding.cc.
View newest version in sPHENIX GitHub at line 922 of file PHCASeeding.cc
References PHTrackSeeding::_cluster_map, _xy_outlier_threshold, A, c, TrkrClusterContainer::findCluster(), fitter, TrkrCluster::getX(), TrkrCluster::getY(), TrkrCluster::getZ(), i, Acts::IntegrationTest::R, Fun4AllBase::Verbosity(), x, y, and z.
Referenced by FindSeedsWithMerger().
void PHCASeeding::set_field_dir (const double rescale) inline
Definition at line 98 of file PHCASeeding.h.
View newest version in sPHENIX GitHub at line 98 of file PHCASeeding.h
References _fieldDir.
void PHCASeeding::setFixedClusterError (int i, double val) inline
Definition at line 108 of file PHCASeeding.h.
View newest version in sPHENIX GitHub at line 108 of file PHCASeeding.h
References _fixed_clus_err.
void PHCASeeding::SetLayerRange (unsigned int layer_low, unsigned int layer_up) inline
Definition at line 93 of file PHCASeeding.h.
View newest version in sPHENIX GitHub at line 93 of file PHCASeeding.h
References _end_layer, and _start_layer.
void PHCASeeding::SetMinClustersPerTrack (unsigned int minClus) inline
Definition at line 96 of file PHCASeeding.h.
View newest version in sPHENIX GitHub at line 96 of file PHCASeeding.h
References _min_clusters_per_track.
void PHCASeeding::SetMinHitsPerCluster (unsigned int minHits) inline
Definition at line 95 of file PHCASeeding.h.
View newest version in sPHENIX GitHub at line 95 of file PHCASeeding.h
References _min_nhits_per_cluster.
void PHCASeeding::SetSearchWindow (float eta_width, float phi_width) inline
Definition at line 94 of file PHCASeeding.h.
View newest version in sPHENIX GitHub at line 94 of file PHCASeeding.h
References _neighbor_eta_width, and _neighbor_phi_width.
int PHCASeeding::Setup (PHCompositeNode * topNode) override protected virtual
setup interface for trackers, called in InitRun, setup things like pointers to nodes. overrided in derived classes
Reimplemented from PHTrackSeeding.
Definition at line 1039 of file PHCASeeding.cc.
View newest version in sPHENIX GitHub at line 1039 of file PHCASeeding.cc
References PHTrackSeeding::_cluster_map, _fieldDir, _fixed_clus_err, _max_sin_phi, _min_clusters_per_track, _use_const_field, _use_fixed_clus_err, Fun4AllReturnCodes::EVENT_OK, fitter, InitializeGeometry(), PHTrackSeeding::Setup(), t_fill, t_seed, and Fun4AllBase::Verbosity().
pointKey PHCASeeding::toPointKey (coordKey v) private
Definition at line 427 of file PHCASeeding.cc.
View newest version in sPHENIX GitHub at line 427 of file PHCASeeding.cc
vector< pointKey > PHCASeeding::toPointKey (std::vector< coordKey > v) private
Definition at line 432 of file PHCASeeding.cc.
View newest version in sPHENIX GitHub at line 432 of file PHCASeeding.cc
References gtest_output_test::output.
void PHCASeeding::useConstBField (bool opt) inline
Definition at line 106 of file PHCASeeding.h.
View newest version in sPHENIX GitHub at line 106 of file PHCASeeding.h
References _use_const_field.
void PHCASeeding::useFixedClusterError (bool opt) inline
Definition at line 107 of file PHCASeeding.h.
View newest version in sPHENIX GitHub at line 107 of file PHCASeeding.h
References _use_fixed_clus_err.
Member Data Documentation
float PHCASeeding::_Bz private
Definition at line 170 of file PHCASeeding.h.
View newest version in sPHENIX GitHub at line 170 of file PHCASeeding.h
float PHCASeeding::_cosTheta_limit private
Definition at line 171 of file PHCASeeding.h.
View newest version in sPHENIX GitHub at line 171 of file PHCASeeding.h
Referenced by CreateLinks().
unsigned int PHCASeeding::_end_layer private
Definition at line 162 of file PHCASeeding.h.
View newest version in sPHENIX GitHub at line 162 of file PHCASeeding.h
Referenced by CreateLinks(), FillTree(), FindSeedsWithMerger(), and SetLayerRange().
double PHCASeeding::_fieldDir = -1 private
Definition at line 175 of file PHCASeeding.h.
View newest version in sPHENIX GitHub at line 175 of file PHCASeeding.h
Referenced by set_field_dir(), and Setup().
std::array<double,3> PHCASeeding::_fixed_clus_err = {.1,.1,.1} private
Definition at line 178 of file PHCASeeding.h.
View newest version in sPHENIX GitHub at line 178 of file PHCASeeding.h
Referenced by setFixedClusterError(), and Setup().
SvtxTrackMap* PHCASeeding::_g4tracks private
fetch node pointers
Definition at line 121 of file PHCASeeding.h.
View newest version in sPHENIX GitHub at line 121 of file PHCASeeding.h
SvtxVertexMap* PHCASeeding::_g4vertexes private
Definition at line 122 of file PHCASeeding.h.
View newest version in sPHENIX GitHub at line 122 of file PHCASeeding.h
int* PHCASeeding::_hit_used_map private
Definition at line 125 of file PHCASeeding.h.
View newest version in sPHENIX GitHub at line 125 of file PHCASeeding.h
int PHCASeeding::_hit_used_map_size private
Definition at line 126 of file PHCASeeding.h.
View newest version in sPHENIX GitHub at line 126 of file PHCASeeding.h
std::map<int, unsigned int> PHCASeeding::_layer_ilayer_map private
Definition at line 151 of file PHCASeeding.h.
View newest version in sPHENIX GitHub at line 151 of file PHCASeeding.h
Referenced by InitializeGeometry().
std::map<int, unsigned int> PHCASeeding::_layer_ilayer_map_all private
Definition at line 150 of file PHCASeeding.h.
View newest version in sPHENIX GitHub at line 150 of file PHCASeeding.h
Referenced by InitializeGeometry().
float PHCASeeding::_max_sin_phi private
Definition at line 169 of file PHCASeeding.h.
View newest version in sPHENIX GitHub at line 169 of file PHCASeeding.h
Referenced by Setup().
unsigned int PHCASeeding::_min_clusters_per_track private
Definition at line 164 of file PHCASeeding.h.
View newest version in sPHENIX GitHub at line 164 of file PHCASeeding.h
Referenced by SetMinClustersPerTrack(), and Setup().
unsigned int PHCASeeding::_min_nhits_per_cluster private
Definition at line 163 of file PHCASeeding.h.
View newest version in sPHENIX GitHub at line 163 of file PHCASeeding.h
Referenced by FillTree(), and SetMinHitsPerCluster().
float PHCASeeding::_neighbor_eta_width private
Definition at line 168 of file PHCASeeding.h.
View newest version in sPHENIX GitHub at line 168 of file PHCASeeding.h
Referenced by CreateLinks(), MergeSeeds(), and SetSearchWindow().
float PHCASeeding::_neighbor_phi_width private
Definition at line 167 of file PHCASeeding.h.
View newest version in sPHENIX GitHub at line 167 of file PHCASeeding.h
Referenced by CreateLinks(), MergeSeeds(), and SetSearchWindow().
const unsigned int PHCASeeding::_nlayers_intt private
Definition at line 159 of file PHCASeeding.h.
View newest version in sPHENIX GitHub at line 159 of file PHCASeeding.h
Referenced by CreateLinks(), FindBiLinks(), FindLinkedClusters(), and FollowBiLinks().
const unsigned int PHCASeeding::_nlayers_maps private
Definition at line 158 of file PHCASeeding.h.
View newest version in sPHENIX GitHub at line 158 of file PHCASeeding.h
Referenced by CreateLinks(), FindBiLinks(), FindLinkedClusters(), and FollowBiLinks().
const unsigned int PHCASeeding::_nlayers_tpc private
Definition at line 160 of file PHCASeeding.h.
View newest version in sPHENIX GitHub at line 160 of file PHCASeeding.h
Referenced by CreateLinks(), FindBiLinks(), FindLinkedClusters(), FindSeedsWithMerger(), and FollowBiLinks().
std::vector<float> PHCASeeding::_radii_all private
Definition at line 128 of file PHCASeeding.h.
View newest version in sPHENIX GitHub at line 128 of file PHCASeeding.h
Referenced by InitializeGeometry().
bgi::rtree<pointKey, bgi::quadratic<16> > PHCASeeding::_rtree private
Definition at line 184 of file PHCASeeding.h.
View newest version in sPHENIX GitHub at line 184 of file PHCASeeding.h
Referenced by CreateLinks(), FillTree(), FindLinkedClusters(), FindSeedsWithMerger(), MergeSeeds(), and Process().
double PHCASeeding::_rz_outlier_threshold = 0.1 private
Definition at line 172 of file PHCASeeding.h.
View newest version in sPHENIX GitHub at line 172 of file PHCASeeding.h
unsigned int PHCASeeding::_start_layer private
Definition at line 161 of file PHCASeeding.h.
View newest version in sPHENIX GitHub at line 161 of file PHCASeeding.h
Referenced by CreateLinks(), FindSeedsWithMerger(), and SetLayerRange().
SvtxHitMap* PHCASeeding::_svtxhitsmap private
Definition at line 124 of file PHCASeeding.h.
View newest version in sPHENIX GitHub at line 124 of file PHCASeeding.h
bool PHCASeeding::_use_const_field = false private
Definition at line 176 of file PHCASeeding.h.
View newest version in sPHENIX GitHub at line 176 of file PHCASeeding.h
Referenced by Setup(), and useConstBField().
bool PHCASeeding::_use_fixed_clus_err = false private
Definition at line 177 of file PHCASeeding.h.
View newest version in sPHENIX GitHub at line 177 of file PHCASeeding.h
Referenced by Setup(), and useFixedClusterError().
SvtxVertex* PHCASeeding::_vertex private
Definition at line 156 of file PHCASeeding.h.
View newest version in sPHENIX GitHub at line 156 of file PHCASeeding.h
double PHCASeeding::_xy_outlier_threshold = 0.1 private
Definition at line 173 of file PHCASeeding.h.
View newest version in sPHENIX GitHub at line 173 of file PHCASeeding.h
Referenced by RemoveBadClusters().
std::shared_ptr<ALICEKF> PHCASeeding::fitter private
Definition at line 180 of file PHCASeeding.h.
View newest version in sPHENIX GitHub at line 180 of file PHCASeeding.h
Referenced by FindSeedsWithMerger(), RemoveBadClusters(), and Setup().
std::unique_ptr<PHTimer> PHCASeeding::t_fill private
Definition at line 183 of file PHCASeeding.h.
View newest version in sPHENIX GitHub at line 183 of file PHCASeeding.h
Referenced by FillTree(), and Setup().
std::unique_ptr<PHTimer> PHCASeeding::t_seed private
Definition at line 182 of file PHCASeeding.h.
View newest version in sPHENIX GitHub at line 182 of file PHCASeeding.h
Referenced by CreateLinks(), FindBiLinks(), FindLinkedClusters(), FindSeedsWithMerger(), FollowBiLinks(), Process(), and Setup().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/trackreco/PHCASeeding.h
coresoftware/blob/master/offline/packages/trackreco/PHCASeeding.cc