Analysis Software: TrackSeedTrackMapConverter Class Reference
TrackSeedTrackMapConverter Class Reference
#include <coresoftware/blob/master/offline/packages/TrackingDiagnostics/TrackSeedTrackMapConverter.h>
Public Member Functions
TrackSeedTrackMapConverter (const std::string &name="TrackSeedTrackMapConverter")
virtual ~TrackSeedTrackMapConverter ()
int InitRun (PHCompositeNode *topNode) override
int process_event (PHCompositeNode *topNode) override
int End (PHCompositeNode *topNode) override
Called at the end of all processing.
void setFieldMap (const std::string &name)
void setTrackMapName (const std::string &name)
void setTrackSeedName (const std::string &name)
void cosmics ()
Public Member Functions inherited from SubsysReco
~SubsysReco () override
virtual int EndRun (const int)
Called at the end of each run.
virtual int Init (PHCompositeNode *)
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
void Print (const std::string &="ALL") const override
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Private Member Functions
int getNodes (PHCompositeNode *topNode)
void addKeys (std::unique_ptr< SvtxTrack_v4 > &track, TrackSeed *seed)
void addKeys (TrackSeed *seedToAddTo, TrackSeed *seedToAdd)
std::pair< int, float > getCosmicCharge (TrackSeed *seed, float vertexradius) const
Private Attributes
std::string m_trackMapName = "SvtxTrackMap"
std::string m_trackSeedName = "TpcTrackSeedContainer"
bool m_cosmics = false
SvtxTrackMap * m_trackMap = nullptr
TrackSeedContainer * m_seedContainer = nullptr
TrackSeedContainer * m_tpcContainer = nullptr
TrackSeedContainer * m_siContainer = nullptr
std::string m_fieldMap = ""
TrkrClusterContainer * m_clusters = nullptr
ActsGeometry * m_tGeometry = nullptr
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = std::numeric_limits<int>::max() - 10
}
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Detailed Description
Definition at line 18 of file TrackSeedTrackMapConverter.h.
View newest version in sPHENIX GitHub at line 18 of file TrackSeedTrackMapConverter.h
Constructor & Destructor Documentation
TrackSeedTrackMapConverter::TrackSeedTrackMapConverter (const std::string & name = "TrackSeedTrackMapConverter")
Definition at line 32 of file TrackSeedTrackMapConverter.cc.
View newest version in sPHENIX GitHub at line 32 of file TrackSeedTrackMapConverter.cc
TrackSeedTrackMapConverter::~TrackSeedTrackMapConverter () virtual default
Member Function Documentation
void TrackSeedTrackMapConverter::addKeys (std::unique_ptr< SvtxTrack_v4 > & track, TrackSeed * seed) private
Definition at line 356 of file TrackSeedTrackMapConverter.cc.
View newest version in sPHENIX GitHub at line 356 of file TrackSeedTrackMapConverter.cc
References TrackSeed::begin_cluster_keys(), TrackSeed::end_cluster_keys(), and SvtxTrack::insert_cluster_key().
Referenced by process_event().
void TrackSeedTrackMapConverter::addKeys (TrackSeed * seedToAddTo, TrackSeed * seedToAdd) private
Definition at line 346 of file TrackSeedTrackMapConverter.cc.
View newest version in sPHENIX GitHub at line 346 of file TrackSeedTrackMapConverter.cc
References TrackSeed::begin_cluster_keys(), TrackSeed::end_cluster_keys(), and TrackSeed::insert_cluster_key().
void TrackSeedTrackMapConverter::cosmics () inline
Definition at line 32 of file TrackSeedTrackMapConverter.h.
View newest version in sPHENIX GitHub at line 32 of file TrackSeedTrackMapConverter.h
References m_cosmics.
Referenced by convert_seeds().
int TrackSeedTrackMapConverter::End (PHCompositeNode *) override virtual
Called at the end of all processing.
Reimplemented from SubsysReco.
Definition at line 342 of file TrackSeedTrackMapConverter.cc.
View newest version in sPHENIX GitHub at line 342 of file TrackSeedTrackMapConverter.cc
References Fun4AllReturnCodes::EVENT_OK.
std::pair< int, float > TrackSeedTrackMapConverter::getCosmicCharge (TrackSeed * seed, float vertexradius) const private
Definition at line 449 of file TrackSeedTrackMapConverter.cc.
View newest version in sPHENIX GitHub at line 449 of file TrackSeedTrackMapConverter.cc
References TrackSeed::begin_cluster_keys(), charge(), INTTVtxZ::dphi, TrackSeed::end_cluster_keys(), TrkrClusterContainer::findCluster(), ActsGeometry::getGlobalPosition(), it, m_clusters, m_tGeometry, physmon_track_finding_ttbar::r, r1, r2, and square().
Referenced by process_event().
int TrackSeedTrackMapConverter::getNodes (PHCompositeNode * topNode) private
Definition at line 366 of file TrackSeedTrackMapConverter.cc.
View newest version in sPHENIX GitHub at line 366 of file TrackSeedTrackMapConverter.cc
References Fun4AllReturnCodes::ABORTEVENT, PHCompositeNode::addNode(), Fun4AllReturnCodes::EVENT_OK, PHNodeIterator::findFirst(), m_clusters, m_seedContainer, m_siContainer, m_tGeometry, m_tpcContainer, m_trackMap, m_trackMapName, m_trackSeedName, PHWHERE, and Fun4AllBase::Verbosity().
Referenced by InitRun().
int TrackSeedTrackMapConverter::InitRun (PHCompositeNode *) override virtual
Called for first event when run number is known. Typically this is where you may want to fetch data from database, because you know the run number.
Reimplemented from SubsysReco.
Definition at line 41 of file TrackSeedTrackMapConverter.cc.
View newest version in sPHENIX GitHub at line 41 of file TrackSeedTrackMapConverter.cc
References getNodes().
int TrackSeedTrackMapConverter::process_event (PHCompositeNode *) override virtual
Called for each event. This is where you do the real work.
Start with a fresh track map in case running iterative tracking
If the seed was removed, skip it
Catches entries in the vector removed by ghost finder
If we've run the track matching
Didn't find a match, so just use the tpc seed
Otherwise we are using an individual subdetectors container
Reimplemented from SubsysReco.
Definition at line 48 of file TrackSeedTrackMapConverter.cc.
View newest version in sPHENIX GitHub at line 48 of file TrackSeedTrackMapConverter.cc
References addKeys(), TrackSeedContainer::begin(), Acts::PhysicalConstants::c, charge(), TrackFitUtils::circle_circle_intersection(), TrackSeed::circleFitByTaubin(), dy, TrackSeedContainer::end(), Fun4AllReturnCodes::EVENT_OK, TrkrClusterContainer::findCluster(), TrackSeedContainer::get(), TrackSeed::get_eta(), TrackFitUtils::get_helix_tangent(), TrackSeed::get_p(), TrackSeed::get_phi(), TrackSeed::get_px(), TrackSeed::get_py(), TrackSeed::get_pz(), TrackSeed::get_qOverR(), TrackSeed::get_slope(), TrackSeed::get_theta(), TrackSeed::get_tpc_seed_index(), TrackSeed::get_x(), TrackSeed::get_X0(), TrackSeed::get_y(), TrackSeed::get_Y0(), TrackSeed::get_z(), TrackSeed::get_Z0(), TrkrCluster::getActsLocalError(), getCosmicCharge(), ActsGeometry::getGlobalPosition(), i, TrackSeedContainer::index(), SvtxTrackMap::insert(), Acts::PlanarHelper::intersect(), m_clusters, m_cosmics, m_fieldMap, m_seedContainer, m_siContainer, m_tGeometry, m_tpcContainer, m_trackMap, m_trackSeedName, merge_hashes::p, ActsTests::PropagationDatasets::phi, Acts::Test::pos, physmon_track_finding_ttbar::pt, Acts::IntegrationTest::R, physmon_track_finding_ttbar::r, PHObject::Reset(), seed, TrackSeedContainer::size(), Fun4AllBase::Verbosity(), ambiguity_solver_full_chain::x, X0, y, Y0, physmon_track_finding_ttbar::z, and Z0.
void TrackSeedTrackMapConverter::setFieldMap (const std::string & name) inline
Definition at line 29 of file TrackSeedTrackMapConverter.h.
View newest version in sPHENIX GitHub at line 29 of file TrackSeedTrackMapConverter.h
References m_fieldMap, and perf_headwind::name.
Referenced by convert_seeds().
void TrackSeedTrackMapConverter::setTrackMapName (const std::string & name) inline
Definition at line 30 of file TrackSeedTrackMapConverter.h.
View newest version in sPHENIX GitHub at line 30 of file TrackSeedTrackMapConverter.h
References m_trackMapName, and perf_headwind::name.
void TrackSeedTrackMapConverter::setTrackSeedName (const std::string & name) inline
Definition at line 31 of file TrackSeedTrackMapConverter.h.
View newest version in sPHENIX GitHub at line 31 of file TrackSeedTrackMapConverter.h
References m_trackSeedName, and perf_headwind::name.
Referenced by convert_seeds().
Member Data Documentation
TrkrClusterContainer* TrackSeedTrackMapConverter::m_clusters = nullptr private
Definition at line 50 of file TrackSeedTrackMapConverter.h.
View newest version in sPHENIX GitHub at line 50 of file TrackSeedTrackMapConverter.h
Referenced by getCosmicCharge(), getNodes(), and process_event().
bool TrackSeedTrackMapConverter::m_cosmics = false private
Definition at line 44 of file TrackSeedTrackMapConverter.h.
View newest version in sPHENIX GitHub at line 44 of file TrackSeedTrackMapConverter.h
Referenced by cosmics(), and process_event().
std::string TrackSeedTrackMapConverter::m_fieldMap = "" private
Definition at line 49 of file TrackSeedTrackMapConverter.h.
View newest version in sPHENIX GitHub at line 49 of file TrackSeedTrackMapConverter.h
Referenced by process_event(), and setFieldMap().
TrackSeedContainer* TrackSeedTrackMapConverter::m_seedContainer = nullptr private
Definition at line 46 of file TrackSeedTrackMapConverter.h.
View newest version in sPHENIX GitHub at line 46 of file TrackSeedTrackMapConverter.h
Referenced by getNodes(), and process_event().
TrackSeedContainer* TrackSeedTrackMapConverter::m_siContainer = nullptr private
Definition at line 48 of file TrackSeedTrackMapConverter.h.
View newest version in sPHENIX GitHub at line 48 of file TrackSeedTrackMapConverter.h
Referenced by getNodes(), and process_event().
ActsGeometry* TrackSeedTrackMapConverter::m_tGeometry = nullptr private
Definition at line 51 of file TrackSeedTrackMapConverter.h.
View newest version in sPHENIX GitHub at line 51 of file TrackSeedTrackMapConverter.h
Referenced by getCosmicCharge(), getNodes(), and process_event().
TrackSeedContainer* TrackSeedTrackMapConverter::m_tpcContainer = nullptr private
Definition at line 47 of file TrackSeedTrackMapConverter.h.
View newest version in sPHENIX GitHub at line 47 of file TrackSeedTrackMapConverter.h
Referenced by getNodes(), and process_event().
SvtxTrackMap* TrackSeedTrackMapConverter::m_trackMap = nullptr private
Definition at line 45 of file TrackSeedTrackMapConverter.h.
View newest version in sPHENIX GitHub at line 45 of file TrackSeedTrackMapConverter.h
Referenced by getNodes(), and process_event().
std::string TrackSeedTrackMapConverter::m_trackMapName = "SvtxTrackMap" private
Definition at line 41 of file TrackSeedTrackMapConverter.h.
View newest version in sPHENIX GitHub at line 41 of file TrackSeedTrackMapConverter.h
Referenced by getNodes(), and setTrackMapName().
std::string TrackSeedTrackMapConverter::m_trackSeedName = "TpcTrackSeedContainer" private
Definition at line 42 of file TrackSeedTrackMapConverter.h.
View newest version in sPHENIX GitHub at line 42 of file TrackSeedTrackMapConverter.h
Referenced by getNodes(), process_event(), and setTrackSeedName().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/TrackingDiagnostics/TrackSeedTrackMapConverter.h
coresoftware/blob/master/offline/packages/TrackingDiagnostics/TrackSeedTrackMapConverter.cc