Analysis Software: Acts::Svg::DetectorVolumeConverter Namespace Reference
Acts::Svg::DetectorVolumeConverter Namespace Reference
Classes
struct Options
A nested options class for the layer conversion.
Functions
std::tuple< ProtoVolume,
ProtoIndexedSurfaceGrid > convert (const GeometryContext &gctx, const Experimental::DetectorVolume &dVolume, const Options &volumeOptions)
Function Documentation
std::tuple< Acts::Svg::ProtoVolume, Acts::Svg::ProtoIndexedSurfaceGrid > Acts::Svg::DetectorVolumeConverter::convert (const GeometryContext & gctx, const Experimental::DetectorVolume & dVolume, const Options & volumeOptions)
Write/create the detector volume
Parameters
gctx the geometry context
dVolume the detector volumeto be displayed
volumeOptions the conversion objects
Returns
a vector of svg objects
Definition at line 21 of file DetectorVolumeSvgConverter.cpp.
View newest version in sPHENIX GitHub at line 21 of file DetectorVolumeSvgConverter.cpp
References Acts::Svg::DetectorConverter::convert(), Acts::VolumeBounds::eCylinder, Acts::GeometryHierarchyMap< value_t >::empty(), Acts::enumerate(), Acts::Experimental::DetectorVolume::geometryId(), add_histos_bX::ib, Acts::Experimental::DetectorVolume::name(), merge_hashes::p, Acts::Svg::DetectorVolumeConverter::Options::portalIndices, Acts::Svg::DetectorVolumeConverter::Options::portalOptions, Acts::Experimental::DetectorVolume::portals(), pSurface, physmon_simulation::s, Acts::Svg::SurfaceConverter::Options::style, Acts::Experimental::DetectorVolume::surfaceCandidatesUpdator(), Acts::Svg::DetectorVolumeConverter::Options::surfaceOptions, Acts::Experimental::DetectorVolume::surfaces(), Acts::Svg::IndexedSurfacesConverter::Options::surfaceStyles, to_string(), Acts::Experimental::DetectorVolume::transform(), Acts::VolumeBounds::type(), physmon_ckf_tracking::u, Acts::VolumeBounds::values(), and Acts::Experimental::DetectorVolume::volumeBounds().
Referenced by BOOST_AUTO_TEST_CASE().