Analysis Software: test_writer Namespace Reference
test_writer Namespace Reference
Functions
def test_obj_propagation_step_writer
def test_csv_particle_writer
def test_root_prop_step_writer
def test_root_particle_writer
def test_root_meas_writer
def test_root_simhits_writer
def test_root_clusters_writer
def test_csv_meas_writer
def test_csv_simhits_writer
def test_csv_clusters_writer
def test_root_writer_interface
def test_csv_writer_interface
def test_root_material_writer
def test_json_material_writer
def test_csv_multitrajectory_writer
def hepmc_data_impl
def hepmc_data
def test_hepmc3_histogram
def test_edm4hep_measurement_writer
def test_edm4hep_simhit_writer
def test_edm4hep_particle_writer
def test_edm4hep_multitrajectory_writer
def test_edm4hep_tracks_writer
Function Documentation
def test_writer.hepmc_data (hepmc_data_impl)
Definition at line 531 of file test_writer.py.
View newest version in sPHENIX GitHub at line 531 of file test_writer.py
def test_writer.hepmc_data_impl (tmp_path_factory)
Definition at line 502 of file test_writer.py.
View newest version in sPHENIX GitHub at line 502 of file test_writer.py
References str.
def test_writer.test_csv_clusters_writer (tmp_path, fatras, conf_const, trk_geo, rng)
Definition at line 301 of file test_writer.py.
View newest version in sPHENIX GitHub at line 301 of file test_writer.py
References conftest.conf_const(), and str.
def test_writer.test_csv_meas_writer (tmp_path, fatras, trk_geo, conf_const)
Definition at line 254 of file test_writer.py.
View newest version in sPHENIX GitHub at line 254 of file test_writer.py
References conftest.conf_const(), and str.
def test_writer.test_csv_multitrajectory_writer (tmp_path)
Definition at line 465 of file test_writer.py.
View newest version in sPHENIX GitHub at line 465 of file test_writer.py
References truth_tracking_kalman.runTruthTrackingKalman(), and str.
def test_writer.test_csv_particle_writer (tmp_path, conf_const, ptcl_gun)
Definition at line 82 of file test_writer.py.
View newest version in sPHENIX GitHub at line 82 of file test_writer.py
References conftest.conf_const(), conftest.ptcl_gun(), str, and test_root_prop_step_writer().
def test_writer.test_csv_simhits_writer (tmp_path, fatras, conf_const)
Definition at line 278 of file test_writer.py.
View newest version in sPHENIX GitHub at line 278 of file test_writer.py
References conftest.conf_const(), and str.
def test_writer.test_csv_writer_interface (writer, conf_const, tmp_path, trk_geo)
Definition at line 397 of file test_writer.py.
View newest version in sPHENIX GitHub at line 397 of file test_writer.py
References conftest.conf_const(), and str.
def test_writer.test_edm4hep_measurement_writer (tmp_path, fatras)
Definition at line 585 of file test_writer.py.
View newest version in sPHENIX GitHub at line 585 of file test_writer.py
References str.
def test_writer.test_edm4hep_multitrajectory_writer (tmp_path)
Definition at line 662 of file test_writer.py.
View newest version in sPHENIX GitHub at line 662 of file test_writer.py
References truth_tracking_kalman.runTruthTrackingKalman(), and str.
def test_writer.test_edm4hep_particle_writer (tmp_path, conf_const, ptcl_gun)
Definition at line 635 of file test_writer.py.
View newest version in sPHENIX GitHub at line 635 of file test_writer.py
References conftest.conf_const(), conftest.ptcl_gun(), and str.
def test_writer.test_edm4hep_simhit_writer (tmp_path, fatras, conf_const)
Definition at line 610 of file test_writer.py.
View newest version in sPHENIX GitHub at line 610 of file test_writer.py
References conftest.conf_const(), and str.
def test_writer.test_edm4hep_tracks_writer (tmp_path)
Definition at line 703 of file test_writer.py.
View newest version in sPHENIX GitHub at line 703 of file test_writer.py
References truth_tracking_kalman.runTruthTrackingKalman(), and str.
def test_writer.test_hepmc3_histogram (hepmc_data, tmp_path)
Definition at line 543 of file test_writer.py.
View newest version in sPHENIX GitHub at line 543 of file test_writer.py
References str.
def test_writer.test_json_material_writer (tmp_path, fmt)
Definition at line 444 of file test_writer.py.
View newest version in sPHENIX GitHub at line 444 of file test_writer.py
References common.getOpenDataDetectorDirectory(), and str.
def test_writer.test_obj_propagation_step_writer (tmp_path, trk_geo, conf_const, basic_prop_seq)
Definition at line 57 of file test_writer.py.
View newest version in sPHENIX GitHub at line 57 of file test_writer.py
References conftest.basic_prop_seq(), conftest.conf_const(), and str.
def test_writer.test_root_clusters_writer (tmp_path, fatras, conf_const, trk_geo, rng, assert_root_hash)
Definition at line 211 of file test_writer.py.
View newest version in sPHENIX GitHub at line 211 of file test_writer.py
References conftest.assert_root_hash(), conftest.conf_const(), and str.
Referenced by test_root_simhits_writer().
def test_writer.test_root_material_writer (tmp_path, assert_root_hash)
Definition at line 420 of file test_writer.py.
View newest version in sPHENIX GitHub at line 420 of file test_writer.py
References conftest.assert_root_hash(), common.getOpenDataDetectorDirectory(), and str.
def test_writer.test_root_meas_writer (tmp_path, fatras, trk_geo, assert_root_hash)
Definition at line 159 of file test_writer.py.
View newest version in sPHENIX GitHub at line 159 of file test_writer.py
References conftest.assert_root_hash(), and str.
def test_writer.test_root_particle_writer (tmp_path, conf_const, ptcl_gun, assert_root_hash)
Definition at line 134 of file test_writer.py.
View newest version in sPHENIX GitHub at line 134 of file test_writer.py
References conftest.assert_root_hash(), conftest.conf_const(), conftest.ptcl_gun(), and str.
def test_writer.test_root_prop_step_writer (tmp_path, trk_geo, conf_const, basic_prop_seq, assert_root_hash)
Definition at line 109 of file test_writer.py.
View newest version in sPHENIX GitHub at line 109 of file test_writer.py
References conftest.assert_root_hash(), conftest.basic_prop_seq(), conftest.conf_const(), and str.
Referenced by test_csv_particle_writer().
def test_writer.test_root_simhits_writer (tmp_path, fatras, conf_const, assert_root_hash)
Definition at line 185 of file test_writer.py.
View newest version in sPHENIX GitHub at line 185 of file test_writer.py
References conftest.assert_root_hash(), conftest.conf_const(), str, and test_root_clusters_writer().
def test_writer.test_root_writer_interface (writer, conf_const, tmp_path, trk_geo)
Definition at line 361 of file test_writer.py.
View newest version in sPHENIX GitHub at line 361 of file test_writer.py
References conftest.conf_const(), and str.