Analysis Software: PHG4CylinderGeomv2 Class Reference
PHG4CylinderGeomv2 Class Reference
#include <coresoftware/blob/master/simulation/g4simulation/g4detectors/PHG4CylinderGeomv2.h>
Public Member Functions
PHG4CylinderGeomv2 ()
PHG4CylinderGeomv2 (const double r, const double zmi, const double zma, const double thickn, const int n_scint)
~PHG4CylinderGeomv2 () override
void identify (std::ostream &os=std::cout) const override
void set_nscint (const int i) override
int get_nscint () const override
void ImportParameters (const PHParameters &param) override
load parameters from PHParameters, which interface to Database/XML/ROOT files
Public Member Functions inherited from PHG4CylinderGeomv1
PHG4CylinderGeomv1 ()
PHG4CylinderGeomv1 (const double r, const double zmi, const double zma, const double thickn)
~PHG4CylinderGeomv1 () override
int get_layer () const override
double get_radius () const override
double get_thickness () const override
double get_zmin () const override
double get_zmax () const override
void set_layer (const int i) override
void set_radius (const double r) override
void set_thickness (const double t) override
void set_zmin (const double z) override
void set_zmax (const double z) override
Public Member Functions inherited from PHG4CylinderGeom
~PHG4CylinderGeom () override
virtual double get_tiltangle () const
virtual double get_phi_slat_zero () const
virtual void set_tiltangle (const double)
virtual void set_phi_slat_zero (const double)
virtual void find_segment_center (const int, const int, double[])
virtual void find_strip_center (const int, const int, const int, const int, double[])
virtual void find_strip_index_values (const int, const double, const double, int &, int &)
virtual void find_strip_center_local_coords (const int, const int, const int, double[])
virtual double get_strip_y_spacing () const
virtual double get_strip_z_spacing () const
virtual double get_strip_tilt () const
virtual int get_N_strip_columns () const
virtual int get_N_strips_per_column () const
virtual int get_N_sensors_in_layer () const
virtual double get_pixel_z () const
virtual double get_pixel_x () const
virtual double get_pixel_thickness () const
Public Member Functions inherited from PHObject
PHObject ()
ctor
~PHObject () override
dtor
virtual PHObject * CloneMe () const
Virtual copy constructor.
virtual PHObject * clone () const final
PHObject * Clone (const char *newname="") const final
void Copy (TObject &object) const final
virtual void Reset ()
Clear Event.
virtual int isValid () const
isValid returns non zero if object contains vailid data
virtual int Integrate () const
virtual int Integrate (PHObject *)
virtual void CopyFrom (const PHObject *obj)
Protected Attributes
int nscint = -9999
Protected Attributes inherited from PHG4CylinderGeomv1
int layer = -1
double radius = NAN
double zmin = NAN
double zmax = NAN
double thickness = NAN
Additional Inherited Members
Protected Member Functions inherited from PHG4CylinderGeom
PHG4CylinderGeom ()
Detailed Description
Definition at line 12 of file PHG4CylinderGeomv2.h.
View newest version in sPHENIX GitHub at line 12 of file PHG4CylinderGeomv2.h
Constructor & Destructor Documentation
PHG4CylinderGeomv2::PHG4CylinderGeomv2 () inline
Definition at line 15 of file PHG4CylinderGeomv2.h.
View newest version in sPHENIX GitHub at line 15 of file PHG4CylinderGeomv2.h
PHG4CylinderGeomv2::PHG4CylinderGeomv2 (const double r, const double zmi, const double zma, const double thickn, const int n_scint) inline
Definition at line 16 of file PHG4CylinderGeomv2.h.
View newest version in sPHENIX GitHub at line 16 of file PHG4CylinderGeomv2.h
PHG4CylinderGeomv2::~PHG4CylinderGeomv2 () inline override
Definition at line 22 of file PHG4CylinderGeomv2.h.
View newest version in sPHENIX GitHub at line 22 of file PHG4CylinderGeomv2.h
Member Function Documentation
int PHG4CylinderGeomv2::get_nscint () const inline override virtual
Reimplemented from PHG4CylinderGeom.
Definition at line 28 of file PHG4CylinderGeomv2.h.
View newest version in sPHENIX GitHub at line 28 of file PHG4CylinderGeomv2.h
References nscint.
Referenced by PHG4SpacalPrototype4Detector::ConstructMe(), PHG4SpacalPrototypeDetector::ConstructMe(), and PHG4SpacalDetector::ConstructMe().
void PHG4CylinderGeomv2::identify (std::ostream & os = std::cout) const override virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from PHG4CylinderGeomv1.
Reimplemented in PHG4CylinderGeomv3.
Definition at line 5 of file PHG4CylinderGeomv2.cc.
View newest version in sPHENIX GitHub at line 5 of file PHG4CylinderGeomv2.cc
References PHG4CylinderGeomv1::layer, nscint, PHG4CylinderGeomv1::radius, PHG4CylinderGeomv1::thickness, PHG4CylinderGeomv1::zmax, and PHG4CylinderGeomv1::zmin.
void PHG4CylinderGeomv2::ImportParameters (const PHParameters & param) override virtual
load parameters from PHParameters, which interface to Database/XML/ROOT files
Reimplemented from PHG4CylinderGeomv1.
Definition at line 17 of file PHG4CylinderGeomv2.cc.
View newest version in sPHENIX GitHub at line 17 of file PHG4CylinderGeomv2.cc
References PHParameters::exist_int_param(), PHParameters::get_int_param(), PHG4CylinderGeomv1::ImportParameters(), and nscint.
Referenced by PHG4CylinderGeom_Spacalv1::ImportParameters().
void PHG4CylinderGeomv2::set_nscint (const int i) inline override virtual
Reimplemented from PHG4CylinderGeom.
Definition at line 27 of file PHG4CylinderGeomv2.h.
View newest version in sPHENIX GitHub at line 27 of file PHG4CylinderGeomv2.h
References i, and nscint.
Referenced by PHG4SpacalDetector::Construct_AzimuthalSeg(), PHG4SpacalPrototypeDetector::ConstructMe(), PHG4SpacalPrototype4Detector::ConstructMe(), and PHG4SpacalDetector::ConstructMe().
Member Data Documentation
int PHG4CylinderGeomv2::nscint = -9999 protected
Definition at line 34 of file PHG4CylinderGeomv2.h.
View newest version in sPHENIX GitHub at line 34 of file PHG4CylinderGeomv2.h
Referenced by get_nscint(), identify(), PHG4CylinderGeomv3::identify(), PHG4CylinderGeom_Spacalv2::identify(), PHG4CylinderGeom_Spacalv3::identify(), PHG4CylinderGeom_Spacalv1::identify(), ImportParameters(), set_nscint(), and PHG4CylinderGeom_Spacalv1::SetDefault().
The documentation for this class was generated from the following files:
coresoftware/blob/master/simulation/g4simulation/g4detectors/PHG4CylinderGeomv2.h
coresoftware/blob/master/simulation/g4simulation/g4detectors/PHG4CylinderGeomv2.cc