Analysis Software: PHG4InttHitReco Class Reference
PHG4InttHitReco Class Reference
#include <coresoftware/blob/master/simulation/g4simulation/g4intt/PHG4InttHitReco.h>
Public Member Functions
PHG4InttHitReco (const std::string &name="PHG4InttHitReco")
~PHG4InttHitReco () override
int InitRun (PHCompositeNode *topNode) override
module initialization
int process_event (PHCompositeNode *topNode) override
event processing
void SetDefaultParameters () override
set default parameter values
void Detector (const std::string &d)
void set_pixel_thresholdrat (double val)
void set_max_g4hitstep (float _)
void set_ClusHitsVerbose (bool set=true)
Public Member Functions inherited from SubsysReco
~SubsysReco () override
virtual int End (PHCompositeNode *)
Called at the end of all processing.
virtual int EndRun (const int)
Called at the end of each run.
virtual int Init (PHCompositeNode *)
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
void Print (const std::string &="ALL") const override
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Public Member Functions inherited from PHParameterInterface
PHParameterInterface (const std::string &name)
PHParameterInterface (const PHParameterInterface &)=delete
PHParameterInterface & operator= (PHParameterInterface const &)=delete
virtual ~PHParameterInterface ()
void set_paramname (const std::string &name)
void set_double_param (const std::string &name, const double dval)
double get_double_param (const std::string &name) const
void set_int_param (const std::string &name, const int ival)
int get_int_param (const std::string &name) const
void set_string_param (const std::string &name, const std::string &sval)
std::string get_string_param (const std::string &name) const
void UpdateParametersWithMacro ()
void SaveToNodeTree (PHCompositeNode *runNode, const std::string &nodename)
void PutOnParNode (PHCompositeNode *parNode, const std::string &nodename)
void Print () const
Public Attributes
ClusHitsVerbosev1 * mClusHitsVerbose { nullptr }
Protected Attributes
std::string m_Detector = "INTT"
std::string m_HitNodeName
std::string m_CellNodeName
std::string m_GeoNodeName
double m_Tmin
double m_Tmax
double m_crossingPeriod
gsl_vector * m_LocalOutVec = nullptr
gsl_vector * m_PathVec = nullptr
gsl_vector * m_SegmentVec = nullptr
Private Member Functions
void truthcheck_g4hit (PHG4Hit *, PHCompositeNode *topNode)
void addtruthhitset (TrkrDefs::hitsetkey, TrkrDefs::hitkey, float neffelectrons)
void cluster_truthhits (PHCompositeNode *topNode)
void end_event_truthcluster (PHCompositeNode *topNode)
Private Attributes
TrkrTruthTrackContainer * m_truthtracks { nullptr }
TrkrClusterContainer * m_truthclusters { nullptr }
PHG4TruthInfoContainer * m_truthinfo { nullptr }
int m_trkid { -1 }
bool m_is_emb { false }
TrkrTruthTrack * m_current_track { nullptr }
const int m_cluster_version { 4 }
TrkrHitSetContainer * m_truth_hits
std::map< TrkrDefs::hitsetkey,
unsigned int > m_hitsetkey_cnt {}
PHG4Hit * prior_g4hit { nullptr }
double m_pixel_thresholdrat { 0.01 }
float max_g4hitstep { 2.0 }
bool record_ClusHitsVerbose { false }
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = std::numeric_limits<int>::max() - 10
}
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Protected Member Functions inherited from PHParameterInterface
void set_default_double_param (const std::string &name, const double dval)
void set_default_int_param (const std::string &name, const int ival)
void set_default_string_param (const std::string &name, const std::string &sval)
void InitializeParameters ()
Detailed Description
Definition at line 27 of file PHG4InttHitReco.h.
View newest version in sPHENIX GitHub at line 27 of file PHG4InttHitReco.h
Constructor & Destructor Documentation
PHG4InttHitReco::PHG4InttHitReco (const std::string & name = "PHG4InttHitReco")
Definition at line 55 of file PHG4InttHitReco.cc.
View newest version in sPHENIX GitHub at line 55 of file PHG4InttHitReco.cc
PHG4InttHitReco::~PHG4InttHitReco () override
Definition at line 74 of file PHG4InttHitReco.cc.
View newest version in sPHENIX GitHub at line 74 of file PHG4InttHitReco.cc
References m_LocalOutVec, m_PathVec, m_SegmentVec, and m_truth_hits.
Member Function Documentation
void PHG4InttHitReco::addtruthhitset (TrkrDefs::hitsetkey hitsetkey, TrkrDefs::hitkey hitkey, float neffelectrons) private
Definition at line 586 of file PHG4InttHitReco.cc.
View newest version in sPHENIX GitHub at line 586 of file PHG4InttHitReco.cc
References TrkrHit::addEnergy(), TrkrHitSetContainer::findOrAddHitSet(), m_is_emb, and m_truth_hits.
Referenced by process_event().
void PHG4InttHitReco::cluster_truthhits (PHCompositeNode * topNode) private
Definition at line 606 of file PHG4InttHitReco.cc.
View newest version in sPHENIX GitHub at line 606 of file PHG4InttHitReco.cc
References TrkrTruthTrack::addCluster(), TrkrClusterContainer::addClusterSpecifyKey(), ClusHitsVerbosev1::addPhiCutHit(), ClusHitsVerbosev1::addPhiHit(), ClusHitsVerbosev1::addZCutHit(), ClusHitsVerbosev1::addZHit(), col, CylinderGeomIntt::find_strip_center_localcoords(), TrkrDefs::genClusKey(), InttDefs::getCol(), TrkrHitSet::getHits(), TrkrHitSet::getHitSetKey(), TrkrHitSetContainer::getHitSets(), InttDefs::getLadderZId(), TrkrDefs::getLayer(), PHG4CylinderGeomContainer::GetLayerGeom(), ClusHitsVerbosev1::getMap(), InttDefs::getRow(), TrkrHitSet::identify(), TrkrDefs::inttId, layer, m_cluster_version, m_current_track, m_hitsetkey_cnt, m_pixel_thresholdrat, m_truth_hits, m_truthclusters, mClusHitsVerbose, MATSCAN::phibins, prior_g4hit, ClusHitsVerbosev1::push_hits(), TrkrHitSetContainer::Reset(), and Fun4AllBase::Verbosity().
Referenced by end_event_truthcluster(), process_event(), and truthcheck_g4hit().
void PHG4InttHitReco::Detector (const std::string & d) inline
Definition at line 42 of file PHG4InttHitReco.h.
View newest version in sPHENIX GitHub at line 42 of file PHG4InttHitReco.h
References m_Detector.
void PHG4InttHitReco::end_event_truthcluster (PHCompositeNode * topNode) private
Definition at line 576 of file PHG4InttHitReco.cc.
View newest version in sPHENIX GitHub at line 576 of file PHG4InttHitReco.cc
References cluster_truthhits(), m_current_track, m_hitsetkey_cnt, m_is_emb, and m_trkid.
Referenced by process_event().
int PHG4InttHitReco::InitRun (PHCompositeNode * topNode) override virtual
module initialization
Reimplemented from SubsysReco.
Definition at line 82 of file PHG4InttHitReco.cc.
View newest version in sPHENIX GitHub at line 82 of file PHG4InttHitReco.cc
References PHCompositeNode::addNode(), assert, Fun4AllReturnCodes::EVENT_OK, PHNodeIterator::findFirst(), PHParameterInterface::get_double_param(), PHG4CylinderGeomContainer::identify(), m_crossingPeriod, m_Detector, m_GeoNodeName, m_HitNodeName, m_Tmax, m_Tmin, m_truthclusters, m_truthinfo, m_truthtracks, mClusHitsVerbose, Fun4AllBase::Name(), PHWHERE, PHParameterInterface::PutOnParNode(), record_ClusHitsVerbose, PHParameterInterface::SaveToNodeTree(), PHParameterInterface::UpdateParametersWithMacro(), and Fun4AllBase::Verbosity().
int PHG4InttHitReco::process_event (PHCompositeNode * topNode) override virtual
event processing
Reimplemented from SubsysReco.
Definition at line 234 of file PHG4InttHitReco.cc.
View newest version in sPHENIX GitHub at line 234 of file PHG4InttHitReco.cc
References TrkrHit::addEnergy(), addtruthhitset(), PHG4Utils::circle_rectangle_intersection(), cluster_truthhits(), double(), end_event_truthcluster(), Fun4AllReturnCodes::EVENT_OK, CylinderGeomIntt::find_strip_center_localcoords(), CylinderGeomIntt::find_strip_index_values(), InttDefs::genHitKey(), InttDefs::genHitSetKey(), CylinderGeomIntt::get_strip_y_spacing(), CylinderGeomIntt::get_strip_z_spacing(), TrkrHit::getEnergy(), PHG4HitContainer::getHits(), PHG4CylinderGeomContainer::GetLayerGeom(), i, centProxy::interval, m_crossingPeriod, m_GeoNodeName, m_HitNodeName, m_is_emb, m_LocalOutVec, m_PathVec, m_SegmentVec, m_Tmax, m_Tmin, prior_g4hit, PHG4Hit::prop_eion, round(), swap(), Acts::Test::time, truthcheck_g4hit(), and Fun4AllBase::Verbosity().
void PHG4InttHitReco::set_ClusHitsVerbose (bool set = true) inline
Definition at line 84 of file PHG4InttHitReco.h.
View newest version in sPHENIX GitHub at line 84 of file PHG4InttHitReco.h
References record_ClusHitsVerbose.
void PHG4InttHitReco::set_max_g4hitstep (float _) inline
Definition at line 82 of file PHG4InttHitReco.h.
View newest version in sPHENIX GitHub at line 82 of file PHG4InttHitReco.h
References _, and max_g4hitstep.
void PHG4InttHitReco::set_pixel_thresholdrat (double val) inline
Definition at line 81 of file PHG4InttHitReco.h.
View newest version in sPHENIX GitHub at line 81 of file PHG4InttHitReco.h
References m_pixel_thresholdrat.
void PHG4InttHitReco::SetDefaultParameters () override virtual
set default parameter values
Implements PHParameterInterface.
Definition at line 526 of file PHG4InttHitReco.cc.
View newest version in sPHENIX GitHub at line 526 of file PHG4InttHitReco.cc
References PHParameterInterface::set_default_double_param().
void PHG4InttHitReco::truthcheck_g4hit (PHG4Hit * g4hit, PHCompositeNode * topNode) private
Definition at line 538 of file PHG4InttHitReco.cc.
View newest version in sPHENIX GitHub at line 538 of file PHG4InttHitReco.cc
References cluster_truthhits(), PHG4Hit::get_trkid(), PHG4Hit::get_x(), PHG4Hit::get_y(), TrkrTruthTrackContainer::getTruthTrack(), PHG4TruthInfoContainer::isEmbeded(), m_current_track, m_is_emb, m_trkid, m_truthinfo, m_truthtracks, max_g4hitstep, PHWHERE, prior_g4hit, and Fun4AllBase::Verbosity().
Referenced by process_event().
Member Data Documentation
std::string PHG4InttHitReco::m_CellNodeName protected
Definition at line 47 of file PHG4InttHitReco.h.
View newest version in sPHENIX GitHub at line 47 of file PHG4InttHitReco.h
const int PHG4InttHitReco::m_cluster_version { 4 } private
Definition at line 66 of file PHG4InttHitReco.h.
View newest version in sPHENIX GitHub at line 66 of file PHG4InttHitReco.h
Referenced by cluster_truthhits().
double PHG4InttHitReco::m_crossingPeriod protected
Definition at line 52 of file PHG4InttHitReco.h.
View newest version in sPHENIX GitHub at line 52 of file PHG4InttHitReco.h
Referenced by InitRun(), and process_event().
TrkrTruthTrack* PHG4InttHitReco::m_current_track { nullptr } private
Definition at line 65 of file PHG4InttHitReco.h.
View newest version in sPHENIX GitHub at line 65 of file PHG4InttHitReco.h
Referenced by cluster_truthhits(), end_event_truthcluster(), and truthcheck_g4hit().
std::string PHG4InttHitReco::m_Detector = "INTT" protected
Definition at line 45 of file PHG4InttHitReco.h.
View newest version in sPHENIX GitHub at line 45 of file PHG4InttHitReco.h
Referenced by Detector(), and InitRun().
std::string PHG4InttHitReco::m_GeoNodeName protected
Definition at line 48 of file PHG4InttHitReco.h.
View newest version in sPHENIX GitHub at line 48 of file PHG4InttHitReco.h
Referenced by InitRun(), and process_event().
std::string PHG4InttHitReco::m_HitNodeName protected
Definition at line 46 of file PHG4InttHitReco.h.
View newest version in sPHENIX GitHub at line 46 of file PHG4InttHitReco.h
Referenced by InitRun(), and process_event().
std::map<TrkrDefs::hitsetkey,unsigned int> PHG4InttHitReco::m_hitsetkey_cnt {} private
Definition at line 68 of file PHG4InttHitReco.h.
View newest version in sPHENIX GitHub at line 68 of file PHG4InttHitReco.h
Referenced by cluster_truthhits(), and end_event_truthcluster().
bool PHG4InttHitReco::m_is_emb { false } private
Definition at line 64 of file PHG4InttHitReco.h.
View newest version in sPHENIX GitHub at line 64 of file PHG4InttHitReco.h
Referenced by addtruthhitset(), end_event_truthcluster(), process_event(), and truthcheck_g4hit().
gsl_vector* PHG4InttHitReco::m_LocalOutVec = nullptr protected
Definition at line 54 of file PHG4InttHitReco.h.
View newest version in sPHENIX GitHub at line 54 of file PHG4InttHitReco.h
Referenced by process_event(), and ~PHG4InttHitReco().
gsl_vector* PHG4InttHitReco::m_PathVec = nullptr protected
Definition at line 55 of file PHG4InttHitReco.h.
View newest version in sPHENIX GitHub at line 55 of file PHG4InttHitReco.h
Referenced by process_event(), and ~PHG4InttHitReco().
double PHG4InttHitReco::m_pixel_thresholdrat { 0.01 } private
Definition at line 76 of file PHG4InttHitReco.h.
View newest version in sPHENIX GitHub at line 76 of file PHG4InttHitReco.h
Referenced by cluster_truthhits(), and set_pixel_thresholdrat().
gsl_vector* PHG4InttHitReco::m_SegmentVec = nullptr protected
Definition at line 56 of file PHG4InttHitReco.h.
View newest version in sPHENIX GitHub at line 56 of file PHG4InttHitReco.h
Referenced by process_event(), and ~PHG4InttHitReco().
double PHG4InttHitReco::m_Tmax protected
Definition at line 51 of file PHG4InttHitReco.h.
View newest version in sPHENIX GitHub at line 51 of file PHG4InttHitReco.h
Referenced by InitRun(), and process_event().
double PHG4InttHitReco::m_Tmin protected
Definition at line 50 of file PHG4InttHitReco.h.
View newest version in sPHENIX GitHub at line 50 of file PHG4InttHitReco.h
Referenced by InitRun(), and process_event().
int PHG4InttHitReco::m_trkid { -1 } private
Definition at line 63 of file PHG4InttHitReco.h.
View newest version in sPHENIX GitHub at line 63 of file PHG4InttHitReco.h
Referenced by end_event_truthcluster(), and truthcheck_g4hit().
TrkrHitSetContainer* PHG4InttHitReco::m_truth_hits private
Definition at line 67 of file PHG4InttHitReco.h.
View newest version in sPHENIX GitHub at line 67 of file PHG4InttHitReco.h
Referenced by addtruthhitset(), cluster_truthhits(), and ~PHG4InttHitReco().
TrkrClusterContainer* PHG4InttHitReco::m_truthclusters { nullptr } private
Definition at line 61 of file PHG4InttHitReco.h.
View newest version in sPHENIX GitHub at line 61 of file PHG4InttHitReco.h
Referenced by cluster_truthhits(), and InitRun().
PHG4TruthInfoContainer* PHG4InttHitReco::m_truthinfo { nullptr } private
Definition at line 62 of file PHG4InttHitReco.h.
View newest version in sPHENIX GitHub at line 62 of file PHG4InttHitReco.h
Referenced by InitRun(), and truthcheck_g4hit().
TrkrTruthTrackContainer* PHG4InttHitReco::m_truthtracks { nullptr } private
Definition at line 60 of file PHG4InttHitReco.h.
View newest version in sPHENIX GitHub at line 60 of file PHG4InttHitReco.h
Referenced by InitRun(), and truthcheck_g4hit().
float PHG4InttHitReco::max_g4hitstep { 2.0 } private
Definition at line 77 of file PHG4InttHitReco.h.
View newest version in sPHENIX GitHub at line 77 of file PHG4InttHitReco.h
Referenced by set_max_g4hitstep(), and truthcheck_g4hit().
ClusHitsVerbosev1* PHG4InttHitReco::mClusHitsVerbose { nullptr }
Definition at line 85 of file PHG4InttHitReco.h.
View newest version in sPHENIX GitHub at line 85 of file PHG4InttHitReco.h
Referenced by cluster_truthhits(), and InitRun().
PHG4Hit* PHG4InttHitReco::prior_g4hit { nullptr } private
Definition at line 70 of file PHG4InttHitReco.h.
View newest version in sPHENIX GitHub at line 70 of file PHG4InttHitReco.h
Referenced by cluster_truthhits(), process_event(), and truthcheck_g4hit().
bool PHG4InttHitReco::record_ClusHitsVerbose { false } private
Definition at line 78 of file PHG4InttHitReco.h.
View newest version in sPHENIX GitHub at line 78 of file PHG4InttHitReco.h
Referenced by InitRun(), and set_ClusHitsVerbose().
The documentation for this class was generated from the following files:
coresoftware/blob/master/simulation/g4simulation/g4intt/PHG4InttHitReco.h
coresoftware/blob/master/simulation/g4simulation/g4intt/PHG4InttHitReco.cc