Analysis Software: MicromegasRawDataCalibration Class Reference
MicromegasRawDataCalibration Class Reference
micromegas raw data decoder
#include <coresoftware/blob/master/offline/packages/micromegas/MicromegasRawDataCalibration.h>
Public Member Functions
MicromegasRawDataCalibration (const std::string &name="MicromegasRawDataCalibration")
constructor
int Init (PHCompositeNode *) override
global initialization
int InitRun (PHCompositeNode *) override
run initialization
int process_event (PHCompositeNode *) override
event processing
int End (PHCompositeNode *) override
end of processing
void set_sample_min (int value)
set min sample for noise estimation
void set_sample_max (int value)
set min sample for noise estimation
void set_calibration_file (const std::string &value)
set to true to store evaluation histograms and ntuples
Public Member Functions inherited from SubsysReco
~SubsysReco () override
virtual int EndRun (const int)
Called at the end of each run.
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
void Print (const std::string &="ALL") const override
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Private Types
using profile_map_t = std::map< int, TProfile * >
map fee id to Profile histogram
Private Attributes
int m_sample_min = 0
min sample for noise estimation
int m_sample_max = 100
max sample for noise estimation
std::string m_calibration_filename = "TPOT_Pedestal_000.root"
calibration output file
profile_map_t m_profile_map
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = std::numeric_limits<int>::max() - 10
}
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Detailed Description
micromegas raw data decoder
Definition at line 21 of file MicromegasRawDataCalibration.h.
View newest version in sPHENIX GitHub at line 21 of file MicromegasRawDataCalibration.h
Member Typedef Documentation
using MicromegasRawDataCalibration::profile_map_t = std::map<int, TProfile*> private
map fee id to Profile histogram
Definition at line 61 of file MicromegasRawDataCalibration.h.
View newest version in sPHENIX GitHub at line 61 of file MicromegasRawDataCalibration.h
Constructor & Destructor Documentation
MicromegasRawDataCalibration::MicromegasRawDataCalibration (const std::string & name = "MicromegasRawDataCalibration")
constructor
Definition at line 27 of file MicromegasRawDataCalibration.cc.
View newest version in sPHENIX GitHub at line 27 of file MicromegasRawDataCalibration.cc
Member Function Documentation
int MicromegasRawDataCalibration::End (PHCompositeNode *) override virtual
end of processing
Reimplemented from SubsysReco.
Definition at line 110 of file MicromegasRawDataCalibration.cc.
View newest version in sPHENIX GitHub at line 110 of file MicromegasRawDataCalibration.cc
References Fun4AllReturnCodes::EVENT_OK, i, m_calibration_filename, m_profile_map, pedestal(), profile(), rms(), MicromegasCalibrationData::set_pedestal(), MicromegasCalibrationData::set_rms(), and MicromegasCalibrationData::write().
int MicromegasRawDataCalibration::Init (PHCompositeNode *) override virtual
global initialization
Reimplemented from SubsysReco.
Definition at line 32 of file MicromegasRawDataCalibration.cc.
View newest version in sPHENIX GitHub at line 32 of file MicromegasRawDataCalibration.cc
References Fun4AllReturnCodes::EVENT_OK.
int MicromegasRawDataCalibration::InitRun (PHCompositeNode *) override virtual
run initialization
Reimplemented from SubsysReco.
Definition at line 39 of file MicromegasRawDataCalibration.cc.
View newest version in sPHENIX GitHub at line 39 of file MicromegasRawDataCalibration.cc
References Fun4AllReturnCodes::EVENT_OK.
int MicromegasRawDataCalibration::process_event (PHCompositeNode * topNode) override virtual
event processing
Reimplemented from SubsysReco.
Definition at line 43 of file MicromegasRawDataCalibration.cc.
View newest version in sPHENIX GitHub at line 43 of file MicromegasRawDataCalibration.cc
References assert, channel(), Fun4AllReturnCodes::DISCARDEVENT, event, Fun4AllReturnCodes::EVENT_OK, i, MicromegasDefs::m_nchannels_fee, MicromegasDefs::m_packet_ids, m_profile_map, m_sample_max, m_sample_min, Acts::UnitConstants::min, profile(), and Fun4AllBase::Verbosity().
void MicromegasRawDataCalibration::set_calibration_file (const std::string & value) inline
set to true to store evaluation histograms and ntuples
Definition at line 47 of file MicromegasRawDataCalibration.h.
View newest version in sPHENIX GitHub at line 47 of file MicromegasRawDataCalibration.h
References m_calibration_filename, and value.
void MicromegasRawDataCalibration::set_sample_max (int value) inline
set min sample for noise estimation
Definition at line 44 of file MicromegasRawDataCalibration.h.
View newest version in sPHENIX GitHub at line 44 of file MicromegasRawDataCalibration.h
References m_sample_max, and value.
void MicromegasRawDataCalibration::set_sample_min (int value) inline
set min sample for noise estimation
Definition at line 41 of file MicromegasRawDataCalibration.h.
View newest version in sPHENIX GitHub at line 41 of file MicromegasRawDataCalibration.h
References m_sample_min, and value.
Member Data Documentation
std::string MicromegasRawDataCalibration::m_calibration_filename = "TPOT_Pedestal_000.root" private
calibration output file
Definition at line 58 of file MicromegasRawDataCalibration.h.
View newest version in sPHENIX GitHub at line 58 of file MicromegasRawDataCalibration.h
Referenced by End(), and set_calibration_file().
profile_map_t MicromegasRawDataCalibration::m_profile_map private
Definition at line 62 of file MicromegasRawDataCalibration.h.
View newest version in sPHENIX GitHub at line 62 of file MicromegasRawDataCalibration.h
Referenced by End(), and process_event().
int MicromegasRawDataCalibration::m_sample_max = 100 private
max sample for noise estimation
Definition at line 55 of file MicromegasRawDataCalibration.h.
View newest version in sPHENIX GitHub at line 55 of file MicromegasRawDataCalibration.h
Referenced by process_event(), and set_sample_max().
int MicromegasRawDataCalibration::m_sample_min = 0 private
min sample for noise estimation
Definition at line 52 of file MicromegasRawDataCalibration.h.
View newest version in sPHENIX GitHub at line 52 of file MicromegasRawDataCalibration.h
Referenced by process_event(), and set_sample_min().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/micromegas/MicromegasRawDataCalibration.h
coresoftware/blob/master/offline/packages/micromegas/MicromegasRawDataCalibration.cc