Analysis Software: ActsExamples::Generic Namespace Reference
ActsExamples::Generic Namespace Reference
Classes
class GenericDetectorElement
class LayerBuilderT
struct ProtoLayerSurfaces
class ProtoLayerCreatorT
Typedefs
using SurfacePosition = std::pair< const Acts::Surface *, Acts::Vector3 >
Functions
std::vector< Acts::Vector3 > modulePositionsCylinder (double radius, double zStagger, double moduleHalfLength, double lOverlap, const std::pair< int, int > &binningSchema)
helper method for cylinder
std::vector< Acts::Vector3 > modulePositionsRing (double z, double radius, double phiStagger, double phiSubStagger, int nPhiBins)
Helper method for positioning.
std::vector< std::vector
< Acts::Vector3 > > modulePositionsDisc (double z, double ringStagger, std::vector< double > phiStagger, std::vector< double > phiSubStagger, double innerRadius, double outerRadius, const std::vector< size_t > &discBinning, const std::vector< double > &moduleHalfLength)
helper method for disc
template<typename detector_element_t >
std::unique_ptr< const
Acts::TrackingGeometry > buildDetector (const typename detector_element_t::ContextType &gctxIn, std::vector< std::vector< std::shared_ptr< detector_element_t >>> &detectorStore, size_t level, std::shared_ptr< const Acts::IMaterialDecorator > matDecorator=nullptr, bool protoMaterial=false, Acts::Logging::Level surfaceLLevel=Acts::Logging::INFO, Acts::Logging::Level layerLLevel=Acts::Logging::INFO, Acts::Logging::Level volumeLLevel=Acts::Logging::INFO)
Typedef Documentation
typedef std::pair< const Acts::Surface *, Acts::Vector3 > ActsExamples::Generic::SurfacePosition
Definition at line 36 of file LayerBuilderT.hpp.
View newest version in sPHENIX GitHub at line 36 of file LayerBuilderT.hpp
Function Documentation
template<typename detector_element_t > std::unique_ptr<const Acts::TrackingGeometry> ActsExamples::Generic::buildDetector (const typename detector_element_t::ContextType & gctxIn, std::vector< std::vector< std::shared_ptr< detector_element_t >>> & detectorStore, size_t level, std::shared_ptr< const Acts::IMaterialDecorator > matDecorator = nullptr, bool protoMaterial = false, Acts::Logging::Level surfaceLLevel = Acts::Logging::INFO, Acts::Logging::Level layerLLevel = Acts::Logging::INFO, Acts::Logging::Level volumeLLevel = Acts::Logging::INFO)
Global method to build the generic tracking geometry
Template Parameters
detector_element_t is the actual type of the detector element, each derivative of a GenericDetectorElement can be used
Parameters
gctx is the detector element dependent geometry context
detectorStore is the store for the detector element
matDecorator is an optional decorator for the material
level is the detector building level 0 - pixel barrel only 1 - pixel detector only 2 - full barrel only 3 - full detector (without stereo modules)
matDecorator is the source for material decoration
protoMaterial is a flag to steer proto material to be loaded
surfaceLLevel is the surface building logging level
layerLLevel is the layer building logging level
volumeLLevel is the volume building logging level return a unique vector to the tracking geometry
The ProtoLayer creator
return the tracking geometry
Definition at line 112 of file BuildGenericDetector.hpp.
View newest version in sPHENIX GitHub at line 112 of file BuildGenericDetector.hpp
References Acts::binPhi, Acts::binR, Acts::binX, Acts::binZ, Acts::closed, filter::Config, Acts::Material::fromMassDensity(), gctx, Acts::getDefaultLogger(), train_ambiguity_solver::id, Acts::CylinderVolumeHelper::Config::layerArrayCreator, Acts::PassiveLayerBuilder::Config::layerIdentification, Acts::UnitConstants::mm, modulePositionsCylinder(), modulePositionsDisc(), Acts::open, Acts::LayerCreator::Config::surfaceArrayCreator, and Acts::CylinderVolumeBuilder::Config::trackingVolumeHelper.
std::vector< Acts::Vector3 > ActsExamples::Generic::modulePositionsCylinder (double radius, double zStagger, double moduleHalfLength, double lOverlap, const std::pair< int, int > & binningSchema)
helper method for cylinder
Helper method for positioning
Parameters
radius is the cylinder radius
zStagger is the radial staggering along z
moduleHalfLength is the module length (longitudinal)
lOverlap is the overlap of the modules (longitudinal) is the way the bins are laid out rphi x z
Definition at line 18 of file BuildGenericDetector.cpp.
View newest version in sPHENIX GitHub at line 18 of file BuildGenericDetector.cpp
References Acts::Test::minPhi, and physmon_ckf_tracking::u.
Referenced by buildDetector().
std::vector< std::vector< Acts::Vector3 > > ActsExamples::Generic::modulePositionsDisc (double z, double ringStagger, std::vector< double > phiStagger, std::vector< double > phiSubStagger, double innerRadius, double outerRadius, const std::vector< size_t > & discBinning, const std::vector< double > & moduleHalfLength)
helper method for disc
Helper method for positioning
Parameters
z is the nominal z posiiton of the dis
ringStagger is the staggering of the different rings
phiStagger is the staggering on a ring in phi : it is even/odd
phiSubStagger is the sub staggering on a ring in phi : it affects 0/4/8 and 3/6
innerRadius is the inner Radius for the disc
outerRadius is the outer Radius for the disc
discBinning is the binning setup in r, phi
moduleHalfLength is pair of phibins and module length
Definition at line 48 of file BuildGenericDetector.cpp.
View newest version in sPHENIX GitHub at line 48 of file BuildGenericDetector.cpp
References physmon_track_finding_ttbar::deltaR, modulePositionsRing(), and physmon_ckf_tracking::u.
Referenced by buildDetector().
std::vector< Acts::Vector3 > ActsExamples::Generic::modulePositionsRing (double z, double radius, double phiStagger, double phiSubStagger, int nPhiBins)
Helper method for positioning.
Helper method for positioning
Parameters
z is the z position of the ring
radius is the ring radius
phiStagger is the radial staggering along phi
lOverlap is the overlap of the modules
nPhiBins is the number of bins in phi
Definition at line 105 of file BuildGenericDetector.cpp.
View newest version in sPHENIX GitHub at line 105 of file BuildGenericDetector.cpp
References Acts::Test::minPhi, ActsTests::PropagationDatasets::phi, and physmon_ckf_tracking::u.
Referenced by modulePositionsDisc().