Analysis Software: JETSCAPE/blob/main/external_packages/fjcore.cc File Reference
fjcore.cc File Reference
#include "fjcore.hh"
#include <string>
#include <vector>
#include <iostream>
#include <sstream>
#include <cassert>
#include <cstddef>
#include <memory>
#include <limits>
#include <stack>
#include <iomanip>
#include <algorithm>
#include <fstream>
#include <cmath>
#include <cstdlib>
#include <set>
#include <valarray>
#include <cstdarg>
Classes
class EtaPhi
class DnnError
class DynamicNearestNeighbours
class SearchTree< T >
class SearchTree< T >::Node
class SearchTree< T >::circulator
class SearchTree< T >::const_circulator
class MinHeap
struct MinHeap::ValueLoc
class Coord2D
class ClosestPair2DBase
class ClosestPair2D
class ClosestPair2D::triplet< T >
class ClosestPair2D::Shuffle
class ClosestPair2D::Point
class TiledJet
class Tile
class LazyTiling9Alt
class Tile2Base< NN >
class LazyTiling9
class LazyTiling25
class TilingExtent
class Private::MirrorInfo
class SW_Identity
class SW_Not
class SW_BinaryOperator
class SW_And
class SW_Or
class SW_Mult
class QuantityBase
class QuantitySquareBase
class SW_QuantityMin< QuantityType >
class SW_QuantityMax< QuantityType >
class SW_QuantityRange< QuantityType >
class QuantityPt2
class QuantityEt2
class QuantityE
class QuantityM2
class QuantityRap
class SW_RapMin
class SW_RapMax
class SW_RapRange
class QuantityAbsRap
class SW_AbsRapMax
class SW_AbsRapRange
class QuantityEta
class QuantityAbsEta
class SW_PhiRange
class SW_RapPhiRange
class SW_NHardest
class SW_WithReference
class SW_Circle
class SW_Doughnut
class SW_Strip
class SW_Rectangle
class SW_PtFractionMin
class SW_IsZero
Namespaces
namespace Private
Macros
#define __FJCORE_VERSION_HH__
#define __FJCORE_CLUSTERQUENCE_N2_ICC__
#define __FJCORE_DYNAMICNEARESTNEIGHBOURS_HH__
#define __FJCORE_SEARCHTREE_HH__
#define __FJCORE_MINHEAP__HH__
#define __FJCORE_CLOSESTPAIR2DBASE__HH__
#define __FJCORE_CLOSESTPAIR2D__HH__
#define __FJCORE_LAZYTILING9ALT_HH__
#define __FJCORE_LAZYTILING9_HH__
#define __FJCORE_LAZYTILING25_HH__
#define __FJCORE_TILINGEXTENT_HH__
#define _FJCORE_TILING25_USE_TILING_ANALYSIS_
#define FJCORE_LAZY25_MIN3TILESY
#define _FJCORE_TILING2_USE_TILING_ANALYSIS_
#define FJCORE_LAZY9_MIN2TILESY
Typedefs
typedef Tile2Base< 9 > Tile2
Functions
bool floor_ln2_less (unsigned x, unsigned y)
string fastjet_version_string ()
bool Private::make_mirror (Coord2D &point, double Dlim)
PseudoJet join (const vector< PseudoJet > &pieces, const JetDefinition::Recombiner &recombiner)
PseudoJet join (const PseudoJet &j1, const JetDefinition::Recombiner &recombiner)
PseudoJet join (const PseudoJet &j1, const PseudoJet &j2, const JetDefinition::Recombiner &recombiner)
PseudoJet join (const PseudoJet &j1, const PseudoJet &j2, const PseudoJet &j3, const JetDefinition::Recombiner &recombiner)
PseudoJet join (const PseudoJet &j1, const PseudoJet &j2, const PseudoJet &j3, const PseudoJet &j4, const JetDefinition::Recombiner &recombiner)
PseudoJet operator+ (const PseudoJet &jet1, const PseudoJet &jet2)
PseudoJet operator- (const PseudoJet &jet1, const PseudoJet &jet2)
PseudoJet operator* (double coeff, const PseudoJet &jet)
PseudoJet operator* (const PseudoJet &jet, double coeff)
PseudoJet operator/ (const PseudoJet &jet, double coeff)
bool operator== (const PseudoJet &a, const PseudoJet &b)
bool operator== (const PseudoJet &jet, const double val)
bool have_same_momentum (const PseudoJet &jeta, const PseudoJet &jetb)
PseudoJet PtYPhiM (double pt, double y, double phi, double m)
void sort_indices (vector< int > &indices, const vector< double > &values)
vector< PseudoJet > sorted_by_pt (const vector< PseudoJet > &jets)
vector< PseudoJet > sorted_by_rapidity (const vector< PseudoJet > &jets)
vector< PseudoJet > sorted_by_E (const vector< PseudoJet > &jets)
vector< PseudoJet > sorted_by_pz (const vector< PseudoJet > &jets)
PseudoJet join (const vector< PseudoJet > &pieces)
PseudoJet join (const PseudoJet &j1)
PseudoJet join (const PseudoJet &j1, const PseudoJet &j2)
PseudoJet join (const PseudoJet &j1, const PseudoJet &j2, const PseudoJet &j3)
PseudoJet join (const PseudoJet &j1, const PseudoJet &j2, const PseudoJet &j3, const PseudoJet &j4)
Selector SelectorIdentity ()
Selector operator! (const Selector &s)
Selector operator&& (const Selector &s1, const Selector &s2)
Selector operator|| (const Selector &s1, const Selector &s2)
Selector operator* (const Selector &s1, const Selector &s2)
Selector SelectorPtMin (double ptmin)
select objects with pt >= ptmin
Selector SelectorPtMax (double ptmax)
select objects with pt <= ptmax
Selector SelectorPtRange (double ptmin, double ptmax)
select objects with ptmin <= pt <= ptmax
Selector SelectorEtMin (double Etmin)
select objects with Et >= Etmin
Selector SelectorEtMax (double Etmax)
select objects with Et <= Etmax
Selector SelectorEtRange (double Etmin, double Etmax)
select objects with Etmin <= Et <= Etmax
Selector SelectorEMin (double Emin)
select objects with E >= Emin
Selector SelectorEMax (double Emax)
select objects with E <= Emax
Selector SelectorERange (double Emin, double Emax)
select objects with Emin <= E <= Emax
Selector SelectorMassMin (double mmin)
select objects with Mass >= Mmin
Selector SelectorMassMax (double mmax)
select objects with Mass <= Mmax
Selector SelectorMassRange (double mmin, double mmax)
select objects with Mmin <= Mass <= Mmax
Selector SelectorRapMin (double rapmin)
select objects with rap >= rapmin
Selector SelectorRapMax (double rapmax)
select objects with rap <= rapmax
Selector SelectorRapRange (double rapmin, double rapmax)
select objects with rapmin <= rap <= rapmax
Selector SelectorAbsRapMin (double absrapmin)
select objects with |rap| >= absrapmin
Selector SelectorAbsRapMax (double absrapmax)
select objects with |rap| <= absrapmax
Selector SelectorAbsRapRange (double rapmin, double rapmax)
select objects with absrapmin <= |rap| <= absrapmax
Selector SelectorEtaMin (double etamin)
select objects with eta >= etamin
Selector SelectorEtaMax (double etamax)
select objects with eta <= etamax
Selector SelectorEtaRange (double etamin, double etamax)
select objects with etamin <= eta <= etamax
Selector SelectorAbsEtaMin (double absetamin)
select objects with |eta| >= absetamin
Selector SelectorAbsEtaMax (double absetamax)
select objects with |eta| <= absetamax
Selector SelectorAbsEtaRange (double absetamin, double absetamax)
select objects with absetamin <= |eta| <= absetamax
Selector SelectorPhiRange (double phimin, double phimax)
select objects with phimin <= phi <= phimax
Selector SelectorRapPhiRange (double rapmin, double rapmax, double phimin, double phimax)
Selector SelectorNHardest (unsigned int n)
Selector SelectorCircle (const double radius)
Selector SelectorDoughnut (const double radius_in, const double radius_out)
Selector SelectorStrip (const double half_width)
Selector SelectorRectangle (const double half_rap_width, const double half_phi_width)
Selector SelectorPtFractionMin (double fraction)
Selector SelectorIsZero ()
ostream & operator<< (ostream &ostr, const TiledJet &jet)
Variables
FJCORE_BEGIN_NAMESPACE typedef
Tile2Base< 25 > Tile25
FJCORE_BEGIN_NAMESPACE const char * fastjet_version = FJCORE_PACKAGE_VERSION
FJCORE_BEGIN_NAMESPACE const double tile_edge_security_margin =1.0e-7
const int n_tile_neighbours = 9
FJCORE_END_NAMESPACE
FJCORE_BEGIN_NAMESPACE const
unsigned int twopow31 = 2147483648U
Macro Definition Documentation
#define __FJCORE_CLOSESTPAIR2D__HH__
Definition at line 722 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 722 of file fjcore.cc
#define __FJCORE_CLOSESTPAIR2DBASE__HH__
Definition at line 667 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 667 of file fjcore.cc
#define __FJCORE_CLUSTERQUENCE_N2_ICC__
Definition at line 87 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 87 of file fjcore.cc
#define __FJCORE_DYNAMICNEARESTNEIGHBOURS_HH__
Definition at line 160 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 160 of file fjcore.cc
#define __FJCORE_LAZYTILING25_HH__
Definition at line 1057 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 1057 of file fjcore.cc
#define __FJCORE_LAZYTILING9_HH__
Definition at line 948 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 948 of file fjcore.cc
#define __FJCORE_LAZYTILING9ALT_HH__
Definition at line 821 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 821 of file fjcore.cc
#define __FJCORE_MINHEAP__HH__
Definition at line 636 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 636 of file fjcore.cc
#define __FJCORE_SEARCHTREE_HH__
Definition at line 220 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 220 of file fjcore.cc
#define __FJCORE_TILINGEXTENT_HH__
Definition at line 1144 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 1144 of file fjcore.cc
#define __FJCORE_VERSION_HH__
Definition at line 80 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 80 of file fjcore.cc
#define _FJCORE_TILING25_USE_TILING_ANALYSIS_
#define _FJCORE_TILING2_USE_TILING_ANALYSIS_
Definition at line 5351 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 5351 of file fjcore.cc
#define FJCORE_LAZY25_MIN3TILESY
#define FJCORE_LAZY9_MIN2TILESY
Typedef Documentation
typedef Tile2Base<9> Tile2
Definition at line 972 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 972 of file fjcore.cc
Function Documentation
string fastjet_version_string ()
Definition at line 1547 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 1547 of file fjcore.cc
References fastjet_version.
bool floor_ln2_less (unsigned x, unsigned y) inline
Definition at line 808 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 808 of file fjcore.cc
Referenced by ClosestPair2D::Shuffle::operator<().
bool have_same_momentum (const PseudoJet & jeta, const PseudoJet & jetb)
Definition at line 3900 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 3900 of file fjcore.cc
PseudoJet join (const vector< PseudoJet > & pieces, const JetDefinition::Recombiner & recombiner)
Definition at line 3604 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 3604 of file fjcore.cc
References i, and JetDefinition::Recombiner::plus_equal().
Referenced by cpp.ast.Parameter::__str__(), cpp.ast.Type::__str__(), upload.SubversionVCS::_CollapseKeywords(), cpp.gmock_class::_GenerateMethods(), cpp.gmock_class::_GenerateMocks(), cpp.ast.AstBuilder::_GenerateOne(), cpp.ast.AstBuilder::_GetClass(), upload.HttpRpcServer::_GetOpener(), acts._adapter::_make_config_adapter(), cpp.ast._GenericDeclaration::_TypeStringHelper(), pr_commands::atlas(), pump::BeautifyCode(), Acts::DD4hepLayerBuilder::centralLayers(), check_include_guards::code_print(), cpp.ast.TypeConverter::DeclarationToParts(), acts.examples::dump_args(), acts.examples::dump_args_calls(), Acts::DD4hepLayerBuilder::endcapLayers(), cpp.ast._GenericDeclaration::FullName(), generate_particle_data_table::generate_code(), upload.GitVCS::GenerateDiff(), upload.MercurialVCS::GenerateDiff(), gen_gtest_pred_impl::GenerateHeader(), cpp.gmock_class_test.GenerateMethodsTest::GenerateMethodSource(), cpp.gmock_class_test.GenerateMocksTest::GenerateMocks(), gen_gtest_pred_impl::GenerateUnitTest(), upload.MercurialVCS::GetBaseFile(), cpp.ast.AstBuilder::handle_struct(), helpers.hash_root::hash_root_file(), join(), check_end_of_file::main(), upload_gmock::main(), upload_gtest::main(), check_license::main(), cpp.gmock_class::main(), makeCondorJobs::makeCondorJob(), Acts::Polyhedron::merge(), parse_clang_tidy::parse_clang_tidy_item(), OnlMonHtml::plainHtmlMenu(), gtest_throw_on_failure_test::Run(), utils::run_analysis(), gtest_throw_on_failure_test.ThrowOnFailureTest::RunAndVerify(), gtest_break_on_failure_unittest.GTestBreakOnFailureUnitTest::RunAndVerify(), gtest_list_tests_unittest.GTestListTestsUnitTest::RunAndVerify(), upload::RunShellWithReturnCode(), upload::SplitPatch(), cpp.gmock_class_test.TestCase::StripLeadingWhitespace(), pump::SubString(), gtest_output_test.GTestOutputTest::testOutput(), gen_gtest_pred_impl::TestsForArity(), cpp.ast.TypeConverter::ToType(), and Acts::CylinderVolumeBuilder::trackingVolume().
PseudoJet join (const PseudoJet & j1, const JetDefinition::Recombiner & recombiner)
Definition at line 3615 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 3615 of file fjcore.cc
References join().
PseudoJet join (const PseudoJet & j1, const PseudoJet & j2, const JetDefinition::Recombiner & recombiner)
Definition at line 3619 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 3619 of file fjcore.cc
References join().
PseudoJet join (const PseudoJet & j1, const PseudoJet & j2, const PseudoJet & j3, const JetDefinition::Recombiner & recombiner)
Definition at line 3626 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 3626 of file fjcore.cc
References join().
PseudoJet join (const PseudoJet & j1, const PseudoJet & j2, const PseudoJet & j3, const PseudoJet & j4, const JetDefinition::Recombiner & recombiner)
Definition at line 3634 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 3634 of file fjcore.cc
References join().
PseudoJet join (const vector< PseudoJet > & pieces)
Definition at line 4074 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 4074 of file fjcore.cc
References i, and PseudoJet::PseudoJet().
PseudoJet join (const PseudoJet & j1)
Definition at line 4082 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 4082 of file fjcore.cc
References join().
PseudoJet join (const PseudoJet & j1, const PseudoJet & j2)
Definition at line 4085 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 4085 of file fjcore.cc
References join(), and PseudoJet::pieces().
PseudoJet join (const PseudoJet & j1, const PseudoJet & j2, const PseudoJet & j3)
Definition at line 4092 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 4092 of file fjcore.cc
References join(), and PseudoJet::pieces().
PseudoJet join (const PseudoJet & j1, const PseudoJet & j2, const PseudoJet & j3, const PseudoJet & j4)
Definition at line 4100 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 4100 of file fjcore.cc
References join(), and PseudoJet::pieces().
Selector operator! (const Selector & s)
Definition at line 4317 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 4317 of file fjcore.cc
Selector operator&& (const Selector & s1, const Selector & s2)
Definition at line 4376 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 4376 of file fjcore.cc
PseudoJet operator* (double coeff, const PseudoJet & jet)
Definition at line 3816 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 3816 of file fjcore.cc
PseudoJet operator* (const PseudoJet & jet, double coeff)
Definition at line 3822 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 3822 of file fjcore.cc
Selector operator* (const Selector & s1, const Selector & s2)
Definition at line 4437 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 4437 of file fjcore.cc
PseudoJet operator+ (const PseudoJet & jet1, const PseudoJet & jet2)
Definition at line 3804 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 3804 of file fjcore.cc
PseudoJet operator- (const PseudoJet & jet1, const PseudoJet & jet2)
Definition at line 3810 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 3810 of file fjcore.cc
PseudoJet operator/ (const PseudoJet & jet, double coeff)
Definition at line 3825 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 3825 of file fjcore.cc
ostream& operator<< (ostream & ostr, const TiledJet & jet)
Definition at line 5907 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 5907 of file fjcore.cc
References TiledJet::_jets_index, TiledJet::eta, TiledJet::kt2, TiledJet::phi, and TiledJet::tile_index.
bool operator== (const PseudoJet & a, const PseudoJet & b)
Definition at line 3853 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 3853 of file fjcore.cc
bool operator== (const PseudoJet & jet, const double val)
Definition at line 3864 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 3864 of file fjcore.cc
Selector operator|| (const Selector & s1, const Selector & s2)
Definition at line 4416 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 4416 of file fjcore.cc
PseudoJet PtYPhiM (double pt, double y, double phi, double m)
Definition at line 3922 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 3922 of file fjcore.cc
References assert, and twopi.
Selector SelectorAbsEtaMax (double absetamax)
select objects with |eta| <= absetamax
Definition at line 4676 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 4676 of file fjcore.cc
Referenced by FastJetAlgo::calc_rhomeddens(), FastJetAlgo::cluster_and_fill(), RandomConeAna::EstimateRhos(), main(), and JetBkgdSub::process_event().
Selector SelectorAbsEtaMin (double absetamin)
select objects with |eta| >= absetamin
Definition at line 4673 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 4673 of file fjcore.cc
Selector SelectorAbsEtaRange (double absetamin, double absetamax)
select objects with absetamin <= |eta| <= absetamax
Definition at line 4679 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 4679 of file fjcore.cc
Selector SelectorAbsRapMax (double absrapmax)
select objects with |rap| <= absrapmax
Definition at line 4645 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 4645 of file fjcore.cc
Referenced by FastJetAlgo::get_selector(), main(), PHAJMaker::PHAJMaker(), and PHAJMaker::process_event().
Selector SelectorAbsRapMin (double absrapmin)
select objects with |rap| >= absrapmin
Definition at line 4642 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 4642 of file fjcore.cc
Selector SelectorAbsRapRange (double rapmin, double rapmax)
select objects with absrapmin <= |rap| <= absrapmax
Definition at line 4648 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 4648 of file fjcore.cc
Selector SelectorCircle (const double radius)
Definition at line 4799 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 4799 of file fjcore.cc
Referenced by PHAJMaker::process_event().
Selector SelectorDoughnut (const double radius_in, const double radius_out)
Definition at line 4833 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 4833 of file fjcore.cc
Selector SelectorEMax (double Emax)
select objects with E <= Emax
Definition at line 4544 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 4544 of file fjcore.cc
Selector SelectorEMin (double Emin)
select objects with E >= Emin
Definition at line 4541 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 4541 of file fjcore.cc
Selector SelectorERange (double Emin, double Emax)
select objects with Emin <= E <= Emax
Definition at line 4547 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 4547 of file fjcore.cc
Selector SelectorEtaMax (double etamax)
select objects with eta <= etamax
Definition at line 4660 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 4660 of file fjcore.cc
Selector SelectorEtaMin (double etamin)
select objects with eta >= etamin
Definition at line 4657 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 4657 of file fjcore.cc
Selector SelectorEtaRange (double etamin, double etamax)
select objects with etamin <= eta <= etamax
Definition at line 4663 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 4663 of file fjcore.cc
Selector SelectorEtMax (double Etmax)
select objects with Et <= Etmax
Definition at line 4529 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 4529 of file fjcore.cc
Selector SelectorEtMin (double Etmin)
select objects with Et >= Etmin
Definition at line 4526 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 4526 of file fjcore.cc
Selector SelectorEtRange (double Etmin, double Etmax)
select objects with Etmin <= Et <= Etmax
Definition at line 4532 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 4532 of file fjcore.cc
Selector SelectorIdentity ()
Definition at line 4282 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 4282 of file fjcore.cc
Referenced by PHAJMaker::PHAJMaker().
Selector SelectorIsZero ()
Definition at line 4929 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 4929 of file fjcore.cc
Selector SelectorMassMax (double mmax)
select objects with Mass <= Mmax
Definition at line 4559 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 4559 of file fjcore.cc
Selector SelectorMassMin (double mmin)
select objects with Mass >= Mmin
Definition at line 4556 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 4556 of file fjcore.cc
Selector SelectorMassRange (double mmin, double mmax)
select objects with Mmin <= Mass <= Mmax
Definition at line 4562 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 4562 of file fjcore.cc
Selector SelectorNHardest (unsigned int n)
Definition at line 4755 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 4755 of file fjcore.cc
Referenced by FastJetAlgo::calc_rhomeddens(), RandomConeAna::EstimateRhos(), JetBkgdSub::process_event(), and PHAJMaker::process_event().
Selector SelectorPhiRange (double phimin, double phimax)
select objects with phimin <= phi <= phimax
Definition at line 4707 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 4707 of file fjcore.cc
Selector SelectorPtFractionMin (double fraction)
Definition at line 4918 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 4918 of file fjcore.cc
Selector SelectorPtMax (double ptmax)
select objects with pt <= ptmax
Definition at line 4514 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 4514 of file fjcore.cc
Referenced by FastJetAlgo::first_call_init(), and PHAJMaker::PHAJMaker().
Selector SelectorPtMin (double ptmin)
select objects with pt >= ptmin
Definition at line 4511 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 4511 of file fjcore.cc
Referenced by RandomConeAna::EstimateRhos(), FastJetAlgo::get_selector(), main(), and PHAJMaker::PHAJMaker().
Selector SelectorPtRange (double ptmin, double ptmax)
select objects with ptmin <= pt <= ptmax
Definition at line 4517 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 4517 of file fjcore.cc
Referenced by main().
Selector SelectorRapMax (double rapmax)
select objects with rap <= rapmax
Definition at line 4605 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 4605 of file fjcore.cc
Selector SelectorRapMin (double rapmin)
select objects with rap >= rapmin
Definition at line 4602 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 4602 of file fjcore.cc
Selector SelectorRapPhiRange (double rapmin, double rapmax, double phimin, double phimax)
Definition at line 4722 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 4722 of file fjcore.cc
Selector SelectorRapRange (double rapmin, double rapmax)
select objects with rapmin <= rap <= rapmax
Definition at line 4608 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 4608 of file fjcore.cc
Selector SelectorRectangle (const double half_rap_width, const double half_phi_width)
Definition at line 4898 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 4898 of file fjcore.cc
Selector SelectorStrip (const double half_width)
Definition at line 4865 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 4865 of file fjcore.cc
void sort_indices (vector< int > & indices, const vector< double > & values)
Definition at line 4049 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 4049 of file fjcore.cc
References Acts::Experimental::detail::BlueprintHelper::sort().
Referenced by objects_sorted_by_values().
vector<PseudoJet> sorted_by_E (const vector< PseudoJet > & jets)
Definition at line 4064 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 4064 of file fjcore.cc
References i, and objects_sorted_by_values().
Referenced by JetDefinition::operator()().
vector<PseudoJet> sorted_by_pt (const vector< PseudoJet > & jets)
Definition at line 4054 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 4054 of file fjcore.cc
References i, and objects_sorted_by_values().
Referenced by FastJetAlgo::cluster_area_jets(), FastJetAlgo::cluster_jets(), RandomConeAna::EstimateRhos(), main(), JetDefinition::operator()(), JetBkgdSub::process_event(), PHAJMaker::process_event(), EMJetVal::process_event(), and TreeMaker::UseFastJet().
vector<PseudoJet> sorted_by_pz (const vector< PseudoJet > & jets)
Definition at line 4069 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 4069 of file fjcore.cc
References i, objects_sorted_by_values(), and PseudoJet::pz().
vector<PseudoJet> sorted_by_rapidity (const vector< PseudoJet > & jets)
Definition at line 4059 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 4059 of file fjcore.cc
References i, and objects_sorted_by_values().
Variable Documentation
FJCORE_BEGIN_NAMESPACE const char* fastjet_version = FJCORE_PACKAGE_VERSION
Definition at line 83 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 83 of file fjcore.cc
Referenced by fastjet_version_string(), and ClusterSequence::print_banner().
const int n_tile_neighbours = 9
Definition at line 834 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 834 of file fjcore.cc
FJCORE_BEGIN_NAMESPACE typedef Tile2Base<25> Tile25
Definition at line 1059 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 1059 of file fjcore.cc
FJCORE_BEGIN_NAMESPACE const double tile_edge_security_margin =1.0e-7
Definition at line 823 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 823 of file fjcore.cc
Referenced by LazyTiling9::_add_untagged_neighbours_to_tile_union_using_max_info(), and LazyTiling25::_add_untagged_neighbours_to_tile_union_using_max_info().
FJCORE_END_NAMESPACE FJCORE_BEGIN_NAMESPACE const unsigned int twopow31 = 2147483648U
Definition at line 1164 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 1164 of file fjcore.cc