Analysis Software: Acts::MaterialInteraction Struct Reference
Acts::MaterialInteraction Struct Reference
The Material interaction struct It records the surface and the passed material This is only necessary recorded when configured.
#include <acts/blob/sPHENIX/Core/include/Acts/Material/MaterialInteraction.hpp>
Public Attributes
Vector3 position = Vector3(0., 0., 0)
The particle position at the interaction.
double time = 0.0
The particle time at the interaction.
Vector3 direction = Vector3(0., 0., 0)
The particle direction at the interaction.
double deltaP = 0.0
The momentum change due to the interaction.
double sigmaPhi2 = 0.0
Expected phi variance due to the interactions.
double sigmaTheta2 = 0.0
Expected theta variance due to the interactions.
double sigmaQoP2 = 0.0
Expected q/p variance due to the interactions.
Vector3 intersection = Vector3(0., 0., 0)
The position where the interaction occurred.
GeometryIdentifier intersectionID
The ID where the interaction occurred.
const Surface * surface = nullptr
The surface where the interaction occurred.
InteractionVolume volume {}
The volume where the interaction occurred.
bool updatedVolumeStep = false
Update the volume step to implement the proper step size.
double pathCorrection = 1.
The path correction factor due to non-zero incidence on the surface.
MaterialSlab materialSlab
The effective, passed material properties including the path correction.
Detailed Description
The Material interaction struct It records the surface and the passed material This is only necessary recorded when configured.
Definition at line 62 of file MaterialInteraction.hpp.
View newest version in sPHENIX GitHub at line 62 of file MaterialInteraction.hpp
Member Data Documentation
double Acts::MaterialInteraction::deltaP = 0.0
The momentum change due to the interaction.
Definition at line 70 of file MaterialInteraction.hpp.
View newest version in sPHENIX GitHub at line 70 of file MaterialInteraction.hpp
Referenced by Acts::MaterialInteractor::recordResult().
Vector3 Acts::MaterialInteraction::direction = Vector3(0., 0., 0)
The particle direction at the interaction.
Definition at line 68 of file MaterialInteraction.hpp.
View newest version in sPHENIX GitHub at line 68 of file MaterialInteraction.hpp
Referenced by ActsExamples::RootMaterialTrackReader::read(), Acts::MaterialInteractor::recordResult(), and ActsExamples::MaterialSteppingAction::UserSteppingAction().
Vector3 Acts::MaterialInteraction::intersection = Vector3(0., 0., 0)
The position where the interaction occurred.
Definition at line 78 of file MaterialInteraction.hpp.
View newest version in sPHENIX GitHub at line 78 of file MaterialInteraction.hpp
Referenced by Acts::SurfaceMaterialMapper::mapInteraction(), and ActsExamples::RootMaterialTrackReader::read().
GeometryIdentifier Acts::MaterialInteraction::intersectionID
The ID where the interaction occurred.
Definition at line 80 of file MaterialInteraction.hpp.
View newest version in sPHENIX GitHub at line 80 of file MaterialInteraction.hpp
Referenced by Acts::SurfaceMaterialMapper::mapInteraction(), and ActsExamples::RootMaterialTrackReader::read().
MaterialSlab Acts::MaterialInteraction::materialSlab
The effective, passed material properties including the path correction.
Definition at line 90 of file MaterialInteraction.hpp.
View newest version in sPHENIX GitHub at line 90 of file MaterialInteraction.hpp
Referenced by ActsExamples::RootMaterialTrackReader::read(), Acts::MaterialInteractor::recordResult(), and ActsExamples::MaterialSteppingAction::UserSteppingAction().
double Acts::MaterialInteraction::pathCorrection = 1.
The path correction factor due to non-zero incidence on the surface.
Definition at line 88 of file MaterialInteraction.hpp.
View newest version in sPHENIX GitHub at line 88 of file MaterialInteraction.hpp
Referenced by ActsExamples::RootMaterialTrackReader::read(), Acts::MaterialInteractor::recordResult(), and ActsExamples::MaterialSteppingAction::UserSteppingAction().
Vector3 Acts::MaterialInteraction::position = Vector3(0., 0., 0)
The particle position at the interaction.
Definition at line 64 of file MaterialInteraction.hpp.
View newest version in sPHENIX GitHub at line 64 of file MaterialInteraction.hpp
Referenced by ActsExamples::RootMaterialTrackReader::read(), Acts::MaterialInteractor::recordResult(), and ActsExamples::MaterialSteppingAction::UserSteppingAction().
double Acts::MaterialInteraction::sigmaPhi2 = 0.0
Expected phi variance due to the interactions.
Definition at line 72 of file MaterialInteraction.hpp.
View newest version in sPHENIX GitHub at line 72 of file MaterialInteraction.hpp
Referenced by Acts::MaterialInteractor::recordResult().
double Acts::MaterialInteraction::sigmaQoP2 = 0.0
Expected q/p variance due to the interactions.
Definition at line 76 of file MaterialInteraction.hpp.
View newest version in sPHENIX GitHub at line 76 of file MaterialInteraction.hpp
Referenced by Acts::MaterialInteractor::recordResult().
double Acts::MaterialInteraction::sigmaTheta2 = 0.0
Expected theta variance due to the interactions.
Definition at line 74 of file MaterialInteraction.hpp.
View newest version in sPHENIX GitHub at line 74 of file MaterialInteraction.hpp
Referenced by Acts::MaterialInteractor::recordResult().
const Surface* Acts::MaterialInteraction::surface = nullptr
The surface where the interaction occurred.
Definition at line 82 of file MaterialInteraction.hpp.
View newest version in sPHENIX GitHub at line 82 of file MaterialInteraction.hpp
Referenced by Acts::SurfaceMaterialMapper::mapInteraction(), and Acts::MaterialInteractor::recordResult().
double Acts::MaterialInteraction::time = 0.0
The particle time at the interaction.
Definition at line 66 of file MaterialInteraction.hpp.
View newest version in sPHENIX GitHub at line 66 of file MaterialInteraction.hpp
Referenced by Acts::MaterialInteractor::recordResult().
bool Acts::MaterialInteraction::updatedVolumeStep = false
Update the volume step to implement the proper step size.
Definition at line 86 of file MaterialInteraction.hpp.
View newest version in sPHENIX GitHub at line 86 of file MaterialInteraction.hpp
InteractionVolume Acts::MaterialInteraction::volume {}
The volume where the interaction occurred.
Definition at line 84 of file MaterialInteraction.hpp.
View newest version in sPHENIX GitHub at line 84 of file MaterialInteraction.hpp
Referenced by Acts::MaterialInteractor::recordResult().
The documentation for this struct was generated from the following file:
acts/blob/sPHENIX/Core/include/Acts/Material/MaterialInteraction.hpp