Analysis Software: Acts::Legacy::SPForSeed< SpacePoint > Class Template Reference
Acts::Legacy::SPForSeed< SpacePoint > Class Template Reference
#include <acts/blob/sPHENIX/Plugins/Legacy/include/Acts/Seeding/SPForSeed.hpp>
Public Member Functions
SPForSeed ()
SPForSeed (SpacePoint *const &, const float *)
SPForSeed (SpacePoint *const &, const float *, const float *)
SPForSeed (const SPForSeed &)
virtual ~SPForSeed ()
SPForSeed & operator= (const SPForSeed &)
void set (SpacePoint *const &, const float *)
void set (SpacePoint *const &, const float *, const float *)
void setQuality (float)
void setParam (const float &)
const float & x () const
const float & y () const
const float & z () const
const float & radius () const
float phi () const
const float & covr () const
const float & covz () const
const float & param () const
const float & quality () const
const int & surface () const
Public Attributes
const SpacePoint * spacepoint = nullptr
Protected Attributes
float m_x = 0
float m_y = 0
float m_z = 0
float m_r = 0
float m_covr = 0
float m_covz = 0
float m_param = 0
float m_q = 0
int m_surface = 0
Detailed Description
template<typename SpacePoint>
class Acts::Legacy::SPForSeed< SpacePoint >
Definition at line 35 of file SPForSeed.hpp.
View newest version in sPHENIX GitHub at line 35 of file SPForSeed.hpp
Constructor & Destructor Documentation
template<typename SpacePoint > Acts::Legacy::SPForSeed< SpacePoint >::SPForSeed () inline
Definition at line 84 of file SPForSeed.hpp.
View newest version in sPHENIX GitHub at line 84 of file SPForSeed.hpp
template<typename SpacePoint > Acts::Legacy::SPForSeed< SpacePoint >::SPForSeed (SpacePoint *const & sp, const float * r) inline
Definition at line 113 of file SPForSeed.hpp.
View newest version in sPHENIX GitHub at line 113 of file SPForSeed.hpp
References physmon_track_finding_ttbar::r.
template<typename SpacePoint > Acts::Legacy::SPForSeed< SpacePoint >::SPForSeed (SpacePoint *const & sp, const float * r, const float * sc) inline
Definition at line 119 of file SPForSeed.hpp.
View newest version in sPHENIX GitHub at line 119 of file SPForSeed.hpp
References physmon_track_finding_ttbar::r.
template<typename SpacePoint > Acts::Legacy::SPForSeed< SpacePoint >::SPForSeed (const SPForSeed< SpacePoint > & sp) inline
Definition at line 130 of file SPForSeed.hpp.
View newest version in sPHENIX GitHub at line 130 of file SPForSeed.hpp
template<typename SpacePoint > Acts::Legacy::SPForSeed< SpacePoint >::~SPForSeed () inline virtual default
Member Function Documentation
template<typename SpacePoint> const float& Acts::Legacy::SPForSeed< SpacePoint >::covr () const inline
Definition at line 59 of file SPForSeed.hpp.
View newest version in sPHENIX GitHub at line 59 of file SPForSeed.hpp
References Acts::Legacy::SPForSeed< SpacePoint >::m_covr.
Referenced by Acts::Legacy::AtlasSeedFinder< SpacePoint >::production3Sp().
template<typename SpacePoint> const float& Acts::Legacy::SPForSeed< SpacePoint >::covz () const inline
Definition at line 60 of file SPForSeed.hpp.
View newest version in sPHENIX GitHub at line 60 of file SPForSeed.hpp
References Acts::Legacy::SPForSeed< SpacePoint >::m_covz.
Referenced by Acts::Legacy::AtlasSeedFinder< SpacePoint >::production3Sp().
template<typename SpacePoint > SPForSeed< SpacePoint > & Acts::Legacy::SPForSeed< SpacePoint >::operator= (const SPForSeed< SpacePoint > & sp) inline
Definition at line 97 of file SPForSeed.hpp.
View newest version in sPHENIX GitHub at line 97 of file SPForSeed.hpp
References Acts::Legacy::SPForSeed< SpacePoint >::m_covr, Acts::Legacy::SPForSeed< SpacePoint >::m_covz, Acts::Legacy::SPForSeed< SpacePoint >::m_q, Acts::Legacy::SPForSeed< SpacePoint >::m_r, Acts::Legacy::SPForSeed< SpacePoint >::m_x, Acts::Legacy::SPForSeed< SpacePoint >::m_y, Acts::Legacy::SPForSeed< SpacePoint >::m_z, and Acts::Legacy::SPForSeed< SpacePoint >::spacepoint.
template<typename SpacePoint> const float& Acts::Legacy::SPForSeed< SpacePoint >::param () const inline
Definition at line 61 of file SPForSeed.hpp.
View newest version in sPHENIX GitHub at line 61 of file SPForSeed.hpp
References Acts::Legacy::SPForSeed< SpacePoint >::m_param.
template<typename SpacePoint> float Acts::Legacy::SPForSeed< SpacePoint >::phi () const inline
Definition at line 58 of file SPForSeed.hpp.
View newest version in sPHENIX GitHub at line 58 of file SPForSeed.hpp
References Acts::Legacy::SPForSeed< SpacePoint >::m_x, and Acts::Legacy::SPForSeed< SpacePoint >::m_y.
template<typename SpacePoint> const float& Acts::Legacy::SPForSeed< SpacePoint >::quality () const inline
Definition at line 62 of file SPForSeed.hpp.
View newest version in sPHENIX GitHub at line 62 of file SPForSeed.hpp
References Acts::Legacy::SPForSeed< SpacePoint >::m_q.
Referenced by Acts::Legacy::AtlasSeedFinder< SpacePoint >::newOneSeedWithCurvaturesComparison().
template<typename SpacePoint> const float& Acts::Legacy::SPForSeed< SpacePoint >::radius () const inline
Definition at line 57 of file SPForSeed.hpp.
View newest version in sPHENIX GitHub at line 57 of file SPForSeed.hpp
References Acts::Legacy::SPForSeed< SpacePoint >::m_r.
Referenced by Acts::Legacy::AtlasSeedFinder< SpacePoint >::newEvent().
template<typename SpacePoint > void Acts::Legacy::SPForSeed< SpacePoint >::set (SpacePoint *const & sp, const float * r) inline
Definition at line 146 of file SPForSeed.hpp.
View newest version in sPHENIX GitHub at line 146 of file SPForSeed.hpp
References SpacePoint::clusterList(), SpacePoint::covr, SpacePoint::covz, and SpacePoint::surface.
Referenced by Acts::Legacy::AtlasSeedFinder< SpacePoint >::newSpacePoint().
template<typename SpacePoint > void Acts::Legacy::SPForSeed< SpacePoint >::set (SpacePoint *const & sp, const float * r, const float * sc) inline
Definition at line 185 of file SPForSeed.hpp.
View newest version in sPHENIX GitHub at line 185 of file SPForSeed.hpp
References SpacePoint::clusterList(), SpacePoint::covr, and SpacePoint::covz.
template<typename SpacePoint > void Acts::Legacy::SPForSeed< SpacePoint >::setParam (const float & p) inline
Definition at line 240 of file SPForSeed.hpp.
View newest version in sPHENIX GitHub at line 240 of file SPForSeed.hpp
References merge_hashes::p.
template<typename SpacePoint > void Acts::Legacy::SPForSeed< SpacePoint >::setQuality (float q) inline
Definition at line 244 of file SPForSeed.hpp.
View newest version in sPHENIX GitHub at line 244 of file SPForSeed.hpp
template<typename SpacePoint> const int& Acts::Legacy::SPForSeed< SpacePoint >::surface () const inline
Definition at line 64 of file SPForSeed.hpp.
View newest version in sPHENIX GitHub at line 64 of file SPForSeed.hpp
References Acts::Legacy::SPForSeed< SpacePoint >::m_surface.
template<typename SpacePoint> const float& Acts::Legacy::SPForSeed< SpacePoint >::x () const inline
Definition at line 54 of file SPForSeed.hpp.
View newest version in sPHENIX GitHub at line 54 of file SPForSeed.hpp
References Acts::Legacy::SPForSeed< SpacePoint >::m_x.
Referenced by Acts::Legacy::AtlasSeedFinder< SpacePoint >::production3Sp().
template<typename SpacePoint> const float& Acts::Legacy::SPForSeed< SpacePoint >::y () const inline
Definition at line 55 of file SPForSeed.hpp.
View newest version in sPHENIX GitHub at line 55 of file SPForSeed.hpp
References Acts::Legacy::SPForSeed< SpacePoint >::m_y.
Referenced by Acts::Legacy::AtlasSeedFinder< SpacePoint >::production3Sp().
template<typename SpacePoint> const float& Acts::Legacy::SPForSeed< SpacePoint >::z () const inline
Definition at line 56 of file SPForSeed.hpp.
View newest version in sPHENIX GitHub at line 56 of file SPForSeed.hpp
References Acts::Legacy::SPForSeed< SpacePoint >::m_z.
Referenced by Acts::Legacy::AtlasSeedFinder< SpacePoint >::production3Sp().
Member Data Documentation
template<typename SpacePoint> float Acts::Legacy::SPForSeed< SpacePoint >::m_covr = 0 protected
Definition at line 71 of file SPForSeed.hpp.
View newest version in sPHENIX GitHub at line 71 of file SPForSeed.hpp
Referenced by Acts::Legacy::SPForSeed< SpacePoint >::covr(), and Acts::Legacy::SPForSeed< SpacePoint >::operator=().
template<typename SpacePoint> float Acts::Legacy::SPForSeed< SpacePoint >::m_covz = 0 protected
Definition at line 72 of file SPForSeed.hpp.
View newest version in sPHENIX GitHub at line 72 of file SPForSeed.hpp
Referenced by Acts::Legacy::SPForSeed< SpacePoint >::covz(), and Acts::Legacy::SPForSeed< SpacePoint >::operator=().
template<typename SpacePoint> float Acts::Legacy::SPForSeed< SpacePoint >::m_param = 0 protected
Definition at line 73 of file SPForSeed.hpp.
View newest version in sPHENIX GitHub at line 73 of file SPForSeed.hpp
Referenced by Acts::Legacy::SPForSeed< SpacePoint >::param().
template<typename SpacePoint> float Acts::Legacy::SPForSeed< SpacePoint >::m_q = 0 protected
Definition at line 74 of file SPForSeed.hpp.
View newest version in sPHENIX GitHub at line 74 of file SPForSeed.hpp
Referenced by Acts::Legacy::SPForSeed< SpacePoint >::operator=(), and Acts::Legacy::SPForSeed< SpacePoint >::quality().
template<typename SpacePoint> float Acts::Legacy::SPForSeed< SpacePoint >::m_r = 0 protected
Definition at line 70 of file SPForSeed.hpp.
View newest version in sPHENIX GitHub at line 70 of file SPForSeed.hpp
Referenced by Acts::Legacy::SPForSeed< SpacePoint >::operator=(), and Acts::Legacy::SPForSeed< SpacePoint >::radius().
template<typename SpacePoint> int Acts::Legacy::SPForSeed< SpacePoint >::m_surface = 0 protected
Definition at line 76 of file SPForSeed.hpp.
View newest version in sPHENIX GitHub at line 76 of file SPForSeed.hpp
Referenced by Acts::Legacy::SPForSeed< SpacePoint >::surface().
template<typename SpacePoint> float Acts::Legacy::SPForSeed< SpacePoint >::m_x = 0 protected
Definition at line 67 of file SPForSeed.hpp.
View newest version in sPHENIX GitHub at line 67 of file SPForSeed.hpp
Referenced by Acts::Legacy::SPForSeed< SpacePoint >::operator=(), Acts::Legacy::SPForSeed< SpacePoint >::phi(), and Acts::Legacy::SPForSeed< SpacePoint >::x().
template<typename SpacePoint> float Acts::Legacy::SPForSeed< SpacePoint >::m_y = 0 protected
Definition at line 68 of file SPForSeed.hpp.
View newest version in sPHENIX GitHub at line 68 of file SPForSeed.hpp
Referenced by Acts::Legacy::SPForSeed< SpacePoint >::operator=(), Acts::Legacy::SPForSeed< SpacePoint >::phi(), and Acts::Legacy::SPForSeed< SpacePoint >::y().
template<typename SpacePoint> float Acts::Legacy::SPForSeed< SpacePoint >::m_z = 0 protected
Definition at line 69 of file SPForSeed.hpp.
View newest version in sPHENIX GitHub at line 69 of file SPForSeed.hpp
Referenced by Acts::Legacy::SPForSeed< SpacePoint >::operator=(), and Acts::Legacy::SPForSeed< SpacePoint >::z().
template<typename SpacePoint> const SpacePoint* Acts::Legacy::SPForSeed< SpacePoint >::spacepoint = nullptr
Definition at line 53 of file SPForSeed.hpp.
View newest version in sPHENIX GitHub at line 53 of file SPForSeed.hpp
Referenced by Acts::Legacy::AtlasSeedFinder< SpacePoint >::newOneSeedWithCurvaturesComparison(), and Acts::Legacy::SPForSeed< SpacePoint >::operator=().
The documentation for this class was generated from the following file:
acts/blob/sPHENIX/Plugins/Legacy/include/Acts/Seeding/SPForSeed.hpp