Analysis Software: acts/blob/sPHENIX/Tests/IntegrationTests/Autodiff/PropagationCompareAtlasAutodiffConstant.cpp File Reference
PropagationCompareAtlasAutodiffConstant.cpp File Reference
#include <boost/test/data/test_case.hpp>
#include <boost/test/unit_test.hpp>
#include "Acts/Geometry/GeometryContext.hpp"
#include "Acts/MagneticField/ConstantBField.hpp"
#include "Acts/MagneticField/MagneticFieldContext.hpp"
#include "Acts/Plugins/Autodiff/AutodiffExtensionWrapper.hpp"
#include "Acts/Propagator/AtlasStepper.hpp"
#include "Acts/Propagator/DefaultExtension.hpp"
#include "Acts/Propagator/EigenStepper.hpp"
#include "Acts/Propagator/Propagator.hpp"
#include <limits>
#include <utility>
#include "../PropagationDatasets.hpp"
#include "../PropagationTests.hpp"
Functions
BOOST_DATA_TEST_CASE (Forward, ds::phi *ds::theta *ds::absMomentum *ds::chargeNonZero *ds::pathLength *ds::magneticField, phi, theta, p, q, s, bz)
BOOST_DATA_TEST_CASE (ToCylinderAlongZ, ds::phi *ds::thetaWithoutBeam *ds::absMomentum *ds::chargeNonZero *ds::pathLength *ds::magneticField, phi, theta, p, q, s, bz)
BOOST_DATA_TEST_CASE (ToDisc, ds::phiWithoutAmbiguity *ds::theta *ds::absMomentum *ds::chargeNonZero *ds::pathLength *ds::magneticField, phi, theta, p, q, s, bz)
BOOST_DATA_TEST_CASE (ToPlane, ds::phi *ds::theta *ds::absMomentum *ds::chargeNonZero *ds::pathLength *ds::magneticField, phi, theta, p, q, s, bz)
BOOST_DATA_TEST_CASE (ToStrawAlongZ, ds::phi *ds::thetaWithoutBeam *ds::absMomentum *ds::chargeNonZero *ds::pathLength *ds::magneticField, phi, theta, p, q, s, bz)
Function Documentation
BOOST_DATA_TEST_CASE (Forward , ds::phi *ds::theta *ds::absMomentum *ds::chargeNonZero *ds::pathLength *ds::magneticField , phi , theta , p , q , s , bz)
Definition at line 63 of file PropagationCompareAtlasAutodiffConstant.cpp.
View newest version in sPHENIX GitHub at line 63 of file PropagationCompareAtlasAutodiffConstant.cpp
References geoCtx, magCtx, makeParametersCurvilinear(), and runForwardComparisonTest().
BOOST_DATA_TEST_CASE (ToCylinderAlongZ , ds::phi *ds::thetaWithoutBeam *ds::absMomentum *ds::chargeNonZero *ds::pathLength *ds::magneticField , phi , theta , p , q , s , bz)
Definition at line 73 of file PropagationCompareAtlasAutodiffConstant.cpp.
View newest version in sPHENIX GitHub at line 73 of file PropagationCompareAtlasAutodiffConstant.cpp
References geoCtx, magCtx, makeParametersCurvilinear(), merge_hashes::p, ActsTests::PropagationDatasets::phi, runToSurfaceComparisonTest(), physmon_simulation::s, and ActsTests::PropagationDatasets::theta.
BOOST_DATA_TEST_CASE (ToDisc , ds::phiWithoutAmbiguity *ds::theta *ds::absMomentum *ds::chargeNonZero *ds::pathLength *ds::magneticField , phi , theta , p , q , s , bz)
Definition at line 84 of file PropagationCompareAtlasAutodiffConstant.cpp.
View newest version in sPHENIX GitHub at line 84 of file PropagationCompareAtlasAutodiffConstant.cpp
References geoCtx, magCtx, makeParametersCurvilinear(), merge_hashes::p, ActsTests::PropagationDatasets::phi, runToSurfaceComparisonTest(), physmon_simulation::s, and ActsTests::PropagationDatasets::theta.
BOOST_DATA_TEST_CASE (ToPlane , ds::phi *ds::theta *ds::absMomentum *ds::chargeNonZero *ds::pathLength *ds::magneticField , phi , theta , p , q , s , bz)
Definition at line 95 of file PropagationCompareAtlasAutodiffConstant.cpp.
View newest version in sPHENIX GitHub at line 95 of file PropagationCompareAtlasAutodiffConstant.cpp
References geoCtx, magCtx, makeParametersCurvilinear(), merge_hashes::p, ActsTests::PropagationDatasets::phi, runToSurfaceComparisonTest(), physmon_simulation::s, and ActsTests::PropagationDatasets::theta.
BOOST_DATA_TEST_CASE (ToStrawAlongZ , ds::phi *ds::thetaWithoutBeam *ds::absMomentum *ds::chargeNonZero *ds::pathLength *ds::magneticField , phi , theta , p , q , s , bz)
Definition at line 106 of file PropagationCompareAtlasAutodiffConstant.cpp.
View newest version in sPHENIX GitHub at line 106 of file PropagationCompareAtlasAutodiffConstant.cpp
References geoCtx, magCtx, makeParametersCurvilinear(), merge_hashes::p, ActsTests::PropagationDatasets::phi, runToSurfaceComparisonTest(), physmon_simulation::s, and ActsTests::PropagationDatasets::theta.