Analysis Software: SingleGl1PoolInput Class Reference
SingleGl1PoolInput Class Reference
#include <coresoftware/blob/master/offline/framework/fun4allraw/SingleGl1PoolInput.h>
Public Member Functions
SingleGl1PoolInput (const std::string &name)
~SingleGl1PoolInput () override
void FillPool (const unsigned int) override
void CleanupUsedPackets (const uint64_t bclk) override
bool CheckPoolDepth (const uint64_t bclk) override
void ClearCurrentEvent () override
bool GetSomeMoreEvents ()
void Print (const std::string &what="ALL") const override
void CreateDSTNode (PHCompositeNode *topNode) override
void SetBcoRange (const unsigned int i)
Public Member Functions inherited from SingleStreamingInput
SingleStreamingInput (const std::string &name, Fun4AllEvtInputPoolManager *inman)
SingleStreamingInput (const std::string &name)
~SingleStreamingInput () override
virtual Eventiterator * GetEventIterator ()
virtual void FillPool (const uint64_t)
virtual void RunNumber (const int runno)
virtual int RunNumber () const
virtual int fileopen (const std::string &filename) override
virtual int fileclose () override
virtual int AllDone () const
virtual void AllDone (const int i)
virtual void EventNumberOffset (const int i)
virtual Eventiterator * GetEventiterator () const
virtual
Fun4AllEvtInputPoolManager * InputManager ()
virtual void InputManager (Fun4AllEvtInputPoolManager *in)
virtual
Fun4AllStreamingInputManager * StreamingInputManager ()
virtual void StreamingInputManager (Fun4AllStreamingInputManager *in)
virtual void ConfigureStreamingInputManager ()
virtual void SubsystemEnum (const int id)
virtual int SubsystemEnum () const
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Public Member Functions inherited from InputFileHandler
InputFileHandler ()=default
virtual ~InputFileHandler ()=default
int OpenNextFile ()
int AddListFile (const std::string &filename)
int AddFile (const std::string &filename)
void AddToFileOpened (const std::string &filename)
void Print (const std::string &what="ALL") const
int IsOpen () const
void IsOpen (const int i)
void SetVerbosity (const int i)
int GetVerbosity () const
void UpdateFileList ()
void FileName (const std::string &fn)
const std::string FileName () const
Private Attributes
unsigned int m_NumSpecialEvents {0}
unsigned int m_BcoRange {0}
std::map< unsigned int, uint64_t > m_packet_bco
map bco to packet
std::set< uint64_t > m_BeamClockFEE
std::map< uint64_t,
std::vector< Gl1RawHit * > > m_Gl1RawHitMap
std::set< uint64_t > m_FEEBclkMap
std::set< uint64_t > m_BclkStack
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = std::numeric_limits<int>::max() - 10
}
Protected Member Functions inherited from Fun4AllBase
Fun4AllBase (const std::string &name="NONAME")
Detailed Description
Definition at line 16 of file SingleGl1PoolInput.h.
View newest version in sPHENIX GitHub at line 16 of file SingleGl1PoolInput.h
Constructor & Destructor Documentation
SingleGl1PoolInput::SingleGl1PoolInput (const std::string & name) explicit
Definition at line 28 of file SingleGl1PoolInput.cc.
View newest version in sPHENIX GitHub at line 28 of file SingleGl1PoolInput.cc
References Fun4AllStreamingInputManager::GL1, and SingleStreamingInput::SubsystemEnum().
SingleGl1PoolInput::~SingleGl1PoolInput () override
Definition at line 34 of file SingleGl1PoolInput.cc.
View newest version in sPHENIX GitHub at line 34 of file SingleGl1PoolInput.cc
References CleanupUsedPackets().
Member Function Documentation
bool SingleGl1PoolInput::CheckPoolDepth (const uint64_t bclk) override virtual
Reimplemented from SingleStreamingInput.
Definition at line 182 of file SingleGl1PoolInput.cc.
View newest version in sPHENIX GitHub at line 182 of file SingleGl1PoolInput.cc
References m_FEEBclkMap, PHWHERE, and Fun4AllBase::Verbosity().
void SingleGl1PoolInput::CleanupUsedPackets (const uint64_t bclk) override virtual
Reimplemented from SingleStreamingInput.
Definition at line 151 of file SingleGl1PoolInput.cc.
View newest version in sPHENIX GitHub at line 151 of file SingleGl1PoolInput.cc
References m_BclkStack, m_BeamClockFEE, and m_Gl1RawHitMap.
Referenced by ClearCurrentEvent(), and ~SingleGl1PoolInput().
void SingleGl1PoolInput::ClearCurrentEvent () override virtual
Reimplemented from SingleStreamingInput.
Definition at line 209 of file SingleGl1PoolInput.cc.
View newest version in sPHENIX GitHub at line 209 of file SingleGl1PoolInput.cc
References CleanupUsedPackets(), and m_BclkStack.
void SingleGl1PoolInput::CreateDSTNode (PHCompositeNode * topNode) override virtual
Reimplemented from SingleStreamingInput.
Definition at line 247 of file SingleGl1PoolInput.cc.
View newest version in sPHENIX GitHub at line 247 of file SingleGl1PoolInput.cc
References PHCompositeNode::addNode(), and PHNodeIterator::findFirst().
void SingleGl1PoolInput::FillPool (const unsigned int) override virtual
Reimplemented from SingleStreamingInput.
Definition at line 39 of file SingleGl1PoolInput.cc.
View newest version in sPHENIX GitHub at line 39 of file SingleGl1PoolInput.cc
References Fun4AllStreamingInputManager::AddGl1RawHit(), SingleStreamingInput::AllDone(), DATAEVENT, SingleStreamingInput::fileclose(), SingleStreamingInput::GetEventiterator(), Event::getEvtSequence(), Event::getEvtType(), Event::getPacket(), Event::getRunNumber(), GetSomeMoreEvents(), InputFileHandler::GetVerbosity(), Event::identify(), Packet::identify(), Packet::lValue(), m_BclkStack, m_BeamClockFEE, m_FEEBclkMap, m_Gl1RawHitMap, m_NumSpecialEvents, InputFileHandler::OpenNextFile(), PHWHERE, SingleStreamingInput::RunNumber(), Gl1RawHit::set_bco(), SingleStreamingInput::StreamingInputManager(), and Fun4AllBase::Verbosity().
bool SingleGl1PoolInput::GetSomeMoreEvents ()
Definition at line 220 of file SingleGl1PoolInput.cc.
View newest version in sPHENIX GitHub at line 220 of file SingleGl1PoolInput.cc
References SingleStreamingInput::AllDone(), m_BcoRange, m_Gl1RawHitMap, PHWHERE, and Fun4AllBase::Verbosity().
Referenced by FillPool().
void SingleGl1PoolInput::Print (const std::string & what = "ALL") const override virtual
Print out some info about this module.
Parameters
what can be used to specify what to print exactly.
Reimplemented from SingleStreamingInput.
Definition at line 113 of file SingleGl1PoolInput.cc.
View newest version in sPHENIX GitHub at line 113 of file SingleGl1PoolInput.cc
References m_BclkStack, m_BeamClockFEE, m_FEEBclkMap, m_Gl1RawHitMap, and PHWHERE.
void SingleGl1PoolInput::SetBcoRange (const unsigned int i) inline
Definition at line 28 of file SingleGl1PoolInput.h.
View newest version in sPHENIX GitHub at line 28 of file SingleGl1PoolInput.h
References i, and m_BcoRange.
Member Data Documentation
std::set<uint64_t> SingleGl1PoolInput::m_BclkStack private
Definition at line 41 of file SingleGl1PoolInput.h.
View newest version in sPHENIX GitHub at line 41 of file SingleGl1PoolInput.h
Referenced by CleanupUsedPackets(), ClearCurrentEvent(), FillPool(), and Print().
unsigned int SingleGl1PoolInput::m_BcoRange {0} private
Definition at line 33 of file SingleGl1PoolInput.h.
View newest version in sPHENIX GitHub at line 33 of file SingleGl1PoolInput.h
Referenced by GetSomeMoreEvents(), and SetBcoRange().
std::set<uint64_t> SingleGl1PoolInput::m_BeamClockFEE private
Definition at line 38 of file SingleGl1PoolInput.h.
View newest version in sPHENIX GitHub at line 38 of file SingleGl1PoolInput.h
Referenced by CleanupUsedPackets(), FillPool(), and Print().
std::set<uint64_t> SingleGl1PoolInput::m_FEEBclkMap private
Definition at line 40 of file SingleGl1PoolInput.h.
View newest version in sPHENIX GitHub at line 40 of file SingleGl1PoolInput.h
Referenced by CheckPoolDepth(), FillPool(), and Print().
std::map<uint64_t, std::vector<Gl1RawHit *> > SingleGl1PoolInput::m_Gl1RawHitMap private
Definition at line 39 of file SingleGl1PoolInput.h.
View newest version in sPHENIX GitHub at line 39 of file SingleGl1PoolInput.h
Referenced by CleanupUsedPackets(), FillPool(), GetSomeMoreEvents(), and Print().
unsigned int SingleGl1PoolInput::m_NumSpecialEvents {0} private
Definition at line 32 of file SingleGl1PoolInput.h.
View newest version in sPHENIX GitHub at line 32 of file SingleGl1PoolInput.h
Referenced by FillPool().
std::map<unsigned int, uint64_t> SingleGl1PoolInput::m_packet_bco private
map bco to packet
Definition at line 36 of file SingleGl1PoolInput.h.
View newest version in sPHENIX GitHub at line 36 of file SingleGl1PoolInput.h
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/framework/fun4allraw/SingleGl1PoolInput.h
coresoftware/blob/master/offline/framework/fun4allraw/SingleGl1PoolInput.cc