Analysis Software: Jetscape::StringTokenizer Class Reference
Jetscape::StringTokenizer Class Reference
#include <JETSCAPE/blob/main/src/framework/StringTokenizer.h>
Public Member Functions
StringTokenizer ()
StringTokenizer (const std::string &str, const std::string &delimiter=DEFAULT_DELIMITER)
~StringTokenizer ()
void set (const std::string &str, const std::string &delimiter=DEFAULT_DELIMITER)
void setString (const std::string &str)
void setDelimiter (const std::string &delimiter)
std::string next ()
std::vector< std::string > split ()
bool done () const
bool isGraphEntry () const
bool isNodeEntry () const
bool isNodeZero () const
bool isEdgeEntry () const
bool isCommentEntry () const
bool isEventEntry () const
bool isHadronEntry () const
Private Member Functions
void skipDelimiter ()
bool isDelimiter (char c)
Private Attributes
std::string buffer
std::string token
std::string delimiter
std::string::const_iterator currPos
Detailed Description
Definition at line 30 of file StringTokenizer.h.
View newest version in sPHENIX GitHub at line 30 of file StringTokenizer.h
Constructor & Destructor Documentation
Jetscape::StringTokenizer::StringTokenizer () inline
Definition at line 33 of file StringTokenizer.h.
View newest version in sPHENIX GitHub at line 33 of file StringTokenizer.h
Jetscape::StringTokenizer::StringTokenizer (const std::string & str, const std::string & delimiter = DEFAULT_DELIMITER)
Jetscape::StringTokenizer::~StringTokenizer ()
Definition at line 26 of file StringTokenizer.cc.
View newest version in sPHENIX GitHub at line 26 of file StringTokenizer.cc
Member Function Documentation
bool Jetscape::StringTokenizer::done () const inline
Definition at line 49 of file StringTokenizer.h.
View newest version in sPHENIX GitHub at line 49 of file StringTokenizer.h
References currPos.
bool Jetscape::StringTokenizer::isCommentEntry () const
Definition at line 69 of file StringTokenizer.cc.
View newest version in sPHENIX GitHub at line 69 of file StringTokenizer.cc
bool Jetscape::StringTokenizer::isDelimiter (char c) private
Definition at line 149 of file StringTokenizer.cc.
View newest version in sPHENIX GitHub at line 149 of file StringTokenizer.cc
References delimiter.
Referenced by next(), and skipDelimiter().
bool Jetscape::StringTokenizer::isEdgeEntry () const
Definition at line 58 of file StringTokenizer.cc.
View newest version in sPHENIX GitHub at line 58 of file StringTokenizer.cc
References isGraphEntry().
bool Jetscape::StringTokenizer::isEventEntry () const
Definition at line 77 of file StringTokenizer.cc.
View newest version in sPHENIX GitHub at line 77 of file StringTokenizer.cc
bool Jetscape::StringTokenizer::isGraphEntry () const
Definition at line 28 of file StringTokenizer.cc.
View newest version in sPHENIX GitHub at line 28 of file StringTokenizer.cc
Referenced by isEdgeEntry(), and isNodeZero().
bool Jetscape::StringTokenizer::isHadronEntry () const
Definition at line 86 of file StringTokenizer.cc.
View newest version in sPHENIX GitHub at line 86 of file StringTokenizer.cc
Referenced by isNodeZero().
bool Jetscape::StringTokenizer::isNodeEntry () const
Definition at line 36 of file StringTokenizer.cc.
View newest version in sPHENIX GitHub at line 36 of file StringTokenizer.cc
Referenced by isNodeZero().
bool Jetscape::StringTokenizer::isNodeZero () const
Definition at line 44 of file StringTokenizer.cc.
View newest version in sPHENIX GitHub at line 44 of file StringTokenizer.cc
References isGraphEntry(), isHadronEntry(), and isNodeEntry().
std::string Jetscape::StringTokenizer::next ()
Definition at line 118 of file StringTokenizer.cc.
View newest version in sPHENIX GitHub at line 118 of file StringTokenizer.cc
References currPos, isDelimiter(), skipDelimiter(), and token.
Referenced by split().
void Jetscape::StringTokenizer::set (const std::string & str, const std::string & delimiter = DEFAULT_DELIMITER)
Definition at line 97 of file StringTokenizer.cc.
View newest version in sPHENIX GitHub at line 97 of file StringTokenizer.cc
References currPos, delimiter, and str.
void Jetscape::StringTokenizer::setDelimiter (const std::string & delimiter)
Definition at line 109 of file StringTokenizer.cc.
View newest version in sPHENIX GitHub at line 109 of file StringTokenizer.cc
References currPos, and delimiter.
void Jetscape::StringTokenizer::setString (const std::string & str)
Definition at line 104 of file StringTokenizer.cc.
View newest version in sPHENIX GitHub at line 104 of file StringTokenizer.cc
References currPos, and str.
void Jetscape::StringTokenizer::skipDelimiter () private
Definition at line 141 of file StringTokenizer.cc.
View newest version in sPHENIX GitHub at line 141 of file StringTokenizer.cc
References currPos, and isDelimiter().
Referenced by next().
std::vector< std::string > Jetscape::StringTokenizer::split ()
Definition at line 157 of file StringTokenizer.cc.
View newest version in sPHENIX GitHub at line 157 of file StringTokenizer.cc
References next(), and token.
Member Data Documentation
std::string Jetscape::StringTokenizer::buffer private
Definition at line 64 of file StringTokenizer.h.
View newest version in sPHENIX GitHub at line 64 of file StringTokenizer.h
std::string::const_iterator Jetscape::StringTokenizer::currPos private
Definition at line 68 of file StringTokenizer.h.
View newest version in sPHENIX GitHub at line 68 of file StringTokenizer.h
Referenced by done(), next(), set(), setDelimiter(), setString(), and skipDelimiter().
std::string Jetscape::StringTokenizer::delimiter private
Definition at line 66 of file StringTokenizer.h.
View newest version in sPHENIX GitHub at line 66 of file StringTokenizer.h
Referenced by isDelimiter(), set(), and setDelimiter().
std::string Jetscape::StringTokenizer::token private
Definition at line 65 of file StringTokenizer.h.
View newest version in sPHENIX GitHub at line 65 of file StringTokenizer.h
Referenced by next(), and split().
The documentation for this class was generated from the following files:
JETSCAPE/blob/main/src/framework/StringTokenizer.h
JETSCAPE/blob/main/src/framework/StringTokenizer.cc