Analysis Software: Acts::Test::CylindricalTrackingGeometry Struct Reference
Acts::Test::CylindricalTrackingGeometry Struct Reference
#include <acts/blob/sPHENIX/Tests/CommonHelpers/Acts/Tests/CommonHelpers/CylindricalTrackingGeometry.hpp>
Public Types
using DetectorStore = std::vector< std::unique_ptr< const DetectorElementStub >>
Public Member Functions
CylindricalTrackingGeometry (const GeometryContext &gctx)
Only allowed constructor with reference wrapper.
std::vector< const Surface * > surfacesRing (DetectorStore &detStore, double moduleHalfXminY, double moduleHalfXmaxY, double moduleHalfY, double moduleThickness, double moduleTilt, double ringRadius, double ringZ, double zStagger, int nPhi)
std::vector< const Surface * > surfacesCylinder (DetectorStore &detStore, double moduleHalfX, double moduleHalfY, double moduleThickness, double moduleTiltPhi, double layerRadius, double radialStagger, double longitudinalOverlap, const std::pair< int, int > &binningSchema)
std::vector< Vector3 > modulePositionsCylinder (double radius, double zStagger, double moduleHalfLength, double lOverlap, const std::pair< int, int > &binningSchema)
std::shared_ptr< const
TrackingGeometry > operator() ()
Public Attributes
std::reference_wrapper< const
GeometryContext > geoContext
DetectorStore detectorStore = {}
The detector store for memory management.
Detailed Description
Definition at line 44 of file CylindricalTrackingGeometry.hpp.
View newest version in sPHENIX GitHub at line 44 of file CylindricalTrackingGeometry.hpp
Member Typedef Documentation
using Acts::Test::CylindricalTrackingGeometry::DetectorStore = std::vector<std::unique_ptr<const DetectorElementStub>>
Definition at line 50 of file CylindricalTrackingGeometry.hpp.
View newest version in sPHENIX GitHub at line 50 of file CylindricalTrackingGeometry.hpp
Constructor & Destructor Documentation
Acts::Test::CylindricalTrackingGeometry::CylindricalTrackingGeometry (const GeometryContext & gctx) inline
Only allowed constructor with reference wrapper.
Definition at line 48 of file CylindricalTrackingGeometry.hpp.
View newest version in sPHENIX GitHub at line 48 of file CylindricalTrackingGeometry.hpp
Member Function Documentation
std::vector<Vector3> Acts::Test::CylindricalTrackingGeometry::modulePositionsCylinder (double radius, double zStagger, double moduleHalfLength, double lOverlap, const std::pair< int, int > & binningSchema) inline
Helper method for cylinder layer create the positions for module surfaces on a cylinder
Definition at line 181 of file CylindricalTrackingGeometry.hpp.
View newest version in sPHENIX GitHub at line 181 of file CylindricalTrackingGeometry.hpp
References Acts::Test::minPhi, and physmon_ckf_tracking::u.
Referenced by surfacesCylinder().
std::shared_ptr<const TrackingGeometry> Acts::Test::CylindricalTrackingGeometry::operator() () inline
now push back the layer
Definition at line 211 of file CylindricalTrackingGeometry.hpp.
View newest version in sPHENIX GitHub at line 211 of file CylindricalTrackingGeometry.hpp
References Acts::arbitrary, Acts::Surface::assignSurfaceMaterial(), Acts::binR, Acts::TrackingVolume::create(), detectorStore, Acts::ProtoLayer::envelope, geoContext, Acts::getDefaultLogger(), Acts::Logging::INFO, Acts::CylinderVolumeHelper::Config::layerArrayCreator, Acts::PassiveLayerBuilder::Config::layerIdentification, Acts::Test::makeBeryllium(), Acts::Test::makeSilicon(), testing::internal::move(), Acts::LayerCreator::Config::surfaceArrayCreator, surfacesCylinder(), and Acts::CylinderVolumeBuilder::Config::trackingVolumeHelper.
std::vector<const Surface*> Acts::Test::CylindricalTrackingGeometry::surfacesCylinder (DetectorStore & detStore, double moduleHalfX, double moduleHalfY, double moduleThickness, double moduleTiltPhi, double layerRadius, double radialStagger, double longitudinalOverlap, const std::pair< int, int > & binningSchema) inline
Generator of surfaces for a cylindrical layer
Parameters
detStore The DetectorStore for storing the modules
moduleHalfX The half length in X of the module
moduleHalfY The half length in Y of the module
moduleThickness The module thickness
moduleTilePhi The tilt in phi direction of the module
layerRadius The radius of the cylindrical layer
radialStagger The radial delta of modules next in z
longitudinalOverlap The z overlap of modules next in z
binningSchema The number of bins in phi/z
Returns
A vector of Surfaces
Definition at line 127 of file CylindricalTrackingGeometry.hpp.
View newest version in sPHENIX GitHub at line 127 of file CylindricalTrackingGeometry.hpp
References Acts::Test::makeSilicon(), modulePositionsCylinder(), testing::internal::move(), and Acts::VectorHelpers::phi().
Referenced by Acts::Test::Layers::BOOST_AUTO_TEST_CASE(), Acts::Test::BOOST_AUTO_TEST_CASE(), BOOST_AUTO_TEST_CASE(), and operator()().
std::vector<const Surface*> Acts::Test::CylindricalTrackingGeometry::surfacesRing (DetectorStore & detStore, double moduleHalfXminY, double moduleHalfXmaxY, double moduleHalfY, double moduleThickness, double moduleTilt, double ringRadius, double ringZ, double zStagger, int nPhi) inline
Generator of surfaces for a ring
Parameters
detStore The DetectorStore for storing the modules
moduleHalfXminY The half length in X (at Y min) of the module
moduleHalfXmaxY The half length in X (at Y max) of the module
moduleHalfY The half length in Y of the module
moduleThickness The module thickness
moduleTilt The tilt out of the plane for discs
ringRadius The central radius of the ring
ringZ The z position of the ring
zStagger The z offset of phi modules
nPhi The number of phi modules
Returns
A vector of Surfaces
Definition at line 69 of file CylindricalTrackingGeometry.hpp.
View newest version in sPHENIX GitHub at line 69 of file CylindricalTrackingGeometry.hpp
References Acts::Test::makeSilicon(), testing::internal::move(), and ActsTests::PropagationDatasets::phi.
Referenced by Acts::Test::Layers::BOOST_AUTO_TEST_CASE(), Acts::Test::BOOST_AUTO_TEST_CASE(), and BOOST_AUTO_TEST_CASE().
Member Data Documentation
DetectorStore Acts::Test::CylindricalTrackingGeometry::detectorStore = {}
The detector store for memory management.
Definition at line 53 of file CylindricalTrackingGeometry.hpp.
View newest version in sPHENIX GitHub at line 53 of file CylindricalTrackingGeometry.hpp
Referenced by operator()().
std::reference_wrapper<const GeometryContext> Acts::Test::CylindricalTrackingGeometry::geoContext
Definition at line 45 of file CylindricalTrackingGeometry.hpp.
View newest version in sPHENIX GitHub at line 45 of file CylindricalTrackingGeometry.hpp
Referenced by operator()().
The documentation for this struct was generated from the following file:
acts/blob/sPHENIX/Tests/CommonHelpers/Acts/Tests/CommonHelpers/CylindricalTrackingGeometry.hpp