Analysis Software: Jetscape::JetScapeTask Class Reference
Jetscape::JetScapeTask Class Reference
#include <JETSCAPE/blob/main/src/framework/JetScapeTask.h>
Public Member Functions
JetScapeTask ()
virtual ~JetScapeTask ()
virtual void Init ()
virtual void Exec ()
virtual void Finish ()
virtual void Clear ()
virtual void ExecuteTasks ()
virtual void ExecuteTask ()
virtual void InitTask ()
virtual void InitTasks ()
virtual void ClearTasks ()
virtual void ClearTask ()
virtual void FinishTask ()
virtual void FinishTasks ()
virtual void WriteTasks (weak_ptr< JetScapeWriter > w)
virtual void WriteTask (weak_ptr< JetScapeWriter > w)
virtual void CollectHeader (weak_ptr< JetScapeWriter > w)
virtual void CollectHeaders (weak_ptr< JetScapeWriter > w)
virtual void Add (shared_ptr< JetScapeTask > m_tasks)
virtual const int GetMyTaskNumber () const
const vector< shared_ptr
< JetScapeTask > > GetTaskList () const
shared_ptr< JetScapeTask > GetTaskAt (int i)
void EraseTaskLast ()
void EraseTaskAt (int i)
void ResizeTaskList (int i)
void ClearTaskList ()
int GetNumberOfTasks ()
const bool GetActive () const
void SetActive (bool m_active_exec)
void SetId (string m_id)
const string GetId () const
const shared_ptr
< JetScapeModuleMutex > GetMutex () const
void SetMutex (shared_ptr< JetScapeModuleMutex > m_mutex)
Private Attributes
vector< shared_ptr
< JetScapeTask > > tasks
bool active_exec
string id
int my_task_number_
shared_ptr< JetScapeModuleMutex > mutex
Detailed Description
Definition at line 41 of file JetScapeTask.h.
View newest version in sPHENIX GitHub at line 41 of file JetScapeTask.h
Constructor & Destructor Documentation
Jetscape::JetScapeTask::JetScapeTask ()
Default constructor to create a JetScapeTask. It sets the flag "active_exec" to true and "id" to default string value.
Definition at line 28 of file JetScapeTask.cc.
View newest version in sPHENIX GitHub at line 28 of file JetScapeTask.cc
References VERBOSE.
Jetscape::JetScapeTask::~JetScapeTask () virtual
Default destructor for a JetScapeTask.
Definition at line 35 of file JetScapeTask.cc.
View newest version in sPHENIX GitHub at line 35 of file JetScapeTask.cc
References JSDEBUG, and VERBOSE.
Member Function Documentation
void Jetscape::JetScapeTask::Add (shared_ptr< JetScapeTask > m_tasks) virtual
This function adds the module "m_tasks" into the vector of subtask of a JetScapeTask.
Definition at line 88 of file JetScapeTask.cc.
View newest version in sPHENIX GitHub at line 88 of file JetScapeTask.cc
Referenced by Jetscape::JetScape::CheckForWriterFromXML(), and Jetscape::JetScape::DetermineTaskListFromXML().
virtual void Jetscape::JetScapeTask::Clear (void) inline virtual
A virtual function to define a default Clear() function for a JetScapeTask. It can be overridden by different modules/tasks.
Reimplemented in Jetscape::FluidDynamics, Jetscape::JetEnergyLoss, Jetscape::TrentoInitial, Jetscape::JetScapeModuleBase, Jetscape::PreequilibriumDynamics, Jetscape::HardProcess, Jetscape::JetEnergyLossManager, Jetscape::InitialState, InitialFromFile, IPGlasmaWrapper, NcollListFromFile, iSpectraSamplerWrapper, Jetscape::Hadronization, AdSCFT, Jetscape::HadronPrinter, Jetscape::HadronizationManager, Jetscape::SoftParticlization, and Jetscape::PartonPrinter.
Definition at line 66 of file JetScapeTask.h.
View newest version in sPHENIX GitHub at line 66 of file JetScapeTask.h
virtual void Jetscape::JetScapeTask::ClearTask () inline virtual
A virtual function to define a default ClearTask() function for a JetScapeTask. It can be overridden by different modules/tasks.
Definition at line 92 of file JetScapeTask.h.
View newest version in sPHENIX GitHub at line 92 of file JetScapeTask.h
void Jetscape::JetScapeTask::ClearTaskList () inline
This function removes all the tasks in the vector of tasks of a JetScapeTask and changes the size to 0.
Definition at line 164 of file JetScapeTask.h.
View newest version in sPHENIX GitHub at line 164 of file JetScapeTask.h
References tasks.
void Jetscape::JetScapeTask::ClearTasks () virtual
Recursively calls Clear() function of the subtasks of a JetScapeTask.
Definition at line 65 of file JetScapeTask.cc.
View newest version in sPHENIX GitHub at line 65 of file JetScapeTask.cc
References it, and VERBOSE.
Referenced by Jetscape::JetScape::Exec().
virtual void Jetscape::JetScapeTask::CollectHeader (weak_ptr< JetScapeWriter > w) inline virtual
Should get called only by CollectHeaders. Maybe make protected?
Parameters
w is a pointer of type JetScapeWrite class.
Reimplemented in Jetscape::FluidDynamics, Jetscape::HardProcess, and Jetscape::InitialState.
Definition at line 128 of file JetScapeTask.h.
View newest version in sPHENIX GitHub at line 128 of file JetScapeTask.h
void Jetscape::JetScapeTask::CollectHeaders (weak_ptr< JetScapeWriter > w) virtual
Recursively collect the header information of different tasks/subtasks of a JetScapeTask into a writer. We use "active_exec" flag to decide whether to write the output in the file or not.
Definition at line 80 of file JetScapeTask.cc.
View newest version in sPHENIX GitHub at line 80 of file JetScapeTask.cc
References it.
Referenced by Jetscape::JetScape::Exec().
void Jetscape::JetScapeTask::EraseTaskAt (int i) inline
This function deletes the task at ith location in the vector of tasks of a JetScapeTask.
Definition at line 156 of file JetScapeTask.h.
View newest version in sPHENIX GitHub at line 156 of file JetScapeTask.h
References i, and tasks.
void Jetscape::JetScapeTask::EraseTaskLast () inline
This function deletes the last task in the vector of tasks of a JetScapeTask.
Definition at line 151 of file JetScapeTask.h.
View newest version in sPHENIX GitHub at line 151 of file JetScapeTask.h
References tasks.
void Jetscape::JetScapeTask::Exec () virtual
A virtual function to define a default Exec() function for a JetScapeTask. It can be overridden by different modules/tasks.
Reimplemented in Jetscape::FluidDynamics, Jetscape::JetEnergyLoss, Jetscape::TrentoInitial, epemGun, Jetscape::JetScapeModuleBase, Jetscape::PreequilibriumDynamics, PythiaGun, Jetscape::JetScapeWriterHepMC, Jetscape::JetScapeWriterRootHepMC, Jetscape::HardProcess, Jetscape::JetEnergyLossManager, Jetscape::InitialState, InitialFromFile, Jetscape::JetScapeWriterFinalStateStream< T >, Jetscape::JetScape, iSpectraSamplerWrapper, IPGlasmaWrapper, Jetscape::JetScapeWriterStream< T >, NcollListFromFile, PGun, Jetscape::Afterburner, Jetscape::HadronPrinter, Jetscape::HadronizationManager, Jetscape::SoftParticlization, Jetscape::Hadronization, Jetscape::JetScapeWriterAsciiGZ, and Jetscape::PartonPrinter.
Definition at line 53 of file JetScapeTask.cc.
View newest version in sPHENIX GitHub at line 53 of file JetScapeTask.cc
References VERBOSE.
virtual void Jetscape::JetScapeTask::ExecuteTask () inline virtual
A virtual function to define a default ExecuteTask() function for a JetScapeTask. It can be overridden by different modules/tasks.
Reimplemented in SmashWrapper.
Definition at line 75 of file JetScapeTask.h.
View newest version in sPHENIX GitHub at line 75 of file JetScapeTask.h
void Jetscape::JetScapeTask::ExecuteTasks () virtual
Recursive Execution of all the subtasks of the JetScapeTask.
Definition at line 55 of file JetScapeTask.cc.
View newest version in sPHENIX GitHub at line 55 of file JetScapeTask.cc
References it, JSDEBUG, and VERBOSE.
Referenced by Jetscape::JetScape::Exec().
virtual void Jetscape::JetScapeTask::Finish () inline virtual
A virtual function to define a default Finish() function for a JetScapeTask. It can be overridden by different modules/tasks.
Reimplemented in Jetscape::JetScape.
Definition at line 62 of file JetScapeTask.h.
View newest version in sPHENIX GitHub at line 62 of file JetScapeTask.h
virtual void Jetscape::JetScapeTask::FinishTask () inline virtual
A virtual function to define a default FinishTask() function for a JetScapeTask. It can be overridden by different modules/tasks.
Definition at line 96 of file JetScapeTask.h.
View newest version in sPHENIX GitHub at line 96 of file JetScapeTask.h
virtual void Jetscape::JetScapeTask::FinishTasks () inline virtual
A virtual function to define a default FinishTasks() function for a JetScapeTask. It can be overridden by different modules/tasks.
Definition at line 100 of file JetScapeTask.h.
View newest version in sPHENIX GitHub at line 100 of file JetScapeTask.h
Referenced by Jetscape::JetScape::Finish().
const bool Jetscape::JetScapeTask::GetActive () const inline
This function tells whether the task is active or not.
Definition at line 172 of file JetScapeTask.h.
View newest version in sPHENIX GitHub at line 172 of file JetScapeTask.h
References active_exec.
Referenced by Jetscape::JetScapeWriterAsciiGZ::Init(), Jetscape::JetScapeWriterHepMC::Init(), Jetscape::JetScapeWriterRootHepMC::Init(), Jetscape::JetEnergyLoss::JetEnergyLoss(), Jetscape::JetScapeWriterAsciiGZ::~JetScapeWriterAsciiGZ(), Jetscape::JetScapeWriterHepMC::~JetScapeWriterHepMC(), and Jetscape::JetScapeWriterRootHepMC::~JetScapeWriterRootHepMC().
const string Jetscape::JetScapeTask::GetId () const inline
This function returns the id of the task of a JetScapeTask.
Definition at line 186 of file JetScapeTask.h.
View newest version in sPHENIX GitHub at line 186 of file JetScapeTask.h
References id.
Referenced by Jetscape::JetEnergyLossModule< AdSCFT >::Clone(), PGun::Exec(), Jetscape::SoftParticlization::Init(), Jetscape::InitialState::Init(), Jetscape::JetEnergyLoss::JetEnergyLoss(), Jetscape::JetEnergyLossModule< AdSCFT >::TakeResponsibilityFor(), Jetscape::JetScapeWriterAsciiGZ::WriteHeaderToFile(), and AdSCFT::WriteTask().
const shared_ptr<JetScapeModuleMutex> Jetscape::JetScapeTask::GetMutex () const inline
This function returns the mutex of a JetScapeTask.
Definition at line 190 of file JetScapeTask.h.
View newest version in sPHENIX GitHub at line 190 of file JetScapeTask.h
References mutex.
virtual const int Jetscape::JetScapeTask::GetMyTaskNumber () const inline virtual
This function returns the current task number.
Definition at line 141 of file JetScapeTask.h.
View newest version in sPHENIX GitHub at line 141 of file JetScapeTask.h
References my_task_number_.
Referenced by Jetscape::JetEnergyLossModule< AdSCFT >::Clone(), and Jetscape::JetScapeModuleBase::GetMt19937Generator().
int Jetscape::JetScapeTask::GetNumberOfTasks () inline
This function returns the number of tasks of a JetScapeTask stored in the vector array of tasks.
Definition at line 168 of file JetScapeTask.h.
View newest version in sPHENIX GitHub at line 168 of file JetScapeTask.h
References tasks.
Referenced by Jetscape::JetScape::Exec(), and Jetscape::JetScape::Init().
shared_ptr<JetScapeTask> Jetscape::JetScapeTask::GetTaskAt (int i) inline
This function returns the task at ith location in the vector of tasks of a JetScapeTask.
Definition at line 148 of file JetScapeTask.h.
View newest version in sPHENIX GitHub at line 148 of file JetScapeTask.h
References tasks.
const vector<shared_ptr<JetScapeTask> > Jetscape::JetScapeTask::GetTaskList () const inline
This function returns the vector of tasks of a JetScapeTask.
Definition at line 145 of file JetScapeTask.h.
View newest version in sPHENIX GitHub at line 145 of file JetScapeTask.h
References tasks.
Referenced by Jetscape::JetScape::Exec(), Jetscape::JetEnergyLoss::JetEnergyLoss(), and Jetscape::JetScape::SetPointers().
void Jetscape::JetScapeTask::Init () virtual
A virtual function to define a default initialization function for a JetScapeTask. It can be overridden by different modules tasks.
Reimplemented in Martini, Jetscape::FluidDynamics, Jetscape::JetEnergyLoss, Jetscape::JetScapeModuleBase, Jetscape::JetScapeWriterHepMC, Jetscape::PreequilibriumDynamics, Jetscape::JetScapeWriterRootHepMC, LBT, Jetscape::HardProcess, Jetscape::JetEnergyLossManager, Jetscape::JetScapeWriterFinalStateStream< T >, Jetscape::InitialState, Jetscape::JetScapeWriterStream< T >, AdSCFT, Jetscape::Afterburner, Jetscape::JetScape, Jetscape::HadronPrinter, Jetscape::HadronizationManager, Jetscape::SoftParticlization, Jetscape::Hadronization, HybridHadronization, Jetscape::JetScapeWriterAsciiGZ, Jetscape::PartonPrinter, ColorlessHadronization, Matter, ColoredHadronization, and ElossValidate.
Definition at line 41 of file JetScapeTask.cc.
View newest version in sPHENIX GitHub at line 41 of file JetScapeTask.cc
References JSDEBUG.
virtual void Jetscape::JetScapeTask::InitTask () inline virtual
A virtual function to define a default InitTask() function for a JetScapeTask. It can be overridden by different modules/tasks.
Reimplemented in SmashWrapper, Jetscape::TrentoInitial, epemGun, PythiaGun, InitialFromFile, Brick, IPGlasmaWrapper, iSpectraSamplerWrapper, and PGun.
Definition at line 79 of file JetScapeTask.h.
View newest version in sPHENIX GitHub at line 79 of file JetScapeTask.h
Referenced by Jetscape::SoftParticlization::Init(), and Jetscape::InitialState::Init().
void Jetscape::JetScapeTask::InitTasks () virtual
Recursive initialization of all the subtasks of the JetScapeTask. Subtasks are also of type JetScapeTask such as Pythia Gun, Trento, Energy Loss Matter and Martini etc.
Definition at line 45 of file JetScapeTask.cc.
View newest version in sPHENIX GitHub at line 45 of file JetScapeTask.cc
References it, and VERBOSE.
Referenced by Jetscape::JetScape::Init(), and Jetscape::InitialState::Init().
void Jetscape::JetScapeTask::ResizeTaskList (int i) inline
This function resizes the length of the vector of tasks to "i". If "i" is less than the current size, it will keep the first i elements of the vector of the tasks of a JetScapeTask.
Definition at line 160 of file JetScapeTask.h.
View newest version in sPHENIX GitHub at line 160 of file JetScapeTask.h
References tasks.
void Jetscape::JetScapeTask::SetActive (bool m_active_exec) inline
This functions sets the flag "active_exec" to true (active) or false(deactive).
Definition at line 176 of file JetScapeTask.h.
View newest version in sPHENIX GitHub at line 176 of file JetScapeTask.h
References active_exec.
void Jetscape::JetScapeTask::SetId (string m_id) inline
This function sets the string "id" of the task of a JetScapeTask.
Definition at line 182 of file JetScapeTask.h.
View newest version in sPHENIX GitHub at line 182 of file JetScapeTask.h
Referenced by AdSCFT::AdSCFT(), Jetscape::Afterburner::Afterburner(), Brick::Brick(), Glasma::Glasma(), GubserHydro::GubserHydro(), Jetscape::HadronPrinter::Init(), InitialFromFile::InitialFromFile(), Jetscape::InitialState::InitialState(), IPGlasmaWrapper::IPGlasmaWrapper(), Jetscape::JetScape::JetScape(), Jetscape::JetScapeWriter::JetScapeWriter(), Jetscape::JetScapeWriterHepMC::JetScapeWriterHepMC(), Jetscape::JetScapeWriterRootHepMC::JetScapeWriterRootHepMC(), NcollListFromFile::NcollListFromFile(), NullPreDynamics::NullPreDynamics(), PGun::PGun(), and Jetscape::TrentoInitial::TrentoInitial().
void Jetscape::JetScapeTask::SetMutex (shared_ptr< JetScapeModuleMutex > m_mutex) inline
This function sets the "mutex" of a JetScapeTask.
Definition at line 194 of file JetScapeTask.h.
View newest version in sPHENIX GitHub at line 194 of file JetScapeTask.h
References mutex.
Referenced by AdSCFT::AdSCFT().
virtual void Jetscape::JetScapeTask::WriteTask (weak_ptr< JetScapeWriter > w) inline virtual
A virtual function to define a default WriteTask() function for a JetScapeTask. It can be overridden by different modules/tasks. Current setup: Every task gets handed a pointer to the writer and can add any information it likes to it (using predefined functions like WriteComment()) This is maximally flexible but makes it difficult to properly store information for a variety of outputs. E.g., sigmaGen: A HardProcess can easily write the xsec to any stream-type output using WriteComment. But to set it in a HepMC file, either HardProcess needs to make a case-by-case selection, meaning a new file format would need to percolate through multiple base classes, or the writer needs to know this information and implement WriteEvent appropriately. The latter is obviously better, but it's non-trivial to collect this information.
Reimplemented in Martini, SmashWrapper, Jetscape::JetEnergyLoss, Jetscape::JetEnergyLossManager, Jetscape::HardProcess, LBT, AdSCFT, iSpectraSamplerWrapper, Jetscape::HadronPrinter, Jetscape::Hadronization, Jetscape::HadronizationManager, HybridHadronization, Matter, ColorlessHadronization, ColoredHadronization, and ElossValidate.
Definition at line 123 of file JetScapeTask.h.
View newest version in sPHENIX GitHub at line 123 of file JetScapeTask.h
void Jetscape::JetScapeTask::WriteTasks (weak_ptr< JetScapeWriter > w) virtual
Recursively write the output information of different tasks/subtasks of a JetScapeTask into a file. We use "active_exec" flag to decide whether to write the output in the file or not.
Definition at line 72 of file JetScapeTask.cc.
View newest version in sPHENIX GitHub at line 72 of file JetScapeTask.cc
References it.
Referenced by Jetscape::JetScape::Exec(), and Jetscape::HadronPrinter::WriteTask().
Member Data Documentation
bool Jetscape::JetScapeTask::active_exec private
Definition at line 201 of file JetScapeTask.h.
View newest version in sPHENIX GitHub at line 201 of file JetScapeTask.h
Referenced by GetActive(), and SetActive().
string Jetscape::JetScapeTask::id private
Definition at line 202 of file JetScapeTask.h.
View newest version in sPHENIX GitHub at line 202 of file JetScapeTask.h
Referenced by GetId().
shared_ptr<JetScapeModuleMutex> Jetscape::JetScapeTask::mutex private
Definition at line 206 of file JetScapeTask.h.
View newest version in sPHENIX GitHub at line 206 of file JetScapeTask.h
Referenced by GetMutex(), and SetMutex().
int Jetscape::JetScapeTask::my_task_number_ private
Definition at line 205 of file JetScapeTask.h.
View newest version in sPHENIX GitHub at line 205 of file JetScapeTask.h
Referenced by GetMyTaskNumber().
vector<shared_ptr<JetScapeTask> > Jetscape::JetScapeTask::tasks private
Definition at line 198 of file JetScapeTask.h.
View newest version in sPHENIX GitHub at line 198 of file JetScapeTask.h
Referenced by ClearTaskList(), EraseTaskAt(), EraseTaskLast(), GetNumberOfTasks(), GetTaskAt(), GetTaskList(), and ResizeTaskList().
The documentation for this class was generated from the following files:
JETSCAPE/blob/main/src/framework/JetScapeTask.h
JETSCAPE/blob/main/src/framework/JetScapeTask.cc