Analysis Software: acts/blob/sPHENIX/Tests/UnitTests/Plugins/Json/VolumeBoundsJsonConverterTests.cpp File Reference
VolumeBoundsJsonConverterTests.cpp File Reference
#include <boost/test/unit_test.hpp>
#include "Acts/Definitions/Algebra.hpp"
#include "Acts/Definitions/Units.hpp"
#include "Acts/Geometry/ConeVolumeBounds.hpp"
#include "Acts/Geometry/CuboidVolumeBounds.hpp"
#include "Acts/Geometry/CutoutCylinderVolumeBounds.hpp"
#include "Acts/Geometry/CylinderVolumeBounds.hpp"
#include "Acts/Geometry/GenericCuboidVolumeBounds.hpp"
#include "Acts/Geometry/TrapezoidVolumeBounds.hpp"
#include "Acts/Plugins/Json/VolumeBoundsJsonConverter.hpp"
#include <algorithm>
#include <array>
#include <cmath>
#include <fstream>
#include <memory>
#include <string>
#include <vector>
#include <nlohmann/json.hpp>
Functions
BOOST_AUTO_TEST_CASE (Cuboid)
BOOST_AUTO_TEST_CASE (Cylinder)
BOOST_AUTO_TEST_CASE (Cone)
BOOST_AUTO_TEST_CASE (CutoutCylinder)
BOOST_AUTO_TEST_CASE (GenericCuboid)
BOOST_AUTO_TEST_CASE (Trapezoid)
Function Documentation
BOOST_AUTO_TEST_CASE (Cuboid)
Definition at line 35 of file VolumeBoundsJsonConverterTests.cpp.
View newest version in sPHENIX GitHub at line 35 of file VolumeBoundsJsonConverterTests.cpp
References in, out, and Acts::VolumeBoundsJsonConverter::toJson().
BOOST_AUTO_TEST_CASE (Cylinder)
Definition at line 56 of file VolumeBoundsJsonConverterTests.cpp.
View newest version in sPHENIX GitHub at line 56 of file VolumeBoundsJsonConverterTests.cpp
References in, out, and Acts::VolumeBoundsJsonConverter::toJson().
BOOST_AUTO_TEST_CASE (Cone)
Definition at line 78 of file VolumeBoundsJsonConverterTests.cpp.
View newest version in sPHENIX GitHub at line 78 of file VolumeBoundsJsonConverterTests.cpp
References in, out, and Acts::VolumeBoundsJsonConverter::toJson().
BOOST_AUTO_TEST_CASE (CutoutCylinder)
Definition at line 99 of file VolumeBoundsJsonConverterTests.cpp.
View newest version in sPHENIX GitHub at line 99 of file VolumeBoundsJsonConverterTests.cpp
References in, out, and Acts::VolumeBoundsJsonConverter::toJson().
BOOST_AUTO_TEST_CASE (GenericCuboid)
Definition at line 123 of file VolumeBoundsJsonConverterTests.cpp.
View newest version in sPHENIX GitHub at line 123 of file VolumeBoundsJsonConverterTests.cpp
References Acts::VolumeBoundsJsonConverter::fromJson(), in, out, Acts::VolumeBoundsJsonConverter::toJson(), and ActsExamples::HepMC3Event::vertices().
BOOST_AUTO_TEST_CASE (Trapezoid)
Definition at line 154 of file VolumeBoundsJsonConverterTests.cpp.
View newest version in sPHENIX GitHub at line 154 of file VolumeBoundsJsonConverterTests.cpp
References in, out, and Acts::VolumeBoundsJsonConverter::toJson().