Analysis Software: ElectronPid Class Reference
ElectronPid Class Reference
#include <analysis/blob/master/TrackPid/src/ElectronPid.h>
Public Member Functions
ElectronPid (const std::string &name="ElectronPid", const std::string &filename="_ElectronPid.root")
virtual ~ElectronPid ()
int Init (PHCompositeNode *topNode)
int InitRun (PHCompositeNode *topNode)
int process_event (PHCompositeNode *topNode)
int End (PHCompositeNode *topNode)
Called at the end of all processing.
void setEMOPcutlimits (float EMOPlowerlimit, float EMOPhigherlimit)
Set the cemce3x3/p cut limits for electrons; default: 0.0<cemce3x3/p<100.0, means without cuts.
void setHinOEMcutlimit (float HinOEMhigherlimit)
Set the hcaline3x3/cemce3x3 cut limit for electrons; default: hcaline3x3/cemce3x3<100.0, means without cut.
void setPtcutlimit (float Ptlowerlimit, float Pthigherlimit)
Set the pt cut limit for Upsilon decay electrons; default: 0.0<pt<100.0 GeV, means without cut.
void setHOPcutlimit (float HOPlowerlimit)
Set the (hcaline3x3+hcaloute3x3)/p cut lower limit for hadrons; default: 0.0<(hcaline3x3+hcaloute3x3)/p, means without cut.
void setTrackcutlimits (int Nmvtxlowerlimit, int Ninttlowerlimit, int Ntpclowerlimit, int Nqualityhigherlimit)
Set the track cut limits; default: nmvtx>=0, nintt>=0, ntpc>=0; quality<100.
void set_output_ntuple (bool outputntuple)
Public Member Functions inherited from SubsysReco
~SubsysReco () override
virtual int EndRun (const int)
Called at the end of each run.
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
void Print (const std::string &what="ALL") const override
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Protected Attributes
bool output_ntuple
TFile * OutputNtupleFile
std::string OutputFileName
TNtuple * ntpbeforecut
TNtuple * ntpcutEMOP
TNtuple * ntpcutEMOP_HinOEM
TNtuple * ntpcutEMOP_HinOEM_Pt
TNtuple * ntpcutEMOP_HinOEM_Pt_read
TNtuple * ntpcutHOP
int EventNumber
Private Member Functions
int GetNodes (PHCompositeNode *topNode)
fetch node pointers
Private Attributes
TrackPidAssoc * _track_pid_assoc
SvtxTrackMap * _track_map
float EMOP_lowerlimit
A float lower limit for cutting on cemce3x3/p.
float EMOP_higherlimit
A float higher limit for cutting on cemce3x3/p.
float HinOEM_higherlimit
A float higher limit for cutting on hcaline3x3/cemce3x3.
float Pt_lowerlimit
A float lower limit for cutting on pt.
float Pt_higherlimit
A float higher limit for cutting on pt.
float HOP_lowerlimit
A float lower limit for cutting on (hcaline3x3+hcaloute3x3)/p.
int Nmvtx_lowerlimit
A float lower limit for cutting on nmvtx.
int Nintt_lowerlimit
A float lower limit for cutting on nintt.
int Ntpc_lowerlimit
A float lower limit for cutting on ntpc.
int Nquality_higherlimit
A float higher limit for cutting on quality.
unsigned int _nlayers_maps = 3
unsigned int _nlayers_intt = 4
unsigned int _nlayers_tpc = 48
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = INT_MAX - 10
}
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Detailed Description
Definition at line 33 of file ElectronPid.h.
View newest version in sPHENIX GitHub at line 33 of file ElectronPid.h
Constructor & Destructor Documentation
ElectronPid::ElectronPid (const std::string & name = "ElectronPid", const std::string & filename = "_ElectronPid.root")
default limits
Definition at line 51 of file ElectronPid.cc.
View newest version in sPHENIX GitHub at line 51 of file ElectronPid.cc
References EMOP_higherlimit, EMOP_lowerlimit, EventNumber, filename, HinOEM_higherlimit, HOP_lowerlimit, Nintt_lowerlimit, Nmvtx_lowerlimit, Nquality_higherlimit, Ntpc_lowerlimit, output_ntuple, OutputFileName, OutputNtupleFile, Pt_higherlimit, and Pt_lowerlimit.
ElectronPid::~ElectronPid () virtual
Definition at line 75 of file ElectronPid.cc.
View newest version in sPHENIX GitHub at line 75 of file ElectronPid.cc
Member Function Documentation
int ElectronPid::End (PHCompositeNode *) virtual
Called at the end of all processing.
Reimplemented from SubsysReco.
Definition at line 407 of file ElectronPid.cc.
View newest version in sPHENIX GitHub at line 407 of file ElectronPid.cc
References cd(), testing::internal::posix::Close(), Fun4AllReturnCodes::EVENT_OK, output_ntuple, OutputNtupleFile, and testing::internal::posix::Write().
int ElectronPid::GetNodes (PHCompositeNode * topNode) private
fetch node pointers
Definition at line 370 of file ElectronPid.cc.
View newest version in sPHENIX GitHub at line 370 of file ElectronPid.cc
References _track_map, _track_pid_assoc, Fun4AllReturnCodes::ABORTEVENT, PHCompositeNode::addNode(), Fun4AllReturnCodes::EVENT_OK, PHNodeIterator::findFirst(), PHWHERE, and Fun4AllBase::Verbosity().
Referenced by InitRun().
int ElectronPid::Init (PHCompositeNode *) virtual
Called during initialization. Typically this is where you can book histograms, and e.g. register them to Fun4AllServer (so they can be output to file using Fun4AllServer::dumpHistos() method).
Reimplemented from SubsysReco.
Definition at line 79 of file ElectronPid.cc.
View newest version in sPHENIX GitHub at line 79 of file ElectronPid.cc
References Fun4AllReturnCodes::ABORTEVENT, Fun4AllReturnCodes::EVENT_OK, PHNodeIterator::findFirst(), ntpbeforecut, ntpcutEMOP, ntpcutEMOP_HinOEM, ntpcutEMOP_HinOEM_Pt, ntpcutEMOP_HinOEM_Pt_read, ntpcutHOP, output_ntuple, OutputFileName, OutputNtupleFile, and PHWHERE.
int ElectronPid::InitRun (PHCompositeNode *) virtual
Called for first event when run number is known. Typically this is where you may want to fetch data from database, because you know the run number.
Reimplemented from SubsysReco.
Definition at line 108 of file ElectronPid.cc.
View newest version in sPHENIX GitHub at line 108 of file ElectronPid.cc
References Fun4AllReturnCodes::EVENT_OK, and GetNodes().
int ElectronPid::process_event (PHCompositeNode *) virtual
Called for each event. This is where you do the real work.
Reimplemented from SubsysReco.
Definition at line 116 of file ElectronPid.cc.
View newest version in sPHENIX GitHub at line 116 of file ElectronPid.cc
References _nlayers_intt, _nlayers_maps, _nlayers_tpc, _track_map, _track_pid_assoc, Fun4AllReturnCodes::ABORTEVENT, TrackPidAssoc::addAssoc(), SvtxTrackMap::begin(), SvtxTrack::begin_cluster_keys(), RawTowerDefs::CEMC, charge, TrackPidAssoc::electron, EMOP_higherlimit, EMOP_lowerlimit, SvtxTrackMap::end(), SvtxTrack::end_cluster_keys(), Fun4AllReturnCodes::EVENT_OK, EventNumber, Fill(), SvtxTrackMap::get(), SvtxTrack::get_cal_cluster_e(), SvtxTrack::get_cal_energy_3x3(), SvtxTrack::get_charge(), SvtxTrack::get_p(), SvtxTrack::get_px(), SvtxTrack::get_py(), SvtxTrack::get_quality(), SvtxTrack::get_vertex_id(), SvtxTrack::get_z(), TrkrDefs::getLayer(), TrackPidAssoc::getTracks(), TrackPidAssoc::hadron, RawTowerDefs::HCALIN, RawTowerDefs::HCALOUT, HinOEM_higherlimit, HOP_lowerlimit, it, layer, Nintt_lowerlimit, Nmvtx_lowerlimit, ntpbeforecut, Ntpc_lowerlimit, ntpcutEMOP, ntpcutEMOP_HinOEM, ntpcutEMOP_HinOEM_Pt, ntpcutEMOP_HinOEM_Pt_read, ntpcutHOP, output_ntuple, p, PHWHERE, pid, Pt_higherlimit, Pt_lowerlimit, Fun4AllBase::Verbosity(), and z.
void ElectronPid::set_output_ntuple (bool outputntuple) inline
Definition at line 65 of file ElectronPid.h.
View newest version in sPHENIX GitHub at line 65 of file ElectronPid.h
References output_ntuple.
Referenced by run(), and runpairs().
void ElectronPid::setEMOPcutlimits (float EMOPlowerlimit, float EMOPhigherlimit) inline
Set the cemce3x3/p cut limits for electrons; default: 0.0<cemce3x3/p<100.0, means without cuts.
Definition at line 45 of file ElectronPid.h.
View newest version in sPHENIX GitHub at line 45 of file ElectronPid.h
References EMOP_higherlimit, and EMOP_lowerlimit.
Referenced by run(), and runpairs().
void ElectronPid::setHinOEMcutlimit (float HinOEMhigherlimit) inline
Set the hcaline3x3/cemce3x3 cut limit for electrons; default: hcaline3x3/cemce3x3<100.0, means without cut.
Definition at line 48 of file ElectronPid.h.
View newest version in sPHENIX GitHub at line 48 of file ElectronPid.h
References HinOEM_higherlimit.
Referenced by run().
void ElectronPid::setHOPcutlimit (float HOPlowerlimit) inline
Set the (hcaline3x3+hcaloute3x3)/p cut lower limit for hadrons; default: 0.0<(hcaline3x3+hcaloute3x3)/p, means without cut.
Definition at line 54 of file ElectronPid.h.
View newest version in sPHENIX GitHub at line 54 of file ElectronPid.h
References HOP_lowerlimit.
Referenced by run(), and runpairs().
void ElectronPid::setPtcutlimit (float Ptlowerlimit, float Pthigherlimit) inline
Set the pt cut limit for Upsilon decay electrons; default: 0.0<pt<100.0 GeV, means without cut.
Definition at line 51 of file ElectronPid.h.
View newest version in sPHENIX GitHub at line 51 of file ElectronPid.h
References Pt_higherlimit, and Pt_lowerlimit.
Referenced by run(), and runpairs().
void ElectronPid::setTrackcutlimits (int Nmvtxlowerlimit, int Ninttlowerlimit, int Ntpclowerlimit, int Nqualityhigherlimit) inline
Set the track cut limits; default: nmvtx>=0, nintt>=0, ntpc>=0; quality<100.
Definition at line 57 of file ElectronPid.h.
View newest version in sPHENIX GitHub at line 57 of file ElectronPid.h
References Nintt_lowerlimit, Nmvtx_lowerlimit, Nquality_higherlimit, and Ntpc_lowerlimit.
Referenced by run().
Member Data Documentation
unsigned int ElectronPid::_nlayers_intt = 4 private
Definition at line 118 of file ElectronPid.h.
View newest version in sPHENIX GitHub at line 118 of file ElectronPid.h
Referenced by process_event().
unsigned int ElectronPid::_nlayers_maps = 3 private
Definition at line 117 of file ElectronPid.h.
View newest version in sPHENIX GitHub at line 117 of file ElectronPid.h
Referenced by process_event().
unsigned int ElectronPid::_nlayers_tpc = 48 private
Definition at line 119 of file ElectronPid.h.
View newest version in sPHENIX GitHub at line 119 of file ElectronPid.h
Referenced by process_event().
SvtxTrackMap* ElectronPid::_track_map private
Definition at line 87 of file ElectronPid.h.
View newest version in sPHENIX GitHub at line 87 of file ElectronPid.h
Referenced by GetNodes(), and process_event().
TrackPidAssoc* ElectronPid::_track_pid_assoc private
Definition at line 86 of file ElectronPid.h.
View newest version in sPHENIX GitHub at line 86 of file ElectronPid.h
Referenced by GetNodes(), and process_event().
float ElectronPid::EMOP_higherlimit private
A float higher limit for cutting on cemce3x3/p.
Definition at line 92 of file ElectronPid.h.
View newest version in sPHENIX GitHub at line 92 of file ElectronPid.h
Referenced by ElectronPid(), process_event(), and setEMOPcutlimits().
float ElectronPid::EMOP_lowerlimit private
A float lower limit for cutting on cemce3x3/p.
Definition at line 90 of file ElectronPid.h.
View newest version in sPHENIX GitHub at line 90 of file ElectronPid.h
Referenced by ElectronPid(), process_event(), and setEMOPcutlimits().
int ElectronPid::EventNumber protected
Definition at line 80 of file ElectronPid.h.
View newest version in sPHENIX GitHub at line 80 of file ElectronPid.h
Referenced by ElectronPid(), and process_event().
float ElectronPid::HinOEM_higherlimit private
A float higher limit for cutting on hcaline3x3/cemce3x3.
Definition at line 95 of file ElectronPid.h.
View newest version in sPHENIX GitHub at line 95 of file ElectronPid.h
Referenced by ElectronPid(), process_event(), and setHinOEMcutlimit().
float ElectronPid::HOP_lowerlimit private
A float lower limit for cutting on (hcaline3x3+hcaloute3x3)/p.
Definition at line 103 of file ElectronPid.h.
View newest version in sPHENIX GitHub at line 103 of file ElectronPid.h
Referenced by ElectronPid(), process_event(), and setHOPcutlimit().
int ElectronPid::Nintt_lowerlimit private
A float lower limit for cutting on nintt.
Definition at line 109 of file ElectronPid.h.
View newest version in sPHENIX GitHub at line 109 of file ElectronPid.h
Referenced by ElectronPid(), process_event(), and setTrackcutlimits().
int ElectronPid::Nmvtx_lowerlimit private
A float lower limit for cutting on nmvtx.
Definition at line 106 of file ElectronPid.h.
View newest version in sPHENIX GitHub at line 106 of file ElectronPid.h
Referenced by ElectronPid(), process_event(), and setTrackcutlimits().
int ElectronPid::Nquality_higherlimit private
A float higher limit for cutting on quality.
Definition at line 115 of file ElectronPid.h.
View newest version in sPHENIX GitHub at line 115 of file ElectronPid.h
Referenced by ElectronPid(), and setTrackcutlimits().
TNtuple* ElectronPid::ntpbeforecut protected
Definition at line 72 of file ElectronPid.h.
View newest version in sPHENIX GitHub at line 72 of file ElectronPid.h
Referenced by Init(), and process_event().
int ElectronPid::Ntpc_lowerlimit private
A float lower limit for cutting on ntpc.
Definition at line 112 of file ElectronPid.h.
View newest version in sPHENIX GitHub at line 112 of file ElectronPid.h
Referenced by ElectronPid(), process_event(), and setTrackcutlimits().
TNtuple* ElectronPid::ntpcutEMOP protected
Definition at line 73 of file ElectronPid.h.
View newest version in sPHENIX GitHub at line 73 of file ElectronPid.h
Referenced by Init(), and process_event().
TNtuple* ElectronPid::ntpcutEMOP_HinOEM protected
Definition at line 74 of file ElectronPid.h.
View newest version in sPHENIX GitHub at line 74 of file ElectronPid.h
Referenced by Init(), and process_event().
TNtuple* ElectronPid::ntpcutEMOP_HinOEM_Pt protected
Definition at line 75 of file ElectronPid.h.
View newest version in sPHENIX GitHub at line 75 of file ElectronPid.h
Referenced by Init(), and process_event().
TNtuple* ElectronPid::ntpcutEMOP_HinOEM_Pt_read protected
Definition at line 76 of file ElectronPid.h.
View newest version in sPHENIX GitHub at line 76 of file ElectronPid.h
Referenced by Init(), and process_event().
TNtuple* ElectronPid::ntpcutHOP protected
Definition at line 78 of file ElectronPid.h.
View newest version in sPHENIX GitHub at line 78 of file ElectronPid.h
Referenced by Init(), and process_event().
bool ElectronPid::output_ntuple protected
Definition at line 68 of file ElectronPid.h.
View newest version in sPHENIX GitHub at line 68 of file ElectronPid.h
Referenced by ElectronPid(), End(), Init(), process_event(), and set_output_ntuple().
std::string ElectronPid::OutputFileName protected
Definition at line 71 of file ElectronPid.h.
View newest version in sPHENIX GitHub at line 71 of file ElectronPid.h
Referenced by ElectronPid(), and Init().
TFile* ElectronPid::OutputNtupleFile protected
Definition at line 70 of file ElectronPid.h.
View newest version in sPHENIX GitHub at line 70 of file ElectronPid.h
Referenced by ElectronPid(), End(), and Init().
float ElectronPid::Pt_higherlimit private
A float higher limit for cutting on pt.
Definition at line 100 of file ElectronPid.h.
View newest version in sPHENIX GitHub at line 100 of file ElectronPid.h
Referenced by ElectronPid(), process_event(), and setPtcutlimit().
float ElectronPid::Pt_lowerlimit private
A float lower limit for cutting on pt.
Definition at line 98 of file ElectronPid.h.
View newest version in sPHENIX GitHub at line 98 of file ElectronPid.h
Referenced by ElectronPid(), process_event(), and setPtcutlimit().
The documentation for this class was generated from the following files:
analysis/blob/master/TrackPid/src/ElectronPid.h
analysis/blob/master/TrackPid/src/ElectronPid.cc