Analysis Software: PHG4InEvent Class Reference
PHG4InEvent Class Reference
#include <coresoftware/blob/master/simulation/g4simulation/g4main/PHG4InEvent.h>
Public Member Functions
PHG4InEvent ()
~PHG4InEvent () override
void identify (std::ostream &os=std::cout) const override
void Reset () override
Clear Event.
int AddVtxHepMC (const int id, const double x, const double y, const double z, const double t)
int AddVtx (const double x, const double y, const double z, const double t)
int AddVtx (const int id, const PHG4VtxPoint &)
int AddParticle (const int vtxid, PHG4Particle *particle)
void AddEmbeddedParticle (PHG4Particle *particle, int flag)
std::pair< std::map< int,
PHG4VtxPoint * >
::const_iterator, std::map
< int, PHG4VtxPoint * >
::const_iterator > GetVertices () const
std::pair< std::multimap< int,
PHG4Particle * >
::const_iterator,
std::multimap< int,
PHG4Particle * >
::const_iterator > GetParticles (const int vtxid) const
std::pair< std::multimap< int,
PHG4Particle * >
::const_iterator,
std::multimap< int,
PHG4Particle * >
::const_iterator > GetParticles () const
std::pair< std::multimap< int,
PHG4Particle * >::iterator,
std::multimap< int,
PHG4Particle * >::iterator > GetParticles_Modify ()
std::pair< std::map
< PHG4Particle *, int >
::const_iterator, std::map
< PHG4Particle *, int >
::const_iterator > GetEmbeddedParticles () const
int isEmbeded (PHG4Particle *) const
int GetNEmbedded () const
int GetNVtx () const
void DeleteParticle (std::multimap< int, PHG4Particle * >::iterator &iter)
Public Member Functions inherited from PHObject
PHObject ()
ctor
~PHObject () override
dtor
virtual PHObject * CloneMe () const
Virtual copy constructor.
virtual PHObject * clone () const final
PHObject * Clone (const char *newname="") const final
void Copy (TObject &object) const final
virtual int isValid () const
isValid returns non zero if object contains vailid data
virtual int Integrate () const
virtual int Integrate (PHObject *)
virtual void CopyFrom (const PHObject *obj)
Protected Member Functions
int AddVtxCommon (PHG4VtxPoint *newvtx)
Protected Attributes
std::map< int, PHG4VtxPoint * > vtxlist
std::multimap< int,
PHG4Particle * > particlelist
std::map< PHG4Particle *, int > embedded_particlelist
Detailed Description
Definition at line 15 of file PHG4InEvent.h.
View newest version in sPHENIX GitHub at line 15 of file PHG4InEvent.h
Constructor & Destructor Documentation
PHG4InEvent::PHG4InEvent () inline
Definition at line 18 of file PHG4InEvent.h.
View newest version in sPHENIX GitHub at line 18 of file PHG4InEvent.h
PHG4InEvent::~PHG4InEvent () override
Definition at line 12 of file PHG4InEvent.cc.
View newest version in sPHENIX GitHub at line 12 of file PHG4InEvent.cc
Member Function Documentation
void PHG4InEvent::AddEmbeddedParticle (PHG4Particle * particle, int flag) inline
Definition at line 28 of file PHG4InEvent.h.
View newest version in sPHENIX GitHub at line 28 of file PHG4InEvent.h
References embedded_particlelist.
Referenced by PHG4ParticleGeneratorD0::process_event(), HepMCNodeReader::process_event(), PHG4ParticleGeneratorVectorMeson::process_event(), PHG4SimpleEventGenerator::process_event(), and PHG4ParticleGeneratorBase::SetParticleId().
int PHG4InEvent::AddParticle (const int vtxid, PHG4Particle * particle)
Definition at line 82 of file PHG4InEvent.cc.
View newest version in sPHENIX GitHub at line 82 of file PHG4InEvent.cc
Referenced by PHG4ParticleGun::process_event(), PHG4InEventReadBack::process_event(), PHG4IonGun::process_event(), PHG4ParticleGenerator::process_event(), PHG4ParticleGeneratorD0::process_event(), CosmicSpray::process_event(), HepMCNodeReader::process_event(), PHG4SimpleEventGenerator::process_event(), and PHG4ParticleGeneratorVectorMeson::process_event().
int PHG4InEvent::AddVtx (const double x, const double y, const double z, const double t = NAN)
Definition at line 37 of file PHG4InEvent.cc.
View newest version in sPHENIX GitHub at line 37 of file PHG4InEvent.cc
Referenced by PHG4ParticleGun::process_event(), PHG4InEventReadBack::process_event(), PHG4IonGun::process_event(), PHG4ParticleGenerator::process_event(), PHG4ParticleGeneratorD0::process_event(), CosmicSpray::process_event(), HepMCNodeReader::process_event(), PHG4SimpleEventGenerator::process_event(), and PHG4ParticleGeneratorVectorMeson::process_event().
int PHG4InEvent::AddVtx (const int id, const PHG4VtxPoint & vtx)
Definition at line 21 of file PHG4InEvent.cc.
View newest version in sPHENIX GitHub at line 21 of file PHG4InEvent.cc
int PHG4InEvent::AddVtxCommon (PHG4VtxPoint * newvtx) protected
Do a simultaneous relative + absolute floating point comparison for the vertex four vectors make the distance comparison 1 micron, time comparison 0.1 ps
Definition at line 45 of file PHG4InEvent.cc.
View newest version in sPHENIX GitHub at line 45 of file PHG4InEvent.cc
References PHG4VtxPoint::get_t(), PHG4VtxPoint::get_x(), PHG4VtxPoint::get_y(), PHG4VtxPoint::get_z(), train_ambiguity_solver::id, and tlist.
int PHG4InEvent::AddVtxHepMC (const int id, const double x, const double y, const double z, const double t = NAN)
Definition at line 29 of file PHG4InEvent.cc.
View newest version in sPHENIX GitHub at line 29 of file PHG4InEvent.cc
References train_ambiguity_solver::id.
void PHG4InEvent::DeleteParticle (std::multimap< int, PHG4Particle * >::iterator & iter)
Definition at line 195 of file PHG4InEvent.cc.
View newest version in sPHENIX GitHub at line 195 of file PHG4InEvent.cc
Referenced by PHG4InputFilter::process_event().
std::pair< std::map<PHG4Particle *,int>::const_iterator, std::map<PHG4Particle *,int>::const_iterator> PHG4InEvent::GetEmbeddedParticles () const inline
Definition at line 35 of file PHG4InEvent.h.
View newest version in sPHENIX GitHub at line 35 of file PHG4InEvent.h
References embedded_particlelist.
int PHG4InEvent::GetNEmbedded () const inline
Definition at line 38 of file PHG4InEvent.h.
View newest version in sPHENIX GitHub at line 38 of file PHG4InEvent.h
References embedded_particlelist.
int PHG4InEvent::GetNVtx () const inline
Definition at line 39 of file PHG4InEvent.h.
View newest version in sPHENIX GitHub at line 39 of file PHG4InEvent.h
References vtxlist.
Referenced by PHG4ParticleGeneratorBase::ReuseExistingVertex().
pair< multimap< int, PHG4Particle * >::const_iterator, multimap< int, PHG4Particle * >::const_iterator > PHG4InEvent::GetParticles (const int vtxid) const
Definition at line 132 of file PHG4InEvent.cc.
View newest version in sPHENIX GitHub at line 132 of file PHG4InEvent.cc
Referenced by PHG4InEventCompress::process_event(), PHG4ScoringManager::process_event(), and DumpPHG4InEvent::process_Node().
pair< multimap< int, PHG4Particle * >::const_iterator, multimap< int, PHG4Particle * >::const_iterator > PHG4InEvent::GetParticles () const
Definition at line 139 of file PHG4InEvent.cc.
View newest version in sPHENIX GitHub at line 139 of file PHG4InEvent.cc
pair< multimap< int, PHG4Particle * >::iterator, multimap< int, PHG4Particle * >::iterator > PHG4InEvent::GetParticles_Modify ()
Definition at line 146 of file PHG4InEvent.cc.
View newest version in sPHENIX GitHub at line 146 of file PHG4InEvent.cc
Referenced by PHG4InputFilter::process_event().
pair< map< int, PHG4VtxPoint * >::const_iterator, map< int, PHG4VtxPoint * >::const_iterator > PHG4InEvent::GetVertices () const
Definition at line 124 of file PHG4InEvent.cc.
View newest version in sPHENIX GitHub at line 124 of file PHG4InEvent.cc
Referenced by PHG4InEventCompress::process_event(), DumpPHG4InEvent::process_Node(), and PHG4ParticleGeneratorBase::ReuseExistingVertex().
void PHG4InEvent::identify (std::ostream & os = std::cout) const override virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from PHObject.
Definition at line 153 of file PHG4InEvent.cc.
View newest version in sPHENIX GitHub at line 153 of file PHG4InEvent.cc
References GetParticles(), and identify.
Referenced by PHG4ParticleGun::process_event(), PHG4InputFilter::process_event(), PHG4ParticleGenerator::process_event(), PHG4ParticleGeneratorD0::process_event(), HepMCNodeReader::process_event(), PHG4ParticleGeneratorVectorMeson::process_event(), PHG4SimpleEventGenerator::process_event(), and PHG4Reco::process_event().
int PHG4InEvent::isEmbeded (PHG4Particle * p) const
Definition at line 184 of file PHG4InEvent.cc.
View newest version in sPHENIX GitHub at line 184 of file PHG4InEvent.cc
void PHG4InEvent::Reset () override virtual
Clear Event.
Reimplemented from PHObject.
Definition at line 107 of file PHG4InEvent.cc.
View newest version in sPHENIX GitHub at line 107 of file PHG4InEvent.cc
Referenced by PHG4InEventReadBack::process_event().
Member Data Documentation
std::map<PHG4Particle *,int> PHG4InEvent::embedded_particlelist protected
Definition at line 47 of file PHG4InEvent.h.
View newest version in sPHENIX GitHub at line 47 of file PHG4InEvent.h
Referenced by AddEmbeddedParticle(), GetEmbeddedParticles(), and GetNEmbedded().
std::multimap<int,PHG4Particle *> PHG4InEvent::particlelist protected
Definition at line 46 of file PHG4InEvent.h.
View newest version in sPHENIX GitHub at line 46 of file PHG4InEvent.h
std::map<int,PHG4VtxPoint *> PHG4InEvent::vtxlist protected
Definition at line 45 of file PHG4InEvent.h.
View newest version in sPHENIX GitHub at line 45 of file PHG4InEvent.h
Referenced by GetNVtx().
The documentation for this class was generated from the following files:
coresoftware/blob/master/simulation/g4simulation/g4main/PHG4InEvent.h
coresoftware/blob/master/simulation/g4simulation/g4main/PHG4InEvent.cc