Analysis Software: noiPads Struct Reference
noiPads Struct Reference
#include <analysis/blob/master/JS-Jet/FastJetMedianBkg/src_JetMedianTree/macro/loc_lib/noiPads.h>
Public Member Functions
noiPads (int nYpads=1, vector< double > dimensions={}, int nXpads=1)
noiPads (vector< pair< noiPadDim, noiPadDim >> _pad_dimensions={{{},{}}}, int _canvas_width=0, int _canvas_height=0)
if (_canvas_height) canvas_height
void add_pad (pair< noiPadDim, noiPadDim > &coord)
void add_pad (vector< pair< noiPadDim, noiPadDim >> input)
void init ()
TPad * operator() (int row=0, int col=0)
void stamp (string msg, noiDict opt={}, noiDict dict={{"TextColor",(kGray+2),"TextSize", 16,"x-loc",.05,"y-loc",.05}})
void pdf (string string_with_dollar0, vector< string > other={})
Public Attributes
string prefix =""
int i_prefix =1
TCanvas * canvas = nullptr
vector< pair< noiPadDim,
noiPadDim > > pad_dimensions
vector< TPad * > pads
TPad * canvas_pad
int nRow {1}
int nCol {1}
int canvas_width { 1200 }
int canvas_height { 800 }
Detailed Description
Definition at line 151 of file noiPads.h.
View newest version in sPHENIX GitHub at line 151 of file noiPads.h
Constructor & Destructor Documentation
noiPads::noiPads (int nYpads = 1, vector< double > dimensions = {}, int nXpads = 1) inline
Definition at line 164 of file noiPads.h.
View newest version in sPHENIX GitHub at line 164 of file noiPads.h
noiPads::noiPads (vector< pair< noiPadDim, noiPadDim >> _pad_dimensions = {{{},{}}}, int _canvas_width = 0, int _canvas_height = 0) inline
Definition at line 216 of file noiPads.h.
View newest version in sPHENIX GitHub at line 216 of file noiPads.h
Member Function Documentation
void noiPads::add_pad (pair< noiPadDim, noiPadDim > & coord) inline
Definition at line 223 of file noiPads.h.
View newest version in sPHENIX GitHub at line 223 of file noiPads.h
References i, noiUniqueName(), merge_hashes::p, prefix, ambiguity_solver_full_chain::x, and y.
void noiPads::add_pad (vector< pair< noiPadDim, noiPadDim >> input) inline
Definition at line 253 of file noiPads.h.
View newest version in sPHENIX GitHub at line 253 of file noiPads.h
References digitization_config::input.
noiPads::if (_canvas_height)
void noiPads::init () inline
Definition at line 257 of file noiPads.h.
View newest version in sPHENIX GitHub at line 257 of file noiPads.h
References noiUniqueName(), and prefix.
TPad* noiPads::operator() (int row = 0, int col = 0) inline
Definition at line 272 of file noiPads.h.
View newest version in sPHENIX GitHub at line 272 of file noiPads.h
References col, and myAnalysis::init().
void noiPads::pdf (string string_with_dollar0, vector< string > other = {}) inline
Definition at line 305 of file noiPads.h.
View newest version in sPHENIX GitHub at line 305 of file noiPads.h
Referenced by init(), and initpythia().
void noiPads::stamp (string msg, noiDict opt = {}, noiDict dict = {{ "TextColor", (kGray+2), "TextSize", 16, "x-loc", .05, "y-loc", .05}}) inline
Definition at line 287 of file noiPads.h.
View newest version in sPHENIX GitHub at line 287 of file noiPads.h
Member Data Documentation
TCanvas* noiPads::canvas = nullptr
Definition at line 155 of file noiPads.h.
View newest version in sPHENIX GitHub at line 155 of file noiPads.h
int noiPads::canvas_height { 800 }
Definition at line 162 of file noiPads.h.
View newest version in sPHENIX GitHub at line 162 of file noiPads.h
TPad* noiPads::canvas_pad
Definition at line 158 of file noiPads.h.
View newest version in sPHENIX GitHub at line 158 of file noiPads.h
int noiPads::canvas_width { 1200 }
Definition at line 161 of file noiPads.h.
View newest version in sPHENIX GitHub at line 161 of file noiPads.h
int noiPads::i_prefix =1
Definition at line 154 of file noiPads.h.
View newest version in sPHENIX GitHub at line 154 of file noiPads.h
int noiPads::nCol {1}
Definition at line 160 of file noiPads.h.
View newest version in sPHENIX GitHub at line 160 of file noiPads.h
int noiPads::nRow {1}
Definition at line 159 of file noiPads.h.
View newest version in sPHENIX GitHub at line 159 of file noiPads.h
vector<pair<noiPadDim,noiPadDim> > noiPads::pad_dimensions
Definition at line 156 of file noiPads.h.
View newest version in sPHENIX GitHub at line 156 of file noiPads.h
vector<TPad*> noiPads::pads
Definition at line 157 of file noiPads.h.
View newest version in sPHENIX GitHub at line 157 of file noiPads.h
string noiPads::prefix =""
Definition at line 153 of file noiPads.h.
View newest version in sPHENIX GitHub at line 153 of file noiPads.h
The documentation for this struct was generated from the following file:
analysis/blob/master/JS-Jet/FastJetMedianBkg/src_JetMedianTree/macro/loc_lib/noiPads.h