Analysis Software: ActsExamples::TrackFittingAlgorithm Exception Reference
ActsExamples::TrackFittingAlgorithm Exception Reference final
#include <acts/blob/sPHENIX/Examples/Algorithms/TrackFitting/include/ActsExamples/TrackFitting/TrackFittingAlgorithm.hpp>
Classes
struct Config
Public Member Functions
TrackFittingAlgorithm (Config config, Acts::Logging::Level level)
ActsExamples::ProcessCode execute (const AlgorithmContext &ctx) const final
const Config & config () const
Get readonly access to the config parameters.
Public Member Functions inherited from ActsExamples::IAlgorithm
IAlgorithm (std::string name, Acts::Logging::Level level=Acts::Logging::INFO)
std::string name () const override
The algorithm name.
ProcessCode internalExecute (const AlgorithmContext &context) final
ProcessCode initialize () override
Initialize the algorithm.
ProcessCode finalize () override
Finalize the algorithm.
Private Attributes
Config m_cfg
ReadDataHandle
< MeasurementContainer > m_inputMeasurements
ReadDataHandle
< IndexSourceLinkContainer > m_inputSourceLinks
ReadDataHandle
< ProtoTrackContainer > m_inputProtoTracks
ReadDataHandle
< TrackParametersContainer > m_inputInitialTrackParameters
ReadDataHandle< ClusterContainer > m_inputClusters {this, "InputClusters"}
WriteDataHandle
< ConstTrackContainer > m_outputTracks {this, "OutputTracks"}
Additional Inherited Members
Protected Member Functions inherited from ActsExamples::IAlgorithm
const Acts::Logger & logger () const
Detailed Description
Definition at line 34 of file TrackFittingAlgorithm.hpp.
View newest version in sPHENIX GitHub at line 34 of file TrackFittingAlgorithm.hpp
Constructor & Destructor Documentation
ActsExamples::TrackFittingAlgorithm::TrackFittingAlgorithm (Config config, Acts::Logging::Level level)
Constructor of the fitting algorithm
Parameters
config is the config struct to configure the algorithm
level is the logging level
Definition at line 34 of file TrackFittingAlgorithm.cpp.
View newest version in sPHENIX GitHub at line 34 of file TrackFittingAlgorithm.cpp
References ActsExamples::TrackFittingAlgorithm::Config::calibrator, ActsExamples::WriteDataHandle< T >::initialize(), ActsExamples::ReadDataHandle< T >::initialize(), ActsExamples::TrackFittingAlgorithm::Config::inputClusters, ActsExamples::TrackFittingAlgorithm::Config::inputInitialTrackParameters, ActsExamples::TrackFittingAlgorithm::Config::inputMeasurements, ActsExamples::TrackFittingAlgorithm::Config::inputProtoTracks, ActsExamples::TrackFittingAlgorithm::Config::inputSourceLinks, m_cfg, m_inputClusters, m_inputInitialTrackParameters, m_inputMeasurements, m_inputProtoTracks, m_inputSourceLinks, m_outputTracks, ActsExamples::DataHandleBase::maybeInitialize(), and ActsExamples::TrackFittingAlgorithm::Config::outputTracks.
Member Function Documentation
const Config& ActsExamples::TrackFittingAlgorithm::config () const inline
Get readonly access to the config parameters.
Definition at line 70 of file TrackFittingAlgorithm.hpp.
View newest version in sPHENIX GitHub at line 70 of file TrackFittingAlgorithm.hpp
References m_cfg.
ActsExamples::ProcessCode ActsExamples::TrackFittingAlgorithm::execute (const AlgorithmContext & ctx) const final virtual
Framework execute method of the fitting algorithm
Parameters
ctx is the algorithm context that holds event-wise information
Returns
a process code to steer the algporithm flow
Implements ActsExamples::IAlgorithm.
Definition at line 69 of file TrackFittingAlgorithm.cpp.
View newest version in sPHENIX GitHub at line 69 of file TrackFittingAlgorithm.cpp
References ACTS_DEBUG, ACTS_FATAL, ACTS_VERBOSE, ACTS_WARNING, ActsExamples::AlgorithmContext::calibContext, clusters, ActsExamples::AlgorithmContext::geoContext, it, m_cfg(), ActsExamples::AlgorithmContext::magFieldContext, testing::internal::move(), ckf::options, pSurface, SUCCESS, and tracks().
Member Data Documentation
Config ActsExamples::TrackFittingAlgorithm::m_cfg private
Definition at line 73 of file TrackFittingAlgorithm.hpp.
View newest version in sPHENIX GitHub at line 73 of file TrackFittingAlgorithm.hpp
Referenced by config(), and TrackFittingAlgorithm().
ReadDataHandle<ClusterContainer> ActsExamples::TrackFittingAlgorithm::m_inputClusters {this, "InputClusters"} private
Definition at line 84 of file TrackFittingAlgorithm.hpp.
View newest version in sPHENIX GitHub at line 84 of file TrackFittingAlgorithm.hpp
Referenced by TrackFittingAlgorithm().
ReadDataHandle<TrackParametersContainer> ActsExamples::TrackFittingAlgorithm::m_inputInitialTrackParameters private
Initial value:
{
      this, "InputInitialTrackParameters"}
Definition at line 81 of file TrackFittingAlgorithm.hpp.
View newest version in sPHENIX GitHub at line 81 of file TrackFittingAlgorithm.hpp
Referenced by TrackFittingAlgorithm().
ReadDataHandle<MeasurementContainer> ActsExamples::TrackFittingAlgorithm::m_inputMeasurements private
Initial value:
{this,
                                                           "InputMeasurements"}
Definition at line 75 of file TrackFittingAlgorithm.hpp.
View newest version in sPHENIX GitHub at line 75 of file TrackFittingAlgorithm.hpp
Referenced by TrackFittingAlgorithm().
ReadDataHandle<ProtoTrackContainer> ActsExamples::TrackFittingAlgorithm::m_inputProtoTracks private
Initial value:
{this,
                                                         "InputProtoTracks"}
Definition at line 79 of file TrackFittingAlgorithm.hpp.
View newest version in sPHENIX GitHub at line 79 of file TrackFittingAlgorithm.hpp
Referenced by TrackFittingAlgorithm().
ReadDataHandle<IndexSourceLinkContainer> ActsExamples::TrackFittingAlgorithm::m_inputSourceLinks private
Initial value:
{
      this, "InputSourceLinks"}
Definition at line 77 of file TrackFittingAlgorithm.hpp.
View newest version in sPHENIX GitHub at line 77 of file TrackFittingAlgorithm.hpp
Referenced by TrackFittingAlgorithm().
WriteDataHandle<ConstTrackContainer> ActsExamples::TrackFittingAlgorithm::m_outputTracks {this, "OutputTracks"} private
Definition at line 86 of file TrackFittingAlgorithm.hpp.
View newest version in sPHENIX GitHub at line 86 of file TrackFittingAlgorithm.hpp
Referenced by TrackFittingAlgorithm().
The documentation for this exception was generated from the following files:
acts/blob/sPHENIX/Examples/Algorithms/TrackFitting/include/ActsExamples/TrackFitting/TrackFittingAlgorithm.hpp
acts/blob/sPHENIX/Examples/Algorithms/TrackFitting/src/TrackFittingAlgorithm.cpp