Analysis Software: Fatras::Scattering< formula_t > Struct Template Reference
Fatras::Scattering< formula_t > Struct Template Reference
#include <acts-fatras/blob/master/Core/include/Fatras/Physics/Scattering/Scattering.hpp>
Public Member Functions
template<typename generator_t , typename detector_t , typename particle_t >
std::vector< particle_t > operator() (generator_t &gen, const detector_t &det, particle_t &in) const
This is the scattering call operator.
Public Attributes
bool scattering = true
The flag to include scattering or not.
bool parametric = false
Include the log term.
double projectionFactor = 1. / std::sqrt(2.)
formula_t angle
The scattering formula.
Detailed Description
template<typename formula_t>
struct Fatras::Scattering< formula_t >
Definition at line 29 of file Scattering.hpp.
View newest version in sPHENIX GitHub at line 29 of file Scattering.hpp
Member Function Documentation
template<typename formula_t> template<typename generator_t , typename detector_t , typename particle_t > std::vector<particle_t> Fatras::Scattering< formula_t >::operator() (generator_t & gen, const detector_t & det, particle_t & in) const inline
This is the scattering call operator.
uniform distribution
Definition at line 43 of file Scattering.hpp.
View newest version in sPHENIX GitHub at line 43 of file Scattering.hpp
References Fatras::Scattering< formula_t >::angle, deltaPhi(), Acts::UnitConstants::e, Fatras::Scattering< formula_t >::parametric, ActsTests::PropagationDatasets::phi, Acts::VectorHelpers::phi(), Fatras::Scattering< formula_t >::projectionFactor, Fatras::Scattering< formula_t >::scattering, ActsTests::PropagationDatasets::theta, Acts::VectorHelpers::theta(), ambiguity_solver_full_chain::x, y, and physmon_track_finding_ttbar::z.
Member Data Documentation
template<typename formula_t> formula_t Fatras::Scattering< formula_t >::angle
The scattering formula.
Definition at line 39 of file Scattering.hpp.
View newest version in sPHENIX GitHub at line 39 of file Scattering.hpp
Referenced by Fatras::Scattering< formula_t >::operator()().
template<typename formula_t> bool Fatras::Scattering< formula_t >::parametric = false
Include the log term.
Definition at line 35 of file Scattering.hpp.
View newest version in sPHENIX GitHub at line 35 of file Scattering.hpp
Referenced by Fatras::Scattering< formula_t >::operator()().
template<typename formula_t> double Fatras::Scattering< formula_t >::projectionFactor = 1. / std::sqrt(2.)
Definition at line 36 of file Scattering.hpp.
View newest version in sPHENIX GitHub at line 36 of file Scattering.hpp
Referenced by Fatras::Scattering< formula_t >::operator()().
template<typename formula_t> bool Fatras::Scattering< formula_t >::scattering = true
The flag to include scattering or not.
Definition at line 32 of file Scattering.hpp.
View newest version in sPHENIX GitHub at line 32 of file Scattering.hpp
Referenced by Fatras::Scattering< formula_t >::operator()().
The documentation for this struct was generated from the following file:
acts-fatras/blob/master/Core/include/Fatras/Physics/Scattering/Scattering.hpp