Analysis Software: TrackSeedContainer_v1 Class Reference
TrackSeedContainer_v1 Class Reference
#include <coresoftware/blob/master/offline/packages/trackbase_historic/TrackSeedContainer_v1.h>
Public Member Functions
TrackSeedContainer_v1 ()
TrackSeedContainer_v1 (const TrackSeedContainer_v1 &trackmap)
TrackSeedContainer_v1 & operator= (const TrackSeedContainer_v1 &seedContainer)
~TrackSeedContainer_v1 () override
void identify (std::ostream &os=std::cout) const override
void Reset () override
Clear Event.
int isValid () const override
isValid returns non zero if object contains vailid data
PHObject * CloneMe () const override
Virtual copy constructor.
bool empty () const override
std::size_t size () const override
void clear () override
const TrackSeed * get (const std::size_t key) const override
TrackSeed * get (const std::size_t key) override
TrackSeed * insert (const TrackSeed *seed) override
void erase (const std::size_t key) override
std::size_t index (ConstIter it) const override
std::size_t index (Iter it) const override
ConstIter begin () const override
ConstIter find (const std::size_t key) const override
std::size_t find (const TrackSeed *) const override
ConstIter end () const override
Iter begin () override
Iter find (const std::size_t key) override
std::size_t find (const TrackSeed *) override
Iter end () override
Public Member Functions inherited from TrackSeedContainer
~TrackSeedContainer () override
Public Member Functions inherited from PHObject
PHObject ()
ctor
~PHObject () override
dtor
virtual PHObject * clone () const final
PHObject * Clone (const char *newname="") const final
void Copy (TObject &object) const final
virtual int Integrate () const
virtual int Integrate (PHObject *)
virtual void CopyFrom (const PHObject *obj)
Private Member Functions
ClassDefOverride (TrackSeedContainer_v1, 1)
Private Attributes
Container m_seeds
Additional Inherited Members
Public Types inherited from TrackSeedContainer
typedef std::vector< TrackSeed * > Container
typedef std::vector< TrackSeed * >
::const_iterator ConstIter
typedef std::vector< TrackSeed * >
::iterator Iter
Protected Member Functions inherited from TrackSeedContainer
TrackSeedContainer ()
Detailed Description
Definition at line 10 of file TrackSeedContainer_v1.h.
View newest version in sPHENIX GitHub at line 10 of file TrackSeedContainer_v1.h
Constructor & Destructor Documentation
TrackSeedContainer_v1::TrackSeedContainer_v1 ()
Definition at line 10 of file TrackSeedContainer_v1.cc.
View newest version in sPHENIX GitHub at line 10 of file TrackSeedContainer_v1.cc
Referenced by CloneMe().
TrackSeedContainer_v1::TrackSeedContainer_v1 (const TrackSeedContainer_v1 & trackmap)
Definition at line 13 of file TrackSeedContainer_v1.cc.
View newest version in sPHENIX GitHub at line 13 of file TrackSeedContainer_v1.cc
References m_seeds, and seed.
TrackSeedContainer_v1::~TrackSeedContainer_v1 () override
Definition at line 45 of file TrackSeedContainer_v1.cc.
View newest version in sPHENIX GitHub at line 45 of file TrackSeedContainer_v1.cc
References Reset().
Member Function Documentation
ConstIter TrackSeedContainer_v1::begin (void) const inline override virtual
Reimplemented from TrackSeedContainer.
Definition at line 41 of file TrackSeedContainer_v1.h.
View newest version in sPHENIX GitHub at line 41 of file TrackSeedContainer_v1.h
References m_seeds.
Iter TrackSeedContainer_v1::begin (void) inline override virtual
Reimplemented from TrackSeedContainer.
Definition at line 46 of file TrackSeedContainer_v1.h.
View newest version in sPHENIX GitHub at line 46 of file TrackSeedContainer_v1.h
References m_seeds.
TrackSeedContainer_v1::ClassDefOverride (TrackSeedContainer_v1 , 1) private
void TrackSeedContainer_v1::clear () inline override virtual
Reimplemented from TrackSeedContainer.
Definition at line 27 of file TrackSeedContainer_v1.h.
View newest version in sPHENIX GitHub at line 27 of file TrackSeedContainer_v1.h
References Reset().
PHObject* TrackSeedContainer_v1::CloneMe () const inline override virtual
Virtual copy constructor.
Reimplemented from TrackSeedContainer.
Definition at line 23 of file TrackSeedContainer_v1.h.
View newest version in sPHENIX GitHub at line 23 of file TrackSeedContainer_v1.h
References TrackSeedContainer_v1().
bool TrackSeedContainer_v1::empty () const inline override virtual
Reimplemented from TrackSeedContainer.
Definition at line 25 of file TrackSeedContainer_v1.h.
View newest version in sPHENIX GitHub at line 25 of file TrackSeedContainer_v1.h
References m_seeds.
ConstIter TrackSeedContainer_v1::end (void) const inline override virtual
Reimplemented from TrackSeedContainer.
Definition at line 44 of file TrackSeedContainer_v1.h.
View newest version in sPHENIX GitHub at line 44 of file TrackSeedContainer_v1.h
References m_seeds.
Iter TrackSeedContainer_v1::end (void) inline override virtual
Reimplemented from TrackSeedContainer.
Definition at line 49 of file TrackSeedContainer_v1.h.
View newest version in sPHENIX GitHub at line 49 of file TrackSeedContainer_v1.h
References m_seeds.
void TrackSeedContainer_v1::erase (const std::size_t key) inline override virtual
Reimplemented from TrackSeedContainer.
Definition at line 32 of file TrackSeedContainer_v1.h.
View newest version in sPHENIX GitHub at line 32 of file TrackSeedContainer_v1.h
References m_seeds.
ConstIter TrackSeedContainer_v1::find (const std::size_t key) const inline override virtual
Reimplemented from TrackSeedContainer.
Definition at line 42 of file TrackSeedContainer_v1.h.
View newest version in sPHENIX GitHub at line 42 of file TrackSeedContainer_v1.h
References m_seeds.
std::size_t TrackSeedContainer_v1::find (const TrackSeed * seed) const override virtual
Reimplemented from TrackSeedContainer.
Definition at line 75 of file TrackSeedContainer_v1.cc.
View newest version in sPHENIX GitHub at line 75 of file TrackSeedContainer_v1.cc
References distance(), it, m_seeds, and seed.
Iter TrackSeedContainer_v1::find (const std::size_t key) inline override virtual
Reimplemented from TrackSeedContainer.
Definition at line 47 of file TrackSeedContainer_v1.h.
View newest version in sPHENIX GitHub at line 47 of file TrackSeedContainer_v1.h
References m_seeds.
std::size_t TrackSeedContainer_v1::find (const TrackSeed * seed) override virtual
Reimplemented from TrackSeedContainer.
Definition at line 81 of file TrackSeedContainer_v1.cc.
View newest version in sPHENIX GitHub at line 81 of file TrackSeedContainer_v1.cc
References distance(), it, m_seeds, and seed.
const TrackSeed * TrackSeedContainer_v1::get (const std::size_t key) const override virtual
Reimplemented from TrackSeedContainer.
Definition at line 56 of file TrackSeedContainer_v1.cc.
View newest version in sPHENIX GitHub at line 56 of file TrackSeedContainer_v1.cc
References m_seeds.
TrackSeed * TrackSeedContainer_v1::get (const std::size_t key) override virtual
Reimplemented from TrackSeedContainer.
Definition at line 62 of file TrackSeedContainer_v1.cc.
View newest version in sPHENIX GitHub at line 62 of file TrackSeedContainer_v1.cc
References m_seeds.
void TrackSeedContainer_v1::identify (std::ostream & os = std::cout) const override virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from TrackSeedContainer.
Definition at line 50 of file TrackSeedContainer_v1.cc.
View newest version in sPHENIX GitHub at line 50 of file TrackSeedContainer_v1.cc
References m_seeds.
std::size_t TrackSeedContainer_v1::index (ConstIter) const inline override virtual
Interface to return the index corresponding to the track id of the container
Reimplemented from TrackSeedContainer.
Definition at line 38 of file TrackSeedContainer_v1.h.
View newest version in sPHENIX GitHub at line 38 of file TrackSeedContainer_v1.h
References m_seeds.
std::size_t TrackSeedContainer_v1::index (Iter it) const inline override virtual
Reimplemented from TrackSeedContainer.
Definition at line 39 of file TrackSeedContainer_v1.h.
View newest version in sPHENIX GitHub at line 39 of file TrackSeedContainer_v1.h
References m_seeds.
TrackSeed * TrackSeedContainer_v1::insert (const TrackSeed * seed) override virtual
Reimplemented from TrackSeedContainer.
Definition at line 68 of file TrackSeedContainer_v1.cc.
View newest version in sPHENIX GitHub at line 68 of file TrackSeedContainer_v1.cc
References TrackSeed::CloneMe(), and m_seeds.
int TrackSeedContainer_v1::isValid () const inline override virtual
isValid returns non zero if object contains vailid data
Reimplemented from TrackSeedContainer.
Definition at line 22 of file TrackSeedContainer_v1.h.
View newest version in sPHENIX GitHub at line 22 of file TrackSeedContainer_v1.h
TrackSeedContainer_v1 & TrackSeedContainer_v1::operator= (const TrackSeedContainer_v1 & seedContainer)
Definition at line 22 of file TrackSeedContainer_v1.cc.
View newest version in sPHENIX GitHub at line 22 of file TrackSeedContainer_v1.cc
References m_seeds, Reset(), and seed.
void TrackSeedContainer_v1::Reset () override virtual
Clear Event.
Reimplemented from PHObject.
Definition at line 34 of file TrackSeedContainer_v1.cc.
View newest version in sPHENIX GitHub at line 34 of file TrackSeedContainer_v1.cc
References m_seeds, and seed.
Referenced by clear(), operator=(), and ~TrackSeedContainer_v1().
std::size_t TrackSeedContainer_v1::size (void) const inline override virtual
Reimplemented from TrackSeedContainer.
Definition at line 26 of file TrackSeedContainer_v1.h.
View newest version in sPHENIX GitHub at line 26 of file TrackSeedContainer_v1.h
References m_seeds.
Member Data Documentation
Container TrackSeedContainer_v1::m_seeds private
Definition at line 52 of file TrackSeedContainer_v1.h.
View newest version in sPHENIX GitHub at line 52 of file TrackSeedContainer_v1.h
Referenced by begin(), empty(), end(), erase(), find(), get(), identify(), index(), insert(), operator=(), Reset(), size(), and TrackSeedContainer_v1().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/trackbase_historic/TrackSeedContainer_v1.h
coresoftware/blob/master/offline/packages/trackbase_historic/TrackSeedContainer_v1.cc