Analysis Software: HybridHadronization::parton_collection Class Reference
HybridHadronization::parton_collection Class Reference
Public Member Functions
parton_collection ()
parton_collection (HHparton par)
void add (HHparton par)
void add (parton_collection pars)
int num ()
void clear ()
void insert (int i, HHparton newparton)
void remove (int i)
void swap (int i, int j)
std::vector< HHparton >::iterator begin ()
std::vector< HHparton >::iterator end ()
HHparton & operator[] (int i)
const HHparton & operator[] (int i) const
Public Attributes
std::vector< HHparton > partons
Detailed Description
Definition at line 254 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 254 of file HybridHadronization.h
Constructor & Destructor Documentation
HybridHadronization::parton_collection::parton_collection () inline
Definition at line 259 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 259 of file HybridHadronization.h
HybridHadronization::parton_collection::parton_collection (HHparton par) inline
Definition at line 261 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 261 of file HybridHadronization.h
Member Function Documentation
void HybridHadronization::parton_collection::add (HHparton par) inline
Definition at line 263 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 263 of file HybridHadronization.h
Referenced by HybridHadronization::DoHadronization(), HybridHadronization::gluon_decay(), HybridHadronization::recomb(), and HybridHadronization::stringprep().
void HybridHadronization::parton_collection::add (parton_collection pars) inline
Definition at line 265 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 265 of file HybridHadronization.h
References i, and num().
std::vector<HHparton>::iterator HybridHadronization::parton_collection::begin (void) inline
Definition at line 277 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 277 of file HybridHadronization.h
void HybridHadronization::parton_collection::clear () inline
Definition at line 269 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 269 of file HybridHadronization.h
Referenced by HybridHadronization::DoHadronization(), HybridHadronization::recomb(), and HybridHadronization::stringprep().
std::vector<HHparton>::iterator HybridHadronization::parton_collection::end (void) inline
Definition at line 279 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 279 of file HybridHadronization.h
void HybridHadronization::parton_collection::insert (int i, HHparton newparton) inline
Definition at line 271 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 271 of file HybridHadronization.h
References i.
int HybridHadronization::parton_collection::num () inline
Definition at line 267 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 267 of file HybridHadronization.h
Referenced by add(), HybridHadronization::DoHadronization(), HybridHadronization::findcloserepl(), HybridHadronization::findcloserepl_glu(), HybridHadronization::findthermalsibling(), pevrec(), HybridHadronization::recomb(), HybridHadronization::set_initial_parton_masses(), and HybridHadronization::stringprep().
HHparton& HybridHadronization::parton_collection::operator[] (int i) inline
Definition at line 295 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 295 of file HybridHadronization.h
References i.
const HHparton& HybridHadronization::parton_collection::operator[] (int i) const inline
Definition at line 296 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 296 of file HybridHadronization.h
References i.
void HybridHadronization::parton_collection::remove (int i) inline
Definition at line 273 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 273 of file HybridHadronization.h
References i.
void HybridHadronization::parton_collection::swap (int i, int j) inline
Definition at line 275 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 275 of file HybridHadronization.h
References swap().
Member Data Documentation
std::vector<HHparton> HybridHadronization::parton_collection::partons
Definition at line 257 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 257 of file HybridHadronization.h
Referenced by HybridHadronization::recomb().
The documentation for this class was generated from the following file:
JETSCAPE/blob/main/src/hadronization/HybridHadronization.h