Analysis Software: SColdQcdCorrelatorAnalysis::SLambdaJetHunter Class Reference
SColdQcdCorrelatorAnalysis::SLambdaJetHunter Class Reference
#include <analysis/blob/master/AndersonAnalysisModules/ColdQcdCorrelatorAnalysis/SLambdaJetHunter/src/SLambdaJetHunter.h>
Public Types
enum Algo { AntiKt, Kt, CA }
enum Recomb {
E, Pt, Pt2, Et,
Et2
}
Public Member Functions
SLambdaJetHunter (const string &name="SLambdaJetHunter", const bool debug=false)
SLambdaJetHunter (SLambdaJetHunterConfig &config)
~SLambdaJetHunter () override
int Init (PHCompositeNode *topNode) override
int process_event (PHCompositeNode *topNode) override
int End (PHCompositeNode *topNode) override
Called at the end of all processing.
void SetConfig (SLambdaJetHunterConfig &config)
SLambdaJetHunterConfig GetConfig ()
Public Member Functions inherited from SubsysReco
~SubsysReco () override
virtual int EndRun (const int)
Called at the end of each run.
virtual int InitRun (PHCompositeNode *)
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
void Print (const std::string &="ALL") const override
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Private Member Functions
void InitTree ()
void InitOutput ()
void SaveAndCloseOutput ()
Private Attributes
TFile * m_outFile = NULL
TTree * m_outTree = NULL
SLambdaJetHunterConfig m_config
GenInfo m_genEvtInfo
vector< JetInfo > m_jetInfo
vector< vector< CstInfo > > m_cstInfo
vector< vector< ParInfo > > m_lambdaInfo
Additional Inherited Members
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Detailed Description
Definition at line 40 of file SLambdaJetHunter.h.
View newest version in sPHENIX GitHub at line 40 of file SLambdaJetHunter.h
Member Enumeration Documentation
enum SColdQcdCorrelatorAnalysis::SLambdaJetHunter::Algo
Enumerator:
AntiKt
Kt
CA
Definition at line 45 of file SLambdaJetHunter.h.
View newest version in sPHENIX GitHub at line 45 of file SLambdaJetHunter.h
enum SColdQcdCorrelatorAnalysis::SLambdaJetHunter::Recomb
Enumerator:
E
Pt
Pt2
Et
Et2
Definition at line 46 of file SLambdaJetHunter.h.
View newest version in sPHENIX GitHub at line 46 of file SLambdaJetHunter.h
Constructor & Destructor Documentation
SColdQcdCorrelatorAnalysis::SLambdaJetHunter::SLambdaJetHunter (const string & name = "SLambdaJetHunter", const bool debug = false)
Definition at line 33 of file SLambdaJetHunter.cc.
View newest version in sPHENIX GitHub at line 33 of file SLambdaJetHunter.cc
SColdQcdCorrelatorAnalysis::SLambdaJetHunter::SLambdaJetHunter (SLambdaJetHunterConfig & config)
Definition at line 43 of file SLambdaJetHunter.cc.
View newest version in sPHENIX GitHub at line 43 of file SLambdaJetHunter.cc
References filter::config, SColdQcdCorrelatorAnalysis::SLambdaJetHunterConfig::isDebugOn, and m_config.
SColdQcdCorrelatorAnalysis::SLambdaJetHunter::~SLambdaJetHunter () override
Definition at line 54 of file SLambdaJetHunter.cc.
View newest version in sPHENIX GitHub at line 54 of file SLambdaJetHunter.cc
References SColdQcdCorrelatorAnalysis::SLambdaJetHunterConfig::isDebugOn, and m_config.
Member Function Documentation
int SColdQcdCorrelatorAnalysis::SLambdaJetHunter::End (PHCompositeNode *) override virtual
Called at the end of all processing.
Reimplemented from SubsysReco.
Definition at line 95 of file SLambdaJetHunter.cc.
View newest version in sPHENIX GitHub at line 95 of file SLambdaJetHunter.cc
References Fun4AllReturnCodes::EVENT_OK, SColdQcdCorrelatorAnalysis::SLambdaJetHunterConfig::isDebugOn, m_config, and SaveAndCloseOutput().
SLambdaJetHunterConfig SColdQcdCorrelatorAnalysis::SLambdaJetHunter::GetConfig () inline
Definition at line 62 of file SLambdaJetHunter.h.
View newest version in sPHENIX GitHub at line 62 of file SLambdaJetHunter.h
int SColdQcdCorrelatorAnalysis::SLambdaJetHunter::Init (PHCompositeNode *) override virtual
Called during initialization. Typically this is where you can book histograms, and e.g. register them to Fun4AllServer (so they can be output to file using Fun4AllServer::dumpHistos() method).
Reimplemented from SubsysReco.
Definition at line 66 of file SLambdaJetHunter.cc.
View newest version in sPHENIX GitHub at line 66 of file SLambdaJetHunter.cc
References Fun4AllReturnCodes::EVENT_OK, InitOutput(), InitTree(), SColdQcdCorrelatorAnalysis::SLambdaJetHunterConfig::isDebugOn, and m_config.
void SColdQcdCorrelatorAnalysis::SLambdaJetHunter::InitOutput () private
Definition at line 41 of file SLambdaJetHunter.sys.h.
View newest version in sPHENIX GitHub at line 41 of file SLambdaJetHunter.sys.h
References assert.
Referenced by Init().
void SColdQcdCorrelatorAnalysis::SLambdaJetHunter::InitTree () private
Definition at line 25 of file SLambdaJetHunter.sys.h.
View newest version in sPHENIX GitHub at line 25 of file SLambdaJetHunter.sys.h
References Branch().
Referenced by Init().
int SColdQcdCorrelatorAnalysis::SLambdaJetHunter::process_event (PHCompositeNode *) override virtual
Called for each event. This is where you do the real work.
Reimplemented from SubsysReco.
Definition at line 81 of file SLambdaJetHunter.cc.
View newest version in sPHENIX GitHub at line 81 of file SLambdaJetHunter.cc
References Fun4AllReturnCodes::EVENT_OK, SColdQcdCorrelatorAnalysis::SLambdaJetHunterConfig::isDebugOn, and m_config.
void SColdQcdCorrelatorAnalysis::SLambdaJetHunter::SaveAndCloseOutput () private
Definition at line 59 of file SLambdaJetHunter.sys.h.
View newest version in sPHENIX GitHub at line 59 of file SLambdaJetHunter.sys.h
References cd(), Close(), and Write().
Referenced by End().
void SColdQcdCorrelatorAnalysis::SLambdaJetHunter::SetConfig (SLambdaJetHunterConfig & config) inline
Definition at line 59 of file SLambdaJetHunter.h.
View newest version in sPHENIX GitHub at line 59 of file SLambdaJetHunter.h
References filter::config.
Member Data Documentation
SLambdaJetHunterConfig SColdQcdCorrelatorAnalysis::SLambdaJetHunter::m_config private
Definition at line 71 of file SLambdaJetHunter.h.
View newest version in sPHENIX GitHub at line 71 of file SLambdaJetHunter.h
Referenced by End(), Init(), process_event(), SLambdaJetHunter(), and ~SLambdaJetHunter().
vector<vector<CstInfo> > SColdQcdCorrelatorAnalysis::SLambdaJetHunter::m_cstInfo private
Definition at line 76 of file SLambdaJetHunter.h.
View newest version in sPHENIX GitHub at line 76 of file SLambdaJetHunter.h
GenInfo SColdQcdCorrelatorAnalysis::SLambdaJetHunter::m_genEvtInfo private
Definition at line 74 of file SLambdaJetHunter.h.
View newest version in sPHENIX GitHub at line 74 of file SLambdaJetHunter.h
vector<JetInfo> SColdQcdCorrelatorAnalysis::SLambdaJetHunter::m_jetInfo private
Definition at line 75 of file SLambdaJetHunter.h.
View newest version in sPHENIX GitHub at line 75 of file SLambdaJetHunter.h
vector<vector<ParInfo> > SColdQcdCorrelatorAnalysis::SLambdaJetHunter::m_lambdaInfo private
Definition at line 77 of file SLambdaJetHunter.h.
View newest version in sPHENIX GitHub at line 77 of file SLambdaJetHunter.h
TFile* SColdQcdCorrelatorAnalysis::SLambdaJetHunter::m_outFile = NULL private
Definition at line 67 of file SLambdaJetHunter.h.
View newest version in sPHENIX GitHub at line 67 of file SLambdaJetHunter.h
TTree* SColdQcdCorrelatorAnalysis::SLambdaJetHunter::m_outTree = NULL private
Definition at line 68 of file SLambdaJetHunter.h.
View newest version in sPHENIX GitHub at line 68 of file SLambdaJetHunter.h
The documentation for this class was generated from the following files:
analysis/blob/master/AndersonAnalysisModules/ColdQcdCorrelatorAnalysis/SLambdaJetHunter/src/SLambdaJetHunter.h
analysis/blob/master/AndersonAnalysisModules/ColdQcdCorrelatorAnalysis/SLambdaJetHunter/src/SLambdaJetHunter.cc
analysis/blob/master/AndersonAnalysisModules/ColdQcdCorrelatorAnalysis/SLambdaJetHunter/src/SLambdaJetHunter.sys.h