Analysis Software: analysis/blob/master/PhotonJet/example_macros/Fun4All_G4_fsPHENIX_pi0.C File Reference
Fun4All_G4_fsPHENIX_pi0.C File Reference
Functions
int Fun4All_G4_fsPHENIX_pi0 (const int nEvents=10, const char *inputFile="/sphenix/sim//sim01/production/2016-07-21/single_particle/spacal2d/fieldmap/G4Hits_sPHENIX_e-_eta0_8GeV-0002.root", const char *outputFile="G4fsPHENIX.root", const char *embed_input_file="/sphenix/sim/sim01/production/2016-07-12/sHijing/spacal2d/G4Hits_sPHENIX_sHijing-0-4.4fm.list")
void G4Cmd (const char *cmd)
Function Documentation
int Fun4All_G4_fsPHENIX_pi0 (const int nEvents = 10, const char * inputFile = "/sphenix/sim//sim01/production/2016-07-21/single_particle/spacal2d/fieldmap/G4Hits_sPHENIX_e-_eta0_8GeV-0002.root", const char * outputFile = "G4fsPHENIX.root", const char * embed_input_file = "/sphenix/sim/sim01/production/2016-07-12/sHijing/spacal2d/G4Hits_sPHENIX_sHijing-0-4.4fm.list")
Definition at line 2 of file Fun4All_G4_fsPHENIX_pi0.C.
View newest version in sPHENIX GitHub at line 2 of file Fun4All_G4_fsPHENIX_pi0.C
References PHG4SimpleEventGenerator::add_particles(), Fun4AllInputManager::AddListFile(), PHG4Reco::ApplyCommand(), Bbc_Reco(), BbcInit(), CEMC_Cells(), CEMC_Clusters(), CEMC_Eval(), CEMC_Towers(), Fun4AllServer::End(), FEMC_Cells(), FEMC_Clusters(), FEMC_Towers(), FGEM_FastSim_Reco(), FHCAL_Cells(), FHCAL_Clusters(), FHCAL_Towers(), Fun4AllInputManager::fileopen(), Fun4AllServer::fileopen(), g4, G4DSTreader_fsPHENIX(), G4Init(), G4Setup(), gen(), Fun4AllServer::getSubsysReco(), Global_FastSim(), Global_Reco(), HCALInner_Cells(), HCALInner_Clusters(), HCALInner_Eval(), HCALInner_Towers(), HCALOuter_Cells(), HCALOuter_Clusters(), HCALOuter_Eval(), HCALOuter_Towers(), in, recoConsts::instance(), Fun4AllServer::instance(), Jet_Eval(), Jet_FwdEval(), Jet_FwdReco(), Jet_Reco(), kAll, G4MAGNET::magfield, G4MAGNET::magfield_rescale, Fun4AllBase::Name(), nEvents, Fun4AllServer::registerInputManager(), Fun4AllServer::registerSubsystem(), Fun4AllServer::run(), Forward_pi0s::set_cluspt_mincut(), PHPythia6::set_config_file(), PHPythia8::set_config_file(), Forward_pi0s::set_eta_lowhigh(), PHG4SimpleEventGenerator::set_eta_range(), PHG4SimpleEventGenerator::set_existing_vertex_offset_vector(), PHG4SimpleEventGenerator::set_p_range(), PHG4SimpleEventGenerator::set_phi_range(), PHG4ParticleGeneratorBase::set_reuse_existing_vertex(), PHG4SimpleEventGenerator::set_vertex_distribution_function(), PHG4SimpleEventGenerator::set_vertex_distribution_mean(), PHG4SimpleEventGenerator::set_vertex_distribution_width(), PHG4SimpleEventGenerator::set_vertex_size_function(), PHG4SimpleEventGenerator::set_vertex_size_parameters(), ShowerCompress(), Svtx_Cells(), Svtx_Eval(), Svtx_Reco(), PHG4SimpleEventGenerator::Uniform, Fun4AllBase::Verbosity(), and Fun4AllBase::VERBOSITY_SOME.
void G4Cmd (const char * cmd)
Definition at line 449 of file Fun4All_G4_fsPHENIX_pi0.C.
View newest version in sPHENIX GitHub at line 449 of file Fun4All_G4_fsPHENIX_pi0.C
References PHG4Reco::ApplyCommand(), g4, Fun4AllServer::getSubsysReco(), and Fun4AllServer::instance().