Analysis Software: ActsExamples::FatrasSimulation Exception Reference
ActsExamples::FatrasSimulation Exception Reference final
Fast track simulation using the Acts propagation and navigation.
#include <acts/blob/sPHENIX/Examples/Algorithms/Fatras/include/ActsExamples/Fatras/FatrasSimulation.hpp>
Classes
struct Config
Public Member Functions
FatrasSimulation (Config cfg, Acts::Logging::Level lvl)
~FatrasSimulation () override
ActsExamples::ProcessCode execute (const AlgorithmContext &ctx) const override
const Config & config () const
Const access to the config.
Public Member Functions inherited from ActsExamples::IAlgorithm
IAlgorithm (std::string name, Acts::Logging::Level level=Acts::Logging::INFO)
std::string name () const override
The algorithm name.
ProcessCode internalExecute (const AlgorithmContext &context) final
ProcessCode initialize () override
Initialize the algorithm.
ProcessCode finalize () override
Finalize the algorithm.
Public Attributes
ReadDataHandle
< SimParticleContainer > m_inputParticles {this, "InputParticles"}
WriteDataHandle< SimHitContainer > m_outputSimHits {this, "OutputSimHits"}
WriteDataHandle
< SimParticleContainer > m_outputParticlesInitial
WriteDataHandle
< SimParticleContainer > m_outputParticlesFinal
Private Attributes
Config m_cfg
std::unique_ptr
< detail::FatrasSimulation > m_sim
Additional Inherited Members
Protected Member Functions inherited from ActsExamples::IAlgorithm
const Acts::Logger & logger () const
Detailed Description
Fast track simulation using the Acts propagation and navigation.
Definition at line 41 of file FatrasSimulation.hpp.
View newest version in sPHENIX GitHub at line 41 of file FatrasSimulation.hpp
Constructor & Destructor Documentation
ActsExamples::FatrasSimulation::FatrasSimulation (Config cfg, Acts::Logging::Level lvl)
Construct the algorithm from a config.
Parameters
cfg is the configuration struct
lvl is the logging level
Definition at line 180 of file FatrasSimulation.cpp.
View newest version in sPHENIX GitHub at line 180 of file FatrasSimulation.cpp
References ACTS_DEBUG, ACTS_WARNING, ActsExamples::FatrasSimulation::Config::generateHitsOnMaterial, ActsExamples::FatrasSimulation::Config::generateHitsOnPassive, ActsExamples::FatrasSimulation::Config::generateHitsOnSensitive, ActsExamples::WriteDataHandle< T >::initialize(), ActsExamples::ReadDataHandle< T >::initialize(), m_cfg, m_inputParticles, m_outputParticlesFinal, m_outputParticlesInitial, m_outputSimHits, m_sim, ActsExamples::FatrasSimulation::Config::magneticField, ActsExamples::FatrasSimulation::Config::randomNumbers, and ActsExamples::FatrasSimulation::Config::trackingGeometry.
ActsExamples::FatrasSimulation::~FatrasSimulation () override default
Member Function Documentation
const Config& ActsExamples::FatrasSimulation::config () const inline
Const access to the config.
Definition at line 102 of file FatrasSimulation.hpp.
View newest version in sPHENIX GitHub at line 102 of file FatrasSimulation.hpp
References m_cfg.
ActsExamples::ProcessCode ActsExamples::FatrasSimulation::execute (const AlgorithmContext & ctx) const override virtual
Run the simulation for a single event.
Parameters
ctx the algorithm context containing all event information
Implements ActsExamples::IAlgorithm.
Definition at line 214 of file FatrasSimulation.cpp.
View newest version in sPHENIX GitHub at line 214 of file FatrasSimulation.cpp
References ACTS_DEBUG, ACTS_ERROR, ACTS_FATAL, ActsExamples::AlgorithmContext::eventNumber, ActsExamples::AlgorithmContext::geoContext, h, physmon_simulation::inputParticles, m_cfg(), ActsExamples::AlgorithmContext::magFieldContext, testing::internal::move(), merge_hashes::p, conftest::rng(), and SUCCESS.
Member Data Documentation
Config ActsExamples::FatrasSimulation::m_cfg private
Definition at line 114 of file FatrasSimulation.hpp.
View newest version in sPHENIX GitHub at line 114 of file FatrasSimulation.hpp
Referenced by config(), and FatrasSimulation().
ReadDataHandle<SimParticleContainer> ActsExamples::FatrasSimulation::m_inputParticles {this, "InputParticles"}
Definition at line 104 of file FatrasSimulation.hpp.
View newest version in sPHENIX GitHub at line 104 of file FatrasSimulation.hpp
Referenced by FatrasSimulation().
WriteDataHandle<SimParticleContainer> ActsExamples::FatrasSimulation::m_outputParticlesFinal
Initial value:
{
      this, "OutputParticlesFinal"}
Definition at line 110 of file FatrasSimulation.hpp.
View newest version in sPHENIX GitHub at line 110 of file FatrasSimulation.hpp
Referenced by FatrasSimulation().
WriteDataHandle<SimParticleContainer> ActsExamples::FatrasSimulation::m_outputParticlesInitial
Initial value:
{
      this, "OutputParticlesInitial"}
Definition at line 108 of file FatrasSimulation.hpp.
View newest version in sPHENIX GitHub at line 108 of file FatrasSimulation.hpp
Referenced by FatrasSimulation().
WriteDataHandle<SimHitContainer> ActsExamples::FatrasSimulation::m_outputSimHits {this, "OutputSimHits"}
Definition at line 106 of file FatrasSimulation.hpp.
View newest version in sPHENIX GitHub at line 106 of file FatrasSimulation.hpp
Referenced by FatrasSimulation().
std::unique_ptr<detail::FatrasSimulation> ActsExamples::FatrasSimulation::m_sim private
Definition at line 115 of file FatrasSimulation.hpp.
View newest version in sPHENIX GitHub at line 115 of file FatrasSimulation.hpp
Referenced by FatrasSimulation().
The documentation for this exception was generated from the following files:
acts/blob/sPHENIX/Examples/Algorithms/Fatras/include/ActsExamples/Fatras/FatrasSimulation.hpp
acts/blob/sPHENIX/Examples/Algorithms/Fatras/src/FatrasSimulation.cpp