Analysis Software: Acts::Test::Stepper Struct Reference
Acts::Test::Stepper Struct Reference
mockup of stepping state
Public Member Functions
Result< Vector3 > getField (SteppingState &, const Vector3 &) const
Vector3 position (const SteppingState &state) const
Access method - position.
Vector3 direction (const SteppingState &state) const
Access method - direction.
double absoluteMomentum (const SteppingState &state) const
Access method - momentum.
Stepper ()=default
Vector3 position (const StepperState &state) const
double time (const StepperState &state) const
Vector3 direction (const StepperState &state) const
double qOverP (const StepperState &state) const
double absoluteMomentum (const StepperState &state) const
double charge (const StepperState &state) const
ParticleHypothesis particleHypothesis (const StepperState &state) const
Public Attributes
Vector3 field = Vector3(0., 0., 2_T)
Detailed Description
mockup of stepping state
Simplified stepper.
Definition at line 67 of file LoopProtectionTests.cpp.
View newest version in sPHENIX GitHub at line 67 of file LoopProtectionTests.cpp
Constructor & Destructor Documentation
Acts::Test::Stepper::Stepper () default
Member Function Documentation
double Acts::Test::Stepper::absoluteMomentum (const StepperState & state) const inline
Definition at line 68 of file VolumeMaterialInteractionTests.cpp.
View newest version in sPHENIX GitHub at line 68 of file VolumeMaterialInteractionTests.cpp
References Acts::Test::StepperState::p.
double Acts::Test::Stepper::absoluteMomentum (const SteppingState & state) const inline
Access method - momentum.
Definition at line 90 of file LoopProtectionTests.cpp.
View newest version in sPHENIX GitHub at line 90 of file LoopProtectionTests.cpp
References Acts::Test::SteppingState::p.
Referenced by Acts::Test::BOOST_AUTO_TEST_CASE().
double Acts::Test::Stepper::charge (const StepperState & state) const inline
Definition at line 70 of file VolumeMaterialInteractionTests.cpp.
View newest version in sPHENIX GitHub at line 70 of file VolumeMaterialInteractionTests.cpp
References Acts::Test::StepperState::q.
Referenced by Acts::Test::BOOST_AUTO_TEST_CASE().
Vector3 Acts::Test::Stepper::direction (const StepperState & state) const inline
Definition at line 64 of file VolumeMaterialInteractionTests.cpp.
View newest version in sPHENIX GitHub at line 64 of file VolumeMaterialInteractionTests.cpp
References Acts::Test::StepperState::dir.
Vector3 Acts::Test::Stepper::direction (const SteppingState & state) const inline
Access method - direction.
Definition at line 87 of file LoopProtectionTests.cpp.
View newest version in sPHENIX GitHub at line 87 of file LoopProtectionTests.cpp
References Acts::Test::SteppingState::dir.
Referenced by Acts::Test::BOOST_AUTO_TEST_CASE().
Result<Vector3> Acts::Test::Stepper::getField (SteppingState & , const Vector3 &) const inline
Get the field for the stepping, it checks first if the access is still within the Cell, and updates the cell if necessary.
Parameters
[in,out] state is the propagation state associated with the track the magnetic field cell is used (and potentially updated)
[in] pos is the field position
Definition at line 77 of file LoopProtectionTests.cpp.
View newest version in sPHENIX GitHub at line 77 of file LoopProtectionTests.cpp
References ckf::field.
ParticleHypothesis Acts::Test::Stepper::particleHypothesis (const StepperState & state) const inline
Definition at line 72 of file VolumeMaterialInteractionTests.cpp.
View newest version in sPHENIX GitHub at line 72 of file VolumeMaterialInteractionTests.cpp
References Acts::Test::StepperState::particleHypothesis.
Vector3 Acts::Test::Stepper::position (const StepperState & state) const inline
Definition at line 60 of file VolumeMaterialInteractionTests.cpp.
View newest version in sPHENIX GitHub at line 60 of file VolumeMaterialInteractionTests.cpp
References Acts::Test::StepperState::pos.
Vector3 Acts::Test::Stepper::position (const SteppingState & state) const inline
Access method - position.
Definition at line 84 of file LoopProtectionTests.cpp.
View newest version in sPHENIX GitHub at line 84 of file LoopProtectionTests.cpp
References Acts::Test::SteppingState::pos.
Referenced by Acts::Test::BOOST_AUTO_TEST_CASE().
double Acts::Test::Stepper::qOverP (const StepperState & state) const inline
Definition at line 66 of file VolumeMaterialInteractionTests.cpp.
View newest version in sPHENIX GitHub at line 66 of file VolumeMaterialInteractionTests.cpp
References Acts::Test::StepperState::p, and Acts::Test::StepperState::q.
Referenced by Acts::Test::BOOST_AUTO_TEST_CASE().
double Acts::Test::Stepper::time (const StepperState & state) const inline
Definition at line 62 of file VolumeMaterialInteractionTests.cpp.
View newest version in sPHENIX GitHub at line 62 of file VolumeMaterialInteractionTests.cpp
References Acts::Test::StepperState::t.
Referenced by Acts::Test::BOOST_AUTO_TEST_CASE().
Member Data Documentation
Vector3 Acts::Test::Stepper::field = Vector3(0., 0., 2_T)
Definition at line 68 of file LoopProtectionTests.cpp.
View newest version in sPHENIX GitHub at line 68 of file LoopProtectionTests.cpp
The documentation for this struct was generated from the following files:
acts/blob/sPHENIX/Tests/UnitTests/Core/Propagator/LoopProtectionTests.cpp
acts/blob/sPHENIX/Tests/UnitTests/Core/Propagator/VolumeMaterialInteractionTests.cpp