Analysis Software: SColdQcdCorrelatorAnalysis::SCheckTrackPairs Class Reference
SColdQcdCorrelatorAnalysis::SCheckTrackPairs Class Reference
#include <analysis/blob/master/AndersonAnalysisModules/ColdQcdCorrelatorAnalysis/SCorrelatorQAMaker/src/SCheckTrackPairs.h>
Public Member Functions
SCheckTrackPairs (const string &name="CheckTrackPairs")
~SCheckTrackPairs ()
int Init (PHCompositeNode *) override
int process_event (PHCompositeNode *) override
int End (PHCompositeNode *) override
Called at the end of all processing.
Public Member Functions inherited from SubsysReco
~SubsysReco () override
virtual int EndRun (const int)
Called at the end of each run.
virtual int InitRun (PHCompositeNode *)
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
void Print (const std::string &="ALL") const override
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Public Member Functions inherited from SColdQcdCorrelatorAnalysis::SBaseQAPlugin< SCheckTrackPairsConfig >
SBaseQAPlugin ()
~SBaseQAPlugin ()
void SetDebug (const bool debug)
void SetOutFile (const string file)
void SetOutDir (const string name)
void SetVerbosity (const uint16_t verb)
void SetConfig (const SCheckTrackPairsConfig &cfg)
TFile * GetOutFile ()
TDirectory * GetOutDir ()
Private Member Functions
void InitTuples ()
void SaveOutput ()
void ResetVectors ()
void DoDoubleTrackLoop (PHCompositeNode *topNode)
bool IsGoodTrack (SvtxTrack *track, PHCompositeNode *topNode)
Private Attributes
vector< float > m_vecTrackPairLeaves
vector< TrkrDefs::cluskey > m_vecClustKeysA
vector< TrkrDefs::cluskey > m_vecClustKeysB
TNtuple * m_ntTrackPairs
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = std::numeric_limits<int>::max() - 10
}
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Protected Member Functions inherited from SColdQcdCorrelatorAnalysis::SBaseQAPlugin< SCheckTrackPairsConfig >
void InitOutput ()
void CloseOutput ()
Protected Attributes inherited from SColdQcdCorrelatorAnalysis::SBaseQAPlugin< SCheckTrackPairsConfig >
TFile * m_outFile
TDirectory * m_outDir
bool m_isDebugOn
string m_outFileName
string m_outDirName
uint16_t m_verbosity
SCheckTrackPairsConfig m_config
Detailed Description
Definition at line 71 of file SCheckTrackPairs.h.
View newest version in sPHENIX GitHub at line 71 of file SCheckTrackPairs.h
Constructor & Destructor Documentation
SColdQcdCorrelatorAnalysis::SCheckTrackPairs::SCheckTrackPairs (const string & name = "CheckTrackPairs") inline
Definition at line 76 of file SCheckTrackPairs.h.
View newest version in sPHENIX GitHub at line 76 of file SCheckTrackPairs.h
SColdQcdCorrelatorAnalysis::SCheckTrackPairs::~SCheckTrackPairs () inline
Definition at line 77 of file SCheckTrackPairs.h.
View newest version in sPHENIX GitHub at line 77 of file SCheckTrackPairs.h
Member Function Documentation
void SColdQcdCorrelatorAnalysis::SCheckTrackPairs::DoDoubleTrackLoop (PHCompositeNode * topNode) private
Definition at line 205 of file SCheckTrackPairs.h.
View newest version in sPHENIX GitHub at line 205 of file SCheckTrackPairs.h
References parse_cmake_options::begin, SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::TrkInfo::dcaXY, SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::TrkInfo::dcaZ, end, SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::TrkInfo::ene, SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::TrkInfo::eta, Fill(), SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::GetTrackMap(), SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::TrkInfo::id, SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::TrkInfo::nInttClust, SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::TrkInfo::nInttLayer, SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::TrkInfo::nMvtxClust, SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::TrkInfo::nMvtxLayer, SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::TrkInfo::nTpcClust, SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::TrkInfo::nTpcLayer, SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::TrkInfo::phi, SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::TrkInfo::pt, SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::TrkInfo::ptErr, SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::TrkInfo::px, SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::TrkInfo::py, SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::TrkInfo::pz, SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::TrkInfo::quality, SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::TrkInfo::vtxX, SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::TrkInfo::vtxY, and SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::TrkInfo::vtxZ.
int SColdQcdCorrelatorAnalysis::SCheckTrackPairs::End (PHCompositeNode *) override virtual
Called at the end of all processing.
Reimplemented from SubsysReco.
Definition at line 127 of file SCheckTrackPairs.h.
View newest version in sPHENIX GitHub at line 127 of file SCheckTrackPairs.h
References Fun4AllReturnCodes::EVENT_OK.
int SColdQcdCorrelatorAnalysis::SCheckTrackPairs::Init (PHCompositeNode *) override virtual
Called during initialization. Typically this is where you can book histograms, and e.g. register them to Fun4AllServer (so they can be output to file using Fun4AllServer::dumpHistos() method).
Reimplemented from SubsysReco.
Definition at line 107 of file SCheckTrackPairs.h.
View newest version in sPHENIX GitHub at line 107 of file SCheckTrackPairs.h
References Fun4AllReturnCodes::EVENT_OK.
void SColdQcdCorrelatorAnalysis::SCheckTrackPairs::InitTuples () private
Definition at line 139 of file SCheckTrackPairs.h.
View newest version in sPHENIX GitHub at line 139 of file SCheckTrackPairs.h
References SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::FlattenLeafList().
bool SColdQcdCorrelatorAnalysis::SCheckTrackPairs::IsGoodTrack (SvtxTrack * track, PHCompositeNode * topNode) private
Definition at line 340 of file SCheckTrackPairs.h.
View newest version in sPHENIX GitHub at line 340 of file SCheckTrackPairs.h
References SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::IsFromPrimaryVtx(), SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::IsGoodTrackSeed(), and SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::IsInSigmaDcaCut().
int SColdQcdCorrelatorAnalysis::SCheckTrackPairs::process_event (PHCompositeNode *) override virtual
Called for each event. This is where you do the real work.
Reimplemented from SubsysReco.
Definition at line 117 of file SCheckTrackPairs.h.
View newest version in sPHENIX GitHub at line 117 of file SCheckTrackPairs.h
References Fun4AllReturnCodes::EVENT_OK.
void SColdQcdCorrelatorAnalysis::SCheckTrackPairs::ResetVectors () private
Definition at line 184 of file SCheckTrackPairs.h.
View newest version in sPHENIX GitHub at line 184 of file SCheckTrackPairs.h
void SColdQcdCorrelatorAnalysis::SCheckTrackPairs::SaveOutput () private
Definition at line 170 of file SCheckTrackPairs.h.
View newest version in sPHENIX GitHub at line 170 of file SCheckTrackPairs.h
References cd(), and Write().
Member Data Documentation
TNtuple* SColdQcdCorrelatorAnalysis::SCheckTrackPairs::m_ntTrackPairs private
Definition at line 99 of file SCheckTrackPairs.h.
View newest version in sPHENIX GitHub at line 99 of file SCheckTrackPairs.h
vector<TrkrDefs::cluskey> SColdQcdCorrelatorAnalysis::SCheckTrackPairs::m_vecClustKeysA private
Definition at line 95 of file SCheckTrackPairs.h.
View newest version in sPHENIX GitHub at line 95 of file SCheckTrackPairs.h
vector<TrkrDefs::cluskey> SColdQcdCorrelatorAnalysis::SCheckTrackPairs::m_vecClustKeysB private
Definition at line 96 of file SCheckTrackPairs.h.
View newest version in sPHENIX GitHub at line 96 of file SCheckTrackPairs.h
vector<float> SColdQcdCorrelatorAnalysis::SCheckTrackPairs::m_vecTrackPairLeaves private
Definition at line 94 of file SCheckTrackPairs.h.
View newest version in sPHENIX GitHub at line 94 of file SCheckTrackPairs.h
The documentation for this class was generated from the following file:
analysis/blob/master/AndersonAnalysisModules/ColdQcdCorrelatorAnalysis/SCorrelatorQAMaker/src/SCheckTrackPairs.h