Analysis Software: rcdaq/blob/master/rcdaq_server.cc File Reference
rcdaq_server.cc File Reference
#include "rcdaq_rpc.h"
#include "rcdaq_actions.h"
#include "parseargument.h"
#include "rcdaq.h"
#include "daq_device.h"
#include "rcdaq_plugin.h"
#include "all.h"
#include <iostream>
#include <sstream>
#include <iomanip>
#include <fstream>
#include <string.h>
#include <stdlib.h>
#include <dlfcn.h>
#include <rpc/pmap_clnt.h>
#include <stdio.h>
#include <unistd.h>
#include "pthread.h"
#include "signal.h"
#include <sys/file.h>
#include <errno.h>
#include <sys/stat.h>
#include <sys/types.h>
#include <vector>
#include <set>
Functions
void rcdaq_1 (struct svc_req *rqstp, SVCXPRT *transp)
void sig_handler (int i)
void plugin_register (RCDAQPlugin *p)
void plugin_unregister (RCDAQPlugin *p)
int daq_load_plugin (const char *sharedlib, std::ostream &os)
int daq_status_plugin (const int flag, std::ostream &os)
shortResult * r_create_device_1_svc (deviceblock *db, struct svc_req *rqstp)
shortResult * r_action_1_svc (actionblock *ab, struct svc_req *rqstp)
shortResult * r_shutdown_1_svc (void *x, struct svc_req *rqstp)
int main (int argc, char **argv)
Variables
static pthread_mutex_t M_output
std::vector< RCDAQPlugin * > pluginlist
static unsigned long my_servernumber = 0
static int pid_fd = 0
Function Documentation
int daq_load_plugin (const char * sharedlib, std::ostream & os)
Definition at line 81 of file rcdaq_server.cc.
View newest version in sPHENIX GitHub at line 81 of file rcdaq_server.cc
References testSigmaEff::v.
Referenced by r_action_1_svc().
int daq_status_plugin (const int flag, std::ostream & os)
Definition at line 114 of file rcdaq_server.cc.
View newest version in sPHENIX GitHub at line 114 of file rcdaq_server.cc
References Eventiterator::identify(), it, and pluginlist.
Referenced by daq_status().
int main (int argc, char ** argv)
Definition at line 944 of file rcdaq_server.cc.
View newest version in sPHENIX GitHub at line 944 of file rcdaq_server.cc
References fprintf(), get_value(), i, M_output, mask, my_servernumber, obtain_pidfilename(), Acts::open, train_ambiguity_solver::pid, pid_fd, pidfilename, rcdaq_1(), rcdaq_init(), servernumber, sig_handler(), signal(), write(), and ambiguity_solver_full_chain::x.
void plugin_register (RCDAQPlugin * p)
Definition at line 69 of file rcdaq_server.cc.
View newest version in sPHENIX GitHub at line 69 of file rcdaq_server.cc
References pluginlist.
Referenced by RCDAQPlugin::RCDAQPlugin().
void plugin_unregister (RCDAQPlugin * p)
Definition at line 74 of file rcdaq_server.cc.
View newest version in sPHENIX GitHub at line 74 of file rcdaq_server.cc
Referenced by RCDAQPlugin::~RCDAQPlugin().
shortResult* r_action_1_svc (actionblock * ab, struct svc_req * rqstp)
Definition at line 477 of file rcdaq_server.cc.
View newest version in sPHENIX GitHub at line 477 of file rcdaq_server.cc
References DAQ_BEGIN, daq_begin(), DAQ_BEGIN_IMMEDIATE, daq_begin_immediate(), daq_clear_readlist(), DAQ_CLEARREADLIST, DAQ_CLOSE, daq_close(), daq_define_runtype(), DAQ_DEFINERUNTYPE, DAQ_ELOG, DAQ_END, DAQ_END_IMMEDIATE, daq_end_immediate(), daq_end_interactive(), daq_fake_trigger(), DAQ_FAKETRIGGER, DAQ_GET_MQTT_HOST, daq_get_mqtt_host(), daq_get_name(), DAQ_GET_RUNCONTROLMODE, daq_getlastevent_number(), DAQ_GETLASTEVENTNUMBER, DAQ_GETLASTFILENAME, daq_getlastfilename(), DAQ_GETNAME, daq_getRunControlMode(), DAQ_GETRUNTYPE, daq_getruntype(), daq_list_readlist(), daq_list_runtypes(), DAQ_LISTREADLIST, DAQ_LISTRUNTYPES, DAQ_LOAD, daq_load_plugin(), DAQ_OPEN, daq_open(), DAQ_ROLLOVERLIMIT, DAQ_RUNNUMBERFILE, DAQ_SET_COMPRESSION, daq_set_compression(), daq_set_eloghandler(), daq_set_filerule(), DAQ_SET_MQTT_HOST, daq_set_mqtt_host(), daq_set_name(), DAQ_SET_RUNCONTROLMODE, daq_set_runnumberApp(), daq_set_runnumberfile(), DAQ_SET_SERVER, daq_set_server(), DAQ_SETADAPTIVEBUFFER, daq_setadaptivebuffering(), DAQ_SETEVENTFORMAT, daq_setEventFormat(), DAQ_SETFILERULE, DAQ_SETMAXBUFFERSIZE, daq_setmaxbuffersize(), DAQ_SETMAXEVENTS, daq_setmaxevents(), DAQ_SETMAXVOLUME, daq_setmaxvolume(), DAQ_SETNAME, daq_setrolloverlimit(), daq_setRunControlMode(), DAQ_SETRUNNUMBERAPP, DAQ_SETRUNTYPE, daq_setruntype(), DAQ_STATUS, daq_status(), DAQ_SYNC, daq_wait_for_actual_end(), daq_wait_for_begin_done(), DAQ_WEBCONTROL, daq_webcontrol(), and M_output.
shortResult* r_create_device_1_svc (deviceblock * db, struct svc_req * rqstp)
Definition at line 142 of file rcdaq_server.cc.
View newest version in sPHENIX GitHub at line 142 of file rcdaq_server.cc
References add_readoutdevice(), daq_running(), acts::error, get_value(), it, pluginlist, physmon_simulation::s, and utils::status.
shortResult* r_shutdown_1_svc (void * x, struct svc_req * rqstp)
Definition at line 906 of file rcdaq_server.cc.
View newest version in sPHENIX GitHub at line 906 of file rcdaq_server.cc
References daq_shutdown(), M_output, my_servernumber, and pid_fd.
void rcdaq_1 (struct svc_req * rqstp, SVCXPRT * transp)
Referenced by main().
void sig_handler (int i)
Definition at line 53 of file rcdaq_server.cc.
View newest version in sPHENIX GitHub at line 53 of file rcdaq_server.cc
References M_cout, obtain_pidfilename(), pid_fd, pidfilename, TriggerControl, and verbose.
Variable Documentation
pthread_mutex_t M_output static
Definition at line 42 of file rcdaq_server.cc.
View newest version in sPHENIX GitHub at line 42 of file rcdaq_server.cc
Referenced by main(), r_action_1_svc(), and r_shutdown_1_svc().
unsigned long my_servernumber = 0 static
Definition at line 46 of file rcdaq_server.cc.
View newest version in sPHENIX GitHub at line 46 of file rcdaq_server.cc
Referenced by main(), and r_shutdown_1_svc().
int pid_fd = 0 static
Definition at line 50 of file rcdaq_server.cc.
View newest version in sPHENIX GitHub at line 50 of file rcdaq_server.cc
Referenced by daq_shutdown(), main(), r_shutdown_1_svc(), shutdown_thread(), and sig_handler().
std::vector<RCDAQPlugin *> pluginlist
Definition at line 44 of file rcdaq_server.cc.
View newest version in sPHENIX GitHub at line 44 of file rcdaq_server.cc
Referenced by daq_status_plugin(), plugin_register(), and r_create_device_1_svc().