Analysis Software: RetowerCEMC Class Reference
RetowerCEMC Class Reference
creates 0.1x0.1-towerized CEMC container
#include <coresoftware/blob/master/offline/packages/jetbackground/RetowerCEMC.h>
Public Member Functions
RetowerCEMC (const std::string &name="RetowerCEMC")
~RetowerCEMC () override
int InitRun (PHCompositeNode *topNode) override
int process_event (PHCompositeNode *topNode) override
void SetEnergyDistribution (int val)
void set_towerinfo (bool use_towerinfo)
Public Member Functions inherited from SubsysReco
~SubsysReco () override
virtual int End (PHCompositeNode *)
Called at the end of all processing.
virtual int EndRun (const int)
Called at the end of each run.
virtual int Init (PHCompositeNode *)
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
void Print (const std::string &="ALL") const override
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Private Member Functions
int CreateNode (PHCompositeNode *topNode)
Private Attributes
int _WEIGHTED_ENERGY_DISTRIBUTION
int _NETA
int _NPHI
bool m_use_towerinfo = false
std::vector< std::vector< float > > _EMCAL_RETOWER_E
std::vector< std::vector< int > > _EMCAL_RETOWER_T
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = std::numeric_limits<int>::max() - 10
}
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Detailed Description
creates 0.1x0.1-towerized CEMC container
Using the existing CEMC tower collection, creates a new 0.1x0.1-towerized version appropriate for HI jet reconstruction
Definition at line 26 of file RetowerCEMC.h.
View newest version in sPHENIX GitHub at line 26 of file RetowerCEMC.h
Constructor & Destructor Documentation
RetowerCEMC::RetowerCEMC (const std::string & name = "RetowerCEMC")
Definition at line 30 of file RetowerCEMC.cc.
View newest version in sPHENIX GitHub at line 30 of file RetowerCEMC.cc
RetowerCEMC::~RetowerCEMC () inline override
Definition at line 30 of file RetowerCEMC.h.
View newest version in sPHENIX GitHub at line 30 of file RetowerCEMC.h
Member Function Documentation
int RetowerCEMC::CreateNode (PHCompositeNode * topNode) private
Definition at line 260 of file RetowerCEMC.cc.
View newest version in sPHENIX GitHub at line 260 of file RetowerCEMC.cc
References Fun4AllReturnCodes::ABORTRUN, PHCompositeNode::addNode(), Fun4AllReturnCodes::EVENT_OK, PHNodeIterator::findFirst(), RawTowerDefs::HCALIN, m_use_towerinfo, PHWHERE, and Fun4AllBase::Verbosity().
Referenced by InitRun().
int RetowerCEMC::InitRun (PHCompositeNode *) override virtual
Called for first event when run number is known. Typically this is where you may want to fetch data from database, because you know the run number.
Reimplemented from SubsysReco.
Definition at line 38 of file RetowerCEMC.cc.
View newest version in sPHENIX GitHub at line 38 of file RetowerCEMC.cc
References CreateNode(), and Fun4AllReturnCodes::EVENT_OK.
int RetowerCEMC::process_event (PHCompositeNode *) override virtual
Called for each event. This is where you do the real work.
Reimplemented from SubsysReco.
Definition at line 45 of file RetowerCEMC.cc.
View newest version in sPHENIX GitHub at line 45 of file RetowerCEMC.cc
References _EMCAL_RETOWER_E, _EMCAL_RETOWER_T, _NETA, _NPHI, _WEIGHTED_ENERGY_DISTRIBUTION, Fun4AllReturnCodes::ABORTRUN, RawTowerContainer::AddTower(), Enable::CEMC, channel(), TowerInfoContainer::decode_key(), TowerInfoContainer::encode_key(), RawTowerDefs::encode_towerid(), eta, Fun4AllReturnCodes::EVENT_OK, RawTowerGeom::get_bineta(), TowerInfo::get_energy(), RawTower::get_energy(), RawTowerGeom::get_eta(), RawTowerGeomContainer::get_etabounds(), RawTower::get_key(), RawTowerGeom::get_phi(), TowerInfo::get_time(), TowerInfoContainer::get_tower_at_channel(), RawTowerGeomContainer::get_tower_geometry(), TowerInfoContainer::getTowerEtaBin(), TowerInfoContainer::getTowerPhiBin(), RawTowerContainer::getTowers(), m_use_towerinfo, ActsTests::PropagationDatasets::phi, PHWHERE, TowerInfo::set_energy(), RawTower::set_energy(), TowerInfo::set_time(), TowerInfoContainer::size(), RawTowerContainer::size(), and Fun4AllBase::Verbosity().
void RetowerCEMC::set_towerinfo (bool use_towerinfo) inline
Definition at line 35 of file RetowerCEMC.h.
View newest version in sPHENIX GitHub at line 35 of file RetowerCEMC.h
References m_use_towerinfo.
Referenced by Fun4All_JetBkgd(), and HIJetReco().
void RetowerCEMC::SetEnergyDistribution (int val) inline
Definition at line 34 of file RetowerCEMC.h.
View newest version in sPHENIX GitHub at line 34 of file RetowerCEMC.h
References _WEIGHTED_ENERGY_DISTRIBUTION.
Member Data Documentation
std::vector<std::vector<float> > RetowerCEMC::_EMCAL_RETOWER_E private
Definition at line 45 of file RetowerCEMC.h.
View newest version in sPHENIX GitHub at line 45 of file RetowerCEMC.h
Referenced by process_event().
std::vector<std::vector<int> > RetowerCEMC::_EMCAL_RETOWER_T private
Definition at line 46 of file RetowerCEMC.h.
View newest version in sPHENIX GitHub at line 46 of file RetowerCEMC.h
Referenced by process_event().
int RetowerCEMC::_NETA private
Definition at line 42 of file RetowerCEMC.h.
View newest version in sPHENIX GitHub at line 42 of file RetowerCEMC.h
Referenced by process_event().
int RetowerCEMC::_NPHI private
Definition at line 43 of file RetowerCEMC.h.
View newest version in sPHENIX GitHub at line 43 of file RetowerCEMC.h
Referenced by process_event().
int RetowerCEMC::_WEIGHTED_ENERGY_DISTRIBUTION private
Definition at line 41 of file RetowerCEMC.h.
View newest version in sPHENIX GitHub at line 41 of file RetowerCEMC.h
Referenced by process_event(), and SetEnergyDistribution().
bool RetowerCEMC::m_use_towerinfo = false private
Definition at line 44 of file RetowerCEMC.h.
View newest version in sPHENIX GitHub at line 44 of file RetowerCEMC.h
Referenced by CreateNode(), process_event(), and set_towerinfo().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/jetbackground/RetowerCEMC.h
coresoftware/blob/master/offline/packages/jetbackground/RetowerCEMC.cc