Analysis Software: BaseTruthEval Class Reference
BaseTruthEval Class Reference
#include <coresoftware/blob/master/simulation/g4simulation/g4eval/BaseTruthEval.h>
Public Member Functions
BaseTruthEval (PHCompositeNode *topNode)
virtual ~BaseTruthEval ()
void next_event (PHCompositeNode *topNode)
reinitialize the eval for a new event
void set_strict (bool strict)
unsigned int get_errors ()
get a count of the errors discovered thus far
void set_verbosity (int verbosity)
adjust the messaging from the evalutaion module
bool has_reduced_node_pointers ()
int get_embed (PHG4Particle *particle)
what was the embed flag set for this particle?
PHG4VtxPoint * get_vertex (PHG4Particle *particle)
what was the vertex creation point of the particle?
bool is_primary (PHG4Shower *shower)
is this a primary shower?
bool is_primary (PHG4Particle *particle)
is this a primary particle?
PHG4Shower * get_primary_shower (PHG4Shower *shower)
what was the primary shower for this possibly secondary shower?
PHG4Shower * get_primary_shower (PHG4Particle *particle)
what was the primary shower that is associated with this particle?
PHG4Particle * get_primary_particle (PHG4Particle *particle)
what was the primary particle that is associated with this particle?
PHG4Particle * get_primary_particle (PHG4Shower *shower)
what was the primary particle that is associated with this shower?
std::set< PHG4Shower * > all_secondary_showers (PHG4Shower *shower)
which secondary showers are inside this shower?
bool are_same_shower (PHG4Shower *s1, PHG4Shower *s2)
do these two shower pointers resolve to the same shower?
bool are_same_particle (PHG4Particle *p1, PHG4Particle *p2)
do these two particle pointers resolve to the same particle?
bool are_same_vertex (PHG4VtxPoint *vtx1, PHG4VtxPoint *vtx2)
do these two vertex pointers resolve to the same vertex?
bool has_full_node_pointers ()
PHG4Particle * get_particle (PHG4Hit *g4hit)
which particle left this truth hit?
PHG4Shower * get_primary_shower (PHG4Hit *g4hit)
which primary shower contains this truth hit?
PHG4Particle * get_primary_particle (PHG4Hit *g4hit)
which primary particle resulted in this truth hit?
PHG4Particle * get_particle (const int trackid)
which is the particle associated with this track ID?
bool is_g4hit_from_primary_shower (PHG4Hit *g4hit, PHG4Shower *shower)
is this truth hit inside this shower?
bool is_g4hit_from_particle (PHG4Hit *g4hit, PHG4Particle *particle)
was this truth hit left by this particle?
Private Member Functions
void get_node_pointers (PHCompositeNode *topNode)
Private Attributes
PHG4TruthInfoContainer * m_TruthInfo = nullptr
bool m_Strict = false
int m_Verbosity = 0
unsigned int m_Errors = 0
Detailed Description
Definition at line 13 of file BaseTruthEval.h.
View newest version in sPHENIX GitHub at line 13 of file BaseTruthEval.h
Constructor & Destructor Documentation
BaseTruthEval::BaseTruthEval (PHCompositeNode * topNode) explicit
Definition at line 17 of file BaseTruthEval.cc.
View newest version in sPHENIX GitHub at line 17 of file BaseTruthEval.cc
References get_node_pointers().
BaseTruthEval::~BaseTruthEval () virtual
Definition at line 22 of file BaseTruthEval.cc.
View newest version in sPHENIX GitHub at line 22 of file BaseTruthEval.cc
References m_Errors, and m_Verbosity.
Member Function Documentation
std::set< PHG4Shower * > BaseTruthEval::all_secondary_showers (PHG4Shower * shower)
which secondary showers are inside this shower?
Definition at line 322 of file BaseTruthEval.cc.
View newest version in sPHENIX GitHub at line 322 of file BaseTruthEval.cc
References assert, PHG4Shower::get_id(), PHG4Shower::get_parent_shower_id(), PHG4TruthInfoContainer::GetSecondaryShowerRange(), has_reduced_node_pointers(), m_Errors, m_Strict, and m_TruthInfo.
bool BaseTruthEval::are_same_particle (PHG4Particle * p1, PHG4Particle * p2)
do these two particle pointers resolve to the same particle?
Definition at line 396 of file BaseTruthEval.cc.
View newest version in sPHENIX GitHub at line 396 of file BaseTruthEval.cc
References assert, PHG4Particle::get_track_id(), has_reduced_node_pointers(), m_Errors, and m_Strict.
Referenced by SvtxTruthEval::are_same_particle(), and CaloTruthEval::are_same_particle().
bool BaseTruthEval::are_same_shower (PHG4Shower * s1, PHG4Shower * s2)
do these two shower pointers resolve to the same shower?
Definition at line 370 of file BaseTruthEval.cc.
View newest version in sPHENIX GitHub at line 370 of file BaseTruthEval.cc
References assert, PHG4Shower::get_id(), has_reduced_node_pointers(), m_Errors, and m_Strict.
Referenced by CaloTruthEval::are_same_shower().
bool BaseTruthEval::are_same_vertex (PHG4VtxPoint * vtx1, PHG4VtxPoint * vtx2)
do these two vertex pointers resolve to the same vertex?
Definition at line 422 of file BaseTruthEval.cc.
View newest version in sPHENIX GitHub at line 422 of file BaseTruthEval.cc
References assert, PHG4VtxPoint::get_id(), has_reduced_node_pointers(), m_Errors, and m_Strict.
Referenced by SvtxTruthEval::are_same_vertex(), and CaloTruthEval::are_same_vertex().
int BaseTruthEval::get_embed (PHG4Particle * particle)
what was the embed flag set for this particle?
Definition at line 38 of file BaseTruthEval.cc.
View newest version in sPHENIX GitHub at line 38 of file BaseTruthEval.cc
References assert, get_primary_particle(), PHG4Particle::get_track_id(), has_reduced_node_pointers(), PHG4TruthInfoContainer::isEmbeded(), m_Errors, m_Strict, and m_TruthInfo.
Referenced by SvtxTruthEval::get_embed(), and CaloTruthEval::get_embed().
unsigned int BaseTruthEval::get_errors () inline
get a count of the errors discovered thus far
Definition at line 27 of file BaseTruthEval.h.
View newest version in sPHENIX GitHub at line 27 of file BaseTruthEval.h
References m_Errors.
Referenced by SvtxTruthEval::get_errors().
void BaseTruthEval::get_node_pointers (PHCompositeNode * topNode) private
Definition at line 602 of file BaseTruthEval.cc.
View newest version in sPHENIX GitHub at line 602 of file BaseTruthEval.cc
References m_TruthInfo, and PHWHERE.
Referenced by BaseTruthEval(), and next_event().
PHG4Particle * BaseTruthEval::get_particle (PHG4Hit * g4hit)
which particle left this truth hit?
Definition at line 448 of file BaseTruthEval.cc.
View newest version in sPHENIX GitHub at line 448 of file BaseTruthEval.cc
References assert, PHG4Hit::get_trkid(), PHG4TruthInfoContainer::GetParticle(), has_reduced_node_pointers(), m_Errors, m_Strict, m_TruthInfo, and particle.
Referenced by CaloTruthEval::get_parent_particle(), SvtxTruthEval::get_particle(), and get_primary_particle().
PHG4Particle * BaseTruthEval::get_particle (const int trackid)
which is the particle associated with this track ID?
Definition at line 543 of file BaseTruthEval.cc.
View newest version in sPHENIX GitHub at line 543 of file BaseTruthEval.cc
References PHG4TruthInfoContainer::GetParticle(), and m_TruthInfo.
PHG4Particle * BaseTruthEval::get_primary_particle (PHG4Particle * particle)
what was the primary particle that is associated with this particle?
Definition at line 240 of file BaseTruthEval.cc.
View newest version in sPHENIX GitHub at line 240 of file BaseTruthEval.cc
References assert, PHG4Particle::get_primary_id(), PHG4TruthInfoContainer::GetPrimaryParticle(), has_reduced_node_pointers(), is_primary(), m_Errors, m_Strict, m_TruthInfo, and particle.
Referenced by get_embed(), SvtxTruthEval::get_primary_particle(), get_primary_particle(), CaloTruthEval::get_primary_particle(), and get_primary_shower().
PHG4Particle * BaseTruthEval::get_primary_particle (PHG4Shower * shower)
what was the primary particle that is associated with this shower?
Definition at line 277 of file BaseTruthEval.cc.
View newest version in sPHENIX GitHub at line 277 of file BaseTruthEval.cc
References assert, PHG4Shower::get_parent_particle_id(), get_primary_particle(), PHG4TruthInfoContainer::GetParticle(), has_reduced_node_pointers(), m_Errors, m_Strict, and m_TruthInfo.
PHG4Particle * BaseTruthEval::get_primary_particle (PHG4Hit * g4hit)
which primary particle resulted in this truth hit?
Definition at line 510 of file BaseTruthEval.cc.
View newest version in sPHENIX GitHub at line 510 of file BaseTruthEval.cc
References assert, get_particle(), get_primary_particle(), has_reduced_node_pointers(), m_Errors, m_Strict, and particle.
PHG4Shower * BaseTruthEval::get_primary_shower (PHG4Shower * shower)
what was the primary shower for this possibly secondary shower?
Definition at line 158 of file BaseTruthEval.cc.
View newest version in sPHENIX GitHub at line 158 of file BaseTruthEval.cc
References assert, PHG4Shower::get_parent_shower_id(), PHG4TruthInfoContainer::GetShower(), has_reduced_node_pointers(), is_primary(), m_Errors, m_Strict, and m_TruthInfo.
Referenced by CaloTruthEval::get_primary_shower().
PHG4Shower * BaseTruthEval::get_primary_shower (PHG4Particle * particle)
what was the primary shower that is associated with this particle?
Definition at line 199 of file BaseTruthEval.cc.
View newest version in sPHENIX GitHub at line 199 of file BaseTruthEval.cc
References assert, PHG4Shower::get_parent_particle_id(), get_primary_particle(), PHG4Particle::get_track_id(), PHG4TruthInfoContainer::GetPrimaryShowerRange(), has_reduced_node_pointers(), is_primary(), m_Errors, m_Strict, and m_TruthInfo.
PHG4Shower * BaseTruthEval::get_primary_shower (PHG4Hit * g4hit)
which primary shower contains this truth hit?
Definition at line 479 of file BaseTruthEval.cc.
View newest version in sPHENIX GitHub at line 479 of file BaseTruthEval.cc
References assert, PHG4Hit::get_shower_id(), PHG4TruthInfoContainer::GetShower(), has_reduced_node_pointers(), m_Errors, m_Strict, and m_TruthInfo.
PHG4VtxPoint * BaseTruthEval::get_vertex (PHG4Particle * particle)
what was the vertex creation point of the particle?
Definition at line 73 of file BaseTruthEval.cc.
View newest version in sPHENIX GitHub at line 73 of file BaseTruthEval.cc
References assert, PHG4Particle::get_vtx_id(), PHG4TruthInfoContainer::GetVtx(), has_reduced_node_pointers(), m_Errors, m_Strict, and m_TruthInfo.
Referenced by SvtxTruthEval::get_vertex(), and CaloTruthEval::get_vertex().
bool BaseTruthEval::has_full_node_pointers () inline
Definition at line 74 of file BaseTruthEval.h.
View newest version in sPHENIX GitHub at line 74 of file BaseTruthEval.h
References has_reduced_node_pointers().
Referenced by CaloTruthEval::has_full_node_pointers().
bool BaseTruthEval::has_reduced_node_pointers ()
Definition at line 614 of file BaseTruthEval.cc.
View newest version in sPHENIX GitHub at line 614 of file BaseTruthEval.cc
References assert, m_Strict, and m_TruthInfo.
Referenced by all_secondary_showers(), are_same_particle(), are_same_shower(), are_same_vertex(), get_embed(), get_particle(), get_primary_particle(), get_primary_shower(), get_vertex(), has_full_node_pointers(), CaloTruthEval::has_reduced_node_pointers(), is_g4hit_from_particle(), is_g4hit_from_primary_shower(), and is_primary().
bool BaseTruthEval::is_g4hit_from_particle (PHG4Hit * g4hit, PHG4Particle * particle)
was this truth hit left by this particle?
Definition at line 575 of file BaseTruthEval.cc.
View newest version in sPHENIX GitHub at line 575 of file BaseTruthEval.cc
References assert, PHG4Particle::get_track_id(), PHG4Hit::get_trkid(), has_reduced_node_pointers(), m_Errors, and m_Strict.
Referenced by SvtxTruthEval::is_g4hit_from_particle(), and CaloTruthEval::is_g4hit_from_particle().
bool BaseTruthEval::is_g4hit_from_primary_shower (PHG4Hit * g4hit, PHG4Shower * shower)
is this truth hit inside this shower?
Definition at line 548 of file BaseTruthEval.cc.
View newest version in sPHENIX GitHub at line 548 of file BaseTruthEval.cc
References assert, PHG4Shower::get_id(), PHG4Hit::get_shower_id(), has_reduced_node_pointers(), m_Errors, and m_Strict.
bool BaseTruthEval::is_primary (PHG4Shower * shower)
is this a primary shower?
Definition at line 104 of file BaseTruthEval.cc.
View newest version in sPHENIX GitHub at line 104 of file BaseTruthEval.cc
References assert, PHG4Shower::get_parent_shower_id(), has_reduced_node_pointers(), m_Errors, and m_Strict.
Referenced by get_primary_particle(), get_primary_shower(), is_primary(), SvtxTruthEval::is_primary(), and CaloTruthEval::is_primary().
bool BaseTruthEval::is_primary (PHG4Particle * particle)
is this a primary particle?
Definition at line 131 of file BaseTruthEval.cc.
View newest version in sPHENIX GitHub at line 131 of file BaseTruthEval.cc
References assert, PHG4Particle::get_parent_id(), has_reduced_node_pointers(), is_primary(), m_Errors, and m_Strict.
void BaseTruthEval::next_event (PHCompositeNode * topNode)
reinitialize the eval for a new event
Definition at line 33 of file BaseTruthEval.cc.
View newest version in sPHENIX GitHub at line 33 of file BaseTruthEval.cc
References get_node_pointers().
Referenced by CaloTruthEval::next_event(), and SvtxTruthEval::next_event().
void BaseTruthEval::set_strict (bool strict) inline
strict mode will assert when an error is detected non-strict mode will notice and report at the End()
Definition at line 24 of file BaseTruthEval.h.
View newest version in sPHENIX GitHub at line 24 of file BaseTruthEval.h
References m_Strict.
Referenced by SvtxTruthEval::set_strict(), and CaloTruthEval::set_strict().
void BaseTruthEval::set_verbosity (int verbosity) inline
adjust the messaging from the evalutaion module
Definition at line 30 of file BaseTruthEval.h.
View newest version in sPHENIX GitHub at line 30 of file BaseTruthEval.h
References m_Verbosity, and verbosity.
Referenced by SvtxTruthEval::set_verbosity(), and CaloTruthEval::set_verbosity().
Member Data Documentation
unsigned int BaseTruthEval::m_Errors = 0 private
Definition at line 101 of file BaseTruthEval.h.
View newest version in sPHENIX GitHub at line 101 of file BaseTruthEval.h
Referenced by all_secondary_showers(), are_same_particle(), are_same_shower(), are_same_vertex(), get_embed(), get_errors(), get_particle(), get_primary_particle(), get_primary_shower(), get_vertex(), is_g4hit_from_particle(), is_g4hit_from_primary_shower(), is_primary(), and ~BaseTruthEval().
bool BaseTruthEval::m_Strict = false private
Definition at line 99 of file BaseTruthEval.h.
View newest version in sPHENIX GitHub at line 99 of file BaseTruthEval.h
Referenced by all_secondary_showers(), are_same_particle(), are_same_shower(), are_same_vertex(), get_embed(), get_particle(), get_primary_particle(), get_primary_shower(), get_vertex(), has_reduced_node_pointers(), is_g4hit_from_particle(), is_g4hit_from_primary_shower(), is_primary(), and set_strict().
PHG4TruthInfoContainer* BaseTruthEval::m_TruthInfo = nullptr private
Definition at line 97 of file BaseTruthEval.h.
View newest version in sPHENIX GitHub at line 97 of file BaseTruthEval.h
Referenced by all_secondary_showers(), get_embed(), get_node_pointers(), get_particle(), get_primary_particle(), get_primary_shower(), get_vertex(), and has_reduced_node_pointers().
int BaseTruthEval::m_Verbosity = 0 private
Definition at line 100 of file BaseTruthEval.h.
View newest version in sPHENIX GitHub at line 100 of file BaseTruthEval.h
Referenced by set_verbosity(), and ~BaseTruthEval().
The documentation for this class was generated from the following files:
coresoftware/blob/master/simulation/g4simulation/g4eval/BaseTruthEval.h
coresoftware/blob/master/simulation/g4simulation/g4eval/BaseTruthEval.cc