Analysis Software: bfield_writing Namespace Reference
bfield_writing Namespace Reference
Functions
def RootBFieldWrite
def CsvBFieldWrite
def runBFieldWriting
Variables
u acts.UnitConstants
Function Documentation
def bfield_writing.CsvBFieldWrite (bField, fileName, level = acts.logging.VERBOSE)
Definition at line 20 of file bfield_writing.py.
View newest version in sPHENIX GitHub at line 20 of file bfield_writing.py
References str.
Referenced by runBFieldWriting().
def bfield_writing.RootBFieldWrite (bField, fileName, treeName = "solenoid", level = acts.logging.VERBOSE)
Definition at line 10 of file bfield_writing.py.
View newest version in sPHENIX GitHub at line 10 of file bfield_writing.py
References str.
Referenced by runBFieldWriting().
def bfield_writing.runBFieldWriting (outputDir)
Definition at line 28 of file bfield_writing.py.
View newest version in sPHENIX GitHub at line 28 of file bfield_writing.py
References CsvBFieldWrite(), print(), and RootBFieldWrite().
Referenced by test_examples.test_bfield_writing().
Variable Documentation
bfield_writing.u acts.UnitConstants
Definition at line 7 of file bfield_writing.py.
View newest version in sPHENIX GitHub at line 7 of file bfield_writing.py