Analysis Software: PHTpcTrackSeedVertexAssoc Class Reference
PHTpcTrackSeedVertexAssoc Class Reference
#include <coresoftware/blob/master/offline/packages/trackreco/PHTpcTrackSeedVertexAssoc.h>
Public Member Functions
PHTpcTrackSeedVertexAssoc (const std::string &name="PHTpcTrackSeedVertexAssoc")
~PHTpcTrackSeedVertexAssoc () override
void reject_xy_outliers (const bool reject)
void reject_z_outliers (const bool reject)
void set_xy_residual_cut (const double cut)
void set_z_residual_cut (const double cut)
void set_refit (const bool refit)
Public Member Functions inherited from PHTrackPropagating
PHTrackPropagating (const std::string &name="PHTrackPropagating")
~PHTrackPropagating () override
int InitRun (PHCompositeNode *topNode) override
int process_event (PHCompositeNode *topNode) override
int End (PHCompositeNode *topNode) override
Called at the end of all processing.
void set_track_map_name (const std::string &map_name)
void SetUseTruthClusters (bool setit)
Public Member Functions inherited from SubsysReco
~SubsysReco () override
virtual int EndRun (const int)
Called at the end of each run.
virtual int Init (PHCompositeNode *)
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
void Print (const std::string &what="ALL") const override
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Protected Member Functions
int Setup (PHCompositeNode *topNode) override
int Process () override
int End () override
Private Member Functions
int GetNodes (PHCompositeNode *topNode)
void line_fit_clusters (std::vector< TrkrCluster * > clusters, double &a, double &b)
void line_fit (std::vector< std::pair< double, double >> points, double &a, double &b)
void CircleFitByTaubin (std::vector< std::pair< double, double >> points, double &R, double &X0, double &Y0)
std::vector< double > GetCircleClusterResiduals (std::vector< std::pair< double, double >> points, double R, double X0, double Y0)
std::vector< double > GetLineClusterResiduals (std::vector< std::pair< double, double >> points, double A, double B)
std::vector< TrkrCluster * > getTrackClusters (SvtxTrack *_tracklet_tpc)
Private Attributes
std::string _track_map_name_silicon
SvtxTrack * _tracklet_tpc {nullptr}
unsigned int _min_tpc_layer = 7
unsigned int _max_tpc_layer = 54
double _z_proj = 0
bool _reject_xy_outliers = false
bool _reject_z_outliers = false
bool _refit = false
double _xy_residual_cut = 0.08
double _z_residual_cut = 0.22
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = INT_MAX - 10
}
Protected Attributes inherited from PHTrackPropagating
TrkrClusterContainer * _cluster_map
TrkrHitSetContainer * _hitsets
SvtxVertexMap * _vertex_map
SvtxTrackMap * _track_map
AssocInfoContainer * _assoc_container
std::string _track_map_name
bool _use_truth_clusters = false
Detailed Description
Definition at line 18 of file PHTpcTrackSeedVertexAssoc.h.
View newest version in sPHENIX GitHub at line 18 of file PHTpcTrackSeedVertexAssoc.h
Constructor & Destructor Documentation
PHTpcTrackSeedVertexAssoc::PHTpcTrackSeedVertexAssoc (const std::string & name = "PHTpcTrackSeedVertexAssoc")
Definition at line 38 of file PHTpcTrackSeedVertexAssoc.cc.
View newest version in sPHENIX GitHub at line 38 of file PHTpcTrackSeedVertexAssoc.cc
PHTpcTrackSeedVertexAssoc::~PHTpcTrackSeedVertexAssoc () override
Definition at line 46 of file PHTpcTrackSeedVertexAssoc.cc.
View newest version in sPHENIX GitHub at line 46 of file PHTpcTrackSeedVertexAssoc.cc
Member Function Documentation
void PHTpcTrackSeedVertexAssoc::CircleFitByTaubin (std::vector< std::pair< double, double >> points, double & R, double & X0, double & Y0) private
Definition at line 525 of file PHTpcTrackSeedVertexAssoc.cc.
View newest version in sPHENIX GitHub at line 525 of file PHTpcTrackSeedVertexAssoc.cc
References Dy, i, x, and y.
Referenced by Process().
int PHTpcTrackSeedVertexAssoc::End () override protected virtual
Implements PHTrackPropagating.
Definition at line 461 of file PHTpcTrackSeedVertexAssoc.cc.
View newest version in sPHENIX GitHub at line 461 of file PHTpcTrackSeedVertexAssoc.cc
References Fun4AllReturnCodes::EVENT_OK.
std::vector< double > PHTpcTrackSeedVertexAssoc::GetCircleClusterResiduals (std::vector< std::pair< double, double >> points, double R, double X0, double Y0) private
Definition at line 618 of file PHTpcTrackSeedVertexAssoc.cc.
View newest version in sPHENIX GitHub at line 618 of file PHTpcTrackSeedVertexAssoc.cc
References i, Acts::IntegrationTest::R, x, and y.
Referenced by Process().
std::vector< double > PHTpcTrackSeedVertexAssoc::GetLineClusterResiduals (std::vector< std::pair< double, double >> points, double A, double B) private
Definition at line 634 of file PHTpcTrackSeedVertexAssoc.cc.
View newest version in sPHENIX GitHub at line 634 of file PHTpcTrackSeedVertexAssoc.cc
References KFPMath::a, A, KFPMath::b, c, i, r, and z.
Referenced by Process().
int PHTpcTrackSeedVertexAssoc::GetNodes (PHCompositeNode * topNode) private
Definition at line 466 of file PHTpcTrackSeedVertexAssoc.cc.
View newest version in sPHENIX GitHub at line 466 of file PHTpcTrackSeedVertexAssoc.cc
References Fun4AllReturnCodes::EVENT_OK.
Referenced by Setup().
std::vector< TrkrCluster * > PHTpcTrackSeedVertexAssoc::getTrackClusters (SvtxTrack * _tracklet_tpc) private
Definition at line 655 of file PHTpcTrackSeedVertexAssoc.cc.
View newest version in sPHENIX GitHub at line 655 of file PHTpcTrackSeedVertexAssoc.cc
References PHTrackPropagating::_cluster_map, _max_tpc_layer, _min_tpc_layer, SvtxTrack::begin_cluster_keys(), SvtxTrack::end_cluster_keys(), TrkrClusterContainer::findCluster(), TrkrDefs::getLayer(), TrkrCluster::getX(), TrkrCluster::getY(), TrkrCluster::getZ(), layer, and Fun4AllBase::Verbosity().
Referenced by Process().
void PHTpcTrackSeedVertexAssoc::line_fit (std::vector< std::pair< double, double >> points, double & a, double & b) private
Definition at line 476 of file PHTpcTrackSeedVertexAssoc.cc.
View newest version in sPHENIX GitHub at line 476 of file PHTpcTrackSeedVertexAssoc.cc
References KFPMath::b, i, r, Fun4AllBase::Verbosity(), and z.
Referenced by line_fit_clusters(), and Process().
void PHTpcTrackSeedVertexAssoc::line_fit_clusters (std::vector< TrkrCluster * > clusters, double & a, double & b) private
Definition at line 508 of file PHTpcTrackSeedVertexAssoc.cc.
View newest version in sPHENIX GitHub at line 508 of file PHTpcTrackSeedVertexAssoc.cc
References i, line_fit(), r, and z.
Referenced by Process().
int PHTpcTrackSeedVertexAssoc::Process () override protected virtual
process event interface for trackers, called in process_event. implemented in derived classes
Implements PHTrackPropagating.
Definition at line 68 of file PHTpcTrackSeedVertexAssoc.cc.
View newest version in sPHENIX GitHub at line 68 of file PHTpcTrackSeedVertexAssoc.cc
References _refit, _reject_xy_outliers, _reject_z_outliers, PHTrackPropagating::_track_map, _tracklet_tpc, PHTrackPropagating::_vertex_map, _xy_residual_cut, _z_proj, _z_residual_cut, A, SvtxTrackMap::begin(), SvtxVertexMap::begin(), CircleFitByTaubin(), dx, dy, dz, SvtxTrackMap::end(), SvtxVertexMap::end(), SvtxTrackMap::erase(), SvtxTrack::erase_cluster_key(), Fun4AllReturnCodes::EVENT_OK, SvtxVertexMap::find(), SvtxTrack::get_charge(), SvtxTrack::get_eta(), SvtxTrack::get_id(), SvtxTrack::get_p(), SvtxTrack::get_phi(), SvtxTrack::get_pt(), SvtxTrack::get_px(), SvtxTrack::get_py(), SvtxTrack::get_pz(), GetCircleClusterResiduals(), TrkrDefs::getLayer(), GetLineClusterResiduals(), getTrackClusters(), i, layer, line_fit(), line_fit_clusters(), M_PI, phi, PHWHERE, Acts::IntegrationTest::R, r, SvtxTrack::set_px(), SvtxTrack::set_py(), SvtxTrack::set_pz(), SvtxTrack::set_vertex_id(), SvtxTrack::set_x(), SvtxTrack::set_y(), SvtxTrack::set_z(), SvtxTrackMap::size(), Fun4AllBase::Verbosity(), x, y, and z.
void PHTpcTrackSeedVertexAssoc::reject_xy_outliers (const bool reject) inline
Definition at line 26 of file PHTpcTrackSeedVertexAssoc.h.
View newest version in sPHENIX GitHub at line 26 of file PHTpcTrackSeedVertexAssoc.h
References _reject_xy_outliers.
void PHTpcTrackSeedVertexAssoc::reject_z_outliers (const bool reject) inline
Definition at line 27 of file PHTpcTrackSeedVertexAssoc.h.
View newest version in sPHENIX GitHub at line 27 of file PHTpcTrackSeedVertexAssoc.h
References _reject_z_outliers.
void PHTpcTrackSeedVertexAssoc::set_refit (const bool refit) inline
Definition at line 31 of file PHTpcTrackSeedVertexAssoc.h.
View newest version in sPHENIX GitHub at line 31 of file PHTpcTrackSeedVertexAssoc.h
References _refit.
void PHTpcTrackSeedVertexAssoc::set_xy_residual_cut (const double cut) inline
Definition at line 29 of file PHTpcTrackSeedVertexAssoc.h.
View newest version in sPHENIX GitHub at line 29 of file PHTpcTrackSeedVertexAssoc.h
References _xy_residual_cut.
void PHTpcTrackSeedVertexAssoc::set_z_residual_cut (const double cut) inline
Definition at line 30 of file PHTpcTrackSeedVertexAssoc.h.
View newest version in sPHENIX GitHub at line 30 of file PHTpcTrackSeedVertexAssoc.h
References _z_residual_cut.
int PHTpcTrackSeedVertexAssoc::Setup (PHCompositeNode * topNode) override protected virtual
setup interface for trackers, called in InitRun, setup things like pointers to nodes. overrided in derived classes
Reimplemented from PHTrackPropagating.
Definition at line 52 of file PHTpcTrackSeedVertexAssoc.cc.
View newest version in sPHENIX GitHub at line 52 of file PHTpcTrackSeedVertexAssoc.cc
References _refit, _reject_xy_outliers, _reject_z_outliers, _xy_residual_cut, _z_residual_cut, Fun4AllReturnCodes::EVENT_OK, GetNodes(), PHWHERE, and PHTrackPropagating::Setup().
Member Data Documentation
unsigned int PHTpcTrackSeedVertexAssoc::_max_tpc_layer = 54 private
Definition at line 57 of file PHTpcTrackSeedVertexAssoc.h.
View newest version in sPHENIX GitHub at line 57 of file PHTpcTrackSeedVertexAssoc.h
Referenced by getTrackClusters().
unsigned int PHTpcTrackSeedVertexAssoc::_min_tpc_layer = 7 private
Definition at line 56 of file PHTpcTrackSeedVertexAssoc.h.
View newest version in sPHENIX GitHub at line 56 of file PHTpcTrackSeedVertexAssoc.h
Referenced by getTrackClusters().
bool PHTpcTrackSeedVertexAssoc::_refit = false private
Definition at line 63 of file PHTpcTrackSeedVertexAssoc.h.
View newest version in sPHENIX GitHub at line 63 of file PHTpcTrackSeedVertexAssoc.h
Referenced by Process(), set_refit(), and Setup().
bool PHTpcTrackSeedVertexAssoc::_reject_xy_outliers = false private
Definition at line 61 of file PHTpcTrackSeedVertexAssoc.h.
View newest version in sPHENIX GitHub at line 61 of file PHTpcTrackSeedVertexAssoc.h
Referenced by Process(), reject_xy_outliers(), and Setup().
bool PHTpcTrackSeedVertexAssoc::_reject_z_outliers = false private
Definition at line 62 of file PHTpcTrackSeedVertexAssoc.h.
View newest version in sPHENIX GitHub at line 62 of file PHTpcTrackSeedVertexAssoc.h
Referenced by Process(), reject_z_outliers(), and Setup().
std::string PHTpcTrackSeedVertexAssoc::_track_map_name_silicon private
Definition at line 51 of file PHTpcTrackSeedVertexAssoc.h.
View newest version in sPHENIX GitHub at line 51 of file PHTpcTrackSeedVertexAssoc.h
SvtxTrack* PHTpcTrackSeedVertexAssoc::_tracklet_tpc {nullptr} private
Definition at line 54 of file PHTpcTrackSeedVertexAssoc.h.
View newest version in sPHENIX GitHub at line 54 of file PHTpcTrackSeedVertexAssoc.h
Referenced by Process().
double PHTpcTrackSeedVertexAssoc::_xy_residual_cut = 0.08 private
Definition at line 65 of file PHTpcTrackSeedVertexAssoc.h.
View newest version in sPHENIX GitHub at line 65 of file PHTpcTrackSeedVertexAssoc.h
Referenced by Process(), set_xy_residual_cut(), and Setup().
double PHTpcTrackSeedVertexAssoc::_z_proj = 0 private
Definition at line 59 of file PHTpcTrackSeedVertexAssoc.h.
View newest version in sPHENIX GitHub at line 59 of file PHTpcTrackSeedVertexAssoc.h
Referenced by Process().
double PHTpcTrackSeedVertexAssoc::_z_residual_cut = 0.22 private
Definition at line 66 of file PHTpcTrackSeedVertexAssoc.h.
View newest version in sPHENIX GitHub at line 66 of file PHTpcTrackSeedVertexAssoc.h
Referenced by Process(), set_z_residual_cut(), and Setup().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/trackreco/PHTpcTrackSeedVertexAssoc.h
coresoftware/blob/master/offline/packages/trackreco/PHTpcTrackSeedVertexAssoc.cc