Analysis Software: GPUTPCTrackParam Class Reference
GPUTPCTrackParam Class Reference
#include <coresoftware/blob/master/offline/packages/trackreco/GPUTPCTrackParam.h>
Classes
struct GPUTPCTrackFitParam
Public Member Functions
const GPUTPCBaseTrackParam & GetParam () const
void SetParam (const GPUTPCBaseTrackParam &v)
void InitParam ()
double X () const
double Y () const
double Z () const
double SinPhi () const
double DzDs () const
double QPt () const
double ZOffset () const
double SignCosPhi () const
double Chi2 () const
int NDF () const
double Err2Y () const
double Err2Z () const
double Err2SinPhi () const
double Err2DzDs () const
double Err2QPt () const
double GetX () const
double GetY () const
double GetZ () const
double GetSinPhi () const
double GetDzDs () const
double GetQPt () const
double GetSignCosPhi () const
double GetChi2 () const
int GetNDF () const
double GetKappa (double Bz) const
double GetCosPhi () const
double GetErr2Y () const
double GetErr2Z () const
double GetErr2SinPhi () const
double GetErr2DzDs () const
double GetErr2QPt () const
const double * Par () const
const double * Cov () const
const double * GetPar () const
double GetPar (int i) const
const double * GetCov () const
double GetCov (int i) const
void SetPar (int i, double v)
void SetCov (int i, double v)
void SetX (double v)
void SetY (double v)
void SetZ (double v)
void SetSinPhi (double v)
void SetDzDs (double v)
void SetQPt (double v)
void SetZOffset (double v)
void SetSignCosPhi (double v)
void SetChi2 (double v)
void SetNDF (int v)
double GetDist2 (const GPUTPCTrackParam &t) const
double GetDistXZ2 (const GPUTPCTrackParam &t) const
double GetS (double x, double y, double Bz) const
void GetDCAPoint (double x, double y, double z, double &px, double &py, double &pz, double Bz) const
bool TransportToX (double x, double Bz, double maxSinPhi=GPUCA_MAX_SIN_PHI)
bool TransportToXWithMaterial (double x, double Bz, double maxSinPhi=GPUCA_MAX_SIN_PHI)
bool TransportToX (double x, GPUTPCTrackLinearisation &t0, double Bz, double maxSinPhi=GPUCA_MAX_SIN_PHI, double *DL=nullptr)
bool TransportToX (double x, double sinPhi0, double cosPhi0, double Bz, double maxSinPhi=GPUCA_MAX_SIN_PHI)
bool TransportToXWithMaterial (double x, GPUTPCTrackLinearisation &t0, GPUTPCTrackFitParam &par, double Bz, double maxSinPhi=GPUCA_MAX_SIN_PHI)
bool TransportToXWithMaterial (double x, GPUTPCTrackFitParam &par, double Bz, double maxSinPhi=GPUCA_MAX_SIN_PHI)
void CalculateFitParameters (GPUTPCTrackFitParam &par, double mass=0.13957f)
bool CorrectForMeanMaterial (double xOverX0, double xTimesRho, const GPUTPCTrackFitParam &par)
bool Rotate (double alpha, double maxSinPhi=GPUCA_MAX_SIN_PHI)
bool Rotate (double alpha, GPUTPCTrackLinearisation &t0, double maxSinPhi=GPUCA_MAX_SIN_PHI)
bool Filter (double y, double z, double err2Y, double err2Z, double maxSinPhi=GPUCA_MAX_SIN_PHI, bool paramOnly=false)
bool CheckNumericalQuality () const
void Print () const
Static Public Member Functions
static double ApproximateBetheBloch (double beta2)
static double BetheBlochGeant (double bg, double kp0=2.33f, double kp1=0.20f, double kp2=3.00f, double kp3=173e-9f, double kp4=0.49848f)
static double BetheBlochSolid (double bg)
static double BetheBlochGas (double bg)
Private Attributes
GPUTPCBaseTrackParam mParam
GPUCA_GPUCODE.
double mC [15]
double mSignCosPhi
double mChi2
int mNDF
Detailed Description
GPUTPCTrackParam class describes the track parametrisation which is used by the GPUTPCTracker slice tracker.
Definition at line 28 of file GPUTPCTrackParam.h.
View newest version in sPHENIX GitHub at line 28 of file GPUTPCTrackParam.h
Member Function Documentation
double GPUTPCTrackParam::ApproximateBetheBloch (double beta2) static
Definition at line 415 of file GPUTPCTrackParam.cxx.
View newest version in sPHENIX GitHub at line 415 of file GPUTPCTrackParam.cxx
References f.
double GPUTPCTrackParam::BetheBlochGas (double bg) static
Definition at line 391 of file GPUTPCTrackParam.cxx.
View newest version in sPHENIX GitHub at line 391 of file GPUTPCTrackParam.cxx
References BetheBlochGeant(), f, rho, and x0.
Referenced by CalculateFitParameters().
double GPUTPCTrackParam::BetheBlochGeant (double bg, double kp0 = 2.33f, double kp1 = 0.20f, double kp2 = 3.00f, double kp3 = 173e-9f, double kp4 = 0.49848f) static
Definition at line 340 of file GPUTPCTrackParam.cxx.
View newest version in sPHENIX GitHub at line 340 of file GPUTPCTrackParam.cxx
References Acts::UnitConstants::e, f, physmon_track_finding_ttbar::r, rho, ambiguity_solver_full_chain::x, and x0.
Referenced by BetheBlochGas(), and BetheBlochSolid().
double GPUTPCTrackParam::BetheBlochSolid (double bg) static
Definition at line 379 of file GPUTPCTrackParam.cxx.
View newest version in sPHENIX GitHub at line 379 of file GPUTPCTrackParam.cxx
References BetheBlochGeant().
void GPUTPCTrackParam::CalculateFitParameters (GPUTPCTrackFitParam & par, double mass = 0.13957f)
Definition at line 432 of file GPUTPCTrackParam.cxx.
View newest version in sPHENIX GitHub at line 432 of file GPUTPCTrackParam.cxx
References GPUTPCTrackParam::GPUTPCTrackFitParam::bethe, BetheBlochGas(), GPUTPCTrackParam::GPUTPCTrackFitParam::e, GPUTPCTrackParam::GPUTPCTrackFitParam::EP2, f, GetPar(), GPUTPCTrackParam::GPUTPCTrackFitParam::k22, GPUTPCTrackParam::GPUTPCTrackFitParam::k33, GPUTPCTrackParam::GPUTPCTrackFitParam::k43, GPUTPCTrackParam::GPUTPCTrackFitParam::k44, mass, mC, GPUTPCTrackParam::GPUTPCTrackFitParam::sigmadE2, and GPUTPCTrackParam::GPUTPCTrackFitParam::theta2.
Referenced by ALICEKF::ALICEKalmanFilter(), PHSimpleKFProp::PropagateTrack(), and TransportToXWithMaterial().
bool GPUTPCTrackParam::CheckNumericalQuality () const
Definition at line 679 of file GPUTPCTrackParam.cxx.
View newest version in sPHENIX GitHub at line 679 of file GPUTPCTrackParam.cxx
References Acts::PhysicalConstants::c, Cov(), f, GetX(), GPUCA_MAX_SIN_PHI, i, mChi2, mSignCosPhi, Par(), QPt(), and SinPhi().
double GPUTPCTrackParam::Chi2 () const inline
Definition at line 47 of file GPUTPCTrackParam.h.
View newest version in sPHENIX GitHub at line 47 of file GPUTPCTrackParam.h
References mChi2.
bool GPUTPCTrackParam::CorrectForMeanMaterial (double xOverX0, double xTimesRho, const GPUTPCTrackFitParam & par)
Definition at line 466 of file GPUTPCTrackParam.cxx.
View newest version in sPHENIX GitHub at line 466 of file GPUTPCTrackParam.cxx
References GPUTPCTrackParam::GPUTPCTrackFitParam::bethe, corr, GPUTPCTrackParam::GPUTPCTrackFitParam::e, GPUTPCTrackParam::GPUTPCTrackFitParam::EP2, f, GetPar(), GPUTPCTrackParam::GPUTPCTrackFitParam::k22, GPUTPCTrackParam::GPUTPCTrackFitParam::k33, GPUTPCTrackParam::GPUTPCTrackFitParam::k43, GPUTPCTrackParam::GPUTPCTrackFitParam::k44, mC, SetPar(), GPUTPCTrackParam::GPUTPCTrackFitParam::sigmadE2, and GPUTPCTrackParam::GPUTPCTrackFitParam::theta2.
Referenced by TransportToXWithMaterial().
const double* GPUTPCTrackParam::Cov () const inline
Definition at line 76 of file GPUTPCTrackParam.h.
View newest version in sPHENIX GitHub at line 76 of file GPUTPCTrackParam.h
References mC.
Referenced by CheckNumericalQuality().
double GPUTPCTrackParam::DzDs () const inline
Definition at line 43 of file GPUTPCTrackParam.h.
View newest version in sPHENIX GitHub at line 43 of file GPUTPCTrackParam.h
References GPUTPCBaseTrackParam::DzDs(), and mParam.
Referenced by Rotate(), and TransportToX().
double GPUTPCTrackParam::Err2DzDs () const inline
Definition at line 53 of file GPUTPCTrackParam.h.
View newest version in sPHENIX GitHub at line 53 of file GPUTPCTrackParam.h
References mC.
double GPUTPCTrackParam::Err2QPt () const inline
Definition at line 54 of file GPUTPCTrackParam.h.
View newest version in sPHENIX GitHub at line 54 of file GPUTPCTrackParam.h
References mC.
double GPUTPCTrackParam::Err2SinPhi () const inline
Definition at line 52 of file GPUTPCTrackParam.h.
View newest version in sPHENIX GitHub at line 52 of file GPUTPCTrackParam.h
References mC.
double GPUTPCTrackParam::Err2Y () const inline
Definition at line 50 of file GPUTPCTrackParam.h.
View newest version in sPHENIX GitHub at line 50 of file GPUTPCTrackParam.h
References mC.
double GPUTPCTrackParam::Err2Z () const inline
Definition at line 51 of file GPUTPCTrackParam.h.
View newest version in sPHENIX GitHub at line 51 of file GPUTPCTrackParam.h
References mC.
bool GPUTPCTrackParam::Filter (double y, double z, double err2Y, double err2Z, double maxSinPhi = GPUCA_MAX_SIN_PHI, bool paramOnly = false)
Definition at line 618 of file GPUTPCTrackParam.cxx.
View newest version in sPHENIX GitHub at line 618 of file GPUTPCTrackParam.cxx
References Acts::UnitConstants::e, f, GetPar(), mC, mChi2, mNDF, and SetPar().
Referenced by ALICEKF::ALICEKalmanFilter(), and PHSimpleKFProp::PropagateTrack().
double GPUTPCTrackParam::GetChi2 () const inline
Definition at line 63 of file GPUTPCTrackParam.h.
View newest version in sPHENIX GitHub at line 63 of file GPUTPCTrackParam.h
References mChi2.
Referenced by ALICEKF::ALICEKalmanFilter().
double GPUTPCTrackParam::GetCosPhi () const inline
Definition at line 67 of file GPUTPCTrackParam.h.
View newest version in sPHENIX GitHub at line 67 of file GPUTPCTrackParam.h
References mSignCosPhi, and SinPhi().
Referenced by GetDCAPoint(), GetS(), and Rotate().
const double* GPUTPCTrackParam::GetCov () const inline
Definition at line 80 of file GPUTPCTrackParam.h.
View newest version in sPHENIX GitHub at line 80 of file GPUTPCTrackParam.h
References mC.
Referenced by ALICEKF::ALICEKalmanFilter(), and PHSimpleKFProp::PropagateTrack().
double GPUTPCTrackParam::GetCov (int i) const inline
Definition at line 81 of file GPUTPCTrackParam.h.
View newest version in sPHENIX GitHub at line 81 of file GPUTPCTrackParam.h
References i, and mC.
void GPUTPCTrackParam::GetDCAPoint (double x, double y, double z, double & px, double & py, double & pz, double Bz) const
Definition at line 64 of file GPUTPCTrackParam.cxx.
View newest version in sPHENIX GitHub at line 64 of file GPUTPCTrackParam.cxx
References KFPMath::a, CKF_timing_vs_mu::ax, dy, Acts::UnitConstants::e, f, GetCosPhi(), GetDzDs(), GetKappa(), GetS(), GetSinPhi(), GetX(), GetY(), GetZ(), k, round(), physmon_simulation::s, and x0.
double GPUTPCTrackParam::GetDist2 (const GPUTPCTrackParam & t) const
Definition at line 29 of file GPUTPCTrackParam.cxx.
View newest version in sPHENIX GitHub at line 29 of file GPUTPCTrackParam.cxx
References dy, dz, GetX(), GetY(), and GetZ().
double GPUTPCTrackParam::GetDistXZ2 (const GPUTPCTrackParam & t) const
Definition at line 39 of file GPUTPCTrackParam.cxx.
View newest version in sPHENIX GitHub at line 39 of file GPUTPCTrackParam.cxx
References dz, GetX(), and GetZ().
double GPUTPCTrackParam::GetDzDs () const inline
Definition at line 60 of file GPUTPCTrackParam.h.
View newest version in sPHENIX GitHub at line 60 of file GPUTPCTrackParam.h
References GPUTPCBaseTrackParam::GetDzDs(), and mParam.
Referenced by ALICEKF::ALICEKalmanFilter(), GetDCAPoint(), Print(), and PHSimpleKFProp::PropagateTrack().
double GPUTPCTrackParam::GetErr2DzDs () const inline
Definition at line 72 of file GPUTPCTrackParam.h.
View newest version in sPHENIX GitHub at line 72 of file GPUTPCTrackParam.h
References mC.
Referenced by Print().
double GPUTPCTrackParam::GetErr2QPt () const inline
Definition at line 73 of file GPUTPCTrackParam.h.
View newest version in sPHENIX GitHub at line 73 of file GPUTPCTrackParam.h
References mC.
Referenced by ALICEKF::ALICEKalmanFilter(), and Print().
double GPUTPCTrackParam::GetErr2SinPhi () const inline
Definition at line 71 of file GPUTPCTrackParam.h.
View newest version in sPHENIX GitHub at line 71 of file GPUTPCTrackParam.h
References mC.
Referenced by Print().
double GPUTPCTrackParam::GetErr2Y () const inline
Definition at line 69 of file GPUTPCTrackParam.h.
View newest version in sPHENIX GitHub at line 69 of file GPUTPCTrackParam.h
References mC.
Referenced by ALICEKF::ALICEKalmanFilter(), and Print().
double GPUTPCTrackParam::GetErr2Z () const inline
Definition at line 70 of file GPUTPCTrackParam.h.
View newest version in sPHENIX GitHub at line 70 of file GPUTPCTrackParam.h
References mC.
Referenced by ALICEKF::ALICEKalmanFilter(), and Print().
double GPUTPCTrackParam::GetKappa (double Bz) const inline
Definition at line 66 of file GPUTPCTrackParam.h.
View newest version in sPHENIX GitHub at line 66 of file GPUTPCTrackParam.h
References GPUTPCBaseTrackParam::GetKappa(), and mParam.
Referenced by ALICEKF::ALICEKalmanFilter(), GetDCAPoint(), and GetS().
int GPUTPCTrackParam::GetNDF () const inline
Definition at line 64 of file GPUTPCTrackParam.h.
View newest version in sPHENIX GitHub at line 64 of file GPUTPCTrackParam.h
References mNDF.
Referenced by ALICEKF::ALICEKalmanFilter(), and PHSimpleKFProp::PropagateTrack().
const double* GPUTPCTrackParam::GetPar () const inline
Definition at line 78 of file GPUTPCTrackParam.h.
View newest version in sPHENIX GitHub at line 78 of file GPUTPCTrackParam.h
References GPUTPCBaseTrackParam::GetPar(), and mParam.
Referenced by CalculateFitParameters(), CorrectForMeanMaterial(), Filter(), and TransportToX().
double GPUTPCTrackParam::GetPar (int i) const inline
Definition at line 79 of file GPUTPCTrackParam.h.
View newest version in sPHENIX GitHub at line 79 of file GPUTPCTrackParam.h
References GPUTPCBaseTrackParam::GetPar(), and mParam.
const GPUTPCBaseTrackParam& GPUTPCTrackParam::GetParam () const inline
Definition at line 35 of file GPUTPCTrackParam.h.
View newest version in sPHENIX GitHub at line 35 of file GPUTPCTrackParam.h
References mParam.
double GPUTPCTrackParam::GetQPt () const inline
Definition at line 61 of file GPUTPCTrackParam.h.
View newest version in sPHENIX GitHub at line 61 of file GPUTPCTrackParam.h
References GPUTPCBaseTrackParam::GetQPt(), and mParam.
Referenced by ALICEKF::ALICEKalmanFilter(), Print(), and PHSimpleKFProp::PropagateTrack().
double GPUTPCTrackParam::GetS (double x, double y, double Bz) const
Definition at line 48 of file GPUTPCTrackParam.cxx.
View newest version in sPHENIX GitHub at line 48 of file GPUTPCTrackParam.cxx
References Acts::UnitConstants::e, f, GetCosPhi(), GetKappa(), GetSinPhi(), GetX(), GetY(), and k.
Referenced by GetDCAPoint().
double GPUTPCTrackParam::GetSignCosPhi () const inline
Definition at line 62 of file GPUTPCTrackParam.h.
View newest version in sPHENIX GitHub at line 62 of file GPUTPCTrackParam.h
References mSignCosPhi.
Referenced by Print().
double GPUTPCTrackParam::GetSinPhi () const inline
Definition at line 59 of file GPUTPCTrackParam.h.
View newest version in sPHENIX GitHub at line 59 of file GPUTPCTrackParam.h
References GPUTPCBaseTrackParam::GetSinPhi(), and mParam.
Referenced by ALICEKF::ALICEKalmanFilter(), GetDCAPoint(), GetS(), Print(), and PHSimpleKFProp::PropagateTrack().
double GPUTPCTrackParam::GetX () const inline
Definition at line 56 of file GPUTPCTrackParam.h.
View newest version in sPHENIX GitHub at line 56 of file GPUTPCTrackParam.h
References GPUTPCBaseTrackParam::GetX(), and mParam.
Referenced by ALICEKF::ALICEKalmanFilter(), CheckNumericalQuality(), GetDCAPoint(), GetDist2(), GetDistXZ2(), GetS(), Print(), and PHSimpleKFProp::PropagateTrack().
double GPUTPCTrackParam::GetY () const inline
Definition at line 57 of file GPUTPCTrackParam.h.
View newest version in sPHENIX GitHub at line 57 of file GPUTPCTrackParam.h
References GPUTPCBaseTrackParam::GetY(), and mParam.
Referenced by ALICEKF::ALICEKalmanFilter(), GetDCAPoint(), GetDist2(), GetS(), Print(), and PHSimpleKFProp::PropagateTrack().
double GPUTPCTrackParam::GetZ () const inline
Definition at line 58 of file GPUTPCTrackParam.h.
View newest version in sPHENIX GitHub at line 58 of file GPUTPCTrackParam.h
References GPUTPCBaseTrackParam::GetZ(), and mParam.
Referenced by ALICEKF::ALICEKalmanFilter(), GetDCAPoint(), GetDist2(), GetDistXZ2(), Print(), and PHSimpleKFProp::PropagateTrack().
void GPUTPCTrackParam::InitParam () inline
Definition at line 147 of file GPUTPCTrackParam.h.
View newest version in sPHENIX GitHub at line 147 of file GPUTPCTrackParam.h
References f, SetChi2(), SetCov(), SetDzDs(), SetNDF(), SetQPt(), SetSignCosPhi(), SetSinPhi(), and SetZOffset().
Referenced by ALICEKF::ALICEKalmanFilter(), and PHSimpleKFProp::PropagateTrack().
int GPUTPCTrackParam::NDF () const inline
Definition at line 48 of file GPUTPCTrackParam.h.
View newest version in sPHENIX GitHub at line 48 of file GPUTPCTrackParam.h
References mNDF.
const double* GPUTPCTrackParam::Par () const inline
Definition at line 75 of file GPUTPCTrackParam.h.
View newest version in sPHENIX GitHub at line 75 of file GPUTPCTrackParam.h
References mParam, and GPUTPCBaseTrackParam::Par().
Referenced by CheckNumericalQuality().
void GPUTPCTrackParam::Print () const
Definition at line 719 of file GPUTPCTrackParam.cxx.
View newest version in sPHENIX GitHub at line 719 of file GPUTPCTrackParam.cxx
References GetDzDs(), GetErr2DzDs(), GetErr2QPt(), GetErr2SinPhi(), GetErr2Y(), GetErr2Z(), GetQPt(), GetSignCosPhi(), GetSinPhi(), GetX(), GetY(), and GetZ().
double GPUTPCTrackParam::QPt () const inline
Definition at line 44 of file GPUTPCTrackParam.h.
View newest version in sPHENIX GitHub at line 44 of file GPUTPCTrackParam.h
References mParam, and GPUTPCBaseTrackParam::QPt().
Referenced by CheckNumericalQuality(), Rotate(), and TransportToX().
bool GPUTPCTrackParam::Rotate (double alpha, double maxSinPhi = GPUCA_MAX_SIN_PHI)
Definition at line 515 of file GPUTPCTrackParam.cxx.
View newest version in sPHENIX GitHub at line 515 of file GPUTPCTrackParam.cxx
References DzDs(), Acts::UnitConstants::e, f, GetCosPhi(), mC, QPt(), SetDzDs(), SetQPt(), SetSignCosPhi(), SetSinPhi(), SetX(), SetY(), SinPhi(), X(), ambiguity_solver_full_chain::x, y, and Y().
Referenced by ALICEKF::ALICEKalmanFilter(), and PHSimpleKFProp::PropagateTrack().
bool GPUTPCTrackParam::Rotate (double alpha, GPUTPCTrackLinearisation & t0, double maxSinPhi = GPUCA_MAX_SIN_PHI)
Definition at line 572 of file GPUTPCTrackParam.cxx.
View newest version in sPHENIX GitHub at line 572 of file GPUTPCTrackParam.cxx
References GPUTPCTrackLinearisation::CosPhi(), Acts::UnitConstants::e, f, mC, GPUTPCTrackLinearisation::SetCosPhi(), GPUTPCTrackLinearisation::SetSinPhi(), SetSinPhi(), SetX(), SetY(), SinPhi(), GPUTPCTrackLinearisation::SinPhi(), X(), x0, and Y().
void GPUTPCTrackParam::SetChi2 (double v) inline
Definition at line 94 of file GPUTPCTrackParam.h.
View newest version in sPHENIX GitHub at line 94 of file GPUTPCTrackParam.h
References mChi2, and testSigmaEff::v.
Referenced by InitParam().
void GPUTPCTrackParam::SetCov (int i, double v) inline
Definition at line 84 of file GPUTPCTrackParam.h.
View newest version in sPHENIX GitHub at line 84 of file GPUTPCTrackParam.h
References i, mC, and testSigmaEff::v.
Referenced by InitParam(), and PHSimpleKFProp::PropagateTrack().
void GPUTPCTrackParam::SetDzDs (double v) inline
Definition at line 90 of file GPUTPCTrackParam.h.
View newest version in sPHENIX GitHub at line 90 of file GPUTPCTrackParam.h
References mParam, and GPUTPCBaseTrackParam::SetDzDs().
Referenced by ALICEKF::ALICEKalmanFilter(), InitParam(), PHSimpleKFProp::PropagateTrack(), and Rotate().
void GPUTPCTrackParam::SetNDF (int v) inline
Definition at line 95 of file GPUTPCTrackParam.h.
View newest version in sPHENIX GitHub at line 95 of file GPUTPCTrackParam.h
References mNDF, and testSigmaEff::v.
Referenced by InitParam(), and PHSimpleKFProp::PropagateTrack().
void GPUTPCTrackParam::SetPar (int i, double v) inline
Definition at line 83 of file GPUTPCTrackParam.h.
View newest version in sPHENIX GitHub at line 83 of file GPUTPCTrackParam.h
References mParam, and GPUTPCBaseTrackParam::SetPar().
Referenced by CorrectForMeanMaterial(), Filter(), and TransportToX().
void GPUTPCTrackParam::SetParam (const GPUTPCBaseTrackParam & v) inline
Definition at line 36 of file GPUTPCTrackParam.h.
View newest version in sPHENIX GitHub at line 36 of file GPUTPCTrackParam.h
References mParam, and testSigmaEff::v.
void GPUTPCTrackParam::SetQPt (double v) inline
Definition at line 91 of file GPUTPCTrackParam.h.
View newest version in sPHENIX GitHub at line 91 of file GPUTPCTrackParam.h
References mParam, and GPUTPCBaseTrackParam::SetQPt().
Referenced by ALICEKF::ALICEKalmanFilter(), InitParam(), PHSimpleKFProp::PropagateTrack(), and Rotate().
void GPUTPCTrackParam::SetSignCosPhi (double v) inline
Definition at line 93 of file GPUTPCTrackParam.h.
View newest version in sPHENIX GitHub at line 93 of file GPUTPCTrackParam.h
References mSignCosPhi.
Referenced by InitParam(), PHSimpleKFProp::PropagateTrack(), and Rotate().
void GPUTPCTrackParam::SetSinPhi (double v) inline
Definition at line 89 of file GPUTPCTrackParam.h.
View newest version in sPHENIX GitHub at line 89 of file GPUTPCTrackParam.h
References mParam, and GPUTPCBaseTrackParam::SetSinPhi().
Referenced by ALICEKF::ALICEKalmanFilter(), InitParam(), PHSimpleKFProp::PropagateTrack(), and Rotate().
void GPUTPCTrackParam::SetX (double v) inline
Definition at line 86 of file GPUTPCTrackParam.h.
View newest version in sPHENIX GitHub at line 86 of file GPUTPCTrackParam.h
References mParam, and GPUTPCBaseTrackParam::SetX().
Referenced by ALICEKF::ALICEKalmanFilter(), PHSimpleKFProp::PropagateTrack(), Rotate(), and TransportToX().
void GPUTPCTrackParam::SetY (double v) inline
Definition at line 87 of file GPUTPCTrackParam.h.
View newest version in sPHENIX GitHub at line 87 of file GPUTPCTrackParam.h
References mParam, and GPUTPCBaseTrackParam::SetY().
Referenced by ALICEKF::ALICEKalmanFilter(), PHSimpleKFProp::PropagateTrack(), and Rotate().
void GPUTPCTrackParam::SetZ (double v) inline
Definition at line 88 of file GPUTPCTrackParam.h.
View newest version in sPHENIX GitHub at line 88 of file GPUTPCTrackParam.h
References mParam, and GPUTPCBaseTrackParam::SetZ().
Referenced by ALICEKF::ALICEKalmanFilter(), and PHSimpleKFProp::PropagateTrack().
void GPUTPCTrackParam::SetZOffset (double v) inline
Definition at line 92 of file GPUTPCTrackParam.h.
View newest version in sPHENIX GitHub at line 92 of file GPUTPCTrackParam.h
References mParam, and GPUTPCBaseTrackParam::SetZOffset().
Referenced by InitParam().
double GPUTPCTrackParam::SignCosPhi () const inline
Definition at line 46 of file GPUTPCTrackParam.h.
View newest version in sPHENIX GitHub at line 46 of file GPUTPCTrackParam.h
References mSignCosPhi.
Referenced by GPUTPCTrackLinearisation::GPUTPCTrackLinearisation().
double GPUTPCTrackParam::SinPhi () const inline
Definition at line 42 of file GPUTPCTrackParam.h.
View newest version in sPHENIX GitHub at line 42 of file GPUTPCTrackParam.h
References mParam, and GPUTPCBaseTrackParam::SinPhi().
Referenced by CheckNumericalQuality(), GetCosPhi(), Rotate(), and TransportToX().
bool GPUTPCTrackParam::TransportToX (double x, double Bz, double maxSinPhi = GPUCA_MAX_SIN_PHI)
Definition at line 294 of file GPUTPCTrackParam.cxx.
View newest version in sPHENIX GitHub at line 294 of file GPUTPCTrackParam.cxx
Referenced by TransportToXWithMaterial().
bool GPUTPCTrackParam::TransportToX (double x, GPUTPCTrackLinearisation & t0, double Bz, double maxSinPhi = GPUCA_MAX_SIN_PHI, double * DL = nullptr)
Definition at line 94 of file GPUTPCTrackParam.cxx.
View newest version in sPHENIX GitHub at line 94 of file GPUTPCTrackParam.cxx
References Acts::IntegrationTest::Bz, GPUTPCTrackLinearisation::CosPhi(), dy, dz, GPUTPCTrackLinearisation::DzDs(), Acts::UnitConstants::e, f, GetPar(), h2, k, mC, GPUTPCTrackLinearisation::QPt(), GPUTPCTrackLinearisation::SetCosPhi(), SetPar(), GPUTPCTrackLinearisation::SetSinPhi(), SetX(), GPUTPCTrackLinearisation::SinPhi(), tg, X(), Y(), and Z().
bool GPUTPCTrackParam::TransportToX (double x, double sinPhi0, double cosPhi0, double Bz, double maxSinPhi = GPUCA_MAX_SIN_PHI)
Definition at line 214 of file GPUTPCTrackParam.cxx.
View newest version in sPHENIX GitHub at line 214 of file GPUTPCTrackParam.cxx
References Acts::IntegrationTest::Bz, DzDs(), Acts::UnitConstants::e, f, GetPar(), h2, mC, QPt(), SetPar(), SetX(), SinPhi(), and X().
bool GPUTPCTrackParam::TransportToXWithMaterial (double x, double Bz, double maxSinPhi = GPUCA_MAX_SIN_PHI)
Definition at line 328 of file GPUTPCTrackParam.cxx.
View newest version in sPHENIX GitHub at line 328 of file GPUTPCTrackParam.cxx
References CalculateFitParameters().
Referenced by ALICEKF::ALICEKalmanFilter(), PHSimpleKFProp::PropagateTrack(), and TransportToXWithMaterial().
bool GPUTPCTrackParam::TransportToXWithMaterial (double x, GPUTPCTrackLinearisation & t0, GPUTPCTrackFitParam & par, double Bz, double maxSinPhi = GPUCA_MAX_SIN_PHI)
Definition at line 301 of file GPUTPCTrackParam.cxx.
View newest version in sPHENIX GitHub at line 301 of file GPUTPCTrackParam.cxx
References CorrectForMeanMaterial(), f, and TransportToX().
bool GPUTPCTrackParam::TransportToXWithMaterial (double x, GPUTPCTrackFitParam & par, double Bz, double maxSinPhi = GPUCA_MAX_SIN_PHI)
Definition at line 320 of file GPUTPCTrackParam.cxx.
View newest version in sPHENIX GitHub at line 320 of file GPUTPCTrackParam.cxx
References TransportToXWithMaterial().
double GPUTPCTrackParam::X () const inline
Definition at line 39 of file GPUTPCTrackParam.h.
View newest version in sPHENIX GitHub at line 39 of file GPUTPCTrackParam.h
References mParam, and GPUTPCBaseTrackParam::X().
Referenced by Rotate(), and TransportToX().
double GPUTPCTrackParam::Y () const inline
Definition at line 40 of file GPUTPCTrackParam.h.
View newest version in sPHENIX GitHub at line 40 of file GPUTPCTrackParam.h
References mParam, and GPUTPCBaseTrackParam::Y().
Referenced by Rotate(), and TransportToX().
double GPUTPCTrackParam::Z () const inline
Definition at line 41 of file GPUTPCTrackParam.h.
View newest version in sPHENIX GitHub at line 41 of file GPUTPCTrackParam.h
References mParam, and GPUTPCBaseTrackParam::Z().
Referenced by TransportToX().
double GPUTPCTrackParam::ZOffset () const inline
Definition at line 45 of file GPUTPCTrackParam.h.
View newest version in sPHENIX GitHub at line 45 of file GPUTPCTrackParam.h
References mParam, and GPUTPCBaseTrackParam::ZOffset().
Member Data Documentation
double GPUTPCTrackParam::mC[15] private
Definition at line 141 of file GPUTPCTrackParam.h.
View newest version in sPHENIX GitHub at line 141 of file GPUTPCTrackParam.h
Referenced by CalculateFitParameters(), CorrectForMeanMaterial(), Cov(), Err2DzDs(), Err2QPt(), Err2SinPhi(), Err2Y(), Err2Z(), Filter(), GetCov(), GetErr2DzDs(), GetErr2QPt(), GetErr2SinPhi(), GetErr2Y(), GetErr2Z(), Rotate(), SetCov(), and TransportToX().
double GPUTPCTrackParam::mChi2 private
Definition at line 143 of file GPUTPCTrackParam.h.
View newest version in sPHENIX GitHub at line 143 of file GPUTPCTrackParam.h
Referenced by CheckNumericalQuality(), Chi2(), Filter(), GetChi2(), and SetChi2().
int GPUTPCTrackParam::mNDF private
Definition at line 144 of file GPUTPCTrackParam.h.
View newest version in sPHENIX GitHub at line 144 of file GPUTPCTrackParam.h
Referenced by Filter(), GetNDF(), NDF(), and SetNDF().
GPUTPCBaseTrackParam GPUTPCTrackParam::mParam private
GPUCA_GPUCODE.
Definition at line 135 of file GPUTPCTrackParam.h.
View newest version in sPHENIX GitHub at line 135 of file GPUTPCTrackParam.h
Referenced by DzDs(), GetDzDs(), GetKappa(), GetPar(), GetParam(), GetQPt(), GetSinPhi(), GetX(), GetY(), GetZ(), Par(), QPt(), SetDzDs(), SetPar(), SetParam(), SetQPt(), SetSinPhi(), SetX(), SetY(), SetZ(), SetZOffset(), SinPhi(), X(), Y(), Z(), and ZOffset().
double GPUTPCTrackParam::mSignCosPhi private
Definition at line 142 of file GPUTPCTrackParam.h.
View newest version in sPHENIX GitHub at line 142 of file GPUTPCTrackParam.h
Referenced by CheckNumericalQuality(), GetCosPhi(), GetSignCosPhi(), SetSignCosPhi(), and SignCosPhi().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/trackreco/GPUTPCTrackParam.h
coresoftware/blob/master/offline/packages/trackreco/GPUTPCTrackParam.cxx