Analysis Software: PHFieldConfigv2 Class Reference
PHFieldConfigv2 Class Reference
PHFieldConfigv2 implements field configuration information for uniform field model.
#include <coresoftware/blob/master/offline/packages/PHField/PHFieldConfigv2.h>
Public Member Functions
PHFieldConfigv2 (double field_mag_x, double field_mag_y, double field_mag_z)
construct field configuration in units of Tesla
PHFieldConfigv2 ()
default constructor for ROOT file IO
~PHFieldConfigv2 () override
PHObject * CloneMe () const override
Virtual copy constructor.
void identify (std::ostream &os=std::cout) const override
void Reset () override
Clear Content.
int isValid () const override
isValid returns non zero if object contains vailid data
FieldConfigTypes get_field_config () const override
double get_field_mag_x () const override
field value in Tesla for uniform field model ONLY for PHFieldConfigv2
void set_field_mag_x (double fieldMagX) override
field value in Tesla for uniform field model ONLY for PHFieldConfigv2
double get_field_mag_y () const override
field value in Tesla for uniform field model ONLY for PHFieldConfigv2
void set_field_mag_y (double fieldMagY) override
field value in Tesla for uniform field model ONLY for PHFieldConfigv2
double get_field_mag_z () const override
field value in Tesla for uniform field model ONLY for PHFieldConfigv2
void set_field_mag_z (double fieldMagZ) override
field value in Tesla for uniform field model ONLY for PHFieldConfigv2
Public Member Functions inherited from PHFieldConfig
~PHFieldConfig () override
std::string get_field_config_description () const
virtual void set_field_config (FieldConfigTypes)
virtual const std::string & get_filename () const
virtual void set_filename (const std::string &)
virtual double get_magfield_rescale () const
virtual void set_magfield_rescale (double)
Public Member Functions inherited from PHObject
PHObject ()
ctor
~PHObject () override
dtor
virtual PHObject * clone () const final
PHObject * Clone (const char *newname="") const final
void Copy (TObject &object) const final
virtual int Integrate () const
virtual int Integrate (PHObject *)
virtual void CopyFrom (const PHObject *obj)
Protected Attributes
double field_mag_x_
double field_mag_y_
double field_mag_z_
Additional Inherited Members
Public Types inherited from PHFieldConfig
enum FieldConfigTypes {
kFieldUniform = 0, kField2D = 2, kField3DCylindrical = 3, kFieldBeast = 4,
kFieldCleo = 5, Field3DCartesian = 1, kFieldInvalid = 9999
}
Protected Member Functions inherited from PHFieldConfig
PHFieldConfig ()
pure virtual interface class. not for direct use
Static Protected Attributes inherited from PHFieldConfig
static const std::string kInvalid_FileName
Detailed Description
PHFieldConfigv2 implements field configuration information for uniform field model.
Definition at line 22 of file PHFieldConfigv2.h.
View newest version in sPHENIX GitHub at line 22 of file PHFieldConfigv2.h
Constructor & Destructor Documentation
PHFieldConfigv2::PHFieldConfigv2 (double field_mag_x, double field_mag_y, double field_mag_z)
construct field configuration in units of Tesla
Definition at line 16 of file PHFieldConfigv2.cc.
View newest version in sPHENIX GitHub at line 16 of file PHFieldConfigv2.cc
PHFieldConfigv2::PHFieldConfigv2 () inline
default constructor for ROOT file IO
Definition at line 32 of file PHFieldConfigv2.h.
View newest version in sPHENIX GitHub at line 32 of file PHFieldConfigv2.h
Referenced by CloneMe().
PHFieldConfigv2::~PHFieldConfigv2 () inline override
Definition at line 37 of file PHFieldConfigv2.h.
View newest version in sPHENIX GitHub at line 37 of file PHFieldConfigv2.h
Member Function Documentation
PHObject* PHFieldConfigv2::CloneMe () const inline override virtual
Virtual copy constructor.
Reimplemented from PHObject.
Definition at line 40 of file PHFieldConfigv2.h.
View newest version in sPHENIX GitHub at line 40 of file PHFieldConfigv2.h
References PHFieldConfigv2().
FieldConfigTypes PHFieldConfigv2::get_field_config () const inline override virtual
Reimplemented from PHFieldConfig.
Definition at line 54 of file PHFieldConfigv2.h.
View newest version in sPHENIX GitHub at line 54 of file PHFieldConfigv2.h
References PHFieldConfig::kFieldUniform.
double PHFieldConfigv2::get_field_mag_x () const inline override virtual
field value in Tesla for uniform field model ONLY for PHFieldConfigv2
Reimplemented from PHFieldConfig.
Definition at line 60 of file PHFieldConfigv2.h.
View newest version in sPHENIX GitHub at line 60 of file PHFieldConfigv2.h
References field_mag_x_.
Referenced by identify().
double PHFieldConfigv2::get_field_mag_y () const inline override virtual
field value in Tesla for uniform field model ONLY for PHFieldConfigv2
Reimplemented from PHFieldConfig.
Definition at line 72 of file PHFieldConfigv2.h.
View newest version in sPHENIX GitHub at line 72 of file PHFieldConfigv2.h
References field_mag_y_.
Referenced by identify().
double PHFieldConfigv2::get_field_mag_z () const inline override virtual
field value in Tesla for uniform field model ONLY for PHFieldConfigv2
Reimplemented from PHFieldConfig.
Definition at line 84 of file PHFieldConfigv2.h.
View newest version in sPHENIX GitHub at line 84 of file PHFieldConfigv2.h
References field_mag_z_.
Referenced by identify().
void PHFieldConfigv2::identify (std::ostream & os = std::cout) const override virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from PHFieldConfig.
Definition at line 29 of file PHFieldConfigv2.cc.
View newest version in sPHENIX GitHub at line 29 of file PHFieldConfigv2.cc
References PHFieldConfig::get_field_config_description(), get_field_mag_x(), get_field_mag_y(), get_field_mag_z(), and isValid().
int PHFieldConfigv2::isValid () const inline override virtual
isValid returns non zero if object contains vailid data
Reimplemented from PHObject.
Definition at line 52 of file PHFieldConfigv2.h.
View newest version in sPHENIX GitHub at line 52 of file PHFieldConfigv2.h
Referenced by identify().
void PHFieldConfigv2::Reset () inline override virtual
Clear Content.
Reimplemented from PHObject.
Definition at line 49 of file PHFieldConfigv2.h.
View newest version in sPHENIX GitHub at line 49 of file PHFieldConfigv2.h
void PHFieldConfigv2::set_field_mag_x (double fieldMagX) inline override virtual
field value in Tesla for uniform field model ONLY for PHFieldConfigv2
Reimplemented from PHFieldConfig.
Definition at line 66 of file PHFieldConfigv2.h.
View newest version in sPHENIX GitHub at line 66 of file PHFieldConfigv2.h
References field_mag_x_.
void PHFieldConfigv2::set_field_mag_y (double fieldMagY) inline override virtual
field value in Tesla for uniform field model ONLY for PHFieldConfigv2
Reimplemented from PHFieldConfig.
Definition at line 78 of file PHFieldConfigv2.h.
View newest version in sPHENIX GitHub at line 78 of file PHFieldConfigv2.h
References field_mag_y_.
void PHFieldConfigv2::set_field_mag_z (double fieldMagZ) inline override virtual
field value in Tesla for uniform field model ONLY for PHFieldConfigv2
Reimplemented from PHFieldConfig.
Definition at line 90 of file PHFieldConfigv2.h.
View newest version in sPHENIX GitHub at line 90 of file PHFieldConfigv2.h
References field_mag_z_.
Member Data Documentation
double PHFieldConfigv2::field_mag_x_ protected
Definition at line 96 of file PHFieldConfigv2.h.
View newest version in sPHENIX GitHub at line 96 of file PHFieldConfigv2.h
Referenced by get_field_mag_x(), and set_field_mag_x().
double PHFieldConfigv2::field_mag_y_ protected
Definition at line 97 of file PHFieldConfigv2.h.
View newest version in sPHENIX GitHub at line 97 of file PHFieldConfigv2.h
Referenced by get_field_mag_y(), and set_field_mag_y().
double PHFieldConfigv2::field_mag_z_ protected
Definition at line 98 of file PHFieldConfigv2.h.
View newest version in sPHENIX GitHub at line 98 of file PHFieldConfigv2.h
Referenced by get_field_mag_z(), and set_field_mag_z().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/PHField/PHFieldConfigv2.h
coresoftware/blob/master/offline/packages/PHField/PHFieldConfigv2.cc