Analysis Software: PHHepMCGenEventMap Class Reference
PHHepMCGenEventMap Class Reference
PHHepMCGenEventMap is collection of HEPMC events input into this simulation map of embedding ID -> PHHepMCGenEvent positive ID is the embedded event of interest, e.g. jetty event from pythia negative IDs are backgrounds, .e.g out of time pile up collisions Usually, ID = 0 means the primary Au+Au collision background.
#include <coresoftware/blob/master/generators/phhepmc/PHHepMCGenEventMap.h>
Public Types
typedef std::map< int,
PHHepMCGenEvent * > HepMCGenEventMap
typedef std::map< int,
PHHepMCGenEvent * >
::const_iterator ConstIter
typedef std::map< int,
PHHepMCGenEvent * >::iterator Iter
typedef std::map< int,
PHHepMCGenEvent * >
::const_reverse_iterator ConstReverseIter
typedef std::map< int,
PHHepMCGenEvent * >
::reverse_iterator ReverseIter
Public Member Functions
PHHepMCGenEventMap ()=default
PHHepMCGenEventMap (const PHHepMCGenEventMap &eventmap)
PHHepMCGenEventMap & operator= (const PHHepMCGenEventMap &eventmap)
~PHHepMCGenEventMap () override
void identify (std::ostream &os=std::cout) const override
void Reset () override
Clear Event.
int isValid () const override
isValid returns non zero if object contains vailid data
PHHepMCGenEventMap * CloneMe () const override
Virtual copy constructor.
bool empty () const
container service
size_t size () const
size_t count (int idkey) const
void clear ()
const PHHepMCGenEvent * get (int idkey) const
fetch event
PHHepMCGenEvent * get (int idkey)
PHHepMCGenEvent * insert (const PHHepMCGenEvent *event)
insert a event of interest, e.g. jetty event from pythia
PHHepMCGenEvent * insert_active_event (const PHHepMCGenEvent *event=nullptr)
insert a event of interest, e.g. jetty event from pythia
PHHepMCGenEvent * insert_background_event (const PHHepMCGenEvent *event=nullptr)
insert a event of background, e.g. Au+Au collision background. First event has embedding ID = 0, which is usually the primary Au+Au collision in the case of HI embedding
PHHepMCGenEvent * insert_event (const int embedding_id, const PHHepMCGenEvent *event=nullptr)
insert a event with specific embedding ID
size_t erase (int idkey)
ConstIter find (unsigned int idkey) const
find
Iter find (int idkey)
ConstIter begin () const
iterator from lowest ID to highest, i.e. background to signal
ConstIter end () const
Iter begin ()
Iter end ()
ConstReverseIter rbegin () const
iterator from lowest ID to highest, i.e. signal to background
ConstReverseIter rend () const
ReverseIter rbegin ()
ReverseIter rend ()
const HepMCGenEventMap & get_map () const
for c++11 range-based for loop
HepMCGenEventMap & get_map ()
Public Member Functions inherited from PHObject
PHObject ()
ctor
~PHObject () override
dtor
virtual PHObject * clone () const final
PHObject * Clone (const char *newname="") const final
void Copy (TObject &object) const final
virtual int Integrate () const
virtual int Integrate (PHObject *)
virtual void CopyFrom (const PHObject *obj)
Private Member Functions
ClassDefOverride (PHHepMCGenEventMap, 4)
Private Attributes
HepMCGenEventMap _map
Detailed Description
PHHepMCGenEventMap is collection of HEPMC events input into this simulation map of embedding ID -> PHHepMCGenEvent positive ID is the embedded event of interest, e.g. jetty event from pythia negative IDs are backgrounds, .e.g out of time pile up collisions Usually, ID = 0 means the primary Au+Au collision background.
Definition at line 17 of file PHHepMCGenEventMap.h.
View newest version in sPHENIX GitHub at line 17 of file PHHepMCGenEventMap.h
Member Typedef Documentation
typedef std::map<int, PHHepMCGenEvent*>::const_iterator PHHepMCGenEventMap::ConstIter
Definition at line 25 of file PHHepMCGenEventMap.h.
View newest version in sPHENIX GitHub at line 25 of file PHHepMCGenEventMap.h
typedef std::map<int, PHHepMCGenEvent*>::const_reverse_iterator PHHepMCGenEventMap::ConstReverseIter
Definition at line 27 of file PHHepMCGenEventMap.h.
View newest version in sPHENIX GitHub at line 27 of file PHHepMCGenEventMap.h
typedef std::map<int, PHHepMCGenEvent*> PHHepMCGenEventMap::HepMCGenEventMap
map of embedding ID -> PHHepMCGenEvent positive ID is the embedded event of interest, e.g. jetty event from pythia negative IDs are backgrounds, .e.g out of time pile up collisions Usually, ID = 0 means the primary Au+Au collision background
Definition at line 24 of file PHHepMCGenEventMap.h.
View newest version in sPHENIX GitHub at line 24 of file PHHepMCGenEventMap.h
typedef std::map<int, PHHepMCGenEvent*>::iterator PHHepMCGenEventMap::Iter
Definition at line 26 of file PHHepMCGenEventMap.h.
View newest version in sPHENIX GitHub at line 26 of file PHHepMCGenEventMap.h
typedef std::map<int, PHHepMCGenEvent*>::reverse_iterator PHHepMCGenEventMap::ReverseIter
Definition at line 28 of file PHHepMCGenEventMap.h.
View newest version in sPHENIX GitHub at line 28 of file PHHepMCGenEventMap.h
Constructor & Destructor Documentation
PHHepMCGenEventMap::PHHepMCGenEventMap () default
Referenced by CloneMe().
PHHepMCGenEventMap::PHHepMCGenEventMap (const PHHepMCGenEventMap & eventmap)
Definition at line 12 of file PHHepMCGenEventMap.cc.
View newest version in sPHENIX GitHub at line 12 of file PHHepMCGenEventMap.cc
References _map, and get_map().
PHHepMCGenEventMap::~PHHepMCGenEventMap () override
Definition at line 26 of file PHHepMCGenEventMap.cc.
View newest version in sPHENIX GitHub at line 26 of file PHHepMCGenEventMap.cc
References Reset().
Member Function Documentation
ConstIter PHHepMCGenEventMap::begin (void) const inline
iterator from lowest ID to highest, i.e. background to signal
Definition at line 69 of file PHHepMCGenEventMap.h.
View newest version in sPHENIX GitHub at line 69 of file PHHepMCGenEventMap.h
References _map.
Referenced by FermimotionAfterburner::AddpF(), EpFinderEval::fill_tree(), EventEvaluator::fillOutputNtuples(), AnaTutorial::getHEPMCTruth(), IsolatedTrackAnalysis::getHepMCTruth(), PhotonJet::process_event(), DumpPHHepMCGenEventMap::process_Node(), and Fun4AllHepMCPileupInputManager::PushBackEvents().
Iter PHHepMCGenEventMap::begin (void) inline
Definition at line 71 of file PHHepMCGenEventMap.h.
View newest version in sPHENIX GitHub at line 71 of file PHHepMCGenEventMap.h
References _map.
PHHepMCGenEventMap::ClassDefOverride (PHHepMCGenEventMap , 4) private
void PHHepMCGenEventMap::clear () inline
Definition at line 45 of file PHHepMCGenEventMap.h.
View newest version in sPHENIX GitHub at line 45 of file PHHepMCGenEventMap.h
References Reset().
PHHepMCGenEventMap* PHHepMCGenEventMap::CloneMe () const inline override virtual
Virtual copy constructor.
Reimplemented from PHObject.
Definition at line 40 of file PHHepMCGenEventMap.h.
View newest version in sPHENIX GitHub at line 40 of file PHHepMCGenEventMap.h
References PHHepMCGenEventMap().
size_t PHHepMCGenEventMap::count (int idkey) const inline
Definition at line 44 of file PHHepMCGenEventMap.h.
View newest version in sPHENIX GitHub at line 44 of file PHHepMCGenEventMap.h
References _map.
bool PHHepMCGenEventMap::empty () const inline
container service
Definition at line 42 of file PHHepMCGenEventMap.h.
View newest version in sPHENIX GitHub at line 42 of file PHHepMCGenEventMap.h
References _map.
ConstIter PHHepMCGenEventMap::end (void) const inline
Definition at line 70 of file PHHepMCGenEventMap.h.
View newest version in sPHENIX GitHub at line 70 of file PHHepMCGenEventMap.h
References _map.
Referenced by FermimotionAfterburner::AddpF(), EventEvaluator::fillOutputNtuples(), AnaTutorial::getHEPMCTruth(), IsolatedTrackAnalysis::getHepMCTruth(), PhotonJet::process_event(), DumpPHHepMCGenEventMap::process_Node(), and Fun4AllHepMCPileupInputManager::PushBackEvents().
Iter PHHepMCGenEventMap::end (void) inline
Definition at line 72 of file PHHepMCGenEventMap.h.
View newest version in sPHENIX GitHub at line 72 of file PHHepMCGenEventMap.h
References _map.
size_t PHHepMCGenEventMap::erase (int idkey) inline
Definition at line 59 of file PHHepMCGenEventMap.h.
View newest version in sPHENIX GitHub at line 59 of file PHHepMCGenEventMap.h
References _map.
ConstIter PHHepMCGenEventMap::find (unsigned int idkey) const inline
find
Definition at line 66 of file PHHepMCGenEventMap.h.
View newest version in sPHENIX GitHub at line 66 of file PHHepMCGenEventMap.h
References _map.
Referenced by Fun4AllOscarInputManager::ConvertFromOscar(), and Fun4AllHepMCInputManager::run().
Iter PHHepMCGenEventMap::find (int idkey) inline
Definition at line 67 of file PHHepMCGenEventMap.h.
View newest version in sPHENIX GitHub at line 67 of file PHHepMCGenEventMap.h
References _map.
const PHHepMCGenEvent * PHHepMCGenEventMap::get (int idkey) const
fetch event
Definition at line 57 of file PHHepMCGenEventMap.cc.
View newest version in sPHENIX GitHub at line 57 of file PHHepMCGenEventMap.cc
References _map.
Referenced by ExclusiveReco::AddInvariantMassInformation(), DISKinematicsReco::AddTruthEventInformation(), DISKinematicsReco::CollectEmCandidatesFromTruth(), ResonanceJetTagging::findMCTaggedJets(), AntiTrigger::findParticle(), HFTrackEfficiency::findTracks(), BuildResonanceJetTaggingTree::getGenEventFromNode(), KFParticle_truthAndDetTools::getHepMCInfo(), BuildResonanceJetTaggingTree::getMother(), PHHepMCGenHelper::HepMC2Lab_boost_rotation_translation(), QAG4SimulationKFParticle::makeHepLV(), PHHepMCParticleSelectorDecayProductChain::process_event(), TracksInJets::process_event(), Quarkonia2LeptonsMC::process_event(), HFJetTruthTrigger::process_event(), BJetModule::process_event(), HFMLTriggerHepMCTrigger::process_event(), DirectPhotonPythia::process_event(), HFFastSim::process_event(), HFMLTriggerInterface::process_event(), SynRadAna::process_event(), TruthPhotonJet::process_event(), TruthJetTagging::process_event(), JetHepMCLoader::process_event(), FullJetFinder::process_event(), and Fun4AllHepMCOutputManager::Write().
PHHepMCGenEvent * PHHepMCGenEventMap::get (int idkey)
Definition at line 64 of file PHHepMCGenEventMap.cc.
View newest version in sPHENIX GitHub at line 64 of file PHHepMCGenEventMap.cc
References _map.
const HepMCGenEventMap& PHHepMCGenEventMap::get_map () const inline
for c++11 range-based for loop
Definition at line 80 of file PHHepMCGenEventMap.h.
View newest version in sPHENIX GitHub at line 80 of file PHHepMCGenEventMap.h
References _map.
Referenced by operator=(), PHHepMCGenEventMap(), and PHG4ScoringManager::process_event().
HepMCGenEventMap& PHHepMCGenEventMap::get_map () inline
Definition at line 81 of file PHHepMCGenEventMap.h.
View newest version in sPHENIX GitHub at line 81 of file PHHepMCGenEventMap.h
References _map.
void PHHepMCGenEventMap::identify (std::ostream & os = std::cout) const override virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from PHObject.
Definition at line 43 of file PHHepMCGenEventMap.cc.
View newest version in sPHENIX GitHub at line 43 of file PHHepMCGenEventMap.cc
References _map, and assert.
Referenced by ExclusiveReco::AddInvariantMassInformation(), DISKinematicsReco::AddTruthEventInformation(), DISKinematicsReco::CollectEmCandidatesFromTruth(), PHHepMCGenHelper::HepMC2Lab_boost_rotation_translation(), insert_event(), TracksInJets::process_event(), Quarkonia2LeptonsMC::process_event(), HFJetTruthTrigger::process_event(), BJetModule::process_event(), HFMLTriggerHepMCTrigger::process_event(), DirectPhotonPythia::process_event(), HFFastSim::process_event(), HFMLTriggerInterface::process_event(), and TruthJetTagging::process_event().
PHHepMCGenEvent* PHHepMCGenEventMap::insert (const PHHepMCGenEvent * event) inline
insert a event of interest, e.g. jetty event from pythia
Definition at line 51 of file PHHepMCGenEventMap.h.
View newest version in sPHENIX GitHub at line 51 of file PHHepMCGenEventMap.h
References insert_active_event().
PHHepMCGenEvent * PHHepMCGenEventMap::insert_active_event (const PHHepMCGenEvent * event = nullptr)
insert a event of interest, e.g. jetty event from pythia
Definition at line 71 of file PHHepMCGenEventMap.cc.
View newest version in sPHENIX GitHub at line 71 of file PHHepMCGenEventMap.cc
References _map, index, and PHHepMCGenEvent::set_embedding_id().
Referenced by insert(), and Fun4AllHepMCPileupInputManager::InsertEvent().
PHHepMCGenEvent * PHHepMCGenEventMap::insert_background_event (const PHHepMCGenEvent * event = nullptr)
insert a event of background, e.g. Au+Au collision background. First event has embedding ID = 0, which is usually the primary Au+Au collision in the case of HI embedding
Definition at line 80 of file PHHepMCGenEventMap.cc.
View newest version in sPHENIX GitHub at line 80 of file PHHepMCGenEventMap.cc
References _map, index, and PHHepMCGenEvent::set_embedding_id().
Referenced by Fun4AllDstPileupMerger::copy_background_event(), and Fun4AllHepMCPileupInputManager::InsertEvent().
PHHepMCGenEvent * PHHepMCGenEventMap::insert_event (const int embedding_id, const PHHepMCGenEvent * event = nullptr)
insert a event with specific embedding ID
Definition at line 89 of file PHHepMCGenEventMap.cc.
View newest version in sPHENIX GitHub at line 89 of file PHHepMCGenEventMap.cc
References _map, identify(), and PHHepMCGenEvent::set_embedding_id().
Referenced by PHHepMCGenHelper::insert_event(), and sPHAnalysis::process_event_hepmc().
int PHHepMCGenEventMap::isValid () const inline override virtual
isValid returns non zero if object contains vailid data
Reimplemented from PHObject.
Definition at line 39 of file PHHepMCGenEventMap.h.
View newest version in sPHENIX GitHub at line 39 of file PHHepMCGenEventMap.h
PHHepMCGenEventMap & PHHepMCGenEventMap::operator= (const PHHepMCGenEventMap & eventmap)
Definition at line 18 of file PHHepMCGenEventMap.cc.
View newest version in sPHENIX GitHub at line 18 of file PHHepMCGenEventMap.cc
References _map, get_map(), and Reset().
ConstReverseIter PHHepMCGenEventMap::rbegin () const inline
iterator from lowest ID to highest, i.e. signal to background
Definition at line 74 of file PHHepMCGenEventMap.h.
View newest version in sPHENIX GitHub at line 74 of file PHHepMCGenEventMap.h
References _map.
Referenced by LeptoquarksReco::AddTrueTauTag(), DecayFinder::findDecay(), HepMCFlowAfterBurner::process_event(), HepMCNodeReader::process_event(), sPHAnalysis::process_event_bimp(), sPHAnalysis::process_event_hepmc(), sPHAnalysis::process_event_pythiaupsilon(), and PHG4ParticleGeneratorBase::ReuseExistingVertex().
ReverseIter PHHepMCGenEventMap::rbegin () inline
Definition at line 76 of file PHHepMCGenEventMap.h.
View newest version in sPHENIX GitHub at line 76 of file PHHepMCGenEventMap.h
References _map.
ConstReverseIter PHHepMCGenEventMap::rend () const inline
Definition at line 75 of file PHHepMCGenEventMap.h.
View newest version in sPHENIX GitHub at line 75 of file PHHepMCGenEventMap.h
References _map.
Referenced by LeptoquarksReco::AddTrueTauTag(), DecayFinder::findDecay(), HepMCFlowAfterBurner::process_event(), HepMCNodeReader::process_event(), sPHAnalysis::process_event_bimp(), sPHAnalysis::process_event_hepmc(), sPHAnalysis::process_event_pythiaupsilon(), PHG4ParticleGeneratorBase::ReuseExistingVertex(), and rv2().
ReverseIter PHHepMCGenEventMap::rend () inline
Definition at line 77 of file PHHepMCGenEventMap.h.
View newest version in sPHENIX GitHub at line 77 of file PHHepMCGenEventMap.h
References _map.
void PHHepMCGenEventMap::Reset () override virtual
Clear Event.
Reimplemented from PHObject.
Definition at line 31 of file PHHepMCGenEventMap.cc.
View newest version in sPHENIX GitHub at line 31 of file PHHepMCGenEventMap.cc
References _map.
Referenced by clear(), operator=(), and ~PHHepMCGenEventMap().
size_t PHHepMCGenEventMap::size (void) const inline
Definition at line 43 of file PHHepMCGenEventMap.h.
View newest version in sPHENIX GitHub at line 43 of file PHHepMCGenEventMap.h
References _map.
Referenced by TPCIntegratedCharge::process_event(), TPCDataStreamEmulator::process_event(), TPCMLDataInterface::process_event(), PHG4ScoringManager::process_event(), and DumpPHHepMCGenEventMap::process_Node().
Member Data Documentation
HepMCGenEventMap PHHepMCGenEventMap::_map private
Definition at line 84 of file PHHepMCGenEventMap.h.
View newest version in sPHENIX GitHub at line 84 of file PHHepMCGenEventMap.h
Referenced by begin(), count(), empty(), end(), erase(), find(), get(), get_map(), identify(), insert_active_event(), insert_background_event(), insert_event(), operator=(), PHHepMCGenEventMap(), rbegin(), rend(), Reset(), and size().
The documentation for this class was generated from the following files:
coresoftware/blob/master/generators/phhepmc/PHHepMCGenEventMap.h
coresoftware/blob/master/generators/phhepmc/PHHepMCGenEventMap.cc