Analysis Software: PHG4Utils Class Reference
PHG4Utils Class Reference
#include <coresoftware/blob/master/simulation/g4simulation/g4main/PHG4Utils.h>
Static Public Member Functions
static double GetLengthForRapidityCoverage (const double radius, const double eta)
static double GetLengthForRapidityCoverage (const double radius)
static void SetPseudoRapidityCoverage (const double eta)
static void SetColour (G4VisAttributes *att, const std::string &mat)
static double get_theta (const double eta)
static double get_eta (const double theta)
static std::pair< double, double > get_etaphi (const double x, const double y, const double z)
static double get_eta (const double radius, const double z)
static std::pair< bool, double > line_and_rectangle_intersect (double ax, double ay, double bx, double by, double cx, double cy, double dx, double dy)
static std::pair< bool,
std::pair< double, double > > lines_intersect (double ax, double ay, double bx, double by, double cx, double cy, double dx, double dy)
static double circle_rectangle_intersection (double x1, double y1, double x2, double y2, double mx, double my, double r)
static double sA (double r, double x, double y)
static std::string md5sum (const std::string &filename)
Static Private Attributes
static double _eta_coverage = 1.
Detailed Description
Definition at line 11 of file PHG4Utils.h.
View newest version in sPHENIX GitHub at line 11 of file PHG4Utils.h
Member Function Documentation
double PHG4Utils::circle_rectangle_intersection (double x1, double y1, double x2, double y2, double mx, double my, double r) static
Definition at line 381 of file PHG4Utils.cc.
View newest version in sPHENIX GitHub at line 381 of file PHG4Utils.cc
Referenced by PHG4InttHitReco::process_event(), and PHG4MvtxHitReco::process_event().
double PHG4Utils::get_eta (const double theta) static
Definition at line 58 of file PHG4Utils.cc.
View newest version in sPHENIX GitHub at line 58 of file PHG4Utils.cc
References eta.
Referenced by PHG4BlockCellReco::InitRun(), PHG4CylinderCellReco::InitRun(), and PHG4SimpleEventGenerator::process_event().
double PHG4Utils::get_eta (const double radius, const double z) static
Definition at line 79 of file PHG4Utils.cc.
View newest version in sPHENIX GitHub at line 79 of file PHG4Utils.cc
References eta, and ActsTests::PropagationDatasets::theta.
pair< double, double > PHG4Utils::get_etaphi (const double x, const double y, const double z) static
Definition at line 65 of file PHG4Utils.cc.
View newest version in sPHENIX GitHub at line 65 of file PHG4Utils.cc
References eta, ActsTests::PropagationDatasets::phi, and ActsTests::PropagationDatasets::theta.
Referenced by PHG4BlockCellReco::process_event(), and PHG4CylinderCellReco::process_event().
double PHG4Utils::get_theta (const double eta) static
Definition at line 51 of file PHG4Utils.cc.
View newest version in sPHENIX GitHub at line 51 of file PHG4Utils.cc
References ActsTests::PropagationDatasets::theta.
Referenced by PHG4OHCalDetector::AddGeometryNode(), PHG4IHCalDetector::AddGeometryNode(), PHG4OuterHcalDetector::AddGeometryNode(), PHG4InnerHcalDetector::AddGeometryNode(), PHG4SpacalDetector::AddTowerGeometryNode(), PHG4OuterHcalDetector::ConstructHcalSingleScintillators(), PHG4InnerHcalDetector::ConstructHcalSingleScintillators(), RawTowerBuilder::CreateNodes(), and HcalRawTowerBuilder::InitRun().
double PHG4Utils::GetLengthForRapidityCoverage (const double radius, const double eta) static
Definition at line 31 of file PHG4Utils.cc.
View newest version in sPHENIX GitHub at line 31 of file PHG4Utils.cc
References G4PLUGDOOR::length, and ActsTests::PropagationDatasets::theta.
Referenced by CEmc_2DProjectiveSpacal(), PHG4HcalDetector::ConstructMe(), PHG4HcalSubsystem::InitRun(), and PHG4CylinderSubsystem::InitRunSubsystem().
double PHG4Utils::GetLengthForRapidityCoverage (const double radius) static
Definition at line 40 of file PHG4Utils.cc.
View newest version in sPHENIX GitHub at line 40 of file PHG4Utils.cc
std::pair< bool, double > PHG4Utils::line_and_rectangle_intersect (double ax, double ay, double bx, double by, double cx, double cy, double dx, double dy) static
Definition at line 246 of file PHG4Utils.cc.
View newest version in sPHENIX GitHub at line 246 of file PHG4Utils.cc
References dy, PHWHERE, vx, and vy.
Referenced by PHG4BlockCellReco::process_event(), and PHG4CylinderCellReco::process_event().
std::pair< bool, std::pair< double, double > > PHG4Utils::lines_intersect (double ax, double ay, double bx, double by, double cx, double cy, double dx, double dy) static
Definition at line 191 of file PHG4Utils.cc.
View newest version in sPHENIX GitHub at line 191 of file PHG4Utils.cc
References CKF_timing_vs_mu::ax, gx, gy, and h.
string PHG4Utils::md5sum (const std::string & filename) static
Definition at line 404 of file PHG4Utils.cc.
View newest version in sPHENIX GitHub at line 404 of file PHG4Utils.cc
References Acts::PhysicalConstants::c, and Acts::Test::hash().
double PHG4Utils::sA (double r, double x, double y) static
Definition at line 337 of file PHG4Utils.cc.
View newest version in sPHENIX GitHub at line 337 of file PHG4Utils.cc
References KFPMath::a, physmon_track_finding_ttbar::r, and y.
void PHG4Utils::SetColour (G4VisAttributes * att, const std::string & mat) static
Definition at line 92 of file PHG4Utils.cc.
View newest version in sPHENIX GitHub at line 92 of file PHG4Utils.cc
Referenced by PHG4BlockDisplayAction::ApplyDisplayAction(), PHG4CylinderDisplayAction::ApplyDisplayAction(), PHG4MvtxDisplayAction::ApplyDisplayAction(), PHG4TpcEndCapDisplayAction::ApplyDisplayAction(), G4Example03DisplayAction::ApplyDisplayAction(), PHG4ConeDisplayAction::ApplyDisplayAction(), PHG4SectorDisplayAction::ApplyDisplayAction(), PHG4SpacalDisplayAction::ApplyDisplayAction(), PHG4SpacalPrototypeDetector::Construct_Fiber(), PHG4SpacalPrototype4Detector::Construct_Fiber(), PHG4SpacalPrototype4Detector::Construct_LightGuide(), PHG4SpacalPrototypeDetector::Construct_LightGuide(), PHG4BeamlineMagnetDetector::ConstructMe(), PHG4HcalDetector::ConstructMe(), PHG4SpacalPrototypeDetector::ConstructMe(), PHG4SpacalPrototype4Detector::ConstructMe(), and PHG4GDMLDetector::SetDisplayProperty().
void PHG4Utils::SetPseudoRapidityCoverage (const double eta) static
Definition at line 45 of file PHG4Utils.cc.
View newest version in sPHENIX GitHub at line 45 of file PHG4Utils.cc
References eta.
Referenced by PHG4Reco::set_rapidity_coverage().
Member Data Documentation
double PHG4Utils::_eta_coverage = 1. static private
Definition at line 29 of file PHG4Utils.h.
View newest version in sPHENIX GitHub at line 29 of file PHG4Utils.h
The documentation for this class was generated from the following files:
coresoftware/blob/master/simulation/g4simulation/g4main/PHG4Utils.h
coresoftware/blob/master/simulation/g4simulation/g4main/PHG4Utils.cc