Analysis Software: BBCStudy Class Reference
BBCStudy Class Reference
#include <analysis/blob/master/BBCStudy/BBCStudy.h>
Public Member Functions
BBCStudy (const std::string &name="BBCStudy")
int Init (PHCompositeNode *)
int InitRun (PHCompositeNode *)
int process_event (PHCompositeNode *)
int End (PHCompositeNode *)
Called at the end of all processing.
void set_savefile (const char *f)
void set_tres (const Float_t tr)
Public Member Functions inherited from SubsysReco
~SubsysReco () override
virtual int EndRun (const int)
Called at the end of each run.
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
void Print (const std::string &="ALL") const override
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Private Member Functions
void CheckDST (PHCompositeNode *topNode)
void GetNodes (PHCompositeNode *)
Private Attributes
std::string _savefname
TFile * _savefile
int nprocessed {0}
TTree * _tree
Int_t f_evt
Float_t f_bimp
Int_t f_ncoll
Int_t f_npart
Float_t f_vx
Float_t f_vy
Float_t f_vz
Float_t f_vt
Short_t f_bbcn [2]
Float_t f_bbcq [2]
Float_t f_bbct [2]
Float_t f_bbcte [2]
Float_t f_bbcz
Float_t f_bbct0
TH1 * h_bbcq [128]
TH1 * h_bbcqtot [2]
TH2 * h2_bbcqtot
TH1 * h_ztrue
TH1 * h_tdiff
TH2 * h2_tdiff_ch
TCanvas * c_bbct
TH1 * hevt_bbct [2]
TF1 * gaussian
std::map< int, int > _pids
TDatabasePDG * _pdg
TRandom3 * _rndm
Float_t _tres
PHG4TruthInfoContainer * _truth_container
PHG4HitContainer * _bbchits
EventHeader * _evtheader
MbdOut * _bbcout
MbdPmtContainer * _bbcpmts
MbdGeom * _bbcgeom
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = std::numeric_limits<int>::max() - 10
}
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Detailed Description
Definition at line 28 of file BBCStudy.h.
View newest version in sPHENIX GitHub at line 28 of file BBCStudy.h
Constructor & Destructor Documentation
BBCStudy::BBCStudy (const std::string & name = "BBCStudy")
Definition at line 41 of file BBCStudy.cc.
View newest version in sPHENIX GitHub at line 41 of file BBCStudy.cc
Member Function Documentation
void BBCStudy::CheckDST (PHCompositeNode * topNode) private
Definition at line 517 of file BBCStudy.cc.
View newest version in sPHENIX GitHub at line 517 of file BBCStudy.cc
References _bbcout, _bbcpmts, f_bbcq, f_bbcz, f_evt, MbdOut::get_q(), MbdOut::get_zvtx(), and PHWHERE.
int BBCStudy::End (PHCompositeNode *) virtual
Called at the end of all processing.
Reimplemented from SubsysReco.
Definition at line 493 of file BBCStudy.cc.
View newest version in sPHENIX GitHub at line 493 of file BBCStudy.cc
References _pids, _savefile, npart(), and train_ambiguity_solver::pid.
void BBCStudy::GetNodes (PHCompositeNode * topNode) private
Definition at line 475 of file BBCStudy.cc.
View newest version in sPHENIX GitHub at line 475 of file BBCStudy.cc
References _bbchits, _evtheader, _truth_container, f_evt, and PHWHERE.
Referenced by InitRun().
int BBCStudy::Init (PHCompositeNode *) virtual
Called during initialization. Typically this is where you can book histograms, and e.g. register them to Fun4AllServer (so they can be output to file using Fun4AllServer::dumpHistos() method).
Reimplemented from SubsysReco.
Definition at line 54 of file BBCStudy.cc.
View newest version in sPHENIX GitHub at line 54 of file BBCStudy.cc
References _pdg, _rndm, _savefile, _savefname, _tree, c_bbct, f_bbcn, f_bbcq, f_bbct, f_bbct0, f_bbcte, f_bbcz, f_bimp, f_evt, f_ncoll, f_npart, f_vx, f_vy, f_vz, gaussian, h2_bbcqtot, h2_tdiff_ch, h_bbcq, h_bbcqtot, h_tdiff, h_ztrue, hevt_bbct, MbdDefs::MBD_N_PMT, perf_headwind::name, PHWHERE, and title.
int BBCStudy::InitRun (PHCompositeNode *) virtual
Called for first event when run number is known. Typically this is where you may want to fetch data from database, because you know the run number.
Reimplemented from SubsysReco.
Definition at line 125 of file BBCStudy.cc.
View newest version in sPHENIX GitHub at line 125 of file BBCStudy.cc
References _bbcgeom, and GetNodes().
int BBCStudy::process_event (PHCompositeNode *) virtual
Called for each event. This is where you do the real work.
Reimplemented from SubsysReco.
Definition at line 135 of file BBCStudy.cc.
View newest version in sPHENIX GitHub at line 135 of file BBCStudy.cc
References _bbcgeom, _bbchits, _evtheader, _pdg, _pids, _rndm, _tree, _tres, _truth_container, parse_cmake_options::begin, C, c_bbct, charge(), end, f_bbcn, f_bbcq, f_bbct, f_bbct0, f_bbcte, f_bbcz, f_bimp, f_evt, f_ncoll, f_npart, f_vt, f_vx, f_vy, f_vz, gaussian, MbdGeom::get_arm(), PHG4Particle::get_e(), PHG4Hit::get_edep(), EventHeader::get_EvtSequence(), EventHeader::get_ImpactParameter(), PHG4Particle::get_IonCharge(), PHG4Hit::get_layer(), EventHeader::get_ncoll(), EventHeader::get_npart(), PHG4Hit::get_path_length(), PHG4Particle::get_pid(), PHG4Particle::get_px(), PHG4Particle::get_py(), PHG4Particle::get_pz(), PHG4VtxPoint::get_t(), PHG4Hit::get_t(), PHG4Particle::get_track_id(), PHG4Hit::get_trkid(), MbdGeom::get_x(), PHG4VtxPoint::get_x(), PHG4Hit::get_x(), MbdGeom::get_y(), PHG4VtxPoint::get_y(), PHG4Hit::get_y(), PHG4VtxPoint::get_z(), PHG4Hit::get_z(), PHG4HitContainer::getHits(), PHG4TruthInfoContainer::GetNumVertices(), PHG4TruthInfoContainer::GetParticle(), PHG4TruthInfoContainer::GetPrimaryVertexIndex(), PHG4TruthInfoContainer::GetPrimaryVtx(), PHG4TruthInfoContainer::GetVtxRange(), h2_bbcqtot, h2_tdiff_ch, h_bbcq, h_bbcqtot, h_tdiff, h_ztrue, hevt_bbct, PHG4Particle::isIon(), MbdDefs::MBD_N_PMT, perf_headwind::name, nprocessed, PHWHERE, train_ambiguity_solver::pid, Acts::Experimental::detail::BlueprintHelper::sort(), v4, and MbdDefs::v_ckov.
void BBCStudy::set_savefile (const char * f) inline
Definition at line 48 of file BBCStudy.h.
View newest version in sPHENIX GitHub at line 48 of file BBCStudy.h
References _savefname, and f.
Referenced by Run_BBCStudy().
void BBCStudy::set_tres (const Float_t tr) inline
Definition at line 50 of file BBCStudy.h.
View newest version in sPHENIX GitHub at line 50 of file BBCStudy.h
References _tres.
Member Data Documentation
MbdGeom* BBCStudy::_bbcgeom private
Definition at line 107 of file BBCStudy.h.
View newest version in sPHENIX GitHub at line 107 of file BBCStudy.h
Referenced by InitRun(), and process_event().
PHG4HitContainer* BBCStudy::_bbchits private
Definition at line 103 of file BBCStudy.h.
View newest version in sPHENIX GitHub at line 103 of file BBCStudy.h
Referenced by GetNodes(), and process_event().
MbdOut* BBCStudy::_bbcout private
Definition at line 105 of file BBCStudy.h.
View newest version in sPHENIX GitHub at line 105 of file BBCStudy.h
Referenced by CheckDST().
MbdPmtContainer* BBCStudy::_bbcpmts private
Definition at line 106 of file BBCStudy.h.
View newest version in sPHENIX GitHub at line 106 of file BBCStudy.h
Referenced by CheckDST().
EventHeader* BBCStudy::_evtheader private
Definition at line 104 of file BBCStudy.h.
View newest version in sPHENIX GitHub at line 104 of file BBCStudy.h
Referenced by GetNodes(), and process_event().
TDatabasePDG* BBCStudy::_pdg private
Definition at line 94 of file BBCStudy.h.
View newest version in sPHENIX GitHub at line 94 of file BBCStudy.h
Referenced by Init(), and process_event().
std::map<int,int> BBCStudy::_pids private
Definition at line 91 of file BBCStudy.h.
View newest version in sPHENIX GitHub at line 91 of file BBCStudy.h
Referenced by End(), and process_event().
TRandom3* BBCStudy::_rndm private
Definition at line 95 of file BBCStudy.h.
View newest version in sPHENIX GitHub at line 95 of file BBCStudy.h
Referenced by Init(), and process_event().
TFile* BBCStudy::_savefile private
Definition at line 59 of file BBCStudy.h.
View newest version in sPHENIX GitHub at line 59 of file BBCStudy.h
Referenced by End(), and Init().
std::string BBCStudy::_savefname private
Definition at line 58 of file BBCStudy.h.
View newest version in sPHENIX GitHub at line 58 of file BBCStudy.h
Referenced by Init(), and set_savefile().
TTree* BBCStudy::_tree private
Definition at line 64 of file BBCStudy.h.
View newest version in sPHENIX GitHub at line 64 of file BBCStudy.h
Referenced by Init(), and process_event().
Float_t BBCStudy::_tres private
Definition at line 96 of file BBCStudy.h.
View newest version in sPHENIX GitHub at line 96 of file BBCStudy.h
Referenced by process_event(), and set_tres().
PHG4TruthInfoContainer* BBCStudy::_truth_container private
Definition at line 102 of file BBCStudy.h.
View newest version in sPHENIX GitHub at line 102 of file BBCStudy.h
Referenced by GetNodes(), and process_event().
TCanvas* BBCStudy::c_bbct private
Definition at line 87 of file BBCStudy.h.
View newest version in sPHENIX GitHub at line 87 of file BBCStudy.h
Referenced by Init(), and process_event().
Short_t BBCStudy::f_bbcn[2] private
Definition at line 73 of file BBCStudy.h.
View newest version in sPHENIX GitHub at line 73 of file BBCStudy.h
Referenced by Init(), and process_event().
Float_t BBCStudy::f_bbcq[2] private
Definition at line 74 of file BBCStudy.h.
View newest version in sPHENIX GitHub at line 74 of file BBCStudy.h
Referenced by CheckDST(), Init(), and process_event().
Float_t BBCStudy::f_bbct[2] private
Definition at line 75 of file BBCStudy.h.
View newest version in sPHENIX GitHub at line 75 of file BBCStudy.h
Referenced by Init(), and process_event().
Float_t BBCStudy::f_bbct0 private
Definition at line 78 of file BBCStudy.h.
View newest version in sPHENIX GitHub at line 78 of file BBCStudy.h
Referenced by Init(), and process_event().
Float_t BBCStudy::f_bbcte[2] private
Definition at line 76 of file BBCStudy.h.
View newest version in sPHENIX GitHub at line 76 of file BBCStudy.h
Referenced by Init(), and process_event().
Float_t BBCStudy::f_bbcz private
Definition at line 77 of file BBCStudy.h.
View newest version in sPHENIX GitHub at line 77 of file BBCStudy.h
Referenced by CheckDST(), Init(), and process_event().
Float_t BBCStudy::f_bimp private
Definition at line 66 of file BBCStudy.h.
View newest version in sPHENIX GitHub at line 66 of file BBCStudy.h
Referenced by Init(), and process_event().
Int_t BBCStudy::f_evt private
Definition at line 65 of file BBCStudy.h.
View newest version in sPHENIX GitHub at line 65 of file BBCStudy.h
Referenced by CheckDST(), GetNodes(), Init(), and process_event().
Int_t BBCStudy::f_ncoll private
Definition at line 67 of file BBCStudy.h.
View newest version in sPHENIX GitHub at line 67 of file BBCStudy.h
Referenced by Init(), and process_event().
Int_t BBCStudy::f_npart private
Definition at line 68 of file BBCStudy.h.
View newest version in sPHENIX GitHub at line 68 of file BBCStudy.h
Referenced by Init(), and process_event().
Float_t BBCStudy::f_vt private
Definition at line 72 of file BBCStudy.h.
View newest version in sPHENIX GitHub at line 72 of file BBCStudy.h
Referenced by process_event().
Float_t BBCStudy::f_vx private
Definition at line 69 of file BBCStudy.h.
View newest version in sPHENIX GitHub at line 69 of file BBCStudy.h
Referenced by Init(), and process_event().
Float_t BBCStudy::f_vy private
Definition at line 70 of file BBCStudy.h.
View newest version in sPHENIX GitHub at line 70 of file BBCStudy.h
Referenced by Init(), and process_event().
Float_t BBCStudy::f_vz private
Definition at line 71 of file BBCStudy.h.
View newest version in sPHENIX GitHub at line 71 of file BBCStudy.h
Referenced by Init(), and process_event().
TF1* BBCStudy::gaussian private
Definition at line 89 of file BBCStudy.h.
View newest version in sPHENIX GitHub at line 89 of file BBCStudy.h
Referenced by Init(), and process_event().
TH2* BBCStudy::h2_bbcqtot private
Definition at line 82 of file BBCStudy.h.
View newest version in sPHENIX GitHub at line 82 of file BBCStudy.h
Referenced by Init(), and process_event().
TH2* BBCStudy::h2_tdiff_ch private
Definition at line 85 of file BBCStudy.h.
View newest version in sPHENIX GitHub at line 85 of file BBCStudy.h
Referenced by Init(), and process_event().
TH1* BBCStudy::h_bbcq[128] private
Definition at line 80 of file BBCStudy.h.
View newest version in sPHENIX GitHub at line 80 of file BBCStudy.h
Referenced by Init(), and process_event().
TH1* BBCStudy::h_bbcqtot[2] private
Definition at line 81 of file BBCStudy.h.
View newest version in sPHENIX GitHub at line 81 of file BBCStudy.h
Referenced by Init(), and process_event().
TH1* BBCStudy::h_tdiff private
Definition at line 84 of file BBCStudy.h.
View newest version in sPHENIX GitHub at line 84 of file BBCStudy.h
Referenced by Init(), and process_event().
TH1* BBCStudy::h_ztrue private
Definition at line 83 of file BBCStudy.h.
View newest version in sPHENIX GitHub at line 83 of file BBCStudy.h
Referenced by Init(), and process_event().
TH1* BBCStudy::hevt_bbct[2] private
Definition at line 88 of file BBCStudy.h.
View newest version in sPHENIX GitHub at line 88 of file BBCStudy.h
Referenced by Init(), and process_event().
int BBCStudy::nprocessed {0} private
Definition at line 61 of file BBCStudy.h.
View newest version in sPHENIX GitHub at line 61 of file BBCStudy.h
Referenced by process_event().
The documentation for this class was generated from the following files:
analysis/blob/master/BBCStudy/BBCStudy.h
analysis/blob/master/BBCStudy/BBCStudy.cc