Analysis Software: GeneralElement Class Reference
GeneralElement Class Reference
#include <JETSCAPE/blob/main/external_packages/cornelius.h>
Public Member Functions
GeneralElement ()
~GeneralElement ()
double * get_centroid ()
double * get_normal ()
GeneralElement ()
~GeneralElement ()
double * get_centroid ()
double * get_normal ()
GeneralElement ()
~GeneralElement ()
double * get_centroid ()
double * get_normal ()
GeneralElement ()
~GeneralElement ()
double * get_centroid ()
double * get_normal ()
Protected Member Functions
virtual void calculate_centroid ()
virtual void calculate_normal ()
void check_normal_direction (double *normal, double *out)
virtual void calculate_centroid ()
virtual void calculate_normal ()
void check_normal_direction (double *normal, double *out)
virtual void calculate_centroid ()
virtual void calculate_normal ()
void check_normal_direction (double *normal, double *out)
virtual void calculate_centroid ()
virtual void calculate_normal ()
void check_normal_direction (double *normal, double *out)
Protected Attributes
double * centroid
double * normal
int normal_calculated
int centroid_calculated
Static Protected Attributes
static const int DIM = 4
Detailed Description
General class for elements. All other element classes are inherited from this.
Definition at line 40 of file cornelius.cpp.
View newest version in sPHENIX GitHub at line 40 of file cornelius.cpp
Constructor & Destructor Documentation
GeneralElement::GeneralElement ()
Constructor allocates memory for centroid and normal.
Definition at line 63 of file cornelius.cpp.
View newest version in sPHENIX GitHub at line 63 of file cornelius.cpp
GeneralElement::~GeneralElement ()
Destructor frees memory.
Definition at line 76 of file cornelius.cpp.
View newest version in sPHENIX GitHub at line 76 of file cornelius.cpp
GeneralElement::GeneralElement ()
GeneralElement::~GeneralElement ()
GeneralElement::GeneralElement ()
GeneralElement::~GeneralElement ()
GeneralElement::GeneralElement ()
GeneralElement::~GeneralElement ()
Member Function Documentation
virtual void GeneralElement::calculate_centroid () inline protected virtual
Reimplemented in Polyhedron, Polyhedron, Polygon, Polygon, Line, Line, Polyhedron, Polyhedron, Polygon, Polygon, Line, and Line.
Definition at line 25 of file cornelius.h.
View newest version in sPHENIX GitHub at line 25 of file cornelius.h
virtual void GeneralElement::calculate_centroid () inline protected virtual
Reimplemented in Polyhedron, Polyhedron, Polygon, Polygon, Line, Line, Polyhedron, Polyhedron, Polygon, Polygon, Line, and Line.
Definition at line 31 of file cornelius.h.
View newest version in sPHENIX GitHub at line 31 of file cornelius.h
virtual void GeneralElement::calculate_centroid () inline protected virtual
Reimplemented in Polyhedron, Polyhedron, Polygon, Polygon, Line, Line, Polyhedron, Polyhedron, Polygon, Polygon, Line, and Line.
Definition at line 48 of file cornelius.cpp.
View newest version in sPHENIX GitHub at line 48 of file cornelius.cpp
virtual void GeneralElement::calculate_centroid () inline protected virtual
Reimplemented in Polyhedron, Polyhedron, Polygon, Polygon, Line, Line, Polyhedron, Polyhedron, Polygon, Polygon, Line, and Line.
Definition at line 48 of file cornelius.cpp.
View newest version in sPHENIX GitHub at line 48 of file cornelius.cpp
virtual void GeneralElement::calculate_normal () inline protected virtual
Reimplemented in Polyhedron, Polyhedron, Polygon, Polygon, Line, Line, Polyhedron, Polyhedron, Polygon, Polygon, Line, and Line.
Definition at line 26 of file cornelius.h.
View newest version in sPHENIX GitHub at line 26 of file cornelius.h
virtual void GeneralElement::calculate_normal () inline protected virtual
Reimplemented in Polyhedron, Polyhedron, Polygon, Polygon, Line, Line, Polyhedron, Polyhedron, Polygon, Polygon, Line, and Line.
Definition at line 32 of file cornelius.h.
View newest version in sPHENIX GitHub at line 32 of file cornelius.h
virtual void GeneralElement::calculate_normal () inline protected virtual
Reimplemented in Polyhedron, Polyhedron, Polygon, Polygon, Line, Line, Polyhedron, Polyhedron, Polygon, Polygon, Line, and Line.
Definition at line 49 of file cornelius.cpp.
View newest version in sPHENIX GitHub at line 49 of file cornelius.cpp
virtual void GeneralElement::calculate_normal () inline protected virtual
Reimplemented in Polyhedron, Polyhedron, Polygon, Polygon, Line, Line, Polyhedron, Polyhedron, Polygon, Polygon, Line, and Line.
Definition at line 49 of file cornelius.cpp.
View newest version in sPHENIX GitHub at line 49 of file cornelius.cpp
void GeneralElement::check_normal_direction (double * normal, double * out) protected
void GeneralElement::check_normal_direction (double * normal, double * out) protected
void GeneralElement::check_normal_direction (double * normal, double * out) protected
Checks if the normal is pointing into right direction. If the normal is pointing in the wrong direction, it is turned to the right direction.
Parameters
[in/out] normal The normal vector
[in] out Vector pointing into outward direction.
Definition at line 91 of file cornelius.cpp.
View newest version in sPHENIX GitHub at line 91 of file cornelius.cpp
References dot_product(), and i.
void GeneralElement::check_normal_direction (double * normal, double * out) protected
double* GeneralElement::get_centroid ()
double* GeneralElement::get_centroid ()
double* GeneralElement::get_centroid ()
double * GeneralElement::get_centroid ()
Returns the centroid as a (double*) always in 4d.
Returns
Table containing centroid in 4D
Definition at line 115 of file cornelius.cpp.
View newest version in sPHENIX GitHub at line 115 of file cornelius.cpp
Referenced by Cornelius::find_surface_2d(), Cornelius::find_surface_4d(), and Cornelius::surface_3d().
double* GeneralElement::get_normal ()
double* GeneralElement::get_normal ()
double* GeneralElement::get_normal ()
double * GeneralElement::get_normal ()
Returns the normal as a (double*) always in 4d.
Returns
Table containing normal in 4D
Definition at line 129 of file cornelius.cpp.
View newest version in sPHENIX GitHub at line 129 of file cornelius.cpp
Referenced by Cornelius::find_surface_2d(), Cornelius::find_surface_4d(), and Cornelius::surface_3d().
Member Data Documentation
double * GeneralElement::centroid protected
Definition at line 44 of file cornelius.cpp.
View newest version in sPHENIX GitHub at line 44 of file cornelius.cpp
int GeneralElement::centroid_calculated protected
Definition at line 47 of file cornelius.cpp.
View newest version in sPHENIX GitHub at line 47 of file cornelius.cpp
static const int GeneralElement::DIM = 4 static protected
Definition at line 43 of file cornelius.cpp.
View newest version in sPHENIX GitHub at line 43 of file cornelius.cpp
double * GeneralElement::normal protected
Definition at line 45 of file cornelius.cpp.
View newest version in sPHENIX GitHub at line 45 of file cornelius.cpp
int GeneralElement::normal_calculated protected
Definition at line 46 of file cornelius.cpp.
View newest version in sPHENIX GitHub at line 46 of file cornelius.cpp
The documentation for this class was generated from the following files:
JETSCAPE/blob/main/external_packages/cornelius.cpp
JETSCAPE/blob/main/external_packages/cornelius.h
JETSCAPE/blob/main/external_packages/hydro_from_external_file/cornelius.cpp
JETSCAPE/blob/main/external_packages/hydro_from_external_file/cornelius.h