Analysis Software: SphenixClient Class Reference
SphenixClient Class Reference
#include <coresoftware/blob/master/offline/database/sphenixnpc/SphenixClient.h>
Public Member Functions
SphenixClient ()=default
SphenixClient (const std::string &globaltag)
virtual ~SphenixClient ()=default
nlohmann::json insertPayload (const std::string &pl_type, const std::string &file_url, long long iov_start)
nlohmann::json getUrlDict (long long iov)
nlohmann::json deletePayloadIOV (const std::string &pl_type, long long iov_start)
nlohmann::json getPayloadIOVs (long long iov)
nlohmann::json getUrl (const std::string &pl_type, long long iov)
nlohmann::json insertPayload (const std::string &pl_type, const std::string &file_url, long long iov_start, long long iov_end) override
nlohmann::json setGlobalTag (const std::string &name) override
std::string getCalibration (const std::string &pl_type, long long iov)
nlohmann::json unlockGlobalTag (const std::string &tagname) override
nlohmann::json lockGlobalTag (const std::string &tagname) override
nlohmann::json deletePayloadIOV (const std::string &pl_type, long long iov_start, long long iov_end) override
bool existGlobalTag (const std::string &tagname)
int createDomain (const std::string &domain)
int cache_set_GlobalTag (const std::string &name)
bool isGlobalTagSet ()
void Verbosity (int i)
int Verbosity () const
Private Attributes
int m_Verbosity = 0
std::string m_CachedGlobalTag
std::set< std::string > m_DomainCache
std::set< std::string > m_GlobalTagCache
Detailed Description
Definition at line 11 of file SphenixClient.h.
View newest version in sPHENIX GitHub at line 11 of file SphenixClient.h
Constructor & Destructor Documentation
SphenixClient::SphenixClient () default
SphenixClient::SphenixClient (const std::string & globaltag) explicit
Definition at line 11 of file SphenixClient.cc.
View newest version in sPHENIX GitHub at line 11 of file SphenixClient.cc
virtual SphenixClient::~SphenixClient () virtual default
Member Function Documentation
int SphenixClient::cache_set_GlobalTag (const std::string & name)
Definition at line 149 of file SphenixClient.cc.
View newest version in sPHENIX GitHub at line 149 of file SphenixClient.cc
References createGlobalTag(), it, m_CachedGlobalTag, and setGlobalTag().
int SphenixClient::createDomain (const std::string & domain)
Definition at line 187 of file SphenixClient.cc.
View newest version in sPHENIX GitHub at line 187 of file SphenixClient.cc
References createPayloadType(), it, and m_DomainCache.
Referenced by CDBUtils::createPayloadType().
nlohmann::json SphenixClient::deletePayloadIOV (const std::string & pl_type, long long iov_start)
Definition at line 75 of file SphenixClient.cc.
View newest version in sPHENIX GitHub at line 75 of file SphenixClient.cc
References deletePayloadIOV().
Referenced by CDBUtils::deletePayloadIOV().
nlohmann::json SphenixClient::deletePayloadIOV (const std::string & pl_type, long long iov_start, long long iov_end) override
Definition at line 80 of file SphenixClient.cc.
View newest version in sPHENIX GitHub at line 80 of file SphenixClient.cc
References deletePayloadIOV().
bool SphenixClient::existGlobalTag (const std::string & tagname)
Definition at line 226 of file SphenixClient.cc.
View newest version in sPHENIX GitHub at line 226 of file SphenixClient.cc
References it, and m_GlobalTagCache.
Referenced by lockGlobalTag(), setGlobalTag(), and unlockGlobalTag().
std::string SphenixClient::getCalibration (const std::string & pl_type, long long iov)
Definition at line 85 of file SphenixClient.cc.
View newest version in sPHENIX GitHub at line 85 of file SphenixClient.cc
References getUrl(), and m_Verbosity.
Referenced by CDBInterface::getUrl().
nlohmann::json SphenixClient::getPayloadIOVs (long long iov)
Definition at line 17 of file SphenixClient.cc.
View newest version in sPHENIX GitHub at line 17 of file SphenixClient.cc
Referenced by getUrl(), getUrlDict(), and CDBUtils::listPayloadIOVs().
nlohmann::json SphenixClient::getUrl (const std::string & pl_type, long long iov)
Definition at line 22 of file SphenixClient.cc.
View newest version in sPHENIX GitHub at line 22 of file SphenixClient.cc
References getPayloadIOVs(), and m_Verbosity.
Referenced by getCalibration(), and CDBUtils::getUrl().
nlohmann::json SphenixClient::getUrlDict (long long iov)
Definition at line 50 of file SphenixClient.cc.
View newest version in sPHENIX GitHub at line 50 of file SphenixClient.cc
References parse_cmake_options::begin, getPayloadIOVs(), it, and merge_hashes::items.
nlohmann::json SphenixClient::insertPayload (const std::string & pl_type, const std::string & file_url, long long iov_start)
Definition at line 119 of file SphenixClient.cc.
View newest version in sPHENIX GitHub at line 119 of file SphenixClient.cc
References insertPayload().
Referenced by CDBUtils::insertPayload(), and TestCDBInsert().
nlohmann::json SphenixClient::insertPayload (const std::string & pl_type, const std::string & file_url, long long iov_start, long long iov_end) override
Definition at line 125 of file SphenixClient.cc.
View newest version in sPHENIX GitHub at line 125 of file SphenixClient.cc
References insertPayload().
bool SphenixClient::isGlobalTagSet ()
Definition at line 217 of file SphenixClient.cc.
View newest version in sPHENIX GitHub at line 217 of file SphenixClient.cc
References m_CachedGlobalTag.
Referenced by CDBUtils::isGlobalTagSet().
nlohmann::json SphenixClient::lockGlobalTag (const std::string & tagname) override
Definition at line 109 of file SphenixClient.cc.
View newest version in sPHENIX GitHub at line 109 of file SphenixClient.cc
References existGlobalTag(), lockGlobalTag(), and gtest_output_test::message.
Referenced by CDBUtils::lockGlobalTag().
nlohmann::json SphenixClient::setGlobalTag (const std::string & name) override
Definition at line 131 of file SphenixClient.cc.
View newest version in sPHENIX GitHub at line 131 of file SphenixClient.cc
References existGlobalTag(), m_CachedGlobalTag, gtest_output_test::message, and setGlobalTag().
Referenced by CDBUtils::setGlobalTag().
nlohmann::json SphenixClient::unlockGlobalTag (const std::string & tagname) override
Definition at line 99 of file SphenixClient.cc.
View newest version in sPHENIX GitHub at line 99 of file SphenixClient.cc
References existGlobalTag(), gtest_output_test::message, and unlockGlobalTag().
Referenced by CDBUtils::unlockGlobalTag().
void SphenixClient::Verbosity (int i) inline
Definition at line 40 of file SphenixClient.h.
View newest version in sPHENIX GitHub at line 40 of file SphenixClient.h
References i, and m_Verbosity.
Referenced by CDBUtils::Verbosity().
int SphenixClient::Verbosity () const inline
Definition at line 41 of file SphenixClient.h.
View newest version in sPHENIX GitHub at line 41 of file SphenixClient.h
References m_Verbosity.
Member Data Documentation
std::string SphenixClient::m_CachedGlobalTag private
Definition at line 45 of file SphenixClient.h.
View newest version in sPHENIX GitHub at line 45 of file SphenixClient.h
Referenced by cache_set_GlobalTag(), isGlobalTagSet(), and setGlobalTag().
std::set<std::string> SphenixClient::m_DomainCache private
Definition at line 46 of file SphenixClient.h.
View newest version in sPHENIX GitHub at line 46 of file SphenixClient.h
Referenced by createDomain().
std::set<std::string> SphenixClient::m_GlobalTagCache private
Definition at line 47 of file SphenixClient.h.
View newest version in sPHENIX GitHub at line 47 of file SphenixClient.h
Referenced by existGlobalTag().
int SphenixClient::m_Verbosity = 0 private
Definition at line 44 of file SphenixClient.h.
View newest version in sPHENIX GitHub at line 44 of file SphenixClient.h
Referenced by getCalibration(), getUrl(), and Verbosity().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/database/sphenixnpc/SphenixClient.h
coresoftware/blob/master/offline/database/sphenixnpc/SphenixClient.cc