Analysis Software: Acts::SinglyCharged Struct Reference
Acts::SinglyCharged Struct Reference
Charge interpretation for track parameters
Charge and momentum interpretation for particles with +-e charge.
#include <acts/blob/sPHENIX/Core/include/Acts/EventData/Charge.hpp>
Public Member Functions
constexpr SinglyCharged ()=default
constexpr SinglyCharged (float absQ) noexcept
constexpr float absQ () const noexcept
template<typename T >
constexpr auto extractCharge (T qOverP) const noexcept
template<typename T >
constexpr auto extractMomentum (T qOverP) const noexcept
template<typename P , typename Q >
constexpr auto qOverP (P momentum, Q signedQ) const noexcept
Friends
constexpr bool operator== (SinglyCharged, SinglyCharged) noexcept
Detailed Description
Charge and momentum interpretation for particles with +-e charge.
Definition at line 100 of file Charge.hpp.
View newest version in sPHENIX GitHub at line 100 of file Charge.hpp
Constructor & Destructor Documentation
constexpr Acts::SinglyCharged::SinglyCharged () default
constexpr Acts::SinglyCharged::SinglyCharged (float absQ) inline noexcept
Construct and verify the input charge magnitude (in debug builds).
This constructor is only provided to allow consistent construction.
Definition at line 108 of file Charge.hpp.
View newest version in sPHENIX GitHub at line 108 of file Charge.hpp
References absQ(), assert, and Acts::UnitConstants::e.
Member Function Documentation
constexpr float Acts::SinglyCharged::absQ () const inline noexcept
Definition at line 113 of file Charge.hpp.
View newest version in sPHENIX GitHub at line 113 of file Charge.hpp
References Acts::UnitConstants::e.
Referenced by SinglyCharged().
template<typename T > constexpr auto Acts::SinglyCharged::extractCharge (T qOverP) const inline noexcept
Definition at line 116 of file Charge.hpp.
View newest version in sPHENIX GitHub at line 116 of file Charge.hpp
References autodiff::detail::copysign(), Acts::UnitConstants::e, and qOverP().
Referenced by BOOST_AUTO_TEST_CASE(), and extractMomentum().
template<typename T > constexpr auto Acts::SinglyCharged::extractMomentum (T qOverP) const inline noexcept
Definition at line 123 of file Charge.hpp.
View newest version in sPHENIX GitHub at line 123 of file Charge.hpp
References extractCharge(), and qOverP().
Referenced by BOOST_AUTO_TEST_CASE().
template<typename P , typename Q > constexpr auto Acts::SinglyCharged::qOverP (P momentum, Q signedQ) const inline noexcept
Definition at line 130 of file Charge.hpp.
View newest version in sPHENIX GitHub at line 130 of file Charge.hpp
References assert, Acts::UnitConstants::e, and momentum.
Referenced by extractCharge(), and extractMomentum().
Friends And Related Function Documentation
constexpr bool operator== (SinglyCharged , SinglyCharged) friend
Compare for equality.
This is always true as SinglyCharged has no internal state. Must be available to provide a consistent interface.
Definition at line 140 of file Charge.hpp.
View newest version in sPHENIX GitHub at line 140 of file Charge.hpp
The documentation for this struct was generated from the following file:
acts/blob/sPHENIX/Core/include/Acts/EventData/Charge.hpp