Analysis Software: ActsTrackingGeometry Struct Reference
ActsTrackingGeometry Struct Reference
#include <coresoftware/blob/master/offline/packages/trackbase/ActsTrackingGeometry.h>
Public Member Functions
ActsTrackingGeometry ()
ActsTrackingGeometry (std::shared_ptr< const Acts::TrackingGeometry > tGeo, std::shared_ptr< Acts::MagneticFieldProvider > mag, Acts::CalibrationContext calib, Acts::GeometryContext geoCtxt, Acts::MagneticFieldContext magFieldCtxt)
Acts::GeometryContext & getGeoContext ()
Public Attributes
std::shared_ptr< const
Acts::TrackingGeometry > tGeometry
Tracking geometry and magnetic field, for fitter function.
std::shared_ptr
< Acts::MagneticFieldProvider > magField
Acts::CalibrationContext calibContext
Acts context, for Kalman options.
Acts::GeometryContext geoContext
Acts::MagneticFieldContext magFieldContext
double tpcSurfStepPhi = 0
double tpcSurfStepZ = 0
Detailed Description
A struct to carry around Acts geometry on node tree, so as to not put all of the MakeActsGeometry tree
Definition at line 18 of file ActsTrackingGeometry.h.
View newest version in sPHENIX GitHub at line 18 of file ActsTrackingGeometry.h
Constructor & Destructor Documentation
ActsTrackingGeometry::ActsTrackingGeometry () inline
Definition at line 19 of file ActsTrackingGeometry.h.
View newest version in sPHENIX GitHub at line 19 of file ActsTrackingGeometry.h
ActsTrackingGeometry::ActsTrackingGeometry (std::shared_ptr< const Acts::TrackingGeometry > tGeo, std::shared_ptr< Acts::MagneticFieldProvider > mag, Acts::CalibrationContext calib, Acts::GeometryContext geoCtxt, Acts::MagneticFieldContext magFieldCtxt) inline
Definition at line 20 of file ActsTrackingGeometry.h.
View newest version in sPHENIX GitHub at line 20 of file ActsTrackingGeometry.h
Member Function Documentation
Acts::GeometryContext& ActsTrackingGeometry::getGeoContext () inline
Definition at line 44 of file ActsTrackingGeometry.h.
View newest version in sPHENIX GitHub at line 44 of file ActsTrackingGeometry.h
References geoContext.
Referenced by PHActsTrackPropagator::addTrackState(), PHTpcResiduals::addTrackState(), TpcClusterBuilder::cluster_hits(), AlignmentTransformation::createMap(), PHActsToSvtxTracks::createSvtxTrack(), DSTEmulator::evaluate_tracks(), ActsEvaluator::evaluateTrackFit(), ActsAlignmentStates::fillAlignmentStateMap(), ActsEvaluator::fillFittedTrackParams(), ActsEvaluator::fillProtoTrack(), TrackResiduals::fillStatesWithLineFit(), PHActsVertexFinder::findVertices(), PHActsInitialVertexFinder::findVertices(), PHActsVertexFitter::fitVertex(), HelicalFitter::get_helix_surface_intersection(), CylinderGeom_Mvtx::get_local_from_world_coords(), CylinderGeomMicromegas::get_local_from_world_coords(), CylinderGeomIntt::get_local_from_world_coords(), CylinderGeomMicromegas::get_local_from_world_vect(), ActsAlignmentStates::get_projectionXY(), HelicalFitter::get_projectionXY(), CylinderGeom_Mvtx::get_world_from_local_coords(), CylinderGeomMicromegas::get_world_from_local_coords(), CylinderGeomIntt::get_world_from_local_coords(), CylinderGeomMicromegas::get_world_from_local_vect(), HelicalFitter::getGlobalDerivativesXY(), MakeMilleFiles::getLocalVtxDerivativesXY(), MakeSourceLinks::getSourceLinks(), PHActsInitialVertexFinder::getTrackPointers(), PHActsVertexFitter::getTracks(), PHActsVertexFinder::getTracks(), MakeActsGeometry::InitRun(), PHActsTrackProjection::makeCaloSurfacePtrs(), PHActsGSF::makeSeed(), PHActsKDTreeSeeding::makeSpacePoint(), PHActsSiliconSeeding::makeSpacePoint(), PHActsVertexFitter::makeTrackParam(), ActsPropagator::makeTrackParams(), PHTpcResiduals::makeTrackParams(), AlignmentTransformation::newMakeTransform(), ActsPropagator::printTrackParams(), PHTpcClusterMover::process_event(), HelicalFitter::process_event(), PHTpcResiduals::processTrack(), KshortReconstruction::projectTrackToCylinder(), KshortReconstruction::projectTrackToPoint(), SecondaryVertexFinder::projectTrackToPoint(), ActsPropagator::propagateTrack(), ActsPropagator::propagateTrackFast(), MakeSourceLinks::resetTransientTransformMap(), PHActsVertexPropagator::updateSvtxTrack(), PHActsTrackProjection::updateSvtxTrack(), and ActsEvaluator::visitTrackStates().
Member Data Documentation
Acts::CalibrationContext ActsTrackingGeometry::calibContext
Acts context, for Kalman options.
Definition at line 40 of file ActsTrackingGeometry.h.
View newest version in sPHENIX GitHub at line 40 of file ActsTrackingGeometry.h
Referenced by PHCosmicsTrkFitter::loopTracks(), PHActsTrkFitter::loopTracks(), and PHActsGSF::process_event().
Acts::GeometryContext ActsTrackingGeometry::geoContext
Definition at line 41 of file ActsTrackingGeometry.h.
View newest version in sPHENIX GitHub at line 41 of file ActsTrackingGeometry.h
Referenced by AlignmentTransformation::createMap(), getGeoContext(), and PHTpcResiduals::processTrack().
std::shared_ptr<Acts::MagneticFieldProvider> ActsTrackingGeometry::magField
Definition at line 37 of file ActsTrackingGeometry.h.
View newest version in sPHENIX GitHub at line 37 of file ActsTrackingGeometry.h
Referenced by PHActsVertexFinder::findVertices(), PHActsInitialVertexFinder::findVertices(), PHActsVertexFitter::fitVertex(), PHActsGSF::InitRun(), PHCosmicsTrkFitter::InitRun(), MakeActsGeometry::InitRun(), PHActsTrkFitter::InitRun(), ActsPropagator::makeFastPropagator(), and ActsPropagator::makePropagator().
Acts::MagneticFieldContext ActsTrackingGeometry::magFieldContext
Definition at line 42 of file ActsTrackingGeometry.h.
View newest version in sPHENIX GitHub at line 42 of file ActsTrackingGeometry.h
Referenced by PHActsVertexFinder::findVertices(), PHActsInitialVertexFinder::findVertices(), PHActsVertexFitter::fitVertex(), MakeMilleFiles::getLocalVtxDerivativesXY(), PHCosmicsTrkFitter::loopTracks(), PHActsTrkFitter::loopTracks(), PHActsGSF::process_event(), ActsPropagator::propagateTrack(), and ActsPropagator::propagateTrackFast().
std::shared_ptr<const Acts::TrackingGeometry> ActsTrackingGeometry::tGeometry
Tracking geometry and magnetic field, for fitter function.
Definition at line 34 of file ActsTrackingGeometry.h.
View newest version in sPHENIX GitHub at line 34 of file ActsTrackingGeometry.h
Referenced by ActsPropagator::checkLayer(), PHActsTrkFitter::getSurfaceVector(), PHActsGSF::InitRun(), PHCosmicsTrkFitter::InitRun(), MakeActsGeometry::InitRun(), PHActsTrkFitter::InitRun(), and ActsPropagator::makePropagator().
double ActsTrackingGeometry::tpcSurfStepPhi = 0
Definition at line 49 of file ActsTrackingGeometry.h.
View newest version in sPHENIX GitHub at line 49 of file ActsTrackingGeometry.h
Referenced by ActsGeometry::get_tpc_surface_from_coords(), and MakeActsGeometry::InitRun().
double ActsTrackingGeometry::tpcSurfStepZ = 0
Definition at line 50 of file ActsTrackingGeometry.h.
View newest version in sPHENIX GitHub at line 50 of file ActsTrackingGeometry.h
Referenced by ActsGeometry::get_tpc_surface_from_coords(), and MakeActsGeometry::InitRun().
The documentation for this struct was generated from the following file:
coresoftware/blob/master/offline/packages/trackbase/ActsTrackingGeometry.h