Analysis Software: PHGenFit::SpacepointMeasurement2 Class Reference
PHGenFit::SpacepointMeasurement2 Class Reference
#include <coresoftware/blob/master/offline/packages/PHTpcTracker/SpacepointMeasurement2.h>
Public Member Functions
SpacepointMeasurement2 (const TVector3 &pos, const TVector3 &resolution)
SpacepointMeasurement2 (const TVector3 &pos, const TMatrixDSym &cov)
void init (const TVector3 &pos, const TMatrixDSym &cov)
~SpacepointMeasurement2 ()
dtor
Public Member Functions inherited from PHGenFit::Measurement
Measurement ()
ctor
~Measurement ()
dtor
genfit::AbsMeasurement * getMeasurement ()
unsigned int get_cluster_ID () const
void set_cluster_ID (unsigned int clusterId)
TrkrDefs::cluskey get_cluster_key () const
void set_cluster_key (TrkrDefs::cluskey clusterkey)
Additional Inherited Members
Protected Attributes inherited from PHGenFit::Measurement
genfit::AbsMeasurement * _measurement
unsigned int _clusterID
TrkrDefs::cluskey _clusterkey
Detailed Description
Definition at line 18 of file SpacepointMeasurement2.h.
View newest version in sPHENIX GitHub at line 18 of file SpacepointMeasurement2.h
Constructor & Destructor Documentation
PHGenFit::SpacepointMeasurement2::SpacepointMeasurement2 (const TVector3 & pos, const TVector3 & resolution)
Ctor
Parameters
pos measurement position
resolution standard dev for diagnal elements of the cov, other elements are zero
Definition at line 39 of file SpacepointMeasurement2.cc.
View newest version in sPHENIX GitHub at line 39 of file SpacepointMeasurement2.cc
References Acts::Test::cov, and init().
PHGenFit::SpacepointMeasurement2::SpacepointMeasurement2 (const TVector3 & pos, const TMatrixDSym & cov)
Ctor
Parameters
pos measurement position
covariance matrix
Definition at line 54 of file SpacepointMeasurement2.cc.
View newest version in sPHENIX GitHub at line 54 of file SpacepointMeasurement2.cc
References init().
PHGenFit::SpacepointMeasurement2::~SpacepointMeasurement2 ()
dtor
Definition at line 59 of file SpacepointMeasurement2.cc.
View newest version in sPHENIX GitHub at line 59 of file SpacepointMeasurement2.cc
Member Function Documentation
void PHGenFit::SpacepointMeasurement2::init (const TVector3 & pos, const TMatrixDSym & cov)
Definition at line 19 of file SpacepointMeasurement2.cc.
View newest version in sPHENIX GitHub at line 19 of file SpacepointMeasurement2.cc
References PHGenFit::Measurement::_measurement, Acts::Test::cov, i, and j.
Referenced by SpacepointMeasurement2().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/PHTpcTracker/SpacepointMeasurement2.h
coresoftware/blob/master/offline/packages/PHTpcTracker/SpacepointMeasurement2.cc