Analysis Software: PHMicromegasTpcTrackMatching Class Reference
PHMicromegasTpcTrackMatching Class Reference
#include <coresoftware/blob/master/offline/packages/trackreco/PHMicromegasTpcTrackMatching.h>
Public Member Functions
PHMicromegasTpcTrackMatching (const std::string &name="PHMicromegasTpcTrackMatching")
~PHMicromegasTpcTrackMatching () override=default
void set_rphi_search_window_lyr1 (const double win)
void set_z_search_window_lyr1 (const double win)
void set_rphi_search_window_lyr2 (const double win)
void set_z_search_window_lyr2 (const double win)
void set_min_tpc_layer (const unsigned int layer)
void set_test_windows_printout (const bool test)
void SetIteration (int iter)
int InitRun (PHCompositeNode *topNode) override
int process_event (PHCompositeNode *) override
int End (PHCompositeNode *) override
Called at the end of all processing.
void set_sc_calib_mode (const bool)
void set_collision_rate (const double)
Public Member Functions inherited from SubsysReco
~SubsysReco () override
virtual int EndRun (const int)
Called at the end of each run.
virtual int Init (PHCompositeNode *)
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
void Print (const std::string &="ALL") const override
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Private Member Functions
int GetNodes (PHCompositeNode *topNode)
load nodes relevant for the analysis
void copyMicromegasClustersToCorrectedMap ()
Acts::Vector3 getGlobalPosition (TrkrDefs::cluskey key, TrkrCluster *cluster, short int crossing, unsigned int side)
Private Attributes
bool _use_truth_clusters = false
TrkrClusterContainer * _cluster_map {nullptr}
TrkrClusterContainer * _corrected_cluster_map {nullptr}
TrackSeedContainer * _svtx_seed_map {nullptr}
TrackSeedContainer * _tpc_track_map {nullptr}
TrackSeedContainer * _si_track_map {nullptr}
std::array< double, _n_mm_layers > _rphi_search_win = {0.25, 13.0}
default rphi search window for each layer
std::array< double, _n_mm_layers > _z_search_win = {26.0, 0.25}
default z search window for each layer
unsigned int _min_tpc_layer = 38
unsigned int _min_mm_layer = 55
first micromegas layer
int _event = -1
internal event number
PHG4CylinderGeomContainer * _geomContainerMicromegas = nullptr
micomegas geometry
TrkrClusterIterationMapv1 * _iteration_map = nullptr
int _n_iteration = 0
ActsGeometry * _tGeometry = nullptr
TpcClusterZCrossingCorrection m_clusterCrossingCorrection
TpcDistortionCorrectionContainer * m_dcc_static = nullptr
TpcDistortionCorrectionContainer * m_dcc_average = nullptr
TpcDistortionCorrectionContainer * m_dcc_fluctuation = nullptr
TpcDistortionCorrection m_distortionCorrection
tpc distortion correction utility class
bool _test_windows = false
true to printout actual residuals for testing
Static Private Attributes
static constexpr unsigned int _n_mm_layers = 2
number of layers in the micromegas
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = std::numeric_limits<int>::max() - 10
}
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Detailed Description
Definition at line 27 of file PHMicromegasTpcTrackMatching.h.
View newest version in sPHENIX GitHub at line 27 of file PHMicromegasTpcTrackMatching.h
Constructor & Destructor Documentation
PHMicromegasTpcTrackMatching::PHMicromegasTpcTrackMatching (const std::string & name = "PHMicromegasTpcTrackMatching")
Definition at line 110 of file PHMicromegasTpcTrackMatching.cc.
View newest version in sPHENIX GitHub at line 110 of file PHMicromegasTpcTrackMatching.cc
PHMicromegasTpcTrackMatching::~PHMicromegasTpcTrackMatching () override default
Member Function Documentation
void PHMicromegasTpcTrackMatching::copyMicromegasClustersToCorrectedMap () private
int PHMicromegasTpcTrackMatching::End (PHCompositeNode *) override virtual
Called at the end of all processing.
Reimplemented from SubsysReco.
Definition at line 416 of file PHMicromegasTpcTrackMatching.cc.
View newest version in sPHENIX GitHub at line 416 of file PHMicromegasTpcTrackMatching.cc
References Fun4AllReturnCodes::EVENT_OK.
Acts::Vector3 PHMicromegasTpcTrackMatching::getGlobalPosition (TrkrDefs::cluskey key, TrkrCluster * cluster, short int crossing, unsigned int side) private
Definition at line 496 of file PHMicromegasTpcTrackMatching.cc.
View newest version in sPHENIX GitHub at line 496 of file PHMicromegasTpcTrackMatching.cc
References _tGeometry, TpcClusterZCrossingCorrection::correctZ(), TpcDistortionCorrection::get_corrected_position(), ActsGeometry::getGlobalPosition(), TrkrDefs::getTrkrId(), m_clusterCrossingCorrection, m_dcc_average, m_dcc_fluctuation, m_dcc_static, m_distortionCorrection, and TrkrDefs::tpcId.
Referenced by process_event().
int PHMicromegasTpcTrackMatching::GetNodes (PHCompositeNode * topNode) private
load nodes relevant for the analysis
Definition at line 420 of file PHMicromegasTpcTrackMatching.cc.
View newest version in sPHENIX GitHub at line 420 of file PHMicromegasTpcTrackMatching.cc
References _cluster_map, _geomContainerMicromegas, _si_track_map, _svtx_seed_map, _tGeometry, _tpc_track_map, _use_truth_clusters, Fun4AllReturnCodes::ABORTEVENT, Fun4AllReturnCodes::EVENT_OK, m_dcc_average, m_dcc_fluctuation, m_dcc_static, and PHWHERE.
Referenced by InitRun().
int PHMicromegasTpcTrackMatching::InitRun (PHCompositeNode *) override virtual
Called for first event when run number is known. Typically this is where you may want to fetch data from database, because you know the run number.
Reimplemented from SubsysReco.
Definition at line 115 of file PHMicromegasTpcTrackMatching.cc.
View newest version in sPHENIX GitHub at line 115 of file PHMicromegasTpcTrackMatching.cc
References _geomContainerMicromegas, _min_mm_layer, _n_mm_layers, _rphi_search_win, _z_search_win, Fun4AllReturnCodes::ABORTRUN, Fun4AllReturnCodes::EVENT_OK, PHG4CylinderGeomContainer::get_NLayers(), PHG4CylinderGeomContainer::GetFirstLayerGeom(), GetNodes(), and PHWHERE.
int PHMicromegasTpcTrackMatching::process_event (PHCompositeNode *) override virtual
Called for each event. This is where you do the real work.
Reimplemented from SubsysReco.
Definition at line 150 of file PHMicromegasTpcTrackMatching.cc.
View newest version in sPHENIX GitHub at line 150 of file PHMicromegasTpcTrackMatching.cc
References _cluster_map, _event, _geomContainerMicromegas, _iteration_map, _min_mm_layer, _min_tpc_layer, _n_iteration, _n_mm_layers, _rphi_search_win, _si_track_map, _svtx_seed_map, _test_windows, _tGeometry, _tpc_track_map, _z_search_win, A, Fun4AllReturnCodes::ABORTEVENT, TrackFitUtils::circle_circle_intersection(), TrackFitUtils::circle_fit_by_taubin(), clusters, dz, Fun4AllReturnCodes::EVENT_OK, TrkrClusterContainer::findCluster(), MicromegasDefs::genHitSetKey(), TrackSeedContainer::get(), TrackSeed::get_crossing(), QAG4Util::get_r(), CylinderGeomMicromegas::get_radius(), TrkrClusterContainer::getClusters(), ActsGeometry::getGlobalPosition(), getGlobalPosition(), TrkrClusterIterationMapv1::getIteration(), TrkrDefs::getLayer(), PHG4CylinderGeomContainer::GetLayerGeom(), TrkrCluster::getLocalX(), TrkrCluster::getLocalY(), TpcDefs::getSide(), layer, TrackFitUtils::line_fit(), ActsTests::PropagationDatasets::phi, PHWHERE, Acts::IntegrationTest::R, physmon_track_finding_ttbar::r, seed, TrackSeedContainer::size(), Fun4AllBase::Verbosity(), X0, Y0, and physmon_track_finding_ttbar::z.
void PHMicromegasTpcTrackMatching::set_collision_rate (const double) inline
Definition at line 48 of file PHMicromegasTpcTrackMatching.h.
View newest version in sPHENIX GitHub at line 48 of file PHMicromegasTpcTrackMatching.h
void PHMicromegasTpcTrackMatching::set_min_tpc_layer (const unsigned int layer) inline
Definition at line 38 of file PHMicromegasTpcTrackMatching.h.
View newest version in sPHENIX GitHub at line 38 of file PHMicromegasTpcTrackMatching.h
References _min_tpc_layer, and layer.
void PHMicromegasTpcTrackMatching::set_rphi_search_window_lyr1 (const double win) inline
Definition at line 34 of file PHMicromegasTpcTrackMatching.h.
View newest version in sPHENIX GitHub at line 34 of file PHMicromegasTpcTrackMatching.h
References _rphi_search_win.
void PHMicromegasTpcTrackMatching::set_rphi_search_window_lyr2 (const double win) inline
Definition at line 36 of file PHMicromegasTpcTrackMatching.h.
View newest version in sPHENIX GitHub at line 36 of file PHMicromegasTpcTrackMatching.h
References _rphi_search_win.
void PHMicromegasTpcTrackMatching::set_sc_calib_mode (const bool) inline
Definition at line 47 of file PHMicromegasTpcTrackMatching.h.
View newest version in sPHENIX GitHub at line 47 of file PHMicromegasTpcTrackMatching.h
void PHMicromegasTpcTrackMatching::set_test_windows_printout (const bool test) inline
Definition at line 39 of file PHMicromegasTpcTrackMatching.h.
View newest version in sPHENIX GitHub at line 39 of file PHMicromegasTpcTrackMatching.h
References _test_windows, and train_ambiguity_solver::test.
void PHMicromegasTpcTrackMatching::set_z_search_window_lyr1 (const double win) inline
Definition at line 35 of file PHMicromegasTpcTrackMatching.h.
View newest version in sPHENIX GitHub at line 35 of file PHMicromegasTpcTrackMatching.h
References _z_search_win.
void PHMicromegasTpcTrackMatching::set_z_search_window_lyr2 (const double win) inline
Definition at line 37 of file PHMicromegasTpcTrackMatching.h.
View newest version in sPHENIX GitHub at line 37 of file PHMicromegasTpcTrackMatching.h
References _z_search_win.
void PHMicromegasTpcTrackMatching::SetIteration (int iter) inline
Definition at line 40 of file PHMicromegasTpcTrackMatching.h.
View newest version in sPHENIX GitHub at line 40 of file PHMicromegasTpcTrackMatching.h
References _n_iteration.
Member Data Documentation
TrkrClusterContainer* PHMicromegasTpcTrackMatching::_cluster_map {nullptr} private
Definition at line 62 of file PHMicromegasTpcTrackMatching.h.
View newest version in sPHENIX GitHub at line 62 of file PHMicromegasTpcTrackMatching.h
Referenced by GetNodes(), and process_event().
TrkrClusterContainer* PHMicromegasTpcTrackMatching::_corrected_cluster_map {nullptr} private
Definition at line 63 of file PHMicromegasTpcTrackMatching.h.
View newest version in sPHENIX GitHub at line 63 of file PHMicromegasTpcTrackMatching.h
int PHMicromegasTpcTrackMatching::_event = -1 private
internal event number
Definition at line 83 of file PHMicromegasTpcTrackMatching.h.
View newest version in sPHENIX GitHub at line 83 of file PHMicromegasTpcTrackMatching.h
Referenced by process_event().
PHG4CylinderGeomContainer* PHMicromegasTpcTrackMatching::_geomContainerMicromegas = nullptr private
micomegas geometry
Definition at line 86 of file PHMicromegasTpcTrackMatching.h.
View newest version in sPHENIX GitHub at line 86 of file PHMicromegasTpcTrackMatching.h
Referenced by GetNodes(), InitRun(), and process_event().
TrkrClusterIterationMapv1* PHMicromegasTpcTrackMatching::_iteration_map = nullptr private
Definition at line 87 of file PHMicromegasTpcTrackMatching.h.
View newest version in sPHENIX GitHub at line 87 of file PHMicromegasTpcTrackMatching.h
Referenced by process_event().
unsigned int PHMicromegasTpcTrackMatching::_min_mm_layer = 55 private
first micromegas layer
it is reset in ::Setup using actual micromegas geometry
Definition at line 80 of file PHMicromegasTpcTrackMatching.h.
View newest version in sPHENIX GitHub at line 80 of file PHMicromegasTpcTrackMatching.h
Referenced by InitRun(), and process_event().
unsigned int PHMicromegasTpcTrackMatching::_min_tpc_layer = 38 private
Definition at line 76 of file PHMicromegasTpcTrackMatching.h.
View newest version in sPHENIX GitHub at line 76 of file PHMicromegasTpcTrackMatching.h
Referenced by process_event(), and set_min_tpc_layer().
int PHMicromegasTpcTrackMatching::_n_iteration = 0 private
Definition at line 88 of file PHMicromegasTpcTrackMatching.h.
View newest version in sPHENIX GitHub at line 88 of file PHMicromegasTpcTrackMatching.h
Referenced by process_event(), and SetIteration().
constexpr unsigned int PHMicromegasTpcTrackMatching::_n_mm_layers = 2 static private
number of layers in the micromegas
Definition at line 59 of file PHMicromegasTpcTrackMatching.h.
View newest version in sPHENIX GitHub at line 59 of file PHMicromegasTpcTrackMatching.h
Referenced by InitRun(), and process_event().
std::array<double,_n_mm_layers> PHMicromegasTpcTrackMatching::_rphi_search_win = {0.25, 13.0} private
default rphi search window for each layer
Definition at line 70 of file PHMicromegasTpcTrackMatching.h.
View newest version in sPHENIX GitHub at line 70 of file PHMicromegasTpcTrackMatching.h
Referenced by InitRun(), process_event(), set_rphi_search_window_lyr1(), and set_rphi_search_window_lyr2().
TrackSeedContainer* PHMicromegasTpcTrackMatching::_si_track_map {nullptr} private
Definition at line 67 of file PHMicromegasTpcTrackMatching.h.
View newest version in sPHENIX GitHub at line 67 of file PHMicromegasTpcTrackMatching.h
Referenced by GetNodes(), and process_event().
TrackSeedContainer* PHMicromegasTpcTrackMatching::_svtx_seed_map {nullptr} private
Definition at line 65 of file PHMicromegasTpcTrackMatching.h.
View newest version in sPHENIX GitHub at line 65 of file PHMicromegasTpcTrackMatching.h
Referenced by GetNodes(), and process_event().
bool PHMicromegasTpcTrackMatching::_test_windows = false private
true to printout actual residuals for testing
Definition at line 105 of file PHMicromegasTpcTrackMatching.h.
View newest version in sPHENIX GitHub at line 105 of file PHMicromegasTpcTrackMatching.h
Referenced by process_event(), and set_test_windows_printout().
ActsGeometry* PHMicromegasTpcTrackMatching::_tGeometry = nullptr private
Definition at line 91 of file PHMicromegasTpcTrackMatching.h.
View newest version in sPHENIX GitHub at line 91 of file PHMicromegasTpcTrackMatching.h
Referenced by getGlobalPosition(), GetNodes(), and process_event().
TrackSeedContainer* PHMicromegasTpcTrackMatching::_tpc_track_map {nullptr} private
Definition at line 66 of file PHMicromegasTpcTrackMatching.h.
View newest version in sPHENIX GitHub at line 66 of file PHMicromegasTpcTrackMatching.h
Referenced by GetNodes(), and process_event().
bool PHMicromegasTpcTrackMatching::_use_truth_clusters = false private
Definition at line 61 of file PHMicromegasTpcTrackMatching.h.
View newest version in sPHENIX GitHub at line 61 of file PHMicromegasTpcTrackMatching.h
Referenced by GetNodes().
std::array<double,_n_mm_layers> PHMicromegasTpcTrackMatching::_z_search_win = {26.0, 0.25} private
default z search window for each layer
Definition at line 73 of file PHMicromegasTpcTrackMatching.h.
View newest version in sPHENIX GitHub at line 73 of file PHMicromegasTpcTrackMatching.h
Referenced by InitRun(), process_event(), set_z_search_window_lyr1(), and set_z_search_window_lyr2().
TpcClusterZCrossingCorrection PHMicromegasTpcTrackMatching::m_clusterCrossingCorrection private
Definition at line 94 of file PHMicromegasTpcTrackMatching.h.
View newest version in sPHENIX GitHub at line 94 of file PHMicromegasTpcTrackMatching.h
Referenced by getGlobalPosition().
TpcDistortionCorrectionContainer* PHMicromegasTpcTrackMatching::m_dcc_average = nullptr private
Definition at line 98 of file PHMicromegasTpcTrackMatching.h.
View newest version in sPHENIX GitHub at line 98 of file PHMicromegasTpcTrackMatching.h
Referenced by getGlobalPosition(), and GetNodes().
TpcDistortionCorrectionContainer* PHMicromegasTpcTrackMatching::m_dcc_fluctuation = nullptr private
Definition at line 99 of file PHMicromegasTpcTrackMatching.h.
View newest version in sPHENIX GitHub at line 99 of file PHMicromegasTpcTrackMatching.h
Referenced by getGlobalPosition(), and GetNodes().
TpcDistortionCorrectionContainer* PHMicromegasTpcTrackMatching::m_dcc_static = nullptr private
Definition at line 97 of file PHMicromegasTpcTrackMatching.h.
View newest version in sPHENIX GitHub at line 97 of file PHMicromegasTpcTrackMatching.h
Referenced by getGlobalPosition(), and GetNodes().
TpcDistortionCorrection PHMicromegasTpcTrackMatching::m_distortionCorrection private
tpc distortion correction utility class
Definition at line 102 of file PHMicromegasTpcTrackMatching.h.
View newest version in sPHENIX GitHub at line 102 of file PHMicromegasTpcTrackMatching.h
Referenced by getGlobalPosition().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/trackreco/PHMicromegasTpcTrackMatching.h
coresoftware/blob/master/offline/packages/trackreco/PHMicromegasTpcTrackMatching.cc