Analysis Software: macros/blob/master/calibrations/calo/tower_slope_macro/emc_corr_files/make_EmcCorr.C File Reference
make_EmcCorr.C File Reference
Functions
TTree t1 ("emc_corr_tree","")
t1 Branch ("corr",&corr,"corr/F")
t1 Branch ("towid",&towid,"towid/I")
for (Int_t i=0;i< 96;i++)
f Write ()
Variables
Int_t towid
Float_t corr
Function Documentation
t1 Branch ("corr" , & corr, "corr/F")
Referenced by mbdAnalysis::Init(), hijbkg_upc::Init(), isoCluster::Init(), pi0ClusterAna::Init(), quickHIJING::Init(), singlePhotonClusterAna::Init(), caloTreeGen::Init(), pythiaEMCalAna::Init(), hcal_towerid::Init(), SColdQcdCorrelatorAnalysis::SLambdaJetHunter::InitTree(), SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::InitTrees(), LEDTowerBuilder::LEDTowerBuilder(), simulateTimestamps(), tileTree::tileTree(), and towerid::WriteCDBTree().
t1 Branch ("towid" , & towid, "towid/I")
for ()
Definition at line 11 of file make_EmcCorr.C.
View newest version in sPHENIX GitHub at line 11 of file make_EmcCorr.C
References i, j, k, and ambiguity_solver_full_chain::t1.
TTree t1 ("emc_corr_tree" , "")
Referenced by getmd(), getproba(), pygfxx(), pymirm(), and pywidt().
f Write ()
Variable Documentation
Float_t corr
Definition at line 7 of file make_EmcCorr.C.
View newest version in sPHENIX GitHub at line 7 of file make_EmcCorr.C
Referenced by GPUTPCTrackParam::CorrectForMeanMaterial(), drawCorr(), LiteCaloEval::FitRelativeShifts(), Acts::Test::generateParametersCovariance(), log_gamma_function(), makeParametersCurvilinearWithCovariance(), plot_checks(), pymirm(), and Svtx_Reco().
Int_t towid
Definition at line 6 of file make_EmcCorr.C.
View newest version in sPHENIX GitHub at line 6 of file make_EmcCorr.C
Referenced by LiteCaloEval::FitRelativeShifts().