Analysis Software: MessageSystem Class Reference
MessageSystem Class Reference
#include <OnlMon/blob/main/onlmonserver/MessageSystem.h>
Public Member Functions
MessageSystem (const std::string &name)
~MessageSystem () override
MessageSystem (const MessageSystem &)=delete
MessageSystem & operator= (const MessageSystem &)=delete
int send_message (const int msg_source, const int severity, const std::string &err_message, const int msgtype)
int Reset ()
Public Member Functions inherited from OnlMonBase
OnlMonBase (const std::string &name="NONE")
virtual ~OnlMonBase ()
const std::string Name () const
void Name (const std::string &name)
virtual void Verbosity (const int i)
virtual int Verbosity () const
Protected Attributes
msg_control * Message
std::map< int, std::pair< int,
int > > msgcounter
Protected Attributes inherited from OnlMonBase
std::string ThisName
int verbosity = 0
Detailed Description
Definition at line 12 of file MessageSystem.h.
View newest version in sPHENIX GitHub at line 12 of file MessageSystem.h
Constructor & Destructor Documentation
MessageSystem::MessageSystem (const std::string & name)
Definition at line 11 of file MessageSystem.cc.
View newest version in sPHENIX GitHub at line 11 of file MessageSystem.cc
References Message, MSG_SEV_DEFAULT, MSG_SOURCE_DEFAULT, and MSG_TYPE_MONITORING.
MessageSystem::~MessageSystem () override
Definition at line 18 of file MessageSystem.cc.
View newest version in sPHENIX GitHub at line 18 of file MessageSystem.cc
References Message, and msgcounter.
MessageSystem::MessageSystem (const MessageSystem &) explicit delete
Member Function Documentation
MessageSystem& MessageSystem::operator= (const MessageSystem &) delete
int MessageSystem::Reset ()
Definition at line 66 of file MessageSystem.cc.
View newest version in sPHENIX GitHub at line 66 of file MessageSystem.cc
References msgcounter.
int MessageSystem::send_message (const int msg_source, const int severity, const std::string & err_message, const int msgtype)
Definition at line 25 of file MessageSystem.cc.
View newest version in sPHENIX GitHub at line 25 of file MessageSystem.cc
References OnlMonServer::instance(), Message, MSG_SEV_INFORMATIONAL, msgcounter, msg_control::set_severity(), msg_control::set_source(), OnlMonBase::ThisName, and OnlMonServer::WriteLogFile().
Member Data Documentation
msg_control* MessageSystem::Message protected
Definition at line 27 of file MessageSystem.h.
View newest version in sPHENIX GitHub at line 27 of file MessageSystem.h
Referenced by MessageSystem(), send_message(), and ~MessageSystem().
std::map<int, std::pair<int, int> > MessageSystem::msgcounter protected
Definition at line 28 of file MessageSystem.h.
View newest version in sPHENIX GitHub at line 28 of file MessageSystem.h
Referenced by Reset(), send_message(), and ~MessageSystem().
The documentation for this class was generated from the following files:
OnlMon/blob/main/onlmonserver/MessageSystem.h
OnlMon/blob/main/onlmonserver/MessageSystem.cc