Analysis Software: cl::NDRange Class Reference
cl::NDRange Class Reference
NDRange interface.
#include <JETSCAPE/blob/main/external_packages/clvisc_wrapper/include/cl.hpp>
Public Member Functions
NDRange ()
NDRange (::size_t size0)
NDRange (::size_t size0,::size_t size1)
NDRange (::size_t size0,::size_t size1,::size_t size2)
operator const ::size_t * () const
::size_t dimensions () const
Private Attributes
size_t< 3 > sizes_
cl_uint dimensions_
Detailed Description
NDRange interface.
Definition at line 2211 of file cl.hpp.
View newest version in sPHENIX GitHub at line 2211 of file cl.hpp
Constructor & Destructor Documentation
cl::NDRange::NDRange () inline
Definition at line 2218 of file cl.hpp.
View newest version in sPHENIX GitHub at line 2218 of file cl.hpp
cl::NDRange::NDRange (::size_t size0) inline
Definition at line 2222 of file cl.hpp.
View newest version in sPHENIX GitHub at line 2222 of file cl.hpp
References cl::vector< T, N >::push_back().
cl::NDRange::NDRange (::size_t size0, ::size_t size1) inline
Definition at line 2228 of file cl.hpp.
View newest version in sPHENIX GitHub at line 2228 of file cl.hpp
References cl::vector< T, N >::push_back().
cl::NDRange::NDRange (::size_t size0, ::size_t size1, ::size_t size2) inline
Definition at line 2235 of file cl.hpp.
View newest version in sPHENIX GitHub at line 2235 of file cl.hpp
References cl::vector< T, N >::push_back().
Member Function Documentation
::size_t cl::NDRange::dimensions () const inline
Definition at line 2244 of file cl.hpp.
View newest version in sPHENIX GitHub at line 2244 of file cl.hpp
Referenced by cl::CommandQueue::enqueueNDRangeKernel().
cl::NDRange::operator const ::size_t * () const inline
Definition at line 2243 of file cl.hpp.
View newest version in sPHENIX GitHub at line 2243 of file cl.hpp
Member Data Documentation
cl_uint cl::NDRange::dimensions_ private
Definition at line 2215 of file cl.hpp.
View newest version in sPHENIX GitHub at line 2215 of file cl.hpp
size_t<3> cl::NDRange::sizes_ private
Definition at line 2214 of file cl.hpp.
View newest version in sPHENIX GitHub at line 2214 of file cl.hpp
The documentation for this class was generated from the following file:
JETSCAPE/blob/main/external_packages/clvisc_wrapper/include/cl.hpp