Analysis Software: PIDplots Class Reference
PIDplots Class Reference
#include <analysis/blob/master/ElectronID/anaplots/PIDplots.h>
Public Member Functions
void inputpars ()
void fhistogram_eID ()
void eID ()
void eIDoutput ()
void inputpars ()
void fhistogram_eID ()
void eID ()
void eIDoutput ()
Private Attributes
int Nfile
int Nevent
int Nmpnbin
int tag
float me
float mep
float men
float pi
float rYs [3]
const char * input_file [400]
char input_file_embed [400]
const char * output_eID
const char * output_plot_eID
const char * output_plot_eID_eta
const char * output_plot_eID_pt
const char * output_plot_eID_HOM
const char * output_plot_eID_HOP
const char * output_plot_eID_EOP
TFile * fHistogramFile_eID
TH1F * h1pt_e
TH1F * h1EOP
TH1F * h1EOP_e
TH1F * h1HOM
TH1F * h1HOP
TH1F * h1dR
TH1F * h1gflavor
int NEID_electron
int NEID_electron_eta [50]
int NEID_electron_pt [50]
int NEID_electron_HOP [50]
int NEID_electron_HOM [50]
int NEID_electron_EOP [50]
int N_electron_eta [50]
int N_electron_pt [50]
int N_electron_HOM [50]
int N_electron_HOP [50]
int N_electron_EOP [50]
int N_pion_eta [50]
int N_K_eta [50]
int N_antiproton_eta [50]
int N_pion_pt [50]
int N_K_pt [50]
int N_antiproton_pt [50]
int N_pion_HOM [50]
int N_K_HOM [50]
int N_antiproton_HOM [50]
int N_pion_HOP [50]
int N_K_HOP [50]
int N_antiproton_HOP [50]
int N_pion_EOP [50]
int N_K_EOP [50]
int N_antiproton_EOP [50]
int NEID_pion_eta [50]
int NEID_K_eta [50]
int NEID_antiproton_eta [50]
int NEID_pion_pt [50]
int NEID_K_pt [50]
int NEID_antiproton_pt [50]
int NEID_pion
int NEID_K
int NEID_antiproton
float eta_point [50]
float pt_point [50]
float HOM_point [50]
float HOP_point [50]
float EOP_point [50]
Detailed Description
Definition at line 78 of file PIDplots.h.
View newest version in sPHENIX GitHub at line 78 of file PIDplots.h
Member Function Documentation
void PIDplots::eID ()
Definition at line 150 of file PIDplots.cc.
View newest version in sPHENIX GitHub at line 150 of file PIDplots.cc
References dR(), file2, i, perf_headwind::input_file, ntp_gtrack(), printf(), and physmon_track_finding_ttbar::pt.
Referenced by main().
void PIDplots::eID ()
void PIDplots::eIDoutput ()
Definition at line 392 of file PIDplots.cc.
View newest version in sPHENIX GitHub at line 392 of file PIDplots.cc
References generate_files_AA::ff, fprintf(), g4, i, and SetsPhenixStyle().
void PIDplots::eIDoutput ()
void PIDplots::fhistogram_eID ()
Definition at line 137 of file PIDplots.cc.
View newest version in sPHENIX GitHub at line 137 of file PIDplots.cc
void PIDplots::fhistogram_eID ()
void PIDplots::inputpars ()
Definition at line 41 of file PIDplots.cc.
View newest version in sPHENIX GitHub at line 41 of file PIDplots.cc
References perf_headwind::input_file, Nevent, and pi.
Referenced by main().
void PIDplots::inputpars ()
Member Data Documentation
float PIDplots::EOP_point private
Definition at line 160 of file PIDplots.h.
View newest version in sPHENIX GitHub at line 160 of file PIDplots.h
float PIDplots::eta_point private
Definition at line 156 of file PIDplots.h.
View newest version in sPHENIX GitHub at line 156 of file PIDplots.h
TFile * PIDplots::fHistogramFile_eID private
Definition at line 105 of file PIDplots.h.
View newest version in sPHENIX GitHub at line 105 of file PIDplots.h
TH1F * PIDplots::h1dR private
Definition at line 111 of file PIDplots.h.
View newest version in sPHENIX GitHub at line 111 of file PIDplots.h
TH1F * PIDplots::h1EOP private
Definition at line 107 of file PIDplots.h.
View newest version in sPHENIX GitHub at line 107 of file PIDplots.h
TH1F * PIDplots::h1EOP_e private
Definition at line 108 of file PIDplots.h.
View newest version in sPHENIX GitHub at line 108 of file PIDplots.h
TH1F * PIDplots::h1gflavor private
Definition at line 112 of file PIDplots.h.
View newest version in sPHENIX GitHub at line 112 of file PIDplots.h
TH1F * PIDplots::h1HOM private
Definition at line 109 of file PIDplots.h.
View newest version in sPHENIX GitHub at line 109 of file PIDplots.h
TH1F * PIDplots::h1HOP private
Definition at line 110 of file PIDplots.h.
View newest version in sPHENIX GitHub at line 110 of file PIDplots.h
TH1F * PIDplots::h1pt_e private
Definition at line 106 of file PIDplots.h.
View newest version in sPHENIX GitHub at line 106 of file PIDplots.h
float PIDplots::HOM_point private
Definition at line 158 of file PIDplots.h.
View newest version in sPHENIX GitHub at line 158 of file PIDplots.h
float PIDplots::HOP_point private
Definition at line 159 of file PIDplots.h.
View newest version in sPHENIX GitHub at line 159 of file PIDplots.h
const char * PIDplots::input_file private
Definition at line 93 of file PIDplots.h.
View newest version in sPHENIX GitHub at line 93 of file PIDplots.h
char PIDplots::input_file_embed private
Definition at line 94 of file PIDplots.h.
View newest version in sPHENIX GitHub at line 94 of file PIDplots.h
float PIDplots::me private
Definition at line 87 of file PIDplots.h.
View newest version in sPHENIX GitHub at line 87 of file PIDplots.h
float PIDplots::men private
Definition at line 89 of file PIDplots.h.
View newest version in sPHENIX GitHub at line 89 of file PIDplots.h
float PIDplots::mep private
Definition at line 88 of file PIDplots.h.
View newest version in sPHENIX GitHub at line 88 of file PIDplots.h
int PIDplots::N_antiproton_EOP private
Definition at line 143 of file PIDplots.h.
View newest version in sPHENIX GitHub at line 143 of file PIDplots.h
int PIDplots::N_antiproton_eta private
Definition at line 131 of file PIDplots.h.
View newest version in sPHENIX GitHub at line 131 of file PIDplots.h
int PIDplots::N_antiproton_HOM private
Definition at line 137 of file PIDplots.h.
View newest version in sPHENIX GitHub at line 137 of file PIDplots.h
int PIDplots::N_antiproton_HOP private
Definition at line 140 of file PIDplots.h.
View newest version in sPHENIX GitHub at line 140 of file PIDplots.h
int PIDplots::N_antiproton_pt private
Definition at line 134 of file PIDplots.h.
View newest version in sPHENIX GitHub at line 134 of file PIDplots.h
int PIDplots::N_electron_EOP private
Definition at line 127 of file PIDplots.h.
View newest version in sPHENIX GitHub at line 127 of file PIDplots.h
int PIDplots::N_electron_eta private
Definition at line 123 of file PIDplots.h.
View newest version in sPHENIX GitHub at line 123 of file PIDplots.h
int PIDplots::N_electron_HOM private
Definition at line 125 of file PIDplots.h.
View newest version in sPHENIX GitHub at line 125 of file PIDplots.h
int PIDplots::N_electron_HOP private
Definition at line 126 of file PIDplots.h.
View newest version in sPHENIX GitHub at line 126 of file PIDplots.h
int PIDplots::N_electron_pt private
Definition at line 124 of file PIDplots.h.
View newest version in sPHENIX GitHub at line 124 of file PIDplots.h
int PIDplots::N_K_EOP private
Definition at line 142 of file PIDplots.h.
View newest version in sPHENIX GitHub at line 142 of file PIDplots.h
int PIDplots::N_K_eta private
Definition at line 130 of file PIDplots.h.
View newest version in sPHENIX GitHub at line 130 of file PIDplots.h
int PIDplots::N_K_HOM private
Definition at line 136 of file PIDplots.h.
View newest version in sPHENIX GitHub at line 136 of file PIDplots.h
int PIDplots::N_K_HOP private
Definition at line 139 of file PIDplots.h.
View newest version in sPHENIX GitHub at line 139 of file PIDplots.h
int PIDplots::N_K_pt private
Definition at line 133 of file PIDplots.h.
View newest version in sPHENIX GitHub at line 133 of file PIDplots.h
int PIDplots::N_pion_EOP private
Definition at line 141 of file PIDplots.h.
View newest version in sPHENIX GitHub at line 141 of file PIDplots.h
int PIDplots::N_pion_eta private
Definition at line 129 of file PIDplots.h.
View newest version in sPHENIX GitHub at line 129 of file PIDplots.h
int PIDplots::N_pion_HOM private
Definition at line 135 of file PIDplots.h.
View newest version in sPHENIX GitHub at line 135 of file PIDplots.h
int PIDplots::N_pion_HOP private
Definition at line 138 of file PIDplots.h.
View newest version in sPHENIX GitHub at line 138 of file PIDplots.h
int PIDplots::N_pion_pt private
Definition at line 132 of file PIDplots.h.
View newest version in sPHENIX GitHub at line 132 of file PIDplots.h
int PIDplots::NEID_antiproton private
Definition at line 155 of file PIDplots.h.
View newest version in sPHENIX GitHub at line 155 of file PIDplots.h
int PIDplots::NEID_antiproton_eta private
Definition at line 147 of file PIDplots.h.
View newest version in sPHENIX GitHub at line 147 of file PIDplots.h
int PIDplots::NEID_antiproton_pt private
Definition at line 150 of file PIDplots.h.
View newest version in sPHENIX GitHub at line 150 of file PIDplots.h
int PIDplots::NEID_electron private
Definition at line 114 of file PIDplots.h.
View newest version in sPHENIX GitHub at line 114 of file PIDplots.h
int PIDplots::NEID_electron_EOP private
Definition at line 120 of file PIDplots.h.
View newest version in sPHENIX GitHub at line 120 of file PIDplots.h
int PIDplots::NEID_electron_eta private
Definition at line 116 of file PIDplots.h.
View newest version in sPHENIX GitHub at line 116 of file PIDplots.h
int PIDplots::NEID_electron_HOM private
Definition at line 119 of file PIDplots.h.
View newest version in sPHENIX GitHub at line 119 of file PIDplots.h
int PIDplots::NEID_electron_HOP private
Definition at line 118 of file PIDplots.h.
View newest version in sPHENIX GitHub at line 118 of file PIDplots.h
int PIDplots::NEID_electron_pt private
Definition at line 117 of file PIDplots.h.
View newest version in sPHENIX GitHub at line 117 of file PIDplots.h
int PIDplots::NEID_K private
Definition at line 154 of file PIDplots.h.
View newest version in sPHENIX GitHub at line 154 of file PIDplots.h
int PIDplots::NEID_K_eta private
Definition at line 146 of file PIDplots.h.
View newest version in sPHENIX GitHub at line 146 of file PIDplots.h
int PIDplots::NEID_K_pt private
Definition at line 149 of file PIDplots.h.
View newest version in sPHENIX GitHub at line 149 of file PIDplots.h
int PIDplots::NEID_pion private
Definition at line 153 of file PIDplots.h.
View newest version in sPHENIX GitHub at line 153 of file PIDplots.h
int PIDplots::NEID_pion_eta private
Definition at line 145 of file PIDplots.h.
View newest version in sPHENIX GitHub at line 145 of file PIDplots.h
int PIDplots::NEID_pion_pt private
Definition at line 148 of file PIDplots.h.
View newest version in sPHENIX GitHub at line 148 of file PIDplots.h
int PIDplots::Nevent private
Definition at line 83 of file PIDplots.h.
View newest version in sPHENIX GitHub at line 83 of file PIDplots.h
int PIDplots::Nfile private
Definition at line 82 of file PIDplots.h.
View newest version in sPHENIX GitHub at line 82 of file PIDplots.h
int PIDplots::Nmpnbin private
Definition at line 84 of file PIDplots.h.
View newest version in sPHENIX GitHub at line 84 of file PIDplots.h
const char * PIDplots::output_eID private
Definition at line 96 of file PIDplots.h.
View newest version in sPHENIX GitHub at line 96 of file PIDplots.h
const char * PIDplots::output_plot_eID private
Definition at line 97 of file PIDplots.h.
View newest version in sPHENIX GitHub at line 97 of file PIDplots.h
const char * PIDplots::output_plot_eID_EOP private
Definition at line 102 of file PIDplots.h.
View newest version in sPHENIX GitHub at line 102 of file PIDplots.h
const char * PIDplots::output_plot_eID_eta private
Definition at line 98 of file PIDplots.h.
View newest version in sPHENIX GitHub at line 98 of file PIDplots.h
const char * PIDplots::output_plot_eID_HOM private
Definition at line 100 of file PIDplots.h.
View newest version in sPHENIX GitHub at line 100 of file PIDplots.h
const char * PIDplots::output_plot_eID_HOP private
Definition at line 101 of file PIDplots.h.
View newest version in sPHENIX GitHub at line 101 of file PIDplots.h
const char * PIDplots::output_plot_eID_pt private
Definition at line 99 of file PIDplots.h.
View newest version in sPHENIX GitHub at line 99 of file PIDplots.h
float PIDplots::pi private
Definition at line 90 of file PIDplots.h.
View newest version in sPHENIX GitHub at line 90 of file PIDplots.h
float PIDplots::pt_point private
Definition at line 157 of file PIDplots.h.
View newest version in sPHENIX GitHub at line 157 of file PIDplots.h
float PIDplots::rYs private
Definition at line 91 of file PIDplots.h.
View newest version in sPHENIX GitHub at line 91 of file PIDplots.h
int PIDplots::tag private
Definition at line 85 of file PIDplots.h.
View newest version in sPHENIX GitHub at line 85 of file PIDplots.h
The documentation for this class was generated from the following files:
analysis/blob/master/ElectronID/anaplots/PIDplots.h
analysis/blob/master/TrackPid/anaplots/PIDplots.h
analysis/blob/master/ElectronID/anaplots/PIDplots.cc
analysis/blob/master/TrackPid/anaplots/PIDplots.cc