Analysis Software: analysis/blob/master/HCalCosmicCalib/offline/fit_channel_hist.C File Reference
fit_channel_hist.C File Reference
#include <TH1.h>
#include <TStyle.h>
#include <TCanvas.h>
#include <TMath.h>
#include <TF1.h>
#include "TROOT.h"
#include <iostream>
#include <string>
#include <fstream>
#include <TAxis.h>
#include <TGraph.h>
#include <TSpectrum.h>
Functions
double gamma_function (double *x, double *par)
float get_temp_shift (TH1F *hist, float y)
float get_temp_scale (TH1F *hist, float x)
float get_temp_N (float x, float y, float shift, float scale)
float get_fit_min (TH1F *hist, float y)
float get_fit_max (TH1F *hist, float y)
void do_peak_finder (TH1F *hist, float &x, float &y, float &shift, float &scale, float &N, float &min, float &max)
void do_peak_fit (TH1F *hist, TF1 *func)
void fit_channel_hist ()
Function Documentation
void do_peak_finder (TH1F * hist, float & x, float & y, float & shift, float & scale, float & N, float & min, float & max)
Definition at line 78 of file fit_channel_hist.C.
View newest version in sPHENIX GitHub at line 78 of file fit_channel_hist.C
References get_fit_max(), get_fit_min(), get_temp_N(), get_temp_scale(), get_temp_shift(), index, and physmon_simulation::s.
Referenced by do_peak_fit().
void do_peak_fit (TH1F * hist, TF1 * func)
Definition at line 103 of file fit_channel_hist.C.
View newest version in sPHENIX GitHub at line 103 of file fit_channel_hist.C
References do_peak_finder().
Referenced by fit_channel_hist().
void fit_channel_hist ()
Definition at line 113 of file fit_channel_hist.C.
View newest version in sPHENIX GitHub at line 113 of file fit_channel_hist.C
References do_peak_fit(), and gamma_function().
double gamma_function (double * x, double * par)
Definition at line 14 of file fit_channel_hist.C.
View newest version in sPHENIX GitHub at line 14 of file fit_channel_hist.C
References N.
Referenced by fit_channel_hist().
float get_fit_max (TH1F * hist, float y)
Definition at line 67 of file fit_channel_hist.C.
View newest version in sPHENIX GitHub at line 67 of file fit_channel_hist.C
References i.
Referenced by do_peak_finder().
float get_fit_min (TH1F * hist, float y)
Definition at line 53 of file fit_channel_hist.C.
View newest version in sPHENIX GitHub at line 53 of file fit_channel_hist.C
References i, and Acts::UnitConstants::min.
Referenced by do_peak_finder().
float get_temp_N (float x, float y, float shift, float scale)
Definition at line 45 of file fit_channel_hist.C.
View newest version in sPHENIX GitHub at line 45 of file fit_channel_hist.C
References y.
Referenced by do_peak_finder().
float get_temp_scale (TH1F * hist, float x)
Definition at line 40 of file fit_channel_hist.C.
View newest version in sPHENIX GitHub at line 40 of file fit_channel_hist.C
References ambiguity_solver_full_chain::x.
Referenced by do_peak_finder().
float get_temp_shift (TH1F * hist, float y)
Definition at line 29 of file fit_channel_hist.C.
View newest version in sPHENIX GitHub at line 29 of file fit_channel_hist.C
References i.
Referenced by do_peak_finder().