Analysis Software: TrackInfoContainer_v1 Class Reference
TrackInfoContainer_v1 Class Reference
#include <coresoftware/blob/master/offline/packages/trackbase_historic/TrackInfoContainer_v1.h>
Public Member Functions
TrackInfoContainer_v1 ()
~TrackInfoContainer_v1 () override
void identify (std::ostream &os=std::cout) const override
void Reset () override
Clear Event.
size_t size () const override
SvtxTrackInfo * get_trackinfo (int pos) override
void add_trackinfo (int pos, SvtxTrackInfo trackinfo) override
void add_trackinfo (int pos, SvtxTrackInfo *trackinfo) override
Public Member Functions inherited from TrackInfoContainer
TrackInfoContainer ()=default
~TrackInfoContainer () override=default
Public Member Functions inherited from PHObject
PHObject ()
ctor
~PHObject () override
dtor
virtual PHObject * CloneMe () const
Virtual copy constructor.
virtual PHObject * clone () const final
PHObject * Clone (const char *newname="") const final
void Copy (TObject &object) const final
virtual int isValid () const
isValid returns non zero if object contains vailid data
virtual int Integrate () const
virtual int Integrate (PHObject *)
virtual void CopyFrom (const PHObject *obj)
Protected Attributes
TClonesArray * _clones = nullptr
Private Member Functions
ClassDefOverride (TrackInfoContainer_v1, 1)
Detailed Description
Definition at line 14 of file TrackInfoContainer_v1.h.
View newest version in sPHENIX GitHub at line 14 of file TrackInfoContainer_v1.h
Constructor & Destructor Documentation
TrackInfoContainer_v1::TrackInfoContainer_v1 ()
Definition at line 10 of file TrackInfoContainer_v1.cc.
View newest version in sPHENIX GitHub at line 10 of file TrackInfoContainer_v1.cc
References _clones.
TrackInfoContainer_v1::~TrackInfoContainer_v1 () override
Definition at line 20 of file TrackInfoContainer_v1.cc.
View newest version in sPHENIX GitHub at line 20 of file TrackInfoContainer_v1.cc
References _clones.
Member Function Documentation
void TrackInfoContainer_v1::add_trackinfo (int pos, SvtxTrackInfo trackinfo) inline override virtual
Reimplemented from TrackInfoContainer.
Definition at line 34 of file TrackInfoContainer_v1.h.
View newest version in sPHENIX GitHub at line 34 of file TrackInfoContainer_v1.h
References _clones, SvtxTrackInfo::CopyFrom(), and Acts::Test::pos.
Referenced by DSTTrackInfoWriter::evaluate_track_info().
void TrackInfoContainer_v1::add_trackinfo (int pos, SvtxTrackInfo * trackinfo) inline override virtual
Reimplemented from TrackInfoContainer.
Definition at line 41 of file TrackInfoContainer_v1.h.
View newest version in sPHENIX GitHub at line 41 of file TrackInfoContainer_v1.h
References _clones, SvtxTrackInfo::CopyFrom(), and Acts::Test::pos.
TrackInfoContainer_v1::ClassDefOverride (TrackInfoContainer_v1 , 1) private
SvtxTrackInfo* TrackInfoContainer_v1::get_trackinfo (int pos) inline override virtual
Reimplemented from TrackInfoContainer.
Definition at line 29 of file TrackInfoContainer_v1.h.
View newest version in sPHENIX GitHub at line 29 of file TrackInfoContainer_v1.h
References _clones.
Referenced by DSTTrackInfoReader::evaluate_track_info().
void TrackInfoContainer_v1::identify (std::ostream & os = std::cout) const override virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from TrackInfoContainer.
Definition at line 25 of file TrackInfoContainer_v1.cc.
View newest version in sPHENIX GitHub at line 25 of file TrackInfoContainer_v1.cc
References size().
void TrackInfoContainer_v1::Reset () override virtual
Clear Event.
Reimplemented from TrackInfoContainer.
Definition at line 29 of file TrackInfoContainer_v1.cc.
View newest version in sPHENIX GitHub at line 29 of file TrackInfoContainer_v1.cc
References _clones, assert, and i.
Referenced by DSTTrackInfoWriter::evaluate_track_info(), DSTTrackInfoReader::process_event(), and DSTTrackInfoWriter::process_event().
size_t TrackInfoContainer_v1::size (void) const inline override virtual
Reimplemented from TrackInfoContainer.
Definition at line 27 of file TrackInfoContainer_v1.h.
View newest version in sPHENIX GitHub at line 27 of file TrackInfoContainer_v1.h
References _clones.
Referenced by DSTTrackInfoReader::evaluate_track_info(), and identify().
Member Data Documentation
TClonesArray* TrackInfoContainer_v1::_clones = nullptr protected
Definition at line 50 of file TrackInfoContainer_v1.h.
View newest version in sPHENIX GitHub at line 50 of file TrackInfoContainer_v1.h
Referenced by add_trackinfo(), get_trackinfo(), Reset(), size(), TrackInfoContainer_v1(), and ~TrackInfoContainer_v1().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/trackbase_historic/TrackInfoContainer_v1.h
coresoftware/blob/master/offline/packages/trackbase_historic/TrackInfoContainer_v1.cc