Analysis Software: cl::KernelFunctor Class Reference
cl::KernelFunctor Class Reference
Kernel functor interface.
#include <JETSCAPE/blob/main/external_packages/clvisc_wrapper/include/cl.hpp>
Public Member Functions
KernelFunctor ()
KernelFunctor (const Kernel &kernel, const CommandQueue &queue, const NDRange &offset, const NDRange &global, const NDRange &local)
KernelFunctor & operator= (const KernelFunctor &rhs)
KernelFunctor (const KernelFunctor &rhs)
cl_int getError ()
Event operator() (const VECTOR_CLASS< Event > *events=NULL)
template<typename A1 >
Event operator() (const A1 &a1, const VECTOR_CLASS< Event > *events=NULL)
template<class A1 , class A2 >
Event operator() (const A1 &a1, const A2 &a2, const VECTOR_CLASS< Event > *events=NULL)
template<class A1 , class A2 , class A3 >
Event operator() (const A1 &a1, const A2 &a2, const A3 &a3, const VECTOR_CLASS< Event > *events=NULL)
template<class A1 , class A2 , class A3 , class A4 >
Event operator() (const A1 &a1, const A2 &a2, const A3 &a3, const A4 &a4, const VECTOR_CLASS< Event > *events=NULL)
template<class A1 , class A2 , class A3 , class A4 , class A5 >
Event operator() (const A1 &a1, const A2 &a2, const A3 &a3, const A4 &a4, const A5 &a5, const VECTOR_CLASS< Event > *events=NULL)
template<class A1 , class A2 , class A3 , class A4 , class A5 , class A6 >
Event operator() (const A1 &a1, const A2 &a2, const A3 &a3, const A4 &a4, const A5 &a5, const A6 &a6, const VECTOR_CLASS< Event > *events=NULL)
template<class A1 , class A2 , class A3 , class A4 , class A5 , class A6 , class A7 >
Event operator() (const A1 &a1, const A2 &a2, const A3 &a3, const A4 &a4, const A5 &a5, const A6 &a6, const A7 &a7, const VECTOR_CLASS< Event > *events=NULL)
template<class A1 , class A2 , class A3 , class A4 , class A5 , class A6 , class A7 , class A8 >
Event operator() (const A1 &a1, const A2 &a2, const A3 &a3, const A4 &a4, const A5 &a5, const A6 &a6, const A7 &a7, const A8 &a8, const VECTOR_CLASS< Event > *events=NULL)
template<class A1 , class A2 , class A3 , class A4 , class A5 , class A6 , class A7 , class A8 , class A9 >
Event operator() (const A1 &a1, const A2 &a2, const A3 &a3, const A4 &a4, const A5 &a5, const A6 &a6, const A7 &a7, const A8 &a8, const A9 &a9, const VECTOR_CLASS< Event > *events=NULL)
template<class A1 , class A2 , class A3 , class A4 , class A5 , class A6 , class A7 , class A8 , class A9 , class A10 >
Event operator() (const A1 &a1, const A2 &a2, const A3 &a3, const A4 &a4, const A5 &a5, const A6 &a6, const A7 &a7, const A8 &a8, const A9 &a9, const A10 &a10, const VECTOR_CLASS< Event > *events=NULL)
template<class A1 , class A2 , class A3 , class A4 , class A5 , class A6 , class A7 , class A8 , class A9 , class A10 , class A11 >
Event operator() (const A1 &a1, const A2 &a2, const A3 &a3, const A4 &a4, const A5 &a5, const A6 &a6, const A7 &a7, const A8 &a8, const A9 &a9, const A10 &a10, const A11 &a11, const VECTOR_CLASS< Event > *events=NULL)
template<class A1 , class A2 , class A3 , class A4 , class A5 , class A6 , class A7 , class A8 , class A9 , class A10 , class A11 , class A12 >
Event operator() (const A1 &a1, const A2 &a2, const A3 &a3, const A4 &a4, const A5 &a5, const A6 &a6, const A7 &a7, const A8 &a8, const A9 &a9, const A10 &a10, const A11 &a11, const A12 &a12, const VECTOR_CLASS< Event > *events=NULL)
template<class A1 , class A2 , class A3 , class A4 , class A5 , class A6 , class A7 , class A8 , class A9 , class A10 , class A11 , class A12 , class A13 >
Event operator() (const A1 &a1, const A2 &a2, const A3 &a3, const A4 &a4, const A5 &a5, const A6 &a6, const A7 &a7, const A8 &a8, const A9 &a9, const A10 &a10, const A11 &a11, const A12 &a12, const A13 &a13, const VECTOR_CLASS< Event > *events=NULL)
template<class A1 , class A2 , class A3 , class A4 , class A5 , class A6 , class A7 , class A8 , class A9 , class A10 , class A11 , class A12 , class A13 , class A14 >
Event operator() (const A1 &a1, const A2 &a2, const A3 &a3, const A4 &a4, const A5 &a5, const A6 &a6, const A7 &a7, const A8 &a8, const A9 &a9, const A10 &a10, const A11 &a11, const A12 &a12, const A13 &a13, const A14 &a14, const VECTOR_CLASS< Event > *events=NULL)
template<class A1 , class A2 , class A3 , class A4 , class A5 , class A6 , class A7 , class A8 , class A9 , class A10 , class A11 , class A12 , class A13 , class A14 , class A15 >
Event operator() (const A1 &a1, const A2 &a2, const A3 &a3, const A4 &a4, const A5 &a5, const A6 &a6, const A7 &a7, const A8 &a8, const A9 &a9, const A10 &a10, const A11 &a11, const A12 &a12, const A13 &a13, const A14 &a14, const A15 &a15, const VECTOR_CLASS< Event > *events=NULL)
Private Attributes
Kernel kernel_
CommandQueue queue_
NDRange offset_
NDRange global_
NDRange local_
cl_int err_
Detailed Description
Kernel functor interface.
Note
Currently only functors of zero to ten arguments are supported. It is straightforward to add more and a more general solution, similar to Boost.Lambda could be followed if required in the future.
Definition at line 3125 of file cl.hpp.
View newest version in sPHENIX GitHub at line 3125 of file cl.hpp
Constructor & Destructor Documentation
cl::KernelFunctor::KernelFunctor () inline
Definition at line 3136 of file cl.hpp.
View newest version in sPHENIX GitHub at line 3136 of file cl.hpp
cl::KernelFunctor::KernelFunctor (const Kernel & kernel, const CommandQueue & queue, const NDRange & offset, const NDRange & global, const NDRange & local) inline
Definition at line 3138 of file cl.hpp.
View newest version in sPHENIX GitHub at line 3138 of file cl.hpp
cl::KernelFunctor::KernelFunctor (const KernelFunctor & rhs) inline
Definition at line 3387 of file cl.hpp.
View newest version in sPHENIX GitHub at line 3387 of file cl.hpp
Member Function Documentation
cl_int cl::KernelFunctor::getError () inline
Definition at line 3156 of file cl.hpp.
View newest version in sPHENIX GitHub at line 3156 of file cl.hpp
Event cl::KernelFunctor::operator() (const VECTOR_CLASS< Event > * events = NULL) inline
Definition at line 3396 of file cl.hpp.
View newest version in sPHENIX GitHub at line 3396 of file cl.hpp
References cl::CommandQueue::enqueueNDRangeKernel(), err_, event, global_, kernel_, local_, offset_, and queue_.
template<typename A1 > Event cl::KernelFunctor::operator() (const A1 & a1, const VECTOR_CLASS< Event > * events = NULL) inline
Definition at line 3412 of file cl.hpp.
View newest version in sPHENIX GitHub at line 3412 of file cl.hpp
References cl::CommandQueue::enqueueNDRangeKernel(), err_, event, global_, kernel_, local_, offset_, queue_, and cl::Kernel::setArg().
template<typename A1 , typename A2 > Event cl::KernelFunctor::operator() (const A1 & a1, const A2 & a2, const VECTOR_CLASS< Event > * events = NULL) inline
Definition at line 3432 of file cl.hpp.
View newest version in sPHENIX GitHub at line 3432 of file cl.hpp
References cl::CommandQueue::enqueueNDRangeKernel(), err_, event, global_, kernel_, local_, offset_, queue_, and cl::Kernel::setArg().
template<typename A1 , typename A2 , typename A3 > Event cl::KernelFunctor::operator() (const A1 & a1, const A2 & a2, const A3 & a3, const VECTOR_CLASS< Event > * events = NULL) inline
Definition at line 3454 of file cl.hpp.
View newest version in sPHENIX GitHub at line 3454 of file cl.hpp
References cl::CommandQueue::enqueueNDRangeKernel(), err_, event, global_, kernel_, local_, offset_, queue_, and cl::Kernel::setArg().
template<typename A1 , typename A2 , typename A3 , typename A4 > Event cl::KernelFunctor::operator() (const A1 & a1, const A2 & a2, const A3 & a3, const A4 & a4, const VECTOR_CLASS< Event > * events = NULL) inline
Definition at line 3478 of file cl.hpp.
View newest version in sPHENIX GitHub at line 3478 of file cl.hpp
References cl::CommandQueue::enqueueNDRangeKernel(), err_, event, global_, kernel_, local_, offset_, queue_, and cl::Kernel::setArg().
template<typename A1 , typename A2 , typename A3 , typename A4 , typename A5 > Event cl::KernelFunctor::operator() (const A1 & a1, const A2 & a2, const A3 & a3, const A4 & a4, const A5 & a5, const VECTOR_CLASS< Event > * events = NULL) inline
Definition at line 3504 of file cl.hpp.
View newest version in sPHENIX GitHub at line 3504 of file cl.hpp
References cl::CommandQueue::enqueueNDRangeKernel(), err_, event, global_, kernel_, local_, offset_, queue_, and cl::Kernel::setArg().
template<typename A1 , typename A2 , typename A3 , typename A4 , typename A5 , typename A6 > Event cl::KernelFunctor::operator() (const A1 & a1, const A2 & a2, const A3 & a3, const A4 & a4, const A5 & a5, const A6 & a6, const VECTOR_CLASS< Event > * events = NULL) inline
Definition at line 3533 of file cl.hpp.
View newest version in sPHENIX GitHub at line 3533 of file cl.hpp
References cl::CommandQueue::enqueueNDRangeKernel(), err_, event, global_, kernel_, local_, offset_, queue_, and cl::Kernel::setArg().
template<typename A1 , typename A2 , typename A3 , typename A4 , typename A5 , typename A6 , typename A7 > Event cl::KernelFunctor::operator() (const A1 & a1, const A2 & a2, const A3 & a3, const A4 & a4, const A5 & a5, const A6 & a6, const A7 & a7, const VECTOR_CLASS< Event > * events = NULL) inline
Definition at line 3564 of file cl.hpp.
View newest version in sPHENIX GitHub at line 3564 of file cl.hpp
References cl::CommandQueue::enqueueNDRangeKernel(), err_, event, global_, kernel_, local_, offset_, queue_, and cl::Kernel::setArg().
template<typename A1 , typename A2 , typename A3 , typename A4 , typename A5 , typename A6 , typename A7 , typename A8 > Event cl::KernelFunctor::operator() (const A1 & a1, const A2 & a2, const A3 & a3, const A4 & a4, const A5 & a5, const A6 & a6, const A7 & a7, const A8 & a8, const VECTOR_CLASS< Event > * events = NULL) inline
Definition at line 3597 of file cl.hpp.
View newest version in sPHENIX GitHub at line 3597 of file cl.hpp
References cl::CommandQueue::enqueueNDRangeKernel(), err_, event, global_, kernel_, local_, offset_, queue_, and cl::Kernel::setArg().
template<typename A1 , typename A2 , typename A3 , typename A4 , typename A5 , typename A6 , typename A7 , typename A8 , typename A9 > Event cl::KernelFunctor::operator() (const A1 & a1, const A2 & a2, const A3 & a3, const A4 & a4, const A5 & a5, const A6 & a6, const A7 & a7, const A8 & a8, const A9 & a9, const VECTOR_CLASS< Event > * events = NULL) inline
Definition at line 3632 of file cl.hpp.
View newest version in sPHENIX GitHub at line 3632 of file cl.hpp
References cl::CommandQueue::enqueueNDRangeKernel(), err_, event, global_, kernel_, local_, offset_, queue_, and cl::Kernel::setArg().
template<typename A1 , typename A2 , typename A3 , typename A4 , typename A5 , typename A6 , typename A7 , typename A8 , typename A9 , typename A10 > Event cl::KernelFunctor::operator() (const A1 & a1, const A2 & a2, const A3 & a3, const A4 & a4, const A5 & a5, const A6 & a6, const A7 & a7, const A8 & a8, const A9 & a9, const A10 & a10, const VECTOR_CLASS< Event > * events = NULL) inline
Definition at line 3669 of file cl.hpp.
View newest version in sPHENIX GitHub at line 3669 of file cl.hpp
References cl::CommandQueue::enqueueNDRangeKernel(), err_, event, global_, kernel_, local_, offset_, queue_, and cl::Kernel::setArg().
template<class A1 , class A2 , class A3 , class A4 , class A5 , class A6 , class A7 , class A8 , class A9 , class A10 , class A11 > Event cl::KernelFunctor::operator() (const A1 & a1, const A2 & a2, const A3 & a3, const A4 & a4, const A5 & a5, const A6 & a6, const A7 & a7, const A8 & a8, const A9 & a9, const A10 & a10, const A11 & a11, const VECTOR_CLASS< Event > * events = NULL) inline
Definition at line 3709 of file cl.hpp.
View newest version in sPHENIX GitHub at line 3709 of file cl.hpp
References cl::CommandQueue::enqueueNDRangeKernel(), err_, event, global_, kernel_, local_, offset_, queue_, and cl::Kernel::setArg().
template<class A1 , class A2 , class A3 , class A4 , class A5 , class A6 , class A7 , class A8 , class A9 , class A10 , class A11 , class A12 > Event cl::KernelFunctor::operator() (const A1 & a1, const A2 & a2, const A3 & a3, const A4 & a4, const A5 & a5, const A6 & a6, const A7 & a7, const A8 & a8, const A9 & a9, const A10 & a10, const A11 & a11, const A12 & a12, const VECTOR_CLASS< Event > * events = NULL) inline
Definition at line 3751 of file cl.hpp.
View newest version in sPHENIX GitHub at line 3751 of file cl.hpp
References cl::CommandQueue::enqueueNDRangeKernel(), err_, event, global_, kernel_, local_, offset_, queue_, and cl::Kernel::setArg().
template<class A1 , class A2 , class A3 , class A4 , class A5 , class A6 , class A7 , class A8 , class A9 , class A10 , class A11 , class A12 , class A13 > Event cl::KernelFunctor::operator() (const A1 & a1, const A2 & a2, const A3 & a3, const A4 & a4, const A5 & a5, const A6 & a6, const A7 & a7, const A8 & a8, const A9 & a9, const A10 & a10, const A11 & a11, const A12 & a12, const A13 & a13, const VECTOR_CLASS< Event > * events = NULL) inline
Definition at line 3795 of file cl.hpp.
View newest version in sPHENIX GitHub at line 3795 of file cl.hpp
References cl::CommandQueue::enqueueNDRangeKernel(), err_, event, global_, kernel_, local_, offset_, queue_, and cl::Kernel::setArg().
template<class A1 , class A2 , class A3 , class A4 , class A5 , class A6 , class A7 , class A8 , class A9 , class A10 , class A11 , class A12 , class A13 , class A14 > Event cl::KernelFunctor::operator() (const A1 & a1, const A2 & a2, const A3 & a3, const A4 & a4, const A5 & a5, const A6 & a6, const A7 & a7, const A8 & a8, const A9 & a9, const A10 & a10, const A11 & a11, const A12 & a12, const A13 & a13, const A14 & a14, const VECTOR_CLASS< Event > * events = NULL) inline
Definition at line 3841 of file cl.hpp.
View newest version in sPHENIX GitHub at line 3841 of file cl.hpp
References cl::CommandQueue::enqueueNDRangeKernel(), err_, event, global_, kernel_, local_, offset_, queue_, and cl::Kernel::setArg().
template<class A1 , class A2 , class A3 , class A4 , class A5 , class A6 , class A7 , class A8 , class A9 , class A10 , class A11 , class A12 , class A13 , class A14 , class A15 > Event cl::KernelFunctor::operator() (const A1 & a1, const A2 & a2, const A3 & a3, const A4 & a4, const A5 & a5, const A6 & a6, const A7 & a7, const A8 & a8, const A9 & a9, const A10 & a10, const A11 & a11, const A12 & a12, const A13 & a13, const A14 & a14, const A15 & a15, const VECTOR_CLASS< Event > * events = NULL) inline
Definition at line 3889 of file cl.hpp.
View newest version in sPHENIX GitHub at line 3889 of file cl.hpp
References cl::CommandQueue::enqueueNDRangeKernel(), err_, event, global_, kernel_, local_, offset_, queue_, and cl::Kernel::setArg().
KernelFunctor & cl::KernelFunctor::operator= (const KernelFunctor & rhs) inline
Definition at line 3372 of file cl.hpp.
View newest version in sPHENIX GitHub at line 3372 of file cl.hpp
References global_, kernel_, local_, offset_, and queue_.
Member Data Documentation
cl_int cl::KernelFunctor::err_ private
Definition at line 3134 of file cl.hpp.
View newest version in sPHENIX GitHub at line 3134 of file cl.hpp
Referenced by operator()().
NDRange cl::KernelFunctor::global_ private
Definition at line 3131 of file cl.hpp.
View newest version in sPHENIX GitHub at line 3131 of file cl.hpp
Referenced by operator()(), and operator=().
Kernel cl::KernelFunctor::kernel_ private
Definition at line 3128 of file cl.hpp.
View newest version in sPHENIX GitHub at line 3128 of file cl.hpp
Referenced by operator()(), and operator=().
NDRange cl::KernelFunctor::local_ private
Definition at line 3132 of file cl.hpp.
View newest version in sPHENIX GitHub at line 3132 of file cl.hpp
Referenced by operator()(), and operator=().
NDRange cl::KernelFunctor::offset_ private
Definition at line 3130 of file cl.hpp.
View newest version in sPHENIX GitHub at line 3130 of file cl.hpp
Referenced by operator()(), and operator=().
CommandQueue cl::KernelFunctor::queue_ private
Definition at line 3129 of file cl.hpp.
View newest version in sPHENIX GitHub at line 3129 of file cl.hpp
Referenced by operator()(), and operator=().
The documentation for this class was generated from the following file:
JETSCAPE/blob/main/external_packages/clvisc_wrapper/include/cl.hpp