Analysis Software: TSQLDriverManager Class Reference
TSQLDriverManager Class Reference
#include <RDBC/blob/master/include/RDBC/TSQLDriverManager.h>
Public Member Functions
~TSQLDriverManager ()
const char * GetName () const
Public Member Functions inherited from TSQL
TSQL (void *imp=0)
virtual ~TSQL ()
virtual void Throw (TSQLException *e)
TList * GetWarnings () const
void ClearWarnings ()
virtual Bool_t IsValid () const
Static Public Member Functions
static TSQLConnection * GetConnection (const TString &connectString)
static TSQLConnection * GetConnection (const TString &dsn, const TString &user, const TString &password="")
static Int_t GetLoginTimeout ()
static void SetLoginTimeout (Int_t seconds)
static void Shutdown ()
static TList * GetDataSources ()
static TList * GetDrivers ()
static TList * GetConnections ()
Static Public Member Functions inherited from TSQL
static Bool_t SetHandler (const TString &handler)
static Bool_t UnsetHandler (const TString &handler="")
Private Member Functions
TSQLDriverManager (const TSQLDriverManager &)
void operator= (const TSQLDriverManager &)
TSQLDriverManager ()
Friends
TSQLDriverManager * InitGlobalDriverManager ()
Additional Inherited Members
Protected Attributes inherited from TSQL
TList * fWarnings
void * fImp
Detailed Description
Definition at line 20 of file TSQLDriverManager.h.
View newest version in sPHENIX GitHub at line 20 of file TSQLDriverManager.h
Constructor & Destructor Documentation
TSQLDriverManager::TSQLDriverManager (const TSQLDriverManager &) inline private
Definition at line 25 of file TSQLDriverManager.h.
View newest version in sPHENIX GitHub at line 25 of file TSQLDriverManager.h
TSQLDriverManager::TSQLDriverManager () private
Definition at line 197 of file TSQLDriverManager.cxx.
View newest version in sPHENIX GitHub at line 197 of file TSQLDriverManager.cxx
References gConnections, and gDrivers.
TSQLDriverManager::~TSQLDriverManager ()
Definition at line 212 of file TSQLDriverManager.cxx.
View newest version in sPHENIX GitHub at line 212 of file TSQLDriverManager.cxx
References Shutdown().
Member Function Documentation
TSQLConnection * TSQLDriverManager::GetConnection (const TString & connectString) static
Definition at line 477 of file TSQLDriverManager.cxx.
View newest version in sPHENIX GitHub at line 477 of file TSQLDriverManager.cxx
References con, TSQL::fImp, GetConnections(), TSQL::GetWarnings(), gHandlersInitiated, gODBCini, InitHandlers(), TSQLConnection::SetURL(), and TSQL::Throw().
Referenced by bench(), ClassImp(), DbForm::Connect(), PgPostApplication::getConnection(), PgPostBankBackupLog::Init(), main(), oproducer(), RDBCconsumer(), RDBCemp(), RDBCfirst(), RDBCscroll(), RDBCTestConnect(), RDBCTestInt(), RDBCTestMetaData(), and PgPostApplication::setDBName().
TSQLConnection * TSQLDriverManager::GetConnection (const TString & dsn, const TString & user, const TString & password = "") static
Definition at line 359 of file TSQLDriverManager.cxx.
View newest version in sPHENIX GitHub at line 359 of file TSQLDriverManager.cxx
References TSQLUrl::AddOption(), con, EnterPassword(), TSQL::fImp, TSQLUrl::GetAnchor(), GetConnections(), TSQLUrl::GetDriver(), TSQLUrl::GetDSN(), TSQLUrl::GetPort(), TSQLUrl::GetProtocol(), TSQLUrl::GetSubProtocol(), TSQLUrl::GetUrl(), TSQL::GetWarnings(), gHandlersInitiated, gODBCini, TSQLImporter::Import(), InitHandlers(), TSQLUrl::IsDynamicDSN(), TSQLImporter::IsValid(), TSQLUrl::IsValid(), TSQLConnection::SetURL(), and TSQL::Throw().
TList * TSQLDriverManager::GetConnections () static
Definition at line 554 of file TSQLDriverManager.cxx.
View newest version in sPHENIX GitHub at line 554 of file TSQLDriverManager.cxx
References gConnections.
Referenced by TSQLConnection::Close(), and GetConnection().
TList * TSQLDriverManager::GetDataSources () static
Definition at line 260 of file TSQLDriverManager.cxx.
View newest version in sPHENIX GitHub at line 260 of file TSQLDriverManager.cxx
References TSQL::Throw().
TList * TSQLDriverManager::GetDrivers () static
Definition at line 244 of file TSQLDriverManager.cxx.
View newest version in sPHENIX GitHub at line 244 of file TSQLDriverManager.cxx
References gDrivers, and TSQL::Throw().
Int_t TSQLDriverManager::GetLoginTimeout () static
Definition at line 541 of file TSQLDriverManager.cxx.
View newest version in sPHENIX GitHub at line 541 of file TSQLDriverManager.cxx
const char* TSQLDriverManager::GetName () const inline
Definition at line 42 of file TSQLDriverManager.h.
View newest version in sPHENIX GitHub at line 42 of file TSQLDriverManager.h
void TSQLDriverManager::operator= (const TSQLDriverManager &) inline private
Definition at line 27 of file TSQLDriverManager.h.
View newest version in sPHENIX GitHub at line 27 of file TSQLDriverManager.h
void TSQLDriverManager::SetLoginTimeout (Int_t seconds) static
Definition at line 528 of file TSQLDriverManager.cxx.
View newest version in sPHENIX GitHub at line 528 of file TSQLDriverManager.cxx
void TSQLDriverManager::Shutdown () static
Definition at line 225 of file TSQLDriverManager.cxx.
View newest version in sPHENIX GitHub at line 225 of file TSQLDriverManager.cxx
References gConnections, gDrivers, and gODBCini.
Referenced by ~TSQLDriverManager().
Friends And Related Function Documentation
TSQLDriverManager* InitGlobalDriverManager () friend
Definition at line 76 of file TSQLDriverManager.cxx.
View newest version in sPHENIX GitHub at line 76 of file TSQLDriverManager.cxx
The documentation for this class was generated from the following files:
RDBC/blob/master/include/RDBC/TSQLDriverManager.h
RDBC/blob/master/rdbc/TSQLDriverManager.cxx