Analysis Software: TSQLTimestamp Class Reference
TSQLTimestamp Class Reference
#include <RDBC/blob/master/include/RDBC/TSQLTypes.h>
Public Member Functions
TSQLTimestamp (Int_t year, Int_t month, Int_t day, Int_t hour, Int_t minute, Int_t second, Int_t nanos=0)
TSQLTimestamp ()
TSQLTimestamp (UInt_t t)
TSQLTimestamp (const TSQLTimestamp &t)
virtual ~TSQLTimestamp ()
TSQLTimestamp & operator= (const TSQLTimestamp &d)
Int_t GetYear () const
Int_t GetMonth () const
Int_t GetDay () const
Int_t GetHour () const
Int_t GetMinute () const
Int_t GetSecond () const
Int_t GetNanos () const
void SetYear (Int_t year)
void SetMonth (Int_t month)
void SetDay (Int_t day)
void SetHour (Int_t h)
void SetMinute (Int_t m)
void SetSecond (Int_t s)
void SetNanos (Int_t nanos)
TString ToString () const
Protected Attributes
Int_t fNanos
Detailed Description
Definition at line 101 of file TSQLTypes.h.
View newest version in sPHENIX GitHub at line 101 of file TSQLTypes.h
Constructor & Destructor Documentation
TSQLTimestamp::TSQLTimestamp (Int_t year, Int_t month, Int_t day, Int_t hour, Int_t minute, Int_t second, Int_t nanos = 0) inline
Definition at line 108 of file TSQLTypes.h.
View newest version in sPHENIX GitHub at line 108 of file TSQLTypes.h
References Set(), and SetNanos().
TSQLTimestamp::TSQLTimestamp () inline
Definition at line 112 of file TSQLTypes.h.
View newest version in sPHENIX GitHub at line 112 of file TSQLTypes.h
TSQLTimestamp::TSQLTimestamp (UInt_t t) inline
Definition at line 113 of file TSQLTypes.h.
View newest version in sPHENIX GitHub at line 113 of file TSQLTypes.h
References t.
TSQLTimestamp::TSQLTimestamp (const TSQLTimestamp & t) inline
Definition at line 115 of file TSQLTypes.h.
View newest version in sPHENIX GitHub at line 115 of file TSQLTypes.h
virtual TSQLTimestamp::~TSQLTimestamp () inline virtual
Definition at line 116 of file TSQLTypes.h.
View newest version in sPHENIX GitHub at line 116 of file TSQLTypes.h
Member Function Documentation
Int_t TSQLTimestamp::GetDay () const inline
Definition at line 122 of file TSQLTypes.h.
View newest version in sPHENIX GitHub at line 122 of file TSQLTypes.h
Referenced by SetMonth(), ODBCPreparedStatement::SetTimestamp(), ODBCCallableStatement::SetTimestamp(), SetYear(), and ODBCResultSet::UpdateTimestamp().
Int_t TSQLTimestamp::GetHour () const inline
Definition at line 123 of file TSQLTypes.h.
View newest version in sPHENIX GitHub at line 123 of file TSQLTypes.h
Referenced by SetMinute(), SetSecond(), ODBCPreparedStatement::SetTimestamp(), ODBCCallableStatement::SetTimestamp(), and ODBCResultSet::UpdateTimestamp().
Int_t TSQLTimestamp::GetMinute () const inline
Definition at line 124 of file TSQLTypes.h.
View newest version in sPHENIX GitHub at line 124 of file TSQLTypes.h
Referenced by SetHour(), SetSecond(), ODBCPreparedStatement::SetTimestamp(), ODBCCallableStatement::SetTimestamp(), and ODBCResultSet::UpdateTimestamp().
Int_t TSQLTimestamp::GetMonth () const inline
Definition at line 121 of file TSQLTypes.h.
View newest version in sPHENIX GitHub at line 121 of file TSQLTypes.h
Referenced by SetDay(), ODBCPreparedStatement::SetTimestamp(), ODBCCallableStatement::SetTimestamp(), SetYear(), and ODBCResultSet::UpdateTimestamp().
Int_t TSQLTimestamp::GetNanos () const inline
Definition at line 126 of file TSQLTypes.h.
View newest version in sPHENIX GitHub at line 126 of file TSQLTypes.h
References fNanos.
Referenced by ODBCPreparedStatement::SetTimestamp(), ODBCCallableStatement::SetTimestamp(), and ODBCResultSet::UpdateTimestamp().
Int_t TSQLTimestamp::GetSecond () const inline
Definition at line 125 of file TSQLTypes.h.
View newest version in sPHENIX GitHub at line 125 of file TSQLTypes.h
Referenced by SetHour(), SetMinute(), ODBCPreparedStatement::SetTimestamp(), ODBCCallableStatement::SetTimestamp(), and ODBCResultSet::UpdateTimestamp().
Int_t TSQLTimestamp::GetYear () const inline
Definition at line 120 of file TSQLTypes.h.
View newest version in sPHENIX GitHub at line 120 of file TSQLTypes.h
Referenced by SetDay(), SetMonth(), ODBCPreparedStatement::SetTimestamp(), ODBCCallableStatement::SetTimestamp(), and ODBCResultSet::UpdateTimestamp().
TSQLTimestamp & TSQLTimestamp::operator= (const TSQLTimestamp & d) inline
Definition at line 161 of file TSQLTypes.h.
View newest version in sPHENIX GitHub at line 161 of file TSQLTypes.h
References fNanos.
void TSQLTimestamp::SetDay (Int_t day)
Definition at line 159 of file TSQLTypes.cxx.
View newest version in sPHENIX GitHub at line 159 of file TSQLTypes.cxx
References GetMonth(), GetYear(), and Set().
void TSQLTimestamp::SetHour (Int_t h)
Definition at line 167 of file TSQLTypes.cxx.
View newest version in sPHENIX GitHub at line 167 of file TSQLTypes.cxx
References GetMinute(), GetSecond(), and Set().
void TSQLTimestamp::SetMinute (Int_t m)
Definition at line 175 of file TSQLTypes.cxx.
View newest version in sPHENIX GitHub at line 175 of file TSQLTypes.cxx
References GetHour(), GetSecond(), and Set().
void TSQLTimestamp::SetMonth (Int_t month)
Definition at line 151 of file TSQLTypes.cxx.
View newest version in sPHENIX GitHub at line 151 of file TSQLTypes.cxx
References GetDay(), GetYear(), and Set().
void TSQLTimestamp::SetNanos (Int_t nanos) inline
Definition at line 133 of file TSQLTypes.h.
View newest version in sPHENIX GitHub at line 133 of file TSQLTypes.h
References fNanos.
Referenced by TSQLTimestamp().
void TSQLTimestamp::SetSecond (Int_t s)
Definition at line 183 of file TSQLTypes.cxx.
View newest version in sPHENIX GitHub at line 183 of file TSQLTypes.cxx
References GetHour(), GetMinute(), and Set().
void TSQLTimestamp::SetYear (Int_t year)
Definition at line 143 of file TSQLTypes.cxx.
View newest version in sPHENIX GitHub at line 143 of file TSQLTypes.cxx
References GetDay(), GetMonth(), and Set().
TString TSQLTimestamp::ToString () const
Definition at line 131 of file TSQLTypes.cxx.
View newest version in sPHENIX GitHub at line 131 of file TSQLTypes.cxx
References str.
Member Data Documentation
Int_t TSQLTimestamp::fNanos protected
Definition at line 104 of file TSQLTypes.h.
View newest version in sPHENIX GitHub at line 104 of file TSQLTypes.h
Referenced by GetNanos(), operator=(), and SetNanos().
The documentation for this class was generated from the following files:
RDBC/blob/master/include/RDBC/TSQLTypes.h
RDBC/blob/master/rdbc/TSQLTypes.cxx