Analysis Software: TpcDistortionCorrection Class Reference
TpcDistortionCorrection Class Reference
#include <coresoftware/blob/master/offline/packages/tpc/TpcDistortionCorrection.h>
Public Types
enum DistortionType { StaticOnly =0, BeamInducedAverage =1, BeamInducedFluctuation =2 }
enum CoordMask {
COORD_PHI = 1<<0, COORD_R = 1<<1, COORD_Z = 1<<2, COORD_PHIZ = COORD_PHI|COORD_Z,
COORD_ALL = COORD_PHI|COORD_R|COORD_Z
}
Public Member Functions
TpcDistortionCorrection ()=default
constructor
Acts::Vector3 get_corrected_position (const Acts::Vector3 &, const TpcDistortionCorrectionContainer *, unsigned int mask=COORD_ALL) const
get cluster corrected 3D position using given DistortionCorrectionObject
void read_phi_as_radians (bool flag=true)
set the phi histogram to be interpreted as radians.
Private Attributes
bool m_phi_hist_in_radians =true
Detailed Description
Definition at line 14 of file TpcDistortionCorrection.h.
View newest version in sPHENIX GitHub at line 14 of file TpcDistortionCorrection.h
Member Enumeration Documentation
enum TpcDistortionCorrection::CoordMask
Enumerator:
COORD_PHI
COORD_R
COORD_Z
COORD_PHIZ
COORD_ALL
Definition at line 28 of file TpcDistortionCorrection.h.
View newest version in sPHENIX GitHub at line 28 of file TpcDistortionCorrection.h
enum TpcDistortionCorrection::DistortionType
Enumerator:
StaticOnly
BeamInducedAverage
BeamInducedFluctuation
Definition at line 21 of file TpcDistortionCorrection.h.
View newest version in sPHENIX GitHub at line 21 of file TpcDistortionCorrection.h
Constructor & Destructor Documentation
TpcDistortionCorrection::TpcDistortionCorrection () default
constructor
Member Function Documentation
Acts::Vector3 TpcDistortionCorrection::get_corrected_position (const Acts::Vector3 & source, const TpcDistortionCorrectionContainer * dcc, unsigned int mask = COORD_ALL) const
get cluster corrected 3D position using given DistortionCorrectionObject
Definition at line 44 of file TpcDistortionCorrection.cc.
View newest version in sPHENIX GitHub at line 44 of file TpcDistortionCorrection.cc
References COORD_PHI, COORD_R, COORD_Z, TpcDistortionCorrectionContainer::dimensions, index, TpcDistortionCorrectionContainer::m_hDPint, TpcDistortionCorrectionContainer::m_hDRint, TpcDistortionCorrectionContainer::m_hDZint, m_phi_hist_in_radians, ActsTests::PropagationDatasets::phi, physmon_track_finding_ttbar::r, square(), and physmon_track_finding_ttbar::z.
Referenced by TpcSpaceChargeReconstruction::get_global_position(), PHTpcTrackSeedCircleFit::getGlobalPosition(), PHMicromegasTpcTrackMatching::getGlobalPosition(), PHTpcResiduals::getGlobalPosition(), PHSimpleKFProp::getGlobalPosition(), PHCASeeding::getGlobalPosition(), PHGenFitTrkFitter::getGlobalPosition(), MakeSourceLinks::getSourceLinks(), ActsAlignmentStates::makeTpcGlobalCorrections(), HelicalFitter::makeTpcGlobalCorrections(), PHTpcClusterMover::process_event(), PHTpcCentralMembraneClusterizer::process_event(), PHTpcCentralMembraneMatcher::process_event(), and PHSimpleKFProp::PropagateTrack().
void TpcDistortionCorrection::read_phi_as_radians (bool flag = true) inline
set the phi histogram to be interpreted as radians.
Definition at line 42 of file TpcDistortionCorrection.h.
View newest version in sPHENIX GitHub at line 42 of file TpcDistortionCorrection.h
References m_phi_hist_in_radians.
Member Data Documentation
bool TpcDistortionCorrection::m_phi_hist_in_radians =true private
Definition at line 47 of file TpcDistortionCorrection.h.
View newest version in sPHENIX GitHub at line 47 of file TpcDistortionCorrection.h
Referenced by get_corrected_position(), and read_phi_as_radians().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/tpc/TpcDistortionCorrection.h
coresoftware/blob/master/offline/packages/tpc/TpcDistortionCorrection.cc