Analysis Software: q_node Class Reference
q_node Class Reference
#include <JETSCAPE/blob/main/external_packages/gtl/include/GTL/pq_node.h>
Private Member Functions
q_node (node, int)
void partial (iterator)
void full (iterator)
PQ_KIND kind () const
void write (ostream &, int)
void clear ()
p_node * P ()
q_node * Q ()
direction_indicator * D ()
pq_leaf * L ()
void pertinent (iterator)
q_node * merge (iterator)
void turn ()
Private Attributes
iterator pert_begin
iterator pert_end
iterator partial_pos [3]
bool pert_cons
int partial_count
int full_count
Friends
class planarity
class pq_tree
Additional Inherited Members
Protected Types inherited from pq_node
enum PQ_KIND { P_NODE, Q_NODE, LEAF, DIR }
enum PQ_MARK { UNMARKED, QUEUED, BLOCKED, UNBLOCKED }
typedef symlist< pq_node * >
::iterator iterator
Protected Member Functions inherited from pq_node
pq_node (node n_, int id_)
virtual ~pq_node ()
Protected Attributes inherited from pq_node
int pert_children
int pert_leaves
bool is_endmost
pq_node * father
PQ_MARK mark
symlist< pq_node * > sons
iterator pos
list< pq_node * >::iterator lpos
node n
int id
node up
int up_id
Detailed Description
Definition at line 419 of file pq_node.h.
View newest version in sPHENIX GitHub at line 419 of file pq_node.h
Constructor & Destructor Documentation
q_node::q_node (node n_, int id_) private
Definition at line 102 of file pq_node.cpp.
View newest version in sPHENIX GitHub at line 102 of file pq_node.cpp
Member Function Documentation
void q_node::clear () inline private virtual
Reimplemented from pq_node.
Definition at line 270 of file pq_node.cpp.
View newest version in sPHENIX GitHub at line 270 of file pq_node.cpp
References pq_node::clear(), full_count, partial_count, pert_begin, and pert_end.
direction_indicator* q_node::D () inline private virtual
Implements pq_node.
Definition at line 486 of file pq_node.h.
View newest version in sPHENIX GitHub at line 486 of file pq_node.h
References assert.
void q_node::full (iterator it) inline private virtual
Reimplemented from pq_node.
Definition at line 121 of file pq_node.cpp.
View newest version in sPHENIX GitHub at line 121 of file pq_node.cpp
References full_count, pert_begin, pq_node::pert_leaves, and pertinent().
PQ_KIND q_node::kind () const inline private virtual
Implements pq_node.
Definition at line 445 of file pq_node.h.
View newest version in sPHENIX GitHub at line 445 of file pq_node.h
References pq_node::Q_NODE.
pq_leaf* q_node::L () inline private virtual
Implements pq_node.
Definition at line 496 of file pq_node.h.
View newest version in sPHENIX GitHub at line 496 of file pq_node.h
References assert.
q_node * q_node::merge (iterator it) private
Definition at line 293 of file pq_node.cpp.
View newest version in sPHENIX GitHub at line 293 of file pq_node.cpp
References assert, symlist< T >::back(), symlist< T >::erase(), pq_node::father, symlist< T >::front(), pq_node::is_endmost, pq_node::Q_NODE, pq_node::sons, and symlist< T >::splice().
Referenced by pq_tree::Q2(), and pq_tree::Q3().
p_node* q_node::P () inline private virtual
Implements pq_node.
Definition at line 467 of file pq_node.h.
View newest version in sPHENIX GitHub at line 467 of file pq_node.h
References assert.
void q_node::partial (iterator it) inline private virtual
Reimplemented from pq_node.
Definition at line 106 of file pq_node.cpp.
View newest version in sPHENIX GitHub at line 106 of file pq_node.cpp
References it, partial_count, partial_pos, pert_begin, pq_node::pert_leaves, and pertinent().
void q_node::pertinent (iterator it) private
Definition at line 133 of file pq_node.cpp.
View newest version in sPHENIX GitHub at line 133 of file pq_node.cpp
References assert, symlist< T >::back(), pq_node::DIR, end, symlist< T >::end(), symlist< T >::front(), it, pert_begin, pq_node::pert_children, pert_cons, pert_end, pq_node::sons, Acts::Test::tmp(), turn(), and pq_node::UNBLOCKED.
Referenced by full(), and partial().
q_node* q_node::Q () inline private virtual
Implements pq_node.
Definition at line 477 of file pq_node.h.
View newest version in sPHENIX GitHub at line 477 of file pq_node.h
Referenced by planarity::case_A(), planarity::case_B(), pq_tree::Q2(), and pq_tree::Q3().
void q_node::turn () private
Definition at line 316 of file pq_node.cpp.
View newest version in sPHENIX GitHub at line 316 of file pq_node.cpp
References symlist< T >::reverse(), and pq_node::sons.
Referenced by pq_tree::P6(), pertinent(), pq_tree::Q2(), and pq_tree::Q3().
void q_node::write (ostream & os, int _id) inline private virtual
Implements pq_node.
Definition at line 278 of file pq_node.cpp.
View newest version in sPHENIX GitHub at line 278 of file pq_node.cpp
References pq_node::BLOCKED, pq_node::mark, and pq_node::UNBLOCKED.
Friends And Related Function Documentation
friend class planarity friend
Definition at line 577 of file pq_node.h.
View newest version in sPHENIX GitHub at line 577 of file pq_node.h
friend class pq_tree friend
Definition at line 583 of file pq_node.h.
View newest version in sPHENIX GitHub at line 583 of file pq_node.h
Member Data Documentation
int q_node::full_count private
Definition at line 567 of file pq_node.h.
View newest version in sPHENIX GitHub at line 567 of file pq_node.h
Referenced by clear(), full(), and pq_tree::reduce().
int q_node::partial_count private
Definition at line 561 of file pq_node.h.
View newest version in sPHENIX GitHub at line 561 of file pq_node.h
Referenced by clear(), planarity::examine_obstruction(), partial(), pq_tree::Q1(), pq_tree::Q2(), pq_tree::Q3(), and pq_tree::reduce().
iterator q_node::partial_pos[3] private
Definition at line 546 of file pq_node.h.
View newest version in sPHENIX GitHub at line 546 of file pq_node.h
Referenced by planarity::examine_obstruction(), partial(), pq_tree::Q2(), pq_tree::Q3(), and pq_tree::reduce().
iterator q_node::pert_begin private
Definition at line 532 of file pq_node.h.
View newest version in sPHENIX GitHub at line 532 of file pq_node.h
Referenced by planarity::case_B(), planarity::case_E(), clear(), planarity::examine_obstruction(), full(), pq_tree::P3(), pq_tree::P6(), partial(), pertinent(), pq_tree::Q1(), pq_tree::Q2(), pq_tree::Q3(), pq_tree::reduce(), and pq_tree::replace_pert().
bool q_node::pert_cons private
Definition at line 555 of file pq_node.h.
View newest version in sPHENIX GitHub at line 555 of file pq_node.h
Referenced by planarity::examine_obstruction(), pq_tree::P3(), pertinent(), and pq_tree::reduce().
iterator q_node::pert_end private
Definition at line 538 of file pq_node.h.
View newest version in sPHENIX GitHub at line 538 of file pq_node.h
Referenced by planarity::case_B(), planarity::case_E(), clear(), planarity::examine_obstruction(), pq_tree::P3(), pq_tree::P4(), pq_tree::P5(), pq_tree::P6(), pertinent(), pq_tree::Q1(), pq_tree::Q2(), pq_tree::Q3(), pq_tree::reduce(), and pq_tree::replace_pert().
The documentation for this class was generated from the following files:
JETSCAPE/blob/main/external_packages/gtl/include/GTL/pq_node.h
JETSCAPE/blob/main/external_packages/gtl/src/pq_node.cpp