Analysis Software: ClusHitsVerbosev1 Class Reference
ClusHitsVerbosev1 Class Reference
Cluster container object.
#include <coresoftware/blob/master/offline/packages/trackbase/ClusHitsVerbosev1.h>
Public Member Functions
ClusHitsVerbosev1 ()=default
void Reset () override
Clear Event.
bool hasClusKey (TrkrDefs::cluskey) const override
Vector & phiBins (TrkrDefs::cluskey) override
Vector & zBins (TrkrDefs::cluskey) override
Vector & phiCutBins (TrkrDefs::cluskey) override
Vector & zCutBins (TrkrDefs::cluskey) override
Map & getMap () override
PairVector phiBins_pvecIE (TrkrDefs::cluskey) override
PairVector phiCutBins_pvecIE (TrkrDefs::cluskey) override
PairVector zBins_pvecIE (TrkrDefs::cluskey) override
PairVector zCutBins_pvecIE (TrkrDefs::cluskey) override
void addPhiHit (int _i, int _v) override
void addPhiCutHit (int _i, int _v) override
void addZHit (int _i, int _v) override
void addZCutHit (int _i, int _v) override
void push_hits (TrkrDefs::cluskey) override
void identify (std::ostream &os=std::cout) const override
Private Member Functions
PairVector pvecIE (TrkrDefs::cluskey, int which)
Vector & vecBins (TrkrDefs::cluskey, int which)
Private Attributes
Map m_data {}
Vector m_stage_phi {}
Vector m_stage_z {}
Vector m_stage_phiCut {}
Vector m_stage_zCut {}
Additional Inherited Members
Public Types inherited from ClusHitsVerbose
using BinData = std::pair< int, int >
using Vector = std::vector< BinData >
using Map = std::map< TrkrDefs::cluskey, std::array< Vector, 4 >>
using VecInt = std::vector< int >
using PairVector = std::pair< VecInt, VecInt >
Protected Member Functions inherited from ClusHitsVerbose
ClusHitsVerbose ()=default
Detailed Description
Cluster container object.
Definition at line 16 of file ClusHitsVerbosev1.h.
View newest version in sPHENIX GitHub at line 16 of file ClusHitsVerbosev1.h
Constructor & Destructor Documentation
ClusHitsVerbosev1::ClusHitsVerbosev1 () default
Member Function Documentation
void ClusHitsVerbosev1::addPhiCutHit (int _i, int _v) inline override virtual
Reimplemented from ClusHitsVerbose.
Definition at line 36 of file ClusHitsVerbosev1.h.
View newest version in sPHENIX GitHub at line 36 of file ClusHitsVerbosev1.h
References m_stage_phiCut.
Referenced by TpcClusterBuilder::cluster_hits(), PHG4InttHitReco::cluster_truthhits(), and PHG4MvtxHitReco::cluster_truthhits().
void ClusHitsVerbosev1::addPhiHit (int _i, int _v) inline override virtual
Reimplemented from ClusHitsVerbose.
Definition at line 35 of file ClusHitsVerbosev1.h.
View newest version in sPHENIX GitHub at line 35 of file ClusHitsVerbosev1.h
References m_stage_phi.
Referenced by TpcClusterBuilder::cluster_hits(), PHG4InttHitReco::cluster_truthhits(), PHG4MvtxHitReco::cluster_truthhits(), InttClusterizer::ClusterLadderCellsRaw(), and TpcClusterizer::process_event().
void ClusHitsVerbosev1::addZCutHit (int _i, int _v) inline override virtual
Reimplemented from ClusHitsVerbose.
Definition at line 38 of file ClusHitsVerbosev1.h.
View newest version in sPHENIX GitHub at line 38 of file ClusHitsVerbosev1.h
References m_stage_zCut.
Referenced by TpcClusterBuilder::cluster_hits(), PHG4InttHitReco::cluster_truthhits(), and PHG4MvtxHitReco::cluster_truthhits().
void ClusHitsVerbosev1::addZHit (int _i, int _v) inline override virtual
Reimplemented from ClusHitsVerbose.
Definition at line 37 of file ClusHitsVerbosev1.h.
View newest version in sPHENIX GitHub at line 37 of file ClusHitsVerbosev1.h
References m_stage_z.
Referenced by TpcClusterBuilder::cluster_hits(), PHG4InttHitReco::cluster_truthhits(), PHG4MvtxHitReco::cluster_truthhits(), InttClusterizer::ClusterLadderCellsRaw(), and TpcClusterizer::process_event().
Map& ClusHitsVerbosev1::getMap () inline override virtual
Reimplemented from ClusHitsVerbose.
Definition at line 28 of file ClusHitsVerbosev1.h.
View newest version in sPHENIX GitHub at line 28 of file ClusHitsVerbosev1.h
References m_data.
Referenced by PHG4InttHitReco::cluster_truthhits().
bool ClusHitsVerbosev1::hasClusKey (TrkrDefs::cluskey key) const override virtual
Reimplemented from ClusHitsVerbose.
Definition at line 25 of file ClusHitsVerbosev1.cc.
View newest version in sPHENIX GitHub at line 25 of file ClusHitsVerbosev1.cc
References m_data.
Referenced by pvecIE(), and vecBins().
void ClusHitsVerbosev1::identify (std::ostream & os = std::cout) const inline override virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from ClusHitsVerbose.
Definition at line 41 of file ClusHitsVerbosev1.h.
View newest version in sPHENIX GitHub at line 41 of file ClusHitsVerbosev1.h
References os.
ClusHitsVerbose::Vector & ClusHitsVerbosev1::phiBins (TrkrDefs::cluskey key) override virtual
Reimplemented from ClusHitsVerbose.
Definition at line 34 of file ClusHitsVerbosev1.cc.
View newest version in sPHENIX GitHub at line 34 of file ClusHitsVerbosev1.cc
References vecBins().
ClusHitsVerbose::PairVector ClusHitsVerbosev1::phiBins_pvecIE (TrkrDefs::cluskey key) override virtual
Reimplemented from ClusHitsVerbose.
Definition at line 60 of file ClusHitsVerbosev1.cc.
View newest version in sPHENIX GitHub at line 60 of file ClusHitsVerbosev1.cc
References pvecIE().
ClusHitsVerbose::Vector & ClusHitsVerbosev1::phiCutBins (TrkrDefs::cluskey key) override virtual
Reimplemented from ClusHitsVerbose.
Definition at line 40 of file ClusHitsVerbosev1.cc.
View newest version in sPHENIX GitHub at line 40 of file ClusHitsVerbosev1.cc
References vecBins().
ClusHitsVerbose::PairVector ClusHitsVerbosev1::phiCutBins_pvecIE (TrkrDefs::cluskey key) override virtual
Reimplemented from ClusHitsVerbose.
Definition at line 66 of file ClusHitsVerbosev1.cc.
View newest version in sPHENIX GitHub at line 66 of file ClusHitsVerbosev1.cc
References pvecIE().
void ClusHitsVerbosev1::push_hits (TrkrDefs::cluskey key) override virtual
Reimplemented from ClusHitsVerbose.
Definition at line 72 of file ClusHitsVerbosev1.cc.
View newest version in sPHENIX GitHub at line 72 of file ClusHitsVerbosev1.cc
References m_data, m_stage_phi, m_stage_phiCut, m_stage_z, and m_stage_zCut.
Referenced by TpcClusterBuilder::cluster_hits(), PHG4InttHitReco::cluster_truthhits(), PHG4MvtxHitReco::cluster_truthhits(), InttClusterizer::ClusterLadderCellsRaw(), and TpcClusterizer::process_event().
ClusHitsVerbose::PairVector ClusHitsVerbosev1::pvecIE (TrkrDefs::cluskey key, int which) private
Definition at line 46 of file ClusHitsVerbosev1.cc.
View newest version in sPHENIX GitHub at line 46 of file ClusHitsVerbosev1.cc
References entry, hasClusKey(), and m_data.
Referenced by phiBins_pvecIE(), phiCutBins_pvecIE(), zBins_pvecIE(), and zCutBins_pvecIE().
void ClusHitsVerbosev1::Reset () override virtual
Clear Event.
Reimplemented from ClusHitsVerbose.
Definition at line 16 of file ClusHitsVerbosev1.cc.
View newest version in sPHENIX GitHub at line 16 of file ClusHitsVerbosev1.cc
References m_data, m_stage_phi, m_stage_phiCut, m_stage_z, and m_stage_zCut.
ClusHitsVerbose::Vector & ClusHitsVerbosev1::vecBins (TrkrDefs::cluskey key, int which) private
Definition at line 29 of file ClusHitsVerbosev1.cc.
View newest version in sPHENIX GitHub at line 29 of file ClusHitsVerbosev1.cc
References hasClusKey(), and m_data.
Referenced by phiBins(), phiCutBins(), zBins(), and zCutBins().
ClusHitsVerbose::Vector & ClusHitsVerbosev1::zBins (TrkrDefs::cluskey key) override virtual
Reimplemented from ClusHitsVerbose.
Definition at line 37 of file ClusHitsVerbosev1.cc.
View newest version in sPHENIX GitHub at line 37 of file ClusHitsVerbosev1.cc
References vecBins().
ClusHitsVerbose::PairVector ClusHitsVerbosev1::zBins_pvecIE (TrkrDefs::cluskey key) override virtual
Reimplemented from ClusHitsVerbose.
Definition at line 63 of file ClusHitsVerbosev1.cc.
View newest version in sPHENIX GitHub at line 63 of file ClusHitsVerbosev1.cc
References pvecIE().
ClusHitsVerbose::Vector & ClusHitsVerbosev1::zCutBins (TrkrDefs::cluskey key) override virtual
Reimplemented from ClusHitsVerbose.
Definition at line 43 of file ClusHitsVerbosev1.cc.
View newest version in sPHENIX GitHub at line 43 of file ClusHitsVerbosev1.cc
References vecBins().
ClusHitsVerbose::PairVector ClusHitsVerbosev1::zCutBins_pvecIE (TrkrDefs::cluskey key) override virtual
Reimplemented from ClusHitsVerbose.
Definition at line 69 of file ClusHitsVerbosev1.cc.
View newest version in sPHENIX GitHub at line 69 of file ClusHitsVerbosev1.cc
References pvecIE().
Member Data Documentation
Map ClusHitsVerbosev1::m_data {} private
Definition at line 48 of file ClusHitsVerbosev1.h.
View newest version in sPHENIX GitHub at line 48 of file ClusHitsVerbosev1.h
Referenced by getMap(), hasClusKey(), push_hits(), pvecIE(), Reset(), and vecBins().
Vector ClusHitsVerbosev1::m_stage_phi {} private
Definition at line 49 of file ClusHitsVerbosev1.h.
View newest version in sPHENIX GitHub at line 49 of file ClusHitsVerbosev1.h
Referenced by addPhiHit(), push_hits(), and Reset().
Vector ClusHitsVerbosev1::m_stage_phiCut {} private
Definition at line 51 of file ClusHitsVerbosev1.h.
View newest version in sPHENIX GitHub at line 51 of file ClusHitsVerbosev1.h
Referenced by addPhiCutHit(), push_hits(), and Reset().
Vector ClusHitsVerbosev1::m_stage_z {} private
Definition at line 50 of file ClusHitsVerbosev1.h.
View newest version in sPHENIX GitHub at line 50 of file ClusHitsVerbosev1.h
Referenced by addZHit(), push_hits(), and Reset().
Vector ClusHitsVerbosev1::m_stage_zCut {} private
Definition at line 52 of file ClusHitsVerbosev1.h.
View newest version in sPHENIX GitHub at line 52 of file ClusHitsVerbosev1.h
Referenced by addZCutHit(), push_hits(), and Reset().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/trackbase/ClusHitsVerbosev1.h
coresoftware/blob/master/offline/packages/trackbase/ClusHitsVerbosev1.cc