Analysis Software: Acts::BinnedArray< T > Class Template Reference
Acts::BinnedArray< T > Class Template Reference abstract
#include <acts/blob/sPHENIX/Core/include/Acts/Utilities/BinnedArray.hpp>
Public Member Functions
BinnedArray ()=default
Default Constructor - needed for inherited classes.
virtual ~BinnedArray ()=default
Virtual Destructor.
virtual T object (const Vector2 &lposition, std::array< size_t, 3 > &bins) const =0
virtual T object (const Vector2 &lposition) const
virtual T object (const Vector3 &position, std::array< size_t, 3 > &bin) const =0
virtual T object (const Vector3 &position) const
virtual const std::vector< T > & arrayObjects () const =0
virtual const std::vector
< std::vector< std::vector< T > > > & objectGrid () const =0
virtual const BinUtility * binUtility () const =0
Detailed Description
template<class T>
class Acts::BinnedArray< T >
Pure virtual base class for Binned Array to avoid map searches
there is only one restriction: T must be of pointer type in order to be initialized with nullptr and to allow for nullptr return type
the BinnedArray is designed for 0D, 1D, 2D, and 3D binning
Definition at line 31 of file BinnedArray.hpp.
View newest version in sPHENIX GitHub at line 31 of file BinnedArray.hpp
Constructor & Destructor Documentation
template<class T > Acts::BinnedArray< T >::BinnedArray () default
Default Constructor - needed for inherited classes.
template<class T > virtual Acts::BinnedArray< T >::~BinnedArray () virtual default
Virtual Destructor.
Member Function Documentation
template<class T > virtual const std::vector<T>& Acts::BinnedArray< T >::arrayObjects () const pure virtual
Return all unique object
Note
this is the accessor to the
Returns
the vector of all array objects
Implemented in Acts::BinnedArrayXD< T >.
Referenced by Acts::Test::BOOST_AUTO_TEST_CASE(), ActsExamples::RootMaterialWriter::collectMaterial(), Acts::VolumeMaterialMapper::collectMaterialSurfaces(), Acts::Svg::TrackingGeometryConverter::convert(), Acts::MaterialMapJsonConverter::convertToHierarchy(), Acts::GeometryView3D::drawTrackingVolume(), Acts::SurfaceMaterialMapper::resolveMaterialSurfaces(), and Acts::MappingMaterialDecorator::volumeLoop().
template<class T > virtual const BinUtility* Acts::BinnedArray< T >::binUtility () const pure virtual
Return the BinUtility
if returned 0 it is a 0D array
Returns
plain pointer to the bin utility
Implemented in Acts::BinnedArrayXD< T >.
template<class T > virtual T Acts::BinnedArray< T >::object (const Vector2 & lposition, std::array< size_t, 3 > & bins) const pure virtual
Returns the object in the associated bin according the local position
Parameters
lposition is the local position for the object retrieval
bins is the bin triple to filled
Returns
the object according to the estimated bin
Implemented in Acts::BinnedArrayXD< T >.
Referenced by Acts::BinnedArray< T >::object().
template<class T > virtual T Acts::BinnedArray< T >::object (const Vector2 & lposition) const inline virtual
Same method without bins for backward compatibility
Parameters
lposition is the local position for finding the object
Returns
the object according to the estimated bin
Reimplemented in Acts::BinnedArrayXD< T >.
Definition at line 51 of file BinnedArray.hpp.
View newest version in sPHENIX GitHub at line 51 of file BinnedArray.hpp
References Acts::BinnedArray< T >::object().
template<class T > virtual T Acts::BinnedArray< T >::object (const Vector3 & position, std::array< size_t, 3 > & bin) const pure virtual
Returns the object in the associated bin according the local position
Parameters
position is the global position for the object retrieval
bin is the bin triple filled
Returns
the object according to the estimated bin
Implemented in Acts::BinnedArrayXD< T >.
template<class T > virtual T Acts::BinnedArray< T >::object (const Vector3 & position) const inline virtual
Same method without bins for backward compatibility
Parameters
position is the global position for the object finding
Returns
the object according to the estimated bin
Reimplemented in Acts::BinnedArrayXD< T >.
Definition at line 70 of file BinnedArray.hpp.
View newest version in sPHENIX GitHub at line 70 of file BinnedArray.hpp
References Acts::BinnedArray< T >::object().
template<class T > virtual const std::vector<std::vector<std::vector<T> > >& Acts::BinnedArray< T >::objectGrid () const pure virtual
Return the object grid multiple entries are allowed
Returns
the object grid
Implemented in Acts::BinnedArrayXD< T >.
The documentation for this class was generated from the following file:
acts/blob/sPHENIX/Core/include/Acts/Utilities/BinnedArray.hpp