Analysis Software: PHG4InnerHcalDetector Class Reference
PHG4InnerHcalDetector Class Reference
#include <coresoftware/blob/master/simulation/g4simulation/g4detectors/PHG4InnerHcalDetector.h>
Public Types
typedef
CGAL::Exact_circular_kernel_2 Circular_k
typedef CGAL::Point_2< Circular_k > Point_2
Public Member Functions
PHG4InnerHcalDetector (PHG4Subsystem *subsys, PHCompositeNode *Node, PHParameters *parameters, const std::string &dnam)
constructor
~PHG4InnerHcalDetector () override
destructor
void ConstructMe (G4LogicalVolume *world) override
construct
void Print (const std::string &what="ALL") const override
void SuperDetector (const std::string &name)
const std::string SuperDetector () const
int get_Layer () const
G4VSolid * ConstructSteelPlate (G4LogicalVolume *hcalenvelope)
G4VSolid * ConstructScintillatorBox (G4LogicalVolume *hcalenvelope)
void ShiftSecantToTangent (Point_2 &lowleft, Point_2 &upleft, Point_2 &upright, Point_2 &lowright)
G4AssemblyVolume * ConstructHcalScintillatorAssembly (G4LogicalVolume *hcalenvelope)
void ConstructHcalSingleScintillators (G4LogicalVolume *hcalenvelope)
int CheckTiltAngle () const
int ConsistencyCheck () const
void SetTiltViaNcross ()
std::pair< int, int > GetLayerTowerId (G4VPhysicalVolume *volume) const
volume accessors
int IsInInnerHcal (G4VPhysicalVolume *) const
Public Member Functions inherited from PHG4Detector
PHG4Detector ()=delete
constructor
PHG4Detector (PHG4Subsystem *subsys, PHCompositeNode *Node, const std::string &nam)
virtual ~PHG4Detector (void)
destructor
virtual void Construct (G4LogicalVolume *world) final
construct method
virtual void PostConstruction ()
Optional PostConstruction call after all geometry is constructed.
virtual void Verbosity (const int v)
virtual int Verbosity () const
virtual G4UserSteppingAction * GetSteppingAction ()
virtual std::string GetName () const
virtual void OverlapCheck (const bool chk)
virtual bool OverlapCheck () const
virtual int DisplayVolume (G4VSolid *volume, G4LogicalVolume *logvol, G4RotationMatrix *rotm=nullptr)
virtual int DisplayVolume (G4LogicalVolume *checksolid, G4LogicalVolume *logvol, G4RotationMatrix *rotm=nullptr)
virtual PHCompositeNode * topNode ()
virtual PHG4Subsystem * GetMySubsystem ()
Protected Member Functions
void AddGeometryNode ()
int ConstructInnerHcal (G4LogicalVolume *sandwich)
double x_at_y (Point_2 &p0, Point_2 &p1, double yin)
Protected Attributes
PHG4InnerHcalDisplayAction * m_DisplayAction = nullptr
PHParameters * m_Params = nullptr
G4AssemblyVolume * m_ScintiMotherAssembly = nullptr
double m_InnerRadius = NAN
double m_OuterRadius = NAN
double m_SizeZ = NAN
double m_ScintiTileX = NAN
double m_ScintiTileXLower = NAN
double m_ScintiTileXUpper = NAN
double m_ScintiTileZ = NAN
double m_ScintiTileThickness = NAN
double m_ScintiInnerGap = NAN
double m_ScintiOuterGap = NAN
double m_ScintiOuterRadius = NAN
double m_TiltAngle = NAN
double m_EnvelopeInnerRadius = NAN
double m_EnvelopeOuterRadius = NAN
double m_EnvelopeZ = NAN
double m_VolumeEnvelope = NAN
double m_VolumeSteel = NAN
double m_VolumeScintillator = NAN
int m_NumScintiPlates = 0
int m_NumScintiTilesPos = 0
int m_NumScintiTilesNeg = 0
int m_Active = 0
int m_AbsorberActive = 0
int m_Layer = 0
std::string m_SuperDetector
std::set< G4VPhysicalVolume * > m_SteelAbsorberPhysVolSet
std::map< G4VPhysicalVolume
*, std::pair< int, int > > m_ScintiTilePhysVolMap
std::vector< G4VSolid * > m_ScintiTilesVec
std::string m_ScintiLogicNamePrefix
RawTowerGeomContainer * m_RawTowerGeom = nullptr
std::string m_TowerGeomNodeName
Additional Inherited Members
Static Public Member Functions inherited from PHG4Detector
static G4Material * GetDetectorMaterial (const std::string &name, const bool quit=true)
static G4Element * GetDetectorElement (const std::string &name, const bool quit=true)
Detailed Description
Definition at line 33 of file PHG4InnerHcalDetector.h.
View newest version in sPHENIX GitHub at line 33 of file PHG4InnerHcalDetector.h
Member Typedef Documentation
typedef CGAL::Exact_circular_kernel_2 PHG4InnerHcalDetector::Circular_k
Definition at line 36 of file PHG4InnerHcalDetector.h.
View newest version in sPHENIX GitHub at line 36 of file PHG4InnerHcalDetector.h
typedef CGAL::Point_2<Circular_k> PHG4InnerHcalDetector::Point_2
Definition at line 37 of file PHG4InnerHcalDetector.h.
View newest version in sPHENIX GitHub at line 37 of file PHG4InnerHcalDetector.h
Constructor & Destructor Documentation
PHG4InnerHcalDetector::PHG4InnerHcalDetector (PHG4Subsystem * subsys, PHCompositeNode * Node, PHParameters * parameters, const std::string & dnam)
constructor
Definition at line 81 of file PHG4InnerHcalDetector.cc.
View newest version in sPHENIX GitHub at line 81 of file PHG4InnerHcalDetector.cc
References PHParameters::get_int_param(), m_NumScintiTilesNeg, m_NumScintiTilesPos, m_Params, m_ScintiTilesVec, PHG4HcalDefs::n_scinti_tiles, and PHParameters::set_int_param().
PHG4InnerHcalDetector::~PHG4InnerHcalDetector () override
destructor
Definition at line 123 of file PHG4InnerHcalDetector.cc.
View newest version in sPHENIX GitHub at line 123 of file PHG4InnerHcalDetector.cc
References m_ScintiMotherAssembly.
Member Function Documentation
void PHG4InnerHcalDetector::AddGeometryNode () protected
Definition at line 952 of file PHG4InnerHcalDetector.cc.
View newest version in sPHENIX GitHub at line 952 of file PHG4InnerHcalDetector.cc
References RawTowerGeomContainer::add_tower_geometry(), PHCompositeNode::addNode(), RawTowerDefs::convert_name_to_caloid(), Acts::UnitConstants::e, RawTowerDefs::encode_towerid(), PHNodeIterator::findFirst(), RawTowerGeom::get_center_x(), PHParameters::get_double_param(), RawTowerGeomContainer::get_etabins(), RawTowerGeomContainer::get_etacenter(), PHParameters::get_int_param(), RawTowerGeomContainer::get_phibins(), RawTowerGeomContainer::get_phicenter(), PHG4Utils::get_theta(), RawTowerGeomContainer::get_tower_geometry(), i, RawTowerGeomContainer::identify(), PHG4HcalDefs::innerrad, m_Params, m_RawTowerGeom, m_SuperDetector, m_TowerGeomNodeName, PHG4HcalDefs::n_towers, PHG4HcalDefs::outerrad, PHCompositeNode::PHCompositeNode(), G4HCALIN::phistart, PHWHERE, RawTowerGeomContainer::set_etabins(), RawTowerGeomContainer::set_etabounds(), RawTowerGeomContainer::set_phibins(), RawTowerGeomContainer::set_phibounds(), RawTowerGeomContainer::set_radius(), RawTowerGeomContainer::set_thickness(), tg, thickness, PHG4Detector::topNode(), PHG4Detector::Verbosity(), ambiguity_solver_full_chain::x, y, and physmon_track_finding_ttbar::z.
Referenced by ConstructMe().
int PHG4InnerHcalDetector::CheckTiltAngle () const
Definition at line 785 of file PHG4InnerHcalDetector.cc.
View newest version in sPHENIX GitHub at line 785 of file PHG4InnerHcalDetector.cc
References deg, m_InnerRadius, m_OuterRadius, m_TiltAngle, PHWHERE, and Acts::UnitConstants::rad.
Referenced by ConstructInnerHcal().
int PHG4InnerHcalDetector::ConsistencyCheck () const
Definition at line 813 of file PHG4InnerHcalDetector.cc.
View newest version in sPHENIX GitHub at line 813 of file PHG4InnerHcalDetector.cc
References Acts::UnitConstants::cm, m_InnerRadius, m_OuterRadius, m_ScintiInnerGap, m_ScintiOuterRadius, m_ScintiTileThickness, and PHWHERE.
Referenced by ConstructInnerHcal().
G4AssemblyVolume * PHG4InnerHcalDetector::ConstructHcalScintillatorAssembly (G4LogicalVolume * hcalenvelope)
Definition at line 760 of file PHG4InnerHcalDetector.cc.
View newest version in sPHENIX GitHub at line 760 of file PHG4InnerHcalDetector.cc
References PHG4InnerHcalDisplayAction::AddScintiVolume(), Acts::UnitConstants::cm, ConstructHcalSingleScintillators(), PHParameters::get_double_param(), PHG4Detector::GetDetectorMaterial(), i, m_DisplayAction, m_Params, m_ScintiLogicNamePrefix, m_ScintiTilesVec, and perf_headwind::name.
Referenced by ConstructInnerHcal().
void PHG4InnerHcalDetector::ConstructHcalSingleScintillators (G4LogicalVolume * hcalenvelope)
Definition at line 582 of file PHG4InnerHcalDetector.cc.
View newest version in sPHENIX GitHub at line 582 of file PHG4InnerHcalDetector.cc
References Acts::UnitConstants::cm, ConstructScintillatorBox(), deg, eta, PHParameters::get_double_param(), PHG4Utils::get_theta(), i, j, m_InnerRadius, m_NumScintiTilesNeg, m_NumScintiTilesPos, m_OuterRadius, m_Params, m_ScintiTilesVec, m_ScintiTileThickness, m_ScintiTileX, Acts::UnitConstants::mm, perf_headwind::name, offset, PHParameters::set_double_param(), ActsTests::PropagationDatasets::theta, testSigmaEff::v, ambiguity_solver_full_chain::x, x_at_y(), physmon_track_finding_ttbar::z, and KFPMath::zero().
Referenced by ConstructHcalScintillatorAssembly().
int PHG4InnerHcalDetector::ConstructInnerHcal (G4LogicalVolume * sandwich) protected
Definition at line 507 of file PHG4InnerHcalDetector.cc.
View newest version in sPHENIX GitHub at line 507 of file PHG4InnerHcalDetector.cc
References PHG4InnerHcalDisplayAction::AddSteelVolume(), CheckTiltAngle(), ConsistencyCheck(), ConstructHcalScintillatorAssembly(), ConstructSteelPlate(), PHParameters::get_string_param(), PHG4Detector::GetDetectorMaterial(), i, m_DisplayAction, m_InnerRadius, m_NumScintiPlates, m_OuterRadius, m_Params, m_ScintiMotherAssembly, m_ScintiTileX, m_ScintiTileXLower, m_ScintiTileXUpper, m_SteelAbsorberPhysVolSet, m_TiltAngle, perf_headwind::name, PHG4Detector::OverlapCheck(), ActsTests::PropagationDatasets::phi, Acts::UnitConstants::rad, SetTiltViaNcross(), subtract_from_scinti_x, and xpos.
Referenced by ConstructMe().
void PHG4InnerHcalDetector::ConstructMe (G4LogicalVolume * world) override virtual
construct
Implements PHG4Detector.
Definition at line 430 of file PHG4InnerHcalDetector.cc.
View newest version in sPHENIX GitHub at line 430 of file PHG4InnerHcalDetector.cc
References AddGeometryNode(), Acts::UnitConstants::cm, ConstructInnerHcal(), deg, PHParameters::get_double_param(), PHParameters::get_int_param(), PHFlag::get_StringFlag(), PHG4Detector::GetDetectorMaterial(), i, recoConsts::instance(), it, m_DisplayAction, m_EnvelopeInnerRadius, m_EnvelopeOuterRadius, m_EnvelopeZ, m_NumScintiPlates, m_Params, m_ScintiMotherAssembly, m_ScintiTilePhysVolMap, m_VolumeEnvelope, PHG4Detector::OverlapCheck(), PHWHERE, and PHG4InnerHcalDisplayAction::SetMyTopVolume().
G4VSolid * PHG4InnerHcalDetector::ConstructScintillatorBox (G4LogicalVolume * hcalenvelope)
Definition at line 150 of file PHG4InnerHcalDetector.cc.
View newest version in sPHENIX GitHub at line 150 of file PHG4InnerHcalDetector.cc
References m_InnerRadius, m_NumScintiPlates, m_OuterRadius, m_ScintiOuterRadius, m_ScintiTileThickness, m_ScintiTileX, m_ScintiTileXLower, m_ScintiTileXUpper, m_ScintiTileZ, m_TiltAngle, m_VolumeScintillator, Acts::VectorHelpers::perp(), Acts::UnitConstants::rad, and subtract_from_scinti_x.
Referenced by ConstructHcalSingleScintillators().
G4VSolid * PHG4InnerHcalDetector::ConstructSteelPlate (G4LogicalVolume * hcalenvelope)
Definition at line 227 of file PHG4InnerHcalDetector.cc.
View newest version in sPHENIX GitHub at line 227 of file PHG4InnerHcalDetector.cc
References m_InnerRadius, m_NumScintiPlates, m_OuterRadius, m_ScintiInnerGap, m_ScintiOuterGap, m_SizeZ, m_TiltAngle, m_VolumeSteel, Acts::VectorHelpers::perp(), Acts::UnitConstants::rad, ShiftSecantToTangent(), v1, v2, v3, v4, and KFPMath::zero().
Referenced by ConstructInnerHcal().
int PHG4InnerHcalDetector::get_Layer () const inline
Definition at line 57 of file PHG4InnerHcalDetector.h.
View newest version in sPHENIX GitHub at line 57 of file PHG4InnerHcalDetector.h
References m_Layer.
std::pair< int, int > PHG4InnerHcalDetector::GetLayerTowerId (G4VPhysicalVolume * volume) const
Definition at line 936 of file PHG4InnerHcalDetector.cc.
View newest version in sPHENIX GitHub at line 936 of file PHG4InnerHcalDetector.cc
References it, and m_ScintiTilePhysVolMap.
Referenced by PHG4InnerHcalSteppingAction::NoHitSteppingAction(), and PHG4InnerHcalSteppingAction::UserSteppingAction().
int PHG4InnerHcalDetector::IsInInnerHcal (G4VPhysicalVolume * volume) const
Definition at line 130 of file PHG4InnerHcalDetector.cc.
View newest version in sPHENIX GitHub at line 130 of file PHG4InnerHcalDetector.cc
References m_AbsorberActive, m_Active, m_ScintiTilePhysVolMap, and m_SteelAbsorberPhysVolSet.
Referenced by PHG4InnerHcalSteppingAction::NoHitSteppingAction(), and PHG4InnerHcalSteppingAction::UserSteppingAction().
void PHG4InnerHcalDetector::Print (const std::string & what = "ALL") const override virtual
Reimplemented from PHG4Detector.
Definition at line 923 of file PHG4InnerHcalDetector.cc.
View newest version in sPHENIX GitHub at line 923 of file PHG4InnerHcalDetector.cc
References Acts::UnitConstants::cm3, m_VolumeEnvelope, m_VolumeScintillator, and m_VolumeSteel.
Referenced by PHG4InnerHcalSubsystem::Print().
void PHG4InnerHcalDetector::SetTiltViaNcross ()
Definition at line 840 of file PHG4InnerHcalDetector.cc.
View newest version in sPHENIX GitHub at line 840 of file PHG4InnerHcalDetector.cc
References autodiff::detail::copysign(), deg, PHParameters::get_int_param(), m_InnerRadius, m_NumScintiPlates, m_OuterRadius, m_Params, m_TiltAngle, Acts::UnitConstants::rad, PHParameters::set_double_param(), PHParameters::set_int_param(), and PHG4Detector::Verbosity().
Referenced by ConstructInnerHcal().
void PHG4InnerHcalDetector::ShiftSecantToTangent (Point_2 & lowleft, Point_2 & upleft, Point_2 & upright, Point_2 & lowright)
Definition at line 381 of file PHG4InnerHcalDetector.cc.
View newest version in sPHENIX GitHub at line 381 of file PHG4InnerHcalDetector.cc
References m_InnerRadius.
Referenced by ConstructSteelPlate().
void PHG4InnerHcalDetector::SuperDetector (const std::string & name) inline
Definition at line 55 of file PHG4InnerHcalDetector.h.
View newest version in sPHENIX GitHub at line 55 of file PHG4InnerHcalDetector.h
References m_SuperDetector, and perf_headwind::name.
Referenced by PHG4InnerHcalSteppingAction::CreateNodeTree(), PHG4InnerHcalSubsystem::InitRunSubsystem(), and PHG4InnerHcalSteppingAction::SetInterfacePointers().
const std::string PHG4InnerHcalDetector::SuperDetector () const inline
Definition at line 56 of file PHG4InnerHcalDetector.h.
View newest version in sPHENIX GitHub at line 56 of file PHG4InnerHcalDetector.h
References m_SuperDetector.
double PHG4InnerHcalDetector::x_at_y (Point_2 & p0, Point_2 & p1, double yin) protected
Definition at line 730 of file PHG4InnerHcalDetector.cc.
View newest version in sPHENIX GitHub at line 730 of file PHG4InnerHcalDetector.cc
References PHWHERE, ambiguity_solver_full_chain::x, and y.
Referenced by ConstructHcalSingleScintillators().
Member Data Documentation
int PHG4InnerHcalDetector::m_AbsorberActive = 0 protected
Definition at line 100 of file PHG4InnerHcalDetector.h.
View newest version in sPHENIX GitHub at line 100 of file PHG4InnerHcalDetector.h
Referenced by IsInInnerHcal().
int PHG4InnerHcalDetector::m_Active = 0 protected
Definition at line 99 of file PHG4InnerHcalDetector.h.
View newest version in sPHENIX GitHub at line 99 of file PHG4InnerHcalDetector.h
Referenced by IsInInnerHcal().
PHG4InnerHcalDisplayAction* PHG4InnerHcalDetector::m_DisplayAction = nullptr protected
Definition at line 73 of file PHG4InnerHcalDetector.h.
View newest version in sPHENIX GitHub at line 73 of file PHG4InnerHcalDetector.h
Referenced by ConstructHcalScintillatorAssembly(), ConstructInnerHcal(), and ConstructMe().
double PHG4InnerHcalDetector::m_EnvelopeInnerRadius = NAN protected
Definition at line 88 of file PHG4InnerHcalDetector.h.
View newest version in sPHENIX GitHub at line 88 of file PHG4InnerHcalDetector.h
Referenced by ConstructMe().
double PHG4InnerHcalDetector::m_EnvelopeOuterRadius = NAN protected
Definition at line 89 of file PHG4InnerHcalDetector.h.
View newest version in sPHENIX GitHub at line 89 of file PHG4InnerHcalDetector.h
Referenced by ConstructMe().
double PHG4InnerHcalDetector::m_EnvelopeZ = NAN protected
Definition at line 90 of file PHG4InnerHcalDetector.h.
View newest version in sPHENIX GitHub at line 90 of file PHG4InnerHcalDetector.h
Referenced by ConstructMe().
double PHG4InnerHcalDetector::m_InnerRadius = NAN protected
Definition at line 76 of file PHG4InnerHcalDetector.h.
View newest version in sPHENIX GitHub at line 76 of file PHG4InnerHcalDetector.h
Referenced by CheckTiltAngle(), ConsistencyCheck(), ConstructHcalSingleScintillators(), ConstructInnerHcal(), ConstructScintillatorBox(), ConstructSteelPlate(), SetTiltViaNcross(), and ShiftSecantToTangent().
int PHG4InnerHcalDetector::m_Layer = 0 protected
Definition at line 102 of file PHG4InnerHcalDetector.h.
View newest version in sPHENIX GitHub at line 102 of file PHG4InnerHcalDetector.h
Referenced by get_Layer().
int PHG4InnerHcalDetector::m_NumScintiPlates = 0 protected
Definition at line 95 of file PHG4InnerHcalDetector.h.
View newest version in sPHENIX GitHub at line 95 of file PHG4InnerHcalDetector.h
Referenced by ConstructInnerHcal(), ConstructMe(), ConstructScintillatorBox(), ConstructSteelPlate(), and SetTiltViaNcross().
int PHG4InnerHcalDetector::m_NumScintiTilesNeg = 0 protected
Definition at line 97 of file PHG4InnerHcalDetector.h.
View newest version in sPHENIX GitHub at line 97 of file PHG4InnerHcalDetector.h
Referenced by ConstructHcalSingleScintillators(), and PHG4InnerHcalDetector().
int PHG4InnerHcalDetector::m_NumScintiTilesPos = 0 protected
Definition at line 96 of file PHG4InnerHcalDetector.h.
View newest version in sPHENIX GitHub at line 96 of file PHG4InnerHcalDetector.h
Referenced by ConstructHcalSingleScintillators(), and PHG4InnerHcalDetector().
double PHG4InnerHcalDetector::m_OuterRadius = NAN protected
Definition at line 77 of file PHG4InnerHcalDetector.h.
View newest version in sPHENIX GitHub at line 77 of file PHG4InnerHcalDetector.h
Referenced by CheckTiltAngle(), ConsistencyCheck(), ConstructHcalSingleScintillators(), ConstructInnerHcal(), ConstructScintillatorBox(), ConstructSteelPlate(), and SetTiltViaNcross().
PHParameters* PHG4InnerHcalDetector::m_Params = nullptr protected
Definition at line 74 of file PHG4InnerHcalDetector.h.
View newest version in sPHENIX GitHub at line 74 of file PHG4InnerHcalDetector.h
Referenced by AddGeometryNode(), ConstructHcalScintillatorAssembly(), ConstructHcalSingleScintillators(), ConstructInnerHcal(), ConstructMe(), PHG4InnerHcalDetector(), and SetTiltViaNcross().
RawTowerGeomContainer* PHG4InnerHcalDetector::m_RawTowerGeom = nullptr protected
Definition at line 108 of file PHG4InnerHcalDetector.h.
View newest version in sPHENIX GitHub at line 108 of file PHG4InnerHcalDetector.h
Referenced by AddGeometryNode().
double PHG4InnerHcalDetector::m_ScintiInnerGap = NAN protected
Definition at line 84 of file PHG4InnerHcalDetector.h.
View newest version in sPHENIX GitHub at line 84 of file PHG4InnerHcalDetector.h
Referenced by ConsistencyCheck(), and ConstructSteelPlate().
std::string PHG4InnerHcalDetector::m_ScintiLogicNamePrefix protected
Definition at line 107 of file PHG4InnerHcalDetector.h.
View newest version in sPHENIX GitHub at line 107 of file PHG4InnerHcalDetector.h
Referenced by ConstructHcalScintillatorAssembly().
G4AssemblyVolume* PHG4InnerHcalDetector::m_ScintiMotherAssembly = nullptr protected
Definition at line 75 of file PHG4InnerHcalDetector.h.
View newest version in sPHENIX GitHub at line 75 of file PHG4InnerHcalDetector.h
Referenced by ConstructInnerHcal(), ConstructMe(), and ~PHG4InnerHcalDetector().
double PHG4InnerHcalDetector::m_ScintiOuterGap = NAN protected
Definition at line 85 of file PHG4InnerHcalDetector.h.
View newest version in sPHENIX GitHub at line 85 of file PHG4InnerHcalDetector.h
Referenced by ConstructSteelPlate().
double PHG4InnerHcalDetector::m_ScintiOuterRadius = NAN protected
Definition at line 86 of file PHG4InnerHcalDetector.h.
View newest version in sPHENIX GitHub at line 86 of file PHG4InnerHcalDetector.h
Referenced by ConsistencyCheck(), and ConstructScintillatorBox().
std::map<G4VPhysicalVolume *, std::pair<int, int> > PHG4InnerHcalDetector::m_ScintiTilePhysVolMap protected
Definition at line 105 of file PHG4InnerHcalDetector.h.
View newest version in sPHENIX GitHub at line 105 of file PHG4InnerHcalDetector.h
Referenced by ConstructMe(), GetLayerTowerId(), and IsInInnerHcal().
std::vector<G4VSolid *> PHG4InnerHcalDetector::m_ScintiTilesVec protected
Definition at line 106 of file PHG4InnerHcalDetector.h.
View newest version in sPHENIX GitHub at line 106 of file PHG4InnerHcalDetector.h
Referenced by ConstructHcalScintillatorAssembly(), ConstructHcalSingleScintillators(), and PHG4InnerHcalDetector().
double PHG4InnerHcalDetector::m_ScintiTileThickness = NAN protected
Definition at line 83 of file PHG4InnerHcalDetector.h.
View newest version in sPHENIX GitHub at line 83 of file PHG4InnerHcalDetector.h
Referenced by ConsistencyCheck(), ConstructHcalSingleScintillators(), and ConstructScintillatorBox().
double PHG4InnerHcalDetector::m_ScintiTileX = NAN protected
Definition at line 79 of file PHG4InnerHcalDetector.h.
View newest version in sPHENIX GitHub at line 79 of file PHG4InnerHcalDetector.h
Referenced by ConstructHcalSingleScintillators(), ConstructInnerHcal(), and ConstructScintillatorBox().
double PHG4InnerHcalDetector::m_ScintiTileXLower = NAN protected
Definition at line 80 of file PHG4InnerHcalDetector.h.
View newest version in sPHENIX GitHub at line 80 of file PHG4InnerHcalDetector.h
Referenced by ConstructInnerHcal(), and ConstructScintillatorBox().
double PHG4InnerHcalDetector::m_ScintiTileXUpper = NAN protected
Definition at line 81 of file PHG4InnerHcalDetector.h.
View newest version in sPHENIX GitHub at line 81 of file PHG4InnerHcalDetector.h
Referenced by ConstructInnerHcal(), and ConstructScintillatorBox().
double PHG4InnerHcalDetector::m_ScintiTileZ = NAN protected
Definition at line 82 of file PHG4InnerHcalDetector.h.
View newest version in sPHENIX GitHub at line 82 of file PHG4InnerHcalDetector.h
Referenced by ConstructScintillatorBox().
double PHG4InnerHcalDetector::m_SizeZ = NAN protected
Definition at line 78 of file PHG4InnerHcalDetector.h.
View newest version in sPHENIX GitHub at line 78 of file PHG4InnerHcalDetector.h
Referenced by ConstructSteelPlate().
std::set<G4VPhysicalVolume *> PHG4InnerHcalDetector::m_SteelAbsorberPhysVolSet protected
Definition at line 104 of file PHG4InnerHcalDetector.h.
View newest version in sPHENIX GitHub at line 104 of file PHG4InnerHcalDetector.h
Referenced by ConstructInnerHcal(), and IsInInnerHcal().
std::string PHG4InnerHcalDetector::m_SuperDetector protected
Definition at line 103 of file PHG4InnerHcalDetector.h.
View newest version in sPHENIX GitHub at line 103 of file PHG4InnerHcalDetector.h
Referenced by AddGeometryNode(), and SuperDetector().
double PHG4InnerHcalDetector::m_TiltAngle = NAN protected
Definition at line 87 of file PHG4InnerHcalDetector.h.
View newest version in sPHENIX GitHub at line 87 of file PHG4InnerHcalDetector.h
Referenced by CheckTiltAngle(), ConstructInnerHcal(), ConstructScintillatorBox(), ConstructSteelPlate(), and SetTiltViaNcross().
std::string PHG4InnerHcalDetector::m_TowerGeomNodeName protected
Definition at line 109 of file PHG4InnerHcalDetector.h.
View newest version in sPHENIX GitHub at line 109 of file PHG4InnerHcalDetector.h
Referenced by AddGeometryNode().
double PHG4InnerHcalDetector::m_VolumeEnvelope = NAN protected
Definition at line 91 of file PHG4InnerHcalDetector.h.
View newest version in sPHENIX GitHub at line 91 of file PHG4InnerHcalDetector.h
Referenced by ConstructMe(), and Print().
double PHG4InnerHcalDetector::m_VolumeScintillator = NAN protected
Definition at line 93 of file PHG4InnerHcalDetector.h.
View newest version in sPHENIX GitHub at line 93 of file PHG4InnerHcalDetector.h
Referenced by ConstructScintillatorBox(), and Print().
double PHG4InnerHcalDetector::m_VolumeSteel = NAN protected
Definition at line 92 of file PHG4InnerHcalDetector.h.
View newest version in sPHENIX GitHub at line 92 of file PHG4InnerHcalDetector.h
Referenced by ConstructSteelPlate(), and Print().
The documentation for this class was generated from the following files:
coresoftware/blob/master/simulation/g4simulation/g4detectors/PHG4InnerHcalDetector.h
coresoftware/blob/master/simulation/g4simulation/g4detectors/PHG4InnerHcalDetector.cc