Analysis Software: ActsExamples::TrackFindingFromPrototrackAlgorithm Exception Reference
ActsExamples::TrackFindingFromPrototrackAlgorithm Exception Reference final
#include <acts/blob/sPHENIX/Examples/Algorithms/TrackFindingExaTrkX/include/ActsExamples/TrackFindingExaTrkX/TrackFindingFromPrototrackAlgorithm.hpp>
Classes
struct Config
Public Member Functions
TrackFindingFromPrototrackAlgorithm (Config cfg, Acts::Logging::Level lvl)
virtual ~TrackFindingFromPrototrackAlgorithm ()
ActsExamples::ProcessCode execute (const ActsExamples::AlgorithmContext &ctx) const final
ActsExamples::ProcessCode finalize () override
Finalize the algorithm.
const Config & config () const
Public Member Functions inherited from ActsExamples::IAlgorithm
IAlgorithm (std::string name, Acts::Logging::Level level=Acts::Logging::INFO)
std::string name () const override
The algorithm name.
ProcessCode internalExecute (const AlgorithmContext &context) final
ProcessCode initialize () override
Initialize the algorithm.
ProcessCode finalize () override
Finalize the algorithm.
Private Attributes
Config m_cfg
std::mutex m_mutex
std::vector< unsigned > m_nTracksPerSeeds
ReadDataHandle
< ProtoTrackContainer > m_inputProtoTracks
ReadDataHandle
< MeasurementContainer > m_inputMeasurements
ReadDataHandle
< IndexSourceLinkContainer > m_inputSourceLinks
ReadDataHandle
< TrackParametersContainer > m_inputInitialTrackParameters
WriteDataHandle
< ConstTrackContainer > m_outputTracks {this, "OutputTracks"}
Additional Inherited Members
Protected Member Functions inherited from ActsExamples::IAlgorithm
const Acts::Logger & logger () const
Detailed Description
This algorithm starts a CKF of from a given prototrack. This means: If for any given surface there exists a measurements in the prototrack, this measurement is returned. Otherwise (typically after the end of the prototrack), the algorithm falls back to providing all possible measurements on the surface.
Definition at line 40 of file TrackFindingFromPrototrackAlgorithm.hpp.
View newest version in sPHENIX GitHub at line 40 of file TrackFindingFromPrototrackAlgorithm.hpp
Constructor & Destructor Documentation
ActsExamples::TrackFindingFromPrototrackAlgorithm::TrackFindingFromPrototrackAlgorithm (Config cfg, Acts::Logging::Level lvl)
Constructor of the track finding algorithm
Parameters
cfg is the config struct to configure the algorithm
level is the logging level
Definition at line 54 of file TrackFindingFromPrototrackAlgorithm.cpp.
View newest version in sPHENIX GitHub at line 54 of file TrackFindingFromPrototrackAlgorithm.cpp
References ActsExamples::WriteDataHandle< T >::initialize(), ActsExamples::ReadDataHandle< T >::initialize(), ActsExamples::TrackFindingFromPrototrackAlgorithm::Config::inputInitialTrackParameters, ActsExamples::TrackFindingFromPrototrackAlgorithm::Config::inputMeasurements, ActsExamples::TrackFindingFromPrototrackAlgorithm::Config::inputProtoTracks, ActsExamples::TrackFindingFromPrototrackAlgorithm::Config::inputSourceLinks, m_cfg, m_inputInitialTrackParameters, m_inputMeasurements, m_inputProtoTracks, m_inputSourceLinks, m_outputTracks, and ActsExamples::TrackFindingFromPrototrackAlgorithm::Config::outputTracks.
virtual ActsExamples::TrackFindingFromPrototrackAlgorithm::~TrackFindingFromPrototrackAlgorithm () inline virtual
Definition at line 80 of file TrackFindingFromPrototrackAlgorithm.hpp.
View newest version in sPHENIX GitHub at line 80 of file TrackFindingFromPrototrackAlgorithm.hpp
Member Function Documentation
const Config& ActsExamples::TrackFindingFromPrototrackAlgorithm::config () const inline
Definition at line 91 of file TrackFindingFromPrototrackAlgorithm.hpp.
View newest version in sPHENIX GitHub at line 91 of file TrackFindingFromPrototrackAlgorithm.hpp
References m_cfg.
ActsExamples::ProcessCode ActsExamples::TrackFindingFromPrototrackAlgorithm::execute (const ActsExamples::AlgorithmContext & ctx) const final virtual
Filter the measurements
Parameters
ctx is the algorithm context that holds event-wise information
Returns
a process code to steer the algorithm flow
Implements ActsExamples::IAlgorithm.
Definition at line 64 of file TrackFindingFromPrototrackAlgorithm.cpp.
View newest version in sPHENIX GitHub at line 64 of file TrackFindingFromPrototrackAlgorithm.cpp
References ACTS_DEBUG, ACTS_FATAL, ACTS_INFO, ACTS_WARNING, ActsExamples::AlgorithmContext::calibContext, ActsExamples::MeasurementCalibratorAdapter::calibrate(), Acts::CombinatorialKalmanFilterExtensions< traj_t >::calibrator, Acts::Logger::clone(), ActsExamples::AlgorithmContext::eventNumber, conf::extensions, ActsExamples::TrackFindingFromPrototrackAlgorithm::Config::findTracks, ActsExamples::AlgorithmContext::geoContext, i, it, ActsExamples::IAlgorithm::logger(), m_cfg, m_inputInitialTrackParameters, m_inputMeasurements, m_inputProtoTracks, m_inputSourceLinks, m_mutex, m_nTracksPerSeeds, m_outputTracks, ActsExamples::AlgorithmContext::magFieldContext, Acts::PropagatorPlainOptions::maxSteps, Acts::CombinatorialKalmanFilterExtensions< traj_t >::measurementSelector, ActsExamples::TrackFindingFromPrototrackAlgorithm::Config::measurementSelectorCfg, testing::internal::move(), ckf::options, pSurface, Acts::CombinatorialKalmanFilterExtensions< traj_t >::smoother, SUCCESS, tracks(), and Acts::CombinatorialKalmanFilterExtensions< traj_t >::updater.
ActsExamples::ProcessCode ActsExamples::TrackFindingFromPrototrackAlgorithm::finalize () override virtual
Finalize the algorithm.
Implements ActsExamples::SequenceElement.
Definition at line 202 of file TrackFindingFromPrototrackAlgorithm.cpp.
View newest version in sPHENIX GitHub at line 202 of file TrackFindingFromPrototrackAlgorithm.cpp
References ACTS_INFO, assert, distance(), m_nTracksPerSeeds, mean(), sum(), and testSigmaEff::v.
Member Data Documentation
Config ActsExamples::TrackFindingFromPrototrackAlgorithm::m_cfg private
Definition at line 94 of file TrackFindingFromPrototrackAlgorithm.hpp.
View newest version in sPHENIX GitHub at line 94 of file TrackFindingFromPrototrackAlgorithm.hpp
Referenced by config(), execute(), and TrackFindingFromPrototrackAlgorithm().
ReadDataHandle<TrackParametersContainer> ActsExamples::TrackFindingFromPrototrackAlgorithm::m_inputInitialTrackParameters private
Initial value:
{
      this, "InputInitialTrackParameters"}
Definition at line 105 of file TrackFindingFromPrototrackAlgorithm.hpp.
View newest version in sPHENIX GitHub at line 105 of file TrackFindingFromPrototrackAlgorithm.hpp
Referenced by execute(), and TrackFindingFromPrototrackAlgorithm().
ReadDataHandle<MeasurementContainer> ActsExamples::TrackFindingFromPrototrackAlgorithm::m_inputMeasurements private
Initial value:
{this,
                                                           "InputMeasurements"}
Definition at line 101 of file TrackFindingFromPrototrackAlgorithm.hpp.
View newest version in sPHENIX GitHub at line 101 of file TrackFindingFromPrototrackAlgorithm.hpp
Referenced by execute(), and TrackFindingFromPrototrackAlgorithm().
ReadDataHandle<ProtoTrackContainer> ActsExamples::TrackFindingFromPrototrackAlgorithm::m_inputProtoTracks private
Initial value:
{this,
                                                         "InputProtoTracks"}
Definition at line 99 of file TrackFindingFromPrototrackAlgorithm.hpp.
View newest version in sPHENIX GitHub at line 99 of file TrackFindingFromPrototrackAlgorithm.hpp
Referenced by execute(), and TrackFindingFromPrototrackAlgorithm().
ReadDataHandle<IndexSourceLinkContainer> ActsExamples::TrackFindingFromPrototrackAlgorithm::m_inputSourceLinks private
Initial value:
{
      this, "InputSourceLinks"}
Definition at line 103 of file TrackFindingFromPrototrackAlgorithm.hpp.
View newest version in sPHENIX GitHub at line 103 of file TrackFindingFromPrototrackAlgorithm.hpp
Referenced by execute(), and TrackFindingFromPrototrackAlgorithm().
std::mutex ActsExamples::TrackFindingFromPrototrackAlgorithm::m_mutex mutable private
Definition at line 96 of file TrackFindingFromPrototrackAlgorithm.hpp.
View newest version in sPHENIX GitHub at line 96 of file TrackFindingFromPrototrackAlgorithm.hpp
Referenced by execute().
std::vector<unsigned> ActsExamples::TrackFindingFromPrototrackAlgorithm::m_nTracksPerSeeds mutable private
Definition at line 97 of file TrackFindingFromPrototrackAlgorithm.hpp.
View newest version in sPHENIX GitHub at line 97 of file TrackFindingFromPrototrackAlgorithm.hpp
Referenced by execute(), and finalize().
WriteDataHandle<ConstTrackContainer> ActsExamples::TrackFindingFromPrototrackAlgorithm::m_outputTracks {this, "OutputTracks"} private
Definition at line 108 of file TrackFindingFromPrototrackAlgorithm.hpp.
View newest version in sPHENIX GitHub at line 108 of file TrackFindingFromPrototrackAlgorithm.hpp
Referenced by execute(), and TrackFindingFromPrototrackAlgorithm().
The documentation for this exception was generated from the following files:
acts/blob/sPHENIX/Examples/Algorithms/TrackFindingExaTrkX/include/ActsExamples/TrackFindingExaTrkX/TrackFindingFromPrototrackAlgorithm.hpp
acts/blob/sPHENIX/Examples/Algorithms/TrackFindingExaTrkX/src/TrackFindingFromPrototrackAlgorithm.cpp