Analysis Software: PHG4TrackFastSimEval Class Reference
PHG4TrackFastSimEval Class Reference
#include <coresoftware/blob/master/simulation/g4simulation/g4trackfastsim/PHG4TrackFastSimEval.h>
Public Member Functions
PHG4TrackFastSimEval (const std::string &name="PHG4TrackFastSimEval", const std::string &filename="g4eval.root", const std::string &trackmapname="SvtxTrackMap")
int Init (PHCompositeNode *) override
int InitRun (PHCompositeNode *) override
int process_event (PHCompositeNode *) override
int End (PHCompositeNode *) override
Called at the end of all processing.
void set_filename (const std::string &file)
void set_trackmapname (const std::string &name)
void reset_variables ()
void AddProjection (const std::string &name)
Public Member Functions inherited from SubsysReco
~SubsysReco () override
virtual int EndRun (const int)
Called at the end of each run.
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
void Print (const std::string &="ALL") const override
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Private Member Functions
void fill_track_tree (PHCompositeNode *)
void fill_vertex_tree (PHCompositeNode *)
int GetNodes (PHCompositeNode *)
Private Attributes
PHG4TruthInfoContainer * m_TruthInfoContainer
SvtxTrackMap * m_TrackMap
SvtxVertexMap * m_VertexMap
TTree * m_TracksEvalTree
TTree * m_VertexEvalTree
TH2D * m_H2D_DeltaMomVsTruthMom
TH2D * m_H2D_DeltaMomVsTruthEta
int m_EventCounter
int m_TTree_Event
int m_TTree_gTrackID
int m_TTree_gFlavor
float m_TTree_gpx
float m_TTree_gpy
float m_TTree_gpz
float m_TTree_gvx
float m_TTree_gvy
float m_TTree_gvz
float m_TTree_gvt
int m_TTree_TrackID
int m_TTree_Charge
int m_TTree_nHits
float m_TTree_px
float m_TTree_py
float m_TTree_pz
float m_TTree_pcax
float m_TTree_pcay
float m_TTree_pcaz
float m_TTree_dca2d
std::map< int, int > m_TTree_HitContainerID_nHits_map
float m_TTree_vx
float m_TTree_vy
float m_TTree_vz
float m_TTree_DeltaVx
float m_TTree_DeltaVy
float m_TTree_DeltaVz
int m_TTree_nTracks
int m_TTree_nFromTruth
std::string m_OutFileName
std::string m_TrackMapName
std::map< std::string,
unsigned int > m_ProjectionNameMap
std::vector< std::vector< float > > m_TTree_proj_vec
std::vector< std::vector< float > > m_TTree_proj_p_vec
std::vector< std::vector< float > > m_TTree_ref_vec
std::vector< std::vector< float > > m_TTree_ref_p_vec
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = std::numeric_limits<int>::max() - 10
}
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Detailed Description
Definition at line 28 of file PHG4TrackFastSimEval.h.
View newest version in sPHENIX GitHub at line 28 of file PHG4TrackFastSimEval.h
Constructor & Destructor Documentation
PHG4TrackFastSimEval::PHG4TrackFastSimEval (const std::string & name = "PHG4TrackFastSimEval", const std::string & filename = "g4eval.root", const std::string & trackmapname = "SvtxTrackMap")
Definition at line 55 of file PHG4TrackFastSimEval.cc.
View newest version in sPHENIX GitHub at line 55 of file PHG4TrackFastSimEval.cc
References reset_variables().
Member Function Documentation
void PHG4TrackFastSimEval::AddProjection (const std::string & name)
Definition at line 622 of file PHG4TrackFastSimEval.cc.
View newest version in sPHENIX GitHub at line 622 of file PHG4TrackFastSimEval.cc
References m_ProjectionNameMap, m_TTree_proj_p_vec, m_TTree_proj_vec, m_TTree_ref_p_vec, and m_TTree_ref_vec.
Referenced by Fun4All_G4_Momentum_Projection(), Fun4All_G4_Momentum_Projection_Calorimeters(), and Fun4All_G4_Momentum_Projection_Detectors().
int PHG4TrackFastSimEval::End (PHCompositeNode *) override virtual
Called at the end of all processing.
Reimplemented from SubsysReco.
Definition at line 249 of file PHG4TrackFastSimEval.cc.
View newest version in sPHENIX GitHub at line 249 of file PHG4TrackFastSimEval.cc
References PHTFileServer::cd(), Fun4AllReturnCodes::EVENT_OK, PHTFileServer::get(), m_H2D_DeltaMomVsTruthEta, m_H2D_DeltaMomVsTruthMom, m_OutFileName, m_TracksEvalTree, and m_VertexEvalTree.
void PHG4TrackFastSimEval::fill_track_tree (PHCompositeNode * topNode) private
Definition at line 268 of file PHG4TrackFastSimEval.cc.
View newest version in sPHENIX GitHub at line 268 of file PHG4TrackFastSimEval.cc
References assert, SvtxTrackMap::begin(), SvtxTrack_v1::begin_states(), SvtxTrackMap::end(), SvtxTrack_v1::end_states(), SvtxTrack::g4hit_ids(), SvtxTrack_v1::get_charge(), SvtxTrack_v1::get_dca2d(), SvtxTrack_v1::get_id(), PHG4Particle::get_pid(), PHG4Particle::get_px(), SvtxTrack_v1::get_px(), PHG4Particle::get_py(), SvtxTrack_v1::get_py(), PHG4Particle::get_pz(), SvtxTrack_v1::get_pz(), PHG4VtxPoint::get_t(), PHG4Particle::get_track_id(), SvtxTrack_FastSim::get_truth_track_id(), PHG4Particle::get_vtx_id(), PHG4VtxPoint::get_x(), SvtxTrack_v1::get_x(), PHG4VtxPoint::get_y(), SvtxTrack_v1::get_y(), PHG4VtxPoint::get_z(), SvtxTrack_v1::get_z(), PHG4HitContainer::getHits(), PHG4TruthInfoContainer::GetPrimaryParticleRange(), PHG4TruthInfoContainer::GetVtx(), i, SvtxTrack_FastSim::identify(), LogDebug, LogError, m_EventCounter, m_H2D_DeltaMomVsTruthEta, m_H2D_DeltaMomVsTruthMom, m_ProjectionNameMap, m_TrackMap, m_TracksEvalTree, m_TruthInfoContainer, m_TTree_Charge, m_TTree_dca2d, m_TTree_Event, m_TTree_gFlavor, m_TTree_gpx, m_TTree_gpy, m_TTree_gpz, m_TTree_gTrackID, m_TTree_gvt, m_TTree_gvx, m_TTree_gvy, m_TTree_gvz, m_TTree_HitContainerID_nHits_map, m_TTree_nHits, m_TTree_pcax, m_TTree_pcay, m_TTree_pcaz, m_TTree_proj_p_vec, m_TTree_proj_vec, m_TTree_px, m_TTree_py, m_TTree_pz, m_TTree_ref_p_vec, m_TTree_ref_vec, m_TTree_TrackID, reset_variables(), SvtxTrackMap::size(), PHG4HitContainer::size(), SvtxTrack_v1::size_clusters(), and Fun4AllBase::Verbosity().
Referenced by process_event().
void PHG4TrackFastSimEval::fill_vertex_tree (PHCompositeNode *) private
Definition at line 443 of file PHG4TrackFastSimEval.cc.
View newest version in sPHENIX GitHub at line 443 of file PHG4TrackFastSimEval.cc
References assert, SvtxVertexMap::begin(), SvtxVertex::begin_tracks(), SvtxTrackMap::end(), SvtxVertexMap::end(), SvtxVertex::end_tracks(), SvtxTrackMap::find(), SvtxVertex::get_error(), SvtxVertex::get_id(), SvtxTrack_FastSim::get_truth_track_id(), PHG4Particle::get_vtx_id(), SvtxVertex::get_x(), SvtxVertex::get_y(), SvtxVertex::get_z(), PHG4TruthInfoContainer::GetParticle(), PHG4TruthInfoContainer::GetVtx(), LogDebug, LogError, m_EventCounter, m_TrackMap, m_TruthInfoContainer, m_TTree_DeltaVx, m_TTree_DeltaVy, m_TTree_DeltaVz, m_TTree_Event, m_TTree_gTrackID, m_TTree_gvt, m_TTree_gvx, m_TTree_gvy, m_TTree_gvz, m_TTree_nFromTruth, m_TTree_nTracks, m_TTree_TrackID, m_TTree_vx, m_TTree_vy, m_TTree_vz, m_VertexEvalTree, m_VertexMap, reset_variables(), and SvtxVertex::size_tracks().
Referenced by process_event().
int PHG4TrackFastSimEval::GetNodes (PHCompositeNode * topNode) private
Definition at line 587 of file PHG4TrackFastSimEval.cc.
View newest version in sPHENIX GitHub at line 587 of file PHG4TrackFastSimEval.cc
References Fun4AllReturnCodes::ABORTEVENT, Fun4AllReturnCodes::EVENT_OK, m_EventCounter, m_TrackMap, m_TrackMapName, m_TruthInfoContainer, m_VertexMap, PHWHERE, and Fun4AllBase::Verbosity().
Referenced by process_event().
int PHG4TrackFastSimEval::Init (PHCompositeNode *) override virtual
Called during initialization. Typically this is where you can book histograms, and e.g. register them to Fun4AllServer (so they can be output to file using Fun4AllServer::dumpHistos() method).
Reimplemented from SubsysReco.
Definition at line 75 of file PHG4TrackFastSimEval.cc.
View newest version in sPHENIX GitHub at line 75 of file PHG4TrackFastSimEval.cc
References Fun4AllReturnCodes::EVENT_OK.
int PHG4TrackFastSimEval::InitRun (PHCompositeNode *) override virtual
Called for first event when run number is known. Typically this is where you may want to fetch data from database, because you know the run number.
Reimplemented from SubsysReco.
Definition at line 84 of file PHG4TrackFastSimEval.cc.
View newest version in sPHENIX GitHub at line 84 of file PHG4TrackFastSimEval.cc
References Fun4AllReturnCodes::EVENT_OK, PHParameters::FillFrom(), PHTFileServer::get(), PHParameters::get_all_int_params(), i, m_H2D_DeltaMomVsTruthEta, m_H2D_DeltaMomVsTruthMom, m_OutFileName, m_ProjectionNameMap, m_TracksEvalTree, m_TTree_Charge, m_TTree_dca2d, m_TTree_DeltaVx, m_TTree_DeltaVy, m_TTree_DeltaVz, m_TTree_Event, m_TTree_gFlavor, m_TTree_gpx, m_TTree_gpy, m_TTree_gpz, m_TTree_gTrackID, m_TTree_gvt, m_TTree_gvx, m_TTree_gvy, m_TTree_gvz, m_TTree_HitContainerID_nHits_map, m_TTree_nFromTruth, m_TTree_nHits, m_TTree_nTracks, m_TTree_pcax, m_TTree_pcay, m_TTree_pcaz, m_TTree_proj_p_vec, m_TTree_proj_vec, m_TTree_px, m_TTree_py, m_TTree_pz, m_TTree_ref_p_vec, m_TTree_ref_vec, m_TTree_TrackID, m_TTree_vx, m_TTree_vy, m_TTree_vz, m_VertexEvalTree, PHTFileServer::open(), PHWHERE, PHParameters::Print(), Fun4AllBase::Verbosity(), and xyzt.
int PHG4TrackFastSimEval::process_event (PHCompositeNode *) override virtual
Called for each event. This is where you do the real work.
Reimplemented from SubsysReco.
Definition at line 228 of file PHG4TrackFastSimEval.cc.
View newest version in sPHENIX GitHub at line 228 of file PHG4TrackFastSimEval.cc
References Fun4AllReturnCodes::EVENT_OK, fill_track_tree(), fill_vertex_tree(), GetNodes(), m_EventCounter, PHWHERE, and Fun4AllBase::Verbosity().
void PHG4TrackFastSimEval::reset_variables ()
Definition at line 540 of file PHG4TrackFastSimEval.cc.
View newest version in sPHENIX GitHub at line 540 of file PHG4TrackFastSimEval.cc
References m_TTree_Charge, m_TTree_dca2d, m_TTree_DeltaVx, m_TTree_DeltaVy, m_TTree_DeltaVz, m_TTree_Event, m_TTree_gFlavor, m_TTree_gpx, m_TTree_gpy, m_TTree_gpz, m_TTree_gTrackID, m_TTree_gvt, m_TTree_gvx, m_TTree_gvy, m_TTree_gvz, m_TTree_HitContainerID_nHits_map, m_TTree_nFromTruth, m_TTree_nHits, m_TTree_nTracks, m_TTree_pcax, m_TTree_pcay, m_TTree_pcaz, m_TTree_proj_p_vec, m_TTree_proj_vec, m_TTree_px, m_TTree_py, m_TTree_pz, m_TTree_ref_p_vec, m_TTree_ref_vec, m_TTree_TrackID, m_TTree_vx, m_TTree_vy, and m_TTree_vz.
Referenced by fill_track_tree(), fill_vertex_tree(), and PHG4TrackFastSimEval().
void PHG4TrackFastSimEval::set_filename (const std::string & file) inline
Definition at line 49 of file PHG4TrackFastSimEval.h.
View newest version in sPHENIX GitHub at line 49 of file PHG4TrackFastSimEval.h
References file, and m_OutFileName.
Referenced by Fun4All_G4_Momentum(), Fun4All_G4_Momentum_Projection(), Fun4All_G4_Momentum_Projection_Calorimeters(), and Fun4All_G4_Momentum_Projection_Detectors().
void PHG4TrackFastSimEval::set_trackmapname (const std::string & name) inline
Definition at line 55 of file PHG4TrackFastSimEval.h.
View newest version in sPHENIX GitHub at line 55 of file PHG4TrackFastSimEval.h
References m_TrackMapName, and perf_headwind::name.
Member Data Documentation
int PHG4TrackFastSimEval::m_EventCounter private
Definition at line 86 of file PHG4TrackFastSimEval.h.
View newest version in sPHENIX GitHub at line 86 of file PHG4TrackFastSimEval.h
Referenced by fill_track_tree(), fill_vertex_tree(), GetNodes(), and process_event().
TH2D* PHG4TrackFastSimEval::m_H2D_DeltaMomVsTruthEta private
Definition at line 83 of file PHG4TrackFastSimEval.h.
View newest version in sPHENIX GitHub at line 83 of file PHG4TrackFastSimEval.h
Referenced by End(), fill_track_tree(), and InitRun().
TH2D* PHG4TrackFastSimEval::m_H2D_DeltaMomVsTruthMom private
Definition at line 82 of file PHG4TrackFastSimEval.h.
View newest version in sPHENIX GitHub at line 82 of file PHG4TrackFastSimEval.h
Referenced by End(), fill_track_tree(), and InitRun().
std::string PHG4TrackFastSimEval::m_OutFileName private
Definition at line 126 of file PHG4TrackFastSimEval.h.
View newest version in sPHENIX GitHub at line 126 of file PHG4TrackFastSimEval.h
Referenced by End(), InitRun(), and set_filename().
std::map<std::string, unsigned int> PHG4TrackFastSimEval::m_ProjectionNameMap private
Definition at line 132 of file PHG4TrackFastSimEval.h.
View newest version in sPHENIX GitHub at line 132 of file PHG4TrackFastSimEval.h
Referenced by AddProjection(), fill_track_tree(), and InitRun().
SvtxTrackMap* PHG4TrackFastSimEval::m_TrackMap private
Definition at line 74 of file PHG4TrackFastSimEval.h.
View newest version in sPHENIX GitHub at line 74 of file PHG4TrackFastSimEval.h
Referenced by fill_track_tree(), fill_vertex_tree(), and GetNodes().
std::string PHG4TrackFastSimEval::m_TrackMapName private
Definition at line 129 of file PHG4TrackFastSimEval.h.
View newest version in sPHENIX GitHub at line 129 of file PHG4TrackFastSimEval.h
Referenced by GetNodes(), and set_trackmapname().
TTree* PHG4TrackFastSimEval::m_TracksEvalTree private
Definition at line 78 of file PHG4TrackFastSimEval.h.
View newest version in sPHENIX GitHub at line 78 of file PHG4TrackFastSimEval.h
Referenced by End(), fill_track_tree(), and InitRun().
PHG4TruthInfoContainer* PHG4TrackFastSimEval::m_TruthInfoContainer private
Definition at line 73 of file PHG4TrackFastSimEval.h.
View newest version in sPHENIX GitHub at line 73 of file PHG4TrackFastSimEval.h
Referenced by fill_track_tree(), fill_vertex_tree(), and GetNodes().
int PHG4TrackFastSimEval::m_TTree_Charge private
Definition at line 103 of file PHG4TrackFastSimEval.h.
View newest version in sPHENIX GitHub at line 103 of file PHG4TrackFastSimEval.h
Referenced by fill_track_tree(), InitRun(), and reset_variables().
float PHG4TrackFastSimEval::m_TTree_dca2d private
Definition at line 111 of file PHG4TrackFastSimEval.h.
View newest version in sPHENIX GitHub at line 111 of file PHG4TrackFastSimEval.h
Referenced by fill_track_tree(), InitRun(), and reset_variables().
float PHG4TrackFastSimEval::m_TTree_DeltaVx private
Definition at line 119 of file PHG4TrackFastSimEval.h.
View newest version in sPHENIX GitHub at line 119 of file PHG4TrackFastSimEval.h
Referenced by fill_vertex_tree(), InitRun(), and reset_variables().
float PHG4TrackFastSimEval::m_TTree_DeltaVy private
Definition at line 120 of file PHG4TrackFastSimEval.h.
View newest version in sPHENIX GitHub at line 120 of file PHG4TrackFastSimEval.h
Referenced by fill_vertex_tree(), InitRun(), and reset_variables().
float PHG4TrackFastSimEval::m_TTree_DeltaVz private
Definition at line 121 of file PHG4TrackFastSimEval.h.
View newest version in sPHENIX GitHub at line 121 of file PHG4TrackFastSimEval.h
Referenced by fill_vertex_tree(), InitRun(), and reset_variables().
int PHG4TrackFastSimEval::m_TTree_Event private
Definition at line 89 of file PHG4TrackFastSimEval.h.
View newest version in sPHENIX GitHub at line 89 of file PHG4TrackFastSimEval.h
Referenced by fill_track_tree(), fill_vertex_tree(), InitRun(), and reset_variables().
int PHG4TrackFastSimEval::m_TTree_gFlavor private
Definition at line 92 of file PHG4TrackFastSimEval.h.
View newest version in sPHENIX GitHub at line 92 of file PHG4TrackFastSimEval.h
Referenced by fill_track_tree(), InitRun(), and reset_variables().
float PHG4TrackFastSimEval::m_TTree_gpx private
Definition at line 93 of file PHG4TrackFastSimEval.h.
View newest version in sPHENIX GitHub at line 93 of file PHG4TrackFastSimEval.h
Referenced by fill_track_tree(), InitRun(), and reset_variables().
float PHG4TrackFastSimEval::m_TTree_gpy private
Definition at line 94 of file PHG4TrackFastSimEval.h.
View newest version in sPHENIX GitHub at line 94 of file PHG4TrackFastSimEval.h
Referenced by fill_track_tree(), InitRun(), and reset_variables().
float PHG4TrackFastSimEval::m_TTree_gpz private
Definition at line 95 of file PHG4TrackFastSimEval.h.
View newest version in sPHENIX GitHub at line 95 of file PHG4TrackFastSimEval.h
Referenced by fill_track_tree(), InitRun(), and reset_variables().
int PHG4TrackFastSimEval::m_TTree_gTrackID private
Definition at line 91 of file PHG4TrackFastSimEval.h.
View newest version in sPHENIX GitHub at line 91 of file PHG4TrackFastSimEval.h
Referenced by fill_track_tree(), fill_vertex_tree(), InitRun(), and reset_variables().
float PHG4TrackFastSimEval::m_TTree_gvt private
Definition at line 99 of file PHG4TrackFastSimEval.h.
View newest version in sPHENIX GitHub at line 99 of file PHG4TrackFastSimEval.h
Referenced by fill_track_tree(), fill_vertex_tree(), InitRun(), and reset_variables().
float PHG4TrackFastSimEval::m_TTree_gvx private
Definition at line 96 of file PHG4TrackFastSimEval.h.
View newest version in sPHENIX GitHub at line 96 of file PHG4TrackFastSimEval.h
Referenced by fill_track_tree(), fill_vertex_tree(), InitRun(), and reset_variables().
float PHG4TrackFastSimEval::m_TTree_gvy private
Definition at line 97 of file PHG4TrackFastSimEval.h.
View newest version in sPHENIX GitHub at line 97 of file PHG4TrackFastSimEval.h
Referenced by fill_track_tree(), fill_vertex_tree(), InitRun(), and reset_variables().
float PHG4TrackFastSimEval::m_TTree_gvz private
Definition at line 98 of file PHG4TrackFastSimEval.h.
View newest version in sPHENIX GitHub at line 98 of file PHG4TrackFastSimEval.h
Referenced by fill_track_tree(), fill_vertex_tree(), InitRun(), and reset_variables().
std::map<int, int> PHG4TrackFastSimEval::m_TTree_HitContainerID_nHits_map private
Definition at line 113 of file PHG4TrackFastSimEval.h.
View newest version in sPHENIX GitHub at line 113 of file PHG4TrackFastSimEval.h
Referenced by fill_track_tree(), InitRun(), and reset_variables().
int PHG4TrackFastSimEval::m_TTree_nFromTruth private
Definition at line 123 of file PHG4TrackFastSimEval.h.
View newest version in sPHENIX GitHub at line 123 of file PHG4TrackFastSimEval.h
Referenced by fill_vertex_tree(), InitRun(), and reset_variables().
int PHG4TrackFastSimEval::m_TTree_nHits private
Definition at line 104 of file PHG4TrackFastSimEval.h.
View newest version in sPHENIX GitHub at line 104 of file PHG4TrackFastSimEval.h
Referenced by fill_track_tree(), InitRun(), and reset_variables().
int PHG4TrackFastSimEval::m_TTree_nTracks private
Definition at line 122 of file PHG4TrackFastSimEval.h.
View newest version in sPHENIX GitHub at line 122 of file PHG4TrackFastSimEval.h
Referenced by fill_vertex_tree(), InitRun(), and reset_variables().
float PHG4TrackFastSimEval::m_TTree_pcax private
Definition at line 108 of file PHG4TrackFastSimEval.h.
View newest version in sPHENIX GitHub at line 108 of file PHG4TrackFastSimEval.h
Referenced by fill_track_tree(), InitRun(), and reset_variables().
float PHG4TrackFastSimEval::m_TTree_pcay private
Definition at line 109 of file PHG4TrackFastSimEval.h.
View newest version in sPHENIX GitHub at line 109 of file PHG4TrackFastSimEval.h
Referenced by fill_track_tree(), InitRun(), and reset_variables().
float PHG4TrackFastSimEval::m_TTree_pcaz private
Definition at line 110 of file PHG4TrackFastSimEval.h.
View newest version in sPHENIX GitHub at line 110 of file PHG4TrackFastSimEval.h
Referenced by fill_track_tree(), InitRun(), and reset_variables().
std::vector<std::vector<float> > PHG4TrackFastSimEval::m_TTree_proj_p_vec private
Definition at line 135 of file PHG4TrackFastSimEval.h.
View newest version in sPHENIX GitHub at line 135 of file PHG4TrackFastSimEval.h
Referenced by AddProjection(), fill_track_tree(), InitRun(), and reset_variables().
std::vector<std::vector<float> > PHG4TrackFastSimEval::m_TTree_proj_vec private
Definition at line 134 of file PHG4TrackFastSimEval.h.
View newest version in sPHENIX GitHub at line 134 of file PHG4TrackFastSimEval.h
Referenced by AddProjection(), fill_track_tree(), InitRun(), and reset_variables().
float PHG4TrackFastSimEval::m_TTree_px private
Definition at line 105 of file PHG4TrackFastSimEval.h.
View newest version in sPHENIX GitHub at line 105 of file PHG4TrackFastSimEval.h
Referenced by fill_track_tree(), InitRun(), and reset_variables().
float PHG4TrackFastSimEval::m_TTree_py private
Definition at line 106 of file PHG4TrackFastSimEval.h.
View newest version in sPHENIX GitHub at line 106 of file PHG4TrackFastSimEval.h
Referenced by fill_track_tree(), InitRun(), and reset_variables().
float PHG4TrackFastSimEval::m_TTree_pz private
Definition at line 107 of file PHG4TrackFastSimEval.h.
View newest version in sPHENIX GitHub at line 107 of file PHG4TrackFastSimEval.h
Referenced by fill_track_tree(), InitRun(), and reset_variables().
std::vector<std::vector<float> > PHG4TrackFastSimEval::m_TTree_ref_p_vec private
Definition at line 138 of file PHG4TrackFastSimEval.h.
View newest version in sPHENIX GitHub at line 138 of file PHG4TrackFastSimEval.h
Referenced by AddProjection(), fill_track_tree(), InitRun(), and reset_variables().
std::vector<std::vector<float> > PHG4TrackFastSimEval::m_TTree_ref_vec private
Definition at line 137 of file PHG4TrackFastSimEval.h.
View newest version in sPHENIX GitHub at line 137 of file PHG4TrackFastSimEval.h
Referenced by AddProjection(), fill_track_tree(), InitRun(), and reset_variables().
int PHG4TrackFastSimEval::m_TTree_TrackID private
Definition at line 102 of file PHG4TrackFastSimEval.h.
View newest version in sPHENIX GitHub at line 102 of file PHG4TrackFastSimEval.h
Referenced by fill_track_tree(), fill_vertex_tree(), InitRun(), and reset_variables().
float PHG4TrackFastSimEval::m_TTree_vx private
Definition at line 116 of file PHG4TrackFastSimEval.h.
View newest version in sPHENIX GitHub at line 116 of file PHG4TrackFastSimEval.h
Referenced by fill_vertex_tree(), InitRun(), and reset_variables().
float PHG4TrackFastSimEval::m_TTree_vy private
Definition at line 117 of file PHG4TrackFastSimEval.h.
View newest version in sPHENIX GitHub at line 117 of file PHG4TrackFastSimEval.h
Referenced by fill_vertex_tree(), InitRun(), and reset_variables().
float PHG4TrackFastSimEval::m_TTree_vz private
Definition at line 118 of file PHG4TrackFastSimEval.h.
View newest version in sPHENIX GitHub at line 118 of file PHG4TrackFastSimEval.h
Referenced by fill_vertex_tree(), InitRun(), and reset_variables().
TTree* PHG4TrackFastSimEval::m_VertexEvalTree private
Definition at line 79 of file PHG4TrackFastSimEval.h.
View newest version in sPHENIX GitHub at line 79 of file PHG4TrackFastSimEval.h
Referenced by End(), fill_vertex_tree(), and InitRun().
SvtxVertexMap* PHG4TrackFastSimEval::m_VertexMap private
Definition at line 75 of file PHG4TrackFastSimEval.h.
View newest version in sPHENIX GitHub at line 75 of file PHG4TrackFastSimEval.h
Referenced by fill_vertex_tree(), and GetNodes().
The documentation for this class was generated from the following files:
coresoftware/blob/master/simulation/g4simulation/g4trackfastsim/PHG4TrackFastSimEval.h
coresoftware/blob/master/simulation/g4simulation/g4trackfastsim/PHG4TrackFastSimEval.cc