Analysis Software: PHG4CylinderGeom Class Reference
PHG4CylinderGeom Class Reference
#include <coresoftware/blob/master/simulation/g4simulation/g4detectors/PHG4CylinderGeom.h>
Public Member Functions
~PHG4CylinderGeom () override
void identify (std::ostream &os=std::cout) const override
virtual int get_layer () const
virtual double get_radius () const
virtual double get_thickness () const
virtual double get_zmin () const
virtual double get_zmax () const
virtual int get_nscint () const
virtual double get_tiltangle () const
virtual double get_phi_slat_zero () const
virtual void set_layer (const int i)
virtual void set_radius (const double r)
virtual void set_thickness (const double t)
virtual void set_zmin (const double z)
virtual void set_zmax (const double z)
virtual void set_nscint (const int i)
virtual void set_tiltangle (const double i)
virtual void set_phi_slat_zero (const double phi)
virtual void find_segment_center (const int segment_z_bin, const int segment_phi_bin, double location[])
virtual void find_strip_center (const int segment_z_bin, const int segment_phi_bin, const int strip_column, const int strip_index, double location[])
virtual void find_strip_index_values (const int segment_z_bin, const double ypos, const double zpos, int &strip_y_index, int &strip_z_index)
virtual void find_strip_center_local_coords (const int segment_z_bin, const int strip_y_index, const int strip_z_index, double location[])
virtual double get_strip_y_spacing () const
virtual double get_strip_z_spacing () const
virtual double get_strip_tilt () const
virtual int get_N_strip_columns () const
virtual int get_N_strips_per_column () const
virtual int get_N_sensors_in_layer () const
virtual double get_pixel_z () const
virtual double get_pixel_x () const
virtual double get_pixel_thickness () const
virtual void ImportParameters (const PHParameters &param)
load parameters from PHParameters, which interface to Database/XML/ROOT files
Public Member Functions inherited from PHObject
PHObject ()
ctor
~PHObject () override
dtor
virtual PHObject * CloneMe () const
Virtual copy constructor.
virtual PHObject * clone () const final
PHObject * Clone (const char *newname="") const final
void Copy (TObject &object) const final
virtual void Reset ()
Clear Event.
virtual int isValid () const
isValid returns non zero if object contains vailid data
virtual int isValid (const float) const
virtual int isValid (const double) const
virtual int isValid (const int) const
virtual int isValid (const unsigned int) const
virtual int isImplemented (const float f) const
virtual int isImplemented (const double f) const
virtual int isImplemented (const int i) const
virtual int isImplemented (const unsigned int i) const
virtual int Integrate () const
virtual int Integrate (PHObject *obj)
virtual void CopyFrom (const PHObject *obj)
Protected Member Functions
PHG4CylinderGeom ()
Detailed Description
Definition at line 15 of file PHG4CylinderGeom.h.
View newest version in sPHENIX GitHub at line 15 of file PHG4CylinderGeom.h
Constructor & Destructor Documentation
PHG4CylinderGeom::~PHG4CylinderGeom () inline override
Definition at line 19 of file PHG4CylinderGeom.h.
View newest version in sPHENIX GitHub at line 19 of file PHG4CylinderGeom.h
PHG4CylinderGeom::PHG4CylinderGeom () inline protected
Definition at line 63 of file PHG4CylinderGeom.h.
View newest version in sPHENIX GitHub at line 63 of file PHG4CylinderGeom.h
Member Function Documentation
virtual void PHG4CylinderGeom::find_segment_center (const int segment_z_bin, const int segment_phi_bin, double location[]) inline virtual
Reimplemented in CylinderGeomIntt, and PHG4CylinderGeomv4.
Definition at line 42 of file PHG4CylinderGeom.h.
View newest version in sPHENIX GitHub at line 42 of file PHG4CylinderGeom.h
References PHOOL_VIRTUAL_WARN.
Referenced by BDiJetModule::MakeGenFitTrack().
virtual void PHG4CylinderGeom::find_strip_center (const int segment_z_bin, const int segment_phi_bin, const int strip_column, const int strip_index, double location[]) inline virtual
Reimplemented in CylinderGeomIntt, and PHG4CylinderGeomv4.
Definition at line 43 of file PHG4CylinderGeom.h.
View newest version in sPHENIX GitHub at line 43 of file PHG4CylinderGeom.h
References PHOOL_VIRTUAL_WARN.
virtual void PHG4CylinderGeom::find_strip_center_local_coords (const int segment_z_bin, const int strip_y_index, const int strip_z_index, double location[]) inline virtual
Definition at line 45 of file PHG4CylinderGeom.h.
View newest version in sPHENIX GitHub at line 45 of file PHG4CylinderGeom.h
References PHOOL_VIRTUAL_WARN.
virtual void PHG4CylinderGeom::find_strip_index_values (const int segment_z_bin, const double ypos, const double zpos, int & strip_y_index, int & strip_z_index) inline virtual
Reimplemented in CylinderGeomIntt.
Definition at line 44 of file PHG4CylinderGeom.h.
View newest version in sPHENIX GitHub at line 44 of file PHG4CylinderGeom.h
References PHOOL_VIRTUAL_WARN.
virtual int PHG4CylinderGeom::get_layer () const inline virtual
Reimplemented in CylinderGeomIntt, PHG4CylinderGeomv4, CylinderGeomMicromegas, CylinderGeom_Mvtx, and PHG4CylinderGeomv1.
Definition at line 24 of file PHG4CylinderGeom.h.
View newest version in sPHENIX GitHub at line 24 of file PHG4CylinderGeom.h
References PHOOL_VIRTUAL_WARN.
Referenced by PHG4CylinderGeomContainer::AddLayerGeom(), PHInitZVertexing::initialize_geometry(), PHPatternReco::initialize_geometry(), PHHybridSeeding::InitializeGeometry(), PHRTreeSeeding::InitializeGeometry(), PHCASeeding::InitializeGeometry(), PHHoughSeeding::InitializeGeometry(), PHGenFitTrkProp::InitializeGeometry(), and PHG4CylinderCellReco::InitRun().
virtual int PHG4CylinderGeom::get_N_sensors_in_layer () const inline virtual
Reimplemented in PHG4CylinderGeomv4.
Definition at line 53 of file PHG4CylinderGeom.h.
View newest version in sPHENIX GitHub at line 53 of file PHG4CylinderGeom.h
References PHOOL_VIRTUAL_WARN.
virtual int PHG4CylinderGeom::get_N_strip_columns () const inline virtual
Reimplemented in PHG4CylinderGeomv4.
Definition at line 51 of file PHG4CylinderGeom.h.
View newest version in sPHENIX GitHub at line 51 of file PHG4CylinderGeom.h
References PHOOL_VIRTUAL_WARN.
virtual int PHG4CylinderGeom::get_N_strips_per_column () const inline virtual
Reimplemented in PHG4CylinderGeomv4.
Definition at line 52 of file PHG4CylinderGeom.h.
View newest version in sPHENIX GitHub at line 52 of file PHG4CylinderGeom.h
References PHOOL_VIRTUAL_WARN.
virtual int PHG4CylinderGeom::get_nscint () const inline virtual
Reimplemented in PHG4CylinderGeomv2.
Definition at line 29 of file PHG4CylinderGeom.h.
View newest version in sPHENIX GitHub at line 29 of file PHG4CylinderGeom.h
References PHOOL_VIRTUAL_WARN.
virtual double PHG4CylinderGeom::get_phi_slat_zero () const inline virtual
Reimplemented in PHG4CylinderGeomv3.
Definition at line 31 of file PHG4CylinderGeom.h.
View newest version in sPHENIX GitHub at line 31 of file PHG4CylinderGeom.h
References PHOOL_VIRTUAL_WARN.
virtual double PHG4CylinderGeom::get_pixel_thickness () const inline virtual
Reimplemented in CylinderGeom_Mvtx.
Definition at line 57 of file PHG4CylinderGeom.h.
View newest version in sPHENIX GitHub at line 57 of file PHG4CylinderGeom.h
References PHOOL_VIRTUAL_WARN.
virtual double PHG4CylinderGeom::get_pixel_x () const inline virtual
Reimplemented in CylinderGeom_Mvtx.
Definition at line 56 of file PHG4CylinderGeom.h.
View newest version in sPHENIX GitHub at line 56 of file PHG4CylinderGeom.h
References PHOOL_VIRTUAL_WARN.
virtual double PHG4CylinderGeom::get_pixel_z () const inline virtual
Reimplemented in CylinderGeom_Mvtx.
Definition at line 55 of file PHG4CylinderGeom.h.
View newest version in sPHENIX GitHub at line 55 of file PHG4CylinderGeom.h
References PHOOL_VIRTUAL_WARN.
virtual double PHG4CylinderGeom::get_radius () const inline virtual
Reimplemented in CylinderGeomIntt, PHG4CylinderGeomv4, CylinderGeomMicromegas, CylinderGeom_Mvtx, and PHG4CylinderGeomv1.
Definition at line 25 of file PHG4CylinderGeom.h.
View newest version in sPHENIX GitHub at line 25 of file PHG4CylinderGeom.h
References PHOOL_VIRTUAL_WARN.
Referenced by PHInitZVertexing::initialize_geometry(), PHPatternReco::initialize_geometry(), PHHybridSeeding::InitializeGeometry(), PHRTreeSeeding::InitializeGeometry(), PHCASeeding::InitializeGeometry(), PHHoughSeeding::InitializeGeometry(), PHGenFitTrkProp::InitializeGeometry(), PHG4CylinderCellReco::InitRun(), and PHG4GenHit::process_event().
virtual double PHG4CylinderGeom::get_strip_tilt () const inline virtual
Reimplemented in CylinderGeomIntt, and PHG4CylinderGeomv4.
Definition at line 49 of file PHG4CylinderGeom.h.
View newest version in sPHENIX GitHub at line 49 of file PHG4CylinderGeom.h
References PHOOL_VIRTUAL_WARN.
virtual double PHG4CylinderGeom::get_strip_y_spacing () const inline virtual
Reimplemented in CylinderGeomIntt, and PHG4CylinderGeomv4.
Definition at line 47 of file PHG4CylinderGeom.h.
View newest version in sPHENIX GitHub at line 47 of file PHG4CylinderGeom.h
References PHOOL_VIRTUAL_WARN.
virtual double PHG4CylinderGeom::get_strip_z_spacing () const inline virtual
Reimplemented in CylinderGeomIntt, and PHG4CylinderGeomv4.
Definition at line 48 of file PHG4CylinderGeom.h.
View newest version in sPHENIX GitHub at line 48 of file PHG4CylinderGeom.h
References PHOOL_VIRTUAL_WARN.
virtual double PHG4CylinderGeom::get_thickness () const inline virtual
Reimplemented in PHG4CylinderGeomv4, CylinderGeomIntt, CylinderGeomMicromegas, and PHG4CylinderGeomv1.
Definition at line 26 of file PHG4CylinderGeom.h.
View newest version in sPHENIX GitHub at line 26 of file PHG4CylinderGeom.h
References PHOOL_VIRTUAL_WARN.
Referenced by PHInitZVertexing::initialize_geometry(), PHPatternReco::initialize_geometry(), PHHybridSeeding::InitializeGeometry(), PHRTreeSeeding::InitializeGeometry(), PHCASeeding::InitializeGeometry(), PHHoughSeeding::InitializeGeometry(), PHGenFitTrkProp::InitializeGeometry(), PHG4CylinderCellReco::InitRun(), and PHG4GenHit::process_event().
virtual double PHG4CylinderGeom::get_tiltangle () const inline virtual
Reimplemented in PHG4CylinderGeomv3.
Definition at line 30 of file PHG4CylinderGeom.h.
View newest version in sPHENIX GitHub at line 30 of file PHG4CylinderGeom.h
References PHOOL_VIRTUAL_WARN.
virtual double PHG4CylinderGeom::get_zmax () const inline virtual
Reimplemented in CylinderGeomMicromegas, and PHG4CylinderGeomv1.
Definition at line 28 of file PHG4CylinderGeom.h.
View newest version in sPHENIX GitHub at line 28 of file PHG4CylinderGeom.h
References PHOOL_VIRTUAL_WARN.
Referenced by PHG4SpacalDetector::Construct_AzimuthalSeg(), and PHG4CylinderCellReco::InitRun().
virtual double PHG4CylinderGeom::get_zmin () const inline virtual
Reimplemented in CylinderGeomMicromegas, and PHG4CylinderGeomv1.
Definition at line 27 of file PHG4CylinderGeom.h.
View newest version in sPHENIX GitHub at line 27 of file PHG4CylinderGeom.h
References PHOOL_VIRTUAL_WARN.
Referenced by PHG4CylinderCellReco::InitRun().
void PHG4CylinderGeom::identify (std::ostream & os = std::cout) const override virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from PHObject.
Reimplemented in PHG4CylinderGeomv4, PHG4CylinderGeom_Spacalv1, PHG4CylinderGeom_Spacalv2, PHG4CylinderGeom_Spacalv3, PHG4CylinderGeomv1, PHG4CylinderGeomv2, and PHG4CylinderGeomv3.
Definition at line 6 of file PHG4CylinderGeom.cc.
View newest version in sPHENIX GitHub at line 6 of file PHG4CylinderGeom.cc
Referenced by PHInitZVertexing::initialize_geometry().
virtual void PHG4CylinderGeom::ImportParameters (const PHParameters & param) inline virtual
load parameters from PHParameters, which interface to Database/XML/ROOT files
Reimplemented in PHG4CylinderGeom_Spacalv1, PHG4CylinderGeomv1, PHG4CylinderGeom_Spacalv2, PHG4CylinderGeom_Spacalv3, and PHG4CylinderGeomv2.
Definition at line 60 of file PHG4CylinderGeom.h.
View newest version in sPHENIX GitHub at line 60 of file PHG4CylinderGeom.h
References return().
Referenced by PHG4CylinderGeomv1::ImportParameters().
virtual void PHG4CylinderGeom::set_layer (const int i) inline virtual
Reimplemented in CylinderGeomMicromegas, CylinderGeomIntt, PHG4CylinderGeomv4, CylinderGeom_Mvtx, and PHG4CylinderGeomv1.
Definition at line 33 of file PHG4CylinderGeom.h.
View newest version in sPHENIX GitHub at line 33 of file PHG4CylinderGeom.h
References PHOOL_VIRTUAL_WARN.
Referenced by PHG4CylinderGeomContainer::AddLayerGeom().
virtual void PHG4CylinderGeom::set_nscint (const int i) inline virtual
Reimplemented in PHG4CylinderGeomv2.
Definition at line 38 of file PHG4CylinderGeom.h.
View newest version in sPHENIX GitHub at line 38 of file PHG4CylinderGeom.h
References PHOOL_VIRTUAL_WARN.
virtual void PHG4CylinderGeom::set_phi_slat_zero (const double phi) inline virtual
Reimplemented in PHG4CylinderGeomv3.
Definition at line 40 of file PHG4CylinderGeom.h.
View newest version in sPHENIX GitHub at line 40 of file PHG4CylinderGeom.h
References PHOOL_VIRTUAL_WARN.
virtual void PHG4CylinderGeom::set_radius (const double r) inline virtual
Reimplemented in CylinderGeomMicromegas, and PHG4CylinderGeomv1.
Definition at line 34 of file PHG4CylinderGeom.h.
View newest version in sPHENIX GitHub at line 34 of file PHG4CylinderGeom.h
References PHOOL_VIRTUAL_WARN.
virtual void PHG4CylinderGeom::set_thickness (const double t) inline virtual
Reimplemented in CylinderGeomMicromegas, and PHG4CylinderGeomv1.
Definition at line 35 of file PHG4CylinderGeom.h.
View newest version in sPHENIX GitHub at line 35 of file PHG4CylinderGeom.h
References PHOOL_VIRTUAL_WARN.
virtual void PHG4CylinderGeom::set_tiltangle (const double i) inline virtual
Reimplemented in PHG4CylinderGeomv3.
Definition at line 39 of file PHG4CylinderGeom.h.
View newest version in sPHENIX GitHub at line 39 of file PHG4CylinderGeom.h
References PHOOL_VIRTUAL_WARN.
virtual void PHG4CylinderGeom::set_zmax (const double z) inline virtual
Reimplemented in CylinderGeomMicromegas, and PHG4CylinderGeomv1.
Definition at line 37 of file PHG4CylinderGeom.h.
View newest version in sPHENIX GitHub at line 37 of file PHG4CylinderGeom.h
References PHOOL_VIRTUAL_WARN.
virtual void PHG4CylinderGeom::set_zmin (const double z) inline virtual
Reimplemented in CylinderGeomMicromegas, and PHG4CylinderGeomv1.
Definition at line 36 of file PHG4CylinderGeom.h.
View newest version in sPHENIX GitHub at line 36 of file PHG4CylinderGeom.h
References PHOOL_VIRTUAL_WARN.
The documentation for this class was generated from the following files:
coresoftware/blob/master/simulation/g4simulation/g4detectors/PHG4CylinderGeom.h
coresoftware/blob/master/simulation/g4simulation/g4detectors/PHG4CylinderGeom.cc