Analysis Software: ODBCStatement Class Reference
ODBCStatement Class Reference
#include <RDBC/blob/master/odbc/ODBCStatement.h>
Public Member Functions
virtual ~ODBCStatement ()
Bool_t Execute (const TString &sql="")
TSQLResultSet * ExecuteQuery (const TString &sql="")
Int_t ExecuteUpdate (const TString &sql="")
TSQLResultSet * GetResultSet ()
Bool_t GetMoreResults ()
void Close ()
void Cancel ()
Int_t GetMaxFieldSize ()
void SetMaxFieldSize (Int_t max)
Int_t GetMaxRows ()
void SetMaxRows (Int_t max)
Bool_t GetEscapeProcessing ()
void SetEscapeProcessing (Bool_t enable=kTRUE)
Int_t GetQueryTimeout ()
void SetQueryTimeout (Int_t seconds)
Int_t GetUpdateCount ()
void SetCursorName (const TString &name)
void AddBatch (const TString &sql)
void ClearBatch ()
Int_t * ExecuteBatch ()
Int_t GetFetchDirection ()
void SetFetchDirection (Int_t direction)
Int_t GetFetchSize ()
void SetFetchSize (Int_t rows)
Int_t GetResultSetConcurrency ()
Int_t GetResultSetType ()
Public Member Functions inherited from TSQLStatement
virtual void Execute (const char *, const char *, int *)
virtual void Execute (TMethod *, TObjArray *, int *)
virtual ~TSQLStatement ()
TSQLConnection * GetConnection () const
Public Member Functions inherited from TSQL
TSQL (void *imp=0)
virtual ~TSQL ()
virtual void Throw (TSQLException *e)
TList * GetWarnings () const
void ClearWarnings ()
virtual Bool_t IsValid () const
Protected Member Functions
ODBCStatement (TSQLConnection *con, void *imp=0)
Protected Member Functions inherited from TSQLStatement
TSQLStatement (TSQLConnection *con, void *imp=0)
Friends
class ODBCConnection
class ODBCResultSet
Additional Inherited Members
Static Public Member Functions inherited from TSQL
static Bool_t SetHandler (const TString &handler)
static Bool_t UnsetHandler (const TString &handler="")
Protected Attributes inherited from TSQLStatement
TList * fBatches
TSQLResultSet * fCurrentResult
TSQLConnection * fConnection
Detailed Description
Definition at line 15 of file ODBCStatement.h.
View newest version in sPHENIX GitHub at line 15 of file ODBCStatement.h
Constructor & Destructor Documentation
ODBCStatement::ODBCStatement (TSQLConnection * con, void * imp = 0) protected
ODBCStatement::~ODBCStatement () virtual
Definition at line 114 of file ODBCStatement.cxx.
View newest version in sPHENIX GitHub at line 114 of file ODBCStatement.cxx
References Acts::UnitConstants::e, TSQL::fImp, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), ODBCXX_STRING_CSTR, and TSQL::Throw().
Member Function Documentation
void ODBCStatement::AddBatch (const TString & sql) virtual
Implements TSQLStatement.
Definition at line 817 of file ODBCStatement.cxx.
View newest version in sPHENIX GitHub at line 817 of file ODBCStatement.cxx
void ODBCStatement::Cancel () virtual
Implements TSQLStatement.
Definition at line 583 of file ODBCStatement.cxx.
View newest version in sPHENIX GitHub at line 583 of file ODBCStatement.cxx
References odbc::Statement::cancel(), Acts::UnitConstants::e, TSQL::fImp, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), ODBCXX_STRING_CSTR, and TSQL::Throw().
void ODBCStatement::ClearBatch () virtual
Implements TSQLStatement.
Definition at line 832 of file ODBCStatement.cxx.
View newest version in sPHENIX GitHub at line 832 of file ODBCStatement.cxx
void ODBCStatement::Close () virtual
Implements TSQLStatement.
Definition at line 606 of file ODBCStatement.cxx.
View newest version in sPHENIX GitHub at line 606 of file ODBCStatement.cxx
References Acts::UnitConstants::e, TSQL::fImp, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), ODBCXX_STRING_CSTR, and TSQL::Throw().
Bool_t ODBCStatement::Execute (const TString & sql = "") virtual
Implements TSQLStatement.
Definition at line 173 of file ODBCStatement.cxx.
View newest version in sPHENIX GitHub at line 173 of file ODBCStatement.cxx
References TSQL::ClearWarnings(), Acts::UnitConstants::e, odbc::Statement::execute(), TSQL::fImp, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), ODBCXX_STRING_C, ODBCXX_STRING_CSTR, and TSQL::Throw().
Int_t * ODBCStatement::ExecuteBatch () virtual
Implements TSQLStatement.
Definition at line 844 of file ODBCStatement.cxx.
View newest version in sPHENIX GitHub at line 844 of file ODBCStatement.cxx
TSQLResultSet * ODBCStatement::ExecuteQuery (const TString & sql = "") virtual
Implements TSQLStatement.
Definition at line 138 of file ODBCStatement.cxx.
View newest version in sPHENIX GitHub at line 138 of file ODBCStatement.cxx
References TSQL::ClearWarnings(), Acts::UnitConstants::e, odbc::Statement::executeQuery(), TSQL::fImp, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), ODBCResultSet::ODBCResultSet(), ODBCXX_STRING_C, ODBCXX_STRING_CSTR, and TSQL::Throw().
Int_t ODBCStatement::ExecuteUpdate (const TString & sql = "") virtual
Implements TSQLStatement.
Definition at line 219 of file ODBCStatement.cxx.
View newest version in sPHENIX GitHub at line 219 of file ODBCStatement.cxx
References TSQL::ClearWarnings(), Acts::UnitConstants::e, odbc::Statement::executeUpdate(), TSQL::fImp, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), ODBCXX_STRING_C, ODBCXX_STRING_CSTR, and TSQL::Throw().
Bool_t ODBCStatement::GetEscapeProcessing () virtual
Implements TSQLStatement.
Definition at line 496 of file ODBCStatement.cxx.
View newest version in sPHENIX GitHub at line 496 of file ODBCStatement.cxx
References Acts::UnitConstants::e, TSQL::fImp, odbc::SQLException::getErrorCode(), odbc::Statement::getEscapeProcessing(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), ODBCXX_STRING_CSTR, and TSQL::Throw().
Int_t ODBCStatement::GetFetchDirection () virtual
Implements TSQLStatement.
Definition at line 696 of file ODBCStatement.cxx.
View newest version in sPHENIX GitHub at line 696 of file ODBCStatement.cxx
Int_t ODBCStatement::GetFetchSize () virtual
Implements TSQLStatement.
Definition at line 732 of file ODBCStatement.cxx.
View newest version in sPHENIX GitHub at line 732 of file ODBCStatement.cxx
References Acts::UnitConstants::e, TSQL::fImp, odbc::SQLException::getErrorCode(), odbc::Statement::getFetchSize(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), ODBCXX_STRING_CSTR, and TSQL::Throw().
Int_t ODBCStatement::GetMaxFieldSize () virtual
Implements TSQLStatement.
Definition at line 356 of file ODBCStatement.cxx.
View newest version in sPHENIX GitHub at line 356 of file ODBCStatement.cxx
References Acts::UnitConstants::e, TSQL::fImp, odbc::SQLException::getErrorCode(), odbc::Statement::getMaxFieldSize(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), ODBCXX_STRING_CSTR, and TSQL::Throw().
Int_t ODBCStatement::GetMaxRows () virtual
Implements TSQLStatement.
Definition at line 415 of file ODBCStatement.cxx.
View newest version in sPHENIX GitHub at line 415 of file ODBCStatement.cxx
References Acts::UnitConstants::e, TSQL::fImp, odbc::SQLException::getErrorCode(), odbc::Statement::getMaxRows(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), ODBCXX_STRING_CSTR, and TSQL::Throw().
Bool_t ODBCStatement::GetMoreResults () virtual
Implements TSQLStatement.
Definition at line 322 of file ODBCStatement.cxx.
View newest version in sPHENIX GitHub at line 322 of file ODBCStatement.cxx
References Acts::UnitConstants::e, TSQL::fImp, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::Statement::getMoreResults(), odbc::SQLException::getSQLState(), ODBCXX_STRING_CSTR, and TSQL::Throw().
Int_t ODBCStatement::GetQueryTimeout () virtual
Implements TSQLStatement.
Definition at line 529 of file ODBCStatement.cxx.
View newest version in sPHENIX GitHub at line 529 of file ODBCStatement.cxx
References Acts::UnitConstants::e, TSQL::fImp, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::Statement::getQueryTimeout(), odbc::SQLException::getSQLState(), ODBCXX_STRING_CSTR, and TSQL::Throw().
TSQLResultSet * ODBCStatement::GetResultSet () virtual
Implements TSQLStatement.
Definition at line 255 of file ODBCStatement.cxx.
View newest version in sPHENIX GitHub at line 255 of file ODBCStatement.cxx
References Acts::UnitConstants::e, TSQL::fImp, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::Statement::getResultSet(), odbc::SQLException::getSQLState(), ODBCResultSet::ODBCResultSet(), ODBCXX_STRING_CSTR, and TSQL::Throw().
Int_t ODBCStatement::GetResultSetConcurrency () virtual
Implements TSQLStatement.
Definition at line 763 of file ODBCStatement.cxx.
View newest version in sPHENIX GitHub at line 763 of file ODBCStatement.cxx
References Acts::UnitConstants::e, TSQL::fImp, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::Statement::getResultSetConcurrency(), odbc::SQLException::getSQLState(), ODBCXX_STRING_CSTR, and TSQL::Throw().
Int_t ODBCStatement::GetResultSetType () virtual
Implements TSQLStatement.
Definition at line 789 of file ODBCStatement.cxx.
View newest version in sPHENIX GitHub at line 789 of file ODBCStatement.cxx
References Acts::UnitConstants::e, TSQL::fImp, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::Statement::getResultSetType(), odbc::SQLException::getSQLState(), ODBCXX_STRING_CSTR, and TSQL::Throw().
Int_t ODBCStatement::GetUpdateCount () virtual
Implements TSQLStatement.
Definition at line 291 of file ODBCStatement.cxx.
View newest version in sPHENIX GitHub at line 291 of file ODBCStatement.cxx
References Acts::UnitConstants::e, TSQL::fImp, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), odbc::Statement::getUpdateCount(), ODBCXX_STRING_CSTR, and TSQL::Throw().
void ODBCStatement::SetCursorName (const TString & name) virtual
Implements TSQLStatement.
Definition at line 638 of file ODBCStatement.cxx.
View newest version in sPHENIX GitHub at line 638 of file ODBCStatement.cxx
References Acts::UnitConstants::e, TSQL::fImp, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), ODBCXX_STRING_C, ODBCXX_STRING_CSTR, odbc::Statement::setCursorName(), and TSQL::Throw().
void ODBCStatement::SetEscapeProcessing (Bool_t enable = kTRUE) virtual
Implements TSQLStatement.
Definition at line 467 of file ODBCStatement.cxx.
View newest version in sPHENIX GitHub at line 467 of file ODBCStatement.cxx
References Acts::UnitConstants::e, TSQL::fImp, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), ODBCXX_STRING_CSTR, odbc::Statement::setEscapeProcessing(), and TSQL::Throw().
void ODBCStatement::SetFetchDirection (Int_t direction) virtual
Implements TSQLStatement.
Definition at line 675 of file ODBCStatement.cxx.
View newest version in sPHENIX GitHub at line 675 of file ODBCStatement.cxx
References TSQL::fImp.
void ODBCStatement::SetFetchSize (Int_t rows) virtual
Implements TSQLStatement.
Definition at line 714 of file ODBCStatement.cxx.
View newest version in sPHENIX GitHub at line 714 of file ODBCStatement.cxx
References TSQL::fImp.
void ODBCStatement::SetMaxFieldSize (Int_t max) virtual
Implements TSQLStatement.
Definition at line 387 of file ODBCStatement.cxx.
View newest version in sPHENIX GitHub at line 387 of file ODBCStatement.cxx
References Acts::UnitConstants::e, TSQL::fImp, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), ODBCXX_STRING_CSTR, odbc::Statement::setMaxFieldSize(), and TSQL::Throw().
void ODBCStatement::SetMaxRows (Int_t max) virtual
Implements TSQLStatement.
Definition at line 443 of file ODBCStatement.cxx.
View newest version in sPHENIX GitHub at line 443 of file ODBCStatement.cxx
References Acts::UnitConstants::e, TSQL::fImp, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), ODBCXX_STRING_CSTR, odbc::Statement::setMaxRows(), and TSQL::Throw().
void ODBCStatement::SetQueryTimeout (Int_t seconds) virtual
Implements TSQLStatement.
Definition at line 558 of file ODBCStatement.cxx.
View newest version in sPHENIX GitHub at line 558 of file ODBCStatement.cxx
References Acts::UnitConstants::e, TSQL::fImp, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), ODBCXX_STRING_CSTR, odbc::Statement::setQueryTimeout(), and TSQL::Throw().
Friends And Related Function Documentation
friend class ODBCConnection friend
Definition at line 17 of file ODBCStatement.h.
View newest version in sPHENIX GitHub at line 17 of file ODBCStatement.h
friend class ODBCResultSet friend
Definition at line 18 of file ODBCStatement.h.
View newest version in sPHENIX GitHub at line 18 of file ODBCStatement.h
The documentation for this class was generated from the following files:
RDBC/blob/master/odbc/ODBCStatement.h
RDBC/blob/master/odbc/ODBCStatement.cxx