Analysis Software: ThermalPartonSampler Class Reference
ThermalPartonSampler Class Reference
#include <JETSCAPE/blob/main/src/hadronization/ThermPtnSampler.h>
Public Member Functions
ThermalPartonSampler (unsigned int ran_seed)
void samplebrick ()
void sample_2p1d (double eta_max)
void sample_3p1d (bool Cartesian_hydro=false)
void set_hypersurface (std::vector< std::vector< double >> surf_in)
void brick_length_width (double len_bri, double wid_bri)
void brick_flow (double vx_in, double vy_in, double vz_in)
void brick_Tc (double brick_Tc)
int nTot ()
int th_Evnum (int i)
int th_pid (int i)
int th_orig (int i)
int th_stat (int i)
double th_px (int i)
double th_py (int i)
double th_pz (int i)
double th_e (int i)
double th_x (int i)
double th_y (int i)
double th_z (int i)
double th_t (int i)
int th_nL ()
int th_nS ()
Private Member Functions
bool SplitSort (double goal, int floor, int ceiling, int quark)
void MCSampler (double Temp, int quark)
double FermiPDF (double Pc, double Mc, double Tc, double muc)
void CDFGenerator (double Temp, double M, int quark)
std::uniform_real_distribution
< double > double ran ()
std::mt19937_64 & getRandomGenerator ()
Private Attributes
std::vector< std::vector
< double > > Plist
std::mt19937_64 rng_engine
std::uniform_real_distribution
< double > distribution
const double PI = 3.141592653589793
double muPi0 = 0.
const double GEVFM = 0.197327053
double xmq
double xms
double T
double NUMSTEP
double CellDX
double CellDY
double CellDZ
double CellDT
int GPoints = 50
double GWeight [50]
double GAbs [50]
bool SetNum
bool SetNumLight
bool SetNumStrange
bool ShuffleList
double NewX
double NewY
double NewZ
double NewP
int num_ud
int num_s
std::vector< std::vector
< double > > CDFTabLight
std::vector< std::vector
< double > > CDFTabStrange
double L
double W
double Time
double Vx
double Vy
double Vz
std::vector< std::vector
< double > > surface
Detailed Description
Definition at line 11 of file ThermPtnSampler.h.
View newest version in sPHENIX GitHub at line 11 of file ThermPtnSampler.h
Constructor & Destructor Documentation
ThermalPartonSampler::ThermalPartonSampler (unsigned int ran_seed)
Definition at line 15 of file ThermPtnSampler.cc.
View newest version in sPHENIX GitHub at line 15 of file ThermPtnSampler.cc
References Acts::IntegrationTest::L, writeMapConfig::surface, and Acts::UnitConstants::T.
Member Function Documentation
void ThermalPartonSampler::brick_flow (double vx_in, double vy_in, double vz_in) inline
Definition at line 27 of file ThermPtnSampler.h.
View newest version in sPHENIX GitHub at line 27 of file ThermPtnSampler.h
Referenced by HybridHadronization::DoHadronization().
void ThermalPartonSampler::brick_length_width (double len_bri, double wid_bri) inline
Definition at line 26 of file ThermPtnSampler.h.
View newest version in sPHENIX GitHub at line 26 of file ThermPtnSampler.h
References Acts::IntegrationTest::L.
Referenced by HybridHadronization::DoHadronization().
void ThermalPartonSampler::brick_Tc (double brick_Tc) inline
Definition at line 28 of file ThermPtnSampler.h.
View newest version in sPHENIX GitHub at line 28 of file ThermPtnSampler.h
References Acts::UnitConstants::T.
Referenced by HybridHadronization::DoHadronization().
void ThermalPartonSampler::CDFGenerator (double Temp, double M, int quark) private
Definition at line 92 of file ThermPtnSampler.cc.
View newest version in sPHENIX GitHub at line 92 of file ThermPtnSampler.cc
References i, and JSWARN.
double ThermalPartonSampler::FermiPDF (double Pc, double Mc, double Tc, double muc) private
Definition at line 79 of file ThermPtnSampler.cc.
View newest version in sPHENIX GitHub at line 79 of file ThermPtnSampler.cc
std::mt19937_64& ThermalPartonSampler::getRandomGenerator () inline private
Definition at line 66 of file ThermPtnSampler.h.
View newest version in sPHENIX GitHub at line 66 of file ThermPtnSampler.h
void ThermalPartonSampler::MCSampler (double Temp, int quark) private
Definition at line 134 of file ThermPtnSampler.cc.
View newest version in sPHENIX GitHub at line 134 of file ThermPtnSampler.cc
References Acts::UnitConstants::e, i, ran(), and train_ambiguity_solver::test.
int ThermalPartonSampler::nTot () inline
Definition at line 31 of file ThermPtnSampler.h.
View newest version in sPHENIX GitHub at line 31 of file ThermPtnSampler.h
Referenced by HybridHadronization::DoHadronization().
std::uniform_real_distribution<double> double ThermalPartonSampler::ran () inline private
Definition at line 64 of file ThermPtnSampler.h.
View newest version in sPHENIX GitHub at line 64 of file ThermPtnSampler.h
void ThermalPartonSampler::sample_2p1d (double eta_max)
Definition at line 822 of file ThermPtnSampler.cc.
View newest version in sPHENIX GitHub at line 822 of file ThermPtnSampler.cc
References distance(), Acts::UnitConstants::e, energy, entry, JSDEBUG, JSINFO, k, Acts::UnitConstants::m, mass, ran(), and writeMapConfig::surface.
Referenced by HybridHadronization::DoHadronization().
void ThermalPartonSampler::sample_3p1d (bool Cartesian_hydro = false)
Definition at line 471 of file ThermPtnSampler.cc.
View newest version in sPHENIX GitHub at line 471 of file ThermPtnSampler.cc
References distance(), Acts::UnitConstants::e, energy, entry, JSDEBUG, k, Acts::UnitConstants::m, mass, ran(), and writeMapConfig::surface.
Referenced by HybridHadronization::DoHadronization().
void ThermalPartonSampler::samplebrick ()
Definition at line 175 of file ThermPtnSampler.cc.
View newest version in sPHENIX GitHub at line 175 of file ThermPtnSampler.cc
References energy, JSDEBUG, JSWARN, k, Acts::IntegrationTest::L, Acts::UnitConstants::m, mass, ran(), and Acts::UnitConstants::T.
Referenced by HybridHadronization::DoHadronization().
void ThermalPartonSampler::set_hypersurface (std::vector< std::vector< double >> surf_in) inline
Definition at line 23 of file ThermPtnSampler.h.
View newest version in sPHENIX GitHub at line 23 of file ThermPtnSampler.h
References writeMapConfig::surface.
Referenced by HybridHadronization::DoHadronization().
bool ThermalPartonSampler::SplitSort (double goal, int floor, int ceiling, int quark) private
Definition at line 83 of file ThermPtnSampler.cc.
View newest version in sPHENIX GitHub at line 83 of file ThermPtnSampler.cc
double ThermalPartonSampler::th_e (int i) inline
Definition at line 39 of file ThermPtnSampler.h.
View newest version in sPHENIX GitHub at line 39 of file ThermPtnSampler.h
References i.
Referenced by HybridHadronization::DoHadronization().
int ThermalPartonSampler::th_Evnum (int i) inline
Definition at line 32 of file ThermPtnSampler.h.
View newest version in sPHENIX GitHub at line 32 of file ThermPtnSampler.h
References i.
int ThermalPartonSampler::th_nL () inline
Definition at line 44 of file ThermPtnSampler.h.
View newest version in sPHENIX GitHub at line 44 of file ThermPtnSampler.h
Referenced by HybridHadronization::DoHadronization().
int ThermalPartonSampler::th_nS () inline
Definition at line 45 of file ThermPtnSampler.h.
View newest version in sPHENIX GitHub at line 45 of file ThermPtnSampler.h
Referenced by HybridHadronization::DoHadronization().
int ThermalPartonSampler::th_orig (int i) inline
Definition at line 34 of file ThermPtnSampler.h.
View newest version in sPHENIX GitHub at line 34 of file ThermPtnSampler.h
References i.
int ThermalPartonSampler::th_pid (int i) inline
Definition at line 33 of file ThermPtnSampler.h.
View newest version in sPHENIX GitHub at line 33 of file ThermPtnSampler.h
References i.
Referenced by HybridHadronization::DoHadronization().
double ThermalPartonSampler::th_px (int i) inline
Definition at line 36 of file ThermPtnSampler.h.
View newest version in sPHENIX GitHub at line 36 of file ThermPtnSampler.h
References i.
Referenced by HybridHadronization::DoHadronization().
double ThermalPartonSampler::th_py (int i) inline
Definition at line 37 of file ThermPtnSampler.h.
View newest version in sPHENIX GitHub at line 37 of file ThermPtnSampler.h
References i.
Referenced by HybridHadronization::DoHadronization().
double ThermalPartonSampler::th_pz (int i) inline
Definition at line 38 of file ThermPtnSampler.h.
View newest version in sPHENIX GitHub at line 38 of file ThermPtnSampler.h
References i.
Referenced by HybridHadronization::DoHadronization().
int ThermalPartonSampler::th_stat (int i) inline
Definition at line 35 of file ThermPtnSampler.h.
View newest version in sPHENIX GitHub at line 35 of file ThermPtnSampler.h
References i.
double ThermalPartonSampler::th_t (int i) inline
Definition at line 43 of file ThermPtnSampler.h.
View newest version in sPHENIX GitHub at line 43 of file ThermPtnSampler.h
References i.
Referenced by HybridHadronization::DoHadronization().
double ThermalPartonSampler::th_x (int i) inline
Definition at line 40 of file ThermPtnSampler.h.
View newest version in sPHENIX GitHub at line 40 of file ThermPtnSampler.h
References i.
Referenced by HybridHadronization::DoHadronization().
double ThermalPartonSampler::th_y (int i) inline
Definition at line 41 of file ThermPtnSampler.h.
View newest version in sPHENIX GitHub at line 41 of file ThermPtnSampler.h
References i.
Referenced by HybridHadronization::DoHadronization().
double ThermalPartonSampler::th_z (int i) inline
Definition at line 42 of file ThermPtnSampler.h.
View newest version in sPHENIX GitHub at line 42 of file ThermPtnSampler.h
References i.
Referenced by HybridHadronization::DoHadronization().
Member Data Documentation
std::vector<std::vector<double> > ThermalPartonSampler::CDFTabLight private
Definition at line 89 of file ThermPtnSampler.h.
View newest version in sPHENIX GitHub at line 89 of file ThermPtnSampler.h
std::vector<std::vector<double> > ThermalPartonSampler::CDFTabStrange private
Definition at line 90 of file ThermPtnSampler.h.
View newest version in sPHENIX GitHub at line 90 of file ThermPtnSampler.h
double ThermalPartonSampler::CellDT private
Definition at line 75 of file ThermPtnSampler.h.
View newest version in sPHENIX GitHub at line 75 of file ThermPtnSampler.h
double ThermalPartonSampler::CellDX private
Definition at line 75 of file ThermPtnSampler.h.
View newest version in sPHENIX GitHub at line 75 of file ThermPtnSampler.h
double ThermalPartonSampler::CellDY private
Definition at line 75 of file ThermPtnSampler.h.
View newest version in sPHENIX GitHub at line 75 of file ThermPtnSampler.h
double ThermalPartonSampler::CellDZ private
Definition at line 75 of file ThermPtnSampler.h.
View newest version in sPHENIX GitHub at line 75 of file ThermPtnSampler.h
std::uniform_real_distribution<double> ThermalPartonSampler::distribution private
Definition at line 62 of file ThermPtnSampler.h.
View newest version in sPHENIX GitHub at line 62 of file ThermPtnSampler.h
double ThermalPartonSampler::GAbs[50] private
Definition at line 81 of file ThermPtnSampler.h.
View newest version in sPHENIX GitHub at line 81 of file ThermPtnSampler.h
const double ThermalPartonSampler::GEVFM = 0.197327053 private
Definition at line 71 of file ThermPtnSampler.h.
View newest version in sPHENIX GitHub at line 71 of file ThermPtnSampler.h
int ThermalPartonSampler::GPoints = 50 private
Definition at line 79 of file ThermPtnSampler.h.
View newest version in sPHENIX GitHub at line 79 of file ThermPtnSampler.h
double ThermalPartonSampler::GWeight[50] private
Definition at line 80 of file ThermPtnSampler.h.
View newest version in sPHENIX GitHub at line 80 of file ThermPtnSampler.h
double ThermalPartonSampler::L private
Definition at line 96 of file ThermPtnSampler.h.
View newest version in sPHENIX GitHub at line 96 of file ThermPtnSampler.h
double ThermalPartonSampler::muPi0 = 0. private
Definition at line 70 of file ThermPtnSampler.h.
View newest version in sPHENIX GitHub at line 70 of file ThermPtnSampler.h
double ThermalPartonSampler::NewP private
Definition at line 87 of file ThermPtnSampler.h.
View newest version in sPHENIX GitHub at line 87 of file ThermPtnSampler.h
double ThermalPartonSampler::NewX private
Definition at line 87 of file ThermPtnSampler.h.
View newest version in sPHENIX GitHub at line 87 of file ThermPtnSampler.h
double ThermalPartonSampler::NewY private
Definition at line 87 of file ThermPtnSampler.h.
View newest version in sPHENIX GitHub at line 87 of file ThermPtnSampler.h
double ThermalPartonSampler::NewZ private
Definition at line 87 of file ThermPtnSampler.h.
View newest version in sPHENIX GitHub at line 87 of file ThermPtnSampler.h
int ThermalPartonSampler::num_s private
Definition at line 88 of file ThermPtnSampler.h.
View newest version in sPHENIX GitHub at line 88 of file ThermPtnSampler.h
int ThermalPartonSampler::num_ud private
Definition at line 88 of file ThermPtnSampler.h.
View newest version in sPHENIX GitHub at line 88 of file ThermPtnSampler.h
double ThermalPartonSampler::NUMSTEP private
Definition at line 74 of file ThermPtnSampler.h.
View newest version in sPHENIX GitHub at line 74 of file ThermPtnSampler.h
const double ThermalPartonSampler::PI = 3.141592653589793 private
Definition at line 69 of file ThermPtnSampler.h.
View newest version in sPHENIX GitHub at line 69 of file ThermPtnSampler.h
std::vector<std::vector<double> > ThermalPartonSampler::Plist private
Definition at line 51 of file ThermPtnSampler.h.
View newest version in sPHENIX GitHub at line 51 of file ThermPtnSampler.h
std::mt19937_64 ThermalPartonSampler::rng_engine private
Definition at line 61 of file ThermPtnSampler.h.
View newest version in sPHENIX GitHub at line 61 of file ThermPtnSampler.h
bool ThermalPartonSampler::SetNum private
Definition at line 84 of file ThermPtnSampler.h.
View newest version in sPHENIX GitHub at line 84 of file ThermPtnSampler.h
bool ThermalPartonSampler::SetNumLight private
Definition at line 84 of file ThermPtnSampler.h.
View newest version in sPHENIX GitHub at line 84 of file ThermPtnSampler.h
bool ThermalPartonSampler::SetNumStrange private
Definition at line 84 of file ThermPtnSampler.h.
View newest version in sPHENIX GitHub at line 84 of file ThermPtnSampler.h
bool ThermalPartonSampler::ShuffleList private
Definition at line 84 of file ThermPtnSampler.h.
View newest version in sPHENIX GitHub at line 84 of file ThermPtnSampler.h
std::vector<std::vector<double> > ThermalPartonSampler::surface private
Definition at line 99 of file ThermPtnSampler.h.
View newest version in sPHENIX GitHub at line 99 of file ThermPtnSampler.h
double ThermalPartonSampler::T private
Definition at line 74 of file ThermPtnSampler.h.
View newest version in sPHENIX GitHub at line 74 of file ThermPtnSampler.h
double ThermalPartonSampler::Time private
Definition at line 96 of file ThermPtnSampler.h.
View newest version in sPHENIX GitHub at line 96 of file ThermPtnSampler.h
double ThermalPartonSampler::Vx private
Definition at line 96 of file ThermPtnSampler.h.
View newest version in sPHENIX GitHub at line 96 of file ThermPtnSampler.h
double ThermalPartonSampler::Vy private
Definition at line 96 of file ThermPtnSampler.h.
View newest version in sPHENIX GitHub at line 96 of file ThermPtnSampler.h
double ThermalPartonSampler::Vz private
Definition at line 96 of file ThermPtnSampler.h.
View newest version in sPHENIX GitHub at line 96 of file ThermPtnSampler.h
double ThermalPartonSampler::W private
Definition at line 96 of file ThermPtnSampler.h.
View newest version in sPHENIX GitHub at line 96 of file ThermPtnSampler.h
double ThermalPartonSampler::xmq private
Definition at line 74 of file ThermPtnSampler.h.
View newest version in sPHENIX GitHub at line 74 of file ThermPtnSampler.h
double ThermalPartonSampler::xms private
Definition at line 74 of file ThermPtnSampler.h.
View newest version in sPHENIX GitHub at line 74 of file ThermPtnSampler.h
The documentation for this class was generated from the following files:
JETSCAPE/blob/main/src/hadronization/ThermPtnSampler.h
JETSCAPE/blob/main/src/hadronization/ThermPtnSampler.cc