Analysis Software: PHTrackCleaner Class Reference
PHTrackCleaner Class Reference
#include <coresoftware/blob/master/offline/packages/trackreco/PHTrackCleaner.h>
Public Member Functions
PHTrackCleaner (const std::string &name="PHTrackCleaner")
Tracking includes.
~PHTrackCleaner () override
int InitRun (PHCompositeNode *topNode) override
int process_event (PHCompositeNode *topNode) override
int End (PHCompositeNode *topNode) override
Called at the end of all processing.
void set_pp_mode (const bool flag)
Public Member Functions inherited from SubsysReco
~SubsysReco () override
virtual int EndRun (const int)
Called at the end of each run.
virtual int Init (PHCompositeNode *)
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
void Print (const std::string &="ALL") const override
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Private Member Functions
int GetNodes (PHCompositeNode *topNode)
void findGhostTracks ()
Private Attributes
SvtxTrackMap * _track_map {nullptr}
SvtxTrack * _track {nullptr}
TrackSeedContainer * _tpc_seed_map {nullptr}
double min_ndf = 25
bool _pp_mode = false
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = std::numeric_limits<int>::max() - 10
}
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Detailed Description
Definition at line 25 of file PHTrackCleaner.h.
View newest version in sPHENIX GitHub at line 25 of file PHTrackCleaner.h
Constructor & Destructor Documentation
PHTrackCleaner::PHTrackCleaner (const std::string & name = "PHTrackCleaner")
Tracking includes.
Definition at line 26 of file PHTrackCleaner.cc.
View newest version in sPHENIX GitHub at line 26 of file PHTrackCleaner.cc
PHTrackCleaner::~PHTrackCleaner () override
Definition at line 33 of file PHTrackCleaner.cc.
View newest version in sPHENIX GitHub at line 33 of file PHTrackCleaner.cc
Member Function Documentation
int PHTrackCleaner::End (PHCompositeNode *) override virtual
Called at the end of all processing.
Reimplemented from SubsysReco.
Definition at line 189 of file PHTrackCleaner.cc.
View newest version in sPHENIX GitHub at line 189 of file PHTrackCleaner.cc
References Fun4AllReturnCodes::EVENT_OK.
void PHTrackCleaner::findGhostTracks () private
int PHTrackCleaner::GetNodes (PHCompositeNode * topNode) private
Definition at line 194 of file PHTrackCleaner.cc.
View newest version in sPHENIX GitHub at line 194 of file PHTrackCleaner.cc
References _tpc_seed_map, _track_map, Fun4AllReturnCodes::ABORTEVENT, Fun4AllReturnCodes::EVENT_OK, and PHWHERE.
Referenced by InitRun().
int PHTrackCleaner::InitRun (PHCompositeNode *) override virtual
Called for first event when run number is known. Typically this is where you may want to fetch data from database, because you know the run number.
Reimplemented from SubsysReco.
Definition at line 39 of file PHTrackCleaner.cc.
View newest version in sPHENIX GitHub at line 39 of file PHTrackCleaner.cc
References Fun4AllReturnCodes::EVENT_OK, and GetNodes().
int PHTrackCleaner::process_event (PHCompositeNode *) override virtual
Called for each event. This is where you do the real work.
Reimplemented from SubsysReco.
Definition at line 48 of file PHTrackCleaner.cc.
View newest version in sPHENIX GitHub at line 48 of file PHTrackCleaner.cc
References _pp_mode, _tpc_seed_map, _track, _track_map, SvtxTrackMap::begin(), SvtxTrackMap::end(), SvtxTrackMap::erase(), Fun4AllReturnCodes::EVENT_OK, TrackSeedContainer::find(), SvtxTrackMap::get(), SvtxTrack::get_chisq(), SvtxTrack::get_crossing(), SvtxTrack::get_ndf(), it, min_ndf, PHWHERE, SvtxTrackMap::size(), and Fun4AllBase::Verbosity().
void PHTrackCleaner::set_pp_mode (const bool flag) inline
Definition at line 37 of file PHTrackCleaner.h.
View newest version in sPHENIX GitHub at line 37 of file PHTrackCleaner.h
References _pp_mode.
Member Data Documentation
bool PHTrackCleaner::_pp_mode = false private
Definition at line 49 of file PHTrackCleaner.h.
View newest version in sPHENIX GitHub at line 49 of file PHTrackCleaner.h
Referenced by process_event(), and set_pp_mode().
TrackSeedContainer* PHTrackCleaner::_tpc_seed_map {nullptr} private
Definition at line 46 of file PHTrackCleaner.h.
View newest version in sPHENIX GitHub at line 46 of file PHTrackCleaner.h
Referenced by GetNodes(), and process_event().
SvtxTrack* PHTrackCleaner::_track {nullptr} private
Definition at line 45 of file PHTrackCleaner.h.
View newest version in sPHENIX GitHub at line 45 of file PHTrackCleaner.h
Referenced by process_event().
SvtxTrackMap* PHTrackCleaner::_track_map {nullptr} private
Definition at line 44 of file PHTrackCleaner.h.
View newest version in sPHENIX GitHub at line 44 of file PHTrackCleaner.h
Referenced by GetNodes(), and process_event().
double PHTrackCleaner::min_ndf = 25 private
Definition at line 48 of file PHTrackCleaner.h.
View newest version in sPHENIX GitHub at line 48 of file PHTrackCleaner.h
Referenced by process_event().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/trackreco/PHTrackCleaner.h
coresoftware/blob/master/offline/packages/trackreco/PHTrackCleaner.cc