Analysis Software: TSQLConnection Class Reference
TSQLConnection Class Reference abstract
#include <RDBC/blob/master/include/RDBC/TSQLConnection.h>
Public Member Functions
virtual Bool_t GetAutoCommit ()=0
virtual void SetAutoCommit (Bool_t autoCommit=kTRUE)=0
virtual TString GetCatalog ()=0
virtual void SetCatalog (const TString &catalog)=0
virtual Bool_t IsClosed ()
virtual Bool_t IsReadOnly ()=0
virtual void SetReadOnly (Bool_t readOnly=kTRUE)=0
virtual Bool_t GetTrace ()=0
virtual void SetTrace (Bool_t trace=kTRUE)=0
virtual void SetTraceFile (const TString &filename)=0
virtual TString GetTraceFile ()=0
virtual Int_t GetTransactionIsolation ()=0
virtual void SetTransactionIsolation (Int_t level)=0
virtual TString NativeSQL (const TString &sql)=0
virtual void Commit ()=0
virtual void Rollback ()=0
virtual TSQLStatement * CreateStatement ()=0
virtual TSQLStatement * CreateStatement (Int_t resultSetType, Int_t resultSetConcurrency)=0
virtual TSQLPreparedStatement * PrepareStatement (const TString &sql)=0
virtual TSQLPreparedStatement * PrepareStatement (const TString &sql, Int_t resultSetType, Int_t resultSetConcurrency)=0
virtual TSQLCallableStatement * PrepareCall (const TString &sql)=0
virtual TSQLCallableStatement * PrepareCall (const TString &sql, Int_t resultSetType, Int_t resultSetConcurrency)=0
virtual TSQLDatabaseMetaData * GetMetaData ()=0
virtual Bool_t HasBatchSupport ()=0
virtual void Close ()
TList * GetListOfStatements () const
virtual const char * GetName () const
virtual const char * GetTitle () const
virtual void Print (Option_t *option="") const
virtual void ls (Option_t *option="") const
Public Member Functions inherited from TSQL
TSQL (void *imp=0)
virtual ~TSQL ()
virtual void Throw (TSQLException *e)
TList * GetWarnings () const
void ClearWarnings ()
virtual Bool_t IsValid () const
Protected Member Functions
TSQLConnection (const TString &url, const TString &username, const TString &password)
TSQLConnection (const TString &connectString)
void SetURL (const TString &url)
virtual ~TSQLConnection ()
Protected Attributes
TSQLDatabaseMetaData * fMetaData
TList * fListOfStatements
Protected Attributes inherited from TSQL
TList * fWarnings
void * fImp
Friends
class TSQLDriverManager
Additional Inherited Members
Static Public Member Functions inherited from TSQL
static Bool_t SetHandler (const TString &handler)
static Bool_t UnsetHandler (const TString &handler="")
Detailed Description
Definition at line 37 of file TSQLConnection.h.
View newest version in sPHENIX GitHub at line 37 of file TSQLConnection.h
Constructor & Destructor Documentation
TSQLConnection::TSQLConnection (const TString & url, const TString & username, const TString & password) protected
Definition at line 183 of file MySQLConnection.cxx.
View newest version in sPHENIX GitHub at line 183 of file MySQLConnection.cxx
References TSQL::fImp, MySQLConnectionPrivate::fIsConnected, fListOfStatements, MySQLConnectionPrivate::fLocked, fMetaData, MySQLConnectionPrivate::fMYSQL, TSQL::Throw(), and summary::url.
TSQLConnection::TSQLConnection (const TString & connectString) protected
Definition at line 161 of file MySQLConnection.cxx.
View newest version in sPHENIX GitHub at line 161 of file MySQLConnection.cxx
References TSQL::fImp, fListOfStatements, and fMetaData.
TSQLConnection::~TSQLConnection () protected virtual
Definition at line 231 of file MySQLConnection.cxx.
View newest version in sPHENIX GitHub at line 231 of file MySQLConnection.cxx
References Close().
Member Function Documentation
void TSQLConnection::Close () virtual
Reimplemented in ODBCConnection.
Definition at line 511 of file MySQLConnection.cxx.
View newest version in sPHENIX GitHub at line 511 of file MySQLConnection.cxx
References TSQL::fImp, fListOfStatements, fMetaData, MySQLConnectionPrivate::fMYSQL, TSQLDriverManager::GetConnections(), IsClosed(), and TSQL::Throw().
Referenced by TRDBCServer::Close(), ODBCConnection::Close(), PgPostApplication::DisconnectDB(), DbForm::HandleDisconnect(), oproducer(), RDBCconsumer(), RDBCfirst(), RDBCTestConnect(), RDBCTestInt(), RDBCTestMetaData(), PgPostApplication::setDBName(), PgPostApplication::~PgPostApplication(), and ~TSQLConnection().
void TSQLConnection::Commit () pure virtual
Implemented in ODBCConnection.
Definition at line 476 of file MySQLConnection.cxx.
View newest version in sPHENIX GitHub at line 476 of file MySQLConnection.cxx
References IsClosed(), and TSQL::Throw().
Referenced by PgPostBankBackupManager::CleanTable(), PgPostApplication::commit(), PgPostBankWrapper::commit(), PgPostBankBackupManager::commit(), PgPostBankBackupManager::commitAllBankfromTFile(), CreateStuff(), Fill(), PgPostBankBackupLog::Log(), oproducer(), Populate(), and RDBCconsumer().
TSQLStatement * TSQLConnection::CreateStatement () pure virtual
Implemented in ODBCConnection.
Definition at line 242 of file MySQLConnection.cxx.
View newest version in sPHENIX GitHub at line 242 of file MySQLConnection.cxx
References fListOfStatements.
Referenced by PgPostBankBackupManager::CleanTable(), Compare(), TRDBCServer::CreateDataBase(), RDBCBench::CreateDatabase(), CreateStuff(), RDBCBench::DoOne(), TRDBCServer::DropDataBase(), RDBCBench::DropDatabase(), DropStuff(), PgPostBankBackupManager::dumpTable(), PgPostBankBackupManager::fetchAllBank2TFile(), PgPostBankManager::fetchBank(), PgPostBankBackupManager::fetchBank(), Fill(), PgPostBankBackupManager::getListOfRId(), PgPostBankBackupManager::getTotalRowCount(), DbForm::HandleExecuteQuery(), PgPostCalBankIterator::init(), PgPostBankBackupManager::isRIdExist(), TSQLImporter::LoadCatalog(), TSQLImporter::LoadTable(), TRDBCServer::Query(), RDBCconsumer(), RDBCfirst(), RDBCTestInt(), RDBCTestMetaData(), TRDBCServer::Reload(), and TRDBCServer::SelectDataBase().
TSQLStatement * TSQLConnection::CreateStatement (Int_t resultSetType, Int_t resultSetConcurrency) pure virtual
Implemented in ODBCConnection.
Definition at line 264 of file MySQLConnection.cxx.
View newest version in sPHENIX GitHub at line 264 of file MySQLConnection.cxx
References fListOfStatements.
Bool_t TSQLConnection::GetAutoCommit () pure virtual
Implemented in ODBCConnection.
Definition at line 461 of file MySQLConnection.cxx.
View newest version in sPHENIX GitHub at line 461 of file MySQLConnection.cxx
TString TSQLConnection::GetCatalog () pure virtual
Implemented in ODBCConnection.
Definition at line 649 of file MySQLConnection.cxx.
View newest version in sPHENIX GitHub at line 649 of file MySQLConnection.cxx
References TSQL::fImp, IsClosed(), and TSQL::Throw().
Referenced by TSQLStatement::Execute(), and TSQLStatement::ExecuteQuery().
TList* TSQLConnection::GetListOfStatements () const inline
Definition at line 84 of file TSQLConnection.h.
View newest version in sPHENIX GitHub at line 84 of file TSQLConnection.h
References fListOfStatements.
Referenced by PgPostBankBackupManager::deleteODBCPreparedStatement(), PgPostBankBackupManager::deleteSQLStatement(), and TSQLStatement::~TSQLStatement().
TSQLDatabaseMetaData * TSQLConnection::GetMetaData () pure virtual
Implemented in ODBCConnection.
Definition at line 567 of file MySQLConnection.cxx.
View newest version in sPHENIX GitHub at line 567 of file MySQLConnection.cxx
References fMetaData.
Referenced by Compare(), DbForm::HandleConnect(), oproducer(), and RDBCTestMetaData().
const char * TSQLConnection::GetName () const virtual
Definition at line 1069 of file MySQLConnection.cxx.
View newest version in sPHENIX GitHub at line 1069 of file MySQLConnection.cxx
References fMetaData, and TSQLDatabaseMetaData::GetURL().
const char * TSQLConnection::GetTitle () const virtual
Definition at line 1077 of file MySQLConnection.cxx.
View newest version in sPHENIX GitHub at line 1077 of file MySQLConnection.cxx
Bool_t TSQLConnection::GetTrace () pure virtual
Implemented in ODBCConnection.
Definition at line 708 of file MySQLConnection.cxx.
View newest version in sPHENIX GitHub at line 708 of file MySQLConnection.cxx
References TSQL::Throw().
TString TSQLConnection::GetTraceFile () pure virtual
Implemented in ODBCConnection.
Definition at line 725 of file MySQLConnection.cxx.
View newest version in sPHENIX GitHub at line 725 of file MySQLConnection.cxx
References TSQL::Throw().
Int_t TSQLConnection::GetTransactionIsolation () pure virtual
Implemented in ODBCConnection.
Definition at line 695 of file MySQLConnection.cxx.
View newest version in sPHENIX GitHub at line 695 of file MySQLConnection.cxx
References kTRANSACTION_SERIALIZABLE.
Bool_t TSQLConnection::HasBatchSupport () pure virtual
Implemented in ODBCConnection.
Definition at line 742 of file MySQLConnection.cxx.
View newest version in sPHENIX GitHub at line 742 of file MySQLConnection.cxx
Bool_t TSQLConnection::IsClosed () virtual
Definition at line 545 of file MySQLConnection.cxx.
View newest version in sPHENIX GitHub at line 545 of file MySQLConnection.cxx
References TSQL::fImp.
Referenced by TRDBCServer::Close(), ODBCConnection::Close(), Close(), ODBCConnection::Commit(), Commit(), ODBCConnection::CreateStatement(), ODBCConnection::GetAutoCommit(), ODBCConnection::GetCatalog(), GetCatalog(), ODBCConnection::GetMetaData(), ODBCConnection::GetTrace(), ODBCConnection::GetTraceFile(), ODBCConnection::GetTransactionIsolation(), ODBCConnection::IsReadOnly(), ODBCConnection::NativeSQL(), ODBCConnection::PrepareCall(), ODBCConnection::PrepareStatement(), ODBCConnection::Rollback(), Rollback(), ODBCConnection::SetAutoCommit(), ODBCConnection::SetCatalog(), SetCatalog(), ODBCConnection::SetReadOnly(), SetReadOnly(), ODBCConnection::SetTrace(), ODBCConnection::SetTraceFile(), ODBCConnection::SetTransactionIsolation(), SetTransactionIsolation(), and ODBCConnection::~ODBCConnection().
Bool_t TSQLConnection::IsReadOnly () pure virtual
Implemented in ODBCConnection.
Definition at line 610 of file MySQLConnection.cxx.
View newest version in sPHENIX GitHub at line 610 of file MySQLConnection.cxx
References TSQL::fImp, and MySQLConnectionPrivate::fReadOnly.
virtual void TSQLConnection::ls (Option_t * option = "") const inline virtual
Definition at line 88 of file TSQLConnection.h.
View newest version in sPHENIX GitHub at line 88 of file TSQLConnection.h
References Print().
TString TSQLConnection::NativeSQL (const TString & sql) pure virtual
Implemented in ODBCConnection.
Definition at line 412 of file MySQLConnection.cxx.
View newest version in sPHENIX GitHub at line 412 of file MySQLConnection.cxx
TSQLCallableStatement * TSQLConnection::PrepareCall (const TString & sql) pure virtual
Implemented in ODBCConnection.
Definition at line 325 of file MySQLConnection.cxx.
View newest version in sPHENIX GitHub at line 325 of file MySQLConnection.cxx
References TSQL::Throw().
TSQLCallableStatement * TSQLConnection::PrepareCall (const TString & sql, Int_t resultSetType, Int_t resultSetConcurrency) pure virtual
Implemented in ODBCConnection.
Definition at line 384 of file MySQLConnection.cxx.
View newest version in sPHENIX GitHub at line 384 of file MySQLConnection.cxx
References TSQL::Throw().
TSQLPreparedStatement * TSQLConnection::PrepareStatement (const TString & sql) pure virtual
Implemented in ODBCConnection.
Definition at line 289 of file MySQLConnection.cxx.
View newest version in sPHENIX GitHub at line 289 of file MySQLConnection.cxx
References fListOfStatements, and TSQLPreparedStatement.
Referenced by PgPostBankBackupManager::CleanTable(), PgPostBankWrapper::commit(), PgPostBankBackupManager::commit(), PgPostBankBackupManager::commitAllBankfromTFile(), CreateStuff(), createTables(), dropTable(), PgPostBankBackupLog::Init(), Populate(), populateTables(), and RDBCTestInt().
TSQLPreparedStatement * TSQLConnection::PrepareStatement (const TString & sql, Int_t resultSetType, Int_t resultSetConcurrency) pure virtual
Implemented in ODBCConnection.
Definition at line 356 of file MySQLConnection.cxx.
View newest version in sPHENIX GitHub at line 356 of file MySQLConnection.cxx
References fListOfStatements, and TSQLPreparedStatement.
void TSQLConnection::Print (Option_t * option = "") const virtual
Definition at line 1007 of file MySQLConnection.cxx.
View newest version in sPHENIX GitHub at line 1007 of file MySQLConnection.cxx
References catalogInfo(), driverInfo(), fMetaData, funcInfo(), TSQLDatabaseMetaData::GetURL(), keywordInfo(), kTYPE_FORWARD_ONLY, kTYPE_SCROLL_INSENSITIVE, kTYPE_SCROLL_SENSITIVE, printf(), productInfo(), rsInfo(), schemaInfo(), and transactionInfo().
Referenced by Fill(), and ls().
void TSQLConnection::Rollback () pure virtual
Implemented in ODBCConnection.
Definition at line 494 of file MySQLConnection.cxx.
View newest version in sPHENIX GitHub at line 494 of file MySQLConnection.cxx
References IsClosed(), and TSQL::Throw().
Referenced by PgPostApplication::abort().
void TSQLConnection::SetAutoCommit (Bool_t autoCommit = kTRUE) pure virtual
Implemented in ODBCConnection.
Definition at line 432 of file MySQLConnection.cxx.
View newest version in sPHENIX GitHub at line 432 of file MySQLConnection.cxx
References TSQL::Throw().
Referenced by oproducer().
void TSQLConnection::SetCatalog (const TString & catalog) pure virtual
Implemented in ODBCConnection.
Definition at line 624 of file MySQLConnection.cxx.
View newest version in sPHENIX GitHub at line 624 of file MySQLConnection.cxx
References TSQL::fImp, MySQLConnectionPrivate::fMYSQL, IsClosed(), and TSQL::Throw().
Referenced by TSQLStatement::Execute(), and TSQLStatement::ExecuteQuery().
void TSQLConnection::SetReadOnly (Bool_t readOnly = kTRUE) pure virtual
Implemented in ODBCConnection.
Definition at line 585 of file MySQLConnection.cxx.
View newest version in sPHENIX GitHub at line 585 of file MySQLConnection.cxx
References TSQL::fImp, MySQLConnectionPrivate::fReadOnly, IsClosed(), and TSQL::Throw().
void TSQLConnection::SetTrace (Bool_t trace = kTRUE) pure virtual
Implemented in ODBCConnection.
Definition at line 717 of file MySQLConnection.cxx.
View newest version in sPHENIX GitHub at line 717 of file MySQLConnection.cxx
References TSQL::Throw().
void TSQLConnection::SetTraceFile (const TString & filename) pure virtual
Implemented in ODBCConnection.
Definition at line 734 of file MySQLConnection.cxx.
View newest version in sPHENIX GitHub at line 734 of file MySQLConnection.cxx
References TSQL::Throw().
void TSQLConnection::SetTransactionIsolation (Int_t level) pure virtual
Implemented in ODBCConnection.
Definition at line 669 of file MySQLConnection.cxx.
View newest version in sPHENIX GitHub at line 669 of file MySQLConnection.cxx
References IsClosed(), and TSQL::Throw().
void TSQLConnection::SetURL (const TString & url) protected
Definition at line 753 of file MySQLConnection.cxx.
View newest version in sPHENIX GitHub at line 753 of file MySQLConnection.cxx
References TSQL::fImp, fMetaData, MySQLConnectionPrivate::fURL, TSQLDatabaseMetaData::SetURL(), and summary::url.
Referenced by TSQLDriverManager::GetConnection().
Friends And Related Function Documentation
friend class TSQLDriverManager friend
Definition at line 39 of file TSQLConnection.h.
View newest version in sPHENIX GitHub at line 39 of file TSQLConnection.h
Member Data Documentation
TList* TSQLConnection::fListOfStatements protected
Definition at line 43 of file TSQLConnection.h.
View newest version in sPHENIX GitHub at line 43 of file TSQLConnection.h
Referenced by Close(), ODBCConnection::CreateStatement(), CreateStatement(), GetListOfStatements(), ODBCConnection::PrepareCall(), ODBCConnection::PrepareStatement(), PrepareStatement(), TSQLConnection(), and ODBCConnection::~ODBCConnection().
TSQLDatabaseMetaData* TSQLConnection::fMetaData protected
Definition at line 42 of file TSQLConnection.h.
View newest version in sPHENIX GitHub at line 42 of file TSQLConnection.h
Referenced by ClassImpQ(), ODBCConnection::Close(), Close(), ODBCConnection::GetMetaData(), GetMetaData(), GetName(), ODBCConnection::ODBCConnection(), Print(), SetURL(), TSQLConnection(), and ODBCConnection::~ODBCConnection().
The documentation for this class was generated from the following files:
RDBC/blob/master/include/RDBC/TSQLConnection.h
RDBC/blob/master/mysql/MySQLConnection.cxx
RDBC/blob/master/rdbc/TSQLConnection.cxx