Analysis Software: ActsExamples::RootBFieldWriter< bfield_t > Class Template Reference
ActsExamples::RootBFieldWriter< bfield_t > Class Template Reference
#include <acts/blob/sPHENIX/Examples/Io/Root/include/ActsExamples/Io/Root/RootBFieldWriter.hpp>
Classes
struct Config
Public Types
enum GridType
Describes the axes definition of the grid of the magnetic field map.
Static Public Member Functions
static void run (const Config &cfg, std::unique_ptr< const Acts::Logger > p_logger=Acts::getDefaultLogger("RootBFieldWriter", Acts::Logging::INFO))
Write down an interpolated magnetic field map.
Detailed Description
template<typename bfield_t>
class ActsExamples::RootBFieldWriter< bfield_t >
Writes out the Acts::InterpolatedbFieldMap. Currently implemented for 'rz' and 'xyz' field maps.
Definition at line 37 of file RootBFieldWriter.hpp.
View newest version in sPHENIX GitHub at line 37 of file RootBFieldWriter.hpp
Member Enumeration Documentation
template<typename bfield_t > enum ActsExamples::RootBFieldWriter::GridType
Describes the axes definition of the grid of the magnetic field map.
Definition at line 40 of file RootBFieldWriter.hpp.
View newest version in sPHENIX GitHub at line 40 of file RootBFieldWriter.hpp
Member Function Documentation
template<typename bfield_t > static void ActsExamples::RootBFieldWriter< bfield_t >::run (const Config & cfg, std::unique_ptr< const Acts::Logger > p_logger = Acts::getDefaultLogger("RootBFieldWriter< bfield_t >", Acts::Logging::INFO)) inline static
Write down an interpolated magnetic field map.
Definition at line 77 of file RootBFieldWriter.hpp.
View newest version in sPHENIX GitHub at line 77 of file RootBFieldWriter.hpp
References ACTS_INFO, ACTS_LOCAL_LOGGER, ActsExamples::RootBFieldWriter< bfield_t >::Config::bField, Acts::IntegrationTest::bField, Acts::IntegrationTest::Bz, ActsExamples::RootBFieldWriter< bfield_t >::Config::fileMode, ActsExamples::RootBFieldWriter< bfield_t >::Config::fileName, ActsExamples::RootBFieldWriter< bfield_t >::Config::gridType, i, j, k, M_PI, mapper(), maxR, maxZ, Acts::Test::minPhi, minR, Acts::UnitConstants::mm, testing::internal::move(), Acts::IntegrationTest::nBinsR, Acts::IntegrationTest::nBinsZ, Acts::VectorHelpers::perp(), phi, ActsExamples::RootBFieldWriter< bfield_t >::Config::phiBins, position, r, ActsExamples::RootBFieldWriter< bfield_t >::Config::rBins, ActsExamples::RootBFieldWriter< bfield_t >::Config::rBounds, Acts::UnitConstants::T, ActsExamples::RootBFieldWriter< bfield_t >::Config::treeName, x, y, z, ActsExamples::RootBFieldWriter< bfield_t >::Config::zBins, and ActsExamples::RootBFieldWriter< bfield_t >::Config::zBounds.
Referenced by ActsExamples::BField::writeField().
The documentation for this class was generated from the following file:
acts/blob/sPHENIX/Examples/Io/Root/include/ActsExamples/Io/Root/RootBFieldWriter.hpp