Analysis Software: Acts::GeometryObject Class Reference
Acts::GeometryObject Class Reference abstract
#include <acts/blob/sPHENIX/Core/include/Acts/Geometry/GeometryObject.hpp>
Public Member Functions
GeometryObject ()=default
Defaulted constructor.
GeometryObject (const GeometryObject &)=default
Defaulted copy constructor.
GeometryObject (const GeometryIdentifier &geometryId)
GeometryObject & operator= (const GeometryObject &geometryId)
const GeometryIdentifier & geometryId () const
virtual Vector3 binningPosition (const GeometryContext &gctx, BinningValue bValue) const =0
virtual double binningPositionValue (const GeometryContext &gctx, BinningValue bValue) const
void assignGeometryId (const GeometryIdentifier &geometryId)
Protected Attributes
GeometryIdentifier m_geometryId
Detailed Description
Base class to provide GeometryIdentifier interface:
simple set and get
It also provides the binningPosition method for Geometry geometrical object to be binned in BinnedArrays
Definition at line 26 of file GeometryObject.hpp.
View newest version in sPHENIX GitHub at line 26 of file GeometryObject.hpp
Constructor & Destructor Documentation
Acts::GeometryObject::GeometryObject () default
Defaulted constructor.
Acts::GeometryObject::GeometryObject (const GeometryObject &) default
Defaulted copy constructor.
Acts::GeometryObject::GeometryObject (const GeometryIdentifier & geometryId) inline
Constructor from a value
Parameters
geometryId the geometry identifier of the object
Definition at line 37 of file GeometryObject.hpp.
View newest version in sPHENIX GitHub at line 37 of file GeometryObject.hpp
Member Function Documentation
void Acts::GeometryObject::assignGeometryId (const GeometryIdentifier & geometryId) inline
Set the value
Parameters
geometryId the geometry identifier to be assigned
Definition at line 84 of file GeometryObject.hpp.
View newest version in sPHENIX GitHub at line 84 of file GeometryObject.hpp
References geometryId(), and m_geometryId.
Referenced by Acts::Experimental::GeometryIdGenerator::assignGeometryId(), Acts::Layer::closeGeometry(), and Acts::TrackingVolume::closeGeometry().
virtual Vector3 Acts::GeometryObject::binningPosition (const GeometryContext & gctx, BinningValue bValue) const pure virtual
Force a binning position method
Parameters
gctx The current geometry context object, e.g. alignment
bValue is the value in which you want to bin
Returns
vector 3D used for the binning schema
Implemented in Acts::LineSurface, Acts::PlaneSurface, Acts::CylinderSurface, Acts::ConeSurface, Acts::Volume, Acts::SurfaceStub, and Acts::NavigationLayer.
Referenced by binningPositionValue(), Acts::SurfaceArrayCreator::createEquidistantAxis(), Acts::SurfaceArrayCreator::createVariableAxis(), Acts::SurfaceArrayCreator::isSurfaceEquivalent(), and Acts::Experimental::detail::BinningValueReferenceGenerator< bVAL >::references().
double Acts::GeometryObject::binningPositionValue (const GeometryContext & gctx, BinningValue bValue) const inline virtual
Implement the binningValue
Parameters
gctx The current geometry context object, e.g. alignment
bValue is the dobule in which you want to bin
Returns
float to be used for the binning schema
Definition at line 89 of file GeometryObject.hpp.
View newest version in sPHENIX GitHub at line 89 of file GeometryObject.hpp
References binningPosition(), and Acts::VectorHelpers::cast().
Referenced by ActsFatras::Channelizer::segments().
const GeometryIdentifier & Acts::GeometryObject::geometryId () const inline
Returns
the geometry id by reference
Definition at line 80 of file GeometryObject.hpp.
View newest version in sPHENIX GitHub at line 80 of file GeometryObject.hpp
References m_geometryId.
Referenced by assignGeometryId(), Acts::Experimental::GeometryIdGenerator::assignGeometryId(), ActsExamples::averageSimHits(), Acts::Test::BOOST_AUTO_TEST_CASE(), Acts::VolumeMaterialMapper::checkAndInsert(), Acts::SurfaceMaterialMapper::checkAndInsert(), ActsPropagator::checkLayer(), ActsExamples::RootMaterialWriter::collectMaterial(), Acts::SurfaceMaterialMapper::collectMaterialVolumes(), Acts::Layer::compatibleSurfaces(), Acts::PodioUtil::convertSurfaceToPodio(), Acts::MaterialMapJsonConverter::convertToHierarchy(), Acts::EventDataView3DTest::createDetector(), Acts::JsonMaterialDecorator::decorate(), Acts::GeometryView3D::drawTrackingVolume(), Acts::KalmanFitter< propagator_t, traj_t >::Actor< parameters_t >::filter(), Acts::CombinatorialKalmanFilter< propagator_t, traj_t >::Actor< source_link_accessor_t, parameters_t >::filter(), Acts::KalmanFitter< propagator_t, traj_t >::fit(), ActsExamples::RefittingCalibrator::RefittingSourceLink::geometryId(), Acts::InteractionVolume::geometryId(), ActsSurfaceMaps::isMicromegasSurface(), ActsSurfaceMaps::isTpcSurface(), Acts::detail::kalmanHandleMeasurement(), Acts::detail::kalmanHandleNoMeasurement(), ActsExamples::SeedingFTFAlgorithm::LayerNumbering(), Acts::KalmanFitter< propagator_t, traj_t >::Actor< parameters_t >::materialInteractor(), Acts::CombinatorialKalmanFilter< propagator_t, traj_t >::Actor< source_link_accessor_t, parameters_t >::materialInteractor(), ResidualOutlierFinder::operator()(), ActsExamples::DigitizationConfigurator::operator()(), ActsFatras::detail::SimulationActor< generator_t, decay_t, interactions_t, hit_surface_selector_t >::operator()(), Acts::VolumeMaterialMapper::BoundSurfaceSelector::operator()(), ActsExamples::PlanarSteppingAlgorithm::PlanarSteppingAlgorithm(), Acts::detail::printBoundParameters(), ActsExamples::IndexSourceLinkAccessor::range(), ActsExamples::SensitiveSurfaceMapper::remapSensitiveNames(), Acts::KalmanFitter< propagator_t, traj_t >::Actor< parameters_t >::reversedFilter(), Acts::Test::runTest(), Acts::SurfaceJsonConverter::toJson(), Acts::SurfaceJsonConverter::toJsonDetray(), Acts::TrackingGeometry::TrackingGeometry(), sPHENIXActsDetectorElement::transform(), Acts::detail::updateSingleSurfaceStatus(), Acts::MultiEigenStepperLoop< extensionlist_t, component_reducer_t, auctioneer_t >::updateSurfaceStatus(), Acts::MappingMaterialDecorator::volumeLoop(), and ActsExamples::RootMaterialTrackWriter::writeT().
GeometryObject& Acts::GeometryObject::operator= (const GeometryObject & geometryId) inline
Assignment operator
Parameters
geometryId the source geometryId
Definition at line 43 of file GeometryObject.hpp.
View newest version in sPHENIX GitHub at line 43 of file GeometryObject.hpp
References m_geometryId.
Referenced by Acts::Surface::operator=().
Member Data Documentation
GeometryIdentifier Acts::GeometryObject::m_geometryId protected
Definition at line 77 of file GeometryObject.hpp.
View newest version in sPHENIX GitHub at line 77 of file GeometryObject.hpp
Referenced by assignGeometryId(), BOOST_AUTO_TEST_CASE(), geometryId(), and operator=().
The documentation for this class was generated from the following file:
acts/blob/sPHENIX/Core/include/Acts/Geometry/GeometryObject.hpp