Analysis Software: PHG4OuterHcalSteppingAction Class Reference
PHG4OuterHcalSteppingAction Class Reference
#include <coresoftware/blob/master/simulation/g4simulation/g4detectors/PHG4OuterHcalSteppingAction.h>
Public Member Functions
PHG4OuterHcalSteppingAction (PHG4OuterHcalDetector *, const PHParameters *parameters)
constructor
~PHG4OuterHcalSteppingAction () override
destructor
bool UserSteppingAction (const G4Step *, bool) override
stepping action
int InitWithNode (PHCompositeNode *topNode) override
void SetInterfacePointers (PHCompositeNode *) override
reimplemented from base class
void FieldChecker (const G4Step *)
void EnableFieldChecker (const int i=1)
void CreateNodeTree (PHCompositeNode *topNode)
Public Member Functions inherited from PHG4SteppingAction
PHG4SteppingAction (const std::string &name, const int i=0)
virtual ~PHG4SteppingAction ()
virtual void Verbosity (const int i)
virtual int Verbosity () const
virtual int Init ()
virtual double GetScintLightYield (const G4Step *step)
get scintillation photon count. It require a custom set SCINTILLATIONYIELD property to work
virtual double GetVisibleEnergyDeposition (const G4Step *step)
get amount of energy that can make scintillation light, in Unit of GeV.
virtual void StoreLocalCoordinate (PHG4Hit *hit, const G4Step *step, const bool do_prepoint, const bool do_postpoint)
Extract local coordinate of the hit and save to PHG4Hit.
virtual void Print (const std::string &) const
std::string GetName () const
void SetName (const std::string &name)
virtual void SetLightCorrection (const double inner_radius, const double inner_corr, const double outer_radius, const double outer_corr)
virtual double GetLightCorrection (const double r) const
virtual double GetLightCorrection (const double xpos, const double ypos) const
virtual bool ValidCorrection () const
virtual void SetHitNodeName (const std::string &, const std::string &)
Set the G4HIT node names from Subsystem rather than constructing your own.
Private Member Functions
bool NoHitSteppingAction (const G4Step *aStep)
Private Attributes
PHG4OuterHcalDetector * m_Detector = nullptr
pointer to the detector
TH2 * m_MapCorrHist = nullptr
efficiency maps from Mephi
PHG4HitContainer * m_Hits = nullptr
pointer to hit container
PHG4HitContainer * m_AbsorberHits = nullptr
PHG4Hit * m_Hit = nullptr
const PHParameters * m_Params = nullptr
PHG4HitContainer * m_SaveHitContainer = nullptr
PHG4Shower * m_SaveShower = nullptr
G4VPhysicalVolume * m_SaveVolPre = nullptr
G4VPhysicalVolume * m_SaveVolPost = nullptr
int m_SaveTrackId = -1
int m_SavePreStepStatus = -1
int m_SavePostStepStatus = -1
int m_EnableFieldCheckerFlag = -1
int m_IsActiveFlag = -1
int m_IsBlackHoleFlag = -1
int m_NScintiPlates = -1
int m_LightScintModelFlag = 0
bool m_doG4Hit = true
double m_tmin = -20.
double m_tmax = 60.
double m_dt = 100.
TowerInfoContainer * m_CaloInfoContainer = nullptr
Detailed Description
Definition at line 19 of file PHG4OuterHcalSteppingAction.h.
View newest version in sPHENIX GitHub at line 19 of file PHG4OuterHcalSteppingAction.h
Constructor & Destructor Documentation
PHG4OuterHcalSteppingAction::PHG4OuterHcalSteppingAction (PHG4OuterHcalDetector * detector, const PHParameters * parameters)
constructor
Definition at line 77 of file PHG4OuterHcalSteppingAction.cc.
View newest version in sPHENIX GitHub at line 77 of file PHG4OuterHcalSteppingAction.cc
References Acts::UnitConstants::cm, PHParameters::get_double_param(), m_Params, and PHG4SteppingAction::SetLightCorrection().
PHG4OuterHcalSteppingAction::~PHG4OuterHcalSteppingAction () override
destructor
Definition at line 97 of file PHG4OuterHcalSteppingAction.cc.
View newest version in sPHENIX GitHub at line 97 of file PHG4OuterHcalSteppingAction.cc
References m_Hit, and m_MapCorrHist.
Member Function Documentation
void PHG4OuterHcalSteppingAction::CreateNodeTree (PHCompositeNode * topNode)
Definition at line 666 of file PHG4OuterHcalSteppingAction.cc.
View newest version in sPHENIX GitHub at line 666 of file PHG4OuterHcalSteppingAction.cc
References PHCompositeNode::addNode(), PHNodeIterator::findFirst(), m_CaloInfoContainer, m_Detector, PHCompositeNode::PHCompositeNode(), and PHG4OuterHcalDetector::SuperDetector().
Referenced by InitWithNode().
void PHG4OuterHcalSteppingAction::EnableFieldChecker (const int i = 1) inline
Definition at line 37 of file PHG4OuterHcalSteppingAction.h.
View newest version in sPHENIX GitHub at line 37 of file PHG4OuterHcalSteppingAction.h
References i, and m_EnableFieldCheckerFlag.
void PHG4OuterHcalSteppingAction::FieldChecker (const G4Step * aStep)
Definition at line 592 of file PHG4OuterHcalSteppingAction.cc.
View newest version in sPHENIX GitHub at line 592 of file PHG4OuterHcalSteppingAction.cc
References assert, Acts::UnitConstants::cm, Fun4AllServer::getHisto(), h, Fun4AllServer::instance(), Fun4AllServer::isHistoRegistered(), and Fun4AllServer::registerHisto().
Referenced by NoHitSteppingAction(), and UserSteppingAction().
int PHG4OuterHcalSteppingAction::InitWithNode (PHCompositeNode * topNode) override virtual
Reimplemented from PHG4SteppingAction.
Definition at line 108 of file PHG4OuterHcalSteppingAction.cc.
View newest version in sPHENIX GitHub at line 108 of file PHG4OuterHcalSteppingAction.cc
References Fun4AllReturnCodes::ABORTRUN, CreateNodeTree(), Acts::UnitConstants::e, Acts::Concepts::exists, file, PHParameters::get_int_param(), PHParameters::get_string_param(), CDBInterface::getUrl(), CDBInterface::instance(), m_doG4Hit, m_EnableFieldCheckerFlag, m_LightScintModelFlag, m_MapCorrHist, m_Params, PHWHERE, PHCompositeNode::print(), summary::url, and PHG4SteppingAction::Verbosity().
bool PHG4OuterHcalSteppingAction::NoHitSteppingAction (const G4Step * aStep) private
Definition at line 154 of file PHG4OuterHcalSteppingAction.cc.
View newest version in sPHENIX GitHub at line 154 of file PHG4OuterHcalSteppingAction.cc
References Acts::UnitConstants::cm, TowerInfoDefs::encode_hcal(), FieldChecker(), TowerInfo::get_energy(), TowerInfoContainer::get_tower_at_key(), PHG4OuterHcalDetector::GetLayerTowerId(), PHG4SteppingAction::GetLightCorrection(), PHG4SteppingAction::GetVisibleEnergyDeposition(), Acts::UnitConstants::GeV, PHG4OuterHcalDetector::IsInOuterHcal(), m_CaloInfoContainer, m_Detector, m_dt, m_EnableFieldCheckerFlag, m_IsActiveFlag, m_LightScintModelFlag, m_MapCorrHist, m_tmax, merge_hashes::p, and TowerInfo::set_energy().
Referenced by UserSteppingAction().
void PHG4OuterHcalSteppingAction::SetInterfacePointers (PHCompositeNode * topNode) override virtual
reimplemented from base class
Reimplemented from PHG4SteppingAction.
Definition at line 559 of file PHG4OuterHcalSteppingAction.cc.
View newest version in sPHENIX GitHub at line 559 of file PHG4OuterHcalSteppingAction.cc
References PHG4Detector::GetName(), m_AbsorberHits, m_Detector, m_Hits, PHG4OuterHcalDetector::SuperDetector(), and PHG4SteppingAction::Verbosity().
bool PHG4OuterHcalSteppingAction::UserSteppingAction (const G4Step * aStep, bool) override virtual
stepping action
Implements PHG4SteppingAction.
Definition at line 261 of file PHG4OuterHcalSteppingAction.cc.
View newest version in sPHENIX GitHub at line 261 of file PHG4OuterHcalSteppingAction.cc
References PHG4Shower::add_g4hit_id(), PHG4HitContainer::AddHit(), Acts::UnitConstants::cm, FieldChecker(), PHG4Hit::get_edep(), PHG4Hit::get_eion(), PHG4Hit::get_hit_id(), PHG4Hit::get_light_yield(), PHG4Hit::get_raw_light_yield(), PHG4Hit::get_x(), PHG4HitContainer::GetID(), PHG4OuterHcalDetector::GetLayerTowerId(), PHG4SteppingAction::GetLightCorrection(), PHG4SteppingAction::GetName(), PHG4StepStatusDecode::GetStepStatus(), PHG4SteppingAction::GetVisibleEnergyDeposition(), Acts::UnitConstants::GeV, PHG4OuterHcalDetector::IsInOuterHcal(), m_AbsorberHits, m_Detector, m_doG4Hit, m_EnableFieldCheckerFlag, m_Hit, m_Hits, m_IsActiveFlag, m_IsBlackHoleFlag, m_LightScintModelFlag, m_MapCorrHist, m_SaveHitContainer, m_SavePostStepStatus, m_SavePreStepStatus, m_SaveShower, m_SaveTrackId, m_SaveVolPost, m_SaveVolPre, NoHitSteppingAction(), merge_hashes::p, PHG4Hit::Reset(), PHG4Hit::set_edep(), PHG4Hit::set_eion(), PHG4Hit::set_light_yield(), PHG4Hit::set_raw_light_yield(), PHG4Hit::set_scint_id(), PHG4Hit::set_shower_id(), PHG4Hit::set_t(), PHG4Hit::set_trkid(), PHG4Hit::set_x(), PHG4Hit::set_y(), and PHG4Hit::set_z().
Member Data Documentation
PHG4HitContainer* PHG4OuterHcalSteppingAction::m_AbsorberHits = nullptr private
Definition at line 50 of file PHG4OuterHcalSteppingAction.h.
View newest version in sPHENIX GitHub at line 50 of file PHG4OuterHcalSteppingAction.h
Referenced by SetInterfacePointers(), and UserSteppingAction().
TowerInfoContainer* PHG4OuterHcalSteppingAction::m_CaloInfoContainer = nullptr private
Definition at line 73 of file PHG4OuterHcalSteppingAction.h.
View newest version in sPHENIX GitHub at line 73 of file PHG4OuterHcalSteppingAction.h
Referenced by CreateNodeTree(), and NoHitSteppingAction().
PHG4OuterHcalDetector* PHG4OuterHcalSteppingAction::m_Detector = nullptr private
pointer to the detector
Definition at line 43 of file PHG4OuterHcalSteppingAction.h.
View newest version in sPHENIX GitHub at line 43 of file PHG4OuterHcalSteppingAction.h
Referenced by CreateNodeTree(), NoHitSteppingAction(), SetInterfacePointers(), and UserSteppingAction().
bool PHG4OuterHcalSteppingAction::m_doG4Hit = true private
Definition at line 69 of file PHG4OuterHcalSteppingAction.h.
View newest version in sPHENIX GitHub at line 69 of file PHG4OuterHcalSteppingAction.h
Referenced by InitWithNode(), and UserSteppingAction().
double PHG4OuterHcalSteppingAction::m_dt = 100. private
Definition at line 72 of file PHG4OuterHcalSteppingAction.h.
View newest version in sPHENIX GitHub at line 72 of file PHG4OuterHcalSteppingAction.h
Referenced by NoHitSteppingAction().
int PHG4OuterHcalSteppingAction::m_EnableFieldCheckerFlag = -1 private
Definition at line 60 of file PHG4OuterHcalSteppingAction.h.
View newest version in sPHENIX GitHub at line 60 of file PHG4OuterHcalSteppingAction.h
Referenced by EnableFieldChecker(), InitWithNode(), NoHitSteppingAction(), and UserSteppingAction().
PHG4Hit* PHG4OuterHcalSteppingAction::m_Hit = nullptr private
Definition at line 51 of file PHG4OuterHcalSteppingAction.h.
View newest version in sPHENIX GitHub at line 51 of file PHG4OuterHcalSteppingAction.h
Referenced by UserSteppingAction(), and ~PHG4OuterHcalSteppingAction().
PHG4HitContainer* PHG4OuterHcalSteppingAction::m_Hits = nullptr private
pointer to hit container
Definition at line 49 of file PHG4OuterHcalSteppingAction.h.
View newest version in sPHENIX GitHub at line 49 of file PHG4OuterHcalSteppingAction.h
Referenced by SetInterfacePointers(), and UserSteppingAction().
int PHG4OuterHcalSteppingAction::m_IsActiveFlag = -1 private
Definition at line 65 of file PHG4OuterHcalSteppingAction.h.
View newest version in sPHENIX GitHub at line 65 of file PHG4OuterHcalSteppingAction.h
Referenced by NoHitSteppingAction(), and UserSteppingAction().
int PHG4OuterHcalSteppingAction::m_IsBlackHoleFlag = -1 private
Definition at line 66 of file PHG4OuterHcalSteppingAction.h.
View newest version in sPHENIX GitHub at line 66 of file PHG4OuterHcalSteppingAction.h
Referenced by UserSteppingAction().
int PHG4OuterHcalSteppingAction::m_LightScintModelFlag = 0 private
Definition at line 68 of file PHG4OuterHcalSteppingAction.h.
View newest version in sPHENIX GitHub at line 68 of file PHG4OuterHcalSteppingAction.h
Referenced by InitWithNode(), NoHitSteppingAction(), and UserSteppingAction().
TH2* PHG4OuterHcalSteppingAction::m_MapCorrHist = nullptr private
efficiency maps from Mephi
Definition at line 46 of file PHG4OuterHcalSteppingAction.h.
View newest version in sPHENIX GitHub at line 46 of file PHG4OuterHcalSteppingAction.h
Referenced by InitWithNode(), NoHitSteppingAction(), UserSteppingAction(), and ~PHG4OuterHcalSteppingAction().
int PHG4OuterHcalSteppingAction::m_NScintiPlates = -1 private
Definition at line 67 of file PHG4OuterHcalSteppingAction.h.
View newest version in sPHENIX GitHub at line 67 of file PHG4OuterHcalSteppingAction.h
const PHParameters* PHG4OuterHcalSteppingAction::m_Params = nullptr private
Definition at line 52 of file PHG4OuterHcalSteppingAction.h.
View newest version in sPHENIX GitHub at line 52 of file PHG4OuterHcalSteppingAction.h
Referenced by InitWithNode(), and PHG4OuterHcalSteppingAction().
PHG4HitContainer* PHG4OuterHcalSteppingAction::m_SaveHitContainer = nullptr private
Definition at line 53 of file PHG4OuterHcalSteppingAction.h.
View newest version in sPHENIX GitHub at line 53 of file PHG4OuterHcalSteppingAction.h
Referenced by UserSteppingAction().
int PHG4OuterHcalSteppingAction::m_SavePostStepStatus = -1 private
Definition at line 59 of file PHG4OuterHcalSteppingAction.h.
View newest version in sPHENIX GitHub at line 59 of file PHG4OuterHcalSteppingAction.h
Referenced by UserSteppingAction().
int PHG4OuterHcalSteppingAction::m_SavePreStepStatus = -1 private
Definition at line 58 of file PHG4OuterHcalSteppingAction.h.
View newest version in sPHENIX GitHub at line 58 of file PHG4OuterHcalSteppingAction.h
Referenced by UserSteppingAction().
PHG4Shower* PHG4OuterHcalSteppingAction::m_SaveShower = nullptr private
Definition at line 54 of file PHG4OuterHcalSteppingAction.h.
View newest version in sPHENIX GitHub at line 54 of file PHG4OuterHcalSteppingAction.h
Referenced by UserSteppingAction().
int PHG4OuterHcalSteppingAction::m_SaveTrackId = -1 private
Definition at line 57 of file PHG4OuterHcalSteppingAction.h.
View newest version in sPHENIX GitHub at line 57 of file PHG4OuterHcalSteppingAction.h
Referenced by UserSteppingAction().
G4VPhysicalVolume* PHG4OuterHcalSteppingAction::m_SaveVolPost = nullptr private
Definition at line 56 of file PHG4OuterHcalSteppingAction.h.
View newest version in sPHENIX GitHub at line 56 of file PHG4OuterHcalSteppingAction.h
Referenced by UserSteppingAction().
G4VPhysicalVolume* PHG4OuterHcalSteppingAction::m_SaveVolPre = nullptr private
Definition at line 55 of file PHG4OuterHcalSteppingAction.h.
View newest version in sPHENIX GitHub at line 55 of file PHG4OuterHcalSteppingAction.h
Referenced by UserSteppingAction().
double PHG4OuterHcalSteppingAction::m_tmax = 60. private
Definition at line 71 of file PHG4OuterHcalSteppingAction.h.
View newest version in sPHENIX GitHub at line 71 of file PHG4OuterHcalSteppingAction.h
Referenced by NoHitSteppingAction().
double PHG4OuterHcalSteppingAction::m_tmin = -20. private
Definition at line 70 of file PHG4OuterHcalSteppingAction.h.
View newest version in sPHENIX GitHub at line 70 of file PHG4OuterHcalSteppingAction.h
The documentation for this class was generated from the following files:
coresoftware/blob/master/simulation/g4simulation/g4detectors/PHG4OuterHcalSteppingAction.h
coresoftware/blob/master/simulation/g4simulation/g4detectors/PHG4OuterHcalSteppingAction.cc