Analysis Software: EmptyDetector Struct Reference
EmptyDetector Struct Reference
#include <acts/blob/sPHENIX/Examples/Run/Common/include/ActsExamples/Detector/EmptyDetector.hpp>
Public Member Functions
void addOptions (boost::program_options::options_description &opt) const override
std::pair
< ActsExamples::IBaseDetector::TrackingGeometryPtr,
ContextDecorators > finalize (const boost::program_options::variables_map &vm, std::shared_ptr< const Acts::IMaterialDecorator > mdecorator) override
Public Member Functions inherited from ActsExamples::IBaseDetector
virtual ~IBaseDetector ()=default
Additional Inherited Members
Public Types inherited from ActsExamples::IBaseDetector
using ContextDecorators = std::vector< std::shared_ptr< ActsExamples::IContextDecorator >>
using TrackingGeometryPtr = std::shared_ptr< const Acts::TrackingGeometry >
Detailed Description
Definition at line 17 of file EmptyDetector.hpp.
View newest version in sPHENIX GitHub at line 17 of file EmptyDetector.hpp
Member Function Documentation
void EmptyDetector::addOptions (boost::program_options::options_description & opt) const override virtual
Implements ActsExamples::IBaseDetector.
Definition at line 20 of file EmptyDetector.cpp.
View newest version in sPHENIX GitHub at line 20 of file EmptyDetector.cpp
References ActsExamples::Options::addEmptyGeometryOptions().
auto EmptyDetector::finalize (const boost::program_options::variables_map & vm, std::shared_ptr< const Acts::IMaterialDecorator > mdecorator) override virtual
Empty decorators
Implements ActsExamples::IBaseDetector.
Definition at line 25 of file EmptyDetector.cpp.
View newest version in sPHENIX GitHub at line 25 of file EmptyDetector.cpp
References Acts::TrackingVolume::create(), Acts::Test::hz, testing::internal::move(), and physmon_track_finding_ttbar::r.
The documentation for this struct was generated from the following files:
acts/blob/sPHENIX/Examples/Run/Common/include/ActsExamples/Detector/EmptyDetector.hpp
acts/blob/sPHENIX/Examples/Run/Common/src/EmptyDetector.cpp