Analysis Software: Acts::SeedFinderOptions Struct Reference
Acts::SeedFinderOptions Struct Reference
#include <acts/blob/sPHENIX/Core/include/Acts/Seeding/SeedFinderConfig.hpp>
Public Member Functions
SeedFinderOptions toInternalUnits () const
template<typename Config >
SeedFinderOptions calculateDerivedQuantities (const Config &config) const
Public Attributes
Acts::Vector2 beamPos
float bFieldInZ = 2.08 * Acts::UnitConstants::T
float pTPerHelixRadius = std::numeric_limits<float>::quiet_NaN()
float minHelixDiameter2 = std::numeric_limits<float>::quiet_NaN()
float pT2perRadius = std::numeric_limits<float>::quiet_NaN()
float sigmapT2perRadius = std::numeric_limits<float>::quiet_NaN()
float multipleScattering2 = std::numeric_limits<float>::quiet_NaN()
bool isInInternalUnits = false
Detailed Description
Definition at line 238 of file SeedFinderConfig.hpp.
View newest version in sPHENIX GitHub at line 238 of file SeedFinderConfig.hpp
Member Function Documentation
template<typename Config > SeedFinderOptions Acts::SeedFinderOptions::calculateDerivedQuantities (const Config & config) const inline
Definition at line 271 of file SeedFinderConfig.hpp.
View newest version in sPHENIX GitHub at line 271 of file SeedFinderConfig.hpp
References Acts::SeedFinderConfig< SpacePoint >::isInInternalUnits, and ckf::options.
Referenced by PHActsSiliconSeeding::configureSeeder(), PHActsKDTreeSeeding::configureSeedFinder(), main(), ActsExamples::SeedingAlgorithm::SeedingAlgorithm(), ActsExamples::SeedingFTFAlgorithm::SeedingFTFAlgorithm(), and ActsExamples::SeedingOrthogonalAlgorithm::SeedingOrthogonalAlgorithm().
SeedFinderOptions Acts::SeedFinderOptions::toInternalUnits () const inline
Definition at line 255 of file SeedFinderConfig.hpp.
View newest version in sPHENIX GitHub at line 255 of file SeedFinderConfig.hpp
References Acts::SeedFinderConfig< SpacePoint >::isInInternalUnits, and ckf::options.
Referenced by PHActsSiliconSeeding::configureSeeder(), PHActsKDTreeSeeding::configureSeedFinder(), main(), ActsExamples::SeedingAlgorithm::SeedingAlgorithm(), ActsExamples::SeedingFTFAlgorithm::SeedingFTFAlgorithm(), and ActsExamples::SeedingOrthogonalAlgorithm::SeedingOrthogonalAlgorithm().
Member Data Documentation
Acts::Vector2 Acts::SeedFinderOptions::beamPos
Initial value:
{0 * Acts::UnitConstants::mm,
                        0 * Acts::UnitConstants::mm}
Definition at line 241 of file SeedFinderConfig.hpp.
View newest version in sPHENIX GitHub at line 241 of file SeedFinderConfig.hpp
Referenced by Acts::BinnedSPGroup< external_spacepoint_t >::BinnedSPGroup(), PHActsKDTreeSeeding::configureSeedFinder(), Acts::SeedFinderOrthogonal< external_spacepoint_t >::createSeeds(), main(), PHActsSiliconSeeding::printSeedConfigs(), runRecCKFTracks(), runSeedingExample(), and setupSeedFinderOptions().
float Acts::SeedFinderOptions::bFieldInZ = 2.08 * Acts::UnitConstants::T
Definition at line 244 of file SeedFinderConfig.hpp.
View newest version in sPHENIX GitHub at line 244 of file SeedFinderConfig.hpp
Referenced by PHActsSiliconSeeding::configureSeeder(), PHActsKDTreeSeeding::configureSeedFinder(), main(), PHActsSiliconSeeding::printSeedConfigs(), runRecCKFTracks(), runSeedingExample(), ActsExamples::SeedingAlgorithm::SeedingAlgorithm(), and setupSeedFinderOptions().
bool Acts::SeedFinderOptions::isInInternalUnits = false
Definition at line 253 of file SeedFinderConfig.hpp.
View newest version in sPHENIX GitHub at line 253 of file SeedFinderConfig.hpp
Referenced by Acts::BinnedSPGroup< external_spacepoint_t >::BinnedSPGroup(), Acts::SeedFinderOrthogonal< external_spacepoint_t >::createSeeds(), Acts::SeedFinder< external_spacepoint_t, platform_t >::createSeedsForGroup(), and Acts::Cuda::SeedFinder< external_spacepoint_t >::SeedFinder().
float Acts::SeedFinderOptions::minHelixDiameter2 = std::numeric_limits<float>::quiet_NaN()
Definition at line 248 of file SeedFinderConfig.hpp.
View newest version in sPHENIX GitHub at line 248 of file SeedFinderConfig.hpp
Referenced by Acts::SeedFinder< external_spacepoint_t, platform_t >::filterCandidates(), Acts::SeedFinderOrthogonal< external_spacepoint_t >::filterCandidates(), Acts::SeedFinder< external_spacepoint_t, platform_t >::getCompatibleDoublets(), PHActsSiliconSeeding::printSeedConfigs(), Acts::Sycl::SeedFinder< external_spacepoint_t >::SeedFinder(), and Acts::SeedFinderOrthogonal< external_spacepoint_t >::validTuple().
float Acts::SeedFinderOptions::multipleScattering2 = std::numeric_limits<float>::quiet_NaN()
Definition at line 251 of file SeedFinderConfig.hpp.
View newest version in sPHENIX GitHub at line 251 of file SeedFinderConfig.hpp
Referenced by Acts::SeedFinder< external_spacepoint_t, platform_t >::filterCandidates(), and Acts::SeedFinderOrthogonal< external_spacepoint_t >::filterCandidates().
float Acts::SeedFinderOptions::pT2perRadius = std::numeric_limits<float>::quiet_NaN()
Definition at line 249 of file SeedFinderConfig.hpp.
View newest version in sPHENIX GitHub at line 249 of file SeedFinderConfig.hpp
Referenced by PHActsSiliconSeeding::printSeedConfigs(), and Acts::Sycl::SeedFinder< external_spacepoint_t >::SeedFinder().
float Acts::SeedFinderOptions::pTPerHelixRadius = std::numeric_limits<float>::quiet_NaN()
Definition at line 247 of file SeedFinderConfig.hpp.
View newest version in sPHENIX GitHub at line 247 of file SeedFinderConfig.hpp
Referenced by Acts::SeedFinder< external_spacepoint_t, platform_t >::filterCandidates(), Acts::SeedFinderOrthogonal< external_spacepoint_t >::filterCandidates(), and PHActsSiliconSeeding::printSeedConfigs().
float Acts::SeedFinderOptions::sigmapT2perRadius = std::numeric_limits<float>::quiet_NaN()
Definition at line 250 of file SeedFinderConfig.hpp.
View newest version in sPHENIX GitHub at line 250 of file SeedFinderConfig.hpp
Referenced by Acts::SeedFinder< external_spacepoint_t, platform_t >::filterCandidates(), Acts::SeedFinderOrthogonal< external_spacepoint_t >::filterCandidates(), and PHActsSiliconSeeding::printSeedConfigs().
The documentation for this struct was generated from the following file:
acts/blob/sPHENIX/Core/include/Acts/Seeding/SeedFinderConfig.hpp