Analysis Software: ActsExamples::Geant4SimulationBase Class Reference
ActsExamples::Geant4SimulationBase Class Reference abstract
Abstracts common Geant4 Acts algorithm behaviour.
#include <acts/blob/sPHENIX/Examples/Algorithms/Geant4/include/ActsExamples/Geant4/Geant4Simulation.hpp>
Classes
struct Config
Nested configuration struct for the Geant4 simulation.
Public Member Functions
Geant4SimulationBase (const Config &cfg, std::string name, Acts::Logging::Level level)
~Geant4SimulationBase () override
ProcessCode initialize () final
Initialize the algorithm.
ActsExamples::ProcessCode execute (const ActsExamples::AlgorithmContext &ctx) const override
virtual const Config & config () const =0
Readonly access to the configuration.
std::shared_ptr< Geant4Handle > geant4Handle () const
Public Member Functions inherited from ActsExamples::IAlgorithm
IAlgorithm (std::string name, Acts::Logging::Level level=Acts::Logging::INFO)
std::string name () const override
The algorithm name.
ProcessCode internalExecute (const AlgorithmContext &context) final
ProcessCode initialize () override
Initialize the algorithm.
ProcessCode finalize () override
Finalize the algorithm.
Protected Member Functions
void commonInitialization ()
G4RunManager & runManager () const
EventStore & eventStore () const
Protected Member Functions inherited from ActsExamples::IAlgorithm
const Acts::Logger & logger () const
Protected Attributes
std::unique_ptr< const
Acts::Logger > m_logger
std::shared_ptr< EventStore > m_eventStore
int m_geant4Level {}
std::shared_ptr< Geant4Handle > m_geant4Instance
G4VUserDetectorConstruction * m_detectorConstruction {}
ReadDataHandle
< SimParticleContainer > m_inputParticles {this, "InputParticles"}
Detailed Description
Abstracts common Geant4 Acts algorithm behaviour.
Definition at line 52 of file Geant4Simulation.hpp.
View newest version in sPHENIX GitHub at line 52 of file Geant4Simulation.hpp
Constructor & Destructor Documentation
ActsExamples::Geant4SimulationBase::Geant4SimulationBase (const Config & cfg, std::string name, Acts::Logging::Level level)
Definition at line 54 of file Geant4Simulation.cpp.
View newest version in sPHENIX GitHub at line 54 of file Geant4Simulation.cpp
References ActsExamples::Geant4SimulationBase::Config::detectorConstructionFactory, Acts::getDefaultLogger(), ActsExamples::Geant4SimulationBase::Config::inputParticles, Acts::Logger::level(), ActsExamples::IAlgorithm::logger(), m_eventStore, m_geant4Level, m_logger, ActsExamples::Geant4SimulationBase::Config::randomNumbers, and Acts::Logging::VERBOSE.
ActsExamples::Geant4SimulationBase::~Geant4SimulationBase () override default
Member Function Documentation
void ActsExamples::Geant4SimulationBase::commonInitialization () protected
Definition at line 79 of file Geant4Simulation.cpp.
View newest version in sPHENIX GitHub at line 79 of file Geant4Simulation.cpp
References filter::config.
Referenced by ActsExamples::Geant4MaterialRecording::Geant4MaterialRecording(), and ActsExamples::Geant4Simulation::Geant4Simulation().
virtual const Config& ActsExamples::Geant4SimulationBase::config () const pure virtual
Readonly access to the configuration.
Implemented in ActsExamples::Geant4MaterialRecording, and ActsExamples::Geant4Simulation.
ActsExamples::EventStore & ActsExamples::Geant4SimulationBase::eventStore () const protected
Definition at line 98 of file Geant4Simulation.cpp.
View newest version in sPHENIX GitHub at line 98 of file Geant4Simulation.cpp
ActsExamples::ProcessCode ActsExamples::Geant4SimulationBase::execute (const ActsExamples::AlgorithmContext & ctx) const override virtual
Algorithm execute method, called once per event with context
Parameters
ctx the AlgorithmContext for this event
Implements ActsExamples::IAlgorithm.
Reimplemented in ActsExamples::Geant4MaterialRecording, and ActsExamples::Geant4Simulation.
Definition at line 110 of file Geant4Simulation.cpp.
View newest version in sPHENIX GitHub at line 110 of file Geant4Simulation.cpp
References ACTS_DEBUG, ACTS_WARNING, filter::config, ActsExamples::AlgorithmContext::eventStore, physmon_simulation::randomNumbers, ActsExamples::EventStore::store, SUCCESS, and throw_assert.
Referenced by ActsExamples::Geant4Simulation::execute(), and ActsExamples::Geant4MaterialRecording::execute().
std::shared_ptr< ActsExamples::Geant4Handle > ActsExamples::Geant4SimulationBase::geant4Handle () const
Definition at line 170 of file Geant4Simulation.cpp.
View newest version in sPHENIX GitHub at line 170 of file Geant4Simulation.cpp
ActsExamples::ProcessCode ActsExamples::Geant4SimulationBase::initialize () final virtual
Initialize the algorithm.
Implements ActsExamples::SequenceElement.
Definition at line 103 of file Geant4Simulation.cpp.
View newest version in sPHENIX GitHub at line 103 of file Geant4Simulation.cpp
References SUCCESS.
G4RunManager & ActsExamples::Geant4SimulationBase::runManager () const protected
Definition at line 94 of file Geant4Simulation.cpp.
View newest version in sPHENIX GitHub at line 94 of file Geant4Simulation.cpp
Referenced by ActsExamples::Geant4MaterialRecording::Geant4MaterialRecording(), and ActsExamples::Geant4Simulation::Geant4Simulation().
Member Data Documentation
G4VUserDetectorConstruction* ActsExamples::Geant4SimulationBase::m_detectorConstruction {} protected
Detector construction object. G4RunManager will take care of deletion
Definition at line 106 of file Geant4Simulation.hpp.
View newest version in sPHENIX GitHub at line 106 of file Geant4Simulation.hpp
Referenced by ActsExamples::Geant4Simulation::Geant4Simulation().
std::shared_ptr<EventStore> ActsExamples::Geant4SimulationBase::m_eventStore protected
Definition at line 98 of file Geant4Simulation.hpp.
View newest version in sPHENIX GitHub at line 98 of file Geant4Simulation.hpp
Referenced by ActsExamples::Geant4MaterialRecording::Geant4MaterialRecording(), ActsExamples::Geant4Simulation::Geant4Simulation(), and Geant4SimulationBase().
std::shared_ptr<Geant4Handle> ActsExamples::Geant4SimulationBase::m_geant4Instance protected
Definition at line 102 of file Geant4Simulation.hpp.
View newest version in sPHENIX GitHub at line 102 of file Geant4Simulation.hpp
Referenced by ActsExamples::Geant4MaterialRecording::Geant4MaterialRecording(), and ActsExamples::Geant4Simulation::Geant4Simulation().
int ActsExamples::Geant4SimulationBase::m_geant4Level {} protected
Definition at line 100 of file Geant4Simulation.hpp.
View newest version in sPHENIX GitHub at line 100 of file Geant4Simulation.hpp
Referenced by ActsExamples::Geant4MaterialRecording::Geant4MaterialRecording(), ActsExamples::Geant4Simulation::Geant4Simulation(), and Geant4SimulationBase().
ReadDataHandle<SimParticleContainer> ActsExamples::Geant4SimulationBase::m_inputParticles {this, "InputParticles"} protected
Definition at line 108 of file Geant4Simulation.hpp.
View newest version in sPHENIX GitHub at line 108 of file Geant4Simulation.hpp
Referenced by ActsExamples::Geant4MaterialRecording::Geant4MaterialRecording(), and ActsExamples::Geant4Simulation::Geant4Simulation().
std::unique_ptr<const Acts::Logger> ActsExamples::Geant4SimulationBase::m_logger protected
Definition at line 96 of file Geant4Simulation.hpp.
View newest version in sPHENIX GitHub at line 96 of file Geant4Simulation.hpp
Referenced by ActsExamples::Geant4MaterialRecording::Geant4MaterialRecording(), ActsExamples::Geant4Simulation::Geant4Simulation(), and Geant4SimulationBase().
The documentation for this class was generated from the following files:
acts/blob/sPHENIX/Examples/Algorithms/Geant4/include/ActsExamples/Geant4/Geant4Simulation.hpp
acts/blob/sPHENIX/Examples/Algorithms/Geant4/src/Geant4Simulation.cpp