Analysis Software: oBuffer Class Reference
oBuffer Class Reference abstract
#include <online_distribution/blob/master/newbasic/oBuffer.h>
Classes
struct buffer_ptr
Public Member Functions
oBuffer ()
virtual ~oBuffer ()
virtual int nextEvent (const unsigned int evtsize, const int etype=0, const int evtseq=0)=0
virtual int addRawEvent (unsigned int *)=0
virtual int addEvent (Event *)=0
virtual int addFrame (PHDWORD *)
virtual int addPacket (const Packet *p)=0
virtual int addUnstructPacketData (PHDWORD *data, const int length, const int id, const int wordsize, const int hitformat)=0
virtual int writeout ()=0
virtual int setMaxSize (const int size)=0
virtual int getMaxSize () const =0
virtual unsigned long long getBytesWritten () const =0
virtual int addEoB ()=0
Detailed Description
Definition at line 8 of file oBuffer.h.
View newest version in sPHENIX GitHub at line 8 of file oBuffer.h
Constructor & Destructor Documentation
oBuffer::oBuffer ()
Definition at line 3 of file oBuffer.cc.
View newest version in sPHENIX GitHub at line 3 of file oBuffer.cc
oBuffer::~oBuffer () virtual
Definition at line 4 of file oBuffer.cc.
View newest version in sPHENIX GitHub at line 4 of file oBuffer.cc
Member Function Documentation
virtual int oBuffer::addEoB () pure virtual
Implemented in ophBuffer, and ospBuffer.
virtual int oBuffer::addEvent (Event *) pure virtual
Implemented in ophBuffer, and ospBuffer.
Referenced by main(), Fun4AllFileOutStream::WriteEventOut(), and Fun4AllRolloverFileOutStream::WriteEventOut().
virtual int oBuffer::addFrame (PHDWORD *) inline virtual
Reimplemented in ophBuffer, and ospBuffer.
Definition at line 37 of file oBuffer.h.
View newest version in sPHENIX GitHub at line 37 of file oBuffer.h
virtual int oBuffer::addPacket (const Packet * p) pure virtual
Implemented in ophBuffer, and ospBuffer.
virtual int oBuffer::addRawEvent (unsigned int *) pure virtual
Implemented in ophBuffer, and ospBuffer.
virtual int oBuffer::addUnstructPacketData (PHDWORD * data, const int length, const int id, const int wordsize, const int hitformat) pure virtual
Implemented in ophBuffer, and ospBuffer.
Referenced by PHRawOManager::write().
virtual unsigned long long oBuffer::getBytesWritten () const pure virtual
Implemented in ophBuffer, and ospBuffer.
Referenced by Fun4AllFileOutStream::WriteEventOut().
virtual int oBuffer::getMaxSize () const pure virtual
Implemented in ophBuffer, and ospBuffer.
virtual int oBuffer::nextEvent (const unsigned int evtsize, const int etype = 0, const int evtseq = 0) pure virtual
Implemented in ophBuffer, and ospBuffer.
Referenced by PHRawOManager::write().
virtual int oBuffer::setMaxSize (const int size) pure virtual
Implemented in ophBuffer, and ospBuffer.
virtual int oBuffer::writeout () pure virtual
Implemented in ophBuffer, ospBuffer, oamlBuffer, ogzBuffer, and olzoBuffer.
The documentation for this class was generated from the following files:
online_distribution/blob/master/newbasic/oBuffer.h
online_distribution/blob/master/newbasic/oBuffer.cc