Analysis Software: Acts::MaxMomentumReducerLoop Struct Reference
Acts::MaxMomentumReducerLoop Struct Reference
#include <acts/blob/sPHENIX/Core/include/Acts/Propagator/MultiEigenStepperLoop.hpp>
Static Public Member Functions
template<typename component_range_t >
static const auto & maxAbsoluteMomentumIt (const component_range_t &cmps)
template<typename stepper_state_t >
static Vector3 position (const stepper_state_t &s)
template<typename stepper_state_t >
static Vector3 direction (const stepper_state_t &s)
template<typename stepper_state_t >
static ActsScalar qOverP (const stepper_state_t &s)
template<typename stepper_state_t >
static ActsScalar absoluteMomentum (const stepper_state_t &s)
template<typename stepper_state_t >
static Vector3 momentum (const stepper_state_t &s)
template<typename stepper_state_t >
static ActsScalar charge (const stepper_state_t &s)
template<typename stepper_state_t >
static ActsScalar time (const stepper_state_t &s)
template<typename stepper_state_t >
static FreeVector pars (const stepper_state_t &s)
template<typename stepper_state_t >
static FreeVector cov (const stepper_state_t &s)
Detailed Description
Definition at line 142 of file MultiEigenStepperLoop.hpp.
View newest version in sPHENIX GitHub at line 142 of file MultiEigenStepperLoop.hpp
Member Function Documentation
template<typename stepper_state_t > static ActsScalar Acts::MaxMomentumReducerLoop::absoluteMomentum (const stepper_state_t & s) inline static
Definition at line 171 of file MultiEigenStepperLoop.hpp.
View newest version in sPHENIX GitHub at line 171 of file MultiEigenStepperLoop.hpp
References root_event_diff_np::cmp(), and Acts::eFreeQOverP.
template<typename stepper_state_t > static ActsScalar Acts::MaxMomentumReducerLoop::charge (const stepper_state_t & s) inline static
Definition at line 184 of file MultiEigenStepperLoop.hpp.
View newest version in sPHENIX GitHub at line 184 of file MultiEigenStepperLoop.hpp
template<typename stepper_state_t > static FreeVector Acts::MaxMomentumReducerLoop::cov (const stepper_state_t & s) inline static
Definition at line 199 of file MultiEigenStepperLoop.hpp.
View newest version in sPHENIX GitHub at line 199 of file MultiEigenStepperLoop.hpp
template<typename stepper_state_t > static Vector3 Acts::MaxMomentumReducerLoop::direction (const stepper_state_t & s) inline static
Definition at line 159 of file MultiEigenStepperLoop.hpp.
View newest version in sPHENIX GitHub at line 159 of file MultiEigenStepperLoop.hpp
References Acts::eFreeDir0.
template<typename component_range_t > static const auto& Acts::MaxMomentumReducerLoop::maxAbsoluteMomentumIt (const component_range_t & cmps) inline static
Definition at line 144 of file MultiEigenStepperLoop.hpp.
View newest version in sPHENIX GitHub at line 144 of file MultiEigenStepperLoop.hpp
References KFPMath::a, KFPMath::b, and Acts::eFreeQOverP.
template<typename stepper_state_t > static Vector3 Acts::MaxMomentumReducerLoop::momentum (const stepper_state_t & s) inline static
Definition at line 177 of file MultiEigenStepperLoop.hpp.
View newest version in sPHENIX GitHub at line 177 of file MultiEigenStepperLoop.hpp
References root_event_diff_np::cmp(), Acts::eFreeDir0, and Acts::eFreeQOverP.
template<typename stepper_state_t > static FreeVector Acts::MaxMomentumReducerLoop::pars (const stepper_state_t & s) inline static
Definition at line 194 of file MultiEigenStepperLoop.hpp.
View newest version in sPHENIX GitHub at line 194 of file MultiEigenStepperLoop.hpp
template<typename stepper_state_t > static Vector3 Acts::MaxMomentumReducerLoop::position (const stepper_state_t & s) inline static
Definition at line 153 of file MultiEigenStepperLoop.hpp.
View newest version in sPHENIX GitHub at line 153 of file MultiEigenStepperLoop.hpp
References Acts::eFreePos0.
template<typename stepper_state_t > static ActsScalar Acts::MaxMomentumReducerLoop::qOverP (const stepper_state_t & s) inline static
Definition at line 165 of file MultiEigenStepperLoop.hpp.
View newest version in sPHENIX GitHub at line 165 of file MultiEigenStepperLoop.hpp
References root_event_diff_np::cmp(), and Acts::eFreeQOverP.
template<typename stepper_state_t > static ActsScalar Acts::MaxMomentumReducerLoop::time (const stepper_state_t & s) inline static
Definition at line 189 of file MultiEigenStepperLoop.hpp.
View newest version in sPHENIX GitHub at line 189 of file MultiEigenStepperLoop.hpp
References Acts::eFreeTime.
The documentation for this struct was generated from the following file:
acts/blob/sPHENIX/Core/include/Acts/Propagator/MultiEigenStepperLoop.hpp