Analysis Software: ActsExamples::TrajectoriesToPrototracks Exception Reference
ActsExamples::TrajectoriesToPrototracks Exception Reference final
#include <acts/blob/sPHENIX/Examples/Algorithms/Utilities/include/ActsExamples/Utilities/TrajectoriesToPrototracks.hpp>
Classes
struct Config
Public Member Functions
TrajectoriesToPrototracks (Config cfg, Acts::Logging::Level lvl)
ProcessCode execute (const AlgorithmContext &ctx) const final
const Config & config () const
Const access to the config.
Public Member Functions inherited from ActsExamples::IAlgorithm
IAlgorithm (std::string name, Acts::Logging::Level level=Acts::Logging::INFO)
std::string name () const override
The algorithm name.
ProcessCode internalExecute (const AlgorithmContext &context) final
ProcessCode initialize () override
Initialize the algorithm.
ProcessCode finalize () override
Finalize the algorithm.
Private Attributes
Config m_cfg
ReadDataHandle
< TrajectoriesContainer > m_inputTrajectories
WriteDataHandle
< ProtoTrackContainer > m_outputProtoTracks
Additional Inherited Members
Protected Member Functions inherited from ActsExamples::IAlgorithm
const Acts::Logger & logger () const
Detailed Description
Definition at line 23 of file TrajectoriesToPrototracks.hpp.
View newest version in sPHENIX GitHub at line 23 of file TrajectoriesToPrototracks.hpp
Constructor & Destructor Documentation
ActsExamples::TrajectoriesToPrototracks::TrajectoriesToPrototracks (Config cfg, Acts::Logging::Level lvl)
Construct the algorithm.
Parameters
cfg is the algorithm configuration
lvl is the logging level
Definition at line 22 of file TrajectoriesToPrototracks.cpp.
View newest version in sPHENIX GitHub at line 22 of file TrajectoriesToPrototracks.cpp
References ActsExamples::WriteDataHandle< T >::initialize(), ActsExamples::ReadDataHandle< T >::initialize(), ActsExamples::TrajectoriesToPrototracks::Config::inputTrajectories, m_cfg, m_inputTrajectories, m_outputProtoTracks, and ActsExamples::TrajectoriesToPrototracks::Config::outputProtoTracks.
Member Function Documentation
const Config& ActsExamples::TrajectoriesToPrototracks::config () const inline
Const access to the config.
Definition at line 43 of file TrajectoriesToPrototracks.hpp.
View newest version in sPHENIX GitHub at line 43 of file TrajectoriesToPrototracks.hpp
References m_cfg.
ProcessCode ActsExamples::TrajectoriesToPrototracks::execute (const AlgorithmContext & ctx) const final virtual
Run the algorithm.
Parameters
ctx is the algorithm context with event information
Returns
a process code indication success or failure
Implements ActsExamples::IAlgorithm.
Definition at line 29 of file TrajectoriesToPrototracks.cpp.
View newest version in sPHENIX GitHub at line 29 of file TrajectoriesToPrototracks.cpp
References m_inputTrajectories, m_outputProtoTracks, Acts::MeasurementFlag, testing::internal::move(), filter::state, SUCCESS, tracks(), and trajectory.
Member Data Documentation
Config ActsExamples::TrajectoriesToPrototracks::m_cfg private
Definition at line 46 of file TrajectoriesToPrototracks.hpp.
View newest version in sPHENIX GitHub at line 46 of file TrajectoriesToPrototracks.hpp
Referenced by config(), and TrajectoriesToPrototracks().
ReadDataHandle<TrajectoriesContainer> ActsExamples::TrajectoriesToPrototracks::m_inputTrajectories private
Initial value:
{
      this, "InputTrajectories"}
Definition at line 48 of file TrajectoriesToPrototracks.hpp.
View newest version in sPHENIX GitHub at line 48 of file TrajectoriesToPrototracks.hpp
Referenced by execute(), and TrajectoriesToPrototracks().
WriteDataHandle<ProtoTrackContainer> ActsExamples::TrajectoriesToPrototracks::m_outputProtoTracks private
Initial value:
{this,
                                                           "OutputProtoTracks"}
Definition at line 51 of file TrajectoriesToPrototracks.hpp.
View newest version in sPHENIX GitHub at line 51 of file TrajectoriesToPrototracks.hpp
Referenced by execute(), and TrajectoriesToPrototracks().
The documentation for this exception was generated from the following files:
acts/blob/sPHENIX/Examples/Algorithms/Utilities/include/ActsExamples/Utilities/TrajectoriesToPrototracks.hpp
acts/blob/sPHENIX/Examples/Algorithms/Utilities/src/TrajectoriesToPrototracks.cpp