Analysis Software: TrkrTruthTrackv1::CompHitSetKey Struct Reference
TrkrTruthTrackv1::CompHitSetKey Struct Reference
#include <coresoftware/blob/master/simulation/g4simulation/g4tracking/TrkrTruthTrackv1.h>
Public Member Functions
bool operator() (const TrkrDefs::cluskey &lhs, const TrkrDefs::cluskey &rhs)
bool operator() (const TrkrDefs::cluskey &lhs, const TrkrDefs::hitsetkey &rhs)
bool operator() (const TrkrDefs::hitsetkey &lhs, const TrkrDefs::cluskey &rhs)
Detailed Description
Definition at line 52 of file TrkrTruthTrackv1.h.
View newest version in sPHENIX GitHub at line 52 of file TrkrTruthTrackv1.h
Member Function Documentation
bool TrkrTruthTrackv1::CompHitSetKey::operator() (const TrkrDefs::cluskey & lhs, const TrkrDefs::cluskey & rhs) inline
Definition at line 53 of file TrkrTruthTrackv1.h.
View newest version in sPHENIX GitHub at line 53 of file TrkrTruthTrackv1.h
References TrkrDefs::getHitSetKeyFromClusKey().
bool TrkrTruthTrackv1::CompHitSetKey::operator() (const TrkrDefs::cluskey & lhs, const TrkrDefs::hitsetkey & rhs) inline
Definition at line 56 of file TrkrTruthTrackv1.h.
View newest version in sPHENIX GitHub at line 56 of file TrkrTruthTrackv1.h
References TrkrDefs::getHitSetKeyFromClusKey(), and check_smearing_config::rhs.
bool TrkrTruthTrackv1::CompHitSetKey::operator() (const TrkrDefs::hitsetkey & lhs, const TrkrDefs::cluskey & rhs) inline
Definition at line 59 of file TrkrTruthTrackv1.h.
View newest version in sPHENIX GitHub at line 59 of file TrkrTruthTrackv1.h
References TrkrDefs::getHitSetKeyFromClusKey().
The documentation for this struct was generated from the following file:
coresoftware/blob/master/simulation/g4simulation/g4tracking/TrkrTruthTrackv1.h