Analysis Software: Acts::TrapezoidVolumeBounds Class Reference
Acts::TrapezoidVolumeBounds Class Reference
#include <acts/blob/sPHENIX/Core/include/Acts/Geometry/TrapezoidVolumeBounds.hpp>
Public Types
enum BoundValues : unsigned int {
eHalfLengthXnegY = 0, eHalfLengthXposY = 1, eHalfLengthY = 2, eHalfLengthZ = 3,
eAlpha = 4, eBeta = 5, eSize
}
for access / streaming
Public Types inherited from Acts::VolumeBounds
enum BoundsType : int {
eCone = 0, eCuboid = 1, eCutoutCylinder = 2, eCylinder = 3,
eGenericCuboid = 4, eTrapezoid = 5, eOther = 6
}
Public Member Functions
TrapezoidVolumeBounds ()=delete
TrapezoidVolumeBounds (double minhalex, double maxhalex, double haley, double halez) noexcept(false)
TrapezoidVolumeBounds (double minhalex, double haley, double halez, double alpha, double beta) noexcept(false)
TrapezoidVolumeBounds (const std::array< double, eSize > &values) noexcept(false)
TrapezoidVolumeBounds (const TrapezoidVolumeBounds &trabo)=default
~TrapezoidVolumeBounds () override=default
TrapezoidVolumeBounds & operator= (const TrapezoidVolumeBounds &trabo)=default
VolumeBounds::BoundsType type () const final
std::vector< double > values () const final
bool inside (const Vector3 &pos, double tol=0.) const override
OrientedSurfaces orientedSurfaces (const Transform3 &transform=Transform3::Identity()) const override
Volume::BoundingBox boundingBox (const Transform3 *trf=nullptr, const Vector3 &envelope={0, 0, 0}, const Volume *entity=nullptr) const final
std::ostream & toStream (std::ostream &sl) const override
Output Method for std::ostream.
double get (BoundValues bValue) const
Public Member Functions inherited from Acts::VolumeBounds
VolumeBounds ()=default
virtual ~VolumeBounds ()=default
virtual Vector3 binningOffset (BinningValue bValue) const
Binning offset - overloaded for some R-binning types.
virtual double binningBorder (BinningValue bValue) const
Private Member Functions
void checkConsistency () noexcept(false)
void buildSurfaceBounds ()
Helper method to create the surface bounds.
template<class stream_t >
stream_t & dumpT (stream_t &dt) const
Private Attributes
std::array< double, eSize > m_values {}
The internal version of the bounds can be float/double.
std::shared_ptr< const
TrapezoidBounds > m_faceXYTrapezoidBounds {nullptr}
The face PlaneSurface parallel to local xy plane.
std::shared_ptr< const
RectangleBounds > m_faceAlphaRectangleBounds {nullptr}
Thhe face PlaneSurface attached to alpha (negative local x)
std::shared_ptr< const
RectangleBounds > m_faceBetaRectangleBounds {nullptr}
The face PlaneSurface attached to beta (positive local x)
std::shared_ptr< const
RectangleBounds > m_faceZXRectangleBoundsBottom {nullptr}
The face PlaneSurface parallel to local zx plane, negative local y.
std::shared_ptr< const
RectangleBounds > m_faceZXRectangleBoundsTop {nullptr}
The face PlaneSurface parallel to local zx plane, positive local y.
Detailed Description
Bounds for a trapezoidal shaped Volume, the orientedSurface(...) method creates a vector of 6 surfaces:
BoundarySurfaceFace [index]:
negativeFaceXY [0] : Trazpezoidal Acts::PlaneSurface, parallel to plane at negative
positiveFaceXY [1] : Trazpezoidal Acts::PlaneSurface, parallel to plane at positive
trapezoidFaceAlpha [2] : Rectangular Acts::PlaneSurface, attached to [0] and [1] at negative (associated to alpha)
trapezoidFaceBeta [3] : Rectangular Acts::PlaneSurface, attached to [0] and [1] at positive (associated to beta)
negativeFaceZX [4] : Rectangular Acts::PlaneSurface, parallel to plane at negative
positiveFaceZX [5] : Rectangular Acts::PlaneSurface, parallel to plane at positive
Definition at line 50 of file TrapezoidVolumeBounds.hpp.
View newest version in sPHENIX GitHub at line 50 of file TrapezoidVolumeBounds.hpp
Member Enumeration Documentation
enum Acts::TrapezoidVolumeBounds::BoundValues : unsigned int
for access / streaming
Enumerator:
eHalfLengthXnegY
halflength in x at negative y
eHalfLengthXposY
halflength in x at positive y
eHalfLengthY
halflength in y
eHalfLengthZ
halflength in z
eAlpha
opening angle alpha (in point A)
eBeta
opening angle beta (in point B)
eSize
length of the bounds vector
Definition at line 53 of file TrapezoidVolumeBounds.hpp.
View newest version in sPHENIX GitHub at line 53 of file TrapezoidVolumeBounds.hpp
Constructor & Destructor Documentation
Acts::TrapezoidVolumeBounds::TrapezoidVolumeBounds () delete
Acts::TrapezoidVolumeBounds::TrapezoidVolumeBounds (double minhalex, double maxhalex, double haley, double halez) noexcept
Constructor - the trapezoid boundaries (symmetric trapezoid)
Parameters
minhalex is the half length in x at minimal y
maxhalex is the half length in x at maximal y
haley is the half length in y
halez is the half length in z
Definition at line 23 of file TrapezoidVolumeBounds.cpp.
View newest version in sPHENIX GitHub at line 23 of file TrapezoidVolumeBounds.cpp
References buildSurfaceBounds(), checkConsistency(), eAlpha, eBeta, eHalfLengthXnegY, eHalfLengthXposY, eHalfLengthY, eHalfLengthZ, and m_values.
Acts::TrapezoidVolumeBounds::TrapezoidVolumeBounds (double minhalex, double haley, double halez, double alpha, double beta) noexcept
Constructor - the trapezoid boundaries (arbitrary trapezoid)
Parameters
minhalex is the half length in x at minimal y
haley is the half length in y
halez is the half length in z
alpha is the opening angle at -x,-y
beta is the opening angle at +x,-y
Definition at line 37 of file TrapezoidVolumeBounds.cpp.
View newest version in sPHENIX GitHub at line 37 of file TrapezoidVolumeBounds.cpp
References alpha, buildSurfaceBounds(), checkConsistency(), eAlpha, eBeta, eHalfLengthXnegY, eHalfLengthXposY, eHalfLengthY, eHalfLengthZ, and m_values.
Acts::TrapezoidVolumeBounds::TrapezoidVolumeBounds (const std::array< double, eSize > & values) inline noexcept
Constructor - from a fixed size array
Parameters
values The bound values
Definition at line 87 of file TrapezoidVolumeBounds.hpp.
View newest version in sPHENIX GitHub at line 87 of file TrapezoidVolumeBounds.hpp
References buildSurfaceBounds(), and checkConsistency().
Acts::TrapezoidVolumeBounds::TrapezoidVolumeBounds (const TrapezoidVolumeBounds & trabo) default
Acts::TrapezoidVolumeBounds::~TrapezoidVolumeBounds () override default
Member Function Documentation
Acts::Volume::BoundingBox Acts::TrapezoidVolumeBounds::boundingBox (const Transform3 * trf = nullptr, const Vector3 & envelope = {0, 0, 0}, const Volume * entity = nullptr) const final virtual
Construct bounding box for this shape
Parameters
trf Optional transform
envelope Optional envelope to add / subtract from min/max
entity Entity to associate this bounding box with
Returns
Constructed bounding box
Implements Acts::VolumeBounds.
Definition at line 150 of file TrapezoidVolumeBounds.cpp.
View newest version in sPHENIX GitHub at line 150 of file TrapezoidVolumeBounds.cpp
References i, Acts::Test::transform, and ActsExamples::HepMC3Event::vertices().
void Acts::TrapezoidVolumeBounds::buildSurfaceBounds () private
Helper method to create the surface bounds.
Definition at line 116 of file TrapezoidVolumeBounds.cpp.
View newest version in sPHENIX GitHub at line 116 of file TrapezoidVolumeBounds.cpp
Referenced by TrapezoidVolumeBounds().
void Acts::TrapezoidVolumeBounds::checkConsistency () inline private noexcept
Check the input values for consistency, will throw a logic_exception if consistency is not given
Definition at line 191 of file TrapezoidVolumeBounds.hpp.
View newest version in sPHENIX GitHub at line 191 of file TrapezoidVolumeBounds.hpp
References eHalfLengthXnegY, eHalfLengthXposY, eHalfLengthY, and eHalfLengthZ.
Referenced by TrapezoidVolumeBounds().
template<class stream_t > stream_t & Acts::TrapezoidVolumeBounds::dumpT (stream_t & dt) const private
Templated dump methods
Template Parameters
stream_t The type of the stream for dumping
Parameters
dt The stream object
Definition at line 174 of file TrapezoidVolumeBounds.hpp.
View newest version in sPHENIX GitHub at line 174 of file TrapezoidVolumeBounds.hpp
References eAlpha, eBeta, eHalfLengthXnegY, eHalfLengthXposY, eHalfLengthY, and eHalfLengthZ.
double Acts::TrapezoidVolumeBounds::get (BoundValues bValue) const inline
Access to the bound values
Parameters
bValue the class nested enum for the array access
Definition at line 143 of file TrapezoidVolumeBounds.hpp.
View newest version in sPHENIX GitHub at line 143 of file TrapezoidVolumeBounds.hpp
References m_values.
bool Acts::TrapezoidVolumeBounds::inside (const Vector3 & pos, double tol = 0.) const override virtual
This method checks if position in the 3D volume frame is inside the cylinder
Parameters
pos is the global position to be checked
tol is the tolerance applied
Returns
boolean indicator if position is inside
Implements Acts::VolumeBounds.
Definition at line 133 of file TrapezoidVolumeBounds.cpp.
View newest version in sPHENIX GitHub at line 133 of file TrapezoidVolumeBounds.cpp
Referenced by Acts::Test::BOOST_AUTO_TEST_CASE().
TrapezoidVolumeBounds& Acts::TrapezoidVolumeBounds::operator= (const TrapezoidVolumeBounds & trabo) default
Acts::OrientedSurfaces Acts::TrapezoidVolumeBounds::orientedSurfaces (const Transform3 & transform = Transform3::Identity()) const override virtual
Oriented surfaces, i.e. the decomposed boundary surfaces and the according navigation direction into the volume given the normal vector on the surface
Parameters
transform is the 3D transform to be applied to the boundary surfaces to position them in 3D space
It will throw an exception if the orientation prescription is not adequate
Returns
a vector of surfaces bounding this volume
Implements Acts::VolumeBounds.
Definition at line 54 of file TrapezoidVolumeBounds.cpp.
View newest version in sPHENIX GitHub at line 54 of file TrapezoidVolumeBounds.cpp
References testing::internal::move(), Acts::Direction::Negative, Acts::Direction::Positive, Acts::s_planeYZ, and Acts::s_planeZX.
Referenced by Acts::Test::BOOST_AUTO_TEST_CASE().
std::ostream & Acts::TrapezoidVolumeBounds::toStream (std::ostream & sl) const override virtual
Output Method for std::ostream.
Implements Acts::VolumeBounds.
Definition at line 146 of file TrapezoidVolumeBounds.cpp.
View newest version in sPHENIX GitHub at line 146 of file TrapezoidVolumeBounds.cpp
VolumeBounds::BoundsType Acts::TrapezoidVolumeBounds::type () const inline final virtual
Return the bounds type - for persistency optimization
Returns
is a BoundsType enum
Implements Acts::VolumeBounds.
Definition at line 98 of file TrapezoidVolumeBounds.hpp.
View newest version in sPHENIX GitHub at line 98 of file TrapezoidVolumeBounds.hpp
References Acts::VolumeBounds::eTrapezoid.
std::vector< double > Acts::TrapezoidVolumeBounds::values () const inline final virtual
Return the bound values as dynamically sized vector
Returns
this returns a copy of the internal values
Implements Acts::VolumeBounds.
Definition at line 185 of file TrapezoidVolumeBounds.hpp.
View newest version in sPHENIX GitHub at line 185 of file TrapezoidVolumeBounds.hpp
References m_values.
Member Data Documentation
std::shared_ptr<const RectangleBounds> Acts::TrapezoidVolumeBounds::m_faceAlphaRectangleBounds {nullptr} private
Thhe face PlaneSurface attached to alpha (negative local x)
Definition at line 151 of file TrapezoidVolumeBounds.hpp.
View newest version in sPHENIX GitHub at line 151 of file TrapezoidVolumeBounds.hpp
std::shared_ptr<const RectangleBounds> Acts::TrapezoidVolumeBounds::m_faceBetaRectangleBounds {nullptr} private
The face PlaneSurface attached to beta (positive local x)
Definition at line 153 of file TrapezoidVolumeBounds.hpp.
View newest version in sPHENIX GitHub at line 153 of file TrapezoidVolumeBounds.hpp
std::shared_ptr<const TrapezoidBounds> Acts::TrapezoidVolumeBounds::m_faceXYTrapezoidBounds {nullptr} private
The face PlaneSurface parallel to local xy plane.
Definition at line 149 of file TrapezoidVolumeBounds.hpp.
View newest version in sPHENIX GitHub at line 149 of file TrapezoidVolumeBounds.hpp
std::shared_ptr<const RectangleBounds> Acts::TrapezoidVolumeBounds::m_faceZXRectangleBoundsBottom {nullptr} private
The face PlaneSurface parallel to local zx plane, negative local y.
Definition at line 155 of file TrapezoidVolumeBounds.hpp.
View newest version in sPHENIX GitHub at line 155 of file TrapezoidVolumeBounds.hpp
std::shared_ptr<const RectangleBounds> Acts::TrapezoidVolumeBounds::m_faceZXRectangleBoundsTop {nullptr} private
The face PlaneSurface parallel to local zx plane, positive local y.
Definition at line 157 of file TrapezoidVolumeBounds.hpp.
View newest version in sPHENIX GitHub at line 157 of file TrapezoidVolumeBounds.hpp
std::array<double, eSize> Acts::TrapezoidVolumeBounds::m_values {} private
The internal version of the bounds can be float/double.
Definition at line 147 of file TrapezoidVolumeBounds.hpp.
View newest version in sPHENIX GitHub at line 147 of file TrapezoidVolumeBounds.hpp
Referenced by get(), TrapezoidVolumeBounds(), and values().
The documentation for this class was generated from the following files:
acts/blob/sPHENIX/Core/include/Acts/Geometry/TrapezoidVolumeBounds.hpp
acts/blob/sPHENIX/Core/src/Geometry/TrapezoidVolumeBounds.cpp