Analysis Software: analysis/blob/master/Calorimeter/macros/DrawHadronShowers.C File Reference
DrawHadronShowers.C File Reference
#include <TFile.h>
#include <TLine.h>
#include <TString.h>
#include <TTree.h>
#include <cassert>
#include <cmath>
#include "SaveCanvas.C"
#include "sPhenixStyle.C"
Classes
class lin_res
Functions
void DrawHadronShowers (void)
void EtaScan (void)
void PIDScan (void)
void ClusterSizeScan (TString seta="eta0", TString eta_desc="0<|#eta|<0.1")
lin_res * GetResolution (TString PID="pi-", TString eta="eta0", TString qa_histo="h_QAG4Sim_CalorimeterSum_TrackProj_5x5Tower_EP")
TH1 * GetEvalHisto (TString PID="pi-", TString eta="eta0", TString energy="16GeV")
TH1 * GetQAHisto (TString PID="pi-", TString eta="eta0", TString energy="16GeV", TString qa_histo="h_QAG4Sim_CalorimeterSum_TrackProj_5x5Tower_EP")
Variables
TString base_dataset = "/sphenix/u/weihuma/analysis/Calorimeter/macros/"
Function Documentation
void ClusterSizeScan (TString seta = "eta0", TString eta_desc = "0<|#eta|<0.1")
Definition at line 364 of file DrawHadronShowers.C.
View newest version in sPHENIX GitHub at line 364 of file DrawHadronShowers.C
References base_dataset, filter::config, lin_res::f_res, GetResolution(), ambiguity_solver_full_chain::idx, leg, lin_res::linearity, lin_res::name, merge_hashes::p, lin_res::resolution, and SaveCanvas().
Referenced by DrawHadronShowers().
void DrawHadronShowers (void)
Definition at line 28 of file DrawHadronShowers.C.
View newest version in sPHENIX GitHub at line 28 of file DrawHadronShowers.C
References ClusterSizeScan(), and SetsPhenixStyle().
void EtaScan (void)
Definition at line 39 of file DrawHadronShowers.C.
View newest version in sPHENIX GitHub at line 39 of file DrawHadronShowers.C
References base_dataset, filter::config, lin_res::f_res, GetResolution(), ambiguity_solver_full_chain::idx, leg, lin_res::linearity, lin_res::name, merge_hashes::p, lin_res::resolution, and SaveCanvas().
TH1* GetEvalHisto (TString PID = "pi-", TString eta = "eta0", TString energy = "16GeV")
Definition at line 623 of file DrawHadronShowers.C.
View newest version in sPHENIX GitHub at line 623 of file DrawHadronShowers.C
References base_dataset, energy, eta, infile, and n.
Referenced by GetResolution().
TH1* GetQAHisto (TString PID = "pi-", TString eta = "eta0", TString energy = "16GeV", TString qa_histo = "h_QAG4Sim_CalorimeterSum_TrackProj_5x5Tower_EP")
Definition at line 643 of file DrawHadronShowers.C.
View newest version in sPHENIX GitHub at line 643 of file DrawHadronShowers.C
References assert, base_dataset, energy, eta, f, h, infile, n, next, and Acts::UnitConstants::T.
lin_res* GetResolution (TString PID = "pi-", TString eta = "eta0", TString qa_histo = "h_QAG4Sim_CalorimeterSum_TrackProj_5x5Tower_EP")
Definition at line 527 of file DrawHadronShowers.C.
View newest version in sPHENIX GitHub at line 527 of file DrawHadronShowers.C
References base_dataset, eta, lin_res::f_res, GetEvalHisto(), h, i, ambiguity_solver_full_chain::idx, lin_res::linearity, mean(), N, lin_res::name, merge_hashes::p, P(), lin_res::resolution, and SaveCanvas().
Referenced by ClusterSizeScan(), EtaScan(), Get_Res_linear_Summmary(), Get_Res_linear_Summmary_Sim(), and PIDScan().
void PIDScan (void)
Definition at line 201 of file DrawHadronShowers.C.
View newest version in sPHENIX GitHub at line 201 of file DrawHadronShowers.C
References base_dataset, filter::config, lin_res::f_res, GetResolution(), ambiguity_solver_full_chain::idx, leg, lin_res::linearity, lin_res::name, merge_hashes::p, lin_res::resolution, and SaveCanvas().
Variable Documentation
TString base_dataset = "/sphenix/u/weihuma/analysis/Calorimeter/macros/"
Definition at line 26 of file DrawHadronShowers.C.
View newest version in sPHENIX GitHub at line 26 of file DrawHadronShowers.C
Referenced by ClusterSizeScan(), EtaScan(), GetEvalHisto(), GetQAHisto(), GetResolution(), and PIDScan().