Analysis Software: PHG4HitEval Class Reference
PHG4HitEval Class Reference
PHG4HitEval for evaluating PHG4Hitv1 in CINT readable evaluation trees.
#include <coresoftware/blob/master/simulation/g4simulation/g4main/PHG4HitEval.h>
Public Member Functions
PHG4HitEval ()
PHG4HitEval (const PHG4Hit *g4hit)
~PHG4HitEval () override
void CopyFrom (const PHObject *phobj) override
float get_eion () const override
void set_eion (const float f) override
int get_scint_id () const override
void set_scint_id (const int i) override
float get_light_yield () const override
void set_light_yield (float lightYield) override
float get_path_length () const override
void set_path_length (float pathLength) override
Public Member Functions inherited from PHG4Hitv1
PHG4Hitv1 ()=default
PHG4Hitv1 (const PHG4Hit *g4hit)
~PHG4Hitv1 () override=default
void identify (std::ostream &os=std::cout) const override
void Reset () override
Clear Event.
float get_x (const int i) const override
float get_y (const int i) const override
float get_z (const int i) const override
float get_t (const int i) const override
float get_edep () const override
PHG4HitDefs::keytype get_hit_id () const override
int get_detid () const override
int get_shower_id () const override
int get_trkid () const override
void set_x (const int i, const float f) override
void set_y (const int i, const float f) override
void set_z (const int i, const float f) override
void set_t (const int i, const float f) override
void set_edep (const float f) override
void set_hit_id (const PHG4HitDefs::keytype i) override
void set_shower_id (const int i) override
void set_trkid (const int i) override
void print () const override
bool has_property (const PROPERTY prop_id) const override
float get_property_float (const PROPERTY prop_id) const override
int get_property_int (const PROPERTY prop_id) const override
unsigned int get_property_uint (const PROPERTY prop_id) const override
void set_property (const PROPERTY prop_id, const float value) override
void set_property (const PROPERTY prop_id, const int value) override
void set_property (const PROPERTY prop_id, const unsigned int value) override
float get_px (const int i) const override
float get_py (const int i) const override
float get_pz (const int i) const override
float get_local_x (const int i) const override
float get_local_y (const int i) const override
float get_local_z (const int i) const override
float get_eion () const override
float get_light_yield () const override
float get_raw_light_yield () const override
float get_path_length () const override
unsigned int get_layer () const override
int get_scint_id () const override
int get_row () const override
int get_sector () const override
int get_strip_z_index () const override
int get_strip_y_index () const override
int get_ladder_z_index () const override
int get_ladder_phi_index () const override
int get_index_i () const override
int get_index_j () const override
int get_index_k () const override
int get_index_l () const override
int get_hit_type () const override
void set_px (const int i, const float f) override
void set_py (const int i, const float f) override
void set_pz (const int i, const float f) override
void set_local_x (const int i, const float f) override
void set_local_y (const int i, const float f) override
void set_local_z (const int i, const float f) override
void set_eion (const float f) override
void set_light_yield (const float f) override
void set_raw_light_yield (const float f) override
void set_path_length (const float f) override
void set_layer (const unsigned int i) override
void set_scint_id (const int i) override
void set_row (const int i) override
void set_sector (const int i) override
void set_strip_z_index (const int i) override
void set_strip_y_index (const int i) override
void set_ladder_z_index (const int i) override
void set_ladder_phi_index (const int i) override
void set_index_i (const int i) override
void set_index_j (const int i) override
void set_index_k (const int i) override
void set_index_l (const int i) override
void set_hit_type (const int i) override
Public Member Functions inherited from PHG4Hit
PHG4Hit ()
~PHG4Hit () override
virtual float get_avg_x () const
virtual float get_avg_y () const
virtual float get_avg_z () const
virtual float get_avg_t () const
Public Member Functions inherited from PHObject
PHObject ()
ctor
~PHObject () override
dtor
virtual PHObject * CloneMe () const
Virtual copy constructor.
virtual PHObject * clone () const final
PHObject * Clone (const char *newname="") const final
void Copy (TObject &object) const final
virtual int isValid () const
isValid returns non zero if object contains vailid data
virtual int Integrate () const
virtual int Integrate (PHObject *)
Protected Attributes
float eion
int scint_id
float light_yield
a number proportional to the scintillation light yield.
float path_length
path length of the track to the hit
Protected Attributes inherited from PHG4Hitv1
float x [2] = {NAN, NAN}
float y [2] = {NAN, NAN}
float z [2] = {NAN, NAN}
float t [2] = {NAN, NAN}
PHG4HitDefs::keytype hitid = ULONG_LONG_MAX
int trackid = INT_MIN
int showerid = INT_MIN
float edep = NAN
prop_map_t prop_map
container for additional property
Additional Inherited Members
Public Types inherited from PHG4Hit
enum PROPERTY {
prop_eion = 1, prop_light_yield = 2, scint_gammas = 3, cerenkov_gammas = 4,
prop_raw_light_yield = 5, prop_px_0 = 10, prop_px_1 = 11, prop_py_0 = 12,
prop_py_1 = 13, prop_pz_0 = 14, prop_pz_1 = 15, prop_path_length = 16,
prop_local_x_0 = 20, prop_local_x_1 = 21, prop_local_y_0 = 22, prop_local_y_1 = 23,
prop_local_z_0 = 24, prop_local_z_1 = 25, prop_layer = 101, prop_scint_id = 102,
prop_row = 103, prop_sector = 104, prop_strip_z_index = 110, prop_strip_y_index = 111,
prop_ladder_z_index = 112, prop_ladder_phi_index = 113, prop_stave_index = 114, prop_half_stave_index = 115,
prop_module_index = 116, prop_chip_index = 117, prop_local_pos_x_0 = 118, prop_local_pos_y_0 = 119,
prop_local_pos_z_0 = 120, prop_index_i = 121, prop_index_j = 122, prop_index_k = 123,
prop_index_l = 124, prop_hit_type = 125, prop_local_pos_x_1 = 128, prop_local_pos_y_1 = 126,
prop_local_pos_z_1 = 127, prop_MAX_NUMBER = UCHAR_MAX
}
enum PROPERTY_TYPE { type_int = 1, type_uint = 2, type_float = 3, type_unknown = -1 }
Static Public Member Functions inherited from PHG4Hit
static std::pair< const
std::string, PROPERTY_TYPE > get_property_info (PROPERTY prop_id)
static bool check_property (const PROPERTY prop_id, const PROPERTY_TYPE prop_type)
static std::string get_property_type (const PROPERTY_TYPE prop_type)
Protected Types inherited from PHG4Hitv1
typedef uint8_t prop_id_t
storage types for additional property
typedef uint32_t prop_storage_t
typedef std::map< prop_id_t,
prop_storage_t > prop_map_t
Protected Member Functions inherited from PHG4Hitv1
unsigned int get_property_nocheck (const PROPERTY prop_id) const override
void set_property_nocheck (const PROPERTY prop_id, const unsigned int ui) override
Detailed Description
PHG4HitEval for evaluating PHG4Hitv1 in CINT readable evaluation trees.
Definition at line 24 of file PHG4HitEval.h.
View newest version in sPHENIX GitHub at line 24 of file PHG4HitEval.h
Constructor & Destructor Documentation
PHG4HitEval::PHG4HitEval ()
Definition at line 20 of file PHG4HitEval.cc.
View newest version in sPHENIX GitHub at line 20 of file PHG4HitEval.cc
PHG4HitEval::PHG4HitEval (const PHG4Hit * g4hit)
Definition at line 30 of file PHG4HitEval.cc.
View newest version in sPHENIX GitHub at line 30 of file PHG4HitEval.cc
References CopyFrom().
PHG4HitEval::~PHG4HitEval () inline override
Definition at line 31 of file PHG4HitEval.h.
View newest version in sPHENIX GitHub at line 31 of file PHG4HitEval.h
Member Function Documentation
void PHG4HitEval::CopyFrom (const PHObject * phobj) override virtual
Reimplemented from PHG4Hit.
Definition at line 39 of file PHG4HitEval.cc.
View newest version in sPHENIX GitHub at line 39 of file PHG4HitEval.cc
References assert, PHG4Hit::CopyFrom(), eion, PHG4Hit::get_eion(), PHG4Hit::get_light_yield(), PHG4Hit::get_path_length(), PHG4Hit::get_scint_id(), light_yield, path_length, and scint_id.
Referenced by PHG4HitEval().
float PHG4HitEval::get_eion () const inline override virtual
Reimplemented from PHG4Hit.
Definition at line 36 of file PHG4HitEval.h.
View newest version in sPHENIX GitHub at line 36 of file PHG4HitEval.h
References eion.
float PHG4HitEval::get_light_yield () const inline override virtual
Reimplemented from PHG4Hit.
Definition at line 58 of file PHG4HitEval.h.
View newest version in sPHENIX GitHub at line 58 of file PHG4HitEval.h
References light_yield.
float PHG4HitEval::get_path_length () const inline override virtual
Reimplemented from PHG4Hit.
Definition at line 70 of file PHG4HitEval.h.
View newest version in sPHENIX GitHub at line 70 of file PHG4HitEval.h
References path_length.
int PHG4HitEval::get_scint_id () const inline override virtual
Reimplemented from PHG4Hit.
Definition at line 46 of file PHG4HitEval.h.
View newest version in sPHENIX GitHub at line 46 of file PHG4HitEval.h
References scint_id.
void PHG4HitEval::set_eion (const float f) inline override virtual
Reimplemented from PHG4Hit.
Definition at line 41 of file PHG4HitEval.h.
View newest version in sPHENIX GitHub at line 41 of file PHG4HitEval.h
References eion, and f.
void PHG4HitEval::set_light_yield (float lightYield) inline override virtual
Reimplemented from PHG4Hit.
Definition at line 64 of file PHG4HitEval.h.
View newest version in sPHENIX GitHub at line 64 of file PHG4HitEval.h
References light_yield.
void PHG4HitEval::set_path_length (float pathLength) inline override virtual
Reimplemented from PHG4Hit.
Definition at line 76 of file PHG4HitEval.h.
View newest version in sPHENIX GitHub at line 76 of file PHG4HitEval.h
References path_length, and ActsTests::PropagationDatasets::pathLength.
void PHG4HitEval::set_scint_id (const int i) inline override virtual
Reimplemented from PHG4Hit.
Definition at line 52 of file PHG4HitEval.h.
View newest version in sPHENIX GitHub at line 52 of file PHG4HitEval.h
References i, and scint_id.
Member Data Documentation
float PHG4HitEval::eion protected
Definition at line 82 of file PHG4HitEval.h.
View newest version in sPHENIX GitHub at line 82 of file PHG4HitEval.h
Referenced by CopyFrom(), get_eion(), and set_eion().
float PHG4HitEval::light_yield protected
a number proportional to the scintillation light yield.
Definition at line 87 of file PHG4HitEval.h.
View newest version in sPHENIX GitHub at line 87 of file PHG4HitEval.h
Referenced by CopyFrom(), get_light_yield(), and set_light_yield().
float PHG4HitEval::path_length protected
path length of the track to the hit
Definition at line 90 of file PHG4HitEval.h.
View newest version in sPHENIX GitHub at line 90 of file PHG4HitEval.h
Referenced by CopyFrom(), get_path_length(), and set_path_length().
int PHG4HitEval::scint_id protected
Definition at line 84 of file PHG4HitEval.h.
View newest version in sPHENIX GitHub at line 84 of file PHG4HitEval.h
Referenced by CopyFrom(), get_scint_id(), and set_scint_id().
The documentation for this class was generated from the following files:
coresoftware/blob/master/simulation/g4simulation/g4main/PHG4HitEval.h
coresoftware/blob/master/simulation/g4simulation/g4main/PHG4HitEval.cc