Analysis Software: acts/blob/sPHENIX/thirdparty/dfelibs/dfe/dfe_dispatcher.hpp File Reference
dfe_dispatcher.hpp File Reference
Command dispatcher to register functions and call them by name.
#include <cassert>
#include <cstdint>
#include <functional>
#include <ostream>
#include <stdexcept>
#include <string>
#include <type_traits>
#include <unordered_map>
#include <utility>
#include <vector>
Classes
exception dfe::Variable
Variable-type value object a.k.a. a poor mans std::variant.
struct Converter< T >
struct IntegerConverter< I >
class dfe::Dispatcher
struct dfe::Dispatcher::Command
struct dfe::Variable::Converter< bool >
struct dfe::Variable::Converter< float >
struct dfe::Variable::Converter< double >
struct dfe::Variable::Converter< std::string >
struct dfe::Variable::IntegerConverter< I >
struct dfe::Variable::Converter< int8_t >
struct dfe::Variable::Converter< int16_t >
struct dfe::Variable::Converter< int32_t >
struct dfe::Variable::Converter< int64_t >
struct dfe::Variable::Converter< uint8_t >
struct dfe::Variable::Converter< uint16_t >
struct dfe::Variable::Converter< uint32_t >
struct dfe::Variable::Converter< uint64_t >
Namespaces
namespace dfe
namespace dfe::dispatcher_impl
Functions
std::ostream & dfe::operator<< (std::ostream &os, const Variable &v)
Detailed Description
Command dispatcher to register functions and call them by name.
Author
Moritz Kiehn msmk@.nosp@m.cern.nosp@m..ch
Date
2018-02-20
Definition in file dfe_dispatcher.hpp.
Variable Documentation
std::function<R(Args...)> func static
Definition at line 290 of file dfe_dispatcher.hpp.
View newest version in sPHENIX GitHub at line 290 of file dfe_dispatcher.hpp
Referenced by dfe::Dispatcher::add(), Rossegger::FindNextZero(), get_bin_average_and_count(), main(), mg_scan_directory(), FitNewton::NewtonMinimizerGradHessian::setFunction(), and testing::gmock_matchers_test::TEST().