Analysis Software: PHG4VtxPointv1 Class Reference
PHG4VtxPointv1 Class Reference
#include <coresoftware/blob/master/simulation/g4simulation/g4main/PHG4VtxPointv1.h>
Public Member Functions
PHG4VtxPointv1 ()
PHG4VtxPointv1 (const PHG4VtxPoint *vtx)
PHG4VtxPointv1 (const double x, const double y, const double z, const double t, const int id_value=INT_MIN)
~PHG4VtxPointv1 () override
void identify (std::ostream &os=std::cout) const override
void set_x (const double r) override
void set_y (const double r) override
void set_z (const double r) override
void set_t (const double r) override
void set_id (const int i) override
double get_x () const override
double get_y () const override
double get_z () const override
double get_t () const override
int get_id () const override
Public Member Functions inherited from PHG4VtxPoint
~PHG4VtxPoint () override
bool operator== (const PHG4VtxPoint &) const
comparison of vertex value only, not on the id, per algorithm requirement in PHG4TruthInfoContainer::AddPrimaryVertex
Public Member Functions inherited from PHObject
PHObject ()
ctor
~PHObject () override
dtor
virtual PHObject * CloneMe () const
Virtual copy constructor.
virtual PHObject * clone () const final
PHObject * Clone (const char *newname="") const final
void Copy (TObject &object) const final
virtual void Reset ()
Clear Event.
virtual int isValid () const
isValid returns non zero if object contains vailid data
virtual int Integrate () const
virtual int Integrate (PHObject *)
virtual void CopyFrom (const PHObject *obj)
Protected Attributes
double vx
double vy
double vz
double t0
int id
id tag for this vertex
Additional Inherited Members
Protected Member Functions inherited from PHG4VtxPoint
PHG4VtxPoint ()
Detailed Description
Definition at line 12 of file PHG4VtxPointv1.h.
View newest version in sPHENIX GitHub at line 12 of file PHG4VtxPointv1.h
Constructor & Destructor Documentation
PHG4VtxPointv1::PHG4VtxPointv1 () inline
Definition at line 15 of file PHG4VtxPointv1.h.
View newest version in sPHENIX GitHub at line 15 of file PHG4VtxPointv1.h
PHG4VtxPointv1::PHG4VtxPointv1 (const PHG4VtxPoint * vtx) inline
Definition at line 23 of file PHG4VtxPointv1.h.
View newest version in sPHENIX GitHub at line 23 of file PHG4VtxPointv1.h
PHG4VtxPointv1::PHG4VtxPointv1 (const double x, const double y, const double z, const double t, const int id_value = INT_MIN) inline
Definition at line 31 of file PHG4VtxPointv1.h.
View newest version in sPHENIX GitHub at line 31 of file PHG4VtxPointv1.h
PHG4VtxPointv1::~PHG4VtxPointv1 () inline override
Definition at line 39 of file PHG4VtxPointv1.h.
View newest version in sPHENIX GitHub at line 39 of file PHG4VtxPointv1.h
Member Function Documentation
int PHG4VtxPointv1::get_id () const inline override virtual
Reimplemented from PHG4VtxPoint.
Definition at line 54 of file PHG4VtxPointv1.h.
View newest version in sPHENIX GitHub at line 54 of file PHG4VtxPointv1.h
References id.
double PHG4VtxPointv1::get_t () const inline override virtual
Reimplemented from PHG4VtxPoint.
Definition at line 53 of file PHG4VtxPointv1.h.
View newest version in sPHENIX GitHub at line 53 of file PHG4VtxPointv1.h
References t0.
double PHG4VtxPointv1::get_x () const inline override virtual
Reimplemented from PHG4VtxPoint.
Definition at line 50 of file PHG4VtxPointv1.h.
View newest version in sPHENIX GitHub at line 50 of file PHG4VtxPointv1.h
References vx.
double PHG4VtxPointv1::get_y () const inline override virtual
Reimplemented from PHG4VtxPoint.
Definition at line 51 of file PHG4VtxPointv1.h.
View newest version in sPHENIX GitHub at line 51 of file PHG4VtxPointv1.h
References vy.
double PHG4VtxPointv1::get_z () const inline override virtual
Reimplemented from PHG4VtxPoint.
Definition at line 52 of file PHG4VtxPointv1.h.
View newest version in sPHENIX GitHub at line 52 of file PHG4VtxPointv1.h
References vz.
void PHG4VtxPointv1::identify (std::ostream & os = std::cout) const override virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from PHG4VtxPoint.
Definition at line 6 of file PHG4VtxPointv1.cc.
View newest version in sPHENIX GitHub at line 6 of file PHG4VtxPointv1.cc
void PHG4VtxPointv1::set_id (const int i) inline override virtual
Reimplemented from PHG4VtxPoint.
Definition at line 48 of file PHG4VtxPointv1.h.
View newest version in sPHENIX GitHub at line 48 of file PHG4VtxPointv1.h
References i.
Referenced by PHG4DSTReader::process_event().
void PHG4VtxPointv1::set_t (const double r) inline override virtual
Reimplemented from PHG4VtxPoint.
Definition at line 47 of file PHG4VtxPointv1.h.
View newest version in sPHENIX GitHub at line 47 of file PHG4VtxPointv1.h
References physmon_track_finding_ttbar::r, and t0.
Referenced by PHG4InEventReadBack::process_event(), and PHG4DSTReader::process_event().
void PHG4VtxPointv1::set_x (const double r) inline override virtual
Reimplemented from PHG4VtxPoint.
Definition at line 44 of file PHG4VtxPointv1.h.
View newest version in sPHENIX GitHub at line 44 of file PHG4VtxPointv1.h
References physmon_track_finding_ttbar::r, and vx.
Referenced by PHG4InEventReadBack::process_event(), and PHG4DSTReader::process_event().
void PHG4VtxPointv1::set_y (const double r) inline override virtual
Reimplemented from PHG4VtxPoint.
Definition at line 45 of file PHG4VtxPointv1.h.
View newest version in sPHENIX GitHub at line 45 of file PHG4VtxPointv1.h
References physmon_track_finding_ttbar::r, and vy.
Referenced by PHG4InEventReadBack::process_event(), and PHG4DSTReader::process_event().
void PHG4VtxPointv1::set_z (const double r) inline override virtual
Reimplemented from PHG4VtxPoint.
Definition at line 46 of file PHG4VtxPointv1.h.
View newest version in sPHENIX GitHub at line 46 of file PHG4VtxPointv1.h
References physmon_track_finding_ttbar::r, and vz.
Referenced by PHG4InEventReadBack::process_event(), and PHG4DSTReader::process_event().
Member Data Documentation
int PHG4VtxPointv1::id protected
id tag for this vertex
Definition at line 65 of file PHG4VtxPointv1.h.
View newest version in sPHENIX GitHub at line 65 of file PHG4VtxPointv1.h
Referenced by get_id().
double PHG4VtxPointv1::t0 protected
Definition at line 62 of file PHG4VtxPointv1.h.
View newest version in sPHENIX GitHub at line 62 of file PHG4VtxPointv1.h
Referenced by get_t(), and set_t().
double PHG4VtxPointv1::vx protected
Definition at line 59 of file PHG4VtxPointv1.h.
View newest version in sPHENIX GitHub at line 59 of file PHG4VtxPointv1.h
Referenced by get_x(), and set_x().
double PHG4VtxPointv1::vy protected
Definition at line 60 of file PHG4VtxPointv1.h.
View newest version in sPHENIX GitHub at line 60 of file PHG4VtxPointv1.h
Referenced by get_y(), and set_y().
double PHG4VtxPointv1::vz protected
Definition at line 61 of file PHG4VtxPointv1.h.
View newest version in sPHENIX GitHub at line 61 of file PHG4VtxPointv1.h
Referenced by get_z(), and set_z().
The documentation for this class was generated from the following files:
coresoftware/blob/master/simulation/g4simulation/g4main/PHG4VtxPointv1.h
coresoftware/blob/master/simulation/g4simulation/g4main/PHG4VtxPointv1.cc