Analysis Software: trento::Collider Class Reference
trento::Collider Class Reference
#include <JETSCAPE/blob/master/external_packages/trento/src/collider.h>
Public Member Functions
Collider (const VarMap &var_map)
Instantiate from the configuration.
~Collider ()
void run_events ()
Run events and output.
Private Member Functions
double sample_impact_param ()
Sample a min-bias impact parameter within the set range.
Private Attributes
std::unique_ptr< Nucleus > nucleusA_
Pair of nucleus projectiles.
std::unique_ptr< Nucleus > nucleusB_
NucleonProfile nucleon_profile_
The nucleon profile instance.
const int nevents_
Number of events to run.
const double bmin_
Minimum and maximum impact parameter.
const double bmax_
const double asymmetry_
Event event_
The event instance.
Output output_
The output instance.
Detailed Description
Orchestrates event generation and output. Owns instances of several other TRENTO classes and knows how they work together. Responsible for sampling impact parameters. After instantiation, call run_events() to do everything.
Example::
Collider collider{var_map}; collider.run_events();
Definition at line 29 of file collider.h.
View newest version in sPHENIX GitHub at line 29 of file collider.h
Constructor & Destructor Documentation
trento::Collider::Collider (const VarMap & var_map) explicit
Instantiate from the configuration.
Definition at line 58 of file collider.cxx.
View newest version in sPHENIX GitHub at line 58 of file collider.cxx
References trento::random::engine, and TauVsDIS_MachineLearning_Differentiation::seed.
trento::Collider::~Collider () default
Declare a destructor to properly handle the std::unique_ptr<Nucleus> members. At this point in the code, Nucleus is an incomplete type so the compiler does not know how to delete it. Therefore the destructor is defined (as default) in the implementation file, at which point Nucleus is fully defined. See e.g. Item 22 of Effective Modern C++ by Scott Meyers and this stackoverflow answer: http://stackoverflow.com/a/6089065.
Member Function Documentation
void trento::Collider::run_events ()
Run events and output.
Definition at line 78 of file collider.cxx.
View newest version in sPHENIX GitHub at line 78 of file collider.cxx
References KFPMath::b, trento::Event::compute(), event_, n, nevents_, nucleon_profile_, nucleusA_, nucleusB_, output_, and sample_impact_param().
Referenced by main(), and TEST_CASE().
double trento::Collider::sample_impact_param () private
Sample a min-bias impact parameter within the set range.
Definition at line 94 of file collider.cxx.
View newest version in sPHENIX GitHub at line 94 of file collider.cxx
References A, asymmetry_, KFPMath::b, bmax_, bmin_, nucleon_profile_, nucleusA_, nucleusB_, and trento::NucleonProfile::participate().
Referenced by run_events().
Member Data Documentation
const double trento::Collider::asymmetry_ private
Parameterizes the degree of asymmetry between the two projectiles. Used to apportion the total impact parameter to each projectile so that the resulting overlap is approximately centered. Given the two nuclear radii rA and rB (see Nucleus::radius()), the parameter is
asymmetry = rA / (rA + rB)
and the impact parameter b is apportioned
offset_A = asymmetry * b offset_B = (asymmetry-1) * b
So for example, two identical projectiles would have asymmetry = 0.5, and each would be offset by half the impact parameter. A proton-lead system would have asymmetry = 1, meaning the lead nucleus would be offset by the entire impact parameter and the proton would not be offset at all.
Definition at line 79 of file collider.h.
View newest version in sPHENIX GitHub at line 79 of file collider.h
Referenced by sample_impact_param().
const double trento::Collider::bmax_ private
Definition at line 61 of file collider.h.
View newest version in sPHENIX GitHub at line 61 of file collider.h
Referenced by sample_impact_param().
const double trento::Collider::bmin_ private
Minimum and maximum impact parameter.
Definition at line 61 of file collider.h.
View newest version in sPHENIX GitHub at line 61 of file collider.h
Referenced by sample_impact_param().
Event trento::Collider::event_ private
The event instance.
Definition at line 82 of file collider.h.
View newest version in sPHENIX GitHub at line 82 of file collider.h
Referenced by run_events().
const int trento::Collider::nevents_ private
Number of events to run.
Definition at line 58 of file collider.h.
View newest version in sPHENIX GitHub at line 58 of file collider.h
Referenced by run_events().
NucleonProfile trento::Collider::nucleon_profile_ private
The nucleon profile instance.
Definition at line 55 of file collider.h.
View newest version in sPHENIX GitHub at line 55 of file collider.h
Referenced by run_events(), and sample_impact_param().
std::unique_ptr<Nucleus> trento::Collider::nucleusA_ private
Pair of nucleus projectiles.
Definition at line 52 of file collider.h.
View newest version in sPHENIX GitHub at line 52 of file collider.h
Referenced by run_events(), and sample_impact_param().
std::unique_ptr<Nucleus> trento::Collider::nucleusB_ private
Definition at line 52 of file collider.h.
View newest version in sPHENIX GitHub at line 52 of file collider.h
Referenced by run_events(), and sample_impact_param().
Output trento::Collider::output_ private
The output instance.
Definition at line 85 of file collider.h.
View newest version in sPHENIX GitHub at line 85 of file collider.h
Referenced by run_events().
The documentation for this class was generated from the following files:
JETSCAPE/blob/master/external_packages/trento/src/collider.h
JETSCAPE/blob/master/external_packages/trento/src/collider.cxx