Analysis Software: Acts::detail::VolumeMaterialInteraction Struct Reference
Acts::detail::VolumeMaterialInteraction Struct Reference
Struct to handle volume material interaction.
#include <acts/blob/sPHENIX/Core/include/Acts/Propagator/detail/VolumeMaterialInteraction.hpp>
Public Member Functions
template<typename propagator_state_t , typename stepper_t >
VolumeMaterialInteraction (const TrackingVolume *vVolume, const propagator_state_t &state, const stepper_t &stepper)
Constructor.
template<typename propagator_state_t , typename navigator_t >
bool evaluateMaterialSlab (const propagator_state_t &state, const navigator_t &navigator)
This function evaluates the material properties to interact with.
Public Attributes
InteractionVolume volume {}
The material interaction volume.
const Vector3 pos = Vector3::Zero()
The particle current position.
const double time = 0
The particle current time.
const Vector3 dir = Vector3::Zero()
The particle current direction.
const float qOverP = 0
The particle q/p at the interaction.
const float absQ = 0
The absolute particle charge.
const float momentum = 0
The particle momentum at the interaction.
const float mass = 0
The particle mass.
const PdgParticle absPdg = eInvalid
The particle pdg.
const bool performCovarianceTransport = false
The covariance transport decision at the interaction.
const Direction navDir
The navigation direction.
MaterialSlab slab
Data evaluated within this struct.
double pathCorrection = 0
The path correction factor due to non-zero incidence on the surface.
Detailed Description
Struct to handle volume material interaction.
Definition at line 23 of file VolumeMaterialInteraction.hpp.
View newest version in sPHENIX GitHub at line 23 of file VolumeMaterialInteraction.hpp
Constructor & Destructor Documentation
template<typename propagator_state_t , typename stepper_t > Acts::detail::VolumeMaterialInteraction::VolumeMaterialInteraction (const TrackingVolume * vVolume, const propagator_state_t & state, const stepper_t & stepper) inline
Constructor.
Template Parameters
propagator_state_t Type of the propagator state
stepper_t Type of the stepper
Parameters
[in] vVolume The current volume
[in] state State of the propagation
[in] stepper Stepper in use
Definition at line 61 of file VolumeMaterialInteraction.hpp.
View newest version in sPHENIX GitHub at line 61 of file VolumeMaterialInteraction.hpp
Member Function Documentation
template<typename propagator_state_t , typename navigator_t > bool Acts::detail::VolumeMaterialInteraction::evaluateMaterialSlab (const propagator_state_t & state, const navigator_t & navigator) inline
This function evaluates the material properties to interact with.
Template Parameters
propagator_state_t Type of the propagator state
navigator_t Type of the propagator state
Parameters
[in] state State of the propagation
[in] navigator Navigator of the propagation
Returns
Boolean statement whether the material is valid
Definition at line 86 of file VolumeMaterialInteraction.hpp.
View newest version in sPHENIX GitHub at line 86 of file VolumeMaterialInteraction.hpp
References pathCorrection, pos, and slab.
Referenced by Acts::MaterialInteractor::operator()().
Member Data Documentation
const PdgParticle Acts::detail::VolumeMaterialInteraction::absPdg = eInvalid
The particle pdg.
Definition at line 41 of file VolumeMaterialInteraction.hpp.
View newest version in sPHENIX GitHub at line 41 of file VolumeMaterialInteraction.hpp
const float Acts::detail::VolumeMaterialInteraction::absQ = 0
The absolute particle charge.
Definition at line 35 of file VolumeMaterialInteraction.hpp.
View newest version in sPHENIX GitHub at line 35 of file VolumeMaterialInteraction.hpp
const Vector3 Acts::detail::VolumeMaterialInteraction::dir = Vector3::Zero()
The particle current direction.
Definition at line 31 of file VolumeMaterialInteraction.hpp.
View newest version in sPHENIX GitHub at line 31 of file VolumeMaterialInteraction.hpp
Referenced by Acts::MaterialInteractor::recordResult().
const float Acts::detail::VolumeMaterialInteraction::mass = 0
The particle mass.
Definition at line 39 of file VolumeMaterialInteraction.hpp.
View newest version in sPHENIX GitHub at line 39 of file VolumeMaterialInteraction.hpp
const float Acts::detail::VolumeMaterialInteraction::momentum = 0
The particle momentum at the interaction.
Definition at line 37 of file VolumeMaterialInteraction.hpp.
View newest version in sPHENIX GitHub at line 37 of file VolumeMaterialInteraction.hpp
const Direction Acts::detail::VolumeMaterialInteraction::navDir
The navigation direction.
Definition at line 45 of file VolumeMaterialInteraction.hpp.
View newest version in sPHENIX GitHub at line 45 of file VolumeMaterialInteraction.hpp
double Acts::detail::VolumeMaterialInteraction::pathCorrection = 0
The path correction factor due to non-zero incidence on the surface.
Definition at line 50 of file VolumeMaterialInteraction.hpp.
View newest version in sPHENIX GitHub at line 50 of file VolumeMaterialInteraction.hpp
Referenced by evaluateMaterialSlab(), and Acts::MaterialInteractor::recordResult().
const bool Acts::detail::VolumeMaterialInteraction::performCovarianceTransport = false
The covariance transport decision at the interaction.
Definition at line 43 of file VolumeMaterialInteraction.hpp.
View newest version in sPHENIX GitHub at line 43 of file VolumeMaterialInteraction.hpp
const Vector3 Acts::detail::VolumeMaterialInteraction::pos = Vector3::Zero()
The particle current position.
Definition at line 27 of file VolumeMaterialInteraction.hpp.
View newest version in sPHENIX GitHub at line 27 of file VolumeMaterialInteraction.hpp
Referenced by evaluateMaterialSlab(), and Acts::MaterialInteractor::recordResult().
const float Acts::detail::VolumeMaterialInteraction::qOverP = 0
The particle q/p at the interaction.
Definition at line 33 of file VolumeMaterialInteraction.hpp.
View newest version in sPHENIX GitHub at line 33 of file VolumeMaterialInteraction.hpp
MaterialSlab Acts::detail::VolumeMaterialInteraction::slab
Data evaluated within this struct.
Definition at line 48 of file VolumeMaterialInteraction.hpp.
View newest version in sPHENIX GitHub at line 48 of file VolumeMaterialInteraction.hpp
Referenced by evaluateMaterialSlab(), and Acts::MaterialInteractor::recordResult().
const double Acts::detail::VolumeMaterialInteraction::time = 0
The particle current time.
Definition at line 29 of file VolumeMaterialInteraction.hpp.
View newest version in sPHENIX GitHub at line 29 of file VolumeMaterialInteraction.hpp
Referenced by Acts::MaterialInteractor::recordResult().
InteractionVolume Acts::detail::VolumeMaterialInteraction::volume {}
The material interaction volume.
Definition at line 25 of file VolumeMaterialInteraction.hpp.
View newest version in sPHENIX GitHub at line 25 of file VolumeMaterialInteraction.hpp
Referenced by Acts::MaterialInteractor::recordResult().
The documentation for this struct was generated from the following file:
acts/blob/sPHENIX/Core/include/Acts/Propagator/detail/VolumeMaterialInteraction.hpp