Analysis Software: Acts::GenericCurvilinearTrackParameters< particle_hypothesis_t > Class Template Reference
Acts::GenericCurvilinearTrackParameters< particle_hypothesis_t > Class Template Reference
#include <acts/blob/sPHENIX/Core/include/Acts/EventData/GenericCurvilinearTrackParameters.hpp>
Public Types
using Scalar = ActsScalar
using ParametersVector = BoundVector
using CovarianceMatrix = BoundSquareMatrix
using ParticleHypothesis = particle_hypothesis_t
Public Types inherited from Acts::GenericBoundTrackParameters< particle_hypothesis_t >
using Scalar = ActsScalar
using ParametersVector = BoundVector
using CovarianceMatrix = BoundSquareMatrix
using ParticleHypothesis = particle_hypothesis_t
Public Member Functions
GenericCurvilinearTrackParameters (const Vector4 &pos4, const Vector3 &dir, Scalar qOverP, std::optional< CovarianceMatrix > cov, ParticleHypothesis particleHypothesis)
GenericCurvilinearTrackParameters (const Vector4 &pos4, Scalar phi, Scalar theta, Scalar qOverP, std::optional< CovarianceMatrix > cov, ParticleHypothesis particleHypothesis)
template<typename other_particle_hypothesis_t >
GenericCurvilinearTrackParameters (const GenericCurvilinearTrackParameters< other_particle_hypothesis_t > &other)
Converts a bound track parameter with a different hypothesis.
GenericCurvilinearTrackParameters ()=delete
Parameters are not default constructible due to the charge type.
GenericCurvilinearTrackParameters (const GenericCurvilinearTrackParameters &)=default
GenericCurvilinearTrackParameters (GenericCurvilinearTrackParameters &&)=default
~GenericCurvilinearTrackParameters ()=default
GenericCurvilinearTrackParameters & operator= (const GenericCurvilinearTrackParameters &)=default
GenericCurvilinearTrackParameters & operator= (GenericCurvilinearTrackParameters &&)=default
Vector4 fourPosition () const
Space-time position four-vector.
Vector3 position () const
Spatial position three-vector.
Public Member Functions inherited from Acts::GenericBoundTrackParameters< particle_hypothesis_t >
GenericBoundTrackParameters (std::shared_ptr< const Surface > surface, const ParametersVector &params, std::optional< CovarianceMatrix > cov, ParticleHypothesis particleHypothesis)
template<typename other_particle_hypothesis_t >
GenericBoundTrackParameters (const GenericBoundTrackParameters< other_particle_hypothesis_t > &other)
Converts a bound track parameter with a different hypothesis.
GenericBoundTrackParameters ()=delete
Parameters are not default constructible due to the charge type.
GenericBoundTrackParameters (const GenericBoundTrackParameters &)=default
GenericBoundTrackParameters (GenericBoundTrackParameters &&)=default
~GenericBoundTrackParameters ()=default
GenericBoundTrackParameters & operator= (const GenericBoundTrackParameters &)=default
GenericBoundTrackParameters & operator= (GenericBoundTrackParameters &&)=default
ParametersVector & parameters ()
Parameters vector.
const ParametersVector & parameters () const
Parameters vector.
ActsVector< 2 > spatialImpactParameters () const
Vector of spatial impact parameters (i.e., d0 and z0)
ActsVector< 3 > impactParameters () const
Vector of spatial and temporal impact parameters (i.e., d0, z0, and t)
std::optional< CovarianceMatrix > & covariance ()
Optional covariance matrix.
const std::optional
< CovarianceMatrix > & covariance () const
Optional covariance matrix.
std::optional
< ActsSquareMatrix< 2 > > spatialImpactParameterCovariance () const
Covariance matrix of the spatial impact parameters (i.e., of d0 and z0)
std::optional
< ActsSquareMatrix< 3 > > impactParameterCovariance () const
template<BoundIndices kIndex>
Scalar get () const
Vector2 localPosition () const
Local spatial position two-vector.
Vector4 fourPosition (const GeometryContext &geoCtx) const
Vector3 position (const GeometryContext &geoCtx) const
Scalar time () const
Time coordinate.
Scalar phi () const
Phi direction.
Scalar theta () const
Theta direction.
Scalar qOverP () const
Charge over momentum.
Vector3 direction () const
Scalar absoluteMomentum () const
Absolute momentum.
Scalar transverseMomentum () const
Transverse momentum.
Vector3 momentum () const
Momentum three-vector.
Scalar charge () const
Particle electric charge.
const ParticleHypothesis & particleHypothesis () const
Particle hypothesis.
const Surface & referenceSurface () const
Reference surface onto which the parameters are bound.
RotationMatrix3 referenceFrame (const GeometryContext &geoCtx) const
Static Public Member Functions
template<typename other_track_parameter_t >
static
GenericCurvilinearTrackParameters create (const other_track_parameter_t &other)
Converts an unknown bound track parameter.
Static Public Member Functions inherited from Acts::GenericBoundTrackParameters< particle_hypothesis_t >
static Result
< GenericBoundTrackParameters > create (std::shared_ptr< const Surface > surface, const GeometryContext &geoCtx, const Vector4 &pos4, const Vector3 &dir, Scalar qOverP, std::optional< CovarianceMatrix > cov, ParticleHypothesis particleHypothesis, ActsScalar tolerance=s_onSurfaceTolerance)
Private Types
using Base = GenericBoundTrackParameters< particle_hypothesis_t >
Detailed Description
template<typename particle_hypothesis_t>
class Acts::GenericCurvilinearTrackParameters< particle_hypothesis_t >
Curvilinear track parameters for a single track.
Template Parameters
particle_hypothesis_t Helper type to interpret the particle charge/momentum
This is intended as a user-facing data class that adds additional accessors and charge/momentum interpretation on top of the pure parameters vector. All parameters and their corresponding covariance matrix are stored in curvilinear parametrization.
See Also
GenericBoundTrackParameters
Definition at line 28 of file GenericCurvilinearTrackParameters.hpp.
View newest version in sPHENIX GitHub at line 28 of file GenericCurvilinearTrackParameters.hpp
Member Typedef Documentation
template<typename particle_hypothesis_t> using Acts::GenericCurvilinearTrackParameters< particle_hypothesis_t >::Base = GenericBoundTrackParameters<particle_hypothesis_t> private
Definition at line 30 of file GenericCurvilinearTrackParameters.hpp.
View newest version in sPHENIX GitHub at line 30 of file GenericCurvilinearTrackParameters.hpp
template<typename particle_hypothesis_t> using Acts::GenericCurvilinearTrackParameters< particle_hypothesis_t >::CovarianceMatrix = BoundSquareMatrix
Definition at line 35 of file GenericCurvilinearTrackParameters.hpp.
View newest version in sPHENIX GitHub at line 35 of file GenericCurvilinearTrackParameters.hpp
template<typename particle_hypothesis_t> using Acts::GenericCurvilinearTrackParameters< particle_hypothesis_t >::ParametersVector = BoundVector
Definition at line 34 of file GenericCurvilinearTrackParameters.hpp.
View newest version in sPHENIX GitHub at line 34 of file GenericCurvilinearTrackParameters.hpp
template<typename particle_hypothesis_t> using Acts::GenericCurvilinearTrackParameters< particle_hypothesis_t >::ParticleHypothesis = particle_hypothesis_t
Definition at line 36 of file GenericCurvilinearTrackParameters.hpp.
View newest version in sPHENIX GitHub at line 36 of file GenericCurvilinearTrackParameters.hpp
template<typename particle_hypothesis_t> using Acts::GenericCurvilinearTrackParameters< particle_hypothesis_t >::Scalar = ActsScalar
Definition at line 33 of file GenericCurvilinearTrackParameters.hpp.
View newest version in sPHENIX GitHub at line 33 of file GenericCurvilinearTrackParameters.hpp
Constructor & Destructor Documentation
template<typename particle_hypothesis_t> Acts::GenericCurvilinearTrackParameters< particle_hypothesis_t >::GenericCurvilinearTrackParameters (const Vector4 & pos4, const Vector3 & dir, Scalar qOverP, std::optional< CovarianceMatrix > cov, ParticleHypothesis particleHypothesis) inline
Construct from four-position, direction, and qOverP.
Parameters
pos4 Track position/time four-vector
dir Track direction three-vector; normalization is ignored.
qOverP Charge over momentum
cov Curvilinear bound parameters covariance matrix
particleHypothesis Particle hypothesis
Definition at line 45 of file GenericCurvilinearTrackParameters.hpp.
View newest version in sPHENIX GitHub at line 45 of file GenericCurvilinearTrackParameters.hpp
template<typename particle_hypothesis_t> Acts::GenericCurvilinearTrackParameters< particle_hypothesis_t >::GenericCurvilinearTrackParameters (const Vector4 & pos4, Scalar phi, Scalar theta, Scalar qOverP, std::optional< CovarianceMatrix > cov, ParticleHypothesis particleHypothesis) inline
Construct from four-position, angles, and qOverP.
Parameters
pos4 Track position/time four-vector
phi Transverse track direction angle
theta Longitudinal track direction angle
qOverP Charge over momentum
cov Curvilinear bound parameters covariance matrix
particleHypothesis Particle hypothesis
Definition at line 62 of file GenericCurvilinearTrackParameters.hpp.
View newest version in sPHENIX GitHub at line 62 of file GenericCurvilinearTrackParameters.hpp
template<typename particle_hypothesis_t> template<typename other_particle_hypothesis_t > Acts::GenericCurvilinearTrackParameters< particle_hypothesis_t >::GenericCurvilinearTrackParameters (const GenericCurvilinearTrackParameters< other_particle_hypothesis_t > & other) inline
Converts a bound track parameter with a different hypothesis.
Definition at line 74 of file GenericCurvilinearTrackParameters.hpp.
View newest version in sPHENIX GitHub at line 74 of file GenericCurvilinearTrackParameters.hpp
template<typename particle_hypothesis_t> Acts::GenericCurvilinearTrackParameters< particle_hypothesis_t >::GenericCurvilinearTrackParameters () delete
Parameters are not default constructible due to the charge type.
Referenced by Acts::GenericCurvilinearTrackParameters< particle_hypothesis_t >::create().
template<typename particle_hypothesis_t> Acts::GenericCurvilinearTrackParameters< particle_hypothesis_t >::GenericCurvilinearTrackParameters (const GenericCurvilinearTrackParameters< particle_hypothesis_t > &) default
template<typename particle_hypothesis_t> Acts::GenericCurvilinearTrackParameters< particle_hypothesis_t >::GenericCurvilinearTrackParameters (GenericCurvilinearTrackParameters< particle_hypothesis_t > &&) default
template<typename particle_hypothesis_t> Acts::GenericCurvilinearTrackParameters< particle_hypothesis_t >::~GenericCurvilinearTrackParameters () default
Member Function Documentation
template<typename particle_hypothesis_t> template<typename other_track_parameter_t > static GenericCurvilinearTrackParameters Acts::GenericCurvilinearTrackParameters< particle_hypothesis_t >::create (const other_track_parameter_t & other) inline static
Converts an unknown bound track parameter.
Definition at line 83 of file GenericCurvilinearTrackParameters.hpp.
View newest version in sPHENIX GitHub at line 83 of file GenericCurvilinearTrackParameters.hpp
References Acts::GenericCurvilinearTrackParameters< particle_hypothesis_t >::GenericCurvilinearTrackParameters().
template<typename particle_hypothesis_t> Vector4 Acts::GenericCurvilinearTrackParameters< particle_hypothesis_t >::fourPosition () const inline
Space-time position four-vector.
Definition at line 108 of file GenericCurvilinearTrackParameters.hpp.
View newest version in sPHENIX GitHub at line 108 of file GenericCurvilinearTrackParameters.hpp
References Acts::GenericBoundTrackParameters< particle_hypothesis_t >::fourPosition().
template<typename particle_hypothesis_t> GenericCurvilinearTrackParameters& Acts::GenericCurvilinearTrackParameters< particle_hypothesis_t >::operator= (const GenericCurvilinearTrackParameters< particle_hypothesis_t > &) default
template<typename particle_hypothesis_t> GenericCurvilinearTrackParameters& Acts::GenericCurvilinearTrackParameters< particle_hypothesis_t >::operator= (GenericCurvilinearTrackParameters< particle_hypothesis_t > &&) default
template<typename particle_hypothesis_t> Vector3 Acts::GenericCurvilinearTrackParameters< particle_hypothesis_t >::position () const inline
Spatial position three-vector.
Definition at line 112 of file GenericCurvilinearTrackParameters.hpp.
View newest version in sPHENIX GitHub at line 112 of file GenericCurvilinearTrackParameters.hpp
References Acts::GenericBoundTrackParameters< particle_hypothesis_t >::position().
Referenced by Acts::Test::BOOST_AUTO_TEST_CASE(), and Acts::Test::BOOST_DATA_TEST_CASE().
The documentation for this class was generated from the following file:
acts/blob/sPHENIX/Core/include/Acts/EventData/GenericCurvilinearTrackParameters.hpp