Analysis Software: PHG4CylinderGeomv1 Class Reference
PHG4CylinderGeomv1 Class Reference
#include <coresoftware/blob/master/simulation/g4simulation/g4detectors/PHG4CylinderGeomv1.h>
Public Member Functions
PHG4CylinderGeomv1 ()
PHG4CylinderGeomv1 (const double r, const double zmi, const double zma, const double thickn)
~PHG4CylinderGeomv1 () override
void identify (std::ostream &os=std::cout) const override
int get_layer () const override
double get_radius () const override
double get_thickness () const override
double get_zmin () const override
double get_zmax () const override
void set_layer (const int i) override
void set_radius (const double r) override
void set_thickness (const double t) override
void set_zmin (const double z) override
void set_zmax (const double z) override
void ImportParameters (const PHParameters &param) override
load parameters from PHParameters, which interface to Database/XML/ROOT files
Public Member Functions inherited from PHG4CylinderGeom
~PHG4CylinderGeom () override
virtual int get_nscint () const
virtual double get_tiltangle () const
virtual double get_phi_slat_zero () const
virtual void set_nscint (const int)
virtual void set_tiltangle (const double)
virtual void set_phi_slat_zero (const double)
virtual void find_segment_center (const int, const int, double[])
virtual void find_strip_center (const int, const int, const int, const int, double[])
virtual void find_strip_index_values (const int, const double, const double, int &, int &)
virtual void find_strip_center_local_coords (const int, const int, const int, double[])
virtual double get_strip_y_spacing () const
virtual double get_strip_z_spacing () const
virtual double get_strip_tilt () const
virtual int get_N_strip_columns () const
virtual int get_N_strips_per_column () const
virtual int get_N_sensors_in_layer () const
virtual double get_pixel_z () const
virtual double get_pixel_x () const
virtual double get_pixel_thickness () const
Public Member Functions inherited from PHObject
PHObject ()
ctor
~PHObject () override
dtor
virtual PHObject * CloneMe () const
Virtual copy constructor.
virtual PHObject * clone () const final
PHObject * Clone (const char *newname="") const final
void Copy (TObject &object) const final
virtual void Reset ()
Clear Event.
virtual int isValid () const
isValid returns non zero if object contains vailid data
virtual int Integrate () const
virtual int Integrate (PHObject *)
virtual void CopyFrom (const PHObject *obj)
Protected Attributes
int layer = -1
double radius = NAN
double zmin = NAN
double zmax = NAN
double thickness = NAN
Additional Inherited Members
Protected Member Functions inherited from PHG4CylinderGeom
PHG4CylinderGeom ()
Detailed Description
Definition at line 13 of file PHG4CylinderGeomv1.h.
View newest version in sPHENIX GitHub at line 13 of file PHG4CylinderGeomv1.h
Constructor & Destructor Documentation
PHG4CylinderGeomv1::PHG4CylinderGeomv1 () inline
Definition at line 16 of file PHG4CylinderGeomv1.h.
View newest version in sPHENIX GitHub at line 16 of file PHG4CylinderGeomv1.h
PHG4CylinderGeomv1::PHG4CylinderGeomv1 (const double r, const double zmi, const double zma, const double thickn) inline
Definition at line 17 of file PHG4CylinderGeomv1.h.
View newest version in sPHENIX GitHub at line 17 of file PHG4CylinderGeomv1.h
PHG4CylinderGeomv1::~PHG4CylinderGeomv1 () inline override
Definition at line 25 of file PHG4CylinderGeomv1.h.
View newest version in sPHENIX GitHub at line 25 of file PHG4CylinderGeomv1.h
Member Function Documentation
int PHG4CylinderGeomv1::get_layer () const inline override virtual
Reimplemented from PHG4CylinderGeom.
Definition at line 30 of file PHG4CylinderGeomv1.h.
View newest version in sPHENIX GitHub at line 30 of file PHG4CylinderGeomv1.h
References layer.
Referenced by PHG4SpacalDetector::AddCellGeometryNode(), and PHG4FullProjSpacalCellReco::InitRun().
double PHG4CylinderGeomv1::get_radius () const inline override virtual
Reimplemented from PHG4CylinderGeom.
Definition at line 31 of file PHG4CylinderGeomv1.h.
View newest version in sPHENIX GitHub at line 31 of file PHG4CylinderGeomv1.h
References radius.
Referenced by PHG4SpacalDetector::AddCellGeometryNode(), PHG4SpacalPrototype4Detector::Construct_AzimuthalSeg(), PHG4SpacalPrototypeDetector::Construct_AzimuthalSeg(), PHG4FullProjTiltedSpacalDetector::Construct_AzimuthalSeg(), PHG4SpacalDetector::Construct_AzimuthalSeg(), PHG4SpacalPrototype4Detector::ConstructMe(), PHG4SpacalPrototypeDetector::ConstructMe(), PHG4SpacalDetector::ConstructMe(), PHG4CylinderGeom_Spacalv1::get_half_radius(), PHG4CylinderGeom_Spacalv1::get_max_radius(), PHG4CylinderGeom_Spacalv2::get_sec_azimuthal_width(), PHG4CylinderGeom_Spacalv2::get_sec_depth(), and PHG4FullProjSpacalCellReco::InitRun().
double PHG4CylinderGeomv1::get_thickness () const inline override virtual
Reimplemented from PHG4CylinderGeom.
Definition at line 32 of file PHG4CylinderGeomv1.h.
View newest version in sPHENIX GitHub at line 32 of file PHG4CylinderGeomv1.h
References thickness.
Referenced by PHG4SpacalDetector::AddCellGeometryNode(), PHG4SpacalPrototype4Detector::Construct_AzimuthalSeg(), PHG4SpacalDetector::Construct_AzimuthalSeg(), PHG4SpacalPrototypeDetector::ConstructMe(), PHG4SpacalPrototype4Detector::ConstructMe(), PHG4CylinderGeom_Spacalv1::get_half_radius(), PHG4CylinderGeom_Spacalv1::get_max_radius(), PHG4CylinderGeom_Spacalv2::get_sec_depth(), and PHG4FullProjSpacalCellReco::InitRun().
double PHG4CylinderGeomv1::get_zmax () const inline override virtual
Reimplemented from PHG4CylinderGeom.
Definition at line 34 of file PHG4CylinderGeomv1.h.
View newest version in sPHENIX GitHub at line 34 of file PHG4CylinderGeomv1.h
References zmax.
Referenced by PHG4SpacalPrototype4Detector::Construct_AzimuthalSeg(), PHG4SpacalPrototypeDetector::Construct_AzimuthalSeg(), PHG4SpacalPrototype4Detector::ConstructMe(), PHG4SpacalPrototypeDetector::ConstructMe(), PHG4SpacalDetector::ConstructMe(), PHG4CylinderGeom_Spacalv1::get_length(), PHG4SpacalPrototype4SteppingAction::get_zmax(), PHG4SpacalSteppingAction::get_zmax(), and PHG4SpacalPrototypeSteppingAction::get_zmax().
double PHG4CylinderGeomv1::get_zmin () const inline override virtual
Reimplemented from PHG4CylinderGeom.
Definition at line 33 of file PHG4CylinderGeomv1.h.
View newest version in sPHENIX GitHub at line 33 of file PHG4CylinderGeomv1.h
References zmin.
Referenced by PHG4SpacalPrototype4Detector::Construct_AzimuthalSeg(), PHG4SpacalPrototypeDetector::Construct_AzimuthalSeg(), PHG4SpacalDetector::Construct_AzimuthalSeg(), PHG4SpacalPrototype4Detector::ConstructMe(), PHG4SpacalPrototypeDetector::ConstructMe(), PHG4SpacalDetector::ConstructMe(), PHG4CylinderGeom_Spacalv1::get_length(), PHG4SpacalPrototype4SteppingAction::get_zmin(), PHG4SpacalPrototypeSteppingAction::get_zmin(), and PHG4SpacalSteppingAction::get_zmin().
void PHG4CylinderGeomv1::identify (std::ostream & os = std::cout) const override virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from PHG4CylinderGeom.
Reimplemented in PHG4CylinderGeomv2, and PHG4CylinderGeomv3.
Definition at line 5 of file PHG4CylinderGeomv1.cc.
View newest version in sPHENIX GitHub at line 5 of file PHG4CylinderGeomv1.cc
References layer, radius, thickness, zmax, and zmin.
void PHG4CylinderGeomv1::ImportParameters (const PHParameters & param) override virtual
load parameters from PHParameters, which interface to Database/XML/ROOT files
Reimplemented from PHG4CylinderGeom.
Reimplemented in PHG4CylinderGeomv2.
Definition at line 16 of file PHG4CylinderGeomv1.cc.
View newest version in sPHENIX GitHub at line 16 of file PHG4CylinderGeomv1.cc
References PHParameters::exist_double_param(), PHParameters::exist_int_param(), PHParameters::get_double_param(), PHParameters::get_int_param(), PHG4CylinderGeom::ImportParameters(), layer, radius, thickness, zmax, and zmin.
Referenced by PHG4CylinderGeomv2::ImportParameters().
void PHG4CylinderGeomv1::set_layer (const int i) inline override virtual
Reimplemented from PHG4CylinderGeom.
Definition at line 36 of file PHG4CylinderGeomv1.h.
View newest version in sPHENIX GitHub at line 36 of file PHG4CylinderGeomv1.h
References i, and layer.
void PHG4CylinderGeomv1::set_radius (const double r) inline override virtual
Reimplemented from PHG4CylinderGeom.
Definition at line 37 of file PHG4CylinderGeomv1.h.
View newest version in sPHENIX GitHub at line 37 of file PHG4CylinderGeomv1.h
References physmon_track_finding_ttbar::r, and radius.
void PHG4CylinderGeomv1::set_thickness (const double t) inline override virtual
Reimplemented from PHG4CylinderGeom.
Definition at line 38 of file PHG4CylinderGeomv1.h.
View newest version in sPHENIX GitHub at line 38 of file PHG4CylinderGeomv1.h
References t, and thickness.
void PHG4CylinderGeomv1::set_zmax (const double z) inline override virtual
Reimplemented from PHG4CylinderGeom.
Definition at line 40 of file PHG4CylinderGeomv1.h.
View newest version in sPHENIX GitHub at line 40 of file PHG4CylinderGeomv1.h
References physmon_track_finding_ttbar::z, and zmax.
void PHG4CylinderGeomv1::set_zmin (const double z) inline override virtual
Reimplemented from PHG4CylinderGeom.
Definition at line 39 of file PHG4CylinderGeomv1.h.
View newest version in sPHENIX GitHub at line 39 of file PHG4CylinderGeomv1.h
References physmon_track_finding_ttbar::z, and zmin.
Member Data Documentation
int PHG4CylinderGeomv1::layer = -1 protected
Definition at line 46 of file PHG4CylinderGeomv1.h.
View newest version in sPHENIX GitHub at line 46 of file PHG4CylinderGeomv1.h
Referenced by get_layer(), PHG4CylinderGeomv2::identify(), PHG4CylinderGeomv3::identify(), identify(), PHG4CylinderGeom_Spacalv2::identify(), PHG4CylinderGeom_Spacalv3::identify(), PHG4CylinderGeom_Spacalv1::identify(), ImportParameters(), set_layer(), and PHG4CylinderGeom_Spacalv1::SetDefault().
double PHG4CylinderGeomv1::radius = NAN protected
Definition at line 47 of file PHG4CylinderGeomv1.h.
View newest version in sPHENIX GitHub at line 47 of file PHG4CylinderGeomv1.h
Referenced by get_radius(), PHG4CylinderGeomv2::identify(), PHG4CylinderGeomv3::identify(), identify(), PHG4CylinderGeom_Spacalv3::identify(), PHG4CylinderGeom_Spacalv2::identify(), PHG4CylinderGeom_Spacalv1::identify(), ImportParameters(), PHG4CylinderGeom_Spacalv3::load_demo_sector_tower_map1(), PHG4CylinderGeom_Spacalv3::load_demo_sector_tower_map2(), PHG4CylinderGeom_Spacalv3::load_demo_sector_tower_map4(), set_radius(), and PHG4CylinderGeom_Spacalv1::SetDefault().
double PHG4CylinderGeomv1::thickness = NAN protected
Definition at line 50 of file PHG4CylinderGeomv1.h.
View newest version in sPHENIX GitHub at line 50 of file PHG4CylinderGeomv1.h
Referenced by get_thickness(), PHG4CylinderGeomv2::identify(), PHG4CylinderGeomv3::identify(), identify(), PHG4CylinderGeom_Spacalv3::identify(), PHG4CylinderGeom_Spacalv2::identify(), PHG4CylinderGeom_Spacalv1::identify(), ImportParameters(), PHG4CylinderGeom_Spacalv3::load_demo_sector_tower_map1(), PHG4CylinderGeom_Spacalv3::load_demo_sector_tower_map2(), PHG4CylinderGeom_Spacalv3::load_demo_sector_tower_map4(), set_thickness(), and PHG4CylinderGeom_Spacalv1::SetDefault().
double PHG4CylinderGeomv1::zmax = NAN protected
Definition at line 49 of file PHG4CylinderGeomv1.h.
View newest version in sPHENIX GitHub at line 49 of file PHG4CylinderGeomv1.h
Referenced by get_zmax(), PHG4CylinderGeomv2::identify(), PHG4CylinderGeomv3::identify(), identify(), PHG4CylinderGeom_Spacalv3::identify(), PHG4CylinderGeom_Spacalv2::identify(), PHG4CylinderGeom_Spacalv1::identify(), ImportParameters(), PHG4CylinderGeom_Spacalv3::load_demo_sector_tower_map1(), PHG4CylinderGeom_Spacalv3::load_demo_sector_tower_map2(), PHG4CylinderGeom_Spacalv3::load_demo_sector_tower_map4(), set_zmax(), and PHG4CylinderGeom_Spacalv1::SetDefault().
double PHG4CylinderGeomv1::zmin = NAN protected
Definition at line 48 of file PHG4CylinderGeomv1.h.
View newest version in sPHENIX GitHub at line 48 of file PHG4CylinderGeomv1.h
Referenced by get_zmin(), PHG4CylinderGeomv2::identify(), PHG4CylinderGeomv3::identify(), identify(), PHG4CylinderGeom_Spacalv3::identify(), PHG4CylinderGeom_Spacalv2::identify(), PHG4CylinderGeom_Spacalv1::identify(), ImportParameters(), PHG4CylinderGeom_Spacalv3::load_demo_sector_tower_map1(), PHG4CylinderGeom_Spacalv3::load_demo_sector_tower_map2(), PHG4CylinderGeom_Spacalv3::load_demo_sector_tower_map4(), set_zmin(), and PHG4CylinderGeom_Spacalv1::SetDefault().
The documentation for this class was generated from the following files:
coresoftware/blob/master/simulation/g4simulation/g4detectors/PHG4CylinderGeomv1.h
coresoftware/blob/master/simulation/g4simulation/g4detectors/PHG4CylinderGeomv1.cc