Analysis Software: PHRandomSeed Class Reference
PHRandomSeed Class Reference
#include <coresoftware/blob/master/offline/framework/phool/PHRandomSeed.h>
Public Member Functions
PHRandomSeed ()
virtual ~PHRandomSeed ()
operator unsigned int () const
conversion operator for unsigned int seed = PHRandomSeed();
Static Public Member Functions
static unsigned int GetSeed ()
get a seed
static void LoadSeed (const unsigned int iseed)
static void Verbosity (const int iverb)
static int Verbosity ()
Static Protected Member Functions
static void InitSeed ()
Static Protected Attributes
static bool fFixed
static bool fInitialized
static int verbose
Detailed Description
standard way to get a random seed: unsigned int seed = PHRandomSeed(); It return fix seed sequence if recoConsts RANDOMSEED is set. If values are preloaded via PHRandomSeed::LoadSeed, they are returned in loaded order otherwise it return a random seed from std::random_device rdev
Definition at line 9 of file PHRandomSeed.h.
View newest version in sPHENIX GitHub at line 9 of file PHRandomSeed.h
Constructor & Destructor Documentation
PHRandomSeed::PHRandomSeed () inline
Definition at line 12 of file PHRandomSeed.h.
View newest version in sPHENIX GitHub at line 12 of file PHRandomSeed.h
virtual PHRandomSeed::~PHRandomSeed () inline virtual
Definition at line 13 of file PHRandomSeed.h.
View newest version in sPHENIX GitHub at line 13 of file PHRandomSeed.h
Member Function Documentation
unsigned int PHRandomSeed::GetSeed () static
get a seed
Definition at line 17 of file PHRandomSeed.cc.
View newest version in sPHENIX GitHub at line 17 of file PHRandomSeed.cc
References fDistribution, fFixed, fInitialized, fRandomGenerator, InitSeed(), and verbose.
Referenced by operator unsigned int().
void PHRandomSeed::InitSeed () static protected
Definition at line 48 of file PHRandomSeed.cc.
View newest version in sPHENIX GitHub at line 48 of file PHRandomSeed.cc
References fFixed, fInitialized, PHFlag::FlagExist(), fRandomGenerator, PHFlag::get_IntFlag(), recoConsts::instance(), and seed.
Referenced by GetSeed().
void PHRandomSeed::LoadSeed (const unsigned int iseed) static
Definition at line 62 of file PHRandomSeed.cc.
View newest version in sPHENIX GitHub at line 62 of file PHRandomSeed.cc
PHRandomSeed::operator unsigned int () const inline
conversion operator for unsigned int seed = PHRandomSeed();
Definition at line 15 of file PHRandomSeed.h.
View newest version in sPHENIX GitHub at line 15 of file PHRandomSeed.h
References GetSeed().
void PHRandomSeed::Verbosity (const int iverb) static
Definition at line 67 of file PHRandomSeed.cc.
View newest version in sPHENIX GitHub at line 67 of file PHRandomSeed.cc
References verbose.
static int PHRandomSeed::Verbosity () inline static
Definition at line 24 of file PHRandomSeed.h.
View newest version in sPHENIX GitHub at line 24 of file PHRandomSeed.h
References verbose.
Referenced by Fun4All_AnaTutorial_sPHENIX(), Fun4All_AnaTutorial_sPHENIX_Jets(), Fun4All_BHG(), Fun4All_G4_Calo(), Fun4All_G4_sPHENIX(), Fun4All_G4_sPHENIX_ForTrackCutStudy(), Fun4All_G4_sPHENIX_ForTrackCutStudy_EmbedScanOff(), Fun4All_G4_sPHENIX_ForTrackCutStudy_EmbedScanOn(), Fun4All_G4_sPHENIX_ForTrackCutStudy_WithPileup_EmbedScanOff(), Fun4All_G4_sPHENIX_ForTrackCutStudy_WithPileup_EmbedScanOn(), Fun4All_G4_sPHENIX_jobC(), Fun4All_Pi0Gen_sPHENIX(), Fun4All_pi0tbt_SIMPLE_EMBED(), Fun4All_RunNewTruthMatcher(), Fun4All_SinglePhotonGen_sPHENIX(), Fun4All_SinglePi0Gen_sPHENIX(), PHG4Reco::G4Seed(), PHG4Reco::InitRun(), PHG4Reco::process_event(), run_calo_fromMDC2Hits_towslope_Fun4All_G4_Calo(), rundst_spiNo(), and spiNo2().
Member Data Documentation
bool PHRandomSeed::fFixed static protected
Definition at line 28 of file PHRandomSeed.h.
View newest version in sPHENIX GitHub at line 28 of file PHRandomSeed.h
Referenced by GetSeed(), and InitSeed().
bool PHRandomSeed::fInitialized static protected
Definition at line 29 of file PHRandomSeed.h.
View newest version in sPHENIX GitHub at line 29 of file PHRandomSeed.h
Referenced by GetSeed(), and InitSeed().
int PHRandomSeed::verbose static protected
Definition at line 30 of file PHRandomSeed.h.
View newest version in sPHENIX GitHub at line 30 of file PHRandomSeed.h
Referenced by GetSeed(), and Verbosity().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/framework/phool/PHRandomSeed.h
coresoftware/blob/master/offline/framework/phool/PHRandomSeed.cc