Analysis Software: Eventplaneinfov1 Class Reference
Eventplaneinfov1 Class Reference
#include <coresoftware/blob/master/offline/packages/eventplaneinfo/Eventplaneinfov1.h>
Public Member Functions
Eventplaneinfov1 ()=default
~Eventplaneinfov1 () override=default
void identify (std::ostream &os=std::cout) const override
void Reset () override
Clear Event.
PHObject * CloneMe () const override
Virtual copy constructor.
void set_qvector (std::vector< std::pair< double, double >> Qvec) override
void set_shifted_psi (std::vector< double > Psi_Shifted) override
std::pair< double, double > get_qvector (int order) const override
double get_psi (int order) const override
double get_shifted_psi (int order) const override
double GetPsi (const double Qx, const double Qy, const unsigned int order) const override
Public Member Functions inherited from Eventplaneinfo
~Eventplaneinfo () override
Public Member Functions inherited from PHObject
PHObject ()
ctor
~PHObject () override
dtor
virtual PHObject * clone () const final
PHObject * Clone (const char *newname="") const final
void Copy (TObject &object) const final
virtual int isValid () const
isValid returns non zero if object contains vailid data
virtual int Integrate () const
virtual int Integrate (PHObject *)
virtual void CopyFrom (const PHObject *obj)
Private Member Functions
ClassDefOverride (Eventplaneinfov1, 1)
Private Attributes
std::vector< std::pair< double,
double > > mQvec
std::vector< double > mPsi_Shifted
Additional Inherited Members
Protected Member Functions inherited from Eventplaneinfo
Eventplaneinfo ()
Detailed Description
Definition at line 16 of file Eventplaneinfov1.h.
View newest version in sPHENIX GitHub at line 16 of file Eventplaneinfov1.h
Constructor & Destructor Documentation
Eventplaneinfov1::Eventplaneinfov1 () default
Referenced by CloneMe(), and Reset().
Eventplaneinfov1::~Eventplaneinfov1 () override default
Member Function Documentation
Eventplaneinfov1::ClassDefOverride (Eventplaneinfov1 , 1) private
PHObject* Eventplaneinfov1::CloneMe () const inline override virtual
Virtual copy constructor.
Reimplemented from Eventplaneinfo.
Definition at line 24 of file Eventplaneinfov1.h.
View newest version in sPHENIX GitHub at line 24 of file Eventplaneinfov1.h
References Eventplaneinfov1().
double Eventplaneinfov1::get_psi (int order) const inline override virtual
Reimplemented from Eventplaneinfo.
Definition at line 29 of file Eventplaneinfov1.h.
View newest version in sPHENIX GitHub at line 29 of file Eventplaneinfov1.h
References GetPsi(), and mQvec.
Referenced by identify().
std::pair<double, double> Eventplaneinfov1::get_qvector (int order) const inline override virtual
Reimplemented from Eventplaneinfo.
Definition at line 28 of file Eventplaneinfov1.h.
View newest version in sPHENIX GitHub at line 28 of file Eventplaneinfov1.h
References mQvec.
double Eventplaneinfov1::get_shifted_psi (int order) const inline override virtual
Reimplemented from Eventplaneinfo.
Definition at line 30 of file Eventplaneinfov1.h.
View newest version in sPHENIX GitHub at line 30 of file Eventplaneinfov1.h
References mPsi_Shifted.
double Eventplaneinfov1::GetPsi (const double Qx, const double Qy, const unsigned int order) const override virtual
Reimplemented from Eventplaneinfo.
Definition at line 12 of file Eventplaneinfov1.cc.
View newest version in sPHENIX GitHub at line 12 of file Eventplaneinfov1.cc
References double().
Referenced by get_psi().
void Eventplaneinfov1::identify (std::ostream & os = std::cout) const override virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from Eventplaneinfo.
Definition at line 5 of file Eventplaneinfov1.cc.
View newest version in sPHENIX GitHub at line 5 of file Eventplaneinfov1.cc
References get_psi().
void Eventplaneinfov1::Reset () inline override virtual
Clear Event.
Reimplemented from PHObject.
Definition at line 23 of file Eventplaneinfov1.h.
View newest version in sPHENIX GitHub at line 23 of file Eventplaneinfov1.h
References Eventplaneinfov1().
void Eventplaneinfov1::set_qvector (std::vector< std::pair< double, double >> Qvec) inline override virtual
Reimplemented from Eventplaneinfo.
Definition at line 26 of file Eventplaneinfov1.h.
View newest version in sPHENIX GitHub at line 26 of file Eventplaneinfov1.h
References mQvec.
void Eventplaneinfov1::set_shifted_psi (std::vector< double > Psi_Shifted) inline override virtual
Reimplemented from Eventplaneinfo.
Definition at line 27 of file Eventplaneinfov1.h.
View newest version in sPHENIX GitHub at line 27 of file Eventplaneinfov1.h
References mPsi_Shifted.
Member Data Documentation
std::vector<double> Eventplaneinfov1::mPsi_Shifted private
Definition at line 35 of file Eventplaneinfov1.h.
View newest version in sPHENIX GitHub at line 35 of file Eventplaneinfov1.h
Referenced by get_shifted_psi(), and set_shifted_psi().
std::vector<std::pair<double, double> > Eventplaneinfov1::mQvec private
Definition at line 34 of file Eventplaneinfov1.h.
View newest version in sPHENIX GitHub at line 34 of file Eventplaneinfov1.h
Referenced by get_psi(), get_qvector(), and set_qvector().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/eventplaneinfo/Eventplaneinfov1.h
coresoftware/blob/master/offline/packages/eventplaneinfo/Eventplaneinfov1.cc