Analysis Software: PHG4ScintillatorSlatv1 Class Reference
PHG4ScintillatorSlatv1 Class Reference
#include <coresoftware/blob/master/simulation/g4simulation/g4detectors/PHG4ScintillatorSlatv1.h>
Public Member Functions
PHG4ScintillatorSlatv1 ()
~PHG4ScintillatorSlatv1 () override
void identify (std::ostream &os=std::cout) const override
void add_edep (const double f, const double e, const double ly) override
void add_hit_key (PHG4HitDefs::keytype i) override
void set_key (PHG4ScintillatorSlatDefs::keytype i) override
void set_light_yield (const double lightYield)
short get_row () const override
short get_column () const override
PHG4ScintillatorSlatDefs::keytype get_key () const override
double get_edep () const override
double get_eion () const override
double get_light_yield () const override
std::pair< std::set
< PHG4HitDefs::keytype >
::const_iterator, std::set
< PHG4HitDefs::keytype >
::const_iterator > get_hit_ids () const override
Public Member Functions inherited from PHG4ScintillatorSlat
~PHG4ScintillatorSlat () override
Public Member Functions inherited from PHObject
PHObject ()
ctor
~PHObject () override
dtor
virtual PHObject * CloneMe () const
Virtual copy constructor.
virtual PHObject * clone () const final
PHObject * Clone (const char *newname="") const final
void Copy (TObject &object) const final
virtual void Reset ()
Clear Event.
virtual int isValid () const
isValid returns non zero if object contains vailid data
virtual int Integrate () const
virtual int Integrate (PHObject *)
virtual void CopyFrom (const PHObject *obj)
Protected Attributes
PHG4ScintillatorSlatDefs::keytype key = ~0x0
double edep = 0.
double eion = 0.
double light_yield = 0.
std::set< PHG4HitDefs::keytype > hit_id
Additional Inherited Members
Protected Member Functions inherited from PHG4ScintillatorSlat
PHG4ScintillatorSlat ()
Detailed Description
Definition at line 16 of file PHG4ScintillatorSlatv1.h.
View newest version in sPHENIX GitHub at line 16 of file PHG4ScintillatorSlatv1.h
Constructor & Destructor Documentation
PHG4ScintillatorSlatv1::PHG4ScintillatorSlatv1 () inline
Definition at line 19 of file PHG4ScintillatorSlatv1.h.
View newest version in sPHENIX GitHub at line 19 of file PHG4ScintillatorSlatv1.h
PHG4ScintillatorSlatv1::~PHG4ScintillatorSlatv1 () inline override
Definition at line 20 of file PHG4ScintillatorSlatv1.h.
View newest version in sPHENIX GitHub at line 20 of file PHG4ScintillatorSlatv1.h
Member Function Documentation
void PHG4ScintillatorSlatv1::add_edep (const double f, const double e, const double ly) inline override virtual
Reimplemented from PHG4ScintillatorSlat.
Definition at line 24 of file PHG4ScintillatorSlatv1.h.
View newest version in sPHENIX GitHub at line 24 of file PHG4ScintillatorSlatv1.h
References Acts::UnitConstants::e, edep, eion, f, and light_yield.
void PHG4ScintillatorSlatv1::add_hit_key (PHG4HitDefs::keytype i) inline override virtual
Reimplemented from PHG4ScintillatorSlat.
Definition at line 30 of file PHG4ScintillatorSlatv1.h.
View newest version in sPHENIX GitHub at line 30 of file PHG4ScintillatorSlatv1.h
References hit_id.
short PHG4ScintillatorSlatv1::get_column () const override virtual
Reimplemented from PHG4ScintillatorSlat.
Definition at line 10 of file PHG4ScintillatorSlatv1.cc.
View newest version in sPHENIX GitHub at line 10 of file PHG4ScintillatorSlatv1.cc
References key.
Referenced by identify().
double PHG4ScintillatorSlatv1::get_edep () const inline override virtual
Reimplemented from PHG4ScintillatorSlat.
Definition at line 38 of file PHG4ScintillatorSlatv1.h.
View newest version in sPHENIX GitHub at line 38 of file PHG4ScintillatorSlatv1.h
References edep.
Referenced by identify().
double PHG4ScintillatorSlatv1::get_eion () const inline override virtual
Reimplemented from PHG4ScintillatorSlat.
Definition at line 39 of file PHG4ScintillatorSlatv1.h.
View newest version in sPHENIX GitHub at line 39 of file PHG4ScintillatorSlatv1.h
References eion.
Referenced by identify().
std::pair<std::set<PHG4HitDefs::keytype>::const_iterator, std::set<PHG4HitDefs::keytype>::const_iterator> PHG4ScintillatorSlatv1::get_hit_ids () const inline override virtual
Implements PHG4ScintillatorSlat.
Definition at line 41 of file PHG4ScintillatorSlatv1.h.
View newest version in sPHENIX GitHub at line 41 of file PHG4ScintillatorSlatv1.h
References hit_id.
PHG4ScintillatorSlatDefs::keytype PHG4ScintillatorSlatv1::get_key () const inline override virtual
Reimplemented from PHG4ScintillatorSlat.
Definition at line 37 of file PHG4ScintillatorSlatv1.h.
View newest version in sPHENIX GitHub at line 37 of file PHG4ScintillatorSlatv1.h
References key.
double PHG4ScintillatorSlatv1::get_light_yield () const inline override virtual
Reimplemented from PHG4ScintillatorSlat.
Definition at line 40 of file PHG4ScintillatorSlatv1.h.
View newest version in sPHENIX GitHub at line 40 of file PHG4ScintillatorSlatv1.h
References light_yield.
Referenced by identify().
short PHG4ScintillatorSlatv1::get_row () const override virtual
Reimplemented from PHG4ScintillatorSlat.
Definition at line 5 of file PHG4ScintillatorSlatv1.cc.
View newest version in sPHENIX GitHub at line 5 of file PHG4ScintillatorSlatv1.cc
References key.
Referenced by identify().
void PHG4ScintillatorSlatv1::identify (std::ostream & os = std::cout) const override virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from PHG4ScintillatorSlat.
Definition at line 15 of file PHG4ScintillatorSlatv1.cc.
View newest version in sPHENIX GitHub at line 15 of file PHG4ScintillatorSlatv1.cc
References get_column(), get_edep(), get_eion(), get_light_yield(), and get_row().
void PHG4ScintillatorSlatv1::set_key (PHG4ScintillatorSlatDefs::keytype i) inline override virtual
Reimplemented from PHG4ScintillatorSlat.
Definition at line 32 of file PHG4ScintillatorSlatv1.h.
View newest version in sPHENIX GitHub at line 32 of file PHG4ScintillatorSlatv1.h
References i, and key.
void PHG4ScintillatorSlatv1::set_light_yield (const double lightYield) inline
Definition at line 33 of file PHG4ScintillatorSlatv1.h.
View newest version in sPHENIX GitHub at line 33 of file PHG4ScintillatorSlatv1.h
References light_yield.
Member Data Documentation
double PHG4ScintillatorSlatv1::edep = 0. protected
Definition at line 45 of file PHG4ScintillatorSlatv1.h.
View newest version in sPHENIX GitHub at line 45 of file PHG4ScintillatorSlatv1.h
Referenced by add_edep(), and get_edep().
double PHG4ScintillatorSlatv1::eion = 0. protected
Definition at line 46 of file PHG4ScintillatorSlatv1.h.
View newest version in sPHENIX GitHub at line 46 of file PHG4ScintillatorSlatv1.h
Referenced by add_edep(), and get_eion().
std::set<PHG4HitDefs::keytype> PHG4ScintillatorSlatv1::hit_id protected
Definition at line 48 of file PHG4ScintillatorSlatv1.h.
View newest version in sPHENIX GitHub at line 48 of file PHG4ScintillatorSlatv1.h
Referenced by add_hit_key(), and get_hit_ids().
PHG4ScintillatorSlatDefs::keytype PHG4ScintillatorSlatv1::key = ~0x0 protected
Definition at line 44 of file PHG4ScintillatorSlatv1.h.
View newest version in sPHENIX GitHub at line 44 of file PHG4ScintillatorSlatv1.h
Referenced by conftest.RootHashAssertionError::__init__(), get_column(), get_key(), get_row(), and set_key().
double PHG4ScintillatorSlatv1::light_yield = 0. protected
Definition at line 47 of file PHG4ScintillatorSlatv1.h.
View newest version in sPHENIX GitHub at line 47 of file PHG4ScintillatorSlatv1.h
Referenced by add_edep(), get_light_yield(), and set_light_yield().
The documentation for this class was generated from the following files:
coresoftware/blob/master/simulation/g4simulation/g4detectors/PHG4ScintillatorSlatv1.h
coresoftware/blob/master/simulation/g4simulation/g4detectors/PHG4ScintillatorSlatv1.cc