Analysis Software: RawHit Class Reference
RawHit Class Reference
Base class for hit object.
#include <coresoftware/blob/master/offline/packages/trackbase/RawHit.h>
Public Member Functions
~RawHit () override
dtor
void identify (std::ostream &os=std::cout) const override
void Reset () override
Clear Event.
int isValid () const override
isValid returns non zero if object contains vailid data
virtual void setAdc (const unsigned int)
virtual unsigned int getAdc ()
virtual void setPhiBin (const unsigned int)
virtual unsigned int getPhiBin ()
virtual void setTBin (const unsigned int)
virtual unsigned int getTBin ()
Public Member Functions inherited from PHObject
PHObject ()
ctor
~PHObject () override
dtor
virtual PHObject * CloneMe () const
Virtual copy constructor.
virtual PHObject * clone () const final
PHObject * Clone (const char *newname="") const final
void Copy (TObject &object) const final
virtual int Integrate () const
virtual int Integrate (PHObject *)
virtual void CopyFrom (const PHObject *obj)
Protected Member Functions
ClassDefOverride (RawHit, 1)
Detailed Description
Base class for hit object.
This is the empty virtual base class for a hit object. Each subsystem should implement an inherited version which contains the actual storage information.
Definition at line 25 of file RawHit.h.
View newest version in sPHENIX GitHub at line 25 of file RawHit.h
Constructor & Destructor Documentation
RawHit::~RawHit () inline override
dtor
Definition at line 30 of file RawHit.h.
View newest version in sPHENIX GitHub at line 30 of file RawHit.h
Member Function Documentation
RawHit::ClassDefOverride (RawHit , 1) protected
virtual unsigned int RawHit::getAdc () inline virtual
Reimplemented in TPC_RawHit, RawHitTpc, and RawHitv1.
Definition at line 41 of file RawHit.h.
View newest version in sPHENIX GitHub at line 41 of file RawHit.h
virtual unsigned int RawHit::getPhiBin () inline virtual
Reimplemented in TPC_RawHit, RawHitTpc, and RawHitv1.
Definition at line 44 of file RawHit.h.
View newest version in sPHENIX GitHub at line 44 of file RawHit.h
Referenced by MvtxClusterizer::are_adjacent(), and InttClusterizer::ladder_are_adjacent().
virtual unsigned int RawHit::getTBin () inline virtual
Reimplemented in TPC_RawHit, RawHitTpc, and RawHitv1.
Definition at line 47 of file RawHit.h.
View newest version in sPHENIX GitHub at line 47 of file RawHit.h
Referenced by MvtxClusterizer::are_adjacent(), and InttClusterizer::ladder_are_adjacent().
void RawHit::identify (std::ostream & os = std::cout) const inline override virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from PHObject.
Reimplemented in RawHitTpc, and RawHitv1.
Definition at line 32 of file RawHit.h.
View newest version in sPHENIX GitHub at line 32 of file RawHit.h
References os.
int RawHit::isValid () const inline override virtual
isValid returns non zero if object contains vailid data
Reimplemented from PHObject.
Reimplemented in RawHitTpc, and RawHitv1.
Definition at line 37 of file RawHit.h.
View newest version in sPHENIX GitHub at line 37 of file RawHit.h
void RawHit::Reset () inline override virtual
Clear Event.
Reimplemented from PHObject.
Reimplemented in RawHitTpc, and RawHitv1.
Definition at line 36 of file RawHit.h.
View newest version in sPHENIX GitHub at line 36 of file RawHit.h
virtual void RawHit::setAdc (const unsigned int) inline virtual
Reimplemented in TPC_RawHit, RawHitTpc, and RawHitv1.
Definition at line 40 of file RawHit.h.
View newest version in sPHENIX GitHub at line 40 of file RawHit.h
virtual void RawHit::setPhiBin (const unsigned int) inline virtual
Reimplemented in TPC_RawHit, RawHitTpc, and RawHitv1.
Definition at line 43 of file RawHit.h.
View newest version in sPHENIX GitHub at line 43 of file RawHit.h
virtual void RawHit::setTBin (const unsigned int) inline virtual
Reimplemented in TPC_RawHit, RawHitTpc, and RawHitv1.
Definition at line 46 of file RawHit.h.
View newest version in sPHENIX GitHub at line 46 of file RawHit.h
The documentation for this class was generated from the following file:
coresoftware/blob/master/offline/packages/trackbase/RawHit.h