Analysis Software: analysis/blob/master/HF-Jet/TruthGeneration/projections/200pp_pythia8_CTEQ6L_7GeV_ALL.cfg_eneg_DSTReader.root_Draw_HFJetTruth_CrossSection2RAA_Ratio_3yr_deta0.70.C File Reference
200pp_pythia8_CTEQ6L_7GeV_ALL.cfg_eneg_DSTReader.root_Draw_HFJetTruth_CrossSection2RAA_Ratio_3yr_deta0.70.C File Reference
Functions
gStyle SetOptFit (1)
gStyle SetOptStat (0)
gStyle SetOptTitle (0)
Draw_HFJetTruth_CrossSection2RAA_Ratio_3yr_deta0 Range (0, 0, 1, 1)
Draw_HFJetTruth_CrossSection2RAA_Ratio_3yr_deta0 SetFillColor (0)
Draw_HFJetTruth_CrossSection2RAA_Ratio_3yr_deta0 SetBorderMode (0)
Draw_HFJetTruth_CrossSection2RAA_Ratio_3yr_deta0 SetBorderSize (2)
Draw_HFJetTruth_CrossSection2RAA_Ratio_3yr_deta0 SetTickx (1)
Draw_HFJetTruth_CrossSection2RAA_Ratio_3yr_deta0 SetTicky (1)
Draw_HFJetTruth_CrossSection2RAA_Ratio_3yr_deta0 SetLeftMargin (0.16)
Draw_HFJetTruth_CrossSection2RAA_Ratio_3yr_deta0 SetRightMargin (0.05)
Draw_HFJetTruth_CrossSection2RAA_Ratio_3yr_deta0 SetTopMargin (0.05)
Draw_HFJetTruth_CrossSection2RAA_Ratio_3yr_deta0 SetBottomMargin (0.16)
Draw_HFJetTruth_CrossSection2RAA_Ratio_3yr_deta0 SetFrameBorderMode (0)
Draw_HFJetTruth_CrossSection2RAA_Ratio_3yr_deta0 Draw ()
Draw_HFJetTruth_CrossSection2RAA_Ratio_3yr_deta0 cd ()
Draw_HFJetTruth_CrossSection2RAA_Ratio_3yr_deta0 Range (-20.25316,-0.4204901, 106.3291, 2.207573)
h_b_copy846930886 SetBinContent (4, 1)
h_b_copy846930886 SetBinContent (5, 1)
h_b_copy846930886 SetBinContent (6, 1)
h_b_copy846930886 SetBinContent (7, 1)
h_b_copy846930886 SetBinContent (8, 1)
h_b_copy846930886 SetBinContent (9, 1)
h_b_copy846930886 SetBinContent (10, 1)
h_b_copy846930886 SetBinError (4, 0.008925437)
h_b_copy846930886 SetBinError (5, 0.02146109)
h_b_copy846930886 SetBinError (6, 0.04903408)
h_b_copy846930886 SetBinError (7, 0.1079253)
h_b_copy846930886 SetBinError (8, 0.2635595)
h_b_copy846930886 SetBinError (9, 0.5893369)
h_b_copy846930886 SetBinError (10, 0.9773048)
h_b_copy846930886 SetEntries (58360)
h_b_copy846930886 SetLineColor (ci)
h_b_copy846930886 SetLineWidth (2)
h_b_copy846930886 SetMarkerStyle (20)
h_b_copy846930886 SetMarkerSize (1.2)
h_b_copy846930886 GetXaxis () -> SetTitle("p_
h_b_copy846930886 GetYaxis () -> SetTitle("Relative Cross Section and Uncertainty")
h_b_copy846930886 GetZaxis () -> SetLabelFont(42)
h_b_copy846930886 Draw ("")
h_b_copy1681692777 SetBinContent (4, 0.6)
h_b_copy1681692777 SetBinContent (5, 0.6)
h_b_copy1681692777 SetBinContent (6, 0.6)
h_b_copy1681692777 SetBinContent (7, 0.6)
h_b_copy1681692777 SetBinContent (8, 0.6)
h_b_copy1681692777 SetBinContent (9, 0.6)
h_b_copy1681692777 SetBinContent (10, 0.6)
h_b_copy1681692777 Draw ("same")
Draw_HFJetTruth_CrossSection2RAA_Ratio_3yr_deta0 Modified ()
Draw_HFJetTruth_CrossSection2RAA_Ratio_3yr_deta0 SetSelected (Draw_HFJetTruth_CrossSection2RAA_Ratio_3yr_deta0.70)
Variables
TPad * Draw_HFJetTruth_CrossSection2RAA_Ratio_3yr_deta0 = new TPad("Draw_HFJetTruth_CrossSection2RAA_Ratio_3yr_deta0.70_1", "Draw_HFJetTruth_CrossSection2RAA_Ratio_3yr_deta0.70_1",0.01,0.01,0.99,0.99)
TH1F * h_b_copy846930886 = new TH1F("h_b_copy846930886","",20,0,100)
Int_t ci = TColor::GetColor("#ff0000")
TColor * color
TH1F * h_b_copy1681692777 = new TH1F("h_b_copy1681692777","",20,0,100)
Function Documentation
Draw_HFJetTruth_CrossSection2RAA_Ratio_3yr_deta0 cd ()
Draw_HFJetTruth_CrossSection2RAA_Ratio_3yr_deta0 Draw ()
h_b_copy846930886 Draw ("")
h_b_copy1681692777 Draw ("same")
h_b_copy846930886 GetXaxis () -> SetTitle("p_
Definition at line 61 of file 200pp_pythia8_CTEQ6L_7GeV_ALL.cfg_eneg_DSTReader.root_Draw_HFJetTruth_CrossSection2RAA_Ratio_3yr_deta0.70.C.
View newest version in sPHENIX GitHub at line 61 of file 200pp_pythia8_CTEQ6L_7GeV_ALL.cfg_eneg_DSTReader.root_Draw_HFJetTruth_CrossSection2RAA_Ratio_3yr_deta0.70.C
h_b_copy846930886 GetYaxis () -> SetTitle("Relative Cross Section and Uncertainty")
Definition at line 51 of file 200pp_pythia8_CTEQ6L_7GeV_ALL.cfg_eneg_DSTReader.root_Draw_HFJetTruth_CrossSection2RAA.C.
View newest version in sPHENIX GitHub at line 51 of file 200pp_pythia8_CTEQ6L_7GeV_ALL.cfg_eneg_DSTReader.root_Draw_HFJetTruth_CrossSection2RAA.C
h_b_copy846930886 GetZaxis () -> SetLabelFont(42)
Draw_HFJetTruth_CrossSection2RAA_Ratio_3yr_deta0 Modified ()
Draw_HFJetTruth_CrossSection2RAA_Ratio_3yr_deta0 Range (0 , 0 , 1 , 1)
Draw_HFJetTruth_CrossSection2RAA_Ratio_3yr_deta0 Range (-20. 25316, -0. 4204901, 106. 3291, 2. 207573)
h_b_copy846930886 SetBinContent (4 , 1)
Referenced by towerid::CalculateCutOffs(), DoPercentDifference(), CemcMonDraw::DrawFirst(), SColdQcdCorrelatorAnalysis::SEnergyCorrelator::ExtractHistsFromCorr(), GetSubtractedDist(), and CemcMon::process_event().
h_b_copy846930886 SetBinContent (5 , 1)
h_b_copy846930886 SetBinContent (6 , 1)
h_b_copy846930886 SetBinContent (7 , 1)
h_b_copy846930886 SetBinContent (8 , 1)
h_b_copy846930886 SetBinContent (9 , 1)
h_b_copy846930886 SetBinContent (10 , 1)
h_b_copy1681692777 SetBinContent (4 , 0. 6)
h_b_copy1681692777 SetBinContent (5 , 0. 6)
h_b_copy1681692777 SetBinContent (6 , 0. 6)
h_b_copy1681692777 SetBinContent (7 , 0. 6)
h_b_copy1681692777 SetBinContent (8 , 0. 6)
h_b_copy1681692777 SetBinContent (9 , 0. 6)
h_b_copy1681692777 SetBinContent (10 , 0. 6)
h_b_copy1681692777 SetBinError (4 , 0. 008925437)
Referenced by DoPercentDifference(), and SColdQcdCorrelatorAnalysis::SEnergyCorrelator::ExtractHistsFromCorr().
h_b_copy1681692777 SetBinError (5 , 0. 02146109)
h_b_copy1681692777 SetBinError (6 , 0. 04903408)
h_b_copy1681692777 SetBinError (7 , 0. 1079253)
h_b_copy1681692777 SetBinError (8 , 0. 2635595)
h_b_copy1681692777 SetBinError (9 , 0. 5893369)
h_b_copy1681692777 SetBinError (10 , 0. 9773048)
Draw_HFJetTruth_CrossSection2RAA_Ratio_3yr_deta0 SetBorderMode (0)
Draw_HFJetTruth_CrossSection2RAA_Ratio_3yr_deta0 SetBorderSize (2)
Draw_HFJetTruth_CrossSection2RAA_Ratio_3yr_deta0 SetBottomMargin (0. 16)
h_b_copy1681692777 SetEntries (58360)
Draw_HFJetTruth_CrossSection2RAA_Ratio_3yr_deta0 SetFillColor (0)
Draw_HFJetTruth_CrossSection2RAA_Ratio_3yr_deta0 SetFrameBorderMode (0)
Draw_HFJetTruth_CrossSection2RAA_Ratio_3yr_deta0 SetLeftMargin (0. 16)
fTCBfordave SetLineColor (ci)
h_b_copy846930886 SetLineWidth (2)
h_b_copy846930886 SetMarkerSize (1. 2)
h_b_copy846930886 SetMarkerStyle (20)
gStyle SetOptFit (1)
gStyle SetOptStat (0)
gStyle SetOptTitle (0)
Draw_HFJetTruth_CrossSection2RAA_Ratio_3yr_deta0 SetRightMargin (0. 05)
Draw_HFJetTruth_CrossSection2RAA_Ratio_3yr_deta0 SetSelected (Draw_HFJetTruth_CrossSection2RAA_Ratio_3yr_deta0. 70)
Draw_HFJetTruth_CrossSection2RAA_Ratio_3yr_deta0 SetTickx (1)
Draw_HFJetTruth_CrossSection2RAA_Ratio_3yr_deta0 SetTicky (1)
Draw_HFJetTruth_CrossSection2RAA_Ratio_3yr_deta0 SetTopMargin (0. 05)
Variable Documentation
ci = TColor::GetColor("#ff0000")
Definition at line 54 of file 200pp_pythia8_CTEQ6L_7GeV_ALL.cfg_eneg_DSTReader.root_Draw_HFJetTruth_CrossSection2RAA_Ratio_3yr_deta0.70.C.
View newest version in sPHENIX GitHub at line 54 of file 200pp_pythia8_CTEQ6L_7GeV_ALL.cfg_eneg_DSTReader.root_Draw_HFJetTruth_CrossSection2RAA_Ratio_3yr_deta0.70.C
Referenced by AN_dp_sPHENIX(), D0_BUP2020_AN_3yr(), D0_BUP2020_AN_5yr_comparison(), D0_BUP2020_AuAu_RAA_3yr(), D0_BUP2020_AuAu_v1_5y_compare(), D0_BUP2020_AuAu_v2_3yr(), D0_BUP2020_AuAu_v2_3yr_20wk_comp(), D0_BUP2020_pAu_C0_5_v2_3yr(), D0_BUP2020_pAu_v2_3yr(), D0_BUP2020ArAr_significance_5yr(), D0_BUP2020AuAu_0_10_significance_3yr(), D0_BUP2020OO_significance_5yr(), D0_BUP2020OOArAr_RAA_5yr(), D0_BUP2020OOArAr_RAA_flat_5yr(), D0_BUP2020OOArAr_v2_5yr(), D0_BUP2020pp_significance_3yr(), D0_BUP2020pp_significance_5yr(), Error_Viz(), fg(), fgp(), CaloCalibEmc_Pi0::Fit_Histos(), CaloCalibEmc_Pi0::Fit_Histos_Eta_Phi_Add32(), CaloCalibEmc_Pi0::Fit_Histos_Eta_Phi_Add96(), CaloCalibEmc_Pi0::Fit_Histos_Etas96(), JetSpectra(), Lc_BUP2020_AuAu_3yr(), Lc_BUP2022_AuAu_3yr(), CaloCalibEmc_Pi0::Loop(), CaloCalibEmc_Pi0::Loop_for_eta_slices(), MakeShowerGraph(), pycdiv(), pyrnmq(), rootTrackClusterEnergy(), rootTrackQA(), rootTruckatedMean(), and sphenix_han().
TColor* color
Definition at line 55 of file 200pp_pythia8_CTEQ6L_7GeV_ALL.cfg_eneg_DSTReader.root_Draw_HFJetTruth_CrossSection2RAA_Ratio_3yr_deta0.70.C.
View newest version in sPHENIX GitHub at line 55 of file 200pp_pythia8_CTEQ6L_7GeV_ALL.cfg_eneg_DSTReader.root_Draw_HFJetTruth_CrossSection2RAA_Ratio_3yr_deta0.70.C
Referenced by Acts::Python::addOutput(), AN_dp_sPHENIX(), PHG4TpcDisplayAction::ApplyDisplayAction(), BOOST_AUTO_TEST_CASE(), Acts::Test::BOOST_AUTO_TEST_CASE(), ChargePerLayer(), PHG4MicromegasDetector::construct_fee_board(), PHG4MicromegasDetector::construct_micromegas_tile(), Acts::Svg::SurfaceConverter::convert(), D0_BUP2020_AN_3yr(), D0_BUP2020_AN_5yr_comparison(), D0_BUP2020_AuAu_RAA_3yr(), D0_BUP2020_AuAu_v1_5y_compare(), D0_BUP2020_AuAu_v2_3yr(), D0_BUP2020_AuAu_v2_3yr_20wk_comp(), D0_BUP2020_pAu_C0_5_v2_3yr(), D0_BUP2020_pAu_v2_3yr(), D0_BUP2020ArAr_significance_5yr(), D0_BUP2020AuAu_0_10_significance_3yr(), D0_BUP2020OO_significance_5yr(), D0_BUP2020OOArAr_RAA_5yr(), D0_BUP2020OOArAr_RAA_flat_5yr(), D0_BUP2020OOArAr_v2_5yr(), D0_BUP2020pp_significance_3yr(), D0_BUP2020pp_significance_5yr(), Matter::DoEnergyLoss(), ColoredHadronization::DoHadronization(), Acts::Experimental::Blueprint::Node::dotStream(), DrawTpcPrototypeGenFitTrkFitter_Summary(), Error_Viz(), Acts::ObjVisualization3D< T >::face(), Acts::ObjVisualization3D< T >::faces(), getResolutions(), testing::internal::GTestFlagSaver::GTestFlagSaver(), Acts::Svg::infoBox(), JetSpectra(), Lc_BUP2020_AuAu_3yr(), Lc_BUP2022_AuAu_3yr(), Acts::ObjVisualization3D< T >::line(), MakeShowerGraph(), testing::internal::ParseGoogleTestFlag(), genfit::Track::Print(), testing::internal::PrintColorEncoded(), testing::PrintFlag(), rootTrackClusterEnergy(), rootTrackQA(), rootTruckatedMean(), setEffStyle(), SetHist(), setHistStyle(), testing::internal::ShouldUseColor(), sphenix_han(), Acts::Frustum< value_t, DIM, SIDES >::svg(), Acts::AxisAlignedBoundingBox< entity_t, value_t, DIM >::svg(), TEST(), Acts::ObjVisualization3D< T >::vertex(), and testing::internal::GTestFlagSaver::~GTestFlagSaver().
TPad* Draw_HFJetTruth_CrossSection2RAA_Ratio_3yr_deta0 = new TPad("Draw_HFJetTruth_CrossSection2RAA_Ratio_3yr_deta0.70_1", "Draw_HFJetTruth_CrossSection2RAA_Ratio_3yr_deta0.70_1",0.01,0.01,0.99,0.99)
Definition at line 21 of file 200pp_pythia8_CTEQ6L_7GeV_ALL.cfg_eneg_DSTReader.root_Draw_HFJetTruth_CrossSection2RAA_Ratio_3yr_deta0.70.C.
View newest version in sPHENIX GitHub at line 21 of file 200pp_pythia8_CTEQ6L_7GeV_ALL.cfg_eneg_DSTReader.root_Draw_HFJetTruth_CrossSection2RAA_Ratio_3yr_deta0.70.C
TH1F* h_b_copy1681692777 = new TH1F("h_b_copy1681692777","",20,0,100)
Definition at line 80 of file 200pp_pythia8_CTEQ6L_7GeV_ALL.cfg_eneg_DSTReader.root_Draw_HFJetTruth_CrossSection2RAA_Ratio_3yr_deta0.70.C.
View newest version in sPHENIX GitHub at line 80 of file 200pp_pythia8_CTEQ6L_7GeV_ALL.cfg_eneg_DSTReader.root_Draw_HFJetTruth_CrossSection2RAA_Ratio_3yr_deta0.70.C
TH1F* h_b_copy846930886 = new TH1F("h_b_copy846930886","",20,0,100)
Definition at line 37 of file 200pp_pythia8_CTEQ6L_7GeV_ALL.cfg_eneg_DSTReader.root_Draw_HFJetTruth_CrossSection2RAA_Ratio_3yr_deta0.70.C.
View newest version in sPHENIX GitHub at line 37 of file 200pp_pythia8_CTEQ6L_7GeV_ALL.cfg_eneg_DSTReader.root_Draw_HFJetTruth_CrossSection2RAA_Ratio_3yr_deta0.70.C