Analysis Software: RawTowerGeomv3 Class Reference
RawTowerGeomv3 Class Reference
#include <coresoftware/blob/master/offline/packages/CaloBase/RawTowerGeomv3.h>
Public Member Functions
RawTowerGeomv3 ()
RawTowerGeomv3 (RawTowerDefs::keytype id)
~RawTowerGeomv3 () override
void identify (std::ostream &os=std::cout) const override
void set_id (RawTowerDefs::keytype key) override
RawTowerDefs::keytype get_id () const override
int get_bineta () const override
int get_binphi () const override
int get_column () const override
int get_row () const override
int get_binl () const override
void set_center_x (double x) override
void set_center_y (double y) override
void set_center_z (double z) override
void set_size_x (double dx) override
void set_size_y (double dy) override
void set_size_z (double dz) override
double get_center_x () const override
double get_center_y () const override
double get_center_z () const override
double get_size_x () const override
double get_size_y () const override
double get_size_z () const override
double get_volume () const override
double get_center_radius () const override
double get_eta () const override
double get_phi () const override
double get_theta () const override
void set_tower_type (int tt) override
int get_tower_type () const override
Public Member Functions inherited from RawTowerGeom
~RawTowerGeom () override
virtual double get_roty () const
virtual double get_rotz () const
virtual void set_roty (double)
virtual void set_rotz (double)
Public Member Functions inherited from PHObject
PHObject ()
ctor
~PHObject () override
dtor
virtual PHObject * CloneMe () const
Virtual copy constructor.
virtual PHObject * clone () const final
PHObject * Clone (const char *newname="") const final
void Copy (TObject &object) const final
virtual void Reset ()
Clear Event.
virtual int isValid () const
isValid returns non zero if object contains vailid data
virtual int Integrate () const
virtual int Integrate (PHObject *)
virtual void CopyFrom (const PHObject *obj)
Protected Attributes
RawTowerDefs::keytype _towerid = ~0
double _center_x = NAN
double _center_y = NAN
double _center_z = NAN
double _size_x = NAN
double _size_y = NAN
double _size_z = NAN
int _tower_type = -1
Additional Inherited Members
Protected Member Functions inherited from RawTowerGeom
RawTowerGeom ()
Detailed Description
Definition at line 11 of file RawTowerGeomv3.h.
View newest version in sPHENIX GitHub at line 11 of file RawTowerGeomv3.h
Constructor & Destructor Documentation
RawTowerGeomv3::RawTowerGeomv3 () inline
Definition at line 14 of file RawTowerGeomv3.h.
View newest version in sPHENIX GitHub at line 14 of file RawTowerGeomv3.h
RawTowerGeomv3::RawTowerGeomv3 (RawTowerDefs::keytype id)
Definition at line 6 of file RawTowerGeomv3.cc.
View newest version in sPHENIX GitHub at line 6 of file RawTowerGeomv3.cc
RawTowerGeomv3::~RawTowerGeomv3 () inline override
Definition at line 16 of file RawTowerGeomv3.h.
View newest version in sPHENIX GitHub at line 16 of file RawTowerGeomv3.h
Member Function Documentation
int RawTowerGeomv3::get_bineta () const override virtual
Reimplemented from RawTowerGeom.
Definition at line 36 of file RawTowerGeomv3.cc.
View newest version in sPHENIX GitHub at line 36 of file RawTowerGeomv3.cc
References _towerid, RawTowerDefs::decode_caloid(), RawTowerDefs::decode_index1(), RawTowerDefs::decode_index1v2(), and RawTowerDefs::LFHCAL.
Referenced by get_column().
int RawTowerGeomv3::get_binl () const inline override virtual
Reimplemented from RawTowerGeom.
Definition at line 29 of file RawTowerGeomv3.h.
View newest version in sPHENIX GitHub at line 29 of file RawTowerGeomv3.h
References _towerid, and RawTowerDefs::decode_index3v2().
int RawTowerGeomv3::get_binphi () const override virtual
Reimplemented from RawTowerGeom.
Definition at line 49 of file RawTowerGeomv3.cc.
View newest version in sPHENIX GitHub at line 49 of file RawTowerGeomv3.cc
References _towerid, RawTowerDefs::decode_caloid(), RawTowerDefs::decode_index2(), RawTowerDefs::decode_index2v2(), and RawTowerDefs::LFHCAL.
Referenced by get_row().
double RawTowerGeomv3::get_center_radius () const override virtual
Reimplemented from RawTowerGeom.
Definition at line 11 of file RawTowerGeomv3.cc.
View newest version in sPHENIX GitHub at line 11 of file RawTowerGeomv3.cc
References _center_x, and _center_y.
double RawTowerGeomv3::get_center_x () const inline override virtual
Reimplemented from RawTowerGeom.
Definition at line 63 of file RawTowerGeomv3.h.
View newest version in sPHENIX GitHub at line 63 of file RawTowerGeomv3.h
References _center_x.
Referenced by identify().
double RawTowerGeomv3::get_center_y () const inline override virtual
Reimplemented from RawTowerGeom.
Definition at line 64 of file RawTowerGeomv3.h.
View newest version in sPHENIX GitHub at line 64 of file RawTowerGeomv3.h
References _center_y.
Referenced by identify().
double RawTowerGeomv3::get_center_z () const inline override virtual
Reimplemented from RawTowerGeom.
Definition at line 65 of file RawTowerGeomv3.h.
View newest version in sPHENIX GitHub at line 65 of file RawTowerGeomv3.h
References _center_z.
Referenced by identify().
int RawTowerGeomv3::get_column () const inline override virtual
Reimplemented from RawTowerGeom.
Definition at line 26 of file RawTowerGeomv3.h.
View newest version in sPHENIX GitHub at line 26 of file RawTowerGeomv3.h
References get_bineta().
double RawTowerGeomv3::get_eta () const override virtual
Reimplemented from RawTowerGeom.
Definition at line 24 of file RawTowerGeomv3.cc.
View newest version in sPHENIX GitHub at line 24 of file RawTowerGeomv3.cc
References eta, get_theta(), and ActsTests::PropagationDatasets::theta.
RawTowerDefs::keytype RawTowerGeomv3::get_id () const inline override virtual
Reimplemented from RawTowerGeom.
Definition at line 21 of file RawTowerGeomv3.h.
View newest version in sPHENIX GitHub at line 21 of file RawTowerGeomv3.h
References _towerid.
double RawTowerGeomv3::get_phi () const override virtual
Reimplemented from RawTowerGeom.
Definition at line 31 of file RawTowerGeomv3.cc.
View newest version in sPHENIX GitHub at line 31 of file RawTowerGeomv3.cc
References _center_x, and _center_y.
int RawTowerGeomv3::get_row () const inline override virtual
Reimplemented from RawTowerGeom.
Definition at line 27 of file RawTowerGeomv3.h.
View newest version in sPHENIX GitHub at line 27 of file RawTowerGeomv3.h
References get_binphi().
double RawTowerGeomv3::get_size_x () const inline override virtual
Reimplemented from RawTowerGeom.
Definition at line 67 of file RawTowerGeomv3.h.
View newest version in sPHENIX GitHub at line 67 of file RawTowerGeomv3.h
References _size_x.
Referenced by identify().
double RawTowerGeomv3::get_size_y () const inline override virtual
Reimplemented from RawTowerGeom.
Definition at line 68 of file RawTowerGeomv3.h.
View newest version in sPHENIX GitHub at line 68 of file RawTowerGeomv3.h
References _size_y.
Referenced by identify().
double RawTowerGeomv3::get_size_z () const inline override virtual
Reimplemented from RawTowerGeom.
Definition at line 69 of file RawTowerGeomv3.h.
View newest version in sPHENIX GitHub at line 69 of file RawTowerGeomv3.h
References _size_z.
Referenced by identify().
double RawTowerGeomv3::get_theta () const override virtual
Reimplemented from RawTowerGeom.
Definition at line 17 of file RawTowerGeomv3.cc.
View newest version in sPHENIX GitHub at line 17 of file RawTowerGeomv3.cc
References _center_x, _center_y, _center_z, and ActsTests::PropagationDatasets::theta.
Referenced by get_eta().
int RawTowerGeomv3::get_tower_type () const inline override virtual
Reimplemented from RawTowerGeom.
Definition at line 78 of file RawTowerGeomv3.h.
View newest version in sPHENIX GitHub at line 78 of file RawTowerGeomv3.h
References _tower_type.
double RawTowerGeomv3::get_volume () const inline override virtual
Reimplemented from RawTowerGeom.
Definition at line 70 of file RawTowerGeomv3.h.
View newest version in sPHENIX GitHub at line 70 of file RawTowerGeomv3.h
References _size_x, _size_y, and _size_z.
void RawTowerGeomv3::identify (std::ostream & os = std::cout) const override virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from RawTowerGeom.
Definition at line 62 of file RawTowerGeomv3.cc.
View newest version in sPHENIX GitHub at line 62 of file RawTowerGeomv3.cc
References _tower_type, get_center_x(), get_center_y(), get_center_z(), get_size_x(), get_size_y(), and get_size_z().
void RawTowerGeomv3::set_center_x (double x) inline override virtual
Reimplemented from RawTowerGeom.
Definition at line 31 of file RawTowerGeomv3.h.
View newest version in sPHENIX GitHub at line 31 of file RawTowerGeomv3.h
References _center_x, and ambiguity_solver_full_chain::x.
void RawTowerGeomv3::set_center_y (double y) inline override virtual
Reimplemented from RawTowerGeom.
Definition at line 36 of file RawTowerGeomv3.h.
View newest version in sPHENIX GitHub at line 36 of file RawTowerGeomv3.h
References _center_y, and y.
void RawTowerGeomv3::set_center_z (double z) inline override virtual
Reimplemented from RawTowerGeom.
Definition at line 41 of file RawTowerGeomv3.h.
View newest version in sPHENIX GitHub at line 41 of file RawTowerGeomv3.h
References _center_z, and physmon_track_finding_ttbar::z.
void RawTowerGeomv3::set_id (RawTowerDefs::keytype key) inline override virtual
Reimplemented from RawTowerGeom.
Definition at line 20 of file RawTowerGeomv3.h.
View newest version in sPHENIX GitHub at line 20 of file RawTowerGeomv3.h
References _towerid.
void RawTowerGeomv3::set_size_x (double dx) inline override virtual
Reimplemented from RawTowerGeom.
Definition at line 47 of file RawTowerGeomv3.h.
View newest version in sPHENIX GitHub at line 47 of file RawTowerGeomv3.h
References _size_x.
void RawTowerGeomv3::set_size_y (double dy) inline override virtual
Reimplemented from RawTowerGeom.
Definition at line 52 of file RawTowerGeomv3.h.
View newest version in sPHENIX GitHub at line 52 of file RawTowerGeomv3.h
References _size_y, and dy.
void RawTowerGeomv3::set_size_z (double dz) inline override virtual
Reimplemented from RawTowerGeom.
Definition at line 57 of file RawTowerGeomv3.h.
View newest version in sPHENIX GitHub at line 57 of file RawTowerGeomv3.h
References _size_z, and dz.
void RawTowerGeomv3::set_tower_type (int tt) inline override virtual
Reimplemented from RawTowerGeom.
Definition at line 77 of file RawTowerGeomv3.h.
View newest version in sPHENIX GitHub at line 77 of file RawTowerGeomv3.h
References _tower_type.
Member Data Documentation
double RawTowerGeomv3::_center_x = NAN protected
Definition at line 83 of file RawTowerGeomv3.h.
View newest version in sPHENIX GitHub at line 83 of file RawTowerGeomv3.h
Referenced by get_center_radius(), get_center_x(), get_phi(), get_theta(), and set_center_x().
double RawTowerGeomv3::_center_y = NAN protected
Definition at line 84 of file RawTowerGeomv3.h.
View newest version in sPHENIX GitHub at line 84 of file RawTowerGeomv3.h
Referenced by get_center_radius(), get_center_y(), get_phi(), get_theta(), and set_center_y().
double RawTowerGeomv3::_center_z = NAN protected
Definition at line 85 of file RawTowerGeomv3.h.
View newest version in sPHENIX GitHub at line 85 of file RawTowerGeomv3.h
Referenced by get_center_z(), get_theta(), and set_center_z().
double RawTowerGeomv3::_size_x = NAN protected
Definition at line 87 of file RawTowerGeomv3.h.
View newest version in sPHENIX GitHub at line 87 of file RawTowerGeomv3.h
Referenced by get_size_x(), get_volume(), and set_size_x().
double RawTowerGeomv3::_size_y = NAN protected
Definition at line 88 of file RawTowerGeomv3.h.
View newest version in sPHENIX GitHub at line 88 of file RawTowerGeomv3.h
Referenced by get_size_y(), get_volume(), and set_size_y().
double RawTowerGeomv3::_size_z = NAN protected
Definition at line 89 of file RawTowerGeomv3.h.
View newest version in sPHENIX GitHub at line 89 of file RawTowerGeomv3.h
Referenced by get_size_z(), get_volume(), and set_size_z().
int RawTowerGeomv3::_tower_type = -1 protected
Definition at line 91 of file RawTowerGeomv3.h.
View newest version in sPHENIX GitHub at line 91 of file RawTowerGeomv3.h
Referenced by get_tower_type(), identify(), and set_tower_type().
RawTowerDefs::keytype RawTowerGeomv3::_towerid = ~0 protected
Definition at line 81 of file RawTowerGeomv3.h.
View newest version in sPHENIX GitHub at line 81 of file RawTowerGeomv3.h
Referenced by get_bineta(), get_binl(), get_binphi(), get_id(), and set_id().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/CaloBase/RawTowerGeomv3.h
coresoftware/blob/master/offline/packages/CaloBase/RawTowerGeomv3.cc