Analysis Software: ActsPropagator Class Reference
ActsPropagator Class Reference
#include <coresoftware/blob/master/offline/packages/trackreco/ActsPropagator.h>
Public Types
using BoundTrackParam = Acts::BoundTrackParameters
using BoundTrackParamResult = Acts::Result< BoundTrackParam >
using BoundTrackParamPair = std::pair< float, BoundTrackParam >
Return type of std::pair<path length, parameters>
using BTPPairResult = Acts::Result< BoundTrackParamPair >
using SurfacePtr = std::shared_ptr< const Acts::Surface >
using Stepper = Acts::EigenStepper<>
using FastPropagator = Acts::Propagator< Stepper >
using SphenixPropagator = Acts::Propagator< Stepper, Acts::Navigator >
Public Member Functions
ActsPropagator ()
ActsPropagator (ActsGeometry *geometry)
~ActsPropagator ()
SurfacePtr makeVertexSurface (const SvtxVertex *vertex)
SurfacePtr makeVertexSurface (const Acts::Vector3 &vertex)
BoundTrackParamResult makeTrackParams (SvtxTrack *track, SvtxVertexMap *vertexMap)
BoundTrackParamResult makeTrackParams (SvtxTrackState *state, int trackCharge, SurfacePtr surf)
BTPPairResult propagateTrack (const Acts::BoundTrackParameters &params, const unsigned int sphenixLayer)
BTPPairResult propagateTrack (const Acts::BoundTrackParameters &params, const SurfacePtr &surface)
BTPPairResult propagateTrackFast (const Acts::BoundTrackParameters &params, const SurfacePtr &surface)
bool checkLayer (const unsigned int &sphenixlayer, unsigned int &actsvolume, unsigned int &actslayer)
void verbosity (int verb)
void setConstFieldValue (float field)
void constField ()
void setOverstepLimit (const double overstep)
SphenixPropagator makePropagator ()
FastPropagator makeFastPropagator ()
Private Member Functions
void printTrackParams (const Acts::BoundTrackParameters &params)
Private Attributes
int m_verbosity = 0
bool m_constField = false
ActsGeometry * m_geometry = nullptr
float m_fieldval = 1.4 * Acts::UnitConstants::T
float m_overstepLimit = 0.01 * Acts::UnitConstants::cm
Default Acts limit.
Detailed Description
Definition at line 30 of file ActsPropagator.h.
View newest version in sPHENIX GitHub at line 30 of file ActsPropagator.h
Member Typedef Documentation
using ActsPropagator::BoundTrackParam = Acts::BoundTrackParameters
Definition at line 33 of file ActsPropagator.h.
View newest version in sPHENIX GitHub at line 33 of file ActsPropagator.h
using ActsPropagator::BoundTrackParamPair = std::pair<float, BoundTrackParam>
Return type of std::pair<path length, parameters>
Definition at line 36 of file ActsPropagator.h.
View newest version in sPHENIX GitHub at line 36 of file ActsPropagator.h
using ActsPropagator::BoundTrackParamResult = Acts::Result<BoundTrackParam>
Definition at line 34 of file ActsPropagator.h.
View newest version in sPHENIX GitHub at line 34 of file ActsPropagator.h
using ActsPropagator::BTPPairResult = Acts::Result<BoundTrackParamPair>
Definition at line 37 of file ActsPropagator.h.
View newest version in sPHENIX GitHub at line 37 of file ActsPropagator.h
using ActsPropagator::FastPropagator = Acts::Propagator<Stepper>
Definition at line 40 of file ActsPropagator.h.
View newest version in sPHENIX GitHub at line 40 of file ActsPropagator.h
using ActsPropagator::SphenixPropagator = Acts::Propagator<Stepper, Acts::Navigator>
Definition at line 41 of file ActsPropagator.h.
View newest version in sPHENIX GitHub at line 41 of file ActsPropagator.h
using ActsPropagator::Stepper = Acts::EigenStepper<>
Definition at line 39 of file ActsPropagator.h.
View newest version in sPHENIX GitHub at line 39 of file ActsPropagator.h
using ActsPropagator::SurfacePtr = std::shared_ptr<const Acts::Surface>
Definition at line 38 of file ActsPropagator.h.
View newest version in sPHENIX GitHub at line 38 of file ActsPropagator.h
Constructor & Destructor Documentation
ActsPropagator::ActsPropagator () inline
Definition at line 43 of file ActsPropagator.h.
View newest version in sPHENIX GitHub at line 43 of file ActsPropagator.h
ActsPropagator::ActsPropagator (ActsGeometry * geometry) inline
Definition at line 44 of file ActsPropagator.h.
View newest version in sPHENIX GitHub at line 44 of file ActsPropagator.h
ActsPropagator::~ActsPropagator () inline
Definition at line 48 of file ActsPropagator.h.
View newest version in sPHENIX GitHub at line 48 of file ActsPropagator.h
Member Function Documentation
bool ActsPropagator::checkLayer (const unsigned int & sphenixlayer, unsigned int & actsvolume, unsigned int & actslayer)
mvtx
intt
tpc
tpot only has one layer in Acts geometry
Test to make sure the found volume and layer exist
Definition at line 252 of file ActsPropagator.cc.
View newest version in sPHENIX GitHub at line 252 of file ActsPropagator.cc
References ActsGeometry::geometry(), Acts::GeometryObject::geometryId(), Acts::GeometryIdentifier::layer(), layer, m_geometry, ActsTrackingGeometry::tGeometry, and Acts::GeometryIdentifier::volume().
Referenced by propagateTrack().
void ActsPropagator::constField () inline
Definition at line 81 of file ActsPropagator.h.
View newest version in sPHENIX GitHub at line 81 of file ActsPropagator.h
References m_constField.
Referenced by ActsAlignmentStates::fillAlignmentStateMap(), and PHActsTrackProjection::propagateTrack().
ActsPropagator::FastPropagator ActsPropagator::makeFastPropagator ()
Definition at line 197 of file ActsPropagator.cc.
View newest version in sPHENIX GitHub at line 197 of file ActsPropagator.cc
References Acts::Logging::FATAL, ckf::field, ActsGeometry::geometry(), Acts::getDefaultLogger(), logger(), telescope_simulation::logLevel, m_constField, m_fieldval, m_geometry, m_verbosity, ActsTrackingGeometry::magField, propagation_timing::stepper, and Acts::Logging::VERBOSE.
Referenced by propagateTrackFast().
ActsPropagator::SphenixPropagator ActsPropagator::makePropagator ()
Definition at line 224 of file ActsPropagator.cc.
View newest version in sPHENIX GitHub at line 224 of file ActsPropagator.cc
References cfg, Acts::Logging::FATAL, ckf::field, ActsGeometry::geometry(), Acts::getDefaultLogger(), logger(), telescope_simulation::logLevel, m_constField, m_fieldval, m_geometry, m_overstepLimit, m_verbosity, ActsTrackingGeometry::magField, Acts::Test::navigator, propagation_timing::stepper, ActsTrackingGeometry::tGeometry, digitization_config::trackingGeometry, and Acts::Logging::VERBOSE.
Referenced by MakeMilleFiles::getLocalVtxDerivativesXY(), and propagateTrack().
ActsPropagator::BoundTrackParamResult ActsPropagator::makeTrackParams (SvtxTrack * track, SvtxVertexMap * vertexMap)
Definition at line 60 of file ActsPropagator.cc.
View newest version in sPHENIX GitHub at line 60 of file ActsPropagator.cc
References Acts::UnitConstants::cm, Acts::Test::cov, Acts::GenericBoundTrackParameters< particle_hypothesis_t >::create(), ActsGeometry::geometry(), SvtxVertexMap::get(), SvtxTrack::get_charge(), SvtxTrack::get_p(), SvtxTrack::get_px(), SvtxTrack::get_py(), SvtxTrack::get_pz(), SvtxTrack::get_vertex_id(), SvtxVertex::get_x(), SvtxTrack::get_x(), SvtxVertex::get_y(), SvtxTrack::get_y(), SvtxVertex::get_z(), SvtxTrack::get_z(), ActsTrackingGeometry::getGeoContext(), m_geometry, momentum, Acts::UnitConstants::ns, and Acts::ParticleHypothesis::pion().
Referenced by MakeMilleFiles::getLocalVtxDerivativesXY(), PHActsTrackPropagator::process_event(), PHActsTrackProjection::projectTracks(), and KshortReconstruction::projectTrackToPoint().
ActsPropagator::BoundTrackParamResult ActsPropagator::makeTrackParams (SvtxTrackState * state, int trackCharge, ActsPropagator::SurfacePtr surf)
Definition at line 36 of file ActsPropagator.cc.
View newest version in sPHENIX GitHub at line 36 of file ActsPropagator.cc
References Acts::UnitConstants::cm, Acts::Test::cov, Acts::GenericBoundTrackParameters< particle_hypothesis_t >::create(), ActsGeometry::geometry(), SvtxTrackState::get_px(), SvtxTrackState::get_py(), SvtxTrackState::get_pz(), SvtxTrackState::get_x(), SvtxTrackState::get_y(), SvtxTrackState::get_z(), ActsTrackingGeometry::getGeoContext(), m_geometry, momentum, Acts::UnitConstants::ns, and Acts::ParticleHypothesis::pion().
ActsPropagator::SurfacePtr ActsPropagator::makeVertexSurface (const SvtxVertex * vertex)
Helper functions for creating needed input for track propagation functions below
Definition at line 22 of file ActsPropagator.cc.
View newest version in sPHENIX GitHub at line 22 of file ActsPropagator.cc
References Acts::UnitConstants::cm, SvtxVertex::get_x(), SvtxVertex::get_y(), and SvtxVertex::get_z().
Referenced by MakeMilleFiles::getLocalVtxDerivativesXY(), and KshortReconstruction::projectTrackToPoint().
ActsPropagator::SurfacePtr ActsPropagator::makeVertexSurface (const Acts::Vector3 & vertex)
Definition at line 30 of file ActsPropagator.cc.
View newest version in sPHENIX GitHub at line 30 of file ActsPropagator.cc
References Acts::UnitConstants::cm.
void ActsPropagator::printTrackParams (const Acts::BoundTrackParameters & params) private
Definition at line 322 of file ActsPropagator.cc.
View newest version in sPHENIX GitHub at line 322 of file ActsPropagator.cc
References ActsGeometry::geometry(), ActsTrackingGeometry::getGeoContext(), m_geometry, Acts::GenericBoundTrackParameters< particle_hypothesis_t >::momentum(), and Acts::GenericBoundTrackParameters< particle_hypothesis_t >::position().
Referenced by propagateTrack(), and propagateTrackFast().
ActsPropagator::BTPPairResult ActsPropagator::propagateTrack (const Acts::BoundTrackParameters & params, const unsigned int sphenixLayer)
The return type is an Acts::Result of a std::pair, where the pair is a path length and the track parameters at the surface in units of mm and GeV. For an example of how to unpack this, see PHActsTrackProjection::propagateTrack and PHActsTrackProjection::updateSvtxTrack
Definition at line 99 of file ActsPropagator.cc.
View newest version in sPHENIX GitHub at line 99 of file ActsPropagator.cc
References checkLayer(), ActsGeometry::geometry(), ActsTrackingGeometry::getGeoContext(), m_geometry, m_verbosity, ActsTrackingGeometry::magFieldContext, makePropagator(), ckf::options, and printTrackParams().
Referenced by PHTpcResiduals::processTrack(), KshortReconstruction::projectTrackToPoint(), and PHActsTrackPropagator::propagateTrack().
ActsPropagator::BTPPairResult ActsPropagator::propagateTrack (const Acts::BoundTrackParameters & params, const SurfacePtr & surface)
Definition at line 140 of file ActsPropagator.cc.
View newest version in sPHENIX GitHub at line 140 of file ActsPropagator.cc
References ActsGeometry::geometry(), ActsTrackingGeometry::getGeoContext(), m_geometry, m_verbosity, ActsTrackingGeometry::magFieldContext, makePropagator(), ckf::options, and printTrackParams().
ActsPropagator::BTPPairResult ActsPropagator::propagateTrackFast (const Acts::BoundTrackParameters & params, const SurfacePtr & surface)
The following function takes the track parameters at the vertex and propagates them in isolation to the requested surface, i.e. it does NOT stop at each layer in the sPHENIX detector on the way to the target surface
Definition at line 169 of file ActsPropagator.cc.
View newest version in sPHENIX GitHub at line 169 of file ActsPropagator.cc
References ActsGeometry::geometry(), ActsTrackingGeometry::getGeoContext(), m_geometry, m_verbosity, ActsTrackingGeometry::magFieldContext, makeFastPropagator(), ckf::options, and printTrackParams().
Referenced by PHActsTrackProjection::propagateTrack().
void ActsPropagator::setConstFieldValue (float field) inline
Definition at line 80 of file ActsPropagator.h.
View newest version in sPHENIX GitHub at line 80 of file ActsPropagator.h
References ckf::field, and m_fieldval.
Referenced by ActsAlignmentStates::fillAlignmentStateMap(), and PHActsTrackProjection::propagateTrack().
void ActsPropagator::setOverstepLimit (const double overstep) inline
Definition at line 82 of file ActsPropagator.h.
View newest version in sPHENIX GitHub at line 82 of file ActsPropagator.h
References m_overstepLimit.
void ActsPropagator::verbosity (int verb) inline
Definition at line 79 of file ActsPropagator.h.
View newest version in sPHENIX GitHub at line 79 of file ActsPropagator.h
References m_verbosity.
Referenced by PHActsTrackPropagator::propagateTrack(), and PHActsTrackProjection::propagateTrack().
Member Data Documentation
bool ActsPropagator::m_constField = false private
Definition at line 91 of file ActsPropagator.h.
View newest version in sPHENIX GitHub at line 91 of file ActsPropagator.h
Referenced by constField(), makeFastPropagator(), and makePropagator().
float ActsPropagator::m_fieldval = 1.4 * Acts::UnitConstants::T private
Definition at line 95 of file ActsPropagator.h.
View newest version in sPHENIX GitHub at line 95 of file ActsPropagator.h
Referenced by makeFastPropagator(), makePropagator(), and setConstFieldValue().
ActsGeometry* ActsPropagator::m_geometry = nullptr private
Definition at line 93 of file ActsPropagator.h.
View newest version in sPHENIX GitHub at line 93 of file ActsPropagator.h
Referenced by checkLayer(), makeFastPropagator(), makePropagator(), makeTrackParams(), printTrackParams(), propagateTrack(), and propagateTrackFast().
float ActsPropagator::m_overstepLimit = 0.01 * Acts::UnitConstants::cm private
Default Acts limit.
Definition at line 98 of file ActsPropagator.h.
View newest version in sPHENIX GitHub at line 98 of file ActsPropagator.h
Referenced by makePropagator(), and setOverstepLimit().
int ActsPropagator::m_verbosity = 0 private
Definition at line 89 of file ActsPropagator.h.
View newest version in sPHENIX GitHub at line 89 of file ActsPropagator.h
Referenced by makeFastPropagator(), makePropagator(), propagateTrack(), propagateTrackFast(), and verbosity().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/trackreco/ActsPropagator.h
coresoftware/blob/master/offline/packages/trackreco/ActsPropagator.cc