Analysis Software: Acts::Legacy::AtlasSeedFinder< SpacePoint > Class Template Reference
Acts::Legacy::AtlasSeedFinder< SpacePoint > Class Template Reference
#include <acts/blob/sPHENIX/Plugins/Legacy/include/Acts/Seeding/AtlasSeedFinder.hpp>
Classes
struct Config
Public Member Functions
AtlasSeedFinder ()
virtual ~AtlasSeedFinder ()
template<class RandIter >
void newEvent (int, RandIter, RandIter)
void find3Sp ()
const Seed< SpacePoint > * next ()
Public Attributes
const Config m_config
Protected Member Functions
void buildFrameWork ()
void buildBeamFrameWork ()
SPForSeed< SpacePoint > * newSpacePoint (SpacePoint *const &)
void newOneSeed (SPForSeed< SpacePoint > *&, SPForSeed< SpacePoint > *&, SPForSeed< SpacePoint > *&, float, float)
void newOneSeedWithCurvaturesComparison (SPForSeed< SpacePoint > *&, SPForSeed< SpacePoint > *&, float)
void fillSeeds ()
void fillLists ()
void erase ()
void production3Sp ()
void production3Sp (typename std::list< SPForSeed< SpacePoint > * >::iterator *, typename std::list< SPForSeed< SpacePoint > * >::iterator *, typename std::list< SPForSeed< SpacePoint > * >::iterator *, typename std::list< SPForSeed< SpacePoint > * >::iterator *, int, int, int &)
void findNext ()
bool isZCompatible (float &)
void convertToBeamFrameWork (SpacePoint *const &, float *)
Disallow default instantiation, copy, assignment
AtlasSeedFinder (const AtlasSeedFinder< SpacePoint > &)=delete
AtlasSeedFinder< SpacePoint > & operator= (const AtlasSeedFinder< SpacePoint > &)=delete
Protected Attributes
bool m_endlist = false
bool m_checketa = false
bool m_isvertex = false
int m_nprint = 0
int m_nlist = 0
int m_maxsize = 0
int m_state = 0
int m_iteration = 0
float m_etamin = 0
float m_etamax = 0
float m_drmin = 0
float m_drminv = 0
float m_drmax = 0
float m_dzdrmin0 = 0
float m_dzdrmax0 = 0
float m_dzdrmin = 0
float m_dzdrmax = 0
float m_zmin = 0
float m_zmax = 0
float m_zminU = 0
float m_zmaxU = 0
float m_zminB = 0
float m_zmaxB = 0
float m_ftrig = 0
float m_ftrigW = 0
float r_rmax = 0
float r_rstep = 0
float m_dzver = 0
float m_dzdrver = 0
float m_diver = 0
float m_diverpps = 0
float m_diversss = 0
float m_divermax = 0
float m_dazmax = 0
float m_ptmin = 0
float m_ipt = 0
float m_ipt2 = 0
float m_COF = 0
float m_K = 0
float m_ipt2K = 0
float m_ipt2C = 0
float m_COFK = 0
float m_umax = 0
int r_size = 0
int r_first = 0
int rf_size = 0
int rfz_size = 0
std::list< SPForSeed
< SpacePoint > * > * r_Sorted = nullptr
std::list< SPForSeed
< SpacePoint > * > rfz_Sorted [583]
std::list< SPForSeed
< SpacePoint > * > l_spforseed
std::list< SPForSeed
< SpacePoint > * >::iterator i_spforseed
std::list< SPForSeed
< SpacePoint > * >::iterator m_rMin
int m_nsaz = 0
int m_nsazv = 0
int m_fNmax = 0
int m_fvNmax = 0
int m_fNmin = 0
int m_fvNmin = 0
int m_zMin = 0
int m_nr = 0
int * r_index = nullptr
int * r_map = nullptr
int m_nrfz = 0
int rfz_index [583] = {}
int rfz_map [583] = {}
int rfz_b [583] = {}
int rfz_t [593] = {}
int rfz_ib [583][9] = {}
int rfz_it [583][9] = {}
float m_sF = 0
int m_maxsizeSP = 0
SPForSeed< SpacePoint > ** m_SP = nullptr
float * m_Zo = nullptr
float * m_Tz = nullptr
float * m_R = nullptr
float * m_U = nullptr
float * m_V = nullptr
float * m_Er = nullptr
Seed< SpacePoint > * m_seedOutput = nullptr
std::list< InternalSeed
< SpacePoint > * > l_seeds
std::list< InternalSeed
< SpacePoint > * >::iterator i_seed
std::list< InternalSeed
< SpacePoint > * >::iterator i_seede
std::multimap< float,
InternalSeed< SpacePoint > * > m_seeds
std::multimap< float,
InternalSeed< SpacePoint >
* >::iterator m_seed
std::multimap< float,
InternalSeed< SpacePoint > * > m_mapOneSeeds
InternalSeed< SpacePoint > * m_OneSeeds = nullptr
int m_maxOneSize = 0
int m_nOneSeeds = 0
int m_fillOneSeeds = 0
std::vector< std::pair< float,
SPForSeed< SpacePoint > * > > m_CmSp
float m_xbeam = 0
float m_ybeam = 0
float m_zbeam = 0
Detailed Description
template<typename SpacePoint>
class Acts::Legacy::AtlasSeedFinder< SpacePoint >
Definition at line 27 of file AtlasSeedFinder.hpp.
View newest version in sPHENIX GitHub at line 27 of file AtlasSeedFinder.hpp
Constructor & Destructor Documentation
template<typename SpacePoint > Acts::Legacy::AtlasSeedFinder< SpacePoint >::AtlasSeedFinder ()
Definition at line 20 of file AtlasSeedFinder.ipp.
View newest version in sPHENIX GitHub at line 20 of file AtlasSeedFinder.ipp
template<typename SpacePoint> virtual Acts::Legacy::AtlasSeedFinder< SpacePoint >::~AtlasSeedFinder () inline virtual
Definition at line 53 of file AtlasSeedFinder.hpp.
View newest version in sPHENIX GitHub at line 53 of file AtlasSeedFinder.hpp
References Acts::Legacy::AtlasSeedFinder< SpacePoint >::i_seed, Acts::Legacy::AtlasSeedFinder< SpacePoint >::i_spforseed, Acts::Legacy::AtlasSeedFinder< SpacePoint >::l_seeds, Acts::Legacy::AtlasSeedFinder< SpacePoint >::l_spforseed, Acts::Legacy::AtlasSeedFinder< SpacePoint >::m_Er, Acts::Legacy::AtlasSeedFinder< SpacePoint >::m_OneSeeds, Acts::Legacy::AtlasSeedFinder< SpacePoint >::m_R, Acts::Legacy::AtlasSeedFinder< SpacePoint >::m_seedOutput, Acts::Legacy::AtlasSeedFinder< SpacePoint >::m_SP, Acts::Legacy::AtlasSeedFinder< SpacePoint >::m_Tz, Acts::Legacy::AtlasSeedFinder< SpacePoint >::m_U, Acts::Legacy::AtlasSeedFinder< SpacePoint >::m_V, Acts::Legacy::AtlasSeedFinder< SpacePoint >::m_Zo, Acts::Legacy::AtlasSeedFinder< SpacePoint >::r_index, Acts::Legacy::AtlasSeedFinder< SpacePoint >::r_map, and Acts::Legacy::AtlasSeedFinder< SpacePoint >::r_Sorted.
template<typename SpacePoint> Acts::Legacy::AtlasSeedFinder< SpacePoint >::AtlasSeedFinder (const AtlasSeedFinder< SpacePoint > &) protected delete
Member Function Documentation
template<class SpacePoint > void Acts::Legacy::AtlasSeedFinder< SpacePoint >::buildBeamFrameWork () protected
Definition at line 390 of file AtlasSeedFinder.ipp.
View newest version in sPHENIX GitHub at line 390 of file AtlasSeedFinder.ipp
template<class SpacePoint > void Acts::Legacy::AtlasSeedFinder< SpacePoint >::buildFrameWork () protected
Definition at line 207 of file AtlasSeedFinder.ipp.
View newest version in sPHENIX GitHub at line 207 of file AtlasSeedFinder.ipp
References KFPMath::a, KFPMath::b, Acts::PhysicalConstants::c, f, i, and physmon_track_finding_ttbar::z.
template<class SpacePoint > void Acts::Legacy::AtlasSeedFinder< SpacePoint >::convertToBeamFrameWork (SpacePoint *const & sp, float * r) protected
Definition at line 404 of file AtlasSeedFinder.ipp.
View newest version in sPHENIX GitHub at line 404 of file AtlasSeedFinder.ipp
References SpacePoint::x, SpacePoint::y, and SpacePoint::z.
template<class SpacePoint > void Acts::Legacy::AtlasSeedFinder< SpacePoint >::erase () protected
Definition at line 507 of file AtlasSeedFinder.ipp.
View newest version in sPHENIX GitHub at line 507 of file AtlasSeedFinder.ipp
References i, and n.
template<class SpacePoint > void Acts::Legacy::AtlasSeedFinder< SpacePoint >::fillLists () protected
Definition at line 415 of file AtlasSeedFinder.ipp.
View newest version in sPHENIX GitHub at line 415 of file AtlasSeedFinder.ipp
References f, F, i, n, physmon_track_finding_ttbar::r, SVM_v1::Z, and physmon_track_finding_ttbar::z.
template<class SpacePoint > void Acts::Legacy::AtlasSeedFinder< SpacePoint >::fillSeeds () protected
Definition at line 983 of file AtlasSeedFinder.ipp.
View newest version in sPHENIX GitHub at line 983 of file AtlasSeedFinder.ipp
References physmon_simulation::s, Acts::Legacy::InternalSeed< SpacePoint >::setQuality(), Acts::Legacy::InternalSeed< SpacePoint >::spacepoint0(), Acts::Legacy::InternalSeed< SpacePoint >::spacepoint1(), and Acts::Legacy::InternalSeed< SpacePoint >::spacepoint2().
template<class SpacePoint > void Acts::Legacy::AtlasSeedFinder< SpacePoint >::find3Sp ()
Definition at line 167 of file AtlasSeedFinder.ipp.
View newest version in sPHENIX GitHub at line 167 of file AtlasSeedFinder.ipp
Referenced by runSeeding().
template<class SpacePoint > void Acts::Legacy::AtlasSeedFinder< SpacePoint >::findNext () protected
Definition at line 189 of file AtlasSeedFinder.ipp.
View newest version in sPHENIX GitHub at line 189 of file AtlasSeedFinder.ipp
template<typename SpacePoint > bool Acts::Legacy::AtlasSeedFinder< SpacePoint >::isZCompatible (float & Zv) inline protected
Definition at line 300 of file AtlasSeedFinder.hpp.
View newest version in sPHENIX GitHub at line 300 of file AtlasSeedFinder.hpp
template<typename SpacePoint > template<class RandIter > void Acts::Legacy::AtlasSeedFinder< SpacePoint >::newEvent (int iteration, RandIter spBegin, RandIter spEnd)
Definition at line 96 of file AtlasSeedFinder.ipp.
View newest version in sPHENIX GitHub at line 96 of file AtlasSeedFinder.ipp
References i, n, and Acts::Legacy::SPForSeed< SpacePoint >::radius().
Referenced by runSeeding().
template<class SpacePoint > void Acts::Legacy::AtlasSeedFinder< SpacePoint >::newOneSeed (SPForSeed< SpacePoint > *& p1, SPForSeed< SpacePoint > *& p2, SPForSeed< SpacePoint > *& p3, float z, float q) protected
Definition at line 828 of file AtlasSeedFinder.ipp.
View newest version in sPHENIX GitHub at line 828 of file AtlasSeedFinder.ipp
References i, physmon_simulation::s, and Acts::Legacy::InternalSeed< SpacePoint >::set().
template<class SpacePoint > void Acts::Legacy::AtlasSeedFinder< SpacePoint >::newOneSeedWithCurvaturesComparison (SPForSeed< SpacePoint > *& SPb, SPForSeed< SpacePoint > *& SP0, float Zob) protected
Definition at line 876 of file AtlasSeedFinder.ipp.
View newest version in sPHENIX GitHub at line 876 of file AtlasSeedFinder.ipp
References SpacePoint::clusterList(), i, in, j, jn, Acts::Legacy::SPForSeed< SpacePoint >::quality(), Acts::Experimental::detail::BlueprintHelper::sort(), Acts::Legacy::SPForSeed< SpacePoint >::spacepoint, and physmon_ckf_tracking::u.
template<typename SpacePoint > SPForSeed< SpacePoint > * Acts::Legacy::AtlasSeedFinder< SpacePoint >::newSpacePoint (SpacePoint *const & sp) inline protected
Definition at line 313 of file AtlasSeedFinder.hpp.
View newest version in sPHENIX GitHub at line 313 of file AtlasSeedFinder.hpp
References physmon_track_finding_ttbar::r, Acts::Legacy::SPForSeed< SpacePoint >::set(), ambiguity_solver_full_chain::x, y, and physmon_track_finding_ttbar::z.
template<typename SpacePoint > const Seed< SpacePoint > * Acts::Legacy::AtlasSeedFinder< SpacePoint >::next () inline
Definition at line 286 of file AtlasSeedFinder.hpp.
View newest version in sPHENIX GitHub at line 286 of file AtlasSeedFinder.hpp
Referenced by runSeeding().
template<typename SpacePoint> AtlasSeedFinder<SpacePoint>& Acts::Legacy::AtlasSeedFinder< SpacePoint >::operator= (const AtlasSeedFinder< SpacePoint > &) protected delete
template<class SpacePoint > void Acts::Legacy::AtlasSeedFinder< SpacePoint >::production3Sp () protected
Definition at line 524 of file AtlasSeedFinder.ipp.
View newest version in sPHENIX GitHub at line 524 of file AtlasSeedFinder.ipp
References KFPMath::a, f, i, Acts::Test::rb, and physmon_track_finding_ttbar::z.
template<class SpacePoint > void Acts::Legacy::AtlasSeedFinder< SpacePoint >::production3Sp (typename std::list< SPForSeed< SpacePoint > * >::iterator * rb, typename std::list< SPForSeed< SpacePoint > * >::iterator * rbe, typename std::list< SPForSeed< SpacePoint > * >::iterator * rt, typename std::list< SPForSeed< SpacePoint > * >::iterator * rte, int NB, int NT, int & nseed) protected
Definition at line 588 of file AtlasSeedFinder.ipp.
View newest version in sPHENIX GitHub at line 588 of file AtlasSeedFinder.ipp
References A, CKF_timing_vs_mu::ax, KFPMath::b, Acts::Legacy::SPForSeed< SpacePoint >::covr(), Acts::Legacy::SPForSeed< SpacePoint >::covz(), dR(), dy, dz, i, Acts::IntegrationTest::R, physmon_track_finding_ttbar::r, r0, r2, t, Acts::Legacy::SPForSeed< SpacePoint >::x(), TauVsDIS_MachineLearning_Differentiation::X, ambiguity_solver_full_chain::x, y, Acts::Legacy::SPForSeed< SpacePoint >::y(), TauVsDIS_MachineLearning_Differentiation::Y, Acts::Legacy::SPForSeed< SpacePoint >::z(), and SVM_v1::Z.
Member Data Documentation
template<typename SpacePoint> std::list<InternalSeed<SpacePoint>*>::iterator Acts::Legacy::AtlasSeedFinder< SpacePoint >::i_seed protected
Definition at line 227 of file AtlasSeedFinder.hpp.
View newest version in sPHENIX GitHub at line 227 of file AtlasSeedFinder.hpp
Referenced by Acts::Legacy::AtlasSeedFinder< SpacePoint >::~AtlasSeedFinder().
template<typename SpacePoint> std::list<InternalSeed<SpacePoint>*>::iterator Acts::Legacy::AtlasSeedFinder< SpacePoint >::i_seede protected
Definition at line 228 of file AtlasSeedFinder.hpp.
View newest version in sPHENIX GitHub at line 228 of file AtlasSeedFinder.hpp
template<typename SpacePoint> std::list<SPForSeed<SpacePoint>*>::iterator Acts::Legacy::AtlasSeedFinder< SpacePoint >::i_spforseed protected
Definition at line 194 of file AtlasSeedFinder.hpp.
View newest version in sPHENIX GitHub at line 194 of file AtlasSeedFinder.hpp
Referenced by Acts::Legacy::AtlasSeedFinder< SpacePoint >::~AtlasSeedFinder().
template<typename SpacePoint> std::list<InternalSeed<SpacePoint>*> Acts::Legacy::AtlasSeedFinder< SpacePoint >::l_seeds protected
Definition at line 226 of file AtlasSeedFinder.hpp.
View newest version in sPHENIX GitHub at line 226 of file AtlasSeedFinder.hpp
Referenced by Acts::Legacy::AtlasSeedFinder< SpacePoint >::~AtlasSeedFinder().
template<typename SpacePoint> std::list<SPForSeed<SpacePoint>*> Acts::Legacy::AtlasSeedFinder< SpacePoint >::l_spforseed protected
Definition at line 193 of file AtlasSeedFinder.hpp.
View newest version in sPHENIX GitHub at line 193 of file AtlasSeedFinder.hpp
Referenced by Acts::Legacy::AtlasSeedFinder< SpacePoint >::~AtlasSeedFinder().
template<typename SpacePoint> bool Acts::Legacy::AtlasSeedFinder< SpacePoint >::m_checketa = false protected
Definition at line 142 of file AtlasSeedFinder.hpp.
View newest version in sPHENIX GitHub at line 142 of file AtlasSeedFinder.hpp
template<typename SpacePoint> std::vector<std::pair<float, SPForSeed<SpacePoint>*> > Acts::Legacy::AtlasSeedFinder< SpacePoint >::m_CmSp protected
Definition at line 238 of file AtlasSeedFinder.hpp.
View newest version in sPHENIX GitHub at line 238 of file AtlasSeedFinder.hpp
template<typename SpacePoint> float Acts::Legacy::AtlasSeedFinder< SpacePoint >::m_COF = 0 protected
Definition at line 180 of file AtlasSeedFinder.hpp.
View newest version in sPHENIX GitHub at line 180 of file AtlasSeedFinder.hpp
template<typename SpacePoint> float Acts::Legacy::AtlasSeedFinder< SpacePoint >::m_COFK = 0 protected
Definition at line 184 of file AtlasSeedFinder.hpp.
View newest version in sPHENIX GitHub at line 184 of file AtlasSeedFinder.hpp
template<typename SpacePoint> const Config Acts::Legacy::AtlasSeedFinder< SpacePoint >::m_config
Definition at line 128 of file AtlasSeedFinder.hpp.
View newest version in sPHENIX GitHub at line 128 of file AtlasSeedFinder.hpp
template<typename SpacePoint> float Acts::Legacy::AtlasSeedFinder< SpacePoint >::m_dazmax = 0 protected
Definition at line 176 of file AtlasSeedFinder.hpp.
View newest version in sPHENIX GitHub at line 176 of file AtlasSeedFinder.hpp
template<typename SpacePoint> float Acts::Legacy::AtlasSeedFinder< SpacePoint >::m_diver = 0 protected
Definition at line 172 of file AtlasSeedFinder.hpp.
View newest version in sPHENIX GitHub at line 172 of file AtlasSeedFinder.hpp
template<typename SpacePoint> float Acts::Legacy::AtlasSeedFinder< SpacePoint >::m_divermax = 0 protected
Definition at line 175 of file AtlasSeedFinder.hpp.
View newest version in sPHENIX GitHub at line 175 of file AtlasSeedFinder.hpp
template<typename SpacePoint> float Acts::Legacy::AtlasSeedFinder< SpacePoint >::m_diverpps = 0 protected
Definition at line 173 of file AtlasSeedFinder.hpp.
View newest version in sPHENIX GitHub at line 173 of file AtlasSeedFinder.hpp
template<typename SpacePoint> float Acts::Legacy::AtlasSeedFinder< SpacePoint >::m_diversss = 0 protected
Definition at line 174 of file AtlasSeedFinder.hpp.
View newest version in sPHENIX GitHub at line 174 of file AtlasSeedFinder.hpp
template<typename SpacePoint> float Acts::Legacy::AtlasSeedFinder< SpacePoint >::m_drmax = 0 protected
Definition at line 152 of file AtlasSeedFinder.hpp.
View newest version in sPHENIX GitHub at line 152 of file AtlasSeedFinder.hpp
template<typename SpacePoint> float Acts::Legacy::AtlasSeedFinder< SpacePoint >::m_drmin = 0 protected
Definition at line 151 of file AtlasSeedFinder.hpp.
View newest version in sPHENIX GitHub at line 151 of file AtlasSeedFinder.hpp
template<typename SpacePoint> float Acts::Legacy::AtlasSeedFinder< SpacePoint >::m_drminv = 0 protected
Definition at line 151 of file AtlasSeedFinder.hpp.
View newest version in sPHENIX GitHub at line 151 of file AtlasSeedFinder.hpp
template<typename SpacePoint> float Acts::Legacy::AtlasSeedFinder< SpacePoint >::m_dzdrmax = 0 protected
Definition at line 156 of file AtlasSeedFinder.hpp.
View newest version in sPHENIX GitHub at line 156 of file AtlasSeedFinder.hpp
template<typename SpacePoint> float Acts::Legacy::AtlasSeedFinder< SpacePoint >::m_dzdrmax0 = 0 protected
Definition at line 154 of file AtlasSeedFinder.hpp.
View newest version in sPHENIX GitHub at line 154 of file AtlasSeedFinder.hpp
template<typename SpacePoint> float Acts::Legacy::AtlasSeedFinder< SpacePoint >::m_dzdrmin = 0 protected
Definition at line 155 of file AtlasSeedFinder.hpp.
View newest version in sPHENIX GitHub at line 155 of file AtlasSeedFinder.hpp
template<typename SpacePoint> float Acts::Legacy::AtlasSeedFinder< SpacePoint >::m_dzdrmin0 = 0 protected
Definition at line 153 of file AtlasSeedFinder.hpp.
View newest version in sPHENIX GitHub at line 153 of file AtlasSeedFinder.hpp
template<typename SpacePoint> float Acts::Legacy::AtlasSeedFinder< SpacePoint >::m_dzdrver = 0 protected
Definition at line 171 of file AtlasSeedFinder.hpp.
View newest version in sPHENIX GitHub at line 171 of file AtlasSeedFinder.hpp
template<typename SpacePoint> float Acts::Legacy::AtlasSeedFinder< SpacePoint >::m_dzver = 0 protected
Definition at line 170 of file AtlasSeedFinder.hpp.
View newest version in sPHENIX GitHub at line 170 of file AtlasSeedFinder.hpp
template<typename SpacePoint> bool Acts::Legacy::AtlasSeedFinder< SpacePoint >::m_endlist = false protected
Definition at line 141 of file AtlasSeedFinder.hpp.
View newest version in sPHENIX GitHub at line 141 of file AtlasSeedFinder.hpp
template<typename SpacePoint> float* Acts::Legacy::AtlasSeedFinder< SpacePoint >::m_Er = nullptr protected
Definition at line 222 of file AtlasSeedFinder.hpp.
View newest version in sPHENIX GitHub at line 222 of file AtlasSeedFinder.hpp
Referenced by Acts::Legacy::AtlasSeedFinder< SpacePoint >::~AtlasSeedFinder().
template<typename SpacePoint> float Acts::Legacy::AtlasSeedFinder< SpacePoint >::m_etamax = 0 protected
Definition at line 150 of file AtlasSeedFinder.hpp.
View newest version in sPHENIX GitHub at line 150 of file AtlasSeedFinder.hpp
template<typename SpacePoint> float Acts::Legacy::AtlasSeedFinder< SpacePoint >::m_etamin = 0 protected
Definition at line 150 of file AtlasSeedFinder.hpp.
View newest version in sPHENIX GitHub at line 150 of file AtlasSeedFinder.hpp
template<typename SpacePoint> int Acts::Legacy::AtlasSeedFinder< SpacePoint >::m_fillOneSeeds = 0 protected
Definition at line 237 of file AtlasSeedFinder.hpp.
View newest version in sPHENIX GitHub at line 237 of file AtlasSeedFinder.hpp
template<typename SpacePoint> int Acts::Legacy::AtlasSeedFinder< SpacePoint >::m_fNmax = 0 protected
Definition at line 198 of file AtlasSeedFinder.hpp.
View newest version in sPHENIX GitHub at line 198 of file AtlasSeedFinder.hpp
template<typename SpacePoint> int Acts::Legacy::AtlasSeedFinder< SpacePoint >::m_fNmin = 0 protected
Definition at line 199 of file AtlasSeedFinder.hpp.
View newest version in sPHENIX GitHub at line 199 of file AtlasSeedFinder.hpp
template<typename SpacePoint> float Acts::Legacy::AtlasSeedFinder< SpacePoint >::m_ftrig = 0 protected
Definition at line 163 of file AtlasSeedFinder.hpp.
View newest version in sPHENIX GitHub at line 163 of file AtlasSeedFinder.hpp
template<typename SpacePoint> float Acts::Legacy::AtlasSeedFinder< SpacePoint >::m_ftrigW = 0 protected
Definition at line 164 of file AtlasSeedFinder.hpp.
View newest version in sPHENIX GitHub at line 164 of file AtlasSeedFinder.hpp
template<typename SpacePoint> int Acts::Legacy::AtlasSeedFinder< SpacePoint >::m_fvNmax = 0 protected
Definition at line 198 of file AtlasSeedFinder.hpp.
View newest version in sPHENIX GitHub at line 198 of file AtlasSeedFinder.hpp
template<typename SpacePoint> int Acts::Legacy::AtlasSeedFinder< SpacePoint >::m_fvNmin = 0 protected
Definition at line 199 of file AtlasSeedFinder.hpp.
View newest version in sPHENIX GitHub at line 199 of file AtlasSeedFinder.hpp
template<typename SpacePoint> float Acts::Legacy::AtlasSeedFinder< SpacePoint >::m_ipt = 0 protected
Definition at line 178 of file AtlasSeedFinder.hpp.
View newest version in sPHENIX GitHub at line 178 of file AtlasSeedFinder.hpp
template<typename SpacePoint> float Acts::Legacy::AtlasSeedFinder< SpacePoint >::m_ipt2 = 0 protected
Definition at line 179 of file AtlasSeedFinder.hpp.
View newest version in sPHENIX GitHub at line 179 of file AtlasSeedFinder.hpp
template<typename SpacePoint> float Acts::Legacy::AtlasSeedFinder< SpacePoint >::m_ipt2C = 0 protected
Definition at line 183 of file AtlasSeedFinder.hpp.
View newest version in sPHENIX GitHub at line 183 of file AtlasSeedFinder.hpp
template<typename SpacePoint> float Acts::Legacy::AtlasSeedFinder< SpacePoint >::m_ipt2K = 0 protected
Definition at line 182 of file AtlasSeedFinder.hpp.
View newest version in sPHENIX GitHub at line 182 of file AtlasSeedFinder.hpp
template<typename SpacePoint> bool Acts::Legacy::AtlasSeedFinder< SpacePoint >::m_isvertex = false protected
Definition at line 143 of file AtlasSeedFinder.hpp.
View newest version in sPHENIX GitHub at line 143 of file AtlasSeedFinder.hpp
template<typename SpacePoint> int Acts::Legacy::AtlasSeedFinder< SpacePoint >::m_iteration = 0 protected
Definition at line 149 of file AtlasSeedFinder.hpp.
View newest version in sPHENIX GitHub at line 149 of file AtlasSeedFinder.hpp
template<typename SpacePoint> float Acts::Legacy::AtlasSeedFinder< SpacePoint >::m_K = 0 protected
Definition at line 181 of file AtlasSeedFinder.hpp.
View newest version in sPHENIX GitHub at line 181 of file AtlasSeedFinder.hpp
template<typename SpacePoint> std::multimap<float, InternalSeed<SpacePoint>*> Acts::Legacy::AtlasSeedFinder< SpacePoint >::m_mapOneSeeds protected
Definition at line 233 of file AtlasSeedFinder.hpp.
View newest version in sPHENIX GitHub at line 233 of file AtlasSeedFinder.hpp
template<typename SpacePoint> int Acts::Legacy::AtlasSeedFinder< SpacePoint >::m_maxOneSize = 0 protected
Definition at line 235 of file AtlasSeedFinder.hpp.
View newest version in sPHENIX GitHub at line 235 of file AtlasSeedFinder.hpp
template<typename SpacePoint> int Acts::Legacy::AtlasSeedFinder< SpacePoint >::m_maxsize = 0 protected
Definition at line 146 of file AtlasSeedFinder.hpp.
View newest version in sPHENIX GitHub at line 146 of file AtlasSeedFinder.hpp
template<typename SpacePoint> int Acts::Legacy::AtlasSeedFinder< SpacePoint >::m_maxsizeSP = 0 protected
Definition at line 215 of file AtlasSeedFinder.hpp.
View newest version in sPHENIX GitHub at line 215 of file AtlasSeedFinder.hpp
template<typename SpacePoint> int Acts::Legacy::AtlasSeedFinder< SpacePoint >::m_nlist = 0 protected
Definition at line 145 of file AtlasSeedFinder.hpp.
View newest version in sPHENIX GitHub at line 145 of file AtlasSeedFinder.hpp
template<typename SpacePoint> int Acts::Legacy::AtlasSeedFinder< SpacePoint >::m_nOneSeeds = 0 protected
Definition at line 236 of file AtlasSeedFinder.hpp.
View newest version in sPHENIX GitHub at line 236 of file AtlasSeedFinder.hpp
template<typename SpacePoint> int Acts::Legacy::AtlasSeedFinder< SpacePoint >::m_nprint = 0 protected
Definition at line 144 of file AtlasSeedFinder.hpp.
View newest version in sPHENIX GitHub at line 144 of file AtlasSeedFinder.hpp
template<typename SpacePoint> int Acts::Legacy::AtlasSeedFinder< SpacePoint >::m_nr = 0 protected
Definition at line 203 of file AtlasSeedFinder.hpp.
View newest version in sPHENIX GitHub at line 203 of file AtlasSeedFinder.hpp
template<typename SpacePoint> int Acts::Legacy::AtlasSeedFinder< SpacePoint >::m_nrfz = 0 protected
Definition at line 206 of file AtlasSeedFinder.hpp.
View newest version in sPHENIX GitHub at line 206 of file AtlasSeedFinder.hpp
template<typename SpacePoint> int Acts::Legacy::AtlasSeedFinder< SpacePoint >::m_nsaz = 0 protected
Definition at line 197 of file AtlasSeedFinder.hpp.
View newest version in sPHENIX GitHub at line 197 of file AtlasSeedFinder.hpp
template<typename SpacePoint> int Acts::Legacy::AtlasSeedFinder< SpacePoint >::m_nsazv = 0 protected
Definition at line 197 of file AtlasSeedFinder.hpp.
View newest version in sPHENIX GitHub at line 197 of file AtlasSeedFinder.hpp
template<typename SpacePoint> InternalSeed<SpacePoint>* Acts::Legacy::AtlasSeedFinder< SpacePoint >::m_OneSeeds = nullptr protected
Definition at line 234 of file AtlasSeedFinder.hpp.
View newest version in sPHENIX GitHub at line 234 of file AtlasSeedFinder.hpp
Referenced by Acts::Legacy::AtlasSeedFinder< SpacePoint >::~AtlasSeedFinder().
template<typename SpacePoint> float Acts::Legacy::AtlasSeedFinder< SpacePoint >::m_ptmin = 0 protected
Definition at line 177 of file AtlasSeedFinder.hpp.
View newest version in sPHENIX GitHub at line 177 of file AtlasSeedFinder.hpp
template<typename SpacePoint> float* Acts::Legacy::AtlasSeedFinder< SpacePoint >::m_R = nullptr protected
Definition at line 219 of file AtlasSeedFinder.hpp.
View newest version in sPHENIX GitHub at line 219 of file AtlasSeedFinder.hpp
Referenced by Acts::Legacy::AtlasSeedFinder< SpacePoint >::~AtlasSeedFinder().
template<typename SpacePoint> std::list<SPForSeed<SpacePoint>*>::iterator Acts::Legacy::AtlasSeedFinder< SpacePoint >::m_rMin protected
Definition at line 195 of file AtlasSeedFinder.hpp.
View newest version in sPHENIX GitHub at line 195 of file AtlasSeedFinder.hpp
template<typename SpacePoint> std::multimap<float, InternalSeed<SpacePoint>*>::iterator Acts::Legacy::AtlasSeedFinder< SpacePoint >::m_seed protected
Definition at line 231 of file AtlasSeedFinder.hpp.
View newest version in sPHENIX GitHub at line 231 of file AtlasSeedFinder.hpp
template<typename SpacePoint> Seed<SpacePoint>* Acts::Legacy::AtlasSeedFinder< SpacePoint >::m_seedOutput = nullptr protected
Definition at line 224 of file AtlasSeedFinder.hpp.
View newest version in sPHENIX GitHub at line 224 of file AtlasSeedFinder.hpp
Referenced by Acts::Legacy::AtlasSeedFinder< SpacePoint >::~AtlasSeedFinder().
template<typename SpacePoint> std::multimap<float, InternalSeed<SpacePoint>*> Acts::Legacy::AtlasSeedFinder< SpacePoint >::m_seeds protected
Definition at line 230 of file AtlasSeedFinder.hpp.
View newest version in sPHENIX GitHub at line 230 of file AtlasSeedFinder.hpp
template<typename SpacePoint> float Acts::Legacy::AtlasSeedFinder< SpacePoint >::m_sF = 0 protected
Definition at line 209 of file AtlasSeedFinder.hpp.
View newest version in sPHENIX GitHub at line 209 of file AtlasSeedFinder.hpp
template<typename SpacePoint> SPForSeed<SpacePoint>** Acts::Legacy::AtlasSeedFinder< SpacePoint >::m_SP = nullptr protected
Definition at line 216 of file AtlasSeedFinder.hpp.
View newest version in sPHENIX GitHub at line 216 of file AtlasSeedFinder.hpp
Referenced by Acts::Legacy::AtlasSeedFinder< SpacePoint >::~AtlasSeedFinder().
template<typename SpacePoint> int Acts::Legacy::AtlasSeedFinder< SpacePoint >::m_state = 0 protected
Definition at line 147 of file AtlasSeedFinder.hpp.
View newest version in sPHENIX GitHub at line 147 of file AtlasSeedFinder.hpp
template<typename SpacePoint> float* Acts::Legacy::AtlasSeedFinder< SpacePoint >::m_Tz = nullptr protected
Definition at line 218 of file AtlasSeedFinder.hpp.
View newest version in sPHENIX GitHub at line 218 of file AtlasSeedFinder.hpp
Referenced by Acts::Legacy::AtlasSeedFinder< SpacePoint >::~AtlasSeedFinder().
template<typename SpacePoint> float* Acts::Legacy::AtlasSeedFinder< SpacePoint >::m_U = nullptr protected
Definition at line 220 of file AtlasSeedFinder.hpp.
View newest version in sPHENIX GitHub at line 220 of file AtlasSeedFinder.hpp
Referenced by Acts::Legacy::AtlasSeedFinder< SpacePoint >::~AtlasSeedFinder().
template<typename SpacePoint> float Acts::Legacy::AtlasSeedFinder< SpacePoint >::m_umax = 0 protected
Definition at line 185 of file AtlasSeedFinder.hpp.
View newest version in sPHENIX GitHub at line 185 of file AtlasSeedFinder.hpp
template<typename SpacePoint> float* Acts::Legacy::AtlasSeedFinder< SpacePoint >::m_V = nullptr protected
Definition at line 221 of file AtlasSeedFinder.hpp.
View newest version in sPHENIX GitHub at line 221 of file AtlasSeedFinder.hpp
Referenced by Acts::Legacy::AtlasSeedFinder< SpacePoint >::~AtlasSeedFinder().
template<typename SpacePoint> float Acts::Legacy::AtlasSeedFinder< SpacePoint >::m_xbeam = 0 protected
Definition at line 244 of file AtlasSeedFinder.hpp.
View newest version in sPHENIX GitHub at line 244 of file AtlasSeedFinder.hpp
template<typename SpacePoint> float Acts::Legacy::AtlasSeedFinder< SpacePoint >::m_ybeam = 0 protected
Definition at line 245 of file AtlasSeedFinder.hpp.
View newest version in sPHENIX GitHub at line 245 of file AtlasSeedFinder.hpp
template<typename SpacePoint> float Acts::Legacy::AtlasSeedFinder< SpacePoint >::m_zbeam = 0 protected
Definition at line 246 of file AtlasSeedFinder.hpp.
View newest version in sPHENIX GitHub at line 246 of file AtlasSeedFinder.hpp
template<typename SpacePoint> float Acts::Legacy::AtlasSeedFinder< SpacePoint >::m_zmax = 0 protected
Definition at line 158 of file AtlasSeedFinder.hpp.
View newest version in sPHENIX GitHub at line 158 of file AtlasSeedFinder.hpp
template<typename SpacePoint> float Acts::Legacy::AtlasSeedFinder< SpacePoint >::m_zmaxB = 0 protected
Definition at line 162 of file AtlasSeedFinder.hpp.
View newest version in sPHENIX GitHub at line 162 of file AtlasSeedFinder.hpp
template<typename SpacePoint> float Acts::Legacy::AtlasSeedFinder< SpacePoint >::m_zmaxU = 0 protected
Definition at line 160 of file AtlasSeedFinder.hpp.
View newest version in sPHENIX GitHub at line 160 of file AtlasSeedFinder.hpp
template<typename SpacePoint> float Acts::Legacy::AtlasSeedFinder< SpacePoint >::m_zmin = 0 protected
Definition at line 157 of file AtlasSeedFinder.hpp.
View newest version in sPHENIX GitHub at line 157 of file AtlasSeedFinder.hpp
template<typename SpacePoint> int Acts::Legacy::AtlasSeedFinder< SpacePoint >::m_zMin = 0 protected
Definition at line 200 of file AtlasSeedFinder.hpp.
View newest version in sPHENIX GitHub at line 200 of file AtlasSeedFinder.hpp
template<typename SpacePoint> float Acts::Legacy::AtlasSeedFinder< SpacePoint >::m_zminB = 0 protected
Definition at line 161 of file AtlasSeedFinder.hpp.
View newest version in sPHENIX GitHub at line 161 of file AtlasSeedFinder.hpp
template<typename SpacePoint> float Acts::Legacy::AtlasSeedFinder< SpacePoint >::m_zminU = 0 protected
Definition at line 159 of file AtlasSeedFinder.hpp.
View newest version in sPHENIX GitHub at line 159 of file AtlasSeedFinder.hpp
template<typename SpacePoint> float* Acts::Legacy::AtlasSeedFinder< SpacePoint >::m_Zo = nullptr protected
Definition at line 217 of file AtlasSeedFinder.hpp.
View newest version in sPHENIX GitHub at line 217 of file AtlasSeedFinder.hpp
Referenced by Acts::Legacy::AtlasSeedFinder< SpacePoint >::~AtlasSeedFinder().
template<typename SpacePoint> int Acts::Legacy::AtlasSeedFinder< SpacePoint >::r_first = 0 protected
Definition at line 188 of file AtlasSeedFinder.hpp.
View newest version in sPHENIX GitHub at line 188 of file AtlasSeedFinder.hpp
template<typename SpacePoint> int* Acts::Legacy::AtlasSeedFinder< SpacePoint >::r_index = nullptr protected
Definition at line 204 of file AtlasSeedFinder.hpp.
View newest version in sPHENIX GitHub at line 204 of file AtlasSeedFinder.hpp
Referenced by Acts::Legacy::AtlasSeedFinder< SpacePoint >::~AtlasSeedFinder().
template<typename SpacePoint> int* Acts::Legacy::AtlasSeedFinder< SpacePoint >::r_map = nullptr protected
Definition at line 205 of file AtlasSeedFinder.hpp.
View newest version in sPHENIX GitHub at line 205 of file AtlasSeedFinder.hpp
Referenced by Acts::Legacy::AtlasSeedFinder< SpacePoint >::~AtlasSeedFinder().
template<typename SpacePoint> float Acts::Legacy::AtlasSeedFinder< SpacePoint >::r_rmax = 0 protected
Definition at line 166 of file AtlasSeedFinder.hpp.
View newest version in sPHENIX GitHub at line 166 of file AtlasSeedFinder.hpp
template<typename SpacePoint> float Acts::Legacy::AtlasSeedFinder< SpacePoint >::r_rstep = 0 protected
Definition at line 168 of file AtlasSeedFinder.hpp.
View newest version in sPHENIX GitHub at line 168 of file AtlasSeedFinder.hpp
template<typename SpacePoint> int Acts::Legacy::AtlasSeedFinder< SpacePoint >::r_size = 0 protected
Definition at line 187 of file AtlasSeedFinder.hpp.
View newest version in sPHENIX GitHub at line 187 of file AtlasSeedFinder.hpp
template<typename SpacePoint> std::list<SPForSeed<SpacePoint>*>* Acts::Legacy::AtlasSeedFinder< SpacePoint >::r_Sorted = nullptr protected
Definition at line 191 of file AtlasSeedFinder.hpp.
View newest version in sPHENIX GitHub at line 191 of file AtlasSeedFinder.hpp
Referenced by Acts::Legacy::AtlasSeedFinder< SpacePoint >::~AtlasSeedFinder().
template<typename SpacePoint> int Acts::Legacy::AtlasSeedFinder< SpacePoint >::rf_size = 0 protected
Definition at line 189 of file AtlasSeedFinder.hpp.
View newest version in sPHENIX GitHub at line 189 of file AtlasSeedFinder.hpp
template<typename SpacePoint> int Acts::Legacy::AtlasSeedFinder< SpacePoint >::rfz_b[583] = {} protected
Definition at line 207 of file AtlasSeedFinder.hpp.
View newest version in sPHENIX GitHub at line 207 of file AtlasSeedFinder.hpp
template<typename SpacePoint> int Acts::Legacy::AtlasSeedFinder< SpacePoint >::rfz_ib[583][9] = {} protected
Definition at line 207 of file AtlasSeedFinder.hpp.
View newest version in sPHENIX GitHub at line 207 of file AtlasSeedFinder.hpp
template<typename SpacePoint> int Acts::Legacy::AtlasSeedFinder< SpacePoint >::rfz_index[583] = {} protected
Definition at line 206 of file AtlasSeedFinder.hpp.
View newest version in sPHENIX GitHub at line 206 of file AtlasSeedFinder.hpp
template<typename SpacePoint> int Acts::Legacy::AtlasSeedFinder< SpacePoint >::rfz_it[583][9] = {} protected
Definition at line 208 of file AtlasSeedFinder.hpp.
View newest version in sPHENIX GitHub at line 208 of file AtlasSeedFinder.hpp
template<typename SpacePoint> int Acts::Legacy::AtlasSeedFinder< SpacePoint >::rfz_map[583] = {} protected
Definition at line 206 of file AtlasSeedFinder.hpp.
View newest version in sPHENIX GitHub at line 206 of file AtlasSeedFinder.hpp
template<typename SpacePoint> int Acts::Legacy::AtlasSeedFinder< SpacePoint >::rfz_size = 0 protected
Definition at line 190 of file AtlasSeedFinder.hpp.
View newest version in sPHENIX GitHub at line 190 of file AtlasSeedFinder.hpp
template<typename SpacePoint> std::list<SPForSeed<SpacePoint>*> Acts::Legacy::AtlasSeedFinder< SpacePoint >::rfz_Sorted[583] protected
Definition at line 192 of file AtlasSeedFinder.hpp.
View newest version in sPHENIX GitHub at line 192 of file AtlasSeedFinder.hpp
template<typename SpacePoint> int Acts::Legacy::AtlasSeedFinder< SpacePoint >::rfz_t[593] = {} protected
Definition at line 207 of file AtlasSeedFinder.hpp.
View newest version in sPHENIX GitHub at line 207 of file AtlasSeedFinder.hpp
The documentation for this class was generated from the following files:
acts/blob/sPHENIX/Plugins/Legacy/include/Acts/Seeding/AtlasSeedFinder.hpp
acts/blob/sPHENIX/Plugins/Legacy/include/Acts/Seeding/AtlasSeedFinder.ipp