Analysis Software: Acts::FpeMonitor Class Reference
Acts::FpeMonitor Class Reference
#include <acts/blob/sPHENIX/Plugins/FpeMonitoring/include/Acts/Plugins/FpeMonitoring/FpeMonitor.hpp>
Classes
struct Buffer
struct GlobalState
struct Result
Public Member Functions
FpeMonitor ()
FpeMonitor (int excepts)
FpeMonitor (FpeMonitor &&other)=default
~FpeMonitor ()
Result & result ()
void consumeRecorded ()
void rearm ()
Static Public Member Functions
static std::string stackTraceToString (const boost::stacktrace::stacktrace &st, std::size_t depth)
static std::string getSourceLocation (const boost::stacktrace::frame &frame)
Private Member Functions
void enable ()
void disable ()
Static Private Member Functions
static void ensureSignalHandlerInstalled ()
static void signalHandler (int signal, siginfo_t *si, void *ctx)
static std::stack< FpeMonitor * > & stack ()
static GlobalState & globalState ()
Private Attributes
int m_excepts = 0
Result m_result
Buffer m_buffer {65536}
boost::container::static_vector
< std::tuple< FpeType, void
*, std::size_t >, 128 > m_recorded
Detailed Description
Definition at line 40 of file FpeMonitor.hpp.
View newest version in sPHENIX GitHub at line 40 of file FpeMonitor.hpp
Constructor & Destructor Documentation
Acts::FpeMonitor::FpeMonitor ()
Acts::FpeMonitor::FpeMonitor (int excepts) explicit
Acts::FpeMonitor::FpeMonitor (FpeMonitor && other) default
Acts::FpeMonitor::~FpeMonitor ()
Member Function Documentation
void Acts::FpeMonitor::consumeRecorded ()
void Acts::FpeMonitor::disable () private
void Acts::FpeMonitor::enable () private
static void Acts::FpeMonitor::ensureSignalHandlerInstalled () static private
static std::string Acts::FpeMonitor::getSourceLocation (const boost::stacktrace::frame & frame) static
Referenced by ActsExamples::Sequencer::fpeMaskCount().
static GlobalState& Acts::FpeMonitor::globalState () static private
void Acts::FpeMonitor::rearm ()
Referenced by Acts::Python::addFramework(), and Acts::Test::BOOST_AUTO_TEST_CASE().
Result& Acts::FpeMonitor::result ()
Referenced by Acts::Python::addFramework(), and Acts::Test::BOOST_AUTO_TEST_CASE().
static void Acts::FpeMonitor::signalHandler (int signal, siginfo_t * si, void * ctx) static private
static std::stack<FpeMonitor *>& Acts::FpeMonitor::stack () static private
static std::string Acts::FpeMonitor::stackTraceToString (const boost::stacktrace::stacktrace & st, std::size_t depth) static
Referenced by ActsExamples::Sequencer::fpeReport(), and ActsExamples::Sequencer::run().
Member Data Documentation
Buffer Acts::FpeMonitor::m_buffer {65536} private
Definition at line 153 of file FpeMonitor.hpp.
View newest version in sPHENIX GitHub at line 153 of file FpeMonitor.hpp
int Acts::FpeMonitor::m_excepts = 0 private
Definition at line 149 of file FpeMonitor.hpp.
View newest version in sPHENIX GitHub at line 149 of file FpeMonitor.hpp
boost::container::static_vector<std::tuple<FpeType, void *, std::size_t>, 128> Acts::FpeMonitor::m_recorded private
Definition at line 156 of file FpeMonitor.hpp.
View newest version in sPHENIX GitHub at line 156 of file FpeMonitor.hpp
Result Acts::FpeMonitor::m_result private
Definition at line 151 of file FpeMonitor.hpp.
View newest version in sPHENIX GitHub at line 151 of file FpeMonitor.hpp
The documentation for this class was generated from the following file:
acts/blob/sPHENIX/Plugins/FpeMonitoring/include/Acts/Plugins/FpeMonitoring/FpeMonitor.hpp