Analysis Software: Acts::OnnxMetricLearning Exception Reference
Acts::OnnxMetricLearning Exception Reference final
#include <acts/blob/sPHENIX/Plugins/ExaTrkX/include/Acts/Plugins/ExaTrkX/OnnxMetricLearning.hpp>
Classes
struct Config
Public Member Functions
OnnxMetricLearning (const Config &cfg, std::unique_ptr< const Logger > logger)
~OnnxMetricLearning ()
std::tuple< std::any, std::any > operator() (std::vector< float > &inputValues, std::size_t numNodes, int deviceHint=-1) override
Config config () const
Public Member Functions inherited from Acts::GraphConstructionBase
virtual ~GraphConstructionBase ()=default
Private Member Functions
void buildEdgesWrapper (std::vector< float > &embedFeatures, std::vector< int64_t > &edgeList, int64_t numSpacepoints, const Logger &logger) const
const auto & logger () const
Private Attributes
std::unique_ptr< const
Acts::Logger > m_logger
Config m_cfg
std::unique_ptr< Ort::Env > m_env
std::unique_ptr< Ort::Session > m_model
Detailed Description
Definition at line 24 of file OnnxMetricLearning.hpp.
View newest version in sPHENIX GitHub at line 24 of file OnnxMetricLearning.hpp
Constructor & Destructor Documentation
Acts::OnnxMetricLearning::OnnxMetricLearning (const Config & cfg, std::unique_ptr< const Logger > logger)
Definition at line 20 of file OnnxMetricLearning.cpp.
View newest version in sPHENIX GitHub at line 20 of file OnnxMetricLearning.cpp
References m_cfg, m_env, m_model, and Acts::OnnxMetricLearning::Config::modelPath.
Acts::OnnxMetricLearning::~OnnxMetricLearning ()
Definition at line 35 of file OnnxMetricLearning.cpp.
View newest version in sPHENIX GitHub at line 35 of file OnnxMetricLearning.cpp
Member Function Documentation
void Acts::OnnxMetricLearning::buildEdgesWrapper (std::vector< float > & embedFeatures, std::vector< int64_t > & edgeList, int64_t numSpacepoints, const Logger & logger) const private
Definition at line 37 of file OnnxMetricLearning.cpp.
View newest version in sPHENIX GitHub at line 37 of file OnnxMetricLearning.cpp
References Acts::ACTS_VERBOSE(), Acts::detail::buildEdges(), Acts::OnnxMetricLearning::Config::embeddingDim, Acts::OnnxMetricLearning::Config::knnVal, m_cfg, ckf::options, and Acts::OnnxMetricLearning::Config::rVal.
Referenced by operator()().
Config Acts::OnnxMetricLearning::config () const inline
Definition at line 41 of file OnnxMetricLearning.hpp.
View newest version in sPHENIX GitHub at line 41 of file OnnxMetricLearning.hpp
References m_cfg.
const auto& Acts::OnnxMetricLearning::logger () const inline private
Definition at line 49 of file OnnxMetricLearning.hpp.
View newest version in sPHENIX GitHub at line 49 of file OnnxMetricLearning.hpp
References m_logger.
Referenced by operator()().
std::tuple< std::any, std::any > Acts::OnnxMetricLearning::operator() (std::vector< float > & inputValues, std::size_t numNodes, int deviceHint = -1) override virtual
Perform the graph construction
Parameters
inputValues Flattened input data
numNodes Number of nodes. inputValues.size() / numNodes then gives the number of features
deviceHint Which GPU to pick. Not relevant for CPU-only builds
Returns
(node_tensor, edge_tensore)
Implements Acts::GraphConstructionBase.
Definition at line 59 of file OnnxMetricLearning.cpp.
View newest version in sPHENIX GitHub at line 59 of file OnnxMetricLearning.cpp
References ACTS_DEBUG, Acts::ACTS_VERBOSE(), buildEdgesWrapper(), Acts::OnnxMetricLearning::Config::embeddingDim, i, logger(), m_cfg, m_model, testing::internal::move(), runSessionWithIoBinding(), and Acts::OnnxMetricLearning::Config::spacepointFeatures.
Member Data Documentation
Config Acts::OnnxMetricLearning::m_cfg private
Definition at line 51 of file OnnxMetricLearning.hpp.
View newest version in sPHENIX GitHub at line 51 of file OnnxMetricLearning.hpp
Referenced by buildEdgesWrapper(), config(), OnnxMetricLearning(), and operator()().
std::unique_ptr<Ort::Env> Acts::OnnxMetricLearning::m_env private
Definition at line 52 of file OnnxMetricLearning.hpp.
View newest version in sPHENIX GitHub at line 52 of file OnnxMetricLearning.hpp
Referenced by OnnxMetricLearning().
std::unique_ptr<const Acts::Logger> Acts::OnnxMetricLearning::m_logger private
Definition at line 48 of file OnnxMetricLearning.hpp.
View newest version in sPHENIX GitHub at line 48 of file OnnxMetricLearning.hpp
Referenced by logger().
std::unique_ptr<Ort::Session> Acts::OnnxMetricLearning::m_model private
Definition at line 53 of file OnnxMetricLearning.hpp.
View newest version in sPHENIX GitHub at line 53 of file OnnxMetricLearning.hpp
Referenced by OnnxMetricLearning(), and operator()().
The documentation for this exception was generated from the following files:
acts/blob/sPHENIX/Plugins/ExaTrkX/include/Acts/Plugins/ExaTrkX/OnnxMetricLearning.hpp
acts/blob/sPHENIX/Plugins/ExaTrkX/src/OnnxMetricLearning.cpp