Analysis Software: SColdQcdCorrelatorAnalysis::SCorrelatorUtilities Namespace Reference
SColdQcdCorrelatorAnalysis::SCorrelatorUtilities Namespace Reference
Classes
struct ClustInfo
struct CstInfo
struct RecoInfo
struct GenInfo
struct FlowInfo
struct ParInfo
struct JetInfo
struct TrkInfo
Functions
RawClusterContainer * GetClusterStore (PHCompositeNode *topNode, const string node)
RawClusterContainer::ConstRange GetClusters (PHCompositeNode *topNode, const string store)
bool IsInAcceptance (const ClustInfo &cluster, const ClustInfo &minimum, const ClustInfo &maximum)
bool IsInAcceptance (const CstInfo &cst, const CstInfo &minimum, const CstInfo &maximum)
long GetNumTrks (PHCompositeNode *topNode)
long GetNumFinalStatePars (PHCompositeNode *topNode, const vector< int > evtsToGrab, const int subset=0, optional< float > chargeToGrab=nullopt)
double GetSumTrkMomentum (PHCompositeNode *topNode)
double GetSumCaloEne (PHCompositeNode *topNode, const string store)
double GetSumFinalStateParEne (PHCompositeNode *topNode, const vector< int > evtsToGrab, const int subset, optional< float > chargeToGrab=nullopt)
ParInfo GetPartonInfo (PHCompositeNode *topNode, const int event, const int status)
ROOT::Math::XYZVector GetRecoVtx (PHCompositeNode *topNode)
ParticleFlowElementContainer * GetFlowStore (PHCompositeNode *topNode)
ParticleFlowElementContainer::ConstRange GetParticleFlowObjects (PHCompositeNode *topNode)
bool IsInAcceptance (const FlowInfo &flow, const FlowInfo &minimum, const FlowInfo &maximum)
PHHepMCGenEventMap * GetMcEventMap (PHCompositeNode *topNode)
PHHepMCGenEvent * GetMcEvent (PHCompositeNode *topNode, const int iEvtToGrab)
HepMC::GenEvent * GetGenEvent (PHCompositeNode *topNode, const int iEvtToGrab)
int GetEmbedID (PHCompositeNode *topNode, const int iEvtToGrab)
bool IsInAcceptance (const ParInfo &particle, const ParInfo &minimum, const ParInfo &maximum)
bool IsFinalState (const int status)
bool IsHardScatterProduct (const int status)
bool IsParton (const int pid)
bool IsOutgoingParton (const HepMC::GenParticle *par)
float GetParticleCharge (const int pid)
vector< int > GrabSubevents (PHCompositeNode *topNode, optional< vector< int >> evtsToGrab=nullopt)
bool IsSubEvtGood (const int embedID, const int option, const bool isEmbed)
bool IsSubEvtGood (const int embedID, vector< int > subEvtsToUse)
void CleanseNodeName (string &nameToClean)
template<typename T >
void CreateNode (PHCompositeNode *topNode, string newNodeName, T &objectInNode)
template<typename T >
int64_t GetEntry (T *tree, const uint64_t entry)
template int64_t GetEntry (TTree *tree, const uint64_t entry)
template int64_t GetEntry (TChain *tree, const uint64_t entry)
template int64_t GetEntry (TNtuple *tree, const uint64_t entry)
template<typename T >
int64_t LoadTree (T *tree, const uint64_t entry, int &current)
template int64_t LoadTree (TTree *tree, const uint64_t entry, int &current)
template int64_t LoadTree (TChain *tree, const uint64_t entry, int &current)
template int64_t LoadTree (TNtuple *tree, const uint64_t entry, int &current)
void AddTagToLeaves (const string tag, vector< string > &leaves)
string FlattenLeafList (const vector< string > &leaves)
template<typename T >
vector< string > MakeLeafVector (optional< string > tag=nullopt)
template<typename T >
void AddLeavesToVector (vector< string > &vecToAddTo, optional< string > tag=nullopt)
bool IsInAcceptance (const JetInfo &jet, const JetInfo &minimum, const JetInfo &maximum)
pair< double, double > GetTrackDcaPair (SvtxTrack *track, PHCompositeNode *topNode)
ROOT::Math::XYZVector GetTrackVertex (SvtxTrack *track, PHCompositeNode *topNode)
double GetTrackDeltaPt (SvtxTrack *track)
int GetNumLayer (SvtxTrack *track, const uint8_t sys)
int GetNumClust (SvtxTrack *track, const uint8_t sys)
SvtxTrackMap * GetTrackMap (PHCompositeNode *topNode)
bool IsInAcceptance (const TrkInfo &trk, const TrkInfo &minimum, const TrkInfo &maximum)
bool IsInSigmaDcaCut (const TrkInfo &trk, const pair< float, float > nSigCut, const pair< float, float > ptFitMax, const pair< TF1 *, TF1 * > fSigmaDca)
bool IsGoodTrackSeed (SvtxTrack *track, const bool requireSiSeeds=true)
bool IsFromPrimaryVtx (SvtxTrack *track, PHCompositeNode *topNode)
TrackSeed * GetTrackSeed (SvtxTrack *track, const uint8_t sys)
int GetMatchID (SvtxTrack *track, SvtxTrackEval *trackEval)
GlobalVertexMap * GetVertexMap (PHCompositeNode *topNode)
GlobalVertex * GetGlobalVertex (PHCompositeNode *topNode, optional< int > iVtxToGrab=nullopt)
Function Documentation
template<typename T > void SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::AddLeavesToVector (vector< string > & vecToAddTo, optional< string > tag = nullopt)
Definition at line 175 of file Interfaces.h.
View newest version in sPHENIX GitHub at line 175 of file Interfaces.h
void SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::AddTagToLeaves (const string tag, vector< string > & leaves)
Definition at line 134 of file Interfaces.h.
View newest version in sPHENIX GitHub at line 134 of file Interfaces.h
Referenced by MakeLeafVector().
void SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::CleanseNodeName (string & nameToClean)
Definition at line 49 of file Interfaces.h.
View newest version in sPHENIX GitHub at line 49 of file Interfaces.h
References position.
Referenced by CreateNode().
template<typename T > void SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::CreateNode (PHCompositeNode * topNode, string newNodeName, T & objectInNode)
Definition at line 63 of file Interfaces.h.
View newest version in sPHENIX GitHub at line 63 of file Interfaces.h
References CleanseNodeName(), and PHNodeIterator::findFirst().
string SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::FlattenLeafList (const vector< string > & leaves)
Definition at line 146 of file Interfaces.h.
View newest version in sPHENIX GitHub at line 146 of file Interfaces.h
Referenced by SColdQcdCorrelatorAnalysis::SCheckTrackPairs::InitTuples().
RawClusterContainer::ConstRange SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::GetClusters (PHCompositeNode * topNode, const string store)
Definition at line 169 of file CalTools.h.
View newest version in sPHENIX GitHub at line 169 of file CalTools.h
References GetClusterStore().
Referenced by GetSumCaloEne().
RawClusterContainer* SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::GetClusterStore (PHCompositeNode * topNode, const string node)
Definition at line 153 of file CalTools.h.
View newest version in sPHENIX GitHub at line 153 of file CalTools.h
References assert, and PHWHERE.
Referenced by SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::AddECal(), SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::AddHCal(), GetClusters(), SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::GetSumECalEne(), and SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::GetSumHCalEne().
int SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::GetEmbedID (PHCompositeNode * topNode, const int iEvtToGrab)
Definition at line 235 of file GenTools.h.
View newest version in sPHENIX GitHub at line 235 of file GenTools.h
References GetMcEvent().
Referenced by SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::AddParticles().
template<typename T > int64_t SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::GetEntry (T * tree, const uint64_t entry)
Definition at line 84 of file Interfaces.h.
View newest version in sPHENIX GitHub at line 84 of file Interfaces.h
References Acts::UnitConstants::min, and utils::status.
Referenced by STrackCutStudy::Analyze(), analyzeClusterEtIso(), SDeltaPtCutStudy::ApplyFlatDeltaPtCuts(), SDeltaPtCutStudy::ApplyPtDependentDeltaPtCuts(), CalculateSigmaDca(), SColdQcdCorrelatorAnalysis::SEnergyCorrelator::DoCorrelatorCalculation(), SDeltaPtCutStudy::FillTruthHistograms(), SColdQcdCorrelatorAnalysis::SEnergyCorrelator::GetEntry(), STrackMatcherComparator::GetNewTreeHists(), STrackMatcherComparator::GetNewTupleHists(), STrackMatcherComparator::GetOldTupleHists(), MakeNewMatcherPlots(), MakeNewMatcherTuplePlots(), MakeOldEvaluatorPlots(), Prototype2_DSTReader::Process(), and QuickDeltaPtExtractor().
template int64_t SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::GetEntry (TTree * tree, const uint64_t entry)
template int64_t SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::GetEntry (TChain * tree, const uint64_t entry)
template int64_t SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::GetEntry (TNtuple * tree, const uint64_t entry)
ParticleFlowElementContainer* SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::GetFlowStore (PHCompositeNode * topNode)
Definition at line 150 of file FlowTools.h.
View newest version in sPHENIX GitHub at line 150 of file FlowTools.h
References assert, PHWHERE, and store.
Referenced by SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::AddFlow(), and GetParticleFlowObjects().
HepMC::GenEvent* SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::GetGenEvent (PHCompositeNode * topNode, const int iEvtToGrab)
Definition at line 219 of file GenTools.h.
View newest version in sPHENIX GitHub at line 219 of file GenTools.h
References assert, GetMcEvent(), and PHWHERE.
Referenced by GetNumFinalStatePars(), GetPartonInfo(), and GetSumFinalStateParEne().
GlobalVertex* SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::GetGlobalVertex (PHCompositeNode * topNode, optional< int > iVtxToGrab = nullopt)
Definition at line 60 of file VtxTools.h.
View newest version in sPHENIX GitHub at line 60 of file VtxTools.h
References assert, parse_cmake_options::begin, GetVertexMap(), and PHWHERE.
Referenced by SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::AddECal(), SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::AddHCal(), GetRecoVtx(), SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::GetRecoVtx(), SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::GetSumECalEne(), SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::GetSumHCalEne(), GetTrackDcaPair(), SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::GetTrackDcaPair(), GetTrackVertex(), SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::GetTrackVertex(), IsFromPrimaryVtx(), and SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::IsFromPrimaryVtx().
int SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::GetMatchID (SvtxTrack * track, SvtxTrackEval * trackEval)
Definition at line 527 of file TrkTools.h.
View newest version in sPHENIX GitHub at line 527 of file TrkTools.h
Referenced by SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::AddTracks().
PHHepMCGenEvent* SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::GetMcEvent (PHCompositeNode * topNode, const int iEvtToGrab)
Definition at line 203 of file GenTools.h.
View newest version in sPHENIX GitHub at line 203 of file GenTools.h
References assert, GetMcEventMap(), and PHWHERE.
Referenced by SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::AddParticles(), GetEmbedID(), GetGenEvent(), SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::GetNumChrgPars(), SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::GetPartonInfo(), and SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::GetSumParEne().
PHHepMCGenEventMap* SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::GetMcEventMap (PHCompositeNode * topNode)
Definition at line 188 of file GenTools.h.
View newest version in sPHENIX GitHub at line 188 of file GenTools.h
References assert, and PHWHERE.
Referenced by GetMcEvent(), and GrabSubevents().
int SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::GetNumClust (SvtxTrack * track, const uint8_t sys = 0)
Definition at line 483 of file TrkTools.h.
View newest version in sPHENIX GitHub at line 483 of file TrkTools.h
References TrkrDefs::getLayer(), GetTrackSeed(), Intt(), layer, Mvtx(), and seed.
Referenced by SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::AddTracks(), and SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::TrkInfo::SetInfo().
long SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::GetNumFinalStatePars (PHCompositeNode * topNode, const vector< int > evtsToGrab, const int subset = 0, optional< float > chargeToGrab = nullopt)
Definition at line 233 of file EvtTools.h.
View newest version in sPHENIX GitHub at line 233 of file EvtTools.h
References charge(), GetGenEvent(), GetParticleCharge(), IsFinalState(), particle, and utils::status.
Referenced by SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::GenInfo::SetInfo().
int SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::GetNumLayer (SvtxTrack * track, const uint8_t sys = 0)
Definition at line 407 of file TrkTools.h.
View newest version in sPHENIX GitHub at line 407 of file TrkTools.h
References TrkrDefs::getLayer(), GetTrackSeed(), Intt(), layer, Mvtx(), and seed.
Referenced by SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::AddTracks(), SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::IsGoodTrack(), and SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::TrkInfo::SetInfo().
long SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::GetNumTrks (PHCompositeNode * topNode)
Definition at line 223 of file EvtTools.h.
View newest version in sPHENIX GitHub at line 223 of file EvtTools.h
References GetTrackMap(), and size.
Referenced by SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::GetEventVariables(), and SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::RecoInfo::SetInfo().
float SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::GetParticleCharge (const int pid)
Definition at line 295 of file GenTools.h.
View newest version in sPHENIX GitHub at line 295 of file GenTools.h
References charge().
Referenced by GetNumFinalStatePars(), GetSumFinalStateParEne(), and SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::IsGoodParticle().
ParticleFlowElementContainer::ConstRange SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::GetParticleFlowObjects (PHCompositeNode * topNode)
Definition at line 165 of file FlowTools.h.
View newest version in sPHENIX GitHub at line 165 of file FlowTools.h
References assert, GetFlowStore(), PHWHERE, and store.
ParInfo SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::GetPartonInfo (PHCompositeNode * topNode, const int event, const int status)
Definition at line 403 of file EvtTools.h.
View newest version in sPHENIX GitHub at line 403 of file EvtTools.h
References GetGenEvent(), IsParton(), particle, parton(), SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::ParInfo::SetInfo(), and utils::status.
Referenced by SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::GenInfo::SetInfo().
ROOT::Math::XYZVector SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::GetRecoVtx (PHCompositeNode * topNode)
Definition at line 86 of file VtxTools.h.
View newest version in sPHENIX GitHub at line 86 of file VtxTools.h
References GetGlobalVertex().
Referenced by SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::GetEventVariables(), and SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::RecoInfo::SetInfo().
double SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::GetSumCaloEne (PHCompositeNode * topNode, const string store)
Definition at line 318 of file EvtTools.h.
View newest version in sPHENIX GitHub at line 318 of file EvtTools.h
References clusters, and GetClusters().
Referenced by SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::RecoInfo::SetInfo().
double SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::GetSumFinalStateParEne (PHCompositeNode * topNode, const vector< int > evtsToGrab, const int subset, optional< float > chargeToGrab = nullopt)
Definition at line 345 of file EvtTools.h.
View newest version in sPHENIX GitHub at line 345 of file EvtTools.h
References charge(), energy, GetGenEvent(), GetParticleCharge(), IsFinalState(), momentum, particle, and utils::status.
Referenced by SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::GenInfo::SetInfo().
double SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::GetSumTrkMomentum (PHCompositeNode * topNode)
Definition at line 291 of file EvtTools.h.
View newest version in sPHENIX GitHub at line 291 of file EvtTools.h
References parse_cmake_options::begin, end, and GetTrackMap().
Referenced by SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::RecoInfo::SetInfo().
pair< double, double > SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::GetTrackDcaPair (SvtxTrack * track, PHCompositeNode * topNode)
Definition at line 323 of file TrkTools.h.
View newest version in sPHENIX GitHub at line 323 of file TrkTools.h
References TrackAnalysisUtils::get_dca(), and GetGlobalVertex().
Referenced by SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::AddTracks(), SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::IsGoodTrack(), and SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::TrkInfo::SetInfo().
double SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::GetTrackDeltaPt (SvtxTrack * track)
Definition at line 351 of file TrkTools.h.
View newest version in sPHENIX GitHub at line 351 of file TrkTools.h
Referenced by SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::AddTracks(), SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::IsGoodTrack(), and SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::TrkInfo::SetInfo().
SvtxTrackMap* SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::GetTrackMap (PHCompositeNode * topNode)
Definition at line 249 of file TrkTools.h.
View newest version in sPHENIX GitHub at line 249 of file TrkTools.h
References assert, and PHWHERE.
Referenced by SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::AddTracks(), SColdQcdCorrelatorAnalysis::SCheckTrackPairs::DoDoubleTrackLoop(), GetNumTrks(), SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::GetNumTrks(), and GetSumTrkMomentum().
TrackSeed* SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::GetTrackSeed (SvtxTrack * track, const uint8_t sys)
Definition at line 374 of file TrkTools.h.
View newest version in sPHENIX GitHub at line 374 of file TrkTools.h
References Intt(), Mvtx(), and seed.
Referenced by GetNumClust(), and GetNumLayer().
ROOT::Math::XYZVector SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::GetTrackVertex (SvtxTrack * track, PHCompositeNode * topNode)
Definition at line 337 of file TrkTools.h.
View newest version in sPHENIX GitHub at line 337 of file TrkTools.h
References GetGlobalVertex().
Referenced by SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::AddTracks(), SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::IsGoodTrack(), and SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::TrkInfo::SetInfo().
GlobalVertexMap* SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::GetVertexMap (PHCompositeNode * topNode)
Definition at line 40 of file VtxTools.h.
View newest version in sPHENIX GitHub at line 40 of file VtxTools.h
References assert, and PHWHERE.
Referenced by GetGlobalVertex(), and SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::GetGlobalVertex().
vector<int> SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::GrabSubevents (PHCompositeNode * topNode, optional< vector< int >> evtsToGrab = nullopt)
Definition at line 310 of file GenTools.h.
View newest version in sPHENIX GitHub at line 310 of file GenTools.h
References parse_cmake_options::begin, end, and GetMcEventMap().
bool SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::IsFinalState (const int status)
Definition at line 253 of file GenTools.h.
View newest version in sPHENIX GitHub at line 253 of file GenTools.h
Referenced by GetNumFinalStatePars(), and GetSumFinalStateParEne().
bool SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::IsFromPrimaryVtx (SvtxTrack * track, PHCompositeNode * topNode)
Definition at line 306 of file TrkTools.h.
View newest version in sPHENIX GitHub at line 306 of file TrkTools.h
References GetGlobalVertex().
Referenced by SColdQcdCorrelatorAnalysis::SCheckTrackPairs::IsGoodTrack(), and SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::IsGoodTrack().
bool SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::IsGoodTrackSeed (SvtxTrack * track, const bool requireSiSeeds = true)
Definition at line 289 of file TrkTools.h.
View newest version in sPHENIX GitHub at line 289 of file TrkTools.h
Referenced by SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::GetNumClust(), SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::GetNumLayer(), SColdQcdCorrelatorAnalysis::SCheckTrackPairs::IsGoodTrack(), and SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::IsGoodTrack().
bool SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::IsHardScatterProduct (const int status)
Definition at line 261 of file GenTools.h.
View newest version in sPHENIX GitHub at line 261 of file GenTools.h
Referenced by IsOutgoingParton().
bool SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::IsInAcceptance (const JetInfo & jet, const JetInfo & minimum, const JetInfo & maximum)
Definition at line 126 of file JetTools.h.
View newest version in sPHENIX GitHub at line 126 of file JetTools.h
bool SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::IsInAcceptance (const CstInfo & cst, const CstInfo & minimum, const CstInfo & maximum)
Definition at line 142 of file CstTools.h.
View newest version in sPHENIX GitHub at line 142 of file CstTools.h
bool SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::IsInAcceptance (const ClustInfo & cluster, const ClustInfo & minimum, const ClustInfo & maximum)
Definition at line 179 of file CalTools.h.
View newest version in sPHENIX GitHub at line 179 of file CalTools.h
bool SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::IsInAcceptance (const FlowInfo & flow, const FlowInfo & minimum, const FlowInfo & maximum)
Definition at line 184 of file FlowTools.h.
View newest version in sPHENIX GitHub at line 184 of file FlowTools.h
bool SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::IsInAcceptance (const ParInfo & particle, const ParInfo & minimum, const ParInfo & maximum)
Definition at line 245 of file GenTools.h.
View newest version in sPHENIX GitHub at line 245 of file GenTools.h
bool SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::IsInAcceptance (const TrkInfo & trk, const TrkInfo & minimum, const TrkInfo & maximum)
Definition at line 265 of file TrkTools.h.
View newest version in sPHENIX GitHub at line 265 of file TrkTools.h
bool SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::IsInSigmaDcaCut (const TrkInfo & trk, const pair< float, float > nSigCut, const pair< float, float > ptFitMax, const pair< TF1 *, TF1 * > fSigmaDca)
Definition at line 273 of file TrkTools.h.
View newest version in sPHENIX GitHub at line 273 of file TrkTools.h
References SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::TrkInfo::dcaXY, SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::TrkInfo::dcaZ, and SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::TrkInfo::pt.
Referenced by SColdQcdCorrelatorAnalysis::SCheckTrackPairs::IsGoodTrack().
bool SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::IsOutgoingParton (const HepMC::GenParticle * par)
Definition at line 281 of file GenTools.h.
View newest version in sPHENIX GitHub at line 281 of file GenTools.h
References IsHardScatterProduct(), IsParton(), train_ambiguity_solver::pid, and utils::status.
Referenced by SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::GetPartonInfo().
bool SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::IsParton (const int pid)
Definition at line 269 of file GenTools.h.
View newest version in sPHENIX GitHub at line 269 of file GenTools.h
Referenced by GetPartonInfo(), and IsOutgoingParton().
bool SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::IsSubEvtGood (const int embedID, const int option, const bool isEmbed)
Definition at line 347 of file GenTools.h.
View newest version in sPHENIX GitHub at line 347 of file GenTools.h
bool SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::IsSubEvtGood (const int embedID, vector< int > subEvtsToUse)
Definition at line 394 of file GenTools.h.
View newest version in sPHENIX GitHub at line 394 of file GenTools.h
template<typename T > int64_t SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::LoadTree (T * tree, const uint64_t entry, int & current)
Definition at line 103 of file Interfaces.h.
View newest version in sPHENIX GitHub at line 103 of file Interfaces.h
References Acts::UnitConstants::min, and utils::status.
Referenced by SColdQcdCorrelatorAnalysis::SEnergyCorrelator::DoCorrelatorCalculation(), and SColdQcdCorrelatorAnalysis::SEnergyCorrelator::LoadTree().
template int64_t SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::LoadTree (TTree * tree, const uint64_t entry, int & current)
template int64_t SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::LoadTree (TChain * tree, const uint64_t entry, int & current)
template int64_t SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::LoadTree (TNtuple * tree, const uint64_t entry, int & current)
template<typename T > vector<string> SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::MakeLeafVector (optional< string > tag = nullopt)
Definition at line 162 of file Interfaces.h.
View newest version in sPHENIX GitHub at line 162 of file Interfaces.h
References AddTagToLeaves().