Analysis Software: ActsExamples::Trajectories Struct Reference
ActsExamples::Trajectories Struct Reference final
#include <acts/blob/sPHENIX/Examples/Framework/include/ActsExamples/EventData/Trajectories.hpp>
Public Types
using MultiTrajectory = Acts::ConstVectorMultiTrajectory
(Reconstructed) trajectory with multiple states.
using IndexedParameters = std::unordered_map< Acts::MultiTrajectoryTraits::IndexType, TrackParameters >
Fitted parameters identified by indices in the multi trajectory.
Public Member Functions
Trajectories ()=default
Trajectories (const MultiTrajectory &multiTraj, const std::vector< Acts::MultiTrajectoryTraits::IndexType > &tTips, const IndexedParameters &parameters)
bool empty () const
Return true if there exists no valid trajectory.
const MultiTrajectory & multiTrajectory () const
Access the underlying multi trajectory.
const std::vector
< Acts::MultiTrajectoryTraits::IndexType > & tips () const
Access the tip indices that identify valid trajectories.
bool hasTrajectory (Acts::MultiTrajectoryTraits::IndexType entryIndex) const
bool hasTrackParameters (Acts::MultiTrajectoryTraits::IndexType entryIndex) const
const TrackParameters & trackParameters (Acts::MultiTrajectoryTraits::IndexType entryIndex) const
Private Attributes
const MultiTrajectory * m_multiTrajectory {nullptr}
std::vector
< Acts::MultiTrajectoryTraits::IndexType > m_trackTips = {}
IndexedParameters m_trackParameters = {}
Detailed Description
Store reconstructed trajectories from track finding/fitting.
It contains a MultiTrajectory with a vector of entry indices for individual trajectories, and a map of fitted parameters indexed by the entry index. In case of track fitting, there is at most one trajectory in the MultiTrajectory; In case of track finding, there could be multiple trajectories in the MultiTrajectory.
Definition at line 30 of file Trajectories.hpp.
View newest version in sPHENIX GitHub at line 30 of file Trajectories.hpp
Member Typedef Documentation
using ActsExamples::Trajectories::IndexedParameters = std::unordered_map<Acts::MultiTrajectoryTraits::IndexType, TrackParameters>
Fitted parameters identified by indices in the multi trajectory.
Definition at line 37 of file Trajectories.hpp.
View newest version in sPHENIX GitHub at line 37 of file Trajectories.hpp
using ActsExamples::Trajectories::MultiTrajectory = Acts::ConstVectorMultiTrajectory
(Reconstructed) trajectory with multiple states.
Definition at line 33 of file Trajectories.hpp.
View newest version in sPHENIX GitHub at line 33 of file Trajectories.hpp
Constructor & Destructor Documentation
ActsExamples::Trajectories::Trajectories () default
Default construct an empty object. Required for container compatibility and to signal an error.
ActsExamples::Trajectories::Trajectories (const MultiTrajectory & multiTraj, const std::vector< Acts::MultiTrajectoryTraits::IndexType > & tTips, const IndexedParameters & parameters) inline
Construct from fitted multi trajectory and parameters.
Parameters
multiTraj The multi trajectory ///
tTips Tip indices that identify valid trajectories
parameters Fitted track parameters indexed by trajectory index
Definition at line 47 of file Trajectories.hpp.
View newest version in sPHENIX GitHub at line 47 of file Trajectories.hpp
Member Function Documentation
bool ActsExamples::Trajectories::empty () const inline
Return true if there exists no valid trajectory.
Definition at line 55 of file Trajectories.hpp.
View newest version in sPHENIX GitHub at line 55 of file Trajectories.hpp
References m_trackTips.
bool ActsExamples::Trajectories::hasTrackParameters (Acts::MultiTrajectoryTraits::IndexType entryIndex) const inline
Check if fitted track parameters exists for the given index.
Parameters
entryIndex The trajectory entry index
Returns
Whether having fitted track parameters or not
Definition at line 80 of file Trajectories.hpp.
View newest version in sPHENIX GitHub at line 80 of file Trajectories.hpp
References m_trackParameters.
bool ActsExamples::Trajectories::hasTrajectory (Acts::MultiTrajectoryTraits::IndexType entryIndex) const inline
Check if a trajectory exists for the given index.
Parameters
entryIndex The trajectory entry index
Returns
Whether there is trajectory with provided entry index
Definition at line 72 of file Trajectories.hpp.
View newest version in sPHENIX GitHub at line 72 of file Trajectories.hpp
References test_fpe::count, and m_trackTips.
Referenced by ActsExamples::identifyContributingParticles().
const MultiTrajectory& ActsExamples::Trajectories::multiTrajectory () const inline
Access the underlying multi trajectory.
Definition at line 58 of file Trajectories.hpp.
View newest version in sPHENIX GitHub at line 58 of file Trajectories.hpp
References m_multiTrajectory, and throw_assert.
Referenced by ActsExamples::identifyContributingParticles(), and ActsExamples::EDM4hepUtil::writeTrajectory().
const std::vector<Acts::MultiTrajectoryTraits::IndexType>& ActsExamples::Trajectories::tips () const inline
Access the tip indices that identify valid trajectories.
Definition at line 64 of file Trajectories.hpp.
View newest version in sPHENIX GitHub at line 64 of file Trajectories.hpp
References m_trackTips.
const TrackParameters& ActsExamples::Trajectories::trackParameters (Acts::MultiTrajectoryTraits::IndexType entryIndex) const inline
Access the fitted track parameters for the given index.
Parameters
entryIndex The trajectory entry index
Returns
The fitted track parameters of the trajectory
Definition at line 89 of file Trajectories.hpp.
View newest version in sPHENIX GitHub at line 89 of file Trajectories.hpp
References it, m_trackParameters, and to_string().
Referenced by PHActsToSvtxTracks::createSvtxTrack().
Member Data Documentation
const MultiTrajectory* ActsExamples::Trajectories::m_multiTrajectory {nullptr} private
Definition at line 102 of file Trajectories.hpp.
View newest version in sPHENIX GitHub at line 102 of file Trajectories.hpp
Referenced by multiTrajectory().
IndexedParameters ActsExamples::Trajectories::m_trackParameters = {} private
Definition at line 106 of file Trajectories.hpp.
View newest version in sPHENIX GitHub at line 106 of file Trajectories.hpp
Referenced by hasTrackParameters(), and trackParameters().
std::vector<Acts::MultiTrajectoryTraits::IndexType> ActsExamples::Trajectories::m_trackTips = {} private
Definition at line 104 of file Trajectories.hpp.
View newest version in sPHENIX GitHub at line 104 of file Trajectories.hpp
Referenced by empty(), hasTrajectory(), and tips().
The documentation for this struct was generated from the following file:
acts/blob/sPHENIX/Examples/Framework/include/ActsExamples/EventData/Trajectories.hpp