Analysis Software: Selector Class Reference
Selector Class Reference
#include <JETSCAPE/blob/main/external_packages/fjcore.hh>
Classes
class InvalidArea
class InvalidWorker
Public Member Functions
Selector ()
Selector (SelectorWorker *worker_in)
virtual ~Selector ()
bool pass (const PseudoJet &jet) const
bool operator() (const PseudoJet &jet) const
unsigned int count (const std::vector< PseudoJet > &jets) const
PseudoJet sum (const std::vector< PseudoJet > &jets) const
double scalar_pt_sum (const std::vector< PseudoJet > &jets) const
void sift (const std::vector< PseudoJet > &jets, std::vector< PseudoJet > &jets_that_pass, std::vector< PseudoJet > &jets_that_fail) const
bool applies_jet_by_jet () const
std::vector< PseudoJet > operator() (const std::vector< PseudoJet > &jets) const
virtual void nullify_non_selected (std::vector< const PseudoJet * > &jets) const
void get_rapidity_extent (double &rapmin, double &rapmax) const
std::string description () const
bool is_geometric () const
bool has_finite_area () const
const SharedPtr< SelectorWorker > & worker () const
const SelectorWorker * validated_worker () const
bool takes_reference () const
const Selector & set_reference (const PseudoJet &reference)
Selector & operator&= (const Selector &b)
Selector & operator|= (const Selector &b)
Protected Member Functions
void _copy_worker_if_needed ()
Private Attributes
SharedPtr< SelectorWorker > _worker
the underlying worker
Detailed Description
Definition at line 863 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 863 of file fjcore.hh
Constructor & Destructor Documentation
Selector::Selector () inline
Definition at line 865 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 865 of file fjcore.hh
Selector::Selector (SelectorWorker * worker_in) inline
Definition at line 866 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 866 of file fjcore.hh
References _worker, and SharedPtr< T >::reset().
virtual Selector::~Selector () inline virtual
Definition at line 867 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 867 of file fjcore.hh
Member Function Documentation
void Selector::_copy_worker_if_needed () inline protected
Definition at line 930 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 930 of file fjcore.hh
References _worker, SelectorWorker::copy(), SharedPtr< T >::reset(), and SharedPtr< T >::unique().
Referenced by set_reference().
bool Selector::applies_jet_by_jet () const inline
Definition at line 883 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 883 of file fjcore.hh
References SelectorWorker::applies_jet_by_jet(), and validated_worker().
Referenced by pass().
unsigned int Selector::count (const std::vector< PseudoJet > & jets) const
Definition at line 4176 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 4176 of file fjcore.cc
References i, and n.
std::string Selector::description () const inline
Definition at line 893 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 893 of file fjcore.hh
References SelectorWorker::description(), and validated_worker().
void Selector::get_rapidity_extent (double & rapmin, double & rapmax) const inline
Definition at line 890 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 890 of file fjcore.hh
References SelectorWorker::get_rapidity_extent(), and validated_worker().
bool Selector::has_finite_area () const inline
Definition at line 899 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 899 of file fjcore.hh
References SelectorWorker::has_finite_area(), and validated_worker().
bool Selector::is_geometric () const inline
Definition at line 896 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 896 of file fjcore.hh
References SelectorWorker::is_geometric(), and validated_worker().
virtual void Selector::nullify_non_selected (std::vector< const PseudoJet * > & jets) const inline virtual
Definition at line 887 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 887 of file fjcore.hh
References SelectorWorker::terminator(), and validated_worker().
Selector & Selector::operator&= (const Selector & b)
Definition at line 4932 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 4932 of file fjcore.cc
bool Selector::operator() (const PseudoJet & jet) const inline
Definition at line 874 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 874 of file fjcore.hh
References pass().
FJCORE_BEGIN_NAMESPACE std::vector< PseudoJet > Selector::operator() (const std::vector< PseudoJet > & jets) const
Definition at line 4156 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 4156 of file fjcore.cc
References i.
Selector & Selector::operator|= (const Selector & b)
Definition at line 4936 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 4936 of file fjcore.cc
bool Selector::pass (const PseudoJet & jet) const inline
Definition at line 868 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 868 of file fjcore.hh
References _worker, applies_jet_by_jet(), SelectorWorker::pass(), and validated_worker().
Referenced by operator()().
double Selector::scalar_pt_sum (const std::vector< PseudoJet > & jets) const
Definition at line 4214 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 4214 of file fjcore.cc
References i, and PseudoJet::pt().
const Selector& Selector::set_reference (const PseudoJet & reference) inline
Definition at line 911 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 911 of file fjcore.hh
References _copy_worker_if_needed(), _worker, SelectorWorker::set_reference(), takes_reference(), and validated_worker().
void Selector::sift (const std::vector< PseudoJet > & jets, std::vector< PseudoJet > & jets_that_pass, std::vector< PseudoJet > & jets_that_fail) const
Definition at line 4233 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 4233 of file fjcore.cc
References i.
PseudoJet Selector::sum (const std::vector< PseudoJet > & jets) const
Definition at line 4195 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 4195 of file fjcore.cc
References i, and PseudoJet::PseudoJet().
bool Selector::takes_reference () const inline
Definition at line 908 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 908 of file fjcore.hh
References SelectorWorker::takes_reference(), and validated_worker().
Referenced by set_reference().
const SelectorWorker* Selector::validated_worker () const inline
Definition at line 903 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 903 of file fjcore.hh
References _worker, and SharedPtr< T >::get().
Referenced by applies_jet_by_jet(), description(), get_rapidity_extent(), has_finite_area(), is_geometric(), nullify_non_selected(), pass(), set_reference(), and takes_reference().
const SharedPtr<SelectorWorker>& Selector::worker () const inline
Definition at line 902 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 902 of file fjcore.hh
References _worker.
Member Data Documentation
SharedPtr<SelectorWorker> Selector::_worker private
the underlying worker
Definition at line 935 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 935 of file fjcore.hh
Referenced by _copy_worker_if_needed(), pass(), Selector(), set_reference(), validated_worker(), and worker().
The documentation for this class was generated from the following files:
JETSCAPE/blob/main/external_packages/fjcore.hh
JETSCAPE/blob/main/external_packages/fjcore.cc