Analysis Software: g4exampledetector/blob/master/template/macros/Fun4All_G4_MyDetector.C File Reference
Fun4All_G4_MyDetector.C File Reference
#include <mydetector/MyDetectorSubsystem.h>
#include <g4detectors/PHG4DetectorSubsystem.h>
#include <g4histos/G4HitNtuple.h>
#include <g4main/PHG4ParticleGenerator.h>
#include <g4main/PHG4ParticleGeneratorBase.h>
#include <g4main/PHG4ParticleGun.h>
#include <g4main/PHG4Reco.h>
#include <g4main/PHG4SimpleEventGenerator.h>
#include <fun4all/Fun4AllDstOutputManager.h>
#include <fun4all/Fun4AllDummyInputManager.h>
#include <fun4all/Fun4AllInputManager.h>
#include <fun4all/Fun4AllOutputManager.h>
#include <fun4all/Fun4AllServer.h>
#include <fun4all/SubsysReco.h>
#include <phool/recoConsts.h>
Macros
#define MACRO_FUN4ALLG4MYDETECTOR_C
Functions
void Fun4All_G4_MyDetector (int nEvents=10000)
Macro Definition Documentation
#define MACRO_FUN4ALLG4MYDETECTOR_C
Definition at line 2 of file Fun4All_G4_MyDetector.C.
View newest version in sPHENIX GitHub at line 2 of file Fun4All_G4_MyDetector.C
Function Documentation
void Fun4All_G4_MyDetector (int nEvents = 10000)
Definition at line 31 of file Fun4All_G4_MyDetector.C.
View newest version in sPHENIX GitHub at line 31 of file Fun4All_G4_MyDetector.C
References G4HitNtuple::AddNode(), Fun4AllServer::End(), gen(), in, recoConsts::instance(), Fun4AllServer::instance(), Fun4AllServer::registerInputManager(), Fun4AllServer::registerSubsystem(), PHG4Reco::registerSubsystem(), Fun4AllServer::run(), PHG4Reco::save_DST_geometry(), PHG4ParticleGenerator::set_eta_range(), PHG4Reco::set_field(), PHG4ParticleGeneratorBase::set_mom(), PHG4ParticleGenerator::set_mom_range(), PHG4ParticleGeneratorBase::set_name(), PHG4ParticleGenerator::set_phi_range(), PHG4ParticleGeneratorBase::set_vtx(), and PHG4ParticleGenerator::set_z_range().