Analysis Software: analysis/blob/master/TPC/DAQ/macros/DrawTPCIntegratedCharge.C File Reference
DrawTPCIntegratedCharge.C File Reference
#include <TFile.h>
#include <TGraphAsymmErrors.h>
#include <TGraphErrors.h>
#include <TH2.h>
#include <TLatex.h>
#include <TLegend.h>
#include <TString.h>
#include <TTree.h>
#include <cassert>
#include <cmath>
#include "SaveCanvas.C"
#include "sPhenixStyle.C"
Functions
void DrawTPCIntegratedCharge (const TString infile="/sphenix/user/jinhuang/TPC/Multiplicity/AuAu200MB_170kHz_Iter2/AuAu200MB_170kHz_Iter2_SUM.xml_TPCIntegratedCharge.root", const TString disc="Au+Au MB Triggered + 170 kHz collision")
void ChargePerLayer (vector< int > layers)
void Check ()
Variables
TFile * _file0 = NULL
TString description
Function Documentation
void ChargePerLayer (vector< int > layers)
Definition at line 48 of file DrawTPCIntegratedCharge.C.
View newest version in sPHENIX GitHub at line 48 of file DrawTPCIntegratedCharge.C
References _file0, assert, color, description, Acts::UnitConstants::e, i, ambiguity_solver_full_chain::idx, layer, leg, merge_hashes::p, and SaveCanvas().
Referenced by DrawTPCIntegratedCharge().
void Check ()
Definition at line 147 of file DrawTPCIntegratedCharge.C.
View newest version in sPHENIX GitHub at line 147 of file DrawTPCIntegratedCharge.C
References _file0, assert, hNormalization, ambiguity_solver_full_chain::idx, merge_hashes::p, and SaveCanvas().
void DrawTPCIntegratedCharge (const TString infile = "/sphenix/user/jinhuang/TPC/Multiplicity/AuAu200MB_170kHz_Iter2/AuAu200MB_170kHz_Iter2_SUM.xml_TPCIntegratedCharge.root", const TString disc = "Au+Au MB Triggered + 170 kHz collision")
Definition at line 18 of file DrawTPCIntegratedCharge.C.
View newest version in sPHENIX GitHub at line 18 of file DrawTPCIntegratedCharge.C
References _file0, assert, ChargePerLayer(), Check(), description, infile, and SetsPhenixStyle().
Variable Documentation
TFile* _file0 = NULL
Definition at line 15 of file DrawTPCIntegratedCharge.C.
View newest version in sPHENIX GitHub at line 15 of file DrawTPCIntegratedCharge.C
TString description
Definition at line 16 of file DrawTPCIntegratedCharge.C.
View newest version in sPHENIX GitHub at line 16 of file DrawTPCIntegratedCharge.C