Analysis Software: ActsExamples::SeedingOrthogonalAlgorithm Exception Reference
ActsExamples::SeedingOrthogonalAlgorithm Exception Reference final
Construct track seeds from space points.
#include <acts/blob/sPHENIX/Examples/Algorithms/TrackFinding/include/ActsExamples/TrackFinding/SeedingOrthogonalAlgorithm.hpp>
Classes
struct Config
Public Member Functions
SeedingOrthogonalAlgorithm (Config cfg, Acts::Logging::Level lvl)
ProcessCode execute (const AlgorithmContext &ctx) const override
const Config & config () const
Const access to the config.
Public Member Functions inherited from ActsExamples::IAlgorithm
IAlgorithm (std::string name, Acts::Logging::Level level=Acts::Logging::INFO)
std::string name () const override
The algorithm name.
ProcessCode internalExecute (const AlgorithmContext &context) final
ProcessCode initialize () override
Initialize the algorithm.
ProcessCode finalize () override
Finalize the algorithm.
Private Member Functions
void printOptions () const
template<typename sp >
void printConfig () const
Private Attributes
Config m_cfg
Acts::SeedFinderOrthogonal
< SimSpacePoint > m_finder
std::vector< std::unique_ptr
< ReadDataHandle
< SimSpacePointContainer > > > m_inputSpacePoints {}
WriteDataHandle< SimSeedContainer > m_outputSeeds {this, "OutputSeeds"}
Additional Inherited Members
Protected Member Functions inherited from ActsExamples::IAlgorithm
const Acts::Logger & logger () const
Detailed Description
Construct track seeds from space points.
Definition at line 33 of file SeedingOrthogonalAlgorithm.hpp.
View newest version in sPHENIX GitHub at line 33 of file SeedingOrthogonalAlgorithm.hpp
Constructor & Destructor Documentation
ActsExamples::SeedingOrthogonalAlgorithm::SeedingOrthogonalAlgorithm (Config cfg, Acts::Logging::Level lvl)
Construct the seeding algorithm.
Parameters
cfg is the algorithm configuration
lvl is the logging level
Definition at line 26 of file SeedingOrthogonalAlgorithm.cpp.
View newest version in sPHENIX GitHub at line 26 of file SeedingOrthogonalAlgorithm.cpp
References Acts::SeedFinderOrthogonalConfig< SpacePoint >::calculateDerivedQuantities(), Acts::SeedFinderOptions::calculateDerivedQuantities(), ActsExamples::WriteDataHandle< T >::initialize(), ActsExamples::SeedingOrthogonalAlgorithm::Config::inputSpacePoints, m_cfg, m_finder, m_inputSpacePoints, m_outputSeeds, Acts::SeedFilterConfig::maxSeedsPerSpM, Acts::SeedFinderOrthogonalConfig< SpacePoint >::maxSeedsPerSpM, ActsExamples::SeedingOrthogonalAlgorithm::Config::outputSeeds, printOptions(), Acts::SeedFinderOrthogonalConfig< SpacePoint >::seedFilter, ActsExamples::SeedingOrthogonalAlgorithm::Config::seedFilterConfig, ActsExamples::SeedingOrthogonalAlgorithm::Config::seedFinderConfig, ActsExamples::SeedingOrthogonalAlgorithm::Config::seedFinderOptions, to_string(), Acts::SeedFilterConfig::toInternalUnits(), Acts::SeedFinderOrthogonalConfig< SpacePoint >::toInternalUnits(), and Acts::SeedFinderOptions::toInternalUnits().
Member Function Documentation
const Config& ActsExamples::SeedingOrthogonalAlgorithm::config () const inline
Const access to the config.
Definition at line 64 of file SeedingOrthogonalAlgorithm.hpp.
View newest version in sPHENIX GitHub at line 64 of file SeedingOrthogonalAlgorithm.hpp
References m_cfg.
ActsExamples::ProcessCode ActsExamples::SeedingOrthogonalAlgorithm::execute (const AlgorithmContext & ctx) const override virtual
Run the seeding algorithm.
Parameters
txt is the algorithm context with event information
Returns
a process code indication success or failure
Implements ActsExamples::IAlgorithm.
Definition at line 75 of file SeedingOrthogonalAlgorithm.cpp.
View newest version in sPHENIX GitHub at line 75 of file SeedingOrthogonalAlgorithm.cpp
References ACTS_DEBUG, Acts::SeedFinderOrthogonal< external_spacepoint_t >::createSeeds(), m_cfg(), testing::internal::move(), position, SUCCESS, ActsExamples::SimSpacePoint::varianceR(), ActsExamples::SimSpacePoint::varianceZ(), ActsExamples::SimSpacePoint::x(), ActsExamples::SimSpacePoint::y(), and ActsExamples::SimSpacePoint::z().
template<typename sp > void ActsExamples::SeedingOrthogonalAlgorithm::printConfig () const private
Definition at line 120 of file SeedingOrthogonalAlgorithm.cpp.
View newest version in sPHENIX GitHub at line 120 of file SeedingOrthogonalAlgorithm.cpp
References ACTS_DEBUG, and m_cfg().
void ActsExamples::SeedingOrthogonalAlgorithm::printOptions () const private
Definition at line 106 of file SeedingOrthogonalAlgorithm.cpp.
View newest version in sPHENIX GitHub at line 106 of file SeedingOrthogonalAlgorithm.cpp
References ACTS_DEBUG, and m_cfg().
Referenced by SeedingOrthogonalAlgorithm().
Member Data Documentation
Config ActsExamples::SeedingOrthogonalAlgorithm::m_cfg private
Definition at line 67 of file SeedingOrthogonalAlgorithm.hpp.
View newest version in sPHENIX GitHub at line 67 of file SeedingOrthogonalAlgorithm.hpp
Referenced by config(), and SeedingOrthogonalAlgorithm().
Acts::SeedFinderOrthogonal<SimSpacePoint> ActsExamples::SeedingOrthogonalAlgorithm::m_finder private
Definition at line 68 of file SeedingOrthogonalAlgorithm.hpp.
View newest version in sPHENIX GitHub at line 68 of file SeedingOrthogonalAlgorithm.hpp
Referenced by SeedingOrthogonalAlgorithm().
std::vector<std::unique_ptr<ReadDataHandle<SimSpacePointContainer> > > ActsExamples::SeedingOrthogonalAlgorithm::m_inputSpacePoints {} private
Definition at line 71 of file SeedingOrthogonalAlgorithm.hpp.
View newest version in sPHENIX GitHub at line 71 of file SeedingOrthogonalAlgorithm.hpp
Referenced by SeedingOrthogonalAlgorithm().
WriteDataHandle<SimSeedContainer> ActsExamples::SeedingOrthogonalAlgorithm::m_outputSeeds {this, "OutputSeeds"} private
Definition at line 73 of file SeedingOrthogonalAlgorithm.hpp.
View newest version in sPHENIX GitHub at line 73 of file SeedingOrthogonalAlgorithm.hpp
Referenced by SeedingOrthogonalAlgorithm().
The documentation for this exception was generated from the following files:
acts/blob/sPHENIX/Examples/Algorithms/TrackFinding/include/ActsExamples/TrackFinding/SeedingOrthogonalAlgorithm.hpp
acts/blob/sPHENIX/Examples/Algorithms/TrackFinding/src/SeedingOrthogonalAlgorithm.cpp