Analysis Software: analysis/blob/master/JS-Jet/FastJetMedianBkg/src_JetMedianTree/macro/Fun4All_RhoFluct.C File Reference
Fun4All_RhoFluct.C File Reference
#include <fun4all/Fun4AllDstInputManager.h>
#include <fun4all/Fun4AllInputManager.h>
#include <fun4all/Fun4AllServer.h>
#include <fun4all/SubsysReco.h>
#include <g4centrality/PHG4CentralityReco.h>
#include <jetbase/FastJetAlgo.h>
#include <jetbase/JetReco.h>
#include <jetbase/TowerJetInput.h>
#include <g4jets/TruthJetInput.h>
#include <jetbackground/FastJetAlgoSub.h>
#include <fun4all/PHTFileServer.h>
#include <jetbackground/RetowerCEMC.h>
#include <HIJetReco.C>
#include <fastjetmedianbkg/RhoFluct.h>
#include <fastjetmedianbkg/PrintTowers.h>
Macros
#define MACRO_FUN4ALLJETANA_C
Functions
void Fun4All_RhoFluct (const int nevnt=10, const float jet_R=0.4, const string &out_name="test.root", const string &list_calo_cluster="", const string &list_bbc="", const string &list_global="", const int verbosity=0)
Macro Definition Documentation
#define MACRO_FUN4ALLJETANA_C
Definition at line 2 of file Fun4All_RhoFluct.C.
View newest version in sPHENIX GitHub at line 2 of file Fun4All_RhoFluct.C
Function Documentation
void Fun4All_RhoFluct (const int nevnt = 10, const float jet_R = 0.4, const string & out_name = "test.root", const string & list_calo_cluster = "", const string & list_bbc = "", const string & list_global = "", const int verbosity = 0)
Definition at line 31 of file Fun4All_RhoFluct.C.
View newest version in sPHENIX GitHub at line 31 of file Fun4All_RhoFluct.C
References RhoFluct::add_input_rhoA(), RhoFluct::add_input_Sub1(), Fun4AllInputManager::AddListFile(), Jet::CEMC_TOWER_RETOWER, Jet::CEMC_TOWERINFO_SUB1, Fun4AllServer::End(), PHG4CentralityReco::GetCalibrationParameters(), Jet::HCALIN_TOWER, Jet::HCALIN_TOWERINFO_SUB1, Jet::HCALOUT_TOWER, Jet::HCALOUT_TOWERINFO_SUB1, HIJetReco(), Enable::HIJETS_TRUTH, Fun4AllServer::instance(), PHParameters::ReadFromFile(), Fun4AllServer::registerInputManager(), Fun4AllServer::registerSubsystem(), Fun4AllServer::run(), and Fun4AllBase::Verbosity().