Analysis Software: ActsFatras::PDGtoG4Converter Class Reference
ActsFatras::PDGtoG4Converter Class Reference
This class converts a PDG ID into a corresponding Geant4 particle.
#include <acts/blob/sPHENIX/Fatras/Geant4/include/ActsFatras/Geant4/PDGtoG4Converter.hpp>
Public Member Functions
PDGtoG4Converter ()
Constructor.
G4ParticleDefinition * getParticleDefinition (Acts::PdgParticle pdgCode) const
Private Member Functions
void fillPredefinedParticles ()
Fills the internal lookup with PDG ids and their Geant4 particles.
void addParticle (G4ParticleDefinition *pDef)
Private Attributes
std::unordered_map
< Acts::PdgParticle,
G4ParticleDefinition * > m_pdgG4ParticleMap
The internal storage consisting of PDG ID and the Geant4 particle.
Detailed Description
This class converts a PDG ID into a corresponding Geant4 particle.
Definition at line 19 of file PDGtoG4Converter.hpp.
View newest version in sPHENIX GitHub at line 19 of file PDGtoG4Converter.hpp
Constructor & Destructor Documentation
ActsFatras::PDGtoG4Converter::PDGtoG4Converter ()
Constructor.
Fill the storage
Definition at line 17 of file PDGtoG4Converter.cpp.
View newest version in sPHENIX GitHub at line 17 of file PDGtoG4Converter.cpp
References fillPredefinedParticles().
Member Function Documentation
void ActsFatras::PDGtoG4Converter::addParticle (G4ParticleDefinition * pDef) private
Add a certain Particle to the internal lookup.
Parameters
[in] pDef The Geant4 particle that will be added
Definition at line 136 of file PDGtoG4Converter.cpp.
View newest version in sPHENIX GitHub at line 136 of file PDGtoG4Converter.cpp
void ActsFatras::PDGtoG4Converter::fillPredefinedParticles () private
Fills the internal lookup with PDG ids and their Geant4 particles.
Definition at line 43 of file PDGtoG4Converter.cpp.
View newest version in sPHENIX GitHub at line 43 of file PDGtoG4Converter.cpp
References ActsExamples::HepMC3Event::addParticle().
Referenced by PDGtoG4Converter().
G4ParticleDefinition * ActsFatras::PDGtoG4Converter::getParticleDefinition (Acts::PdgParticle pdgCode) const
Convert a PDG ID into the corresponding Geant4 particle.
Parameters
[in] pdgCode The PDG ID
Returns
Pointer to the Geant4 particle
Definition at line 22 of file PDGtoG4Converter.cpp.
View newest version in sPHENIX GitHub at line 22 of file PDGtoG4Converter.cpp
References it, and Acts::makeAbsolutePdgParticle().
Referenced by ActsFatras::Geant4Decay::generateProperTimeLimit().
Member Data Documentation
std::unordered_map<Acts::PdgParticle, G4ParticleDefinition*> ActsFatras::PDGtoG4Converter::m_pdgG4ParticleMap private
The internal storage consisting of PDG ID and the Geant4 particle.
Definition at line 42 of file PDGtoG4Converter.hpp.
View newest version in sPHENIX GitHub at line 42 of file PDGtoG4Converter.hpp
The documentation for this class was generated from the following files:
acts/blob/sPHENIX/Fatras/Geant4/include/ActsFatras/Geant4/PDGtoG4Converter.hpp
acts/blob/sPHENIX/Fatras/Geant4/src/PDGtoG4Converter.cpp