Analysis Software: Acts::VectorHelpers Namespace Reference
Acts::VectorHelpers Namespace Reference
Namespaces
namespace detail
Functions
template<typename Derived >
double phi (const Eigen::MatrixBase< Derived > &v) noexcept
template<typename T , std::enable_if_t< detail::has_phi_method< T >::value, int > = 0>
double phi (const T &v) noexcept
template<typename Derived >
double perp (const Eigen::MatrixBase< Derived > &v) noexcept
template<typename Derived >
double theta (const Eigen::MatrixBase< Derived > &v) noexcept
template<typename Derived >
double eta (const Eigen::MatrixBase< Derived > &v) noexcept
double cast (const Vector3D &position, BinningValue bval)
ActsMatrixD< 3, 3 > cross (const ActsMatrixD< 3, 3 > &m, const Vector3D &v)
Calculates column-wise cross products of a matrix and a vector and stores the result column-wise in a matrix.
auto position (const Vector4D &pos4)
Access the three-position components in a four-position vector.
auto position (const FreeVector &params)
Access the three-position components in a free parameters vector.
template<typename vector3_t >
auto makeVector4 (const Eigen::MatrixBase< vector3_t > &vec3, typename vector3_t::Scalar w) -> Eigen::Matrix< typename vector3_t::Scalar, 4, 1 >
Construct a four-vector from a three-vector and scalar fourth component.
Function Documentation
double Acts::VectorHelpers::cast (const Vector3D & position, BinningValue bval) inline
Helper method to extract the binning value from a 3D vector.
For this method a 3D vector is required to guarantee all potential binning values.
Definition at line 154 of file Helpers.hpp.
View newest version in sPHENIX GitHub at line 154 of file Helpers.hpp
References assert, Acts::binEta, Acts::binH, Acts::binMag, Acts::binPhi, Acts::binR, Acts::binRPhi, Acts::binX, Acts::binY, Acts::binZ, eta(), perp(), phi(), and theta().
Referenced by Acts::GeometryObject::binningPositionValue(), Acts::Extent::check(), and Acts::TGeoParser::select().
ActsMatrixD<3, 3> Acts::VectorHelpers::cross (const ActsMatrixD< 3, 3 > & m, const Vector3D & v) inline
Calculates column-wise cross products of a matrix and a vector and stores the result column-wise in a matrix.
Parameters
[in] m Matrix that will be used for cross products
[in] v Vector for cross products
Returns
Constructed matrix
Definition at line 186 of file Helpers.hpp.
View newest version in sPHENIX GitHub at line 186 of file Helpers.hpp
References r.
Referenced by CylindricalHough::addHits(), Acts::Test::BOOST_AUTO_TEST_CASE(), HelixHoughFuncs_v1::calculate_phi_range(), Acts::Frustum< value_t, DIM, SIDES >::draw(), kdfinder::Helix< T >::geometricSignedDistance(), PHHepMCGenHelper::HepMC2Lab_boost_rotation_translation(), Acts::LineSurface::initJacobianToGlobal(), Acts::DefaultExtension::k(), Acts::DenseEnvironmentExtension::k(), main(), Acts::Frustum< value_t, DIM, SIDES >::svg(), Acts::DefaultExtension::transportMatrix(), and Acts::DenseEnvironmentExtension::transportMatrix().
template<typename Derived > double Acts::VectorHelpers::eta (const Eigen::MatrixBase< Derived > & v) noexcept
Calculate the pseudorapidity for a vector.
Template Parameters
Derived Eigen derived concrete type
Parameters
v Any vector like Eigen type, static or dynamic
Note
Will static assert that the number of rows of v is at least 3, or in case of dynamic size, will abort execution if that is not the case.
Returns
The pseudorapidity value
Definition at line 134 of file Helpers.hpp.
View newest version in sPHENIX GitHub at line 134 of file Helpers.hpp
References v.
Referenced by LazyTiling9Alt::_initialise_tiles(), LazyTiling9::_initialise_tiles(), LazyTiling25::_initialise_tiles(), AddFlowToParent(), analyzeSignal(), Acts::Test::BOOST_AUTO_TEST_CASE(), BOOST_DATA_TEST_CASE(), cast(), ccbb(), PHActsSiliconSeeding::circleFitSeed(), ConstructGeometry(), PHG4InnerHcalDetector::ConstructHcalSingleScintillators(), PHG4OuterHcalDetector::ConstructHcalSingleScintillators(), create_pythia_dummy(), EMCalLikelihood::do_ganging(), Martini::DoEnergyLoss(), ColoredHadronization::DoHadronization(), DrawEcal_BlockCalibration(), dvcs_plot(), eic_sphenix_test_smearing(), eic_unsmeared_eta_p(), eicsmear_check_calorimeter(), eicsmear_check_tracking(), EMCalCalib::eval_photon_proj(), EMCalAna::eval_trk_proj(), QAG4SimulationCalorimeterSum::eval_trk_proj(), ActsExamples::PrintParticles::execute(), ActsExamples::TrackSelector::execute(), ActsExamples::TruthSeedSelector::execute(), ActsExamples::ParticleSelector::execute(), ActsExamples::EffPlotTool::fill(), ActsExamples::DuplicationPlotTool::fill(), ActsExamples::TrackSummaryPlotTool::fill(), ActsExamples::FakeRatePlotTool::fill(), ActsExamples::ResPlotTool::fill(), JetEvaluator::fillOutputNtuples(), JetEnergies::fillOutputNtuples(), SvtxEvaluator::fillOutputNtuples(), CaloEvaluator::fillOutputNtuples(), find_matching_jet(), LeptoquarksReco::FindMinDeltaRCandidate(), fjetResol(), flowAfterburner(), Jetscape::FluidDynamics::FluidDynamics(), fullMaterial(), Fun4All_G4_Prototype3(), Fun4All_G4_Prototype4(), Fun4All_G4_TPC(), ActsExamples::PrimaryGeneratorAction::GeneratePrimaries(), PHG4Utils::get_eta(), PHG4InputFilter::get_eta(), RawTowerGeomv1::get_eta(), RawTowerGeomv4::get_eta(), RawTowerGeomv2::get_eta(), RawTowerGeomv3::get_eta(), PHG4Utils::get_etaphi(), TowerJetInput::get_input(), TruthJetInput::get_input(), Jetscape::EvolutionHistory::GetAtTimeStep(), TrackProjectionTools::getCluster(), getEta(), KFParticleBaseSIMD::GetEta(), GetEvalHisto(), Hydroinfo_MUSIC::getHydroValues(), DVMPHelper::GetParticleReco(), DVMPHelper::GetParticleTruth(), GetQAHisto(), GetResolution(), hijfst_(), TowerBackgroundv1::identify(), RawTowerDeadMapLoader::InitRun(), DISKinematicsReco::InsertCandidateFromCluster(), TrackProjectorPid::is_in_RICH(), likelihood(), Jetscape::PartonShower::load_edge_info_handler(), MachineLearning_CSV(), main(), PHActsTrackProjection::makeCaloSurfacePtrs(), makeV1_BUP2020(), PHCASeeding::MergeSeeds(), momentumDistributions(), Fatras::casts::eta::operator()(), Fatras::casts::absEta::operator()(), Acts::ObjectSorterT< Vector3D >::operator()(), ActsExamples::ParametricParticleGenerator::operator()(), Acts::DistanceSorterT< T >::operator()(), Plot_FastTrack_Efficiency(), Plot_Hit_Count(), plotbg(), plotembed_vscent(), printHits(), HFFastSim::process_D02PiK(), PHG4InputFilter::process_event(), PHG4ParticleGenerator::process_event(), PHG4ParticleGeneratorD0::process_event(), TrackingPerformanceCheck::process_event(), RecoInfoExport::process_event(), PHHepMCParticleSelectorDecayProductChain::process_event(), RawTowerCalibration::process_event(), RawTowerDigitizer::process_event(), G4CellNtuple::process_event(), PHG4ParticleGeneratorVectorMeson::process_event(), PHG4SimpleEventGenerator::process_event(), G4TowerNtuple::process_event(), Quarkonia2LeptonsMC::process_event(), SubtractTowersCS::process_event(), SubtractTowers::process_event(), TowerTiming::process_event(), RetowerCEMC::process_event(), DetermineTowerBackground::process_event(), HFMLTriggerHepMCTrigger::process_event(), DirectPhotonPythia::process_event(), TPCDataStreamEmulator::process_event(), PJTranslator::process_event(), PHGenFitTrackProjection::process_event(), LiteCaloEval::process_event(), TPCMLDataInterface::process_event(), RawTowerCombiner::process_event(), sPHAnalysis::process_event_hepmc(), sPHAnalysis::process_event_test(), HFFastSim::process_Lc2pPiK(), CaloAna::process_towers(), ActsExamples::Options::readParticleGunOptions(), VtxRegressor::regress(), PHFlowJetMaker::run_particle_flow(), CaloTriggerInfov1::set_best2_EMCal_4x4_eta(), CaloTriggerInfov1::set_best_EMCal_2x2_eta(), CaloTriggerInfov1::set_best_EMCal_4x4_eta(), CaloTriggerInfov1::set_best_FullCalo_0p2x0p2_eta(), CaloTriggerInfov1::set_best_FullCalo_0p4x0p4_eta(), CaloTriggerInfov1::set_best_FullCalo_0p6x0p6_eta(), CaloTriggerInfov1::set_best_FullCalo_0p8x0p8_eta(), CaloTriggerInfov1::set_best_FullCalo_1p0x1p0_eta(), PHG4Reco::set_rapidity_coverage(), PHSartreParticleTrigger::SetAbsEtaHigh(), PHPy8ParticleTrigger::SetAbsEtaHigh(), PHPy6ParticleTrigger::SetAbsEtaHigh(), PHSartreParticleTrigger::SetAbsEtaLow(), PHPy8ParticleTrigger::SetAbsEtaLow(), PHPy6ParticleTrigger::SetAbsEtaLow(), PHSartreParticleTrigger::SetEtaHigh(), PHPy8ParticleTrigger::SetEtaHigh(), PHPy6ParticleTrigger::SetEtaHigh(), PHSartreParticleTrigger::SetEtaLow(), PHPy8ParticleTrigger::SetEtaLow(), PHPy6ParticleTrigger::SetEtaLow(), Proto3ShowerCalib::Eval_Cluster::setfmods(), PHG4Utils::SetPseudoRapidityCoverage(), TrackParametrization(), TreeMaker::UseFastJet(), Acts::BinningData::value(), ActsEvaluator::visitTrackStates(), VtxRegressor::VtxRegressor(), ActsExamples::RootParticleWriter::writeT(), ActsExamples::RootTrajectoryWriter::writeT(), and ActsExamples::RootMaterialTrackWriter::writeT().
template<typename vector3_t > auto Acts::VectorHelpers::makeVector4 (const Eigen::MatrixBase< vector3_t > & vec3, typename vector3_t::Scalar w) -> Eigen::Matrix<typename vector3_t::Scalar, 4, 1> inline
Construct a four-vector from a three-vector and scalar fourth component.
Definition at line 207 of file Helpers.hpp.
View newest version in sPHENIX GitHub at line 207 of file Helpers.hpp
References Acts::ePos0, Acts::ePos1, Acts::ePos2, and Acts::eTime.
Referenced by Acts::Test::BOOST_AUTO_TEST_CASE(), Acts::Test::BOOST_DATA_TEST_CASE(), Acts::VolumeMaterialMapper::mapMaterialTrack(), Acts::SurfaceMaterialMapper::mapMaterialTrack(), and Acts::EventDataView3DTest::testMultiTrajectory().
template<typename Derived > double Acts::VectorHelpers::perp (const Eigen::MatrixBase< Derived > & v) noexcept
Calculate radius in the transverse (xy) plane of a vector
Template Parameters
Derived Eigen derived concrete type
Parameters
v Any vector like Eigen type, static or dynamic
Note
Will static assert that the number of rows of v is at least 2, or in case of dynamic size, will abort execution if that is not the case.
Returns
The transverse radius value.
Definition at line 87 of file Helpers.hpp.
View newest version in sPHENIX GitHub at line 87 of file Helpers.hpp
References v.
Referenced by Acts::Test::BOOST_AUTO_TEST_CASE(), Acts::Test::BOOST_DATA_TEST_CASE(), Acts::Test::BOOST_FIXTURE_TEST_CASE(), cast(), Acts::LayerCreator::checkBinning(), PHG4InnerHcalDetector::ConstructScintillatorBox(), PHG4OuterHcalDetector::ConstructScintillatorBox(), PHG4InnerHcalDetector::ConstructSteelPlate(), PHG4OuterHcalDetector::ConstructSteelPlate(), Acts::detail::PointwiseMaterialInteraction::covarianceContributions(), genfit::MeasurementCreator::create(), Acts::SurfaceArrayCreator::createVariableAxis(), Fatras::Test::Particle::energyLoss(), ActsExamples::TruthSeedSelector::execute(), ActsExamples::ParticleSelector::execute(), Acts::fieldMapperRZ(), ActsExamples::DuplicationPlotTool::fill(), ActsExamples::TrackSummaryPlotTool::fill(), ActsExamples::FakeRatePlotTool::fill(), ActsExamples::ResPlotTool::fill(), FastJetAlgoSub::get_jets(), FastJetAlgo::get_jets(), Acts::SolenoidBField::getField(), Acts::ConeSurface::globalToLocal(), Acts::CylinderSurface::globalToLocal(), Acts::LineSurface::globalToLocal(), Acts::globalToLocalFromBin(), Acts::CutoutCylinderVolumeBounds::inside(), Acts::ConeVolumeBounds::inside(), Acts::CylinderVolumeBounds::inside(), Acts::CylinderBounds::inside3D(), Acts::SurfaceArrayCreator::isSurfaceEquivalent(), Acts::ConeSurface::localCartesianToBoundLocalDerivative(), Acts::CylinderSurface::localCartesianToBoundLocalDerivative(), main(), Acts::materialMapperRZ(), Acts::ObjectSorterT< Vector3D >::operator()(), Fatras::casts::pT::operator()(), Acts::Test::PerpendicularMeasure::operator()(), Fatras::casts::vR::operator()(), Acts::Test::SurfaceObserver< Surface >::operator()(), Acts::DistanceSorterT< T >::operator()(), PHHepMCParticleSelectorDecayProductChain::process_event(), PseudoJet::pseudorapidity(), ActsExamples::RootBFieldWriter< bfield_t >::run(), Fatras::Test::Particle::scatter(), Acts::solenoidFieldMapper(), Acts::SurfaceArrayCreator::surfaceArrayOnDisc(), Fatras::Test::Particle::update(), Acts::BinningData::value(), ActsExamples::RootParticleWriter::writeT(), and ActsExamples::RootTrajectoryWriter::writeT().
template<typename Derived > double Acts::VectorHelpers::phi (const Eigen::MatrixBase< Derived > & v) noexcept
Calculate phi (transverse plane angle) from compatible Eigen types
Template Parameters
Derived Eigen derived concrete type
Parameters
v Any vector like Eigen type, static or dynamic
Note
Will static assert that the number of rows of v is at least 2, or in case of dynamic size, will abort execution if that is not the case.
Returns
The value of the angle in the transverse plane.
Definition at line 51 of file Helpers.hpp.
View newest version in sPHENIX GitHub at line 51 of file Helpers.hpp
References v.
Referenced by ActsFatras::BOOST_AUTO_TEST_CASE(), Acts::Test::BOOST_AUTO_TEST_CASE(), cast(), Acts::detail::differenceOfClustersChecked(), Acts::EventDataView3D::drawCovarianceAngular(), ActsExamples::PrintParticles::execute(), ActsExamples::ParticleSmearing::execute(), ActsExamples::TruthSeedSelector::execute(), ActsExamples::ParticleSelector::execute(), ActsExamples::ResPlotTool::fill(), Acts::Frustum< value_t, DIM, SIDES >::Frustum(), Acts::globalToLocalFromBin(), Acts::EllipseBounds::inside(), Acts::CutoutCylinderVolumeBounds::inside(), Acts::ConeVolumeBounds::inside(), Acts::CylinderVolumeBounds::inside(), main(), Acts::ObjectSorterT< Vector3D >::operator()(), Fatras::Scattering< formula_t >::operator()(), ActsFatras::BoundParametersSmearer< kParameters >::operator()(), Acts::DistanceSorterT< T >::operator()(), Acts::ConeSurface::pathCorrection(), Acts::AnnulusBounds::stripXYToModulePC(), Acts::Test::CylindricalTrackingGeometry::surfacesCylinder(), Acts::BinningData::value(), Acts::AnnulusBounds::vertices(), and ActsExamples::RootParticleWriter::writeT().
template<typename T , std::enable_if_t< detail::has_phi_method< T >::value, int > = 0> double Acts::VectorHelpers::phi (const T & v) noexcept
Calculate phi (transverse plane angle) from anything implementing a method like phi() returing anything convertible to double.
Template Parameters
T anything that has a phi method
Parameters
v Any type that implements a phi method
Returns
The phi value
Definition at line 76 of file Helpers.hpp.
View newest version in sPHENIX GitHub at line 76 of file Helpers.hpp
References v.
auto Acts::VectorHelpers::position (const Vector4D & pos4) inline
Access the three-position components in a four-position vector.
Definition at line 196 of file Helpers.hpp.
View newest version in sPHENIX GitHub at line 196 of file Helpers.hpp
References Acts::ePos0.
Referenced by Acts::Test::BOOST_AUTO_TEST_CASE(), and Acts::Vertex< input_track_t >::position().
auto Acts::VectorHelpers::position (const FreeVector & params) inline
Access the three-position components in a free parameters vector.
Definition at line 201 of file Helpers.hpp.
View newest version in sPHENIX GitHub at line 201 of file Helpers.hpp
References Acts::eFreePos0.
template<typename Derived > double Acts::VectorHelpers::theta (const Eigen::MatrixBase< Derived > & v) noexcept
Calculate the theta angle (longitudinal w.r.t. z axis) of a vector
Template Parameters
Derived Eigen derived concrete type
Parameters
v Any vector like Eigen type, static or dynamic
Note
Will static assert that the number of rows of v is at least 3, or in case of dynamic size, will abort execution if that is not the case.
Returns
The theta value
Definition at line 111 of file Helpers.hpp.
View newest version in sPHENIX GitHub at line 111 of file Helpers.hpp
References v.
Referenced by Acts::Test::BOOST_AUTO_TEST_CASE(), ActsFatras::BOOST_AUTO_TEST_CASE(), cast(), Acts::detail::differenceOfClustersChecked(), Acts::EventDataView3D::drawCovarianceAngular(), ActsExamples::ParticleSmearing::execute(), ActsExamples::ResPlotTool::fill(), Fatras::Scattering< formula_t >::operator()(), and ActsFatras::BoundParametersSmearer< kParameters >::operator()().