Analysis Software: Acts::SourceLink Exception Reference
Acts::SourceLink Exception Reference final
#include <acts/blob/sPHENIX/Core/include/Acts/EventData/SourceLink.hpp>
Public Member Functions
SourceLink (const SourceLink &other)=default
SourceLink (SourceLink &&other)=default
SourceLink & operator= (const SourceLink &other)=default
SourceLink & operator= (SourceLink &&other)=default
template<typename T , typename = std::enable_if_t< !std::is_same_v<std::decay_t<T>, SourceLink>>>
SourceLink (T &&upstream)
template<typename T >
T & get ()
template<typename T >
const T & get () const
Private Types
using any_type = AnyBase< ACTS_SOURCELINK_SBO_SIZE >
Private Attributes
any_type m_upstream {}
Detailed Description
Definition at line 28 of file SourceLink.hpp.
View newest version in sPHENIX GitHub at line 28 of file SourceLink.hpp
Member Typedef Documentation
using Acts::SourceLink::any_type = AnyBase<ACTS_SOURCELINK_SBO_SIZE> private
Definition at line 29 of file SourceLink.hpp.
View newest version in sPHENIX GitHub at line 29 of file SourceLink.hpp
Constructor & Destructor Documentation
Acts::SourceLink::SourceLink (const SourceLink & other) default
Acts::SourceLink::SourceLink (SourceLink && other) default
template<typename T , typename = std::enable_if_t< !std::is_same_v<std::decay_t<T>, SourceLink>>> Acts::SourceLink::SourceLink (T && upstream) inline explicit
Constructor from concrete sourcelink
Template Parameters
T The source link type
Parameters
upstream The upstream source link to store
Definition at line 42 of file SourceLink.hpp.
View newest version in sPHENIX GitHub at line 42 of file SourceLink.hpp
References m_upstream, testing::internal::move(), and Acts::UnitConstants::T.
Member Function Documentation
template<typename T > T& Acts::SourceLink::get () inline
Concrete source link class getter
Template Parameters
T The source link type to retrieve
Returns
Reference to the stored source link
Definition at line 57 of file SourceLink.hpp.
View newest version in sPHENIX GitHub at line 57 of file SourceLink.hpp
References m_upstream, and Acts::UnitConstants::T.
Referenced by Calibrator::calibrate(), ActsExamples::RefittingCalibrator::calibrate(), ActsExamples::PassThroughCalibrator::calibrate(), Acts::MutablePodioTrackStateContainer::getUncalibratedSourceLink_impl(), ActsExamples::IndexSourceLink::SurfaceAccessor::operator()(), ActsSourceLink::SurfaceAccessor::operator()(), Acts::Test::TestSourceLink::SurfaceAccessor::operator()(), Acts::Test::stripEnds(), ActsExamples::CsvPlanarClusterWriter::writeT(), and ActsExamples::RootPlanarClusterWriter::writeT().
template<typename T > const T& Acts::SourceLink::get () const inline
Concrete source link class getter, const version
Template Parameters
T The source link type to retrieve
Returns
Const reference to the stored source link
Definition at line 65 of file SourceLink.hpp.
View newest version in sPHENIX GitHub at line 65 of file SourceLink.hpp
References m_upstream, and Acts::UnitConstants::T.
SourceLink& Acts::SourceLink::operator= (const SourceLink & other) default
SourceLink& Acts::SourceLink::operator= (SourceLink && other) default
Member Data Documentation
any_type Acts::SourceLink::m_upstream {} private
Definition at line 70 of file SourceLink.hpp.
View newest version in sPHENIX GitHub at line 70 of file SourceLink.hpp
Referenced by get(), and SourceLink().
The documentation for this exception was generated from the following file:
acts/blob/sPHENIX/Core/include/Acts/EventData/SourceLink.hpp