Analysis Software: RawTowerv1 Class Reference
RawTowerv1 Class Reference
#include <coresoftware/blob/master/offline/packages/CaloBase/RawTowerv1.h>
Public Member Functions
RawTowerv1 ()
RawTowerv1 (const RawTower &tower)
RawTowerv1 (RawTowerDefs::keytype id)
RawTowerv1 (const unsigned int ieta, const unsigned int iphi)
RawTowerv1 (const RawTowerDefs::CalorimeterId caloid, const unsigned int ieta, const unsigned int iphi)
~RawTowerv1 () override
void Reset () override
Clear Event.
int isValid () const override
isValid returns non zero if object contains vailid data
void identify (std::ostream &os=std::cout) const override
void set_id (RawTowerDefs::keytype id) override
RawTowerDefs::keytype get_id () const override
int get_bineta () const override
int get_binphi () const override
int get_binl () const override
return layer ID assigned to tower
double get_energy () const override
energy assigned to the tower. Depending on stage of process and DST node name, it could be energy deposition, light yield or calibrated energies
void set_energy (const double e) override
energy assigned to the tower. Depending on stage of process and DST node name, it could be energy deposition, light yield or calibrated energies
float get_time () const override
Time stamp assigned to the tower. Depending on the tower maker, it could be rise time or peak time.
void set_time (const float t) override
Time stamp assigned to the tower. Depending on the tower maker, it could be rise time or peak time.
bool empty_g4cells () const override
size_t size_g4cells () const override
RawTower::CellConstRange get_g4cells () const override
RawTower::CellIterator find_g4cell (CellKeyType id) override
RawTower::CellConstIterator find_g4cell (CellKeyType id) const override
void add_ecell (const CellKeyType g4cellid, const float ecell) override
void clear_g4cells () override
bool empty_g4showers () const override
size_t size_g4showers () const override
RawTower::ShowerConstRange get_g4showers () const override
RawTower::ShowerIterator find_g4shower (int id) override
RawTower::ShowerConstIterator find_g4shower (int id) const override
void add_eshower (const int g4showerid, const float eshower) override
void clear_g4showers () override
Public Member Functions inherited from RawTower
~RawTower () override
virtual void set_key (RawTowerDefs::keytype id)
virtual RawTowerDefs::keytype get_key () const
virtual int get_bintheta () const
virtual int get_column () const
virtual int get_row () const
virtual double get_scint_gammas () const
energy assigned to the tower. Depending on stage of process and DST node name, it could be energy deposition, light yield or calibrated energies
virtual void set_scint_gammas (const double)
scint_gammas assigned to the tower. Depending on stage of process and DST node name, it could be scint_gammas deposition, light yield or calibrated energies
virtual double get_cerenkov_gammas () const
energy assigned to the tower. Depending on stage of process and DST node name, it could be energy deposition, light yield or calibrated energies
virtual void set_cerenkov_gammas (const double)
cerenkov_gammas assigned to the tower. Depending on stage of process and DST node name, it could be cerenkov_gammas deposition, light yield or calibrated energies
virtual bool has_property (const PROPERTY) const
virtual double get_property (const PROPERTY) const
virtual void set_property (const PROPERTY, const double)
Public Member Functions inherited from PHObject
PHObject ()
ctor
~PHObject () override
dtor
virtual PHObject * CloneMe () const
Virtual copy constructor.
virtual PHObject * clone () const final
PHObject * Clone (const char *newname="") const final
void Copy (TObject &object) const final
virtual int Integrate () const
virtual int Integrate (PHObject *)
virtual void CopyFrom (const PHObject *obj)
Protected Attributes
RawTowerDefs::keytype towerid = ~0
double energy = 0.
float time = NAN
CellMap ecells
ShowerMap eshowers
Additional Inherited Members
Public Types inherited from RawTower
enum PROPERTY { prop_scint_gammas = 1, prop_cerenkov_gammas = 2, prop_MAX_NUMBER = UCHAR_MAX }
typedef unsigned long long CellKeyType
key type for cell map which should be consistent with CellKeyType
typedef std::map< CellKeyType,
float > CellMap
typedef CellMap::iterator CellIterator
typedef CellMap::const_iterator CellConstIterator
typedef std::pair
< CellIterator, CellIterator > CellRange
typedef std::pair
< CellConstIterator,
CellConstIterator > CellConstRange
typedef std::map< int, float > ShowerMap
typedef ShowerMap::iterator ShowerIterator
typedef ShowerMap::const_iterator ShowerConstIterator
typedef std::pair
< ShowerIterator,
ShowerIterator > ShowerRange
typedef std::pair
< ShowerConstIterator,
ShowerConstIterator > ShowerConstRange
Static Public Member Functions inherited from RawTower
static const std::string get_property_info (PROPERTY prop_id)
Protected Member Functions inherited from RawTower
RawTower ()
virtual unsigned int get_property_nocheck (const PROPERTY) const
virtual void set_property_nocheck (const PROPERTY, const unsigned int)
Detailed Description
Definition at line 13 of file RawTowerv1.h.
View newest version in sPHENIX GitHub at line 13 of file RawTowerv1.h
Constructor & Destructor Documentation
RawTowerv1::RawTowerv1 () inline
Definition at line 16 of file RawTowerv1.h.
View newest version in sPHENIX GitHub at line 16 of file RawTowerv1.h
RawTowerv1::RawTowerv1 (const RawTower & tower)
Definition at line 8 of file RawTowerv1.cc.
View newest version in sPHENIX GitHub at line 8 of file RawTowerv1.cc
References energy, RawTower::get_energy(), RawTower::get_g4cells(), RawTower::get_g4showers(), RawTower::get_id(), RawTower::get_time(), and Acts::Test::time.
RawTowerv1::RawTowerv1 (RawTowerDefs::keytype id)
Definition at line 31 of file RawTowerv1.cc.
View newest version in sPHENIX GitHub at line 31 of file RawTowerv1.cc
RawTowerv1::RawTowerv1 (const unsigned int ieta, const unsigned int iphi)
Definition at line 36 of file RawTowerv1.cc.
View newest version in sPHENIX GitHub at line 36 of file RawTowerv1.cc
References RawTowerDefs::encode_towerid(), and RawTowerDefs::NONE.
RawTowerv1::RawTowerv1 (const RawTowerDefs::CalorimeterId caloid, const unsigned int ieta, const unsigned int iphi)
Definition at line 41 of file RawTowerv1.cc.
View newest version in sPHENIX GitHub at line 41 of file RawTowerv1.cc
References RawTowerDefs::encode_towerid().
RawTowerv1::~RawTowerv1 () inline override
Definition at line 22 of file RawTowerv1.h.
View newest version in sPHENIX GitHub at line 22 of file RawTowerv1.h
Member Function Documentation
void RawTowerv1::add_ecell (const CellKeyType g4cellid, const float ecell) override virtual
Reimplemented from RawTower.
Definition at line 76 of file RawTowerv1.cc.
View newest version in sPHENIX GitHub at line 76 of file RawTowerv1.cc
References ecells.
void RawTowerv1::add_eshower (const int g4showerid, const float eshower) override virtual
Reimplemented from RawTower.
Definition at line 89 of file RawTowerv1.cc.
View newest version in sPHENIX GitHub at line 89 of file RawTowerv1.cc
References eshowers.
void RawTowerv1::clear_g4cells () inline override virtual
Reimplemented from RawTower.
Definition at line 50 of file RawTowerv1.h.
View newest version in sPHENIX GitHub at line 50 of file RawTowerv1.h
References ecells.
void RawTowerv1::clear_g4showers () inline override virtual
Reimplemented from RawTower.
Definition at line 63 of file RawTowerv1.h.
View newest version in sPHENIX GitHub at line 63 of file RawTowerv1.h
References eshowers.
bool RawTowerv1::empty_g4cells () const inline override virtual
Reimplemented from RawTower.
Definition at line 40 of file RawTowerv1.h.
View newest version in sPHENIX GitHub at line 40 of file RawTowerv1.h
References ecells.
bool RawTowerv1::empty_g4showers () const inline override virtual
Reimplemented from RawTower.
Definition at line 54 of file RawTowerv1.h.
View newest version in sPHENIX GitHub at line 54 of file RawTowerv1.h
References eshowers.
RawTower::CellIterator RawTowerv1::find_g4cell (CellKeyType id) inline override virtual
Reimplemented from RawTower.
Definition at line 46 of file RawTowerv1.h.
View newest version in sPHENIX GitHub at line 46 of file RawTowerv1.h
References ecells.
RawTower::CellConstIterator RawTowerv1::find_g4cell (CellKeyType id) const inline override virtual
Reimplemented from RawTower.
Definition at line 47 of file RawTowerv1.h.
View newest version in sPHENIX GitHub at line 47 of file RawTowerv1.h
References ecells.
RawTower::ShowerIterator RawTowerv1::find_g4shower (int id) inline override virtual
Reimplemented from RawTower.
Definition at line 60 of file RawTowerv1.h.
View newest version in sPHENIX GitHub at line 60 of file RawTowerv1.h
References eshowers.
RawTower::ShowerConstIterator RawTowerv1::find_g4shower (int id) const inline override virtual
Reimplemented from RawTower.
Definition at line 61 of file RawTowerv1.h.
View newest version in sPHENIX GitHub at line 61 of file RawTowerv1.h
References eshowers.
int RawTowerv1::get_bineta () const override virtual
Reimplemented from RawTower.
Definition at line 101 of file RawTowerv1.cc.
View newest version in sPHENIX GitHub at line 101 of file RawTowerv1.cc
References RawTowerDefs::decode_caloid(), RawTowerDefs::decode_index1(), RawTowerDefs::decode_index1v2(), and RawTowerDefs::LFHCAL.
Referenced by identify(), and RawTowerv2::identify().
int RawTowerv1::get_binl () const inline override virtual
return layer ID assigned to tower
Reimplemented from RawTower.
Definition at line 32 of file RawTowerv1.h.
View newest version in sPHENIX GitHub at line 32 of file RawTowerv1.h
References RawTowerDefs::decode_index3v2().
Referenced by identify().
int RawTowerv1::get_binphi () const override virtual
Reimplemented from RawTower.
Definition at line 114 of file RawTowerv1.cc.
View newest version in sPHENIX GitHub at line 114 of file RawTowerv1.cc
References RawTowerDefs::decode_caloid(), RawTowerDefs::decode_index2(), RawTowerDefs::decode_index2v2(), and RawTowerDefs::LFHCAL.
Referenced by identify(), and RawTowerv2::identify().
double RawTowerv1::get_energy () const inline override virtual
energy assigned to the tower. Depending on stage of process and DST node name, it could be energy deposition, light yield or calibrated energies
Reimplemented from RawTower.
Definition at line 33 of file RawTowerv1.h.
View newest version in sPHENIX GitHub at line 33 of file RawTowerv1.h
References energy.
Referenced by identify(), RawTowerv2::identify(), isValid(), and PHG4DSTReader::process_event().
RawTower::CellConstRange RawTowerv1::get_g4cells () const inline override virtual
Reimplemented from RawTower.
Definition at line 42 of file RawTowerv1.h.
View newest version in sPHENIX GitHub at line 42 of file RawTowerv1.h
References ecells.
RawTower::ShowerConstRange RawTowerv1::get_g4showers () const inline override virtual
Reimplemented from RawTower.
Definition at line 56 of file RawTowerv1.h.
View newest version in sPHENIX GitHub at line 56 of file RawTowerv1.h
References eshowers.
RawTowerDefs::keytype RawTowerv1::get_id () const inline override virtual
Reimplemented from RawTower.
Definition at line 29 of file RawTowerv1.h.
View newest version in sPHENIX GitHub at line 29 of file RawTowerv1.h
References towerid.
float RawTowerv1::get_time () const inline override virtual
Time stamp assigned to the tower. Depending on the tower maker, it could be rise time or peak time.
Reimplemented from RawTower.
Definition at line 35 of file RawTowerv1.h.
View newest version in sPHENIX GitHub at line 35 of file RawTowerv1.h
References time.
void RawTowerv1::identify (std::ostream & os = std::cout) const override virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from RawTower.
Reimplemented in RawTowerv2.
Definition at line 60 of file RawTowerv1.cc.
View newest version in sPHENIX GitHub at line 60 of file RawTowerv1.cc
References RawTowerDefs::decode_caloid(), get_bineta(), get_binl(), get_binphi(), get_energy(), and RawTowerDefs::LFHCAL.
int RawTowerv1::isValid () const override virtual
isValid returns non zero if object contains vailid data
Reimplemented from RawTower.
Reimplemented in RawTowerv2.
Definition at line 55 of file RawTowerv1.cc.
View newest version in sPHENIX GitHub at line 55 of file RawTowerv1.cc
References get_energy().
Referenced by RawTowerv2::isValid().
void RawTowerv1::Reset () override virtual
Clear Event.
Reimplemented from RawTower.
Reimplemented in RawTowerv2.
Definition at line 47 of file RawTowerv1.cc.
View newest version in sPHENIX GitHub at line 47 of file RawTowerv1.cc
References ecells, energy, eshowers, and time.
Referenced by RawTowerv2::Reset().
void RawTowerv1::set_energy (const double) inline override virtual
energy assigned to the tower. Depending on stage of process and DST node name, it could be energy deposition, light yield or calibrated energies
Reimplemented from RawTower.
Definition at line 34 of file RawTowerv1.h.
View newest version in sPHENIX GitHub at line 34 of file RawTowerv1.h
References Acts::UnitConstants::e, and energy.
void RawTowerv1::set_id (RawTowerDefs::keytype id) inline override virtual
Reimplemented from RawTower.
Definition at line 28 of file RawTowerv1.h.
View newest version in sPHENIX GitHub at line 28 of file RawTowerv1.h
References train_ambiguity_solver::id.
void RawTowerv1::set_time (const float) inline override virtual
Time stamp assigned to the tower. Depending on the tower maker, it could be rise time or peak time.
Reimplemented from RawTower.
Definition at line 36 of file RawTowerv1.h.
View newest version in sPHENIX GitHub at line 36 of file RawTowerv1.h
References t, and time.
size_t RawTowerv1::size_g4cells () const inline override virtual
Reimplemented from RawTower.
Definition at line 41 of file RawTowerv1.h.
View newest version in sPHENIX GitHub at line 41 of file RawTowerv1.h
References ecells.
size_t RawTowerv1::size_g4showers () const inline override virtual
Reimplemented from RawTower.
Definition at line 55 of file RawTowerv1.h.
View newest version in sPHENIX GitHub at line 55 of file RawTowerv1.h
References eshowers.
Member Data Documentation
CellMap RawTowerv1::ecells protected
Definition at line 75 of file RawTowerv1.h.
View newest version in sPHENIX GitHub at line 75 of file RawTowerv1.h
Referenced by add_ecell(), clear_g4cells(), empty_g4cells(), find_g4cell(), get_g4cells(), Reset(), and size_g4cells().
double RawTowerv1::energy = 0. protected
energy assigned to the tower. Depending on stage of process and DST node name, it could be energy deposition, light yield or calibrated energies
Definition at line 70 of file RawTowerv1.h.
View newest version in sPHENIX GitHub at line 70 of file RawTowerv1.h
Referenced by get_energy(), Reset(), and set_energy().
ShowerMap RawTowerv1::eshowers protected
Definition at line 76 of file RawTowerv1.h.
View newest version in sPHENIX GitHub at line 76 of file RawTowerv1.h
Referenced by add_eshower(), clear_g4showers(), empty_g4showers(), find_g4shower(), get_g4showers(), Reset(), and size_g4showers().
float RawTowerv1::time = NAN protected
Time stamp assigned to the tower. Depending on the tower maker, it could be rise time or peak time.
Definition at line 73 of file RawTowerv1.h.
View newest version in sPHENIX GitHub at line 73 of file RawTowerv1.h
Referenced by get_time(), Reset(), and set_time().
RawTowerDefs::keytype RawTowerv1::towerid = ~0 protected
Definition at line 66 of file RawTowerv1.h.
View newest version in sPHENIX GitHub at line 66 of file RawTowerv1.h
Referenced by get_id().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/CaloBase/RawTowerv1.h
coresoftware/blob/master/offline/packages/CaloBase/RawTowerv1.cc