Analysis Software: ActsFatras::LandauDistribution Class Reference
ActsFatras::LandauDistribution Class Reference
#include <acts/blob/sPHENIX/Fatras/include/ActsFatras/Utilities/LandauDistribution.hpp>
Classes
struct param_type
Parameter struct that contains all distribution parameters.
Public Types
using result_type = double
The type of the generated values.
Public Member Functions
LandauDistribution (double location, double scale)
Construct directly from the distribution parameters.
LandauDistribution (const param_type &cfg)
Construct from a parameter object.
LandauDistribution ()=default
LandauDistribution (const LandauDistribution &)=default
LandauDistribution (LandauDistribution &&)=default
LandauDistribution & operator= (const LandauDistribution &)=default
LandauDistribution & operator= (LandauDistribution &&)=default
void reset ()
Reset any possible internal state. Noop, since there is no internal state.
param_type param () const
Return the currently configured distribution parameters.
void param (const param_type &cfg)
Set the distribution parameters.
result_type min () const
The minimum value the distribution generates.
result_type max () const
The maximum value the distribution generates.
template<typename Generator >
result_type operator() (Generator &generator)
Generate a random number from the configured Landau distribution.
template<typename Generator >
result_type operator() (Generator &generator, const param_type &params)
Generate a random number from the given Landau distribution.
Static Private Member Functions
static double quantile (double z)
Private Attributes
param_type m_cfg
Friends
bool operator== (const LandauDistribution &lhs, const LandauDistribution &rhs)
Provide standard comparison operators.
bool operator!= (const LandauDistribution &lhs, const LandauDistribution &rhs)
Detailed Description
Draw random numbers from a Landau distribution.
Implements the same interface as the standard library distributions.
Definition at line 19 of file LandauDistribution.hpp.
View newest version in sPHENIX GitHub at line 19 of file LandauDistribution.hpp
Member Typedef Documentation
using ActsFatras::LandauDistribution::result_type = double
The type of the generated values.
Definition at line 52 of file LandauDistribution.hpp.
View newest version in sPHENIX GitHub at line 52 of file LandauDistribution.hpp
Constructor & Destructor Documentation
ActsFatras::LandauDistribution::LandauDistribution (double location, double scale) inline
Construct directly from the distribution parameters.
Definition at line 55 of file LandauDistribution.hpp.
View newest version in sPHENIX GitHub at line 55 of file LandauDistribution.hpp
ActsFatras::LandauDistribution::LandauDistribution (const param_type & cfg) inline
Construct from a parameter object.
Definition at line 57 of file LandauDistribution.hpp.
View newest version in sPHENIX GitHub at line 57 of file LandauDistribution.hpp
ActsFatras::LandauDistribution::LandauDistribution () default
ActsFatras::LandauDistribution::LandauDistribution (const LandauDistribution &) default
ActsFatras::LandauDistribution::LandauDistribution (LandauDistribution &&) default
Member Function Documentation
result_type ActsFatras::LandauDistribution::max (void) const inline
The maximum value the distribution generates.
Definition at line 75 of file LandauDistribution.hpp.
View newest version in sPHENIX GitHub at line 75 of file LandauDistribution.hpp
result_type ActsFatras::LandauDistribution::min (void) const inline
The minimum value the distribution generates.
Definition at line 73 of file LandauDistribution.hpp.
View newest version in sPHENIX GitHub at line 73 of file LandauDistribution.hpp
template<typename Generator > result_type ActsFatras::LandauDistribution::operator() (Generator & generator) inline
Generate a random number from the configured Landau distribution.
Definition at line 79 of file LandauDistribution.hpp.
View newest version in sPHENIX GitHub at line 79 of file LandauDistribution.hpp
References Fatras::Test::generator, and m_cfg.
template<typename Generator > result_type ActsFatras::LandauDistribution::operator() (Generator & generator, const param_type & params) inline
Generate a random number from the given Landau distribution.
Definition at line 84 of file LandauDistribution.hpp.
View newest version in sPHENIX GitHub at line 84 of file LandauDistribution.hpp
References ActsFatras::LandauDistribution::param_type::location, quantile(), ActsFatras::LandauDistribution::param_type::scale, and physmon_track_finding_ttbar::z.
LandauDistribution& ActsFatras::LandauDistribution::operator= (const LandauDistribution &) default
LandauDistribution& ActsFatras::LandauDistribution::operator= (LandauDistribution &&) default
param_type ActsFatras::LandauDistribution::param () const inline
Return the currently configured distribution parameters.
Definition at line 68 of file LandauDistribution.hpp.
View newest version in sPHENIX GitHub at line 68 of file LandauDistribution.hpp
References m_cfg.
Referenced by alphas(), converttohepmc(), deriv(), dofistatescat(), doinstatescat(), dokinematics(), generatez(), genevent(), getdeltat(), getinspliti(), getinsudafast(), getinsudakov(), getinsudared(), getmass(), getnewmass(), getpdf(), getpdfxintexact(), getpnorad1(), getqvec(), getspliti(), getsscat(), getsudakov(), gett(), getxsecint(), init(), initpythia(), insudaint(), intpgghigh(), intpgglow(), intpqghigh(), intpqglow(), intpqq(), makebranch(), makecascade(), makeinsplit(), makesplitting(), makestrings_minl(), makestrings_vac(), pdfint(), scatprimfunc(), splitfncint(), and xsecint().
void ActsFatras::LandauDistribution::param (const param_type & cfg) inline
Set the distribution parameters.
Definition at line 70 of file LandauDistribution.hpp.
View newest version in sPHENIX GitHub at line 70 of file LandauDistribution.hpp
References cfg, and m_cfg.
double ActsFatras::LandauDistribution::quantile (double z) static private
Definition at line 13 of file LandauDistribution.cpp.
View newest version in sPHENIX GitHub at line 13 of file LandauDistribution.cpp
References f, i, physmon_ckf_tracking::u, testSigmaEff::v, and physmon_track_finding_ttbar::z.
Referenced by operator()().
void ActsFatras::LandauDistribution::reset () inline
Reset any possible internal state. Noop, since there is no internal state.
Definition at line 66 of file LandauDistribution.hpp.
View newest version in sPHENIX GitHub at line 66 of file LandauDistribution.hpp
Friends And Related Function Documentation
bool operator!= (const LandauDistribution & lhs, const LandauDistribution & rhs) friend
Definition at line 94 of file LandauDistribution.hpp.
View newest version in sPHENIX GitHub at line 94 of file LandauDistribution.hpp
bool operator== (const LandauDistribution & lhs, const LandauDistribution & rhs) friend
Provide standard comparison operators.
Definition at line 90 of file LandauDistribution.hpp.
View newest version in sPHENIX GitHub at line 90 of file LandauDistribution.hpp
Member Data Documentation
param_type ActsFatras::LandauDistribution::m_cfg private
Definition at line 100 of file LandauDistribution.hpp.
View newest version in sPHENIX GitHub at line 100 of file LandauDistribution.hpp
Referenced by operator()(), and param().
The documentation for this class was generated from the following files:
acts/blob/sPHENIX/Fatras/include/ActsFatras/Utilities/LandauDistribution.hpp
acts/blob/sPHENIX/Fatras/src/Utilities/LandauDistribution.cpp