Analysis Software: analysis/blob/master/EMCal-position-dependent-calibration/macro/ana.354/G4Setup_sPHENIX.C File Reference
G4Setup_sPHENIX.C File Reference
#include <GlobalVariables.C>
#include <G4_Bbc.C>
#include <G4_BlackHole.C>
#include <G4_CEmc_Albedo.C>
#include <G4_CEmc_Spacal.C>
#include <G4_EPD.C>
#include <G4_HcalIn_ref.C>
#include <G4_HcalOut_ref.C>
#include <G4_BeamLine.C>
#include <G4_Intt.C>
#include <G4_Magnet.C>
#include <G4_Micromegas.C>
#include <G4_Mvtx.C>
#include <G4_PSTOF.C>
#include <G4_Pipe.C>
#include <G4_PlugDoor.C>
#include <G4_TPC.C>
#include <G4_User.C>
#include <G4_World.C>
#include <G4_ZDC.C>
#include <g4detectors/PHG4CylinderSubsystem.h>
#include <g4eval/PHG4DstCompressReco.h>
#include <g4main/PHG4Reco.h>
#include <g4main/PHG4TruthSubsystem.h>
#include <phfield/PHFieldConfig.h>
#include <g4decayer/EDecayType.hh>
#include <fun4all/Fun4AllDstOutputManager.h>
#include <fun4all/Fun4AllServer.h>
Macros
#define MACRO_G4SETUPSPHENIX_C
Functions
void G4Init ()
int G4Setup ()
void ShowerCompress (int verbosity=0)
void DstCompress (Fun4AllDstOutputManager *out)
Macro Definition Documentation
#define MACRO_G4SETUPSPHENIX_C
Definition at line 2 of file G4Setup_sPHENIX.C.
View newest version in sPHENIX GitHub at line 2 of file G4Setup_sPHENIX.C
Function Documentation
void DstCompress (Fun4AllDstOutputManager * out)
Definition at line 202 of file G4Setup_sPHENIX.C.
View newest version in sPHENIX GitHub at line 202 of file G4Setup_sPHENIX.C
References Fun4AllDstOutputManager::StripNode().
void G4Init ()
Definition at line 43 of file G4Setup_sPHENIX.C.
View newest version in sPHENIX GitHub at line 43 of file G4Setup_sPHENIX.C
References BbcInit(), Enable::BEAMLINE, BeamLineInit(), Enable::BLACKHOLE, BlackHoleInit(), Enable::CEMC, Enable::CEMCALBEDO, CEmcAlbedoInit(), CEmcInit(), Enable::EPD, EPDInit(), Enable::HCALIN, HCalInnerInit(), Enable::HCALOUT, HCalOuterInit(), Enable::INTT, InttInit(), Enable::MAGNET, MagnetFieldInit(), MagnetInit(), Enable::MICROMEGAS, MicromegasInit(), Enable::MVTX, MvtxInit(), Enable::PIPE, PipeInit(), Enable::PLUGDOOR, PlugDoorInit(), Enable::TPC, TPCInit(), Enable::USER, UserInit(), Enable::ZDC, and ZDCInit().
int G4Setup ()
Definition at line 79 of file G4Setup_sPHENIX.C.
View newest version in sPHENIX GitHub at line 79 of file G4Setup_sPHENIX.C
References Bbc(), Enable::BEAMLINE, BeamLineDefineBeamPipe(), BeamLineDefineMagnets(), Enable::BLACKHOLE, BlackHole(), CEmc(), Enable::CEMC, Enable::CEMCALBEDO, CEmcAlbedo(), PHG4Reco::CustomizeEvtGenDecay(), EVTGENDECAYER::DecayFile, G4P6DECAYER::decayType, Enable::EPD, EPD(), PHFieldConfig::Field3DCartesian, Enable::HCALIN, HCalInner(), Enable::HCALOUT, HCalOuter(), Fun4AllServer::instance(), Enable::INTT, Intt(), kAll, PHFieldConfig::kField2D, G4MAGNET::magfield, G4MAGNET::magfield_rescale, Magnet(), Enable::MAGNET, Enable::MICROMEGAS, Micromegas(), Enable::MVTX, Mvtx(), Pipe(), Enable::PIPE, Enable::PLUGDOOR, PlugDoor(), Fun4AllServer::registerSubsystem(), PHG4Reco::registerSubsystem(), PHG4Reco::set_field(), PHG4Reco::set_field_map(), PHG4Reco::set_field_rescale(), PHG4Reco::set_force_decay(), PHG4Reco::set_rapidity_coverage(), g4evalfn::TPC, Enable::TPC, Enable::USER, UserDetector(), WorldInit(), WorldSize(), Enable::ZDC, and ZDCSetup().
void ShowerCompress (int verbosity = 0)
Definition at line 164 of file G4Setup_sPHENIX.C.
View newest version in sPHENIX GitHub at line 164 of file G4Setup_sPHENIX.C
References PHG4DstCompressReco::AddCellContainer(), PHG4DstCompressReco::AddHitContainer(), PHG4DstCompressReco::AddTowerContainer(), Fun4AllServer::instance(), and Fun4AllServer::registerSubsystem().