Analysis Software: RawHitSetContainer Class Reference
RawHitSetContainer Class Reference
#include <coresoftware/blob/master/offline/packages/trackbase/RawHitSetContainer.h>
Public Types
using Map = std::map< TrkrDefs::hitsetkey, RawHitSet * >
using Iterator = Map::iterator
using ConstIterator = Map::const_iterator
using Range = std::pair< Iterator, Iterator >
using ConstRange = std::pair< ConstIterator, ConstIterator >
Public Member Functions
~RawHitSetContainer () override=default
dtir
void Reset () override
PHObject functions.
virtual ConstIterator addHitSet (RawHitSet *)
Add a RawHitSet to the container.
virtual ConstIterator addHitSetSpecifyKey (const TrkrDefs::hitsetkey, RawHitSet *)
virtual void removeHitSet (TrkrDefs::hitsetkey)
preferred removal method, key is currently the hit id
virtual void removeHitSet (RawHitSet *)
inefficent, use key where possible instead
virtual Iterator findOrAddHitSet (TrkrDefs::hitsetkey)
find or add HitSet
virtual ConstRange getHitSets (const TrkrDefs::TrkrId) const
return all HitSets matching a given detid
virtual ConstRange getHitSets (const TrkrDefs::TrkrId trackerid, const uint8_t layer) const
return all HitSets matching a given detid, layer
virtual ConstRange getHitSets () const
return all HitSets
virtual RawHitSet * findHitSet (TrkrDefs::hitsetkey)
return a given HitSet based on its key
virtual unsigned int size () const
Public Member Functions inherited from PHObject
PHObject ()
ctor
~PHObject () override
dtor
virtual PHObject * CloneMe () const
Virtual copy constructor.
virtual PHObject * clone () const final
PHObject * Clone (const char *newname="") const final
void Copy (TObject &object) const final
virtual void identify (std::ostream &os=std::cout) const
virtual int isValid () const
isValid returns non zero if object contains vailid data
virtual int Integrate () const
virtual int Integrate (PHObject *)
virtual void CopyFrom (const PHObject *obj)
Protected Member Functions
RawHitSetContainer ()=default
ctor
Detailed Description
Container for RawHitSet objects
Definition at line 23 of file RawHitSetContainer.h.
View newest version in sPHENIX GitHub at line 23 of file RawHitSetContainer.h
Member Typedef Documentation
using RawHitSetContainer::ConstIterator = Map::const_iterator
Definition at line 29 of file RawHitSetContainer.h.
View newest version in sPHENIX GitHub at line 29 of file RawHitSetContainer.h
using RawHitSetContainer::ConstRange = std::pair<ConstIterator, ConstIterator>
Definition at line 31 of file RawHitSetContainer.h.
View newest version in sPHENIX GitHub at line 31 of file RawHitSetContainer.h
using RawHitSetContainer::Iterator = Map::iterator
Definition at line 28 of file RawHitSetContainer.h.
View newest version in sPHENIX GitHub at line 28 of file RawHitSetContainer.h
using RawHitSetContainer::Map = std::map<TrkrDefs::hitsetkey, RawHitSet *>
Definition at line 27 of file RawHitSetContainer.h.
View newest version in sPHENIX GitHub at line 27 of file RawHitSetContainer.h
using RawHitSetContainer::Range = std::pair<Iterator, Iterator>
Definition at line 30 of file RawHitSetContainer.h.
View newest version in sPHENIX GitHub at line 30 of file RawHitSetContainer.h
Constructor & Destructor Documentation
RawHitSetContainer::~RawHitSetContainer () override default
dtir
RawHitSetContainer::RawHitSetContainer () protected default
ctor
Member Function Documentation
RawHitSetContainer::ConstIterator RawHitSetContainer::addHitSet (RawHitSet *) virtual
Add a RawHitSet to the container.
Reimplemented in RawHitSetContainerv1.
Definition at line 27 of file RawHitSetContainer.cc.
View newest version in sPHENIX GitHub at line 27 of file RawHitSetContainer.cc
RawHitSetContainer::ConstIterator RawHitSetContainer::addHitSetSpecifyKey (const TrkrDefs::hitsetkey , RawHitSet *) virtual
Reimplemented in RawHitSetContainerv1.
Definition at line 31 of file RawHitSetContainer.cc.
View newest version in sPHENIX GitHub at line 31 of file RawHitSetContainer.cc
virtual RawHitSet* RawHitSetContainer::findHitSet (TrkrDefs::hitsetkey) inline virtual
return a given HitSet based on its key
Reimplemented in RawHitSetContainerv1.
Definition at line 65 of file RawHitSetContainer.h.
View newest version in sPHENIX GitHub at line 65 of file RawHitSetContainer.h
RawHitSetContainer::Iterator RawHitSetContainer::findOrAddHitSet (TrkrDefs::hitsetkey) virtual
find or add HitSet
Reimplemented in RawHitSetContainerv1.
Definition at line 35 of file RawHitSetContainer.cc.
View newest version in sPHENIX GitHub at line 35 of file RawHitSetContainer.cc
RawHitSetContainer::ConstRange RawHitSetContainer::getHitSets (const TrkrDefs::TrkrId) const virtual
return all HitSets matching a given detid
Reimplemented in RawHitSetContainerv1.
Definition at line 39 of file RawHitSetContainer.cc.
View newest version in sPHENIX GitHub at line 39 of file RawHitSetContainer.cc
Referenced by InttClusterizer::ClusterLadderCellsRaw(), MvtxClusterizer::ClusterMvtxRaw(), and TpcClusterizer::process_event().
RawHitSetContainer::ConstRange RawHitSetContainer::getHitSets (const TrkrDefs::TrkrId trackerid, const uint8_t layer) const virtual
return all HitSets matching a given detid, layer
Reimplemented in RawHitSetContainerv1.
Definition at line 43 of file RawHitSetContainer.cc.
View newest version in sPHENIX GitHub at line 43 of file RawHitSetContainer.cc
RawHitSetContainer::ConstRange RawHitSetContainer::getHitSets () const virtual
return all HitSets
Reimplemented in RawHitSetContainerv1.
Definition at line 47 of file RawHitSetContainer.cc.
View newest version in sPHENIX GitHub at line 47 of file RawHitSetContainer.cc
virtual void RawHitSetContainer::removeHitSet (TrkrDefs::hitsetkey) inline virtual
preferred removal method, key is currently the hit id
Reimplemented in RawHitSetContainerv1.
Definition at line 45 of file RawHitSetContainer.h.
View newest version in sPHENIX GitHub at line 45 of file RawHitSetContainer.h
virtual void RawHitSetContainer::removeHitSet (RawHitSet *) inline virtual
inefficent, use key where possible instead
Reimplemented in RawHitSetContainerv1.
Definition at line 49 of file RawHitSetContainer.h.
View newest version in sPHENIX GitHub at line 49 of file RawHitSetContainer.h
void RawHitSetContainer::Reset () override virtual
PHObject functions.
Reimplemented from PHObject.
Reimplemented in RawHitSetContainerv1.
Definition at line 20 of file RawHitSetContainer.cc.
View newest version in sPHENIX GitHub at line 20 of file RawHitSetContainer.cc
virtual unsigned int RawHitSetContainer::size (void) const inline virtual
Reimplemented in RawHitSetContainerv1.
Definition at line 68 of file RawHitSetContainer.h.
View newest version in sPHENIX GitHub at line 68 of file RawHitSetContainer.h
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/trackbase/RawHitSetContainer.h
coresoftware/blob/master/offline/packages/trackbase/RawHitSetContainer.cc