Analysis Software: nanoflann::KNNResultSet< DistanceType, IndexType, CountType > Class Template Reference
nanoflann::KNNResultSet< DistanceType, IndexType, CountType > Class Template Reference
Result set classes
#include <coresoftware/blob/master/offline/packages/trackreco/nanoflann.hpp>
Public Member Functions
KNNResultSet (CountType capacity_)
void init (IndexType *indices_, DistanceType *dists_)
CountType size () const
bool full () const
void addPoint (DistanceType dist, IndexType index)
DistanceType worstDist () const
Private Attributes
IndexType * indices
DistanceType * dists
CountType capacity
CountType count
Detailed Description
template<typename DistanceType, typename IndexType = size_t, typename CountType = size_t>
class nanoflann::KNNResultSet< DistanceType, IndexType, CountType >
Definition at line 78 of file nanoflann.hpp.
View newest version in sPHENIX GitHub at line 78 of file nanoflann.hpp
Constructor & Destructor Documentation
template<typename DistanceType, typename IndexType = size_t, typename CountType = size_t> nanoflann::KNNResultSet< DistanceType, IndexType, CountType >::KNNResultSet (CountType capacity_) inline
Definition at line 86 of file nanoflann.hpp.
View newest version in sPHENIX GitHub at line 86 of file nanoflann.hpp
Member Function Documentation
template<typename DistanceType, typename IndexType = size_t, typename CountType = size_t> void nanoflann::KNNResultSet< DistanceType, IndexType, CountType >::addPoint (DistanceType dist, IndexType index) inline
Definition at line 113 of file nanoflann.hpp.
View newest version in sPHENIX GitHub at line 113 of file nanoflann.hpp
References nanoflann::KNNResultSet< DistanceType, IndexType, CountType >::capacity, nanoflann::KNNResultSet< DistanceType, IndexType, CountType >::count, dist(), nanoflann::KNNResultSet< DistanceType, IndexType, CountType >::dists, i, index, and nanoflann::KNNResultSet< DistanceType, IndexType, CountType >::indices.
template<typename DistanceType, typename IndexType = size_t, typename CountType = size_t> bool nanoflann::KNNResultSet< DistanceType, IndexType, CountType >::full () const inline
Definition at line 108 of file nanoflann.hpp.
View newest version in sPHENIX GitHub at line 108 of file nanoflann.hpp
References nanoflann::KNNResultSet< DistanceType, IndexType, CountType >::capacity, and nanoflann::KNNResultSet< DistanceType, IndexType, CountType >::count.
template<typename DistanceType, typename IndexType = size_t, typename CountType = size_t> void nanoflann::KNNResultSet< DistanceType, IndexType, CountType >::init (IndexType * indices_, DistanceType * dists_) inline
Definition at line 94 of file nanoflann.hpp.
View newest version in sPHENIX GitHub at line 94 of file nanoflann.hpp
References nanoflann::KNNResultSet< DistanceType, IndexType, CountType >::capacity, nanoflann::KNNResultSet< DistanceType, IndexType, CountType >::count, nanoflann::KNNResultSet< DistanceType, IndexType, CountType >::dists, and nanoflann::KNNResultSet< DistanceType, IndexType, CountType >::indices.
Referenced by nanoflann::KDTreeSingleIndexAdaptor< Distance, DatasetAdaptor, DIM, IndexType >::knnSearch(), nanoflann::KDTreeEigenMatrixAdaptor< MatrixType, DIM, Distance >::query(), and nanoflann::RadiusResultSet< DistanceType, IndexType >::RadiusResultSet().
template<typename DistanceType, typename IndexType = size_t, typename CountType = size_t> CountType nanoflann::KNNResultSet< DistanceType, IndexType, CountType >::size (void) const inline
Definition at line 103 of file nanoflann.hpp.
View newest version in sPHENIX GitHub at line 103 of file nanoflann.hpp
References nanoflann::KNNResultSet< DistanceType, IndexType, CountType >::count.
Referenced by nanoflann::KDTreeSingleIndexAdaptor< Distance, DatasetAdaptor, DIM, IndexType >::findNeighbors(), nanoflann::KDTreeEigenMatrixAdaptor< MatrixType, DIM, Distance >::kdtree_distance(), nanoflann::KDTreeSingleIndexAdaptor< Distance, DatasetAdaptor, DIM, IndexType >::knnSearch(), nanoflann::load_value(), nanoflann::PooledAllocator::malloc(), nanoflann::L1_Adaptor< T, DataSource, _DistanceType >::operator()(), nanoflann::L2_Adaptor< T, DataSource, _DistanceType >::operator()(), nanoflann::CArray< T, N >::rangecheck(), and nanoflann::save_value().
template<typename DistanceType, typename IndexType = size_t, typename CountType = size_t> DistanceType nanoflann::KNNResultSet< DistanceType, IndexType, CountType >::worstDist () const inline
Definition at line 142 of file nanoflann.hpp.
View newest version in sPHENIX GitHub at line 142 of file nanoflann.hpp
References nanoflann::KNNResultSet< DistanceType, IndexType, CountType >::capacity, and nanoflann::KNNResultSet< DistanceType, IndexType, CountType >::dists.
Member Data Documentation
template<typename DistanceType, typename IndexType = size_t, typename CountType = size_t> CountType nanoflann::KNNResultSet< DistanceType, IndexType, CountType >::capacity private
Definition at line 82 of file nanoflann.hpp.
View newest version in sPHENIX GitHub at line 82 of file nanoflann.hpp
Referenced by nanoflann::KNNResultSet< DistanceType, IndexType, CountType >::addPoint(), nanoflann::KNNResultSet< DistanceType, IndexType, CountType >::full(), nanoflann::KNNResultSet< DistanceType, IndexType, CountType >::init(), and nanoflann::KNNResultSet< DistanceType, IndexType, CountType >::worstDist().
template<typename DistanceType, typename IndexType = size_t, typename CountType = size_t> CountType nanoflann::KNNResultSet< DistanceType, IndexType, CountType >::count private
Definition at line 83 of file nanoflann.hpp.
View newest version in sPHENIX GitHub at line 83 of file nanoflann.hpp
Referenced by nanoflann::KNNResultSet< DistanceType, IndexType, CountType >::addPoint(), nanoflann::allocate(), nanoflann::PooledAllocator::allocate(), nanoflann::KDTreeSingleIndexAdaptor< Distance, DatasetAdaptor, DIM, IndexType >::computeMinMax(), nanoflann::KNNResultSet< DistanceType, IndexType, CountType >::full(), nanoflann::KNNResultSet< DistanceType, IndexType, CountType >::init(), nanoflann::load_value(), nanoflann::save_value(), and nanoflann::KNNResultSet< DistanceType, IndexType, CountType >::size().
template<typename DistanceType, typename IndexType = size_t, typename CountType = size_t> DistanceType* nanoflann::KNNResultSet< DistanceType, IndexType, CountType >::dists private
Definition at line 81 of file nanoflann.hpp.
View newest version in sPHENIX GitHub at line 81 of file nanoflann.hpp
Referenced by nanoflann::KNNResultSet< DistanceType, IndexType, CountType >::addPoint(), nanoflann::KDTreeSingleIndexAdaptor< Distance, DatasetAdaptor, DIM, IndexType >::findNeighbors(), nanoflann::KNNResultSet< DistanceType, IndexType, CountType >::init(), and nanoflann::KNNResultSet< DistanceType, IndexType, CountType >::worstDist().
template<typename DistanceType, typename IndexType = size_t, typename CountType = size_t> IndexType* nanoflann::KNNResultSet< DistanceType, IndexType, CountType >::indices private
Definition at line 80 of file nanoflann.hpp.
View newest version in sPHENIX GitHub at line 80 of file nanoflann.hpp
Referenced by nanoflann::KNNResultSet< DistanceType, IndexType, CountType >::addPoint(), and nanoflann::KNNResultSet< DistanceType, IndexType, CountType >::init().
The documentation for this class was generated from the following file:
coresoftware/blob/master/offline/packages/trackreco/nanoflann.hpp