Analysis Software: RDBC/blob/master/macros/RDBCconsumer.C File Reference
RDBCconsumer.C File Reference
#include <TError.h>
#include <TH1.h>
#include <TH2.h>
#include <TProfile.h>
#include <TCanvas.h>
#include <TSystem.h>
#include <TROOT.h>
#include <RDBC/TSQLDriverManager.h>
#include <RDBC/TSQLConnection.h>
#include <RDBC/TSQLResultSet.h>
#include <RDBC/TSQLResultSetMetaData.h>
#include <RDBC/TSQLPreparedStatement.h>
Functions
void DropStuff (TSQLConnection *con)
Int_t RDBCconsumer (const Text_t *dsn, const Text_t *usr, const Text_t *pwd)
void Catch (TSQLException *e)
Variables
const TString tableName = "object_test"
TH1F * hpx =0
TH2F * hpxpy =0
TProfile * hprof =0
Function Documentation
void Catch (TSQLException * e)
Definition at line 164 of file RDBCconsumer.C.
View newest version in sPHENIX GitHub at line 164 of file RDBCconsumer.C
References TSQLException::GetMessage(), printf(), and str.
void DropStuff (TSQLConnection * con)
Definition at line 54 of file RDBCconsumer.C.
View newest version in sPHENIX GitHub at line 54 of file RDBCconsumer.C
References TSQLConnection::CreateStatement(), TSQLStatement::ExecuteUpdate(), printf(), and tableName.
Referenced by RDBCscroll().
Int_t RDBCconsumer (const Text_t * dsn, const Text_t * usr, const Text_t * pwd)
Definition at line 65 of file RDBCconsumer.C.
View newest version in sPHENIX GitHub at line 65 of file RDBCconsumer.C
References TSQLConnection::Close(), TSQLConnection::Commit(), con, TSQLConnection::CreateStatement(), TSQLStatement::ExecuteQuery(), TSQLDriverManager::GetConnection(), TSQLResultSet::GetObject(), TSQLResultSet::GetString(), gSQLDriverManager, hprof, hpx, hpxpy, i, j, kCONCUR_READ_ONLY, kTYPE_FORWARD_ONLY, TSQLResultSet::Next(), printf(), TSQL::SetHandler(), str, and tableName.
Variable Documentation
TProfile* hprof =0
Definition at line 51 of file RDBCconsumer.C.
View newest version in sPHENIX GitHub at line 51 of file RDBCconsumer.C
Referenced by CreateStuff(), Fill(), RDBCconsumer(), and reconstructionPerformance().
TH1F* hpx =0
Definition at line 49 of file RDBCconsumer.C.
View newest version in sPHENIX GitHub at line 49 of file RDBCconsumer.C
Referenced by CreateStuff(), Fill(), and RDBCconsumer().
TH2F* hpxpy =0
Definition at line 50 of file RDBCconsumer.C.
View newest version in sPHENIX GitHub at line 50 of file RDBCconsumer.C
Referenced by CreateStuff(), Fill(), and RDBCconsumer().
const TString tableName = "object_test"
Definition at line 46 of file RDBCconsumer.C.
View newest version in sPHENIX GitHub at line 46 of file RDBCconsumer.C
Referenced by Compare(), CreateStuff(), DropStuff(), Fill(), Populate(), RDBCconsumer(), and RDBCTestMetaData().