Analysis Software: ActsExamples::GeantinoRecording Exception Reference
ActsExamples::GeantinoRecording Exception Reference final
#include <acts/blob/sPHENIX/Examples/Algorithms/Geant4/include/ActsExamples/Geant4/GeantinoRecording.hpp>
Classes
struct Config
Public Member Functions
GeantinoRecording (Config &&cfg, Acts::Logging::Level lvl)
~GeantinoRecording ()
ActsExamples::ProcessCode execute (const ActsExamples::AlgorithmContext &ctx) const finaloverride
Public Member Functions inherited from ActsExamples::BareAlgorithm
BareAlgorithm (std::string name, Acts::Logging::Level level=Acts::Logging::INFO)
std::string name () const finaloverride
The algorithm name.
Private Attributes
Config m_cfg
std::unique_ptr< G4RunManager > m_runManager
std::mutex m_runManagerLock
Additional Inherited Members
Protected Member Functions inherited from ActsExamples::BareAlgorithm
const Acts::Logger & logger () const
Detailed Description
Records the simulation geometry using geantinos.
This initiates the Geant4 simulation, and creates and writes out the MaterialTrack entities which are needed for material mapping.
Definition at line 37 of file GeantinoRecording.hpp.
View newest version in sPHENIX GitHub at line 37 of file GeantinoRecording.hpp
Constructor & Destructor Documentation
GeantinoRecording::GeantinoRecording (GeantinoRecording::Config && cfg, Acts::Logging::Level lvl)
Definition at line 26 of file GeantinoRecording.cpp.
View newest version in sPHENIX GitHub at line 26 of file GeantinoRecording.cpp
References ActsExamples::GeantinoRecording::Config::detectorConstruction, ActsExamples::PrimaryGeneratorAction::Config::energy, ActsExamples::GeantinoRecording::Config::generationConfig, m_cfg, m_runManager, ActsExamples::GeantinoRecording::Config::outputMaterialTracks, and ActsExamples::PrimaryGeneratorAction::Config::particleName.
GeantinoRecording::~GeantinoRecording ()
Definition at line 52 of file GeantinoRecording.cpp.
View newest version in sPHENIX GitHub at line 52 of file GeantinoRecording.cpp
Member Function Documentation
ActsExamples::ProcessCode GeantinoRecording::execute (const ActsExamples::AlgorithmContext & context) const final override virtual
Execute the algorithm for one event.
This function must be implemented by subclasses.
Implements ActsExamples::BareAlgorithm.
Definition at line 54 of file GeantinoRecording.cpp.
View newest version in sPHENIX GitHub at line 54 of file GeantinoRecording.cpp
References ActsExamples::WhiteBoard::add(), ActsExamples::AlgorithmContext::eventStore, ActsExamples::EventAction::instance(), m_cfg, m_runManager, m_runManagerLock, ActsExamples::EventAction::materialTracks(), testing::internal::move(), ActsExamples::GeantinoRecording::Config::outputMaterialTracks, SUCCESS, and ActsExamples::GeantinoRecording::Config::tracksPerEvent.
Member Data Documentation
Config ActsExamples::GeantinoRecording::m_cfg private
Definition at line 57 of file GeantinoRecording.hpp.
View newest version in sPHENIX GitHub at line 57 of file GeantinoRecording.hpp
Referenced by execute(), and GeantinoRecording().
std::unique_ptr<G4RunManager> ActsExamples::GeantinoRecording::m_runManager private
Definition at line 58 of file GeantinoRecording.hpp.
View newest version in sPHENIX GitHub at line 58 of file GeantinoRecording.hpp
Referenced by execute(), and GeantinoRecording().
std::mutex ActsExamples::GeantinoRecording::m_runManagerLock mutable private
Definition at line 60 of file GeantinoRecording.hpp.
View newest version in sPHENIX GitHub at line 60 of file GeantinoRecording.hpp
Referenced by execute().
The documentation for this exception was generated from the following files:
acts/blob/sPHENIX/Examples/Algorithms/Geant4/include/ActsExamples/Geant4/GeantinoRecording.hpp
acts/blob/sPHENIX/Examples/Algorithms/Geant4/src/GeantinoRecording.cpp