Analysis Software: TrkrClusterv2 Class Reference
TrkrClusterv2 Class Reference
Version 2 of TrkrCluster.
#include <coresoftware/blob/master/offline/packages/trackbase/TrkrClusterv2.h>
Public Member Functions
TrkrClusterv2 ()
ctor
~TrkrClusterv2 () override=default
dtor
void identify (std::ostream &os=std::cout) const override
void Reset () override
Clear Event.
int isValid () const override
isValid returns non zero if object contains vailid data
PHObject * CloneMe () const override
Virtual copy constructor.
void CopyFrom (const TrkrCluster &) override
copy content from base class
void CopyFrom (TrkrCluster *source) override
copy content from base class
float getX () const override
void setX (float x) override
float getY () const override
void setY (float y) override
float getZ () const override
void setZ (float z) override
float getPosition (int coor) const override
void setPosition (int coor, float xi) override
void setGlobal () override
void setLocal () override
bool isGlobal () const override
float getLocalX () const override
void setLocalX (float loc0) override
float getLocalY () const override
void setLocalY (float loc1) override
void setActsLocalError (unsigned int i, unsigned int j, float value) override
Acts functions, for Acts module use only.
float getActsLocalError (unsigned int i, unsigned int j) const override
TrkrDefs::subsurfkey getSubSurfKey () const override
void setSubSurfKey (TrkrDefs::subsurfkey id) override
unsigned int getAdc () const override
void setAdc (unsigned int adc) override
float getSize (unsigned int i, unsigned int j) const override
void setSize (unsigned int i, unsigned int j, float value) override
float getError (unsigned int i, unsigned int j) const override
void setError (unsigned int i, unsigned int j, float value) override
float getPhiSize () const override
float getZSize () const override
float getRPhiError () const override
float getPhiError () const override
float getZError () const override
Public Member Functions inherited from TrkrCluster
~TrkrCluster () override=default
dtor
virtual void setMaxAdc (uint16_t)
virtual unsigned int getMaxAdc () const
virtual char getOverlap () const
virtual void setOverlap (char)
virtual char getEdge () const
virtual void setEdge (char)
virtual void setTime (const float)
virtual float getTime () const
virtual char getSize () const
Public Member Functions inherited from PHObject
PHObject ()
ctor
~PHObject () override
dtor
virtual PHObject * clone () const final
PHObject * Clone (const char *newname="") const final
void Copy (TObject &object) const final
virtual int Integrate () const
virtual int Integrate (PHObject *)
virtual void CopyFrom (const PHObject *obj)
Protected Attributes
TrkrDefs::cluskey m_cluskey
TrkrDefs::subsurfkey m_subsurfkey
float m_pos [3]
bool m_isGlobal
unsigned int m_adc
float m_size [6]
float m_err [6]
float m_local [2]
float m_actsLocalErr [2][2]
Additional Inherited Members
Protected Member Functions inherited from TrkrCluster
TrkrCluster ()=default
Detailed Description
Version 2 of TrkrCluster.
This version of TrkrCluster contains Acts source link objects as member variables, to join the Svtx and Acts worlds
Definition at line 22 of file TrkrClusterv2.h.
View newest version in sPHENIX GitHub at line 22 of file TrkrClusterv2.h
Constructor & Destructor Documentation
TrkrClusterv2::TrkrClusterv2 ()
ctor
Definition at line 41 of file TrkrClusterv2.cc.
View newest version in sPHENIX GitHub at line 41 of file TrkrClusterv2.cc
References i, j, m_actsLocalErr, m_err, m_local, m_pos, and m_size.
Referenced by CloneMe().
TrkrClusterv2::~TrkrClusterv2 () override default
dtor
Member Function Documentation
PHObject* TrkrClusterv2::CloneMe () const inline override virtual
Virtual copy constructor.
Reimplemented from PHObject.
Definition at line 36 of file TrkrClusterv2.h.
View newest version in sPHENIX GitHub at line 36 of file TrkrClusterv2.h
References TrkrClusterv2().
void TrkrClusterv2::CopyFrom (const TrkrCluster & source) override virtual
copy content from base class
Reimplemented from TrkrCluster.
Definition at line 133 of file TrkrClusterv2.cc.
View newest version in sPHENIX GitHub at line 133 of file TrkrClusterv2.cc
References TrkrCluster::CopyFrom(), TrkrCluster::getActsLocalError(), TrkrCluster::getAdc(), TrkrCluster::getError(), TrkrCluster::getLocalX(), TrkrCluster::getLocalY(), TrkrCluster::getSize(), TrkrCluster::getSubSurfKey(), TrkrCluster::getX(), TrkrCluster::getY(), TrkrCluster::getZ(), i, TrkrCluster::isGlobal(), j, m_isGlobal, setActsLocalError(), setAdc(), setError(), setLocalX(), setLocalY(), setSize(), setSubSurfKey(), setX(), setY(), and setZ().
void TrkrClusterv2::CopyFrom (TrkrCluster * source) inline override virtual
copy content from base class
Reimplemented from TrkrCluster.
Definition at line 42 of file TrkrClusterv2.h.
View newest version in sPHENIX GitHub at line 42 of file TrkrClusterv2.h
References CopyFrom().
Referenced by CopyFrom().
float TrkrClusterv2::getActsLocalError (unsigned int i, unsigned int j) const inline override virtual
Reimplemented from TrkrCluster.
Definition at line 68 of file TrkrClusterv2.h.
View newest version in sPHENIX GitHub at line 68 of file TrkrClusterv2.h
References i, j, and m_actsLocalErr.
unsigned int TrkrClusterv2::getAdc () const inline override virtual
Reimplemented from TrkrCluster.
Definition at line 75 of file TrkrClusterv2.h.
View newest version in sPHENIX GitHub at line 75 of file TrkrClusterv2.h
References m_adc.
Referenced by identify().
float TrkrClusterv2::getError (unsigned int i, unsigned int j) const override virtual
Reimplemented from TrkrCluster.
Definition at line 178 of file TrkrClusterv2.cc.
View newest version in sPHENIX GitHub at line 178 of file TrkrClusterv2.cc
References m_err.
Referenced by getZError(), identify(), and isValid().
float TrkrClusterv2::getLocalX () const inline override virtual
Reimplemented from TrkrCluster.
Definition at line 61 of file TrkrClusterv2.h.
View newest version in sPHENIX GitHub at line 61 of file TrkrClusterv2.h
References m_local.
float TrkrClusterv2::getLocalY () const inline override virtual
Reimplemented from TrkrCluster.
Definition at line 63 of file TrkrClusterv2.h.
View newest version in sPHENIX GitHub at line 63 of file TrkrClusterv2.h
References m_local.
float TrkrClusterv2::getPhiError () const override virtual
Reimplemented from TrkrCluster.
Definition at line 187 of file TrkrClusterv2.cc.
View newest version in sPHENIX GitHub at line 187 of file TrkrClusterv2.cc
References getRPhiError(), m_pos, Acts::UnitConstants::rad, and square().
float TrkrClusterv2::getPhiSize () const override virtual
Reimplemented from TrkrCluster.
Definition at line 181 of file TrkrClusterv2.cc.
View newest version in sPHENIX GitHub at line 181 of file TrkrClusterv2.cc
Referenced by identify().
float TrkrClusterv2::getPosition (int coor) const inline override virtual
Reimplemented from TrkrCluster.
Definition at line 55 of file TrkrClusterv2.h.
View newest version in sPHENIX GitHub at line 55 of file TrkrClusterv2.h
References m_pos.
Referenced by identify(), and isValid().
float TrkrClusterv2::getRPhiError () const override virtual
Reimplemented from TrkrCluster.
Definition at line 194 of file TrkrClusterv2.cc.
View newest version in sPHENIX GitHub at line 194 of file TrkrClusterv2.cc
Referenced by getPhiError().
float TrkrClusterv2::getSize (unsigned int i, unsigned int j) const override virtual
Reimplemented from TrkrCluster.
Definition at line 169 of file TrkrClusterv2.cc.
View newest version in sPHENIX GitHub at line 169 of file TrkrClusterv2.cc
References m_size.
TrkrDefs::subsurfkey TrkrClusterv2::getSubSurfKey () const inline override virtual
Reimplemented from TrkrCluster.
Definition at line 69 of file TrkrClusterv2.h.
View newest version in sPHENIX GitHub at line 69 of file TrkrClusterv2.h
References m_subsurfkey.
float TrkrClusterv2::getX () const inline override virtual
Reimplemented from TrkrCluster.
Definition at line 49 of file TrkrClusterv2.h.
View newest version in sPHENIX GitHub at line 49 of file TrkrClusterv2.h
References m_pos.
float TrkrClusterv2::getY () const inline override virtual
Reimplemented from TrkrCluster.
Definition at line 51 of file TrkrClusterv2.h.
View newest version in sPHENIX GitHub at line 51 of file TrkrClusterv2.h
References m_pos.
float TrkrClusterv2::getZ () const inline override virtual
Reimplemented from TrkrCluster.
Definition at line 53 of file TrkrClusterv2.h.
View newest version in sPHENIX GitHub at line 53 of file TrkrClusterv2.h
References m_pos.
float TrkrClusterv2::getZError () const override virtual
Reimplemented from TrkrCluster.
Definition at line 197 of file TrkrClusterv2.cc.
View newest version in sPHENIX GitHub at line 197 of file TrkrClusterv2.cc
References getError().
float TrkrClusterv2::getZSize () const override virtual
Reimplemented from TrkrCluster.
Definition at line 184 of file TrkrClusterv2.cc.
View newest version in sPHENIX GitHub at line 184 of file TrkrClusterv2.cc
References TrkrCluster::getSize().
Referenced by identify().
void TrkrClusterv2::identify (std::ostream & os = std::cout) const override virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from TrkrCluster.
Definition at line 64 of file TrkrClusterv2.cc.
View newest version in sPHENIX GitHub at line 64 of file TrkrClusterv2.cc
References getAdc(), getError(), getPhiSize(), getPosition(), TrkrCluster::getSize(), getZSize(), and m_isGlobal.
bool TrkrClusterv2::isGlobal () const inline override virtual
Reimplemented from TrkrCluster.
Definition at line 59 of file TrkrClusterv2.h.
View newest version in sPHENIX GitHub at line 59 of file TrkrClusterv2.h
References m_isGlobal.
int TrkrClusterv2::isValid () const override virtual
isValid returns non zero if object contains vailid data
Reimplemented from TrkrCluster.
Definition at line 113 of file TrkrClusterv2.cc.
View newest version in sPHENIX GitHub at line 113 of file TrkrClusterv2.cc
References getError(), getPosition(), TrkrCluster::getSize(), i, j, m_adc, and m_cluskey.
void TrkrClusterv2::Reset () inline override virtual
Clear Event.
Reimplemented from TrkrCluster.
Definition at line 34 of file TrkrClusterv2.h.
View newest version in sPHENIX GitHub at line 34 of file TrkrClusterv2.h
void TrkrClusterv2::setActsLocalError (unsigned int i, unsigned int j, float value) override virtual
Acts functions, for Acts module use only.
Reimplemented from TrkrCluster.
Definition at line 200 of file TrkrClusterv2.cc.
View newest version in sPHENIX GitHub at line 200 of file TrkrClusterv2.cc
References i, j, m_actsLocalErr, and value.
Referenced by CopyFrom().
void TrkrClusterv2::setAdc (unsigned int adc) inline override virtual
Reimplemented from TrkrCluster.
Definition at line 76 of file TrkrClusterv2.h.
View newest version in sPHENIX GitHub at line 76 of file TrkrClusterv2.h
References m_adc.
Referenced by CopyFrom().
void TrkrClusterv2::setError (unsigned int i, unsigned int j, float value) override virtual
Reimplemented from TrkrCluster.
Definition at line 172 of file TrkrClusterv2.cc.
View newest version in sPHENIX GitHub at line 172 of file TrkrClusterv2.cc
References m_err, and value.
Referenced by CopyFrom().
void TrkrClusterv2::setGlobal () inline override virtual
Reimplemented from TrkrCluster.
Definition at line 57 of file TrkrClusterv2.h.
View newest version in sPHENIX GitHub at line 57 of file TrkrClusterv2.h
References m_isGlobal.
void TrkrClusterv2::setLocal () inline override virtual
Reimplemented from TrkrCluster.
Definition at line 58 of file TrkrClusterv2.h.
View newest version in sPHENIX GitHub at line 58 of file TrkrClusterv2.h
References m_isGlobal.
void TrkrClusterv2::setLocalX (float loc0) inline override virtual
Reimplemented from TrkrCluster.
Definition at line 62 of file TrkrClusterv2.h.
View newest version in sPHENIX GitHub at line 62 of file TrkrClusterv2.h
References physmon_track_finding_ttbar::loc0, and m_local.
Referenced by CopyFrom().
void TrkrClusterv2::setLocalY (float loc1) inline override virtual
Reimplemented from TrkrCluster.
Definition at line 64 of file TrkrClusterv2.h.
View newest version in sPHENIX GitHub at line 64 of file TrkrClusterv2.h
References m_local.
Referenced by CopyFrom().
void TrkrClusterv2::setPosition (int coor, float xi) inline override virtual
Reimplemented from TrkrCluster.
Definition at line 56 of file TrkrClusterv2.h.
View newest version in sPHENIX GitHub at line 56 of file TrkrClusterv2.h
References m_pos.
void TrkrClusterv2::setSize (unsigned int i, unsigned int j, float value) override virtual
Reimplemented from TrkrCluster.
Definition at line 163 of file TrkrClusterv2.cc.
View newest version in sPHENIX GitHub at line 163 of file TrkrClusterv2.cc
References m_size, and value.
Referenced by CopyFrom().
void TrkrClusterv2::setSubSurfKey (TrkrDefs::subsurfkey id) inline override virtual
Reimplemented from TrkrCluster.
Definition at line 70 of file TrkrClusterv2.h.
View newest version in sPHENIX GitHub at line 70 of file TrkrClusterv2.h
References train_ambiguity_solver::id, and m_subsurfkey.
Referenced by CopyFrom().
void TrkrClusterv2::setX (float x) inline override virtual
Reimplemented from TrkrCluster.
Definition at line 50 of file TrkrClusterv2.h.
View newest version in sPHENIX GitHub at line 50 of file TrkrClusterv2.h
References m_pos, and ambiguity_solver_full_chain::x.
Referenced by CopyFrom().
void TrkrClusterv2::setY (float y) inline override virtual
Reimplemented from TrkrCluster.
Definition at line 52 of file TrkrClusterv2.h.
View newest version in sPHENIX GitHub at line 52 of file TrkrClusterv2.h
References m_pos, and y.
Referenced by CopyFrom().
void TrkrClusterv2::setZ (float z) inline override virtual
Reimplemented from TrkrCluster.
Definition at line 54 of file TrkrClusterv2.h.
View newest version in sPHENIX GitHub at line 54 of file TrkrClusterv2.h
References m_pos, and physmon_track_finding_ttbar::z.
Referenced by CopyFrom().
Member Data Documentation
float TrkrClusterv2::m_actsLocalErr[2][2] protected
Definition at line 104 of file TrkrClusterv2.h.
View newest version in sPHENIX GitHub at line 104 of file TrkrClusterv2.h
Referenced by getActsLocalError(), setActsLocalError(), and TrkrClusterv2().
unsigned int TrkrClusterv2::m_adc protected
Definition at line 99 of file TrkrClusterv2.h.
View newest version in sPHENIX GitHub at line 99 of file TrkrClusterv2.h
Referenced by getAdc(), isValid(), and setAdc().
TrkrDefs::cluskey TrkrClusterv2::m_cluskey protected
Definition at line 95 of file TrkrClusterv2.h.
View newest version in sPHENIX GitHub at line 95 of file TrkrClusterv2.h
Referenced by isValid().
float TrkrClusterv2::m_err[6] protected
Definition at line 101 of file TrkrClusterv2.h.
View newest version in sPHENIX GitHub at line 101 of file TrkrClusterv2.h
Referenced by getError(), setError(), and TrkrClusterv2().
bool TrkrClusterv2::m_isGlobal protected
Definition at line 98 of file TrkrClusterv2.h.
View newest version in sPHENIX GitHub at line 98 of file TrkrClusterv2.h
Referenced by CopyFrom(), identify(), isGlobal(), setGlobal(), and setLocal().
float TrkrClusterv2::m_local[2] protected
Definition at line 103 of file TrkrClusterv2.h.
View newest version in sPHENIX GitHub at line 103 of file TrkrClusterv2.h
Referenced by getLocalX(), getLocalY(), setLocalX(), setLocalY(), and TrkrClusterv2().
float TrkrClusterv2::m_pos[3] protected
Definition at line 97 of file TrkrClusterv2.h.
View newest version in sPHENIX GitHub at line 97 of file TrkrClusterv2.h
Referenced by getPhiError(), getPosition(), getX(), getY(), getZ(), setPosition(), setX(), setY(), setZ(), and TrkrClusterv2().
float TrkrClusterv2::m_size[6] protected
Definition at line 100 of file TrkrClusterv2.h.
View newest version in sPHENIX GitHub at line 100 of file TrkrClusterv2.h
Referenced by getSize(), setSize(), and TrkrClusterv2().
TrkrDefs::subsurfkey TrkrClusterv2::m_subsurfkey protected
Definition at line 96 of file TrkrClusterv2.h.
View newest version in sPHENIX GitHub at line 96 of file TrkrClusterv2.h
Referenced by getSubSurfKey(), and setSubSurfKey().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/trackbase/TrkrClusterv2.h
coresoftware/blob/master/offline/packages/trackbase/TrkrClusterv2.cc