Analysis Software: RawClusterv1 Class Reference
RawClusterv1 Class Reference
#include <coresoftware/blob/master/offline/packages/CaloBase/RawClusterv1.h>
Classes
union u_property
convert between 32bit inputs and storage type prop_storage_t
Public Member Functions
RawClusterv1 ()
~RawClusterv1 () override
void Reset () override
Clear Event.
PHObject * CloneMe () const override
Virtual copy constructor.
int isValid () const override
isValid returns non zero if object contains vailid data
void identify (std::ostream &os=std::cout) const override
RawClusterDefs::keytype get_id () const override
cluster ID
float get_energy () const override
total energy
size_t getNTowers () const override
Tower operations.
RawCluster::TowerConstRange get_towers () const override
const TowerMap & get_towermap () const override
return tower map for c++11 range-based for-loop
CLHEP::Hep3Vector get_position () const override
cluster position in 3D
float get_phi () const override
access to intrinsic cylindrical coordinate system
float get_r () const override
float get_z () const override
float get_x () const override
access Cartesian coordinate system
float get_y () const override
float get_ecore () const override
float get_chi2 () const override
reduced chi2 for EM shower
float get_prob () const override
cluster template probability for EM shower
float get_et_iso () const override
isolation ET default
float get_et_iso (const int radiusx10, bool subtracted, bool clusterTower) const override
isolation ET the radius and hueristic can be specified
void set_id (const RawClusterDefs::keytype id) override
cluster ID
void addTower (const RawClusterDefs::keytype twrid, const float etower) override
Tower operations.
void set_energy (const float energy) override
total energy
void set_phi (const float phi) override
access to intrinsic cylindrical coordinate system
void set_z (const float z) override
void set_r (const float r) override
void set_ecore (const float ecore) override
void set_chi2 (const float chi2) override
reduced chi2 for EM shower
void set_prob (const float prob) override
cluster template probability for EM shower
void set_et_iso (const float e) override
isolation ET default
void set_et_iso (const float et_iso, const int radiusx10, bool subtracted, bool clusterTower) override
isolation ET the radius and hueristic can be specified
bool has_property (const PROPERTY prop_id) const override
float get_property_float (const PROPERTY prop_id) const override
int get_property_int (const PROPERTY prop_id) const override
unsigned int get_property_uint (const PROPERTY prop_id) const override
void set_property (const PROPERTY prop_id, const float value) override
void set_property (const PROPERTY prop_id, const int value) override
void set_property (const PROPERTY prop_id, const unsigned int value) override
Public Member Functions inherited from RawCluster
~RawCluster () override
virtual bool has_property (const PROPERTY) const
getters
virtual float get_property_float (const PROPERTY) const
virtual int get_property_int (const PROPERTY) const
virtual unsigned int get_property_uint (const PROPERTY) const
virtual void set_property (const PROPERTY, const float)
setters
virtual void set_property (const PROPERTY, const int)
virtual void set_property (const PROPERTY, const unsigned int)
Public Member Functions inherited from PHObject
PHObject ()
ctor
~PHObject () override
dtor
virtual PHObject * clone () const final
PHObject * Clone (const char *newname="") const final
void Copy (TObject &object) const final
virtual int Integrate () const
virtual int Integrate (PHObject *)
virtual void CopyFrom (const PHObject *obj)
Protected Types
typedef uint8_t prop_id_t
storage types for additional property
typedef uint32_t prop_storage_t
typedef std::map< prop_id_t,
prop_storage_t > prop_map_t
Protected Member Functions
unsigned int get_property_nocheck (const PROPERTY prop_id) const
void set_property_nocheck (const PROPERTY prop_id, const unsigned int ui)
Protected Member Functions inherited from RawCluster
RawCluster ()
Protected Attributes
prop_map_t prop_map
container for additional property
RawClusterDefs::keytype clusterid
cluster ID
float _energy
total energy
TowerMap towermap
Tower operations.
float _r
location of cluster in cylindrical coordinate
float _phi
float _z
Additional Inherited Members
Public Types inherited from RawCluster
enum PROPERTY {
prop_ecore = 0, prop_prob = 1, prop_chi2 = 2, prop_et_iso_calotower_sub_R01 = 20,
prop_et_iso_calotower_R01 = 21, prop_et_iso_calotower_sub_R02 = 22, prop_et_iso_calotower_R02 = 23, prop_et_iso_calotower_sub_R03 = 24,
prop_et_iso_calotower_R03 = 25, prop_et_iso_calotower_sub_R04 = 26, prop_et_iso_calotower_R04 = 27, prop_MAX_NUMBER = UCHAR_MAX
}
enum PROPERTY_TYPE { type_int = 1, type_uint = 2, type_float = 3, type_unknown = -1 }
typedef std::map
< RawTowerDefs::keytype, float > TowerMap
typedef TowerMap::iterator TowerIterator
typedef TowerMap::const_iterator TowerConstIterator
typedef std::pair
< TowerIterator, TowerIterator > TowerRange
typedef std::pair
< TowerConstIterator,
TowerConstIterator > TowerConstRange
Static Public Member Functions inherited from RawCluster
static std::pair< const
std::string, PROPERTY_TYPE > get_property_info (PROPERTY prop_id)
type management
static bool check_property (const PROPERTY prop_id, const PROPERTY_TYPE prop_type)
static std::string get_property_type (const PROPERTY_TYPE prop_type)
Detailed Description
Definition at line 17 of file RawClusterv1.h.
View newest version in sPHENIX GitHub at line 17 of file RawClusterv1.h
Constructor & Destructor Documentation
RawClusterv1::RawClusterv1 ()
Definition at line 13 of file RawClusterv1.cc.
View newest version in sPHENIX GitHub at line 13 of file RawClusterv1.cc
Referenced by CloneMe().
RawClusterv1::~RawClusterv1 () inline override
Definition at line 21 of file RawClusterv1.h.
View newest version in sPHENIX GitHub at line 21 of file RawClusterv1.h
Member Function Documentation
PHObject* RawClusterv1::CloneMe () const inline override virtual
Virtual copy constructor.
Reimplemented from RawCluster.
Definition at line 24 of file RawClusterv1.h.
View newest version in sPHENIX GitHub at line 24 of file RawClusterv1.h
References RawClusterv1().
void RawClusterv1::identify (std::ostream & os = std::cout) const override virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from RawCluster.
Definition at line 45 of file RawClusterv1.cc.
View newest version in sPHENIX GitHub at line 45 of file RawClusterv1.cc
References get_energy(), get_id(), get_phi(), get_property_float(), RawCluster::get_property_info(), get_property_int(), get_property_uint(), get_r(), get_x(), get_y(), get_z(), getNTowers(), i, prop_map, RawCluster::type_float, RawCluster::type_int, and RawCluster::type_uint.
int RawClusterv1::isValid () const inline override virtual
isValid returns non zero if object contains vailid data
Reimplemented from RawCluster.
Definition at line 25 of file RawClusterv1.h.
View newest version in sPHENIX GitHub at line 25 of file RawClusterv1.h
References towermap.
void RawClusterv1::Reset () override virtual
Clear Event.
Reimplemented from RawCluster.
Definition at line 23 of file RawClusterv1.cc.
View newest version in sPHENIX GitHub at line 23 of file RawClusterv1.cc
References _energy, _phi, _r, _z, clusterid, prop_map, and towermap.
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/CaloBase/RawClusterv1.h
coresoftware/blob/master/offline/packages/CaloBase/RawClusterv1.cc