Analysis Software: LBT Class Reference
LBT Class Reference
#include <JETSCAPE/blob/main/src/jet/LBT.h>
Public Member Functions
LBT ()
virtual ~LBT ()
void Init ()
void DoEnergyLoss (double deltaT, double time, double Q2, vector< Parton > &pIn, vector< Parton > &pOut)
void WriteTask (weak_ptr< JetScapeWriter > w)
Public Member Functions inherited from Jetscape::JetEnergyLossModule< LBT >
virtual shared_ptr< JetEnergyLoss > Clone () const override
Deep copy constructor. The goal is to not have to initialize Modules multiple times.
void SetActive (bool m_active_exec)
Override deactivation.
Public Member Functions inherited from Jetscape::JetEnergyLoss
JetEnergyLoss ()
JetEnergyLoss (const JetEnergyLoss &j)
virtual ~JetEnergyLoss ()
virtual void Exec () final
virtual void Clear ()
void SetQhat (double m_qhat)
const double GetQhat () const
void AddShowerInitiatingParton (shared_ptr< Parton > p)
shared_ptr< Parton > GetShowerInitiatingParton ()
void PrintShowerInitiatingParton ()
double GetDeltaT ()
double GetMaxT ()
shared_ptr< PartonShower > GetShower ()
void SetJetSignalConnected (bool m_jetSignalConnected)
TODO: Remove.
const bool GetJetSignalConnected () const
void SetEdensitySignalConnected (bool m_edensitySignalConnected)
const bool GetEdensitySignalConnected () const
void SetGetHydroCellSignalConnected (bool m_GetHydroCellSignalConnected)
const bool GetGetHydroCellSignalConnected ()
void SetGetHydroTau0SignalConnected (bool m_GetHydroTau0SignalConnected)
const bool GetGetHydroTau0SignalConnected ()
void SetSentInPartonsConnected (bool m_SentInPartonsConnected)
const bool GetSentInPartonsConnected ()
void add_a_liquefier (std::shared_ptr< LiquefierBase > new_liquefier)
std::weak_ptr< LiquefierBase > get_liquefier ()
void SendFinalStatePartons (vector< vector< shared_ptr< Parton >>> &fPartons)
void GetFinalPartonsForEachShower (shared_ptr< PartonShower > shower)
Public Member Functions inherited from Jetscape::JetScapeModuleBase
JetScapeModuleBase ()
JetScapeModuleBase (string m_name)
virtual ~JetScapeModuleBase ()
void SetXMLMainFileName (string m_name)
string GetXMLMainFileName ()
void SetXMLUserFileName (string m_name)
string GetXMLUserFileName ()
shared_ptr< std::mt19937 > GetMt19937Generator ()
tinyxml2::XMLElement * GetXMLElement (std::initializer_list< const char * > path, bool isRequired=true)
std::string GetXMLElementText (std::initializer_list< const char * > path, bool isRequired=true)
int GetXMLElementInt (std::initializer_list< const char * > path, bool isRequired=true)
double GetXMLElementDouble (std::initializer_list< const char * > path, bool isRequired=true)
Public Member Functions inherited from Jetscape::JetScapeTask
JetScapeTask ()
virtual ~JetScapeTask ()
virtual void Finish ()
virtual void ExecuteTasks ()
virtual void ExecuteTask ()
virtual void InitTask ()
virtual void InitTasks ()
virtual void ClearTasks ()
virtual void ClearTask ()
virtual void FinishTask ()
virtual void FinishTasks ()
virtual void WriteTasks (weak_ptr< JetScapeWriter > w)
virtual void CollectHeader (weak_ptr< JetScapeWriter > w)
virtual void CollectHeaders (weak_ptr< JetScapeWriter > w)
virtual void Add (shared_ptr< JetScapeTask > m_tasks)
virtual const int GetMyTaskNumber () const
const vector< shared_ptr
< JetScapeTask > > GetTaskList () const
shared_ptr< JetScapeTask > GetTaskAt (int i)
void EraseTaskLast ()
void EraseTaskAt (int i)
void ResizeTaskList (int i)
void ClearTaskList ()
int GetNumberOfTasks ()
const bool GetActive () const
void SetActive (bool m_active_exec)
void SetId (string m_id)
const string GetId () const
const shared_ptr
< JetScapeModuleMutex > GetMutex () const
void SetMutex (shared_ptr< JetScapeModuleMutex > m_mutex)
Public Member Functions inherited from sigslot::has_slots< sigslot::multi_threaded_local >
has_slots ()
has_slots (const has_slots &hs)
void signal_connect (_signal_base< sigslot::multi_threaded_local > *sender)
void signal_disconnect (_signal_base< sigslot::multi_threaded_local > *sender)
virtual ~has_slots ()
void disconnect_all ()
Private Member Functions
void LBT0 (int &n, double &ti)
void trans (double v[4], double p[4])
void transback (double v[4], double p[4])
float ran0 (long *idum)
double alphas0 (int &Kalphas, double temp0)
double DebyeMass2 (int &Kqhat0, double alphas, double temp0)
void lam (int KATT0, double &RTE, double E, double T, double &T1, double &T2, double &E1, double &E2, int &iT1, int &iT2, int &iE1, int &iE2)
void flavor (int &CT, int &KATT0, int &KATT2, int &KATT3, double RTE, double E, double T, double &T1, double &T2, double &E1, double &E2, int &iT1, int &iT2, int &iE1, int &iE2)
void linear (int KATT, double E, double T, double &T1, double &T2, double &E1, double &E2, int &iT1, int &iT2, int &iE1, int &iE2, double &RTEg, double &RTEg1, double &RTEg2, double &RTEg3, double &RTEq, double &RTEq3, double &RTEq4, double &RTEq5, double &RTEq6, double &RTEq7, double &RTEq8, double &RTEHQ, double &RTEHQ11, double &RTEHQ12, double &qhatTP)
void twflavor (int &CT, int &KATT0, int &KATT2, double E, double T)
void twlinear (int KATT, double E, double T, double &RTEg1, double &RTEg2, double &RTEq6, double &RTEq7, double &RTEq8)
void colljet22 (int CT, double temp, double qhat0ud, double v0[4], double p0[4], double p2[4], double p3[4], double p4[4], double &qt)
void twcoll (int CT, double qhat0ud, double v0[4], double p0[4], double p2[4])
void titau (double ti, double vf[4], double vp[4], double p0[4], double &Vx, double &Vy, double &Veta, double &Xtau)
void rotate (double px, double py, double pz, double p[4], int icc)
int KPoisson (double alambda)
void radiationHQ (int parID, double qhat0ud, double v0[4], double P2[4], double P3[4], double P4[4], double Pj0[4], int &ic, double Tdiff, double HQenergy, double max_Ng, double temp_med, double xLow, double xInt)
void collHQ22 (int CT, double temp, double qhat, double v0[4], double p0[4], double p2[4], double p3[4], double p4[4], double &qt)
double Mqc2qc (double s, double t, double M)
double Mgc2gc (double s, double t, double M)
void collHQ23 (int parID, double temp_med, double qhat0ud, double v0[4], double p0[4], double p2[4], double p3[4], double p4[4], double qt, int &ic, double Tdiff, double HQenergy, double max_Ng, double xLow, double xInt)
double dNg_over_dxdydt (int parID, double x0g, double y0g, double HQenergy, double HQmass, double temp_med, double Tdiff)
double tau_f (double x0g, double y0g, double HQenergy, double HQmass)
double splittingP (int parID, double z0g)
double lambdas (double kTFnc)
double nflavor (double kTFnc)
double alphasHQ (double kTFnc, double tempFnc)
double nHQgluon (int parID, double dtLRF, double &time_gluon, double &temp_med, double &HQenergy, double &max_Ng)
void read_xyMC (int &numXY)
void jetInitialize (int numXY)
void setJetX (int numXY)
void read_tables ()
void jetClean ()
void setParameter (string fileName)
int checkParameter (int nArg)
Private Attributes
const double pi = 3.1415926
const double epsilon = 1e-6
const double CA = 3.0
const double CF = 4.0 / 3.0
const double sctr = 0.1973
const int lightOut = 1
const int heavyOut = 0
const int outFormat
const double cutOut
int vacORmed = 1
int bulkFlag = 0
double temp0 = 0.25
double hydro_Tc = 0.165
double temp00
double KPamp = 0.0
double KPsig = 5.0
double KTamp = 0.0
double KTsig = 0.05 * hydro_Tc
double preKT = 0.3 / 0.3
double scaleAK = 2.0
double KPfactor
double KTfactor
double Kfactor
double runKT
double fixedLog
double runLog
double scaleMu2
double runAlphas
int initHardFlag
int fixMomentum = 0
int fixPosition = 1
int run_alphas = 1
int flagJetX
int Kjet = 21
double ipTmin = 0.0
double ipTmax = 800.0
double eta_cut = 0.5
double ener = 50.0
double amss = 0.0
int nj = 1000
int ncall = 1
int np
int nprint = 100
int tauswitch
double tau0 = 0.0
double dtau = 0.1
double tauend = 4.0
double time0
double dt
double timend
int Kprimary
int KINT0 = 1
int Kqhat0 = 2
int Kalphas = 1
double Ecut = 0.0
double fixAlphas = 0.3
int KINT
double alphas
double qhat0
double qhat00
std::uniform_real_distribution
< double > ZeroOneDistribution
double qhat_over_T3
double D2piT
const double HQener_max = 1000.0
const double t_max_1 = 20.0
const double t_max_2 = 270.0
const double t_max = t_max_2
const double temp_max = 0.65
const double temp_min = 0.15
double delta_tg_1 = t_max_1 / t_gn_1
double delta_tg_2 = (t_max_2 - t_max_1) / t_gn_2
double delta_temp = (temp_max - temp_min) / temp_gn
double delta_HQener = HQener_max / HQener_gn
int icl22
int icl23
int iclrad
int isp
int counth100 = 0
double qhat
double dng0 [101][101] = {{0.0}}
double Vtemp [4] = {0.0}
double tirad [dimParList] = {0.0}
double tiscatter [dimParList] = {0.0}
double tiform [dimParList] = {0.0}
double Tint_lrf [dimParList] = {0.0}
double eGluon = 0.0
double nGluon = 0.0
double dEel = 0.0
double radng [dimParList] = {0.0}
double xwm [3] = {0.0}
double wkt2m
double vf [4] = {0.0}
double vfcar [4] = {0.0}
double vp [4] = {0.0}
double vc0 [4] = {0.0}
double vc [4] = {0.0}
double pc0 [4] = {0.0}
double pc2 [4] = {0.0}
double pc3 [4] = {0.0}
double pc4 [4] = {0.0}
double p0 [4] = {0.0}
double p2 [4] = {0.0}
double p3 [4] = {0.0}
double p4 [4] = {0.0}
double pc00 [4] = {0.0}
double pc30 [4] = {0.0}
double pc01 [4] = {0.0}
double pb [4] = {0.0}
double Pj0 [4] = {0.0}
double V [4][dimParList] = {{0.0}}
double P [7][dimParList] = {{0.0}}
double V0 [4][dimParList] = {{0.0}}
double P0 [7][dimParList] = {{0.0}}
double Prad [4][dimParList] = {{0.0}}
double WT [dimParList] = {0}
double WT0 [dimParList] = {0}
int NR [dimParList] = {0}
int KATT1 [dimParList] = {0}
int KATT10 [dimParList] = {0}
double PGm [4] = {0.0}
double tjp [dimParList] = {0.0}
double Vfrozen [4][dimParList] = {{0.0}}
double Vfrozen0 [4][dimParList] = {{0.0}}
double Ecmcut = 2.0
double Tfrozen [dimParList] = {0.0}
double Tfrozen0 [dimParList] = {0.0}
double vcfrozen [4][dimParList] = {{0.0}}
double vcfrozen0 [4][dimParList] = {{0.0}}
double VV [4][dimParList] = {{0.0}}
double VV0 [4][dimParList] = {{0.0}}
double PP [4][dimParList] = {{0.0}}
double PP0 [4][dimParList] = {{0.0}}
int CAT [dimParList] = {0}
int CAT0 [dimParList] = {0}
int ncut
int ncut0
int n_coll22 = 0
int n_coll23 = 0
int ng_coll23 = 0
int ng_nrad = 0
int n_radiation = 0
int ng_radiation = 0
int n_gluon = 0
int n_sp1 = 0
int n_sp2 = 0
double min_p1 = 0.0
double max_p1 = 1000.0
double bin_p1 = (max_p1 - min_p1) / N_p1
double min_T = 0.1
double max_T = 0.7
double bin_T = (max_T - min_T) / N_T
double min_e2 = 0.0
double max_e2 = 15.0
double bin_e2 = (max_e2 - min_e2) / N_e2
int loopN = 1000
int numInitXY = 0
int flagScatter
int flag_update
int flag_update0
double Q00
double Q0
double tStart
Static Private Attributes
static bool flag_init = 0
static double Rg [60][20]
static double Rg1 [60][20] = {{0.0}}
static double Rg2 [60][20] = {{0.0}}
static double Rg3 [60][20] = {{0.0}}
static double Rq [60][20]
static double Rq3 [60][20] = {{0.0}}
static double Rq4 [60][20] = {{0.0}}
static double Rq5 [60][20] = {{0.0}}
static double Rq6 [60][20] = {{0.0}}
static double Rq7 [60][20] = {{0.0}}
static double Rq8 [60][20] = {{0.0}}
static double qhatLQ [60][20] = {{0.0}}
static double qhatG [60][20] = {{0.0}}
static double RHQ [60][20] = {{0.0}}
static double RHQ11 [60][20] = {{0.0}}
static double RHQ12 [60][20] = {{0.0}}
static double qhatHQ [60][20] = {{0.0}}
static const int HQener_gn = 500
static const int t_gn_1 = 100
static const int t_gn_2 = 125
static const int t_gn = t_gn_1 + t_gn_2
static const int temp_gn = 100
static double dNg_over_dt_c [t_gn+2][temp_gn+1][HQener_gn+1] = {{{0.0}}}
static double dNg_over_dt_q [t_gn+2][temp_gn+1][HQener_gn+1] = {{{0.0}}}
static double dNg_over_dt_g [t_gn+2][temp_gn+1][HQener_gn+1] = {{{0.0}}}
static double max_dNgfnc_c [t_gn+2][temp_gn+1][HQener_gn+1] = {{{0.0}}}
static double max_dNgfnc_q [t_gn+2][temp_gn+1][HQener_gn+1] = {{{0.0}}}
static double max_dNgfnc_g [t_gn+2][temp_gn+1][HQener_gn+1] = {{{0.0}}}
static const int maxMC = 2000000
static double initMCX [maxMC] = {0.0}
static double initMCY [maxMC] = {0.0}
static const int dimParList = 50
static const int N_p1 = 500
static const int N_T = 60
static const int N_e2 = 75
static double distFncB [N_T][N_p1][N_e2] = {{{0.0}}}
static double distFncF [N_T][N_p1][N_e2] = {{{0.0}}}
static double distMaxB [N_T][N_p1][N_e2] = {{{0.0}}}
static double distMaxF [N_T][N_p1][N_e2] = {{{0.0}}}
static double distFncBM [N_T][N_p1] = {{0.0}}
static double distFncFM [N_T][N_p1] = {{0.0}}
static RegisterJetScapeModule
< LBT > reg
Additional Inherited Members
Static Public Member Functions inherited from Jetscape::JetScapeModuleBase
static int GetCurrentEvent ()
static void IncrementCurrentEvent ()
Public Attributes inherited from Jetscape::JetEnergyLoss
sigslot::signal5< double,
double, double, double,
std::unique_ptr< FluidCellInfo >
&, multi_threaded_local > GetHydroCellSignal
Core signal to receive information from the medium.
sigslot::signal1< double
&, multi_threaded_local > GetHydroTau0Signal
sigslot::signal2< int, double,
multi_threaded_local > jetSignal
sigslot::signal2< int, double
&, multi_threaded_local > edensitySignal
sigslot::signal5< double,
double, double, vector< Parton >
&, vector< Parton >
&, multi_threaded_local > SentInPartons
Protected Member Functions inherited from Jetscape::JetEnergyLossModule< LBT >
bool TakeResponsibilityFor (Parton &p)
Protected Attributes inherited from Jetscape::JetEnergyLoss
std::weak_ptr< LiquefierBase > liquefier_ptr
Detailed Description
Definition at line 40 of file LBT.h.
View newest version in sPHENIX GitHub at line 40 of file LBT.h
Constructor & Destructor Documentation
LBT::LBT ()
Definition at line 76 of file LBT.cc.
View newest version in sPHENIX GitHub at line 76 of file LBT.cc
References SetId(), and VERBOSE.
LBT::~LBT () virtual
Definition at line 85 of file LBT.cc.
View newest version in sPHENIX GitHub at line 85 of file LBT.cc
References VERBOSE.
Member Function Documentation
double LBT::alphas0 (int & Kalphas, double temp0) private
Definition at line 1651 of file LBT.cc.
View newest version in sPHENIX GitHub at line 1651 of file LBT.cc
References TauVsDIS_MachineLearning_Differentiation::X.
double LBT::alphasHQ (double kTFnc, double tempFnc) private
Definition at line 3960 of file LBT.cc.
View newest version in sPHENIX GitHub at line 3960 of file LBT.cc
References alphas().
int LBT::checkParameter (int nArg) private
Definition at line 4453 of file LBT.cc.
View newest version in sPHENIX GitHub at line 4453 of file LBT.cc
void LBT::collHQ22 (int CT, double temp, double qhat, double v0[4], double p0[4], double p2[4], double p3[4], double p4[4], double & qt) private
Definition at line 2633 of file LBT.cc.
View newest version in sPHENIX GitHub at line 2633 of file LBT.cc
References Acts::UnitConstants::e, generate_files_AA::ff, and Jetscape::pi.
void LBT::collHQ23 (int parID, double temp_med, double qhat0ud, double v0[4], double p0[4], double p2[4], double p3[4], double p4[4], double qt, int & ic, double Tdiff, double HQenergy, double max_Ng, double xLow, double xInt) private
Definition at line 3131 of file LBT.cc.
View newest version in sPHENIX GitHub at line 3131 of file LBT.cc
References Acts::UnitConstants::e, JSINFO, MAGENTA, and Jetscape::pi.
void LBT::colljet22 (int CT, double temp, double qhat0ud, double v0[4], double p0[4], double p2[4], double p3[4], double p4[4], double & qt) private
Definition at line 2265 of file LBT.cc.
View newest version in sPHENIX GitHub at line 2265 of file LBT.cc
References std::tr1::f1, std::tr1::f2, generate_files_AA::ff, and Jetscape::pi.
double LBT::DebyeMass2 (int & Kqhat0, double alphas, double temp0) private
Definition at line 1663 of file LBT.cc.
View newest version in sPHENIX GitHub at line 1663 of file LBT.cc
References JSWARN, and Jetscape::pi.
double LBT::dNg_over_dxdydt (int parID, double x0g, double y0g, double HQenergy, double HQmass, double temp_med, double Tdiff) private
Definition at line 4046 of file LBT.cc.
View newest version in sPHENIX GitHub at line 4046 of file LBT.cc
References Jetscape::pi, and AlignmentDefs::sctr.
void LBT::DoEnergyLoss (double deltaT, double time, double Q2, vector< Parton > & pIn, vector< Parton > & pOut) virtual
Default function to perform the energy loss for partons at time "time". It should be overridden by different energy loss tasks.
Parameters
deltaT Step-size.
time Current time.
Q2 Current virtuality of the parton.
pIn Vector of current partons.
pOut Vector of partons at time "time+deltaT".
Reimplemented from Jetscape::JetEnergyLoss.
Definition at line 157 of file LBT.cc.
View newest version in sPHENIX GitHub at line 157 of file LBT.cc
References dtau, i, j, JSDEBUG, JSWARN, k, MAGENTA, P(), Jetscape::photonid, train_ambiguity_solver::pid, Acts::Test::time, VERBOSESHOWER, and physmon_track_finding_ttbar::z.
void LBT::flavor (int & CT, int & KATT0, int & KATT2, int & KATT3, double RTE, double E, double T, double & T1, double & T2, double & E1, double & E2, int & iT1, int & iT2, int & iE1, int & iE2) private
Definition at line 1777 of file LBT.cc.
View newest version in sPHENIX GitHub at line 1777 of file LBT.cc
References KFPMath::a, KFPMath::b, std::tr1::f1, std::tr1::f2, R0, R1, R2, R3, and R4.
void LBT::Init () virtual
It reads the input parameters from a XML file under the tag <Eloss>. Sets the Parton class inP and PartonShower class pShower to null. Also initializes the tasks attached to the JetEnergyLoss module.
Reimplemented from Jetscape::JetEnergyLoss.
Definition at line 87 of file LBT.cc.
View newest version in sPHENIX GitHub at line 87 of file LBT.cc
References alphas(), dtau, JSDEBUG, JSINFO, MAGENTA, physmon_simulation::s, and tau0.
void LBT::jetClean () private
Definition at line 4095 of file LBT.cc.
View newest version in sPHENIX GitHub at line 4095 of file LBT.cc
References i, and P().
void LBT::jetInitialize (int numXY) private
Definition at line 4171 of file LBT.cc.
View newest version in sPHENIX GitHub at line 4171 of file LBT.cc
References i, j, P(), ActsTests::PropagationDatasets::phi, Jetscape::pi, and tau0.
int LBT::KPoisson (double alambda) private
Definition at line 3803 of file LBT.cc.
View newest version in sPHENIX GitHub at line 3803 of file LBT.cc
References merge_hashes::p, and material_mapping_optimisation::target.
void LBT::lam (int KATT0, double & RTE, double E, double T, double & T1, double & T2, double & E1, double & E2, int & iT1, int & iT2, int & iE1, int & iE2) private
Definition at line 1735 of file LBT.cc.
View newest version in sPHENIX GitHub at line 1735 of file LBT.cc
References T1.
double LBT::lambdas (double kTFnc) private
Definition at line 3999 of file LBT.cc.
View newest version in sPHENIX GitHub at line 3999 of file LBT.cc
void LBT::LBT0 (int & n, double & ti) private
Definition at line 481 of file LBT.cc.
View newest version in sPHENIX GitHub at line 481 of file LBT.cc
References alphas(), E, Jetscape::FluidCellInfo::entropy_density, i, j, JSWARN, k, Acts::UnitConstants::m, P(), Jetscape::pi, Jetscape::rounding_error, Acts::UnitConstants::T, T1, T2, Jetscape::FluidCellInfo::temperature, Jetscape::FluidCellInfo::vx, Jetscape::FluidCellInfo::vy, and Jetscape::FluidCellInfo::vz.
void LBT::linear (int KATT, double E, double T, double & T1, double & T2, double & E1, double & E2, int & iT1, int & iT2, int & iE1, int & iE2, double & RTEg, double & RTEg1, double & RTEg2, double & RTEg3, double & RTEq, double & RTEq3, double & RTEq4, double & RTEq5, double & RTEq6, double & RTEq7, double & RTEq8, double & RTEHQ, double & RTEHQ11, double & RTEHQ12, double & qhatTP) private
Definition at line 1947 of file LBT.cc.
View newest version in sPHENIX GitHub at line 1947 of file LBT.cc
References T1.
double LBT::Mgc2gc (double s, double t, double M) private
Definition at line 3939 of file LBT.cc.
View newest version in sPHENIX GitHub at line 3939 of file LBT.cc
References t, and physmon_ckf_tracking::u.
double LBT::Mqc2qc (double s, double t, double M) private
Definition at line 3927 of file LBT.cc.
View newest version in sPHENIX GitHub at line 3927 of file LBT.cc
References t, and physmon_ckf_tracking::u.
double LBT::nflavor (double kTFnc) private
Definition at line 3980 of file LBT.cc.
View newest version in sPHENIX GitHub at line 3980 of file LBT.cc
double LBT::nHQgluon (int parID, double dtLRF, double & time_gluon, double & temp_med, double & HQenergy, double & max_Ng) private
Definition at line 3822 of file LBT.cc.
View newest version in sPHENIX GitHub at line 3822 of file LBT.cc
void LBT::radiationHQ (int parID, double qhat0ud, double v0[4], double P2[4], double P3[4], double P4[4], double Pj0[4], int & ic, double Tdiff, double HQenergy, double max_Ng, double temp_med, double xLow, double xInt) private
Definition at line 3410 of file LBT.cc.
View newest version in sPHENIX GitHub at line 3410 of file LBT.cc
References Acts::UnitConstants::e, i, and Jetscape::pi.
float LBT::ran0 (long * idum) private
Definition at line 1591 of file LBT.cc.
View newest version in sPHENIX GitHub at line 1591 of file LBT.cc
References j, and k.
void LBT::read_tables () private
Definition at line 1441 of file LBT.cc.
View newest version in sPHENIX GitHub at line 1441 of file LBT.cc
References std::tr1::f1, i, it, j, k, and n.
void LBT::read_xyMC (int & numXY) private
Definition at line 4069 of file LBT.cc.
View newest version in sPHENIX GitHub at line 4069 of file LBT.cc
void LBT::rotate (double px, double py, double pz, double p[4], int icc) private
Definition at line 3751 of file LBT.cc.
View newest version in sPHENIX GitHub at line 3751 of file LBT.cc
References E, and physmon_track_finding_ttbar::pt.
void LBT::setJetX (int numXY) private
Definition at line 4271 of file LBT.cc.
View newest version in sPHENIX GitHub at line 4271 of file LBT.cc
References i, P(), and tau0.
void LBT::setParameter (string fileName) private
Definition at line 4311 of file LBT.cc.
View newest version in sPHENIX GitHub at line 4311 of file LBT.cc
References dtau, digitization_config::input, line, str, and tau0.
double LBT::splittingP (int parID, double z0g) private
Definition at line 4018 of file LBT.cc.
View newest version in sPHENIX GitHub at line 4018 of file LBT.cc
double LBT::tau_f (double x0g, double y0g, double HQenergy, double HQmass) private
Definition at line 4034 of file LBT.cc.
View newest version in sPHENIX GitHub at line 4034 of file LBT.cc
void LBT::titau (double ti, double vf[4], double vp[4], double p0[4], double & Vx, double & Vy, double & Veta, double & Xtau) private
Definition at line 1698 of file LBT.cc.
View newest version in sPHENIX GitHub at line 1698 of file LBT.cc
References etas.
void LBT::trans (double v[4], double p[4]) private
Definition at line 2242 of file LBT.cc.
View newest version in sPHENIX GitHub at line 2242 of file LBT.cc
void LBT::transback (double v[4], double p[4]) private
Definition at line 2253 of file LBT.cc.
View newest version in sPHENIX GitHub at line 2253 of file LBT.cc
void LBT::twcoll (int CT, double qhat0ud, double v0[4], double p0[4], double p2[4]) private
Definition at line 2864 of file LBT.cc.
View newest version in sPHENIX GitHub at line 2864 of file LBT.cc
References Jetscape::pi.
void LBT::twflavor (int & CT, int & KATT0, int & KATT2, double E, double T) private
Definition at line 2039 of file LBT.cc.
View newest version in sPHENIX GitHub at line 2039 of file LBT.cc
References KFPMath::a, KFPMath::b, R1, and R2.
void LBT::twlinear (int KATT, double E, double T, double & RTEg1, double & RTEg2, double & RTEq6, double & RTEq7, double & RTEq8) private
Definition at line 2174 of file LBT.cc.
View newest version in sPHENIX GitHub at line 2174 of file LBT.cc
References T1, and T2.
void LBT::WriteTask (weak_ptr< JetScapeWriter > w) virtual
Write output information for each tasks/subtasks attached to the JetEnergyLoss module using JetScapeWriter functionality.
Parameters
w A pointer of type JetScapeWriter.
Reimplemented from Jetscape::JetEnergyLoss.
Definition at line 148 of file LBT.cc.
View newest version in sPHENIX GitHub at line 148 of file LBT.cc
References f, and VERBOSE.
Member Data Documentation
double LBT::alphas private
Definition at line 137 of file LBT.h.
View newest version in sPHENIX GitHub at line 137 of file LBT.h
double LBT::amss = 0.0 private
Definition at line 108 of file LBT.h.
View newest version in sPHENIX GitHub at line 108 of file LBT.h
double LBT::bin_e2 = (max_e2 - min_e2) / N_e2 private
Definition at line 317 of file LBT.h.
View newest version in sPHENIX GitHub at line 317 of file LBT.h
double LBT::bin_p1 = (max_p1 - min_p1) / N_p1 private
Definition at line 311 of file LBT.h.
View newest version in sPHENIX GitHub at line 311 of file LBT.h
double LBT::bin_T = (max_T - min_T) / N_T private
Definition at line 314 of file LBT.h.
View newest version in sPHENIX GitHub at line 314 of file LBT.h
int LBT::bulkFlag = 0 private
Definition at line 78 of file LBT.h.
View newest version in sPHENIX GitHub at line 78 of file LBT.h
const double LBT::CA = 3.0 private
Definition at line 64 of file LBT.h.
View newest version in sPHENIX GitHub at line 64 of file LBT.h
int LBT::CAT[dimParList] = {0} private
Definition at line 286 of file LBT.h.
View newest version in sPHENIX GitHub at line 286 of file LBT.h
int LBT::CAT0[dimParList] = {0} private
Definition at line 287 of file LBT.h.
View newest version in sPHENIX GitHub at line 287 of file LBT.h
const double LBT::CF = 4.0 / 3.0 private
Definition at line 65 of file LBT.h.
View newest version in sPHENIX GitHub at line 65 of file LBT.h
int LBT::counth100 = 0 private
Definition at line 208 of file LBT.h.
View newest version in sPHENIX GitHub at line 208 of file LBT.h
const double LBT::cutOut private
Initial value:
=
      epsilon
Definition at line 73 of file LBT.h.
View newest version in sPHENIX GitHub at line 73 of file LBT.h
double LBT::D2piT private
Definition at line 170 of file LBT.h.
View newest version in sPHENIX GitHub at line 170 of file LBT.h
double LBT::dEel = 0.0 private
Definition at line 226 of file LBT.h.
View newest version in sPHENIX GitHub at line 226 of file LBT.h
double LBT::delta_HQener = HQener_max / HQener_gn private
Definition at line 195 of file LBT.h.
View newest version in sPHENIX GitHub at line 195 of file LBT.h
double LBT::delta_temp = (temp_max - temp_min) / temp_gn private
Definition at line 194 of file LBT.h.
View newest version in sPHENIX GitHub at line 194 of file LBT.h
double LBT::delta_tg_1 = t_max_1 / t_gn_1 private
Definition at line 192 of file LBT.h.
View newest version in sPHENIX GitHub at line 192 of file LBT.h
double LBT::delta_tg_2 = (t_max_2 - t_max_1) / t_gn_2 private
Definition at line 193 of file LBT.h.
View newest version in sPHENIX GitHub at line 193 of file LBT.h
const int LBT::dimParList = 50 static private
Definition at line 218 of file LBT.h.
View newest version in sPHENIX GitHub at line 218 of file LBT.h
double LBT::distFncB = {{{0.0}}} static private
Definition at line 306 of file LBT.h.
View newest version in sPHENIX GitHub at line 306 of file LBT.h
double LBT::distFncBM = {{0.0}} static private
Definition at line 308 of file LBT.h.
View newest version in sPHENIX GitHub at line 308 of file LBT.h
double LBT::distFncF = {{{0.0}}} static private
Definition at line 306 of file LBT.h.
View newest version in sPHENIX GitHub at line 306 of file LBT.h
double LBT::distFncFM = {{0.0}} static private
Definition at line 308 of file LBT.h.
View newest version in sPHENIX GitHub at line 308 of file LBT.h
double LBT::distMaxB = {{{0.0}}} static private
Definition at line 306 of file LBT.h.
View newest version in sPHENIX GitHub at line 306 of file LBT.h
double LBT::distMaxF = {{{0.0}}} static private
Definition at line 306 of file LBT.h.
View newest version in sPHENIX GitHub at line 306 of file LBT.h
double LBT::dng0[101][101] = {{0.0}} private
Definition at line 212 of file LBT.h.
View newest version in sPHENIX GitHub at line 212 of file LBT.h
double LBT::dNg_over_dt_c = {{{0.0}}} static private
Definition at line 179 of file LBT.h.
View newest version in sPHENIX GitHub at line 179 of file LBT.h
double LBT::dNg_over_dt_g = {{{0.0}}} static private
Definition at line 181 of file LBT.h.
View newest version in sPHENIX GitHub at line 181 of file LBT.h
double LBT::dNg_over_dt_q = {{{0.0}}} static private
Definition at line 180 of file LBT.h.
View newest version in sPHENIX GitHub at line 180 of file LBT.h
double LBT::dt private
Definition at line 124 of file LBT.h.
View newest version in sPHENIX GitHub at line 124 of file LBT.h
double LBT::dtau = 0.1 private
Definition at line 119 of file LBT.h.
View newest version in sPHENIX GitHub at line 119 of file LBT.h
double LBT::Ecmcut = 2.0 private
Definition at line 276 of file LBT.h.
View newest version in sPHENIX GitHub at line 276 of file LBT.h
double LBT::Ecut = 0.0 private
Definition at line 133 of file LBT.h.
View newest version in sPHENIX GitHub at line 133 of file LBT.h
double LBT::eGluon = 0.0 private
Definition at line 224 of file LBT.h.
View newest version in sPHENIX GitHub at line 224 of file LBT.h
double LBT::ener = 50.0 private
Definition at line 107 of file LBT.h.
View newest version in sPHENIX GitHub at line 107 of file LBT.h
const double LBT::epsilon = 1e-6 private
Definition at line 63 of file LBT.h.
View newest version in sPHENIX GitHub at line 63 of file LBT.h
double LBT::eta_cut = 0.5 private
Definition at line 106 of file LBT.h.
View newest version in sPHENIX GitHub at line 106 of file LBT.h
double LBT::fixAlphas = 0.3 private
Definition at line 134 of file LBT.h.
View newest version in sPHENIX GitHub at line 134 of file LBT.h
double LBT::fixedLog private
Definition at line 93 of file LBT.h.
View newest version in sPHENIX GitHub at line 93 of file LBT.h
int LBT::fixMomentum = 0 private
Definition at line 98 of file LBT.h.
View newest version in sPHENIX GitHub at line 98 of file LBT.h
int LBT::fixPosition = 1 private
Definition at line 99 of file LBT.h.
View newest version in sPHENIX GitHub at line 99 of file LBT.h
bool LBT::flag_init = 0 static private
Definition at line 144 of file LBT.h.
View newest version in sPHENIX GitHub at line 144 of file LBT.h
int LBT::flag_update private
Definition at line 323 of file LBT.h.
View newest version in sPHENIX GitHub at line 323 of file LBT.h
int LBT::flag_update0 private
Definition at line 323 of file LBT.h.
View newest version in sPHENIX GitHub at line 323 of file LBT.h
int LBT::flagJetX private
Initial value:
=
      0
Definition at line 101 of file LBT.h.
View newest version in sPHENIX GitHub at line 101 of file LBT.h
int LBT::flagScatter private
Definition at line 323 of file LBT.h.
View newest version in sPHENIX GitHub at line 323 of file LBT.h
const int LBT::heavyOut = 0 private
Definition at line 70 of file LBT.h.
View newest version in sPHENIX GitHub at line 70 of file LBT.h
const int LBT::HQener_gn = 500 static private
Definition at line 173 of file LBT.h.
View newest version in sPHENIX GitHub at line 173 of file LBT.h
const double LBT::HQener_max = 1000.0 private
Definition at line 186 of file LBT.h.
View newest version in sPHENIX GitHub at line 186 of file LBT.h
double LBT::hydro_Tc = 0.165 private
Definition at line 80 of file LBT.h.
View newest version in sPHENIX GitHub at line 80 of file LBT.h
int LBT::icl22 private
Definition at line 202 of file LBT.h.
View newest version in sPHENIX GitHub at line 202 of file LBT.h
int LBT::icl23 private
Definition at line 203 of file LBT.h.
View newest version in sPHENIX GitHub at line 203 of file LBT.h
int LBT::iclrad private
Definition at line 204 of file LBT.h.
View newest version in sPHENIX GitHub at line 204 of file LBT.h
int LBT::initHardFlag private
Initial value:
=
      2
Definition at line 96 of file LBT.h.
View newest version in sPHENIX GitHub at line 96 of file LBT.h
double LBT::initMCX = {0.0} static private
Definition at line 199 of file LBT.h.
View newest version in sPHENIX GitHub at line 199 of file LBT.h
double LBT::initMCY = {0.0} static private
Definition at line 199 of file LBT.h.
View newest version in sPHENIX GitHub at line 199 of file LBT.h
double LBT::ipTmax = 800.0 private
Definition at line 105 of file LBT.h.
View newest version in sPHENIX GitHub at line 105 of file LBT.h
double LBT::ipTmin = 0.0 private
Definition at line 104 of file LBT.h.
View newest version in sPHENIX GitHub at line 104 of file LBT.h
int LBT::isp private
Definition at line 205 of file LBT.h.
View newest version in sPHENIX GitHub at line 205 of file LBT.h
int LBT::Kalphas = 1 private
Definition at line 132 of file LBT.h.
View newest version in sPHENIX GitHub at line 132 of file LBT.h
int LBT::KATT1[dimParList] = {0} private
Definition at line 269 of file LBT.h.
View newest version in sPHENIX GitHub at line 269 of file LBT.h
int LBT::KATT10[dimParList] = {0} private
Definition at line 270 of file LBT.h.
View newest version in sPHENIX GitHub at line 270 of file LBT.h
double LBT::Kfactor private
Definition at line 92 of file LBT.h.
View newest version in sPHENIX GitHub at line 92 of file LBT.h
int LBT::KINT private
Definition at line 136 of file LBT.h.
View newest version in sPHENIX GitHub at line 136 of file LBT.h
int LBT::KINT0 = 1 private
Definition at line 130 of file LBT.h.
View newest version in sPHENIX GitHub at line 130 of file LBT.h
int LBT::Kjet = 21 private
Definition at line 103 of file LBT.h.
View newest version in sPHENIX GitHub at line 103 of file LBT.h
double LBT::KPamp = 0.0 private
Definition at line 85 of file LBT.h.
View newest version in sPHENIX GitHub at line 85 of file LBT.h
double LBT::KPfactor private
Definition at line 92 of file LBT.h.
View newest version in sPHENIX GitHub at line 92 of file LBT.h
int LBT::Kprimary private
Initial value:
=
      0
Definition at line 128 of file LBT.h.
View newest version in sPHENIX GitHub at line 128 of file LBT.h
double LBT::KPsig = 5.0 private
Definition at line 86 of file LBT.h.
View newest version in sPHENIX GitHub at line 86 of file LBT.h
int LBT::Kqhat0 = 2 private
Definition at line 131 of file LBT.h.
View newest version in sPHENIX GitHub at line 131 of file LBT.h
double LBT::KTamp = 0.0 private
Definition at line 87 of file LBT.h.
View newest version in sPHENIX GitHub at line 87 of file LBT.h
double LBT::KTfactor private
Definition at line 92 of file LBT.h.
View newest version in sPHENIX GitHub at line 92 of file LBT.h
double LBT::KTsig = 0.05 * hydro_Tc private
Definition at line 88 of file LBT.h.
View newest version in sPHENIX GitHub at line 88 of file LBT.h
const int LBT::lightOut = 1 private
Definition at line 69 of file LBT.h.
View newest version in sPHENIX GitHub at line 69 of file LBT.h
int LBT::loopN = 1000 private
Definition at line 320 of file LBT.h.
View newest version in sPHENIX GitHub at line 320 of file LBT.h
double LBT::max_dNgfnc_c = {{{0.0}}} static private
Definition at line 182 of file LBT.h.
View newest version in sPHENIX GitHub at line 182 of file LBT.h
double LBT::max_dNgfnc_g = {{{0.0}}} static private
Definition at line 184 of file LBT.h.
View newest version in sPHENIX GitHub at line 184 of file LBT.h
double LBT::max_dNgfnc_q = {{{0.0}}} static private
Definition at line 183 of file LBT.h.
View newest version in sPHENIX GitHub at line 183 of file LBT.h
double LBT::max_e2 = 15.0 private
Definition at line 316 of file LBT.h.
View newest version in sPHENIX GitHub at line 316 of file LBT.h
double LBT::max_p1 = 1000.0 private
Definition at line 310 of file LBT.h.
View newest version in sPHENIX GitHub at line 310 of file LBT.h
double LBT::max_T = 0.7 private
Definition at line 313 of file LBT.h.
View newest version in sPHENIX GitHub at line 313 of file LBT.h
const int LBT::maxMC = 2000000 static private
Definition at line 198 of file LBT.h.
View newest version in sPHENIX GitHub at line 198 of file LBT.h
double LBT::min_e2 = 0.0 private
Definition at line 315 of file LBT.h.
View newest version in sPHENIX GitHub at line 315 of file LBT.h
double LBT::min_p1 = 0.0 private
Definition at line 309 of file LBT.h.
View newest version in sPHENIX GitHub at line 309 of file LBT.h
double LBT::min_T = 0.1 private
Definition at line 312 of file LBT.h.
View newest version in sPHENIX GitHub at line 312 of file LBT.h
int LBT::n_coll22 = 0 private
Definition at line 292 of file LBT.h.
View newest version in sPHENIX GitHub at line 292 of file LBT.h
int LBT::n_coll23 = 0 private
Definition at line 293 of file LBT.h.
View newest version in sPHENIX GitHub at line 293 of file LBT.h
const int LBT::N_e2 = 75 static private
Definition at line 305 of file LBT.h.
View newest version in sPHENIX GitHub at line 305 of file LBT.h
int LBT::n_gluon = 0 private
Definition at line 298 of file LBT.h.
View newest version in sPHENIX GitHub at line 298 of file LBT.h
const int LBT::N_p1 = 500 static private
Definition at line 303 of file LBT.h.
View newest version in sPHENIX GitHub at line 303 of file LBT.h
int LBT::n_radiation = 0 private
Definition at line 296 of file LBT.h.
View newest version in sPHENIX GitHub at line 296 of file LBT.h
int LBT::n_sp1 = 0 private
Definition at line 299 of file LBT.h.
View newest version in sPHENIX GitHub at line 299 of file LBT.h
int LBT::n_sp2 = 0 private
Definition at line 300 of file LBT.h.
View newest version in sPHENIX GitHub at line 300 of file LBT.h
const int LBT::N_T = 60 static private
Definition at line 304 of file LBT.h.
View newest version in sPHENIX GitHub at line 304 of file LBT.h
int LBT::ncall = 1 private
Definition at line 110 of file LBT.h.
View newest version in sPHENIX GitHub at line 110 of file LBT.h
int LBT::ncut private
Definition at line 289 of file LBT.h.
View newest version in sPHENIX GitHub at line 289 of file LBT.h
int LBT::ncut0 private
Definition at line 290 of file LBT.h.
View newest version in sPHENIX GitHub at line 290 of file LBT.h
int LBT::ng_coll23 = 0 private
Definition at line 294 of file LBT.h.
View newest version in sPHENIX GitHub at line 294 of file LBT.h
int LBT::ng_nrad = 0 private
Definition at line 295 of file LBT.h.
View newest version in sPHENIX GitHub at line 295 of file LBT.h
int LBT::ng_radiation = 0 private
Definition at line 297 of file LBT.h.
View newest version in sPHENIX GitHub at line 297 of file LBT.h
double LBT::nGluon = 0.0 private
Definition at line 225 of file LBT.h.
View newest version in sPHENIX GitHub at line 225 of file LBT.h
int LBT::nj = 1000 private
Definition at line 109 of file LBT.h.
View newest version in sPHENIX GitHub at line 109 of file LBT.h
int LBT::np private
Definition at line 112 of file LBT.h.
View newest version in sPHENIX GitHub at line 112 of file LBT.h
int LBT::nprint = 100 private
Definition at line 115 of file LBT.h.
View newest version in sPHENIX GitHub at line 115 of file LBT.h
int LBT::NR[dimParList] = {0} private
Definition at line 268 of file LBT.h.
View newest version in sPHENIX GitHub at line 268 of file LBT.h
int LBT::numInitXY = 0 private
Definition at line 322 of file LBT.h.
View newest version in sPHENIX GitHub at line 322 of file LBT.h
const int LBT::outFormat private
Initial value:
=
      2
Definition at line 71 of file LBT.h.
View newest version in sPHENIX GitHub at line 71 of file LBT.h
double LBT::P[7][dimParList] = {{0.0}} private
Definition at line 259 of file LBT.h.
View newest version in sPHENIX GitHub at line 259 of file LBT.h
double LBT::p0[4] = {0.0} private
Definition at line 245 of file LBT.h.
View newest version in sPHENIX GitHub at line 245 of file LBT.h
double LBT::P0[7][dimParList] = {{0.0}} private
Definition at line 261 of file LBT.h.
View newest version in sPHENIX GitHub at line 261 of file LBT.h
double LBT::p2[4] = {0.0} private
Definition at line 246 of file LBT.h.
View newest version in sPHENIX GitHub at line 246 of file LBT.h
double LBT::p3[4] = {0.0} private
Definition at line 247 of file LBT.h.
View newest version in sPHENIX GitHub at line 247 of file LBT.h
double LBT::p4[4] = {0.0} private
Definition at line 248 of file LBT.h.
View newest version in sPHENIX GitHub at line 248 of file LBT.h
double LBT::pb[4] = {0.0} private
Definition at line 254 of file LBT.h.
View newest version in sPHENIX GitHub at line 254 of file LBT.h
double LBT::pc0[4] = {0.0} private
Definition at line 241 of file LBT.h.
View newest version in sPHENIX GitHub at line 241 of file LBT.h
double LBT::pc00[4] = {0.0} private
Definition at line 250 of file LBT.h.
View newest version in sPHENIX GitHub at line 250 of file LBT.h
double LBT::pc01[4] = {0.0} private
Definition at line 253 of file LBT.h.
View newest version in sPHENIX GitHub at line 253 of file LBT.h
double LBT::pc2[4] = {0.0} private
Definition at line 242 of file LBT.h.
View newest version in sPHENIX GitHub at line 242 of file LBT.h
double LBT::pc3[4] = {0.0} private
Definition at line 243 of file LBT.h.
View newest version in sPHENIX GitHub at line 243 of file LBT.h
double LBT::pc30[4] = {0.0} private
Definition at line 251 of file LBT.h.
View newest version in sPHENIX GitHub at line 251 of file LBT.h
double LBT::pc4[4] = {0.0} private
Definition at line 244 of file LBT.h.
View newest version in sPHENIX GitHub at line 244 of file LBT.h
double LBT::PGm[4] = {0.0} private
Definition at line 272 of file LBT.h.
View newest version in sPHENIX GitHub at line 272 of file LBT.h
const double LBT::pi = 3.1415926 private
Definition at line 62 of file LBT.h.
View newest version in sPHENIX GitHub at line 62 of file LBT.h
double LBT::Pj0[4] = {0.0} private
Definition at line 256 of file LBT.h.
View newest version in sPHENIX GitHub at line 256 of file LBT.h
double LBT::PP[4][dimParList] = {{0.0}} private
Definition at line 284 of file LBT.h.
View newest version in sPHENIX GitHub at line 284 of file LBT.h
double LBT::PP0[4][dimParList] = {{0.0}} private
Definition at line 285 of file LBT.h.
View newest version in sPHENIX GitHub at line 285 of file LBT.h
double LBT::Prad[4][dimParList] = {{0.0}} private
Definition at line 263 of file LBT.h.
View newest version in sPHENIX GitHub at line 263 of file LBT.h
double LBT::preKT = 0.3 / 0.3 private
Definition at line 89 of file LBT.h.
View newest version in sPHENIX GitHub at line 89 of file LBT.h
double LBT::Q0 private
Definition at line 324 of file LBT.h.
View newest version in sPHENIX GitHub at line 324 of file LBT.h
double LBT::Q00 private
Definition at line 324 of file LBT.h.
View newest version in sPHENIX GitHub at line 324 of file LBT.h
double LBT::qhat private
Definition at line 210 of file LBT.h.
View newest version in sPHENIX GitHub at line 210 of file LBT.h
double LBT::qhat0 private
Definition at line 138 of file LBT.h.
View newest version in sPHENIX GitHub at line 138 of file LBT.h
double LBT::qhat00 private
Definition at line 139 of file LBT.h.
View newest version in sPHENIX GitHub at line 139 of file LBT.h
double LBT::qhat_over_T3 private
Definition at line 169 of file LBT.h.
View newest version in sPHENIX GitHub at line 169 of file LBT.h
double LBT::qhatG = {{0.0}} static private
Definition at line 163 of file LBT.h.
View newest version in sPHENIX GitHub at line 163 of file LBT.h
double LBT::qhatHQ = {{0.0}} static private
Definition at line 168 of file LBT.h.
View newest version in sPHENIX GitHub at line 168 of file LBT.h
double LBT::qhatLQ = {{0.0}} static private
Definition at line 162 of file LBT.h.
View newest version in sPHENIX GitHub at line 162 of file LBT.h
double LBT::radng[dimParList] = {0.0} private
Definition at line 229 of file LBT.h.
View newest version in sPHENIX GitHub at line 229 of file LBT.h
RegisterJetScapeModule< LBT > LBT::reg static private
Definition at line 407 of file LBT.h.
View newest version in sPHENIX GitHub at line 407 of file LBT.h
double LBT::Rg static private
Initial value:
= {
    {0.0}}
Definition at line 149 of file LBT.h.
View newest version in sPHENIX GitHub at line 149 of file LBT.h
double LBT::Rg1 = {{0.0}} static private
Definition at line 150 of file LBT.h.
View newest version in sPHENIX GitHub at line 150 of file LBT.h
double LBT::Rg2 = {{0.0}} static private
Definition at line 151 of file LBT.h.
View newest version in sPHENIX GitHub at line 151 of file LBT.h
double LBT::Rg3 = {{0.0}} static private
Definition at line 152 of file LBT.h.
View newest version in sPHENIX GitHub at line 152 of file LBT.h
double LBT::RHQ = {{0.0}} static private
Definition at line 165 of file LBT.h.
View newest version in sPHENIX GitHub at line 165 of file LBT.h
double LBT::RHQ11 = {{0.0}} static private
Definition at line 166 of file LBT.h.
View newest version in sPHENIX GitHub at line 166 of file LBT.h
double LBT::RHQ12 = {{0.0}} static private
Definition at line 167 of file LBT.h.
View newest version in sPHENIX GitHub at line 167 of file LBT.h
double LBT::Rq static private
Initial value:
= {
    {0.0}}
Definition at line 155 of file LBT.h.
View newest version in sPHENIX GitHub at line 155 of file LBT.h
double LBT::Rq3 = {{0.0}} static private
Definition at line 156 of file LBT.h.
View newest version in sPHENIX GitHub at line 156 of file LBT.h
double LBT::Rq4 = {{0.0}} static private
Definition at line 157 of file LBT.h.
View newest version in sPHENIX GitHub at line 157 of file LBT.h
double LBT::Rq5 = {{0.0}} static private
Definition at line 158 of file LBT.h.
View newest version in sPHENIX GitHub at line 158 of file LBT.h
double LBT::Rq6 = {{0.0}} static private
Definition at line 159 of file LBT.h.
View newest version in sPHENIX GitHub at line 159 of file LBT.h
double LBT::Rq7 = {{0.0}} static private
Definition at line 160 of file LBT.h.
View newest version in sPHENIX GitHub at line 160 of file LBT.h
double LBT::Rq8 = {{0.0}} static private
Definition at line 161 of file LBT.h.
View newest version in sPHENIX GitHub at line 161 of file LBT.h
int LBT::run_alphas = 1 private
Definition at line 100 of file LBT.h.
View newest version in sPHENIX GitHub at line 100 of file LBT.h
double LBT::runAlphas private
Definition at line 93 of file LBT.h.
View newest version in sPHENIX GitHub at line 93 of file LBT.h
double LBT::runKT private
Definition at line 92 of file LBT.h.
View newest version in sPHENIX GitHub at line 92 of file LBT.h
double LBT::runLog private
Definition at line 93 of file LBT.h.
View newest version in sPHENIX GitHub at line 93 of file LBT.h
double LBT::scaleAK = 2.0 private
Definition at line 90 of file LBT.h.
View newest version in sPHENIX GitHub at line 90 of file LBT.h
double LBT::scaleMu2 private
Definition at line 93 of file LBT.h.
View newest version in sPHENIX GitHub at line 93 of file LBT.h
const double LBT::sctr = 0.1973 private
Definition at line 66 of file LBT.h.
View newest version in sPHENIX GitHub at line 66 of file LBT.h
const int LBT::t_gn = t_gn_1 + t_gn_2 static private
Definition at line 176 of file LBT.h.
View newest version in sPHENIX GitHub at line 176 of file LBT.h
const int LBT::t_gn_1 = 100 static private
Definition at line 174 of file LBT.h.
View newest version in sPHENIX GitHub at line 174 of file LBT.h
const int LBT::t_gn_2 = 125 static private
Definition at line 175 of file LBT.h.
View newest version in sPHENIX GitHub at line 175 of file LBT.h
const double LBT::t_max = t_max_2 private
Definition at line 189 of file LBT.h.
View newest version in sPHENIX GitHub at line 189 of file LBT.h
const double LBT::t_max_1 = 20.0 private
Definition at line 187 of file LBT.h.
View newest version in sPHENIX GitHub at line 187 of file LBT.h
const double LBT::t_max_2 = 270.0 private
Definition at line 188 of file LBT.h.
View newest version in sPHENIX GitHub at line 188 of file LBT.h
double LBT::tau0 = 0.0 private
Definition at line 118 of file LBT.h.
View newest version in sPHENIX GitHub at line 118 of file LBT.h
double LBT::tauend = 4.0 private
Definition at line 120 of file LBT.h.
View newest version in sPHENIX GitHub at line 120 of file LBT.h
int LBT::tauswitch private
Initial value:
=
      0
Definition at line 116 of file LBT.h.
View newest version in sPHENIX GitHub at line 116 of file LBT.h
double LBT::temp0 = 0.25 private
Definition at line 79 of file LBT.h.
View newest version in sPHENIX GitHub at line 79 of file LBT.h
double LBT::temp00 private
Definition at line 82 of file LBT.h.
View newest version in sPHENIX GitHub at line 82 of file LBT.h
const int LBT::temp_gn = 100 static private
Definition at line 177 of file LBT.h.
View newest version in sPHENIX GitHub at line 177 of file LBT.h
const double LBT::temp_max = 0.65 private
Definition at line 190 of file LBT.h.
View newest version in sPHENIX GitHub at line 190 of file LBT.h
const double LBT::temp_min = 0.15 private
Definition at line 191 of file LBT.h.
View newest version in sPHENIX GitHub at line 191 of file LBT.h
double LBT::Tfrozen[dimParList] = {0.0} private
Definition at line 277 of file LBT.h.
View newest version in sPHENIX GitHub at line 277 of file LBT.h
double LBT::Tfrozen0[dimParList] = {0.0} private
Definition at line 278 of file LBT.h.
View newest version in sPHENIX GitHub at line 278 of file LBT.h
double LBT::tiform[dimParList] = {0.0} private
Definition at line 222 of file LBT.h.
View newest version in sPHENIX GitHub at line 222 of file LBT.h
double LBT::time0 private
Definition at line 122 of file LBT.h.
View newest version in sPHENIX GitHub at line 122 of file LBT.h
double LBT::timend private
Definition at line 125 of file LBT.h.
View newest version in sPHENIX GitHub at line 125 of file LBT.h
double LBT::Tint_lrf[dimParList] = {0.0} private
Definition at line 223 of file LBT.h.
View newest version in sPHENIX GitHub at line 223 of file LBT.h
double LBT::tirad[dimParList] = {0.0} private
Definition at line 220 of file LBT.h.
View newest version in sPHENIX GitHub at line 220 of file LBT.h
double LBT::tiscatter[dimParList] = {0.0} private
Definition at line 221 of file LBT.h.
View newest version in sPHENIX GitHub at line 221 of file LBT.h
double LBT::tjp[dimParList] = {0.0} private
Definition at line 273 of file LBT.h.
View newest version in sPHENIX GitHub at line 273 of file LBT.h
double LBT::tStart private
Definition at line 326 of file LBT.h.
View newest version in sPHENIX GitHub at line 326 of file LBT.h
double LBT::V[4][dimParList] = {{0.0}} private
Definition at line 258 of file LBT.h.
View newest version in sPHENIX GitHub at line 258 of file LBT.h
double LBT::V0[4][dimParList] = {{0.0}} private
Definition at line 260 of file LBT.h.
View newest version in sPHENIX GitHub at line 260 of file LBT.h
int LBT::vacORmed = 1 private
Definition at line 77 of file LBT.h.
View newest version in sPHENIX GitHub at line 77 of file LBT.h
double LBT::vc[4] = {0.0} private
Definition at line 240 of file LBT.h.
View newest version in sPHENIX GitHub at line 240 of file LBT.h
double LBT::vc0[4] = {0.0} private
Definition at line 237 of file LBT.h.
View newest version in sPHENIX GitHub at line 237 of file LBT.h
double LBT::vcfrozen[4][dimParList] = {{0.0}} private
Definition at line 279 of file LBT.h.
View newest version in sPHENIX GitHub at line 279 of file LBT.h
double LBT::vcfrozen0[4][dimParList] = {{0.0}} private
Definition at line 280 of file LBT.h.
View newest version in sPHENIX GitHub at line 280 of file LBT.h
double LBT::vf[4] = {0.0} private
Definition at line 233 of file LBT.h.
View newest version in sPHENIX GitHub at line 233 of file LBT.h
double LBT::vfcar[4] = {0.0} private
Definition at line 234 of file LBT.h.
View newest version in sPHENIX GitHub at line 234 of file LBT.h
double LBT::Vfrozen[4][dimParList] = {{0.0}} private
Definition at line 274 of file LBT.h.
View newest version in sPHENIX GitHub at line 274 of file LBT.h
double LBT::Vfrozen0[4][dimParList] = {{0.0}} private
Definition at line 275 of file LBT.h.
View newest version in sPHENIX GitHub at line 275 of file LBT.h
double LBT::vp[4] = {0.0} private
Definition at line 236 of file LBT.h.
View newest version in sPHENIX GitHub at line 236 of file LBT.h
double LBT::Vtemp[4] = {0.0} private
Definition at line 214 of file LBT.h.
View newest version in sPHENIX GitHub at line 214 of file LBT.h
double LBT::VV[4][dimParList] = {{0.0}} private
Definition at line 282 of file LBT.h.
View newest version in sPHENIX GitHub at line 282 of file LBT.h
double LBT::VV0[4][dimParList] = {{0.0}} private
Definition at line 283 of file LBT.h.
View newest version in sPHENIX GitHub at line 283 of file LBT.h
double LBT::wkt2m private
Definition at line 231 of file LBT.h.
View newest version in sPHENIX GitHub at line 231 of file LBT.h
double LBT::WT[dimParList] = {0} private
Definition at line 265 of file LBT.h.
View newest version in sPHENIX GitHub at line 265 of file LBT.h
double LBT::WT0[dimParList] = {0} private
Definition at line 266 of file LBT.h.
View newest version in sPHENIX GitHub at line 266 of file LBT.h
double LBT::xwm[3] = {0.0} private
Definition at line 230 of file LBT.h.
View newest version in sPHENIX GitHub at line 230 of file LBT.h
std::uniform_real_distribution<double> LBT::ZeroOneDistribution private
Definition at line 141 of file LBT.h.
View newest version in sPHENIX GitHub at line 141 of file LBT.h
The documentation for this class was generated from the following files:
JETSCAPE/blob/main/src/jet/LBT.h
JETSCAPE/blob/main/src/jet/LBT.cc