Analysis Software: CylinderGeomIntt Class Reference
CylinderGeomIntt Class Reference
#include <coresoftware/blob/master/offline/packages/intt/CylinderGeomIntt.h>
Public Member Functions
CylinderGeomIntt ()=default
CylinderGeomIntt (const int layer, const double strip_x, const double strip_y, const double strip_z0, const double strip_z1, const int nstrips_z_sensor0, const int nstrips_z_sensor1, const int nstrips_phi_cell, const int nladders_layer, const double ladder_z0, const double ladder_z1, const double sensor_radius, const double strip_x_offset, const double offsetphi, const double offsetrot)
void identify (std::ostream &os=std::cout) const override
double get_thickness () const override
double get_strip_y_spacing () const override
double get_strip_z_spacing () const override
double get_strip_tilt () const override
void set_layer (const int i) override
int get_layer () const override
double get_radius () const override
void find_segment_center (const Surface &surface, ActsGeometry *tGeometry, double location[])
void find_strip_center (const Surface &surface, ActsGeometry *tGeometry, const int segment_z_bin, const int segment_phi_bin, const int strip_column, const int strip_index, double location[])
void find_strip_index_values (const int segment_z_bin, const double ypos, const double zpos, int &strip_y_index, int &strip_z_index) override
bool load_geometry ()
void find_strip_center_localcoords (const int segment_z_bin, const int strip_y_index, const int strip_z_index, double location[])
void find_indices_from_segment_center (int &segment_z_bin, int &segment_phi_bin, double location[])
TVector3 get_world_from_local_coords (const Surface &surface, ActsGeometry *tGeometry, const TVector2 &local)
TVector3 get_world_from_local_coords (const Surface &surface, ActsGeometry *tGeometry, const TVector3 &local)
TVector3 get_local_from_world_coords (const Surface &surface, ActsGeometry *tGeometry, TVector3 world)
void find_indices_from_world_location (int &segment_z_bin, int &segment_phi_bin, double location[])
void find_strip_center (int, int, int, int, double *) override
void find_segment_center (const int, const int, double *) override
double get_strip_phi_tilt () const
Public Member Functions inherited from PHG4CylinderGeom
~PHG4CylinderGeom () override
void identify (std::ostream &os=std::cout) const override
virtual double get_zmin () const
virtual double get_zmax () const
virtual int get_nscint () const
virtual double get_tiltangle () const
virtual double get_phi_slat_zero () const
virtual void set_radius (const double)
virtual void set_thickness (const double)
virtual void set_zmin (const double)
virtual void set_zmax (const double)
virtual void set_nscint (const int)
virtual void set_tiltangle (const double)
virtual void set_phi_slat_zero (const double)
virtual void find_segment_center (const int, const int, double[])
virtual void find_strip_center (const int, const int, const int, const int, double[])
virtual void find_strip_center_local_coords (const int, const int, const int, double[])
virtual int get_N_strip_columns () const
virtual int get_N_strips_per_column () const
virtual int get_N_sensors_in_layer () const
virtual double get_pixel_z () const
virtual double get_pixel_x () const
virtual double get_pixel_thickness () const
virtual void ImportParameters (const PHParameters &)
load parameters from PHParameters, which interface to Database/XML/ROOT files
Public Member Functions inherited from PHObject
PHObject ()
ctor
~PHObject () override
dtor
virtual PHObject * CloneMe () const
Virtual copy constructor.
virtual PHObject * clone () const final
PHObject * Clone (const char *newname="") const final
void Copy (TObject &object) const final
virtual void Reset ()
Clear Event.
virtual int isValid () const
isValid returns non zero if object contains vailid data
virtual int Integrate () const
virtual int Integrate (PHObject *)
virtual void CopyFrom (const PHObject *obj)
Protected Attributes
int m_Layer {-1}
int m_NStripsPhiCell {-1}
int m_NStripsZSensor [2] {-1,-1}
double m_StripX {std::numeric_limits<double>::quiet_NaN()}
double m_StripY {std::numeric_limits<double>::quiet_NaN()}
double m_SensorRadius {std::numeric_limits<double>::quiet_NaN()}
double m_StripXOffset {std::numeric_limits<double>::quiet_NaN()}
double m_OffsetPhi {std::numeric_limits<double>::quiet_NaN()}
double m_OffsetRot {std::numeric_limits<double>::quiet_NaN()}
double m_dPhi {std::numeric_limits<double>::quiet_NaN()}
double m_StripZ [2] {std::numeric_limits<double>::quiet_NaN(), std::numeric_limits<double>::quiet_NaN()}
double m_LadderZ [2] {std::numeric_limits<double>::quiet_NaN(), std::numeric_limits<double>::quiet_NaN()}
Additional Inherited Members
Protected Member Functions inherited from PHG4CylinderGeom
PHG4CylinderGeom ()
Detailed Description
Definition at line 14 of file CylinderGeomIntt.h.
View newest version in sPHENIX GitHub at line 14 of file CylinderGeomIntt.h
Constructor & Destructor Documentation
CylinderGeomIntt::CylinderGeomIntt () default
CylinderGeomIntt::CylinderGeomIntt (const int layer, const double strip_x, const double strip_y, const double strip_z0, const double strip_z1, const int nstrips_z_sensor0, const int nstrips_z_sensor1, const int nstrips_phi_cell, const int nladders_layer, const double ladder_z0, const double ladder_z1, const double sensor_radius, const double strip_x_offset, const double offsetphi, const double offsetrot) inline
Definition at line 18 of file CylinderGeomIntt.h.
View newest version in sPHENIX GitHub at line 18 of file CylinderGeomIntt.h
References m_dPhi, m_LadderZ, m_NStripsZSensor, and m_StripZ.
Member Function Documentation
void CylinderGeomIntt::find_indices_from_segment_center (int & segment_z_bin, int & segment_phi_bin, double location[])
Definition at line 114 of file CylinderGeomIntt.cc.
View newest version in sPHENIX GitHub at line 114 of file CylinderGeomIntt.cc
References m_dPhi, m_LadderZ, m_OffsetPhi, and ActsTests::PropagationDatasets::phi.
Referenced by MakeActsGeometry::getInttHitSetKeyFromCoords().
void CylinderGeomIntt::find_indices_from_world_location (int & segment_z_bin, int & segment_phi_bin, double location[])
Definition at line 80 of file CylinderGeomIntt.cc.
View newest version in sPHENIX GitHub at line 80 of file CylinderGeomIntt.cc
References m_dPhi, m_LadderZ, m_OffsetPhi, ActsTests::PropagationDatasets::phi, and round().
Referenced by PHTruthClustering::G4ClusterSize(), and SvtxTruthEval::G4ClusterSize().
void CylinderGeomIntt::find_segment_center (const Surface & surface, ActsGeometry * tGeometry, double location[])
Definition at line 69 of file CylinderGeomIntt.cc.
View newest version in sPHENIX GitHub at line 69 of file CylinderGeomIntt.cc
References get_world_from_local_coords().
Referenced by find_strip_center(), and SVReco::MakeGenFitTrack().
void CylinderGeomIntt::find_segment_center (const int , const int , double *) inline override
Definition at line 112 of file CylinderGeomIntt.h.
View newest version in sPHENIX GitHub at line 112 of file CylinderGeomIntt.h
void CylinderGeomIntt::find_strip_center (const Surface & surface, ActsGeometry * tGeometry, const int segment_z_bin, const int segment_phi_bin, const int strip_column, const int strip_index, double location[])
Definition at line 153 of file CylinderGeomIntt.cc.
View newest version in sPHENIX GitHub at line 153 of file CylinderGeomIntt.cc
References find_segment_center(), m_dPhi, m_NStripsPhiCell, m_NStripsZSensor, m_OffsetPhi, m_OffsetRot, m_StripXOffset, m_StripY, m_StripZ, and ActsTests::PropagationDatasets::phi.
void CylinderGeomIntt::find_strip_center (int , int , int , int , double *) inline override
Definition at line 108 of file CylinderGeomIntt.h.
View newest version in sPHENIX GitHub at line 108 of file CylinderGeomIntt.h
void CylinderGeomIntt::find_strip_center_localcoords (const int segment_z_bin, const int strip_y_index, const int strip_z_index, double location[])
Definition at line 222 of file CylinderGeomIntt.cc.
View newest version in sPHENIX GitHub at line 222 of file CylinderGeomIntt.cc
References double(), m_NStripsPhiCell, m_NStripsZSensor, m_StripY, and m_StripZ.
Referenced by PHG4InttHitReco::cluster_truthhits(), InttClusterizer::ClusterLadderCells(), InttClusterizer::ClusterLadderCellsRaw(), TrackResiduals::fillHitTree(), and PHG4InttHitReco::process_event().
void CylinderGeomIntt::find_strip_index_values (const int segment_z_bin, const double ypos, const double zpos, int & strip_y_index, int & strip_z_index) override virtual
Reimplemented from PHG4CylinderGeom.
Definition at line 184 of file CylinderGeomIntt.cc.
View newest version in sPHENIX GitHub at line 184 of file CylinderGeomIntt.cc
References double(), m_NStripsPhiCell, m_NStripsZSensor, m_StripY, and m_StripZ.
Referenced by PHTruthClustering::G4ClusterSize(), SvtxTruthEval::G4ClusterSize(), and PHG4InttHitReco::process_event().
int CylinderGeomIntt::get_layer () const inline override virtual
Reimplemented from PHG4CylinderGeom.
Definition at line 85 of file CylinderGeomIntt.h.
View newest version in sPHENIX GitHub at line 85 of file CylinderGeomIntt.h
References m_Layer.
Referenced by identify().
TVector3 CylinderGeomIntt::get_local_from_world_coords (const Surface & surface, ActsGeometry * tGeometry, TVector3 world)
The acts transform is offset by one element
Definition at line 53 of file CylinderGeomIntt.cc.
View newest version in sPHENIX GitHub at line 53 of file CylinderGeomIntt.cc
References Acts::UnitConstants::cm, ActsGeometry::geometry(), and ActsTrackingGeometry::getGeoContext().
Referenced by PHTruthClustering::G4ClusterSize(), and SvtxTruthEval::G4ClusterSize().
double CylinderGeomIntt::get_radius () const inline override virtual
Reimplemented from PHG4CylinderGeom.
Definition at line 90 of file CylinderGeomIntt.h.
View newest version in sPHENIX GitHub at line 90 of file CylinderGeomIntt.h
References m_SensorRadius.
Referenced by identify().
double CylinderGeomIntt::get_strip_phi_tilt () const inline
Definition at line 117 of file CylinderGeomIntt.h.
View newest version in sPHENIX GitHub at line 117 of file CylinderGeomIntt.h
References m_OffsetRot.
Referenced by SVReco::MakeGenFitTrack().
double CylinderGeomIntt::get_strip_tilt () const inline override virtual
Reimplemented from PHG4CylinderGeom.
Definition at line 75 of file CylinderGeomIntt.h.
View newest version in sPHENIX GitHub at line 75 of file CylinderGeomIntt.h
double CylinderGeomIntt::get_strip_y_spacing () const inline override virtual
Reimplemented from PHG4CylinderGeom.
Definition at line 65 of file CylinderGeomIntt.h.
View newest version in sPHENIX GitHub at line 65 of file CylinderGeomIntt.h
References m_StripY.
Referenced by InttClusterizer::ClusterLadderCells(), InttClusterizer::ClusterLadderCellsRaw(), PHTruthClustering::G4ClusterSize(), SvtxTruthEval::G4ClusterSize(), TrkrClusterIsMatcher::init(), G4Eval::TrkrClusterComparer::init(), and PHG4InttHitReco::process_event().
double CylinderGeomIntt::get_strip_z_spacing () const inline override virtual
Reimplemented from PHG4CylinderGeom.
Definition at line 70 of file CylinderGeomIntt.h.
View newest version in sPHENIX GitHub at line 70 of file CylinderGeomIntt.h
References m_StripZ.
Referenced by InttClusterizer::ClusterLadderCells(), InttClusterizer::ClusterLadderCellsRaw(), PHTruthClustering::G4ClusterSize(), SvtxTruthEval::G4ClusterSize(), and PHG4InttHitReco::process_event().
double CylinderGeomIntt::get_thickness () const inline override virtual
Reimplemented from PHG4CylinderGeom.
Definition at line 60 of file CylinderGeomIntt.h.
View newest version in sPHENIX GitHub at line 60 of file CylinderGeomIntt.h
References m_StripX.
TVector3 CylinderGeomIntt::get_world_from_local_coords (const Surface & surface, ActsGeometry * tGeometry, const TVector2 & local)
Acts requires a dummy vector to be passed in the arg list
Definition at line 32 of file CylinderGeomIntt.cc.
View newest version in sPHENIX GitHub at line 32 of file CylinderGeomIntt.cc
References Acts::UnitConstants::cm, ActsGeometry::geometry(), and ActsTrackingGeometry::getGeoContext().
Referenced by find_segment_center().
TVector3 CylinderGeomIntt::get_world_from_local_coords (const Surface & surface, ActsGeometry * tGeometry, const TVector3 & local)
Definition at line 23 of file CylinderGeomIntt.cc.
View newest version in sPHENIX GitHub at line 23 of file CylinderGeomIntt.cc
References Acts::UnitConstants::cm, ActsGeometry::geometry(), ActsTrackingGeometry::getGeoContext(), and loc.
void CylinderGeomIntt::identify (std::ostream & os = std::cout) const override virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from PHObject.
Definition at line 16 of file CylinderGeomIntt.cc.
View newest version in sPHENIX GitHub at line 16 of file CylinderGeomIntt.cc
References get_layer(), and get_radius().
bool CylinderGeomIntt::load_geometry () inline
Definition at line 100 of file CylinderGeomIntt.h.
View newest version in sPHENIX GitHub at line 100 of file CylinderGeomIntt.h
void CylinderGeomIntt::set_layer (const int i) inline override virtual
Reimplemented from PHG4CylinderGeom.
Definition at line 80 of file CylinderGeomIntt.h.
View newest version in sPHENIX GitHub at line 80 of file CylinderGeomIntt.h
References i, and m_Layer.
Member Data Documentation
double CylinderGeomIntt::m_dPhi {std::numeric_limits<double>::quiet_NaN()} protected
Definition at line 132 of file CylinderGeomIntt.h.
View newest version in sPHENIX GitHub at line 132 of file CylinderGeomIntt.h
Referenced by CylinderGeomIntt(), find_indices_from_segment_center(), find_indices_from_world_location(), and find_strip_center().
double CylinderGeomIntt::m_LadderZ[2] {std::numeric_limits<double>::quiet_NaN(), std::numeric_limits<double>::quiet_NaN()} protected
Definition at line 135 of file CylinderGeomIntt.h.
View newest version in sPHENIX GitHub at line 135 of file CylinderGeomIntt.h
Referenced by CylinderGeomIntt(), find_indices_from_segment_center(), and find_indices_from_world_location().
int CylinderGeomIntt::m_Layer {-1} protected
Definition at line 123 of file CylinderGeomIntt.h.
View newest version in sPHENIX GitHub at line 123 of file CylinderGeomIntt.h
Referenced by get_layer(), and set_layer().
int CylinderGeomIntt::m_NStripsPhiCell {-1} protected
Definition at line 124 of file CylinderGeomIntt.h.
View newest version in sPHENIX GitHub at line 124 of file CylinderGeomIntt.h
Referenced by find_strip_center(), find_strip_center_localcoords(), and find_strip_index_values().
int CylinderGeomIntt::m_NStripsZSensor[2] {-1,-1} protected
Definition at line 125 of file CylinderGeomIntt.h.
View newest version in sPHENIX GitHub at line 125 of file CylinderGeomIntt.h
Referenced by CylinderGeomIntt(), find_strip_center(), find_strip_center_localcoords(), and find_strip_index_values().
double CylinderGeomIntt::m_OffsetPhi {std::numeric_limits<double>::quiet_NaN()} protected
Definition at line 130 of file CylinderGeomIntt.h.
View newest version in sPHENIX GitHub at line 130 of file CylinderGeomIntt.h
Referenced by find_indices_from_segment_center(), find_indices_from_world_location(), and find_strip_center().
double CylinderGeomIntt::m_OffsetRot {std::numeric_limits<double>::quiet_NaN()} protected
Definition at line 131 of file CylinderGeomIntt.h.
View newest version in sPHENIX GitHub at line 131 of file CylinderGeomIntt.h
Referenced by find_strip_center(), and get_strip_phi_tilt().
double CylinderGeomIntt::m_SensorRadius {std::numeric_limits<double>::quiet_NaN()} protected
Definition at line 128 of file CylinderGeomIntt.h.
View newest version in sPHENIX GitHub at line 128 of file CylinderGeomIntt.h
Referenced by get_radius().
double CylinderGeomIntt::m_StripX {std::numeric_limits<double>::quiet_NaN()} protected
Definition at line 126 of file CylinderGeomIntt.h.
View newest version in sPHENIX GitHub at line 126 of file CylinderGeomIntt.h
Referenced by get_thickness().
double CylinderGeomIntt::m_StripXOffset {std::numeric_limits<double>::quiet_NaN()} protected
Definition at line 129 of file CylinderGeomIntt.h.
View newest version in sPHENIX GitHub at line 129 of file CylinderGeomIntt.h
Referenced by find_strip_center().
double CylinderGeomIntt::m_StripY {std::numeric_limits<double>::quiet_NaN()} protected
Definition at line 127 of file CylinderGeomIntt.h.
View newest version in sPHENIX GitHub at line 127 of file CylinderGeomIntt.h
Referenced by find_strip_center(), find_strip_center_localcoords(), find_strip_index_values(), and get_strip_y_spacing().
double CylinderGeomIntt::m_StripZ[2] {std::numeric_limits<double>::quiet_NaN(), std::numeric_limits<double>::quiet_NaN()} protected
Definition at line 134 of file CylinderGeomIntt.h.
View newest version in sPHENIX GitHub at line 134 of file CylinderGeomIntt.h
Referenced by CylinderGeomIntt(), find_strip_center(), find_strip_center_localcoords(), find_strip_index_values(), and get_strip_z_spacing().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/intt/CylinderGeomIntt.h
coresoftware/blob/master/offline/packages/intt/CylinderGeomIntt.cc