Analysis Software: smearing-config Namespace Reference
smearing-config Namespace Reference
Functions
def add_switch
def get_args_blocks
def arg_parser
def get_args
def get_n_params
def get_param_blocks
def block_to_json
def get_json_data
def main
Function Documentation
def smearing-config.add_switch (i, argv, current)
Definition at line 34 of file smearing-config.py.
View newest version in sPHENIX GitHub at line 34 of file smearing-config.py
Referenced by get_args_blocks().
def smearing-config.arg_parser ()
Definition at line 74 of file smearing-config.py.
View newest version in sPHENIX GitHub at line 74 of file smearing-config.py
Referenced by get_args().
def smearing-config.block_to_json (args)
Definition at line 117 of file smearing-config.py.
View newest version in sPHENIX GitHub at line 117 of file smearing-config.py
References get_param_blocks(), and Acts.zip().
Referenced by get_json_data().
def smearing-config.get_args ()
Definition at line 97 of file smearing-config.py.
View newest version in sPHENIX GitHub at line 97 of file smearing-config.py
References arg_parser(), and get_args_blocks().
Referenced by get_json_data().
def smearing-config.get_args_blocks ()
Definition at line 55 of file smearing-config.py.
View newest version in sPHENIX GitHub at line 55 of file smearing-config.py
References add_switch().
Referenced by get_args().
def smearing-config.get_json_data ()
Definition at line 163 of file smearing-config.py.
View newest version in sPHENIX GitHub at line 163 of file smearing-config.py
References block_to_json(), and get_args().
Referenced by main().
def smearing-config.get_n_params (type_id)
Definition at line 101 of file smearing-config.py.
View newest version in sPHENIX GitHub at line 101 of file smearing-config.py
Referenced by get_param_blocks().
def smearing-config.get_param_blocks (types_ids, params)
Definition at line 107 of file smearing-config.py.
View newest version in sPHENIX GitHub at line 107 of file smearing-config.py
References get_n_params().
Referenced by block_to_json().
def smearing-config.main (void)
Definition at line 173 of file smearing-config.py.
View newest version in sPHENIX GitHub at line 173 of file smearing-config.py
References get_json_data(), and print().