Analysis Software: macros/blob/master/common/G4_Tracking_Cosmics.C File Reference
G4_Tracking_Cosmics.C File Reference
#include <G4_ActsGeom.C>
#include <G4_TPC.C>
#include <G4_Mvtx.C>
#include <G4_Intt.C>
#include <G4_Magnet.C>
#include <G4_Micromegas.C>
#include <g4eval/SvtxEvaluator.h>
#include <g4eval/SvtxTruthRecoTableEval.h>
#include <g4eval/TrackSeedTrackMapConverter.h>
#include <trackreco/MakeActsGeometry.h>
#include <trackreco/PHActsSiliconSeeding.h>
#include <trackreco/PHCASeeding.h>
#include <trackreco/PHMicromegasTpcTrackMatching.h>
#include <trackreco/PHSiliconHelicalPropagator.h>
#include <trackreco/PHSimpleKFProp.h>
#include <trackreco/PHSimpleVertexFinder.h>
#include <trackreco/PHTrackSeeding.h>
#include <trackreco/PHTruthSiliconAssociation.h>
#include <trackreco/PHTruthTrackSeeding.h>
#include <tpc/TpcLoadDistortionCorrection.h>
#include <trackermillepedealignment/MakeMilleFiles.h>
#include <trackermillepedealignment/HelicalFitter.h>
#include <qa_modules/QAG4SimulationTracking.h>
#include <qa_modules/QAG4SimulationUpsilon.h>
#include <qa_modules/QAG4SimulationVertex.h>
#include <fun4all/Fun4AllServer.h>
Namespaces
namespace Enable
namespace G4TRACKING
Macros
#define MACRO_G4TRACKING_C
Functions
void TrackingInit ()
void convert_seeds ()
void Tracking_Reco_TrackSeed ()
void vertexing ()
void alignment (std::string datafilename="mille_output_data_file", std::string steeringfilename="mille_steer")
void Tracking_Reco ()
void build_truthreco_tables ()
void Tracking_Eval (const std::string &outputfile)
void Tracking_QA ()
Variables
bool Enable::TRACKING_TRACK = false
bool Enable::TRACKING_EVAL = false
int Enable::TRACKING_VERBOSITY = 0
bool Enable::TRACKING_QA = false
bool G4TRACKING::use_alignment = false
bool G4TRACKING::use_full_truth_track_seeding = false
bool G4TRACKING::use_truth_tpc_seeding = false
bool G4TRACKING::g4eval_use_initial_vertex = true
bool G4TRACKING::SC_CALIBMODE = false
Macro Definition Documentation
#define MACRO_G4TRACKING_C
Definition at line 2 of file G4_Tracking_Cosmics.C.
View newest version in sPHENIX GitHub at line 2 of file G4_Tracking_Cosmics.C
Function Documentation
void alignment (std::string datafilename = "mille_output_data_file", std::string steeringfilename = "mille_steer")
Definition at line 207 of file G4_Tracking_Cosmics.C.
View newest version in sPHENIX GitHub at line 207 of file G4_Tracking_Cosmics.C
References Fun4AllServer::instance(), Fun4AllServer::registerSubsystem(), Enable::TRACKING_VERBOSITY, verbosity, Enable::VERBOSITY, and Fun4AllBase::Verbosity().
void build_truthreco_tables ()
Definition at line 234 of file G4_Tracking_Cosmics.C.
View newest version in sPHENIX GitHub at line 234 of file G4_Tracking_Cosmics.C
References Fun4AllServer::instance(), Fun4AllServer::registerSubsystem(), Enable::TRACKING_VERBOSITY, verbosity, Enable::VERBOSITY, and Fun4AllBase::Verbosity().
void convert_seeds ()
Definition at line 76 of file G4_Tracking_Cosmics.C.
View newest version in sPHENIX GitHub at line 76 of file G4_Tracking_Cosmics.C
References Fun4AllServer::instance(), Fun4AllServer::registerSubsystem(), TrackSeedTrackMapConverter::setTrackSeedName(), Enable::TRACKING_VERBOSITY, verbosity, Enable::VERBOSITY, and Fun4AllBase::Verbosity().
void Tracking_Eval (const std::string & outputfile)
Definition at line 249 of file G4_Tracking_Cosmics.C.
View newest version in sPHENIX GitHub at line 249 of file G4_Tracking_Cosmics.C
References build_truthreco_tables(), SvtxEvaluator::do_cluster_eval(), SvtxEvaluator::do_eval_light(), SvtxEvaluator::do_g4hit_eval(), SvtxEvaluator::do_gpoint_eval(), SvtxEvaluator::do_hit_eval(), SvtxEvaluator::do_vtx_eval_light(), G4TRACKING::g4eval_use_initial_vertex, Fun4AllServer::instance(), G4TPC::n_gas_layer, G4INTT::n_intt_layer, G4MVTX::n_maps_layer, G4MICROMEGAS::n_micromegas_layer, TRACKING::pp_mode, Fun4AllServer::registerSubsystem(), SvtxEvaluator::scan_for_embedded(), SvtxEvaluator::scan_for_primaries(), SvtxEvaluator::set_use_initial_vertex(), Enable::TRACKING_VERBOSITY, verbosity, Enable::VERBOSITY, and Fun4AllBase::Verbosity().
void Tracking_QA ()
Definition at line 289 of file G4_Tracking_Cosmics.C.
View newest version in sPHENIX GitHub at line 289 of file G4_Tracking_Cosmics.C
References QAG4SimulationUpsilon::addEmbeddingID(), build_truthreco_tables(), Fun4AllServer::instance(), Enable::QA_VERBOSITY, Fun4AllServer::registerSubsystem(), QAG4SimulationVertex::setVertexMapName(), Enable::TRACKING_VERBOSITY, Input::UPSILON, Input::UPSILON_EmbedIds, verbosity, and Fun4AllBase::Verbosity().
void Tracking_Reco ()
Definition at line 227 of file G4_Tracking_Cosmics.C.
View newest version in sPHENIX GitHub at line 227 of file G4_Tracking_Cosmics.C
References alignment(), Tracking_Reco_TrackSeed(), G4TRACKING::use_alignment, and vertexing().
void Tracking_Reco_TrackSeed ()
Definition at line 89 of file G4_Tracking_Cosmics.C.
View newest version in sPHENIX GitHub at line 89 of file G4_Tracking_Cosmics.C
References convert_seeds(), Fun4AllServer::instance(), G4MAGNET::magfield, G4MAGNET::magfield_rescale, Enable::MICROMEGAS, G4TPC::n_gas_layer, G4INTT::n_intt_layer, G4MVTX::n_maps_layer, G4TRACKING::SC_CALIBMODE, physmon_track_finding_ttbar::seeder, Enable::TRACKING_VERBOSITY, G4TRACKING::use_full_truth_track_seeding, G4TRACKING::use_truth_tpc_seeding, verbosity, Enable::VERBOSITY, and Fun4AllBase::Verbosity().
void TrackingInit ()
Definition at line 62 of file G4_Tracking_Cosmics.C.
View newest version in sPHENIX GitHub at line 62 of file G4_Tracking_Cosmics.C
References ACTSGEOM::ActsGeomInit(), G4TPC::correction_filename, G4TPC::ENABLE_CORRECTIONS, Fun4AllServer::instance(), and TpcLoadDistortionCorrection::set_distortion_filename().
void vertexing ()
Definition at line 197 of file G4_Tracking_Cosmics.C.
View newest version in sPHENIX GitHub at line 197 of file G4_Tracking_Cosmics.C
References Fun4AllServer::instance(), Fun4AllServer::registerSubsystem(), Enable::TRACKING_VERBOSITY, verbosity, Enable::VERBOSITY, and Fun4AllBase::Verbosity().