Analysis Software: Jetscape::JetEnergyLossManager Class Reference
Jetscape::JetEnergyLossManager Class Reference
#include <JETSCAPE/blob/main/src/framework/JetEnergyLossManager.h>
Public Member Functions
JetEnergyLossManager ()
virtual ~JetEnergyLossManager ()
virtual void Init ()
virtual void Exec ()
virtual void Clear ()
virtual void WriteTask (weak_ptr< JetScapeWriter > w)
int GetNumSignals ()
void CreateSignalSlots ()
void SetGetHardPartonListConnected (bool m_GetHardPartonListConnected)
const bool GetGetHardPartonListConnected ()
Public Member Functions inherited from Jetscape::JetScapeTask
JetScapeTask ()
virtual ~JetScapeTask ()
virtual void Finish ()
virtual void ExecuteTasks ()
virtual void ExecuteTask ()
virtual void InitTask ()
virtual void InitTasks ()
virtual void ClearTasks ()
virtual void ClearTask ()
virtual void FinishTask ()
virtual void FinishTasks ()
virtual void WriteTasks (weak_ptr< JetScapeWriter > w)
virtual void CollectHeader (weak_ptr< JetScapeWriter > w)
virtual void CollectHeaders (weak_ptr< JetScapeWriter > w)
virtual void Add (shared_ptr< JetScapeTask > m_tasks)
virtual const int GetMyTaskNumber () const
const vector< shared_ptr
< JetScapeTask > > GetTaskList () const
shared_ptr< JetScapeTask > GetTaskAt (int i)
void EraseTaskLast ()
void EraseTaskAt (int i)
void ResizeTaskList (int i)
void ClearTaskList ()
int GetNumberOfTasks ()
const bool GetActive () const
void SetActive (bool m_active_exec)
void SetId (string m_id)
const string GetId () const
const shared_ptr
< JetScapeModuleMutex > GetMutex () const
void SetMutex (shared_ptr< JetScapeModuleMutex > m_mutex)
Public Attributes
sigslot::signal1< vector
< shared_ptr< Parton > > & > GetHardPartonList
Private Attributes
bool GetHardPartonListConnected
vector< shared_ptr< Parton > > hp
Detailed Description
Definition at line 28 of file JetEnergyLossManager.h.
View newest version in sPHENIX GitHub at line 28 of file JetEnergyLossManager.h
Constructor & Destructor Documentation
Jetscape::JetEnergyLossManager::JetEnergyLossManager ()
Default constructor to create a jet energy loss manager. Sets task ID as "JLossManager". Flag GetHardPartonListConnected is set to false.
Definition at line 30 of file JetEnergyLossManager.cc.
View newest version in sPHENIX GitHub at line 30 of file JetEnergyLossManager.cc
References SetId(), and VERBOSE.
Jetscape::JetEnergyLossManager::~JetEnergyLossManager () virtual
Destructor for the jet energy loss manager.
Definition at line 36 of file JetEnergyLossManager.cc.
View newest version in sPHENIX GitHub at line 36 of file JetEnergyLossManager.cc
References Clear(), and JSDEBUG.
Member Function Documentation
void Jetscape::JetEnergyLossManager::Clear (void) virtual
It erases the tasks attached with the energy loss manager. It can be overridden by other tasks.
Reimplemented from Jetscape::JetScapeTask.
Definition at line 45 of file JetEnergyLossManager.cc.
View newest version in sPHENIX GitHub at line 45 of file JetEnergyLossManager.cc
References i, JSDEBUG, n, and VERBOSE.
void Jetscape::JetEnergyLossManager::CreateSignalSlots ()
Uses philosophy of signal slots. Checks whether the attached task is connected via signal slots to the functions UpdateEnergyDeposit(), GetEnergyDensity(), GetHydroCell() (defined in FluidDynamics class), and DoEnergyLoss() (defined in JetEnergyLoss class). If not, then, it sends a signal to these functions.
See Also
JetScapeSignalManager to understand the implementation of signal slots philosophy.
Definition at line 203 of file JetEnergyLossManager.cc.
View newest version in sPHENIX GitHub at line 203 of file JetEnergyLossManager.cc
References boost::dynamic_pointer_cast(), it, VERBOSE, and Jetscape::weak_ptr_is_uninitialized().
void Jetscape::JetEnergyLossManager::Exec () virtual
It reads the Hard Patrons list and calls CreateSignalSlots() function. Then, it executes the energy loss tasks attached with the jet energy loss manager. This function also includes the parallel computing feature. It can be overridden by other tasks.
Reimplemented from Jetscape::JetScapeTask.
Definition at line 91 of file JetEnergyLossManager.cc.
View newest version in sPHENIX GitHub at line 91 of file JetEnergyLossManager.cc
References Jetscape::JetEnergyLoss::add_a_liquefier(), boost::dynamic_pointer_cast(), i, it, JSDEBUG, JSWARN, n, VERBOSE, and Jetscape::weak_ptr_is_uninitialized().
const bool Jetscape::JetEnergyLossManager::GetGetHardPartonListConnected () inline
Returns
GetHardPartonListConnected A boolean flag. Its status indicates whether JetEnergyLossManager had sent a signal to the function GetHardPartonList() of the class HardProcess.
Definition at line 80 of file JetEnergyLossManager.h.
View newest version in sPHENIX GitHub at line 80 of file JetEnergyLossManager.h
References GetHardPartonListConnected.
int Jetscape::JetEnergyLossManager::GetNumSignals ()
void Jetscape::JetEnergyLossManager::Init () virtual
It initializes the tasks attached to the jet energy loss manager. It also sends a signal to connect the JetEnergyLoss object to the GetHardPartonList() function of the HardProcess class. It can be overridden by other tasks.
See Also
JetScapeSignalManager to understand the implementation of signal slots philosophy.
Reimplemented from Jetscape::JetScapeTask.
Definition at line 61 of file JetEnergyLossManager.cc.
View newest version in sPHENIX GitHub at line 61 of file JetEnergyLossManager.cc
References it, JSINFO, and JSWARN.
void Jetscape::JetEnergyLossManager::SetGetHardPartonListConnected (bool m_GetHardPartonListConnected) inline
Use the flag m_GetHardPartonListConnected as true, if JetEnergyLossManager had sent a signal to function GetHardPartonList() of the class HardProcess.
Parameters
m_GetHardPartonListConnected A boolean flag.
Definition at line 74 of file JetEnergyLossManager.h.
View newest version in sPHENIX GitHub at line 74 of file JetEnergyLossManager.h
References GetHardPartonListConnected.
void Jetscape::JetEnergyLossManager::WriteTask (weak_ptr< JetScapeWriter > w) virtual
It writes the output information relevant to the jet energy loss tasks/subtasks into a file. It can be overridden by other tasks.
Parameters
w A pointer of type JetScapeWriter class.
See Also
JetScapeWriter class for further information.
Reimplemented from Jetscape::JetScapeTask.
Definition at line 86 of file JetEnergyLossManager.cc.
View newest version in sPHENIX GitHub at line 86 of file JetEnergyLossManager.cc
References VERBOSE.
Member Data Documentation
sigslot::signal1<vector<shared_ptr<Parton> > &> Jetscape::JetEnergyLossManager::GetHardPartonList
A signal to connect the JetEnergyLossManager to the function GetHardPartonList() of the class HardProcess.
Definition at line 69 of file JetEnergyLossManager.h.
View newest version in sPHENIX GitHub at line 69 of file JetEnergyLossManager.h
bool Jetscape::JetEnergyLossManager::GetHardPartonListConnected private
Definition at line 85 of file JetEnergyLossManager.h.
View newest version in sPHENIX GitHub at line 85 of file JetEnergyLossManager.h
Referenced by GetGetHardPartonListConnected(), and SetGetHardPartonListConnected().
vector<shared_ptr<Parton> > Jetscape::JetEnergyLossManager::hp private
Definition at line 86 of file JetEnergyLossManager.h.
View newest version in sPHENIX GitHub at line 86 of file JetEnergyLossManager.h
The documentation for this class was generated from the following files:
JETSCAPE/blob/main/src/framework/JetEnergyLossManager.h
JETSCAPE/blob/main/src/framework/JetEnergyLossManager.cc