Analysis Software: JETSCAPE/blob/main/jail/vhlle/src/rmn.cpp File Reference
rmn.cpp File Reference
#include <iostream>
#include <fstream>
#include <iomanip>
#include <cstdlib>
#include <execinfo.h>
#include <signal.h>
#include "rmn.h"
Functions
void handler (int sig)
void transformPV (EoS *eos, double Q[7], double &e, double &p, double &nb, double &nq, double &ns, double &vx, double &vy, double &vz)
void transformPVBulk (EoS *eos, double Pi, double Q[7], double &e, double &p, double &nb, double &nq, double &ns, double &vx, double &vy, double &vz)
void transformCV (double e, double p, double nb, double nq, double ns, double vx, double vy, double vz, double Q[])
Variables
bool debugRiemann
Function Documentation
void handler (int sig)
Definition at line 15 of file rmn.cpp.
View newest version in sPHENIX GitHub at line 15 of file rmn.cpp
References TauVsDIS_MachineLearning_Differentiation::array, and size.
void transformCV (double e, double p, double nb, double nq, double ns, double vx, double vy, double vz, double Q[])
Definition at line 246 of file rmn.cpp.
View newest version in sPHENIX GitHub at line 246 of file rmn.cpp
References NB_, NQ_, NS_, merge_hashes::p, T_, vz, X_, Y_, and Z_.
Referenced by main(), and Hydro::source().
void transformPV (EoS * eos, double Q[7], double & e, double & p, double & nb, double & nq, double & ns, double & vx, double & vy, double & vz)
Definition at line 28 of file rmn.cpp.
View newest version in sPHENIX GitHub at line 28 of file rmn.cpp
References debugRiemann, perf_headwind::df, f, i, NB_, NQ_, NS_, merge_hashes::p, EoS::p(), T_, testSigmaEff::v, X_, Y_, and Z_.
Referenced by Cell::getPrimVar(), Cell::getPrimVarHCenter(), Cell::getPrimVarHLeft(), Cell::getPrimVarHRight(), Cell::getPrimVarLeft(), Cell::getPrimVarPrev(), Cell::getPrimVarRight(), and main().
void transformPVBulk (EoS * eos, double Pi, double Q[7], double & e, double & p, double & nb, double & nq, double & ns, double & vx, double & vy, double & vz)
Definition at line 137 of file rmn.cpp.
View newest version in sPHENIX GitHub at line 137 of file rmn.cpp
References debugRiemann, perf_headwind::df, f, handler(), i, NB_, NQ_, NS_, merge_hashes::p, EoS::p(), T_, testSigmaEff::v, X_, Y_, and Z_.
Variable Documentation
bool debugRiemann
Definition at line 13 of file rmn.cpp.
View newest version in sPHENIX GitHub at line 13 of file rmn.cpp
Referenced by Hydro::hlle_flux(), Hydro::performStep(), transformPV(), and transformPVBulk().