Analysis Software: PHSiliconTpcTrackMatching Class Reference
PHSiliconTpcTrackMatching Class Reference
#include <coresoftware/blob/master/offline/packages/trackreco/PHSiliconTpcTrackMatching.h>
Public Member Functions
PHSiliconTpcTrackMatching (const std::string &name="PHSiliconTpcTrackMatching")
~PHSiliconTpcTrackMatching () override
void SetDefaultParameters () override
void set_phi_search_window (const double win)
void set_eta_search_window (const double win)
void set_x_search_window (const double win)
void set_y_search_window (const double win)
void set_z_search_window (const double win)
void set_test_windows_printout (const bool test)
void set_pp_mode (const bool flag)
void set_use_intt_crossing (const bool flag)
int InitRun (PHCompositeNode *topNode) override
int process_event (PHCompositeNode *) override
int End (PHCompositeNode *) override
Called at the end of all processing.
void fieldMap (std::string &fieldmap)
void set_silicon_track_map_name (const std::string &map_name)
void set_track_map_name (const std::string &map_name)
void SetIteration (int iter)
Public Member Functions inherited from SubsysReco
~SubsysReco () override
virtual int EndRun (const int)
Called at the end of each run.
virtual int Init (PHCompositeNode *)
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
void Print (const std::string &="ALL") const override
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Public Member Functions inherited from PHParameterInterface
PHParameterInterface (const std::string &name)
PHParameterInterface (const PHParameterInterface &)=delete
PHParameterInterface & operator= (PHParameterInterface const &)=delete
virtual ~PHParameterInterface ()
void set_paramname (const std::string &name)
void set_double_param (const std::string &name, const double dval)
double get_double_param (const std::string &name) const
void set_int_param (const std::string &name, const int ival)
int get_int_param (const std::string &name) const
void set_string_param (const std::string &name, const std::string &sval)
std::string get_string_param (const std::string &name) const
void UpdateParametersWithMacro ()
void SaveToNodeTree (PHCompositeNode *runNode, const std::string &nodename)
void PutOnParNode (PHCompositeNode *parNode, const std::string &nodename)
void Print () const
Private Member Functions
int GetNodes (PHCompositeNode *topNode)
void findEtaPhiMatches (std::set< unsigned int > &tpc_matched_set, std::set< unsigned int > &tpc_unmatched_set, std::multimap< unsigned int, unsigned int > &tpc_matches)
std::vector< short int > getInttCrossings (TrackSeed *si_track)
void checkCrossingMatches (std::multimap< unsigned int, unsigned int > &tpc_matches)
short int getCrossingIntt (TrackSeed *_tracklet_si)
short int findCrossingGeometrically (unsigned int tpc_id, unsigned int si_id)
double getBunchCrossing (unsigned int trid, double z_mismatch)
Private Attributes
double _phi_search_win = 0.01
double _eta_search_win = 0.004
double _x_search_win = 0.3
double _y_search_win = 0.3
double _z_search_win = 0.4
TrackSeedContainer * _svtx_seed_map {nullptr}
TrackSeedContainer * _track_map {nullptr}
TrackSeedContainer * _track_map_silicon {nullptr}
TrackSeed * _tracklet_tpc {nullptr}
TrackSeed * _tracklet_si {nullptr}
TrkrClusterContainer * _cluster_map {nullptr}
ActsGeometry * _tGeometry {nullptr}
TrkrClusterCrossingAssoc * _cluster_crossing_map {nullptr}
std::map< unsigned int, double > _z_mismatch_map
double _collision_rate = 50e3
double _reference_collision_rate = 50e3
double _si_vertex_dzmax = 0.25
double crossing_period = 106.0
bool _test_windows = false
bool _pp_mode = false
bool _use_intt_crossing = true
int _n_iteration = 0
std::string _track_map_name = "TpcTrackSeedContainer"
std::string _silicon_track_map_name = "SiliconTrackSeedContainer"
std::string m_fieldMap = "1.4"
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = std::numeric_limits<int>::max() - 10
}
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Protected Member Functions inherited from PHParameterInterface
void set_default_double_param (const std::string &name, const double dval)
void set_default_int_param (const std::string &name, const int ival)
void set_default_string_param (const std::string &name, const std::string &sval)
void InitializeParameters ()
Detailed Description
Definition at line 20 of file PHSiliconTpcTrackMatching.h.
View newest version in sPHENIX GitHub at line 20 of file PHSiliconTpcTrackMatching.h
Constructor & Destructor Documentation
PHSiliconTpcTrackMatching::PHSiliconTpcTrackMatching (const std::string & name = "PHSiliconTpcTrackMatching")
Definition at line 41 of file PHSiliconTpcTrackMatching.cc.
View newest version in sPHENIX GitHub at line 41 of file PHSiliconTpcTrackMatching.cc
References PHParameterInterface::InitializeParameters().
PHSiliconTpcTrackMatching::~PHSiliconTpcTrackMatching () override
Definition at line 49 of file PHSiliconTpcTrackMatching.cc.
View newest version in sPHENIX GitHub at line 49 of file PHSiliconTpcTrackMatching.cc
Member Function Documentation
void PHSiliconTpcTrackMatching::checkCrossingMatches (std::multimap< unsigned int, unsigned int > & tpc_matches) private
Definition at line 546 of file PHSiliconTpcTrackMatching.cc.
View newest version in sPHENIX GitHub at line 546 of file PHSiliconTpcTrackMatching.cc
References _tGeometry, _track_map, _track_map_silicon, crossing_period, TrackSeedContainer::get(), TrackSeed::get_crossing(), ActsGeometry::get_drift_velocity(), TrackSeed::get_eta(), TrackSeed::get_z(), it, and Fun4AllBase::Verbosity().
Referenced by process_event().
int PHSiliconTpcTrackMatching::End (PHCompositeNode *) override virtual
Called at the end of all processing.
Reimplemented from SubsysReco.
Definition at line 235 of file PHSiliconTpcTrackMatching.cc.
View newest version in sPHENIX GitHub at line 235 of file PHSiliconTpcTrackMatching.cc
References Fun4AllReturnCodes::EVENT_OK.
void PHSiliconTpcTrackMatching::fieldMap (std::string & fieldmap) inline
Definition at line 46 of file PHSiliconTpcTrackMatching.h.
View newest version in sPHENIX GitHub at line 46 of file PHSiliconTpcTrackMatching.h
References m_fieldMap.
short int PHSiliconTpcTrackMatching::findCrossingGeometrically (unsigned int tpc_id, unsigned int si_id) private
Definition at line 164 of file PHSiliconTpcTrackMatching.cc.
View newest version in sPHENIX GitHub at line 164 of file PHSiliconTpcTrackMatching.cc
References _track_map, _track_map_silicon, TrackSeedContainer::get(), TrackSeed::get_crossing(), TrackSeed::get_z(), getBunchCrossing(), and Fun4AllBase::Verbosity().
Referenced by process_event().
void PHSiliconTpcTrackMatching::findEtaPhiMatches (std::set< unsigned int > & tpc_matched_set, std::set< unsigned int > & tpc_unmatched_set, std::multimap< unsigned int, unsigned int > & tpc_matches) private
Definition at line 317 of file PHSiliconTpcTrackMatching.cc.
View newest version in sPHENIX GitHub at line 317 of file PHSiliconTpcTrackMatching.cc
References _cluster_map, _eta_search_win, _phi_search_win, _pp_mode, _test_windows, _tGeometry, _track_map, _track_map_silicon, _tracklet_si, _tracklet_tpc, _x_search_win, _y_search_win, _z_search_win, TrackSeedContainer::get(), TrackSeed::get_crossing(), TrackSeed::get_eta(), TrackSeed::get_phi(), TrackSeed::get_pt(), TrackSeed::get_qOverR(), TrackSeed::get_x(), TrackSeed::get_y(), TrackSeed::get_z(), TrackSeed::identify(), m_fieldMap, TrackSeedContainer::size(), and Fun4AllBase::Verbosity().
Referenced by process_event().
double PHSiliconTpcTrackMatching::getBunchCrossing (unsigned int trid, double z_mismatch) private
Definition at line 187 of file PHSiliconTpcTrackMatching.cc.
View newest version in sPHENIX GitHub at line 187 of file PHSiliconTpcTrackMatching.cc
References _tGeometry, _track_map, TrackSeed::begin_cluster_keys(), crossing_period, TrackSeed::end_cluster_keys(), TrackSeedContainer::get(), ActsGeometry::get_drift_velocity(), TpcDefs::getSide(), TrkrDefs::getTrkrId(), TrkrDefs::tpcId, and Fun4AllBase::Verbosity().
Referenced by findCrossingGeometrically().
short int PHSiliconTpcTrackMatching::getCrossingIntt (TrackSeed * _tracklet_si) private
Definition at line 456 of file PHSiliconTpcTrackMatching.cc.
View newest version in sPHENIX GitHub at line 456 of file PHSiliconTpcTrackMatching.cc
References false, getInttCrossings(), and Fun4AllBase::Verbosity().
Referenced by process_event().
std::vector< short int > PHSiliconTpcTrackMatching::getInttCrossings (TrackSeed * si_track) private
Definition at line 491 of file PHSiliconTpcTrackMatching.cc.
View newest version in sPHENIX GitHub at line 491 of file PHSiliconTpcTrackMatching.cc
References _cluster_crossing_map, _cluster_map, _tGeometry, _track_map_silicon, TrackSeed::begin_cluster_keys(), TrackSeed::end_cluster_keys(), TrackSeedContainer::find(), TrkrClusterContainer::findCluster(), TrackSeed::get_eta(), TrkrClusterCrossingAssoc::getCrossings(), ActsGeometry::getGlobalPosition(), TrkrDefs::getLayer(), TrkrDefs::getTrkrId(), TrkrDefs::inttId, layer, TrkrDefs::mvtxId, and Fun4AllBase::Verbosity().
Referenced by getCrossingIntt().
int PHSiliconTpcTrackMatching::GetNodes (PHCompositeNode * topNode) private
Get the DST Node
Check that it is there
Get the tracking subnode
Check that it is there
Definition at line 240 of file PHSiliconTpcTrackMatching.cc.
View newest version in sPHENIX GitHub at line 240 of file PHSiliconTpcTrackMatching.cc
References _cluster_crossing_map, _cluster_map, _silicon_track_map_name, _svtx_seed_map, _tGeometry, _track_map, _track_map_name, _track_map_silicon, Fun4AllReturnCodes::ABORTEVENT, PHCompositeNode::addNode(), Fun4AllReturnCodes::EVENT_OK, PHNodeIterator::findFirst(), and PHWHERE.
Referenced by InitRun().
int PHSiliconTpcTrackMatching::InitRun (PHCompositeNode *) override virtual
Called for first event when run number is known. Typically this is where you may want to fetch data from database, because you know the run number.
Reimplemented from SubsysReco.
Definition at line 55 of file PHSiliconTpcTrackMatching.cc.
View newest version in sPHENIX GitHub at line 55 of file PHSiliconTpcTrackMatching.cc
References _eta_search_win, _phi_search_win, _pp_mode, _use_intt_crossing, Fun4AllReturnCodes::EVENT_OK, GetNodes(), PHWHERE, and PHParameterInterface::UpdateParametersWithMacro().
int PHSiliconTpcTrackMatching::process_event (PHCompositeNode *) override virtual
Called for each event. This is where you do the real work.
Reimplemented from SubsysReco.
Definition at line 82 of file PHSiliconTpcTrackMatching.cc.
View newest version in sPHENIX GitHub at line 82 of file PHSiliconTpcTrackMatching.cc
References _svtx_seed_map, _track_map, _track_map_silicon, _tracklet_si, _use_intt_crossing, checkCrossingMatches(), Fun4AllReturnCodes::EVENT_OK, findCrossingGeometrically(), findEtaPhiMatches(), TrackSeedContainer::get(), TrackSeed::get_eta(), TrackSeed::get_pt(), TrackSeed::get_z(), getCrossingIntt(), TrackSeedContainer::insert(), PHWHERE, seed, TrackSeed::set_crossing(), TrackSeedContainer::size(), and Fun4AllBase::Verbosity().
void PHSiliconTpcTrackMatching::set_eta_search_window (const double win) inline
Definition at line 31 of file PHSiliconTpcTrackMatching.h.
View newest version in sPHENIX GitHub at line 31 of file PHSiliconTpcTrackMatching.h
References _eta_search_win.
void PHSiliconTpcTrackMatching::set_phi_search_window (const double win) inline
Definition at line 30 of file PHSiliconTpcTrackMatching.h.
View newest version in sPHENIX GitHub at line 30 of file PHSiliconTpcTrackMatching.h
References _phi_search_win.
void PHSiliconTpcTrackMatching::set_pp_mode (const bool flag) inline
Definition at line 37 of file PHSiliconTpcTrackMatching.h.
View newest version in sPHENIX GitHub at line 37 of file PHSiliconTpcTrackMatching.h
References _pp_mode.
void PHSiliconTpcTrackMatching::set_silicon_track_map_name (const std::string & map_name) inline
Definition at line 48 of file PHSiliconTpcTrackMatching.h.
View newest version in sPHENIX GitHub at line 48 of file PHSiliconTpcTrackMatching.h
References _silicon_track_map_name.
void PHSiliconTpcTrackMatching::set_test_windows_printout (const bool test) inline
Definition at line 36 of file PHSiliconTpcTrackMatching.h.
View newest version in sPHENIX GitHub at line 36 of file PHSiliconTpcTrackMatching.h
References _test_windows, and train_ambiguity_solver::test.
void PHSiliconTpcTrackMatching::set_track_map_name (const std::string & map_name) inline
Definition at line 49 of file PHSiliconTpcTrackMatching.h.
View newest version in sPHENIX GitHub at line 49 of file PHSiliconTpcTrackMatching.h
References _track_map_name.
void PHSiliconTpcTrackMatching::set_use_intt_crossing (const bool flag) inline
Definition at line 38 of file PHSiliconTpcTrackMatching.h.
View newest version in sPHENIX GitHub at line 38 of file PHSiliconTpcTrackMatching.h
References _use_intt_crossing.
void PHSiliconTpcTrackMatching::set_x_search_window (const double win) inline
Definition at line 32 of file PHSiliconTpcTrackMatching.h.
View newest version in sPHENIX GitHub at line 32 of file PHSiliconTpcTrackMatching.h
References _x_search_win.
void PHSiliconTpcTrackMatching::set_y_search_window (const double win) inline
Definition at line 33 of file PHSiliconTpcTrackMatching.h.
View newest version in sPHENIX GitHub at line 33 of file PHSiliconTpcTrackMatching.h
References _y_search_win.
void PHSiliconTpcTrackMatching::set_z_search_window (const double win) inline
Definition at line 34 of file PHSiliconTpcTrackMatching.h.
View newest version in sPHENIX GitHub at line 34 of file PHSiliconTpcTrackMatching.h
References _z_search_win.
void PHSiliconTpcTrackMatching::SetDefaultParameters () override virtual
Implements PHParameterInterface.
Definition at line 71 of file PHSiliconTpcTrackMatching.cc.
View newest version in sPHENIX GitHub at line 71 of file PHSiliconTpcTrackMatching.cc
void PHSiliconTpcTrackMatching::SetIteration (int iter) inline
Definition at line 50 of file PHSiliconTpcTrackMatching.h.
View newest version in sPHENIX GitHub at line 50 of file PHSiliconTpcTrackMatching.h
References _n_iteration.
Member Data Documentation
TrkrClusterCrossingAssoc* PHSiliconTpcTrackMatching::_cluster_crossing_map {nullptr} private
Definition at line 113 of file PHSiliconTpcTrackMatching.h.
View newest version in sPHENIX GitHub at line 113 of file PHSiliconTpcTrackMatching.h
Referenced by getInttCrossings(), and GetNodes().
TrkrClusterContainer* PHSiliconTpcTrackMatching::_cluster_map {nullptr} private
Definition at line 111 of file PHSiliconTpcTrackMatching.h.
View newest version in sPHENIX GitHub at line 111 of file PHSiliconTpcTrackMatching.h
Referenced by findEtaPhiMatches(), getInttCrossings(), and GetNodes().
double PHSiliconTpcTrackMatching::_collision_rate = 50e3 private
Definition at line 117 of file PHSiliconTpcTrackMatching.h.
View newest version in sPHENIX GitHub at line 117 of file PHSiliconTpcTrackMatching.h
double PHSiliconTpcTrackMatching::_eta_search_win = 0.004 private
Definition at line 101 of file PHSiliconTpcTrackMatching.h.
View newest version in sPHENIX GitHub at line 101 of file PHSiliconTpcTrackMatching.h
Referenced by findEtaPhiMatches(), InitRun(), and set_eta_search_window().
int PHSiliconTpcTrackMatching::_n_iteration = 0 private
Definition at line 126 of file PHSiliconTpcTrackMatching.h.
View newest version in sPHENIX GitHub at line 126 of file PHSiliconTpcTrackMatching.h
Referenced by SetIteration().
double PHSiliconTpcTrackMatching::_phi_search_win = 0.01 private
Definition at line 100 of file PHSiliconTpcTrackMatching.h.
View newest version in sPHENIX GitHub at line 100 of file PHSiliconTpcTrackMatching.h
Referenced by findEtaPhiMatches(), InitRun(), and set_phi_search_window().
bool PHSiliconTpcTrackMatching::_pp_mode = false private
Definition at line 123 of file PHSiliconTpcTrackMatching.h.
View newest version in sPHENIX GitHub at line 123 of file PHSiliconTpcTrackMatching.h
Referenced by findEtaPhiMatches(), InitRun(), and set_pp_mode().
double PHSiliconTpcTrackMatching::_reference_collision_rate = 50e3 private
Definition at line 118 of file PHSiliconTpcTrackMatching.h.
View newest version in sPHENIX GitHub at line 118 of file PHSiliconTpcTrackMatching.h
double PHSiliconTpcTrackMatching::_si_vertex_dzmax = 0.25 private
Definition at line 119 of file PHSiliconTpcTrackMatching.h.
View newest version in sPHENIX GitHub at line 119 of file PHSiliconTpcTrackMatching.h
std::string PHSiliconTpcTrackMatching::_silicon_track_map_name = "SiliconTrackSeedContainer" private
Definition at line 128 of file PHSiliconTpcTrackMatching.h.
View newest version in sPHENIX GitHub at line 128 of file PHSiliconTpcTrackMatching.h
Referenced by GetNodes(), and set_silicon_track_map_name().
TrackSeedContainer* PHSiliconTpcTrackMatching::_svtx_seed_map {nullptr} private
Definition at line 106 of file PHSiliconTpcTrackMatching.h.
View newest version in sPHENIX GitHub at line 106 of file PHSiliconTpcTrackMatching.h
Referenced by GetNodes(), and process_event().
bool PHSiliconTpcTrackMatching::_test_windows = false private
Definition at line 122 of file PHSiliconTpcTrackMatching.h.
View newest version in sPHENIX GitHub at line 122 of file PHSiliconTpcTrackMatching.h
Referenced by findEtaPhiMatches(), and set_test_windows_printout().
ActsGeometry* PHSiliconTpcTrackMatching::_tGeometry {nullptr} private
Definition at line 112 of file PHSiliconTpcTrackMatching.h.
View newest version in sPHENIX GitHub at line 112 of file PHSiliconTpcTrackMatching.h
Referenced by checkCrossingMatches(), findEtaPhiMatches(), getBunchCrossing(), getInttCrossings(), and GetNodes().
TrackSeedContainer* PHSiliconTpcTrackMatching::_track_map {nullptr} private
Definition at line 107 of file PHSiliconTpcTrackMatching.h.
View newest version in sPHENIX GitHub at line 107 of file PHSiliconTpcTrackMatching.h
Referenced by checkCrossingMatches(), findCrossingGeometrically(), findEtaPhiMatches(), getBunchCrossing(), GetNodes(), and process_event().
std::string PHSiliconTpcTrackMatching::_track_map_name = "TpcTrackSeedContainer" private
Definition at line 127 of file PHSiliconTpcTrackMatching.h.
View newest version in sPHENIX GitHub at line 127 of file PHSiliconTpcTrackMatching.h
Referenced by GetNodes(), and set_track_map_name().
TrackSeedContainer* PHSiliconTpcTrackMatching::_track_map_silicon {nullptr} private
Definition at line 108 of file PHSiliconTpcTrackMatching.h.
View newest version in sPHENIX GitHub at line 108 of file PHSiliconTpcTrackMatching.h
Referenced by checkCrossingMatches(), findCrossingGeometrically(), findEtaPhiMatches(), getInttCrossings(), GetNodes(), and process_event().
TrackSeed* PHSiliconTpcTrackMatching::_tracklet_si {nullptr} private
Definition at line 110 of file PHSiliconTpcTrackMatching.h.
View newest version in sPHENIX GitHub at line 110 of file PHSiliconTpcTrackMatching.h
Referenced by findEtaPhiMatches(), and process_event().
TrackSeed* PHSiliconTpcTrackMatching::_tracklet_tpc {nullptr} private
Definition at line 109 of file PHSiliconTpcTrackMatching.h.
View newest version in sPHENIX GitHub at line 109 of file PHSiliconTpcTrackMatching.h
Referenced by findEtaPhiMatches().
bool PHSiliconTpcTrackMatching::_use_intt_crossing = true private
Definition at line 124 of file PHSiliconTpcTrackMatching.h.
View newest version in sPHENIX GitHub at line 124 of file PHSiliconTpcTrackMatching.h
Referenced by InitRun(), process_event(), and set_use_intt_crossing().
double PHSiliconTpcTrackMatching::_x_search_win = 0.3 private
Definition at line 102 of file PHSiliconTpcTrackMatching.h.
View newest version in sPHENIX GitHub at line 102 of file PHSiliconTpcTrackMatching.h
Referenced by findEtaPhiMatches(), and set_x_search_window().
double PHSiliconTpcTrackMatching::_y_search_win = 0.3 private
Definition at line 103 of file PHSiliconTpcTrackMatching.h.
View newest version in sPHENIX GitHub at line 103 of file PHSiliconTpcTrackMatching.h
Referenced by findEtaPhiMatches(), and set_y_search_window().
std::map<unsigned int, double> PHSiliconTpcTrackMatching::_z_mismatch_map private
Definition at line 115 of file PHSiliconTpcTrackMatching.h.
View newest version in sPHENIX GitHub at line 115 of file PHSiliconTpcTrackMatching.h
double PHSiliconTpcTrackMatching::_z_search_win = 0.4 private
Definition at line 104 of file PHSiliconTpcTrackMatching.h.
View newest version in sPHENIX GitHub at line 104 of file PHSiliconTpcTrackMatching.h
Referenced by findEtaPhiMatches(), and set_z_search_window().
double PHSiliconTpcTrackMatching::crossing_period = 106.0 private
Definition at line 120 of file PHSiliconTpcTrackMatching.h.
View newest version in sPHENIX GitHub at line 120 of file PHSiliconTpcTrackMatching.h
Referenced by checkCrossingMatches(), and getBunchCrossing().
std::string PHSiliconTpcTrackMatching::m_fieldMap = "1.4" private
Definition at line 129 of file PHSiliconTpcTrackMatching.h.
View newest version in sPHENIX GitHub at line 129 of file PHSiliconTpcTrackMatching.h
Referenced by fieldMap(), and findEtaPhiMatches().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/trackreco/PHSiliconTpcTrackMatching.h
coresoftware/blob/master/offline/packages/trackreco/PHSiliconTpcTrackMatching.cc