Analysis Software: EventHeaderv2 Class Reference
EventHeaderv2 Class Reference
simple event header with ID and time
#include <coresoftware/blob/master/offline/framework/ffaobjects/EventHeaderv2.h>
Public Member Functions
EventHeaderv2 ()=default
ctor
~EventHeaderv2 () override=default
dtor
PHObject * CloneMe () const override
clone
void Reset () override
Clear Event.
void identify (std::ostream &os=std::cout) const override
void set_BunchCrossing (int64_t value) override
bunch crossing
int64_t get_BunchCrossing () const override
bunch crossing
Public Member Functions inherited from EventHeaderv1
EventHeaderv1 ()=default
ctor
~EventHeaderv1 () override=default
dtor
int isValid () const override
isValid returns non zero if object contains valid data
int get_RunNumber () const override
get Run Number
void set_RunNumber (const int run) override
set Run Number
int get_EvtSequence () const override
get Event Number
void set_EvtSequence (const int evtno) override
set Event Number
void set_floatval (const std::string &name, const float fval) override
float get_floatval (const std::string &name) const override
void set_intval (const std::string &name, const int64_t ival) override
int64_t get_intval (const std::string &name) const override
Public Member Functions inherited from EventHeader
~EventHeader () override=default
dtor
int get_EvtType () const
get Event Type (Data,rejected,EOR,BOR,...)
void set_EvtType (const int ival)
set Event Type (Data,rejected,EOR,BOR,...)
void set_ImpactParameter (const double rval)
float get_ImpactParameter () const
void set_EventPlaneAngle (const double rval)
float get_EventPlaneAngle () const
void set_eccentricity (const double rval)
float get_eccentricity () const
void set_ncoll (const int ival)
int get_ncoll () const
void set_npart (const int ival)
int get_npart () const
void set_TimeStamp (const time_t tval)
time_t get_TimeStamp () const
Public Member Functions inherited from PHObject
PHObject ()
ctor
~PHObject () override
dtor
virtual PHObject * clone () const final
PHObject * Clone (const char *newname="") const final
void Copy (TObject &object) const final
virtual int Integrate () const
virtual int Integrate (PHObject *)
virtual void CopyFrom (const PHObject *obj)
Private Attributes
int64_t m_bunchCrossing = 0
bunch crossing id
Detailed Description
simple event header with ID and time
Definition at line 19 of file EventHeaderv2.h.
View newest version in sPHENIX GitHub at line 19 of file EventHeaderv2.h
Constructor & Destructor Documentation
EventHeaderv2::EventHeaderv2 () default
ctor
Referenced by CloneMe().
EventHeaderv2::~EventHeaderv2 () override default
dtor
Member Function Documentation
PHObject* EventHeaderv2::CloneMe () const inline override virtual
clone
Reimplemented from EventHeaderv1.
Definition at line 29 of file EventHeaderv2.h.
View newest version in sPHENIX GitHub at line 29 of file EventHeaderv2.h
References EventHeaderv2().
int64_t EventHeaderv2::get_BunchCrossing () const inline override virtual
bunch crossing
Reimplemented from EventHeader.
Definition at line 50 of file EventHeaderv2.h.
View newest version in sPHENIX GitHub at line 50 of file EventHeaderv2.h
References m_bunchCrossing.
void EventHeaderv2::identify (std::ostream & os = std::cout) const override virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from EventHeaderv1.
Definition at line 11 of file EventHeaderv2.cc.
View newest version in sPHENIX GitHub at line 11 of file EventHeaderv2.cc
References EventHeaderv1::get_EvtSequence(), EventHeader::get_EvtType(), EventHeaderv1::get_RunNumber(), and m_bunchCrossing.
void EventHeaderv2::Reset () override virtual
Clear Event.
Reimplemented from EventHeaderv1.
Definition at line 5 of file EventHeaderv2.cc.
View newest version in sPHENIX GitHub at line 5 of file EventHeaderv2.cc
References m_bunchCrossing, and EventHeaderv1::Reset().
void EventHeaderv2::set_BunchCrossing (int64_t value) inline override virtual
bunch crossing
Reimplemented from EventHeader.
Definition at line 44 of file EventHeaderv2.h.
View newest version in sPHENIX GitHub at line 44 of file EventHeaderv2.h
References m_bunchCrossing, and value.
Member Data Documentation
int64_t EventHeaderv2::m_bunchCrossing = 0 private
bunch crossing id
Definition at line 57 of file EventHeaderv2.h.
View newest version in sPHENIX GitHub at line 57 of file EventHeaderv2.h
Referenced by get_BunchCrossing(), identify(), Reset(), and set_BunchCrossing().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/framework/ffaobjects/EventHeaderv2.h
coresoftware/blob/master/offline/framework/ffaobjects/EventHeaderv2.cc