Analysis Software: PHG4TpcCylinderGeomContainer Class Reference
PHG4TpcCylinderGeomContainer Class Reference
#include <coresoftware/blob/master/simulation/g4simulation/g4detectors/PHG4TpcCylinderGeomContainer.h>
Public Types
typedef std::map< int,
PHG4TpcCylinderGeom * > Map
typedef Map::iterator Iterator
typedef Map::const_iterator ConstIterator
typedef std::pair< Iterator,
Iterator > Range
typedef std::pair
< ConstIterator, ConstIterator > ConstRange
Public Member Functions
PHG4TpcCylinderGeomContainer ()
~PHG4TpcCylinderGeomContainer () override
void identify (std::ostream &os=std::cout) const override
int AddLayerCellGeom (const int i, PHG4TpcCylinderGeom *mygeom)
int AddLayerCellGeom (PHG4TpcCylinderGeom *mygeom)
PHG4TpcCylinderGeom * GetLayerCellGeom (const int i)
PHG4TpcCylinderGeom * GetFirstLayerCellGeom ()
int get_NLayers () const
ConstRange get_begin_end () const
Public Member Functions inherited from PHObject
PHObject ()
ctor
~PHObject () override
dtor
virtual PHObject * CloneMe () const
Virtual copy constructor.
virtual PHObject * clone () const final
PHObject * Clone (const char *newname="") const final
void Copy (TObject &object) const final
virtual void Reset ()
Clear Event.
virtual int isValid () const
isValid returns non zero if object contains vailid data
virtual int Integrate () const
virtual int Integrate (PHObject *)
virtual void CopyFrom (const PHObject *obj)
Protected Attributes
Map layergeoms
Detailed Description
Definition at line 14 of file PHG4TpcCylinderGeomContainer.h.
View newest version in sPHENIX GitHub at line 14 of file PHG4TpcCylinderGeomContainer.h
Member Typedef Documentation
typedef Map::const_iterator PHG4TpcCylinderGeomContainer::ConstIterator
Definition at line 19 of file PHG4TpcCylinderGeomContainer.h.
View newest version in sPHENIX GitHub at line 19 of file PHG4TpcCylinderGeomContainer.h
typedef std::pair<ConstIterator, ConstIterator> PHG4TpcCylinderGeomContainer::ConstRange
Definition at line 21 of file PHG4TpcCylinderGeomContainer.h.
View newest version in sPHENIX GitHub at line 21 of file PHG4TpcCylinderGeomContainer.h
typedef Map::iterator PHG4TpcCylinderGeomContainer::Iterator
Definition at line 18 of file PHG4TpcCylinderGeomContainer.h.
View newest version in sPHENIX GitHub at line 18 of file PHG4TpcCylinderGeomContainer.h
typedef std::map<int, PHG4TpcCylinderGeom *> PHG4TpcCylinderGeomContainer::Map
Definition at line 17 of file PHG4TpcCylinderGeomContainer.h.
View newest version in sPHENIX GitHub at line 17 of file PHG4TpcCylinderGeomContainer.h
typedef std::pair<Iterator, Iterator> PHG4TpcCylinderGeomContainer::Range
Definition at line 20 of file PHG4TpcCylinderGeomContainer.h.
View newest version in sPHENIX GitHub at line 20 of file PHG4TpcCylinderGeomContainer.h
Constructor & Destructor Documentation
PHG4TpcCylinderGeomContainer::PHG4TpcCylinderGeomContainer () inline
Definition at line 23 of file PHG4TpcCylinderGeomContainer.h.
View newest version in sPHENIX GitHub at line 23 of file PHG4TpcCylinderGeomContainer.h
PHG4TpcCylinderGeomContainer::~PHG4TpcCylinderGeomContainer () override
Definition at line 5 of file PHG4TpcCylinderGeomContainer.cc.
View newest version in sPHENIX GitHub at line 5 of file PHG4TpcCylinderGeomContainer.cc
References layergeoms.
Member Function Documentation
int PHG4TpcCylinderGeomContainer::AddLayerCellGeom (const int i, PHG4TpcCylinderGeom * mygeom)
Definition at line 26 of file PHG4TpcCylinderGeomContainer.cc.
View newest version in sPHENIX GitHub at line 26 of file PHG4TpcCylinderGeomContainer.cc
References i, layergeoms, and PHG4TpcCylinderGeom::set_layer().
int PHG4TpcCylinderGeomContainer::AddLayerCellGeom (PHG4TpcCylinderGeom * mygeom)
Definition at line 38 of file PHG4TpcCylinderGeomContainer.cc.
View newest version in sPHENIX GitHub at line 38 of file PHG4TpcCylinderGeomContainer.cc
References PHG4TpcCylinderGeom::get_layer(), layer, and layergeoms.
ConstRange PHG4TpcCylinderGeomContainer::get_begin_end () const inline
Definition at line 34 of file PHG4TpcCylinderGeomContainer.h.
View newest version in sPHENIX GitHub at line 34 of file PHG4TpcCylinderGeomContainer.h
References layergeoms.
Referenced by PHG4TpcDigitizer::CalculateCylinderCellADCScale(), TpcClusterMover::initialize_geometry(), PHHybridSeeding::InitializeGeometry(), QAG4SimulationTpc::InitRun(), PHG4TpcElectronDrift::InitRun(), PHG4TpcPadPlaneReadout::MapToPadPlane(), DumpPHG4TpcCylinderGeomContainer::process_Node(), and MakeActsGeometry::setPlanarSurfaceDivisions().
int PHG4TpcCylinderGeomContainer::get_NLayers () const inline
Definition at line 33 of file PHG4TpcCylinderGeomContainer.h.
View newest version in sPHENIX GitHub at line 33 of file PHG4TpcCylinderGeomContainer.h
References layergeoms.
Referenced by DumpPHG4TpcCylinderGeomContainer::process_Node().
PHG4TpcCylinderGeom * PHG4TpcCylinderGeomContainer::GetFirstLayerCellGeom ()
Definition at line 63 of file PHG4TpcCylinderGeomContainer.cc.
View newest version in sPHENIX GitHub at line 63 of file PHG4TpcCylinderGeomContainer.cc
References layergeoms.
PHG4TpcCylinderGeom * PHG4TpcCylinderGeomContainer::GetLayerCellGeom (const int i)
Definition at line 51 of file PHG4TpcCylinderGeomContainer.cc.
View newest version in sPHENIX GitHub at line 51 of file PHG4TpcCylinderGeomContainer.cc
References layergeoms.
Referenced by TrackEvaluation::add_truth_information(), TpcClusterBuilder::cluster_hits(), PHG4TpcDigitizer::DigitizeCylinderCells(), TrackResiduals::fillHitTree(), TrkrNtuplizer::fillOutputNtuples(), SvtxEvaluator::fillOutputNtuples(), PHTruthClustering::G4ClusterSize(), SvtxTruthEval::G4ClusterSize(), PHSimpleKFProp::get_nodes(), PHTpcClusterMover::InitRun(), PHTruthClustering::LayerClusterG4Hits(), SvtxTruthEval::LayerClusterG4Hits(), TrackerEventDisplay::makeJsonFile(), TrkrNtuplizer::printOutputInfo(), SvtxEvaluator::printOutputInfo(), G4CellNtuple::process_event(), TpcCombinedRawDataUnpacker::process_event(), TpcSimpleClusterizer::process_event(), PHG4TpcPadBaselineShift::process_event(), TpcRawWriter::process_event(), TpcClusterizer::process_event(), TpcRawDataDecoder::process_event(), readDigitalCurrents::process_event(), PHTpcCentralMembraneClusterizer::process_event(), and TpcDirectLaserReconstruction::process_track().
void PHG4TpcCylinderGeomContainer::identify (std::ostream & os = std::cout) const override virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from PHObject.
Definition at line 15 of file PHG4TpcCylinderGeomContainer.cc.
View newest version in sPHENIX GitHub at line 15 of file PHG4TpcCylinderGeomContainer.cc
References layergeoms.
Member Data Documentation
Map PHG4TpcCylinderGeomContainer::layergeoms protected
Definition at line 37 of file PHG4TpcCylinderGeomContainer.h.
View newest version in sPHENIX GitHub at line 37 of file PHG4TpcCylinderGeomContainer.h
Referenced by AddLayerCellGeom(), get_begin_end(), get_NLayers(), GetFirstLayerCellGeom(), GetLayerCellGeom(), identify(), and ~PHG4TpcCylinderGeomContainer().
The documentation for this class was generated from the following files:
coresoftware/blob/master/simulation/g4simulation/g4detectors/PHG4TpcCylinderGeomContainer.h
coresoftware/blob/master/simulation/g4simulation/g4detectors/PHG4TpcCylinderGeomContainer.cc