Analysis Software: PHG4Hitv1 Class Reference
PHG4Hitv1 Class Reference
#include <coresoftware/blob/master/simulation/g4simulation/g4main/PHG4Hitv1.h>
Classes
union u_property
convert between 32bit inputs and storage type prop_storage_t
Public Member Functions
PHG4Hitv1 ()=default
PHG4Hitv1 (const PHG4Hit *g4hit)
~PHG4Hitv1 () override=default
void identify (std::ostream &os=std::cout) const override
void Reset () override
Clear Event.
float get_x (const int i) const override
float get_y (const int i) const override
float get_z (const int i) const override
float get_t (const int i) const override
float get_edep () const override
PHG4HitDefs::keytype get_hit_id () const override
int get_detid () const override
int get_shower_id () const override
int get_trkid () const override
void set_x (const int i, const float f) override
void set_y (const int i, const float f) override
void set_z (const int i, const float f) override
void set_t (const int i, const float f) override
void set_edep (const float f) override
void set_hit_id (const PHG4HitDefs::keytype i) override
void set_shower_id (const int i) override
void set_trkid (const int i) override
void print () const override
bool has_property (const PROPERTY prop_id) const override
float get_property_float (const PROPERTY prop_id) const override
int get_property_int (const PROPERTY prop_id) const override
unsigned int get_property_uint (const PROPERTY prop_id) const override
void set_property (const PROPERTY prop_id, const float value) override
void set_property (const PROPERTY prop_id, const int value) override
void set_property (const PROPERTY prop_id, const unsigned int value) override
float get_px (const int i) const override
float get_py (const int i) const override
float get_pz (const int i) const override
float get_local_x (const int i) const override
float get_local_y (const int i) const override
float get_local_z (const int i) const override
float get_eion () const override
float get_light_yield () const override
float get_raw_light_yield () const override
float get_path_length () const override
unsigned int get_layer () const override
int get_scint_id () const override
int get_row () const override
int get_sector () const override
int get_strip_z_index () const override
int get_strip_y_index () const override
int get_ladder_z_index () const override
int get_ladder_phi_index () const override
int get_index_i () const override
int get_index_j () const override
int get_index_k () const override
int get_index_l () const override
int get_hit_type () const override
void set_px (const int i, const float f) override
void set_py (const int i, const float f) override
void set_pz (const int i, const float f) override
void set_local_x (const int i, const float f) override
void set_local_y (const int i, const float f) override
void set_local_z (const int i, const float f) override
void set_eion (const float f) override
void set_light_yield (const float f) override
void set_raw_light_yield (const float f) override
void set_path_length (const float f) override
void set_layer (const unsigned int i) override
void set_scint_id (const int i) override
void set_row (const int i) override
void set_sector (const int i) override
void set_strip_z_index (const int i) override
void set_strip_y_index (const int i) override
void set_ladder_z_index (const int i) override
void set_ladder_phi_index (const int i) override
void set_index_i (const int i) override
void set_index_j (const int i) override
void set_index_k (const int i) override
void set_index_l (const int i) override
void set_hit_type (const int i) override
Public Member Functions inherited from PHG4Hit
PHG4Hit ()
~PHG4Hit () override
void CopyFrom (const PHObject *phobj) override
virtual float get_avg_x () const
virtual float get_avg_y () const
virtual float get_avg_z () const
virtual float get_avg_t () const
Public Member Functions inherited from PHObject
PHObject ()
ctor
~PHObject () override
dtor
virtual PHObject * CloneMe () const
Virtual copy constructor.
virtual PHObject * clone () const final
PHObject * Clone (const char *newname="") const final
void Copy (TObject &object) const final
virtual int isValid () const
isValid returns non zero if object contains vailid data
virtual int Integrate () const
virtual int Integrate (PHObject *)
Protected Types
typedef uint8_t prop_id_t
storage types for additional property
typedef uint32_t prop_storage_t
typedef std::map< prop_id_t,
prop_storage_t > prop_map_t
Protected Member Functions
unsigned int get_property_nocheck (const PROPERTY prop_id) const override
void set_property_nocheck (const PROPERTY prop_id, const unsigned int ui) override
Protected Attributes
float x [2] = {NAN, NAN}
float y [2] = {NAN, NAN}
float z [2] = {NAN, NAN}
float t [2] = {NAN, NAN}
PHG4HitDefs::keytype hitid = ULONG_LONG_MAX
int trackid = INT_MIN
int showerid = INT_MIN
float edep = NAN
prop_map_t prop_map
container for additional property
Additional Inherited Members
Public Types inherited from PHG4Hit
enum PROPERTY {
prop_eion = 1, prop_light_yield = 2, scint_gammas = 3, cerenkov_gammas = 4,
prop_raw_light_yield = 5, prop_px_0 = 10, prop_px_1 = 11, prop_py_0 = 12,
prop_py_1 = 13, prop_pz_0 = 14, prop_pz_1 = 15, prop_path_length = 16,
prop_local_x_0 = 20, prop_local_x_1 = 21, prop_local_y_0 = 22, prop_local_y_1 = 23,
prop_local_z_0 = 24, prop_local_z_1 = 25, prop_layer = 101, prop_scint_id = 102,
prop_row = 103, prop_sector = 104, prop_strip_z_index = 110, prop_strip_y_index = 111,
prop_ladder_z_index = 112, prop_ladder_phi_index = 113, prop_stave_index = 114, prop_half_stave_index = 115,
prop_module_index = 116, prop_chip_index = 117, prop_local_pos_x_0 = 118, prop_local_pos_y_0 = 119,
prop_local_pos_z_0 = 120, prop_index_i = 121, prop_index_j = 122, prop_index_k = 123,
prop_index_l = 124, prop_hit_type = 125, prop_local_pos_x_1 = 128, prop_local_pos_y_1 = 126,
prop_local_pos_z_1 = 127, prop_MAX_NUMBER = UCHAR_MAX
}
enum PROPERTY_TYPE { type_int = 1, type_uint = 2, type_float = 3, type_unknown = -1 }
Static Public Member Functions inherited from PHG4Hit
static std::pair< const
std::string, PROPERTY_TYPE > get_property_info (PROPERTY prop_id)
static bool check_property (const PROPERTY prop_id, const PROPERTY_TYPE prop_type)
static std::string get_property_type (const PROPERTY_TYPE prop_type)
Detailed Description
Definition at line 15 of file PHG4Hitv1.h.
View newest version in sPHENIX GitHub at line 15 of file PHG4Hitv1.h
Member Typedef Documentation
typedef uint8_t PHG4Hitv1::prop_id_t protected
storage types for additional property
Definition at line 117 of file PHG4Hitv1.h.
View newest version in sPHENIX GitHub at line 117 of file PHG4Hitv1.h
typedef std::map<prop_id_t, prop_storage_t> PHG4Hitv1::prop_map_t protected
Definition at line 119 of file PHG4Hitv1.h.
View newest version in sPHENIX GitHub at line 119 of file PHG4Hitv1.h
typedef uint32_t PHG4Hitv1::prop_storage_t protected
Definition at line 118 of file PHG4Hitv1.h.
View newest version in sPHENIX GitHub at line 118 of file PHG4Hitv1.h
Constructor & Destructor Documentation
PHG4Hitv1::PHG4Hitv1 () default
PHG4Hitv1::PHG4Hitv1 (const PHG4Hit * g4hit) explicit
Definition at line 14 of file PHG4Hitv1.cc.
View newest version in sPHENIX GitHub at line 14 of file PHG4Hitv1.cc
PHG4Hitv1::~PHG4Hitv1 () override default
Member Function Documentation
int PHG4Hitv1::get_detid () const override virtual
Reimplemented from PHG4Hit.
Definition at line 37 of file PHG4Hitv1.cc.
View newest version in sPHENIX GitHub at line 37 of file PHG4Hitv1.cc
References PHG4HitDefs::hit_idbits.
float PHG4Hitv1::get_edep () const inline override virtual
Reimplemented from PHG4Hit.
Definition at line 29 of file PHG4Hitv1.h.
View newest version in sPHENIX GitHub at line 29 of file PHG4Hitv1.h
References edep.
float PHG4Hitv1::get_eion () const inline override virtual
Reimplemented from PHG4Hit.
Definition at line 60 of file PHG4Hitv1.h.
View newest version in sPHENIX GitHub at line 60 of file PHG4Hitv1.h
References get_property_float(), and PHG4Hit::prop_eion.
PHG4HitDefs::keytype PHG4Hitv1::get_hit_id () const inline override virtual
Reimplemented from PHG4Hit.
Definition at line 30 of file PHG4Hitv1.h.
View newest version in sPHENIX GitHub at line 30 of file PHG4Hitv1.h
References hitid.
int PHG4Hitv1::get_hit_type () const inline override virtual
Reimplemented from PHG4Hit.
Definition at line 76 of file PHG4Hitv1.h.
View newest version in sPHENIX GitHub at line 76 of file PHG4Hitv1.h
References get_property_int(), and PHG4Hit::prop_hit_type.
int PHG4Hitv1::get_index_i () const inline override virtual
Reimplemented from PHG4Hit.
Definition at line 72 of file PHG4Hitv1.h.
View newest version in sPHENIX GitHub at line 72 of file PHG4Hitv1.h
References get_property_int(), and PHG4Hit::prop_index_i.
int PHG4Hitv1::get_index_j () const inline override virtual
Reimplemented from PHG4Hit.
Definition at line 73 of file PHG4Hitv1.h.
View newest version in sPHENIX GitHub at line 73 of file PHG4Hitv1.h
References get_property_int(), and PHG4Hit::prop_index_j.
int PHG4Hitv1::get_index_k () const inline override virtual
Reimplemented from PHG4Hit.
Definition at line 74 of file PHG4Hitv1.h.
View newest version in sPHENIX GitHub at line 74 of file PHG4Hitv1.h
References get_property_int(), and PHG4Hit::prop_index_k.
int PHG4Hitv1::get_index_l () const inline override virtual
Reimplemented from PHG4Hit.
Definition at line 75 of file PHG4Hitv1.h.
View newest version in sPHENIX GitHub at line 75 of file PHG4Hitv1.h
References get_property_int(), and PHG4Hit::prop_index_l.
int PHG4Hitv1::get_ladder_phi_index () const inline override virtual
Reimplemented from PHG4Hit.
Definition at line 71 of file PHG4Hitv1.h.
View newest version in sPHENIX GitHub at line 71 of file PHG4Hitv1.h
References get_property_int(), and PHG4Hit::prop_ladder_phi_index.
int PHG4Hitv1::get_ladder_z_index () const inline override virtual
Reimplemented from PHG4Hit.
Definition at line 70 of file PHG4Hitv1.h.
View newest version in sPHENIX GitHub at line 70 of file PHG4Hitv1.h
References get_property_int(), and PHG4Hit::prop_ladder_z_index.
unsigned int PHG4Hitv1::get_layer () const inline override virtual
Reimplemented from PHG4Hit.
Definition at line 64 of file PHG4Hitv1.h.
View newest version in sPHENIX GitHub at line 64 of file PHG4Hitv1.h
References get_property_uint(), and PHG4Hit::prop_layer.
float PHG4Hitv1::get_light_yield () const inline override virtual
Reimplemented from PHG4Hit.
Definition at line 61 of file PHG4Hitv1.h.
View newest version in sPHENIX GitHub at line 61 of file PHG4Hitv1.h
References get_property_float(), and PHG4Hit::prop_light_yield.
float PHG4Hitv1::get_local_x (const int i) const override virtual
Reimplemented from PHG4Hit.
Definition at line 287 of file PHG4Hitv1.cc.
View newest version in sPHENIX GitHub at line 287 of file PHG4Hitv1.cc
float PHG4Hitv1::get_local_y (const int i) const override virtual
Reimplemented from PHG4Hit.
Definition at line 302 of file PHG4Hitv1.cc.
View newest version in sPHENIX GitHub at line 302 of file PHG4Hitv1.cc
float PHG4Hitv1::get_local_z (const int i) const override virtual
Reimplemented from PHG4Hit.
Definition at line 317 of file PHG4Hitv1.cc.
View newest version in sPHENIX GitHub at line 317 of file PHG4Hitv1.cc
float PHG4Hitv1::get_path_length () const inline override virtual
Reimplemented from PHG4Hit.
Definition at line 63 of file PHG4Hitv1.h.
View newest version in sPHENIX GitHub at line 63 of file PHG4Hitv1.h
References get_property_float(), and PHG4Hit::prop_path_length.
float PHG4Hitv1::get_property_float (const PROPERTY prop_id) const override virtual
Reimplemented from PHG4Hit.
Definition at line 83 of file PHG4Hitv1.cc.
View newest version in sPHENIX GitHub at line 83 of file PHG4Hitv1.cc
References PHG4Hitv1::u_property::fdata, i, and PHWHERE.
Referenced by get_eion(), get_light_yield(), get_path_length(), and get_raw_light_yield().
int PHG4Hitv1::get_property_int (const PROPERTY prop_id) const override virtual
Reimplemented from PHG4Hit.
Definition at line 101 of file PHG4Hitv1.cc.
View newest version in sPHENIX GitHub at line 101 of file PHG4Hitv1.cc
References i, PHG4Hitv1::u_property::idata, and PHWHERE.
Referenced by get_hit_type(), get_index_i(), get_index_j(), get_index_k(), get_index_l(), get_ladder_phi_index(), get_ladder_z_index(), get_row(), get_scint_id(), get_sector(), get_strip_y_index(), and get_strip_z_index().
unsigned int PHG4Hitv1::get_property_nocheck (const PROPERTY prop_id) const override protected virtual
Reimplemented from PHG4Hit.
Definition at line 179 of file PHG4Hitv1.cc.
View newest version in sPHENIX GitHub at line 179 of file PHG4Hitv1.cc
unsigned int PHG4Hitv1::get_property_uint (const PROPERTY prop_id) const override virtual
Reimplemented from PHG4Hit.
Definition at line 119 of file PHG4Hitv1.cc.
View newest version in sPHENIX GitHub at line 119 of file PHG4Hitv1.cc
References i, PHWHERE, and PHG4Hitv1::u_property::uidata.
Referenced by get_layer().
float PHG4Hitv1::get_px (const int i) const override virtual
Reimplemented from PHG4Hit.
Definition at line 190 of file PHG4Hitv1.cc.
View newest version in sPHENIX GitHub at line 190 of file PHG4Hitv1.cc
float PHG4Hitv1::get_py (const int i) const override virtual
Reimplemented from PHG4Hit.
Definition at line 205 of file PHG4Hitv1.cc.
View newest version in sPHENIX GitHub at line 205 of file PHG4Hitv1.cc
float PHG4Hitv1::get_pz (const int i) const override virtual
Reimplemented from PHG4Hit.
Definition at line 220 of file PHG4Hitv1.cc.
View newest version in sPHENIX GitHub at line 220 of file PHG4Hitv1.cc
float PHG4Hitv1::get_raw_light_yield () const inline override virtual
Reimplemented from PHG4Hit.
Definition at line 62 of file PHG4Hitv1.h.
View newest version in sPHENIX GitHub at line 62 of file PHG4Hitv1.h
References get_property_float(), and PHG4Hit::prop_raw_light_yield.
int PHG4Hitv1::get_row () const inline override virtual
Reimplemented from PHG4Hit.
Definition at line 66 of file PHG4Hitv1.h.
View newest version in sPHENIX GitHub at line 66 of file PHG4Hitv1.h
References get_property_int(), and PHG4Hit::prop_row.
int PHG4Hitv1::get_scint_id () const inline override virtual
Reimplemented from PHG4Hit.
Definition at line 65 of file PHG4Hitv1.h.
View newest version in sPHENIX GitHub at line 65 of file PHG4Hitv1.h
References get_property_int(), and PHG4Hit::prop_scint_id.
int PHG4Hitv1::get_sector () const inline override virtual
Reimplemented from PHG4Hit.
Definition at line 67 of file PHG4Hitv1.h.
View newest version in sPHENIX GitHub at line 67 of file PHG4Hitv1.h
References get_property_int(), and PHG4Hit::prop_sector.
int PHG4Hitv1::get_shower_id () const inline override virtual
Reimplemented from PHG4Hit.
Definition at line 32 of file PHG4Hitv1.h.
View newest version in sPHENIX GitHub at line 32 of file PHG4Hitv1.h
References showerid.
int PHG4Hitv1::get_strip_y_index () const inline override virtual
Reimplemented from PHG4Hit.
Definition at line 69 of file PHG4Hitv1.h.
View newest version in sPHENIX GitHub at line 69 of file PHG4Hitv1.h
References get_property_int(), and PHG4Hit::prop_strip_y_index.
int PHG4Hitv1::get_strip_z_index () const inline override virtual
Reimplemented from PHG4Hit.
Definition at line 68 of file PHG4Hitv1.h.
View newest version in sPHENIX GitHub at line 68 of file PHG4Hitv1.h
References get_property_int(), and PHG4Hit::prop_strip_z_index.
float PHG4Hitv1::get_t (const int i) const inline override virtual
Reimplemented from PHG4Hit.
Definition at line 28 of file PHG4Hitv1.h.
View newest version in sPHENIX GitHub at line 28 of file PHG4Hitv1.h
References i, and t.
int PHG4Hitv1::get_trkid () const inline override virtual
Reimplemented from PHG4Hit.
Definition at line 33 of file PHG4Hitv1.h.
View newest version in sPHENIX GitHub at line 33 of file PHG4Hitv1.h
References trackid.
float PHG4Hitv1::get_x (const int i) const inline override virtual
Reimplemented from PHG4Hit.
Definition at line 25 of file PHG4Hitv1.h.
View newest version in sPHENIX GitHub at line 25 of file PHG4Hitv1.h
References i, and x.
float PHG4Hitv1::get_y (const int i) const inline override virtual
Reimplemented from PHG4Hit.
Definition at line 26 of file PHG4Hitv1.h.
View newest version in sPHENIX GitHub at line 26 of file PHG4Hitv1.h
References i, and y.
float PHG4Hitv1::get_z (const int i) const inline override virtual
Reimplemented from PHG4Hit.
Definition at line 27 of file PHG4Hitv1.h.
View newest version in sPHENIX GitHub at line 27 of file PHG4Hitv1.h
References i, and z.
bool PHG4Hitv1::has_property (const PROPERTY prop_id) const override virtual
Reimplemented from PHG4Hit.
Definition at line 76 of file PHG4Hitv1.cc.
View newest version in sPHENIX GitHub at line 76 of file PHG4Hitv1.cc
References i.
void PHG4Hitv1::identify (std::ostream & os = std::cout) const override virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from PHG4Hit.
Definition at line 383 of file PHG4Hitv1.cc.
View newest version in sPHENIX GitHub at line 383 of file PHG4Hitv1.cc
References i.
void PHG4Hitv1::print () const override virtual
Reimplemented from PHG4Hit.
Definition at line 46 of file PHG4Hitv1.cc.
View newest version in sPHENIX GitHub at line 46 of file PHG4Hitv1.cc
References i, t, ambiguity_solver_full_chain::x, y, and physmon_track_finding_ttbar::z.
void PHG4Hitv1::Reset () override virtual
Clear Event.
Reimplemented from PHG4Hit.
Definition at line 20 of file PHG4Hitv1.cc.
View newest version in sPHENIX GitHub at line 20 of file PHG4Hitv1.cc
References i.
void PHG4Hitv1::set_edep (const float f) inline override virtual
Reimplemented from PHG4Hit.
Definition at line 39 of file PHG4Hitv1.h.
View newest version in sPHENIX GitHub at line 39 of file PHG4Hitv1.h
References edep, and f.
void PHG4Hitv1::set_eion (const float f) inline override virtual
Reimplemented from PHG4Hit.
Definition at line 84 of file PHG4Hitv1.h.
View newest version in sPHENIX GitHub at line 84 of file PHG4Hitv1.h
References PHG4Hit::prop_eion, and set_property().
void PHG4Hitv1::set_hit_id (const PHG4HitDefs::keytype i) inline override virtual
Reimplemented from PHG4Hit.
Definition at line 40 of file PHG4Hitv1.h.
View newest version in sPHENIX GitHub at line 40 of file PHG4Hitv1.h
References hitid, and i.
void PHG4Hitv1::set_hit_type (const int i) inline override virtual
Reimplemented from PHG4Hit.
Definition at line 100 of file PHG4Hitv1.h.
View newest version in sPHENIX GitHub at line 100 of file PHG4Hitv1.h
References PHG4Hit::prop_hit_type, and set_property().
void PHG4Hitv1::set_index_i (const int i) inline override virtual
Reimplemented from PHG4Hit.
Definition at line 96 of file PHG4Hitv1.h.
View newest version in sPHENIX GitHub at line 96 of file PHG4Hitv1.h
References PHG4Hit::prop_index_i, and set_property().
void PHG4Hitv1::set_index_j (const int i) inline override virtual
Reimplemented from PHG4Hit.
Definition at line 97 of file PHG4Hitv1.h.
View newest version in sPHENIX GitHub at line 97 of file PHG4Hitv1.h
References PHG4Hit::prop_index_j, and set_property().
void PHG4Hitv1::set_index_k (const int i) inline override virtual
Reimplemented from PHG4Hit.
Definition at line 98 of file PHG4Hitv1.h.
View newest version in sPHENIX GitHub at line 98 of file PHG4Hitv1.h
References PHG4Hit::prop_index_k, and set_property().
void PHG4Hitv1::set_index_l (const int i) inline override virtual
Reimplemented from PHG4Hit.
Definition at line 99 of file PHG4Hitv1.h.
View newest version in sPHENIX GitHub at line 99 of file PHG4Hitv1.h
References PHG4Hit::prop_index_l, and set_property().
void PHG4Hitv1::set_ladder_phi_index (const int i) inline override virtual
Reimplemented from PHG4Hit.
Definition at line 95 of file PHG4Hitv1.h.
View newest version in sPHENIX GitHub at line 95 of file PHG4Hitv1.h
References PHG4Hit::prop_ladder_phi_index, and set_property().
void PHG4Hitv1::set_ladder_z_index (const int i) inline override virtual
Reimplemented from PHG4Hit.
Definition at line 94 of file PHG4Hitv1.h.
View newest version in sPHENIX GitHub at line 94 of file PHG4Hitv1.h
References PHG4Hit::prop_ladder_z_index, and set_property().
void PHG4Hitv1::set_layer (const unsigned int i) inline override virtual
Reimplemented from PHG4Hit.
Definition at line 88 of file PHG4Hitv1.h.
View newest version in sPHENIX GitHub at line 88 of file PHG4Hitv1.h
References PHG4Hit::prop_layer, and set_property().
void PHG4Hitv1::set_light_yield (const float f) inline override virtual
Reimplemented from PHG4Hit.
Definition at line 85 of file PHG4Hitv1.h.
View newest version in sPHENIX GitHub at line 85 of file PHG4Hitv1.h
References PHG4Hit::prop_light_yield, and set_property().
void PHG4Hitv1::set_local_x (const int i, const float f) override virtual
Reimplemented from PHG4Hit.
Definition at line 332 of file PHG4Hitv1.cc.
View newest version in sPHENIX GitHub at line 332 of file PHG4Hitv1.cc
void PHG4Hitv1::set_local_y (const int i, const float f) override virtual
Reimplemented from PHG4Hit.
Definition at line 349 of file PHG4Hitv1.cc.
View newest version in sPHENIX GitHub at line 349 of file PHG4Hitv1.cc
void PHG4Hitv1::set_local_z (const int i, const float f) override virtual
Reimplemented from PHG4Hit.
Definition at line 366 of file PHG4Hitv1.cc.
View newest version in sPHENIX GitHub at line 366 of file PHG4Hitv1.cc
void PHG4Hitv1::set_path_length (const float f) inline override virtual
Reimplemented from PHG4Hit.
Definition at line 87 of file PHG4Hitv1.h.
View newest version in sPHENIX GitHub at line 87 of file PHG4Hitv1.h
References PHG4Hit::prop_path_length, and set_property().
void PHG4Hitv1::set_property (const PROPERTY prop_id, const float value) override virtual
Reimplemented from PHG4Hit.
Definition at line 137 of file PHG4Hitv1.cc.
View newest version in sPHENIX GitHub at line 137 of file PHG4Hitv1.cc
References PHG4Hitv1::u_property::get_storage(), and PHWHERE.
Referenced by set_eion(), set_hit_type(), set_index_i(), set_index_j(), set_index_k(), set_index_l(), set_ladder_phi_index(), set_ladder_z_index(), set_layer(), set_light_yield(), set_path_length(), set_raw_light_yield(), set_row(), set_scint_id(), set_sector(), set_strip_y_index(), and set_strip_z_index().
void PHG4Hitv1::set_property (const PROPERTY prop_id, const int value) override virtual
Reimplemented from PHG4Hit.
Definition at line 151 of file PHG4Hitv1.cc.
View newest version in sPHENIX GitHub at line 151 of file PHG4Hitv1.cc
References PHG4Hitv1::u_property::get_storage(), and PHWHERE.
void PHG4Hitv1::set_property (const PROPERTY prop_id, const unsigned int value) override virtual
Reimplemented from PHG4Hit.
Definition at line 165 of file PHG4Hitv1.cc.
View newest version in sPHENIX GitHub at line 165 of file PHG4Hitv1.cc
References PHG4Hitv1::u_property::get_storage(), and PHWHERE.
void PHG4Hitv1::set_property_nocheck (const PROPERTY prop_id, const unsigned int ui) inline override protected virtual
Reimplemented from PHG4Hit.
Definition at line 104 of file PHG4Hitv1.h.
View newest version in sPHENIX GitHub at line 104 of file PHG4Hitv1.h
References prop_map.
void PHG4Hitv1::set_px (const int i, const float f) override virtual
Reimplemented from PHG4Hit.
Definition at line 235 of file PHG4Hitv1.cc.
View newest version in sPHENIX GitHub at line 235 of file PHG4Hitv1.cc
void PHG4Hitv1::set_py (const int i, const float f) override virtual
Reimplemented from PHG4Hit.
Definition at line 252 of file PHG4Hitv1.cc.
View newest version in sPHENIX GitHub at line 252 of file PHG4Hitv1.cc
void PHG4Hitv1::set_pz (const int i, const float f) override virtual
Reimplemented from PHG4Hit.
Definition at line 269 of file PHG4Hitv1.cc.
View newest version in sPHENIX GitHub at line 269 of file PHG4Hitv1.cc
void PHG4Hitv1::set_raw_light_yield (const float f) inline override virtual
Reimplemented from PHG4Hit.
Definition at line 86 of file PHG4Hitv1.h.
View newest version in sPHENIX GitHub at line 86 of file PHG4Hitv1.h
References PHG4Hit::prop_raw_light_yield, and set_property().
void PHG4Hitv1::set_row (const int i) inline override virtual
Reimplemented from PHG4Hit.
Definition at line 90 of file PHG4Hitv1.h.
View newest version in sPHENIX GitHub at line 90 of file PHG4Hitv1.h
References PHG4Hit::prop_row, and set_property().
void PHG4Hitv1::set_scint_id (const int i) inline override virtual
Reimplemented from PHG4Hit.
Definition at line 89 of file PHG4Hitv1.h.
View newest version in sPHENIX GitHub at line 89 of file PHG4Hitv1.h
References PHG4Hit::prop_scint_id, and set_property().
void PHG4Hitv1::set_sector (const int i) inline override virtual
Reimplemented from PHG4Hit.
Definition at line 91 of file PHG4Hitv1.h.
View newest version in sPHENIX GitHub at line 91 of file PHG4Hitv1.h
References PHG4Hit::prop_sector, and set_property().
void PHG4Hitv1::set_shower_id (const int i) inline override virtual
Reimplemented from PHG4Hit.
Definition at line 41 of file PHG4Hitv1.h.
View newest version in sPHENIX GitHub at line 41 of file PHG4Hitv1.h
References i, and showerid.
void PHG4Hitv1::set_strip_y_index (const int i) inline override virtual
Reimplemented from PHG4Hit.
Definition at line 93 of file PHG4Hitv1.h.
View newest version in sPHENIX GitHub at line 93 of file PHG4Hitv1.h
References PHG4Hit::prop_strip_y_index, and set_property().
void PHG4Hitv1::set_strip_z_index (const int i) inline override virtual
Reimplemented from PHG4Hit.
Definition at line 92 of file PHG4Hitv1.h.
View newest version in sPHENIX GitHub at line 92 of file PHG4Hitv1.h
References PHG4Hit::prop_strip_z_index, and set_property().
void PHG4Hitv1::set_t (const int i, const float f) inline override virtual
Reimplemented from PHG4Hit.
Definition at line 38 of file PHG4Hitv1.h.
View newest version in sPHENIX GitHub at line 38 of file PHG4Hitv1.h
References f, i, and t.
void PHG4Hitv1::set_trkid (const int i) inline override virtual
Reimplemented from PHG4Hit.
Definition at line 42 of file PHG4Hitv1.h.
View newest version in sPHENIX GitHub at line 42 of file PHG4Hitv1.h
References i, and trackid.
void PHG4Hitv1::set_x (const int i, const float f) inline override virtual
Reimplemented from PHG4Hit.
Definition at line 35 of file PHG4Hitv1.h.
View newest version in sPHENIX GitHub at line 35 of file PHG4Hitv1.h
References f, i, and x.
void PHG4Hitv1::set_y (const int i, const float f) inline override virtual
Reimplemented from PHG4Hit.
Definition at line 36 of file PHG4Hitv1.h.
View newest version in sPHENIX GitHub at line 36 of file PHG4Hitv1.h
References f, i, and y.
void PHG4Hitv1::set_z (const int i, const float f) inline override virtual
Reimplemented from PHG4Hit.
Definition at line 37 of file PHG4Hitv1.h.
View newest version in sPHENIX GitHub at line 37 of file PHG4Hitv1.h
References f, i, and z.
Member Data Documentation
float PHG4Hitv1::edep = NAN protected
Definition at line 114 of file PHG4Hitv1.h.
View newest version in sPHENIX GitHub at line 114 of file PHG4Hitv1.h
Referenced by get_edep(), and set_edep().
PHG4HitDefs::keytype PHG4Hitv1::hitid = ULONG_LONG_MAX protected
Definition at line 111 of file PHG4Hitv1.h.
View newest version in sPHENIX GitHub at line 111 of file PHG4Hitv1.h
Referenced by get_hit_id(), and set_hit_id().
prop_map_t PHG4Hitv1::prop_map protected
container for additional property
Definition at line 149 of file PHG4Hitv1.h.
View newest version in sPHENIX GitHub at line 149 of file PHG4Hitv1.h
Referenced by set_property_nocheck().
int PHG4Hitv1::showerid = INT_MIN protected
Definition at line 113 of file PHG4Hitv1.h.
View newest version in sPHENIX GitHub at line 113 of file PHG4Hitv1.h
Referenced by get_shower_id(), and set_shower_id().
float PHG4Hitv1::t[2] = {NAN, NAN} protected
Definition at line 110 of file PHG4Hitv1.h.
View newest version in sPHENIX GitHub at line 110 of file PHG4Hitv1.h
Referenced by get_t(), and set_t().
int PHG4Hitv1::trackid = INT_MIN protected
Definition at line 112 of file PHG4Hitv1.h.
View newest version in sPHENIX GitHub at line 112 of file PHG4Hitv1.h
Referenced by get_trkid(), and set_trkid().
float PHG4Hitv1::x[2] = {NAN, NAN} protected
Definition at line 107 of file PHG4Hitv1.h.
View newest version in sPHENIX GitHub at line 107 of file PHG4Hitv1.h
Referenced by get_x(), and set_x().
float PHG4Hitv1::y[2] = {NAN, NAN} protected
Definition at line 108 of file PHG4Hitv1.h.
View newest version in sPHENIX GitHub at line 108 of file PHG4Hitv1.h
Referenced by get_y(), and set_y().
float PHG4Hitv1::z[2] = {NAN, NAN} protected
Definition at line 109 of file PHG4Hitv1.h.
View newest version in sPHENIX GitHub at line 109 of file PHG4Hitv1.h
Referenced by get_z(), and set_z().
The documentation for this class was generated from the following files:
coresoftware/blob/master/simulation/g4simulation/g4main/PHG4Hitv1.h
coresoftware/blob/master/simulation/g4simulation/g4main/PHG4Hitv1.cc