Analysis Software: InttRawHit Class Reference
InttRawHit Class Reference
#include <coresoftware/blob/master/offline/framework/ffarawobjects/InttRawHit.h>
Public Member Functions
InttRawHit ()=default
virtual ~InttRawHit ()=default
virtual uint64_t get_bco () const
virtual void set_bco (const uint64_t)
virtual int32_t get_packetid () const
virtual void set_packetid (const int32_t)
virtual uint32_t get_word () const
virtual void set_word (uint32_t)
virtual uint16_t get_fee () const
virtual void set_fee (uint16_t)
virtual uint16_t get_channel_id () const
virtual void set_channel_id (uint16_t)
virtual uint16_t get_chip_id () const
virtual void set_chip_id (uint16_t)
virtual uint16_t get_adc () const
virtual void set_adc (uint16_t)
virtual uint16_t get_FPHX_BCO () const
virtual void set_FPHX_BCO (uint16_t)
virtual uint16_t get_full_FPHX () const
virtual void set_full_FPHX (uint16_t)
virtual uint16_t get_full_ROC () const
virtual void set_full_ROC (uint16_t)
virtual uint16_t get_amplitude () const
virtual void set_amplitude (uint16_t)
Public Member Functions inherited from PHObject
PHObject ()
ctor
~PHObject () override
dtor
virtual PHObject * CloneMe () const
Virtual copy constructor.
virtual PHObject * clone () const final
PHObject * Clone (const char *newname="") const final
void Copy (TObject &object) const final
virtual void identify (std::ostream &os=std::cout) const
virtual void Reset ()
Clear Event.
virtual int isValid () const
isValid returns non zero if object contains vailid data
virtual int Integrate () const
virtual int Integrate (PHObject *)
virtual void CopyFrom (const PHObject *obj)
Detailed Description
Definition at line 9 of file InttRawHit.h.
View newest version in sPHENIX GitHub at line 9 of file InttRawHit.h
Constructor & Destructor Documentation
InttRawHit::InttRawHit () default
virtual InttRawHit::~InttRawHit () virtual default
Member Function Documentation
virtual uint16_t InttRawHit::get_adc () const inline virtual
Reimplemented in InttRawHitv1.
Definition at line 35 of file InttRawHit.h.
View newest version in sPHENIX GitHub at line 35 of file InttRawHit.h
Referenced by InttRawHitv1::InttRawHitv1(), InttCombinedRawDataDecoder::process_event(), InttCombinedRawDataConverter::process_event(), and DumpInttRawHitContainer::process_Node().
virtual uint16_t InttRawHit::get_amplitude () const inline virtual
Reimplemented in InttRawHitv1.
Definition at line 47 of file InttRawHit.h.
View newest version in sPHENIX GitHub at line 47 of file InttRawHit.h
Referenced by InttRawHitv1::InttRawHitv1(), InttCombinedRawDataConverter::process_event(), and DumpInttRawHitContainer::process_Node().
virtual uint64_t InttRawHit::get_bco () const inline virtual
Reimplemented in InttRawHitv1.
Definition at line 17 of file InttRawHit.h.
View newest version in sPHENIX GitHub at line 17 of file InttRawHit.h
Referenced by InttRawHitContainerv1::identify(), InttRawHitv1::InttRawHitv1(), InttCombinedRawDataDecoder::process_event(), StreamingCheck::process_event(), InttCheck::process_event(), InttCombinedRawDataConverter::process_event(), and DumpInttRawHitContainer::process_Node().
virtual uint16_t InttRawHit::get_channel_id () const inline virtual
Reimplemented in InttRawHitv1.
Definition at line 29 of file InttRawHit.h.
View newest version in sPHENIX GitHub at line 29 of file InttRawHit.h
Referenced by SingleInttPoolInput::FillPool(), InttRawHitv1::InttRawHitv1(), DumpInttRawHitContainer::process_Node(), and InttNameSpace::RawFromHit().
virtual uint16_t InttRawHit::get_chip_id () const inline virtual
Reimplemented in InttRawHitv1.
Definition at line 32 of file InttRawHit.h.
View newest version in sPHENIX GitHub at line 32 of file InttRawHit.h
Referenced by InttRawHitv1::InttRawHitv1(), DumpInttRawHitContainer::process_Node(), and InttNameSpace::RawFromHit().
virtual uint16_t InttRawHit::get_fee () const inline virtual
Reimplemented in InttRawHitv1.
Definition at line 26 of file InttRawHit.h.
View newest version in sPHENIX GitHub at line 26 of file InttRawHit.h
Referenced by Fun4AllStreamingInputManager::AddInttRawHit(), InttRawHitv1::InttRawHitv1(), DumpInttRawHitContainer::process_Node(), and InttNameSpace::RawFromHit().
virtual uint16_t InttRawHit::get_FPHX_BCO () const inline virtual
Reimplemented in InttRawHitv1.
Definition at line 38 of file InttRawHit.h.
View newest version in sPHENIX GitHub at line 38 of file InttRawHit.h
Referenced by InttRawHitv1::InttRawHitv1(), InttCombinedRawDataConverter::process_event(), and DumpInttRawHitContainer::process_Node().
virtual uint16_t InttRawHit::get_full_FPHX () const inline virtual
Reimplemented in InttRawHitv1.
Definition at line 41 of file InttRawHit.h.
View newest version in sPHENIX GitHub at line 41 of file InttRawHit.h
Referenced by InttRawHitv1::InttRawHitv1(), and DumpInttRawHitContainer::process_Node().
virtual uint16_t InttRawHit::get_full_ROC () const inline virtual
Reimplemented in InttRawHitv1.
Definition at line 44 of file InttRawHit.h.
View newest version in sPHENIX GitHub at line 44 of file InttRawHit.h
Referenced by InttRawHitv1::InttRawHitv1(), and DumpInttRawHitContainer::process_Node().
virtual int32_t InttRawHit::get_packetid () const inline virtual
Reimplemented in InttRawHitv1.
Definition at line 20 of file InttRawHit.h.
View newest version in sPHENIX GitHub at line 20 of file InttRawHit.h
Referenced by Fun4AllStreamingInputManager::AddInttRawHit(), InttRawHitv1::InttRawHitv1(), DumpInttRawHitContainer::process_Node(), and InttNameSpace::RawFromHit().
virtual uint32_t InttRawHit::get_word () const inline virtual
Reimplemented in InttRawHitv1.
Definition at line 23 of file InttRawHit.h.
View newest version in sPHENIX GitHub at line 23 of file InttRawHit.h
Referenced by InttRawHitv1::InttRawHitv1(), and DumpInttRawHitContainer::process_Node().
virtual void InttRawHit::set_adc (uint16_t) inline virtual
Reimplemented in InttRawHitv1.
Definition at line 36 of file InttRawHit.h.
View newest version in sPHENIX GitHub at line 36 of file InttRawHit.h
Referenced by SingleInttPoolInput::FillPool().
virtual void InttRawHit::set_amplitude (uint16_t) inline virtual
Reimplemented in InttRawHitv1.
Definition at line 48 of file InttRawHit.h.
View newest version in sPHENIX GitHub at line 48 of file InttRawHit.h
Referenced by SingleInttPoolInput::FillPool().
virtual void InttRawHit::set_bco (const uint64_t) inline virtual
Reimplemented in InttRawHitv1.
Definition at line 18 of file InttRawHit.h.
View newest version in sPHENIX GitHub at line 18 of file InttRawHit.h
Referenced by SingleInttPoolInput::FillPool().
virtual void InttRawHit::set_channel_id (uint16_t) inline virtual
Reimplemented in InttRawHitv1.
Definition at line 30 of file InttRawHit.h.
View newest version in sPHENIX GitHub at line 30 of file InttRawHit.h
Referenced by SingleInttPoolInput::FillPool().
virtual void InttRawHit::set_chip_id (uint16_t) inline virtual
Reimplemented in InttRawHitv1.
Definition at line 33 of file InttRawHit.h.
View newest version in sPHENIX GitHub at line 33 of file InttRawHit.h
Referenced by SingleInttPoolInput::FillPool().
virtual void InttRawHit::set_fee (uint16_t) inline virtual
Reimplemented in InttRawHitv1.
Definition at line 27 of file InttRawHit.h.
View newest version in sPHENIX GitHub at line 27 of file InttRawHit.h
Referenced by SingleInttPoolInput::FillPool().
virtual void InttRawHit::set_FPHX_BCO (uint16_t) inline virtual
Reimplemented in InttRawHitv1.
Definition at line 39 of file InttRawHit.h.
View newest version in sPHENIX GitHub at line 39 of file InttRawHit.h
Referenced by SingleInttPoolInput::FillPool().
virtual void InttRawHit::set_full_FPHX (uint16_t) inline virtual
Reimplemented in InttRawHitv1.
Definition at line 42 of file InttRawHit.h.
View newest version in sPHENIX GitHub at line 42 of file InttRawHit.h
Referenced by SingleInttPoolInput::FillPool().
virtual void InttRawHit::set_full_ROC (uint16_t) inline virtual
Reimplemented in InttRawHitv1.
Definition at line 45 of file InttRawHit.h.
View newest version in sPHENIX GitHub at line 45 of file InttRawHit.h
Referenced by SingleInttPoolInput::FillPool().
virtual void InttRawHit::set_packetid (const int32_t) inline virtual
Reimplemented in InttRawHitv1.
Definition at line 21 of file InttRawHit.h.
View newest version in sPHENIX GitHub at line 21 of file InttRawHit.h
Referenced by SingleInttPoolInput::FillPool().
virtual void InttRawHit::set_word (uint32_t) inline virtual
Reimplemented in InttRawHitv1.
Definition at line 24 of file InttRawHit.h.
View newest version in sPHENIX GitHub at line 24 of file InttRawHit.h
Referenced by SingleInttPoolInput::FillPool().
The documentation for this class was generated from the following file:
coresoftware/blob/master/offline/framework/ffarawobjects/InttRawHit.h