Analysis Software: analysis/blob/master/Calo_Validation_Package/macros/figMaker/figmaker.C File Reference
figmaker.C File Reference
#include "sPhenixStyle.C"
Functions
void myText (Double_t x, Double_t y, Color_t color, const char *text, Double_t tsize=0.04)
TH1F * proj (TH2F *h2)
TH1F * FBratio (TH1F *h)
void figmaker ()
Function Documentation
TH1F* FBratio (TH1F * h)
Definition at line 14 of file figmaker.C.
View newest version in sPHENIX GitHub at line 14 of file figmaker.C
References b1, check_license::err(), and i.
Referenced by figmaker().
void figmaker ()
Definition at line 32 of file figmaker.C.
View newest version in sPHENIX GitHub at line 32 of file figmaker.C
References c2, physmon_vertexing::events, FBratio(), infile, myText(), proj(), utils::run, and SetsPhenixStyle().
void myText (Double_t x, Double_t y, Color_t color, const char * text, Double_t tsize = 0.04)
Definition at line 4 of file figmaker.C.
View newest version in sPHENIX GitHub at line 4 of file figmaker.C
Referenced by Compare_ntp_gtrack(), draw_G4_bjet_truth_tagging(), draw_G4_dibjet_truth_tagging(), figmaker(), plot(), and plotTimes().
TH1F * proj (TH2F * h2)
Definition at line 432 of file figmaker.C.
View newest version in sPHENIX GitHub at line 432 of file figmaker.C
References h, sum(), ambiguity_solver_full_chain::x, and y.
Referenced by __example_1.f__(), __example_2.f__(), __example_3.f__(), __example_4.f__(), __example_5.f__(), __example_6.f__(), __example_7.f__(), __example_8.f__(), EMCalLikelihood::ApplyEMCalGanging(), BOOST_AUTO_TEST_CASE(), Acts::detail::computeSymmetricKlDivergence(), figmaker(), sPHAnalysis::Get_CAL_e3x3(), FilterEventsUpsilon::GetProjectionCEMC(), FilterEvents::GetProjectionCEMC(), sPHAnalysis::GetProjectionToCalorimeter(), PHTpcCentralMembraneMatcher::getRPeaks(), hijset(), Jetscape::TrentoInitial::InitTask(), main(), SDeltaPtCutStudy::MakePlots(), FilterEventsUpsilon::MatchClusterCEMC(), FilterEvents::MatchClusterCEMC(), sPHAnalysis::MatchClusterCEMC(), Acts::detail::mergeComponents(), Acts::detail::normalizeWeights(), FilterEvents::process_event(), FilterEventsUpsilon::process_event(), Acts::detail::FixedSizeSubspace< kFullSize, kSize >::projector(), Acts::MultiComponentBoundTrackParameters::reduce(), Acts::reduceMixtureWithKLDistance(), reduceWithKLDistanceImpl(), Acts::detail::GsfActor< bethe_heitler_approx_t, traj_t >::removeLowWeightComponents(), test_surface(), TrackProjection_Checks(), and Acts::detail::weightsAreNormalized().