Analysis Software: ActsExamples::TrackParamsEstimationAlgorithm Exception Reference
ActsExamples::TrackParamsEstimationAlgorithm Exception Reference final
#include <acts/blob/sPHENIX/Examples/Algorithms/TrackFinding/include/ActsExamples/TrackFinding/TrackParamsEstimationAlgorithm.hpp>
Classes
struct Config
Public Member Functions
TrackParamsEstimationAlgorithm (Config cfg, Acts::Logging::Level lvl)
ProcessCode execute (const AlgorithmContext &ctx) const override
const Config & config () const
Const access to the config.
Public Member Functions inherited from ActsExamples::IAlgorithm
IAlgorithm (std::string name, Acts::Logging::Level level=Acts::Logging::INFO)
std::string name () const override
The algorithm name.
ProcessCode internalExecute (const AlgorithmContext &context) final
ProcessCode initialize () override
Initialize the algorithm.
ProcessCode finalize () override
Finalize the algorithm.
Private Attributes
Config m_cfg
Acts::BoundSquareMatrix m_covariance = Acts::BoundSquareMatrix::Zero()
ReadDataHandle< SimSeedContainer > m_inputSeeds {this, "InputSeeds"}
ReadDataHandle
< ProtoTrackContainer > m_inputTracks {this, "InputTracks"}
WriteDataHandle
< TrackParametersContainer > m_outputTrackParameters
WriteDataHandle< SimSeedContainer > m_outputSeeds {this, "OutputSeeds"}
WriteDataHandle
< ProtoTrackContainer > m_outputTracks {this, "OutputTracks"}
Additional Inherited Members
Protected Member Functions inherited from ActsExamples::IAlgorithm
const Acts::Logger & logger () const
Detailed Description
Estimate track parameters for track seeds.
The algorithm takes the either directly the seeds or indirectly the proto tracks and space points, and source links container as input. The proto track is basically a seed and its space points info could be retrieved from the space point container. The source links container is necessary to retrieve the geometry identifier of the module at which a space point is located. It creates two additional container to the event store, i.e. the estimated track parameters container and the proto tracks container storing only those proto tracks with track parameters estimated.
Definition at line 51 of file TrackParamsEstimationAlgorithm.hpp.
View newest version in sPHENIX GitHub at line 51 of file TrackParamsEstimationAlgorithm.hpp
Constructor & Destructor Documentation
ActsExamples::TrackParamsEstimationAlgorithm::TrackParamsEstimationAlgorithm (Config cfg, Acts::Logging::Level lvl)
Construct the track parameters making algorithm.
Parameters
cfg is the algorithm configuration
lvl is the logging level
Definition at line 35 of file TrackParamsEstimationAlgorithm.cpp.
View newest version in sPHENIX GitHub at line 35 of file TrackParamsEstimationAlgorithm.cpp
References Acts::eBoundLoc0, Acts::eBoundSize, i, ActsExamples::WriteDataHandle< T >::initialize(), ActsExamples::ReadDataHandle< T >::initialize(), ActsExamples::TrackParamsEstimationAlgorithm::Config::initialSigmas, ActsExamples::TrackParamsEstimationAlgorithm::Config::initialVarInflation, ActsExamples::TrackParamsEstimationAlgorithm::Config::inputProtoTracks, ActsExamples::TrackParamsEstimationAlgorithm::Config::inputSeeds, m_cfg, m_covariance, m_inputSeeds, m_inputTracks, m_outputSeeds, m_outputTrackParameters, m_outputTracks, ActsExamples::TrackParamsEstimationAlgorithm::Config::magneticField, ActsExamples::DataHandleBase::maybeInitialize(), ActsExamples::TrackParamsEstimationAlgorithm::Config::outputProtoTracks, ActsExamples::TrackParamsEstimationAlgorithm::Config::outputSeeds, ActsExamples::TrackParamsEstimationAlgorithm::Config::outputTrackParameters, and ActsExamples::TrackParamsEstimationAlgorithm::Config::trackingGeometry.
Member Function Documentation
const Config& ActsExamples::TrackParamsEstimationAlgorithm::config () const inline
Const access to the config.
Definition at line 97 of file TrackParamsEstimationAlgorithm.hpp.
View newest version in sPHENIX GitHub at line 97 of file TrackParamsEstimationAlgorithm.hpp
References m_cfg.
ActsExamples::ProcessCode ActsExamples::TrackParamsEstimationAlgorithm::execute (const AlgorithmContext & ctx) const override virtual
Run the track parameters making algorithm.
Parameters
ctx is the algorithm context with event information
Returns
a process code indication success or failure
Implements ActsExamples::IAlgorithm.
Definition at line 67 of file TrackParamsEstimationAlgorithm.cpp.
View newest version in sPHENIX GitHub at line 67 of file TrackParamsEstimationAlgorithm.cpp
References ACTS_ERROR, ACTS_FATAL, ACTS_VERBOSE, ACTS_WARNING, Acts::IntegrationTest::bCache, Acts::estimateTrackParamsFromSeed(), ckf::field, ActsExamples::AlgorithmContext::geoContext, Acts::Surface::getSharedPtr(), truth_tracking_gsf_refitting::inputTracks, logger(), m_cfg(), ActsExamples::AlgorithmContext::magFieldContext, testing::internal::move(), truth_tracking_gsf_refitting::outputTracks, seed, SUCCESS, and writeMapConfig::surface.
Member Data Documentation
Config ActsExamples::TrackParamsEstimationAlgorithm::m_cfg private
Definition at line 100 of file TrackParamsEstimationAlgorithm.hpp.
View newest version in sPHENIX GitHub at line 100 of file TrackParamsEstimationAlgorithm.hpp
Referenced by config(), and TrackParamsEstimationAlgorithm().
Acts::BoundSquareMatrix ActsExamples::TrackParamsEstimationAlgorithm::m_covariance = Acts::BoundSquareMatrix::Zero() private
The track parameters covariance (assumed to be the same for all estimated track parameters for the moment)
Definition at line 104 of file TrackParamsEstimationAlgorithm.hpp.
View newest version in sPHENIX GitHub at line 104 of file TrackParamsEstimationAlgorithm.hpp
Referenced by TrackParamsEstimationAlgorithm().
ReadDataHandle<SimSeedContainer> ActsExamples::TrackParamsEstimationAlgorithm::m_inputSeeds {this, "InputSeeds"} private
Definition at line 106 of file TrackParamsEstimationAlgorithm.hpp.
View newest version in sPHENIX GitHub at line 106 of file TrackParamsEstimationAlgorithm.hpp
Referenced by TrackParamsEstimationAlgorithm().
ReadDataHandle<ProtoTrackContainer> ActsExamples::TrackParamsEstimationAlgorithm::m_inputTracks {this, "InputTracks"} private
Definition at line 107 of file TrackParamsEstimationAlgorithm.hpp.
View newest version in sPHENIX GitHub at line 107 of file TrackParamsEstimationAlgorithm.hpp
Referenced by TrackParamsEstimationAlgorithm().
WriteDataHandle<SimSeedContainer> ActsExamples::TrackParamsEstimationAlgorithm::m_outputSeeds {this, "OutputSeeds"} private
Definition at line 111 of file TrackParamsEstimationAlgorithm.hpp.
View newest version in sPHENIX GitHub at line 111 of file TrackParamsEstimationAlgorithm.hpp
Referenced by TrackParamsEstimationAlgorithm().
WriteDataHandle<TrackParametersContainer> ActsExamples::TrackParamsEstimationAlgorithm::m_outputTrackParameters private
Initial value:
{
      this, "OutputTrackParameters"}
Definition at line 109 of file TrackParamsEstimationAlgorithm.hpp.
View newest version in sPHENIX GitHub at line 109 of file TrackParamsEstimationAlgorithm.hpp
Referenced by TrackParamsEstimationAlgorithm().
WriteDataHandle<ProtoTrackContainer> ActsExamples::TrackParamsEstimationAlgorithm::m_outputTracks {this, "OutputTracks"} private
Definition at line 112 of file TrackParamsEstimationAlgorithm.hpp.
View newest version in sPHENIX GitHub at line 112 of file TrackParamsEstimationAlgorithm.hpp
Referenced by TrackParamsEstimationAlgorithm().
The documentation for this exception was generated from the following files:
acts/blob/sPHENIX/Examples/Algorithms/TrackFinding/include/ActsExamples/TrackFinding/TrackParamsEstimationAlgorithm.hpp
acts/blob/sPHENIX/Examples/Algorithms/TrackFinding/src/TrackParamsEstimationAlgorithm.cpp