Analysis Software: PHG4SpacalDetector Class Reference
PHG4SpacalDetector Class Reference
#include <coresoftware/blob/master/simulation/g4simulation/g4detectors/PHG4SpacalDetector.h>
Public Types
enum {
FIBER_CORE = 1, FIBER_CLADING = 0, ABSORBER = -1, SUPPORT = -2,
INACTIVE = -100
}
typedef PHG4CylinderGeom_Spacalv1 SpacalGeom_t
Public Member Functions
PHG4SpacalDetector (PHG4Subsystem *subsys, PHCompositeNode *Node, const std::string &dnam, PHParameters *parameters, const int layer=0, bool init_geom=true)
~PHG4SpacalDetector (void) override
void ConstructMe (G4LogicalVolume *world) override
virtual std::pair
< G4LogicalVolume
*, G4Transform3D > Construct_AzimuthalSeg ()
virtual G4LogicalVolume * Construct_Fiber (const G4double length, const std::string &id)
void SetActive (const int i=1)
void SetAbsorberActive (const int i=1)
void SetDetectorType (const std::string &typ)
int IsInCylinderActive (const G4VPhysicalVolume *)
void SuperDetector (const std::string &name)
const std::string SuperDetector () const
int get_Layer () const
void Print (const std::string &what="ALL") const override
const SpacalGeom_t * get_geom () const
virtual PHG4CylinderGeom * clone_geom () const
PHG4SpacalDisplayAction * GetDisplayAction ()
void CosmicSetup (const int i)
int CosmicSetup ()
Public Member Functions inherited from PHG4Detector
PHG4Detector ()=delete
constructor
PHG4Detector (PHG4Subsystem *subsys, PHCompositeNode *Node, const std::string &nam)
virtual ~PHG4Detector (void)
destructor
virtual void Construct (G4LogicalVolume *world) final
construct method
virtual void PostConstruction ()
Optional PostConstruction call after all geometry is constructed.
virtual void Verbosity (const int v)
virtual int Verbosity () const
virtual G4UserSteppingAction * GetSteppingAction ()
virtual std::string GetName () const
virtual void OverlapCheck (const bool chk)
virtual bool OverlapCheck () const
virtual int DisplayVolume (G4VSolid *volume, G4LogicalVolume *logvol, G4RotationMatrix *rotm=nullptr)
virtual int DisplayVolume (G4LogicalVolume *checksolid, G4LogicalVolume *logvol, G4RotationMatrix *rotm=nullptr)
virtual PHCompositeNode * topNode ()
virtual PHG4Subsystem * GetMySubsystem ()
Protected Member Functions
void AddTowerGeometryNode ()
void AddCellGeometryNode ()
Protected Attributes
std::map< const
G4VPhysicalVolume *, int > fiber_core_vol
std::map< const
G4VPhysicalVolume *, int > fiber_vol
map for G4VPhysicalVolume -> fiber ID
std::map< const
G4VPhysicalVolume *, int > calo_vol
map for G4VPhysicalVolume -> Sector ID
std::map< const
G4VPhysicalVolume *, int > block_vol
map for G4VPhysicalVolume -> towers ID
int active = 0
int absorberactive = 0
int layer = -9999
int m_CosmicSetupFlag = 0
int m_CellBinning = PHG4CellDefs::undefined
int m_NumLayers = -1
int m_NumPhiBins = -1
int m_NumEtaBins = -1
double m_Emin = 1e-6
double m_EtaMin = NAN
double m_PhiMin = NAN
double m_EtaStep = NAN
double m_PhiStep = NAN
std::string detector_type
std::string superdetector
G4UserLimits * fiber_core_step_limits = nullptr
PHG4GDMLConfig * gdml_config = nullptr
registry for volumes that should not be exported, i.e. fibers
SpacalGeom_t * _geom = nullptr
RawTowerGeomContainer * m_RawTowerGeomContainer = nullptr
std::string m_TowerGeomNodeName
Private Attributes
PHG4SpacalDisplayAction * m_DisplayAction = nullptr
Additional Inherited Members
Static Public Member Functions inherited from PHG4Detector
static G4Material * GetDetectorMaterial (const std::string &name, const bool quit=true)
static G4Element * GetDetectorElement (const std::string &name, const bool quit=true)
Detailed Description
Definition at line 38 of file PHG4SpacalDetector.h.
View newest version in sPHENIX GitHub at line 38 of file PHG4SpacalDetector.h
Member Typedef Documentation
typedef PHG4CylinderGeom_Spacalv1 PHG4SpacalDetector::SpacalGeom_t
Definition at line 41 of file PHG4SpacalDetector.h.
View newest version in sPHENIX GitHub at line 41 of file PHG4SpacalDetector.h
Member Enumeration Documentation
anonymous enum
Enumerator:
FIBER_CORE
FIBER_CLADING
ABSORBER
SUPPORT
INACTIVE
Definition at line 108 of file PHG4SpacalDetector.h.
View newest version in sPHENIX GitHub at line 108 of file PHG4SpacalDetector.h
Constructor & Destructor Documentation
PHG4SpacalDetector::PHG4SpacalDetector (PHG4Subsystem * subsys, PHCompositeNode * Node, const std::string & dnam, PHParameters * parameters, const int layer = 0, bool init_geom = true)
Definition at line 65 of file PHG4SpacalDetector.cc.
View newest version in sPHENIX GitHub at line 65 of file PHG4SpacalDetector.cc
References _geom, assert, gdml_config, PHG4GDMLUtility::GetOrMakeConfigNode(), and PHG4CylinderGeom_Spacalv1::ImportParameters().
PHG4SpacalDetector::~PHG4SpacalDetector (void) override
Definition at line 94 of file PHG4SpacalDetector.cc.
View newest version in sPHENIX GitHub at line 94 of file PHG4SpacalDetector.cc
References _geom, and fiber_core_step_limits.
Member Function Documentation
void PHG4SpacalDetector::AddCellGeometryNode () protected
Definition at line 736 of file PHG4SpacalDetector.cc.
View newest version in sPHENIX GitHub at line 736 of file PHG4SpacalDetector.cc
References PHG4CylinderCellGeomContainer::AddLayerCellGeom(), PHCompositeNode::addNode(), assert, PHG4CylinderGeom_Spacalv3::geom_tower::centralZ, dz, KF_timing::etabin, PHNodeIterator::findFirst(), PHG4CylinderGeom_Spacalv2::get_azimuthal_n_sec(), PHG4CylinderGeomv1::get_layer(), PHG4CylinderGeom_Spacalv3::get_max_phi_bin_in_sec(), PHG4CylinderGeom_Spacalv3::get_n_subtower_eta(), PHG4CylinderGeom_Spacalv3::get_n_subtower_phi(), PHG4CylinderGeomv1::get_radius(), PHG4CylinderGeom_Spacalv1::get_sector_map(), PHG4CylinderGeom_Spacalv3::get_sector_tower_map(), PHG4CylinderGeomv1::get_thickness(), PHG4CylinderGeom_Spacalv3::get_tower_radial_position(), PHG4CylinderGeom_Spacalv3::get_tower_z_phi_ID(), PHG4CylinderGeomContainer::GetFirstLayerGeom(), PHG4CylinderGeomContainer::identify(), PHG4CylinderGeom_Spacalv3::identify(), PHG4CylinderGeom_Spacalv3::geom_tower::NSubtowerY, PHG4CylinderGeom_Spacalv3::geom_tower::pDy1, PHG4CylinderGeom_Spacalv3::geom_tower::pDy2, myAnalysis::phi_min, PHWHERE, PHCompositeNode::print(), PHG4CylinderGeom_Spacalv3::geom_tower::pRotationAngleX, PHG4CylinderCellGeom::set_binning(), PHG4CylinderCellGeom::set_etabins(), PHG4CylinderCellGeom_Spacalv1::set_etabounds(), PHG4CylinderCellGeom::set_etamin(), PHG4CylinderCellGeom::set_etastep(), PHG4CylinderCellGeom::set_layer(), PHG4CylinderCellGeom::set_phibins(), PHG4CylinderCellGeom::set_phimin(), PHG4CylinderCellGeom::set_phistep(), PHG4CylinderCellGeom::set_radius(), PHG4CylinderCellGeom::set_thickness(), PHG4CylinderCellGeom_Spacalv1::set_tower_z_ID_eta_bin_map(), PHG4CylinderCellGeom_Spacalv1::set_zbounds(), PHG4CellDefs::spacalbinning, PHG4CylinderGeom_Spacalv3::subtower_consistency_check(), superdetector, PHG4Detector::topNode(), PHG4Detector::Verbosity(), and physmon_track_finding_ttbar::z.
Referenced by PHG4FullProjTiltedSpacalDetector::ConstructMe().
void PHG4SpacalDetector::AddTowerGeometryNode () protected
Definition at line 396 of file PHG4SpacalDetector.cc.
View newest version in sPHENIX GitHub at line 396 of file PHG4SpacalDetector.cc
References RawTowerGeomContainer::add_tower_geometry(), PHCompositeNode::addNode(), RawTowerDefs::convert_name_to_caloid(), Acts::UnitConstants::e, RawTowerDefs::encode_towerid(), PHG4CellDefs::etaphibinning, PHG4CellDefs::etaslatbinning, PHNodeIterator::findFirst(), PHG4CylinderCellGeomContainer::get_begin_end(), PHG4CylinderCellGeom::get_binning(), RawTowerGeom::get_center_x(), PHG4CylinderCellGeom::get_etabins(), RawTowerGeomContainer::get_etabins(), PHG4CylinderCellGeom::get_etabounds(), RawTowerGeomContainer::get_etacenter(), PHG4CylinderCellGeom::get_etamin(), PHG4CylinderCellGeom::get_etastep(), PHG4CylinderCellGeom::get_layer(), PHG4CylinderCellGeomContainer::get_NLayers(), PHG4CylinderCellGeom::get_phibins(), RawTowerGeomContainer::get_phibins(), PHG4CylinderCellGeom::get_phibounds(), RawTowerGeomContainer::get_phicenter(), PHG4CylinderCellGeom::get_phimin(), PHG4CylinderCellGeom::get_phistep(), PHG4CylinderCellGeom::get_radius(), PHG4Utils::get_theta(), PHG4CylinderCellGeom::get_thickness(), RawTowerGeomContainer::get_tower_geometry(), PHG4CylinderCellGeom::get_zbins(), PHG4CylinderCellGeom::get_zbounds(), PHG4CylinderCellGeom::get_zcenter(), PHG4Detector::GetName(), configureMap::ibin, PHG4CylinderCellGeom::identify(), RawTowerGeomContainer::identify(), G4CEMCALBEDO::inner_radius, m_CellBinning, m_EtaMin, m_EtaStep, m_NumEtaBins, m_NumLayers, m_NumPhiBins, m_PhiMin, m_PhiStep, m_RawTowerGeomContainer, m_TowerGeomNodeName, PHWHERE, physmon_track_finding_ttbar::r, RawTowerGeomContainer::set_etabins(), RawTowerGeomContainer::set_etabounds(), RawTowerGeomContainer::set_phibins(), RawTowerGeomContainer::set_phibounds(), RawTowerGeomContainer::set_radius(), RawTowerGeomContainer::set_thickness(), PHG4CellDefs::sizebinning, PHG4CellDefs::spacalbinning, superdetector, tg, thickness, PHG4Detector::topNode(), PHG4Detector::Verbosity(), ambiguity_solver_full_chain::x, y, and physmon_track_finding_ttbar::z.
Referenced by PHG4FullProjTiltedSpacalDetector::ConstructMe().
virtual PHG4CylinderGeom* PHG4SpacalDetector::clone_geom () const inline virtual
Reimplemented in PHG4FullProjTiltedSpacalDetector, and PHG4FullProjSpacalDetector.
Definition at line 103 of file PHG4SpacalDetector.h.
View newest version in sPHENIX GitHub at line 103 of file PHG4SpacalDetector.h
References _geom.
Referenced by ConstructMe().
std::pair< G4LogicalVolume *, G4Transform3D > PHG4SpacalDetector::Construct_AzimuthalSeg () virtual
Reimplemented in PHG4FullProjSpacalDetector, and PHG4FullProjTiltedSpacalDetector.
Definition at line 286 of file PHG4SpacalDetector.cc.
View newest version in sPHENIX GitHub at line 286 of file PHG4SpacalDetector.cc
References _geom, PHG4SpacalDisplayAction::AddVolume(), assert, Acts::UnitConstants::cm, Construct_Fiber(), PHG4GDMLConfig::exclude_physical_vol(), fiber_vol, gdml_config, PHG4CylinderGeom_Spacalv1::get_absorber_mat(), PHG4CylinderGeom_Spacalv1::get_azimuthal_distance(), PHG4CylinderGeom_Spacalv1::get_azimuthal_n_sec(), PHG4CylinderGeom_Spacalv1::get_fiber_distance(), PHG4CylinderGeom_Spacalv1::get_fiber_outer_r(), PHG4CylinderGeom_Spacalv1::get_half_radius(), PHG4CylinderGeom_Spacalv1::get_length(), PHG4CylinderGeom_Spacalv1::get_max_radius(), PHG4CylinderGeomv1::get_radius(), PHG4CylinderGeomv1::get_thickness(), PHG4CylinderGeom_Spacalv1::get_z_distance(), PHG4CylinderGeom::get_zmax(), PHG4CylinderGeomv1::get_zmin(), PHG4CylinderGeom_Spacalv1::get_zpos(), PHG4Detector::GetDetectorMaterial(), GetDisplayAction(), PHG4Detector::GetName(), PHG4CylinderGeom_Spacalv1::is_virualize_fiber(), perf_headwind::name, PHG4Detector::OverlapCheck(), PHG4CylinderGeomv2::set_nscint(), twopi, PHG4Detector::Verbosity(), and physmon_track_finding_ttbar::z.
Referenced by ConstructMe().
G4LogicalVolume * PHG4SpacalDetector::Construct_Fiber (const G4double length, const std::string & id) virtual
Definition at line 348 of file PHG4SpacalDetector.cc.
View newest version in sPHENIX GitHub at line 348 of file PHG4SpacalDetector.cc
References _geom, PHG4SpacalDisplayAction::AddVolume(), assert, Acts::UnitConstants::cm, fiber_core_step_limits, fiber_core_vol, PHG4CylinderGeom_Spacalv1::get_fiber_clading_mat(), PHG4CylinderGeom_Spacalv1::get_fiber_core_diameter(), PHG4CylinderGeom_Spacalv1::get_fiber_core_mat(), PHG4CylinderGeom_Spacalv1::get_fiber_outer_r(), PHG4Detector::GetDetectorMaterial(), GetDisplayAction(), PHG4Detector::GetName(), PHG4Detector::OverlapCheck(), twopi, and PHG4Detector::Verbosity().
Referenced by Construct_AzimuthalSeg(), PHG4FullProjSpacalDetector::Construct_Fibers(), PHG4FullProjTiltedSpacalDetector::Construct_Fibers(), PHG4FullProjSpacalDetector::Construct_Fibers_SameLengthFiberPerTower(), and PHG4FullProjTiltedSpacalDetector::Construct_Fibers_SameLengthFiberPerTower().
void PHG4SpacalDetector::ConstructMe (G4LogicalVolume * world) override virtual
Implements PHG4Detector.
Definition at line 132 of file PHG4SpacalDetector.cc.
View newest version in sPHENIX GitHub at line 132 of file PHG4SpacalDetector.cc
References _geom, absorberactive, active, PHG4CylinderGeomContainer::AddLayerGeom(), PHCompositeNode::addNode(), PHG4SpacalDisplayAction::AddVolume(), assert, calo_vol, clone_geom(), Acts::UnitConstants::cm, Construct_AzimuthalSeg(), detector_type, PHG4GDMLConfig::exclude_physical_vol(), fiber_core_step_limits, PHNodeIterator::findFirst(), gdml_config, PHG4CylinderGeom_Spacalv1::get_construction_verbose(), PHG4CylinderGeom_Spacalv1::get_fiber_core_step_size(), PHG4CylinderGeom_Spacalv1::get_length(), PHG4CylinderGeom_Spacalv1::get_max_radius(), PHG4CylinderGeomv2::get_nscint(), PHG4CylinderGeomv1::get_radius(), PHG4CylinderGeom_Spacalv1::get_sector_map(), PHG4CylinderGeom_Spacalv1::get_xpos(), PHG4CylinderGeom_Spacalv1::get_ypos(), PHG4CylinderGeomv1::get_zmax(), PHG4CylinderGeomv1::get_zmin(), PHG4CylinderGeom_Spacalv1::get_zpos(), PHG4Detector::GetDetectorMaterial(), GetDisplayAction(), PHG4Detector::GetName(), PHG4CylinderGeom_Spacalv1::init_default_sector_map(), recoConsts::instance(), layer, m_CosmicSetupFlag, perf_headwind::name, PHG4Detector::OverlapCheck(), PHG4CylinderGeom_Spacalv1::Print(), Print(), PHG4CylinderGeomv2::set_nscint(), superdetector, PHG4Detector::topNode(), twopi, and PHG4Detector::Verbosity().
Referenced by PHG4FullProjTiltedSpacalDetector::ConstructMe(), and PHG4FullProjSpacalDetector::ConstructMe().
void PHG4SpacalDetector::CosmicSetup (const int i) inline
Definition at line 119 of file PHG4SpacalDetector.h.
View newest version in sPHENIX GitHub at line 119 of file PHG4SpacalDetector.h
References i, and m_CosmicSetupFlag.
Referenced by PHG4SpacalSubsystem::InitRunSubsystem().
int PHG4SpacalDetector::CosmicSetup () inline
Definition at line 120 of file PHG4SpacalDetector.h.
View newest version in sPHENIX GitHub at line 120 of file PHG4SpacalDetector.h
References m_CosmicSetupFlag.
const SpacalGeom_t* PHG4SpacalDetector::get_geom () const inline
Definition at line 98 of file PHG4SpacalDetector.h.
View newest version in sPHENIX GitHub at line 98 of file PHG4SpacalDetector.h
References _geom.
Referenced by PHG4SpacalSteppingAction::get_zmax(), PHG4SpacalSteppingAction::get_zmin(), PHG4SpacalSubsystem::InitRunSubsystem(), PHG4SpacalSteppingAction::NoHitSteppingAction(), and PHG4SpacalSteppingAction::UserSteppingAction().
int PHG4SpacalDetector::get_Layer () const inline
Definition at line 89 of file PHG4SpacalDetector.h.
View newest version in sPHENIX GitHub at line 89 of file PHG4SpacalDetector.h
References layer.
Referenced by PHG4SpacalSteppingAction::UserSteppingAction().
PHG4SpacalDisplayAction* PHG4SpacalDetector::GetDisplayAction () inline
Definition at line 117 of file PHG4SpacalDetector.h.
View newest version in sPHENIX GitHub at line 117 of file PHG4SpacalDetector.h
References m_DisplayAction.
Referenced by PHG4FullProjTiltedSpacalDetector::Construct_AzimuthalSeg(), PHG4FullProjSpacalDetector::Construct_AzimuthalSeg(), Construct_AzimuthalSeg(), Construct_Fiber(), PHG4FullProjTiltedSpacalDetector::Construct_LightGuide(), PHG4FullProjTiltedSpacalDetector::Construct_Tower(), PHG4FullProjSpacalDetector::Construct_Tower(), and ConstructMe().
int PHG4SpacalDetector::IsInCylinderActive (const G4VPhysicalVolume * volume)
Definition at line 103 of file PHG4SpacalDetector.cc.
View newest version in sPHENIX GitHub at line 103 of file PHG4SpacalDetector.cc
References ABSORBER, absorberactive, active, block_vol, calo_vol, FIBER_CLADING, FIBER_CORE, fiber_core_vol, fiber_vol, INACTIVE, and SUPPORT.
Referenced by PHG4SpacalSteppingAction::NoHitSteppingAction(), and PHG4SpacalSteppingAction::UserSteppingAction().
void PHG4SpacalDetector::Print (const std::string & what = "ALL") const override virtual
Reimplemented from PHG4Detector.
Definition at line 388 of file PHG4SpacalDetector.cc.
View newest version in sPHENIX GitHub at line 388 of file PHG4SpacalDetector.cc
References _geom, PHG4Detector::GetName(), and PHG4CylinderGeom_Spacalv1::Print().
Referenced by ConstructMe(), and PHG4SpacalSubsystem::Print().
void PHG4SpacalDetector::SetAbsorberActive (const int i = 1) inline
Definition at line 64 of file PHG4SpacalDetector.h.
View newest version in sPHENIX GitHub at line 64 of file PHG4SpacalDetector.h
References absorberactive, and i.
Referenced by PHG4SpacalSubsystem::InitRunSubsystem().
void PHG4SpacalDetector::SetActive (const int i = 1) inline
Definition at line 58 of file PHG4SpacalDetector.h.
View newest version in sPHENIX GitHub at line 58 of file PHG4SpacalDetector.h
References active, and i.
Referenced by PHG4SpacalSubsystem::InitRunSubsystem().
void PHG4SpacalDetector::SetDetectorType (const std::string & typ) inline
Definition at line 70 of file PHG4SpacalDetector.h.
View newest version in sPHENIX GitHub at line 70 of file PHG4SpacalDetector.h
References detector_type.
void PHG4SpacalDetector::SuperDetector (const std::string & name) inline
Definition at line 78 of file PHG4SpacalDetector.h.
View newest version in sPHENIX GitHub at line 78 of file PHG4SpacalDetector.h
References perf_headwind::name, and superdetector.
Referenced by PHG4SpacalSubsystem::InitRunSubsystem(), PHG4SpacalSteppingAction::InitWithNode(), and PHG4SpacalSteppingAction::SetUpGeomNode().
const std::string PHG4SpacalDetector::SuperDetector () const inline
Definition at line 84 of file PHG4SpacalDetector.h.
View newest version in sPHENIX GitHub at line 84 of file PHG4SpacalDetector.h
References superdetector.
Member Data Documentation
SpacalGeom_t* PHG4SpacalDetector::_geom = nullptr protected
Definition at line 163 of file PHG4SpacalDetector.h.
View newest version in sPHENIX GitHub at line 163 of file PHG4SpacalDetector.h
Referenced by clone_geom(), Construct_AzimuthalSeg(), Construct_Fiber(), PHG4FullProjTiltedSpacalDetector::Construct_LightGuide(), ConstructMe(), get_geom(), PHG4FullProjSpacalDetector::get_geom_v3(), PHG4FullProjTiltedSpacalDetector::get_geom_v3(), PHG4FullProjSpacalDetector::PHG4FullProjSpacalDetector(), PHG4FullProjTiltedSpacalDetector::PHG4FullProjTiltedSpacalDetector(), PHG4SpacalDetector(), Print(), and ~PHG4SpacalDetector().
int PHG4SpacalDetector::absorberactive = 0 protected
Definition at line 140 of file PHG4SpacalDetector.h.
View newest version in sPHENIX GitHub at line 140 of file PHG4SpacalDetector.h
Referenced by ConstructMe(), IsInCylinderActive(), and SetAbsorberActive().
int PHG4SpacalDetector::active = 0 protected
Definition at line 139 of file PHG4SpacalDetector.h.
View newest version in sPHENIX GitHub at line 139 of file PHG4SpacalDetector.h
Referenced by ConstructMe(), IsInCylinderActive(), and SetActive().
std::map<const G4VPhysicalVolume*, int> PHG4SpacalDetector::block_vol protected
map for G4VPhysicalVolume -> towers ID
Definition at line 137 of file PHG4SpacalDetector.h.
View newest version in sPHENIX GitHub at line 137 of file PHG4SpacalDetector.h
Referenced by PHG4FullProjTiltedSpacalDetector::Construct_AzimuthalSeg(), PHG4FullProjSpacalDetector::Construct_AzimuthalSeg(), and IsInCylinderActive().
std::map<const G4VPhysicalVolume*, int> PHG4SpacalDetector::calo_vol protected
map for G4VPhysicalVolume -> Sector ID
Definition at line 134 of file PHG4SpacalDetector.h.
View newest version in sPHENIX GitHub at line 134 of file PHG4SpacalDetector.h
Referenced by PHG4FullProjTiltedSpacalDetector::Construct_AzimuthalSeg(), PHG4FullProjSpacalDetector::Construct_AzimuthalSeg(), ConstructMe(), and IsInCylinderActive().
std::string PHG4SpacalDetector::detector_type protected
Definition at line 152 of file PHG4SpacalDetector.h.
View newest version in sPHENIX GitHub at line 152 of file PHG4SpacalDetector.h
Referenced by ConstructMe(), and SetDetectorType().
G4UserLimits* PHG4SpacalDetector::fiber_core_step_limits = nullptr protected
Definition at line 157 of file PHG4SpacalDetector.h.
View newest version in sPHENIX GitHub at line 157 of file PHG4SpacalDetector.h
Referenced by Construct_Fiber(), ConstructMe(), and ~PHG4SpacalDetector().
std::map<const G4VPhysicalVolume*, int> PHG4SpacalDetector::fiber_core_vol protected
Definition at line 128 of file PHG4SpacalDetector.h.
View newest version in sPHENIX GitHub at line 128 of file PHG4SpacalDetector.h
Referenced by Construct_Fiber(), and IsInCylinderActive().
std::map<const G4VPhysicalVolume*, int> PHG4SpacalDetector::fiber_vol protected
map for G4VPhysicalVolume -> fiber ID
Definition at line 131 of file PHG4SpacalDetector.h.
View newest version in sPHENIX GitHub at line 131 of file PHG4SpacalDetector.h
Referenced by Construct_AzimuthalSeg(), PHG4FullProjSpacalDetector::Construct_Fibers(), PHG4FullProjTiltedSpacalDetector::Construct_Fibers(), PHG4FullProjSpacalDetector::Construct_Fibers_SameLengthFiberPerTower(), PHG4FullProjTiltedSpacalDetector::Construct_Fibers_SameLengthFiberPerTower(), and IsInCylinderActive().
PHG4GDMLConfig* PHG4SpacalDetector::gdml_config = nullptr protected
registry for volumes that should not be exported, i.e. fibers
Definition at line 160 of file PHG4SpacalDetector.h.
View newest version in sPHENIX GitHub at line 160 of file PHG4SpacalDetector.h
Referenced by PHG4FullProjTiltedSpacalDetector::Construct_AzimuthalSeg(), PHG4FullProjSpacalDetector::Construct_AzimuthalSeg(), Construct_AzimuthalSeg(), PHG4FullProjSpacalDetector::Construct_Fibers(), PHG4FullProjTiltedSpacalDetector::Construct_Fibers(), PHG4FullProjSpacalDetector::Construct_Fibers_SameLengthFiberPerTower(), PHG4FullProjTiltedSpacalDetector::Construct_Fibers_SameLengthFiberPerTower(), ConstructMe(), and PHG4SpacalDetector().
int PHG4SpacalDetector::layer = -9999 protected
Definition at line 141 of file PHG4SpacalDetector.h.
View newest version in sPHENIX GitHub at line 141 of file PHG4SpacalDetector.h
Referenced by ConstructMe(), and get_Layer().
int PHG4SpacalDetector::m_CellBinning = PHG4CellDefs::undefined protected
Definition at line 143 of file PHG4SpacalDetector.h.
View newest version in sPHENIX GitHub at line 143 of file PHG4SpacalDetector.h
Referenced by AddTowerGeometryNode().
int PHG4SpacalDetector::m_CosmicSetupFlag = 0 protected
Definition at line 142 of file PHG4SpacalDetector.h.
View newest version in sPHENIX GitHub at line 142 of file PHG4SpacalDetector.h
Referenced by ConstructMe(), and CosmicSetup().
PHG4SpacalDisplayAction* PHG4SpacalDetector::m_DisplayAction = nullptr private
Definition at line 123 of file PHG4SpacalDetector.h.
View newest version in sPHENIX GitHub at line 123 of file PHG4SpacalDetector.h
Referenced by GetDisplayAction().
double PHG4SpacalDetector::m_Emin = 1e-6 protected
Definition at line 147 of file PHG4SpacalDetector.h.
View newest version in sPHENIX GitHub at line 147 of file PHG4SpacalDetector.h
double PHG4SpacalDetector::m_EtaMin = NAN protected
Definition at line 148 of file PHG4SpacalDetector.h.
View newest version in sPHENIX GitHub at line 148 of file PHG4SpacalDetector.h
Referenced by AddTowerGeometryNode().
double PHG4SpacalDetector::m_EtaStep = NAN protected
Definition at line 150 of file PHG4SpacalDetector.h.
View newest version in sPHENIX GitHub at line 150 of file PHG4SpacalDetector.h
Referenced by AddTowerGeometryNode().
int PHG4SpacalDetector::m_NumEtaBins = -1 protected
Definition at line 146 of file PHG4SpacalDetector.h.
View newest version in sPHENIX GitHub at line 146 of file PHG4SpacalDetector.h
Referenced by AddTowerGeometryNode().
int PHG4SpacalDetector::m_NumLayers = -1 protected
Definition at line 144 of file PHG4SpacalDetector.h.
View newest version in sPHENIX GitHub at line 144 of file PHG4SpacalDetector.h
Referenced by AddTowerGeometryNode().
int PHG4SpacalDetector::m_NumPhiBins = -1 protected
Definition at line 145 of file PHG4SpacalDetector.h.
View newest version in sPHENIX GitHub at line 145 of file PHG4SpacalDetector.h
Referenced by AddTowerGeometryNode().
double PHG4SpacalDetector::m_PhiMin = NAN protected
Definition at line 149 of file PHG4SpacalDetector.h.
View newest version in sPHENIX GitHub at line 149 of file PHG4SpacalDetector.h
Referenced by AddTowerGeometryNode().
double PHG4SpacalDetector::m_PhiStep = NAN protected
Definition at line 151 of file PHG4SpacalDetector.h.
View newest version in sPHENIX GitHub at line 151 of file PHG4SpacalDetector.h
Referenced by AddTowerGeometryNode().
RawTowerGeomContainer* PHG4SpacalDetector::m_RawTowerGeomContainer = nullptr protected
Definition at line 165 of file PHG4SpacalDetector.h.
View newest version in sPHENIX GitHub at line 165 of file PHG4SpacalDetector.h
Referenced by AddTowerGeometryNode().
std::string PHG4SpacalDetector::m_TowerGeomNodeName protected
Definition at line 166 of file PHG4SpacalDetector.h.
View newest version in sPHENIX GitHub at line 166 of file PHG4SpacalDetector.h
Referenced by AddTowerGeometryNode().
std::string PHG4SpacalDetector::superdetector protected
Definition at line 153 of file PHG4SpacalDetector.h.
View newest version in sPHENIX GitHub at line 153 of file PHG4SpacalDetector.h
Referenced by AddCellGeometryNode(), AddTowerGeometryNode(), ConstructMe(), and SuperDetector().
The documentation for this class was generated from the following files:
coresoftware/blob/master/simulation/g4simulation/g4detectors/PHG4SpacalDetector.h
coresoftware/blob/master/simulation/g4simulation/g4detectors/PHG4SpacalDetector.cc