Analysis Software: MyMon Class Reference
MyMon Class Reference
#include <OnlMon/blob/main/subsystems/example/MyMon.h>
Public Member Functions
MyMon (const std::string &name="MYMON")
virtual ~MyMon ()
int process_event (Event *evt)
int Init ()
int BeginRun (const int runno)
int Reset ()
Public Member Functions inherited from OnlMon
OnlMon (const std::string &name="NONE")
~OnlMon () override
virtual int process_event_common (Event *evt)
virtual int InitCommon (OnlMonServer *se)
virtual void identify (std::ostream &out=std::cout) const
virtual int BeginRunCommon (const int runno, OnlMonServer *se)
virtual int EndRun (const int)
virtual void SetStatus (const int newstatus)
virtual int ResetEvent ()
virtual void SetMonitorServerId (unsigned int i)
virtual unsigned int MonitorServerId () const
Public Member Functions inherited from OnlMonBase
OnlMonBase (const std::string &name="NONE")
virtual ~OnlMonBase ()
const std::string Name () const
void Name (const std::string &name)
virtual void Verbosity (const int i)
virtual int Verbosity () const
Protected Member Functions
int DBVarInit ()
Protected Attributes
int evtcnt = 0
int idummy = 0
OnlMonDB * dbvars = nullptr
TH1 * myhist1 = nullptr
TH2 * myhist2 = nullptr
Protected Attributes inherited from OnlMon
int status
unsigned int m_MonitorServerId = 0
TH1 * m_LocalFrameWorkVars = nullptr
Protected Attributes inherited from OnlMonBase
std::string ThisName
int verbosity = 0
Additional Inherited Members
Public Types inherited from OnlMon
enum { ACTIVE = -1, OK = 0, WARNING = 1, ERROR = 2 }
Detailed Description
Definition at line 11 of file MyMon.h.
View newest version in sPHENIX GitHub at line 11 of file MyMon.h
Constructor & Destructor Documentation
MyMon::MyMon (const std::string & name = "MYMON")
Definition at line 30 of file MyMon.cc.
View newest version in sPHENIX GitHub at line 30 of file MyMon.cc
MyMon::~MyMon () virtual
Definition at line 38 of file MyMon.cc.
View newest version in sPHENIX GitHub at line 38 of file MyMon.cc
References dbvars.
Member Function Documentation
int MyMon::BeginRun (const int runno) virtual
Reimplemented from OnlMon.
Definition at line 63 of file MyMon.cc.
View newest version in sPHENIX GitHub at line 63 of file MyMon.cc
int MyMon::DBVarInit () protected
Definition at line 106 of file MyMon.cc.
View newest version in sPHENIX GitHub at line 106 of file MyMon.cc
References OnlMonDB::DBInit(), dbvars, OnlMonDB::Print(), OnlMonDB::registerVar(), and OnlMonBase::verbosity.
Referenced by Init().
int MyMon::Init () virtual
Reimplemented from OnlMon.
Definition at line 45 of file MyMon.cc.
View newest version in sPHENIX GitHub at line 45 of file MyMon.cc
References DBVarInit(), dbvars, OnlMonServer::instance(), myhist1, myhist2, printf(), OnlMonServer::registerHisto(), Reset(), and OnlMonBase::ThisName.
int MyMon::process_event (Event * evt) virtual
Reimplemented from OnlMon.
Definition at line 70 of file MyMon.cc.
View newest version in sPHENIX GitHub at line 70 of file MyMon.cc
References OnlMonServer::CurrentTicks(), OnlMonDB::DBcommit(), dbvars, evtcnt, FILLMESSAGE, idummy, OnlMonServer::instance(), TauVsDIS_MachineLearning_Differentiation::msg, MSG_SEV_INFORMATIONAL, MSG_SOURCE_UNSPECIFIED, myhist1, myhist2, OnlMonServer::send_message(), and OnlMonDB::SetVar().
int MyMon::Reset () virtual
Reimplemented from OnlMon.
Definition at line 98 of file MyMon.cc.
View newest version in sPHENIX GitHub at line 98 of file MyMon.cc
References evtcnt, and idummy.
Referenced by Init().
Member Data Documentation
OnlMonDB* MyMon::dbvars = nullptr protected
Definition at line 26 of file MyMon.h.
View newest version in sPHENIX GitHub at line 26 of file MyMon.h
Referenced by DBVarInit(), Init(), process_event(), and ~MyMon().
int MyMon::evtcnt = 0 protected
Definition at line 24 of file MyMon.h.
View newest version in sPHENIX GitHub at line 24 of file MyMon.h
Referenced by process_event(), and Reset().
int MyMon::idummy = 0 protected
Definition at line 25 of file MyMon.h.
View newest version in sPHENIX GitHub at line 25 of file MyMon.h
Referenced by process_event(), and Reset().
TH1* MyMon::myhist1 = nullptr protected
Definition at line 27 of file MyMon.h.
View newest version in sPHENIX GitHub at line 27 of file MyMon.h
Referenced by Init(), and process_event().
TH2* MyMon::myhist2 = nullptr protected
Definition at line 28 of file MyMon.h.
View newest version in sPHENIX GitHub at line 28 of file MyMon.h
Referenced by Init(), and process_event().
The documentation for this class was generated from the following files:
OnlMon/blob/main/subsystems/example/MyMon.h
OnlMon/blob/main/subsystems/example/MyMon.cc