Analysis Software: RawTower_Prototype2 Class Reference
RawTower_Prototype2 Class Reference
#include <prototype/blob/master/offline/packages/Prototype2/RawTower_Prototype2.h>
Public Types
enum { NSAMPLES = PROTOTYPE2_FEM::NSAMPLES }
typedef float signal_type
Public Types inherited from RawTower
enum PROPERTY { prop_scint_gammas = 1, prop_cerenkov_gammas = 2, prop_MAX_NUMBER = UCHAR_MAX }
typedef unsigned long long CellKeyType
key type for cell map which should be consistent with CellKeyType
typedef std::map< CellKeyType,
float > CellMap
typedef CellMap::iterator CellIterator
typedef CellMap::const_iterator CellConstIterator
typedef std::pair
< CellIterator, CellIterator > CellRange
typedef std::pair
< CellConstIterator,
CellConstIterator > CellConstRange
typedef std::map< int, float > ShowerMap
typedef ShowerMap::iterator ShowerIterator
typedef ShowerMap::const_iterator ShowerConstIterator
typedef std::pair
< ShowerIterator,
ShowerIterator > ShowerRange
typedef std::pair
< ShowerConstIterator,
ShowerConstIterator > ShowerConstRange
Public Member Functions
RawTower_Prototype2 ()
RawTower_Prototype2 (const RawTower &tower)
RawTower_Prototype2 (RawTowerDefs::keytype id)
RawTower_Prototype2 (const unsigned int icol, const unsigned int irow)
RawTower_Prototype2 (const RawTowerDefs::CalorimeterId caloid, const unsigned int ieta, const unsigned int iphi)
virtual ~RawTower_Prototype2 ()
void Reset () override
Clear Event.
int isValid () const override
isValid returns non zero if object contains vailid data
void identify (std::ostream &os=std::cout) const override
void set_id (RawTowerDefs::keytype id) override
RawTowerDefs::keytype get_id () const override
int get_bineta () const override
int get_binphi () const override
int get_column () const override
int get_row () const override
double get_energy () const override
energy assigned to the tower. Depending on stage of process and DST node name, it could be energy deposition, light yield or calibrated energies
void set_energy (const double e) override
energy assigned to the tower. Depending on stage of process and DST node name, it could be energy deposition, light yield or calibrated energies
float get_time () const override
Time stamp assigned to the tower. Depending on the tower maker, it could be rise time or peak time.
void set_time (const float t) override
Time stamp assigned to the tower. Depending on the tower maker, it could be rise time or peak time.
void set_signal_samples (int i, signal_type sig)
signal_type get_signal_samples (int i) const
void set_HBD_channel_number (int i)
int get_HBD_channel_number () const
double get_energy_power_law_exp (int verbosity=0)
Public Member Functions inherited from RawTower
~RawTower () override
virtual void set_key (RawTowerDefs::keytype id)
virtual RawTowerDefs::keytype get_key () const
virtual int get_bintheta () const
virtual int get_binl () const
return layer ID assigned to tower
virtual double get_scint_gammas () const
energy assigned to the tower. Depending on stage of process and DST node name, it could be energy deposition, light yield or calibrated energies
virtual void set_scint_gammas (const double)
scint_gammas assigned to the tower. Depending on stage of process and DST node name, it could be scint_gammas deposition, light yield or calibrated energies
virtual double get_cerenkov_gammas () const
energy assigned to the tower. Depending on stage of process and DST node name, it could be energy deposition, light yield or calibrated energies
virtual void set_cerenkov_gammas (const double)
cerenkov_gammas assigned to the tower. Depending on stage of process and DST node name, it could be cerenkov_gammas deposition, light yield or calibrated energies
virtual bool empty_g4cells () const
virtual size_t size_g4cells () const
virtual CellConstRange get_g4cells () const
virtual CellIterator find_g4cell (CellKeyType id)
virtual CellConstIterator find_g4cell (CellKeyType id) const
virtual void add_ecell (const CellKeyType, const float)
virtual void clear_g4cells ()
virtual bool empty_g4showers () const
virtual size_t size_g4showers () const
virtual ShowerConstRange get_g4showers () const
virtual ShowerIterator find_g4shower (int)
virtual ShowerConstIterator find_g4shower (int) const
virtual void add_eshower (const int, const float)
virtual void clear_g4showers ()
virtual bool has_property (const PROPERTY) const
virtual double get_property (const PROPERTY) const
virtual void set_property (const PROPERTY, const double)
Public Member Functions inherited from PHObject
PHObject ()
ctor
~PHObject () override
dtor
virtual PHObject * CloneMe () const
Virtual copy constructor.
virtual PHObject * clone () const final
PHObject * Clone (const char *newname="") const final
void Copy (TObject &object) const final
virtual int Integrate () const
virtual int Integrate (PHObject *)
virtual void CopyFrom (const PHObject *obj)
Protected Attributes
RawTowerDefs::keytype towerid
double energy
float time
signal_type signal_samples [NSAMPLES]
int HBD_channel
Additional Inherited Members
Static Public Member Functions inherited from RawTower
static const std::string get_property_info (PROPERTY prop_id)
Protected Member Functions inherited from RawTower
RawTower ()
virtual unsigned int get_property_nocheck (const PROPERTY) const
virtual void set_property_nocheck (const PROPERTY, const unsigned int)
Detailed Description
Definition at line 13 of file RawTower_Prototype2.h.
View newest version in sPHENIX GitHub at line 13 of file RawTower_Prototype2.h
Member Typedef Documentation
typedef float RawTower_Prototype2::signal_type
Definition at line 46 of file RawTower_Prototype2.h.
View newest version in sPHENIX GitHub at line 46 of file RawTower_Prototype2.h
Member Enumeration Documentation
anonymous enum
Enumerator:
NSAMPLES
Definition at line 42 of file RawTower_Prototype2.h.
View newest version in sPHENIX GitHub at line 42 of file RawTower_Prototype2.h
Constructor & Destructor Documentation
RawTower_Prototype2::RawTower_Prototype2 ()
Definition at line 16 of file RawTower_Prototype2.cc.
View newest version in sPHENIX GitHub at line 16 of file RawTower_Prototype2.cc
References NSAMPLES, and signal_samples.
RawTower_Prototype2::RawTower_Prototype2 (const RawTower & tower)
Definition at line 26 of file RawTower_Prototype2.cc.
View newest version in sPHENIX GitHub at line 26 of file RawTower_Prototype2.cc
References energy, RawTower::get_energy(), RawTower::get_id(), RawTower::get_time(), HBD_channel, NSAMPLES, signal_samples, and time.
RawTower_Prototype2::RawTower_Prototype2 (RawTowerDefs::keytype id)
Definition at line 35 of file RawTower_Prototype2.cc.
View newest version in sPHENIX GitHub at line 35 of file RawTower_Prototype2.cc
References NSAMPLES, and signal_samples.
RawTower_Prototype2::RawTower_Prototype2 (const unsigned int icol, const unsigned int irow)
Definition at line 44 of file RawTower_Prototype2.cc.
View newest version in sPHENIX GitHub at line 44 of file RawTower_Prototype2.cc
References RawTowerDefs::encode_towerid(), RawTowerDefs::NONE, NSAMPLES, and signal_samples.
RawTower_Prototype2::RawTower_Prototype2 (const RawTowerDefs::CalorimeterId caloid, const unsigned int ieta, const unsigned int iphi)
Definition at line 55 of file RawTower_Prototype2.cc.
View newest version in sPHENIX GitHub at line 55 of file RawTower_Prototype2.cc
References RawTowerDefs::encode_towerid(), NSAMPLES, and signal_samples.
virtual RawTower_Prototype2::~RawTower_Prototype2 () inline virtual
Definition at line 22 of file RawTower_Prototype2.h.
View newest version in sPHENIX GitHub at line 22 of file RawTower_Prototype2.h
Member Function Documentation
int RawTower_Prototype2::get_bineta () const inline override virtual
Reimplemented from RawTower.
Definition at line 30 of file RawTower_Prototype2.h.
View newest version in sPHENIX GitHub at line 30 of file RawTower_Prototype2.h
References RawTowerDefs::decode_index1().
Referenced by identify().
int RawTower_Prototype2::get_binphi () const inline override virtual
Reimplemented from RawTower.
Definition at line 31 of file RawTower_Prototype2.h.
View newest version in sPHENIX GitHub at line 31 of file RawTower_Prototype2.h
References RawTowerDefs::decode_index2().
Referenced by identify().
int RawTower_Prototype2::get_column () const inline override virtual
Reimplemented from RawTower.
Definition at line 32 of file RawTower_Prototype2.h.
View newest version in sPHENIX GitHub at line 32 of file RawTower_Prototype2.h
References RawTowerDefs::decode_index1().
double RawTower_Prototype2::get_energy () const inline override virtual
energy assigned to the tower. Depending on stage of process and DST node name, it could be energy deposition, light yield or calibrated energies
Reimplemented from RawTower.
Definition at line 34 of file RawTower_Prototype2.h.
View newest version in sPHENIX GitHub at line 34 of file RawTower_Prototype2.h
References energy.
Referenced by identify(), isValid(), and Prototype2DSTReader::process_event().
double RawTower_Prototype2::get_energy_power_law_exp (int verbosity = 0)
Definition at line 98 of file RawTower_Prototype2.cc.
View newest version in sPHENIX GitHub at line 98 of file RawTower_Prototype2.cc
References i, NSAMPLES, PROTOTYPE2_FEM::SampleFit_PowerLawExp(), and signal_samples.
int RawTower_Prototype2::get_HBD_channel_number () const inline
Definition at line 51 of file RawTower_Prototype2.h.
View newest version in sPHENIX GitHub at line 51 of file RawTower_Prototype2.h
References HBD_channel.
RawTowerDefs::keytype RawTower_Prototype2::get_id () const inline override virtual
Reimplemented from RawTower.
Definition at line 29 of file RawTower_Prototype2.h.
View newest version in sPHENIX GitHub at line 29 of file RawTower_Prototype2.h
References towerid.
int RawTower_Prototype2::get_row () const inline override virtual
Reimplemented from RawTower.
Definition at line 33 of file RawTower_Prototype2.h.
View newest version in sPHENIX GitHub at line 33 of file RawTower_Prototype2.h
References RawTowerDefs::decode_index2().
RawTower_Prototype2::signal_type RawTower_Prototype2::get_signal_samples (int i) const
Definition at line 91 of file RawTower_Prototype2.cc.
View newest version in sPHENIX GitHub at line 91 of file RawTower_Prototype2.cc
References assert, i, NSAMPLES, and signal_samples.
float RawTower_Prototype2::get_time () const inline override virtual
Time stamp assigned to the tower. Depending on the tower maker, it could be rise time or peak time.
Reimplemented from RawTower.
Definition at line 36 of file RawTower_Prototype2.h.
View newest version in sPHENIX GitHub at line 36 of file RawTower_Prototype2.h
References time.
void RawTower_Prototype2::identify (std::ostream & os = std::cout) const override virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from RawTower.
Definition at line 76 of file RawTower_Prototype2.cc.
View newest version in sPHENIX GitHub at line 76 of file RawTower_Prototype2.cc
References get_bineta(), get_binphi(), and get_energy().
int RawTower_Prototype2::isValid () const override virtual
isValid returns non zero if object contains vailid data
Reimplemented from RawTower.
Definition at line 74 of file RawTower_Prototype2.cc.
View newest version in sPHENIX GitHub at line 74 of file RawTower_Prototype2.cc
References get_energy().
void RawTower_Prototype2::Reset () override virtual
Clear Event.
Reimplemented from RawTower.
Definition at line 67 of file RawTower_Prototype2.cc.
View newest version in sPHENIX GitHub at line 67 of file RawTower_Prototype2.cc
References energy, NSAMPLES, signal_samples, and time.
void RawTower_Prototype2::set_energy (const double) inline override virtual
energy assigned to the tower. Depending on stage of process and DST node name, it could be energy deposition, light yield or calibrated energies
Reimplemented from RawTower.
Definition at line 35 of file RawTower_Prototype2.h.
View newest version in sPHENIX GitHub at line 35 of file RawTower_Prototype2.h
References Acts::UnitConstants::e, and energy.
void RawTower_Prototype2::set_HBD_channel_number (int i) inline
Definition at line 50 of file RawTower_Prototype2.h.
View newest version in sPHENIX GitHub at line 50 of file RawTower_Prototype2.h
References HBD_channel, and i.
void RawTower_Prototype2::set_id (RawTowerDefs::keytype id) inline override virtual
Reimplemented from RawTower.
Definition at line 28 of file RawTower_Prototype2.h.
View newest version in sPHENIX GitHub at line 28 of file RawTower_Prototype2.h
References train_ambiguity_solver::id.
void RawTower_Prototype2::set_signal_samples (int i, RawTower_Prototype2::signal_type sig)
Definition at line 82 of file RawTower_Prototype2.cc.
View newest version in sPHENIX GitHub at line 82 of file RawTower_Prototype2.cc
References assert, i, NSAMPLES, and signal_samples.
void RawTower_Prototype2::set_time (const float) inline override virtual
Time stamp assigned to the tower. Depending on the tower maker, it could be rise time or peak time.
Reimplemented from RawTower.
Definition at line 37 of file RawTower_Prototype2.h.
View newest version in sPHENIX GitHub at line 37 of file RawTower_Prototype2.h
References t, and time.
Member Data Documentation
double RawTower_Prototype2::energy protected
energy assigned to the tower. Depending on stage of process and DST node name, it could be energy deposition, light yield or calibrated energies
Definition at line 62 of file RawTower_Prototype2.h.
View newest version in sPHENIX GitHub at line 62 of file RawTower_Prototype2.h
Referenced by get_energy(), RawTower_Prototype2(), Reset(), and set_energy().
int RawTower_Prototype2::HBD_channel protected
Definition at line 69 of file RawTower_Prototype2.h.
View newest version in sPHENIX GitHub at line 69 of file RawTower_Prototype2.h
Referenced by get_HBD_channel_number(), RawTower_Prototype2(), and set_HBD_channel_number().
signal_type RawTower_Prototype2::signal_samples[NSAMPLES] protected
Definition at line 68 of file RawTower_Prototype2.h.
View newest version in sPHENIX GitHub at line 68 of file RawTower_Prototype2.h
Referenced by get_energy_power_law_exp(), get_signal_samples(), RawTower_Prototype2(), Reset(), and set_signal_samples().
float RawTower_Prototype2::time protected
Time stamp assigned to the tower. Depending on the tower maker, it could be rise time or peak time.
Definition at line 65 of file RawTower_Prototype2.h.
View newest version in sPHENIX GitHub at line 65 of file RawTower_Prototype2.h
Referenced by get_time(), RawTower_Prototype2(), Reset(), and set_time().
RawTowerDefs::keytype RawTower_Prototype2::towerid protected
Definition at line 58 of file RawTower_Prototype2.h.
View newest version in sPHENIX GitHub at line 58 of file RawTower_Prototype2.h
Referenced by get_id().
The documentation for this class was generated from the following files:
prototype/blob/master/offline/packages/Prototype2/RawTower_Prototype2.h
prototype/blob/master/offline/packages/Prototype2/RawTower_Prototype2.cc