Analysis Software: Factory Class Reference
Factory Class Reference
#include <pythia6/blob/master/pythiaeRHIC/erhic/factory.h>
Public Member Functions
Factory ()
virtual ~Factory ()
erhic::EventPythia * Create ()
virtual std::string EventName () const
virtual TBranch * Branch (TTree &tree, const std::string &name)
Private Attributes
erhic::EventPythia * mEvent
Detailed Description
Factor class for PYTHIA events. Handles creating the ROOT tree branch and copying values from PYTHIA common blocks/modules to the event.
Definition at line 29 of file factory.h.
View newest version in sPHENIX GitHub at line 29 of file factory.h
Constructor & Destructor Documentation
Factory::Factory ()
Constructor
Definition at line 24 of file factory.cpp.
View newest version in sPHENIX GitHub at line 24 of file factory.cpp
References Factory().
Referenced by Factory().
Factory::~Factory () virtual
Destructor
Definition at line 30 of file factory.cpp.
View newest version in sPHENIX GitHub at line 30 of file factory.cpp
References ~Factory().
Referenced by ~Factory().
Member Function Documentation
TBranch * Factory::Branch (TTree & tree, const std::string & name) virtual
Add a branch named "name" for the event type generated by this factory to a ROOT TTree. Returns a pointer to the branch, or NULL in the case of an error.
Definition at line 154 of file factory.cpp.
View newest version in sPHENIX GitHub at line 154 of file factory.cpp
erhic::EventPythia * Factory::Create ()
Populate the stored event with the current contents of PYTHIA and return a pointer to the event. Do not delete this pointer!
Definition at line 42 of file factory.cpp.
View newest version in sPHENIX GitHub at line 42 of file factory.cpp
References __pythia6_MOD_ebrems, __pythia6_MOD_f1, __pythia6_MOD_f2, __pythia6_MOD_genevent, __pythia6_MOD_r, __pythia6_MOD_radgame, __pythia6_MOD_radgamp, __pythia6_MOD_sigma_rad, __pythia6_MOD_sigradcor, __pythia6_MOD_truenu, __pythia6_MOD_truew2, __pythia6_MOD_truex, Create(), i, k, msti, Acts::UnitConstants::nm, ntracks, merge_hashes::p, pari, pyjets_, testSigmaEff::v, and vint.
Referenced by Create().
std::string Factory::EventName () const virtual
Returns a string with the full (including namespace) class name of the event type produced. This is important for use with ROOT TTree to ensure the correct event type in branches.
Definition at line 145 of file factory.cpp.
View newest version in sPHENIX GitHub at line 145 of file factory.cpp
References EventName().
Referenced by EventName().
Member Data Documentation
erhic::EventPythia* Factory::mEvent private
Definition at line 61 of file factory.h.
View newest version in sPHENIX GitHub at line 61 of file factory.h
The documentation for this class was generated from the following files:
pythia6/blob/master/pythiaeRHIC/erhic/factory.h
pythia6/blob/master/pythiaeRHIC/erhic/factory.cpp