Analysis Software: Acts::MultiTrajectoryHelpers Namespace Reference
Acts::MultiTrajectoryHelpers Namespace Reference
Classes
struct TrajectoryState
Struct for brief trajectory summary info.
Typedefs
using VolumeTrajectoryStateContainer = std::unordered_map< GeometryIdentifier::Value, TrajectoryState >
Functions
template<typename traj_t >
TrajectoryState trajectoryState (const traj_t &multiTraj, size_t entryIndex)
Getter for global trajectory info.
template<typename traj_t >
VolumeTrajectoryStateContainer trajectoryState (const traj_t &multiTraj, size_t entryIndex, const std::vector< GeometryIdentifier::Value > &volumeIds)
Getter for trajectory info for different sub-detectors.
template<typename track_state_proxy_t >
FreeVector freeFiltered (const GeometryContext &gctx, const track_state_proxy_t &trackStateProxy)
Transforms the filtered parameters from a TrackStateProxy to free parameters.
template<typename track_state_proxy_t >
FreeVector freeSmoothed (const GeometryContext &gctx, const track_state_proxy_t &trackStateProxy)
Transforms the smoothed parameters from a TrackStateProxy to free parameters.
Typedef Documentation
using Acts::MultiTrajectoryHelpers::VolumeTrajectoryStateContainer = typedef std::unordered_map<GeometryIdentifier::Value, TrajectoryState>
Definition at line 44 of file MultiTrajectoryHelpers.hpp.
View newest version in sPHENIX GitHub at line 44 of file MultiTrajectoryHelpers.hpp
Function Documentation
template<typename track_state_proxy_t > FreeVector Acts::MultiTrajectoryHelpers::freeFiltered (const GeometryContext & gctx, const track_state_proxy_t & trackStateProxy)
Transforms the filtered parameters from a TrackStateProxy to free parameters.
Template Parameters
track_state_proxy_t Type of the TrackStateProxy
Parameters
[in] gctx Geometry context
[in] trackStateProxy TrackStateProxy
Returns
Free parameters representation of the filtered parameters
Definition at line 146 of file MultiTrajectoryHelpers.hpp.
View newest version in sPHENIX GitHub at line 146 of file MultiTrajectoryHelpers.hpp
References gctx, and Acts::detail::transformBoundToFreeParameters().
Referenced by Acts::KalmanFitter< propagator_t, traj_t >::Actor< parameters_t >::filter(), Acts::CombinatorialKalmanFilter< propagator_t, traj_t >::Actor< source_link_accessor_t, parameters_t >::filter(), Acts::KalmanFitter< propagator_t, traj_t >::Actor< parameters_t >::reversedFilter(), and Acts::detail::GsfActor< bethe_heitler_approx_t, traj_t >::updateStepper().
template<typename track_state_proxy_t > FreeVector Acts::MultiTrajectoryHelpers::freeSmoothed (const GeometryContext & gctx, const track_state_proxy_t & trackStateProxy)
Transforms the smoothed parameters from a TrackStateProxy to free parameters.
Template Parameters
track_state_proxy_t Type of the TrackStateProxy
Parameters
[in] gctx Geometry context
[in] trackStateProxy TrackStateProxy
Returns
Free parameters representation of the smoothed parameters
Definition at line 161 of file MultiTrajectoryHelpers.hpp.
View newest version in sPHENIX GitHub at line 161 of file MultiTrajectoryHelpers.hpp
References gctx, and Acts::detail::transformBoundToFreeParameters().
Referenced by Acts::CombinatorialKalmanFilter< propagator_t, traj_t >::Actor< source_link_accessor_t, parameters_t >::finalize(), and ActsAlignment::detail::trackAlignmentState().
template<typename traj_t > TrajectoryState Acts::MultiTrajectoryHelpers::trajectoryState (const traj_t & multiTraj, size_t entryIndex)
Getter for global trajectory info.
Parameters
multiTraj The MultiTrajectory object
entryIndex The entry index of trajectory to investigate
Returns
The trajectory summary info
Definition at line 53 of file MultiTrajectoryHelpers.hpp.
View newest version in sPHENIX GitHub at line 53 of file MultiTrajectoryHelpers.hpp
References Acts::MultiTrajectoryHelpers::TrajectoryState::chi2Sum, Acts::HoleFlag, layer, Acts::MultiTrajectoryHelpers::TrajectoryState::measurementChi2, Acts::MeasurementFlag, Acts::MultiTrajectoryHelpers::TrajectoryState::measurementLayer, Acts::MultiTrajectoryHelpers::TrajectoryState::measurementVolume, Acts::MultiTrajectoryHelpers::TrajectoryState::NDF, Acts::MultiTrajectoryHelpers::TrajectoryState::nHoles, Acts::MultiTrajectoryHelpers::TrajectoryState::nMeasurements, Acts::MultiTrajectoryHelpers::TrajectoryState::nOutliers, Acts::MultiTrajectoryHelpers::TrajectoryState::nSharedHits, Acts::MultiTrajectoryHelpers::TrajectoryState::nStates, Acts::MultiTrajectoryHelpers::TrajectoryState::outlierChi2, Acts::OutlierFlag, Acts::MultiTrajectoryHelpers::TrajectoryState::outlierLayer, Acts::MultiTrajectoryHelpers::TrajectoryState::outlierVolume, Acts::SharedHitFlag, and filter::state.
Referenced by PHActsToSvtxTracks::createSvtxTrack(), ActsEvaluator::evaluateTrackFit(), Acts::AmbiguityTrackClassifier::inferScores(), PHActsGSF::updateSvtxTrack(), PHCosmicsTrkFitter::updateSvtxTrack(), PHActsTrkFitter::updateSvtxTrack(), ActsExamples::TrackFitterPerformanceWriter::writeT(), ActsExamples::CsvMultiTrajectoryWriter::writeT(), ActsExamples::CKFPerformanceWriter::writeT(), ActsExamples::RootTrajectorySummaryWriter::writeT(), ActsExamples::RootTrajectoryStatesWriter::writeT(), ActsExamples::VertexPerformanceWriter::writeT(), and ActsExamples::EDM4hepUtil::writeTrajectory().
template<typename traj_t > VolumeTrajectoryStateContainer Acts::MultiTrajectoryHelpers::trajectoryState (const traj_t & multiTraj, size_t entryIndex, const std::vector< GeometryIdentifier::Value > & volumeIds)
Getter for trajectory info for different sub-detectors.
Template Parameters
source_link_t Type of source link
Parameters
multiTraj The MultiTrajectory object
entryIndex The entry index of trajectory to investigate track states at different sub-detectors.
volumeIds The container for sub-detector Ids
Returns
The trajectory summary info at different sub-detectors (i.e. different volumes)
Definition at line 96 of file MultiTrajectoryHelpers.hpp.
View newest version in sPHENIX GitHub at line 96 of file MultiTrajectoryHelpers.hpp
References Acts::HoleFlag, it, layer, Acts::MeasurementFlag, Acts::OutlierFlag, Acts::SharedHitFlag, and filter::state.