Analysis Software: material_validation Namespace Reference
material_validation Namespace Reference
Functions
def runMaterialValidation
Variables
tuple matDeco acts.IMaterialDecorator.fromFile("material-map.json")
tuple field acts.ConstantBField(acts.Vector3(0, 0, 2 * acts.UnitConstants.T))
Function Documentation
def material_validation.runMaterialValidation (trackingGeometry, decorators, field, outputDir, outputName = "propagation-material", s = None)
Definition at line 21 of file material_validation.py.
View newest version in sPHENIX GitHub at line 21 of file material_validation.py
References acts.examples.ConcretePropagator(), and acts.Propagator().
Referenced by test_examples.test_material_mapping(), and test_examples.test_volume_material_mapping().
Variable Documentation
tuple material_validation.field acts.ConstantBField(acts.Vector3(0, 0, 2 * acts.UnitConstants.T))
Definition at line 70 of file material_validation.py.
View newest version in sPHENIX GitHub at line 70 of file material_validation.py
tuple material_validation.matDeco acts.IMaterialDecorator.fromFile("material-map.json")
Definition at line 64 of file material_validation.py.
View newest version in sPHENIX GitHub at line 64 of file material_validation.py