Analysis Software: EventHeaderv1 Class Reference
EventHeaderv1 Class Reference
simple event header with ID and time
#include <coresoftware/blob/master/offline/framework/ffaobjects/EventHeaderv1.h>
Public Member Functions
EventHeaderv1 ()=default
ctor
~EventHeaderv1 () override=default
dtor
PHObject * CloneMe () const override
Virtual copy constructor.
void Reset () override
Clear Event.
void identify (std::ostream &os=std::cout) const override
int isValid () const override
isValid returns non zero if object contains valid data
int get_RunNumber () const override
get Run Number
void set_RunNumber (const int run) override
set Run Number
int get_EvtSequence () const override
get Event Number
void set_EvtSequence (const int evtno) override
set Event Number
void set_floatval (const std::string &name, const float fval) override
float get_floatval (const std::string &name) const override
void set_intval (const std::string &name, const int64_t ival) override
int64_t get_intval (const std::string &name) const override
Public Member Functions inherited from EventHeader
~EventHeader () override=default
dtor
virtual void set_BunchCrossing (int64_t bcr)
bunch crossing
virtual int64_t get_BunchCrossing () const
bunch crossing
int get_EvtType () const
get Event Type (Data,rejected,EOR,BOR,...)
void set_EvtType (const int ival)
set Event Type (Data,rejected,EOR,BOR,...)
void set_ImpactParameter (const double rval)
float get_ImpactParameter () const
void set_EventPlaneAngle (const double rval)
float get_EventPlaneAngle () const
void set_eccentricity (const double rval)
float get_eccentricity () const
void set_ncoll (const int ival)
int get_ncoll () const
void set_npart (const int ival)
int get_npart () const
void set_TimeStamp (const time_t tval)
time_t get_TimeStamp () const
Public Member Functions inherited from PHObject
PHObject ()
ctor
~PHObject () override
dtor
virtual PHObject * clone () const final
PHObject * Clone (const char *newname="") const final
void Copy (TObject &object) const final
virtual int Integrate () const
virtual int Integrate (PHObject *)
virtual void CopyFrom (const PHObject *obj)
Private Attributes
int RunNumber = 0
int EvtSequence = 0
std::map< std::string, int64_t > m_IntEventProperties
std::map< std::string, float > m_FloatEventProperties
Detailed Description
simple event header with ID and time
Definition at line 16 of file EventHeaderv1.h.
View newest version in sPHENIX GitHub at line 16 of file EventHeaderv1.h
Constructor & Destructor Documentation
EventHeaderv1::EventHeaderv1 () default
ctor
Referenced by CloneMe().
EventHeaderv1::~EventHeaderv1 () override default
dtor
Member Function Documentation
PHObject* EventHeaderv1::CloneMe () const inline override virtual
Virtual copy constructor.
Reimplemented from PHObject.
Reimplemented in EventHeaderv2.
Definition at line 24 of file EventHeaderv1.h.
View newest version in sPHENIX GitHub at line 24 of file EventHeaderv1.h
References EventHeaderv1().
int EventHeaderv1::get_EvtSequence () const inline override virtual
get Event Number
Reimplemented from EventHeader.
Definition at line 43 of file EventHeaderv1.h.
View newest version in sPHENIX GitHub at line 43 of file EventHeaderv1.h
References EvtSequence.
Referenced by KFParticle_nTuple::fillBranch(), and EventHeaderv2::identify().
float EventHeaderv1::get_floatval (const std::string & name) const override virtual
Reimplemented from EventHeader.
Definition at line 47 of file EventHeaderv1.cc.
View newest version in sPHENIX GitHub at line 47 of file EventHeaderv1.cc
References m_FloatEventProperties.
int64_t EventHeaderv1::get_intval (const std::string & name) const override virtual
Reimplemented from EventHeader.
Definition at line 62 of file EventHeaderv1.cc.
View newest version in sPHENIX GitHub at line 62 of file EventHeaderv1.cc
References m_IntEventProperties.
int EventHeaderv1::get_RunNumber () const inline override virtual
get Run Number
Reimplemented from EventHeader.
Definition at line 38 of file EventHeaderv1.h.
View newest version in sPHENIX GitHub at line 38 of file EventHeaderv1.h
References RunNumber.
Referenced by KFParticle_nTuple::fillBranch(), and EventHeaderv2::identify().
void EventHeaderv1::identify (std::ostream & os = std::cout) const override virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from EventHeader.
Reimplemented in EventHeaderv2.
Definition at line 16 of file EventHeaderv1.cc.
View newest version in sPHENIX GitHub at line 16 of file EventHeaderv1.cc
References EvtSequence, m_FloatEventProperties, m_IntEventProperties, and RunNumber.
Referenced by RunInfoUnpackPRDF::process_event(), and MvtxRunInfoUnpackPRDF::process_event().
int EventHeaderv1::isValid () const override virtual
isValid returns non zero if object contains valid data
Reimplemented from EventHeader.
Definition at line 37 of file EventHeaderv1.cc.
View newest version in sPHENIX GitHub at line 37 of file EventHeaderv1.cc
References RunNumber.
void EventHeaderv1::Reset () override virtual
Clear Event.
Reimplemented from EventHeader.
Reimplemented in EventHeaderv2.
Definition at line 7 of file EventHeaderv1.cc.
View newest version in sPHENIX GitHub at line 7 of file EventHeaderv1.cc
References EvtSequence, m_FloatEventProperties, m_IntEventProperties, and RunNumber.
Referenced by EventHeaderv2::Reset().
void EventHeaderv1::set_EvtSequence (const int evtno) inline override virtual
set Event Number
Reimplemented from EventHeader.
Definition at line 45 of file EventHeaderv1.h.
View newest version in sPHENIX GitHub at line 45 of file EventHeaderv1.h
References EvtSequence.
Referenced by RunInfoUnpackPRDF::process_event(), and MvtxRunInfoUnpackPRDF::process_event().
void EventHeaderv1::set_floatval (const std::string & name, const float fval) override virtual
Reimplemented from EventHeader.
Definition at line 42 of file EventHeaderv1.cc.
View newest version in sPHENIX GitHub at line 42 of file EventHeaderv1.cc
References m_FloatEventProperties, and perf_headwind::name.
void EventHeaderv1::set_intval (const std::string & name, const int64_t ival) override virtual
Reimplemented from EventHeader.
Definition at line 57 of file EventHeaderv1.cc.
View newest version in sPHENIX GitHub at line 57 of file EventHeaderv1.cc
References m_IntEventProperties, and perf_headwind::name.
void EventHeaderv1::set_RunNumber (const int run) inline override virtual
set Run Number
Reimplemented from EventHeader.
Definition at line 40 of file EventHeaderv1.h.
View newest version in sPHENIX GitHub at line 40 of file EventHeaderv1.h
References utils::run, and RunNumber.
Referenced by RunInfoUnpackPRDF::process_event(), and MvtxRunInfoUnpackPRDF::process_event().
Member Data Documentation
int EventHeaderv1::EvtSequence = 0 private
Definition at line 55 of file EventHeaderv1.h.
View newest version in sPHENIX GitHub at line 55 of file EventHeaderv1.h
Referenced by get_EvtSequence(), identify(), Reset(), and set_EvtSequence().
std::map<std::string, float> EventHeaderv1::m_FloatEventProperties private
Definition at line 57 of file EventHeaderv1.h.
View newest version in sPHENIX GitHub at line 57 of file EventHeaderv1.h
Referenced by get_floatval(), identify(), Reset(), and set_floatval().
std::map<std::string, int64_t> EventHeaderv1::m_IntEventProperties private
Definition at line 56 of file EventHeaderv1.h.
View newest version in sPHENIX GitHub at line 56 of file EventHeaderv1.h
Referenced by get_intval(), identify(), Reset(), and set_intval().
int EventHeaderv1::RunNumber = 0 private
Definition at line 54 of file EventHeaderv1.h.
View newest version in sPHENIX GitHub at line 54 of file EventHeaderv1.h
Referenced by get_RunNumber(), identify(), isValid(), Reset(), and set_RunNumber().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/framework/ffaobjects/EventHeaderv1.h
coresoftware/blob/master/offline/framework/ffaobjects/EventHeaderv1.cc