Analysis Software: kdfinder::TrackCandidate< T > Class Template Reference
kdfinder::TrackCandidate< T > Class Template Reference
#include <coresoftware/blob/master/offline/packages/PHTpcTracker/externals/kdfinder.hpp>
Public Member Functions
TrackCandidate (std::vector< std::vector< T >> &hits, T B)
~TrackCandidate ()
bool isFitted () const
void refit ()
size_t nhits () const
std::vector< T > & getFirstHit ()
std::vector< T > & getLastHit ()
std::vector< std::vector< T > > & getHits ()
void deleteHits ()
T sign () const
T momentum () const
T Pt () const
T Pl () const
std::vector< T > getMomForHit (size_t i)
std::vector< T > getPosForHit (size_t i)
std::vector< T > & getHit (size_t i)
T approxLength ()
T getB () const
T minR () const
T maxR () const
T radius () const
T radius_err () const
T tanl () const
T tanl_err () const
T dip () const
T distanceToCircle (T x, T y)
T distanceToCircle (const std::vector< T > &hit)
void mergeCandidate (TrackCandidate< T > *candidate)
void print ()
void print_xy ()
void print_sz ()
Circle< T > * getCircleFit ()
Private Member Functions
void calcMinMaxR ()
void radiusFit ()
void szFit ()
T getS (size_t i) const
T calcAlpha (size_t i)
T calcZPosByS (T s)
T phi_mpi_pi (T x) const
Private Attributes
Circle< T > * mCircle
Line< T > * mLine
std::vector< std::vector< T > > mHits
T mB
T mMinR
T mMaxR
Detailed Description
template<class T>
class kdfinder::TrackCandidate< T >
Definition at line 2328 of file kdfinder.hpp.
View newest version in sPHENIX GitHub at line 2328 of file kdfinder.hpp
Constructor & Destructor Documentation
template<class T> kdfinder::TrackCandidate< T >::TrackCandidate (std::vector< std::vector< T >> & hits, T B) inline
Definition at line 2331 of file kdfinder.hpp.
View newest version in sPHENIX GitHub at line 2331 of file kdfinder.hpp
References kdfinder::TrackCandidate< T >::calcMinMaxR(), kdfinder::TrackCandidate< T >::mHits, and n.
template<class T> kdfinder::TrackCandidate< T >::~TrackCandidate () inline
Definition at line 2350 of file kdfinder.hpp.
View newest version in sPHENIX GitHub at line 2350 of file kdfinder.hpp
References kdfinder::TrackCandidate< T >::mCircle, kdfinder::TrackCandidate< T >::mHits, and kdfinder::TrackCandidate< T >::mLine.
Member Function Documentation
template<class T> T kdfinder::TrackCandidate< T >::approxLength () inline
Definition at line 2506 of file kdfinder.hpp.
View newest version in sPHENIX GitHub at line 2506 of file kdfinder.hpp
References kdfinder::TrackCandidate< T >::getMomForHit(), kdfinder::TrackCandidate< T >::getPosForHit(), i, kdfinder::TrackCandidate< T >::isFitted(), G4PLUGDOOR::length, kdfinder::TrackCandidate< T >::mB, kdfinder::TrackCandidate< T >::mHits, p, kdfinder::TrackCandidate< T >::sign(), and Acts::UnitConstants::T.
Referenced by kdfinder::TrackCandidate< T >::print().
template<class T> T kdfinder::TrackCandidate< T >::calcAlpha (size_t i) inline private
Definition at line 2727 of file kdfinder.hpp.
View newest version in sPHENIX GitHub at line 2727 of file kdfinder.hpp
References M_PI, kdfinder::TrackCandidate< T >::mCircle, and kdfinder::TrackCandidate< T >::mHits.
Referenced by kdfinder::TrackCandidate< T >::getMomForHit(), and kdfinder::TrackCandidate< T >::getPosForHit().
template<class T> void kdfinder::TrackCandidate< T >::calcMinMaxR () inline private
Definition at line 2650 of file kdfinder.hpp.
View newest version in sPHENIX GitHub at line 2650 of file kdfinder.hpp
References i, kdfinder::TrackCandidate< T >::mHits, kdfinder::TrackCandidate< T >::mMaxR, kdfinder::TrackCandidate< T >::mMinR, kdfinder::TrackCandidate< T >::radius(), and Acts::UnitConstants::T.
Referenced by kdfinder::TrackCandidate< T >::mergeCandidate(), and kdfinder::TrackCandidate< T >::TrackCandidate().
template<class T> T kdfinder::TrackCandidate< T >::calcZPosByS (T s) inline private
Definition at line 2732 of file kdfinder.hpp.
View newest version in sPHENIX GitHub at line 2732 of file kdfinder.hpp
References kdfinder::TrackCandidate< T >::mLine.
Referenced by kdfinder::TrackCandidate< T >::getPosForHit().
template<class T> void kdfinder::TrackCandidate< T >::deleteHits () inline
Definition at line 2399 of file kdfinder.hpp.
View newest version in sPHENIX GitHub at line 2399 of file kdfinder.hpp
References kdfinder::TrackCandidate< T >::mCircle, kdfinder::TrackCandidate< T >::mHits, kdfinder::TrackCandidate< T >::mLine, and swap().
Referenced by kdfinder::TrackCandidate< T >::mergeCandidate().
template<class T> T kdfinder::TrackCandidate< T >::dip () const inline
Definition at line 2565 of file kdfinder.hpp.
View newest version in sPHENIX GitHub at line 2565 of file kdfinder.hpp
References kdfinder::TrackCandidate< T >::mLine.
Referenced by __example_3.f__().
template<class T> T kdfinder::TrackCandidate< T >::distanceToCircle (T x, T y) inline
Definition at line 2570 of file kdfinder.hpp.
View newest version in sPHENIX GitHub at line 2570 of file kdfinder.hpp
References kdfinder::TrackCandidate< T >::mCircle, x, and y.
template<class T> T kdfinder::TrackCandidate< T >::distanceToCircle (const std::vector< T > & hit) inline
Definition at line 2575 of file kdfinder.hpp.
View newest version in sPHENIX GitHub at line 2575 of file kdfinder.hpp
References kdfinder::TrackCandidate< T >::mCircle.
template<class T> T kdfinder::TrackCandidate< T >::getB () const inline
Definition at line 2530 of file kdfinder.hpp.
View newest version in sPHENIX GitHub at line 2530 of file kdfinder.hpp
References kdfinder::TrackCandidate< T >::mB.
template<class T> Circle<T>* kdfinder::TrackCandidate< T >::getCircleFit () inline
Definition at line 2647 of file kdfinder.hpp.
View newest version in sPHENIX GitHub at line 2647 of file kdfinder.hpp
References kdfinder::TrackCandidate< T >::mCircle.
template<class T> std::vector<T>& kdfinder::TrackCandidate< T >::getFirstHit () inline
Definition at line 2384 of file kdfinder.hpp.
View newest version in sPHENIX GitHub at line 2384 of file kdfinder.hpp
References kdfinder::TrackCandidate< T >::mHits.
template<class T> std::vector<T>& kdfinder::TrackCandidate< T >::getHit (size_t i) inline
Definition at line 2501 of file kdfinder.hpp.
View newest version in sPHENIX GitHub at line 2501 of file kdfinder.hpp
References i, and kdfinder::TrackCandidate< T >::mHits.
Referenced by PHTpcTrackFollower::candidate_to_genfit().
template<class T> std::vector<std::vector<T> >& kdfinder::TrackCandidate< T >::getHits () inline
Definition at line 2394 of file kdfinder.hpp.
View newest version in sPHENIX GitHub at line 2394 of file kdfinder.hpp
References kdfinder::TrackCandidate< T >::mHits.
Referenced by kdfinder::TrackCandidate< T >::mergeCandidate(), and PHTpcTrackFollower::propagateTrack().
template<class T> std::vector<T>& kdfinder::TrackCandidate< T >::getLastHit () inline
Definition at line 2389 of file kdfinder.hpp.
View newest version in sPHENIX GitHub at line 2389 of file kdfinder.hpp
References kdfinder::TrackCandidate< T >::mHits.
template<class T> std::vector<T> kdfinder::TrackCandidate< T >::getMomForHit (size_t i) inline
Definition at line 2452 of file kdfinder.hpp.
View newest version in sPHENIX GitHub at line 2452 of file kdfinder.hpp
References kdfinder::TrackCandidate< T >::calcAlpha(), i, kdfinder::TrackCandidate< T >::mHits, phi, kdfinder::TrackCandidate< T >::Pl(), kdfinder::TrackCandidate< T >::Pt(), and Acts::UnitConstants::T.
Referenced by kdfinder::TrackCandidate< T >::approxLength(), PHTpcTrackFollower::candidate_to_genfit(), and PHTpcTrackFollower::propagateTrack().
template<class T> std::vector<T> kdfinder::TrackCandidate< T >::getPosForHit (size_t i) inline
Definition at line 2489 of file kdfinder.hpp.
View newest version in sPHENIX GitHub at line 2489 of file kdfinder.hpp
References kdfinder::TrackCandidate< T >::calcAlpha(), kdfinder::TrackCandidate< T >::calcZPosByS(), kdfinder::TrackCandidate< T >::getS(), kdfinder::TrackCandidate< T >::mCircle, kdfinder::TVector< T >::rotateZ(), kdfinder::TVector< T >::setZ(), kdfinder::TVector< T >::x(), kdfinder::TVector< T >::y(), and kdfinder::TVector< T >::z().
Referenced by kdfinder::TrackCandidate< T >::approxLength(), PHTpcTrackFollower::candidate_to_genfit(), and PHTpcTrackFollower::propagateTrack().
template<class T> T kdfinder::TrackCandidate< T >::getS (size_t i) const inline private
Definition at line 2720 of file kdfinder.hpp.
View newest version in sPHENIX GitHub at line 2720 of file kdfinder.hpp
References kdfinder::TrackCandidate< T >::mCircle, kdfinder::TrackCandidate< T >::mHits, kdfinder::TrackCandidate< T >::phi_mpi_pi(), and Acts::UnitConstants::T.
Referenced by kdfinder::TrackCandidate< T >::getPosForHit(), kdfinder::TrackCandidate< T >::print_sz(), kdfinder::TrackCandidate< T >::sign(), and kdfinder::TrackCandidate< T >::szFit().
template<class T> bool kdfinder::TrackCandidate< T >::isFitted () const inline
Definition at line 2365 of file kdfinder.hpp.
View newest version in sPHENIX GitHub at line 2365 of file kdfinder.hpp
References kdfinder::TrackCandidate< T >::mCircle, and kdfinder::TrackCandidate< T >::mLine.
Referenced by kdfinder::TrackCandidate< T >::approxLength(), and kdfinder::get_track_candidates().
template<class T> T kdfinder::TrackCandidate< T >::maxR () const inline
Definition at line 2540 of file kdfinder.hpp.
View newest version in sPHENIX GitHub at line 2540 of file kdfinder.hpp
References kdfinder::TrackCandidate< T >::mMaxR.
Referenced by kdfinder::TrackCandidate< T >::mergeCandidate().
template<class T> void kdfinder::TrackCandidate< T >::mergeCandidate (TrackCandidate< T > * candidate) inline
Definition at line 2580 of file kdfinder.hpp.
View newest version in sPHENIX GitHub at line 2580 of file kdfinder.hpp
References kdfinder::TrackCandidate< T >::calcMinMaxR(), kdfinder::TrackCandidate< T >::deleteHits(), kdfinder::TrackCandidate< T >::getHits(), kdfinder::TrackCandidate< T >::maxR(), kdfinder::TrackCandidate< T >::mHits, kdfinder::TrackCandidate< T >::minR(), and kdfinder::TrackCandidate< T >::refit().
template<class T> T kdfinder::TrackCandidate< T >::minR () const inline
Definition at line 2535 of file kdfinder.hpp.
View newest version in sPHENIX GitHub at line 2535 of file kdfinder.hpp
References kdfinder::TrackCandidate< T >::mMinR.
Referenced by kdfinder::candidatesortradius(), and kdfinder::TrackCandidate< T >::mergeCandidate().
template<class T> T kdfinder::TrackCandidate< T >::momentum () const inline
Definition at line 2421 of file kdfinder.hpp.
View newest version in sPHENIX GitHub at line 2421 of file kdfinder.hpp
References kdfinder::TrackCandidate< T >::Pl(), and kdfinder::TrackCandidate< T >::Pt().
Referenced by kdfinder::TrackCandidate< T >::print(), and PHTpcTrackFollower::propagateTrack().
template<class T> size_t kdfinder::TrackCandidate< T >::nhits () const inline
Definition at line 2379 of file kdfinder.hpp.
View newest version in sPHENIX GitHub at line 2379 of file kdfinder.hpp
References kdfinder::TrackCandidate< T >::mHits.
Referenced by PHTpcTrackFollower::candidate_to_genfit(), kdfinder::candidatesort(), PHTpcTrackFollower::followTracks(), and kdfinder::ismergedcandidate().
template<class T> T kdfinder::TrackCandidate< T >::phi_mpi_pi (T x) const inline private
Definition at line 2737 of file kdfinder.hpp.
View newest version in sPHENIX GitHub at line 2737 of file kdfinder.hpp
References M_PI, and x.
Referenced by kdfinder::TrackCandidate< T >::getS().
template<class T> T kdfinder::TrackCandidate< T >::Pl () const inline
Definition at line 2431 of file kdfinder.hpp.
View newest version in sPHENIX GitHub at line 2431 of file kdfinder.hpp
References kdfinder::TrackCandidate< T >::mHits, kdfinder::TrackCandidate< T >::mLine, kdfinder::TrackCandidate< T >::Pt(), and Acts::UnitConstants::T.
Referenced by kdfinder::TrackCandidate< T >::getMomForHit(), kdfinder::TrackCandidate< T >::momentum(), and kdfinder::TrackCandidate< T >::print().
template<class T> void kdfinder::TrackCandidate< T >::print () inline
Definition at line 2603 of file kdfinder.hpp.
View newest version in sPHENIX GitHub at line 2603 of file kdfinder.hpp
References kdfinder::TrackCandidate< T >::approxLength(), kdfinder::TrackCandidate< T >::mCircle, kdfinder::TrackCandidate< T >::mLine, kdfinder::TrackCandidate< T >::momentum(), kdfinder::TrackCandidate< T >::Pl(), and kdfinder::TrackCandidate< T >::Pt().
template<class T> void kdfinder::TrackCandidate< T >::print_sz () inline
Definition at line 2638 of file kdfinder.hpp.
View newest version in sPHENIX GitHub at line 2638 of file kdfinder.hpp
References kdfinder::TrackCandidate< T >::getS(), i, and kdfinder::TrackCandidate< T >::mHits.
template<class T> void kdfinder::TrackCandidate< T >::print_xy () inline
Definition at line 2628 of file kdfinder.hpp.
View newest version in sPHENIX GitHub at line 2628 of file kdfinder.hpp
References i, kdfinder::TrackCandidate< T >::mCircle, and kdfinder::TrackCandidate< T >::mHits.
template<class T> T kdfinder::TrackCandidate< T >::Pt () const inline
Definition at line 2426 of file kdfinder.hpp.
View newest version in sPHENIX GitHub at line 2426 of file kdfinder.hpp
References kdfinder::TrackCandidate< T >::mB, and kdfinder::TrackCandidate< T >::mCircle.
Referenced by kdfinder::TrackCandidate< T >::getMomForHit(), kdfinder::TrackCandidate< T >::momentum(), kdfinder::TrackCandidate< T >::Pl(), and kdfinder::TrackCandidate< T >::print().
template<class T> T kdfinder::TrackCandidate< T >::radius () const inline
Definition at line 2545 of file kdfinder.hpp.
View newest version in sPHENIX GitHub at line 2545 of file kdfinder.hpp
References kdfinder::TrackCandidate< T >::mCircle.
Referenced by kdfinder::TrackCandidate< T >::calcMinMaxR().
template<class T> T kdfinder::TrackCandidate< T >::radius_err () const inline
Definition at line 2550 of file kdfinder.hpp.
View newest version in sPHENIX GitHub at line 2550 of file kdfinder.hpp
References kdfinder::TrackCandidate< T >::mCircle.
template<class T> void kdfinder::TrackCandidate< T >::radiusFit () inline private
Definition at line 2673 of file kdfinder.hpp.
View newest version in sPHENIX GitHub at line 2673 of file kdfinder.hpp
References kdfinder::TrackCandidate< T >::mCircle, kdfinder::TrackCandidate< T >::mHits, kdfinder::CircleFit< T >::RegularFit(), and kdfinder::CircleFit< T >::RobustFit().
Referenced by kdfinder::TrackCandidate< T >::refit().
template<class T> void kdfinder::TrackCandidate< T >::refit () inline
Definition at line 2370 of file kdfinder.hpp.
View newest version in sPHENIX GitHub at line 2370 of file kdfinder.hpp
References kdfinder::TrackCandidate< T >::mCircle, kdfinder::TrackCandidate< T >::radiusFit(), and kdfinder::TrackCandidate< T >::szFit().
Referenced by kdfinder::get_track_candidates(), and kdfinder::TrackCandidate< T >::mergeCandidate().
template<class T> T kdfinder::TrackCandidate< T >::sign () const inline
Definition at line 2415 of file kdfinder.hpp.
View newest version in sPHENIX GitHub at line 2415 of file kdfinder.hpp
References kdfinder::TrackCandidate< T >::getS(), kdfinder::TrackCandidate< T >::mB, Acts::UnitConstants::s, and Acts::UnitConstants::T.
Referenced by kdfinder::TrackCandidate< T >::approxLength(), and PHTpcTrackFollower::candidate_to_genfit().
template<class T> void kdfinder::TrackCandidate< T >::szFit () inline private
Definition at line 2689 of file kdfinder.hpp.
View newest version in sPHENIX GitHub at line 2689 of file kdfinder.hpp
References kdfinder::TrackCandidate< T >::getS(), i, kdfinder::TrackCandidate< T >::mCircle, kdfinder::TrackCandidate< T >::mHits, kdfinder::TrackCandidate< T >::mLine, kdfinder::LinearFit< T >::RegularFit(), and kdfinder::LinearFit< T >::RobustFit().
Referenced by kdfinder::TrackCandidate< T >::refit().
template<class T> T kdfinder::TrackCandidate< T >::tanl () const inline
Definition at line 2555 of file kdfinder.hpp.
View newest version in sPHENIX GitHub at line 2555 of file kdfinder.hpp
References kdfinder::TrackCandidate< T >::mLine.
template<class T> T kdfinder::TrackCandidate< T >::tanl_err () const inline
Definition at line 2560 of file kdfinder.hpp.
View newest version in sPHENIX GitHub at line 2560 of file kdfinder.hpp
References kdfinder::TrackCandidate< T >::mLine.
Member Data Documentation
template<class T> T kdfinder::TrackCandidate< T >::mB private
Definition at line 2755 of file kdfinder.hpp.
View newest version in sPHENIX GitHub at line 2755 of file kdfinder.hpp
Referenced by kdfinder::TrackCandidate< T >::approxLength(), kdfinder::TrackCandidate< T >::getB(), kdfinder::TrackCandidate< T >::Pt(), and kdfinder::TrackCandidate< T >::sign().
template<class T> Circle<T>* kdfinder::TrackCandidate< T >::mCircle private
Definition at line 2752 of file kdfinder.hpp.
View newest version in sPHENIX GitHub at line 2752 of file kdfinder.hpp
Referenced by kdfinder::TrackCandidate< T >::calcAlpha(), kdfinder::TrackCandidate< T >::deleteHits(), kdfinder::TrackCandidate< T >::distanceToCircle(), kdfinder::TrackCandidate< T >::getCircleFit(), kdfinder::TrackCandidate< T >::getPosForHit(), kdfinder::TrackCandidate< T >::getS(), kdfinder::TrackCandidate< T >::isFitted(), kdfinder::TrackCandidate< T >::print(), kdfinder::TrackCandidate< T >::print_xy(), kdfinder::TrackCandidate< T >::Pt(), kdfinder::TrackCandidate< T >::radius(), kdfinder::TrackCandidate< T >::radius_err(), kdfinder::TrackCandidate< T >::radiusFit(), kdfinder::TrackCandidate< T >::refit(), kdfinder::TrackCandidate< T >::szFit(), and kdfinder::TrackCandidate< T >::~TrackCandidate().
template<class T> std::vector<std::vector<T> > kdfinder::TrackCandidate< T >::mHits private
Definition at line 2754 of file kdfinder.hpp.
View newest version in sPHENIX GitHub at line 2754 of file kdfinder.hpp
Referenced by kdfinder::TrackCandidate< T >::approxLength(), kdfinder::TrackCandidate< T >::calcAlpha(), kdfinder::TrackCandidate< T >::calcMinMaxR(), kdfinder::TrackCandidate< T >::deleteHits(), kdfinder::TrackCandidate< T >::getFirstHit(), kdfinder::TrackCandidate< T >::getHit(), kdfinder::TrackCandidate< T >::getHits(), kdfinder::TrackCandidate< T >::getLastHit(), kdfinder::TrackCandidate< T >::getMomForHit(), kdfinder::TrackCandidate< T >::getS(), kdfinder::TrackCandidate< T >::mergeCandidate(), kdfinder::TrackCandidate< T >::nhits(), kdfinder::TrackCandidate< T >::Pl(), kdfinder::TrackCandidate< T >::print_sz(), kdfinder::TrackCandidate< T >::print_xy(), kdfinder::TrackCandidate< T >::radiusFit(), kdfinder::TrackCandidate< T >::szFit(), kdfinder::TrackCandidate< T >::TrackCandidate(), and kdfinder::TrackCandidate< T >::~TrackCandidate().
template<class T> Line<T>* kdfinder::TrackCandidate< T >::mLine private
Definition at line 2753 of file kdfinder.hpp.
View newest version in sPHENIX GitHub at line 2753 of file kdfinder.hpp
Referenced by kdfinder::TrackCandidate< T >::calcZPosByS(), kdfinder::TrackCandidate< T >::deleteHits(), kdfinder::TrackCandidate< T >::dip(), kdfinder::TrackCandidate< T >::isFitted(), kdfinder::TrackCandidate< T >::Pl(), kdfinder::TrackCandidate< T >::print(), kdfinder::TrackCandidate< T >::szFit(), kdfinder::TrackCandidate< T >::tanl(), kdfinder::TrackCandidate< T >::tanl_err(), and kdfinder::TrackCandidate< T >::~TrackCandidate().
template<class T> T kdfinder::TrackCandidate< T >::mMaxR private
Definition at line 2757 of file kdfinder.hpp.
View newest version in sPHENIX GitHub at line 2757 of file kdfinder.hpp
Referenced by kdfinder::TrackCandidate< T >::calcMinMaxR(), and kdfinder::TrackCandidate< T >::maxR().
template<class T> T kdfinder::TrackCandidate< T >::mMinR private
Definition at line 2756 of file kdfinder.hpp.
View newest version in sPHENIX GitHub at line 2756 of file kdfinder.hpp
Referenced by kdfinder::TrackCandidate< T >::calcMinMaxR(), and kdfinder::TrackCandidate< T >::minR().
The documentation for this class was generated from the following file:
coresoftware/blob/master/offline/packages/PHTpcTracker/externals/kdfinder.hpp