Analysis Software: SubSystem Class Reference
SubSystem Class Reference
#include <OnlMon/blob/main/poms/Poms.h>
Public Member Functions
SubSystem (const char *name, const char *prefix, int loadLibrary=1)
virtual ~SubSystem ()
TList * GetCanvases (int forceReQuery=0)
void PrintCanvasList ()
void ShowCanvases ()
SubSystemAction * AddAction (const char *cmd, const char *description)
SubSystemAction * AddAction (const std::string &cmd, const std::string &description)
SubSystemAction * AddAction (SubSystemAction *action)
void AddDefaultActions ()
void TileCanvases ()
void CascadeCanvases ()
const std::string & GetName ()
const std::string & GetPrefix ()
SubSystemActionList * GetActions ()
int isInitialized ()
void setInitialized (const int i)
Private Attributes
std::string _name
std::string _prefix
TList * _canvasList
SubSystemActionList _actions
int _initialized
Detailed Description
Definition at line 144 of file Poms.h.
View newest version in sPHENIX GitHub at line 144 of file Poms.h
Constructor & Destructor Documentation
SubSystem::SubSystem (const char * name, const char * prefix, int loadLibrary = 1)
Definition at line 428 of file Poms.cc.
View newest version in sPHENIX GitHub at line 428 of file Poms.cc
References _prefix, acts::error, PomsMainFrame::GetMacroPath(), and PomsMainFrame::Instance().
SubSystem::~SubSystem () virtual
Definition at line 451 of file Poms.cc.
View newest version in sPHENIX GitHub at line 451 of file Poms.cc
References _canvasList.
Member Function Documentation
SubSystemAction * SubSystem::AddAction (const char * cmd, const char * description)
Definition at line 534 of file Poms.cc.
View newest version in sPHENIX GitHub at line 534 of file Poms.cc
References _actions, _name, parse_cmake_options::action, POMS_VER, and str.
Referenced by AddAction(), AddDefaultActions(), and StartPoms().
SubSystemAction * SubSystem::AddAction (const std::string & cmd, const std::string & description)
Definition at line 555 of file Poms.cc.
View newest version in sPHENIX GitHub at line 555 of file Poms.cc
References AddAction().
SubSystemAction * SubSystem::AddAction (SubSystemAction * action)
Definition at line 560 of file Poms.cc.
View newest version in sPHENIX GitHub at line 560 of file Poms.cc
References _actions, _name, parse_cmake_options::action, SubSystemAction::GetDescription(), and POMS_VER.
void SubSystem::AddDefaultActions ()
Definition at line 568 of file Poms.cc.
View newest version in sPHENIX GitHub at line 568 of file Poms.cc
References _name, AddAction(), and POMS_VER.
Referenced by PomsMainFrame::RegisterSubSystem().
void SubSystem::CascadeCanvases ()
Definition at line 591 of file Poms.cc.
View newest version in sPHENIX GitHub at line 591 of file Poms.cc
References PomsMainFrame::CascadeCanvases(), GetCanvases(), PomsMainFrame::Instance(), and ShowCanvases().
SubSystemActionList* SubSystem::GetActions () inline
Definition at line 173 of file Poms.h.
View newest version in sPHENIX GitHub at line 173 of file Poms.h
References _actions.
TList * SubSystem::GetCanvases (int forceReQuery = 0)
Definition at line 456 of file Poms.cc.
View newest version in sPHENIX GitHub at line 456 of file Poms.cc
References _canvasList, _name, _prefix, POMS_VER, and prefix.
Referenced by CascadeCanvases(), PrintCanvasList(), ShowCanvases(), and TileCanvases().
const std::string& SubSystem::GetName () inline
Definition at line 171 of file Poms.h.
View newest version in sPHENIX GitHub at line 171 of file Poms.h
References _name.
Referenced by PomsMainFrame::RegisterSubSystem().
const std::string& SubSystem::GetPrefix () inline
Definition at line 172 of file Poms.h.
View newest version in sPHENIX GitHub at line 172 of file Poms.h
References _prefix.
Referenced by SubSystemAction::Execute(), SubSystemActionDraw::Execute(), SubSystemActionSavePlot::Execute(), SubSystemActionDrawPS::Execute(), and SubSystemActionDrawHtml::Execute().
int SubSystem::isInitialized () inline
Definition at line 174 of file Poms.h.
View newest version in sPHENIX GitHub at line 174 of file Poms.h
References _initialized.
Referenced by SubSystemAction::Execute(), and SubSystemActionDraw::Execute().
void SubSystem::PrintCanvasList ()
Definition at line 498 of file Poms.cc.
View newest version in sPHENIX GitHub at line 498 of file Poms.cc
References _name, GetCanvases(), and POMS_VER.
void SubSystem::setInitialized (const int i) inline
Definition at line 175 of file Poms.h.
View newest version in sPHENIX GitHub at line 175 of file Poms.h
References _initialized, and i.
Referenced by SubSystemAction::Execute(), and SubSystemActionDraw::Execute().
void SubSystem::ShowCanvases ()
Definition at line 517 of file Poms.cc.
View newest version in sPHENIX GitHub at line 517 of file Poms.cc
References GetCanvases().
Referenced by CascadeCanvases(), SubSystemActionShowCanvases::Execute(), and TileCanvases().
void SubSystem::TileCanvases ()
Definition at line 584 of file Poms.cc.
View newest version in sPHENIX GitHub at line 584 of file Poms.cc
References GetCanvases(), PomsMainFrame::Instance(), ShowCanvases(), and PomsMainFrame::TileCanvases().
Referenced by SubSystemActionTileCanvases::Execute().
Member Data Documentation
SubSystemActionList SubSystem::_actions private
Definition at line 150 of file Poms.h.
View newest version in sPHENIX GitHub at line 150 of file Poms.h
Referenced by AddAction(), and GetActions().
TList* SubSystem::_canvasList private
Definition at line 149 of file Poms.h.
View newest version in sPHENIX GitHub at line 149 of file Poms.h
Referenced by GetCanvases(), and ~SubSystem().
int SubSystem::_initialized private
Definition at line 151 of file Poms.h.
View newest version in sPHENIX GitHub at line 151 of file Poms.h
Referenced by isInitialized(), and setInitialized().
std::string SubSystem::_name private
Definition at line 147 of file Poms.h.
View newest version in sPHENIX GitHub at line 147 of file Poms.h
Referenced by AddAction(), AddDefaultActions(), GetCanvases(), GetName(), and PrintCanvasList().
std::string SubSystem::_prefix private
Definition at line 148 of file Poms.h.
View newest version in sPHENIX GitHub at line 148 of file Poms.h
Referenced by GetCanvases(), GetPrefix(), and SubSystem().
The documentation for this class was generated from the following files:
OnlMon/blob/main/poms/Poms.h
OnlMon/blob/main/poms/Poms.cc