Analysis Software: TrackSeed Class Reference
TrackSeed Class Reference
#include <coresoftware/blob/master/offline/packages/trackbase_historic/TrackSeed.h>
Public Types
typedef std::set
< TrkrDefs::cluskey > ClusterKeySet
typedef
ClusterKeySet::const_iterator ConstClusterKeyIter
typedef ClusterKeySet::iterator ClusterKeyIter
typedef std::map< int,
std::set< PHG4HitDefs::keytype > > HitIdMap
typedef HitIdMap::iterator HitIdIter
typedef HitIdMap::const_iterator HitIdConstIter
Public Member Functions
~TrackSeed () override=default
void identify (std::ostream &os=std::cout) const override
int isValid () const override
isValid returns non zero if object contains vailid data
PHObject * CloneMe () const override
Virtual copy constructor.
virtual void CopyFrom (const TrackSeed &)
virtual void CopyFrom (TrackSeed *)
virtual int get_charge () const
virtual float get_px (TrkrClusterContainer *, ActsGeometry *) const
We need access to the first two clusters to get the phi angle right.
virtual float get_py (TrkrClusterContainer *, ActsGeometry *) const
virtual float get_phi (TrkrClusterContainer *, ActsGeometry *) const
virtual float get_phi (std::map< TrkrDefs::cluskey, Acts::Vector3 > &) const
virtual float get_pz () const
virtual float get_x () const
virtual float get_y () const
virtual float get_z () const
virtual float get_qOverR () const
virtual float get_X0 () const
virtual float get_Y0 () const
virtual float get_slope () const
virtual float get_Z0 () const
virtual float get_eta () const
virtual float get_theta () const
virtual float get_pt () const
virtual float get_p () const
virtual short int get_crossing () const
virtual void set_crossing (const short int)
virtual void set_qOverR (const float)
virtual void set_X0 (const float)
virtual void set_Y0 (const float)
virtual void set_slope (const float)
virtual void set_Z0 (const float)
virtual void circleFitByTaubin (TrkrClusterContainer *, ActsGeometry *, uint8_t, uint8_t)
virtual void lineFit (TrkrClusterContainer *, ActsGeometry *, uint8_t, uint8_t)
virtual void circleFitByTaubin (std::map< TrkrDefs::cluskey, Acts::Vector3 > &, uint8_t, uint8_t)
virtual void lineFit (std::map< TrkrDefs::cluskey, Acts::Vector3 > &, uint8_t, uint8_t)
virtual void clear_cluster_keys ()
virtual bool empty_cluster_keys () const
virtual size_t size_cluster_keys () const
virtual void insert_cluster_key (TrkrDefs::cluskey)
virtual size_t erase_cluster_key (TrkrDefs::cluskey)
virtual ConstClusterKeyIter find_cluster_key (TrkrDefs::cluskey) const
virtual ConstClusterKeyIter begin_cluster_keys () const
virtual ConstClusterKeyIter end_cluster_keys () const
virtual ClusterKeyIter begin_cluster_keys ()
virtual ClusterKeyIter find_cluster_keys (unsigned int)
virtual ClusterKeyIter end_cluster_keys ()
virtual void set_silicon_seed_index (const unsigned int)
virtual void set_tpc_seed_index (const unsigned int)
virtual unsigned int get_silicon_seed_index () const
virtual unsigned int get_tpc_seed_index () const
virtual void set_crossing_estimate (const short int)
virtual short int get_crossing_estimate () const
virtual unsigned int get_truth_track_id () const
virtual void set_truth_track_id (unsigned int)
virtual void set_num_measurements (int)
virtual unsigned int get_num_measurements () const
virtual bool empty_g4hit_id () const
virtual size_t size_g4hit_id () const
virtual void add_g4hit_id (int, PHG4HitDefs::keytype)
virtual HitIdIter begin_g4hit_id ()
virtual HitIdConstIter begin_g4hit_id () const
virtual HitIdIter find_g4hit_id (int)
virtual HitIdConstIter find_g4hit_id (int) const
virtual HitIdIter end_g4hit_id ()
virtual HitIdConstIter end_g4hit_id () const
virtual size_t remove_g4hit_id (int, PHG4HitDefs::keytype)
virtual size_t remove_g4hit_volume (int)
virtual void clear_g4hit_id ()
virtual const HitIdMap & g4hit_ids () const
Public Member Functions inherited from PHObject
PHObject ()
ctor
~PHObject () override
dtor
virtual PHObject * clone () const final
PHObject * Clone (const char *newname="") const final
void Copy (TObject &object) const final
virtual void Reset ()
Clear Event.
virtual int Integrate () const
virtual int Integrate (PHObject *)
virtual void CopyFrom (const PHObject *obj)
Protected Member Functions
TrackSeed ()
ClassDefOverride (TrackSeed, 1)
Detailed Description
Definition at line 17 of file TrackSeed.h.
View newest version in sPHENIX GitHub at line 17 of file TrackSeed.h
Member Typedef Documentation
typedef ClusterKeySet::iterator TrackSeed::ClusterKeyIter
Definition at line 22 of file TrackSeed.h.
View newest version in sPHENIX GitHub at line 22 of file TrackSeed.h
typedef std::set<TrkrDefs::cluskey> TrackSeed::ClusterKeySet
Definition at line 20 of file TrackSeed.h.
View newest version in sPHENIX GitHub at line 20 of file TrackSeed.h
typedef ClusterKeySet::const_iterator TrackSeed::ConstClusterKeyIter
Definition at line 21 of file TrackSeed.h.
View newest version in sPHENIX GitHub at line 21 of file TrackSeed.h
typedef HitIdMap::const_iterator TrackSeed::HitIdConstIter
Definition at line 110 of file TrackSeed.h.
View newest version in sPHENIX GitHub at line 110 of file TrackSeed.h
typedef HitIdMap::iterator TrackSeed::HitIdIter
Definition at line 109 of file TrackSeed.h.
View newest version in sPHENIX GitHub at line 109 of file TrackSeed.h
typedef std::map<int, std::set<PHG4HitDefs::keytype> > TrackSeed::HitIdMap
Definition at line 108 of file TrackSeed.h.
View newest version in sPHENIX GitHub at line 108 of file TrackSeed.h
Constructor & Destructor Documentation
TrackSeed::~TrackSeed () override default
TrackSeed::TrackSeed () inline protected
Definition at line 132 of file TrackSeed.h.
View newest version in sPHENIX GitHub at line 132 of file TrackSeed.h
Member Function Documentation
virtual void TrackSeed::add_g4hit_id (int , PHG4HitDefs::keytype) inline virtual
Reimplemented in TrackSeed_FastSim_v1.
Definition at line 118 of file TrackSeed.h.
View newest version in sPHENIX GitHub at line 118 of file TrackSeed.h
TrackSeed::ConstClusterKeyIter TrackSeed::begin_cluster_keys () const virtual
Reimplemented in TrackSeed_v1.
Definition at line 11 of file TrackSeed.cc.
View newest version in sPHENIX GitHub at line 11 of file TrackSeed.cc
References dummyKeySet.
Referenced by TrackingIterationCounter::addClustersToIterationMap(), PHCosmicSeedCombiner::addKeys(), PHCosmicTrackMerger::addKeys(), TrackSeedTrackMapConverter::addKeys(), PHGhostRejection::checkClusterSharing(), PHSimpleVertexFinder::checkDCAs(), TrackSeed_v1::CopyFrom(), DSTTrackInfoWriter::evaluate_track_info(), TrkrNtuplizer::fillOutputNtuples(), SvtxEvaluator::fillOutputNtuples(), TrkrNtuplizer::get_track_ckeys(), SvtxTrackEval::get_track_ckeys(), PHSiliconTpcTrackMatching::getBunchCrossing(), PHCosmicsTrkFitter::getCharge(), TrackSeedTrackMapConverter::getCosmicCharge(), PHTruthSiliconAssociation::getG4PrimaryParticle(), PHCosmicTrackMerger::getGlobalPositions(), PHSiliconTpcTrackMatching::getInttCrossings(), PHTruthSiliconAssociation::getInttCrossings(), PHTruthTrackSeeding::getInttCrossings(), MakeSourceLinks::getSourceLinks(), HelicalFitter::getTrackletClusterList(), SvtxTrack_v4::identify(), KFParticle_Tools::makeAllDaughterParticles(), PHActsSiliconSeeding::matchInttClusters(), PHSiliconHelicalPropagator::process_event(), PHSiliconSeedMerger::process_event(), FilterEvents::process_event(), FilterEventsUpsilon::process_event(), QAG4SimulationVertex::process_event(), BJetModule::process_event(), QAG4SimulationTracking::process_event(), PHSimpleKFProp::process_event(), PHTpcDeltaZCorrection::process_track(), and PHSimpleKFProp::PropagateTrack().
TrackSeed::ClusterKeyIter TrackSeed::begin_cluster_keys () virtual
Reimplemented in TrackSeed_v1.
Definition at line 22 of file TrackSeed.cc.
View newest version in sPHENIX GitHub at line 22 of file TrackSeed.cc
References dummyKeySet.
TrackSeed::HitIdIter TrackSeed::begin_g4hit_id () virtual
Reimplemented in TrackSeed_FastSim_v1.
Definition at line 53 of file TrackSeed.cc.
View newest version in sPHENIX GitHub at line 53 of file TrackSeed.cc
References dummyHitIdMap.
TrackSeed::HitIdConstIter TrackSeed::begin_g4hit_id () const virtual
Reimplemented in TrackSeed_FastSim_v1.
Definition at line 37 of file TrackSeed.cc.
View newest version in sPHENIX GitHub at line 37 of file TrackSeed.cc
References dummyHitIdMap.
virtual void TrackSeed::circleFitByTaubin (TrkrClusterContainer * , ActsGeometry * , uint8_t , uint8_t) inline virtual
Reimplemented in TrackSeed_v1.
Definition at line 70 of file TrackSeed.h.
View newest version in sPHENIX GitHub at line 70 of file TrackSeed.h
Referenced by TrackSeedTrackMapConverter::process_event(), PHTpcTrackSeedCircleFit::process_event(), and PHSimpleKFProp::process_event().
virtual void TrackSeed::circleFitByTaubin (std::map< TrkrDefs::cluskey, Acts::Vector3 > & , uint8_t , uint8_t) inline virtual
In case the global cluster positions have already been obtained, these can be called to avoid performing transformations twice
Reimplemented in TrackSeed_v1.
Definition at line 79 of file TrackSeed.h.
View newest version in sPHENIX GitHub at line 79 of file TrackSeed.h
TrackSeed::ClassDefOverride (TrackSeed , 1) protected
virtual void TrackSeed::clear_cluster_keys () inline virtual
Reimplemented in TrackSeed_v1.
Definition at line 84 of file TrackSeed.h.
View newest version in sPHENIX GitHub at line 84 of file TrackSeed.h
virtual void TrackSeed::clear_g4hit_id () inline virtual
Reimplemented in TrackSeed_FastSim_v1.
Definition at line 127 of file TrackSeed.h.
View newest version in sPHENIX GitHub at line 127 of file TrackSeed.h
PHObject* TrackSeed::CloneMe () const inline override virtual
Virtual copy constructor.
Reimplemented from PHObject.
Reimplemented in TrackSeed_v1, and TrackSeed_FastSim_v1.
Definition at line 32 of file TrackSeed.h.
View newest version in sPHENIX GitHub at line 32 of file TrackSeed.h
Referenced by TrackSeedContainer_v1::insert(), FilterEvents::process_event(), and FilterEventsUpsilon::process_event().
virtual void TrackSeed::CopyFrom (const TrackSeed &) inline virtual
Reimplemented in TrackSeed_v1, SvtxTrackSeed_v1, SvtxTrackSeed_v2, and TrackSeed_FastSim_v1.
Definition at line 35 of file TrackSeed.h.
View newest version in sPHENIX GitHub at line 35 of file TrackSeed.h
Referenced by SvtxTrackSeed_v1::CopyFrom(), SvtxTrackSeed_v2::CopyFrom(), and TrackSeed_v1::CopyFrom().
virtual void TrackSeed::CopyFrom (TrackSeed *) inline virtual
Reimplemented in TrackSeed_v1, SvtxTrackSeed_v1, SvtxTrackSeed_v2, and TrackSeed_FastSim_v1.
Definition at line 37 of file TrackSeed.h.
View newest version in sPHENIX GitHub at line 37 of file TrackSeed.h
virtual bool TrackSeed::empty_cluster_keys () const inline virtual
Reimplemented in TrackSeed_v1.
Definition at line 85 of file TrackSeed.h.
View newest version in sPHENIX GitHub at line 85 of file TrackSeed.h
virtual bool TrackSeed::empty_g4hit_id () const inline virtual
Reimplemented in TrackSeed_FastSim_v1.
Definition at line 116 of file TrackSeed.h.
View newest version in sPHENIX GitHub at line 116 of file TrackSeed.h
TrackSeed::ConstClusterKeyIter TrackSeed::end_cluster_keys () const virtual
Reimplemented in TrackSeed_v1.
Definition at line 16 of file TrackSeed.cc.
View newest version in sPHENIX GitHub at line 16 of file TrackSeed.cc
References dummyKeySet.
Referenced by TrackingIterationCounter::addClustersToIterationMap(), PHCosmicSeedCombiner::addKeys(), PHCosmicTrackMerger::addKeys(), TrackSeedTrackMapConverter::addKeys(), PHGhostRejection::checkClusterSharing(), PHSimpleVertexFinder::checkDCAs(), TrackSeed_v1::CopyFrom(), DSTTrackInfoWriter::evaluate_track_info(), TrkrNtuplizer::fillOutputNtuples(), SvtxEvaluator::fillOutputNtuples(), TrkrNtuplizer::get_track_ckeys(), SvtxTrackEval::get_track_ckeys(), PHSiliconTpcTrackMatching::getBunchCrossing(), PHCosmicsTrkFitter::getCharge(), TrackSeedTrackMapConverter::getCosmicCharge(), PHTruthSiliconAssociation::getG4PrimaryParticle(), PHCosmicTrackMerger::getGlobalPositions(), PHSiliconTpcTrackMatching::getInttCrossings(), PHTruthSiliconAssociation::getInttCrossings(), PHTruthTrackSeeding::getInttCrossings(), MakeSourceLinks::getSourceLinks(), HelicalFitter::getTrackletClusterList(), SvtxTrack_v4::identify(), KFParticle_Tools::makeAllDaughterParticles(), PHActsSiliconSeeding::matchInttClusters(), PHSiliconHelicalPropagator::process_event(), PHSiliconSeedMerger::process_event(), FilterEvents::process_event(), FilterEventsUpsilon::process_event(), QAG4SimulationVertex::process_event(), BJetModule::process_event(), QAG4SimulationTracking::process_event(), PHSimpleKFProp::process_event(), PHTpcDeltaZCorrection::process_track(), and PHSimpleKFProp::PropagateTrack().
TrackSeed::ClusterKeyIter TrackSeed::end_cluster_keys () virtual
Reimplemented in TrackSeed_v1.
Definition at line 32 of file TrackSeed.cc.
View newest version in sPHENIX GitHub at line 32 of file TrackSeed.cc
References dummyKeySet.
TrackSeed::HitIdIter TrackSeed::end_g4hit_id () virtual
Reimplemented in TrackSeed_FastSim_v1.
Definition at line 63 of file TrackSeed.cc.
View newest version in sPHENIX GitHub at line 63 of file TrackSeed.cc
References dummyHitIdMap.
TrackSeed::HitIdConstIter TrackSeed::end_g4hit_id () const virtual
Reimplemented in TrackSeed_FastSim_v1.
Definition at line 47 of file TrackSeed.cc.
View newest version in sPHENIX GitHub at line 47 of file TrackSeed.cc
References dummyHitIdMap.
virtual size_t TrackSeed::erase_cluster_key (TrkrDefs::cluskey) inline virtual
Reimplemented in TrackSeed_v1.
Definition at line 88 of file TrackSeed.h.
View newest version in sPHENIX GitHub at line 88 of file TrackSeed.h
Referenced by PHCosmicTrackMerger::removeOutliers().
TrackSeed::ConstClusterKeyIter TrackSeed::find_cluster_key (TrkrDefs::cluskey) const virtual
Reimplemented in TrackSeed_v1.
Definition at line 6 of file TrackSeed.cc.
View newest version in sPHENIX GitHub at line 6 of file TrackSeed.cc
References dummyKeySet.
TrackSeed::ClusterKeyIter TrackSeed::find_cluster_keys (unsigned int) virtual
Reimplemented in TrackSeed_v1.
Definition at line 27 of file TrackSeed.cc.
View newest version in sPHENIX GitHub at line 27 of file TrackSeed.cc
References dummyKeySet.
TrackSeed::HitIdIter TrackSeed::find_g4hit_id (int) virtual
Reimplemented in TrackSeed_FastSim_v1.
Definition at line 58 of file TrackSeed.cc.
View newest version in sPHENIX GitHub at line 58 of file TrackSeed.cc
References dummyHitIdMap.
TrackSeed::HitIdConstIter TrackSeed::find_g4hit_id (int) const virtual
Reimplemented in TrackSeed_FastSim_v1.
Definition at line 42 of file TrackSeed.cc.
View newest version in sPHENIX GitHub at line 42 of file TrackSeed.cc
References dummyHitIdMap.
const TrackSeed::HitIdMap & TrackSeed::g4hit_ids () const virtual
Reimplemented in TrackSeed_FastSim_v1.
Definition at line 68 of file TrackSeed.cc.
View newest version in sPHENIX GitHub at line 68 of file TrackSeed.cc
References dummyHitIdMap.
Referenced by TrackSeed_FastSim_v1::CopyFrom().
virtual int TrackSeed::get_charge () const inline virtual
Reimplemented in TrackSeed_v1.
Definition at line 39 of file TrackSeed.h.
View newest version in sPHENIX GitHub at line 39 of file TrackSeed.h
Referenced by HelicalFitter::process_event(), PHTpcDeltaZCorrection::process_track(), and PHSimpleKFProp::PropagateTrack().
virtual short int TrackSeed::get_crossing () const inline virtual
Reimplemented in TrackSeed_v1.
Definition at line 61 of file TrackSeed.h.
View newest version in sPHENIX GitHub at line 61 of file TrackSeed.h
Referenced by PHSiliconTpcTrackMatching::checkCrossingMatches(), TrackSeed_v1::CopyFrom(), helixResiduals::fill_residuals(), ActsAlignmentStates::fillAlignmentStateMap(), PHSiliconTpcTrackMatching::findCrossingGeometrically(), PHSiliconTpcTrackMatching::findEtaPhiMatches(), PHActsTrkFitter::loopTracks(), PHMicromegasTpcTrackMatching::process_event(), PHActsGSF::process_event(), HelicalFitter::process_event(), and PHGenFitTrkFitter::process_event().
virtual short int TrackSeed::get_crossing_estimate () const inline virtual
Reimplemented in SvtxTrackSeed_v2.
Definition at line 102 of file TrackSeed.h.
View newest version in sPHENIX GitHub at line 102 of file TrackSeed.h
Referenced by SvtxTrackSeed_v2::CopyFrom(), and PHActsTrkFitter::loopTracks().
virtual float TrackSeed::get_eta () const inline virtual
Reimplemented in TrackSeed_v1.
Definition at line 57 of file TrackSeed.h.
View newest version in sPHENIX GitHub at line 57 of file TrackSeed.h
Referenced by PHSiliconTpcTrackMatching::checkCrossingMatches(), TrkrNtuplizer::fillOutputNtuples(), PHSiliconTpcTrackMatching::findEtaPhiMatches(), PHSiliconTpcTrackMatching::getInttCrossings(), TrackSeedTrackMapConverter::process_event(), PHTpcTrackSeedCircleFit::process_event(), PHSiliconTpcTrackMatching::process_event(), PHSimpleKFProp::PropagateTrack(), and PHGhostRejection::rejectGhostTracks().
virtual unsigned int TrackSeed::get_num_measurements () const inline virtual
Reimplemented in TrackSeed_FastSim_v1.
Definition at line 115 of file TrackSeed.h.
View newest version in sPHENIX GitHub at line 115 of file TrackSeed.h
Referenced by TrackSeed_FastSim_v1::CopyFrom().
virtual float TrackSeed::get_p () const inline virtual
Reimplemented in TrackSeed_v1.
Definition at line 60 of file TrackSeed.h.
View newest version in sPHENIX GitHub at line 60 of file TrackSeed.h
Referenced by TrackSeedTrackMapConverter::process_event(), and PHTpcTrackSeedCircleFit::process_event().
virtual float TrackSeed::get_phi (TrkrClusterContainer * , ActsGeometry *) const inline virtual
Reimplemented in TrackSeed_FastSim_v1, and TrackSeed_v1.
Definition at line 45 of file TrackSeed.h.
View newest version in sPHENIX GitHub at line 45 of file TrackSeed.h
Referenced by TrkrNtuplizer::fillOutputNtuples(), SvtxEvaluator::fillOutputNtuples(), PHSiliconTpcTrackMatching::findEtaPhiMatches(), PHCosmicSeedCombiner::process_event(), TrackSeedTrackMapConverter::process_event(), PHTpcTrackSeedCircleFit::process_event(), PHSimpleKFProp::PropagateTrack(), and PHGhostRejection::rejectGhostTracks().
virtual float TrackSeed::get_phi (std::map< TrkrDefs::cluskey, Acts::Vector3 > &) const inline virtual
Reimplemented in TrackSeed_v1.
Definition at line 47 of file TrackSeed.h.
View newest version in sPHENIX GitHub at line 47 of file TrackSeed.h
virtual float TrackSeed::get_pt () const inline virtual
Reimplemented in TrackSeed_v1.
Definition at line 59 of file TrackSeed.h.
View newest version in sPHENIX GitHub at line 59 of file TrackSeed.h
Referenced by helixResiduals::fill_residuals(), TrkrNtuplizer::fillOutputNtuples(), PHSiliconTpcTrackMatching::findEtaPhiMatches(), FilterEventsUpsilon::process_event(), FilterEvents::process_event(), PHTpcTrackSeedCircleFit::process_event(), and PHSiliconTpcTrackMatching::process_event().
virtual float TrackSeed::get_px (TrkrClusterContainer * , ActsGeometry *) const inline virtual
We need access to the first two clusters to get the phi angle right.
Reimplemented in TrackSeed_v1.
Definition at line 41 of file TrackSeed.h.
View newest version in sPHENIX GitHub at line 41 of file TrackSeed.h
Referenced by helixResiduals::fill_residuals(), TrackSeedTrackMapConverter::process_event(), and PHSimpleKFProp::PropagateTrack().
virtual float TrackSeed::get_py (TrkrClusterContainer * , ActsGeometry *) const inline virtual
Reimplemented in TrackSeed_v1.
Definition at line 43 of file TrackSeed.h.
View newest version in sPHENIX GitHub at line 43 of file TrackSeed.h
Referenced by helixResiduals::fill_residuals(), TrackSeedTrackMapConverter::process_event(), and PHSimpleKFProp::PropagateTrack().
virtual float TrackSeed::get_pz () const inline virtual
Reimplemented in TrackSeed_v1.
Definition at line 48 of file TrackSeed.h.
View newest version in sPHENIX GitHub at line 48 of file TrackSeed.h
Referenced by helixResiduals::fill_residuals(), TrackSeedTrackMapConverter::process_event(), and PHSimpleKFProp::PropagateTrack().
virtual float TrackSeed::get_qOverR () const inline virtual
Reimplemented in TrackSeed_v1.
Definition at line 52 of file TrackSeed.h.
View newest version in sPHENIX GitHub at line 52 of file TrackSeed.h
Referenced by TrackSeed_v1::CopyFrom(), TrackEvaluation::create_cluster(), TrkrNtuplizer::fillOutputNtuples(), SvtxEvaluator::fillOutputNtuples(), PHSiliconTpcTrackMatching::findEtaPhiMatches(), PHActsKDTreeSeeding::findInttMatches(), PHActsSiliconSeeding::findInttMatches(), TrackSeedTrackMapConverter::process_event(), PHTpcDeltaZCorrection::process_track(), and PHSimpleKFProp::PropagateTrack().
virtual unsigned int TrackSeed::get_silicon_seed_index () const inline virtual
Reimplemented in SvtxTrackSeed_v1, and SvtxTrackSeed_v2.
Definition at line 98 of file TrackSeed.h.
View newest version in sPHENIX GitHub at line 98 of file TrackSeed.h
Referenced by SvtxTrackSeed_v1::CopyFrom(), SvtxTrackSeed_v2::CopyFrom(), TrkrNtuplizer::fillOutputNtuples(), ActsEvaluator::fillProtoTrack(), PHCosmicsTrkFitter::loopTracks(), PHActsTrkFitter::loopTracks(), PHCosmicSeedCombiner::process_event(), PHTruthSiliconAssociation::process_event(), and PHGenFitTrkFitter::process_event().
virtual float TrackSeed::get_slope () const inline virtual
Reimplemented in TrackSeed_v1.
Definition at line 55 of file TrackSeed.h.
View newest version in sPHENIX GitHub at line 55 of file TrackSeed.h
Referenced by TrackSeed_v1::CopyFrom(), TrackEvaluation::create_cluster(), PHActsKDTreeSeeding::findInttMatches(), PHActsSiliconSeeding::findInttMatches(), and TrackSeedTrackMapConverter::process_event().
virtual float TrackSeed::get_theta () const inline virtual
Reimplemented in TrackSeed_v1.
Definition at line 58 of file TrackSeed.h.
View newest version in sPHENIX GitHub at line 58 of file TrackSeed.h
Referenced by SvtxEvaluator::fillOutputNtuples(), TrackSeedTrackMapConverter::process_event(), and PHSimpleKFProp::PropagateTrack().
virtual unsigned int TrackSeed::get_tpc_seed_index () const inline virtual
Reimplemented in SvtxTrackSeed_v1, and SvtxTrackSeed_v2.
Definition at line 99 of file TrackSeed.h.
View newest version in sPHENIX GitHub at line 99 of file TrackSeed.h
Referenced by SvtxTrackSeed_v1::CopyFrom(), SvtxTrackSeed_v2::CopyFrom(), ActsEvaluator::evaluateTrackFit(), TrkrNtuplizer::fillOutputNtuples(), ActsEvaluator::fillProtoTrack(), PHCosmicsTrkFitter::loopTracks(), PHActsTrkFitter::loopTracks(), PHCosmicSeedCombiner::process_event(), TrackSeedTrackMapConverter::process_event(), PHTruthSiliconAssociation::process_event(), and PHGenFitTrkFitter::process_event().
virtual unsigned int TrackSeed::get_truth_track_id () const inline virtual
Reimplemented in TrackSeed_FastSim_v1.
Definition at line 112 of file TrackSeed.h.
View newest version in sPHENIX GitHub at line 112 of file TrackSeed.h
Referenced by TrackSeed_FastSim_v1::CopyFrom().
virtual float TrackSeed::get_x () const inline virtual
Reimplemented in TrackSeed_v1.
Definition at line 49 of file TrackSeed.h.
View newest version in sPHENIX GitHub at line 49 of file TrackSeed.h
Referenced by PHSiliconTpcTrackMatching::findEtaPhiMatches(), PHCosmicsTrkFitter::loopTracks(), PHActsTrkFitter::loopTracks(), TrackSeedTrackMapConverter::process_event(), PHTpcDeltaZCorrection::process_track(), PHSimpleKFProp::PropagateTrack(), and PHGhostRejection::rejectGhostTracks().
virtual float TrackSeed::get_X0 () const inline virtual
Reimplemented in TrackSeed_v1.
Definition at line 53 of file TrackSeed.h.
View newest version in sPHENIX GitHub at line 53 of file TrackSeed.h
Referenced by TrackSeed_v1::CopyFrom(), TrkrNtuplizer::fillOutputNtuples(), SvtxEvaluator::fillOutputNtuples(), PHActsKDTreeSeeding::findInttMatches(), PHActsSiliconSeeding::findInttMatches(), TrackSeedTrackMapConverter::process_event(), PHTpcDeltaZCorrection::process_track(), and PHSimpleKFProp::PropagateTrack().
virtual float TrackSeed::get_y () const inline virtual
Reimplemented in TrackSeed_v1.
Definition at line 50 of file TrackSeed.h.
View newest version in sPHENIX GitHub at line 50 of file TrackSeed.h
Referenced by PHSiliconTpcTrackMatching::findEtaPhiMatches(), TrackSeedTrackMapConverter::process_event(), PHTpcDeltaZCorrection::process_track(), PHSimpleKFProp::PropagateTrack(), and PHGhostRejection::rejectGhostTracks().
virtual float TrackSeed::get_Y0 () const inline virtual
Reimplemented in TrackSeed_v1.
Definition at line 54 of file TrackSeed.h.
View newest version in sPHENIX GitHub at line 54 of file TrackSeed.h
Referenced by TrackSeed_v1::CopyFrom(), TrkrNtuplizer::fillOutputNtuples(), SvtxEvaluator::fillOutputNtuples(), PHActsKDTreeSeeding::findInttMatches(), PHActsSiliconSeeding::findInttMatches(), TrackSeedTrackMapConverter::process_event(), PHTpcDeltaZCorrection::process_track(), and PHSimpleKFProp::PropagateTrack().
virtual float TrackSeed::get_z () const inline virtual
Reimplemented in TrackSeed_v1.
Definition at line 51 of file TrackSeed.h.
View newest version in sPHENIX GitHub at line 51 of file TrackSeed.h
Referenced by PHSiliconTpcTrackMatching::checkCrossingMatches(), PHSiliconTpcTrackMatching::findCrossingGeometrically(), PHSiliconTpcTrackMatching::findEtaPhiMatches(), TrackSeedTrackMapConverter::process_event(), PHSiliconTpcTrackMatching::process_event(), PHTpcDeltaZCorrection::process_track(), PHSimpleKFProp::PropagateTrack(), and PHGhostRejection::rejectGhostTracks().
virtual float TrackSeed::get_Z0 () const inline virtual
Reimplemented in TrackSeed_v1.
Definition at line 56 of file TrackSeed.h.
View newest version in sPHENIX GitHub at line 56 of file TrackSeed.h
Referenced by TrackSeed_v1::CopyFrom(), TrkrNtuplizer::fillOutputNtuples(), PHActsKDTreeSeeding::findInttMatches(), PHActsSiliconSeeding::findInttMatches(), and TrackSeedTrackMapConverter::process_event().
void TrackSeed::identify (std::ostream & os = std::cout) const inline override virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from PHObject.
Reimplemented in TrackSeed_v1, and TrackSeed_FastSim_v1.
Definition at line 26 of file TrackSeed.h.
View newest version in sPHENIX GitHub at line 26 of file TrackSeed.h
References os.
Referenced by PHSiliconTpcTrackMatching::findEtaPhiMatches(), PHTruthTrackSeeding::Process(), PHCosmicSeedCombiner::process_event(), PHSiliconSeedMerger::process_event(), PHCosmicTrackMerger::process_event(), and PHTruthSiliconAssociation::process_event().
virtual void TrackSeed::insert_cluster_key (TrkrDefs::cluskey) inline virtual
Reimplemented in TrackSeed_v1.
Definition at line 87 of file TrackSeed.h.
View newest version in sPHENIX GitHub at line 87 of file TrackSeed.h
Referenced by PHCosmicSeedCombiner::addKeys(), PHCosmicTrackMerger::addKeys(), and TrackSeedTrackMapConverter::addKeys().
int TrackSeed::isValid () const inline override virtual
isValid returns non zero if object contains vailid data
Reimplemented from PHObject.
Reimplemented in TrackSeed_v1, and TrackSeed_FastSim_v1.
Definition at line 31 of file TrackSeed.h.
View newest version in sPHENIX GitHub at line 31 of file TrackSeed.h
virtual void TrackSeed::lineFit (TrkrClusterContainer * , ActsGeometry * , uint8_t , uint8_t) inline virtual
Reimplemented in TrackSeed_v1.
Definition at line 73 of file TrackSeed.h.
View newest version in sPHENIX GitHub at line 73 of file TrackSeed.h
Referenced by PHTpcTrackSeedCircleFit::process_event(), and PHSimpleKFProp::process_event().
virtual void TrackSeed::lineFit (std::map< TrkrDefs::cluskey, Acts::Vector3 > & , uint8_t , uint8_t) inline virtual
Reimplemented in TrackSeed_v1.
Definition at line 81 of file TrackSeed.h.
View newest version in sPHENIX GitHub at line 81 of file TrackSeed.h
virtual size_t TrackSeed::remove_g4hit_id (int , PHG4HitDefs::keytype) inline virtual
Reimplemented in TrackSeed_FastSim_v1.
Definition at line 125 of file TrackSeed.h.
View newest version in sPHENIX GitHub at line 125 of file TrackSeed.h
virtual size_t TrackSeed::remove_g4hit_volume (int) inline virtual
Reimplemented in TrackSeed_FastSim_v1.
Definition at line 126 of file TrackSeed.h.
View newest version in sPHENIX GitHub at line 126 of file TrackSeed.h
virtual void TrackSeed::set_crossing (const short int) inline virtual
Reimplemented in TrackSeed_v1.
Definition at line 63 of file TrackSeed.h.
View newest version in sPHENIX GitHub at line 63 of file TrackSeed.h
Referenced by PHSiliconTpcTrackMatching::process_event(), and PHGenFitTrkFitter::process_event().
virtual void TrackSeed::set_crossing_estimate (const short int) inline virtual
Reimplemented in SvtxTrackSeed_v2.
Definition at line 101 of file TrackSeed.h.
View newest version in sPHENIX GitHub at line 101 of file TrackSeed.h
virtual void TrackSeed::set_num_measurements (int) inline virtual
Reimplemented in TrackSeed_FastSim_v1.
Definition at line 114 of file TrackSeed.h.
View newest version in sPHENIX GitHub at line 114 of file TrackSeed.h
virtual void TrackSeed::set_qOverR (const float) inline virtual
Reimplemented in TrackSeed_v1.
Definition at line 64 of file TrackSeed.h.
View newest version in sPHENIX GitHub at line 64 of file TrackSeed.h
virtual void TrackSeed::set_silicon_seed_index (const unsigned int) inline virtual
Reimplemented in SvtxTrackSeed_v2, and SvtxTrackSeed_v1.
Definition at line 96 of file TrackSeed.h.
View newest version in sPHENIX GitHub at line 96 of file TrackSeed.h
Referenced by PHCosmicSeedCombiner::process_event().
virtual void TrackSeed::set_slope (const float) inline virtual
Reimplemented in TrackSeed_v1.
Definition at line 67 of file TrackSeed.h.
View newest version in sPHENIX GitHub at line 67 of file TrackSeed.h
virtual void TrackSeed::set_tpc_seed_index (const unsigned int) inline virtual
Reimplemented in SvtxTrackSeed_v2, and SvtxTrackSeed_v1.
Definition at line 97 of file TrackSeed.h.
View newest version in sPHENIX GitHub at line 97 of file TrackSeed.h
virtual void TrackSeed::set_truth_track_id (unsigned int) inline virtual
Reimplemented in TrackSeed_FastSim_v1.
Definition at line 113 of file TrackSeed.h.
View newest version in sPHENIX GitHub at line 113 of file TrackSeed.h
virtual void TrackSeed::set_X0 (const float) inline virtual
Reimplemented in TrackSeed_v1.
Definition at line 65 of file TrackSeed.h.
View newest version in sPHENIX GitHub at line 65 of file TrackSeed.h
virtual void TrackSeed::set_Y0 (const float) inline virtual
Reimplemented in TrackSeed_v1.
Definition at line 66 of file TrackSeed.h.
View newest version in sPHENIX GitHub at line 66 of file TrackSeed.h
virtual void TrackSeed::set_Z0 (const float) inline virtual
Reimplemented in TrackSeed_v1.
Definition at line 68 of file TrackSeed.h.
View newest version in sPHENIX GitHub at line 68 of file TrackSeed.h
virtual size_t TrackSeed::size_cluster_keys () const inline virtual
Reimplemented in TrackSeed_v1.
Definition at line 86 of file TrackSeed.h.
View newest version in sPHENIX GitHub at line 86 of file TrackSeed.h
Referenced by helixResiduals::fill_residuals(), KshortReconstruction::fillNtp(), SecondaryVertexFinder::fillNtp(), TrkrNtuplizer::fillOutputNtuples(), SvtxEvaluator::fillOutputNtuples(), HFTrackEfficiency::findTracks(), IsolatedTrackAnalysis::getTracks(), SecondaryVertexFinder::outputTrackDetails(), SecondaryVertexFinder::passConversionElectronCuts(), FilterEvents::process_event(), FilterEventsUpsilon::process_event(), PHTpcTrackSeedCircleFit::process_event(), and jetrtrack::process_event().
virtual size_t TrackSeed::size_g4hit_id () const inline virtual
Reimplemented in TrackSeed_FastSim_v1.
Definition at line 117 of file TrackSeed.h.
View newest version in sPHENIX GitHub at line 117 of file TrackSeed.h
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/trackbase_historic/TrackSeed.h
coresoftware/blob/master/offline/packages/trackbase_historic/TrackSeed.cc