Analysis Software: JetNconstituents Class Reference
JetNconstituents Class Reference
#include <analysis/blob/master/JS-Jet/JetNconstituents/src/JetNconstituents.h>
Public Member Functions
JetNconstituents (const std::string &recojetname="AntiKt_Tower_r04", const std::string &outputfilename="JetNconstituents.root")
~JetNconstituents () override
void setEtaRange (double low, double high)
void setPtRange (double low, double high)
int Init (PHCompositeNode *topNode) override
int InitRun (PHCompositeNode *topNode) override
int process_event (PHCompositeNode *topNode) override
int ResetEvent (PHCompositeNode *topNode) override
Clean up internals after each event.
int EndRun (const int runnumber) override
Called at the end of each run.
int End (PHCompositeNode *topNode) override
Called at the end of all processing.
int Reset (PHCompositeNode *) override
Reset.
void Print (const std::string &what="ALL") const override
Public Member Functions inherited from SubsysReco
~SubsysReco () override
void Print (const std::string &="ALL") const override
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Private Attributes
std::string m_recoJetName
Input Node pointers.
std::string m_outputFileName
std::pair< double, double > m_etaRange
std::pair< double, double > m_ptRange
TH1 * h1d_nConsituents = nullptr
Output Histos variables.
TH1 * h1d_nConsituents_IHCal = nullptr
TH1 * h1d_nConsituents_OHCal = nullptr
TH1 * h1d_nConsituents_EMCal = nullptr
TH1 * h1d_FracEnergy_EMCal = nullptr
TH1 * h1d_FracEnergy_IHCal = nullptr
TH1 * h1d_FracEnergy_OHCal = nullptr
TH2 * h2d_FracEnergy_vs_CaloLayer = nullptr
TH2 * h2d_nConstituent_vs_CaloLayer = nullptr
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = std::numeric_limits<int>::max() - 10
}
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Detailed Description
Definition at line 19 of file JetNconstituents.h.
View newest version in sPHENIX GitHub at line 19 of file JetNconstituents.h
Constructor & Destructor Documentation
JetNconstituents::JetNconstituents (const std::string & recojetname = "AntiKt_Tower_r04", const std::string & outputfilename = "JetNconstituents.root")
Definition at line 33 of file JetNconstituents.cc.
View newest version in sPHENIX GitHub at line 33 of file JetNconstituents.cc
JetNconstituents::~JetNconstituents () override
Definition at line 45 of file JetNconstituents.cc.
View newest version in sPHENIX GitHub at line 45 of file JetNconstituents.cc
Member Function Documentation
int JetNconstituents::End (PHCompositeNode * topNode) override virtual
Called at the end of all processing.
Reimplemented from SubsysReco.
Definition at line 273 of file JetNconstituents.cc.
View newest version in sPHENIX GitHub at line 273 of file JetNconstituents.cc
References Fun4AllReturnCodes::EVENT_OK.
int JetNconstituents::EndRun (const int runnumber) override virtual
Called at the end of each run.
Reimplemented from SubsysReco.
Definition at line 245 of file JetNconstituents.cc.
View newest version in sPHENIX GitHub at line 245 of file JetNconstituents.cc
References PHTFileServer::cd(), Fun4AllReturnCodes::EVENT_OK, PHTFileServer::get(), h1d_FracEnergy_EMCal, h1d_FracEnergy_IHCal, h1d_FracEnergy_OHCal, h1d_nConsituents, h1d_nConsituents_EMCal, h1d_nConsituents_IHCal, h1d_nConsituents_OHCal, h2d_FracEnergy_vs_CaloLayer, h2d_nConstituent_vs_CaloLayer, and m_outputFileName.
int JetNconstituents::Init (PHCompositeNode * topNode) override virtual
Called during initialization. Typically this is where you can book histograms, and e.g. register them to Fun4AllServer (so they can be output to file using Fun4AllServer::dumpHistos() method).
Reimplemented from SubsysReco.
Definition at line 52 of file JetNconstituents.cc.
View newest version in sPHENIX GitHub at line 52 of file JetNconstituents.cc
References Fun4AllReturnCodes::EVENT_OK, PHTFileServer::get(), h1d_FracEnergy_EMCal, h1d_FracEnergy_IHCal, h1d_FracEnergy_OHCal, h1d_nConsituents, h1d_nConsituents_EMCal, h1d_nConsituents_IHCal, h1d_nConsituents_OHCal, h2d_FracEnergy_vs_CaloLayer, h2d_nConstituent_vs_CaloLayer, m_outputFileName, and PHTFileServer::open().
int JetNconstituents::InitRun (PHCompositeNode * topNode) override virtual
Called for first event when run number is known. Typically this is where you may want to fetch data from database, because you know the run number. A place to book histograms which have to know the run number.
Reimplemented from SubsysReco.
Definition at line 105 of file JetNconstituents.cc.
View newest version in sPHENIX GitHub at line 105 of file JetNconstituents.cc
References Fun4AllReturnCodes::EVENT_OK.
void JetNconstituents::Print (const std::string & what = "ALL") const override virtual
Print out some info about this module.
Parameters
what can be used to specify what to print exactly.
Reimplemented from Fun4AllBase.
Definition at line 287 of file JetNconstituents.cc.
View newest version in sPHENIX GitHub at line 287 of file JetNconstituents.cc
int JetNconstituents::process_event (PHCompositeNode * topNode) override virtual
Called for each event. This is where you do the real work.
Reimplemented from SubsysReco.
Definition at line 112 of file JetNconstituents.cc.
View newest version in sPHENIX GitHub at line 112 of file JetNconstituents.cc
References JetMap::begin(), Jet::begin_comp(), channel(), mvtx_utils::comp(), JetMap::end(), Jet::end_comp(), Fun4AllReturnCodes::EVENT_OK, TowerInfo::get_energy(), Jet::get_eta(), Jet::get_pt(), TowerInfoContainer::get_tower_at_channel(), h1d_FracEnergy_EMCal, h1d_FracEnergy_IHCal, h1d_FracEnergy_OHCal, h1d_nConsituents, h1d_nConsituents_EMCal, h1d_nConsituents_IHCal, h1d_nConsituents_OHCal, h2d_FracEnergy_vs_CaloLayer, h2d_nConstituent_vs_CaloLayer, configureMap::ibin, m_etaRange, m_ptRange, m_recoJetName, and Jet::size_comp().
int JetNconstituents::Reset (PHCompositeNode * topNode) override virtual
Reset.
Reimplemented from SubsysReco.
Definition at line 280 of file JetNconstituents.cc.
View newest version in sPHENIX GitHub at line 280 of file JetNconstituents.cc
References Fun4AllReturnCodes::EVENT_OK.
int JetNconstituents::ResetEvent (PHCompositeNode * topNode) override virtual
Clean up internals after each event.
Reimplemented from SubsysReco.
Definition at line 237 of file JetNconstituents.cc.
View newest version in sPHENIX GitHub at line 237 of file JetNconstituents.cc
References Fun4AllReturnCodes::EVENT_OK.
void JetNconstituents::setEtaRange (double low, double high) inline
Definition at line 28 of file JetNconstituents.h.
View newest version in sPHENIX GitHub at line 28 of file JetNconstituents.h
References m_etaRange.
Referenced by Fun4All_JetNconst().
void JetNconstituents::setPtRange (double low, double high) inline
Definition at line 33 of file JetNconstituents.h.
View newest version in sPHENIX GitHub at line 33 of file JetNconstituents.h
References m_ptRange.
Referenced by Fun4All_JetNconst().
Member Data Documentation
TH1* JetNconstituents::h1d_FracEnergy_EMCal = nullptr private
Definition at line 83 of file JetNconstituents.h.
View newest version in sPHENIX GitHub at line 83 of file JetNconstituents.h
Referenced by EndRun(), Init(), and process_event().
TH1* JetNconstituents::h1d_FracEnergy_IHCal = nullptr private
Definition at line 84 of file JetNconstituents.h.
View newest version in sPHENIX GitHub at line 84 of file JetNconstituents.h
Referenced by EndRun(), Init(), and process_event().
TH1* JetNconstituents::h1d_FracEnergy_OHCal = nullptr private
Definition at line 85 of file JetNconstituents.h.
View newest version in sPHENIX GitHub at line 85 of file JetNconstituents.h
Referenced by EndRun(), Init(), and process_event().
TH1* JetNconstituents::h1d_nConsituents = nullptr private
Output Histos variables.
Definition at line 79 of file JetNconstituents.h.
View newest version in sPHENIX GitHub at line 79 of file JetNconstituents.h
Referenced by EndRun(), Init(), and process_event().
TH1* JetNconstituents::h1d_nConsituents_EMCal = nullptr private
Definition at line 82 of file JetNconstituents.h.
View newest version in sPHENIX GitHub at line 82 of file JetNconstituents.h
Referenced by EndRun(), Init(), and process_event().
TH1* JetNconstituents::h1d_nConsituents_IHCal = nullptr private
Definition at line 80 of file JetNconstituents.h.
View newest version in sPHENIX GitHub at line 80 of file JetNconstituents.h
Referenced by EndRun(), Init(), and process_event().
TH1* JetNconstituents::h1d_nConsituents_OHCal = nullptr private
Definition at line 81 of file JetNconstituents.h.
View newest version in sPHENIX GitHub at line 81 of file JetNconstituents.h
Referenced by EndRun(), Init(), and process_event().
TH2* JetNconstituents::h2d_FracEnergy_vs_CaloLayer = nullptr private
Definition at line 88 of file JetNconstituents.h.
View newest version in sPHENIX GitHub at line 88 of file JetNconstituents.h
Referenced by EndRun(), Init(), and process_event().
TH2* JetNconstituents::h2d_nConstituent_vs_CaloLayer = nullptr private
Definition at line 89 of file JetNconstituents.h.
View newest version in sPHENIX GitHub at line 89 of file JetNconstituents.h
Referenced by EndRun(), Init(), and process_event().
std::pair<double, double> JetNconstituents::m_etaRange private
Definition at line 75 of file JetNconstituents.h.
View newest version in sPHENIX GitHub at line 75 of file JetNconstituents.h
Referenced by process_event(), and setEtaRange().
std::string JetNconstituents::m_outputFileName private
Definition at line 74 of file JetNconstituents.h.
View newest version in sPHENIX GitHub at line 74 of file JetNconstituents.h
Referenced by EndRun(), and Init().
std::pair<double, double> JetNconstituents::m_ptRange private
Definition at line 76 of file JetNconstituents.h.
View newest version in sPHENIX GitHub at line 76 of file JetNconstituents.h
Referenced by process_event(), and setPtRange().
std::string JetNconstituents::m_recoJetName private
Input Node pointers.
Definition at line 73 of file JetNconstituents.h.
View newest version in sPHENIX GitHub at line 73 of file JetNconstituents.h
Referenced by process_event().
The documentation for this class was generated from the following files:
analysis/blob/master/JS-Jet/JetNconstituents/src/JetNconstituents.h
analysis/blob/master/JS-Jet/JetNconstituents/src/JetNconstituents.cc