Analysis Software: ActsExamples::Geant4::HepMC3::EventAction Exception Reference
ActsExamples::Geant4::HepMC3::EventAction Exception Reference final
#include <acts/blob/sPHENIX/Examples/Algorithms/Geant4HepMC/src/EventAction.hpp>
Public Member Functions
EventAction (std::vector< std::string > processFilter)
Construct the action and ensure singleton usage.
~EventAction () override
void BeginOfEventAction (const G4Event *event) override
void EndOfEventAction (const G4Event *event) override
void clear ()
Clear the recorded data.
::HepMC3::GenEvent & event ()
Getter of the created HepMC3 event.
Static Public Member Functions
static EventAction * instance ()
Static access method.
Private Attributes
::HepMC3::GenEvent m_event
The current HepMC3 event.
std::vector< std::string > m_processFilter
List of processes that can be combined to a single vertex.
Static Private Attributes
static EventAction * s_instance = nullptr
Instance of the EventAction.
Detailed Description
The EventAction class is the realization of the Geant4 class G4UserEventAction and is writing out the collected RecordedMaterialTrack entities needed for material mapping once per event.
Definition at line 25 of file EventAction.hpp.
View newest version in sPHENIX GitHub at line 25 of file EventAction.hpp
Constructor & Destructor Documentation
ActsExamples::Geant4::HepMC3::EventAction::EventAction (std::vector< std::string > processFilter)
Construct the action and ensure singleton usage.
Definition at line 132 of file EventAction.cpp.
View newest version in sPHENIX GitHub at line 132 of file EventAction.cpp
References s_instance.
ActsExamples::Geant4::HepMC3::EventAction::~EventAction () override
Definition at line 141 of file EventAction.cpp.
View newest version in sPHENIX GitHub at line 141 of file EventAction.cpp
References s_instance.
Member Function Documentation
void ActsExamples::Geant4::HepMC3::EventAction::BeginOfEventAction (const G4Event * event) override
Interface method for begin of the event
Parameters
event is the G4Event to be processed
Note
resets the event and step action
Definition at line 145 of file EventAction.cpp.
View newest version in sPHENIX GitHub at line 145 of file EventAction.cpp
References ActsExamples::Geant4::HepMC3::SteppingAction::clear(), ActsExamples::Geant4::HepMC3::SteppingAction::instance(), and m_event.
void ActsExamples::Geant4::HepMC3::EventAction::clear ()
Clear the recorded data.
Definition at line 192 of file EventAction.cpp.
View newest version in sPHENIX GitHub at line 192 of file EventAction.cpp
References ActsExamples::Geant4::HepMC3::SteppingAction::clear(), and ActsExamples::Geant4::HepMC3::SteppingAction::instance().
Referenced by ActsExamples::Geant4::HepMC3::RunAction::BeginOfRunAction().
void ActsExamples::Geant4::HepMC3::EventAction::EndOfEventAction (const G4Event * event) override
Interface method for end of event
Parameters
event is the G4Event to be processed
Definition at line 151 of file EventAction.cpp.
View newest version in sPHENIX GitHub at line 151 of file EventAction.cpp
References m_event, m_processFilter, merge_hashes::p, and testSigmaEff::v.
HepMC3::GenEvent & ActsExamples::Geant4::HepMC3::EventAction::event ()
Getter of the created HepMC3 event.
Definition at line 196 of file EventAction.cpp.
View newest version in sPHENIX GitHub at line 196 of file EventAction.cpp
References m_event.
Referenced by ActsExamples::EventRecording::execute(), and ActsExamples::Geant4::HepMC3::SteppingAction::UserSteppingAction().
EventAction * ActsExamples::Geant4::HepMC3::EventAction::instance () static
Static access method.
Definition at line 127 of file EventAction.cpp.
View newest version in sPHENIX GitHub at line 127 of file EventAction.cpp
References s_instance.
Referenced by ActsExamples::Geant4::HepMC3::RunAction::BeginOfRunAction(), ActsExamples::EventRecording::execute(), and ActsExamples::Geant4::HepMC3::SteppingAction::UserSteppingAction().
Member Data Documentation
::HepMC3::GenEvent ActsExamples::Geant4::HepMC3::EventAction::m_event private
The current HepMC3 event.
Definition at line 53 of file EventAction.hpp.
View newest version in sPHENIX GitHub at line 53 of file EventAction.hpp
Referenced by BeginOfEventAction(), EndOfEventAction(), and event().
std::vector<std::string> ActsExamples::Geant4::HepMC3::EventAction::m_processFilter private
List of processes that can be combined to a single vertex.
Definition at line 55 of file EventAction.hpp.
View newest version in sPHENIX GitHub at line 55 of file EventAction.hpp
Referenced by EndOfEventAction().
EventAction * ActsExamples::Geant4::HepMC3::EventAction::s_instance = nullptr static private
Instance of the EventAction.
Definition at line 51 of file EventAction.hpp.
View newest version in sPHENIX GitHub at line 51 of file EventAction.hpp
Referenced by EventAction(), instance(), and ~EventAction().
The documentation for this exception was generated from the following files:
acts/blob/sPHENIX/Examples/Algorithms/Geant4HepMC/src/EventAction.hpp
acts/blob/sPHENIX/Examples/Algorithms/Geant4HepMC/src/EventAction.cpp