Analysis Software: acts/blob/sPHENIX/Tests/UnitTests/Core/Seeding/EstimateTrackParamsFromSeedTest.cpp File Reference
EstimateTrackParamsFromSeedTest.cpp File Reference
#include <boost/test/unit_test.hpp>
#include "Acts/Definitions/Algebra.hpp"
#include "Acts/Definitions/Direction.hpp"
#include "Acts/Definitions/TrackParametrization.hpp"
#include "Acts/Definitions/Units.hpp"
#include "Acts/EventData/GenericCurvilinearTrackParameters.hpp"
#include "Acts/EventData/TrackParameters.hpp"
#include "Acts/Geometry/GeometryContext.hpp"
#include "Acts/Geometry/GeometryIdentifier.hpp"
#include "Acts/Geometry/LayerCreator.hpp"
#include "Acts/Geometry/TrackingGeometry.hpp"
#include "Acts/MagneticField/ConstantBField.hpp"
#include "Acts/MagneticField/MagneticFieldContext.hpp"
#include "Acts/Propagator/EigenStepper.hpp"
#include "Acts/Propagator/Navigator.hpp"
#include "Acts/Propagator/Propagator.hpp"
#include "Acts/Seeding/EstimateTrackParamsFromSeed.hpp"
#include "Acts/Surfaces/Surface.hpp"
#include "Acts/Tests/CommonHelpers/CylindricalTrackingGeometry.hpp"
#include "Acts/Tests/CommonHelpers/FloatComparisons.hpp"
#include "Acts/Tests/CommonHelpers/MeasurementsCreator.hpp"
#include "Acts/Tests/CommonHelpers/TestSourceLink.hpp"
#include "Acts/Utilities/CalibrationContext.hpp"
#include "Acts/Utilities/Logger.hpp"
#include <algorithm>
#include <array>
#include <cmath>
#include <iterator>
#include <map>
#include <memory>
#include <optional>
#include <ostream>
#include <random>
#include <utility>
#include <vector>
#include "SpacePoint.hpp"
Functions
BOOST_AUTO_TEST_CASE (trackparameters_estimation_test)
Function Documentation
BOOST_AUTO_TEST_CASE (trackparameters_estimation_test)
Definition at line 94 of file EstimateTrackParamsFromSeedTest.cpp.
View newest version in sPHENIX GitHub at line 94 of file EstimateTrackParamsFromSeedTest.cpp
References CHECK_CLOSE_ABS, Acts::Test::createMeasurements(), Acts::UnitConstants::e, Acts::eBoundLoc0, Acts::eBoundLoc1, Acts::eBoundPhi, Acts::eBoundQOverP, Acts::eBoundTheta, Acts::eBoundTime, Acts::estimateTrackParamsFromSeed(), ckf::field, geoCtx, Acts::Test::geometry, Acts::getDefaultLogger(), Acts::Logging::INFO, it, layer, logger(), Acts::UnitConstants::m, Acts::GeometryObject::m_geometryId, magCtx, Acts::Test::makeParameters(), testing::internal::move(), Acts::Test::navigator, next, physmon_track_finding_ttbar::r, Acts::Test::resolutions, rho, conftest::rng(), start, propagation_timing::stepper, writeMapConfig::surface, and Acts::Test::transform.