Analysis Software: KFParticle_sPHENIX Class Reference
KFParticle_sPHENIX Class Reference
#include <coresoftware/blob/master/offline/packages/KFParticle_sPHENIX/KFParticle_sPHENIX.h>
Public Member Functions
KFParticle_sPHENIX ()
KFParticle constructor.
KFParticle_sPHENIX (const std::string &name)
virtual ~KFParticle_sPHENIX ()
int Init (PHCompositeNode *topNode)
int process_event (PHCompositeNode *topNode)
int End (PHCompositeNode *topNode)
Called at the end of all processing.
void printParticles (KFParticle motherParticle, KFParticle chosenVertex, std::vector< KFParticle > daughterParticles, std::vector< KFParticle > intermediateParticles, int numPVs, int numTracks)
int parseDecayDescriptor ()
bool findParticle (std::string particle)
void setDecayDescriptor (std::string decayDescriptor)
Parameters for the user to vary.
void setMotherName (const std::string &mother_name)
void useIntermediateName (bool use_intermediate_name)
void hasIntermediateStates (bool has_intermediates)
void setNumberOfTracks (int num_tracks)
void setNumberTracksFromIntermeditateState (const std::vector< int > &num_tracks)
void setNumberOfIntermediateStates (int n_intermediates)
void getChargeConjugate (bool get_charge_conjugate)
void setDaughters (std::vector< std::pair< std::string, int >> daughter_list)
void setIntermediateStates (std::vector< std::pair< std::string, int >> intermediate_list)
void setMinimumMass (float min_mass)
void setMaximumMass (float max_mass)
void setDecayTimeRange (float min_decayTime, float max_decayTime)
void setDecayLengthRange (float min_decayLength, float max_decayLength)
void setMinimumTrackPT (float pt)
void setMaximumTrackPTchi2 (float ptchi2)
void setMinimumTrackIP (float ip)
void setMinimumTrackIPchi2 (float ipchi2)
void setMaximumTrackchi2nDOF (float trackchi2ndof)
void setMaximumDaughterDCA (float dca)
void setMaximumVertexchi2nDOF (float vertexchi2nDOF)
void setFlightDistancechi2 (float fdchi2)
void setMinDIRA (float dira_min)
void setMaxDIRA (float dira_max)
void setMotherPT (float mother_pt)
void setMotherIPchi2 (float mother_ipchi2)
void constrainToPrimaryVertex (bool constrain_to_vertex)
void useFakePrimaryVertex (bool use_fake)
void allowZeroMassTracks (bool allow)
void constrainIntermediateMasses (bool constrain_int_mass)
void setIntermediateMassRange (std::vector< std::pair< float, float >> intermediate_mass_range)
void setIntermediateMinPT (std::vector< float > intermediate_min_pt)
void setIntermediateMinIP (std::vector< float > intermediate_min_IP)
void setIntermediateIPRange (std::vector< std::pair< float, float >> intermediate_IP_range)
void setIntermediateMinIPchi2 (std::vector< float > intermediate_min_IPchi2)
void setIntermediateIPchi2Range (std::vector< std::pair< float, float >> intermediate_IPchi2_range)
void setIntermediateMinDIRA (std::vector< float > intermediate_min_DIRA)
void setIntermediateMinFDchi2 (std::vector< float > intermediate_min_FDchi2)
void useMVA (bool require_mva)
void setNumMVAPars (unsigned int nPars)
void setMVAVarList (std::vector< std::string > mva_variable_list)
void setMVAType (const std::string &mva_type)
void setMVAWeightsPath (const std::string &mva_weights_path)
void setMVACutValue (float cut_value)
void saveDST (bool save)
void saveTrackContainer (bool save)
void saveParticleContainer (bool save)
void setContainerName (const std::string &name)
void saveOutput (bool save)
void setOutputName (const std::string &name)
void doTruthMatching (bool truth)
void getDetectorInfo (bool detinfo)
void getCaloInfo (bool caloinfo)
void getAllPVInfo (bool pvinfo)
void setVertexMapNodeName (const std::string &vtx_map_node_name)
Use alternate vertex and track fitters.
void setTrackMapNodeName (const std::string &trk_map_node_name)
Use alternate vertex and track fitters.
Public Member Functions inherited from SubsysReco
~SubsysReco () override
virtual int EndRun (const int)
Called at the end of each run.
virtual int InitRun (PHCompositeNode *)
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
void Print (const std::string &what="ALL") const override
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Public Member Functions inherited from KFParticle_nTuple
KFParticle_nTuple ()
Constructor.
virtual ~KFParticle_nTuple ()
Destructor.
void initializeVariables ()
Unused for now, variables are initialised in the header.
void initializeBranches ()
Initialises required branches based off the user selection (number of tracks, PV constraints etc) and sets branch names if specified.
void fillBranch (PHCompositeNode *topNode, KFParticle motherParticle, KFParticle vertex, std::vector< KFParticle > daughters, std::vector< KFParticle > intermediates, int nPVs, int multiplicity)
Fills required information for your selection, also requests truth and detector information if needed.
float calc_secondary_vertex_mass_noPID (std::vector< KFParticle > kfp_daughters)
Public Member Functions inherited from KFParticle_truthAndDetTools
KFParticle_truthAndDetTools ()
virtual ~KFParticle_truthAndDetTools ()
SvtxTrack * getTrack (unsigned int track_id, SvtxTrackMap *trackmap)
SvtxVertex * getVertex (unsigned int vertex_id, SvtxVertexMap *vertexmap)
PHG4Particle * getTruthTrack (SvtxTrack *thisTrack, PHCompositeNode *topNode)
void initializeTruthBranches (TTree *m_tree, int daughter_id, std::string daughter_number, bool m_constrain_to_vertex_truthMatch)
void fillTruthBranch (PHCompositeNode *topNode, TTree *m_tree, KFParticle daughter, int daughter_id, KFParticle vertex, bool m_constrain_to_vertex_truthMatch)
void fillHepMCBranch (HepMC::GenParticle *particle, int daughter_id)
int getHepMCInfo (PHCompositeNode *topNode, TTree *m_tree, KFParticle daughter, int daughter_id)
void initializeCaloBranches (TTree *m_tree, int daughter_id, std::string daughter_number)
void fillCaloBranch (PHCompositeNode *topNode, TTree *m_tree, KFParticle daughter, int daughter_id)
void initializeDetectorBranches (TTree *m_tree, int daughter_id, std::string daughter_number)
void initializeSubDetectorBranches (TTree *m_tree, std::string detectorName, int daughter_id, std::string daughter_number)
void fillDetectorBranch (PHCompositeNode *topNode, TTree *m_tree, KFParticle daughter, int daughter_id)
void allPVInfo (PHCompositeNode *topNode, TTree *m_tree, KFParticle motherParticle, std::vector< KFParticle > daughters, std::vector< KFParticle > intermediates)
void clearVectors ()
Public Member Functions inherited from KFParticle_DST
KFParticle_DST ()
Constructor.
virtual ~KFParticle_DST ()
Destructor.
int createParticleNode (PHCompositeNode *topNode)
Places a KFParticle_Container and SvtxTrackMap on the node tree if they don't exist.
void fillParticleNode (PHCompositeNode *topNode, const KFParticle &motherParticle, const std::vector< KFParticle > &daughters, const std::vector< KFParticle > &intermediates)
Simultaneously fills a KFParticle_Container and SvtxTrackMap if they are enabled.
void fillParticleNode_Track (PHCompositeNode *topNode, const KFParticle &motherParticle, std::vector< KFParticle > daughters, std::vector< KFParticle > intermediates)
Called by fillParticleNode, fills an SvtxTrackMap.
void fillParticleNode_Particle (PHCompositeNode *topNode, const KFParticle &motherParticle, std::vector< KFParticle > daughters, std::vector< KFParticle > intermediates)
Called by fillParticleNode, fills a KFParitcle_Container.
void printNode (PHCompositeNode *topNode)
Prints contents of KFParticle_Containers and SvtxTrackMaps for an event if they are enabled.
Static Public Attributes
static const int max_particles = 99
Private Attributes
bool m_has_intermediates_sPHENIX
bool m_constrain_to_vertex_sPHENIX
bool m_require_mva
bool m_save_dst
bool m_save_output
std::string m_outfile_name
TFile * m_outfile
std::string m_decayDescriptor
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = INT_MAX - 10
}
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Protected Member Functions inherited from KFParticle_eventReconstruction
KFParticle_eventReconstruction ()
KFParticle constructor.
virtual ~KFParticle_eventReconstruction ()
void createDecay (PHCompositeNode *topNode, std::vector< KFParticle > &selectedMother, std::vector< KFParticle > &selectedVertex, std::vector< std::vector< KFParticle >> &selectedDaughters, std::vector< std::vector< KFParticle >> &selectedIntermediates, int &nPVs, int &multiplicity)
void buildBasicChain (std::vector< KFParticle > &selectedMotherBasic, std::vector< KFParticle > &selectedVertexBasic, std::vector< std::vector< KFParticle >> &selectedDaughtersBasic, const std::vector< KFParticle > &daughterParticlesBasic, const std::vector< int > &goodTrackIndexBasic, const std::vector< KFParticle > &primaryVerticesBasic)
Used to reconstruct simple decays with no intermediate states.
void buildChain (std::vector< KFParticle > &selectedMotherAdv, std::vector< KFParticle > &selectedVertexAdv, std::vector< std::vector< KFParticle >> &selectedDaughtersAdv, std::vector< std::vector< KFParticle >> &selectedIntermediatesAdv, const std::vector< KFParticle > &daughterParticlesAdv, const std::vector< int > &goodTrackIndexAdv, const std::vector< KFParticle > &primaryVerticesAdv)
Used to reconstruct more complicated decays with up to four intermediate states.
void getCandidateDecay (std::vector< KFParticle > &selectedMotherCand, std::vector< KFParticle > &selectedVertexCand, std::vector< std::vector< KFParticle >> &selectedDaughtersCand, std::vector< KFParticle > daughterParticlesCand, std::vector< std::vector< int >> goodTracksThatMeetCand, std::vector< KFParticle > primaryVerticesCand, int n_track_start, int n_track_stop, bool isIntermediate, int intermediateNumber, bool constrainMass)
Basic building block for event reconstruction and selection.
int selectBestCombination (bool PVconstraint, bool isAnInterMother, std::vector< KFParticle > possibleCandidates, std::vector< KFParticle > possibleVertex)
Method to chose best candidate from a selection of common SV's.
KFParticle createFakePV ()
Protected Attributes inherited from KFParticle_nTuple
bool m_has_intermediates_nTuple
bool m_constrain_to_vertex_nTuple
bool m_get_all_PVs
std::vector< int > m_num_tracks_from_intermediate_nTuple
bool m_truth_matching
bool m_detector_info
bool m_calo_info
std::string m_mother_name
bool m_use_intermediate_name
bool m_get_charge_conjugate_nTuple
std::vector< std::string > m_intermediate_name_ntuple
Protected Attributes inherited from KFParticle_DST
bool m_has_intermediates_DST = false
bool m_write_track_container = true
bool m_write_particle_container = true
std::string m_container_name
Static Protected Attributes inherited from KFParticle_truthAndDetTools
static const int max_tracks = 20
Detailed Description
Definition at line 40 of file KFParticle_sPHENIX.h.
View newest version in sPHENIX GitHub at line 40 of file KFParticle_sPHENIX.h
Constructor & Destructor Documentation
KFParticle_sPHENIX::KFParticle_sPHENIX ()
KFParticle constructor.
Definition at line 41 of file KFParticle_sPHENIX.cc.
View newest version in sPHENIX GitHub at line 41 of file KFParticle_sPHENIX.cc
KFParticle_sPHENIX::KFParticle_sPHENIX (const std::string & name) explicit
Definition at line 53 of file KFParticle_sPHENIX.cc.
View newest version in sPHENIX GitHub at line 53 of file KFParticle_sPHENIX.cc
virtual KFParticle_sPHENIX::~KFParticle_sPHENIX () inline virtual
Definition at line 47 of file KFParticle_sPHENIX.h.
View newest version in sPHENIX GitHub at line 47 of file KFParticle_sPHENIX.h
Member Function Documentation
void KFParticle_sPHENIX::allowZeroMassTracks (bool allow) inline
Definition at line 187 of file KFParticle_sPHENIX.h.
View newest version in sPHENIX GitHub at line 187 of file KFParticle_sPHENIX.h
References KFParticle_Tools::m_allowZeroMassTracks.
void KFParticle_sPHENIX::constrainIntermediateMasses (bool constrain_int_mass) inline
Definition at line 189 of file KFParticle_sPHENIX.h.
View newest version in sPHENIX GitHub at line 189 of file KFParticle_sPHENIX.h
References KFParticle_eventReconstruction::m_constrain_int_mass.
Referenced by Fun4All_KFParticle_advanced(), Fun4All_KFParticle_basic(), Fun4All_KFParticle_condorJob(), and Fun4All_KFParticle_singleFile().
void KFParticle_sPHENIX::constrainToPrimaryVertex (bool constrain_to_vertex) inline
Definition at line 178 of file KFParticle_sPHENIX.h.
View newest version in sPHENIX GitHub at line 178 of file KFParticle_sPHENIX.h
References KFParticle_eventReconstruction::m_constrain_to_vertex, KFParticle_nTuple::m_constrain_to_vertex_nTuple, and m_constrain_to_vertex_sPHENIX.
Referenced by Fun4All_KFParticle_advanced(), Fun4All_KFParticle_basic(), Fun4All_KFParticle_condorJob(), Fun4All_KFParticle_singleFile(), Fun4All_KFParticle_standardContainers(), KFParticle_D0_Reco(), KFParticle_Lambdac_Reco(), and KFParticle_Upsilon_Reco().
void KFParticle_sPHENIX::doTruthMatching (bool truth) inline
Definition at line 266 of file KFParticle_sPHENIX.h.
View newest version in sPHENIX GitHub at line 266 of file KFParticle_sPHENIX.h
References KFParticle_nTuple::m_truth_matching.
Referenced by Fun4All_KFParticle_advanced(), Fun4All_KFParticle_basic(), Fun4All_KFParticle_condorJob(), Fun4All_KFParticle_singleFile(), Fun4All_KFParticle_standardContainers(), KFParticle_D0_Reco(), KFParticle_Lambdac_Reco(), and KFParticle_Upsilon_Reco().
int KFParticle_sPHENIX::End (PHCompositeNode *) virtual
Called at the end of all processing.
Reimplemented from SubsysReco.
Definition at line 149 of file KFParticle_sPHENIX.cc.
View newest version in sPHENIX GitHub at line 149 of file KFParticle_sPHENIX.cc
References m_outfile, m_save_output, and Fun4AllBase::Name().
bool KFParticle_sPHENIX::findParticle (std::string particle)
Definition at line 382 of file KFParticle_sPHENIX.cc.
View newest version in sPHENIX GitHub at line 382 of file KFParticle_sPHENIX.cc
References Fun4AllBase::Verbosity(), and Fun4AllBase::VERBOSITY_SOME.
Referenced by parseDecayDescriptor().
void KFParticle_sPHENIX::getAllPVInfo (bool pvinfo) inline
Definition at line 272 of file KFParticle_sPHENIX.h.
View newest version in sPHENIX GitHub at line 272 of file KFParticle_sPHENIX.h
References KFParticle_nTuple::m_get_all_PVs.
Referenced by Fun4All_KFParticle_condorJob().
void KFParticle_sPHENIX::getCaloInfo (bool caloinfo) inline
Definition at line 270 of file KFParticle_sPHENIX.h.
View newest version in sPHENIX GitHub at line 270 of file KFParticle_sPHENIX.h
References KFParticle_nTuple::m_calo_info.
Referenced by Fun4All_KFParticle_condorJob().
void KFParticle_sPHENIX::getChargeConjugate (bool get_charge_conjugate) inline
Definition at line 113 of file KFParticle_sPHENIX.h.
View newest version in sPHENIX GitHub at line 113 of file KFParticle_sPHENIX.h
References KFParticle_Tools::m_get_charge_conjugate, and KFParticle_nTuple::m_get_charge_conjugate_nTuple.
Referenced by Fun4All_KFParticle_advanced(), Fun4All_KFParticle_basic(), Fun4All_KFParticle_condorJob(), Fun4All_KFParticle_singleFile(), Fun4All_KFParticle_standardContainers(), and parseDecayDescriptor().
void KFParticle_sPHENIX::getDetectorInfo (bool detinfo) inline
Definition at line 268 of file KFParticle_sPHENIX.h.
View newest version in sPHENIX GitHub at line 268 of file KFParticle_sPHENIX.h
References KFParticle_nTuple::m_detector_info.
Referenced by Fun4All_KFParticle_advanced(), Fun4All_KFParticle_basic(), Fun4All_KFParticle_condorJob(), Fun4All_KFParticle_singleFile(), Fun4All_KFParticle_standardContainers(), KFParticle_D0_Reco(), KFParticle_Lambdac_Reco(), and KFParticle_Upsilon_Reco().
void KFParticle_sPHENIX::hasIntermediateStates (bool has_intermediates) inline
Definition at line 84 of file KFParticle_sPHENIX.h.
View newest version in sPHENIX GitHub at line 84 of file KFParticle_sPHENIX.h
References KFParticle_Tools::m_has_intermediates, KFParticle_DST::m_has_intermediates_DST, KFParticle_nTuple::m_has_intermediates_nTuple, and m_has_intermediates_sPHENIX.
Referenced by Fun4All_KFParticle_advanced(), Fun4All_KFParticle_basic(), Fun4All_KFParticle_condorJob(), Fun4All_KFParticle_singleFile(), Fun4All_KFParticle_standardContainers(), and parseDecayDescriptor().
int KFParticle_sPHENIX::Init (PHCompositeNode *) virtual
Called during initialization. Typically this is where you can book histograms, and e.g. register them to Fun4AllServer (so they can be output to file using Fun4AllServer::dumpHistos() method).
Reimplemented from SubsysReco.
Definition at line 65 of file KFParticle_sPHENIX.cc.
View newest version in sPHENIX GitHub at line 65 of file KFParticle_sPHENIX.cc
References KFParticle_DST::createParticleNode(), i, KFParticle_MVA::initMVA(), KFParticle_Tools::m_daughter_name, m_decayDescriptor, KFParticle_Tools::m_num_tracks, m_outfile_name, m_require_mva, m_save_dst, m_save_output, parseDecayDescriptor(), Fun4AllBase::Verbosity(), and Fun4AllBase::VERBOSITY_SOME.
int KFParticle_sPHENIX::parseDecayDescriptor ()
Definition at line 205 of file KFParticle_sPHENIX.cc.
View newest version in sPHENIX GitHub at line 205 of file KFParticle_sPHENIX.cc
References Fun4AllReturnCodes::ABORTRUN, c, findParticle(), getChargeConjugate(), hasIntermediateStates(), i, j, m_decayDescriptor, Fun4AllBase::Name(), Acts::Test::pos, setDaughters(), setIntermediateStates(), setMotherName(), setNumberOfIntermediateStates(), setNumberOfTracks(), setNumberTracksFromIntermeditateState(), Fun4AllBase::Verbosity(), Fun4AllBase::VERBOSITY_MORE, and Fun4AllBase::VERBOSITY_SOME.
Referenced by Init().
void KFParticle_sPHENIX::printParticles (KFParticle motherParticle, KFParticle chosenVertex, std::vector< KFParticle > daughterParticles, std::vector< KFParticle > intermediateParticles, int numPVs, int numTracks)
If verbosity is > 0, this will print out all candidate information: masses, momenta and positions for mothers, intermediates and final state tracks, PV position, number of vertices and number of tracks in the event (multiplicity)
Definition at line 163 of file KFParticle_sPHENIX.cc.
View newest version in sPHENIX GitHub at line 163 of file KFParticle_sPHENIX.cc
References KFParticle::GetCovariance(), KFParticle::GetX(), KFParticle::GetY(), KFParticle::GetZ(), i, KFParticle_Tools::identify(), m_constrain_to_vertex_sPHENIX, and m_has_intermediates_sPHENIX.
Referenced by process_event().
int KFParticle_sPHENIX::process_event (PHCompositeNode *) virtual
Called for each event. This is where you do the real work.
Reimplemented from SubsysReco.
Definition at line 92 of file KFParticle_sPHENIX.cc.
View newest version in sPHENIX GitHub at line 92 of file KFParticle_sPHENIX.cc
References Fun4AllReturnCodes::ABORTEVENT, KFParticle_eventReconstruction::createDecay(), Fun4AllReturnCodes::EVENT_OK, KFParticle_nTuple::fillBranch(), KFParticle_DST::fillParticleNode(), i, KFParticle_nTuple::initializeBranches(), m_constrain_to_vertex_sPHENIX, m_has_intermediates_sPHENIX, m_outfile, m_outfile_name, m_save_dst, m_save_output, KFParticle_Tools::m_trk_map_node_name, KFParticle_eventReconstruction::m_use_fake_pv, KFParticle_Tools::m_vtx_map_node_name, KFParticle_DST::printNode(), printParticles(), SvtxVertexMap::size(), SvtxTrackMap::size(), Fun4AllBase::Verbosity(), Fun4AllBase::VERBOSITY_MORE, Fun4AllBase::VERBOSITY_SOME, and KFParticle_truthAndDetTools::vertex.
void KFParticle_sPHENIX::saveDST (bool save) inline
Definition at line 254 of file KFParticle_sPHENIX.h.
View newest version in sPHENIX GitHub at line 254 of file KFParticle_sPHENIX.h
References m_save_dst, and save().
Referenced by Fun4All_KFParticle_advanced(), Fun4All_KFParticle_basic(), Fun4All_KFParticle_condorJob(), Fun4All_KFParticle_singleFile(), Fun4All_KFParticle_standardContainers(), KFParticle_D0_Reco(), KFParticle_Lambdac_Reco(), and KFParticle_Upsilon_Reco().
void KFParticle_sPHENIX::saveOutput (bool save) inline
Definition at line 262 of file KFParticle_sPHENIX.h.
View newest version in sPHENIX GitHub at line 262 of file KFParticle_sPHENIX.h
References m_save_output, and save().
Referenced by Fun4All_KFParticle_advanced(), Fun4All_KFParticle_basic(), Fun4All_KFParticle_condorJob(), Fun4All_KFParticle_singleFile(), Fun4All_KFParticle_standardContainers(), KFParticle_D0_Reco(), KFParticle_Lambdac_Reco(), and KFParticle_Upsilon_Reco().
void KFParticle_sPHENIX::saveParticleContainer (bool save) inline
Definition at line 258 of file KFParticle_sPHENIX.h.
View newest version in sPHENIX GitHub at line 258 of file KFParticle_sPHENIX.h
References KFParticle_DST::m_write_particle_container, and save().
void KFParticle_sPHENIX::saveTrackContainer (bool save) inline
Definition at line 256 of file KFParticle_sPHENIX.h.
View newest version in sPHENIX GitHub at line 256 of file KFParticle_sPHENIX.h
References KFParticle_DST::m_write_track_container, and save().
void KFParticle_sPHENIX::setContainerName (const std::string & name) inline
Definition at line 260 of file KFParticle_sPHENIX.h.
View newest version in sPHENIX GitHub at line 260 of file KFParticle_sPHENIX.h
References KFParticle_DST::m_container_name, and name.
Referenced by Fun4All_KFParticle_advanced(), Fun4All_KFParticle_standardContainers(), KFParticle_D0_Reco(), KFParticle_Lambdac_Reco(), and KFParticle_Upsilon_Reco().
void KFParticle_sPHENIX::setDaughters (std::vector< std::pair< std::string, int >> daughter_list) inline
Definition at line 119 of file KFParticle_sPHENIX.h.
View newest version in sPHENIX GitHub at line 119 of file KFParticle_sPHENIX.h
References i, KFParticle_Tools::m_daughter_charge, and KFParticle_Tools::m_daughter_name.
Referenced by Fun4All_KFParticle_advanced(), Fun4All_KFParticle_basic(), Fun4All_KFParticle_condorJob(), Fun4All_KFParticle_singleFile(), Fun4All_KFParticle_standardContainers(), and parseDecayDescriptor().
void KFParticle_sPHENIX::setDecayDescriptor (std::string decayDescriptor) inline
Parameters for the user to vary.
Definition at line 72 of file KFParticle_sPHENIX.h.
View newest version in sPHENIX GitHub at line 72 of file KFParticle_sPHENIX.h
References m_decayDescriptor.
Referenced by Fun4All_KFParticle_condorJob(), KFParticle_D0_Reco(), KFParticle_Lambdac_Reco(), and KFParticle_Upsilon_Reco().
void KFParticle_sPHENIX::setDecayLengthRange (float min_decayLength, float max_decayLength) inline
Definition at line 148 of file KFParticle_sPHENIX.h.
View newest version in sPHENIX GitHub at line 148 of file KFParticle_sPHENIX.h
References KFParticle_Tools::m_max_decayLength, and KFParticle_Tools::m_min_decayLength.
void KFParticle_sPHENIX::setDecayTimeRange (float min_decayTime, float max_decayTime) inline
Definition at line 142 of file KFParticle_sPHENIX.h.
View newest version in sPHENIX GitHub at line 142 of file KFParticle_sPHENIX.h
References KFParticle_Tools::m_max_decayTime, and KFParticle_Tools::m_min_decayTime.
void KFParticle_sPHENIX::setFlightDistancechi2 (float fdchi2) inline
Definition at line 168 of file KFParticle_sPHENIX.h.
View newest version in sPHENIX GitHub at line 168 of file KFParticle_sPHENIX.h
References KFParticle_Tools::m_fdchi2.
Referenced by Fun4All_KFParticle_advanced(), Fun4All_KFParticle_basic(), Fun4All_KFParticle_condorJob(), and Fun4All_KFParticle_singleFile().
void KFParticle_sPHENIX::setIntermediateIPchi2Range (std::vector< std::pair< float, float >> intermediate_IPchi2_range) inline
Definition at line 220 of file KFParticle_sPHENIX.h.
View newest version in sPHENIX GitHub at line 220 of file KFParticle_sPHENIX.h
References i, KFParticle_Tools::m_intermediate_max_ipchi2, and KFParticle_Tools::m_intermediate_min_ipchi2.
Referenced by Fun4All_KFParticle_condorJob().
void KFParticle_sPHENIX::setIntermediateIPRange (std::vector< std::pair< float, float >> intermediate_IP_range) inline
Definition at line 206 of file KFParticle_sPHENIX.h.
View newest version in sPHENIX GitHub at line 206 of file KFParticle_sPHENIX.h
References i, KFParticle_Tools::m_intermediate_max_ip, and KFParticle_Tools::m_intermediate_min_ip.
Referenced by Fun4All_KFParticle_condorJob().
void KFParticle_sPHENIX::setIntermediateMassRange (std::vector< std::pair< float, float >> intermediate_mass_range) inline
Definition at line 191 of file KFParticle_sPHENIX.h.
View newest version in sPHENIX GitHub at line 191 of file KFParticle_sPHENIX.h
References i, and KFParticle_Tools::m_intermediate_mass_range.
Referenced by Fun4All_KFParticle_advanced(), Fun4All_KFParticle_basic(), Fun4All_KFParticle_condorJob(), and Fun4All_KFParticle_singleFile().
void KFParticle_sPHENIX::setIntermediateMinDIRA (std::vector< float > intermediate_min_DIRA) inline
Definition at line 229 of file KFParticle_sPHENIX.h.
View newest version in sPHENIX GitHub at line 229 of file KFParticle_sPHENIX.h
References i, and KFParticle_Tools::m_intermediate_min_dira.
Referenced by Fun4All_KFParticle_condorJob().
void KFParticle_sPHENIX::setIntermediateMinFDchi2 (std::vector< float > intermediate_min_FDchi2) inline
Definition at line 234 of file KFParticle_sPHENIX.h.
View newest version in sPHENIX GitHub at line 234 of file KFParticle_sPHENIX.h
References i, and KFParticle_Tools::m_intermediate_min_fdchi2.
Referenced by Fun4All_KFParticle_condorJob().
void KFParticle_sPHENIX::setIntermediateMinIP (std::vector< float > intermediate_min_IP) inline
Definition at line 201 of file KFParticle_sPHENIX.h.
View newest version in sPHENIX GitHub at line 201 of file KFParticle_sPHENIX.h
References i, and KFParticle_Tools::m_intermediate_min_ip.
Referenced by Fun4All_KFParticle_condorJob().
void KFParticle_sPHENIX::setIntermediateMinIPchi2 (std::vector< float > intermediate_min_IPchi2) inline
Definition at line 215 of file KFParticle_sPHENIX.h.
View newest version in sPHENIX GitHub at line 215 of file KFParticle_sPHENIX.h
References i, and KFParticle_Tools::m_intermediate_min_ipchi2.
Referenced by Fun4All_KFParticle_condorJob().
void KFParticle_sPHENIX::setIntermediateMinPT (std::vector< float > intermediate_min_pt) inline
Definition at line 196 of file KFParticle_sPHENIX.h.
View newest version in sPHENIX GitHub at line 196 of file KFParticle_sPHENIX.h
References KFParticle_Tools::m_intermediate_min_pt.
Referenced by Fun4All_KFParticle_advanced(), Fun4All_KFParticle_basic(), Fun4All_KFParticle_condorJob(), and Fun4All_KFParticle_singleFile().
void KFParticle_sPHENIX::setIntermediateStates (std::vector< std::pair< std::string, int >> intermediate_list) inline
Definition at line 128 of file KFParticle_sPHENIX.h.
View newest version in sPHENIX GitHub at line 128 of file KFParticle_sPHENIX.h
References i, KFParticle_Tools::m_intermediate_charge, KFParticle_Tools::m_intermediate_name, and KFParticle_nTuple::m_intermediate_name_ntuple.
Referenced by Fun4All_KFParticle_advanced(), Fun4All_KFParticle_basic(), Fun4All_KFParticle_condorJob(), Fun4All_KFParticle_singleFile(), and parseDecayDescriptor().
void KFParticle_sPHENIX::setMaxDIRA (float dira_max) inline
Definition at line 172 of file KFParticle_sPHENIX.h.
View newest version in sPHENIX GitHub at line 172 of file KFParticle_sPHENIX.h
References KFParticle_Tools::m_dira_max.
void KFParticle_sPHENIX::setMaximumDaughterDCA (float dca) inline
Definition at line 164 of file KFParticle_sPHENIX.h.
View newest version in sPHENIX GitHub at line 164 of file KFParticle_sPHENIX.h
References KFParticle_Tools::m_comb_DCA.
Referenced by Fun4All_KFParticle_advanced(), Fun4All_KFParticle_basic(), Fun4All_KFParticle_condorJob(), Fun4All_KFParticle_singleFile(), Fun4All_KFParticle_standardContainers(), KFParticle_D0_Reco(), KFParticle_Lambdac_Reco(), and KFParticle_Upsilon_Reco().
void KFParticle_sPHENIX::setMaximumMass (float max_mass) inline
Definition at line 140 of file KFParticle_sPHENIX.h.
View newest version in sPHENIX GitHub at line 140 of file KFParticle_sPHENIX.h
References KFParticle_Tools::m_max_mass.
Referenced by Fun4All_KFParticle_advanced(), Fun4All_KFParticle_basic(), Fun4All_KFParticle_condorJob(), Fun4All_KFParticle_singleFile(), Fun4All_KFParticle_standardContainers(), KFParticle_D0_Reco(), KFParticle_Lambdac_Reco(), and KFParticle_Upsilon_Reco().
void KFParticle_sPHENIX::setMaximumTrackchi2nDOF (float trackchi2ndof) inline
Definition at line 162 of file KFParticle_sPHENIX.h.
View newest version in sPHENIX GitHub at line 162 of file KFParticle_sPHENIX.h
References KFParticle_Tools::m_track_chi2ndof.
Referenced by Fun4All_KFParticle_advanced(), Fun4All_KFParticle_basic(), Fun4All_KFParticle_condorJob(), Fun4All_KFParticle_singleFile(), Fun4All_KFParticle_standardContainers(), KFParticle_D0_Reco(), KFParticle_Lambdac_Reco(), and KFParticle_Upsilon_Reco().
void KFParticle_sPHENIX::setMaximumTrackPTchi2 (float ptchi2) inline
Definition at line 156 of file KFParticle_sPHENIX.h.
View newest version in sPHENIX GitHub at line 156 of file KFParticle_sPHENIX.h
References KFParticle_Tools::m_track_ptchi2.
void KFParticle_sPHENIX::setMaximumVertexchi2nDOF (float vertexchi2nDOF) inline
Definition at line 166 of file KFParticle_sPHENIX.h.
View newest version in sPHENIX GitHub at line 166 of file KFParticle_sPHENIX.h
References KFParticle_Tools::m_vertex_chi2ndof.
Referenced by Fun4All_KFParticle_advanced(), Fun4All_KFParticle_basic(), Fun4All_KFParticle_condorJob(), Fun4All_KFParticle_singleFile(), Fun4All_KFParticle_standardContainers(), KFParticle_D0_Reco(), KFParticle_Lambdac_Reco(), and KFParticle_Upsilon_Reco().
void KFParticle_sPHENIX::setMinDIRA (float dira_min) inline
Definition at line 170 of file KFParticle_sPHENIX.h.
View newest version in sPHENIX GitHub at line 170 of file KFParticle_sPHENIX.h
References KFParticle_Tools::m_dira_min.
Referenced by Fun4All_KFParticle_advanced(), Fun4All_KFParticle_basic(), Fun4All_KFParticle_condorJob(), and Fun4All_KFParticle_singleFile().
void KFParticle_sPHENIX::setMinimumMass (float min_mass) inline
Definition at line 138 of file KFParticle_sPHENIX.h.
View newest version in sPHENIX GitHub at line 138 of file KFParticle_sPHENIX.h
References KFParticle_Tools::m_min_mass.
Referenced by Fun4All_KFParticle_advanced(), Fun4All_KFParticle_basic(), Fun4All_KFParticle_condorJob(), Fun4All_KFParticle_singleFile(), Fun4All_KFParticle_standardContainers(), KFParticle_D0_Reco(), KFParticle_Lambdac_Reco(), and KFParticle_Upsilon_Reco().
void KFParticle_sPHENIX::setMinimumTrackIP (float ip) inline
Definition at line 158 of file KFParticle_sPHENIX.h.
View newest version in sPHENIX GitHub at line 158 of file KFParticle_sPHENIX.h
References KFParticle_Tools::m_track_ip.
Referenced by Fun4All_KFParticle_condorJob().
void KFParticle_sPHENIX::setMinimumTrackIPchi2 (float ipchi2) inline
Definition at line 160 of file KFParticle_sPHENIX.h.
View newest version in sPHENIX GitHub at line 160 of file KFParticle_sPHENIX.h
References KFParticle_Tools::m_track_ipchi2.
Referenced by Fun4All_KFParticle_advanced(), Fun4All_KFParticle_basic(), Fun4All_KFParticle_condorJob(), Fun4All_KFParticle_singleFile(), Fun4All_KFParticle_standardContainers(), KFParticle_D0_Reco(), KFParticle_Lambdac_Reco(), and KFParticle_Upsilon_Reco().
void KFParticle_sPHENIX::setMinimumTrackPT (float pt) inline
Definition at line 154 of file KFParticle_sPHENIX.h.
View newest version in sPHENIX GitHub at line 154 of file KFParticle_sPHENIX.h
References KFParticle_Tools::m_track_pt.
Referenced by Fun4All_KFParticle_advanced(), Fun4All_KFParticle_basic(), Fun4All_KFParticle_condorJob(), Fun4All_KFParticle_singleFile(), Fun4All_KFParticle_standardContainers(), KFParticle_D0_Reco(), KFParticle_Lambdac_Reco(), and KFParticle_Upsilon_Reco().
void KFParticle_sPHENIX::setMotherIPchi2 (float mother_ipchi2) inline
Definition at line 176 of file KFParticle_sPHENIX.h.
View newest version in sPHENIX GitHub at line 176 of file KFParticle_sPHENIX.h
References KFParticle_Tools::m_mother_ipchi2.
Referenced by Fun4All_KFParticle_advanced(), Fun4All_KFParticle_basic(), Fun4All_KFParticle_condorJob(), and Fun4All_KFParticle_singleFile().
void KFParticle_sPHENIX::setMotherName (const std::string & mother_name) inline
Definition at line 76 of file KFParticle_sPHENIX.h.
View newest version in sPHENIX GitHub at line 76 of file KFParticle_sPHENIX.h
References KFParticle_nTuple::m_mother_name, and KFParticle_Tools::m_mother_name_Tools.
Referenced by Fun4All_KFParticle_advanced(), Fun4All_KFParticle_basic(), Fun4All_KFParticle_condorJob(), Fun4All_KFParticle_singleFile(), Fun4All_KFParticle_standardContainers(), and parseDecayDescriptor().
void KFParticle_sPHENIX::setMotherPT (float mother_pt) inline
Definition at line 174 of file KFParticle_sPHENIX.h.
View newest version in sPHENIX GitHub at line 174 of file KFParticle_sPHENIX.h
References KFParticle_Tools::m_mother_pt.
Referenced by Fun4All_KFParticle_advanced(), Fun4All_KFParticle_basic(), Fun4All_KFParticle_condorJob(), Fun4All_KFParticle_singleFile(), Fun4All_KFParticle_standardContainers(), KFParticle_D0_Reco(), KFParticle_Lambdac_Reco(), and KFParticle_Upsilon_Reco().
void KFParticle_sPHENIX::setMVACutValue (float cut_value) inline
Definition at line 252 of file KFParticle_sPHENIX.h.
View newest version in sPHENIX GitHub at line 252 of file KFParticle_sPHENIX.h
References KFParticle_Tools::m_mva_cut_value.
void KFParticle_sPHENIX::setMVAType (const std::string & mva_type) inline
Definition at line 248 of file KFParticle_sPHENIX.h.
View newest version in sPHENIX GitHub at line 248 of file KFParticle_sPHENIX.h
References KFParticle_MVA::m_mva_type.
void KFParticle_sPHENIX::setMVAVarList (std::vector< std::string > mva_variable_list) inline
Definition at line 243 of file KFParticle_sPHENIX.h.
View newest version in sPHENIX GitHub at line 243 of file KFParticle_sPHENIX.h
References i, and KFParticle_MVA::m_mva_variable_list.
void KFParticle_sPHENIX::setMVAWeightsPath (const std::string & mva_weights_path) inline
Definition at line 250 of file KFParticle_sPHENIX.h.
View newest version in sPHENIX GitHub at line 250 of file KFParticle_sPHENIX.h
References KFParticle_MVA::m_mva_path.
void KFParticle_sPHENIX::setNumberOfIntermediateStates (int n_intermediates) inline
Definition at line 107 of file KFParticle_sPHENIX.h.
View newest version in sPHENIX GitHub at line 107 of file KFParticle_sPHENIX.h
References KFParticle_Tools::m_num_intermediate_states, and KFParticle_truthAndDetTools::m_num_intermediate_states_nTuple.
Referenced by Fun4All_KFParticle_advanced(), Fun4All_KFParticle_basic(), Fun4All_KFParticle_condorJob(), Fun4All_KFParticle_singleFile(), and parseDecayDescriptor().
void KFParticle_sPHENIX::setNumberOfTracks (int num_tracks) inline
Definition at line 92 of file KFParticle_sPHENIX.h.
View newest version in sPHENIX GitHub at line 92 of file KFParticle_sPHENIX.h
References KFParticle_Tools::m_num_tracks, and KFParticle_truthAndDetTools::m_num_tracks_nTuple.
Referenced by Fun4All_KFParticle_advanced(), Fun4All_KFParticle_basic(), Fun4All_KFParticle_condorJob(), Fun4All_KFParticle_singleFile(), Fun4All_KFParticle_standardContainers(), and parseDecayDescriptor().
void KFParticle_sPHENIX::setNumberTracksFromIntermeditateState (const std::vector< int > & num_tracks) inline
Definition at line 98 of file KFParticle_sPHENIX.h.
View newest version in sPHENIX GitHub at line 98 of file KFParticle_sPHENIX.h
References i, KFParticle_Tools::m_num_tracks_from_intermediate, and KFParticle_nTuple::m_num_tracks_from_intermediate_nTuple.
Referenced by Fun4All_KFParticle_advanced(), Fun4All_KFParticle_basic(), Fun4All_KFParticle_condorJob(), Fun4All_KFParticle_singleFile(), and parseDecayDescriptor().
void KFParticle_sPHENIX::setNumMVAPars (unsigned int nPars) inline
Definition at line 241 of file KFParticle_sPHENIX.h.
View newest version in sPHENIX GitHub at line 241 of file KFParticle_sPHENIX.h
References KFParticle_MVA::m_nPars.
void KFParticle_sPHENIX::setOutputName (const std::string & name) inline
Definition at line 264 of file KFParticle_sPHENIX.h.
View newest version in sPHENIX GitHub at line 264 of file KFParticle_sPHENIX.h
References m_outfile_name, and name.
Referenced by Fun4All_KFParticle_advanced(), Fun4All_KFParticle_basic(), Fun4All_KFParticle_condorJob(), Fun4All_KFParticle_singleFile(), Fun4All_KFParticle_standardContainers(), KFParticle_D0_Reco(), KFParticle_Lambdac_Reco(), and KFParticle_Upsilon_Reco().
void KFParticle_sPHENIX::setTrackMapNodeName (const std::string & trk_map_node_name) inline
Use alternate vertex and track fitters.
Definition at line 278 of file KFParticle_sPHENIX.h.
View newest version in sPHENIX GitHub at line 278 of file KFParticle_sPHENIX.h
References KFParticle_Tools::m_trk_map_node_name, and KFParticle_truthAndDetTools::m_trk_map_node_name_nTuple.
void KFParticle_sPHENIX::setVertexMapNodeName (const std::string & vtx_map_node_name) inline
Use alternate vertex and track fitters.
Definition at line 275 of file KFParticle_sPHENIX.h.
View newest version in sPHENIX GitHub at line 275 of file KFParticle_sPHENIX.h
References KFParticle_Tools::m_vtx_map_node_name, and KFParticle_truthAndDetTools::m_vtx_map_node_name_nTuple.
Referenced by Fun4All_KFParticle_advanced(), Fun4All_KFParticle_condorJob(), and Fun4All_KFParticle_standardContainers().
void KFParticle_sPHENIX::useFakePrimaryVertex (bool use_fake) inline
Definition at line 185 of file KFParticle_sPHENIX.h.
View newest version in sPHENIX GitHub at line 185 of file KFParticle_sPHENIX.h
References KFParticle_eventReconstruction::m_use_fake_pv.
void KFParticle_sPHENIX::useIntermediateName (bool use_intermediate_name) inline
Definition at line 82 of file KFParticle_sPHENIX.h.
View newest version in sPHENIX GitHub at line 82 of file KFParticle_sPHENIX.h
References KFParticle_nTuple::m_use_intermediate_name.
void KFParticle_sPHENIX::useMVA (bool require_mva) inline
Definition at line 239 of file KFParticle_sPHENIX.h.
View newest version in sPHENIX GitHub at line 239 of file KFParticle_sPHENIX.h
References m_require_mva.
Member Data Documentation
bool KFParticle_sPHENIX::m_constrain_to_vertex_sPHENIX private
Definition at line 282 of file KFParticle_sPHENIX.h.
View newest version in sPHENIX GitHub at line 282 of file KFParticle_sPHENIX.h
Referenced by constrainToPrimaryVertex(), printParticles(), and process_event().
std::string KFParticle_sPHENIX::m_decayDescriptor private
Definition at line 288 of file KFParticle_sPHENIX.h.
View newest version in sPHENIX GitHub at line 288 of file KFParticle_sPHENIX.h
Referenced by Init(), parseDecayDescriptor(), and setDecayDescriptor().
bool KFParticle_sPHENIX::m_has_intermediates_sPHENIX private
Definition at line 281 of file KFParticle_sPHENIX.h.
View newest version in sPHENIX GitHub at line 281 of file KFParticle_sPHENIX.h
Referenced by hasIntermediateStates(), printParticles(), and process_event().
TFile* KFParticle_sPHENIX::m_outfile private
Definition at line 287 of file KFParticle_sPHENIX.h.
View newest version in sPHENIX GitHub at line 287 of file KFParticle_sPHENIX.h
Referenced by End(), and process_event().
std::string KFParticle_sPHENIX::m_outfile_name private
Definition at line 286 of file KFParticle_sPHENIX.h.
View newest version in sPHENIX GitHub at line 286 of file KFParticle_sPHENIX.h
Referenced by Init(), process_event(), and setOutputName().
bool KFParticle_sPHENIX::m_require_mva private
Definition at line 283 of file KFParticle_sPHENIX.h.
View newest version in sPHENIX GitHub at line 283 of file KFParticle_sPHENIX.h
Referenced by Init(), and useMVA().
bool KFParticle_sPHENIX::m_save_dst private
Definition at line 284 of file KFParticle_sPHENIX.h.
View newest version in sPHENIX GitHub at line 284 of file KFParticle_sPHENIX.h
Referenced by Init(), process_event(), and saveDST().
bool KFParticle_sPHENIX::m_save_output private
Definition at line 285 of file KFParticle_sPHENIX.h.
View newest version in sPHENIX GitHub at line 285 of file KFParticle_sPHENIX.h
Referenced by End(), Init(), process_event(), and saveOutput().
const int KFParticle_sPHENIX::max_particles = 99 static
Definition at line 74 of file KFParticle_sPHENIX.h.
View newest version in sPHENIX GitHub at line 74 of file KFParticle_sPHENIX.h
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/KFParticle_sPHENIX/KFParticle_sPHENIX.h
coresoftware/blob/master/offline/packages/KFParticle_sPHENIX/KFParticle_sPHENIX.cc