Analysis Software: PHG4CylinderGeom_Spacalv3 Class Reference
PHG4CylinderGeom_Spacalv3 Class Reference
#include <coresoftware/blob/master/simulation/g4simulation/g4detectors/PHG4CylinderGeom_Spacalv3.h>
Classes
class geom_tower
class scint_id_coder
compact ID of each fiber in 32bit PHG4Hit::set_scint_id(). Buffer the result for repeated use.
Public Types
typedef std::map< int, geom_tower > tower_map_t
Public Member Functions
PHG4CylinderGeom_Spacalv3 ()
~PHG4CylinderGeom_Spacalv3 () override
void identify (std::ostream &os=std::cout) const override
void Print (Option_t *option="") const override
void SetDefault () override
void ImportParameters (const PHParameters &param) override
load parameters from PHParameters, which interface to Database/XML/ROOT files
double get_sidewall_outer_torr () const
void set_sidewall_outer_torr (double sidewallOuterTorr)
double get_sidewall_thickness () const
void set_sidewall_thickness (double sidewallThickness)
std::string get_sidewall_mat () const
void set_sidewall_mat (const std::string &absorberMat)
int get_max_phi_bin_in_sec () const
void set_max_phi_bin_in_sec (int maxPhiBinInSec)
const std::string & get_divider_mat () const
void set_divider_mat (const std::string &dividerMat)
double get_divider_width () const
void set_divider_width (double dividerWidth)
void load_demo_sector_tower_map1 ()
void load_demo_sector_tower_map2 ()
void load_demo_sector_tower_map4 ()
const tower_map_t & get_sector_tower_map () const
double get_tower_radial_position (const geom_tower &tower) const
get approximate radial position of tower
void subtower_consistency_check () const
check that all towers has consistent sub-tower divider
int get_n_subtower_eta () const
sub-tower divider along the polar direction
int get_n_subtower_phi () const
sub-tower divider along the azimuthal direction
double get_max_lightguide_height () const
max tolerance needed for the light guide
virtual std::pair< int, int > get_tower_z_phi_ID (const int tower_ID, const int sector_ID) const
Public Member Functions inherited from PHG4CylinderGeom_Spacalv2
PHG4CylinderGeom_Spacalv2 ()
~PHG4CylinderGeom_Spacalv2 () override
void Print (Option_t *option="") const override
int get_azimuthal_n_sec () const override
virtual void set_azimuthal_n_sec (int azimuthalNSec)
double get_azimuthal_tilt () const
azimuthal tilt in rad
void set_azimuthal_tilt (double azimuthalTilt)
azimuthal tilt in rad
bool is_azimuthal_seg_visible () const override
virtual void set_azimuthal_seg_visible (bool b=true)
double get_polar_taper_ratio () const
void set_polar_taper_ratio (double polarTaperRatio)
double get_half_polar_taper_angle () const
double get_sec_azimuthal_width () const
double get_sec_depth () const
double get_block_width () const
double get_block_depth () const
double get_assembly_spacing () const
void set_assembly_spacing (double assemblySpacing)
double get_reg_fiber_grid_distance_taper () const
regulated fiber distance in the tapering direction
double get_reg_fiber_grid_distance_nontaper () const
regulated fiber distance in the non-tapering direction
Public Member Functions inherited from PHG4CylinderGeom_Spacalv1
PHG4CylinderGeom_Spacalv1 ()
~PHG4CylinderGeom_Spacalv1 () override
void Print (Option_t *option="") const override
double get_max_radius () const
double get_half_radius () const
double get_length () const
double get_xpos () const
void set_xpos (double x)
double get_ypos () const
void set_ypos (double y)
double get_zpos () const
void set_zpos (double z)
double get_fiber_outer_r () const
double get_fiber_clading_thickness () const
void set_fiber_clading_thickness (double fiberCladingThickness)
double get_fiber_core_diameter () const
void set_fiber_core_diameter (double fiberCoreDiameter)
double get_fiber_distance () const
void set_fiber_distance (double fiberDistance)
std::string get_absorber_mat () const
void set_absorber_mat (const std::string &absorberMat)
std::string get_fiber_clading_mat () const
void set_fiber_clading_mat (const std::string &fiberCladingMat)
std::string get_fiber_core_mat () const
void set_fiber_core_mat (const std::string &fiberCoreMat)
virtual double get_azimuthal_distance () const
virtual double get_z_distance () const
const sector_map_t & get_sector_map () const
sector map sector_ID -> azimuthal rotation.
sector_map_t & get_sector_map ()
sector map sector_ID -> azimuthal rotation.
void init_default_sector_map ()
load a default map that populate all the sectors
double get_fiber_core_step_size () const
config_t get_config () const
void set_config (config_t c)
bool is_virualize_fiber () const
void set_virualize_fiber (bool virualizeFiber=true)
int get_construction_verbose () const
void set_construction_verbose (int constructionVerbose)
Public Member Functions inherited from PHG4CylinderGeomv2
PHG4CylinderGeomv2 ()
PHG4CylinderGeomv2 (const double r, const double zmi, const double zma, const double thickn, const int n_scint)
~PHG4CylinderGeomv2 () override
void identify (std::ostream &os=std::cout) const override
void set_nscint (const int i) override
int get_nscint () const override
void ImportParameters (const PHParameters &param) override
load parameters from PHParameters, which interface to Database/XML/ROOT files
Public Member Functions inherited from PHG4CylinderGeomv1
PHG4CylinderGeomv1 ()
PHG4CylinderGeomv1 (const double r, const double zmi, const double zma, const double thickn)
~PHG4CylinderGeomv1 () override
int get_layer () const override
double get_radius () const override
double get_thickness () const override
double get_zmin () const override
double get_zmax () const override
void set_layer (const int i) override
void set_radius (const double r) override
void set_thickness (const double t) override
void set_zmin (const double z) override
void set_zmax (const double z) override
Public Member Functions inherited from PHG4CylinderGeom
~PHG4CylinderGeom () override
virtual double get_tiltangle () const
virtual double get_phi_slat_zero () const
virtual void set_tiltangle (const double)
virtual void set_phi_slat_zero (const double)
virtual void find_segment_center (const int, const int, double[])
virtual void find_strip_center (const int, const int, const int, const int, double[])
virtual void find_strip_index_values (const int, const double, const double, int &, int &)
virtual void find_strip_center_local_coords (const int, const int, const int, double[])
virtual double get_strip_y_spacing () const
virtual double get_strip_z_spacing () const
virtual double get_strip_tilt () const
virtual int get_N_strip_columns () const
virtual int get_N_strips_per_column () const
virtual int get_N_sensors_in_layer () const
virtual double get_pixel_z () const
virtual double get_pixel_x () const
virtual double get_pixel_thickness () const
Public Member Functions inherited from PHObject
PHObject ()
ctor
~PHObject () override
dtor
virtual PHObject * CloneMe () const
Virtual copy constructor.
virtual PHObject * clone () const final
PHObject * Clone (const char *newname="") const final
void Copy (TObject &object) const final
virtual void Reset ()
Clear Event.
virtual int isValid () const
isValid returns non zero if object contains vailid data
virtual int Integrate () const
virtual int Integrate (PHObject *)
virtual void CopyFrom (const PHObject *obj)
Protected Attributes
double sidewall_thickness
double sidewall_outer_torr
std::string sidewall_mat
int max_phi_bin_in_sec
tower_map_t sector_tower_map
double divider_width
wdith along the approximate radial direction
std::string divider_mat
material for divider
Protected Attributes inherited from PHG4CylinderGeom_Spacalv2
int azimuthal_n_sec
double azimuthal_tilt
azimuthal tilt in rad
bool azimuthal_seg_visible
double polar_taper_ratio
double assembly_spacing
Protected Attributes inherited from PHG4CylinderGeom_Spacalv1
std::string absorber_mat
std::string fiber_core_mat
std::string fiber_clading_mat
double xpos
double ypos
double zpos
double fiber_core_diameter
double fiber_clading_thickness
double fiber_distance
config_t config
bool virualize_fiber
int construction_verbose
sector_map_t sector_map
sector map sector_ID -> azimuthal rotation.
Protected Attributes inherited from PHG4CylinderGeomv2
int nscint = -9999
Protected Attributes inherited from PHG4CylinderGeomv1
int layer = -1
double radius = NAN
double zmin = NAN
double zmax = NAN
double thickness = NAN
Additional Inherited Members
Protected Member Functions inherited from PHG4CylinderGeom
PHG4CylinderGeom ()
Detailed Description
Definition at line 24 of file PHG4CylinderGeom_Spacalv3.h.
View newest version in sPHENIX GitHub at line 24 of file PHG4CylinderGeom_Spacalv3.h
Member Typedef Documentation
typedef std::map<int, geom_tower> PHG4CylinderGeom_Spacalv3::tower_map_t
Definition at line 183 of file PHG4CylinderGeom_Spacalv3.h.
View newest version in sPHENIX GitHub at line 183 of file PHG4CylinderGeom_Spacalv3.h
Constructor & Destructor Documentation
PHG4CylinderGeom_Spacalv3::PHG4CylinderGeom_Spacalv3 ()
Definition at line 30 of file PHG4CylinderGeom_Spacalv3.cc.
View newest version in sPHENIX GitHub at line 30 of file PHG4CylinderGeom_Spacalv3.cc
References SetDefault().
PHG4CylinderGeom_Spacalv3::~PHG4CylinderGeom_Spacalv3 () override
Definition at line 35 of file PHG4CylinderGeom_Spacalv3.cc.
View newest version in sPHENIX GitHub at line 35 of file PHG4CylinderGeom_Spacalv3.cc
References sector_tower_map.
Member Function Documentation
const std::string& PHG4CylinderGeom_Spacalv3::get_divider_mat () const inline
Definition at line 90 of file PHG4CylinderGeom_Spacalv3.h.
View newest version in sPHENIX GitHub at line 90 of file PHG4CylinderGeom_Spacalv3.h
References divider_mat.
Referenced by DumpPHG4CylinderGeomContainer::process_Node().
double PHG4CylinderGeom_Spacalv3::get_divider_width () const inline
Definition at line 100 of file PHG4CylinderGeom_Spacalv3.h.
View newest version in sPHENIX GitHub at line 100 of file PHG4CylinderGeom_Spacalv3.h
References divider_width.
Referenced by PHG4SpacalPrototype4Detector::Construct_AzimuthalSeg(), PHG4FullProjTiltedSpacalDetector::Construct_AzimuthalSeg(), and DumpPHG4CylinderGeomContainer::process_Node().
double PHG4CylinderGeom_Spacalv3::get_max_lightguide_height () const
max tolerance needed for the light guide
Definition at line 433 of file PHG4CylinderGeom_Spacalv3.cc.
View newest version in sPHENIX GitHub at line 433 of file PHG4CylinderGeom_Spacalv3.cc
References h, it, and sector_tower_map.
Referenced by PHG4SpacalPrototypeDetector::Construct_AzimuthalSeg(), PHG4SpacalPrototype4Detector::ConstructMe(), PHG4SpacalPrototypeDetector::ConstructMe(), and Print().
int PHG4CylinderGeom_Spacalv3::get_max_phi_bin_in_sec () const inline
Definition at line 79 of file PHG4CylinderGeom_Spacalv3.h.
View newest version in sPHENIX GitHub at line 79 of file PHG4CylinderGeom_Spacalv3.h
References max_phi_bin_in_sec.
Referenced by PHG4SpacalDetector::AddCellGeometryNode(), PHG4SpacalPrototype4Detector::Construct_AzimuthalSeg(), PHG4FullProjTiltedSpacalDetector::Construct_AzimuthalSeg(), PHG4FullProjSpacalCellReco::InitRun(), Print(), and DumpPHG4CylinderGeomContainer::process_Node().
int PHG4CylinderGeom_Spacalv3::get_n_subtower_eta () const
sub-tower divider along the polar direction
Definition at line 418 of file PHG4CylinderGeom_Spacalv3.cc.
View newest version in sPHENIX GitHub at line 418 of file PHG4CylinderGeom_Spacalv3.cc
References assert, and sector_tower_map.
Referenced by PHG4SpacalDetector::AddCellGeometryNode(), PHG4FullProjSpacalCellReco::InitRun(), CaloWaveformSim::maphitetaphi(), PHG4SpacalSteppingAction::NoHitSteppingAction(), Print(), PHG4FullProjSpacalCellReco::process_event(), CaloWaveFormSim::process_g4hits(), and subtower_consistency_check().
int PHG4CylinderGeom_Spacalv3::get_n_subtower_phi () const
sub-tower divider along the azimuthal direction
Definition at line 425 of file PHG4CylinderGeom_Spacalv3.cc.
View newest version in sPHENIX GitHub at line 425 of file PHG4CylinderGeom_Spacalv3.cc
References assert, and sector_tower_map.
Referenced by PHG4SpacalDetector::AddCellGeometryNode(), PHG4FullProjSpacalCellReco::InitRun(), CaloWaveformSim::maphitetaphi(), PHG4SpacalSteppingAction::NoHitSteppingAction(), Print(), PHG4FullProjSpacalCellReco::process_event(), CaloWaveFormSim::process_g4hits(), and subtower_consistency_check().
const tower_map_t& PHG4CylinderGeom_Spacalv3::get_sector_tower_map () const inline
Definition at line 193 of file PHG4CylinderGeom_Spacalv3.h.
View newest version in sPHENIX GitHub at line 193 of file PHG4CylinderGeom_Spacalv3.h
References sector_tower_map.
Referenced by PHG4SpacalDetector::AddCellGeometryNode(), PHG4SpacalPrototype4Detector::Construct_AzimuthalSeg(), PHG4SpacalPrototypeDetector::Construct_AzimuthalSeg(), PHG4FullProjTiltedSpacalDetector::Construct_AzimuthalSeg(), PHG4FullProjSpacalDetector::Construct_AzimuthalSeg(), PHG4FullProjSpacalCellReco::InitRun(), CaloWaveformSim::maphitetaphi(), PHG4SpacalSteppingAction::NoHitSteppingAction(), PHG4FullProjSpacalCellReco::process_event(), CaloWaveFormSim::process_g4hits(), and DumpPHG4CylinderGeomContainer::process_Node().
std::string PHG4CylinderGeom_Spacalv3::get_sidewall_mat () const inline
Definition at line 68 of file PHG4CylinderGeom_Spacalv3.h.
View newest version in sPHENIX GitHub at line 68 of file PHG4CylinderGeom_Spacalv3.h
References sidewall_mat.
Referenced by Print(), and DumpPHG4CylinderGeomContainer::process_Node().
double PHG4CylinderGeom_Spacalv3::get_sidewall_outer_torr () const inline
Definition at line 44 of file PHG4CylinderGeom_Spacalv3.h.
View newest version in sPHENIX GitHub at line 44 of file PHG4CylinderGeom_Spacalv3.h
References sidewall_outer_torr.
Referenced by PHG4SpacalPrototype4Detector::Construct_AzimuthalSeg(), PHG4FullProjTiltedSpacalDetector::Construct_AzimuthalSeg(), PHG4FullProjSpacalDetector::Construct_AzimuthalSeg(), get_tower_radial_position(), Print(), and DumpPHG4CylinderGeomContainer::process_Node().
double PHG4CylinderGeom_Spacalv3::get_sidewall_thickness () const inline
Definition at line 56 of file PHG4CylinderGeom_Spacalv3.h.
View newest version in sPHENIX GitHub at line 56 of file PHG4CylinderGeom_Spacalv3.h
References sidewall_thickness.
Referenced by PHG4SpacalPrototype4Detector::Construct_AzimuthalSeg(), PHG4SpacalPrototypeDetector::Construct_AzimuthalSeg(), PHG4FullProjTiltedSpacalDetector::Construct_AzimuthalSeg(), PHG4FullProjSpacalDetector::Construct_AzimuthalSeg(), get_tower_radial_position(), Print(), and DumpPHG4CylinderGeomContainer::process_Node().
double PHG4CylinderGeom_Spacalv3::get_tower_radial_position (const geom_tower & tower) const
get approximate radial position of tower
Definition at line 359 of file PHG4CylinderGeom_Spacalv3.cc.
View newest version in sPHENIX GitHub at line 359 of file PHG4CylinderGeom_Spacalv3.cc
References assert, PHG4CylinderGeom_Spacalv3::geom_tower::centralY, PHG4CylinderGeom_Spacalv2::get_assembly_spacing(), PHG4CylinderGeom_Spacalv2::get_azimuthal_n_sec(), PHG4CylinderGeom_Spacalv2::get_azimuthal_tilt(), PHG4CylinderGeom_Spacalv1::get_config(), PHG4CylinderGeom_Spacalv1::get_construction_verbose(), PHG4CylinderGeom_Spacalv1::get_half_radius(), get_sidewall_outer_torr(), get_sidewall_thickness(), PHG4CylinderGeom_Spacalv1::kFullProjective_2DTaper, PHG4CylinderGeom_Spacalv1::kFullProjective_2DTaper_SameLengthFiberPerTower, PHG4CylinderGeom_Spacalv1::kFullProjective_2DTaper_Tilted, PHG4CylinderGeom_Spacalv1::kFullProjective_2DTaper_Tilted_SameLengthFiberPerTower, and Print().
Referenced by PHG4SpacalDetector::AddCellGeometryNode(), and PHG4FullProjSpacalCellReco::InitRun().
std::pair< int, int > PHG4CylinderGeom_Spacalv3::get_tower_z_phi_ID (const int tower_ID, const int sector_ID) const virtual
convert tower_ID + sector ID to eta and z bins as in other cylindrical calorimeters
Returns
: a std::pair of zbin and phibin number
Definition at line 327 of file PHG4CylinderGeom_Spacalv3.cc.
View newest version in sPHENIX GitHub at line 327 of file PHG4CylinderGeom_Spacalv3.cc
References assert, PHG4CylinderGeom_Spacalv1::get_config(), PHG4CylinderGeom_Spacalv1::kFullProjective_2DTaper, PHG4CylinderGeom_Spacalv1::kFullProjective_2DTaper_SameLengthFiberPerTower, PHG4CylinderGeom_Spacalv1::kFullProjective_2DTaper_Tilted, PHG4CylinderGeom_Spacalv1::kFullProjective_2DTaper_Tilted_SameLengthFiberPerTower, max_phi_bin_in_sec, and Print().
Referenced by PHG4SpacalDetector::AddCellGeometryNode(), PHG4FullProjSpacalCellReco::InitRun(), CaloWaveformSim::maphitetaphi(), PHG4SpacalSteppingAction::NoHitSteppingAction(), PHG4FullProjSpacalCellReco::process_event(), EMCalAna::process_event_SF(), and CaloWaveFormSim::process_g4hits().
void PHG4CylinderGeom_Spacalv3::identify (std::ostream & os = std::cout) const override virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from PHG4CylinderGeom_Spacalv2.
Definition at line 40 of file PHG4CylinderGeom_Spacalv3.cc.
View newest version in sPHENIX GitHub at line 40 of file PHG4CylinderGeom_Spacalv3.cc
References PHG4CylinderGeom_Spacalv2::azimuthal_n_sec, PHG4CylinderGeomv1::layer, PHG4CylinderGeomv2::nscint, PHG4CylinderGeomv1::radius, sector_tower_map, PHG4CylinderGeomv1::thickness, PHG4CylinderGeomv1::zmax, and PHG4CylinderGeomv1::zmin.
Referenced by PHG4SpacalDetector::AddCellGeometryNode(), and PHG4FullProjSpacalCellReco::InitRun().
void PHG4CylinderGeom_Spacalv3::ImportParameters (const PHParameters & param) override virtual
load parameters from PHParameters, which interface to Database/XML/ROOT files
Reimplemented from PHG4CylinderGeom_Spacalv2.
Definition at line 112 of file PHG4CylinderGeom_Spacalv3.cc.
View newest version in sPHENIX GitHub at line 112 of file PHG4CylinderGeom_Spacalv3.cc
References divider_mat, divider_width, PHParameters::exist_double_param(), PHParameters::exist_int_param(), PHParameters::exist_string_param(), PHParameters::get_double_param(), PHParameters::get_int_param(), PHParameters::get_string_param(), i, PHG4CylinderGeom_Spacalv3::geom_tower::id, PHG4CylinderGeom_Spacalv2::ImportParameters(), PHG4CylinderGeom_Spacalv3::geom_tower::ImportParameters(), max_phi_bin_in_sec, n, prefix, sector_tower_map, sidewall_mat, sidewall_outer_torr, sidewall_thickness, and t.
Referenced by PHG4SpacalPrototype4Detector::ConstructMe(), PHG4SpacalPrototypeDetector::ConstructMe(), PHG4FullProjSpacalDetector::PHG4FullProjSpacalDetector(), and PHG4FullProjTiltedSpacalDetector::PHG4FullProjTiltedSpacalDetector().
void PHG4CylinderGeom_Spacalv3::load_demo_sector_tower_map1 ()
Definition at line 446 of file PHG4CylinderGeom_Spacalv3.cc.
View newest version in sPHENIX GitHub at line 446 of file PHG4CylinderGeom_Spacalv3.cc
References PHG4CylinderGeom_Spacalv2::assembly_spacing, PHG4CylinderGeom_Spacalv2::azimuthal_n_sec, PHG4CylinderGeom_Spacalv2::azimuthal_seg_visible, PHG4CylinderGeom_Spacalv2::azimuthal_tilt, PHG4CylinderGeom_Spacalv3::geom_tower::centralX, PHG4CylinderGeom_Spacalv3::geom_tower::centralY, PHG4CylinderGeom_Spacalv3::geom_tower::centralZ, PHG4CylinderGeom_Spacalv3::geom_tower::id, max_phi_bin_in_sec, PHG4CylinderGeom_Spacalv3::geom_tower::ModuleSkinThickness, PHG4CylinderGeom_Spacalv3::geom_tower::NFiberX, PHG4CylinderGeom_Spacalv3::geom_tower::NFiberY, PHG4CylinderGeom_Spacalv3::geom_tower::pAlp1, PHG4CylinderGeom_Spacalv3::geom_tower::pAlp2, PHG4CylinderGeom_Spacalv3::geom_tower::pDx1, PHG4CylinderGeom_Spacalv3::geom_tower::pDx2, PHG4CylinderGeom_Spacalv3::geom_tower::pDx3, PHG4CylinderGeom_Spacalv3::geom_tower::pDx4, PHG4CylinderGeom_Spacalv3::geom_tower::pDy1, PHG4CylinderGeom_Spacalv3::geom_tower::pDy2, PHG4CylinderGeom_Spacalv3::geom_tower::pDz, PHG4CylinderGeom_Spacalv2::polar_taper_ratio, PHG4CylinderGeom_Spacalv3::geom_tower::pPhi, PHG4CylinderGeom_Spacalv3::geom_tower::pRotationAngleX, PHG4CylinderGeom_Spacalv3::geom_tower::pTheta, PHG4CylinderGeomv1::radius, PHG4CylinderGeom_Spacalv1::sector_map, sector_tower_map, sidewall_outer_torr, sidewall_thickness, PHG4CylinderGeomv1::thickness, PHG4CylinderGeomv1::zmax, and PHG4CylinderGeomv1::zmin.
void PHG4CylinderGeom_Spacalv3::load_demo_sector_tower_map2 ()
Definition at line 520 of file PHG4CylinderGeom_Spacalv3.cc.
View newest version in sPHENIX GitHub at line 520 of file PHG4CylinderGeom_Spacalv3.cc
References PHG4CylinderGeom_Spacalv2::assembly_spacing, PHG4CylinderGeom_Spacalv2::azimuthal_n_sec, PHG4CylinderGeom_Spacalv2::azimuthal_seg_visible, PHG4CylinderGeom_Spacalv2::azimuthal_tilt, PHG4CylinderGeom_Spacalv3::geom_tower::centralX, PHG4CylinderGeom_Spacalv3::geom_tower::centralY, PHG4CylinderGeom_Spacalv3::geom_tower::centralZ, PHG4CylinderGeom_Spacalv3::geom_tower::id, max_phi_bin_in_sec, PHG4CylinderGeom_Spacalv3::geom_tower::ModuleSkinThickness, PHG4CylinderGeom_Spacalv3::geom_tower::NFiberX, PHG4CylinderGeom_Spacalv3::geom_tower::NFiberY, PHG4CylinderGeom_Spacalv3::geom_tower::pAlp1, PHG4CylinderGeom_Spacalv3::geom_tower::pAlp2, PHG4CylinderGeom_Spacalv3::geom_tower::pDx1, PHG4CylinderGeom_Spacalv3::geom_tower::pDx2, PHG4CylinderGeom_Spacalv3::geom_tower::pDx3, PHG4CylinderGeom_Spacalv3::geom_tower::pDx4, PHG4CylinderGeom_Spacalv3::geom_tower::pDy1, PHG4CylinderGeom_Spacalv3::geom_tower::pDy2, PHG4CylinderGeom_Spacalv3::geom_tower::pDz, PHG4CylinderGeom_Spacalv2::polar_taper_ratio, PHG4CylinderGeom_Spacalv3::geom_tower::pPhi, PHG4CylinderGeom_Spacalv3::geom_tower::pRotationAngleX, PHG4CylinderGeom_Spacalv3::geom_tower::pTheta, PHG4CylinderGeomv1::radius, PHG4CylinderGeom_Spacalv1::sector_map, sector_tower_map, sidewall_outer_torr, sidewall_thickness, PHG4CylinderGeomv1::thickness, PHG4CylinderGeomv1::zmax, and PHG4CylinderGeomv1::zmin.
void PHG4CylinderGeom_Spacalv3::load_demo_sector_tower_map4 ()
Definition at line 736 of file PHG4CylinderGeom_Spacalv3.cc.
View newest version in sPHENIX GitHub at line 736 of file PHG4CylinderGeom_Spacalv3.cc
References PHG4CylinderGeom_Spacalv2::assembly_spacing, assert, PHG4CylinderGeom_Spacalv2::azimuthal_n_sec, PHG4CylinderGeom_Spacalv2::azimuthal_seg_visible, PHG4CylinderGeom_Spacalv2::azimuthal_tilt, PHG4CylinderGeom_Spacalv3::geom_tower::centralX, PHG4CylinderGeom_Spacalv3::geom_tower::centralY, PHG4CylinderGeom_Spacalv3::geom_tower::centralZ, double(), PHG4CylinderGeom_Spacalv1::fiber_clading_thickness, PHG4CylinderGeom_Spacalv1::fiber_core_diameter, PHG4CylinderGeom_Spacalv2::get_azimuthal_n_sec(), PHG4CylinderGeom_Spacalv3::geom_tower::id, max_phi_bin_in_sec, PHG4CylinderGeom_Spacalv3::geom_tower::ModuleSkinThickness, PHG4CylinderGeom_Spacalv3::geom_tower::NFiberX, PHG4CylinderGeom_Spacalv3::geom_tower::NFiberY, nx, ny, PHG4CylinderGeom_Spacalv3::geom_tower::pAlp1, PHG4CylinderGeom_Spacalv3::geom_tower::pAlp2, PHG4CylinderGeom_Spacalv3::geom_tower::pDx1, PHG4CylinderGeom_Spacalv3::geom_tower::pDx2, PHG4CylinderGeom_Spacalv3::geom_tower::pDx3, PHG4CylinderGeom_Spacalv3::geom_tower::pDx4, PHG4CylinderGeom_Spacalv3::geom_tower::pDy1, PHG4CylinderGeom_Spacalv3::geom_tower::pDy2, PHG4CylinderGeom_Spacalv3::geom_tower::pDz, PHG4CylinderGeom_Spacalv2::polar_taper_ratio, PHG4CylinderGeom_Spacalv3::geom_tower::pPhi, PHG4CylinderGeom_Spacalv3::geom_tower::pRotationAngleX, PHG4CylinderGeom_Spacalv3::geom_tower::pTheta, PHG4CylinderGeomv1::radius, PHG4CylinderGeom_Spacalv1::sector_map, sector_tower_map, sidewall_outer_torr, sidewall_thickness, PHG4CylinderGeomv1::thickness, twopi, y, PHG4CylinderGeomv1::zmax, and PHG4CylinderGeomv1::zmin.
void PHG4CylinderGeom_Spacalv3::Print (Option_t * option = "") const override
Definition at line 55 of file PHG4CylinderGeom_Spacalv3.cc.
View newest version in sPHENIX GitHub at line 55 of file PHG4CylinderGeom_Spacalv3.cc
References PHG4CylinderGeom_Spacalv1::get_construction_verbose(), get_max_lightguide_height(), get_max_phi_bin_in_sec(), get_n_subtower_eta(), get_n_subtower_phi(), get_sidewall_mat(), get_sidewall_outer_torr(), get_sidewall_thickness(), Eventiterator::identify(), it, PHG4CylinderGeom_Spacalv2::Print(), sector_tower_map, and subtower_consistency_check().
Referenced by get_tower_radial_position(), get_tower_z_phi_ID(), PHG4FullProjSpacalDetector::Print(), PHG4FullProjTiltedSpacalDetector::Print(), PHG4SpacalPrototype4Detector::Print(), and PHG4SpacalPrototypeDetector::Print().
void PHG4CylinderGeom_Spacalv3::set_divider_mat (const std::string & dividerMat) inline
Definition at line 95 of file PHG4CylinderGeom_Spacalv3.h.
View newest version in sPHENIX GitHub at line 95 of file PHG4CylinderGeom_Spacalv3.h
References divider_mat.
void PHG4CylinderGeom_Spacalv3::set_divider_width (double dividerWidth) inline
Definition at line 105 of file PHG4CylinderGeom_Spacalv3.h.
View newest version in sPHENIX GitHub at line 105 of file PHG4CylinderGeom_Spacalv3.h
References divider_width.
void PHG4CylinderGeom_Spacalv3::set_max_phi_bin_in_sec (int maxPhiBinInSec) inline
Definition at line 85 of file PHG4CylinderGeom_Spacalv3.h.
View newest version in sPHENIX GitHub at line 85 of file PHG4CylinderGeom_Spacalv3.h
References max_phi_bin_in_sec.
void PHG4CylinderGeom_Spacalv3::set_sidewall_mat (const std::string & absorberMat) inline
Definition at line 74 of file PHG4CylinderGeom_Spacalv3.h.
View newest version in sPHENIX GitHub at line 74 of file PHG4CylinderGeom_Spacalv3.h
References sidewall_mat.
void PHG4CylinderGeom_Spacalv3::set_sidewall_outer_torr (double sidewallOuterTorr) inline
Definition at line 50 of file PHG4CylinderGeom_Spacalv3.h.
View newest version in sPHENIX GitHub at line 50 of file PHG4CylinderGeom_Spacalv3.h
References sidewall_outer_torr.
void PHG4CylinderGeom_Spacalv3::set_sidewall_thickness (double sidewallThickness) inline
Definition at line 62 of file PHG4CylinderGeom_Spacalv3.h.
View newest version in sPHENIX GitHub at line 62 of file PHG4CylinderGeom_Spacalv3.h
References sidewall_thickness.
void PHG4CylinderGeom_Spacalv3::SetDefault () override virtual
Reimplemented from PHG4CylinderGeom_Spacalv2.
Definition at line 93 of file PHG4CylinderGeom_Spacalv3.cc.
View newest version in sPHENIX GitHub at line 93 of file PHG4CylinderGeom_Spacalv3.cc
References divider_mat, divider_width, max_phi_bin_in_sec, PHG4CylinderGeom_Spacalv2::SetDefault(), sidewall_mat, sidewall_outer_torr, and sidewall_thickness.
Referenced by PHG4CylinderGeom_Spacalv3().
void PHG4CylinderGeom_Spacalv3::subtower_consistency_check () const
check that all towers has consistent sub-tower divider
Definition at line 398 of file PHG4CylinderGeom_Spacalv3.cc.
View newest version in sPHENIX GitHub at line 398 of file PHG4CylinderGeom_Spacalv3.cc
References assert, PHG4CylinderGeom_Spacalv1::get_construction_verbose(), get_n_subtower_eta(), get_n_subtower_phi(), it, and sector_tower_map.
Referenced by PHG4SpacalDetector::AddCellGeometryNode(), PHG4SpacalPrototypeDetector::ConstructMe(), PHG4SpacalPrototype4Detector::ConstructMe(), PHG4FullProjSpacalCellReco::InitRun(), and Print().
Member Data Documentation
std::string PHG4CylinderGeom_Spacalv3::divider_mat protected
material for divider
Definition at line 269 of file PHG4CylinderGeom_Spacalv3.h.
View newest version in sPHENIX GitHub at line 269 of file PHG4CylinderGeom_Spacalv3.h
Referenced by get_divider_mat(), ImportParameters(), set_divider_mat(), and SetDefault().
double PHG4CylinderGeom_Spacalv3::divider_width protected
wdith along the approximate radial direction
Definition at line 267 of file PHG4CylinderGeom_Spacalv3.h.
View newest version in sPHENIX GitHub at line 267 of file PHG4CylinderGeom_Spacalv3.h
Referenced by get_divider_width(), ImportParameters(), set_divider_width(), and SetDefault().
int PHG4CylinderGeom_Spacalv3::max_phi_bin_in_sec protected
Definition at line 262 of file PHG4CylinderGeom_Spacalv3.h.
View newest version in sPHENIX GitHub at line 262 of file PHG4CylinderGeom_Spacalv3.h
Referenced by get_max_phi_bin_in_sec(), get_tower_z_phi_ID(), ImportParameters(), load_demo_sector_tower_map1(), load_demo_sector_tower_map2(), load_demo_sector_tower_map4(), set_max_phi_bin_in_sec(), and SetDefault().
tower_map_t PHG4CylinderGeom_Spacalv3::sector_tower_map protected
Definition at line 264 of file PHG4CylinderGeom_Spacalv3.h.
View newest version in sPHENIX GitHub at line 264 of file PHG4CylinderGeom_Spacalv3.h
Referenced by get_max_lightguide_height(), get_n_subtower_eta(), get_n_subtower_phi(), get_sector_tower_map(), identify(), ImportParameters(), load_demo_sector_tower_map1(), load_demo_sector_tower_map2(), load_demo_sector_tower_map4(), Print(), subtower_consistency_check(), and ~PHG4CylinderGeom_Spacalv3().
std::string PHG4CylinderGeom_Spacalv3::sidewall_mat protected
Definition at line 261 of file PHG4CylinderGeom_Spacalv3.h.
View newest version in sPHENIX GitHub at line 261 of file PHG4CylinderGeom_Spacalv3.h
Referenced by get_sidewall_mat(), ImportParameters(), set_sidewall_mat(), and SetDefault().
double PHG4CylinderGeom_Spacalv3::sidewall_outer_torr protected
Definition at line 260 of file PHG4CylinderGeom_Spacalv3.h.
View newest version in sPHENIX GitHub at line 260 of file PHG4CylinderGeom_Spacalv3.h
Referenced by get_sidewall_outer_torr(), ImportParameters(), load_demo_sector_tower_map1(), load_demo_sector_tower_map2(), load_demo_sector_tower_map4(), set_sidewall_outer_torr(), and SetDefault().
double PHG4CylinderGeom_Spacalv3::sidewall_thickness protected
Definition at line 259 of file PHG4CylinderGeom_Spacalv3.h.
View newest version in sPHENIX GitHub at line 259 of file PHG4CylinderGeom_Spacalv3.h
Referenced by get_sidewall_thickness(), ImportParameters(), load_demo_sector_tower_map1(), load_demo_sector_tower_map2(), load_demo_sector_tower_map4(), set_sidewall_thickness(), and SetDefault().
The documentation for this class was generated from the following files:
coresoftware/blob/master/simulation/g4simulation/g4detectors/PHG4CylinderGeom_Spacalv3.h
coresoftware/blob/master/simulation/g4simulation/g4detectors/PHG4CylinderGeom_Spacalv3.cc