Analysis Software: Fun4AllHistoManager Class Reference
Fun4AllHistoManager Class Reference
#include <coresoftware/blob/master/offline/framework/fun4all/Fun4AllHistoManager.h>
Public Member Functions
Fun4AllHistoManager (const std::string &name)
~Fun4AllHistoManager () override
void Print (const std::string &what="ALL") const override
bool registerHisto (const std::string &hname, TNamed *h1d, const int replace=0)
bool registerHisto (TNamed *h1d, const int replace=0)
template<typename T >
T * makeHisto (T *t)
int isHistoRegistered (const std::string &name) const
TNamed * getHisto (const std::string &hname) const
TNamed * getHisto (const unsigned int ihisto) const
std::string getHistoName (const unsigned int ihisto) const
unsigned int nHistos () const
void Reset ()
int dumpHistos (const std::string &filename="", const std::string &openmode="RECREATE")
void setOutfileName (const std::string &filename)
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Private Attributes
std::string outfilename
std::map< const std::string,
TNamed * > Histo
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = std::numeric_limits<int>::max() - 10
}
Protected Member Functions inherited from Fun4AllBase
Fun4AllBase (const std::string &name="NONAME")
Detailed Description
Definition at line 13 of file Fun4AllHistoManager.h.
View newest version in sPHENIX GitHub at line 13 of file Fun4AllHistoManager.h
Constructor & Destructor Documentation
Fun4AllHistoManager::Fun4AllHistoManager (const std::string & name) explicit
Definition at line 24 of file Fun4AllHistoManager.cc.
View newest version in sPHENIX GitHub at line 24 of file Fun4AllHistoManager.cc
Fun4AllHistoManager::~Fun4AllHistoManager () override
Definition at line 30 of file Fun4AllHistoManager.cc.
View newest version in sPHENIX GitHub at line 30 of file Fun4AllHistoManager.cc
References Histo.
Member Function Documentation
int Fun4AllHistoManager::dumpHistos (const std::string & filename = "", const std::string & openmode = "RECREATE")
Definition at line 40 of file Fun4AllHistoManager.cc.
View newest version in sPHENIX GitHub at line 40 of file Fun4AllHistoManager.cc
References filename, PHFlag::FlagExist(), PHFlag::get_IntFlag(), Histo, recoConsts::instance(), TDirectoryHelper::mkdir(), Fun4AllBase::Name(), outfilename, PHWHERE, Acts::Test::pos, runnumber, and Fun4AllBase::Verbosity().
Referenced by AnalyzeSimpleTree::End(), G4RawTowerTTree::End(), G4ScintillatorSlatTTree::End(), G4ScintillatorTowerTTree::End(), G4HitTTree::End(), G4VtxNtuple::End(), HCalCalibTree::End(), G4EdepNtuple::End(), CentralityValid::End(), CaloAna::End(), CaloWaveFormSim::End(), G4CellNtuple::End(), G4HitNtuple::End(), G4TowerNtuple::End(), G4SnglNtuple::End(), CaloValid::End(), HijingCountNtuple::End(), TowerTiming::End(), HitCountNtuple::End(), ShowerSize::End(), EdepNtuple::End(), TimingNtuple::End(), pi0EtaByEta::End(), HijingShowerSize::End(), SigmaTimingNtuple::End(), SynRadAna::End(), JetHepMCLoader::End(), tpc_hits::End(), fillSpaceChargeMaps::End(), TpcRawDataDecoder::End(), readDigitalCurrents::End(), Fun4All_G4_sPHENIX(), and QAHistManagerDef::saveQARootFile().
TNamed * Fun4AllHistoManager::getHisto (const std::string & hname) const
Definition at line 252 of file Fun4AllHistoManager.cc.
View newest version in sPHENIX GitHub at line 252 of file Fun4AllHistoManager.cc
References Histo, and Print().
Referenced by EMCalLikelihood::ApplyEMCalGanging(), TPCIntegratedCharge::End(), PHAna::End(), Proto4ShowerCalib::End(), TPCDataStreamEmulator::End(), Proto2ShowerCalib::End(), Proto3ShowerCalib::End(), Proto4SampleFrac::End(), Proto4TowerCalib::End(), TPCMLDataInterface::End(), EMCalLikelihood::End(), PHG4ScoringManager::End(), TPCFEETestRecov1::End(), ExampleAnalysisModule::End(), TpcPrototypeUnpacker::End(), EMCalAna::End(), EMCalCalib::End(), jetrtrack::End(), analysis::End(), QAG4SimulationCalorimeterSum::eval_trk_proj(), PHAna::fill_histos(), Fun4AllServer::getHisto(), TPCIntegratedCharge::process_event(), QAG4SimulationUpsilon::process_event(), QAG4SimulationDistortions::process_event(), QAG4SimulationVertex::process_event(), Proto4ShowerCalib::process_event(), QAG4SimulationCalorimeter::process_event(), QAG4SimulationKFParticle::process_event(), QAG4SimulationTracking::process_event(), QAG4SimulationCalorimeterSum::process_event(), TPCDataStreamEmulator::process_event(), Proto2ShowerCalib::process_event(), Proto3ShowerCalib::process_event(), SynRadAna::process_event(), QAG4Decayer::process_event(), Proto4SampleFrac::process_event(), Proto4TowerCalib::process_event(), truthDecayTester::process_event(), QAG4SimulationTruthDecay::process_event(), TPCMLDataInterface::process_event(), PHG4ScoringManager::process_event(), ExampleAnalysisModule::process_event(), TPCFEETestRecov1::process_event(), TpcPrototypeUnpacker::process_event(), JetHepMCLoader::process_event(), analysis::process_event(), jetrtrack::process_event(), QAG4SimulationCalorimeter::process_event_Cluster(), QAG4SimulationCalorimeterSum::process_event_Cluster(), QAG4SimulationCalorimeter::process_event_G4Hit(), EMCalAna::process_event_SF(), EMCalCalib::process_event_SF(), QAG4SimulationCalorimeter::process_event_Tower(), EMCalAna::process_event_Tower(), EMCalCalib::process_event_Tower(), QAG4SimulationCalorimeterSum::process_event_TrackProj(), QAG4SimulationJet::process_Spectrum(), SoftLeptonTaggingTruth::process_Spectrum(), and QAG4SimulationJet::process_TruthMatching().
TNamed * Fun4AllHistoManager::getHisto (const unsigned int ihisto) const
Definition at line 202 of file Fun4AllHistoManager.cc.
View newest version in sPHENIX GitHub at line 202 of file Fun4AllHistoManager.cc
References Histo, i, size, and Fun4AllBase::Verbosity().
std::string Fun4AllHistoManager::getHistoName (const unsigned int ihisto) const
Definition at line 227 of file Fun4AllHistoManager.cc.
View newest version in sPHENIX GitHub at line 227 of file Fun4AllHistoManager.cc
References Histo, i, size, and Fun4AllBase::Verbosity().
Referenced by Fun4AllServer::getHistoName().
int Fun4AllHistoManager::isHistoRegistered (const std::string & name) const
Definition at line 191 of file Fun4AllHistoManager.cc.
View newest version in sPHENIX GitHub at line 191 of file Fun4AllHistoManager.cc
References Histo.
Referenced by Fun4AllServer::isHistoRegistered().
template<typename T > T* Fun4AllHistoManager::makeHisto (T * t) inline
Definition at line 30 of file Fun4AllHistoManager.h.
View newest version in sPHENIX GitHub at line 30 of file Fun4AllHistoManager.h
References registerHisto(), and t.
Referenced by Fun4AllServer::makeHisto().
unsigned int Fun4AllHistoManager::nHistos () const inline
Definition at line 43 of file Fun4AllHistoManager.h.
View newest version in sPHENIX GitHub at line 43 of file Fun4AllHistoManager.h
References Histo.
Referenced by TPCIntegratedCharge::End(), PHAna::End(), Proto4ShowerCalib::End(), TPCDataStreamEmulator::End(), Proto3ShowerCalib::End(), Proto2ShowerCalib::End(), Proto4SampleFrac::End(), Proto4TowerCalib::End(), TPCMLDataInterface::End(), EMCalLikelihood::End(), PHG4ScoringManager::End(), TPCFEETestRecov1::End(), ExampleAnalysisModule::End(), TpcPrototypeUnpacker::End(), EMCalCalib::End(), EMCalAna::End(), jetrtrack::End(), and analysis::End().
void Fun4AllHistoManager::Print (const std::string & what = "ALL") const override virtual
Print out some info about this module.
Parameters
what can be used to specify what to print exactly.
Reimplemented from Fun4AllBase.
Definition at line 265 of file Fun4AllHistoManager.cc.
View newest version in sPHENIX GitHub at line 265 of file Fun4AllHistoManager.cc
References Histo, and Fun4AllBase::Name().
Referenced by getHisto().
bool Fun4AllHistoManager::registerHisto (const std::string & hname, TNamed * h1d, const int replace = 0)
Register histogram or TTree object For histograms, enforce error calculation and propagation
Definition at line 147 of file Fun4AllHistoManager.cc.
View newest version in sPHENIX GitHub at line 147 of file Fun4AllHistoManager.cc
References h1d, Histo, histoname, PHWHERE, Acts::Test::pos, SetDirectory(), and Fun4AllBase::Verbosity().
Referenced by PHAna::create_histos(), AnalyzeSimpleTree::Init(), G4RawTowerTTree::Init(), G4ScintillatorSlatTTree::Init(), G4ScintillatorTowerTTree::Init(), G4HitTTree::Init(), QAG4SimulationUpsilon::Init(), G4VtxNtuple::Init(), QAG4SimulationDistortions::Init(), CentralityValid::Init(), SynRadAna::Init(), QAG4SimulationVertex::Init(), Proto4ShowerCalib::Init(), tpc_hits::Init(), QAG4SimulationCalorimeter::Init(), QAG4SimulationKFParticle::Init(), QAG4SimulationTracking::Init(), Proto2ShowerCalib::Init(), Proto3ShowerCalib::Init(), Proto4TowerCalib::Init(), QAG4SimulationCalorimeterSum::Init(), Proto4SampleFrac::Init(), TpcRawDataDecoder::Init(), QAG4SimulationTruthDecay::Init(), truthDecayTester::Init(), QAG4Decayer::Init(), ExampleAnalysisModule::Init(), readDigitalCurrents::Init(), EMCalLikelihood::Init(), PHAJMaker::Init(), QAG4SimulationCalorimeter::Init_Cluster(), QAG4SimulationCalorimeterSum::Init_Cluster(), QAG4SimulationCalorimeter::Init_G4Hit(), EMCalAna::Init_SF(), EMCalCalib::Init_SF(), QAG4SimulationJet::Init_Spectrum(), SoftLeptonTaggingTruth::Init_Spectrum(), QAG4SimulationCalorimeter::Init_Tower(), EMCalAna::Init_Tower(), EMCalCalib::Init_Tower(), QAG4SimulationCalorimeterSum::Init_TrackProj(), QAG4SimulationJet::Init_TruthMatching(), TPCIntegratedCharge::InitRun(), TPCDataStreamEmulator::InitRun(), PHG4ScoringManager::InitRun(), TPCMLDataInterface::InitRun(), TPCFEETestRecov1::InitRun(), TpcPrototypeUnpacker::InitRun(), JetHepMCLoader::InitRun(), analysis::InitRun(), jetrtrack::InitRun(), makeHisto(), PHG4ScoringManager::makeScoringHistograms(), registerHisto(), and Fun4AllServer::registerHisto().
bool Fun4AllHistoManager::registerHisto (TNamed * h1d, const int replace = 0)
Register histogram or TTree object For histograms, enforce error calculation and propagation
Definition at line 142 of file Fun4AllHistoManager.cc.
View newest version in sPHENIX GitHub at line 142 of file Fun4AllHistoManager.cc
References h1d, and registerHisto().
void Fun4AllHistoManager::Reset ()
Definition at line 285 of file Fun4AllHistoManager.cc.
View newest version in sPHENIX GitHub at line 285 of file Fun4AllHistoManager.cc
References h, and Histo.
void Fun4AllHistoManager::setOutfileName (const std::string & filename) inline
Definition at line 46 of file Fun4AllHistoManager.h.
View newest version in sPHENIX GitHub at line 46 of file Fun4AllHistoManager.h
References filename, and outfilename.
Referenced by Fun4AllServer::dumpHistos(), and PHAJMaker::Init().
Member Data Documentation
std::map<const std::string, TNamed *> Fun4AllHistoManager::Histo private
Definition at line 50 of file Fun4AllHistoManager.h.
View newest version in sPHENIX GitHub at line 50 of file Fun4AllHistoManager.h
Referenced by dumpHistos(), getHisto(), getHistoName(), isHistoRegistered(), nHistos(), Print(), registerHisto(), Reset(), and ~Fun4AllHistoManager().
std::string Fun4AllHistoManager::outfilename private
Definition at line 49 of file Fun4AllHistoManager.h.
View newest version in sPHENIX GitHub at line 49 of file Fun4AllHistoManager.h
Referenced by dumpHistos(), and setOutfileName().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/framework/fun4all/Fun4AllHistoManager.h
coresoftware/blob/master/offline/framework/fun4all/Fun4AllHistoManager.cc