Analysis Software: ActsSourceLink Exception Reference
ActsSourceLink Exception Reference final
#include <coresoftware/blob/master/offline/packages/trackbase/ActsSourceLink.h>
Classes
struct SurfaceAccessor
Public Types
using Index = uint8_t
Public Member Functions
constexpr ActsSourceLink (Acts::GeometryIdentifier gid, Index idx)
Construct from geometry identifier and index.
constexpr ActsSourceLink (Acts::GeometryIdentifier gid, Index idx, TrkrDefs::cluskey cluskey)
ActsSourceLink ()
satisfy SourceLinkConcept.
m_index (UINT8_MAX)
m_cluskey (UINT64_MAX)
ActsSourceLink (const ActsSourceLink &)=default
ActsSourceLink (ActsSourceLink &&)=default
ActsSourceLink & operator= (const ActsSourceLink &)=default
ActsSourceLink & operator= (ActsSourceLink &&)=default
constexpr Index index () const
Access the index.
constexpr TrkrDefs::cluskey cluskey () const
constexpr Acts::GeometryIdentifier geometryId () const
Private Attributes
Acts::GeometryIdentifier m_geometryId
Index m_index
TrkrDefs::cluskey m_cluskey
Friends
constexpr bool operator== (const ActsSourceLink &lhs, const ActsSourceLink &rhs)
constexpr bool operator!= (const ActsSourceLink &lhs, const ActsSourceLink &rhs)
Detailed Description
A source link that stores just an index. Using an index instead of e.g. a pointer, means source link and measurement are decoupled and the measurement represenation can be easily changed without having to also change the source link.
Definition at line 17 of file ActsSourceLink.h.
View newest version in sPHENIX GitHub at line 17 of file ActsSourceLink.h
Member Typedef Documentation
using ActsSourceLink::Index = uint8_t
Definition at line 20 of file ActsSourceLink.h.
View newest version in sPHENIX GitHub at line 20 of file ActsSourceLink.h
Constructor & Destructor Documentation
constexpr ActsSourceLink::ActsSourceLink (Acts::GeometryIdentifier gid, Index idx) inline
Construct from geometry identifier and index.
Definition at line 23 of file ActsSourceLink.h.
View newest version in sPHENIX GitHub at line 23 of file ActsSourceLink.h
constexpr ActsSourceLink::ActsSourceLink (Acts::GeometryIdentifier gid, Index idx, TrkrDefs::cluskey cluskey) inline
Definition at line 29 of file ActsSourceLink.h.
View newest version in sPHENIX GitHub at line 29 of file ActsSourceLink.h
ActsSourceLink::ActsSourceLink () inline
satisfy SourceLinkConcept.
Definition at line 38 of file ActsSourceLink.h.
View newest version in sPHENIX GitHub at line 38 of file ActsSourceLink.h
ActsSourceLink::ActsSourceLink (const ActsSourceLink &) default
ActsSourceLink::ActsSourceLink (ActsSourceLink &&) default
Member Function Documentation
constexpr TrkrDefs::cluskey ActsSourceLink::cluskey () const inline
Definition at line 52 of file ActsSourceLink.h.
View newest version in sPHENIX GitHub at line 52 of file ActsSourceLink.h
References m_cluskey.
Referenced by Calibrator::calibrate().
constexpr Acts::GeometryIdentifier ActsSourceLink::geometryId () const inline
Definition at line 53 of file ActsSourceLink.h.
View newest version in sPHENIX GitHub at line 53 of file ActsSourceLink.h
References m_geometryId.
Referenced by PHActsTrkFitter::getSurfaceVector().
constexpr Index ActsSourceLink::index () const inline
Access the index.
Definition at line 51 of file ActsSourceLink.h.
View newest version in sPHENIX GitHub at line 51 of file ActsSourceLink.h
References m_index.
Referenced by Calibrator::calibrate().
ActsSourceLink::m_cluskey (UINT64_MAX) inline
Definition at line 41 of file ActsSourceLink.h.
View newest version in sPHENIX GitHub at line 41 of file ActsSourceLink.h
ActsSourceLink::m_index (UINT8_MAX)
ActsSourceLink& ActsSourceLink::operator= (const ActsSourceLink &) default
ActsSourceLink& ActsSourceLink::operator= (ActsSourceLink &&) default
Friends And Related Function Documentation
constexpr bool operator!= (const ActsSourceLink & lhs, const ActsSourceLink & rhs) friend
Definition at line 77 of file ActsSourceLink.h.
View newest version in sPHENIX GitHub at line 77 of file ActsSourceLink.h
constexpr bool operator== (const ActsSourceLink & lhs, const ActsSourceLink & rhs) friend
Definition at line 70 of file ActsSourceLink.h.
View newest version in sPHENIX GitHub at line 70 of file ActsSourceLink.h
Member Data Documentation
TrkrDefs::cluskey ActsSourceLink::m_cluskey private
Definition at line 68 of file ActsSourceLink.h.
View newest version in sPHENIX GitHub at line 68 of file ActsSourceLink.h
Referenced by cluskey().
Acts::GeometryIdentifier ActsSourceLink::m_geometryId private
Definition at line 66 of file ActsSourceLink.h.
View newest version in sPHENIX GitHub at line 66 of file ActsSourceLink.h
Referenced by geometryId().
Index ActsSourceLink::m_index private
Definition at line 67 of file ActsSourceLink.h.
View newest version in sPHENIX GitHub at line 67 of file ActsSourceLink.h
Referenced by index().
The documentation for this exception was generated from the following file:
coresoftware/blob/master/offline/packages/trackbase/ActsSourceLink.h