Analysis Software: ActsExamples::RootTrajectorySummaryReader Class Reference
ActsExamples::RootTrajectorySummaryReader Class Reference
Reads in TrackParameter information from a root file and fills it into a Acts::BoundTrackParameter format.
#include <acts/blob/sPHENIX/Examples/Io/Root/include/ActsExamples/Io/Root/RootTrajectorySummaryReader.hpp>
Classes
struct Config
The nested configuration struct.
Public Member Functions
RootTrajectorySummaryReader (const Config &config, Acts::Logging::Level level)
~RootTrajectorySummaryReader () override
Destructor.
std::string name () const override
Framework name() method.
std::pair< size_t, size_t > availableEvents () const override
Return the available events range.
ProcessCode read (const ActsExamples::AlgorithmContext &context) override
const Config & config () const
Readonly access to the config.
Public Member Functions inherited from ActsExamples::IReader
ProcessCode internalExecute (const AlgorithmContext &context) final
ProcessCode initialize () override
Fulfill the algorithm interface.
ProcessCode finalize () override
Fulfill the algorithm interface.
Public Member Functions inherited from ActsExamples::SequenceElement
virtual ~SequenceElement ()=default
const std::vector< const
DataHandleBase * > & writeHandles () const
const std::vector< const
DataHandleBase * > & readHandles () const
Private Member Functions
const Acts::Logger & logger () const
Private access to the logging instance.
Private Attributes
std::unique_ptr< const
Acts::Logger > m_logger
The logger.
Config m_cfg
The config class.
WriteDataHandle< std::vector
< Acts::BoundTrackParameters > > m_outputTrackParameters {this, "OutputTrackParameters"}
WriteDataHandle
< SimParticleContainer > m_outputParticles
std::mutex m_read_mutex
mutex used to protect multi-threaded reads
size_t m_events = 0
The number of events.
TChain * m_inputChain = nullptr
The input tree name.
uint32_t m_eventNr {0}
the event number
std::vector< uint32_t > * m_multiTrajNr
the multi-trajectory number
std::vector< unsigned int > * m_subTrajNr
std::vector< long long > m_entryNumbers = {}
std::vector< unsigned int > * m_nStates
The number of states.
std::vector< unsigned int > * m_nMeasurements
The number of measurements.
std::vector< unsigned int > * m_nOutliers
The number of outliers.
std::vector< unsigned int > * m_nHoles
The number of holes.
std::vector< float > * m_chi2Sum = new std::vector<float>
The total chi2.
std::vector< unsigned int > * m_NDF
std::vector< std::vector
< double > > * m_measurementChi2
std::vector< std::vector
< double > > * m_outlierChi2
The chi2 on all outlier states.
std::vector< std::vector
< double > > * m_measurementVolume
std::vector< std::vector
< double > > * m_measurementLayer
std::vector< std::vector
< double > > * m_outlierVolume
The volume id of the outliers.
std::vector< std::vector
< double > > * m_outlierLayer
The layer id of the outliers.
std::vector< unsigned int > * m_nMajorityHits
std::vector< uint64_t > * m_majorityParticleId
The particle Id of the majority particle.
std::vector< int > * m_t_charge
Charge of majority particle.
std::vector< float > * m_t_time
Time of majority particle.
std::vector< float > * m_t_vx
Vertex x positions of majority particle.
std::vector< float > * m_t_vy
Vertex y positions of majority particle.
std::vector< float > * m_t_vz
Vertex z positions of majority particle.
std::vector< float > * m_t_px
Initial momenta px of majority particle.
std::vector< float > * m_t_py
Initial momenta py of majority particle.
std::vector< float > * m_t_pz
Initial momenta pz of majority particle.
std::vector< float > * m_t_theta
Initial momenta theta of majority particle.
std::vector< float > * m_t_phi
Initial momenta phi of majority particle.
std::vector< float > * m_t_pT
Initial momenta pT of majority particle.
std::vector< float > * m_t_eta
Initial momenta eta of majority particle.
std::vector< bool > * m_hasFittedParams
If the track has fitted parameter.
std::vector< float > * m_eLOC0_fit
Fitted parameters eBoundLoc0 of track.
std::vector< float > * m_eLOC1_fit
Fitted parameters eBoundLoc1 of track.
std::vector< float > * m_ePHI_fit
Fitted parameters ePHI of track.
std::vector< float > * m_eTHETA_fit
Fitted parameters eTHETA of track.
std::vector< float > * m_eQOP_fit
Fitted parameters eQOP of track.
std::vector< float > * m_eT_fit
Fitted parameters eT of track.
std::vector< float > * m_err_eLOC0_fit
Fitted parameters eLOC err of track.
std::vector< float > * m_err_eLOC1_fit
Fitted parameters eBoundLoc1 err of track.
std::vector< float > * m_err_ePHI_fit
Fitted parameters ePHI err of track.
std::vector< float > * m_err_eTHETA_fit
Fitted parameters eTHETA err of track.
std::vector< float > * m_err_eQOP_fit
Fitted parameters eQOP err of track.
std::vector< float > * m_err_eT_fit
Fitted parameters eT err of track.
Detailed Description
Reads in TrackParameter information from a root file and fills it into a Acts::BoundTrackParameter format.
Definition at line 37 of file RootTrajectorySummaryReader.hpp.
View newest version in sPHENIX GitHub at line 37 of file RootTrajectorySummaryReader.hpp
Constructor & Destructor Documentation
ActsExamples::RootTrajectorySummaryReader::RootTrajectorySummaryReader (const Config & config, Acts::Logging::Level level)
Constructor
Parameters
config The Configuration struct
level The log level
Definition at line 27 of file RootTrajectorySummaryReader.cpp.
View newest version in sPHENIX GitHub at line 27 of file RootTrajectorySummaryReader.cpp
References Acts::getDefaultLogger(), and name().
ActsExamples::RootTrajectorySummaryReader::~RootTrajectorySummaryReader () override
Destructor.
Definition at line 114 of file RootTrajectorySummaryReader.cpp.
View newest version in sPHENIX GitHub at line 114 of file RootTrajectorySummaryReader.cpp
References Acts::detail_vtc::m_nHoles, Acts::detail_vtc::m_nMeasurements, and Acts::detail_vtc::m_nOutliers.
Member Function Documentation
std::pair< size_t, size_t > ActsExamples::RootTrajectorySummaryReader::availableEvents () const override virtual
Return the available events range.
Implements ActsExamples::IReader.
Definition at line 110 of file RootTrajectorySummaryReader.cpp.
View newest version in sPHENIX GitHub at line 110 of file RootTrajectorySummaryReader.cpp
References physmon_ckf_tracking::u.
const Config& ActsExamples::RootTrajectorySummaryReader::config () const inline
Readonly access to the config.
Definition at line 71 of file RootTrajectorySummaryReader.hpp.
View newest version in sPHENIX GitHub at line 71 of file RootTrajectorySummaryReader.hpp
References m_cfg.
const Acts::Logger& ActsExamples::RootTrajectorySummaryReader::logger () const inline private
Private access to the logging instance.
Definition at line 78 of file RootTrajectorySummaryReader.hpp.
View newest version in sPHENIX GitHub at line 78 of file RootTrajectorySummaryReader.hpp
References m_logger.
std::string ActsExamples::RootTrajectorySummaryReader::name () const inline override virtual
Framework name() method.
Implements ActsExamples::SequenceElement.
Definition at line 60 of file RootTrajectorySummaryReader.hpp.
View newest version in sPHENIX GitHub at line 60 of file RootTrajectorySummaryReader.hpp
Referenced by RootTrajectorySummaryReader().
ActsExamples::ProcessCode ActsExamples::RootTrajectorySummaryReader::read (const ActsExamples::AlgorithmContext & context) override virtual
Read out data from the input stream
Parameters
context The algorithm context
Implements ActsExamples::IReader.
Definition at line 158 of file RootTrajectorySummaryReader.cpp.
View newest version in sPHENIX GitHub at line 158 of file RootTrajectorySummaryReader.cpp
References ACTS_DEBUG, ACTS_INFO, ACTS_WARNING, entry, ActsExamples::AlgorithmContext::eventNumber, i, m_cfg(), testing::internal::move(), Acts::ParticleHypothesis::pion(), ActsFatras::Particle::setDirection(), ActsFatras::Particle::setParticleId(), ActsFatras::Particle::setPosition4(), and SUCCESS.
Member Data Documentation
Config ActsExamples::RootTrajectorySummaryReader::m_cfg private
The config class.
Definition at line 81 of file RootTrajectorySummaryReader.hpp.
View newest version in sPHENIX GitHub at line 81 of file RootTrajectorySummaryReader.hpp
Referenced by config().
std::vector<float>* ActsExamples::RootTrajectorySummaryReader::m_chi2Sum = new std::vector<float> private
The total chi2.
Definition at line 117 of file RootTrajectorySummaryReader.hpp.
View newest version in sPHENIX GitHub at line 117 of file RootTrajectorySummaryReader.hpp
std::vector<float>* ActsExamples::RootTrajectorySummaryReader::m_eLOC0_fit private
Initial value:
=
      new std::vector<float>
Fitted parameters eBoundLoc0 of track.
Definition at line 170 of file RootTrajectorySummaryReader.hpp.
View newest version in sPHENIX GitHub at line 170 of file RootTrajectorySummaryReader.hpp
std::vector<float>* ActsExamples::RootTrajectorySummaryReader::m_eLOC1_fit private
Initial value:
=
      new std::vector<float>
Fitted parameters eBoundLoc1 of track.
Definition at line 172 of file RootTrajectorySummaryReader.hpp.
View newest version in sPHENIX GitHub at line 172 of file RootTrajectorySummaryReader.hpp
std::vector<long long> ActsExamples::RootTrajectorySummaryReader::m_entryNumbers = {} private
The entry numbers for accessing events in increased order (there could be multiple entries corresponding to one event number)
Definition at line 107 of file RootTrajectorySummaryReader.hpp.
View newest version in sPHENIX GitHub at line 107 of file RootTrajectorySummaryReader.hpp
std::vector<float>* ActsExamples::RootTrajectorySummaryReader::m_ePHI_fit private
Initial value:
=
      new std::vector<float>
Fitted parameters ePHI of track.
Definition at line 174 of file RootTrajectorySummaryReader.hpp.
View newest version in sPHENIX GitHub at line 174 of file RootTrajectorySummaryReader.hpp
std::vector<float>* ActsExamples::RootTrajectorySummaryReader::m_eQOP_fit private
Initial value:
=
      new std::vector<float>
Fitted parameters eQOP of track.
Definition at line 178 of file RootTrajectorySummaryReader.hpp.
View newest version in sPHENIX GitHub at line 178 of file RootTrajectorySummaryReader.hpp
std::vector<float>* ActsExamples::RootTrajectorySummaryReader::m_err_eLOC0_fit private
Initial value:
=
      new std::vector<float>
Fitted parameters eLOC err of track.
Definition at line 182 of file RootTrajectorySummaryReader.hpp.
View newest version in sPHENIX GitHub at line 182 of file RootTrajectorySummaryReader.hpp
std::vector<float>* ActsExamples::RootTrajectorySummaryReader::m_err_eLOC1_fit private
Initial value:
=
      new std::vector<float>
Fitted parameters eBoundLoc1 err of track.
Definition at line 184 of file RootTrajectorySummaryReader.hpp.
View newest version in sPHENIX GitHub at line 184 of file RootTrajectorySummaryReader.hpp
std::vector<float>* ActsExamples::RootTrajectorySummaryReader::m_err_ePHI_fit private
Initial value:
=
      new std::vector<float>
Fitted parameters ePHI err of track.
Definition at line 186 of file RootTrajectorySummaryReader.hpp.
View newest version in sPHENIX GitHub at line 186 of file RootTrajectorySummaryReader.hpp
std::vector<float>* ActsExamples::RootTrajectorySummaryReader::m_err_eQOP_fit private
Initial value:
=
      new std::vector<float>
Fitted parameters eQOP err of track.
Definition at line 190 of file RootTrajectorySummaryReader.hpp.
View newest version in sPHENIX GitHub at line 190 of file RootTrajectorySummaryReader.hpp
std::vector<float>* ActsExamples::RootTrajectorySummaryReader::m_err_eT_fit private
Initial value:
=
      new std::vector<float>
Fitted parameters eT err of track.
Definition at line 192 of file RootTrajectorySummaryReader.hpp.
View newest version in sPHENIX GitHub at line 192 of file RootTrajectorySummaryReader.hpp
std::vector<float>* ActsExamples::RootTrajectorySummaryReader::m_err_eTHETA_fit private
Initial value:
=
      new std::vector<float>
Fitted parameters eTHETA err of track.
Definition at line 188 of file RootTrajectorySummaryReader.hpp.
View newest version in sPHENIX GitHub at line 188 of file RootTrajectorySummaryReader.hpp
std::vector<float>* ActsExamples::RootTrajectorySummaryReader::m_eT_fit private
Initial value:
=
      new std::vector<float>
Fitted parameters eT of track.
Definition at line 180 of file RootTrajectorySummaryReader.hpp.
View newest version in sPHENIX GitHub at line 180 of file RootTrajectorySummaryReader.hpp
std::vector<float>* ActsExamples::RootTrajectorySummaryReader::m_eTHETA_fit private
Initial value:
=
      new std::vector<float>
Fitted parameters eTHETA of track.
Definition at line 176 of file RootTrajectorySummaryReader.hpp.
View newest version in sPHENIX GitHub at line 176 of file RootTrajectorySummaryReader.hpp
uint32_t ActsExamples::RootTrajectorySummaryReader::m_eventNr {0} private
the event number
Definition at line 98 of file RootTrajectorySummaryReader.hpp.
View newest version in sPHENIX GitHub at line 98 of file RootTrajectorySummaryReader.hpp
size_t ActsExamples::RootTrajectorySummaryReader::m_events = 0 private
The number of events.
Definition at line 93 of file RootTrajectorySummaryReader.hpp.
View newest version in sPHENIX GitHub at line 93 of file RootTrajectorySummaryReader.hpp
std::vector<bool>* ActsExamples::RootTrajectorySummaryReader::m_hasFittedParams private
Initial value:
=
      new std::vector<bool>
If the track has fitted parameter.
Definition at line 168 of file RootTrajectorySummaryReader.hpp.
View newest version in sPHENIX GitHub at line 168 of file RootTrajectorySummaryReader.hpp
TChain* ActsExamples::RootTrajectorySummaryReader::m_inputChain = nullptr private
The input tree name.
Definition at line 96 of file RootTrajectorySummaryReader.hpp.
View newest version in sPHENIX GitHub at line 96 of file RootTrajectorySummaryReader.hpp
std::unique_ptr<const Acts::Logger> ActsExamples::RootTrajectorySummaryReader::m_logger private
The logger.
Definition at line 75 of file RootTrajectorySummaryReader.hpp.
View newest version in sPHENIX GitHub at line 75 of file RootTrajectorySummaryReader.hpp
Referenced by logger().
std::vector<uint64_t>* ActsExamples::RootTrajectorySummaryReader::m_majorityParticleId private
Initial value:
=
      new std::vector<uint64_t>
The particle Id of the majority particle.
Definition at line 141 of file RootTrajectorySummaryReader.hpp.
View newest version in sPHENIX GitHub at line 141 of file RootTrajectorySummaryReader.hpp
std::vector<std::vector<double> >* ActsExamples::RootTrajectorySummaryReader::m_measurementChi2 private
Initial value:
=
      new std::vector<std::vector<double>>
The chi2 on all measurement states
Definition at line 121 of file RootTrajectorySummaryReader.hpp.
View newest version in sPHENIX GitHub at line 121 of file RootTrajectorySummaryReader.hpp
std::vector<std::vector<double> >* ActsExamples::RootTrajectorySummaryReader::m_measurementLayer private
Initial value:
=
      new std::vector<std::vector<double>>
The layer id of the measurements
Definition at line 129 of file RootTrajectorySummaryReader.hpp.
View newest version in sPHENIX GitHub at line 129 of file RootTrajectorySummaryReader.hpp
std::vector<std::vector<double> >* ActsExamples::RootTrajectorySummaryReader::m_measurementVolume private
Initial value:
=
      new std::vector<std::vector<double>>
The volume id of the measurements
Definition at line 126 of file RootTrajectorySummaryReader.hpp.
View newest version in sPHENIX GitHub at line 126 of file RootTrajectorySummaryReader.hpp
std::vector<uint32_t>* ActsExamples::RootTrajectorySummaryReader::m_multiTrajNr private
Initial value:
=
      new std::vector<uint32_t>
the multi-trajectory number
Definition at line 99 of file RootTrajectorySummaryReader.hpp.
View newest version in sPHENIX GitHub at line 99 of file RootTrajectorySummaryReader.hpp
std::vector<unsigned int>* ActsExamples::RootTrajectorySummaryReader::m_NDF private
Initial value:
=
      new std::vector<unsigned int>
The number of ndf of the measurements+outliers
Definition at line 118 of file RootTrajectorySummaryReader.hpp.
View newest version in sPHENIX GitHub at line 118 of file RootTrajectorySummaryReader.hpp
std::vector<unsigned int>* ActsExamples::RootTrajectorySummaryReader::m_nHoles private
Initial value:
=
      new std::vector<unsigned int>
The number of holes.
Definition at line 115 of file RootTrajectorySummaryReader.hpp.
View newest version in sPHENIX GitHub at line 115 of file RootTrajectorySummaryReader.hpp
std::vector<unsigned int>* ActsExamples::RootTrajectorySummaryReader::m_nMajorityHits private
Initial value:
=
      new std::vector<unsigned int>
The number of hits from majority particle
Definition at line 138 of file RootTrajectorySummaryReader.hpp.
View newest version in sPHENIX GitHub at line 138 of file RootTrajectorySummaryReader.hpp
std::vector<unsigned int>* ActsExamples::RootTrajectorySummaryReader::m_nMeasurements private
Initial value:
=
      new std::vector<unsigned int>
The number of measurements.
Definition at line 111 of file RootTrajectorySummaryReader.hpp.
View newest version in sPHENIX GitHub at line 111 of file RootTrajectorySummaryReader.hpp
std::vector<unsigned int>* ActsExamples::RootTrajectorySummaryReader::m_nOutliers private
Initial value:
=
      new std::vector<unsigned int>
The number of outliers.
Definition at line 113 of file RootTrajectorySummaryReader.hpp.
View newest version in sPHENIX GitHub at line 113 of file RootTrajectorySummaryReader.hpp
std::vector<unsigned int>* ActsExamples::RootTrajectorySummaryReader::m_nStates private
Initial value:
=
      new std::vector<unsigned int>
The number of states.
Definition at line 109 of file RootTrajectorySummaryReader.hpp.
View newest version in sPHENIX GitHub at line 109 of file RootTrajectorySummaryReader.hpp
std::vector<std::vector<double> >* ActsExamples::RootTrajectorySummaryReader::m_outlierChi2 private
Initial value:
=
      new std::vector<std::vector<double>>
The chi2 on all outlier states.
Definition at line 124 of file RootTrajectorySummaryReader.hpp.
View newest version in sPHENIX GitHub at line 124 of file RootTrajectorySummaryReader.hpp
std::vector<std::vector<double> >* ActsExamples::RootTrajectorySummaryReader::m_outlierLayer private
Initial value:
=
      new std::vector<std::vector<double>>
The layer id of the outliers.
Definition at line 134 of file RootTrajectorySummaryReader.hpp.
View newest version in sPHENIX GitHub at line 134 of file RootTrajectorySummaryReader.hpp
std::vector<std::vector<double> >* ActsExamples::RootTrajectorySummaryReader::m_outlierVolume private
Initial value:
=
      new std::vector<std::vector<double>>
The volume id of the outliers.
Definition at line 132 of file RootTrajectorySummaryReader.hpp.
View newest version in sPHENIX GitHub at line 132 of file RootTrajectorySummaryReader.hpp
WriteDataHandle<SimParticleContainer> ActsExamples::RootTrajectorySummaryReader::m_outputParticles private
Initial value:
{this,
                                                          "OutputParticles"}
Definition at line 86 of file RootTrajectorySummaryReader.hpp.
View newest version in sPHENIX GitHub at line 86 of file RootTrajectorySummaryReader.hpp
WriteDataHandle<std::vector<Acts::BoundTrackParameters> > ActsExamples::RootTrajectorySummaryReader::m_outputTrackParameters {this, "OutputTrackParameters"} private
Definition at line 84 of file RootTrajectorySummaryReader.hpp.
View newest version in sPHENIX GitHub at line 84 of file RootTrajectorySummaryReader.hpp
std::mutex ActsExamples::RootTrajectorySummaryReader::m_read_mutex private
mutex used to protect multi-threaded reads
Definition at line 90 of file RootTrajectorySummaryReader.hpp.
View newest version in sPHENIX GitHub at line 90 of file RootTrajectorySummaryReader.hpp
std::vector<unsigned int>* ActsExamples::RootTrajectorySummaryReader::m_subTrajNr private
Initial value:
=
      new std::vector<unsigned int>
the multi-trajectory sub-trajectory number
Definition at line 101 of file RootTrajectorySummaryReader.hpp.
View newest version in sPHENIX GitHub at line 101 of file RootTrajectorySummaryReader.hpp
std::vector<int>* ActsExamples::RootTrajectorySummaryReader::m_t_charge private
Initial value:
=
      new std::vector<int>
Charge of majority particle.
Definition at line 143 of file RootTrajectorySummaryReader.hpp.
View newest version in sPHENIX GitHub at line 143 of file RootTrajectorySummaryReader.hpp
std::vector<float>* ActsExamples::RootTrajectorySummaryReader::m_t_eta private
Initial value:
=
      new std::vector<float>
Initial momenta eta of majority particle.
Definition at line 165 of file RootTrajectorySummaryReader.hpp.
View newest version in sPHENIX GitHub at line 165 of file RootTrajectorySummaryReader.hpp
std::vector<float>* ActsExamples::RootTrajectorySummaryReader::m_t_phi private
Initial value:
=
      new std::vector<float>
Initial momenta phi of majority particle.
Definition at line 161 of file RootTrajectorySummaryReader.hpp.
View newest version in sPHENIX GitHub at line 161 of file RootTrajectorySummaryReader.hpp
std::vector<float>* ActsExamples::RootTrajectorySummaryReader::m_t_pT private
Initial value:
=
      new std::vector<float>
Initial momenta pT of majority particle.
Definition at line 163 of file RootTrajectorySummaryReader.hpp.
View newest version in sPHENIX GitHub at line 163 of file RootTrajectorySummaryReader.hpp
std::vector<float>* ActsExamples::RootTrajectorySummaryReader::m_t_px private
Initial value:
=
      new std::vector<float>
Initial momenta px of majority particle.
Definition at line 153 of file RootTrajectorySummaryReader.hpp.
View newest version in sPHENIX GitHub at line 153 of file RootTrajectorySummaryReader.hpp
std::vector<float>* ActsExamples::RootTrajectorySummaryReader::m_t_py private
Initial value:
=
      new std::vector<float>
Initial momenta py of majority particle.
Definition at line 155 of file RootTrajectorySummaryReader.hpp.
View newest version in sPHENIX GitHub at line 155 of file RootTrajectorySummaryReader.hpp
std::vector<float>* ActsExamples::RootTrajectorySummaryReader::m_t_pz private
Initial value:
=
      new std::vector<float>
Initial momenta pz of majority particle.
Definition at line 157 of file RootTrajectorySummaryReader.hpp.
View newest version in sPHENIX GitHub at line 157 of file RootTrajectorySummaryReader.hpp
std::vector<float>* ActsExamples::RootTrajectorySummaryReader::m_t_theta private
Initial value:
=
      new std::vector<float>
Initial momenta theta of majority particle.
Definition at line 159 of file RootTrajectorySummaryReader.hpp.
View newest version in sPHENIX GitHub at line 159 of file RootTrajectorySummaryReader.hpp
std::vector<float>* ActsExamples::RootTrajectorySummaryReader::m_t_time private
Initial value:
=
      new std::vector<float>
Time of majority particle.
Definition at line 145 of file RootTrajectorySummaryReader.hpp.
View newest version in sPHENIX GitHub at line 145 of file RootTrajectorySummaryReader.hpp
std::vector<float>* ActsExamples::RootTrajectorySummaryReader::m_t_vx private
Initial value:
=
      new std::vector<float>
Vertex x positions of majority particle.
Definition at line 147 of file RootTrajectorySummaryReader.hpp.
View newest version in sPHENIX GitHub at line 147 of file RootTrajectorySummaryReader.hpp
std::vector<float>* ActsExamples::RootTrajectorySummaryReader::m_t_vy private
Initial value:
=
      new std::vector<float>
Vertex y positions of majority particle.
Definition at line 149 of file RootTrajectorySummaryReader.hpp.
View newest version in sPHENIX GitHub at line 149 of file RootTrajectorySummaryReader.hpp
std::vector<float>* ActsExamples::RootTrajectorySummaryReader::m_t_vz private
Initial value:
=
      new std::vector<float>
Vertex z positions of majority particle.
Definition at line 151 of file RootTrajectorySummaryReader.hpp.
View newest version in sPHENIX GitHub at line 151 of file RootTrajectorySummaryReader.hpp
The documentation for this class was generated from the following files:
acts/blob/sPHENIX/Examples/Io/Root/include/ActsExamples/Io/Root/RootTrajectorySummaryReader.hpp
acts/blob/sPHENIX/Examples/Io/Root/src/RootTrajectorySummaryReader.cpp