Analysis Software: Tracklet Class Reference
Tracklet Class Reference
#include <analysis/blob/master/dNdEta_Run2023/analysis_INTT/src/Tracklet.h>
Public Member Functions
Tracklet ()
Tracklet (Hit *hit1, Hit *hit2)
~Tracklet ()
void SetHits (Hit *hit1, Hit *hit2)
Hit * Hit1 ()
Hit * Hit2 ()
float dEta ()
float dPhi ()
float dR ()
float Eta ()
float Phi ()
float tklVtxZ ()
int LayerComb ()
void SetMatchedGenHardon ()
bool IsMatchedGenHadron ()
void SetGenHadron (GenHadron *genhad)
GenHadron * MatchedGenHadron ()
Private Attributes
Hit * _hit1
Hit * _hit2
float _deta
float _dphi
bool _matched_genhadron
GenHadron * _genhad
Detailed Description
Definition at line 12 of file Tracklet.h.
View newest version in sPHENIX GitHub at line 12 of file Tracklet.h
Constructor & Destructor Documentation
Tracklet::Tracklet ()
Definition at line 43 of file Tracklet.h.
View newest version in sPHENIX GitHub at line 43 of file Tracklet.h
Tracklet::Tracklet (Hit * hit1, Hit * hit2)
Definition at line 51 of file Tracklet.h.
View newest version in sPHENIX GitHub at line 51 of file Tracklet.h
References _dphi, deltaPhi(), and Hit::Eta().
Tracklet::~Tracklet ()
Definition at line 61 of file Tracklet.h.
View newest version in sPHENIX GitHub at line 61 of file Tracklet.h
Member Function Documentation
float Tracklet::dEta ()
Definition at line 77 of file Tracklet.h.
View newest version in sPHENIX GitHub at line 77 of file Tracklet.h
Referenced by ProtoTracklets().
float Tracklet::dPhi ()
Definition at line 79 of file Tracklet.h.
View newest version in sPHENIX GitHub at line 79 of file Tracklet.h
References _dphi.
Referenced by ProtoTracklets().
float Tracklet::dR ()
Definition at line 81 of file Tracklet.h.
View newest version in sPHENIX GitHub at line 81 of file Tracklet.h
References _dphi.
Referenced by compare_dR(), and ProtoTracklets().
float Tracklet::Eta ()
Definition at line 83 of file Tracklet.h.
View newest version in sPHENIX GitHub at line 83 of file Tracklet.h
Hit * Tracklet::Hit1 ()
Definition at line 73 of file Tracklet.h.
View newest version in sPHENIX GitHub at line 73 of file Tracklet.h
Referenced by ProtoTracklets().
Hit * Tracklet::Hit2 ()
Definition at line 75 of file Tracklet.h.
View newest version in sPHENIX GitHub at line 75 of file Tracklet.h
bool Tracklet::IsMatchedGenHadron ()
Definition at line 93 of file Tracklet.h.
View newest version in sPHENIX GitHub at line 93 of file Tracklet.h
int Tracklet::LayerComb ()
Definition at line 89 of file Tracklet.h.
View newest version in sPHENIX GitHub at line 89 of file Tracklet.h
GenHadron * Tracklet::MatchedGenHadron ()
Definition at line 101 of file Tracklet.h.
View newest version in sPHENIX GitHub at line 101 of file Tracklet.h
float Tracklet::Phi ()
Definition at line 85 of file Tracklet.h.
View newest version in sPHENIX GitHub at line 85 of file Tracklet.h
void Tracklet::SetGenHadron (GenHadron * genhad)
Definition at line 95 of file Tracklet.h.
View newest version in sPHENIX GitHub at line 95 of file Tracklet.h
void Tracklet::SetHits (Hit * hit1, Hit * hit2)
Definition at line 63 of file Tracklet.h.
View newest version in sPHENIX GitHub at line 63 of file Tracklet.h
References _dphi, deltaPhi(), and Hit::Eta().
void Tracklet::SetMatchedGenHardon ()
Definition at line 91 of file Tracklet.h.
View newest version in sPHENIX GitHub at line 91 of file Tracklet.h
float Tracklet::tklVtxZ ()
Definition at line 87 of file Tracklet.h.
View newest version in sPHENIX GitHub at line 87 of file Tracklet.h
Member Data Documentation
float Tracklet::_deta private
Definition at line 37 of file Tracklet.h.
View newest version in sPHENIX GitHub at line 37 of file Tracklet.h
float Tracklet::_dphi private
Definition at line 38 of file Tracklet.h.
View newest version in sPHENIX GitHub at line 38 of file Tracklet.h
GenHadron* Tracklet::_genhad private
Definition at line 40 of file Tracklet.h.
View newest version in sPHENIX GitHub at line 40 of file Tracklet.h
Hit* Tracklet::_hit1 private
Definition at line 35 of file Tracklet.h.
View newest version in sPHENIX GitHub at line 35 of file Tracklet.h
Hit* Tracklet::_hit2 private
Definition at line 36 of file Tracklet.h.
View newest version in sPHENIX GitHub at line 36 of file Tracklet.h
bool Tracklet::_matched_genhadron private
Definition at line 39 of file Tracklet.h.
View newest version in sPHENIX GitHub at line 39 of file Tracklet.h
The documentation for this class was generated from the following file:
analysis/blob/master/dNdEta_Run2023/analysis_INTT/src/Tracklet.h