Analysis Software: Acts::Python Namespace Reference
Acts::Python Namespace Reference
Classes
struct Context
class PythonLogger
Functions
template<typename T , typename Ur , typename Ut >
void pythonRangeProperty (T &obj, const std::string &name, Ur Ut::*begin, Ur Ut::*end)
void patchClassesWithConfig (pybind11::module_ &m)
template<typename T >
void patchKwargsConstructor (T &c)
METHOD_TRAIT (write_method_trait_t, write)
void addAmbiguityResolution (Context &ctx)
void addUnits (Context &ctx)
void addLogging (Acts::Python::Context &ctx)
void addPdgParticle (Acts::Python::Context &ctx)
void addAlgebra (Acts::Python::Context &ctx)
void addBinning (Context &ctx)
void addDetector (Context &ctx)
void addDetectorInspectors (Context &)
void addDigitization (Context &ctx)
void addEDM4hep (Context &ctx)
void addEventData (Context &ctx)
void addExampleAlgorithms (Context &ctx)
void addExaTrkXTrackFinding (Context &ctx)
void addFramework (Context &ctx)
void addGeant4HepMC3 (Context &ctx)
void addGenerators (Context &ctx)
void addGeometry (Context &ctx)
void addExperimentalGeometry (Context &ctx)
void addHepMC3 (Context &ctx)
void addInput (Context &ctx)
void addJson (Context &ctx)
void addMagneticField (Context &ctx)
void addMaterial (Context &ctx)
void addPropagation (Context &ctx)
void addOutput (Context &ctx)
void addTruthTracking (Context &ctx)
void addTrackFitting (Context &ctx)
void addTrackFinding (Context &ctx)
void addVertexing (Context &ctx)
void addPythia8 (Context &ctx)
void addSvg (Context &ctx)
void addObj (Context &ctx)
void addOnnx (Context &ctx)
void addOnnxMlpack (Context &ctx)
void addOnnxNeuralCalibrator (Context &ctx)
Function Documentation
void Acts::Python::addAlgebra (Acts::Python::Context & ctx)
Definition at line 238 of file Base.cpp.
View newest version in sPHENIX GitHub at line 238 of file Base.cpp
References testSigmaEff::v.
Referenced by PYBIND11_MODULE().
void Acts::Python::addAmbiguityResolution (Context & ctx)
Definition at line 24 of file AmbiguityResolution.cpp.
View newest version in sPHENIX GitHub at line 24 of file AmbiguityResolution.cpp
References ACTS_PYTHON_DECLARE_ALGORITHM, Acts::Python::Context::get(), truth_tracking_gsf_refitting::inputTracks, Acts::UnitConstants::m, full_chain_odd::maximumSharedHits, physmon_track_finding_ttbar::nMeasurementsMin, and truth_tracking_gsf_refitting::outputTracks.
Referenced by PYBIND11_MODULE().
void Acts::Python::addBinning (Context & ctx)
Definition at line 283 of file Base.cpp.
View newest version in sPHENIX GitHub at line 283 of file Base.cpp
Referenced by PYBIND11_MODULE().
void Acts::Python::addDetector (Context & ctx)
Definition at line 37 of file Detector.cpp.
View newest version in sPHENIX GitHub at line 37 of file Detector.cpp
References ACTS_PYTHON_MEMBER, ACTS_PYTHON_STRUCT_BEGIN, ACTS_PYTHON_STRUCT_END, Acts::arbitrary, Acts::Test::at, telescope_simulation::binValue, bounds, Acts::PhysicalConstants::c, cfg, filter::Config, ActsExamples::IContextDecorator::decorate(), Acts::equidistant, file, myAnalysis::finalize(), GenericDetector::finalize(), ActsExamples::TGeoDetector::finalize(), Acts::Python::Context::get(), myAnalysis::init(), ActsExamples::Options::Interval::lower, Acts::UnitConstants::m, CKF_timing_vs_mu::mode, perf_headwind::name, ActsExamples::IContextDecorator::name(), patchKwargsConstructor(), telescope_simulation::positions, seed, truth_tracking_telescope::stereos, thickness, parse_cmake_options::type, ActsExamples::Options::Interval::upper, testSigmaEff::v, value, and volumes.
Referenced by PYBIND11_MODULE().
void Acts::Python::addDetectorInspectors (Context &)
Definition at line 16 of file DetectorInspectorsStub.cpp.
View newest version in sPHENIX GitHub at line 16 of file DetectorInspectorsStub.cpp
void Acts::Python::addDigitization (Context & ctx)
Definition at line 44 of file Digitization.cpp.
View newest version in sPHENIX GitHub at line 44 of file Digitization.cpp
References ACTS_PYTHON_MEMBER, ACTS_PYTHON_STRUCT_BEGIN, ACTS_PYTHON_STRUCT_END, Acts::PhysicalConstants::c, filter::Config, filter::config, ActsExamples::DigitizationAlgorithm::config(), Acts::Python::Context::get(), Acts::getDefaultLogger(), myAnalysis::init(), physmon_simulation::level, Acts::UnitConstants::m, patchKwargsConstructor(), physmon_simulation::randomNumbers, ActsExamples::readDigiConfigFromJson(), digitization_config::trackingGeometry, and ActsExamples::writeDigiConfigToJson().
Referenced by PYBIND11_MODULE().
void Acts::Python::addEDM4hep (Context & ctx)
Definition at line 32 of file EDM4hep.cpp.
View newest version in sPHENIX GitHub at line 32 of file EDM4hep.cpp
References ACTS_PYTHON_DECLARE_READER, ACTS_PYTHON_DECLARE_WRITER, Acts::IntegrationTest::Bz, Acts::Python::Context::get(), truth_tracking_gsf_refitting::inputMeasurementParticlesMap, physmon_simulation::inputParticles, truth_tracking_gsf_refitting::inputTracks, truth_tracking_gsf_refitting::inputTrajectories, physmon_simulation::outputParticles, physmon_simulation::outputSimHits, and truth_tracking_gsf_refitting::outputTracks.
Referenced by PYBIND11_MODULE().
void Acts::Python::addEventData (Context & ctx)
Definition at line 21 of file EventData.cpp.
View newest version in sPHENIX GitHub at line 21 of file EventData.cpp
References Acts::ParticleHypothesis::chargedGeantino(), Acts::ParticleHypothesis::electron(), Acts::ParticleHypothesis::geantino(), Acts::Python::Context::get(), Acts::UnitConstants::m, Acts::ParticleHypothesis::muon(), os, particleHypothesis, and Acts::ParticleHypothesis::pion().
Referenced by PYBIND11_MODULE().
void Acts::Python::addExampleAlgorithms (Context & ctx)
Definition at line 32 of file ExampleAlgorithms.cpp.
View newest version in sPHENIX GitHub at line 32 of file ExampleAlgorithms.cpp
References ACTS_PYTHON_DECLARE_ALGORITHM, ACTS_PYTHON_MEMBER, ACTS_PYTHON_STRUCT_BEGIN, ACTS_PYTHON_STRUCT_END, Acts::PhysicalConstants::c, filter::Config, filter::config, Acts::Python::Context::get(), truth_tracking_gsf_refitting::inputMeasurementParticlesMap, physmon_simulation::inputParticles, truth_tracking_gsf_refitting::inputTracks, Acts::UnitConstants::m, ActsTests::PropagationDatasets::magneticField, nEtaBins, physmon_simulation::outputParticlesFinal, physmon_simulation::outputParticlesInitial, physmon_simulation::outputSimHits, truth_tracking_gsf_refitting::outputTracks, patchKwargsConstructor(), Acts::Test::phiMin, pythonRangeProperty(), physmon_simulation::randomNumbers, ActsExamples::readJsonGeometryList(), ActsExamples::selectLayer(), ActsExamples::selectModule(), ActsExamples::selectVolume(), and digitization_config::trackingGeometry.
Referenced by PYBIND11_MODULE().
void Acts::Python::addExaTrkXTrackFinding (Context & ctx)
Definition at line 35 of file ExaTrkXTrackFinding.cpp.
View newest version in sPHENIX GitHub at line 35 of file ExaTrkXTrackFinding.cpp
References ACTS_PYTHON_DECLARE_ALGORITHM, ACTS_PYTHON_MEMBER, ACTS_PYTHON_STRUCT_BEGIN, ACTS_PYTHON_STRUCT_END, C, Acts::PhysicalConstants::c, filter::Config, filter::config, Acts::UnitConstants::e, Acts::UnitConstants::g, Acts::Test::geometry, Acts::Python::Context::get(), Acts::getDefaultLogger(), myAnalysis::init(), physmon_simulation::inputParticles, Acts::UnitConstants::m, ActsTests::PropagationDatasets::magneticField, truth_tracking_gsf_refitting::outputTracks, utils::run, t, and digitization_config::trackingGeometry.
Referenced by PYBIND11_MODULE().
void Acts::Python::addExperimentalGeometry (Context & ctx)
Definition at line 180 of file Geometry.cpp.
View newest version in sPHENIX GitHub at line 180 of file Geometry.cpp
References ACTS_PYTHON_DECLARE_ALGORITHM, ACTS_PYTHON_MEMBER, ACTS_PYTHON_STRUCT_BEGIN, ACTS_PYTHON_STRUCT_END, filter::config, Acts::Python::Context::get(), Acts::getDefaultLogger(), Jetscape::gid, myAnalysis::init(), physmon_simulation::level, Acts::UnitConstants::m, perf_headwind::name, Acts::Test::ntests, physmon_simulation::randomNumbers, writeMapConfig::surface, and Acts::Test::transform.
Referenced by PYBIND11_MODULE().
void Acts::Python::addFramework (Context & ctx)
Definition at line 97 of file Framework.cpp.
View newest version in sPHENIX GitHub at line 97 of file Framework.cpp
References ACTS_PYTHON_MEMBER, ACTS_PYTHON_STRUCT_BEGIN, ACTS_PYTHON_STRUCT_END, ActsExamples::Sequencer::addAlgorithm(), ActsExamples::Sequencer::addContextDecorator(), ActsExamples::Sequencer::addReader(), ActsExamples::Sequencer::addWhiteboardAlias(), ActsExamples::Sequencer::addWriter(), ActsExamples::AlgorithmContext::algorithmNumber, Acts::PhysicalConstants::c, ActsExamples::AlgorithmContext::calibContext, cfg, filter::Config, ActsExamples::Sequencer::config(), Acts::FpeMonitor::Result::count(), test_fpe::count, ActsExamples::AlgorithmContext::eventNumber, physmon_vertexing::events, ActsExamples::IAlgorithm::execute(), ActsExamples::WhiteBoard::exists(), file, Acts::UnitConstants::fm, physmon_track_finding_ttbar::fpeMasks, ActsExamples::AlgorithmContext::fpeMonitor, ActsExamples::Sequencer::fpeResult(), ActsExamples::AlgorithmContext::geoContext, Acts::Python::Context::get(), Acts::getDefaultLogger(), myAnalysis::init(), ActsExamples::SequenceElement::internalExecute(), physmon_simulation::level, test_fpe::lines, telescope_simulation::logLevel, Acts::UnitConstants::m, ActsExamples::AlgorithmContext::magFieldContext, Acts::FpeMonitor::Result::merge(), Acts::FpeMonitor::Result::merged(), perf_headwind::name, ActsExamples::SequenceElement::name(), os, outputDir, physmon_simulation::randomNumbers, Acts::FpeMonitor::rearm(), Acts::FpeMonitor::result(), ActsExamples::RandomNumbers::Config::seed, Acts::Test::skip, SUCCESS, Acts::FpeMonitor::Result::summary(), parse_cmake_options::type, value, and Acts::Test::values.
Referenced by PYBIND11_MODULE().
void Acts::Python::addGeant4HepMC3 (Context & ctx)
Definition at line 25 of file Geant4HepMC3.cpp.
View newest version in sPHENIX GitHub at line 25 of file Geant4HepMC3.cpp
References ACTS_PYTHON_DECLARE_ALGORITHM, event_recording::detectorConstructionFactory, Acts::Python::Context::get(), physmon_simulation::inputParticles, and Acts::UnitConstants::m.
Referenced by PYBIND11_MODULE().
void Acts::Python::addGenerators (Context & ctx) static
Definition at line 51 of file Generators.cpp.
View newest version in sPHENIX GitHub at line 51 of file Generators.cpp
References cfg, charge(), filter::Config, ActsExamples::EventGenerator::config(), ActsExamples::FixedVertexGenerator::fixed, Acts::UnitConstants::g, gen(), physmon_simulation::generators, Acts::Python::Context::get(), myAnalysis::init(), mass, ActsExamples::PoissonMultiplicityGenerator::mean, ActsExamples::GaussianVertexGenerator::mean, mean(), full_chain_odd::multiplicity, ActsExamples::FixedMultiplicityGenerator::n, n, physmon_simulation::outputParticles, particles, pdg, Acts::Test::phiMin, physmon_simulation::randomNumbers, ActsExamples::GaussianVertexGenerator::stddev, testSigmaEff::v, and value.
Referenced by PYBIND11_MODULE().
void Acts::Python::addGeometry (Context & ctx)
Definition at line 64 of file Geometry.cpp.
View newest version in sPHENIX GitHub at line 64 of file Geometry.cpp
References Acts::GeometryIdentifier::approach(), Acts::GeometryIdentifier::boundary(), bounds, Acts::GeometryIdentifier::extra(), Acts::Python::Context::get(), Acts::TrackingGeometry::highestTrackingVolumeShared(), myAnalysis::init(), Acts::GeometryIdentifier::layer(), Acts::UnitConstants::m, physmon_track_finding_ttbar::r, Acts::GeometryIdentifier::sensitive(), Acts::Extent::set(), Acts::GeometryIdentifier::setApproach(), Acts::GeometryIdentifier::setBoundary(), Acts::GeometryIdentifier::setExtra(), Acts::GeometryIdentifier::setLayer(), Acts::GeometryIdentifier::setSensitive(), Acts::GeometryIdentifier::setVolume(), value, and Acts::GeometryIdentifier::volume().
Referenced by PYBIND11_MODULE().
void Acts::Python::addHepMC3 (Context & ctx)
Definition at line 25 of file HepMC3.cpp.
View newest version in sPHENIX GitHub at line 25 of file HepMC3.cpp
References ACTS_PYTHON_DECLARE_ALGORITHM, ACTS_PYTHON_DECLARE_READER, ACTS_PYTHON_DECLARE_WRITER, Acts::Python::Context::get(), material_mapping_optimisation::inputDir, Acts::UnitConstants::m, and outputDir.
Referenced by PYBIND11_MODULE().
void Acts::Python::addInput (Context & ctx)
Definition at line 34 of file Input.cpp.
View newest version in sPHENIX GitHub at line 34 of file Input.cpp
References ACTS_PYTHON_DECLARE_READER, truth_tracking_gsf_refitting::filePath, Acts::Python::Context::get(), material_mapping_optimisation::inputDir, physmon_simulation::outputParticles, physmon_simulation::outputSimHits, truth_tracking_gsf_refitting::outputTracks, material_mapping::readCachedSurfaceInformation, and digitization_config::trackingGeometry.
Referenced by PYBIND11_MODULE().
void Acts::Python::addJson (Context & ctx)
Definition at line 49 of file Json.cpp.
View newest version in sPHENIX GitHub at line 49 of file Json.cpp
References ACTS_PYTHON_MEMBER, ACTS_PYTHON_STRUCT_BEGIN, ACTS_PYTHON_STRUCT_END, Acts::PhysicalConstants::c, filter::config, Acts::DetectorJsonConverter::fromJson(), gctx, Acts::Python::Context::get(), in, myAnalysis::init(), Acts::UnitConstants::m, Acts::Experimental::Detector::name(), out, outputDir, Acts::DetectorVolumeJsonConverter::Options::portalOptions, ActsExamples::JsonSurfacesReader::read(), Acts::DetectorVolumeJsonConverter::Options::surfaceOptions, Acts::PortalJsonConverter::Options::surfaceOptions, Acts::DetectorJsonConverter::toJson(), Acts::DetectorJsonConverter::toJsonDetray(), digitization_config::trackingGeometry, Acts::DetectorVolumeJsonConverter::Options::transformOptions, Acts::SurfaceJsonConverter::Options::transformOptions, Acts::Transform3JsonConverter::Options::transpose, value, write(), and Acts::Transform3JsonConverter::Options::writeIdentity.
Referenced by PYBIND11_MODULE().
void Acts::Python::addLogging (Acts::Python::Context & ctx)
Definition at line 99 of file Base.cpp.
View newest version in sPHENIX GitHub at line 99 of file Base.cpp
References addPdgParticle(), check_smearing_config::args, Acts::Logging::DEBUG, Acts::UnitConstants::e, Acts::eInvalid, Acts::Logging::ERROR, Acts::Logging::FATAL, Acts::Python::Context::get(), Acts::Logging::getFailureThreshold(), Acts::Logging::INFO, physmon_simulation::level, logger(), Acts::UnitConstants::m, Acts::Logging::MAX, gtest_output_test::message, perf_headwind::name, merge_hashes::p, Acts::Logging::setFailureThreshold(), value, Acts::Logging::VERBOSE, and Acts::Logging::WARNING.
Referenced by PYBIND11_MODULE().
void Acts::Python::addMagneticField (Context & ctx)
Definition at line 39 of file MagneticField.cpp.
View newest version in sPHENIX GitHub at line 39 of file MagneticField.cpp
References bins, Acts::IntegrationTest::bMagCenter, filter::Config, file, filename, Acts::Python::Context::get(), myAnalysis::init(), G4PLUGDOOR::length, ActsExamples::HepMC3Event::lengthUnit(), Acts::UnitConstants::m, ActsExamples::makeMagneticFieldMapRzFromRoot(), ActsExamples::makeMagneticFieldMapRzFromText(), ActsExamples::makeMagneticFieldMapXyzFromRoot(), ActsExamples::makeMagneticFieldMapXyzFromText(), Acts::UnitConstants::mm, testing::internal::move(), Acts::IntegrationTest::nCoils, path, Acts::solenoidFieldMap(), Acts::UnitConstants::T, and tree.
Referenced by PYBIND11_MODULE().
void Acts::Python::addMaterial (Context & ctx)
Definition at line 44 of file Material.cpp.
View newest version in sPHENIX GitHub at line 44 of file Material.cpp
References ACTS_PYTHON_MEMBER, ACTS_PYTHON_STRUCT_BEGIN, ACTS_PYTHON_STRUCT_END, Acts::PhysicalConstants::c, filter::Config, filter::config, Acts::Test::geoContext, Acts::Python::Context::get(), Acts::getDefaultLogger(), myAnalysis::init(), physmon_simulation::level, Acts::UnitConstants::m, Acts::Test::magFieldContext, testing::internal::move(), and digitization_config::trackingGeometry.
Referenced by PYBIND11_MODULE().
void Acts::Python::addObj (Context & ctx)
Write a collection of surfaces to an '.obj' file
Parameters
surfaces is the collection of surfaces
viewContext is the geometry context
viewRgb is the color of the surfaces
fileName is the path to the output file
Write a collection of surfaces to an '.obj' file
Parameters
surfaces is the collection of surfaces
viewContext is the geometry context
viewRgb is the color of the surfaces
fileName is the path to the output file
Definition at line 28 of file Obj.cpp.
View newest version in sPHENIX GitHub at line 28 of file Obj.cpp
References Acts::GeometryView3D::drawSurface(), Acts::Python::Context::get(), Acts::UnitConstants::m, writeMapConfig::surface, and Acts::ObjVisualization3D< T >::write().
Referenced by PYBIND11_MODULE().
void Acts::Python::addOnnx (Context & ctx)
Definition at line 22 of file Onnx.cpp.
View newest version in sPHENIX GitHub at line 22 of file Onnx.cpp
References ACTS_PYTHON_DECLARE_ALGORITHM, Acts::Python::Context::get(), truth_tracking_gsf_refitting::inputTracks, Acts::UnitConstants::m, Acts::Python::Context::modules, physmon_track_finding_ttbar::nMeasurementsMin, and truth_tracking_gsf_refitting::outputTracks.
Referenced by PYBIND11_MODULE().
void Acts::Python::addOnnxMlpack (Context & ctx)
Definition at line 22 of file OnnxMlpack.cpp.
View newest version in sPHENIX GitHub at line 22 of file OnnxMlpack.cpp
References ACTS_PYTHON_DECLARE_ALGORITHM, Acts::Python::Context::get(), truth_tracking_gsf_refitting::inputTracks, Acts::UnitConstants::m, physmon_track_finding_ttbar::nMeasurementsMin, and truth_tracking_gsf_refitting::outputTracks.
Referenced by PYBIND11_MODULE().
void Acts::Python::addOnnxNeuralCalibrator (Context & ctx)
Definition at line 22 of file OnnxNeuralCalibrator.cpp.
View newest version in sPHENIX GitHub at line 22 of file OnnxNeuralCalibrator.cpp
References Acts::Python::Context::get(), and Acts::UnitConstants::m.
Referenced by PYBIND11_MODULE().
void Acts::Python::addOutput (Context & ctx)
Definition at line 101 of file Output.cpp.
View newest version in sPHENIX GitHub at line 101 of file Output.cpp
References ACTS_PYTHON_DECLARE_WRITER, ACTS_PYTHON_MEMBER, ACTS_PYTHON_STRUCT_BEGIN, ACTS_PYTHON_STRUCT_END, Acts::IntegrationTest::bField, Acts::PhysicalConstants::c, color, filter::Config, truth_tracking_gsf_refitting::filePath, Acts::Python::Context::get(), ActsExamples::DigitizationConfig::getBoundIndices(), Acts::getDefaultLogger(), myAnalysis::init(), truth_tracking_gsf_refitting::inputMeasurementParticlesMap, physmon_simulation::inputParticles, truth_tracking_gsf_refitting::inputTrajectories, Acts::UnitConstants::m, physmon_track_finding_ttbar::nMeasurementsMin, offset, outputDir, add_histos::outputName, patchKwargsConstructor(), rBounds, utils::run, digitization_config::trackingGeometry, value, BlackHoleGeometry::visible, write(), and full_chain_odd::writeCovMat.
Referenced by PYBIND11_MODULE().
void Acts::Python::addPdgParticle (Acts::Python::Context & ctx)
Definition at line 216 of file Base.cpp.
View newest version in sPHENIX GitHub at line 216 of file Base.cpp
Referenced by addLogging(), and PYBIND11_MODULE().
void Acts::Python::addPropagation (Context & ctx)
Definition at line 67 of file Propagation.cpp.
View newest version in sPHENIX GitHub at line 67 of file Propagation.cpp
References ACTS_PYTHON_DECLARE_ALGORITHM, ACTS_PYTHON_MEMBER, ACTS_PYTHON_STRUCT_BEGIN, ACTS_PYTHON_STRUCT_END, Acts::IntegrationTest::bField, Acts::PhysicalConstants::c, cfg, filter::Config, Acts::Python::Context::get(), Acts::getDefaultLogger(), Acts::Logging::INFO, myAnalysis::init(), physmon_simulation::level, Acts::UnitConstants::m, CKF_timing_vs_mu::mode, testing::internal::move(), Acts::Test::ntests, particleHypothesis, propagation_timing::stepper, and Acts::trackingGeometry().
Referenced by PYBIND11_MODULE().
void Acts::Python::addPythia8 (Context & ctx)
Definition at line 28 of file Pythia8.cpp.
View newest version in sPHENIX GitHub at line 28 of file Pythia8.cpp
References gen(), Acts::Python::Context::get(), Acts::Python::Context::modules, and patchClassesWithConfig().
Referenced by PYBIND11_MODULE().
void Acts::Python::addSvg (Context & ctx)
Definition at line 34 of file Svg.cpp.
View newest version in sPHENIX GitHub at line 34 of file Svg.cpp
References ACTS_PYTHON_MEMBER, ACTS_PYTHON_STRUCT_BEGIN, ACTS_PYTHON_STRUCT_END, Acts::PhysicalConstants::c, filter::Config, Acts::Python::Context::get(), Acts::UnitConstants::m, perf_headwind::name, outputDir, prefix, digitization_config::trackingGeometry, and write().
Referenced by PYBIND11_MODULE().
void Acts::Python::addTrackFinding (Context & ctx)
Definition at line 61 of file TrackFinding.cpp.
View newest version in sPHENIX GitHub at line 61 of file TrackFinding.cpp
References ACTS_PYTHON_DECLARE_ALGORITHM, ACTS_PYTHON_MEMBER, ACTS_PYTHON_STRUCT_BEGIN, ACTS_PYTHON_STRUCT_END, bins, Acts::PhysicalConstants::c, filter::Config, filter::config, cuts, ckf::geometrySelection, Acts::Python::Context::get(), Acts::getDefaultLogger(), physmon_track_finding_ttbar::impactMax, myAnalysis::init(), digitization_config::input, truth_tracking_gsf_refitting::inputTracks, truth_tracking_gsf_refitting::inputTrajectories, physmon_simulation::level, Acts::UnitConstants::m, ActsTests::PropagationDatasets::magneticField, physmon_track_finding_ttbar::maxSeedsPerSpM, physmon_track_finding_ttbar::minPt, Acts::UnitConstants::ms, truth_tracking_gsf_refitting::outputTracks, truth_tracking_gsf_refitting::outputTrajectories, particleHypothesis, patchKwargsConstructor(), Acts::Test::phiMin, physmon_track_finding_ttbar::radLengthPerSeed, physmon_track_finding_ttbar::sigmaScattering, and digitization_config::trackingGeometry.
Referenced by PYBIND11_MODULE().
void Acts::Python::addTrackFitting (Context & ctx)
Definition at line 45 of file TrackFitting.cpp.
View newest version in sPHENIX GitHub at line 45 of file TrackFitting.cpp
References ACTS_PYTHON_DECLARE_ALGORITHM, fit(), Acts::Python::Context::get(), Acts::getDefaultLogger(), truth_tracking_gsf_refitting::inputTracks, physmon_simulation::level, Acts::AtlasBetheHeitlerApprox< NComponents, PolyDegree >::loadFromFiles(), ActsTests::PropagationDatasets::magneticField, Acts::makeDefaultBetheHeitlerApprox(), ActsExamples::makeGlobalChiSquareFitterFunction(), ActsExamples::makeGsfFitterFunction(), ActsExamples::makeKalmanFitterFunction(), truth_tracking_gsf_refitting::outputTracks, path, digitization_config::trackingGeometry, and value.
Referenced by PYBIND11_MODULE().
void Acts::Python::addTruthTracking (Context & ctx)
Definition at line 40 of file TruthTracking.cpp.
View newest version in sPHENIX GitHub at line 40 of file TruthTracking.cpp
References ACTS_PYTHON_DECLARE_ALGORITHM, ACTS_PYTHON_MEMBER, ACTS_PYTHON_STRUCT_BEGIN, ACTS_PYTHON_STRUCT_END, Acts::PhysicalConstants::c, filter::Config, filter::config, Acts::Python::Context::get(), truth_tracking_gsf_refitting::inputMeasurementParticlesMap, physmon_simulation::inputParticles, truth_tracking_gsf_refitting::inputTrajectories, physmon_simulation::outputParticles, physmon_track_finding_ttbar::outputProtoVertices, truth_tracking_gsf_refitting::outputTrajectories, particleHypothesis, Acts::Test::phiMin, pythonRangeProperty(), and physmon_simulation::randomNumbers.
Referenced by PYBIND11_MODULE().
void Acts::Python::addUnits (Context & ctx)
Definition at line 32 of file Base.cpp.
View newest version in sPHENIX GitHub at line 32 of file Base.cpp
References Acts::UnitConstants::cm, Acts::UnitConstants::cm2, Acts::UnitConstants::cm3, Acts::UnitConstants::degree, Acts::UnitConstants::e, Acts::UnitConstants::eV, Acts::UnitConstants::fm, Acts::UnitConstants::fs, Acts::UnitConstants::g, Acts::UnitConstants::Gauss, Acts::Python::Context::get(), Acts::UnitConstants::GeV, h, Acts::UnitConstants::J, Acts::UnitConstants::keV, Acts::UnitConstants::kg, Acts::UnitConstants::kGauss, Acts::UnitConstants::km, Acts::UnitConstants::m, Acts::UnitConstants::m2, Acts::UnitConstants::m3, Acts::UnitConstants::MeV, Acts::UnitConstants::min, Acts::UnitConstants::mm, Acts::UnitConstants::mm2, Acts::UnitConstants::mm3, Acts::UnitConstants::mol, Acts::UnitConstants::mrad, Acts::UnitConstants::ms, Acts::UnitConstants::nm, Acts::UnitConstants::ns, Acts::UnitConstants::pm, Acts::UnitConstants::ps, Acts::UnitConstants::rad, physmon_simulation::s, Acts::UnitConstants::T, Acts::UnitConstants::TeV, physmon_ckf_tracking::u, Acts::UnitConstants::um, UNIT, and Acts::UnitConstants::us.
Referenced by PYBIND11_MODULE().
void Acts::Python::addVertexing (Context & ctx)
Definition at line 30 of file Vertexing.cpp.
View newest version in sPHENIX GitHub at line 30 of file Vertexing.cpp
References ACTS_PYTHON_DECLARE_ALGORITHM, Acts::IntegrationTest::bField, Acts::Python::Context::get(), truth_tracking_gsf_refitting::inputTrajectories, Acts::UnitConstants::m, physmon_track_finding_ttbar::outputProtoVertices, physmon_track_finding_ttbar::outputVertices, and value.
Referenced by PYBIND11_MODULE().
Acts::Python::METHOD_TRAIT (write_method_trait_t , write)
void Acts::Python::patchClassesWithConfig (pybind11::module_ & m) inline
Definition at line 47 of file Utilities.hpp.
View newest version in sPHENIX GitHub at line 47 of file Utilities.hpp
References Acts::UnitConstants::m.
Referenced by addPythia8().
template<typename T > void Acts::Python::patchKwargsConstructor (T & c)
Definition at line 52 of file Utilities.hpp.
View newest version in sPHENIX GitHub at line 52 of file Utilities.hpp
References Acts::PhysicalConstants::c.
Referenced by addDetector(), addDigitization(), addExampleAlgorithms(), addOutput(), addTrackFinding(), and PYBIND11_MODULE().
template<typename T , typename Ur , typename Ut > void Acts::Python::pythonRangeProperty (T & obj, const std::string & name, Ur Ut::* begin, Ur Ut::* end)
Definition at line 34 of file Utilities.hpp.
View newest version in sPHENIX GitHub at line 34 of file Utilities.hpp
References parse_cmake_options::begin, and merge_hashes::p.
Referenced by addExampleAlgorithms(), and addTruthTracking().