Analysis Software: SharedPtr< T > Class Template Reference
SharedPtr< T > Class Template Reference
#include <JETSCAPE/blob/main/external_packages/fjcore.hh>
Classes
class __SharedCountingPtr
Public Member Functions
SharedPtr ()
template<class Y >
SharedPtr (Y *ptr)
SharedPtr (SharedPtr const &share)
~SharedPtr ()
void reset ()
template<class Y >
void reset (Y *ptr)
template<class Y >
void reset (SharedPtr< Y > const &share)
SharedPtr & operator= (SharedPtr const &share)
template<class Y >
SharedPtr & operator= (SharedPtr< Y > const &share)
T * operator() () const
T & operator* () const
T * operator-> () const
T * get () const
bool unique () const
long use_count () const
operator bool () const
void swap (SharedPtr &share)
void set_count (const long &count)
Private Member Functions
__SharedCountingPtr * _get_container () const
void _decrease_count ()
Private Attributes
__SharedCountingPtr * _ptr
Detailed Description
template<class T>
class SharedPtr< T >
Definition at line 280 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 280 of file fjcore.hh
Constructor & Destructor Documentation
template<class T> SharedPtr< T >::SharedPtr () inline
Definition at line 283 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 283 of file fjcore.hh
Referenced by SharedPtr< MinHeap >::reset().
template<class T> template<class Y > SharedPtr< T >::SharedPtr (Y * ptr) inline explicit
Definition at line 284 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 284 of file fjcore.hh
template<class T> SharedPtr< T >::SharedPtr (SharedPtr< T > const & share) inline
Definition at line 287 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 287 of file fjcore.hh
template<class T> SharedPtr< T >::~SharedPtr () inline
Definition at line 290 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 290 of file fjcore.hh
Member Function Documentation
template<class T> void SharedPtr< T >::_decrease_count () inline private
Definition at line 378 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 378 of file fjcore.hh
Referenced by SharedPtr< MinHeap >::reset(), and SharedPtr< MinHeap >::~SharedPtr().
template<class T> __SharedCountingPtr* SharedPtr< T >::_get_container () const inline private
Definition at line 375 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 375 of file fjcore.hh
Referenced by SharedPtr< MinHeap >::reset().
template<class T> T* SharedPtr< T >::get (void) const inline
Definition at line 328 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 328 of file fjcore.hh
Referenced by ClusterSequence::_delaunay_cluster(), get_pointer(), PseudoJet::has_structure_of(), PseudoJet::has_user_info(), operator!=(), operator==(), PseudoJet::user_info(), PseudoJet::user_info_ptr(), and Selector::validated_worker().
template<class T> SharedPtr< T >::operator bool () const inline
Definition at line 342 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 342 of file fjcore.hh
template<class T> T* SharedPtr< T >::operator() () const inline
Definition at line 317 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 317 of file fjcore.hh
template<class T> T& SharedPtr< T >::operator* () const inline
Definition at line 321 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 321 of file fjcore.hh
template<class T> T* SharedPtr< T >::operator-> () const inline
Definition at line 324 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 324 of file fjcore.hh
template<class T> SharedPtr& SharedPtr< T >::operator= (SharedPtr< T > const & share) inline
Definition at line 308 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 308 of file fjcore.hh
template<class T> template<class Y > SharedPtr& SharedPtr< T >::operator= (SharedPtr< Y > const & share) inline
Definition at line 312 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 312 of file fjcore.hh
template<class T> void SharedPtr< T >::reset () inline
Definition at line 294 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 294 of file fjcore.hh
Referenced by Selector::_copy_worker_if_needed(), ClusterSequence::_delaunay_cluster(), PseudoJet::_reset_indices(), SharedPtr< MinHeap >::operator=(), Selector::Selector(), JetDefinition::set_recombiner(), and PseudoJet::set_user_info().
template<class T> template<class Y > void SharedPtr< T >::reset (Y * ptr) inline
Definition at line 297 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 297 of file fjcore.hh
template<class T> template<class Y > void SharedPtr< T >::reset (SharedPtr< Y > const & share) inline
Definition at line 300 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 300 of file fjcore.hh
template<class T> void SharedPtr< T >::set_count (const long & count) inline
Definition at line 350 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 350 of file fjcore.hh
template<class T> void SharedPtr< T >::swap (SharedPtr< T > & share) inline
Definition at line 345 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 345 of file fjcore.hh
Referenced by swap().
template<class T> bool SharedPtr< T >::unique () const inline
Definition at line 332 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 332 of file fjcore.hh
Referenced by Selector::_copy_worker_if_needed().
template<class T> long SharedPtr< T >::use_count () const inline
Definition at line 335 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 335 of file fjcore.hh
Referenced by SharedPtr< MinHeap >::unique().
Member Data Documentation
template<class T> __SharedCountingPtr* SharedPtr< T >::_ptr private
Definition at line 383 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 383 of file fjcore.hh
Referenced by SharedPtr< MinHeap >::_decrease_count(), SharedPtr< MinHeap >::_get_container(), SharedPtr< MinHeap >::get(), SharedPtr< MinHeap >::operator()(), SharedPtr< MinHeap >::operator*(), SharedPtr< MinHeap >::operator->(), SharedPtr< MinHeap >::reset(), SharedPtr< MinHeap >::set_count(), SharedPtr< MinHeap >::SharedPtr(), SharedPtr< MinHeap >::swap(), SharedPtr< MinHeap >::use_count(), and SharedPtr< MinHeap >::~SharedPtr().
The documentation for this class was generated from the following file:
JETSCAPE/blob/main/external_packages/fjcore.hh