Analysis Software: Acts::Experimental::DetectorNavigator Class Reference
Acts::Experimental::DetectorNavigator Class Reference
#include <acts/blob/sPHENIX/Core/include/Acts/Navigation/DetectorNavigator.hpp>
Classes
struct Config
struct State
Public Member Functions
DetectorNavigator (Config cfg, std::shared_ptr< const Logger > _logger=getDefaultLogger("DetectorNavigator", Logging::Level::INFO))
template<typename propagator_state_t >
std::string volInfo (const propagator_state_t &state) const
template<typename propagator_state_t , typename stepper_t >
std::string posInfo (const propagator_state_t &state, const stepper_t &stepper) const
const Logger & logger () const
bool inactive () const
template<typename propagator_state_t , typename stepper_t >
void initializeTarget (propagator_state_t &state, const stepper_t &stepper) const
Navigation (re-)initialisation for the target.
template<typename propagator_state_t , typename stepper_t >
void fillNavigationState (propagator_state_t &state, const stepper_t &stepper, NavigationState &nState) const
Public Attributes
m_logger
std::shared_ptr< const Logger > m_logger
Detailed Description
Definition at line 34 of file DetectorNavigator.hpp.
View newest version in sPHENIX GitHub at line 34 of file DetectorNavigator.hpp
Constructor & Destructor Documentation
Acts::Experimental::DetectorNavigator::DetectorNavigator (Config cfg, std::shared_ptr< const Logger > _logger = getDefaultLogger("DetectorNavigator", Logging::Level::INFO)) inline explicit
Constructor with configuration object
Parameters
cfg The navigator configuration
_logger a logger instance
Definition at line 71 of file DetectorNavigator.hpp.
View newest version in sPHENIX GitHub at line 71 of file DetectorNavigator.hpp
Member Function Documentation
template<typename propagator_state_t , typename stepper_t > void Acts::Experimental::DetectorNavigator::fillNavigationState (propagator_state_t & state, const stepper_t & stepper, NavigationState & nState) const inline
Definition at line 429 of file DetectorNavigator.hpp.
View newest version in sPHENIX GitHub at line 429 of file DetectorNavigator.hpp
References Acts::Experimental::NavigationState::absMomentum, ACTS_ERROR, Acts::Experimental::NavigationState::direction, Acts::Experimental::NavigationState::magneticField, posInfo(), Acts::Experimental::NavigationState::position, and volInfo().
bool Acts::Experimental::DetectorNavigator::inactive () const inline
This checks if a navigation break had been triggered or navigator is misconfigured
boolean return triggers exit to stepper
Definition at line 359 of file DetectorNavigator.hpp.
View newest version in sPHENIX GitHub at line 359 of file DetectorNavigator.hpp
References m_cfg().
template<typename propagator_state_t , typename stepper_t > void Acts::Experimental::DetectorNavigator::initializeTarget (propagator_state_t & state, const stepper_t & stepper) const inline
Navigation (re-)initialisation for the target.
Note
This is only called a few times every propagation/extrapolation
As a straight line estimate can lead you to the wrong destination Volume, this will be called at:
initialization
attempted volume switch Target finding by association will not be done again
Template Parameters
propagator_state_t The state type of the propagator
stepper_t The type of stepper used for the propagation
Parameters
[in,out] state is the propagation state object
[in] stepper Stepper in use
boolean return triggers exit to stepper
Definition at line 390 of file DetectorNavigator.hpp.
View newest version in sPHENIX GitHub at line 390 of file DetectorNavigator.hpp
References KFPMath::a, ACTS_ERROR, Acts::ACTS_VERBOSE(), KFPMath::b, Acts::Experimental::NavigationState::currentDetector, Acts::Experimental::NavigationState::currentVolume, Acts::Experimental::Detector::findDetectorVolume(), nState, posInfo(), Acts::Experimental::NavigationState::position, Acts::Experimental::detail::BlueprintHelper::sort(), Acts::Experimental::NavigationState::surfaceCandidate, Acts::Experimental::NavigationState::surfaceCandidates, Acts::Experimental::DetectorVolume::updateNavigationState(), and volInfo().
const Logger& Acts::Experimental::DetectorNavigator::logger () const inline
Definition at line 353 of file DetectorNavigator.hpp.
View newest version in sPHENIX GitHub at line 353 of file DetectorNavigator.hpp
References m_logger.
template<typename propagator_state_t , typename stepper_t > std::string Acts::Experimental::DetectorNavigator::posInfo (const propagator_state_t & state, const stepper_t & stepper) const inline
Definition at line 345 of file DetectorNavigator.hpp.
View newest version in sPHENIX GitHub at line 345 of file DetectorNavigator.hpp
Referenced by fillNavigationState(), and initializeTarget().
template<typename propagator_state_t > std::string Acts::Experimental::DetectorNavigator::volInfo (const propagator_state_t & state) const inline
Definition at line 337 of file DetectorNavigator.hpp.
View newest version in sPHENIX GitHub at line 337 of file DetectorNavigator.hpp
References Acts::Experimental::NavigationState::currentVolume, Acts::Experimental::DetectorVolume::name(), and nState.
Referenced by fillNavigationState(), and initializeTarget().
Member Data Documentation
Acts::Experimental::DetectorNavigator::m_logger
Definition at line 75 of file DetectorNavigator.hpp.
View newest version in sPHENIX GitHub at line 75 of file DetectorNavigator.hpp
Referenced by logger().
std::shared_ptr<const Logger> Acts::Experimental::DetectorNavigator::m_logger
Definition at line 334 of file DetectorNavigator.hpp.
View newest version in sPHENIX GitHub at line 334 of file DetectorNavigator.hpp
The documentation for this class was generated from the following file:
acts/blob/sPHENIX/Core/include/Acts/Navigation/DetectorNavigator.hpp