Analysis Software: PHG4CentralityReco Class Reference
PHG4CentralityReco Class Reference
#include <coresoftware/blob/master/simulation/g4simulation/g4centrality/PHG4CentralityReco.h>
Public Member Functions
PHG4CentralityReco (const std::string &name="PHG4CentralityReco")
~PHG4CentralityReco () override
int InitRun (PHCompositeNode *topNode) override
int process_event (PHCompositeNode *topNode) override
int End (PHCompositeNode *topNode) override
Called at the end of all processing.
void DoCentralityCalibration (bool do_centrality_calibration)
PHParameters & GetCalibrationParameters ()
Public Member Functions inherited from SubsysReco
~SubsysReco () override
virtual int EndRun (const int)
Called at the end of each run.
virtual int Init (PHCompositeNode *)
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
void Print (const std::string &="ALL") const override
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Private Member Functions
void CreateNode (PHCompositeNode *topNode)
void FillNode (PHCompositeNode *topNode)
Private Attributes
PHParameters _centrality_calibration_params
bool _do_centrality_calibration = true
std::map< float, int > _cent_cal_bimp
std::map< float, int > _cent_cal_epd
std::map< float, int > _cent_cal_mbd
float _bimp = NAN
float _bimp_cent = NAN
float _epd_N = NAN
float _epd_S = NAN
float _epd_NS = NAN
float _epd_cent = NAN
float _mbd_N = NAN
float _mbd_S = NAN
float _mbd_NS = NAN
float _mbd_cent = NAN
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = std::numeric_limits<int>::max() - 10
}
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Detailed Description
Definition at line 20 of file PHG4CentralityReco.h.
View newest version in sPHENIX GitHub at line 20 of file PHG4CentralityReco.h
Constructor & Destructor Documentation
PHG4CentralityReco::PHG4CentralityReco (const std::string & name = "PHG4CentralityReco")
Definition at line 28 of file PHG4CentralityReco.cc.
View newest version in sPHENIX GitHub at line 28 of file PHG4CentralityReco.cc
PHG4CentralityReco::~PHG4CentralityReco () inline override
Definition at line 24 of file PHG4CentralityReco.h.
View newest version in sPHENIX GitHub at line 24 of file PHG4CentralityReco.h
Member Function Documentation
void PHG4CentralityReco::CreateNode (PHCompositeNode * topNode) private
Definition at line 340 of file PHG4CentralityReco.cc.
View newest version in sPHENIX GitHub at line 340 of file PHG4CentralityReco.cc
References PHCompositeNode::addNode(), PHNodeIterator::findFirst(), and PHWHERE.
Referenced by InitRun().
void PHG4CentralityReco::DoCentralityCalibration (bool do_centrality_calibration) inline
Definition at line 30 of file PHG4CentralityReco.h.
View newest version in sPHENIX GitHub at line 30 of file PHG4CentralityReco.h
References _do_centrality_calibration.
int PHG4CentralityReco::End (PHCompositeNode *) override virtual
Called at the end of all processing.
Reimplemented from SubsysReco.
Definition at line 311 of file PHG4CentralityReco.cc.
View newest version in sPHENIX GitHub at line 311 of file PHG4CentralityReco.cc
References Fun4AllReturnCodes::EVENT_OK.
void PHG4CentralityReco::FillNode (PHCompositeNode * topNode) private
Definition at line 316 of file PHG4CentralityReco.cc.
View newest version in sPHENIX GitHub at line 316 of file PHG4CentralityReco.cc
References _bimp, _bimp_cent, _epd_cent, _epd_N, _epd_NS, _epd_S, _mbd_cent, _mbd_N, _mbd_NS, _mbd_S, CentralityInfo::set_centile(), and CentralityInfo::set_quantity().
Referenced by process_event().
PHParameters& PHG4CentralityReco::GetCalibrationParameters () inline
Definition at line 35 of file PHG4CentralityReco.h.
View newest version in sPHENIX GitHub at line 35 of file PHG4CentralityReco.h
References _centrality_calibration_params.
Referenced by Centrality(), Fun4All(), Fun4All_EMJetVal(), Fun4All_G4_sPHENIX(), Fun4All_JetBkgd(), Fun4All_JetNconst(), Fun4All_JetRhoMedian(), Fun4All_JetSeedCount(), Fun4All_JetSub(), Fun4All_JetVal(), Fun4All_RhoFluct(), Fun4All_RTrack(), Fun4All_UE_v2_Psi2(), and G4_HIJetReco().
int PHG4CentralityReco::InitRun (PHCompositeNode *) override virtual
Called for first event when run number is known. Typically this is where you may want to fetch data from database, because you know the run number.
Reimplemented from SubsysReco.
Definition at line 34 of file PHG4CentralityReco.cc.
View newest version in sPHENIX GitHub at line 34 of file PHG4CentralityReco.cc
References _cent_cal_bimp, _cent_cal_epd, _cent_cal_mbd, _centrality_calibration_params, CreateNode(), Acts::UnitConstants::e, Fun4AllReturnCodes::EVENT_OK, PHParameters::exist_double_param(), PHParameters::exist_string_param(), PHParameters::get_double_param(), PHParameters::get_string_param(), n, PHWHERE, and Fun4AllBase::Verbosity().
int PHG4CentralityReco::process_event (PHCompositeNode *) override virtual
Called for each event. This is where you do the real work.
Reimplemented from SubsysReco.
Definition at line 108 of file PHG4CentralityReco.cc.
View newest version in sPHENIX GitHub at line 108 of file PHG4CentralityReco.cc
References _bimp, _bimp_cent, _cent_cal_bimp, _cent_cal_epd, _cent_cal_mbd, _do_centrality_calibration, _epd_cent, _epd_N, _epd_NS, _epd_S, _mbd_cent, _mbd_N, _mbd_NS, _mbd_S, Fun4AllReturnCodes::EVENT_OK, FillNode(), EPDDefs::get_arm(), PHG4HitDefs::hit_idbits, it, signal(), and Fun4AllBase::Verbosity().
Member Data Documentation
float PHG4CentralityReco::_bimp = NAN private
Definition at line 52 of file PHG4CentralityReco.h.
View newest version in sPHENIX GitHub at line 52 of file PHG4CentralityReco.h
Referenced by FillNode(), and process_event().
float PHG4CentralityReco::_bimp_cent = NAN private
Definition at line 53 of file PHG4CentralityReco.h.
View newest version in sPHENIX GitHub at line 53 of file PHG4CentralityReco.h
Referenced by FillNode(), and process_event().
std::map<float, int> PHG4CentralityReco::_cent_cal_bimp private
Definition at line 48 of file PHG4CentralityReco.h.
View newest version in sPHENIX GitHub at line 48 of file PHG4CentralityReco.h
Referenced by InitRun(), and process_event().
std::map<float, int> PHG4CentralityReco::_cent_cal_epd private
Definition at line 49 of file PHG4CentralityReco.h.
View newest version in sPHENIX GitHub at line 49 of file PHG4CentralityReco.h
Referenced by InitRun(), and process_event().
std::map<float, int> PHG4CentralityReco::_cent_cal_mbd private
Definition at line 50 of file PHG4CentralityReco.h.
View newest version in sPHENIX GitHub at line 50 of file PHG4CentralityReco.h
Referenced by InitRun(), and process_event().
PHParameters PHG4CentralityReco::_centrality_calibration_params private
Definition at line 44 of file PHG4CentralityReco.h.
View newest version in sPHENIX GitHub at line 44 of file PHG4CentralityReco.h
Referenced by GetCalibrationParameters(), and InitRun().
bool PHG4CentralityReco::_do_centrality_calibration = true private
Definition at line 46 of file PHG4CentralityReco.h.
View newest version in sPHENIX GitHub at line 46 of file PHG4CentralityReco.h
Referenced by DoCentralityCalibration(), and process_event().
float PHG4CentralityReco::_epd_cent = NAN private
Definition at line 58 of file PHG4CentralityReco.h.
View newest version in sPHENIX GitHub at line 58 of file PHG4CentralityReco.h
Referenced by FillNode(), and process_event().
float PHG4CentralityReco::_epd_N = NAN private
Definition at line 55 of file PHG4CentralityReco.h.
View newest version in sPHENIX GitHub at line 55 of file PHG4CentralityReco.h
Referenced by FillNode(), and process_event().
float PHG4CentralityReco::_epd_NS = NAN private
Definition at line 57 of file PHG4CentralityReco.h.
View newest version in sPHENIX GitHub at line 57 of file PHG4CentralityReco.h
Referenced by FillNode(), and process_event().
float PHG4CentralityReco::_epd_S = NAN private
Definition at line 56 of file PHG4CentralityReco.h.
View newest version in sPHENIX GitHub at line 56 of file PHG4CentralityReco.h
Referenced by FillNode(), and process_event().
float PHG4CentralityReco::_mbd_cent = NAN private
Definition at line 63 of file PHG4CentralityReco.h.
View newest version in sPHENIX GitHub at line 63 of file PHG4CentralityReco.h
Referenced by FillNode(), and process_event().
float PHG4CentralityReco::_mbd_N = NAN private
Definition at line 60 of file PHG4CentralityReco.h.
View newest version in sPHENIX GitHub at line 60 of file PHG4CentralityReco.h
Referenced by FillNode(), and process_event().
float PHG4CentralityReco::_mbd_NS = NAN private
Definition at line 62 of file PHG4CentralityReco.h.
View newest version in sPHENIX GitHub at line 62 of file PHG4CentralityReco.h
Referenced by FillNode(), and process_event().
float PHG4CentralityReco::_mbd_S = NAN private
Definition at line 61 of file PHG4CentralityReco.h.
View newest version in sPHENIX GitHub at line 61 of file PHG4CentralityReco.h
Referenced by FillNode(), and process_event().
The documentation for this class was generated from the following files:
coresoftware/blob/master/simulation/g4simulation/g4centrality/PHG4CentralityReco.h
coresoftware/blob/master/simulation/g4simulation/g4centrality/PHG4CentralityReco.cc