Analysis Software: Fun4AllNoSyncDstInputManager Class Reference
Fun4AllNoSyncDstInputManager Class Reference
#include <coresoftware/blob/master/offline/framework/fun4all/Fun4AllNoSyncDstInputManager.h>
Public Member Functions
Fun4AllNoSyncDstInputManager (const std::string &name="DUMMY", const std::string &nodename="DST", const std::string &topnodename="TOP")
~Fun4AllNoSyncDstInputManager () override
int SyncIt (const SyncObject *) override
int GetSyncObject (SyncObject **) override
int NoSyncPushBackEvents (const int nevt) override
int setSyncBranches (PHNodeIOManager *) override
int NoRunTTree ()
int SkipForThisManager (const int nevents) override
int HasSyncObject () const override
Public Member Functions inherited from Fun4AllDstInputManager
Fun4AllDstInputManager (const std::string &name="DUMMY", const std::string &nodename="DST", const std::string &topnodename="TOP")
~Fun4AllDstInputManager () override
int fileopen (const std::string &filenam) override
int fileclose () override
int run (const int nevents=0) override
int BranchSelect (const std::string &branch, const int iflag) override
int setBranches () override
void Print (const std::string &what="ALL") const override
int PushBackEvents (const int i) override
Public Member Functions inherited from Fun4AllInputManager
~Fun4AllInputManager () override
virtual int ReadInRunNode (PHCompositeNode *)
std::string FileName () const
void FileName (const std::string &fn)
void Print (const std::string &what="ALL") const override
virtual int skip (const int nevt)
int AddFile (const std::string &filename)
int AddListFile (const std::string &filename, const int do_it=0)
int registerSubsystem (SubsysReco *subsystem)
virtual int RejectEvent ()
void Repeat (const int i=-1)
virtual void setSyncManager (Fun4AllSyncManager *master)
virtual int ResetFileList ()
virtual int ResetEvent ()
virtual void SetRunNumber (const int runno)
virtual int RunNumber () const
void AddToFileOpened (const std::string &filename)
std::pair< std::list
< std::string >
::const_iterator, std::list
< std::string >
::const_iterator > FileOpenListBeginEnd ()
std::string InputNode ()
void InputNode (const std::string &innode)
std::string TopNodeName () const
bool FileListEmpty () const
virtual int IsOpen () const
virtual std::string GetString (const std::string &) const
const std::list< std::string > GetFileList () const
const std::list< std::string > GetFileOpenedList () const
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = std::numeric_limits<int>::max() - 10
}
Protected Member Functions inherited from Fun4AllDstInputManager
int ReadNextEventSyncObject ()
void ReadRunTTree (const int i)
void IManager (PHNodeIOManager *iman)
PHNodeIOManager * IManager ()
void runNode (PHCompositeNode *node)
PHCompositeNode * runNode ()
void runNodeCopy (PHCompositeNode *node)
PHCompositeNode * runNodeCopy ()
void runNodeSum (PHCompositeNode *node)
PHCompositeNode * runNodeSum ()
std::string RunNodeName () const
Protected Attributes inherited from Fun4AllDstInputManager
std::string fullfilename
Detailed Description
Definition at line 15 of file Fun4AllNoSyncDstInputManager.h.
View newest version in sPHENIX GitHub at line 15 of file Fun4AllNoSyncDstInputManager.h
Constructor & Destructor Documentation
Fun4AllNoSyncDstInputManager::Fun4AllNoSyncDstInputManager (const std::string & name = "DUMMY", const std::string & nodename = "DST", const std::string & topnodename = "TOP")
Definition at line 6 of file Fun4AllNoSyncDstInputManager.cc.
View newest version in sPHENIX GitHub at line 6 of file Fun4AllNoSyncDstInputManager.cc
Fun4AllNoSyncDstInputManager::~Fun4AllNoSyncDstInputManager () inline override
Definition at line 20 of file Fun4AllNoSyncDstInputManager.h.
View newest version in sPHENIX GitHub at line 20 of file Fun4AllNoSyncDstInputManager.h
Member Function Documentation
int Fun4AllNoSyncDstInputManager::GetSyncObject (SyncObject **) inline override virtual
Reimplemented from Fun4AllDstInputManager.
Definition at line 25 of file Fun4AllNoSyncDstInputManager.h.
View newest version in sPHENIX GitHub at line 25 of file Fun4AllNoSyncDstInputManager.h
References Fun4AllReturnCodes::SYNC_NOOBJECT.
int Fun4AllNoSyncDstInputManager::HasSyncObject () const inline override virtual
Reimplemented from Fun4AllDstInputManager.
Definition at line 34 of file Fun4AllNoSyncDstInputManager.h.
View newest version in sPHENIX GitHub at line 34 of file Fun4AllNoSyncDstInputManager.h
int Fun4AllNoSyncDstInputManager::NoRunTTree ()
Definition at line 14 of file Fun4AllNoSyncDstInputManager.cc.
View newest version in sPHENIX GitHub at line 14 of file Fun4AllNoSyncDstInputManager.cc
References Fun4AllInputManager::IsOpen(), Fun4AllBase::Name(), and Fun4AllDstInputManager::ReadRunTTree().
int Fun4AllNoSyncDstInputManager::NoSyncPushBackEvents (const int nevt) inline override virtual
Reimplemented from Fun4AllInputManager.
Definition at line 26 of file Fun4AllNoSyncDstInputManager.h.
View newest version in sPHENIX GitHub at line 26 of file Fun4AllNoSyncDstInputManager.h
References Fun4AllDstInputManager::PushBackEvents().
int Fun4AllNoSyncDstInputManager::setSyncBranches (PHNodeIOManager *) inline override virtual
Reimplemented from Fun4AllDstInputManager.
Definition at line 28 of file Fun4AllNoSyncDstInputManager.h.
View newest version in sPHENIX GitHub at line 28 of file Fun4AllNoSyncDstInputManager.h
int Fun4AllNoSyncDstInputManager::SkipForThisManager (const int nevents) inline override virtual
Reimplemented from Fun4AllInputManager.
Definition at line 33 of file Fun4AllNoSyncDstInputManager.h.
View newest version in sPHENIX GitHub at line 33 of file Fun4AllNoSyncDstInputManager.h
References Fun4AllDstInputManager::PushBackEvents().
int Fun4AllNoSyncDstInputManager::SyncIt (const SyncObject *) inline override virtual
Reimplemented from Fun4AllDstInputManager.
Definition at line 24 of file Fun4AllNoSyncDstInputManager.h.
View newest version in sPHENIX GitHub at line 24 of file Fun4AllNoSyncDstInputManager.h
References Fun4AllReturnCodes::SYNC_OK.
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/framework/fun4all/Fun4AllNoSyncDstInputManager.h
coresoftware/blob/master/offline/framework/fun4all/Fun4AllNoSyncDstInputManager.cc