Analysis Software: macros/blob/master/common/G4_TrkrSimulation.C File Reference
G4_TrkrSimulation.C File Reference
#include <GlobalVariables.C>
#include <G4_TrkrVariables.C>
#include <G4_ActsGeom.C>
#include <g4detectors/PHG4CylinderSubsystem.h>
#include <g4mvtx/PHG4MvtxDefs.h>
#include <g4mvtx/PHG4MvtxDigitizer.h>
#include <g4mvtx/PHG4MvtxHitReco.h>
#include <g4mvtx/PHG4MvtxSubsystem.h>
#include <g4intt/PHG4InttDeadMapLoader.h>
#include <g4intt/PHG4InttDefs.h>
#include <g4intt/PHG4InttDigitizer.h>
#include <g4intt/PHG4InttHitReco.h>
#include <g4intt/PHG4InttSubsystem.h>
#include <g4tpc/PHG4TpcCentralMembrane.h>
#include <g4tpc/PHG4TpcDigitizer.h>
#include <g4tpc/PHG4TpcDirectLaser.h>
#include <g4tpc/PHG4TpcDistortion.h>
#include <g4tpc/PHG4TpcElectronDrift.h>
#include <g4tpc/PHG4TpcEndCapSubsystem.h>
#include <g4tpc/PHG4TpcPadPlane.h>
#include <g4tpc/PHG4TpcPadPlaneReadout.h>
#include <g4tpc/PHG4TpcSubsystem.h>
#include <tpc/TpcClusterZCrossingCorrection.h>
#include <g4micromegas/PHG4MicromegasDigitizer.h>
#include <g4micromegas/PHG4MicromegasHitReco.h>
#include <g4micromegas/PHG4MicromegasSubsystem.h>
#include <g4main/PHG4Reco.h>
#include <cmath>
#include <vector>
Macros
#define MACRO_G4TRKRSIM_C
Functions
void MvtxInit ()
double Mvtx (PHG4Reco *g4Reco, double radius, const int supportactive=0)
void Mvtx_Cells ()
void InttInit ()
double Intt (PHG4Reco *g4Reco, double radius, const int absorberactive=0)
void Intt_Cells ()
void TPCInit ()
void TPC_Endcaps (PHG4Reco *g4Reco)
TPC end cap, wagon wheel, electronics.
double TPC (PHG4Reco *g4Reco, double radius)
void TPC_Cells ()
void MicromegasInit ()
void Micromegas (PHG4Reco *g4Reco)
void Micromegas_Cells ()
Macro Definition Documentation
#define MACRO_G4TRKRSIM_C
Definition at line 2 of file G4_TrkrSimulation.C.
View newest version in sPHENIX GitHub at line 2 of file G4_TrkrSimulation.C
Function Documentation
double Intt (PHG4Reco * g4Reco, double radius, const int absorberactive = 0)
Definition at line 131 of file G4_TrkrSimulation.C.
View newest version in sPHENIX GitHub at line 131 of file G4_TrkrSimulation.C
References Enable::ABSORBER, i, Enable::INTT_ABSORBER, Enable::INTT_OVERLAPCHECK, G4INTT::intt_radius_max, Enable::INTT_SUPPORT, Enable::INTT_VERBOSITY, G4INTT::laddertype, G4INTT::n_intt_layer, G4MVTX::n_maps_layer, G4INTT::nladder, PHG4DetectorGroupSubsystem::OverlapCheck(), Enable::OVERLAPCHECK, PHG4Reco::registerSubsystem(), G4INTT::sensor_radius, PHG4DetectorGroupSubsystem::set_double_param(), PHG4DetectorGroupSubsystem::set_int_param(), PHG4DetectorGroupSubsystem::SetAbsorberActive(), PHG4DetectorGroupSubsystem::SetActive(), Enable::SUPPORT, PHG4InttDefs::SUPPORTPARAMS, verbosity, Enable::VERBOSITY, and Fun4AllBase::Verbosity().
Referenced by G4Setup(), SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::GetNumClust(), SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::GetNumLayer(), SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::GetTrackSeed(), and SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::TrkInfo::SetInfo().
void Intt_Cells ()
Definition at line 185 of file G4_TrkrSimulation.C.
View newest version in sPHENIX GitHub at line 185 of file G4_TrkrSimulation.C
References PHG4InttDeadMapLoader::deadMapPath(), i, Fun4AllServer::instance(), Enable::INTT_VERBOSITY, G4INTT::InttDeadMapOption, G4INTT::kInttDeadMap, G4INTT::kInttNoDeadMap, G4INTT::n_intt_layer, G4MVTX::n_maps_layer, TRACKING::pp_extended_readout_time, TRACKING::pp_mode, Fun4AllServer::registerSubsystem(), PHG4InttDigitizer::set_adc_scale(), PHParameterInterface::set_double_param(), verbosity, Enable::VERBOSITY, and Fun4AllBase::Verbosity().
Referenced by Fun4All_AnaTutorial_sPHENIX(), Fun4All_AnaTutorial_sPHENIX_Jets(), Fun4All_BHG(), Fun4All_G4_Calo(), Fun4All_G4_sPHENIX(), Fun4All_G4_sPHENIX_ForTrackCutStudy(), Fun4All_G4_sPHENIX_ForTrackCutStudy_EmbedScanOff(), Fun4All_G4_sPHENIX_ForTrackCutStudy_EmbedScanOn(), Fun4All_G4_sPHENIX_ForTrackCutStudy_WithPileup_EmbedScanOff(), Fun4All_G4_sPHENIX_ForTrackCutStudy_WithPileup_EmbedScanOn(), Fun4All_Pi0Gen_sPHENIX(), Fun4All_pi0tbt_SIMPLE_EMBED(), Fun4All_RunCorrelatorJetTree(), Fun4All_RunCorrelatorQAModules(), Fun4All_RunNewTruthMatcher(), Fun4All_SinglePhotonGen_sPHENIX(), Fun4All_SinglePi0Gen_sPHENIX(), run_calo_fromMDC2Hits_towslope_Fun4All_G4_Calo(), rundst_spiNo(), and spiNo2().
void InttInit ()
Definition at line 118 of file G4_TrkrSimulation.C.
View newest version in sPHENIX GitHub at line 118 of file G4_TrkrSimulation.C
References BlackHoleGeometry::max_radius, BlackHoleGeometry::max_z, Acts::UnitConstants::min, BlackHoleGeometry::min_z, Enable::MVTX, and G4MVTX::n_maps_layer.
Referenced by G4Init().
void Micromegas (PHG4Reco * g4Reco)
Definition at line 488 of file G4_TrkrSimulation.C.
View newest version in sPHENIX GitHub at line 488 of file G4_TrkrSimulation.C
References Enable::MICROMEGAS_OVERLAPCHECK, Enable::MICROMEGAS_SUPPORT, Enable::MICROMEGAS_VERBOSITY, Acts::UnitConstants::mm, G4TPC::n_gas_layer, G4INTT::n_intt_layer, G4MVTX::n_maps_layer, overlapcheck, Enable::OVERLAPCHECK, PHG4Reco::registerSubsystem(), Enable::SUPPORT, verbosity, and Enable::VERBOSITY.
Referenced by G4Setup().
void Micromegas_Cells ()
Definition at line 505 of file G4_TrkrSimulation.C.
View newest version in sPHENIX GitHub at line 505 of file G4_TrkrSimulation.C
References ACTSGEOM::ActsGeomInit(), Fun4AllServer::instance(), Enable::MICROMEGAS_VERBOSITY, TRACKING::pp_extended_readout_time, TRACKING::pp_mode, verbosity, Enable::VERBOSITY, and Fun4AllBase::Verbosity().
Referenced by Fun4All_AnaTutorial_sPHENIX(), Fun4All_AnaTutorial_sPHENIX_Jets(), Fun4All_BHG(), Fun4All_G4_Calo(), Fun4All_G4_sPHENIX(), Fun4All_G4_sPHENIX_ForTrackCutStudy(), Fun4All_G4_sPHENIX_ForTrackCutStudy_EmbedScanOff(), Fun4All_G4_sPHENIX_ForTrackCutStudy_EmbedScanOn(), Fun4All_G4_sPHENIX_ForTrackCutStudy_WithPileup_EmbedScanOff(), Fun4All_G4_sPHENIX_ForTrackCutStudy_WithPileup_EmbedScanOn(), Fun4All_Pi0Gen_sPHENIX(), Fun4All_pi0tbt_SIMPLE_EMBED(), Fun4All_RunCorrelatorJetTree(), Fun4All_RunCorrelatorQAModules(), Fun4All_RunNewTruthMatcher(), Fun4All_SinglePhotonGen_sPHENIX(), Fun4All_SinglePi0Gen_sPHENIX(), run_calo_fromMDC2Hits_towslope_Fun4All_G4_Calo(), rundst_spiNo(), and spiNo2().
void MicromegasInit ()
Definition at line 468 of file G4_TrkrSimulation.C.
View newest version in sPHENIX GitHub at line 468 of file G4_TrkrSimulation.C
References Enable::INTT, BlackHoleGeometry::max_radius, BlackHoleGeometry::max_z, Acts::UnitConstants::min, BlackHoleGeometry::min_z, Enable::MVTX, G4TPC::n_gas_layer, G4INTT::n_intt_layer, G4MVTX::n_maps_layer, and Enable::TPC.
Referenced by G4Init().
double Mvtx (PHG4Reco * g4Reco, double radius, const int supportactive = 0)
Definition at line 56 of file G4_TrkrSimulation.C.
View newest version in sPHENIX GitHub at line 56 of file G4_TrkrSimulation.C
References PHG4MvtxDefs::GLOBAL, PHG4MvtxDefs::kRmd, Enable::MVTX_OVERLAPCHECK, Enable::MVTX_SUPPORT, Enable::MVTX_VERBOSITY, PHG4MvtxDefs::mvtxdat, G4MVTX::n_maps_layer, PHG4DetectorGroupSubsystem::OverlapCheck(), Enable::OVERLAPCHECK, G4MVTX::radius_offset, PHG4Reco::registerSubsystem(), PHG4DetectorGroupSubsystem::set_string_param(), PHG4DetectorGroupSubsystem::SetActive(), PHG4DetectorGroupSubsystem::SetSupportActive(), Enable::SUPPORT, verbosity, Enable::VERBOSITY, and Fun4AllBase::Verbosity().
Referenced by G4Setup(), SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::GetNumClust(), SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::GetNumLayer(), SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::GetTrackSeed(), and SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::TrkInfo::SetInfo().
void Mvtx_Cells ()
Definition at line 90 of file G4_TrkrSimulation.C.
View newest version in sPHENIX GitHub at line 90 of file G4_TrkrSimulation.C
References Fun4AllServer::instance(), Enable::MVTX_VERBOSITY, TRACKING::pp_extended_readout_time, TRACKING::pp_mode, Fun4AllServer::registerSubsystem(), PHParameterInterface::set_double_param(), verbosity, Enable::VERBOSITY, and Fun4AllBase::Verbosity().
Referenced by Fun4All_AnaTutorial_sPHENIX(), Fun4All_AnaTutorial_sPHENIX_Jets(), Fun4All_BHG(), Fun4All_G4_Calo(), Fun4All_G4_sPHENIX(), Fun4All_G4_sPHENIX_ForTrackCutStudy(), Fun4All_G4_sPHENIX_ForTrackCutStudy_EmbedScanOff(), Fun4All_G4_sPHENIX_ForTrackCutStudy_EmbedScanOn(), Fun4All_G4_sPHENIX_ForTrackCutStudy_WithPileup_EmbedScanOff(), Fun4All_G4_sPHENIX_ForTrackCutStudy_WithPileup_EmbedScanOn(), Fun4All_Pi0Gen_sPHENIX(), Fun4All_pi0tbt_SIMPLE_EMBED(), Fun4All_RunCorrelatorJetTree(), Fun4All_RunCorrelatorQAModules(), Fun4All_RunNewTruthMatcher(), Fun4All_SinglePhotonGen_sPHENIX(), Fun4All_SinglePi0Gen_sPHENIX(), run_calo_fromMDC2Hits_towslope_Fun4All_G4_Calo(), rundst_spiNo(), and spiNo2().
void MvtxInit ()
Definition at line 49 of file G4_TrkrSimulation.C.
View newest version in sPHENIX GitHub at line 49 of file G4_TrkrSimulation.C
References BlackHoleGeometry::max_radius, BlackHoleGeometry::max_z, Acts::UnitConstants::min, and BlackHoleGeometry::min_z.
Referenced by G4Init().
double TPC (PHG4Reco * g4Reco, double radius)
Definition at line 328 of file G4_TrkrSimulation.C.
View newest version in sPHENIX GitHub at line 328 of file G4_TrkrSimulation.C
References Enable::ABSORBER, G4INTT::n_intt_layer, G4MVTX::n_maps_layer, G4TPC::n_tpc_layer_inner, no_overlapp, PHG4DetectorSubsystem::OverlapCheck(), Enable::OVERLAPCHECK, TRACKING::pp_extended_readout_time, TRACKING::pp_mode, PHG4Reco::registerSubsystem(), PHG4DetectorSubsystem::set_double_param(), PHG4DetectorSubsystem::set_int_param(), PHG4DetectorSubsystem::SetAbsorberActive(), PHG4DetectorSubsystem::SetActive(), PHG4DetectorSubsystem::SuperDetector(), Enable::TPC_ABSORBER, G4TPC::tpc_drift_velocity_sim, Enable::TPC_ENDCAP, TPC_Endcaps(), G4TPC::tpc_layer_rphi_count_inner, G4TPC::tpc_outer_radius, and Enable::TPC_OVERLAPCHECK.
void TPC_Cells ()
Definition at line 373 of file G4_TrkrSimulation.C.
View newest version in sPHENIX GitHub at line 373 of file G4_TrkrSimulation.C
References PHG4TpcElectronDrift::Detector(), G4TPC::ENABLE_CENTRAL_MEMBRANE_HITS, G4TPC::ENABLE_DIRECT_LASER_HITS, G4TPC::ENABLE_STATIC_DISTORTIONS, G4TPC::ENABLE_TIME_ORDERED_DISTORTIONS, Fun4AllServer::instance(), G4INTT::n_intt_layer, G4MVTX::n_maps_layer, TRACKING::pp_extended_readout_time, TRACKING::pp_mode, PHG4TpcDistortion::set_do_static_distortions(), PHG4TpcDigitizer::set_skip_noise_flag(), PHG4TpcDigitizer::SetADCThreshold(), PHG4TpcCentralMembrane::setCentralMembraneDelay(), PHG4TpcDigitizer::SetENC(), PHG4TpcDirectLaser::SetPhiStepping(), PHG4TpcDigitizer::SetTpcMinLayer(), G4TPC::static_distortion_filename, G4TPC::time_ordered_distortion_filename, G4TPC::tpc_drift_velocity_sim, Enable::TPC_VERBOSITY, verbosity, Enable::VERBOSITY, and Fun4AllBase::Verbosity().
Referenced by Fun4All_AnaTutorial_sPHENIX(), Fun4All_AnaTutorial_sPHENIX_Jets(), Fun4All_BHG(), Fun4All_G4_Calo(), Fun4All_G4_sPHENIX(), Fun4All_G4_sPHENIX_ForTrackCutStudy(), Fun4All_G4_sPHENIX_ForTrackCutStudy_EmbedScanOff(), Fun4All_G4_sPHENIX_ForTrackCutStudy_EmbedScanOn(), Fun4All_G4_sPHENIX_ForTrackCutStudy_WithPileup_EmbedScanOff(), Fun4All_G4_sPHENIX_ForTrackCutStudy_WithPileup_EmbedScanOn(), Fun4All_Pi0Gen_sPHENIX(), Fun4All_pi0tbt_SIMPLE_EMBED(), Fun4All_RunCorrelatorJetTree(), Fun4All_RunCorrelatorQAModules(), Fun4All_RunNewTruthMatcher(), Fun4All_SinglePhotonGen_sPHENIX(), Fun4All_SinglePi0Gen_sPHENIX(), run_calo_fromMDC2Hits_towslope_Fun4All_G4_Calo(), rundst_spiNo(), and spiNo2().
void TPC_Endcaps (PHG4Reco * g4Reco)
TPC end cap, wagon wheel, electronics.
Definition at line 310 of file G4_TrkrSimulation.C.
View newest version in sPHENIX GitHub at line 310 of file G4_TrkrSimulation.C
References Enable::ABSORBER, PHG4DetectorSubsystem::OverlapCheck(), Enable::OVERLAPCHECK, PHG4Reco::registerSubsystem(), PHG4DetectorSubsystem::SetActive(), PHG4DetectorSubsystem::SuperDetector(), Enable::TPC_ABSORBER, and Enable::TPC_OVERLAPCHECK.
Referenced by TPC().
void TPCInit ()
Definition at line 277 of file G4_TrkrSimulation.C.
View newest version in sPHENIX GitHub at line 277 of file G4_TrkrSimulation.C
References TpcClusterZCrossingCorrection::_vdrift, Enable::INTT, BlackHoleGeometry::max_radius, BlackHoleGeometry::max_z, Acts::UnitConstants::min, BlackHoleGeometry::min_z, Enable::MVTX, G4INTT::n_intt_layer, G4MVTX::n_maps_layer, G4TPC::tpc_drift_velocity_reco, Enable::TPC_ENDCAP, and G4TPC::tpc_outer_radius.