Analysis Software: SvtxTrackEval Class Reference
SvtxTrackEval Class Reference
#include <coresoftware/blob/master/simulation/g4simulation/g4eval/SvtxTrackEval.h>
Public Member Functions
SvtxTrackEval (PHCompositeNode *topNode)
virtual ~SvtxTrackEval ()
void next_event (PHCompositeNode *topNode)
void do_caching (bool do_cache)
void set_strict (bool strict)
void set_verbosity (int verbosity)
SvtxClusterEval * get_cluster_eval ()
SvtxHitEval * get_hit_eval ()
SvtxTruthEval * get_truth_eval ()
std::set< PHG4Hit * > all_truth_hits (SvtxTrack *track)
std::set< PHG4Particle * > all_truth_particles (SvtxTrack *track)
PHG4Particle * max_truth_particle_by_nclusters (SvtxTrack *track)
std::set< SvtxTrack * > all_tracks_from (PHG4Particle *truthparticle)
SvtxTrack * best_track_from (PHG4Particle *truthparticle)
std::set< SvtxTrack * > all_tracks_from (PHG4Hit *truthhit)
std::set< SvtxTrack * > all_tracks_from (TrkrDefs::cluskey cluster_key)
SvtxTrack * best_track_from (TrkrDefs::cluskey cluster_key)
void create_cache_track_from_cluster ()
void calc_cluster_contribution (SvtxTrack *svtxtrack, PHG4Particle *truthparticle)
unsigned int get_nclusters_contribution (SvtxTrack *svtxtrack, PHG4Particle *truthparticle)
std::pair< unsigned int,
unsigned int > get_layer_range_contribution (SvtxTrack *track, PHG4Particle *particle, unsigned int start_layer, unsigned int end_layer)
unsigned int get_nclusters_contribution_by_layer (SvtxTrack *svtxtrack, PHG4Particle *truthparticle)
unsigned int get_nwrongclusters_contribution (SvtxTrack *svtxtrack, PHG4Particle *truthparticle)
unsigned int get_errors ()
void set_track_nodename (const std::string &name)
Private Member Functions
void get_node_pointers (PHCompositeNode *topNode)
bool has_node_pointers ()
std::vector< TrkrDefs::cluskey > get_track_ckeys (SvtxTrack *track)
Private Attributes
SvtxClusterEval _clustereval
SvtxTrackMap * _trackmap = nullptr
PHG4TruthInfoContainer * _truthinfo = nullptr
const PHG4ParticleSvtxMap * _truthRecoMap = nullptr
const SvtxPHG4ParticleMap * _recoTruthMap = nullptr
bool _strict = false
int _verbosity = 0
unsigned int _errors = 0
bool _do_cache = true
bool _cache_track_from_cluster_exists = false
std::map< SvtxTrack
*, std::set< PHG4Hit * > > _cache_all_truth_hits
std::map< SvtxTrack
*, std::set< PHG4Particle * > > _cache_all_truth_particles
std::map< SvtxTrack
*, PHG4Particle * > _cache_max_truth_particle_by_nclusters
std::map< PHG4Particle
*, std::set< SvtxTrack * > > _cache_all_tracks_from_particle
std::map< PHG4Particle
*, SvtxTrack * > _cache_best_track_from_particle
std::map< PHG4Hit *, std::set
< SvtxTrack * > > _cache_all_tracks_from_g4hit
std::map< TrkrDefs::cluskey,
std::set< SvtxTrack * > > _cache_all_tracks_from_cluster
std::map< TrkrDefs::cluskey,
SvtxTrack * > _cache_best_track_from_cluster
std::map< std::pair< SvtxTrack
*, PHG4Particle * >, unsigned
int > _cache_get_nclusters_contribution
std::map< std::pair< SvtxTrack
*, PHG4Particle * >, unsigned
int > _cache_get_nclusters_contribution_by_layer
std::map< std::pair< SvtxTrack
*, PHG4Particle * >, unsigned
int > _cache_get_nwrongclusters_contribution
std::string m_TrackNodeName = "SvtxTrackMap"
Detailed Description
Definition at line 26 of file SvtxTrackEval.h.
View newest version in sPHENIX GitHub at line 26 of file SvtxTrackEval.h
Constructor & Destructor Documentation
SvtxTrackEval::SvtxTrackEval (PHCompositeNode * topNode)
Definition at line 25 of file SvtxTrackEval.cc.
View newest version in sPHENIX GitHub at line 25 of file SvtxTrackEval.cc
References get_node_pointers().
SvtxTrackEval::~SvtxTrackEval () virtual
Definition at line 31 of file SvtxTrackEval.cc.
View newest version in sPHENIX GitHub at line 31 of file SvtxTrackEval.cc
References _errors, and _verbosity.
Member Function Documentation
std::set< SvtxTrack * > SvtxTrackEval::all_tracks_from (PHG4Particle * truthparticle)
Definition at line 276 of file SvtxTrackEval.cc.
View newest version in sPHENIX GitHub at line 276 of file SvtxTrackEval.cc
References _cache_all_tracks_from_particle, _clustereval, _do_cache, _errors, _strict, _trackmap, _truthRecoMap, SvtxClusterEval::all_truth_particles(), assert, SvtxTrackMap::get(), PHG4ParticleSvtxMap::get(), get_track_ckeys(), PHG4Particle::get_track_id(), get_truth_eval(), has_node_pointers(), particles, PHG4ParticleSvtxMap::processed(), and tracks().
Referenced by best_track_from(), SvtxTruthRecoTableEval::fillTruthMap(), SvtxEvaluatorHaiwang::printOutputInfo(), psTOFTimezeroEval::printOutputInfo(), SvtxEvaluator::printOutputInfo(), TrackClusterEvaluator::processRecoTracks(), and TrackClusterEvaluator::processTruthTracks().
std::set< SvtxTrack * > SvtxTrackEval::all_tracks_from (PHG4Hit * truthhit)
Definition at line 359 of file SvtxTrackEval.cc.
View newest version in sPHENIX GitHub at line 359 of file SvtxTrackEval.cc
References _cache_all_tracks_from_g4hit, _clustereval, _do_cache, _errors, _strict, _trackmap, SvtxClusterEval::all_truth_hits(), assert, get_track_ckeys(), PHG4Hit::get_trkid(), has_node_pointers(), and tracks().
std::set< SvtxTrack * > SvtxTrackEval::all_tracks_from (TrkrDefs::cluskey cluster_key)
Definition at line 540 of file SvtxTrackEval.cc.
View newest version in sPHENIX GitHub at line 540 of file SvtxTrackEval.cc
References _cache_all_tracks_from_cluster, _cache_track_from_cluster_exists, _do_cache, _errors, _trackmap, create_cache_track_from_cluster(), get_track_ckeys(), has_node_pointers(), and tracks().
std::set< PHG4Hit * > SvtxTrackEval::all_truth_hits (SvtxTrack * track)
Definition at line 60 of file SvtxTrackEval.cc.
View newest version in sPHENIX GitHub at line 60 of file SvtxTrackEval.cc
References _cache_all_truth_hits, _clustereval, _do_cache, _errors, _strict, SvtxClusterEval::all_truth_hits(), assert, get_track_ckeys(), and has_node_pointers().
Referenced by JetRecoEval::all_truth_hits().
std::set< PHG4Particle * > SvtxTrackEval::all_truth_particles (SvtxTrack * track)
Definition at line 119 of file SvtxTrackEval.cc.
View newest version in sPHENIX GitHub at line 119 of file SvtxTrackEval.cc
References _cache_all_truth_particles, _clustereval, _do_cache, _errors, _recoTruthMap, _strict, _truthinfo, SvtxClusterEval::all_truth_particles(), assert, SvtxPHG4ParticleMap::get(), SvtxTrack::get_id(), get_track_ckeys(), get_truth_eval(), SvtxTrack_FastSim::get_truth_track_id(), PHG4TruthInfoContainer::GetParticle(), has_node_pointers(), and SvtxPHG4ParticleMap::processed().
Referenced by JetRecoEval::all_truth_particles(), SvtxTruthRecoTableEval::fillRecoMap(), max_truth_particle_by_nclusters(), and TrackClusterEvaluator::processRecoTracks().
SvtxTrack * SvtxTrackEval::best_track_from (PHG4Particle * truthparticle)
No reco tracks found
Definition at line 428 of file SvtxTrackEval.cc.
View newest version in sPHENIX GitHub at line 428 of file SvtxTrackEval.cc
References _cache_best_track_from_particle, _do_cache, _errors, _strict, _trackmap, _truthRecoMap, all_tracks_from(), assert, test_fpe::count, SvtxTrackMap::get(), PHG4ParticleSvtxMap::get(), get_nclusters_contribution(), PHG4Particle::get_track_id(), has_node_pointers(), PHG4ParticleSvtxMap::processed(), and tracks().
Referenced by EMCalCalib::eval_photon(), EMCalAna::eval_trk(), AnaSvtxTracksForGenFit::fill_tree(), psTOFTimezeroEval::fillOutputNtuples(), SvtxEvaluatorHaiwang::fillOutputNtuples(), SvtxEvaluator::fillOutputNtuples(), Conversion::get_cluster_id(), SvtxSimPerformanceCheckReco::process_event(), TrackingPerformanceCheck::process_event(), QAG4SimulationUpsilon::process_event(), SimpleTrackingAnalysis::process_event(), STACalorimeterCharacterization::process_event(), QAG4SimulationTracking::process_event(), VtxTest::process_event(), TruthConversionEval::process_event(), QAG4SimulationCalorimeterSum::process_event_TrackProj(), TrackClusterEvaluator::processRecoTracks(), TrackClusterEvaluator::processTruthTracks(), and Conversion::setRecoTracks().
SvtxTrack * SvtxTrackEval::best_track_from (TrkrDefs::cluskey cluster_key)
Definition at line 612 of file SvtxTrackEval.cc.
View newest version in sPHENIX GitHub at line 612 of file SvtxTrackEval.cc
References _cache_best_track_from_cluster, _do_cache, _errors, all_tracks_from(), has_node_pointers(), and tracks().
void SvtxTrackEval::calc_cluster_contribution (SvtxTrack * svtxtrack, PHG4Particle * truthparticle)
Definition at line 724 of file SvtxTrackEval.cc.
View newest version in sPHENIX GitHub at line 724 of file SvtxTrackEval.cc
References _cache_get_nclusters_contribution, _cache_get_nwrongclusters_contribution, _clustereval, _errors, _strict, SvtxClusterEval::all_truth_particles(), assert, get_track_ckeys(), get_truth_eval(), has_node_pointers(), and particles.
Referenced by get_nclusters_contribution(), and get_nwrongclusters_contribution().
void SvtxTrackEval::create_cache_track_from_cluster ()
Definition at line 492 of file SvtxTrackEval.cc.
View newest version in sPHENIX GitHub at line 492 of file SvtxTrackEval.cc
References _cache_all_tracks_from_cluster, _cache_track_from_cluster_exists, _errors, _trackmap, get_track_ckeys(), has_node_pointers(), and tracks().
Referenced by all_tracks_from().
void SvtxTrackEval::do_caching (bool do_cache) inline
Definition at line 33 of file SvtxTrackEval.h.
View newest version in sPHENIX GitHub at line 33 of file SvtxTrackEval.h
References _clustereval, _do_cache, and SvtxClusterEval::do_caching().
Referenced by SvtxVertexEval::do_caching().
SvtxClusterEval* SvtxTrackEval::get_cluster_eval () inline
Definition at line 50 of file SvtxTrackEval.h.
View newest version in sPHENIX GitHub at line 50 of file SvtxTrackEval.h
References _clustereval.
Referenced by SvtxVertexEval::get_cluster_eval().
unsigned int SvtxTrackEval::get_errors () inline
Definition at line 75 of file SvtxTrackEval.h.
View newest version in sPHENIX GitHub at line 75 of file SvtxTrackEval.h
References _clustereval, _errors, and SvtxClusterEval::get_errors().
Referenced by SvtxVertexEval::get_errors().
SvtxHitEval* SvtxTrackEval::get_hit_eval () inline
Definition at line 51 of file SvtxTrackEval.h.
View newest version in sPHENIX GitHub at line 51 of file SvtxTrackEval.h
References _clustereval, and SvtxClusterEval::get_hit_eval().
Referenced by SvtxVertexEval::get_hit_eval().
std::pair< unsigned int, unsigned int > SvtxTrackEval::get_layer_range_contribution (SvtxTrack * track, PHG4Particle * particle, unsigned int start_layer, unsigned int end_layer)
Definition at line 870 of file SvtxTrackEval.cc.
View newest version in sPHENIX GitHub at line 870 of file SvtxTrackEval.cc
References _clustereval, _errors, _strict, SvtxClusterEval::all_truth_particles(), assert, get_track_ckeys(), get_truth_eval(), TrkrDefs::getLayer(), has_node_pointers(), i, nlayers, and particles.
Referenced by SvtxEvaluator::fillOutputNtuples().
unsigned int SvtxTrackEval::get_nclusters_contribution (SvtxTrack * svtxtrack, PHG4Particle * truthparticle)
Definition at line 662 of file SvtxTrackEval.cc.
View newest version in sPHENIX GitHub at line 662 of file SvtxTrackEval.cc
References _cache_get_nclusters_contribution, _errors, _strict, assert, calc_cluster_contribution(), and has_node_pointers().
Referenced by best_track_from(), EMCalCalib::eval_photon(), EMCalAna::eval_trk(), psTOFTimezeroEval::fillOutputNtuples(), SvtxEvaluatorHaiwang::fillOutputNtuples(), SvtxEvaluator::fillOutputNtuples(), SvtxTruthRecoTableEval::fillRecoMap(), SvtxTruthRecoTableEval::fillTruthMap(), max_truth_particle_by_nclusters(), psTOFTimezeroEval::printOutputInfo(), SvtxEvaluatorHaiwang::printOutputInfo(), SvtxEvaluator::printOutputInfo(), SvtxSimPerformanceCheckReco::process_event(), TrackingPerformanceCheck::process_event(), SimpleTrackingAnalysis::process_event(), and BJetModule::process_event().
unsigned int SvtxTrackEval::get_nclusters_contribution_by_layer (SvtxTrack * svtxtrack, PHG4Particle * truthparticle)
Definition at line 792 of file SvtxTrackEval.cc.
View newest version in sPHENIX GitHub at line 792 of file SvtxTrackEval.cc
References _cache_get_nclusters_contribution_by_layer, _clustereval, _do_cache, _errors, _strict, SvtxClusterEval::all_truth_particles(), assert, get_track_ckeys(), get_truth_eval(), TrkrDefs::getLayer(), has_node_pointers(), i, and particles.
Referenced by psTOFTimezeroEval::fillOutputNtuples(), SvtxEvaluatorHaiwang::fillOutputNtuples(), SvtxEvaluator::fillOutputNtuples(), SvtxSimPerformanceCheckReco::process_event(), and BJetModule::process_event().
void SvtxTrackEval::get_node_pointers (PHCompositeNode * topNode) private
Definition at line 957 of file SvtxTrackEval.cc.
View newest version in sPHENIX GitHub at line 957 of file SvtxTrackEval.cc
References _recoTruthMap, _trackmap, _truthinfo, _truthRecoMap, and m_TrackNodeName.
Referenced by next_event(), and SvtxTrackEval().
unsigned int SvtxTrackEval::get_nwrongclusters_contribution (SvtxTrack * svtxtrack, PHG4Particle * truthparticle)
Definition at line 692 of file SvtxTrackEval.cc.
View newest version in sPHENIX GitHub at line 692 of file SvtxTrackEval.cc
References _cache_get_nwrongclusters_contribution, _errors, _strict, assert, calc_cluster_contribution(), and has_node_pointers().
Referenced by SvtxEvaluator::fillOutputNtuples().
std::vector< TrkrDefs::cluskey > SvtxTrackEval::get_track_ckeys (SvtxTrack * track) private
Definition at line 985 of file SvtxTrackEval.cc.
View newest version in sPHENIX GitHub at line 985 of file SvtxTrackEval.cc
References TrackSeed::begin_cluster_keys(), TrackSeed::end_cluster_keys(), SvtxTrack::get_silicon_seed(), and SvtxTrack::get_tpc_seed().
Referenced by all_tracks_from(), all_truth_hits(), all_truth_particles(), calc_cluster_contribution(), create_cache_track_from_cluster(), get_layer_range_contribution(), and get_nclusters_contribution_by_layer().
SvtxTruthEval* SvtxTrackEval::get_truth_eval () inline
Definition at line 52 of file SvtxTrackEval.h.
View newest version in sPHENIX GitHub at line 52 of file SvtxTrackEval.h
References _clustereval, and SvtxClusterEval::get_truth_eval().
Referenced by all_tracks_from(), all_truth_particles(), calc_cluster_contribution(), get_layer_range_contribution(), get_nclusters_contribution_by_layer(), SvtxVertexEval::get_truth_eval(), and max_truth_particle_by_nclusters().
bool SvtxTrackEval::has_node_pointers () private
Definition at line 971 of file SvtxTrackEval.cc.
View newest version in sPHENIX GitHub at line 971 of file SvtxTrackEval.cc
References _strict, _trackmap, and assert.
Referenced by all_tracks_from(), all_truth_hits(), all_truth_particles(), best_track_from(), calc_cluster_contribution(), create_cache_track_from_cluster(), get_layer_range_contribution(), get_nclusters_contribution(), get_nclusters_contribution_by_layer(), get_nwrongclusters_contribution(), and max_truth_particle_by_nclusters().
PHG4Particle * SvtxTrackEval::max_truth_particle_by_nclusters (SvtxTrack * track)
Definition at line 202 of file SvtxTrackEval.cc.
View newest version in sPHENIX GitHub at line 202 of file SvtxTrackEval.cc
References _cache_max_truth_particle_by_nclusters, _do_cache, _errors, _recoTruthMap, _strict, _truthinfo, all_truth_particles(), assert, SvtxPHG4ParticleMap::get(), SvtxTrack::get_id(), get_nclusters_contribution(), SvtxTruthEval::get_particle(), get_truth_eval(), SvtxTrack_FastSim::get_truth_track_id(), PHG4TruthInfoContainer::GetParticle(), has_node_pointers(), particles, and SvtxPHG4ParticleMap::processed().
Referenced by LeptoquarksReco::AddTrackInformation(), SvtxVertexEval::all_truth_particles(), ActsEvaluator::evaluateTrackFit(), GenFitTrackProp::fill_tree(), SvtxEvaluatorHaiwang::fillOutputNtuples(), psTOFTimezeroEval::fillOutputNtuples(), SvtxEvaluator::fillOutputNtuples(), BuildResonanceJetTaggingTree::findMatchedTruthD0(), JetRecoEval::get_energy_contribution(), SvtxVertexEval::get_ntracks_contribution(), PhotonJet::GetRecoHadronsAndJets(), AnaTutorial::getTracks(), IsolatedTrackAnalysis::getTracks(), KFParticle_truthAndDetTools::getTruthTrack(), SvtxSimPerformanceCheckReco::process_event(), TrackingPerformanceCheck::process_event(), SimpleTrackingAnalysis::process_event(), BJetModule::process_event(), QAG4SimulationTracking::process_event(), PhotonJet::process_event(), and TrackClusterEvaluator::processRecoTracks().
void SvtxTrackEval::next_event (PHCompositeNode * topNode)
Definition at line 42 of file SvtxTrackEval.cc.
View newest version in sPHENIX GitHub at line 42 of file SvtxTrackEval.cc
References _cache_all_tracks_from_cluster, _cache_all_tracks_from_g4hit, _cache_all_tracks_from_particle, _cache_all_truth_hits, _cache_all_truth_particles, _cache_best_track_from_cluster, _cache_best_track_from_particle, _cache_get_nclusters_contribution, _cache_get_nclusters_contribution_by_layer, _cache_get_nwrongclusters_contribution, _cache_max_truth_particle_by_nclusters, _clustereval, get_node_pointers(), and SvtxClusterEval::next_event().
Referenced by SvtxVertexEval::next_event().
void SvtxTrackEval::set_strict (bool strict) inline
Definition at line 38 of file SvtxTrackEval.h.
View newest version in sPHENIX GitHub at line 38 of file SvtxTrackEval.h
References _clustereval, _strict, and SvtxClusterEval::set_strict().
Referenced by SvtxVertexEval::set_strict().
void SvtxTrackEval::set_track_nodename (const std::string & name) inline
Definition at line 77 of file SvtxTrackEval.h.
View newest version in sPHENIX GitHub at line 77 of file SvtxTrackEval.h
References m_TrackNodeName, and perf_headwind::name.
Referenced by SvtxVertexEval::set_track_nodename().
void SvtxTrackEval::set_verbosity (int verbosity) inline
Definition at line 43 of file SvtxTrackEval.h.
View newest version in sPHENIX GitHub at line 43 of file SvtxTrackEval.h
References _clustereval, _verbosity, SvtxClusterEval::set_verbosity(), and verbosity.
Referenced by SvtxTruthRecoTableEval::fillTruthMap(), and SvtxVertexEval::set_verbosity().
Member Data Documentation
std::map<TrkrDefs::cluskey, std::set<SvtxTrack*> > SvtxTrackEval::_cache_all_tracks_from_cluster private
Definition at line 103 of file SvtxTrackEval.h.
View newest version in sPHENIX GitHub at line 103 of file SvtxTrackEval.h
Referenced by all_tracks_from(), create_cache_track_from_cluster(), and next_event().
std::map<PHG4Hit*, std::set<SvtxTrack*> > SvtxTrackEval::_cache_all_tracks_from_g4hit private
Definition at line 102 of file SvtxTrackEval.h.
View newest version in sPHENIX GitHub at line 102 of file SvtxTrackEval.h
Referenced by all_tracks_from(), and next_event().
std::map<PHG4Particle*, std::set<SvtxTrack*> > SvtxTrackEval::_cache_all_tracks_from_particle private
Definition at line 100 of file SvtxTrackEval.h.
View newest version in sPHENIX GitHub at line 100 of file SvtxTrackEval.h
Referenced by all_tracks_from(), and next_event().
std::map<SvtxTrack*, std::set<PHG4Hit*> > SvtxTrackEval::_cache_all_truth_hits private
Definition at line 97 of file SvtxTrackEval.h.
View newest version in sPHENIX GitHub at line 97 of file SvtxTrackEval.h
Referenced by all_truth_hits(), and next_event().
std::map<SvtxTrack*, std::set<PHG4Particle*> > SvtxTrackEval::_cache_all_truth_particles private
Definition at line 98 of file SvtxTrackEval.h.
View newest version in sPHENIX GitHub at line 98 of file SvtxTrackEval.h
Referenced by all_truth_particles(), and next_event().
std::map<TrkrDefs::cluskey, SvtxTrack*> SvtxTrackEval::_cache_best_track_from_cluster private
Definition at line 104 of file SvtxTrackEval.h.
View newest version in sPHENIX GitHub at line 104 of file SvtxTrackEval.h
Referenced by best_track_from(), and next_event().
std::map<PHG4Particle*, SvtxTrack*> SvtxTrackEval::_cache_best_track_from_particle private
Definition at line 101 of file SvtxTrackEval.h.
View newest version in sPHENIX GitHub at line 101 of file SvtxTrackEval.h
Referenced by best_track_from(), and next_event().
std::map<std::pair<SvtxTrack*, PHG4Particle*>, unsigned int> SvtxTrackEval::_cache_get_nclusters_contribution private
Definition at line 105 of file SvtxTrackEval.h.
View newest version in sPHENIX GitHub at line 105 of file SvtxTrackEval.h
Referenced by calc_cluster_contribution(), get_nclusters_contribution(), and next_event().
std::map<std::pair<SvtxTrack*, PHG4Particle*>, unsigned int> SvtxTrackEval::_cache_get_nclusters_contribution_by_layer private
Definition at line 106 of file SvtxTrackEval.h.
View newest version in sPHENIX GitHub at line 106 of file SvtxTrackEval.h
Referenced by get_nclusters_contribution_by_layer(), and next_event().
std::map<std::pair<SvtxTrack*, PHG4Particle*>, unsigned int> SvtxTrackEval::_cache_get_nwrongclusters_contribution private
Definition at line 107 of file SvtxTrackEval.h.
View newest version in sPHENIX GitHub at line 107 of file SvtxTrackEval.h
Referenced by calc_cluster_contribution(), get_nwrongclusters_contribution(), and next_event().
std::map<SvtxTrack*, PHG4Particle*> SvtxTrackEval::_cache_max_truth_particle_by_nclusters private
Definition at line 99 of file SvtxTrackEval.h.
View newest version in sPHENIX GitHub at line 99 of file SvtxTrackEval.h
Referenced by max_truth_particle_by_nclusters(), and next_event().
bool SvtxTrackEval::_cache_track_from_cluster_exists = false private
Definition at line 96 of file SvtxTrackEval.h.
View newest version in sPHENIX GitHub at line 96 of file SvtxTrackEval.h
Referenced by all_tracks_from(), and create_cache_track_from_cluster().
SvtxClusterEval SvtxTrackEval::_clustereval private
Definition at line 85 of file SvtxTrackEval.h.
View newest version in sPHENIX GitHub at line 85 of file SvtxTrackEval.h
Referenced by all_tracks_from(), all_truth_hits(), all_truth_particles(), calc_cluster_contribution(), do_caching(), get_cluster_eval(), get_errors(), get_hit_eval(), get_layer_range_contribution(), get_nclusters_contribution_by_layer(), get_truth_eval(), next_event(), set_strict(), and set_verbosity().
bool SvtxTrackEval::_do_cache = true private
Definition at line 95 of file SvtxTrackEval.h.
View newest version in sPHENIX GitHub at line 95 of file SvtxTrackEval.h
Referenced by all_tracks_from(), all_truth_hits(), all_truth_particles(), best_track_from(), do_caching(), get_nclusters_contribution_by_layer(), and max_truth_particle_by_nclusters().
unsigned int SvtxTrackEval::_errors = 0 private
Definition at line 93 of file SvtxTrackEval.h.
View newest version in sPHENIX GitHub at line 93 of file SvtxTrackEval.h
Referenced by all_tracks_from(), all_truth_hits(), all_truth_particles(), best_track_from(), calc_cluster_contribution(), create_cache_track_from_cluster(), get_errors(), get_layer_range_contribution(), get_nclusters_contribution(), get_nclusters_contribution_by_layer(), get_nwrongclusters_contribution(), max_truth_particle_by_nclusters(), and ~SvtxTrackEval().
const SvtxPHG4ParticleMap* SvtxTrackEval::_recoTruthMap = nullptr private
Definition at line 89 of file SvtxTrackEval.h.
View newest version in sPHENIX GitHub at line 89 of file SvtxTrackEval.h
Referenced by all_truth_particles(), get_node_pointers(), and max_truth_particle_by_nclusters().
bool SvtxTrackEval::_strict = false private
Definition at line 91 of file SvtxTrackEval.h.
View newest version in sPHENIX GitHub at line 91 of file SvtxTrackEval.h
Referenced by all_tracks_from(), all_truth_hits(), all_truth_particles(), best_track_from(), calc_cluster_contribution(), get_layer_range_contribution(), get_nclusters_contribution(), get_nclusters_contribution_by_layer(), get_nwrongclusters_contribution(), has_node_pointers(), max_truth_particle_by_nclusters(), and set_strict().
SvtxTrackMap* SvtxTrackEval::_trackmap = nullptr private
Definition at line 86 of file SvtxTrackEval.h.
View newest version in sPHENIX GitHub at line 86 of file SvtxTrackEval.h
Referenced by all_tracks_from(), best_track_from(), create_cache_track_from_cluster(), get_node_pointers(), and has_node_pointers().
PHG4TruthInfoContainer* SvtxTrackEval::_truthinfo = nullptr private
Definition at line 87 of file SvtxTrackEval.h.
View newest version in sPHENIX GitHub at line 87 of file SvtxTrackEval.h
Referenced by all_truth_particles(), get_node_pointers(), and max_truth_particle_by_nclusters().
const PHG4ParticleSvtxMap* SvtxTrackEval::_truthRecoMap = nullptr private
Definition at line 88 of file SvtxTrackEval.h.
View newest version in sPHENIX GitHub at line 88 of file SvtxTrackEval.h
Referenced by all_tracks_from(), best_track_from(), and get_node_pointers().
int SvtxTrackEval::_verbosity = 0 private
Definition at line 92 of file SvtxTrackEval.h.
View newest version in sPHENIX GitHub at line 92 of file SvtxTrackEval.h
Referenced by set_verbosity(), and ~SvtxTrackEval().
std::string SvtxTrackEval::m_TrackNodeName = "SvtxTrackMap" private
Definition at line 108 of file SvtxTrackEval.h.
View newest version in sPHENIX GitHub at line 108 of file SvtxTrackEval.h
Referenced by get_node_pointers(), and set_track_nodename().
The documentation for this class was generated from the following files:
coresoftware/blob/master/simulation/g4simulation/g4eval/SvtxTrackEval.h
coresoftware/blob/master/simulation/g4simulation/g4eval/SvtxTrackEval.cc