Analysis Software: PHNodeIterator Class Reference
PHNodeIterator Class Reference
#include <coresoftware/blob/master/offline/framework/phool/PHNodeIterator.h>
Public Member Functions
PHNodeIterator (PHCompositeNode *)
virtual ~PHNodeIterator ()
PHNodeIterator ()
void print ()
PHPointerList< PHNode > & ls ()
PHNode * findFirst (const std::string &, const std::string &)
PHNode * findFirst (const std::string &)
bool cd (const std::string &pathString="")
bool addNode (PHNode *)
void forEach (PHNodeOperation &)
void for_each (PHNodeOperation &)
PHCompositeNode * get_currentNode () const
Protected Attributes
PHCompositeNode * currentNode
PHPointerList< PHNode > subNodeList
Detailed Description
Definition at line 17 of file PHNodeIterator.h.
View newest version in sPHENIX GitHub at line 17 of file PHNodeIterator.h
Constructor & Destructor Documentation
PHNodeIterator::PHNodeIterator (PHCompositeNode * node) explicit
Definition at line 25 of file PHNodeIterator.cc.
View newest version in sPHENIX GitHub at line 25 of file PHNodeIterator.cc
virtual PHNodeIterator::~PHNodeIterator () inline virtual
Definition at line 21 of file PHNodeIterator.h.
View newest version in sPHENIX GitHub at line 21 of file PHNodeIterator.h
PHNodeIterator::PHNodeIterator ()
Definition at line 30 of file PHNodeIterator.cc.
View newest version in sPHENIX GitHub at line 30 of file PHNodeIterator.cc
Member Function Documentation
bool PHNodeIterator::addNode (PHNode * newNode)
Definition at line 157 of file PHNodeIterator.cc.
View newest version in sPHENIX GitHub at line 157 of file PHNodeIterator.cc
References PHCompositeNode::addNode(), and currentNode.
Referenced by PHDataNodeIterator::AddIODataNode(), and PHNodeIOManager::reconstructNodeTree().
bool PHNodeIterator::cd (const std::string & pathString = "")
Definition at line 104 of file PHNodeIterator.cc.
View newest version in sPHENIX GitHub at line 104 of file PHNodeIterator.cc
References currentNode, PHNode::getName(), PHNode::getParent(), PHNode::getType(), i, phooldefs::nodetreepathdelim, and PHCompositeNode::subNodes.
Referenced by Dumper::End(), Dumper::process_event(), PHNodeIOManager::reconstructNodeTree(), and Fun4AllServer::ResetNodeTree().
PHNode * PHNodeIterator::findFirst (const std::string & requiredType, const std::string & requiredName)
Definition at line 54 of file PHNodeIterator.cc.
View newest version in sPHENIX GitHub at line 54 of file PHNodeIterator.cc
References currentNode, findFirst(), PHNode::getName(), PHNode::getType(), and PHCompositeNode::subNodes.
Referenced by PHG4TpcDetector::add_geometry_node(), PHG4MicromegasDetector::add_geometry_node(), PHG4SpacalDetector::AddCellGeometryNode(), PHG4OHCalDetector::AddGeometryNode(), PHG4EICMvtxDetector::AddGeometryNode(), PHG4IHCalDetector::AddGeometryNode(), PHG4MvtxDetector::AddGeometryNode(), PHG4InttDetector::AddGeometryNode(), PHG4OuterHcalDetector::AddGeometryNode(), PHG4InnerHcalDetector::AddGeometryNode(), PHG4SpacalDetector::AddTowerGeometryNode(), PHG4HcalDetector::ConstructMe(), PHG4SpacalPrototype4Detector::ConstructMe(), PHG4SpacalPrototypeDetector::ConstructMe(), PHG4SpacalDetector::ConstructMe(), PHFlowJetMaker::create_node_tree(), PHPythia8::create_node_tree(), PHHepMCGenHelper::create_node_tree(), AlignmentTransformation::createAlignmentTransformContainer(), DecayFinder::createDecayNode(), SingleGl1PoolInput::CreateDSTNode(), SingleMicromegasPoolInput::CreateDSTNode(), SingleTpcPoolInput::CreateDSTNode(), SingleInttPoolInput::CreateDSTNode(), SingleMvtxPoolInput::CreateDSTNode(), CaloGeomMapping::CreateGeomNode(), ResonanceJetTagging::createJetNode(), SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::CreateJetNode(), TreeMaker::CreateNode(), SubtractTowersCS::CreateNode(), SubtractTowers::CreateNode(), RetowerCEMC::CreateNode(), CaloTriggerSim::CreateNode(), PHG4CentralityReco::CreateNode(), CopyAndSubtractJets::CreateNode(), DetermineTowerBackground::CreateNode(), ParticleFlowReco::CreateNode(), SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::CreateNode(), JetMultSub::CreateNode(), CentralityReco::CreateNodes(), RawClusterBuilderGraph::CreateNodes(), MinimumBiasClassifier::CreateNodes(), TrackingIterationCounter::createNodes(), MbdReco::createNodes(), RawTowerDeadTowerInterp::CreateNodes(), SvtxTruthRecoTableEval::createNodes(), MbdVertexFastSimReco::CreateNodes(), FastPid_RICH::CreateNodes(), InttVertexFinder::createNodes(), GlobalVertexFastSimReco::CreateNodes(), PHTrackClusterAssociator::createNodes(), PHCosmicSeeder::createNodes(), PHActsKDTreeSeeding::createNodes(), RICHParticleID::CreateNodes(), GlobalVertexReco::CreateNodes(), PHSimpleVertexFinder::CreateNodes(), PHInitVertexing::CreateNodes(), PHActsVertexFitter::createNodes(), MbdDigitization::CreateNodes(), PHActsToSvtxTracks::createNodes(), EventPlaneReco::CreateNodes(), PHActsVertexFinder::createNodes(), FillTruthRecoMatchMap::createNodes(), RawClusterBuilderTemplate::CreateNodes(), PHTrackSetMerging::CreateNodes(), PHG4EPDModuleReco::CreateNodes(), RawTowerBuilder::CreateNodes(), RawTowerBuilderByHitIndex::CreateNodes(), PHTrackSeeding::CreateNodes(), PHActsInitialVertexFinder::createNodes(), JetHepMCLoader::CreateNodes(), PHTruthTrackSeeding::CreateNodes(), RawClusterBuilderTopo::CreateNodes(), FillTruthRecoMatchTree::createNodes(), HcalRawTowerBuilder::CreateNodes(), HelicalFitter::CreateNodes(), PHCosmicsTrkFitter::createNodes(), PHActsSiliconSeeding::createNodes(), PHRaveVertexing::CreateNodes(), TpcPrototypeGenFitTrkFinder::CreateNodes(), PHActsTrkFitter::createNodes(), RawTowerCombiner::CreateNodes(), RawTowerCalibration::CreateNodes(), MakeActsGeometry::createNodes(), PHG4TrackFastSim::CreateNodes(), RawTowerDigitizer::CreateNodes(), TpcPrototypeGenFitTrkFitter::CreateNodes(), PHGenFitTrkFitter::CreateNodes(), EventInfoSummary::CreateNodeTree(), RunInfoUnpackPRDF::CreateNodeTree(), SyncReco::CreateNodeTree(), TempInfoUnpackPRDF::CreateNodeTree(), GenericUnpackPRDF::CreateNodeTree(), CaloUnpackPRDF::CreateNodeTree(), RawClusterPositionCorrection::CreateNodeTree(), CaloCalibration::CreateNodeTree(), Emcal_Tower_Masking::CreateNodeTree(), CaloTowerBuilder::CreateNodeTree(), CaloTowerCalib::CreateNodeTree(), MvtxRunInfoUnpackPRDF::CreateNodeTree(), SaveTowerInfo::CreateNodeTree(), CaloTemplateFit::CreateNodeTree(), MvtxPrototype2UnpackPRDF::CreateNodeTree(), PHG4InnerHcalSteppingAction::CreateNodeTree(), caloTowerEmbed::CreateNodeTree(), PHG4OuterHcalSteppingAction::CreateNodeTree(), PHG4IHCalSteppingAction::CreateNodeTree(), MvtxUnpackPRDF::CreateNodeTree(), RawClusterDeadHotMask::CreateNodeTree(), ReadEICFiles::CreateNodeTree(), PHG4OHCalSteppingAction::CreateNodeTree(), CaloWaveformSim::CreateNodeTree(), SecondaryVertexFinder::CreateOutputNode(), KFParticle_DST::createParticleNode(), PHSiliconHelicalPropagator::createSeedContainer(), PHCosmicSiliconPropagator::createSeedContainer(), CDBInterface::End(), Fun4AllServer::End(), KFParticle_nTuple::fillBranch(), KFParticle_truthAndDetTools::fillCaloBranch(), KFParticle_truthAndDetTools::fillDetectorBranch(), EventEvaluator::fillOutputNtuples(), KFParticle_truthAndDetTools::fillTruthBranch(), findFirst(), PHDataNodeIterator::FindIODataNode(), Fun4AllPrdfInputManager::Fun4AllPrdfInputManager(), Fun4AllPrdfInputPoolManager::Fun4AllPrdfInputPoolManager(), JetBkgdSub::GetCentInfo(), findNode::getClass(), PHFieldUtility::GetFieldConfigNode(), PHFieldUtility::GetFieldMapNode(), PHGeomUtility::GetGeomIOTGeoNode(), PHGeomUtility::GetGeomTGeoNode(), KFParticle_truthAndDetTools::getHepMCInfo(), truthDecayTester::getMotherPDG(), QAG4SimulationTruthDecay::getMotherPDG(), Fun4AllServer::getNode(), TrackSeedTrackMapConverter::getNodes(), PHTpcClusterMover::GetNodes(), PHTrackSelector::GetNodes(), PHTruthClustering::GetNodes(), PHSiliconTpcTrackMatching::GetNodes(), PHTruthSiliconAssociation::GetNodes(), PHTpcCentralMembraneClusterizer::GetNodes(), PHTpcCentralMembraneMatcher::GetNodes(), ElectronID::GetNodes(), PHG4GDMLUtility::GetOrMakeConfigNode(), KFParticle_truthAndDetTools::getTruthTrack(), MakeSimpleTree::Init(), HeadReco::Init(), PHG4HeadReco::Init(), G4RawTowerTTree::Init(), G4ScintillatorTowerTTree::Init(), G4ScintillatorSlatTTree::Init(), HepMCCompress::Init(), G4HitTTree::Init(), EventCombiner::Init(), HepMCNodeReader::Init(), PairMaker::Init(), FilterEvents::Init(), FilterEventsUpsilon::Init(), PHG4SectorSubsystem::Init(), PHG4EnvelopeSubsystem::Init(), PHG4CEmcTestBeamSubsystem::Init(), PJTranslator::Init(), G4Example01Subsystem::Init(), PHG4HcalPrototypeSubsystem::Init(), ElectronID::Init(), TrackEvaluation::Init(), DSTEmulator::Init(), HFTrackEfficiency::Init(), Fun4AllPrdfOutputManager::InitPrdfNode(), PHG4InEventReadBack::InitRun(), PHG4InEventCompress::InitRun(), Prototype2RawTowerBuilder::InitRun(), RawTowerBuilder::InitRun(), InttCombinedRawDataDecoder::InitRun(), TpcPrototypeClusterizer::InitRun(), PHG4Prototype2HcalCellReco::InitRun(), CosmicSpray::InitRun(), FlagHandler::InitRun(), RawTowerDeadTowerInterp::InitRun(), PHG4ParticleGeneratorBase::InitRun(), JetProbeMaker::InitRun(), PHG4HcalCellReco::InitRun(), PHG4EPDModuleReco::InitRun(), HcalRawTowerBuilder::InitRun(), InttRawDataDecoder::InitRun(), PHG4InttDigitizer::InitRun(), PHG4BlockCellReco::InitRun(), RawTowerBuilderByHitIndex::InitRun(), PHG4CylinderCellReco::InitRun(), CaloTowerCalib::InitRun(), RawTowerCalibration::InitRun(), CaloTowerStatus::InitRun(), TpcLoadDistortionCorrection::InitRun(), PHG4DetectorSubsystem::InitRun(), PHG4DetectorGroupSubsystem::InitRun(), PHG4TruthSubsystem::InitRun(), PHG4MvtxDigitizer::InitRun(), MicromegasClusterizer::InitRun(), PHG4TpcDigitizer::InitRun(), PHG4TpcDirectLaser::InitRun(), PHG4TpcPadPlane::InitRun(), PHG4SimpleEventGenerator::InitRun(), MvtxPrototype2Clusterizer::InitRun(), Proto4ShowerCalib::InitRun(), PHG4FullProjSpacalCellReco::InitRun(), PHG4ParticleGeneratorVectorMeson::InitRun(), MicromegasRawDataDecoder::InitRun(), RawTowerDigitizer::InitRun(), InttClusterizer::InitRun(), TpcSimpleClusterizer::InitRun(), PHG4InttDeadMapLoader::InitRun(), TpcCombinedRawDataUnpacker::InitRun(), DeadHotMapLoader::InitRun(), MicromegasCombinedDataDecoder::InitRun(), PHG4TpcPadBaselineShift::InitRun(), TpcRawWriter::InitRun(), HFMLTriggerHepMCTrigger::InitRun(), QAG4SimulationCalorimeter::InitRun(), PHG4MvtxHitReco::InitRun(), PHG4InttHitReco::InitRun(), Proto3ShowerCalib::InitRun(), PHG4MicromegasHitReco::InitRun(), Proto2ShowerCalib::InitRun(), TpcClusterizer::InitRun(), PHG4HcalSubsystem::InitRun(), Proto4TowerCalib::InitRun(), Proto4SampleFrac::InitRun(), MvtxCombinedRawDataDecoder::InitRun(), tpc_hits::InitRun(), ExampleAnalysisModule::InitRun(), EMCalLikelihood::InitRun(), TpcRawDataDecoder::InitRun(), MvtxClusterizer::InitRun(), PHG4TpcElectronDrift::InitRun(), DSTTrackInfoWriter::InitRun(), TpcPrototypeUnpacker::InitRun(), EMCalAna::InitRun(), EMCalCalib::InitRun(), RawTowerCombiner::InitRun(), EMCalCalib_TestBeam::InitRun(), PHG4EPDSubsystem::InitRunSubsystem(), PHG4OHCalSubsystem::InitRunSubsystem(), PHG4OuterHcalSubsystem::InitRunSubsystem(), PHG4ZDCSubsystem::InitRunSubsystem(), PHG4InnerHcalSubsystem::InitRunSubsystem(), PHG4IHCalSubsystem::InitRunSubsystem(), PHG4SpacalPrototype4Subsystem::InitRunSubsystem(), PHG4Prototype3InnerHcalSubsystem::InitRunSubsystem(), PHG4TpcSubsystem::InitRunSubsystem(), PHG4Prototype2OuterHcalSubsystem::InitRunSubsystem(), BeamLineMagnetSubsystem::InitRunSubsystem(), PHG4Prototype2InnerHcalSubsystem::InitRunSubsystem(), PHG4CylinderSubsystem::InitRunSubsystem(), PHG4BlockSubsystem::InitRunSubsystem(), PHG4SpacalPrototypeSubsystem::InitRunSubsystem(), PHG4ConeSubsystem::InitRunSubsystem(), PHG4MvtxSubsystem::InitRunSubsystem(), PHG4EICMvtxSubsystem::InitRunSubsystem(), PHG4InttSubsystem::InitRunSubsystem(), PHG4TpcEndCapSubsystem::InitRunSubsystem(), G4Example02Subsystem::InitRunSubsystem(), PHG4MicromegasSubsystem::InitRunSubsystem(), G4Example03Subsystem::InitRunSubsystem(), PHG4SpacalSubsystem::InitRunSubsystem(), PHG4BbcSubsystem::InitRunSubsystem(), PHG4PSTOFSubsystem::InitRunSubsystem(), PHG4SpacalSteppingAction::InitWithNode(), Dumper::process_event(), TpcPrototypeClusterizer::process_event(), EventCombiner::process_event(), TpcSimpleClusterizer::process_event(), PHG4TpcPadBaselineShift::process_event(), TpcRawWriter::process_event(), TpcClusterizer::process_event(), HFTrackEfficiency::process_event(), Fun4AllServer::process_event(), PHNodeIOManager::reconstructNodeTree(), EventCombiner::ResetEvent(), Fun4AllPrdfInputManager::ResetEvent(), Fun4AllPrdfInputPoolManager::ResetEvent(), Fun4AllPrdfInputManager::run(), Fun4AllPrdfInputPoolManager::run(), PHG4Reco::setupInputEventNodeReader(), Fun4AllDstOutputManager::Write(), and Fun4AllDstOutputManager::WriteNode().
PHNode * PHNodeIterator::findFirst (const std::string & requiredName)
Definition at line 78 of file PHNodeIterator.cc.
View newest version in sPHENIX GitHub at line 78 of file PHNodeIterator.cc
References currentNode, findFirst(), PHNode::getName(), PHNode::getType(), and PHCompositeNode::subNodes.
void PHNodeIterator::for_each (PHNodeOperation & operation)
Definition at line 181 of file PHNodeIterator.cc.
View newest version in sPHENIX GitHub at line 181 of file PHNodeIterator.cc
References forEach().
void PHNodeIterator::forEach (PHNodeOperation & operation)
Definition at line 162 of file PHNodeIterator.cc.
View newest version in sPHENIX GitHub at line 162 of file PHNodeIterator.cc
References currentNode, forEach(), PHNode::getType(), and PHCompositeNode::subNodes.
Referenced by Dumper::End(), Fun4AllDstInputManager::fileopen(), Fun4AllSingleDstPileupInputManager::fileopen(), Fun4AllDstPileupInputManager::fileopen(), for_each(), forEach(), Fun4AllDstPileupMerger::load_nodes(), Dumper::process_event(), and Fun4AllServer::ResetNodeTree().
PHCompositeNode* PHNodeIterator::get_currentNode () const inline
Definition at line 33 of file PHNodeIterator.h.
View newest version in sPHENIX GitHub at line 33 of file PHNodeIterator.h
References currentNode.
PHPointerList< PHNode > & PHNodeIterator::ls ()
Definition at line 36 of file PHNodeIterator.cc.
View newest version in sPHENIX GitHub at line 36 of file PHNodeIterator.cc
References PHPointerList< T >::append(), PHPointerList< T >::clear(), currentNode, subNodeList, and PHCompositeNode::subNodes.
Referenced by Fun4AllServer::CountOutNodesRecursive(), Fun4AllServer::MakeNodesPersistent(), Fun4AllServer::MakeNodesTransient(), PHG4DstCompressReco::SearchG4HitNodes(), and PHG4TruthEventAction::SearchNode().
void PHNodeIterator::print ()
Definition at line 48 of file PHNodeIterator.cc.
View newest version in sPHENIX GitHub at line 48 of file PHNodeIterator.cc
References currentNode, and PHCompositeNode::print().
Referenced by Fun4AllServer::Print(), and Fun4AllServer::process_event().
Member Data Documentation
PHCompositeNode* PHNodeIterator::currentNode protected
Definition at line 36 of file PHNodeIterator.h.
View newest version in sPHENIX GitHub at line 36 of file PHNodeIterator.h
Referenced by addNode(), cd(), findFirst(), forEach(), get_currentNode(), ls(), and print().
PHPointerList<PHNode> PHNodeIterator::subNodeList protected
Definition at line 37 of file PHNodeIterator.h.
View newest version in sPHENIX GitHub at line 37 of file PHNodeIterator.h
Referenced by ls().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/framework/phool/PHNodeIterator.h
coresoftware/blob/master/offline/framework/phool/PHNodeIterator.cc