Analysis Software: acts/blob/sPHENIX/Tests/UnitTests/Core/Detector/BlueprintHelperTests.cpp File Reference
BlueprintHelperTests.cpp File Reference
#include <boost/test/unit_test.hpp>
#include "Acts/Detector/Blueprint.hpp"
#include "Acts/Detector/detail/BlueprintHelper.hpp"
#include <exception>
#include <fstream>
Classes
class Acts::Experimental::IInternalStructureBuilder
This is the interface definition of internal structure builders for DetectorVolume construction.
Namespaces
namespace Acts
Acts includes to create all necessary definitions.
namespace Acts::Experimental
Functions
BOOST_AUTO_TEST_CASE (BlueprintHelperSorting)
BOOST_AUTO_TEST_CASE (BlueprintCylindricalGapFilling)
BOOST_AUTO_TEST_CASE (BlueprintCylindricalGapException)
Function Documentation
BOOST_AUTO_TEST_CASE (BlueprintHelperSorting)
Definition at line 25 of file BlueprintHelperTests.cpp.
View newest version in sPHENIX GitHub at line 25 of file BlueprintHelperTests.cpp
References Acts::binR, Acts::binZ, Acts::VolumeBounds::eCylinder, Acts::VolumeBounds::eOther, Acts::UnitConstants::fs, layer, testing::internal::move(), Acts::Experimental::detail::BlueprintHelper::sort(), and physmon_ckf_tracking::u.
BOOST_AUTO_TEST_CASE (BlueprintCylindricalGapFilling)
Definition at line 91 of file BlueprintHelperTests.cpp.
View newest version in sPHENIX GitHub at line 91 of file BlueprintHelperTests.cpp
References Acts::binR, Acts::binZ, Acts::VolumeBounds::eCylinder, Acts::Experimental::detail::BlueprintHelper::fillGaps(), Acts::UnitConstants::fs, testing::internal::move(), and physmon_ckf_tracking::u.
BOOST_AUTO_TEST_CASE (BlueprintCylindricalGapException)
Definition at line 263 of file BlueprintHelperTests.cpp.
View newest version in sPHENIX GitHub at line 263 of file BlueprintHelperTests.cpp
References Acts::binX, Acts::VolumeBounds::eCuboid, Acts::VolumeBounds::eCylinder, Acts::Experimental::detail::BlueprintHelper::fillGaps(), and testing::internal::move().