Analysis Software: kdfinder::TVector< T > Class Template Reference
kdfinder::TVector< T > Class Template Reference
#include <coresoftware/blob/master/offline/packages/PHTpcTracker/externals/kdfinder.hpp>
Public Member Functions
TVector ()
TVector (T x, T y, T z)
TVector (const TVector< T > &v)
TVector (const T *a)
~TVector ()
void setX (T x)
void setY (T y)
void setZ (T z)
void set (T X, T Y, T Z)
void setPhi (T Angle)
void setTheta (T Angle)
void setMag (T Mag)
void setMagnitude (T r)
const T & x () const
const T & y () const
const T & z () const
const T * xyz () const
T * xyz ()
T abs (const TVector< T > &v)
T theta () const
T cosTheta () const
T phi () const
T perp () const
T perp2 () const
T magnitude () const
T mag () const
T mag2 () const
T pseudoRapidity () const
TVector< T > & operator= (const TVector< T > &v)
T operator() (size_t i) const
T operator[] (size_t i) const
T & operator() (size_t i)
T & operator[] (size_t i)
T massHypothesis (T mass) const
TVector< T > unit () const
TVector< T > orthogonal () const
void rotateX (T Angle)
void rotateY (T Angle)
void rotateZ (T Angle)
TVector< T > operator- ()
TVector< T > operator+ ()
TVector< T > & operator*= (T c)
TVector< T > & operator/= (T c)
TVector< T > pseudoProduct (T X, T Y, T Z) const
T angle (const TVector< T > &vec) const
TVector< T > cross (const TVector< T > &v) const
T dot (const TVector< T > &v) const
TVector< T > pseudoProduct (const TVector< T > &v) const
bool operator== (const TVector< T > &v) const
bool operator!= (const TVector< T > &v) const
TVector< T > & operator+= (const TVector< T > &v)
TVector< T > & operator-= (const TVector< T > &v)
int valid (T world=1.e+5) const
int bad (T world=1.e+5) const
Protected Attributes
T mX1
T mX2
T mX3
Detailed Description
template<class T>
class kdfinder::TVector< T >
Definition at line 77 of file kdfinder.hpp.
View newest version in sPHENIX GitHub at line 77 of file kdfinder.hpp
Constructor & Destructor Documentation
template<class T> kdfinder::TVector< T >::TVector () inline
Definition at line 80 of file kdfinder.hpp.
View newest version in sPHENIX GitHub at line 80 of file kdfinder.hpp
template<class T> kdfinder::TVector< T >::TVector (T x, T y, T z) inline
Definition at line 86 of file kdfinder.hpp.
View newest version in sPHENIX GitHub at line 86 of file kdfinder.hpp
template<class T> kdfinder::TVector< T >::TVector (const TVector< T > & v) inline
Definition at line 92 of file kdfinder.hpp.
View newest version in sPHENIX GitHub at line 92 of file kdfinder.hpp
template<class T> kdfinder::TVector< T >::TVector (const T * a) inline
Definition at line 98 of file kdfinder.hpp.
View newest version in sPHENIX GitHub at line 98 of file kdfinder.hpp
template<class T> kdfinder::TVector< T >::~TVector () inline
Definition at line 104 of file kdfinder.hpp.
View newest version in sPHENIX GitHub at line 104 of file kdfinder.hpp
Member Function Documentation
template<class T> T kdfinder::TVector< T >::abs (const TVector< T > & v) inline
Definition at line 155 of file kdfinder.hpp.
View newest version in sPHENIX GitHub at line 155 of file kdfinder.hpp
References kdfinder::TVector< T >::mag().
template<class T> T kdfinder::TVector< T >::angle (const TVector< T > & vec) const inline
Definition at line 317 of file kdfinder.hpp.
View newest version in sPHENIX GitHub at line 317 of file kdfinder.hpp
References kdfinder::TVector< T >::dot(), kdfinder::TVector< T >::mag2(), norm, and Acts::UnitConstants::T.
template<class T> int kdfinder::TVector< T >::bad (T world = 1.e+5) const inline
Definition at line 372 of file kdfinder.hpp.
View newest version in sPHENIX GitHub at line 372 of file kdfinder.hpp
References i, kdfinder::TVector< T >::mX1, and Acts::Test::world.
Referenced by kdfinder::TVector< T >::valid().
template<class T> T kdfinder::TVector< T >::cosTheta () const inline
Definition at line 162 of file kdfinder.hpp.
View newest version in sPHENIX GitHub at line 162 of file kdfinder.hpp
References Acts::UnitConstants::e, kdfinder::TVector< T >::mag(), and kdfinder::TVector< T >::mX3.
Referenced by kdfinder::TVector< T >::theta().
template<class T> TVector<T> kdfinder::TVector< T >::cross (const TVector< T > & v) const inline
Definition at line 323 of file kdfinder.hpp.
View newest version in sPHENIX GitHub at line 323 of file kdfinder.hpp
References kdfinder::TVector< T >::mX1, kdfinder::TVector< T >::mX2, kdfinder::TVector< T >::mX3, kdfinder::TVector< T >::x(), kdfinder::TVector< T >::y(), and kdfinder::TVector< T >::z().
Referenced by kdfinder::cross_product().
template<class T> T kdfinder::TVector< T >::dot (const TVector< T > & v) const inline
Definition at line 331 of file kdfinder.hpp.
View newest version in sPHENIX GitHub at line 331 of file kdfinder.hpp
References kdfinder::TVector< T >::mX1, kdfinder::TVector< T >::mX2, kdfinder::TVector< T >::mX3, kdfinder::TVector< T >::x(), kdfinder::TVector< T >::y(), and kdfinder::TVector< T >::z().
Referenced by kdfinder::TVector< T >::angle(), and pyqqbh().
template<class T> T kdfinder::TVector< T >::mag () const inline
Definition at line 187 of file kdfinder.hpp.
View newest version in sPHENIX GitHub at line 187 of file kdfinder.hpp
References kdfinder::TVector< T >::mX1, kdfinder::TVector< T >::mX2, and kdfinder::TVector< T >::mX3.
Referenced by kdfinder::TVector< T >::abs(), kdfinder::abs(), kdfinder::TVector< T >::cosTheta(), kdfinder::TVector< T >::magnitude(), and kdfinder::TVector< T >::unit().
template<class T> T kdfinder::TVector< T >::mag2 () const inline
Definition at line 192 of file kdfinder.hpp.
View newest version in sPHENIX GitHub at line 192 of file kdfinder.hpp
References kdfinder::TVector< T >::mX1, kdfinder::TVector< T >::mX2, and kdfinder::TVector< T >::mX3.
Referenced by kdfinder::TVector< T >::angle().
template<class T> T kdfinder::TVector< T >::magnitude () const inline
Definition at line 182 of file kdfinder.hpp.
View newest version in sPHENIX GitHub at line 182 of file kdfinder.hpp
References kdfinder::TVector< T >::mag().
Referenced by kdfinder::TVector< T >::setPhi(), and kdfinder::TVector< T >::setTheta().
template<class T> T kdfinder::TVector< T >::massHypothesis (T mass) const inline
Definition at line 238 of file kdfinder.hpp.
View newest version in sPHENIX GitHub at line 238 of file kdfinder.hpp
template<class T> bool kdfinder::TVector< T >::operator!= (const TVector< T > & v) const inline
Definition at line 346 of file kdfinder.hpp.
View newest version in sPHENIX GitHub at line 346 of file kdfinder.hpp
References v.
template<class T> T kdfinder::TVector< T >::operator() (size_t i) const inline
Definition at line 218 of file kdfinder.hpp.
View newest version in sPHENIX GitHub at line 218 of file kdfinder.hpp
References i, and kdfinder::TVector< T >::mX1.
template<class T> T& kdfinder::TVector< T >::operator() (size_t i) inline
Definition at line 228 of file kdfinder.hpp.
View newest version in sPHENIX GitHub at line 228 of file kdfinder.hpp
References i, and kdfinder::TVector< T >::mX1.
template<class T> TVector<T>& kdfinder::TVector< T >::operator*= (T c) inline
Definition at line 296 of file kdfinder.hpp.
View newest version in sPHENIX GitHub at line 296 of file kdfinder.hpp
References c, kdfinder::TVector< T >::mX1, kdfinder::TVector< T >::mX2, and kdfinder::TVector< T >::mX3.
template<class T> TVector<T> kdfinder::TVector< T >::operator+ () inline
Definition at line 291 of file kdfinder.hpp.
View newest version in sPHENIX GitHub at line 291 of file kdfinder.hpp
template<class T> TVector<T>& kdfinder::TVector< T >::operator+= (const TVector< T > & v) inline
Definition at line 351 of file kdfinder.hpp.
View newest version in sPHENIX GitHub at line 351 of file kdfinder.hpp
References kdfinder::TVector< T >::mX1, kdfinder::TVector< T >::mX2, kdfinder::TVector< T >::mX3, kdfinder::TVector< T >::x(), kdfinder::TVector< T >::y(), and kdfinder::TVector< T >::z().
template<class T> TVector<T> kdfinder::TVector< T >::operator- () inline
Definition at line 286 of file kdfinder.hpp.
View newest version in sPHENIX GitHub at line 286 of file kdfinder.hpp
References kdfinder::TVector< T >::mX1, kdfinder::TVector< T >::mX2, and kdfinder::TVector< T >::mX3.
template<class T> TVector<T>& kdfinder::TVector< T >::operator-= (const TVector< T > & v) inline
Definition at line 359 of file kdfinder.hpp.
View newest version in sPHENIX GitHub at line 359 of file kdfinder.hpp
References kdfinder::TVector< T >::mX1, kdfinder::TVector< T >::mX2, kdfinder::TVector< T >::mX3, kdfinder::TVector< T >::x(), kdfinder::TVector< T >::y(), and kdfinder::TVector< T >::z().
template<class T> TVector<T>& kdfinder::TVector< T >::operator/= (T c) inline
Definition at line 304 of file kdfinder.hpp.
View newest version in sPHENIX GitHub at line 304 of file kdfinder.hpp
References c, kdfinder::TVector< T >::mX1, kdfinder::TVector< T >::mX2, and kdfinder::TVector< T >::mX3.
template<class T> TVector<T>& kdfinder::TVector< T >::operator= (const TVector< T > & v) inline
Definition at line 210 of file kdfinder.hpp.
View newest version in sPHENIX GitHub at line 210 of file kdfinder.hpp
References kdfinder::TVector< T >::mX1, kdfinder::TVector< T >::mX2, kdfinder::TVector< T >::mX3, kdfinder::TVector< T >::x(), kdfinder::TVector< T >::y(), and kdfinder::TVector< T >::z().
template<class T> bool kdfinder::TVector< T >::operator== (const TVector< T > & v) const inline
Definition at line 341 of file kdfinder.hpp.
View newest version in sPHENIX GitHub at line 341 of file kdfinder.hpp
References kdfinder::TVector< T >::mX1, kdfinder::TVector< T >::mX2, kdfinder::TVector< T >::mX3, kdfinder::TVector< T >::x(), kdfinder::TVector< T >::y(), and kdfinder::TVector< T >::z().
template<class T> T kdfinder::TVector< T >::operator[] (size_t i) const inline
Definition at line 223 of file kdfinder.hpp.
View newest version in sPHENIX GitHub at line 223 of file kdfinder.hpp
References i, and kdfinder::TVector< T >::mX1.
template<class T> T& kdfinder::TVector< T >::operator[] (size_t i) inline
Definition at line 233 of file kdfinder.hpp.
View newest version in sPHENIX GitHub at line 233 of file kdfinder.hpp
References i, and kdfinder::TVector< T >::mX1.
template<class T> TVector<T> kdfinder::TVector< T >::orthogonal () const inline
Definition at line 250 of file kdfinder.hpp.
View newest version in sPHENIX GitHub at line 250 of file kdfinder.hpp
References kdfinder::TVector< T >::mX1, kdfinder::TVector< T >::mX2, kdfinder::TVector< T >::mX3, Acts::UnitConstants::T, TauVsDIS_MachineLearning_Differentiation::X, TauVsDIS_MachineLearning_Differentiation::Y, and SVM_v1::Z.
template<class T> T kdfinder::TVector< T >::perp () const inline
Definition at line 172 of file kdfinder.hpp.
View newest version in sPHENIX GitHub at line 172 of file kdfinder.hpp
References kdfinder::TVector< T >::mX1, and kdfinder::TVector< T >::mX2.
Referenced by kdfinder::find_vertex_seeds(), kdfinder::Helix< T >::geometricSignedDistance(), and kdfinder::Helix< T >::Helix().
template<class T> T kdfinder::TVector< T >::perp2 () const inline
Definition at line 177 of file kdfinder.hpp.
View newest version in sPHENIX GitHub at line 177 of file kdfinder.hpp
References kdfinder::TVector< T >::mX1, and kdfinder::TVector< T >::mX2.
template<class T> T kdfinder::TVector< T >::phi () const inline
Definition at line 167 of file kdfinder.hpp.
View newest version in sPHENIX GitHub at line 167 of file kdfinder.hpp
References kdfinder::TVector< T >::mX1, and kdfinder::TVector< T >::mX2.
Referenced by kdfinder::TVector< T >::setMagnitude(), and kdfinder::TVector< T >::setTheta().
template<class T> TVector<T> kdfinder::TVector< T >::pseudoProduct (T X, T Y, T Z) const inline
Definition at line 312 of file kdfinder.hpp.
View newest version in sPHENIX GitHub at line 312 of file kdfinder.hpp
References kdfinder::TVector< T >::mX1, kdfinder::TVector< T >::mX2, kdfinder::TVector< T >::mX3, TauVsDIS_MachineLearning_Differentiation::X, TauVsDIS_MachineLearning_Differentiation::Y, and SVM_v1::Z.
Referenced by kdfinder::TVector< T >::pseudoProduct().
template<class T> TVector<T> kdfinder::TVector< T >::pseudoProduct (const TVector< T > & v) const inline
Definition at line 336 of file kdfinder.hpp.
View newest version in sPHENIX GitHub at line 336 of file kdfinder.hpp
References kdfinder::TVector< T >::pseudoProduct(), kdfinder::TVector< T >::x(), kdfinder::TVector< T >::y(), and kdfinder::TVector< T >::z().
template<class T> T kdfinder::TVector< T >::pseudoRapidity () const inline
Definition at line 197 of file kdfinder.hpp.
View newest version in sPHENIX GitHub at line 197 of file kdfinder.hpp
References rotate::log, and kdfinder::TVector< T >::theta().
template<class T> void kdfinder::TVector< T >::rotateX (T Angle) inline
Definition at line 262 of file kdfinder.hpp.
View newest version in sPHENIX GitHub at line 262 of file kdfinder.hpp
References kdfinder::TVector< T >::mX2, kdfinder::TVector< T >::mX3, and Acts::UnitConstants::T.
template<class T> void kdfinder::TVector< T >::rotateY (T Angle) inline
Definition at line 270 of file kdfinder.hpp.
View newest version in sPHENIX GitHub at line 270 of file kdfinder.hpp
References kdfinder::TVector< T >::mX1, kdfinder::TVector< T >::mX3, and Acts::UnitConstants::T.
template<class T> void kdfinder::TVector< T >::rotateZ (T Angle) inline
Definition at line 278 of file kdfinder.hpp.
View newest version in sPHENIX GitHub at line 278 of file kdfinder.hpp
References kdfinder::TVector< T >::mX1, kdfinder::TVector< T >::mX2, and Acts::UnitConstants::T.
Referenced by kdfinder::TrackCandidate< T >::getPosForHit().
template<class T> void kdfinder::TVector< T >::set (T X, T Y, T Z) inline
Definition at line 110 of file kdfinder.hpp.
View newest version in sPHENIX GitHub at line 110 of file kdfinder.hpp
References kdfinder::TVector< T >::mX1, kdfinder::TVector< T >::mX2, kdfinder::TVector< T >::mX3, TauVsDIS_MachineLearning_Differentiation::X, TauVsDIS_MachineLearning_Differentiation::Y, and SVM_v1::Z.
template<class T> void kdfinder::TVector< T >::setMag (T Mag) inline
Definition at line 134 of file kdfinder.hpp.
View newest version in sPHENIX GitHub at line 134 of file kdfinder.hpp
References kdfinder::TVector< T >::setMagnitude().
template<class T> void kdfinder::TVector< T >::setMagnitude (T r) inline
Definition at line 139 of file kdfinder.hpp.
View newest version in sPHENIX GitHub at line 139 of file kdfinder.hpp
References kdfinder::TVector< T >::mX1, kdfinder::TVector< T >::mX2, kdfinder::TVector< T >::mX3, kdfinder::TVector< T >::phi(), and kdfinder::TVector< T >::theta().
Referenced by kdfinder::TVector< T >::setMag().
template<class T> void kdfinder::TVector< T >::setPhi (T Angle) inline
Definition at line 117 of file kdfinder.hpp.
View newest version in sPHENIX GitHub at line 117 of file kdfinder.hpp
References kdfinder::TVector< T >::magnitude(), kdfinder::TVector< T >::mX1, kdfinder::TVector< T >::mX2, r, and kdfinder::TVector< T >::theta().
template<class T> void kdfinder::TVector< T >::setTheta (T Angle) inline
Definition at line 125 of file kdfinder.hpp.
View newest version in sPHENIX GitHub at line 125 of file kdfinder.hpp
References kdfinder::TVector< T >::magnitude(), kdfinder::TVector< T >::mX1, kdfinder::TVector< T >::mX2, kdfinder::TVector< T >::mX3, kdfinder::TVector< T >::phi(), and r.
template<class T> void kdfinder::TVector< T >::setX (T x) inline
Definition at line 106 of file kdfinder.hpp.
View newest version in sPHENIX GitHub at line 106 of file kdfinder.hpp
References kdfinder::TVector< T >::mX1, and kdfinder::TVector< T >::x().
template<class T> void kdfinder::TVector< T >::setY (T y) inline
Definition at line 107 of file kdfinder.hpp.
View newest version in sPHENIX GitHub at line 107 of file kdfinder.hpp
References kdfinder::TVector< T >::mX2, and kdfinder::TVector< T >::y().
template<class T> void kdfinder::TVector< T >::setZ (T z) inline
Definition at line 108 of file kdfinder.hpp.
View newest version in sPHENIX GitHub at line 108 of file kdfinder.hpp
References kdfinder::TVector< T >::mX3, and kdfinder::TVector< T >::z().
Referenced by kdfinder::Helix< T >::geometricSignedDistance(), and kdfinder::TrackCandidate< T >::getPosForHit().
template<class T> T kdfinder::TVector< T >::theta () const inline
Definition at line 157 of file kdfinder.hpp.
View newest version in sPHENIX GitHub at line 157 of file kdfinder.hpp
References kdfinder::TVector< T >::cosTheta().
Referenced by kdfinder::TVector< T >::pseudoRapidity(), kdfinder::TVector< T >::setMagnitude(), and kdfinder::TVector< T >::setPhi().
template<class T> TVector<T> kdfinder::TVector< T >::unit () const inline
Definition at line 243 of file kdfinder.hpp.
View newest version in sPHENIX GitHub at line 243 of file kdfinder.hpp
References Acts::UnitConstants::e, kdfinder::TVector< T >::mag(), and Acts::UnitConstants::T.
Referenced by init(), medinit(), and xytabl().
template<class T> int kdfinder::TVector< T >::valid (T world = 1.e+5) const inline
Definition at line 367 of file kdfinder.hpp.
View newest version in sPHENIX GitHub at line 367 of file kdfinder.hpp
References kdfinder::TVector< T >::bad(), and Acts::Test::world.
template<class T> const T& kdfinder::TVector< T >::x () const inline
Definition at line 148 of file kdfinder.hpp.
View newest version in sPHENIX GitHub at line 148 of file kdfinder.hpp
References kdfinder::TVector< T >::mX1.
Referenced by kdfinder::TVector< T >::cross(), kdfinder::Helix< T >::curvatureSignedDistance(), kdfinder::TVector< T >::dot(), kdfinder::find_vertex_seeds(), kdfinder::Helix< T >::fudgePathLength(), kdfinder::Helix< T >::geometricSignedDistance(), kdfinder::TrackCandidate< T >::getPosForHit(), kdfinder::Helix< T >::Helix(), kdfinder::Helix< T >::moveOrigin(), kdfinder::TVector< T >::operator+=(), kdfinder::TVector< T >::operator-=(), kdfinder::TVector< T >::operator=(), kdfinder::TVector< T >::operator==(), kdfinder::Helix< T >::pathLength(), kdfinder::TVector< T >::pseudoProduct(), and kdfinder::TVector< T >::setX().
template<class T> const T* kdfinder::TVector< T >::xyz () const inline
Definition at line 152 of file kdfinder.hpp.
View newest version in sPHENIX GitHub at line 152 of file kdfinder.hpp
References kdfinder::TVector< T >::mX1.
template<class T> T* kdfinder::TVector< T >::xyz () inline
Definition at line 153 of file kdfinder.hpp.
View newest version in sPHENIX GitHub at line 153 of file kdfinder.hpp
References kdfinder::TVector< T >::mX1.
template<class T> const T& kdfinder::TVector< T >::y () const inline
Definition at line 149 of file kdfinder.hpp.
View newest version in sPHENIX GitHub at line 149 of file kdfinder.hpp
References kdfinder::TVector< T >::mX2.
Referenced by kdfinder::TVector< T >::cross(), kdfinder::Helix< T >::curvatureSignedDistance(), kdfinder::TVector< T >::dot(), kdfinder::find_vertex_seeds(), kdfinder::Helix< T >::fudgePathLength(), kdfinder::Helix< T >::geometricSignedDistance(), kdfinder::TrackCandidate< T >::getPosForHit(), kdfinder::Helix< T >::Helix(), kdfinder::Helix< T >::moveOrigin(), kdfinder::TVector< T >::operator+=(), kdfinder::TVector< T >::operator-=(), kdfinder::TVector< T >::operator=(), kdfinder::TVector< T >::operator==(), kdfinder::Helix< T >::pathLength(), kdfinder::TVector< T >::pseudoProduct(), and kdfinder::TVector< T >::setY().
template<class T> const T& kdfinder::TVector< T >::z () const inline
Definition at line 150 of file kdfinder.hpp.
View newest version in sPHENIX GitHub at line 150 of file kdfinder.hpp
References kdfinder::TVector< T >::mX3.
Referenced by kdfinder::TVector< T >::cross(), kdfinder::TVector< T >::dot(), kdfinder::find_vertex_seeds(), kdfinder::TrackCandidate< T >::getPosForHit(), kdfinder::Helix< T >::Helix(), kdfinder::TVector< T >::operator+=(), kdfinder::TVector< T >::operator-=(), kdfinder::TVector< T >::operator=(), kdfinder::TVector< T >::operator==(), kdfinder::Helix< T >::pathLength(), kdfinder::TVector< T >::pseudoProduct(), and kdfinder::TVector< T >::setZ().
Member Data Documentation
template<class T> T kdfinder::TVector< T >::mX1 protected
Definition at line 389 of file kdfinder.hpp.
View newest version in sPHENIX GitHub at line 389 of file kdfinder.hpp
Referenced by kdfinder::TVector< T >::bad(), kdfinder::TVector< T >::cross(), kdfinder::TVector< T >::dot(), kdfinder::TVector< T >::mag(), kdfinder::TVector< T >::mag2(), kdfinder::TVector< T >::operator()(), kdfinder::TVector< T >::operator*=(), kdfinder::TVector< T >::operator+=(), kdfinder::TVector< T >::operator-(), kdfinder::TVector< T >::operator-=(), kdfinder::TVector< T >::operator/=(), kdfinder::TVector< T >::operator=(), kdfinder::TVector< T >::operator==(), kdfinder::TVector< T >::operator[](), kdfinder::TVector< T >::orthogonal(), kdfinder::TVector< T >::perp(), kdfinder::TVector< T >::perp2(), kdfinder::TVector< T >::phi(), kdfinder::TVector< T >::pseudoProduct(), kdfinder::TVector< T >::rotateY(), kdfinder::TVector< T >::rotateZ(), kdfinder::TVector< T >::set(), kdfinder::TVector< T >::setMagnitude(), kdfinder::TVector< T >::setPhi(), kdfinder::TVector< T >::setTheta(), kdfinder::TVector< T >::setX(), kdfinder::TVector< T >::x(), and kdfinder::TVector< T >::xyz().
template<class T> T kdfinder::TVector< T >::mX2 protected
Definition at line 389 of file kdfinder.hpp.
View newest version in sPHENIX GitHub at line 389 of file kdfinder.hpp
Referenced by kdfinder::TVector< T >::cross(), kdfinder::TVector< T >::dot(), kdfinder::TVector< T >::mag(), kdfinder::TVector< T >::mag2(), kdfinder::TVector< T >::operator*=(), kdfinder::TVector< T >::operator+=(), kdfinder::TVector< T >::operator-(), kdfinder::TVector< T >::operator-=(), kdfinder::TVector< T >::operator/=(), kdfinder::TVector< T >::operator=(), kdfinder::TVector< T >::operator==(), kdfinder::TVector< T >::orthogonal(), kdfinder::TVector< T >::perp(), kdfinder::TVector< T >::perp2(), kdfinder::TVector< T >::phi(), kdfinder::TVector< T >::pseudoProduct(), kdfinder::TVector< T >::rotateX(), kdfinder::TVector< T >::rotateZ(), kdfinder::TVector< T >::set(), kdfinder::TVector< T >::setMagnitude(), kdfinder::TVector< T >::setPhi(), kdfinder::TVector< T >::setTheta(), kdfinder::TVector< T >::setY(), and kdfinder::TVector< T >::y().
template<class T> T kdfinder::TVector< T >::mX3 protected
Definition at line 389 of file kdfinder.hpp.
View newest version in sPHENIX GitHub at line 389 of file kdfinder.hpp
Referenced by kdfinder::TVector< T >::cosTheta(), kdfinder::TVector< T >::cross(), kdfinder::TVector< T >::dot(), kdfinder::TVector< T >::mag(), kdfinder::TVector< T >::mag2(), kdfinder::TVector< T >::operator*=(), kdfinder::TVector< T >::operator+=(), kdfinder::TVector< T >::operator-(), kdfinder::TVector< T >::operator-=(), kdfinder::TVector< T >::operator/=(), kdfinder::TVector< T >::operator=(), kdfinder::TVector< T >::operator==(), kdfinder::TVector< T >::orthogonal(), kdfinder::TVector< T >::pseudoProduct(), kdfinder::TVector< T >::rotateX(), kdfinder::TVector< T >::rotateY(), kdfinder::TVector< T >::set(), kdfinder::TVector< T >::setMagnitude(), kdfinder::TVector< T >::setTheta(), kdfinder::TVector< T >::setZ(), and kdfinder::TVector< T >::z().
The documentation for this class was generated from the following file:
coresoftware/blob/master/offline/packages/PHTpcTracker/externals/kdfinder.hpp