Analysis Software: macros/blob/master/calibrations/calo/calib_nov23/pimacs/plain_sim_dst_simple_preNov23.C File Reference
plain_sim_dst_simple_preNov23.C File Reference
#include <fun4all/SubsysReco.h>
#include <fun4all/Fun4AllServer.h>
#include <fun4all/Fun4AllInputManager.h>
#include <fun4all/Fun4AllRunNodeInputManager.h>
#include <fun4allraw/Fun4AllPrdfInputManager.h>
#include <fun4all/Fun4AllDstInputManager.h>
#include <fun4all/Fun4AllDstOutputManager.h>
#include <caloreco/CaloTowerCalib.h>
#include <caloreco/RawClusterBuilderTemplate.h>
#include <calib_emc_pi0/CaloCalibEmc_Pi0.h>
#include <phool/recoConsts.h>
#include <g4centrality/PHG4CentralityReco.h>
Functions
void clus_dst_simple_superfastcalib (const int file_num=0)
Function Documentation
void clus_dst_simple_superfastcalib (const int file_num = 0)
sphenix/lustre01/sphnxpro/mdc2/shijing_hepmc/fm_0_20/calocluster/run0007
Definition at line 32 of file plain_sim_dst_simple_preNov23.C.
View newest version in sPHENIX GitHub at line 32 of file plain_sim_dst_simple_preNov23.C
References Enable::CEMC, RawClusterBuilderTemplate::Detector(), Fun4AllServer::End(), Fun4AllInputManager::fileopen(), recoConsts::instance(), Fun4AllServer::instance(), RawClusterBuilderTemplate::LoadProfile(), nEvents, Fun4AllServer::PrintTimer(), Fun4AllServer::registerInputManager(), Fun4AllServer::registerSubsystem(), Fun4AllServer::run(), CaloTowerCalib::set_detector_type(), PHFlag::set_StringFlag(), RawClusterBuilderTemplate::set_threshold_energy(), PHFlag::set_uint64Flag(), RawClusterBuilderTemplate::set_UseTowerInfo(), CaloCalibEmc_Pi0::set_UseTowerInfo(), CaloTowerCalib::setCalibName(), CaloTowerCalib::setFieldName(), and Fun4AllBase::Verbosity().