Analysis Software: GPUTPCBaseTrackParam Class Reference
GPUTPCBaseTrackParam Class Reference
#include <coresoftware/blob/master/offline/packages/trackreco/GPUTPCBaseTrackParam.h>
Public Member Functions
double X () const
double Y () const
double Z () const
double SinPhi () const
double DzDs () const
double QPt () const
double ZOffset () const
double GetX () const
double GetY () const
double GetZ () const
double GetSinPhi () const
double GetDzDs () const
double GetQPt () const
double GetZOffset () const
double GetKappa (double Bz) const
const double * Par () const
const double * GetPar () const
double GetPar (int i) const
void SetPar (int i, double v)
void SetX (double v)
void SetY (double v)
void SetZ (double v)
void SetSinPhi (double v)
void SetDzDs (double v)
void SetQPt (double v)
void SetZOffset (double v)
Private Attributes
double mX
double mZOffset
double mP [5]
Detailed Description
GPUTPCBaseTrackParam class contains track parameters used in output of the GPUTPCTracker slice tracker. This class is used for transfer between tracker and merger and does not contain the covariance matrice
Definition at line 28 of file GPUTPCBaseTrackParam.h.
View newest version in sPHENIX GitHub at line 28 of file GPUTPCBaseTrackParam.h
Member Function Documentation
double GPUTPCBaseTrackParam::DzDs () const inline
Definition at line 35 of file GPUTPCBaseTrackParam.h.
View newest version in sPHENIX GitHub at line 35 of file GPUTPCBaseTrackParam.h
References mP.
Referenced by GPUTPCTrackParam::DzDs().
double GPUTPCBaseTrackParam::GetDzDs () const inline
Definition at line 43 of file GPUTPCBaseTrackParam.h.
View newest version in sPHENIX GitHub at line 43 of file GPUTPCBaseTrackParam.h
References mP.
Referenced by GPUTPCTrackParam::GetDzDs().
double GPUTPCBaseTrackParam::GetKappa (double Bz) const inline
Definition at line 47 of file GPUTPCBaseTrackParam.h.
View newest version in sPHENIX GitHub at line 47 of file GPUTPCBaseTrackParam.h
References Acts::IntegrationTest::Bz, and mP.
Referenced by GPUTPCTrackParam::GetKappa().
const double* GPUTPCBaseTrackParam::GetPar () const inline
Definition at line 50 of file GPUTPCBaseTrackParam.h.
View newest version in sPHENIX GitHub at line 50 of file GPUTPCBaseTrackParam.h
References mP.
Referenced by GPUTPCTrackParam::GetPar().
double GPUTPCBaseTrackParam::GetPar (int i) const inline
Definition at line 51 of file GPUTPCBaseTrackParam.h.
View newest version in sPHENIX GitHub at line 51 of file GPUTPCBaseTrackParam.h
References mP.
double GPUTPCBaseTrackParam::GetQPt () const inline
Definition at line 44 of file GPUTPCBaseTrackParam.h.
View newest version in sPHENIX GitHub at line 44 of file GPUTPCBaseTrackParam.h
References mP.
Referenced by GPUTPCTrackParam::GetQPt().
double GPUTPCBaseTrackParam::GetSinPhi () const inline
Definition at line 42 of file GPUTPCBaseTrackParam.h.
View newest version in sPHENIX GitHub at line 42 of file GPUTPCBaseTrackParam.h
References mP.
Referenced by GPUTPCTrackParam::GetSinPhi().
double GPUTPCBaseTrackParam::GetX () const inline
Definition at line 39 of file GPUTPCBaseTrackParam.h.
View newest version in sPHENIX GitHub at line 39 of file GPUTPCBaseTrackParam.h
References mX.
Referenced by GPUTPCTrackParam::GetX().
double GPUTPCBaseTrackParam::GetY () const inline
Definition at line 40 of file GPUTPCBaseTrackParam.h.
View newest version in sPHENIX GitHub at line 40 of file GPUTPCBaseTrackParam.h
References mP.
Referenced by GPUTPCTrackParam::GetY().
double GPUTPCBaseTrackParam::GetZ () const inline
Definition at line 41 of file GPUTPCBaseTrackParam.h.
View newest version in sPHENIX GitHub at line 41 of file GPUTPCBaseTrackParam.h
References mP.
Referenced by GPUTPCTrackParam::GetZ().
double GPUTPCBaseTrackParam::GetZOffset () const inline
Definition at line 45 of file GPUTPCBaseTrackParam.h.
View newest version in sPHENIX GitHub at line 45 of file GPUTPCBaseTrackParam.h
References mZOffset.
const double* GPUTPCBaseTrackParam::Par () const inline
Definition at line 49 of file GPUTPCBaseTrackParam.h.
View newest version in sPHENIX GitHub at line 49 of file GPUTPCBaseTrackParam.h
References mP.
Referenced by GPUTPCTrackParam::Par().
double GPUTPCBaseTrackParam::QPt () const inline
Definition at line 36 of file GPUTPCBaseTrackParam.h.
View newest version in sPHENIX GitHub at line 36 of file GPUTPCBaseTrackParam.h
References mP.
Referenced by GPUTPCTrackParam::QPt().
void GPUTPCBaseTrackParam::SetDzDs (double v) inline
Definition at line 59 of file GPUTPCBaseTrackParam.h.
View newest version in sPHENIX GitHub at line 59 of file GPUTPCBaseTrackParam.h
References mP, and testSigmaEff::v.
Referenced by GPUTPCTrackParam::SetDzDs().
void GPUTPCBaseTrackParam::SetPar (int i, double v) inline
Definition at line 53 of file GPUTPCBaseTrackParam.h.
View newest version in sPHENIX GitHub at line 53 of file GPUTPCBaseTrackParam.h
References i, mP, and testSigmaEff::v.
Referenced by GPUTPCTrackParam::SetPar().
void GPUTPCBaseTrackParam::SetQPt (double v) inline
Definition at line 60 of file GPUTPCBaseTrackParam.h.
View newest version in sPHENIX GitHub at line 60 of file GPUTPCBaseTrackParam.h
References mP, and testSigmaEff::v.
Referenced by GPUTPCTrackParam::SetQPt().
void GPUTPCBaseTrackParam::SetSinPhi (double v) inline
Definition at line 58 of file GPUTPCBaseTrackParam.h.
View newest version in sPHENIX GitHub at line 58 of file GPUTPCBaseTrackParam.h
References mP, and testSigmaEff::v.
Referenced by GPUTPCTrackParam::SetSinPhi().
void GPUTPCBaseTrackParam::SetX (double v) inline
Definition at line 55 of file GPUTPCBaseTrackParam.h.
View newest version in sPHENIX GitHub at line 55 of file GPUTPCBaseTrackParam.h
References mX, and testSigmaEff::v.
Referenced by GPUTPCTrackParam::SetX().
void GPUTPCBaseTrackParam::SetY (double v) inline
Definition at line 56 of file GPUTPCBaseTrackParam.h.
View newest version in sPHENIX GitHub at line 56 of file GPUTPCBaseTrackParam.h
References mP, and testSigmaEff::v.
Referenced by GPUTPCTrackParam::SetY().
void GPUTPCBaseTrackParam::SetZ (double v) inline
Definition at line 57 of file GPUTPCBaseTrackParam.h.
View newest version in sPHENIX GitHub at line 57 of file GPUTPCBaseTrackParam.h
References mP, and testSigmaEff::v.
Referenced by GPUTPCTrackParam::SetZ().
void GPUTPCBaseTrackParam::SetZOffset (double v) inline
Definition at line 61 of file GPUTPCBaseTrackParam.h.
View newest version in sPHENIX GitHub at line 61 of file GPUTPCBaseTrackParam.h
References mZOffset, and testSigmaEff::v.
Referenced by GPUTPCTrackParam::SetZOffset().
double GPUTPCBaseTrackParam::SinPhi () const inline
Definition at line 34 of file GPUTPCBaseTrackParam.h.
View newest version in sPHENIX GitHub at line 34 of file GPUTPCBaseTrackParam.h
References mP.
Referenced by GPUTPCTrackParam::SinPhi().
double GPUTPCBaseTrackParam::X () const inline
Definition at line 31 of file GPUTPCBaseTrackParam.h.
View newest version in sPHENIX GitHub at line 31 of file GPUTPCBaseTrackParam.h
References mX.
Referenced by GPUTPCTrackParam::X().
double GPUTPCBaseTrackParam::Y () const inline
Definition at line 32 of file GPUTPCBaseTrackParam.h.
View newest version in sPHENIX GitHub at line 32 of file GPUTPCBaseTrackParam.h
References mP.
Referenced by GPUTPCTrackParam::Y().
double GPUTPCBaseTrackParam::Z () const inline
Definition at line 33 of file GPUTPCBaseTrackParam.h.
View newest version in sPHENIX GitHub at line 33 of file GPUTPCBaseTrackParam.h
References mP.
Referenced by GPUTPCTrackParam::Z().
double GPUTPCBaseTrackParam::ZOffset () const inline
Definition at line 37 of file GPUTPCBaseTrackParam.h.
View newest version in sPHENIX GitHub at line 37 of file GPUTPCBaseTrackParam.h
References mZOffset.
Referenced by GPUTPCTrackParam::ZOffset().
Member Data Documentation
double GPUTPCBaseTrackParam::mP[5] private
Definition at line 69 of file GPUTPCBaseTrackParam.h.
View newest version in sPHENIX GitHub at line 69 of file GPUTPCBaseTrackParam.h
Referenced by DzDs(), GetDzDs(), GetKappa(), GetPar(), GetQPt(), GetSinPhi(), GetY(), GetZ(), Par(), QPt(), SetDzDs(), SetPar(), SetQPt(), SetSinPhi(), SetY(), SetZ(), SinPhi(), Y(), and Z().
double GPUTPCBaseTrackParam::mX private
Definition at line 67 of file GPUTPCBaseTrackParam.h.
View newest version in sPHENIX GitHub at line 67 of file GPUTPCBaseTrackParam.h
Referenced by GetX(), SetX(), and X().
double GPUTPCBaseTrackParam::mZOffset private
Definition at line 68 of file GPUTPCBaseTrackParam.h.
View newest version in sPHENIX GitHub at line 68 of file GPUTPCBaseTrackParam.h
Referenced by GetZOffset(), SetZOffset(), and ZOffset().
The documentation for this class was generated from the following file:
coresoftware/blob/master/offline/packages/trackreco/GPUTPCBaseTrackParam.h