Analysis Software: ActsExamples::PlanarSteppingAlgorithm Exception Reference
ActsExamples::PlanarSteppingAlgorithm Exception Reference final
Create planar clusters from simulation hits.
#include <acts/blob/sPHENIX/Examples/Algorithms/Digitization/include/ActsExamples/Digitization/PlanarSteppingAlgorithm.hpp>
Classes
struct Config
struct Digitizable
Public Types
using ClusterContainer = ActsExamples::GeometryIdMultimap< Acts::PlanarModuleCluster >
Public Member Functions
PlanarSteppingAlgorithm (Config config, Acts::Logging::Level level)
ProcessCode execute (const AlgorithmContext &ctx) const override
const Config & config () const
Readonly access to the config.
Public Member Functions inherited from ActsExamples::IAlgorithm
IAlgorithm (std::string name, Acts::Logging::Level level=Acts::Logging::INFO)
std::string name () const override
The algorithm name.
ProcessCode internalExecute (const AlgorithmContext &context) final
ProcessCode initialize () override
Initialize the algorithm.
ProcessCode finalize () override
Finalize the algorithm.
Private Attributes
Config m_cfg
std::unordered_map
< Acts::GeometryIdentifier,
Digitizable > m_digitizables
Lookup container for all digitizable surfaces.
ReadDataHandle< SimHitContainer > m_inputSimHits {this, "InputSimHits"}
WriteDataHandle< ClusterContainer > m_outputClusters {this, "OutputClusters"}
WriteDataHandle
< GeometryIdMultiset
< IndexSourceLink > > m_outputSourceLinks
WriteDataHandle< std::vector
< Acts::DigitizationSourceLink > > m_outputDigiSourceLinks {this, "OutputDigiSourceLinks"}
WriteDataHandle
< MeasurementContainer > m_outputMeasurements
WriteDataHandle< IndexMultimap
< ActsFatras::Barcode > > m_outputMeasurementParticlesMap {this, "OutputMeasurementParticlesMap"}
WriteDataHandle< IndexMultimap
< Index > > m_outputMeasurementSimHitsMap
Additional Inherited Members
Protected Member Functions inherited from ActsExamples::IAlgorithm
const Acts::Logger & logger () const
Detailed Description
Create planar clusters from simulation hits.
Definition at line 49 of file PlanarSteppingAlgorithm.hpp.
View newest version in sPHENIX GitHub at line 49 of file PlanarSteppingAlgorithm.hpp
Member Typedef Documentation
using ActsExamples::PlanarSteppingAlgorithm::ClusterContainer = ActsExamples::GeometryIdMultimap<Acts::PlanarModuleCluster>
Definition at line 52 of file PlanarSteppingAlgorithm.hpp.
View newest version in sPHENIX GitHub at line 52 of file PlanarSteppingAlgorithm.hpp
Constructor & Destructor Documentation
ActsExamples::PlanarSteppingAlgorithm::PlanarSteppingAlgorithm (Config config, Acts::Logging::Level level)
Construct the digitization algorithm.
Parameters
config is the algorithm configuration
level is the logging level
Definition at line 44 of file PlanarSteppingAlgorithm.cpp.
View newest version in sPHENIX GitHub at line 44 of file PlanarSteppingAlgorithm.cpp
References Acts::IdentifiedDetectorElement::digitizationModule(), Acts::GeometryObject::geometryId(), ActsExamples::WriteDataHandle< T >::initialize(), ActsExamples::ReadDataHandle< T >::initialize(), ActsExamples::PlanarSteppingAlgorithm::Config::inputSimHits, m_cfg, m_digitizables, m_inputSimHits, m_outputClusters, m_outputDigiSourceLinks, m_outputMeasurementParticlesMap, m_outputMeasurements, m_outputMeasurementSimHitsMap, m_outputSourceLinks, ActsExamples::PlanarSteppingAlgorithm::Config::outputClusters, ActsExamples::PlanarSteppingAlgorithm::Config::outputDigiSourceLinks, ActsExamples::PlanarSteppingAlgorithm::Config::outputMeasurementParticlesMap, ActsExamples::PlanarSteppingAlgorithm::Config::outputMeasurements, ActsExamples::PlanarSteppingAlgorithm::Config::outputMeasurementSimHitsMap, ActsExamples::PlanarSteppingAlgorithm::Config::outputSourceLinks, ActsExamples::PlanarSteppingAlgorithm::Config::planarModuleStepper, ActsExamples::PlanarSteppingAlgorithm::Config::randomNumbers, writeMapConfig::surface, ActsExamples::PlanarSteppingAlgorithm::Digitizable::surface, and ActsExamples::PlanarSteppingAlgorithm::Config::trackingGeometry.
Member Function Documentation
const Config& ActsExamples::PlanarSteppingAlgorithm::config () const inline
Readonly access to the config.
Definition at line 90 of file PlanarSteppingAlgorithm.hpp.
View newest version in sPHENIX GitHub at line 90 of file PlanarSteppingAlgorithm.hpp
References m_cfg.
ActsExamples::ProcessCode ActsExamples::PlanarSteppingAlgorithm::execute (const AlgorithmContext & ctx) const override virtual
Build clusters from input simulation hits.
Parameters
txt is the algorithm context with event information
Returns
a process code indication success or failure
Implements ActsExamples::IAlgorithm.
Definition at line 117 of file PlanarSteppingAlgorithm.cpp.
View newest version in sPHENIX GitHub at line 117 of file PlanarSteppingAlgorithm.cpp
References ACTS_DEBUG, ACTS_VERBOSE, Acts::Segmentation::binUtility(), clusters, Acts::Test::cov, Acts::eBoundLoc0, Acts::eBoundLoc1, Acts::eBoundTime, ActsExamples::AlgorithmContext::geoContext, ActsExamples::groupByModule(), it, m_cfg(), Acts::makeMeasurement(), testing::internal::move(), Acts::UnitConstants::ps, Acts::Measurement< indices_t, kSize >::size(), SUCCESS, and thickness.
Member Data Documentation
Config ActsExamples::PlanarSteppingAlgorithm::m_cfg private
Definition at line 99 of file PlanarSteppingAlgorithm.hpp.
View newest version in sPHENIX GitHub at line 99 of file PlanarSteppingAlgorithm.hpp
Referenced by config(), and PlanarSteppingAlgorithm().
std::unordered_map<Acts::GeometryIdentifier, Digitizable> ActsExamples::PlanarSteppingAlgorithm::m_digitizables private
Lookup container for all digitizable surfaces.
Definition at line 101 of file PlanarSteppingAlgorithm.hpp.
View newest version in sPHENIX GitHub at line 101 of file PlanarSteppingAlgorithm.hpp
Referenced by PlanarSteppingAlgorithm().
ReadDataHandle<SimHitContainer> ActsExamples::PlanarSteppingAlgorithm::m_inputSimHits {this, "InputSimHits"} private
Definition at line 103 of file PlanarSteppingAlgorithm.hpp.
View newest version in sPHENIX GitHub at line 103 of file PlanarSteppingAlgorithm.hpp
Referenced by PlanarSteppingAlgorithm().
WriteDataHandle<ClusterContainer> ActsExamples::PlanarSteppingAlgorithm::m_outputClusters {this, "OutputClusters"} private
Definition at line 105 of file PlanarSteppingAlgorithm.hpp.
View newest version in sPHENIX GitHub at line 105 of file PlanarSteppingAlgorithm.hpp
Referenced by PlanarSteppingAlgorithm().
WriteDataHandle<std::vector<Acts::DigitizationSourceLink> > ActsExamples::PlanarSteppingAlgorithm::m_outputDigiSourceLinks {this, "OutputDigiSourceLinks"} private
Definition at line 111 of file PlanarSteppingAlgorithm.hpp.
View newest version in sPHENIX GitHub at line 111 of file PlanarSteppingAlgorithm.hpp
Referenced by PlanarSteppingAlgorithm().
WriteDataHandle<IndexMultimap<ActsFatras::Barcode> > ActsExamples::PlanarSteppingAlgorithm::m_outputMeasurementParticlesMap {this, "OutputMeasurementParticlesMap"} private
Definition at line 117 of file PlanarSteppingAlgorithm.hpp.
View newest version in sPHENIX GitHub at line 117 of file PlanarSteppingAlgorithm.hpp
Referenced by PlanarSteppingAlgorithm().
WriteDataHandle<MeasurementContainer> ActsExamples::PlanarSteppingAlgorithm::m_outputMeasurements private
Initial value:
{
      this, "OutputMeasurements"}
Definition at line 113 of file PlanarSteppingAlgorithm.hpp.
View newest version in sPHENIX GitHub at line 113 of file PlanarSteppingAlgorithm.hpp
Referenced by PlanarSteppingAlgorithm().
WriteDataHandle<IndexMultimap<Index> > ActsExamples::PlanarSteppingAlgorithm::m_outputMeasurementSimHitsMap private
Initial value:
{
      this, "OutputMeasurementSimHitsMap"}
Definition at line 119 of file PlanarSteppingAlgorithm.hpp.
View newest version in sPHENIX GitHub at line 119 of file PlanarSteppingAlgorithm.hpp
Referenced by PlanarSteppingAlgorithm().
WriteDataHandle<GeometryIdMultiset<IndexSourceLink> > ActsExamples::PlanarSteppingAlgorithm::m_outputSourceLinks private
Initial value:
{
      this, "OutputSourceLinks"}
Definition at line 107 of file PlanarSteppingAlgorithm.hpp.
View newest version in sPHENIX GitHub at line 107 of file PlanarSteppingAlgorithm.hpp
Referenced by PlanarSteppingAlgorithm().
The documentation for this exception was generated from the following files:
acts/blob/sPHENIX/Examples/Algorithms/Digitization/include/ActsExamples/Digitization/PlanarSteppingAlgorithm.hpp
acts/blob/sPHENIX/Examples/Algorithms/Digitization/src/PlanarSteppingAlgorithm.cpp