Analysis Software: pi0EtaByEta Class Reference
pi0EtaByEta Class Reference
#include <coresoftware/blob/master/calibrations/calorimeter/calo_emc_pi0_tbt/pi0EtaByEta.h>
Public Member Functions
pi0EtaByEta (const std::string &name="pi0EtaByEta", const std::string &fname="MyNtuple.root")
constructor
virtual ~pi0EtaByEta ()
destructor
int Init (PHCompositeNode *)
full initialization
int process_event (PHCompositeNode *)
event processing method
int End (PHCompositeNode *)
end of run method
int process_g4hits (PHCompositeNode *)
int process_g4cells (PHCompositeNode *)
int process_towers (PHCompositeNode *)
int process_clusters (PHCompositeNode *)
void Detector (const std::string &name)
void set_timing_cut_width (const int t)
void set_vertex_cut (const float v)
void apply_vertex_cut (bool Vtx_cut)
TF1 * fitHistogram (TH1 *h)
void fitEtaSlices (const std::string &infile, const std::string &outfile, const std::string &cdbFile)
Public Member Functions inherited from SubsysReco
~SubsysReco () override
virtual int EndRun (const int)
Called at the end of each run.
virtual int InitRun (PHCompositeNode *)
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
void Print (const std::string &="ALL") const override
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Protected Member Functions
int Getpeaktime (TH1 *h)
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Protected Member Functions inherited from Fun4AllBase
Fun4AllBase (const std::string &name="NONAME")
Protected Attributes
std::string detector
std::string outfilename
std::vector< float > m_energy
std::vector< int > m_etabin
std::vector< int > m_phibin
std::vector< int > m_time
std::vector< float > m_hcalin_energy
std::vector< int > m_hcalin_etabin
std::vector< int > m_hcalin_phibin
std::vector< int > m_hcalin_time
std::vector< float > m_hcalout_energy
std::vector< int > m_hcalout_etabin
std::vector< int > m_hcalout_phibin
std::vector< int > m_hcalout_time
std::vector< float > m_zdc_energy
std::vector< int > m_zdc_index
std::vector< int > m_zdc_side
std::vector< float > m_bbc_energy
std::vector< int > m_bbc_type
std::vector< int > m_bbc_side
std::array< TH1 *, 96 > h_mass_eta_lt {}
int _eventcounter {0}
int _range {1}
float _vz {0.}
float target_pi0_mass {0.152}
bool m_vtxCut {false}
bool dynMaskClus {false}
Fun4AllHistoManager * hm {nullptr}
TFile * outfile {nullptr}
TH2 * h_emcal_mbd_correlation {nullptr}
TH2 * h_ohcal_mbd_correlation {nullptr}
TH2 * h_ihcal_mbd_correlation {nullptr}
TH2 * h_emcal_hcal_correlation {nullptr}
TH2 * h_emcal_zdc_correlation {nullptr}
TH1 * h_InvMass {nullptr}
TH1 * h_InvMassMix {nullptr}
TH2 * h_cemc_etaphi {nullptr}
TH2 * h_hcalin_etaphi {nullptr}
TH2 * h_hcalout_etaphi {nullptr}
TH2 * h_cemc_etaphi_wQA {nullptr}
TH2 * h_hcalin_etaphi_wQA {nullptr}
TH2 * h_hcalout_etaphi_wQA {nullptr}
TH1 * h_totalzdc_e {nullptr}
TProfile2D * h_cemc_etaphi_time {nullptr}
TProfile2D * h_hcalin_etaphi_time {nullptr}
TProfile2D * h_hcalout_etaphi_time {nullptr}
TProfile2D * h_cemc_etaphi_badChi2 {nullptr}
TProfile2D * h_hcalin_etaphi_badChi2 {nullptr}
TProfile2D * h_hcalout_etaphi_badChi2 {nullptr}
TH1 * hzdctime {nullptr}
TH1 * hmbdtime {nullptr}
TH1 * hemcaltime {nullptr}
TH1 * hihcaltime {nullptr}
TH1 * hohcaltime {nullptr}
TH1 * hzdctime_cut {nullptr}
TH1 * hmbdtime_cut {nullptr}
TH1 * hemcaltime_cut {nullptr}
TH1 * hihcaltime_cut {nullptr}
TH1 * hohcaltime_cut {nullptr}
TH1 * hvtx_z_raw {nullptr}
TH1 * hvtx_z_cut {nullptr}
TH1 * hzdcSouthraw {nullptr}
TH1 * hzdcNorthraw {nullptr}
TH1 * hzdcSouthcalib {nullptr}
TH1 * hzdcNorthcalib {nullptr}
TH1 * h_clusE {nullptr}
TH2 * h_etaphi_clus {nullptr}
TNtuple * g4hitntuple {nullptr}
TNtuple * g4cellntuple {nullptr}
TTree * towerntuple {nullptr}
TNtuple * clusterntuple {nullptr}
TH1 * h_pt1 {nullptr}
TH1 * h_pt2 {nullptr}
TH1 * h_nclusters {nullptr}
TH1 * h_emcal_e_eta {nullptr}
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = std::numeric_limits<int>::max() - 10
}
Detailed Description
Definition at line 22 of file pi0EtaByEta.h.
View newest version in sPHENIX GitHub at line 22 of file pi0EtaByEta.h
Constructor & Destructor Documentation
pi0EtaByEta::pi0EtaByEta (const std::string & name = "pi0EtaByEta", const std::string & fname = "MyNtuple.root")
constructor
Definition at line 40 of file pi0EtaByEta.cc.
View newest version in sPHENIX GitHub at line 40 of file pi0EtaByEta.cc
References h_mass_eta_lt.
pi0EtaByEta::~pi0EtaByEta () virtual
destructor
Definition at line 48 of file pi0EtaByEta.cc.
View newest version in sPHENIX GitHub at line 48 of file pi0EtaByEta.cc
References clusterntuple, g4cellntuple, g4hitntuple, hm, and towerntuple.
Member Function Documentation
void pi0EtaByEta::apply_vertex_cut (bool Vtx_cut) inline
Definition at line 48 of file pi0EtaByEta.h.
View newest version in sPHENIX GitHub at line 48 of file pi0EtaByEta.h
References m_vtxCut.
Referenced by Fun4All_EMCal().
void pi0EtaByEta::Detector (const std::string & name) inline
Definition at line 45 of file pi0EtaByEta.h.
View newest version in sPHENIX GitHub at line 45 of file pi0EtaByEta.h
References perf_headwind::name.
int pi0EtaByEta::End (PHCompositeNode *) virtual
end of run method
Reimplemented from SubsysReco.
Definition at line 383 of file pi0EtaByEta.cc.
View newest version in sPHENIX GitHub at line 383 of file pi0EtaByEta.cc
References Fun4AllHistoManager::dumpHistos(), hm, outfile, and outfilename.
void pi0EtaByEta::fitEtaSlices (const std::string & infile, const std::string & outfile, const std::string & cdbFile)
Definition at line 422 of file pi0EtaByEta.cc.
View newest version in sPHENIX GitHub at line 422 of file pi0EtaByEta.cc
References TowerInfoDefs::encode_emcal(), fitHistogram(), CDBTTree::GetFloatValue(), GetParameter(), i, j, and target_pi0_mass.
Referenced by doFitAndCalibUpdate().
TF1 * pi0EtaByEta::fitHistogram (TH1 * h)
Definition at line 394 of file pi0EtaByEta.cc.
View newest version in sPHENIX GitHub at line 394 of file pi0EtaByEta.cc
References fitFunc, and target_pi0_mass.
Referenced by fitEtaSlices().
int pi0EtaByEta::Getpeaktime (TH1 * h) protected
int pi0EtaByEta::Init (PHCompositeNode *) virtual
full initialization
Reimplemented from SubsysReco.
Definition at line 57 of file pi0EtaByEta.cc.
View newest version in sPHENIX GitHub at line 57 of file pi0EtaByEta.cc
References h_cemc_etaphi, h_clusE, h_emcal_e_eta, h_etaphi_clus, h_InvMass, h_InvMassMix, h_mass_eta_lt, h_nclusters, h_pt1, h_pt2, hm, i, Fun4AllBase::Name(), outfile, and outfilename.
int pi0EtaByEta::process_clusters (PHCompositeNode *)
int pi0EtaByEta::process_event (PHCompositeNode * topNode) virtual
event processing method
Reimplemented from SubsysReco.
Definition at line 90 of file pi0EtaByEta.cc.
View newest version in sPHENIX GitHub at line 90 of file pi0EtaByEta.cc
References _eventcounter, Fun4AllReturnCodes::EVENT_OK, and process_towers().
int pi0EtaByEta::process_g4cells (PHCompositeNode *)
int pi0EtaByEta::process_g4hits (PHCompositeNode *)
int pi0EtaByEta::process_towers (PHCompositeNode * topNode)
Definition at line 99 of file pi0EtaByEta.cc.
View newest version in sPHENIX GitHub at line 99 of file pi0EtaByEta.cc
References _eventcounter, GlobalVertexMap::begin(), channel(), TowerInfoContainer::decode_key(), dynMaskClus, GlobalVertexMap::empty(), TowerInfoDefs::encode_emcal(), TowerInfoContainer::encode_key(), energy, Fun4AllReturnCodes::EVENT_OK, RawTowerGeom::get_bineta(), RawTowerGeom::get_binphi(), RawCluster::get_chi2(), TowerInfo::get_energy(), TowerInfo::get_isBadChi2(), TowerInfoContainer::get_tower_at_channel(), RawTowerGeomContainer::get_tower_geometry(), RawCluster::get_towers(), GlobalVertex::get_z(), RawClusterContainer::getClusters(), RawClusterUtility::GetECoreVec(), TowerInfoContainer::getTowerEtaBin(), TowerInfoContainer::getTowerPhiBin(), h_cemc_etaphi, h_clusE, h_emcal_e_eta, h_etaphi_clus, h_InvMass, h_mass_eta_lt, h_nclusters, h_pt1, h_pt2, i, Fun4AllBase::Name(), PHWHERE, TowerInfoContainer::size(), and size.
Referenced by process_event().
void pi0EtaByEta::set_timing_cut_width (const int t) inline
Definition at line 46 of file pi0EtaByEta.h.
View newest version in sPHENIX GitHub at line 46 of file pi0EtaByEta.h
References _range, and t.
Referenced by Fun4All_EMCal().
void pi0EtaByEta::set_vertex_cut (const float v) inline
Definition at line 47 of file pi0EtaByEta.h.
View newest version in sPHENIX GitHub at line 47 of file pi0EtaByEta.h
References _vz, and testSigmaEff::v.
Referenced by Fun4All_EMCal().
Member Data Documentation
int pi0EtaByEta::_eventcounter {0} protected
Definition at line 83 of file pi0EtaByEta.h.
View newest version in sPHENIX GitHub at line 83 of file pi0EtaByEta.h
Referenced by process_event(), and process_towers().
int pi0EtaByEta::_range {1} protected
Definition at line 84 of file pi0EtaByEta.h.
View newest version in sPHENIX GitHub at line 84 of file pi0EtaByEta.h
Referenced by set_timing_cut_width().
float pi0EtaByEta::_vz {0.} protected
Definition at line 86 of file pi0EtaByEta.h.
View newest version in sPHENIX GitHub at line 86 of file pi0EtaByEta.h
Referenced by set_vertex_cut().
TNtuple* pi0EtaByEta::clusterntuple {nullptr} protected
Definition at line 145 of file pi0EtaByEta.h.
View newest version in sPHENIX GitHub at line 145 of file pi0EtaByEta.h
Referenced by ~pi0EtaByEta().
std::string pi0EtaByEta::detector protected
Definition at line 55 of file pi0EtaByEta.h.
View newest version in sPHENIX GitHub at line 55 of file pi0EtaByEta.h
bool pi0EtaByEta::dynMaskClus {false} protected
Definition at line 90 of file pi0EtaByEta.h.
View newest version in sPHENIX GitHub at line 90 of file pi0EtaByEta.h
Referenced by process_towers().
TNtuple* pi0EtaByEta::g4cellntuple {nullptr} protected
Definition at line 143 of file pi0EtaByEta.h.
View newest version in sPHENIX GitHub at line 143 of file pi0EtaByEta.h
Referenced by ~pi0EtaByEta().
TNtuple* pi0EtaByEta::g4hitntuple {nullptr} protected
Definition at line 142 of file pi0EtaByEta.h.
View newest version in sPHENIX GitHub at line 142 of file pi0EtaByEta.h
Referenced by ~pi0EtaByEta().
TH2* pi0EtaByEta::h_cemc_etaphi {nullptr} protected
Definition at line 103 of file pi0EtaByEta.h.
View newest version in sPHENIX GitHub at line 103 of file pi0EtaByEta.h
Referenced by Init(), and process_towers().
TProfile2D* pi0EtaByEta::h_cemc_etaphi_badChi2 {nullptr} protected
Definition at line 115 of file pi0EtaByEta.h.
View newest version in sPHENIX GitHub at line 115 of file pi0EtaByEta.h
TProfile2D* pi0EtaByEta::h_cemc_etaphi_time {nullptr} protected
Definition at line 111 of file pi0EtaByEta.h.
View newest version in sPHENIX GitHub at line 111 of file pi0EtaByEta.h
TH2* pi0EtaByEta::h_cemc_etaphi_wQA {nullptr} protected
Definition at line 106 of file pi0EtaByEta.h.
View newest version in sPHENIX GitHub at line 106 of file pi0EtaByEta.h
TH1* pi0EtaByEta::h_clusE {nullptr} protected
Definition at line 139 of file pi0EtaByEta.h.
View newest version in sPHENIX GitHub at line 139 of file pi0EtaByEta.h
Referenced by Init(), and process_towers().
TH1* pi0EtaByEta::h_emcal_e_eta {nullptr} protected
Definition at line 150 of file pi0EtaByEta.h.
View newest version in sPHENIX GitHub at line 150 of file pi0EtaByEta.h
Referenced by Init(), and process_towers().
TH2* pi0EtaByEta::h_emcal_hcal_correlation {nullptr} protected
Definition at line 97 of file pi0EtaByEta.h.
View newest version in sPHENIX GitHub at line 97 of file pi0EtaByEta.h
TH2* pi0EtaByEta::h_emcal_mbd_correlation {nullptr} protected
Definition at line 94 of file pi0EtaByEta.h.
View newest version in sPHENIX GitHub at line 94 of file pi0EtaByEta.h
TH2* pi0EtaByEta::h_emcal_zdc_correlation {nullptr} protected
Definition at line 98 of file pi0EtaByEta.h.
View newest version in sPHENIX GitHub at line 98 of file pi0EtaByEta.h
TH2* pi0EtaByEta::h_etaphi_clus {nullptr} protected
Definition at line 140 of file pi0EtaByEta.h.
View newest version in sPHENIX GitHub at line 140 of file pi0EtaByEta.h
Referenced by Init(), and process_towers().
TH2* pi0EtaByEta::h_hcalin_etaphi {nullptr} protected
Definition at line 104 of file pi0EtaByEta.h.
View newest version in sPHENIX GitHub at line 104 of file pi0EtaByEta.h
TProfile2D* pi0EtaByEta::h_hcalin_etaphi_badChi2 {nullptr} protected
Definition at line 116 of file pi0EtaByEta.h.
View newest version in sPHENIX GitHub at line 116 of file pi0EtaByEta.h
TProfile2D* pi0EtaByEta::h_hcalin_etaphi_time {nullptr} protected
Definition at line 112 of file pi0EtaByEta.h.
View newest version in sPHENIX GitHub at line 112 of file pi0EtaByEta.h
TH2* pi0EtaByEta::h_hcalin_etaphi_wQA {nullptr} protected
Definition at line 107 of file pi0EtaByEta.h.
View newest version in sPHENIX GitHub at line 107 of file pi0EtaByEta.h
TH2* pi0EtaByEta::h_hcalout_etaphi {nullptr} protected
Definition at line 105 of file pi0EtaByEta.h.
View newest version in sPHENIX GitHub at line 105 of file pi0EtaByEta.h
TProfile2D* pi0EtaByEta::h_hcalout_etaphi_badChi2 {nullptr} protected
Definition at line 117 of file pi0EtaByEta.h.
View newest version in sPHENIX GitHub at line 117 of file pi0EtaByEta.h
TProfile2D* pi0EtaByEta::h_hcalout_etaphi_time {nullptr} protected
Definition at line 113 of file pi0EtaByEta.h.
View newest version in sPHENIX GitHub at line 113 of file pi0EtaByEta.h
TH2* pi0EtaByEta::h_hcalout_etaphi_wQA {nullptr} protected
Definition at line 108 of file pi0EtaByEta.h.
View newest version in sPHENIX GitHub at line 108 of file pi0EtaByEta.h
TH2* pi0EtaByEta::h_ihcal_mbd_correlation {nullptr} protected
Definition at line 96 of file pi0EtaByEta.h.
View newest version in sPHENIX GitHub at line 96 of file pi0EtaByEta.h
TH1* pi0EtaByEta::h_InvMass {nullptr} protected
Definition at line 100 of file pi0EtaByEta.h.
View newest version in sPHENIX GitHub at line 100 of file pi0EtaByEta.h
Referenced by Init(), and process_towers().
TH1* pi0EtaByEta::h_InvMassMix {nullptr} protected
Definition at line 101 of file pi0EtaByEta.h.
View newest version in sPHENIX GitHub at line 101 of file pi0EtaByEta.h
Referenced by Init().
std::array<TH1*, 96> pi0EtaByEta::h_mass_eta_lt {} protected
Definition at line 81 of file pi0EtaByEta.h.
View newest version in sPHENIX GitHub at line 81 of file pi0EtaByEta.h
Referenced by Init(), pi0EtaByEta(), and process_towers().
TH1* pi0EtaByEta::h_nclusters {nullptr} protected
Definition at line 149 of file pi0EtaByEta.h.
View newest version in sPHENIX GitHub at line 149 of file pi0EtaByEta.h
Referenced by Init(), and process_towers().
TH2* pi0EtaByEta::h_ohcal_mbd_correlation {nullptr} protected
Definition at line 95 of file pi0EtaByEta.h.
View newest version in sPHENIX GitHub at line 95 of file pi0EtaByEta.h
TH1* pi0EtaByEta::h_pt1 {nullptr} protected
Definition at line 147 of file pi0EtaByEta.h.
View newest version in sPHENIX GitHub at line 147 of file pi0EtaByEta.h
Referenced by Init(), and process_towers().
TH1* pi0EtaByEta::h_pt2 {nullptr} protected
Definition at line 148 of file pi0EtaByEta.h.
View newest version in sPHENIX GitHub at line 148 of file pi0EtaByEta.h
Referenced by Init(), and process_towers().
TH1* pi0EtaByEta::h_totalzdc_e {nullptr} protected
Definition at line 109 of file pi0EtaByEta.h.
View newest version in sPHENIX GitHub at line 109 of file pi0EtaByEta.h
TH1* pi0EtaByEta::hemcaltime {nullptr} protected
Definition at line 121 of file pi0EtaByEta.h.
View newest version in sPHENIX GitHub at line 121 of file pi0EtaByEta.h
TH1* pi0EtaByEta::hemcaltime_cut {nullptr} protected
Definition at line 127 of file pi0EtaByEta.h.
View newest version in sPHENIX GitHub at line 127 of file pi0EtaByEta.h
TH1* pi0EtaByEta::hihcaltime {nullptr} protected
Definition at line 122 of file pi0EtaByEta.h.
View newest version in sPHENIX GitHub at line 122 of file pi0EtaByEta.h
TH1* pi0EtaByEta::hihcaltime_cut {nullptr} protected
Definition at line 128 of file pi0EtaByEta.h.
View newest version in sPHENIX GitHub at line 128 of file pi0EtaByEta.h
Fun4AllHistoManager* pi0EtaByEta::hm {nullptr} protected
Definition at line 92 of file pi0EtaByEta.h.
View newest version in sPHENIX GitHub at line 92 of file pi0EtaByEta.h
Referenced by End(), Init(), and ~pi0EtaByEta().
TH1* pi0EtaByEta::hmbdtime {nullptr} protected
Definition at line 120 of file pi0EtaByEta.h.
View newest version in sPHENIX GitHub at line 120 of file pi0EtaByEta.h
TH1* pi0EtaByEta::hmbdtime_cut {nullptr} protected
Definition at line 126 of file pi0EtaByEta.h.
View newest version in sPHENIX GitHub at line 126 of file pi0EtaByEta.h
TH1* pi0EtaByEta::hohcaltime {nullptr} protected
Definition at line 123 of file pi0EtaByEta.h.
View newest version in sPHENIX GitHub at line 123 of file pi0EtaByEta.h
TH1* pi0EtaByEta::hohcaltime_cut {nullptr} protected
Definition at line 129 of file pi0EtaByEta.h.
View newest version in sPHENIX GitHub at line 129 of file pi0EtaByEta.h
TH1* pi0EtaByEta::hvtx_z_cut {nullptr} protected
Definition at line 132 of file pi0EtaByEta.h.
View newest version in sPHENIX GitHub at line 132 of file pi0EtaByEta.h
TH1* pi0EtaByEta::hvtx_z_raw {nullptr} protected
Definition at line 131 of file pi0EtaByEta.h.
View newest version in sPHENIX GitHub at line 131 of file pi0EtaByEta.h
TH1* pi0EtaByEta::hzdcNorthcalib {nullptr} protected
Definition at line 137 of file pi0EtaByEta.h.
View newest version in sPHENIX GitHub at line 137 of file pi0EtaByEta.h
TH1* pi0EtaByEta::hzdcNorthraw {nullptr} protected
Definition at line 135 of file pi0EtaByEta.h.
View newest version in sPHENIX GitHub at line 135 of file pi0EtaByEta.h
TH1* pi0EtaByEta::hzdcSouthcalib {nullptr} protected
Definition at line 136 of file pi0EtaByEta.h.
View newest version in sPHENIX GitHub at line 136 of file pi0EtaByEta.h
TH1* pi0EtaByEta::hzdcSouthraw {nullptr} protected
Definition at line 134 of file pi0EtaByEta.h.
View newest version in sPHENIX GitHub at line 134 of file pi0EtaByEta.h
TH1* pi0EtaByEta::hzdctime {nullptr} protected
Definition at line 119 of file pi0EtaByEta.h.
View newest version in sPHENIX GitHub at line 119 of file pi0EtaByEta.h
TH1* pi0EtaByEta::hzdctime_cut {nullptr} protected
Definition at line 125 of file pi0EtaByEta.h.
View newest version in sPHENIX GitHub at line 125 of file pi0EtaByEta.h
std::vector<float> pi0EtaByEta::m_bbc_energy protected
Definition at line 77 of file pi0EtaByEta.h.
View newest version in sPHENIX GitHub at line 77 of file pi0EtaByEta.h
std::vector<int> pi0EtaByEta::m_bbc_side protected
Definition at line 79 of file pi0EtaByEta.h.
View newest version in sPHENIX GitHub at line 79 of file pi0EtaByEta.h
std::vector<int> pi0EtaByEta::m_bbc_type protected
Definition at line 78 of file pi0EtaByEta.h.
View newest version in sPHENIX GitHub at line 78 of file pi0EtaByEta.h
std::vector<float> pi0EtaByEta::m_energy protected
Definition at line 58 of file pi0EtaByEta.h.
View newest version in sPHENIX GitHub at line 58 of file pi0EtaByEta.h
std::vector<int> pi0EtaByEta::m_etabin protected
Definition at line 59 of file pi0EtaByEta.h.
View newest version in sPHENIX GitHub at line 59 of file pi0EtaByEta.h
std::vector<float> pi0EtaByEta::m_hcalin_energy protected
Definition at line 63 of file pi0EtaByEta.h.
View newest version in sPHENIX GitHub at line 63 of file pi0EtaByEta.h
std::vector<int> pi0EtaByEta::m_hcalin_etabin protected
Definition at line 64 of file pi0EtaByEta.h.
View newest version in sPHENIX GitHub at line 64 of file pi0EtaByEta.h
std::vector<int> pi0EtaByEta::m_hcalin_phibin protected
Definition at line 65 of file pi0EtaByEta.h.
View newest version in sPHENIX GitHub at line 65 of file pi0EtaByEta.h
std::vector<int> pi0EtaByEta::m_hcalin_time protected
Definition at line 66 of file pi0EtaByEta.h.
View newest version in sPHENIX GitHub at line 66 of file pi0EtaByEta.h
std::vector<float> pi0EtaByEta::m_hcalout_energy protected
Definition at line 68 of file pi0EtaByEta.h.
View newest version in sPHENIX GitHub at line 68 of file pi0EtaByEta.h
std::vector<int> pi0EtaByEta::m_hcalout_etabin protected
Definition at line 69 of file pi0EtaByEta.h.
View newest version in sPHENIX GitHub at line 69 of file pi0EtaByEta.h
std::vector<int> pi0EtaByEta::m_hcalout_phibin protected
Definition at line 70 of file pi0EtaByEta.h.
View newest version in sPHENIX GitHub at line 70 of file pi0EtaByEta.h
std::vector<int> pi0EtaByEta::m_hcalout_time protected
Definition at line 71 of file pi0EtaByEta.h.
View newest version in sPHENIX GitHub at line 71 of file pi0EtaByEta.h
std::vector<int> pi0EtaByEta::m_phibin protected
Definition at line 60 of file pi0EtaByEta.h.
View newest version in sPHENIX GitHub at line 60 of file pi0EtaByEta.h
std::vector<int> pi0EtaByEta::m_time protected
Definition at line 61 of file pi0EtaByEta.h.
View newest version in sPHENIX GitHub at line 61 of file pi0EtaByEta.h
bool pi0EtaByEta::m_vtxCut {false} protected
Definition at line 89 of file pi0EtaByEta.h.
View newest version in sPHENIX GitHub at line 89 of file pi0EtaByEta.h
Referenced by apply_vertex_cut().
std::vector<float> pi0EtaByEta::m_zdc_energy protected
Definition at line 73 of file pi0EtaByEta.h.
View newest version in sPHENIX GitHub at line 73 of file pi0EtaByEta.h
std::vector<int> pi0EtaByEta::m_zdc_index protected
Definition at line 74 of file pi0EtaByEta.h.
View newest version in sPHENIX GitHub at line 74 of file pi0EtaByEta.h
std::vector<int> pi0EtaByEta::m_zdc_side protected
Definition at line 75 of file pi0EtaByEta.h.
View newest version in sPHENIX GitHub at line 75 of file pi0EtaByEta.h
TFile* pi0EtaByEta::outfile {nullptr} protected
Definition at line 93 of file pi0EtaByEta.h.
View newest version in sPHENIX GitHub at line 93 of file pi0EtaByEta.h
Referenced by End(), and Init().
std::string pi0EtaByEta::outfilename protected
Definition at line 56 of file pi0EtaByEta.h.
View newest version in sPHENIX GitHub at line 56 of file pi0EtaByEta.h
Referenced by End(), and Init().
float pi0EtaByEta::target_pi0_mass {0.152} protected
Definition at line 87 of file pi0EtaByEta.h.
View newest version in sPHENIX GitHub at line 87 of file pi0EtaByEta.h
Referenced by fitEtaSlices(), and fitHistogram().
TTree* pi0EtaByEta::towerntuple {nullptr} protected
Definition at line 144 of file pi0EtaByEta.h.
View newest version in sPHENIX GitHub at line 144 of file pi0EtaByEta.h
Referenced by ~pi0EtaByEta().
The documentation for this class was generated from the following files:
coresoftware/blob/master/calibrations/calorimeter/calo_emc_pi0_tbt/pi0EtaByEta.h
coresoftware/blob/master/calibrations/calorimeter/calo_emc_pi0_tbt/pi0EtaByEta.cc