Analysis Software: Acts::IntegrationTest Namespace Reference
Acts::IntegrationTest Namespace Reference
Classes
struct StreamWrapper
Typedefs
using Box = Acts::Volume::BoundingBox
using Ray = Acts::Ray< double, 3 >
using BFieldType = InterpolatedBFieldMap
using EigenStepperType = EigenStepper<>
using AtlasStepperType = AtlasStepper
using EigenPropagatorType = Propagator< EigenStepperType >
using AtlasPropagatorType = Propagator< AtlasStepperType >
Functions
BOOST_DATA_TEST_CASE (bvhnavigation_test, bdata::random((bdata::seed=7, bdata::engine=std::mt19937(), bdata::distribution=std::uniform_real_distribution<>(-5, 5)))^bdata::random((bdata::seed=2, bdata::engine=std::mt19937(), bdata::distribution=std::uniform_real_distribution<>(-M_PI, M_PI)))^bdata::random((bdata::seed=3, bdata::engine=std::mt19937(), bdata::distribution=std::uniform_real_distribution<>(-100, 100)))^bdata::random((bdata::seed=4, bdata::engine=std::mt19937(), bdata::distribution=std::uniform_real_distribution<>(-100, 100)))^bdata::random((bdata::seed=5, bdata::engine=std::mt19937(), bdata::distribution=std::uniform_real_distribution<>(-100, 100)))^bdata::xrange(NTESTS), eta, phi, x, y, z, index)
auto makeFieldMap (const SolenoidBField &field)
StreamWrapper valid (std::ofstream("magfield_lookup.csv"))
BOOST_DATA_TEST_CASE (solenoid_interpolated_bfield_comparison, bdata::random((bdata::seed=1, bdata::engine=std::mt19937(), bdata::distribution=std::uniform_real_distribution<>(1.5 *(-L/2.), 1.5 *L/2.)))^bdata::random((bdata::seed=2, bdata::engine=std::mt19937(), bdata::distribution=std::uniform_real_distribution<>(0, R *1.5)))^bdata::random((bdata::seed=3, bdata::engine=std::mt19937(), bdata::distribution=std::uniform_real_distribution<>(-M_PI, M_PI)))^bdata::xrange(ntests), z, r, phi, index)
InterpolatedBFieldMap::FieldMapper< 3, 3 > readFieldXYZ (std::function< size_t(std::array< size_t, 3 > binsXYZ, std::array< size_t, 3 > nBinsXYZ)> localToGlobalBin, std::string fieldMapFile="Field.txt", double lengthUnit=1., double BFieldUnit=1., size_t nPoints=100000, bool firstOctant=false)
std::shared_ptr< const
InterpolatedBFieldMap > atlasBField (std::string fieldMapFile="Field.txt")
EigenPropagatorType epropagator (std::move(estepper))
AtlasPropagatorType apropagator (std::move(astepper))
Variables
GeometryContext tgContext = GeometryContext()
MagneticFieldContext mfContext = MagneticFieldContext()
Test::CubicBVHTrackingGeometry grid (NBOXES, 1000, 5)
auto volumes = grid.volumes
auto tg = grid.trackingGeometry
const double L = 5.8_m
const double R = (2.56 + 2.46) * 0.5 * 0.5_m
const size_t nCoils = 1154
const double bMagCenter = 2_T
const size_t nBinsR = 150
const size_t nBinsZ = 200
Acts::SolenoidBField bSolenoidField ({R, L, nCoils, bMagCenter})
auto bFieldMap = makeFieldMap(bSolenoidField)
auto bCache = bFieldMap.makeCache(Acts::MagneticFieldContext{})
const int ntests = 10000
double Bz = 2_T
auto bField = atlasBField("Field.txt")
EigenStepperType estepper (bField)
AtlasStepperType astepper (bField)
Detailed Description
Get the ATLAS field from : http://acts.web.cern.ch/ACTS/data/AtlasField/AtlasField.tar.gz to run this
Typedef Documentation
using Acts::IntegrationTest::AtlasPropagatorType = typedef Propagator<AtlasStepperType>
Definition at line 112 of file PropagationTestsAtlasField.cpp.
View newest version in sPHENIX GitHub at line 112 of file PropagationTestsAtlasField.cpp
using Acts::IntegrationTest::AtlasStepperType = typedef AtlasStepper
Definition at line 110 of file PropagationTestsAtlasField.cpp.
View newest version in sPHENIX GitHub at line 110 of file PropagationTestsAtlasField.cpp
using Acts::IntegrationTest::BFieldType = typedef InterpolatedBFieldMap
Definition at line 108 of file PropagationTestsAtlasField.cpp.
View newest version in sPHENIX GitHub at line 108 of file PropagationTestsAtlasField.cpp
using Acts::IntegrationTest::Box = typedef Acts::Volume::BoundingBox
Definition at line 15 of file BVHNavigationTest.cpp.
View newest version in sPHENIX GitHub at line 15 of file BVHNavigationTest.cpp
using Acts::IntegrationTest::EigenPropagatorType = typedef Propagator<EigenStepperType>
Definition at line 111 of file PropagationTestsAtlasField.cpp.
View newest version in sPHENIX GitHub at line 111 of file PropagationTestsAtlasField.cpp
using Acts::IntegrationTest::EigenStepperType = typedef EigenStepper<>
Definition at line 109 of file PropagationTestsAtlasField.cpp.
View newest version in sPHENIX GitHub at line 109 of file PropagationTestsAtlasField.cpp
using Acts::IntegrationTest::Ray = typedef Acts::Ray<double, 3>
Definition at line 16 of file BVHNavigationTest.cpp.
View newest version in sPHENIX GitHub at line 16 of file BVHNavigationTest.cpp
Function Documentation
AtlasPropagatorType Acts::IntegrationTest::apropagator (std:: moveastepper)
std::shared_ptr<const InterpolatedBFieldMap> Acts::IntegrationTest::atlasBField (std::string fieldMapFile = "Field.txt")
Definition at line 85 of file PropagationTestsAtlasField.cpp.
View newest version in sPHENIX GitHub at line 85 of file PropagationTestsAtlasField.cpp
References filter::config, ActsExamples::HepMC3Event::lengthUnit(), mapper(), Acts::UnitConstants::mm, testing::internal::move(), readFieldXYZ(), and Acts::UnitConstants::T.
Acts::IntegrationTest::BOOST_DATA_TEST_CASE (bvhnavigation_test , bdata:: random(bdata::seed=7, bdata::engine=std::mt19937(),bdata::distribution=std::uniform_real_distribution<>(-5,5)))^bdata::random((bdata::seed=2, bdata::engine=std::mt19937(),bdata::distribution=std::uniform_real_distribution<>(-M_PI, M_PI)))^bdata::random((bdata::seed=3, bdata::engine=std::mt19937(),bdata::distribution=std::uniform_real_distribution<>(-100, 100)))^bdata::random((bdata::seed=4, bdata::engine=std::mt19937(),bdata::distribution=std::uniform_real_distribution<>(-100, 100)))^bdata::random((bdata::seed=5, bdata::engine=std::mt19937(),bdata::distribution=std::uniform_real_distribution<>(-100, 100)))^bdata::xrange(NTESTS, eta , phi , x , y , z , index)
Definition at line 26 of file BVHNavigationTest.cpp.
View newest version in sPHENIX GitHub at line 26 of file BVHNavigationTest.cpp
Acts::IntegrationTest::BOOST_DATA_TEST_CASE (solenoid_interpolated_bfield_comparison , bdata:: random(bdata::seed=1, bdata::engine=std::mt19937(),bdata::distribution=std::uniform_real_distribution<>(1.5 *(-L/2.), 1.5 *L/2.)))^bdata::random((bdata::seed=2, bdata::engine=std::mt19937(),bdata::distribution=std::uniform_real_distribution<>(0, R *1.5)))^bdata::random((bdata::seed=3, bdata::engine=std::mt19937(),bdata::distribution=std::uniform_real_distribution<>(-M_PI, M_PI)))^bdata::xrange(ntests, z , r , phi , index)
Definition at line 100 of file InterpolatedSolenoidBFieldTest.cpp.
View newest version in sPHENIX GitHub at line 100 of file InterpolatedSolenoidBFieldTest.cpp
References bCache, bFieldMap, bSolenoidField, CHECK_CLOSE_REL, Acts::SolenoidBField::getField(), index, L, Acts::IntegrationTest::StreamWrapper::m_ofstr, ActsTests::PropagationDatasets::phi, Acts::Test::pos, R, physmon_track_finding_ttbar::r, Acts::UnitConstants::T, valid(), and physmon_track_finding_ttbar::z.
EigenPropagatorType Acts::IntegrationTest::epropagator (std:: moveestepper)
Referenced by Acts::Test::BOOST_DATA_TEST_CASE().
auto Acts::IntegrationTest::makeFieldMap (const SolenoidBField & field)
Definition at line 43 of file InterpolatedSolenoidBFieldTest.cpp.
View newest version in sPHENIX GitHub at line 43 of file InterpolatedSolenoidBFieldTest.cpp
References ckf::field, grid(), i, index, j, L, nBinsR, nBinsZ, R, and Acts::solenoidFieldMap().
InterpolatedBFieldMap::FieldMapper<3, 3> Acts::IntegrationTest::readFieldXYZ (std::function< size_t(std::array< size_t, 3 > binsXYZ, std::array< size_t, 3 > nBinsXYZ)> localToGlobalBin, std::string fieldMapFile = "Field.txt", double lengthUnit = 1., double BFieldUnit = 1., size_t nPoints = 100000, bool firstOctant = false)
[1] Read in field map file
Definition at line 43 of file PropagationTestsAtlasField.cpp.
View newest version in sPHENIX GitHub at line 43 of file PropagationTestsAtlasField.cpp
References bField, in, ActsExamples::HepMC3Event::lengthUnit(), line, Acts::Test::tmp(), ambiguity_solver_full_chain::x, y, and physmon_track_finding_ttbar::z.
Referenced by atlasBField().
StreamWrapper Acts::IntegrationTest::valid (std:: ofstream"magfield_lookup.csv")
Referenced by ActsExamples::Sequencer::addElement(), Acts::Test::BOOST_AUTO_TEST_CASE(), BOOST_DATA_TEST_CASE(), Acts::Test::BOOST_FIXTURE_TEST_CASE(), calccorr(), and QAG4Util::interpolate().
Variable Documentation
AtlasStepperType Acts::IntegrationTest::astepper(bField)
auto Acts::IntegrationTest::bCache = bFieldMap.makeCache(Acts::MagneticFieldContext{})
Definition at line 87 of file InterpolatedSolenoidBFieldTest.cpp.
View newest version in sPHENIX GitHub at line 87 of file InterpolatedSolenoidBFieldTest.cpp
Referenced by accessRandom(), accessStepWise(), Acts::Test::BOOST_AUTO_TEST_CASE(), Acts::Test::BOOST_DATA_TEST_CASE(), BOOST_DATA_TEST_CASE(), ActsExamples::PrototracksToParameters::execute(), ActsExamples::TrackParamsEstimationAlgorithm::execute(), and ActsExamples::MagneticFieldWrapper::GetFieldValue().
auto Acts::IntegrationTest::bField = atlasBField("Field.txt")
Definition at line 114 of file PropagationTestsAtlasField.cpp.
View newest version in sPHENIX GitHub at line 114 of file PropagationTestsAtlasField.cpp
Referenced by Acts::Python::addOutput(), Acts::Python::addPropagation(), Acts::Python::addVertexing(), Acts::Test::BOOST_AUTO_TEST_CASE(), BOOST_AUTO_TEST_CASE(), Acts::Test::BOOST_DATA_TEST_CASE(), PHActsVertexFinder::findVertices(), PHActsInitialVertexFinder::findVertices(), PHActsVertexFitter::fitVertex(), main(), ActsExamples::makeMagneticFieldMapRzFromRoot(), ActsExamples::makeMagneticFieldMapRzFromText(), ActsExamples::makeMagneticFieldMapXyzFromRoot(), ActsExamples::makeMagneticFieldMapXyzFromText(), materialValidationExample(), propagationExample(), propagator_instatiation_test_function(), readFieldXYZ(), ActsExamples::RootBFieldWriter::run(), ActsExamples::CsvBFieldWriter::run(), Acts::Test::testJacobianToGlobal(), and Acts::EventDataView3DTest::testMultiTrajectory().
auto Acts::IntegrationTest::bFieldMap = makeFieldMap(bSolenoidField)
Definition at line 86 of file InterpolatedSolenoidBFieldTest.cpp.
View newest version in sPHENIX GitHub at line 86 of file InterpolatedSolenoidBFieldTest.cpp
Referenced by BOOST_DATA_TEST_CASE(), and main().
const double Acts::IntegrationTest::bMagCenter = 2_T
Definition at line 39 of file InterpolatedSolenoidBFieldTest.cpp.
View newest version in sPHENIX GitHub at line 39 of file InterpolatedSolenoidBFieldTest.cpp
Referenced by Acts::Python::addMagneticField(), and main().
Acts::SolenoidBField Acts::IntegrationTest::bSolenoidField({R, L, nCoils, bMagCenter})
Referenced by BOOST_DATA_TEST_CASE(), and main().
double Acts::IntegrationTest::Bz = 2_T
Definition at line 106 of file PropagationTestsAtlasField.cpp.
View newest version in sPHENIX GitHub at line 106 of file PropagationTestsAtlasField.cpp
Referenced by Acts::Python::addEDM4hep(), BOOST_AUTO_TEST_CASE(), Acts::Test::BOOST_DATA_TEST_CASE(), Acts::EDM4hepUtil::detail::convertTrackParametersFromEdm4hep(), Acts::EDM4hepUtil::detail::convertTrackParametersToEdm4hep(), PHG4OHCalSteppingAction::FieldChecker(), genfit::Field::get(), genfit::AbsBField::get(), SecondaryVertexFinder::getCircleXYTrack(), KFParticleBaseSIMD::GetDStoParticleB(), KFParticleBase::GetDStoPointB(), GPUTPCBaseTrackParam::GetKappa(), genfit::HelixTrackModel::HelixTrackModel(), ActsExamples::makeMagneticFieldMapRzFromRoot(), ActsExamples::makeMagneticFieldMapXyzFromRoot(), PHField2D::PHField2D(), PHField3DCylindrical::PHField3DCylindrical(), printBField(), PHGenFitTrackProjection::process_event(), ActsExamples::RootBFieldWriter::run(), ActsExamples::ScalableBField::setField(), KFParticleBase::TransportBz(), KFParticleBaseSIMD::TransportBz(), and GPUTPCTrackParam::TransportToX().
EigenStepperType Acts::IntegrationTest::estepper(bField)
Referenced by Acts::Test::BOOST_DATA_TEST_CASE().
Test::CubicBVHTrackingGeometry Acts::IntegrationTest::grid(NBOXES, 1000, 5)
const double Acts::IntegrationTest::L = 5.8_m
Definition at line 36 of file InterpolatedSolenoidBFieldTest.cpp.
View newest version in sPHENIX GitHub at line 36 of file InterpolatedSolenoidBFieldTest.cpp
Referenced by BOOST_DATA_TEST_CASE(), ThermalPartonSampler::brick_length_width(), ClassImpQ(), BEmcRecCEMC::CorrectShowerDepth(), oncsSub_iduppetdata::decode(), oncsSub_iduppetdata_v104::decode(), LaplaceSolution::Ephi(), LaplaceSolution::Er(), TSQLStatement::Execute(), TSQLStatement::ExecuteQuery(), Acts::Polyhedron::extent(), LaplaceSolution::Ez(), TSQLResultSet::First(), TSQLResultSet::GetLong(), PseudoJet::has_user_info(), ValueGen1::i5(), TrigFTF_GNN_EdgeState< external_spacepoint_t >::initialize(), INTT::LADDERS_(), LaplaceSolution::LaplaceSolution(), tinyxml2::XMLDocument::LoadFile(), main(), makeFieldMap(), noiPtrDbl::noiPtrDbl(), Acts::Sycl::detail::TripletSearch::operator()(), testing::internal::PrintAsCharLiteralTo(), testing::internal::PrintAsStringLiteralTo(), CosmicSpray::process_event(), FileF::Read(), LaplaceSolution::Rmn1(), LaplaceSolution::Rmn2(), LaplaceSolution::Rnk(), LaplaceSolution::RPrime(), ThermalPartonSampler::samplebrick(), HybridHadronization::set_spacetime_for_pythia_hadrons(), CaloRecoUtility::ShowerDepthCorrZVertex(), testing::internal::TEST(), TEST(), testing::gtest_printers_test::TEST(), testing::gmock_more_actions_test::TEST(), testing::gmock_matchers_test::TEST(), testing::gmock_generated_function_mockers_test::TEST_F(), ThermalPartonSampler::ThermalPartonSampler(), PseudoJet::user_info(), and testing::internal::WideStringToUtf8().
MagneticFieldContext Acts::IntegrationTest::mfContext = MagneticFieldContext()
Definition at line 19 of file BVHNavigationTest.cpp.
View newest version in sPHENIX GitHub at line 19 of file BVHNavigationTest.cpp
Referenced by Acts::Test::BOOST_AUTO_TEST_CASE(), BOOST_AUTO_TEST_CASE(), BOOST_DATA_TEST_CASE(), Acts::Test::BOOST_DATA_TEST_CASE(), main(), runMaterialMapping(), Acts::Test::runTest(), Acts::Test::testJacobianToGlobal(), and Acts::EventDataView3DTest::testMultiTrajectory().
const size_t Acts::IntegrationTest::nBinsR = 150
Definition at line 40 of file InterpolatedSolenoidBFieldTest.cpp.
View newest version in sPHENIX GitHub at line 40 of file InterpolatedSolenoidBFieldTest.cpp
Referenced by Acts::Test::BOOST_FIXTURE_TEST_CASE(), Acts::fieldMapRZ(), main(), makeFieldMap(), Acts::materialMapperRZ(), ActsExamples::RootBFieldWriter::run(), and Acts::solenoidFieldMap().
const size_t Acts::IntegrationTest::nBinsZ = 200
Definition at line 41 of file InterpolatedSolenoidBFieldTest.cpp.
View newest version in sPHENIX GitHub at line 41 of file InterpolatedSolenoidBFieldTest.cpp
Referenced by Acts::fieldMapRZ(), Acts::fieldMapXYZ(), main(), makeFieldMap(), Acts::materialMapperRZ(), Acts::materialMapperXYZ(), ActsExamples::RootBFieldWriter::run(), and Acts::solenoidFieldMap().
const size_t Acts::IntegrationTest::nCoils = 1154
Definition at line 38 of file InterpolatedSolenoidBFieldTest.cpp.
View newest version in sPHENIX GitHub at line 38 of file InterpolatedSolenoidBFieldTest.cpp
Referenced by Acts::Python::addMagneticField(), and main().
const int Acts::IntegrationTest::ntests = 10000
Definition at line 99 of file InterpolatedSolenoidBFieldTest.cpp.
View newest version in sPHENIX GitHub at line 99 of file InterpolatedSolenoidBFieldTest.cpp
const double Acts::IntegrationTest::R = (2.56 + 2.46) * 0.5 * 0.5_m
Definition at line 37 of file InterpolatedSolenoidBFieldTest.cpp.
View newest version in sPHENIX GitHub at line 37 of file InterpolatedSolenoidBFieldTest.cpp
Referenced by ALICEKF::ALICEKalmanFilter(), Acts::CylinderSurface::binningPosition(), BOOST_DATA_TEST_CASE(), Acts::Test::BOOST_FIXTURE_TEST_CASE(), PHTruthSiliconAssociation::buildTrackSeed(), PHTruthTrackSeeding::buildTrackSeed(), calc_dca_circle_line(), calculate_g1(), TrackFitUtils::circle_fit_by_taubin(), CosmicSpray::CosmicSpray(), groot::CreateZigzags(), daq_device_gauss::daq_device_gauss(), JetDefinition::description_no_recombiner(), Acts::GeometryView3D::drawSurfaceArray(), QAG4SimulationMicromegas::evaluate_clusters(), QAG4SimulationTpc::evaluate_clusters(), PHActsKDTreeSeeding::findInttMatches(), PHActsSiliconSeeding::findInttMatches(), TrackSeed_v1::findRoot(), Acts::SingleSeedVertexFinder< spacepoint_t >::findTriplets(), get_A1_sigma(), ClusterErrorPara::get_cluster_error(), get_depolarization_factor(), get_g1_sigma(), get_g1_value(), TpcPrototypeGenFitTrkFitter::get_rotation_matrix(), TpcPrototypeGenFitTrkFitter::get_vertex_error_uvn(), JetAnalyzer::GetBackgroundSubtractor(), ALICEKF::GetCircleClusterResiduals(), TrackFitUtils::getCircleClusterResiduals(), PHG4OuterHcalField::GetFieldValue(), eic_dual_rich::ind_ray(), eic_bnl_rich::ind_ray(), Acts::CylinderSurface::intersectionSolver(), Acts::ConeSurface::localCartesianToBoundLocalDerivative(), Acts::CylinderSurface::localCartesianToBoundLocalDerivative(), main(), makeFieldMap(), numericInverse(), Acts::Sycl::detail::TripletSearch::operator()(), ActsExamples::tbbWrap::parallel_for::parallel_for(), TpcPrototypeGenFitTrkFitter::pos_cov_uvn_to_rz(), PHGenFitTrkFitter::pos_cov_XYZ_to_RZ(), TpcPrototypeGenFitTrkFitter::pos_cov_XYZ_to_RZ(), TpcMon::process_event(), TrackSeedTrackMapConverter::process_event(), TpcRawDataTree::process_event(), TPCRawDataTree::process_event(), PHTpcClusterMover::process_event(), PHMicromegasTpcTrackMatching::process_event(), tpc_hits::process_event(), TpcRawDataDecoder::process_event(), TpcClusterMover::processTrack(), genfit::KalmanFitter::processTrackPoint(), genfit::KalmanFitterRefTrack::processTrackPointSqrt(), Acts::Legacy::AtlasSeedFinder< SpacePoint >::production3Sp(), daq_device_gauss::put_data(), PHSimpleKFProp::RemoveBadClusters(), PHCASeeding::RemoveBadClusters(), genfit::MplTrackRep::RKPropagate(), genfit::RKTrackRep::RKPropagate(), genfit::RKTrackRep::RKutta(), LaplaceSolution::Rmn(), Rossegger::Rmn(), LaplaceSolution::Rmn1(), Rossegger::Rmn1(), Rossegger::Rmn1_(), LaplaceSolution::Rmn2(), Rossegger::Rmn2(), Rossegger::Rmn2_(), Rossegger::Rmn_(), LaplaceSolution::Rnk(), LaplaceSolution::RPrime(), Rossegger::RPrime(), Rossegger::RPrime_(), PHPy8JetTrigger::SetJetR(), PHPy6JetTrigger::SetJetR(), Acts::AtlasStepper::step(), Acts::SurfaceArrayCreator::surfaceArrayOnCylinder(), TEST_CASE(), TPCEventDisplay_Updated(), TPCEventDisplay_Updated_BCO(), PHG4GDMLWriteStructure::TraverseVolumeTree(), TreeMaker::UseFastJet(), PHG4GDMLWrite::Write(), and daq_device_gauss::~daq_device_gauss().
auto Acts::IntegrationTest::tg = grid.trackingGeometry
Definition at line 24 of file BVHNavigationTest.cpp.
View newest version in sPHENIX GitHub at line 24 of file BVHNavigationTest.cpp
GeometryContext Acts::IntegrationTest::tgContext = GeometryContext()
Definition at line 18 of file BVHNavigationTest.cpp.
View newest version in sPHENIX GitHub at line 18 of file BVHNavigationTest.cpp
auto Acts::IntegrationTest::volumes = grid.volumes
Definition at line 23 of file BVHNavigationTest.cpp.
View newest version in sPHENIX GitHub at line 23 of file BVHNavigationTest.cpp