Analysis Software: tinyxml2::MemPoolT< ITEM_SIZE > Class Template Reference
tinyxml2::MemPoolT< ITEM_SIZE > Class Template Reference
#include <JETSCAPE/blob/main/external_packages/tinyxml2.h>
Classes
struct Block
union Item
Public Types
enum { ITEMS_PER_BLOCK = (4 * 1024) / ITEM_SIZE }
Public Member Functions
MemPoolT ()
~MemPoolT ()
void Clear ()
virtual int ItemSize () const
int CurrentAllocs () const
virtual void * Alloc ()
virtual void Free (void *mem)
void Trace (const char *name)
void SetTracked ()
int Untracked () const
Public Member Functions inherited from tinyxml2::MemPool
MemPool ()
virtual ~MemPool ()
Private Member Functions
MemPoolT (const MemPoolT &)
void operator= (const MemPoolT &)
Private Attributes
DynArray< Block *, 10 > _blockPtrs
Item * _root
int _currentAllocs
int _nAllocs
int _maxAllocs
int _nUntracked
Detailed Description
template<int ITEM_SIZE>
class tinyxml2::MemPoolT< ITEM_SIZE >
Definition at line 325 of file tinyxml2.h.
View newest version in sPHENIX GitHub at line 325 of file tinyxml2.h
Member Enumeration Documentation
template<int ITEM_SIZE> anonymous enum
Enumerator:
ITEMS_PER_BLOCK
Definition at line 416 of file tinyxml2.h.
View newest version in sPHENIX GitHub at line 416 of file tinyxml2.h
Constructor & Destructor Documentation
template<int ITEM_SIZE> tinyxml2::MemPoolT< ITEM_SIZE >::MemPoolT () inline
Definition at line 328 of file tinyxml2.h.
View newest version in sPHENIX GitHub at line 328 of file tinyxml2.h
template<int ITEM_SIZE> tinyxml2::MemPoolT< ITEM_SIZE >::~MemPoolT () inline
Definition at line 329 of file tinyxml2.h.
View newest version in sPHENIX GitHub at line 329 of file tinyxml2.h
template<int ITEM_SIZE> tinyxml2::MemPoolT< ITEM_SIZE >::MemPoolT (const MemPoolT< ITEM_SIZE > &) private
Member Function Documentation
template<int ITEM_SIZE> virtual void* tinyxml2::MemPoolT< ITEM_SIZE >::Alloc () inline virtual
Implements tinyxml2::MemPool.
Definition at line 353 of file tinyxml2.h.
View newest version in sPHENIX GitHub at line 353 of file tinyxml2.h
Referenced by tinyxml2::XMLElement::CreateAttribute(), tinyxml2::XMLDocument::Identify(), tinyxml2::XMLDocument::NewComment(), tinyxml2::XMLDocument::NewDeclaration(), tinyxml2::XMLDocument::NewElement(), tinyxml2::XMLDocument::NewText(), and tinyxml2::XMLDocument::NewUnknown().
template<int ITEM_SIZE> void tinyxml2::MemPoolT< ITEM_SIZE >::Clear (void) inline virtual
Implements tinyxml2::MemPool.
Definition at line 333 of file tinyxml2.h.
View newest version in sPHENIX GitHub at line 333 of file tinyxml2.h
Referenced by tinyxml2::XMLDocument::Parse(), and tinyxml2::MemPoolT< sizeof(XMLElement) >::~MemPoolT().
template<int ITEM_SIZE> int tinyxml2::MemPoolT< ITEM_SIZE >::CurrentAllocs () const inline
Definition at line 349 of file tinyxml2.h.
View newest version in sPHENIX GitHub at line 349 of file tinyxml2.h
Referenced by tinyxml2::XMLDocument::Clear().
template<int ITEM_SIZE> virtual void tinyxml2::MemPoolT< ITEM_SIZE >::Free (void * mem) inline virtual
Implements tinyxml2::MemPool.
Definition at line 379 of file tinyxml2.h.
View newest version in sPHENIX GitHub at line 379 of file tinyxml2.h
template<int ITEM_SIZE> virtual int tinyxml2::MemPoolT< ITEM_SIZE >::ItemSize () const inline virtual
Implements tinyxml2::MemPool.
Definition at line 346 of file tinyxml2.h.
View newest version in sPHENIX GitHub at line 346 of file tinyxml2.h
Referenced by tinyxml2::XMLElement::CreateAttribute(), tinyxml2::XMLDocument::Identify(), tinyxml2::XMLDocument::NewComment(), tinyxml2::XMLDocument::NewDeclaration(), tinyxml2::XMLDocument::NewElement(), tinyxml2::XMLDocument::NewText(), and tinyxml2::XMLDocument::NewUnknown().
template<int ITEM_SIZE> void tinyxml2::MemPoolT< ITEM_SIZE >::operator= (const MemPoolT< ITEM_SIZE > &) private
template<int ITEM_SIZE> void tinyxml2::MemPoolT< ITEM_SIZE >::SetTracked () inline virtual
Implements tinyxml2::MemPool.
Definition at line 397 of file tinyxml2.h.
View newest version in sPHENIX GitHub at line 397 of file tinyxml2.h
Referenced by tinyxml2::XMLElement::CreateAttribute().
template<int ITEM_SIZE> void tinyxml2::MemPoolT< ITEM_SIZE >::Trace (const char * name) inline
Definition at line 391 of file tinyxml2.h.
View newest version in sPHENIX GitHub at line 391 of file tinyxml2.h
Referenced by tinyxml2::XMLDocument::Clear().
template<int ITEM_SIZE> int tinyxml2::MemPoolT< ITEM_SIZE >::Untracked () const inline
Definition at line 401 of file tinyxml2.h.
View newest version in sPHENIX GitHub at line 401 of file tinyxml2.h
Referenced by tinyxml2::XMLDocument::Clear().
Member Data Documentation
template<int ITEM_SIZE> DynArray< Block*, 10 > tinyxml2::MemPoolT< ITEM_SIZE >::_blockPtrs private
Definition at line 429 of file tinyxml2.h.
View newest version in sPHENIX GitHub at line 429 of file tinyxml2.h
Referenced by tinyxml2::MemPoolT< sizeof(XMLElement) >::Alloc(), tinyxml2::MemPoolT< sizeof(XMLElement) >::Clear(), and tinyxml2::MemPoolT< sizeof(XMLElement) >::Trace().
template<int ITEM_SIZE> int tinyxml2::MemPoolT< ITEM_SIZE >::_currentAllocs private
Definition at line 432 of file tinyxml2.h.
View newest version in sPHENIX GitHub at line 432 of file tinyxml2.h
Referenced by tinyxml2::MemPoolT< sizeof(XMLElement) >::Alloc(), tinyxml2::MemPoolT< sizeof(XMLElement) >::Clear(), tinyxml2::MemPoolT< sizeof(XMLElement) >::CurrentAllocs(), tinyxml2::MemPoolT< sizeof(XMLElement) >::Free(), and tinyxml2::MemPoolT< sizeof(XMLElement) >::Trace().
template<int ITEM_SIZE> int tinyxml2::MemPoolT< ITEM_SIZE >::_maxAllocs private
Definition at line 434 of file tinyxml2.h.
View newest version in sPHENIX GitHub at line 434 of file tinyxml2.h
Referenced by tinyxml2::MemPoolT< sizeof(XMLElement) >::Alloc(), tinyxml2::MemPoolT< sizeof(XMLElement) >::Clear(), and tinyxml2::MemPoolT< sizeof(XMLElement) >::Trace().
template<int ITEM_SIZE> int tinyxml2::MemPoolT< ITEM_SIZE >::_nAllocs private
Definition at line 433 of file tinyxml2.h.
View newest version in sPHENIX GitHub at line 433 of file tinyxml2.h
Referenced by tinyxml2::MemPoolT< sizeof(XMLElement) >::Alloc(), tinyxml2::MemPoolT< sizeof(XMLElement) >::Clear(), and tinyxml2::MemPoolT< sizeof(XMLElement) >::Trace().
template<int ITEM_SIZE> int tinyxml2::MemPoolT< ITEM_SIZE >::_nUntracked private
Definition at line 435 of file tinyxml2.h.
View newest version in sPHENIX GitHub at line 435 of file tinyxml2.h
Referenced by tinyxml2::MemPoolT< sizeof(XMLElement) >::Alloc(), tinyxml2::MemPoolT< sizeof(XMLElement) >::Clear(), tinyxml2::MemPoolT< sizeof(XMLElement) >::SetTracked(), and tinyxml2::MemPoolT< sizeof(XMLElement) >::Untracked().
template<int ITEM_SIZE> Item* tinyxml2::MemPoolT< ITEM_SIZE >::_root private
Definition at line 430 of file tinyxml2.h.
View newest version in sPHENIX GitHub at line 430 of file tinyxml2.h
Referenced by tinyxml2::MemPoolT< sizeof(XMLElement) >::Alloc(), tinyxml2::MemPoolT< sizeof(XMLElement) >::Clear(), and tinyxml2::MemPoolT< sizeof(XMLElement) >::Free().
The documentation for this class was generated from the following file:
JETSCAPE/blob/main/external_packages/tinyxml2.h