Analysis Software: Fun4AllEventOutputManager Class Reference
Fun4AllEventOutputManager Class Reference
#include <coresoftware/blob/master/offline/framework/fun4allraw/Fun4AllEventOutputManager.h>
Public Member Functions
Fun4AllEventOutputManager (const std::string &myname="EVENTOUT", const std::string &filename="eventout.prdf", const unsigned int nEvents=0, const unsigned int sizeInMB=0, const int offset=0, const int increment=1)
virtual ~Fun4AllEventOutputManager ()
int outfileopen (const std::string &) override
opens output file
void Print (const std::string &what="ALL") const override
print method (dump event selector)
int Write (PHCompositeNode *startNode) override
write starting from given node
int AddPacket (const int ipkt)
int DropPacket (const int ipkt)
int AddPacketRange (const int ipktmin, const int ipktmax)
int DropPacketRange (const int ipktmin, const int ipktmax)
void SetOutfileName (const std::string &fname)
void Verbosity (const int i) override
Sets the verbosity of this module (0 by default=quiet).
Public Member Functions inherited from Fun4AllOutputManager
~Fun4AllOutputManager () override=default
destructor
virtual int AddNode (const std::string &)
add a node in outputmanager
virtual int AddRunNode (const std::string &)
add a runwise node in outputmanager
virtual int StripNode (const std::string &)
not write a node in outputmanager
virtual int StripRunNode (const std::string &)
not write a runwise node in outputmanager
virtual void SaveRunNode (const int)
virtual void SaveDstNode (const int)
virtual int AddEventSelector (const std::string &recomodule)
add an event selector to the outputmanager. event will get written only if all event selectors process_event method return EVENT_OK
int WriteGeneric (PHCompositeNode *startNode)
Common method, called before calling virtual Write.
virtual int WriteNode (PHCompositeNode *)
write specified node
virtual std::vector
< std::string > * EventSelector ()
retrieves pointer to vector of event selector module names
virtual std::vector< unsigned > * RecoModuleIndex ()
retrieves pointer to vector of event selector module ids
virtual int DoNotWriteEvent (std::vector< int > *retcodes) const
decides if event is to be written or not
virtual unsigned int EventsWritten () const
get number of Events
virtual void IncrementEvents (const unsigned int i)
increment number of events
virtual void SetEventsWritten (const unsigned int i)
set number of events
virtual std::string OutFileName () const
get output file name
void OutFileName (const std::string &name)
void SetClosingScript (const std::string &script)
void SetClosingScriptArgs (const std::string &args)
int RunAfterClosing ()
void UseFileRule ()
bool ApplyFileRule () const
void SetNEvents (const unsigned int nevt)
unsigned int GetNEvents () const
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Protected Attributes
std::string m_OutFileRule
Fun4AllEventOutStream * m_OutStream {nullptr}
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = std::numeric_limits<int>::max() - 10
}
Protected Member Functions inherited from Fun4AllOutputManager
Fun4AllOutputManager (const std::string &myname)
Fun4AllOutputManager (const std::string &myname, const std::string &outfname)
Detailed Description
Definition at line 13 of file Fun4AllEventOutputManager.h.
View newest version in sPHENIX GitHub at line 13 of file Fun4AllEventOutputManager.h
Constructor & Destructor Documentation
Fun4AllEventOutputManager::Fun4AllEventOutputManager (const std::string & myname = "EVENTOUT", const std::string & filename = "eventout.prdf", const unsigned int nEvents = 0, const unsigned int sizeInMB = 0, const int offset = 0, const int increment = 1)
Definition at line 17 of file Fun4AllEventOutputManager.cc.
View newest version in sPHENIX GitHub at line 17 of file Fun4AllEventOutputManager.cc
References m_OutStream, and Fun4AllEventOutStream::SetManager().
Fun4AllEventOutputManager::~Fun4AllEventOutputManager () virtual
Definition at line 26 of file Fun4AllEventOutputManager.cc.
View newest version in sPHENIX GitHub at line 26 of file Fun4AllEventOutputManager.cc
References m_OutStream.
Member Function Documentation
int Fun4AllEventOutputManager::AddPacket (const int ipkt)
Definition at line 55 of file Fun4AllEventOutputManager.cc.
View newest version in sPHENIX GitHub at line 55 of file Fun4AllEventOutputManager.cc
References Fun4AllEventOutStream::AddPacket(), m_OutStream, and PHWHERE.
int Fun4AllEventOutputManager::AddPacketRange (const int ipktmin, const int ipktmax)
Definition at line 69 of file Fun4AllEventOutputManager.cc.
View newest version in sPHENIX GitHub at line 69 of file Fun4AllEventOutputManager.cc
References Fun4AllEventOutStream::AddPacketRange(), m_OutStream, and PHWHERE.
int Fun4AllEventOutputManager::DropPacket (const int ipkt)
Definition at line 83 of file Fun4AllEventOutputManager.cc.
View newest version in sPHENIX GitHub at line 83 of file Fun4AllEventOutputManager.cc
References Fun4AllEventOutStream::DropPacket(), m_OutStream, and PHWHERE.
int Fun4AllEventOutputManager::DropPacketRange (const int ipktmin, const int ipktmax)
Definition at line 97 of file Fun4AllEventOutputManager.cc.
View newest version in sPHENIX GitHub at line 97 of file Fun4AllEventOutputManager.cc
References Fun4AllEventOutStream::DropPacketRange(), m_OutStream, and PHWHERE.
int Fun4AllEventOutputManager::outfileopen (const std::string &) inline override virtual
opens output file
Reimplemented from Fun4AllOutputManager.
Definition at line 19 of file Fun4AllEventOutputManager.h.
View newest version in sPHENIX GitHub at line 19 of file Fun4AllEventOutputManager.h
void Fun4AllEventOutputManager::Print (const std::string & what = "ALL") const override virtual
print method (dump event selector)
Reimplemented from Fun4AllOutputManager.
Definition at line 32 of file Fun4AllEventOutputManager.cc.
View newest version in sPHENIX GitHub at line 32 of file Fun4AllEventOutputManager.cc
References m_OutFileRule, Fun4AllBase::Name(), and Fun4AllOutputManager::Print().
void Fun4AllEventOutputManager::SetOutfileName (const std::string & fname)
Definition at line 111 of file Fun4AllEventOutputManager.cc.
View newest version in sPHENIX GitHub at line 111 of file Fun4AllEventOutputManager.cc
References Fun4AllOutputManager::OutFileName().
Referenced by Fun4AllRolloverFileOutStream::WriteEventOut().
void Fun4AllEventOutputManager::Verbosity (const int ival) override virtual
Sets the verbosity of this module (0 by default=quiet).
Reimplemented from Fun4AllBase.
Definition at line 117 of file Fun4AllEventOutputManager.cc.
View newest version in sPHENIX GitHub at line 117 of file Fun4AllEventOutputManager.cc
References m_OutStream, and Fun4AllBase::Verbosity().
int Fun4AllEventOutputManager::Write (PHCompositeNode *) override virtual
write starting from given node
Reimplemented from Fun4AllOutputManager.
Definition at line 41 of file Fun4AllEventOutputManager.cc.
View newest version in sPHENIX GitHub at line 41 of file Fun4AllEventOutputManager.cc
References Fun4AllServer::instance(), m_OutStream, PHWHERE, Fun4AllServer::topNode(), and Fun4AllEventOutStream::WriteEvent().
Member Data Documentation
std::string Fun4AllEventOutputManager::m_OutFileRule protected
Definition at line 33 of file Fun4AllEventOutputManager.h.
View newest version in sPHENIX GitHub at line 33 of file Fun4AllEventOutputManager.h
Referenced by Print().
Fun4AllEventOutStream* Fun4AllEventOutputManager::m_OutStream {nullptr} protected
Definition at line 34 of file Fun4AllEventOutputManager.h.
View newest version in sPHENIX GitHub at line 34 of file Fun4AllEventOutputManager.h
Referenced by AddPacket(), AddPacketRange(), DropPacket(), DropPacketRange(), Fun4AllEventOutputManager(), Verbosity(), Write(), and ~Fun4AllEventOutputManager().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/framework/fun4allraw/Fun4AllEventOutputManager.h
coresoftware/blob/master/offline/framework/fun4allraw/Fun4AllEventOutputManager.cc