Analysis Software: analysis/blob/master/JS-Jet/FullJetFinder/macro/readJetTree.C File Reference
readJetTree.C File Reference
An example macro how to proccess TTrees from FullJetFinder.cc.
#include <TFile.h>
#include <TH1.h>
#include <TH2.h>
#include <TCanvas.h>
#include <TTreeReader.h>
#include <TTreeReaderValue.h>
#include <TTreeReaderArray.h>
#include <vector>
#include <iostream>
#include <TDatabasePDG.h>
#include <TString.h>
#include <set>
#include <TChain.h>
#include <TGraph.h>
#include <string>
#include <FullJetFinder.h>
Functions
bool CheckValue (ROOT::Internal::TTreeReaderValueBase &value)
void printProgress (int cur, int total)
bool readJetTree (const std::string &dataFiles="/sphenix/tg/tg01/hf/jkvapil/JET30_r11_30GeV/condorJob/myTestJets/outputData_000*.root")
Detailed Description
An example macro how to proccess TTrees from FullJetFinder.cc.
Author
Jakub Kvapil Contact: jakub.nosp@m..kva.nosp@m.pil@c.nosp@m.ern..nosp@m.ch
Definition in file readJetTree.C.
Function Documentation
bool CheckValue (ROOT::Internal::TTreeReaderValueBase & value)
Definition at line 37 of file readJetTree.C.
View newest version in sPHENIX GitHub at line 37 of file readJetTree.C
Referenced by readJetTree().
void printProgress (int cur, int total)
Definition at line 46 of file readJetTree.C.
View newest version in sPHENIX GitHub at line 46 of file readJetTree.C
References i, and Acts::Test::pos.
Referenced by readJetTree().
bool readJetTree (const std::string & dataFiles = "/sphenix/tg/tg01/hf/jkvapil/JET30_r11_30GeV/condorJob/myTestJets/outputData_000*.root")
Definition at line 66 of file readJetTree.C.
View newest version in sPHENIX GitHub at line 66 of file readJetTree.C
References Acts::PhysicalConstants::c, CheckValue(), geant4_parallel::n_events, printProgress(), summary::reader, and tc.