Analysis Software: ActsExamples::TrackFindingAlgorithmExaTrkX Exception Reference
ActsExamples::TrackFindingAlgorithmExaTrkX Exception Reference final
#include <acts/blob/sPHENIX/Examples/Algorithms/TrackFindingExaTrkX/include/ActsExamples/TrackFindingExaTrkX/TrackFindingAlgorithmExaTrkX.hpp>
Classes
struct Config
Public Member Functions
TrackFindingAlgorithmExaTrkX (Config cfg, Acts::Logging::Level lvl)
~TrackFindingAlgorithmExaTrkX () override=default
ActsExamples::ProcessCode execute (const ActsExamples::AlgorithmContext &ctx) const final
ActsExamples::ProcessCode finalize () final
Finalize and print timing.
const Config & config () const
Public Member Functions inherited from ActsExamples::IAlgorithm
IAlgorithm (std::string name, Acts::Logging::Level level=Acts::Logging::INFO)
std::string name () const override
The algorithm name.
ProcessCode internalExecute (const AlgorithmContext &context) final
ProcessCode initialize () override
Initialize the algorithm.
ProcessCode finalize () override
Finalize the algorithm.
Private Types
using Accumulator = boost::accumulators::accumulator_set< float, boost::accumulators::features< boost::accumulators::tag::mean, boost::accumulators::tag::variance >>
Private Attributes
Config m_cfg
Acts::ExaTrkXPipeline m_pipeline
std::mutex m_mutex
struct {
Accumulator graphBuildingTime
std::vector< Accumulator > classifierTimes
Accumulator trackBuildingTime
} m_timing
ReadDataHandle
< SimSpacePointContainer > m_inputSpacePoints
ReadDataHandle< ClusterContainer > m_inputClusters {this, "InputClusters"}
WriteDataHandle
< ProtoTrackContainer > m_outputProtoTracks
ReadDataHandle< SimHitContainer > m_inputSimHits {this, "InputSimHits"}
ReadDataHandle
< SimParticleContainer > m_inputParticles {this, "InputParticles"}
ReadDataHandle< IndexMultimap
< Index > > m_inputMeasurementMap
Additional Inherited Members
Protected Member Functions inherited from ActsExamples::IAlgorithm
const Acts::Logger & logger () const
Detailed Description
Definition at line 31 of file TrackFindingAlgorithmExaTrkX.hpp.
View newest version in sPHENIX GitHub at line 31 of file TrackFindingAlgorithmExaTrkX.hpp
Member Typedef Documentation
using ActsExamples::TrackFindingAlgorithmExaTrkX::Accumulator = boost::accumulators::accumulator_set< float, boost::accumulators::features<boost::accumulators::tag::mean, boost::accumulators::tag::variance>> private
Definition at line 103 of file TrackFindingAlgorithmExaTrkX.hpp.
View newest version in sPHENIX GitHub at line 103 of file TrackFindingAlgorithmExaTrkX.hpp
Constructor & Destructor Documentation
ActsExamples::TrackFindingAlgorithmExaTrkX::TrackFindingAlgorithmExaTrkX (Config cfg, Acts::Logging::Level lvl)
Constructor of the track finding algorithm
Parameters
cfg is the config struct to configure the algorithm
level is the logging level
Definition at line 117 of file TrackFindingAlgorithmExaTrkX.cpp.
View newest version in sPHENIX GitHub at line 117 of file TrackFindingAlgorithmExaTrkX.cpp
References ActsExamples::TrackFindingAlgorithmExaTrkX::Config::edgeClassifiers, ActsExamples::WriteDataHandle< T >::initialize(), ActsExamples::ReadDataHandle< T >::initialize(), ActsExamples::TrackFindingAlgorithmExaTrkX::Config::inputClusters, ActsExamples::TrackFindingAlgorithmExaTrkX::Config::inputMeasurementSimhitsMap, ActsExamples::TrackFindingAlgorithmExaTrkX::Config::inputParticles, ActsExamples::TrackFindingAlgorithmExaTrkX::Config::inputSimHits, ActsExamples::TrackFindingAlgorithmExaTrkX::Config::inputSpacePoints, m_cfg, m_inputClusters, m_inputMeasurementMap, m_inputParticles, m_inputSimHits, m_inputSpacePoints, m_outputProtoTracks, m_timing, ActsExamples::DataHandleBase::maybeInitialize(), and ActsExamples::TrackFindingAlgorithmExaTrkX::Config::outputProtoTracks.
ActsExamples::TrackFindingAlgorithmExaTrkX::~TrackFindingAlgorithmExaTrkX () override default
Member Function Documentation
const Config& ActsExamples::TrackFindingAlgorithmExaTrkX::config () const inline
Definition at line 93 of file TrackFindingAlgorithmExaTrkX.hpp.
View newest version in sPHENIX GitHub at line 93 of file TrackFindingAlgorithmExaTrkX.hpp
References m_cfg.
ActsExamples::ProcessCode ActsExamples::TrackFindingAlgorithmExaTrkX::execute (const ActsExamples::AlgorithmContext & ctx) const final virtual
Framework execute method of the track finding algorithm
Parameters
ctx is the algorithm context that holds event-wise information
Returns
a process code to steer the algorithm flow
Implements ActsExamples::IAlgorithm.
Definition at line 173 of file TrackFindingAlgorithmExaTrkX.cpp.
View newest version in sPHENIX GitHub at line 173 of file TrackFindingAlgorithmExaTrkX.cpp
References KFPMath::a, ACTS_DEBUG, ACTS_INFO, assert, Acts::PhysicalConstants::c, Acts::ExaTrkXTiming::classifierTimes, clusters, eCellCount, eCellSum, eClusterX, eClusterY, ePhi, eR, eZ, Acts::ExaTrkXTiming::graphBuildingTime, i, logger(), m_cfg(), testing::internal::move(), physmon_simulation::s, SUCCESS, Acts::ExaTrkXTiming::trackBuildingTime, ambiguity_solver_full_chain::x, and Acts::zip().
ActsExamples::ProcessCode TrackFindingAlgorithmExaTrkX::finalize () final virtual
Finalize and print timing.
Implements ActsExamples::SequenceElement.
Definition at line 282 of file TrackFindingAlgorithmExaTrkX.cpp.
View newest version in sPHENIX GitHub at line 282 of file TrackFindingAlgorithmExaTrkX.cpp
References ACTS_INFO, m_timing, mean(), and t.
Member Data Documentation
std::vector<Accumulator> ActsExamples::TrackFindingAlgorithmExaTrkX::classifierTimes
Definition at line 107 of file TrackFindingAlgorithmExaTrkX.hpp.
View newest version in sPHENIX GitHub at line 107 of file TrackFindingAlgorithmExaTrkX.hpp
Accumulator ActsExamples::TrackFindingAlgorithmExaTrkX::graphBuildingTime
Definition at line 106 of file TrackFindingAlgorithmExaTrkX.hpp.
View newest version in sPHENIX GitHub at line 106 of file TrackFindingAlgorithmExaTrkX.hpp
Config ActsExamples::TrackFindingAlgorithmExaTrkX::m_cfg private
Definition at line 96 of file TrackFindingAlgorithmExaTrkX.hpp.
View newest version in sPHENIX GitHub at line 96 of file TrackFindingAlgorithmExaTrkX.hpp
Referenced by config(), and TrackFindingAlgorithmExaTrkX().
ReadDataHandle<ClusterContainer> ActsExamples::TrackFindingAlgorithmExaTrkX::m_inputClusters {this, "InputClusters"} private
Definition at line 113 of file TrackFindingAlgorithmExaTrkX.hpp.
View newest version in sPHENIX GitHub at line 113 of file TrackFindingAlgorithmExaTrkX.hpp
Referenced by TrackFindingAlgorithmExaTrkX().
ReadDataHandle<IndexMultimap<Index> > ActsExamples::TrackFindingAlgorithmExaTrkX::m_inputMeasurementMap private
Initial value:
{
      this, "InputMeasurementMap"}
Definition at line 121 of file TrackFindingAlgorithmExaTrkX.hpp.
View newest version in sPHENIX GitHub at line 121 of file TrackFindingAlgorithmExaTrkX.hpp
Referenced by TrackFindingAlgorithmExaTrkX().
ReadDataHandle<SimParticleContainer> ActsExamples::TrackFindingAlgorithmExaTrkX::m_inputParticles {this, "InputParticles"} private
Definition at line 120 of file TrackFindingAlgorithmExaTrkX.hpp.
View newest version in sPHENIX GitHub at line 120 of file TrackFindingAlgorithmExaTrkX.hpp
Referenced by TrackFindingAlgorithmExaTrkX().
ReadDataHandle<SimHitContainer> ActsExamples::TrackFindingAlgorithmExaTrkX::m_inputSimHits {this, "InputSimHits"} private
Definition at line 119 of file TrackFindingAlgorithmExaTrkX.hpp.
View newest version in sPHENIX GitHub at line 119 of file TrackFindingAlgorithmExaTrkX.hpp
Referenced by TrackFindingAlgorithmExaTrkX().
ReadDataHandle<SimSpacePointContainer> ActsExamples::TrackFindingAlgorithmExaTrkX::m_inputSpacePoints private
Initial value:
{this,
                                                            "InputSpacePoints"}
Definition at line 111 of file TrackFindingAlgorithmExaTrkX.hpp.
View newest version in sPHENIX GitHub at line 111 of file TrackFindingAlgorithmExaTrkX.hpp
Referenced by TrackFindingAlgorithmExaTrkX().
std::mutex ActsExamples::TrackFindingAlgorithmExaTrkX::m_mutex mutable private
Definition at line 99 of file TrackFindingAlgorithmExaTrkX.hpp.
View newest version in sPHENIX GitHub at line 99 of file TrackFindingAlgorithmExaTrkX.hpp
WriteDataHandle<ProtoTrackContainer> ActsExamples::TrackFindingAlgorithmExaTrkX::m_outputProtoTracks private
Initial value:
{this,
                                                           "OutputProtoTracks"}
Definition at line 115 of file TrackFindingAlgorithmExaTrkX.hpp.
View newest version in sPHENIX GitHub at line 115 of file TrackFindingAlgorithmExaTrkX.hpp
Referenced by TrackFindingAlgorithmExaTrkX().
Acts::ExaTrkXPipeline ActsExamples::TrackFindingAlgorithmExaTrkX::m_pipeline private
Definition at line 98 of file TrackFindingAlgorithmExaTrkX.hpp.
View newest version in sPHENIX GitHub at line 98 of file TrackFindingAlgorithmExaTrkX.hpp
struct { ... } ActsExamples::TrackFindingAlgorithmExaTrkX::m_timing
Referenced by finalize(), and TrackFindingAlgorithmExaTrkX().
Accumulator ActsExamples::TrackFindingAlgorithmExaTrkX::trackBuildingTime
Definition at line 108 of file TrackFindingAlgorithmExaTrkX.hpp.
View newest version in sPHENIX GitHub at line 108 of file TrackFindingAlgorithmExaTrkX.hpp
The documentation for this exception was generated from the following files:
acts/blob/sPHENIX/Examples/Algorithms/TrackFindingExaTrkX/include/ActsExamples/TrackFindingExaTrkX/TrackFindingAlgorithmExaTrkX.hpp
acts/blob/sPHENIX/Examples/Algorithms/TrackFindingExaTrkX/src/TrackFindingAlgorithmExaTrkX.cpp