Analysis Software: ActsExamples::IBaseDetector Class Reference
ActsExamples::IBaseDetector Class Reference abstract
#include <acts/blob/sPHENIX/Examples/Detectors/Common/include/ActsExamples/Detector/IBaseDetector.hpp>
Public Types
using ContextDecorators = std::vector< std::shared_ptr< ActsExamples::IContextDecorator >>
using TrackingGeometryPtr = std::shared_ptr< const Acts::TrackingGeometry >
Public Member Functions
virtual ~IBaseDetector ()=default
virtual void addOptions (boost::program_options::options_description &opt) const =0
virtual std::pair
< TrackingGeometryPtr,
ContextDecorators > finalize (const boost::program_options::variables_map &vm, std::shared_ptr< const Acts::IMaterialDecorator > mdecorator)=0
Detailed Description
Definition at line 31 of file IBaseDetector.hpp.
View newest version in sPHENIX GitHub at line 31 of file IBaseDetector.hpp
Member Typedef Documentation
using ActsExamples::IBaseDetector::ContextDecorators = std::vector<std::shared_ptr<ActsExamples::IContextDecorator>>
Definition at line 34 of file IBaseDetector.hpp.
View newest version in sPHENIX GitHub at line 34 of file IBaseDetector.hpp
using ActsExamples::IBaseDetector::TrackingGeometryPtr = std::shared_ptr<const Acts::TrackingGeometry>
Definition at line 35 of file IBaseDetector.hpp.
View newest version in sPHENIX GitHub at line 35 of file IBaseDetector.hpp
Constructor & Destructor Documentation
virtual ActsExamples::IBaseDetector::~IBaseDetector () virtual default
Member Function Documentation
virtual void ActsExamples::IBaseDetector::addOptions (boost::program_options::options_description & opt) const pure virtual
Implemented in PayloadDetector, GenericDetector, TGeoDetector, AlignedDetector, DD4hepDetector, and EmptyDetector.
Referenced by MakeActsGeometry::makeGeometry(), materialMappingExample(), materialValidationExample(), processGeometry(), and propagationExample().
virtual std::pair<TrackingGeometryPtr, ContextDecorators> ActsExamples::IBaseDetector::finalize (const boost::program_options::variables_map & vm, std::shared_ptr< const Acts::IMaterialDecorator > mdecorator) pure virtual
Implemented in PayloadDetector, GenericDetector, TGeoDetector, AlignedDetector, DD4hepDetector, and EmptyDetector.
Referenced by ActsExamples::Geometry::build().
The documentation for this class was generated from the following file:
acts/blob/sPHENIX/Examples/Detectors/Common/include/ActsExamples/Detector/IBaseDetector.hpp