Analysis Software: analysis/blob/master/EventMix/ana/work/plotembed_vscent.C File Reference
plotembed_vscent.C File Reference
#include <TNtuple.h>
#include <TF1.h>
#include <TLine.h>
#include "sPHENIXStyle/sPhenixStyle.C"
#include <iostream>
#include <fstream>
Functions
double CBFunction (double *x, double *p)
double CBFunction_withBG (double *x, double *p)
Double_t CrystallBall2 (Double_t x, Double_t mean, Double_t sigma, Double_t alpha1, Double_t n1, Double_t alpha2, Double_t n2)
Double_t CrystallBall2Integral (Double_t sigma, Double_t alpha1, Double_t n1, Double_t alpha2, Double_t n2)
Double_t CrystallBall2 (Double_t *x, Double_t *par)
void plotembed_vscent ()
Function Documentation
double CBFunction (double * x, double * p)
Definition at line 10 of file plotembed_vscent.C.
View newest version in sPHENIX GitHub at line 10 of file plotembed_vscent.C
References A, alpha, k, CKF_timing_vs_mu::mu, n, norm, and sigma.
Referenced by centrality_newplotbg_newsupp(), fit_vs_directcount(), newplotbg_dAu_vscent_2022(), newplotbg_newsupp(), newplotbg_newsupp_2021(), newplotbg_newsupp_2022(), newplotbg_newsupp_2022_60pct(), newplotbg_vscent_2022(), and plotembed_vscent().
double CBFunction_withBG (double * x, double * p)
Definition at line 34 of file plotembed_vscent.C.
View newest version in sPHENIX GitHub at line 34 of file plotembed_vscent.C
References A, alpha, k, CKF_timing_vs_mu::mu, n, norm, and sigma.
Referenced by plotembed_vscent().
Double_t CrystallBall2 (Double_t x, Double_t mean, Double_t sigma, Double_t alpha1, Double_t n1, Double_t alpha2, Double_t n2)
Definition at line 65 of file plotembed_vscent.C.
View newest version in sPHENIX GitHub at line 65 of file plotembed_vscent.C
References KFPMath::a, KFPMath::b, mean(), and t.
Referenced by CrystallBall2(), and plotembed_vscent().
Double_t CrystallBall2 (Double_t * x, Double_t * par)
Definition at line 93 of file plotembed_vscent.C.
View newest version in sPHENIX GitHub at line 93 of file plotembed_vscent.C
References CrystallBall2(), CrystallBall2Integral(), and integral().
Double_t CrystallBall2Integral (Double_t sigma, Double_t alpha1, Double_t n1, Double_t alpha2, Double_t n2)
Definition at line 81 of file plotembed_vscent.C.
View newest version in sPHENIX GitHub at line 81 of file plotembed_vscent.C
Referenced by CrystallBall2().
void plotembed_vscent ()
Definition at line 105 of file plotembed_vscent.C.
View newest version in sPHENIX GitHub at line 105 of file plotembed_vscent.C
References bins, CBFunction(), CBFunction_withBG(), CrystallBall2(), double(), Acts::UnitConstants::e, eta, std::tr1::f2, i, j, k, testSigmaEff::l1, mass, nbins, physmon_track_finding_ttbar::pt, SetsPhenixStyle(), sum(), parse_cmake_options::type, ambiguity_solver_full_chain::x, and y.