Analysis Software: MbdPmtHit Class Reference
MbdPmtHit Class Reference
#include <coresoftware/blob/master/offline/packages/mbd/MbdPmtHit.h>
Public Member Functions
MbdPmtHit ()
virtual ~MbdPmtHit () override=default
virtual Short_t get_pmt () const
virtual Float_t get_q () const
virtual Float_t get_time () const
virtual Float_t get_tt () const
virtual Float_t get_tq () const
virtual void set_pmt (const Short_t, const Float_t, const Float_t, const Float_t)
virtual void identify (std::ostream &os=std::cout) const override
virtual int isValid () const override
isValid returns non zero if object contains vailid data
Public Member Functions inherited from PHObject
PHObject ()
ctor
~PHObject () override
dtor
virtual PHObject * CloneMe () const
Virtual copy constructor.
virtual PHObject * clone () const final
PHObject * Clone (const char *newname="") const final
void Copy (TObject &object) const final
virtual void Reset ()
Clear Event.
virtual int Integrate () const
virtual int Integrate (PHObject *)
virtual void CopyFrom (const PHObject *obj)
Detailed Description
Definition at line 13 of file MbdPmtHit.h.
View newest version in sPHENIX GitHub at line 13 of file MbdPmtHit.h
Constructor & Destructor Documentation
MbdPmtHit::MbdPmtHit () inline
Definition at line 16 of file MbdPmtHit.h.
View newest version in sPHENIX GitHub at line 16 of file MbdPmtHit.h
virtual MbdPmtHit::~MbdPmtHit () override virtual default
Member Function Documentation
virtual Short_t MbdPmtHit::get_pmt () const inline virtual
Reimplemented in MbdPmtHitV1.
Definition at line 19 of file MbdPmtHit.h.
View newest version in sPHENIX GitHub at line 19 of file MbdPmtHit.h
References PHOOL_VIRTUAL_WARNING.
virtual Float_t MbdPmtHit::get_q () const inline virtual
Reimplemented in MbdPmtHitV1.
Definition at line 25 of file MbdPmtHit.h.
View newest version in sPHENIX GitHub at line 25 of file MbdPmtHit.h
References MbdReturnCodes::MBD_INVALID_FLOAT, and PHOOL_VIRTUAL_WARNING.
Referenced by MbdEvent::Calculate(), BbcCheck::CheckDST(), EventPlaneReco::process_event(), DumpMbdPmtContainer::process_Node(), CaloAna::process_towers(), and CaloValid::process_towers().
virtual Float_t MbdPmtHit::get_time () const inline virtual
Reimplemented in MbdPmtHitV1.
Definition at line 31 of file MbdPmtHit.h.
View newest version in sPHENIX GitHub at line 31 of file MbdPmtHit.h
References MbdReturnCodes::MBD_INVALID_FLOAT, and PHOOL_VIRTUAL_WARNING.
Referenced by MbdEvent::Calculate(), BbcCheck::CheckDST(), and DumpMbdPmtContainer::process_Node().
virtual Float_t MbdPmtHit::get_tq () const inline virtual
Reimplemented in MbdPmtHitV1.
Definition at line 43 of file MbdPmtHit.h.
View newest version in sPHENIX GitHub at line 43 of file MbdPmtHit.h
References MbdReturnCodes::MBD_INVALID_FLOAT, and PHOOL_VIRTUAL_WARNING.
virtual Float_t MbdPmtHit::get_tt () const inline virtual
Reimplemented in MbdPmtHitV1.
Definition at line 37 of file MbdPmtHit.h.
View newest version in sPHENIX GitHub at line 37 of file MbdPmtHit.h
References MbdReturnCodes::MBD_INVALID_FLOAT, and PHOOL_VIRTUAL_WARNING.
void MbdPmtHit::identify (std::ostream & os = std::cout) const override virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from PHObject.
Reimplemented in MbdPmtHitV1.
Definition at line 5 of file MbdPmtHit.cc.
View newest version in sPHENIX GitHub at line 5 of file MbdPmtHit.cc
virtual int MbdPmtHit::isValid () const inline override virtual
isValid returns non zero if object contains vailid data
Reimplemented from PHObject.
Reimplemented in MbdPmtHitV1.
Definition at line 56 of file MbdPmtHit.h.
View newest version in sPHENIX GitHub at line 56 of file MbdPmtHit.h
virtual void MbdPmtHit::set_pmt (const Short_t , const Float_t , const Float_t , const Float_t) inline virtual
Reimplemented in MbdPmtHitV1.
Definition at line 49 of file MbdPmtHit.h.
View newest version in sPHENIX GitHub at line 49 of file MbdPmtHit.h
References PHOOL_VIRTUAL_WARNING.
Referenced by MbdDigitization::process_event(), and MbdEvent::SetRawData().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/mbd/MbdPmtHit.h
coresoftware/blob/master/offline/packages/mbd/MbdPmtHit.cc