Analysis Software: CaloTowerStatus Class Reference
CaloTowerStatus Class Reference
#include <coresoftware/blob/master/offline/packages/CaloReco/CaloTowerStatus.h>
Public Member Functions
CaloTowerStatus (const std::string &name="CaloTowerStatus")
~CaloTowerStatus () override
int InitRun (PHCompositeNode *topNode) override
int process_event (PHCompositeNode *topNode) override
void CreateNodeTree (PHCompositeNode *topNode)
void set_detector_type (CaloTowerDefs::DetectorSystem dettype)
void set_inputNodePrefix (const std::string &name)
void set_badChi2_treshold (float threshold)
void set_fraction_badChi2_threshold (float threshold)
void set_time_cut (float threshold)
Public Member Functions inherited from SubsysReco
~SubsysReco () override
virtual int End (PHCompositeNode *)
Called at the end of all processing.
virtual int EndRun (const int)
Called at the end of each run.
virtual int Init (PHCompositeNode *)
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
void Print (const std::string &="ALL") const override
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Private Attributes
TowerInfoContainer * m_raw_towers {nullptr}
CDBTTree * m_cdbttree_chi2 {nullptr}
CDBTTree * m_cdbttree_time {nullptr}
CDBTTree * m_cdbttree_hotMap {nullptr}
bool m_doHotChi2 {true}
bool m_doTime {true}
bool m_doHotMap {true}
CaloTowerDefs::DetectorSystem m_dettype {CaloTowerDefs::DETECTOR_INVALID}
std::string m_detector
std::string m_fieldname_time
std::string m_calibName_time
std::string m_fieldname_chi2
std::string m_calibName_chi2
std::string m_fieldname_hotMap
std::string m_calibName_hotMap
std::string m_inputNodePrefix {"TOWERS_"}
float badChi2_treshold = 1e4
float fraction_badChi2_threshold = 0.01
float time_cut = 2
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = std::numeric_limits<int>::max() - 10
}
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Detailed Description
Definition at line 20 of file CaloTowerStatus.h.
View newest version in sPHENIX GitHub at line 20 of file CaloTowerStatus.h
Constructor & Destructor Documentation
CaloTowerStatus::CaloTowerStatus (const std::string & name = "CaloTowerStatus")
Definition at line 38 of file CaloTowerStatus.cc.
View newest version in sPHENIX GitHub at line 38 of file CaloTowerStatus.cc
References Fun4AllBase::Verbosity().
CaloTowerStatus::~CaloTowerStatus () override
Definition at line 48 of file CaloTowerStatus.cc.
View newest version in sPHENIX GitHub at line 48 of file CaloTowerStatus.cc
References m_cdbttree_chi2, m_cdbttree_time, and Fun4AllBase::Verbosity().
Member Function Documentation
void CaloTowerStatus::CreateNodeTree (PHCompositeNode * topNode)
Definition at line 203 of file CaloTowerStatus.cc.
View newest version in sPHENIX GitHub at line 203 of file CaloTowerStatus.cc
References m_detector, m_inputNodePrefix, m_raw_towers, and Fun4AllBase::Name().
Referenced by InitRun().
int CaloTowerStatus::InitRun (PHCompositeNode *) override virtual
Called for first event when run number is known. Typically this is where you may want to fetch data from database, because you know the run number.
Reimplemented from SubsysReco.
Definition at line 59 of file CaloTowerStatus.cc.
View newest version in sPHENIX GitHub at line 59 of file CaloTowerStatus.cc
References Fun4AllReturnCodes::ABORTRUN, CaloTowerDefs::CEMC, CreateNodeTree(), Acts::UnitConstants::e, Fun4AllReturnCodes::EVENT_OK, PHNodeIterator::findFirst(), CDBInterface::getUrl(), CaloTowerDefs::HCALIN, CaloTowerDefs::HCALOUT, CDBInterface::instance(), m_calibName_chi2, m_calibName_hotMap, m_calibName_time, m_cdbttree_chi2, m_cdbttree_hotMap, m_cdbttree_time, m_detector, m_dettype, m_doHotChi2, m_doHotMap, m_doTime, m_fieldname_chi2, m_fieldname_hotMap, m_fieldname_time, Fun4AllBase::Name(), PHCompositeNode::print(), CaloTowerDefs::SEPD, Fun4AllBase::Verbosity(), and CaloTowerDefs::ZDC.
int CaloTowerStatus::process_event (PHCompositeNode *) override virtual
Called for each event. This is where you do the real work.
Reimplemented from SubsysReco.
Definition at line 157 of file CaloTowerStatus.cc.
View newest version in sPHENIX GitHub at line 157 of file CaloTowerStatus.cc
References badChi2_treshold, channel(), TowerInfoContainer::encode_key(), Fun4AllReturnCodes::EVENT_OK, fraction_badChi2_threshold, TowerInfo::get_chi2(), TowerInfo::get_time_float(), TowerInfoContainer::get_tower_at_channel(), CDBTTree::GetFloatValue(), CDBTTree::GetIntValue(), m_cdbttree_chi2, m_cdbttree_hotMap, m_cdbttree_time, m_doHotChi2, m_doHotMap, m_doTime, m_fieldname_chi2, m_fieldname_hotMap, m_fieldname_time, m_raw_towers, TowerInfo::set_isBadChi2(), TowerInfo::set_isBadTime(), TowerInfo::set_isHot(), TowerInfo::set_status(), TowerInfoContainer::size(), Acts::Test::time, and time_cut.
void CaloTowerStatus::set_badChi2_treshold (float threshold) inline
Definition at line 41 of file CaloTowerStatus.h.
View newest version in sPHENIX GitHub at line 41 of file CaloTowerStatus.h
References badChi2_treshold.
void CaloTowerStatus::set_detector_type (CaloTowerDefs::DetectorSystem dettype) inline
Definition at line 31 of file CaloTowerStatus.h.
View newest version in sPHENIX GitHub at line 31 of file CaloTowerStatus.h
References m_dettype.
Referenced by Fun4All_JetBkgd_Embed(), and Fun4All_Year1().
void CaloTowerStatus::set_fraction_badChi2_threshold (float threshold) inline
Definition at line 46 of file CaloTowerStatus.h.
View newest version in sPHENIX GitHub at line 46 of file CaloTowerStatus.h
References fraction_badChi2_threshold.
void CaloTowerStatus::set_inputNodePrefix (const std::string & name) inline
Definition at line 36 of file CaloTowerStatus.h.
View newest version in sPHENIX GitHub at line 36 of file CaloTowerStatus.h
References m_inputNodePrefix, and perf_headwind::name.
Referenced by Fun4All_JetBkgd_Embed().
void CaloTowerStatus::set_time_cut (float threshold) inline
Definition at line 51 of file CaloTowerStatus.h.
View newest version in sPHENIX GitHub at line 51 of file CaloTowerStatus.h
References time_cut.
Referenced by Fun4All_JetBkgd_Embed(), and Fun4All_Year1().
Member Data Documentation
float CaloTowerStatus::badChi2_treshold = 1e4 private
Definition at line 79 of file CaloTowerStatus.h.
View newest version in sPHENIX GitHub at line 79 of file CaloTowerStatus.h
Referenced by process_event(), and set_badChi2_treshold().
float CaloTowerStatus::fraction_badChi2_threshold = 0.01 private
Definition at line 80 of file CaloTowerStatus.h.
View newest version in sPHENIX GitHub at line 80 of file CaloTowerStatus.h
Referenced by process_event(), and set_fraction_badChi2_threshold().
std::string CaloTowerStatus::m_calibName_chi2 private
Definition at line 74 of file CaloTowerStatus.h.
View newest version in sPHENIX GitHub at line 74 of file CaloTowerStatus.h
Referenced by InitRun().
std::string CaloTowerStatus::m_calibName_hotMap private
Definition at line 76 of file CaloTowerStatus.h.
View newest version in sPHENIX GitHub at line 76 of file CaloTowerStatus.h
Referenced by InitRun().
std::string CaloTowerStatus::m_calibName_time private
Definition at line 72 of file CaloTowerStatus.h.
View newest version in sPHENIX GitHub at line 72 of file CaloTowerStatus.h
Referenced by InitRun().
CDBTTree* CaloTowerStatus::m_cdbttree_chi2 {nullptr} private
Definition at line 60 of file CaloTowerStatus.h.
View newest version in sPHENIX GitHub at line 60 of file CaloTowerStatus.h
Referenced by InitRun(), process_event(), and ~CaloTowerStatus().
CDBTTree* CaloTowerStatus::m_cdbttree_hotMap {nullptr} private
Definition at line 62 of file CaloTowerStatus.h.
View newest version in sPHENIX GitHub at line 62 of file CaloTowerStatus.h
Referenced by InitRun(), and process_event().
CDBTTree* CaloTowerStatus::m_cdbttree_time {nullptr} private
Definition at line 61 of file CaloTowerStatus.h.
View newest version in sPHENIX GitHub at line 61 of file CaloTowerStatus.h
Referenced by InitRun(), process_event(), and ~CaloTowerStatus().
std::string CaloTowerStatus::m_detector private
Definition at line 70 of file CaloTowerStatus.h.
View newest version in sPHENIX GitHub at line 70 of file CaloTowerStatus.h
Referenced by CreateNodeTree(), and InitRun().
CaloTowerDefs::DetectorSystem CaloTowerStatus::m_dettype {CaloTowerDefs::DETECTOR_INVALID} private
Definition at line 68 of file CaloTowerStatus.h.
View newest version in sPHENIX GitHub at line 68 of file CaloTowerStatus.h
Referenced by InitRun(), and set_detector_type().
bool CaloTowerStatus::m_doHotChi2 {true} private
Definition at line 64 of file CaloTowerStatus.h.
View newest version in sPHENIX GitHub at line 64 of file CaloTowerStatus.h
Referenced by InitRun(), and process_event().
bool CaloTowerStatus::m_doHotMap {true} private
Definition at line 66 of file CaloTowerStatus.h.
View newest version in sPHENIX GitHub at line 66 of file CaloTowerStatus.h
Referenced by InitRun(), and process_event().
bool CaloTowerStatus::m_doTime {true} private
Definition at line 65 of file CaloTowerStatus.h.
View newest version in sPHENIX GitHub at line 65 of file CaloTowerStatus.h
Referenced by InitRun(), and process_event().
std::string CaloTowerStatus::m_fieldname_chi2 private
Definition at line 73 of file CaloTowerStatus.h.
View newest version in sPHENIX GitHub at line 73 of file CaloTowerStatus.h
Referenced by InitRun(), and process_event().
std::string CaloTowerStatus::m_fieldname_hotMap private
Definition at line 75 of file CaloTowerStatus.h.
View newest version in sPHENIX GitHub at line 75 of file CaloTowerStatus.h
Referenced by InitRun(), and process_event().
std::string CaloTowerStatus::m_fieldname_time private
Definition at line 71 of file CaloTowerStatus.h.
View newest version in sPHENIX GitHub at line 71 of file CaloTowerStatus.h
Referenced by InitRun(), and process_event().
std::string CaloTowerStatus::m_inputNodePrefix {"TOWERS_"} private
Definition at line 77 of file CaloTowerStatus.h.
View newest version in sPHENIX GitHub at line 77 of file CaloTowerStatus.h
Referenced by CreateNodeTree(), and set_inputNodePrefix().
TowerInfoContainer* CaloTowerStatus::m_raw_towers {nullptr} private
Definition at line 58 of file CaloTowerStatus.h.
View newest version in sPHENIX GitHub at line 58 of file CaloTowerStatus.h
Referenced by CreateNodeTree(), and process_event().
float CaloTowerStatus::time_cut = 2 private
Definition at line 81 of file CaloTowerStatus.h.
View newest version in sPHENIX GitHub at line 81 of file CaloTowerStatus.h
Referenced by process_event(), and set_time_cut().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/CaloReco/CaloTowerStatus.h
coresoftware/blob/master/offline/packages/CaloReco/CaloTowerStatus.cc