Analysis Software: LazyTiling9Alt Class Reference
LazyTiling9Alt Class Reference
Public Member Functions
LazyTiling9Alt (ClusterSequence &cs)
void run ()
Protected Member Functions
void _initialise_tiles ()
int _tile_index (int ieta, int iphi) const
void _bj_remove_from_tiles (TiledJet *const jet)
int _tile_index (const double eta, const double phi) const
void _tj_set_jetinfo (TiledJet *const jet, const int _jets_index)
void _print_tiles (TiledJet *briefjets) const
void _add_neighbours_to_tile_union (const int tile_index, std::vector< int > &tile_union, int &n_near_tiles) const
void _add_untagged_neighbours_to_tile_union (const int tile_index, std::vector< int > &tile_union, int &n_near_tiles)
void _add_untagged_neighbours_to_tile_union_using_max_info (const TiledJet *const jet, std::vector< int > &tile_union, int &n_near_tiles)
void _update_jetX_jetI_NN (TiledJet *jetX, TiledJet *jetI, std::vector< TiledJet * > &jets_for_minheap)
void _set_NN (TiledJet *jetI, std::vector< TiledJet * > &jets_for_minheap)
template<class J >
double _bj_diJ (const J *const jet) const
template<class J >
void _bj_set_jetinfo (J *const jetA, const int _jets_index) const
template<class J >
double _bj_dist (const J *const jetA, const J *const jetB) const
template<class J >
double _bj_dist_not_periodic (const J *const jetA, const J *const jetB) const
Protected Attributes
ClusterSequence & _cs
const std::vector< PseudoJet > & _jets
std::vector< Tile > _tiles
double _Rparam
double _R2
double _invR2
double _tiles_eta_min
double _tiles_eta_max
double _tile_size_eta
double _tile_size_phi
double _tile_half_size_eta
double _tile_half_size_phi
int _n_tiles_phi
int _tiles_ieta_min
int _tiles_ieta_max
std::vector< TiledJet * > _jets_for_minheap
Detailed Description
Definition at line 886 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 886 of file fjcore.cc
Constructor & Destructor Documentation
FJCORE_BEGIN_NAMESPACE LazyTiling9Alt::LazyTiling9Alt (ClusterSequence & cs)
Definition at line 5735 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 5735 of file fjcore.cc
References _initialise_tiles(), _invR2, _R2, and _Rparam.
Member Function Documentation
void LazyTiling9Alt::_add_neighbours_to_tile_union (const int tile_index, std::vector< int > & tile_union, int & n_near_tiles) const protected
Definition at line 5874 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 5874 of file fjcore.cc
References _tiles.
void LazyTiling9Alt::_add_untagged_neighbours_to_tile_union (const int tile_index, std::vector< int > & tile_union, int & n_near_tiles) inline protected
Definition at line 5882 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 5882 of file fjcore.cc
References _tiles.
void LazyTiling9Alt::_add_untagged_neighbours_to_tile_union_using_max_info (const TiledJet *const jet, std::vector< int > & tile_union, int & n_near_tiles) inline protected
Definition at line 5894 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 5894 of file fjcore.cc
References _tiles, Tile::begin_tiles, dist(), Tile::end_tiles, and TiledJet::tile_index.
Referenced by run().
template<class J > double LazyTiling9Alt::_bj_diJ (const J *const jet) const inline protected
Definition at line 917 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 917 of file fjcore.cc
Referenced by run().
template<class J > double LazyTiling9Alt::_bj_dist (const J *const jetA, const J *const jetB) const inline protected
Definition at line 931 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 931 of file fjcore.cc
References INTTVtxZ::dphi, pi, and twopi.
Referenced by _set_NN(), _update_jetX_jetI_NN(), and run().
template<class J > double LazyTiling9Alt::_bj_dist_not_periodic (const J *const jetA, const J *const jetB) const inline protected
Definition at line 938 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 938 of file fjcore.cc
References INTTVtxZ::dphi.
Referenced by run().
void LazyTiling9Alt::_bj_remove_from_tiles (TiledJet *const jet) protected
Definition at line 5850 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 5850 of file fjcore.cc
References _tiles, Tile::head, TiledJet::next, TiledJet::previous, and TiledJet::tile_index.
Referenced by run().
template<class J > void LazyTiling9Alt::_bj_set_jetinfo (J *const jetA, const int _jets_index) const inline protected
Definition at line 922 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 922 of file fjcore.cc
References _cs, _jets, and _R2.
void LazyTiling9Alt::_initialise_tiles () protected
Definition at line 5743 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 5743 of file fjcore.cc
References _jets, _n_tiles_phi, _Rparam, _tile_half_size_eta, _tile_half_size_phi, _tile_index(), _tile_size_eta, _tile_size_phi, _tiles, _tiles_eta_max, _tiles_eta_min, _tiles_ieta_max, _tiles_ieta_min, Tile::begin_tiles, Tile::distance_to_bottom(), Tile::distance_to_centre(), Tile::distance_to_left(), Tile::distance_to_left_bottom(), Tile::distance_to_left_top(), Tile::distance_to_right(), Tile::distance_to_right_bottom(), Tile::distance_to_right_top(), Tile::distance_to_top(), Tile::end_tiles, eta, Tile::eta_max, Tile::eta_min, Tile::head, i, Tile::max_NN_dist, Tile::phi_max, Tile::phi_min, Tile::RH_tiles, Tile::surrounding_tiles, Tile::tagged, twopi, and Tile::use_periodic_delta_phi.
Referenced by LazyTiling9Alt().
void LazyTiling9Alt::_print_tiles (TiledJet * briefjets) const protected
Definition at line 5861 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 5861 of file fjcore.cc
References _tiles, Tile2Base< NN >::head, i, TiledJet::next, and Acts::Experimental::detail::BlueprintHelper::sort().
void LazyTiling9Alt::_set_NN (TiledJet * jetI, std::vector< TiledJet * > & jets_for_minheap) inline protected
Definition at line 5933 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 5933 of file fjcore.cc
References _bj_dist(), _R2, _tiles, Tile::begin_tiles, dist(), Tile::end_tiles, TiledJet::label_minheap_update_needed(), TiledJet::minheap_update_needed(), TiledJet::next, TiledJet::NN, TiledJet::NN_dist, and TiledJet::tile_index.
Referenced by run().
int LazyTiling9Alt::_tile_index (int ieta, int iphi) const inline protected
Definition at line 901 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 901 of file fjcore.cc
References _n_tiles_phi, and _tiles_ieta_min.
Referenced by _initialise_tiles(), and _tj_set_jetinfo().
int LazyTiling9Alt::_tile_index (const double eta, const double phi) const protected
Definition at line 5828 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 5828 of file fjcore.cc
References _n_tiles_phi, _tile_size_eta, _tile_size_phi, _tiles_eta_max, _tiles_eta_min, _tiles_ieta_max, _tiles_ieta_min, and twopi.
void LazyTiling9Alt::_tj_set_jetinfo (TiledJet *const jet, const int _jets_index) inline protected
Definition at line 5840 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 5840 of file fjcore.cc
References _tile_index(), _tiles, Tile::head, TiledJet::next, and TiledJet::previous.
Referenced by run().
void LazyTiling9Alt::_update_jetX_jetI_NN (TiledJet * jetX, TiledJet * jetI, std::vector< TiledJet * > & jets_for_minheap) inline protected
Definition at line 5915 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 5915 of file fjcore.cc
References _bj_dist(), dist(), TiledJet::label_minheap_update_needed(), TiledJet::minheap_update_needed(), TiledJet::NN, and TiledJet::NN_dist.
Referenced by run().
void LazyTiling9Alt::run ()
Definition at line 5953 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 5953 of file fjcore.cc
References _add_untagged_neighbours_to_tile_union_using_max_info(), _bj_diJ(), _bj_dist(), _bj_dist_not_periodic(), _bj_remove_from_tiles(), _cs, _invR2, _jets, TiledJet::_jets_index, _set_NN(), _tiles, _tj_set_jetinfo(), _update_jetX_jetI_NN(), Tile::begin_tiles, dist(), Tile::end_tiles, Tile::head, i, TiledJet::label_minheap_update_done(), Tile::max_NN_dist, MinHeap::minloc(), MinHeap::minval(), n, TiledJet::next, TiledJet::NN, TiledJet::NN_dist, MinHeap::remove(), swap(), Tile::tagged, tile(), TiledJet::tile_index, and MinHeap::update().
Referenced by ClusterSequence::_initialise_and_run_no_decant().
Member Data Documentation
ClusterSequence& LazyTiling9Alt::_cs protected
Definition at line 891 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 891 of file fjcore.cc
Referenced by _bj_set_jetinfo(), and run().
double LazyTiling9Alt::_invR2 protected
Definition at line 894 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 894 of file fjcore.cc
Referenced by LazyTiling9Alt(), and run().
const std::vector<PseudoJet>& LazyTiling9Alt::_jets protected
Definition at line 892 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 892 of file fjcore.cc
Referenced by _bj_set_jetinfo(), _initialise_tiles(), and run().
std::vector<TiledJet *> LazyTiling9Alt::_jets_for_minheap protected
Definition at line 899 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 899 of file fjcore.cc
int LazyTiling9Alt::_n_tiles_phi protected
Definition at line 898 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 898 of file fjcore.cc
Referenced by _initialise_tiles(), and _tile_index().
double LazyTiling9Alt::_R2 protected
Definition at line 894 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 894 of file fjcore.cc
Referenced by _bj_set_jetinfo(), _set_NN(), and LazyTiling9Alt().
double LazyTiling9Alt::_Rparam protected
Definition at line 894 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 894 of file fjcore.cc
Referenced by _initialise_tiles(), and LazyTiling9Alt().
double LazyTiling9Alt::_tile_half_size_eta protected
Definition at line 897 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 897 of file fjcore.cc
Referenced by _initialise_tiles().
double LazyTiling9Alt::_tile_half_size_phi protected
Definition at line 897 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 897 of file fjcore.cc
Referenced by _initialise_tiles().
double LazyTiling9Alt::_tile_size_eta protected
Definition at line 896 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 896 of file fjcore.cc
Referenced by _initialise_tiles(), and _tile_index().
double LazyTiling9Alt::_tile_size_phi protected
Definition at line 896 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 896 of file fjcore.cc
Referenced by _initialise_tiles(), and _tile_index().
std::vector<Tile> LazyTiling9Alt::_tiles protected
Definition at line 893 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 893 of file fjcore.cc
Referenced by _add_neighbours_to_tile_union(), _add_untagged_neighbours_to_tile_union(), _add_untagged_neighbours_to_tile_union_using_max_info(), _bj_remove_from_tiles(), _initialise_tiles(), _print_tiles(), _set_NN(), _tj_set_jetinfo(), and run().
double LazyTiling9Alt::_tiles_eta_max protected
Definition at line 895 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 895 of file fjcore.cc
Referenced by _initialise_tiles(), and _tile_index().
double LazyTiling9Alt::_tiles_eta_min protected
Definition at line 895 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 895 of file fjcore.cc
Referenced by _initialise_tiles(), and _tile_index().
int LazyTiling9Alt::_tiles_ieta_max protected
Definition at line 898 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 898 of file fjcore.cc
Referenced by _initialise_tiles(), and _tile_index().
int LazyTiling9Alt::_tiles_ieta_min protected
Definition at line 898 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 898 of file fjcore.cc
Referenced by _initialise_tiles(), and _tile_index().
The documentation for this class was generated from the following file:
JETSCAPE/blob/main/external_packages/fjcore.cc