Analysis Software: TrkrTruthTrackContainer Class Reference
TrkrTruthTrackContainer Class Reference
#include <coresoftware/blob/master/simulation/g4simulation/g4tracking/TrkrTruthTrackContainer.h>
Public Types
using Map = std::map< unsigned int, TrkrTruthTrack * >
using Iterator = Map::iterator
using ConstIterator = Map::const_iterator
using Range = std::pair< Iterator, Iterator >
using ConstRange = std::pair< ConstIterator, ConstIterator >
Public Member Functions
void Reset () override
reset method
virtual void addTruthTrack (TrkrTruthTrack *)
add a Track
virtual TrkrTruthTrack * getTruthTrack (unsigned int)
virtual TrkrTruthTrack * getTruthTrack (unsigned int, PHG4TruthInfoContainer *)
virtual ConstRange getTruthTrackRange () const
virtual bool hasTrackid (unsigned int) const
virtual Map & getMap ()
int nhw ()
int nhw_cc ()
virtual int nhw_virt ()
void identify (std::ostream &os=std::cout) const override
Public Member Functions inherited from PHObject
PHObject ()
ctor
~PHObject () override
dtor
virtual PHObject * CloneMe () const
Virtual copy constructor.
virtual PHObject * clone () const final
PHObject * Clone (const char *newname="") const final
void Copy (TObject &object) const final
virtual int isValid () const
isValid returns non zero if object contains vailid data
virtual int Integrate () const
virtual int Integrate (PHObject *)
virtual void CopyFrom (const PHObject *obj)
Protected Member Functions
TrkrTruthTrackContainer ()=default
Detailed Description
Definition at line 13 of file TrkrTruthTrackContainer.h.
View newest version in sPHENIX GitHub at line 13 of file TrkrTruthTrackContainer.h
Member Typedef Documentation
using TrkrTruthTrackContainer::ConstIterator = Map::const_iterator
Definition at line 19 of file TrkrTruthTrackContainer.h.
View newest version in sPHENIX GitHub at line 19 of file TrkrTruthTrackContainer.h
using TrkrTruthTrackContainer::ConstRange = std::pair<ConstIterator, ConstIterator>
Definition at line 21 of file TrkrTruthTrackContainer.h.
View newest version in sPHENIX GitHub at line 21 of file TrkrTruthTrackContainer.h
using TrkrTruthTrackContainer::Iterator = Map::iterator
Definition at line 18 of file TrkrTruthTrackContainer.h.
View newest version in sPHENIX GitHub at line 18 of file TrkrTruthTrackContainer.h
using TrkrTruthTrackContainer::Map = std::map<unsigned int, TrkrTruthTrack*>
Definition at line 17 of file TrkrTruthTrackContainer.h.
View newest version in sPHENIX GitHub at line 17 of file TrkrTruthTrackContainer.h
using TrkrTruthTrackContainer::Range = std::pair<Iterator, Iterator>
Definition at line 20 of file TrkrTruthTrackContainer.h.
View newest version in sPHENIX GitHub at line 20 of file TrkrTruthTrackContainer.h
Constructor & Destructor Documentation
TrkrTruthTrackContainer::TrkrTruthTrackContainer () protected default
Member Function Documentation
virtual void TrkrTruthTrackContainer::addTruthTrack (TrkrTruthTrack *) inline virtual
add a Track
Reimplemented in TrkrTruthTrackContainerv1.
Definition at line 27 of file TrkrTruthTrackContainer.h.
View newest version in sPHENIX GitHub at line 27 of file TrkrTruthTrackContainer.h
TrkrTruthTrackContainer::Map & TrkrTruthTrackContainer::getMap () virtual
Reimplemented in TrkrTruthTrackContainerv1.
Definition at line 13 of file TrkrTruthTrackContainer.cc.
View newest version in sPHENIX GitHub at line 13 of file TrkrTruthTrackContainer.cc
Referenced by TpcClusterBuilder::print(), TpcClusterBuilder::print_file(), FillTruthRecoMatchTree::print_mvtx_diagnostics(), PHG4MvtxHitReco::process_event(), and FillTruthRecoMatchTree::process_event().
virtual TrkrTruthTrack* TrkrTruthTrackContainer::getTruthTrack (unsigned int) inline virtual
Reimplemented in TrkrTruthTrackContainerv1.
Definition at line 28 of file TrkrTruthTrackContainer.h.
View newest version in sPHENIX GitHub at line 28 of file TrkrTruthTrackContainer.h
Referenced by PHG4TpcElectronDrift::process_event(), FillTruthRecoMatchTree::process_event(), PHG4InttHitReco::truthcheck_g4hit(), and PHG4MvtxHitReco::truthcheck_g4hit().
virtual TrkrTruthTrack* TrkrTruthTrackContainer::getTruthTrack (unsigned int , PHG4TruthInfoContainer *) inline virtual
Reimplemented in TrkrTruthTrackContainerv1.
Definition at line 29 of file TrkrTruthTrackContainer.h.
View newest version in sPHENIX GitHub at line 29 of file TrkrTruthTrackContainer.h
TrkrTruthTrackContainer::ConstRange TrkrTruthTrackContainer::getTruthTrackRange () const virtual
Reimplemented in TrkrTruthTrackContainerv1.
Definition at line 8 of file TrkrTruthTrackContainer.cc.
View newest version in sPHENIX GitHub at line 8 of file TrkrTruthTrackContainer.cc
virtual bool TrkrTruthTrackContainer::hasTrackid (unsigned int) const inline virtual
Reimplemented in TrkrTruthTrackContainerv1.
Definition at line 32 of file TrkrTruthTrackContainer.h.
View newest version in sPHENIX GitHub at line 32 of file TrkrTruthTrackContainer.h
void TrkrTruthTrackContainer::identify (std::ostream & os = std::cout) const inline override virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from PHObject.
Reimplemented in TrkrTruthTrackContainerv1.
Definition at line 39 of file TrkrTruthTrackContainer.h.
View newest version in sPHENIX GitHub at line 39 of file TrkrTruthTrackContainer.h
References os.
Referenced by PHG4TpcElectronDrift::process_event().
int TrkrTruthTrackContainer::nhw () inline
Definition at line 34 of file TrkrTruthTrackContainer.h.
View newest version in sPHENIX GitHub at line 34 of file TrkrTruthTrackContainer.h
int TrkrTruthTrackContainer::nhw_cc ()
Definition at line 18 of file TrkrTruthTrackContainer.cc.
View newest version in sPHENIX GitHub at line 18 of file TrkrTruthTrackContainer.cc
virtual int TrkrTruthTrackContainer::nhw_virt () inline virtual
Reimplemented in TrkrTruthTrackContainerv1.
Definition at line 36 of file TrkrTruthTrackContainer.h.
View newest version in sPHENIX GitHub at line 36 of file TrkrTruthTrackContainer.h
void TrkrTruthTrackContainer::Reset () inline override virtual
reset method
Reimplemented from PHObject.
Reimplemented in TrkrTruthTrackContainerv1.
Definition at line 24 of file TrkrTruthTrackContainer.h.
View newest version in sPHENIX GitHub at line 24 of file TrkrTruthTrackContainer.h
The documentation for this class was generated from the following files:
coresoftware/blob/master/simulation/g4simulation/g4tracking/TrkrTruthTrackContainer.h
coresoftware/blob/master/simulation/g4simulation/g4tracking/TrkrTruthTrackContainer.cc