Analysis Software: Acts::ConstantBField Exception Reference
Acts::ConstantBField Exception Reference final
#include <acts/blob/sPHENIX/Core/include/Acts/MagneticField/ConstantBField.hpp>
Classes
struct Cache
Public Member Functions
ConstantBField (Vector3D B)
ConstantBField (double Bx=0., double By=0., double Bz=0.)
construct constant magnetic field from components
Vector3D getField (const Vector3D &) const
retrieve magnetic field value
Vector3D getField (const Vector3D &, Cache &) const
retrieve magnetic field value
Vector3D getFieldGradient (const Vector3D &, ActsMatrixD< 3, 3 > &) const
retrieve magnetic field value & its gradient
Vector3D getFieldGradient (const Vector3D &, ActsMatrixD< 3, 3 > &, Cache &) const
retrieve magnetic field value & its gradient
bool isInside (const Vector3D &) const
check whether given 3D position is inside look-up domain
void setField (double Bx, double By, double Bz)
update magnetic field vector from components
void setField (const Vector3D &B)
update magnetic field vector
Private Attributes
Vector3D m_BField
magnetic field vector
Detailed Description
This class implements a simple constant magnetic field. The magnetic field value has to be set at creation time, but can be updated later on.
Definition at line 20 of file ConstantBField.hpp.
View newest version in sPHENIX GitHub at line 20 of file ConstantBField.hpp
Constructor & Destructor Documentation
Acts::ConstantBField::ConstantBField (Vector3D B) inline explicit
Construct constant magnetic field from field vector.
Parameters
[in] B magnetic field vector in global coordinate system
Definition at line 30 of file ConstantBField.hpp.
View newest version in sPHENIX GitHub at line 30 of file ConstantBField.hpp
Acts::ConstantBField::ConstantBField (double Bx = 0., double By = 0., double Bz = 0.) inline
construct constant magnetic field from components
Parameters
[in] Bx magnetic field component in global x-direction
[in] By magnetic field component in global y-direction
[in] Bz magnetic field component in global z-direction
Definition at line 37 of file ConstantBField.hpp.
View newest version in sPHENIX GitHub at line 37 of file ConstantBField.hpp
Member Function Documentation
Vector3D Acts::ConstantBField::getField (const Vector3D &) const inline
retrieve magnetic field value
Parameters
[in] position global position
Returns
magnetic field vector
Note
The position is ignored and only kept as argument to provide a consistent interface with other magnetic field services.
Definition at line 47 of file ConstantBField.hpp.
View newest version in sPHENIX GitHub at line 47 of file ConstantBField.hpp
References m_BField.
Referenced by Acts::Test::BOOST_AUTO_TEST_CASE(), and Acts::Test::BOOST_DATA_TEST_CASE().
Vector3D Acts::ConstantBField::getField (const Vector3D & , Cache &) const inline
retrieve magnetic field value
Parameters
[in] position global position
[in] cache Cache object (is ignored)
Returns
magnetic field vector
Note
The position is ignored and only kept as argument to provide a consistent interface with other magnetic field services.
Definition at line 57 of file ConstantBField.hpp.
View newest version in sPHENIX GitHub at line 57 of file ConstantBField.hpp
References m_BField.
Vector3D Acts::ConstantBField::getFieldGradient (const Vector3D & , ActsMatrixD< 3, 3 > &) const inline
retrieve magnetic field value & its gradient
Parameters
[in] position global position
[out] derivative gradient of magnetic field vector as (3x3) matrix
Returns
magnetic field vector
Note
The position is ignored and only kept as argument to provide a consistent interface with other magnetic field services.
currently the derivative is not calculated
Definition at line 71 of file ConstantBField.hpp.
View newest version in sPHENIX GitHub at line 71 of file ConstantBField.hpp
References m_BField.
Vector3D Acts::ConstantBField::getFieldGradient (const Vector3D & , ActsMatrixD< 3, 3 > & , Cache &) const inline
retrieve magnetic field value & its gradient
Parameters
[in] position global position
[out] derivative gradient of magnetic field vector as (3x3) matrix
[in] cache Cache object (is ignored)
Returns
magnetic field vector
Note
The position is ignored and only kept as argument to provide a consistent interface with other magnetic field services.
currently the derivative is not calculated
Definition at line 87 of file ConstantBField.hpp.
View newest version in sPHENIX GitHub at line 87 of file ConstantBField.hpp
References m_BField.
bool Acts::ConstantBField::isInside (const Vector3D &) const inline
check whether given 3D position is inside look-up domain
Parameters
[in] position global 3D position
Returns
true if position is inside the defined look-up grid, otherwise false
Note
The method will always return true for the constant B-Field
Definition at line 99 of file ConstantBField.hpp.
View newest version in sPHENIX GitHub at line 99 of file ConstantBField.hpp
void Acts::ConstantBField::setField (double Bx, double By, double Bz) inline
update magnetic field vector from components
Parameters
[in] Bx magnetic field component in global x-direction
[in] By magnetic field component in global y-direction
[in] Bz magnetic field component in global z-direction
Definition at line 106 of file ConstantBField.hpp.
View newest version in sPHENIX GitHub at line 106 of file ConstantBField.hpp
References Acts::IntegrationTest::Bz, and m_BField.
Referenced by Acts::Test::BOOST_AUTO_TEST_CASE(), and Acts::Test::BOOST_DATA_TEST_CASE().
void Acts::ConstantBField::setField (const Vector3D & B) inline
update magnetic field vector
Parameters
[in] B magnetic field vector in global coordinate system
Definition at line 111 of file ConstantBField.hpp.
View newest version in sPHENIX GitHub at line 111 of file ConstantBField.hpp
References m_BField.
Member Data Documentation
Vector3D Acts::ConstantBField::m_BField private
magnetic field vector
Definition at line 115 of file ConstantBField.hpp.
View newest version in sPHENIX GitHub at line 115 of file ConstantBField.hpp
Referenced by getField(), getFieldGradient(), and setField().
The documentation for this exception was generated from the following file:
acts/blob/sPHENIX/Core/include/Acts/MagneticField/ConstantBField.hpp