Analysis Software: jetrtrack Class Reference
jetrtrack Class Reference
#include <analysis/blob/master/JS-Jet/JetRTrack/src/jetrtrack.h>
Public Member Functions
jetrtrack (const std::string &name="jetrtrack")
virtual ~jetrtrack ()
void SetOutputFileName (std::string outfilename)
int Init (PHCompositeNode *topNode) override
int InitRun (PHCompositeNode *topNode) override
int process_event (PHCompositeNode *topNode) override
int ResetEvent (PHCompositeNode *topNode) override
Clean up internals after each event.
int EndRun (const int runnumber) override
Called at the end of each run.
int End (PHCompositeNode *topNode) override
Called at the end of all processing.
int Reset (PHCompositeNode *) override
Reset.
void Print (const std::string &what="ALL") const override
Public Member Functions inherited from SubsysReco
~SubsysReco () override
void Print (const std::string &="ALL") const override
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Private Member Functions
Fun4AllHistoManager * get_HistoManager ()
Private Attributes
std::vector< float > m_tjet_pt
std::vector< float > m_tjet_phi
std::vector< float > m_tjet_eta
std::vector< float > m_tjet_jcpt
std::vector< float > m_rjet_pt
std::vector< float > m_rjet_phi
std::vector< float > m_rjet_eta
std::vector< float > m_dr
std::vector< float > m_trk_pt
std::vector< float > m_trk_eta
std::vector< float > m_trk_phi
std::vector< float > m_trk_qual
std::vector< float > m_nmvtxhits
std::vector< float > m_tp_pt
std::vector< float > m_tp_px
std::vector< float > m_tp_py
std::vector< float > m_tp_pz
std::vector< float > m_tp_phi
std::vector< float > m_tp_eta
std::vector< float > m_jc_pt
std::vector< int > m_jc_index
std::vector< float > m_jc_phi
std::vector< float > m_jc_eta
std::vector< int > m_tp_pid
float m_zvtx
int m_centrality
int m_impactparam
std::string m_outfilename
float m_tjet_pt2
TFile * outfile
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = std::numeric_limits<int>::max() - 10
}
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Detailed Description
Definition at line 26 of file jetrtrack.h.
View newest version in sPHENIX GitHub at line 26 of file jetrtrack.h
Constructor & Destructor Documentation
jetrtrack::jetrtrack (const std::string & name = "jetrtrack")
Definition at line 62 of file jetrtrack.cc.
View newest version in sPHENIX GitHub at line 62 of file jetrtrack.cc
jetrtrack::~jetrtrack () virtual
Definition at line 69 of file jetrtrack.cc.
View newest version in sPHENIX GitHub at line 69 of file jetrtrack.cc
Member Function Documentation
int jetrtrack::End (PHCompositeNode * topNode) override virtual
Called at the end of all processing.
Reimplemented from SubsysReco.
Definition at line 510 of file jetrtrack.cc.
View newest version in sPHENIX GitHub at line 510 of file jetrtrack.cc
References assert, PHTFileServer::cd(), Fun4AllReturnCodes::EVENT_OK, PHTFileServer::get(), get_HistoManager(), Fun4AllHistoManager::getHisto(), i, m_outfilename, and Fun4AllHistoManager::nHistos().
int jetrtrack::EndRun (const int runnumber) override virtual
Called at the end of each run.
Reimplemented from SubsysReco.
Definition at line 503 of file jetrtrack.cc.
View newest version in sPHENIX GitHub at line 503 of file jetrtrack.cc
References Fun4AllReturnCodes::EVENT_OK.
Fun4AllHistoManager * jetrtrack::get_HistoManager () private
Definition at line 84 of file jetrtrack.cc.
View newest version in sPHENIX GitHub at line 84 of file jetrtrack.cc
References assert, Fun4AllServer::getHistoManager(), Fun4AllServer::instance(), and Fun4AllServer::registerHistoManager().
Referenced by End(), InitRun(), and process_event().
int jetrtrack::Init (PHCompositeNode *) override virtual
Called during initialization. Typically this is where you can book histograms, and e.g. register them to Fun4AllServer (so they can be output to file using Fun4AllServer::dumpHistos() method).
Reimplemented from SubsysReco.
Definition at line 75 of file jetrtrack.cc.
View newest version in sPHENIX GitHub at line 75 of file jetrtrack.cc
References Fun4AllReturnCodes::EVENT_OK, and PHCompositeNode::print().
int jetrtrack::InitRun (PHCompositeNode * topNode) override virtual
Called for first event when run number is known. Typically this is where you may want to fetch data from database, because you know the run number. A place to book histograms which have to know the run number.
Reimplemented from SubsysReco.
Definition at line 102 of file jetrtrack.cc.
View newest version in sPHENIX GitHub at line 102 of file jetrtrack.cc
References assert, Fun4AllReturnCodes::EVENT_OK, PHTFileServer::get(), get_HistoManager(), m_centrality, m_jc_eta, m_jc_index, m_jc_phi, m_jc_pt, m_nmvtxhits, m_outfilename, m_rjet_eta, m_rjet_phi, m_rjet_pt, m_tjet_eta, m_tjet_jcpt, m_tjet_phi, m_tjet_pt, m_tp_eta, m_tp_phi, m_tp_pid, m_tp_pt, m_tp_px, m_tp_py, m_tp_pz, m_trk_eta, m_trk_phi, m_trk_pt, m_trk_qual, m_zvtx, PHTFileServer::open(), Fun4AllHistoManager::registerHisto(), and tree.
void jetrtrack::Print (const std::string & what = "ALL") const override virtual
Print out some info about this module.
Parameters
what can be used to specify what to print exactly.
Reimplemented from Fun4AllBase.
Definition at line 538 of file jetrtrack.cc.
View newest version in sPHENIX GitHub at line 538 of file jetrtrack.cc
int jetrtrack::process_event (PHCompositeNode * topNode) override virtual
Called for each event. This is where you do the real work.
Loop over the G4 truth (stable) particles
Get this truth particle
Get this particles momentum, etc.
Reimplemented from SubsysReco.
Definition at line 167 of file jetrtrack.cc.
View newest version in sPHENIX GitHub at line 167 of file jetrtrack.cc
References assert, SvtxTrackMap::begin(), SvtxVertexMap::begin(), JetMap::begin(), Jet::begin_comp(), mvtx_utils::comp(), INTTVtxZ::dphi, SvtxVertexMap::empty(), SvtxTrackMap::end(), JetMap::end(), Jet::end_comp(), Fun4AllReturnCodes::EVENT_OK, CentralityInfo::get_centile(), PHG4Particle::get_e(), SvtxTrack::get_eta(), Jet::get_eta(), get_HistoManager(), SvtxTrack::get_phi(), Jet::get_phi(), PHG4Particle::get_pid(), SvtxTrack::get_pt(), Jet::get_pt(), PHG4Particle::get_px(), PHG4Particle::get_py(), PHG4Particle::get_pz(), SvtxTrack::get_quality(), SvtxTrack::get_silicon_seed(), SvtxVertex::get_z(), Fun4AllHistoManager::getHisto(), PHG4TruthInfoContainer::GetParticle(), PHG4TruthInfoContainer::GetPrimaryParticleRange(), k, m_centrality, m_dr, m_jc_eta, m_jc_index, m_jc_phi, m_jc_pt, m_nmvtxhits, m_rjet_eta, m_rjet_phi, m_rjet_pt, m_tjet_eta, m_tjet_jcpt, m_tjet_phi, m_tjet_pt, m_tp_eta, m_tp_phi, m_tp_pid, m_tp_pt, m_tp_px, m_tp_py, m_tp_pz, m_trk_eta, m_trk_phi, m_trk_pt, m_trk_qual, m_zvtx, pi, TrackSeed::size_cluster_keys(), and tree.
int jetrtrack::Reset (PHCompositeNode * topNode) override virtual
Reset.
Reimplemented from SubsysReco.
Definition at line 531 of file jetrtrack.cc.
View newest version in sPHENIX GitHub at line 531 of file jetrtrack.cc
References Fun4AllReturnCodes::EVENT_OK.
int jetrtrack::ResetEvent (PHCompositeNode * topNode) override virtual
Clean up internals after each event.
Reimplemented from SubsysReco.
Definition at line 462 of file jetrtrack.cc.
View newest version in sPHENIX GitHub at line 462 of file jetrtrack.cc
References Fun4AllReturnCodes::EVENT_OK, m_dr, m_jc_eta, m_jc_index, m_jc_phi, m_jc_pt, m_nmvtxhits, m_rjet_eta, m_rjet_phi, m_rjet_pt, m_tjet_eta, m_tjet_jcpt, m_tjet_phi, m_tjet_pt, m_tp_eta, m_tp_phi, m_tp_pid, m_tp_pt, m_tp_px, m_tp_py, m_tp_pz, m_trk_eta, m_trk_phi, m_trk_pt, and m_trk_qual.
void jetrtrack::SetOutputFileName (std::string outfilename) inline
Called during initialization. Typically this is where you can book histograms, and e.g. register them to Fun4AllServer (so they can be output to file using Fun4AllServer::dumpHistos() method).
Definition at line 39 of file jetrtrack.h.
View newest version in sPHENIX GitHub at line 39 of file jetrtrack.h
References m_outfilename.
Referenced by Fun4All_RTrack().
Member Data Documentation
int jetrtrack::m_centrality private
Definition at line 117 of file jetrtrack.h.
View newest version in sPHENIX GitHub at line 117 of file jetrtrack.h
Referenced by InitRun(), and process_event().
std::vector<float> jetrtrack::m_dr private
Definition at line 92 of file jetrtrack.h.
View newest version in sPHENIX GitHub at line 92 of file jetrtrack.h
Referenced by process_event(), and ResetEvent().
int jetrtrack::m_impactparam private
Definition at line 118 of file jetrtrack.h.
View newest version in sPHENIX GitHub at line 118 of file jetrtrack.h
std::vector<float> jetrtrack::m_jc_eta private
Definition at line 110 of file jetrtrack.h.
View newest version in sPHENIX GitHub at line 110 of file jetrtrack.h
Referenced by InitRun(), process_event(), and ResetEvent().
std::vector<int> jetrtrack::m_jc_index private
Definition at line 108 of file jetrtrack.h.
View newest version in sPHENIX GitHub at line 108 of file jetrtrack.h
Referenced by InitRun(), process_event(), and ResetEvent().
std::vector<float> jetrtrack::m_jc_phi private
Definition at line 109 of file jetrtrack.h.
View newest version in sPHENIX GitHub at line 109 of file jetrtrack.h
Referenced by InitRun(), process_event(), and ResetEvent().
std::vector<float> jetrtrack::m_jc_pt private
Definition at line 107 of file jetrtrack.h.
View newest version in sPHENIX GitHub at line 107 of file jetrtrack.h
Referenced by InitRun(), process_event(), and ResetEvent().
std::vector<float> jetrtrack::m_nmvtxhits private
Definition at line 97 of file jetrtrack.h.
View newest version in sPHENIX GitHub at line 97 of file jetrtrack.h
Referenced by InitRun(), process_event(), and ResetEvent().
std::string jetrtrack::m_outfilename private
Definition at line 119 of file jetrtrack.h.
View newest version in sPHENIX GitHub at line 119 of file jetrtrack.h
Referenced by End(), InitRun(), and SetOutputFileName().
std::vector<float> jetrtrack::m_rjet_eta private
Definition at line 91 of file jetrtrack.h.
View newest version in sPHENIX GitHub at line 91 of file jetrtrack.h
Referenced by InitRun(), process_event(), and ResetEvent().
std::vector<float> jetrtrack::m_rjet_phi private
Definition at line 90 of file jetrtrack.h.
View newest version in sPHENIX GitHub at line 90 of file jetrtrack.h
Referenced by InitRun(), process_event(), and ResetEvent().
std::vector<float> jetrtrack::m_rjet_pt private
Definition at line 89 of file jetrtrack.h.
View newest version in sPHENIX GitHub at line 89 of file jetrtrack.h
Referenced by InitRun(), process_event(), and ResetEvent().
std::vector<float> jetrtrack::m_tjet_eta private
Definition at line 85 of file jetrtrack.h.
View newest version in sPHENIX GitHub at line 85 of file jetrtrack.h
Referenced by InitRun(), process_event(), and ResetEvent().
std::vector<float> jetrtrack::m_tjet_jcpt private
Definition at line 86 of file jetrtrack.h.
View newest version in sPHENIX GitHub at line 86 of file jetrtrack.h
Referenced by InitRun(), process_event(), and ResetEvent().
std::vector<float> jetrtrack::m_tjet_phi private
Definition at line 84 of file jetrtrack.h.
View newest version in sPHENIX GitHub at line 84 of file jetrtrack.h
Referenced by InitRun(), process_event(), and ResetEvent().
std::vector<float> jetrtrack::m_tjet_pt private
Definition at line 83 of file jetrtrack.h.
View newest version in sPHENIX GitHub at line 83 of file jetrtrack.h
Referenced by InitRun(), process_event(), and ResetEvent().
float jetrtrack::m_tjet_pt2 private
Definition at line 121 of file jetrtrack.h.
View newest version in sPHENIX GitHub at line 121 of file jetrtrack.h
std::vector<float> jetrtrack::m_tp_eta private
Definition at line 104 of file jetrtrack.h.
View newest version in sPHENIX GitHub at line 104 of file jetrtrack.h
Referenced by InitRun(), process_event(), and ResetEvent().
std::vector<float> jetrtrack::m_tp_phi private
Definition at line 103 of file jetrtrack.h.
View newest version in sPHENIX GitHub at line 103 of file jetrtrack.h
Referenced by InitRun(), process_event(), and ResetEvent().
std::vector<int> jetrtrack::m_tp_pid private
Definition at line 113 of file jetrtrack.h.
View newest version in sPHENIX GitHub at line 113 of file jetrtrack.h
Referenced by InitRun(), process_event(), and ResetEvent().
std::vector<float> jetrtrack::m_tp_pt private
Definition at line 99 of file jetrtrack.h.
View newest version in sPHENIX GitHub at line 99 of file jetrtrack.h
Referenced by InitRun(), process_event(), and ResetEvent().
std::vector<float> jetrtrack::m_tp_px private
Definition at line 100 of file jetrtrack.h.
View newest version in sPHENIX GitHub at line 100 of file jetrtrack.h
Referenced by InitRun(), process_event(), and ResetEvent().
std::vector<float> jetrtrack::m_tp_py private
Definition at line 101 of file jetrtrack.h.
View newest version in sPHENIX GitHub at line 101 of file jetrtrack.h
Referenced by InitRun(), process_event(), and ResetEvent().
std::vector<float> jetrtrack::m_tp_pz private
Definition at line 102 of file jetrtrack.h.
View newest version in sPHENIX GitHub at line 102 of file jetrtrack.h
Referenced by InitRun(), process_event(), and ResetEvent().
std::vector<float> jetrtrack::m_trk_eta private
Definition at line 94 of file jetrtrack.h.
View newest version in sPHENIX GitHub at line 94 of file jetrtrack.h
Referenced by InitRun(), process_event(), and ResetEvent().
std::vector<float> jetrtrack::m_trk_phi private
Definition at line 95 of file jetrtrack.h.
View newest version in sPHENIX GitHub at line 95 of file jetrtrack.h
Referenced by InitRun(), process_event(), and ResetEvent().
std::vector<float> jetrtrack::m_trk_pt private
Definition at line 93 of file jetrtrack.h.
View newest version in sPHENIX GitHub at line 93 of file jetrtrack.h
Referenced by InitRun(), process_event(), and ResetEvent().
std::vector<float> jetrtrack::m_trk_qual private
Definition at line 96 of file jetrtrack.h.
View newest version in sPHENIX GitHub at line 96 of file jetrtrack.h
Referenced by InitRun(), process_event(), and ResetEvent().
float jetrtrack::m_zvtx private
Definition at line 115 of file jetrtrack.h.
View newest version in sPHENIX GitHub at line 115 of file jetrtrack.h
Referenced by InitRun(), and process_event().
TFile* jetrtrack::outfile private
Definition at line 125 of file jetrtrack.h.
View newest version in sPHENIX GitHub at line 125 of file jetrtrack.h
The documentation for this class was generated from the following files:
analysis/blob/master/JS-Jet/JetRTrack/src/jetrtrack.h
analysis/blob/master/JS-Jet/JetRTrack/src/jetrtrack.cc