Analysis Software: acts/blob/sPHENIX/Examples/Run/Fatras/Common/src/FatrasCommon.cpp File Reference
FatrasCommon.cpp File Reference
#include "ActsExamples/Fatras/FatrasCommon.hpp"
#include "ActsExamples/Detector/IBaseDetector.hpp"
#include "ActsExamples/Fatras/FatrasSimulation.hpp"
#include "ActsExamples/Framework/RandomNumbers.hpp"
#include "ActsExamples/Framework/Sequencer.hpp"
#include "ActsExamples/Generators/EventGenerator.hpp"
#include "ActsExamples/Geometry/CommonGeometry.hpp"
#include "ActsExamples/Io/Csv/CsvParticleReader.hpp"
#include "ActsExamples/Io/Csv/CsvParticleWriter.hpp"
#include "ActsExamples/Io/Csv/CsvSimHitWriter.hpp"
#include "ActsExamples/Io/Root/RootParticleWriter.hpp"
#include "ActsExamples/Io/Root/RootSimHitWriter.hpp"
#include "ActsExamples/Options/CommonOptions.hpp"
#include "ActsExamples/Options/FatrasOptions.hpp"
#include "ActsExamples/Options/MagneticFieldOptions.hpp"
#include "ActsExamples/Options/ParticleGunOptions.hpp"
#include "ActsExamples/Simulation/CommonSimulation.hpp"
#include "ActsExamples/TruthTracking/ParticleSelector.hpp"
#include "ActsExamples/Utilities/Paths.hpp"
#include <memory>
#include <string>
#include <boost/program_options.hpp>
Functions
int runFatras (int argc, char *argv[], const std::shared_ptr< ActsExamples::IBaseDetector > &detector)
Function Documentation
int runFatras (int argc, char * argv[], const std::shared_ptr< ActsExamples::IBaseDetector > & detector)
Fatras main function
Standard arguments
Parameters
argc and
argv[] are forwarded
detector abstracts the used detector input
Definition at line 66 of file FatrasCommon.cpp.
View newest version in sPHENIX GitHub at line 66 of file FatrasCommon.cpp
References ActsExamples::Options::addFatrasOptions(), ActsExamples::Options::addGeometryOptions(), ActsExamples::Simulation::addInputOptions(), ActsExamples::Options::addMagneticFieldOptions(), ActsExamples::Options::addMaterialOptions(), ActsExamples::Options::addOutputOptions(), ActsExamples::Options::addRandomNumbersOptions(), ActsExamples::Options::addSequencerOptions(), ActsExamples::Geometry::build(), ActsExamples::Options::makeDefaultOptions(), ActsExamples::Options::parse(), ActsExamples::Options::readRandomNumbersConfig(), ActsExamples::Options::readSequencerConfig(), ActsExamples::Simulation::setupInput(), ActsExamples::Simulation::setupOutput(), and digitization_config::trackingGeometry.