Analysis Software: NNH< BJ, I > Class Template Reference
NNH< BJ, I > Class Template Reference
#include <JETSCAPE/blob/main/external_packages/fjcore.hh>
Classes
class NNBJ
Public Member Functions
NNH (const std::vector< PseudoJet > &jets)
NNH (const std::vector< PseudoJet > &jets, I *info)
void start (const std::vector< PseudoJet > &jets)
double dij_min (int &iA, int &iB)
void remove_jet (int iA)
void merge_jets (int iA, int iB, const PseudoJet &jet, int jet_index)
~NNH ()
Public Member Functions inherited from NNBase< I >
NNBase ()
NNBase (I *info)
virtual ~NNBase ()
Public Member Functions inherited from NNInfo< I >
NNInfo ()
NNInfo (I *info)
template<class BJ >
void init_jet (BJ *briefjet, const fjcore::PseudoJet &jet, int index)
Private Member Functions
void set_NN_crosscheck (NNBJ *jet, NNBJ *begin, NNBJ *end)
void set_NN_nocross (NNBJ *jet, NNBJ *begin, NNBJ *end)
Private Attributes
NNBJ * briefjets
NNBJ * head
NNBJ * tail
int n
std::vector< NNBJ * > where_is
Detailed Description
template<class BJ, class I = _NoInfo>
class NNH< BJ, I >
Definition at line 1767 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 1767 of file fjcore.hh
Constructor & Destructor Documentation
template<class BJ , class I = _NoInfo> NNH< BJ, I >::NNH (const std::vector< PseudoJet > & jets) inline
Definition at line 1769 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 1769 of file fjcore.hh
References I, and NNH< BJ, I >::start().
template<class BJ , class I = _NoInfo> NNH< BJ, I >::NNH (const std::vector< PseudoJet > & jets, I * info) inline
Definition at line 1770 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 1770 of file fjcore.hh
References I, and NNH< BJ, I >::start().
template<class BJ , class I = _NoInfo> NNH< BJ, I >::~NNH () inline
Definition at line 1775 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 1775 of file fjcore.hh
References NNH< BJ, I >::briefjets.
Member Function Documentation
template<class BJ , class I > double NNH< BJ, I >::dij_min (int & iA, int & iB) virtual
Implements NNBase< I >.
Definition at line 1824 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 1824 of file fjcore.hh
References i, NNH< BJ, I >::NNBJ::index(), n, and NNH< BJ, I >::NNBJ::NN.
template<class BJ , class I > void NNH< BJ, I >::merge_jets (int iA, int iB, const PseudoJet & jet, int jet_index) virtual
Implements NNBase< I >.
Definition at line 1848 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 1848 of file fjcore.hh
References dist(), NNH< BJ, I >::NNBJ::index(), n, NNH< BJ, I >::NNBJ::NN, NNH< BJ, I >::NNBJ::NN_dist, and swap().
template<class BJ , class I > void NNH< BJ, I >::remove_jet (int iA) virtual
Implements NNBase< I >.
Definition at line 1838 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 1838 of file fjcore.hh
References NNH< BJ, I >::NNBJ::index(), and n.
template<class BJ , class I > void NNH< BJ, I >::set_NN_crosscheck (NNBJ * jet, NNBJ * begin, NNBJ * end) private
Definition at line 1879 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 1879 of file fjcore.hh
References dist(), end, NN, NNH< BJ, I >::NNBJ::NN, and NNH< BJ, I >::NNBJ::NN_dist.
template<class BJ , class I > void NNH< BJ, I >::set_NN_nocross (NNBJ * jet, NNBJ * begin, NNBJ * end) private
Definition at line 1897 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 1897 of file fjcore.hh
References dist(), end, NN, NNH< BJ, I >::NNBJ::NN, and NNH< BJ, I >::NNBJ::NN_dist.
template<class BJ , class I > void NNH< BJ, I >::start (const std::vector< PseudoJet > & jets) virtual
Implements NNBase< I >.
Definition at line 1808 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 1808 of file fjcore.hh
References i, and n.
Referenced by NNH< BJ, I >::NNH().
Member Data Documentation
template<class BJ , class I = _NoInfo> NNBJ* NNH< BJ, I >::briefjets private
Definition at line 1782 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 1782 of file fjcore.hh
Referenced by NNH< BJ, I >::~NNH().
template<class BJ , class I = _NoInfo> NNBJ* NNH< BJ, I >::head private
Definition at line 1783 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 1783 of file fjcore.hh
template<class BJ , class I = _NoInfo> int NNH< BJ, I >::n private
Definition at line 1784 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 1784 of file fjcore.hh
template<class BJ , class I = _NoInfo> NNBJ * NNH< BJ, I >::tail private
Definition at line 1783 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 1783 of file fjcore.hh
template<class BJ , class I = _NoInfo> std::vector<NNBJ *> NNH< BJ, I >::where_is private
Definition at line 1785 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 1785 of file fjcore.hh
The documentation for this class was generated from the following file:
JETSCAPE/blob/main/external_packages/fjcore.hh