Analysis Software: PHCosmicSeedCombiner Class Reference
PHCosmicSeedCombiner Class Reference
#include <coresoftware/blob/master/offline/packages/trackreco/PHCosmicSeedCombiner.h>
Public Member Functions
PHCosmicSeedCombiner (const std::string &name="PHCosmicSeedCombiner")
~PHCosmicSeedCombiner () override
int Init (PHCompositeNode *topNode) override
int InitRun (PHCompositeNode *topNode) override
int process_event (PHCompositeNode *topNode) override
int End (PHCompositeNode *topNode) override
Called at the end of all processing.
void dphiCut (float dphi)
void detaCut (float deta)
Public Member Functions inherited from SubsysReco
~SubsysReco () override
virtual int EndRun (const int)
Called at the end of each run.
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
void Print (const std::string &="ALL") const override
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Private Member Functions
int getNodes (PHCompositeNode *topNode)
void addKeys (TrackSeed *seedToAddTo, TrackSeed *seedToAdd)
Private Attributes
ActsGeometry * m_tGeometry = nullptr
TrkrClusterContainer * m_clusterContainer = nullptr
TrackSeedContainer * m_seedMap = nullptr
TrackSeedContainer * m_tpcSeeds = nullptr
TrackSeedContainer * m_siliconSeeds = nullptr
float m_dphiCut = 0.04
float m_detaCut = 0.02
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = std::numeric_limits<int>::max() - 10
}
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Detailed Description
Definition at line 16 of file PHCosmicSeedCombiner.h.
View newest version in sPHENIX GitHub at line 16 of file PHCosmicSeedCombiner.h
Constructor & Destructor Documentation
PHCosmicSeedCombiner::PHCosmicSeedCombiner (const std::string & name = "PHCosmicSeedCombiner")
Definition at line 24 of file PHCosmicSeedCombiner.cc.
View newest version in sPHENIX GitHub at line 24 of file PHCosmicSeedCombiner.cc
PHCosmicSeedCombiner::~PHCosmicSeedCombiner () override
Definition at line 30 of file PHCosmicSeedCombiner.cc.
View newest version in sPHENIX GitHub at line 30 of file PHCosmicSeedCombiner.cc
Member Function Documentation
void PHCosmicSeedCombiner::addKeys (TrackSeed * seedToAddTo, TrackSeed * seedToAdd) private
Definition at line 151 of file PHCosmicSeedCombiner.cc.
View newest version in sPHENIX GitHub at line 151 of file PHCosmicSeedCombiner.cc
References TrackSeed::begin_cluster_keys(), TrackSeed::end_cluster_keys(), and TrackSeed::insert_cluster_key().
Referenced by process_event().
void PHCosmicSeedCombiner::detaCut (float deta) inline
Definition at line 29 of file PHCosmicSeedCombiner.h.
View newest version in sPHENIX GitHub at line 29 of file PHCosmicSeedCombiner.h
References m_detaCut.
void PHCosmicSeedCombiner::dphiCut (float dphi) inline
Definition at line 28 of file PHCosmicSeedCombiner.h.
View newest version in sPHENIX GitHub at line 28 of file PHCosmicSeedCombiner.h
References INTTVtxZ::dphi, and m_dphiCut.
int PHCosmicSeedCombiner::End (PHCompositeNode *) override virtual
Called at the end of all processing.
Reimplemented from SubsysReco.
Definition at line 161 of file PHCosmicSeedCombiner.cc.
View newest version in sPHENIX GitHub at line 161 of file PHCosmicSeedCombiner.cc
References Fun4AllReturnCodes::EVENT_OK.
int PHCosmicSeedCombiner::getNodes (PHCompositeNode * topNode) private
Definition at line 165 of file PHCosmicSeedCombiner.cc.
View newest version in sPHENIX GitHub at line 165 of file PHCosmicSeedCombiner.cc
References Fun4AllReturnCodes::ABORTEVENT, Fun4AllReturnCodes::EVENT_OK, m_clusterContainer, m_seedMap, m_siliconSeeds, m_tGeometry, m_tpcSeeds, and PHWHERE.
Referenced by InitRun().
int PHCosmicSeedCombiner::Init (PHCompositeNode *) override virtual
Called during initialization. Typically this is where you can book histograms, and e.g. register them to Fun4AllServer (so they can be output to file using Fun4AllServer::dumpHistos() method).
Reimplemented from SubsysReco.
Definition at line 35 of file PHCosmicSeedCombiner.cc.
View newest version in sPHENIX GitHub at line 35 of file PHCosmicSeedCombiner.cc
References Fun4AllReturnCodes::EVENT_OK.
int PHCosmicSeedCombiner::InitRun (PHCompositeNode *) override virtual
Called for first event when run number is known. Typically this is where you may want to fetch data from database, because you know the run number.
Reimplemented from SubsysReco.
Definition at line 41 of file PHCosmicSeedCombiner.cc.
View newest version in sPHENIX GitHub at line 41 of file PHCosmicSeedCombiner.cc
References getNodes().
int PHCosmicSeedCombiner::process_event (PHCompositeNode *) override virtual
Called for each event. This is where you do the real work.
phis are the same, so we subtract to check
If they are back to back, dphi=pi
etas are opposite each other, so we add them
add the clusters to the tpc seed and delete seed 2 since it is from the same track
Reimplemented from SubsysReco.
Definition at line 47 of file PHCosmicSeedCombiner.cc.
View newest version in sPHENIX GitHub at line 47 of file PHCosmicSeedCombiner.cc
References addKeys(), TrackSeedContainer::begin(), INTTVtxZ::dphi, TrackSeedContainer::end(), TrackSeedContainer::erase(), Fun4AllReturnCodes::EVENT_OK, TrackSeedContainer::get(), TrackSeed::get_phi(), TrackSeed::get_silicon_seed_index(), TrackSeed::get_tpc_seed_index(), TrackSeed::identify(), TrackSeedContainer::index(), m_clusterContainer, m_detaCut, m_dphiCut, m_seedMap, m_siliconSeeds, m_tGeometry, m_tpcSeeds, TrackSeed::set_silicon_seed_index(), and Fun4AllBase::Verbosity().
Member Data Documentation
TrkrClusterContainer* PHCosmicSeedCombiner::m_clusterContainer = nullptr private
Definition at line 36 of file PHCosmicSeedCombiner.h.
View newest version in sPHENIX GitHub at line 36 of file PHCosmicSeedCombiner.h
Referenced by getNodes(), and process_event().
float PHCosmicSeedCombiner::m_detaCut = 0.02 private
Definition at line 42 of file PHCosmicSeedCombiner.h.
View newest version in sPHENIX GitHub at line 42 of file PHCosmicSeedCombiner.h
Referenced by detaCut(), and process_event().
float PHCosmicSeedCombiner::m_dphiCut = 0.04 private
Definition at line 41 of file PHCosmicSeedCombiner.h.
View newest version in sPHENIX GitHub at line 41 of file PHCosmicSeedCombiner.h
Referenced by dphiCut(), and process_event().
TrackSeedContainer* PHCosmicSeedCombiner::m_seedMap = nullptr private
Definition at line 37 of file PHCosmicSeedCombiner.h.
View newest version in sPHENIX GitHub at line 37 of file PHCosmicSeedCombiner.h
Referenced by getNodes(), and process_event().
TrackSeedContainer* PHCosmicSeedCombiner::m_siliconSeeds = nullptr private
Definition at line 39 of file PHCosmicSeedCombiner.h.
View newest version in sPHENIX GitHub at line 39 of file PHCosmicSeedCombiner.h
Referenced by getNodes(), and process_event().
ActsGeometry* PHCosmicSeedCombiner::m_tGeometry = nullptr private
Definition at line 35 of file PHCosmicSeedCombiner.h.
View newest version in sPHENIX GitHub at line 35 of file PHCosmicSeedCombiner.h
Referenced by getNodes(), and process_event().
TrackSeedContainer* PHCosmicSeedCombiner::m_tpcSeeds = nullptr private
Definition at line 38 of file PHCosmicSeedCombiner.h.
View newest version in sPHENIX GitHub at line 38 of file PHCosmicSeedCombiner.h
Referenced by getNodes(), and process_event().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/trackreco/PHCosmicSeedCombiner.h
coresoftware/blob/master/offline/packages/trackreco/PHCosmicSeedCombiner.cc