Analysis Software: EventHeader Class Reference
EventHeader Class Reference
base class for EventHeaders
#include <coresoftware/blob/master/offline/framework/ffaobjects/EventHeader.h>
Public Member Functions
~EventHeader () override=default
dtor
void Reset () override
Clear Event.
void identify (std::ostream &os=std::cout) const override
int isValid () const override
isValid returns non zero if object contains valid data
virtual int get_RunNumber () const
get Run Number
virtual void set_RunNumber (const int)
set Run Number
virtual int get_EvtSequence () const
get Event Number
virtual void set_EvtSequence (const int)
set Event Number
virtual void set_BunchCrossing (int64_t bcr)
bunch crossing
virtual int64_t get_BunchCrossing () const
bunch crossing
virtual void set_floatval (const std::string &, const float)
virtual float get_floatval (const std::string &) const
virtual void set_intval (const std::string &, const int64_t)
virtual int64_t get_intval (const std::string &) const
int get_EvtType () const
get Event Type (Data,rejected,EOR,BOR,...)
void set_EvtType (const int ival)
set Event Type (Data,rejected,EOR,BOR,...)
void set_ImpactParameter (const double rval)
float get_ImpactParameter () const
void set_EventPlaneAngle (const double rval)
float get_EventPlaneAngle () const
void set_eccentricity (const double rval)
float get_eccentricity () const
void set_ncoll (const int ival)
int get_ncoll () const
void set_npart (const int ival)
int get_npart () const
void set_TimeStamp (const time_t tval)
time_t get_TimeStamp () const
Public Member Functions inherited from PHObject
PHObject ()
ctor
~PHObject () override
dtor
virtual PHObject * CloneMe () const
Virtual copy constructor.
virtual PHObject * clone () const final
PHObject * Clone (const char *newname="") const final
void Copy (TObject &object) const final
virtual int Integrate () const
virtual int Integrate (PHObject *)
virtual void CopyFrom (const PHObject *obj)
Detailed Description
base class for EventHeaders
Definition at line 15 of file EventHeader.h.
View newest version in sPHENIX GitHub at line 15 of file EventHeader.h
Constructor & Destructor Documentation
EventHeader::~EventHeader () override default
dtor
Member Function Documentation
virtual int64_t EventHeader::get_BunchCrossing () const inline virtual
bunch crossing
Reimplemented in EventHeaderv2.
Definition at line 47 of file EventHeader.h.
View newest version in sPHENIX GitHub at line 47 of file EventHeader.h
References get_intval().
Referenced by DumpEventHeader::process_Node().
float EventHeader::get_eccentricity () const inline
Definition at line 67 of file EventHeader.h.
View newest version in sPHENIX GitHub at line 67 of file EventHeader.h
References get_floatval().
Referenced by DumpEventHeader::process_Node().
float EventHeader::get_EventPlaneAngle () const inline
Definition at line 64 of file EventHeader.h.
View newest version in sPHENIX GitHub at line 64 of file EventHeader.h
References get_floatval().
Referenced by DumpEventHeader::process_Node().
virtual int EventHeader::get_EvtSequence () const inline virtual
get Event Number
Reimplemented in EventHeaderv1.
Definition at line 39 of file EventHeader.h.
View newest version in sPHENIX GitHub at line 39 of file EventHeader.h
Referenced by PHNodeDump::GetGlobalVars(), TimerStats::process_event(), Proto4ShowerCalib::process_event(), Proto3ShowerCalib::process_event(), Proto2ShowerCalib::process_event(), MBDStudy::process_event(), hijbkg_upc::process_event(), BBCStudy::process_event(), ExampleAnalysisModule::process_event(), and DumpEventHeader::process_Node().
int EventHeader::get_EvtType () const inline
get Event Type (Data,rejected,EOR,BOR,...)
Definition at line 56 of file EventHeader.h.
View newest version in sPHENIX GitHub at line 56 of file EventHeader.h
References get_intval().
Referenced by EventHeaderv2::identify(), Proto4ShowerCalib::process_event(), and DumpEventHeader::process_Node().
virtual float EventHeader::get_floatval (const std::string &) const inline virtual
Reimplemented in EventHeaderv1.
Definition at line 50 of file EventHeader.h.
View newest version in sPHENIX GitHub at line 50 of file EventHeader.h
Referenced by get_eccentricity(), get_EventPlaneAngle(), and get_ImpactParameter().
float EventHeader::get_ImpactParameter () const inline
Definition at line 61 of file EventHeader.h.
View newest version in sPHENIX GitHub at line 61 of file EventHeader.h
References get_floatval().
Referenced by MBDStudy::process_event(), BBCStudy::process_event(), and DumpEventHeader::process_Node().
virtual int64_t EventHeader::get_intval (const std::string &) const inline virtual
Reimplemented in EventHeaderv1.
Definition at line 53 of file EventHeader.h.
View newest version in sPHENIX GitHub at line 53 of file EventHeader.h
Referenced by get_BunchCrossing(), get_EvtType(), get_ncoll(), get_npart(), and get_TimeStamp().
int EventHeader::get_ncoll () const inline
Definition at line 70 of file EventHeader.h.
View newest version in sPHENIX GitHub at line 70 of file EventHeader.h
References get_intval().
Referenced by dNdEtaINTT::GetCentralityInfo(), MBDStudy::process_event(), BBCStudy::process_event(), and DumpEventHeader::process_Node().
int EventHeader::get_npart () const inline
Definition at line 73 of file EventHeader.h.
View newest version in sPHENIX GitHub at line 73 of file EventHeader.h
References get_intval().
Referenced by dNdEtaINTT::GetCentralityInfo(), MBDStudy::process_event(), BBCStudy::process_event(), and DumpEventHeader::process_Node().
virtual int EventHeader::get_RunNumber () const inline virtual
get Run Number
Reimplemented in EventHeaderv1.
Definition at line 34 of file EventHeader.h.
View newest version in sPHENIX GitHub at line 34 of file EventHeader.h
Referenced by CaloWaveformSim::Init(), CaloTowerCalib::InitRun(), caloTowerEmbed::InitRun(), Proto4ShowerCalib::process_event(), Proto2ShowerCalib::process_event(), Proto3ShowerCalib::process_event(), and ExampleAnalysisModule::process_event().
time_t EventHeader::get_TimeStamp () const inline
Definition at line 76 of file EventHeader.h.
View newest version in sPHENIX GitHub at line 76 of file EventHeader.h
References get_intval().
Referenced by Proto2ShowerCalib::process_event(), and DumpEventHeader::process_Node().
void EventHeader::identify (std::ostream & os = std::cout) const override virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from PHObject.
Reimplemented in EventHeaderv2, and EventHeaderv1.
Definition at line 15 of file EventHeader.cc.
View newest version in sPHENIX GitHub at line 15 of file EventHeader.cc
Referenced by HeadReco::process_event(), and Proto4ShowerCalib::process_event().
int EventHeader::isValid () const override virtual
isValid returns non zero if object contains valid data
Reimplemented from PHObject.
Reimplemented in EventHeaderv1.
Definition at line 22 of file EventHeader.cc.
View newest version in sPHENIX GitHub at line 22 of file EventHeader.cc
Referenced by DumpEventHeader::process_Node().
void EventHeader::Reset () override virtual
Clear Event.
Reimplemented from PHObject.
Reimplemented in EventHeaderv2, and EventHeaderv1.
Definition at line 5 of file EventHeader.cc.
View newest version in sPHENIX GitHub at line 5 of file EventHeader.cc
virtual void EventHeader::set_BunchCrossing (int64_t bcr) inline virtual
bunch crossing
Reimplemented in EventHeaderv2.
Definition at line 44 of file EventHeader.h.
View newest version in sPHENIX GitHub at line 44 of file EventHeader.h
References set_intval().
void EventHeader::set_eccentricity (const double rval) inline
Definition at line 66 of file EventHeader.h.
View newest version in sPHENIX GitHub at line 66 of file EventHeader.h
References set_floatval().
Referenced by HeadReco::process_event().
void EventHeader::set_EventPlaneAngle (const double rval) inline
Definition at line 63 of file EventHeader.h.
View newest version in sPHENIX GitHub at line 63 of file EventHeader.h
References set_floatval().
Referenced by HeadReco::process_event().
virtual void EventHeader::set_EvtSequence (const int) inline virtual
set Event Number
Reimplemented in EventHeaderv1.
Definition at line 41 of file EventHeader.h.
View newest version in sPHENIX GitHub at line 41 of file EventHeader.h
Referenced by HeadReco::process_event().
void EventHeader::set_EvtType (const int ival) inline
set Event Type (Data,rejected,EOR,BOR,...)
Definition at line 58 of file EventHeader.h.
View newest version in sPHENIX GitHub at line 58 of file EventHeader.h
References set_intval().
Referenced by HeadReco::process_event(), RunInfoUnpackPRDF::process_event(), and MvtxRunInfoUnpackPRDF::process_event().
virtual void EventHeader::set_floatval (const std::string & , const float) inline virtual
Reimplemented in EventHeaderv1.
Definition at line 49 of file EventHeader.h.
View newest version in sPHENIX GitHub at line 49 of file EventHeader.h
Referenced by set_eccentricity(), set_EventPlaneAngle(), and set_ImpactParameter().
void EventHeader::set_ImpactParameter (const double rval) inline
Definition at line 60 of file EventHeader.h.
View newest version in sPHENIX GitHub at line 60 of file EventHeader.h
References set_floatval().
Referenced by HeadReco::process_event().
virtual void EventHeader::set_intval (const std::string & , const int64_t) inline virtual
Reimplemented in EventHeaderv1.
Definition at line 52 of file EventHeader.h.
View newest version in sPHENIX GitHub at line 52 of file EventHeader.h
Referenced by set_BunchCrossing(), set_EvtType(), set_ncoll(), set_npart(), and set_TimeStamp().
void EventHeader::set_ncoll (const int ival) inline
Definition at line 69 of file EventHeader.h.
View newest version in sPHENIX GitHub at line 69 of file EventHeader.h
References set_intval().
Referenced by HeadReco::process_event().
void EventHeader::set_npart (const int ival) inline
Definition at line 72 of file EventHeader.h.
View newest version in sPHENIX GitHub at line 72 of file EventHeader.h
References set_intval().
Referenced by HeadReco::process_event().
virtual void EventHeader::set_RunNumber (const int) inline virtual
set Run Number
Reimplemented in EventHeaderv1.
Definition at line 36 of file EventHeader.h.
View newest version in sPHENIX GitHub at line 36 of file EventHeader.h
Referenced by HeadReco::process_event().
void EventHeader::set_TimeStamp (const time_t tval) inline
Definition at line 75 of file EventHeader.h.
View newest version in sPHENIX GitHub at line 75 of file EventHeader.h
References set_intval().
Referenced by RunInfoUnpackPRDF::process_event(), and MvtxRunInfoUnpackPRDF::process_event().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/framework/ffaobjects/EventHeader.h
coresoftware/blob/master/offline/framework/ffaobjects/EventHeader.cc