Analysis Software: PktSizeCommon Namespace Reference
PktSizeCommon Namespace Reference
Functions
int fillgranules (std::map< std::string, std::pair< unsigned int, unsigned int > > &granulepacketlimits)
int filldcmgroups (std::map< unsigned int, std::string > &dcmgroupmap)
int fillfibergroups (std::map< unsigned int, std::string > &dcmgroupmap)
Function Documentation
int PktSizeCommon::filldcmgroups (std::map< unsigned int, std::string > & dcmgroupmap)
Definition at line 110 of file PktSizeCommon.cc.
View newest version in sPHENIX GitHub at line 110 of file PktSizeCommon.cc
References in, infile, line, and packetid.
Referenced by PktSizeMon::Init().
int PktSizeCommon::fillfibergroups (std::map< unsigned int, std::string > & dcmgroupmap)
Definition at line 186 of file PktSizeCommon.cc.
View newest version in sPHENIX GitHub at line 186 of file PktSizeCommon.cc
References in, infile, line, and packetid.
Referenced by PktSizeMon::Init().
int PktSizeCommon::fillgranules (std::map< std::string, std::pair< unsigned int, unsigned int > > & granulepacketlimits)
Definition at line 11 of file PktSizeCommon.cc.
View newest version in sPHENIX GitHub at line 11 of file PktSizeCommon.cc
Referenced by PktSizeMon::Init(), and PktSizeMonDraw::Init().