Analysis Software: QAG4Decayer Class Reference
QAG4Decayer Class Reference
#include <coresoftware/blob/master/offline/QA/modules/QAG4Decayer.h>
Public Member Functions
QAG4Decayer (const std::string &name="QAG4Decayer")
virtual ~QAG4Decayer ()
int Init (PHCompositeNode *topNode) override
int process_event (PHCompositeNode *topNode) override
int End (PHCompositeNode *topNode) override
Called at the end of all processing.
std::vector< int > Channel (int pdgid, std::vector< int > Daughter)
Public Member Functions inherited from SubsysReco
~SubsysReco () override
virtual int EndRun (const int)
Called at the end of each run.
virtual int InitRun (PHCompositeNode *)
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
void Print (const std::string &="ALL") const override
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Private Attributes
PHG4TruthInfoContainer * m_truth_info = nullptr
TFile * fout = nullptr
TTree * QATree = nullptr
int EvtID = -1
float LifeTime = -1
int NParticles = -1
std::vector< int > PVDaughtersPDGID
bool m_write_nTuple
bool m_SaveFiles
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = std::numeric_limits<int>::max() - 10
}
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Detailed Description
Definition at line 29 of file QAG4Decayer.h.
View newest version in sPHENIX GitHub at line 29 of file QAG4Decayer.h
Constructor & Destructor Documentation
QAG4Decayer::QAG4Decayer (const std::string & name = "QAG4Decayer")
Definition at line 51 of file QAG4Decayer.cc.
View newest version in sPHENIX GitHub at line 51 of file QAG4Decayer.cc
QAG4Decayer::~QAG4Decayer () virtual
Definition at line 59 of file QAG4Decayer.cc.
View newest version in sPHENIX GitHub at line 59 of file QAG4Decayer.cc
Member Function Documentation
std::vector<int> QAG4Decayer::Channel (int pdgid, std::vector< int > Daughter)
int QAG4Decayer::End (PHCompositeNode *) override virtual
Called at the end of all processing.
Reimplemented from SubsysReco.
Definition at line 700 of file QAG4Decayer.cc.
View newest version in sPHENIX GitHub at line 700 of file QAG4Decayer.cc
References assert, Fun4AllReturnCodes::EVENT_OK, fout, m_SaveFiles, m_write_nTuple, and QATree.
int QAG4Decayer::Init (PHCompositeNode *) override virtual
Called during initialization. Typically this is where you can book histograms, and e.g. register them to Fun4AllServer (so they can be output to file using Fun4AllServer::dumpHistos() method).
Reimplemented from SubsysReco.
Definition at line 63 of file QAG4Decayer.cc.
View newest version in sPHENIX GitHub at line 63 of file QAG4Decayer.cc
References assert, EvtID, fout, QAHistManagerDef::getHistoManager(), h, i, LifeTime, m_SaveFiles, MassMax, MassMin, NHFQA, NParticles, PVDaughtersPDGID, QATree, and Fun4AllHistoManager::registerHisto().
int QAG4Decayer::process_event (PHCompositeNode *) override virtual
Called for each event. This is where you do the real work.
Reimplemented from SubsysReco.
Definition at line 286 of file QAG4Decayer.cc.
View newest version in sPHENIX GitHub at line 286 of file QAG4Decayer.cc
References assert, parse_cmake_options::begin, end, Fun4AllReturnCodes::EVENT_OK, EvtID, PHG4Particle::get_e(), PHG4Particle::get_parent_id(), PHG4Particle::get_pid(), PHG4Particle::get_px(), PHG4Particle::get_py(), PHG4Particle::get_pz(), PHG4Particle::get_track_id(), PHG4Particle::get_vtx_id(), PHG4VtxPoint::get_x(), PHG4VtxPoint::get_y(), PHG4VtxPoint::get_z(), Fun4AllHistoManager::getHisto(), QAHistManagerDef::getHistoManager(), PHG4TruthInfoContainer::GetParticle(), PHG4TruthInfoContainer::GetParticleRange(), PHG4TruthInfoContainer::GetVtx(), gflavor, i, LifeTime, m_truth_info, m_write_nTuple, NHFQA, merge_hashes::p, QATree, QAVtxPDGID, physmon_track_finding_ttbar::r, and Acts::Experimental::detail::BlueprintHelper::sort().
Member Data Documentation
int QAG4Decayer::EvtID = -1 private
Definition at line 49 of file QAG4Decayer.h.
View newest version in sPHENIX GitHub at line 49 of file QAG4Decayer.h
Referenced by Init(), and process_event().
TFile* QAG4Decayer::fout = nullptr private
Definition at line 47 of file QAG4Decayer.h.
View newest version in sPHENIX GitHub at line 47 of file QAG4Decayer.h
Referenced by End(), and Init().
float QAG4Decayer::LifeTime = -1 private
Definition at line 50 of file QAG4Decayer.h.
View newest version in sPHENIX GitHub at line 50 of file QAG4Decayer.h
Referenced by Init(), and process_event().
bool QAG4Decayer::m_SaveFiles private
Definition at line 61 of file QAG4Decayer.h.
View newest version in sPHENIX GitHub at line 61 of file QAG4Decayer.h
Referenced by End(), and Init().
PHG4TruthInfoContainer* QAG4Decayer::m_truth_info = nullptr private
Definition at line 44 of file QAG4Decayer.h.
View newest version in sPHENIX GitHub at line 44 of file QAG4Decayer.h
Referenced by process_event().
bool QAG4Decayer::m_write_nTuple private
Definition at line 59 of file QAG4Decayer.h.
View newest version in sPHENIX GitHub at line 59 of file QAG4Decayer.h
Referenced by End(), and process_event().
int QAG4Decayer::NParticles = -1 private
Definition at line 56 of file QAG4Decayer.h.
View newest version in sPHENIX GitHub at line 56 of file QAG4Decayer.h
Referenced by Init().
std::vector<int> QAG4Decayer::PVDaughtersPDGID private
Definition at line 57 of file QAG4Decayer.h.
View newest version in sPHENIX GitHub at line 57 of file QAG4Decayer.h
Referenced by Init().
TTree* QAG4Decayer::QATree = nullptr private
Definition at line 48 of file QAG4Decayer.h.
View newest version in sPHENIX GitHub at line 48 of file QAG4Decayer.h
Referenced by End(), Init(), and process_event().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/QA/modules/QAG4Decayer.h
coresoftware/blob/master/offline/QA/modules/QAG4Decayer.cc