Analysis Software: RawClusterZVertexRecorrect Class Reference
RawClusterZVertexRecorrect Class Reference
#include <coresoftware/blob/master/offline/packages/CaloReco/RawClusterZVertexRecorrect.h>
Public Member Functions
RawClusterZVertexRecorrect (const std::string &name)
int InitRun (PHCompositeNode *topNode) override
int process_event (PHCompositeNode *topNode) override
int End (PHCompositeNode *topNode) override
Called at the end of all processing.
void set_UseTowerInfo (const int useMode)
void set_UseBbcZVtx (const bool useBbc)
Public Member Functions inherited from SubsysReco
~SubsysReco () override
virtual int EndRun (const int)
Called at the end of each run.
virtual int Init (PHCompositeNode *)
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
void Print (const std::string &="ALL") const override
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Private Attributes
std::string _det_name
CaloRecoUtility m_calrecoUtilInstance
int m_UseTowerInfo = 0
bool m_UseBbcZVtx = false
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = std::numeric_limits<int>::max() - 10
}
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Detailed Description
Definition at line 14 of file RawClusterZVertexRecorrect.h.
View newest version in sPHENIX GitHub at line 14 of file RawClusterZVertexRecorrect.h
Constructor & Destructor Documentation
RawClusterZVertexRecorrect::RawClusterZVertexRecorrect (const std::string & name) explicit
Definition at line 24 of file RawClusterZVertexRecorrect.cc.
View newest version in sPHENIX GitHub at line 24 of file RawClusterZVertexRecorrect.cc
Member Function Documentation
int RawClusterZVertexRecorrect::End (PHCompositeNode *) override virtual
Called at the end of all processing.
Reimplemented from SubsysReco.
Definition at line 204 of file RawClusterZVertexRecorrect.cc.
View newest version in sPHENIX GitHub at line 204 of file RawClusterZVertexRecorrect.cc
References Fun4AllReturnCodes::EVENT_OK.
int RawClusterZVertexRecorrect::InitRun (PHCompositeNode *) override virtual
Called for first event when run number is known. Typically this is where you may want to fetch data from database, because you know the run number.
Reimplemented from SubsysReco.
Definition at line 33 of file RawClusterZVertexRecorrect.cc.
View newest version in sPHENIX GitHub at line 33 of file RawClusterZVertexRecorrect.cc
References Fun4AllReturnCodes::EVENT_OK, CaloRecoUtility::LoadProfile(), m_calrecoUtilInstance, and Fun4AllBase::Verbosity().
int RawClusterZVertexRecorrect::process_event (PHCompositeNode *) override virtual
Called for each event. This is where you do the real work.
Reimplemented from SubsysReco.
Definition at line 45 of file RawClusterZVertexRecorrect.cc.
View newest version in sPHENIX GitHub at line 45 of file RawClusterZVertexRecorrect.cc
References _det_name, Fun4AllReturnCodes::ABORTEVENT, MbdVertexMap::begin(), GlobalVertexMap::begin(), GlobalVertexMap::empty(), MbdVertexMap::end(), Fun4AllReturnCodes::EVENT_OK, RawCluster::get_chi2(), RawCluster::get_energy(), MbdVertex::get_z(), GlobalVertex::get_z(), RawCluster::get_z(), RawClusterContainer::getClusters(), m_calrecoUtilInstance, m_UseBbcZVtx, m_UseTowerInfo, CaloRecoUtility::ProbCorrsZVertex(), CaloRecoUtility::ShowerDepthCorrZVertex(), Fun4AllBase::Verbosity(), and vz.
void RawClusterZVertexRecorrect::set_UseBbcZVtx (const bool useBbc) inline
Definition at line 32 of file RawClusterZVertexRecorrect.h.
View newest version in sPHENIX GitHub at line 32 of file RawClusterZVertexRecorrect.h
References m_UseBbcZVtx.
void RawClusterZVertexRecorrect::set_UseTowerInfo (const int useMode) inline
Definition at line 26 of file RawClusterZVertexRecorrect.h.
View newest version in sPHENIX GitHub at line 26 of file RawClusterZVertexRecorrect.h
References m_UseTowerInfo.
Member Data Documentation
std::string RawClusterZVertexRecorrect::_det_name private
Definition at line 43 of file RawClusterZVertexRecorrect.h.
View newest version in sPHENIX GitHub at line 43 of file RawClusterZVertexRecorrect.h
Referenced by process_event().
CaloRecoUtility RawClusterZVertexRecorrect::m_calrecoUtilInstance private
Definition at line 45 of file RawClusterZVertexRecorrect.h.
View newest version in sPHENIX GitHub at line 45 of file RawClusterZVertexRecorrect.h
Referenced by InitRun(), and process_event().
bool RawClusterZVertexRecorrect::m_UseBbcZVtx = false private
Definition at line 47 of file RawClusterZVertexRecorrect.h.
View newest version in sPHENIX GitHub at line 47 of file RawClusterZVertexRecorrect.h
Referenced by process_event(), and set_UseBbcZVtx().
int RawClusterZVertexRecorrect::m_UseTowerInfo = 0 private
Definition at line 46 of file RawClusterZVertexRecorrect.h.
View newest version in sPHENIX GitHub at line 46 of file RawClusterZVertexRecorrect.h
Referenced by process_event(), and set_UseTowerInfo().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/CaloReco/RawClusterZVertexRecorrect.h
coresoftware/blob/master/offline/packages/CaloReco/RawClusterZVertexRecorrect.cc