Analysis Software: BbcVertexMap Class Reference
BbcVertexMap Class Reference
#include <coresoftware/blob/master/simulation/g4simulation/g4bbc/BbcVertexMap.h>
Public Types
typedef std::map< unsigned int,
BbcVertex * >::const_iterator ConstIter
typedef std::map< unsigned int,
BbcVertex * >::iterator Iter
Public Member Functions
~BbcVertexMap () override
void identify (std::ostream &os=std::cout) const override
int isValid () const override
isValid returns non zero if object contains vailid data
virtual bool empty () const
virtual size_t size () const
virtual size_t count (unsigned int idkey) const
virtual void clear ()
virtual const BbcVertex * get (unsigned int idkey) const
virtual BbcVertex * get (unsigned int idkey)
virtual BbcVertex * insert (BbcVertex *vertex)
virtual size_t erase (unsigned int idkey)
virtual ConstIter begin () const
virtual ConstIter find (unsigned int idkey) const
virtual ConstIter end () const
virtual Iter begin ()
virtual Iter find (unsigned int idkey)
virtual Iter end ()
Public Member Functions inherited from PHObject
PHObject ()
ctor
~PHObject () override
dtor
virtual PHObject * CloneMe () const
Virtual copy constructor.
virtual PHObject * clone () const final
PHObject * Clone (const char *newname="") const final
void Copy (TObject &object) const final
virtual void Reset ()
Clear Event.
virtual int isValid (const float) const
virtual int isValid (const double) const
virtual int isValid (const int) const
virtual int isValid (const unsigned int) const
virtual int isImplemented (const float f) const
virtual int isImplemented (const double f) const
virtual int isImplemented (const int i) const
virtual int isImplemented (const unsigned int i) const
virtual int Integrate () const
virtual int Integrate (PHObject *obj)
virtual void CopyFrom (const PHObject *obj)
Protected Member Functions
BbcVertexMap ()
Private Member Functions
ClassDefOverride (BbcVertexMap, 1)
Detailed Description
Definition at line 10 of file BbcVertexMap.h.
View newest version in sPHENIX GitHub at line 10 of file BbcVertexMap.h
Member Typedef Documentation
typedef std::map<unsigned int, BbcVertex*>::const_iterator BbcVertexMap::ConstIter
Definition at line 13 of file BbcVertexMap.h.
View newest version in sPHENIX GitHub at line 13 of file BbcVertexMap.h
typedef std::map<unsigned int, BbcVertex*>::iterator BbcVertexMap::Iter
Definition at line 14 of file BbcVertexMap.h.
View newest version in sPHENIX GitHub at line 14 of file BbcVertexMap.h
Constructor & Destructor Documentation
BbcVertexMap::~BbcVertexMap () inline override
Definition at line 16 of file BbcVertexMap.h.
View newest version in sPHENIX GitHub at line 16 of file BbcVertexMap.h
BbcVertexMap::BbcVertexMap () inline protected
Definition at line 40 of file BbcVertexMap.h.
View newest version in sPHENIX GitHub at line 40 of file BbcVertexMap.h
Member Function Documentation
BbcVertexMap::ConstIter BbcVertexMap::begin () const virtual
Reimplemented in BbcVertexMapv1.
Definition at line 5 of file BbcVertexMap.cc.
View newest version in sPHENIX GitHub at line 5 of file BbcVertexMap.cc
Referenced by PHHoughSeeding::fast_vertex_from_bbc(), and DumpBbcVertexMap::process_Node().
BbcVertexMap::Iter BbcVertexMap::begin () virtual
Reimplemented in BbcVertexMapv1.
Definition at line 21 of file BbcVertexMap.cc.
View newest version in sPHENIX GitHub at line 21 of file BbcVertexMap.cc
BbcVertexMap::ClassDefOverride (BbcVertexMap , 1) private
virtual void BbcVertexMap::clear () inline virtual
Reimplemented in BbcVertexMapv1.
Definition at line 24 of file BbcVertexMap.h.
View newest version in sPHENIX GitHub at line 24 of file BbcVertexMap.h
virtual size_t BbcVertexMap::count (unsigned int idkey) const inline virtual
Reimplemented in BbcVertexMapv1.
Definition at line 23 of file BbcVertexMap.h.
View newest version in sPHENIX GitHub at line 23 of file BbcVertexMap.h
virtual bool BbcVertexMap::empty () const inline virtual
Reimplemented in BbcVertexMapv1.
Definition at line 21 of file BbcVertexMap.h.
View newest version in sPHENIX GitHub at line 21 of file BbcVertexMap.h
BbcVertexMap::ConstIter BbcVertexMap::end () const virtual
Reimplemented in BbcVertexMapv1.
Definition at line 15 of file BbcVertexMap.cc.
View newest version in sPHENIX GitHub at line 15 of file BbcVertexMap.cc
Referenced by DumpBbcVertexMap::process_Node().
BbcVertexMap::Iter BbcVertexMap::end () virtual
Reimplemented in BbcVertexMapv1.
Definition at line 31 of file BbcVertexMap.cc.
View newest version in sPHENIX GitHub at line 31 of file BbcVertexMap.cc
virtual size_t BbcVertexMap::erase (unsigned int idkey) inline virtual
Reimplemented in BbcVertexMapv1.
Definition at line 29 of file BbcVertexMap.h.
View newest version in sPHENIX GitHub at line 29 of file BbcVertexMap.h
BbcVertexMap::ConstIter BbcVertexMap::find (unsigned int idkey) const virtual
Reimplemented in BbcVertexMapv1.
Definition at line 10 of file BbcVertexMap.cc.
View newest version in sPHENIX GitHub at line 10 of file BbcVertexMap.cc
BbcVertexMap::Iter BbcVertexMap::find (unsigned int idkey) virtual
Reimplemented in BbcVertexMapv1.
Definition at line 26 of file BbcVertexMap.cc.
View newest version in sPHENIX GitHub at line 26 of file BbcVertexMap.cc
virtual const BbcVertex* BbcVertexMap::get (unsigned int idkey) const inline virtual
Reimplemented in BbcVertexMapv1.
Definition at line 26 of file BbcVertexMap.h.
View newest version in sPHENIX GitHub at line 26 of file BbcVertexMap.h
virtual BbcVertex* BbcVertexMap::get (unsigned int idkey) inline virtual
Reimplemented in BbcVertexMapv1.
Definition at line 27 of file BbcVertexMap.h.
View newest version in sPHENIX GitHub at line 27 of file BbcVertexMap.h
void BbcVertexMap::identify (std::ostream & os = std::cout) const inline override virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from PHObject.
Reimplemented in BbcVertexMapv1.
Definition at line 18 of file BbcVertexMap.h.
View newest version in sPHENIX GitHub at line 18 of file BbcVertexMap.h
References os.
virtual BbcVertex* BbcVertexMap::insert (BbcVertex * vertex) inline virtual
Reimplemented in BbcVertexMapv1.
Definition at line 28 of file BbcVertexMap.h.
View newest version in sPHENIX GitHub at line 28 of file BbcVertexMap.h
Referenced by BbcVertexFastSimReco::process_event().
int BbcVertexMap::isValid () const inline override virtual
isValid returns non zero if object contains vailid data
Reimplemented from PHObject.
Reimplemented in BbcVertexMapv1.
Definition at line 19 of file BbcVertexMap.h.
View newest version in sPHENIX GitHub at line 19 of file BbcVertexMap.h
virtual size_t BbcVertexMap::size (void) const inline virtual
Reimplemented in BbcVertexMapv1.
Definition at line 22 of file BbcVertexMap.h.
View newest version in sPHENIX GitHub at line 22 of file BbcVertexMap.h
Referenced by DumpBbcVertexMap::process_Node().
The documentation for this class was generated from the following files:
coresoftware/blob/master/simulation/g4simulation/g4bbc/BbcVertexMap.h
coresoftware/blob/master/simulation/g4simulation/g4bbc/BbcVertexMap.cc