Analysis Software: ActsExamples::FittingAlgorithm Exception Reference
ActsExamples::FittingAlgorithm Exception Reference final
#include <acts/blob/sPHENIX/Examples/Algorithms/Fitting/include/ActsExamples/Fitting/FittingAlgorithm.hpp>
Classes
struct Config
Public Types
using FitterResult = Acts::Result< Acts::KalmanFitterResult< SimSourceLink >>
using FitterFunction = std::function< FitterResult(const std::vector< SimSourceLink > &, const TrackParameters &, const Acts::KalmanFitterOptions< Acts::VoidOutlierFinder > &)>
Public Member Functions
FittingAlgorithm (Config cfg, Acts::Logging::Level lvl)
ActsExamples::ProcessCode execute (const ActsExamples::AlgorithmContext &ctx) const finaloverride
Public Member Functions inherited from ActsExamples::BareAlgorithm
BareAlgorithm (std::string name, Acts::Logging::Level level=Acts::Logging::INFO)
std::string name () const finaloverride
The algorithm name.
Static Public Member Functions
static FitterFunction makeFitterFunction (std::shared_ptr< const Acts::TrackingGeometry > trackingGeometry, Options::BFieldVariant magneticField)
Private Attributes
Config m_cfg
Additional Inherited Members
Protected Member Functions inherited from ActsExamples::BareAlgorithm
const Acts::Logger & logger () const
Detailed Description
Definition at line 24 of file FittingAlgorithm.hpp.
View newest version in sPHENIX GitHub at line 24 of file FittingAlgorithm.hpp
Member Typedef Documentation
using ActsExamples::FittingAlgorithm::FitterFunction = std::function<FitterResult(const std::vector<SimSourceLink>&, const TrackParameters&, const Acts::KalmanFitterOptions<Acts::VoidOutlierFinder>&)>
Fit function that takes input measurements, initial trackstate and fitter options and returns some fit-specific result.
Definition at line 31 of file FittingAlgorithm.hpp.
View newest version in sPHENIX GitHub at line 31 of file FittingAlgorithm.hpp
using ActsExamples::FittingAlgorithm::FitterResult = Acts::Result<Acts::KalmanFitterResult<SimSourceLink>>
Definition at line 26 of file FittingAlgorithm.hpp.
View newest version in sPHENIX GitHub at line 26 of file FittingAlgorithm.hpp
Constructor & Destructor Documentation
ActsExamples::FittingAlgorithm::FittingAlgorithm (Config cfg, Acts::Logging::Level lvl)
Constructor of the fitting algorithm
Parameters
cfg is the config struct to configure the algorihtm
level is the logging level
Definition at line 18 of file FittingAlgorithm.cpp.
View newest version in sPHENIX GitHub at line 18 of file FittingAlgorithm.cpp
References ActsExamples::FittingAlgorithm::Config::inputInitialTrackParameters, ActsExamples::FittingAlgorithm::Config::inputProtoTracks, ActsExamples::FittingAlgorithm::Config::inputSourceLinks, m_cfg, and ActsExamples::FittingAlgorithm::Config::outputTrajectories.
Member Function Documentation
ActsExamples::ProcessCode ActsExamples::FittingAlgorithm::execute (const ActsExamples::AlgorithmContext & ctx) const final override virtual
Framework execute method of the fitting algorithm
Parameters
ctx is the algorithm context that holds event-wise information
Returns
a process code to steer the algporithm flow
Implements ActsExamples::BareAlgorithm.
Definition at line 37 of file FittingAlgorithm.cpp.
View newest version in sPHENIX GitHub at line 37 of file FittingAlgorithm.cpp
References ACTS_DEBUG, ACTS_FATAL, ACTS_VERBOSE, ACTS_WARNING, ActsExamples::WhiteBoard::add(), ActsExamples::AlgorithmContext::calibContext, ActsExamples::AlgorithmContext::eventStore, ActsExamples::AlgorithmContext::geoContext, ActsExamples::WhiteBoard::get(), ActsExamples::AlgorithmContext::magFieldContext, testing::internal::move(), and SUCCESS.
ActsExamples::FittingAlgorithm::FitterFunction ActsExamples::FittingAlgorithm::makeFitterFunction (std::shared_ptr< const Acts::TrackingGeometry > trackingGeometry, Options::BFieldVariant magneticField) static
Create the fitter function implementation.
The magnetic field is intentionally given by-value since the variant contains shared_ptr anyways.
Definition at line 48 of file FittingAlgorithmFitterFunction.cpp.
View newest version in sPHENIX GitHub at line 48 of file FittingAlgorithmFitterFunction.cpp
References testing::internal::move(), Acts::Test::navigator, and propagation_timing::stepper.
Member Data Documentation
Config ActsExamples::FittingAlgorithm::m_cfg private
Definition at line 68 of file FittingAlgorithm.hpp.
View newest version in sPHENIX GitHub at line 68 of file FittingAlgorithm.hpp
Referenced by FittingAlgorithm().
The documentation for this exception was generated from the following files:
acts/blob/sPHENIX/Examples/Algorithms/Fitting/include/ActsExamples/Fitting/FittingAlgorithm.hpp
acts/blob/sPHENIX/Examples/Algorithms/Fitting/src/FittingAlgorithm.cpp
acts/blob/sPHENIX/Examples/Algorithms/Fitting/src/FittingAlgorithmFitterFunction.cpp