Analysis Software: Line Class Reference
Line Class Reference
#include <JETSCAPE/blob/main/external_packages/cornelius.h>
Public Member Functions
Line ()
~Line ()
void init (double **, double *, int *)
void flip_start_end ()
double * get_start ()
double * get_end ()
double * get_out ()
Line ()
~Line ()
void init (double **, double *, int *)
void flip_start_end ()
double * get_start ()
double * get_end ()
double * get_out ()
Line ()
~Line ()
void init (double **, double *, int *)
void flip_start_end ()
double * get_start ()
double * get_end ()
double * get_out ()
Line ()
~Line ()
void init (double **, double *, int *)
void flip_start_end ()
double * get_start ()
double * get_end ()
double * get_out ()
Public Member Functions inherited from GeneralElement
GeneralElement ()
~GeneralElement ()
double * get_centroid ()
double * get_normal ()
GeneralElement ()
~GeneralElement ()
double * get_centroid ()
double * get_normal ()
GeneralElement ()
~GeneralElement ()
double * get_centroid ()
double * get_normal ()
GeneralElement ()
~GeneralElement ()
double * get_centroid ()
double * get_normal ()
Private Member Functions
void calculate_centroid ()
void calculate_normal ()
void calculate_centroid ()
void calculate_normal ()
void calculate_centroid ()
void calculate_normal ()
void calculate_centroid ()
void calculate_normal ()
Private Attributes
int x1
int x2
int start_point
int end_point
double ** corners
double * out
int * const_i
Static Private Attributes
static const int LINE_CORNERS = 2
static const int LINE_DIM = 2
Additional Inherited Members
Protected Member Functions inherited from GeneralElement
void check_normal_direction (double *normal, double *out)
void check_normal_direction (double *normal, double *out)
void check_normal_direction (double *normal, double *out)
void check_normal_direction (double *normal, double *out)
Protected Attributes inherited from GeneralElement
double * centroid
double * normal
int normal_calculated
int centroid_calculated
Static Protected Attributes inherited from GeneralElement
static const int DIM = 4
Detailed Description
This class is used for line elements gotten from the squares. Can calculate the centroid and normal of the line.
Definition at line 143 of file cornelius.cpp.
View newest version in sPHENIX GitHub at line 143 of file cornelius.cpp
Constructor & Destructor Documentation
Line::Line ()
Constructor allocates memory for end points, point which is always outside and indices of the elements which are constant.
Definition at line 172 of file cornelius.cpp.
View newest version in sPHENIX GitHub at line 172 of file cornelius.cpp
References i, and out.
Line::~Line ()
Frees memory allocated in constructor.
Definition at line 188 of file cornelius.cpp.
View newest version in sPHENIX GitHub at line 188 of file cornelius.cpp
References i, and out.
Line::Line ()
Line::~Line ()
Line::Line ()
Line::~Line ()
Line::Line ()
Line::~Line ()
Member Function Documentation
void Line::calculate_centroid () private virtual
Reimplemented from GeneralElement.
void Line::calculate_centroid () private virtual
Reimplemented from GeneralElement.
void Line::calculate_centroid () private virtual
Determines the centroid for a line. Thus this a very trivial operation.
Reimplemented from GeneralElement.
Definition at line 259 of file cornelius.cpp.
View newest version in sPHENIX GitHub at line 259 of file cornelius.cpp
References i.
void Line::calculate_centroid () private virtual
Reimplemented from GeneralElement.
void Line::calculate_normal () private virtual
Reimplemented from GeneralElement.
void Line::calculate_normal () private virtual
Reimplemented from GeneralElement.
void Line::calculate_normal () private virtual
Reimplemented from GeneralElement.
void Line::calculate_normal () private virtual
Calculates the normal vector for a line.
Reimplemented from GeneralElement.
Definition at line 273 of file cornelius.cpp.
View newest version in sPHENIX GitHub at line 273 of file cornelius.cpp
References j, and out.
void Line::flip_start_end ()
void Line::flip_start_end ()
void Line::flip_start_end ()
Flips the start and end point of the line.
Definition at line 298 of file cornelius.cpp.
View newest version in sPHENIX GitHub at line 298 of file cornelius.cpp
Referenced by Polygon::add_line().
void Line::flip_start_end ()
double* Line::get_end ()
double* Line::get_end ()
double* Line::get_end ()
double * Line::get_end ()
Returns the end point in 4d as double*.
Returns
End point as a table
Definition at line 324 of file cornelius.cpp.
View newest version in sPHENIX GitHub at line 324 of file cornelius.cpp
Referenced by Polygon::add_line(), Polyhedron::calculate_centroid(), Polyhedron::calculate_normal(), and Polyhedron::lines_equal().
double* Line::get_out ()
double* Line::get_out ()
double* Line::get_out ()
double * Line::get_out ()
Returns the point, which is always outside, in 4d as double*.
Returns
Point which is always outside as a table
Definition at line 336 of file cornelius.cpp.
View newest version in sPHENIX GitHub at line 336 of file cornelius.cpp
References out.
Referenced by Polyhedron::calculate_normal().
double* Line::get_start ()
double* Line::get_start ()
double * Line::get_start ()
Returns the start point in 4d as double*.
Returns
Start point as a table
Definition at line 312 of file cornelius.cpp.
View newest version in sPHENIX GitHub at line 312 of file cornelius.cpp
Referenced by Polygon::add_line(), Polyhedron::calculate_centroid(), Polyhedron::calculate_normal(), and Polyhedron::lines_equal().
double* Line::get_start ()
void Line::init (double ** , double * , int *)
void Line::init (double ** , double * , int *)
void Line::init (double ** p, double * o, int * c)
Initializes line element. Same element can be initialized several times with this function.
Parameters
[in] p Table containing end points
[in] o Table containing point which is outside surface
[in] o Table containing constant indices
Definition at line 208 of file cornelius.cpp.
View newest version in sPHENIX GitHub at line 208 of file cornelius.cpp
References i, j, and out.
void Line::init (double ** , double * , int *)
Member Data Documentation
int * Line::const_i private
Definition at line 153 of file cornelius.cpp.
View newest version in sPHENIX GitHub at line 153 of file cornelius.cpp
double ** Line::corners private
Definition at line 151 of file cornelius.cpp.
View newest version in sPHENIX GitHub at line 151 of file cornelius.cpp
int Line::end_point private
Definition at line 150 of file cornelius.cpp.
View newest version in sPHENIX GitHub at line 150 of file cornelius.cpp
static const int Line::LINE_CORNERS = 2 static private
Definition at line 146 of file cornelius.cpp.
View newest version in sPHENIX GitHub at line 146 of file cornelius.cpp
static const int Line::LINE_DIM = 2 static private
Definition at line 147 of file cornelius.cpp.
View newest version in sPHENIX GitHub at line 147 of file cornelius.cpp
double * Line::out private
Definition at line 152 of file cornelius.cpp.
View newest version in sPHENIX GitHub at line 152 of file cornelius.cpp
int Line::start_point private
Definition at line 149 of file cornelius.cpp.
View newest version in sPHENIX GitHub at line 149 of file cornelius.cpp
int Line::x1 private
Definition at line 148 of file cornelius.cpp.
View newest version in sPHENIX GitHub at line 148 of file cornelius.cpp
int Line::x2 private
Definition at line 148 of file cornelius.cpp.
View newest version in sPHENIX GitHub at line 148 of file cornelius.cpp
The documentation for this class was generated from the following files:
JETSCAPE/blob/main/external_packages/cornelius.cpp
JETSCAPE/blob/main/external_packages/cornelius.h
JETSCAPE/blob/main/external_packages/hydro_from_external_file/cornelius.cpp
JETSCAPE/blob/main/external_packages/hydro_from_external_file/cornelius.h