Analysis Software: MvtxDefs Namespace Reference
MvtxDefs Namespace Reference
Utility functions for MVTX.
Functions
static const unsigned int
kBitShiftStaveIdOffset __attribute__ ((unused)) = 7
uint8_t getStaveId (TrkrDefs::hitsetkey key)
Get the stave id from hitsetkey.
uint8_t getStaveId (TrkrDefs::cluskey key)
Get the stave id from cluskey.
uint8_t getChipId (TrkrDefs::hitsetkey key)
Get the chip id from hitsetkey.
uint8_t getChipId (TrkrDefs::cluskey key)
Get the chip id from cluskey.
int getStrobeId (TrkrDefs::hitsetkey key)
Get the chip id from hitsetkey.
int getStrobeId (TrkrDefs::cluskey key)
Get the strobe id from hitsetkey.
uint16_t getCol (TrkrDefs::hitkey key)
Get the strobe id from the cluskey.
uint16_t getRow (TrkrDefs::hitkey key)
Get the row index from hitkey.
TrkrDefs::hitkey genHitKey (const uint16_t col, const uint16_t row)
Generate a hitkey from a pixels column and row index.
TrkrDefs::hitsetkey genHitSetKey (const uint8_t lyr, const uint8_t stave, const uint8_t chip, const int strobe)
Generate a hitsetkey for the mvtx.
TrkrDefs::cluskey genClusKey (const uint8_t lyr, const uint8_t stave, const uint8_t chip, const int strobe, const uint32_t clusid)
Generate a cluster key from indeces.
TrkrDefs::hitsetkey resetStrobeHitSetKey (const TrkrDefs::hitsetkey hitsetkey)
Zero the strobe bits in the hitsetkey.
Detailed Description
Utility functions for MVTX.
Contains the functions for manipulating the various keys used by the mvtx for hits, hit sets, and clusters
Function Documentation
static const uint16_t MAXROW MvtxDefs::__attribute__ ((unused)) = 7 static
TrkrDefs::cluskey MvtxDefs::genClusKey (const uint8_t lyr, const uint8_t stave, const uint8_t chip, const int strobe, const uint32_t clusid)
Generate a cluster key from indeces.
Parameters
[in] lyr Layer index
[in] stave Stave index
[in] chip Chip index
[in] crossing bunch crossing
[in] clusid Cluster id
[out] cluskey
Definition at line 102 of file MvtxDefs.cc.
View newest version in sPHENIX GitHub at line 102 of file MvtxDefs.cc
References TrkrDefs::genClusKey(), and MicromegasDefs::genHitSetKey().
Referenced by PHTruthClustering::all_truth_clusters(), SvtxTruthEval::all_truth_clusters(), and MvtxPrototype2Clusterizer::ClusterMvtx().
TrkrDefs::hitkey MvtxDefs::genHitKey (const uint16_t col, const uint16_t row)
Generate a hitkey from a pixels column and row index.
Parameters
[in] col Column index
[in] row Row index
[out] hitkey
Definition at line 73 of file MvtxDefs.cc.
View newest version in sPHENIX GitHub at line 73 of file MvtxDefs.cc
References Acts::Test::tmp().
Referenced by MvtxCombinedRawDataDecoder::InitRun(), PHG4MvtxHitReco::process_event(), and MvtxCombinedRawDataDecoder::process_event().
TrkrDefs::hitsetkey MvtxDefs::genHitSetKey (const uint8_t lyr, const uint8_t stave, const uint8_t chip, const int strobe)
Generate a hitsetkey for the mvtx.
Parameters
[in] lyr Layer index
[in] stave Stave index
[in] chip Chip index
[out] hitsetkey Generate a hitsetkey for the mvtx. The tracker id is known implicitly and used in the function.
Definition at line 82 of file MvtxDefs.cc.
View newest version in sPHENIX GitHub at line 82 of file MvtxDefs.cc
References TrkrDefs::genHitSetKey(), TrkrDefs::mvtxId, and Acts::Test::tmp().
Referenced by PHG4MvtxHitReco::cluster_truthhits(), MakeActsGeometry::getMvtxHitSetKeyFromCoords(), MakeActsGeometry::getMvtxKeyFromNode(), MvtxCombinedRawDataDecoder::InitRun(), MvtxPrototype2UnpackPRDF::process_event(), PHG4MvtxHitReco::process_event(), MvtxHitPruner::process_event(), MvtxCombinedRawDataDecoder::process_event(), MvtxPrototype2Align::ReadAlignmentParFile(), and PHG4MvtxHitReco::zero_strobe_bits().
uint8_t MvtxDefs::getChipId (TrkrDefs::hitsetkey key)
Get the chip id from hitsetkey.
Parameters
[in] hitsetkey
[out] chip id
Definition at line 22 of file MvtxDefs.cc.
View newest version in sPHENIX GitHub at line 22 of file MvtxDefs.cc
References Acts::Test::tmp().
Referenced by PHG4MvtxHitReco::cluster_truthhits(), MvtxClusterizer::ClusterMvtx(), MvtxClusterizer::ClusterMvtxRaw(), TrackResiduals::fillClusterTree(), KFParticle_truthAndDetTools::fillDetectorBranch(), TrackResiduals::fillHitTree(), getChipId(), MvtxPrototype2Geom::getChipIndex(), SVReco::MakeGenFitTrack(), MakeActsGeometry::makeMvtxMapPairs(), MvtxHitPruner::process_event(), HelicalFitter::process_event(), AnaMvtxTestBeam2019::process_event(), and PHG4MvtxHitReco::zero_strobe_bits().
uint8_t MvtxDefs::getChipId (TrkrDefs::cluskey key)
Get the chip id from cluskey.
Parameters
[in] cluskey
[out] chip id
Definition at line 32 of file MvtxDefs.cc.
View newest version in sPHENIX GitHub at line 32 of file MvtxDefs.cc
References getChipId(), and Acts::Test::tmp().
uint16_t MvtxDefs::getCol (TrkrDefs::hitkey key)
Get the strobe id from the cluskey.
Parameters
[in] cluskey
[out] strobe id
Definition at line 59 of file MvtxDefs.cc.
View newest version in sPHENIX GitHub at line 59 of file MvtxDefs.cc
References Acts::Test::tmp().
Referenced by MvtxPrototype2Clusterizer::are_adjacent(), MvtxClusterizer::are_adjacent(), PHG4MvtxHitReco::cluster_truthhits(), MvtxPrototype2Clusterizer::ClusterMvtx(), MvtxClusterizer::ClusterMvtx(), MvtxPrototype2Geom::detectorToGlobal(), QAG4SimulationMvtx::evaluate_clusters(), TrackResiduals::fillHitTree(), TpcRawWriter::process_event(), and AnaMvtxTestBeam2019::process_event().
uint16_t MvtxDefs::getRow (TrkrDefs::hitkey key)
Get the row index from hitkey.
Parameters
[in] hitkey
[out] row index
Definition at line 66 of file MvtxDefs.cc.
View newest version in sPHENIX GitHub at line 66 of file MvtxDefs.cc
References Acts::Test::tmp().
Referenced by MvtxPrototype2Clusterizer::are_adjacent(), MvtxClusterizer::are_adjacent(), PHG4MvtxHitReco::cluster_truthhits(), MvtxPrototype2Clusterizer::ClusterMvtx(), MvtxClusterizer::ClusterMvtx(), MvtxPrototype2Geom::detectorToGlobal(), QAG4SimulationMvtx::evaluate_clusters(), TrackResiduals::fillHitTree(), TpcRawWriter::process_event(), and AnaMvtxTestBeam2019::process_event().
uint8_t MvtxDefs::getStaveId (TrkrDefs::hitsetkey key)
Get the stave id from hitsetkey.
Parameters
[in] hitsetkey
[out] stave id
Definition at line 4 of file MvtxDefs.cc.
View newest version in sPHENIX GitHub at line 4 of file MvtxDefs.cc
References Acts::Test::tmp().
Referenced by MakeMilleFiles::addTrackToMilleFile(), PHG4MvtxHitReco::cluster_truthhits(), MvtxClusterizer::ClusterMvtx(), MvtxClusterizer::ClusterMvtxRaw(), TrackResiduals::fillClusterTree(), KFParticle_truthAndDetTools::fillDetectorBranch(), TrackResiduals::fillHitTree(), getStaveId(), SVReco::MakeGenFitTrack(), MakeActsGeometry::makeMvtxMapPairs(), MvtxHitPruner::process_event(), HelicalFitter::process_event(), AnaMvtxTestBeam2019::process_event(), and PHG4MvtxHitReco::zero_strobe_bits().
uint8_t MvtxDefs::getStaveId (TrkrDefs::cluskey key)
Get the stave id from cluskey.
Parameters
[in] cluskey
[out] stave id
Definition at line 15 of file MvtxDefs.cc.
View newest version in sPHENIX GitHub at line 15 of file MvtxDefs.cc
References getStaveId(), and Acts::Test::tmp().
int MvtxDefs::getStrobeId (TrkrDefs::hitsetkey key)
Get the chip id from hitsetkey.
Parameters
[in] hitsetkey
[out] chip id
Definition at line 39 of file MvtxDefs.cc.
View newest version in sPHENIX GitHub at line 39 of file MvtxDefs.cc
References Acts::Test::tmp().
Referenced by PHG4MvtxHitReco::cluster_truthhits(), MvtxClusterizer::ClusterMvtx(), MvtxClusterizer::ClusterMvtxRaw(), TrackResiduals::fillClusterTree(), TrackResiduals::fillHitTree(), getStrobeId(), and MvtxHitPruner::process_event().
int MvtxDefs::getStrobeId (TrkrDefs::cluskey key)
Get the strobe id from hitsetkey.
Parameters
[in] hitsetkey
[out] strobe id
Definition at line 52 of file MvtxDefs.cc.
View newest version in sPHENIX GitHub at line 52 of file MvtxDefs.cc
References getStrobeId(), and Acts::Test::tmp().
TrkrDefs::hitsetkey MvtxDefs::resetStrobeHitSetKey (const TrkrDefs::hitsetkey hitsetkey)
Zero the strobe bits in the hitsetkey.
Parameters
[in] hskey hitsetkey
[out] hitsetkey with strobe bits set to zero
Definition at line 110 of file MvtxDefs.cc.
View newest version in sPHENIX GitHub at line 110 of file MvtxDefs.cc
References Acts::Test::tmp().
Referenced by ActsSurfaceMaps::getSiliconSurface().