Analysis Software: InttSurveyMap Class Reference
InttSurveyMap Class Reference
#include <coresoftware/blob/master/offline/packages/intt/InttSurveyMap.h>
Public Types
typedef std::map
< InttMap::Offline_s,
Eigen::Affine3d,
InttMap::OfflineComparator > map_t
typedef InttMap::Offline_s key_t
typedef Eigen::Affine3d val_t
Public Member Functions
InttSurveyMap ()=default
~InttSurveyMap () override=default
virtual void identify (std::ostream &=std::cout) const override
virtual std::size_t size () const
int LoadFromFile (std::string const &="InttSurveyMap.root")
int LoadFromCDB (std::string const &="InttSurveyMap")
virtual val_t const * GetAbsoluteTransform (key_t) const
virtual val_t const * GetRelativeTransform (key_t) const
Public Member Functions inherited from PHObject
PHObject ()
ctor
~PHObject () override
dtor
virtual PHObject * CloneMe () const
Virtual copy constructor.
virtual PHObject * clone () const final
PHObject * Clone (const char *newname="") const final
void Copy (TObject &object) const final
virtual void Reset ()
Clear Event.
virtual int isValid () const
isValid returns non zero if object contains vailid data
virtual int Integrate () const
virtual int Integrate (PHObject *)
virtual void CopyFrom (const PHObject *obj)
Protected Member Functions
virtual int v_LoadFromCDBTTree (CDBTTree &)
virtual int v_LookupAbsoluteTransform (key_t const &, map_t::const_iterator &) const
virtual int v_LookupRelativeTransform (key_t const &, map_t::const_iterator &) const
Detailed Description
Definition at line 17 of file InttSurveyMap.h.
View newest version in sPHENIX GitHub at line 17 of file InttSurveyMap.h
Member Typedef Documentation
typedef InttMap::Offline_s InttSurveyMap::key_t
Definition at line 21 of file InttSurveyMap.h.
View newest version in sPHENIX GitHub at line 21 of file InttSurveyMap.h
typedef std::map<InttMap::Offline_s, Eigen::Affine3d, InttMap::OfflineComparator> InttSurveyMap::map_t
Definition at line 20 of file InttSurveyMap.h.
View newest version in sPHENIX GitHub at line 20 of file InttSurveyMap.h
typedef Eigen::Affine3d InttSurveyMap::val_t
Definition at line 22 of file InttSurveyMap.h.
View newest version in sPHENIX GitHub at line 22 of file InttSurveyMap.h
Constructor & Destructor Documentation
InttSurveyMap::InttSurveyMap () default
InttSurveyMap::~InttSurveyMap () override default
Member Function Documentation
InttSurveyMap::val_t const * InttSurveyMap::GetAbsoluteTransform (key_t k) const virtual
Definition at line 72 of file InttSurveyMap.cc.
View newest version in sPHENIX GitHub at line 72 of file InttSurveyMap.cc
References InttMap::Offline_s::ladder_phi, InttMap::Offline_s::ladder_z, InttMap::Offline_s::layer, InttMap::Offline_s::strip_phi, InttMap::Offline_s::strip_z, v_LookupAbsoluteTransform(), and InttMap::Wildcard.
InttSurveyMap::val_t const * InttSurveyMap::GetRelativeTransform (key_t k) const virtual
Definition at line 115 of file InttSurveyMap.cc.
View newest version in sPHENIX GitHub at line 115 of file InttSurveyMap.cc
References InttMap::Offline_s::ladder_phi, InttMap::Offline_s::ladder_z, InttMap::Offline_s::layer, InttMap::Offline_s::strip_phi, InttMap::Offline_s::strip_z, v_LookupRelativeTransform(), and InttMap::Wildcard.
void InttSurveyMap::identify (std::ostream & os = std::cout) const override virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from PHObject.
Reimplemented in InttSurveyMapv1.
Definition at line 10 of file InttSurveyMap.cc.
View newest version in sPHENIX GitHub at line 10 of file InttSurveyMap.cc
int InttSurveyMap::LoadFromCDB (std::string const & name = "InttSurveyMap")
Definition at line 48 of file InttSurveyMap.cc.
View newest version in sPHENIX GitHub at line 48 of file InttSurveyMap.cc
References CDBInterface::getUrl(), CDBInterface::instance(), CDBTTree::LoadCalibrations(), and v_LoadFromCDBTTree().
int InttSurveyMap::LoadFromFile (std::string const & filename = "InttSurveyMap.root")
Definition at line 25 of file InttSurveyMap.cc.
View newest version in sPHENIX GitHub at line 25 of file InttSurveyMap.cc
References Acts::Concepts::exists, CDBTTree::LoadCalibrations(), and v_LoadFromCDBTTree().
std::size_t InttSurveyMap::size (void) const virtual
Reimplemented in InttSurveyMapv1.
Definition at line 20 of file InttSurveyMap.cc.
View newest version in sPHENIX GitHub at line 20 of file InttSurveyMap.cc
int InttSurveyMap::v_LoadFromCDBTTree (CDBTTree &) protected virtual
Reimplemented in InttSurveyMapv1.
Definition at line 65 of file InttSurveyMap.cc.
View newest version in sPHENIX GitHub at line 65 of file InttSurveyMap.cc
Referenced by LoadFromCDB(), and LoadFromFile().
int InttSurveyMap::v_LookupAbsoluteTransform (key_t const & , map_t::const_iterator &) const protected virtual
Reimplemented in InttSurveyMapv1.
Definition at line 158 of file InttSurveyMap.cc.
View newest version in sPHENIX GitHub at line 158 of file InttSurveyMap.cc
Referenced by GetAbsoluteTransform().
int InttSurveyMap::v_LookupRelativeTransform (key_t const & , map_t::const_iterator &) const protected virtual
Reimplemented in InttSurveyMapv1.
Definition at line 165 of file InttSurveyMap.cc.
View newest version in sPHENIX GitHub at line 165 of file InttSurveyMap.cc
Referenced by GetRelativeTransform().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/intt/InttSurveyMap.h
coresoftware/blob/master/offline/packages/intt/InttSurveyMap.cc