Analysis Software: OnlMon/blob/master/onlmonserver/HistoServer.h File Reference
HistoServer.h File Reference
Functions
int setup_server ()
void handleconnection (void *arg)
void handletest (void *arg)
void send_test_message ()
Function Documentation
void handleconnection (void * arg)
Definition at line 157 of file HistoServer.cc.
View newest version in sPHENIX GitHub at line 157 of file HistoServer.cc
References Fun4AllServer::getHisto(), Fun4AllServer::getHistoName(), i, OnlMonServer::instance(), TauVsDIS_MachineLearning_Differentiation::msg, printf(), return(), and Fun4AllBase::Verbosity().
Referenced by server().
void handletest (void * arg)
Definition at line 150 of file HistoServer.cc.
View newest version in sPHENIX GitHub at line 150 of file HistoServer.cc
References return().
void send_test_message ()
Definition at line 338 of file HistoServer.cc.
View newest version in sPHENIX GitHub at line 338 of file HistoServer.cc
References MONIPORT.
Referenced by OnlMonServer::testmsg().
int setup_server ()
Definition at line 37 of file HistoServer.cc.
View newest version in sPHENIX GitHub at line 37 of file HistoServer.cc
References OnlMonServer::GetMutex(), OnlMonServer::instance(), mutex, server(), ServerThread, OnlMonServer::SetThreadId(), and ThreadId.
Referenced by OnlMonServer::StartServer().