Analysis Software: analysis/blob/master/JS-Jet/FastJetMedianBkg/src_JetMedianTree/macro/loc_lib/loc_lib.h File Reference
loc_lib.h File Reference
#include "noiBinVec.h"
#include "pAu_bins.h"
#include "noi_fnc.h"
Functions
TH1D * norm_binwidths (TH1D *hg)
float calc_dphi (float a, float b)
TH1D * rebin_TH1D (TH1D *hg_in, vector< int > i_bins, string _name="", bool delete_hg_in=true, bool norm_by_cnt=true, bool norm_by_width=true)
void div_by_W (TH1D *hg, TH1D *w)
void set_range (int axis, int bin0, int bin1, vector< THnSparseD * > vec_sparse, bool print=false)
pair< double, double > sparse_integral (THnSparseD *sp)
TH1D * sparse_proj (THnSparseD *sp, int i_ax, string name="", bool norm_bin_width=false)
void set_track_cuts (vector< THnSparseD * > data)
TH1D * emb_eff_per_zdcx_binnedby3 (THnSparseD *reco, THnSparseD *truth, string name)
TH1D * hg_abs_max (vector< TH1D * > vdat)
TH1D * hg_abs_deltarat (TH1D *nom, TH1D *comp)
TH1D * hg_abs_delta (TH1D *nom, TH1D *comp)
TH1D * hg_const (TH1D *nom, double val, string name)
TH1D * hg_RSS (vector< TH1D * > vec, string name)
TH1D * hg_syserr (TH1D *hg_nom, TH1D *hg_rss, string name)
Function Documentation
float calc_dphi (float a, float b)
Definition at line 23 of file loc_lib.h.
View newest version in sPHENIX GitHub at line 23 of file loc_lib.h
References _, and KFPMath::b.
void div_by_W (TH1D * hg, TH1D * w)
Definition at line 72 of file loc_lib.h.
View newest version in sPHENIX GitHub at line 72 of file loc_lib.h
References i.
TH1D* emb_eff_per_zdcx_binnedby3 (THnSparseD * reco, THnSparseD * truth, string name)
Definition at line 119 of file loc_lib.h.
View newest version in sPHENIX GitHub at line 119 of file loc_lib.h
References _pt, _zdcx, i, noiUniqueName(), norm, and set_range().
TH1D* hg_abs_delta (TH1D * nom, TH1D * comp)
Definition at line 178 of file loc_lib.h.
View newest version in sPHENIX GitHub at line 178 of file loc_lib.h
References i, and noiUniqueName().
TH1D* hg_abs_deltarat (TH1D * nom, TH1D * comp)
Definition at line 165 of file loc_lib.h.
View newest version in sPHENIX GitHub at line 165 of file loc_lib.h
References i, and noiUniqueName().
TH1D* hg_abs_max (vector< TH1D * > vdat)
Definition at line 150 of file loc_lib.h.
View newest version in sPHENIX GitHub at line 150 of file loc_lib.h
References noiUniqueName().
TH1D* hg_const (TH1D * nom, double val, string name)
Definition at line 191 of file loc_lib.h.
View newest version in sPHENIX GitHub at line 191 of file loc_lib.h
References i.
TH1D* hg_RSS (vector< TH1D * > vec, string name)
Definition at line 200 of file loc_lib.h.
View newest version in sPHENIX GitHub at line 200 of file loc_lib.h
References i.
TH1D* hg_syserr (TH1D * hg_nom, TH1D * hg_rss, string name)
Definition at line 214 of file loc_lib.h.
View newest version in sPHENIX GitHub at line 214 of file loc_lib.h
References i.
TH1D* norm_binwidths (TH1D * hg)
Definition at line 11 of file loc_lib.h.
View newest version in sPHENIX GitHub at line 11 of file loc_lib.h
References CKF_timing_vs_mu::ax, and i.
Referenced by sparse_proj().
TH1D* rebin_TH1D (TH1D * hg_in, vector< int > i_bins, string _name = "", bool delete_hg_in = true, bool norm_by_cnt = true, bool norm_by_width = true)
Definition at line 30 of file loc_lib.h.
View newest version in sPHENIX GitHub at line 30 of file loc_lib.h
References CKF_timing_vs_mu::ax, Acts::PhysicalConstants::c, Acts::UnitConstants::e, edges, i, k, perf_headwind::name, nbins, noiUniqueName(), and sum().
void set_range (int axis, int bin0, int bin1, vector< THnSparseD * > vec_sparse, bool print = false)
Definition at line 85 of file loc_lib.h.
View newest version in sPHENIX GitHub at line 85 of file loc_lib.h
References CKF_timing_vs_mu::ax, and print().
Referenced by emb_eff_per_zdcx_binnedby3(), and set_track_cuts().
void set_track_cuts (vector< THnSparseD * > data)
Definition at line 113 of file loc_lib.h.
View newest version in sPHENIX GitHub at line 113 of file loc_lib.h
References _dca, _nhitfit, _nhitrat, and set_range().
pair<double,double> sparse_integral (THnSparseD * sp)
Definition at line 97 of file loc_lib.h.
View newest version in sPHENIX GitHub at line 97 of file loc_lib.h
TH1D* sparse_proj (THnSparseD * sp, int i_ax, string name = "", bool norm_bin_width = false)
Definition at line 105 of file loc_lib.h.
View newest version in sPHENIX GitHub at line 105 of file loc_lib.h
References perf_headwind::name, noiUniqueName(), and norm_binwidths().