Analysis Software: PHRTreeSeeding Class Reference
PHRTreeSeeding Class Reference
#include <coresoftware/blob/master/offline/packages/trackreco/PHRTreeSeeding.h>
Public Member Functions
PHRTreeSeeding (const std::string &name="PHRTreeSeeding", unsigned int nlayers_maps=3, unsigned int nlayers_intt=4, unsigned int nlayers_tpc=48, unsigned int start_layer=53)
double chisq (const double *xx)
void set_phi_scale (float scale)
void set_z_scale (float scale)
~PHRTreeSeeding () override
Public Member Functions inherited from PHTrackSeeding
PHTrackSeeding (const std::string &name="PHTrackSeeding")
~PHTrackSeeding () override
int InitRun (PHCompositeNode *topNode) override
int process_event (PHCompositeNode *topNode) override
int End (PHCompositeNode *topNode) override
Called at the end of all processing.
void set_track_map_name (const std::string &map_name)
void SetUseTruthClusters (bool setit)
Public Member Functions inherited from SubsysReco
~SubsysReco () override
virtual int EndRun (const int)
Called at the end of each run.
virtual int Init (PHCompositeNode *)
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
void Print (const std::string &what="ALL") const override
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Protected Member Functions
int Setup (PHCompositeNode *topNode) override
int GetNodes (PHCompositeNode *topNode)
int Process ()
int Process (PHCompositeNode *topNode) override
int InitializeGeometry (PHCompositeNode *topNode)
int End () override
Called in SubsysReco::End.
Private Member Functions
double phiadd (double phi1, double phi2)
double phidiff (double phi1, double phi2)
double costfunction (const double *xx)
void FillTree ()
double pointKeyToTuple (pointKey *pK)
void QueryTree (const bgi::rtree< pointKey, bgi::quadratic< 16 >> &rtree, double phimin, double etamin, double lmin, double phimax, double etamax, double lmax, std::vector< pointKey > &returned_values)
Private Attributes
SvtxClusterMap * _g4clusters
fetch node pointers
SvtxTrackMap * _g4tracks
SvtxVertexMap * _g4vertexes
TrkrClusterContainer * _cluster_map
SvtxHitMap * _svtxhitsmap
int * _hit_used_map
int _hit_used_map_size
double phisr
double etasr
double phist
double etast
double phixt
double etaxt
std::vector< float > _radii_all
std::map< int, unsigned int > _layer_ilayer_map_all
std::map< int, unsigned int > _layer_ilayer_map
unsigned int _nlayers_maps
unsigned int _nlayers_intt
unsigned int _nlayers_tpc
unsigned int _start_layer
float _phi_scale
float _z_scale
bgi::rtree< pointKey,
bgi::quadratic< 16 > > _rtree
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = INT_MAX - 10
}
Protected Attributes inherited from PHTrackSeeding
TrkrClusterContainer * _cluster_map = nullptr
TrkrClusterHitAssoc * _cluster_hit_map = nullptr
SvtxVertexMap * _vertex_map = nullptr
SvtxTrackMap * _track_map = nullptr
AssocInfoContainer * _assoc_container = nullptr
TrkrHitSetContainer * _hitsets = nullptr
std::string _track_map_name = "SvtxTrackMap"
bool _use_truth_clusters = false
Detailed Description
Definition at line 59 of file PHRTreeSeeding.h.
View newest version in sPHENIX GitHub at line 59 of file PHRTreeSeeding.h
Constructor & Destructor Documentation
PHRTreeSeeding::PHRTreeSeeding (const std::string & name = "PHRTreeSeeding", unsigned int nlayers_maps = 3, unsigned int nlayers_intt = 4, unsigned int nlayers_tpc = 48, unsigned int start_layer = 53)
Definition at line 75 of file PHRTreeSeeding.cc.
View newest version in sPHENIX GitHub at line 75 of file PHRTreeSeeding.cc
PHRTreeSeeding::~PHRTreeSeeding () inline override
Definition at line 74 of file PHRTreeSeeding.h.
View newest version in sPHENIX GitHub at line 74 of file PHRTreeSeeding.h
Member Function Documentation
double PHRTreeSeeding::chisq (const double * xx)
Definition at line 419 of file PHRTreeSeeding.cc.
View newest version in sPHENIX GitHub at line 419 of file PHRTreeSeeding.cc
References clusterpoints, TrkrCluster::getError(), TrkrCluster::getX(), TrkrCluster::getY(), TrkrCluster::getZ(), i, and M_PI.
double PHRTreeSeeding::costfunction (const double * xx) private
int PHRTreeSeeding::End () override protected virtual
Called in SubsysReco::End.
Implements PHTrackSeeding.
Definition at line 729 of file PHRTreeSeeding.cc.
View newest version in sPHENIX GitHub at line 729 of file PHRTreeSeeding.cc
References Fun4AllReturnCodes::EVENT_OK.
void PHRTreeSeeding::FillTree () private
Definition at line 441 of file PHRTreeSeeding.cc.
View newest version in sPHENIX GitHub at line 441 of file PHRTreeSeeding.cc
References _cluster_map, PHTrackSeeding::_hitsets, _rtree, _vertex, PHTimer::get_accumulated_time(), SvtxVertex::get_x(), SvtxVertex::get_y(), SvtxVertex::get_z(), TrkrClusterContainer::getClusters(), TrkrHitSetContainer::getHitSets(), TrkrDefs::getLayer(), TrkrCluster::getPosition(), j, layer, M_PI, QueryTree(), PHTimer::restart(), PHTimer::stop(), and TrkrDefs::tpcId.
Referenced by Process().
int PHRTreeSeeding::GetNodes (PHCompositeNode * topNode) protected
Definition at line 345 of file PHRTreeSeeding.cc.
View newest version in sPHENIX GitHub at line 345 of file PHRTreeSeeding.cc
References _cluster_map, Fun4AllReturnCodes::ABORTEVENT, Fun4AllReturnCodes::EVENT_OK, and PHWHERE.
Referenced by Setup().
int PHRTreeSeeding::InitializeGeometry (PHCompositeNode * topNode) protected
Definition at line 104 of file PHRTreeSeeding.cc.
View newest version in sPHENIX GitHub at line 104 of file PHRTreeSeeding.cc
References _layer_ilayer_map, _layer_ilayer_map_all, _radii_all, Fun4AllReturnCodes::EVENT_OK, PHG4CylinderCellGeomContainer::get_begin_end(), PHG4CylinderCellGeom::get_layer(), PHG4CylinderGeom::get_layer(), PHG4CylinderCellGeom::get_radius(), PHG4CylinderGeom::get_radius(), PHG4CylinderCellGeom::get_thickness(), PHG4CylinderGeom::get_thickness(), and findNode::getClass().
Referenced by Setup().
double PHRTreeSeeding::phiadd (double phi1, double phi2) private
Definition at line 360 of file PHRTreeSeeding.cc.
View newest version in sPHENIX GitHub at line 360 of file PHRTreeSeeding.cc
References M_PI, and Acts::UnitConstants::s.
double PHRTreeSeeding::phidiff (double phi1, double phi2) private
Definition at line 371 of file PHRTreeSeeding.cc.
View newest version in sPHENIX GitHub at line 371 of file PHRTreeSeeding.cc
References d, and M_PI.
Referenced by Process().
double PHRTreeSeeding::pointKeyToTuple (pointKey * pK) private
int PHRTreeSeeding::Process () protected
int PHRTreeSeeding::Process (PHCompositeNode * topNode) override protected virtual
process event interface for trackers, called in process_event. implemented in derived classes
Implements PHTrackSeeding.
Definition at line 485 of file PHRTreeSeeding.cc.
View newest version in sPHENIX GitHub at line 485 of file PHRTreeSeeding.cc
References _cluster_map, _phi_scale, _radii_all, _rtree, _start_layer, PHTrackSeeding::_track_map, _vertex, PHTrackSeeding::_vertex_map, _z_scale, kdfinder::abs(), centrality::dist(), etasr, etast, Fun4AllReturnCodes::EVENT_OK, FillTree(), TrkrClusterContainer::findCluster(), SvtxVertexMap::get(), PHTimer::get_accumulated_time(), SvtxVertex::get_x(), SvtxVertex::get_y(), SvtxVertex::get_z(), TrkrCluster::getError(), SvtxTrackMap::insert(), SvtxTrack_v1::insert_cluster_key(), it, j, M_PI, phidiff(), phisr, phist, QueryTree(), PHTimer::restart(), SvtxTrack_v1::set_charge(), SvtxTrack_v1::set_error(), SvtxTrack_v1::set_id(), SvtxTrack_v1::set_ndf(), SvtxTrack_v1::set_px(), SvtxTrack_v1::set_py(), SvtxTrack_v1::set_pz(), SvtxTrack_v1::set_x(), SvtxTrack_v1::set_y(), SvtxTrack_v1::set_z(), PHTimer::stop(), and Acts::Test::transform.
void PHRTreeSeeding::QueryTree (const bgi::rtree< pointKey, bgi::quadratic< 16 >> & rtree, double phimin, double etamin, double lmin, double phimax, double etamax, double lmax, std::vector< pointKey > & returned_values) private
Definition at line 382 of file PHRTreeSeeding.cc.
View newest version in sPHENIX GitHub at line 382 of file PHRTreeSeeding.cc
References M_PI.
Referenced by FillTree(), and Process().
void PHRTreeSeeding::set_phi_scale (float scale) inline
Definition at line 71 of file PHRTreeSeeding.h.
View newest version in sPHENIX GitHub at line 71 of file PHRTreeSeeding.h
References _phi_scale.
void PHRTreeSeeding::set_z_scale (float scale) inline
Definition at line 72 of file PHRTreeSeeding.h.
View newest version in sPHENIX GitHub at line 72 of file PHRTreeSeeding.h
References _z_scale.
int PHRTreeSeeding::Setup (PHCompositeNode * topNode) override protected virtual
setup interface for trackers, called in InitRun, setup things like pointers to nodes. overrided in derived classes
Reimplemented from PHTrackSeeding.
Definition at line 717 of file PHRTreeSeeding.cc.
View newest version in sPHENIX GitHub at line 717 of file PHRTreeSeeding.cc
References Fun4AllReturnCodes::EVENT_OK, GetNodes(), InitializeGeometry(), and PHTrackSeeding::Setup().
Member Data Documentation
TrkrClusterContainer* PHRTreeSeeding::_cluster_map private
Definition at line 94 of file PHRTreeSeeding.h.
View newest version in sPHENIX GitHub at line 94 of file PHRTreeSeeding.h
Referenced by FillTree(), GetNodes(), and Process().
SvtxClusterMap* PHRTreeSeeding::_g4clusters private
fetch node pointers
Definition at line 91 of file PHRTreeSeeding.h.
View newest version in sPHENIX GitHub at line 91 of file PHRTreeSeeding.h
SvtxTrackMap* PHRTreeSeeding::_g4tracks private
Definition at line 92 of file PHRTreeSeeding.h.
View newest version in sPHENIX GitHub at line 92 of file PHRTreeSeeding.h
SvtxVertexMap* PHRTreeSeeding::_g4vertexes private
Definition at line 93 of file PHRTreeSeeding.h.
View newest version in sPHENIX GitHub at line 93 of file PHRTreeSeeding.h
int* PHRTreeSeeding::_hit_used_map private
Definition at line 97 of file PHRTreeSeeding.h.
View newest version in sPHENIX GitHub at line 97 of file PHRTreeSeeding.h
int PHRTreeSeeding::_hit_used_map_size private
Definition at line 98 of file PHRTreeSeeding.h.
View newest version in sPHENIX GitHub at line 98 of file PHRTreeSeeding.h
std::map<int, unsigned int> PHRTreeSeeding::_layer_ilayer_map private
Definition at line 115 of file PHRTreeSeeding.h.
View newest version in sPHENIX GitHub at line 115 of file PHRTreeSeeding.h
Referenced by InitializeGeometry().
std::map<int, unsigned int> PHRTreeSeeding::_layer_ilayer_map_all private
Definition at line 114 of file PHRTreeSeeding.h.
View newest version in sPHENIX GitHub at line 114 of file PHRTreeSeeding.h
Referenced by InitializeGeometry().
unsigned int PHRTreeSeeding::_nlayers_intt private
Definition at line 122 of file PHRTreeSeeding.h.
View newest version in sPHENIX GitHub at line 122 of file PHRTreeSeeding.h
unsigned int PHRTreeSeeding::_nlayers_maps private
Definition at line 121 of file PHRTreeSeeding.h.
View newest version in sPHENIX GitHub at line 121 of file PHRTreeSeeding.h
unsigned int PHRTreeSeeding::_nlayers_tpc private
Definition at line 123 of file PHRTreeSeeding.h.
View newest version in sPHENIX GitHub at line 123 of file PHRTreeSeeding.h
float PHRTreeSeeding::_phi_scale private
Definition at line 125 of file PHRTreeSeeding.h.
View newest version in sPHENIX GitHub at line 125 of file PHRTreeSeeding.h
Referenced by Process(), and set_phi_scale().
std::vector<float> PHRTreeSeeding::_radii_all private
Definition at line 103 of file PHRTreeSeeding.h.
View newest version in sPHENIX GitHub at line 103 of file PHRTreeSeeding.h
Referenced by InitializeGeometry(), and Process().
bgi::rtree<pointKey, bgi::quadratic<16> > PHRTreeSeeding::_rtree private
Definition at line 129 of file PHRTreeSeeding.h.
View newest version in sPHENIX GitHub at line 129 of file PHRTreeSeeding.h
Referenced by FillTree(), and Process().
unsigned int PHRTreeSeeding::_start_layer private
Definition at line 124 of file PHRTreeSeeding.h.
View newest version in sPHENIX GitHub at line 124 of file PHRTreeSeeding.h
Referenced by Process().
SvtxHitMap* PHRTreeSeeding::_svtxhitsmap private
Definition at line 96 of file PHRTreeSeeding.h.
View newest version in sPHENIX GitHub at line 96 of file PHRTreeSeeding.h
float PHRTreeSeeding::_z_scale private
Definition at line 126 of file PHRTreeSeeding.h.
View newest version in sPHENIX GitHub at line 126 of file PHRTreeSeeding.h
Referenced by Process(), and set_z_scale().
double PHRTreeSeeding::etasr private
Definition at line 101 of file PHRTreeSeeding.h.
View newest version in sPHENIX GitHub at line 101 of file PHRTreeSeeding.h
Referenced by Process().
double PHRTreeSeeding::etast private
Definition at line 101 of file PHRTreeSeeding.h.
View newest version in sPHENIX GitHub at line 101 of file PHRTreeSeeding.h
Referenced by Process().
double PHRTreeSeeding::etaxt private
Definition at line 101 of file PHRTreeSeeding.h.
View newest version in sPHENIX GitHub at line 101 of file PHRTreeSeeding.h
double PHRTreeSeeding::phisr private
Definition at line 101 of file PHRTreeSeeding.h.
View newest version in sPHENIX GitHub at line 101 of file PHRTreeSeeding.h
Referenced by Process().
double PHRTreeSeeding::phist private
Definition at line 101 of file PHRTreeSeeding.h.
View newest version in sPHENIX GitHub at line 101 of file PHRTreeSeeding.h
Referenced by Process().
double PHRTreeSeeding::phixt private
Definition at line 101 of file PHRTreeSeeding.h.
View newest version in sPHENIX GitHub at line 101 of file PHRTreeSeeding.h
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/trackreco/PHRTreeSeeding.h
coresoftware/blob/master/offline/packages/trackreco/PHRTreeSeeding.cc