Analysis Software: macros/blob/master/common/G4_Mvtx.C File Reference
G4_Mvtx.C File Reference
#include <GlobalVariables.C>
#include <QA.C>
#include <g4detectors/PHG4CylinderSubsystem.h>
#include <g4mvtx/PHG4MvtxDefs.h>
#include <g4mvtx/PHG4MvtxDigitizer.h>
#include <g4mvtx/PHG4MvtxHitReco.h>
#include <g4mvtx/PHG4MvtxSubsystem.h>
#include <g4main/PHG4Reco.h>
#include <mvtx/MvtxClusterizer.h>
#include <qa_modules/QAG4SimulationMvtx.h>
#include <fun4all/Fun4AllServer.h>
#include <cmath>
#include <vector>
Namespaces
namespace Enable
namespace G4MVTX
Macros
#define MACRO_G4MVTX_C
Functions
void MvtxInit ()
double calculateArea (double inner_radius, double outer_radius)
double calculateOR (double inner_radius, double area)
void calculateMaterialBoundaries (int &service_layer_ID, double &outer_copper_radius, double &outer_water_radius, double &outer_plastic_radius)
double MVTXService (PHG4Reco *g4Reco, double radius)
double Mvtx (PHG4Reco *g4Reco, double radius, const int absorberactive=0)
void Mvtx_Cells ()
void Mvtx_Clustering ()
void Mvtx_QA ()
Variables
bool Enable::MVTX = false
bool Enable::MVTX_OVERLAPCHECK = false
bool Enable::MVTX_CELL = false
bool Enable::MVTX_CLUSTER = false
bool Enable::MVTX_QA = false
bool Enable::MVTX_ABSORBER = false
bool Enable::MVTX_SERVICE = true
int Enable::MVTX_VERBOSITY = 0
int G4MVTX::n_maps_layer = 3
double G4MVTX::radius_offset = 0.7
double G4MVTX::single_stave_service_copper_area = 0.0677
double G4MVTX::single_stave_service_water_area = 0.0098
double G4MVTX::single_stave_service_plastic_area = 0.4303
const int G4MVTX::n_service_layers = 1
double G4MVTX::service_layer_start_radius [] = {8.5}
int G4MVTX::n_staves_service_layer [] = {48}
double G4MVTX::service_barrel_radius = 10.75
double G4MVTX::service_barrel_start = -35
double G4MVTX::service_barrel_length = 150
Macro Definition Documentation
#define MACRO_G4MVTX_C
Definition at line 2 of file G4_Mvtx.C.
View newest version in sPHENIX GitHub at line 2 of file G4_Mvtx.C
Function Documentation
double calculateArea (double inner_radius, double outer_radius)
Definition at line 67 of file G4_Mvtx.C.
View newest version in sPHENIX GitHub at line 67 of file G4_Mvtx.C
References M_PI.
void calculateMaterialBoundaries (int & service_layer_ID, double & outer_copper_radius, double & outer_water_radius, double & outer_plastic_radius)
Definition at line 77 of file G4_Mvtx.C.
View newest version in sPHENIX GitHub at line 77 of file G4_Mvtx.C
References calculateOR(), G4MVTX::n_staves_service_layer, G4MVTX::service_layer_start_radius, G4MVTX::single_stave_service_copper_area, G4MVTX::single_stave_service_plastic_area, and G4MVTX::single_stave_service_water_area.
Referenced by MVTXService().
double calculateOR (double inner_radius, double area)
Definition at line 72 of file G4_Mvtx.C.
View newest version in sPHENIX GitHub at line 72 of file G4_Mvtx.C
References M_PI.
Referenced by calculateMaterialBoundaries().
double Mvtx (PHG4Reco * g4Reco, double radius, const int absorberactive = 0)
Definition at line 185 of file G4_Mvtx.C.
View newest version in sPHENIX GitHub at line 185 of file G4_Mvtx.C
References PHG4MvtxDefs::GLOBAL, PHG4MvtxDefs::kRmd, max, Enable::MVTX_OVERLAPCHECK, Enable::MVTX_SERVICE, Enable::MVTX_VERBOSITY, PHG4MvtxDefs::mvtxdat, MVTXService(), G4MVTX::n_maps_layer, Enable::OVERLAPCHECK, PHG4DetectorGroupSubsystem::OverlapCheck(), G4MVTX::radius_offset, PHG4Reco::registerSubsystem(), PHG4DetectorGroupSubsystem::set_string_param(), PHG4DetectorGroupSubsystem::SetActive(), verbosity, Enable::VERBOSITY, and Fun4AllBase::Verbosity().
Referenced by G4Setup().
void Mvtx_Cells ()
Definition at line 213 of file G4_Mvtx.C.
View newest version in sPHENIX GitHub at line 213 of file G4_Mvtx.C
References Fun4AllServer::instance(), max, Enable::MVTX_VERBOSITY, G4MVTX::n_maps_layer, Fun4AllServer::registerSubsystem(), PHG4MvtxHitReco::set_timing_window(), verbosity, Enable::VERBOSITY, and Fun4AllBase::Verbosity().
Referenced by Fun4All_AnaTutorial_sPHENIX(), Fun4All_AnaTutorial_sPHENIX_Jets(), and Fun4All_G4_sPHENIX().
void Mvtx_Clustering ()
Definition at line 236 of file G4_Mvtx.C.
View newest version in sPHENIX GitHub at line 236 of file G4_Mvtx.C
References Fun4AllServer::instance(), max, Enable::MVTX_VERBOSITY, Fun4AllServer::registerSubsystem(), verbosity, Enable::VERBOSITY, and Fun4AllBase::Verbosity().
Referenced by Fun4All_AnaTutorial_sPHENIX(), Fun4All_AnaTutorial_sPHENIX_Jets(), and Fun4All_G4_sPHENIX().
void Mvtx_QA ()
Definition at line 248 of file G4_Mvtx.C.
View newest version in sPHENIX GitHub at line 248 of file G4_Mvtx.C
References Fun4AllServer::instance(), max, Enable::MVTX_VERBOSITY, Enable::QA_VERBOSITY, Fun4AllServer::registerSubsystem(), verbosity, and Fun4AllBase::Verbosity().
Referenced by Fun4All_AnaTutorial_sPHENIX(), Fun4All_AnaTutorial_sPHENIX_Jets(), and Fun4All_G4_sPHENIX().
void MvtxInit ()
Definition at line 58 of file G4_Mvtx.C.
View newest version in sPHENIX GitHub at line 58 of file G4_Mvtx.C
References max, BlackHoleGeometry::max_radius, min, BlackHoleGeometry::min_z, G4MVTX::service_barrel_length, G4MVTX::service_barrel_radius, and G4MVTX::service_barrel_start.
Referenced by G4Init().
double MVTXService (PHG4Reco * g4Reco, double radius)
Definition at line 84 of file G4_Mvtx.C.
View newest version in sPHENIX GitHub at line 84 of file G4_Mvtx.C
References Enable::ABSORBER, calculateMaterialBoundaries(), i, j, max, Enable::MVTX_ABSORBER, Enable::MVTX_OVERLAPCHECK, Enable::MVTX_VERBOSITY, G4MVTX::n_service_layers, G4MVTX::n_staves_service_layer, no_overlapp, PHG4DetectorSubsystem::OverlapCheck(), Enable::OVERLAPCHECK, PHG4Reco::registerSubsystem(), G4MVTX::service_barrel_length, G4MVTX::service_barrel_radius, G4MVTX::service_barrel_start, G4MVTX::service_layer_start_radius, PHG4DetectorSubsystem::set_double_param(), PHG4DetectorSubsystem::set_int_param(), PHG4DetectorSubsystem::set_string_param(), PHG4DetectorSubsystem::SetActive(), G4MVTX::single_stave_service_copper_area, G4MVTX::single_stave_service_plastic_area, G4MVTX::single_stave_service_water_area, PHG4DetectorSubsystem::SuperDetector(), nlohmann::to_string(), verbosity, and Enable::VERBOSITY.
Referenced by Mvtx().