Analysis Software: InttMon Class Reference
InttMon Class Reference
#include <OnlMon/blob/main/subsystems/intt/InttMon.h>
Public Member Functions
InttMon (const std::string &name)
virtual ~InttMon ()
int Init ()
int BeginRun (const int)
int process_event (Event *)
int Reset ()
int MiscDebug ()
void RandomEvent (int)
Public Member Functions inherited from OnlMon
OnlMon (const std::string &name="NONE")
~OnlMon () override
virtual int process_event_common (Event *evt)
virtual int InitCommon (OnlMonServer *se)
virtual void identify (std::ostream &out=std::cout) const
virtual int BeginRunCommon (const int runno, OnlMonServer *se)
virtual int EndRun (const int)
virtual void SetStatus (const int newstatus)
virtual int ResetEvent ()
virtual void SetMonitorServerId (unsigned int i)
virtual unsigned int MonitorServerId () const
Public Member Functions inherited from OnlMonBase
OnlMonBase (const std::string &name="NONE")
virtual ~OnlMonBase ()
const std::string Name () const
void Name (const std::string &name)
virtual void Verbosity (const int i)
virtual int Verbosity () const
Private Member Functions
int DBVarInit ()
int DBVarUpdate ()
Private Attributes
TRandom * rng = nullptr
OnlMonDB * dbvars = nullptr
int evtcnt = 0
TH1D * NumEvents = nullptr
TH1D * HitMap = nullptr
Additional Inherited Members
Public Types inherited from OnlMon
enum { ACTIVE = -1, OK = 0, WARNING = 1, ERROR = 2 }
Protected Attributes inherited from OnlMon
int status
unsigned int m_MonitorServerId = 0
TH1 * m_LocalFrameWorkVars = nullptr
Detailed Description
Definition at line 27 of file InttMon.h.
View newest version in sPHENIX GitHub at line 27 of file InttMon.h
Constructor & Destructor Documentation
InttMon::InttMon (const std::string & name)
Definition at line 4 of file InttMon.cc.
View newest version in sPHENIX GitHub at line 4 of file InttMon.cc
InttMon::~InttMon () virtual
Definition at line 10 of file InttMon.cc.
View newest version in sPHENIX GitHub at line 10 of file InttMon.cc
References dbvars.
Member Function Documentation
int InttMon::BeginRun (const int) virtual
Reimplemented from OnlMon.
Definition at line 54 of file InttMon.cc.
View newest version in sPHENIX GitHub at line 54 of file InttMon.cc
int InttMon::DBVarInit () private
Definition at line 148 of file InttMon.cc.
View newest version in sPHENIX GitHub at line 148 of file InttMon.cc
References OnlMonDB::DBInit(), dbvars, and OnlMonDB::registerVar().
Referenced by Init().
int InttMon::DBVarUpdate () private
Definition at line 160 of file InttMon.cc.
View newest version in sPHENIX GitHub at line 160 of file InttMon.cc
References dbvars, evtcnt, and OnlMonDB::SetVar().
Referenced by process_event().
int InttMon::Init () virtual
Reimplemented from OnlMon.
Definition at line 15 of file InttMon.cc.
View newest version in sPHENIX GitHub at line 15 of file InttMon.cc
References INTT::ADCS, DBVarInit(), dbvars, HitMap, OnlMonServer::instance(), NumEvents, OnlMonServer::registerHisto(), Reset(), rng, and OnlMonBase::ThisName.
int InttMon::MiscDebug ()
Definition at line 205 of file InttMon.cc.
View newest version in sPHENIX GitHub at line 205 of file InttMon.cc
References INTT::ADC, INTT::Indexes_s::adc, KFPMath::b, Acts::PhysicalConstants::c, INTT::CHANNEL, INTT::CHIP, INTT::Indexes_s::chn, INTT::Indexes_s::chp, INTT::FELIX_CHANNEL, INTT::GetFelixBinFromIndexes(), INTT::GetFelixIndexesFromBin(), and INTT::Indexes_s::lyr.
int InttMon::process_event (Event * evt) virtual
Reimplemented from OnlMon.
Definition at line 61 of file InttMon.cc.
View newest version in sPHENIX GitHub at line 61 of file InttMon.cc
References INTT::Indexes_s::adc, INTT::Indexes_s::arm, INTT_Felix::Ladder_s::barrel, INTT::Indexes_s::chn, INTT::Indexes_s::chp, DBVarUpdate(), INTT_Felix::FelixMap(), INTT::GetFelixBinFromIndexes(), Event::getPacket(), HitMap, Packet::iValue(), INTT_Felix::Ladder_s::ladder, INTT_Felix::Ladder_s::layer, INTT::Indexes_s::ldr, INTT::Indexes_s::lyr, n, N, NumEvents, merge_hashes::p, and train_ambiguity_solver::pid.
void InttMon::RandomEvent (int felix)
Definition at line 169 of file InttMon.cc.
View newest version in sPHENIX GitHub at line 169 of file InttMon.cc
References INTT::ADC, INTT::Indexes_s::adc, INTT::Indexes_s::arm, INTT_Felix::Ladder_s::barrel, INTT::CHANNEL, INTT::CHIP, INTT::Indexes_s::chn, INTT::Indexes_s::chp, INTT::FELIX_CHANNEL, INTT_Felix::FelixMap(), INTT::GetFelixBinFromIndexes(), HitMap, INTT_Felix::Ladder_s::ladder, INTT_Felix::Ladder_s::layer, INTT::Indexes_s::ldr, INTT::Indexes_s::lyr, NumEvents, printf(), and rng.
int InttMon::Reset () virtual
Reimplemented from OnlMon.
Definition at line 134 of file InttMon.cc.
View newest version in sPHENIX GitHub at line 134 of file InttMon.cc
References evtcnt, HitMap, and NumEvents.
Referenced by Init().
Member Data Documentation
OnlMonDB* InttMon::dbvars = nullptr private
Definition at line 50 of file InttMon.h.
View newest version in sPHENIX GitHub at line 50 of file InttMon.h
Referenced by DBVarInit(), DBVarUpdate(), Init(), and ~InttMon().
int InttMon::evtcnt = 0 private
Definition at line 51 of file InttMon.h.
View newest version in sPHENIX GitHub at line 51 of file InttMon.h
Referenced by DBVarUpdate(), and Reset().
TH1D* InttMon::HitMap = nullptr private
Definition at line 54 of file InttMon.h.
View newest version in sPHENIX GitHub at line 54 of file InttMon.h
Referenced by Init(), process_event(), RandomEvent(), and Reset().
TH1D* InttMon::NumEvents = nullptr private
Definition at line 53 of file InttMon.h.
View newest version in sPHENIX GitHub at line 53 of file InttMon.h
Referenced by Init(), process_event(), RandomEvent(), and Reset().
TRandom* InttMon::rng = nullptr private
Definition at line 43 of file InttMon.h.
View newest version in sPHENIX GitHub at line 43 of file InttMon.h
Referenced by Init(), and RandomEvent().
The documentation for this class was generated from the following files:
OnlMon/blob/main/subsystems/intt/InttMon.h
OnlMon/blob/main/subsystems/intt/InttMon.cc