Analysis Software: BbcPmtContainer Class Reference
BbcPmtContainer Class Reference
#include <coresoftware/blob/master/offline/packages/mbd/BbcPmtContainer.h>
Public Member Functions
virtual ~BbcPmtContainer ()
dtor
virtual void identify (std::ostream &os=std::cout) const override
virtual void Reset () override
Clear Event.
virtual int isValid () const override
isValid returns non zero if object contains valid data
virtual void set_npmt (const short ival)
virtual Short_t get_npmt () const
get Number of Bbc Pmt's
virtual BbcPmtHit * get_pmt (const int ipmt) const
get BbcPmtHit Object
Public Member Functions inherited from PHObject
PHObject ()
ctor
~PHObject () override
dtor
virtual PHObject * CloneMe () const
Virtual copy constructor.
virtual PHObject * clone () const final
PHObject * Clone (const char *newname="") const final
void Copy (TObject &object) const final
virtual int Integrate () const
virtual int Integrate (PHObject *)
virtual void CopyFrom (const PHObject *obj)
Private Member Functions
void virtual_warning (const std::string &funcname) const
Detailed Description
Definition at line 14 of file BbcPmtContainer.h.
View newest version in sPHENIX GitHub at line 14 of file BbcPmtContainer.h
Constructor & Destructor Documentation
virtual BbcPmtContainer::~BbcPmtContainer () inline virtual
dtor
Definition at line 18 of file BbcPmtContainer.h.
View newest version in sPHENIX GitHub at line 18 of file BbcPmtContainer.h
Member Function Documentation
Short_t BbcPmtContainer::get_npmt () const virtual
get Number of Bbc Pmt's
Reimplemented in BbcPmtContainerV1.
Definition at line 32 of file BbcPmtContainer.cc.
View newest version in sPHENIX GitHub at line 32 of file BbcPmtContainer.cc
References BbcReturnCodes::BBC_INVALID_SHORT, and virtual_warning().
BbcPmtHit * BbcPmtContainer::get_pmt (const int ipmt) const virtual
get BbcPmtHit Object
Reimplemented in BbcPmtContainerV1.
Definition at line 38 of file BbcPmtContainer.cc.
View newest version in sPHENIX GitHub at line 38 of file BbcPmtContainer.cc
References virtual_warning().
void BbcPmtContainer::identify (std::ostream & os = std::cout) const override virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from PHObject.
Reimplemented in BbcPmtContainerV1.
Definition at line 8 of file BbcPmtContainer.cc.
View newest version in sPHENIX GitHub at line 8 of file BbcPmtContainer.cc
int BbcPmtContainer::isValid () const override virtual
isValid returns non zero if object contains valid data
Reimplemented from PHObject.
Reimplemented in BbcPmtContainerV1.
Definition at line 20 of file BbcPmtContainer.cc.
View newest version in sPHENIX GitHub at line 20 of file BbcPmtContainer.cc
References virtual_warning().
void BbcPmtContainer::Reset () override virtual
Clear Event.
Reimplemented from PHObject.
Reimplemented in BbcPmtContainerV1.
Definition at line 14 of file BbcPmtContainer.cc.
View newest version in sPHENIX GitHub at line 14 of file BbcPmtContainer.cc
References PHWHERE.
void BbcPmtContainer::set_npmt (const short ival) virtual
set number of PMTs for Bbc
Parameters
ival Number of Bbc Pmt's
Definition at line 26 of file BbcPmtContainer.cc.
View newest version in sPHENIX GitHub at line 26 of file BbcPmtContainer.cc
References virtual_warning().
void BbcPmtContainer::virtual_warning (const std::string & funcname) const private
Definition at line 44 of file BbcPmtContainer.cc.
View newest version in sPHENIX GitHub at line 44 of file BbcPmtContainer.cc
Referenced by get_npmt(), get_pmt(), isValid(), and set_npmt().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/mbd/BbcPmtContainer.h
coresoftware/blob/master/offline/packages/mbd/BbcPmtContainer.cc