Analysis Software: analysis/blob/master/FrawleyTrackEvalMacros/CBfitter.C File Reference
CBfitter.C File Reference
#include <TF1.h>
#include <TMath.h>
#include <TFile.h>
#include <TCanvas.h>
#include <TH1.h>
#include <TGraph.h>
#include <TLegend.h>
#include <TStyle.h>
#include <TROOT.h>
#include <TLatex.h>
Functions
Double_t CBcalc (Double_t *xx, Double_t *par)
Double_t Upscalc (Double_t *xx, Double_t *par)
void CBfitter ()
Function Documentation
Double_t CBcalc (Double_t * xx, Double_t * par)
Definition at line 12 of file CBfitter.C.
View newest version in sPHENIX GitHub at line 12 of file CBfitter.C
References A, alpha, f, n, N, sigma, and ambiguity_solver_full_chain::x.
Referenced by CBfitter(), CBfitter_1state(), CBfitter_jpsi_1state(), CBfitter_jpsi_LL_single(), TrackingQA(), and Upscalc().
void CBfitter ()
Definition at line 91 of file CBfitter.C.
View newest version in sPHENIX GitHub at line 91 of file CBfitter.C
References Acts::PhysicalConstants::c, CBcalc(), double(), i, leg, recomass, step, Upscalc(), ambiguity_solver_full_chain::x, and y.
Double_t Upscalc (Double_t * xx, Double_t * par)
Definition at line 41 of file CBfitter.C.
View newest version in sPHENIX GitHub at line 41 of file CBfitter.C
References CBcalc(), std::tr1::f1, std::tr1::f2, std::tr1::f3, mass, and ambiguity_solver_full_chain::x.
Referenced by CBfitter().