Analysis Software: sigslot::_connection7< dest_type, arg1_type, arg2_type, arg3_type, arg4_type, arg5_type, arg6_type, arg7_type, mt_policy > Class Template Reference
sigslot::_connection7< dest_type, arg1_type, arg2_type, arg3_type, arg4_type, arg5_type, arg6_type, arg7_type, mt_policy > Class Template Reference
#include <JETSCAPE/blob/main/external_packages/sigslot.h>
Public Member Functions
_connection7 ()
_connection7 (dest_type *pobject, void(dest_type::*pmemfun)(arg1_type, arg2_type, arg3_type, arg4_type, arg5_type, arg6_type, arg7_type))
virtual _connection_base7
< arg1_type, arg2_type,
arg3_type, arg4_type,
arg5_type, arg6_type,
arg7_type, mt_policy > * clone ()
virtual _connection_base7
< arg1_type, arg2_type,
arg3_type, arg4_type,
arg5_type, arg6_type,
arg7_type, mt_policy > * duplicate (has_slots< mt_policy > *pnewdest)
virtual void emit (arg1_type a1, arg2_type a2, arg3_type a3, arg4_type a4, arg5_type a5, arg6_type a6, arg7_type a7)
virtual has_slots< mt_policy > * getdest () const
Public Member Functions inherited from sigslot::_connection_base7< arg1_type, arg2_type, arg3_type, arg4_type, arg5_type, arg6_type, arg7_type, mt_policy >
virtual ~_connection_base7 ()
Private Attributes
dest_type * m_pobject
void(dest_type::* m_pmemfun)(arg1_type, arg2_type, arg3_type, arg4_type, arg5_type, arg6_type, arg7_type)
Detailed Description
template<class dest_type, class arg1_type, class arg2_type, class arg3_type, class arg4_type, class arg5_type, class arg6_type, class arg7_type, class mt_policy>
class sigslot::_connection7< dest_type, arg1_type, arg2_type, arg3_type, arg4_type, arg5_type, arg6_type, arg7_type, mt_policy >
Definition at line 1836 of file sigslot.h.
View newest version in sPHENIX GitHub at line 1836 of file sigslot.h
Constructor & Destructor Documentation
template<class dest_type , class arg1_type , class arg2_type , class arg3_type , class arg4_type , class arg5_type , class arg6_type , class arg7_type , class mt_policy > sigslot::_connection7< dest_type, arg1_type, arg2_type, arg3_type, arg4_type, arg5_type, arg6_type, arg7_type, mt_policy >::_connection7 () inline
Definition at line 1840 of file sigslot.h.
View newest version in sPHENIX GitHub at line 1840 of file sigslot.h
template<class dest_type , class arg1_type , class arg2_type , class arg3_type , class arg4_type , class arg5_type , class arg6_type , class arg7_type , class mt_policy > sigslot::_connection7< dest_type, arg1_type, arg2_type, arg3_type, arg4_type, arg5_type, arg6_type, arg7_type, mt_policy >::_connection7 (dest_type * pobject, void(dest_type::*)(arg1_type, arg2_type, arg3_type, arg4_type, arg5_type, arg6_type, arg7_type) pmemfun) inline
Definition at line 1846 of file sigslot.h.
View newest version in sPHENIX GitHub at line 1846 of file sigslot.h
References sigslot::_connection7< dest_type, arg1_type, arg2_type, arg3_type, arg4_type, arg5_type, arg6_type, arg7_type, mt_policy >::m_pmemfun, and sigslot::_connection7< dest_type, arg1_type, arg2_type, arg3_type, arg4_type, arg5_type, arg6_type, arg7_type, mt_policy >::m_pobject.
Member Function Documentation
template<class dest_type , class arg1_type , class arg2_type , class arg3_type , class arg4_type , class arg5_type , class arg6_type , class arg7_type , class mt_policy > virtual _connection_base7<arg1_type, arg2_type, arg3_type, arg4_type, arg5_type, arg6_type, arg7_type, mt_policy>* sigslot::_connection7< dest_type, arg1_type, arg2_type, arg3_type, arg4_type, arg5_type, arg6_type, arg7_type, mt_policy >::clone () inline virtual
Implements sigslot::_connection_base7< arg1_type, arg2_type, arg3_type, arg4_type, arg5_type, arg6_type, arg7_type, mt_policy >.
Definition at line 1854 of file sigslot.h.
View newest version in sPHENIX GitHub at line 1854 of file sigslot.h
template<class dest_type , class arg1_type , class arg2_type , class arg3_type , class arg4_type , class arg5_type , class arg6_type , class arg7_type , class mt_policy > virtual _connection_base7<arg1_type, arg2_type, arg3_type, arg4_type, arg5_type, arg6_type, arg7_type, mt_policy>* sigslot::_connection7< dest_type, arg1_type, arg2_type, arg3_type, arg4_type, arg5_type, arg6_type, arg7_type, mt_policy >::duplicate (has_slots< mt_policy > * pnewdest) inline virtual
Implements sigslot::_connection_base7< arg1_type, arg2_type, arg3_type, arg4_type, arg5_type, arg6_type, arg7_type, mt_policy >.
Definition at line 1861 of file sigslot.h.
View newest version in sPHENIX GitHub at line 1861 of file sigslot.h
References sigslot::_connection7< dest_type, arg1_type, arg2_type, arg3_type, arg4_type, arg5_type, arg6_type, arg7_type, mt_policy >::m_pmemfun.
template<class dest_type , class arg1_type , class arg2_type , class arg3_type , class arg4_type , class arg5_type , class arg6_type , class arg7_type , class mt_policy > virtual void sigslot::_connection7< dest_type, arg1_type, arg2_type, arg3_type, arg4_type, arg5_type, arg6_type, arg7_type, mt_policy >::emit (arg1_type a1, arg2_type a2, arg3_type a3, arg4_type a4, arg5_type a5, arg6_type a6, arg7_type a7) inline virtual
Implements sigslot::_connection_base7< arg1_type, arg2_type, arg3_type, arg4_type, arg5_type, arg6_type, arg7_type, mt_policy >.
Definition at line 1867 of file sigslot.h.
View newest version in sPHENIX GitHub at line 1867 of file sigslot.h
References sigslot::_connection7< dest_type, arg1_type, arg2_type, arg3_type, arg4_type, arg5_type, arg6_type, arg7_type, mt_policy >::m_pmemfun, and sigslot::_connection7< dest_type, arg1_type, arg2_type, arg3_type, arg4_type, arg5_type, arg6_type, arg7_type, mt_policy >::m_pobject.
template<class dest_type , class arg1_type , class arg2_type , class arg3_type , class arg4_type , class arg5_type , class arg6_type , class arg7_type , class mt_policy > virtual has_slots<mt_policy>* sigslot::_connection7< dest_type, arg1_type, arg2_type, arg3_type, arg4_type, arg5_type, arg6_type, arg7_type, mt_policy >::getdest () const inline virtual
Implements sigslot::_connection_base7< arg1_type, arg2_type, arg3_type, arg4_type, arg5_type, arg6_type, arg7_type, mt_policy >.
Definition at line 1873 of file sigslot.h.
View newest version in sPHENIX GitHub at line 1873 of file sigslot.h
References sigslot::_connection7< dest_type, arg1_type, arg2_type, arg3_type, arg4_type, arg5_type, arg6_type, arg7_type, mt_policy >::m_pobject.
Member Data Documentation
template<class dest_type , class arg1_type , class arg2_type , class arg3_type , class arg4_type , class arg5_type , class arg6_type , class arg7_type , class mt_policy > void(dest_type::* sigslot::_connection7< dest_type, arg1_type, arg2_type, arg3_type, arg4_type, arg5_type, arg6_type, arg7_type, mt_policy >::m_pmemfun)(arg1_type, arg2_type, arg3_type, arg4_type, arg5_type, arg6_type, arg7_type) private
Definition at line 1880 of file sigslot.h.
View newest version in sPHENIX GitHub at line 1880 of file sigslot.h
Referenced by sigslot::_connection7< dest_type, arg1_type, arg2_type, arg3_type, arg4_type, arg5_type, arg6_type, arg7_type, mt_policy >::_connection7(), sigslot::_connection7< dest_type, arg1_type, arg2_type, arg3_type, arg4_type, arg5_type, arg6_type, arg7_type, mt_policy >::duplicate(), and sigslot::_connection7< dest_type, arg1_type, arg2_type, arg3_type, arg4_type, arg5_type, arg6_type, arg7_type, mt_policy >::emit().
template<class dest_type , class arg1_type , class arg2_type , class arg3_type , class arg4_type , class arg5_type , class arg6_type , class arg7_type , class mt_policy > dest_type* sigslot::_connection7< dest_type, arg1_type, arg2_type, arg3_type, arg4_type, arg5_type, arg6_type, arg7_type, mt_policy >::m_pobject private
Definition at line 1879 of file sigslot.h.
View newest version in sPHENIX GitHub at line 1879 of file sigslot.h
Referenced by sigslot::_connection7< dest_type, arg1_type, arg2_type, arg3_type, arg4_type, arg5_type, arg6_type, arg7_type, mt_policy >::_connection7(), sigslot::_connection7< dest_type, arg1_type, arg2_type, arg3_type, arg4_type, arg5_type, arg6_type, arg7_type, mt_policy >::emit(), and sigslot::_connection7< dest_type, arg1_type, arg2_type, arg3_type, arg4_type, arg5_type, arg6_type, arg7_type, mt_policy >::getdest().
The documentation for this class was generated from the following file:
JETSCAPE/blob/main/external_packages/sigslot.h