Analysis Software: PHActsGSF Class Reference
PHActsGSF Class Reference
#include <coresoftware/blob/master/offline/packages/trackreco/PHActsGSF.h>
Public Member Functions
PHActsGSF (const std::string &name="PHActsGSF")
~PHActsGSF () override
int InitRun (PHCompositeNode *topNode) override
int process_event (PHCompositeNode *topNode) override
int End (PHCompositeNode *topNode) override
Called at the end of all processing.
void set_pp_mode (bool mode)
Public Member Functions inherited from SubsysReco
~SubsysReco () override
virtual int EndRun (const int)
Called at the end of each run.
virtual int Init (PHCompositeNode *)
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
void Print (const std::string &="ALL") const override
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Private Member Functions
int getNodes (PHCompositeNode *topNode)
std::shared_ptr
< Acts::PerigeeSurface > makePerigee (SvtxTrack *track) const
ActsTrackFittingAlgorithm::TrackParameters makeSeed (SvtxTrack *track, std::shared_ptr< Acts::PerigeeSurface > psurf) const
ActsTrackFittingAlgorithm::TrackFitterResult fitTrack (const std::vector< Acts::SourceLink > &sourceLinks, const ActsTrackFittingAlgorithm::TrackParameters &seed, const ActsTrackFittingAlgorithm::GeneralFitterOptions &options, const CalibratorAdapter &calibrator, ActsTrackFittingAlgorithm::TrackContainer &tracks)
void updateTrack (FitResult &result, SvtxTrack *track, ActsTrackFittingAlgorithm::TrackContainer &tracks)
void updateSvtxTrack (std::vector< Acts::MultiTrajectoryTraits::IndexType > &tips, Trajectory::IndexedParameters &paramsMap, ActsTrackFittingAlgorithm::TrackContainer &tracks, SvtxTrack *track)
Private Attributes
ActsGeometry * m_tGeometry = nullptr
TrkrClusterContainer * m_clusterContainer = nullptr
SvtxTrackMap * m_trackMap = nullptr
SvtxVertexMap * m_vertexMap = nullptr
TpcClusterZCrossingCorrection m_clusterCrossingCorrection
alignmentTransformationContainer * m_alignmentTransformationMap = nullptr
alignmentTransformationContainer * m_alignmentTransformationMapTransient = nullptr
std::set
< Acts::GeometryIdentifier > m_transient_id_set
Acts::GeometryContext m_transient_geocontext
TpcDistortionCorrectionContainer * m_dccStatic = nullptr
TpcDistortionCorrectionContainer * m_dccAverage = nullptr
TpcDistortionCorrectionContainer * m_dccFluctuation {nullptr}
TpcDistortionCorrection m_distortionCorrection
std::string m_trackMapName = "SvtxTrackMap"
unsigned int m_pHypothesis = 11
bool m_pp_mode = false
ClusterErrorPara _ClusErrPara
ActsTrackFittingAlgorithm::Config m_fitCfg
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = std::numeric_limits<int>::max() - 10
}
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Detailed Description
Definition at line 45 of file PHActsGSF.h.
View newest version in sPHENIX GitHub at line 45 of file PHActsGSF.h
Constructor & Destructor Documentation
PHActsGSF::PHActsGSF (const std::string & name = "PHActsGSF")
Definition at line 43 of file PHActsGSF.cc.
View newest version in sPHENIX GitHub at line 43 of file PHActsGSF.cc
PHActsGSF::~PHActsGSF () override
Definition at line 49 of file PHActsGSF.cc.
View newest version in sPHENIX GitHub at line 49 of file PHActsGSF.cc
Member Function Documentation
int PHActsGSF::End (PHCompositeNode *) override virtual
Called at the end of all processing.
Reimplemented from SubsysReco.
Definition at line 325 of file PHActsGSF.cc.
View newest version in sPHENIX GitHub at line 325 of file PHActsGSF.cc
References Fun4AllReturnCodes::EVENT_OK.
ActsTrackFittingAlgorithm::TrackFitterResult PHActsGSF::fitTrack (const std::vector< Acts::SourceLink > & sourceLinks, const ActsTrackFittingAlgorithm::TrackParameters & seed, const ActsTrackFittingAlgorithm::GeneralFitterOptions & options, const CalibratorAdapter & calibrator, ActsTrackFittingAlgorithm::TrackContainer & tracks) private
Definition at line 231 of file PHActsGSF.cc.
View newest version in sPHENIX GitHub at line 231 of file PHActsGSF.cc
References ActsTrackFittingAlgorithm::Config::fit, m_fitCfg, ckf::options, seed, and tracks().
Referenced by process_event().
int PHActsGSF::getNodes (PHCompositeNode * topNode) private
Definition at line 330 of file PHActsGSF.cc.
View newest version in sPHENIX GitHub at line 330 of file PHActsGSF.cc
References Fun4AllReturnCodes::ABORTEVENT, Fun4AllReturnCodes::EVENT_OK, m_alignmentTransformationMapTransient, m_clusterContainer, m_dccAverage, m_dccFluctuation, m_dccStatic, m_tGeometry, m_trackMap, m_trackMapName, m_vertexMap, and PHWHERE.
Referenced by InitRun().
int PHActsGSF::InitRun (PHCompositeNode *) override virtual
Called for first event when run number is known. Typically this is where you may want to fetch data from database, because you know the run number.
Reimplemented from SubsysReco.
Definition at line 54 of file PHActsGSF.cc.
View newest version in sPHENIX GitHub at line 54 of file PHActsGSF.cc
References Fun4AllReturnCodes::ABORTEVENT, Acts::UnitConstants::e, Fun4AllReturnCodes::EVENT_OK, ActsTrackFittingAlgorithm::Config::fit, ActsGeometry::geometry(), getNodes(), m_fitCfg, m_tGeometry, ActsTrackingGeometry::magField, Acts::makeDefaultBetheHeitlerApprox(), ActsGsfTrackFittingAlgorithm::makeGsfFitterFunction(), ActsTrackingGeometry::tGeometry, and Fun4AllBase::Verbosity().
std::shared_ptr< Acts::PerigeeSurface > PHActsGSF::makePerigee (SvtxTrack * track) const private
Definition at line 188 of file PHActsGSF.cc.
View newest version in sPHENIX GitHub at line 188 of file PHActsGSF.cc
References Acts::UnitConstants::cm, SvtxVertexMap::get(), SvtxTrack::get_vertex_id(), SvtxVertex::get_x(), SvtxVertex::get_y(), SvtxVertex::get_z(), and m_vertexMap.
Referenced by process_event().
ActsTrackFittingAlgorithm::TrackParameters PHActsGSF::makeSeed (SvtxTrack * track, std::shared_ptr< Acts::PerigeeSurface > psurf) const private
Definition at line 204 of file PHActsGSF.cc.
View newest version in sPHENIX GitHub at line 204 of file PHActsGSF.cc
References charge(), Acts::UnitConstants::cm, Acts::Test::cov, Acts::GenericBoundTrackParameters< particle_hypothesis_t >::create(), Acts::ParticleHypothesis::electron(), ActsGeometry::geometry(), SvtxTrack::get_charge(), SvtxTrack::get_px(), SvtxTrack::get_py(), SvtxTrack::get_pz(), SvtxTrack::get_x(), SvtxTrack::get_y(), SvtxTrack::get_z(), ActsTrackingGeometry::getGeoContext(), m_tGeometry, momentum, Acts::UnitConstants::ns, and value.
Referenced by process_event().
int PHActsGSF::process_event (PHCompositeNode *) override virtual
Called for each event. This is where you do the real work.
If no vertex was assigned to track, just skip it
We only fit full sPHENIX tracks
Reimplemented from SubsysReco.
Definition at line 78 of file PHActsGSF.cc.
View newest version in sPHENIX GitHub at line 78 of file PHActsGSF.cc
References ActsTrackingGeometry::calibContext, Fun4AllReturnCodes::EVENT_OK, Acts::Logging::FATAL, fitTrack(), ActsGeometry::geometry(), TrackSeed::get_crossing(), Acts::getDefaultLogger(), MakeSourceLinks::getSourceLinks(), logger(), telescope_simulation::logLevel, m_alignmentTransformationMapTransient, m_clusterContainer, m_pp_mode, m_tGeometry, m_trackMap, m_transient_geocontext, m_transient_id_set, ActsTrackingGeometry::magFieldContext, makePerigee(), makeSeed(), ckf::options, pSurface, MakeSourceLinks::resetTransientTransformMap(), seed, MakeSourceLinks::set_pp_mode(), MakeSourceLinks::setVerbosity(), tracks(), updateTrack(), Acts::Logging::VERBOSE, and Fun4AllBase::Verbosity().
void PHActsGSF::set_pp_mode (bool mode) inline
Definition at line 56 of file PHActsGSF.h.
View newest version in sPHENIX GitHub at line 56 of file PHActsGSF.h
References m_pp_mode, and CKF_timing_vs_mu::mode.
void PHActsGSF::updateSvtxTrack (std::vector< Acts::MultiTrajectoryTraits::IndexType > & tips, Trajectory::IndexedParameters & paramsMap, ActsTrackFittingAlgorithm::TrackContainer & tracks, SvtxTrack * track) private
Will create new states
Definition at line 257 of file PHActsGSF.cc.
View newest version in sPHENIX GitHub at line 257 of file PHActsGSF.cc
References SvtxTrack::clear_states(), Acts::UnitConstants::cm, ActsTransformations::fillSvtxTrackStates(), SvtxTrack::get_px(), SvtxTrack::get_py(), SvtxTrack::get_pz(), SvtxTrack::get_x(), SvtxTrack::get_y(), SvtxTrack::get_z(), i, SvtxTrack::insert_state(), j, m_transient_geocontext, out, ActsTransformations::rotateActsCovToSvtxTrack(), SvtxTrack::set_charge(), SvtxTrack::set_chisq(), SvtxTrack::set_error(), SvtxTrack::set_ndf(), SvtxTrack::set_px(), SvtxTrack::set_py(), SvtxTrack::set_pz(), SvtxTrackState_v1::set_x(), SvtxTrack::set_x(), SvtxTrackState_v1::set_y(), SvtxTrack::set_y(), SvtxTrackState_v1::set_z(), SvtxTrack::set_z(), ActsTransformations::setVerbosity(), Acts::MultiTrajectoryHelpers::trajectoryState(), and Fun4AllBase::Verbosity().
Referenced by updateTrack().
void PHActsGSF::updateTrack (FitResult & result, SvtxTrack * track, ActsTrackFittingAlgorithm::TrackContainer & tracks) private
Definition at line 241 of file PHActsGSF.cc.
View newest version in sPHENIX GitHub at line 241 of file PHActsGSF.cc
References Acts::ParticleHypothesis::electron(), Acts::Surface::getSharedPtr(), Acts::GenericBoundTrackParameters< particle_hypothesis_t >::referenceSurface(), and updateSvtxTrack().
Referenced by process_event().
Member Data Documentation
ClusterErrorPara PHActsGSF::_ClusErrPara private
Definition at line 101 of file PHActsGSF.h.
View newest version in sPHENIX GitHub at line 101 of file PHActsGSF.h
alignmentTransformationContainer* PHActsGSF::m_alignmentTransformationMap = nullptr private
Definition at line 86 of file PHActsGSF.h.
View newest version in sPHENIX GitHub at line 86 of file PHActsGSF.h
alignmentTransformationContainer* PHActsGSF::m_alignmentTransformationMapTransient = nullptr private
Definition at line 87 of file PHActsGSF.h.
View newest version in sPHENIX GitHub at line 87 of file PHActsGSF.h
Referenced by getNodes(), and process_event().
TrkrClusterContainer* PHActsGSF::m_clusterContainer = nullptr private
Definition at line 81 of file PHActsGSF.h.
View newest version in sPHENIX GitHub at line 81 of file PHActsGSF.h
Referenced by getNodes(), and process_event().
TpcClusterZCrossingCorrection PHActsGSF::m_clusterCrossingCorrection private
Definition at line 84 of file PHActsGSF.h.
View newest version in sPHENIX GitHub at line 84 of file PHActsGSF.h
TpcDistortionCorrectionContainer* PHActsGSF::m_dccAverage = nullptr private
Definition at line 92 of file PHActsGSF.h.
View newest version in sPHENIX GitHub at line 92 of file PHActsGSF.h
Referenced by getNodes().
TpcDistortionCorrectionContainer* PHActsGSF::m_dccFluctuation {nullptr} private
Definition at line 93 of file PHActsGSF.h.
View newest version in sPHENIX GitHub at line 93 of file PHActsGSF.h
Referenced by getNodes().
TpcDistortionCorrectionContainer* PHActsGSF::m_dccStatic = nullptr private
Definition at line 91 of file PHActsGSF.h.
View newest version in sPHENIX GitHub at line 91 of file PHActsGSF.h
Referenced by getNodes().
TpcDistortionCorrection PHActsGSF::m_distortionCorrection private
Definition at line 94 of file PHActsGSF.h.
View newest version in sPHENIX GitHub at line 94 of file PHActsGSF.h
ActsTrackFittingAlgorithm::Config PHActsGSF::m_fitCfg private
Definition at line 103 of file PHActsGSF.h.
View newest version in sPHENIX GitHub at line 103 of file PHActsGSF.h
Referenced by fitTrack(), and InitRun().
unsigned int PHActsGSF::m_pHypothesis = 11 private
Definition at line 97 of file PHActsGSF.h.
View newest version in sPHENIX GitHub at line 97 of file PHActsGSF.h
bool PHActsGSF::m_pp_mode = false private
Definition at line 99 of file PHActsGSF.h.
View newest version in sPHENIX GitHub at line 99 of file PHActsGSF.h
Referenced by process_event(), and set_pp_mode().
ActsGeometry* PHActsGSF::m_tGeometry = nullptr private
Definition at line 80 of file PHActsGSF.h.
View newest version in sPHENIX GitHub at line 80 of file PHActsGSF.h
Referenced by getNodes(), InitRun(), makeSeed(), and process_event().
SvtxTrackMap* PHActsGSF::m_trackMap = nullptr private
Definition at line 82 of file PHActsGSF.h.
View newest version in sPHENIX GitHub at line 82 of file PHActsGSF.h
Referenced by getNodes(), and process_event().
std::string PHActsGSF::m_trackMapName = "SvtxTrackMap" private
Definition at line 96 of file PHActsGSF.h.
View newest version in sPHENIX GitHub at line 96 of file PHActsGSF.h
Referenced by getNodes().
Acts::GeometryContext PHActsGSF::m_transient_geocontext private
Definition at line 89 of file PHActsGSF.h.
View newest version in sPHENIX GitHub at line 89 of file PHActsGSF.h
Referenced by process_event(), and updateSvtxTrack().
std::set< Acts::GeometryIdentifier> PHActsGSF::m_transient_id_set private
Definition at line 88 of file PHActsGSF.h.
View newest version in sPHENIX GitHub at line 88 of file PHActsGSF.h
Referenced by process_event().
SvtxVertexMap* PHActsGSF::m_vertexMap = nullptr private
Definition at line 83 of file PHActsGSF.h.
View newest version in sPHENIX GitHub at line 83 of file PHActsGSF.h
Referenced by getNodes(), and makePerigee().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/trackreco/PHActsGSF.h
coresoftware/blob/master/offline/packages/trackreco/PHActsGSF.cc