Analysis Software: sPHElectronPairContainerv1 Class Reference
sPHElectronPairContainerv1 Class Reference
#include <analysis/blob/master/EventMix/src/sPHElectronPairContainerv1.h>
Public Types
typedef std::map< unsigned int,
sPHElectronPairv1 * > PairMap
typedef std::map< unsigned int,
sPHElectronPairv1 * >
::const_iterator ConstIter
typedef std::map< unsigned int,
sPHElectronPairv1 * >
::iterator Iter
Public Member Functions
sPHElectronPairContainerv1 ()
sPHElectronPairContainerv1 (const sPHElectronPairContainerv1 &container)
sPHElectronPairContainerv1 & operator= (const sPHElectronPairContainerv1 &container)
virtual ~sPHElectronPairContainerv1 ()
void identify (std::ostream &os=std::cout) const
void Reset ()
Clear Event.
void clear ()
int isValid () const
isValid returns non zero if object contains vailid data
size_t size () const
bool empty () const
PHObject * CloneMe () const
Virtual copy constructor.
const sPHElectronPairv1 * get (unsigned int idkey) const
sPHElectronPairv1 * get (unsigned int idkey)
void insert (const sPHElectronPairv1 *pair)
size_t erase (unsigned int idkey)
ConstIter begin () const
ConstIter find (unsigned int idkey) const
ConstIter end () const
Iter begin ()
Iter find (unsigned int idkey)
Iter end ()
Public Member Functions inherited from sPHElectronPairContainer
virtual ~sPHElectronPairContainer ()
Public Member Functions inherited from PHObject
PHObject ()
ctor
~PHObject () override
dtor
virtual PHObject * clone () const final
PHObject * Clone (const char *newname="") const final
void Copy (TObject &object) const final
virtual int Integrate () const
virtual int Integrate (PHObject *)
virtual void CopyFrom (const PHObject *obj)
Protected Member Functions
ClassDef (sPHElectronPairContainerv1, 1)
Protected Member Functions inherited from sPHElectronPairContainer
sPHElectronPairContainer ()
ClassDef (sPHElectronPairContainer, 1)
Protected Attributes
PairMap _map
Detailed Description
Definition at line 11 of file sPHElectronPairContainerv1.h.
View newest version in sPHENIX GitHub at line 11 of file sPHElectronPairContainerv1.h
Member Typedef Documentation
typedef std::map<unsigned int, sPHElectronPairv1*>::const_iterator sPHElectronPairContainerv1::ConstIter
Definition at line 16 of file sPHElectronPairContainerv1.h.
View newest version in sPHENIX GitHub at line 16 of file sPHElectronPairContainerv1.h
typedef std::map<unsigned int, sPHElectronPairv1*>::iterator sPHElectronPairContainerv1::Iter
Definition at line 17 of file sPHElectronPairContainerv1.h.
View newest version in sPHENIX GitHub at line 17 of file sPHElectronPairContainerv1.h
typedef std::map<unsigned int, sPHElectronPairv1*> sPHElectronPairContainerv1::PairMap
Definition at line 15 of file sPHElectronPairContainerv1.h.
View newest version in sPHENIX GitHub at line 15 of file sPHElectronPairContainerv1.h
Constructor & Destructor Documentation
sPHElectronPairContainerv1::sPHElectronPairContainerv1 ()
Definition at line 11 of file sPHElectronPairContainerv1.cc.
View newest version in sPHENIX GitHub at line 11 of file sPHElectronPairContainerv1.cc
Referenced by CloneMe().
sPHElectronPairContainerv1::sPHElectronPairContainerv1 (const sPHElectronPairContainerv1 & container)
Definition at line 16 of file sPHElectronPairContainerv1.cc.
View newest version in sPHENIX GitHub at line 16 of file sPHElectronPairContainerv1.cc
References _map, begin(), end(), and sPHElectronPairv1::get_id().
sPHElectronPairContainerv1::~sPHElectronPairContainerv1 () virtual
Definition at line 41 of file sPHElectronPairContainerv1.cc.
View newest version in sPHENIX GitHub at line 41 of file sPHElectronPairContainerv1.cc
References Reset().
Member Function Documentation
ConstIter sPHElectronPairContainerv1::begin (void) const inline
Definition at line 42 of file sPHElectronPairContainerv1.h.
View newest version in sPHENIX GitHub at line 42 of file sPHElectronPairContainerv1.h
References _map.
Referenced by operator=(), sPHAnalysis::process_event_pairs(), and sPHElectronPairContainerv1().
Iter sPHElectronPairContainerv1::begin (void) inline
Definition at line 46 of file sPHElectronPairContainerv1.h.
View newest version in sPHENIX GitHub at line 46 of file sPHElectronPairContainerv1.h
References _map.
sPHElectronPairContainerv1::ClassDef (sPHElectronPairContainerv1 , 1) protected
void sPHElectronPairContainerv1::clear () inline virtual
Reimplemented from sPHElectronPairContainer.
Definition at line 27 of file sPHElectronPairContainerv1.h.
View newest version in sPHENIX GitHub at line 27 of file sPHElectronPairContainerv1.h
References Reset().
PHObject* sPHElectronPairContainerv1::CloneMe () const inline virtual
Virtual copy constructor.
Reimplemented from sPHElectronPairContainer.
Definition at line 31 of file sPHElectronPairContainerv1.h.
View newest version in sPHENIX GitHub at line 31 of file sPHElectronPairContainerv1.h
References sPHElectronPairContainerv1().
bool sPHElectronPairContainerv1::empty () const inline virtual
Reimplemented from sPHElectronPairContainer.
Definition at line 30 of file sPHElectronPairContainerv1.h.
View newest version in sPHENIX GitHub at line 30 of file sPHElectronPairContainerv1.h
References _map.
ConstIter sPHElectronPairContainerv1::end (void) const inline
Definition at line 44 of file sPHElectronPairContainerv1.h.
View newest version in sPHENIX GitHub at line 44 of file sPHElectronPairContainerv1.h
References _map.
Referenced by operator=(), sPHAnalysis::process_event_pairs(), and sPHElectronPairContainerv1().
Iter sPHElectronPairContainerv1::end (void) inline
Definition at line 48 of file sPHElectronPairContainerv1.h.
View newest version in sPHENIX GitHub at line 48 of file sPHElectronPairContainerv1.h
References _map.
size_t sPHElectronPairContainerv1::erase (unsigned int idkey) inline
Definition at line 36 of file sPHElectronPairContainerv1.h.
View newest version in sPHENIX GitHub at line 36 of file sPHElectronPairContainerv1.h
References _map.
ConstIter sPHElectronPairContainerv1::find (unsigned int idkey) const inline
Definition at line 43 of file sPHElectronPairContainerv1.h.
View newest version in sPHENIX GitHub at line 43 of file sPHElectronPairContainerv1.h
References _map.
Iter sPHElectronPairContainerv1::find (unsigned int idkey) inline
Definition at line 47 of file sPHElectronPairContainerv1.h.
View newest version in sPHENIX GitHub at line 47 of file sPHElectronPairContainerv1.h
References _map.
const sPHElectronPairv1 * sPHElectronPairContainerv1::get (unsigned int idkey) const
Definition at line 64 of file sPHElectronPairContainerv1.cc.
View newest version in sPHENIX GitHub at line 64 of file sPHElectronPairContainerv1.cc
References _map.
sPHElectronPairv1 * sPHElectronPairContainerv1::get (unsigned int idkey)
Definition at line 71 of file sPHElectronPairContainerv1.cc.
View newest version in sPHENIX GitHub at line 71 of file sPHElectronPairContainerv1.cc
References _map.
void sPHElectronPairContainerv1::identify (std::ostream & os = std::cout) const virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from sPHElectronPairContainer.
Definition at line 58 of file sPHElectronPairContainerv1.cc.
View newest version in sPHENIX GitHub at line 58 of file sPHElectronPairContainerv1.cc
References _map.
void sPHElectronPairContainerv1::insert (const sPHElectronPairv1 * pair)
Definition at line 78 of file sPHElectronPairContainerv1.cc.
View newest version in sPHENIX GitHub at line 78 of file sPHElectronPairContainerv1.cc
References _map, sPHElectronPairv1::CloneMe(), and index.
Referenced by PairMaker::MakeMixedPairs(), and PairMaker::process_event_test().
int sPHElectronPairContainerv1::isValid () const inline virtual
isValid returns non zero if object contains vailid data
Reimplemented from sPHElectronPairContainer.
Definition at line 28 of file sPHElectronPairContainerv1.h.
View newest version in sPHENIX GitHub at line 28 of file sPHElectronPairContainerv1.h
sPHElectronPairContainerv1 & sPHElectronPairContainerv1::operator= (const sPHElectronPairContainerv1 & container)
Definition at line 28 of file sPHElectronPairContainerv1.cc.
View newest version in sPHENIX GitHub at line 28 of file sPHElectronPairContainerv1.cc
References _map, begin(), end(), sPHElectronPairv1::get_id(), and Reset().
void sPHElectronPairContainerv1::Reset () virtual
Clear Event.
Reimplemented from sPHElectronPairContainer.
Definition at line 46 of file sPHElectronPairContainerv1.cc.
View newest version in sPHENIX GitHub at line 46 of file sPHElectronPairContainerv1.cc
References _map.
Referenced by clear(), operator=(), and ~sPHElectronPairContainerv1().
size_t sPHElectronPairContainerv1::size (void) const inline virtual
Reimplemented from sPHElectronPairContainer.
Definition at line 29 of file sPHElectronPairContainerv1.h.
View newest version in sPHENIX GitHub at line 29 of file sPHElectronPairContainerv1.h
References _map.
Referenced by sPHAnalysis::process_event_pairs().
Member Data Documentation
PairMap sPHElectronPairContainerv1::_map protected
Definition at line 51 of file sPHElectronPairContainerv1.h.
View newest version in sPHENIX GitHub at line 51 of file sPHElectronPairContainerv1.h
Referenced by begin(), empty(), end(), erase(), find(), get(), identify(), insert(), operator=(), Reset(), size(), and sPHElectronPairContainerv1().
The documentation for this class was generated from the following files:
analysis/blob/master/EventMix/src/sPHElectronPairContainerv1.h
analysis/blob/master/EventMix/src/sPHElectronPairContainerv1.cc