Analysis Software: analysis/blob/master/pythiaInfo/macro/Fun4AllPythia.C File Reference
Fun4AllPythia.C File Reference
#include <fun4all/Fun4AllDstOutputManager.h>
#include <fun4all/Fun4AllOutputManager.h>
#include <fun4all/Fun4AllServer.h>
#include <fun4all/Fun4AllSyncManager.h>
#include <fun4all/Fun4AllUtils.h>
#include <phool/PHRandomSeed.h>
#include <phool/recoConsts.h>
#include <stdlib.h>
#include <g4main/PHG4Reco.h>
#include <g4main/PHG4TruthSubsystem.h>
#include <GlobalVariables.C>
#include <G4_Input.C>
#include <phpythia8/PHPy8JetTrigger.h>
#include <jethistogrammer/jetHistogrammer.h>
#include <g4jets/FastJetAlgo.h>
#include <g4jets/JetReco.h>
#include <g4jets/TruthJetInput.h>
#include <time.h>
Functions
void Fun4AllPythia (int nEvents=1, const string &Jet_Trigger="Jet10", int doCrossSection=1, const string &outname="out")
Function Documentation
void Fun4AllPythia (int nEvents = 1, const string & Jet_Trigger = "Jet10", int doCrossSection = 1, const string & outname = "out")
Definition at line 30 of file Fun4AllPythia.C.
View newest version in sPHENIX GitHub at line 30 of file Fun4AllPythia.C
References JetReco::add_algo(), Jet::ANTIKT, Input::ApplysPHENIXBeamParameter(), PYTHIA8::config_file, double(), InputInit(), InputManagers(), InputRegister(), Fun4AllServer::instance(), Jet::PARTICLE, Input::PYTHIA8, INPUTGENERATOR::Pythia8, PHPythia8::register_trigger(), utils::run, JetReco::set_algo_node(), JetReco::set_input_node(), PHPythia8::set_trigger_AND(), PHPy8JetTrigger::SetEtaHighLow(), PHPy8JetTrigger::SetJetR(), PHPy8JetTrigger::SetMinJetPt(), PHPy8GenTrigger::Verbosity(), Fun4AllBase::Verbosity(), Input::VERBOSITY, and Verbosity().