Analysis Software: Acts::detail::ScopedGsfInfoPrinterAndChecker< propagator_state_t, stepper_t, navigator_t > Class Template Reference
Acts::detail::ScopedGsfInfoPrinterAndChecker< propagator_state_t, stepper_t, navigator_t > Class Template Reference
#include <acts/blob/sPHENIX/Core/include/Acts/TrackFitting/detail/GsfUtils.hpp>
Public Member Functions
ScopedGsfInfoPrinterAndChecker (const propagator_state_t &state, const stepper_t &stepper, const navigator_t &navigator, const Logger &logger)
ACTS_VERBOSE ("Gsf step "<< state.stepping.steps<< " at mean position "<< stepper.position(state.stepping).transpose()<< " with direction "<< stepper.direction(state.stepping).transpose()<< " and momentum "<< stepper.absoluteMomentum(state.stepping)<< " and charge "<< stepper.charge(state.stepping))
ACTS_VERBOSE ("Propagation is in "<< state.options.direction<< " mode")
print_component_stats ()
~ScopedGsfInfoPrinterAndChecker ()
Private Member Functions
const Logger & logger () const
void print_component_stats () const
void checks (bool onStart) const
Private Attributes
const propagator_state_t & m_state
const stepper_t & m_stepper
const navigator_t & m_navigator
double m_p_initial
const Logger & m_logger
Detailed Description
template<typename propagator_state_t, typename stepper_t, typename navigator_t>
class Acts::detail::ScopedGsfInfoPrinterAndChecker< propagator_state_t, stepper_t, navigator_t >
Definition at line 74 of file GsfUtils.hpp.
View newest version in sPHENIX GitHub at line 74 of file GsfUtils.hpp
Constructor & Destructor Documentation
template<typename propagator_state_t , typename stepper_t , typename navigator_t > Acts::detail::ScopedGsfInfoPrinterAndChecker< propagator_state_t, stepper_t, navigator_t >::ScopedGsfInfoPrinterAndChecker (const propagator_state_t & state, const stepper_t & stepper, const navigator_t & navigator, const Logger & logger) inline
Definition at line 119 of file GsfUtils.hpp.
View newest version in sPHENIX GitHub at line 119 of file GsfUtils.hpp
template<typename propagator_state_t , typename stepper_t , typename navigator_t > Acts::detail::ScopedGsfInfoPrinterAndChecker< propagator_state_t, stepper_t, navigator_t >::~ScopedGsfInfoPrinterAndChecker () inline
Definition at line 141 of file GsfUtils.hpp.
View newest version in sPHENIX GitHub at line 141 of file GsfUtils.hpp
References Acts::detail::ScopedGsfInfoPrinterAndChecker< propagator_state_t, stepper_t, navigator_t >::ACTS_VERBOSE(), Acts::detail::ScopedGsfInfoPrinterAndChecker< propagator_state_t, stepper_t, navigator_t >::checks(), Acts::detail::ScopedGsfInfoPrinterAndChecker< propagator_state_t, stepper_t, navigator_t >::m_navigator, Acts::detail::ScopedGsfInfoPrinterAndChecker< propagator_state_t, stepper_t, navigator_t >::m_p_initial, Acts::detail::ScopedGsfInfoPrinterAndChecker< propagator_state_t, stepper_t, navigator_t >::m_state, Acts::detail::ScopedGsfInfoPrinterAndChecker< propagator_state_t, stepper_t, navigator_t >::m_stepper, and Acts::detail::ScopedGsfInfoPrinterAndChecker< propagator_state_t, stepper_t, navigator_t >::print_component_stats().
Member Function Documentation
template<typename propagator_state_t , typename stepper_t , typename navigator_t > Acts::detail::ScopedGsfInfoPrinterAndChecker< propagator_state_t, stepper_t, navigator_t >::ACTS_VERBOSE ("Gsf step "<< state.stepping.steps<< " at mean position "<< stepper. positionstate.stepping).transpose()<< " with direction "<< stepper.direction(state.stepping).transpose()<< " and momentum "<< stepper.absoluteMomentum(state.stepping)<< " and charge "<< stepper.charge(state.stepping)
Referenced by Acts::detail::ScopedGsfInfoPrinterAndChecker< propagator_state_t, stepper_t, navigator_t >::print_component_stats(), and Acts::detail::ScopedGsfInfoPrinterAndChecker< propagator_state_t, stepper_t, navigator_t >::~ScopedGsfInfoPrinterAndChecker().
template<typename propagator_state_t , typename stepper_t , typename navigator_t > Acts::detail::ScopedGsfInfoPrinterAndChecker< propagator_state_t, stepper_t, navigator_t >::ACTS_VERBOSE ("Propagation is in "<< state.options.direction<< " mode")
template<typename propagator_state_t , typename stepper_t , typename navigator_t > void Acts::detail::ScopedGsfInfoPrinterAndChecker< propagator_state_t, stepper_t, navigator_t >::checks (bool onStart) const inline private
Definition at line 97 of file GsfUtils.hpp.
View newest version in sPHENIX GitHub at line 97 of file GsfUtils.hpp
References assert, root_event_diff_np::cmp(), Acts::detail::ScopedGsfInfoPrinterAndChecker< propagator_state_t, stepper_t, navigator_t >::m_state, Acts::detail::ScopedGsfInfoPrinterAndChecker< propagator_state_t, stepper_t, navigator_t >::m_stepper, and Acts::detail::weightsAreNormalized().
Referenced by Acts::detail::ScopedGsfInfoPrinterAndChecker< propagator_state_t, stepper_t, navigator_t >::~ScopedGsfInfoPrinterAndChecker().
template<typename propagator_state_t , typename stepper_t , typename navigator_t > const Logger& Acts::detail::ScopedGsfInfoPrinterAndChecker< propagator_state_t, stepper_t, navigator_t >::logger () const inline private
Definition at line 81 of file GsfUtils.hpp.
View newest version in sPHENIX GitHub at line 81 of file GsfUtils.hpp
References Acts::detail::ScopedGsfInfoPrinterAndChecker< propagator_state_t, stepper_t, navigator_t >::m_logger.
template<typename propagator_state_t , typename stepper_t , typename navigator_t > void Acts::detail::ScopedGsfInfoPrinterAndChecker< propagator_state_t, stepper_t, navigator_t >::print_component_stats () const inline private
Definition at line 83 of file GsfUtils.hpp.
View newest version in sPHENIX GitHub at line 83 of file GsfUtils.hpp
References Acts::detail::ScopedGsfInfoPrinterAndChecker< propagator_state_t, stepper_t, navigator_t >::ACTS_VERBOSE(), root_event_diff_np::cmp(), Acts::eFreeDir0, Acts::eFreePos0, Acts::eFreeQOverP, i, ambiguity_solver_full_chain::idx, Acts::detail::ScopedGsfInfoPrinterAndChecker< propagator_state_t, stepper_t, navigator_t >::m_state, and Acts::detail::ScopedGsfInfoPrinterAndChecker< propagator_state_t, stepper_t, navigator_t >::m_stepper.
Referenced by Acts::detail::ScopedGsfInfoPrinterAndChecker< propagator_state_t, stepper_t, navigator_t >::~ScopedGsfInfoPrinterAndChecker().
template<typename propagator_state_t , typename stepper_t , typename navigator_t > Acts::detail::ScopedGsfInfoPrinterAndChecker< propagator_state_t, stepper_t, navigator_t >::print_component_stats ()
Member Data Documentation
template<typename propagator_state_t , typename stepper_t , typename navigator_t > const Logger& Acts::detail::ScopedGsfInfoPrinterAndChecker< propagator_state_t, stepper_t, navigator_t >::m_logger private
Definition at line 79 of file GsfUtils.hpp.
View newest version in sPHENIX GitHub at line 79 of file GsfUtils.hpp
Referenced by Acts::detail::ScopedGsfInfoPrinterAndChecker< propagator_state_t, stepper_t, navigator_t >::logger().
template<typename propagator_state_t , typename stepper_t , typename navigator_t > const navigator_t& Acts::detail::ScopedGsfInfoPrinterAndChecker< propagator_state_t, stepper_t, navigator_t >::m_navigator private
Definition at line 77 of file GsfUtils.hpp.
View newest version in sPHENIX GitHub at line 77 of file GsfUtils.hpp
Referenced by Acts::detail::ScopedGsfInfoPrinterAndChecker< propagator_state_t, stepper_t, navigator_t >::~ScopedGsfInfoPrinterAndChecker().
template<typename propagator_state_t , typename stepper_t , typename navigator_t > double Acts::detail::ScopedGsfInfoPrinterAndChecker< propagator_state_t, stepper_t, navigator_t >::m_p_initial private
Definition at line 78 of file GsfUtils.hpp.
View newest version in sPHENIX GitHub at line 78 of file GsfUtils.hpp
Referenced by Acts::detail::ScopedGsfInfoPrinterAndChecker< propagator_state_t, stepper_t, navigator_t >::~ScopedGsfInfoPrinterAndChecker().
template<typename propagator_state_t , typename stepper_t , typename navigator_t > const propagator_state_t& Acts::detail::ScopedGsfInfoPrinterAndChecker< propagator_state_t, stepper_t, navigator_t >::m_state private
Definition at line 75 of file GsfUtils.hpp.
View newest version in sPHENIX GitHub at line 75 of file GsfUtils.hpp
Referenced by Acts::detail::ScopedGsfInfoPrinterAndChecker< propagator_state_t, stepper_t, navigator_t >::checks(), Acts::detail::ScopedGsfInfoPrinterAndChecker< propagator_state_t, stepper_t, navigator_t >::print_component_stats(), and Acts::detail::ScopedGsfInfoPrinterAndChecker< propagator_state_t, stepper_t, navigator_t >::~ScopedGsfInfoPrinterAndChecker().
template<typename propagator_state_t , typename stepper_t , typename navigator_t > const stepper_t& Acts::detail::ScopedGsfInfoPrinterAndChecker< propagator_state_t, stepper_t, navigator_t >::m_stepper private
Definition at line 76 of file GsfUtils.hpp.
View newest version in sPHENIX GitHub at line 76 of file GsfUtils.hpp
Referenced by Acts::detail::ScopedGsfInfoPrinterAndChecker< propagator_state_t, stepper_t, navigator_t >::checks(), Acts::detail::ScopedGsfInfoPrinterAndChecker< propagator_state_t, stepper_t, navigator_t >::print_component_stats(), and Acts::detail::ScopedGsfInfoPrinterAndChecker< propagator_state_t, stepper_t, navigator_t >::~ScopedGsfInfoPrinterAndChecker().
The documentation for this class was generated from the following file:
acts/blob/sPHENIX/Core/include/Acts/TrackFitting/detail/GsfUtils.hpp