Analysis Software: acts/blob/sPHENIX/Tests/UnitTests/Plugins/EDM4hep/ConvertTrackEDM4hepTest.cpp File Reference
ConvertTrackEDM4hepTest.cpp File Reference
#include <boost/test/data/test_case.hpp>
#include <boost/test/tools/old/interface.hpp>
#include <boost/test/unit_test.hpp>
#include <boost/test/unit_test_suite.hpp>
#include "Acts/Definitions/TrackParametrization.hpp"
#include "Acts/EventData/Charge.hpp"
#include "Acts/EventData/GenericBoundTrackParameters.hpp"
#include "Acts/EventData/MultiTrajectory.hpp"
#include "Acts/EventData/TrackHelpers.hpp"
#include "Acts/EventData/TrackStatePropMask.hpp"
#include "Acts/EventData/VectorMultiTrajectory.hpp"
#include "Acts/EventData/VectorTrackContainer.hpp"
#include "Acts/Geometry/GeometryContext.hpp"
#include "Acts/Plugins/EDM4hep/EDM4hepUtil.hpp"
#include "Acts/Surfaces/PerigeeSurface.hpp"
#include "Acts/Surfaces/PlaneSurface.hpp"
#include "Acts/Surfaces/Surface.hpp"
#include "Acts/Tests/CommonHelpers/FloatComparisons.hpp"
#include "Acts/Utilities/Logger.hpp"
#include "Acts/Utilities/Zip.hpp"
#include <algorithm>
#include <random>
#include <edm4hep/TrackCollection.h>
Functions
BOOST_AUTO_TEST_CASE (ConvertTrackParametersToEdm4hepWithPerigee)
BOOST_AUTO_TEST_CASE (ConvertTrackParametersToEdm4hepWithOutPerigee)
BOOST_AUTO_TEST_CASE (ConvertTrackParametersToEdm4hepWithPerigeeNoCov)
BOOST_AUTO_TEST_CASE (ConvertTrackParametersToEdm4hepWithOutPerigeeNoCov)
BOOST_AUTO_TEST_CASE (CovariancePacking)
BOOST_AUTO_TEST_CASE (RoundTripTests)
Function Documentation
BOOST_AUTO_TEST_CASE (ConvertTrackParametersToEdm4hepWithPerigee)
Definition at line 40 of file ConvertTrackEDM4hepTest.cpp.
View newest version in sPHENIX GitHub at line 40 of file ConvertTrackEDM4hepTest.cpp
References Acts::IntegrationTest::Bz, Acts::EDM4hepUtil::detail::convertTrackParametersFromEdm4hep(), Acts::EDM4hepUtil::detail::convertTrackParametersToEdm4hep(), Acts::Test::cov, Acts::EDM4hepUtil::detail::Parameters::covariance, Acts::GenericBoundTrackParameters< particle_hypothesis_t >::covariance(), gctx, Acts::GenericBoundTrackParameters< particle_hypothesis_t >::parameters(), Acts::ParticleHypothesis::pion(), Acts::EDM4hepUtil::detail::Parameters::surface, and Acts::EDM4hepUtil::detail::Parameters::values.
BOOST_AUTO_TEST_CASE (ConvertTrackParametersToEdm4hepWithOutPerigee)
Definition at line 83 of file ConvertTrackEDM4hepTest.cpp.
View newest version in sPHENIX GitHub at line 83 of file ConvertTrackEDM4hepTest.cpp
References Acts::IntegrationTest::Bz, Acts::EDM4hepUtil::detail::convertTrackParametersToEdm4hep(), Acts::Test::cov, Acts::EDM4hepUtil::detail::Parameters::covariance, gctx, Acts::ParticleHypothesis::pion(), Acts::EDM4hepUtil::detail::Parameters::surface, and Acts::EDM4hepUtil::detail::Parameters::values.
BOOST_AUTO_TEST_CASE (ConvertTrackParametersToEdm4hepWithPerigeeNoCov)
Definition at line 127 of file ConvertTrackEDM4hepTest.cpp.
View newest version in sPHENIX GitHub at line 127 of file ConvertTrackEDM4hepTest.cpp
References Acts::IntegrationTest::Bz, Acts::EDM4hepUtil::detail::convertTrackParametersFromEdm4hep(), Acts::EDM4hepUtil::detail::convertTrackParametersToEdm4hep(), Acts::EDM4hepUtil::detail::Parameters::covariance, Acts::GenericBoundTrackParameters< particle_hypothesis_t >::covariance(), gctx, Acts::GenericBoundTrackParameters< particle_hypothesis_t >::parameters(), Acts::ParticleHypothesis::pion(), Acts::EDM4hepUtil::detail::Parameters::surface, and Acts::EDM4hepUtil::detail::Parameters::values.
BOOST_AUTO_TEST_CASE (ConvertTrackParametersToEdm4hepWithOutPerigeeNoCov)
Definition at line 160 of file ConvertTrackEDM4hepTest.cpp.
View newest version in sPHENIX GitHub at line 160 of file ConvertTrackEDM4hepTest.cpp
References Acts::IntegrationTest::Bz, Acts::EDM4hepUtil::detail::convertTrackParametersToEdm4hep(), Acts::EDM4hepUtil::detail::Parameters::covariance, gctx, Acts::ParticleHypothesis::pion(), Acts::EDM4hepUtil::detail::Parameters::surface, and Acts::EDM4hepUtil::detail::Parameters::values.
BOOST_AUTO_TEST_CASE (CovariancePacking)
Definition at line 194 of file ConvertTrackEDM4hepTest.cpp.
View newest version in sPHENIX GitHub at line 194 of file ConvertTrackEDM4hepTest.cpp
References CHECK_CLOSE_ABS, Acts::UnitConstants::e, Acts::UnitConstants::m, Acts::UnitConstants::m2, Acts::EDM4hepUtil::detail::packCovariance(), Acts::EDM4hepUtil::detail::unpackCovariance(), and Acts::Test::values.
BOOST_AUTO_TEST_CASE (RoundTripTests)
Definition at line 215 of file ConvertTrackEDM4hepTest.cpp.
View newest version in sPHENIX GitHub at line 215 of file ConvertTrackEDM4hepTest.cpp
References Acts::IntegrationTest::Bz, Acts::calculateTrackQuantities(), charge(), CHECK_CLOSE_ABS, CHECK_CLOSE_OR_SMALL, Acts::Test::cov, Acts::UnitConstants::e, eta, Acts::Test::etaDist(), f, Acts::EventDataView3DTest::gauss(), gctx, Acts::getDefaultLogger(), Acts::HoleFlag, i, Acts::Logging::INFO, logger(), Acts::MaterialFlag, Acts::MeasurementFlag, Acts::OutlierFlag, merge_hashes::p, ActsTests::PropagationDatasets::phi, Acts::Test::phiDist(), Acts::Test::pos, physmon_track_finding_ttbar::pt, Acts::Test::qDist(), physmon_track_finding_ttbar::r, ActsExamples::JsonSurfacesReader::read(), Acts::EDM4hepUtil::readTrack(), conftest::rng(), Acts::SharedHitFlag, t, ActsTests::PropagationDatasets::theta, tracks(), and Acts::EDM4hepUtil::writeTrack().