Analysis Software: PHGenFitTrackProjection Class Reference
PHGenFitTrackProjection Class Reference
Projects into calorimeters and fills track cal fields.
#include <coresoftware/blob/master/offline/packages/trackreco/PHGenFitTrackProjection.h>
Public Member Functions
PHGenFitTrackProjection (const std::string &name="PHGenFitTrackProjection", const int pid_guess=211)
~PHGenFitTrackProjection () override
int Init (PHCompositeNode *topNode) override
int InitRun (PHCompositeNode *topNode) override
int process_event (PHCompositeNode *topNode) override
int End (PHCompositeNode *topNode) override
Called at the end of all processing.
int get_pid_guess () const
void set_pid_guess (int pidGuess)
void use_poscalib_cemc_clusters (bool calib)
Public Member Functions inherited from SubsysReco
~SubsysReco () override
virtual int EndRun (const int)
Called at the end of each run.
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
void Print (const std::string &="ALL") const override
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Private Attributes
PHGenFit::Fitter * _fitter
int _pid_guess
bool _use_poscalib_cemc = false
int _num_cal_layers
std::vector< SvtxTrack::CAL_LAYER > _cal_types
std::vector< std::string > _cal_names
std::vector< float > _cal_radii
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = std::numeric_limits<int>::max() - 10
}
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Detailed Description
Projects into calorimeters and fills track cal fields.
Definition at line 29 of file PHGenFitTrackProjection.h.
View newest version in sPHENIX GitHub at line 29 of file PHGenFitTrackProjection.h
Constructor & Destructor Documentation
PHGenFitTrackProjection::PHGenFitTrackProjection (const std::string & name = "PHGenFitTrackProjection", const int pid_guess = 211)
Definition at line 68 of file PHGenFitTrackProjection.cc.
View newest version in sPHENIX GitHub at line 68 of file PHGenFitTrackProjection.cc
References _cal_names, _cal_radii, _cal_types, _num_cal_layers, SvtxTrack::CEMC, SvtxTrack::HCALIN, SvtxTrack::HCALOUT, and SvtxTrack::PRES.
PHGenFitTrackProjection::~PHGenFitTrackProjection () inline override
Definition at line 35 of file PHGenFitTrackProjection.h.
View newest version in sPHENIX GitHub at line 35 of file PHGenFitTrackProjection.h
Member Function Documentation
int PHGenFitTrackProjection::End (PHCompositeNode *) override virtual
Called at the end of all processing.
Reimplemented from SubsysReco.
Definition at line 474 of file PHGenFitTrackProjection.cc.
View newest version in sPHENIX GitHub at line 474 of file PHGenFitTrackProjection.cc
References Fun4AllReturnCodes::EVENT_OK.
int PHGenFitTrackProjection::get_pid_guess () const inline
Definition at line 42 of file PHGenFitTrackProjection.h.
View newest version in sPHENIX GitHub at line 42 of file PHGenFitTrackProjection.h
References _pid_guess.
int PHGenFitTrackProjection::Init (PHCompositeNode *) override virtual
Called during initialization. Typically this is where you can book histograms, and e.g. register them to Fun4AllServer (so they can be output to file using Fun4AllServer::dumpHistos() method).
Reimplemented from SubsysReco.
Definition at line 88 of file PHGenFitTrackProjection.cc.
View newest version in sPHENIX GitHub at line 88 of file PHGenFitTrackProjection.cc
References Fun4AllReturnCodes::EVENT_OK.
int PHGenFitTrackProjection::InitRun (PHCompositeNode *) override virtual
Called for first event when run number is known. Typically this is where you may want to fetch data from database, because you know the run number.
Reimplemented from SubsysReco.
Definition at line 92 of file PHGenFitTrackProjection.cc.
View newest version in sPHENIX GitHub at line 92 of file PHGenFitTrackProjection.cc
References _cal_names, _cal_radii, _fitter, _num_cal_layers, Fun4AllReturnCodes::ABORTRUN, Fun4AllReturnCodes::EVENT_OK, ckf::field, RawTowerGeomContainer::get_radius(), PHFieldUtility::GetFieldMapNode(), PHGenFit::Fitter::getInstance(), PHGeomUtility::GetTGeoManager(), i, PHWHERE, PHGenFit::Fitter::set_verbosity(), and Fun4AllBase::Verbosity().
int PHGenFitTrackProjection::process_event (PHCompositeNode *) override virtual
Called for each event. This is where you do the real work.
eta as location mark of cluster relative to (0,0,0)
Reimplemented from SubsysReco.
Definition at line 143 of file PHGenFitTrackProjection.cc.
View newest version in sPHENIX GitHub at line 143 of file PHGenFitTrackProjection.cc
References _cal_names, _cal_radii, _cal_types, _num_cal_layers, _pid_guess, _use_poscalib_cemc, Fun4AllReturnCodes::ABORTRUN, SvtxTrackMap::begin(), Acts::IntegrationTest::Bz, compare(), Acts::Test::cov, INTTVtxZ::dphi, SvtxTrackMap::end(), SvtxTrack::end_states(), eta, Fun4AllReturnCodes::EVENT_OK, SvtxTrack::get_charge(), TowerInfo::get_energy(), RawCluster::get_energy(), SvtxTrackState::get_error(), SvtxTrack::get_eta(), RawTowerGeomContainer::get_etabin(), RawTowerGeomContainer::get_etabins(), SvtxTrack::get_id(), RawCluster::get_phi(), SvtxTrack::get_phi(), RawTowerGeomContainer::get_phibin(), RawTowerGeomContainer::get_phibins(), SvtxTrack::get_pt(), SvtxTrackState::get_px(), SvtxTrackState::get_py(), SvtxTrackState::get_pz(), TowerInfoContainer::get_tower_at_key(), SvtxTrackState::get_x(), SvtxTrackState::get_y(), SvtxTrackState::get_z(), findNode::getClass(), RawClusterContainer::getClustersMap(), genfit::FieldManager::getFieldVal(), genfit::FieldManager::getInstance(), genfit::AbsTrackRep::getMom(), genfit::AbsTrackRep::getPos(), RawClusterUtility::GetPseudorapidity(), i, j, k, LogWarning, pdg, ActsTests::PropagationDatasets::phi, PHWHERE, Acts::Test::pos, physmon_track_finding_ttbar::r, SvtxTrack::set_cal_cluster_e(), SvtxTrack::set_cal_cluster_id(), SvtxTrack::set_cal_deta(), SvtxTrack::set_cal_dphi(), SvtxTrack::set_cal_energy_3x3(), SvtxTrack::set_cal_energy_5x5(), genfit::AbsTrackRep::setPosMomCov(), Fun4AllBase::Verbosity(), ambiguity_solver_full_chain::x, y, and physmon_track_finding_ttbar::z.
void PHGenFitTrackProjection::set_pid_guess (int pidGuess) inline
Definition at line 46 of file PHGenFitTrackProjection.h.
View newest version in sPHENIX GitHub at line 46 of file PHGenFitTrackProjection.h
References _pid_guess.
void PHGenFitTrackProjection::use_poscalib_cemc_clusters (bool calib) inline
Definition at line 50 of file PHGenFitTrackProjection.h.
View newest version in sPHENIX GitHub at line 50 of file PHGenFitTrackProjection.h
References _use_poscalib_cemc.
Member Data Documentation
std::vector<std::string> PHGenFitTrackProjection::_cal_names private
Definition at line 63 of file PHGenFitTrackProjection.h.
View newest version in sPHENIX GitHub at line 63 of file PHGenFitTrackProjection.h
Referenced by InitRun(), PHGenFitTrackProjection(), and process_event().
std::vector<float> PHGenFitTrackProjection::_cal_radii private
Definition at line 64 of file PHGenFitTrackProjection.h.
View newest version in sPHENIX GitHub at line 64 of file PHGenFitTrackProjection.h
Referenced by InitRun(), PHGenFitTrackProjection(), and process_event().
std::vector<SvtxTrack::CAL_LAYER> PHGenFitTrackProjection::_cal_types private
Definition at line 62 of file PHGenFitTrackProjection.h.
View newest version in sPHENIX GitHub at line 62 of file PHGenFitTrackProjection.h
Referenced by PHGenFitTrackProjection(), and process_event().
PHGenFit::Fitter* PHGenFitTrackProjection::_fitter private
Definition at line 56 of file PHGenFitTrackProjection.h.
View newest version in sPHENIX GitHub at line 56 of file PHGenFitTrackProjection.h
Referenced by InitRun().
int PHGenFitTrackProjection::_num_cal_layers private
Definition at line 61 of file PHGenFitTrackProjection.h.
View newest version in sPHENIX GitHub at line 61 of file PHGenFitTrackProjection.h
Referenced by InitRun(), PHGenFitTrackProjection(), and process_event().
int PHGenFitTrackProjection::_pid_guess private
Definition at line 57 of file PHGenFitTrackProjection.h.
View newest version in sPHENIX GitHub at line 57 of file PHGenFitTrackProjection.h
Referenced by get_pid_guess(), process_event(), and set_pid_guess().
bool PHGenFitTrackProjection::_use_poscalib_cemc = false private
Definition at line 59 of file PHGenFitTrackProjection.h.
View newest version in sPHENIX GitHub at line 59 of file PHGenFitTrackProjection.h
Referenced by process_event(), and use_poscalib_cemc_clusters().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/trackreco/PHGenFitTrackProjection.h
coresoftware/blob/master/offline/packages/trackreco/PHGenFitTrackProjection.cc