Analysis Software: TrkrClusterContainer Class Reference
TrkrClusterContainer Class Reference
Cluster container object.
#include <coresoftware/blob/master/offline/packages/trackbase/TrkrClusterContainer.h>
Public Types
convenient shortuts
using Map = std::map< TrkrDefs::cluskey, TrkrCluster * >
using Iterator = Map::iterator
using ConstIterator = Map::const_iterator
using Range = std::pair< Iterator, Iterator >
using ConstRange = std::pair< ConstIterator, ConstIterator >
using HitSetKeyList = std::vector< TrkrDefs::hitsetkey >
Public Member Functions
void Reset () override
reset method
void identify (std::ostream &=std::cout) const override
identify object
virtual void addClusterSpecifyKey (const TrkrDefs::cluskey, TrkrCluster *)
add a cluster with specific key
virtual void removeCluster (TrkrDefs::cluskey)
remove cluster
virtual ConstRange getClusters () const
return all clusters
virtual ConstRange getClusters (TrkrDefs::hitsetkey)
get all clusters matching hitset
virtual TrkrCluster * findCluster (TrkrDefs::cluskey) const
find cluster matching given key
virtual HitSetKeyList getHitSetKeys () const
get hitset key list
virtual HitSetKeyList getHitSetKeys (const TrkrDefs::TrkrId) const
get hitset key list for a given detector
virtual HitSetKeyList getHitSetKeys (const TrkrDefs::TrkrId, const uint8_t) const
get hitset key list for a given detector and layer
virtual unsigned int size () const
total number of clusters
Public Member Functions inherited from PHObject
PHObject ()
ctor
~PHObject () override
dtor
virtual PHObject * CloneMe () const
Virtual copy constructor.
virtual PHObject * clone () const final
PHObject * Clone (const char *newname="") const final
void Copy (TObject &object) const final
virtual int isValid () const
isValid returns non zero if object contains vailid data
virtual int Integrate () const
virtual int Integrate (PHObject *)
virtual void CopyFrom (const PHObject *obj)
Protected Member Functions
TrkrClusterContainer ()=default
constructor
Detailed Description
Cluster container object.
Definition at line 24 of file TrkrClusterContainer.h.
View newest version in sPHENIX GitHub at line 24 of file TrkrClusterContainer.h
Member Typedef Documentation
using TrkrClusterContainer::ConstIterator = Map::const_iterator
Definition at line 31 of file TrkrClusterContainer.h.
View newest version in sPHENIX GitHub at line 31 of file TrkrClusterContainer.h
using TrkrClusterContainer::ConstRange = std::pair<ConstIterator, ConstIterator>
Definition at line 33 of file TrkrClusterContainer.h.
View newest version in sPHENIX GitHub at line 33 of file TrkrClusterContainer.h
using TrkrClusterContainer::HitSetKeyList = std::vector<TrkrDefs::hitsetkey>
Definition at line 35 of file TrkrClusterContainer.h.
View newest version in sPHENIX GitHub at line 35 of file TrkrClusterContainer.h
using TrkrClusterContainer::Iterator = Map::iterator
Definition at line 30 of file TrkrClusterContainer.h.
View newest version in sPHENIX GitHub at line 30 of file TrkrClusterContainer.h
using TrkrClusterContainer::Map = std::map<TrkrDefs::cluskey, TrkrCluster*>
Definition at line 29 of file TrkrClusterContainer.h.
View newest version in sPHENIX GitHub at line 29 of file TrkrClusterContainer.h
using TrkrClusterContainer::Range = std::pair<Iterator, Iterator>
Definition at line 32 of file TrkrClusterContainer.h.
View newest version in sPHENIX GitHub at line 32 of file TrkrClusterContainer.h
Constructor & Destructor Documentation
TrkrClusterContainer::TrkrClusterContainer () protected default
constructor
Member Function Documentation
virtual void TrkrClusterContainer::addClusterSpecifyKey (const TrkrDefs::cluskey , TrkrCluster *) inline virtual
add a cluster with specific key
Reimplemented in TrkrClusterContainerv1, TrkrClusterContainerv2, TrkrClusterContainerv3, and TrkrClusterContainerv4.
Definition at line 46 of file TrkrClusterContainer.h.
View newest version in sPHENIX GitHub at line 46 of file TrkrClusterContainer.h
Referenced by TpcClusterBuilder::cluster_hits(), PHG4InttHitReco::cluster_truthhits(), PHG4MvtxHitReco::cluster_truthhits(), InttClusterizer::ClusterLadderCells(), InttClusterizer::ClusterLadderCellsRaw(), MvtxClusterizer::ClusterMvtx(), MvtxClusterizer::ClusterMvtxRaw(), FilterEventsUpsilon::process_event(), TpcSimpleClusterizer::process_event(), TpcClusterizer::process_event(), and PHTpcClusterMover::process_event().
virtual TrkrCluster* TrkrClusterContainer::findCluster (TrkrDefs::cluskey) const inline virtual
find cluster matching given key
Reimplemented in TrkrClusterContainerv1, TrkrClusterContainerv4, TrkrClusterContainerv2, and TrkrClusterContainerv3.
Definition at line 58 of file TrkrClusterContainer.h.
View newest version in sPHENIX GitHub at line 58 of file TrkrClusterContainer.h
Referenced by TrackFitUtils::addClusters(), TrackFitUtils::addClustersOnLine(), PHCosmicTrackMerger::addKeys(), MakeMilleFiles::addTrackToMilleFile(), ALICEKF::ALICEKalmanFilter(), SvtxClusterEval::all_truth_hits_by_nhit(), g4evalfn::calc_match_statistic(), TrackSeed_v1::circleFitByTaubin(), g4evalfn::clusloc_PHG4(), G4Eval::TrkrClusterComparer::clusloc_PHG4(), g4evalfn::clusloc_SVTX(), G4Eval::TrkrClusterComparer::clusloc_SVTX(), Conversion::dist(), QAG4SimulationMicromegas::evaluate_clusters(), DSTEmulator::evaluate_tracks(), TrackEvaluation::evaluate_tracks(), TpcPrototypeUnpacker::exportDSTCluster(), ActsAlignmentStates::fillAlignmentStateMap(), TrackResiduals::fillClusterTree(), KFParticle_truthAndDetTools::fillDetectorBranch(), TrkrNtuplizer::fillOutputNtuples(), SvtxEvaluator::fillOutputNtuples(), ActsEvaluator::fillProtoTrack(), PHActsKDTreeSeeding::fillTrackSeedContainer(), PHCosmicsTrkFitter::fillVectors(), Conversion::firstLayer(), TrackSeed_v1::get_phi(), PHCosmicsTrkFitter::getCharge(), TrackSeedTrackMapConverter::getCosmicCharge(), PHCosmicTrackMerger::getGlobalPositions(), PHSiliconTpcTrackMatching::getInttCrossings(), MakeMilleFiles::getLocalVtxDerivativesXY(), MakeSourceLinks::getSourceLinks(), HelicalFitter::getTrackletClusterList(), TrackFitUtils::getTrackletClusters(), SvtxClusterEval::gtrackid_and_layer_by_nhit(), RecoConversionEval::hitCuts(), TrackSeed_v1::lineFit(), SVReco::MakeGenFitTrack(), TrackerEventDisplay::makeJsonFile(), PHGenFitTrkFitter::MakeSvtxTrack(), PHActsSiliconSeeding::makeSvtxTracks(), TpcPrototypeGenFitTrkFitter::MakeTpcPrototypeTrack(), SvtxClusterEval::max_truth_cluster_by_energy(), G4Eval::TrkrClusterComparer::operator()(), TpcClusterBuilder::print_file(), PHSiliconTruthTrackSeeding::Process(), PHSiliconHelicalPropagator::process_event(), PHCosmicSiliconPropagator::process_event(), TrackSeedTrackMapConverter::process_event(), FilterEventsUpsilon::process_event(), QAG4SimulationDistortions::process_event(), TPCGemGainCalb::process_event(), MvtxPrototype2Align::process_event(), PHTpcClusterMover::process_event(), PHMicromegasTpcTrackMatching::process_event(), HelicalFitter::process_event(), TpcPrototypeGenFitTrkFitter::process_event(), PHTpcDeltaZCorrection::process_track(), TpcSpaceChargeReconstruction::process_track(), TrackClusterEvaluator::processRecoTracks(), PHTpcResiduals::processTrack(), TruthConversionEval::processTrackBackground(), TrackClusterEvaluator::processTruthTracks(), PHSimpleKFProp::PropagateTrack(), SvtxClusterEval::reco_cluster_from_truth_cluster(), TpcPrototypeGenFitTrkFitter::ReFitTrack(), PHGenFitTrkFitter::ReFitTrack(), TPCHitTrackDisplay::SimulationOut(), and Conversion::trackDLayer().
TrkrClusterContainer::ConstRange TrkrClusterContainer::getClusters (void) const virtual
return all clusters
Reimplemented in TrkrClusterContainerv1, and TrkrClusterContainerv4.
Definition at line 14 of file TrkrClusterContainer.cc.
View newest version in sPHENIX GitHub at line 14 of file TrkrClusterContainer.cc
Referenced by TrackFitUtils::addClusters(), TrackFitUtils::addClustersOnLine(), SvtxClusterEval::all_clusters_from(), SvtxClusterEval::best_cluster_by_nhit(), InttVertexFinder::calculateZvertex(), QAG4SimulationIntt::evaluate_clusters(), QAG4SimulationMvtx::evaluate_clusters(), TrackEvaluation::evaluate_clusters(), TrackEvaluation::evaluate_event(), SvtxClusterEval::fill_cluster_layer_map(), TrackResiduals::fillClusterTree(), TrkrNtuplizer::fillOutputNtuples(), SvtxEvaluator::fillOutputNtuples(), SvtxClusterEval::FillRecoClusterFromG4HitCache(), PHCASeeding::FillTree(), MultiDetectorMultiplicity::getMVTXnclusters(), PHActsKDTreeSeeding::getMvtxSpacePoints(), PHTruthSiliconAssociation::getSiliconClustersFromParticle(), PHActsSiliconSeeding::getSiliconSpacePoints(), TrackerEventDisplay::makeJsonFile(), PHActsKDTreeSeeding::matchInttClusters(), PHActsSiliconSeeding::matchInttClusters(), PHSimpleKFProp::PrepareKDTrees(), FillTruthRecoMatchTree::print_mvtx_diagnostics(), TrkrNtuplizer::printInputInfo(), SvtxEvaluator::printInputInfo(), PHSiliconTruthTrackSeeding::Process(), TpcClusterCleaner::process_event(), QAG4SimulationTracking::process_event(), PHCosmicSeeder::process_event(), MvtxPrototype2Align::process_event(), PHMicromegasTpcTrackMatching::process_event(), PHTruthClustering::process_event(), TpcPrototypeGenFitTrkFinder::process_event(), PHTpcCentralMembraneClusterizer::process_event(), FillTruthRecoMatchTree::process_event(), TpcPrototypeGenFitTrkFitter::process_event(), DumpTrkrClusterContainer::process_Node(), and TPCHitTrackDisplay::SimulationOut().
TrkrClusterContainer::ConstRange TrkrClusterContainer::getClusters (TrkrDefs::hitsetkey) virtual
get all clusters matching hitset
Reimplemented in TrkrClusterContainerv4, TrkrClusterContainerv2, and TrkrClusterContainerv3.
Definition at line 20 of file TrkrClusterContainer.cc.
View newest version in sPHENIX GitHub at line 20 of file TrkrClusterContainer.cc
virtual HitSetKeyList TrkrClusterContainer::getHitSetKeys () const inline virtual
get hitset key list
Reimplemented in TrkrClusterContainerv4, and TrkrClusterContainerv3.
Definition at line 61 of file TrkrClusterContainer.h.
View newest version in sPHENIX GitHub at line 61 of file TrkrClusterContainer.h
Referenced by TrackFitUtils::addClusters(), TrackFitUtils::addClustersOnLine(), SvtxClusterEval::all_clusters_from(), SvtxClusterEval::best_cluster_by_nhit(), InttVertexFinder::calculateZvertex(), QAG4SimulationIntt::evaluate_clusters(), QAG4SimulationMvtx::evaluate_clusters(), TrackEvaluation::evaluate_clusters(), TrackEvaluation::evaluate_event(), SvtxClusterEval::fill_cluster_layer_map(), TrackResiduals::fillClusterTree(), TrkrNtuplizer::fillOutputNtuples(), SvtxEvaluator::fillOutputNtuples(), SvtxClusterEval::FillRecoClusterFromG4HitCache(), PHCASeeding::FillTree(), MultiDetectorMultiplicity::getMVTXnclusters(), PHActsKDTreeSeeding::getMvtxSpacePoints(), PHTruthSiliconAssociation::getSiliconClustersFromParticle(), PHActsSiliconSeeding::getSiliconSpacePoints(), TrackerEventDisplay::makeJsonFile(), PHActsKDTreeSeeding::matchInttClusters(), PHActsSiliconSeeding::matchInttClusters(), PHSimpleKFProp::PrepareKDTrees(), FillTruthRecoMatchTree::print_mvtx_diagnostics(), TrkrNtuplizer::printInputInfo(), SvtxEvaluator::printInputInfo(), PHSiliconTruthTrackSeeding::Process(), TpcClusterCleaner::process_event(), QAG4SimulationTracking::process_event(), PHCosmicSeeder::process_event(), PHTruthClustering::process_event(), PHTpcCentralMembraneClusterizer::process_event(), FillTruthRecoMatchTree::process_event(), DumpTrkrClusterContainer::process_Node(), and TPCHitTrackDisplay::SimulationOut().
virtual HitSetKeyList TrkrClusterContainer::getHitSetKeys (const TrkrDefs::TrkrId) const inline virtual
get hitset key list for a given detector
Reimplemented in TrkrClusterContainerv4, and TrkrClusterContainerv3.
Definition at line 67 of file TrkrClusterContainer.h.
View newest version in sPHENIX GitHub at line 67 of file TrkrClusterContainer.h
virtual HitSetKeyList TrkrClusterContainer::getHitSetKeys (const TrkrDefs::TrkrId , const uint8_t) const inline virtual
get hitset key list for a given detector and layer
Reimplemented in TrkrClusterContainerv4, and TrkrClusterContainerv3.
Definition at line 73 of file TrkrClusterContainer.h.
View newest version in sPHENIX GitHub at line 73 of file TrkrClusterContainer.h
void TrkrClusterContainer::identify (std::ostream & = std::cout) const inline override virtual
identify object
Reimplemented from PHObject.
Reimplemented in TrkrClusterContainerv1, TrkrClusterContainerv2, TrkrClusterContainerv3, and TrkrClusterContainerv4.
Definition at line 43 of file TrkrClusterContainer.h.
View newest version in sPHENIX GitHub at line 43 of file TrkrClusterContainer.h
Referenced by MvtxPrototype2Clusterizer::PrintClusters(), MvtxClusterizer::PrintClusters(), InttClusterizer::PrintClusters(), TpcPrototypeClusterizer::process_event(), DumpTrkrHitTruthAssoc::process_Node(), and DumpTrkrClusterContainer::process_Node().
virtual void TrkrClusterContainer::removeCluster (TrkrDefs::cluskey) inline virtual
remove cluster
Reimplemented in TrkrClusterContainerv1, TrkrClusterContainerv2, TrkrClusterContainerv3, and TrkrClusterContainerv4.
Definition at line 49 of file TrkrClusterContainer.h.
View newest version in sPHENIX GitHub at line 49 of file TrkrClusterContainer.h
Referenced by TpcClusterCleaner::process_event().
void TrkrClusterContainer::Reset () inline override virtual
reset method
Reimplemented from PHObject.
Reimplemented in TrkrClusterContainerv1, TrkrClusterContainerv2, TrkrClusterContainerv3, and TrkrClusterContainerv4.
Definition at line 40 of file TrkrClusterContainer.h.
View newest version in sPHENIX GitHub at line 40 of file TrkrClusterContainer.h
Referenced by PHTpcClusterMover::GetNodes(), and FilterEventsUpsilon::process_event().
virtual unsigned int TrkrClusterContainer::size (void) const inline virtual
total number of clusters
Reimplemented in TrkrClusterContainerv1, TrkrClusterContainerv4, TrkrClusterContainerv3, and TrkrClusterContainerv2.
Definition at line 79 of file TrkrClusterContainer.h.
View newest version in sPHENIX GitHub at line 79 of file TrkrClusterContainer.h
Referenced by SvtxClusterEval::best_cluster_by_nhit(), TrkrNtuplizer::fillOutputNtuples(), SvtxEvaluator::fillOutputNtuples(), SvtxClusterEval::get_node_pointers(), DSTEmulator::load_nodes(), MvtxPrototype2Clusterizer::PrintClusters(), MvtxClusterizer::PrintClusters(), InttClusterizer::PrintClusters(), TrkrNtuplizer::printInputInfo(), SvtxEvaluator::printInputInfo(), FilterEventsUpsilon::process_event(), TpcClusterCleaner::process_event(), TpcSimpleClusterizer::process_event(), PHG4TpcPadBaselineShift::process_event(), TpcClusterizer::process_event(), AnaMvtxPrototype1::process_event(), PHTpcCentralMembraneClusterizer::process_event(), sPHAnalysis::process_event_filtered(), and DumpTrkrClusterContainer::process_Node().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/trackbase/TrkrClusterContainer.h
coresoftware/blob/master/offline/packages/trackbase/TrkrClusterContainer.cc