Analysis Software: TrkrClusterContainerv2 Class Reference
TrkrClusterContainerv2 Class Reference
Cluster container object.
#include <coresoftware/blob/master/offline/packages/trackbase/TrkrClusterContainerv2.h>
Public Member Functions
TrkrClusterContainerv2 ()=default
void Reset () override
reset method
void identify (std::ostream &os=std::cout) const override
identify object
ConstIterator addCluster (TrkrCluster *) override
add a cluster
ConstIterator addClusterSpecifyKey (const TrkrDefs::cluskey, TrkrCluster *) override
add a cluster with specific key
void removeCluster (TrkrDefs::cluskey) override
remove cluster
void removeCluster (TrkrCluster *) override
remove cluster
Iterator findOrAddCluster (TrkrDefs::cluskey) override
find cluster matching key if any, add a new one otherwise and return cluster
ConstRange getClusters (TrkrDefs::hitsetkey) const override
get all clusters matching hitset
Map * getClusterMap (TrkrDefs::hitsetkey) override
get pointer to map containing clusters mathching hitset
TrkrCluster * findCluster (TrkrDefs::cluskey) const override
find cluster matching given key
unsigned int size () const override
total number of clusters
Public Member Functions inherited from TrkrClusterContainer
virtual ConstRange getClusters () const
return all clusters
Public Member Functions inherited from PHObject
PHObject ()
ctor
~PHObject () override
dtor
virtual PHObject * CloneMe () const
Virtual copy constructor.
virtual PHObject * clone () const final
PHObject * Clone (const char *newname="") const final
void Copy (TObject &object) const final
virtual int isValid () const
isValid returns non zero if object contains vailid data
virtual int isValid (const float) const
virtual int isValid (const double) const
virtual int isValid (const int) const
virtual int isValid (const unsigned int) const
virtual int isImplemented (const float f) const
virtual int isImplemented (const double f) const
virtual int isImplemented (const int i) const
virtual int isImplemented (const unsigned int i) const
virtual int Integrate () const
virtual int Integrate (PHObject *obj)
virtual void CopyFrom (const PHObject *obj)
Private Attributes
unsigned int max_layer = 57
unsigned int max_phisegment = 20
unsigned int max_zsegment = 15
Map m_clusmap [57][20][15]
Additional Inherited Members
Public Types inherited from TrkrClusterContainer
using Map = std::map< TrkrDefs::cluskey, TrkrCluster * >
using Iterator = Map::iterator
using ConstIterator = Map::const_iterator
using Range = std::pair< Iterator, Iterator >
using ConstRange = std::pair< ConstIterator, ConstIterator >
Protected Member Functions inherited from TrkrClusterContainer
TrkrClusterContainer ()=default
constructor
Detailed Description
Cluster container object.
Definition at line 20 of file TrkrClusterContainerv2.h.
View newest version in sPHENIX GitHub at line 20 of file TrkrClusterContainerv2.h
Constructor & Destructor Documentation
TrkrClusterContainerv2::TrkrClusterContainerv2 () default
Member Function Documentation
TrkrClusterContainerv2::ConstIterator TrkrClusterContainerv2::addCluster (TrkrCluster *) override virtual
add a cluster
Reimplemented from TrkrClusterContainer.
Definition at line 95 of file TrkrClusterContainerv2.cc.
View newest version in sPHENIX GitHub at line 95 of file TrkrClusterContainerv2.cc
References addClusterSpecifyKey(), and TrkrCluster::getClusKey().
TrkrClusterContainerv2::ConstIterator TrkrClusterContainerv2::addClusterSpecifyKey (const TrkrDefs::cluskey , TrkrCluster *) override virtual
add a cluster with specific key
Reimplemented from TrkrClusterContainer.
Definition at line 100 of file TrkrClusterContainerv2.cc.
View newest version in sPHENIX GitHub at line 100 of file TrkrClusterContainerv2.cc
References TrkrDefs::getLayer(), TrkrDefs::getPhiElement(), TrkrDefs::getZElement(), layer, m_clusmap, max_layer, max_phisegment, and max_zsegment.
Referenced by addCluster().
TrkrCluster * TrkrClusterContainerv2::findCluster (TrkrDefs::cluskey) const override virtual
find cluster matching given key
Reimplemented from TrkrClusterContainer.
Definition at line 216 of file TrkrClusterContainerv2.cc.
View newest version in sPHENIX GitHub at line 216 of file TrkrClusterContainerv2.cc
References TrkrDefs::getLayer(), TrkrDefs::getPhiElement(), TrkrDefs::getZElement(), it, layer, m_clusmap, max_layer, max_phisegment, and max_zsegment.
TrkrClusterContainerv2::Iterator TrkrClusterContainerv2::findOrAddCluster (TrkrDefs::cluskey) override virtual
find cluster matching key if any, add a new one otherwise and return cluster
Reimplemented from TrkrClusterContainer.
Definition at line 185 of file TrkrClusterContainerv2.cc.
View newest version in sPHENIX GitHub at line 185 of file TrkrClusterContainerv2.cc
References TrkrDefs::getLayer(), TrkrDefs::getPhiElement(), TrkrDefs::getZElement(), it, layer, m_clusmap, max_layer, max_phisegment, and max_zsegment.
TrkrClusterContainerv2::Map * TrkrClusterContainerv2::getClusterMap (TrkrDefs::hitsetkey) override virtual
get pointer to map containing clusters mathching hitset
Reimplemented from TrkrClusterContainer.
Definition at line 161 of file TrkrClusterContainerv2.cc.
View newest version in sPHENIX GitHub at line 161 of file TrkrClusterContainerv2.cc
References TrkrDefs::getLayer(), TrkrDefs::getPhiElement(), TrkrDefs::getZElement(), layer, m_clusmap, max_layer, max_phisegment, and max_zsegment.
TrkrClusterContainerv2::ConstRange TrkrClusterContainerv2::getClusters (TrkrDefs::hitsetkey hitsetkey) const override virtual
get all clusters matching hitset
Reimplemented from TrkrClusterContainer.
Definition at line 137 of file TrkrClusterContainerv2.cc.
View newest version in sPHENIX GitHub at line 137 of file TrkrClusterContainerv2.cc
References TrkrDefs::getLayer(), TrkrDefs::getPhiElement(), TrkrDefs::getZElement(), layer, m_clusmap, max_layer, max_phisegment, and max_zsegment.
void TrkrClusterContainerv2::identify (std::ostream & os = std::cout) const override virtual
identify object
Reimplemented from TrkrClusterContainer.
Definition at line 34 of file TrkrClusterContainerv2.cc.
View newest version in sPHENIX GitHub at line 34 of file TrkrClusterContainerv2.cc
References TrkrDefs::getLayer(), TrkrDefs::getPhiElement(), TrkrDefs::getZElement(), layer, m_clusmap, max_layer, max_phisegment, max_zsegment, and size().
void TrkrClusterContainerv2::removeCluster (TrkrDefs::cluskey) override virtual
remove cluster
Reimplemented from TrkrClusterContainer.
Definition at line 65 of file TrkrClusterContainerv2.cc.
View newest version in sPHENIX GitHub at line 65 of file TrkrClusterContainerv2.cc
References TrkrDefs::getLayer(), TrkrDefs::getPhiElement(), TrkrDefs::getZElement(), layer, m_clusmap, max_layer, max_phisegment, and max_zsegment.
Referenced by removeCluster().
void TrkrClusterContainerv2::removeCluster (TrkrCluster *) override virtual
remove cluster
Reimplemented from TrkrClusterContainer.
Definition at line 90 of file TrkrClusterContainerv2.cc.
View newest version in sPHENIX GitHub at line 90 of file TrkrClusterContainerv2.cc
References TrkrCluster::getClusKey(), and removeCluster().
void TrkrClusterContainerv2::Reset () override virtual
reset method
Reimplemented from TrkrClusterContainer.
Definition at line 20 of file TrkrClusterContainerv2.cc.
View newest version in sPHENIX GitHub at line 20 of file TrkrClusterContainerv2.cc
References layer, m_clusmap, max_layer, max_phisegment, and max_zsegment.
unsigned int TrkrClusterContainerv2::size (void) const override virtual
total number of clusters
Reimplemented from TrkrClusterContainer.
Definition at line 246 of file TrkrClusterContainerv2.cc.
View newest version in sPHENIX GitHub at line 246 of file TrkrClusterContainerv2.cc
References layer, m_clusmap, max_layer, max_phisegment, and max_zsegment.
Referenced by identify().
Member Data Documentation
Map TrkrClusterContainerv2::m_clusmap[57][20][15] private
Definition at line 56 of file TrkrClusterContainerv2.h.
View newest version in sPHENIX GitHub at line 56 of file TrkrClusterContainerv2.h
Referenced by addClusterSpecifyKey(), findCluster(), findOrAddCluster(), getClusterMap(), getClusters(), identify(), removeCluster(), Reset(), and size().
unsigned int TrkrClusterContainerv2::max_layer = 57 private
Definition at line 50 of file TrkrClusterContainerv2.h.
View newest version in sPHENIX GitHub at line 50 of file TrkrClusterContainerv2.h
Referenced by addClusterSpecifyKey(), findCluster(), findOrAddCluster(), getClusterMap(), getClusters(), identify(), removeCluster(), Reset(), and size().
unsigned int TrkrClusterContainerv2::max_phisegment = 20 private
Definition at line 52 of file TrkrClusterContainerv2.h.
View newest version in sPHENIX GitHub at line 52 of file TrkrClusterContainerv2.h
Referenced by addClusterSpecifyKey(), findCluster(), findOrAddCluster(), getClusterMap(), getClusters(), identify(), removeCluster(), Reset(), and size().
unsigned int TrkrClusterContainerv2::max_zsegment = 15 private
Definition at line 54 of file TrkrClusterContainerv2.h.
View newest version in sPHENIX GitHub at line 54 of file TrkrClusterContainerv2.h
Referenced by addClusterSpecifyKey(), findCluster(), findOrAddCluster(), getClusterMap(), getClusters(), identify(), removeCluster(), Reset(), and size().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/trackbase/TrkrClusterContainerv2.h
coresoftware/blob/master/offline/packages/trackbase/TrkrClusterContainerv2.cc