Analysis Software: TpcTpotEventInfov1 Class Reference
TpcTpotEventInfov1 Class Reference
Version 1 of TpcTpotEventInfo.
#include <coresoftware/blob/master/offline/packages/trackbase/TpcTpotEventInfov1.h>
Public Member Functions
TpcTpotEventInfov1 ()
ctor
~TpcTpotEventInfov1 () override=default
dtor
void identify (std::ostream &os=std::cout) const override
void Reset () override
Clear Event.
int isValid () const override
isValid returns non zero if object contains vailid data
PHObject * CloneMe () const override
Virtual copy constructor.
void CopyFrom (const TpcTpotEventInfo &) override
copy content from base class
void CopyFrom (TpcTpotEventInfo *source) override
copy content from base class
void checkIndexes (SectorID, PCIeEndPointID, TaggerID) override
uint64_t getBCO (SectorID sector, PCIeEndPointID PCIe, TaggerID tagger) const override
void setBCO (uint64_t bco, SectorID sector, PCIeEndPointID PCIe, TaggerID tagger) override
uint32_t getLevel1Count (SectorID sector, PCIeEndPointID PCIe, TaggerID tagger) const override
void setLevel1Count (uint32_t lvl1count, SectorID sector, PCIeEndPointID PCIe, TaggerID tagger) override
uint32_t getEnDatCount (SectorID sector, PCIeEndPointID PCIe, TaggerID tagger) const override
void setEnDatCount (uint32_t endatcount, SectorID sector, PCIeEndPointID PCIe, TaggerID tagger) override
uint64_t getLastBCO (SectorID sector, PCIeEndPointID PCIe, TaggerID tagger) const override
void setLastBCO (uint64_t lastbco, SectorID sector, PCIeEndPointID PCIe, TaggerID tagger) override
uint8_t getModebits (SectorID sector, PCIeEndPointID PCIe, TaggerID tagger) const override
void setModebits (uint8_t modebits, SectorID sector, PCIeEndPointID PCIe, TaggerID tagger) override
Public Member Functions inherited from TpcTpotEventInfo
~TpcTpotEventInfo () override=default
dtor
Public Member Functions inherited from PHObject
PHObject ()
ctor
~PHObject () override
dtor
virtual PHObject * clone () const final
PHObject * Clone (const char *newname="") const final
void Copy (TObject &object) const final
virtual int Integrate () const
virtual int Integrate (PHObject *)
virtual void CopyFrom (const PHObject *obj)
Protected Attributes
uint64_t m_bco [25][2][2] {}
uint32_t m_lvl1_count [25][2][2] {}
uint32_t m_endat_count [25][2][2] {}
uint64_t m_last_bco [25][2][2] {}
uint8_t m_modebits [25][2][2] {}
Additional Inherited Members
Public Types inherited from TpcTpotEventInfo
enum SectorID {
kTPCSector0 = 0, kTPCSector1, kTPCSector2, kTPCSector3,
kTPCSector4, kTPCSector5, kTPCSector6, kTPCSector7,
kTPCSector8, kTPCSector9, kTPCSector10, kTPCSector11,
kTPCSector12, kTPCSector13, kTPCSector14, kTPCSector15,
kTPCSector16, kTPCSector17, kTPCSector18, kTPCSector19,
kTPCSector20, kTPCSector21, kTPCSector22, kTPCSector23,
kTPOT = 24
}
enum PCIeEndPointID { kEndPoint0 = 0, kEndPoint1 = 1 }
enum TaggerID { kLVL1Tagger = 0, kEnDatTagger = 1 }
Protected Member Functions inherited from TpcTpotEventInfo
TpcTpotEventInfo ()=default
Detailed Description
Version 1 of TpcTpotEventInfo.
Definition at line 21 of file TpcTpotEventInfov1.h.
View newest version in sPHENIX GitHub at line 21 of file TpcTpotEventInfov1.h
Constructor & Destructor Documentation
TpcTpotEventInfov1::TpcTpotEventInfov1 ()
ctor
Definition at line 13 of file TpcTpotEventInfov1.cc.
View newest version in sPHENIX GitHub at line 13 of file TpcTpotEventInfov1.cc
References m_bco, m_endat_count, m_last_bco, m_lvl1_count, and m_modebits.
Referenced by CloneMe().
TpcTpotEventInfov1::~TpcTpotEventInfov1 () override default
dtor
Member Function Documentation
void TpcTpotEventInfov1::checkIndexes (SectorID sector, PCIeEndPointID PCIe, TaggerID tagger) override virtual
Reimplemented from TpcTpotEventInfo.
Definition at line 71 of file TpcTpotEventInfov1.cc.
View newest version in sPHENIX GitHub at line 71 of file TpcTpotEventInfov1.cc
References assert, TpcTpotEventInfo::kEnDatTagger, TpcTpotEventInfo::kEndPoint0, TpcTpotEventInfo::kEndPoint1, TpcTpotEventInfo::kLVL1Tagger, TpcTpotEventInfo::kTPCSector0, and TpcTpotEventInfo::kTPOT.
PHObject* TpcTpotEventInfov1::CloneMe () const inline override virtual
Virtual copy constructor.
Reimplemented from PHObject.
Definition at line 40 of file TpcTpotEventInfov1.h.
View newest version in sPHENIX GitHub at line 40 of file TpcTpotEventInfov1.h
References TpcTpotEventInfov1().
void TpcTpotEventInfov1::CopyFrom (const TpcTpotEventInfo & source) override virtual
copy content from base class
Reimplemented from TpcTpotEventInfo.
Definition at line 47 of file TpcTpotEventInfov1.cc.
View newest version in sPHENIX GitHub at line 47 of file TpcTpotEventInfov1.cc
References TpcTpotEventInfo::CopyFrom(), TpcTpotEventInfo::getBCO(), TpcTpotEventInfo::getEnDatCount(), TpcTpotEventInfo::getLastBCO(), TpcTpotEventInfo::getLevel1Count(), TpcTpotEventInfo::getModebits(), i, j, k, setBCO(), setEnDatCount(), setLastBCO(), setLevel1Count(), and setModebits().
void TpcTpotEventInfov1::CopyFrom (TpcTpotEventInfo * source) inline override virtual
copy content from base class
Reimplemented from TpcTpotEventInfo.
Definition at line 46 of file TpcTpotEventInfov1.h.
View newest version in sPHENIX GitHub at line 46 of file TpcTpotEventInfov1.h
References CopyFrom().
Referenced by CopyFrom().
uint64_t TpcTpotEventInfov1::getBCO (SectorID sector, PCIeEndPointID PCIe, TaggerID tagger) const inline override virtual
Reimplemented from TpcTpotEventInfo.
Definition at line 55 of file TpcTpotEventInfov1.h.
View newest version in sPHENIX GitHub at line 55 of file TpcTpotEventInfov1.h
References m_bco.
uint32_t TpcTpotEventInfov1::getEnDatCount (SectorID sector, PCIeEndPointID PCIe, TaggerID tagger) const inline override virtual
Reimplemented from TpcTpotEventInfo.
Definition at line 59 of file TpcTpotEventInfov1.h.
View newest version in sPHENIX GitHub at line 59 of file TpcTpotEventInfov1.h
References m_endat_count.
uint64_t TpcTpotEventInfov1::getLastBCO (SectorID sector, PCIeEndPointID PCIe, TaggerID tagger) const inline override virtual
Reimplemented from TpcTpotEventInfo.
Definition at line 61 of file TpcTpotEventInfov1.h.
View newest version in sPHENIX GitHub at line 61 of file TpcTpotEventInfov1.h
References m_last_bco.
uint32_t TpcTpotEventInfov1::getLevel1Count (SectorID sector, PCIeEndPointID PCIe, TaggerID tagger) const inline override virtual
Reimplemented from TpcTpotEventInfo.
Definition at line 57 of file TpcTpotEventInfov1.h.
View newest version in sPHENIX GitHub at line 57 of file TpcTpotEventInfov1.h
References m_lvl1_count.
uint8_t TpcTpotEventInfov1::getModebits (SectorID sector, PCIeEndPointID PCIe, TaggerID tagger) const inline override virtual
Reimplemented from TpcTpotEventInfo.
Definition at line 63 of file TpcTpotEventInfov1.h.
View newest version in sPHENIX GitHub at line 63 of file TpcTpotEventInfov1.h
References m_modebits.
void TpcTpotEventInfov1::identify (std::ostream & os = std::cout) const override virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from TpcTpotEventInfo.
Definition at line 22 of file TpcTpotEventInfov1.cc.
View newest version in sPHENIX GitHub at line 22 of file TpcTpotEventInfov1.cc
References i, m_bco, m_endat_count, m_last_bco, m_lvl1_count, and m_modebits.
int TpcTpotEventInfov1::isValid () const override virtual
isValid returns non zero if object contains vailid data
Reimplemented from TpcTpotEventInfo.
Definition at line 42 of file TpcTpotEventInfov1.cc.
View newest version in sPHENIX GitHub at line 42 of file TpcTpotEventInfov1.cc
void TpcTpotEventInfov1::Reset () inline override virtual
Clear Event.
Reimplemented from TpcTpotEventInfo.
Definition at line 31 of file TpcTpotEventInfov1.h.
View newest version in sPHENIX GitHub at line 31 of file TpcTpotEventInfov1.h
References m_bco, m_endat_count, m_last_bco, m_lvl1_count, and m_modebits.
void TpcTpotEventInfov1::setBCO (uint64_t bco, SectorID sector, PCIeEndPointID PCIe, TaggerID tagger) inline override virtual
Reimplemented from TpcTpotEventInfo.
Definition at line 56 of file TpcTpotEventInfov1.h.
View newest version in sPHENIX GitHub at line 56 of file TpcTpotEventInfov1.h
References m_bco.
Referenced by CopyFrom().
void TpcTpotEventInfov1::setEnDatCount (uint32_t endatcount, SectorID sector, PCIeEndPointID PCIe, TaggerID tagger) inline override virtual
Reimplemented from TpcTpotEventInfo.
Definition at line 60 of file TpcTpotEventInfov1.h.
View newest version in sPHENIX GitHub at line 60 of file TpcTpotEventInfov1.h
References m_endat_count.
Referenced by CopyFrom().
void TpcTpotEventInfov1::setLastBCO (uint64_t lastbco, SectorID sector, PCIeEndPointID PCIe, TaggerID tagger) inline override virtual
Reimplemented from TpcTpotEventInfo.
Definition at line 62 of file TpcTpotEventInfov1.h.
View newest version in sPHENIX GitHub at line 62 of file TpcTpotEventInfov1.h
References m_last_bco.
Referenced by CopyFrom().
void TpcTpotEventInfov1::setLevel1Count (uint32_t lvl1count, SectorID sector, PCIeEndPointID PCIe, TaggerID tagger) inline override virtual
Reimplemented from TpcTpotEventInfo.
Definition at line 58 of file TpcTpotEventInfov1.h.
View newest version in sPHENIX GitHub at line 58 of file TpcTpotEventInfov1.h
References m_lvl1_count.
Referenced by CopyFrom().
void TpcTpotEventInfov1::setModebits (uint8_t modebits, SectorID sector, PCIeEndPointID PCIe, TaggerID tagger) inline override virtual
Reimplemented from TpcTpotEventInfo.
Definition at line 64 of file TpcTpotEventInfov1.h.
View newest version in sPHENIX GitHub at line 64 of file TpcTpotEventInfov1.h
References m_modebits.
Referenced by CopyFrom().
Member Data Documentation
uint64_t TpcTpotEventInfov1::m_bco[25][2][2] {} protected
Definition at line 68 of file TpcTpotEventInfov1.h.
View newest version in sPHENIX GitHub at line 68 of file TpcTpotEventInfov1.h
Referenced by getBCO(), identify(), Reset(), setBCO(), and TpcTpotEventInfov1().
uint32_t TpcTpotEventInfov1::m_endat_count[25][2][2] {} protected
Definition at line 70 of file TpcTpotEventInfov1.h.
View newest version in sPHENIX GitHub at line 70 of file TpcTpotEventInfov1.h
Referenced by getEnDatCount(), identify(), Reset(), setEnDatCount(), and TpcTpotEventInfov1().
uint64_t TpcTpotEventInfov1::m_last_bco[25][2][2] {} protected
Definition at line 71 of file TpcTpotEventInfov1.h.
View newest version in sPHENIX GitHub at line 71 of file TpcTpotEventInfov1.h
Referenced by getLastBCO(), identify(), Reset(), setLastBCO(), and TpcTpotEventInfov1().
uint32_t TpcTpotEventInfov1::m_lvl1_count[25][2][2] {} protected
Definition at line 69 of file TpcTpotEventInfov1.h.
View newest version in sPHENIX GitHub at line 69 of file TpcTpotEventInfov1.h
Referenced by getLevel1Count(), identify(), Reset(), setLevel1Count(), and TpcTpotEventInfov1().
uint8_t TpcTpotEventInfov1::m_modebits[25][2][2] {} protected
Definition at line 72 of file TpcTpotEventInfov1.h.
View newest version in sPHENIX GitHub at line 72 of file TpcTpotEventInfov1.h
Referenced by getModebits(), identify(), Reset(), setModebits(), and TpcTpotEventInfov1().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/trackbase/TpcTpotEventInfov1.h
coresoftware/blob/master/offline/packages/trackbase/TpcTpotEventInfov1.cc