Analysis Software: Acts::Experimental::detail Namespace Reference
Acts::Experimental::detail Namespace Reference
Namespaces
namespace BlueprintHelper
namespace CylindricalDetectorHelper
namespace GridAxisGenerators
namespace PortalHelper
namespace SupportHelper
This file contains helper methods to build common support structures such as support cylinders or discs.
Classes
struct IndexedGridFiller
A helper class that fills surfaces into predefined grids.
struct IndexedSurfacesGenerator
A templated indexed grid generator.
struct CenterReferenceGenerator
struct BinningValueReferenceGenerator
struct PolyhedronReferenceGenerator
Functions
std::vector< std::size_t > binSequence (std::array< std::size_t, 2u > minMaxBins, std::size_t expand, std::size_t nBins, Acts::detail::AxisBoundaryType type)
Helper method to generate completely populated bin sequences that respect the boundary type of the axis.
template<typename grid_type >
std::set< typename
grid_type::index_t > localIndices (const grid_type &grid, const std::vector< typename grid_type::point_t > &queries, const std::vector< std::size_t > &expansion={})
Helper method to fill local bins given a set of query points bin in between the extra points are filled, and a possible expansion of the bin window can be chosen.
template<typename local_bin >
std::string outputIndices (const std::set< local_bin > &lbins)
Helper method to screen output the local bins.
Function Documentation
std::vector< std::size_t > Acts::Experimental::detail::binSequence (std::array< std::size_t, 2u > minMaxBins, std::size_t expand, std::size_t nBins, Acts::detail::AxisBoundaryType type)
Helper method to generate completely populated bin sequences that respect the boundary type of the axis.
Parameters
minMaxBins estimated bin range (aka binning boundary box)
expand the parameter to expand the view (extra window)
nBins the maximum number of bins on this axis
type the boundary type of the axis (for correct bin closure)
Note
for closed binning a span over half the bins flips direction
Returns
a vector of bins to be filled
Helper method to fill a range
Parameters
lmin the minimum bin
lmax the maximum bin
Definition at line 28 of file IndexedGridFiller.cpp.
View newest version in sPHENIX GitHub at line 28 of file IndexedGridFiller.cpp
References KFPMath::b, Acts::Experimental::detail::BlueprintHelper::sort(), and physmon_ckf_tracking::u.
Referenced by BOOST_AUTO_TEST_CASE().
template<typename grid_type > std::set<typename grid_type::index_t> Acts::Experimental::detail::localIndices (const grid_type & grid, const std::vector< typename grid_type::point_t > & queries, const std::vector< std::size_t > & expansion = {})
Helper method to fill local bins given a set of query points bin in between the extra points are filled, and a possible expansion of the bin window can be chosen.
Template Parameters
grid_type the type of the grid that determines locall binning
Parameters
grid the grid used for this
queries the grid positions for the bin queries
expansion are the additional (configured) number of bins to expand the view
Returns
a set of unique indices
These are the axis bounds type parameters - for correct bin sequences
Definition at line 60 of file IndexedGridFiller.hpp.
View newest version in sPHENIX GitHub at line 60 of file IndexedGridFiller.hpp
Referenced by Acts::detail::grid_helper::closestPointsIndices(), Acts::detail::grid_helper_impl< N >::getBinCenter(), Acts::detail::grid_helper_impl< 0u >::getBinCenter(), Acts::detail::grid_helper::getBinCenter(), Acts::detail::grid_helper_impl< N >::getLowerLeftBinEdge(), Acts::detail::grid_helper_impl< 0u >::getLowerLeftBinEdge(), Acts::detail::grid_helper::getLowerLeftBinEdge(), Acts::detail::grid_helper_impl< N >::getLowerLeftBinIndices(), Acts::detail::grid_helper_impl< 0u >::getLowerLeftBinIndices(), Acts::detail::grid_helper::getLowerLeftBinIndices(), Acts::detail::grid_helper_impl< N >::getUpperRightBinEdge(), Acts::detail::grid_helper_impl< 0u >::getUpperRightBinEdge(), Acts::detail::grid_helper::getUpperRightBinEdge(), Acts::detail::grid_helper_impl< N >::getUpperRightBinIndices(), Acts::detail::grid_helper_impl< 0u >::getUpperRightBinIndices(), Acts::detail::grid_helper::getUpperRightBinIndices(), Acts::detail::grid_helper_impl< N >::neighborHoodIndices(), Acts::detail::grid_helper_impl< 0u >::neighborHoodIndices(), Acts::detail::grid_helper::neighborHoodIndices(), and Acts::detail::GlobalNeighborHoodIndices< DIM >::iterator::operator++().
template<typename local_bin > std::string Acts::Experimental::detail::outputIndices (const std::set< local_bin > & lbins)
Helper method to screen output the local bins.
Template Parameters
local_bin the type of the local bins
Parameters
lbins the local bins
Returns
a string containing the local bins ordered in a set
Definition at line 141 of file IndexedGridFiller.hpp.
View newest version in sPHENIX GitHub at line 141 of file IndexedGridFiller.hpp
References KFPMath::b, Acts::enumerate(), add_histos_bX::ib, to_string(), and physmon_ckf_tracking::u.