Analysis Software: ActsExamples::ReadDataHandle< T > Exception Template Reference
ActsExamples::ReadDataHandle< T > Exception Template Reference final
#include <acts/blob/sPHENIX/Examples/Framework/include/ActsExamples/Framework/DataHandle.hpp>
Public Member Functions
ReadDataHandle (SequenceElement *parent, const std::string &name)
void initialize (const std::string &key)
const T & operator() (const AlgorithmContext &ctx) const
const T & operator() (const WhiteBoard &wb) const
bool isCompatible (const DataHandleBase &other) const override
const std::type_info & typeInfo () const override
Public Member Functions inherited from ActsExamples::DataHandleBase
const std::string & key () const
bool isInitialized () const
const std::string & name () const
void maybeInitialize (const std::string &key)
std::string fullName () const
Additional Inherited Members
Protected Member Functions inherited from ActsExamples::DataHandleBase
virtual ~DataHandleBase ()=default
DataHandleBase (SequenceElement *parent, const std::string &name)
DataHandleBase (const DataHandleBase &)=delete
DataHandleBase (DataHandleBase &&)=default
Protected Attributes inherited from ActsExamples::DataHandleBase
SequenceElement * m_parent {nullptr}
std::string m_name
std::optional< std::string > m_key {}
Detailed Description
template<typename T>
exception ActsExamples::ReadDataHandle< T >
Definition at line 96 of file DataHandle.hpp.
View newest version in sPHENIX GitHub at line 96 of file DataHandle.hpp
Constructor & Destructor Documentation
template<typename T> ActsExamples::ReadDataHandle< T >::ReadDataHandle (SequenceElement * parent, const std::string & name) inline
Definition at line 98 of file DataHandle.hpp.
View newest version in sPHENIX GitHub at line 98 of file DataHandle.hpp
Member Function Documentation
template<typename T> void ActsExamples::ReadDataHandle< T >::initialize (const std::string & key) inline
Definition at line 103 of file DataHandle.hpp.
View newest version in sPHENIX GitHub at line 103 of file DataHandle.hpp
Referenced by ActsExamples::TrackFinderPerformanceWriter::Impl::_logger(), ActsExamples::AlignmentAlgorithm::AlignmentAlgorithm(), ActsExamples::AmbiguityResolutionMLAlgorithm::AmbiguityResolutionMLAlgorithm(), ActsExamples::AmbiguityResolutionMLDBScanAlgorithm::AmbiguityResolutionMLDBScanAlgorithm(), ActsExamples::CKFPerformanceWriter::CKFPerformanceWriter(), ActsExamples::CsvMeasurementWriter::CsvMeasurementWriter(), ActsExamples::CsvMultiTrajectoryWriter::CsvMultiTrajectoryWriter(), ActsExamples::CsvPlanarClusterWriter::CsvPlanarClusterWriter(), ActsExamples::CsvProtoTrackWriter::CsvProtoTrackWriter(), ActsExamples::DigitizationAlgorithm::DigitizationAlgorithm(), ActsExamples::EDM4hepMultiTrajectoryWriter::EDM4hepMultiTrajectoryWriter(), ActsExamples::EventRecording::EventRecording(), ActsExamples::FatrasSimulation::FatrasSimulation(), ActsExamples::Geant4MaterialRecording::Geant4MaterialRecording(), ActsExamples::Geant4Simulation::Geant4Simulation(), Acts::Test::getFromWhiteBoard(), ActsExamples::GreedyAmbiguityResolutionAlgorithm::GreedyAmbiguityResolutionAlgorithm(), ActsExamples::HelloWhiteBoardAlgorithm::HelloWhiteBoardAlgorithm(), ActsExamples::HepMCProcessExtractor::HepMCProcessExtractor(), ActsExamples::HitsPrinter::HitsPrinter(), ActsExamples::HoughTransformSeeder::HoughTransformSeeder(), ActsExamples::MaterialMapping::MaterialMapping(), ActsExamples::MeasurementMapSelector::MeasurementMapSelector(), ActsExamples::ParticleSelector::ParticleSelector(), ActsExamples::ParticleSmearing::ParticleSmearing(), ActsExamples::ParticlesPrinter::ParticlesPrinter(), ActsExamples::PlanarSteppingAlgorithm::PlanarSteppingAlgorithm(), ActsExamples::PrototracksToParameters::PrototracksToParameters(), ActsExamples::PrototracksToSeeds::PrototracksToSeeds(), ActsExamples::RefittingAlgorithm::RefittingAlgorithm(), ActsExamples::RootMeasurementWriter::RootMeasurementWriter(), ActsExamples::RootPlanarClusterWriter::RootPlanarClusterWriter(), ActsExamples::RootTrackParameterWriter::RootTrackParameterWriter(), ActsExamples::RootTrajectoryStatesWriter::RootTrajectoryStatesWriter(), ActsExamples::RootTrajectorySummaryWriter::RootTrajectorySummaryWriter(), ActsExamples::SeedingFTFAlgorithm::SeedingFTFAlgorithm(), ActsExamples::SeedingPerformanceWriter::SeedingPerformanceWriter(), ActsExamples::SeedsToPrototracks::SeedsToPrototracks(), ActsExamples::SingleSeedVertexFinderAlgorithm::SingleSeedVertexFinderAlgorithm(), ActsExamples::SpacePointMaker::SpacePointMaker(), ActsExamples::SurfaceSortingAlgorithm::SurfaceSortingAlgorithm(), ActsExamples::TrackFindingAlgorithmExaTrkX::TrackFindingAlgorithmExaTrkX(), ActsExamples::TrackFindingFromPrototrackAlgorithm::TrackFindingFromPrototrackAlgorithm(), ActsExamples::TrackFitterPerformanceWriter::TrackFitterPerformanceWriter(), ActsExamples::TrackFittingAlgorithm::TrackFittingAlgorithm(), ActsExamples::TrackParameterSelector::TrackParameterSelector(), ActsExamples::TrackParametersPrinter::TrackParametersPrinter(), ActsExamples::TrackParamsEstimationAlgorithm::TrackParamsEstimationAlgorithm(), ActsExamples::TrackSelectorAlgorithm::TrackSelectorAlgorithm(), ActsExamples::TracksToTrajectories::TracksToTrajectories(), ActsExamples::TrajectoriesToPrototracks::TrajectoriesToPrototracks(), ActsExamples::TruthSeedingAlgorithm::TruthSeedingAlgorithm(), ActsExamples::TruthSeedSelector::TruthSeedSelector(), ActsExamples::TruthTrackFinder::TruthTrackFinder(), ActsExamples::TruthVertexFinder::TruthVertexFinder(), ActsExamples::VertexFitterAlgorithm::VertexFitterAlgorithm(), ActsExamples::VertexPerformanceWriter::VertexPerformanceWriter(), and ActsExamples::WriterT< write_data_t >::WriterT().
template<typename T> bool ActsExamples::ReadDataHandle< T >::isCompatible (const DataHandleBase & other) const inline override virtual
Implements ActsExamples::DataHandleBase.
Definition at line 123 of file DataHandle.hpp.
View newest version in sPHENIX GitHub at line 123 of file DataHandle.hpp
template<typename T> const T& ActsExamples::ReadDataHandle< T >::operator() (const AlgorithmContext & ctx) const inline
Definition at line 111 of file DataHandle.hpp.
View newest version in sPHENIX GitHub at line 111 of file DataHandle.hpp
template<typename T> const T& ActsExamples::ReadDataHandle< T >::operator() (const WhiteBoard & wb) const inline
Definition at line 115 of file DataHandle.hpp.
View newest version in sPHENIX GitHub at line 115 of file DataHandle.hpp
template<typename T> const std::type_info& ActsExamples::ReadDataHandle< T >::typeInfo () const inline override virtual
Implements ActsExamples::DataHandleBase.
Definition at line 127 of file DataHandle.hpp.
View newest version in sPHENIX GitHub at line 127 of file DataHandle.hpp
The documentation for this exception was generated from the following file:
acts/blob/sPHENIX/Examples/Framework/include/ActsExamples/Framework/DataHandle.hpp