Analysis Software: ActsExamples::HepMCProcessExtractor Exception Reference
ActsExamples::HepMCProcessExtractor Exception Reference final
This class extracts a certain process from a HepMC event record.
#include <acts/blob/sPHENIX/Examples/Algorithms/HepMC/include/ActsExamples/HepMC/HepMCProcessExtractor.hpp>
Classes
class Config
Public Member Functions
HepMCProcessExtractor (Config config, Acts::Logging::Level level)
~HepMCProcessExtractor () override
ActsExamples::ProcessCode execute (const AlgorithmContext &context) const override
const Config & config () const
Get readonly access to the config parameters.
Public Member Functions inherited from ActsExamples::IAlgorithm
IAlgorithm (std::string name, Acts::Logging::Level level=Acts::Logging::INFO)
std::string name () const override
The algorithm name.
ProcessCode internalExecute (const AlgorithmContext &context) final
ProcessCode initialize () override
Initialize the algorithm.
ProcessCode finalize () override
Finalize the algorithm.
Private Attributes
Config m_cfg
The config object.
ReadDataHandle< std::vector
< HepMC3::GenEvent > > m_inputEvents
WriteDataHandle
< ActsExamples::ExtractedSimulationProcessContainer > m_outputSimulationProcesses {this, "OutputSimulationProcesses"}
Additional Inherited Members
Protected Member Functions inherited from ActsExamples::IAlgorithm
const Acts::Logger & logger () const
Detailed Description
This class extracts a certain process from a HepMC event record.
Definition at line 31 of file HepMCProcessExtractor.hpp.
View newest version in sPHENIX GitHub at line 31 of file HepMCProcessExtractor.hpp
Constructor & Destructor Documentation
ActsExamples::HepMCProcessExtractor::HepMCProcessExtractor (Config config, Acts::Logging::Level level)
Constructor
Parameters
config the configuration
level the log level
Definition at line 180 of file HepMCProcessExtractor.cpp.
View newest version in sPHENIX GitHub at line 180 of file HepMCProcessExtractor.cpp
References ActsExamples::HepMCProcessExtractor::Config::extractionProcess, ActsExamples::WriteDataHandle< T >::initialize(), ActsExamples::ReadDataHandle< T >::initialize(), ActsExamples::HepMCProcessExtractor::Config::inputEvents, m_cfg, m_inputEvents, m_outputSimulationProcesses, and ActsExamples::HepMCProcessExtractor::Config::outputSimulationProcesses.
ActsExamples::HepMCProcessExtractor::~HepMCProcessExtractor () override default
Member Function Documentation
const Config& ActsExamples::HepMCProcessExtractor::config () const inline
Get readonly access to the config parameters.
Definition at line 60 of file HepMCProcessExtractor.hpp.
View newest version in sPHENIX GitHub at line 60 of file HepMCProcessExtractor.hpp
References m_cfg.
ActsExamples::ProcessCode ActsExamples::HepMCProcessExtractor::execute (const AlgorithmContext & context) const override virtual
Execute the algorithm for one event.
This function must be implemented by subclasses.
Implements ActsExamples::IAlgorithm.
Definition at line 199 of file HepMCProcessExtractor.cpp.
View newest version in sPHENIX GitHub at line 199 of file HepMCProcessExtractor.cpp
References ACTS_INFO, event, physmon_vertexing::events, m_cfg(), testing::internal::move(), ActsExamples::HepMC3Particle::particle(), and SUCCESS.
Member Data Documentation
Config ActsExamples::HepMCProcessExtractor::m_cfg private
The config object.
Definition at line 64 of file HepMCProcessExtractor.hpp.
View newest version in sPHENIX GitHub at line 64 of file HepMCProcessExtractor.hpp
Referenced by config(), and HepMCProcessExtractor().
ReadDataHandle<std::vector<HepMC3::GenEvent> > ActsExamples::HepMCProcessExtractor::m_inputEvents private
Initial value:
{this,
                                                              "InputEvents"}
Definition at line 66 of file HepMCProcessExtractor.hpp.
View newest version in sPHENIX GitHub at line 66 of file HepMCProcessExtractor.hpp
Referenced by HepMCProcessExtractor().
WriteDataHandle<ActsExamples::ExtractedSimulationProcessContainer> ActsExamples::HepMCProcessExtractor::m_outputSimulationProcesses {this, "OutputSimulationProcesses"} private
Definition at line 69 of file HepMCProcessExtractor.hpp.
View newest version in sPHENIX GitHub at line 69 of file HepMCProcessExtractor.hpp
Referenced by HepMCProcessExtractor().
The documentation for this exception was generated from the following files:
acts/blob/sPHENIX/Examples/Algorithms/HepMC/include/ActsExamples/HepMC/HepMCProcessExtractor.hpp
acts/blob/sPHENIX/Examples/Algorithms/HepMC/src/HepMCProcessExtractor.cpp