Analysis Software: TowerInfov2 Class Reference
TowerInfov2 Class Reference
#include <coresoftware/blob/master/offline/packages/CaloBase/TowerInfov2.h>
Public Member Functions
TowerInfov2 ()
~TowerInfov2 () override
void Reset () override
Clear Event.
void Clear (Option_t *="") override
void set_time (short t) override
short get_time () override
void set_time_float (float t) override
float get_time_float () override
void set_chi2 (float chi2) override
float get_chi2 () override
void set_pedestal (float pedestal) override
float get_pedestal () override
void set_isHot (bool isHot) override
bool get_isHot () const override
void set_isBadTime (bool isBadTime) override
bool get_isBadTime () const override
void set_isBadChi2 (bool isBadChi2) override
bool get_isBadChi2 () const override
void set_isNotInstr (bool isNotInstr) override
bool get_isNotInstr () const override
void set_isNoCalib (bool isNoCalib) override
bool get_isNoCalib () const override
bool get_isGood () const override
uint8_t get_status () const override
void set_status (uint8_t status) override
void copy_tower (TowerInfo *tower) override
Public Member Functions inherited from TowerInfov1
TowerInfov1 ()
TowerInfov1 (TowerInfo &tower)
~TowerInfov1 () override
void Clear (Option_t *="") override
Clear is used by TClonesArray to reset the tower to initial state without calling destructor/constructor.
void set_energy (float energy) override
float get_energy () override
Public Member Functions inherited from TowerInfo
TowerInfo ()=default
~TowerInfo () override=default
virtual int get_nsample () const
virtual int16_t get_waveform_value (int) const
virtual void set_waveform_value (int, int16_t)
Public Member Functions inherited from PHObject
PHObject ()
ctor
~PHObject () override
dtor
virtual PHObject * CloneMe () const
Virtual copy constructor.
virtual PHObject * clone () const final
PHObject * Clone (const char *newname="") const final
void Copy (TObject &object) const final
virtual void identify (std::ostream &os=std::cout) const
virtual int isValid () const
isValid returns non zero if object contains vailid data
virtual int Integrate () const
virtual int Integrate (PHObject *)
virtual void CopyFrom (const PHObject *obj)
Private Member Functions
void set_status_bit (int bit, bool value)
bool get_status_bit (int bit) const
ClassDefOverride (TowerInfov2, 1)
Private Attributes
float _chi2 = 0
float _pedestal = 0
uint8_t _status = 0
Detailed Description
Definition at line 7 of file TowerInfov2.h.
View newest version in sPHENIX GitHub at line 7 of file TowerInfov2.h
Constructor & Destructor Documentation
TowerInfov2::TowerInfov2 () inline
Definition at line 10 of file TowerInfov2.h.
View newest version in sPHENIX GitHub at line 10 of file TowerInfov2.h
TowerInfov2::~TowerInfov2 () inline override
Definition at line 12 of file TowerInfov2.h.
View newest version in sPHENIX GitHub at line 12 of file TowerInfov2.h
Member Function Documentation
TowerInfov2::ClassDefOverride (TowerInfov2 , 1) private
void TowerInfov2::Clear (Option_t * = "") override
Definition at line 12 of file TowerInfov2.cc.
View newest version in sPHENIX GitHub at line 12 of file TowerInfov2.cc
References _chi2, _pedestal, _status, and TowerInfov1::Clear().
Referenced by TowerInfov3::Clear().
void TowerInfov2::copy_tower (TowerInfo * tower) override virtual
Reimplemented from TowerInfov1.
Reimplemented in TowerInfov3.
Definition at line 20 of file TowerInfov2.cc.
View newest version in sPHENIX GitHub at line 20 of file TowerInfov2.cc
References TowerInfov1::copy_tower(), TowerInfo::get_chi2(), TowerInfo::get_energy(), TowerInfo::get_pedestal(), TowerInfo::get_status(), TowerInfo::get_time_float(), set_chi2(), TowerInfov1::set_energy(), set_pedestal(), set_status(), and set_time_float().
Referenced by TowerInfov3::copy_tower().
float TowerInfov2::get_chi2 () inline override virtual
Reimplemented from TowerInfo.
Definition at line 23 of file TowerInfov2.h.
View newest version in sPHENIX GitHub at line 23 of file TowerInfov2.h
References _chi2.
bool TowerInfov2::get_isBadChi2 () const inline override virtual
Reimplemented from TowerInfo.
Definition at line 34 of file TowerInfov2.h.
View newest version in sPHENIX GitHub at line 34 of file TowerInfov2.h
References get_status_bit().
bool TowerInfov2::get_isBadTime () const inline override virtual
Reimplemented from TowerInfo.
Definition at line 31 of file TowerInfov2.h.
View newest version in sPHENIX GitHub at line 31 of file TowerInfov2.h
References get_status_bit().
bool TowerInfov2::get_isGood () const inline override virtual
Reimplemented from TowerInfo.
Definition at line 42 of file TowerInfov2.h.
View newest version in sPHENIX GitHub at line 42 of file TowerInfov2.h
References _status.
bool TowerInfov2::get_isHot () const inline override virtual
Reimplemented from TowerInfo.
Definition at line 28 of file TowerInfov2.h.
View newest version in sPHENIX GitHub at line 28 of file TowerInfov2.h
References get_status_bit().
bool TowerInfov2::get_isNoCalib () const inline override virtual
Reimplemented from TowerInfo.
Definition at line 40 of file TowerInfov2.h.
View newest version in sPHENIX GitHub at line 40 of file TowerInfov2.h
References get_status_bit().
bool TowerInfov2::get_isNotInstr () const inline override virtual
Reimplemented from TowerInfo.
Definition at line 37 of file TowerInfov2.h.
View newest version in sPHENIX GitHub at line 37 of file TowerInfov2.h
References get_status_bit().
float TowerInfov2::get_pedestal () inline override virtual
Reimplemented from TowerInfo.
Definition at line 25 of file TowerInfov2.h.
View newest version in sPHENIX GitHub at line 25 of file TowerInfov2.h
References _pedestal.
uint8_t TowerInfov2::get_status () const inline override virtual
Reimplemented from TowerInfo.
Definition at line 44 of file TowerInfov2.h.
View newest version in sPHENIX GitHub at line 44 of file TowerInfov2.h
References _status.
bool TowerInfov2::get_status_bit (int bit) const inline private
Definition at line 65 of file TowerInfov2.h.
View newest version in sPHENIX GitHub at line 65 of file TowerInfov2.h
References _status.
Referenced by get_isBadChi2(), get_isBadTime(), get_isHot(), get_isNoCalib(), and get_isNotInstr().
short TowerInfov2::get_time () inline override virtual
Reimplemented from TowerInfov1.
Definition at line 17 of file TowerInfov2.h.
View newest version in sPHENIX GitHub at line 17 of file TowerInfov2.h
References TowerInfov1::get_time().
float TowerInfov2::get_time_float () inline override virtual
Reimplemented from TowerInfo.
Definition at line 20 of file TowerInfov2.h.
View newest version in sPHENIX GitHub at line 20 of file TowerInfov2.h
References TowerInfov1::get_time().
void TowerInfov2::Reset () override virtual
Clear Event.
Reimplemented from TowerInfov1.
Reimplemented in TowerInfov3.
Definition at line 4 of file TowerInfov2.cc.
View newest version in sPHENIX GitHub at line 4 of file TowerInfov2.cc
References _chi2, _pedestal, _status, and TowerInfov1::Reset().
Referenced by TowerInfov3::Reset().
void TowerInfov2::set_chi2 (float chi2) inline override virtual
Reimplemented from TowerInfo.
Definition at line 22 of file TowerInfov2.h.
View newest version in sPHENIX GitHub at line 22 of file TowerInfov2.h
References _chi2.
Referenced by copy_tower().
void TowerInfov2::set_isBadChi2 (bool isBadChi2) inline override virtual
Reimplemented from TowerInfo.
Definition at line 33 of file TowerInfov2.h.
View newest version in sPHENIX GitHub at line 33 of file TowerInfov2.h
References set_status_bit().
void TowerInfov2::set_isBadTime (bool isBadTime) inline override virtual
Reimplemented from TowerInfo.
Definition at line 30 of file TowerInfov2.h.
View newest version in sPHENIX GitHub at line 30 of file TowerInfov2.h
References set_status_bit().
void TowerInfov2::set_isHot (bool isHot) inline override virtual
Reimplemented from TowerInfo.
Definition at line 27 of file TowerInfov2.h.
View newest version in sPHENIX GitHub at line 27 of file TowerInfov2.h
References set_status_bit().
void TowerInfov2::set_isNoCalib (bool isNoCalib) inline override virtual
Reimplemented from TowerInfo.
Definition at line 39 of file TowerInfov2.h.
View newest version in sPHENIX GitHub at line 39 of file TowerInfov2.h
References set_status_bit().
void TowerInfov2::set_isNotInstr (bool isNotInstr) inline override virtual
Reimplemented from TowerInfo.
Definition at line 36 of file TowerInfov2.h.
View newest version in sPHENIX GitHub at line 36 of file TowerInfov2.h
References set_status_bit().
void TowerInfov2::set_pedestal (float pedestal) inline override virtual
Reimplemented from TowerInfo.
Definition at line 24 of file TowerInfov2.h.
View newest version in sPHENIX GitHub at line 24 of file TowerInfov2.h
References _pedestal, and pedestal().
Referenced by copy_tower().
void TowerInfov2::set_status (uint8_t status) inline override virtual
Reimplemented from TowerInfo.
Definition at line 46 of file TowerInfov2.h.
View newest version in sPHENIX GitHub at line 46 of file TowerInfov2.h
References _status, and utils::status.
Referenced by copy_tower().
void TowerInfov2::set_status_bit (int bit, bool value) inline private
Definition at line 55 of file TowerInfov2.h.
View newest version in sPHENIX GitHub at line 55 of file TowerInfov2.h
References _status.
Referenced by set_isBadChi2(), set_isBadTime(), set_isHot(), set_isNoCalib(), and set_isNotInstr().
void TowerInfov2::set_time (short t) inline override virtual
Reimplemented from TowerInfov1.
Definition at line 16 of file TowerInfov2.h.
View newest version in sPHENIX GitHub at line 16 of file TowerInfov2.h
References TowerInfov1::set_time().
void TowerInfov2::set_time_float (float t) inline override virtual
Reimplemented from TowerInfo.
Definition at line 19 of file TowerInfov2.h.
View newest version in sPHENIX GitHub at line 19 of file TowerInfov2.h
References TowerInfov1::set_time().
Referenced by copy_tower().
Member Data Documentation
float TowerInfov2::_chi2 = 0 private
Definition at line 51 of file TowerInfov2.h.
View newest version in sPHENIX GitHub at line 51 of file TowerInfov2.h
Referenced by Clear(), get_chi2(), Reset(), and set_chi2().
float TowerInfov2::_pedestal = 0 private
Definition at line 52 of file TowerInfov2.h.
View newest version in sPHENIX GitHub at line 52 of file TowerInfov2.h
Referenced by Clear(), get_pedestal(), Reset(), and set_pedestal().
uint8_t TowerInfov2::_status = 0 private
Definition at line 53 of file TowerInfov2.h.
View newest version in sPHENIX GitHub at line 53 of file TowerInfov2.h
Referenced by Clear(), get_isGood(), get_status(), get_status_bit(), Reset(), set_status(), and set_status_bit().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/CaloBase/TowerInfov2.h
coresoftware/blob/master/offline/packages/CaloBase/TowerInfov2.cc