Analysis Software: epemGun Class Reference
epemGun Class Reference
#include <JETSCAPE/blob/main/src/initialstate/epemGun.h>
Public Member Functions
epemGun (string xmlDir="DONTUSETHIS", bool printBanner=false)
~epemGun ()
void InitTask ()
void Exec ()
double GetSigmaGen ()
double GetSigmaErr ()
double GetEventWeight ()
Public Member Functions inherited from Jetscape::HardProcess
HardProcess ()
virtual ~HardProcess ()
virtual void Init ()
virtual void Clear ()
virtual void WriteTask (weak_ptr< JetScapeWriter > w)
virtual void CollectHeader (weak_ptr< JetScapeWriter > w)
int GetNHardPartons ()
shared_ptr< Parton > GetPartonAt (int i)
vector< shared_ptr< Parton > > & GetPartonList ()
void AddParton (shared_ptr< Parton > p)
void GetHardPartonList (vector< shared_ptr< Parton >> &plist)
virtual double GetPtHat ()
void AddHadron (shared_ptr< Hadron > h)
void GetHadronList (vector< shared_ptr< Hadron >> &hlist)
vector< shared_ptr< Hadron > > & GetHadronList ()
int GetNHadrons ()
Public Member Functions inherited from Jetscape::JetScapeModuleBase
JetScapeModuleBase ()
JetScapeModuleBase (string m_name)
virtual ~JetScapeModuleBase ()
void SetXMLMainFileName (string m_name)
string GetXMLMainFileName ()
void SetXMLUserFileName (string m_name)
string GetXMLUserFileName ()
shared_ptr< std::mt19937 > GetMt19937Generator ()
tinyxml2::XMLElement * GetXMLElement (std::initializer_list< const char * > path, bool isRequired=true)
std::string GetXMLElementText (std::initializer_list< const char * > path, bool isRequired=true)
int GetXMLElementInt (std::initializer_list< const char * > path, bool isRequired=true)
double GetXMLElementDouble (std::initializer_list< const char * > path, bool isRequired=true)
Public Member Functions inherited from Jetscape::JetScapeTask
JetScapeTask ()
virtual ~JetScapeTask ()
virtual void Finish ()
virtual void ExecuteTasks ()
virtual void ExecuteTask ()
virtual void InitTasks ()
virtual void ClearTasks ()
virtual void ClearTask ()
virtual void FinishTask ()
virtual void FinishTasks ()
virtual void WriteTasks (weak_ptr< JetScapeWriter > w)
virtual void CollectHeaders (weak_ptr< JetScapeWriter > w)
virtual void Add (shared_ptr< JetScapeTask > m_tasks)
virtual const int GetMyTaskNumber () const
const vector< shared_ptr
< JetScapeTask > > GetTaskList () const
shared_ptr< JetScapeTask > GetTaskAt (int i)
void EraseTaskLast ()
void EraseTaskAt (int i)
void ResizeTaskList (int i)
void ClearTaskList ()
int GetNumberOfTasks ()
const bool GetActive () const
void SetActive (bool m_active_exec)
void SetId (string m_id)
const string GetId () const
const shared_ptr
< JetScapeModuleMutex > GetMutex () const
void SetMutex (shared_ptr< JetScapeModuleMutex > m_mutex)
Public Member Functions inherited from sigslot::has_slots< sigslot::multi_threaded_local >
has_slots ()
has_slots (const has_slots &hs)
void signal_connect (_signal_base< sigslot::multi_threaded_local > *sender)
void signal_disconnect (_signal_base< sigslot::multi_threaded_local > *sender)
virtual ~has_slots ()
void disconnect_all ()
Protected Attributes
std::uniform_real_distribution
< double > ZeroOneDistribution
Private Member Functions
double sud_val_QG_w_M (double M, double h0, double h1, double h2, double E1)
double sud_z_QG_w_M (double M, double cg, double cg1, double E2)
double alpha_s (double q2)
Private Attributes
double eCM
Static Private Attributes
static RegisterJetScapeModule
< epemGun > reg
Additional Inherited Members
Static Public Member Functions inherited from Jetscape::JetScapeModuleBase
static int GetCurrentEvent ()
static void IncrementCurrentEvent ()
Public Attributes inherited from Jetscape::HardProcess
std::shared_ptr< InitialState > ini
std::string printer
Detailed Description
Definition at line 27 of file epemGun.h.
View newest version in sPHENIX GitHub at line 27 of file epemGun.h
Constructor & Destructor Documentation
epemGun::epemGun (string xmlDir = "DONTUSETHIS", bool printBanner = false) inline
standard ctor
Parameters
xmlDir,: Note that the environment variable PYTHIA8DATA takes precedence! So don't use it.
printBanner,: Suppress starting blurb. Should be set to true in production, credit where it's due
Definition at line 50 of file epemGun.h.
View newest version in sPHENIX GitHub at line 50 of file epemGun.h
References SetId().
epemGun::~epemGun ()
Definition at line 28 of file epemGun.cc.
View newest version in sPHENIX GitHub at line 28 of file epemGun.cc
References VERBOSE.
Member Function Documentation
double epemGun::alpha_s (double q2) private
Definition at line 454 of file epemGun.cc.
View newest version in sPHENIX GitHub at line 454 of file epemGun.cc
References KFPMath::a, JSWARN, Jetscape::Lambda_QCD, Jetscape::Nc, Jetscape::nf, and pi.
void epemGun::Exec () virtual
Calls JetScapeTask::ExecuteTasks() for recursive execution of tasks attached to HardProcess module. It can be overridden by the attached module.
Reimplemented from Jetscape::HardProcess.
Definition at line 148 of file epemGun.cc.
View newest version in sPHENIX GitHub at line 148 of file epemGun.cc
References Jetscape::Cf, Acts::UnitConstants::e, Jetscape::fmToGeVinv, Acts::UnitConstants::g, i, j, mass, next, merge_hashes::p, particle, pi, QS, Jetscape::rounding_error, Jetscape::s_approx, Jetscape::s_error, Acts::Experimental::detail::BlueprintHelper::sort(), and VERBOSE.
double epemGun::GetEventWeight () inline virtual
Generated weight. This is in addition to sigmaGen, e.g. coming from dynamic oversampling. To be overwritten by implementations that have such information.
Reimplemented from Jetscape::HardProcess.
Definition at line 67 of file epemGun.h.
View newest version in sPHENIX GitHub at line 67 of file epemGun.h
double epemGun::GetSigmaErr () inline virtual
Generated cross section error. To be overwritten by implementations that have such information.
Reimplemented from Jetscape::HardProcess.
Definition at line 66 of file epemGun.h.
View newest version in sPHENIX GitHub at line 66 of file epemGun.h
double epemGun::GetSigmaGen () inline virtual
Generated cross section. To be overwritten by implementations that have such information.
Reimplemented from Jetscape::HardProcess.
Definition at line 65 of file epemGun.h.
View newest version in sPHENIX GitHub at line 65 of file epemGun.h
void epemGun::InitTask () virtual
A virtual function to define a default InitTask() function for a JetScapeTask. It can be overridden by different modules/tasks.
Reimplemented from Jetscape::JetScapeTask.
Definition at line 30 of file epemGun.cc.
View newest version in sPHENIX GitHub at line 30 of file epemGun.cc
References release::app, tinyxml2::XMLNode::FirstChildElement(), i, in, myAnalysis::init(), JSDEBUG, JSWARN, test_fpe::lines, out, tinyxml2::XMLElement::QueryUnsignedText(), physmon_simulation::s, seed, SetId(), and VERBOSE.
double epemGun::sud_val_QG_w_M (double M, double h0, double h1, double h2, double E1) private
Definition at line 377 of file epemGun.cc.
View newest version in sPHENIX GitHub at line 377 of file epemGun.cc
References Jetscape::approx, acts::error, h, h1, and h2.
double epemGun::sud_z_QG_w_M (double M, double cg, double cg1, double E2) private
Definition at line 408 of file epemGun.cc.
View newest version in sPHENIX GitHub at line 408 of file epemGun.cc
References Jetscape::E_minimum, JSINFO, MAGENTA, ambiguity_solver_full_chain::t1, ambiguity_solver_full_chain::t2, and ambiguity_solver_full_chain::t4.
Member Data Documentation
double epemGun::eCM private
Definition at line 32 of file epemGun.h.
View newest version in sPHENIX GitHub at line 32 of file epemGun.h
RegisterJetScapeModule< epemGun > epemGun::reg static private
Definition at line 36 of file epemGun.h.
View newest version in sPHENIX GitHub at line 36 of file epemGun.h
std::uniform_real_distribution<double> epemGun::ZeroOneDistribution protected
Definition at line 43 of file epemGun.h.
View newest version in sPHENIX GitHub at line 43 of file epemGun.h
The documentation for this class was generated from the following files:
JETSCAPE/blob/main/src/initialstate/epemGun.h
JETSCAPE/blob/main/src/initialstate/epemGun.cc