Analysis Software: DbForm Class Reference
DbForm Class Reference
Public Member Functions
DbForm ()
~DbForm ()
TSQLConnection * GetConnection () const
void SetForwardOnly ()
void SetConnection (TSQLConnection *con)
void SetStatement (TSQLStatement *stmt)
void Hide ()
void Show ()
TGMainFrame * GetMainFrame () const
void HandleFileMenu (Int_t id)
void HandleGotoMenu (Int_t id)
void HandleDisconnect ()
void HandleConnect ()
void HandleExecuteQuery ()
void First ()
void Last ()
void Next ()
void Prev ()
void AcceleratePrevButton ()
void AccelerateNextButton ()
void Connect (const Text_t *dsn, const Text_t *uid, const Text_t *pwd)
Private Types
enum EFile { kConnect, kDisconnect, kExit }
enum EGo {
kPrev, kNext, kFirst, kLast,
kAbsolute
}
enum EHelp { kAbout }
Private Member Functions
void DisplayResults ()
void UpdateColumn (Int_t index, const Text_t *value)
void ClearCanvas ()
Private Attributes
TGMainFrame * fMain
TGPopupMenu * fFileMenu
TGPopupMenu * fGotoMenu
TGPopupMenu * fHelpMenu
TGTextEntry * fQueryTextEntry
TGTextButton * fExecuteQueryButton
TGTextButton * fCancelQueryButton
TGTextButton * fNextButton
TGTextButton * fPrevButton
TGTextButton * fLastButton
TGTextButton * fFirstButton
TTimer * fNextButtonTimer
TTimer * fPrevButtonTimer
TGCompositeFrame * fButtonGroup
TGStatusBar * fStatusBar
TGMenuBar * fMenuBar
TGLayoutHints * fMenuBarLayout
TGLayoutHints * fMenuBarItemLayout
TGLayoutHints * fMenuBarHelpLayout
TGHorizontal3DLine * fToolBarSep
TGToolBar * fToolBar
TGLayoutHints * fBarLayout
TGLayoutHints * fQueryTextLayout
TGCanvas * fCanvasWindow
TGCompositeFrame * fContainer
DbFormEntry ** fEntries
PasswordDialog * fPD
Bool_t fConnected
TString fDSN
Int_t fRstype
Int_t fRsconc
TSQLConnection * fConnection
TSQLStatement * fStatement
TSQLResultSet * fResultSet
TSQLResultSetMetaData * fResultSetMetaData
Detailed Description
Definition at line 431 of file RDBCform.C.
View newest version in sPHENIX GitHub at line 431 of file RDBCform.C
Member Enumeration Documentation
enum DbForm::EFile private
Enumerator:
kConnect
kDisconnect
kExit
Definition at line 436 of file RDBCform.C.
View newest version in sPHENIX GitHub at line 436 of file RDBCform.C
enum DbForm::EGo private
Enumerator:
kPrev
kNext
kFirst
kLast
kAbsolute
Definition at line 437 of file RDBCform.C.
View newest version in sPHENIX GitHub at line 437 of file RDBCform.C
enum DbForm::EHelp private
Enumerator:
kAbout
Definition at line 438 of file RDBCform.C.
View newest version in sPHENIX GitHub at line 438 of file RDBCform.C
Constructor & Destructor Documentation
DbForm::DbForm ()
Definition at line 515 of file RDBCform.C.
View newest version in sPHENIX GitHub at line 515 of file RDBCform.C
References fBarLayout, fButtonGroup, fCancelQueryButton, fCanvasWindow, fConnected, fConnection, fContainer, fExecuteQueryButton, fFileMenu, fFirstButton, fGotoMenu, fHelpMenu, fLastButton, fMain, fMenuBar, fMenuBarHelpLayout, fMenuBarItemLayout, fMenuBarLayout, fNextButton, fNextButtonTimer, fPD, fPrevButton, fPrevButtonTimer, fQueryTextEntry, fResultSet, fResultSetMetaData, fStatement, fStatusBar, fToolBar, fToolBarSep, HandleDisconnect(), kAbout, kConnect, kDisconnect, kExit, kFirst, kLast, kNext, kPrev, and TSQL::SetHandler().
DbForm::~DbForm ()
Definition at line 679 of file RDBCform.C.
View newest version in sPHENIX GitHub at line 679 of file RDBCform.C
References fBarLayout, fButtonGroup, fCancelQueryButton, fCanvasWindow, fContainer, fExecuteQueryButton, fFileMenu, fFirstButton, fGotoMenu, fHelpMenu, fLastButton, fMain, fMenuBar, fMenuBarHelpLayout, fMenuBarItemLayout, fMenuBarLayout, fNextButton, fNextButtonTimer, fPD, fPrevButton, fPrevButtonTimer, fQueryTextEntry, fQueryTextLayout, fStatusBar, fToolBar, fToolBarSep, and HandleDisconnect().
Member Function Documentation
void DbForm::AccelerateNextButton ()
Definition at line 661 of file RDBCform.C.
View newest version in sPHENIX GitHub at line 661 of file RDBCform.C
References fNextButtonTimer.
void DbForm::AcceleratePrevButton ()
Definition at line 670 of file RDBCform.C.
View newest version in sPHENIX GitHub at line 670 of file RDBCform.C
References fPrevButtonTimer, and physmon_track_finding_ttbar::pt.
void DbForm::ClearCanvas () private
Definition at line 857 of file RDBCform.C.
View newest version in sPHENIX GitHub at line 857 of file RDBCform.C
References fCanvasWindow, fEntries, fResultSetMetaData, TSQLResultSetMetaData::GetColumnCount(), and i.
Referenced by HandleDisconnect(), and HandleExecuteQuery().
void DbForm::Connect (const Text_t * dsn, const Text_t * uid, const Text_t * pwd)
Definition at line 1014 of file RDBCform.C.
View newest version in sPHENIX GitHub at line 1014 of file RDBCform.C
References fConnected, fConnection, fDSN, fPD, TSQLDriverManager::GetConnection(), HandleConnect(), HandleDisconnect(), and PasswordDialog::Hide().
void DbForm::DisplayResults () private
Definition at line 762 of file RDBCform.C.
View newest version in sPHENIX GitHub at line 762 of file RDBCform.C
References fEntries, fGotoMenu, fNextButton, fPrevButton, fResultSet, fResultSetMetaData, fRstype, fStatusBar, TSQLResultSetMetaData::GetColumnCount(), TSQLResultSet::GetRow(), TSQLResultSet::GetString(), i, TSQLResultSet::IsAfterLast(), TSQLResultSet::IsBeforeFirst(), kNext, kPrev, kTYPE_FORWARD_ONLY, DbFormEntry::SetColumnValue(), SetForwardOnly(), and value.
Referenced by First(), Last(), Next(), and Prev().
void DbForm::First ()
Definition at line 726 of file RDBCform.C.
View newest version in sPHENIX GitHub at line 726 of file RDBCform.C
References DisplayResults(), TSQLResultSet::First(), and fResultSet.
Referenced by HandleGotoMenu().
TSQLConnection* DbForm::GetConnection () const inline
Definition at line 487 of file RDBCform.C.
View newest version in sPHENIX GitHub at line 487 of file RDBCform.C
References fConnection.
TGMainFrame* DbForm::GetMainFrame () const inline
Definition at line 495 of file RDBCform.C.
View newest version in sPHENIX GitHub at line 495 of file RDBCform.C
References fMain.
Referenced by Catch().
void DbForm::HandleConnect ()
Definition at line 981 of file RDBCform.C.
View newest version in sPHENIX GitHub at line 981 of file RDBCform.C
References fCancelQueryButton, fConnection, fDSN, fExecuteQueryButton, fFileMenu, fQueryTextEntry, fRsconc, fRstype, fStatusBar, TSQLConnection::GetMetaData(), kCONCUR_READ_ONLY, kCONCUR_UPDATABLE, kDisconnect, kTYPE_SCROLL_INSENSITIVE, kTYPE_SCROLL_SENSITIVE, SetForwardOnly(), TSQLDatabaseMetaData::SupportsResultSetConcurrency(), and TSQLDatabaseMetaData::SupportsResultSetType().
Referenced by Connect(), and SetConnection().
void DbForm::HandleDisconnect ()
Definition at line 952 of file RDBCform.C.
View newest version in sPHENIX GitHub at line 952 of file RDBCform.C
References ClearCanvas(), TSQLConnection::Close(), fCancelQueryButton, fConnected, fConnection, fExecuteQueryButton, fFileMenu, fFirstButton, fGotoMenu, fLastButton, fNextButton, fPrevButton, fQueryTextEntry, fResultSet, fResultSetMetaData, fStatement, fStatusBar, kDisconnect, kFirst, kLast, kNext, and kPrev.
Referenced by Connect(), DbForm(), HandleFileMenu(), and ~DbForm().
void DbForm::HandleExecuteQuery ()
Definition at line 879 of file RDBCform.C.
View newest version in sPHENIX GitHub at line 879 of file RDBCform.C
References ClearCanvas(), TSQLConnection::CreateStatement(), TSQLStatement::ExecuteQuery(), fCanvasWindow, fConnection, fEntries, fFirstButton, fGotoMenu, fLastButton, fMain, fMenuBarLayout, fNextButton, fPrevButton, fQueryTextEntry, fResultSet, fResultSetMetaData, fRsconc, fRstype, fStatement, fStatusBar, TSQLResultSetMetaData::GetColumnCount(), TSQLResultSetMetaData::GetColumnName(), TSQLResultSetMetaData::GetColumnType(), TSQLResultSet::GetMetaData(), TSQLResultSet::GetRow(), i, kFirst, kLast, kNext, kPrev, kTYPE_FORWARD_ONLY, SetForwardOnly(), and parse_cmake_options::type.
Referenced by SetStatement().
void DbForm::HandleFileMenu (Int_t id)
Definition at line 804 of file RDBCform.C.
View newest version in sPHENIX GitHub at line 804 of file RDBCform.C
References fConnected, fPD, HandleDisconnect(), kConnect, kDisconnect, kExit, and PasswordDialog::Show().
void DbForm::HandleGotoMenu (Int_t id)
Definition at line 834 of file RDBCform.C.
View newest version in sPHENIX GitHub at line 834 of file RDBCform.C
References First(), kFirst, kLast, kNext, kPrev, Last(), Next(), and Prev().
void DbForm::Hide () inline
Definition at line 493 of file RDBCform.C.
View newest version in sPHENIX GitHub at line 493 of file RDBCform.C
References fMain.
void DbForm::Last ()
Definition at line 735 of file RDBCform.C.
View newest version in sPHENIX GitHub at line 735 of file RDBCform.C
References DisplayResults(), fResultSet, and TSQLResultSet::Last().
Referenced by HandleGotoMenu().
void DbForm::Next ()
Definition at line 744 of file RDBCform.C.
View newest version in sPHENIX GitHub at line 744 of file RDBCform.C
References DisplayResults(), fResultSet, and TSQLResultSet::Next().
Referenced by HandleGotoMenu().
void DbForm::Prev ()
Definition at line 753 of file RDBCform.C.
View newest version in sPHENIX GitHub at line 753 of file RDBCform.C
References DisplayResults(), fResultSet, and TSQLResultSet::Previous().
Referenced by HandleGotoMenu().
void DbForm::SetConnection (TSQLConnection * con) inline
Definition at line 489 of file RDBCform.C.
View newest version in sPHENIX GitHub at line 489 of file RDBCform.C
References con, fConnection, and HandleConnect().
Referenced by SetStatement().
void DbForm::SetForwardOnly ()
Definition at line 1031 of file RDBCform.C.
View newest version in sPHENIX GitHub at line 1031 of file RDBCform.C
References fFirstButton, fGotoMenu, fLastButton, fPrevButton, fRstype, kFirst, kLast, kPrev, and kTYPE_FORWARD_ONLY.
Referenced by DisplayResults(), HandleConnect(), and HandleExecuteQuery().
void DbForm::SetStatement (TSQLStatement * stmt) inline
Definition at line 490 of file RDBCform.C.
View newest version in sPHENIX GitHub at line 490 of file RDBCform.C
References TSQLStatement::GetConnection(), HandleExecuteQuery(), and SetConnection().
void DbForm::Show () inline
Definition at line 494 of file RDBCform.C.
View newest version in sPHENIX GitHub at line 494 of file RDBCform.C
References fMain.
void DbForm::UpdateColumn (Int_t index, const Text_t * value) private
Definition at line 713 of file RDBCform.C.
View newest version in sPHENIX GitHub at line 713 of file RDBCform.C
References fResultSet, TSQLResultSet::IsAfterLast(), TSQLResultSet::IsBeforeFirst(), str, TSQLResultSet::UpdateString(), and value.
Member Data Documentation
TGLayoutHints* DbForm::fBarLayout private
Definition at line 462 of file RDBCform.C.
View newest version in sPHENIX GitHub at line 462 of file RDBCform.C
Referenced by DbForm(), and ~DbForm().
TGCompositeFrame* DbForm::fButtonGroup private
Definition at line 454 of file RDBCform.C.
View newest version in sPHENIX GitHub at line 454 of file RDBCform.C
Referenced by DbForm(), and ~DbForm().
TGTextButton* DbForm::fCancelQueryButton private
Definition at line 447 of file RDBCform.C.
View newest version in sPHENIX GitHub at line 447 of file RDBCform.C
Referenced by DbForm(), HandleConnect(), HandleDisconnect(), and ~DbForm().
TGCanvas* DbForm::fCanvasWindow private
Definition at line 464 of file RDBCform.C.
View newest version in sPHENIX GitHub at line 464 of file RDBCform.C
Referenced by ClearCanvas(), DbForm(), HandleExecuteQuery(), and ~DbForm().
Bool_t DbForm::fConnected private
Definition at line 470 of file RDBCform.C.
View newest version in sPHENIX GitHub at line 470 of file RDBCform.C
Referenced by Connect(), DbForm(), HandleDisconnect(), and HandleFileMenu().
TSQLConnection* DbForm::fConnection private
Definition at line 474 of file RDBCform.C.
View newest version in sPHENIX GitHub at line 474 of file RDBCform.C
Referenced by Connect(), DbForm(), GetConnection(), HandleConnect(), HandleDisconnect(), HandleExecuteQuery(), and SetConnection().
TGCompositeFrame* DbForm::fContainer private
Definition at line 465 of file RDBCform.C.
View newest version in sPHENIX GitHub at line 465 of file RDBCform.C
Referenced by DbForm(), and ~DbForm().
TString DbForm::fDSN private
Definition at line 471 of file RDBCform.C.
View newest version in sPHENIX GitHub at line 471 of file RDBCform.C
Referenced by Connect(), and HandleConnect().
DbFormEntry** DbForm::fEntries private
Definition at line 466 of file RDBCform.C.
View newest version in sPHENIX GitHub at line 466 of file RDBCform.C
Referenced by ClearCanvas(), DisplayResults(), and HandleExecuteQuery().
TGTextButton* DbForm::fExecuteQueryButton private
Definition at line 446 of file RDBCform.C.
View newest version in sPHENIX GitHub at line 446 of file RDBCform.C
Referenced by DbForm(), HandleConnect(), HandleDisconnect(), and ~DbForm().
TGPopupMenu* DbForm::fFileMenu private
Definition at line 442 of file RDBCform.C.
View newest version in sPHENIX GitHub at line 442 of file RDBCform.C
Referenced by DbForm(), HandleConnect(), HandleDisconnect(), and ~DbForm().
TGTextButton* DbForm::fFirstButton private
Definition at line 451 of file RDBCform.C.
View newest version in sPHENIX GitHub at line 451 of file RDBCform.C
Referenced by DbForm(), HandleDisconnect(), HandleExecuteQuery(), SetForwardOnly(), and ~DbForm().
TGPopupMenu* DbForm::fGotoMenu private
Definition at line 443 of file RDBCform.C.
View newest version in sPHENIX GitHub at line 443 of file RDBCform.C
Referenced by DbForm(), DisplayResults(), HandleDisconnect(), HandleExecuteQuery(), SetForwardOnly(), and ~DbForm().
TGPopupMenu* DbForm::fHelpMenu private
Definition at line 444 of file RDBCform.C.
View newest version in sPHENIX GitHub at line 444 of file RDBCform.C
Referenced by DbForm(), and ~DbForm().
TGTextButton* DbForm::fLastButton private
Definition at line 450 of file RDBCform.C.
View newest version in sPHENIX GitHub at line 450 of file RDBCform.C
Referenced by DbForm(), HandleDisconnect(), HandleExecuteQuery(), SetForwardOnly(), and ~DbForm().
TGMainFrame* DbForm::fMain private
Definition at line 441 of file RDBCform.C.
View newest version in sPHENIX GitHub at line 441 of file RDBCform.C
Referenced by DbForm(), GetMainFrame(), HandleExecuteQuery(), Hide(), Show(), and ~DbForm().
TGMenuBar* DbForm::fMenuBar private
Definition at line 456 of file RDBCform.C.
View newest version in sPHENIX GitHub at line 456 of file RDBCform.C
Referenced by DbForm(), and ~DbForm().
TGLayoutHints* DbForm::fMenuBarHelpLayout private
Definition at line 459 of file RDBCform.C.
View newest version in sPHENIX GitHub at line 459 of file RDBCform.C
Referenced by DbForm(), and ~DbForm().
TGLayoutHints* DbForm::fMenuBarItemLayout private
Definition at line 458 of file RDBCform.C.
View newest version in sPHENIX GitHub at line 458 of file RDBCform.C
Referenced by DbForm(), and ~DbForm().
TGLayoutHints* DbForm::fMenuBarLayout private
Definition at line 457 of file RDBCform.C.
View newest version in sPHENIX GitHub at line 457 of file RDBCform.C
Referenced by DbForm(), HandleExecuteQuery(), and ~DbForm().
TGTextButton* DbForm::fNextButton private
Definition at line 448 of file RDBCform.C.
View newest version in sPHENIX GitHub at line 448 of file RDBCform.C
Referenced by DbForm(), DisplayResults(), HandleDisconnect(), HandleExecuteQuery(), and ~DbForm().
TTimer* DbForm::fNextButtonTimer private
Definition at line 452 of file RDBCform.C.
View newest version in sPHENIX GitHub at line 452 of file RDBCform.C
Referenced by AccelerateNextButton(), DbForm(), and ~DbForm().
PasswordDialog* DbForm::fPD private
Definition at line 467 of file RDBCform.C.
View newest version in sPHENIX GitHub at line 467 of file RDBCform.C
Referenced by Connect(), DbForm(), HandleFileMenu(), and ~DbForm().
TGTextButton* DbForm::fPrevButton private
Definition at line 449 of file RDBCform.C.
View newest version in sPHENIX GitHub at line 449 of file RDBCform.C
Referenced by DbForm(), DisplayResults(), HandleDisconnect(), HandleExecuteQuery(), SetForwardOnly(), and ~DbForm().
TTimer* DbForm::fPrevButtonTimer private
Definition at line 453 of file RDBCform.C.
View newest version in sPHENIX GitHub at line 453 of file RDBCform.C
Referenced by AcceleratePrevButton(), DbForm(), and ~DbForm().
TGTextEntry* DbForm::fQueryTextEntry private
Definition at line 445 of file RDBCform.C.
View newest version in sPHENIX GitHub at line 445 of file RDBCform.C
Referenced by DbForm(), HandleConnect(), HandleDisconnect(), HandleExecuteQuery(), and ~DbForm().
TGLayoutHints* DbForm::fQueryTextLayout private
Definition at line 463 of file RDBCform.C.
View newest version in sPHENIX GitHub at line 463 of file RDBCform.C
Referenced by ~DbForm().
TSQLResultSet* DbForm::fResultSet private
Definition at line 476 of file RDBCform.C.
View newest version in sPHENIX GitHub at line 476 of file RDBCform.C
Referenced by DbForm(), DisplayResults(), First(), HandleDisconnect(), HandleExecuteQuery(), Last(), Next(), Prev(), and UpdateColumn().
TSQLResultSetMetaData* DbForm::fResultSetMetaData private
Definition at line 477 of file RDBCform.C.
View newest version in sPHENIX GitHub at line 477 of file RDBCform.C
Referenced by ClearCanvas(), DbForm(), DisplayResults(), HandleDisconnect(), and HandleExecuteQuery().
Int_t DbForm::fRsconc private
Definition at line 473 of file RDBCform.C.
View newest version in sPHENIX GitHub at line 473 of file RDBCform.C
Referenced by HandleConnect(), and HandleExecuteQuery().
Int_t DbForm::fRstype private
Definition at line 472 of file RDBCform.C.
View newest version in sPHENIX GitHub at line 472 of file RDBCform.C
Referenced by DisplayResults(), HandleConnect(), HandleExecuteQuery(), and SetForwardOnly().
TSQLStatement* DbForm::fStatement private
Definition at line 475 of file RDBCform.C.
View newest version in sPHENIX GitHub at line 475 of file RDBCform.C
Referenced by DbForm(), HandleDisconnect(), and HandleExecuteQuery().
TGStatusBar* DbForm::fStatusBar private
Definition at line 455 of file RDBCform.C.
View newest version in sPHENIX GitHub at line 455 of file RDBCform.C
Referenced by DbForm(), DisplayResults(), HandleConnect(), HandleDisconnect(), HandleExecuteQuery(), and ~DbForm().
TGToolBar* DbForm::fToolBar private
Definition at line 461 of file RDBCform.C.
View newest version in sPHENIX GitHub at line 461 of file RDBCform.C
Referenced by DbForm(), and ~DbForm().
TGHorizontal3DLine* DbForm::fToolBarSep private
Definition at line 460 of file RDBCform.C.
View newest version in sPHENIX GitHub at line 460 of file RDBCform.C
Referenced by DbForm(), and ~DbForm().
The documentation for this class was generated from the following file:
RDBC/blob/master/macros/RDBCform.C