Analysis Software: geant4_parallel Namespace Reference
geant4_parallel Namespace Reference
Functions
def runGeant4EventRange
Variables
int n_events 100
int n_jobs 8
tuple chunksize n_events//(n_jobs - 1)
tuple begins range(0, n_events, chunksize)
list ends [min(b + chunksize, n_events) for b in begins]
tuple outputDir Path.cwd()
Function Documentation
def geant4_parallel.runGeant4EventRange (beginEvent, endEvent, outputDir)
Definition at line 25 of file geant4_parallel.py.
View newest version in sPHENIX GitHub at line 25 of file geant4_parallel.py
References acts.examples.simulation.addGeant4(), acts.examples.simulation.addParticleGun(), acts.examples.simulation.EtaConfig, acts.examples.odd.getOpenDataDetector(), and common.getOpenDataDetectorDirectory().
Variable Documentation
tuple geant4_parallel.begins range(0, n_events, chunksize)
Definition at line 72 of file geant4_parallel.py.
View newest version in sPHENIX GitHub at line 72 of file geant4_parallel.py
tuple geant4_parallel.chunksize n_events//(n_jobs - 1)
Definition at line 71 of file geant4_parallel.py.
View newest version in sPHENIX GitHub at line 71 of file geant4_parallel.py
list geant4_parallel.ends [min(b + chunksize, n_events) for b in begins]
Definition at line 73 of file geant4_parallel.py.
View newest version in sPHENIX GitHub at line 73 of file geant4_parallel.py
Referenced by OnCalServer.check_calibrator_in_statustable(), OnCalServer.check_create_subsystable(), OnCalServer.check_create_successtable(), get_statusstring(), mg_server(), Fun4AllMonitoring.PrintsMaps(), and TEST().
int geant4_parallel.n_events 100
Definition at line 68 of file geant4_parallel.py.
View newest version in sPHENIX GitHub at line 68 of file geant4_parallel.py
Referenced by SmashWrapper.ExecuteTask(), and readJetTree().
int geant4_parallel.n_jobs 8
Definition at line 69 of file geant4_parallel.py.
View newest version in sPHENIX GitHub at line 69 of file geant4_parallel.py
tuple geant4_parallel.outputDir Path.cwd()
Definition at line 75 of file geant4_parallel.py.
View newest version in sPHENIX GitHub at line 75 of file geant4_parallel.py