Analysis Software: Jetscape::JetEnergyLoss Class Reference
Jetscape::JetEnergyLoss Class Reference
#include <JETSCAPE/blob/main/src/framework/JetEnergyLoss.h>
Public Member Functions
JetEnergyLoss ()
JetEnergyLoss (const JetEnergyLoss &j)
virtual ~JetEnergyLoss ()
virtual shared_ptr< JetEnergyLoss > Clone () const
virtual void Init ()
virtual void Exec () final
virtual void WriteTask (weak_ptr< JetScapeWriter > w)
virtual void Clear ()
virtual void DoEnergyLoss (double deltaT, double time, double Q2, vector< Parton > &pIn, vector< Parton > &pOut)
void SetQhat (double m_qhat)
const double GetQhat () const
void AddShowerInitiatingParton (shared_ptr< Parton > p)
shared_ptr< Parton > GetShowerInitiatingParton ()
void PrintShowerInitiatingParton ()
double GetDeltaT ()
double GetMaxT ()
shared_ptr< PartonShower > GetShower ()
void SetJetSignalConnected (bool m_jetSignalConnected)
TODO: Remove.
const bool GetJetSignalConnected () const
void SetEdensitySignalConnected (bool m_edensitySignalConnected)
const bool GetEdensitySignalConnected () const
void SetGetHydroCellSignalConnected (bool m_GetHydroCellSignalConnected)
const bool GetGetHydroCellSignalConnected ()
void SetGetHydroTau0SignalConnected (bool m_GetHydroTau0SignalConnected)
const bool GetGetHydroTau0SignalConnected ()
void SetSentInPartonsConnected (bool m_SentInPartonsConnected)
const bool GetSentInPartonsConnected ()
void add_a_liquefier (std::shared_ptr< LiquefierBase > new_liquefier)
std::weak_ptr< LiquefierBase > get_liquefier ()
void SendFinalStatePartons (vector< vector< shared_ptr< Parton >>> &fPartons)
void GetFinalPartonsForEachShower (shared_ptr< PartonShower > shower)
Public Member Functions inherited from Jetscape::JetScapeModuleBase
JetScapeModuleBase ()
JetScapeModuleBase (string m_name)
virtual ~JetScapeModuleBase ()
void SetXMLMainFileName (string m_name)
string GetXMLMainFileName ()
void SetXMLUserFileName (string m_name)
string GetXMLUserFileName ()
shared_ptr< std::mt19937 > GetMt19937Generator ()
tinyxml2::XMLElement * GetXMLElement (std::initializer_list< const char * > path, bool isRequired=true)
std::string GetXMLElementText (std::initializer_list< const char * > path, bool isRequired=true)
int GetXMLElementInt (std::initializer_list< const char * > path, bool isRequired=true)
double GetXMLElementDouble (std::initializer_list< const char * > path, bool isRequired=true)
Public Member Functions inherited from Jetscape::JetScapeTask
JetScapeTask ()
virtual ~JetScapeTask ()
virtual void Finish ()
virtual void ExecuteTasks ()
virtual void ExecuteTask ()
virtual void InitTask ()
virtual void InitTasks ()
virtual void ClearTasks ()
virtual void ClearTask ()
virtual void FinishTask ()
virtual void FinishTasks ()
virtual void WriteTasks (weak_ptr< JetScapeWriter > w)
virtual void CollectHeader (weak_ptr< JetScapeWriter > w)
virtual void CollectHeaders (weak_ptr< JetScapeWriter > w)
virtual void Add (shared_ptr< JetScapeTask > m_tasks)
virtual const int GetMyTaskNumber () const
const vector< shared_ptr
< JetScapeTask > > GetTaskList () const
shared_ptr< JetScapeTask > GetTaskAt (int i)
void EraseTaskLast ()
void EraseTaskAt (int i)
void ResizeTaskList (int i)
void ClearTaskList ()
int GetNumberOfTasks ()
const bool GetActive () const
void SetActive (bool m_active_exec)
void SetId (string m_id)
const string GetId () const
const shared_ptr
< JetScapeModuleMutex > GetMutex () const
void SetMutex (shared_ptr< JetScapeModuleMutex > m_mutex)
Public Member Functions inherited from sigslot::has_slots< sigslot::multi_threaded_local >
has_slots ()
has_slots (const has_slots &hs)
void signal_connect (_signal_base< sigslot::multi_threaded_local > *sender)
void signal_disconnect (_signal_base< sigslot::multi_threaded_local > *sender)
virtual ~has_slots ()
void disconnect_all ()
Public Attributes
sigslot::signal5< double,
double, double, double,
std::unique_ptr< FluidCellInfo >
&, multi_threaded_local > GetHydroCellSignal
Core signal to receive information from the medium.
sigslot::signal1< double
&, multi_threaded_local > GetHydroTau0Signal
sigslot::signal2< int, double,
multi_threaded_local > jetSignal
sigslot::signal2< int, double
&, multi_threaded_local > edensitySignal
sigslot::signal5< double,
double, double, vector< Parton >
&, vector< Parton >
&, multi_threaded_local > SentInPartons
Protected Attributes
std::weak_ptr< LiquefierBase > liquefier_ptr
Private Member Functions
void DoShower ()
Private Attributes
double deltaT
double maxT
double qhat
shared_ptr< Parton > inP
shared_ptr< PartonShower > pShower
bool GetHydroCellSignalConnected
bool GetHydroTau0SignalConnected
bool SentInPartonsConnected
node vStart
node vEnd
bool jetSignalConnected
bool edensitySignalConnected
vector< vector< shared_ptr
< Parton > > > final_Partons
Additional Inherited Members
Static Public Member Functions inherited from Jetscape::JetScapeModuleBase
static int GetCurrentEvent ()
static void IncrementCurrentEvent ()
Detailed Description
Definition at line 33 of file JetEnergyLoss.h.
View newest version in sPHENIX GitHub at line 33 of file JetEnergyLoss.h
Constructor & Destructor Documentation
Jetscape::JetEnergyLoss::JetEnergyLoss ()
Default constructor. It sets the value of qhat, deltaT and maxT to -99.99, 0.0 and 0.0, respectively. Standard signal slot flags are set to false.
Definition at line 46 of file JetEnergyLoss.cc.
View newest version in sPHENIX GitHub at line 46 of file JetEnergyLoss.cc
References SetId(), and VERBOSE.
Jetscape::JetEnergyLoss::JetEnergyLoss (const JetEnergyLoss & j)
A copy constructor for Jet Energy Loss Physics Task.
Parameters
j A pointer of type JetEnergyLoss class.
Definition at line 71 of file JetEnergyLoss.cc.
View newest version in sPHENIX GitHub at line 71 of file JetEnergyLoss.cc
References deltaT, boost::dynamic_pointer_cast(), Jetscape::JetScapeTask::GetActive(), Jetscape::JetScapeTask::GetId(), GetQhat(), Jetscape::JetScapeTask::GetTaskList(), it, maxT, SetId(), and VERBOSE.
Jetscape::JetEnergyLoss::~JetEnergyLoss () virtual
Destructor
Definition at line 64 of file JetEnergyLoss.cc.
View newest version in sPHENIX GitHub at line 64 of file JetEnergyLoss.cc
References VERBOSE.
Member Function Documentation
void Jetscape::JetEnergyLoss::add_a_liquefier (std::shared_ptr< LiquefierBase > new_liquefier) inline
Definition at line 204 of file JetEnergyLoss.h.
View newest version in sPHENIX GitHub at line 204 of file JetEnergyLoss.h
References liquefier_ptr.
Referenced by Jetscape::JetEnergyLossManager::Exec().
void Jetscape::JetEnergyLoss::AddShowerInitiatingParton (shared_ptr< Parton > p) inline
It adds a initiating parton p to create the parton shower in an energy loss task.
Parameters
p A pointer of type parton class.
Definition at line 123 of file JetEnergyLoss.h.
View newest version in sPHENIX GitHub at line 123 of file JetEnergyLoss.h
References inP, and merge_hashes::p.
void Jetscape::JetEnergyLoss::Clear (void) virtual
Reset the parton shower information.
Reimplemented from Jetscape::JetScapeModuleBase.
Reimplemented in AdSCFT.
Definition at line 96 of file JetEnergyLoss.cc.
View newest version in sPHENIX GitHub at line 96 of file JetEnergyLoss.cc
References VERBOSESHOWER.
virtual shared_ptr<JetEnergyLoss> Jetscape::JetEnergyLoss::Clone () const inline virtual
Deep copy.
Returns
Null pointer.
Reimplemented in Jetscape::JetEnergyLossModule< Derived >, Jetscape::JetEnergyLossModule< Matter >, Jetscape::JetEnergyLossModule< LBT >, Jetscape::JetEnergyLossModule< ElossValidate >, Jetscape::JetEnergyLossModule< Martini >, and Jetscape::JetEnergyLossModule< AdSCFT >.
Definition at line 53 of file JetEnergyLoss.h.
View newest version in sPHENIX GitHub at line 53 of file JetEnergyLoss.h
virtual void Jetscape::JetEnergyLoss::DoEnergyLoss (double deltaT, double time, double Q2, vector< Parton > & pIn, vector< Parton > & pOut) inline virtual
Default function to perform the energy loss for partons at time "time". It should be overridden by different energy loss tasks.
Parameters
deltaT Step-size.
time Current time.
Q2 Current virtuality of the parton.
pIn Vector of current partons.
pOut Vector of partons at time "time+deltaT".
Reimplemented in Martini, LBT, AdSCFT, Matter, and ElossValidate.
Definition at line 84 of file JetEnergyLoss.h.
View newest version in sPHENIX GitHub at line 84 of file JetEnergyLoss.h
void Jetscape::JetEnergyLoss::DoShower () private
This function executes the shower process for the partons produced from the hard scaterring.
Definition at line 147 of file JetEnergyLoss.cc.
View newest version in sPHENIX GitHub at line 147 of file JetEnergyLoss.cc
References i, k, train_ambiguity_solver::pid, physmon_track_finding_ttbar::pt, VERBOSE, VERBOSEPARTON, VERBOSESHOWER, and Jetscape::weak_ptr_is_uninitialized().
void Jetscape::JetEnergyLoss::Exec () final virtual
It calls DoShower() for all shower-initiating partons. To avoid abuse, this can NOT be overwritten. Eloss happens on a parton-by-parton level, Exec() should only be executed once per event.
Reimplemented from Jetscape::JetScapeModuleBase.
Definition at line 354 of file JetEnergyLoss.cc.
View newest version in sPHENIX GitHub at line 354 of file JetEnergyLoss.cc
References JSWARN, and VERBOSE.
std::weak_ptr<LiquefierBase> Jetscape::JetEnergyLoss::get_liquefier () inline
Definition at line 208 of file JetEnergyLoss.h.
View newest version in sPHENIX GitHub at line 208 of file JetEnergyLoss.h
References liquefier_ptr.
double Jetscape::JetEnergyLoss::GetDeltaT () inline
Returns
The time-step "deltaT" used by energy loss task.
Definition at line 133 of file JetEnergyLoss.h.
View newest version in sPHENIX GitHub at line 133 of file JetEnergyLoss.h
References deltaT.
Referenced by Jetscape::PartonShowerGenerator::DoShower().
const bool Jetscape::JetEnergyLoss::GetEdensitySignalConnected () const inline
Returns
A boolean flag. Its status indicates whether JetEnergyLoss had sent a signal to the function GetEnergyDensity() of the class FluidDynamics.
Definition at line 166 of file JetEnergyLoss.h.
View newest version in sPHENIX GitHub at line 166 of file JetEnergyLoss.h
References edensitySignalConnected.
void Jetscape::JetEnergyLoss::GetFinalPartonsForEachShower (shared_ptr< PartonShower > shower)
Definition at line 430 of file JetEnergyLoss.cc.
View newest version in sPHENIX GitHub at line 430 of file JetEnergyLoss.cc
const bool Jetscape::JetEnergyLoss::GetGetHydroCellSignalConnected () inline
Returns
A boolean flag. Its status indicates whether JetEnergyLoss had sent a signal to the function GetHydroCell() of the class FluidDynamics.
Definition at line 180 of file JetEnergyLoss.h.
View newest version in sPHENIX GitHub at line 180 of file JetEnergyLoss.h
References GetHydroCellSignalConnected.
const bool Jetscape::JetEnergyLoss::GetGetHydroTau0SignalConnected () inline
Definition at line 188 of file JetEnergyLoss.h.
View newest version in sPHENIX GitHub at line 188 of file JetEnergyLoss.h
References GetHydroTau0SignalConnected.
const bool Jetscape::JetEnergyLoss::GetJetSignalConnected () const inline
Returns
A boolean flag. Its status indicates whether JetEnergyLoss had sent a signal to the function UpdateEnergyDeposit() of the class FluidDynamics.
Definition at line 154 of file JetEnergyLoss.h.
View newest version in sPHENIX GitHub at line 154 of file JetEnergyLoss.h
References jetSignalConnected.
Referenced by AdSCFT::DoEnergyLoss().
double Jetscape::JetEnergyLoss::GetMaxT () inline
Returns
The maximum time limit for parton shower.
Definition at line 137 of file JetEnergyLoss.h.
View newest version in sPHENIX GitHub at line 137 of file JetEnergyLoss.h
References maxT.
Referenced by Jetscape::PartonShowerGenerator::DoShower().
const double Jetscape::JetEnergyLoss::GetQhat () const inline
Returns
The current value of qhat.
Definition at line 118 of file JetEnergyLoss.h.
View newest version in sPHENIX GitHub at line 118 of file JetEnergyLoss.h
References qhat.
Referenced by JetEnergyLoss().
const bool Jetscape::JetEnergyLoss::GetSentInPartonsConnected () inline
Returns
A boolean flag. Its status indicates whether JetEnergyLoss had sent a signal to the function DoEnergyLoss().
Definition at line 202 of file JetEnergyLoss.h.
View newest version in sPHENIX GitHub at line 202 of file JetEnergyLoss.h
References SentInPartonsConnected.
shared_ptr<PartonShower> Jetscape::JetEnergyLoss::GetShower () inline
Returns
The current shower.
Definition at line 141 of file JetEnergyLoss.h.
View newest version in sPHENIX GitHub at line 141 of file JetEnergyLoss.h
References pShower.
Referenced by Jetscape::PartonShowerGenerator::DoShower().
shared_ptr<Parton> Jetscape::JetEnergyLoss::GetShowerInitiatingParton () inline
Returns
The parton which initiated the parton shower.
Definition at line 127 of file JetEnergyLoss.h.
View newest version in sPHENIX GitHub at line 127 of file JetEnergyLoss.h
References inP.
Referenced by Jetscape::PartonShowerGenerator::DoShower().
void Jetscape::JetEnergyLoss::Init () virtual
It reads the input parameters from a XML file under the tag <Eloss>. Sets the Parton class inP and PartonShower class pShower to null. Also initializes the tasks attached to the JetEnergyLoss module.
Reimplemented from Jetscape::JetScapeModuleBase.
Reimplemented in Martini, LBT, AdSCFT, Matter, and ElossValidate.
Definition at line 106 of file JetEnergyLoss.cc.
View newest version in sPHENIX GitHub at line 106 of file JetEnergyLoss.cc
References Init(), JSINFO, and JSWARN.
void Jetscape::JetEnergyLoss::PrintShowerInitiatingParton ()
Definition at line 426 of file JetEnergyLoss.cc.
View newest version in sPHENIX GitHub at line 426 of file JetEnergyLoss.cc
void Jetscape::JetEnergyLoss::SendFinalStatePartons (vector< vector< shared_ptr< Parton >>> & fPartons) inline
Definition at line 211 of file JetEnergyLoss.h.
View newest version in sPHENIX GitHub at line 211 of file JetEnergyLoss.h
References final_Partons.
void Jetscape::JetEnergyLoss::SetEdensitySignalConnected (bool m_edensitySignalConnected) inline
Set the flag m_edensitySignalConnected to true, if JetEnergyLoss had sent a signal to the function GetEnergyDensity() of the class FluidDynamics.
Parameters
m_edensitySignalConnected A boolean flag.
Definition at line 159 of file JetEnergyLoss.h.
View newest version in sPHENIX GitHub at line 159 of file JetEnergyLoss.h
References edensitySignalConnected.
void Jetscape::JetEnergyLoss::SetGetHydroCellSignalConnected (bool m_GetHydroCellSignalConnected) inline
Set the flag m_GetHydroCellSignalConnected to true, if JetEnergyLoss had sent a signal to the function GetHydroCell() of the class FluidDynamics.
Parameters
m_GetHydroCellSignalConnected A boolean flag.
Definition at line 173 of file JetEnergyLoss.h.
View newest version in sPHENIX GitHub at line 173 of file JetEnergyLoss.h
References GetHydroCellSignalConnected.
void Jetscape::JetEnergyLoss::SetGetHydroTau0SignalConnected (bool m_GetHydroTau0SignalConnected) inline
Definition at line 184 of file JetEnergyLoss.h.
View newest version in sPHENIX GitHub at line 184 of file JetEnergyLoss.h
References GetHydroTau0SignalConnected.
void Jetscape::JetEnergyLoss::SetJetSignalConnected (bool m_jetSignalConnected) inline
TODO: Remove.
Set the flag m_jetSignalConnected to true, if JetEnergyLoss had sent a signal to the function UpdateEnergyDeposit() of the class FluidDynamics.
Parameters
m_jetSignalConnected A boolean flag.
Definition at line 148 of file JetEnergyLoss.h.
View newest version in sPHENIX GitHub at line 148 of file JetEnergyLoss.h
References jetSignalConnected.
void Jetscape::JetEnergyLoss::SetQhat (double m_qhat) inline
Sets the value of qhat to "m_qhat".
Parameters
m_qhat Jet quenching parameter q-hat.
Definition at line 114 of file JetEnergyLoss.h.
View newest version in sPHENIX GitHub at line 114 of file JetEnergyLoss.h
References qhat.
void Jetscape::JetEnergyLoss::SetSentInPartonsConnected (bool m_SentInPartonsConnected) inline
Set the flag m_SentInPartonsConnected to true, if JetEnergyLoss had sent a signal to the function DoEnergyLoss().
Parameters
m_SentInPartonsConnected A boolean flag.
Definition at line 195 of file JetEnergyLoss.h.
View newest version in sPHENIX GitHub at line 195 of file JetEnergyLoss.h
References SentInPartonsConnected.
void Jetscape::JetEnergyLoss::WriteTask (weak_ptr< JetScapeWriter > w) virtual
Write output information for each tasks/subtasks attached to the JetEnergyLoss module using JetScapeWriter functionality.
Parameters
w A pointer of type JetScapeWriter.
Reimplemented from Jetscape::JetScapeTask.
Reimplemented in Martini, LBT, AdSCFT, Matter, and ElossValidate.
Definition at line 412 of file JetEnergyLoss.cc.
View newest version in sPHENIX GitHub at line 412 of file JetEnergyLoss.cc
References f, and VERBOSE.
Member Data Documentation
double Jetscape::JetEnergyLoss::deltaT private
Definition at line 221 of file JetEnergyLoss.h.
View newest version in sPHENIX GitHub at line 221 of file JetEnergyLoss.h
Referenced by AdSCFT::DoEnergyLoss(), GetDeltaT(), and JetEnergyLoss().
sigslot::signal2<int, double &, multi_threaded_local> Jetscape::JetEnergyLoss::edensitySignal
For future development. A signal to connect the JetEnergyLoss object to the function GetEnergyDensity() of the FluidDynamics class.
Definition at line 100 of file JetEnergyLoss.h.
View newest version in sPHENIX GitHub at line 100 of file JetEnergyLoss.h
bool Jetscape::JetEnergyLoss::edensitySignalConnected private
Definition at line 241 of file JetEnergyLoss.h.
View newest version in sPHENIX GitHub at line 241 of file JetEnergyLoss.h
Referenced by GetEdensitySignalConnected(), and SetEdensitySignalConnected().
vector<vector<shared_ptr<Parton> > > Jetscape::JetEnergyLoss::final_Partons private
Definition at line 245 of file JetEnergyLoss.h.
View newest version in sPHENIX GitHub at line 245 of file JetEnergyLoss.h
Referenced by SendFinalStatePartons().
sigslot::signal5<double, double, double, double, std::unique_ptr<FluidCellInfo> &, multi_threaded_local> Jetscape::JetEnergyLoss::GetHydroCellSignal
Core signal to receive information from the medium.
Definition at line 85 of file JetEnergyLoss.h.
View newest version in sPHENIX GitHub at line 85 of file JetEnergyLoss.h
Referenced by AdSCFT::DoEnergyLoss().
bool Jetscape::JetEnergyLoss::GetHydroCellSignalConnected private
Definition at line 228 of file JetEnergyLoss.h.
View newest version in sPHENIX GitHub at line 228 of file JetEnergyLoss.h
Referenced by GetGetHydroCellSignalConnected(), and SetGetHydroCellSignalConnected().
sigslot::signal1<double &, multi_threaded_local> Jetscape::JetEnergyLoss::GetHydroTau0Signal
Definition at line 92 of file JetEnergyLoss.h.
View newest version in sPHENIX GitHub at line 92 of file JetEnergyLoss.h
bool Jetscape::JetEnergyLoss::GetHydroTau0SignalConnected private
Definition at line 229 of file JetEnergyLoss.h.
View newest version in sPHENIX GitHub at line 229 of file JetEnergyLoss.h
Referenced by GetGetHydroTau0SignalConnected(), and SetGetHydroTau0SignalConnected().
shared_ptr<Parton> Jetscape::JetEnergyLoss::inP private
Definition at line 225 of file JetEnergyLoss.h.
View newest version in sPHENIX GitHub at line 225 of file JetEnergyLoss.h
Referenced by AddShowerInitiatingParton(), and GetShowerInitiatingParton().
sigslot::signal2<int, double, multi_threaded_local> Jetscape::JetEnergyLoss::jetSignal
For future development. A signal to connect the JetEnergyLoss object to the function UpdateEnergyDeposit() of the FluidDynamics class.
Definition at line 96 of file JetEnergyLoss.h.
View newest version in sPHENIX GitHub at line 96 of file JetEnergyLoss.h
bool Jetscape::JetEnergyLoss::jetSignalConnected private
Definition at line 240 of file JetEnergyLoss.h.
View newest version in sPHENIX GitHub at line 240 of file JetEnergyLoss.h
Referenced by GetJetSignalConnected(), and SetJetSignalConnected().
std::weak_ptr<LiquefierBase> Jetscape::JetEnergyLoss::liquefier_ptr protected
Definition at line 218 of file JetEnergyLoss.h.
View newest version in sPHENIX GitHub at line 218 of file JetEnergyLoss.h
Referenced by add_a_liquefier(), and get_liquefier().
double Jetscape::JetEnergyLoss::maxT private
Definition at line 222 of file JetEnergyLoss.h.
View newest version in sPHENIX GitHub at line 222 of file JetEnergyLoss.h
Referenced by GetMaxT(), and JetEnergyLoss().
shared_ptr<PartonShower> Jetscape::JetEnergyLoss::pShower private
Definition at line 226 of file JetEnergyLoss.h.
View newest version in sPHENIX GitHub at line 226 of file JetEnergyLoss.h
Referenced by GetShower().
double Jetscape::JetEnergyLoss::qhat private
Definition at line 224 of file JetEnergyLoss.h.
View newest version in sPHENIX GitHub at line 224 of file JetEnergyLoss.h
Referenced by GetQhat(), and SetQhat().
sigslot::signal5<double, double, double, vector<Parton> &, vector<Parton> &, multi_threaded_local> Jetscape::JetEnergyLoss::SentInPartons
A signal to connect the JetEnergyLoss object to the function DoEnergyLoss() function. Send all a list of shower-initiating partons to all attached eloss modules. They in turn decide whether they are responsible or not. Rename...
Definition at line 109 of file JetEnergyLoss.h.
View newest version in sPHENIX GitHub at line 109 of file JetEnergyLoss.h
Referenced by Jetscape::PartonShowerGenerator::DoShower().
bool Jetscape::JetEnergyLoss::SentInPartonsConnected private
Definition at line 230 of file JetEnergyLoss.h.
View newest version in sPHENIX GitHub at line 230 of file JetEnergyLoss.h
Referenced by GetSentInPartonsConnected(), and SetSentInPartonsConnected().
node Jetscape::JetEnergyLoss::vEnd private
Definition at line 237 of file JetEnergyLoss.h.
View newest version in sPHENIX GitHub at line 237 of file JetEnergyLoss.h
node Jetscape::JetEnergyLoss::vStart private
Definition at line 236 of file JetEnergyLoss.h.
View newest version in sPHENIX GitHub at line 236 of file JetEnergyLoss.h
The documentation for this class was generated from the following files:
JETSCAPE/blob/main/src/framework/JetEnergyLoss.h
JETSCAPE/blob/main/src/framework/JetEnergyLoss.cc