Analysis Software: generate_files_AA Namespace Reference
generate_files_AA Namespace Reference
Variables
list introduction
tuple ff open("./run_all_AA_jobs.sh","w+")
list evt_start [0, 75, 155, 233, 312, 392, 471, 551, 630, 712, 793, 873, 953, 1033, 1113, 1194, 1272, 1352, 1432, 1511, 1592, 1670, 1750, 1830, 1910, 1990, 2069, 2149, 2230, 2310, 2391, 2470, 2550, 2631, 2711, 2792, 2871, 2952, 3032, 3113, 3193, 3273, 3352, 3433, 3514, 3595, 3676, 3755, 3834, 3915, 3995, 4076, 4156, 4235, 4315, 4396, 4476, 4557, 4636, 4718, 4798, 4877, 4957, 5037, 5118, 5200, 5278, 5359, 5439, 5518, 5598, 5680, 5760, 5841, 5922, 6002, 6081, 6162, 6241, 6321, 6400, 6481, 6561, 6641, 6722, 6804, 6884, 6964, 7045, 7126, 7206, 7286, 7366, 7447, 7527, 7606, 7687, 7767, 7847, 7928, 8008, 8087, 8167, 8248, 8328, 8408, 8489, 8566, 8646, 8727, 8809, 8890, 8970, 9049, 9129, 9209, 9288, 9368, 9449, 9529, 9608, 9688, 9769, 9849]
list evt_end [ 170, 248, 327, 407, 486, 566, 645, 727, 808, 888, 968, 1048, 1128, 1209, 1287, 1367, 1447, 1526, 1607, 1685, 1765, 1845, 1925, 2005, 2084, 2164, 2245, 2325, 2406, 2485, 2565, 2646, 2726, 2807, 2886, 2967, 3047, 3128, 3208, 3288, 3367, 3448, 3529, 3610, 3691, 3770, 3849, 3930, 4010, 4091, 4171, 4250, 4330, 4411, 4491, 4572, 4651, 4733, 4813, 4892, 4972, 5052, 5133, 5215, 5293, 5374, 5454, 5533, 5613, 5695, 5775, 5856, 5937, 6017, 6096, 6177, 6256, 6336, 6415, 6496, 6576, 6656, 6737, 6819, 6899, 6979, 7060, 7141, 7221, 7301, 7381, 7462, 7542, 7621, 7702, 7782, 7862, 7943, 8023, 8102, 8182, 8263, 8343, 8423, 8504, 8581, 8661, 8742, 8824, 8905, 8985, 9064, 9144, 9224, 9303, 9383, 9464, 9544, 9623, 9703, 9784, 9864, 9943, 10000]
list evt_bX [1508071.0, 3016509.0, 4524020.0, 6032112.0, 7540028.0, 9048092.0, 10556072.0, 12064371.0, 13572143.0, 15080178.0, 16588072.0, 18096105.0]
string filename "./run_macros/run_files_AA_{}_{}.sh"
tuple f open(filename,"w+")
string filename_job "./run_macros/condor_run_files_AA_{}_{}.job"
tuple f_job open(filename_job,"w+")
int n_line 0
Variable Documentation
list generate_files_AA.evt_bX [1508071.0, 3016509.0, 4524020.0, 6032112.0, 7540028.0, 9048092.0, 10556072.0, 12064371.0, 13572143.0, 15080178.0, 16588072.0, 18096105.0]
Definition at line 59 of file generate_files_AA.py.
View newest version in sPHENIX GitHub at line 59 of file generate_files_AA.py
list generate_files_AA.evt_end [ 170, 248, 327, 407, 486, 566, 645, 727, 808, 888, 968, 1048, 1128, 1209, 1287, 1367, 1447, 1526, 1607, 1685, 1765, 1845, 1925, 2005, 2084, 2164, 2245, 2325, 2406, 2485, 2565, 2646, 2726, 2807, 2886, 2967, 3047, 3128, 3208, 3288, 3367, 3448, 3529, 3610, 3691, 3770, 3849, 3930, 4010, 4091, 4171, 4250, 4330, 4411, 4491, 4572, 4651, 4733, 4813, 4892, 4972, 5052, 5133, 5215, 5293, 5374, 5454, 5533, 5613, 5695, 5775, 5856, 5937, 6017, 6096, 6177, 6256, 6336, 6415, 6496, 6576, 6656, 6737, 6819, 6899, 6979, 7060, 7141, 7221, 7301, 7381, 7462, 7542, 7621, 7702, 7782, 7862, 7943, 8023, 8102, 8182, 8263, 8343, 8423, 8504, 8581, 8661, 8742, 8824, 8905, 8985, 9064, 9144, 9224, 9303, 9383, 9464, 9544, 9623, 9703, 9784, 9864, 9943, 10000]
Definition at line 58 of file generate_files_AA.py.
View newest version in sPHENIX GitHub at line 58 of file generate_files_AA.py
list generate_files_AA.evt_start [0, 75, 155, 233, 312, 392, 471, 551, 630, 712, 793, 873, 953, 1033, 1113, 1194, 1272, 1352, 1432, 1511, 1592, 1670, 1750, 1830, 1910, 1990, 2069, 2149, 2230, 2310, 2391, 2470, 2550, 2631, 2711, 2792, 2871, 2952, 3032, 3113, 3193, 3273, 3352, 3433, 3514, 3595, 3676, 3755, 3834, 3915, 3995, 4076, 4156, 4235, 4315, 4396, 4476, 4557, 4636, 4718, 4798, 4877, 4957, 5037, 5118, 5200, 5278, 5359, 5439, 5518, 5598, 5680, 5760, 5841, 5922, 6002, 6081, 6162, 6241, 6321, 6400, 6481, 6561, 6641, 6722, 6804, 6884, 6964, 7045, 7126, 7206, 7286, 7366, 7447, 7527, 7606, 7687, 7767, 7847, 7928, 8008, 8087, 8167, 8248, 8328, 8408, 8489, 8566, 8646, 8727, 8809, 8890, 8970, 9049, 9129, 9209, 9288, 9368, 9449, 9529, 9608, 9688, 9769, 9849]
Definition at line 57 of file generate_files_AA.py.
View newest version in sPHENIX GitHub at line 57 of file generate_files_AA.py
tuple generate_files_AA.f open(filename,"w+")
Definition at line 63 of file generate_files_AA.py.
View newest version in sPHENIX GitHub at line 63 of file generate_files_AA.py
tuple generate_files_AA.f_job open(filename_job,"w+")
Definition at line 69 of file generate_files_AA.py.
View newest version in sPHENIX GitHub at line 69 of file generate_files_AA.py
tuple generate_files_AA.ff open("./run_all_AA_jobs.sh","w+")
Definition at line 53 of file generate_files_AA.py.
View newest version in sPHENIX GitHub at line 53 of file generate_files_AA.py
Referenced by Matter.collHQ22(), LBT.collHQ22(), Matter.colljet22(), LBT.colljet22(), EdepPercentSmall(), PIDplots.eIDoutput(), and ICGlauber.setIC().
string generate_files_AA.filename "./run_macros/run_files_AA_{}_{}.sh"
Definition at line 62 of file generate_files_AA.py.
View newest version in sPHENIX GitHub at line 62 of file generate_files_AA.py
string generate_files_AA.filename_job "./run_macros/condor_run_files_AA_{}_{}.job"
Definition at line 67 of file generate_files_AA.py.
View newest version in sPHENIX GitHub at line 67 of file generate_files_AA.py
list generate_files_AA.introduction
Definition at line 5 of file generate_files_AA.py.
View newest version in sPHENIX GitHub at line 5 of file generate_files_AA.py
int generate_files_AA.n_line 0
Definition at line 70 of file generate_files_AA.py.
View newest version in sPHENIX GitHub at line 70 of file generate_files_AA.py
Referenced by readDigitalCurrents.InitRun(), fillSpaceChargeMaps.InitRun(), and readBeamXings().