Analysis Software: TrkrClusterCrossingAssoc Class Reference
TrkrClusterCrossingAssoc Class Reference abstract
Base class for associating clusters to the hits that went into them.
#include <coresoftware/blob/master/offline/packages/trackbase/TrkrClusterCrossingAssoc.h>
Public Types
using Map = std::multimap< TrkrDefs::cluskey, short int >
using ConstIterator = Map::const_iterator
using ConstRange = std::pair< Map::const_iterator, Map::const_iterator >
Public Member Functions
void Reset () override
Clear Event.
virtual void addAssoc (TrkrDefs::cluskey ckey, short int hidx)=0
Add association between cluster and hit.
virtual ConstRange getCrossings (TrkrDefs::cluskey) const =0
virtual ConstRange getAll () const =0
virtual unsigned int size () const
Public Member Functions inherited from PHObject
PHObject ()
ctor
~PHObject () override
dtor
virtual PHObject * CloneMe () const
Virtual copy constructor.
virtual PHObject * clone () const final
PHObject * Clone (const char *newname="") const final
void Copy (TObject &object) const final
virtual void identify (std::ostream &os=std::cout) const
virtual int isValid () const
isValid returns non zero if object contains vailid data
virtual int Integrate () const
virtual int Integrate (PHObject *)
virtual void CopyFrom (const PHObject *obj)
Protected Member Functions
TrkrClusterCrossingAssoc ()=default
Private Member Functions
ClassDefOverride (TrkrClusterCrossingAssoc, 1)
Detailed Description
Base class for associating clusters to the hits that went into them.
Store the associations between clusters and the hits that went into them.
Definition at line 24 of file TrkrClusterCrossingAssoc.h.
View newest version in sPHENIX GitHub at line 24 of file TrkrClusterCrossingAssoc.h
Member Typedef Documentation
using TrkrClusterCrossingAssoc::ConstIterator = Map::const_iterator
Definition at line 29 of file TrkrClusterCrossingAssoc.h.
View newest version in sPHENIX GitHub at line 29 of file TrkrClusterCrossingAssoc.h
using TrkrClusterCrossingAssoc::ConstRange = std::pair<Map::const_iterator, Map::const_iterator>
Definition at line 30 of file TrkrClusterCrossingAssoc.h.
View newest version in sPHENIX GitHub at line 30 of file TrkrClusterCrossingAssoc.h
using TrkrClusterCrossingAssoc::Map = std::multimap<TrkrDefs::cluskey, short int>
Definition at line 28 of file TrkrClusterCrossingAssoc.h.
View newest version in sPHENIX GitHub at line 28 of file TrkrClusterCrossingAssoc.h
Constructor & Destructor Documentation
TrkrClusterCrossingAssoc::TrkrClusterCrossingAssoc () protected default
Member Function Documentation
virtual void TrkrClusterCrossingAssoc::addAssoc (TrkrDefs::cluskey ckey, short int hidx) pure virtual
Add association between cluster and hit.
Parameters
[in] ckey Cluster key
[in] bunch crossing number
Implemented in TrkrClusterCrossingAssocv1.
Referenced by InttClusterizer::ClusterLadderCells(), and InttClusterizer::ClusterLadderCellsRaw().
TrkrClusterCrossingAssoc::ClassDefOverride (TrkrClusterCrossingAssoc , 1) private
virtual ConstRange TrkrClusterCrossingAssoc::getAll () const pure virtual
Implemented in TrkrClusterCrossingAssocv1.
Referenced by DumpTrkrClusterCrossingAssoc::process_Node().
virtual ConstRange TrkrClusterCrossingAssoc::getCrossings (TrkrDefs::cluskey) const pure virtual
Implemented in TrkrClusterCrossingAssocv1.
Referenced by PHSiliconTpcTrackMatching::getInttCrossings(), PHTruthSiliconAssociation::getInttCrossings(), PHTruthTrackSeeding::getInttCrossings(), and PHSiliconHelicalPropagator::process_event().
void TrkrClusterCrossingAssoc::Reset () override virtual
Clear Event.
Reimplemented from PHObject.
Reimplemented in TrkrClusterCrossingAssocv1.
Definition at line 6 of file TrkrClusterCrossingAssoc.cc.
View newest version in sPHENIX GitHub at line 6 of file TrkrClusterCrossingAssoc.cc
virtual unsigned int TrkrClusterCrossingAssoc::size (void) const inline virtual
Reimplemented in TrkrClusterCrossingAssocv1.
Definition at line 45 of file TrkrClusterCrossingAssoc.h.
View newest version in sPHENIX GitHub at line 45 of file TrkrClusterCrossingAssoc.h
Referenced by DumpTrkrClusterCrossingAssoc::process_Node().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/trackbase/TrkrClusterCrossingAssoc.h
coresoftware/blob/master/offline/packages/trackbase/TrkrClusterCrossingAssoc.cc