Analysis Software: analysis/blob/master/HF-Jet/TruthGeneration/macros/Draw_HFJetTruth3yr.C File Reference
Draw_HFJetTruth3yr.C File Reference
#include <TChain.h>
#include <TFile.h>
#include <TGraphAsymmErrors.h>
#include <TGraphErrors.h>
#include <TLatex.h>
#include <TLegend.h>
#include <TLine.h>
#include <TString.h>
#include <TTree.h>
#include <TVirtualFitter.h>
#include <cassert>
#include <cmath>
#include <vector>
#include "SaveCanvas.C"
#include "sPhenixStyle.C"
Functions
TGraphAsymmErrors * GetFONLL_C ()
TGraphAsymmErrors * GetFONLL_B ()
TGraph * pQCDModel_HuangKangVitev (const double g)
TGraph * LIDO_Ke ()
TGraph * GetPHENIX_jet ()
TH1 * CrossSection2RelUncert (const TH1F *h_cross, const double suppression, const double deta, const double pp_quiv_int_lum)
TGraphErrors * GetRAA (TH1 *h_pp, TH1 *h_AA)
void CrossSection2RAA (const TString infile, const bool use_AA_jet_trigger=true, const double dy=.7 *2)
TGraphErrors * GetZgPrediction (const TString data_config="me_bbg")
TH1 * CrossSection2zg_HistogramMaker (const TH1F *h_cross, const double suppression, const double deta, const double pt_max, const double pp_quiv_int_lum, const TString data_config)
void CrossSection2zg (const TString infile, const bool use_AA_jet_trigger=true, const double dy=.7 *2)
TGraph * CrossSection2v2Uncert (const TH1F *h_cross, const double suppression, const double deta, const double pp_quiv_int_lum, const double ep_resolution=1, const double pt_shift=0)
void CrossSection2v2 (const TString infile, const bool use_AA_jet_trigger=true, const double ep_resolution=0.5, const double dy=.7 *2)
void Convert2CrossSection (TH1 *h, const double int_lumi, const double dy)
void DrawCrossSection (double int_lumi, const double dy)
void Draw_HFJetTruth_DrawCrossSection_PR (const TString infile)
void CrossSection2RAA_Proposal (const TString infile)
void Draw_HFJetTruth3yr (const TString infile="/sphenix/user/jinhuang/HF-jet/event_gen/200pp_pythia8_CTEQ6L_7GeV/200pp_pythia8_CTEQ6L_7GeV_ALL.cfg_eneg_DSTReader.root", double int_lumi=891093/3.332e-02/1e9, const double dy=0.6 *2)
Variables
TFile * _file0 = NULL
TTree * T = NULL
Function Documentation
void Convert2CrossSection (TH1 * h, const double int_lumi, const double dy)
Definition at line 1102 of file Draw_HFJetTruth3yr.C.
View newest version in sPHENIX GitHub at line 1102 of file Draw_HFJetTruth3yr.C
References i.
void CrossSection2RAA (const TString infile, const bool use_AA_jet_trigger = true, const double dy = .7 * 2)
Definition at line 110 of file Draw_HFJetTruth3yr.C.
View newest version in sPHENIX GitHub at line 110 of file Draw_HFJetTruth3yr.C
References assert, AuAu_Ncoll_C0_10, AuAu_Ncoll_C0_100, AuAu_Ncoll_C0_20, CrossSection2RelUncert(), dy, Acts::UnitConstants::e, f, GetRAA(), h_b, hall, ambiguity_solver_full_chain::idx, leg, LIDO_Ke(), merge_hashes::p, pAu_Ncoll_C0_100, pp_inelastic_crosssec, pQCDModel_HuangKangVitev(), and SaveCanvas().
void CrossSection2RAA_Proposal (const TString infile)
Definition at line 1742 of file Draw_HFJetTruth3yr.C.
View newest version in sPHENIX GitHub at line 1742 of file Draw_HFJetTruth3yr.C
References assert, AuAu_Ncoll_C0_10, AuAu_Ncoll_C0_100, AuAu_Ncoll_C0_20, CrossSection2RelUncert(), Acts::UnitConstants::e, f, GetRAA(), h_b, i, ambiguity_solver_full_chain::idx, integral(), merge_hashes::p, pAu_Ncoll_C0_100, pp_inelastic_crosssec, SaveCanvas(), and t.
TH1* CrossSection2RelUncert (const TH1F * h_cross, const double suppression, const double deta, const double pp_quiv_int_lum)
Definition at line 41 of file Draw_HFJetTruth3yr.C.
View newest version in sPHENIX GitHub at line 41 of file Draw_HFJetTruth3yr.C
References assert, and i.
void CrossSection2v2 (const TString infile, const bool use_AA_jet_trigger = true, const double ep_resolution = 0.5, const double dy = .7 * 2)
Definition at line 946 of file Draw_HFJetTruth3yr.C.
View newest version in sPHENIX GitHub at line 946 of file Draw_HFJetTruth3yr.C
References assert, AuAu_Ncoll_C0_10, AuAu_Ncoll_C0_100, AuAu_Ncoll_C0_20, CrossSection2v2Uncert(), dy, Acts::UnitConstants::e, f, h_b, hall, ambiguity_solver_full_chain::idx, leg, merge_hashes::p, pAu_Ncoll_C0_100, pp_inelastic_crosssec, and SaveCanvas().
TGraph* CrossSection2v2Uncert (const TH1F * h_cross, const double suppression, const double deta, const double pp_quiv_int_lum, const double ep_resolution = 1, const double pt_shift = 0)
Definition at line 892 of file Draw_HFJetTruth3yr.C.
View newest version in sPHENIX GitHub at line 892 of file Draw_HFJetTruth3yr.C
References assert, gr, and i.
void CrossSection2zg (const TString infile, const bool use_AA_jet_trigger = true, const double dy = .7 * 2)
Definition at line 723 of file Draw_HFJetTruth3yr.C.
View newest version in sPHENIX GitHub at line 723 of file Draw_HFJetTruth3yr.C
References assert, AuAu_Ncoll_C0_10, AuAu_Ncoll_C0_100, AuAu_Ncoll_C0_20, CrossSection2zg_HistogramMaker(), dy, Acts::UnitConstants::e, f, GetZgPrediction(), h_b, hall, i, ambiguity_solver_full_chain::idx, leg, merge_hashes::p, pAu_Ncoll_C0_100, pp_inelastic_crosssec, myAnalysis::pt_max, and SaveCanvas().
Referenced by Draw_HFJetTruth3yr().
TH1* CrossSection2zg_HistogramMaker (const TH1F * h_cross, const double suppression, const double deta, const double pt_max, const double pp_quiv_int_lum, const TString data_config)
Definition at line 682 of file Draw_HFJetTruth3yr.C.
View newest version in sPHENIX GitHub at line 682 of file Draw_HFJetTruth3yr.C
References assert, GetZgPrediction(), i, and myAnalysis::pt_max.
Referenced by CrossSection2zg().
void Draw_HFJetTruth3yr (const TString infile = "/sphenix/user/jinhuang/HF-jet/event_gen/200pp_pythia8_CTEQ6L_7GeV/200pp_pythia8_CTEQ6L_7GeV_ALL.cfg_eneg_DSTReader.root", double int_lumi = 891093 / 3.332e-02 / 1e9, const double dy = 0.6 * 2)
Definition at line 1846 of file Draw_HFJetTruth3yr.C.
View newest version in sPHENIX GitHub at line 1846 of file Draw_HFJetTruth3yr.C
References _file0, assert, CrossSection2zg(), infile, n, SetsPhenixStyle(), t, and Acts::UnitConstants::T.
void Draw_HFJetTruth_DrawCrossSection_PR (const TString infile)
Definition at line 1678 of file Draw_HFJetTruth3yr.C.
View newest version in sPHENIX GitHub at line 1678 of file Draw_HFJetTruth3yr.C
References _file0, assert, f, GetFONLL_B(), GetFONLL_C(), GetPHENIX_jet(), h_b, hall, ambiguity_solver_full_chain::idx, leg, merge_hashes::p, and SaveCanvas().
void DrawCrossSection (double int_lumi, const double dy)
Definition at line 1559 of file Draw_HFJetTruth3yr.C.
View newest version in sPHENIX GitHub at line 1559 of file Draw_HFJetTruth3yr.C
References _file0, Convert2CrossSection(), GetFONLL_B(), GetFONLL_C(), GetPHENIX_jet(), h_b, hall, ambiguity_solver_full_chain::idx, leg, merge_hashes::p, SaveCanvas(), and Acts::UnitConstants::T.
TGraphAsymmErrors* GetFONLL_B ()
TGraphAsymmErrors* GetFONLL_C ()
TGraph* GetPHENIX_jet ()
TGraphErrors* GetRAA (TH1 * h_pp, TH1 * h_AA)
Definition at line 78 of file Draw_HFJetTruth3yr.C.
View newest version in sPHENIX GitHub at line 78 of file Draw_HFJetTruth3yr.C
References assert, and i.
TGraphErrors* GetZgPrediction (const TString data_config = "me_bbg")
Definition at line 262 of file Draw_HFJetTruth3yr.C.
View newest version in sPHENIX GitHub at line 262 of file Draw_HFJetTruth3yr.C
References assert, i, and integral().
Referenced by CrossSection2zg(), and CrossSection2zg_HistogramMaker().
TGraph * LIDO_Ke ()
Definition at line 1417 of file Draw_HFJetTruth3yr.C.
View newest version in sPHENIX GitHub at line 1417 of file Draw_HFJetTruth3yr.C
References i, and graph_fancy::pT.
Referenced by CrossSection2RAA().
TGraph* pQCDModel_HuangKangVitev (const double g)
Variable Documentation
TFile* _file0 = NULL
Definition at line 38 of file Draw_HFJetTruth3yr.C.
View newest version in sPHENIX GitHub at line 38 of file Draw_HFJetTruth3yr.C
TTree* T = NULL
Definition at line 39 of file Draw_HFJetTruth3yr.C.
View newest version in sPHENIX GitHub at line 39 of file Draw_HFJetTruth3yr.C