Analysis Software: PHG4OHCalSteppingAction Class Reference
PHG4OHCalSteppingAction Class Reference
#include <coresoftware/blob/master/simulation/g4simulation/g4ohcal/PHG4OHCalSteppingAction.h>
Public Member Functions
PHG4OHCalSteppingAction (PHG4OHCalDetector *, const PHParameters *parameters)
constructor
~PHG4OHCalSteppingAction () override
destructor
bool UserSteppingAction (const G4Step *, bool) override
stepping action
int InitWithNode (PHCompositeNode *topNode) override
void SetInterfacePointers (PHCompositeNode *) override
reimplemented from base class
void SetHitNodeName (const std::string &type, const std::string &name) override
Set the G4HIT node names from Subsystem rather than constructing your own.
void FieldChecker (const G4Step *)
void EnableFieldChecker (const int i=1)
void CreateNodeTree (PHCompositeNode *topNode)
Public Member Functions inherited from PHG4SteppingAction
PHG4SteppingAction (const std::string &name, const int i=0)
virtual ~PHG4SteppingAction ()
virtual void Verbosity (const int i)
virtual int Verbosity () const
virtual int Init ()
virtual double GetScintLightYield (const G4Step *step)
get scintillation photon count. It require a custom set SCINTILLATIONYIELD property to work
virtual double GetVisibleEnergyDeposition (const G4Step *step)
get amount of energy that can make scintillation light, in Unit of GeV.
virtual void StoreLocalCoordinate (PHG4Hit *hit, const G4Step *step, const bool do_prepoint, const bool do_postpoint)
Extract local coordinate of the hit and save to PHG4Hit.
virtual void Print (const std::string &) const
std::string GetName () const
void SetName (const std::string &name)
virtual void SetLightCorrection (const double inner_radius, const double inner_corr, const double outer_radius, const double outer_corr)
virtual double GetLightCorrection (const double r) const
virtual double GetLightCorrection (const double xpos, const double ypos) const
virtual bool ValidCorrection () const
Private Member Functions
bool NoHitSteppingAction (const G4Step *aStep)
Private Attributes
PHG4OHCalDetector * m_Detector = nullptr
pointer to the detector
TH2 * m_MapCorrHist [24] = {0}
efficiency maps from Mephi
TH2 * m_MapCorrHistChim [24] = {0}
PHG4HitContainer * m_HitContainer = nullptr
pointer to hit container
PHG4HitContainer * m_AbsorberHitContainer = nullptr
PHG4Hit * m_Hit = nullptr
const PHParameters * m_Params = nullptr
PHG4HitContainer * m_SaveHitContainer = nullptr
PHG4Shower * m_SaveShower = nullptr
G4VPhysicalVolume * m_SaveVolPre = nullptr
G4VPhysicalVolume * m_SaveVolPost = nullptr
int m_SaveTrackId = -1
int m_SavePreStepStatus = -1
int m_SavePostStepStatus = -1
int m_EnableFieldCheckerFlag = -1
int m_IsActiveFlag = 0
int m_IsBlackHoleFlag = 0
int m_NScintiPlates = -1
int m_LightScintModelFlag = 0
bool m_doG4Hit = true
double m_tmin = -20.
double m_tmax = 60.
double m_dt = 100.
std::string m_AbsorberNodeName
std::string m_HitNodeName
TowerInfoContainer * m_CaloInfoContainer = nullptr
Detailed Description
Definition at line 21 of file PHG4OHCalSteppingAction.h.
View newest version in sPHENIX GitHub at line 21 of file PHG4OHCalSteppingAction.h
Constructor & Destructor Documentation
PHG4OHCalSteppingAction::PHG4OHCalSteppingAction (PHG4OHCalDetector * detector, const PHParameters * parameters)
constructor
Definition at line 77 of file PHG4OHCalSteppingAction.cc.
View newest version in sPHENIX GitHub at line 77 of file PHG4OHCalSteppingAction.cc
References Acts::UnitConstants::cm, PHParameters::get_double_param(), m_Params, and PHG4SteppingAction::SetLightCorrection().
PHG4OHCalSteppingAction::~PHG4OHCalSteppingAction () override
destructor
Definition at line 97 of file PHG4OHCalSteppingAction.cc.
View newest version in sPHENIX GitHub at line 97 of file PHG4OHCalSteppingAction.cc
References it, j, m_Hit, m_MapCorrHist, and m_MapCorrHistChim.
Member Function Documentation
void PHG4OHCalSteppingAction::CreateNodeTree (PHCompositeNode * topNode)
Definition at line 735 of file PHG4OHCalSteppingAction.cc.
View newest version in sPHENIX GitHub at line 735 of file PHG4OHCalSteppingAction.cc
References PHCompositeNode::addNode(), PHNodeIterator::findFirst(), m_CaloInfoContainer, m_Detector, PHCompositeNode::PHCompositeNode(), and PHG4OHCalDetector::SuperDetector().
Referenced by InitWithNode().
void PHG4OHCalSteppingAction::EnableFieldChecker (const int i = 1) inline
Definition at line 41 of file PHG4OHCalSteppingAction.h.
View newest version in sPHENIX GitHub at line 41 of file PHG4OHCalSteppingAction.h
References i, and m_EnableFieldCheckerFlag.
void PHG4OHCalSteppingAction::FieldChecker (const G4Step * aStep)
Definition at line 644 of file PHG4OHCalSteppingAction.cc.
View newest version in sPHENIX GitHub at line 644 of file PHG4OHCalSteppingAction.cc
References assert, Acts::IntegrationTest::Bz, Acts::UnitConstants::cm, Fun4AllServer::getHisto(), h, Fun4AllServer::instance(), Fun4AllServer::isHistoRegistered(), and Fun4AllServer::registerHisto().
Referenced by NoHitSteppingAction(), and UserSteppingAction().
int PHG4OHCalSteppingAction::InitWithNode (PHCompositeNode * topNode) override virtual
Reimplemented from PHG4SteppingAction.
Definition at line 116 of file PHG4OHCalSteppingAction.cc.
View newest version in sPHENIX GitHub at line 116 of file PHG4OHCalSteppingAction.cc
References Fun4AllReturnCodes::ABORTRUN, CreateNodeTree(), Acts::UnitConstants::e, Acts::Concepts::exists, file, PHParameters::get_int_param(), PHParameters::get_string_param(), i, m_doG4Hit, m_EnableFieldCheckerFlag, m_LightScintModelFlag, m_MapCorrHist, m_MapCorrHistChim, m_Params, PHWHERE, PHCompositeNode::print(), to_string(), and PHG4SteppingAction::Verbosity().
bool PHG4OHCalSteppingAction::NoHitSteppingAction (const G4Step * aStep) private
Definition at line 179 of file PHG4OHCalSteppingAction.cc.
View newest version in sPHENIX GitHub at line 179 of file PHG4OHCalSteppingAction.cc
References Acts::UnitConstants::cm, double(), TowerInfoDefs::encode_hcal(), FieldChecker(), TowerInfo::get_energy(), TowerInfoContainer::get_tower_at_key(), PHG4SteppingAction::GetLightCorrection(), PHG4OHCalDetector::GetRowColumnId(), PHG4SteppingAction::GetVisibleEnergyDeposition(), Acts::UnitConstants::GeV, PHG4OHCalDetector::IsInOHCal(), m_CaloInfoContainer, m_Detector, m_dt, m_EnableFieldCheckerFlag, m_IsActiveFlag, m_LightScintModelFlag, m_MapCorrHist, m_MapCorrHistChim, m_tmax, merge_hashes::p, and TowerInfo::set_energy().
Referenced by UserSteppingAction().
void PHG4OHCalSteppingAction::SetHitNodeName (const std::string & , const std::string &) override virtual
Set the G4HIT node names from Subsystem rather than constructing your own.
Reimplemented from PHG4SteppingAction.
Definition at line 718 of file PHG4OHCalSteppingAction.cc.
View newest version in sPHENIX GitHub at line 718 of file PHG4OHCalSteppingAction.cc
References m_AbsorberNodeName, m_HitNodeName, and perf_headwind::name.
void PHG4OHCalSteppingAction::SetInterfacePointers (PHCompositeNode * topNode) override virtual
reimplemented from base class
Reimplemented from PHG4SteppingAction.
Definition at line 625 of file PHG4OHCalSteppingAction.cc.
View newest version in sPHENIX GitHub at line 625 of file PHG4OHCalSteppingAction.cc
References m_AbsorberHitContainer, m_AbsorberNodeName, m_HitContainer, m_HitNodeName, and PHG4SteppingAction::Verbosity().
bool PHG4OHCalSteppingAction::UserSteppingAction (const G4Step * aStep, bool) override virtual
stepping action
Implements PHG4SteppingAction.
Definition at line 302 of file PHG4OHCalSteppingAction.cc.
View newest version in sPHENIX GitHub at line 302 of file PHG4OHCalSteppingAction.cc
References PHG4Shower::add_g4hit_id(), PHG4HitContainer::AddHit(), Acts::UnitConstants::cm, double(), FieldChecker(), PHG4Hit::get_edep(), PHG4Hit::get_eion(), PHG4Hit::get_hit_id(), PHG4Hit::get_light_yield(), PHG4Hit::get_raw_light_yield(), PHG4Hit::get_x(), PHG4HitContainer::GetID(), PHG4SteppingAction::GetLightCorrection(), PHG4SteppingAction::GetName(), PHG4OHCalDetector::GetRowColumnId(), PHG4StepStatusDecode::GetStepStatus(), PHG4SteppingAction::GetVisibleEnergyDeposition(), Acts::UnitConstants::GeV, PHG4OHCalDetector::IsInOHCal(), m_AbsorberHitContainer, m_Detector, m_doG4Hit, m_EnableFieldCheckerFlag, m_Hit, m_HitContainer, m_IsActiveFlag, m_IsBlackHoleFlag, m_LightScintModelFlag, m_MapCorrHist, m_MapCorrHistChim, m_SaveHitContainer, m_SavePostStepStatus, m_SavePreStepStatus, m_SaveShower, m_SaveTrackId, m_SaveVolPost, m_SaveVolPre, NoHitSteppingAction(), merge_hashes::p, PHG4Hit::Reset(), PHG4Hit::set_edep(), PHG4Hit::set_eion(), PHG4Hit::set_light_yield(), PHG4Hit::set_raw_light_yield(), PHG4Hit::set_scint_id(), PHG4Hit::set_sector(), PHG4Hit::set_shower_id(), PHG4Hit::set_t(), PHG4Hit::set_trkid(), PHG4Hit::set_x(), PHG4Hit::set_y(), and PHG4Hit::set_z().
Member Data Documentation
PHG4HitContainer* PHG4OHCalSteppingAction::m_AbsorberHitContainer = nullptr private
Definition at line 54 of file PHG4OHCalSteppingAction.h.
View newest version in sPHENIX GitHub at line 54 of file PHG4OHCalSteppingAction.h
Referenced by SetInterfacePointers(), and UserSteppingAction().
std::string PHG4OHCalSteppingAction::m_AbsorberNodeName private
Definition at line 77 of file PHG4OHCalSteppingAction.h.
View newest version in sPHENIX GitHub at line 77 of file PHG4OHCalSteppingAction.h
Referenced by SetHitNodeName(), and SetInterfacePointers().
TowerInfoContainer* PHG4OHCalSteppingAction::m_CaloInfoContainer = nullptr private
Definition at line 80 of file PHG4OHCalSteppingAction.h.
View newest version in sPHENIX GitHub at line 80 of file PHG4OHCalSteppingAction.h
Referenced by CreateNodeTree(), and NoHitSteppingAction().
PHG4OHCalDetector* PHG4OHCalSteppingAction::m_Detector = nullptr private
pointer to the detector
Definition at line 46 of file PHG4OHCalSteppingAction.h.
View newest version in sPHENIX GitHub at line 46 of file PHG4OHCalSteppingAction.h
Referenced by CreateNodeTree(), NoHitSteppingAction(), and UserSteppingAction().
bool PHG4OHCalSteppingAction::m_doG4Hit = true private
Definition at line 73 of file PHG4OHCalSteppingAction.h.
View newest version in sPHENIX GitHub at line 73 of file PHG4OHCalSteppingAction.h
Referenced by InitWithNode(), and UserSteppingAction().
double PHG4OHCalSteppingAction::m_dt = 100. private
Definition at line 76 of file PHG4OHCalSteppingAction.h.
View newest version in sPHENIX GitHub at line 76 of file PHG4OHCalSteppingAction.h
Referenced by NoHitSteppingAction().
int PHG4OHCalSteppingAction::m_EnableFieldCheckerFlag = -1 private
Definition at line 64 of file PHG4OHCalSteppingAction.h.
View newest version in sPHENIX GitHub at line 64 of file PHG4OHCalSteppingAction.h
Referenced by EnableFieldChecker(), InitWithNode(), NoHitSteppingAction(), and UserSteppingAction().
PHG4Hit* PHG4OHCalSteppingAction::m_Hit = nullptr private
Definition at line 55 of file PHG4OHCalSteppingAction.h.
View newest version in sPHENIX GitHub at line 55 of file PHG4OHCalSteppingAction.h
Referenced by UserSteppingAction(), and ~PHG4OHCalSteppingAction().
PHG4HitContainer* PHG4OHCalSteppingAction::m_HitContainer = nullptr private
pointer to hit container
Definition at line 53 of file PHG4OHCalSteppingAction.h.
View newest version in sPHENIX GitHub at line 53 of file PHG4OHCalSteppingAction.h
Referenced by SetInterfacePointers(), and UserSteppingAction().
std::string PHG4OHCalSteppingAction::m_HitNodeName private
Definition at line 78 of file PHG4OHCalSteppingAction.h.
View newest version in sPHENIX GitHub at line 78 of file PHG4OHCalSteppingAction.h
Referenced by SetHitNodeName(), and SetInterfacePointers().
int PHG4OHCalSteppingAction::m_IsActiveFlag = 0 private
Definition at line 69 of file PHG4OHCalSteppingAction.h.
View newest version in sPHENIX GitHub at line 69 of file PHG4OHCalSteppingAction.h
Referenced by NoHitSteppingAction(), and UserSteppingAction().
int PHG4OHCalSteppingAction::m_IsBlackHoleFlag = 0 private
Definition at line 70 of file PHG4OHCalSteppingAction.h.
View newest version in sPHENIX GitHub at line 70 of file PHG4OHCalSteppingAction.h
Referenced by UserSteppingAction().
int PHG4OHCalSteppingAction::m_LightScintModelFlag = 0 private
Definition at line 72 of file PHG4OHCalSteppingAction.h.
View newest version in sPHENIX GitHub at line 72 of file PHG4OHCalSteppingAction.h
Referenced by InitWithNode(), NoHitSteppingAction(), and UserSteppingAction().
TH2* PHG4OHCalSteppingAction::m_MapCorrHist[24] = {0} private
efficiency maps from Mephi
Definition at line 49 of file PHG4OHCalSteppingAction.h.
View newest version in sPHENIX GitHub at line 49 of file PHG4OHCalSteppingAction.h
Referenced by InitWithNode(), NoHitSteppingAction(), UserSteppingAction(), and ~PHG4OHCalSteppingAction().
TH2* PHG4OHCalSteppingAction::m_MapCorrHistChim[24] = {0} private
Definition at line 50 of file PHG4OHCalSteppingAction.h.
View newest version in sPHENIX GitHub at line 50 of file PHG4OHCalSteppingAction.h
Referenced by InitWithNode(), NoHitSteppingAction(), UserSteppingAction(), and ~PHG4OHCalSteppingAction().
int PHG4OHCalSteppingAction::m_NScintiPlates = -1 private
Definition at line 71 of file PHG4OHCalSteppingAction.h.
View newest version in sPHENIX GitHub at line 71 of file PHG4OHCalSteppingAction.h
const PHParameters* PHG4OHCalSteppingAction::m_Params = nullptr private
Definition at line 56 of file PHG4OHCalSteppingAction.h.
View newest version in sPHENIX GitHub at line 56 of file PHG4OHCalSteppingAction.h
Referenced by InitWithNode(), and PHG4OHCalSteppingAction().
PHG4HitContainer* PHG4OHCalSteppingAction::m_SaveHitContainer = nullptr private
Definition at line 57 of file PHG4OHCalSteppingAction.h.
View newest version in sPHENIX GitHub at line 57 of file PHG4OHCalSteppingAction.h
Referenced by UserSteppingAction().
int PHG4OHCalSteppingAction::m_SavePostStepStatus = -1 private
Definition at line 63 of file PHG4OHCalSteppingAction.h.
View newest version in sPHENIX GitHub at line 63 of file PHG4OHCalSteppingAction.h
Referenced by UserSteppingAction().
int PHG4OHCalSteppingAction::m_SavePreStepStatus = -1 private
Definition at line 62 of file PHG4OHCalSteppingAction.h.
View newest version in sPHENIX GitHub at line 62 of file PHG4OHCalSteppingAction.h
Referenced by UserSteppingAction().
PHG4Shower* PHG4OHCalSteppingAction::m_SaveShower = nullptr private
Definition at line 58 of file PHG4OHCalSteppingAction.h.
View newest version in sPHENIX GitHub at line 58 of file PHG4OHCalSteppingAction.h
Referenced by UserSteppingAction().
int PHG4OHCalSteppingAction::m_SaveTrackId = -1 private
Definition at line 61 of file PHG4OHCalSteppingAction.h.
View newest version in sPHENIX GitHub at line 61 of file PHG4OHCalSteppingAction.h
Referenced by UserSteppingAction().
G4VPhysicalVolume* PHG4OHCalSteppingAction::m_SaveVolPost = nullptr private
Definition at line 60 of file PHG4OHCalSteppingAction.h.
View newest version in sPHENIX GitHub at line 60 of file PHG4OHCalSteppingAction.h
Referenced by UserSteppingAction().
G4VPhysicalVolume* PHG4OHCalSteppingAction::m_SaveVolPre = nullptr private
Definition at line 59 of file PHG4OHCalSteppingAction.h.
View newest version in sPHENIX GitHub at line 59 of file PHG4OHCalSteppingAction.h
Referenced by UserSteppingAction().
double PHG4OHCalSteppingAction::m_tmax = 60. private
Definition at line 75 of file PHG4OHCalSteppingAction.h.
View newest version in sPHENIX GitHub at line 75 of file PHG4OHCalSteppingAction.h
Referenced by NoHitSteppingAction().
double PHG4OHCalSteppingAction::m_tmin = -20. private
Definition at line 74 of file PHG4OHCalSteppingAction.h.
View newest version in sPHENIX GitHub at line 74 of file PHG4OHCalSteppingAction.h
The documentation for this class was generated from the following files:
coresoftware/blob/master/simulation/g4simulation/g4ohcal/PHG4OHCalSteppingAction.h
coresoftware/blob/master/simulation/g4simulation/g4ohcal/PHG4OHCalSteppingAction.cc