Analysis Software: geant4 Namespace Reference
geant4 Namespace Reference
Functions
def runGeant4
Variables
u acts.UnitConstants
tuple field acts.ConstantBField(acts.Vector3(0, 0, 2 * u.T))
Function Documentation
def geant4.runGeant4 (detector, trackingGeometry, field, outputDir, s)
Definition at line 18 of file geant4.py.
View newest version in sPHENIX GitHub at line 18 of file geant4.py
References acts.examples.simulation.addGeant4(), acts.examples.simulation.addParticleGun(), acts.examples.simulation.EtaConfig, acts.examples.odd.getOpenDataDetector(), and common.getOpenDataDetectorDirectory().
Variable Documentation
tuple geant4.field acts.ConstantBField(acts.Vector3(0, 0, 2 * u.T))
Definition at line 46 of file geant4.py.
View newest version in sPHENIX GitHub at line 46 of file geant4.py
geant4.u acts.UnitConstants
Definition at line 10 of file geant4.py.
View newest version in sPHENIX GitHub at line 10 of file geant4.py