Analysis Software: MicromegasCalibrationData Class Reference
MicromegasCalibrationData Class Reference
micromegas calibration data
#include <coresoftware/blob/master/offline/packages/micromegas/MicromegasCalibrationData.h>
Classes
class calibration_data_t
simple structure to store calibration data
Public Member Functions
MicromegasCalibrationData ()=default
constructor
modifiers
void read (const std::string &)
read calibration from file
void set_pedestal (int, int, double)
set pedestal for a given channel
void set_rms (int, int, double)
set rms for a given channel
accessors
void write (const std::string &) const
write calibration to file
double get_pedestal (int, int) const
get pedestal for a given feeid and channel
double get_rms (int, int) const
get rms for a given feeid and channel
double get_pedestal_mapped (TrkrDefs::hitsetkey, int) const
get pedestal for a given hitsetkey and strip
double get_rms_mapped (TrkrDefs::hitsetkey, int) const
get rms for a given hitsetkey and strip
Private Types
using calibration_vector_t = std::array< calibration_data_t, m_nchannels_fee >
using raw_calibration_map_t = std::map< int, calibration_vector_t >
map fee id to channel based calibration vector
using mapped_calibration_map_t = std::map< TrkrDefs::hitsetkey, calibration_vector_t >
map hitset key to strip based calibration vector
Private Attributes
raw_calibration_map_t m_raw_calibration_map
mapped_calibration_map_t m_mapped_calibration_map
Static Private Attributes
static constexpr int m_nchannels_fee = 256
Friends
std::ostream & operator<< (std::ostream &, const MicromegasCalibrationData &)
Detailed Description
micromegas calibration data
Definition at line 16 of file MicromegasCalibrationData.h.
View newest version in sPHENIX GitHub at line 16 of file MicromegasCalibrationData.h
Member Typedef Documentation
using MicromegasCalibrationData::calibration_vector_t = std::array<calibration_data_t,m_nchannels_fee> private
Definition at line 76 of file MicromegasCalibrationData.h.
View newest version in sPHENIX GitHub at line 76 of file MicromegasCalibrationData.h
using MicromegasCalibrationData::mapped_calibration_map_t = std::map<TrkrDefs::hitsetkey,calibration_vector_t> private
map hitset key to strip based calibration vector
Definition at line 83 of file MicromegasCalibrationData.h.
View newest version in sPHENIX GitHub at line 83 of file MicromegasCalibrationData.h
using MicromegasCalibrationData::raw_calibration_map_t = std::map<int, calibration_vector_t> private
map fee id to channel based calibration vector
Definition at line 79 of file MicromegasCalibrationData.h.
View newest version in sPHENIX GitHub at line 79 of file MicromegasCalibrationData.h
Constructor & Destructor Documentation
MicromegasCalibrationData::MicromegasCalibrationData () default
constructor
Member Function Documentation
double MicromegasCalibrationData::get_pedestal (int fee, int channel) const
get pedestal for a given feeid and channel
Definition at line 135 of file MicromegasCalibrationData.cc.
View newest version in sPHENIX GitHub at line 135 of file MicromegasCalibrationData.cc
References m_raw_calibration_map.
Referenced by TpotMon::process_event(), MicromegasRawDataDecoder::process_event(), MicromegasCombinedDataDecoder::process_event(), MicromegasRawDataEvaluation::process_event(), and MicromegasCombinedDataEvaluation::process_event().
double MicromegasCalibrationData::get_pedestal_mapped (TrkrDefs::hitsetkey hitsetkey, int strip) const
get pedestal for a given hitsetkey and strip
Definition at line 149 of file MicromegasCalibrationData.cc.
View newest version in sPHENIX GitHub at line 149 of file MicromegasCalibrationData.cc
References m_mapped_calibration_map.
Referenced by MicromegasClusterizer::process_event().
double MicromegasCalibrationData::get_rms (int fee, int channel) const
get rms for a given feeid and channel
Definition at line 142 of file MicromegasCalibrationData.cc.
View newest version in sPHENIX GitHub at line 142 of file MicromegasCalibrationData.cc
References m_raw_calibration_map.
Referenced by TpotMon::process_event(), MicromegasRawDataDecoder::process_event(), MicromegasCombinedDataDecoder::process_event(), MicromegasRawDataEvaluation::process_event(), and MicromegasCombinedDataEvaluation::process_event().
double MicromegasCalibrationData::get_rms_mapped (TrkrDefs::hitsetkey hitsetkey, int strip) const
get rms for a given hitsetkey and strip
Definition at line 156 of file MicromegasCalibrationData.cc.
View newest version in sPHENIX GitHub at line 156 of file MicromegasCalibrationData.cc
References m_mapped_calibration_map.
void MicromegasCalibrationData::read (const std::string & filename)
read calibration from file
Definition at line 45 of file MicromegasCalibrationData.cc.
View newest version in sPHENIX GitHub at line 45 of file MicromegasCalibrationData.cc
References channel(), MicromegasMapping::get_fee_id_list(), MicromegasMapping::get_hitsetkey(), MicromegasMapping::get_physical_strip(), CDBTTree::GetDoubleValue(), i, CDBTTree::LoadCalibrations(), m_mapped_calibration_map, m_nchannels_fee, m_raw_calibration_map, pedestal(), and rms().
Referenced by MicromegasClusterizer::Init(), TpotMon::Init(), MicromegasRawDataDecoder::Init(), MicromegasCombinedDataDecoder::Init(), MicromegasCombinedDataEvaluation::Init(), and MicromegasRawDataEvaluation::Init().
void MicromegasCalibrationData::set_pedestal (int fee, int channel, double value)
set pedestal for a given channel
Definition at line 102 of file MicromegasCalibrationData.cc.
View newest version in sPHENIX GitHub at line 102 of file MicromegasCalibrationData.cc
References m_raw_calibration_map, and value.
Referenced by MicromegasRawDataCalibration::End().
void MicromegasCalibrationData::set_rms (int fee, int channel, double value)
set rms for a given channel
Definition at line 106 of file MicromegasCalibrationData.cc.
View newest version in sPHENIX GitHub at line 106 of file MicromegasCalibrationData.cc
References m_raw_calibration_map, and value.
Referenced by MicromegasRawDataCalibration::End().
void MicromegasCalibrationData::write (const std::string & filename) const
write calibration to file
Definition at line 110 of file MicromegasCalibrationData.cc.
View newest version in sPHENIX GitHub at line 110 of file MicromegasCalibrationData.cc
References TauVsDIS_MachineLearning_Differentiation::array, channel(), CDBTTree::Commit(), i, m_nchannels_fee, m_raw_calibration_map, pedestal(), rms(), CDBTTree::SetDoubleValue(), and CDBTTree::WriteCDBTTree().
Referenced by MicromegasRawDataCalibration::End().
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & out, const MicromegasCalibrationData & calib_data) friend
Definition at line 23 of file MicromegasCalibrationData.cc.
View newest version in sPHENIX GitHub at line 23 of file MicromegasCalibrationData.cc
Member Data Documentation
mapped_calibration_map_t MicromegasCalibrationData::m_mapped_calibration_map private
Definition at line 84 of file MicromegasCalibrationData.h.
View newest version in sPHENIX GitHub at line 84 of file MicromegasCalibrationData.h
Referenced by get_pedestal_mapped(), get_rms_mapped(), and read().
constexpr int MicromegasCalibrationData::m_nchannels_fee = 256 static private
Definition at line 75 of file MicromegasCalibrationData.h.
View newest version in sPHENIX GitHub at line 75 of file MicromegasCalibrationData.h
Referenced by read(), and write().
raw_calibration_map_t MicromegasCalibrationData::m_raw_calibration_map private
Definition at line 80 of file MicromegasCalibrationData.h.
View newest version in sPHENIX GitHub at line 80 of file MicromegasCalibrationData.h
Referenced by get_pedestal(), get_rms(), operator<<(), read(), set_pedestal(), set_rms(), and write().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/micromegas/MicromegasCalibrationData.h
coresoftware/blob/master/offline/packages/micromegas/MicromegasCalibrationData.cc