Analysis Software: Acts::AdaptiveMultiVertexFinder< vfitter_t, sfinder_t > Class Template Reference
Acts::AdaptiveMultiVertexFinder< vfitter_t, sfinder_t > Class Template Reference
Implements an iterative vertex finder.
#include <acts/blob/sPHENIX/Core/include/Acts/Vertexing/AdaptiveMultiVertexFinder.hpp>
Classes
struct Config
Configuration struct.
struct NeedsRemovedTracks
struct NeedsRemovedTracks< T, decltype((void) T::tracksToRemove, 0)>
struct State
State struct for fulfilling interface.
Public Member Functions
template<typename T = InputTrack_t, std::enable_if_t< std::is_same< T, BoundTrackParameters >::value, int > = 0>
AdaptiveMultiVertexFinder (Config &cfg, std::unique_ptr< const Logger > logger=getDefaultLogger("AdaptiveMultiVertexFinder", Logging::INFO))
Constructor used if InputTrack_t type == BoundTrackParameters.
m_logger (std::move(logger))
AdaptiveMultiVertexFinder (Config &cfg, std::function< BoundTrackParameters(InputTrack_t)> func, std::unique_ptr< const Logger > logger=getDefaultLogger("AdaptiveMultiVertexFinder", Logging::INFO))
Constructor for user-defined InputTrack_t type != BoundTrackParameters.
AdaptiveMultiVertexFinder (AdaptiveMultiVertexFinder &&)=default
Result< std::vector< Vertex
< InputTrack_t > > > find (const std::vector< const InputTrack_t * > &allTracks, const VertexingOptions< InputTrack_t > &vertexingOptions, State &state) const
Function that performs the adaptive multi-vertex finding.
Private Types
using Propagator_t = typename vfitter_t::Propagator_t
using InputTrack_t = typename vfitter_t::InputTrack_t
using Linearizer_t = typename vfitter_t::Linearizer_t
using FitterState_t = typename vfitter_t::State
using SeedFinderState_t = typename sfinder_t::State
Private Member Functions
const Logger & logger () const
Private access to logging instance.
Result< Vertex< InputTrack_t > > doSeeding (const std::vector< const InputTrack_t * > &trackVector, Vertex< InputTrack_t > &currentConstraint, const VertexingOptions< InputTrack_t > &vertexingOptions, SeedFinderState_t &seedFinderState, const std::vector< const InputTrack_t * > &removedSeedTracks) const
Calls the seed finder and sets constraints on the found seed vertex if desired.
void setConstraintAfterSeeding (Vertex< InputTrack_t > &currentConstraint, bool useVertexConstraintInFit, Vertex< InputTrack_t > &seedVertex) const
Sets constraint vertex after seeding.
Result< double > getIPSignificance (const InputTrack_t *track, const Vertex< InputTrack_t > &vtx, const VertexingOptions< InputTrack_t > &vertexingOptions) const
Calculates the IP significance of a track to a given vertex.
Result< void > addCompatibleTracksToVertex (const std::vector< const InputTrack_t * > &tracks, Vertex< InputTrack_t > &vtx, FitterState_t &fitterState, const VertexingOptions< InputTrack_t > &vertexingOptions) const
Adds compatible track to vertex candidate.
Result< bool > canRecoverFromNoCompatibleTracks (const std::vector< const InputTrack_t * > &allTracks, const std::vector< const InputTrack_t * > &seedTracks, Vertex< InputTrack_t > &vtx, const Vertex< InputTrack_t > &currentConstraint, FitterState_t &fitterState, const VertexingOptions< InputTrack_t > &vertexingOptions) const
Method that tries to recover from cases where no tracks were added to the vertex candidate after seeding.
Result< bool > canPrepareVertexForFit (const std::vector< const InputTrack_t * > &allTracks, const std::vector< const InputTrack_t * > &seedTracks, Vertex< InputTrack_t > &vtx, const Vertex< InputTrack_t > &currentConstraint, FitterState_t &fitterState, const VertexingOptions< InputTrack_t > &vertexingOptions) const
Method that tries to prepare the vertex for the fit.
std::pair< int, bool > checkVertexAndCompatibleTracks (Vertex< InputTrack_t > &vtx, const std::vector< const InputTrack_t * > &seedTracks, FitterState_t &fitterState, bool useVertexConstraintInFit) const
Method that checks if vertex is a good vertex and if compatible tracks are available.
void removeCompatibleTracksFromSeedTracks (Vertex< InputTrack_t > &vtx, std::vector< const InputTrack_t * > &seedTracks, FitterState_t &fitterState, std::vector< const InputTrack_t * > &removedSeedTracks) const
Method that removes all tracks that are compatible with current vertex from seedTracks.
bool removeTrackIfIncompatible (Vertex< InputTrack_t > &vtx, std::vector< const InputTrack_t * > &seedTracks, FitterState_t &fitterState, std::vector< const InputTrack_t * > &removedSeedTracks, const GeometryContext &geoCtx) const
Method that tries to remove an incompatible track from seed tracks after removing a compatible track failed.
bool keepNewVertex (Vertex< InputTrack_t > &vtx, const std::vector< Vertex< InputTrack_t > * > &allVertices, FitterState_t &fitterState) const
Method that evaluates if the new vertex candidate should be kept, i.e. saved, or not.
bool isMergedVertex (const Vertex< InputTrack_t > &vtx, const std::vector< Vertex< InputTrack_t > * > &allVertices) const
Method that evaluates if the new vertex candidate is merged with one of the previously found vertices.
Result< void > deleteLastVertex (Vertex< InputTrack_t > &vtx, std::vector< std::unique_ptr< Vertex< InputTrack_t >>> &allVertices, std::vector< Vertex< InputTrack_t > * > &allVerticesPtr, FitterState_t &fitterState, const VertexingOptions< InputTrack_t > &vertexingOptions) const
Method that deletes last vertex from list of all vertices and refits all vertices afterwards.
Result< std::vector< Vertex
< InputTrack_t > > > getVertexOutputList (const std::vector< Vertex< InputTrack_t > * > &allVerticesPtr, FitterState_t &fitterState) const
Prepares the output vector of vertices.
Private Attributes
Config m_cfg
Configuration object.
std::function
< BoundTrackParameters(InputTrack_t)> m_extractParameters
Function to extract track parameters, InputTrack_t objects are BoundTrackParameters by default, function to be overwritten to return BoundTrackParameters for other InputTrack_t objects.
std::unique_ptr< const Logger > m_logger
Logging instance.
Detailed Description
template<typename vfitter_t, typename sfinder_t>
class Acts::AdaptiveMultiVertexFinder< vfitter_t, sfinder_t >
Implements an iterative vertex finder.
Brief description of the algorithm implemented: TODO
Template Parameters
vfitter_t Vertex fitter type
sfinder_t Seed finder type
Definition at line 35 of file AdaptiveMultiVertexFinder.hpp.
View newest version in sPHENIX GitHub at line 35 of file AdaptiveMultiVertexFinder.hpp
Member Typedef Documentation
template<typename vfitter_t , typename sfinder_t > using Acts::AdaptiveMultiVertexFinder< vfitter_t, sfinder_t >::FitterState_t = typename vfitter_t::State private
Definition at line 39 of file AdaptiveMultiVertexFinder.hpp.
View newest version in sPHENIX GitHub at line 39 of file AdaptiveMultiVertexFinder.hpp
template<typename vfitter_t , typename sfinder_t > using Acts::AdaptiveMultiVertexFinder< vfitter_t, sfinder_t >::InputTrack_t = typename vfitter_t::InputTrack_t private
Definition at line 37 of file AdaptiveMultiVertexFinder.hpp.
View newest version in sPHENIX GitHub at line 37 of file AdaptiveMultiVertexFinder.hpp
template<typename vfitter_t , typename sfinder_t > using Acts::AdaptiveMultiVertexFinder< vfitter_t, sfinder_t >::Linearizer_t = typename vfitter_t::Linearizer_t private
Definition at line 38 of file AdaptiveMultiVertexFinder.hpp.
View newest version in sPHENIX GitHub at line 38 of file AdaptiveMultiVertexFinder.hpp
template<typename vfitter_t , typename sfinder_t > using Acts::AdaptiveMultiVertexFinder< vfitter_t, sfinder_t >::Propagator_t = typename vfitter_t::Propagator_t private
Definition at line 36 of file AdaptiveMultiVertexFinder.hpp.
View newest version in sPHENIX GitHub at line 36 of file AdaptiveMultiVertexFinder.hpp
template<typename vfitter_t , typename sfinder_t > using Acts::AdaptiveMultiVertexFinder< vfitter_t, sfinder_t >::SeedFinderState_t = typename sfinder_t::State private
Definition at line 40 of file AdaptiveMultiVertexFinder.hpp.
View newest version in sPHENIX GitHub at line 40 of file AdaptiveMultiVertexFinder.hpp
Constructor & Destructor Documentation
template<typename vfitter_t , typename sfinder_t > template<typename T = InputTrack_t, std::enable_if_t< std::is_same< T, BoundTrackParameters >::value, int > = 0> Acts::AdaptiveMultiVertexFinder< vfitter_t, sfinder_t >::AdaptiveMultiVertexFinder (Config & cfg, std::unique_ptr< const Logger > logger = getDefaultLogger("AdaptiveMultiVertexFinder< vfitter_t, sfinder_t >", Logging::INFO)) inline
Constructor used if InputTrack_t type == BoundTrackParameters.
Parameters
cfg Configuration object
logger The logging instance
Definition at line 172 of file AdaptiveMultiVertexFinder.hpp.
View newest version in sPHENIX GitHub at line 172 of file AdaptiveMultiVertexFinder.hpp
template<typename vfitter_t , typename sfinder_t > Acts::AdaptiveMultiVertexFinder< vfitter_t, sfinder_t >::AdaptiveMultiVertexFinder (Config & cfg, std::function< BoundTrackParameters(InputTrack_t)> func, std::unique_ptr< const Logger > logger = getDefaultLogger("AdaptiveMultiVertexFinder< vfitter_t, sfinder_t >", Logging::INFO)) inline
Constructor for user-defined InputTrack_t type != BoundTrackParameters.
Parameters
cfg Configuration object
func Function extracting BoundTrackParameters from InputTrack_t object
logger The logging instance
Definition at line 187 of file AdaptiveMultiVertexFinder.hpp.
View newest version in sPHENIX GitHub at line 187 of file AdaptiveMultiVertexFinder.hpp
template<typename vfitter_t , typename sfinder_t > Acts::AdaptiveMultiVertexFinder< vfitter_t, sfinder_t >::AdaptiveMultiVertexFinder (AdaptiveMultiVertexFinder< vfitter_t, sfinder_t > &&) default
Member Function Documentation
template<typename vfitter_t , typename sfinder_t > auto Acts::AdaptiveMultiVertexFinder< vfitter_t, sfinder_t >::addCompatibleTracksToVertex (const std::vector< const InputTrack_t * > & tracks, Vertex< InputTrack_t > & vtx, FitterState_t & fitterState, const VertexingOptions< InputTrack_t > & vertexingOptions) const private
Adds compatible track to vertex candidate.
Parameters
tracks The tracks
vtx The vertex candidate
[out] fitterState The vertex fitter state
vertexingOptions Vertexing options
Definition at line 226 of file AdaptiveMultiVertexFinder.ipp.
View newest version in sPHENIX GitHub at line 226 of file AdaptiveMultiVertexFinder.ipp
References eZ, m_cfg(), Acts::Test::pos, and tracks().
template<typename vfitter_t , typename sfinder_t > auto Acts::AdaptiveMultiVertexFinder< vfitter_t, sfinder_t >::canPrepareVertexForFit (const std::vector< const InputTrack_t * > & allTracks, const std::vector< const InputTrack_t * > & seedTracks, Vertex< InputTrack_t > & vtx, const Vertex< InputTrack_t > & currentConstraint, FitterState_t & fitterState, const VertexingOptions< InputTrack_t > & vertexingOptions) const private
Method that tries to prepare the vertex for the fit.
Parameters
allTracks The tracks to be considered (either origTrack or seedTracks)
seedTracks The seed tracks
[out] vtx The vertex candidate
currentConstraint Vertex constraint
[out] fitterState The vertex fitter state
vertexingOptions Vertexing options
Returns
True if preparation was successful, false otherwise
Definition at line 317 of file AdaptiveMultiVertexFinder.ipp.
View newest version in sPHENIX GitHub at line 317 of file AdaptiveMultiVertexFinder.ipp
template<typename vfitter_t , typename sfinder_t > auto Acts::AdaptiveMultiVertexFinder< vfitter_t, sfinder_t >::canRecoverFromNoCompatibleTracks (const std::vector< const InputTrack_t * > & allTracks, const std::vector< const InputTrack_t * > & seedTracks, Vertex< InputTrack_t > & vtx, const Vertex< InputTrack_t > & currentConstraint, FitterState_t & fitterState, const VertexingOptions< InputTrack_t > & vertexingOptions) const private
Method that tries to recover from cases where no tracks were added to the vertex candidate after seeding.
Parameters
allTracks The tracks to be considered (either origTrack or seedTracks)
seedTracks The seed tracks
[out] vtx The vertex candidate
currentConstraint Vertex constraint
[out] fitterState The vertex fitter state
vertexingOptions Vertexing options
return True if recovery was successful, false otherwise
Definition at line 258 of file AdaptiveMultiVertexFinder.ipp.
View newest version in sPHENIX GitHub at line 258 of file AdaptiveMultiVertexFinder.ipp
References ACTS_DEBUG, eZ, and Acts::Test::pos.
template<typename vfitter_t , typename sfinder_t > auto Acts::AdaptiveMultiVertexFinder< vfitter_t, sfinder_t >::checkVertexAndCompatibleTracks (Vertex< InputTrack_t > & vtx, const std::vector< const InputTrack_t * > & seedTracks, FitterState_t & fitterState, bool useVertexConstraintInFit) const private
Method that checks if vertex is a good vertex and if compatible tracks are available.
Parameters
vtx The vertex candidate
seedTracks The seed tracks
fitterState The vertex fitter state
useVertexConstraintInFit Indicates whether constraint is used in the vertex fit
Returns
pair(nCompatibleTracks, isGoodVertex)
Definition at line 349 of file AdaptiveMultiVertexFinder.ipp.
View newest version in sPHENIX GitHub at line 349 of file AdaptiveMultiVertexFinder.ipp
References ACTS_DEBUG, and m_cfg().
template<typename vfitter_t , typename sfinder_t > auto Acts::AdaptiveMultiVertexFinder< vfitter_t, sfinder_t >::deleteLastVertex (Vertex< InputTrack_t > & vtx, std::vector< std::unique_ptr< Vertex< InputTrack_t >>> & allVertices, std::vector< Vertex< InputTrack_t > * > & allVerticesPtr, FitterState_t & fitterState, const VertexingOptions< InputTrack_t > & vertexingOptions) const private
Method that deletes last vertex from list of all vertices and refits all vertices afterwards.
Parameters
vtx The last added vertex which will be removed
allVertices Vector containing the unique_ptr to vertices
allVerticesPtr Vector containing the actual addresses
fitterState The current vertex fitter state
vertexingOptions Vertexing options
Definition at line 549 of file AdaptiveMultiVertexFinder.ipp.
View newest version in sPHENIX GitHub at line 549 of file AdaptiveMultiVertexFinder.ipp
References entry, and m_cfg().
template<typename vfitter_t , typename sfinder_t > auto Acts::AdaptiveMultiVertexFinder< vfitter_t, sfinder_t >::doSeeding (const std::vector< const InputTrack_t * > & trackVector, Vertex< InputTrack_t > & currentConstraint, const VertexingOptions< InputTrack_t > & vertexingOptions, SeedFinderState_t & seedFinderState, const std::vector< const InputTrack_t * > & removedSeedTracks) const private
Calls the seed finder and sets constraints on the found seed vertex if desired.
Parameters
trackVector All tracks to be used for seeding
currentConstraint Vertex constraint
vertexingOptions Vertexing options
seedFinderState The seed finder state
removedSeedTracks Seed track that have been removed from seed track collection in last iteration
Returns
The seed vertex
Definition at line 139 of file AdaptiveMultiVertexFinder.ipp.
View newest version in sPHENIX GitHub at line 139 of file AdaptiveMultiVertexFinder.ipp
References Acts::VertexingOptions< input_track_t >::constraint, m_cfg(), and Acts::VertexingOptions< input_track_t >::useConstraintInFit.
template<typename vfitter_t , typename sfinder_t > auto Acts::AdaptiveMultiVertexFinder< vfitter_t, sfinder_t >::find (const std::vector< const InputTrack_t * > & allTracks, const VertexingOptions< InputTrack_t > & vertexingOptions, State & state) const
Function that performs the adaptive multi-vertex finding.
Parameters
allTracks Input track collection
vertexingOptions Vertexing options
state State for fulfilling interfaces
Returns
Vector of all reconstructed vertices
Definition at line 13 of file AdaptiveMultiVertexFinder.ipp.
View newest version in sPHENIX GitHub at line 13 of file AdaptiveMultiVertexFinder.ipp
References ACTS_DEBUG, ACTS_ERROR, Acts::VertexingOptions< input_track_t >::constraint, Acts::Vertex< input_track_t >::fullPosition(), Acts::VertexingOptions< input_track_t >::geoContext, m_cfg(), Acts::VertexingOptions< input_track_t >::magFieldContext, Acts::Vertex< input_track_t >::position(), and Acts::VertexingOptions< input_track_t >::useConstraintInFit.
template<typename vfitter_t , typename sfinder_t > auto Acts::AdaptiveMultiVertexFinder< vfitter_t, sfinder_t >::getIPSignificance (const InputTrack_t * track, const Vertex< InputTrack_t > & vtx, const VertexingOptions< InputTrack_t > & vertexingOptions) const private
Calculates the IP significance of a track to a given vertex.
Parameters
track The track
vtx The vertex
vertexingOptions Vertexing options
Returns
The IP significance
Definition at line 192 of file AdaptiveMultiVertexFinder.ipp.
View newest version in sPHENIX GitHub at line 192 of file AdaptiveMultiVertexFinder.ipp
References Acts::ImpactParametersAndSigma::d0, m_cfg(), Acts::Vertex< input_track_t >::setFullCovariance(), Acts::ImpactParametersAndSigma::sigmaD0, Acts::ImpactParametersAndSigma::sigmaZ0, and Acts::ImpactParametersAndSigma::z0.
template<typename vfitter_t , typename sfinder_t > auto Acts::AdaptiveMultiVertexFinder< vfitter_t, sfinder_t >::getVertexOutputList (const std::vector< Vertex< InputTrack_t > * > & allVerticesPtr, FitterState_t & fitterState) const private
Prepares the output vector of vertices.
Parameters
allVerticesPtr Vector of pointers to vertices
fitterState The vertex fitter state
Returns
The output vertex collection
Definition at line 580 of file AdaptiveMultiVertexFinder.ipp.
View newest version in sPHENIX GitHub at line 580 of file AdaptiveMultiVertexFinder.ipp
template<typename vfitter_t , typename sfinder_t > auto Acts::AdaptiveMultiVertexFinder< vfitter_t, sfinder_t >::isMergedVertex (const Vertex< InputTrack_t > & vtx, const std::vector< Vertex< InputTrack_t > * > & allVertices) const private
Method that evaluates if the new vertex candidate is merged with one of the previously found vertices.
Parameters
vtx The vertex candidate
allVertices All so far found vertices
Returns
Vertex is merged
Definition at line 502 of file AdaptiveMultiVertexFinder.ipp.
View newest version in sPHENIX GitHub at line 502 of file AdaptiveMultiVertexFinder.ipp
References eZ, Acts::Vertex< input_track_t >::fullCovariance(), Acts::Vertex< input_track_t >::fullPosition(), m_cfg(), and Acts::safeInverse().
template<typename vfitter_t , typename sfinder_t > auto Acts::AdaptiveMultiVertexFinder< vfitter_t, sfinder_t >::keepNewVertex (Vertex< InputTrack_t > & vtx, const std::vector< Vertex< InputTrack_t > * > & allVertices, FitterState_t & fitterState) const private
Method that evaluates if the new vertex candidate should be kept, i.e. saved, or not.
Parameters
vtx The vertex candidate
allVertices All so far found vertices
fitterState The vertex fitter state
Returns
Keep new vertex
Definition at line 473 of file AdaptiveMultiVertexFinder.ipp.
View newest version in sPHENIX GitHub at line 473 of file AdaptiveMultiVertexFinder.ipp
References m_cfg().
template<typename vfitter_t , typename sfinder_t > const Logger& Acts::AdaptiveMultiVertexFinder< vfitter_t, sfinder_t >::logger () const inline private
Private access to logging instance.
Definition at line 223 of file AdaptiveMultiVertexFinder.hpp.
View newest version in sPHENIX GitHub at line 223 of file AdaptiveMultiVertexFinder.hpp
References Acts::AdaptiveMultiVertexFinder< vfitter_t, sfinder_t >::m_logger.
template<typename vfitter_t , typename sfinder_t > Acts::AdaptiveMultiVertexFinder< vfitter_t, sfinder_t >::m_logger (std:: movelogger) inline
Definition at line 178 of file AdaptiveMultiVertexFinder.hpp.
View newest version in sPHENIX GitHub at line 178 of file AdaptiveMultiVertexFinder.hpp
template<typename vfitter_t , typename sfinder_t > auto Acts::AdaptiveMultiVertexFinder< vfitter_t, sfinder_t >::removeCompatibleTracksFromSeedTracks (Vertex< InputTrack_t > & vtx, std::vector< const InputTrack_t * > & seedTracks, FitterState_t & fitterState, std::vector< const InputTrack_t * > & removedSeedTracks) const private
Method that removes all tracks that are compatible with current vertex from seedTracks.
Parameters
vtx The vertex candidate
[out] seedTracks The seed tracks
fitterState The vertex fitter state
[out] removedSeedTracks Collection of seed track that will be removed
Definition at line 390 of file AdaptiveMultiVertexFinder.ipp.
View newest version in sPHENIX GitHub at line 390 of file AdaptiveMultiVertexFinder.ipp
References m_cfg().
template<typename vfitter_t , typename sfinder_t > auto Acts::AdaptiveMultiVertexFinder< vfitter_t, sfinder_t >::removeTrackIfIncompatible (Vertex< InputTrack_t > & vtx, std::vector< const InputTrack_t * > & seedTracks, FitterState_t & fitterState, std::vector< const InputTrack_t * > & removedSeedTracks, const GeometryContext & geoCtx) const private
Method that tries to remove an incompatible track from seed tracks after removing a compatible track failed.
Parameters
vtx The vertex candidate
[out] seedTracks The seed tracks
fitterState The vertex fitter state
[out] removedSeedTracks Collection of seed track that will be removed
[in] geoCtx The geometry context to access global positions
Returns
Incompatible track was removed
Definition at line 416 of file AdaptiveMultiVertexFinder.ipp.
View newest version in sPHENIX GitHub at line 416 of file AdaptiveMultiVertexFinder.ipp
References ACTS_DEBUG, eZ, geoCtx, i, and Acts::Test::pos.
template<typename vfitter_t , typename sfinder_t > auto Acts::AdaptiveMultiVertexFinder< vfitter_t, sfinder_t >::setConstraintAfterSeeding (Vertex< InputTrack_t > & currentConstraint, bool useVertexConstraintInFit, Vertex< InputTrack_t > & seedVertex) const private
Sets constraint vertex after seeding.
Parameters
currentConstraint Vertex constraint
useVertexConstraintInFit Indicates whether constraint is used during vertex fit
seedVertex Seed vertex
Definition at line 171 of file AdaptiveMultiVertexFinder.ipp.
View newest version in sPHENIX GitHub at line 171 of file AdaptiveMultiVertexFinder.ipp
References m_cfg().
Member Data Documentation
template<typename vfitter_t , typename sfinder_t > Config Acts::AdaptiveMultiVertexFinder< vfitter_t, sfinder_t >::m_cfg private
Configuration object.
Definition at line 212 of file AdaptiveMultiVertexFinder.hpp.
View newest version in sPHENIX GitHub at line 212 of file AdaptiveMultiVertexFinder.hpp
template<typename vfitter_t , typename sfinder_t > std::function<BoundTrackParameters(InputTrack_t)> Acts::AdaptiveMultiVertexFinder< vfitter_t, sfinder_t >::m_extractParameters private
Function to extract track parameters, InputTrack_t objects are BoundTrackParameters by default, function to be overwritten to return BoundTrackParameters for other InputTrack_t objects.
Definition at line 217 of file AdaptiveMultiVertexFinder.hpp.
View newest version in sPHENIX GitHub at line 217 of file AdaptiveMultiVertexFinder.hpp
template<typename vfitter_t , typename sfinder_t > std::unique_ptr<const Logger> Acts::AdaptiveMultiVertexFinder< vfitter_t, sfinder_t >::m_logger private
Logging instance.
Definition at line 220 of file AdaptiveMultiVertexFinder.hpp.
View newest version in sPHENIX GitHub at line 220 of file AdaptiveMultiVertexFinder.hpp
Referenced by Acts::AdaptiveMultiVertexFinder< vfitter_t, sfinder_t >::logger().
The documentation for this class was generated from the following files:
acts/blob/sPHENIX/Core/include/Acts/Vertexing/AdaptiveMultiVertexFinder.hpp
acts/blob/sPHENIX/Core/include/Acts/Vertexing/AdaptiveMultiVertexFinder.ipp