Analysis Software: MvtxPrototype2Clusterizer Class Reference
MvtxPrototype2Clusterizer Class Reference
Clusterizer for the MVTX.
#include <prototype/blob/master/offline/packages/MvtxPrototype2/MvtxPrototype2Clusterizer.h>
Public Types
typedef std::pair< unsigned
int, unsigned int > pixel
Public Member Functions
MvtxPrototype2Clusterizer (const std::string &name="MvtxPrototype2Clusterizer")
virtual ~MvtxPrototype2Clusterizer ()
int Init (PHCompositeNode *topNode)
module initialization
int InitRun (PHCompositeNode *topNode)
run initialization
int process_event (PHCompositeNode *topNode)
event processing
int End (PHCompositeNode *topNode)
end of process
void SetZClustering (const bool make_z_clustering)
option to turn off z-dimension clustering
bool GetZClustering () const
Public Member Functions inherited from SubsysReco
~SubsysReco () override
virtual int EndRun (const int)
Called at the end of each run.
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
void Print (const std::string &="ALL") const override
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Private Member Functions
bool are_adjacent (const std::pair< TrkrDefs::hitkey, TrkrHit * > &lhs, const std::pair< TrkrDefs::hitkey, TrkrHit * > &rhs)
void ClusterMvtx (PHCompositeNode *topNode)
void PrintClusters (PHCompositeNode *topNode)
Private Attributes
TrkrHitSetContainer * m_hits
TrkrClusterContainer * m_clusterlist
TrkrClusterHitAssoc * m_clusterhitassoc
bool m_makeZClustering
Additional Inherited Members
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Detailed Description
Clusterizer for the MVTX.
Definition at line 18 of file MvtxPrototype2Clusterizer.h.
View newest version in sPHENIX GitHub at line 18 of file MvtxPrototype2Clusterizer.h
Member Typedef Documentation
typedef std::pair<unsigned int, unsigned int> MvtxPrototype2Clusterizer::pixel
Definition at line 21 of file MvtxPrototype2Clusterizer.h.
View newest version in sPHENIX GitHub at line 21 of file MvtxPrototype2Clusterizer.h
Constructor & Destructor Documentation
MvtxPrototype2Clusterizer::MvtxPrototype2Clusterizer (const std::string & name = "MvtxPrototype2Clusterizer")
Definition at line 71 of file MvtxPrototype2Clusterizer.cc.
View newest version in sPHENIX GitHub at line 71 of file MvtxPrototype2Clusterizer.cc
virtual MvtxPrototype2Clusterizer::~MvtxPrototype2Clusterizer () inline virtual
Definition at line 24 of file MvtxPrototype2Clusterizer.h.
View newest version in sPHENIX GitHub at line 24 of file MvtxPrototype2Clusterizer.h
Member Function Documentation
bool MvtxPrototype2Clusterizer::are_adjacent (const std::pair< TrkrDefs::hitkey, TrkrHit * > & lhs, const std::pair< TrkrDefs::hitkey, TrkrHit * > & rhs) private
Definition at line 44 of file MvtxPrototype2Clusterizer.cc.
View newest version in sPHENIX GitHub at line 44 of file MvtxPrototype2Clusterizer.cc
References MvtxDefs::getCol(), and MvtxDefs::getRow().
Referenced by ClusterMvtx().
void MvtxPrototype2Clusterizer::ClusterMvtx (PHCompositeNode * topNode) private
Definition at line 189 of file MvtxPrototype2Clusterizer.cc.
View newest version in sPHENIX GitHub at line 189 of file MvtxPrototype2Clusterizer.cc
References TrkrClusterHitAssoc::addAssoc(), are_adjacent(), clusters, col, Jetscape::ERR, G, MvtxDefs::genClusKey(), MvtxDefs::getCol(), TrkrHitSet::getHits(), TrkrHitSet::getHitSetKey(), TrkrHitSetContainer::getHitSets(), MvtxDefs::getRow(), i, PHObject::identify(), TrkrHitSet::identify(), MvtxPrototype2Geom::Instance(), j, m_clusterhitassoc, m_clusterlist, m_hits, TrkrDefs::mvtxId, MATSCAN::phibins, phisize, SegmentationAlpide::PitchCol, SegmentationAlpide::PitchRow, SegmentationAlpide::SensorLayerThicknessEff, thickness, Fun4AllBase::Verbosity(), and zsize.
Referenced by process_event().
int MvtxPrototype2Clusterizer::End (PHCompositeNode * topNode) inline virtual
end of process
Reimplemented from SubsysReco.
Definition at line 36 of file MvtxPrototype2Clusterizer.h.
View newest version in sPHENIX GitHub at line 36 of file MvtxPrototype2Clusterizer.h
bool MvtxPrototype2Clusterizer::GetZClustering () const inline
Definition at line 43 of file MvtxPrototype2Clusterizer.h.
View newest version in sPHENIX GitHub at line 43 of file MvtxPrototype2Clusterizer.h
References m_makeZClustering.
int MvtxPrototype2Clusterizer::Init (PHCompositeNode * topNode) inline virtual
module initialization
Reimplemented from SubsysReco.
Definition at line 27 of file MvtxPrototype2Clusterizer.h.
View newest version in sPHENIX GitHub at line 27 of file MvtxPrototype2Clusterizer.h
int MvtxPrototype2Clusterizer::InitRun (PHCompositeNode * topNode) virtual
run initialization
Reimplemented from SubsysReco.
Definition at line 80 of file MvtxPrototype2Clusterizer.cc.
View newest version in sPHENIX GitHub at line 80 of file MvtxPrototype2Clusterizer.cc
References Fun4AllReturnCodes::ABORTRUN, PHCompositeNode::addNode(), Fun4AllReturnCodes::EVENT_OK, PHNodeIterator::findFirst(), m_makeZClustering, PHWHERE, and Fun4AllBase::Verbosity().
void MvtxPrototype2Clusterizer::PrintClusters (PHCompositeNode * topNode) private
Definition at line 403 of file MvtxPrototype2Clusterizer.cc.
View newest version in sPHENIX GitHub at line 403 of file MvtxPrototype2Clusterizer.cc
References TrkrClusterContainer::identify(), TrkrClusterContainer::size(), and Fun4AllBase::Verbosity().
Referenced by process_event().
int MvtxPrototype2Clusterizer::process_event (PHCompositeNode * topNode) virtual
event processing
Reimplemented from SubsysReco.
Definition at line 155 of file MvtxPrototype2Clusterizer.cc.
View newest version in sPHENIX GitHub at line 155 of file MvtxPrototype2Clusterizer.cc
References Fun4AllReturnCodes::ABORTRUN, ClusterMvtx(), Fun4AllReturnCodes::EVENT_OK, m_clusterhitassoc, m_clusterlist, m_hits, PHWHERE, and PrintClusters().
void MvtxPrototype2Clusterizer::SetZClustering (const bool make_z_clustering) inline
option to turn off z-dimension clustering
Definition at line 39 of file MvtxPrototype2Clusterizer.h.
View newest version in sPHENIX GitHub at line 39 of file MvtxPrototype2Clusterizer.h
References m_makeZClustering.
Member Data Documentation
TrkrClusterHitAssoc* MvtxPrototype2Clusterizer::m_clusterhitassoc private
Definition at line 59 of file MvtxPrototype2Clusterizer.h.
View newest version in sPHENIX GitHub at line 59 of file MvtxPrototype2Clusterizer.h
Referenced by ClusterMvtx(), and process_event().
TrkrClusterContainer* MvtxPrototype2Clusterizer::m_clusterlist private
Definition at line 58 of file MvtxPrototype2Clusterizer.h.
View newest version in sPHENIX GitHub at line 58 of file MvtxPrototype2Clusterizer.h
Referenced by ClusterMvtx(), and process_event().
TrkrHitSetContainer* MvtxPrototype2Clusterizer::m_hits private
Definition at line 57 of file MvtxPrototype2Clusterizer.h.
View newest version in sPHENIX GitHub at line 57 of file MvtxPrototype2Clusterizer.h
Referenced by ClusterMvtx(), and process_event().
bool MvtxPrototype2Clusterizer::m_makeZClustering private
Definition at line 62 of file MvtxPrototype2Clusterizer.h.
View newest version in sPHENIX GitHub at line 62 of file MvtxPrototype2Clusterizer.h
Referenced by GetZClustering(), InitRun(), and SetZClustering().
The documentation for this class was generated from the following files:
prototype/blob/master/offline/packages/MvtxPrototype2/MvtxPrototype2Clusterizer.h
prototype/blob/master/offline/packages/MvtxPrototype2/MvtxPrototype2Clusterizer.cc