Analysis Software: PHG4OuterHcalDetector Class Reference
PHG4OuterHcalDetector Class Reference
#include <coresoftware/blob/master/simulation/g4simulation/g4detectors/PHG4OuterHcalDetector.h>
Public Types
typedef
CGAL::Exact_circular_kernel_2 Circular_k
typedef CGAL::Point_2< Circular_k > Point_2
Public Member Functions
PHG4OuterHcalDetector (PHG4Subsystem *subsys, PHCompositeNode *Node, PHParameters *params, const std::string &dnam)
constructor
~PHG4OuterHcalDetector () override
destructor
void ConstructMe (G4LogicalVolume *world) override
construct
void Print (const std::string &what="ALL") const override
void SuperDetector (const std::string &name)
const std::string SuperDetector () const
int get_Layer () const
void ShiftSecantToTangent (Point_2 &lowleft, Point_2 &upleft, Point_2 &upright, Point_2 &lowright)
int ConsistencyCheck () const
void SetTiltViaNcross ()
int CheckTiltAngle () const
void ConstructHcalSingleScintillators (G4LogicalVolume *hcalenvelope)
G4VSolid * ConstructScintillatorBox (G4LogicalVolume *hcalenvelope)
std::pair< int, int > GetLayerTowerId (G4VPhysicalVolume *volume) const
volume accessors
int IsInOuterHcal (G4VPhysicalVolume *) const
Public Member Functions inherited from PHG4Detector
PHG4Detector ()=delete
constructor
PHG4Detector (PHG4Subsystem *subsys, PHCompositeNode *Node, const std::string &nam)
virtual ~PHG4Detector (void)
destructor
virtual void Construct (G4LogicalVolume *world) final
construct method
virtual void PostConstruction ()
Optional PostConstruction call after all geometry is constructed.
virtual void Verbosity (const int v)
virtual int Verbosity () const
virtual G4UserSteppingAction * GetSteppingAction ()
virtual std::string GetName () const
virtual void OverlapCheck (const bool chk)
virtual bool OverlapCheck () const
virtual int DisplayVolume (G4VSolid *volume, G4LogicalVolume *logvol, G4RotationMatrix *rotm=nullptr)
virtual int DisplayVolume (G4LogicalVolume *checksolid, G4LogicalVolume *logvol, G4RotationMatrix *rotm=nullptr)
virtual PHCompositeNode * topNode ()
virtual PHG4Subsystem * GetMySubsystem ()
Protected Member Functions
void AddGeometryNode ()
int ConstructOuterHcal (G4LogicalVolume *hcalenvelope)
G4VSolid * ConstructSteelPlate (G4LogicalVolume *hcalenvelope)
G4AssemblyVolume * ConstructHcalScintillatorAssembly (G4LogicalVolume *hcalenvelope)
G4double x_at_y (Point_2 &p0, Point_2 &p1, G4double yin)
Protected Attributes
PHG4OuterHcalDisplayAction * m_DisplayAction = nullptr
PHG4OuterHcalFieldSetup * m_FieldSetup = nullptr
PHParameters * m_Params = nullptr
G4AssemblyVolume * m_ScintiMotherAssembly = nullptr
G4VSolid * m_SteelCutoutForMagnetG4Solid = nullptr
double m_InnerRadius = NAN
double m_OuterRadius = NAN
double m_SizeZ = NAN
double m_ScintiTileX = NAN
double m_ScintiTileXLower = NAN
double m_ScintiTileXUpper = NAN
double m_ScintiTileZ = NAN
double m_ScintiTileThickness = NAN
double m_ScintiGap = NAN
double m_ScintiInnerRadius = NAN
double m_ScintiOuterRadius = NAN
double m_TiltAngle = NAN
double m_EnvelopeInnerRadius = NAN
double m_EnvelopeOuterRadius = NAN
double m_EnvelopeZ = NAN
double m_VolumeEnvelope = NAN
double m_VolumeSteel = NAN
double m_VolumeScintillator = NAN
int m_NumScintiPlates = 0
int m_NumScintiTiles = 0
int m_ActiveFlag = 0
int m_AbsorberActiveFlag = 0
int m_Layer = 0
std::string m_SuperDetector
std::string m_ScintiLogicNamePrefix
std::vector< G4VSolid * > m_ScintiTilesVec
std::set< G4VPhysicalVolume * > m_SteelAbsorberVec
std::map< G4VPhysicalVolume
*, std::pair< int, int > > m_ScintiTilePhysVolMap
RawTowerGeomContainer * m_RawTowerGeom = nullptr
std::string m_TowerGeomNodeName
Additional Inherited Members
Static Public Member Functions inherited from PHG4Detector
static G4Material * GetDetectorMaterial (const std::string &name, const bool quit=true)
static G4Element * GetDetectorElement (const std::string &name, const bool quit=true)
Detailed Description
Definition at line 35 of file PHG4OuterHcalDetector.h.
View newest version in sPHENIX GitHub at line 35 of file PHG4OuterHcalDetector.h
Member Typedef Documentation
typedef CGAL::Exact_circular_kernel_2 PHG4OuterHcalDetector::Circular_k
Definition at line 38 of file PHG4OuterHcalDetector.h.
View newest version in sPHENIX GitHub at line 38 of file PHG4OuterHcalDetector.h
typedef CGAL::Point_2<Circular_k> PHG4OuterHcalDetector::Point_2
Definition at line 39 of file PHG4OuterHcalDetector.h.
View newest version in sPHENIX GitHub at line 39 of file PHG4OuterHcalDetector.h
Constructor & Destructor Documentation
PHG4OuterHcalDetector::PHG4OuterHcalDetector (PHG4Subsystem * subsys, PHCompositeNode * Node, PHParameters * params, const std::string & dnam)
constructor
Definition at line 84 of file PHG4OuterHcalDetector.cc.
View newest version in sPHENIX GitHub at line 84 of file PHG4OuterHcalDetector.cc
References m_NumScintiTiles, and m_ScintiTilesVec.
PHG4OuterHcalDetector::~PHG4OuterHcalDetector () override
destructor
Definition at line 109 of file PHG4OuterHcalDetector.cc.
View newest version in sPHENIX GitHub at line 109 of file PHG4OuterHcalDetector.cc
References m_FieldSetup, and m_ScintiMotherAssembly.
Member Function Documentation
void PHG4OuterHcalDetector::AddGeometryNode () protected
Definition at line 996 of file PHG4OuterHcalDetector.cc.
View newest version in sPHENIX GitHub at line 996 of file PHG4OuterHcalDetector.cc
References RawTowerGeomContainer::add_tower_geometry(), PHCompositeNode::addNode(), RawTowerDefs::convert_name_to_caloid(), Acts::UnitConstants::e, RawTowerDefs::encode_towerid(), PHNodeIterator::findFirst(), RawTowerGeom::get_center_x(), PHParameters::get_double_param(), RawTowerGeomContainer::get_etabins(), RawTowerGeomContainer::get_etacenter(), PHParameters::get_int_param(), RawTowerGeomContainer::get_phibins(), RawTowerGeomContainer::get_phicenter(), PHG4Utils::get_theta(), RawTowerGeomContainer::get_tower_geometry(), i, RawTowerGeomContainer::identify(), PHG4HcalDefs::innerrad, m_Params, m_RawTowerGeom, m_SuperDetector, m_TowerGeomNodeName, PHG4HcalDefs::n_towers, PHG4HcalDefs::outerrad, PHCompositeNode::PHCompositeNode(), G4HCALIN::phistart, PHWHERE, RawTowerGeomContainer::set_etabins(), RawTowerGeomContainer::set_etabounds(), RawTowerGeomContainer::set_phibins(), RawTowerGeomContainer::set_phibounds(), RawTowerGeomContainer::set_radius(), RawTowerGeomContainer::set_thickness(), tg, thickness, PHG4Detector::topNode(), PHG4Detector::Verbosity(), ambiguity_solver_full_chain::x, y, and physmon_track_finding_ttbar::z.
Referenced by ConstructMe().
int PHG4OuterHcalDetector::CheckTiltAngle () const
Definition at line 939 of file PHG4OuterHcalDetector.cc.
View newest version in sPHENIX GitHub at line 939 of file PHG4OuterHcalDetector.cc
References deg, m_InnerRadius, m_OuterRadius, m_TiltAngle, PHWHERE, and Acts::UnitConstants::rad.
Referenced by ConstructOuterHcal().
int PHG4OuterHcalDetector::ConsistencyCheck () const
Definition at line 802 of file PHG4OuterHcalDetector.cc.
View newest version in sPHENIX GitHub at line 802 of file PHG4OuterHcalDetector.cc
References Acts::UnitConstants::cm, PHParameters::get_double_param(), m_InnerRadius, m_OuterRadius, m_Params, m_ScintiGap, m_ScintiInnerRadius, m_ScintiOuterRadius, m_ScintiTileThickness, and PHWHERE.
Referenced by ConstructOuterHcal().
G4AssemblyVolume * PHG4OuterHcalDetector::ConstructHcalScintillatorAssembly (G4LogicalVolume * hcalenvelope) protected
Definition at line 772 of file PHG4OuterHcalDetector.cc.
View newest version in sPHENIX GitHub at line 772 of file PHG4OuterHcalDetector.cc
References PHG4OuterHcalDisplayAction::AddScintiVolume(), Acts::UnitConstants::cm, ConstructHcalSingleScintillators(), PHParameters::get_double_param(), PHG4OuterHcalFieldSetup::get_Field_Manager_Gap(), PHG4Detector::GetDetectorMaterial(), i, m_DisplayAction, m_FieldSetup, m_Params, m_ScintiLogicNamePrefix, m_ScintiTilesVec, and perf_headwind::name.
Referenced by ConstructOuterHcal().
void PHG4OuterHcalDetector::ConstructHcalSingleScintillators (G4LogicalVolume * hcalenvelope)
Definition at line 594 of file PHG4OuterHcalDetector.cc.
View newest version in sPHENIX GitHub at line 594 of file PHG4OuterHcalDetector.cc
References Acts::UnitConstants::cm, ConstructScintillatorBox(), deg, PHG4Detector::DisplayVolume(), eta, PHParameters::get_double_param(), PHParameters::get_int_param(), PHG4Utils::get_theta(), i, j, m_InnerRadius, m_NumScintiTiles, m_OuterRadius, m_Params, m_ScintiInnerRadius, m_ScintiOuterRadius, m_ScintiTilesVec, m_ScintiTileThickness, m_ScintiTileX, m_ScintiTileXLower, m_ScintiTileXUpper, m_SteelCutoutForMagnetG4Solid, m_TiltAngle, Acts::UnitConstants::mm, perf_headwind::name, offset, Acts::UnitConstants::rad, subtract_from_scinti_x, ActsTests::PropagationDatasets::theta, testSigmaEff::v, ambiguity_solver_full_chain::x, x0, x_at_y(), xpos, physmon_track_finding_ttbar::z, and KFPMath::zero().
Referenced by ConstructHcalScintillatorAssembly().
void PHG4OuterHcalDetector::ConstructMe (G4LogicalVolume * world) override virtual
construct
Implements PHG4Detector.
Definition at line 418 of file PHG4OuterHcalDetector.cc.
View newest version in sPHENIX GitHub at line 418 of file PHG4OuterHcalDetector.cc
References AddGeometryNode(), Acts::UnitConstants::cm, ConstructOuterHcal(), deg, PHParameters::get_double_param(), PHParameters::get_int_param(), PHFlag::get_StringFlag(), PHG4Detector::GetDetectorMaterial(), i, recoConsts::instance(), it, m_DisplayAction, m_EnvelopeInnerRadius, m_EnvelopeOuterRadius, m_EnvelopeZ, m_NumScintiPlates, m_Params, m_ScintiMotherAssembly, m_ScintiTilePhysVolMap, m_VolumeEnvelope, PHG4Detector::OverlapCheck(), PHWHERE, and PHG4OuterHcalDisplayAction::SetMyTopVolume().
int PHG4OuterHcalDetector::ConstructOuterHcal (G4LogicalVolume * hcalenvelope) protected
Definition at line 498 of file PHG4OuterHcalDetector.cc.
View newest version in sPHENIX GitHub at line 498 of file PHG4OuterHcalDetector.cc
References PHG4OuterHcalDisplayAction::AddSteelVolume(), CheckTiltAngle(), ConsistencyCheck(), ConstructHcalScintillatorAssembly(), ConstructSteelPlate(), PHG4OuterHcalFieldSetup::get_Field_Manager_Gap(), PHG4OuterHcalFieldSetup::get_Field_Manager_Iron(), PHParameters::get_string_param(), PHG4Detector::GetDetectorMaterial(), i, m_DisplayAction, m_FieldSetup, m_InnerRadius, m_NumScintiPlates, m_OuterRadius, m_Params, m_ScintiGap, m_ScintiInnerRadius, m_ScintiMotherAssembly, m_ScintiTileX, m_ScintiTileXLower, m_ScintiTileXUpper, m_SteelAbsorberVec, m_TiltAngle, perf_headwind::name, PHG4Detector::OverlapCheck(), ActsTests::PropagationDatasets::phi, Acts::UnitConstants::rad, SetTiltViaNcross(), subtract_from_scinti_x, and xpos.
Referenced by ConstructMe().
G4VSolid * PHG4OuterHcalDetector::ConstructScintillatorBox (G4LogicalVolume * hcalenvelope)
Definition at line 137 of file PHG4OuterHcalDetector.cc.
View newest version in sPHENIX GitHub at line 137 of file PHG4OuterHcalDetector.cc
References m_InnerRadius, m_NumScintiPlates, m_OuterRadius, m_ScintiInnerRadius, m_ScintiOuterRadius, m_ScintiTileThickness, m_ScintiTileX, m_ScintiTileXLower, m_ScintiTileXUpper, m_ScintiTileZ, m_TiltAngle, m_VolumeScintillator, Acts::VectorHelpers::perp(), Acts::UnitConstants::rad, and subtract_from_scinti_x.
Referenced by ConstructHcalSingleScintillators().
G4VSolid * PHG4OuterHcalDetector::ConstructSteelPlate (G4LogicalVolume * hcalenvelope) protected
Definition at line 214 of file PHG4OuterHcalDetector.cc.
View newest version in sPHENIX GitHub at line 214 of file PHG4OuterHcalDetector.cc
References deg, m_InnerRadius, m_NumScintiPlates, m_OuterRadius, m_ScintiGap, m_SizeZ, m_SteelCutoutForMagnetG4Solid, m_TiltAngle, m_VolumeSteel, Acts::VectorHelpers::perp(), Acts::UnitConstants::rad, ShiftSecantToTangent(), v1, v2, v3, v4, and KFPMath::zero().
Referenced by ConstructOuterHcal().
int PHG4OuterHcalDetector::get_Layer () const inline
Definition at line 58 of file PHG4OuterHcalDetector.h.
View newest version in sPHENIX GitHub at line 58 of file PHG4OuterHcalDetector.h
References m_Layer.
std::pair< int, int > PHG4OuterHcalDetector::GetLayerTowerId (G4VPhysicalVolume * volume) const
Definition at line 980 of file PHG4OuterHcalDetector.cc.
View newest version in sPHENIX GitHub at line 980 of file PHG4OuterHcalDetector.cc
References it, and m_ScintiTilePhysVolMap.
Referenced by PHG4OuterHcalSteppingAction::NoHitSteppingAction(), and PHG4OuterHcalSteppingAction::UserSteppingAction().
int PHG4OuterHcalDetector::IsInOuterHcal (G4VPhysicalVolume * volume) const
Definition at line 117 of file PHG4OuterHcalDetector.cc.
View newest version in sPHENIX GitHub at line 117 of file PHG4OuterHcalDetector.cc
References m_AbsorberActiveFlag, m_ActiveFlag, m_ScintiTilePhysVolMap, and m_SteelAbsorberVec.
Referenced by PHG4OuterHcalSteppingAction::NoHitSteppingAction(), and PHG4OuterHcalSteppingAction::UserSteppingAction().
void PHG4OuterHcalDetector::Print (const std::string & what = "ALL") const override virtual
Reimplemented from PHG4Detector.
Definition at line 967 of file PHG4OuterHcalDetector.cc.
View newest version in sPHENIX GitHub at line 967 of file PHG4OuterHcalDetector.cc
References Acts::UnitConstants::cm, m_VolumeEnvelope, m_VolumeScintillator, and m_VolumeSteel.
Referenced by PHG4OuterHcalSubsystem::Print().
void PHG4OuterHcalDetector::SetTiltViaNcross ()
Definition at line 858 of file PHG4OuterHcalDetector.cc.
View newest version in sPHENIX GitHub at line 858 of file PHG4OuterHcalDetector.cc
References autodiff::detail::copysign(), deg, PHParameters::get_int_param(), m_InnerRadius, m_NumScintiPlates, m_OuterRadius, m_Params, m_TiltAngle, Acts::UnitConstants::rad, PHParameters::set_double_param(), PHParameters::set_int_param(), and PHG4Detector::Verbosity().
Referenced by ConstructOuterHcal().
void PHG4OuterHcalDetector::ShiftSecantToTangent (PHG4OuterHcalDetector::Point_2 & lowleft, PHG4OuterHcalDetector::Point_2 & upleft, PHG4OuterHcalDetector::Point_2 & upright, PHG4OuterHcalDetector::Point_2 & lowright)
Definition at line 371 of file PHG4OuterHcalDetector.cc.
View newest version in sPHENIX GitHub at line 371 of file PHG4OuterHcalDetector.cc
References m_InnerRadius.
Referenced by ConstructSteelPlate().
void PHG4OuterHcalDetector::SuperDetector (const std::string & name) inline
Definition at line 56 of file PHG4OuterHcalDetector.h.
View newest version in sPHENIX GitHub at line 56 of file PHG4OuterHcalDetector.h
References m_SuperDetector, and perf_headwind::name.
Referenced by PHG4OuterHcalSteppingAction::CreateNodeTree(), PHG4OuterHcalSubsystem::InitRunSubsystem(), and PHG4OuterHcalSteppingAction::SetInterfacePointers().
const std::string PHG4OuterHcalDetector::SuperDetector () const inline
Definition at line 57 of file PHG4OuterHcalDetector.h.
View newest version in sPHENIX GitHub at line 57 of file PHG4OuterHcalDetector.h
References m_SuperDetector.
G4double PHG4OuterHcalDetector::x_at_y (PHG4OuterHcalDetector::Point_2 & p0, PHG4OuterHcalDetector::Point_2 & p1, G4double yin) protected
Definition at line 745 of file PHG4OuterHcalDetector.cc.
View newest version in sPHENIX GitHub at line 745 of file PHG4OuterHcalDetector.cc
References PHWHERE, and ambiguity_solver_full_chain::x.
Referenced by ConstructHcalSingleScintillators().
Member Data Documentation
int PHG4OuterHcalDetector::m_AbsorberActiveFlag = 0 protected
Definition at line 101 of file PHG4OuterHcalDetector.h.
View newest version in sPHENIX GitHub at line 101 of file PHG4OuterHcalDetector.h
Referenced by IsInOuterHcal().
int PHG4OuterHcalDetector::m_ActiveFlag = 0 protected
Definition at line 100 of file PHG4OuterHcalDetector.h.
View newest version in sPHENIX GitHub at line 100 of file PHG4OuterHcalDetector.h
Referenced by IsInOuterHcal().
PHG4OuterHcalDisplayAction* PHG4OuterHcalDetector::m_DisplayAction = nullptr protected
Definition at line 73 of file PHG4OuterHcalDetector.h.
View newest version in sPHENIX GitHub at line 73 of file PHG4OuterHcalDetector.h
Referenced by ConstructHcalScintillatorAssembly(), ConstructMe(), and ConstructOuterHcal().
double PHG4OuterHcalDetector::m_EnvelopeInnerRadius = NAN protected
Definition at line 90 of file PHG4OuterHcalDetector.h.
View newest version in sPHENIX GitHub at line 90 of file PHG4OuterHcalDetector.h
Referenced by ConstructMe().
double PHG4OuterHcalDetector::m_EnvelopeOuterRadius = NAN protected
Definition at line 91 of file PHG4OuterHcalDetector.h.
View newest version in sPHENIX GitHub at line 91 of file PHG4OuterHcalDetector.h
Referenced by ConstructMe().
double PHG4OuterHcalDetector::m_EnvelopeZ = NAN protected
Definition at line 92 of file PHG4OuterHcalDetector.h.
View newest version in sPHENIX GitHub at line 92 of file PHG4OuterHcalDetector.h
Referenced by ConstructMe().
PHG4OuterHcalFieldSetup* PHG4OuterHcalDetector::m_FieldSetup = nullptr protected
Definition at line 74 of file PHG4OuterHcalDetector.h.
View newest version in sPHENIX GitHub at line 74 of file PHG4OuterHcalDetector.h
Referenced by ConstructHcalScintillatorAssembly(), ConstructOuterHcal(), and ~PHG4OuterHcalDetector().
double PHG4OuterHcalDetector::m_InnerRadius = NAN protected
Definition at line 78 of file PHG4OuterHcalDetector.h.
View newest version in sPHENIX GitHub at line 78 of file PHG4OuterHcalDetector.h
Referenced by CheckTiltAngle(), ConsistencyCheck(), ConstructHcalSingleScintillators(), ConstructOuterHcal(), ConstructScintillatorBox(), ConstructSteelPlate(), SetTiltViaNcross(), and ShiftSecantToTangent().
int PHG4OuterHcalDetector::m_Layer = 0 protected
Definition at line 103 of file PHG4OuterHcalDetector.h.
View newest version in sPHENIX GitHub at line 103 of file PHG4OuterHcalDetector.h
Referenced by get_Layer().
int PHG4OuterHcalDetector::m_NumScintiPlates = 0 protected
Definition at line 97 of file PHG4OuterHcalDetector.h.
View newest version in sPHENIX GitHub at line 97 of file PHG4OuterHcalDetector.h
Referenced by ConstructMe(), ConstructOuterHcal(), ConstructScintillatorBox(), ConstructSteelPlate(), and SetTiltViaNcross().
int PHG4OuterHcalDetector::m_NumScintiTiles = 0 protected
Definition at line 98 of file PHG4OuterHcalDetector.h.
View newest version in sPHENIX GitHub at line 98 of file PHG4OuterHcalDetector.h
Referenced by ConstructHcalSingleScintillators(), and PHG4OuterHcalDetector().
double PHG4OuterHcalDetector::m_OuterRadius = NAN protected
Definition at line 79 of file PHG4OuterHcalDetector.h.
View newest version in sPHENIX GitHub at line 79 of file PHG4OuterHcalDetector.h
Referenced by CheckTiltAngle(), ConsistencyCheck(), ConstructHcalSingleScintillators(), ConstructOuterHcal(), ConstructScintillatorBox(), ConstructSteelPlate(), and SetTiltViaNcross().
PHParameters* PHG4OuterHcalDetector::m_Params = nullptr protected
Definition at line 75 of file PHG4OuterHcalDetector.h.
View newest version in sPHENIX GitHub at line 75 of file PHG4OuterHcalDetector.h
Referenced by AddGeometryNode(), ConsistencyCheck(), ConstructHcalScintillatorAssembly(), ConstructHcalSingleScintillators(), ConstructMe(), ConstructOuterHcal(), and SetTiltViaNcross().
RawTowerGeomContainer* PHG4OuterHcalDetector::m_RawTowerGeom = nullptr protected
Definition at line 109 of file PHG4OuterHcalDetector.h.
View newest version in sPHENIX GitHub at line 109 of file PHG4OuterHcalDetector.h
Referenced by AddGeometryNode().
double PHG4OuterHcalDetector::m_ScintiGap = NAN protected
Definition at line 86 of file PHG4OuterHcalDetector.h.
View newest version in sPHENIX GitHub at line 86 of file PHG4OuterHcalDetector.h
Referenced by ConsistencyCheck(), ConstructOuterHcal(), and ConstructSteelPlate().
double PHG4OuterHcalDetector::m_ScintiInnerRadius = NAN protected
Definition at line 87 of file PHG4OuterHcalDetector.h.
View newest version in sPHENIX GitHub at line 87 of file PHG4OuterHcalDetector.h
Referenced by ConsistencyCheck(), ConstructHcalSingleScintillators(), ConstructOuterHcal(), and ConstructScintillatorBox().
std::string PHG4OuterHcalDetector::m_ScintiLogicNamePrefix protected
Definition at line 105 of file PHG4OuterHcalDetector.h.
View newest version in sPHENIX GitHub at line 105 of file PHG4OuterHcalDetector.h
Referenced by ConstructHcalScintillatorAssembly().
G4AssemblyVolume* PHG4OuterHcalDetector::m_ScintiMotherAssembly = nullptr protected
Definition at line 76 of file PHG4OuterHcalDetector.h.
View newest version in sPHENIX GitHub at line 76 of file PHG4OuterHcalDetector.h
Referenced by ConstructMe(), ConstructOuterHcal(), and ~PHG4OuterHcalDetector().
double PHG4OuterHcalDetector::m_ScintiOuterRadius = NAN protected
Definition at line 88 of file PHG4OuterHcalDetector.h.
View newest version in sPHENIX GitHub at line 88 of file PHG4OuterHcalDetector.h
Referenced by ConsistencyCheck(), ConstructHcalSingleScintillators(), and ConstructScintillatorBox().
std::map<G4VPhysicalVolume *, std::pair<int, int> > PHG4OuterHcalDetector::m_ScintiTilePhysVolMap protected
Definition at line 108 of file PHG4OuterHcalDetector.h.
View newest version in sPHENIX GitHub at line 108 of file PHG4OuterHcalDetector.h
Referenced by ConstructMe(), GetLayerTowerId(), and IsInOuterHcal().
std::vector<G4VSolid *> PHG4OuterHcalDetector::m_ScintiTilesVec protected
Definition at line 106 of file PHG4OuterHcalDetector.h.
View newest version in sPHENIX GitHub at line 106 of file PHG4OuterHcalDetector.h
Referenced by ConstructHcalScintillatorAssembly(), ConstructHcalSingleScintillators(), and PHG4OuterHcalDetector().
double PHG4OuterHcalDetector::m_ScintiTileThickness = NAN protected
Definition at line 85 of file PHG4OuterHcalDetector.h.
View newest version in sPHENIX GitHub at line 85 of file PHG4OuterHcalDetector.h
Referenced by ConsistencyCheck(), ConstructHcalSingleScintillators(), and ConstructScintillatorBox().
double PHG4OuterHcalDetector::m_ScintiTileX = NAN protected
Definition at line 81 of file PHG4OuterHcalDetector.h.
View newest version in sPHENIX GitHub at line 81 of file PHG4OuterHcalDetector.h
Referenced by ConstructHcalSingleScintillators(), ConstructOuterHcal(), and ConstructScintillatorBox().
double PHG4OuterHcalDetector::m_ScintiTileXLower = NAN protected
Definition at line 82 of file PHG4OuterHcalDetector.h.
View newest version in sPHENIX GitHub at line 82 of file PHG4OuterHcalDetector.h
Referenced by ConstructHcalSingleScintillators(), ConstructOuterHcal(), and ConstructScintillatorBox().
double PHG4OuterHcalDetector::m_ScintiTileXUpper = NAN protected
Definition at line 83 of file PHG4OuterHcalDetector.h.
View newest version in sPHENIX GitHub at line 83 of file PHG4OuterHcalDetector.h
Referenced by ConstructHcalSingleScintillators(), ConstructOuterHcal(), and ConstructScintillatorBox().
double PHG4OuterHcalDetector::m_ScintiTileZ = NAN protected
Definition at line 84 of file PHG4OuterHcalDetector.h.
View newest version in sPHENIX GitHub at line 84 of file PHG4OuterHcalDetector.h
Referenced by ConstructScintillatorBox().
double PHG4OuterHcalDetector::m_SizeZ = NAN protected
Definition at line 80 of file PHG4OuterHcalDetector.h.
View newest version in sPHENIX GitHub at line 80 of file PHG4OuterHcalDetector.h
Referenced by ConstructSteelPlate().
std::set<G4VPhysicalVolume *> PHG4OuterHcalDetector::m_SteelAbsorberVec protected
Definition at line 107 of file PHG4OuterHcalDetector.h.
View newest version in sPHENIX GitHub at line 107 of file PHG4OuterHcalDetector.h
Referenced by ConstructOuterHcal(), and IsInOuterHcal().
G4VSolid* PHG4OuterHcalDetector::m_SteelCutoutForMagnetG4Solid = nullptr protected
Definition at line 77 of file PHG4OuterHcalDetector.h.
View newest version in sPHENIX GitHub at line 77 of file PHG4OuterHcalDetector.h
Referenced by ConstructHcalSingleScintillators(), and ConstructSteelPlate().
std::string PHG4OuterHcalDetector::m_SuperDetector protected
Definition at line 104 of file PHG4OuterHcalDetector.h.
View newest version in sPHENIX GitHub at line 104 of file PHG4OuterHcalDetector.h
Referenced by AddGeometryNode(), and SuperDetector().
double PHG4OuterHcalDetector::m_TiltAngle = NAN protected
Definition at line 89 of file PHG4OuterHcalDetector.h.
View newest version in sPHENIX GitHub at line 89 of file PHG4OuterHcalDetector.h
Referenced by CheckTiltAngle(), ConstructHcalSingleScintillators(), ConstructOuterHcal(), ConstructScintillatorBox(), ConstructSteelPlate(), and SetTiltViaNcross().
std::string PHG4OuterHcalDetector::m_TowerGeomNodeName protected
Definition at line 110 of file PHG4OuterHcalDetector.h.
View newest version in sPHENIX GitHub at line 110 of file PHG4OuterHcalDetector.h
Referenced by AddGeometryNode().
double PHG4OuterHcalDetector::m_VolumeEnvelope = NAN protected
Definition at line 93 of file PHG4OuterHcalDetector.h.
View newest version in sPHENIX GitHub at line 93 of file PHG4OuterHcalDetector.h
Referenced by ConstructMe(), and Print().
double PHG4OuterHcalDetector::m_VolumeScintillator = NAN protected
Definition at line 95 of file PHG4OuterHcalDetector.h.
View newest version in sPHENIX GitHub at line 95 of file PHG4OuterHcalDetector.h
Referenced by ConstructScintillatorBox(), and Print().
double PHG4OuterHcalDetector::m_VolumeSteel = NAN protected
Definition at line 94 of file PHG4OuterHcalDetector.h.
View newest version in sPHENIX GitHub at line 94 of file PHG4OuterHcalDetector.h
Referenced by ConstructSteelPlate(), and Print().
The documentation for this class was generated from the following files:
coresoftware/blob/master/simulation/g4simulation/g4detectors/PHG4OuterHcalDetector.h
coresoftware/blob/master/simulation/g4simulation/g4detectors/PHG4OuterHcalDetector.cc