Analysis Software: Acts::Test::TestSpacePoint Class Reference
Acts::Test::TestSpacePoint Class Reference
Space point representation of a measurement suitable for track seeding.
#include <acts/blob/sPHENIX/Tests/CommonHelpers/Acts/Tests/CommonHelpers/TestSpacePoint.hpp>
Public Member Functions
template<typename position_t >
TestSpacePoint (const Eigen::MatrixBase< position_t > &pos, float varRho, float varZ, boost::container::static_vector< Acts::SourceLink, 2 > sourceLinks)
TestSpacePoint ()=default
constexpr float x () const
constexpr float y () const
constexpr float z () const
constexpr float r () const
constexpr float varianceR () const
constexpr float varianceZ () const
const
boost::container::static_vector
< Acts::SourceLink, 2 > & sourceLinks () const
Private Attributes
float m_x = 0
float m_y = 0
float m_z = 0
float m_rho = 0
float m_varianceRho = 0
float m_varianceZ = 0
boost::container::static_vector
< Acts::SourceLink, 2 > m_sourceLinks
Detailed Description
Space point representation of a measurement suitable for track seeding.
Definition at line 23 of file TestSpacePoint.hpp.
View newest version in sPHENIX GitHub at line 23 of file TestSpacePoint.hpp
Constructor & Destructor Documentation
template<typename position_t > Acts::Test::TestSpacePoint::TestSpacePoint (const Eigen::MatrixBase< position_t > & pos, float varRho, float varZ, boost::container::static_vector< Acts::SourceLink, 2 > sourceLinks) inline
Construct the space point from global position and selected variances.
Template Parameters
position_t Input position type
Parameters
pos Global position
varRho Measurement variance of the global transverse distance
varZ Measurement variance of the global longitudinal position
measurementIndices Indices of the underlying measurement
Definition at line 33 of file TestSpacePoint.hpp.
View newest version in sPHENIX GitHub at line 33 of file TestSpacePoint.hpp
Acts::Test::TestSpacePoint::TestSpacePoint () default
Member Function Documentation
constexpr float Acts::Test::TestSpacePoint::r () const inline
Definition at line 49 of file TestSpacePoint.hpp.
View newest version in sPHENIX GitHub at line 49 of file TestSpacePoint.hpp
References m_rho.
const boost::container::static_vector<Acts::SourceLink, 2>& Acts::Test::TestSpacePoint::sourceLinks () const inline
Definition at line 53 of file TestSpacePoint.hpp.
View newest version in sPHENIX GitHub at line 53 of file TestSpacePoint.hpp
References m_sourceLinks.
Referenced by Acts::Test::operator==().
constexpr float Acts::Test::TestSpacePoint::varianceR () const inline
Definition at line 50 of file TestSpacePoint.hpp.
View newest version in sPHENIX GitHub at line 50 of file TestSpacePoint.hpp
References m_varianceRho.
Referenced by Acts::Test::operator==().
constexpr float Acts::Test::TestSpacePoint::varianceZ () const inline
Definition at line 51 of file TestSpacePoint.hpp.
View newest version in sPHENIX GitHub at line 51 of file TestSpacePoint.hpp
References m_varianceZ.
Referenced by Acts::Test::operator==().
constexpr float Acts::Test::TestSpacePoint::x () const inline
Definition at line 46 of file TestSpacePoint.hpp.
View newest version in sPHENIX GitHub at line 46 of file TestSpacePoint.hpp
References m_x.
Referenced by Acts::Test::operator==().
constexpr float Acts::Test::TestSpacePoint::y () const inline
Definition at line 47 of file TestSpacePoint.hpp.
View newest version in sPHENIX GitHub at line 47 of file TestSpacePoint.hpp
References m_y.
Referenced by Acts::Test::operator==().
constexpr float Acts::Test::TestSpacePoint::z () const inline
Definition at line 48 of file TestSpacePoint.hpp.
View newest version in sPHENIX GitHub at line 48 of file TestSpacePoint.hpp
References m_z.
Referenced by Acts::Test::operator==().
Member Data Documentation
float Acts::Test::TestSpacePoint::m_rho = 0 private
Definition at line 63 of file TestSpacePoint.hpp.
View newest version in sPHENIX GitHub at line 63 of file TestSpacePoint.hpp
Referenced by r().
boost::container::static_vector<Acts::SourceLink, 2> Acts::Test::TestSpacePoint::m_sourceLinks private
Definition at line 68 of file TestSpacePoint.hpp.
View newest version in sPHENIX GitHub at line 68 of file TestSpacePoint.hpp
Referenced by sourceLinks().
float Acts::Test::TestSpacePoint::m_varianceRho = 0 private
Definition at line 65 of file TestSpacePoint.hpp.
View newest version in sPHENIX GitHub at line 65 of file TestSpacePoint.hpp
Referenced by varianceR().
float Acts::Test::TestSpacePoint::m_varianceZ = 0 private
Definition at line 66 of file TestSpacePoint.hpp.
View newest version in sPHENIX GitHub at line 66 of file TestSpacePoint.hpp
Referenced by varianceZ().
float Acts::Test::TestSpacePoint::m_x = 0 private
Definition at line 60 of file TestSpacePoint.hpp.
View newest version in sPHENIX GitHub at line 60 of file TestSpacePoint.hpp
Referenced by x().
float Acts::Test::TestSpacePoint::m_y = 0 private
Definition at line 61 of file TestSpacePoint.hpp.
View newest version in sPHENIX GitHub at line 61 of file TestSpacePoint.hpp
Referenced by y().
float Acts::Test::TestSpacePoint::m_z = 0 private
Definition at line 62 of file TestSpacePoint.hpp.
View newest version in sPHENIX GitHub at line 62 of file TestSpacePoint.hpp
Referenced by z().
The documentation for this class was generated from the following file:
acts/blob/sPHENIX/Tests/CommonHelpers/Acts/Tests/CommonHelpers/TestSpacePoint.hpp