Analysis Software: analysis/blob/master/AndersonAnalysisModules/ColdQcdCorrelatorAnalysis/SCorrelatorQAMaker/Fun4All_RunCorrelatorQAModules.C File Reference
Fun4All_RunCorrelatorQAModules.C File Reference
#include <vector>
#include <string>
#include <cstdlib>
#include <utility>
#include <FROG.h>
#include <G4_Magnet.C>
#include <fun4all/Fun4AllDstInputManager.h>
#include <g4main/Fun4AllDstPileupInputManager.h>
#include <Trkr_QA.C>
#include <Trkr_Reco.C>
#include <Trkr_Eval.C>
#include <Trkr_RecoInit.C>
#include <Trkr_Clustering.C>
#include <Trkr_Diagnostics.C>
#include <G4_TrkrSimulation.C>
#include <g4eval/SvtxEvaluator.h>
#include <g4eval/SvtxTruthRecoTableEval.h>
#include <caloreco/RawClusterBuilderTopo.h>
#include <particleflowreco/ParticleFlowReco.h>
#include "/sphenix/user/danderson/eec/SCorrelatorQAMaker/src/SCorrelatorQAMaker.h"
#include "/sphenix/user/danderson/eec/SCorrelatorQAMaker/src/SCheckTrackPairs.h"
#include "/sphenix/user/danderson/eec/SCorrelatorQAMaker/src/SMakeTrkQATuples.h"
#include "/sphenix/user/danderson/eec/SCorrelatorUtilities/TrkTools.h"
Macros
#define FUN4ALL_RUNCORRELATORQAMODULES_C
Functions
void Fun4All_RunCorrelatorQAModules (const vector< string > &vecOutFiles=VecOutFilesDefault, const vector< string > &vecOutDir=VecOutDirDefault, const vector< string > &vecInFiles=VecInFilesDefault, const int nEvents=NEvtDefault, const int verbosity=VerbDefault, const bool debug=DebugDefault)
Variables
static const vector< string > VecInFilesDefault
static const vector< string > VecOutFilesDefault
static const vector< string > VecOutDirDefault
static const int NEvtDefault = 10
static const int VerbDefault = 0
static const bool DebugDefault = false
Macro Definition Documentation
#define FUN4ALL_RUNCORRELATORQAMODULES_C
Definition at line 10 of file Fun4All_RunCorrelatorQAModules.C.
View newest version in sPHENIX GitHub at line 10 of file Fun4All_RunCorrelatorQAModules.C
Function Documentation
void Fun4All_RunCorrelatorQAModules (const vector< string > & vecOutFiles = VecOutFilesDefault, const vector< string > & vecOutDir = VecOutDirDefault, const vector< string > & vecInFiles = VecInFilesDefault, const int nEvents = NEvtDefault, const int verbosity = VerbDefault, const bool debug = DebugDefault)
Definition at line 82 of file Fun4All_RunCorrelatorQAModules.C.
View newest version in sPHENIX GitHub at line 82 of file Fun4All_RunCorrelatorQAModules.C
References SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::TrkInfo::dcaXY, SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::TrkInfo::dcaZ, Acts::Test::debug, SColdQcdCorrelatorAnalysis::SCheckTrackPairsConfig::doDcaSigCut, SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::TrkInfo::eta, Fun4AllServer::instance(), Intt_Cells(), Intt_Clustering(), Load(), G4MAGNET::magfield_rescale, MagnetFieldInit(), MagnetInit(), Enable::MICROMEGAS, Micromegas_Cells(), Micromegas_Clustering(), Mvtx_Cells(), Mvtx_Clustering(), nEvents, SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::TrkInfo::nInttLayer, SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::TrkInfo::nMvtxLayer, SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::TrkInfo::nTpcLayer, SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::TrkInfo::pt, SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::TrkInfo::ptErr, SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::TrkInfo::quality, utils::run, HeavyFlavorReco::runTracking, to_string(), TPC_Cells(), TPC_Clustering(), Tracking_Reco(), TrackingInit(), verbosity, and Verbosity().
Variable Documentation
const bool DebugDefault = false static
Definition at line 76 of file Fun4All_RunCorrelatorQAModules.C.
View newest version in sPHENIX GitHub at line 76 of file Fun4All_RunCorrelatorQAModules.C
const int NEvtDefault = 10 static
Definition at line 74 of file Fun4All_RunCorrelatorQAModules.C.
View newest version in sPHENIX GitHub at line 74 of file Fun4All_RunCorrelatorQAModules.C
const vector<string> VecInFilesDefault static
Initial value:
= {
  "DST_GLOBAL_pythia8_Jet10_sHijing_pAu_0_10fm_500kHz_bkg_0_10fm-0000000009-00009.root",
  "DST_TRKR_G4HIT_pythia8_Jet10_sHijing_pAu_0_10fm_500kHz_bkg_0_10fm-0000000009-00009.root",
  "DST_TRACKSEEDS_pythia8_Jet10_sHijing_pAu_0_10fm_500kHz_bkg_0_10fm-0000000009-00009.root",
  "DST_TRKR_CLUSTER_pythia8_Jet10_sHijing_pAu_0_10fm_500kHz_bkg_0_10fm-0000000009-00009.root",
  "DST_TRACKS_pythia8_Jet10_sHijing_pAu_0_10fm_500kHz_bkg_0_10fm-0000000009-00009.root",
  "DST_CALO_G4HIT_pythia8_Jet10_sHijing_pAu_0_10fm_500kHz_bkg_0_10fm-0000000009-00009.root",
  "DST_CALO_CLUSTER_pythia8_Jet10_sHijing_pAu_0_10fm_500kHz_bkg_0_10fm-0000000009-00009.root",
  "DST_TRUTH_G4HIT_pythia8_Jet10_sHijing_pAu_0_10fm_500kHz_bkg_0_10fm-0000000009-00009.root",
  "DST_TRUTH_pythia8_Jet10_sHijing_pAu_0_10fm_500kHz_bkg_0_10fm-0000000009-00009.root"
}
Definition at line 53 of file Fun4All_RunCorrelatorQAModules.C.
View newest version in sPHENIX GitHub at line 53 of file Fun4All_RunCorrelatorQAModules.C
const vector<string> VecOutDirDefault static
Initial value:
= {
  "CheckTrackPairs",
  "TrackQATuples"
}
Definition at line 68 of file Fun4All_RunCorrelatorQAModules.C.
View newest version in sPHENIX GitHub at line 68 of file Fun4All_RunCorrelatorQAModules.C
const vector<string> VecOutFilesDefault static
Initial value:
= {
  "test.root",
  "test1.root"
}
Definition at line 64 of file Fun4All_RunCorrelatorQAModules.C.
View newest version in sPHENIX GitHub at line 64 of file Fun4All_RunCorrelatorQAModules.C
const int VerbDefault = 0 static
Definition at line 75 of file Fun4All_RunCorrelatorQAModules.C.
View newest version in sPHENIX GitHub at line 75 of file Fun4All_RunCorrelatorQAModules.C