Analysis Software: Setters
Setters
Modules
property map definitions
Functions
virtual void RawCluster::set_id (const RawClusterDefs::keytype)
cluster ID
virtual void RawCluster::addTower (const RawClusterDefs::keytype, const float)
Tower operations.
virtual void RawCluster::set_energy (const float)
total energy
virtual void RawCluster::set_phi (const float)
access to intrinsic cylindrical coordinate system
virtual void RawCluster::set_z (const float)
virtual void RawCluster::set_r (const float)
virtual void RawCluster::set_ecore (const float)
virtual void RawCluster::set_chi2 (const float)
reduced chi2 for EM shower
virtual void RawCluster::set_prob (const float)
cluster template probability for EM shower
virtual void RawCluster::set_et_iso (const float)
isolation ET
virtual void RawCluster::set_et_iso (const float, const int, bool, bool)
RawCluster::RawCluster ()
void RawClusterv1::set_id (const RawClusterDefs::keytype id) override
cluster ID
void RawClusterv1::addTower (const RawClusterDefs::keytype twrid, const float etower) override
Tower operations.
void RawClusterv1::set_energy (const float energy) override
total energy
void RawClusterv1::set_phi (const float phi) override
access to intrinsic cylindrical coordinate system
void RawClusterv1::set_z (const float z) override
void RawClusterv1::set_r (const float r) override
void RawClusterv1::set_ecore (const float ecore) override
void RawClusterv1::set_chi2 (const float chi2) override
reduced chi2 for EM shower
void RawClusterv1::set_prob (const float prob) override
cluster template probability for EM shower
void RawClusterv1::set_et_iso (const float e) override
isolation ET default
void RawClusterv1::set_et_iso (const float et_iso, const int radiusx10, bool subtracted, bool clusterTower) override
isolation ET the radius and hueristic can be specified
RawClusterv1::u_property::u_property (int32_t in)
RawClusterv1::u_property::u_property (uint32_t in)
RawClusterv1::u_property::u_property (float in)
RawClusterv1::u_property::u_property ()
prop_storage_t RawClusterv1::u_property::get_storage () const
Variables
float RawClusterv1::u_property::fdata
int32_t RawClusterv1::u_property::idata
uint32_t RawClusterv1::u_property::uidata
RawClusterDefs::keytype RawClusterv1::clusterid
cluster ID
float RawClusterv1::_energy
total energy
TowerMap RawClusterv1::towermap
Tower operations.
float RawClusterv1::_r
location of cluster in cylindrical coordinate
float RawClusterv1::_phi
float RawClusterv1::_z
Detailed Description
Function Documentation
void RawClusterv1::addTower (const RawClusterDefs::keytype twrid, const float etower) override virtual
Tower operations.
Reimplemented from RawCluster.
Definition at line 34 of file RawClusterv1.cc.
View newest version in sPHENIX GitHub at line 34 of file RawClusterv1.cc
References RawClusterv1::towermap.
virtual void RawCluster::addTower (const RawClusterDefs::keytype , const float) inline virtual
Tower operations.
Reimplemented in RawClusterv1.
Definition at line 193 of file RawCluster.h.
View newest version in sPHENIX GitHub at line 193 of file RawCluster.h
References PHOOL_VIRTUAL_WARNING.
Referenced by RawClusterBuilderGraph::process_event(), and RawClusterBuilderTemplate::process_event().
prop_storage_t RawClusterv1::u_property::get_storage () const inline
Definition at line 157 of file RawClusterv1.h.
View newest version in sPHENIX GitHub at line 157 of file RawClusterv1.h
References RawClusterv1::u_property::uidata.
RawCluster::RawCluster () inline protected
Definition at line 292 of file RawCluster.h.
View newest version in sPHENIX GitHub at line 292 of file RawCluster.h
void RawClusterv1::set_chi2 (const float chi2) inline override virtual
reduced chi2 for EM shower
Reimplemented from RawCluster.
Definition at line 96 of file RawClusterv1.h.
View newest version in sPHENIX GitHub at line 96 of file RawClusterv1.h
References RawCluster::prop_chi2, and RawClusterv1::set_property().
virtual void RawCluster::set_chi2 (const float) inline virtual
reduced chi2 for EM shower
Reimplemented in RawClusterv1.
Definition at line 206 of file RawCluster.h.
View newest version in sPHENIX GitHub at line 206 of file RawCluster.h
References PHOOL_VIRTUAL_WARNING.
Referenced by TreeMaker::CopyAndMakeClusters(), CaloRecoUtility::ProbCorrsZVertex(), and RawClusterBuilderTemplate::process_event().
void RawClusterv1::set_ecore (const float ecore) inline override virtual
access additional optional properties cluster core energy for EM shower
Reimplemented from RawCluster.
Definition at line 94 of file RawClusterv1.h.
View newest version in sPHENIX GitHub at line 94 of file RawClusterv1.h
References RawCluster::prop_ecore, and RawClusterv1::set_property().
virtual void RawCluster::set_ecore (const float) inline virtual
access additional optional properties cluster core energy for EM shower
Reimplemented in RawClusterv1.
Definition at line 204 of file RawCluster.h.
View newest version in sPHENIX GitHub at line 204 of file RawCluster.h
References PHOOL_VIRTUAL_WARNING.
Referenced by TreeMaker::CopyAndMakeClusters(), RawClusterBuilderTemplate::process_event(), and RawClusterPositionCorrection::process_event().
void RawClusterv1::set_energy (const float energy) inline override virtual
total energy
Reimplemented from RawCluster.
Definition at line 86 of file RawClusterv1.h.
View newest version in sPHENIX GitHub at line 86 of file RawClusterv1.h
References RawClusterv1::_energy, and energy.
virtual void RawCluster::set_energy (const float) inline virtual
total energy
Reimplemented in RawClusterv1.
Definition at line 195 of file RawCluster.h.
View newest version in sPHENIX GitHub at line 195 of file RawCluster.h
References PHOOL_VIRTUAL_WARNING.
Referenced by TreeMaker::CopyAndMakeClusters(), RawClusterBuilderGraph::process_event(), RawClusterBuilderTemplate::process_event(), and RawClusterPositionCorrection::process_event().
void RawClusterv1::set_et_iso (const float e) inline override virtual
isolation ET default
Reimplemented from RawCluster.
Definition at line 100 of file RawClusterv1.h.
View newest version in sPHENIX GitHub at line 100 of file RawClusterv1.h
References RawCluster::prop_et_iso_calotower_R03, and RawClusterv1::set_property().
void RawClusterv1::set_et_iso (const float et_iso, const int radiusx10, bool subtracted, bool clusterTower = true) override virtual
isolation ET the radius and hueristic can be specified
Reimplemented from RawCluster.
Definition at line 193 of file RawClusterv1.cc.
View newest version in sPHENIX GitHub at line 193 of file RawClusterv1.cc
References PHOOL_VIRTUAL_WARN, RawCluster::prop_et_iso_calotower_R01, RawCluster::prop_et_iso_calotower_R02, RawCluster::prop_et_iso_calotower_R03, RawCluster::prop_et_iso_calotower_R04, RawCluster::prop_et_iso_calotower_sub_R01, RawCluster::prop_et_iso_calotower_sub_R02, RawCluster::prop_et_iso_calotower_sub_R03, RawCluster::prop_et_iso_calotower_sub_R04, RawClusterv1::set_property(), and to_string().
virtual void RawCluster::set_et_iso (const float) inline virtual
isolation ET
Reimplemented in RawClusterv1.
Definition at line 210 of file RawCluster.h.
View newest version in sPHENIX GitHub at line 210 of file RawCluster.h
References PHOOL_VIRTUAL_WARNING.
Referenced by ClusterIso::process_event().
virtual void RawCluster::set_et_iso (const float , const int , bool , bool) inline virtual
Reimplemented in RawClusterv1.
Definition at line 211 of file RawCluster.h.
View newest version in sPHENIX GitHub at line 211 of file RawCluster.h
References PHOOL_VIRTUAL_WARNING.
void RawClusterv1::set_id (const RawClusterDefs::keytype id) inline override virtual
cluster ID
Reimplemented from RawCluster.
Definition at line 82 of file RawClusterv1.h.
View newest version in sPHENIX GitHub at line 82 of file RawClusterv1.h
References RawClusterv1::clusterid, and train_ambiguity_solver::id.
virtual void RawCluster::set_id (const RawClusterDefs::keytype) inline virtual
cluster ID
Reimplemented in RawClusterv1.
Definition at line 191 of file RawCluster.h.
View newest version in sPHENIX GitHub at line 191 of file RawCluster.h
References PHOOL_VIRTUAL_WARNING.
Referenced by RawClusterContainer::AddCluster(), and TreeMaker::CopyAndMakeClusters().
void RawClusterv1::set_phi (const float phi) inline override virtual
access to intrinsic cylindrical coordinate system
Reimplemented from RawCluster.
Definition at line 88 of file RawClusterv1.h.
View newest version in sPHENIX GitHub at line 88 of file RawClusterv1.h
References RawClusterv1::_phi, and ActsTests::PropagationDatasets::phi.
virtual void RawCluster::set_phi (const float) inline virtual
access to intrinsic cylindrical coordinate system
Reimplemented in RawClusterv1.
Definition at line 198 of file RawCluster.h.
View newest version in sPHENIX GitHub at line 198 of file RawCluster.h
References PHOOL_VIRTUAL_WARNING.
Referenced by TreeMaker::CopyAndMakeClusters(), RawClusterBuilderGraph::process_event(), and RawClusterBuilderTemplate::process_event().
void RawClusterv1::set_prob (const float prob) inline override virtual
cluster template probability for EM shower
Reimplemented from RawCluster.
Definition at line 98 of file RawClusterv1.h.
View newest version in sPHENIX GitHub at line 98 of file RawClusterv1.h
References RawCluster::prop_prob, and RawClusterv1::set_property().
virtual void RawCluster::set_prob (const float) inline virtual
cluster template probability for EM shower
Reimplemented in RawClusterv1.
Definition at line 208 of file RawCluster.h.
View newest version in sPHENIX GitHub at line 208 of file RawCluster.h
References PHOOL_VIRTUAL_WARNING.
Referenced by TreeMaker::CopyAndMakeClusters(), CaloRecoUtility::ProbCorrsZVertex(), and RawClusterBuilderTemplate::process_event().
void RawClusterv1::set_r (const float r) inline override virtual
Reimplemented from RawCluster.
Definition at line 90 of file RawClusterv1.h.
View newest version in sPHENIX GitHub at line 90 of file RawClusterv1.h
References RawClusterv1::_r, and physmon_track_finding_ttbar::r.
virtual void RawCluster::set_r (const float) inline virtual
Reimplemented in RawClusterv1.
Definition at line 200 of file RawCluster.h.
View newest version in sPHENIX GitHub at line 200 of file RawCluster.h
References PHOOL_VIRTUAL_WARNING.
Referenced by TreeMaker::CopyAndMakeClusters(), RawClusterBuilderGraph::process_event(), and RawClusterBuilderTemplate::process_event().
void RawClusterv1::set_z (const float z) inline override virtual
Reimplemented from RawCluster.
Definition at line 89 of file RawClusterv1.h.
View newest version in sPHENIX GitHub at line 89 of file RawClusterv1.h
References RawClusterv1::_z, and physmon_track_finding_ttbar::z.
virtual void RawCluster::set_z (const float) inline virtual
Reimplemented in RawClusterv1.
Definition at line 199 of file RawCluster.h.
View newest version in sPHENIX GitHub at line 199 of file RawCluster.h
References PHOOL_VIRTUAL_WARNING.
Referenced by TreeMaker::CopyAndMakeClusters(), RawClusterBuilderGraph::process_event(), RawClusterBuilderTemplate::process_event(), and CaloRecoUtility::ShowerDepthCorrZVertex().
RawClusterv1::u_property::u_property (int32_t in) inline
Definition at line 140 of file RawClusterv1.h.
View newest version in sPHENIX GitHub at line 140 of file RawClusterv1.h
RawClusterv1::u_property::u_property (uint32_t in) inline
Definition at line 144 of file RawClusterv1.h.
View newest version in sPHENIX GitHub at line 144 of file RawClusterv1.h
RawClusterv1::u_property::u_property (float in) inline
Definition at line 148 of file RawClusterv1.h.
View newest version in sPHENIX GitHub at line 148 of file RawClusterv1.h
RawClusterv1::u_property::u_property () inline
Definition at line 152 of file RawClusterv1.h.
View newest version in sPHENIX GitHub at line 152 of file RawClusterv1.h
Variable Documentation
float RawClusterv1::_energy protected
total energy
Definition at line 170 of file RawClusterv1.h.
View newest version in sPHENIX GitHub at line 170 of file RawClusterv1.h
Referenced by RawClusterv1::get_energy(), RawClusterv1::Reset(), and RawClusterv1::set_energy().
float RawClusterv1::_phi protected
Definition at line 176 of file RawClusterv1.h.
View newest version in sPHENIX GitHub at line 176 of file RawClusterv1.h
Referenced by RawClusterv1::get_phi(), RawClusterv1::Reset(), and RawClusterv1::set_phi().
float RawClusterv1::_r protected
location of cluster in cylindrical coordinate
Definition at line 175 of file RawClusterv1.h.
View newest version in sPHENIX GitHub at line 175 of file RawClusterv1.h
Referenced by RawClusterv1::get_r(), RawClusterv1::Reset(), and RawClusterv1::set_r().
float RawClusterv1::_z protected
Definition at line 177 of file RawClusterv1.h.
View newest version in sPHENIX GitHub at line 177 of file RawClusterv1.h
Referenced by RawClusterv1::get_z(), RawClusterv1::Reset(), and RawClusterv1::set_z().
RawClusterDefs::keytype RawClusterv1::clusterid protected
cluster ID
Definition at line 168 of file RawClusterv1.h.
View newest version in sPHENIX GitHub at line 168 of file RawClusterv1.h
Referenced by RawClusterv1::get_id(), RawClusterv1::Reset(), and RawClusterv1::set_id().
float RawClusterv1::u_property::fdata
Definition at line 136 of file RawClusterv1.h.
View newest version in sPHENIX GitHub at line 136 of file RawClusterv1.h
Referenced by RawClusterv1::get_property_float().
int32_t RawClusterv1::u_property::idata
Definition at line 137 of file RawClusterv1.h.
View newest version in sPHENIX GitHub at line 137 of file RawClusterv1.h
Referenced by RawClusterv1::get_property_int().
TowerMap RawClusterv1::towermap protected
Tower operations.
Definition at line 172 of file RawClusterv1.h.
View newest version in sPHENIX GitHub at line 172 of file RawClusterv1.h
Referenced by RawClusterv1::addTower(), RawClusterv1::get_towermap(), RawClusterv1::get_towers(), RawClusterv1::getNTowers(), RawClusterv1::isValid(), and RawClusterv1::Reset().
uint32_t RawClusterv1::u_property::uidata
Definition at line 138 of file RawClusterv1.h.
View newest version in sPHENIX GitHub at line 138 of file RawClusterv1.h
Referenced by RawClusterv1::get_property_uint(), and RawClusterv1::u_property::get_storage().