Analysis Software: HFTriggerMVA Class Reference
HFTriggerMVA Class Reference
#include <analysis/blob/master/HF-Particle/HFTrigger/HFTriggerMVA.h>
Public Member Functions
HFTriggerMVA ()
HFTriggerMVA (const std::string &name)
virtual ~HFTriggerMVA ()
int Init (PHCompositeNode *topNode)
int process_event (PHCompositeNode *topNode)
int End (PHCompositeNode *topNode)
Called at the end of all processing.
bool runTrigger (PHCompositeNode *topNode)
bool runCutsTrigger (float mean_hits, float emcal_energy, float IP, float IP_xy, float DCA)
bool runMVATrigger (TMVA::Reader *reader, std::string method, std::vector< float > inputValues, float cut)
void calculateMultiplicity (PHCompositeNode *topNode, float &meanMultiplicity, float &asymmetryMultiplicity)
float getMaxEMCalEnergy (PHCompositeNode *topNode)
void getIPVariables (Track track1, Track track2, Vertex vertex, float &minIP, float &minIP_xy, float &maxIP, float &maxIP_xy, float &DCA)
Vertex makeVertex (PHCompositeNode *topNode)
std::vector< Vertex > makeAllPrimaryVertices (PHCompositeNode *topNode)
Track makeTrack (PHCompositeNode *topNode)
std::vector< Track > makeAllTracks (PHCompositeNode *topNode)
int decomposeTrack (Track track, TrackX &trackPosition, TrackP &trackMomentum)
float calcualteTrackVertex2DDCA (Track track, Vertex vertex)
float calcualteTrackVertexDCA (Track track, Vertex vertex)
float calcualteTrackTrackDCA (Track trackOne, Track trackTwo)
std::tuple< TMVA::Reader
*, std::vector< Float_t > > initMVA (std::vector< std::string > variableList, std::string method, std::string mvaFile)
void printRunRecord ()
void printTrigger ()
void requireCutsTrigger (bool useTrigger)
void requireMVAwCaloTrigger (bool useTrigger)
void setMeanMult (float value)
void setAsymmMult (float value)
void setTrackVertex3DDCA (float value)
void setTrackVertex2DDCA (float value)
void setTrackTrackDCA (float value)
void setminEMCalEnergy (float value)
void setMVA_wCaloResponse (float value)
void setMVA_woutCaloResponse (float value)
void setMVA_woutCaloOrMinTrackResponse (float value)
Public Member Functions inherited from SubsysReco
~SubsysReco () override
virtual int EndRun (const int)
Called at the end of each run.
virtual int InitRun (PHCompositeNode *)
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
void Print (const std::string &="ALL") const override
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Protected Attributes
SvtxEvalStack * m_svtx_evalstack = nullptr
SvtxTrackEval * trackeval = nullptr
Private Attributes
float meanMult = 12
float asymmMult = 0.1
float trackVertex3DDCA = 0.05
float trackVertex2DDCA = 0.05
float trackTrackDCA = 0.05
float minEMCalEnergy = 0.5
float MVA_wCaloResponse = -0.05
float MVA_woutCaloResponse = -0.05
float MVA_woutCaloOrMinTrackResponse = -0.05
bool m_useCutsTrigger = false
bool m_useCutswoutTrigger = false
bool m_useMVAwCaloTrigger = false
bool m_useMVAwoutCaloTrigger = false
bool m_useMVAwoutCaloAndMinTrackTrigger = false
SvtxVertexMap * m_dst_vertexmap = nullptr
SvtxTrackMap * m_dst_trackmap = nullptr
SvtxVertex * m_dst_vertex = nullptr
SvtxTrack * m_dst_track = nullptr
int m_events = 0
int m_no_trigger = 0
int m_counter = 0
int m_cuts_and_mva_wcalo_counter = 0
int m_no_cuts_and_mva_wcalo_counter = 0
int m_cuts_and_no_mva_wcalo_counter = 0
int m_no_cuts_and_no_mva_wcalo_counter = 0
int m_cuts_and_mva_woutcalo_counter = 0
int m_no_cuts_and_mva_woutcalo_counter = 0
int m_cuts_and_no_mva_woutcalo_counter = 0
int m_no_cuts_and_no_mva_woutcalo_counter = 0
int m_cuts_and_mva_woutcalo_and_mintracks_counter = 0
int m_no_cuts_and_mva_woutcalo_and_mintracks_counter = 0
int m_cuts_and_no_mva_woutcalo_and_mintracks_counter = 0
int m_no_cuts_and_no_mva_woutcalo_and_mintracks_counter = 0
std::string path = "/sphenix/u/cdean/software/analysis/HF-Particle/HFTrigger/weights/"
std::string mvaType = "BDTG"
std::vector< std::string > varListwCalo
std::vector< std::string > varListwoutCalo
std::vector< std::string > varListwoutCaloAndMinTrack
TMVA::Reader * wCaloReader
TMVA::Reader * woutCaloReader
TMVA::Reader * woutCaloAndMinTrackReader
std::vector< float > wCaloFloats
std::vector< float > woutCaloFloats
std::vector< float > woutCaloAndMinTrackFloats
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = std::numeric_limits<int>::max() - 10
}
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Detailed Description
Definition at line 45 of file HFTriggerMVA.h.
View newest version in sPHENIX GitHub at line 45 of file HFTriggerMVA.h
Constructor & Destructor Documentation
HFTriggerMVA::HFTriggerMVA ()
Definition at line 31 of file HFTriggerMVA.cc.
View newest version in sPHENIX GitHub at line 31 of file HFTriggerMVA.cc
HFTriggerMVA::HFTriggerMVA (const std::string & name) explicit
Definition at line 41 of file HFTriggerMVA.cc.
View newest version in sPHENIX GitHub at line 41 of file HFTriggerMVA.cc
virtual HFTriggerMVA::~HFTriggerMVA () inline virtual
Definition at line 52 of file HFTriggerMVA.h.
View newest version in sPHENIX GitHub at line 52 of file HFTriggerMVA.h
Member Function Documentation
float HFTriggerMVA::calcualteTrackTrackDCA (Track trackOne, Track trackTwo)
Definition at line 389 of file HFTriggerMVA.cc.
View newest version in sPHENIX GitHub at line 389 of file HFTriggerMVA.cc
References decomposeTrack().
Referenced by getIPVariables().
float HFTriggerMVA::calcualteTrackVertex2DDCA (Track track, Vertex vertex)
Definition at line 361 of file HFTriggerMVA.cc.
View newest version in sPHENIX GitHub at line 361 of file HFTriggerMVA.cc
References decomposeTrack(), and Acts::Test::pos.
Referenced by getIPVariables().
float HFTriggerMVA::calcualteTrackVertexDCA (Track track, Vertex vertex)
Definition at line 376 of file HFTriggerMVA.cc.
View newest version in sPHENIX GitHub at line 376 of file HFTriggerMVA.cc
References decomposeTrack(), and Acts::Test::pos.
Referenced by getIPVariables().
void HFTriggerMVA::calculateMultiplicity (PHCompositeNode * topNode, float & meanMultiplicity, float & asymmetryMultiplicity)
Definition at line 239 of file HFTriggerMVA.cc.
View newest version in sPHENIX GitHub at line 239 of file HFTriggerMVA.cc
References TrkrHitSetContainer::getHitSets(), i, TrkrDefs::inttId, and TrkrHitSet::size().
Referenced by runTrigger().
int HFTriggerMVA::decomposeTrack (Track track, TrackX & trackPosition, TrackP & trackMomentum)
Definition at line 349 of file HFTriggerMVA.cc.
View newest version in sPHENIX GitHub at line 349 of file HFTriggerMVA.cc
References i.
Referenced by calcualteTrackTrackDCA(), calcualteTrackVertex2DDCA(), and calcualteTrackVertexDCA().
int HFTriggerMVA::End (PHCompositeNode *) virtual
Called at the end of all processing.
Reimplemented from SubsysReco.
Definition at line 121 of file HFTriggerMVA.cc.
View newest version in sPHENIX GitHub at line 121 of file HFTriggerMVA.cc
References printRunRecord(), Fun4AllBase::Verbosity(), and Fun4AllBase::VERBOSITY_SOME.
void HFTriggerMVA::getIPVariables (Track track1, Track track2, Vertex vertex, float & minIP, float & minIP_xy, float & maxIP, float & maxIP_xy, float & DCA)
Definition at line 280 of file HFTriggerMVA.cc.
View newest version in sPHENIX GitHub at line 280 of file HFTriggerMVA.cc
References calcualteTrackTrackDCA(), calcualteTrackVertex2DDCA(), calcualteTrackVertexDCA(), and Acts::UnitConstants::min.
Referenced by runTrigger().
float HFTriggerMVA::getMaxEMCalEnergy (PHCompositeNode * topNode)
Definition at line 263 of file HFTriggerMVA.cc.
View newest version in sPHENIX GitHub at line 263 of file HFTriggerMVA.cc
References SvtxTrackMap::begin(), SvtxTrackMap::end(), SvtxTrack::get_cal_cluster_e(), m_dst_track, and m_dst_trackmap.
Referenced by runTrigger().
int HFTriggerMVA::Init (PHCompositeNode *) virtual
Called during initialization. Typically this is where you can book histograms, and e.g. register them to Fun4AllServer (so they can be output to file using Fun4AllServer::dumpHistos() method).
Reimplemented from SubsysReco.
Definition at line 51 of file HFTriggerMVA.cc.
View newest version in sPHENIX GitHub at line 51 of file HFTriggerMVA.cc
References initMVA(), m_useMVAwCaloTrigger, m_useMVAwoutCaloAndMinTrackTrigger, m_useMVAwoutCaloTrigger, meanMult, minEMCalEnergy, MVA_wCaloResponse, MVA_woutCaloOrMinTrackResponse, MVA_woutCaloResponse, mvaType, path, trackTrackDCA, trackVertex2DDCA, trackVertex3DDCA, varListwCalo, varListwoutCalo, varListwoutCaloAndMinTrack, wCaloFloats, wCaloReader, woutCaloAndMinTrackFloats, woutCaloAndMinTrackReader, woutCaloFloats, and woutCaloReader.
std::tuple< TMVA::Reader *, std::vector< Float_t > > HFTriggerMVA::initMVA (std::vector< std::string > variableList, std::string method, std::string mvaFile)
Definition at line 407 of file HFTriggerMVA.cc.
View newest version in sPHENIX GitHub at line 407 of file HFTriggerMVA.cc
References i, std::tr1::make_tuple(), and summary::reader.
Referenced by Init().
std::vector< Vertex > HFTriggerMVA::makeAllPrimaryVertices (PHCompositeNode * topNode)
Definition at line 307 of file HFTriggerMVA.cc.
View newest version in sPHENIX GitHub at line 307 of file HFTriggerMVA.cc
References SvtxVertexMap::begin(), SvtxVertexMap::end(), m_dst_vertex, m_dst_vertexmap, and makeVertex().
Referenced by runTrigger().
std::vector< Track > HFTriggerMVA::makeAllTracks (PHCompositeNode * topNode)
Definition at line 335 of file HFTriggerMVA.cc.
View newest version in sPHENIX GitHub at line 335 of file HFTriggerMVA.cc
References SvtxTrackMap::begin(), SvtxTrackMap::end(), m_dst_track, m_dst_trackmap, makeTrack(), and tracks().
Referenced by runTrigger().
Track HFTriggerMVA::makeTrack (PHCompositeNode * topNode)
Definition at line 321 of file HFTriggerMVA.cc.
View newest version in sPHENIX GitHub at line 321 of file HFTriggerMVA.cc
References SvtxTrack::get_px(), SvtxTrack::get_py(), SvtxTrack::get_pz(), SvtxTrack::get_x(), SvtxTrack::get_y(), SvtxTrack::get_z(), and m_dst_track.
Referenced by makeAllTracks().
Vertex HFTriggerMVA::makeVertex (PHCompositeNode * topNode)
Definition at line 296 of file HFTriggerMVA.cc.
View newest version in sPHENIX GitHub at line 296 of file HFTriggerMVA.cc
References SvtxVertex::get_x(), SvtxVertex::get_y(), SvtxVertex::get_z(), and m_dst_vertex.
Referenced by makeAllPrimaryVertices().
void HFTriggerMVA::printRunRecord ()
Definition at line 424 of file HFTriggerMVA.cc.
View newest version in sPHENIX GitHub at line 424 of file HFTriggerMVA.cc
References m_counter, m_cuts_and_mva_wcalo_counter, m_cuts_and_mva_woutcalo_and_mintracks_counter, m_cuts_and_mva_woutcalo_counter, m_cuts_and_no_mva_wcalo_counter, m_cuts_and_no_mva_woutcalo_and_mintracks_counter, m_cuts_and_no_mva_woutcalo_counter, m_events, m_no_cuts_and_mva_wcalo_counter, m_no_cuts_and_mva_woutcalo_and_mintracks_counter, m_no_cuts_and_mva_woutcalo_counter, m_no_cuts_and_no_mva_wcalo_counter, m_no_cuts_and_no_mva_woutcalo_and_mintracks_counter, m_no_cuts_and_no_mva_woutcalo_counter, and m_no_trigger.
Referenced by End().
void HFTriggerMVA::printTrigger ()
Definition at line 453 of file HFTriggerMVA.cc.
View newest version in sPHENIX GitHub at line 453 of file HFTriggerMVA.cc
References m_useCutsTrigger, and m_useMVAwCaloTrigger.
Referenced by runTrigger().
int HFTriggerMVA::process_event (PHCompositeNode *) virtual
Called for each event. This is where you do the real work.
Reimplemented from SubsysReco.
Definition at line 83 of file HFTriggerMVA.cc.
View newest version in sPHENIX GitHub at line 83 of file HFTriggerMVA.cc
References Fun4AllReturnCodes::EVENT_OK, m_counter, m_cuts_and_mva_wcalo_counter, m_cuts_and_mva_woutcalo_and_mintracks_counter, m_cuts_and_mva_woutcalo_counter, m_cuts_and_no_mva_wcalo_counter, m_cuts_and_no_mva_woutcalo_and_mintracks_counter, m_cuts_and_no_mva_woutcalo_counter, m_events, m_no_cuts_and_mva_wcalo_counter, m_no_cuts_and_mva_woutcalo_and_mintracks_counter, m_no_cuts_and_mva_woutcalo_counter, m_no_cuts_and_no_mva_wcalo_counter, m_no_cuts_and_no_mva_woutcalo_and_mintracks_counter, m_no_cuts_and_no_mva_woutcalo_counter, m_no_trigger, runTrigger(), Fun4AllBase::Verbosity(), and Fun4AllBase::VERBOSITY_MORE.
void HFTriggerMVA::requireCutsTrigger (bool useTrigger) inline
Definition at line 95 of file HFTriggerMVA.h.
View newest version in sPHENIX GitHub at line 95 of file HFTriggerMVA.h
References m_useCutsTrigger.
void HFTriggerMVA::requireMVAwCaloTrigger (bool useTrigger) inline
Definition at line 96 of file HFTriggerMVA.h.
View newest version in sPHENIX GitHub at line 96 of file HFTriggerMVA.h
References m_useMVAwCaloTrigger.
bool HFTriggerMVA::runCutsTrigger (float mean_hits, float emcal_energy, float IP, float IP_xy, float DCA)
Definition at line 219 of file HFTriggerMVA.cc.
View newest version in sPHENIX GitHub at line 219 of file HFTriggerMVA.cc
References meanMult, minEMCalEnergy, trackTrackDCA, trackVertex2DDCA, and trackVertex3DDCA.
Referenced by runTrigger().
bool HFTriggerMVA::runMVATrigger (TMVA::Reader * reader, std::string method, std::vector< float > inputValues, float cut)
Definition at line 233 of file HFTriggerMVA.cc.
View newest version in sPHENIX GitHub at line 233 of file HFTriggerMVA.cc
Referenced by runTrigger().
bool HFTriggerMVA::runTrigger (PHCompositeNode * topNode)
Definition at line 127 of file HFTriggerMVA.cc.
View newest version in sPHENIX GitHub at line 127 of file HFTriggerMVA.cc
References asymmMult, parse_cmake_options::begin, calculateMultiplicity(), fixGDML::element, end, getIPVariables(), getMaxEMCalEnergy(), i, j, k, m_useCutsTrigger, m_useCutswoutTrigger, m_useMVAwCaloTrigger, m_useMVAwoutCaloAndMinTrackTrigger, m_useMVAwoutCaloTrigger, makeAllPrimaryVertices(), makeAllTracks(), meanMult, MVA_wCaloResponse, MVA_woutCaloOrMinTrackResponse, MVA_woutCaloResponse, mvaType, printTrigger(), runCutsTrigger(), runMVATrigger(), Fun4AllBase::Verbosity(), Fun4AllBase::VERBOSITY_MORE, wCaloFloats, wCaloReader, woutCaloAndMinTrackFloats, woutCaloAndMinTrackReader, woutCaloFloats, and woutCaloReader.
Referenced by process_event().
void HFTriggerMVA::setAsymmMult (float value) inline
Definition at line 99 of file HFTriggerMVA.h.
View newest version in sPHENIX GitHub at line 99 of file HFTriggerMVA.h
References asymmMult, and value.
void HFTriggerMVA::setMeanMult (float value) inline
Definition at line 98 of file HFTriggerMVA.h.
View newest version in sPHENIX GitHub at line 98 of file HFTriggerMVA.h
References meanMult, and value.
void HFTriggerMVA::setminEMCalEnergy (float value) inline
Definition at line 103 of file HFTriggerMVA.h.
View newest version in sPHENIX GitHub at line 103 of file HFTriggerMVA.h
References minEMCalEnergy, and value.
void HFTriggerMVA::setMVA_wCaloResponse (float value) inline
Definition at line 104 of file HFTriggerMVA.h.
View newest version in sPHENIX GitHub at line 104 of file HFTriggerMVA.h
References MVA_wCaloResponse, and value.
void HFTriggerMVA::setMVA_woutCaloOrMinTrackResponse (float value) inline
Definition at line 106 of file HFTriggerMVA.h.
View newest version in sPHENIX GitHub at line 106 of file HFTriggerMVA.h
References MVA_woutCaloOrMinTrackResponse, and value.
void HFTriggerMVA::setMVA_woutCaloResponse (float value) inline
Definition at line 105 of file HFTriggerMVA.h.
View newest version in sPHENIX GitHub at line 105 of file HFTriggerMVA.h
References MVA_woutCaloResponse, and value.
void HFTriggerMVA::setTrackTrackDCA (float value) inline
Definition at line 102 of file HFTriggerMVA.h.
View newest version in sPHENIX GitHub at line 102 of file HFTriggerMVA.h
References trackTrackDCA, and value.
void HFTriggerMVA::setTrackVertex2DDCA (float value) inline
Definition at line 101 of file HFTriggerMVA.h.
View newest version in sPHENIX GitHub at line 101 of file HFTriggerMVA.h
References trackVertex2DDCA, and value.
void HFTriggerMVA::setTrackVertex3DDCA (float value) inline
Definition at line 100 of file HFTriggerMVA.h.
View newest version in sPHENIX GitHub at line 100 of file HFTriggerMVA.h
References trackVertex3DDCA, and value.
Member Data Documentation
float HFTriggerMVA::asymmMult = 0.1 private
Definition at line 115 of file HFTriggerMVA.h.
View newest version in sPHENIX GitHub at line 115 of file HFTriggerMVA.h
Referenced by runTrigger(), and setAsymmMult().
int HFTriggerMVA::m_counter = 0 private
Definition at line 138 of file HFTriggerMVA.h.
View newest version in sPHENIX GitHub at line 138 of file HFTriggerMVA.h
Referenced by printRunRecord(), and process_event().
int HFTriggerMVA::m_cuts_and_mva_wcalo_counter = 0 private
Definition at line 139 of file HFTriggerMVA.h.
View newest version in sPHENIX GitHub at line 139 of file HFTriggerMVA.h
Referenced by printRunRecord(), and process_event().
int HFTriggerMVA::m_cuts_and_mva_woutcalo_and_mintracks_counter = 0 private
Definition at line 147 of file HFTriggerMVA.h.
View newest version in sPHENIX GitHub at line 147 of file HFTriggerMVA.h
Referenced by printRunRecord(), and process_event().
int HFTriggerMVA::m_cuts_and_mva_woutcalo_counter = 0 private
Definition at line 143 of file HFTriggerMVA.h.
View newest version in sPHENIX GitHub at line 143 of file HFTriggerMVA.h
Referenced by printRunRecord(), and process_event().
int HFTriggerMVA::m_cuts_and_no_mva_wcalo_counter = 0 private
Definition at line 141 of file HFTriggerMVA.h.
View newest version in sPHENIX GitHub at line 141 of file HFTriggerMVA.h
Referenced by printRunRecord(), and process_event().
int HFTriggerMVA::m_cuts_and_no_mva_woutcalo_and_mintracks_counter = 0 private
Definition at line 149 of file HFTriggerMVA.h.
View newest version in sPHENIX GitHub at line 149 of file HFTriggerMVA.h
Referenced by printRunRecord(), and process_event().
int HFTriggerMVA::m_cuts_and_no_mva_woutcalo_counter = 0 private
Definition at line 145 of file HFTriggerMVA.h.
View newest version in sPHENIX GitHub at line 145 of file HFTriggerMVA.h
Referenced by printRunRecord(), and process_event().
SvtxTrack* HFTriggerMVA::m_dst_track = nullptr private
Definition at line 133 of file HFTriggerMVA.h.
View newest version in sPHENIX GitHub at line 133 of file HFTriggerMVA.h
Referenced by getMaxEMCalEnergy(), makeAllTracks(), and makeTrack().
SvtxTrackMap* HFTriggerMVA::m_dst_trackmap = nullptr private
Definition at line 131 of file HFTriggerMVA.h.
View newest version in sPHENIX GitHub at line 131 of file HFTriggerMVA.h
Referenced by getMaxEMCalEnergy(), and makeAllTracks().
SvtxVertex* HFTriggerMVA::m_dst_vertex = nullptr private
Definition at line 132 of file HFTriggerMVA.h.
View newest version in sPHENIX GitHub at line 132 of file HFTriggerMVA.h
Referenced by makeAllPrimaryVertices(), and makeVertex().
SvtxVertexMap* HFTriggerMVA::m_dst_vertexmap = nullptr private
Definition at line 130 of file HFTriggerMVA.h.
View newest version in sPHENIX GitHub at line 130 of file HFTriggerMVA.h
Referenced by makeAllPrimaryVertices().
int HFTriggerMVA::m_events = 0 private
Definition at line 136 of file HFTriggerMVA.h.
View newest version in sPHENIX GitHub at line 136 of file HFTriggerMVA.h
Referenced by printRunRecord(), and process_event().
int HFTriggerMVA::m_no_cuts_and_mva_wcalo_counter = 0 private
Definition at line 140 of file HFTriggerMVA.h.
View newest version in sPHENIX GitHub at line 140 of file HFTriggerMVA.h
Referenced by printRunRecord(), and process_event().
int HFTriggerMVA::m_no_cuts_and_mva_woutcalo_and_mintracks_counter = 0 private
Definition at line 148 of file HFTriggerMVA.h.
View newest version in sPHENIX GitHub at line 148 of file HFTriggerMVA.h
Referenced by printRunRecord(), and process_event().
int HFTriggerMVA::m_no_cuts_and_mva_woutcalo_counter = 0 private
Definition at line 144 of file HFTriggerMVA.h.
View newest version in sPHENIX GitHub at line 144 of file HFTriggerMVA.h
Referenced by printRunRecord(), and process_event().
int HFTriggerMVA::m_no_cuts_and_no_mva_wcalo_counter = 0 private
Definition at line 142 of file HFTriggerMVA.h.
View newest version in sPHENIX GitHub at line 142 of file HFTriggerMVA.h
Referenced by printRunRecord(), and process_event().
int HFTriggerMVA::m_no_cuts_and_no_mva_woutcalo_and_mintracks_counter = 0 private
Definition at line 150 of file HFTriggerMVA.h.
View newest version in sPHENIX GitHub at line 150 of file HFTriggerMVA.h
Referenced by printRunRecord(), and process_event().
int HFTriggerMVA::m_no_cuts_and_no_mva_woutcalo_counter = 0 private
Definition at line 146 of file HFTriggerMVA.h.
View newest version in sPHENIX GitHub at line 146 of file HFTriggerMVA.h
Referenced by printRunRecord(), and process_event().
int HFTriggerMVA::m_no_trigger = 0 private
Definition at line 137 of file HFTriggerMVA.h.
View newest version in sPHENIX GitHub at line 137 of file HFTriggerMVA.h
Referenced by printRunRecord(), and process_event().
SvtxEvalStack* HFTriggerMVA::m_svtx_evalstack = nullptr protected
Definition at line 109 of file HFTriggerMVA.h.
View newest version in sPHENIX GitHub at line 109 of file HFTriggerMVA.h
bool HFTriggerMVA::m_useCutsTrigger = false private
Definition at line 124 of file HFTriggerMVA.h.
View newest version in sPHENIX GitHub at line 124 of file HFTriggerMVA.h
Referenced by printTrigger(), requireCutsTrigger(), and runTrigger().
bool HFTriggerMVA::m_useCutswoutTrigger = false private
Definition at line 125 of file HFTriggerMVA.h.
View newest version in sPHENIX GitHub at line 125 of file HFTriggerMVA.h
Referenced by runTrigger().
bool HFTriggerMVA::m_useMVAwCaloTrigger = false private
Definition at line 126 of file HFTriggerMVA.h.
View newest version in sPHENIX GitHub at line 126 of file HFTriggerMVA.h
Referenced by Init(), printTrigger(), requireMVAwCaloTrigger(), and runTrigger().
bool HFTriggerMVA::m_useMVAwoutCaloAndMinTrackTrigger = false private
Definition at line 128 of file HFTriggerMVA.h.
View newest version in sPHENIX GitHub at line 128 of file HFTriggerMVA.h
Referenced by Init(), and runTrigger().
bool HFTriggerMVA::m_useMVAwoutCaloTrigger = false private
Definition at line 127 of file HFTriggerMVA.h.
View newest version in sPHENIX GitHub at line 127 of file HFTriggerMVA.h
Referenced by Init(), and runTrigger().
float HFTriggerMVA::meanMult = 12 private
Definition at line 114 of file HFTriggerMVA.h.
View newest version in sPHENIX GitHub at line 114 of file HFTriggerMVA.h
Referenced by Init(), runCutsTrigger(), runTrigger(), and setMeanMult().
float HFTriggerMVA::minEMCalEnergy = 0.5 private
Definition at line 119 of file HFTriggerMVA.h.
View newest version in sPHENIX GitHub at line 119 of file HFTriggerMVA.h
Referenced by Init(), runCutsTrigger(), and setminEMCalEnergy().
float HFTriggerMVA::MVA_wCaloResponse = -0.05 private
Definition at line 120 of file HFTriggerMVA.h.
View newest version in sPHENIX GitHub at line 120 of file HFTriggerMVA.h
Referenced by Init(), runTrigger(), and setMVA_wCaloResponse().
float HFTriggerMVA::MVA_woutCaloOrMinTrackResponse = -0.05 private
Definition at line 122 of file HFTriggerMVA.h.
View newest version in sPHENIX GitHub at line 122 of file HFTriggerMVA.h
Referenced by Init(), runTrigger(), and setMVA_woutCaloOrMinTrackResponse().
float HFTriggerMVA::MVA_woutCaloResponse = -0.05 private
Definition at line 121 of file HFTriggerMVA.h.
View newest version in sPHENIX GitHub at line 121 of file HFTriggerMVA.h
Referenced by Init(), runTrigger(), and setMVA_woutCaloResponse().
std::string HFTriggerMVA::mvaType = "BDTG" private
Definition at line 155 of file HFTriggerMVA.h.
View newest version in sPHENIX GitHub at line 155 of file HFTriggerMVA.h
Referenced by Init(), and runTrigger().
std::string HFTriggerMVA::path = "/sphenix/u/cdean/software/analysis/HF-Particle/HFTrigger/weights/" private
Definition at line 153 of file HFTriggerMVA.h.
View newest version in sPHENIX GitHub at line 153 of file HFTriggerMVA.h
Referenced by item.Item::__eq__(), item.Item::__hash__(), and Init().
SvtxTrackEval* HFTriggerMVA::trackeval = nullptr protected
Definition at line 110 of file HFTriggerMVA.h.
View newest version in sPHENIX GitHub at line 110 of file HFTriggerMVA.h
float HFTriggerMVA::trackTrackDCA = 0.05 private
Definition at line 118 of file HFTriggerMVA.h.
View newest version in sPHENIX GitHub at line 118 of file HFTriggerMVA.h
Referenced by Init(), runCutsTrigger(), and setTrackTrackDCA().
float HFTriggerMVA::trackVertex2DDCA = 0.05 private
Definition at line 117 of file HFTriggerMVA.h.
View newest version in sPHENIX GitHub at line 117 of file HFTriggerMVA.h
Referenced by Init(), runCutsTrigger(), and setTrackVertex2DDCA().
float HFTriggerMVA::trackVertex3DDCA = 0.05 private
Definition at line 116 of file HFTriggerMVA.h.
View newest version in sPHENIX GitHub at line 116 of file HFTriggerMVA.h
Referenced by Init(), runCutsTrigger(), and setTrackVertex3DDCA().
std::vector<std::string> HFTriggerMVA::varListwCalo private
Initial value:
= {"min(track_1_IP,track_2_IP)",
                                           "min(abs(track_1_IP_xy),abs(track_2_IP_xy))",
                                           "max(track_1_IP,track_2_IP)",
                                           "max(abs(track_1_IP_xy),abs(track_2_IP_xy))",
                                           "max(track_1_EMCAL_energy_cluster,track_2_EMCAL_energy_cluster)",
                                           "track_1_track_2_DCA",
                                           "INTT_meanHits"}
Definition at line 157 of file HFTriggerMVA.h.
View newest version in sPHENIX GitHub at line 157 of file HFTriggerMVA.h
Referenced by Init().
std::vector<std::string> HFTriggerMVA::varListwoutCalo private
Initial value:
= {"min(track_1_IP,track_2_IP)",
                                              "min(abs(track_1_IP_xy),abs(track_2_IP_xy))",
                                              "max(track_1_IP,track_2_IP)",
                                              "max(abs(track_1_IP_xy),abs(track_2_IP_xy))",
                                              "track_1_track_2_DCA",
                                              "INTT_meanHits"}
Definition at line 165 of file HFTriggerMVA.h.
View newest version in sPHENIX GitHub at line 165 of file HFTriggerMVA.h
Referenced by Init().
std::vector<std::string> HFTriggerMVA::varListwoutCaloAndMinTrack private
Initial value:
= {"max(track_1_IP,track_2_IP)",
                                                         "max(abs(track_1_IP_xy),abs(track_2_IP_xy))",
                                                         "track_1_track_2_DCA",
                                                         "INTT_meanHits"}
Definition at line 172 of file HFTriggerMVA.h.
View newest version in sPHENIX GitHub at line 172 of file HFTriggerMVA.h
Referenced by Init().
std::vector<float> HFTriggerMVA::wCaloFloats private
Definition at line 178 of file HFTriggerMVA.h.
View newest version in sPHENIX GitHub at line 178 of file HFTriggerMVA.h
Referenced by Init(), and runTrigger().
TMVA::Reader* HFTriggerMVA::wCaloReader private
Definition at line 177 of file HFTriggerMVA.h.
View newest version in sPHENIX GitHub at line 177 of file HFTriggerMVA.h
Referenced by Init(), and runTrigger().
std::vector<float> HFTriggerMVA::woutCaloAndMinTrackFloats private
Definition at line 178 of file HFTriggerMVA.h.
View newest version in sPHENIX GitHub at line 178 of file HFTriggerMVA.h
Referenced by Init(), and runTrigger().
TMVA::Reader * HFTriggerMVA::woutCaloAndMinTrackReader private
Definition at line 177 of file HFTriggerMVA.h.
View newest version in sPHENIX GitHub at line 177 of file HFTriggerMVA.h
Referenced by Init(), and runTrigger().
std::vector<float> HFTriggerMVA::woutCaloFloats private
Definition at line 178 of file HFTriggerMVA.h.
View newest version in sPHENIX GitHub at line 178 of file HFTriggerMVA.h
Referenced by Init(), and runTrigger().
TMVA::Reader * HFTriggerMVA::woutCaloReader private
Definition at line 177 of file HFTriggerMVA.h.
View newest version in sPHENIX GitHub at line 177 of file HFTriggerMVA.h
Referenced by Init(), and runTrigger().
The documentation for this class was generated from the following files:
analysis/blob/master/HF-Particle/HFTrigger/HFTriggerMVA.h
analysis/blob/master/HF-Particle/HFTrigger/HFTriggerMVA.cc