Analysis Software: ActsExamples::TrackSummaryPlotTool Class Reference
ActsExamples::TrackSummaryPlotTool Class Reference
#include <acts/blob/sPHENIX/Examples/Framework/include/ActsExamples/Validation/TrackSummaryPlotTool.hpp>
Classes
struct Config
The nested configuration struct.
struct TrackSummaryPlotCache
Nested Cache struct.
Public Member Functions
TrackSummaryPlotTool (const Config &cfg, Acts::Logging::Level lvl)
void book (TrackSummaryPlotCache &trackSummaryPlotCache) const
book the track info plots
void fill (TrackSummaryPlotCache &trackSummaryPlotCache, const Acts::BoundTrackParameters &fittedParameters, size_t nStates, size_t nMeasurements, size_t Outliers, size_t nHoles, size_t nSharedHits) const
fill reco track info w.r.t. fitted track parameters
void write (const TrackSummaryPlotCache &trackSummaryPlotCache) const
write the track info plots to file
void clear (TrackSummaryPlotCache &trackSummaryPlotCache) const
delete the track info plots
Private Member Functions
const Acts::Logger & logger () const
The logger.
Private Attributes
Config m_cfg
The Config class.
std::unique_ptr< const
Acts::Logger > m_logger
The logging instance.
Detailed Description
Definition at line 26 of file TrackSummaryPlotTool.hpp.
View newest version in sPHENIX GitHub at line 26 of file TrackSummaryPlotTool.hpp
Constructor & Destructor Documentation
ActsExamples::TrackSummaryPlotTool::TrackSummaryPlotTool (const Config & cfg, Acts::Logging::Level lvl)
Constructor
Parameters
cfg Configuration struct
lvl Message level declaration
Definition at line 16 of file TrackSummaryPlotTool.cpp.
View newest version in sPHENIX GitHub at line 16 of file TrackSummaryPlotTool.cpp
Member Function Documentation
void ActsExamples::TrackSummaryPlotTool::book (TrackSummaryPlotTool::TrackSummaryPlotCache & trackSummaryPlotCache) const
book the track info plots
Parameters
trackSummaryPlotCache the cache for track info plots
Definition at line 22 of file TrackSummaryPlotTool.cpp.
View newest version in sPHENIX GitHub at line 22 of file TrackSummaryPlotTool.cpp
References ACTS_DEBUG, ActsExamples::PlotHelpers::bookProf(), m_cfg(), ActsExamples::TrackSummaryPlotTool::TrackSummaryPlotCache::nHoles_vs_eta, ActsExamples::TrackSummaryPlotTool::TrackSummaryPlotCache::nHoles_vs_pt, ActsExamples::TrackSummaryPlotTool::TrackSummaryPlotCache::nMeasurements_vs_eta, ActsExamples::TrackSummaryPlotTool::TrackSummaryPlotCache::nMeasurements_vs_pt, ActsExamples::TrackSummaryPlotTool::TrackSummaryPlotCache::nOutliers_vs_eta, ActsExamples::TrackSummaryPlotTool::TrackSummaryPlotCache::nOutliers_vs_pt, ActsExamples::TrackSummaryPlotTool::TrackSummaryPlotCache::nSharedHits_vs_eta, ActsExamples::TrackSummaryPlotTool::TrackSummaryPlotCache::nSharedHits_vs_pt, ActsExamples::TrackSummaryPlotTool::TrackSummaryPlotCache::nStates_vs_eta, and ActsExamples::TrackSummaryPlotTool::TrackSummaryPlotCache::nStates_vs_pt.
Referenced by ActsExamples::CKFPerformanceWriter::CKFPerformanceWriter(), and ActsExamples::TrackFitterPerformanceWriter::TrackFitterPerformanceWriter().
void ActsExamples::TrackSummaryPlotTool::clear (TrackSummaryPlotCache & trackSummaryPlotCache) const
delete the track info plots
Parameters
trackSummaryPlotCache cache object for track info plots
Definition at line 60 of file TrackSummaryPlotTool.cpp.
View newest version in sPHENIX GitHub at line 60 of file TrackSummaryPlotTool.cpp
References ActsExamples::TrackSummaryPlotTool::TrackSummaryPlotCache::nHoles_vs_eta, ActsExamples::TrackSummaryPlotTool::TrackSummaryPlotCache::nHoles_vs_pt, ActsExamples::TrackSummaryPlotTool::TrackSummaryPlotCache::nMeasurements_vs_eta, ActsExamples::TrackSummaryPlotTool::TrackSummaryPlotCache::nMeasurements_vs_pt, ActsExamples::TrackSummaryPlotTool::TrackSummaryPlotCache::nOutliers_vs_eta, ActsExamples::TrackSummaryPlotTool::TrackSummaryPlotCache::nOutliers_vs_pt, ActsExamples::TrackSummaryPlotTool::TrackSummaryPlotCache::nSharedHits_vs_eta, ActsExamples::TrackSummaryPlotTool::TrackSummaryPlotCache::nSharedHits_vs_pt, ActsExamples::TrackSummaryPlotTool::TrackSummaryPlotCache::nStates_vs_eta, and ActsExamples::TrackSummaryPlotTool::TrackSummaryPlotCache::nStates_vs_pt.
void ActsExamples::TrackSummaryPlotTool::fill (TrackSummaryPlotTool::TrackSummaryPlotCache & trackSummaryPlotCache, const Acts::BoundTrackParameters & fittedParameters, size_t nStates, size_t nMeasurements, size_t Outliers, size_t nHoles, size_t nSharedHits) const
fill reco track info w.r.t. fitted track parameters
Parameters
trackSummaryPlotCache cache object for track info plots
fittedParameters fitted track parameters of this track
nStates number of track states
nMeasurements number of measurements
nOutliers number of outliers
nHoles number of holes
Definition at line 90 of file TrackSummaryPlotTool.cpp.
View newest version in sPHENIX GitHub at line 90 of file TrackSummaryPlotTool.cpp
References eta, Acts::VectorHelpers::eta(), ActsExamples::PlotHelpers::fillProf(), momentum, Acts::GenericBoundTrackParameters< particle_hypothesis_t >::momentum(), ActsExamples::TrackSummaryPlotTool::TrackSummaryPlotCache::nHoles_vs_eta, ActsExamples::TrackSummaryPlotTool::TrackSummaryPlotCache::nHoles_vs_pt, ActsExamples::TrackSummaryPlotTool::TrackSummaryPlotCache::nMeasurements_vs_eta, ActsExamples::TrackSummaryPlotTool::TrackSummaryPlotCache::nMeasurements_vs_pt, ActsExamples::TrackSummaryPlotTool::TrackSummaryPlotCache::nOutliers_vs_eta, ActsExamples::TrackSummaryPlotTool::TrackSummaryPlotCache::nOutliers_vs_pt, ActsExamples::TrackSummaryPlotTool::TrackSummaryPlotCache::nSharedHits_vs_eta, ActsExamples::TrackSummaryPlotTool::TrackSummaryPlotCache::nSharedHits_vs_pt, ActsExamples::TrackSummaryPlotTool::TrackSummaryPlotCache::nStates_vs_eta, ActsExamples::TrackSummaryPlotTool::TrackSummaryPlotCache::nStates_vs_pt, and Acts::VectorHelpers::perp().
const Acts::Logger& ActsExamples::TrackSummaryPlotTool::logger () const inline private
The logger.
Definition at line 92 of file TrackSummaryPlotTool.hpp.
View newest version in sPHENIX GitHub at line 92 of file TrackSummaryPlotTool.hpp
References m_logger.
void ActsExamples::TrackSummaryPlotTool::write (const TrackSummaryPlotCache & trackSummaryPlotCache) const
write the track info plots to file
Parameters
trackSummaryPlotCache cache object for track info plots
Definition at line 74 of file TrackSummaryPlotTool.cpp.
View newest version in sPHENIX GitHub at line 74 of file TrackSummaryPlotTool.cpp
References ACTS_DEBUG, ActsExamples::TrackSummaryPlotTool::TrackSummaryPlotCache::nHoles_vs_eta, ActsExamples::TrackSummaryPlotTool::TrackSummaryPlotCache::nHoles_vs_pt, ActsExamples::TrackSummaryPlotTool::TrackSummaryPlotCache::nMeasurements_vs_eta, ActsExamples::TrackSummaryPlotTool::TrackSummaryPlotCache::nMeasurements_vs_pt, ActsExamples::TrackSummaryPlotTool::TrackSummaryPlotCache::nOutliers_vs_eta, ActsExamples::TrackSummaryPlotTool::TrackSummaryPlotCache::nOutliers_vs_pt, ActsExamples::TrackSummaryPlotTool::TrackSummaryPlotCache::nSharedHits_vs_eta, ActsExamples::TrackSummaryPlotTool::TrackSummaryPlotCache::nSharedHits_vs_pt, ActsExamples::TrackSummaryPlotTool::TrackSummaryPlotCache::nStates_vs_eta, and ActsExamples::TrackSummaryPlotTool::TrackSummaryPlotCache::nStates_vs_pt.
Member Data Documentation
Config ActsExamples::TrackSummaryPlotTool::m_cfg private
The Config class.
Definition at line 88 of file TrackSummaryPlotTool.hpp.
View newest version in sPHENIX GitHub at line 88 of file TrackSummaryPlotTool.hpp
std::unique_ptr<const Acts::Logger> ActsExamples::TrackSummaryPlotTool::m_logger private
The logging instance.
Definition at line 89 of file TrackSummaryPlotTool.hpp.
View newest version in sPHENIX GitHub at line 89 of file TrackSummaryPlotTool.hpp
Referenced by logger().
The documentation for this class was generated from the following files:
acts/blob/sPHENIX/Examples/Framework/include/ActsExamples/Validation/TrackSummaryPlotTool.hpp
acts/blob/sPHENIX/Examples/Framework/src/Validation/TrackSummaryPlotTool.cpp