Analysis Software: tutorials/blob/master/AnaTutorial/macro/G4Setup_EICDetector.C File Reference
G4Setup_EICDetector.C File Reference
#include <GlobalVariables.C>
#include <G4_Aerogel.C>
#include <G4_Barrel_EIC.C>
#include <G4_Bbc.C>
#include <G4_BlackHole.C>
#include <G4_CEmc_EIC.C>
#include <G4_DIRC.C>
#include <G4_EEMC.C>
#include <G4_FEMC_EIC.C>
#include <G4_FHCAL.C>
#include <G4_FST_EIC.C>
#include <G4_GEM_EIC.C>
#include <G4_HcalIn_ref.C>
#include <G4_HcalOut_ref.C>
#include <G4_Input.C>
#include <G4_Magnet.C>
#include <G4_Mvtx_EIC.C>
#include <G4_Pipe_EIC.C>
#include <G4_PlugDoor_EIC.C>
#include <G4_RICH.C>
#include <G4_TPC_EIC.C>
#include <G4_Tracking_EIC.C>
#include <G4_User.C>
#include <G4_World.C>
#include <G4_hFarFwdBeamLine_EIC.C>
#include <g4detectors/PHG4CylinderSubsystem.h>
#include <g4eval/PHG4DstCompressReco.h>
#include <g4main/PHG4Reco.h>
#include <g4main/PHG4TruthSubsystem.h>
#include <phfield/PHFieldConfig.h>
#include <g4decayer/EDecayType.hh>
#include <fun4all/Fun4AllDstOutputManager.h>
#include <fun4all/Fun4AllServer.h>
Macros
#define MACRO_G4SETUPEICDETECTOR_C
Functions
void G4Init ()
int G4Setup ()
void ShowerCompress ()
void DstCompress (Fun4AllDstOutputManager *out)
Macro Definition Documentation
#define MACRO_G4SETUPEICDETECTOR_C
Definition at line 2 of file G4Setup_EICDetector.C.
View newest version in sPHENIX GitHub at line 2 of file G4Setup_EICDetector.C
Function Documentation
void DstCompress (Fun4AllDstOutputManager * out)
Definition at line 259 of file G4Setup_EICDetector.C.
View newest version in sPHENIX GitHub at line 259 of file G4Setup_EICDetector.C
References Fun4AllDstOutputManager::StripNode().
void G4Init ()
Definition at line 48 of file G4Setup_EICDetector.C.
View newest version in sPHENIX GitHub at line 48 of file G4Setup_EICDetector.C
References AerogelInit(), BbcInit(), Enable::BLACKHOLE, BlackHoleInit(), Enable::CEMC, CEmcInit(), DIRCInit(), RawTowerDefs::EEMC, EEMCInit(), EGEM_Init(), RawTowerDefs::FEMC, FEMCInit(), FGEM_Init(), RawTowerDefs::FHCAL, FHCALInit(), Enable::HCALIN, HCalInnerInit(), Enable::HCALOUT, HCalOuterInit(), Enable::MAGNET, MagnetFieldInit(), MagnetInit(), Enable::MVTX, MvtxInit(), Enable::PIPE, PipeInit(), Enable::PLUGDOOR, PlugDoorInit(), RICHInit(), Enable::TPC, TPCInit(), TrackingInit(), Enable::USER, and UserInit().
int G4Setup ()
Definition at line 106 of file G4Setup_EICDetector.C.
View newest version in sPHENIX GitHub at line 106 of file G4Setup_EICDetector.C
References AerogelSetup(), Bbc(), Enable::BLACKHOLE, BlackHole(), CEmc(), Enable::CEMC, G4P6DECAYER::decayType, DIRCSetup(), RawTowerDefs::EEMC, EEMCSetup(), EGEMSetup(), RawTowerDefs::FEMC, FEMCSetup(), FGEMSetup(), RawTowerDefs::FHCAL, FHCALSetup(), PHFieldConfig::Field3DCartesian, Enable::HCALIN, HCalInner(), Enable::HCALOUT, HCalOuter(), Fun4AllServer::instance(), kAll, PHFieldConfig::kField2D, G4MAGNET::magfield, G4MAGNET::magfield_rescale, Magnet(), Enable::MAGNET, Enable::MVTX, Mvtx(), Pipe(), Enable::PIPE, Enable::PLUGDOOR, PlugDoor(), Fun4AllServer::registerSubsystem(), PHG4Reco::registerSubsystem(), RICHSetup(), PHG4Reco::set_field(), PHG4Reco::set_field_map(), PHG4Reco::set_field_rescale(), PHG4Reco::set_force_decay(), PHG4Reco::set_rapidity_coverage(), g4evalfn::TPC, Enable::TPC, Enable::USER, UserDetector(), WorldInit(), and WorldSize().
void ShowerCompress ()
Definition at line 198 of file G4Setup_EICDetector.C.
View newest version in sPHENIX GitHub at line 198 of file G4Setup_EICDetector.C
References PHG4DstCompressReco::AddCellContainer(), PHG4DstCompressReco::AddHitContainer(), PHG4DstCompressReco::AddTowerContainer(), Fun4AllServer::instance(), and Fun4AllServer::registerSubsystem().