Analysis Software: cl::Image2D Class Reference
cl::Image2D Class Reference
Image interface for 2D images.
#include <JETSCAPE/blob/main/external_packages/clvisc_wrapper/include/cl.hpp>
Public Member Functions
Image2D (const Context &context, cl_mem_flags flags, ImageFormat format,::size_t width,::size_t height,::size_t row_pitch=0, void *host_ptr=NULL, cl_int *err=NULL)
Image2D ()
Image2D (const Image2D &image2D)
Image2D & operator= (const Image2D &rhs)
Public Member Functions inherited from cl::Image
template<typename T >
cl_int getImageInfo (cl_image_info name, T *param) const
template<cl_int name>
detail::param_traits
< detail::cl_image_info, name >
::param_type getImageInfo (cl_int *err=NULL) const
Public Member Functions inherited from cl::Memory
Memory ()
Memory (const Memory &memory)
Memory & operator= (const Memory &rhs)
template<typename T >
cl_int getInfo (cl_mem_info name, T *param) const
template<cl_int name>
detail::param_traits
< detail::cl_mem_info, name >
::param_type getInfo (cl_int *err=NULL) const
Public Member Functions inherited from cl::detail::Wrapper< cl_mem >
Wrapper ()
Wrapper (const Wrapper< cl_type > &rhs)
~Wrapper ()
Wrapper< cl_type > & operator= (const Wrapper< cl_type > &rhs)
cl_type operator() () const
cl_type & operator() ()
Additional Inherited Members
Public Types inherited from cl::detail::Wrapper< cl_mem >
typedef cl_mem cl_type
Protected Member Functions inherited from cl::Image
Image ()
Image (const Image &image)
Image & operator= (const Image &rhs)
Protected Attributes inherited from cl::detail::Wrapper< cl_mem >
cl_type object_
Detailed Description
Image interface for 2D images.
Definition at line 1979 of file cl.hpp.
View newest version in sPHENIX GitHub at line 1979 of file cl.hpp
Constructor & Destructor Documentation
cl::Image2D::Image2D (const Context & context, cl_mem_flags flags, ImageFormat format, ::size_t width, ::size_t height, ::size_t row_pitch = 0, void * host_ptr = NULL, cl_int * err = NULL) inline
Definition at line 1982 of file cl.hpp.
View newest version in sPHENIX GitHub at line 1982 of file cl.hpp
References cl::detail::errHandler(), acts::error, and cl::detail::Wrapper< cl_mem >::object_.
cl::Image2D::Image2D () inline
Definition at line 2002 of file cl.hpp.
View newest version in sPHENIX GitHub at line 2002 of file cl.hpp
cl::Image2D::Image2D (const Image2D & image2D) inline
Definition at line 2004 of file cl.hpp.
View newest version in sPHENIX GitHub at line 2004 of file cl.hpp
Member Function Documentation
Image2D& cl::Image2D::operator= (const Image2D & rhs) inline
Definition at line 2006 of file cl.hpp.
View newest version in sPHENIX GitHub at line 2006 of file cl.hpp
References cl::Image::operator=().
Referenced by cl::Image2DGL::operator=().
The documentation for this class was generated from the following file:
JETSCAPE/blob/main/external_packages/clvisc_wrapper/include/cl.hpp