Analysis Software: ActsExamples::PlotHelpers Namespace Reference
ActsExamples::PlotHelpers Namespace Reference
Classes
class Binning
Nested binning struct for booking plots.
Functions
TH1F * bookHisto (const char *histName, const char *histTitle, const Binning &varBinning)
book a 1D histogram
TH2F * bookHisto (const char *histName, const char *histTitle, const Binning &varXBinning, const Binning &varYBinning)
book a 2D histogram
void fillHisto (TH1F *hist, float value, float weight=1.0)
fill a 1D histogram
void fillHisto (TH2F *hist, float xValue, float yValue, float weight=1.0)
fill a 2D histogram
void anaHisto (TH1D *inputHist, int j, TH1F *meanHist, TH1F *widthHist)
extract details, i.e. mean and width of a 1D histogram and fill them into histograms
TEfficiency * bookEff (const char *effName, const char *effTitle, const Binning &varBinning)
book a 1D efficiency plot
TEfficiency * bookEff (const char *effName, const char *effTitle, const Binning &varXBinning, const Binning &varYBinning)
book a 2D efficiency plot
void fillEff (TEfficiency *efficiency, float value, bool status)
fill a 1D efficiency plot
void fillEff (TEfficiency *efficiency, float xValue, float yValue, bool status)
fill a 2D efficiency plot
TProfile * bookProf (const char *profName, const char *profTitle, const Binning &varXBinning, const Binning &varYBinning)
book a TProfile plot
void fillProf (TProfile *profile, float xValue, float yValue, float weight=1.0)
fill a TProfile plot
Function Documentation
void ActsExamples::PlotHelpers::anaHisto (TH1D * inputHist, int j, TH1F * meanHist, TH1F * widthHist)
extract details, i.e. mean and width of a 1D histogram and fill them into histograms
Parameters
inputHist histogram to investigate
j which bin number of meanHist and widthHist to fill
meanHist histogram to fill the mean value of inputHist
widthHist histogram to fill the width value of inputHist
Definition at line 55 of file Helpers.cpp.
View newest version in sPHENIX GitHub at line 55 of file Helpers.cpp
References assert, and physmon_track_finding_ttbar::r.
Referenced by ActsExamples::ResPlotTool::refinement().
TEfficiency * ActsExamples::PlotHelpers::bookEff (const char * effName, const char * effTitle, const Binning & varBinning)
book a 1D efficiency plot
Parameters
effName the name of plot
effTitle the title of plot
varBinning the binning info of variable
Returns
TEfficiency pointer
Definition at line 71 of file Helpers.cpp.
View newest version in sPHENIX GitHub at line 71 of file Helpers.cpp
References ActsExamples::PlotHelpers::Binning::data(), and ActsExamples::PlotHelpers::Binning::nBins().
Referenced by ActsExamples::EffPlotTool::book(), ActsExamples::DuplicationPlotTool::book(), and ActsExamples::FakeRatePlotTool::book().
TEfficiency * ActsExamples::PlotHelpers::bookEff (const char * effName, const char * effTitle, const Binning & varXBinning, const Binning & varYBinning)
book a 2D efficiency plot
Parameters
effName the name of plot
effTitle the title of plot
varXBinning the binning info of variable at x axis
varYBinning the binning info of variable at y axis
Returns
TEfficiency pointer
Definition at line 78 of file Helpers.cpp.
View newest version in sPHENIX GitHub at line 78 of file Helpers.cpp
References ActsExamples::PlotHelpers::Binning::data(), and ActsExamples::PlotHelpers::Binning::nBins().
TH1F * ActsExamples::PlotHelpers::bookHisto (const char * histName, const char * histTitle, const Binning & varBinning)
book a 1D histogram
Parameters
histName the name of histogram
histTitle the title of histogram
varBinning the binning info of variable
Returns
histogram pointer
Definition at line 24 of file Helpers.cpp.
View newest version in sPHENIX GitHub at line 24 of file Helpers.cpp
References ActsExamples::PlotHelpers::Binning::data(), add_histos::hist, ActsExamples::PlotHelpers::Binning::nBins(), and ActsExamples::PlotHelpers::Binning::title().
Referenced by ActsExamples::FakeRatePlotTool::book(), and ActsExamples::ResPlotTool::book().
TH2F * ActsExamples::PlotHelpers::bookHisto (const char * histName, const char * histTitle, const Binning & varXBinning, const Binning & varYBinning)
book a 2D histogram
Parameters
histName the name of histogram
histTitle the title of histogram
varXBinning the binning info of variable at x axis
varYBinning the binning info of variable at y axis
Returns
histogram pointer
Definition at line 34 of file Helpers.cpp.
View newest version in sPHENIX GitHub at line 34 of file Helpers.cpp
References ActsExamples::PlotHelpers::Binning::data(), add_histos::hist, ActsExamples::PlotHelpers::Binning::nBins(), and ActsExamples::PlotHelpers::Binning::title().
TProfile * ActsExamples::PlotHelpers::bookProf (const char * profName, const char * profTitle, const Binning & varXBinning, const Binning & varYBinning)
book a TProfile plot
Parameters
profName the name of plot
profTitle the title of plot
varXBinning the binning info of variable at x axis
varYBinning the binning info of variable at y axis
Returns
TProfile pointer
Definition at line 96 of file Helpers.cpp.
View newest version in sPHENIX GitHub at line 96 of file Helpers.cpp
References ActsExamples::PlotHelpers::Binning::data(), ActsExamples::PlotHelpers::Binning::high(), ActsExamples::PlotHelpers::Binning::low(), ActsExamples::PlotHelpers::Binning::nBins(), and ActsExamples::PlotHelpers::Binning::title().
Referenced by ActsExamples::TrackSummaryPlotTool::book(), and ActsExamples::DuplicationPlotTool::book().
void ActsExamples::PlotHelpers::fillEff (TEfficiency * efficiency, float value, bool status)
fill a 1D efficiency plot
Parameters
efficiency plot to fill
value value to fill
status bool to denote passed or not
Definition at line 86 of file Helpers.cpp.
View newest version in sPHENIX GitHub at line 86 of file Helpers.cpp
References assert.
Referenced by ActsExamples::EffPlotTool::fill(), ActsExamples::DuplicationPlotTool::fill(), and ActsExamples::FakeRatePlotTool::fill().
void ActsExamples::PlotHelpers::fillEff (TEfficiency * efficiency, float xValue, float yValue, bool status)
fill a 2D efficiency plot
Parameters
efficiency plot to fill
xValue x value to fill
yValue y value to fill
status bool to denote passed or not
Definition at line 91 of file Helpers.cpp.
View newest version in sPHENIX GitHub at line 91 of file Helpers.cpp
References assert.
void ActsExamples::PlotHelpers::fillHisto (TH1F * hist, float value, float weight = 1.0)
fill a 1D histogram
Parameters
hist histogram to fill
value value to fill
weight weight to fill
Definition at line 45 of file Helpers.cpp.
View newest version in sPHENIX GitHub at line 45 of file Helpers.cpp
References assert.
Referenced by ActsExamples::FakeRatePlotTool::fill(), and ActsExamples::ResPlotTool::fill().
void ActsExamples::PlotHelpers::fillHisto (TH2F * hist, float xValue, float yValue, float weight = 1.0)
fill a 2D histogram
Parameters
hist histogram to fill
xValue x value to fill
yValue y value to fill
weight weight to fill
Definition at line 50 of file Helpers.cpp.
View newest version in sPHENIX GitHub at line 50 of file Helpers.cpp
References assert.
void ActsExamples::PlotHelpers::fillProf (TProfile * profile, float xValue, float yValue, float weight = 1.0)
fill a TProfile plot
Parameters
profile plot to fill
xValue xvalue to fill
yValue yvalue to fill
weight weight to fill
Definition at line 106 of file Helpers.cpp.
View newest version in sPHENIX GitHub at line 106 of file Helpers.cpp
References assert.
Referenced by ActsExamples::TrackSummaryPlotTool::fill(), and ActsExamples::DuplicationPlotTool::fill().