Analysis Software: Acts::DirectNavigator Class Reference
Acts::DirectNavigator Class Reference
#include <acts/blob/sPHENIX/Core/include/Acts/Propagator/DirectNavigator.hpp>
Classes
struct State
Public Types
using SurfaceSequence = std::vector< const Surface * >
The sequentially crossed surfaces.
using SurfaceIter = std::vector< const Surface * >::iterator
Public Member Functions
DirectNavigator (std::unique_ptr< const Logger > _logger=getDefaultLogger("DirectNavigator", Logging::INFO))
State makeState (const Surface *startSurface, const Surface *targetSurface) const
void resetState (State &state, const GeometryContext &, const Vector3 &, const Vector3 &, const Surface *ssurface, const Surface *tsurface) const
const Surface * currentSurface (const State &state) const
const TrackingVolume * currentVolume (const State &state) const
const IVolumeMaterial * currentVolumeMaterial (const State &state) const
const Surface * startSurface (const State &state) const
const Surface * targetSurface (const State &state) const
bool targetReached (const State &state) const
bool endOfWorldReached (State &state) const
bool navigationBreak (const State &state) const
void currentSurface (State &state, const Surface *surface) const
void targetReached (State &state, bool targetReached) const
void navigationBreak (State &state, bool navigationBreak) const
template<typename propagator_state_t , typename stepper_t >
void initialize (propagator_state_t &state, const stepper_t &stepper) const
Initialize call - start of propagation.
template<typename propagator_state_t , typename stepper_t >
void preStep (propagator_state_t &state, const stepper_t &stepper) const
Navigator pre step call.
template<typename propagator_state_t , typename stepper_t >
void postStep (propagator_state_t &state, const stepper_t &stepper) const
Navigator post step call.
Private Member Functions
const Logger & logger () const
Private Attributes
std::unique_ptr< const Logger > m_logger
Detailed Description
DirectNavigator class
This is a fully guided navigator that progresses through a pre-given sequence of surfaces.
This can either be used as a validation tool, for truth tracking, or track refitting
Definition at line 32 of file DirectNavigator.hpp.
View newest version in sPHENIX GitHub at line 32 of file DirectNavigator.hpp
Member Typedef Documentation
using Acts::DirectNavigator::SurfaceIter = std::vector<const Surface*>::iterator
Definition at line 36 of file DirectNavigator.hpp.
View newest version in sPHENIX GitHub at line 36 of file DirectNavigator.hpp
using Acts::DirectNavigator::SurfaceSequence = std::vector<const Surface*>
The sequentially crossed surfaces.
Definition at line 35 of file DirectNavigator.hpp.
View newest version in sPHENIX GitHub at line 35 of file DirectNavigator.hpp
Constructor & Destructor Documentation
Acts::DirectNavigator::DirectNavigator (std::unique_ptr< const Logger > _logger = getDefaultLogger("DirectNavigator", Logging::INFO)) inline
Definition at line 38 of file DirectNavigator.hpp.
View newest version in sPHENIX GitHub at line 38 of file DirectNavigator.hpp
References testing::internal::move().
Member Function Documentation
const Surface* Acts::DirectNavigator::currentSurface (const State & state) const inline
Definition at line 146 of file DirectNavigator.hpp.
View newest version in sPHENIX GitHub at line 146 of file DirectNavigator.hpp
References Acts::DirectNavigator::State::currentSurface.
void Acts::DirectNavigator::currentSurface (State & state, const Surface * surface) const inline
Definition at line 179 of file DirectNavigator.hpp.
View newest version in sPHENIX GitHub at line 179 of file DirectNavigator.hpp
References Acts::DirectNavigator::State::currentSurface, and writeMapConfig::surface.
const TrackingVolume* Acts::DirectNavigator::currentVolume (const State & state) const inline
Definition at line 150 of file DirectNavigator.hpp.
View newest version in sPHENIX GitHub at line 150 of file DirectNavigator.hpp
References Acts::DirectNavigator::State::currentVolume.
const IVolumeMaterial* Acts::DirectNavigator::currentVolumeMaterial (const State & state) const inline
Definition at line 154 of file DirectNavigator.hpp.
View newest version in sPHENIX GitHub at line 154 of file DirectNavigator.hpp
References Acts::DirectNavigator::State::currentVolume, and Acts::TrackingVolume::volumeMaterial().
bool Acts::DirectNavigator::endOfWorldReached (State & state) const inline
Definition at line 171 of file DirectNavigator.hpp.
View newest version in sPHENIX GitHub at line 171 of file DirectNavigator.hpp
References Acts::DirectNavigator::State::currentVolume.
template<typename propagator_state_t , typename stepper_t > void Acts::DirectNavigator::initialize (propagator_state_t & state, const stepper_t & stepper) const inline
Initialize call - start of propagation.
Template Parameters
propagator_state_t The state type of the propagator
stepper_t The type of stepper used for the propagation
Parameters
[in,out] state is the propagation state object
[in] stepper Stepper in use
Definition at line 199 of file DirectNavigator.hpp.
View newest version in sPHENIX GitHub at line 199 of file DirectNavigator.hpp
const Logger& Acts::DirectNavigator::logger () const inline private
Definition at line 300 of file DirectNavigator.hpp.
View newest version in sPHENIX GitHub at line 300 of file DirectNavigator.hpp
References m_logger.
State Acts::DirectNavigator::makeState (const Surface * startSurface, const Surface * targetSurface) const inline
Definition at line 117 of file DirectNavigator.hpp.
View newest version in sPHENIX GitHub at line 117 of file DirectNavigator.hpp
References Acts::DirectNavigator::State::startSurface, startSurface(), Acts::DirectNavigator::State::targetSurface, and targetSurface().
bool Acts::DirectNavigator::navigationBreak (const State & state) const inline
Definition at line 175 of file DirectNavigator.hpp.
View newest version in sPHENIX GitHub at line 175 of file DirectNavigator.hpp
References Acts::DirectNavigator::State::navigationBreak.
Referenced by navigationBreak().
void Acts::DirectNavigator::navigationBreak (State & state, bool navigationBreak) const inline
Definition at line 187 of file DirectNavigator.hpp.
View newest version in sPHENIX GitHub at line 187 of file DirectNavigator.hpp
References Acts::DirectNavigator::State::navigationBreak, and navigationBreak().
template<typename propagator_state_t , typename stepper_t > void Acts::DirectNavigator::postStep (propagator_state_t & state, const stepper_t & stepper) const inline
Navigator post step call.
Template Parameters
propagator_state_t is the type of Propagatgor state
stepper_t is the used type of the Stepper by the Propagator
Parameters
[in,out] state is the mutable propagator state object
[in] stepper Stepper in use
Definition at line 260 of file DirectNavigator.hpp.
View newest version in sPHENIX GitHub at line 260 of file DirectNavigator.hpp
References Acts::ACTS_VERBOSE(), distance(), Acts::if(), and m_logger.
template<typename propagator_state_t , typename stepper_t > void Acts::DirectNavigator::preStep (propagator_state_t & state, const stepper_t & stepper) const inline
Navigator pre step call.
Template Parameters
propagator_state_t is the type of Propagatgor state
stepper_t is the used type of the Stepper by the Propagator
Parameters
[in,out] state is the mutable propagator state object
[in] stepper Stepper in use
Definition at line 212 of file DirectNavigator.hpp.
View newest version in sPHENIX GitHub at line 212 of file DirectNavigator.hpp
References Acts::ACTS_VERBOSE(), distance(), and m_logger.
void Acts::DirectNavigator::resetState (State & state, const GeometryContext & , const Vector3 & , const Vector3 & , const Surface * ssurface, const Surface * tsurface) const inline
Reset state
Parameters
state is the state to reset
ssurface is the new starting surface
tsurface is the target surface
Definition at line 130 of file DirectNavigator.hpp.
View newest version in sPHENIX GitHub at line 130 of file DirectNavigator.hpp
References Acts::DirectNavigator::State::currentSurface, Acts::DirectNavigator::State::navSurfaceIter, Acts::DirectNavigator::State::navSurfaces, Acts::DirectNavigator::State::startSurface, and Acts::DirectNavigator::State::targetSurface.
const Surface* Acts::DirectNavigator::startSurface (const State & state) const inline
Definition at line 161 of file DirectNavigator.hpp.
View newest version in sPHENIX GitHub at line 161 of file DirectNavigator.hpp
References Acts::DirectNavigator::State::startSurface.
Referenced by makeState().
bool Acts::DirectNavigator::targetReached (const State & state) const inline
Definition at line 169 of file DirectNavigator.hpp.
View newest version in sPHENIX GitHub at line 169 of file DirectNavigator.hpp
References Acts::DirectNavigator::State::targetReached.
Referenced by targetReached().
void Acts::DirectNavigator::targetReached (State & state, bool targetReached) const inline
Definition at line 183 of file DirectNavigator.hpp.
View newest version in sPHENIX GitHub at line 183 of file DirectNavigator.hpp
References Acts::DirectNavigator::State::targetReached, and targetReached().
const Surface* Acts::DirectNavigator::targetSurface (const State & state) const inline
Definition at line 165 of file DirectNavigator.hpp.
View newest version in sPHENIX GitHub at line 165 of file DirectNavigator.hpp
References Acts::DirectNavigator::State::targetSurface.
Referenced by makeState().
Member Data Documentation
std::unique_ptr<const Logger> Acts::DirectNavigator::m_logger private
Definition at line 302 of file DirectNavigator.hpp.
View newest version in sPHENIX GitHub at line 302 of file DirectNavigator.hpp
Referenced by logger(), postStep(), and preStep().
The documentation for this class was generated from the following file:
acts/blob/sPHENIX/Core/include/Acts/Propagator/DirectNavigator.hpp