Analysis Software: PgPostCalBank Class Reference
PgPostCalBank Class Reference abstract
#include <coresoftware/blob/master/offline/database/pdbcal/pg/PgPostCalBank.h>
Public Member Functions
PgPostCalBank ()
virtual ~PgPostCalBank ()
void printHeader () const override
void printEntry (size_t) override=0
void print () override=0
size_t getLength () override=0
PdbCalChan & getEntry (size_t) override=0
void setLength (size_t val) override=0
PdbBankID getBankID () const override
PHTimeStamp getInsertTime () const override
PHTimeStamp getStartValTime () const override
PHTimeStamp getEndValTime () const override
std::string getDescription () const override
std::string getUserName () const override
virtual std::string getTableName () const
void setBankID (const PdbBankID &) override
void setInsertTime (const PHTimeStamp &) override
void setStartValTime (const PHTimeStamp &) override
void setEndValTime (const PHTimeStamp &) override
void setDescription (const std::string &) override
void setUserName (const std::string &) override
virtual void setTableName (const std::string &)
int isValid (const PHTimeStamp &) const override
ClassDefOverride (PgPostCalBank, 2)
Public Member Functions inherited from PdbCalBank
PdbCalBank ()
~PdbCalBank () override
PHObject * CloneMe () const override
Virtual copy constructor.
ClassDefOverride (PdbCalBank, 1)
Public Member Functions inherited from PHObject
PHObject ()
ctor
~PHObject () override
dtor
virtual PHObject * clone () const final
PHObject * Clone (const char *newname="") const final
void Copy (TObject &object) const final
virtual void identify (std::ostream &os=std::cout) const
virtual void Reset ()
Clear Event.
virtual int isValid () const
isValid returns non zero if object contains vailid data
virtual int Integrate () const
virtual int Integrate (PHObject *)
virtual void CopyFrom (const PHObject *obj)
Detailed Description
Definition at line 16 of file PgPostCalBank.h.
View newest version in sPHENIX GitHub at line 16 of file PgPostCalBank.h
Constructor & Destructor Documentation
PgPostCalBank::PgPostCalBank () inline
Definition at line 19 of file PgPostCalBank.h.
View newest version in sPHENIX GitHub at line 19 of file PgPostCalBank.h
virtual PgPostCalBank::~PgPostCalBank () inline virtual
Definition at line 20 of file PgPostCalBank.h.
View newest version in sPHENIX GitHub at line 20 of file PgPostCalBank.h
Member Function Documentation
PgPostCalBank::ClassDefOverride (PgPostCalBank , 2)
PdbBankID PgPostCalBank::getBankID () const inline override virtual
Implements PdbCalBank.
Definition at line 31 of file PgPostCalBank.h.
View newest version in sPHENIX GitHub at line 31 of file PgPostCalBank.h
Referenced by PgPostBankBackupStorage::set_obj_info().
std::string PgPostCalBank::getDescription () const inline override virtual
Implements PdbCalBank.
Definition at line 35 of file PgPostCalBank.h.
View newest version in sPHENIX GitHub at line 35 of file PgPostCalBank.h
Referenced by PgPostBankBackupStorage::set_obj_info().
PHTimeStamp PgPostCalBank::getEndValTime () const inline override virtual
Implements PdbCalBank.
Definition at line 34 of file PgPostCalBank.h.
View newest version in sPHENIX GitHub at line 34 of file PgPostCalBank.h
Referenced by PgPostBankBackupStorage::set_obj_info().
PdbCalChan& PgPostCalBank::getEntry (size_t) override pure virtual
Implements PdbCalBank.
Implemented in PgPostBankWrapper.
Referenced by PgPostBankBackupManager::dumpTable().
PHTimeStamp PgPostCalBank::getInsertTime () const inline override virtual
Implements PdbCalBank.
Definition at line 32 of file PgPostCalBank.h.
View newest version in sPHENIX GitHub at line 32 of file PgPostCalBank.h
Referenced by PgPostBankBackupStorage::set_obj_info().
size_t PgPostCalBank::getLength () override pure virtual
Implements PdbCalBank.
Implemented in PgPostBankWrapper.
Referenced by PgPostBankBackupManager::dumpTable().
PHTimeStamp PgPostCalBank::getStartValTime () const inline override virtual
Implements PdbCalBank.
Definition at line 33 of file PgPostCalBank.h.
View newest version in sPHENIX GitHub at line 33 of file PgPostCalBank.h
Referenced by PgPostBankBackupStorage::set_obj_info().
virtual std::string PgPostCalBank::getTableName () const inline virtual
Reimplemented in PgPostBankWrapper.
Definition at line 37 of file PgPostCalBank.h.
View newest version in sPHENIX GitHub at line 37 of file PgPostCalBank.h
Referenced by PgPostBankBackupStorage::set_obj_info().
std::string PgPostCalBank::getUserName () const inline override virtual
Implements PdbCalBank.
Definition at line 36 of file PgPostCalBank.h.
View newest version in sPHENIX GitHub at line 36 of file PgPostCalBank.h
Referenced by PgPostBankBackupStorage::set_obj_info().
int PgPostCalBank::isValid (const PHTimeStamp &) const inline override virtual
Implements PdbCalBank.
Definition at line 47 of file PgPostCalBank.h.
View newest version in sPHENIX GitHub at line 47 of file PgPostCalBank.h
void PgPostCalBank::print () override pure virtual
Implements PdbCalBank.
Implemented in PgPostBankWrapper.
void PgPostCalBank::printEntry (size_t) override pure virtual
Implements PdbCalBank.
Implemented in PgPostBankWrapper.
void PgPostCalBank::printHeader () const inline override virtual
Implements PdbCalBank.
Definition at line 22 of file PgPostCalBank.h.
View newest version in sPHENIX GitHub at line 22 of file PgPostCalBank.h
void PgPostCalBank::setBankID (const PdbBankID &) inline override virtual
Implements PdbCalBank.
Definition at line 39 of file PgPostCalBank.h.
View newest version in sPHENIX GitHub at line 39 of file PgPostCalBank.h
Referenced by PgPostBankBackupStorage::createBank().
void PgPostCalBank::setDescription (const std::string &) inline override virtual
Implements PdbCalBank.
Definition at line 43 of file PgPostCalBank.h.
View newest version in sPHENIX GitHub at line 43 of file PgPostCalBank.h
Referenced by PgPostBankBackupStorage::createBank().
void PgPostCalBank::setEndValTime (const PHTimeStamp &) inline override virtual
Implements PdbCalBank.
Definition at line 42 of file PgPostCalBank.h.
View newest version in sPHENIX GitHub at line 42 of file PgPostCalBank.h
Referenced by PgPostBankBackupStorage::createBank().
void PgPostCalBank::setInsertTime (const PHTimeStamp &) inline override virtual
Implements PdbCalBank.
Definition at line 40 of file PgPostCalBank.h.
View newest version in sPHENIX GitHub at line 40 of file PgPostCalBank.h
Referenced by PgPostBankBackupStorage::createBank().
void PgPostCalBank::setLength (size_t val) override pure virtual
Implements PdbCalBank.
Implemented in PgPostBankWrapper.
void PgPostCalBank::setStartValTime (const PHTimeStamp &) inline override virtual
Implements PdbCalBank.
Definition at line 41 of file PgPostCalBank.h.
View newest version in sPHENIX GitHub at line 41 of file PgPostCalBank.h
Referenced by PgPostBankBackupStorage::createBank().
virtual void PgPostCalBank::setTableName (const std::string &) inline virtual
Reimplemented in PgPostBankWrapper.
Definition at line 45 of file PgPostCalBank.h.
View newest version in sPHENIX GitHub at line 45 of file PgPostCalBank.h
Referenced by PgPostBankBackupStorage::createBank().
void PgPostCalBank::setUserName (const std::string &) inline override virtual
Implements PdbCalBank.
Definition at line 44 of file PgPostCalBank.h.
View newest version in sPHENIX GitHub at line 44 of file PgPostCalBank.h
Referenced by PgPostBankBackupStorage::createBank().
The documentation for this class was generated from the following file:
coresoftware/blob/master/offline/database/pdbcal/pg/PgPostCalBank.h