Analysis Software: macros/blob/master/common/G4_Tracking.C File Reference
G4_Tracking.C File Reference
#include <GlobalVariables.C>
#include <G4_ActsGeom.C>
#include <G4_Intt.C>
#include <G4_Micromegas.C>
#include <G4_Mvtx.C>
#include <G4_TPC.C>
#include <QA.C>
#include <g4eval/SvtxEvaluator.h>
#include <g4eval/SvtxTruthRecoTableEval.h>
#include <g4eval/TrackSeedTrackMapConverter.h>
#include <trackreco/MakeActsGeometry.h>
#include <trackreco/PHActsSiliconSeeding.h>
#include <trackreco/PHActsTrackProjection.h>
#include <trackreco/PHActsTrkFitter.h>
#include <trackreco/PHActsVertexPropagator.h>
#include <trackreco/PHCASeeding.h>
#include <trackreco/PHMicromegasTpcTrackMatching.h>
#include <trackreco/PHSiliconSeedMerger.h>
#include <trackreco/PHSiliconTpcTrackMatching.h>
#include <trackreco/PHSimpleKFProp.h>
#include <trackreco/PHSimpleVertexFinder.h>
#include <trackreco/PHTpcDeltaZCorrection.h>
#include <trackreco/PHTrackCleaner.h>
#include <trackreco/PHTrackSeeding.h>
#include <trackreco/PHTruthSiliconAssociation.h>
#include <trackreco/PHTruthTrackSeeding.h>
#include <trackreco/PHTruthVertexing.h>
#include <trackreco/SecondaryVertexFinder.h>
#include <tpc/TpcLoadDistortionCorrection.h>
#include <tpccalib/PHTpcResiduals.h>
#include <trackermillepedealignment/MakeMilleFiles.h>
#include <trackermillepedealignment/HelicalFitter.h>
#include <qa_modules/QAG4SimulationTracking.h>
#include <qa_modules/QAG4SimulationUpsilon.h>
#include <qa_modules/QAG4SimulationVertex.h>
#include <qa_modules/QAG4SimulationDistortions.h>
#include <fun4all/Fun4AllServer.h>
Macros
#define MACRO_G4TRACKING_C
Functions
void TrackingInit ()
void convert_seeds ()
void Tracking_Reco_TrackSeed ()
void vertexing ()
void Tracking_Reco_TrackFit ()
void Tracking_Reco_CommissioningTrackSeed ()
void alignment (std::string datafilename="mille_output_data_file", std::string steeringfilename="mille_steer")
void Tracking_Reco ()
void Filter_Conversion_Electrons (std::string ntuple_outfile)
void build_truthreco_tables ()
void Tracking_Eval (const std::string &outputfile)
void Tracking_QA ()
void Distortions_QA ()
Macro Definition Documentation
#define MACRO_G4TRACKING_C
Definition at line 2 of file G4_Tracking.C.
View newest version in sPHENIX GitHub at line 2 of file G4_Tracking.C
Function Documentation
void alignment (std::string datafilename = "mille_output_data_file", std::string steeringfilename = "mille_steer")
Definition at line 433 of file G4_Tracking.C.
View newest version in sPHENIX GitHub at line 433 of file G4_Tracking.C
References Fun4AllServer::instance(), Fun4AllServer::registerSubsystem(), Enable::TRACKING_VERBOSITY, verbosity, Enable::VERBOSITY, and Fun4AllBase::Verbosity().
Referenced by ActsExamples::AlignmentAlgorithm::makeAlignmentFunction(), runDetectorAlignment(), and Tracking_Reco().
void build_truthreco_tables ()
Definition at line 514 of file G4_Tracking.C.
View newest version in sPHENIX GitHub at line 514 of file G4_Tracking.C
References Fun4AllServer::instance(), Fun4AllServer::registerSubsystem(), Enable::TRACKING_VERBOSITY, verbosity, Enable::VERBOSITY, and Fun4AllBase::Verbosity().
Referenced by Fun4All_BHG(), Fun4All_RunNewTruthMatcher(), Tracking_Eval(), and Tracking_QA().
void convert_seeds ()
Definition at line 79 of file G4_Tracking.C.
View newest version in sPHENIX GitHub at line 79 of file G4_Tracking.C
References Fun4AllServer::instance(), Fun4AllServer::registerSubsystem(), TrackSeedTrackMapConverter::setTrackSeedName(), Enable::TRACKING_VERBOSITY, verbosity, Enable::VERBOSITY, and Fun4AllBase::Verbosity().
Referenced by Fun4All_TrkrClusteringSeeding(), Tracking_Reco(), Tracking_Reco_CommissioningTrackSeed(), and Tracking_Reco_TrackSeed().
void Distortions_QA ()
Definition at line 627 of file G4_Tracking.C.
View newest version in sPHENIX GitHub at line 627 of file G4_Tracking.C
References Fun4AllServer::instance(), Enable::QA_VERBOSITY, Fun4AllServer::registerSubsystem(), Enable::TRACKING_VERBOSITY, and verbosity.
void Filter_Conversion_Electrons (std::string ntuple_outfile)
Definition at line 495 of file G4_Tracking.C.
View newest version in sPHENIX GitHub at line 495 of file G4_Tracking.C
References Fun4AllServer::instance(), Fun4AllServer::registerSubsystem(), SecondaryVertexFinder::set_write_electrons_node(), SecondaryVertexFinder::set_write_ntuple(), SecondaryVertexFinder::setDecayParticleMass(), SecondaryVertexFinder::setOutfileName(), and Fun4AllBase::Verbosity().
Referenced by Fun4All_AnaTutorial_sPHENIX(), Fun4All_AnaTutorial_sPHENIX_Jets(), Fun4All_G4_sPHENIX(), Fun4All_G4_sPHENIX_ForTrackCutStudy_EmbedScanOff(), Fun4All_G4_sPHENIX_ForTrackCutStudy_EmbedScanOn(), Fun4All_G4_sPHENIX_ForTrackCutStudy_WithPileup_EmbedScanOff(), Fun4All_G4_sPHENIX_ForTrackCutStudy_WithPileup_EmbedScanOn(), and Fun4All_RunNewTruthMatcher().
void Tracking_Eval (const std::string & outputfile)
Definition at line 529 of file G4_Tracking.C.
View newest version in sPHENIX GitHub at line 529 of file G4_Tracking.C
References build_truthreco_tables(), SvtxEvaluator::do_cluster_eval(), SvtxEvaluator::do_eval_light(), SvtxEvaluator::do_g4hit_eval(), SvtxEvaluator::do_gpoint_eval(), SvtxEvaluator::do_hit_eval(), SvtxEvaluator::do_vtx_eval_light(), G4TRACKING::g4eval_use_initial_vertex, Fun4AllServer::instance(), G4TPC::n_gas_layer, G4INTT::n_intt_layer, G4MVTX::n_maps_layer, G4MICROMEGAS::n_micromegas_layer, TRACKING::pp_mode, Fun4AllServer::registerSubsystem(), SvtxEvaluator::scan_for_embedded(), SvtxEvaluator::scan_for_primaries(), SvtxEvaluator::set_use_initial_vertex(), Enable::TRACKING_VERBOSITY, verbosity, Enable::VERBOSITY, and Fun4AllBase::Verbosity().
Referenced by Fun4All_AnaTutorial_sPHENIX(), Fun4All_AnaTutorial_sPHENIX_Jets(), Fun4All_G4_EICDetector_AnaTutorial(), Fun4All_G4_sPHENIX(), Fun4All_G4_sPHENIX_ForTrackCutStudy(), Fun4All_G4_sPHENIX_ForTrackCutStudy_EmbedScanOn(), Fun4All_Pi0Gen_sPHENIX(), Fun4All_pi0tbt_SIMPLE_EMBED(), Fun4All_SinglePhotonGen_sPHENIX(), and Fun4All_SinglePi0Gen_sPHENIX().
void Tracking_QA ()
Definition at line 577 of file G4_Tracking.C.
View newest version in sPHENIX GitHub at line 577 of file G4_Tracking.C
References QAG4SimulationUpsilon::addEmbeddingID(), build_truthreco_tables(), Fun4AllServer::instance(), Enable::QA_VERBOSITY, Fun4AllServer::registerSubsystem(), QAG4SimulationVertex::setVertexMapName(), Enable::TRACKING_VERBOSITY, Input::UPSILON, Input::UPSILON_EmbedIds, verbosity, and Fun4AllBase::Verbosity().
Referenced by Fun4All_AnaTutorial_sPHENIX(), Fun4All_AnaTutorial_sPHENIX_Jets(), Fun4All_G4_sPHENIX(), Fun4All_G4_sPHENIX_ForTrackCutStudy(), Fun4All_G4_sPHENIX_ForTrackCutStudy_EmbedScanOff(), Fun4All_G4_sPHENIX_ForTrackCutStudy_EmbedScanOn(), Fun4All_G4_sPHENIX_ForTrackCutStudy_WithPileup_EmbedScanOff(), Fun4All_G4_sPHENIX_ForTrackCutStudy_WithPileup_EmbedScanOn(), Fun4All_Pi0Gen_sPHENIX(), Fun4All_pi0tbt_SIMPLE_EMBED(), Fun4All_RunNewTruthMatcher(), Fun4All_SinglePhotonGen_sPHENIX(), and Fun4All_SinglePi0Gen_sPHENIX().
void Tracking_Reco ()
Definition at line 455 of file G4_Tracking.C.
View newest version in sPHENIX GitHub at line 455 of file G4_Tracking.C
References alignment(), G4TRACKING::convert_seeds_to_svtxtracks, Tracking_Reco_CommissioningTrackSeed(), Tracking_Reco_TrackFit(), Tracking_Reco_TrackSeed(), G4TRACKING::use_alignment, and vertexing().
Referenced by Fun4All_AnaTutorial_sPHENIX(), Fun4All_AnaTutorial_sPHENIX_Jets(), Fun4All_BHG(), Fun4All_G4_Calo(), Fun4All_G4_EICDetector_AnaTutorial(), Fun4All_G4_sPHENIX(), Fun4All_G4_sPHENIX_ForTrackCutStudy(), Fun4All_G4_sPHENIX_ForTrackCutStudy_EmbedScanOff(), Fun4All_G4_sPHENIX_ForTrackCutStudy_EmbedScanOn(), Fun4All_G4_sPHENIX_ForTrackCutStudy_WithPileup_EmbedScanOff(), Fun4All_G4_sPHENIX_ForTrackCutStudy_WithPileup_EmbedScanOn(), Fun4All_Pi0Gen_sPHENIX(), Fun4All_pi0tbt_SIMPLE_EMBED(), Fun4All_RunCorrelatorJetTree(), Fun4All_RunCorrelatorQAModules(), Fun4All_RunNewTruthMatcher(), Fun4All_SinglePhotonGen_sPHENIX(), Fun4All_SinglePi0Gen_sPHENIX(), run_calo_fromMDC2Hits_towslope_Fun4All_G4_Calo(), rundst_spiNo(), and spiNo2().
void Tracking_Reco_CommissioningTrackSeed ()
Definition at line 341 of file G4_Tracking.C.
View newest version in sPHENIX GitHub at line 341 of file G4_Tracking.C
References convert_seeds(), G4TRACKING::convert_seeds_to_svtxtracks, Fun4AllServer::instance(), G4MAGNET::magfield, G4MAGNET::magfield_rescale, Enable::MICROMEGAS, TRACKING::pp_mode, physmon_track_finding_ttbar::seeder, Enable::TRACKING_VERBOSITY, verbosity, Enable::VERBOSITY, and Fun4AllBase::Verbosity().
Referenced by Tracking_Reco().
void Tracking_Reco_TrackFit ()
Definition at line 273 of file G4_Tracking.C.
View newest version in sPHENIX GitHub at line 273 of file G4_Tracking.C
References Fun4AllServer::instance(), TRACKING::pp_mode, G4TRACKING::SC_CALIBMODE, G4TRACKING::SC_ROOTOUTPUT_FILENAME, G4TRACKING::SC_USE_MICROMEGAS, PHTpcResiduals::setOutputfile(), Enable::TRACKING_VERBOSITY, G4TRACKING::use_full_truth_track_seeding, verbosity, Enable::VERBOSITY, Fun4AllBase::Verbosity(), and vertexing().
Referenced by Fun4All_G4_sPHENIX_jobC(), and Tracking_Reco().
void Tracking_Reco_TrackSeed ()
Definition at line 92 of file G4_Tracking.C.
View newest version in sPHENIX GitHub at line 92 of file G4_Tracking.C
References convert_seeds(), G4TRACKING::convert_seeds_to_svtxtracks, Fun4AllServer::instance(), G4MAGNET::magfield, G4MAGNET::magfield_rescale, Enable::MICROMEGAS, G4TPC::n_gas_layer, G4INTT::n_intt_layer, G4MVTX::n_maps_layer, TRACKING::pp_mode, G4TRACKING::SC_CALIBMODE, physmon_track_finding_ttbar::seeder, Enable::TRACKING_VERBOSITY, G4TRACKING::use_full_truth_track_seeding, G4TRACKING::use_truth_si_matching, G4TRACKING::use_truth_silicon_seeding, G4TRACKING::use_truth_tpc_seeding, verbosity, Enable::VERBOSITY, and Fun4AllBase::Verbosity().
Referenced by Fun4All_TrkrClusteringSeeding(), and Tracking_Reco().
void TrackingInit ()
Definition at line 56 of file G4_Tracking.C.
View newest version in sPHENIX GitHub at line 56 of file G4_Tracking.C
References ACTSGEOM::ActsGeomInit(), G4TPC::correction_filename, G4TPC::ENABLE_CORRECTIONS, Fun4AllServer::instance(), and TpcLoadDistortionCorrection::set_distortion_filename().
Referenced by Fun4All_AnaTutorial_sPHENIX(), Fun4All_AnaTutorial_sPHENIX_Jets(), Fun4All_BHG(), Fun4All_G4_Calo(), Fun4All_G4_sPHENIX(), Fun4All_G4_sPHENIX_ForTrackCutStudy(), Fun4All_G4_sPHENIX_ForTrackCutStudy_EmbedScanOff(), Fun4All_G4_sPHENIX_ForTrackCutStudy_EmbedScanOn(), Fun4All_G4_sPHENIX_ForTrackCutStudy_WithPileup_EmbedScanOff(), Fun4All_G4_sPHENIX_ForTrackCutStudy_WithPileup_EmbedScanOn(), Fun4All_G4_sPHENIX_jobC(), Fun4All_Pi0Gen_sPHENIX(), Fun4All_pi0tbt_SIMPLE_EMBED(), Fun4All_RunCorrelatorJetTree(), Fun4All_RunCorrelatorQAModules(), Fun4All_RunNewTruthMatcher(), Fun4All_SinglePhotonGen_sPHENIX(), Fun4All_SinglePi0Gen_sPHENIX(), G4Init(), run_calo_fromMDC2Hits_towslope_Fun4All_G4_Calo(), rundst_spiNo(), seedResiduals(), and spiNo2().
void vertexing ()
Definition at line 255 of file G4_Tracking.C.
View newest version in sPHENIX GitHub at line 255 of file G4_Tracking.C
References PHTruthVertexing::associate_tracks(), Fun4AllServer::instance(), Fun4AllServer::registerSubsystem(), Enable::TRACKING_VERBOSITY, G4TRACKING::use_truth_vertexing, verbosity, Enable::VERBOSITY, and Fun4AllBase::Verbosity().
Referenced by Tracking_Reco(), and Tracking_Reco_TrackFit().