Analysis Software: InttDeadMap Class Reference
InttDeadMap Class Reference
#include <coresoftware/blob/master/simulation/g4simulation/g4intt/InttDeadMap.h>
Public Types
typedef std::set
< PHG4CellDefs::keytype > Map
Public Member Functions
~InttDeadMap () override
int isValid () const override
isValid returns non zero if object contains vailid data
void identify (std::ostream &os=std::cout) const override
void addDeadChannelIntt (const int layer, const int ladder_phi, const int ladder_z, const int strip_z, const int strip_phi)
virtual void addDeadChannel (PHG4CellDefs::keytype)
virtual bool isDeadChannel (PHG4CellDefs::keytype) const
bool isDeadChannelIntt (const int layer, const int ladder_phi, const int ladder_z, const int strip_z, const int strip_phi) const
virtual const Map & getDeadChannels (void) const
return all towers
virtual Map & getDeadChannels (void)
virtual unsigned int size () const
Public Member Functions inherited from PHObject
PHObject ()
ctor
~PHObject () override
dtor
virtual PHObject * CloneMe () const
Virtual copy constructor.
virtual PHObject * clone () const final
PHObject * Clone (const char *newname="") const final
void Copy (TObject &object) const final
virtual void Reset ()
Clear Event.
virtual int Integrate () const
virtual int Integrate (PHObject *)
virtual void CopyFrom (const PHObject *obj)
Static Public Member Functions
static PHG4CellDefs::keytype getInttKey (int layer, int ladder_phi, int ladder_z, int strip_z, int strip_phi)
static int getWildCardID ()
Protected Member Functions
InttDeadMap ()
Static Private Attributes
static int s_wildCardID = -1
Detailed Description
Definition at line 11 of file InttDeadMap.h.
View newest version in sPHENIX GitHub at line 11 of file InttDeadMap.h
Member Typedef Documentation
typedef std::set<PHG4CellDefs::keytype> InttDeadMap::Map
Definition at line 14 of file InttDeadMap.h.
View newest version in sPHENIX GitHub at line 14 of file InttDeadMap.h
Constructor & Destructor Documentation
InttDeadMap::~InttDeadMap () inline override
Definition at line 16 of file InttDeadMap.h.
View newest version in sPHENIX GitHub at line 16 of file InttDeadMap.h
InttDeadMap::InttDeadMap () inline protected
Definition at line 44 of file InttDeadMap.h.
View newest version in sPHENIX GitHub at line 44 of file InttDeadMap.h
Member Function Documentation
virtual void InttDeadMap::addDeadChannel (PHG4CellDefs::keytype) inline virtual
Reimplemented in InttDeadMapv1.
Definition at line 24 of file InttDeadMap.h.
View newest version in sPHENIX GitHub at line 24 of file InttDeadMap.h
Referenced by addDeadChannelIntt().
void InttDeadMap::addDeadChannelIntt (const int layer, const int ladder_phi, const int ladder_z, const int strip_z, const int strip_phi)
Definition at line 25 of file InttDeadMap.cc.
View newest version in sPHENIX GitHub at line 25 of file InttDeadMap.cc
References addDeadChannel(), and getInttKey().
Referenced by PHG4InttDeadMapLoader::InitRun().
const InttDeadMap::Map & InttDeadMap::getDeadChannels (void) const virtual
return all towers
Reimplemented in InttDeadMapv1.
Definition at line 12 of file InttDeadMap.cc.
View newest version in sPHENIX GitHub at line 12 of file InttDeadMap.cc
Referenced by DumpInttDeadMap::process_Node().
InttDeadMap::Map & InttDeadMap::getDeadChannels (void) virtual
Reimplemented in InttDeadMapv1.
Definition at line 19 of file InttDeadMap.cc.
View newest version in sPHENIX GitHub at line 19 of file InttDeadMap.cc
PHG4CellDefs::keytype InttDeadMap::getInttKey (int layer, int ladder_phi, int ladder_z, int strip_z, int strip_phi) static
Definition at line 81 of file InttDeadMap.cc.
View newest version in sPHENIX GitHub at line 81 of file InttDeadMap.cc
References assert, layer, and s_wildCardID.
Referenced by addDeadChannelIntt(), and isDeadChannelIntt().
static int InttDeadMap::getWildCardID () inline static
Definition at line 41 of file InttDeadMap.h.
View newest version in sPHENIX GitHub at line 41 of file InttDeadMap.h
References s_wildCardID.
void InttDeadMap::identify (std::ostream & os = std::cout) const override virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from PHObject.
Reimplemented in InttDeadMapv1.
Definition at line 76 of file InttDeadMap.cc.
View newest version in sPHENIX GitHub at line 76 of file InttDeadMap.cc
Referenced by PHG4InttDigitizer::DigitizeLadderCells(), and PHG4InttDeadMapLoader::InitRun().
virtual bool InttDeadMap::isDeadChannel (PHG4CellDefs::keytype) const inline virtual
Reimplemented in InttDeadMapv1.
Definition at line 26 of file InttDeadMap.h.
View newest version in sPHENIX GitHub at line 26 of file InttDeadMap.h
Referenced by isDeadChannelIntt().
bool InttDeadMap::isDeadChannelIntt (const int layer, const int ladder_phi, const int ladder_z, const int strip_z, const int strip_phi) const
Definition at line 34 of file InttDeadMap.cc.
View newest version in sPHENIX GitHub at line 34 of file InttDeadMap.cc
References getInttKey(), isDeadChannel(), and s_wildCardID.
Referenced by PHG4InttDigitizer::DigitizeLadderCells().
int InttDeadMap::isValid () const override virtual
isValid returns non zero if object contains vailid data
Reimplemented from PHObject.
Reimplemented in InttDeadMapv1.
Definition at line 71 of file InttDeadMap.cc.
View newest version in sPHENIX GitHub at line 71 of file InttDeadMap.cc
References size().
virtual unsigned int InttDeadMap::size (void) const inline virtual
Reimplemented in InttDeadMapv1.
Definition at line 35 of file InttDeadMap.h.
View newest version in sPHENIX GitHub at line 35 of file InttDeadMap.h
Referenced by PHG4InttDeadMapLoader::InitRun(), isValid(), and DumpInttDeadMap::process_Node().
Member Data Documentation
int InttDeadMap::s_wildCardID = -1 static private
Definition at line 49 of file InttDeadMap.h.
View newest version in sPHENIX GitHub at line 49 of file InttDeadMap.h
Referenced by getInttKey(), getWildCardID(), and isDeadChannelIntt().
The documentation for this class was generated from the following files:
coresoftware/blob/master/simulation/g4simulation/g4intt/InttDeadMap.h
coresoftware/blob/master/simulation/g4simulation/g4intt/InttDeadMap.cc