Analysis Software: macros/blob/master/InttProduction/Fun4All_Intt_Combiner.C File Reference
Fun4All_Intt_Combiner.C File Reference
#include <fun4all/Fun4AllDstOutputManager.h>
#include <fun4all/Fun4AllInputManager.h>
#include <fun4all/Fun4AllOutputManager.h>
#include <fun4all/Fun4AllServer.h>
#include <fun4allraw/Fun4AllStreamingInputManager.h>
#include <fun4allraw/SingleInttPoolInput.h>
#include <phool/recoConsts.h>
#include <ffarawmodules/InttCheck.h>
Functions
void Fun4All_Intt_Combiner (int nEvents=0, const string &input_file00="intt0.list", const string &input_file01="intt1.list", const string &input_file02="intt2.list", const string &input_file03="intt3.list", const string &input_file04="intt4.list", const string &input_file05="intt5.list", const string &input_file06="intt6.list", const string &input_file07="intt7.list")
Variables
SingleInttPoolInput * sngl [9] {}
Function Documentation
void Fun4All_Intt_Combiner (int nEvents = 0, const string & input_file00 = "intt0.list", const string & input_file01 = "intt1.list", const string & input_file02 = "intt2.list", const string & input_file03 = "intt3.list", const string & input_file04 = "intt4.list", const string & input_file05 = "intt5.list", const string & input_file06 = "intt6.list", const string & input_file07 = "intt7.list")
Definition at line 18 of file Fun4All_Intt_Combiner.C.
View newest version in sPHENIX GitHub at line 18 of file Fun4All_Intt_Combiner.C
References InputFileHandler::AddListFile(), Fun4AllServer::End(), i, in, infile, recoConsts::instance(), Fun4AllServer::instance(), Fun4AllStreamingInputManager::INTT, nEvents, out, Fun4AllServer::registerInputManager(), Fun4AllServer::registerOutputManager(), Fun4AllStreamingInputManager::registerStreamingInput(), Fun4AllServer::run(), SingleInttPoolInput::SetBcoRange(), SingleInttPoolInput::SetNegativeBco(), sngl, to_string(), and Fun4AllBase::Verbosity().
Variable Documentation
SingleInttPoolInput* sngl[9] {}
Definition at line 16 of file Fun4All_Intt_Combiner.C.
View newest version in sPHENIX GitHub at line 16 of file Fun4All_Intt_Combiner.C
Referenced by CleanUp(), Fun4All_Intt_Combiner(), Fun4All_Mvtx_Combiner(), Fun4All_SingleMvtx(), Fun4All_Tpc_Combiner(), Print(), pygaga(), pyhiresd(), pyhisspa(), pyresd(), radgam_pol(), radgen(), radgen_event(), Run(), RunBclk(), strf(), and Verbosity().