Analysis Software: macros/blob/master/common/Trkr_Reco_Cosmics.C File Reference
Trkr_Reco_Cosmics.C File Reference
#include <G4_TrkrVariables.C>
#include <g4eval/SvtxTruthRecoTableEval.h>
#include <trackingdiagnostics/TrackSeedTrackMapConverter.h>
#include <trackreco/MakeActsGeometry.h>
#include <trackreco/PHActsTrkFitter.h>
#include <trackreco/PHActsVertexPropagator.h>
#include <trackreco/PHCosmicSeeder.h>
#include <trackreco/PHCosmicSiliconPropagator.h>
#include <trackreco/PHCosmicTrackMerger.h>
#include <trackreco/PHCosmicsTrkFitter.h>
#include <trackreco/PHMicromegasTpcTrackMatching.h>
#include <trackreco/PHSiliconHelicalPropagator.h>
#include <trackreco/PHSimpleVertexFinder.h>
#include <trackreco/PHTpcDeltaZCorrection.h>
#include <trackreco/PHTrackCleaner.h>
#include <trackreco/SecondaryVertexFinder.h>
#include <tpc/TpcLoadDistortionCorrection.h>
#include <tpccalib/PHTpcResiduals.h>
#include <trackermillepedealignment/HelicalFitter.h>
#include <trackermillepedealignment/MakeMilleFiles.h>
#include <fun4all/Fun4AllServer.h>
#include <string>
Macros
#define MACRO_TRKRRECO_COSMICS_C
Functions
void convert_seeds ()
void Tracking_Reco_TrackSeed ()
void vertexing ()
void Tracking_Reco_TrackFit ()
void alignment (std::string datafilename="mille_output_data_file", std::string steeringfilename="mille_steer")
void Tracking_Reco ()
Macro Definition Documentation
#define MACRO_TRKRRECO_COSMICS_C
Definition at line 2 of file Trkr_Reco_Cosmics.C.
View newest version in sPHENIX GitHub at line 2 of file Trkr_Reco_Cosmics.C
Function Documentation
void alignment (std::string datafilename = "mille_output_data_file", std::string steeringfilename = "mille_steer")
Definition at line 137 of file Trkr_Reco_Cosmics.C.
View newest version in sPHENIX GitHub at line 137 of file Trkr_Reco_Cosmics.C
References Fun4AllServer::instance(), Fun4AllServer::registerSubsystem(), Enable::TRACKING_VERBOSITY, verbosity, Enable::VERBOSITY, and Fun4AllBase::Verbosity().
void convert_seeds ()
Definition at line 39 of file Trkr_Reco_Cosmics.C.
View newest version in sPHENIX GitHub at line 39 of file Trkr_Reco_Cosmics.C
References TrackSeedTrackMapConverter::cosmics(), Fun4AllServer::instance(), G4MAGNET::magfield, Fun4AllServer::registerSubsystem(), TrackSeedTrackMapConverter::setFieldMap(), TrackSeedTrackMapConverter::setTrackSeedName(), Enable::TRACKING_VERBOSITY, verbosity, Enable::VERBOSITY, and Fun4AllBase::Verbosity().
void Tracking_Reco ()
Definition at line 158 of file Trkr_Reco_Cosmics.C.
View newest version in sPHENIX GitHub at line 158 of file Trkr_Reco_Cosmics.C
References alignment(), convert_seeds(), G4TRACKING::convert_seeds_to_svtxtracks, Tracking_Reco_TrackFit(), Tracking_Reco_TrackSeed(), G4TRACKING::use_alignment, and vertexing().
void Tracking_Reco_TrackFit ()
Definition at line 115 of file Trkr_Reco_Cosmics.C.
View newest version in sPHENIX GitHub at line 115 of file Trkr_Reco_Cosmics.C
References Fun4AllServer::instance(), G4MAGNET::magfield, Enable::TRACKING_VERBOSITY, verbosity, Enable::VERBOSITY, and Fun4AllBase::Verbosity().
void Tracking_Reco_TrackSeed ()
Definition at line 54 of file Trkr_Reco_Cosmics.C.
View newest version in sPHENIX GitHub at line 54 of file Trkr_Reco_Cosmics.C
References Fun4AllServer::instance(), PHCosmicSiliconPropagator::resetSvtxSeedContainer(), physmon_track_finding_ttbar::seeder, PHCosmicSiliconPropagator::set_dca_xy_cut(), PHCosmicSiliconPropagator::set_dca_z_cut(), Enable::TRACKING_VERBOSITY, verbosity, Enable::VERBOSITY, Fun4AllBase::Verbosity(), and PHCosmicSiliconPropagator::zero_field().
void vertexing ()
Definition at line 105 of file Trkr_Reco_Cosmics.C.
View newest version in sPHENIX GitHub at line 105 of file Trkr_Reco_Cosmics.C
References Fun4AllServer::instance(), Fun4AllServer::registerSubsystem(), Enable::TRACKING_VERBOSITY, verbosity, Enable::VERBOSITY, and Fun4AllBase::Verbosity().