Analysis Software: rcdaq/blob/master/rcdaq.h File Reference
rcdaq.h File Reference
#include <iostream>
#include <pthread.h>
Macros
#define MG_REQUEST_NAME 1
#define MG_REQUEST_SPEED 2
Functions
void sig_handler (int i)
void set_eventsizes ()
void * writebuffers (void *arg)
void * EventLoop (void *arg)
int Command (const int command)
char * obtain_pidfilename ()
int switch_buffer ()
int device_init ()
int device_endrun ()
int readout (const int etype)
int rearm (const int etype)
int rcdaq_init (const int, pthread_mutex_t &M)
int add_readoutdevice (daq_device *d)
int daq_begin (const int irun, std::ostream &os=std::cout)
int daq_begin_immediate (const int irun, std::ostream &os)
void * daq_begin_thread (void *arg)
int daq_end_immediate (std::ostream &os=std::cout)
int daq_end_interactive (std::ostream &os)
int daq_end (std::ostream &os=std::cout)
int daq_fake_trigger (const int n, const int waitinterval)
int daq_write_runnumberfile (const int run)
int daq_set_runnumberfile (const char *file, const int flag)
int daq_set_runnumberApp (const char *file, const int flag)
int daq_set_filerule (const char *rule)
int daq_setruntype (const char *type, std::ostream &os=std::cout)
int daq_getruntype (const int flag, std::ostream &os=std::cout)
int daq_define_runtype (const char *type, const char *rule)
int daq_list_runtypes (const int flag, std::ostream &os=std::cout)
std::string & daq_get_filerule ()
int daq_open (std::ostream &os=std::cout)
int daq_shutdown (const unsigned long servernumber, const unsigned long versionnumber, const int pid_fd, std::ostream &os=std::cout)
std::string & get_current_filename ()
int daq_close (std::ostream &os=std::cout)
int is_open ()
int daq_set_server (const char *hostname, const int port, std::ostream &os=std::cout)
int is_server_open ()
int daq_server_close (std::ostream &os=std::cout)
int get_serverflag ()
int daq_set_compression (const int flag, std::ostream &os=std::cout)
int daq_set_name (const char *name)
int daq_get_name (std::ostream &os=std::cout)
std::string daq_get_myname ()
int daq_set_mqtt_host (const char *host, const int port, std::ostream &os)
int daq_get_mqtt_host (std::ostream &os)
int daq_generate_json (const int flag)
double daq_get_mb_per_second ()
double daq_get_events_per_second ()
int daq_list_readlist (std::ostream &os=std::cout)
int daq_clear_readlist (std::ostream &os=std::cout)
int daq_status (const int flag, std::ostream &os=std::cout)
int daq_running ()
int daq_status_plugin (const int flag=0, std::ostream &os=std::cout)
int daq_setmaxevents (const int n, std::ostream &os)
int daq_setmaxvolume (const int n_mb, std::ostream &os)
int daq_setrolloverlimit (const int n_gb, std::ostream &os)
int daq_setmaxbuffersize (const int n_mb, std::ostream &os)
int daq_setadaptivebuffering (const int usecs, std::ostream &os)
int daq_set_eloghandler (const char *host, const int port, const char *logname)
int daq_load_plugin (const char *sharedlib, std::ostream &os)
int daq_wait_for_begin_done ()
int daq_wait_for_actual_end ()
int daq_webcontrol (const int port, std::ostream &os=std::cout)
int daq_getlastfilename (std::ostream &os=std::cout)
int daq_getlastevent_number (std::ostream &os=std::cout)
int get_runnumber ()
int get_oldrunnumber ()
int get_eventnumber ()
double get_runvolume ()
int get_runduration ()
int get_openflag ()
int daq_setEventFormat (const int f, std::ostream &os=std::cout)
int daq_getEventFormat ()
int daq_setRunControlMode (const int flag, std::ostream &os=std::cout)
int daq_getRunControlMode (std::ostream &os=std::cout)
int getRunNumberFromApp ()
Macro Definition Documentation
#define MG_REQUEST_NAME 1
Definition at line 133 of file rcdaq.h.
View newest version in sPHENIX GitHub at line 133 of file rcdaq.h
Referenced by daq_set_name(), and request_mg_update().
#define MG_REQUEST_SPEED 2
Definition at line 134 of file rcdaq.h.
View newest version in sPHENIX GitHub at line 134 of file rcdaq.h
Referenced by daq_begin(), daq_end(), and request_mg_update().
Function Documentation
int add_readoutdevice (daq_device * d)
Definition at line 1628 of file rcdaq.cc.
View newest version in sPHENIX GitHub at line 1628 of file rcdaq.cc
int Command (const int command)
int daq_begin (const int irun, std::ostream & os = std::cout)
Definition at line 1223 of file rcdaq.cc.
View newest version in sPHENIX GitHub at line 1223 of file rcdaq.cc
References BEGRUNEVENT, ElogHandler::BegrunLog(), Buffer_number, BytesInThisFile, BytesInThisRun, current_filesequence, CurrentFilename, DAQ_ENDREQUESTED, daq_open_flag, DAQ_RUNNING, daq_server_flag, daq_write_runnumberfile(), device_init(), ElogH, enable_trigger(), Event_number, Event_number_at_last_end, Event_number_at_last_open, Event_number_at_last_write, Eventsize, fillBuffer, get_current_filename(), daqBuffer::getMaxSize(), getRunNumberFromApp(), i, last_bufferwritetime, last_event_nr, last_speed_time, last_volume, last_volume_time, MAXEVENTID, md5_init(), md5state, MG_REQUEST_SPEED, MyHostName, open_file(), open_file_on_server(), outfile_fd, persistentErrorCondition, daqBuffer::prepare_next(), readout(), request_mg_update(), utils::run, run_volume, RunControlMode, RunnumberAppIsSet, set_eventsizes(), daqBuffer::setMaxSize(), StartTime, utils::status, str, TheFileRule, TheRun, TheRunnumberApp, ThreadEvt, Acts::Test::time, transportBuffer, and ambiguity_solver_full_chain::x.
Referenced by daq_begin_thread(), ev_handler(), main(), and r_action_1_svc().
int daq_begin_immediate (const int irun, std::ostream & os)
Definition at line 1186 of file rcdaq.cc.
View newest version in sPHENIX GitHub at line 1186 of file rcdaq.cc
References daq_begin_thread(), DAQ_BEGININPROGRESS, DAQ_RUNNING, MyHostName, utils::status, t, and TheRun.
Referenced by r_action_1_svc().
void* daq_begin_thread (void * arg)
Definition at line 1171 of file rcdaq.cc.
View newest version in sPHENIX GitHub at line 1171 of file rcdaq.cc
References daq_begin(), DAQ_BEGININPROGRESS, and utils::status.
Referenced by daq_begin_immediate().
int daq_clear_readlist (std::ostream & os = std::cout)
Definition at line 1962 of file rcdaq.cc.
View newest version in sPHENIX GitHub at line 1962 of file rcdaq.cc
References DAQ_RUNNING, DeviceList, and MyHostName.
Referenced by main(), and r_action_1_svc().
int daq_close (std::ostream & os = std::cout)
Definition at line 1913 of file rcdaq.cc.
View newest version in sPHENIX GitHub at line 1913 of file rcdaq.cc
References daq_open_flag, DAQ_RUNNING, MyHostName, and persistentErrorCondition.
Referenced by daq_shutdown(), ev_handler(), and r_action_1_svc().
int daq_define_runtype (const char * type, const char * rule)
Definition at line 1073 of file rcdaq.cc.
View newest version in sPHENIX GitHub at line 1073 of file rcdaq.cc
References RunTypes, and parse_cmake_options::type.
Referenced by r_action_1_svc().
int daq_end (std::ostream & os = std::cout)
Definition at line 1472 of file rcdaq.cc.
View newest version in sPHENIX GitHub at line 1472 of file rcdaq.cc
References Buffer_number, BytesInThisFile, BytesInThisRun, CurrentFilename, DAQ_ENDREQUESTED, daq_generate_json(), DAQ_RUNNING, daq_server_flag, device_endrun(), disable_trigger(), ElogH, ENDRUNEVENT, ElogHandler::EndrunLog(), Event_number, Event_number_at_last_end, Event_number_at_last_write, file_is_open, last_event_nr, last_speed_time, last_volume, last_volume_time, MG_REQUEST_SPEED, MyHostName, outfile_fd, PreviousFilename, readout(), request_mg_update(), run_volume, server_send_close_sequence(), server_send_endrun_sequence(), StartTime, switch_buffer(), TheRun, TheServerFD, Acts::Test::time, testSigmaEff::v, and WriteProtectSem.
Referenced by daq_end_thread(), ev_handler(), EventLoop(), and main().
int daq_end_immediate (std::ostream & os = std::cout)
Definition at line 1414 of file rcdaq.cc.
View newest version in sPHENIX GitHub at line 1414 of file rcdaq.cc
References daq_end_thread(), DAQ_ENDREQUESTED, DAQ_RUNNING, MyHostName, os, utils::status, t, TheRun, and ambiguity_solver_full_chain::x.
Referenced by r_action_1_svc().
int daq_end_interactive (std::ostream & os)
Definition at line 1462 of file rcdaq.cc.
View newest version in sPHENIX GitHub at line 1462 of file rcdaq.cc
References daq_end_thread(), os, and ambiguity_solver_full_chain::x.
Referenced by r_action_1_svc().
int daq_fake_trigger (const int n, const int waitinterval)
Definition at line 1550 of file rcdaq.cc.
View newest version in sPHENIX GitHub at line 1550 of file rcdaq.cc
References DAQ_READ, i, n, and Trigger_Todo.
Referenced by main(), and r_action_1_svc().
int daq_generate_json (const int flag)
Definition at line 2650 of file rcdaq.cc.
View newest version in sPHENIX GitHub at line 2650 of file rcdaq.cc
References current_filesequence, CurrentFilename, Event_number_at_last_open, Event_number_at_last_write, i, md5_finish(), md5state, out, shortHostName, TheRun, TheRunType, and Acts::Test::time.
Referenced by daq_end(), open_file(), and switch_buffer().
double daq_get_events_per_second ()
Definition at line 1159 of file rcdaq.cc.
View newest version in sPHENIX GitHub at line 1159 of file rcdaq.cc
References Event_number, last_event_nr, last_speed_time, and Acts::Test::time.
Referenced by trigger_updates().
std::string& daq_get_filerule ()
Definition at line 1132 of file rcdaq.cc.
View newest version in sPHENIX GitHub at line 1132 of file rcdaq.cc
References TheFileRule.
Referenced by daq_status().
double daq_get_mb_per_second ()
Definition at line 1147 of file rcdaq.cc.
View newest version in sPHENIX GitHub at line 1147 of file rcdaq.cc
References last_volume, last_volume_time, run_volume, and Acts::Test::time.
Referenced by trigger_updates().
int daq_get_mqtt_host (std::ostream & os)
Referenced by r_action_1_svc().
std::string daq_get_myname ()
Definition at line 1127 of file rcdaq.cc.
View newest version in sPHENIX GitHub at line 1127 of file rcdaq.cc
References MyName.
Referenced by initial_ws_update(), and trigger_updates().
int daq_get_name (std::ostream & os = std::cout)
Definition at line 1121 of file rcdaq.cc.
View newest version in sPHENIX GitHub at line 1121 of file rcdaq.cc
References MyName.
Referenced by r_action_1_svc().
int daq_getEventFormat ()
Definition at line 403 of file rcdaq.cc.
View newest version in sPHENIX GitHub at line 403 of file rcdaq.cc
References Buffer1, and daqBuffer::getEventFormat().
int daq_getlastevent_number (std::ostream & os = std::cout)
Definition at line 2420 of file rcdaq.cc.
View newest version in sPHENIX GitHub at line 2420 of file rcdaq.cc
References Event_number_at_last_end.
Referenced by r_action_1_svc().
int daq_getlastfilename (std::ostream & os = std::cout)
Definition at line 2413 of file rcdaq.cc.
View newest version in sPHENIX GitHub at line 2413 of file rcdaq.cc
References get_previous_filename().
Referenced by r_action_1_svc().
int daq_getRunControlMode (std::ostream & os = std::cout)
Definition at line 408 of file rcdaq.cc.
View newest version in sPHENIX GitHub at line 408 of file rcdaq.cc
References RunControlMode.
Referenced by r_action_1_svc().
int daq_getruntype (const int flag, std::ostream & os = std::cout)
Definition at line 1050 of file rcdaq.cc.
View newest version in sPHENIX GitHub at line 1050 of file rcdaq.cc
References RunTypes, and TheFileRule.
Referenced by r_action_1_svc().
int daq_list_readlist (std::ostream & os = std::cout)
Definition at line 1948 of file rcdaq.cc.
View newest version in sPHENIX GitHub at line 1948 of file rcdaq.cc
References DeviceList.
Referenced by main(), and r_action_1_svc().
int daq_list_runtypes (const int flag, std::ostream & os = std::cout)
Definition at line 1095 of file rcdaq.cc.
View newest version in sPHENIX GitHub at line 1095 of file rcdaq.cc
References RunTypes.
Referenced by daq_status_runtypes(), and r_action_1_svc().
int daq_load_plugin (const char * sharedlib, std::ostream & os)
Definition at line 81 of file rcdaq_server.cc.
View newest version in sPHENIX GitHub at line 81 of file rcdaq_server.cc
References testSigmaEff::v.
Referenced by r_action_1_svc().
int daq_open (std::ostream & os = std::cout)
Definition at line 1761 of file rcdaq.cc.
View newest version in sPHENIX GitHub at line 1761 of file rcdaq.cc
References daq_open_flag, DAQ_RUNNING, MyHostName, and persistentErrorCondition.
Referenced by ev_handler(), and r_action_1_svc().
int daq_running ()
Definition at line 2426 of file rcdaq.cc.
View newest version in sPHENIX GitHub at line 2426 of file rcdaq.cc
References DAQ_RUNNING.
Referenced by daq_setEventFormat(), get_loggingstring(), get_statusstring(), initial_ws_update(), mg_server(), r_create_device_1_svc(), send_ws_updates(), and trigger_updates().
int daq_server_close (std::ostream & os = std::cout)
Definition at line 1928 of file rcdaq.cc.
View newest version in sPHENIX GitHub at line 1928 of file rcdaq.cc
References DAQ_RUNNING, daq_server_flag, MyHostName, server_send_close_sequence(), and TheServerFD.
int daq_set_compression (const int flag, std::ostream & os = std::cout)
Definition at line 1782 of file rcdaq.cc.
View newest version in sPHENIX GitHub at line 1782 of file rcdaq.cc
References Buffer1, Buffer2, DAQ_RUNNING, MyHostName, and daqBuffer::setCompression().
Referenced by r_action_1_svc().
int daq_set_eloghandler (const char * host, const int port, const char * logname)
Definition at line 415 of file rcdaq.cc.
View newest version in sPHENIX GitHub at line 415 of file rcdaq.cc
References ElogH, and str.
Referenced by r_action_1_svc().
int daq_set_filerule (const char * rule)
Definition at line 969 of file rcdaq.cc.
View newest version in sPHENIX GitHub at line 969 of file rcdaq.cc
References TheFileRule.
Referenced by r_action_1_svc().
int daq_set_mqtt_host (const char * host, const int port, std::ostream & os)
Referenced by r_action_1_svc().
int daq_set_name (const char * name)
Definition at line 975 of file rcdaq.cc.
View newest version in sPHENIX GitHub at line 975 of file rcdaq.cc
References MG_REQUEST_NAME, MyName, perf_headwind::name, request_mg_update(), servernumber, and to_string().
Referenced by r_action_1_svc().
int daq_set_runnumberApp (const char * file, const int flag)
Definition at line 930 of file rcdaq.cc.
View newest version in sPHENIX GitHub at line 930 of file rcdaq.cc
References file, RunnumberAppIsSet, and TheRunnumberApp.
Referenced by r_action_1_svc().
int daq_set_runnumberfile (const char * file, const int flag)
Definition at line 887 of file rcdaq.cc.
View newest version in sPHENIX GitHub at line 887 of file rcdaq.cc
References fclose(), file, physmon_track_finding_ttbar::r, RunnumberfileIsSet, utils::status, TheRun, and TheRunnumberfile.
Referenced by r_action_1_svc().
int daq_set_server (const char * hostname, const int port, std::ostream & os = std::cout)
Definition at line 1805 of file rcdaq.cc.
View newest version in sPHENIX GitHub at line 1805 of file rcdaq.cc
References DAQ_RUNNING, daq_server_flag, daq_server_name, daq_server_port, and MyHostName.
Referenced by r_action_1_svc().
int daq_setadaptivebuffering (const int usecs, std::ostream & os)
Definition at line 374 of file rcdaq.cc.
View newest version in sPHENIX GitHub at line 374 of file rcdaq.cc
References adaptivebuffering.
Referenced by r_action_1_svc().
int daq_setEventFormat (const int f, std::ostream & os = std::cout)
Definition at line 382 of file rcdaq.cc.
View newest version in sPHENIX GitHub at line 382 of file rcdaq.cc
References Buffer1, Buffer2, daq_running(), DeviceList, daqBuffer::setEventFormat(), and utils::status.
Referenced by r_action_1_svc().
int daq_setmaxbuffersize (const int n_mb, std::ostream & os)
Definition at line 361 of file rcdaq.cc.
View newest version in sPHENIX GitHub at line 361 of file rcdaq.cc
References Buffer1, Buffer2, DAQ_RUNNING, and daqBuffer::setMaxSize().
Referenced by r_action_1_svc().
int daq_setmaxevents (const int n, std::ostream & os)
Definition at line 321 of file rcdaq.cc.
View newest version in sPHENIX GitHub at line 321 of file rcdaq.cc
References max_events, and n.
Referenced by r_action_1_svc().
int daq_setmaxvolume (const int n_mb, std::ostream & os)
Definition at line 329 of file rcdaq.cc.
View newest version in sPHENIX GitHub at line 329 of file rcdaq.cc
References max_volume, and ambiguity_solver_full_chain::x.
Referenced by r_action_1_svc().
int daq_setrolloverlimit (const int n_gb, std::ostream & os)
Definition at line 349 of file rcdaq.cc.
View newest version in sPHENIX GitHub at line 349 of file rcdaq.cc
References DAQ_RUNNING, and RolloverLimit.
Referenced by r_action_1_svc().
int daq_setRunControlMode (const int flag, std::ostream & os = std::cout)
Definition at line 337 of file rcdaq.cc.
View newest version in sPHENIX GitHub at line 337 of file rcdaq.cc
References DAQ_RUNNING, and RunControlMode.
Referenced by r_action_1_svc().
int daq_setruntype (const char * type, std::ostream & os = std::cout)
Definition at line 1033 of file rcdaq.cc.
View newest version in sPHENIX GitHub at line 1033 of file rcdaq.cc
References RunTypes, TheFileRule, TheRunType, and parse_cmake_options::type.
Referenced by r_action_1_svc().
int daq_shutdown (const unsigned long servernumber, const unsigned long versionnumber, const int pid_fd, std::ostream & os = std::cout)
Definition at line 1866 of file rcdaq.cc.
View newest version in sPHENIX GitHub at line 1866 of file rcdaq.cc
References daq_close(), DAQ_RUNNING, daq_server_flag, MyHostName, pid_fd, servernumber, shutdown_thread(), utils::status, and t.
Referenced by r_shutdown_1_svc().
int daq_status (const int flag, std::ostream & os = std::cout)
Definition at line 2138 of file rcdaq.cc.
View newest version in sPHENIX GitHub at line 2138 of file rcdaq.cc
References adaptivebuffering, Buffer1, daq_get_filerule(), daq_getEventFormat(), daq_open_flag, DAQ_RUNNING, daq_server_flag, daq_server_name, daq_server_port, daq_status_plugin(), daq_status_runtypes(), ElogH, Event_number, get_current_filename(), daqBuffer::getCompression(), ElogHandler::getHost(), ElogHandler::getLogbookName(), daqBuffer::getMaxSize(), ElogHandler::getPort(), max_events, max_volume, MyHostName, MyName, RolloverLimit, run_volume, RunControlMode, StartTime, ThePort, TheRun, Acts::Test::time, and TriggerH.
Referenced by r_action_1_svc().
int daq_status_plugin (const int flag = 0, std::ostream & os = std::cout)
Definition at line 114 of file rcdaq_server.cc.
View newest version in sPHENIX GitHub at line 114 of file rcdaq_server.cc
References Eventiterator::identify(), it, and pluginlist.
Referenced by daq_status().
int daq_wait_for_actual_end ()
Definition at line 1451 of file rcdaq.cc.
View newest version in sPHENIX GitHub at line 1451 of file rcdaq.cc
References DAQ_ENDREQUESTED.
Referenced by r_action_1_svc().
int daq_wait_for_begin_done ()
Definition at line 1444 of file rcdaq.cc.
View newest version in sPHENIX GitHub at line 1444 of file rcdaq.cc
References DAQ_BEGININPROGRESS.
Referenced by r_action_1_svc().
int daq_webcontrol (const int port, std::ostream & os = std::cout)
Definition at line 2375 of file rcdaq.cc.
View newest version in sPHENIX GitHub at line 2375 of file rcdaq.cc
References mg_end(), mg_server(), MyHostName, servernumber, utils::status, ThePort, and ThreadWeb.
Referenced by r_action_1_svc(), and rcdaq_init().
int daq_write_runnumberfile (const int run)
Definition at line 914 of file rcdaq.cc.
View newest version in sPHENIX GitHub at line 914 of file rcdaq.cc
References fclose(), fprintf(), RunControlMode, RunnumberfileIsSet, and TheRunnumberfile.
Referenced by daq_begin().
int device_endrun ()
Definition at line 1651 of file rcdaq.cc.
View newest version in sPHENIX GitHub at line 1651 of file rcdaq.cc
References DeviceList.
Referenced by daq_end().
int device_init ()
Definition at line 1636 of file rcdaq.cc.
View newest version in sPHENIX GitHub at line 1636 of file rcdaq.cc
References DeviceList.
Referenced by daq_begin().
void* EventLoop (void * arg)
Definition at line 84 of file eventServer.cc.
View newest version in sPHENIX GitHub at line 84 of file eventServer.cc
References coutfl, CurrentEventType, daq_end(), DAQ_RUNNING, DATAEVENT, depth, Acts::UnitConstants::e, EventMap, Event::getEvtSequence(), Eventiterator::getNextEvent(), Event::getRunNumber(), go_on, Eventiterator::identify(), Event::identify(), identify, it, MapSem, old_runnumber, readout(), rearm(), reset_deadtime(), sleeptime, TriggerControl, TriggerH, verbose, and TriggerHandler::wait_for_trigger().
Referenced by enable_trigger(), and main().
std::string& get_current_filename ()
Definition at line 1137 of file rcdaq.cc.
View newest version in sPHENIX GitHub at line 1137 of file rcdaq.cc
References CurrentFilename.
Referenced by daq_begin(), daq_status(), get_loggingstring(), and initial_ws_update().
int get_eventnumber ()
Definition at line 2111 of file rcdaq.cc.
View newest version in sPHENIX GitHub at line 2111 of file rcdaq.cc
References DAQ_RUNNING, and Event_number.
Referenced by initial_ws_update(), mg_server(), send_updates(), and send_ws_updates().
int get_oldrunnumber ()
Definition at line 2106 of file rcdaq.cc.
View newest version in sPHENIX GitHub at line 2106 of file rcdaq.cc
References TheRun.
Referenced by get_statusstring().
int get_openflag ()
Definition at line 2128 of file rcdaq.cc.
View newest version in sPHENIX GitHub at line 2128 of file rcdaq.cc
References daq_open_flag.
Referenced by get_loggingstring(), initial_ws_update(), mg_server(), and trigger_updates().
int get_runduration ()
Definition at line 2122 of file rcdaq.cc.
View newest version in sPHENIX GitHub at line 2122 of file rcdaq.cc
References DAQ_RUNNING, StartTime, and Acts::Test::time.
Referenced by get_statusstring(), initial_ws_update(), and mg_server().
int get_runnumber ()
Definition at line 2100 of file rcdaq.cc.
View newest version in sPHENIX GitHub at line 2100 of file rcdaq.cc
References DAQ_RUNNING, and TheRun.
Referenced by initial_ws_update(), mg_server(), and trigger_updates().
double get_runvolume ()
Definition at line 2116 of file rcdaq.cc.
View newest version in sPHENIX GitHub at line 2116 of file rcdaq.cc
References DAQ_RUNNING, run_volume, and testSigmaEff::v.
Referenced by initial_ws_update(), mg_server(), send_updates(), and send_ws_updates().
int get_serverflag ()
Definition at line 2132 of file rcdaq.cc.
View newest version in sPHENIX GitHub at line 2132 of file rcdaq.cc
References daq_server_flag.
Referenced by get_loggingstring(), initial_ws_update(), mg_server(), and trigger_updates().
int getRunNumberFromApp ()
Definition at line 944 of file rcdaq.cc.
View newest version in sPHENIX GitHub at line 944 of file rcdaq.cc
References in, pclose(), utils::run, RunnumberAppIsSet, physmon_simulation::s, and TheRunnumberApp.
Referenced by daq_begin().
int is_open ()
Definition at line 1903 of file rcdaq.cc.
View newest version in sPHENIX GitHub at line 1903 of file rcdaq.cc
References daq_open_flag.
Referenced by gzstreambuf::close(), and gzstreambuf::open().
int is_server_open ()
Definition at line 1908 of file rcdaq.cc.
View newest version in sPHENIX GitHub at line 1908 of file rcdaq.cc
References daq_server_flag.
char* obtain_pidfilename ()
Definition at line 249 of file rcdaq.cc.
View newest version in sPHENIX GitHub at line 249 of file rcdaq.cc
References pidfilename.
Referenced by main(), and sig_handler().
int rcdaq_init (const int , pthread_mutex_t & M)
Definition at line 1985 of file rcdaq.cc.
View newest version in sPHENIX GitHub at line 1985 of file rcdaq.cc
References Buffer1, Buffer2, daq_webcontrol(), DAQPRDFFORMAT, FdManagementSem, fillBuffer, M_cout, md5state, MonitoringRequestSem, monitorRequestwatcher_thread(), MyHostName, MyName, outfile_fd, sendMonitorData(), SendProtectSem, SendSem, servernumber, daqBuffer::setEventFormat(), daqBuffer::setMD5State(), shortHostName, utils::status, ThePort, ThreadEvt, ThreadId, ThreadMon, to_string(), transportBuffer, writebuffers(), WriteProtectSem, and WriteSem.
Referenced by main().
int readout (const int etype)
Definition at line 1667 of file rcdaq.cc.
View newest version in sPHENIX GitHub at line 1667 of file rcdaq.cc
References adaptivebuffering, daqBuffer::addSubevent(), DAQ_RUNNING, DATAEVENT, DeviceList, Event_number, Event_number_at_last_end, Eventsize, EVTHEADERLENGTH, fillBuffer, last_bufferwritetime, max_events, max_volume, MAXEVENTID, daqBuffer::nextEvent(), run_volume, utils::status, switch_buffer(), and Acts::Test::time.
Referenced by daq_begin(), daq_end(), and EventLoop().
int rearm (const int etype)
Definition at line 1724 of file rcdaq.cc.
View newest version in sPHENIX GitHub at line 1724 of file rcdaq.cc
References DeviceList, and MAXEVENTID.
Referenced by EventLoop().
void set_eventsizes ()
Definition at line 1739 of file rcdaq.cc.
View newest version in sPHENIX GitHub at line 1739 of file rcdaq.cc
References DeviceList, Eventsize, EVTHEADERLENGTH, i, MAXEVENTID, and size.
Referenced by daq_begin().
void sig_handler (int i)
Definition at line 269 of file rcdaq.cc.
View newest version in sPHENIX GitHub at line 269 of file rcdaq.cc
References M_cout, obtain_pidfilename(), pid_fd, pidfilename, TriggerControl, and verbose.
int switch_buffer ()
Definition at line 810 of file rcdaq.cc.
View newest version in sPHENIX GitHub at line 810 of file rcdaq.cc
References daqBuffer::addEoB(), Buffer_number, BytesInThisFile, current_filesequence, CurrentFilename, daq_generate_json(), daq_open_flag, daq_server_flag, Event_number, Event_number_at_last_open, Event_number_at_last_write, file_is_open, fillBuffer, daqBuffer::getLength(), MyHostName, open_file(), outfile_fd, daqBuffer::prepare_next(), RolloverLimit, SendProtectSem, SendSem, server_send_rollover_sequence(), utils::status, TheFileRule, TheRun, TheServerFD, transportBuffer, WriteProtectSem, and WriteSem.
Referenced by daq_end(), and readout().
void* writebuffers (void * arg)
Definition at line 777 of file rcdaq.cc.
View newest version in sPHENIX GitHub at line 777 of file rcdaq.cc
References BytesInThisFile, BytesInThisRun, daq_open_flag, daq_server_flag, end_thread, last_bufferwritetime, NumberWritten, outfile_fd, daqBuffer::sendout(), TheServerFD, Acts::Test::time, transportBuffer, daqBuffer::writeout(), WriteProtectSem, and WriteSem.
Referenced by handle_this_child(), and rcdaq_init().