Analysis Software: analysis/blob/master/JS-Jet/FastJetMedianBkg/src_JetMedianTree/macro/plot/CalcDecile_RhoFluct.cc File Reference
CalcDecile_RhoFluct.cc File Reference
Functions
root l hadd_RhoFluct root
<< EOF TH1D *hparamt=new TH1D("hparamt",";impactparam;N_{events}",
10000, 0., 22);TH1D *gross=new
TH1D("gross",";impact param
[fm];N_{events}",
100, 0., 22);double x[11];double
*q=new double[11];for(int i=0;i
< 11;++i){x[i]=.1 *i;}T-> Draw ("impactparam>>hparamt")
hparamt GetQuantiles (11, q, x)
for (int i=0;i< 11;++i)
T Draw ("impactparam>>gross")
hparamt Draw ("PE")
keep Write ()
fout Close ()
Variables
TCanvas * c = new TCanvas("c","c")
TFile * fout = new TFile("CalcDecile_RhoFluct.root","recreate")
TH1D * keep = (TH1D*) gross->Clone("h_impactparam")
TH1D * bounds = new TH1D("bound",";[fm];", 10, q)
Function Documentation
fout Close ()
Referenced by CalculateSigmaDca(), CheckDeltaPtWithBoundaryMasks(), ClassImpQ(), SDeltaPtCutStudy::CloseFiles(), STrackMatcherComparator::CloseInput(), SColdQcdCorrelatorAnalysis::SBaseQAPlugin< SCheckTrackPairsConfig >::CloseOutput(), STrackMatcherComparator::CloseOutput(), SColdQcdCorrelatorAnalysis::SEnergyCorrelator::CloseOutputFile(), CompareOldVsNewPlots(), STrackCutStudy::ConstructPlots(), DoPercentDifference(), mbdAnalysis::End(), ElectronID::End(), hijbkg_upc::End(), isoCluster::End(), pi0ClusterAna::End(), quickHIJING::End(), singlePhotonClusterAna::End(), caloTreeGen::End(), pythiaEMCalAna::End(), hcal_towerid::End(), STrackCutStudy::End(), SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::End(), tileHelper::evLoop(), towerid::FillHistograms(), Jet_reso_Iso(), MakeNewMatcherPlots(), MakeNewMatcherTuplePlots(), MakeOldEvaluatorPlots(), SDeltaPtCutStudy::MakePlots(), MakePrettyPlot(), MakeRatioComparisonPlot(), STrackMatcherComparator::MakeRatiosAndPlots(), numericInverse(), QuickDeltaPtExtractor(), QuickTreePlotter(), QuickTuplePlotter(), QuickWeirdTuplePlotter(), hLabHelper::renameAndCloseRF(), SColdQcdCorrelatorAnalysis::SLambdaJetHunter::SaveAndCloseOutput(), simulateTimestamps(), Jetscape::JetScapeWriterFinalStateStream< T >::~JetScapeWriterFinalStateStream(), Jetscape::JetScapeWriterStream< T >::~JetScapeWriterStream(), and PHTFileServer::SafeTFile::~SafeTFile().
root l hadd_RhoFluct root<<EOF TH1D* hparamt = new TH1D("hparamt", ";impactparam;N_{events}", 10000, 0.,22); TH1D* gross = new TH1D("gross", ";impact param [fm];N_{events}", 100, 0.,22); double x[11]; double* q = new double[11]; for (int i=0;i<11;++i) { x[i] = .1*i; } T-> Draw ("impactparam>>hparamt")
T Draw ("impactparam>>gross")
hparamt Draw ("PE")
for ()
Definition at line 13 of file CalcDecile_RhoFluct.cc.
View newest version in sPHENIX GitHub at line 13 of file CalcDecile_RhoFluct.cc
References i, and ambiguity_solver_full_chain::x.
hparamt GetQuantiles (11 , q , x)
bounds Write ()
Referenced by calccorr(), CalculateSigmaDca(), CheckDeltaPtWithBoundaryMasks(), CompareOldVsNewPlots(), STrackCutStudy::ConstructPlots(), DoPercentDifference(), LEDTowerBuilder::End(), mbdAnalysis::End(), ElectronID::End(), JetUnderlyingEvent::End(), jetHistogrammer::End(), isoCluster::End(), hijbkg_upc::End(), pi0ClusterAna::End(), quickHIJING::End(), singlePhotonClusterAna::End(), caloTreeGen::End(), pythiaEMCalAna::End(), hcal_towerid::End(), pi0Efficiency::End(), cemcReco::End(), hcalHelper::evLoop(), tileHelper::evLoop(), Jet_reso_Iso(), MakeNewMatcherPlots(), MakeNewMatcherTuplePlots(), MakeOldEvaluatorPlots(), SDeltaPtCutStudy::MakePlots(), MakePrettyPlot(), MakeRatioComparisonPlot(), STrackMatcherComparator::MakeRatiosAndPlots(), numericInverse(), QuickDeltaPtExtractor(), QuickTreePlotter(), QuickTuplePlotter(), QuickWeirdTuplePlotter(), SColdQcdCorrelatorAnalysis::SLambdaJetHunter::SaveAndCloseOutput(), STrackMatcherComparator::SaveHistograms(), STrackCutStudy::SaveHists(), SColdQcdCorrelatorAnalysis::SCheckTrackPairs::SaveOutput(), SDeltaPtCutStudy::SaveOutput(), SColdQcdCorrelatorAnalysis::SEnergyCorrelator::SaveOutput(), SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::SaveOutput(), simulateTimestamps(), Jetscape::JetScapeWriterStream< T >::Write(), towerid::WriteCDBTree(), Jetscape::JetScapeWriterStream< T >::WriteHeaderToFile(), and PHTFileServer::SafeTFile::~SafeTFile().
Variable Documentation
TH1D* bounds = new TH1D("bound",";[fm];", 10, q)
Definition at line 23 of file CalcDecile_RhoFluct.cc.
View newest version in sPHENIX GitHub at line 23 of file CalcDecile_RhoFluct.cc
Referenced by Acts::Python::addDetector(), Acts::Python::addGeometry(), Acts::ConeSurface::alignmentToPathDerivative(), Acts::detail::angleDescriptionSwitch(), Acts::ConeSurface::binningPosition(), Acts::CylinderSurface::binningPosition(), Acts::Test::BOOST_AUTO_TEST_CASE(), BOOST_AUTO_TEST_CASE(), Acts::Test::BOOST_FIXTURE_TEST_CASE(), ActsExamples::MockupSectorBuilder::buildSector(), Acts::CuboidVolumeBuilder::buildVolume(), CompBuilder::construct(), CylindricalVolumeBuilder< surface_type, surface_bounds_type >::construct(), Acts::Experimental::DetectorVolumeBuilder::construct(), InternalVolumeBuilder< bounds_type >::construct(), Acts::EventDataView3DTest::createDetector(), Acts::TGeoSurfaceConverter::cylinderComponents(), Acts::TGeoSurfaceConverter::discComponents(), Acts::Test::draw_surfaces(), Acts::Test::SurfaceArrayFixture::draw_surfaces(), Acts::CylinderVolumeHelper::estimateAndCheckDimension(), Acts::DetectorVolumeJsonConverter::fromJson(), Acts::Test::SurfaceArrayFixture::fullPhiTestSurfacesBRL(), Acts::Test::SurfaceArrayCreatorFixture::fullPhiTestSurfacesBRL(), Acts::Test::LayerCreatorFixture::fullPhiTestSurfacesBRL(), Acts::Test::SurfaceArrayFixture::fullPhiTestSurfacesEC(), Acts::Test::SurfaceArrayCreatorFixture::fullPhiTestSurfacesEC(), Acts::Test::LayerCreatorFixture::fullPhiTestSurfacesEC(), Acts::ConeSurface::globalToLocal(), Acts::CylinderSurface::globalToLocal(), Acts::Surface::insideBounds(), Acts::CylinderSurface::intersect(), Acts::ConeSurface::intersectionSolver(), Acts::CylinderSurface::intersectionSolver(), Acts::Surface::isOnSurface(), Acts::ConeSurface::localCartesianToBoundLocalDerivative(), Acts::CylinderSurface::localCartesianToBoundLocalDerivative(), Acts::ConeSurface::localToGlobal(), Acts::CylinderSurface::localToGlobal(), Acts::Test::SurfaceArrayCreatorFixture::makeBarrelStagger(), Acts::Test::LayerCreatorFixture::makeBarrelStagger(), Acts::Test::makeToyDetector(), Acts::ConeSurface::normal(), Acts::Surface::operator==(), Acts::ConeSurface::pathCorrection(), Acts::TGeoSurfaceConverter::planeComponents(), Acts::PlaneSurface::polyhedronRepresentation(), Acts::ConeSurface::polyhedronRepresentation(), Acts::CylinderSurface::polyhedronRepresentation(), printHits(), ActsExamples::DD4hep::DD4hepDetectorHelper::rectangleDigiModule(), det::utils::rectangleDigiModuleXZ(), PHG4CylinderCellGeom_Spacalv1::set_etabounds(), PHG4CylinderCellGeom_Spacalv1::set_zbounds(), ActsExamples::TGeoITkModuleSplitter::splitBarrelModule(), ActsExamples::TGeoITkModuleSplitter::splitDiscModule(), Acts::Geant4PhysicalVolumeConverter::surface(), Acts::Surface::toStream(), ActsExamples::DD4hep::DD4hepDetectorHelper::trapezoidalDigiModule(), and det::utils::trapezoidalDigiModuleXZ().
TCanvas* c = new TCanvas("c","c")
Definition at line 18 of file CalcDecile_RhoFluct.cc.
View newest version in sPHENIX GitHub at line 18 of file CalcDecile_RhoFluct.cc
Referenced by aiz(), ar3jet(), biz(), dqn32(), ffdeu(), ffhe3(), i1mcry(), ludecy(), nthick(), pycbal(), pydecy(), pyfint(), pygrvv(), pygrvw(), pyhirand(), pyhixtot(), pymirm(), pyresd(), pyrnm3(), pyrnmq(), pytbdy(), pyuedc(), pyxxz6(), r1998(), and vacpol().
TFile* fout = new TFile("CalcDecile_RhoFluct.root","recreate")
Definition at line 21 of file CalcDecile_RhoFluct.cc.
View newest version in sPHENIX GitHub at line 21 of file CalcDecile_RhoFluct.cc
Referenced by Prototype2_DSTReader::Begin(), calculate_g1_projection_per_bin(), ccbb(), Cone_Plots(), crossterms(), DataAna(), DataAna2(), Draw_BDiJetImbalance(), draw_G4_bjet_truth_tagging(), draw_G4_dibjet_truth_tagging(), EdepPercentE(), EdepPercentIH(), EdepPercentOH(), EdepPercentSmall(), eic_sphenix_sidis_countbins(), SecondaryVertexFinder::End(), fakee_invmass(), fasthadv4(), FillEnergy(), Jetscape::TrentoInitial::GenCenTab(), get_alignment(), hera_dis_countbins(), hera_dis_fillbins(), Hijing(), Interlopation0Degree(), InterlopationV4(), InterlopationV4reverse(), JetReso(), ActsExamples::SeedingFTFAlgorithm::LayerNumbering(), look_purity(), Sub1rhoA::Loop(), RhoFluct::Loop(), main(), MakeFile(), makehist(), MatchJets(), Neutrals(), plot_ntp_g4hit(), TpcClusterBuilder::print_file(), OnlMonServer::PrintFile(), Prototype2_DSTReader::Process(), project_quarkonium_mass(), ProjectionReverse(), ProjectionReverse2(), purity(), ReadHis(), ReadHis2(), ReadHis3(), hcal::Save(), clvisc::BulkInfo::save(), ShSizeHist(), ShSizePrep(), Prototype2_DSTReader::Terminate(), ThreeGraphs(), Acts::Svg::toFile(), OnlMonServer::WriteLogFile(), and zdc_calib().
TH1D* keep = (TH1D*) gross->Clone("h_impactparam")
Definition at line 22 of file CalcDecile_RhoFluct.cc.
View newest version in sPHENIX GitHub at line 22 of file CalcDecile_RhoFluct.cc