Analysis Software: gzstreambase Class Reference
gzstreambase Class Reference
#include <JETSCAPE/blob/main/external_packages/gzstream.h>
Public Member Functions
gzstreambase ()
gzstreambase (const char *name, int open_mode)
~gzstreambase ()
void open (const char *name, int open_mode)
void close ()
gzstreambuf * rdbuf ()
Protected Attributes
gzstreambuf buf
Detailed Description
Definition at line 74 of file gzstream.h.
View newest version in sPHENIX GitHub at line 74 of file gzstream.h
Constructor & Destructor Documentation
gzstreambase::gzstreambase () inline
Definition at line 78 of file gzstream.h.
View newest version in sPHENIX GitHub at line 78 of file gzstream.h
References myAnalysis::init().
gzstreambase::gzstreambase (const char * name, int open_mode)
Definition at line 140 of file gzstream.cc.
View newest version in sPHENIX GitHub at line 140 of file gzstream.cc
References myAnalysis::init(), and Acts::open.
gzstreambase::~gzstreambase ()
Definition at line 145 of file gzstream.cc.
View newest version in sPHENIX GitHub at line 145 of file gzstream.cc
Member Function Documentation
void gzstreambase::close (void)
Definition at line 154 of file gzstream.cc.
View newest version in sPHENIX GitHub at line 154 of file gzstream.cc
Referenced by Jetscape::JetScapeWriterAsciiGZ::Close().
void gzstreambase::open (const char * name, int open_mode)
Definition at line 149 of file gzstream.cc.
View newest version in sPHENIX GitHub at line 149 of file gzstream.cc
Referenced by igzstream::open(), and ogzstream::open().
gzstreambuf* gzstreambase::rdbuf () inline
Definition at line 83 of file gzstream.h.
View newest version in sPHENIX GitHub at line 83 of file gzstream.h
Referenced by igzstream::rdbuf(), and ogzstream::rdbuf().
Member Data Documentation
gzstreambuf gzstreambase::buf protected
Definition at line 76 of file gzstream.h.
View newest version in sPHENIX GitHub at line 76 of file gzstream.h
The documentation for this class was generated from the following files:
JETSCAPE/blob/main/external_packages/gzstream.h
JETSCAPE/blob/main/external_packages/gzstream.cc