Analysis Software: acts/blob/sPHENIX/Tests/UnitTests/Fatras/Selectors/SelectorHelpersTests.cpp File Reference
SelectorHelpersTests.cpp File Reference
#include <boost/test/unit_test.hpp>
#include "ActsFatras/Selectors/KinematicCasts.hpp"
#include "ActsFatras/Selectors/SelectorHelpers.hpp"
#include <string>
#include "Dataset.hpp"
Functions
BOOST_AUTO_TEST_CASE (Min)
BOOST_AUTO_TEST_CASE (Max)
BOOST_AUTO_TEST_CASE (Range)
BOOST_AUTO_TEST_CASE (And1)
BOOST_AUTO_TEST_CASE (And2)
BOOST_AUTO_TEST_CASE (Or1)
BOOST_AUTO_TEST_CASE (Or2)
Function Documentation
BOOST_AUTO_TEST_CASE (Min)
Definition at line 60 of file SelectorHelpersTests.cpp.
View newest version in sPHENIX GitHub at line 60 of file SelectorHelpersTests.cpp
BOOST_AUTO_TEST_CASE (Max)
Definition at line 74 of file SelectorHelpersTests.cpp.
View newest version in sPHENIX GitHub at line 74 of file SelectorHelpersTests.cpp
BOOST_AUTO_TEST_CASE (Range)
Definition at line 88 of file SelectorHelpersTests.cpp.
View newest version in sPHENIX GitHub at line 88 of file SelectorHelpersTests.cpp
BOOST_AUTO_TEST_CASE (And1)
Definition at line 100 of file SelectorHelpersTests.cpp.
View newest version in sPHENIX GitHub at line 100 of file SelectorHelpersTests.cpp
References f, and ActsFatras::detail::CombineSelectors< Initial, Combine, Selectors >::get().
BOOST_AUTO_TEST_CASE (And2)
Definition at line 109 of file SelectorHelpersTests.cpp.
View newest version in sPHENIX GitHub at line 109 of file SelectorHelpersTests.cpp
References f, and ActsFatras::detail::CombineSelectors< Initial, Combine, Selectors >::get().
BOOST_AUTO_TEST_CASE (Or1)
Definition at line 119 of file SelectorHelpersTests.cpp.
View newest version in sPHENIX GitHub at line 119 of file SelectorHelpersTests.cpp
References f, and ActsFatras::detail::CombineSelectors< Initial, Combine, Selectors >::get().
BOOST_AUTO_TEST_CASE (Or2)
Definition at line 128 of file SelectorHelpersTests.cpp.
View newest version in sPHENIX GitHub at line 128 of file SelectorHelpersTests.cpp
References f, and ActsFatras::detail::CombineSelectors< Initial, Combine, Selectors >::get().