Analysis Software: EpdGeomV1 Class Reference
EpdGeomV1 Class Reference
#include <coresoftware/blob/master/offline/packages/epd/EpdGeomV1.h>
Public Member Functions
EpdGeomV1 ()=default
~EpdGeomV1 () override=default
float get_r (unsigned int key) const override
float get_z (unsigned int key) const override
float get_phi (unsigned int key) const override
void set_z (unsigned int key, float z) override
void set_r (unsigned int key, float r) override
void set_phi (unsigned int key, float f) override
void set_phi0 (unsigned int key, float f0) override
Public Member Functions inherited from EpdGeom
EpdGeom ()=default
~EpdGeom () override
Public Member Functions inherited from PHObject
PHObject ()
ctor
~PHObject () override
dtor
virtual PHObject * CloneMe () const
Virtual copy constructor.
virtual PHObject * clone () const final
PHObject * Clone (const char *newname="") const final
void Copy (TObject &object) const final
virtual void identify (std::ostream &os=std::cout) const
virtual void Reset ()
Clear Event.
virtual int isValid () const
isValid returns non zero if object contains vailid data
virtual int Integrate () const
virtual int Integrate (PHObject *)
virtual void CopyFrom (const PHObject *obj)
Private Attributes
float tile_r [16] = {}
float tile_z [2] = {}
float tile_phi [24] = {}
float tile_phi0 [12] = {}
Detailed Description
Definition at line 11 of file EpdGeomV1.h.
View newest version in sPHENIX GitHub at line 11 of file EpdGeomV1.h
Constructor & Destructor Documentation
EpdGeomV1::EpdGeomV1 () default
EpdGeomV1::~EpdGeomV1 () override default
Member Function Documentation
float EpdGeomV1::get_phi (unsigned int key) const override virtual
Reimplemented from EpdGeom.
Definition at line 25 of file EpdGeomV1.cc.
View newest version in sPHENIX GitHub at line 25 of file EpdGeomV1.cc
References TowerInfoDefs::get_epd_phibin(), TowerInfoDefs::get_epd_rbin(), tile_phi, and tile_phi0.
float EpdGeomV1::get_r (unsigned int key) const override virtual
Reimplemented from EpdGeom.
Definition at line 15 of file EpdGeomV1.cc.
View newest version in sPHENIX GitHub at line 15 of file EpdGeomV1.cc
References TowerInfoDefs::get_epd_rbin(), and tile_r.
float EpdGeomV1::get_z (unsigned int key) const override virtual
Reimplemented from EpdGeom.
Definition at line 20 of file EpdGeomV1.cc.
View newest version in sPHENIX GitHub at line 20 of file EpdGeomV1.cc
References TowerInfoDefs::get_epd_arm(), and tile_z.
void EpdGeomV1::set_phi (unsigned int key, float f) override virtual
Reimplemented from EpdGeom.
Definition at line 49 of file EpdGeomV1.cc.
View newest version in sPHENIX GitHub at line 49 of file EpdGeomV1.cc
References f, TowerInfoDefs::get_epd_phibin(), and tile_phi.
void EpdGeomV1::set_phi0 (unsigned int key, float f0) override virtual
Reimplemented from EpdGeom.
Definition at line 54 of file EpdGeomV1.cc.
View newest version in sPHENIX GitHub at line 54 of file EpdGeomV1.cc
References TowerInfoDefs::get_epd_phibin(), and tile_phi0.
void EpdGeomV1::set_r (unsigned int key, float r) override virtual
Reimplemented from EpdGeom.
Definition at line 44 of file EpdGeomV1.cc.
View newest version in sPHENIX GitHub at line 44 of file EpdGeomV1.cc
References TowerInfoDefs::get_epd_rbin(), physmon_track_finding_ttbar::r, and tile_r.
void EpdGeomV1::set_z (unsigned int key, float z) override virtual
Reimplemented from EpdGeom.
Definition at line 39 of file EpdGeomV1.cc.
View newest version in sPHENIX GitHub at line 39 of file EpdGeomV1.cc
References TowerInfoDefs::get_epd_arm(), tile_z, and physmon_track_finding_ttbar::z.
Member Data Documentation
float EpdGeomV1::tile_phi[24] = {} private
Definition at line 30 of file EpdGeomV1.h.
View newest version in sPHENIX GitHub at line 30 of file EpdGeomV1.h
Referenced by get_phi(), and set_phi().
float EpdGeomV1::tile_phi0[12] = {} private
Definition at line 31 of file EpdGeomV1.h.
View newest version in sPHENIX GitHub at line 31 of file EpdGeomV1.h
Referenced by get_phi(), and set_phi0().
float EpdGeomV1::tile_r[16] = {} private
Definition at line 28 of file EpdGeomV1.h.
View newest version in sPHENIX GitHub at line 28 of file EpdGeomV1.h
Referenced by get_r(), and set_r().
float EpdGeomV1::tile_z[2] = {} private
Definition at line 29 of file EpdGeomV1.h.
View newest version in sPHENIX GitHub at line 29 of file EpdGeomV1.h
Referenced by get_z(), and set_z().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/epd/EpdGeomV1.h
coresoftware/blob/master/offline/packages/epd/EpdGeomV1.cc