Analysis Software: PHG4Sector::PHG4SectorConstructor Class Reference
PHG4Sector::PHG4SectorConstructor Class Reference
Generalized detector which use sectors of flat panels to cover full azimuthal acceptance.
#include <coresoftware/blob/master/simulation/g4simulation/g4detectors/PHG4SectorConstructor.h>
Public Member Functions
PHG4SectorConstructor (const std::string &name, PHG4Subsystem *subsys)
virtual ~PHG4SectorConstructor ()
void Construct_Sectors (G4LogicalVolume *WorldLog)
void OverlapCheck (bool check)
void Verbosity (int v)
int Verbosity () const
Public Attributes
std::string name_base
Sector_Geometry geom
Protected Types
typedef std::map< G4String,
G4LogicalVolume * > map_log_vol_t
typedef std::pair< G4String,
G4int > phy_vol_idx_t
typedef std::map
< phy_vol_idx_t, G4PVPlacement * > map_phy_vol_t
Protected Member Functions
G4VSolid * Construct_Sectors_Plane (const std::string &name, const double start_z, const double thickness, G4VSolid *SecConeBoundary_Det)
G4LogicalVolume * RegisterLogicalVolume (G4LogicalVolume *)
G4PVPlacement * RegisterPhysicalVolume (G4PVPlacement *v, const bool active=false)
Protected Attributes
bool overlapcheck_sector
map_log_vol_t map_log_vol
map_phy_vol_t map_phy_vol
map_phy_vol_t map_active_phy_vol
all physics volume
Private Attributes
PHG4SectorDisplayAction * m_DisplayAction
int m_Verbosity
Detailed Description
Generalized detector which use sectors of flat panels to cover full azimuthal acceptance.
Definition at line 350 of file PHG4SectorConstructor.h.
View newest version in sPHENIX GitHub at line 350 of file PHG4SectorConstructor.h
Member Typedef Documentation
typedef std::map<G4String, G4LogicalVolume *> PHG4Sector::PHG4SectorConstructor::map_log_vol_t protected
Definition at line 394 of file PHG4SectorConstructor.h.
View newest version in sPHENIX GitHub at line 394 of file PHG4SectorConstructor.h
typedef std::map<phy_vol_idx_t, G4PVPlacement *> PHG4Sector::PHG4SectorConstructor::map_phy_vol_t protected
Definition at line 401 of file PHG4SectorConstructor.h.
View newest version in sPHENIX GitHub at line 401 of file PHG4SectorConstructor.h
typedef std::pair<G4String, G4int> PHG4Sector::PHG4SectorConstructor::phy_vol_idx_t protected
Definition at line 400 of file PHG4SectorConstructor.h.
View newest version in sPHENIX GitHub at line 400 of file PHG4SectorConstructor.h
Constructor & Destructor Documentation
PHG4Sector::PHG4SectorConstructor::PHG4SectorConstructor (const std::string & name, PHG4Subsystem * subsys)
Definition at line 41 of file PHG4SectorConstructor.cc.
View newest version in sPHENIX GitHub at line 41 of file PHG4SectorConstructor.cc
virtual PHG4Sector::PHG4SectorConstructor::~PHG4SectorConstructor () inline virtual
Definition at line 354 of file PHG4SectorConstructor.h.
View newest version in sPHENIX GitHub at line 354 of file PHG4SectorConstructor.h
Member Function Documentation
void PHG4Sector::PHG4SectorConstructor::Construct_Sectors (G4LogicalVolume * WorldLog)
Definition at line 49 of file PHG4SectorConstructor.cc.
View newest version in sPHENIX GitHub at line 49 of file PHG4SectorConstructor.cc
References Acts::UnitConstants::cm, PHG4Detector::GetDetectorMaterial(), PHG4Sector::Sector_Geometry::kConeEdge, PHG4Sector::Sector_Geometry::kFlatEdge, pi, t, Acts::UnitConstants::um, and Verbosity().
Referenced by PHG4SectorDetector::ConstructMe().
G4VSolid * PHG4Sector::PHG4SectorConstructor::Construct_Sectors_Plane (const std::string & name, const double start_z, const double thickness, G4VSolid * SecConeBoundary_Det) protected
Definition at line 208 of file PHG4SectorConstructor.cc.
View newest version in sPHENIX GitHub at line 208 of file PHG4SectorConstructor.cc
References assert, and pi.
void PHG4Sector::PHG4SectorConstructor::OverlapCheck (bool check) inline
Definition at line 360 of file PHG4SectorConstructor.h.
View newest version in sPHENIX GitHub at line 360 of file PHG4SectorConstructor.h
References check_fpe_masks::check(), and overlapcheck_sector.
G4LogicalVolume * PHG4Sector::PHG4SectorConstructor::RegisterLogicalVolume (G4LogicalVolume * v) protected
Definition at line 258 of file PHG4SectorConstructor.cc.
View newest version in sPHENIX GitHub at line 258 of file PHG4SectorConstructor.cc
References testSigmaEff::v.
G4PVPlacement * PHG4Sector::PHG4SectorConstructor::RegisterPhysicalVolume (G4PVPlacement * v, const bool active = false) protected
Definition at line 279 of file PHG4SectorConstructor.cc.
View newest version in sPHENIX GitHub at line 279 of file PHG4SectorConstructor.cc
References train_ambiguity_solver::id, and testSigmaEff::v.
void PHG4Sector::PHG4SectorConstructor::Verbosity (int v) inline
Definition at line 365 of file PHG4SectorConstructor.h.
View newest version in sPHENIX GitHub at line 365 of file PHG4SectorConstructor.h
References m_Verbosity, and testSigmaEff::v.
int PHG4Sector::PHG4SectorConstructor::Verbosity () const inline
Definition at line 366 of file PHG4SectorConstructor.h.
View newest version in sPHENIX GitHub at line 366 of file PHG4SectorConstructor.h
References m_Verbosity.
Member Data Documentation
Sector_Geometry PHG4Sector::PHG4SectorConstructor::geom
Definition at line 384 of file PHG4SectorConstructor.h.
View newest version in sPHENIX GitHub at line 384 of file PHG4SectorConstructor.h
Referenced by PHG4SectorSubsystem::Init().
PHG4SectorDisplayAction* PHG4Sector::PHG4SectorConstructor::m_DisplayAction private
Definition at line 387 of file PHG4SectorConstructor.h.
View newest version in sPHENIX GitHub at line 387 of file PHG4SectorConstructor.h
int PHG4Sector::PHG4SectorConstructor::m_Verbosity private
Definition at line 388 of file PHG4SectorConstructor.h.
View newest version in sPHENIX GitHub at line 388 of file PHG4SectorConstructor.h
Referenced by Verbosity().
map_phy_vol_t PHG4Sector::PHG4SectorConstructor::map_active_phy_vol protected
all physics volume
Definition at line 403 of file PHG4SectorConstructor.h.
View newest version in sPHENIX GitHub at line 403 of file PHG4SectorConstructor.h
Referenced by PHG4SectorDetector::IsInSectorActive().
map_log_vol_t PHG4Sector::PHG4SectorConstructor::map_log_vol protected
Definition at line 395 of file PHG4SectorConstructor.h.
View newest version in sPHENIX GitHub at line 395 of file PHG4SectorConstructor.h
Referenced by PHG4SectorDetector::ConstructMe().
map_phy_vol_t PHG4Sector::PHG4SectorConstructor::map_phy_vol protected
Definition at line 402 of file PHG4SectorConstructor.h.
View newest version in sPHENIX GitHub at line 402 of file PHG4SectorConstructor.h
std::string PHG4Sector::PHG4SectorConstructor::name_base
Definition at line 382 of file PHG4SectorConstructor.h.
View newest version in sPHENIX GitHub at line 382 of file PHG4SectorConstructor.h
Referenced by PHG4SectorDetector::ConstructMe().
bool PHG4Sector::PHG4SectorConstructor::overlapcheck_sector protected
Definition at line 369 of file PHG4SectorConstructor.h.
View newest version in sPHENIX GitHub at line 369 of file PHG4SectorConstructor.h
Referenced by OverlapCheck().
The documentation for this class was generated from the following files:
coresoftware/blob/master/simulation/g4simulation/g4detectors/PHG4SectorConstructor.h
coresoftware/blob/master/simulation/g4simulation/g4detectors/PHG4SectorConstructor.cc