Analysis Software: RawTowerDigitizer Class Reference
RawTowerDigitizer Class Reference
#include <coresoftware/blob/master/simulation/g4simulation/g4calo/RawTowerDigitizer.h>
Public Types
enum enu_digi_algorithm {
kNo_digitization = 0, kNo_digitalization = 0, kSimple_photon_digitization = 1, kSimple_photon_digitalization = 1,
kSiPM_photon_digitization = 2
}
enum ProcessTowerType { kRawTowerOnly = 0, kTowerInfoOnly = 1, kBothTowers =2 }
Public Member Functions
RawTowerDigitizer (const std::string &name="RawTowerDigitizer")
~RawTowerDigitizer () override
int InitRun (PHCompositeNode *topNode) override
int process_event (PHCompositeNode *topNode) override
void Detector (const std::string &d)
void TowerType (const int type)
void set_seed (const unsigned int iseed)
unsigned int get_seed () const
enu_digi_algorithm get_digi_algorithm () const
void set_digi_algorithm (enu_digi_algorithm digiAlgorithm)
double get_pedstal_central_ADC () const
void set_pedstal_central_ADC (const double pedstalCentralAdc)
double get_pedstal_width_ADC () const
void set_pedstal_width_ADC (const double pedstalWidthAdc)
double get_photonelec_ADC () const
void set_photonelec_ADC (const double photonelecAdc)
double get_photonelec_yield_visible_GeV () const
void set_photonelec_yield_visible_GeV (const double photonelecYieldVisibleGeV)
double get_zero_suppression_ADC () const
void set_zero_suppression_ADC (const double zeroSuppressionAdc)
void set_variable_zero_suppression (const bool value)
void set_variable_pedestal (const bool value)
PHParameters & GetParameters ()
std::string get_raw_tower_node_prefix () const
void set_raw_tower_node_prefix (const std::string &rawTowerNodePrefix)
std::string get_sim_tower_node_prefix () const
void set_sim_tower_node_prefix (const std::string &simTowerNodePrefix)
void set_sipm_effective_pixel (const unsigned int &d)
unsigned int get_sipm_effective_pixel ()
void set_DoTowerDecal (const bool doTowerDecal, const char *decalFileName="", const bool doInverse=false)
void set_DecalFileName (const char *inCalFname)
void set_UseConditionsDB (const bool setUseCondDB)
void set_towerinfo (RawTowerDigitizer::ProcessTowerType UseTowerInfo)
Public Member Functions inherited from SubsysReco
~SubsysReco () override
virtual int End (PHCompositeNode *)
Called at the end of all processing.
virtual int EndRun (const int)
Called at the end of each run.
virtual int Init (PHCompositeNode *)
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
void Print (const std::string &="ALL") const override
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Private Member Functions
void CreateNodes (PHCompositeNode *topNode)
RawTower * simple_photon_digitization (RawTower *sim_tower)
TowerInfo * simple_photon_digitization (TowerInfo *sim_tower)
RawTower * sipm_photon_digitization (RawTower *sim_tower)
TowerInfo * sipm_photon_digitization (TowerInfo *sim_tower)
Private Attributes
enu_digi_algorithm m_DigiAlgorithm = kNo_digitization
RawTowerContainer * m_SimTowers = nullptr
RawTowerContainer * m_RawTowers = nullptr
TowerInfoContainer * m_SimTowerInfos = nullptr
TowerInfoContainer * m_RawTowerInfos = nullptr
RawTowerGeomContainer * m_RawTowerGeom = nullptr
RawTowerDeadMap * m_DeadMap = nullptr
std::string m_Detector = "NONE"
std::string m_SimTowerNodePrefix = "SIM"
std::string m_RawTowerNodePrefix = "RAW"
double m_PhotonElecYieldVisibleGeV = NAN
photon electron yield per GeV of visible energy
double m_PhotonElecADC = NAN
photon electron per ADC unit
double m_PedstalCentralADC = NAN
pedstal central in unit of ADC
double m_PedstalWidthADC = NAN
pedstal width in unit of ADC
bool m_pedestalFile = false
pedestal from file
double m_ZeroSuppressionADC = -1000
zero suppression in unit of ADC
bool m_ZeroSuppressionFile = false
zero suppression from file
int m_TowerType = -1
tower type to act on
unsigned int m_Seed = 0
unsigned int m_SiPMEffectivePixel = 40000 * 4
PHParameters _tower_params
gsl_rng * m_RandomGenerator = nullptr
bool m_DoDecal = false
bool m_DecalInverse = false
bool m_Decal = true
std::string m_DecalFileName
bool m_UseConditionsDB = false
CDBTTree * m_CDBTTree = nullptr
RawTowerDigitizer::ProcessTowerType m_UseTowerInfo = RawTowerDigitizer::ProcessTowerType::kBothTowers
Additional Inherited Members
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Detailed Description
simple tower digitizer which sum all cell to produce photon yield and pedstal noises default input DST node is TOWER_SIM_DETECTOR default output DST node is TOWER_RAW_DETECTOR
Definition at line 25 of file RawTowerDigitizer.h.
View newest version in sPHENIX GitHub at line 25 of file RawTowerDigitizer.h
Member Enumeration Documentation
enum RawTowerDigitizer::enu_digi_algorithm
Enumerator:
kNo_digitization
directly pass the energy of sim tower to digitized tower
kNo_digitalization
wrong spelling, kept for macro compatibility
kSimple_photon_digitization
simple digitization with photon statistics, single amplitude ADC conversion and pedestal
kSimple_photon_digitalization
wrong spelling, kept for macro compatibility
kSiPM_photon_digitization
digitization with photon statistics on SiPM with an effective pixel N, ADC conversion and pedestal
Definition at line 41 of file RawTowerDigitizer.h.
View newest version in sPHENIX GitHub at line 41 of file RawTowerDigitizer.h
enum RawTowerDigitizer::ProcessTowerType
Enumerator:
kRawTowerOnly
kTowerInfoOnly
kBothTowers
Definition at line 57 of file RawTowerDigitizer.h.
View newest version in sPHENIX GitHub at line 57 of file RawTowerDigitizer.h
Constructor & Destructor Documentation
RawTowerDigitizer::RawTowerDigitizer (const std::string & name = "RawTowerDigitizer")
Definition at line 51 of file RawTowerDigitizer.cc.
View newest version in sPHENIX GitHub at line 51 of file RawTowerDigitizer.cc
References gsl_rng_set(), m_RandomGenerator, and m_Seed.
RawTowerDigitizer::~RawTowerDigitizer () override
Definition at line 61 of file RawTowerDigitizer.cc.
View newest version in sPHENIX GitHub at line 61 of file RawTowerDigitizer.cc
References m_CDBTTree, and m_RandomGenerator.
Member Function Documentation
void RawTowerDigitizer::CreateNodes (PHCompositeNode * topNode) private
Definition at line 688 of file RawTowerDigitizer.cc.
View newest version in sPHENIX GitHub at line 688 of file RawTowerDigitizer.cc
References PHCompositeNode::addNode(), PHNodeIterator::findFirst(), RawTowerContainer::getCalorimeterID(), RawTowerDeadMap::identify(), RawTowerGeomContainer::identify(), m_DeadMap, m_Detector, m_RawTowerGeom, m_RawTowerInfos, m_RawTowerNodePrefix, m_RawTowers, m_SimTowerInfos, m_SimTowerNodePrefix, m_SimTowers, m_UseTowerInfo, Fun4AllBase::Name(), PHWHERE, and Fun4AllBase::Verbosity().
Referenced by InitRun().
void RawTowerDigitizer::Detector (const std::string & d) inline
Definition at line 33 of file RawTowerDigitizer.h.
View newest version in sPHENIX GitHub at line 33 of file RawTowerDigitizer.h
References _tower_params, m_Detector, and PHParameters::set_name().
Referenced by CEMC_Towers(), EEMC_Towers(), FEMC_Towers(), FHCAL_Towers(), Fun4All_G4_Prototype2(), Fun4All_G4_Prototype3(), Fun4All_G4_Prototype4(), HCALInner_Towers(), HCALOuter_Towers(), and ZDC_Towers().
enu_digi_algorithm RawTowerDigitizer::get_digi_algorithm () const inline
Definition at line 65 of file RawTowerDigitizer.h.
View newest version in sPHENIX GitHub at line 65 of file RawTowerDigitizer.h
References m_DigiAlgorithm.
double RawTowerDigitizer::get_pedstal_central_ADC () const inline
Definition at line 77 of file RawTowerDigitizer.h.
View newest version in sPHENIX GitHub at line 77 of file RawTowerDigitizer.h
References m_PedstalCentralADC.
double RawTowerDigitizer::get_pedstal_width_ADC () const inline
Definition at line 89 of file RawTowerDigitizer.h.
View newest version in sPHENIX GitHub at line 89 of file RawTowerDigitizer.h
References m_PedstalWidthADC.
double RawTowerDigitizer::get_photonelec_ADC () const inline
Definition at line 101 of file RawTowerDigitizer.h.
View newest version in sPHENIX GitHub at line 101 of file RawTowerDigitizer.h
References m_PhotonElecADC.
double RawTowerDigitizer::get_photonelec_yield_visible_GeV () const inline
Definition at line 113 of file RawTowerDigitizer.h.
View newest version in sPHENIX GitHub at line 113 of file RawTowerDigitizer.h
References m_PhotonElecYieldVisibleGeV.
std::string RawTowerDigitizer::get_raw_tower_node_prefix () const inline
Definition at line 155 of file RawTowerDigitizer.h.
View newest version in sPHENIX GitHub at line 155 of file RawTowerDigitizer.h
References m_RawTowerNodePrefix.
unsigned int RawTowerDigitizer::get_seed () const inline
Definition at line 40 of file RawTowerDigitizer.h.
View newest version in sPHENIX GitHub at line 40 of file RawTowerDigitizer.h
References m_Seed.
std::string RawTowerDigitizer::get_sim_tower_node_prefix () const inline
Definition at line 167 of file RawTowerDigitizer.h.
View newest version in sPHENIX GitHub at line 167 of file RawTowerDigitizer.h
References m_SimTowerNodePrefix.
unsigned int RawTowerDigitizer::get_sipm_effective_pixel () inline
Definition at line 182 of file RawTowerDigitizer.h.
View newest version in sPHENIX GitHub at line 182 of file RawTowerDigitizer.h
References m_SiPMEffectivePixel.
double RawTowerDigitizer::get_zero_suppression_ADC () const inline
Definition at line 125 of file RawTowerDigitizer.h.
View newest version in sPHENIX GitHub at line 125 of file RawTowerDigitizer.h
References m_ZeroSuppressionADC.
PHParameters& RawTowerDigitizer::GetParameters () inline
Definition at line 149 of file RawTowerDigitizer.h.
View newest version in sPHENIX GitHub at line 149 of file RawTowerDigitizer.h
References _tower_params.
Referenced by CEMC_Towers().
int RawTowerDigitizer::InitRun (PHCompositeNode *) override virtual
Called for first event when run number is known. Typically this is where you may want to fetch data from database, because you know the run number.
Reimplemented from SubsysReco.
Definition at line 73 of file RawTowerDigitizer.cc.
View newest version in sPHENIX GitHub at line 73 of file RawTowerDigitizer.cc
References Fun4AllReturnCodes::ABORTRUN, CreateNodes(), Acts::UnitConstants::e, Fun4AllReturnCodes::EVENT_OK, PHNodeIterator::findFirst(), CDBInterface::getUrl(), CDBInterface::instance(), m_CDBTTree, m_Detector, m_DoDecal, Fun4AllBase::Name(), PHWHERE, and summary::url.
int RawTowerDigitizer::process_event (PHCompositeNode *) override virtual
Called for each event. This is where you do the real work.
Reimplemented from SubsysReco.
Definition at line 136 of file RawTowerDigitizer.cc.
View newest version in sPHENIX GitHub at line 136 of file RawTowerDigitizer.cc
References _tower_params, Fun4AllReturnCodes::ABORTRUN, RawTowerContainer::AddTower(), RawTowerDefs::decode_caloid(), eta, Fun4AllReturnCodes::EVENT_OK, PHParameters::get_double_param(), TowerInfo::get_energy(), RawTower::get_energy(), TowerInfoContainer::get_tower_at_key(), RawTowerGeomContainer::get_tower_geometries(), CDBTTree::GetFloatValue(), RawTowerContainer::getTotalEdep(), RawTowerContainer::getTower(), RawTower::identify(), RawTowerDeadMap::isDeadTower(), it, kNo_digitization, kSimple_photon_digitization, kSiPM_photon_digitization, RawTowerDefs::LFHCAL, m_CDBTTree, m_DeadMap, m_Decal, m_DecalInverse, m_Detector, m_DigiAlgorithm, m_DoDecal, m_pedestalFile, m_PedstalCentralADC, m_PedstalWidthADC, m_RawTowerGeom, m_RawTowerInfos, m_RawTowers, m_SimTowerInfos, m_SimTowers, m_TowerType, m_UseTowerInfo, m_ZeroSuppressionADC, m_ZeroSuppressionFile, Fun4AllBase::Name(), ActsTests::PropagationDatasets::phi, TowerInfo::set_energy(), RawTower::set_energy(), simple_photon_digitization(), sipm_photon_digitization(), to_string(), Fun4AllBase::Verbosity(), and Fun4AllBase::VERBOSITY_MORE.
void RawTowerDigitizer::set_DecalFileName (const char * inCalFname) inline
Definition at line 194 of file RawTowerDigitizer.h.
View newest version in sPHENIX GitHub at line 194 of file RawTowerDigitizer.h
References m_DecalFileName.
Referenced by set_DoTowerDecal().
void RawTowerDigitizer::set_digi_algorithm (enu_digi_algorithm digiAlgorithm) inline
Definition at line 71 of file RawTowerDigitizer.h.
View newest version in sPHENIX GitHub at line 71 of file RawTowerDigitizer.h
References m_DigiAlgorithm.
Referenced by CEMC_Towers(), EEMC_Towers(), FEMC_Towers(), FHCAL_Towers(), Fun4All_G4_Prototype2(), Fun4All_G4_Prototype3(), Fun4All_G4_Prototype4(), HCALInner_Towers(), HCALOuter_Towers(), and ZDC_Towers().
void RawTowerDigitizer::set_DoTowerDecal (const bool doTowerDecal, const char * decalFileName = "", const bool doInverse = false) inline
Definition at line 185 of file RawTowerDigitizer.h.
View newest version in sPHENIX GitHub at line 185 of file RawTowerDigitizer.h
References m_DecalInverse, m_DoDecal, and set_DecalFileName().
Referenced by CEMC_Towers().
void RawTowerDigitizer::set_pedstal_central_ADC (const double pedstalCentralAdc) inline
Definition at line 83 of file RawTowerDigitizer.h.
View newest version in sPHENIX GitHub at line 83 of file RawTowerDigitizer.h
References m_PedstalCentralADC.
Referenced by CEMC_Towers(), EEMC_Towers(), Fun4All_G4_Prototype2(), Fun4All_G4_Prototype3(), Fun4All_G4_Prototype4(), HCALInner_Towers(), and HCALOuter_Towers().
void RawTowerDigitizer::set_pedstal_width_ADC (const double pedstalWidthAdc) inline
Definition at line 95 of file RawTowerDigitizer.h.
View newest version in sPHENIX GitHub at line 95 of file RawTowerDigitizer.h
References m_PedstalWidthADC.
Referenced by CEMC_Towers(), EEMC_Towers(), Fun4All_G4_Prototype2(), Fun4All_G4_Prototype3(), Fun4All_G4_Prototype4(), HCALInner_Towers(), and HCALOuter_Towers().
void RawTowerDigitizer::set_photonelec_ADC (const double photonelecAdc) inline
Definition at line 107 of file RawTowerDigitizer.h.
View newest version in sPHENIX GitHub at line 107 of file RawTowerDigitizer.h
References m_PhotonElecADC.
Referenced by CEMC_Towers(), EEMC_Towers(), Fun4All_G4_Prototype2(), Fun4All_G4_Prototype3(), Fun4All_G4_Prototype4(), HCALInner_Towers(), and HCALOuter_Towers().
void RawTowerDigitizer::set_photonelec_yield_visible_GeV (const double photonelecYieldVisibleGeV) inline
Definition at line 119 of file RawTowerDigitizer.h.
View newest version in sPHENIX GitHub at line 119 of file RawTowerDigitizer.h
References m_PhotonElecYieldVisibleGeV.
Referenced by CEMC_Towers(), EEMC_Towers(), Fun4All_G4_Prototype2(), Fun4All_G4_Prototype3(), Fun4All_G4_Prototype4(), HCALInner_Towers(), and HCALOuter_Towers().
void RawTowerDigitizer::set_raw_tower_node_prefix (const std::string & rawTowerNodePrefix) inline
Definition at line 161 of file RawTowerDigitizer.h.
View newest version in sPHENIX GitHub at line 161 of file RawTowerDigitizer.h
References m_RawTowerNodePrefix.
Referenced by EEMC_Towers(), Fun4All_G4_Prototype2(), Fun4All_G4_Prototype3(), and Fun4All_G4_Prototype4().
void RawTowerDigitizer::set_seed (const unsigned int iseed)
Definition at line 67 of file RawTowerDigitizer.cc.
View newest version in sPHENIX GitHub at line 67 of file RawTowerDigitizer.cc
References gsl_rng_set(), m_RandomGenerator, and m_Seed.
void RawTowerDigitizer::set_sim_tower_node_prefix (const std::string & simTowerNodePrefix) inline
Definition at line 173 of file RawTowerDigitizer.h.
View newest version in sPHENIX GitHub at line 173 of file RawTowerDigitizer.h
References m_SimTowerNodePrefix.
void RawTowerDigitizer::set_sipm_effective_pixel (const unsigned int & d) inline
Definition at line 179 of file RawTowerDigitizer.h.
View newest version in sPHENIX GitHub at line 179 of file RawTowerDigitizer.h
References m_SiPMEffectivePixel.
void RawTowerDigitizer::set_towerinfo (RawTowerDigitizer::ProcessTowerType UseTowerInfo) inline
Definition at line 204 of file RawTowerDigitizer.h.
View newest version in sPHENIX GitHub at line 204 of file RawTowerDigitizer.h
References m_UseTowerInfo.
Referenced by CEMC_Towers(), HCALInner_Towers(), and HCALOuter_Towers().
void RawTowerDigitizer::set_UseConditionsDB (const bool setUseCondDB) inline
Definition at line 199 of file RawTowerDigitizer.h.
View newest version in sPHENIX GitHub at line 199 of file RawTowerDigitizer.h
References m_UseConditionsDB.
Referenced by CEMC_Towers().
void RawTowerDigitizer::set_variable_pedestal (const bool value) inline
Definition at line 143 of file RawTowerDigitizer.h.
View newest version in sPHENIX GitHub at line 143 of file RawTowerDigitizer.h
References m_pedestalFile, and value.
Referenced by CEMC_Towers().
void RawTowerDigitizer::set_variable_zero_suppression (const bool value) inline
Definition at line 137 of file RawTowerDigitizer.h.
View newest version in sPHENIX GitHub at line 137 of file RawTowerDigitizer.h
References m_ZeroSuppressionFile, and value.
Referenced by CEMC_Towers().
void RawTowerDigitizer::set_zero_suppression_ADC (const double zeroSuppressionAdc) inline
Definition at line 131 of file RawTowerDigitizer.h.
View newest version in sPHENIX GitHub at line 131 of file RawTowerDigitizer.h
References m_ZeroSuppressionADC.
Referenced by CEMC_Towers(), EEMC_Towers(), Fun4All_G4_Prototype2(), Fun4All_G4_Prototype3(), Fun4All_G4_Prototype4(), HCALInner_Towers(), and HCALOuter_Towers().
RawTower * RawTowerDigitizer::simple_photon_digitization (RawTower * sim_tower) private
simple digitization with photon statistics, ADC conversion and pedstal
Parameters
sim_tower simulation tower input
Returns
a new RawTower object contain digitalized value of ADC output in RawTower::get_energy()
Definition at line 385 of file RawTowerDigitizer.cc.
View newest version in sPHENIX GitHub at line 385 of file RawTowerDigitizer.cc
References double(), energy, RawTower::get_energy(), RawTower::identify(), m_Detector, m_DoDecal, m_PedstalCentralADC, m_PedstalWidthADC, m_PhotonElecADC, m_PhotonElecYieldVisibleGeV, m_RandomGenerator, m_ZeroSuppressionADC, Fun4AllBase::Name(), pedestal(), RawTower::set_energy(), and Fun4AllBase::Verbosity().
Referenced by process_event().
TowerInfo * RawTowerDigitizer::simple_photon_digitization (TowerInfo * sim_tower) private
Definition at line 462 of file RawTowerDigitizer.cc.
View newest version in sPHENIX GitHub at line 462 of file RawTowerDigitizer.cc
References double(), energy, TowerInfo::get_energy(), PHObject::identify(), m_Detector, m_DoDecal, m_PedstalCentralADC, m_PedstalWidthADC, m_PhotonElecADC, m_PhotonElecYieldVisibleGeV, m_RandomGenerator, m_ZeroSuppressionADC, Fun4AllBase::Name(), pedestal(), TowerInfo::set_energy(), and Fun4AllBase::Verbosity().
RawTower * RawTowerDigitizer::sipm_photon_digitization (RawTower * sim_tower) private
digitization with photon statistics on SiPM with an effective pixel N, ADC conversion and pedestal this function use the effective pixel to count for the effect that the sipm is not evenly lit
Definition at line 537 of file RawTowerDigitizer.cc.
View newest version in sPHENIX GitHub at line 537 of file RawTowerDigitizer.cc
References energy, RawTower::get_energy(), RawTower::identify(), m_Detector, m_PedstalCentralADC, m_PedstalWidthADC, m_PhotonElecADC, m_PhotonElecYieldVisibleGeV, m_RandomGenerator, m_SiPMEffectivePixel, m_ZeroSuppressionADC, Fun4AllBase::Name(), RawTower::set_energy(), and Fun4AllBase::Verbosity().
Referenced by process_event().
TowerInfo * RawTowerDigitizer::sipm_photon_digitization (TowerInfo * sim_tower) private
Definition at line 610 of file RawTowerDigitizer.cc.
View newest version in sPHENIX GitHub at line 610 of file RawTowerDigitizer.cc
References energy, TowerInfo::get_energy(), PHObject::identify(), m_Detector, m_PedstalCentralADC, m_PedstalWidthADC, m_PhotonElecADC, m_PhotonElecYieldVisibleGeV, m_RandomGenerator, m_SiPMEffectivePixel, m_ZeroSuppressionADC, Fun4AllBase::Name(), TowerInfo::set_energy(), and Fun4AllBase::Verbosity().
void RawTowerDigitizer::TowerType (const int type) inline
Definition at line 38 of file RawTowerDigitizer.h.
View newest version in sPHENIX GitHub at line 38 of file RawTowerDigitizer.h
References m_TowerType, and parse_cmake_options::type.
Referenced by FEMC_Towers(), and ZDC_Towers().
Member Data Documentation
PHParameters RawTowerDigitizer::_tower_params private
Definition at line 271 of file RawTowerDigitizer.h.
View newest version in sPHENIX GitHub at line 271 of file RawTowerDigitizer.h
Referenced by Detector(), GetParameters(), and process_event().
CDBTTree* RawTowerDigitizer::m_CDBTTree = nullptr private
Definition at line 281 of file RawTowerDigitizer.h.
View newest version in sPHENIX GitHub at line 281 of file RawTowerDigitizer.h
Referenced by InitRun(), process_event(), and ~RawTowerDigitizer().
RawTowerDeadMap* RawTowerDigitizer::m_DeadMap = nullptr private
Definition at line 234 of file RawTowerDigitizer.h.
View newest version in sPHENIX GitHub at line 234 of file RawTowerDigitizer.h
Referenced by CreateNodes(), and process_event().
bool RawTowerDigitizer::m_Decal = true private
Definition at line 278 of file RawTowerDigitizer.h.
View newest version in sPHENIX GitHub at line 278 of file RawTowerDigitizer.h
Referenced by process_event().
std::string RawTowerDigitizer::m_DecalFileName private
Definition at line 279 of file RawTowerDigitizer.h.
View newest version in sPHENIX GitHub at line 279 of file RawTowerDigitizer.h
Referenced by set_DecalFileName().
bool RawTowerDigitizer::m_DecalInverse = false private
Definition at line 277 of file RawTowerDigitizer.h.
View newest version in sPHENIX GitHub at line 277 of file RawTowerDigitizer.h
Referenced by process_event(), and set_DoTowerDecal().
std::string RawTowerDigitizer::m_Detector = "NONE" private
Definition at line 236 of file RawTowerDigitizer.h.
View newest version in sPHENIX GitHub at line 236 of file RawTowerDigitizer.h
Referenced by CreateNodes(), Detector(), InitRun(), process_event(), simple_photon_digitization(), and sipm_photon_digitization().
enu_digi_algorithm RawTowerDigitizer::m_DigiAlgorithm = kNo_digitization private
Definition at line 223 of file RawTowerDigitizer.h.
View newest version in sPHENIX GitHub at line 223 of file RawTowerDigitizer.h
Referenced by get_digi_algorithm(), process_event(), and set_digi_algorithm().
bool RawTowerDigitizer::m_DoDecal = false private
Definition at line 276 of file RawTowerDigitizer.h.
View newest version in sPHENIX GitHub at line 276 of file RawTowerDigitizer.h
Referenced by InitRun(), process_event(), set_DoTowerDecal(), and simple_photon_digitization().
bool RawTowerDigitizer::m_pedestalFile = false private
pedestal from file
Definition at line 254 of file RawTowerDigitizer.h.
View newest version in sPHENIX GitHub at line 254 of file RawTowerDigitizer.h
Referenced by process_event(), and set_variable_pedestal().
double RawTowerDigitizer::m_PedstalCentralADC = NAN private
pedstal central in unit of ADC
Definition at line 248 of file RawTowerDigitizer.h.
View newest version in sPHENIX GitHub at line 248 of file RawTowerDigitizer.h
Referenced by get_pedstal_central_ADC(), process_event(), set_pedstal_central_ADC(), simple_photon_digitization(), and sipm_photon_digitization().
double RawTowerDigitizer::m_PedstalWidthADC = NAN private
pedstal width in unit of ADC
Definition at line 251 of file RawTowerDigitizer.h.
View newest version in sPHENIX GitHub at line 251 of file RawTowerDigitizer.h
Referenced by get_pedstal_width_ADC(), process_event(), set_pedstal_width_ADC(), simple_photon_digitization(), and sipm_photon_digitization().
double RawTowerDigitizer::m_PhotonElecADC = NAN private
photon electron per ADC unit
Definition at line 245 of file RawTowerDigitizer.h.
View newest version in sPHENIX GitHub at line 245 of file RawTowerDigitizer.h
Referenced by get_photonelec_ADC(), set_photonelec_ADC(), simple_photon_digitization(), and sipm_photon_digitization().
double RawTowerDigitizer::m_PhotonElecYieldVisibleGeV = NAN private
photon electron yield per GeV of visible energy
Definition at line 242 of file RawTowerDigitizer.h.
View newest version in sPHENIX GitHub at line 242 of file RawTowerDigitizer.h
Referenced by get_photonelec_yield_visible_GeV(), set_photonelec_yield_visible_GeV(), simple_photon_digitization(), and sipm_photon_digitization().
gsl_rng* RawTowerDigitizer::m_RandomGenerator = nullptr private
Definition at line 273 of file RawTowerDigitizer.h.
View newest version in sPHENIX GitHub at line 273 of file RawTowerDigitizer.h
Referenced by RawTowerDigitizer(), set_seed(), simple_photon_digitization(), sipm_photon_digitization(), and ~RawTowerDigitizer().
RawTowerGeomContainer* RawTowerDigitizer::m_RawTowerGeom = nullptr private
Definition at line 233 of file RawTowerDigitizer.h.
View newest version in sPHENIX GitHub at line 233 of file RawTowerDigitizer.h
Referenced by CreateNodes(), and process_event().
TowerInfoContainer* RawTowerDigitizer::m_RawTowerInfos = nullptr private
Definition at line 229 of file RawTowerDigitizer.h.
View newest version in sPHENIX GitHub at line 229 of file RawTowerDigitizer.h
Referenced by CreateNodes(), and process_event().
std::string RawTowerDigitizer::m_RawTowerNodePrefix = "RAW" private
Definition at line 239 of file RawTowerDigitizer.h.
View newest version in sPHENIX GitHub at line 239 of file RawTowerDigitizer.h
Referenced by CreateNodes(), get_raw_tower_node_prefix(), and set_raw_tower_node_prefix().
RawTowerContainer* RawTowerDigitizer::m_RawTowers = nullptr private
Definition at line 226 of file RawTowerDigitizer.h.
View newest version in sPHENIX GitHub at line 226 of file RawTowerDigitizer.h
Referenced by CreateNodes(), and process_event().
unsigned int RawTowerDigitizer::m_Seed = 0 private
Definition at line 265 of file RawTowerDigitizer.h.
View newest version in sPHENIX GitHub at line 265 of file RawTowerDigitizer.h
Referenced by get_seed(), RawTowerDigitizer(), and set_seed().
TowerInfoContainer* RawTowerDigitizer::m_SimTowerInfos = nullptr private
Definition at line 228 of file RawTowerDigitizer.h.
View newest version in sPHENIX GitHub at line 228 of file RawTowerDigitizer.h
Referenced by CreateNodes(), and process_event().
std::string RawTowerDigitizer::m_SimTowerNodePrefix = "SIM" private
Definition at line 238 of file RawTowerDigitizer.h.
View newest version in sPHENIX GitHub at line 238 of file RawTowerDigitizer.h
Referenced by CreateNodes(), get_sim_tower_node_prefix(), and set_sim_tower_node_prefix().
RawTowerContainer* RawTowerDigitizer::m_SimTowers = nullptr private
Definition at line 225 of file RawTowerDigitizer.h.
View newest version in sPHENIX GitHub at line 225 of file RawTowerDigitizer.h
Referenced by CreateNodes(), and process_event().
unsigned int RawTowerDigitizer::m_SiPMEffectivePixel = 40000 * 4 private
Definition at line 269 of file RawTowerDigitizer.h.
View newest version in sPHENIX GitHub at line 269 of file RawTowerDigitizer.h
Referenced by get_sipm_effective_pixel(), set_sipm_effective_pixel(), and sipm_photon_digitization().
int RawTowerDigitizer::m_TowerType = -1 private
tower type to act on
Definition at line 263 of file RawTowerDigitizer.h.
View newest version in sPHENIX GitHub at line 263 of file RawTowerDigitizer.h
Referenced by process_event(), and TowerType().
bool RawTowerDigitizer::m_UseConditionsDB = false private
Definition at line 280 of file RawTowerDigitizer.h.
View newest version in sPHENIX GitHub at line 280 of file RawTowerDigitizer.h
Referenced by set_UseConditionsDB().
RawTowerDigitizer::ProcessTowerType RawTowerDigitizer::m_UseTowerInfo = RawTowerDigitizer::ProcessTowerType::kBothTowers private
Definition at line 284 of file RawTowerDigitizer.h.
View newest version in sPHENIX GitHub at line 284 of file RawTowerDigitizer.h
Referenced by CreateNodes(), process_event(), and set_towerinfo().
double RawTowerDigitizer::m_ZeroSuppressionADC = -1000 private
zero suppression in unit of ADC
Definition at line 257 of file RawTowerDigitizer.h.
View newest version in sPHENIX GitHub at line 257 of file RawTowerDigitizer.h
Referenced by get_zero_suppression_ADC(), process_event(), set_zero_suppression_ADC(), simple_photon_digitization(), and sipm_photon_digitization().
bool RawTowerDigitizer::m_ZeroSuppressionFile = false private
zero suppression from file
Definition at line 260 of file RawTowerDigitizer.h.
View newest version in sPHENIX GitHub at line 260 of file RawTowerDigitizer.h
Referenced by process_event(), and set_variable_zero_suppression().
The documentation for this class was generated from the following files:
coresoftware/blob/master/simulation/g4simulation/g4calo/RawTowerDigitizer.h
coresoftware/blob/master/simulation/g4simulation/g4calo/RawTowerDigitizer.cc