Analysis Software: acts/blob/sPHENIX/Tests/UnitTests/Plugins/Sycl/Seeding/SeedFinderSyclTest.cpp File Reference
SeedFinderSyclTest.cpp File Reference
#include "Acts/EventData/SpacePointData.hpp"
#include "Acts/Plugins/Sycl/Seeding/SeedFinder.hpp"
#include "Acts/Plugins/Sycl/Utilities/QueueWrapper.hpp"
#include "Acts/Seeding/BinFinder.hpp"
#include "Acts/Seeding/BinnedSPGroup.hpp"
#include "Acts/Seeding/InternalSeed.hpp"
#include "Acts/Seeding/InternalSpacePoint.hpp"
#include "Acts/Seeding/Seed.hpp"
#include "Acts/Seeding/SeedFilter.hpp"
#include "Acts/Seeding/SeedFinder.hpp"
#include "Acts/Seeding/SeedFinderConfig.hpp"
#include "Acts/Seeding/SpacePointGrid.hpp"
#include "Acts/Utilities/Logger.hpp"
#include <chrono>
#include <cmath>
#include <ctime>
#include <fstream>
#include <iomanip>
#include <iostream>
#include <limits>
#include <memory>
#include <sstream>
#include <string>
#include <boost/type_erasure/any_cast.hpp>
#include "ATLASCuts.hpp"
#include "CommandLineArguments.h"
#include "SpacePoint.hpp"
#include "vecmem/memory/sycl/device_memory_resource.hpp"
#include "vecmem/memory/sycl/host_memory_resource.hpp"
Functions
auto readFile (const std::string &filename) -> std::vector< const SpacePoint * >
template<typename external_spacepoint_t >
auto setupSeedFinderConfiguration () -> Acts::SeedFinderConfig< external_spacepoint_t >
auto setupSeedFinderOptions ()
template<typename external_spacepoint_t >
auto setupSpacePointGridConfig (const Acts::SeedFinderConfig< external_spacepoint_t > &config, const Acts::SeedFinderOptions &options) -> std::pair< Acts::SpacePointGridConfig, Acts::SpacePointGridOptions >
auto main (int argc, char **argv) -> int
Function Documentation
auto main (int argc, char ** argv) -> int
Definition at line 139 of file SeedFinderSyclTest.cpp.
View newest version in sPHENIX GitHub at line 139 of file SeedFinderSyclTest.cpp
References CommandLineArguments::allgroup, filter::config, covariance(), Acts::SeedFinder< external_spacepoint_t, platform_t >::createSeedsForGroup(), CommandLineArguments::csvFormat, CommandLineArguments::deviceName, Acts::getDefaultLogger(), Acts::Sycl::QueueWrapper::getQueue(), grid(), CommandLineArguments::groups, i, Acts::Logging::INFO, CommandLineArguments::inpFileExists, CommandLineArguments::inpFileName, CommandLineArguments::matches, testing::internal::move(), CommandLineArguments::onlyGpu, ckf::options, CommandLineArguments::parse(), position, readFile(), Acts::SpacePointData::resize(), S(), seed, setupSeedFinderOptions(), setupSpacePointGridConfig(), Acts::BinnedSPGroup< external_spacepoint_t >::size(), filter::state, to_string(), SpacePoint::varianceR, SpacePoint::varianceZ, Acts::Logging::WARNING, SpacePoint::x, SpacePoint::y, and SpacePoint::z.
auto readFile (const std::string & filename) -> std::vector<const SpacePoint*>
Definition at line 44 of file SeedFinderSyclTest.cpp.
View newest version in sPHENIX GitHub at line 44 of file SeedFinderSyclTest.cpp
References Acts::Test::cov, filename, train_ambiguity_solver::id, layer, line, physmon_track_finding_ttbar::r, ambiguity_solver_full_chain::x, y, and physmon_track_finding_ttbar::z.
template<typename external_spacepoint_t > auto setupSeedFinderConfiguration () -> Acts::SeedFinderConfig<external_spacepoint_t>
Definition at line 87 of file SeedFinderSyclTest.cpp.
View newest version in sPHENIX GitHub at line 87 of file SeedFinderSyclTest.cpp
References Acts::SeedFinderConfig< SpacePoint >::collisionRegionMax, Acts::SeedFinderConfig< SpacePoint >::collisionRegionMin, filter::config, Acts::SeedFinderConfig< SpacePoint >::cotThetaMax, Acts::SeedFinderConfig< SpacePoint >::deltaRMax, Acts::SeedFinderConfig< SpacePoint >::deltaRMaxBottomSP, Acts::SeedFinderConfig< SpacePoint >::deltaRMaxTopSP, Acts::SeedFinderConfig< SpacePoint >::deltaRMin, Acts::SeedFinderConfig< SpacePoint >::deltaRMinBottomSP, Acts::SeedFinderConfig< SpacePoint >::deltaRMinTopSP, Acts::SeedFinderConfig< SpacePoint >::impactMax, Acts::SeedFinderConfig< SpacePoint >::maxSeedsPerSpM, Acts::SeedFinderConfig< SpacePoint >::minPt, Acts::SeedFinderConfig< SpacePoint >::nAvgTrplPerSpBLimit, Acts::SeedFinderConfig< SpacePoint >::nTrplPerSpBLimit, Acts::SeedFinderConfig< SpacePoint >::rMax, Acts::SeedFinderConfig< SpacePoint >::sigmaScattering, Acts::SeedFinderConfig< SpacePoint >::zMax, and Acts::SeedFinderConfig< SpacePoint >::zMin.
auto setupSeedFinderOptions ()
Definition at line 114 of file SeedFinderSyclTest.cpp.
View newest version in sPHENIX GitHub at line 114 of file SeedFinderSyclTest.cpp
References Acts::SeedFinderOptions::beamPos, Acts::SeedFinderOptions::bFieldInZ, and ckf::options.
Referenced by main().
template<typename external_spacepoint_t > auto setupSpacePointGridConfig (const Acts::SeedFinderConfig< external_spacepoint_t > & config, const Acts::SeedFinderOptions & options) -> std::pair<Acts::SpacePointGridConfig, Acts::SpacePointGridOptions>
Definition at line 122 of file SeedFinderSyclTest.cpp.
View newest version in sPHENIX GitHub at line 122 of file SeedFinderSyclTest.cpp
References Acts::SpacePointGridOptions::bFieldInZ, filter::config, Acts::SpacePointGridConfig::minPt, and ckf::options.
Referenced by main().