Analysis Software: tutorials/blob/master/materialscan/matscan.C File Reference
matscan.C File Reference
#include <fun4all/Fun4AllServer.h>
#include <g4main/PHG4Reco.h>
Namespaces
namespace MATSCAN
Macros
#define MACRO_MATSCAN_C
Functions
void matscan ()
void set_phimin (const float f)
void set_phispan (const float f)
void set_phibins (const int i)
void set_thetamin (const float f)
void set_thetaspan (const float f)
void set_thetabins (const int i)
void print ()
void setmidrap ()
void set_thetascan ()
Variables
float MATSCAN::phimin = 0.
float MATSCAN::phispan = 360.
int MATSCAN::phibins = 10
float MATSCAN::thetamin = 0.1
float MATSCAN::thetaspan = 360.
int MATSCAN::thetabins = 1
Macro Definition Documentation
#define MACRO_MATSCAN_C
Definition at line 2 of file matscan.C.
View newest version in sPHENIX GitHub at line 2 of file matscan.C
Function Documentation
void matscan ()
Definition at line 31 of file matscan.C.
View newest version in sPHENIX GitHub at line 31 of file matscan.C
References PHG4Reco::ApplyCommand(), runCondor_beamspot::cmd, g4, Fun4AllServer::getSubsysReco(), PHG4Reco::InitRun(), Fun4AllServer::instance(), MATSCAN::phibins, MATSCAN::phimin, MATSCAN::phispan, MATSCAN::thetabins, MATSCAN::thetamin, MATSCAN::thetaspan, and Fun4AllServer::topNode().
void print ()
Definition at line 81 of file matscan.C.
View newest version in sPHENIX GitHub at line 81 of file matscan.C
References MATSCAN::phibins, MATSCAN::phimin, MATSCAN::phispan, MATSCAN::thetabins, MATSCAN::thetamin, and MATSCAN::thetaspan.
void set_phibins (const int i)
Definition at line 61 of file matscan.C.
View newest version in sPHENIX GitHub at line 61 of file matscan.C
References i, and MATSCAN::phibins.
Referenced by set_thetascan(), and setmidrap().
void set_phimin (const float f)
Definition at line 51 of file matscan.C.
View newest version in sPHENIX GitHub at line 51 of file matscan.C
References f, and MATSCAN::phimin.
Referenced by set_thetascan(), and setmidrap().
void set_phispan (const float f)
Definition at line 56 of file matscan.C.
View newest version in sPHENIX GitHub at line 56 of file matscan.C
References f, and MATSCAN::phispan.
Referenced by set_thetascan(), and setmidrap().
void set_thetabins (const int i)
Definition at line 76 of file matscan.C.
View newest version in sPHENIX GitHub at line 76 of file matscan.C
References i, and MATSCAN::thetabins.
Referenced by set_thetascan(), and setmidrap().
void set_thetamin (const float f)
Definition at line 66 of file matscan.C.
View newest version in sPHENIX GitHub at line 66 of file matscan.C
References f, and MATSCAN::thetamin.
Referenced by set_thetascan(), and setmidrap().
void set_thetascan ()
Definition at line 103 of file matscan.C.
View newest version in sPHENIX GitHub at line 103 of file matscan.C
References set_phibins(), set_phimin(), set_phispan(), set_thetabins(), set_thetamin(), and set_thetaspan().
void set_thetaspan (const float f)
Definition at line 71 of file matscan.C.
View newest version in sPHENIX GitHub at line 71 of file matscan.C
References f, and MATSCAN::thetaspan.
Referenced by set_thetascan(), and setmidrap().
void setmidrap ()
Definition at line 93 of file matscan.C.
View newest version in sPHENIX GitHub at line 93 of file matscan.C
References set_phibins(), set_phimin(), set_phispan(), set_thetabins(), set_thetamin(), and set_thetaspan().