Analysis Software: Acts::Neutral Struct Reference
Acts::Neutral Struct Reference
Charge interpretation for track parameters
Charge and momentum interpretation for neutral particles.
#include <acts/blob/sPHENIX/Core/include/Acts/EventData/Charge.hpp>
Public Member Functions
constexpr Neutral ()=default
constexpr Neutral (float absQ) noexcept
constexpr float absQ () const noexcept
template<typename T >
constexpr auto extractCharge (T) const noexcept
template<typename T >
constexpr auto extractMomentum (T qOverP) const noexcept
template<typename P , typename Q >
constexpr auto qOverP (P momentum, Q signedQ) const noexcept
Friends
constexpr bool operator== (Neutral, Neutral) noexcept
Detailed Description
Charge and momentum interpretation for neutral particles.
Definition at line 55 of file Charge.hpp.
View newest version in sPHENIX GitHub at line 55 of file Charge.hpp
Constructor & Destructor Documentation
constexpr Acts::Neutral::Neutral () default
constexpr Acts::Neutral::Neutral (float absQ) inline noexcept
Construct and verify the input charge magnitude (in debug builds).
This constructor is only provided to allow consistent construction.
Definition at line 63 of file Charge.hpp.
View newest version in sPHENIX GitHub at line 63 of file Charge.hpp
References absQ(), and assert.
Member Function Documentation
constexpr float Acts::Neutral::absQ () const inline noexcept
Definition at line 68 of file Charge.hpp.
View newest version in sPHENIX GitHub at line 68 of file Charge.hpp
Referenced by Neutral().
template<typename T > constexpr auto Acts::Neutral::extractCharge (T) const inline noexcept
Definition at line 71 of file Charge.hpp.
View newest version in sPHENIX GitHub at line 71 of file Charge.hpp
Referenced by BOOST_AUTO_TEST_CASE().
template<typename T > constexpr auto Acts::Neutral::extractMomentum (T qOverP) const inline noexcept
Definition at line 76 of file Charge.hpp.
View newest version in sPHENIX GitHub at line 76 of file Charge.hpp
References assert, and qOverP().
Referenced by BOOST_AUTO_TEST_CASE().
template<typename P , typename Q > constexpr auto Acts::Neutral::qOverP (P momentum, Q signedQ) const inline noexcept
Definition at line 82 of file Charge.hpp.
View newest version in sPHENIX GitHub at line 82 of file Charge.hpp
References assert, and momentum.
Referenced by extractMomentum().
Friends And Related Function Documentation
constexpr bool operator== (Neutral , Neutral) friend
Compare for equality.
This is always true as Neutral has no internal state. Must be available to provide a consistent interface.
Definition at line 92 of file Charge.hpp.
View newest version in sPHENIX GitHub at line 92 of file Charge.hpp
The documentation for this struct was generated from the following file:
acts/blob/sPHENIX/Core/include/Acts/EventData/Charge.hpp