Analysis Software: Brick Class Reference
Brick Class Reference
#include <JETSCAPE/blob/main/src/hydro/Brick.h>
Public Member Functions
Brick ()
~Brick ()
void InitializeHydro (Parameter parameter_list)
void EvolveHydro ()
void GetHydroInfo (Jetscape::real t, Jetscape::real x, Jetscape::real y, Jetscape::real z, std::unique_ptr< FluidCellInfo > &fluid_cell_info_ptr)
void GetHyperSurface (Jetscape::real T_cut, SurfaceCellInfo *surface_list_ptr)
void InitTask ()
Public Member Functions inherited from Jetscape::FluidDynamics
FluidDynamics ()
virtual ~FluidDynamics ()
virtual void Init ()
virtual void Exec ()
virtual void Clear ()
Parameter & GetParameterList ()
virtual void CollectHeader (weak_ptr< JetScapeWriter > w)
virtual double GetEventPlaneAngle ()
virtual void GetTemperature (double t, double x, double y, double z, double &mT)
virtual void GetHydroCell (double t, double x, double y, double z, std::unique_ptr< FluidCellInfo > &fCell)
int GetHydroStatus () const
void StoreHydroEvolutionHistory (std::unique_ptr< FluidCellInfo > &fluid_cell_info_ptr)
void clear_up_evolution_data ()
void GetHydroStartTime (double &tau0)
Jetscape::real GetHydroEndTime () const
Jetscape::real GetHydroFreezeOutTemperature () const
void PrintFluidCellInformation (FluidCellInfo *fluid_cell_info_ptr)
void FindAConstantTemperatureSurface (Jetscape::real T_sw, std::vector< SurfaceCellInfo > &surface_cells)
virtual Jetscape::real GetEnergyDensity (Jetscape::real time, Jetscape::real x, Jetscape::real y, Jetscape::real z)
virtual Jetscape::real GetEntropyDensity (Jetscape::real time, Jetscape::real x, Jetscape::real y, Jetscape::real z)
virtual Jetscape::real GetTemperature (Jetscape::real time, Jetscape::real x, Jetscape::real y, Jetscape::real z)
virtual Jetscape::real GetQgpFraction (Jetscape::real time, Jetscape::real x, Jetscape::real y, Jetscape::real z)
virtual void add_a_liquefier (std::shared_ptr< LiquefierBase > new_liquefier)
void get_source_term (Jetscape::real tau, Jetscape::real x, Jetscape::real y, Jetscape::real eta, std::array< Jetscape::real, 4 > jmu) const
virtual void UpdateEnergyDeposit (int t, double edop)
slots for "jet" signals (future)
virtual void GetEnergyDensity (int t, double &edensity)
slots for "jet" signals (future)
const EvolutionHistory & get_bulk_info () const
Public Member Functions inherited from Jetscape::JetScapeModuleBase
JetScapeModuleBase ()
JetScapeModuleBase (string m_name)
virtual ~JetScapeModuleBase ()
void SetXMLMainFileName (string m_name)
string GetXMLMainFileName ()
void SetXMLUserFileName (string m_name)
string GetXMLUserFileName ()
shared_ptr< std::mt19937 > GetMt19937Generator ()
tinyxml2::XMLElement * GetXMLElement (std::initializer_list< const char * > path, bool isRequired=true)
std::string GetXMLElementText (std::initializer_list< const char * > path, bool isRequired=true)
int GetXMLElementInt (std::initializer_list< const char * > path, bool isRequired=true)
double GetXMLElementDouble (std::initializer_list< const char * > path, bool isRequired=true)
Public Member Functions inherited from Jetscape::JetScapeTask
JetScapeTask ()
virtual ~JetScapeTask ()
virtual void Finish ()
virtual void ExecuteTasks ()
virtual void ExecuteTask ()
virtual void InitTasks ()
virtual void ClearTasks ()
virtual void ClearTask ()
virtual void FinishTask ()
virtual void FinishTasks ()
virtual void WriteTasks (weak_ptr< JetScapeWriter > w)
virtual void WriteTask (weak_ptr< JetScapeWriter > w)
virtual void CollectHeaders (weak_ptr< JetScapeWriter > w)
virtual void Add (shared_ptr< JetScapeTask > m_tasks)
virtual const int GetMyTaskNumber () const
const vector< shared_ptr
< JetScapeTask > > GetTaskList () const
shared_ptr< JetScapeTask > GetTaskAt (int i)
void EraseTaskLast ()
void EraseTaskAt (int i)
void ResizeTaskList (int i)
void ClearTaskList ()
int GetNumberOfTasks ()
const bool GetActive () const
void SetActive (bool m_active_exec)
void SetId (string m_id)
const string GetId () const
const shared_ptr
< JetScapeModuleMutex > GetMutex () const
void SetMutex (shared_ptr< JetScapeModuleMutex > m_mutex)
Public Member Functions inherited from sigslot::has_slots< sigslot::multi_threaded_local >
has_slots ()
has_slots (const has_slots &hs)
void signal_connect (_signal_base< sigslot::multi_threaded_local > *sender)
void signal_disconnect (_signal_base< sigslot::multi_threaded_local > *sender)
virtual ~has_slots ()
void disconnect_all ()
Private Attributes
double T_brick
double brick_L
double start_time
bool bjorken_expansion_on
Static Private Attributes
static RegisterJetScapeModule
< Brick > reg
Additional Inherited Members
Static Public Member Functions inherited from Jetscape::JetScapeModuleBase
static int GetCurrentEvent ()
static void IncrementCurrentEvent ()
Protected Attributes inherited from Jetscape::FluidDynamics
Jetscape::real hydro_tau_0
Jetscape::real hydro_tau_max
Jetscape::real hydro_freeze_out_temperature
HydroStatus hydro_status
std::shared_ptr< InitialState > ini
std::shared_ptr
< PreequilibriumDynamics > pre_eq_ptr
double eta
bool boost_invariant_
Parameter parameter_list
EvolutionHistory bulk_info
std::weak_ptr< LiquefierBase > liquefier_ptr
Detailed Description
Definition at line 23 of file Brick.h.
View newest version in sPHENIX GitHub at line 23 of file Brick.h
Constructor & Destructor Documentation
Brick::Brick ()
Definition at line 32 of file Brick.cc.
View newest version in sPHENIX GitHub at line 32 of file Brick.cc
References bjorken_expansion_on, Jetscape::FluidDynamics::hydro_status, Jetscape::NOT_START, Jetscape::JetScapeTask::SetId(), start_time, T_brick, and VERBOSE.
Brick::~Brick ()
Definition at line 43 of file Brick.cc.
View newest version in sPHENIX GitHub at line 43 of file Brick.cc
References VERBOSE.
Member Function Documentation
void Brick::EvolveHydro () virtual
Default function to evolve the hydrodynamics. It can be overridden by different modules.
Reimplemented from Jetscape::FluidDynamics.
Definition at line 80 of file Brick.cc.
View newest version in sPHENIX GitHub at line 80 of file Brick.cc
References Jetscape::FINISHED, Jetscape::FluidDynamics::hydro_status, Jetscape::FluidDynamics::ini, and VERBOSE.
void Brick::GetHydroInfo (Jetscape::real t, Jetscape::real x, Jetscape::real y, Jetscape::real z, std::unique_ptr< FluidCellInfo > & fluid_cell_info_ptr) virtual
Retrieves the hydro information at a given space-time point. It throws a InvalidSpaceTimeRange message when (t or tau, x, y, z or eta) is out of the evolution history range.
Parameters
time Time or tau coordinate.
x Space coordinate.
y Space coordinate.
z Space or eta coordinate.
fluid_cell_info_ptr A pointer to the FluidCellInfo class.
Reimplemented from Jetscape::FluidDynamics.
Definition at line 86 of file Brick.cc.
View newest version in sPHENIX GitHub at line 86 of file Brick.cc
References bjorken_expansion_on, brick_L, Jetscape::FluidCellInfo::bulk_Pi, Jetscape::FluidCellInfo::energy_density, Jetscape::FluidCellInfo::entropy_density, Jetscape::FINISHED, Jetscape::FluidDynamics::hydro_status, i, j, JSWARN, Jetscape::FluidCellInfo::mu_B, Jetscape::FluidCellInfo::mu_C, Jetscape::FluidCellInfo::mu_S, Jetscape::FluidCellInfo::pi, Jetscape::FluidCellInfo::pressure, Jetscape::FluidCellInfo::qgp_fraction, start_time, T_brick, Jetscape::FluidCellInfo::temperature, Jetscape::FluidCellInfo::vx, Jetscape::FluidCellInfo::vy, and Jetscape::FluidCellInfo::vz.
void Brick::GetHyperSurface (Jetscape::real T_cut, SurfaceCellInfo * surface_list_ptr) inline
Definition at line 46 of file Brick.h.
View newest version in sPHENIX GitHub at line 46 of file Brick.h
void Brick::InitializeHydro (Parameter parameter_list) virtual
Default function to initialize the hydrodynamics. It can be overridden by different modules.
Parameters
parameter_list An object of the class Parameter.
Reimplemented from Jetscape::FluidDynamics.
Definition at line 76 of file Brick.cc.
View newest version in sPHENIX GitHub at line 76 of file Brick.cc
References Jetscape::FluidDynamics::hydro_status, and Jetscape::INITIALIZED.
void Brick::InitTask () virtual
A virtual function to define a default InitTask() function for a JetScapeTask. It can be overridden by different modules/tasks.
Reimplemented from Jetscape::JetScapeTask.
Definition at line 45 of file Brick.cc.
View newest version in sPHENIX GitHub at line 45 of file Brick.cc
References tinyxml2::XMLElement::Attribute(), bjorken_expansion_on, brick_L, Jetscape::FluidDynamics::GetParameterList(), Jetscape::JetScapeModuleBase::GetXMLElement(), Jetscape::JetScapeModuleBase::GetXMLElementDouble(), Jetscape::JetScapeModuleBase::GetXMLElementText(), Jetscape::Parameter::hydro_input_filename, Jetscape::FluidDynamics::hydro_tau_0, JSDEBUG, physmon_simulation::s, start_time, T_brick, and VERBOSE.
Member Data Documentation
bool Brick::bjorken_expansion_on private
Definition at line 30 of file Brick.h.
View newest version in sPHENIX GitHub at line 30 of file Brick.h
Referenced by Brick(), GetHydroInfo(), and InitTask().
double Brick::brick_L private
Definition at line 28 of file Brick.h.
View newest version in sPHENIX GitHub at line 28 of file Brick.h
Referenced by GetHydroInfo(), and InitTask().
RegisterJetScapeModule< Brick > Brick::reg static private
Definition at line 33 of file Brick.h.
View newest version in sPHENIX GitHub at line 33 of file Brick.h
double Brick::start_time private
Definition at line 29 of file Brick.h.
View newest version in sPHENIX GitHub at line 29 of file Brick.h
Referenced by Brick(), GetHydroInfo(), and InitTask().
double Brick::T_brick private
Definition at line 27 of file Brick.h.
View newest version in sPHENIX GitHub at line 27 of file Brick.h
Referenced by Brick(), GetHydroInfo(), and InitTask().
The documentation for this class was generated from the following files:
JETSCAPE/blob/main/src/hydro/Brick.h
JETSCAPE/blob/main/src/hydro/Brick.cc