Analysis Software: FlagSave Class Reference
FlagSave Class Reference
#include <coresoftware/blob/master/offline/framework/ffaobjects/FlagSave.h>
Public Member Functions
~FlagSave () override
dtor
void Reset () override
Clear Flag.
void identify (std::ostream &os=std::cout) const override
int isValid () const override
isValid returns non zero if object contains valid data
virtual int FillFromPHFlag (const PHFlag *, const bool)
virtual int PutFlagsBack (PHFlag *, const bool)
Public Member Functions inherited from PHObject
PHObject ()
ctor
~PHObject () override
dtor
virtual PHObject * CloneMe () const
Virtual copy constructor.
virtual PHObject * clone () const final
PHObject * Clone (const char *newname="") const final
void Copy (TObject &object) const final
virtual int Integrate () const
virtual int Integrate (PHObject *)
virtual void CopyFrom (const PHObject *obj)
Detailed Description
Definition at line 12 of file FlagSave.h.
View newest version in sPHENIX GitHub at line 12 of file FlagSave.h
Constructor & Destructor Documentation
FlagSave::~FlagSave () inline override
dtor
Definition at line 16 of file FlagSave.h.
View newest version in sPHENIX GitHub at line 16 of file FlagSave.h
Member Function Documentation
virtual int FlagSave::FillFromPHFlag (const PHFlag * , const bool) inline virtual
Flags are read during InitRun() and written during End() Fills DST object with flags, if clearold is set, old flags from previous files which were deleted will not be saved
Reimplemented in FlagSavev1.
Definition at line 44 of file FlagSave.h.
View newest version in sPHENIX GitHub at line 44 of file FlagSave.h
Referenced by FlagHandler::End().
void FlagSave::identify (std::ostream & os = std::cout) const inline override virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from PHObject.
Reimplemented in FlagSavev1.
Definition at line 28 of file FlagSave.h.
View newest version in sPHENIX GitHub at line 28 of file FlagSave.h
References os.
Referenced by FlagHandler::End(), and DumpFlagSave::process_Node().
int FlagSave::isValid () const inline override virtual
isValid returns non zero if object contains valid data
Reimplemented from PHObject.
Reimplemented in FlagSavev1.
Definition at line 35 of file FlagSave.h.
View newest version in sPHENIX GitHub at line 35 of file FlagSave.h
References PHWHERE.
virtual int FlagSave::PutFlagsBack (PHFlag * , const bool) inline virtual
Read back flags from the DST, if overwrite is set: flags from DST object will overwrite flag values set in the macro
Reimplemented in FlagSavev1.
Definition at line 47 of file FlagSave.h.
View newest version in sPHENIX GitHub at line 47 of file FlagSave.h
Referenced by FlagHandler::InitRun().
void FlagSave::Reset () inline override virtual
Clear Flag.
Reimplemented from PHObject.
Reimplemented in FlagSavev1.
Definition at line 19 of file FlagSave.h.
View newest version in sPHENIX GitHub at line 19 of file FlagSave.h
References PHWHERE.
The documentation for this class was generated from the following file:
coresoftware/blob/master/offline/framework/ffaobjects/FlagSave.h