Analysis Software: release Namespace Reference
release Namespace Reference
Classes
class Commit
Functions
def get_repo
def get_current_version
def evaluate_version_bump
def generate_changelog
def markdown_changelog
def update_zenodo
def update_citation
def make_sync
def get_parsed_commit_range
def make_release
def get_release_branch_version
def get_tag_hash
def get_merge_commit_sha
def get_tag
def get_release
def pr_action
Variables
git sh.git
int RETRY_COUNT 10
float RETRY_INTERVAL 0.5
_default_parser angular_parser
tuple app typer.Typer()
Function Documentation
def release.evaluate_version_bump (commits)
Definition at line 76 of file release.py.
View newest version in sPHENIX GitHub at line 76 of file release.py
References print().
Referenced by make_release(), and pr_action().
def release.generate_changelog (commits, commit_parser = _default_parser, dict)
Modified from: https://github.com/relekang/python-semantic-release/blob/48972fb761ed9b0fb376fa3ad7028d65ff407ee6/semantic_release/history/logs.py#L78
Definition at line 104 of file release.py.
View newest version in sPHENIX GitHub at line 104 of file release.py
References print(), and test_detectors.upper.
Referenced by make_release(), and pr_action().
def release.get_current_version ()
Definition at line 46 of file release.py.
View newest version in sPHENIX GitHub at line 46 of file release.py
def release.get_merge_commit_sha (pr)
Definition at line 334 of file release.py.
View newest version in sPHENIX GitHub at line 334 of file release.py
Referenced by pr_action().
def release.get_parsed_commit_range (start)
Definition at line 178 of file release.py.
View newest version in sPHENIX GitHub at line 178 of file release.py
References _default_parser, make_release(), and print().
Referenced by make_release(), and pr_action().
def release.get_release (tag)
Definition at line 354 of file release.py.
View newest version in sPHENIX GitHub at line 354 of file release.py
References pr_action().
Referenced by pr_action().
def release.get_release_branch_version (repo)
Definition at line 318 of file release.py.
View newest version in sPHENIX GitHub at line 318 of file release.py
Referenced by make_release(), and pr_action().
def release.get_repo ()
Definition at line 35 of file release.py.
View newest version in sPHENIX GitHub at line 35 of file release.py
Referenced by make_release().
def release.get_tag (tag)
Definition at line 347 of file release.py.
View newest version in sPHENIX GitHub at line 347 of file release.py
Referenced by pr_action().
def release.get_tag_hash (tag)
Definition at line 327 of file release.py.
View newest version in sPHENIX GitHub at line 327 of file release.py
Referenced by pr_action().
def release.make_release (token)
Definition at line 229 of file release.py.
View newest version in sPHENIX GitHub at line 229 of file release.py
References evaluate_version_bump(), generate_changelog(), get_parsed_commit_range(), get_release_branch_version(), get_repo(), git, markdown_changelog(), print(), str, update_citation(), and update_zenodo().
Referenced by get_parsed_commit_range().
def release.make_sync (fn)
Definition at line 165 of file release.py.
View newest version in sPHENIX GitHub at line 165 of file release.py
def release.markdown_changelog (version)
Definition at line 135 of file release.py.
View newest version in sPHENIX GitHub at line 135 of file release.py
References material_mapping_optimisation.format.
Referenced by make_release(), and pr_action().
def release.pr_action (fail)
Definition at line 369 of file release.py.
View newest version in sPHENIX GitHub at line 369 of file release.py
References app, evaluate_version_bump(), generate_changelog(), get_merge_commit_sha(), get_parsed_commit_range(), get_release(), get_release_branch_version(), get_tag(), get_tag_hash(), markdown_changelog(), and print().
Referenced by get_release().
def release.update_citation (citation_file)
Definition at line 156 of file release.py.
View newest version in sPHENIX GitHub at line 156 of file release.py
Referenced by make_release().
def release.update_zenodo (zenodo_file)
Definition at line 149 of file release.py.
View newest version in sPHENIX GitHub at line 149 of file release.py
Referenced by make_release().
Variable Documentation
release._default_parser angular_parser
Definition at line 72 of file release.py.
View newest version in sPHENIX GitHub at line 72 of file release.py
Referenced by get_parsed_commit_range().
tuple release.app typer.Typer()
Definition at line 174 of file release.py.
View newest version in sPHENIX GitHub at line 174 of file release.py
Referenced by eic_bnl_rich.acq(), OnlMonDBodbc.AddRow(), FluidcellStatistic.checkFreezeoutSurface(), OnCalServer.End(), PythiaGun.Exec(), Jetscape::PartonPrinter.Init(), GTL_debug.init_debug(), PythiaGun.InitTask(), epemGun.InitTask(), ActsExamples::SeedingFTFAlgorithm.LayerNumbering(), main(), gzstreambuf.open(), FluidcellStatistic.output_flowvelocity_vs_tau(), pr_action(), and Fun4AllMonitoring.Snapshot().
release.git sh.git
Definition at line 29 of file release.py.
View newest version in sPHENIX GitHub at line 29 of file release.py
Referenced by main(), and make_release().
int release.RETRY_COUNT 10
Definition at line 31 of file release.py.
View newest version in sPHENIX GitHub at line 31 of file release.py
float release.RETRY_INTERVAL 0.5
Definition at line 32 of file release.py.
View newest version in sPHENIX GitHub at line 32 of file release.py