Analysis Software: SvtxTrackSeed_v2 Class Reference
SvtxTrackSeed_v2 Class Reference
#include <coresoftware/blob/master/offline/packages/trackbase_historic/SvtxTrackSeed_v2.h>
Public Member Functions
SvtxTrackSeed_v2 ()
~SvtxTrackSeed_v2 () override
SvtxTrackSeed_v2 (const SvtxTrackSeed_v2 &)
SvtxTrackSeed_v2 & operator= (const SvtxTrackSeed_v2 &seed)
void identify (std::ostream &os=std::cout) const override
void Reset () override
Clear Event.
int isValid () const override
isValid returns non zero if object contains vailid data
void CopyFrom (const TrackSeed &) override
void CopyFrom (TrackSeed *seed) override
PHObject * CloneMe () const override
Virtual copy constructor.
unsigned int get_silicon_seed_index () const override
unsigned int get_tpc_seed_index () const override
short int get_crossing_estimate () const override
void set_silicon_seed_index (const unsigned int index) override
void set_tpc_seed_index (const unsigned int index) override
void set_crossing_estimate (const short int cross) override
Public Member Functions inherited from TrackSeed
~TrackSeed () override=default
void identify (std::ostream &os=std::cout) const override
int isValid () const override
isValid returns non zero if object contains vailid data
PHObject * CloneMe () const override
Virtual copy constructor.
virtual int get_charge () const
virtual float get_px (TrkrClusterContainer *, ActsGeometry *) const
We need access to the first two clusters to get the phi angle right.
virtual float get_py (TrkrClusterContainer *, ActsGeometry *) const
virtual float get_phi (TrkrClusterContainer *, ActsGeometry *) const
virtual float get_phi (std::map< TrkrDefs::cluskey, Acts::Vector3 > &) const
virtual float get_pz () const
virtual float get_x () const
virtual float get_y () const
virtual float get_z () const
virtual float get_qOverR () const
virtual float get_X0 () const
virtual float get_Y0 () const
virtual float get_slope () const
virtual float get_Z0 () const
virtual float get_eta () const
virtual float get_theta () const
virtual float get_pt () const
virtual float get_p () const
virtual short int get_crossing () const
virtual void set_crossing (const short int)
virtual void set_qOverR (const float)
virtual void set_X0 (const float)
virtual void set_Y0 (const float)
virtual void set_slope (const float)
virtual void set_Z0 (const float)
virtual void circleFitByTaubin (TrkrClusterContainer *, ActsGeometry *, uint8_t, uint8_t)
virtual void lineFit (TrkrClusterContainer *, ActsGeometry *, uint8_t, uint8_t)
virtual void circleFitByTaubin (std::map< TrkrDefs::cluskey, Acts::Vector3 > &, uint8_t, uint8_t)
virtual void lineFit (std::map< TrkrDefs::cluskey, Acts::Vector3 > &, uint8_t, uint8_t)
virtual void clear_cluster_keys ()
virtual bool empty_cluster_keys () const
virtual size_t size_cluster_keys () const
virtual void insert_cluster_key (TrkrDefs::cluskey)
virtual size_t erase_cluster_key (TrkrDefs::cluskey)
virtual ConstClusterKeyIter find_cluster_key (TrkrDefs::cluskey) const
virtual ConstClusterKeyIter begin_cluster_keys () const
virtual ConstClusterKeyIter end_cluster_keys () const
virtual ClusterKeyIter begin_cluster_keys ()
virtual ClusterKeyIter find_cluster_keys (unsigned int)
virtual ClusterKeyIter end_cluster_keys ()
virtual unsigned int get_truth_track_id () const
virtual void set_truth_track_id (unsigned int)
virtual void set_num_measurements (int)
virtual unsigned int get_num_measurements () const
virtual bool empty_g4hit_id () const
virtual size_t size_g4hit_id () const
virtual void add_g4hit_id (int, PHG4HitDefs::keytype)
virtual HitIdIter begin_g4hit_id ()
virtual HitIdConstIter begin_g4hit_id () const
virtual HitIdIter find_g4hit_id (int)
virtual HitIdConstIter find_g4hit_id (int) const
virtual HitIdIter end_g4hit_id ()
virtual HitIdConstIter end_g4hit_id () const
virtual size_t remove_g4hit_id (int, PHG4HitDefs::keytype)
virtual size_t remove_g4hit_volume (int)
virtual void clear_g4hit_id ()
virtual const HitIdMap & g4hit_ids () const
Public Member Functions inherited from PHObject
PHObject ()
ctor
~PHObject () override
dtor
virtual PHObject * clone () const final
PHObject * Clone (const char *newname="") const final
void Copy (TObject &object) const final
virtual int Integrate () const
virtual int Integrate (PHObject *)
virtual void CopyFrom (const PHObject *obj)
Private Member Functions
ClassDefOverride (SvtxTrackSeed_v2, 1)
Private Attributes
unsigned int m_silicon_seed = std::numeric_limits<unsigned int>::max()
unsigned int m_tpc_seed = std::numeric_limits<unsigned int>::max()
short int m_crossing_estimate = SHRT_MAX
Additional Inherited Members
Public Types inherited from TrackSeed
typedef std::set
< TrkrDefs::cluskey > ClusterKeySet
typedef
ClusterKeySet::const_iterator ConstClusterKeyIter
typedef ClusterKeySet::iterator ClusterKeyIter
typedef std::map< int,
std::set< PHG4HitDefs::keytype > > HitIdMap
typedef HitIdMap::iterator HitIdIter
typedef HitIdMap::const_iterator HitIdConstIter
Protected Member Functions inherited from TrackSeed
TrackSeed ()
ClassDefOverride (TrackSeed, 1)
Detailed Description
Definition at line 11 of file SvtxTrackSeed_v2.h.
View newest version in sPHENIX GitHub at line 11 of file SvtxTrackSeed_v2.h
Constructor & Destructor Documentation
SvtxTrackSeed_v2::SvtxTrackSeed_v2 ()
Definition at line 3 of file SvtxTrackSeed_v2.cc.
View newest version in sPHENIX GitHub at line 3 of file SvtxTrackSeed_v2.cc
Referenced by CloneMe(), and Reset().
SvtxTrackSeed_v2::~SvtxTrackSeed_v2 () override
Definition at line 15 of file SvtxTrackSeed_v2.cc.
View newest version in sPHENIX GitHub at line 15 of file SvtxTrackSeed_v2.cc
SvtxTrackSeed_v2::SvtxTrackSeed_v2 (const SvtxTrackSeed_v2 & seed)
Definition at line 9 of file SvtxTrackSeed_v2.cc.
View newest version in sPHENIX GitHub at line 9 of file SvtxTrackSeed_v2.cc
References CopyFrom().
Member Function Documentation
SvtxTrackSeed_v2::ClassDefOverride (SvtxTrackSeed_v2 , 1) private
PHObject* SvtxTrackSeed_v2::CloneMe () const inline override virtual
Virtual copy constructor.
Reimplemented from PHObject.
Definition at line 25 of file SvtxTrackSeed_v2.h.
View newest version in sPHENIX GitHub at line 25 of file SvtxTrackSeed_v2.h
References SvtxTrackSeed_v2().
void SvtxTrackSeed_v2::CopyFrom (const TrackSeed & seed) override virtual
Reimplemented from TrackSeed.
Definition at line 18 of file SvtxTrackSeed_v2.cc.
View newest version in sPHENIX GitHub at line 18 of file SvtxTrackSeed_v2.cc
References TrackSeed::CopyFrom(), TrackSeed::get_crossing_estimate(), TrackSeed::get_silicon_seed_index(), TrackSeed::get_tpc_seed_index(), m_crossing_estimate, m_silicon_seed, and m_tpc_seed.
Referenced by operator=(), and SvtxTrackSeed_v2().
void SvtxTrackSeed_v2::CopyFrom (TrackSeed * seed) inline override virtual
Reimplemented from TrackSeed.
Definition at line 24 of file SvtxTrackSeed_v2.h.
View newest version in sPHENIX GitHub at line 24 of file SvtxTrackSeed_v2.h
References CopyFrom().
Referenced by CopyFrom().
short int SvtxTrackSeed_v2::get_crossing_estimate () const inline override virtual
Reimplemented from TrackSeed.
Definition at line 29 of file SvtxTrackSeed_v2.h.
View newest version in sPHENIX GitHub at line 29 of file SvtxTrackSeed_v2.h
References m_crossing_estimate.
unsigned int SvtxTrackSeed_v2::get_silicon_seed_index () const inline override virtual
Reimplemented from TrackSeed.
Definition at line 27 of file SvtxTrackSeed_v2.h.
View newest version in sPHENIX GitHub at line 27 of file SvtxTrackSeed_v2.h
References m_silicon_seed.
unsigned int SvtxTrackSeed_v2::get_tpc_seed_index () const inline override virtual
Reimplemented from TrackSeed.
Definition at line 28 of file SvtxTrackSeed_v2.h.
View newest version in sPHENIX GitHub at line 28 of file SvtxTrackSeed_v2.h
References m_tpc_seed.
void SvtxTrackSeed_v2::identify (std::ostream & os = std::cout) const override virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from PHObject.
Definition at line 28 of file SvtxTrackSeed_v2.cc.
View newest version in sPHENIX GitHub at line 28 of file SvtxTrackSeed_v2.cc
References m_crossing_estimate, m_silicon_seed, and m_tpc_seed.
int SvtxTrackSeed_v2::isValid () const inline override virtual
isValid returns non zero if object contains vailid data
Reimplemented from PHObject.
Definition at line 22 of file SvtxTrackSeed_v2.h.
View newest version in sPHENIX GitHub at line 22 of file SvtxTrackSeed_v2.h
SvtxTrackSeed_v2 & SvtxTrackSeed_v2::operator= (const SvtxTrackSeed_v2 & seed)
Definition at line 12 of file SvtxTrackSeed_v2.cc.
View newest version in sPHENIX GitHub at line 12 of file SvtxTrackSeed_v2.cc
References CopyFrom().
void SvtxTrackSeed_v2::Reset () inline override virtual
Clear Event.
Reimplemented from PHObject.
Definition at line 21 of file SvtxTrackSeed_v2.h.
View newest version in sPHENIX GitHub at line 21 of file SvtxTrackSeed_v2.h
References SvtxTrackSeed_v2().
void SvtxTrackSeed_v2::set_crossing_estimate (const short int cross) inline override virtual
Reimplemented from TrackSeed.
Definition at line 32 of file SvtxTrackSeed_v2.h.
View newest version in sPHENIX GitHub at line 32 of file SvtxTrackSeed_v2.h
References Acts::VectorHelpers::cross(), and m_crossing_estimate.
void SvtxTrackSeed_v2::set_silicon_seed_index (const unsigned int index) inline override virtual
Reimplemented from TrackSeed.
Definition at line 30 of file SvtxTrackSeed_v2.h.
View newest version in sPHENIX GitHub at line 30 of file SvtxTrackSeed_v2.h
References index, and m_silicon_seed.
void SvtxTrackSeed_v2::set_tpc_seed_index (const unsigned int index) inline override virtual
Reimplemented from TrackSeed.
Definition at line 31 of file SvtxTrackSeed_v2.h.
View newest version in sPHENIX GitHub at line 31 of file SvtxTrackSeed_v2.h
References index, and m_tpc_seed.
Member Data Documentation
short int SvtxTrackSeed_v2::m_crossing_estimate = SHRT_MAX private
Definition at line 38 of file SvtxTrackSeed_v2.h.
View newest version in sPHENIX GitHub at line 38 of file SvtxTrackSeed_v2.h
Referenced by CopyFrom(), get_crossing_estimate(), identify(), and set_crossing_estimate().
unsigned int SvtxTrackSeed_v2::m_silicon_seed = std::numeric_limits<unsigned int>::max() private
Definition at line 36 of file SvtxTrackSeed_v2.h.
View newest version in sPHENIX GitHub at line 36 of file SvtxTrackSeed_v2.h
Referenced by CopyFrom(), get_silicon_seed_index(), identify(), and set_silicon_seed_index().
unsigned int SvtxTrackSeed_v2::m_tpc_seed = std::numeric_limits<unsigned int>::max() private
Definition at line 37 of file SvtxTrackSeed_v2.h.
View newest version in sPHENIX GitHub at line 37 of file SvtxTrackSeed_v2.h
Referenced by CopyFrom(), get_tpc_seed_index(), identify(), and set_tpc_seed_index().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/trackbase_historic/SvtxTrackSeed_v2.h
coresoftware/blob/master/offline/packages/trackbase_historic/SvtxTrackSeed_v2.cc