Analysis Software: acts/blob/sPHENIX/Examples/Run/Generators/Pythia8/Pythia8.cpp File Reference
Pythia8.cpp File Reference
#include "ActsExamples/Framework/RandomNumbers.hpp"
#include "ActsExamples/Framework/Sequencer.hpp"
#include "ActsExamples/Io/Csv/CsvParticleWriter.hpp"
#include "ActsExamples/Io/Root/RootParticleWriter.hpp"
#include "ActsExamples/Options/CommonOptions.hpp"
#include "ActsExamples/Options/Pythia8Options.hpp"
#include "ActsExamples/Printers/ParticlesPrinter.hpp"
#include "ActsExamples/TruthTracking/ParticleSelector.hpp"
#include "ActsExamples/Utilities/Paths.hpp"
#include <Acts/Definitions/Units.hpp>
#include <cstdlib>
#include <memory>
Functions
int main (int argc, char *argv[])
Function Documentation
int main (int argc, char * argv[])
Definition at line 26 of file Pythia8.cpp.
View newest version in sPHENIX GitHub at line 26 of file Pythia8.cpp
References ActsExamples::Sequencer::addAlgorithm(), ActsExamples::Options::addOutputOptions(), ActsExamples::Options::addPythia8Options(), ActsExamples::Options::addRandomNumbersOptions(), ActsExamples::Sequencer::addReader(), ActsExamples::Options::addSequencerOptions(), ActsExamples::Sequencer::addWriter(), Acts::Logging::DEBUG, ActsExamples::ensureWritableDirectory(), ActsExamples::RootParticleWriter::Config::filePath, ActsExamples::ParticlesPrinter::Config::inputParticles, ActsExamples::RootParticleWriter::Config::inputParticles, ActsExamples::CsvParticleWriter::Config::inputParticles, ActsExamples::joinPaths(), telescope_simulation::logLevel, ActsExamples::Options::makeDefaultOptions(), outputDir, ActsExamples::CsvParticleWriter::Config::outputDir, ActsExamples::CsvParticleWriter::Config::outputStem, ActsExamples::Options::parse(), print(), ActsExamples::Options::readLogLevel(), ActsExamples::Options::readPythia8Options(), ActsExamples::Options::readRandomNumbersConfig(), ActsExamples::Options::readSequencerConfig(), physmon_simulation::rnd, ActsExamples::Sequencer::run(), and Acts::Logging::VERBOSE.