Analysis Software: Acts::PrimitivesView3DTest Namespace Reference
Acts::PrimitivesView3DTest Namespace Reference
Functions
static std::string run (IVisualization3D &helper)
Variables
auto identity = Transform3::Identity()
auto rectangle = std::make_shared<RectangleBounds>(10., 10.)
auto plane = Surface::makeShared<PlaneSurface>(identity, rectangle)
GeometryContext gctx = GeometryContext()
Function Documentation
static std::string Acts::PrimitivesView3DTest::run (IVisualization3D & helper) inline static
Helper method to visualize all types of surfaces
Parameters
helper The visualization helper
Returns
an overall string including all written output
Definition at line 42 of file PrimitivesView3DBase.hpp.
View newest version in sPHENIX GitHub at line 42 of file PrimitivesView3DBase.hpp
References Acts::IVisualization3D::clear(), Acts::Test::cov, Acts::GeometryView3D::drawArrowBackward(), Acts::GeometryView3D::drawArrowForward(), Acts::GeometryView3D::drawArrowsBoth(), Acts::EventDataView3D::drawCovarianceAngular(), Acts::EventDataView3D::drawCovarianceCartesian(), Acts::GeometryView3D::drawSegment(), Acts::GeometryView3D::drawSurface(), end, gctx, Acts::ViewConfig::lineThickness, Acts::Test::origin(), plane, start, and Acts::IVisualization3D::write().
Referenced by Acts::Test::BOOST_AUTO_TEST_CASE().
Variable Documentation
GeometryContext Acts::PrimitivesView3DTest::gctx = GeometryContext()
Definition at line 35 of file PrimitivesView3DBase.hpp.
View newest version in sPHENIX GitHub at line 35 of file PrimitivesView3DBase.hpp
Referenced by run().
auto Acts::PrimitivesView3DTest::identity = Transform3::Identity()
Definition at line 30 of file PrimitivesView3DBase.hpp.
View newest version in sPHENIX GitHub at line 30 of file PrimitivesView3DBase.hpp
Referenced by Acts::Test::BOOST_AUTO_TEST_CASE(), MakeMilleFiles::getGlobalVtxDerivativesXY(), Acts::VolumeView3DTest::run(), Acts::SurfaceView3DTest::run(), and Acts::EventDataView3DTest::testBoundTrackParameters().
auto Acts::PrimitivesView3DTest::plane = Surface::makeShared<PlaneSurface>(identity, rectangle)
Definition at line 32 of file PrimitivesView3DBase.hpp.
View newest version in sPHENIX GitHub at line 32 of file PrimitivesView3DBase.hpp
Referenced by Acts::Test::BOOST_AUTO_TEST_CASE(), genfit::KalmanFitterInfo::checkConsistency(), checkErrorPropagation(), checkSetGetPosMom(), checkStopAtBoundary(), compareForthBackExtrapolation(), compareForthBackJacNoise(), genfit::GblFitter::constructGblInfo(), genfit::MeasurementCreator::create(), Acts::LayerArrayCreator::createNavigationSurface(), genfit::RKTrackRep::extrapolateBy(), genfit::RKTrackRep::extrapolateToCone(), genfit::RKTrackRep::extrapolateToCylinder(), genfit::RKTrackRep::extrapolateToLine(), genfit::RKTrackRep::extrapolateToPlane(), genfit::RKTrackRep::extrapolateToSphere(), genfit::RKTrackRep::extrapToPoint(), genfit::KalmanFitterInfo::getResidual(), PHGenFit::PlanarMeasurement::init(), main(), genfit::KalmanFitterRefTrack::prepareTrack(), genfit::KalmanFitter::processTrackPoint(), genfit::GFGbl::processTrackWithRep(), run(), Acts::SurfaceView3DTest::run(), genfit::StateOnPlane::setPlane(), genfit::AbsFitterInfo::setPlane(), genfit::RKTrackRep::setPosMom(), genfit::StateOnPlane::setStatePlane(), genfit::GblFitter::sortHits(), Acts::EventDataView3DTest::testBoundTrackParameters(), and PHGenFit::Track::updateOneMeasurementKalman().
auto Acts::PrimitivesView3DTest::rectangle = std::make_shared<RectangleBounds>(10., 10.)
Definition at line 31 of file PrimitivesView3DBase.hpp.
View newest version in sPHENIX GitHub at line 31 of file PrimitivesView3DBase.hpp
Referenced by Acts::Test::BOOST_AUTO_TEST_CASE(), BOOST_AUTO_TEST_CASE(), ActsFatras::PlanarSurfaceTestBeds::operator()(), Acts::SurfaceView3DTest::run(), and Acts::EventDataView3DTest::testBoundTrackParameters().