Analysis Software: QAG4Util Namespace Reference
QAG4Util Namespace Reference
Functions
template<class T >
constexpr T square (T x)
square
template<class T >
constexpr T get_r (T x, T y)
radius
template<class T >
const T delta_phi (T phi1, T phi2)
angle difference between [-pi, pi[
template<float(PHG4Hit::*)(int) const accessor>
float interpolate (std::set< PHG4Hit * > hits, float rextrap)
calculate the best average of member function called on all members in collection, extrapolated at a given radius
Function Documentation
template<class T > const T QAG4Util::delta_phi (T phi1, T phi2) inline
angle difference between [-pi, pi[
Definition at line 33 of file QAUtil.h.
View newest version in sPHENIX GitHub at line 33 of file QAUtil.h
References out.
Referenced by QAG4SimulationIntt::evaluate_clusters(), QAG4SimulationMvtx::evaluate_clusters(), and QAG4SimulationTpc::evaluate_clusters().
template<class T > constexpr T QAG4Util::get_r (T x, T y) inline
radius
Definition at line 26 of file QAUtil.h.
View newest version in sPHENIX GitHub at line 26 of file QAUtil.h
References square().
Referenced by TrackEvaluation::add_trk_information(), TrackEvaluation::add_trk_information_micromegas(), TrackEvaluation::add_truth_information(), TrackEvaluation::add_truth_information_micromegas(), AnalyzeResiduals(), CylinderGeomMicromegas::check_radius(), PHG4MicromegasDetector::construct_micromegas(), TrackEvaluation::create_cluster(), QAG4SimulationMvtx::evaluate_clusters(), QAG4SimulationIntt::evaluate_clusters(), QAG4SimulationTpc::evaluate_clusters(), DSTEmulator::evaluate_tracks(), TrackEvaluation::evaluate_tracks(), ActsAlignmentStates::fillAlignmentStateMap(), TpcDirectLaserReconstruction::get_cell_index(), TpcSpaceChargeReconstruction::get_cell_index(), PHTpcResiduals::getCell(), PHTpcCentralMembraneMatcher::InitRun(), interpolate(), MakeActsGeometry::makeMmMapPairs(), PHG4TpcPadPlaneReadout::MapToPadPlane(), QAG4SimulationDistortions::process_event(), PHMicromegasTpcTrackMatching::process_event(), PHTpcCentralMembraneMatcher::process_event(), TpcDirectLaserReconstruction::process_track(), TpcSpaceChargeReconstruction::process_track(), PHTpcResiduals::processTrack(), and SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::ClustInfo::SetInfo().
template<float(PHG4Hit::*)(int) const accessor> float QAG4Util::interpolate (std::set< PHG4Hit * > hits, float rextrap)
calculate the best average of member function called on all members in collection, extrapolated at a given radius
each hit is weighted by its deposited energy
Definition at line 44 of file QAUtil.h.
View newest version in sPHENIX GitHub at line 44 of file QAUtil.h
References alpha, get_r(), r0, r1, square(), Acts::IntegrationTest::valid(), and x0.
template<class T > constexpr T QAG4Util::square (T x) inline
square
Definition at line 19 of file QAUtil.h.
View newest version in sPHENIX GitHub at line 19 of file QAUtil.h
References ambiguity_solver_full_chain::x.
Referenced by get_r(), and interpolate().