Analysis Software: sPHAnalysis_calo Class Reference
sPHAnalysis_calo Class Reference
#include <analysis/blob/master/EventMix/ana_calo/sPHAnalysis_calo.h>
Public Member Functions
sPHAnalysis_calo (const std::string &name="sPHAnalysis_calo", const std::string &filename="test.root")
virtual ~sPHAnalysis_calo ()
int Init (PHCompositeNode *topNode)
int InitRun (PHCompositeNode *topNode)
int process_event (PHCompositeNode *topNode)
int End (PHCompositeNode *topNode)
Called at the end of all processing.
void set_whattodo (int what)
Public Member Functions inherited from SubsysReco
~SubsysReco () override
virtual int EndRun (const int)
Called at the end of each run.
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
void Print (const std::string &="ALL") const override
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Protected Member Functions
int process_event_test (PHCompositeNode *topNode)
int process_event_data (PHCompositeNode *topNode)
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Protected Member Functions inherited from Fun4AllBase
Fun4AllBase (const std::string &name="NONAME")
Protected Attributes
TFile * OutputNtupleFile
std::string OutputFileName
TNtuple * ntp_notracking
TH1D * h_mult
TH1D * h_ecore
TH1F * h_pedestal [256 *96]
int EventNumber
int _whattodo
TRandom * _rng
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = std::numeric_limits<int>::max() - 10
}
Detailed Description
Definition at line 16 of file sPHAnalysis_calo.h.
View newest version in sPHENIX GitHub at line 16 of file sPHAnalysis_calo.h
Constructor & Destructor Documentation
sPHAnalysis_calo::sPHAnalysis_calo (const std::string & name = "sPHAnalysis_calo", const std::string & filename = "test.root")
Definition at line 45 of file sPHAnalysis_calo.cc.
View newest version in sPHENIX GitHub at line 45 of file sPHAnalysis_calo.cc
References _rng, _whattodo, EventNumber, filename, h_ecore, h_mult, ntp_notracking, OutputFileName, and OutputNtupleFile.
virtual sPHAnalysis_calo::~sPHAnalysis_calo () inline virtual
Definition at line 22 of file sPHAnalysis_calo.h.
View newest version in sPHENIX GitHub at line 22 of file sPHAnalysis_calo.h
Member Function Documentation
int sPHAnalysis_calo::End (PHCompositeNode *) virtual
Called at the end of all processing.
Reimplemented from SubsysReco.
Definition at line 335 of file sPHAnalysis_calo.cc.
View newest version in sPHENIX GitHub at line 335 of file sPHAnalysis_calo.cc
References Fun4AllReturnCodes::EVENT_OK, EventNumber, and OutputNtupleFile.
int sPHAnalysis_calo::Init (PHCompositeNode *) virtual
Called during initialization. Typically this is where you can book histograms, and e.g. register them to Fun4AllServer (so they can be output to file using Fun4AllServer::dumpHistos() method).
Reimplemented from SubsysReco.
Definition at line 59 of file sPHAnalysis_calo.cc.
View newest version in sPHENIX GitHub at line 59 of file sPHAnalysis_calo.cc
References _rng, Fun4AllReturnCodes::EVENT_OK, h_ecore, h_mult, h_pedestal, i, ntp_notracking, OutputFileName, and OutputNtupleFile.
int sPHAnalysis_calo::InitRun (PHCompositeNode *) virtual
Called for first event when run number is known. Typically this is where you may want to fetch data from database, because you know the run number.
Reimplemented from SubsysReco.
Definition at line 84 of file sPHAnalysis_calo.cc.
View newest version in sPHENIX GitHub at line 84 of file sPHAnalysis_calo.cc
References Fun4AllReturnCodes::EVENT_OK.
int sPHAnalysis_calo::process_event (PHCompositeNode *) virtual
Called for each event. This is where you do the real work.
Reimplemented from SubsysReco.
Definition at line 93 of file sPHAnalysis_calo.cc.
View newest version in sPHENIX GitHub at line 93 of file sPHAnalysis_calo.cc
References _whattodo, Fun4AllReturnCodes::ABORTRUN, process_event_data(), and process_event_test().
int sPHAnalysis_calo::process_event_data (PHCompositeNode * topNode) protected
Definition at line 106 of file sPHAnalysis_calo.cc.
View newest version in sPHENIX GitHub at line 106 of file sPHAnalysis_calo.cc
References Fun4AllReturnCodes::ABORTEVENT, channel(), TowerInfoContainer::encode_key(), Fun4AllReturnCodes::EVENT_OK, EventNumber, TowerInfo::get_energy(), TowerInfo::get_time(), TowerInfoContainer::get_tower_at_channel(), TowerInfoContainer::getTowerEtaBin(), TowerInfoContainer::getTowerPhiBin(), h_pedestal, PHCompositeNode::print(), and TowerInfoContainer::size().
Referenced by process_event().
int sPHAnalysis_calo::process_event_test (PHCompositeNode * topNode) protected
Definition at line 136 of file sPHAnalysis_calo.cc.
View newest version in sPHENIX GitHub at line 136 of file sPHAnalysis_calo.cc
References Fun4AllReturnCodes::ABORTEVENT, GlobalVertexMap::begin(), GlobalVertexMap::end(), Fun4AllReturnCodes::EVENT_OK, EventNumber, RawTowerGeom::get_bineta(), RawTowerGeom::get_binphi(), RawTowerGeom::get_center_x(), RawTowerGeom::get_center_y(), RawTowerGeom::get_center_z(), RawCluster::get_ecore(), RawTower::get_energy(), GlobalVertex::get_id(), RawTower::get_key(), RawTowerGeom::get_phi(), RawTowerGeomContainer::get_tower_geometry(), RawCluster::get_x(), RawCluster::get_y(), GlobalVertex::get_z(), RawCluster::get_z(), RawClusterContainer::getClusters(), RawTowerContainer::getTower(), RawTowerContainer::getTowers(), h_ecore, h_mult, i, j, ntp_notracking, PHWHERE, PHCompositeNode::print(), Pt(), RawClusterContainer::size(), and Acts::Test::tmp().
Referenced by process_event().
void sPHAnalysis_calo::set_whattodo (int what) inline
Definition at line 29 of file sPHAnalysis_calo.h.
View newest version in sPHENIX GitHub at line 29 of file sPHAnalysis_calo.h
References _whattodo.
Referenced by rundata().
Member Data Documentation
TRandom* sPHAnalysis_calo::_rng protected
Definition at line 48 of file sPHAnalysis_calo.h.
View newest version in sPHENIX GitHub at line 48 of file sPHAnalysis_calo.h
Referenced by Init(), and sPHAnalysis_calo().
int sPHAnalysis_calo::_whattodo protected
Definition at line 46 of file sPHAnalysis_calo.h.
View newest version in sPHENIX GitHub at line 46 of file sPHAnalysis_calo.h
Referenced by process_event(), set_whattodo(), and sPHAnalysis_calo().
int sPHAnalysis_calo::EventNumber protected
Definition at line 45 of file sPHAnalysis_calo.h.
View newest version in sPHENIX GitHub at line 45 of file sPHAnalysis_calo.h
Referenced by End(), process_event_data(), process_event_test(), and sPHAnalysis_calo().
TH1D* sPHAnalysis_calo::h_ecore protected
Definition at line 41 of file sPHAnalysis_calo.h.
View newest version in sPHENIX GitHub at line 41 of file sPHAnalysis_calo.h
Referenced by Init(), process_event_test(), and sPHAnalysis_calo().
TH1D* sPHAnalysis_calo::h_mult protected
Definition at line 40 of file sPHAnalysis_calo.h.
View newest version in sPHENIX GitHub at line 40 of file sPHAnalysis_calo.h
Referenced by Init(), process_event_test(), and sPHAnalysis_calo().
TH1F* sPHAnalysis_calo::h_pedestal[256 *96] protected
Definition at line 43 of file sPHAnalysis_calo.h.
View newest version in sPHENIX GitHub at line 43 of file sPHAnalysis_calo.h
Referenced by Init(), and process_event_data().
TNtuple* sPHAnalysis_calo::ntp_notracking protected
Definition at line 39 of file sPHAnalysis_calo.h.
View newest version in sPHENIX GitHub at line 39 of file sPHAnalysis_calo.h
Referenced by Init(), process_event_test(), and sPHAnalysis_calo().
std::string sPHAnalysis_calo::OutputFileName protected
Definition at line 37 of file sPHAnalysis_calo.h.
View newest version in sPHENIX GitHub at line 37 of file sPHAnalysis_calo.h
Referenced by Init(), and sPHAnalysis_calo().
TFile* sPHAnalysis_calo::OutputNtupleFile protected
Definition at line 36 of file sPHAnalysis_calo.h.
View newest version in sPHENIX GitHub at line 36 of file sPHAnalysis_calo.h
Referenced by End(), Init(), and sPHAnalysis_calo().
The documentation for this class was generated from the following files:
analysis/blob/master/EventMix/ana_calo/sPHAnalysis_calo.h
analysis/blob/master/EventMix/ana_calo/sPHAnalysis_calo.cc