Analysis Software: odbc::SQLException Class Reference
odbc::SQLException Class Reference
#include <RDBC/blob/master/include/RDBC/odbc++/types.h>
Public Member Functions
SQLException (const ODBCXX_STRING &reason="", const ODBCXX_STRING &sqlState="", int vendorCode=0)
SQLException (const DriverMessage &dm)
virtual ~SQLException () throw ()
int getErrorCode () const
const ODBCXX_STRING & getSQLState () const
const ODBCXX_STRING & getMessage () const
virtual const char * what () const throw ()
Private Attributes
ODBCXX_STRING reason_
ODBCXX_STRING sqlState_
int errorCode_
Detailed Description
The exception thrown when errors occur inside the library.
Definition at line 655 of file types.h.
View newest version in sPHENIX GitHub at line 655 of file types.h
Constructor & Destructor Documentation
odbc::SQLException::SQLException (const ODBCXX_STRING & reason = "", const ODBCXX_STRING & sqlState = "", int vendorCode = 0) inline
Constructor
Definition at line 666 of file types.h.
View newest version in sPHENIX GitHub at line 666 of file types.h
odbc::SQLException::SQLException (const DriverMessage & dm) inline
Copy from a DriverMessage
Definition at line 678 of file types.h.
View newest version in sPHENIX GitHub at line 678 of file types.h
virtual odbc::SQLException::~SQLException () throw () inline virtual
Destructor
Definition at line 684 of file types.h.
View newest version in sPHENIX GitHub at line 684 of file types.h
Member Function Documentation
int odbc::SQLException::getErrorCode () const inline
Get the vendor error code of this exception
Definition at line 687 of file types.h.
View newest version in sPHENIX GitHub at line 687 of file types.h
References errorCode_.
Referenced by ODBCResultSet::Absolute(), ODBCResultSet::AfterLast(), ODBCDatabaseMetaData::AllProceduresAreCallable(), ODBCDatabaseMetaData::AllTablesAreSelectable(), ODBCResultSet::BeforeFirst(), ODBCStatement::Cancel(), ODBCPreparedStatement::Cancel(), ODBCCallableStatement::Cancel(), ODBCResultSet::CancelRowUpdates(), ClassImpQ(), ODBCPreparedStatement::ClearParameters(), ODBCCallableStatement::ClearParameters(), ODBCStatement::Close(), ODBCConnection::Close(), ODBCPreparedStatement::Close(), ODBCCallableStatement::Close(), ODBCResultSet::Close(), ODBCConnection::Commit(), ODBCConnection::CreateStatement(), ODBCDatabaseMetaData::DataDefinitionCausesTransactionCommit(), ODBCDatabaseMetaData::DataDefinitionIgnoredInTransactions(), ODBCResultSet::DeleteRow(), ODBCDatabaseMetaData::DeletesAreDetected(), ODBCDatabaseMetaData::DoesMaxRowSizeIncludeBlobs(), ODBCStatement::Execute(), ODBCPreparedStatement::Execute(), ODBCCallableStatement::Execute(), ODBCStatement::ExecuteQuery(), ODBCPreparedStatement::ExecuteQuery(), ODBCCallableStatement::ExecuteQuery(), ODBCStatement::ExecuteUpdate(), ODBCPreparedStatement::ExecuteUpdate(), ODBCCallableStatement::ExecuteUpdate(), ODBCResultSet::FindColumn(), ODBCResultSet::First(), ODBCResultSet::GetAsciiStream(), ODBCConnection::GetAutoCommit(), ODBCDatabaseMetaData::GetBestRowIdentifier(), ODBCResultSet::GetBinaryStream(), ODBCCallableStatement::GetBoolean(), ODBCResultSet::GetBoolean(), ODBCCallableStatement::GetByte(), ODBCResultSet::GetByte(), ODBCCallableStatement::GetBytes(), ODBCResultSet::GetBytes(), ODBCConnection::GetCatalog(), ODBCResultSetMetaData::GetCatalogName(), ODBCDatabaseMetaData::GetCatalogs(), ODBCDatabaseMetaData::GetCatalogSeparator(), ODBCDatabaseMetaData::GetCatalogTerm(), ODBCResultSetMetaData::GetColumnCount(), ODBCResultSetMetaData::GetColumnDisplaySize(), ODBCResultSetMetaData::GetColumnLabel(), ODBCResultSetMetaData::GetColumnName(), ODBCDatabaseMetaData::GetColumnPrivileges(), ODBCDatabaseMetaData::GetColumns(), ODBCResultSetMetaData::GetColumnType(), ODBCResultSetMetaData::GetColumnTypeName(), ODBCResultSet::GetConcurrency(), ODBCDatabaseMetaData::GetCrossReference(), ODBCResultSet::GetCursorName(), ODBCDatabaseMetaData::GetDatabaseProductName(), ODBCDatabaseMetaData::GetDatabaseProductVersion(), ODBCCallableStatement::GetDate(), ODBCResultSet::GetDate(), ODBCDatabaseMetaData::GetDefaultTransactionIsolation(), ODBCCallableStatement::GetDouble(), ODBCResultSet::GetDouble(), ODBCDatabaseMetaData::GetDriverMajorVersion(), ODBCDatabaseMetaData::GetDriverMinorVersion(), ODBCDatabaseMetaData::GetDriverName(), ODBCDatabaseMetaData::GetDriverVersion(), ODBCStatement::GetEscapeProcessing(), ODBCPreparedStatement::GetEscapeProcessing(), ODBCCallableStatement::GetEscapeProcessing(), ODBCDatabaseMetaData::GetExportedKeys(), ODBCDatabaseMetaData::GetExtraNameCharacters(), ODBCStatement::GetFetchSize(), ODBCPreparedStatement::GetFetchSize(), ODBCResultSet::GetFetchSize(), ODBCCallableStatement::GetFetchSize(), ODBCCallableStatement::GetFloat(), ODBCResultSet::GetFloat(), ODBCDatabaseMetaData::GetIdentifierQuoteString(), ODBCDatabaseMetaData::GetImportedKeys(), ODBCDatabaseMetaData::GetIndexInfo(), ODBCCallableStatement::GetInt(), ODBCResultSet::GetInt(), ODBCCallableStatement::GetLong(), ODBCResultSet::GetLong(), ODBCDatabaseMetaData::GetMaxBinaryLiteralLength(), ODBCDatabaseMetaData::GetMaxCatalogNameLength(), ODBCDatabaseMetaData::GetMaxCharLiteralLength(), ODBCDatabaseMetaData::GetMaxColumnNameLength(), ODBCDatabaseMetaData::GetMaxColumnsInGroupBy(), ODBCDatabaseMetaData::GetMaxColumnsInIndex(), ODBCDatabaseMetaData::GetMaxColumnsInOrderBy(), ODBCDatabaseMetaData::GetMaxColumnsInSelect(), ODBCDatabaseMetaData::GetMaxColumnsInTable(), ODBCDatabaseMetaData::GetMaxConnections(), ODBCDatabaseMetaData::GetMaxCursorNameLength(), ODBCStatement::GetMaxFieldSize(), ODBCPreparedStatement::GetMaxFieldSize(), ODBCCallableStatement::GetMaxFieldSize(), ODBCDatabaseMetaData::GetMaxIndexLength(), ODBCDatabaseMetaData::GetMaxProcedureNameLength(), ODBCStatement::GetMaxRows(), ODBCPreparedStatement::GetMaxRows(), ODBCCallableStatement::GetMaxRows(), ODBCDatabaseMetaData::GetMaxRowSize(), ODBCDatabaseMetaData::GetMaxSchemaNameLength(), ODBCDatabaseMetaData::GetMaxStatementLength(), ODBCDatabaseMetaData::GetMaxStatements(), ODBCDatabaseMetaData::GetMaxTableNameLength(), ODBCDatabaseMetaData::GetMaxTablesInSelect(), ODBCDatabaseMetaData::GetMaxUserNameLength(), ODBCConnection::GetMetaData(), ODBCStatement::GetMoreResults(), ODBCPreparedStatement::GetMoreResults(), ODBCCallableStatement::GetMoreResults(), ODBCDatabaseMetaData::GetNumericFunctions(), ODBCResultSetMetaData::GetPrecision(), ODBCDatabaseMetaData::GetPrimaryKeys(), ODBCDatabaseMetaData::GetProcedureColumns(), ODBCDatabaseMetaData::GetProcedures(), ODBCDatabaseMetaData::GetProcedureTerm(), ODBCStatement::GetQueryTimeout(), ODBCPreparedStatement::GetQueryTimeout(), ODBCCallableStatement::GetQueryTimeout(), ODBCStatement::GetResultSet(), ODBCPreparedStatement::GetResultSet(), ODBCCallableStatement::GetResultSet(), ODBCStatement::GetResultSetConcurrency(), ODBCPreparedStatement::GetResultSetConcurrency(), ODBCCallableStatement::GetResultSetConcurrency(), ODBCStatement::GetResultSetType(), ODBCPreparedStatement::GetResultSetType(), ODBCCallableStatement::GetResultSetType(), ODBCResultSet::GetRow(), ODBCResultSetMetaData::GetScale(), ODBCResultSetMetaData::GetSchemaName(), ODBCDatabaseMetaData::GetSchemas(), ODBCDatabaseMetaData::GetSchemaTerm(), ODBCDatabaseMetaData::GetSearchStringEscape(), ODBCCallableStatement::GetShort(), ODBCResultSet::GetShort(), ODBCDatabaseMetaData::GetSQLKeywords(), ODBCCallableStatement::GetString(), ODBCResultSet::GetString(), ODBCDatabaseMetaData::GetStringFunctions(), ODBCDatabaseMetaData::GetSystemFunctions(), ODBCResultSetMetaData::GetTableName(), ODBCDatabaseMetaData::GetTablePrivileges(), ODBCDatabaseMetaData::GetTables(), ODBCDatabaseMetaData::GetTableTerm(), ODBCDatabaseMetaData::GetTableTypes(), ODBCCallableStatement::GetTime(), ODBCResultSet::GetTime(), ODBCDatabaseMetaData::GetTimeDateFunctions(), ODBCCallableStatement::GetTimestamp(), ODBCResultSet::GetTimestamp(), ODBCConnection::GetTrace(), ODBCConnection::GetTraceFile(), ODBCConnection::GetTransactionIsolation(), ODBCResultSet::GetType(), ODBCDatabaseMetaData::GetTypeInfo(), ODBCStatement::GetUpdateCount(), ODBCPreparedStatement::GetUpdateCount(), ODBCCallableStatement::GetUpdateCount(), ODBCDatabaseMetaData::GetUserName(), ODBCDatabaseMetaData::GetVersionColumns(), ODBCResultSet::InsertRow(), ODBCDatabaseMetaData::InsertsAreDetected(), ODBCResultSet::IsAfterLast(), ODBCResultSetMetaData::IsAutoIncrement(), ODBCResultSet::IsBeforeFirst(), ODBCResultSetMetaData::IsCaseSensitive(), ODBCDatabaseMetaData::IsCatalogAtStart(), ODBCResultSetMetaData::IsCurrency(), ODBCResultSetMetaData::IsDefinitelyWritable(), ODBCResultSet::IsFirst(), ODBCResultSet::IsLast(), ODBCResultSetMetaData::IsNullable(), ODBCConnection::IsReadOnly(), ODBCDatabaseMetaData::IsReadOnly(), ODBCResultSetMetaData::IsReadOnly(), ODBCResultSetMetaData::IsSearchable(), ODBCResultSetMetaData::IsSigned(), ODBCResultSetMetaData::IsWritable(), ODBCResultSet::Last(), ODBCResultSet::MoveToCurrentRow(), ODBCResultSet::MoveToInsertRow(), ODBCConnection::NativeSQL(), ODBCResultSet::Next(), ODBCDatabaseMetaData::NullPlusNonNullIsNull(), ODBCDatabaseMetaData::NullsAreSortedAtEnd(), ODBCDatabaseMetaData::NullsAreSortedAtStart(), ODBCDatabaseMetaData::NullsAreSortedHigh(), ODBCDatabaseMetaData::NullsAreSortedLow(), ODBCConnection::ODBCConnection(), ODBCResultSet::ODBCResultSet(), ODBCDatabaseMetaData::OthersDeletesAreVisible(), ODBCDatabaseMetaData::OthersInsertsAreVisible(), ODBCDatabaseMetaData::OthersUpdatesAreVisible(), ODBCDatabaseMetaData::OwnDeletesAreVisible(), ODBCDatabaseMetaData::OwnInsertsAreVisible(), ODBCDatabaseMetaData::OwnUpdatesAreVisible(), ODBCConnection::PrepareCall(), ODBCConnection::PrepareStatement(), ODBCResultSet::Previous(), ODBCConnection::RefreshDataSources(), ODBCConnection::RefreshDrivers(), ODBCResultSet::RefreshRow(), ODBCCallableStatement::RegisterOutParameter(), ODBCResultSet::Relative(), ODBCConnection::Rollback(), ODBCResultSet::RowDeleted(), ODBCResultSet::RowInserted(), ODBCResultSet::RowUpdated(), ODBCPreparedStatement::SetAsciiStream(), ODBCCallableStatement::SetAsciiStream(), ODBCConnection::SetAutoCommit(), ODBCPreparedStatement::SetBinaryStream(), ODBCCallableStatement::SetBinaryStream(), ODBCPreparedStatement::SetBoolean(), ODBCCallableStatement::SetBoolean(), ODBCPreparedStatement::SetByte(), ODBCCallableStatement::SetByte(), ODBCPreparedStatement::SetBytes(), ODBCCallableStatement::SetBytes(), ODBCConnection::SetCatalog(), ODBCStatement::SetCursorName(), ODBCPreparedStatement::SetCursorName(), ODBCCallableStatement::SetCursorName(), ODBCPreparedStatement::SetDate(), ODBCCallableStatement::SetDate(), ODBCPreparedStatement::SetDouble(), ODBCCallableStatement::SetDouble(), ODBCStatement::SetEscapeProcessing(), ODBCPreparedStatement::SetEscapeProcessing(), ODBCCallableStatement::SetEscapeProcessing(), ODBCResultSet::SetFetchSize(), ODBCPreparedStatement::SetFloat(), ODBCCallableStatement::SetFloat(), ODBCPreparedStatement::SetInt(), ODBCCallableStatement::SetInt(), ODBCPreparedStatement::SetLong(), ODBCCallableStatement::SetLong(), ODBCStatement::SetMaxFieldSize(), ODBCPreparedStatement::SetMaxFieldSize(), ODBCCallableStatement::SetMaxFieldSize(), ODBCStatement::SetMaxRows(), ODBCPreparedStatement::SetMaxRows(), ODBCCallableStatement::SetMaxRows(), ODBCPreparedStatement::SetNull(), ODBCCallableStatement::SetNull(), ODBCStatement::SetQueryTimeout(), ODBCPreparedStatement::SetQueryTimeout(), ODBCCallableStatement::SetQueryTimeout(), ODBCConnection::SetReadOnly(), ODBCPreparedStatement::SetShort(), ODBCCallableStatement::SetShort(), ODBCPreparedStatement::SetString(), ODBCCallableStatement::SetString(), ODBCPreparedStatement::SetTime(), ODBCCallableStatement::SetTime(), ODBCPreparedStatement::SetTimestamp(), ODBCCallableStatement::SetTimestamp(), ODBCConnection::SetTrace(), ODBCConnection::SetTraceFile(), ODBCConnection::SetTransactionIsolation(), ODBCConnection::Shutdown(), ODBCDatabaseMetaData::StoresLowerCaseIdentifiers(), ODBCDatabaseMetaData::StoresLowerCaseQuotedIdentifiers(), ODBCDatabaseMetaData::StoresMixedCaseIdentifiers(), ODBCDatabaseMetaData::StoresMixedCaseQuotedIdentifiers(), ODBCDatabaseMetaData::StoresUpperCaseIdentifiers(), ODBCDatabaseMetaData::StoresUpperCaseQuotedIdentifiers(), ODBCDatabaseMetaData::SupportsAlterTableWithAddColumn(), ODBCDatabaseMetaData::SupportsAlterTableWithDropColumn(), ODBCDatabaseMetaData::SupportsANSI92EntryLevelSQL(), ODBCDatabaseMetaData::SupportsANSI92FullSQL(), ODBCDatabaseMetaData::SupportsANSI92IntermediateSQL(), ODBCDatabaseMetaData::SupportsBatchUpdates(), ODBCDatabaseMetaData::SupportsCatalogsInDataManipulation(), ODBCDatabaseMetaData::SupportsCatalogsInIndexDefinitions(), ODBCDatabaseMetaData::SupportsCatalogsInPrivilegeDefinitions(), ODBCDatabaseMetaData::SupportsCatalogsInProcedureCalls(), ODBCDatabaseMetaData::SupportsCatalogsInTableDefinitions(), ODBCDatabaseMetaData::SupportsColumnAliasing(), ODBCDatabaseMetaData::SupportsConvert(), ODBCDatabaseMetaData::SupportsCoreSQLGrammar(), ODBCDatabaseMetaData::SupportsCorrelatedSubqueries(), ODBCDatabaseMetaData::SupportsDataDefinitionAndDataManipulationTransactions(), ODBCDatabaseMetaData::SupportsDataManipulationTransactionsOnly(), ODBCDatabaseMetaData::SupportsDifferentTableCorrelationNames(), ODBCDatabaseMetaData::SupportsExpressionsInOrderBy(), ODBCDatabaseMetaData::SupportsExtendedSQLGrammar(), ODBCDatabaseMetaData::SupportsFullOuterJoins(), ODBCDatabaseMetaData::SupportsGroupBy(), ODBCDatabaseMetaData::SupportsGroupByBeyondSelect(), ODBCDatabaseMetaData::SupportsGroupByUnrelated(), ODBCDatabaseMetaData::SupportsIntegrityEnhancementFacility(), ODBCDatabaseMetaData::SupportsLikeEscapeClause(), ODBCDatabaseMetaData::SupportsLimitedOuterJoins(), ODBCDatabaseMetaData::SupportsMinimumSQLGrammar(), ODBCDatabaseMetaData::SupportsMixedCaseIdentifiers(), ODBCDatabaseMetaData::SupportsMixedCaseQuotedIdentifiers(), ODBCDatabaseMetaData::SupportsMultipleResultSets(), ODBCDatabaseMetaData::SupportsMultipleTransactions(), ODBCDatabaseMetaData::SupportsNonNullableColumns(), ODBCDatabaseMetaData::SupportsOpenCursorsAcrossCommit(), ODBCDatabaseMetaData::SupportsOpenCursorsAcrossRollback(), ODBCDatabaseMetaData::SupportsOpenStatementsAcrossCommit(), ODBCDatabaseMetaData::SupportsOpenStatementsAcrossRollback(), ODBCDatabaseMetaData::SupportsOrderByUnrelated(), ODBCDatabaseMetaData::SupportsOuterJoins(), ODBCDatabaseMetaData::SupportsPositionedDelete(), ODBCDatabaseMetaData::SupportsPositionedUpdate(), ODBCDatabaseMetaData::SupportsResultSetConcurrency(), ODBCDatabaseMetaData::SupportsResultSetType(), ODBCDatabaseMetaData::SupportsSchemasInDataManipulation(), ODBCDatabaseMetaData::SupportsSchemasInIndexDefinitions(), ODBCDatabaseMetaData::SupportsSchemasInPrivilegeDefinitions(), ODBCDatabaseMetaData::SupportsSchemasInProcedureCalls(), ODBCDatabaseMetaData::SupportsSchemasInTableDefinitions(), ODBCDatabaseMetaData::SupportsSelectForUpdate(), ODBCDatabaseMetaData::SupportsStoredProcedures(), ODBCDatabaseMetaData::SupportsSubqueriesInComparisons(), ODBCDatabaseMetaData::SupportsSubqueriesInExists(), ODBCDatabaseMetaData::SupportsSubqueriesInIns(), ODBCDatabaseMetaData::SupportsSubqueriesInQuantifieds(), ODBCDatabaseMetaData::SupportsTableCorrelationNames(), ODBCDatabaseMetaData::SupportsTransactionIsolationLevel(), ODBCDatabaseMetaData::SupportsTransactions(), ODBCDatabaseMetaData::SupportsUnion(), ODBCDatabaseMetaData::SupportsUnionAll(), ODBCResultSet::UpdateAsciiStream(), ODBCResultSet::UpdateBinaryStream(), ODBCResultSet::UpdateBoolean(), ODBCResultSet::UpdateByte(), ODBCResultSet::UpdateBytes(), ODBCResultSet::UpdateDate(), ODBCResultSet::UpdateDouble(), ODBCResultSet::UpdateFloat(), ODBCResultSet::UpdateInt(), ODBCResultSet::UpdateLong(), ODBCResultSet::UpdateNull(), ODBCResultSet::UpdateRow(), ODBCDatabaseMetaData::UpdatesAreDetected(), ODBCResultSet::UpdateShort(), ODBCResultSet::UpdateString(), ODBCResultSet::UpdateTime(), ODBCResultSet::UpdateTimestamp(), ODBCDatabaseMetaData::UsesLocalFilePerTable(), ODBCDatabaseMetaData::UsesLocalFiles(), ODBCCallableStatement::WasNull(), ODBCResultSet::WasNull(), ODBCCallableStatement::~ODBCCallableStatement(), ODBCConnection::~ODBCConnection(), ODBCPreparedStatement::~ODBCPreparedStatement(), ODBCResultSet::~ODBCResultSet(), ODBCResultSetMetaData::~ODBCResultSetMetaData(), and ODBCStatement::~ODBCStatement().
const ODBCXX_STRING& odbc::SQLException::getMessage () const inline
Gets the description of this message
Definition at line 700 of file types.h.
View newest version in sPHENIX GitHub at line 700 of file types.h
References reason_.
Referenced by ODBCResultSet::Absolute(), OnCalServer::add_calibrator_to_statustable(), PktSizeDBodbc::AddRow(), OnlMonDBodbc::AddRow(), ODBCResultSet::AfterLast(), ODBCDatabaseMetaData::AllProceduresAreCallable(), ODBCDatabaseMetaData::AllTablesAreSelectable(), ODBCResultSet::BeforeFirst(), OnlMonClient::CacheRunDB(), OnlMonServer::CacheRunDB(), ODBCStatement::Cancel(), ODBCPreparedStatement::Cancel(), ODBCCallableStatement::Cancel(), ODBCResultSet::CancelRowUpdates(), OnCalServer::check_calibrator_in_statustable(), OnCalServer::check_create_subsystable(), OnCalServer::check_create_successtable(), PktSizeDBodbc::CheckAndAddColumns(), OnlMonStatusDB::CheckAndCreateMonitor(), OnlMonStatusDB::CheckAndCreateTable(), PktSizeDBodbc::CheckAndCreateTable(), OnlMonDBodbc::CheckAndCreateTable(), ClassImpQ(), ODBCPreparedStatement::ClearParameters(), ODBCCallableStatement::ClearParameters(), ODBCConnection::Close(), ODBCStatement::Close(), ODBCPreparedStatement::Close(), ODBCCallableStatement::Close(), ODBCResultSet::Close(), ODBCConnection::Commit(), OnCalServer::connectDB(), OnCalServer::CreateCalibration(), ODBCConnection::CreateStatement(), OnlMonDBodbc::CreateTable(), ODBCDatabaseMetaData::DataDefinitionCausesTransactionCommit(), ODBCDatabaseMetaData::DataDefinitionIgnoredInTransactions(), ODBCResultSet::DeleteRow(), ODBCDatabaseMetaData::DeletesAreDetected(), ODBCDatabaseMetaData::DoesMaxRowSizeIncludeBlobs(), OnlMonDBodbc::Dump(), ODBCStatement::Execute(), ODBCPreparedStatement::Execute(), ODBCCallableStatement::Execute(), ODBCStatement::ExecuteQuery(), ODBCPreparedStatement::ExecuteQuery(), ODBCCallableStatement::ExecuteQuery(), ODBCStatement::ExecuteUpdate(), ODBCPreparedStatement::ExecuteUpdate(), ODBCCallableStatement::ExecuteUpdate(), OnlMonStatusDB::FindAndInsertRunNum(), ODBCResultSet::FindColumn(), OnlMonStatusDB::findRunNumInDB(), OnCalServer::findRunNumInDB(), ODBCResultSet::First(), OnCalServer::FixMissingCalibration(), ODBCResultSet::GetAsciiStream(), ODBCConnection::GetAutoCommit(), ODBCDatabaseMetaData::GetBestRowIdentifier(), ODBCResultSet::GetBinaryStream(), ODBCCallableStatement::GetBoolean(), ODBCResultSet::GetBoolean(), ODBCCallableStatement::GetByte(), ODBCResultSet::GetByte(), ODBCCallableStatement::GetBytes(), ODBCResultSet::GetBytes(), ODBCConnection::GetCatalog(), ODBCResultSetMetaData::GetCatalogName(), ODBCDatabaseMetaData::GetCatalogs(), ODBCDatabaseMetaData::GetCatalogSeparator(), ODBCDatabaseMetaData::GetCatalogTerm(), ODBCResultSetMetaData::GetColumnCount(), ODBCResultSetMetaData::GetColumnDisplaySize(), ODBCResultSetMetaData::GetColumnLabel(), ODBCResultSetMetaData::GetColumnName(), ODBCDatabaseMetaData::GetColumnPrivileges(), ODBCDatabaseMetaData::GetColumns(), ODBCResultSetMetaData::GetColumnType(), ODBCResultSetMetaData::GetColumnTypeName(), ODBCResultSet::GetConcurrency(), OnlMonStatusDB::GetConnection(), PktSizeDBodbc::GetConnection(), FROG::GetConnection(), OnlMonDBodbc::GetConnection(), RunToTimePg::GetConnection(), ODBCDatabaseMetaData::GetCrossReference(), ODBCResultSet::GetCursorName(), ODBCDatabaseMetaData::GetDatabaseProductName(), ODBCDatabaseMetaData::GetDatabaseProductVersion(), ODBCCallableStatement::GetDate(), ODBCResultSet::GetDate(), ODBCDatabaseMetaData::GetDefaultTransactionIsolation(), ODBCCallableStatement::GetDouble(), ODBCResultSet::GetDouble(), ODBCDatabaseMetaData::GetDriverMajorVersion(), ODBCDatabaseMetaData::GetDriverMinorVersion(), ODBCDatabaseMetaData::GetDriverName(), ODBCDatabaseMetaData::GetDriverVersion(), ODBCStatement::GetEscapeProcessing(), ODBCPreparedStatement::GetEscapeProcessing(), ODBCCallableStatement::GetEscapeProcessing(), ODBCDatabaseMetaData::GetExportedKeys(), ODBCDatabaseMetaData::GetExtraNameCharacters(), ODBCStatement::GetFetchSize(), ODBCPreparedStatement::GetFetchSize(), ODBCResultSet::GetFetchSize(), ODBCCallableStatement::GetFetchSize(), ODBCCallableStatement::GetFloat(), ODBCResultSet::GetFloat(), ODBCDatabaseMetaData::GetIdentifierQuoteString(), ODBCDatabaseMetaData::GetImportedKeys(), ODBCDatabaseMetaData::GetIndexInfo(), ODBCCallableStatement::GetInt(), ODBCResultSet::GetInt(), OnCalDBodbc::GetLastCalibratedRun(), ODBCCallableStatement::GetLong(), ODBCResultSet::GetLong(), ODBCDatabaseMetaData::GetMaxBinaryLiteralLength(), ODBCDatabaseMetaData::GetMaxCatalogNameLength(), ODBCDatabaseMetaData::GetMaxCharLiteralLength(), ODBCDatabaseMetaData::GetMaxColumnNameLength(), ODBCDatabaseMetaData::GetMaxColumnsInGroupBy(), ODBCDatabaseMetaData::GetMaxColumnsInIndex(), ODBCDatabaseMetaData::GetMaxColumnsInOrderBy(), ODBCDatabaseMetaData::GetMaxColumnsInSelect(), ODBCDatabaseMetaData::GetMaxColumnsInTable(), ODBCDatabaseMetaData::GetMaxConnections(), ODBCDatabaseMetaData::GetMaxCursorNameLength(), ODBCStatement::GetMaxFieldSize(), ODBCPreparedStatement::GetMaxFieldSize(), ODBCCallableStatement::GetMaxFieldSize(), ODBCDatabaseMetaData::GetMaxIndexLength(), ODBCDatabaseMetaData::GetMaxProcedureNameLength(), ODBCStatement::GetMaxRows(), ODBCPreparedStatement::GetMaxRows(), ODBCCallableStatement::GetMaxRows(), ODBCDatabaseMetaData::GetMaxRowSize(), ODBCDatabaseMetaData::GetMaxSchemaNameLength(), ODBCDatabaseMetaData::GetMaxStatementLength(), ODBCDatabaseMetaData::GetMaxStatements(), ODBCDatabaseMetaData::GetMaxTableNameLength(), ODBCDatabaseMetaData::GetMaxTablesInSelect(), ODBCDatabaseMetaData::GetMaxUserNameLength(), ODBCConnection::GetMetaData(), ODBCStatement::GetMoreResults(), ODBCPreparedStatement::GetMoreResults(), ODBCCallableStatement::GetMoreResults(), ODBCDatabaseMetaData::GetNumericFunctions(), PktSizeDBodbc::GetPacketContent(), ODBCResultSetMetaData::GetPrecision(), ODBCDatabaseMetaData::GetPrimaryKeys(), ODBCDatabaseMetaData::GetProcedureColumns(), ODBCDatabaseMetaData::GetProcedures(), ODBCDatabaseMetaData::GetProcedureTerm(), ODBCStatement::GetQueryTimeout(), ODBCPreparedStatement::GetQueryTimeout(), ODBCCallableStatement::GetQueryTimeout(), ODBCStatement::GetResultSet(), ODBCPreparedStatement::GetResultSet(), ODBCCallableStatement::GetResultSet(), ODBCStatement::GetResultSetConcurrency(), ODBCPreparedStatement::GetResultSetConcurrency(), ODBCCallableStatement::GetResultSetConcurrency(), ODBCStatement::GetResultSetType(), ODBCPreparedStatement::GetResultSetType(), ODBCCallableStatement::GetResultSetType(), ODBCResultSet::GetRow(), RunToTimePg::getRunNumber(), RunDBodbc::GetRunNumbers(), ODBCResultSetMetaData::GetScale(), ODBCResultSetMetaData::GetSchemaName(), ODBCDatabaseMetaData::GetSchemas(), ODBCDatabaseMetaData::GetSchemaTerm(), ODBCDatabaseMetaData::GetSearchStringEscape(), ODBCCallableStatement::GetShort(), ODBCResultSet::GetShort(), ODBCDatabaseMetaData::GetSQLKeywords(), ODBCCallableStatement::GetString(), ODBCResultSet::GetString(), ODBCDatabaseMetaData::GetStringFunctions(), ODBCDatabaseMetaData::GetSystemFunctions(), ODBCResultSetMetaData::GetTableName(), ODBCDatabaseMetaData::GetTablePrivileges(), ODBCDatabaseMetaData::GetTables(), ODBCDatabaseMetaData::GetTableTerm(), ODBCDatabaseMetaData::GetTableTypes(), ODBCCallableStatement::GetTime(), RunToTimePg::getTime(), ODBCResultSet::GetTime(), ODBCDatabaseMetaData::GetTimeDateFunctions(), ODBCCallableStatement::GetTimestamp(), ODBCResultSet::GetTimestamp(), ODBCConnection::GetTrace(), ODBCConnection::GetTraceFile(), ODBCConnection::GetTransactionIsolation(), ODBCResultSet::GetType(), ODBCDatabaseMetaData::GetTypeInfo(), ODBCStatement::GetUpdateCount(), ODBCPreparedStatement::GetUpdateCount(), ODBCCallableStatement::GetUpdateCount(), ODBCDatabaseMetaData::GetUserName(), OnlMonDBodbc::GetVar(), ODBCDatabaseMetaData::GetVersionColumns(), ODBCResultSet::InsertRow(), OnCalServer::insertRunNumInDB(), ODBCDatabaseMetaData::InsertsAreDetected(), ODBCResultSet::IsAfterLast(), ODBCResultSetMetaData::IsAutoIncrement(), ODBCResultSet::IsBeforeFirst(), ODBCResultSetMetaData::IsCaseSensitive(), ODBCDatabaseMetaData::IsCatalogAtStart(), ODBCResultSetMetaData::IsCurrency(), ODBCResultSetMetaData::IsDefinitelyWritable(), ODBCResultSet::IsFirst(), ODBCResultSet::IsLast(), ODBCResultSetMetaData::IsNullable(), ODBCConnection::IsReadOnly(), ODBCDatabaseMetaData::IsReadOnly(), ODBCResultSetMetaData::IsReadOnly(), ODBCResultSetMetaData::IsSearchable(), ODBCResultSetMetaData::IsSigned(), ODBCResultSetMetaData::IsWritable(), ODBCResultSet::Last(), ODBCResultSet::MoveToCurrentRow(), ODBCResultSet::MoveToInsertRow(), ODBCConnection::NativeSQL(), ODBCResultSet::Next(), ODBCDatabaseMetaData::NullPlusNonNullIsNull(), ODBCDatabaseMetaData::NullsAreSortedAtEnd(), ODBCDatabaseMetaData::NullsAreSortedAtStart(), ODBCDatabaseMetaData::NullsAreSortedHigh(), ODBCDatabaseMetaData::NullsAreSortedLow(), ODBCConnection::ODBCConnection(), ODBCResultSet::ODBCResultSet(), ODBCDatabaseMetaData::OthersDeletesAreVisible(), ODBCDatabaseMetaData::OthersInsertsAreVisible(), ODBCDatabaseMetaData::OthersUpdatesAreVisible(), ODBCDatabaseMetaData::OwnDeletesAreVisible(), ODBCDatabaseMetaData::OwnInsertsAreVisible(), ODBCDatabaseMetaData::OwnUpdatesAreVisible(), ODBCConnection::PrepareCall(), ODBCConnection::PrepareStatement(), ODBCResultSet::Previous(), ODBCConnection::RefreshDataSources(), ODBCConnection::RefreshDrivers(), ODBCResultSet::RefreshRow(), ODBCCallableStatement::RegisterOutParameter(), ODBCResultSet::Relative(), ODBCConnection::Rollback(), ODBCResultSet::RowDeleted(), ODBCResultSet::RowInserted(), ODBCResultSet::RowUpdated(), RunDBodbc::RunType(), ODBCPreparedStatement::SetAsciiStream(), ODBCCallableStatement::SetAsciiStream(), ODBCConnection::SetAutoCommit(), ODBCPreparedStatement::SetBinaryStream(), ODBCCallableStatement::SetBinaryStream(), ODBCPreparedStatement::SetBoolean(), ODBCCallableStatement::SetBoolean(), ODBCPreparedStatement::SetByte(), ODBCCallableStatement::SetByte(), ODBCPreparedStatement::SetBytes(), ODBCCallableStatement::SetBytes(), ODBCConnection::SetCatalog(), ODBCStatement::SetCursorName(), ODBCPreparedStatement::SetCursorName(), ODBCCallableStatement::SetCursorName(), ODBCPreparedStatement::SetDate(), ODBCCallableStatement::SetDate(), ODBCPreparedStatement::SetDouble(), ODBCCallableStatement::SetDouble(), ODBCStatement::SetEscapeProcessing(), ODBCPreparedStatement::SetEscapeProcessing(), ODBCCallableStatement::SetEscapeProcessing(), ODBCResultSet::SetFetchSize(), ODBCPreparedStatement::SetFloat(), ODBCCallableStatement::SetFloat(), ODBCPreparedStatement::SetInt(), ODBCCallableStatement::SetInt(), ODBCPreparedStatement::SetLong(), ODBCCallableStatement::SetLong(), ODBCStatement::SetMaxFieldSize(), ODBCPreparedStatement::SetMaxFieldSize(), ODBCCallableStatement::SetMaxFieldSize(), ODBCStatement::SetMaxRows(), ODBCPreparedStatement::SetMaxRows(), ODBCCallableStatement::SetMaxRows(), ODBCPreparedStatement::SetNull(), ODBCCallableStatement::SetNull(), ODBCStatement::SetQueryTimeout(), ODBCPreparedStatement::SetQueryTimeout(), ODBCCallableStatement::SetQueryTimeout(), ODBCConnection::SetReadOnly(), ODBCPreparedStatement::SetShort(), ODBCCallableStatement::SetShort(), ODBCPreparedStatement::SetString(), ODBCCallableStatement::SetString(), ODBCPreparedStatement::SetTime(), ODBCCallableStatement::SetTime(), ODBCPreparedStatement::SetTimestamp(), ODBCCallableStatement::SetTimestamp(), ODBCConnection::SetTrace(), ODBCConnection::SetTraceFile(), ODBCConnection::SetTransactionIsolation(), ODBCConnection::Shutdown(), ODBCDatabaseMetaData::StoresLowerCaseIdentifiers(), ODBCDatabaseMetaData::StoresLowerCaseQuotedIdentifiers(), ODBCDatabaseMetaData::StoresMixedCaseIdentifiers(), ODBCDatabaseMetaData::StoresMixedCaseQuotedIdentifiers(), ODBCDatabaseMetaData::StoresUpperCaseIdentifiers(), ODBCDatabaseMetaData::StoresUpperCaseQuotedIdentifiers(), ODBCDatabaseMetaData::SupportsAlterTableWithAddColumn(), ODBCDatabaseMetaData::SupportsAlterTableWithDropColumn(), ODBCDatabaseMetaData::SupportsANSI92EntryLevelSQL(), ODBCDatabaseMetaData::SupportsANSI92FullSQL(), ODBCDatabaseMetaData::SupportsANSI92IntermediateSQL(), ODBCDatabaseMetaData::SupportsBatchUpdates(), ODBCDatabaseMetaData::SupportsCatalogsInDataManipulation(), ODBCDatabaseMetaData::SupportsCatalogsInIndexDefinitions(), ODBCDatabaseMetaData::SupportsCatalogsInPrivilegeDefinitions(), ODBCDatabaseMetaData::SupportsCatalogsInProcedureCalls(), ODBCDatabaseMetaData::SupportsCatalogsInTableDefinitions(), ODBCDatabaseMetaData::SupportsColumnAliasing(), ODBCDatabaseMetaData::SupportsConvert(), ODBCDatabaseMetaData::SupportsCoreSQLGrammar(), ODBCDatabaseMetaData::SupportsCorrelatedSubqueries(), ODBCDatabaseMetaData::SupportsDataDefinitionAndDataManipulationTransactions(), ODBCDatabaseMetaData::SupportsDataManipulationTransactionsOnly(), ODBCDatabaseMetaData::SupportsDifferentTableCorrelationNames(), ODBCDatabaseMetaData::SupportsExpressionsInOrderBy(), ODBCDatabaseMetaData::SupportsExtendedSQLGrammar(), ODBCDatabaseMetaData::SupportsFullOuterJoins(), ODBCDatabaseMetaData::SupportsGroupBy(), ODBCDatabaseMetaData::SupportsGroupByBeyondSelect(), ODBCDatabaseMetaData::SupportsGroupByUnrelated(), ODBCDatabaseMetaData::SupportsIntegrityEnhancementFacility(), ODBCDatabaseMetaData::SupportsLikeEscapeClause(), ODBCDatabaseMetaData::SupportsLimitedOuterJoins(), ODBCDatabaseMetaData::SupportsMinimumSQLGrammar(), ODBCDatabaseMetaData::SupportsMixedCaseIdentifiers(), ODBCDatabaseMetaData::SupportsMixedCaseQuotedIdentifiers(), ODBCDatabaseMetaData::SupportsMultipleResultSets(), ODBCDatabaseMetaData::SupportsMultipleTransactions(), ODBCDatabaseMetaData::SupportsNonNullableColumns(), ODBCDatabaseMetaData::SupportsOpenCursorsAcrossCommit(), ODBCDatabaseMetaData::SupportsOpenCursorsAcrossRollback(), ODBCDatabaseMetaData::SupportsOpenStatementsAcrossCommit(), ODBCDatabaseMetaData::SupportsOpenStatementsAcrossRollback(), ODBCDatabaseMetaData::SupportsOrderByUnrelated(), ODBCDatabaseMetaData::SupportsOuterJoins(), ODBCDatabaseMetaData::SupportsPositionedDelete(), ODBCDatabaseMetaData::SupportsPositionedUpdate(), ODBCDatabaseMetaData::SupportsResultSetConcurrency(), ODBCDatabaseMetaData::SupportsResultSetType(), ODBCDatabaseMetaData::SupportsSchemasInDataManipulation(), ODBCDatabaseMetaData::SupportsSchemasInIndexDefinitions(), ODBCDatabaseMetaData::SupportsSchemasInPrivilegeDefinitions(), ODBCDatabaseMetaData::SupportsSchemasInProcedureCalls(), ODBCDatabaseMetaData::SupportsSchemasInTableDefinitions(), ODBCDatabaseMetaData::SupportsSelectForUpdate(), ODBCDatabaseMetaData::SupportsStoredProcedures(), ODBCDatabaseMetaData::SupportsSubqueriesInComparisons(), ODBCDatabaseMetaData::SupportsSubqueriesInExists(), ODBCDatabaseMetaData::SupportsSubqueriesInIns(), ODBCDatabaseMetaData::SupportsSubqueriesInQuantifieds(), ODBCDatabaseMetaData::SupportsTableCorrelationNames(), ODBCDatabaseMetaData::SupportsTransactionIsolationLevel(), ODBCDatabaseMetaData::SupportsTransactions(), ODBCDatabaseMetaData::SupportsUnion(), ODBCDatabaseMetaData::SupportsUnionAll(), OnCalServer::SyncCalibTimeStampsToOnCal(), OnCalServer::SyncOncalTimeStampsToRunDB(), ODBCResultSet::UpdateAsciiStream(), ODBCResultSet::UpdateBinaryStream(), ODBCResultSet::UpdateBoolean(), ODBCResultSet::UpdateByte(), ODBCResultSet::UpdateBytes(), ODBCResultSet::UpdateDate(), OnCalServer::updateDB(), OnCalServer::updateDBRunRange(), ODBCResultSet::UpdateDouble(), ODBCResultSet::UpdateFloat(), ODBCResultSet::UpdateInt(), ODBCResultSet::UpdateLong(), ODBCResultSet::UpdateNull(), ODBCResultSet::UpdateRow(), ODBCDatabaseMetaData::UpdatesAreDetected(), ODBCResultSet::UpdateShort(), OnlMonStatusDB::UpdateStatus(), ODBCResultSet::UpdateString(), ODBCResultSet::UpdateTime(), ODBCResultSet::UpdateTimestamp(), ODBCDatabaseMetaData::UsesLocalFilePerTable(), ODBCDatabaseMetaData::UsesLocalFiles(), ODBCCallableStatement::WasNull(), ODBCResultSet::WasNull(), ODBCCallableStatement::~ODBCCallableStatement(), ODBCConnection::~ODBCConnection(), ODBCPreparedStatement::~ODBCPreparedStatement(), ODBCResultSet::~ODBCResultSet(), ODBCResultSetMetaData::~ODBCResultSetMetaData(), and ODBCStatement::~ODBCStatement().
const ODBCXX_STRING& odbc::SQLException::getSQLState () const inline
Gets the SQLSTATE of this exception.
Consult your local ODBC reference for SQLSTATE values.
Definition at line 695 of file types.h.
View newest version in sPHENIX GitHub at line 695 of file types.h
References sqlState_.
Referenced by ODBCResultSet::Absolute(), ODBCResultSet::AfterLast(), ODBCDatabaseMetaData::AllProceduresAreCallable(), ODBCDatabaseMetaData::AllTablesAreSelectable(), ODBCResultSet::BeforeFirst(), ODBCStatement::Cancel(), ODBCPreparedStatement::Cancel(), ODBCCallableStatement::Cancel(), ODBCResultSet::CancelRowUpdates(), ClassImpQ(), ODBCPreparedStatement::ClearParameters(), ODBCCallableStatement::ClearParameters(), ODBCStatement::Close(), ODBCConnection::Close(), ODBCPreparedStatement::Close(), ODBCCallableStatement::Close(), ODBCResultSet::Close(), ODBCConnection::Commit(), ODBCConnection::CreateStatement(), ODBCDatabaseMetaData::DataDefinitionCausesTransactionCommit(), ODBCDatabaseMetaData::DataDefinitionIgnoredInTransactions(), ODBCResultSet::DeleteRow(), ODBCDatabaseMetaData::DeletesAreDetected(), ODBCDatabaseMetaData::DoesMaxRowSizeIncludeBlobs(), ODBCStatement::Execute(), ODBCPreparedStatement::Execute(), ODBCCallableStatement::Execute(), ODBCStatement::ExecuteQuery(), ODBCPreparedStatement::ExecuteQuery(), ODBCCallableStatement::ExecuteQuery(), ODBCStatement::ExecuteUpdate(), ODBCPreparedStatement::ExecuteUpdate(), ODBCCallableStatement::ExecuteUpdate(), ODBCResultSet::FindColumn(), ODBCResultSet::First(), ODBCResultSet::GetAsciiStream(), ODBCConnection::GetAutoCommit(), ODBCDatabaseMetaData::GetBestRowIdentifier(), ODBCResultSet::GetBinaryStream(), ODBCCallableStatement::GetBoolean(), ODBCResultSet::GetBoolean(), ODBCCallableStatement::GetByte(), ODBCResultSet::GetByte(), ODBCCallableStatement::GetBytes(), ODBCResultSet::GetBytes(), ODBCConnection::GetCatalog(), ODBCResultSetMetaData::GetCatalogName(), ODBCDatabaseMetaData::GetCatalogs(), ODBCDatabaseMetaData::GetCatalogSeparator(), ODBCDatabaseMetaData::GetCatalogTerm(), ODBCResultSetMetaData::GetColumnCount(), ODBCResultSetMetaData::GetColumnDisplaySize(), ODBCResultSetMetaData::GetColumnLabel(), ODBCResultSetMetaData::GetColumnName(), ODBCDatabaseMetaData::GetColumnPrivileges(), ODBCDatabaseMetaData::GetColumns(), ODBCResultSetMetaData::GetColumnType(), ODBCResultSetMetaData::GetColumnTypeName(), ODBCResultSet::GetConcurrency(), ODBCDatabaseMetaData::GetCrossReference(), ODBCResultSet::GetCursorName(), ODBCDatabaseMetaData::GetDatabaseProductName(), ODBCDatabaseMetaData::GetDatabaseProductVersion(), ODBCCallableStatement::GetDate(), ODBCResultSet::GetDate(), ODBCDatabaseMetaData::GetDefaultTransactionIsolation(), ODBCCallableStatement::GetDouble(), ODBCResultSet::GetDouble(), ODBCDatabaseMetaData::GetDriverMajorVersion(), ODBCDatabaseMetaData::GetDriverMinorVersion(), ODBCDatabaseMetaData::GetDriverName(), ODBCDatabaseMetaData::GetDriverVersion(), ODBCStatement::GetEscapeProcessing(), ODBCPreparedStatement::GetEscapeProcessing(), ODBCCallableStatement::GetEscapeProcessing(), ODBCDatabaseMetaData::GetExportedKeys(), ODBCDatabaseMetaData::GetExtraNameCharacters(), ODBCStatement::GetFetchSize(), ODBCPreparedStatement::GetFetchSize(), ODBCResultSet::GetFetchSize(), ODBCCallableStatement::GetFetchSize(), ODBCCallableStatement::GetFloat(), ODBCResultSet::GetFloat(), ODBCDatabaseMetaData::GetIdentifierQuoteString(), ODBCDatabaseMetaData::GetImportedKeys(), ODBCDatabaseMetaData::GetIndexInfo(), ODBCCallableStatement::GetInt(), ODBCResultSet::GetInt(), ODBCCallableStatement::GetLong(), ODBCResultSet::GetLong(), ODBCDatabaseMetaData::GetMaxBinaryLiteralLength(), ODBCDatabaseMetaData::GetMaxCatalogNameLength(), ODBCDatabaseMetaData::GetMaxCharLiteralLength(), ODBCDatabaseMetaData::GetMaxColumnNameLength(), ODBCDatabaseMetaData::GetMaxColumnsInGroupBy(), ODBCDatabaseMetaData::GetMaxColumnsInIndex(), ODBCDatabaseMetaData::GetMaxColumnsInOrderBy(), ODBCDatabaseMetaData::GetMaxColumnsInSelect(), ODBCDatabaseMetaData::GetMaxColumnsInTable(), ODBCDatabaseMetaData::GetMaxConnections(), ODBCDatabaseMetaData::GetMaxCursorNameLength(), ODBCStatement::GetMaxFieldSize(), ODBCPreparedStatement::GetMaxFieldSize(), ODBCCallableStatement::GetMaxFieldSize(), ODBCDatabaseMetaData::GetMaxIndexLength(), ODBCDatabaseMetaData::GetMaxProcedureNameLength(), ODBCStatement::GetMaxRows(), ODBCPreparedStatement::GetMaxRows(), ODBCCallableStatement::GetMaxRows(), ODBCDatabaseMetaData::GetMaxRowSize(), ODBCDatabaseMetaData::GetMaxSchemaNameLength(), ODBCDatabaseMetaData::GetMaxStatementLength(), ODBCDatabaseMetaData::GetMaxStatements(), ODBCDatabaseMetaData::GetMaxTableNameLength(), ODBCDatabaseMetaData::GetMaxTablesInSelect(), ODBCDatabaseMetaData::GetMaxUserNameLength(), ODBCConnection::GetMetaData(), ODBCStatement::GetMoreResults(), ODBCPreparedStatement::GetMoreResults(), ODBCCallableStatement::GetMoreResults(), ODBCDatabaseMetaData::GetNumericFunctions(), ODBCResultSetMetaData::GetPrecision(), ODBCDatabaseMetaData::GetPrimaryKeys(), ODBCDatabaseMetaData::GetProcedureColumns(), ODBCDatabaseMetaData::GetProcedures(), ODBCDatabaseMetaData::GetProcedureTerm(), ODBCStatement::GetQueryTimeout(), ODBCPreparedStatement::GetQueryTimeout(), ODBCCallableStatement::GetQueryTimeout(), ODBCStatement::GetResultSet(), ODBCPreparedStatement::GetResultSet(), ODBCCallableStatement::GetResultSet(), ODBCStatement::GetResultSetConcurrency(), ODBCPreparedStatement::GetResultSetConcurrency(), ODBCCallableStatement::GetResultSetConcurrency(), ODBCStatement::GetResultSetType(), ODBCPreparedStatement::GetResultSetType(), ODBCCallableStatement::GetResultSetType(), ODBCResultSet::GetRow(), ODBCResultSetMetaData::GetScale(), ODBCResultSetMetaData::GetSchemaName(), ODBCDatabaseMetaData::GetSchemas(), ODBCDatabaseMetaData::GetSchemaTerm(), ODBCDatabaseMetaData::GetSearchStringEscape(), ODBCCallableStatement::GetShort(), ODBCResultSet::GetShort(), ODBCDatabaseMetaData::GetSQLKeywords(), ODBCCallableStatement::GetString(), ODBCResultSet::GetString(), ODBCDatabaseMetaData::GetStringFunctions(), ODBCDatabaseMetaData::GetSystemFunctions(), ODBCResultSetMetaData::GetTableName(), ODBCDatabaseMetaData::GetTablePrivileges(), ODBCDatabaseMetaData::GetTables(), ODBCDatabaseMetaData::GetTableTerm(), ODBCDatabaseMetaData::GetTableTypes(), ODBCCallableStatement::GetTime(), ODBCResultSet::GetTime(), ODBCDatabaseMetaData::GetTimeDateFunctions(), ODBCCallableStatement::GetTimestamp(), ODBCResultSet::GetTimestamp(), ODBCConnection::GetTrace(), ODBCConnection::GetTraceFile(), ODBCConnection::GetTransactionIsolation(), ODBCResultSet::GetType(), ODBCDatabaseMetaData::GetTypeInfo(), ODBCStatement::GetUpdateCount(), ODBCPreparedStatement::GetUpdateCount(), ODBCCallableStatement::GetUpdateCount(), ODBCDatabaseMetaData::GetUserName(), ODBCDatabaseMetaData::GetVersionColumns(), ODBCResultSet::InsertRow(), ODBCDatabaseMetaData::InsertsAreDetected(), ODBCResultSet::IsAfterLast(), ODBCResultSetMetaData::IsAutoIncrement(), ODBCResultSet::IsBeforeFirst(), ODBCResultSetMetaData::IsCaseSensitive(), ODBCDatabaseMetaData::IsCatalogAtStart(), ODBCResultSetMetaData::IsCurrency(), ODBCResultSetMetaData::IsDefinitelyWritable(), ODBCResultSet::IsFirst(), ODBCResultSet::IsLast(), ODBCResultSetMetaData::IsNullable(), ODBCConnection::IsReadOnly(), ODBCDatabaseMetaData::IsReadOnly(), ODBCResultSetMetaData::IsReadOnly(), ODBCResultSetMetaData::IsSearchable(), ODBCResultSetMetaData::IsSigned(), ODBCResultSetMetaData::IsWritable(), ODBCResultSet::Last(), ODBCResultSet::MoveToCurrentRow(), ODBCResultSet::MoveToInsertRow(), ODBCConnection::NativeSQL(), ODBCResultSet::Next(), ODBCDatabaseMetaData::NullPlusNonNullIsNull(), ODBCDatabaseMetaData::NullsAreSortedAtEnd(), ODBCDatabaseMetaData::NullsAreSortedAtStart(), ODBCDatabaseMetaData::NullsAreSortedHigh(), ODBCDatabaseMetaData::NullsAreSortedLow(), ODBCConnection::ODBCConnection(), ODBCResultSet::ODBCResultSet(), ODBCDatabaseMetaData::OthersDeletesAreVisible(), ODBCDatabaseMetaData::OthersInsertsAreVisible(), ODBCDatabaseMetaData::OthersUpdatesAreVisible(), ODBCDatabaseMetaData::OwnDeletesAreVisible(), ODBCDatabaseMetaData::OwnInsertsAreVisible(), ODBCDatabaseMetaData::OwnUpdatesAreVisible(), ODBCConnection::PrepareCall(), ODBCConnection::PrepareStatement(), ODBCResultSet::Previous(), ODBCConnection::RefreshDataSources(), ODBCConnection::RefreshDrivers(), ODBCResultSet::RefreshRow(), ODBCCallableStatement::RegisterOutParameter(), ODBCResultSet::Relative(), ODBCConnection::Rollback(), ODBCResultSet::RowDeleted(), ODBCResultSet::RowInserted(), ODBCResultSet::RowUpdated(), ODBCPreparedStatement::SetAsciiStream(), ODBCCallableStatement::SetAsciiStream(), ODBCConnection::SetAutoCommit(), ODBCPreparedStatement::SetBinaryStream(), ODBCCallableStatement::SetBinaryStream(), ODBCPreparedStatement::SetBoolean(), ODBCCallableStatement::SetBoolean(), ODBCPreparedStatement::SetByte(), ODBCCallableStatement::SetByte(), ODBCPreparedStatement::SetBytes(), ODBCCallableStatement::SetBytes(), ODBCConnection::SetCatalog(), ODBCStatement::SetCursorName(), ODBCPreparedStatement::SetCursorName(), ODBCCallableStatement::SetCursorName(), ODBCPreparedStatement::SetDate(), ODBCCallableStatement::SetDate(), ODBCPreparedStatement::SetDouble(), ODBCCallableStatement::SetDouble(), ODBCStatement::SetEscapeProcessing(), ODBCPreparedStatement::SetEscapeProcessing(), ODBCCallableStatement::SetEscapeProcessing(), ODBCResultSet::SetFetchSize(), ODBCPreparedStatement::SetFloat(), ODBCCallableStatement::SetFloat(), ODBCPreparedStatement::SetInt(), ODBCCallableStatement::SetInt(), ODBCPreparedStatement::SetLong(), ODBCCallableStatement::SetLong(), ODBCStatement::SetMaxFieldSize(), ODBCPreparedStatement::SetMaxFieldSize(), ODBCCallableStatement::SetMaxFieldSize(), ODBCStatement::SetMaxRows(), ODBCPreparedStatement::SetMaxRows(), ODBCCallableStatement::SetMaxRows(), ODBCPreparedStatement::SetNull(), ODBCCallableStatement::SetNull(), ODBCStatement::SetQueryTimeout(), ODBCPreparedStatement::SetQueryTimeout(), ODBCCallableStatement::SetQueryTimeout(), ODBCConnection::SetReadOnly(), ODBCPreparedStatement::SetShort(), ODBCCallableStatement::SetShort(), ODBCPreparedStatement::SetString(), ODBCCallableStatement::SetString(), ODBCPreparedStatement::SetTime(), ODBCCallableStatement::SetTime(), ODBCPreparedStatement::SetTimestamp(), ODBCCallableStatement::SetTimestamp(), ODBCConnection::SetTrace(), ODBCConnection::SetTraceFile(), ODBCConnection::SetTransactionIsolation(), ODBCConnection::Shutdown(), ODBCDatabaseMetaData::StoresLowerCaseIdentifiers(), ODBCDatabaseMetaData::StoresLowerCaseQuotedIdentifiers(), ODBCDatabaseMetaData::StoresMixedCaseIdentifiers(), ODBCDatabaseMetaData::StoresMixedCaseQuotedIdentifiers(), ODBCDatabaseMetaData::StoresUpperCaseIdentifiers(), ODBCDatabaseMetaData::StoresUpperCaseQuotedIdentifiers(), ODBCDatabaseMetaData::SupportsAlterTableWithAddColumn(), ODBCDatabaseMetaData::SupportsAlterTableWithDropColumn(), ODBCDatabaseMetaData::SupportsANSI92EntryLevelSQL(), ODBCDatabaseMetaData::SupportsANSI92FullSQL(), ODBCDatabaseMetaData::SupportsANSI92IntermediateSQL(), ODBCDatabaseMetaData::SupportsBatchUpdates(), ODBCDatabaseMetaData::SupportsCatalogsInDataManipulation(), ODBCDatabaseMetaData::SupportsCatalogsInIndexDefinitions(), ODBCDatabaseMetaData::SupportsCatalogsInPrivilegeDefinitions(), ODBCDatabaseMetaData::SupportsCatalogsInProcedureCalls(), ODBCDatabaseMetaData::SupportsCatalogsInTableDefinitions(), ODBCDatabaseMetaData::SupportsColumnAliasing(), ODBCDatabaseMetaData::SupportsConvert(), ODBCDatabaseMetaData::SupportsCoreSQLGrammar(), ODBCDatabaseMetaData::SupportsCorrelatedSubqueries(), ODBCDatabaseMetaData::SupportsDataDefinitionAndDataManipulationTransactions(), ODBCDatabaseMetaData::SupportsDataManipulationTransactionsOnly(), ODBCDatabaseMetaData::SupportsDifferentTableCorrelationNames(), ODBCDatabaseMetaData::SupportsExpressionsInOrderBy(), ODBCDatabaseMetaData::SupportsExtendedSQLGrammar(), ODBCDatabaseMetaData::SupportsFullOuterJoins(), ODBCDatabaseMetaData::SupportsGroupBy(), ODBCDatabaseMetaData::SupportsGroupByBeyondSelect(), ODBCDatabaseMetaData::SupportsGroupByUnrelated(), ODBCDatabaseMetaData::SupportsIntegrityEnhancementFacility(), ODBCDatabaseMetaData::SupportsLikeEscapeClause(), ODBCDatabaseMetaData::SupportsLimitedOuterJoins(), ODBCDatabaseMetaData::SupportsMinimumSQLGrammar(), ODBCDatabaseMetaData::SupportsMixedCaseIdentifiers(), ODBCDatabaseMetaData::SupportsMixedCaseQuotedIdentifiers(), ODBCDatabaseMetaData::SupportsMultipleResultSets(), ODBCDatabaseMetaData::SupportsMultipleTransactions(), ODBCDatabaseMetaData::SupportsNonNullableColumns(), ODBCDatabaseMetaData::SupportsOpenCursorsAcrossCommit(), ODBCDatabaseMetaData::SupportsOpenCursorsAcrossRollback(), ODBCDatabaseMetaData::SupportsOpenStatementsAcrossCommit(), ODBCDatabaseMetaData::SupportsOpenStatementsAcrossRollback(), ODBCDatabaseMetaData::SupportsOrderByUnrelated(), ODBCDatabaseMetaData::SupportsOuterJoins(), ODBCDatabaseMetaData::SupportsPositionedDelete(), ODBCDatabaseMetaData::SupportsPositionedUpdate(), ODBCDatabaseMetaData::SupportsResultSetConcurrency(), ODBCDatabaseMetaData::SupportsResultSetType(), ODBCDatabaseMetaData::SupportsSchemasInDataManipulation(), ODBCDatabaseMetaData::SupportsSchemasInIndexDefinitions(), ODBCDatabaseMetaData::SupportsSchemasInPrivilegeDefinitions(), ODBCDatabaseMetaData::SupportsSchemasInProcedureCalls(), ODBCDatabaseMetaData::SupportsSchemasInTableDefinitions(), ODBCDatabaseMetaData::SupportsSelectForUpdate(), ODBCDatabaseMetaData::SupportsStoredProcedures(), ODBCDatabaseMetaData::SupportsSubqueriesInComparisons(), ODBCDatabaseMetaData::SupportsSubqueriesInExists(), ODBCDatabaseMetaData::SupportsSubqueriesInIns(), ODBCDatabaseMetaData::SupportsSubqueriesInQuantifieds(), ODBCDatabaseMetaData::SupportsTableCorrelationNames(), ODBCDatabaseMetaData::SupportsTransactionIsolationLevel(), ODBCDatabaseMetaData::SupportsTransactions(), ODBCDatabaseMetaData::SupportsUnion(), ODBCDatabaseMetaData::SupportsUnionAll(), ODBCResultSet::UpdateAsciiStream(), ODBCResultSet::UpdateBinaryStream(), ODBCResultSet::UpdateBoolean(), ODBCResultSet::UpdateByte(), ODBCResultSet::UpdateBytes(), ODBCResultSet::UpdateDate(), ODBCResultSet::UpdateDouble(), ODBCResultSet::UpdateFloat(), ODBCResultSet::UpdateInt(), ODBCResultSet::UpdateLong(), ODBCResultSet::UpdateNull(), ODBCResultSet::UpdateRow(), ODBCDatabaseMetaData::UpdatesAreDetected(), ODBCResultSet::UpdateShort(), ODBCResultSet::UpdateString(), ODBCResultSet::UpdateTime(), ODBCResultSet::UpdateTimestamp(), ODBCDatabaseMetaData::UsesLocalFilePerTable(), ODBCDatabaseMetaData::UsesLocalFiles(), ODBCCallableStatement::WasNull(), ODBCResultSet::WasNull(), ODBCCallableStatement::~ODBCCallableStatement(), ODBCConnection::~ODBCConnection(), ODBCPreparedStatement::~ODBCPreparedStatement(), ODBCResultSet::~ODBCResultSet(), ODBCResultSetMetaData::~ODBCResultSetMetaData(), and ODBCStatement::~ODBCStatement().
virtual const char* odbc::SQLException::what () const throw () inline virtual
Gets the description of this message
Definition at line 706 of file types.h.
View newest version in sPHENIX GitHub at line 706 of file types.h
References reason_.
Member Data Documentation
int odbc::SQLException::errorCode_ private
Definition at line 659 of file types.h.
View newest version in sPHENIX GitHub at line 659 of file types.h
Referenced by getErrorCode().
ODBCXX_STRING odbc::SQLException::reason_ private
Definition at line 657 of file types.h.
View newest version in sPHENIX GitHub at line 657 of file types.h
Referenced by getMessage(), and what().
ODBCXX_STRING odbc::SQLException::sqlState_ private
Definition at line 658 of file types.h.
View newest version in sPHENIX GitHub at line 658 of file types.h
Referenced by getSQLState().
The documentation for this class was generated from the following file:
RDBC/blob/master/include/RDBC/odbc++/types.h