Analysis Software: SColdQcdCorrelatorAnalysis::SEnergyCorrelator Class Reference
SColdQcdCorrelatorAnalysis::SEnergyCorrelator Class Reference
#include <analysis/blob/master/AndersonAnalysisModules/ColdQcdCorrelatorAnalysis/SEnergyCorrelator/src/SEnergyCorrelator.h>
Public Member Functions
SEnergyCorrelator (const string &name="SEnergyCorrelator", const bool isComplex=false, const bool doDebug=false, const bool inBatch=false)
~SEnergyCorrelator () override
int Init (PHCompositeNode *) override
int process_event (PHCompositeNode *) override
int End (PHCompositeNode *) override
Called at the end of all processing.
void Init ()
void Analyze ()
void End ()
void SetVerbosity (const int verb)
void SetInputNode (const string &iNodeName)
void SetOutputFile (const string &oFileName)
void SetDoSecondCstLoop (const bool loop)
void SetInputFiles (const vector< string > &vecInFileNames)
void SetInputTree (const string &iTreeName, const bool isTruthTree=false, const bool isEmbedTree=false)
void SetJetParameters (const vector< pair< double, double >> &pTjetBins, const pair< double, double > etaJetRange)
void SetConstituentParameters (const pair< double, double > momCstRange, const pair< double, double > drCstRange, const bool applyCstCuts=false)
void SetCorrelatorParameters (const uint32_t nPointCorr, const uint64_t nBinsDr, const pair< double, double > drBinRange)
void SetSubEventsToUse (const uint16_t subEvtOpt=0, const vector< int > vecSubEvtsToUse={})
int GetVerbosity ()
bool GetInDebugMode ()
bool GetInBatchMode ()
bool GetInComplexMode ()
bool GetInStandaloneMode ()
bool GetIsInputTreeTruth ()
bool GetIsInputTreeEmbed ()
bool GetApplyCstCuts ()
bool GetSelectSubEvts ()
bool GetDoSecondCstLoop ()
string GetModuleName ()
string GetInputNodeName ()
string GetInputTreeName ()
string GetOutputFileName ()
uint16_t GetSubEvtOpt ()
vector< string > GetInputFileNames ()
double GetMinDrBin ()
double GetMaxDrBin ()
double GetMinJetPt ()
double GetMaxJetPt ()
double GetMinJetEta ()
double GetMaxJetEta ()
double GetMinCstMom ()
double GetMaxCstMom ()
double GetMinCstDr ()
double GetMaxCstDr ()
size_t GetNBinsJetPt ()
uint32_t GetNPointCorr ()
uint64_t GetNBinsDr ()
Public Member Functions inherited from SubsysReco
~SubsysReco () override
virtual int EndRun (const int)
Called at the end of each run.
virtual int InitRun (PHCompositeNode *)
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
void Print (const std::string &="ALL") const override
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Private Types
enum CONST { NPARTONS = 2 }
Private Member Functions
void GrabInputNode ()
void OpenInputFiles ()
void OpenOutputFile ()
void SaveOutput ()
void CloseOutputFile ()
void InitializeMembers ()
void InitializeHists ()
void InitializeCorrs ()
void InitializeTree ()
void PrintMessage (const uint32_t code, const uint64_t nEvts=0, const uint64_t event=0)
void PrintDebug (const uint32_t code)
void PrintError (const uint32_t code, const size_t nDrBinEdges=0, const size_t iDrBin=0, const string sInFileName="")
bool CheckCriticalParameters ()
int64_t LoadTree (const uint64_t entry)
int64_t GetEntry (const uint64_t entry)
void DoCorrelatorCalculation ()
void ExtractHistsFromCorr ()
bool ApplyJetCuts (const double ptJet, const double etaJet)
bool ApplyCstCuts (const double momCst, const double drCst)
bool CheckIfSubEvtGood (const int embedID)
uint32_t GetJetPtBin (const double ptJet)
Private Attributes
TFile * m_outFile = NULL
TFile * m_inFile = NULL
TChain * m_inChain = NULL
vector< TH1D * > m_outHistVarDrAxis
vector< TH1D * > m_outHistErrDrAxis
vector< TH1D * > m_outHistVarLnDrAxis
vector< TH1D * > m_outHistErrLnDrAxis
TH2D * hCstPtOneVsDr
TH2D * hCstPtTwoVsDr
TH2D * hCstPtFracVsDr
TH2D * hCstPhiOneVsDr
TH2D * hCstPhiTwoVsDr
TH2D * hCstEtaOneVsDr
TH2D * hCstEtaTwoVsDr
TH2D * hDeltaPhiOneVsDr
TH2D * hDeltaPhiTwoVsDr
TH2D * hDeltaEtaOneVsDr
TH2D * hDeltaEtaTwoVsDr
TH2D * hJetPtFracOneVsDr
TH2D * hJetPtFracTwoVsDr
TH2D * hCstPairWeightVsDr
int m_fCurrent = 0
int m_verbosity = 0
bool m_inDebugMode = false
bool m_inBatchMode = false
bool m_inComplexMode = false
bool m_inStandaloneMode = false
bool m_isInputTreeTruth = false
bool m_isInputTreeEmbed = false
bool m_applyCstCuts = false
bool m_selectSubEvts = false
bool m_doSecondCstLoop = false
string m_moduleName = ""
string m_inNodeName = ""
string m_inTreeName = ""
string m_outFileName = ""
uint16_t m_subEvtOpt = 0
vector< string > m_inFileNames
uint32_t m_nPointCorr = 0
uint64_t m_nBinsDr = 0
size_t m_nBinsJetPt = 0
pair< double, double > m_drBinRange = {-999., -999.}
pair< double, double > m_ptJetRange = {-999., -999.}
pair< double, double > m_etaJetRange = {-999., -999.}
pair< double, double > m_momCstRange = {-999., -999.}
pair< double, double > m_drCstRange = {-999., -999.}
vector< pair< double, double > > m_ptJetBins
vector< PseudoJet > m_jetCstVector
vector< int > m_subEvtsToUse
vector
< contrib::eec::EECLongestSide
< contrib::eec::hist::axis::log > * > m_eecLongSide
int m_evtNumChrgPars = -999
int m_partonID [CONST::NPARTONS] = {-999, -999}
double m_partonMomX [CONST::NPARTONS] = {-999., -999.}
double m_partonMomY [CONST::NPARTONS] = {-999., -999.}
double m_partonMomZ [CONST::NPARTONS] = {-999., -999.}
double m_evtSumPar = -999.
vector< vector< int > > * m_cstID = NULL
vector< vector< int > > * m_cstEmbedID = NULL
int m_evtNumTrks = -999
double m_evtSumECal = -999.
double m_evtSumHCal = -999.
vector< vector< int > > * m_cstMatchID = NULL
int m_evtNumJets = -999
double m_evtVtxX = -999.
double m_evtVtxY = -999.
double m_evtVtxZ = -999.
vector< unsigned long > * m_jetNumCst = NULL
vector< unsigned int > * m_jetID = NULL
vector< unsigned int > * m_jetTruthID = NULL
vector< double > * m_jetEnergy = NULL
vector< double > * m_jetPt = NULL
vector< double > * m_jetEta = NULL
vector< double > * m_jetPhi = NULL
vector< double > * m_jetArea = NULL
vector< vector< double > > * m_cstZ = NULL
vector< vector< double > > * m_cstDr = NULL
vector< vector< double > > * m_cstEnergy = NULL
vector< vector< double > > * m_cstPt = NULL
vector< vector< double > > * m_cstEta = NULL
vector< vector< double > > * m_cstPhi = NULL
TBranch * m_brPartonID [CONST::NPARTONS] = {NULL, NULL}
TBranch * m_brPartonMomX [CONST::NPARTONS] = {NULL, NULL}
TBranch * m_brPartonMomY [CONST::NPARTONS] = {NULL, NULL}
TBranch * m_brPartonMomZ [CONST::NPARTONS] = {NULL, NULL}
TBranch * m_brEvtSumPar = NULL
TBranch * m_brCstID = NULL
TBranch * m_brCstEmbedID = NULL
TBranch * m_brEvtNumTrks = NULL
TBranch * m_brEvtSumECal = NULL
TBranch * m_brEvtSumHCal = NULL
TBranch * m_brCstMatchID = NULL
TBranch * m_brEvtNumJets = NULL
TBranch * m_brEvtVtxX = NULL
TBranch * m_brEvtVtxY = NULL
TBranch * m_brEvtVtxZ = NULL
TBranch * m_brJetNumCst = NULL
TBranch * m_brJetID = NULL
TBranch * m_brJetEnergy = NULL
TBranch * m_brJetPt = NULL
TBranch * m_brJetEta = NULL
TBranch * m_brJetPhi = NULL
TBranch * m_brJetArea = NULL
TBranch * m_brCstZ = NULL
TBranch * m_brCstDr = NULL
TBranch * m_brCstPt = NULL
TBranch * m_brCstEnergy = NULL
TBranch * m_brCstEta = NULL
TBranch * m_brCstPhi = NULL
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = std::numeric_limits<int>::max() - 10
}
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Detailed Description
Definition at line 56 of file SEnergyCorrelator.h.
View newest version in sPHENIX GitHub at line 56 of file SEnergyCorrelator.h
Member Enumeration Documentation
enum SColdQcdCorrelatorAnalysis::SEnergyCorrelator::CONST private
Enumerator:
NPARTONS
Definition at line 124 of file SEnergyCorrelator.h.
View newest version in sPHENIX GitHub at line 124 of file SEnergyCorrelator.h
Constructor & Destructor Documentation
SColdQcdCorrelatorAnalysis::SEnergyCorrelator::SEnergyCorrelator (const string & name = "SEnergyCorrelator", const bool isComplex = false, const bool doDebug = false, const bool inBatch = false)
Definition at line 28 of file SEnergyCorrelator.cc.
View newest version in sPHENIX GitHub at line 28 of file SEnergyCorrelator.cc
References InitializeMembers(), m_inBatchMode, m_inComplexMode, m_inDebugMode, m_inStandaloneMode, m_moduleName, m_verbosity, perf_headwind::name, PrintDebug(), PrintMessage(), and Fun4AllBase::Verbosity().
SColdQcdCorrelatorAnalysis::SEnergyCorrelator::~SEnergyCorrelator () override
Definition at line 60 of file SEnergyCorrelator.cc.
View newest version in sPHENIX GitHub at line 60 of file SEnergyCorrelator.cc
References m_eecLongSide, m_inChain, m_inDebugMode, m_inFileNames, m_nBinsJetPt, m_outFile, m_outHistErrDrAxis, m_outHistErrLnDrAxis, m_outHistVarDrAxis, m_outHistVarLnDrAxis, m_ptJetBins, and PrintDebug().
Member Function Documentation
void SColdQcdCorrelatorAnalysis::SEnergyCorrelator::Analyze ()
Definition at line 149 of file SEnergyCorrelator.cc.
View newest version in sPHENIX GitHub at line 149 of file SEnergyCorrelator.cc
References assert, DoCorrelatorCalculation(), ExtractHistsFromCorr(), m_inComplexMode, m_inDebugMode, m_inStandaloneMode, PrintDebug(), PrintError(), and PrintMessage().
bool SColdQcdCorrelatorAnalysis::SEnergyCorrelator::ApplyCstCuts (const double momCst, const double drCst) private
Definition at line 272 of file SEnergyCorrelator.ana.h.
View newest version in sPHENIX GitHub at line 272 of file SEnergyCorrelator.ana.h
bool SColdQcdCorrelatorAnalysis::SEnergyCorrelator::ApplyJetCuts (const double ptJet, const double etaJet) private
Definition at line 258 of file SEnergyCorrelator.ana.h.
View newest version in sPHENIX GitHub at line 258 of file SEnergyCorrelator.ana.h
bool SColdQcdCorrelatorAnalysis::SEnergyCorrelator::CheckCriticalParameters () private
Definition at line 532 of file SEnergyCorrelator.sys.h.
View newest version in sPHENIX GitHub at line 532 of file SEnergyCorrelator.sys.h
bool SColdQcdCorrelatorAnalysis::SEnergyCorrelator::CheckIfSubEvtGood (const int embedID) private
Definition at line 286 of file SEnergyCorrelator.ana.h.
View newest version in sPHENIX GitHub at line 286 of file SEnergyCorrelator.ana.h
void SColdQcdCorrelatorAnalysis::SEnergyCorrelator::CloseOutputFile () private
Definition at line 219 of file SEnergyCorrelator.io.h.
View newest version in sPHENIX GitHub at line 219 of file SEnergyCorrelator.io.h
References cd(), and Close().
Referenced by End().
void SColdQcdCorrelatorAnalysis::SEnergyCorrelator::DoCorrelatorCalculation () private
Definition at line 22 of file SEnergyCorrelator.ana.h.
View newest version in sPHENIX GitHub at line 22 of file SEnergyCorrelator.ana.h
References Acts::Test::at, entry, Fill(), SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::GetEntry(), and SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::LoadTree().
Referenced by Analyze().
int SColdQcdCorrelatorAnalysis::SEnergyCorrelator::End (PHCompositeNode *) override virtual
Called at the end of all processing.
Reimplemented from SubsysReco.
Definition at line 111 of file SEnergyCorrelator.cc.
View newest version in sPHENIX GitHub at line 111 of file SEnergyCorrelator.cc
References Fun4AllReturnCodes::EVENT_OK.
void SColdQcdCorrelatorAnalysis::SEnergyCorrelator::End ()
Definition at line 172 of file SEnergyCorrelator.cc.
View newest version in sPHENIX GitHub at line 172 of file SEnergyCorrelator.cc
References assert, CloseOutputFile(), m_inComplexMode, m_inDebugMode, m_inStandaloneMode, PrintDebug(), PrintError(), PrintMessage(), and SaveOutput().
void SColdQcdCorrelatorAnalysis::SEnergyCorrelator::ExtractHistsFromCorr () private
Definition at line 149 of file SEnergyCorrelator.ana.h.
View newest version in sPHENIX GitHub at line 149 of file SEnergyCorrelator.ana.h
References assert, SetBinContent(), and SetBinError().
Referenced by Analyze().
bool SColdQcdCorrelatorAnalysis::SEnergyCorrelator::GetApplyCstCuts () inline
Definition at line 96 of file SEnergyCorrelator.h.
View newest version in sPHENIX GitHub at line 96 of file SEnergyCorrelator.h
bool SColdQcdCorrelatorAnalysis::SEnergyCorrelator::GetDoSecondCstLoop () inline
Definition at line 98 of file SEnergyCorrelator.h.
View newest version in sPHENIX GitHub at line 98 of file SEnergyCorrelator.h
int64_t SColdQcdCorrelatorAnalysis::SEnergyCorrelator::GetEntry (const uint64_t entry) private
Definition at line 544 of file SEnergyCorrelator.sys.h.
View newest version in sPHENIX GitHub at line 544 of file SEnergyCorrelator.sys.h
References SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::GetEntry().
bool SColdQcdCorrelatorAnalysis::SEnergyCorrelator::GetInBatchMode () inline
Definition at line 91 of file SEnergyCorrelator.h.
View newest version in sPHENIX GitHub at line 91 of file SEnergyCorrelator.h
bool SColdQcdCorrelatorAnalysis::SEnergyCorrelator::GetInComplexMode () inline
Definition at line 92 of file SEnergyCorrelator.h.
View newest version in sPHENIX GitHub at line 92 of file SEnergyCorrelator.h
bool SColdQcdCorrelatorAnalysis::SEnergyCorrelator::GetInDebugMode () inline
Definition at line 90 of file SEnergyCorrelator.h.
View newest version in sPHENIX GitHub at line 90 of file SEnergyCorrelator.h
vector<string> SColdQcdCorrelatorAnalysis::SEnergyCorrelator::GetInputFileNames () inline
Definition at line 104 of file SEnergyCorrelator.h.
View newest version in sPHENIX GitHub at line 104 of file SEnergyCorrelator.h
string SColdQcdCorrelatorAnalysis::SEnergyCorrelator::GetInputNodeName () inline
Definition at line 100 of file SEnergyCorrelator.h.
View newest version in sPHENIX GitHub at line 100 of file SEnergyCorrelator.h
string SColdQcdCorrelatorAnalysis::SEnergyCorrelator::GetInputTreeName () inline
Definition at line 101 of file SEnergyCorrelator.h.
View newest version in sPHENIX GitHub at line 101 of file SEnergyCorrelator.h
bool SColdQcdCorrelatorAnalysis::SEnergyCorrelator::GetInStandaloneMode () inline
Definition at line 93 of file SEnergyCorrelator.h.
View newest version in sPHENIX GitHub at line 93 of file SEnergyCorrelator.h
bool SColdQcdCorrelatorAnalysis::SEnergyCorrelator::GetIsInputTreeEmbed () inline
Definition at line 95 of file SEnergyCorrelator.h.
View newest version in sPHENIX GitHub at line 95 of file SEnergyCorrelator.h
bool SColdQcdCorrelatorAnalysis::SEnergyCorrelator::GetIsInputTreeTruth () inline
Definition at line 94 of file SEnergyCorrelator.h.
View newest version in sPHENIX GitHub at line 94 of file SEnergyCorrelator.h
uint32_t SColdQcdCorrelatorAnalysis::SEnergyCorrelator::GetJetPtBin (const double ptJet) private
Definition at line 343 of file SEnergyCorrelator.ana.h.
View newest version in sPHENIX GitHub at line 343 of file SEnergyCorrelator.ana.h
double SColdQcdCorrelatorAnalysis::SEnergyCorrelator::GetMaxCstDr () inline
Definition at line 116 of file SEnergyCorrelator.h.
View newest version in sPHENIX GitHub at line 116 of file SEnergyCorrelator.h
double SColdQcdCorrelatorAnalysis::SEnergyCorrelator::GetMaxCstMom () inline
Definition at line 114 of file SEnergyCorrelator.h.
View newest version in sPHENIX GitHub at line 114 of file SEnergyCorrelator.h
double SColdQcdCorrelatorAnalysis::SEnergyCorrelator::GetMaxDrBin () inline
Definition at line 108 of file SEnergyCorrelator.h.
View newest version in sPHENIX GitHub at line 108 of file SEnergyCorrelator.h
double SColdQcdCorrelatorAnalysis::SEnergyCorrelator::GetMaxJetEta () inline
Definition at line 112 of file SEnergyCorrelator.h.
View newest version in sPHENIX GitHub at line 112 of file SEnergyCorrelator.h
double SColdQcdCorrelatorAnalysis::SEnergyCorrelator::GetMaxJetPt () inline
Definition at line 110 of file SEnergyCorrelator.h.
View newest version in sPHENIX GitHub at line 110 of file SEnergyCorrelator.h
double SColdQcdCorrelatorAnalysis::SEnergyCorrelator::GetMinCstDr () inline
Definition at line 115 of file SEnergyCorrelator.h.
View newest version in sPHENIX GitHub at line 115 of file SEnergyCorrelator.h
double SColdQcdCorrelatorAnalysis::SEnergyCorrelator::GetMinCstMom () inline
Definition at line 113 of file SEnergyCorrelator.h.
View newest version in sPHENIX GitHub at line 113 of file SEnergyCorrelator.h
double SColdQcdCorrelatorAnalysis::SEnergyCorrelator::GetMinDrBin () inline
Definition at line 107 of file SEnergyCorrelator.h.
View newest version in sPHENIX GitHub at line 107 of file SEnergyCorrelator.h
double SColdQcdCorrelatorAnalysis::SEnergyCorrelator::GetMinJetEta () inline
Definition at line 111 of file SEnergyCorrelator.h.
View newest version in sPHENIX GitHub at line 111 of file SEnergyCorrelator.h
double SColdQcdCorrelatorAnalysis::SEnergyCorrelator::GetMinJetPt () inline
Definition at line 109 of file SEnergyCorrelator.h.
View newest version in sPHENIX GitHub at line 109 of file SEnergyCorrelator.h
string SColdQcdCorrelatorAnalysis::SEnergyCorrelator::GetModuleName () inline
Definition at line 99 of file SEnergyCorrelator.h.
View newest version in sPHENIX GitHub at line 99 of file SEnergyCorrelator.h
uint64_t SColdQcdCorrelatorAnalysis::SEnergyCorrelator::GetNBinsDr () inline
Definition at line 119 of file SEnergyCorrelator.h.
View newest version in sPHENIX GitHub at line 119 of file SEnergyCorrelator.h
size_t SColdQcdCorrelatorAnalysis::SEnergyCorrelator::GetNBinsJetPt () inline
Definition at line 117 of file SEnergyCorrelator.h.
View newest version in sPHENIX GitHub at line 117 of file SEnergyCorrelator.h
uint32_t SColdQcdCorrelatorAnalysis::SEnergyCorrelator::GetNPointCorr () inline
Definition at line 118 of file SEnergyCorrelator.h.
View newest version in sPHENIX GitHub at line 118 of file SEnergyCorrelator.h
string SColdQcdCorrelatorAnalysis::SEnergyCorrelator::GetOutputFileName () inline
Definition at line 102 of file SEnergyCorrelator.h.
View newest version in sPHENIX GitHub at line 102 of file SEnergyCorrelator.h
bool SColdQcdCorrelatorAnalysis::SEnergyCorrelator::GetSelectSubEvts () inline
Definition at line 97 of file SEnergyCorrelator.h.
View newest version in sPHENIX GitHub at line 97 of file SEnergyCorrelator.h
uint16_t SColdQcdCorrelatorAnalysis::SEnergyCorrelator::GetSubEvtOpt () inline
Definition at line 103 of file SEnergyCorrelator.h.
View newest version in sPHENIX GitHub at line 103 of file SEnergyCorrelator.h
int SColdQcdCorrelatorAnalysis::SEnergyCorrelator::GetVerbosity () inline
Definition at line 89 of file SEnergyCorrelator.h.
View newest version in sPHENIX GitHub at line 89 of file SEnergyCorrelator.h
void SColdQcdCorrelatorAnalysis::SEnergyCorrelator::GrabInputNode () private
Definition at line 121 of file SEnergyCorrelator.io.h.
View newest version in sPHENIX GitHub at line 121 of file SEnergyCorrelator.io.h
int SColdQcdCorrelatorAnalysis::SEnergyCorrelator::Init (PHCompositeNode *) override virtual
Called during initialization. Typically this is where you can book histograms, and e.g. register them to Fun4AllServer (so they can be output to file using Fun4AllServer::dumpHistos() method).
Reimplemented from SubsysReco.
Definition at line 92 of file SEnergyCorrelator.cc.
View newest version in sPHENIX GitHub at line 92 of file SEnergyCorrelator.cc
References Fun4AllReturnCodes::EVENT_OK.
void SColdQcdCorrelatorAnalysis::SEnergyCorrelator::Init ()
Definition at line 122 of file SEnergyCorrelator.cc.
View newest version in sPHENIX GitHub at line 122 of file SEnergyCorrelator.cc
References assert, InitializeCorrs(), InitializeHists(), InitializeTree(), m_inComplexMode, m_inDebugMode, m_inStandaloneMode, OpenInputFiles(), OpenOutputFile(), PrintDebug(), PrintError(), and PrintMessage().
void SColdQcdCorrelatorAnalysis::SEnergyCorrelator::InitializeCorrs () private
Definition at line 151 of file SEnergyCorrelator.sys.h.
View newest version in sPHENIX GitHub at line 151 of file SEnergyCorrelator.sys.h
Referenced by Init().
void SColdQcdCorrelatorAnalysis::SEnergyCorrelator::InitializeHists () private
Definition at line 102 of file SEnergyCorrelator.sys.h.
View newest version in sPHENIX GitHub at line 102 of file SEnergyCorrelator.sys.h
Referenced by Init().
void SColdQcdCorrelatorAnalysis::SEnergyCorrelator::InitializeMembers () private
Definition at line 22 of file SEnergyCorrelator.sys.h.
View newest version in sPHENIX GitHub at line 22 of file SEnergyCorrelator.sys.h
Referenced by SEnergyCorrelator().
void SColdQcdCorrelatorAnalysis::SEnergyCorrelator::InitializeTree () private
Definition at line 42 of file SEnergyCorrelator.sys.h.
View newest version in sPHENIX GitHub at line 42 of file SEnergyCorrelator.sys.h
References assert, and SetBranchAddress().
Referenced by Init().
int64_t SColdQcdCorrelatorAnalysis::SEnergyCorrelator::LoadTree (const uint64_t entry) private
Definition at line 561 of file SEnergyCorrelator.sys.h.
View newest version in sPHENIX GitHub at line 561 of file SEnergyCorrelator.sys.h
References SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::LoadTree().
void SColdQcdCorrelatorAnalysis::SEnergyCorrelator::OpenInputFiles () private
Definition at line 133 of file SEnergyCorrelator.io.h.
View newest version in sPHENIX GitHub at line 133 of file SEnergyCorrelator.io.h
References assert, and configureMap::inFileName.
Referenced by Init().
void SColdQcdCorrelatorAnalysis::SEnergyCorrelator::OpenOutputFile () private
Definition at line 162 of file SEnergyCorrelator.io.h.
View newest version in sPHENIX GitHub at line 162 of file SEnergyCorrelator.io.h
References assert.
Referenced by Init().
void SColdQcdCorrelatorAnalysis::SEnergyCorrelator::PrintDebug (const uint32_t code) private
Definition at line 292 of file SEnergyCorrelator.sys.h.
View newest version in sPHENIX GitHub at line 292 of file SEnergyCorrelator.sys.h
Referenced by Analyze(), End(), Init(), SEnergyCorrelator(), and ~SEnergyCorrelator().
void SColdQcdCorrelatorAnalysis::SEnergyCorrelator::PrintError (const uint32_t code, const size_t nDrBinEdges = 0, const size_t iDrBin = 0, const string sInFileName = "") private
Definition at line 409 of file SEnergyCorrelator.sys.h.
View newest version in sPHENIX GitHub at line 409 of file SEnergyCorrelator.sys.h
Referenced by Analyze(), End(), and Init().
void SColdQcdCorrelatorAnalysis::SEnergyCorrelator::PrintMessage (const uint32_t code, const uint64_t nEvts = 0, const uint64_t event = 0) private
Definition at line 169 of file SEnergyCorrelator.sys.h.
View newest version in sPHENIX GitHub at line 169 of file SEnergyCorrelator.sys.h
References material_mapping_optimisation::flush, and configureMap::inFileName.
Referenced by Analyze(), End(), Init(), and SEnergyCorrelator().
int SColdQcdCorrelatorAnalysis::SEnergyCorrelator::process_event (PHCompositeNode *) override virtual
Called for each event. This is where you do the real work.
Reimplemented from SubsysReco.
Definition at line 102 of file SEnergyCorrelator.cc.
View newest version in sPHENIX GitHub at line 102 of file SEnergyCorrelator.cc
References Fun4AllReturnCodes::EVENT_OK.
void SColdQcdCorrelatorAnalysis::SEnergyCorrelator::SaveOutput () private
Definition at line 179 of file SEnergyCorrelator.io.h.
View newest version in sPHENIX GitHub at line 179 of file SEnergyCorrelator.io.h
References cd(), and Write().
Referenced by End().
void SColdQcdCorrelatorAnalysis::SEnergyCorrelator::SetConstituentParameters (const pair< double, double > momCstRange, const pair< double, double > drCstRange, const bool applyCstCuts = false)
Definition at line 59 of file SEnergyCorrelator.io.h.
View newest version in sPHENIX GitHub at line 59 of file SEnergyCorrelator.io.h
void SColdQcdCorrelatorAnalysis::SEnergyCorrelator::SetCorrelatorParameters (const uint32_t nPointCorr, const uint64_t nBinsDr, const pair< double, double > drBinRange)
Definition at line 76 of file SEnergyCorrelator.io.h.
View newest version in sPHENIX GitHub at line 76 of file SEnergyCorrelator.io.h
void SColdQcdCorrelatorAnalysis::SEnergyCorrelator::SetDoSecondCstLoop (const bool loop) inline
Definition at line 78 of file SEnergyCorrelator.h.
View newest version in sPHENIX GitHub at line 78 of file SEnergyCorrelator.h
void SColdQcdCorrelatorAnalysis::SEnergyCorrelator::SetInputFiles (const vector< string > & vecInFileNames) inline
Definition at line 79 of file SEnergyCorrelator.h.
View newest version in sPHENIX GitHub at line 79 of file SEnergyCorrelator.h
void SColdQcdCorrelatorAnalysis::SEnergyCorrelator::SetInputNode (const string & iNodeName) inline
Definition at line 76 of file SEnergyCorrelator.h.
View newest version in sPHENIX GitHub at line 76 of file SEnergyCorrelator.h
void SColdQcdCorrelatorAnalysis::SEnergyCorrelator::SetInputTree (const string & iTreeName, const bool isTruthTree = false, const bool isEmbedTree = false)
Definition at line 21 of file SEnergyCorrelator.io.h.
View newest version in sPHENIX GitHub at line 21 of file SEnergyCorrelator.io.h
void SColdQcdCorrelatorAnalysis::SEnergyCorrelator::SetJetParameters (const vector< pair< double, double >> & pTjetBins, const pair< double, double > etaJetRange)
Definition at line 35 of file SEnergyCorrelator.io.h.
View newest version in sPHENIX GitHub at line 35 of file SEnergyCorrelator.io.h
References physmon_track_finding_ttbar::minPt.
void SColdQcdCorrelatorAnalysis::SEnergyCorrelator::SetOutputFile (const string & oFileName) inline
Definition at line 77 of file SEnergyCorrelator.h.
View newest version in sPHENIX GitHub at line 77 of file SEnergyCorrelator.h
void SColdQcdCorrelatorAnalysis::SEnergyCorrelator::SetSubEventsToUse (const uint16_t subEvtOpt = 0, const vector< int > vecSubEvtsToUse = {})
Definition at line 93 of file SEnergyCorrelator.io.h.
View newest version in sPHENIX GitHub at line 93 of file SEnergyCorrelator.io.h
void SColdQcdCorrelatorAnalysis::SEnergyCorrelator::SetVerbosity (const int verb) inline
Definition at line 75 of file SEnergyCorrelator.h.
View newest version in sPHENIX GitHub at line 75 of file SEnergyCorrelator.h
Member Data Documentation
TH2D* SColdQcdCorrelatorAnalysis::SEnergyCorrelator::hCstEtaOneVsDr private
Definition at line 172 of file SEnergyCorrelator.h.
View newest version in sPHENIX GitHub at line 172 of file SEnergyCorrelator.h
TH2D* SColdQcdCorrelatorAnalysis::SEnergyCorrelator::hCstEtaTwoVsDr private
Definition at line 173 of file SEnergyCorrelator.h.
View newest version in sPHENIX GitHub at line 173 of file SEnergyCorrelator.h
TH2D* SColdQcdCorrelatorAnalysis::SEnergyCorrelator::hCstPairWeightVsDr private
Definition at line 180 of file SEnergyCorrelator.h.
View newest version in sPHENIX GitHub at line 180 of file SEnergyCorrelator.h
TH2D* SColdQcdCorrelatorAnalysis::SEnergyCorrelator::hCstPhiOneVsDr private
Definition at line 170 of file SEnergyCorrelator.h.
View newest version in sPHENIX GitHub at line 170 of file SEnergyCorrelator.h
TH2D* SColdQcdCorrelatorAnalysis::SEnergyCorrelator::hCstPhiTwoVsDr private
Definition at line 171 of file SEnergyCorrelator.h.
View newest version in sPHENIX GitHub at line 171 of file SEnergyCorrelator.h
TH2D* SColdQcdCorrelatorAnalysis::SEnergyCorrelator::hCstPtFracVsDr private
Definition at line 169 of file SEnergyCorrelator.h.
View newest version in sPHENIX GitHub at line 169 of file SEnergyCorrelator.h
TH2D* SColdQcdCorrelatorAnalysis::SEnergyCorrelator::hCstPtOneVsDr private
Definition at line 167 of file SEnergyCorrelator.h.
View newest version in sPHENIX GitHub at line 167 of file SEnergyCorrelator.h
TH2D* SColdQcdCorrelatorAnalysis::SEnergyCorrelator::hCstPtTwoVsDr private
Definition at line 168 of file SEnergyCorrelator.h.
View newest version in sPHENIX GitHub at line 168 of file SEnergyCorrelator.h
TH2D* SColdQcdCorrelatorAnalysis::SEnergyCorrelator::hDeltaEtaOneVsDr private
Definition at line 176 of file SEnergyCorrelator.h.
View newest version in sPHENIX GitHub at line 176 of file SEnergyCorrelator.h
TH2D* SColdQcdCorrelatorAnalysis::SEnergyCorrelator::hDeltaEtaTwoVsDr private
Definition at line 177 of file SEnergyCorrelator.h.
View newest version in sPHENIX GitHub at line 177 of file SEnergyCorrelator.h
TH2D* SColdQcdCorrelatorAnalysis::SEnergyCorrelator::hDeltaPhiOneVsDr private
Definition at line 174 of file SEnergyCorrelator.h.
View newest version in sPHENIX GitHub at line 174 of file SEnergyCorrelator.h
TH2D* SColdQcdCorrelatorAnalysis::SEnergyCorrelator::hDeltaPhiTwoVsDr private
Definition at line 175 of file SEnergyCorrelator.h.
View newest version in sPHENIX GitHub at line 175 of file SEnergyCorrelator.h
TH2D* SColdQcdCorrelatorAnalysis::SEnergyCorrelator::hJetPtFracOneVsDr private
Definition at line 178 of file SEnergyCorrelator.h.
View newest version in sPHENIX GitHub at line 178 of file SEnergyCorrelator.h
TH2D* SColdQcdCorrelatorAnalysis::SEnergyCorrelator::hJetPtFracTwoVsDr private
Definition at line 179 of file SEnergyCorrelator.h.
View newest version in sPHENIX GitHub at line 179 of file SEnergyCorrelator.h
bool SColdQcdCorrelatorAnalysis::SEnergyCorrelator::m_applyCstCuts = false private
Definition at line 191 of file SEnergyCorrelator.h.
View newest version in sPHENIX GitHub at line 191 of file SEnergyCorrelator.h
TBranch* SColdQcdCorrelatorAnalysis::SEnergyCorrelator::m_brCstDr = NULL private
Definition at line 281 of file SEnergyCorrelator.h.
View newest version in sPHENIX GitHub at line 281 of file SEnergyCorrelator.h
TBranch* SColdQcdCorrelatorAnalysis::SEnergyCorrelator::m_brCstEmbedID = NULL private
Definition at line 261 of file SEnergyCorrelator.h.
View newest version in sPHENIX GitHub at line 261 of file SEnergyCorrelator.h
TBranch* SColdQcdCorrelatorAnalysis::SEnergyCorrelator::m_brCstEnergy = NULL private
Definition at line 283 of file SEnergyCorrelator.h.
View newest version in sPHENIX GitHub at line 283 of file SEnergyCorrelator.h
TBranch* SColdQcdCorrelatorAnalysis::SEnergyCorrelator::m_brCstEta = NULL private
Definition at line 284 of file SEnergyCorrelator.h.
View newest version in sPHENIX GitHub at line 284 of file SEnergyCorrelator.h
TBranch* SColdQcdCorrelatorAnalysis::SEnergyCorrelator::m_brCstID = NULL private
Definition at line 260 of file SEnergyCorrelator.h.
View newest version in sPHENIX GitHub at line 260 of file SEnergyCorrelator.h
TBranch* SColdQcdCorrelatorAnalysis::SEnergyCorrelator::m_brCstMatchID = NULL private
Definition at line 266 of file SEnergyCorrelator.h.
View newest version in sPHENIX GitHub at line 266 of file SEnergyCorrelator.h
TBranch* SColdQcdCorrelatorAnalysis::SEnergyCorrelator::m_brCstPhi = NULL private
Definition at line 285 of file SEnergyCorrelator.h.
View newest version in sPHENIX GitHub at line 285 of file SEnergyCorrelator.h
TBranch* SColdQcdCorrelatorAnalysis::SEnergyCorrelator::m_brCstPt = NULL private
Definition at line 282 of file SEnergyCorrelator.h.
View newest version in sPHENIX GitHub at line 282 of file SEnergyCorrelator.h
TBranch* SColdQcdCorrelatorAnalysis::SEnergyCorrelator::m_brCstZ = NULL private
Definition at line 280 of file SEnergyCorrelator.h.
View newest version in sPHENIX GitHub at line 280 of file SEnergyCorrelator.h
TBranch* SColdQcdCorrelatorAnalysis::SEnergyCorrelator::m_brEvtNumJets = NULL private
Definition at line 269 of file SEnergyCorrelator.h.
View newest version in sPHENIX GitHub at line 269 of file SEnergyCorrelator.h
TBranch* SColdQcdCorrelatorAnalysis::SEnergyCorrelator::m_brEvtNumTrks = NULL private
Definition at line 263 of file SEnergyCorrelator.h.
View newest version in sPHENIX GitHub at line 263 of file SEnergyCorrelator.h
TBranch* SColdQcdCorrelatorAnalysis::SEnergyCorrelator::m_brEvtSumECal = NULL private
Definition at line 264 of file SEnergyCorrelator.h.
View newest version in sPHENIX GitHub at line 264 of file SEnergyCorrelator.h
TBranch* SColdQcdCorrelatorAnalysis::SEnergyCorrelator::m_brEvtSumHCal = NULL private
Definition at line 265 of file SEnergyCorrelator.h.
View newest version in sPHENIX GitHub at line 265 of file SEnergyCorrelator.h
TBranch* SColdQcdCorrelatorAnalysis::SEnergyCorrelator::m_brEvtSumPar = NULL private
Definition at line 259 of file SEnergyCorrelator.h.
View newest version in sPHENIX GitHub at line 259 of file SEnergyCorrelator.h
TBranch* SColdQcdCorrelatorAnalysis::SEnergyCorrelator::m_brEvtVtxX = NULL private
Definition at line 270 of file SEnergyCorrelator.h.
View newest version in sPHENIX GitHub at line 270 of file SEnergyCorrelator.h
TBranch* SColdQcdCorrelatorAnalysis::SEnergyCorrelator::m_brEvtVtxY = NULL private
Definition at line 271 of file SEnergyCorrelator.h.
View newest version in sPHENIX GitHub at line 271 of file SEnergyCorrelator.h
TBranch* SColdQcdCorrelatorAnalysis::SEnergyCorrelator::m_brEvtVtxZ = NULL private
Definition at line 272 of file SEnergyCorrelator.h.
View newest version in sPHENIX GitHub at line 272 of file SEnergyCorrelator.h
TBranch* SColdQcdCorrelatorAnalysis::SEnergyCorrelator::m_brJetArea = NULL private
Definition at line 279 of file SEnergyCorrelator.h.
View newest version in sPHENIX GitHub at line 279 of file SEnergyCorrelator.h
TBranch* SColdQcdCorrelatorAnalysis::SEnergyCorrelator::m_brJetEnergy = NULL private
Definition at line 275 of file SEnergyCorrelator.h.
View newest version in sPHENIX GitHub at line 275 of file SEnergyCorrelator.h
TBranch* SColdQcdCorrelatorAnalysis::SEnergyCorrelator::m_brJetEta = NULL private
Definition at line 277 of file SEnergyCorrelator.h.
View newest version in sPHENIX GitHub at line 277 of file SEnergyCorrelator.h
TBranch* SColdQcdCorrelatorAnalysis::SEnergyCorrelator::m_brJetID = NULL private
Definition at line 274 of file SEnergyCorrelator.h.
View newest version in sPHENIX GitHub at line 274 of file SEnergyCorrelator.h
TBranch* SColdQcdCorrelatorAnalysis::SEnergyCorrelator::m_brJetNumCst = NULL private
Definition at line 273 of file SEnergyCorrelator.h.
View newest version in sPHENIX GitHub at line 273 of file SEnergyCorrelator.h
TBranch* SColdQcdCorrelatorAnalysis::SEnergyCorrelator::m_brJetPhi = NULL private
Definition at line 278 of file SEnergyCorrelator.h.
View newest version in sPHENIX GitHub at line 278 of file SEnergyCorrelator.h
TBranch* SColdQcdCorrelatorAnalysis::SEnergyCorrelator::m_brJetPt = NULL private
Definition at line 276 of file SEnergyCorrelator.h.
View newest version in sPHENIX GitHub at line 276 of file SEnergyCorrelator.h
TBranch* SColdQcdCorrelatorAnalysis::SEnergyCorrelator::m_brPartonID[CONST::NPARTONS] = {NULL, NULL} private
Definition at line 255 of file SEnergyCorrelator.h.
View newest version in sPHENIX GitHub at line 255 of file SEnergyCorrelator.h
TBranch* SColdQcdCorrelatorAnalysis::SEnergyCorrelator::m_brPartonMomX[CONST::NPARTONS] = {NULL, NULL} private
Definition at line 256 of file SEnergyCorrelator.h.
View newest version in sPHENIX GitHub at line 256 of file SEnergyCorrelator.h
TBranch* SColdQcdCorrelatorAnalysis::SEnergyCorrelator::m_brPartonMomY[CONST::NPARTONS] = {NULL, NULL} private
Definition at line 257 of file SEnergyCorrelator.h.
View newest version in sPHENIX GitHub at line 257 of file SEnergyCorrelator.h
TBranch* SColdQcdCorrelatorAnalysis::SEnergyCorrelator::m_brPartonMomZ[CONST::NPARTONS] = {NULL, NULL} private
Definition at line 258 of file SEnergyCorrelator.h.
View newest version in sPHENIX GitHub at line 258 of file SEnergyCorrelator.h
vector<vector<double> >* SColdQcdCorrelatorAnalysis::SEnergyCorrelator::m_cstDr = NULL private
Definition at line 248 of file SEnergyCorrelator.h.
View newest version in sPHENIX GitHub at line 248 of file SEnergyCorrelator.h
vector<vector<int> >* SColdQcdCorrelatorAnalysis::SEnergyCorrelator::m_cstEmbedID = NULL private
Definition at line 227 of file SEnergyCorrelator.h.
View newest version in sPHENIX GitHub at line 227 of file SEnergyCorrelator.h
vector<vector<double> >* SColdQcdCorrelatorAnalysis::SEnergyCorrelator::m_cstEnergy = NULL private
Definition at line 249 of file SEnergyCorrelator.h.
View newest version in sPHENIX GitHub at line 249 of file SEnergyCorrelator.h
vector<vector<double> >* SColdQcdCorrelatorAnalysis::SEnergyCorrelator::m_cstEta = NULL private
Definition at line 251 of file SEnergyCorrelator.h.
View newest version in sPHENIX GitHub at line 251 of file SEnergyCorrelator.h
vector<vector<int> >* SColdQcdCorrelatorAnalysis::SEnergyCorrelator::m_cstID = NULL private
Definition at line 226 of file SEnergyCorrelator.h.
View newest version in sPHENIX GitHub at line 226 of file SEnergyCorrelator.h
vector<vector<int> >* SColdQcdCorrelatorAnalysis::SEnergyCorrelator::m_cstMatchID = NULL private
Definition at line 232 of file SEnergyCorrelator.h.
View newest version in sPHENIX GitHub at line 232 of file SEnergyCorrelator.h
vector<vector<double> >* SColdQcdCorrelatorAnalysis::SEnergyCorrelator::m_cstPhi = NULL private
Definition at line 252 of file SEnergyCorrelator.h.
View newest version in sPHENIX GitHub at line 252 of file SEnergyCorrelator.h
vector<vector<double> >* SColdQcdCorrelatorAnalysis::SEnergyCorrelator::m_cstPt = NULL private
Definition at line 250 of file SEnergyCorrelator.h.
View newest version in sPHENIX GitHub at line 250 of file SEnergyCorrelator.h
vector<vector<double> >* SColdQcdCorrelatorAnalysis::SEnergyCorrelator::m_cstZ = NULL private
Definition at line 247 of file SEnergyCorrelator.h.
View newest version in sPHENIX GitHub at line 247 of file SEnergyCorrelator.h
bool SColdQcdCorrelatorAnalysis::SEnergyCorrelator::m_doSecondCstLoop = false private
Definition at line 193 of file SEnergyCorrelator.h.
View newest version in sPHENIX GitHub at line 193 of file SEnergyCorrelator.h
pair<double, double> SColdQcdCorrelatorAnalysis::SEnergyCorrelator::m_drBinRange = {-999., -999.} private
Definition at line 207 of file SEnergyCorrelator.h.
View newest version in sPHENIX GitHub at line 207 of file SEnergyCorrelator.h
pair<double, double> SColdQcdCorrelatorAnalysis::SEnergyCorrelator::m_drCstRange = {-999., -999.} private
Definition at line 211 of file SEnergyCorrelator.h.
View newest version in sPHENIX GitHub at line 211 of file SEnergyCorrelator.h
vector<contrib::eec::EECLongestSide<contrib::eec::hist::axis::log>*> SColdQcdCorrelatorAnalysis::SEnergyCorrelator::m_eecLongSide private
Definition at line 217 of file SEnergyCorrelator.h.
View newest version in sPHENIX GitHub at line 217 of file SEnergyCorrelator.h
Referenced by ~SEnergyCorrelator().
pair<double, double> SColdQcdCorrelatorAnalysis::SEnergyCorrelator::m_etaJetRange = {-999., -999.} private
Definition at line 209 of file SEnergyCorrelator.h.
View newest version in sPHENIX GitHub at line 209 of file SEnergyCorrelator.h
int SColdQcdCorrelatorAnalysis::SEnergyCorrelator::m_evtNumChrgPars = -999 private
Definition at line 220 of file SEnergyCorrelator.h.
View newest version in sPHENIX GitHub at line 220 of file SEnergyCorrelator.h
int SColdQcdCorrelatorAnalysis::SEnergyCorrelator::m_evtNumJets = -999 private
Definition at line 235 of file SEnergyCorrelator.h.
View newest version in sPHENIX GitHub at line 235 of file SEnergyCorrelator.h
int SColdQcdCorrelatorAnalysis::SEnergyCorrelator::m_evtNumTrks = -999 private
Definition at line 229 of file SEnergyCorrelator.h.
View newest version in sPHENIX GitHub at line 229 of file SEnergyCorrelator.h
double SColdQcdCorrelatorAnalysis::SEnergyCorrelator::m_evtSumECal = -999. private
Definition at line 230 of file SEnergyCorrelator.h.
View newest version in sPHENIX GitHub at line 230 of file SEnergyCorrelator.h
double SColdQcdCorrelatorAnalysis::SEnergyCorrelator::m_evtSumHCal = -999. private
Definition at line 231 of file SEnergyCorrelator.h.
View newest version in sPHENIX GitHub at line 231 of file SEnergyCorrelator.h
double SColdQcdCorrelatorAnalysis::SEnergyCorrelator::m_evtSumPar = -999. private
Definition at line 225 of file SEnergyCorrelator.h.
View newest version in sPHENIX GitHub at line 225 of file SEnergyCorrelator.h
double SColdQcdCorrelatorAnalysis::SEnergyCorrelator::m_evtVtxX = -999. private
Definition at line 236 of file SEnergyCorrelator.h.
View newest version in sPHENIX GitHub at line 236 of file SEnergyCorrelator.h
double SColdQcdCorrelatorAnalysis::SEnergyCorrelator::m_evtVtxY = -999. private
Definition at line 237 of file SEnergyCorrelator.h.
View newest version in sPHENIX GitHub at line 237 of file SEnergyCorrelator.h
double SColdQcdCorrelatorAnalysis::SEnergyCorrelator::m_evtVtxZ = -999. private
Definition at line 238 of file SEnergyCorrelator.h.
View newest version in sPHENIX GitHub at line 238 of file SEnergyCorrelator.h
int SColdQcdCorrelatorAnalysis::SEnergyCorrelator::m_fCurrent = 0 private
Definition at line 183 of file SEnergyCorrelator.h.
View newest version in sPHENIX GitHub at line 183 of file SEnergyCorrelator.h
bool SColdQcdCorrelatorAnalysis::SEnergyCorrelator::m_inBatchMode = false private
Definition at line 186 of file SEnergyCorrelator.h.
View newest version in sPHENIX GitHub at line 186 of file SEnergyCorrelator.h
Referenced by SEnergyCorrelator().
TChain* SColdQcdCorrelatorAnalysis::SEnergyCorrelator::m_inChain = NULL private
Definition at line 158 of file SEnergyCorrelator.h.
View newest version in sPHENIX GitHub at line 158 of file SEnergyCorrelator.h
Referenced by ~SEnergyCorrelator().
bool SColdQcdCorrelatorAnalysis::SEnergyCorrelator::m_inComplexMode = false private
Definition at line 187 of file SEnergyCorrelator.h.
View newest version in sPHENIX GitHub at line 187 of file SEnergyCorrelator.h
Referenced by Analyze(), End(), Init(), and SEnergyCorrelator().
bool SColdQcdCorrelatorAnalysis::SEnergyCorrelator::m_inDebugMode = false private
Definition at line 185 of file SEnergyCorrelator.h.
View newest version in sPHENIX GitHub at line 185 of file SEnergyCorrelator.h
Referenced by Analyze(), End(), Init(), SEnergyCorrelator(), and ~SEnergyCorrelator().
TFile* SColdQcdCorrelatorAnalysis::SEnergyCorrelator::m_inFile = NULL private
Definition at line 157 of file SEnergyCorrelator.h.
View newest version in sPHENIX GitHub at line 157 of file SEnergyCorrelator.h
vector<string> SColdQcdCorrelatorAnalysis::SEnergyCorrelator::m_inFileNames private
Definition at line 201 of file SEnergyCorrelator.h.
View newest version in sPHENIX GitHub at line 201 of file SEnergyCorrelator.h
Referenced by ~SEnergyCorrelator().
string SColdQcdCorrelatorAnalysis::SEnergyCorrelator::m_inNodeName = "" private
Definition at line 195 of file SEnergyCorrelator.h.
View newest version in sPHENIX GitHub at line 195 of file SEnergyCorrelator.h
bool SColdQcdCorrelatorAnalysis::SEnergyCorrelator::m_inStandaloneMode = false private
Definition at line 188 of file SEnergyCorrelator.h.
View newest version in sPHENIX GitHub at line 188 of file SEnergyCorrelator.h
Referenced by Analyze(), End(), Init(), and SEnergyCorrelator().
string SColdQcdCorrelatorAnalysis::SEnergyCorrelator::m_inTreeName = "" private
Definition at line 196 of file SEnergyCorrelator.h.
View newest version in sPHENIX GitHub at line 196 of file SEnergyCorrelator.h
bool SColdQcdCorrelatorAnalysis::SEnergyCorrelator::m_isInputTreeEmbed = false private
Definition at line 190 of file SEnergyCorrelator.h.
View newest version in sPHENIX GitHub at line 190 of file SEnergyCorrelator.h
bool SColdQcdCorrelatorAnalysis::SEnergyCorrelator::m_isInputTreeTruth = false private
Definition at line 189 of file SEnergyCorrelator.h.
View newest version in sPHENIX GitHub at line 189 of file SEnergyCorrelator.h
vector<double>* SColdQcdCorrelatorAnalysis::SEnergyCorrelator::m_jetArea = NULL private
Definition at line 246 of file SEnergyCorrelator.h.
View newest version in sPHENIX GitHub at line 246 of file SEnergyCorrelator.h
vector<PseudoJet> SColdQcdCorrelatorAnalysis::SEnergyCorrelator::m_jetCstVector private
Definition at line 213 of file SEnergyCorrelator.h.
View newest version in sPHENIX GitHub at line 213 of file SEnergyCorrelator.h
vector<double>* SColdQcdCorrelatorAnalysis::SEnergyCorrelator::m_jetEnergy = NULL private
Definition at line 242 of file SEnergyCorrelator.h.
View newest version in sPHENIX GitHub at line 242 of file SEnergyCorrelator.h
vector<double>* SColdQcdCorrelatorAnalysis::SEnergyCorrelator::m_jetEta = NULL private
Definition at line 244 of file SEnergyCorrelator.h.
View newest version in sPHENIX GitHub at line 244 of file SEnergyCorrelator.h
vector<unsigned int>* SColdQcdCorrelatorAnalysis::SEnergyCorrelator::m_jetID = NULL private
Definition at line 240 of file SEnergyCorrelator.h.
View newest version in sPHENIX GitHub at line 240 of file SEnergyCorrelator.h
vector<unsigned long>* SColdQcdCorrelatorAnalysis::SEnergyCorrelator::m_jetNumCst = NULL private
Definition at line 239 of file SEnergyCorrelator.h.
View newest version in sPHENIX GitHub at line 239 of file SEnergyCorrelator.h
vector<double>* SColdQcdCorrelatorAnalysis::SEnergyCorrelator::m_jetPhi = NULL private
Definition at line 245 of file SEnergyCorrelator.h.
View newest version in sPHENIX GitHub at line 245 of file SEnergyCorrelator.h
vector<double>* SColdQcdCorrelatorAnalysis::SEnergyCorrelator::m_jetPt = NULL private
Definition at line 243 of file SEnergyCorrelator.h.
View newest version in sPHENIX GitHub at line 243 of file SEnergyCorrelator.h
vector<unsigned int>* SColdQcdCorrelatorAnalysis::SEnergyCorrelator::m_jetTruthID = NULL private
Definition at line 241 of file SEnergyCorrelator.h.
View newest version in sPHENIX GitHub at line 241 of file SEnergyCorrelator.h
string SColdQcdCorrelatorAnalysis::SEnergyCorrelator::m_moduleName = "" private
Definition at line 194 of file SEnergyCorrelator.h.
View newest version in sPHENIX GitHub at line 194 of file SEnergyCorrelator.h
Referenced by SEnergyCorrelator().
pair<double, double> SColdQcdCorrelatorAnalysis::SEnergyCorrelator::m_momCstRange = {-999., -999.} private
Definition at line 210 of file SEnergyCorrelator.h.
View newest version in sPHENIX GitHub at line 210 of file SEnergyCorrelator.h
uint64_t SColdQcdCorrelatorAnalysis::SEnergyCorrelator::m_nBinsDr = 0 private
Definition at line 205 of file SEnergyCorrelator.h.
View newest version in sPHENIX GitHub at line 205 of file SEnergyCorrelator.h
size_t SColdQcdCorrelatorAnalysis::SEnergyCorrelator::m_nBinsJetPt = 0 private
Definition at line 206 of file SEnergyCorrelator.h.
View newest version in sPHENIX GitHub at line 206 of file SEnergyCorrelator.h
Referenced by ~SEnergyCorrelator().
uint32_t SColdQcdCorrelatorAnalysis::SEnergyCorrelator::m_nPointCorr = 0 private
Definition at line 204 of file SEnergyCorrelator.h.
View newest version in sPHENIX GitHub at line 204 of file SEnergyCorrelator.h
TFile* SColdQcdCorrelatorAnalysis::SEnergyCorrelator::m_outFile = NULL private
Definition at line 156 of file SEnergyCorrelator.h.
View newest version in sPHENIX GitHub at line 156 of file SEnergyCorrelator.h
Referenced by ~SEnergyCorrelator().
string SColdQcdCorrelatorAnalysis::SEnergyCorrelator::m_outFileName = "" private
Definition at line 197 of file SEnergyCorrelator.h.
View newest version in sPHENIX GitHub at line 197 of file SEnergyCorrelator.h
vector<TH1D*> SColdQcdCorrelatorAnalysis::SEnergyCorrelator::m_outHistErrDrAxis private
Definition at line 162 of file SEnergyCorrelator.h.
View newest version in sPHENIX GitHub at line 162 of file SEnergyCorrelator.h
Referenced by ~SEnergyCorrelator().
vector<TH1D*> SColdQcdCorrelatorAnalysis::SEnergyCorrelator::m_outHistErrLnDrAxis private
Definition at line 164 of file SEnergyCorrelator.h.
View newest version in sPHENIX GitHub at line 164 of file SEnergyCorrelator.h
Referenced by ~SEnergyCorrelator().
vector<TH1D*> SColdQcdCorrelatorAnalysis::SEnergyCorrelator::m_outHistVarDrAxis private
Definition at line 161 of file SEnergyCorrelator.h.
View newest version in sPHENIX GitHub at line 161 of file SEnergyCorrelator.h
Referenced by ~SEnergyCorrelator().
vector<TH1D*> SColdQcdCorrelatorAnalysis::SEnergyCorrelator::m_outHistVarLnDrAxis private
Definition at line 163 of file SEnergyCorrelator.h.
View newest version in sPHENIX GitHub at line 163 of file SEnergyCorrelator.h
Referenced by ~SEnergyCorrelator().
int SColdQcdCorrelatorAnalysis::SEnergyCorrelator::m_partonID[CONST::NPARTONS] = {-999, -999} private
Definition at line 221 of file SEnergyCorrelator.h.
View newest version in sPHENIX GitHub at line 221 of file SEnergyCorrelator.h
double SColdQcdCorrelatorAnalysis::SEnergyCorrelator::m_partonMomX[CONST::NPARTONS] = {-999., -999.} private
Definition at line 222 of file SEnergyCorrelator.h.
View newest version in sPHENIX GitHub at line 222 of file SEnergyCorrelator.h
double SColdQcdCorrelatorAnalysis::SEnergyCorrelator::m_partonMomY[CONST::NPARTONS] = {-999., -999.} private
Definition at line 223 of file SEnergyCorrelator.h.
View newest version in sPHENIX GitHub at line 223 of file SEnergyCorrelator.h
double SColdQcdCorrelatorAnalysis::SEnergyCorrelator::m_partonMomZ[CONST::NPARTONS] = {-999., -999.} private
Definition at line 224 of file SEnergyCorrelator.h.
View newest version in sPHENIX GitHub at line 224 of file SEnergyCorrelator.h
vector<pair<double, double> > SColdQcdCorrelatorAnalysis::SEnergyCorrelator::m_ptJetBins private
Definition at line 212 of file SEnergyCorrelator.h.
View newest version in sPHENIX GitHub at line 212 of file SEnergyCorrelator.h
Referenced by ~SEnergyCorrelator().
pair<double, double> SColdQcdCorrelatorAnalysis::SEnergyCorrelator::m_ptJetRange = {-999., -999.} private
Definition at line 208 of file SEnergyCorrelator.h.
View newest version in sPHENIX GitHub at line 208 of file SEnergyCorrelator.h
bool SColdQcdCorrelatorAnalysis::SEnergyCorrelator::m_selectSubEvts = false private
Definition at line 192 of file SEnergyCorrelator.h.
View newest version in sPHENIX GitHub at line 192 of file SEnergyCorrelator.h
uint16_t SColdQcdCorrelatorAnalysis::SEnergyCorrelator::m_subEvtOpt = 0 private
Definition at line 198 of file SEnergyCorrelator.h.
View newest version in sPHENIX GitHub at line 198 of file SEnergyCorrelator.h
vector<int> SColdQcdCorrelatorAnalysis::SEnergyCorrelator::m_subEvtsToUse private
Definition at line 214 of file SEnergyCorrelator.h.
View newest version in sPHENIX GitHub at line 214 of file SEnergyCorrelator.h
int SColdQcdCorrelatorAnalysis::SEnergyCorrelator::m_verbosity = 0 private
Definition at line 184 of file SEnergyCorrelator.h.
View newest version in sPHENIX GitHub at line 184 of file SEnergyCorrelator.h
Referenced by SEnergyCorrelator().
The documentation for this class was generated from the following files:
analysis/blob/master/AndersonAnalysisModules/ColdQcdCorrelatorAnalysis/SEnergyCorrelator/src/SEnergyCorrelator.h
analysis/blob/master/AndersonAnalysisModules/ColdQcdCorrelatorAnalysis/SEnergyCorrelator/src/SEnergyCorrelator.ana.h
analysis/blob/master/AndersonAnalysisModules/ColdQcdCorrelatorAnalysis/SEnergyCorrelator/src/SEnergyCorrelator.cc
analysis/blob/master/AndersonAnalysisModules/ColdQcdCorrelatorAnalysis/SEnergyCorrelator/src/SEnergyCorrelator.io.h
analysis/blob/master/AndersonAnalysisModules/ColdQcdCorrelatorAnalysis/SEnergyCorrelator/src/SEnergyCorrelator.sys.h