Analysis Software: ActsFatras::detail::CombineSelectors< Initial, Combine, Selectors > Class Template Reference
ActsFatras::detail::CombineSelectors< Initial, Combine, Selectors > Class Template Reference
Combine multiple selectors with a configurable combine function.
#include <acts/blob/sPHENIX/Fatras/include/ActsFatras/Selectors/detail/combine_selectors.hpp>
Public Member Functions
template<typename... Ts>
bool operator() (const Ts &...things) const
template<size_t I>
std::tuple_element_t< I,
std::tuple< Selectors...> > & get ()
Access a specific selector by index.
template<typename Selector >
Selector & get ()
Access a specific selector by type.
Private Member Functions
template<std::size_t... Is, typename... Ts>
bool impl (std::index_sequence< Is...>, const Ts &...things) const
Private Attributes
std::tuple< Selectors...> m_selectors
Detailed Description
template<bool Initial, typename Combine, typename... Selectors>
class ActsFatras::detail::CombineSelectors< Initial, Combine, Selectors >
Combine multiple selectors with a configurable combine function.
Definition at line 20 of file combine_selectors.hpp.
View newest version in sPHENIX GitHub at line 20 of file combine_selectors.hpp
Member Function Documentation
template<bool Initial, typename Combine, typename... Selectors> template<size_t I> std::tuple_element_t<I, std::tuple<Selectors...> >& ActsFatras::detail::CombineSelectors< Initial, Combine, Selectors >::get () inline
Access a specific selector by index.
Definition at line 42 of file combine_selectors.hpp.
View newest version in sPHENIX GitHub at line 42 of file combine_selectors.hpp
References I, and ActsFatras::detail::CombineSelectors< Initial, Combine, Selectors >::m_selectors.
Referenced by BOOST_AUTO_TEST_CASE().
template<bool Initial, typename Combine, typename... Selectors> template<typename Selector > Selector& ActsFatras::detail::CombineSelectors< Initial, Combine, Selectors >::get () inline
Access a specific selector by type.
Definition at line 47 of file combine_selectors.hpp.
View newest version in sPHENIX GitHub at line 47 of file combine_selectors.hpp
References ActsFatras::detail::CombineSelectors< Initial, Combine, Selectors >::m_selectors.
template<bool Initial, typename Combine, typename... Selectors> template<std::size_t... Is, typename... Ts> bool ActsFatras::detail::CombineSelectors< Initial, Combine, Selectors >::impl (std::index_sequence< Is...> , const Ts &... things) const inline private
Definition at line 55 of file combine_selectors.hpp.
View newest version in sPHENIX GitHub at line 55 of file combine_selectors.hpp
References ActsFatras::detail::CombineSelectors< Initial, Combine, Selectors >::m_selectors, utils::status, and value.
Referenced by ActsFatras::detail::CombineSelectors< Initial, Combine, Selectors >::operator()().
template<bool Initial, typename Combine, typename... Selectors> template<typename... Ts> bool ActsFatras::detail::CombineSelectors< Initial, Combine, Selectors >::operator() (const Ts &... things) const inline
Call all configured selectors and combine the result.
Parameters
[in] things the inputs that will be selected
Returns
a boolean indicating the combined selection decision
Template Parameters
Ts the types of the selected inputs
Definition at line 32 of file combine_selectors.hpp.
View newest version in sPHENIX GitHub at line 32 of file combine_selectors.hpp
References ActsFatras::detail::CombineSelectors< Initial, Combine, Selectors >::impl().
Member Data Documentation
template<bool Initial, typename Combine, typename... Selectors> std::tuple<Selectors...> ActsFatras::detail::CombineSelectors< Initial, Combine, Selectors >::m_selectors private
Definition at line 52 of file combine_selectors.hpp.
View newest version in sPHENIX GitHub at line 52 of file combine_selectors.hpp
Referenced by ActsFatras::detail::CombineSelectors< Initial, Combine, Selectors >::get(), and ActsFatras::detail::CombineSelectors< Initial, Combine, Selectors >::impl().
The documentation for this class was generated from the following file:
acts/blob/sPHENIX/Fatras/include/ActsFatras/Selectors/detail/combine_selectors.hpp