Analysis Software: Acts::TrackingVolumeArrayCreator Class Reference
Acts::TrackingVolumeArrayCreator Class Reference
#include <acts/blob/sPHENIX/Core/include/Acts/Geometry/TrackingVolumeArrayCreator.hpp>
Classes
struct Config
This struct stores the configuration of the tracking geometry.
Public Member Functions
TrackingVolumeArrayCreator (const Config &, std::unique_ptr< const Logger > logger=getDefaultLogger("LayerArrayCreator", Logging::INFO))
~TrackingVolumeArrayCreator () override=default
Destructor.
std::shared_ptr< const
TrackingVolumeArray > trackingVolumeArray (const GeometryContext &gctx, const TrackingVolumeVector &tVolumes, BinningValue bValue) const override
void setLogger (std::unique_ptr< const Logger > logger)
Public Member Functions inherited from Acts::ITrackingVolumeArrayCreator
virtual ~ITrackingVolumeArrayCreator ()=default
Virtual destructor.
Private Member Functions
const Logger & logger () const
Private Attributes
std::unique_ptr< const Logger > m_logger
logging instance
Detailed Description
The TrackingVolumeArrayCreator is a simple Tool that helps to construct binned arrays of TrackingVolumes for both, confinement in another volume and navigation issues.
Definition at line 30 of file TrackingVolumeArrayCreator.hpp.
View newest version in sPHENIX GitHub at line 30 of file TrackingVolumeArrayCreator.hpp
Constructor & Destructor Documentation
Acts::TrackingVolumeArrayCreator::TrackingVolumeArrayCreator (const Config & , std::unique_ptr< const Logger > logger = getDefaultLogger("LayerArrayCreator", Logging::INFO)) inline
Constructor
Parameters
logger logging instance
Definition at line 38 of file TrackingVolumeArrayCreator.hpp.
View newest version in sPHENIX GitHub at line 38 of file TrackingVolumeArrayCreator.hpp
Acts::TrackingVolumeArrayCreator::~TrackingVolumeArrayCreator () override default
Destructor.
Member Function Documentation
const Logger& Acts::TrackingVolumeArrayCreator::logger () const inline private
Definition at line 67 of file TrackingVolumeArrayCreator.hpp.
View newest version in sPHENIX GitHub at line 67 of file TrackingVolumeArrayCreator.hpp
References m_logger.
void Acts::TrackingVolumeArrayCreator::setLogger (std::unique_ptr< const Logger > logger) inline
Set logging instance
Parameters
logger is the logging instance to be set
Definition at line 61 of file TrackingVolumeArrayCreator.hpp.
View newest version in sPHENIX GitHub at line 61 of file TrackingVolumeArrayCreator.hpp
References m_logger, and testing::internal::move().
std::shared_ptr< const Acts::TrackingVolumeArray > Acts::TrackingVolumeArrayCreator::trackingVolumeArray (const GeometryContext & gctx, const TrackingVolumeVector & tVolumes, BinningValue bValue) const override virtual
create a tracking volume array
Parameters
[in] gctx the geometry context for this building
[in] tVolumes is the vector of TrackingVolumes to be
[in] bValue is the binning value
Returns
new created volume array
Implements Acts::ITrackingVolumeArrayCreator.
Definition at line 22 of file TrackingVolumeArrayCreator.cpp.
View newest version in sPHENIX GitHub at line 22 of file TrackingVolumeArrayCreator.cpp
References testing::internal::move(), Acts::open, Acts::Experimental::detail::BlueprintHelper::sort(), value, and volumes.
Member Data Documentation
std::unique_ptr<const Logger> Acts::TrackingVolumeArrayCreator::m_logger private
logging instance
Definition at line 70 of file TrackingVolumeArrayCreator.hpp.
View newest version in sPHENIX GitHub at line 70 of file TrackingVolumeArrayCreator.hpp
Referenced by logger(), and setLogger().
The documentation for this class was generated from the following files:
acts/blob/sPHENIX/Core/include/Acts/Geometry/TrackingVolumeArrayCreator.hpp
acts/blob/sPHENIX/Core/src/Geometry/TrackingVolumeArrayCreator.cpp