Analysis Software: analysis/blob/master/isoCluster/macro/Fun4All_testEtIso_Pythia.C File Reference
Fun4All_testEtIso_Pythia.C File Reference
#include <fun4all/SubsysReco.h>
#include <fun4all/Fun4AllServer.h>
#include <fun4all/Fun4AllInputManager.h>
#include <fun4all/Fun4AllDstInputManager.h>
#include <fun4all/Fun4AllDstOutputManager.h>
#include <fun4all/Fun4AllOutputManager.h>
#include <phool/PHRandomSeed.h>
#include <phool/recoConsts.h>
#include <g4jets/FastJetAlgo.h>
#include <g4jets/JetReco.h>
#include <g4jets/TowerJetInput.h>
#include <g4jets/TruthJetInput.h>
#include <jetbackground/CopyAndSubtractJets.h>
#include <jetbackground/DetermineTowerBackground.h>
#include <jetbackground/FastJetAlgoSub.h>
#include <jetbackground/RetowerCEMC.h>
#include <jetbackground/SubtractTowers.h>
#include <jetbackground/SubtractTowersCS.h>
#include <ClusterIso.h>
#include <isocluster/isoCluster.h>
Namespaces
namespace Enable
namespace G4HIJETS
Functions
void Fun4All_testEtIso_Pythia (int nEvents=1, const char *filelist1="dst_calo_cluster_run40_PhotonJet.list", const char *filelist2="dst_truth_run40_PhotonJet.list", const string outname="test.root")
Function Documentation
void Fun4All_testEtIso_Pythia (int nEvents = 1, const char * filelist1 = "dst_calo_cluster_run40_PhotonJet.list", const char * filelist2 = "dst_truth_run40_PhotonJet.list", const string outname = "test.root")
???
Definition at line 51 of file Fun4All_testEtIso_Pythia.C.
View newest version in sPHENIX GitHub at line 51 of file Fun4All_testEtIso_Pythia.C
References JetReco::add_algo(), JetReco::add_input(), Fun4AllInputManager::AddListFile(), Jet::ANTIKT, Jet::CEMC_TOWER_RETOWER, G4HIJETS::do_flow, Jet::HCALIN_TOWER, Jet::HCALOUT_TOWER, in, recoConsts::instance(), Fun4AllServer::instance(), nEvents, Fun4AllServer::registerInputManager(), Fun4AllServer::registerSubsystem(), utils::run, JetReco::set_algo_node(), JetReco::set_input_node(), DetermineTowerBackground::SetBackgroundOutputName(), DetermineTowerBackground::SetFlow(), SubtractTowers::SetFlowModulation(), CopyAndSubtractJets::SetFlowModulation(), DetermineTowerBackground::SetSeedJetD(), DetermineTowerBackground::SetSeedJetPt(), DetermineTowerBackground::SetSeedType(), verbosity, Fun4AllBase::Verbosity(), and Verbosity().