Analysis Software: AntiTrigger Class Reference
AntiTrigger Class Reference
#include <analysis/blob/master/HF-Particle/AntiTrigger/AntiTrigger.h>
Public Member Functions
AntiTrigger ()
AntiTrigger (const std::string &name)
virtual ~AntiTrigger ()
int Init (PHCompositeNode *topNode)
int process_event (PHCompositeNode *topNode)
int End (PHCompositeNode *topNode)
Called at the end of all processing.
int parseParticleList ()
bool findParticle (PHCompositeNode *topNode)
bool particleIsInList (std::string particle)
void printInfo ()
void setParticleList (std::vector< std::string > particleList)
Public Member Functions inherited from SubsysReco
~SubsysReco () override
virtual int EndRun (const int)
Called at the end of each run.
virtual int InitRun (PHCompositeNode *)
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
void Print (const std::string &="ALL") const override
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Private Attributes
PHHepMCGenEventMap * m_geneventmap = NULL
PHHepMCGenEvent * m_genevt = NULL
int m_counter = 0
std::vector< std::string > m_particleList
std::vector< int > m_particleIDs
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = std::numeric_limits<int>::max() - 10
}
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Detailed Description
Definition at line 28 of file AntiTrigger.h.
View newest version in sPHENIX GitHub at line 28 of file AntiTrigger.h
Constructor & Destructor Documentation
AntiTrigger::AntiTrigger ()
Definition at line 9 of file AntiTrigger.cc.
View newest version in sPHENIX GitHub at line 9 of file AntiTrigger.cc
AntiTrigger::AntiTrigger (const std::string & name) explicit
Definition at line 14 of file AntiTrigger.cc.
View newest version in sPHENIX GitHub at line 14 of file AntiTrigger.cc
virtual AntiTrigger::~AntiTrigger () inline virtual
Definition at line 35 of file AntiTrigger.h.
View newest version in sPHENIX GitHub at line 35 of file AntiTrigger.h
Member Function Documentation
int AntiTrigger::End (PHCompositeNode *) virtual
Called at the end of all processing.
Reimplemented from SubsysReco.
Definition at line 56 of file AntiTrigger.cc.
View newest version in sPHENIX GitHub at line 56 of file AntiTrigger.cc
References printInfo(), Fun4AllBase::Verbosity(), and Fun4AllBase::VERBOSITY_SOME.
bool AntiTrigger::findParticle (PHCompositeNode * topNode)
Definition at line 91 of file AntiTrigger.cc.
View newest version in sPHENIX GitHub at line 91 of file AntiTrigger.cc
References PHHepMCGenEventMap::get(), PHHepMCGenEvent::getEvent(), m_geneventmap, m_genevt, m_particleIDs, merge_hashes::p, Fun4AllBase::Verbosity(), and Fun4AllBase::VERBOSITY_MORE.
Referenced by process_event().
int AntiTrigger::Init (PHCompositeNode *) virtual
Called during initialization. Typically this is where you can book histograms, and e.g. register them to Fun4AllServer (so they can be output to file using Fun4AllServer::dumpHistos() method).
Reimplemented from SubsysReco.
Definition at line 19 of file AntiTrigger.cc.
View newest version in sPHENIX GitHub at line 19 of file AntiTrigger.cc
References i, m_particleList, Fun4AllBase::Name(), parseParticleList(), Fun4AllBase::Verbosity(), and Fun4AllBase::VERBOSITY_SOME.
int AntiTrigger::parseParticleList ()
Definition at line 63 of file AntiTrigger.cc.
View newest version in sPHENIX GitHub at line 63 of file AntiTrigger.cc
References Fun4AllReturnCodes::DONOTREGISTERSUBSYSTEM, i, m_particleIDs, m_particleList, Fun4AllBase::Name(), particleIsInList(), Fun4AllBase::Verbosity(), Fun4AllBase::VERBOSITY_MORE, and Fun4AllBase::VERBOSITY_SOME.
Referenced by Init().
bool AntiTrigger::particleIsInList (std::string particle)
Definition at line 123 of file AntiTrigger.cc.
View newest version in sPHENIX GitHub at line 123 of file AntiTrigger.cc
References Fun4AllBase::Verbosity(), and Fun4AllBase::VERBOSITY_SOME.
Referenced by parseParticleList().
void AntiTrigger::printInfo ()
Definition at line 139 of file AntiTrigger.cc.
View newest version in sPHENIX GitHub at line 139 of file AntiTrigger.cc
References i, m_counter, m_particleList, and Fun4AllBase::Name().
Referenced by End().
int AntiTrigger::process_event (PHCompositeNode *) virtual
Called for each event. This is where you do the real work.
Reimplemented from SubsysReco.
Definition at line 41 of file AntiTrigger.cc.
View newest version in sPHENIX GitHub at line 41 of file AntiTrigger.cc
References Fun4AllReturnCodes::ABORTEVENT, Fun4AllReturnCodes::EVENT_OK, findParticle(), and m_counter.
void AntiTrigger::setParticleList (std::vector< std::string > particleList) inline
Definition at line 52 of file AntiTrigger.h.
View newest version in sPHENIX GitHub at line 52 of file AntiTrigger.h
References m_particleList.
Referenced by Fun4All_testingGround().
Member Data Documentation
int AntiTrigger::m_counter = 0 private
Definition at line 59 of file AntiTrigger.h.
View newest version in sPHENIX GitHub at line 59 of file AntiTrigger.h
Referenced by printInfo(), and process_event().
PHHepMCGenEventMap* AntiTrigger::m_geneventmap = NULL private
Definition at line 56 of file AntiTrigger.h.
View newest version in sPHENIX GitHub at line 56 of file AntiTrigger.h
Referenced by findParticle().
PHHepMCGenEvent* AntiTrigger::m_genevt = NULL private
Definition at line 57 of file AntiTrigger.h.
View newest version in sPHENIX GitHub at line 57 of file AntiTrigger.h
Referenced by findParticle().
std::vector<int> AntiTrigger::m_particleIDs private
Definition at line 62 of file AntiTrigger.h.
View newest version in sPHENIX GitHub at line 62 of file AntiTrigger.h
Referenced by findParticle(), and parseParticleList().
std::vector<std::string> AntiTrigger::m_particleList private
Definition at line 61 of file AntiTrigger.h.
View newest version in sPHENIX GitHub at line 61 of file AntiTrigger.h
Referenced by Init(), parseParticleList(), printInfo(), and setParticleList().
The documentation for this class was generated from the following files:
analysis/blob/master/HF-Particle/AntiTrigger/AntiTrigger.h
analysis/blob/master/HF-Particle/AntiTrigger/AntiTrigger.cc