Analysis Software: ALICEKF Class Reference
ALICEKF Class Reference
#include <coresoftware/blob/master/offline/packages/trackreco/ALICEKF.h>
Public Member Functions
ALICEKF (PHCompositeNode *topNode, TrkrClusterContainer *cmap, PHField *B, double fieldDir, unsigned int min_clusters, double max_sin_phi, int verbosity)
~ALICEKF ()
ALICEKF (const ALICEKF &)=delete
ALICEKF & operator= (const ALICEKF &)=delete
TrackSeedAliceSeedMap ALICEKalmanFilter (const std::vector< std::vector< TrkrDefs::cluskey >> &chains, bool use_nhits_limit, const PositionMap &globalPositions, std::vector< float > &trackChi2) const
bool covIsPosDef (Eigen::Matrix< double, 6, 6 > &cov) const
void repairCovariance (Eigen::Matrix< double, 6, 6 > &cov) const
bool checknan (double val, const std::string &msg, int num) const
double get_Bz (double x, double y, double z) const
void useConstBField (bool opt)
void setConstBField (float b)
void useFixedClusterError (bool opt)
void setFixedClusterError (int i, double val)
double getClusterError (TrkrCluster *c, TrkrDefs::cluskey key, Acts::Vector3 global, int i, int j) const
std::vector< double > GetCircleClusterResiduals (const std::vector< std::pair< double, double >> &pts, double R, double X0, double Y0) const
std::vector< double > GetLineClusterResiduals (const std::vector< std::pair< double, double >> &pts, double A, double B) const
double get_Bzconst () const
Public Attributes
ClusterErrorPara * _ClusErrPara
Private Member Functions
int Verbosity () const
Private Attributes
PHField * _B = nullptr
size_t _min_clusters_per_track = 20
TrkrClusterContainer * _cluster_map = nullptr
int _v = 0
double _Bzconst = 10*0.000299792458f
double _fieldDir = -1
double _max_sin_phi = 1.
bool _use_const_field = false
float _const_field = 1.4
bool _use_fixed_clus_error = true
std::array< double, 3 > _fixed_clus_error = {.1,.1,.1}
Detailed Description
Definition at line 26 of file ALICEKF.h.
View newest version in sPHENIX GitHub at line 26 of file ALICEKF.h
Constructor & Destructor Documentation
ALICEKF::ALICEKF (PHCompositeNode * topNode, TrkrClusterContainer * cmap, PHField * B, double fieldDir, unsigned int min_clusters, double max_sin_phi, int verbosity) inline
Definition at line 29 of file ALICEKF.h.
View newest version in sPHENIX GitHub at line 29 of file ALICEKF.h
References _B, _ClusErrPara, _cluster_map, _fieldDir, _max_sin_phi, _min_clusters_per_track, _v, and verbosity.
ALICEKF::~ALICEKF () inline
Definition at line 48 of file ALICEKF.h.
View newest version in sPHENIX GitHub at line 48 of file ALICEKF.h
References _ClusErrPara.
ALICEKF::ALICEKF (const ALICEKF &) explicit delete
Member Function Documentation
TrackSeedAliceSeedMap ALICEKF::ALICEKalmanFilter (const std::vector< std::vector< TrkrDefs::cluskey >> & chains, bool use_nhits_limit, const PositionMap & globalPositions, std::vector< float > & trackChi2) const
Shows the transformation between ALICE and sPHENIX coordinates
Shows the transformation between ALICE and sPHENIX coordinates
We set the qoverR to get the good charge estimate from the KF which helps the Acts fit
Definition at line 99 of file ALICEKF.cc.
View newest version in sPHENIX GitHub at line 99 of file ALICEKF.cc
References _Bzconst, _cluster_map, _const_field, _fieldDir, _max_sin_phi, _min_clusters_per_track, alpha, Acts::PhysicalConstants::c, GPUTPCTrackParam::CalculateFitParameters(), checknan(), TrackFitUtils::circle_fit_by_taubin(), Acts::Test::cov, covIsPosDef(), INTTVtxZ::dphi, GPUTPCTrackParam::Filter(), TrkrClusterContainer::findCluster(), get_Bz(), GPUTPCTrackParam::GetChi2(), getClusterError(), GPUTPCTrackParam::GetCov(), GPUTPCTrackParam::GetDzDs(), GPUTPCTrackParam::GetErr2QPt(), GPUTPCTrackParam::GetErr2Y(), GPUTPCTrackParam::GetErr2Z(), GPUTPCTrackParam::GetKappa(), TrkrDefs::getLayer(), GPUTPCTrackParam::GetNDF(), GPUTPCTrackParam::GetQPt(), TrkrCluster::getRPhiError(), GPUTPCTrackParam::GetSinPhi(), GPUTPCTrackParam::GetX(), GPUTPCTrackParam::GetY(), GPUTPCTrackParam::GetZ(), i, GPUTPCTrackParam::InitParam(), TrackSeed_v1::insert_cluster_key(), j, Acts::UnitConstants::J, layer, LogDebug, LogError, LogWarning, next, merge_hashes::p, phisize, Acts::IntegrationTest::R, repairCovariance(), GPUTPCTrackParam::Rotate(), physmon_simulation::s, TrackSeed_v1::set_qOverR(), GPUTPCTrackParam::SetDzDs(), GPUTPCTrackParam::SetQPt(), GPUTPCTrackParam::SetSinPhi(), GPUTPCTrackParam::SetX(), GPUTPCTrackParam::SetY(), GPUTPCTrackParam::SetZ(), square(), to_string(), Acts::Test::transform, GPUTPCTrackParam::TransportToXWithMaterial(), Verbosity(), ambiguity_solver_full_chain::x, x0, y, physmon_track_finding_ttbar::z, and zsize.
bool ALICEKF::checknan (double val, const std::string & msg, int num) const
Definition at line 36 of file ALICEKF.cc.
View newest version in sPHENIX GitHub at line 36 of file ALICEKF.cc
References Verbosity().
Referenced by ALICEKalmanFilter().
bool ALICEKF::covIsPosDef (Eigen::Matrix< double, 6, 6 > & cov) const
Definition at line 623 of file ALICEKF.cc.
View newest version in sPHENIX GitHub at line 623 of file ALICEKF.cc
Referenced by ALICEKalmanFilter().
double ALICEKF::get_Bz (double x, double y, double z) const
Definition at line 45 of file ALICEKF.cc.
View newest version in sPHENIX GitHub at line 45 of file ALICEKF.cc
References _B, _const_field, _use_const_field, Acts::UnitConstants::cm, PHField::GetFieldValue(), and merge_hashes::p.
Referenced by ALICEKalmanFilter().
double ALICEKF::get_Bzconst () const inline
Definition at line 65 of file ALICEKF.h.
View newest version in sPHENIX GitHub at line 65 of file ALICEKF.h
References _Bzconst.
std::vector< double > ALICEKF::GetCircleClusterResiduals (const std::vector< std::pair< double, double >> & pts, double R, double X0, double Y0) const
Definition at line 651 of file ALICEKF.cc.
View newest version in sPHENIX GitHub at line 651 of file ALICEKF.cc
References Acts::IntegrationTest::R, square(), Acts::Test::transform, ambiguity_solver_full_chain::x, X0, y, and Y0.
double ALICEKF::getClusterError (TrkrCluster * c, TrkrDefs::cluskey key, Acts::Vector3 global, int i, int j) const
Definition at line 54 of file ALICEKF.cc.
View newest version in sPHENIX GitHub at line 54 of file ALICEKF.cc
References _ClusErrPara, _fixed_clus_error, _use_fixed_clus_error, check_license::err(), ClusterErrorPara::get_clusterv5_modified_error(), i, and j.
Referenced by ALICEKalmanFilter().
std::vector< double > ALICEKF::GetLineClusterResiduals (const std::vector< std::pair< double, double >> & pts, double A, double B) const
Definition at line 665 of file ALICEKF.cc.
View newest version in sPHENIX GitHub at line 665 of file ALICEKF.cc
References KFPMath::a, A, KFPMath::b, Acts::PhysicalConstants::c, physmon_track_finding_ttbar::r, square(), Acts::Test::transform, and physmon_track_finding_ttbar::z.
ALICEKF& ALICEKF::operator= (const ALICEKF &) delete
void ALICEKF::repairCovariance (Eigen::Matrix< double, 6, 6 > & cov) const
Definition at line 631 of file ALICEKF.cc.
View newest version in sPHENIX GitHub at line 631 of file ALICEKF.cc
References Acts::Test::cov, Acts::UnitConstants::e, i, j, Q(), and SVM_v1::Z.
Referenced by ALICEKalmanFilter().
void ALICEKF::setConstBField (float b) inline
Definition at line 59 of file ALICEKF.h.
View newest version in sPHENIX GitHub at line 59 of file ALICEKF.h
References _const_field, and KFPMath::b.
void ALICEKF::setFixedClusterError (int i, double val) inline
Definition at line 61 of file ALICEKF.h.
View newest version in sPHENIX GitHub at line 61 of file ALICEKF.h
References _fixed_clus_error.
void ALICEKF::useConstBField (bool opt) inline
Definition at line 58 of file ALICEKF.h.
View newest version in sPHENIX GitHub at line 58 of file ALICEKF.h
References _use_const_field.
void ALICEKF::useFixedClusterError (bool opt) inline
Definition at line 60 of file ALICEKF.h.
View newest version in sPHENIX GitHub at line 60 of file ALICEKF.h
References _use_fixed_clus_error.
int ALICEKF::Verbosity () const inline private
Definition at line 72 of file ALICEKF.h.
View newest version in sPHENIX GitHub at line 72 of file ALICEKF.h
References _v.
Referenced by ALICEKalmanFilter(), and checknan().
Member Data Documentation
PHField* ALICEKF::_B = nullptr private
Definition at line 69 of file ALICEKF.h.
View newest version in sPHENIX GitHub at line 69 of file ALICEKF.h
Referenced by ALICEKF(), and get_Bz().
double ALICEKF::_Bzconst = 10*0.000299792458f private
Definition at line 76 of file ALICEKF.h.
View newest version in sPHENIX GitHub at line 76 of file ALICEKF.h
Referenced by ALICEKalmanFilter(), and get_Bzconst().
ClusterErrorPara* ALICEKF::_ClusErrPara
Definition at line 67 of file ALICEKF.h.
View newest version in sPHENIX GitHub at line 67 of file ALICEKF.h
Referenced by ALICEKF(), getClusterError(), and ~ALICEKF().
TrkrClusterContainer* ALICEKF::_cluster_map = nullptr private
Definition at line 71 of file ALICEKF.h.
View newest version in sPHENIX GitHub at line 71 of file ALICEKF.h
Referenced by ALICEKalmanFilter(), and ALICEKF().
float ALICEKF::_const_field = 1.4 private
Definition at line 80 of file ALICEKF.h.
View newest version in sPHENIX GitHub at line 80 of file ALICEKF.h
Referenced by ALICEKalmanFilter(), get_Bz(), and setConstBField().
double ALICEKF::_fieldDir = -1 private
Definition at line 77 of file ALICEKF.h.
View newest version in sPHENIX GitHub at line 77 of file ALICEKF.h
Referenced by ALICEKalmanFilter(), and ALICEKF().
std::array<double,3> ALICEKF::_fixed_clus_error = {.1,.1,.1} private
Definition at line 82 of file ALICEKF.h.
View newest version in sPHENIX GitHub at line 82 of file ALICEKF.h
Referenced by getClusterError(), and setFixedClusterError().
double ALICEKF::_max_sin_phi = 1. private
Definition at line 78 of file ALICEKF.h.
View newest version in sPHENIX GitHub at line 78 of file ALICEKF.h
Referenced by ALICEKalmanFilter(), and ALICEKF().
size_t ALICEKF::_min_clusters_per_track = 20 private
Definition at line 70 of file ALICEKF.h.
View newest version in sPHENIX GitHub at line 70 of file ALICEKF.h
Referenced by ALICEKalmanFilter(), and ALICEKF().
bool ALICEKF::_use_const_field = false private
Definition at line 79 of file ALICEKF.h.
View newest version in sPHENIX GitHub at line 79 of file ALICEKF.h
Referenced by get_Bz(), and useConstBField().
bool ALICEKF::_use_fixed_clus_error = true private
Definition at line 81 of file ALICEKF.h.
View newest version in sPHENIX GitHub at line 81 of file ALICEKF.h
Referenced by getClusterError(), and useFixedClusterError().
int ALICEKF::_v = 0 private
Definition at line 75 of file ALICEKF.h.
View newest version in sPHENIX GitHub at line 75 of file ALICEKF.h
Referenced by ALICEKF(), and Verbosity().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/trackreco/ALICEKF.h
coresoftware/blob/master/offline/packages/trackreco/ALICEKF.cc