Analysis Software: Hit Class Reference
Hit Class Reference
#include <analysis/blob/master/dNdEta_Run2023/analysis_INTT/src/Hit.h>
Public Member Functions
Hit ()
Hit (float, float, float, float, float, float, int)
Hit (float, float, float, float, float, float, int, int)
Hit (float, float)
~Hit ()
float posX ()
float posY ()
float posZ ()
float rho ()
float vtxX ()
float vtxY ()
float vtxZ ()
float Eta ()
float Phi ()
float R ()
int Layer ()
int PhiSize ()
pair< float, float > Edge ()
void Update ()
void SetPos (float, float, float)
void SetVtx (float, float, float)
void SetEdge (float, float)
void SetMatchedTkl ()
bool IsMatchedTkl ()
void Print ()
TVector3 VecPos ()
TVector3 VecVtx ()
TVector3 VecRel ()
Private Attributes
float _x
float _y
float _z
float _vtxX
float _vtxY
float _vtxZ
float _eta
float _phi
float _R
int _layer
int _phisize
pair< float, float > _edge
bool _matched_tkl
TVector3 vechit
TVector3 vecvtx
TVector3 vecrel
Detailed Description
Definition at line 14 of file Hit.h.
View newest version in sPHENIX GitHub at line 14 of file Hit.h
Constructor & Destructor Documentation
Hit::Hit ()
Definition at line 68 of file Hit.h.
View newest version in sPHENIX GitHub at line 68 of file Hit.h
References _eta.
Hit::Hit (float x, float y, float z, float vtxX, float vtxY, float vtxZ, int layer)
Definition at line 80 of file Hit.h.
View newest version in sPHENIX GitHub at line 80 of file Hit.h
References _eta, and layer.
Hit::Hit (float x, float y, float z, float vtxX, float vtxY, float vtxZ, int layer, int phisize)
Definition at line 92 of file Hit.h.
View newest version in sPHENIX GitHub at line 92 of file Hit.h
References _eta, layer, and phisize.
Hit::Hit (float eta, float phi)
Definition at line 105 of file Hit.h.
View newest version in sPHENIX GitHub at line 105 of file Hit.h
References _eta, eta, and ActsTests::PropagationDatasets::phi.
Hit::~Hit ()
Definition at line 112 of file Hit.h.
View newest version in sPHENIX GitHub at line 112 of file Hit.h
Member Function Documentation
pair< float, float > Hit::Edge ()
Definition at line 136 of file Hit.h.
View newest version in sPHENIX GitHub at line 136 of file Hit.h
float Hit::Eta ()
Definition at line 128 of file Hit.h.
View newest version in sPHENIX GitHub at line 128 of file Hit.h
References _eta.
Referenced by main(), ProtoTracklets(), Tracklet::SetHits(), and Tracklet::Tracklet().
bool Hit::IsMatchedTkl ()
Definition at line 154 of file Hit.h.
View newest version in sPHENIX GitHub at line 154 of file Hit.h
int Hit::Layer ()
Definition at line 134 of file Hit.h.
View newest version in sPHENIX GitHub at line 134 of file Hit.h
float Hit::Phi ()
Definition at line 130 of file Hit.h.
View newest version in sPHENIX GitHub at line 130 of file Hit.h
Referenced by main(), and ProtoTracklets().
int Hit::PhiSize () inline
Definition at line 34 of file Hit.h.
View newest version in sPHENIX GitHub at line 34 of file Hit.h
float Hit::posX ()
Definition at line 114 of file Hit.h.
View newest version in sPHENIX GitHub at line 114 of file Hit.h
float Hit::posY ()
Definition at line 116 of file Hit.h.
View newest version in sPHENIX GitHub at line 116 of file Hit.h
float Hit::posZ ()
Definition at line 118 of file Hit.h.
View newest version in sPHENIX GitHub at line 118 of file Hit.h
void Hit::Print ()
Definition at line 162 of file Hit.h.
View newest version in sPHENIX GitHub at line 162 of file Hit.h
References printf().
float Hit::R ()
Definition at line 132 of file Hit.h.
View newest version in sPHENIX GitHub at line 132 of file Hit.h
float Hit::rho ()
Definition at line 120 of file Hit.h.
View newest version in sPHENIX GitHub at line 120 of file Hit.h
void Hit::SetEdge (float edge1, float edge2)
Definition at line 142 of file Hit.h.
View newest version in sPHENIX GitHub at line 142 of file Hit.h
Referenced by main().
void Hit::SetMatchedTkl ()
Definition at line 152 of file Hit.h.
View newest version in sPHENIX GitHub at line 152 of file Hit.h
void Hit::SetPos (float x, float y, float z)
Definition at line 138 of file Hit.h.
View newest version in sPHENIX GitHub at line 138 of file Hit.h
Referenced by RandomHit().
void Hit::SetVtx (float vtxX, float vtxY, float vtxZ)
Definition at line 140 of file Hit.h.
View newest version in sPHENIX GitHub at line 140 of file Hit.h
Referenced by RandomHit().
void Hit::Update ()
Definition at line 144 of file Hit.h.
View newest version in sPHENIX GitHub at line 144 of file Hit.h
References _eta.
TVector3 Hit::VecPos ()
Definition at line 156 of file Hit.h.
View newest version in sPHENIX GitHub at line 156 of file Hit.h
TVector3 Hit::VecRel ()
Definition at line 160 of file Hit.h.
View newest version in sPHENIX GitHub at line 160 of file Hit.h
TVector3 Hit::VecVtx ()
Definition at line 158 of file Hit.h.
View newest version in sPHENIX GitHub at line 158 of file Hit.h
float Hit::vtxX ()
Definition at line 122 of file Hit.h.
View newest version in sPHENIX GitHub at line 122 of file Hit.h
float Hit::vtxY ()
Definition at line 124 of file Hit.h.
View newest version in sPHENIX GitHub at line 124 of file Hit.h
float Hit::vtxZ ()
Definition at line 126 of file Hit.h.
View newest version in sPHENIX GitHub at line 126 of file Hit.h
Member Data Documentation
pair<float, float> Hit::_edge private
Definition at line 61 of file Hit.h.
View newest version in sPHENIX GitHub at line 61 of file Hit.h
float Hit::_eta private
Definition at line 56 of file Hit.h.
View newest version in sPHENIX GitHub at line 56 of file Hit.h
int Hit::_layer private
Definition at line 59 of file Hit.h.
View newest version in sPHENIX GitHub at line 59 of file Hit.h
bool Hit::_matched_tkl private
Definition at line 62 of file Hit.h.
View newest version in sPHENIX GitHub at line 62 of file Hit.h
float Hit::_phi private
Definition at line 57 of file Hit.h.
View newest version in sPHENIX GitHub at line 57 of file Hit.h
int Hit::_phisize private
Definition at line 60 of file Hit.h.
View newest version in sPHENIX GitHub at line 60 of file Hit.h
float Hit::_R private
Definition at line 58 of file Hit.h.
View newest version in sPHENIX GitHub at line 58 of file Hit.h
float Hit::_vtxX private
Definition at line 53 of file Hit.h.
View newest version in sPHENIX GitHub at line 53 of file Hit.h
float Hit::_vtxY private
Definition at line 54 of file Hit.h.
View newest version in sPHENIX GitHub at line 54 of file Hit.h
float Hit::_vtxZ private
Definition at line 55 of file Hit.h.
View newest version in sPHENIX GitHub at line 55 of file Hit.h
float Hit::_x private
Definition at line 50 of file Hit.h.
View newest version in sPHENIX GitHub at line 50 of file Hit.h
float Hit::_y private
Definition at line 51 of file Hit.h.
View newest version in sPHENIX GitHub at line 51 of file Hit.h
float Hit::_z private
Definition at line 52 of file Hit.h.
View newest version in sPHENIX GitHub at line 52 of file Hit.h
TVector3 Hit::vechit private
Definition at line 63 of file Hit.h.
View newest version in sPHENIX GitHub at line 63 of file Hit.h
TVector3 Hit::vecrel private
Definition at line 65 of file Hit.h.
View newest version in sPHENIX GitHub at line 65 of file Hit.h
TVector3 Hit::vecvtx private
Definition at line 64 of file Hit.h.
View newest version in sPHENIX GitHub at line 64 of file Hit.h
The documentation for this class was generated from the following file:
analysis/blob/master/dNdEta_Run2023/analysis_INTT/src/Hit.h