Analysis Software: BeamLineMagnetDetector Class Reference
BeamLineMagnetDetector Class Reference
#include <coresoftware/blob/master/simulation/g4simulation/g4detectors/BeamLineMagnetDetector.h>
Public Member Functions
BeamLineMagnetDetector (PHG4Subsystem *subsys, PHCompositeNode *Node, PHParameters *parameters, const std::string &dnam, const int magnetid=0)
constructor
~BeamLineMagnetDetector (void) override
destructor
void ConstructMe (G4LogicalVolume *world) override
construct
void PostConstruction () override
Optional PostConstruction call after all geometry is constructed.
int IsInBeamLineMagnet (const G4VPhysicalVolume *) const
void SuperDetector (const std::string &name)
const std::string SuperDetector () const
int get_MagnetId () const
Public Member Functions inherited from PHG4Detector
PHG4Detector ()=delete
constructor
PHG4Detector (PHG4Subsystem *subsys, PHCompositeNode *Node, const std::string &nam)
virtual ~PHG4Detector (void)
destructor
virtual void Construct (G4LogicalVolume *world) final
construct method
virtual void Verbosity (const int v)
virtual int Verbosity () const
virtual G4UserSteppingAction * GetSteppingAction ()
virtual std::string GetName () const
virtual void OverlapCheck (const bool chk)
virtual bool OverlapCheck () const
virtual void Print (const std::string &="ALL") const
virtual int DisplayVolume (G4VSolid *volume, G4LogicalVolume *logvol, G4RotationMatrix *rotm=nullptr)
virtual int DisplayVolume (G4LogicalVolume *checksolid, G4LogicalVolume *logvol, G4RotationMatrix *rotm=nullptr)
virtual PHCompositeNode * topNode ()
virtual PHG4Subsystem * GetMySubsystem ()
Private Attributes
PHParameters * m_Params = nullptr
G4VPhysicalVolume * magnet_physi = nullptr
G4VPhysicalVolume * magnet_iron_physi = nullptr
G4VPhysicalVolume * magnet_core_physi = nullptr
BeamLineMagnetDisplayAction * m_DisplayAction = nullptr
G4LogicalVolume * m_magnetFieldLogic = nullptr
G4MagneticField * m_magField = nullptr
int m_MagnetId = -1
std::string m_SuperDetector = "NONE"
Additional Inherited Members
Static Public Member Functions inherited from PHG4Detector
static G4Material * GetDetectorMaterial (const std::string &name, const bool quit=true)
static G4Element * GetDetectorElement (const std::string &name, const bool quit=true)
Detailed Description
Definition at line 18 of file BeamLineMagnetDetector.h.
View newest version in sPHENIX GitHub at line 18 of file BeamLineMagnetDetector.h
Constructor & Destructor Documentation
BeamLineMagnetDetector::BeamLineMagnetDetector (PHG4Subsystem * subsys, PHCompositeNode * Node, PHParameters * parameters, const std::string & dnam, const int magnetid = 0)
constructor
Definition at line 41 of file BeamLineMagnetDetector.cc.
View newest version in sPHENIX GitHub at line 41 of file BeamLineMagnetDetector.cc
BeamLineMagnetDetector::~BeamLineMagnetDetector (void) inline override
destructor
Definition at line 25 of file BeamLineMagnetDetector.h.
View newest version in sPHENIX GitHub at line 25 of file BeamLineMagnetDetector.h
Member Function Documentation
void BeamLineMagnetDetector::ConstructMe (G4LogicalVolume * world) override virtual
construct
Implements PHG4Detector.
Definition at line 68 of file BeamLineMagnetDetector.cc.
View newest version in sPHENIX GitHub at line 68 of file BeamLineMagnetDetector.cc
References BeamLineMagnetDisplayAction::AddVolume(), Acts::UnitConstants::cm, deg, ckf::field, PHParameters::get_double_param(), PHParameters::get_string_param(), PHG4Detector::GetDetectorMaterial(), PHG4Subsystem::GetMotherSubsystem(), PHG4Detector::GetMySubsystem(), PHG4Detector::GetName(), m_DisplayAction, m_magField, m_magnetFieldLogic, m_MagnetId, m_Params, magnet_core_physi, magnet_iron_physi, magnet_physi, Fun4AllBase::Name(), Acts::Test::origin(), PHG4Detector::OverlapCheck(), PHWHERE, PHG4Subsystem::SetLogicalVolume(), twopi, and PHG4Detector::Verbosity().
int BeamLineMagnetDetector::get_MagnetId () const inline
Definition at line 38 of file BeamLineMagnetDetector.h.
View newest version in sPHENIX GitHub at line 38 of file BeamLineMagnetDetector.h
References m_MagnetId.
int BeamLineMagnetDetector::IsInBeamLineMagnet (const G4VPhysicalVolume * volume) const
Definition at line 50 of file BeamLineMagnetDetector.cc.
View newest version in sPHENIX GitHub at line 50 of file BeamLineMagnetDetector.cc
References magnet_core_physi, magnet_iron_physi, and magnet_physi.
Referenced by BeamLineMagnetSteppingAction::UserSteppingAction().
void BeamLineMagnetDetector::PostConstruction () override virtual
Optional PostConstruction call after all geometry is constructed.
Reimplemented from PHG4Detector.
Definition at line 236 of file BeamLineMagnetDetector.cc.
View newest version in sPHENIX GitHub at line 236 of file BeamLineMagnetDetector.cc
References assert, m_magField, m_magnetFieldLogic, Acts::UnitConstants::mm, and PHG4Detector::Verbosity().
void BeamLineMagnetDetector::SuperDetector (const std::string & name) inline
Definition at line 36 of file BeamLineMagnetDetector.h.
View newest version in sPHENIX GitHub at line 36 of file BeamLineMagnetDetector.h
References m_SuperDetector, and perf_headwind::name.
Referenced by BeamLineMagnetSubsystem::InitRunSubsystem().
const std::string BeamLineMagnetDetector::SuperDetector () const inline
Definition at line 37 of file BeamLineMagnetDetector.h.
View newest version in sPHENIX GitHub at line 37 of file BeamLineMagnetDetector.h
References m_SuperDetector.
Member Data Documentation
BeamLineMagnetDisplayAction* BeamLineMagnetDetector::m_DisplayAction = nullptr private
Definition at line 46 of file BeamLineMagnetDetector.h.
View newest version in sPHENIX GitHub at line 46 of file BeamLineMagnetDetector.h
Referenced by ConstructMe().
G4MagneticField* BeamLineMagnetDetector::m_magField = nullptr private
Definition at line 48 of file BeamLineMagnetDetector.h.
View newest version in sPHENIX GitHub at line 48 of file BeamLineMagnetDetector.h
Referenced by ConstructMe(), and PostConstruction().
G4LogicalVolume* BeamLineMagnetDetector::m_magnetFieldLogic = nullptr private
Definition at line 47 of file BeamLineMagnetDetector.h.
View newest version in sPHENIX GitHub at line 47 of file BeamLineMagnetDetector.h
Referenced by ConstructMe(), and PostConstruction().
int BeamLineMagnetDetector::m_MagnetId = -1 private
Definition at line 50 of file BeamLineMagnetDetector.h.
View newest version in sPHENIX GitHub at line 50 of file BeamLineMagnetDetector.h
Referenced by ConstructMe(), and get_MagnetId().
PHParameters* BeamLineMagnetDetector::m_Params = nullptr private
Definition at line 41 of file BeamLineMagnetDetector.h.
View newest version in sPHENIX GitHub at line 41 of file BeamLineMagnetDetector.h
Referenced by ConstructMe().
std::string BeamLineMagnetDetector::m_SuperDetector = "NONE" private
Definition at line 52 of file BeamLineMagnetDetector.h.
View newest version in sPHENIX GitHub at line 52 of file BeamLineMagnetDetector.h
Referenced by SuperDetector().
G4VPhysicalVolume* BeamLineMagnetDetector::magnet_core_physi = nullptr private
Definition at line 45 of file BeamLineMagnetDetector.h.
View newest version in sPHENIX GitHub at line 45 of file BeamLineMagnetDetector.h
Referenced by ConstructMe(), and IsInBeamLineMagnet().
G4VPhysicalVolume* BeamLineMagnetDetector::magnet_iron_physi = nullptr private
Definition at line 44 of file BeamLineMagnetDetector.h.
View newest version in sPHENIX GitHub at line 44 of file BeamLineMagnetDetector.h
Referenced by ConstructMe(), and IsInBeamLineMagnet().
G4VPhysicalVolume* BeamLineMagnetDetector::magnet_physi = nullptr private
Definition at line 43 of file BeamLineMagnetDetector.h.
View newest version in sPHENIX GitHub at line 43 of file BeamLineMagnetDetector.h
Referenced by ConstructMe(), and IsInBeamLineMagnet().
The documentation for this class was generated from the following files:
coresoftware/blob/master/simulation/g4simulation/g4detectors/BeamLineMagnetDetector.h
coresoftware/blob/master/simulation/g4simulation/g4detectors/BeamLineMagnetDetector.cc