Analysis Software: nlohmann::detail::iteration_proxy_value< IteratorType > Class Template Reference
nlohmann::detail::iteration_proxy_value< IteratorType > Class Template Reference
#include <acts/blob/sPHENIX/thirdparty/nlohmann_json/single_include/nlohmann/json.hpp>
Public Types
using difference_type = std::ptrdiff_t
using value_type = iteration_proxy_value
using pointer = value_type *
using reference = value_type &
using iterator_category = std::input_iterator_tag
using string_type = typename std::remove_cv< typename std::remove_reference< decltype(std::declval< IteratorType >().key()) >::type >::type
Public Member Functions
iteration_proxy_value (IteratorType it) noexcept
iteration_proxy_value & operator* ()
dereference operator (needed for range-based for)
iteration_proxy_value & operator++ ()
increment operator (needed for range-based for)
bool operator== (const iteration_proxy_value &o) const
equality operator (needed for InputIterator)
bool operator!= (const iteration_proxy_value &o) const
inequality operator (needed for range-based for)
const string_type & key () const
return key of the iterator
IteratorType::reference value () const
return value of the iterator
Private Attributes
IteratorType anchor
the iterator
std::size_t array_index = 0
an index for arrays (used to create key names)
std::size_t array_index_last = 0
last stringified array index
string_type array_index_str = "0"
a string representation of the array index
const string_type empty_str = ""
an empty string (to return a reference for primitive values)
Detailed Description
template<typename IteratorType>
class nlohmann::detail::iteration_proxy_value< IteratorType >
Definition at line 3626 of file json.hpp.
View newest version in sPHENIX GitHub at line 3626 of file json.hpp
Member Typedef Documentation
template<typename IteratorType > using nlohmann::detail::iteration_proxy_value< IteratorType >::difference_type = std::ptrdiff_t
Definition at line 3629 of file json.hpp.
View newest version in sPHENIX GitHub at line 3629 of file json.hpp
template<typename IteratorType > using nlohmann::detail::iteration_proxy_value< IteratorType >::iterator_category = std::input_iterator_tag
Definition at line 3633 of file json.hpp.
View newest version in sPHENIX GitHub at line 3633 of file json.hpp
template<typename IteratorType > using nlohmann::detail::iteration_proxy_value< IteratorType >::pointer = value_type *
Definition at line 3631 of file json.hpp.
View newest version in sPHENIX GitHub at line 3631 of file json.hpp
template<typename IteratorType > using nlohmann::detail::iteration_proxy_value< IteratorType >::reference = value_type &
Definition at line 3632 of file json.hpp.
View newest version in sPHENIX GitHub at line 3632 of file json.hpp
template<typename IteratorType > using nlohmann::detail::iteration_proxy_value< IteratorType >::string_type = typename std::remove_cv< typename std::remove_reference<decltype(std::declval<IteratorType>().key()) >::type >::type
Definition at line 3634 of file json.hpp.
View newest version in sPHENIX GitHub at line 3634 of file json.hpp
template<typename IteratorType > using nlohmann::detail::iteration_proxy_value< IteratorType >::value_type = iteration_proxy_value
Definition at line 3630 of file json.hpp.
View newest version in sPHENIX GitHub at line 3630 of file json.hpp
Constructor & Destructor Documentation
template<typename IteratorType > nlohmann::detail::iteration_proxy_value< IteratorType >::iteration_proxy_value (IteratorType it) inline explicit noexcept
Definition at line 3649 of file json.hpp.
View newest version in sPHENIX GitHub at line 3649 of file json.hpp
Member Function Documentation
template<typename IteratorType > const string_type& nlohmann::detail::iteration_proxy_value< IteratorType >::key () const inline
return key of the iterator
Definition at line 3679 of file json.hpp.
View newest version in sPHENIX GitHub at line 3679 of file json.hpp
References TauVsDIS_MachineLearning_Differentiation::array, assert, and nlohmann::detail::int_to_string().
Referenced by __example_4.f__(), __example_5.f__(), __example_6.f__(), __example_7.f__(), and __example_8.f__().
template<typename IteratorType > bool nlohmann::detail::iteration_proxy_value< IteratorType >::operator!= (const iteration_proxy_value< IteratorType > & o) const inline
inequality operator (needed for range-based for)
Definition at line 3673 of file json.hpp.
View newest version in sPHENIX GitHub at line 3673 of file json.hpp
References nlohmann::detail::iteration_proxy_value< IteratorType >::anchor.
template<typename IteratorType > iteration_proxy_value& nlohmann::detail::iteration_proxy_value< IteratorType >::operator* () inline
dereference operator (needed for range-based for)
Definition at line 3652 of file json.hpp.
View newest version in sPHENIX GitHub at line 3652 of file json.hpp
template<typename IteratorType > iteration_proxy_value& nlohmann::detail::iteration_proxy_value< IteratorType >::operator++ () inline
increment operator (needed for range-based for)
Definition at line 3658 of file json.hpp.
View newest version in sPHENIX GitHub at line 3658 of file json.hpp
template<typename IteratorType > bool nlohmann::detail::iteration_proxy_value< IteratorType >::operator== (const iteration_proxy_value< IteratorType > & o) const inline
equality operator (needed for InputIterator)
Definition at line 3667 of file json.hpp.
View newest version in sPHENIX GitHub at line 3667 of file json.hpp
References nlohmann::detail::iteration_proxy_value< IteratorType >::anchor.
template<typename IteratorType > IteratorType::reference nlohmann::detail::iteration_proxy_value< IteratorType >::value () const inline
return value of the iterator
Definition at line 3707 of file json.hpp.
View newest version in sPHENIX GitHub at line 3707 of file json.hpp
Member Data Documentation
template<typename IteratorType > IteratorType nlohmann::detail::iteration_proxy_value< IteratorType >::anchor private
the iterator
Definition at line 3638 of file json.hpp.
View newest version in sPHENIX GitHub at line 3638 of file json.hpp
Referenced by nlohmann::detail::iteration_proxy_value< IteratorType >::operator!=(), and nlohmann::detail::iteration_proxy_value< IteratorType >::operator==().
template<typename IteratorType > std::size_t nlohmann::detail::iteration_proxy_value< IteratorType >::array_index = 0 private
an index for arrays (used to create key names)
Definition at line 3640 of file json.hpp.
View newest version in sPHENIX GitHub at line 3640 of file json.hpp
template<typename IteratorType > std::size_t nlohmann::detail::iteration_proxy_value< IteratorType >::array_index_last = 0 mutable private
last stringified array index
Definition at line 3642 of file json.hpp.
View newest version in sPHENIX GitHub at line 3642 of file json.hpp
template<typename IteratorType > string_type nlohmann::detail::iteration_proxy_value< IteratorType >::array_index_str = "0" mutable private
a string representation of the array index
Definition at line 3644 of file json.hpp.
View newest version in sPHENIX GitHub at line 3644 of file json.hpp
template<typename IteratorType > const string_type nlohmann::detail::iteration_proxy_value< IteratorType >::empty_str = "" private
an empty string (to return a reference for primitive values)
Definition at line 3646 of file json.hpp.
View newest version in sPHENIX GitHub at line 3646 of file json.hpp
The documentation for this class was generated from the following file:
acts/blob/sPHENIX/thirdparty/nlohmann_json/single_include/nlohmann/json.hpp