Analysis Software: macros/blob/master/StreamingProduction/Fun4All_Stream_Combiner.C File Reference
Fun4All_Stream_Combiner.C File Reference
#include <fun4all/Fun4AllDstOutputManager.h>
#include <fun4all/Fun4AllInputManager.h>
#include <fun4all/Fun4AllOutputManager.h>
#include <fun4all/Fun4AllServer.h>
#include <fun4allraw/Fun4AllStreamingInputManager.h>
#include <fun4allraw/SingleGl1PoolInput.h>
#include <fun4allraw/SingleInttPoolInput.h>
#include <fun4allraw/SingleMicromegasPoolInput.h>
#include <fun4allraw/SingleMvtxPoolInput.h>
#include <fun4allraw/SingleTpcPoolInput.h>
#include <phool/recoConsts.h>
#include <ffarawmodules/InttCheck.h>
#include <ffarawmodules/StreamingCheck.h>
#include <ffarawmodules/TpcCheck.h>
Functions
void Fun4All_Stream_Combiner (int nEvents=0, const string &input_gl1file="gl1.list", const string &input_inttfile00="intt0.list", const string &input_inttfile01="intt1.list", const string &input_inttfile02="intt2.list", const string &input_inttfile03="intt3.list", const string &input_inttfile04="intt4.list", const string &input_inttfile05="intt5.list", const string &input_inttfile06="intt6.list", const string &input_inttfile07="intt7.list", const string &input_mvtxfile00="mvtx-flx0.list", const string &input_mvtxfile01="mvtx-flx1.list", const string &input_mvtxfile02="mvtx-flx2.list", const string &input_mvtxfile03="mvtx-flx3.list", const string &input_mvtxfile04="mvtx-flx4.list", const string &input_mvtxfile05="mvtx-flx5.list", const string &input_tpcfile00="tpc00.list", const string &input_tpcfile01="tpc01.list", const string &input_tpcfile02="tpc02.list", const string &input_tpcfile03="tpc03.list", const string &input_tpcfile04="tpc04.list", const string &input_tpcfile05="tpc05.list", const string &input_tpcfile06="tpc06.list", const string &input_tpcfile07="tpc07.list", const string &input_tpcfile08="tpc08.list", const string &input_tpcfile09="tpc09.list", const string &input_tpcfile10="tpc10.list", const string &input_tpcfile11="tpc11.list", const string &input_tpcfile12="tpc12.list", const string &input_tpcfile13="tpc13.list", const string &input_tpcfile14="tpc14.list", const string &input_tpcfile15="tpc15.list", const string &input_tpcfile16="tpc16.list", const string &input_tpcfile17="tpc17.list", const string &input_tpcfile18="tpc18.list", const string &input_tpcfile19="tpc19.list", const string &input_tpcfile20="tpc20.list", const string &input_tpcfile21="tpc21.list", const string &input_tpcfile22="tpc22.list", const string &input_tpcfile23="tpc23.list", const string &input_tpotfile="tpot.list")
Function Documentation
void Fun4All_Stream_Combiner (int nEvents = 0, const string & input_gl1file = "gl1.list", const string & input_inttfile00 = "intt0.list", const string & input_inttfile01 = "intt1.list", const string & input_inttfile02 = "intt2.list", const string & input_inttfile03 = "intt3.list", const string & input_inttfile04 = "intt4.list", const string & input_inttfile05 = "intt5.list", const string & input_inttfile06 = "intt6.list", const string & input_inttfile07 = "intt7.list", const string & input_mvtxfile00 = "mvtx-flx0.list", const string & input_mvtxfile01 = "mvtx-flx1.list", const string & input_mvtxfile02 = "mvtx-flx2.list", const string & input_mvtxfile03 = "mvtx-flx3.list", const string & input_mvtxfile04 = "mvtx-flx4.list", const string & input_mvtxfile05 = "mvtx-flx5.list", const string & input_tpcfile00 = "tpc00.list", const string & input_tpcfile01 = "tpc01.list", const string & input_tpcfile02 = "tpc02.list", const string & input_tpcfile03 = "tpc03.list", const string & input_tpcfile04 = "tpc04.list", const string & input_tpcfile05 = "tpc05.list", const string & input_tpcfile06 = "tpc06.list", const string & input_tpcfile07 = "tpc07.list", const string & input_tpcfile08 = "tpc08.list", const string & input_tpcfile09 = "tpc09.list", const string & input_tpcfile10 = "tpc10.list", const string & input_tpcfile11 = "tpc11.list", const string & input_tpcfile12 = "tpc12.list", const string & input_tpcfile13 = "tpc13.list", const string & input_tpcfile14 = "tpc14.list", const string & input_tpcfile15 = "tpc15.list", const string & input_tpcfile16 = "tpc16.list", const string & input_tpcfile17 = "tpc17.list", const string & input_tpcfile18 = "tpc18.list", const string & input_tpcfile19 = "tpc19.list", const string & input_tpcfile20 = "tpc20.list", const string & input_tpcfile21 = "tpc21.list", const string & input_tpcfile22 = "tpc22.list", const string & input_tpcfile23 = "tpc23.list", const string & input_tpotfile = "tpot.list")
Definition at line 22 of file Fun4All_Stream_Combiner.C.
View newest version in sPHENIX GitHub at line 22 of file Fun4All_Stream_Combiner.C
References InputFileHandler::AddListFile(), Fun4AllServer::End(), Fun4AllStreamingInputManager::GL1, i, in, recoConsts::instance(), Fun4AllServer::instance(), Fun4AllStreamingInputManager::INTT, Fun4AllStreamingInputManager::MICROMEGAS, Fun4AllStreamingInputManager::MVTX, out, Fun4AllServer::registerInputManager(), Fun4AllServer::registerOutputManager(), Fun4AllStreamingInputManager::registerStreamingInput(), Fun4AllServer::run(), SingleTpcPoolInput::SetBcoRange(), SingleMicromegasPoolInput::SetBcoRange(), SingleInttPoolInput::SetBcoRange(), SingleMvtxPoolInput::SetBcoRange(), SingleMicromegasPoolInput::SetNegativeBco(), SingleInttPoolInput::SetNegativeBco(), SingleMvtxPoolInput::SetNegativeBco(), to_string(), Fun4AllStreamingInputManager::TPC, and Fun4AllBase::Verbosity().