Analysis Software: Acts::EllipseBounds Class Reference
Acts::EllipseBounds Class Reference
#include <acts/blob/sPHENIX/Core/include/Acts/Surfaces/EllipseBounds.hpp>
Public Types
enum BoundValues {
eInnerRx = 0, eInnerRy = 1, eOuterRx = 2, eOuterRy = 3,
eHalfPhiSector = 4, eAveragePhi = 5, eSize = 6
}
Public Member Functions
EllipseBounds ()=delete
EllipseBounds (double innerRx, double innerRy, double outerRx, double outerRy, double halfPhi=M_PI, double averagePhi=0.) noexcept(false)
m_boundingBox (m_values[eInnerRy], m_values[eOuterRy])
EllipseBounds (const std::array< double, eSize > &values) noexcept(false)
~EllipseBounds () override=default
BoundsType type () const final
std::vector< double > values () const final
bool inside (const Vector2 &lposition, const BoundaryCheck &bcheck) const final
std::vector< Vector2 > vertices (unsigned int lseg) const final
const RectangleBounds & boundingBox () const final
std::ostream & toStream (std::ostream &sl) const final
Output Method for std::ostream.
double get (BoundValues bValue) const
Private Member Functions
void checkConsistency () noexcept(false)
Private Attributes
std::array< double, eSize > m_values
RectangleBounds m_boundingBox
Detailed Description
Class to describe the bounds for a planar ellispoid surface.
By providing an argument for hphisec, the bounds can be restricted to a phi-range around the center position.
Definition at line 35 of file EllipseBounds.hpp.
View newest version in sPHENIX GitHub at line 35 of file EllipseBounds.hpp
Member Enumeration Documentation
enum Acts::EllipseBounds::BoundValues
Enumerator:
eInnerRx
eInnerRy
eOuterRx
eOuterRy
eHalfPhiSector
eAveragePhi
eSize
Definition at line 37 of file EllipseBounds.hpp.
View newest version in sPHENIX GitHub at line 37 of file EllipseBounds.hpp
Constructor & Destructor Documentation
Acts::EllipseBounds::EllipseBounds () delete
Acts::EllipseBounds::EllipseBounds (double innerRx, double innerRy, double outerRx, double outerRy, double halfPhi = M_PI, double averagePhi = 0.) inline noexcept
Constructor for full of an ellipsoid ring
Parameters
innerRx The inner ellipse radius in x
innerRy The inner ellipse radius in y
outerRx The outer ellipse radius in x
outerRy The outer ellipse radius in y
halfPhi spanning phi sector (is set to pi as default)
averagePhi average phi (is set to 0. as default)
Definition at line 57 of file EllipseBounds.hpp.
View newest version in sPHENIX GitHub at line 57 of file EllipseBounds.hpp
Acts::EllipseBounds::EllipseBounds (const std::array< double, eSize > & values) inline noexcept
Constructor - from fixed size array
Parameters
values The parameter values
Definition at line 67 of file EllipseBounds.hpp.
View newest version in sPHENIX GitHub at line 67 of file EllipseBounds.hpp
References checkConsistency().
Acts::EllipseBounds::~EllipseBounds () override default
Member Function Documentation
const Acts::RectangleBounds & Acts::EllipseBounds::boundingBox () const final virtual
Bounding box parameters
Returns
rectangle bounds for a bounding box
Implements Acts::PlanarBounds.
Definition at line 56 of file EllipseBounds.cpp.
View newest version in sPHENIX GitHub at line 56 of file EllipseBounds.cpp
Referenced by Acts::Test::BOOST_AUTO_TEST_CASE().
void Acts::EllipseBounds::checkConsistency () inline private noexcept
Check the input values for consistency, will throw a logic_exception if consistency is not given
Definition at line 127 of file EllipseBounds.hpp.
View newest version in sPHENIX GitHub at line 127 of file EllipseBounds.hpp
References eAveragePhi, eHalfPhiSector, eInnerRx, eOuterRx, and Acts::detail::radian_sym().
Referenced by EllipseBounds(), and m_boundingBox().
double Acts::EllipseBounds::get (BoundValues bValue) const inline
Access to the bound values
Parameters
bValue the class nested enum for the array access
Definition at line 110 of file EllipseBounds.hpp.
View newest version in sPHENIX GitHub at line 110 of file EllipseBounds.hpp
References m_values.
Referenced by Acts::Test::BOOST_AUTO_TEST_CASE().
bool Acts::EllipseBounds::inside (const Vector2 & lposition, const BoundaryCheck & bcheck) const final virtual
This method checks if the point given in the local coordinates is between two ellipsoids if only tol0 is given and additional in the phi sector is tol1 is given
Parameters
lposition Local position (assumed to be in right surface frame)
bcheck boundary check directive
Returns
boolean indicator for the success of this operation
Warning
This only works for tolerance-based checks
Implements Acts::SurfaceBounds.
Definition at line 30 of file EllipseBounds.cpp.
View newest version in sPHENIX GitHub at line 30 of file EllipseBounds.cpp
References Acts::eBoundLoc0, Acts::eBoundLoc1, Acts::BoundaryCheck::m_tolerance, ActsTests::PropagationDatasets::phi, Acts::VectorHelpers::phi(), Acts::detail::radian_sym(), and square().
Referenced by Acts::Test::BOOST_AUTO_TEST_CASE().
Acts::EllipseBounds::m_boundingBox (m_values [eInnerRy], m_values [eOuterRy]) inline
Definition at line 60 of file EllipseBounds.hpp.
View newest version in sPHENIX GitHub at line 60 of file EllipseBounds.hpp
References checkConsistency().
std::ostream & Acts::EllipseBounds::toStream (std::ostream & sl) const final virtual
Output Method for std::ostream.
Implements Acts::SurfaceBounds.
Definition at line 61 of file EllipseBounds.cpp.
View newest version in sPHENIX GitHub at line 61 of file EllipseBounds.cpp
Referenced by Acts::Test::BOOST_AUTO_TEST_CASE().
Acts::SurfaceBounds::BoundsType Acts::EllipseBounds::type () const final virtual
Return the bounds type - for persistency optimization
Returns
is a BoundsType enum
Implements Acts::SurfaceBounds.
Definition at line 21 of file EllipseBounds.cpp.
View newest version in sPHENIX GitHub at line 21 of file EllipseBounds.cpp
References Acts::SurfaceBounds::eEllipse.
Referenced by Acts::Test::BOOST_AUTO_TEST_CASE().
std::vector< double > Acts::EllipseBounds::values () const inline final virtual
Return the bound values as dynamically sized vector
Returns
this returns a copy of the internal values
Implements Acts::SurfaceBounds.
Definition at line 121 of file EllipseBounds.hpp.
View newest version in sPHENIX GitHub at line 121 of file EllipseBounds.hpp
References m_values.
Referenced by Acts::Test::BOOST_AUTO_TEST_CASE().
std::vector< Acts::Vector2 > Acts::EllipseBounds::vertices (unsigned int lseg) const final virtual
Return the vertices
Parameters
lseg the number of segments used to approximate and eventually curved line, here it refers to the full 2PI Ellipse
Note
the number of segments to may be altered by also providing the extremas in all direction
Returns
vector for vertices in 2D
Implements Acts::PlanarBounds.
Definition at line 49 of file EllipseBounds.cpp.
View newest version in sPHENIX GitHub at line 49 of file EllipseBounds.cpp
References Acts::detail::VerticesHelper::ellipsoidVertices().
Member Data Documentation
RectangleBounds Acts::EllipseBounds::m_boundingBox private
Definition at line 114 of file EllipseBounds.hpp.
View newest version in sPHENIX GitHub at line 114 of file EllipseBounds.hpp
std::array<double, eSize> Acts::EllipseBounds::m_values private
Definition at line 113 of file EllipseBounds.hpp.
View newest version in sPHENIX GitHub at line 113 of file EllipseBounds.hpp
Referenced by get(), and values().
The documentation for this class was generated from the following files:
acts/blob/sPHENIX/Core/include/Acts/Surfaces/EllipseBounds.hpp
acts/blob/sPHENIX/Core/src/Surfaces/EllipseBounds.cpp