Analysis Software: PHG4TpcEndCapSteppingAction Class Reference
PHG4TpcEndCapSteppingAction Class Reference
#include <coresoftware/blob/master/simulation/g4simulation/g4tpc/PHG4TpcEndCapSteppingAction.h>
Public Member Functions
PHG4TpcEndCapSteppingAction (PHG4TpcEndCapDetector *, const PHParameters *parameters)
constructor
~PHG4TpcEndCapSteppingAction () override
destructor
bool UserSteppingAction (const G4Step *, bool) override
stepping action
void SetInterfacePointers (PHCompositeNode *) override
reimplemented from base class
void SetHitNodeName (const std::string &type, const std::string &name) override
Set the G4HIT node names from Subsystem rather than constructing your own.
Public Member Functions inherited from PHG4SteppingAction
PHG4SteppingAction (const std::string &name, const int i=0)
virtual ~PHG4SteppingAction ()
virtual void Verbosity (const int i)
virtual int Verbosity () const
virtual int Init ()
virtual int InitWithNode (PHCompositeNode *)
virtual double GetScintLightYield (const G4Step *step)
get scintillation photon count. It require a custom set SCINTILLATIONYIELD property to work
virtual double GetVisibleEnergyDeposition (const G4Step *step)
get amount of energy that can make scintillation light, in Unit of GeV.
virtual void StoreLocalCoordinate (PHG4Hit *hit, const G4Step *step, const bool do_prepoint, const bool do_postpoint)
Extract local coordinate of the hit and save to PHG4Hit.
virtual void Print (const std::string &) const
std::string GetName () const
void SetName (const std::string &name)
virtual void SetLightCorrection (const double inner_radius, const double inner_corr, const double outer_radius, const double outer_corr)
virtual double GetLightCorrection (const double r) const
virtual double GetLightCorrection (const double xpos, const double ypos) const
virtual bool ValidCorrection () const
Private Attributes
PHG4TpcEndCapDetector * m_Detector = nullptr
pointer to the detector
const PHParameters * m_Params = nullptr
PHG4HitContainer * m_HitContainer = nullptr
pointer to hit container
PHG4Hit * m_Hit = nullptr
PHG4HitContainer * m_SaveHitContainer = nullptr
G4VPhysicalVolume * m_SaveVolPre = nullptr
G4VPhysicalVolume * m_SaveVolPost = nullptr
int m_SaveTrackId = -1
int m_SavePreStepStatus = -1
int m_SavePostStepStatus = -1
int m_ActiveFlag = 0
int m_BlackHoleFlag = 0
double m_EdepSum = 0.
double m_EionSum = 0.
std::string m_HitNodeName
Detailed Description
Definition at line 19 of file PHG4TpcEndCapSteppingAction.h.
View newest version in sPHENIX GitHub at line 19 of file PHG4TpcEndCapSteppingAction.h
Constructor & Destructor Documentation
PHG4TpcEndCapSteppingAction::PHG4TpcEndCapSteppingAction (PHG4TpcEndCapDetector * detector, const PHParameters * parameters)
constructor
Definition at line 43 of file PHG4TpcEndCapSteppingAction.cc.
View newest version in sPHENIX GitHub at line 43 of file PHG4TpcEndCapSteppingAction.cc
PHG4TpcEndCapSteppingAction::~PHG4TpcEndCapSteppingAction () override
destructor
Definition at line 53 of file PHG4TpcEndCapSteppingAction.cc.
View newest version in sPHENIX GitHub at line 53 of file PHG4TpcEndCapSteppingAction.cc
References m_Hit.
Member Function Documentation
void PHG4TpcEndCapSteppingAction::SetHitNodeName (const std::string & , const std::string &) override virtual
Set the G4HIT node names from Subsystem rather than constructing your own.
Reimplemented from PHG4SteppingAction.
Definition at line 331 of file PHG4TpcEndCapSteppingAction.cc.
View newest version in sPHENIX GitHub at line 331 of file PHG4TpcEndCapSteppingAction.cc
References m_HitNodeName, and perf_headwind::name.
void PHG4TpcEndCapSteppingAction::SetInterfacePointers (PHCompositeNode * topNode) override virtual
reimplemented from base class
Reimplemented from PHG4SteppingAction.
Definition at line 318 of file PHG4TpcEndCapSteppingAction.cc.
View newest version in sPHENIX GitHub at line 318 of file PHG4TpcEndCapSteppingAction.cc
References m_HitContainer, and m_HitNodeName.
bool PHG4TpcEndCapSteppingAction::UserSteppingAction (const G4Step * aStep, bool) override virtual
stepping action
Implements PHG4SteppingAction.
Definition at line 64 of file PHG4TpcEndCapSteppingAction.cc.
View newest version in sPHENIX GitHub at line 64 of file PHG4TpcEndCapSteppingAction.cc
References PHG4HitContainer::AddHit(), Acts::UnitConstants::cm, PHG4Hit::get_hit_id(), PHG4Hit::get_x(), PHG4HitContainer::GetID(), PHG4SteppingAction::GetName(), PHG4StepStatusDecode::GetStepStatus(), Acts::UnitConstants::GeV, PHG4TpcEndCapDetector::IsInDetector(), m_BlackHoleFlag, m_Detector, m_EdepSum, m_EionSum, m_Hit, m_HitContainer, m_SaveHitContainer, m_SavePostStepStatus, m_SavePreStepStatus, m_SaveTrackId, m_SaveVolPost, m_SaveVolPre, merge_hashes::p, PHG4Hit::Reset(), PHG4Hit::set_edep(), PHG4Hit::set_eion(), PHG4Hit::set_layer(), PHG4Hit::set_t(), PHG4Hit::set_trkid(), PHG4Hit::set_x(), PHG4Hit::set_y(), and PHG4Hit::set_z().
Member Data Documentation
int PHG4TpcEndCapSteppingAction::m_ActiveFlag = 0 private
Definition at line 50 of file PHG4TpcEndCapSteppingAction.h.
View newest version in sPHENIX GitHub at line 50 of file PHG4TpcEndCapSteppingAction.h
int PHG4TpcEndCapSteppingAction::m_BlackHoleFlag = 0 private
Definition at line 51 of file PHG4TpcEndCapSteppingAction.h.
View newest version in sPHENIX GitHub at line 51 of file PHG4TpcEndCapSteppingAction.h
Referenced by UserSteppingAction().
PHG4TpcEndCapDetector* PHG4TpcEndCapSteppingAction::m_Detector = nullptr private
pointer to the detector
Definition at line 38 of file PHG4TpcEndCapSteppingAction.h.
View newest version in sPHENIX GitHub at line 38 of file PHG4TpcEndCapSteppingAction.h
Referenced by UserSteppingAction().
double PHG4TpcEndCapSteppingAction::m_EdepSum = 0. private
Definition at line 52 of file PHG4TpcEndCapSteppingAction.h.
View newest version in sPHENIX GitHub at line 52 of file PHG4TpcEndCapSteppingAction.h
Referenced by UserSteppingAction().
double PHG4TpcEndCapSteppingAction::m_EionSum = 0. private
Definition at line 53 of file PHG4TpcEndCapSteppingAction.h.
View newest version in sPHENIX GitHub at line 53 of file PHG4TpcEndCapSteppingAction.h
Referenced by UserSteppingAction().
PHG4Hit* PHG4TpcEndCapSteppingAction::m_Hit = nullptr private
Definition at line 42 of file PHG4TpcEndCapSteppingAction.h.
View newest version in sPHENIX GitHub at line 42 of file PHG4TpcEndCapSteppingAction.h
Referenced by UserSteppingAction(), and ~PHG4TpcEndCapSteppingAction().
PHG4HitContainer* PHG4TpcEndCapSteppingAction::m_HitContainer = nullptr private
pointer to hit container
Definition at line 41 of file PHG4TpcEndCapSteppingAction.h.
View newest version in sPHENIX GitHub at line 41 of file PHG4TpcEndCapSteppingAction.h
Referenced by SetInterfacePointers(), and UserSteppingAction().
std::string PHG4TpcEndCapSteppingAction::m_HitNodeName private
Definition at line 55 of file PHG4TpcEndCapSteppingAction.h.
View newest version in sPHENIX GitHub at line 55 of file PHG4TpcEndCapSteppingAction.h
Referenced by SetHitNodeName(), and SetInterfacePointers().
const PHParameters* PHG4TpcEndCapSteppingAction::m_Params = nullptr private
Definition at line 39 of file PHG4TpcEndCapSteppingAction.h.
View newest version in sPHENIX GitHub at line 39 of file PHG4TpcEndCapSteppingAction.h
PHG4HitContainer* PHG4TpcEndCapSteppingAction::m_SaveHitContainer = nullptr private
Definition at line 43 of file PHG4TpcEndCapSteppingAction.h.
View newest version in sPHENIX GitHub at line 43 of file PHG4TpcEndCapSteppingAction.h
Referenced by UserSteppingAction().
int PHG4TpcEndCapSteppingAction::m_SavePostStepStatus = -1 private
Definition at line 49 of file PHG4TpcEndCapSteppingAction.h.
View newest version in sPHENIX GitHub at line 49 of file PHG4TpcEndCapSteppingAction.h
Referenced by UserSteppingAction().
int PHG4TpcEndCapSteppingAction::m_SavePreStepStatus = -1 private
Definition at line 48 of file PHG4TpcEndCapSteppingAction.h.
View newest version in sPHENIX GitHub at line 48 of file PHG4TpcEndCapSteppingAction.h
Referenced by UserSteppingAction().
int PHG4TpcEndCapSteppingAction::m_SaveTrackId = -1 private
Definition at line 47 of file PHG4TpcEndCapSteppingAction.h.
View newest version in sPHENIX GitHub at line 47 of file PHG4TpcEndCapSteppingAction.h
Referenced by UserSteppingAction().
G4VPhysicalVolume* PHG4TpcEndCapSteppingAction::m_SaveVolPost = nullptr private
Definition at line 45 of file PHG4TpcEndCapSteppingAction.h.
View newest version in sPHENIX GitHub at line 45 of file PHG4TpcEndCapSteppingAction.h
Referenced by UserSteppingAction().
G4VPhysicalVolume* PHG4TpcEndCapSteppingAction::m_SaveVolPre = nullptr private
Definition at line 44 of file PHG4TpcEndCapSteppingAction.h.
View newest version in sPHENIX GitHub at line 44 of file PHG4TpcEndCapSteppingAction.h
Referenced by UserSteppingAction().
The documentation for this class was generated from the following files:
coresoftware/blob/master/simulation/g4simulation/g4tpc/PHG4TpcEndCapSteppingAction.h
coresoftware/blob/master/simulation/g4simulation/g4tpc/PHG4TpcEndCapSteppingAction.cc