Analysis Software: MicromegasCombinedDataDecoder Class Reference
MicromegasCombinedDataDecoder Class Reference
micromegas raw data decoder
#include <coresoftware/blob/master/offline/packages/micromegas/MicromegasCombinedDataDecoder.h>
Public Member Functions
MicromegasCombinedDataDecoder (const std::string &name="MicromegasCombinedDataDecoder")
constructor
int Init (PHCompositeNode *) override
global initialization
int InitRun (PHCompositeNode *) override
run initialization
int process_event (PHCompositeNode *) override
event processing
int End (PHCompositeNode *) override
end of processing
void set_calibration_file (const std::string &value)
calibration file
void set_hot_channel_map_file (const std::string &value)
hot channel map
void set_n_sigma (double value)
set number of RMS sigma used to defined static threshold on a given channel
void set_min_adc (double value)
set minimum ADC value, disregarding pedestal and RMS.
void set_sample_min (int value)
set min sample for noise estimation
void set_sample_max (int value)
set min sample for noise estimation
Public Member Functions inherited from SubsysReco
~SubsysReco () override
virtual int EndRun (const int)
Called at the end of each run.
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
void Print (const std::string &="ALL") const override
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Private Types
using hitcountmap_t = std::map< TrkrDefs::hitsetkey, int >
keep track of number of hits per hitsetid
Private Attributes
std::string m_rawhitnodename = "MICROMEGASRAWHIT"
raw node
MicromegasMapping m_mapping
mapping
double m_n_sigma = 5
number of RMS sigma used to define threshold
double m_min_adc = 50
minimum ADC value, disregarding pedestal and RMS.
int m_sample_min = 0
min sample for signal
int m_sample_max = 100
max sample for signal
hitcountmap_t m_hitcounts
calibration filename
std::string m_calibration_filename = "TPOT_Pedestal_000.root"
MicromegasCalibrationData m_calibration_data
hot channel map
std::string m_hot_channel_map_filename
MicromegasHotChannelMapData m_hot_channels
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = std::numeric_limits<int>::max() - 10
}
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Detailed Description
micromegas raw data decoder
Definition at line 21 of file MicromegasCombinedDataDecoder.h.
View newest version in sPHENIX GitHub at line 21 of file MicromegasCombinedDataDecoder.h
Member Typedef Documentation
using MicromegasCombinedDataDecoder::hitcountmap_t = std::map<TrkrDefs::hitsetkey,int> private
keep track of number of hits per hitsetid
Definition at line 93 of file MicromegasCombinedDataDecoder.h.
View newest version in sPHENIX GitHub at line 93 of file MicromegasCombinedDataDecoder.h
Constructor & Destructor Documentation
MicromegasCombinedDataDecoder::MicromegasCombinedDataDecoder (const std::string & name = "MicromegasCombinedDataDecoder")
constructor
Definition at line 27 of file MicromegasCombinedDataDecoder.cc.
View newest version in sPHENIX GitHub at line 27 of file MicromegasCombinedDataDecoder.cc
Member Function Documentation
int MicromegasCombinedDataDecoder::End (PHCompositeNode *) override virtual
end of processing
Reimplemented from SubsysReco.
Definition at line 226 of file MicromegasCombinedDataDecoder.cc.
View newest version in sPHENIX GitHub at line 226 of file MicromegasCombinedDataDecoder.cc
References test_fpe::count, Fun4AllReturnCodes::EVENT_OK, and m_hitcounts.
int MicromegasCombinedDataDecoder::Init (PHCompositeNode *) override virtual
global initialization
Reimplemented from SubsysReco.
Definition at line 32 of file MicromegasCombinedDataDecoder.cc.
View newest version in sPHENIX GitHub at line 32 of file MicromegasCombinedDataDecoder.cc
References Fun4AllReturnCodes::EVENT_OK, m_calibration_data, m_calibration_filename, m_hot_channel_map_filename, m_hot_channels, m_min_adc, m_n_sigma, m_sample_max, m_sample_min, MicromegasCalibrationData::read(), and MicromegasHotChannelMapData::read().
int MicromegasCombinedDataDecoder::InitRun (PHCompositeNode * topNode) override virtual
run initialization
Reimplemented from SubsysReco.
Definition at line 63 of file MicromegasCombinedDataDecoder.cc.
View newest version in sPHENIX GitHub at line 63 of file MicromegasCombinedDataDecoder.cc
References Fun4AllReturnCodes::EVENT_OK, and PHNodeIterator::findFirst().
int MicromegasCombinedDataDecoder::process_event (PHCompositeNode * topNode) override virtual
event processing
Reimplemented from SubsysReco.
Definition at line 101 of file MicromegasCombinedDataDecoder.cc.
View newest version in sPHENIX GitHub at line 101 of file MicromegasCombinedDataDecoder.cc
References assert, parse_cmake_options::begin, channel(), end, Fun4AllReturnCodes::EVENT_OK, MicromegasDefs::genHitKey(), MicromegasMapping::get_hitsetkey(), MicromegasCalibrationData::get_pedestal(), MicromegasMapping::get_physical_strip(), MicromegasCalibrationData::get_rms(), TrkrDefs::getLayer(), MicromegasDefs::getTileId(), MicromegasHotChannelMapData::is_hot_channel(), layer, m_calibration_data, m_hitcounts, m_hot_channels, m_mapping, m_min_adc, m_n_sigma, MicromegasDefs::m_packet_ids, m_rawhitnodename, m_sample_max, m_sample_min, Acts::UnitConstants::min, pedestal(), rms(), TrkrHitv2::setAdc(), tile(), and Fun4AllBase::Verbosity().
void MicromegasCombinedDataDecoder::set_calibration_file (const std::string & value) inline
calibration file
Definition at line 41 of file MicromegasCombinedDataDecoder.h.
View newest version in sPHENIX GitHub at line 41 of file MicromegasCombinedDataDecoder.h
References m_calibration_filename, and value.
void MicromegasCombinedDataDecoder::set_hot_channel_map_file (const std::string & value) inline
hot channel map
Definition at line 44 of file MicromegasCombinedDataDecoder.h.
View newest version in sPHENIX GitHub at line 44 of file MicromegasCombinedDataDecoder.h
References m_hot_channel_map_filename, and value.
void MicromegasCombinedDataDecoder::set_min_adc (double value) inline
set minimum ADC value, disregarding pedestal and RMS.
This removes faulty channels for which calibration has failed
Definition at line 51 of file MicromegasCombinedDataDecoder.h.
View newest version in sPHENIX GitHub at line 51 of file MicromegasCombinedDataDecoder.h
References m_min_adc, and value.
void MicromegasCombinedDataDecoder::set_n_sigma (double value) inline
set number of RMS sigma used to defined static threshold on a given channel
Definition at line 47 of file MicromegasCombinedDataDecoder.h.
View newest version in sPHENIX GitHub at line 47 of file MicromegasCombinedDataDecoder.h
References m_n_sigma, and value.
void MicromegasCombinedDataDecoder::set_sample_max (int value) inline
set min sample for noise estimation
Definition at line 57 of file MicromegasCombinedDataDecoder.h.
View newest version in sPHENIX GitHub at line 57 of file MicromegasCombinedDataDecoder.h
References m_sample_max, and value.
void MicromegasCombinedDataDecoder::set_sample_min (int value) inline
set min sample for noise estimation
Definition at line 54 of file MicromegasCombinedDataDecoder.h.
View newest version in sPHENIX GitHub at line 54 of file MicromegasCombinedDataDecoder.h
References m_sample_min, and value.
Member Data Documentation
MicromegasCalibrationData MicromegasCombinedDataDecoder::m_calibration_data private
Definition at line 67 of file MicromegasCombinedDataDecoder.h.
View newest version in sPHENIX GitHub at line 67 of file MicromegasCombinedDataDecoder.h
Referenced by Init(), and process_event().
std::string MicromegasCombinedDataDecoder::m_calibration_filename = "TPOT_Pedestal_000.root" private
Definition at line 66 of file MicromegasCombinedDataDecoder.h.
View newest version in sPHENIX GitHub at line 66 of file MicromegasCombinedDataDecoder.h
Referenced by Init(), and set_calibration_file().
hitcountmap_t MicromegasCombinedDataDecoder::m_hitcounts private
Definition at line 94 of file MicromegasCombinedDataDecoder.h.
View newest version in sPHENIX GitHub at line 94 of file MicromegasCombinedDataDecoder.h
Referenced by End(), and process_event().
std::string MicromegasCombinedDataDecoder::m_hot_channel_map_filename private
Definition at line 72 of file MicromegasCombinedDataDecoder.h.
View newest version in sPHENIX GitHub at line 72 of file MicromegasCombinedDataDecoder.h
Referenced by Init(), and set_hot_channel_map_file().
MicromegasHotChannelMapData MicromegasCombinedDataDecoder::m_hot_channels private
Definition at line 73 of file MicromegasCombinedDataDecoder.h.
View newest version in sPHENIX GitHub at line 73 of file MicromegasCombinedDataDecoder.h
Referenced by Init(), and process_event().
MicromegasMapping MicromegasCombinedDataDecoder::m_mapping private
mapping
Definition at line 77 of file MicromegasCombinedDataDecoder.h.
View newest version in sPHENIX GitHub at line 77 of file MicromegasCombinedDataDecoder.h
Referenced by process_event().
double MicromegasCombinedDataDecoder::m_min_adc = 50 private
minimum ADC value, disregarding pedestal and RMS.
Definition at line 84 of file MicromegasCombinedDataDecoder.h.
View newest version in sPHENIX GitHub at line 84 of file MicromegasCombinedDataDecoder.h
Referenced by Init(), process_event(), and set_min_adc().
double MicromegasCombinedDataDecoder::m_n_sigma = 5 private
number of RMS sigma used to define threshold
Definition at line 80 of file MicromegasCombinedDataDecoder.h.
View newest version in sPHENIX GitHub at line 80 of file MicromegasCombinedDataDecoder.h
Referenced by Init(), process_event(), and set_n_sigma().
std::string MicromegasCombinedDataDecoder::m_rawhitnodename = "MICROMEGASRAWHIT" private
raw node
Definition at line 62 of file MicromegasCombinedDataDecoder.h.
View newest version in sPHENIX GitHub at line 62 of file MicromegasCombinedDataDecoder.h
Referenced by process_event().
int MicromegasCombinedDataDecoder::m_sample_max = 100 private
max sample for signal
Definition at line 90 of file MicromegasCombinedDataDecoder.h.
View newest version in sPHENIX GitHub at line 90 of file MicromegasCombinedDataDecoder.h
Referenced by Init(), process_event(), and set_sample_max().
int MicromegasCombinedDataDecoder::m_sample_min = 0 private
min sample for signal
Definition at line 87 of file MicromegasCombinedDataDecoder.h.
View newest version in sPHENIX GitHub at line 87 of file MicromegasCombinedDataDecoder.h
Referenced by Init(), process_event(), and set_sample_min().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/micromegas/MicromegasCombinedDataDecoder.h
coresoftware/blob/master/offline/packages/micromegas/MicromegasCombinedDataDecoder.cc