Analysis Software: nlohmann::basic_json::json_value Union Reference
nlohmann::basic_json::json_value Union Reference
a JSON value
Public Member Functions
json_value ()=default
default constructor (for null values)
json_value (boolean_t v) noexcept
constructor for booleans
json_value (number_integer_t v) noexcept
constructor for numbers (integer)
json_value (number_unsigned_t v) noexcept
constructor for numbers (unsigned)
json_value (number_float_t v) noexcept
constructor for numbers (floating-point)
json_value (value_t t)
constructor for empty values of a given type
json_value (const string_t &value)
constructor for strings
json_value (string_t &&value)
constructor for rvalue strings
json_value (const object_t &value)
constructor for objects
json_value (object_t &&value)
constructor for rvalue objects
json_value (const array_t &value)
constructor for arrays
json_value (array_t &&value)
constructor for rvalue arrays
void destroy (value_t t) noexcept
Public Attributes
object_t * object
object (stored with pointer to save storage)
array_t * array
array (stored with pointer to save storage)
string_t * string
string (stored with pointer to save storage)
boolean_t boolean
boolean
number_integer_t number_integer
number (integer)
number_unsigned_t number_unsigned
number (unsigned integer)
number_float_t number_float
number (floating-point)
Detailed Description
a JSON value
The actual storage for a JSON value of the basic_json class. This union combines the different storage types for the JSON value types defined in value_t.
JSON type value_t type used type
object object pointer to object_t
array array pointer to array_t
string string pointer to string_t
boolean boolean boolean_t
number number_integer number_integer_t
number number_unsigned number_unsigned_t
number number_float number_float_t
null null no value is stored
Note
Variable-length types (objects, arrays, and strings) are stored as pointers. The size of the union should not exceed 64 bits if the default value types are used.
Since
version 1.0.0
Definition at line 15743 of file json.hpp.
View newest version in sPHENIX GitHub at line 15743 of file json.hpp
Constructor & Destructor Documentation
nlohmann::basic_json::json_value::json_value () default
default constructor (for null values)
nlohmann::basic_json::json_value::json_value (boolean_t v) inline noexcept
constructor for booleans
Definition at line 15763 of file json.hpp.
View newest version in sPHENIX GitHub at line 15763 of file json.hpp
nlohmann::basic_json::json_value::json_value (number_integer_t v) inline noexcept
constructor for numbers (integer)
Definition at line 15765 of file json.hpp.
View newest version in sPHENIX GitHub at line 15765 of file json.hpp
nlohmann::basic_json::json_value::json_value (number_unsigned_t v) inline noexcept
constructor for numbers (unsigned)
Definition at line 15767 of file json.hpp.
View newest version in sPHENIX GitHub at line 15767 of file json.hpp
nlohmann::basic_json::json_value::json_value (number_float_t v) inline noexcept
constructor for numbers (floating-point)
Definition at line 15769 of file json.hpp.
View newest version in sPHENIX GitHub at line 15769 of file json.hpp
nlohmann::basic_json::json_value::json_value (value_t t) inline
constructor for empty values of a given type
Definition at line 15771 of file json.hpp.
View newest version in sPHENIX GitHub at line 15771 of file json.hpp
References TauVsDIS_MachineLearning_Differentiation::array, JSON_HEDLEY_UNLIKELY, JSON_THROW, and Jetscape::null.
nlohmann::basic_json::json_value::json_value (const string_t & value) inline
constructor for strings
Definition at line 15836 of file json.hpp.
View newest version in sPHENIX GitHub at line 15836 of file json.hpp
References value.
nlohmann::basic_json::json_value::json_value (string_t && value) inline
constructor for rvalue strings
Definition at line 15842 of file json.hpp.
View newest version in sPHENIX GitHub at line 15842 of file json.hpp
References testing::internal::move(), and value.
nlohmann::basic_json::json_value::json_value (const object_t & value) inline
constructor for objects
Definition at line 15848 of file json.hpp.
View newest version in sPHENIX GitHub at line 15848 of file json.hpp
References value.
nlohmann::basic_json::json_value::json_value (object_t && value) inline
constructor for rvalue objects
Definition at line 15854 of file json.hpp.
View newest version in sPHENIX GitHub at line 15854 of file json.hpp
References testing::internal::move(), and value.
nlohmann::basic_json::json_value::json_value (const array_t & value) inline
constructor for arrays
Definition at line 15860 of file json.hpp.
View newest version in sPHENIX GitHub at line 15860 of file json.hpp
References TauVsDIS_MachineLearning_Differentiation::array, and value.
nlohmann::basic_json::json_value::json_value (array_t && value) inline
constructor for rvalue arrays
Definition at line 15866 of file json.hpp.
View newest version in sPHENIX GitHub at line 15866 of file json.hpp
References TauVsDIS_MachineLearning_Differentiation::array, testing::internal::move(), and value.
Member Function Documentation
void nlohmann::basic_json::json_value::destroy (value_t t) inline noexcept
Definition at line 15871 of file json.hpp.
View newest version in sPHENIX GitHub at line 15871 of file json.hpp
References TauVsDIS_MachineLearning_Differentiation::array, array, nlohmann::basic_json::is_array(), nlohmann::basic_json::is_object(), it, nlohmann::basic_json::m_value, testing::internal::move(), object, and t.
Member Data Documentation
array_t* nlohmann::basic_json::json_value::array
array (stored with pointer to save storage)
Definition at line 15748 of file json.hpp.
View newest version in sPHENIX GitHub at line 15748 of file json.hpp
Referenced by ast.Type::__str__(), nlohmann::basic_json::basic_json(), and destroy().
boolean_t nlohmann::basic_json::json_value::boolean
boolean
Definition at line 15752 of file json.hpp.
View newest version in sPHENIX GitHub at line 15752 of file json.hpp
Referenced by nlohmann::basic_json::basic_json().
number_float_t nlohmann::basic_json::json_value::number_float
number (floating-point)
Definition at line 15758 of file json.hpp.
View newest version in sPHENIX GitHub at line 15758 of file json.hpp
Referenced by nlohmann::basic_json::basic_json().
number_integer_t nlohmann::basic_json::json_value::number_integer
number (integer)
Definition at line 15754 of file json.hpp.
View newest version in sPHENIX GitHub at line 15754 of file json.hpp
Referenced by nlohmann::basic_json::basic_json().
number_unsigned_t nlohmann::basic_json::json_value::number_unsigned
number (unsigned integer)
Definition at line 15756 of file json.hpp.
View newest version in sPHENIX GitHub at line 15756 of file json.hpp
Referenced by nlohmann::basic_json::basic_json().
object_t* nlohmann::basic_json::json_value::object
object (stored with pointer to save storage)
Definition at line 15746 of file json.hpp.
View newest version in sPHENIX GitHub at line 15746 of file json.hpp
Referenced by nlohmann::basic_json::basic_json(), and destroy().
string_t* nlohmann::basic_json::json_value::string
string (stored with pointer to save storage)
Definition at line 15750 of file json.hpp.
View newest version in sPHENIX GitHub at line 15750 of file json.hpp
Referenced by pump.Output::Append(), nlohmann::basic_json::basic_json(), and pump.Output::GetLastLine().
The documentation for this union was generated from the following file:
acts/blob/sPHENIX/thirdparty/nlohmann_json/single_include/nlohmann/json.hpp