Analysis Software: dfe::io_dsv_impl::NamedTupleDsvWriter< Delimiter, NamedTuple > Class Template Reference
dfe::io_dsv_impl::NamedTupleDsvWriter< Delimiter, NamedTuple > Class Template Reference
Write records as delimiter-separated values into a text file.
#include <acts/blob/sPHENIX/thirdparty/dfelibs/dfe/dfe_io_dsv.hpp>
Public Member Functions
NamedTupleDsvWriter ()=delete
NamedTupleDsvWriter (const NamedTupleDsvWriter &)=delete
NamedTupleDsvWriter (NamedTupleDsvWriter &&)=default
~NamedTupleDsvWriter ()=default
NamedTupleDsvWriter & operator= (const NamedTupleDsvWriter &)=delete
NamedTupleDsvWriter & operator= (NamedTupleDsvWriter &&)=default
NamedTupleDsvWriter (const std::string &path, int precision=std::numeric_limits< double >::max_digits10)
void append (const NamedTuple &record)
Append a record to the file.
Private Member Functions
template<std::size_t... I>
void append_impl (const NamedTuple &values, std::index_sequence< I...>)
Static Private Member Functions
static std::vector< std::string > colum_names ()
Private Attributes
DsvWriter< Delimiter > m_writer
Detailed Description
template<char Delimiter, typename NamedTuple>
class dfe::io_dsv_impl::NamedTupleDsvWriter< Delimiter, NamedTuple >
Write records as delimiter-separated values into a text file.
Definition at line 123 of file dfe_io_dsv.hpp.
View newest version in sPHENIX GitHub at line 123 of file dfe_io_dsv.hpp
Constructor & Destructor Documentation
template<char Delimiter, typename NamedTuple> dfe::io_dsv_impl::NamedTupleDsvWriter< Delimiter, NamedTuple >::NamedTupleDsvWriter () delete
template<char Delimiter, typename NamedTuple> dfe::io_dsv_impl::NamedTupleDsvWriter< Delimiter, NamedTuple >::NamedTupleDsvWriter (const NamedTupleDsvWriter< Delimiter, NamedTuple > &) delete
template<char Delimiter, typename NamedTuple> dfe::io_dsv_impl::NamedTupleDsvWriter< Delimiter, NamedTuple >::NamedTupleDsvWriter (NamedTupleDsvWriter< Delimiter, NamedTuple > &&) default
template<char Delimiter, typename NamedTuple> dfe::io_dsv_impl::NamedTupleDsvWriter< Delimiter, NamedTuple >::~NamedTupleDsvWriter () default
template<char Delimiter, typename NamedTuple> dfe::io_dsv_impl::NamedTupleDsvWriter< Delimiter, NamedTuple >::NamedTupleDsvWriter (const std::string & path, int precision = std::numeric_limits<double>::max_digits10) inline
Create a file at the given path. Overwrites existing data.
Parameters
path Path to the output file
precision Output floating point precision
Definition at line 136 of file dfe_io_dsv.hpp.
View newest version in sPHENIX GitHub at line 136 of file dfe_io_dsv.hpp
Member Function Documentation
template<char Delimiter, typename NamedTuple> void dfe::io_dsv_impl::NamedTupleDsvWriter< Delimiter, NamedTuple >::append (const NamedTuple & record) inline
Append a record to the file.
Definition at line 142 of file dfe_io_dsv.hpp.
View newest version in sPHENIX GitHub at line 142 of file dfe_io_dsv.hpp
References dfe::io_dsv_impl::NamedTupleDsvWriter< Delimiter, NamedTuple >::append_impl(), and value.
Referenced by ActsExamples::CsvParticleWriter::writeT(), and ActsExamples::CsvPlanarClusterWriter::writeT().
template<char Delimiter, typename NamedTuple> template<std::size_t... I> void dfe::io_dsv_impl::NamedTupleDsvWriter< Delimiter, NamedTuple >::append_impl (const NamedTuple & values, std::index_sequence< I...>) inline private
Definition at line 156 of file dfe_io_dsv.hpp.
View newest version in sPHENIX GitHub at line 156 of file dfe_io_dsv.hpp
References nlohmann::detail::get(), and dfe::io_dsv_impl::NamedTupleDsvWriter< Delimiter, NamedTuple >::m_writer.
Referenced by dfe::io_dsv_impl::NamedTupleDsvWriter< Delimiter, NamedTuple >::append().
template<char Delimiter, typename NamedTuple> static std::vector<std::string> dfe::io_dsv_impl::NamedTupleDsvWriter< Delimiter, NamedTuple >::colum_names () inline static private
Definition at line 151 of file dfe_io_dsv.hpp.
View newest version in sPHENIX GitHub at line 151 of file dfe_io_dsv.hpp
References TauVsDIS_MachineLearning_Differentiation::names.
template<char Delimiter, typename NamedTuple> NamedTupleDsvWriter& dfe::io_dsv_impl::NamedTupleDsvWriter< Delimiter, NamedTuple >::operator= (const NamedTupleDsvWriter< Delimiter, NamedTuple > &) delete
template<char Delimiter, typename NamedTuple> NamedTupleDsvWriter& dfe::io_dsv_impl::NamedTupleDsvWriter< Delimiter, NamedTuple >::operator= (NamedTupleDsvWriter< Delimiter, NamedTuple > &&) default
Member Data Documentation
template<char Delimiter, typename NamedTuple> DsvWriter<Delimiter> dfe::io_dsv_impl::NamedTupleDsvWriter< Delimiter, NamedTuple >::m_writer private
Definition at line 149 of file dfe_io_dsv.hpp.
View newest version in sPHENIX GitHub at line 149 of file dfe_io_dsv.hpp
Referenced by dfe::io_dsv_impl::NamedTupleDsvWriter< Delimiter, NamedTuple >::append_impl().
The documentation for this class was generated from the following file:
acts/blob/sPHENIX/thirdparty/dfelibs/dfe/dfe_io_dsv.hpp