Analysis Software: ActsExamples::SteppingAction Class Reference
ActsExamples::SteppingAction Class Reference final
Collects the RecordedMaterialSlab entities.
#include <acts/blob/sPHENIX/Examples/Algorithms/Geant4/src/SteppingAction.hpp>
Public Member Functions
SteppingAction ()
Construct the action and ensure singleton usage.
~SteppingAction () finaloverride
void UserSteppingAction (const G4Step *step) finaloverride
Interface Method doing the step.
void clear ()
Clear the recorded steps.
const std::vector
< Acts::MaterialInteraction > & materialSteps () const
Access the recorded material steps.
const
ActsExamples::SimHitContainer::sequence_type & trackSteps () const
Access the recorded tracking steps.
Static Public Member Functions
static SteppingAction * instance ()
Static access method to the instance.
Private Attributes
std::vector
< Acts::MaterialInteraction > m_materialSteps
The collected Acts::MaterialInteraction entities.
ActsExamples::SimHitContainer::sequence_type m_trackSteps
The collected ActsExamples::SimHit entities.
Static Private Attributes
static SteppingAction * s_instance = nullptr
Instance of the SteppingAction.
Detailed Description
Collects the RecordedMaterialSlab entities.
The SteppingAction class is the implementation of the Geant4 class SteppingAction. It extracts the weighted material of every step and collects all material steps.
Definition at line 28 of file SteppingAction.hpp.
View newest version in sPHENIX GitHub at line 28 of file SteppingAction.hpp
Constructor & Destructor Documentation
SteppingAction::SteppingAction ()
Construct the action and ensure singleton usage.
Definition at line 26 of file SteppingAction.cpp.
View newest version in sPHENIX GitHub at line 26 of file SteppingAction.cpp
References s_instance.
SteppingAction::~SteppingAction () final override
Definition at line 35 of file SteppingAction.cpp.
View newest version in sPHENIX GitHub at line 35 of file SteppingAction.cpp
References s_instance.
Member Function Documentation
void SteppingAction::clear ()
Clear the recorded steps.
Definition at line 134 of file SteppingAction.cpp.
View newest version in sPHENIX GitHub at line 134 of file SteppingAction.cpp
References m_materialSteps, and m_trackSteps.
Referenced by ActsExamples::EventAction::BeginOfEventAction().
SteppingAction * SteppingAction::instance () static
Static access method to the instance.
Definition at line 22 of file SteppingAction.cpp.
View newest version in sPHENIX GitHub at line 22 of file SteppingAction.cpp
References s_instance.
Referenced by ActsExamples::EventAction::BeginOfEventAction(), and ActsExamples::EventAction::EndOfEventAction().
const std::vector<Acts::MaterialInteraction>& ActsExamples::SteppingAction::materialSteps () const inline
Access the recorded material steps.
Definition at line 46 of file SteppingAction.hpp.
View newest version in sPHENIX GitHub at line 46 of file SteppingAction.hpp
References m_materialSteps.
Referenced by ActsExamples::EventAction::EndOfEventAction().
const ActsExamples::SimHitContainer::sequence_type& ActsExamples::SteppingAction::trackSteps () const inline
Access the recorded tracking steps.
Definition at line 51 of file SteppingAction.hpp.
View newest version in sPHENIX GitHub at line 51 of file SteppingAction.hpp
References m_trackSteps.
void SteppingAction::UserSteppingAction (const G4Step * step) final override
Interface Method doing the step.
Note
it creates and collects the MaterialInteraction entities
Parameters
step is the Geant4 step of the particle
Definition at line 39 of file SteppingAction.cpp.
View newest version in sPHENIX GitHub at line 39 of file SteppingAction.cpp
References Acts::MaterialInteraction::direction, Acts::Material::fromMassDensity(), Acts::UnitConstants::g, i, m_materialSteps, material, Acts::MaterialInteraction::materialSlab, Acts::UnitConstants::mm, Acts::UnitConstants::mm3, Acts::MaterialInteraction::position, and SVM_v1::Z.
Member Data Documentation
std::vector<Acts::MaterialInteraction> ActsExamples::SteppingAction::m_materialSteps private
The collected Acts::MaterialInteraction entities.
Definition at line 60 of file SteppingAction.hpp.
View newest version in sPHENIX GitHub at line 60 of file SteppingAction.hpp
Referenced by clear(), materialSteps(), and UserSteppingAction().
ActsExamples::SimHitContainer::sequence_type ActsExamples::SteppingAction::m_trackSteps private
The collected ActsExamples::SimHit entities.
Definition at line 62 of file SteppingAction.hpp.
View newest version in sPHENIX GitHub at line 62 of file SteppingAction.hpp
Referenced by clear(), and trackSteps().
SteppingAction * SteppingAction::s_instance = nullptr static private
Instance of the SteppingAction.
Definition at line 57 of file SteppingAction.hpp.
View newest version in sPHENIX GitHub at line 57 of file SteppingAction.hpp
Referenced by instance(), SteppingAction(), and ~SteppingAction().
The documentation for this class was generated from the following files:
acts/blob/sPHENIX/Examples/Algorithms/Geant4/src/SteppingAction.hpp
acts/blob/sPHENIX/Examples/Algorithms/Geant4/src/SteppingAction.cpp