Analysis Software: fuse_gtest_files Namespace Reference
fuse_gtest_files Namespace Reference
Functions
def VerifyFileExists
def ValidateGTestRootDir
def VerifyOutputFile
def ValidateOutputDir
def FuseGTestH
def FuseGTestAllCcToFile
def FuseGTestAllCc
def FuseGTest
def main
Variables
string __author__ 'wan@google.com (Zhanyong Wan)'
tuple DEFAULT_GTEST_ROOT_DIR os.path.join(os.path.dirname(__file__), '..')
tuple INCLUDE_GTEST_FILE_REGEX re.compile(r'^\s*#\s*include\s*"(gtest/.+)"')
tuple INCLUDE_SRC_FILE_REGEX re.compile(r'^\s*#\s*include\s*"(src/.+)"')
string GTEST_H_SEED 'include/gtest/gtest.h'
string GTEST_SPI_H_SEED 'include/gtest/gtest-spi.h'
string GTEST_ALL_CC_SEED 'src/gtest-all.cc'
string GTEST_H_OUTPUT 'gtest/gtest.h'
string GTEST_ALL_CC_OUTPUT 'gtest/gtest-all.cc'
Function Documentation
def fuse_gtest_files.FuseGTest (gtest_root, output_dir)
Fuses gtest.h and gtest-all.cc.
Definition at line 229 of file fuse_gtest_files.py.
View newest version in sPHENIX GitHub at line 229 of file fuse_gtest_files.py
References FuseGTestAllCc(), FuseGTestH(), ValidateGTestRootDir(), and ValidateOutputDir().
Referenced by main().
def fuse_gtest_files.FuseGTestAllCc (gtest_root, output_dir)
Scans folder gtest_root to generate gtest/gtest-all.cc in output_dir.
Definition at line 221 of file fuse_gtest_files.py.
View newest version in sPHENIX GitHub at line 221 of file fuse_gtest_files.py
References FuseGTestAllCcToFile(), and Acts.open.
Referenced by FuseGTest().
def fuse_gtest_files.FuseGTestAllCcToFile (gtest_root, output_file)
Scans folder gtest_root to generate gtest/gtest-all.cc in output_file.
Definition at line 178 of file fuse_gtest_files.py.
View newest version in sPHENIX GitHub at line 178 of file fuse_gtest_files.py
References Acts.open, and cpp.gmock_class.set.
Referenced by FuseGTestAllCc().
def fuse_gtest_files.FuseGTestH (gtest_root, output_dir)
Scans folder gtest_root to generate gtest/gtest.h in output_dir.
Definition at line 149 of file fuse_gtest_files.py.
View newest version in sPHENIX GitHub at line 149 of file fuse_gtest_files.py
References Acts.open, and cpp.gmock_class.set.
Referenced by FuseGTest().
def fuse_gtest_files.main (void)
Definition at line 239 of file fuse_gtest_files.py.
View newest version in sPHENIX GitHub at line 239 of file fuse_gtest_files.py
References FuseGTest(), and print().
def fuse_gtest_files.ValidateGTestRootDir (gtest_root)
Makes sure gtest_root points to a valid gtest root directory.
The function aborts the program on failure.
Definition at line 103 of file fuse_gtest_files.py.
View newest version in sPHENIX GitHub at line 103 of file fuse_gtest_files.py
References VerifyFileExists().
Referenced by FuseGTest().
def fuse_gtest_files.ValidateOutputDir (output_dir)
Makes sure output_dir points to a valid output directory.
The function aborts the program on failure.
Definition at line 139 of file fuse_gtest_files.py.
View newest version in sPHENIX GitHub at line 139 of file fuse_gtest_files.py
References VerifyOutputFile().
Referenced by FuseGTest().
def fuse_gtest_files.VerifyFileExists (directory, relative_path)
Verifies that the given file exists; aborts on failure.
relative_path is the file path relative to the given directory.
Definition at line 89 of file fuse_gtest_files.py.
View newest version in sPHENIX GitHub at line 89 of file fuse_gtest_files.py
References print().
Referenced by ValidateGTestRootDir().
def fuse_gtest_files.VerifyOutputFile (output_dir, relative_path)
Verifies that the given output file path is valid.
relative_path is relative to the output_dir directory.
Definition at line 113 of file fuse_gtest_files.py.
View newest version in sPHENIX GitHub at line 113 of file fuse_gtest_files.py
References print().
Referenced by ValidateOutputDir().
Variable Documentation
string fuse_gtest_files.__author__ 'wan@google.com (Zhanyong Wan)'
Definition at line 59 of file fuse_gtest_files.py.
View newest version in sPHENIX GitHub at line 59 of file fuse_gtest_files.py
tuple fuse_gtest_files.DEFAULT_GTEST_ROOT_DIR os.path.join(os.path.dirname(__file__), '..')
Definition at line 71 of file fuse_gtest_files.py.
View newest version in sPHENIX GitHub at line 71 of file fuse_gtest_files.py
string fuse_gtest_files.GTEST_ALL_CC_OUTPUT 'gtest/gtest-all.cc'
Definition at line 86 of file fuse_gtest_files.py.
View newest version in sPHENIX GitHub at line 86 of file fuse_gtest_files.py
string fuse_gtest_files.GTEST_ALL_CC_SEED 'src/gtest-all.cc'
Definition at line 82 of file fuse_gtest_files.py.
View newest version in sPHENIX GitHub at line 82 of file fuse_gtest_files.py
string fuse_gtest_files.GTEST_H_OUTPUT 'gtest/gtest.h'
Definition at line 85 of file fuse_gtest_files.py.
View newest version in sPHENIX GitHub at line 85 of file fuse_gtest_files.py
string fuse_gtest_files.GTEST_H_SEED 'include/gtest/gtest.h'
Definition at line 80 of file fuse_gtest_files.py.
View newest version in sPHENIX GitHub at line 80 of file fuse_gtest_files.py
string fuse_gtest_files.GTEST_SPI_H_SEED 'include/gtest/gtest-spi.h'
Definition at line 81 of file fuse_gtest_files.py.
View newest version in sPHENIX GitHub at line 81 of file fuse_gtest_files.py
tuple fuse_gtest_files.INCLUDE_GTEST_FILE_REGEX re.compile(r'^\s*#\s*include\s*"(gtest/.+)"')
Definition at line 74 of file fuse_gtest_files.py.
View newest version in sPHENIX GitHub at line 74 of file fuse_gtest_files.py
tuple fuse_gtest_files.INCLUDE_SRC_FILE_REGEX re.compile(r'^\s*#\s*include\s*"(src/.+)"')
Definition at line 77 of file fuse_gtest_files.py.
View newest version in sPHENIX GitHub at line 77 of file fuse_gtest_files.py