Analysis Software: PHG4TruthTrackingAction Class Reference
PHG4TruthTrackingAction Class Reference
#include <coresoftware/blob/master/simulation/g4simulation/g4main/PHG4TruthTrackingAction.h>
Classes
struct G4ParticleInfo
Public Member Functions
PHG4TruthTrackingAction (PHG4TruthEventAction *)
constructor
~PHG4TruthTrackingAction () override
destructor
void PreUserTrackingAction (const G4Track *) override
tracking action
void PostUserTrackingAction (const G4Track *) override
void SetInterfacePointers (PHCompositeNode *) override
Set pointers to the i/o nodes.
int ResetEvent (PHCompositeNode *) override
Public Member Functions inherited from PHG4TrackingAction
PHG4TrackingAction (void)
~PHG4TrackingAction () override
void PreUserTrackingAction (const G4Track *) override
void PostUserTrackingAction (const G4Track *) override
Private Member Functions
PHG4Particle * AddParticle (PHG4TruthInfoContainer &, G4Track &)
PHG4VtxPoint * AddVertex (PHG4TruthInfoContainer &, const G4Track &)
Private Attributes
std::map< G4ThreeVector, int > m_VertexMap
PHG4TruthEventAction * m_EventAction
pointer to the "owning" event action
PHG4TruthInfoContainer * m_TruthInfoList
pointer to truth information container
std::vector< G4ParticleInfo > m_G4ParticleStack
G4ParticleInfo m_CurrG4Particle
void UpdateG4ParticleStack (const G4Track *)
Detailed Description
Definition at line 20 of file PHG4TruthTrackingAction.h.
View newest version in sPHENIX GitHub at line 20 of file PHG4TruthTrackingAction.h
Constructor & Destructor Documentation
PHG4TruthTrackingAction::PHG4TruthTrackingAction (PHG4TruthEventAction * eventAction)
constructor
Definition at line 34 of file PHG4TruthTrackingAction.cc.
View newest version in sPHENIX GitHub at line 34 of file PHG4TruthTrackingAction.cc
PHG4TruthTrackingAction::~PHG4TruthTrackingAction () inline override
destructor
Definition at line 27 of file PHG4TruthTrackingAction.h.
View newest version in sPHENIX GitHub at line 27 of file PHG4TruthTrackingAction.h
Member Function Documentation
PHG4Particle * PHG4TruthTrackingAction::AddParticle (PHG4TruthInfoContainer & truth, G4Track & track) private
Definition at line 225 of file PHG4TruthTrackingAction.cc.
View newest version in sPHENIX GitHub at line 225 of file PHG4TruthTrackingAction.cc
References PHG4TruthInfoContainer::AddParticle(), AddVertex(), PHG4VtxPoint::get_id(), Acts::UnitConstants::GeV, mass, PHG4TruthInfoContainer::maxtrkindex(), PHG4TruthInfoContainer::mintrkindex(), PHG4Particle::set_A(), PHG4Particle::set_e(), PHG4Particle::set_name(), PHG4Particle::set_parent_id(), PHG4Particle::set_pid(), PHG4Particle::set_primary_id(), PHG4Particle::set_px(), PHG4Particle::set_py(), PHG4Particle::set_pz(), PHG4Particle::set_track_id(), PHG4Particle::set_vtx_id(), and PHG4Particle::set_Z().
Referenced by PreUserTrackingAction().
PHG4VtxPoint * PHG4TruthTrackingAction::AddVertex (PHG4TruthInfoContainer & truth, const G4Track & track) private
Definition at line 278 of file PHG4TruthTrackingAction.cc.
View newest version in sPHENIX GitHub at line 278 of file PHG4TruthTrackingAction.cc
References PHG4TruthInfoContainer::AddVertex(), Acts::UnitConstants::cm, PHG4TruthInfoContainer::GetVtxMap(), m_VertexMap, PHG4TruthInfoContainer::maxvtxindex(), PHG4TruthInfoContainer::minvtxindex(), Acts::UnitConstants::ns, and testSigmaEff::v.
Referenced by AddParticle().
void PHG4TruthTrackingAction::PostUserTrackingAction (const G4Track * track) override
Definition at line 121 of file PHG4TruthTrackingAction.cc.
View newest version in sPHENIX GitHub at line 121 of file PHG4TruthTrackingAction.cc
References PHG4TruthEventAction::AddTrackidToWritelist(), i, m_EventAction, merge_hashes::p, PHG4TrackUserInfo::SetShower(), PHG4TrackUserInfo::SetUserParentId(), PHG4TrackUserInfo::SetUserPrimaryId(), and UpdateG4ParticleStack().
void PHG4TruthTrackingAction::PreUserTrackingAction (const G4Track * track) override
tracking action
Definition at line 42 of file PHG4TruthTrackingAction.cc.
View newest version in sPHENIX GitHub at line 42 of file PHG4TruthTrackingAction.cc
References AddParticle(), PHG4TruthInfoContainer::AddShower(), PHG4Particle::get_track_id(), PHG4UserPrimaryParticleInformation::get_user_barcode(), PHG4Particle::get_vtx_id(), m_CurrG4Particle, m_TruthInfoList, merge_hashes::p, PHG4Particle::set_barcode(), PHG4Showerv1::set_id(), PHG4Particle::set_parent_id(), PHG4Showerv1::set_parent_particle_id(), PHG4Showerv1::set_parent_shower_id(), PHG4Particle::set_primary_id(), PHG4UserPrimaryParticleInformation::set_user_track_id(), PHG4UserPrimaryParticleInformation::set_user_vtx_id(), PHG4TrackUserInfo::SetShower(), PHG4TrackUserInfo::SetUserPrimaryId(), and PHG4TrackUserInfo::SetUserTrackId().
int PHG4TruthTrackingAction::ResetEvent (PHCompositeNode *) override virtual
Reimplemented from PHG4TrackingAction.
Definition at line 209 of file PHG4TruthTrackingAction.cc.
View newest version in sPHENIX GitHub at line 209 of file PHG4TruthTrackingAction.cc
References PHG4TruthInfoContainer::delete_particle(), m_G4ParticleStack, m_TruthInfoList, and m_VertexMap.
Referenced by PHG4TruthSubsystem::ResetEvent().
void PHG4TruthTrackingAction::SetInterfacePointers (PHCompositeNode * topNode) override virtual
Set pointers to the i/o nodes.
Reimplemented from PHG4TrackingAction.
Definition at line 197 of file PHG4TruthTrackingAction.cc.
View newest version in sPHENIX GitHub at line 197 of file PHG4TruthTrackingAction.cc
References m_TruthInfoList.
Referenced by PHG4TruthSubsystem::process_event().
void PHG4TruthTrackingAction::UpdateG4ParticleStack (const G4Track * track) private
Machinery to keep track of upstream particles while adding Geant4 tracks to the truth info container
Updates the stack of parent particles and removes unwanted ones from the truth info container.
Definition at line 164 of file PHG4TruthTrackingAction.cc.
View newest version in sPHENIX GitHub at line 164 of file PHG4TruthTrackingAction.cc
References PHG4TruthInfoContainer::delete_particle(), PHG4TrackUserInfoV1::GetKeep(), m_CurrG4Particle, m_G4ParticleStack, m_TruthInfoList, and merge_hashes::p.
Referenced by PostUserTrackingAction().
Member Data Documentation
G4ParticleInfo PHG4TruthTrackingAction::m_CurrG4Particle private
Definition at line 58 of file PHG4TruthTrackingAction.h.
View newest version in sPHENIX GitHub at line 58 of file PHG4TruthTrackingAction.h
Referenced by PreUserTrackingAction(), and UpdateG4ParticleStack().
PHG4TruthEventAction* PHG4TruthTrackingAction::m_EventAction private
pointer to the "owning" event action
Definition at line 43 of file PHG4TruthTrackingAction.h.
View newest version in sPHENIX GitHub at line 43 of file PHG4TruthTrackingAction.h
Referenced by PostUserTrackingAction().
std::vector<G4ParticleInfo> PHG4TruthTrackingAction::m_G4ParticleStack private
Definition at line 57 of file PHG4TruthTrackingAction.h.
View newest version in sPHENIX GitHub at line 57 of file PHG4TruthTrackingAction.h
Referenced by ResetEvent(), and UpdateG4ParticleStack().
PHG4TruthInfoContainer* PHG4TruthTrackingAction::m_TruthInfoList private
pointer to truth information container
Definition at line 46 of file PHG4TruthTrackingAction.h.
View newest version in sPHENIX GitHub at line 46 of file PHG4TruthTrackingAction.h
Referenced by PreUserTrackingAction(), ResetEvent(), SetInterfacePointers(), and UpdateG4ParticleStack().
std::map<G4ThreeVector, int> PHG4TruthTrackingAction::m_VertexMap private
Definition at line 40 of file PHG4TruthTrackingAction.h.
View newest version in sPHENIX GitHub at line 40 of file PHG4TruthTrackingAction.h
Referenced by AddVertex(), and ResetEvent().
The documentation for this class was generated from the following files:
coresoftware/blob/master/simulation/g4simulation/g4main/PHG4TruthTrackingAction.h
coresoftware/blob/master/simulation/g4simulation/g4main/PHG4TruthTrackingAction.cc