Analysis Software: MbdOutV1 Class Reference
MbdOutV1 Class Reference
#include <coresoftware/blob/master/offline/packages/mbd/MbdOutV1.h>
Public Member Functions
MbdOutV1 ()
~MbdOutV1 () override
virtual void Reset () override
Clear Event from memory.
void identify (std::ostream &os=std::cout) const override
int isValid () const override
isValid returns non zero if object contains vailid data
Float_t get_zvtx () const override
get ZVertex determined by Mbd
Float_t get_zvtxerr () const override
get Error on ZVertex determined by Mbd
Float_t get_t0 () const override
get T0 determined by Mbd
Float_t get_t0err () const override
get Error on T0 determined by Mbd
void set_t0 (const Float_t t0, const Float_t t0err=0) override
void set_zvtx (const Float_t vtx, const Float_t vtxerr=0) override
set vertex
void set_zvtxerr (const Float_t vtxerr) override
void set_arm (const int iarm, const Short_t npmt, const Float_t chargesum, const Float_t timing) override
Short_t get_npmt (const int iarm) const override
Float_t get_q (const int iarm) const override
Float_t get_time (const int iarm) const override
Public Member Functions inherited from MbdOut
~MbdOut () override
virtual void set_t0zvtx (const Float_t t0, const Float_t t0err, const Float_t vtx, const Float_t vtxerr)
virtual void set_clocks (const Int_t ievt, const UShort_t iclk, const UShort_t ifemclk)
virtual Int_t get_evt () const
virtual UShort_t get_clock () const
virtual UShort_t get_femclock () const
virtual void FillFromClass (const MbdOut &old)
Public Member Functions inherited from PHObject
PHObject ()
ctor
~PHObject () override
dtor
virtual PHObject * CloneMe () const
Virtual copy constructor.
virtual PHObject * clone () const final
PHObject * Clone (const char *newname="") const final
void Copy (TObject &object) const final
virtual int Integrate () const
virtual int Integrate (PHObject *)
virtual void CopyFrom (const PHObject *obj)
Private Attributes
Float_t bz {std::numeric_limits<Float_t>::quiet_NaN()}
Float_t bzerr {std::numeric_limits<Float_t>::quiet_NaN()}
Float_t bt0 {std::numeric_limits<Float_t>::quiet_NaN()}
Float_t bt0err {std::numeric_limits<Float_t>::quiet_NaN()}
Float_t bqs {0}
Float_t bqn {0}
Float_t bts {std::numeric_limits<Float_t>::quiet_NaN()}
Float_t btn {std::numeric_limits<Float_t>::quiet_NaN()}
Short_t bns {0}
Short_t bnn {0}
Detailed Description
Definition at line 14 of file MbdOutV1.h.
View newest version in sPHENIX GitHub at line 14 of file MbdOutV1.h
Constructor & Destructor Documentation
MbdOutV1::MbdOutV1 () default
MbdOutV1::~MbdOutV1 () override default
Member Function Documentation
Short_t MbdOutV1::get_npmt (const int iarm) const override virtual
get Number of PMT's fired in North/South Mbd
Parameters
iarm Arm, use Mbd::North and Mbd::South
Reimplemented from MbdOut.
Definition at line 86 of file MbdOutV1.cc.
View newest version in sPHENIX GitHub at line 86 of file MbdOutV1.cc
References bnn, and bns.
Float_t MbdOutV1::get_q (const int iarm) const override virtual
get Number of Charged Particles into North/South Mbd
Parameters
iarm Arm, use Mbd::North and Mbd::South
Reimplemented from MbdOut.
Definition at line 92 of file MbdOutV1.cc.
View newest version in sPHENIX GitHub at line 92 of file MbdOutV1.cc
References bqn, and bqs.
Float_t MbdOutV1::get_t0 () const inline override virtual
get T0 determined by Mbd
Reimplemented from MbdOut.
Definition at line 40 of file MbdOutV1.h.
View newest version in sPHENIX GitHub at line 40 of file MbdOutV1.h
References bt0.
Float_t MbdOutV1::get_t0err () const inline override virtual
get Error on T0 determined by Mbd
Reimplemented from MbdOut.
Definition at line 43 of file MbdOutV1.h.
View newest version in sPHENIX GitHub at line 43 of file MbdOutV1.h
References bt0err.
Float_t MbdOutV1::get_time (const int iarm) const override virtual
get Timing of North/South Mbd
Parameters
iarm Arm, use Mbd::North and Mbd::South
Reimplemented from MbdOut.
Definition at line 97 of file MbdOutV1.cc.
View newest version in sPHENIX GitHub at line 97 of file MbdOutV1.cc
References btn, and bts.
Float_t MbdOutV1::get_zvtx () const inline override virtual
get ZVertex determined by Mbd
Reimplemented from MbdOut.
Definition at line 34 of file MbdOutV1.h.
View newest version in sPHENIX GitHub at line 34 of file MbdOutV1.h
References bz.
Float_t MbdOutV1::get_zvtxerr () const inline override virtual
get Error on ZVertex determined by Mbd
Reimplemented from MbdOut.
Definition at line 37 of file MbdOutV1.h.
View newest version in sPHENIX GitHub at line 37 of file MbdOutV1.h
References bzerr.
void MbdOutV1::identify (std::ostream & os = std::cout) const override virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from MbdOut.
Definition at line 37 of file MbdOutV1.cc.
View newest version in sPHENIX GitHub at line 37 of file MbdOutV1.cc
References bt0, bt0err, bz, and bzerr.
int MbdOutV1::isValid () const override virtual
isValid returns non zero if object contains vailid data
Reimplemented from MbdOut.
Definition at line 30 of file MbdOutV1.cc.
View newest version in sPHENIX GitHub at line 30 of file MbdOutV1.cc
References bt0.
void MbdOutV1::Reset () override virtual
Clear Event from memory.
Reimplemented from MbdOut.
Definition at line 12 of file MbdOutV1.cc.
View newest version in sPHENIX GitHub at line 12 of file MbdOutV1.cc
References bnn, bns, bqn, bqs, bt0, bt0err, btn, bts, bz, and bzerr.
void MbdOutV1::set_arm (const int iarm, const Short_t npmt, const Float_t chargesum, const Float_t timing) override virtual
Add Mbd North/South data containing Number of pmt's, Energy and Timing
Parameters
npmt Number of PMT's fired
energy Energy in North/South
timing Timing of North/South
iarm Arm, use Mbd::North and Mbd::South
Reimplemented from MbdOut.
Definition at line 65 of file MbdOutV1.cc.
View newest version in sPHENIX GitHub at line 65 of file MbdOutV1.cc
References bnn, bns, bqn, bqs, btn, bts, and charge().
void MbdOutV1::set_t0 (const Float_t t0, const Float_t t0err = 0) override virtual
set T0 for Mbd
Parameters
t0 Mbd T0
t0err Mbd T0 error
Reimplemented from MbdOut.
Definition at line 45 of file MbdOutV1.cc.
View newest version in sPHENIX GitHub at line 45 of file MbdOutV1.cc
References bt0, and bt0err.
void MbdOutV1::set_zvtx (const Float_t vtx, const Float_t vtxerr = 0) override virtual
set vertex
Reimplemented from MbdOut.
Definition at line 52 of file MbdOutV1.cc.
View newest version in sPHENIX GitHub at line 52 of file MbdOutV1.cc
References bz, and bzerr.
void MbdOutV1::set_zvtxerr (const Float_t vtxerr) override virtual
set Vtx Error for Mbd
Parameters
vtxerr Mbd Vtx Error
Reimplemented from MbdOut.
Definition at line 59 of file MbdOutV1.cc.
View newest version in sPHENIX GitHub at line 59 of file MbdOutV1.cc
References bzerr.
Member Data Documentation
Short_t MbdOutV1::bnn {0} private
Definition at line 92 of file MbdOutV1.h.
View newest version in sPHENIX GitHub at line 92 of file MbdOutV1.h
Referenced by get_npmt(), Reset(), and set_arm().
Short_t MbdOutV1::bns {0} private
Definition at line 91 of file MbdOutV1.h.
View newest version in sPHENIX GitHub at line 91 of file MbdOutV1.h
Referenced by get_npmt(), Reset(), and set_arm().
Float_t MbdOutV1::bqn {0} private
Definition at line 88 of file MbdOutV1.h.
View newest version in sPHENIX GitHub at line 88 of file MbdOutV1.h
Referenced by get_q(), Reset(), and set_arm().
Float_t MbdOutV1::bqs {0} private
Definition at line 87 of file MbdOutV1.h.
View newest version in sPHENIX GitHub at line 87 of file MbdOutV1.h
Referenced by get_q(), Reset(), and set_arm().
Float_t MbdOutV1::bt0 {std::numeric_limits<Float_t>::quiet_NaN()} private
Definition at line 85 of file MbdOutV1.h.
View newest version in sPHENIX GitHub at line 85 of file MbdOutV1.h
Referenced by get_t0(), identify(), isValid(), Reset(), and set_t0().
Float_t MbdOutV1::bt0err {std::numeric_limits<Float_t>::quiet_NaN()} private
Definition at line 86 of file MbdOutV1.h.
View newest version in sPHENIX GitHub at line 86 of file MbdOutV1.h
Referenced by get_t0err(), identify(), Reset(), and set_t0().
Float_t MbdOutV1::btn {std::numeric_limits<Float_t>::quiet_NaN()} private
Definition at line 90 of file MbdOutV1.h.
View newest version in sPHENIX GitHub at line 90 of file MbdOutV1.h
Referenced by get_time(), Reset(), and set_arm().
Float_t MbdOutV1::bts {std::numeric_limits<Float_t>::quiet_NaN()} private
Definition at line 89 of file MbdOutV1.h.
View newest version in sPHENIX GitHub at line 89 of file MbdOutV1.h
Referenced by get_time(), Reset(), and set_arm().
Float_t MbdOutV1::bz {std::numeric_limits<Float_t>::quiet_NaN()} private
Definition at line 83 of file MbdOutV1.h.
View newest version in sPHENIX GitHub at line 83 of file MbdOutV1.h
Referenced by get_zvtx(), identify(), Reset(), and set_zvtx().
Float_t MbdOutV1::bzerr {std::numeric_limits<Float_t>::quiet_NaN()} private
Definition at line 84 of file MbdOutV1.h.
View newest version in sPHENIX GitHub at line 84 of file MbdOutV1.h
Referenced by get_zvtxerr(), identify(), Reset(), set_zvtx(), and set_zvtxerr().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/mbd/MbdOutV1.h
coresoftware/blob/master/offline/packages/mbd/MbdOutV1.cc