Analysis Software: RecoPV_optimization Namespace Reference
RecoPV_optimization Namespace Reference
Functions
def Draw_1Dhist_wTF1
def Draw2Dhisttable
def doFitSaveFitresult
def main
def get2DTable
Variables
float TickSize 0.03
float AxisTitleSize 0.05
float AxisLabelSize 0.04
float LeftMargin 0.15
float RightMargin 0.08
float TopMargin 0.08
float BottomMargin 0.13
tuple parser OptionParser(usage="usage: %prog ver [options -h]")
infiledir opt.infiledir
outdirprefix opt.outdirprefix
dofit opt.dofit
tuple nbinsdphi int(opt.nbinsdphi)
tuple nbinsdca int(opt.nbinsdca)
string plotpath './RecoPV_optimization/'
float dphiinterval 0.1
float dcainterval 0.025
tuple dphicut_deg dphiinterval*(i+1)
tuple dphicut_rad dphicut_deg*(np.pi / 180.)
tuple dcacut dcainterval*(j+1)
string dphitext '{:.3f}'
string dcadtext '{:.3f}'
string outpath './RecoPV_optimization/{}/dPhi{}deg_dca{}cm/'
list sigmainfo df_opt.iloc[i]
Function Documentation
def RecoPV_optimization.doFitSaveFitresult (reshist, resdata, fitresname, histwTF1name)
Definition at line 175 of file RecoPV_optimization.py.
View newest version in sPHENIX GitHub at line 175 of file RecoPV_optimization.py
References Draw_1Dhist_wTF1().
Referenced by main().
def RecoPV_optimization.Draw2Dhisttable (hist, XaxisName, YaxisName, ZaxisName, DrawOpt, outname)
Definition at line 131 of file RecoPV_optimization.py.
View newest version in sPHENIX GitHub at line 131 of file RecoPV_optimization.py
References if(), and SetTitle().
def RecoPV_optimization.Draw_1Dhist_wTF1 (hist, histdata, norm1, logy, ymaxscale, XaxisName, Ytitle_unit, outname)
Definition at line 31 of file RecoPV_optimization.py.
View newest version in sPHENIX GitHub at line 31 of file RecoPV_optimization.py
References material_mapping_optimisation.format, if(), sigmaEff.minimum_size_range(), and SetTitle().
Referenced by doFitSaveFitresult().
def RecoPV_optimization.get2DTable (fitresdir)
Definition at line 213 of file RecoPV_optimization.py.
View newest version in sPHENIX GitHub at line 213 of file RecoPV_optimization.py
References material_mapping_optimisation.format, print(), and Acts.zip().
def RecoPV_optimization.main (dphitxt, dcatxt, infiledir, outfiledir)
Definition at line 193 of file RecoPV_optimization.py.
View newest version in sPHENIX GitHub at line 193 of file RecoPV_optimization.py
References doFitSaveFitresult(), plotUtil.Draw_2Dhist(), Acts.enumerate(), and material_mapping_optimisation.format.
Variable Documentation
float RecoPV_optimization.AxisLabelSize 0.04
Definition at line 22 of file RecoPV_optimization.py.
View newest version in sPHENIX GitHub at line 22 of file RecoPV_optimization.py
float RecoPV_optimization.AxisTitleSize 0.05
Definition at line 21 of file RecoPV_optimization.py.
View newest version in sPHENIX GitHub at line 21 of file RecoPV_optimization.py
float RecoPV_optimization.BottomMargin 0.13
Definition at line 26 of file RecoPV_optimization.py.
View newest version in sPHENIX GitHub at line 26 of file RecoPV_optimization.py
tuple RecoPV_optimization.dcacut dcainterval*(j+1)
Definition at line 279 of file RecoPV_optimization.py.
View newest version in sPHENIX GitHub at line 279 of file RecoPV_optimization.py
string RecoPV_optimization.dcadtext '{:.3f}'
Definition at line 281 of file RecoPV_optimization.py.
View newest version in sPHENIX GitHub at line 281 of file RecoPV_optimization.py
float RecoPV_optimization.dcainterval 0.025
Definition at line 273 of file RecoPV_optimization.py.
View newest version in sPHENIX GitHub at line 273 of file RecoPV_optimization.py
RecoPV_optimization.dofit opt.dofit
Definition at line 265 of file RecoPV_optimization.py.
View newest version in sPHENIX GitHub at line 265 of file RecoPV_optimization.py
tuple RecoPV_optimization.dphicut_deg dphiinterval*(i+1)
Definition at line 277 of file RecoPV_optimization.py.
View newest version in sPHENIX GitHub at line 277 of file RecoPV_optimization.py
tuple RecoPV_optimization.dphicut_rad dphicut_deg*(np.pi / 180.)
Definition at line 278 of file RecoPV_optimization.py.
View newest version in sPHENIX GitHub at line 278 of file RecoPV_optimization.py
float RecoPV_optimization.dphiinterval 0.1
Definition at line 272 of file RecoPV_optimization.py.
View newest version in sPHENIX GitHub at line 272 of file RecoPV_optimization.py
string RecoPV_optimization.dphitext '{:.3f}'
Definition at line 280 of file RecoPV_optimization.py.
View newest version in sPHENIX GitHub at line 280 of file RecoPV_optimization.py
RecoPV_optimization.infiledir opt.infiledir
Definition at line 263 of file RecoPV_optimization.py.
View newest version in sPHENIX GitHub at line 263 of file RecoPV_optimization.py
float RecoPV_optimization.LeftMargin 0.15
Definition at line 23 of file RecoPV_optimization.py.
View newest version in sPHENIX GitHub at line 23 of file RecoPV_optimization.py
tuple RecoPV_optimization.nbinsdca int(opt.nbinsdca)
Definition at line 267 of file RecoPV_optimization.py.
View newest version in sPHENIX GitHub at line 267 of file RecoPV_optimization.py
tuple RecoPV_optimization.nbinsdphi int(opt.nbinsdphi)
Definition at line 266 of file RecoPV_optimization.py.
View newest version in sPHENIX GitHub at line 266 of file RecoPV_optimization.py
RecoPV_optimization.outdirprefix opt.outdirprefix
Definition at line 264 of file RecoPV_optimization.py.
View newest version in sPHENIX GitHub at line 264 of file RecoPV_optimization.py
string RecoPV_optimization.outpath './RecoPV_optimization/{}/dPhi{}deg_dca{}cm/'
Definition at line 283 of file RecoPV_optimization.py.
View newest version in sPHENIX GitHub at line 283 of file RecoPV_optimization.py
tuple RecoPV_optimization.parser OptionParser(usage="usage: %prog ver [options -h]")
Definition at line 253 of file RecoPV_optimization.py.
View newest version in sPHENIX GitHub at line 253 of file RecoPV_optimization.py
string RecoPV_optimization.plotpath './RecoPV_optimization/'
Definition at line 269 of file RecoPV_optimization.py.
View newest version in sPHENIX GitHub at line 269 of file RecoPV_optimization.py
float RecoPV_optimization.RightMargin 0.08
Definition at line 24 of file RecoPV_optimization.py.
View newest version in sPHENIX GitHub at line 24 of file RecoPV_optimization.py
list RecoPV_optimization.sigmainfo df_opt.iloc[i]
Definition at line 305 of file RecoPV_optimization.py.
View newest version in sPHENIX GitHub at line 305 of file RecoPV_optimization.py
float RecoPV_optimization.TickSize 0.03
Definition at line 20 of file RecoPV_optimization.py.
View newest version in sPHENIX GitHub at line 20 of file RecoPV_optimization.py
float RecoPV_optimization.TopMargin 0.08
Definition at line 25 of file RecoPV_optimization.py.
View newest version in sPHENIX GitHub at line 25 of file RecoPV_optimization.py