Analysis Software: acts/blob/sPHENIX/Examples/Io/Root/src/RootMaterialDecorator.cpp File Reference
RootMaterialDecorator.cpp File Reference
#include "ActsExamples/Io/Root/RootMaterialDecorator.hpp"
#include "Acts/Definitions/Algebra.hpp"
#include "Acts/Material/InterpolatedMaterialMap.hpp"
#include "Acts/Material/Material.hpp"
#include "Acts/Material/MaterialGridHelper.hpp"
#include "Acts/Material/MaterialSlab.hpp"
#include "Acts/Utilities/Logger.hpp"
#include "Acts/Utilities/detail/Grid.hpp"
#include <Acts/Geometry/GeometryIdentifier.hpp>
#include <Acts/Material/BinnedSurfaceMaterial.hpp>
#include <Acts/Material/HomogeneousSurfaceMaterial.hpp>
#include <Acts/Material/HomogeneousVolumeMaterial.hpp>
#include <Acts/Utilities/BinUtility.hpp>
#include <Acts/Utilities/BinningType.hpp>
#include <algorithm>
#include <cstdio>
#include <functional>
#include <iostream>
#include <stdexcept>
#include <string>
#include <tuple>
#include <vector>
#include <TFile.h>
#include <TH1.h>
#include <TH2.h>
#include <TIterator.h>
#include <TKey.h>
#include <TList.h>
#include <TObject.h>
#include <boost/algorithm/string.hpp>
#include <boost/algorithm/string/finder.hpp>
#include <boost/algorithm/string/iter_find.hpp>
Namespaces
namespace Acts
Acts includes to create all necessary definitions.
Functions
if (m_inputFile==nullptr)
tIter Reset ()
while (TKey *key=(TKey *)(tIter->Next()))
Variables
TList * tlist = m_inputFile->GetListOfKeys()
auto tIter = tlist->MakeIterator()
Function Documentation
if (m_inputFile = = nullptr)
Definition at line 66 of file RootMaterialDecorator.cpp.
View newest version in sPHENIX GitHub at line 66 of file RootMaterialDecorator.cpp
References m_cfg().
Referenced by TPC_Cluster_Drift_Animator::animate_scatters(), TPC_Cluster_Drift_Animator_beam::animate_scatters(), RecoPV_optimization::Draw2Dhisttable(), INTTVtxZ::Draw_1DEff(), INTTVtxZ::Draw_1DEffComp(), plotUtil::Draw_1Dhist(), plot_DataSimComp::Draw_1Dhist_datasimcomp(), plot_DataSimComp::Draw_1Dhist_datasimcomp_v2(), INTTVtxZ::Draw_1Dhist_fitGaussian(), centProxy::Draw_1Dhist_wPercentile(), RecoPV_optimization::Draw_1Dhist_wTF1(), plotUtil::Draw_1DhistsComp(), plotUtil::Draw_2Dhist(), plot_DataSimComp::Draw_2Dhist_datasimcomp(), INTTVtxZ::Draw_2Dhist_eff(), centProxy::Draw_2Dhist_wPercentile(), INTTVtxZ::Draw_HistGraph(), utils::event_display(), oncsEvent::existPacket(), oncsSubevent_w1::gdump(), oncsSubevent_w2::gdump(), utils::get_status(), utils::hadd(), ActsFatras::detail::SimulationActor< generator_t, decay_t, interactions_t, hit_surface_selector_t >::interact(), Jetscape::PartonShower::load_edge_info_handler(), Jetscape::PartonShower::load_node_info_handler(), lushow(), MD5_Update(), mg_mqtt_next_subscribe_topic(), mg_normalize_uri_path(), mg_resolve_async_eh(), mg_sock_addr_to_str(), oncsSub_idmvtxv0::mvtx_decode(), plotUtil::plot_Stack(), InttCombinedRawDataConverter::process_event(), DetermineTowerBackground::process_event(), pythrg(), TPC_Cluster_Drift_Animator::read_cluster_pos(), TPC_Cluster_Drift_Animator_beam::read_cluster_pos(), utils::run_analysis(), set_week_number_mon4(), TPC_Cluster_Drift_Animator::theLoop(), TPC_Cluster_Drift_Animator_beam::theLoop(), and simpleRandom::xMD5Final().
tIter Reset ()
Referenced by SDeltaPtCutStudy::CalculateEfficiencies(), ClassImp(), PhotonPair::Clear(), EMCalTrk::Clear(), MCPhoton::Clear(), CompareOldVsNewPlots(), DoPercentDifference(), MakePrettyPlot(), MakeRatioComparisonPlot(), STrackMatcherComparator::MakeRatiosAndPlots(), and QuickDeltaPtExtractor().
while (TKey * key = (TKey*)(tIter->Next()))
Definition at line 76 of file RootMaterialDecorator.cpp.
View newest version in sPHENIX GitHub at line 76 of file RootMaterialDecorator.cpp
References A, ACTS_ERROR, ACTS_VERBOSE, Acts::detail::Grid< T, Axes >::at(), Acts::createGrid2D(), Acts::createGrid3D(), Acts::Test::dim, dz, Acts::Material::fromMassDensity(), grid(), add_histos::hist, add_histos_bX::ib, m_cfg(), Acts::m_surfaceMaterialMap, Acts::m_volumeMaterialMap, std::tr1::make_tuple(), material, Acts::detail::Grid< T, Axes >::maxPosition(), Acts::UnitConstants::min, Acts::detail::Grid< T, Axes >::minPosition(), testing::internal::move(), n, nbins, Acts::detail::Grid< T, Axes >::numLocalBins(), merge_hashes::p, Acts::Material::parameters(), rho, Acts::GeometryIdentifier::setApproach(), Acts::GeometryIdentifier::setBoundary(), Acts::GeometryIdentifier::setLayer(), Acts::GeometryIdentifier::setSensitive(), Acts::GeometryIdentifier::setVolume(), t, testSigmaEff::v, x0, and SVM_v1::Z.
Referenced by oncsSub_idinttv0::intt_decode(), daq_device_filenumbers::put_data(), oncsSub_idtpcfeev2::tpc_decode(), and oncsSub_idtpcfeev3::tpc_decode().
Variable Documentation
auto tIter = tlist->MakeIterator()
Definition at line 72 of file RootMaterialDecorator.cpp.
View newest version in sPHENIX GitHub at line 72 of file RootMaterialDecorator.cpp
TList* tlist = m_inputFile->GetListOfKeys()
Definition at line 71 of file RootMaterialDecorator.cpp.
View newest version in sPHENIX GitHub at line 71 of file RootMaterialDecorator.cpp
Referenced by PHG4InEvent::AddVtxCommon().