Analysis Software: ActsExamples::EDM4hepSimHitWriter Exception Reference
ActsExamples::EDM4hepSimHitWriter Exception Reference final
#include <acts/blob/sPHENIX/Examples/Io/EDM4hep/include/ActsExamples/Io/EDM4hep/EDM4hepSimHitWriter.hpp>
Classes
struct Config
Public Member Functions
EDM4hepSimHitWriter (const Config &config, Acts::Logging::Level level)
ProcessCode finalize () final
Finalize the algorithm.
const Config & config () const
Readonly access to the config.
Public Member Functions inherited from ActsExamples::WriterT< SimHitContainer >
WriterT (std::string objectName, std::string writerName, Acts::Logging::Level level)
std::string name () const override
Provide the name of the writer.
ProcessCode write (const AlgorithmContext &context) override
Read the object and call the type-specific member function.
ProcessCode finalize () override
No-op default implementation.
Public Member Functions inherited from ActsExamples::IWriter
ProcessCode internalExecute (const AlgorithmContext &context) final
ProcessCode initialize () override
Fulfil the algorithm interface.
Public Member Functions inherited from ActsExamples::SequenceElement
virtual ~SequenceElement ()=default
const std::vector< const
DataHandleBase * > & writeHandles () const
const std::vector< const
DataHandleBase * > & readHandles () const
Protected Member Functions
ProcessCode writeT (const AlgorithmContext &ctx, const SimHitContainer &simHits) final
Protected Member Functions inherited from ActsExamples::WriterT< SimHitContainer >
const Acts::Logger & logger () const
Private Attributes
Config m_cfg
podio::ROOTFrameWriter m_writer
ReadDataHandle
< SimParticleContainer > m_inputParticles {this, "InputParticles"}
Detailed Description
Write out a simhit collection to EDM4hep.
Inpersistent information:
particle ID
after4 momentum
hit index
digitization channel
Definition at line 31 of file EDM4hepSimHitWriter.hpp.
View newest version in sPHENIX GitHub at line 31 of file EDM4hepSimHitWriter.hpp
Constructor & Destructor Documentation
ActsExamples::EDM4hepSimHitWriter::EDM4hepSimHitWriter (const Config & config, Acts::Logging::Level level)
Construct the cluster writer.
Parameters
config is the configuration object
level is the logging level
Definition at line 25 of file EDM4hepSimHitWriter.cpp.
View newest version in sPHENIX GitHub at line 25 of file EDM4hepSimHitWriter.cpp
References ACTS_VERBOSE, ActsExamples::EDM4hepSimHitWriter::Config::inputParticles, ActsExamples::EDM4hepSimHitWriter::Config::inputSimHits, m_cfg, m_inputParticles, ActsExamples::DataHandleBase::maybeInitialize(), ActsExamples::EDM4hepSimHitWriter::Config::outputParticles, ActsExamples::EDM4hepSimHitWriter::Config::outputPath, and ActsExamples::EDM4hepSimHitWriter::Config::outputSimTrackerHits.
Member Function Documentation
const Config& ActsExamples::EDM4hepSimHitWriter::config () const inline
Readonly access to the config.
Definition at line 55 of file EDM4hepSimHitWriter.hpp.
View newest version in sPHENIX GitHub at line 55 of file EDM4hepSimHitWriter.hpp
References m_cfg.
ActsExamples::ProcessCode ActsExamples::EDM4hepSimHitWriter::finalize () final virtual
Finalize the algorithm.
Implements ActsExamples::SequenceElement.
Definition at line 47 of file EDM4hepSimHitWriter.cpp.
View newest version in sPHENIX GitHub at line 47 of file EDM4hepSimHitWriter.cpp
References m_writer, and SUCCESS.
ProcessCode ActsExamples::EDM4hepSimHitWriter::writeT (const AlgorithmContext & ctx, const SimHitContainer & simHits) final protected virtual
Type-specific write implementation.
Parameters
[in] ctx is the algorithm context
[in] simHits are the simhits to be written
Implements ActsExamples::WriterT< SimHitContainer >.
Definition at line 53 of file EDM4hepSimHitWriter.cpp.
View newest version in sPHENIX GitHub at line 53 of file EDM4hepSimHitWriter.cpp
References ActsExamples::EDM4hepSimHitWriter::Config::inputParticles, it, m_cfg, m_inputParticles, m_writer, testing::internal::move(), ActsExamples::EDM4hepSimHitWriter::Config::outputParticles, ActsExamples::EDM4hepSimHitWriter::Config::outputSimTrackerHits, merge_hashes::p, particle, particles, SUCCESS, ActsExamples::EDM4hepUtil::writeParticle(), and ActsExamples::EDM4hepUtil::writeSimHit().
Member Data Documentation
Config ActsExamples::EDM4hepSimHitWriter::m_cfg private
Definition at line 66 of file EDM4hepSimHitWriter.hpp.
View newest version in sPHENIX GitHub at line 66 of file EDM4hepSimHitWriter.hpp
Referenced by config(), EDM4hepSimHitWriter(), and writeT().
ReadDataHandle<SimParticleContainer> ActsExamples::EDM4hepSimHitWriter::m_inputParticles {this, "InputParticles"} private
Definition at line 70 of file EDM4hepSimHitWriter.hpp.
View newest version in sPHENIX GitHub at line 70 of file EDM4hepSimHitWriter.hpp
Referenced by EDM4hepSimHitWriter(), and writeT().
podio::ROOTFrameWriter ActsExamples::EDM4hepSimHitWriter::m_writer private
Definition at line 68 of file EDM4hepSimHitWriter.hpp.
View newest version in sPHENIX GitHub at line 68 of file EDM4hepSimHitWriter.hpp
Referenced by finalize(), and writeT().
The documentation for this exception was generated from the following files:
acts/blob/sPHENIX/Examples/Io/EDM4hep/include/ActsExamples/Io/EDM4hep/EDM4hepSimHitWriter.hpp
acts/blob/sPHENIX/Examples/Io/EDM4hep/src/EDM4hepSimHitWriter.cpp