Analysis Software: OnlMonDraw Class Reference
OnlMonDraw Class Reference
#include <OnlMon/blob/main/onlmonclient/OnlMonDraw.h>
Public Member Functions
OnlMonDraw (const std::string &name="NONE")
virtual ~OnlMonDraw ()
virtual int Init ()
virtual int Draw (const std::string &what="ALL")
virtual int SavePlot (const std::string &what="ALL", const std::string &type="png")
virtual int MakePS (const std::string &what="ALL")
virtual int MakeHtml (const std::string &what="ALL")
const std::string Name () const
void Verbosity (const int i)
int Verbosity () const
Protected Member Functions
virtual int DrawDeadServer (TPad *transparent)
Protected Attributes
std::string ThisName
int verbosity = 0
Detailed Description
Definition at line 8 of file OnlMonDraw.h.
View newest version in sPHENIX GitHub at line 8 of file OnlMonDraw.h
Constructor & Destructor Documentation
OnlMonDraw::OnlMonDraw (const std::string & name = "NONE")
Definition at line 8 of file OnlMonDraw.cc.
View newest version in sPHENIX GitHub at line 8 of file OnlMonDraw.cc
virtual OnlMonDraw::~OnlMonDraw () inline virtual
Definition at line 12 of file OnlMonDraw.h.
View newest version in sPHENIX GitHub at line 12 of file OnlMonDraw.h
Member Function Documentation
int OnlMonDraw::Draw (const std::string & what = "ALL") virtual
Reimplemented in InttMonDraw, BbcMonDraw, TpotMonDraw, MvtxMonDraw, PktSizeMonDraw, HcalMonDraw, SepdMonDraw, CemcMonDraw, TpcMonDraw, DaqMonDraw, ZdcMonDraw, MyMonDraw, and LL1MonDraw.
Definition at line 13 of file OnlMonDraw.cc.
View newest version in sPHENIX GitHub at line 13 of file OnlMonDraw.cc
int OnlMonDraw::DrawDeadServer (TPad * transparent) protected virtual
Reimplemented in BbcMonDraw, and TpotMonDraw.
Definition at line 37 of file OnlMonDraw.cc.
View newest version in sPHENIX GitHub at line 37 of file OnlMonDraw.cc
References Name().
Referenced by TpotMonDraw::DrawDeadServer(), SepdMonDraw::DrawFifth(), HcalMonDraw::DrawFifth(), MyMonDraw::DrawFirst(), LL1MonDraw::DrawFirst(), DaqMonDraw::DrawFirst(), ZdcMonDraw::DrawFirst(), TpcMonDraw::DrawFirst(), CemcMonDraw::DrawFirst(), SepdMonDraw::DrawFirst(), HcalMonDraw::DrawFirst(), PktSizeMonDraw::DrawFirst(), CemcMonDraw::DrawFourth(), SepdMonDraw::DrawFourth(), HcalMonDraw::DrawFourth(), PktSizeMonDraw::DrawHistory(), HcalMonDraw::DrawHitMap(), PktSizeMonDraw::DrawOldFirst(), MyMonDraw::DrawSecond(), LL1MonDraw::DrawSecond(), ZdcMonDraw::DrawSecond(), DaqMonDraw::DrawSecond(), TpcMonDraw::DrawSecond(), SepdMonDraw::DrawSecond(), CemcMonDraw::DrawSecond(), HcalMonDraw::DrawSecond(), LL1MonDraw::DrawThird(), CemcMonDraw::DrawThird(), SepdMonDraw::DrawThird(), HcalMonDraw::DrawThird(), HcalMonDraw::DrawTowerAvg(), and HcalMonDraw::HandleEvent().
virtual int OnlMonDraw::Init () inline virtual
Reimplemented in InttMonDraw, BbcMonDraw, TpotMonDraw, MvtxMonDraw, PktSizeMonDraw, HcalMonDraw, SepdMonDraw, CemcMonDraw, TpcMonDraw, DaqMonDraw, ZdcMonDraw, MyMonDraw, and LL1MonDraw.
Definition at line 14 of file OnlMonDraw.h.
View newest version in sPHENIX GitHub at line 14 of file OnlMonDraw.h
Referenced by inttDrawInit(), and OnlMonClient::registerDrawer().
int OnlMonDraw::MakeHtml (const std::string & what = "ALL") virtual
Reimplemented in InttMonDraw, BbcMonDraw, TpotMonDraw, MvtxMonDraw, PktSizeMonDraw, HcalMonDraw, SepdMonDraw, CemcMonDraw, TpcMonDraw, DaqMonDraw, ZdcMonDraw, MyMonDraw, and LL1MonDraw.
Definition at line 31 of file OnlMonDraw.cc.
View newest version in sPHENIX GitHub at line 31 of file OnlMonDraw.cc
int OnlMonDraw::MakePS (const std::string & what = "ALL") virtual
Definition at line 25 of file OnlMonDraw.cc.
View newest version in sPHENIX GitHub at line 25 of file OnlMonDraw.cc
const std::string OnlMonDraw::Name () const inline
Definition at line 19 of file OnlMonDraw.h.
View newest version in sPHENIX GitHub at line 19 of file OnlMonDraw.h
References ThisName.
Referenced by DrawDeadServer(), OnlMonClient::htmlAddMenu(), OnlMonClient::htmlNamer(), OnlMonClient::htmlRegisterPage(), OnlMonClient::registerDrawer(), and OnlMonClient::SaveLogFile().
int OnlMonDraw::SavePlot (const std::string & what = "ALL", const std::string & type = "png") virtual
Reimplemented in InttMonDraw, BbcMonDraw, TpotMonDraw, MvtxMonDraw, PktSizeMonDraw, HcalMonDraw, SepdMonDraw, CemcMonDraw, TpcMonDraw, DaqMonDraw, ZdcMonDraw, MyMonDraw, and LL1MonDraw.
Definition at line 19 of file OnlMonDraw.cc.
View newest version in sPHENIX GitHub at line 19 of file OnlMonDraw.cc
void OnlMonDraw::Verbosity (const int i) inline
Definition at line 20 of file OnlMonDraw.h.
View newest version in sPHENIX GitHub at line 20 of file OnlMonDraw.h
References i, and verbosity.
int OnlMonDraw::Verbosity () const inline
Definition at line 21 of file OnlMonDraw.h.
View newest version in sPHENIX GitHub at line 21 of file OnlMonDraw.h
References verbosity.
Referenced by TpotMonDraw::create_canvas(), TpotMonDraw::Draw(), TpotMonDraw::draw_array(), TpotMonDraw::draw_counters(), TpotMonDraw::draw_detector_occupancy(), TpotMonDraw::draw_resist_occupancy(), TpotMonDraw::draw_time(), TpotMonDraw::DrawDeadServer(), TpotMonDraw::get_histograms(), and TpotMonDraw::get_ref_histograms().
Member Data Documentation
std::string OnlMonDraw::ThisName protected
Definition at line 25 of file OnlMonDraw.h.
View newest version in sPHENIX GitHub at line 25 of file OnlMonDraw.h
Referenced by DaqMonDraw::DaqMonDraw(), TpotMonDraw::draw_time(), HcalMonDraw::DrawFifth(), MyMonDraw::DrawFirst(), LL1MonDraw::DrawFirst(), DaqMonDraw::DrawFirst(), ZdcMonDraw::DrawFirst(), TpcMonDraw::DrawFirst(), SepdMonDraw::DrawFirst(), HcalMonDraw::DrawFirst(), BbcMonDraw::DrawFirst(), SepdMonDraw::DrawFourth(), LL1MonDraw::DrawSecond(), MyMonDraw::DrawSecond(), DaqMonDraw::DrawSecond(), ZdcMonDraw::DrawSecond(), TpcMonDraw::DrawSecond(), SepdMonDraw::DrawSecond(), HcalMonDraw::DrawSecond(), BbcMonDraw::DrawSecond(), LL1MonDraw::DrawThird(), SepdMonDraw::DrawThird(), HcalMonDraw::DrawThird(), TpcMonDraw::DrawTPCADCSample(), TpcMonDraw::DrawTPCADCSampleLarge(), TpcMonDraw::DrawTPCchannelphi_layer_weighted(), TpcMonDraw::DrawTPCCheckSum(), TpcMonDraw::DrawTPCMaxADC1D(), TpcMonDraw::DrawTPCMaxADCModule(), TpcMonDraw::DrawTPCModules(), TpcMonDraw::DrawTPCPedestSubADC1D(), TpcMonDraw::DrawTPCRawADC1D(), TpcMonDraw::DrawTPCSampleSize(), TpcMonDraw::DrawTPCXYclusters(), TpcMonDraw::DrawTPCXYclusters_unweighted(), TpcMonDraw::DrawTPCZYclusters(), TpcMonDraw::DrawTPCZYclusters_unweighted(), HcalMonDraw::HcalMonDraw(), PktSizeMonDraw::Init(), MyMonDraw::MyMonDraw(), Name(), MvtxMonDraw::PublishStatistics(), MyMonDraw::SavePlot(), LL1MonDraw::SavePlot(), DaqMonDraw::SavePlot(), ZdcMonDraw::SavePlot(), TpcMonDraw::SavePlot(), CemcMonDraw::SavePlot(), HcalMonDraw::SavePlot(), SepdMonDraw::SavePlot(), PktSizeMonDraw::SavePlot(), MvtxMonDraw::SavePlot(), TpotMonDraw::SavePlot(), BbcMonDraw::SavePlot(), InttMonDraw::SavePlot(), and TpotMonDraw::TpotMonDraw().
int OnlMonDraw::verbosity = 0 protected
Definition at line 26 of file OnlMonDraw.h.
View newest version in sPHENIX GitHub at line 26 of file OnlMonDraw.h
Referenced by PktSizeMonDraw::CleanOldRuns(), PktSizeMonDraw::MakeNoisyCandidates(), and Verbosity().
The documentation for this class was generated from the following files:
OnlMon/blob/main/onlmonclient/OnlMonDraw.h
OnlMon/blob/main/onlmonclient/OnlMonDraw.cc