Analysis Software: JetContainer Class Reference
JetContainer Class Reference
#include <coresoftware/blob/master/offline/packages/jetbase/JetContainer.h>
Public Types
typedef std::set< Jet::SRC >
::const_iterator ConstSrcIter
typedef std::set< Jet::SRC >
::iterator SrcIter
Public Member Functions
JetContainer ()=default
~JetContainer () override=default
virtual void identify (std::ostream &) const override
int isValid () const override
isValid returns non zero if object contains vailid data
PHObject * CloneMe () const override
Virtual copy constructor.
virtual TClonesArray * clone_data () const
virtual bool empty () const
virtual size_t size () const
virtual Jet * add_jet ()
virtual Jet * get_jet (unsigned int)
virtual Jet * get_UncheckedAt (unsigned int)
virtual Jet * operator() (int)
virtual Jet * operator[] (int)
virtual void set_algo (Jet::ALGO)
virtual Jet::ALGO get_algo () const
virtual void set_par (float)
virtual float get_par () const
virtual void set_jetpar_R (float)
virtual float get_jetpar_R () const
virtual bool empty_src () const
virtual void insert_src (Jet::SRC)
virtual ConstSrcIter begin_src () const
virtual ConstSrcIter find_src (Jet::SRC src) const
virtual ConstSrcIter end_src () const
virtual SrcIter begin_src ()
virtual SrcIter find_src (Jet::SRC src)
virtual SrcIter end_src ()
virtual std::map
< Jet::PROPERTY, Jet::PROPERTY > property_indices () const
virtual bool has_property (Jet::PROPERTY) const
virtual size_t size_properties () const
virtual size_t add_property (Jet::PROPERTY)
virtual size_t add_property (std::set< Jet::PROPERTY >)
virtual Jet::PROPERTY property_index (Jet::PROPERTY)
virtual void print_property_types (std::ostream &) const
virtual void print_jets (std::ostream &os=std::cout)
virtual Jet::IterJetTCA begin ()
virtual Jet::IterJetTCA end ()
virtual unsigned int get_index_single () const
virtual std::vector< unsigned int > get_index_vec () const
virtual void set_rho_median (float)
virtual float get_rho_median () const
Public Member Functions inherited from PHObject
PHObject ()
ctor
~PHObject () override
dtor
virtual PHObject * clone () const final
PHObject * Clone (const char *newname="") const final
void Copy (TObject &object) const final
virtual void Reset ()
Clear Event.
virtual int Integrate () const
virtual int Integrate (PHObject *)
virtual void CopyFrom (const PHObject *obj)
Private Member Functions
ClassDefOverride (JetContainer, 1)
Detailed Description
Definition at line 25 of file JetContainer.h.
View newest version in sPHENIX GitHub at line 25 of file JetContainer.h
Member Typedef Documentation
typedef std::set<Jet::SRC>::const_iterator JetContainer::ConstSrcIter
Definition at line 68 of file JetContainer.h.
View newest version in sPHENIX GitHub at line 68 of file JetContainer.h
typedef std::set<Jet::SRC>::iterator JetContainer::SrcIter
Definition at line 69 of file JetContainer.h.
View newest version in sPHENIX GitHub at line 69 of file JetContainer.h
Constructor & Destructor Documentation
JetContainer::JetContainer () default
JetContainer::~JetContainer () override default
Member Function Documentation
virtual Jet* JetContainer::add_jet () inline virtual
Reimplemented in JetContainerv1.
Definition at line 41 of file JetContainer.h.
View newest version in sPHENIX GitHub at line 41 of file JetContainer.h
Referenced by FastJetAlgoSub::cluster_and_fill(), FastJetAlgo::cluster_and_fill(), JetProbeMaker::process_event(), CopyAndSubtractJets::process_event(), and JetHepMCLoader::process_event().
virtual size_t JetContainer::add_property (Jet::PROPERTY) inline virtual
Reimplemented in JetContainerv1.
Definition at line 95 of file JetContainer.h.
View newest version in sPHENIX GitHub at line 95 of file JetContainer.h
Referenced by FastJetAlgo::first_call_init().
virtual size_t JetContainer::add_property (std::set< Jet::PROPERTY >) inline virtual
Reimplemented in JetContainerv1.
Definition at line 96 of file JetContainer.h.
View newest version in sPHENIX GitHub at line 96 of file JetContainer.h
Jet::IterJetTCA JetContainer::begin (void) virtual
Reimplemented in JetContainerv1.
Definition at line 62 of file JetContainer.cc.
View newest version in sPHENIX GitHub at line 62 of file JetContainer.cc
References DummyIterJetTCA.
JetContainer::ConstSrcIter JetContainer::begin_src () const virtual
Reimplemented in JetContainerv1.
Definition at line 16 of file JetContainer.cc.
View newest version in sPHENIX GitHub at line 16 of file JetContainer.cc
JetContainer::SrcIter JetContainer::begin_src () virtual
Reimplemented in JetContainerv1.
Definition at line 31 of file JetContainer.cc.
View newest version in sPHENIX GitHub at line 31 of file JetContainer.cc
JetContainer::ClassDefOverride (JetContainer , 1) private
TClonesArray * JetContainer::clone_data () const virtual
Reimplemented in JetContainerv1.
Definition at line 51 of file JetContainer.cc.
View newest version in sPHENIX GitHub at line 51 of file JetContainer.cc
References DummyTClonesArray().
PHObject* JetContainer::CloneMe () const inline override virtual
Virtual copy constructor.
Reimplemented from PHObject.
Definition at line 32 of file JetContainer.h.
View newest version in sPHENIX GitHub at line 32 of file JetContainer.h
virtual bool JetContainer::empty () const inline virtual
Reimplemented in JetContainerv1.
Definition at line 36 of file JetContainer.h.
View newest version in sPHENIX GitHub at line 36 of file JetContainer.h
virtual bool JetContainer::empty_src () const inline virtual
Reimplemented in JetContainerv1.
Definition at line 71 of file JetContainer.h.
View newest version in sPHENIX GitHub at line 71 of file JetContainer.h
Jet::IterJetTCA JetContainer::end (void) virtual
Reimplemented in JetContainerv1.
Definition at line 67 of file JetContainer.cc.
View newest version in sPHENIX GitHub at line 67 of file JetContainer.cc
References DummyIterJetTCA.
JetContainer::ConstSrcIter JetContainer::end_src () const virtual
Reimplemented in JetContainerv1.
Definition at line 26 of file JetContainer.cc.
View newest version in sPHENIX GitHub at line 26 of file JetContainer.cc
JetContainer::SrcIter JetContainer::end_src () virtual
Reimplemented in JetContainerv1.
Definition at line 41 of file JetContainer.cc.
View newest version in sPHENIX GitHub at line 41 of file JetContainer.cc
JetContainer::ConstSrcIter JetContainer::find_src (Jet::SRC src) const virtual
Reimplemented in JetContainerv1.
Definition at line 21 of file JetContainer.cc.
View newest version in sPHENIX GitHub at line 21 of file JetContainer.cc
JetContainer::SrcIter JetContainer::find_src (Jet::SRC src) virtual
Reimplemented in JetContainerv1.
Definition at line 36 of file JetContainer.cc.
View newest version in sPHENIX GitHub at line 36 of file JetContainer.cc
virtual Jet::ALGO JetContainer::get_algo () const inline virtual
Reimplemented in JetContainerv1.
Definition at line 55 of file JetContainer.h.
View newest version in sPHENIX GitHub at line 55 of file JetContainer.h
References NONE.
Referenced by DumpJetContainer::process_Node().
virtual unsigned int JetContainer::get_index_single () const inline virtual
Definition at line 118 of file JetContainer.h.
View newest version in sPHENIX GitHub at line 118 of file JetContainer.h
virtual std::vector<unsigned int> JetContainer::get_index_vec () const inline virtual
Definition at line 119 of file JetContainer.h.
View newest version in sPHENIX GitHub at line 119 of file JetContainer.h
virtual Jet* JetContainer::get_jet (unsigned int) inline virtual
Reimplemented in JetContainerv1.
Definition at line 42 of file JetContainer.h.
View newest version in sPHENIX GitHub at line 42 of file JetContainer.h
Referenced by JetBkgdSub::process_event().
virtual float JetContainer::get_jetpar_R () const inline virtual
Reimplemented in JetContainerv1.
Definition at line 61 of file JetContainer.h.
View newest version in sPHENIX GitHub at line 61 of file JetContainer.h
virtual float JetContainer::get_par () const inline virtual
Reimplemented in JetContainerv1.
Definition at line 58 of file JetContainer.h.
View newest version in sPHENIX GitHub at line 58 of file JetContainer.h
Referenced by DumpJetContainer::process_Node().
virtual float JetContainer::get_rho_median () const inline virtual
Reimplemented in JetContainerv1.
Definition at line 122 of file JetContainer.h.
View newest version in sPHENIX GitHub at line 122 of file JetContainer.h
virtual Jet* JetContainer::get_UncheckedAt (unsigned int) inline virtual
Reimplemented in JetContainerv1.
Definition at line 43 of file JetContainer.h.
View newest version in sPHENIX GitHub at line 43 of file JetContainer.h
Referenced by JetProbeInput::get_input(), and JetProbeInput::JetProbeInput().
virtual bool JetContainer::has_property (Jet::PROPERTY) const inline virtual
Reimplemented in JetContainerv1.
Definition at line 93 of file JetContainer.h.
View newest version in sPHENIX GitHub at line 93 of file JetContainer.h
void JetContainer::identify (std::ostream & os) const override virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from PHObject.
Reimplemented in JetContainerv1.
Definition at line 46 of file JetContainer.cc.
View newest version in sPHENIX GitHub at line 46 of file JetContainer.cc
virtual void JetContainer::insert_src (Jet::SRC) inline virtual
Reimplemented in JetContainerv1.
Definition at line 72 of file JetContainer.h.
View newest version in sPHENIX GitHub at line 72 of file JetContainer.h
Referenced by JetHepMCLoader::process_event().
int JetContainer::isValid () const inline override virtual
isValid returns non zero if object contains vailid data
Reimplemented from PHObject.
Definition at line 31 of file JetContainer.h.
View newest version in sPHENIX GitHub at line 31 of file JetContainer.h
virtual Jet* JetContainer::operator() (int) inline virtual
Reimplemented in JetContainerv1.
Definition at line 46 of file JetContainer.h.
View newest version in sPHENIX GitHub at line 46 of file JetContainer.h
virtual Jet* JetContainer::operator[] (int) inline virtual
Reimplemented in JetContainerv1.
Definition at line 47 of file JetContainer.h.
View newest version in sPHENIX GitHub at line 47 of file JetContainer.h
virtual void JetContainer::print_jets (std::ostream & os = std::cout) inline virtual
Reimplemented in JetContainerv1.
Definition at line 100 of file JetContainer.h.
View newest version in sPHENIX GitHub at line 100 of file JetContainer.h
References os.
virtual void JetContainer::print_property_types (std::ostream &) const inline virtual
Reimplemented in JetContainerv1.
Definition at line 98 of file JetContainer.h.
View newest version in sPHENIX GitHub at line 98 of file JetContainer.h
virtual Jet::PROPERTY JetContainer::property_index (Jet::PROPERTY) inline virtual
Reimplemented in JetContainerv1.
Definition at line 97 of file JetContainer.h.
View newest version in sPHENIX GitHub at line 97 of file JetContainer.h
Referenced by FastJetAlgo::first_call_init(), DetermineTowerBackground::process_event(), and FullJetFinder::process_event().
virtual std::map<Jet::PROPERTY, Jet::PROPERTY > JetContainer::property_indices () const inline virtual
Reimplemented in JetContainerv1.
Definition at line 92 of file JetContainer.h.
View newest version in sPHENIX GitHub at line 92 of file JetContainer.h
virtual void JetContainer::set_algo (Jet::ALGO) inline virtual
Reimplemented in JetContainerv1.
Definition at line 54 of file JetContainer.h.
View newest version in sPHENIX GitHub at line 54 of file JetContainer.h
Referenced by FastJetAlgo::first_call_init(), and JetHepMCLoader::process_event().
virtual void JetContainer::set_jetpar_R (float) inline virtual
Reimplemented in JetContainerv1.
Definition at line 60 of file JetContainer.h.
View newest version in sPHENIX GitHub at line 60 of file JetContainer.h
Referenced by FastJetAlgo::first_call_init().
virtual void JetContainer::set_par (float) inline virtual
Reimplemented in JetContainerv1.
Definition at line 57 of file JetContainer.h.
View newest version in sPHENIX GitHub at line 57 of file JetContainer.h
Referenced by JetHepMCLoader::process_event().
virtual void JetContainer::set_rho_median (float) inline virtual
Reimplemented in JetContainerv1.
Definition at line 121 of file JetContainer.h.
View newest version in sPHENIX GitHub at line 121 of file JetContainer.h
Referenced by FastJetAlgo::cluster_and_fill().
virtual size_t JetContainer::size (void) const inline virtual
Reimplemented in JetContainerv1.
Definition at line 37 of file JetContainer.h.
View newest version in sPHENIX GitHub at line 37 of file JetContainer.h
Referenced by JetContainerv1::JetContainerv1(), CopyAndSubtractJets::process_event(), PHG4DSTReader::process_event(), JetBkgdSub::process_event(), DumpJetContainer::process_Node(), and QAG4SimulationJet::process_Spectrum().
virtual size_t JetContainer::size_properties () const inline virtual
Reimplemented in JetContainerv1.
Definition at line 94 of file JetContainer.h.
View newest version in sPHENIX GitHub at line 94 of file JetContainer.h
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/jetbase/JetContainer.h
coresoftware/blob/master/offline/packages/jetbase/JetContainer.cc