Analysis Software: FieldMapReadBack Class Reference
FieldMapReadBack Class Reference
#include <tutorials/blob/master/MagneticField/src/FieldMapReadBack.h>
Public Member Functions
FieldMapReadBack (const std::string &name="FieldMapReadBack")
virtual ~FieldMapReadBack ()
int InitRun (PHCompositeNode *topNode) override
int process_event (PHCompositeNode *topNode) override
void Load3dCartMap (const std::string &fname, const float magfield_rescale=1.0)
void PrintField (const double x, const double y, const double z, const double t=0.)
void Verbosity (const int i) override
Sets the verbosity of this module (0 by default=quiet).
void SetFieldPoint (const double x, const double y, const double z, const double t=0.)
Public Member Functions inherited from SubsysReco
~SubsysReco () override
virtual int End (PHCompositeNode *)
Called at the end of all processing.
virtual int EndRun (const int)
Called at the end of each run.
virtual int Init (PHCompositeNode *)
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
void Print (const std::string &="ALL") const override
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Private Attributes
PHField * fieldmap = nullptr
double Point [4] = {0}
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = std::numeric_limits<int>::max() - 10
}
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Detailed Description
Definition at line 13 of file FieldMapReadBack.h.
View newest version in sPHENIX GitHub at line 13 of file FieldMapReadBack.h
Constructor & Destructor Documentation
FieldMapReadBack::FieldMapReadBack (const std::string & name = "FieldMapReadBack") inline
Definition at line 16 of file FieldMapReadBack.h.
View newest version in sPHENIX GitHub at line 16 of file FieldMapReadBack.h
virtual FieldMapReadBack::~FieldMapReadBack () inline virtual
Definition at line 18 of file FieldMapReadBack.h.
View newest version in sPHENIX GitHub at line 18 of file FieldMapReadBack.h
Member Function Documentation
int FieldMapReadBack::InitRun (PHCompositeNode * topNode) override virtual
Called for first event when run number is known. Typically this is where you may want to fetch data from database, because you know the run number. A place to book histograms which have to know the run number.
Reimplemented from SubsysReco.
Definition at line 17 of file FieldMapReadBack.cc.
View newest version in sPHENIX GitHub at line 17 of file FieldMapReadBack.cc
References Fun4AllReturnCodes::EVENT_OK, fieldmap, and PHFieldUtility::GetFieldMapNode().
void FieldMapReadBack::Load3dCartMap (const std::string & fname, const float magfield_rescale = 1.0)
Definition at line 44 of file FieldMapReadBack.cc.
View newest version in sPHENIX GitHub at line 44 of file FieldMapReadBack.cc
References fieldmap.
Referenced by Print3dFieldMap().
void FieldMapReadBack::PrintField (const double x, const double y, const double z, const double t = 0.)
Definition at line 49 of file FieldMapReadBack.cc.
View newest version in sPHENIX GitHub at line 49 of file FieldMapReadBack.cc
References fieldmap, PHField::GetFieldValue(), Point, and SetFieldPoint().
Referenced by Print3dFieldMap().
int FieldMapReadBack::process_event (PHCompositeNode * topNode) override virtual
Called for each event. This is where you do the real work.
Reimplemented from SubsysReco.
Definition at line 32 of file FieldMapReadBack.cc.
View newest version in sPHENIX GitHub at line 32 of file FieldMapReadBack.cc
References Fun4AllReturnCodes::EVENT_OK, fieldmap, PHField::GetFieldValue(), and Point.
void FieldMapReadBack::SetFieldPoint (const double x, const double y, const double z, const double t = 0.)
Definition at line 60 of file FieldMapReadBack.cc.
View newest version in sPHENIX GitHub at line 60 of file FieldMapReadBack.cc
References Acts::UnitConstants::cm, Point, and physmon_simulation::s.
Referenced by PrintField().
void FieldMapReadBack::Verbosity (const int ival) override virtual
Sets the verbosity of this module (0 by default=quiet).
Reimplemented from Fun4AllBase.
Definition at line 68 of file FieldMapReadBack.cc.
View newest version in sPHENIX GitHub at line 68 of file FieldMapReadBack.cc
References fieldmap, PHField::Verbosity(), and Fun4AllBase::Verbosity().
Referenced by Print3dFieldMap().
Member Data Documentation
PHField* FieldMapReadBack::fieldmap = nullptr private
Definition at line 38 of file FieldMapReadBack.h.
View newest version in sPHENIX GitHub at line 38 of file FieldMapReadBack.h
Referenced by InitRun(), Load3dCartMap(), PrintField(), process_event(), and Verbosity().
double FieldMapReadBack::Point[4] = {0} private
Definition at line 39 of file FieldMapReadBack.h.
View newest version in sPHENIX GitHub at line 39 of file FieldMapReadBack.h
Referenced by PrintField(), process_event(), and SetFieldPoint().
The documentation for this class was generated from the following files:
tutorials/blob/master/MagneticField/src/FieldMapReadBack.h
tutorials/blob/master/MagneticField/src/FieldMapReadBack.cc