Analysis Software: Acts::Delegate< R(Args...), H, O > Class Template Reference
Acts::Delegate< R(Args...), H, O > Class Template Reference
#include <acts/blob/sPHENIX/Core/include/Acts/Utilities/Delegate.hpp>
Public Member Functions
Delegate ()=default
Delegate (Delegate &&)=default
Delegate & operator= (Delegate &&)=default
Delegate (const Delegate &)=default
Delegate & operator= (const Delegate &)=default
Delegate (function_type callable)
template<typename Callable , typename = isNoFunPtr<Callable>>
Delegate (Callable &callable)
template<typename Callable , typename = isNoFunPtr<Callable>>
Delegate (Callable &&)=delete
void operator= (function_type callable)
template<typename Callable , typename = isNoFunPtr<Callable>>
void operator= (Callable &callable)
template<typename Callable , typename = isNoFunPtr<Callable>>
void operator= (Callable &&)=delete
template<auto Callable>
void connect ()
template<typename Callable , typename = isNoFunPtr<Callable>>
void connect (Callable &callable)
template<typename Callable , typename = isNoFunPtr<Callable>>
void connect (Callable &&)=delete
void connect (function_type callable)
template<auto Callable, typename Type , DelegateType T = kOwnership, typename = std::enable_if_t<T == DelegateType::NonOwning>>
void connect (const Type *instance)
template<auto Callable, typename Type >
void connect (std::unique_ptr< const Type > instance)
return_type operator() (Args...args) const
bool connected () const
operator bool () const
void disconnect ()
Disconnect this delegate, meaning it cannot be called anymore.
template<typename holder_t = holder_type, typename = std::enable_if_t<!std::is_same_v<holder_t, void>>>
const holder_type * instance () const
Private Types
using return_type = R
Alias of the return type.
using holder_type = H
using function_type = return_type(*)(const holder_type *, Args...)
Alias to the function pointer type this class will store.
using function_ptr_type = return_type(*)(Args...)
using deleter_type = void(*)(const holder_type *)
template<typename T , typename C >
using isSignatureCompatible = decltype(std::declval< T & >()=std::declval< C >())
using OwningDelegate = Delegate< R(Args...), holder_type, DelegateType::Owning >
using NonOwningDelegate = Delegate< R(Args...), holder_type, DelegateType::NonOwning >
template<typename T >
using isNoFunPtr = std::enable_if_t< not std::is_convertible_v< std::decay_t< T >, function_type > and not std::is_same_v< std::decay_t< T >, OwningDelegate > and not std::is_same_v< std::decay_t< T >, NonOwningDelegate >>
Static Private Member Functions
static void noopDeleter (const holder_type *)
Private Attributes
function_type m_function {nullptr}
Stores the function pointer wrapping the compile time function pointer given in connect().
Static Private Attributes
static constexpr DelegateType kOwnership = O
Detailed Description
template<typename R, typename H, DelegateType O, typename... Args>
class Acts::Delegate< R(Args...), H, O >
Delegate type that allows type erasure of a callable without allocation and with a single level of indirection. This type can support:
a free function pointer
a pointer to a member function alongside an instance pointer
Note
Delegate by default does not assume ownership of the instance. In that case You need to ensure that the lifetime of the callable instance is longer than that of the Delegate. If you set O to DelegateType::Owning, it will assume ownership.
Currently Delegate only supports callables that are const
Template Parameters
R Return type of the function signature
H Holder type that is used to store an instance
O Ownership type of the delegate: Owning or NonOwning
Args Types of the arguments of the function signatures
Definition at line 42 of file Delegate.hpp.
View newest version in sPHENIX GitHub at line 42 of file Delegate.hpp
Member Typedef Documentation
template<typename R , typename H , DelegateType O, typename... Args> using Acts::Delegate< R(Args...), H, O >::deleter_type = void (*)(const holder_type *) private
Definition at line 53 of file Delegate.hpp.
View newest version in sPHENIX GitHub at line 53 of file Delegate.hpp
template<typename R , typename H , DelegateType O, typename... Args> using Acts::Delegate< R(Args...), H, O >::function_ptr_type = return_type (*)(Args...) private
Definition at line 51 of file Delegate.hpp.
View newest version in sPHENIX GitHub at line 51 of file Delegate.hpp
template<typename R , typename H , DelegateType O, typename... Args> using Acts::Delegate< R(Args...), H, O >::function_type = return_type (*)(const holder_type *, Args...) private
Alias to the function pointer type this class will store.
Definition at line 49 of file Delegate.hpp.
View newest version in sPHENIX GitHub at line 49 of file Delegate.hpp
template<typename R , typename H , DelegateType O, typename... Args> using Acts::Delegate< R(Args...), H, O >::holder_type = H private
Definition at line 47 of file Delegate.hpp.
View newest version in sPHENIX GitHub at line 47 of file Delegate.hpp
template<typename R , typename H , DelegateType O, typename... Args> template<typename T > using Acts::Delegate< R(Args...), H, O >::isNoFunPtr = std::enable_if_t< not std::is_convertible_v<std::decay_t<T>, function_type> and not std::is_same_v<std::decay_t<T>, OwningDelegate> and not std::is_same_v<std::decay_t<T>, NonOwningDelegate>> private
Definition at line 67 of file Delegate.hpp.
View newest version in sPHENIX GitHub at line 67 of file Delegate.hpp
template<typename R , typename H , DelegateType O, typename... Args> template<typename T , typename C > using Acts::Delegate< R(Args...), H, O >::isSignatureCompatible = decltype(std::declval<T &>() = std::declval<C>()) private
Definition at line 57 of file Delegate.hpp.
View newest version in sPHENIX GitHub at line 57 of file Delegate.hpp
template<typename R , typename H , DelegateType O, typename... Args> using Acts::Delegate< R(Args...), H, O >::NonOwningDelegate = Delegate<R(Args...), holder_type, DelegateType::NonOwning> private
Definition at line 62 of file Delegate.hpp.
View newest version in sPHENIX GitHub at line 62 of file Delegate.hpp
template<typename R , typename H , DelegateType O, typename... Args> using Acts::Delegate< R(Args...), H, O >::OwningDelegate = Delegate<R(Args...), holder_type, DelegateType::Owning> private
Definition at line 60 of file Delegate.hpp.
View newest version in sPHENIX GitHub at line 60 of file Delegate.hpp
template<typename R , typename H , DelegateType O, typename... Args> using Acts::Delegate< R(Args...), H, O >::return_type = R private
Alias of the return type.
Definition at line 46 of file Delegate.hpp.
View newest version in sPHENIX GitHub at line 46 of file Delegate.hpp
Constructor & Destructor Documentation
template<typename R , typename H , DelegateType O, typename... Args> Acts::Delegate< R(Args...), H, O >::Delegate () default
template<typename R , typename H , DelegateType O, typename... Args> Acts::Delegate< R(Args...), H, O >::Delegate (Delegate< R(Args...), H, O > &&) default
template<typename R , typename H , DelegateType O, typename... Args> Acts::Delegate< R(Args...), H, O >::Delegate (const Delegate< R(Args...), H, O > &) default
template<typename R , typename H , DelegateType O, typename... Args> Acts::Delegate< R(Args...), H, O >::Delegate (function_type callable) inline
Constructor with an explicit runtime callable
Parameters
callable The runtime value of the callable
Note
The function signature requires the first argument of the callable is const void*. i.e. if the signature of the delegate is void(int), the callable's signature has to be void(const void*, int).
Definition at line 82 of file Delegate.hpp.
View newest version in sPHENIX GitHub at line 82 of file Delegate.hpp
template<typename R , typename H , DelegateType O, typename... Args> template<typename Callable , typename = isNoFunPtr<Callable>> Acts::Delegate< R(Args...), H, O >::Delegate (Callable & callable) inline
Constructor with a possibly stateful function object.
Template Parameters
Callable Type of the callable
Parameters
callable The callable (function object or lambda)
Note
Delegate does not assume owner ship over callable. You need to ensure it's lifetime is longer than that of Delegate.
Definition at line 90 of file Delegate.hpp.
View newest version in sPHENIX GitHub at line 90 of file Delegate.hpp
template<typename R , typename H , DelegateType O, typename... Args> template<typename Callable , typename = isNoFunPtr<Callable>> Acts::Delegate< R(Args...), H, O >::Delegate (Callable &&) delete
Constructor from rvalue reference is deleted, should catch construction with temporary objects and thus invalid pointers
Member Function Documentation
template<typename R , typename H , DelegateType O, typename... Args> template<auto Callable> void Acts::Delegate< R(Args...), H, O >::connect () inline
Connect a free function pointer.
Note
The function pointer must be constexpr for Delegate to accept it
Template Parameters
Callable The compile-time free function pointer
Definition at line 125 of file Delegate.hpp.
View newest version in sPHENIX GitHub at line 125 of file Delegate.hpp
References check_smearing_config::args, testing::Args(), and value.
template<typename R , typename H , DelegateType O, typename... Args> template<typename Callable , typename = isNoFunPtr<Callable>> void Acts::Delegate< R(Args...), H, O >::connect (Callable & callable) inline
Assignment operator with possibly stateful function object.
Template Parameters
Callable Type of the callable
Parameters
callable The callable (function object or lambda)
Note
Delegate does not assume owner ship over callable. You need to ensure it's lifetime is longer than that of Delegate.
Definition at line 146 of file Delegate.hpp.
View newest version in sPHENIX GitHub at line 146 of file Delegate.hpp
template<typename R , typename H , DelegateType O, typename... Args> template<typename Callable , typename = isNoFunPtr<Callable>> void Acts::Delegate< R(Args...), H, O >::connect (Callable &&) delete
Connection with rvalue reference is deleted, should catch assignment from temporary objects and thus invalid pointers
template<typename R , typename H , DelegateType O, typename... Args> void Acts::Delegate< R(Args...), H, O >::connect (function_type callable) inline
Connect anything that is assignable to the function pointer
Parameters
callable The runtime value of the callable
Note
The function signature requires the first argument of the callable is const void*. i.e. if the signature of the delegate is void(int), the callable's signature has to be void(const void*, int).
Definition at line 160 of file Delegate.hpp.
View newest version in sPHENIX GitHub at line 160 of file Delegate.hpp
template<typename R , typename H , DelegateType O, typename... Args> template<auto Callable, typename Type , DelegateType T = kOwnership, typename = std::enable_if_t<T == DelegateType::NonOwning>> void Acts::Delegate< R(Args...), H, O >::connect (const Type * instance) inline
Connect a member function to be called on an instance
Template Parameters
Callable The compile-time member function pointer
Type The type of the instance the member function should be called on
Parameters
instance The instance on which the member function pointer should be called on
Note
Delegate does not assume owner ship over instance. You need to ensure it's lifetime is longer than that of Delegate.
Definition at line 175 of file Delegate.hpp.
View newest version in sPHENIX GitHub at line 175 of file Delegate.hpp
References check_smearing_config::args, testing::Args(), assert, and value.
template<typename R , typename H , DelegateType O, typename... Args> template<auto Callable, typename Type > void Acts::Delegate< R(Args...), H, O >::connect (std::unique_ptr< const Type > instance) inline
Connect a member function to be called on an instance
Template Parameters
Callable The compile-time member function pointer
Type The type of the instance the member function should be called on
Parameters
instance The instance on which the member function pointer should be called on
Note
Delegate assumes owner ship over instance.
Definition at line 199 of file Delegate.hpp.
View newest version in sPHENIX GitHub at line 199 of file Delegate.hpp
References check_smearing_config::args, testing::Args(), assert, and value.
template<typename R , typename H , DelegateType O, typename... Args> bool Acts::Delegate< R(Args...), H, O >::connected () const inline
Return whether this delegate is currently connected
Returns
True if this delegate is connected
Definition at line 235 of file Delegate.hpp.
View newest version in sPHENIX GitHub at line 235 of file Delegate.hpp
template<typename R , typename H , DelegateType O, typename... Args> void Acts::Delegate< R(Args...), H, O >::disconnect () inline
Disconnect this delegate, meaning it cannot be called anymore.
Definition at line 242 of file Delegate.hpp.
View newest version in sPHENIX GitHub at line 242 of file Delegate.hpp
template<typename R , typename H , DelegateType O, typename... Args> template<typename holder_t = holder_type, typename = std::enable_if_t<!std::is_same_v<holder_t, void>>> const holder_type* Acts::Delegate< R(Args...), H, O >::instance () const inline
Definition at line 249 of file Delegate.hpp.
View newest version in sPHENIX GitHub at line 249 of file Delegate.hpp
template<typename R , typename H , DelegateType O, typename... Args> static void Acts::Delegate< R(Args...), H, O >::noopDeleter (const holder_type *) inline static private
Definition at line 255 of file Delegate.hpp.
View newest version in sPHENIX GitHub at line 255 of file Delegate.hpp
template<typename R , typename H , DelegateType O, typename... Args> Acts::Delegate< R(Args...), H, O >::operator bool () const inline
Return whether this delegate is currently connected
Returns
True if this delegate is connected
Definition at line 239 of file Delegate.hpp.
View newest version in sPHENIX GitHub at line 239 of file Delegate.hpp
template<typename R , typename H , DelegateType O, typename... Args> return_type Acts::Delegate< R(Args...), H, O >::operator() (Args... args) const inline
The call operator that exposes the functionality of the Delegate type.
Parameters
args The arguments to call the contained function with
Returns
Return value of the contained function
Definition at line 227 of file Delegate.hpp.
View newest version in sPHENIX GitHub at line 227 of file Delegate.hpp
References check_smearing_config::args, and assert.
template<typename R , typename H , DelegateType O, typename... Args> Delegate& Acts::Delegate< R(Args...), H, O >::operator= (Delegate< R(Args...), H, O > &&) default
template<typename R , typename H , DelegateType O, typename... Args> Delegate& Acts::Delegate< R(Args...), H, O >::operator= (const Delegate< R(Args...), H, O > &) default
template<typename R , typename H , DelegateType O, typename... Args> void Acts::Delegate< R(Args...), H, O >::operator= (function_type callable) inline
Assignment operator with an explicit runtime callable
Parameters
callable The runtime value of the callable
Note
The function signature requires the first argument of the callable is const void*. i.e. if the signature of the delegate is void(int), the callable's signature has to be void(const void*, int).
Definition at line 104 of file Delegate.hpp.
View newest version in sPHENIX GitHub at line 104 of file Delegate.hpp
template<typename R , typename H , DelegateType O, typename... Args> template<typename Callable , typename = isNoFunPtr<Callable>> void Acts::Delegate< R(Args...), H, O >::operator= (Callable & callable) inline
Assignment operator with possibly stateful function object.
Template Parameters
Callable Type of the callable
Parameters
callable The callable (function object or lambda)
Note
Delegate does not assume owner ship over callable. You need to ensure it's lifetime is longer than that of Delegate.
Definition at line 112 of file Delegate.hpp.
View newest version in sPHENIX GitHub at line 112 of file Delegate.hpp
template<typename R , typename H , DelegateType O, typename... Args> template<typename Callable , typename = isNoFunPtr<Callable>> void Acts::Delegate< R(Args...), H, O >::operator= (Callable &&) delete
Assignment operator from rvalue reference is deleted, should catch assignment from temporary objects and thus invalid pointers
Member Data Documentation
template<typename R , typename H , DelegateType O, typename... Args> constexpr DelegateType Acts::Delegate< R(Args...), H, O >::kOwnership = O static private
Definition at line 43 of file Delegate.hpp.
View newest version in sPHENIX GitHub at line 43 of file Delegate.hpp
template<typename R , typename H , DelegateType O, typename... Args> function_type Acts::Delegate< R(Args...), H, O >::m_function {nullptr} private
Stores the function pointer wrapping the compile time function pointer given in connect().
Definition at line 286 of file Delegate.hpp.
View newest version in sPHENIX GitHub at line 286 of file Delegate.hpp
The documentation for this class was generated from the following file:
acts/blob/sPHENIX/Core/include/Acts/Utilities/Delegate.hpp