Analysis Software: ActsFatras::Hit Class Reference
ActsFatras::Hit Class Reference
#include <acts/blob/sPHENIX/Fatras/include/ActsFatras/EventData/Hit.hpp>
Public Types
using Scalar = Acts::ActsScalar
using Vector3 = Acts::ActsVector< 3 >
using Vector4 = Acts::ActsVector< 4 >
Public Member Functions
Hit ()=default
Construct default hit with (mostly) invalid information.
Hit (Acts::GeometryIdentifier geometryId, Barcode particleId, const Vector4 &pos4, const Vector4 &before4, const Vector4 &after4, int32_t index_=-1)
Hit (const Hit &)=default
Hit (Hit &&)=default
Hit & operator= (const Hit &)=default
Hit & operator= (Hit &&)=default
constexpr Acts::GeometryIdentifier geometryId () const
Geometry identifier of the hit surface.
constexpr Barcode particleId () const
Particle identifier of the particle that generated the hit.
constexpr int32_t index () const
const Vector4 & fourPosition () const
Space-time position four-vector.
auto position () const
Three-position, i.e. spatial coordinates without the time.
Scalar time () const
Time coordinate.
const Vector4 & momentum4Before () const
Particle four-momentum before the hit.
const Vector4 & momentum4After () const
Particle four-momentum after the hit.
Vector3 directionBefore () const
Normalized particle direction vector before the hit.
Vector3 directionAfter () const
Normalized particle direction vector the hit.
Vector3 direction () const
Average normalized particle direction vector through the surface.
Scalar depositedEnergy () const
Private Attributes
Acts::GeometryIdentifier m_geometryId
Identifier of the surface.
Barcode m_particleId
Identifier of the generating particle.
int32_t m_index = -1
Index of the hit along the particle trajectory.
Vector4 m_pos4 = Vector4::Zero()
Global space-time position four-vector.
Vector4 m_before4 = Vector4::Zero()
Global particle energy-momentum four-vector before the hit.
Vector4 m_after4 = Vector4::Zero()
Global particle energy-momentum four-vector after the hit.
Detailed Description
A simulation hit on a surface.
This is the undigitized, truth hit, i.e. just a recording of the particle state at the surface intersection. Since Fatras is surface-based, the hit position is always constrained to a surface. Depending on the simulated interactions the momentum state before and after might differ and is thus stored as two separate four-vectors.
Definition at line 27 of file Hit.hpp.
View newest version in sPHENIX GitHub at line 27 of file Hit.hpp
Member Typedef Documentation
using ActsFatras::Hit::Scalar = Acts::ActsScalar
Definition at line 29 of file Hit.hpp.
View newest version in sPHENIX GitHub at line 29 of file Hit.hpp
using ActsFatras::Hit::Vector3 = Acts::ActsVector<3>
Definition at line 30 of file Hit.hpp.
View newest version in sPHENIX GitHub at line 30 of file Hit.hpp
using ActsFatras::Hit::Vector4 = Acts::ActsVector<4>
Definition at line 31 of file Hit.hpp.
View newest version in sPHENIX GitHub at line 31 of file Hit.hpp
Constructor & Destructor Documentation
ActsFatras::Hit::Hit () default
Construct default hit with (mostly) invalid information.
ActsFatras::Hit::Hit (Acts::GeometryIdentifier geometryId, Barcode particleId, const Vector4 & pos4, const Vector4 & before4, const Vector4 & after4, int32_t index_ = -1) inline
Construct from four-position and four-momenta.
Parameters
geometryId Geometry identifier of the surface
particleId Particle identifier of the particle that created the hit
pos4 Particle space-time four-vector on the surface
before4 Particle four-momentum before the interaction
after4 Particle four-momentum after the interaction
index_ Hit index along the particle trajectory
All quantities are given in the global coordinate system. It is the users responsibility to ensure that the position correspond to a position on the given surface.
Definition at line 47 of file Hit.hpp.
View newest version in sPHENIX GitHub at line 47 of file Hit.hpp
ActsFatras::Hit::Hit (const Hit &) default
ActsFatras::Hit::Hit (Hit &&) default
Member Function Documentation
Scalar ActsFatras::Hit::depositedEnergy () const inline
Energy deposited by the hit.
Return values
positive if the particle lost energy when it passed the surface
negative if magic was involved
Definition at line 99 of file Hit.hpp.
View newest version in sPHENIX GitHub at line 99 of file Hit.hpp
References Acts::eEnergy, m_after4, and m_before4.
Vector3 ActsFatras::Hit::direction () const inline
Average normalized particle direction vector through the surface.
Definition at line 90 of file Hit.hpp.
View newest version in sPHENIX GitHub at line 90 of file Hit.hpp
References Acts::eMom0, m_after4, and m_before4.
Referenced by ActsExamples::DigitizationAlgorithm::channelizing(), ActsFatras::BoundParametersSmearer< RandomEngine, kSmearDIM >::operator()(), and ActsFatras::FreeParametersSmearer< generator_t, kSize >::operator()().
Vector3 ActsFatras::Hit::directionAfter () const inline
Normalized particle direction vector the hit.
Definition at line 86 of file Hit.hpp.
View newest version in sPHENIX GitHub at line 86 of file Hit.hpp
References Acts::eMom0, and m_after4.
Vector3 ActsFatras::Hit::directionBefore () const inline
Normalized particle direction vector before the hit.
Definition at line 82 of file Hit.hpp.
View newest version in sPHENIX GitHub at line 82 of file Hit.hpp
References Acts::eMom0, and m_before4.
const Vector4& ActsFatras::Hit::fourPosition () const inline
Space-time position four-vector.
Definition at line 71 of file Hit.hpp.
View newest version in sPHENIX GitHub at line 71 of file Hit.hpp
References m_pos4.
Referenced by ActsExamples::EDM4hepUtil::writeSimHit().
constexpr Acts::GeometryIdentifier ActsFatras::Hit::geometryId () const inline
Geometry identifier of the hit surface.
Definition at line 62 of file Hit.hpp.
View newest version in sPHENIX GitHub at line 62 of file Hit.hpp
References m_geometryId.
Referenced by ActsExamples::EDM4hepUtil::writeSimHit().
constexpr int32_t ActsFatras::Hit::index () const inline
Hit index along the particle trajectory.
Return values
negative if the hit index is undefined.
Definition at line 68 of file Hit.hpp.
View newest version in sPHENIX GitHub at line 68 of file Hit.hpp
References m_index.
const Vector4& ActsFatras::Hit::momentum4After () const inline
Particle four-momentum after the hit.
Definition at line 80 of file Hit.hpp.
View newest version in sPHENIX GitHub at line 80 of file Hit.hpp
References m_after4.
Referenced by ActsExamples::EDM4hepUtil::writeSimHit().
const Vector4& ActsFatras::Hit::momentum4Before () const inline
Particle four-momentum before the hit.
Definition at line 78 of file Hit.hpp.
View newest version in sPHENIX GitHub at line 78 of file Hit.hpp
References m_before4.
Referenced by ActsExamples::EDM4hepUtil::writeSimHit().
Hit& ActsFatras::Hit::operator= (const Hit &) default
Hit& ActsFatras::Hit::operator= (Hit &&) default
constexpr Barcode ActsFatras::Hit::particleId () const inline
Particle identifier of the particle that generated the hit.
Definition at line 64 of file Hit.hpp.
View newest version in sPHENIX GitHub at line 64 of file Hit.hpp
References m_particleId.
Referenced by ActsExamples::EDM4hepUtil::writeSimHit().
auto ActsFatras::Hit::position () const inline
Three-position, i.e. spatial coordinates without the time.
Definition at line 73 of file Hit.hpp.
View newest version in sPHENIX GitHub at line 73 of file Hit.hpp
References Acts::ePos0, and m_pos4.
Referenced by ActsExamples::DigitizationAlgorithm::channelizing(), ActsFatras::BoundParametersSmearer< RandomEngine, kSmearDIM >::operator()(), and ActsFatras::FreeParametersSmearer< generator_t, kSize >::operator()().
Scalar ActsFatras::Hit::time () const inline
Time coordinate.
Definition at line 75 of file Hit.hpp.
View newest version in sPHENIX GitHub at line 75 of file Hit.hpp
References Acts::eTime, and m_pos4.
Referenced by ActsFatras::BoundParametersSmearer< RandomEngine, kSmearDIM >::operator()(), and ActsFatras::FreeParametersSmearer< generator_t, kSize >::operator()().
Member Data Documentation
Vector4 ActsFatras::Hit::m_after4 = Vector4::Zero() private
Global particle energy-momentum four-vector after the hit.
Definition at line 115 of file Hit.hpp.
View newest version in sPHENIX GitHub at line 115 of file Hit.hpp
Referenced by depositedEnergy(), direction(), directionAfter(), and momentum4After().
Vector4 ActsFatras::Hit::m_before4 = Vector4::Zero() private
Global particle energy-momentum four-vector before the hit.
Definition at line 113 of file Hit.hpp.
View newest version in sPHENIX GitHub at line 113 of file Hit.hpp
Referenced by depositedEnergy(), direction(), directionBefore(), and momentum4Before().
Acts::GeometryIdentifier ActsFatras::Hit::m_geometryId private
Identifier of the surface.
Definition at line 105 of file Hit.hpp.
View newest version in sPHENIX GitHub at line 105 of file Hit.hpp
Referenced by geometryId().
int32_t ActsFatras::Hit::m_index = -1 private
Index of the hit along the particle trajectory.
Definition at line 109 of file Hit.hpp.
View newest version in sPHENIX GitHub at line 109 of file Hit.hpp
Referenced by index().
Barcode ActsFatras::Hit::m_particleId private
Identifier of the generating particle.
Definition at line 107 of file Hit.hpp.
View newest version in sPHENIX GitHub at line 107 of file Hit.hpp
Referenced by particleId().
Vector4 ActsFatras::Hit::m_pos4 = Vector4::Zero() private
Global space-time position four-vector.
Definition at line 111 of file Hit.hpp.
View newest version in sPHENIX GitHub at line 111 of file Hit.hpp
Referenced by fourPosition(), position(), and time().
The documentation for this class was generated from the following file:
acts/blob/sPHENIX/Fatras/include/ActsFatras/EventData/Hit.hpp