Analysis Software: eventReceiverClient Class Reference
eventReceiverClient Class Reference
#include <online_distribution/blob/master/newbasic/eventReceiverClient.h>
Public Member Functions
eventReceiverClient (const std::string hostname, const int flags=0)
~eventReceiverClient ()
Event * getEvent (const int eventnumber, const int flag=0)
void setVerbosity (const int v)
int getVerbosity () const
int getStatus () const
Protected Attributes
int _sockfd
int _flags
int _broken
int _verbosity
std::string _hostname
struct sockaddr_in _serveraddr
struct hostent * _phost
Detailed Description
Definition at line 11 of file eventReceiverClient.h.
View newest version in sPHENIX GitHub at line 11 of file eventReceiverClient.h
Constructor & Destructor Documentation
eventReceiverClient::eventReceiverClient (const std::string hostname, const int flags = 0)
Definition at line 22 of file eventReceiverClient.cc.
View newest version in sPHENIX GitHub at line 22 of file eventReceiverClient.cc
References PORT, and utils::status.
eventReceiverClient::~eventReceiverClient ()
Definition at line 86 of file eventReceiverClient.cc.
View newest version in sPHENIX GitHub at line 86 of file eventReceiverClient.cc
Member Function Documentation
Event * eventReceiverClient::getEvent (const int eventnumber, const int flag = 0)
Definition at line 91 of file eventReceiverClient.cc.
View newest version in sPHENIX GitHub at line 91 of file eventReceiverClient.cc
References Event::convert(), Acts::UnitConstants::e, f, Event::identify(), MAXSIZE, and n.
Referenced by main(), and HcalMon::process_event().
int eventReceiverClient::getStatus () const inline
Definition at line 20 of file eventReceiverClient.h.
View newest version in sPHENIX GitHub at line 20 of file eventReceiverClient.h
References _broken.
Referenced by main().
int eventReceiverClient::getVerbosity () const inline
Definition at line 19 of file eventReceiverClient.h.
View newest version in sPHENIX GitHub at line 19 of file eventReceiverClient.h
References _verbosity.
void eventReceiverClient::setVerbosity (const int v) inline
Definition at line 18 of file eventReceiverClient.h.
View newest version in sPHENIX GitHub at line 18 of file eventReceiverClient.h
References _verbosity, and testSigmaEff::v.
Member Data Documentation
int eventReceiverClient::_broken protected
Definition at line 26 of file eventReceiverClient.h.
View newest version in sPHENIX GitHub at line 26 of file eventReceiverClient.h
Referenced by getStatus().
int eventReceiverClient::_flags protected
Definition at line 25 of file eventReceiverClient.h.
View newest version in sPHENIX GitHub at line 25 of file eventReceiverClient.h
std::string eventReceiverClient::_hostname protected
Definition at line 29 of file eventReceiverClient.h.
View newest version in sPHENIX GitHub at line 29 of file eventReceiverClient.h
struct hostent* eventReceiverClient::_phost protected
Definition at line 32 of file eventReceiverClient.h.
View newest version in sPHENIX GitHub at line 32 of file eventReceiverClient.h
struct sockaddr_in eventReceiverClient::_serveraddr protected
Definition at line 30 of file eventReceiverClient.h.
View newest version in sPHENIX GitHub at line 30 of file eventReceiverClient.h
int eventReceiverClient::_sockfd protected
Definition at line 20 of file eventReceiverClient.h.
View newest version in sPHENIX GitHub at line 20 of file eventReceiverClient.h
int eventReceiverClient::_verbosity protected
Definition at line 27 of file eventReceiverClient.h.
View newest version in sPHENIX GitHub at line 27 of file eventReceiverClient.h
Referenced by getVerbosity(), and setVerbosity().
The documentation for this class was generated from the following files:
online_distribution/blob/master/newbasic/eventReceiverClient.h
online_distribution/blob/master/newbasic/eventReceiverClient.cc