Analysis Software: Acts::SeedFilter< external_spacepoint_t > Class Template Reference
Acts::SeedFilter< external_spacepoint_t > Class Template Reference
#include <acts/blob/sPHENIX/Core/include/Acts/Seeding/SeedFilter.hpp>
Public Member Functions
SeedFilter (SeedFilterConfig config, IExperimentCuts< external_spacepoint_t > *expCuts=nullptr)
SeedFilter ()=delete
virtual ~SeedFilter ()=default
virtual void filterSeeds_2SpFixed (Acts::SpacePointData &spacePointData, const InternalSpacePoint< external_spacepoint_t > &bottomSP, const InternalSpacePoint< external_spacepoint_t > &middleSP, const std::vector< const InternalSpacePoint< external_spacepoint_t > * > &topSpVec, const std::vector< float > &invHelixDiameterVec, const std::vector< float > &impactParametersVec, SeedFilterState &seedFilterState, CandidatesForMiddleSp< const InternalSpacePoint< external_spacepoint_t >> &candidates_collector) const
virtual void filterSeeds_1SpFixed (Acts::SpacePointData &spacePointData, CandidatesForMiddleSp< const InternalSpacePoint< external_spacepoint_t >> &candidates_collector, const std::size_t numQualitySeeds, std::back_insert_iterator< std::vector< Seed< external_spacepoint_t >>> outIt) const
virtual void filterSeeds_1SpFixed (Acts::SpacePointData &spacePointData, std::vector< typename CandidatesForMiddleSp< const InternalSpacePoint< external_spacepoint_t >>::value_type > &candidates, const std::size_t numQualitySeeds, std::back_insert_iterator< std::vector< Seed< external_spacepoint_t >>> outIt) const
const SeedFilterConfig getSeedFilterConfig () const
const IExperimentCuts
< external_spacepoint_t > * getExperimentCuts () const
Private Attributes
const SeedFilterConfig m_cfg
const IExperimentCuts
< external_spacepoint_t > * m_experimentCuts
Detailed Description
template<typename external_spacepoint_t>
class Acts::SeedFilter< external_spacepoint_t >
Filter seeds at various stages with the currently available information.
Definition at line 45 of file SeedFilter.hpp.
View newest version in sPHENIX GitHub at line 45 of file SeedFilter.hpp
Constructor & Destructor Documentation
template<typename external_spacepoint_t > Acts::SeedFilter< external_spacepoint_t >::SeedFilter (SeedFilterConfig config, IExperimentCuts< external_spacepoint_t > * expCuts = nullptr)
Definition at line 16 of file SeedFilter.ipp.
View newest version in sPHENIX GitHub at line 16 of file SeedFilter.ipp
References Acts::SeedFilterConfig::isInInternalUnits.
template<typename external_spacepoint_t > Acts::SeedFilter< external_spacepoint_t >::SeedFilter () delete
template<typename external_spacepoint_t > virtual Acts::SeedFilter< external_spacepoint_t >::~SeedFilter () virtual default
Member Function Documentation
template<typename external_spacepoint_t > void Acts::SeedFilter< external_spacepoint_t >::filterSeeds_1SpFixed (Acts::SpacePointData & spacePointData, CandidatesForMiddleSp< const InternalSpacePoint< external_spacepoint_t >> & candidates_collector, const std::size_t numQualitySeeds, std::back_insert_iterator< std::vector< Seed< external_spacepoint_t >>> outIt) const virtual
Filter seeds once all seeds for one middle space point have been created
Parameters
spacePointData Auxiliary variables used by the seeding
candidates_collector collection of seed candidates
numQualitySeeds number of high quality seeds in seed confirmation
outIt Output iterator for the seeds for all seeds with the same middle space point
Definition at line 247 of file SeedFilter.ipp.
View newest version in sPHENIX GitHub at line 247 of file SeedFilter.ipp
template<typename external_spacepoint_t > void Acts::SeedFilter< external_spacepoint_t >::filterSeeds_1SpFixed (Acts::SpacePointData & spacePointData, std::vector< typename CandidatesForMiddleSp< const InternalSpacePoint< external_spacepoint_t >>::value_type > & candidates, const std::size_t numQualitySeeds, std::back_insert_iterator< std::vector< Seed< external_spacepoint_t >>> outIt) const virtual
Filter seeds once all seeds for one middle space point have been created
Parameters
spacePointData Auxiliary variables used by the seeding
candidates collection of seed candidates
numQualitySeeds number of high quality seeds in seed confirmation
outIt Output iterator for the seeds for all seeds with the same middle space point
Definition at line 263 of file SeedFilter.ipp.
View newest version in sPHENIX GitHub at line 263 of file SeedFilter.ipp
References m_cfg(), testing::internal::move(), Acts::SpacePointData::quality(), Acts::SpacePointData::setQuality(), and Acts::Seed< SpacePoint >::sp().
template<typename external_spacepoint_t > void Acts::SeedFilter< external_spacepoint_t >::filterSeeds_2SpFixed (Acts::SpacePointData & spacePointData, const InternalSpacePoint< external_spacepoint_t > & bottomSP, const InternalSpacePoint< external_spacepoint_t > & middleSP, const std::vector< const InternalSpacePoint< external_spacepoint_t > * > & topSpVec, const std::vector< float > & invHelixDiameterVec, const std::vector< float > & impactParametersVec, SeedFilterState & seedFilterState, CandidatesForMiddleSp< const InternalSpacePoint< external_spacepoint_t >> & candidates_collector) const virtual
Create InternalSeeds for the all seeds with the same bottom and middle space point and discard all others.
Parameters
spacePointData Auxiliary variables used by the seeding
bottomSP fixed bottom space point
middleSP fixed middle space point
topSpVec vector containing all space points that may be compatible with both bottom and middle space point
invHelixDiameterVec vector containing 1/(2*r) values where r is the helix radius
impactParametersVec vector containing the impact parameters
seedFilterState holds quantities used in seed filter
candidates_collector container for the seed candidates
Definition at line 29 of file SeedFilter.ipp.
View newest version in sPHENIX GitHub at line 29 of file SeedFilter.ipp
References Acts::SpacePointData::deltaR(), physmon_track_finding_ttbar::deltaR, i, Acts::if(), Acts::InternalSpacePoint< SpacePoint >::index(), index, m_cfg(), Acts::SeedConfirmationRangeConfig::minImpactSeedConf, Acts::SeedConfirmationRangeConfig::nTopForLargeR, Acts::SeedConfirmationRangeConfig::nTopForSmallR, Acts::SeedFilterState::nTopSeedConf, Acts::SeedFilterState::numQualitySeeds, Acts::SeedFilterState::numSeeds, Acts::SpacePointData::quality(), Acts::InternalSpacePoint< SpacePoint >::radius(), Acts::SeedConfirmationRangeConfig::rMaxSeedConf, Acts::SeedConfirmationRangeConfig::seedConfMaxZOrigin, Acts::SeedConfirmationRangeConfig::seedConfMinBottomRadius, Acts::Experimental::detail::BlueprintHelper::sort(), Acts::InternalSpacePoint< SpacePoint >::z(), and Acts::SeedFilterState::zOrigin.
template<typename external_spacepoint_t > const IExperimentCuts<external_spacepoint_t>* Acts::SeedFilter< external_spacepoint_t >::getExperimentCuts () const inline
Definition at line 106 of file SeedFilter.hpp.
View newest version in sPHENIX GitHub at line 106 of file SeedFilter.hpp
References Acts::SeedFilter< external_spacepoint_t >::m_experimentCuts.
template<typename external_spacepoint_t > const SeedFilterConfig Acts::SeedFilter< external_spacepoint_t >::getSeedFilterConfig () const inline
Definition at line 105 of file SeedFilter.hpp.
View newest version in sPHENIX GitHub at line 105 of file SeedFilter.hpp
References Acts::SeedFilter< external_spacepoint_t >::m_cfg.
Member Data Documentation
template<typename external_spacepoint_t > const SeedFilterConfig Acts::SeedFilter< external_spacepoint_t >::m_cfg private
Definition at line 111 of file SeedFilter.hpp.
View newest version in sPHENIX GitHub at line 111 of file SeedFilter.hpp
Referenced by Acts::SeedFilter< external_spacepoint_t >::getSeedFilterConfig().
template<typename external_spacepoint_t > const IExperimentCuts<external_spacepoint_t>* Acts::SeedFilter< external_spacepoint_t >::m_experimentCuts private
Definition at line 112 of file SeedFilter.hpp.
View newest version in sPHENIX GitHub at line 112 of file SeedFilter.hpp
Referenced by Acts::SeedFilter< external_spacepoint_t >::getExperimentCuts().
The documentation for this class was generated from the following files:
acts/blob/sPHENIX/Core/include/Acts/Seeding/SeedFilter.hpp
acts/blob/sPHENIX/Core/include/Acts/Seeding/SeedFilter.ipp