Analysis Software: ParameterReader Class Reference
ParameterReader Class Reference
#include <JETSCAPE/blob/main/external_packages/hydro_from_external_file/ParameterReader.h>
Public Member Functions
ParameterReader ()
~ParameterReader ()
void phraseOneLine (string str, string commentSymbol=(string)("#"))
void readFromFile (string filename, string commentSymbol=(string)("#"))
void readFromArguments (long argc, char *argv[], string commentSymbol=(string)("#"), long start_from=1)
bool exist (string name)
void setVal (string name, double value)
double getVal (string name)
void echo ()
Private Member Functions
string removeComments (string str, string commentSymbol)
void phraseEquationWithoutComments (string equation)
long find (string name)
Private Attributes
vector< string > * names
vector< double > * values
Detailed Description
Definition at line 21 of file ParameterReader.h.
View newest version in sPHENIX GitHub at line 21 of file ParameterReader.h
Constructor & Destructor Documentation
ParameterReader::ParameterReader ()
Definition at line 16 of file ParameterReader.cpp.
View newest version in sPHENIX GitHub at line 16 of file ParameterReader.cpp
References TauVsDIS_MachineLearning_Differentiation::names, and Acts::Test::values.
ParameterReader::~ParameterReader ()
Definition at line 24 of file ParameterReader.cpp.
View newest version in sPHENIX GitHub at line 24 of file ParameterReader.cpp
References TauVsDIS_MachineLearning_Differentiation::names, and Acts::Test::values.
Member Function Documentation
void ParameterReader::echo ()
Definition at line 161 of file ParameterReader.cpp.
View newest version in sPHENIX GitHub at line 161 of file ParameterReader.cpp
References TauVsDIS_MachineLearning_Differentiation::names.
Referenced by main().
bool ParameterReader::exist (string name)
Definition at line 116 of file ParameterReader.cpp.
View newest version in sPHENIX GitHub at line 116 of file ParameterReader.cpp
Referenced by init(), and medinit().
long ParameterReader::find (string name) private
Definition at line 61 of file ParameterReader.cpp.
View newest version in sPHENIX GitHub at line 61 of file ParameterReader.cpp
References TauVsDIS_MachineLearning_Differentiation::names, toLower(), and trim().
double ParameterReader::getVal (string name)
Definition at line 144 of file ParameterReader.cpp.
View newest version in sPHENIX GitHub at line 144 of file ParameterReader.cpp
References ambiguity_solver_full_chain::idx, and Acts::Test::values.
Referenced by FluidcellStatistic::FluidcellStatistic(), main(), and SurfaceFinder::SurfaceFinder().
void ParameterReader::phraseEquationWithoutComments (string equation) private
Definition at line 42 of file ParameterReader.cpp.
View newest version in sPHENIX GitHub at line 42 of file ParameterReader.cpp
References compare(), stringToDouble(), and trim().
void ParameterReader::phraseOneLine (string str, string commentSymbol = (string)("#"))
Definition at line 73 of file ParameterReader.cpp.
View newest version in sPHENIX GitHub at line 73 of file ParameterReader.cpp
References compare(), and trim().
void ParameterReader::readFromArguments (long argc, char * argv[], string commentSymbol = (string)("#"), long start_from = 1)
Definition at line 106 of file ParameterReader.cpp.
View newest version in sPHENIX GitHub at line 106 of file ParameterReader.cpp
Referenced by main().
void ParameterReader::readFromFile (string filename, string commentSymbol = (string)("#"))
Definition at line 84 of file ParameterReader.cpp.
View newest version in sPHENIX GitHub at line 84 of file ParameterReader.cpp
Referenced by main().
string ParameterReader::removeComments (string str, string commentSymbol) private
Definition at line 32 of file ParameterReader.cpp.
View newest version in sPHENIX GitHub at line 32 of file ParameterReader.cpp
void ParameterReader::setVal (string name, double value)
Definition at line 126 of file ParameterReader.cpp.
View newest version in sPHENIX GitHub at line 126 of file ParameterReader.cpp
References ambiguity_solver_full_chain::idx, TauVsDIS_MachineLearning_Differentiation::names, toLower(), trim(), value, and Acts::Test::values.
Member Data Documentation
vector<string>* ParameterReader::names private
Definition at line 24 of file ParameterReader.h.
View newest version in sPHENIX GitHub at line 24 of file ParameterReader.h
vector<double>* ParameterReader::values private
Definition at line 24 of file ParameterReader.h.
View newest version in sPHENIX GitHub at line 24 of file ParameterReader.h
The documentation for this class was generated from the following files:
JETSCAPE/blob/main/external_packages/hydro_from_external_file/ParameterReader.h
JETSCAPE/blob/main/external_packages/hydro_from_external_file/ParameterReader.cpp