Analysis Software: for cylindrical calorimeter only as implemented in RawTowerGeomContainer_Cylinderv1
for cylindrical calorimeter only as implemented in RawTowerGeomContainer_Cylinderv1
Functions
virtual double RawTowerGeomContainer::get_radius () const
virtual double RawTowerGeomContainer::get_thickness () const
virtual int RawTowerGeomContainer::get_phibins () const
virtual int RawTowerGeomContainer::get_etabins () const
virtual std::pair< double, double > RawTowerGeomContainer::get_phibounds (const int) const
virtual std::pair< double, double > RawTowerGeomContainer::get_etabounds (const int) const
virtual double RawTowerGeomContainer::get_etacenter (const int) const
virtual double RawTowerGeomContainer::get_phicenter (const int) const
virtual int RawTowerGeomContainer::get_etabin (const double) const
virtual int RawTowerGeomContainer::get_phibin (const double) const
virtual void RawTowerGeomContainer::set_radius (const double)
virtual void RawTowerGeomContainer::set_thickness (const double)
virtual void RawTowerGeomContainer::set_phibins (const int)
virtual void RawTowerGeomContainer::set_etabins (const int)
virtual void RawTowerGeomContainer::set_etabounds (const int, const std::pair< double, double > &)
virtual void RawTowerGeomContainer::set_phibounds (const int, const std::pair< double, double > &)
Detailed Description
Note these: concept do not apply to generic calorimeters, like forward calorimeters
Function Documentation
virtual int RawTowerGeomContainer::get_etabin (const double) const inline virtual
Reimplemented in RawTowerGeomContainer_Cylinderv1.
Definition at line 114 of file RawTowerGeomContainer.h.
View newest version in sPHENIX GitHub at line 114 of file RawTowerGeomContainer.h
References PHOOL_VIRTUAL_WARN.
Referenced by EMCalCalib::eval_photon_proj(), EMCalAna::eval_trk_proj(), QAG4SimulationCalorimeterSum::eval_trk_proj(), TrackProjectionTools::getE33Barrel(), SubtractTowers::process_event(), CopyAndSubtractJets::process_event(), DetermineTowerBackground::process_event(), and PHGenFitTrackProjection::process_event().
virtual int RawTowerGeomContainer::get_etabins () const inline virtual
Reimplemented in RawTowerGeomContainer_Cylinderv1.
Definition at line 85 of file RawTowerGeomContainer.h.
View newest version in sPHENIX GitHub at line 85 of file RawTowerGeomContainer.h
References PHOOL_VIRTUAL_WARN.
Referenced by PHG4OHCalDetector::AddGeometryNode(), PHG4IHCalDetector::AddGeometryNode(), PHG4OuterHcalDetector::AddGeometryNode(), PHG4InnerHcalDetector::AddGeometryNode(), PHG4SpacalDetector::AddTowerGeometryNode(), CaloGeomMapping::CreateGeomNode(), RawTowerBuilder::CreateNodes(), RawTowerCombiner::CreateNodes(), EMCalCalib::eval_photon_proj(), EMCalAna::eval_trk_proj(), QAG4SimulationCalorimeterSum::eval_trk_proj(), TrackProjectionTools::getE33Barrel(), PHActsTrackProjection::getSquareTowerEnergies(), Prototype2RawTowerBuilder::InitRun(), HcalRawTowerBuilder::InitRun(), RawClusterDeadHotMask::process_event(), RawTowerDeadTowerInterp::process_event(), SubtractTowers::process_event(), CaloTriggerSim::process_event(), DetermineTowerBackground::process_event(), PHGenFitTrackProjection::process_event(), QAG4SimulationCalorimeter::process_event_Tower(), EMCalAna::process_event_Tower(), and EMCalCalib::process_event_Tower().
virtual std::pair<double, double> RawTowerGeomContainer::get_etabounds (const int) const inline virtual
Reimplemented in RawTowerGeomContainer_Cylinderv1.
Definition at line 98 of file RawTowerGeomContainer.h.
View newest version in sPHENIX GitHub at line 98 of file RawTowerGeomContainer.h
References PHOOL_VIRTUAL_WARN.
Referenced by RawTowerCombiner::CreateNodes(), EMCalCalib::eval_photon_proj(), EMCalAna::eval_trk_proj(), QAG4SimulationCalorimeterSum::eval_trk_proj(), RetowerCEMC::process_event(), and DetermineTowerBackground::process_event().
virtual double RawTowerGeomContainer::get_etacenter (const int) const inline virtual
Reimplemented in RawTowerGeomContainer_Cylinderv1.
Definition at line 103 of file RawTowerGeomContainer.h.
View newest version in sPHENIX GitHub at line 103 of file RawTowerGeomContainer.h
References PHOOL_VIRTUAL_WARN.
Referenced by PHG4OHCalDetector::AddGeometryNode(), PHG4IHCalDetector::AddGeometryNode(), PHG4OuterHcalDetector::AddGeometryNode(), PHG4InnerHcalDetector::AddGeometryNode(), PHG4SpacalDetector::AddTowerGeometryNode(), cemcReco::calculateTSP(), CaloGeomMapping::CreateGeomNode(), RawTowerBuilder::CreateNodes(), RawTowerCombiner::CreateNodes(), EMCalCalib::eval_photon_proj(), EMCalAna::eval_trk_proj(), QAG4SimulationCalorimeterSum::eval_trk_proj(), HcalRawTowerBuilder::InitRun(), RawClusterBuilderTemplate::PrintCylGeom(), RecoInfoExport::process_event(), G4TowerNtuple::process_event(), TowerTiming::process_event(), CaloTriggerSim::process_event(), and DetermineTowerBackground::process_event().
virtual int RawTowerGeomContainer::get_phibin (const double) const inline virtual
Reimplemented in RawTowerGeomContainer_Cylinderv1.
Definition at line 119 of file RawTowerGeomContainer.h.
View newest version in sPHENIX GitHub at line 119 of file RawTowerGeomContainer.h
References PHOOL_VIRTUAL_WARN.
Referenced by EMCalCalib::eval_photon_proj(), EMCalAna::eval_trk_proj(), QAG4SimulationCalorimeterSum::eval_trk_proj(), TrackProjectionTools::getE33Barrel(), SubtractTowers::process_event(), DetermineTowerBackground::process_event(), and PHGenFitTrackProjection::process_event().
virtual int RawTowerGeomContainer::get_phibins () const inline virtual
Reimplemented in RawTowerGeomContainer_Cylinderv1.
Definition at line 78 of file RawTowerGeomContainer.h.
View newest version in sPHENIX GitHub at line 78 of file RawTowerGeomContainer.h
References PHOOL_VIRTUAL_WARN.
Referenced by PHG4OHCalDetector::AddGeometryNode(), PHG4IHCalDetector::AddGeometryNode(), PHG4OuterHcalDetector::AddGeometryNode(), PHG4InnerHcalDetector::AddGeometryNode(), PHG4SpacalDetector::AddTowerGeometryNode(), CaloGeomMapping::CreateGeomNode(), RawTowerBuilder::CreateNodes(), RawTowerCombiner::CreateNodes(), EMCalCalib::eval_photon_proj(), EMCalAna::eval_trk_proj(), QAG4SimulationCalorimeterSum::eval_trk_proj(), TrackProjectionTools::getE33Barrel(), PHActsTrackProjection::getSquareTowerEnergies(), Prototype2RawTowerBuilder::InitRun(), HcalRawTowerBuilder::InitRun(), RawClusterBuilderGraph::process_event(), RawClusterDeadHotMask::process_event(), RawClusterPositionCorrection::process_event(), RawTowerDeadTowerInterp::process_event(), SubtractTowers::process_event(), CaloTriggerSim::process_event(), DetermineTowerBackground::process_event(), PHGenFitTrackProjection::process_event(), QAG4SimulationCalorimeter::process_event_Tower(), EMCalAna::process_event_Tower(), and EMCalCalib::process_event_Tower().
virtual std::pair<double, double> RawTowerGeomContainer::get_phibounds (const int) const inline virtual
Reimplemented in RawTowerGeomContainer_Cylinderv1.
Definition at line 93 of file RawTowerGeomContainer.h.
View newest version in sPHENIX GitHub at line 93 of file RawTowerGeomContainer.h
References PHOOL_VIRTUAL_WARN.
Referenced by RawTowerCombiner::CreateNodes(), EMCalCalib::eval_photon_proj(), EMCalAna::eval_trk_proj(), QAG4SimulationCalorimeterSum::eval_trk_proj(), and DetermineTowerBackground::process_event().
virtual double RawTowerGeomContainer::get_phicenter (const int) const inline virtual
Reimplemented in RawTowerGeomContainer_Cylinderv1.
Definition at line 108 of file RawTowerGeomContainer.h.
View newest version in sPHENIX GitHub at line 108 of file RawTowerGeomContainer.h
References PHOOL_VIRTUAL_WARN.
Referenced by PHG4OHCalDetector::AddGeometryNode(), PHG4IHCalDetector::AddGeometryNode(), PHG4OuterHcalDetector::AddGeometryNode(), PHG4InnerHcalDetector::AddGeometryNode(), PHG4SpacalDetector::AddTowerGeometryNode(), cemcReco::calculateTSP(), CaloGeomMapping::CreateGeomNode(), RawTowerBuilder::CreateNodes(), RawTowerCombiner::CreateNodes(), EMCalCalib::eval_photon_proj(), EMCalAna::eval_trk_proj(), QAG4SimulationCalorimeterSum::eval_trk_proj(), HcalRawTowerBuilder::InitRun(), RawClusterBuilderTemplate::PrintCylGeom(), RecoInfoExport::process_event(), G4TowerNtuple::process_event(), TowerTiming::process_event(), CaloTriggerSim::process_event(), and DetermineTowerBackground::process_event().
virtual double RawTowerGeomContainer::get_radius () const inline virtual
Reimplemented in RawTowerGeomContainer_Cylinderv1.
Definition at line 68 of file RawTowerGeomContainer.h.
View newest version in sPHENIX GitHub at line 68 of file RawTowerGeomContainer.h
References PHOOL_VIRTUAL_WARN.
Referenced by CaloGeomMapping::CreateGeomNode(), RawTowerCombiner::CreateNodes(), PHGenFitTrackProjection::InitRun(), PHActsTrackProjection::makeCaloSurfacePtrs(), PHTrackClusterAssociator::matchTracks(), and ParticleFlowReco::process_event().
virtual double RawTowerGeomContainer::get_thickness () const inline virtual
Reimplemented in RawTowerGeomContainer_Cylinderv1.
Definition at line 73 of file RawTowerGeomContainer.h.
View newest version in sPHENIX GitHub at line 73 of file RawTowerGeomContainer.h
References PHOOL_VIRTUAL_WARN.
Referenced by PHActsTrackProjection::makeCaloSurfacePtrs().
virtual void RawTowerGeomContainer::set_etabins (const int) inline virtual
Reimplemented in RawTowerGeomContainer_Cylinderv1.
Definition at line 130 of file RawTowerGeomContainer.h.
View newest version in sPHENIX GitHub at line 130 of file RawTowerGeomContainer.h
References PHOOL_VIRTUAL_WARN.
Referenced by PHG4OHCalDetector::AddGeometryNode(), PHG4IHCalDetector::AddGeometryNode(), PHG4OuterHcalDetector::AddGeometryNode(), PHG4InnerHcalDetector::AddGeometryNode(), PHG4SpacalDetector::AddTowerGeometryNode(), CaloGeomMapping::CreateGeomNode(), RawTowerBuilder::CreateNodes(), RawTowerCombiner::CreateNodes(), Prototype2RawTowerBuilder::InitRun(), and HcalRawTowerBuilder::InitRun().
virtual void RawTowerGeomContainer::set_etabounds (const int , const std::pair< double, double > &) inline virtual
Reimplemented in RawTowerGeomContainer_Cylinderv1.
Definition at line 133 of file RawTowerGeomContainer.h.
View newest version in sPHENIX GitHub at line 133 of file RawTowerGeomContainer.h
References PHOOL_VIRTUAL_WARN.
Referenced by PHG4OHCalDetector::AddGeometryNode(), PHG4IHCalDetector::AddGeometryNode(), PHG4OuterHcalDetector::AddGeometryNode(), PHG4InnerHcalDetector::AddGeometryNode(), PHG4SpacalDetector::AddTowerGeometryNode(), CaloGeomMapping::CreateGeomNode(), RawTowerBuilder::CreateNodes(), RawTowerCombiner::CreateNodes(), and HcalRawTowerBuilder::InitRun().
virtual void RawTowerGeomContainer::set_phibins (const int) inline virtual
Reimplemented in RawTowerGeomContainer_Cylinderv1.
Definition at line 127 of file RawTowerGeomContainer.h.
View newest version in sPHENIX GitHub at line 127 of file RawTowerGeomContainer.h
References PHOOL_VIRTUAL_WARN.
Referenced by PHG4OHCalDetector::AddGeometryNode(), PHG4IHCalDetector::AddGeometryNode(), PHG4OuterHcalDetector::AddGeometryNode(), PHG4InnerHcalDetector::AddGeometryNode(), PHG4SpacalDetector::AddTowerGeometryNode(), CaloGeomMapping::CreateGeomNode(), RawTowerBuilder::CreateNodes(), RawTowerCombiner::CreateNodes(), Prototype2RawTowerBuilder::InitRun(), and HcalRawTowerBuilder::InitRun().
virtual void RawTowerGeomContainer::set_phibounds (const int , const std::pair< double, double > &) inline virtual
Reimplemented in RawTowerGeomContainer_Cylinderv1.
Definition at line 134 of file RawTowerGeomContainer.h.
View newest version in sPHENIX GitHub at line 134 of file RawTowerGeomContainer.h
References PHOOL_VIRTUAL_WARN.
Referenced by PHG4OHCalDetector::AddGeometryNode(), PHG4IHCalDetector::AddGeometryNode(), PHG4OuterHcalDetector::AddGeometryNode(), PHG4InnerHcalDetector::AddGeometryNode(), PHG4SpacalDetector::AddTowerGeometryNode(), CaloGeomMapping::CreateGeomNode(), RawTowerBuilder::CreateNodes(), RawTowerCombiner::CreateNodes(), and HcalRawTowerBuilder::InitRun().
virtual void RawTowerGeomContainer::set_radius (const double) inline virtual
Reimplemented in RawTowerGeomContainer_Cylinderv1.
Definition at line 125 of file RawTowerGeomContainer.h.
View newest version in sPHENIX GitHub at line 125 of file RawTowerGeomContainer.h
References PHOOL_VIRTUAL_WARN.
Referenced by PHG4OHCalDetector::AddGeometryNode(), PHG4IHCalDetector::AddGeometryNode(), PHG4OuterHcalDetector::AddGeometryNode(), PHG4InnerHcalDetector::AddGeometryNode(), PHG4SpacalDetector::AddTowerGeometryNode(), CaloGeomMapping::CreateGeomNode(), RawTowerBuilder::CreateNodes(), and HcalRawTowerBuilder::InitRun().
virtual void RawTowerGeomContainer::set_thickness (const double) inline virtual
Reimplemented in RawTowerGeomContainer_Cylinderv1.
Definition at line 126 of file RawTowerGeomContainer.h.
View newest version in sPHENIX GitHub at line 126 of file RawTowerGeomContainer.h
References PHOOL_VIRTUAL_WARN.
Referenced by PHG4OHCalDetector::AddGeometryNode(), PHG4IHCalDetector::AddGeometryNode(), PHG4OuterHcalDetector::AddGeometryNode(), PHG4InnerHcalDetector::AddGeometryNode(), PHG4SpacalDetector::AddTowerGeometryNode(), CaloGeomMapping::CreateGeomNode(), RawTowerBuilder::CreateNodes(), and HcalRawTowerBuilder::InitRun().