Analysis Software: macros/blob/master/common/G4_Mbd.C File Reference
G4_Mbd.C File Reference
#include <GlobalVariables.C>
#include <g4detectors/PHG4BbcSubsystem.h>
#include <g4mbd/MbdDigitization.h>
#include <g4mbd/MbdVertexFastSimReco.h>
#include <mbd/MbdReco.h>
#include <g4main/PHG4Reco.h>
#include <fun4all/Fun4AllServer.h>
Namespaces
namespace Enable
namespace G4MBD
Macros
#define MACRO_G4MBD_C
Functions
void MbdInit ()
void Mbd (PHG4Reco *g4Reco)
void Mbd_Reco ()
Variables
bool Enable::MBD = false
bool Enable::MBD_SUPPORT = false
bool Enable::MBDRECO = false
bool Enable::MBDFAKE = false
int Enable::MBD_VERBOSITY = 0
double G4MBD::z_smearing = 0.
double G4MBD::t_smearing = 0.02
Macro Definition Documentation
#define MACRO_G4MBD_C
Definition at line 2 of file G4_Mbd.C.
View newest version in sPHENIX GitHub at line 2 of file G4_Mbd.C
Function Documentation
void Mbd (PHG4Reco * g4Reco)
Definition at line 51 of file G4_Mbd.C.
View newest version in sPHENIX GitHub at line 51 of file G4_Mbd.C
References Enable::MBD, Enable::MBD_SUPPORT, PHG4DetectorSubsystem::OverlapCheck(), Enable::OVERLAPCHECK, PHG4Reco::registerSubsystem(), PHG4DetectorSubsystem::SetActive(), PHG4DetectorSubsystem::SetSupportActive(), PHG4DetectorSubsystem::SuperDetector(), and Enable::SUPPORT.
Referenced by G4Setup().
void Mbd_Reco ()
Definition at line 69 of file G4_Mbd.C.
View newest version in sPHENIX GitHub at line 69 of file G4_Mbd.C
References Fun4AllServer::instance(), Enable::MBD_VERBOSITY, Enable::MBDFAKE, Enable::MBDRECO, Fun4AllServer::registerSubsystem(), MbdVertexFastSimReco::set_t_smearing(), MbdVertexFastSimReco::set_z_smearing(), G4MBD::t_smearing, verbosity, Enable::VERBOSITY, Fun4AllBase::Verbosity(), and G4MBD::z_smearing.
Referenced by Fun4All_BHG(), Fun4All_G4_sPHENIX(), Fun4All_pi0tbt_SIMPLE_EMBED(), Fun4All_RunNewTruthMatcher(), run_calo_fromMDC2Hits_towslope_Fun4All_G4_Calo(), rundst_spiNo(), and spiNo2().
void MbdInit ()
Definition at line 35 of file G4_Mbd.C.
View newest version in sPHENIX GitHub at line 35 of file G4_Mbd.C
References BlackHoleGeometry::max_radius, BlackHoleGeometry::max_z, Enable::MBD, Enable::MBDFAKE, Acts::UnitConstants::min, and BlackHoleGeometry::min_z.
Referenced by G4Init().