Analysis Software: QAG4SimulationDistortions Class Reference
QAG4SimulationDistortions Class Reference
#include <coresoftware/blob/master/offline/QA/modules/QAG4SimulationDistortions.h>
Public Member Functions
QAG4SimulationDistortions (const std::string &name="QAG4SimulationDistortions")
~QAG4SimulationDistortions () override
int Init (PHCompositeNode *) override
int InitRun (PHCompositeNode *topNode) override
int process_event (PHCompositeNode *) override
Public Member Functions inherited from SubsysReco
~SubsysReco () override
virtual int End (PHCompositeNode *)
Called at the end of all processing.
virtual int EndRun (const int)
Called at the end of each run.
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
void Print (const std::string &="ALL") const override
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Private Member Functions
std::string get_histo_prefix ()
std::vector< TrkrDefs::cluskey > get_cluster_keys (SvtxTrack *track)
bool checkTrack (SvtxTrack *track)
Private Attributes
SvtxTrackMap * m_trackMap = nullptr
TrkrClusterContainer * m_clusterContainer = nullptr
ActsGeometry * m_tGeometry = nullptr
int m_event = 0
float m_tanAlpha = NAN
float m_tanBeta = NAN
float m_drphi = NAN
float m_dz = NAN
float m_clusR = NAN
float m_clusPhi = NAN
float m_clusZ = NAN
float m_statePhi = NAN
float m_stateZ = NAN
float m_stateR = NAN
float m_stateRPhiErr = NAN
float m_stateZErr = NAN
float m_clusRPhiErr = NAN
float m_clusZErr = NAN
TrkrDefs::cluskey m_cluskey = TrkrDefs::CLUSKEYMAX
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = std::numeric_limits<int>::max() - 10
}
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Detailed Description
Definition at line 19 of file QAG4SimulationDistortions.h.
View newest version in sPHENIX GitHub at line 19 of file QAG4SimulationDistortions.h
Constructor & Destructor Documentation
QAG4SimulationDistortions::QAG4SimulationDistortions (const std::string & name = "QAG4SimulationDistortions")
Definition at line 76 of file QAG4SimulationDistortions.cc.
View newest version in sPHENIX GitHub at line 76 of file QAG4SimulationDistortions.cc
QAG4SimulationDistortions::~QAG4SimulationDistortions () override
Definition at line 82 of file QAG4SimulationDistortions.cc.
View newest version in sPHENIX GitHub at line 82 of file QAG4SimulationDistortions.cc
Member Function Documentation
bool QAG4SimulationDistortions::checkTrack (SvtxTrack * track) private
Definition at line 344 of file QAG4SimulationDistortions.cc.
View newest version in sPHENIX GitHub at line 344 of file QAG4SimulationDistortions.cc
References get_cluster_keys(), and SvtxTrack::get_pt().
Referenced by process_event().
std::vector< TrkrDefs::cluskey > QAG4SimulationDistortions::get_cluster_keys (SvtxTrack * track) private
Definition at line 363 of file QAG4SimulationDistortions.cc.
View newest version in sPHENIX GitHub at line 363 of file QAG4SimulationDistortions.cc
References SvtxTrack::get_silicon_seed(), SvtxTrack::get_tpc_seed(), out, and seed.
Referenced by checkTrack().
std::string QAG4SimulationDistortions::get_histo_prefix () inline private
Definition at line 31 of file QAG4SimulationDistortions.h.
View newest version in sPHENIX GitHub at line 31 of file QAG4SimulationDistortions.h
References Fun4AllBase::Name().
Referenced by Init(), and process_event().
int QAG4SimulationDistortions::Init (PHCompositeNode *) override virtual
Called during initialization. Typically this is where you can book histograms, and e.g. register them to Fun4AllServer (so they can be output to file using Fun4AllServer::dumpHistos() method).
Reimplemented from SubsysReco.
Definition at line 87 of file QAG4SimulationDistortions.cc.
View newest version in sPHENIX GitHub at line 87 of file QAG4SimulationDistortions.cc
References assert, Fun4AllReturnCodes::EVENT_OK, get_histo_prefix(), QAHistManagerDef::getHistoManager(), h, m_cluskey, m_clusPhi, m_clusR, m_clusRPhiErr, m_clusZ, m_clusZErr, m_drphi, m_dz, m_event, m_statePhi, m_stateR, m_stateRPhiErr, m_stateZ, m_stateZErr, m_tanAlpha, m_tanBeta, Fun4AllHistoManager::registerHisto(), and t.
int QAG4SimulationDistortions::InitRun (PHCompositeNode *) override virtual
Called for first event when run number is known. Typically this is where you may want to fetch data from database, because you know the run number.
Reimplemented from SubsysReco.
Definition at line 160 of file QAG4SimulationDistortions.cc.
View newest version in sPHENIX GitHub at line 160 of file QAG4SimulationDistortions.cc
References Fun4AllReturnCodes::ABORTRUN, Fun4AllReturnCodes::EVENT_OK, m_clusterContainer, m_tGeometry, m_trackMap, and PHWHERE.
int QAG4SimulationDistortions::process_event (PHCompositeNode *) override virtual
Called for each event. This is where you do the real work.
Should have never been added to the map...
If the state name wasn't set to the ckey, it wasn't analyzed in PHTpcResiduals (i.e. it isn't in the tpc)
Reimplemented from SubsysReco.
Definition at line 179 of file QAG4SimulationDistortions.cc.
View newest version in sPHENIX GitHub at line 179 of file QAG4SimulationDistortions.cc
References assert, checkTrack(), deltaPhi(), dz, Fun4AllReturnCodes::EVENT_OK, TrkrClusterContainer::findCluster(), get_histo_prefix(), QAG4Util::get_r(), ActsGeometry::getGlobalPosition(), Fun4AllHistoManager::getHisto(), QAHistManagerDef::getHistoManager(), TrkrDefs::getLayer(), layer, m_cluskey, m_clusPhi, m_clusR, m_clusRPhiErr, m_clusterContainer, m_clusZ, m_clusZErr, m_drphi, m_dz, m_event, m_statePhi, m_stateR, m_stateRPhiErr, m_stateZ, m_stateZErr, m_tanAlpha, m_tanBeta, m_tGeometry, m_trackMap, and filter::state.
Member Data Documentation
TrkrDefs::cluskey QAG4SimulationDistortions::m_cluskey = TrkrDefs::CLUSKEYMAX private
Definition at line 57 of file QAG4SimulationDistortions.h.
View newest version in sPHENIX GitHub at line 57 of file QAG4SimulationDistortions.h
Referenced by Init(), and process_event().
float QAG4SimulationDistortions::m_clusPhi = NAN private
Definition at line 48 of file QAG4SimulationDistortions.h.
View newest version in sPHENIX GitHub at line 48 of file QAG4SimulationDistortions.h
Referenced by Init(), and process_event().
float QAG4SimulationDistortions::m_clusR = NAN private
Definition at line 47 of file QAG4SimulationDistortions.h.
View newest version in sPHENIX GitHub at line 47 of file QAG4SimulationDistortions.h
Referenced by Init(), and process_event().
float QAG4SimulationDistortions::m_clusRPhiErr = NAN private
Definition at line 55 of file QAG4SimulationDistortions.h.
View newest version in sPHENIX GitHub at line 55 of file QAG4SimulationDistortions.h
Referenced by Init(), and process_event().
TrkrClusterContainer* QAG4SimulationDistortions::m_clusterContainer = nullptr private
Definition at line 39 of file QAG4SimulationDistortions.h.
View newest version in sPHENIX GitHub at line 39 of file QAG4SimulationDistortions.h
Referenced by InitRun(), and process_event().
float QAG4SimulationDistortions::m_clusZ = NAN private
Definition at line 49 of file QAG4SimulationDistortions.h.
View newest version in sPHENIX GitHub at line 49 of file QAG4SimulationDistortions.h
Referenced by Init(), and process_event().
float QAG4SimulationDistortions::m_clusZErr = NAN private
Definition at line 56 of file QAG4SimulationDistortions.h.
View newest version in sPHENIX GitHub at line 56 of file QAG4SimulationDistortions.h
Referenced by Init(), and process_event().
float QAG4SimulationDistortions::m_drphi = NAN private
Definition at line 45 of file QAG4SimulationDistortions.h.
View newest version in sPHENIX GitHub at line 45 of file QAG4SimulationDistortions.h
Referenced by Init(), and process_event().
float QAG4SimulationDistortions::m_dz = NAN private
Definition at line 46 of file QAG4SimulationDistortions.h.
View newest version in sPHENIX GitHub at line 46 of file QAG4SimulationDistortions.h
Referenced by Init(), and process_event().
int QAG4SimulationDistortions::m_event = 0 private
Definition at line 42 of file QAG4SimulationDistortions.h.
View newest version in sPHENIX GitHub at line 42 of file QAG4SimulationDistortions.h
Referenced by Init(), and process_event().
float QAG4SimulationDistortions::m_statePhi = NAN private
Definition at line 50 of file QAG4SimulationDistortions.h.
View newest version in sPHENIX GitHub at line 50 of file QAG4SimulationDistortions.h
Referenced by Init(), and process_event().
float QAG4SimulationDistortions::m_stateR = NAN private
Definition at line 52 of file QAG4SimulationDistortions.h.
View newest version in sPHENIX GitHub at line 52 of file QAG4SimulationDistortions.h
Referenced by Init(), and process_event().
float QAG4SimulationDistortions::m_stateRPhiErr = NAN private
Definition at line 53 of file QAG4SimulationDistortions.h.
View newest version in sPHENIX GitHub at line 53 of file QAG4SimulationDistortions.h
Referenced by Init(), and process_event().
float QAG4SimulationDistortions::m_stateZ = NAN private
Definition at line 51 of file QAG4SimulationDistortions.h.
View newest version in sPHENIX GitHub at line 51 of file QAG4SimulationDistortions.h
Referenced by Init(), and process_event().
float QAG4SimulationDistortions::m_stateZErr = NAN private
Definition at line 54 of file QAG4SimulationDistortions.h.
View newest version in sPHENIX GitHub at line 54 of file QAG4SimulationDistortions.h
Referenced by Init(), and process_event().
float QAG4SimulationDistortions::m_tanAlpha = NAN private
Definition at line 43 of file QAG4SimulationDistortions.h.
View newest version in sPHENIX GitHub at line 43 of file QAG4SimulationDistortions.h
Referenced by Init(), and process_event().
float QAG4SimulationDistortions::m_tanBeta = NAN private
Definition at line 44 of file QAG4SimulationDistortions.h.
View newest version in sPHENIX GitHub at line 44 of file QAG4SimulationDistortions.h
Referenced by Init(), and process_event().
ActsGeometry* QAG4SimulationDistortions::m_tGeometry = nullptr private
Definition at line 40 of file QAG4SimulationDistortions.h.
View newest version in sPHENIX GitHub at line 40 of file QAG4SimulationDistortions.h
Referenced by InitRun(), and process_event().
SvtxTrackMap* QAG4SimulationDistortions::m_trackMap = nullptr private
Definition at line 38 of file QAG4SimulationDistortions.h.
View newest version in sPHENIX GitHub at line 38 of file QAG4SimulationDistortions.h
Referenced by InitRun(), and process_event().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/QA/modules/QAG4SimulationDistortions.h
coresoftware/blob/master/offline/QA/modules/QAG4SimulationDistortions.cc