Analysis Software: HFjets Namespace Reference
HFjets Namespace Reference
Namespaces
namespace Enable
namespace KFPARTICLE
namespace KFParticleBaseCut
Functions
int KFParticle_Set_Reco (ResonanceJetTagging::TAG tag)
Function Documentation
int HFjets::KFParticle_Set_Reco (ResonanceJetTagging::TAG tag)
Definition at line 74 of file HFReco.C.
View newest version in sPHENIX GitHub at line 74 of file HFReco.C
References Fun4AllReturnCodes::ABORTRUN, KFParticle_sPHENIX::allowZeroMassTracks(), KFParticle_sPHENIX::constrainToPrimaryVertex(), HFjets::KFParticleBaseCut::constrainToPV, KFPARTICLE::D0MassRange(), KFPARTICLE::D0Name, HFjets::KFPARTICLE::D0toK3piDecayDescriptor, HFjets::KFPARTICLE::D0toK3piName, HFjets::KFPARTICLE::D0toKpiDecayDescriptor, KFParticle_sPHENIX::doTruthMatching(), HFjets::KFPARTICLE::DplusMassRange(), HFjets::KFPARTICLE::DplusName, HFjets::KFPARTICLE::DplustoK2piDecayDescriptor, KFParticle_sPHENIX::getAllPVInfo(), KFParticle_sPHENIX::getCaloInfo(), KFParticle_sPHENIX::getDetectorInfo(), Fun4AllServer::instance(), HFjets::Enable::KFPARTICLE_ALL_PV_INFO, HFjets::KFParticleBaseCut::KFPARTICLE_ALLOW_ZERO_MASS_TRACKS, Enable::KFPARTICLE_APPEND_TO_DST, HFjets::Enable::KFPARTICLE_CALO_INFO, Enable::KFPARTICLE_DETECTOR_INFO, Enable::KFPARTICLE_SAVE_NTUPLE, Enable::KFPARTICLE_TRUTH_MATCH, Enable::KFPARTICLE_VERBOSITY, KFPARTICLE::LambdacDecayDescriptor, KFPARTICLE::LambdacMassRange(), KFPARTICLE::LambdacName, KFParticleBaseCut::maxTrackchi2nDoF, KFParticleBaseCut::maxTrackTrackDCA, KFParticleBaseCut::maxVertexchi2nDoF, KFParticleBaseCut::minMotherPT, HFjets::KFParticleBaseCut::minTrackIP, KFParticleBaseCut::minTrackIPchi2, KFParticleBaseCut::minTrackPT, Fun4AllServer::registerSubsystem(), KFParticle_sPHENIX::saveDST(), KFParticle_sPHENIX::saveOutput(), KFParticle_sPHENIX::setContainerName(), KFParticle_sPHENIX::setDecayDescriptor(), KFParticle_sPHENIX::setFlightDistancechi2(), KFParticle_sPHENIX::setMaximumDaughterDCA(), KFParticle_sPHENIX::setMaximumMass(), KFParticle_sPHENIX::setMaximumTrackchi2nDOF(), KFParticle_sPHENIX::setMaximumVertexchi2nDOF(), KFParticle_sPHENIX::setMinDIRA(), KFParticle_sPHENIX::setMinimumMass(), KFParticle_sPHENIX::setMinimumTrackIP(), KFParticle_sPHENIX::setMinimumTrackIPchi2(), KFParticle_sPHENIX::setMinimumTrackPT(), KFParticle_sPHENIX::setMotherIPchi2(), KFParticle_sPHENIX::setMotherPT(), KFParticle_sPHENIX::setOutputName(), and Fun4AllBase::Verbosity().