Analysis Software: ogzBuffer Class Reference
ogzBuffer Class Reference
#include <online_distribution/blob/master/newbasic/ogzBuffer.h>
Public Member Functions
ogzBuffer (int fd, PHDWORD *where, const int length, const int level=3, const int irun=1, const int iseq=0)
virtual ~ogzBuffer ()
virtual int writeout ()
Public Member Functions inherited from ophBuffer
ophBuffer ()
ophBuffer (int fd, PHDWORD *where, const int length, const int irun=1, const int iseq=0)
ophBuffer (const char *filename, PHDWORD *where, const int length, int &status, const int irun=1, const int iseq=0)
~ophBuffer ()
int nextEvent (const unsigned int evtsize, const int etype=0, const int evtseq=0)
int addRawEvent (unsigned int *)
int addEvent (Event *)
int addFrame (PHDWORD *)
int addPacket (const Packet *p)
int addUnstructPacketData (PHDWORD *data, const int length, const int id, const int wordsize, const int hitformat)
int writeout ()
int setMaxSize (const int size)
int getMaxSize () const
unsigned long long getBytesWritten () const
int addEoB ()
Public Member Functions inherited from oBuffer
oBuffer ()
virtual ~oBuffer ()
Protected Attributes
PHDWORD * outputarray
uLongf outputarraylength
int compressionlevel
Protected Attributes inherited from ophBuffer
buffer_ptr bptr
buffer_ptr bptr_being_written
buffer_ptr bptr0
buffer_ptr bptr1
PHDWORD * data_ptr
int current_index
int max_length
int max_size
unsigned int left
int sequence
int runnumber
unsigned long long byteswritten
oEvent * current_event
int eventsequence
int current_etype
int has_end
int dirty
int fd
int our_fd
int good_object
Additional Inherited Members
Protected Member Functions inherited from ophBuffer
int prepare_next ()
Detailed Description
Definition at line 10 of file ogzBuffer.h.
View newest version in sPHENIX GitHub at line 10 of file ogzBuffer.h
Constructor & Destructor Documentation
ogzBuffer::ogzBuffer (int fd, PHDWORD * where, const int length, const int level = 3, const int irun = 1, const int iseq = 0)
Definition at line 8 of file ogzBuffer.cc.
View newest version in sPHENIX GitHub at line 8 of file ogzBuffer.cc
References compressionlevel, physmon_simulation::level, outputarray, and outputarraylength.
ogzBuffer::~ogzBuffer () virtual
Definition at line 73 of file ogzBuffer.cc.
View newest version in sPHENIX GitHub at line 73 of file ogzBuffer.cc
References outputarray, and writeout().
Member Function Documentation
int ogzBuffer::writeout () virtual
Implements oBuffer.
Definition at line 35 of file ogzBuffer.cc.
View newest version in sPHENIX GitHub at line 35 of file ogzBuffer.cc
References ophBuffer::addEoB(), ophBuffer::bptr, BUFFERBLOCKSIZE, BUFFERHEADERLENGTH, oBuffer::buffer_ptr::Bufseq, ophBuffer::byteswritten, compressionlevel, ophBuffer::dirty, ophBuffer::fd, GZBUFFERMARKER, ophBuffer::has_end, oBuffer::buffer_ptr::Length, n, outputarray, outputarraylength, and write().
Referenced by ~ogzBuffer().
Member Data Documentation
int ogzBuffer::compressionlevel protected
Definition at line 42 of file ogzBuffer.h.
View newest version in sPHENIX GitHub at line 42 of file ogzBuffer.h
Referenced by ogzBuffer(), and writeout().
PHDWORD* ogzBuffer::outputarray protected
Definition at line 40 of file ogzBuffer.h.
View newest version in sPHENIX GitHub at line 40 of file ogzBuffer.h
Referenced by ogzBuffer(), writeout(), and ~ogzBuffer().
uLongf ogzBuffer::outputarraylength protected
Definition at line 41 of file ogzBuffer.h.
View newest version in sPHENIX GitHub at line 41 of file ogzBuffer.h
Referenced by ogzBuffer(), and writeout().
The documentation for this class was generated from the following files:
online_distribution/blob/master/newbasic/ogzBuffer.h
online_distribution/blob/master/newbasic/ogzBuffer.cc