Analysis Software: MicromegasHotChannelMapData Class Reference
MicromegasHotChannelMapData Class Reference
micromegas calibration data
#include <coresoftware/blob/master/offline/packages/micromegas/MicromegasHotChannelMapData.h>
Classes
class channel_id_t
channel id
Public Member Functions
MicromegasHotChannelMapData ()=default
constructor
modifiers
void read (const std::string &)
read calibration from file
void add_hot_channel (int, int, int)
add hot channel
accessors
void write (const std::string &) const
write calibration to file
bool is_hot_channel (int, int, int) const
returns true if channel is hot
Private Types
using channel_id_set_t = std::set< channel_id_t >
Private Attributes
channel_id_set_t m_hot_channel_map
Friends
std::ostream & operator<< (std::ostream &, const MicromegasHotChannelMapData &)
Detailed Description
micromegas calibration data
Definition at line 17 of file MicromegasHotChannelMapData.h.
View newest version in sPHENIX GitHub at line 17 of file MicromegasHotChannelMapData.h
Member Typedef Documentation
using MicromegasHotChannelMapData::channel_id_set_t = std::set<channel_id_t> private
Definition at line 81 of file MicromegasHotChannelMapData.h.
View newest version in sPHENIX GitHub at line 81 of file MicromegasHotChannelMapData.h
Constructor & Destructor Documentation
MicromegasHotChannelMapData::MicromegasHotChannelMapData () default
constructor
Member Function Documentation
void MicromegasHotChannelMapData::add_hot_channel (int layer, int tile, int strip)
add hot channel
Definition at line 75 of file MicromegasHotChannelMapData.cc.
View newest version in sPHENIX GitHub at line 75 of file MicromegasHotChannelMapData.cc
References m_hot_channel_map.
bool MicromegasHotChannelMapData::is_hot_channel (int layer, int tile, int strip) const
returns true if channel is hot
Definition at line 104 of file MicromegasHotChannelMapData.cc.
View newest version in sPHENIX GitHub at line 104 of file MicromegasHotChannelMapData.cc
References layer, m_hot_channel_map, and tile().
Referenced by MicromegasCombinedDataDecoder::process_event().
void MicromegasHotChannelMapData::read (const std::string & filename)
read calibration from file
Definition at line 36 of file MicromegasHotChannelMapData.cc.
View newest version in sPHENIX GitHub at line 36 of file MicromegasHotChannelMapData.cc
References CDBTTree::GetIntValue(), CDBTTree::GetSingleIntValue(), i, CDBTTree::LoadCalibrations(), and m_hot_channel_map.
Referenced by MicromegasCombinedDataDecoder::Init().
void MicromegasHotChannelMapData::write (const std::string & filename) const
write calibration to file
Definition at line 79 of file MicromegasHotChannelMapData.cc.
View newest version in sPHENIX GitHub at line 79 of file MicromegasHotChannelMapData.cc
References CDBTTree::Commit(), CDBTTree::CommitSingle(), index, m_hot_channel_map, CDBTTree::SetIntValue(), CDBTTree::SetSingleIntValue(), and CDBTTree::WriteCDBTTree().
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & out, const MicromegasHotChannelMapData & calib_data) friend
Definition at line 24 of file MicromegasHotChannelMapData.cc.
View newest version in sPHENIX GitHub at line 24 of file MicromegasHotChannelMapData.cc
Member Data Documentation
channel_id_set_t MicromegasHotChannelMapData::m_hot_channel_map private
Definition at line 82 of file MicromegasHotChannelMapData.h.
View newest version in sPHENIX GitHub at line 82 of file MicromegasHotChannelMapData.h
Referenced by add_hot_channel(), is_hot_channel(), operator<<(), read(), and write().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/micromegas/MicromegasHotChannelMapData.h
coresoftware/blob/master/offline/packages/micromegas/MicromegasHotChannelMapData.cc