Analysis Software: Acts::Test::MicroBenchmarkResult Struct Reference
Acts::Test::MicroBenchmarkResult Struct Reference
#include <acts/blob/sPHENIX/Tests/CommonHelpers/Acts/Tests/CommonHelpers/BenchmarkTools.hpp>
Public Types
using Duration = std::chrono::duration< double, std::nano >
Public Member Functions
Duration totalTime () const
Duration iterTimeAverage () const
Duration iterTimeError () const
std::vector< Duration > sortedRunTimes () const
Duration runTimeMedian () const
std::pair< Duration, Duration > runTimeQuartiles () const
Duration runTimeRobustStddev () const
Duration runTimeError () const
Public Attributes
size_t iters_per_run = 0
std::vector< Duration > run_timings
Friends
std::ostream & operator<< (std::ostream &os, const MicroBenchmarkResult &res)
Detailed Description
Definition at line 183 of file BenchmarkTools.hpp.
View newest version in sPHENIX GitHub at line 183 of file BenchmarkTools.hpp
Member Typedef Documentation
using Acts::Test::MicroBenchmarkResult::Duration = std::chrono::duration<double, std::nano>
Definition at line 184 of file BenchmarkTools.hpp.
View newest version in sPHENIX GitHub at line 184 of file BenchmarkTools.hpp
Member Function Documentation
Duration Acts::Test::MicroBenchmarkResult::iterTimeAverage () const inline
Definition at line 220 of file BenchmarkTools.hpp.
View newest version in sPHENIX GitHub at line 220 of file BenchmarkTools.hpp
References assert, iters_per_run, and runTimeMedian().
Referenced by Acts::Test::BOOST_AUTO_TEST_CASE().
Duration Acts::Test::MicroBenchmarkResult::iterTimeError () const inline
Definition at line 231 of file BenchmarkTools.hpp.
View newest version in sPHENIX GitHub at line 231 of file BenchmarkTools.hpp
References assert, iters_per_run, and runTimeError().
Referenced by Acts::Test::BOOST_AUTO_TEST_CASE().
Duration Acts::Test::MicroBenchmarkResult::runTimeError () const inline
Definition at line 313 of file BenchmarkTools.hpp.
View newest version in sPHENIX GitHub at line 313 of file BenchmarkTools.hpp
References run_timings, and runTimeRobustStddev().
Referenced by Acts::Test::BOOST_AUTO_TEST_CASE(), and iterTimeError().
Duration Acts::Test::MicroBenchmarkResult::runTimeMedian () const inline
Definition at line 248 of file BenchmarkTools.hpp.
View newest version in sPHENIX GitHub at line 248 of file BenchmarkTools.hpp
References assert, run_timings, and sortedRunTimes().
Referenced by Acts::Test::BOOST_AUTO_TEST_CASE(), and iterTimeAverage().
std::pair<Duration, Duration> Acts::Test::MicroBenchmarkResult::runTimeQuartiles () const inline
Definition at line 260 of file BenchmarkTools.hpp.
View newest version in sPHENIX GitHub at line 260 of file BenchmarkTools.hpp
References assert, Acts::Test::offset(), run_timings, and sortedRunTimes().
Referenced by Acts::Test::BOOST_AUTO_TEST_CASE(), and runTimeRobustStddev().
Duration Acts::Test::MicroBenchmarkResult::runTimeRobustStddev () const inline
Definition at line 303 of file BenchmarkTools.hpp.
View newest version in sPHENIX GitHub at line 303 of file BenchmarkTools.hpp
References runTimeQuartiles().
Referenced by Acts::Test::BOOST_AUTO_TEST_CASE(), and runTimeError().
std::vector<Duration> Acts::Test::MicroBenchmarkResult::sortedRunTimes () const inline
Definition at line 237 of file BenchmarkTools.hpp.
View newest version in sPHENIX GitHub at line 237 of file BenchmarkTools.hpp
References run_timings, and Acts::Experimental::detail::BlueprintHelper::sort().
Referenced by Acts::Test::BOOST_AUTO_TEST_CASE(), runTimeMedian(), and runTimeQuartiles().
Duration Acts::Test::MicroBenchmarkResult::totalTime () const inline
Definition at line 196 of file BenchmarkTools.hpp.
View newest version in sPHENIX GitHub at line 196 of file BenchmarkTools.hpp
References run_timings.
Referenced by Acts::Test::BOOST_AUTO_TEST_CASE().
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & os, const MicroBenchmarkResult & res) friend
Definition at line 326 of file BenchmarkTools.hpp.
View newest version in sPHENIX GitHub at line 326 of file BenchmarkTools.hpp
Member Data Documentation
size_t Acts::Test::MicroBenchmarkResult::iters_per_run = 0
Definition at line 186 of file BenchmarkTools.hpp.
View newest version in sPHENIX GitHub at line 186 of file BenchmarkTools.hpp
Referenced by Acts::Test::BOOST_AUTO_TEST_CASE(), iterTimeAverage(), iterTimeError(), and Acts::Test::benchmark_tools_internal::microBenchmarkImpl().
std::vector<Duration> Acts::Test::MicroBenchmarkResult::run_timings
Definition at line 187 of file BenchmarkTools.hpp.
View newest version in sPHENIX GitHub at line 187 of file BenchmarkTools.hpp
Referenced by Acts::Test::BOOST_AUTO_TEST_CASE(), Acts::Test::benchmark_tools_internal::microBenchmarkImpl(), runTimeError(), runTimeMedian(), runTimeQuartiles(), sortedRunTimes(), and totalTime().
The documentation for this struct was generated from the following file:
acts/blob/sPHENIX/Tests/CommonHelpers/Acts/Tests/CommonHelpers/BenchmarkTools.hpp