Analysis Software: OnlMonBase Class Reference
OnlMonBase Class Reference
#include <OnlMon/blob/main/onlmonserver/OnlMonBase.h>
Public Member Functions
OnlMonBase (const std::string &name="NONE")
virtual ~OnlMonBase ()
const std::string Name () const
void Name (const std::string &name)
virtual void Verbosity (const int i)
virtual int Verbosity () const
Protected Attributes
std::string ThisName
int verbosity = 0
Detailed Description
Definition at line 6 of file OnlMonBase.h.
View newest version in sPHENIX GitHub at line 6 of file OnlMonBase.h
Constructor & Destructor Documentation
OnlMonBase::OnlMonBase (const std::string & name = "NONE") explicit
Definition at line 3 of file OnlMonBase.cc.
View newest version in sPHENIX GitHub at line 3 of file OnlMonBase.cc
virtual OnlMonBase::~OnlMonBase () inline virtual
Definition at line 10 of file OnlMonBase.h.
View newest version in sPHENIX GitHub at line 10 of file OnlMonBase.h
Member Function Documentation
const std::string OnlMonBase::Name () const inline
Definition at line 12 of file OnlMonBase.h.
View newest version in sPHENIX GitHub at line 12 of file OnlMonBase.h
References ThisName.
Referenced by OnlMonDBodbc::Dump(), OnlMonDBodbc::Info(), OnlMonServer::LookAtMe(), PktSizeMon::putmapinhisto(), OnlMonServer::registerHisto(), OnlMonServer::registerMonitor(), PktSizeMon::Reset(), OnlMonServer::send_message(), OnlMon::SetMonitorServerId(), OnlMonServer::SetSubsystemRunStatus(), and OnlMonServer::SetSubsystemStatus().
void OnlMonBase::Name (const std::string & name) inline
Definition at line 13 of file OnlMonBase.h.
View newest version in sPHENIX GitHub at line 13 of file OnlMonBase.h
References perf_headwind::name, and ThisName.
virtual void OnlMonBase::Verbosity (const int i) inline virtual
Reimplemented in OnlMonClient.
Definition at line 14 of file OnlMonBase.h.
View newest version in sPHENIX GitHub at line 14 of file OnlMonBase.h
References i, and verbosity.
Referenced by OnlMonDB::DBInit(), handleconnection(), and server().
virtual int OnlMonBase::Verbosity () const inline virtual
Definition at line 15 of file OnlMonBase.h.
View newest version in sPHENIX GitHub at line 15 of file OnlMonBase.h
References verbosity.
Referenced by OnlMonDB::DBInit(), OnlMonClient::FindAllMonitors(), OnlMonClient::FindMonitor(), OnlMonServer::getHisto(), TpotMon::Init(), TpotMon::process_event(), MvtxMon::process_event(), OnlMonClient::registerHisto(), OnlMonClient::requestHistoByName(), OnlMonClient::requestHistoBySubSystem(), OnlMonClient::requestHistoList(), OnlMonClient::requestMonitorList(), OnlMonClient::updateHistoMap(), OnlMonServer::WriteHistoFile(), and OnlMonServer::~OnlMonServer().
Member Data Documentation
std::string OnlMonBase::ThisName protected
Definition at line 18 of file OnlMonBase.h.
View newest version in sPHENIX GitHub at line 18 of file OnlMonBase.h
Referenced by OnlMonDB::DBInit(), OnlMonDB::GetVar(), MyMon::Init(), InttMon::Init(), Name(), OnlMonServer::OnlMonServer(), OnlMonDB::Print(), MessageSystem::send_message(), and OnlMonServer::send_message().
int OnlMonBase::verbosity = 0 protected
Definition at line 19 of file OnlMonBase.h.
View newest version in sPHENIX GitHub at line 19 of file OnlMonBase.h
Referenced by OnlMonClient::CacheRunDB(), OnlMonServer::CacheRunDB(), PktSizeDBodbc::CheckAndCreateTable(), OnlMonDBodbc::CheckAndCreateTable(), OnlMonDBodbc::CreateTable(), MyMon::DBVarInit(), OnlMonClient::DoSomething(), OnlMonClient::EventTime(), OnlMonServer::getHistoName(), PktSizeDBodbc::GetPacketContent(), OnlMonClient::IsMonitorRunning(), PktSizeMon::process_event(), OnlMonClient::ReadHistogramsFromFile(), OnlMonServer::registerHisto(), OnlMonClient::requestHisto(), OnlMonClient::requestHistoByName(), OnlMonClient::requestHistoList(), OnlMonClient::SavePlot(), OnlMonClient::SendCommand(), PktSizeMon::UpdateDB(), OnlMonClient::UpdateServerHistoMap(), Verbosity(), OnlMonClient::Verbosity(), and OnlMonClient::~OnlMonClient().
The documentation for this class was generated from the following files:
OnlMon/blob/main/onlmonserver/OnlMonBase.h
OnlMon/blob/main/onlmonserver/OnlMonBase.cc