Analysis Software: TrackClusEvaluator Class Reference
TrackClusEvaluator Class Reference
#include <coresoftware/blob/master/simulation/g4simulation/g4eval/TrackClusEvaluator.h>
Public Member Functions
TrackClusEvaluator (TrkrClusterIsMatcher *_=nullptr)
TrkrClusterContainer * get_PHG4_clusters ()
TrkrClusterContainer * get_SVTX_clusters ()
void reset ()
std::array< int, 3 > find_matches ()
std::array< int, 3 > find_matches (TrkrTruthTrack *g4_track, SvtxTrack *sv_track)
int phg4_n_matched ()
int svtx_n_matched ()
int phg4_nclus ()
int svtx_nclus ()
int addClusKeys (SvtxTrack *)
int addClusKeys (TrkrTruthTrack *)
std::array< int, 5 > svtx_cntclus ()
std::array< int, 5 > phg4_cntclus ()
std::array< int, 5 > svtx_cnt_matchedclus ()
std::array< int, 5 > phg4_cnt_matchedclus ()
std::vector< TrkrClusLoc > phg4_clusloc_all ()
std::vector< TrkrClusLoc > phg4_clusloc_unmatched ()
std::vector< TrkrClusLoc > svtx_clusloc_all ()
std::vector< TrkrClusLoc > svtx_clusloc_unmatched ()
std::vector< TrkrClusLoc > clusloc_matched ()
Public Attributes
TrkrClusterIsMatcher * ismatcher {nullptr}
Vector svtx_keys {}
Vector phg4_keys {}
bool collect_match_statistic = false
double match_stat {0}
std::vector< bool > svtx_matches
std::vector< bool > phg4_matches
Private Types
using Vector = std::vector< std::pair< TrkrDefs::hitsetkey, TrkrDefs::cluskey >>
using Iter = Vector::iterator
Private Member Functions
std::array< int, 5 > cntclus (Vector &keys)
std::array< int, 5 > cnt_matchedclus (Vector &keys, std::vector< bool > &matches)
Detailed Description
Definition at line 16 of file TrackClusEvaluator.h.
View newest version in sPHENIX GitHub at line 16 of file TrackClusEvaluator.h
Member Typedef Documentation
using TrackClusEvaluator::Iter = Vector::iterator private
Definition at line 20 of file TrackClusEvaluator.h.
View newest version in sPHENIX GitHub at line 20 of file TrackClusEvaluator.h
using TrackClusEvaluator::Vector = std::vector<std::pair<TrkrDefs::hitsetkey,TrkrDefs::cluskey>> private
Definition at line 18 of file TrackClusEvaluator.h.
View newest version in sPHENIX GitHub at line 18 of file TrackClusEvaluator.h
Constructor & Destructor Documentation
TrackClusEvaluator::TrackClusEvaluator (TrkrClusterIsMatcher * _ = nullptr) inline
Definition at line 31 of file TrackClusEvaluator.h.
View newest version in sPHENIX GitHub at line 31 of file TrackClusEvaluator.h
References _.
Member Function Documentation
int TrackClusEvaluator::addClusKeys (SvtxTrack * track)
Definition at line 31 of file TrackClusEvaluator.cc.
View newest version in sPHENIX GitHub at line 31 of file TrackClusEvaluator.cc
References TrkrDefs::getHitSetKeyFromClusKey(), Acts::Experimental::detail::BlueprintHelper::sort(), and svtx_keys.
Referenced by find_matches().
int TrackClusEvaluator::addClusKeys (TrkrTruthTrack * track)
Definition at line 58 of file TrackClusEvaluator.cc.
View newest version in sPHENIX GitHub at line 58 of file TrackClusEvaluator.cc
References TrkrTruthTrack::getClusters(), TrkrDefs::getHitSetKeyFromClusKey(), phg4_keys, and Acts::Experimental::detail::BlueprintHelper::sort().
std::vector< TrkrClusLoc > TrackClusEvaluator::clusloc_matched ()
Definition at line 184 of file TrackClusEvaluator.cc.
View newest version in sPHENIX GitHub at line 184 of file TrackClusEvaluator.cc
References g4evalfn::clusloc_PHG4(), i, ismatcher, phg4_keys, phg4_matches, and vec.
std::array< int, 5 > TrackClusEvaluator::cnt_matchedclus (Vector & keys, std::vector< bool > & matches) private
Definition at line 41 of file TrackClusEvaluator.cc.
View newest version in sPHENIX GitHub at line 41 of file TrackClusEvaluator.cc
References i, PHWHERE, and g4evalfn::trklayer_det().
Referenced by phg4_cnt_matchedclus(), and svtx_cnt_matchedclus().
std::array< int, 5 > TrackClusEvaluator::cntclus (Vector & keys) private
Definition at line 22 of file TrackClusEvaluator.cc.
View newest version in sPHENIX GitHub at line 22 of file TrackClusEvaluator.cc
References i, it, and g4evalfn::trklayer_det().
Referenced by phg4_cntclus(), and svtx_cntclus().
std::array< int, 3 > TrackClusEvaluator::find_matches ()
Definition at line 74 of file TrackClusEvaluator.cc.
View newest version in sPHENIX GitHub at line 74 of file TrackClusEvaluator.cc
References g4evalfn::calc_match_statistic(), collect_match_statistic, ismatcher, match_stat, phg4_keys, phg4_matches, PHWHERE, svtx_keys, and svtx_matches.
Referenced by find_matches().
std::array< int, 3 > TrackClusEvaluator::find_matches (TrkrTruthTrack * g4_track, SvtxTrack * sv_track)
Definition at line 142 of file TrackClusEvaluator.cc.
View newest version in sPHENIX GitHub at line 142 of file TrackClusEvaluator.cc
References addClusKeys(), and find_matches().
TrkrClusterContainer * TrackClusEvaluator::get_PHG4_clusters ()
Definition at line 12 of file TrackClusEvaluator.cc.
View newest version in sPHENIX GitHub at line 12 of file TrackClusEvaluator.cc
References ismatcher, and TrkrClusterIsMatcher::m_TruthClusters.
TrkrClusterContainer * TrackClusEvaluator::get_SVTX_clusters ()
Definition at line 17 of file TrackClusEvaluator.cc.
View newest version in sPHENIX GitHub at line 17 of file TrackClusEvaluator.cc
References ismatcher, and TrkrClusterIsMatcher::m_RecoClusters.
std::vector< TrkrClusLoc > TrackClusEvaluator::phg4_clusloc_all ()
Definition at line 154 of file TrackClusEvaluator.cc.
View newest version in sPHENIX GitHub at line 154 of file TrackClusEvaluator.cc
References g4evalfn::clusloc_PHG4(), ismatcher, phg4_keys, and vec.
std::vector< TrkrClusLoc > TrackClusEvaluator::phg4_clusloc_unmatched ()
Definition at line 160 of file TrackClusEvaluator.cc.
View newest version in sPHENIX GitHub at line 160 of file TrackClusEvaluator.cc
References g4evalfn::clusloc_PHG4(), i, ismatcher, phg4_keys, phg4_matches, and vec.
std::array<int,5> TrackClusEvaluator::phg4_cnt_matchedclus () inline
Definition at line 63 of file TrackClusEvaluator.h.
View newest version in sPHENIX GitHub at line 63 of file TrackClusEvaluator.h
References cnt_matchedclus(), phg4_keys, and phg4_matches.
std::array<int,5> TrackClusEvaluator::phg4_cntclus () inline
Definition at line 60 of file TrackClusEvaluator.h.
View newest version in sPHENIX GitHub at line 60 of file TrackClusEvaluator.h
References cntclus(), and phg4_keys.
int TrackClusEvaluator::phg4_n_matched ()
Definition at line 148 of file TrackClusEvaluator.cc.
View newest version in sPHENIX GitHub at line 148 of file TrackClusEvaluator.cc
References phg4_matches.
int TrackClusEvaluator::phg4_nclus () inline
Definition at line 50 of file TrackClusEvaluator.h.
View newest version in sPHENIX GitHub at line 50 of file TrackClusEvaluator.h
References phg4_keys.
void TrackClusEvaluator::reset ()
Definition at line 67 of file TrackClusEvaluator.cc.
View newest version in sPHENIX GitHub at line 67 of file TrackClusEvaluator.cc
References phg4_keys, phg4_matches, svtx_keys, and svtx_matches.
std::vector< TrkrClusLoc > TrackClusEvaluator::svtx_clusloc_all ()
Definition at line 169 of file TrackClusEvaluator.cc.
View newest version in sPHENIX GitHub at line 169 of file TrackClusEvaluator.cc
References g4evalfn::clusloc_SVTX(), ismatcher, svtx_keys, and vec.
std::vector< TrkrClusLoc > TrackClusEvaluator::svtx_clusloc_unmatched ()
Definition at line 175 of file TrackClusEvaluator.cc.
View newest version in sPHENIX GitHub at line 175 of file TrackClusEvaluator.cc
References g4evalfn::clusloc_SVTX(), i, ismatcher, svtx_keys, svtx_matches, and vec.
std::array<int,5> TrackClusEvaluator::svtx_cnt_matchedclus () inline
Definition at line 62 of file TrackClusEvaluator.h.
View newest version in sPHENIX GitHub at line 62 of file TrackClusEvaluator.h
References cnt_matchedclus(), svtx_keys, and svtx_matches.
std::array<int,5> TrackClusEvaluator::svtx_cntclus () inline
Definition at line 59 of file TrackClusEvaluator.h.
View newest version in sPHENIX GitHub at line 59 of file TrackClusEvaluator.h
References cntclus(), and svtx_keys.
int TrackClusEvaluator::svtx_n_matched ()
Definition at line 151 of file TrackClusEvaluator.cc.
View newest version in sPHENIX GitHub at line 151 of file TrackClusEvaluator.cc
References svtx_matches.
int TrackClusEvaluator::svtx_nclus () inline
Definition at line 51 of file TrackClusEvaluator.h.
View newest version in sPHENIX GitHub at line 51 of file TrackClusEvaluator.h
References svtx_keys.
Member Data Documentation
bool TrackClusEvaluator::collect_match_statistic = false
Definition at line 39 of file TrackClusEvaluator.h.
View newest version in sPHENIX GitHub at line 39 of file TrackClusEvaluator.h
Referenced by find_matches().
TrkrClusterIsMatcher* TrackClusEvaluator::ismatcher {nullptr}
Definition at line 29 of file TrackClusEvaluator.h.
View newest version in sPHENIX GitHub at line 29 of file TrackClusEvaluator.h
Referenced by clusloc_matched(), find_matches(), get_PHG4_clusters(), get_SVTX_clusters(), phg4_clusloc_all(), phg4_clusloc_unmatched(), svtx_clusloc_all(), and svtx_clusloc_unmatched().
double TrackClusEvaluator::match_stat {0}
Definition at line 40 of file TrackClusEvaluator.h.
View newest version in sPHENIX GitHub at line 40 of file TrackClusEvaluator.h
Referenced by find_matches().
Vector TrackClusEvaluator::phg4_keys {}
Definition at line 37 of file TrackClusEvaluator.h.
View newest version in sPHENIX GitHub at line 37 of file TrackClusEvaluator.h
Referenced by addClusKeys(), clusloc_matched(), find_matches(), phg4_clusloc_all(), phg4_clusloc_unmatched(), phg4_cnt_matchedclus(), phg4_cntclus(), phg4_nclus(), and reset().
std::vector<bool> TrackClusEvaluator::phg4_matches
Definition at line 54 of file TrackClusEvaluator.h.
View newest version in sPHENIX GitHub at line 54 of file TrackClusEvaluator.h
Referenced by clusloc_matched(), find_matches(), phg4_clusloc_unmatched(), phg4_cnt_matchedclus(), phg4_n_matched(), and reset().
Vector TrackClusEvaluator::svtx_keys {}
Definition at line 36 of file TrackClusEvaluator.h.
View newest version in sPHENIX GitHub at line 36 of file TrackClusEvaluator.h
Referenced by addClusKeys(), find_matches(), reset(), svtx_clusloc_all(), svtx_clusloc_unmatched(), svtx_cnt_matchedclus(), svtx_cntclus(), and svtx_nclus().
std::vector<bool> TrackClusEvaluator::svtx_matches
Definition at line 53 of file TrackClusEvaluator.h.
View newest version in sPHENIX GitHub at line 53 of file TrackClusEvaluator.h
Referenced by find_matches(), reset(), svtx_clusloc_unmatched(), svtx_cnt_matchedclus(), and svtx_n_matched().
The documentation for this class was generated from the following files:
coresoftware/blob/master/simulation/g4simulation/g4eval/TrackClusEvaluator.h
coresoftware/blob/master/simulation/g4simulation/g4eval/TrackClusEvaluator.cc