Analysis Software: AlignmentDefs Namespace Reference
AlignmentDefs Namespace Reference
Enumerations
enum mvtxGrp { snsr, stv, mvtxlyr, clamshl }
enum inttGrp { chp, lad, inttlyr, inttbrl }
enum tpcGrp { htst, sctr, tp }
enum mmsGrp { tl, mm }
Functions
int getTpcRegion (int layer)
void getMvtxGlobalLabels (Surface surf, int glbl_label[], mvtxGrp grp)
void getInttGlobalLabels (Surface surf, int glbl_label[], inttGrp grp)
void getTpcGlobalLabels (Surface surf, TrkrDefs::cluskey cluskey, int glbl_label[], tpcGrp grp)
void getMMGlobalLabels (Surface surf, int glbl_label[], mmsGrp grp)
int getMvtxClamshell (int layer, int stave)
std::vector< int > getAllMvtxGlobalLabels (int grp)
std::vector< int > getAllInttGlobalLabels (int grp)
std::vector< int > getAllTpcGlobalLabels (int grp)
std::vector< int > makeLabelsFromBase (std::vector< int > &label_base)
int getLabelBase (Acts::GeometryIdentifier id, TrkrDefs::cluskey cluskey, int group)
void printBuffers (int index, Acts::Vector2 residual, Acts::Vector2 clus_sigma, float lcl_derivative[], float glbl_derivative[], int glbl_label[])
Variables
static constexpr int NGLVTX = 3
static constexpr int NGL = 6
static constexpr int NLC = 5
static const std::map
< unsigned int, unsigned int > base_layer_map = {{10, 0}, {12, 3}, {14, 7}, {16, 55}}
Map relating Acts::VolumeID to sPHENIX layer.
static constexpr int nsensors_stave [7] = {9, 9, 9, 4, 4, 4, 4}
static constexpr int nstaves_layer_intt [4] = {12, 12, 16, 16}
static constexpr int nstaves_layer_mvtx [3] = {12, 16, 20}
static constexpr int clamshell_stave_list [3][2][10]
static constexpr int glbl_vtx_label [NGLVTX] = {60000000,60000001,60000002}
Enumeration Type Documentation
enum AlignmentDefs::inttGrp
Enumerator:
chp
lad
inttlyr
inttbrl
Definition at line 17 of file AlignmentDefs.h.
View newest version in sPHENIX GitHub at line 17 of file AlignmentDefs.h
enum AlignmentDefs::mmsGrp
Enumerator:
tl
mm
Definition at line 31 of file AlignmentDefs.h.
View newest version in sPHENIX GitHub at line 31 of file AlignmentDefs.h
enum AlignmentDefs::mvtxGrp
Enumerator:
snsr
stv
mvtxlyr
clamshl
Definition at line 9 of file AlignmentDefs.h.
View newest version in sPHENIX GitHub at line 9 of file AlignmentDefs.h
enum AlignmentDefs::tpcGrp
Enumerator:
htst
sctr
tp
Definition at line 25 of file AlignmentDefs.h.
View newest version in sPHENIX GitHub at line 25 of file AlignmentDefs.h
Function Documentation
std::vector< int > AlignmentDefs::getAllInttGlobalLabels (int grp)
Definition at line 344 of file AlignmentDefs.cc.
View newest version in sPHENIX GitHub at line 344 of file AlignmentDefs.cc
References chp, inttbrl, inttlyr, CKF_timing_vs_mu::label, lad, makeLabelsFromBase(), nsensors_stave, and nstaves_layer_intt.
std::vector< int > AlignmentDefs::getAllMvtxGlobalLabels (int grp)
Definition at line 290 of file AlignmentDefs.cc.
View newest version in sPHENIX GitHub at line 290 of file AlignmentDefs.cc
References clamshl, CKF_timing_vs_mu::label, makeLabelsFromBase(), mvtxlyr, nsensors_stave, nstaves_layer_mvtx, snsr, and stv.
std::vector< int > AlignmentDefs::getAllTpcGlobalLabels (int grp)
Definition at line 392 of file AlignmentDefs.cc.
View newest version in sPHENIX GitHub at line 392 of file AlignmentDefs.cc
References CKF_timing_vs_mu::label, makeLabelsFromBase(), and sctr.
void AlignmentDefs::getInttGlobalLabels (Surface surf, int glbl_label[], AlignmentDefs::inttGrp grp)
Definition at line 32 of file AlignmentDefs.cc.
View newest version in sPHENIX GitHub at line 32 of file AlignmentDefs.cc
References chp, getLabelBase(), upload::group, i, inttbrl, inttlyr, lad, and NGL.
Referenced by MakeMilleFiles::addTrackToMilleFile(), and HelicalFitter::process_event().
int AlignmentDefs::getLabelBase (Acts::GeometryIdentifier id, TrkrDefs::cluskey cluskey, int group)
Definition at line 131 of file AlignmentDefs.cc.
View newest version in sPHENIX GitHub at line 131 of file AlignmentDefs.cc
References base_layer_map, getMvtxClamshell(), TpcDefs::getSectorId(), TpcDefs::getSide(), getTpcRegion(), layer, nsensors_stave, nstaves_layer_intt, nstaves_layer_mvtx, and tile().
Referenced by getInttGlobalLabels(), getMMGlobalLabels(), getMvtxGlobalLabels(), and getTpcGlobalLabels().
void AlignmentDefs::getMMGlobalLabels (Surface surf, int glbl_label[], AlignmentDefs::mmsGrp grp)
Definition at line 82 of file AlignmentDefs.cc.
View newest version in sPHENIX GitHub at line 82 of file AlignmentDefs.cc
References getLabelBase(), upload::group, i, Acts::UnitConstants::mm, NGL, and tl.
Referenced by MakeMilleFiles::addTrackToMilleFile().
int AlignmentDefs::getMvtxClamshell (int layer, int stave)
Definition at line 114 of file AlignmentDefs.cc.
View newest version in sPHENIX GitHub at line 114 of file AlignmentDefs.cc
References clamshell_stave_list, layer, and nstaves_layer_mvtx.
Referenced by MakeMilleFiles::addTrackToMilleFile(), getLabelBase(), and HelicalFitter::process_event().
void AlignmentDefs::getMvtxGlobalLabels (Surface surf, int glbl_label[], AlignmentDefs::mvtxGrp grp)
Definition at line 4 of file AlignmentDefs.cc.
View newest version in sPHENIX GitHub at line 4 of file AlignmentDefs.cc
References clamshl, getLabelBase(), upload::group, i, mvtxlyr, NGL, snsr, and stv.
Referenced by MakeMilleFiles::addTrackToMilleFile(), and HelicalFitter::process_event().
void AlignmentDefs::getTpcGlobalLabels (Surface surf, TrkrDefs::cluskey cluskey, int glbl_label[], AlignmentDefs::tpcGrp grp)
Definition at line 59 of file AlignmentDefs.cc.
View newest version in sPHENIX GitHub at line 59 of file AlignmentDefs.cc
References getLabelBase(), upload::group, htst, i, NGL, sctr, and physmon_simulation::tp.
Referenced by MakeMilleFiles::addTrackToMilleFile(), and HelicalFitter::process_event().
int AlignmentDefs::getTpcRegion (int layer)
Definition at line 103 of file AlignmentDefs.cc.
View newest version in sPHENIX GitHub at line 103 of file AlignmentDefs.cc
Referenced by getLabelBase(), MakeMilleFiles::is_tpc_sector_fixed(), and HelicalFitter::is_tpc_sector_fixed().
std::vector< int > AlignmentDefs::makeLabelsFromBase (std::vector< int > & label_base)
Definition at line 410 of file AlignmentDefs.cc.
View newest version in sPHENIX GitHub at line 410 of file AlignmentDefs.cc
Referenced by getAllInttGlobalLabels(), getAllMvtxGlobalLabels(), and getAllTpcGlobalLabels().
void AlignmentDefs::printBuffers (int index, Acts::Vector2 residual, Acts::Vector2 clus_sigma, float lcl_derivative[], float glbl_derivative[], int glbl_label[])
Definition at line 425 of file AlignmentDefs.cc.
View newest version in sPHENIX GitHub at line 425 of file AlignmentDefs.cc
References NGL, and NLC.
Referenced by MakeMilleFiles::addTrackToMilleFile().
Variable Documentation
const std::map<unsigned int, unsigned int> AlignmentDefs::base_layer_map = {{10, 0}, {12, 3}, {14, 7}, {16, 55}} static
Map relating Acts::VolumeID to sPHENIX layer.
Definition at line 42 of file AlignmentDefs.h.
View newest version in sPHENIX GitHub at line 42 of file AlignmentDefs.h
Referenced by getLabelBase().
constexpr int AlignmentDefs::clamshell_stave_list[3][2][10] static
Initial value:
= {
    {{3,4,5,6,7,8,0,0,0,0},
     {0,1,2,9,10,11,0,0,0,0}},
    {{4,5,6,7,8,9,10,11,0,0},
     {0,1,2,3,12,13,14,15,0,0}},
    {{5,6,7,8,9,10,11,12,13,14},
     {0,1,2,3,4,15,16,17,18,19 }} }
Definition at line 47 of file AlignmentDefs.h.
View newest version in sPHENIX GitHub at line 47 of file AlignmentDefs.h
Referenced by getMvtxClamshell().
constexpr int AlignmentDefs::glbl_vtx_label[NGLVTX] = {60000000,60000001,60000002} static
Definition at line 55 of file AlignmentDefs.h.
View newest version in sPHENIX GitHub at line 55 of file AlignmentDefs.h
Referenced by MakeMilleFiles::InitRun(), MakeMilleFiles::process_event(), and HelicalFitter::process_event().
constexpr int AlignmentDefs::NGL = 6 static
Definition at line 38 of file AlignmentDefs.h.
View newest version in sPHENIX GitHub at line 38 of file AlignmentDefs.h
Referenced by getInttGlobalLabels(), getMMGlobalLabels(), getMvtxGlobalLabels(), getTpcGlobalLabels(), Mille::mille(), printBuffers(), and HelicalFitter::process_event().
constexpr int AlignmentDefs::NGLVTX = 3 static
Definition at line 37 of file AlignmentDefs.h.
View newest version in sPHENIX GitHub at line 37 of file AlignmentDefs.h
Referenced by MakeMilleFiles::InitRun(), MakeMilleFiles::process_event(), and HelicalFitter::process_event().
constexpr int AlignmentDefs::NLC = 5 static
Definition at line 39 of file AlignmentDefs.h.
View newest version in sPHENIX GitHub at line 39 of file AlignmentDefs.h
Referenced by Mille::mille(), printBuffers(), and HelicalFitter::process_event().
constexpr int AlignmentDefs::nsensors_stave[7] = {9, 9, 9, 4, 4, 4, 4} static
Definition at line 43 of file AlignmentDefs.h.
View newest version in sPHENIX GitHub at line 43 of file AlignmentDefs.h
Referenced by getAllInttGlobalLabels(), getAllMvtxGlobalLabels(), and getLabelBase().
constexpr int AlignmentDefs::nstaves_layer_intt[4] = {12, 12, 16, 16} static
Definition at line 44 of file AlignmentDefs.h.
View newest version in sPHENIX GitHub at line 44 of file AlignmentDefs.h
Referenced by getAllInttGlobalLabels(), and getLabelBase().
constexpr int AlignmentDefs::nstaves_layer_mvtx[3] = {12, 16, 20} static
Definition at line 45 of file AlignmentDefs.h.
View newest version in sPHENIX GitHub at line 45 of file AlignmentDefs.h
Referenced by getAllMvtxGlobalLabels(), getLabelBase(), and getMvtxClamshell().