Analysis Software: Cell Class Reference
Cell Class Reference
#include <JETSCAPE/blob/main/jail/vhlle/src/cll.h>
Public Member Functions
Cell ()
~Cell ()
void setPos (int iix, int iiy, int iiz)
int getX (void)
int getY (void)
int getZ (void)
void setQ (double *_Q)
void setQh (double *_Qh)
double getpi (const int &i, const int &j)
double getpiH (const int &i, const int &j)
double getpi0 (const int &i, const int &j)
double getpiH0 (const int &i, const int &j)
double getPi (void)
double getPiH (void)
double getPi0 (void)
double getPiH0 (void)
void setpi (const int &i, const int &j, const double &val)
void setpiH (const int &i, const int &j, const double &val)
void setpi0 (const int &i, const int &j, const double &val)
void setpiH0 (const int &i, const int &j, const double &val)
void addpi0 (const int &i, const int &j, const double &val)
void addpiH0 (const int &i, const int &j, const double &val)
void setPi (const double &val)
void setPiH (const double &val)
void setPi0 (const double &val)
void setPiH0 (const double &val)
void addPi0 (const double &val)
void addPiH0 (const double &val)
void getQ (double *_Q)
void getQh (double *_Qh)
void saveQprev (void)
void setNext (int i, Cell *c)
void setPrev (int i, Cell *c)
Cell * getNext (int i)
Cell * getPrev (int i)
void setAllM (double value)
void addM (int dir, double inc)
double getM (int dir)
double getMaxM (void)
void setDM (int dir, double value)
double getDM (int dir)
void setpi0 (double values[4][4])
void setpiH0 (double values[4][4])
void getPrimVar (EoS *eos, double tau, double &_e, double &_p, double &_nb, double &_nq, double &_ns, double &_vx, double &_vy, double &_vz)
void getPrimVarLeft (EoS *eos, double tau, double &_e, double &_p, double &_nb, double &_nq, double &_ns, double &_vx, double &_vy, double &_vz, int dir)
void getPrimVarRight (EoS *eos, double tau, double &_e, double &_p, double &_nb, double &_nq, double &_ns, double &_vx, double &_vy, double &_vz, int dir)
void getPrimVarHLeft (EoS *eos, double tau, double &_e, double &_p, double &_nb, double &_nq, double &_ns, double &_vx, double &_vy, double &_vz, int dir)
void getPrimVarHRight (EoS *eos, double tau, double &_e, double &_p, double &_nb, double &_nq, double &_ns, double &_vx, double &_vy, double &_vz, int dir)
void getPrimVarHCenter (EoS *eos, double tau, double &_e, double &_p, double &_nb, double &_nq, double &_ns, double &_vx, double &_vy, double &_vz)
void getPrimVarPrev (EoS *eos, double tau, double &_e, double &_p, double &_nb, double &_nq, double &_ns, double &_vx, double &_vy, double &_vz)
void setPrimVar (EoS *eos, double tau, double _e, double _nb, double _nq, double _ns, double _vx, double _vy, double _vz)
void addFlux (double Ft, double Fx, double Fy, double Fz, double Fnb, double Fnq, double Fns)
void clearFlux (void)
void updateByFlux ()
void updateQtoQhByFlux ()
void setViscCorrCutFlag (double value)
double getViscCorrCutFlag (void)
void Dump (double tau)
Private Attributes
double Q [7]
double Qh [7]
double Qprev [7]
double pi [10]
double piH [10]
double Pi
double PiH
double pi0 [10]
double piH0 [10]
double Pi0
double PiH0
double flux [7]
Cell * next [3]
Cell * prev [3]
double m [3]
double dm [3]
int ix
int iy
int iz
double viscCorrCut
Detailed Description
Definition at line 29 of file cll.h.
View newest version in sPHENIX GitHub at line 29 of file cll.h
Constructor & Destructor Documentation
Cell::Cell ()
Definition at line 32 of file cll.cpp.
View newest version in sPHENIX GitHub at line 32 of file cll.cpp
References i, pi, and Q().
Cell::~Cell () inline
Definition at line 54 of file cll.h.
View newest version in sPHENIX GitHub at line 54 of file cll.h
Member Function Documentation
void Cell::addFlux (double Ft, double Fx, double Fy, double Fz, double Fnb, double Fnq, double Fns) inline
Definition at line 189 of file cll.h.
View newest version in sPHENIX GitHub at line 189 of file cll.h
References flux, NB_, NQ_, NS_, T_, X_, Y_, and Z_.
Referenced by Hydro::hlle_flux(), Hydro::ISformal(), Hydro::source_step(), Hydro::visc_flux(), and Hydro::visc_source_step().
void Cell::addM (int dir, double inc) inline
Definition at line 133 of file cll.h.
View newest version in sPHENIX GitHub at line 133 of file cll.h
References i, and m.
Referenced by Fluid::updateM().
void Cell::addpi0 (const int & i, const int & j, const double & val) inline
Definition at line 105 of file cll.h.
View newest version in sPHENIX GitHub at line 105 of file cll.h
References index44(), and pi0.
Referenced by Hydro::ISformal().
void Cell::addPi0 (const double & val) inline
Definition at line 115 of file cll.h.
View newest version in sPHENIX GitHub at line 115 of file cll.h
References Pi0.
Referenced by Hydro::ISformal().
void Cell::addpiH0 (const int & i, const int & j, const double & val) inline
Definition at line 108 of file cll.h.
View newest version in sPHENIX GitHub at line 108 of file cll.h
References index44(), and piH0.
Referenced by Hydro::ISformal().
void Cell::addPiH0 (const double & val) inline
Definition at line 116 of file cll.h.
View newest version in sPHENIX GitHub at line 116 of file cll.h
References PiH0.
Referenced by Hydro::ISformal().
void Cell::clearFlux (void) inline
Definition at line 199 of file cll.h.
View newest version in sPHENIX GitHub at line 199 of file cll.h
References flux, and i.
Referenced by Hydro::performStep().
void Cell::Dump (double tau)
Definition at line 213 of file cll.cpp.
View newest version in sPHENIX GitHub at line 213 of file cll.cpp
References Q().
Referenced by Hydro::hlle_flux().
double Cell::getDM (int dir) inline
Definition at line 141 of file cll.h.
View newest version in sPHENIX GitHub at line 141 of file cll.h
References dm.
Referenced by Fluid::updateM().
double Cell::getM (int dir) inline
Definition at line 138 of file cll.h.
View newest version in sPHENIX GitHub at line 138 of file cll.h
References m.
Referenced by Hydro::hlle_flux(), and Hydro::visc_flux().
double Cell::getMaxM (void) inline
Definition at line 139 of file cll.h.
View newest version in sPHENIX GitHub at line 139 of file cll.h
References m.
Referenced by Hydro::NSquant().
Cell* Cell::getNext (int i) inline
Definition at line 129 of file cll.h.
View newest version in sPHENIX GitHub at line 129 of file cll.h
References next.
Referenced by Hydro::NSquant().
double Cell::getpi (const int & i, const int & j) inline
Definition at line 78 of file cll.h.
View newest version in sPHENIX GitHub at line 78 of file cll.h
References index44(), and pi.
Referenced by Fluid::calcTotals(), getvischlle_(), Hydro::ISformal(), and Fluid::outputGnuplot().
double Cell::getPi (void) inline
Definition at line 88 of file cll.h.
View newest version in sPHENIX GitHub at line 88 of file cll.h
References Pi.
Referenced by getvischlle_(), Hydro::ISformal(), and Fluid::outputGnuplot().
double Cell::getpi0 (const int & i, const int & j) inline
Definition at line 82 of file cll.h.
View newest version in sPHENIX GitHub at line 82 of file cll.h
References index44(), and pi0.
Referenced by Hydro::ISformal().
double Cell::getPi0 (void) inline
Definition at line 90 of file cll.h.
View newest version in sPHENIX GitHub at line 90 of file cll.h
References Pi0.
Referenced by Hydro::ISformal().
double Cell::getpiH (const int & i, const int & j) inline
Definition at line 79 of file cll.h.
View newest version in sPHENIX GitHub at line 79 of file cll.h
References index44(), and piH.
Referenced by Hydro::visc_flux(), and Hydro::visc_source_step().
double Cell::getPiH (void) inline
Definition at line 89 of file cll.h.
View newest version in sPHENIX GitHub at line 89 of file cll.h
References PiH.
Referenced by Hydro::visc_flux(), and Hydro::visc_source_step().
double Cell::getpiH0 (const int & i, const int & j) inline
Definition at line 85 of file cll.h.
View newest version in sPHENIX GitHub at line 85 of file cll.h
References index44(), and piH0.
Referenced by Hydro::ISformal().
double Cell::getPiH0 (void) inline
Definition at line 91 of file cll.h.
View newest version in sPHENIX GitHub at line 91 of file cll.h
References PiH0.
Referenced by Hydro::ISformal().
Cell* Cell::getPrev (int i) inline
Definition at line 130 of file cll.h.
View newest version in sPHENIX GitHub at line 130 of file cll.h
References prev.
Referenced by Hydro::NSquant().
void Cell::getPrimVar (EoS * eos, double tau, double & _e, double & _p, double & _nb, double & _nq, double & _ns, double & _vx, double & _vy, double & _vz)
Definition at line 61 of file cll.cpp.
View newest version in sPHENIX GitHub at line 61 of file cll.cpp
References i, Q(), and transformPV().
Referenced by Fluid::getCMFvariables(), getenergyhlle_(), getvalueshlle_(), Hydro::NSquant(), Hydro::setNSvalues(), and Hydro::source_step().
void Cell::getPrimVarHCenter (EoS * eos, double tau, double & _e, double & _p, double & _nb, double & _nq, double & _ns, double & _vx, double & _vy, double & _vz)
Definition at line 175 of file cll.cpp.
View newest version in sPHENIX GitHub at line 175 of file cll.cpp
References i, and transformPV().
Referenced by Hydro::ISformal(), Hydro::NSquant(), Hydro::source_step(), Hydro::visc_flux(), and Hydro::visc_source_step().
void Cell::getPrimVarHLeft (EoS * eos, double tau, double & _e, double & _p, double & _nb, double & _nq, double & _ns, double & _vx, double & _vy, double & _vz, int dir)
Definition at line 125 of file cll.cpp.
View newest version in sPHENIX GitHub at line 125 of file cll.cpp
References i, minmod(), next, tau, and transformPV().
Referenced by Hydro::hlle_flux().
void Cell::getPrimVarHRight (EoS * eos, double tau, double & _e, double & _p, double & _nb, double & _nq, double & _ns, double & _vx, double & _vy, double & _vz, int dir)
Definition at line 150 of file cll.cpp.
View newest version in sPHENIX GitHub at line 150 of file cll.cpp
References i, minmod(), next, tau, and transformPV().
Referenced by Hydro::hlle_flux().
void Cell::getPrimVarLeft (EoS * eos, double tau, double & _e, double & _p, double & _nb, double & _nq, double & _ns, double & _vx, double & _vy, double & _vz, int dir)
Definition at line 75 of file cll.cpp.
View newest version in sPHENIX GitHub at line 75 of file cll.cpp
References i, minmod(), next, Q(), tau, and transformPV().
Referenced by Hydro::hlle_flux().
void Cell::getPrimVarPrev (EoS * eos, double tau, double & _e, double & _p, double & _nb, double & _nq, double & _ns, double & _vx, double & _vy, double & _vz)
Definition at line 183 of file cll.cpp.
View newest version in sPHENIX GitHub at line 183 of file cll.cpp
References i, and transformPV().
Referenced by Hydro::NSquant().
void Cell::getPrimVarRight (EoS * eos, double tau, double & _e, double & _p, double & _nb, double & _nq, double & _ns, double & _vx, double & _vy, double & _vz, int dir)
Definition at line 100 of file cll.cpp.
View newest version in sPHENIX GitHub at line 100 of file cll.cpp
References i, minmod(), next, Q(), tau, and transformPV().
Referenced by Hydro::hlle_flux().
void Cell::getQ (double * _Q) inline
Definition at line 118 of file cll.h.
View newest version in sPHENIX GitHub at line 118 of file cll.h
References i, and Q.
Referenced by Fluid::calcTotals().
void Cell::getQh (double * _Qh) inline
Definition at line 121 of file cll.h.
View newest version in sPHENIX GitHub at line 121 of file cll.h
References i, and Qh.
double Cell::getViscCorrCutFlag (void) inline
Definition at line 205 of file cll.h.
View newest version in sPHENIX GitHub at line 205 of file cll.h
References viscCorrCut.
Referenced by getvalueshlle_(), getvflaghlle_(), and Fluid::outputGnuplot().
int Cell::getX (void) inline
Definition at line 60 of file cll.h.
View newest version in sPHENIX GitHub at line 60 of file cll.h
References ix.
int Cell::getY (void) inline
Definition at line 61 of file cll.h.
View newest version in sPHENIX GitHub at line 61 of file cll.h
References iy.
int Cell::getZ (void) inline
Definition at line 62 of file cll.h.
View newest version in sPHENIX GitHub at line 62 of file cll.h
References iz.
Referenced by Fluid::getCMFvariables().
void Cell::saveQprev (void) inline
Definition at line 124 of file cll.h.
View newest version in sPHENIX GitHub at line 124 of file cll.h
References i, Q, and Qprev.
Referenced by icsethlle_(), Hydro::performStep(), ICGubser::setIC(), IC::setIC(), and ICGlauber::setIC().
void Cell::setAllM (double value) inline
Definition at line 132 of file cll.h.
View newest version in sPHENIX GitHub at line 132 of file cll.h
References m, and value.
Referenced by icsethlle_(), ICGubser::setIC(), IC::setIC(), and ICGlauber::setIC().
void Cell::setDM (int dir, double value) inline
Definition at line 140 of file cll.h.
View newest version in sPHENIX GitHub at line 140 of file cll.h
References dm, and value.
Referenced by Fluid::updateM().
void Cell::setNext (int i, Cell * c) inline
Definition at line 127 of file cll.h.
View newest version in sPHENIX GitHub at line 127 of file cll.h
References Acts::PhysicalConstants::c, and next.
void Cell::setpi (const int & i, const int & j, const double & val) inline
Definition at line 93 of file cll.h.
View newest version in sPHENIX GitHub at line 93 of file cll.h
References index44(), and pi.
Referenced by Hydro::ISformal(), and Hydro::setNSvalues().
void Cell::setPi (const double & val) inline
Definition at line 111 of file cll.h.
View newest version in sPHENIX GitHub at line 111 of file cll.h
References Pi.
Referenced by Hydro::ISformal(), and Hydro::setNSvalues().
void Cell::setpi0 (const int & i, const int & j, const double & val) inline
Definition at line 99 of file cll.h.
View newest version in sPHENIX GitHub at line 99 of file cll.h
References index44(), and pi0.
Referenced by Hydro::ISformal().
void Cell::setPi0 (const double & val) inline
Definition at line 113 of file cll.h.
View newest version in sPHENIX GitHub at line 113 of file cll.h
References Pi0.
Referenced by Hydro::ISformal().
void Cell::setpi0 (double values[4][4]) inline
Definition at line 143 of file cll.h.
View newest version in sPHENIX GitHub at line 143 of file cll.h
References i, index44(), j, and pi0.
void Cell::setpiH (const int & i, const int & j, const double & val) inline
Definition at line 96 of file cll.h.
View newest version in sPHENIX GitHub at line 96 of file cll.h
References index44(), and piH.
Referenced by Hydro::ISformal().
void Cell::setPiH (const double & val) inline
Definition at line 112 of file cll.h.
View newest version in sPHENIX GitHub at line 112 of file cll.h
References PiH.
Referenced by Hydro::ISformal().
void Cell::setpiH0 (const int & i, const int & j, const double & val) inline
Definition at line 102 of file cll.h.
View newest version in sPHENIX GitHub at line 102 of file cll.h
References index44(), and piH0.
Referenced by Hydro::ISformal().
void Cell::setPiH0 (const double & val) inline
Definition at line 114 of file cll.h.
View newest version in sPHENIX GitHub at line 114 of file cll.h
References PiH0.
Referenced by Hydro::ISformal().
void Cell::setpiH0 (double values[4][4]) inline
Definition at line 147 of file cll.h.
View newest version in sPHENIX GitHub at line 147 of file cll.h
References i, index44(), j, and piH0.
void Cell::setPos (int iix, int iiy, int iiz) inline
Definition at line 55 of file cll.h.
View newest version in sPHENIX GitHub at line 55 of file cll.h
References ix, iy, and iz.
void Cell::setPrev (int i, Cell * c) inline
Definition at line 128 of file cll.h.
View newest version in sPHENIX GitHub at line 128 of file cll.h
References Acts::PhysicalConstants::c, and prev.
void Cell::setPrimVar (EoS * eos, double tau, double _e, double _nb, double _nq, double _ns, double _vx, double _vy, double _vz)
Definition at line 192 of file cll.cpp.
View newest version in sPHENIX GitHub at line 192 of file cll.cpp
References NB_, NQ_, NS_, merge_hashes::p, EoS::p(), Q(), T_, X_, Y_, and Z_.
Referenced by icsethlle_(), ICGubser::setIC(), IC::setIC(), and ICGlauber::setIC().
void Cell::setQ (double * _Q) inline
Definition at line 64 of file cll.h.
View newest version in sPHENIX GitHub at line 64 of file cll.h
References i, Q, and T_.
void Cell::setQh (double * _Qh) inline
Definition at line 70 of file cll.h.
View newest version in sPHENIX GitHub at line 70 of file cll.h
References i, Qh, and T_.
void Cell::setViscCorrCutFlag (double value) inline
Definition at line 204 of file cll.h.
View newest version in sPHENIX GitHub at line 204 of file cll.h
References value, and viscCorrCut.
Referenced by Hydro::ISformal().
void Cell::updateByFlux ()
Definition at line 53 of file cll.cpp.
View newest version in sPHENIX GitHub at line 53 of file cll.cpp
References i, and Q().
Referenced by Hydro::performStep().
void Cell::updateQtoQhByFlux ()
Definition at line 57 of file cll.cpp.
View newest version in sPHENIX GitHub at line 57 of file cll.cpp
References i, and Q().
Referenced by Hydro::performStep().
Member Data Documentation
double Cell::dm[3] private
Definition at line 46 of file cll.h.
View newest version in sPHENIX GitHub at line 46 of file cll.h
Referenced by getDM(), and setDM().
double Cell::flux[7] private
Definition at line 42 of file cll.h.
View newest version in sPHENIX GitHub at line 42 of file cll.h
Referenced by addFlux(), and clearFlux().
int Cell::ix private
Definition at line 47 of file cll.h.
View newest version in sPHENIX GitHub at line 47 of file cll.h
Referenced by getX(), and setPos().
int Cell::iy private
Definition at line 47 of file cll.h.
View newest version in sPHENIX GitHub at line 47 of file cll.h
Referenced by getY(), and setPos().
int Cell::iz private
Definition at line 47 of file cll.h.
View newest version in sPHENIX GitHub at line 47 of file cll.h
Referenced by getZ(), and setPos().
double Cell::m[3] private
Definition at line 45 of file cll.h.
View newest version in sPHENIX GitHub at line 45 of file cll.h
Referenced by addM(), getM(), getMaxM(), and setAllM().
Cell* Cell::next[3] private
Definition at line 43 of file cll.h.
View newest version in sPHENIX GitHub at line 43 of file cll.h
Referenced by getNext(), and setNext().
double Cell::pi[10] private
Definition at line 36 of file cll.h.
View newest version in sPHENIX GitHub at line 36 of file cll.h
Referenced by getpi(), and setpi().
double Cell::Pi private
Definition at line 38 of file cll.h.
View newest version in sPHENIX GitHub at line 38 of file cll.h
Referenced by getPi(), and setPi().
double Cell::pi0[10] private
Definition at line 40 of file cll.h.
View newest version in sPHENIX GitHub at line 40 of file cll.h
Referenced by addpi0(), getpi0(), and setpi0().
double Cell::Pi0 private
Definition at line 41 of file cll.h.
View newest version in sPHENIX GitHub at line 41 of file cll.h
Referenced by addPi0(), getPi0(), and setPi0().
double Cell::piH[10] private
Definition at line 36 of file cll.h.
View newest version in sPHENIX GitHub at line 36 of file cll.h
Referenced by getpiH(), and setpiH().
double Cell::PiH private
Definition at line 38 of file cll.h.
View newest version in sPHENIX GitHub at line 38 of file cll.h
Referenced by getPiH(), and setPiH().
double Cell::piH0[10] private
Definition at line 40 of file cll.h.
View newest version in sPHENIX GitHub at line 40 of file cll.h
Referenced by addpiH0(), getpiH0(), and setpiH0().
double Cell::PiH0 private
Definition at line 41 of file cll.h.
View newest version in sPHENIX GitHub at line 41 of file cll.h
Referenced by addPiH0(), getPiH0(), and setPiH0().
Cell* Cell::prev[3] private
Definition at line 44 of file cll.h.
View newest version in sPHENIX GitHub at line 44 of file cll.h
Referenced by getPrev(), and setPrev().
double Cell::Q[7] private
Definition at line 33 of file cll.h.
View newest version in sPHENIX GitHub at line 33 of file cll.h
Referenced by getQ(), saveQprev(), and setQ().
double Cell::Qh[7] private
Definition at line 34 of file cll.h.
View newest version in sPHENIX GitHub at line 34 of file cll.h
Referenced by getQh(), and setQh().
double Cell::Qprev[7] private
Definition at line 35 of file cll.h.
View newest version in sPHENIX GitHub at line 35 of file cll.h
Referenced by saveQprev().
double Cell::viscCorrCut private
Definition at line 50 of file cll.h.
View newest version in sPHENIX GitHub at line 50 of file cll.h
Referenced by getViscCorrCutFlag(), and setViscCorrCutFlag().
The documentation for this class was generated from the following files:
JETSCAPE/blob/main/jail/vhlle/src/cll.h
JETSCAPE/blob/main/jail/vhlle/src/cll.cpp