Analysis Software: CMFlashClusterv3 Class Reference
CMFlashClusterv3 Class Reference
Version 3 of CMFlashCluster.
#include <coresoftware/blob/master/offline/packages/trackbase/CMFlashClusterv3.h>
Public Member Functions
CMFlashClusterv3 ()=default
ctor
void identify (std::ostream &os=std::cout) const override
void Reset () override
Clear Event.
int isValid () const override
isValid returns non zero if object contains vailid data
PHObject * CloneMe () const override
Virtual copy constructor.
void CopyFrom (const CMFlashCluster &) override
copy content from base class
void CopyFrom (CMFlashCluster *source) override
copy content from base class
float getX () const override
void setX (float x) override
float getY () const override
void setY (float y) override
float getZ () const override
void setZ (float z) override
float getX1 () const override
void setX1 (float x) override
float getY1 () const override
void setY1 (float y) override
float getZ1 () const override
void setZ1 (float z) override
float getX2 () const override
void setX2 (float x) override
float getY2 () const override
void setY2 (float y) override
float getZ2 () const override
void setZ2 (float z) override
unsigned int getLayer1 () const override
void setLayer1 (unsigned int layer) override
unsigned int getLayer2 () const override
void setLayer2 (unsigned int layer) override
unsigned int getNclusters () const override
void setNclusters (unsigned int n) override
bool getIsRGap () const override
void setIsRGap (bool isRGap) override
bool getIsPhiGap () const override
void setIsPhiGap (bool isPhiGap) override
unsigned int getAdc () const override
void setAdc (unsigned int adc) override
unsigned int getAdc1 () const override
void setAdc1 (unsigned int adc) override
unsigned int getAdc2 () const override
void setAdc2 (unsigned int adc) override
Public Member Functions inherited from CMFlashCluster
~CMFlashCluster () override
dtor
Public Member Functions inherited from PHObject
PHObject ()
ctor
~PHObject () override
dtor
virtual PHObject * clone () const final
PHObject * Clone (const char *newname="") const final
void Copy (TObject &object) const final
virtual int Integrate () const
virtual int Integrate (PHObject *)
virtual void CopyFrom (const PHObject *obj)
Protected Attributes
float m_pos [3] = {NAN, NAN, NAN}
mean cluster position
float m_pos1 [3] = {NAN, NAN, NAN}
float m_pos2 [3] = {NAN, NAN, NAN}
unsigned int m_adc = 0xFFFFFFFF
cluster sum adc
unsigned int m_adc1 = 0xFFFFFFFF
unsigned int m_adc2 = 0xFFFFFFFF
unsigned int m_layer1 = UINT_MAX
unsigned int m_layer2 = UINT_MAX
unsigned int m_nclusters = UINT_MAX
number of TPC clusters used to create this central mebrane cluster
bool m_isRGap = false
bools to identify if meta-cluster is across sector/module gaps
bool m_isPhiGap = false
Additional Inherited Members
Protected Member Functions inherited from CMFlashCluster
CMFlashCluster ()=default
Detailed Description
Version 3 of CMFlashCluster.
*Adding variable to keep track of clusters *put into metaclusters
Definition at line 23 of file CMFlashClusterv3.h.
View newest version in sPHENIX GitHub at line 23 of file CMFlashClusterv3.h
Constructor & Destructor Documentation
CMFlashClusterv3::CMFlashClusterv3 () default
ctor
Referenced by CloneMe().
Member Function Documentation
PHObject* CMFlashClusterv3::CloneMe () const inline override virtual
Virtual copy constructor.
Reimplemented from PHObject.
Definition at line 33 of file CMFlashClusterv3.h.
View newest version in sPHENIX GitHub at line 33 of file CMFlashClusterv3.h
References CMFlashClusterv3().
void CMFlashClusterv3::CopyFrom (const CMFlashCluster & source) override virtual
copy content from base class
Reimplemented from CMFlashCluster.
Definition at line 51 of file CMFlashClusterv3.cc.
View newest version in sPHENIX GitHub at line 51 of file CMFlashClusterv3.cc
References CMFlashCluster::CopyFrom(), CMFlashCluster::getAdc(), CMFlashCluster::getAdc1(), CMFlashCluster::getAdc2(), CMFlashCluster::getIsPhiGap(), CMFlashCluster::getIsRGap(), CMFlashCluster::getLayer1(), CMFlashCluster::getLayer2(), CMFlashCluster::getX(), CMFlashCluster::getX1(), CMFlashCluster::getX2(), CMFlashCluster::getY(), CMFlashCluster::getY1(), CMFlashCluster::getY2(), CMFlashCluster::getZ(), CMFlashCluster::getZ1(), CMFlashCluster::getZ2(), setAdc(), setAdc1(), setAdc2(), setIsPhiGap(), setIsRGap(), setLayer1(), setLayer2(), setX(), setX1(), setX2(), setY(), setY1(), setY2(), setZ(), setZ1(), and setZ2().
void CMFlashClusterv3::CopyFrom (CMFlashCluster * source) inline override virtual
copy content from base class
Reimplemented from CMFlashCluster.
Definition at line 39 of file CMFlashClusterv3.h.
View newest version in sPHENIX GitHub at line 39 of file CMFlashClusterv3.h
References CopyFrom().
Referenced by CopyFrom().
unsigned int CMFlashClusterv3::getAdc () const inline override virtual
Reimplemented from CMFlashCluster.
Definition at line 82 of file CMFlashClusterv3.h.
View newest version in sPHENIX GitHub at line 82 of file CMFlashClusterv3.h
References m_adc.
Referenced by identify().
unsigned int CMFlashClusterv3::getAdc1 () const inline override virtual
Reimplemented from CMFlashCluster.
Definition at line 85 of file CMFlashClusterv3.h.
View newest version in sPHENIX GitHub at line 85 of file CMFlashClusterv3.h
References m_adc1.
unsigned int CMFlashClusterv3::getAdc2 () const inline override virtual
Reimplemented from CMFlashCluster.
Definition at line 88 of file CMFlashClusterv3.h.
View newest version in sPHENIX GitHub at line 88 of file CMFlashClusterv3.h
References m_adc2.
bool CMFlashClusterv3::getIsPhiGap () const inline override virtual
Reimplemented from CMFlashCluster.
Definition at line 76 of file CMFlashClusterv3.h.
View newest version in sPHENIX GitHub at line 76 of file CMFlashClusterv3.h
References m_isPhiGap.
bool CMFlashClusterv3::getIsRGap () const inline override virtual
Reimplemented from CMFlashCluster.
Definition at line 74 of file CMFlashClusterv3.h.
View newest version in sPHENIX GitHub at line 74 of file CMFlashClusterv3.h
References m_isRGap.
unsigned int CMFlashClusterv3::getLayer1 () const inline override virtual
Reimplemented from CMFlashCluster.
Definition at line 67 of file CMFlashClusterv3.h.
View newest version in sPHENIX GitHub at line 67 of file CMFlashClusterv3.h
References m_layer1.
unsigned int CMFlashClusterv3::getLayer2 () const inline override virtual
Reimplemented from CMFlashCluster.
Definition at line 69 of file CMFlashClusterv3.h.
View newest version in sPHENIX GitHub at line 69 of file CMFlashClusterv3.h
References m_layer2.
unsigned int CMFlashClusterv3::getNclusters () const inline override virtual
Reimplemented from CMFlashCluster.
Definition at line 72 of file CMFlashClusterv3.h.
View newest version in sPHENIX GitHub at line 72 of file CMFlashClusterv3.h
References m_nclusters.
float CMFlashClusterv3::getX () const inline override virtual
Reimplemented from CMFlashCluster.
Definition at line 45 of file CMFlashClusterv3.h.
View newest version in sPHENIX GitHub at line 45 of file CMFlashClusterv3.h
References m_pos.
Referenced by isValid().
float CMFlashClusterv3::getX1 () const inline override virtual
Reimplemented from CMFlashCluster.
Definition at line 53 of file CMFlashClusterv3.h.
View newest version in sPHENIX GitHub at line 53 of file CMFlashClusterv3.h
References m_pos1.
Referenced by isValid().
float CMFlashClusterv3::getX2 () const inline override virtual
Reimplemented from CMFlashCluster.
Definition at line 60 of file CMFlashClusterv3.h.
View newest version in sPHENIX GitHub at line 60 of file CMFlashClusterv3.h
References m_pos2.
Referenced by isValid().
float CMFlashClusterv3::getY () const inline override virtual
Reimplemented from CMFlashCluster.
Definition at line 47 of file CMFlashClusterv3.h.
View newest version in sPHENIX GitHub at line 47 of file CMFlashClusterv3.h
References m_pos.
Referenced by isValid().
float CMFlashClusterv3::getY1 () const inline override virtual
Reimplemented from CMFlashCluster.
Definition at line 55 of file CMFlashClusterv3.h.
View newest version in sPHENIX GitHub at line 55 of file CMFlashClusterv3.h
References m_pos1.
Referenced by isValid().
float CMFlashClusterv3::getY2 () const inline override virtual
Reimplemented from CMFlashCluster.
Definition at line 62 of file CMFlashClusterv3.h.
View newest version in sPHENIX GitHub at line 62 of file CMFlashClusterv3.h
References m_pos2.
Referenced by isValid().
float CMFlashClusterv3::getZ () const inline override virtual
Reimplemented from CMFlashCluster.
Definition at line 49 of file CMFlashClusterv3.h.
View newest version in sPHENIX GitHub at line 49 of file CMFlashClusterv3.h
References m_pos.
Referenced by isValid().
float CMFlashClusterv3::getZ1 () const inline override virtual
Reimplemented from CMFlashCluster.
Definition at line 57 of file CMFlashClusterv3.h.
View newest version in sPHENIX GitHub at line 57 of file CMFlashClusterv3.h
References m_pos1.
Referenced by isValid().
float CMFlashClusterv3::getZ2 () const inline override virtual
Reimplemented from CMFlashCluster.
Definition at line 64 of file CMFlashClusterv3.h.
View newest version in sPHENIX GitHub at line 64 of file CMFlashClusterv3.h
References m_pos2.
Referenced by isValid().
void CMFlashClusterv3::identify (std::ostream & os = std::cout) const override virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from CMFlashCluster.
Definition at line 12 of file CMFlashClusterv3.cc.
View newest version in sPHENIX GitHub at line 12 of file CMFlashClusterv3.cc
References getAdc(), and m_pos.
int CMFlashClusterv3::isValid () const override virtual
isValid returns non zero if object contains vailid data
Reimplemented from CMFlashCluster.
Definition at line 28 of file CMFlashClusterv3.cc.
View newest version in sPHENIX GitHub at line 28 of file CMFlashClusterv3.cc
References getX(), getX1(), getX2(), getY(), getY1(), getY2(), getZ(), getZ1(), getZ2(), m_adc, m_adc1, and m_adc2.
void CMFlashClusterv3::Reset () inline override virtual
Clear Event.
Reimplemented from CMFlashCluster.
Definition at line 31 of file CMFlashClusterv3.h.
View newest version in sPHENIX GitHub at line 31 of file CMFlashClusterv3.h
void CMFlashClusterv3::setAdc (unsigned int adc) inline override virtual
Reimplemented from CMFlashCluster.
Definition at line 83 of file CMFlashClusterv3.h.
View newest version in sPHENIX GitHub at line 83 of file CMFlashClusterv3.h
References m_adc.
Referenced by CopyFrom().
void CMFlashClusterv3::setAdc1 (unsigned int adc) inline override virtual
Reimplemented from CMFlashCluster.
Definition at line 86 of file CMFlashClusterv3.h.
View newest version in sPHENIX GitHub at line 86 of file CMFlashClusterv3.h
References m_adc1.
Referenced by CopyFrom().
void CMFlashClusterv3::setAdc2 (unsigned int adc) inline override virtual
Reimplemented from CMFlashCluster.
Definition at line 89 of file CMFlashClusterv3.h.
View newest version in sPHENIX GitHub at line 89 of file CMFlashClusterv3.h
References m_adc2.
Referenced by CopyFrom().
void CMFlashClusterv3::setIsPhiGap (bool isPhiGap) inline override virtual
Reimplemented from CMFlashCluster.
Definition at line 77 of file CMFlashClusterv3.h.
View newest version in sPHENIX GitHub at line 77 of file CMFlashClusterv3.h
References m_isPhiGap.
Referenced by CopyFrom().
void CMFlashClusterv3::setIsRGap (bool isRGap) inline override virtual
Reimplemented from CMFlashCluster.
Definition at line 75 of file CMFlashClusterv3.h.
View newest version in sPHENIX GitHub at line 75 of file CMFlashClusterv3.h
References m_isRGap.
Referenced by CopyFrom().
void CMFlashClusterv3::setLayer1 (unsigned int layer) inline override virtual
Reimplemented from CMFlashCluster.
Definition at line 68 of file CMFlashClusterv3.h.
View newest version in sPHENIX GitHub at line 68 of file CMFlashClusterv3.h
References layer, and m_layer1.
Referenced by CopyFrom().
void CMFlashClusterv3::setLayer2 (unsigned int layer) inline override virtual
Reimplemented from CMFlashCluster.
Definition at line 70 of file CMFlashClusterv3.h.
View newest version in sPHENIX GitHub at line 70 of file CMFlashClusterv3.h
References layer, and m_layer2.
Referenced by CopyFrom().
void CMFlashClusterv3::setNclusters (unsigned int n) inline override virtual
Reimplemented from CMFlashCluster.
Definition at line 73 of file CMFlashClusterv3.h.
View newest version in sPHENIX GitHub at line 73 of file CMFlashClusterv3.h
References m_nclusters, and n.
void CMFlashClusterv3::setX (float x) inline override virtual
Reimplemented from CMFlashCluster.
Definition at line 46 of file CMFlashClusterv3.h.
View newest version in sPHENIX GitHub at line 46 of file CMFlashClusterv3.h
References m_pos, and ambiguity_solver_full_chain::x.
Referenced by CopyFrom().
void CMFlashClusterv3::setX1 (float x) inline override virtual
Reimplemented from CMFlashCluster.
Definition at line 54 of file CMFlashClusterv3.h.
View newest version in sPHENIX GitHub at line 54 of file CMFlashClusterv3.h
References m_pos1, and ambiguity_solver_full_chain::x.
Referenced by CopyFrom().
void CMFlashClusterv3::setX2 (float x) inline override virtual
Reimplemented from CMFlashCluster.
Definition at line 61 of file CMFlashClusterv3.h.
View newest version in sPHENIX GitHub at line 61 of file CMFlashClusterv3.h
References m_pos2, and ambiguity_solver_full_chain::x.
Referenced by CopyFrom().
void CMFlashClusterv3::setY (float y) inline override virtual
Reimplemented from CMFlashCluster.
Definition at line 48 of file CMFlashClusterv3.h.
View newest version in sPHENIX GitHub at line 48 of file CMFlashClusterv3.h
References m_pos, and y.
Referenced by CopyFrom().
void CMFlashClusterv3::setY1 (float y) inline override virtual
Reimplemented from CMFlashCluster.
Definition at line 56 of file CMFlashClusterv3.h.
View newest version in sPHENIX GitHub at line 56 of file CMFlashClusterv3.h
References m_pos1, and y.
Referenced by CopyFrom().
void CMFlashClusterv3::setY2 (float y) inline override virtual
Reimplemented from CMFlashCluster.
Definition at line 63 of file CMFlashClusterv3.h.
View newest version in sPHENIX GitHub at line 63 of file CMFlashClusterv3.h
References m_pos2, and y.
Referenced by CopyFrom().
void CMFlashClusterv3::setZ (float z) inline override virtual
Reimplemented from CMFlashCluster.
Definition at line 50 of file CMFlashClusterv3.h.
View newest version in sPHENIX GitHub at line 50 of file CMFlashClusterv3.h
References m_pos, and physmon_track_finding_ttbar::z.
Referenced by CopyFrom().
void CMFlashClusterv3::setZ1 (float z) inline override virtual
Reimplemented from CMFlashCluster.
Definition at line 58 of file CMFlashClusterv3.h.
View newest version in sPHENIX GitHub at line 58 of file CMFlashClusterv3.h
References m_pos1, and physmon_track_finding_ttbar::z.
Referenced by CopyFrom().
void CMFlashClusterv3::setZ2 (float z) inline override virtual
Reimplemented from CMFlashCluster.
Definition at line 65 of file CMFlashClusterv3.h.
View newest version in sPHENIX GitHub at line 65 of file CMFlashClusterv3.h
References m_pos2, and physmon_track_finding_ttbar::z.
Referenced by CopyFrom().
Member Data Documentation
unsigned int CMFlashClusterv3::m_adc = 0xFFFFFFFF protected
cluster sum adc
Definition at line 100 of file CMFlashClusterv3.h.
View newest version in sPHENIX GitHub at line 100 of file CMFlashClusterv3.h
Referenced by getAdc(), isValid(), and setAdc().
unsigned int CMFlashClusterv3::m_adc1 = 0xFFFFFFFF protected
Definition at line 101 of file CMFlashClusterv3.h.
View newest version in sPHENIX GitHub at line 101 of file CMFlashClusterv3.h
Referenced by getAdc1(), isValid(), and setAdc1().
unsigned int CMFlashClusterv3::m_adc2 = 0xFFFFFFFF protected
Definition at line 102 of file CMFlashClusterv3.h.
View newest version in sPHENIX GitHub at line 102 of file CMFlashClusterv3.h
Referenced by getAdc2(), isValid(), and setAdc2().
bool CMFlashClusterv3::m_isPhiGap = false protected
Definition at line 112 of file CMFlashClusterv3.h.
View newest version in sPHENIX GitHub at line 112 of file CMFlashClusterv3.h
Referenced by getIsPhiGap(), and setIsPhiGap().
bool CMFlashClusterv3::m_isRGap = false protected
bools to identify if meta-cluster is across sector/module gaps
Definition at line 111 of file CMFlashClusterv3.h.
View newest version in sPHENIX GitHub at line 111 of file CMFlashClusterv3.h
Referenced by getIsRGap(), and setIsRGap().
unsigned int CMFlashClusterv3::m_layer1 = UINT_MAX protected
Definition at line 104 of file CMFlashClusterv3.h.
View newest version in sPHENIX GitHub at line 104 of file CMFlashClusterv3.h
Referenced by getLayer1(), and setLayer1().
unsigned int CMFlashClusterv3::m_layer2 = UINT_MAX protected
Definition at line 105 of file CMFlashClusterv3.h.
View newest version in sPHENIX GitHub at line 105 of file CMFlashClusterv3.h
Referenced by getLayer2(), and setLayer2().
unsigned int CMFlashClusterv3::m_nclusters = UINT_MAX protected
number of TPC clusters used to create this central mebrane cluster
Definition at line 108 of file CMFlashClusterv3.h.
View newest version in sPHENIX GitHub at line 108 of file CMFlashClusterv3.h
Referenced by getNclusters(), and setNclusters().
float CMFlashClusterv3::m_pos[3] = {NAN, NAN, NAN} protected
mean cluster position
Definition at line 94 of file CMFlashClusterv3.h.
View newest version in sPHENIX GitHub at line 94 of file CMFlashClusterv3.h
Referenced by getX(), getY(), getZ(), identify(), setX(), setY(), and setZ().
float CMFlashClusterv3::m_pos1[3] = {NAN, NAN, NAN} protected
Definition at line 96 of file CMFlashClusterv3.h.
View newest version in sPHENIX GitHub at line 96 of file CMFlashClusterv3.h
Referenced by getX1(), getY1(), getZ1(), setX1(), setY1(), and setZ1().
float CMFlashClusterv3::m_pos2[3] = {NAN, NAN, NAN} protected
Definition at line 97 of file CMFlashClusterv3.h.
View newest version in sPHENIX GitHub at line 97 of file CMFlashClusterv3.h
Referenced by getX2(), getY2(), getZ2(), setX2(), setY2(), and setZ2().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/trackbase/CMFlashClusterv3.h
coresoftware/blob/master/offline/packages/trackbase/CMFlashClusterv3.cc