Analysis Software: ActsExamples::SeedingAlgorithm Exception Reference
ActsExamples::SeedingAlgorithm Exception Reference final
Construct track seeds from space points.
#include <acts/blob/sPHENIX/Examples/Algorithms/TrackFinding/include/ActsExamples/TrackFinding/SeedingAlgorithm.hpp>
Classes
struct Config
Public Member Functions
SeedingAlgorithm (Config cfg, Acts::Logging::Level lvl)
ProcessCode execute (const AlgorithmContext &ctx) const final
const Config & config () const
Const access to the config.
Public Member Functions inherited from ActsExamples::IAlgorithm
IAlgorithm (std::string name, Acts::Logging::Level level=Acts::Logging::INFO)
std::string name () const override
The algorithm name.
ProcessCode internalExecute (const AlgorithmContext &context) final
ProcessCode initialize () override
Initialize the algorithm.
ProcessCode finalize () override
Finalize the algorithm.
Private Attributes
Acts::SeedFinder< SimSpacePoint > m_seedFinder
std::shared_ptr< const
Acts::BinFinder< SimSpacePoint > > m_bottomBinFinder
std::shared_ptr< const
Acts::BinFinder< SimSpacePoint > > m_topBinFinder
Config m_cfg
std::vector< std::unique_ptr
< ReadDataHandle
< SimSpacePointContainer > > > m_inputSpacePoints {}
WriteDataHandle< SimSeedContainer > m_outputSeeds {this, "OutputSeeds"}
Additional Inherited Members
Protected Member Functions inherited from ActsExamples::IAlgorithm
const Acts::Logger & logger () const
Detailed Description
Construct track seeds from space points.
Definition at line 39 of file SeedingAlgorithm.hpp.
View newest version in sPHENIX GitHub at line 39 of file SeedingAlgorithm.hpp
Constructor & Destructor Documentation
ActsExamples::SeedingAlgorithm::SeedingAlgorithm (Config cfg, Acts::Logging::Level lvl)
Construct the seeding algorithm.
Parameters
cfg is the algorithm configuration
lvl is the logging level
Definition at line 37 of file SeedingAlgorithm.cpp.
View newest version in sPHENIX GitHub at line 37 of file SeedingAlgorithm.cpp
References ActsExamples::SeedingAlgorithm::Config::allowSeparateRMax, Acts::SpacePointGridOptions::bFieldInZ, Acts::SeedFinderOptions::bFieldInZ, ActsExamples::SimSpacePoint::bottomHalfStripLength(), ActsExamples::SimSpacePoint::bottomStripDirection(), Acts::SeedFinderConfig< SpacePoint >::calculateDerivedQuantities(), Acts::SeedFinderOptions::calculateDerivedQuantities(), Acts::SeedFinderConfig< SpacePoint >::cotThetaMax, Acts::SpacePointGridConfig::cotThetaMax, Acts::SpacePointGridConfig::deltaRMax, Acts::SeedFinderConfig< SpacePoint >::deltaRMax, Acts::SeedFinderConfig< SpacePoint >::deltaRMaxBottomSP, Acts::SeedFinderConfig< SpacePoint >::deltaRMaxTopSP, Acts::SeedFilterConfig::deltaRMin, Acts::SeedFinderConfig< SpacePoint >::deltaRMin, Acts::SeedFinderConfig< SpacePoint >::deltaRMinBottomSP, Acts::SeedFinderConfig< SpacePoint >::deltaRMinTopSP, Acts::SeedFinderConfig< SpacePoint >::getBottomHalfStripLength, Acts::SeedFinderConfig< SpacePoint >::getBottomStripDirection, Acts::SeedFinderConfig< SpacePoint >::getStripCenterDistance, Acts::SeedFinderConfig< SpacePoint >::getTopHalfStripLength, Acts::SeedFinderConfig< SpacePoint >::getTopStripCenterPosition, Acts::SeedFinderConfig< SpacePoint >::getTopStripDirection, ActsExamples::SeedingAlgorithm::Config::gridConfig, ActsExamples::SeedingAlgorithm::Config::gridOptions, i, ActsExamples::WriteDataHandle< T >::initialize(), ActsExamples::SeedingAlgorithm::Config::inputSpacePoints, m_bottomBinFinder, m_cfg, m_inputSpacePoints, m_outputSeeds, m_seedFinder, m_topBinFinder, Acts::SeedFilterConfig::maxSeedsPerSpM, Acts::SeedFinderConfig< SpacePoint >::maxSeedsPerSpM, Acts::SpacePointGridConfig::minPt, Acts::SeedFinderConfig< SpacePoint >::minPt, ActsExamples::SeedingAlgorithm::Config::numPhiNeighbors, ActsExamples::SeedingAlgorithm::Config::outputSeeds, Acts::SpacePointGridConfig::rMax, Acts::SeedFinderConfig< SpacePoint >::rMax, Acts::SeedFinderConfig< SpacePoint >::seedFilter, ActsExamples::SeedingAlgorithm::Config::seedFilterConfig, ActsExamples::SeedingAlgorithm::Config::seedFinderConfig, ActsExamples::SeedingAlgorithm::Config::seedFinderOptions, ActsExamples::SimSpacePoint::stripCenterDistance(), to_string(), Acts::SpacePointGridConfig::toInternalUnits(), Acts::SeedFilterConfig::toInternalUnits(), Acts::SpacePointGridOptions::toInternalUnits(), Acts::SeedFinderConfig< SpacePoint >::toInternalUnits(), Acts::SeedFinderOptions::toInternalUnits(), ActsExamples::SimSpacePoint::topHalfStripLength(), ActsExamples::SimSpacePoint::topStripCenterPosition(), ActsExamples::SimSpacePoint::topStripDirection(), Acts::SeedFinderConfig< SpacePoint >::useDetailedDoubleMeasurementInfo, Acts::SpacePointGridConfig::zBinEdges, ActsExamples::SeedingAlgorithm::Config::zBinNeighborsBottom, ActsExamples::SeedingAlgorithm::Config::zBinNeighborsTop, Acts::SeedFinderConfig< SpacePoint >::zBinsCustomLooping, Acts::SpacePointGridConfig::zMax, Acts::SeedFinderConfig< SpacePoint >::zMax, Acts::SpacePointGridConfig::zMin, and Acts::SeedFinderConfig< SpacePoint >::zMin.
Member Function Documentation
const Config& ActsExamples::SeedingAlgorithm::config () const inline
Const access to the config.
Definition at line 82 of file SeedingAlgorithm.hpp.
View newest version in sPHENIX GitHub at line 82 of file SeedingAlgorithm.hpp
References m_cfg.
ActsExamples::ProcessCode ActsExamples::SeedingAlgorithm::execute (const AlgorithmContext & ctx) const final virtual
Run the seeding algorithm.
Parameters
ctx is the algorithm context with event information
Returns
a process code indication success or failure
variable middle SP radial region of interest
Implements ActsExamples::IAlgorithm.
Definition at line 218 of file SeedingAlgorithm.cpp.
View newest version in sPHENIX GitHub at line 218 of file SeedingAlgorithm.cpp
References ACTS_DEBUG, Acts::binR, covariance(), grid(), index, m_cfg(), testing::internal::move(), position, size, filter::state, SUCCESS, ActsExamples::SimSpacePoint::varianceR(), ActsExamples::SimSpacePoint::varianceZ(), ActsExamples::SimSpacePoint::x(), ActsExamples::SimSpacePoint::y(), and ActsExamples::SimSpacePoint::z().
Member Data Documentation
std::shared_ptr<const Acts::BinFinder<SimSpacePoint> > ActsExamples::SeedingAlgorithm::m_bottomBinFinder private
Definition at line 86 of file SeedingAlgorithm.hpp.
View newest version in sPHENIX GitHub at line 86 of file SeedingAlgorithm.hpp
Referenced by SeedingAlgorithm().
Config ActsExamples::SeedingAlgorithm::m_cfg private
Definition at line 88 of file SeedingAlgorithm.hpp.
View newest version in sPHENIX GitHub at line 88 of file SeedingAlgorithm.hpp
Referenced by config(), and SeedingAlgorithm().
std::vector<std::unique_ptr<ReadDataHandle<SimSpacePointContainer> > > ActsExamples::SeedingAlgorithm::m_inputSpacePoints {} private
Definition at line 91 of file SeedingAlgorithm.hpp.
View newest version in sPHENIX GitHub at line 91 of file SeedingAlgorithm.hpp
Referenced by SeedingAlgorithm().
WriteDataHandle<SimSeedContainer> ActsExamples::SeedingAlgorithm::m_outputSeeds {this, "OutputSeeds"} private
Definition at line 93 of file SeedingAlgorithm.hpp.
View newest version in sPHENIX GitHub at line 93 of file SeedingAlgorithm.hpp
Referenced by SeedingAlgorithm().
Acts::SeedFinder<SimSpacePoint> ActsExamples::SeedingAlgorithm::m_seedFinder private
Definition at line 85 of file SeedingAlgorithm.hpp.
View newest version in sPHENIX GitHub at line 85 of file SeedingAlgorithm.hpp
Referenced by SeedingAlgorithm().
std::shared_ptr<const Acts::BinFinder<SimSpacePoint> > ActsExamples::SeedingAlgorithm::m_topBinFinder private
Definition at line 87 of file SeedingAlgorithm.hpp.
View newest version in sPHENIX GitHub at line 87 of file SeedingAlgorithm.hpp
Referenced by SeedingAlgorithm().
The documentation for this exception was generated from the following files:
acts/blob/sPHENIX/Examples/Algorithms/TrackFinding/include/ActsExamples/TrackFinding/SeedingAlgorithm.hpp
acts/blob/sPHENIX/Examples/Algorithms/TrackFinding/src/SeedingAlgorithm.cpp