Analysis Software: MicromegasGeometry Class Reference
MicromegasGeometry Class Reference
handle simplified TPOT 2D geometry, for histogram representation
#include <OnlMon/blob/main/subsystems/tpot/MicromegasGeometry.h>
Public Types
using point_t = std::pair< double, double >
using point_list_t = std::vector< point_t >
Public Member Functions
MicromegasGeometry ()
constructor
size_t get_ntiles () const
get number of defined tiles
point_t get_tile_center (size_t tile_id) const
get tile center for given tile id
std::string get_detname_sphenix (size_t tile_id) const
get detector name for a given tile id
point_list_t get_tile_boundaries (size_t) const
get tile boundaries for a given tile id
point_list_t get_resist_boundaries (size_t, size_t, MicromegasDefs::SegmentationType) const
get resist region boundaries for a given tile id
Static Public Attributes
static constexpr double m_tile_length = 54.2
tile definitions
static constexpr double m_tile_width = 31.6
static constexpr double m_pitch_z = 0.2
pitch for z views (cm)
static constexpr double m_pitch_phi = 0.1
pitch for phi views (cm)
static constexpr int m_nresist = 4
number of resist sectors
Private Attributes
point_list_t m_tile_centers
tile centers
std::vector< std::string > m_detnames_sphenix
matching detector name
Detailed Description
handle simplified TPOT 2D geometry, for histogram representation
positioning follows the same tile_id order as in coresoftware/simulation/g4simulation/g4micromegas/PHG4MicromegasDetector::setup_tiles it is ordered by tile number as defined in MicromegasMapping.cc
Definition at line 16 of file MicromegasGeometry.h.
View newest version in sPHENIX GitHub at line 16 of file MicromegasGeometry.h
Member Typedef Documentation
using MicromegasGeometry::point_list_t = std::vector<point_t>
Definition at line 21 of file MicromegasGeometry.h.
View newest version in sPHENIX GitHub at line 21 of file MicromegasGeometry.h
using MicromegasGeometry::point_t = std::pair<double, double>
Definition at line 20 of file MicromegasGeometry.h.
View newest version in sPHENIX GitHub at line 20 of file MicromegasGeometry.h
Constructor & Destructor Documentation
MicromegasGeometry::MicromegasGeometry ()
constructor
Definition at line 4 of file MicromegasGeometry.cc.
View newest version in sPHENIX GitHub at line 4 of file MicromegasGeometry.cc
Member Function Documentation
std::string MicromegasGeometry::get_detname_sphenix (size_t tile_id) const inline
get detector name for a given tile id
Definition at line 35 of file MicromegasGeometry.h.
View newest version in sPHENIX GitHub at line 35 of file MicromegasGeometry.h
References m_detnames_sphenix.
Referenced by TpotMonDraw::draw_detnames_sphenix().
size_t MicromegasGeometry::get_ntiles () const inline
get number of defined tiles
Definition at line 27 of file MicromegasGeometry.h.
View newest version in sPHENIX GitHub at line 27 of file MicromegasGeometry.h
References m_tile_centers.
Referenced by TpotMonDraw::draw_detnames_sphenix(), TpotMon::setup_detector_bins(), and TpotMon::setup_resist_bins().
point_list_t MicromegasGeometry::get_resist_boundaries (size_t , size_t , MicromegasDefs::SegmentationType) const
get resist region boundaries for a given tile id
there are 4 resistive layer regions for a given tile, each oriented along the strips
Referenced by TpotMon::setup_resist_bins().
point_list_t MicromegasGeometry::get_tile_boundaries (size_t) const
get tile boundaries for a given tile id
Referenced by TpotMon::setup_detector_bins().
point_t MicromegasGeometry::get_tile_center (size_t tile_id) const inline
get tile center for given tile id
Definition at line 31 of file MicromegasGeometry.h.
View newest version in sPHENIX GitHub at line 31 of file MicromegasGeometry.h
References m_tile_centers.
Referenced by TpotMonDraw::draw_detnames_sphenix(), and TpotMon::Init().
Member Data Documentation
std::vector<std::string> MicromegasGeometry::m_detnames_sphenix private
matching detector name
Definition at line 65 of file MicromegasGeometry.h.
View newest version in sPHENIX GitHub at line 65 of file MicromegasGeometry.h
Referenced by get_detname_sphenix().
constexpr int MicromegasGeometry::m_nresist = 4 static
number of resist sectors
Definition at line 56 of file MicromegasGeometry.h.
View newest version in sPHENIX GitHub at line 56 of file MicromegasGeometry.h
Referenced by TpotMon::setup_resist_bins().
constexpr double MicromegasGeometry::m_pitch_phi = 0.1 static
pitch for phi views (cm)
Definition at line 53 of file MicromegasGeometry.h.
View newest version in sPHENIX GitHub at line 53 of file MicromegasGeometry.h
constexpr double MicromegasGeometry::m_pitch_z = 0.2 static
pitch for z views (cm)
Definition at line 50 of file MicromegasGeometry.h.
View newest version in sPHENIX GitHub at line 50 of file MicromegasGeometry.h
point_list_t MicromegasGeometry::m_tile_centers private
tile centers
tile centers are ordered by tile_ids as defined in MicromegasMapping.cc
Definition at line 62 of file MicromegasGeometry.h.
View newest version in sPHENIX GitHub at line 62 of file MicromegasGeometry.h
Referenced by get_ntiles(), and get_tile_center().
constexpr double MicromegasGeometry::m_tile_length = 54.2 static
tile definitions
Definition at line 46 of file MicromegasGeometry.h.
View newest version in sPHENIX GitHub at line 46 of file MicromegasGeometry.h
Referenced by TpotMonDraw::draw_detnames_sphenix(), and TpotMon::process_event().
constexpr double MicromegasGeometry::m_tile_width = 31.6 static
Definition at line 47 of file MicromegasGeometry.h.
View newest version in sPHENIX GitHub at line 47 of file MicromegasGeometry.h
Referenced by TpotMonDraw::draw_detnames_sphenix(), and TpotMon::process_event().
The documentation for this class was generated from the following files:
OnlMon/blob/main/subsystems/tpot/MicromegasGeometry.h
OnlMon/blob/main/subsystems/tpot/MicromegasGeometry.cc