Analysis Software: acts/blob/sPHENIX/Tests/UnitTests/Core/Material/MaterialTests.cpp File Reference
MaterialTests.cpp File Reference
#include <boost/test/data/test_case.hpp>
#include <boost/test/unit_test.hpp>
#include "Acts/Definitions/Units.hpp"
#include "Acts/Material/Material.hpp"
#include "Acts/Tests/CommonHelpers/FloatComparisons.hpp"
#include "Acts/Tests/CommonHelpers/PredefinedMaterials.hpp"
#include <limits>
Functions
BOOST_AUTO_TEST_CASE (ConstructVacuum)
BOOST_AUTO_TEST_CASE (ConstructSomething)
BOOST_AUTO_TEST_CASE (Units)
BOOST_DATA_TEST_CASE (EncodingDecodingRoundtrip, bdata::make({Acts::Material(), Acts::Material::fromMolarDensity(1, 2, 3, 4, 5), Acts::Test::makeBeryllium(), Acts::Test::makeSilicon(),}), material)
Variables
static constexpr auto eps = 2 * std::numeric_limits<float>::epsilon()
static constexpr float SiNe = 1.160954941_mol / 1_cm3
static constexpr float SiI = 172.042290036_eV
Function Documentation
BOOST_AUTO_TEST_CASE (ConstructVacuum)
Definition at line 30 of file MaterialTests.cpp.
View newest version in sPHENIX GitHub at line 30 of file MaterialTests.cpp
BOOST_AUTO_TEST_CASE (ConstructSomething)
Definition at line 36 of file MaterialTests.cpp.
View newest version in sPHENIX GitHub at line 36 of file MaterialTests.cpp
References Acts::Material::fromMolarDensity().
BOOST_AUTO_TEST_CASE (Units)
Definition at line 42 of file MaterialTests.cpp.
View newest version in sPHENIX GitHub at line 42 of file MaterialTests.cpp
References Acts::Material::Ar(), CHECK_CLOSE_REL, eps, Acts::Material::L0(), Acts::Test::makeSilicon(), Acts::Material::massDensity(), Acts::Material::meanExcitationEnergy(), Acts::Material::molarDensity(), Acts::Material::molarElectronDensity(), SiI, SiNe, Acts::Material::X0(), and Acts::Material::Z().
BOOST_DATA_TEST_CASE (EncodingDecodingRoundtrip , bdata:: make{Acts::Material(),Acts::Material::fromMolarDensity(1, 2, 3, 4, 5),Acts::Test::makeBeryllium(),Acts::Test::makeSilicon(),}, material)
Definition at line 66 of file MaterialTests.cpp.
View newest version in sPHENIX GitHub at line 66 of file MaterialTests.cpp
References Acts::Material::fromMolarDensity(), Acts::Test::makeBeryllium(), and Acts::Test::makeSilicon().
Variable Documentation
constexpr auto eps = 2 * std::numeric_limits<float>::epsilon() static
Definition at line 23 of file MaterialTests.cpp.
View newest version in sPHENIX GitHub at line 23 of file MaterialTests.cpp
Referenced by BOOST_AUTO_TEST_CASE().
constexpr float SiI = 172.042290036_eV static
Definition at line 26 of file MaterialTests.cpp.
View newest version in sPHENIX GitHub at line 26 of file MaterialTests.cpp
Referenced by BOOST_AUTO_TEST_CASE().
constexpr float SiNe = 1.160954941_mol / 1_cm3 static
Definition at line 25 of file MaterialTests.cpp.
View newest version in sPHENIX GitHub at line 25 of file MaterialTests.cpp
Referenced by BOOST_AUTO_TEST_CASE().