Analysis Software: SvtxVertexMap Class Reference
SvtxVertexMap Class Reference
#include <coresoftware/blob/master/offline/packages/trackbase_historic/SvtxVertexMap.h>
Public Types
typedef std::map< unsigned int,
SvtxVertex * > VertexMap
typedef std::map< unsigned int,
SvtxVertex * >::const_iterator ConstIter
typedef std::map< unsigned int,
SvtxVertex * >::iterator Iter
Public Member Functions
~SvtxVertexMap () override
void identify (std::ostream &os=std::cout) const override
int isValid () const override
isValid returns non zero if object contains vailid data
PHObject * CloneMe () const override
Virtual copy constructor.
virtual bool empty () const
virtual size_t size () const
virtual size_t count (unsigned int idkey) const
virtual void clear ()
virtual const SvtxVertex * get (unsigned int idkey) const
virtual SvtxVertex * get (unsigned int idkey)
virtual SvtxVertex * insert (SvtxVertex *cluster)
Add vertex to container. Note the container take to ownership.
virtual SvtxVertex * insert_clone (const SvtxVertex *vertex)
legacy interface. Add vertex to container. Note the container does not take ownership
virtual size_t erase (unsigned int idkey)
virtual ConstIter begin () const
virtual ConstIter find (unsigned int idkey) const
virtual ConstIter end () const
virtual Iter begin ()
virtual Iter find (unsigned int idkey)
virtual Iter end ()
Public Member Functions inherited from PHObject
PHObject ()
ctor
~PHObject () override
dtor
virtual PHObject * clone () const final
PHObject * Clone (const char *newname="") const final
void Copy (TObject &object) const final
virtual void Reset ()
Clear Event.
virtual int isValid (const float) const
virtual int isValid (const double) const
virtual int isValid (const int) const
virtual int isValid (const unsigned int) const
virtual int isImplemented (const float f) const
virtual int isImplemented (const double f) const
virtual int isImplemented (const int i) const
virtual int isImplemented (const unsigned int i) const
virtual int Integrate () const
virtual int Integrate (PHObject *obj)
virtual void CopyFrom (const PHObject *obj)
Protected Member Functions
SvtxVertexMap ()
Private Member Functions
ClassDefOverride (SvtxVertexMap, 1)
Detailed Description
Definition at line 10 of file SvtxVertexMap.h.
View newest version in sPHENIX GitHub at line 10 of file SvtxVertexMap.h
Member Typedef Documentation
typedef std::map<unsigned int, SvtxVertex*>::const_iterator SvtxVertexMap::ConstIter
Definition at line 14 of file SvtxVertexMap.h.
View newest version in sPHENIX GitHub at line 14 of file SvtxVertexMap.h
typedef std::map<unsigned int, SvtxVertex*>::iterator SvtxVertexMap::Iter
Definition at line 15 of file SvtxVertexMap.h.
View newest version in sPHENIX GitHub at line 15 of file SvtxVertexMap.h
typedef std::map<unsigned int, SvtxVertex*> SvtxVertexMap::VertexMap
Definition at line 13 of file SvtxVertexMap.h.
View newest version in sPHENIX GitHub at line 13 of file SvtxVertexMap.h
Constructor & Destructor Documentation
SvtxVertexMap::~SvtxVertexMap () inline override
Definition at line 17 of file SvtxVertexMap.h.
View newest version in sPHENIX GitHub at line 17 of file SvtxVertexMap.h
SvtxVertexMap::SvtxVertexMap () inline protected
Definition at line 50 of file SvtxVertexMap.h.
View newest version in sPHENIX GitHub at line 50 of file SvtxVertexMap.h
Member Function Documentation
SvtxVertexMap::ConstIter SvtxVertexMap::begin () const virtual
Reimplemented in SvtxVertexMap_v1.
Definition at line 5 of file SvtxVertexMap.cc.
View newest version in sPHENIX GitHub at line 5 of file SvtxVertexMap.cc
References DummyVertexMap.
Referenced by SvtxVertexEval::all_vertexes_from(), PHTruthVertexing::assignStubsVertices(), PHPatternReco::export_output(), TpcPrototypeGenFitTrkFitter::fill_eval_tree(), PHG4TrackFastSimEval::fill_vertex_tree(), psTOFTimezeroEval::fillOutputNtuples(), SvtxEvaluatorHaiwang::fillOutputNtuples(), EventEvaluator::fillOutputNtuples(), BDiJetModule::FillVertexMap(), KFParticle_truthAndDetTools::getVertex(), KFParticle_Tools::makeAllPrimaryVertices(), HFTrigger::makeAllPrimaryVertices(), HFTriggerMVA::makeAllPrimaryVertices(), PHSimpleKFProp::MoveToVertex(), psTOFTimezeroEval::printInputInfo(), SvtxEvaluatorHaiwang::printInputInfo(), psTOFTimezeroEval::printOutputInfo(), SvtxEvaluatorHaiwang::printOutputInfo(), PHTpcTrackSeedVertexAssoc::Process(), PHSimpleKFProp::Process(), PHHybridSeeding::Process(), SvtxSimPerformanceCheckReco::process_event(), QAG4SimulationVertex::process_event(), SimpleTrackingAnalysis::process_event(), GlobalVertexReco::process_event(), TPCGemGainCalb::process_event(), and DumpSvtxVertexMap::process_Node().
SvtxVertexMap::Iter SvtxVertexMap::begin () virtual
Reimplemented in SvtxVertexMap_v1.
Definition at line 21 of file SvtxVertexMap.cc.
View newest version in sPHENIX GitHub at line 21 of file SvtxVertexMap.cc
References DummyVertexMap.
SvtxVertexMap::ClassDefOverride (SvtxVertexMap , 1) private
virtual void SvtxVertexMap::clear () inline virtual
Reimplemented in SvtxVertexMap_v1.
Definition at line 29 of file SvtxVertexMap.h.
View newest version in sPHENIX GitHub at line 29 of file SvtxVertexMap.h
Referenced by PHInitZVertexing::export_output(), PHHoughSeeding::export_output(), PHRaveVertexing::FillSvtxVertexMap(), TpcPrototypeGenFitTrkFitter::FillSvtxVertexMap(), PHActsVertexFinder::fillVertexMap(), PHActsInitialVertexFinder::fillVertexMap(), PHActsVertexFitter::ResetEvent(), and PHActsVertexFinder::ResetEvent().
PHObject* SvtxVertexMap::CloneMe () const inline override virtual
Virtual copy constructor.
Reimplemented from PHObject.
Reimplemented in SvtxVertexMap_v1.
Definition at line 24 of file SvtxVertexMap.h.
View newest version in sPHENIX GitHub at line 24 of file SvtxVertexMap.h
virtual size_t SvtxVertexMap::count (unsigned int idkey) const inline virtual
Reimplemented in SvtxVertexMap_v1.
Definition at line 28 of file SvtxVertexMap.h.
View newest version in sPHENIX GitHub at line 28 of file SvtxVertexMap.h
virtual bool SvtxVertexMap::empty () const inline virtual
Reimplemented in SvtxVertexMap_v1.
Definition at line 26 of file SvtxVertexMap.h.
View newest version in sPHENIX GitHub at line 26 of file SvtxVertexMap.h
Referenced by EventEvaluator::fillOutputNtuples(), psTOFTimezeroEval::printOutputInfo(), and SvtxEvaluatorHaiwang::printOutputInfo().
SvtxVertexMap::ConstIter SvtxVertexMap::end () const virtual
Reimplemented in SvtxVertexMap_v1.
Definition at line 15 of file SvtxVertexMap.cc.
View newest version in sPHENIX GitHub at line 15 of file SvtxVertexMap.cc
References DummyVertexMap.
Referenced by SvtxVertexEval::all_vertexes_from(), PHTruthVertexing::assignStubsVertices(), PHPatternReco::export_output(), TpcPrototypeGenFitTrkFitter::fill_eval_tree(), PHG4TrackFastSimEval::fill_vertex_tree(), SvtxEvaluatorHaiwang::fillOutputNtuples(), psTOFTimezeroEval::fillOutputNtuples(), BDiJetModule::FillVertexMap(), KFParticle_truthAndDetTools::getVertex(), KFParticle_Tools::makeAllPrimaryVertices(), HFTrigger::makeAllPrimaryVertices(), HFTriggerMVA::makeAllPrimaryVertices(), PHSimpleKFProp::MoveToVertex(), psTOFTimezeroEval::printInputInfo(), SvtxEvaluatorHaiwang::printInputInfo(), PHTpcTrackSeedVertexAssoc::Process(), PHSimpleKFProp::Process(), PHHybridSeeding::Process(), SvtxSimPerformanceCheckReco::process_event(), QAG4SimulationVertex::process_event(), SimpleTrackingAnalysis::process_event(), GlobalVertexReco::process_event(), TPCGemGainCalb::process_event(), and DumpSvtxVertexMap::process_Node().
SvtxVertexMap::Iter SvtxVertexMap::end () virtual
Reimplemented in SvtxVertexMap_v1.
Definition at line 31 of file SvtxVertexMap.cc.
View newest version in sPHENIX GitHub at line 31 of file SvtxVertexMap.cc
References DummyVertexMap.
virtual size_t SvtxVertexMap::erase (unsigned int idkey) inline virtual
Reimplemented in SvtxVertexMap_v1.
Definition at line 39 of file SvtxVertexMap.h.
View newest version in sPHENIX GitHub at line 39 of file SvtxVertexMap.h
SvtxVertexMap::ConstIter SvtxVertexMap::find (unsigned int idkey) const virtual
Reimplemented in SvtxVertexMap_v1.
Definition at line 10 of file SvtxVertexMap.cc.
View newest version in sPHENIX GitHub at line 10 of file SvtxVertexMap.cc
References DummyVertexMap.
Referenced by PHTruthVertexing::assignStubsVertices(), PHActsToSvtxTracks::createSvtxTrack(), KFParticle_Tools::getTracksFromVertex(), PHSimpleKFProp::MoveToVertex(), and PHTpcTrackSeedVertexAssoc::Process().
SvtxVertexMap::Iter SvtxVertexMap::find (unsigned int idkey) virtual
Reimplemented in SvtxVertexMap_v1.
Definition at line 26 of file SvtxVertexMap.cc.
View newest version in sPHENIX GitHub at line 26 of file SvtxVertexMap.cc
References DummyVertexMap.
virtual const SvtxVertex* SvtxVertexMap::get (unsigned int idkey) const inline virtual
Reimplemented in SvtxVertexMap_v1.
Definition at line 31 of file SvtxVertexMap.h.
View newest version in sPHENIX GitHub at line 31 of file SvtxVertexMap.h
Referenced by PHActsVertexFinder::checkTrackVertexAssociation(), ActsEvaluator::evaluateTrackFits(), TruthConversionEval::get_primary_vertex(), PHActsVertexFinder::getTracks(), PHActsTrackProjection::getVertex(), PHActsTrkFitter::getVertex(), PHTpcResiduals::getVertex(), PHSimpleKFProp::MoveToFirstTPCCluster(), PHSiliconTpcTrackMatching::Process(), PHGenFitTrkProp::Process(), PHSiliconTruthTrackSeeding::Process(), PHRTreeSeeding::Process(), PHTruthSiliconAssociation::process_event(), BDiJetModule::process_event(), TpcPrototypeGenFitTrkFitter::process_event(), PHGenFitTrkFitter::process_event(), PHActsTrkFitter::updateSvtxTrack(), PHActsVertexFitter::updateSvtxVertex(), and PHHoughSeeding::vertexing().
virtual SvtxVertex* SvtxVertexMap::get (unsigned int idkey) inline virtual
Reimplemented in SvtxVertexMap_v1.
Definition at line 32 of file SvtxVertexMap.h.
View newest version in sPHENIX GitHub at line 32 of file SvtxVertexMap.h
void SvtxVertexMap::identify (std::ostream & os = std::cout) const inline override virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from PHObject.
Reimplemented in SvtxVertexMap_v1.
Definition at line 19 of file SvtxVertexMap.h.
View newest version in sPHENIX GitHub at line 19 of file SvtxVertexMap.h
References os.
Referenced by PHGenFitTrkFitter::FillSvtxVertexMap(), PHTruthVertexing::Process(), PHSiliconTruthTrackSeeding::Process(), and PHRaveVertexing::process_event().
virtual SvtxVertex* SvtxVertexMap::insert (SvtxVertex * cluster) inline virtual
Add vertex to container. Note the container take to ownership.
Reimplemented in SvtxVertexMap_v1.
Definition at line 35 of file SvtxVertexMap.h.
View newest version in sPHENIX GitHub at line 35 of file SvtxVertexMap.h
Referenced by PHActsVertexFitter::createActsSvtxVertex(), PHActsInitialVertexFinder::createDummyVertex(), PHActsVertexFinder::fillVertexMap(), PHActsInitialVertexFinder::fillVertexMap(), PHActsVertexFinder::Process(), and PHTruthVertexing::Process().
virtual SvtxVertex* SvtxVertexMap::insert_clone (const SvtxVertex * vertex) inline virtual
legacy interface. Add vertex to container. Note the container does not take ownership
Reimplemented in SvtxVertexMap_v1.
Definition at line 37 of file SvtxVertexMap.h.
View newest version in sPHENIX GitHub at line 37 of file SvtxVertexMap.h
Referenced by PHInitZVertexing::export_output(), PHPatternReco::export_output(), PHHoughSeeding::export_output(), PHRaveVertexing::FillSvtxVertexMap(), PHGenFitTrkFitter::FillSvtxVertexMap(), PHG4TrackFastSim::FillSvtxVertexMap(), and TpcPrototypeGenFitTrkFitter::FillSvtxVertexMap().
int SvtxVertexMap::isValid () const inline override virtual
isValid returns non zero if object contains vailid data
Reimplemented from PHObject.
Reimplemented in SvtxVertexMap_v1.
Definition at line 23 of file SvtxVertexMap.h.
View newest version in sPHENIX GitHub at line 23 of file SvtxVertexMap.h
virtual size_t SvtxVertexMap::size (void) const inline virtual
Reimplemented in SvtxVertexMap_v1.
Definition at line 27 of file SvtxVertexMap.h.
View newest version in sPHENIX GitHub at line 27 of file SvtxVertexMap.h
Referenced by psTOFTimezeroEval::printInputInfo(), SvtxEvaluatorHaiwang::printInputInfo(), SvtxEvaluator::printInputInfo(), PHGenFitTrkProp::Process(), TPCGemGainCalb::process_event(), KFParticle_sPHENIX::process_event(), TpcPrototypeGenFitTrkFitter::process_event(), PHGenFitTrkFitter::process_event(), DumpSvtxVertexMap::process_Node(), and PHHoughSeeding::vertexing().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/trackbase_historic/SvtxVertexMap.h
coresoftware/blob/master/offline/packages/trackbase_historic/SvtxVertexMap.cc