Analysis Software: Acts::Test::PropagatorState::Stepper Struct Reference
Acts::Test::PropagatorState::Stepper Struct Reference
This is a simple cache struct to mimic a Stepper.
Classes
struct State
Public Types
using Jacobian = BoundMatrix
using Covariance = BoundSquareMatrix
using BoundState = std::tuple< BoundTrackParameters, Jacobian, double >
using CurvilinearState = std::tuple< CurvilinearTrackParameters, Jacobian, double >
using BField = int
template<typename , typename >
using return_parameter_type = void
Public Member Functions
void resetState (State &, const BoundVector &, const BoundSquareMatrix &, const Surface &, const double) const
State resetter.
Vector3 position (const State &state) const
Global particle position accessor.
double time (const State &state) const
Time access.
Vector3 direction (const State &state) const
Momentum direction accessor.
double qOverP (const State &state) const
QoP accessor.
double absoluteMomentum (const State &state) const
Absolute momentum accessor.
Vector3 momentum (const State &state) const
Momentum accessor.
double charge (const State &state) const
Charge access.
double overstepLimit (const State &) const
Overstep limit access.
Intersection3D::Status updateSurfaceStatus (State &state, const Surface &surface, Direction navDir, const BoundaryCheck &bcheck, ActsScalar surfaceTolerance, const Logger &logger) const
template<typename object_intersection_t >
void updateStepSize (State &state, const object_intersection_t &oIntersection, Direction, bool release=true) const
void setStepSize (State &state, double stepSize, ConstrainedStep::Type stype=ConstrainedStep::actor, bool release=true) const
double getStepSize (const State &state, ConstrainedStep::Type stype) const
void releaseStepSize (State &state) const
std::string outputStepSize (const State &state) const
Result< BoundState > boundState (State &state, const Surface &surface, bool, const FreeToBoundCorrection &) const
CurvilinearState curvilinearState (State &state, bool) const
void update (State &, const FreeVector &, const BoundVector &, const Covariance &, const Surface &) const
void update (State &, const Vector3 &, const Vector3 &, double, double) const
void transportCovarianceToCurvilinear (State &) const
void transportCovarianceToBound (State &, const Surface &, const FreeToBoundCorrection &) const
Result< Vector3 > getField (State &, const Vector3 &) const
Detailed Description
This is a simple cache struct to mimic a Stepper.
Definition at line 67 of file NavigatorTests.cpp.
View newest version in sPHENIX GitHub at line 67 of file NavigatorTests.cpp
Member Typedef Documentation
using Acts::Test::PropagatorState::Stepper::BField = int
Definition at line 74 of file NavigatorTests.cpp.
View newest version in sPHENIX GitHub at line 74 of file NavigatorTests.cpp
using Acts::Test::PropagatorState::Stepper::BoundState = std::tuple<BoundTrackParameters, Jacobian, double>
Definition at line 71 of file NavigatorTests.cpp.
View newest version in sPHENIX GitHub at line 71 of file NavigatorTests.cpp
using Acts::Test::PropagatorState::Stepper::Covariance = BoundSquareMatrix
Definition at line 70 of file NavigatorTests.cpp.
View newest version in sPHENIX GitHub at line 70 of file NavigatorTests.cpp
using Acts::Test::PropagatorState::Stepper::CurvilinearState = std::tuple<CurvilinearTrackParameters, Jacobian, double>
Definition at line 73 of file NavigatorTests.cpp.
View newest version in sPHENIX GitHub at line 73 of file NavigatorTests.cpp
using Acts::Test::PropagatorState::Stepper::Jacobian = BoundMatrix
Definition at line 69 of file NavigatorTests.cpp.
View newest version in sPHENIX GitHub at line 69 of file NavigatorTests.cpp
template<typename , typename > using Acts::Test::PropagatorState::Stepper::return_parameter_type = void
Definition at line 77 of file NavigatorTests.cpp.
View newest version in sPHENIX GitHub at line 77 of file NavigatorTests.cpp
Member Function Documentation
double Acts::Test::PropagatorState::Stepper::absoluteMomentum (const State & state) const inline
Absolute momentum accessor.
Definition at line 135 of file NavigatorTests.cpp.
View newest version in sPHENIX GitHub at line 135 of file NavigatorTests.cpp
References Acts::Test::PropagatorState::Stepper::State::p.
Result<BoundState> Acts::Test::PropagatorState::Stepper::boundState (State & state, const Surface & surface, bool , const FreeToBoundCorrection &) const inline
Definition at line 184 of file NavigatorTests.cpp.
View newest version in sPHENIX GitHub at line 184 of file NavigatorTests.cpp
References Acts::GenericBoundTrackParameters< ParticleHypothesis >::create(), Acts::Test::PropagatorState::Stepper::State::dir, Acts::Surface::getSharedPtr(), testing::internal::move(), Acts::Test::PropagatorState::Stepper::State::p, Acts::Test::PropagatorState::Stepper::State::particleHypothesis, Acts::Test::PropagatorState::Stepper::State::pathAccumulated, Acts::Test::PropagatorState::Stepper::State::pos4, Acts::Test::PropagatorState::Stepper::State::q, and Acts::tgContext.
double Acts::Test::PropagatorState::Stepper::charge (const State & state) const inline
Charge access.
Definition at line 141 of file NavigatorTests.cpp.
View newest version in sPHENIX GitHub at line 141 of file NavigatorTests.cpp
References Acts::Test::PropagatorState::Stepper::State::q.
CurvilinearState Acts::Test::PropagatorState::Stepper::curvilinearState (State & state, bool) const inline
Definition at line 199 of file NavigatorTests.cpp.
View newest version in sPHENIX GitHub at line 199 of file NavigatorTests.cpp
References Acts::Test::PropagatorState::Stepper::State::dir, testing::internal::move(), Acts::Test::PropagatorState::Stepper::State::p, Dataset::parameters, Acts::Test::PropagatorState::Stepper::State::particleHypothesis, Acts::Test::PropagatorState::Stepper::State::pathAccumulated, Acts::Test::PropagatorState::Stepper::State::pos4, and Acts::Test::PropagatorState::Stepper::State::q.
Vector3 Acts::Test::PropagatorState::Stepper::direction (const State & state) const inline
Momentum direction accessor.
Definition at line 127 of file NavigatorTests.cpp.
View newest version in sPHENIX GitHub at line 127 of file NavigatorTests.cpp
References Acts::Test::PropagatorState::Stepper::State::dir.
Result<Vector3> Acts::Test::PropagatorState::Stepper::getField (State & , const Vector3 &) const inline
Definition at line 224 of file NavigatorTests.cpp.
View newest version in sPHENIX GitHub at line 224 of file NavigatorTests.cpp
double Acts::Test::PropagatorState::Stepper::getStepSize (const State & state, ConstrainedStep::Type stype) const inline
Definition at line 172 of file NavigatorTests.cpp.
View newest version in sPHENIX GitHub at line 172 of file NavigatorTests.cpp
References Acts::Test::PropagatorState::Stepper::State::stepSize, and Acts::ConstrainedStep::value().
Vector3 Acts::Test::PropagatorState::Stepper::momentum (const State & state) const inline
Momentum accessor.
Definition at line 138 of file NavigatorTests.cpp.
View newest version in sPHENIX GitHub at line 138 of file NavigatorTests.cpp
References Acts::Test::PropagatorState::Stepper::State::dir, and Acts::Test::PropagatorState::Stepper::State::p.
std::string Acts::Test::PropagatorState::Stepper::outputStepSize (const State & state) const inline
Definition at line 180 of file NavigatorTests.cpp.
View newest version in sPHENIX GitHub at line 180 of file NavigatorTests.cpp
References Acts::Test::PropagatorState::Stepper::State::stepSize, and Acts::ConstrainedStep::toString().
double Acts::Test::PropagatorState::Stepper::overstepLimit (const State &) const inline
Overstep limit access.
Definition at line 144 of file NavigatorTests.cpp.
View newest version in sPHENIX GitHub at line 144 of file NavigatorTests.cpp
References Acts::s_onSurfaceTolerance.
Vector3 Acts::Test::PropagatorState::Stepper::position (const State & state) const inline
Global particle position accessor.
Definition at line 119 of file NavigatorTests.cpp.
View newest version in sPHENIX GitHub at line 119 of file NavigatorTests.cpp
References Acts::ePos0, and Acts::Test::PropagatorState::Stepper::State::pos4.
Referenced by Acts::Test::BOOST_AUTO_TEST_CASE().
double Acts::Test::PropagatorState::Stepper::qOverP (const State & state) const inline
QoP accessor.
Definition at line 130 of file NavigatorTests.cpp.
View newest version in sPHENIX GitHub at line 130 of file NavigatorTests.cpp
References Acts::Test::PropagatorState::Stepper::State::p, and Acts::Test::PropagatorState::Stepper::State::q.
void Acts::Test::PropagatorState::Stepper::releaseStepSize (State & state) const inline
Definition at line 176 of file NavigatorTests.cpp.
View newest version in sPHENIX GitHub at line 176 of file NavigatorTests.cpp
References Acts::ConstrainedStep::actor, Acts::ConstrainedStep::release(), and Acts::Test::PropagatorState::Stepper::State::stepSize.
void Acts::Test::PropagatorState::Stepper::resetState (State & , const BoundVector & , const BoundSquareMatrix & , const Surface & , const double) const inline
State resetter.
Definition at line 113 of file NavigatorTests.cpp.
View newest version in sPHENIX GitHub at line 113 of file NavigatorTests.cpp
void Acts::Test::PropagatorState::Stepper::setStepSize (State & state, double stepSize, ConstrainedStep::Type stype = ConstrainedStep::actor, bool release = true) const inline
Definition at line 165 of file NavigatorTests.cpp.
View newest version in sPHENIX GitHub at line 165 of file NavigatorTests.cpp
References Acts::Test::PropagatorState::Stepper::State::previousStepSize, Acts::Test::PropagatorState::Stepper::State::stepSize, Acts::ConstrainedStep::update(), and Acts::ConstrainedStep::value().
double Acts::Test::PropagatorState::Stepper::time (const State & state) const inline
Time access.
Definition at line 124 of file NavigatorTests.cpp.
View newest version in sPHENIX GitHub at line 124 of file NavigatorTests.cpp
References Acts::eTime, and Acts::Test::PropagatorState::Stepper::State::pos4.
void Acts::Test::PropagatorState::Stepper::transportCovarianceToBound (State & , const Surface & , const FreeToBoundCorrection &) const inline
Definition at line 220 of file NavigatorTests.cpp.
View newest version in sPHENIX GitHub at line 220 of file NavigatorTests.cpp
void Acts::Test::PropagatorState::Stepper::transportCovarianceToCurvilinear (State &) const inline
Definition at line 218 of file NavigatorTests.cpp.
View newest version in sPHENIX GitHub at line 218 of file NavigatorTests.cpp
void Acts::Test::PropagatorState::Stepper::update (State & , const FreeVector & , const BoundVector & , const Covariance & , const Surface &) const inline
Definition at line 210 of file NavigatorTests.cpp.
View newest version in sPHENIX GitHub at line 210 of file NavigatorTests.cpp
void Acts::Test::PropagatorState::Stepper::update (State & , const Vector3 & , const Vector3 & , double , double) const inline
Definition at line 214 of file NavigatorTests.cpp.
View newest version in sPHENIX GitHub at line 214 of file NavigatorTests.cpp
template<typename object_intersection_t > void Acts::Test::PropagatorState::Stepper::updateStepSize (State & state, const object_intersection_t & oIntersection, Direction , bool release = true) const inline
Definition at line 159 of file NavigatorTests.cpp.
View newest version in sPHENIX GitHub at line 159 of file NavigatorTests.cpp
References filter::state.
Intersection3D::Status Acts::Test::PropagatorState::Stepper::updateSurfaceStatus (State & state, const Surface & surface, Direction navDir, const BoundaryCheck & bcheck, ActsScalar surfaceTolerance, const Logger & logger) const inline
Definition at line 148 of file NavigatorTests.cpp.
View newest version in sPHENIX GitHub at line 148 of file NavigatorTests.cpp
References logger(), Acts::Test::navDir, filter::state, and writeMapConfig::surface.
The documentation for this struct was generated from the following file:
acts/blob/sPHENIX/Tests/UnitTests/Core/Propagator/NavigatorTests.cpp