Analysis Software: Acts::DD4hepVolumeBuilder Class Reference
Acts::DD4hepVolumeBuilder Class Reference
build confined TrackingVolumes of one cylinder setup from DD4hep input.
#include <acts/blob/sPHENIX/Plugins/DD4hep/include/Acts/Plugins/DD4hep/DD4hepVolumeBuilder.hpp>
Classes
struct Config
Public Member Functions
DD4hepVolumeBuilder (const Acts::DD4hepVolumeBuilder::Config &config, std::unique_ptr< const Logger > logger)
~DD4hepVolumeBuilder () override
Destructor.
MutableTrackingVolumeVector centralVolumes () const final
Builder method for cylindrical, confined volume.
const std::string & identification () const final
void setConfiguration (const Config &config)
Config getConfiguration () const
void setLogger (std::unique_ptr< const Logger > logger)
Public Member Functions inherited from Acts::IConfinedTrackingVolumeBuilder
virtual ~IConfinedTrackingVolumeBuilder ()=default
Virtual destructor.
Private Member Functions
const Logger & logger () const
Acts::Transform3 convertTransform (const TGeoMatrix *tGeoTrans) const
Converter of the transformation of a volume from DD4hep to Acts formalism.
Private Attributes
Config m_cfg
Configuration object.
std::unique_ptr< const Logger > m_logger
Logging instance.
Detailed Description
build confined TrackingVolumes of one cylinder setup from DD4hep input.
This class is an implementation of the Acts::IConfinedTrackingVolumeBuilder, creating the central (volumes of barrel), the negative and positive volumes (volumes of endcaps) of one hierarchy (e.g. ECal, HCal...) with input from DD4hep.
Definition at line 42 of file DD4hepVolumeBuilder.hpp.
View newest version in sPHENIX GitHub at line 42 of file DD4hepVolumeBuilder.hpp
Constructor & Destructor Documentation
Acts::DD4hepVolumeBuilder::DD4hepVolumeBuilder (const Acts::DD4hepVolumeBuilder::Config & config, std::unique_ptr< const Logger > logger)
Constructor
Parameters
[in] config is the configuration struct
[in] logger is the logging instance
Definition at line 24 of file DD4hepVolumeBuilder.cpp.
View newest version in sPHENIX GitHub at line 24 of file DD4hepVolumeBuilder.cpp
References setConfiguration().
Acts::DD4hepVolumeBuilder::~DD4hepVolumeBuilder () override default
Destructor.
Member Function Documentation
std::vector< std::shared_ptr< Acts::TrackingVolume > > Acts::DD4hepVolumeBuilder::centralVolumes () const final virtual
Builder method for cylindrical, confined volume.
Returns
The vector of TrackingVolumes at the central sector
Implements Acts::IConfinedTrackingVolumeBuilder.
Definition at line 39 of file DD4hepVolumeBuilder.cpp.
View newest version in sPHENIX GitHub at line 39 of file DD4hepVolumeBuilder.cpp
References ACTS_ERROR, Acts::ACTS_VERBOSE(), Acts::UnitConstants::cm, Acts::TrackingVolume::create(), dz, m_cfg(), Acts::Test::transform, and volumes.
Acts::Transform3 Acts::DD4hepVolumeBuilder::convertTransform (const TGeoMatrix * tGeoTrans) const private
Converter of the transformation of a volume from DD4hep to Acts formalism.
Parameters
[in] tGeoTrans Transformation of the DD4hep DetElement
Returns
Pointer to the corresponding Acts transformation
Definition at line 89 of file DD4hepVolumeBuilder.cpp.
View newest version in sPHENIX GitHub at line 89 of file DD4hepVolumeBuilder.cpp
References Acts::UnitConstants::cm, Acts::TGeoPrimitivesHelper::makeTransform(), and translation().
DD4hepVolumeBuilder::Config Acts::DD4hepVolumeBuilder::getConfiguration () const inline
Get the configuration object
Returns
The used configuration struct
Definition at line 106 of file DD4hepVolumeBuilder.hpp.
View newest version in sPHENIX GitHub at line 106 of file DD4hepVolumeBuilder.hpp
References m_cfg.
const std::string & Acts::DD4hepVolumeBuilder::identification () const inline final virtual
Name identification
Returns
The string based identification of this configuration
Implements Acts::IConfinedTrackingVolumeBuilder.
Definition at line 102 of file DD4hepVolumeBuilder.hpp.
View newest version in sPHENIX GitHub at line 102 of file DD4hepVolumeBuilder.hpp
References Acts::DD4hepVolumeBuilder::Config::configurationName, and m_cfg.
const Logger& Acts::DD4hepVolumeBuilder::logger () const inline private
Private access to the logger
Returns
Used logger
Definition at line 92 of file DD4hepVolumeBuilder.hpp.
View newest version in sPHENIX GitHub at line 92 of file DD4hepVolumeBuilder.hpp
References m_logger.
void Acts::DD4hepVolumeBuilder::setConfiguration (const Config & config)
Set the configuration object
Parameters
[in] config is the configuration struct
Definition at line 33 of file DD4hepVolumeBuilder.cpp.
View newest version in sPHENIX GitHub at line 33 of file DD4hepVolumeBuilder.cpp
References filter::config, and m_cfg().
Referenced by DD4hepVolumeBuilder().
void Acts::DD4hepVolumeBuilder::setLogger (std::unique_ptr< const Logger > logger)
Set logging instance
Parameters
[in] logger Logger in use
Member Data Documentation
Config Acts::DD4hepVolumeBuilder::m_cfg private
Configuration object.
Definition at line 85 of file DD4hepVolumeBuilder.hpp.
View newest version in sPHENIX GitHub at line 85 of file DD4hepVolumeBuilder.hpp
Referenced by getConfiguration(), and identification().
std::unique_ptr<const Logger> Acts::DD4hepVolumeBuilder::m_logger private
Logging instance.
Definition at line 88 of file DD4hepVolumeBuilder.hpp.
View newest version in sPHENIX GitHub at line 88 of file DD4hepVolumeBuilder.hpp
Referenced by logger().
The documentation for this class was generated from the following files:
acts/blob/sPHENIX/Plugins/DD4hep/include/Acts/Plugins/DD4hep/DD4hepVolumeBuilder.hpp
acts/blob/sPHENIX/Plugins/DD4hep/src/DD4hepVolumeBuilder.cpp