Analysis Software: Acts::Experimental::detail::IndexedSurfacesGenerator< surface_container, indexed_updator > Struct Template Reference
Acts::Experimental::detail::IndexedSurfacesGenerator< surface_container, indexed_updator > Struct Template Reference
A templated indexed grid generator.
#include <acts/blob/sPHENIX/Core/include/Acts/Detector/detail/IndexedSurfacesGenerator.hpp>
Public Member Functions
template<typename axis_generator , typename reference_generator >
SurfaceCandidatesUpdator operator() (const GeometryContext &gctx, const axis_generator &aGenerator, const reference_generator &rGenerator) const
const Logger & logger () const
Public Attributes
surface_container surfaces = {}
std::vector< std::size_t > assignToAll = {}
std::vector< BinningValue > bValues = {}
The binning for the indexing.
std::vector< std::size_t > binExpansion = {}
Transform3 transform = Transform3::Identity()
The transform into the local binning schema.
std::unique_ptr< const Logger > oLogger
Screen output logger.
Detailed Description
template<typename surface_container, template< typename > class indexed_updator>
struct Acts::Experimental::detail::IndexedSurfacesGenerator< surface_container, indexed_updator >
A templated indexed grid generator.
This Generator creates a SurfaceCandidatesUpdator delegate which can then be used in the DetectorVolume class for updating given surface candidates based on an index grid.
It allows for:
certain indices being forcly assigned to all bins
a chosen expansion to fill indices in neighborhood bins
Template Parameters
objects_container the objects container
Definition at line 36 of file IndexedSurfacesGenerator.hpp.
View newest version in sPHENIX GitHub at line 36 of file IndexedSurfacesGenerator.hpp
Member Function Documentation
template<typename surface_container , template< typename > class indexed_updator> const Logger& Acts::Experimental::detail::IndexedSurfacesGenerator< surface_container, indexed_updator >::logger () const inline
Access to the logger
Returns
a const reference to the logger
Definition at line 104 of file IndexedSurfacesGenerator.hpp.
View newest version in sPHENIX GitHub at line 104 of file IndexedSurfacesGenerator.hpp
References Acts::Experimental::detail::IndexedSurfacesGenerator< surface_container, indexed_updator >::oLogger.
template<typename surface_container , template< typename > class indexed_updator> template<typename axis_generator , typename reference_generator > SurfaceCandidatesUpdator Acts::Experimental::detail::IndexedSurfacesGenerator< surface_container, indexed_updator >::operator() (const GeometryContext & gctx, const axis_generator & aGenerator, const reference_generator & rGenerator) const inline
Create the Surface candidate updator
Template Parameters
axis_generator does generate the axis of the grid
reference_generator does generate the reference query points
Parameters
gctx the geometry context
aGenerator the axis generator
rGenerator the reference generataor
Returns
a SurfaceCandidateUpdator delegate
Definition at line 63 of file IndexedSurfacesGenerator.hpp.
View newest version in sPHENIX GitHub at line 63 of file IndexedSurfacesGenerator.hpp
References ACTS_DEBUG, Acts::Experimental::detail::IndexedSurfacesGenerator< surface_container, indexed_updator >::assignToAll, Acts::Experimental::detail::IndexedSurfacesGenerator< surface_container, indexed_updator >::binExpansion, Acts::Experimental::detail::IndexedSurfacesGenerator< surface_container, indexed_updator >::bValues, Acts::enumerate(), grid(), testing::internal::move(), Acts::Experimental::detail::IndexedSurfacesGenerator< surface_container, indexed_updator >::oLogger, Acts::Experimental::detail::IndexedSurfacesGenerator< surface_container, indexed_updator >::surfaces, Acts::Experimental::detail::IndexedSurfacesGenerator< surface_container, indexed_updator >::transform, and Acts::KalmanVertexTrackUpdater::update().
Member Data Documentation
template<typename surface_container , template< typename > class indexed_updator> std::vector<std::size_t> Acts::Experimental::detail::IndexedSurfacesGenerator< surface_container, indexed_updator >::assignToAll = {}
Definition at line 41 of file IndexedSurfacesGenerator.hpp.
View newest version in sPHENIX GitHub at line 41 of file IndexedSurfacesGenerator.hpp
Referenced by Acts::Experimental::detail::IndexedSurfacesGenerator< surface_container, indexed_updator >::operator()().
template<typename surface_container , template< typename > class indexed_updator> std::vector<std::size_t> Acts::Experimental::detail::IndexedSurfacesGenerator< surface_container, indexed_updator >::binExpansion = {}
Definition at line 45 of file IndexedSurfacesGenerator.hpp.
View newest version in sPHENIX GitHub at line 45 of file IndexedSurfacesGenerator.hpp
Referenced by Acts::Experimental::detail::IndexedSurfacesGenerator< surface_container, indexed_updator >::operator()().
template<typename surface_container , template< typename > class indexed_updator> std::vector<BinningValue> Acts::Experimental::detail::IndexedSurfacesGenerator< surface_container, indexed_updator >::bValues = {}
The binning for the indexing.
Definition at line 43 of file IndexedSurfacesGenerator.hpp.
View newest version in sPHENIX GitHub at line 43 of file IndexedSurfacesGenerator.hpp
Referenced by Acts::Experimental::detail::IndexedSurfacesGenerator< surface_container, indexed_updator >::operator()().
template<typename surface_container , template< typename > class indexed_updator> std::unique_ptr<const Logger> Acts::Experimental::detail::IndexedSurfacesGenerator< surface_container, indexed_updator >::oLogger
Initial value:
=
      getDefaultLogger("IndexedSurfacesGenerator", Logging::INFO)
Screen output logger.
Definition at line 49 of file IndexedSurfacesGenerator.hpp.
View newest version in sPHENIX GitHub at line 49 of file IndexedSurfacesGenerator.hpp
Referenced by Acts::Experimental::detail::IndexedSurfacesGenerator< surface_container, indexed_updator >::logger(), and Acts::Experimental::detail::IndexedSurfacesGenerator< surface_container, indexed_updator >::operator()().
template<typename surface_container , template< typename > class indexed_updator> surface_container Acts::Experimental::detail::IndexedSurfacesGenerator< surface_container, indexed_updator >::surfaces = {}
The surfaces to be indexed (including surfaces that are assigned to all bins)
Definition at line 39 of file IndexedSurfacesGenerator.hpp.
View newest version in sPHENIX GitHub at line 39 of file IndexedSurfacesGenerator.hpp
Referenced by Acts::Experimental::detail::IndexedSurfacesGenerator< surface_container, indexed_updator >::operator()().
template<typename surface_container , template< typename > class indexed_updator> Transform3 Acts::Experimental::detail::IndexedSurfacesGenerator< surface_container, indexed_updator >::transform = Transform3::Identity()
The transform into the local binning schema.
Definition at line 47 of file IndexedSurfacesGenerator.hpp.
View newest version in sPHENIX GitHub at line 47 of file IndexedSurfacesGenerator.hpp
Referenced by Acts::Experimental::detail::IndexedSurfacesGenerator< surface_container, indexed_updator >::operator()().
The documentation for this struct was generated from the following file:
acts/blob/sPHENIX/Core/include/Acts/Detector/detail/IndexedSurfacesGenerator.hpp