Analysis Software: Acts::Sycl::SeedFinder< external_spacepoint_t > Class Template Reference
Acts::Sycl::SeedFinder< external_spacepoint_t > Class Template Reference
#include <acts/blob/sPHENIX/Plugins/Sycl/include/Acts/Plugins/Sycl/Seeding/SeedFinder.hpp>
Public Member Functions
SeedFinder (Acts::SeedFinderConfig< external_spacepoint_t > config, const Acts::SeedFinderOptions &options, const Acts::Sycl::DeviceExperimentCuts &cuts, Acts::Sycl::QueueWrapper wrappedQueue, vecmem::memory_resource &resource, vecmem::memory_resource *device_resource=nullptr)
~SeedFinder ()=default
SeedFinder ()=delete
SeedFinder (const SeedFinder< external_spacepoint_t > &)=delete
SeedFinder
< external_spacepoint_t > & operator= (const SeedFinder< external_spacepoint_t > &)=delete
template<typename sp_range_t >
std::vector< Seed
< external_spacepoint_t > > createSeedsForGroup (Acts::SpacePointData &spacePointData, Acts::SpacePointGrid< external_spacepoint_t > &grid, const sp_range_t &bottomSPs, const std::size_t middleSPs, const sp_range_t &topSPs) const
Private Attributes
Acts::SeedFinderConfig
< external_spacepoint_t > m_config
Acts::SeedFinderOptions m_options
Acts::Sycl::DeviceExperimentCuts m_deviceCuts
Experiment specific cuts.
Acts::Sycl::detail::DeviceSeedFinderConfig m_deviceConfig
Configuration object for the device side.
QueueWrapper m_wrappedQueue
Wrapper around a SYCL queue object.
vecmem::memory_resource * m_resource
host/shared memory resource to use in the seed-finder
vecmem::memory_resource * m_device_resource
Device memory resource for use.
Detailed Description
template<typename external_spacepoint_t>
class Acts::Sycl::SeedFinder< external_spacepoint_t >
Definition at line 27 of file SeedFinder.hpp.
View newest version in sPHENIX GitHub at line 27 of file SeedFinder.hpp
Constructor & Destructor Documentation
template<typename external_spacepoint_t > Acts::Sycl::SeedFinder< external_spacepoint_t >::SeedFinder (Acts::SeedFinderConfig< external_spacepoint_t > config, const Acts::SeedFinderOptions & options, const Acts::Sycl::DeviceExperimentCuts & cuts, Acts::Sycl::QueueWrapper wrappedQueue, vecmem::memory_resource & resource, vecmem::memory_resource * device_resource = nullptr)
Definition at line 28 of file SeedFinder.ipp.
View newest version in sPHENIX GitHub at line 28 of file SeedFinder.ipp
References Acts::SeedFinderConfig< SpacePoint >::collisionRegionMax, Acts::SeedFinderConfig< SpacePoint >::collisionRegionMin, Acts::SeedFinderConfig< SpacePoint >::cotThetaMax, Acts::SeedFinderConfig< SpacePoint >::deltaRMax, Acts::SeedFinderConfig< SpacePoint >::deltaRMin, Acts::SeedFinderConfig< SpacePoint >::impactMax, Acts::Sycl::SeedFinder< external_spacepoint_t >::m_config, Acts::Sycl::SeedFinder< external_spacepoint_t >::m_deviceConfig, Acts::Sycl::SeedFinder< external_spacepoint_t >::m_options, Acts::SeedFinderConfig< SpacePoint >::maxScatteringAngle2, Acts::SeedFinderOptions::minHelixDiameter2, Acts::SeedFinderOptions::pT2perRadius, Acts::SeedFinderConfig< SpacePoint >::seedFilter, and Acts::SeedFinderConfig< SpacePoint >::sigmaScattering.
template<typename external_spacepoint_t > Acts::Sycl::SeedFinder< external_spacepoint_t >::~SeedFinder () default
template<typename external_spacepoint_t > Acts::Sycl::SeedFinder< external_spacepoint_t >::SeedFinder () delete
template<typename external_spacepoint_t > Acts::Sycl::SeedFinder< external_spacepoint_t >::SeedFinder (const SeedFinder< external_spacepoint_t > &) delete
Member Function Documentation
template<typename external_spacepoint_t > template<typename sp_range_t > std::vector< Acts::Seed< external_spacepoint_t > > Acts::Sycl::SeedFinder< external_spacepoint_t >::createSeedsForGroup (Acts::SpacePointData & spacePointData, Acts::SpacePointGrid< external_spacepoint_t > & grid, const sp_range_t & bottomSPs, const std::size_t middleSPs, const sp_range_t & topSPs) const
Create all seeds from the space points in the three iterators. Can be used to parallelize the seed creation
Parameters
bottomSPs group of space points to be used as innermost SP in a seed.
middleSPs group of space points to be used as middle SP in a seed.
topSPs group of space points to be used as outermost SP in a seed. Ranges must return pointers. Ranges must be separate objects for each parallel call.
Returns
vector in which all found seeds for this group are stored.
Definition at line 65 of file SeedFinder.ipp.
View newest version in sPHENIX GitHub at line 65 of file SeedFinder.ipp
References Acts::detail::Grid< T, Axes >::at(), Acts::Sycl::createSeedsForGroupSycl(), j, Acts::Experimental::detail::BlueprintHelper::sort(), and ActsExamples::SP.
template<typename external_spacepoint_t > SeedFinder<external_spacepoint_t>& Acts::Sycl::SeedFinder< external_spacepoint_t >::operator= (const SeedFinder< external_spacepoint_t > &) delete
Member Data Documentation
template<typename external_spacepoint_t > Acts::SeedFinderConfig<external_spacepoint_t> Acts::Sycl::SeedFinder< external_spacepoint_t >::m_config private
Definition at line 58 of file SeedFinder.hpp.
View newest version in sPHENIX GitHub at line 58 of file SeedFinder.hpp
Referenced by Acts::Sycl::SeedFinder< external_spacepoint_t >::SeedFinder().
template<typename external_spacepoint_t > vecmem::memory_resource* Acts::Sycl::SeedFinder< external_spacepoint_t >::m_device_resource private
Device memory resource for use.
Definition at line 74 of file SeedFinder.hpp.
View newest version in sPHENIX GitHub at line 74 of file SeedFinder.hpp
template<typename external_spacepoint_t > Acts::Sycl::detail::DeviceSeedFinderConfig Acts::Sycl::SeedFinder< external_spacepoint_t >::m_deviceConfig private
Configuration object for the device side.
Definition at line 65 of file SeedFinder.hpp.
View newest version in sPHENIX GitHub at line 65 of file SeedFinder.hpp
Referenced by Acts::Sycl::SeedFinder< external_spacepoint_t >::SeedFinder().
template<typename external_spacepoint_t > Acts::Sycl::DeviceExperimentCuts Acts::Sycl::SeedFinder< external_spacepoint_t >::m_deviceCuts private
Experiment specific cuts.
Definition at line 62 of file SeedFinder.hpp.
View newest version in sPHENIX GitHub at line 62 of file SeedFinder.hpp
template<typename external_spacepoint_t > Acts::SeedFinderOptions Acts::Sycl::SeedFinder< external_spacepoint_t >::m_options private
Definition at line 59 of file SeedFinder.hpp.
View newest version in sPHENIX GitHub at line 59 of file SeedFinder.hpp
Referenced by Acts::Sycl::SeedFinder< external_spacepoint_t >::SeedFinder().
template<typename external_spacepoint_t > vecmem::memory_resource* Acts::Sycl::SeedFinder< external_spacepoint_t >::m_resource private
host/shared memory resource to use in the seed-finder
Definition at line 71 of file SeedFinder.hpp.
View newest version in sPHENIX GitHub at line 71 of file SeedFinder.hpp
template<typename external_spacepoint_t > QueueWrapper Acts::Sycl::SeedFinder< external_spacepoint_t >::m_wrappedQueue private
Wrapper around a SYCL queue object.
Definition at line 68 of file SeedFinder.hpp.
View newest version in sPHENIX GitHub at line 68 of file SeedFinder.hpp
The documentation for this class was generated from the following files:
acts/blob/sPHENIX/Plugins/Sycl/include/Acts/Plugins/Sycl/Seeding/SeedFinder.hpp
acts/blob/sPHENIX/Plugins/Sycl/include/Acts/Plugins/Sycl/Seeding/SeedFinder.ipp