Analysis Software: acts/blob/sPHENIX/Tests/UnitTests/Core/EventData/ParticleHypothesisTests.cpp File Reference
ParticleHypothesisTests.cpp File Reference
#include <boost/test/unit_test.hpp>
#include "Acts/Definitions/Units.hpp"
#include "Acts/EventData/Charge.hpp"
#include "Acts/EventData/ParticleHypothesis.hpp"
#include "Acts/Tests/CommonHelpers/FloatComparisons.hpp"
#include <limits>
#include <type_traits>
Functions
BOOST_AUTO_TEST_CASE (Neutral)
BOOST_AUTO_TEST_CASE (SinglyCharged)
BOOST_AUTO_TEST_CASE (NonNeutralChargeSingle)
BOOST_AUTO_TEST_CASE (NonNeutralChargeMultiple)
BOOST_AUTO_TEST_CASE (AnyChargeNeutral)
BOOST_AUTO_TEST_CASE (AnyChargeSingle)
BOOST_AUTO_TEST_CASE (AnyChargeMultiple)
Variables
static auto eps = std::numeric_limits<double>::epsilon()
Function Documentation
BOOST_AUTO_TEST_CASE (Neutral)
Definition at line 25 of file ParticleHypothesisTests.cpp.
View newest version in sPHENIX GitHub at line 25 of file ParticleHypothesisTests.cpp
References CHECK_CLOSE_REL, eps, and merge_hashes::p.
BOOST_AUTO_TEST_CASE (SinglyCharged)
Definition at line 36 of file ParticleHypothesisTests.cpp.
View newest version in sPHENIX GitHub at line 36 of file ParticleHypothesisTests.cpp
References CHECK_CLOSE_REL, eps, merge_hashes::p, and pion.
BOOST_AUTO_TEST_CASE (NonNeutralChargeSingle)
Definition at line 48 of file ParticleHypothesisTests.cpp.
View newest version in sPHENIX GitHub at line 48 of file ParticleHypothesisTests.cpp
References CHECK_CLOSE_REL, eps, merge_hashes::p, and Acts::NonNeutralChargedParticleHypothesis::pion().
BOOST_AUTO_TEST_CASE (NonNeutralChargeMultiple)
Definition at line 60 of file ParticleHypothesisTests.cpp.
View newest version in sPHENIX GitHub at line 60 of file ParticleHypothesisTests.cpp
References CHECK_CLOSE_REL, eps, merge_hashes::p, and Acts::NonNeutralChargedParticleHypothesis::pionLike().
BOOST_AUTO_TEST_CASE (AnyChargeNeutral)
Definition at line 72 of file ParticleHypothesisTests.cpp.
View newest version in sPHENIX GitHub at line 72 of file ParticleHypothesisTests.cpp
References CHECK_CLOSE_REL, eps, merge_hashes::p, and Acts::ParticleHypothesis::pion0().
BOOST_AUTO_TEST_CASE (AnyChargeSingle)
Definition at line 87 of file ParticleHypothesisTests.cpp.
View newest version in sPHENIX GitHub at line 87 of file ParticleHypothesisTests.cpp
References CHECK_CLOSE_REL, eps, merge_hashes::p, and Acts::ParticleHypothesis::pion().
BOOST_AUTO_TEST_CASE (AnyChargeMultiple)
Definition at line 99 of file ParticleHypothesisTests.cpp.
View newest version in sPHENIX GitHub at line 99 of file ParticleHypothesisTests.cpp
References CHECK_CLOSE_REL, eps, merge_hashes::p, and Acts::ParticleHypothesis::pionLike().
Variable Documentation
auto eps = std::numeric_limits<double>::epsilon() static
Definition at line 21 of file ParticleHypothesisTests.cpp.
View newest version in sPHENIX GitHub at line 21 of file ParticleHypothesisTests.cpp
Referenced by BOOST_AUTO_TEST_CASE().