Analysis Software: TrackSeed_FastSim_v1 Class Reference
TrackSeed_FastSim_v1 Class Reference
#include <coresoftware/blob/master/offline/packages/trackbase_historic/TrackSeed_FastSim_v1.h>
Public Member Functions
TrackSeed_FastSim_v1 ()=default
TrackSeed_FastSim_v1 (const TrackSeed &)
~TrackSeed_FastSim_v1 ()=default
void identify (std::ostream &os=std::cout) const override
void Reset () override
Clear Event.
int isValid () const override
isValid returns non zero if object contains vailid data
void CopyFrom (const TrackSeed &) override
void CopyFrom (TrackSeed *seed) override
PHObject * CloneMe () const override
Virtual copy constructor.
unsigned int get_truth_track_id () const override
unsigned int get_num_measurements () const override
const HitIdMap & g4hit_ids () const override
bool empty_g4hit_id () const override
size_t size_g4hit_id () const override
TrackSeed::HitIdConstIter begin_g4hit_id () const override
TrackSeed::HitIdConstIter end_g4hit_id () const override
TrackSeed::HitIdConstIter find_g4hit_id (int volume) const override
float get_phi (TrkrClusterContainer *clusters, ActsGeometry *tGeometry) const override
void set_truth_track_id (unsigned int truthTrackId) override
void set_num_measurements (int nmeas) override
void add_g4hit_id (int volume, PHG4HitDefs::keytype id) override
size_t remove_g4hit_id (int volume, PHG4HitDefs::keytype id) override
size_t remove_g4hit_volume (int volume) override
TrackSeed::HitIdIter begin_g4hit_id () override
TrackSeed::HitIdIter end_g4hit_id () override
TrackSeed::HitIdIter find_g4hit_id (int volume) override
void clear_g4hit_id () override
Public Member Functions inherited from TrackSeed_v1
TrackSeed_v1 ()
TrackSeed_v1 (const TrackSeed &)
Copy constructors.
TrackSeed_v1 (const TrackSeed_v1 &)
TrackSeed_v1 & operator= (const TrackSeed_v1 &seed)
~TrackSeed_v1 () override
void identify (std::ostream &os=std::cout) const override
void Reset () override
Clear Event.
int isValid () const override
isValid returns non zero if object contains vailid data
void CopyFrom (const TrackSeed &) override
void CopyFrom (TrackSeed *seed) override
PHObject * CloneMe () const override
Virtual copy constructor.
int get_charge () const override
float get_px (TrkrClusterContainer *clusters, ActsGeometry *tGeometry) const override
We need access to the first two clusters to get the phi angle right.
float get_py (TrkrClusterContainer *clusters, ActsGeometry *tGeometry) const override
float get_pz () const override
float get_x () const override
float get_y () const override
float get_z () const override
float get_phi (TrkrClusterContainer *clusters, ActsGeometry *tGeometry) const override
float get_phi (std::map< TrkrDefs::cluskey, Acts::Vector3 > &positions) const override
float get_eta () const override
float get_theta () const override
float get_pt () const override
float get_p () const override
float get_qOverR () const override
float get_X0 () const override
float get_Y0 () const override
float get_slope () const override
float get_Z0 () const override
short int get_crossing () const override
void set_crossing (const short int crossing) override
void set_qOverR (const float qOverR) override
void set_X0 (const float X0) override
void set_Y0 (const float Y0) override
void set_slope (const float slope) override
void set_Z0 (const float Z0) override
void clear_cluster_keys () override
bool empty_cluster_keys () const override
size_t size_cluster_keys () const override
void insert_cluster_key (TrkrDefs::cluskey clusterid) override
size_t erase_cluster_key (TrkrDefs::cluskey clusterid) override
ConstClusterKeyIter find_cluster_key (TrkrDefs::cluskey clusterid) const override
ConstClusterKeyIter begin_cluster_keys () const override
ConstClusterKeyIter end_cluster_keys () const override
ClusterKeyIter find_cluster_keys (unsigned int clusterid) override
ClusterKeyIter begin_cluster_keys () override
ClusterKeyIter end_cluster_keys () override
void circleFitByTaubin (TrkrClusterContainer *clusters, ActsGeometry *tGeometry, uint8_t startLayer=0, uint8_t endLayer=58) override
Updates R, X0, Y0.
void lineFit (TrkrClusterContainer *clusters, ActsGeometry *tGeometry, uint8_t startLayer=0, uint8_t endLayer=58) override
Updates r-z slope and intercept B.
void circleFitByTaubin (std::map< TrkrDefs::cluskey, Acts::Vector3 > &positions, uint8_t startLayer=0, uint8_t endLayer=58) override
void lineFit (std::map< TrkrDefs::cluskey, Acts::Vector3 > &positions, uint8_t startLayer=0, uint8_t endLayer=58) override
Public Member Functions inherited from TrackSeed
~TrackSeed () override=default
virtual void set_silicon_seed_index (const unsigned int)
virtual void set_tpc_seed_index (const unsigned int)
virtual unsigned int get_silicon_seed_index () const
virtual unsigned int get_tpc_seed_index () const
virtual void set_crossing_estimate (const short int)
virtual short int get_crossing_estimate () const
Public Member Functions inherited from PHObject
PHObject ()
ctor
~PHObject () override
dtor
virtual PHObject * clone () const final
PHObject * Clone (const char *newname="") const final
void Copy (TObject &object) const final
virtual int Integrate () const
virtual int Integrate (PHObject *)
virtual void CopyFrom (const PHObject *obj)
Private Attributes
unsigned int m_truth_track_id = std::numeric_limits<unsigned int>::max()
unsigned int m_nmeas = 0
HitIdMap m_g4hit_ids
Additional Inherited Members
Public Types inherited from TrackSeed
typedef std::set
< TrkrDefs::cluskey > ClusterKeySet
typedef
ClusterKeySet::const_iterator ConstClusterKeyIter
typedef ClusterKeySet::iterator ClusterKeyIter
typedef std::map< int,
std::set< PHG4HitDefs::keytype > > HitIdMap
typedef HitIdMap::iterator HitIdIter
typedef HitIdMap::const_iterator HitIdConstIter
Protected Member Functions inherited from TrackSeed_v1
std::pair< float, float > findRoot () const
Returns transverse PCA to (0,0)
Detailed Description
Definition at line 8 of file TrackSeed_FastSim_v1.h.
View newest version in sPHENIX GitHub at line 8 of file TrackSeed_FastSim_v1.h
Constructor & Destructor Documentation
TrackSeed_FastSim_v1::TrackSeed_FastSim_v1 () default
Referenced by CloneMe(), and Reset().
TrackSeed_FastSim_v1::TrackSeed_FastSim_v1 (const TrackSeed & source)
Definition at line 6 of file TrackSeed_FastSim_v1.cc.
View newest version in sPHENIX GitHub at line 6 of file TrackSeed_FastSim_v1.cc
References CopyFrom().
TrackSeed_FastSim_v1::~TrackSeed_FastSim_v1 () default
Member Function Documentation
void TrackSeed_FastSim_v1::add_g4hit_id (int volume, PHG4HitDefs::keytype id) inline override virtual
Reimplemented from TrackSeed.
Definition at line 60 of file TrackSeed_FastSim_v1.h.
View newest version in sPHENIX GitHub at line 60 of file TrackSeed_FastSim_v1.h
References m_g4hit_ids.
TrackSeed::HitIdConstIter TrackSeed_FastSim_v1::begin_g4hit_id () const inline override virtual
Reimplemented from TrackSeed.
Definition at line 40 of file TrackSeed_FastSim_v1.h.
View newest version in sPHENIX GitHub at line 40 of file TrackSeed_FastSim_v1.h
References m_g4hit_ids.
TrackSeed::HitIdIter TrackSeed_FastSim_v1::begin_g4hit_id () inline override virtual
Reimplemented from TrackSeed.
Definition at line 69 of file TrackSeed_FastSim_v1.h.
View newest version in sPHENIX GitHub at line 69 of file TrackSeed_FastSim_v1.h
References m_g4hit_ids.
void TrackSeed_FastSim_v1::clear_g4hit_id () inline override virtual
Reimplemented from TrackSeed.
Definition at line 78 of file TrackSeed_FastSim_v1.h.
View newest version in sPHENIX GitHub at line 78 of file TrackSeed_FastSim_v1.h
References m_g4hit_ids.
PHObject* TrackSeed_FastSim_v1::CloneMe () const inline override virtual
Virtual copy constructor.
Reimplemented from TrackSeed.
Definition at line 23 of file TrackSeed_FastSim_v1.h.
View newest version in sPHENIX GitHub at line 23 of file TrackSeed_FastSim_v1.h
References TrackSeed_FastSim_v1().
void TrackSeed_FastSim_v1::CopyFrom (const TrackSeed & source) override virtual
Reimplemented from TrackSeed.
Definition at line 9 of file TrackSeed_FastSim_v1.cc.
View newest version in sPHENIX GitHub at line 9 of file TrackSeed_FastSim_v1.cc
References TrackSeed_v1::CopyFrom(), TrackSeed::g4hit_ids(), TrackSeed::get_num_measurements(), TrackSeed::get_truth_track_id(), m_g4hit_ids, m_nmeas, and m_truth_track_id.
Referenced by TrackSeed_FastSim_v1().
void TrackSeed_FastSim_v1::CopyFrom (TrackSeed * seed) inline override virtual
Reimplemented from TrackSeed.
Definition at line 21 of file TrackSeed_FastSim_v1.h.
View newest version in sPHENIX GitHub at line 21 of file TrackSeed_FastSim_v1.h
References CopyFrom().
Referenced by CopyFrom().
bool TrackSeed_FastSim_v1::empty_g4hit_id () const inline override virtual
Reimplemented from TrackSeed.
Definition at line 34 of file TrackSeed_FastSim_v1.h.
View newest version in sPHENIX GitHub at line 34 of file TrackSeed_FastSim_v1.h
References m_g4hit_ids.
TrackSeed::HitIdConstIter TrackSeed_FastSim_v1::end_g4hit_id () const inline override virtual
Reimplemented from TrackSeed.
Definition at line 43 of file TrackSeed_FastSim_v1.h.
View newest version in sPHENIX GitHub at line 43 of file TrackSeed_FastSim_v1.h
References m_g4hit_ids.
TrackSeed::HitIdIter TrackSeed_FastSim_v1::end_g4hit_id () inline override virtual
Reimplemented from TrackSeed.
Definition at line 72 of file TrackSeed_FastSim_v1.h.
View newest version in sPHENIX GitHub at line 72 of file TrackSeed_FastSim_v1.h
References m_g4hit_ids.
TrackSeed::HitIdConstIter TrackSeed_FastSim_v1::find_g4hit_id (int volume) const inline override virtual
Reimplemented from TrackSeed.
Definition at line 46 of file TrackSeed_FastSim_v1.h.
View newest version in sPHENIX GitHub at line 46 of file TrackSeed_FastSim_v1.h
References m_g4hit_ids.
TrackSeed::HitIdIter TrackSeed_FastSim_v1::find_g4hit_id (int volume) inline override virtual
Reimplemented from TrackSeed.
Definition at line 75 of file TrackSeed_FastSim_v1.h.
View newest version in sPHENIX GitHub at line 75 of file TrackSeed_FastSim_v1.h
References m_g4hit_ids.
const HitIdMap& TrackSeed_FastSim_v1::g4hit_ids () const inline override virtual
Reimplemented from TrackSeed.
Definition at line 31 of file TrackSeed_FastSim_v1.h.
View newest version in sPHENIX GitHub at line 31 of file TrackSeed_FastSim_v1.h
References m_g4hit_ids.
unsigned int TrackSeed_FastSim_v1::get_num_measurements () const inline override virtual
Reimplemented from TrackSeed.
Definition at line 28 of file TrackSeed_FastSim_v1.h.
View newest version in sPHENIX GitHub at line 28 of file TrackSeed_FastSim_v1.h
References m_nmeas.
float TrackSeed_FastSim_v1::get_phi (TrkrClusterContainer * clusters, ActsGeometry * tGeometry) const override virtual
We need a separate function for truth tracks because the bend angle is already properly accounted for
Reimplemented from TrackSeed.
Definition at line 41 of file TrackSeed_FastSim_v1.cc.
View newest version in sPHENIX GitHub at line 41 of file TrackSeed_FastSim_v1.cc
References TrackSeed_v1::findRoot(), TrackSeed_v1::get_X0(), TrackSeed_v1::get_Y0(), ambiguity_solver_full_chain::x, and y.
unsigned int TrackSeed_FastSim_v1::get_truth_track_id () const inline override virtual
Reimplemented from TrackSeed.
Definition at line 25 of file TrackSeed_FastSim_v1.h.
View newest version in sPHENIX GitHub at line 25 of file TrackSeed_FastSim_v1.h
References m_truth_track_id.
void TrackSeed_FastSim_v1::identify (std::ostream & os = std::cout) const override virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from TrackSeed.
Definition at line 23 of file TrackSeed_FastSim_v1.cc.
View newest version in sPHENIX GitHub at line 23 of file TrackSeed_FastSim_v1.cc
References TrackSeed_v1::identify(), m_g4hit_ids, m_nmeas, and m_truth_track_id.
int TrackSeed_FastSim_v1::isValid () const inline override virtual
isValid returns non zero if object contains vailid data
Reimplemented from TrackSeed.
Definition at line 19 of file TrackSeed_FastSim_v1.h.
View newest version in sPHENIX GitHub at line 19 of file TrackSeed_FastSim_v1.h
size_t TrackSeed_FastSim_v1::remove_g4hit_id (int volume, PHG4HitDefs::keytype id) inline override virtual
Reimplemented from TrackSeed.
Definition at line 63 of file TrackSeed_FastSim_v1.h.
View newest version in sPHENIX GitHub at line 63 of file TrackSeed_FastSim_v1.h
References m_g4hit_ids.
size_t TrackSeed_FastSim_v1::remove_g4hit_volume (int volume) inline override virtual
Reimplemented from TrackSeed.
Definition at line 66 of file TrackSeed_FastSim_v1.h.
View newest version in sPHENIX GitHub at line 66 of file TrackSeed_FastSim_v1.h
References m_g4hit_ids.
void TrackSeed_FastSim_v1::Reset () inline override virtual
Clear Event.
Reimplemented from PHObject.
Definition at line 18 of file TrackSeed_FastSim_v1.h.
View newest version in sPHENIX GitHub at line 18 of file TrackSeed_FastSim_v1.h
References TrackSeed_FastSim_v1().
void TrackSeed_FastSim_v1::set_num_measurements (int nmeas) inline override virtual
Reimplemented from TrackSeed.
Definition at line 57 of file TrackSeed_FastSim_v1.h.
View newest version in sPHENIX GitHub at line 57 of file TrackSeed_FastSim_v1.h
References m_nmeas.
void TrackSeed_FastSim_v1::set_truth_track_id (unsigned int truthTrackId) inline override virtual
Reimplemented from TrackSeed.
Definition at line 54 of file TrackSeed_FastSim_v1.h.
View newest version in sPHENIX GitHub at line 54 of file TrackSeed_FastSim_v1.h
References m_truth_track_id.
size_t TrackSeed_FastSim_v1::size_g4hit_id () const inline override virtual
Reimplemented from TrackSeed.
Definition at line 37 of file TrackSeed_FastSim_v1.h.
View newest version in sPHENIX GitHub at line 37 of file TrackSeed_FastSim_v1.h
References m_g4hit_ids.
Member Data Documentation
HitIdMap TrackSeed_FastSim_v1::m_g4hit_ids private
Definition at line 85 of file TrackSeed_FastSim_v1.h.
View newest version in sPHENIX GitHub at line 85 of file TrackSeed_FastSim_v1.h
Referenced by add_g4hit_id(), begin_g4hit_id(), clear_g4hit_id(), CopyFrom(), empty_g4hit_id(), end_g4hit_id(), find_g4hit_id(), g4hit_ids(), identify(), remove_g4hit_id(), remove_g4hit_volume(), and size_g4hit_id().
unsigned int TrackSeed_FastSim_v1::m_nmeas = 0 private
Definition at line 84 of file TrackSeed_FastSim_v1.h.
View newest version in sPHENIX GitHub at line 84 of file TrackSeed_FastSim_v1.h
Referenced by CopyFrom(), get_num_measurements(), identify(), and set_num_measurements().
unsigned int TrackSeed_FastSim_v1::m_truth_track_id = std::numeric_limits<unsigned int>::max() private
Definition at line 83 of file TrackSeed_FastSim_v1.h.
View newest version in sPHENIX GitHub at line 83 of file TrackSeed_FastSim_v1.h
Referenced by CopyFrom(), get_truth_track_id(), identify(), and set_truth_track_id().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/trackbase_historic/TrackSeed_FastSim_v1.h
coresoftware/blob/master/offline/packages/trackbase_historic/TrackSeed_FastSim_v1.cc