Analysis Software: Acts::DetectorJsonConverter Namespace Reference
Acts::DetectorJsonConverter Namespace Reference
Classes
struct Options
Functions
nlohmann::json toJson (const GeometryContext &gctx, const Experimental::Detector &detector, const Options &options=Options{})
Convert to json format.
nlohmann::json toJsonDetray (const GeometryContext &gctx, const Experimental::Detector &detector, const Options &options=Options{})
Convert to detray json format.
std::shared_ptr
< Experimental::Detector > fromJson (const GeometryContext &gctx, const nlohmann::json &jDetector)
convert from json format
Function Documentation
std::shared_ptr< Acts::Experimental::Detector > Acts::DetectorJsonConverter::fromJson (const GeometryContext & gctx, const nlohmann::json & jDetector)
convert from json format
Parameters
gctx the geometry context
jDetector the json object
Returns
a newly created shared Detector object
Definition at line 140 of file DetectorJsonConverter.cpp.
View newest version in sPHENIX GitHub at line 140 of file DetectorJsonConverter.cpp
References Acts::enumerate(), Acts::Transform3JsonConverter::fromJson(), perf_headwind::name, Acts::Experimental::tryRootVolumes(), testSigmaEff::v, and volumes.
Referenced by Acts::Python::addJson(), and BOOST_AUTO_TEST_CASE().
nlohmann::json Acts::DetectorJsonConverter::toJson (const GeometryContext & gctx, const Experimental::Detector & detector, const Options & options = Options{})
Convert to json format.
Parameters
gctx the geometry context
detector the detector instance
options the writing options that propagate to the downstream converters
Returns
a json object
Definition at line 25 of file DetectorJsonConverter.cpp.
View newest version in sPHENIX GitHub at line 25 of file DetectorJsonConverter.cpp
References Acts::Experimental::Detector::name(), Acts::DetectorVolumeJsonConverter::Options::portalOptions, Acts::Test::time, Acts::Transform3JsonConverter::toJson(), Acts::DetectorJsonConverter::Options::volumeOptions, volumes, and Acts::Experimental::Detector::volumes().
Referenced by Acts::Python::addJson(), and BOOST_AUTO_TEST_CASE().
nlohmann::json Acts::DetectorJsonConverter::toJsonDetray (const GeometryContext & gctx, const Experimental::Detector & detector, const Options & options = Options{})
Convert to detray json format.
Parameters
gctx the geometry context
detector the detector instance
options the writing options that propagate to the downstream converters
Returns
a json object in detray format
fix this to actual volume grid
Definition at line 85 of file DetectorJsonConverter.cpp.
View newest version in sPHENIX GitHub at line 85 of file DetectorJsonConverter.cpp
References Acts::Experimental::Detector::name(), Acts::Test::time, Acts::DetectorJsonConverter::Options::volumeOptions, volumes, and Acts::Experimental::Detector::volumes().
Referenced by Acts::Python::addJson(), BOOST_AUTO_TEST_CASE(), Acts::DetectorVolumeJsonConverter::toJsonDetray(), Acts::PortalJsonConverter::toJsonDetray(), and Acts::SurfaceJsonConverter::toJsonDetray().