Analysis Software: acts/blob/sPHENIX/Tests/UnitTests/Core/EventData/TrackTests.cpp File Reference
TrackTests.cpp File Reference
#include <boost/test/data/test_case.hpp>
#include <boost/test/unit_test.hpp>
#include "Acts/Definitions/Algebra.hpp"
#include "Acts/Definitions/TrackParametrization.hpp"
#include "Acts/Definitions/Units.hpp"
#include "Acts/EventData/MultiTrajectory.hpp"
#include "Acts/EventData/TrackContainer.hpp"
#include "Acts/EventData/TrackHelpers.hpp"
#include "Acts/EventData/TrackProxy.hpp"
#include "Acts/EventData/TrackStatePropMask.hpp"
#include "Acts/EventData/VectorMultiTrajectory.hpp"
#include "Acts/EventData/VectorTrackContainer.hpp"
#include "Acts/Geometry/GeometryContext.hpp"
#include "Acts/Surfaces/PlaneSurface.hpp"
#include "Acts/Surfaces/Surface.hpp"
#include "Acts/Tests/CommonHelpers/GenerateParameters.hpp"
#include "Acts/Tests/CommonHelpers/TestTrackState.hpp"
#include "Acts/Utilities/HashedString.hpp"
#include "Acts/Utilities/Holders.hpp"
#include "Acts/Utilities/Zip.hpp"
#include <cstddef>
#include <iterator>
#include <memory>
#include <numeric>
#include <random>
#include <stdexcept>
#include <tuple>
#include <type_traits>
#include <utility>
#include <vector>
Functions
BOOST_AUTO_TEST_CASE (BuildDefaultHolder)
BOOST_AUTO_TEST_CASE (BuildValueHolder)
BOOST_AUTO_TEST_CASE (BuildRefHolder)
BOOST_AUTO_TEST_CASE (BuildSharedPtr)
BOOST_AUTO_TEST_CASE_TEMPLATE (Build, factory_t, holder_types)
BOOST_AUTO_TEST_CASE_TEMPLATE (TrackStateAccess, factory_t, holder_types)
BOOST_AUTO_TEST_CASE_TEMPLATE (TrackIterator, factory_t, holder_types)
BOOST_AUTO_TEST_CASE (IteratorConcept)
BOOST_AUTO_TEST_CASE (ConstCorrectness)
BOOST_AUTO_TEST_CASE (BuildFromConstRef)
BOOST_AUTO_TEST_CASE_TEMPLATE (BuildReadOnly, factory_t, const_holder_types)
BOOST_AUTO_TEST_CASE_TEMPLATE (DynamicColumns, factory_t, holder_types)
BOOST_AUTO_TEST_CASE (EnsureDynamicColumns)
BOOST_AUTO_TEST_CASE (AppendTrackState)
BOOST_AUTO_TEST_CASE (ForwardIteration)
BOOST_AUTO_TEST_CASE (CalculateQuantities)
Function Documentation
BOOST_AUTO_TEST_CASE (BuildDefaultHolder)
Definition at line 122 of file TrackTests.cpp.
View newest version in sPHENIX GitHub at line 122 of file TrackTests.cpp
References mtj, and tc.
BOOST_AUTO_TEST_CASE (BuildValueHolder)
Definition at line 141 of file TrackTests.cpp.
View newest version in sPHENIX GitHub at line 141 of file TrackTests.cpp
References testing::internal::move(), mtj, and tc.
BOOST_AUTO_TEST_CASE (BuildRefHolder)
Definition at line 170 of file TrackTests.cpp.
View newest version in sPHENIX GitHub at line 170 of file TrackTests.cpp
References mtj, and tc.
BOOST_AUTO_TEST_CASE (BuildSharedPtr)
Definition at line 189 of file TrackTests.cpp.
View newest version in sPHENIX GitHub at line 189 of file TrackTests.cpp
References mtj, and tc.
BOOST_AUTO_TEST_CASE (IteratorConcept)
Definition at line 365 of file TrackTests.cpp.
View newest version in sPHENIX GitHub at line 365 of file TrackTests.cpp
References distance(), i, it, mtj, t, and tc.
BOOST_AUTO_TEST_CASE (ConstCorrectness)
Definition at line 426 of file TrackTests.cpp.
View newest version in sPHENIX GitHub at line 426 of file TrackTests.cpp
References cmtj, cvtc, i, testing::internal::move(), mtj, t, and tc.
BOOST_AUTO_TEST_CASE (BuildFromConstRef)
Definition at line 466 of file TrackTests.cpp.
View newest version in sPHENIX GitHub at line 466 of file TrackTests.cpp
References cmtj, ctc, cvtc, testing::internal::move(), mtj, Acts::MultiTrajectory< derived_t >::size(), and t.
BOOST_AUTO_TEST_CASE (EnsureDynamicColumns)
Definition at line 540 of file TrackTests.cpp.
View newest version in sPHENIX GitHub at line 540 of file TrackTests.cpp
References tc.
BOOST_AUTO_TEST_CASE (AppendTrackState)
Definition at line 559 of file TrackTests.cpp.
View newest version in sPHENIX GitHub at line 559 of file TrackTests.cpp
References i, t, and tc.
BOOST_AUTO_TEST_CASE (ForwardIteration)
Definition at line 578 of file TrackTests.cpp.
View newest version in sPHENIX GitHub at line 578 of file TrackTests.cpp
References i, t, and tc.
BOOST_AUTO_TEST_CASE (CalculateQuantities)
Definition at line 634 of file TrackTests.cpp.
View newest version in sPHENIX GitHub at line 634 of file TrackTests.cpp
References Acts::calculateTrackQuantities(), Acts::HoleFlag, Acts::MeasurementFlag, Acts::OutlierFlag, Acts::SharedHitFlag, t, and tc.
BOOST_AUTO_TEST_CASE_TEMPLATE (Build , factory_t , holder_types)
Definition at line 208 of file TrackTests.cpp.
View newest version in sPHENIX GitHub at line 208 of file TrackTests.cpp
References caccNMeasuements, Acts::Test::cov, ambiguity_solver_full_chain::idx, pars, Acts::TrackContainer< track_container_t, traj_t, holder_t >::ReadOnly, writeMapConfig::surface, t, ambiguity_solver_full_chain::t2, and tc.
BOOST_AUTO_TEST_CASE_TEMPLATE (TrackStateAccess , factory_t , holder_types)
Definition at line 282 of file TrackTests.cpp.
View newest version in sPHENIX GitHub at line 282 of file TrackTests.cpp
References Acts::MultiTrajectory< derived_t >::addTrackState(), Acts::MultiTrajectory< derived_t >::getTrackState(), i, Acts::MultiTrajectoryTraits::kInvalid, conftest::rng(), filter::state, t, tc, and physmon_ckf_tracking::u.
BOOST_AUTO_TEST_CASE_TEMPLATE (TrackIterator , factory_t , holder_types)
Definition at line 345 of file TrackTests.cpp.
View newest version in sPHENIX GitHub at line 345 of file TrackTests.cpp
References distance(), i, t, and tc.
BOOST_AUTO_TEST_CASE_TEMPLATE (BuildReadOnly , factory_t , const_holder_types)
Definition at line 515 of file TrackTests.cpp.
View newest version in sPHENIX GitHub at line 515 of file TrackTests.cpp
References Acts::TrackContainer< track_container_t, traj_t, holder_t >::ReadOnly, and tc.
BOOST_AUTO_TEST_CASE_TEMPLATE (DynamicColumns , factory_t , holder_types)
Definition at line 527 of file TrackTests.cpp.
View newest version in sPHENIX GitHub at line 527 of file TrackTests.cpp
References f, t, and tc.