Analysis Software: ActsExamples::WriteDataHandle< T > Exception Template Reference
ActsExamples::WriteDataHandle< T > Exception Template Reference final
#include <acts/blob/sPHENIX/Examples/Framework/include/ActsExamples/Framework/DataHandle.hpp>
Public Member Functions
WriteDataHandle (SequenceElement *parent, const std::string &name)
void operator() (const AlgorithmContext &ctx, T &&value) const
void operator() (WhiteBoard &wb, T &&value) const
void initialize (const std::string &key)
bool isCompatible (const DataHandleBase &other) const override
const std::type_info & typeInfo () const override
Public Member Functions inherited from ActsExamples::DataHandleBase
const std::string & key () const
bool isInitialized () const
const std::string & name () const
void maybeInitialize (const std::string &key)
std::string fullName () const
Additional Inherited Members
Protected Member Functions inherited from ActsExamples::DataHandleBase
virtual ~DataHandleBase ()=default
DataHandleBase (SequenceElement *parent, const std::string &name)
DataHandleBase (const DataHandleBase &)=delete
DataHandleBase (DataHandleBase &&)=default
Protected Attributes inherited from ActsExamples::DataHandleBase
SequenceElement * m_parent {nullptr}
std::string m_name
std::optional< std::string > m_key {}
Detailed Description
template<typename T>
exception ActsExamples::WriteDataHandle< T >
Definition at line 61 of file DataHandle.hpp.
View newest version in sPHENIX GitHub at line 61 of file DataHandle.hpp
Constructor & Destructor Documentation
template<typename T> ActsExamples::WriteDataHandle< T >::WriteDataHandle (SequenceElement * parent, const std::string & name) inline
Definition at line 63 of file DataHandle.hpp.
View newest version in sPHENIX GitHub at line 63 of file DataHandle.hpp
Member Function Documentation
template<typename T> void ActsExamples::WriteDataHandle< T >::initialize (const std::string & key) inline
Definition at line 80 of file DataHandle.hpp.
View newest version in sPHENIX GitHub at line 80 of file DataHandle.hpp
Referenced by ActsExamples::AdaptiveMultiVertexFinderAlgorithm::AdaptiveMultiVertexFinderAlgorithm(), Acts::Test::addToWhiteBoard(), ActsExamples::AlignmentAlgorithm::AlignmentAlgorithm(), ActsExamples::AmbiguityResolutionMLAlgorithm::AmbiguityResolutionMLAlgorithm(), ActsExamples::AmbiguityResolutionMLDBScanAlgorithm::AmbiguityResolutionMLDBScanAlgorithm(), ActsExamples::CsvMeasurementReader::CsvMeasurementReader(), ActsExamples::CsvParticleReader::CsvParticleReader(), ActsExamples::CsvPlanarClusterReader::CsvPlanarClusterReader(), ActsExamples::CsvSimHitReader::CsvSimHitReader(), ActsExamples::CsvSpacePointReader::CsvSpacePointReader(), ActsExamples::CsvTrackParameterReader::CsvTrackParameterReader(), ActsExamples::DigitizationAlgorithm::DigitizationAlgorithm(), ActsExamples::EDM4hepMeasurementReader::EDM4hepMeasurementReader(), ActsExamples::EDM4hepParticleReader::EDM4hepParticleReader(), ActsExamples::EDM4hepSimHitReader::EDM4hepSimHitReader(), ActsExamples::EDM4hepTrackReader::EDM4hepTrackReader(), ActsExamples::EventGenerator::EventGenerator(), ActsExamples::EventRecording::EventRecording(), ActsExamples::FatrasSimulation::FatrasSimulation(), ActsExamples::Geant4MaterialRecording::Geant4MaterialRecording(), ActsExamples::Geant4Simulation::Geant4Simulation(), ActsExamples::GreedyAmbiguityResolutionAlgorithm::GreedyAmbiguityResolutionAlgorithm(), ActsExamples::HelloRandomAlgorithm::HelloRandomAlgorithm(), ActsExamples::HelloWhiteBoardAlgorithm::HelloWhiteBoardAlgorithm(), ActsExamples::HepMC3AsciiReader::HepMC3AsciiReader(), ActsExamples::HepMCProcessExtractor::HepMCProcessExtractor(), ActsExamples::HoughTransformSeeder::HoughTransformSeeder(), ActsExamples::IterativeVertexFinderAlgorithm::IterativeVertexFinderAlgorithm(), ActsExamples::MaterialMapping::MaterialMapping(), ActsExamples::MeasurementMapSelector::MeasurementMapSelector(), ActsExamples::ParticleSelector::ParticleSelector(), ActsExamples::ParticleSmearing::ParticleSmearing(), ActsExamples::PlanarSteppingAlgorithm::PlanarSteppingAlgorithm(), ActsExamples::PropagationAlgorithm::PropagationAlgorithm(), ActsExamples::PrototracksToParameters::PrototracksToParameters(), ActsExamples::PrototracksToSeeds::PrototracksToSeeds(), ActsExamples::RefittingAlgorithm::RefittingAlgorithm(), ActsExamples::RootAthenaNTupleReader::RootAthenaNTupleReader(), ActsExamples::RootParticleReader::RootParticleReader(), ActsExamples::RootSimHitReader::RootSimHitReader(), ActsExamples::SeedingAlgorithm::SeedingAlgorithm(), ActsExamples::SeedingFTFAlgorithm::SeedingFTFAlgorithm(), ActsExamples::SeedingOrthogonalAlgorithm::SeedingOrthogonalAlgorithm(), ActsExamples::SeedsToPrototracks::SeedsToPrototracks(), ActsExamples::SingleSeedVertexFinderAlgorithm::SingleSeedVertexFinderAlgorithm(), ActsExamples::SpacePointMaker::SpacePointMaker(), ActsExamples::SurfaceSortingAlgorithm::SurfaceSortingAlgorithm(), ActsExamples::TrackFindingAlgorithmExaTrkX::TrackFindingAlgorithmExaTrkX(), ActsExamples::TrackFindingFromPrototrackAlgorithm::TrackFindingFromPrototrackAlgorithm(), ActsExamples::TrackFittingAlgorithm::TrackFittingAlgorithm(), ActsExamples::TrackParameterSelector::TrackParameterSelector(), ActsExamples::TrackParamsEstimationAlgorithm::TrackParamsEstimationAlgorithm(), ActsExamples::TrackSelectorAlgorithm::TrackSelectorAlgorithm(), ActsExamples::TracksToTrajectories::TracksToTrajectories(), ActsExamples::TrajectoriesToPrototracks::TrajectoriesToPrototracks(), ActsExamples::TruthSeedingAlgorithm::TruthSeedingAlgorithm(), ActsExamples::TruthSeedSelector::TruthSeedSelector(), ActsExamples::TruthTrackFinder::TruthTrackFinder(), ActsExamples::TruthVertexFinder::TruthVertexFinder(), ActsExamples::TutorialVertexFinderAlgorithm::TutorialVertexFinderAlgorithm(), and ActsExamples::VertexFitterAlgorithm::VertexFitterAlgorithm().
template<typename T> bool ActsExamples::WriteDataHandle< T >::isCompatible (const DataHandleBase & other) const inline override virtual
Implements ActsExamples::DataHandleBase.
Definition at line 88 of file DataHandle.hpp.
View newest version in sPHENIX GitHub at line 88 of file DataHandle.hpp
template<typename T> void ActsExamples::WriteDataHandle< T >::operator() (const AlgorithmContext & ctx, T && value) const inline
Definition at line 68 of file DataHandle.hpp.
View newest version in sPHENIX GitHub at line 68 of file DataHandle.hpp
template<typename T> void ActsExamples::WriteDataHandle< T >::operator() (WhiteBoard & wb, T && value) const inline
Definition at line 72 of file DataHandle.hpp.
View newest version in sPHENIX GitHub at line 72 of file DataHandle.hpp
template<typename T> const std::type_info& ActsExamples::WriteDataHandle< T >::typeInfo () const inline override virtual
Implements ActsExamples::DataHandleBase.
Definition at line 92 of file DataHandle.hpp.
View newest version in sPHENIX GitHub at line 92 of file DataHandle.hpp
The documentation for this exception was generated from the following file:
acts/blob/sPHENIX/Examples/Framework/include/ActsExamples/Framework/DataHandle.hpp