Analysis Software: SvtxTrackState_v1 Class Reference
SvtxTrackState_v1 Class Reference
#include <coresoftware/blob/master/offline/packages/trackbase_historic/SvtxTrackState_v1.h>
Public Member Functions
SvtxTrackState_v1 (float pathlength=0.0)
~SvtxTrackState_v1 () override
void identify (std::ostream &os=std::cout) const override
void Reset () override
Clear Event.
int isValid () const override
isValid returns non zero if object contains vailid data
PHObject * CloneMe () const override
Virtual copy constructor.
float get_pathlength () const override
float get_x () const override
void set_x (float x) override
float get_y () const override
void set_y (float y) override
float get_z () const override
void set_z (float z) override
float get_pos (unsigned int i) const override
float get_px () const override
void set_px (float px) override
float get_py () const override
void set_py (float py) override
float get_pz () const override
void set_pz (float pz) override
float get_mom (unsigned int i) const override
float get_p () const override
float get_pt () const override
float get_eta () const override
float get_phi () const override
float get_error (unsigned int i, unsigned int j) const override
void set_error (unsigned int i, unsigned int j, float value) override
std::string get_name () const override
void set_name (const std::string &name) override
float get_rphi_error () const override
rphi error
float get_phi_error () const override
phi error
float get_z_error () const override
z error
Public Member Functions inherited from SvtxTrackState
~SvtxTrackState () override
virtual TrkrDefs::cluskey get_cluskey () const
virtual void set_cluskey (TrkrDefs::cluskey)
Public Member Functions inherited from PHObject
PHObject ()
ctor
~PHObject () override
dtor
virtual PHObject * clone () const final
PHObject * Clone (const char *newname="") const final
void Copy (TObject &object) const final
virtual int Integrate () const
virtual int Integrate (PHObject *)
virtual void CopyFrom (const PHObject *obj)
Private Attributes
float _pathlength
float _pos [3]
float _mom [3]
float _covar [21]
std::string state_name
Additional Inherited Members
Protected Member Functions inherited from SvtxTrackState
SvtxTrackState (float=0.0)
ClassDefOverride (SvtxTrackState, 1)
Detailed Description
Definition at line 12 of file SvtxTrackState_v1.h.
View newest version in sPHENIX GitHub at line 12 of file SvtxTrackState_v1.h
Constructor & Destructor Documentation
SvtxTrackState_v1::SvtxTrackState_v1 (float pathlength = 0.0)
Definition at line 24 of file SvtxTrackState_v1.cc.
View newest version in sPHENIX GitHub at line 24 of file SvtxTrackState_v1.cc
References _mom, _pos, i, j, set_error(), and state_name.
Referenced by CloneMe(), and Reset().
SvtxTrackState_v1::~SvtxTrackState_v1 () inline override
Definition at line 16 of file SvtxTrackState_v1.h.
View newest version in sPHENIX GitHub at line 16 of file SvtxTrackState_v1.h
Member Function Documentation
PHObject* SvtxTrackState_v1::CloneMe () const inline override virtual
Virtual copy constructor.
Reimplemented from SvtxTrackState.
Definition at line 22 of file SvtxTrackState_v1.h.
View newest version in sPHENIX GitHub at line 22 of file SvtxTrackState_v1.h
References SvtxTrackState_v1().
float SvtxTrackState_v1::get_error (unsigned int i, unsigned int j) const override virtual
Reimplemented from SvtxTrackState.
Definition at line 52 of file SvtxTrackState_v1.cc.
View newest version in sPHENIX GitHub at line 52 of file SvtxTrackState_v1.cc
References _covar.
Referenced by get_rphi_error(), and get_z_error().
float SvtxTrackState_v1::get_eta () const inline override virtual
Reimplemented from SvtxTrackState.
Definition at line 50 of file SvtxTrackState_v1.h.
View newest version in sPHENIX GitHub at line 50 of file SvtxTrackState_v1.h
References get_pt(), and get_pz().
float SvtxTrackState_v1::get_mom (unsigned int i) const inline override virtual
Reimplemented from SvtxTrackState.
Definition at line 46 of file SvtxTrackState_v1.h.
View newest version in sPHENIX GitHub at line 46 of file SvtxTrackState_v1.h
References _mom, and i.
std::string SvtxTrackState_v1::get_name (void) const inline override virtual
Reimplemented from SvtxTrackState.
Definition at line 57 of file SvtxTrackState_v1.h.
View newest version in sPHENIX GitHub at line 57 of file SvtxTrackState_v1.h
References state_name.
float SvtxTrackState_v1::get_p () const inline override virtual
Reimplemented from SvtxTrackState.
Definition at line 48 of file SvtxTrackState_v1.h.
View newest version in sPHENIX GitHub at line 48 of file SvtxTrackState_v1.h
References get_px(), get_py(), and get_pz().
float SvtxTrackState_v1::get_pathlength () const inline override virtual
Reimplemented from SvtxTrackState.
Definition at line 24 of file SvtxTrackState_v1.h.
View newest version in sPHENIX GitHub at line 24 of file SvtxTrackState_v1.h
References _pathlength.
Referenced by identify().
float SvtxTrackState_v1::get_phi () const inline override virtual
Reimplemented from SvtxTrackState.
Definition at line 51 of file SvtxTrackState_v1.h.
View newest version in sPHENIX GitHub at line 51 of file SvtxTrackState_v1.h
References get_px(), and get_py().
float SvtxTrackState_v1::get_phi_error () const override virtual
phi error
Reimplemented from SvtxTrackState.
Definition at line 63 of file SvtxTrackState_v1.cc.
View newest version in sPHENIX GitHub at line 63 of file SvtxTrackState_v1.cc
References _pos, get_rphi_error(), physmon_track_finding_ttbar::r, and square().
float SvtxTrackState_v1::get_pos (unsigned int i) const inline override virtual
Reimplemented from SvtxTrackState.
Definition at line 35 of file SvtxTrackState_v1.h.
View newest version in sPHENIX GitHub at line 35 of file SvtxTrackState_v1.h
References _pos, and i.
float SvtxTrackState_v1::get_pt () const inline override virtual
Reimplemented from SvtxTrackState.
Definition at line 49 of file SvtxTrackState_v1.h.
View newest version in sPHENIX GitHub at line 49 of file SvtxTrackState_v1.h
References get_px(), and get_py().
Referenced by get_eta().
float SvtxTrackState_v1::get_px () const inline override virtual
Reimplemented from SvtxTrackState.
Definition at line 37 of file SvtxTrackState_v1.h.
View newest version in sPHENIX GitHub at line 37 of file SvtxTrackState_v1.h
References _mom.
Referenced by get_p(), get_phi(), get_pt(), identify(), and TpcDirectLaserReconstruction::process_track().
float SvtxTrackState_v1::get_py () const inline override virtual
Reimplemented from SvtxTrackState.
Definition at line 40 of file SvtxTrackState_v1.h.
View newest version in sPHENIX GitHub at line 40 of file SvtxTrackState_v1.h
References _mom.
Referenced by get_p(), get_phi(), get_pt(), identify(), and TpcDirectLaserReconstruction::process_track().
float SvtxTrackState_v1::get_pz () const inline override virtual
Reimplemented from SvtxTrackState.
Definition at line 43 of file SvtxTrackState_v1.h.
View newest version in sPHENIX GitHub at line 43 of file SvtxTrackState_v1.h
References _mom.
Referenced by get_eta(), get_p(), identify(), and TpcDirectLaserReconstruction::process_track().
float SvtxTrackState_v1::get_rphi_error () const override virtual
rphi error
Reimplemented from SvtxTrackState.
Definition at line 70 of file SvtxTrackState_v1.cc.
View newest version in sPHENIX GitHub at line 70 of file SvtxTrackState_v1.cc
References _pos, get_error(), ActsTests::PropagationDatasets::phi, and square().
Referenced by get_phi_error().
float SvtxTrackState_v1::get_x () const inline override virtual
Reimplemented from SvtxTrackState.
Definition at line 26 of file SvtxTrackState_v1.h.
View newest version in sPHENIX GitHub at line 26 of file SvtxTrackState_v1.h
References _pos.
Referenced by identify().
float SvtxTrackState_v1::get_y () const inline override virtual
Reimplemented from SvtxTrackState.
Definition at line 29 of file SvtxTrackState_v1.h.
View newest version in sPHENIX GitHub at line 29 of file SvtxTrackState_v1.h
References _pos.
Referenced by identify().
float SvtxTrackState_v1::get_z () const inline override virtual
Reimplemented from SvtxTrackState.
Definition at line 32 of file SvtxTrackState_v1.h.
View newest version in sPHENIX GitHub at line 32 of file SvtxTrackState_v1.h
References _pos.
Referenced by identify().
float SvtxTrackState_v1::get_z_error () const override virtual
z error
Reimplemented from SvtxTrackState.
Definition at line 81 of file SvtxTrackState_v1.cc.
View newest version in sPHENIX GitHub at line 81 of file SvtxTrackState_v1.cc
References get_error().
void SvtxTrackState_v1::identify (std::ostream & os = std::cout) const override virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from SvtxTrackState.
Definition at line 39 of file SvtxTrackState_v1.cc.
View newest version in sPHENIX GitHub at line 39 of file SvtxTrackState_v1.cc
References get_pathlength(), get_px(), get_py(), get_pz(), get_x(), get_y(), and get_z().
int SvtxTrackState_v1::isValid () const inline override virtual
isValid returns non zero if object contains vailid data
Reimplemented from SvtxTrackState.
Definition at line 21 of file SvtxTrackState_v1.h.
View newest version in sPHENIX GitHub at line 21 of file SvtxTrackState_v1.h
void SvtxTrackState_v1::Reset () inline override virtual
Clear Event.
Reimplemented from PHObject.
Definition at line 20 of file SvtxTrackState_v1.h.
View newest version in sPHENIX GitHub at line 20 of file SvtxTrackState_v1.h
References SvtxTrackState_v1().
void SvtxTrackState_v1::set_error (unsigned int i, unsigned int j, float value) override virtual
Reimplemented from SvtxTrackState.
Definition at line 57 of file SvtxTrackState_v1.cc.
View newest version in sPHENIX GitHub at line 57 of file SvtxTrackState_v1.cc
References _covar, and value.
Referenced by PHActsTrackPropagator::addTrackState(), PHTpcResiduals::addTrackState(), TrackProjectorPid::project_track(), TrackProjectorPlaneECAL::project_track(), SvtxTrackState_v1(), and PHActsTrackProjection::updateSvtxTrack().
void SvtxTrackState_v1::set_name (const std::string & name) inline override virtual
Reimplemented from SvtxTrackState.
Definition at line 58 of file SvtxTrackState_v1.h.
View newest version in sPHENIX GitHub at line 58 of file SvtxTrackState_v1.h
References perf_headwind::name, and state_name.
Referenced by PHTpcResiduals::addTrackState().
void SvtxTrackState_v1::set_px (float px) inline override virtual
Reimplemented from SvtxTrackState.
Definition at line 38 of file SvtxTrackState_v1.h.
View newest version in sPHENIX GitHub at line 38 of file SvtxTrackState_v1.h
References _mom.
Referenced by PHActsTrackPropagator::addTrackState(), PHTpcResiduals::addTrackState(), TpcDirectLaserReconstruction::process_track(), TrackProjectorPid::project_track(), TrackProjectorPlaneECAL::project_track(), and PHActsTrackProjection::updateSvtxTrack().
void SvtxTrackState_v1::set_py (float py) inline override virtual
Reimplemented from SvtxTrackState.
Definition at line 41 of file SvtxTrackState_v1.h.
View newest version in sPHENIX GitHub at line 41 of file SvtxTrackState_v1.h
References _mom.
Referenced by PHActsTrackPropagator::addTrackState(), PHTpcResiduals::addTrackState(), TpcDirectLaserReconstruction::process_track(), TrackProjectorPid::project_track(), TrackProjectorPlaneECAL::project_track(), and PHActsTrackProjection::updateSvtxTrack().
void SvtxTrackState_v1::set_pz (float pz) inline override virtual
Reimplemented from SvtxTrackState.
Definition at line 44 of file SvtxTrackState_v1.h.
View newest version in sPHENIX GitHub at line 44 of file SvtxTrackState_v1.h
References _mom.
Referenced by PHActsTrackPropagator::addTrackState(), PHTpcResiduals::addTrackState(), TpcDirectLaserReconstruction::process_track(), TrackProjectorPid::project_track(), TrackProjectorPlaneECAL::project_track(), and PHActsTrackProjection::updateSvtxTrack().
void SvtxTrackState_v1::set_x (float x) inline override virtual
Reimplemented from SvtxTrackState.
Definition at line 27 of file SvtxTrackState_v1.h.
View newest version in sPHENIX GitHub at line 27 of file SvtxTrackState_v1.h
References _pos, and ambiguity_solver_full_chain::x.
Referenced by PHActsTrackPropagator::addTrackState(), PHTpcResiduals::addTrackState(), PHActsToSvtxTracks::createSvtxTrack(), HelicalFitter::process_event(), TpcDirectLaserReconstruction::process_track(), TrackProjectorPid::project_track(), TrackProjectorPlaneECAL::project_track(), PHActsGSF::updateSvtxTrack(), PHActsTrackProjection::updateSvtxTrack(), PHCosmicsTrkFitter::updateSvtxTrack(), and PHActsTrkFitter::updateSvtxTrack().
void SvtxTrackState_v1::set_y (float y) inline override virtual
Reimplemented from SvtxTrackState.
Definition at line 30 of file SvtxTrackState_v1.h.
View newest version in sPHENIX GitHub at line 30 of file SvtxTrackState_v1.h
References _pos, and y.
Referenced by PHActsTrackPropagator::addTrackState(), PHTpcResiduals::addTrackState(), PHActsToSvtxTracks::createSvtxTrack(), TpcDirectLaserReconstruction::process_track(), TrackProjectorPid::project_track(), TrackProjectorPlaneECAL::project_track(), PHActsGSF::updateSvtxTrack(), PHActsTrackProjection::updateSvtxTrack(), PHCosmicsTrkFitter::updateSvtxTrack(), and PHActsTrkFitter::updateSvtxTrack().
void SvtxTrackState_v1::set_z (float z) inline override virtual
Reimplemented from SvtxTrackState.
Definition at line 33 of file SvtxTrackState_v1.h.
View newest version in sPHENIX GitHub at line 33 of file SvtxTrackState_v1.h
References _pos, and physmon_track_finding_ttbar::z.
Referenced by PHActsTrackPropagator::addTrackState(), PHTpcResiduals::addTrackState(), PHActsToSvtxTracks::createSvtxTrack(), TpcDirectLaserReconstruction::process_track(), TrackProjectorPid::project_track(), TrackProjectorPlaneECAL::project_track(), PHActsGSF::updateSvtxTrack(), PHActsTrackProjection::updateSvtxTrack(), PHCosmicsTrkFitter::updateSvtxTrack(), and PHActsTrkFitter::updateSvtxTrack().
Member Data Documentation
float SvtxTrackState_v1::_covar[21] private
Definition at line 70 of file SvtxTrackState_v1.h.
View newest version in sPHENIX GitHub at line 70 of file SvtxTrackState_v1.h
Referenced by get_error(), and set_error().
float SvtxTrackState_v1::_mom[3] private
Definition at line 69 of file SvtxTrackState_v1.h.
View newest version in sPHENIX GitHub at line 69 of file SvtxTrackState_v1.h
Referenced by get_mom(), get_px(), get_py(), get_pz(), set_px(), set_py(), set_pz(), and SvtxTrackState_v1().
float SvtxTrackState_v1::_pathlength private
Definition at line 67 of file SvtxTrackState_v1.h.
View newest version in sPHENIX GitHub at line 67 of file SvtxTrackState_v1.h
Referenced by get_pathlength().
float SvtxTrackState_v1::_pos[3] private
Definition at line 68 of file SvtxTrackState_v1.h.
View newest version in sPHENIX GitHub at line 68 of file SvtxTrackState_v1.h
Referenced by get_phi_error(), get_pos(), get_rphi_error(), get_x(), get_y(), get_z(), set_x(), set_y(), set_z(), and SvtxTrackState_v1().
std::string SvtxTrackState_v1::state_name private
Definition at line 72 of file SvtxTrackState_v1.h.
View newest version in sPHENIX GitHub at line 72 of file SvtxTrackState_v1.h
Referenced by get_name(), set_name(), and SvtxTrackState_v1().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/trackbase_historic/SvtxTrackState_v1.h
coresoftware/blob/master/offline/packages/trackbase_historic/SvtxTrackState_v1.cc