Analysis Software: TSQLDatabaseMetaData Class Reference
TSQLDatabaseMetaData Class Reference abstract
#include <RDBC/blob/master/include/RDBC/TSQLDatabaseMetaData.h>
Public Types
enum EMetaDataConstants {
kBestRowTemporary = 0, kBestRowTransaction = 1, kBestRowSession = 2, kBestRowUnknown = 0,
kBestRowPseudo = 2, kBestRowNotPseudo = 1, kVersionColumnNotPseudo = 1, kVersionColumnPseudo = 2,
kVersionColumnUnknown = 0, kTypeNoNulls = 0, kTypeNullable = 1, kTypeNullableUnknown = 2,
kColumnNoNulls = 0, kColumnNullable = 1, kColumnNullableUnknown = 2, kTypePredNone = 0,
kTypePredChar = 1, kTypePredBasic = 2, kTypeSearchable = 3, kImportedKeyCascade = 0x00000020L,
kImportedKeySetNull = 2, kImportedKeySetDefault = 4, kImportedKeyNoAction = 3, kImportedKeyRestrict = 1,
kImportedKeyInitiallyDeferred = 5, kImportedKeyInitiallyImmediate = 6, kImportedKeyNotDeferrable = 7, kTableIndexClustered = 1,
kTableIndexHashed = 2, kTableIndexOther = 3, kTableIndexStatistic = 0, kProcedureColumnIn = 1,
kProcedureColumnInOut = 2, kProcedureColumnOut = 4, kProcedureColumnResult = 3, kProcedureColumnReturn = 5,
kProcedureColumnUnknown = 0, kProcedureNoNulls = 0, kProcedureNullable = 1, kProcedureNullableUnknown = 2,
kProcedureReturnsResult = 2, kProcedureNoResult = 1, kProcedureResultUnknown = 0
}
Public Member Functions
virtual Bool_t AllProceduresAreCallable ()=0
virtual Bool_t AllTablesAreSelectable ()=0
virtual TString GetUserName ()=0
virtual Bool_t IsReadOnly ()=0
virtual Bool_t NullsAreSortedHigh ()=0
virtual Bool_t NullsAreSortedLow ()=0
virtual Bool_t NullsAreSortedAtStart ()=0
virtual Bool_t NullsAreSortedAtEnd ()=0
virtual TString GetDatabaseProductName ()=0
virtual TString GetDatabaseProductVersion ()=0
virtual TString GetDriverName ()=0
virtual TString GetDriverVersion ()=0
virtual Int_t GetDriverMajorVersion ()=0
virtual Int_t GetDriverMinorVersion ()=0
virtual Bool_t UsesLocalFiles ()=0
virtual Bool_t UsesLocalFilePerTable ()=0
virtual Bool_t SupportsMixedCaseIdentifiers ()=0
virtual Bool_t StoresUpperCaseIdentifiers ()=0
virtual Bool_t StoresLowerCaseIdentifiers ()=0
virtual Bool_t StoresMixedCaseIdentifiers ()=0
virtual Bool_t SupportsMixedCaseQuotedIdentifiers ()=0
virtual Bool_t StoresUpperCaseQuotedIdentifiers ()=0
virtual Bool_t StoresLowerCaseQuotedIdentifiers ()=0
virtual Bool_t StoresMixedCaseQuotedIdentifiers ()=0
virtual TString GetIdentifierQuoteString ()=0
virtual TString GetSQLKeywords ()=0
virtual TString GetNumericFunctions ()=0
virtual TString GetStringFunctions ()=0
virtual TString GetSystemFunctions ()=0
virtual TString GetTimeDateFunctions ()=0
virtual TString GetSearchStringEscape ()=0
virtual TString GetExtraNameCharacters ()=0
virtual Bool_t SupportsAlterTableWithAddColumn ()=0
virtual Bool_t SupportsAlterTableWithDropColumn ()=0
virtual Bool_t SupportsColumnAliasing ()=0
virtual Bool_t NullPlusNonNullIsNull ()=0
virtual Bool_t SupportsConvert ()=0
virtual Bool_t SupportsConvert (Int_t fromType, Int_t toType)=0
virtual Bool_t SupportsTableCorrelationNames ()=0
virtual Bool_t SupportsDifferentTableCorrelationNames ()=0
virtual Bool_t SupportsExpressionsInOrderBy ()=0
virtual Bool_t SupportsOrderByUnrelated ()=0
virtual Bool_t SupportsGroupBy ()=0
virtual Bool_t SupportsGroupByUnrelated ()=0
virtual Bool_t SupportsGroupByBeyondSelect ()=0
virtual Bool_t SupportsLikeEscapeClause ()=0
virtual Bool_t SupportsMultipleResultSets ()=0
virtual Bool_t SupportsMultipleTransactions ()=0
virtual Bool_t SupportsNonNullableColumns ()=0
virtual Bool_t SupportsMinimumSQLGrammar ()=0
virtual Bool_t SupportsCoreSQLGrammar ()=0
virtual Bool_t SupportsExtendedSQLGrammar ()=0
virtual Bool_t SupportsANSI92EntryLevelSQL ()=0
virtual Bool_t SupportsANSI92IntermediateSQL ()=0
virtual Bool_t SupportsANSI92FullSQL ()=0
virtual Bool_t SupportsIntegrityEnhancementFacility ()=0
virtual Bool_t SupportsOuterJoins ()=0
virtual Bool_t SupportsFullOuterJoins ()=0
virtual Bool_t SupportsLimitedOuterJoins ()=0
virtual TString GetSchemaTerm ()=0
virtual TString GetTableTerm ()=0
virtual TString GetProcedureTerm ()=0
virtual TString GetCatalogTerm ()=0
virtual Bool_t IsCatalogAtStart ()=0
virtual TString GetCatalogSeparator ()=0
virtual Bool_t SupportsSchemasInDataManipulation ()=0
virtual Bool_t SupportsSchemasInProcedureCalls ()=0
virtual Bool_t SupportsSchemasInTableDefinitions ()=0
virtual Bool_t SupportsSchemasInIndexDefinitions ()=0
virtual Bool_t SupportsSchemasInPrivilegeDefinitions ()=0
virtual Bool_t SupportsCatalogsInDataManipulation ()=0
virtual Bool_t SupportsCatalogsInProcedureCalls ()=0
virtual Bool_t SupportsCatalogsInTableDefinitions ()=0
virtual Bool_t SupportsCatalogsInIndexDefinitions ()=0
virtual Bool_t SupportsCatalogsInPrivilegeDefinitions ()=0
virtual Bool_t SupportsPositionedDelete ()=0
virtual Bool_t SupportsPositionedUpdate ()=0
virtual Bool_t SupportsSelectForUpdate ()=0
virtual Bool_t SupportsStoredProcedures ()=0
virtual Bool_t SupportsSubqueriesInComparisons ()=0
virtual Bool_t SupportsSubqueriesInExists ()=0
virtual Bool_t SupportsSubqueriesInIns ()=0
virtual Bool_t SupportsSubqueriesInQuantifieds ()=0
virtual Bool_t SupportsCorrelatedSubqueries ()=0
virtual Bool_t SupportsUnion ()=0
virtual Bool_t SupportsUnionAll ()=0
virtual Bool_t SupportsOpenCursorsAcrossRollback ()=0
virtual Bool_t SupportsOpenStatementsAcrossCommit ()=0
virtual Bool_t SupportsOpenStatementsAcrossRollback ()=0
virtual Int_t GetMaxBinaryLiteralLength ()=0
virtual Int_t GetMaxCharLiteralLength ()=0
virtual Int_t GetMaxColumnNameLength ()=0
virtual Int_t GetMaxColumnsInGroupBy ()=0
virtual Int_t GetMaxColumnsInIndex ()=0
virtual Int_t GetMaxColumnsInOrderBy ()=0
virtual Int_t GetMaxColumnsInSelect ()=0
virtual Int_t GetMaxColumnsInTable ()=0
virtual Int_t GetMaxConnections ()=0
virtual Int_t GetMaxCursorNameLength ()=0
virtual Int_t GetMaxIndexLength ()=0
virtual Int_t GetMaxSchemaNameLength ()=0
virtual Int_t GetMaxProcedureNameLength ()=0
virtual Int_t GetMaxCatalogNameLength ()=0
virtual Int_t GetMaxRowSize ()=0
virtual Bool_t DoesMaxRowSizeIncludeBlobs ()=0
virtual Int_t GetMaxStatementLength ()=0
virtual Int_t GetMaxStatements ()=0
virtual Int_t GetMaxTableNameLength ()=0
virtual Int_t GetMaxTablesInSelect ()=0
virtual Int_t GetMaxUserNameLength ()=0
virtual Int_t GetDefaultTransactionIsolation ()=0
virtual Bool_t SupportsTransactions ()=0
virtual Bool_t SupportsTransactionIsolationLevel (Int_t level)=0
virtual Bool_t SupportsDataDefinitionAndDataManipulationTransactions ()=0
virtual Bool_t SupportsDataManipulationTransactionsOnly ()=0
virtual Bool_t DataDefinitionCausesTransactionCommit ()=0
virtual Bool_t DataDefinitionIgnoredInTransactions ()=0
virtual Bool_t SupportsResultSetType (Int_t type)=0
virtual Bool_t SupportsResultSetConcurrency (Int_t type, Int_t concurrency)=0
virtual Bool_t OwnUpdatesAreVisible (Int_t type)=0
virtual Bool_t OwnDeletesAreVisible (Int_t type)=0
virtual Bool_t OwnInsertsAreVisible (Int_t type)=0
virtual Bool_t OthersUpdatesAreVisible (Int_t type)=0
virtual Bool_t OthersDeletesAreVisible (Int_t type)=0
virtual Bool_t OthersInsertsAreVisible (Int_t type)=0
virtual Bool_t UpdatesAreDetected (Int_t type)=0
virtual Bool_t DeletesAreDetected (Int_t type)=0
virtual Bool_t InsertsAreDetected (Int_t type)=0
virtual Bool_t SupportsBatchUpdates ()=0
virtual TSQLResultSet * GetProcedures (const TString &catalog, const TString &schemaPattern, const TString &procedureNamePattern)=0
virtual TSQLResultSet * GetProcedureColumns (const TString &catalog, const TString &schemaPattern, const TString &procedureNamePattern, const TString &columnNamePattern)=0
virtual TSQLResultSet * GetTables (const TString &catalog, const TString &schemaPattern, const TString &tableNamePattern, const TString &types)=0
virtual TSQLResultSet * GetSchemas ()=0
virtual TSQLResultSet * GetCatalogs ()=0
virtual TSQLResultSet * GetTableTypes ()=0
virtual TSQLResultSet * GetColumns (const TString &catalog, const TString &schemaPattern, const TString &tableNamePattern, const TString &columnNamePattern)=0
virtual TSQLResultSet * GetColumnPrivileges (const TString &catalog, const TString &schema, const TString &table, const TString &columnNamePattern)=0
virtual TSQLResultSet * GetTablePrivileges (const TString &catalog, const TString &schemaPattern, const TString &tableNamePattern)=0
virtual TSQLResultSet * GetBestRowIdentifier (const TString &catalog, const TString &schema, const TString &table, Int_t scope, Bool_t nullable)=0
virtual TSQLResultSet * GetVersionColumns (const TString &catalog, const TString &schema, const TString &table)=0
virtual TSQLResultSet * GetPrimaryKeys (const TString &catalog, const TString &schema, const TString &table)=0
virtual TSQLResultSet * GetImportedKeys (const TString &catalog, const TString &schema, const TString &table)=0
virtual TSQLResultSet * GetExportedKeys (const TString &catalog, const TString &schema, const TString &table)=0
virtual TSQLResultSet * GetCrossReference (const TString &primaryCatalog, const TString &primarySchema, const TString &primaryTable, const TString &foreignCatalog, const TString &foreignSchema, const TString &foreignTable)=0
virtual TSQLResultSet * GetTypeInfo ()=0
virtual TSQLResultSet * GetIndexInfo (const TString &catalog, const TString &schema, const TString &table, Bool_t unique, Bool_t approximate)=0
TSQLConnection * GetConnection () const
virtual TString GetURL () const
Public Member Functions inherited from TSQL
TSQL (void *imp=0)
virtual ~TSQL ()
virtual void Throw (TSQLException *e)
TList * GetWarnings () const
void ClearWarnings ()
virtual Bool_t IsValid () const
Protected Member Functions
TSQLDatabaseMetaData (TSQLConnection *connection, void *imp=0)
virtual ~TSQLDatabaseMetaData ()
void SetURL (const TString &url)
void Set (TSQLConnection *connection, void *imp=0)
Protected Attributes
TSQLConnection * fConnection
TString fUrl
Protected Attributes inherited from TSQL
TList * fWarnings
void * fImp
Friends
class TSQLConnection
Additional Inherited Members
Static Public Member Functions inherited from TSQL
static Bool_t SetHandler (const TString &handler)
static Bool_t UnsetHandler (const TString &handler="")
Detailed Description
Definition at line 17 of file TSQLDatabaseMetaData.h.
View newest version in sPHENIX GitHub at line 17 of file TSQLDatabaseMetaData.h
Member Enumeration Documentation
enum TSQLDatabaseMetaData::EMetaDataConstants
Enumerator:
kBestRowTemporary
kBestRowTransaction
kBestRowSession
kBestRowUnknown
kBestRowPseudo
kBestRowNotPseudo
kVersionColumnNotPseudo
kVersionColumnPseudo
kVersionColumnUnknown
kTypeNoNulls
kTypeNullable
kTypeNullableUnknown
kColumnNoNulls
kColumnNullable
kColumnNullableUnknown
kTypePredNone
kTypePredChar
kTypePredBasic
kTypeSearchable
kImportedKeyCascade
kImportedKeySetNull
kImportedKeySetDefault
kImportedKeyNoAction
kImportedKeyRestrict
kImportedKeyInitiallyDeferred
kImportedKeyInitiallyImmediate
kImportedKeyNotDeferrable
kTableIndexClustered
kTableIndexHashed
kTableIndexOther
kTableIndexStatistic
kProcedureColumnIn
kProcedureColumnInOut
kProcedureColumnOut
kProcedureColumnResult
kProcedureColumnReturn
kProcedureColumnUnknown
kProcedureNoNulls
kProcedureNullable
kProcedureNullableUnknown
kProcedureReturnsResult
kProcedureNoResult
kProcedureResultUnknown
Definition at line 32 of file TSQLDatabaseMetaData.h.
View newest version in sPHENIX GitHub at line 32 of file TSQLDatabaseMetaData.h
Constructor & Destructor Documentation
TSQLDatabaseMetaData::TSQLDatabaseMetaData (TSQLConnection * connection, void * imp = 0) protected
Definition at line 438 of file MySQLDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 438 of file MySQLDatabaseMetaData.cxx
References fConnection.
TSQLDatabaseMetaData::~TSQLDatabaseMetaData () protected virtual
Definition at line 448 of file MySQLDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 448 of file MySQLDatabaseMetaData.cxx
References fConnection, and TSQL::fImp.
Member Function Documentation
Bool_t TSQLDatabaseMetaData::AllProceduresAreCallable () pure virtual
Implemented in ODBCDatabaseMetaData.
Definition at line 457 of file MySQLDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 457 of file MySQLDatabaseMetaData.cxx
Referenced by RDBCTestMetaData().
Bool_t TSQLDatabaseMetaData::AllTablesAreSelectable () pure virtual
Implemented in ODBCDatabaseMetaData.
Definition at line 471 of file MySQLDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 471 of file MySQLDatabaseMetaData.cxx
Referenced by RDBCTestMetaData().
Bool_t TSQLDatabaseMetaData::DataDefinitionCausesTransactionCommit () pure virtual
Implemented in ODBCDatabaseMetaData.
Definition at line 2531 of file MySQLDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 2531 of file MySQLDatabaseMetaData.cxx
Referenced by RDBCTestMetaData(), and transactionInfo().
Bool_t TSQLDatabaseMetaData::DataDefinitionIgnoredInTransactions () pure virtual
Implemented in ODBCDatabaseMetaData.
Definition at line 2545 of file MySQLDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 2545 of file MySQLDatabaseMetaData.cxx
Referenced by RDBCTestMetaData(), and transactionInfo().
Bool_t TSQLDatabaseMetaData::DeletesAreDetected (Int_t type) pure virtual
Implemented in ODBCDatabaseMetaData.
Definition at line 3915 of file MySQLDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 3915 of file MySQLDatabaseMetaData.cxx
Bool_t TSQLDatabaseMetaData::DoesMaxRowSizeIncludeBlobs () pure virtual
Implemented in ODBCDatabaseMetaData.
Definition at line 2347 of file MySQLDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 2347 of file MySQLDatabaseMetaData.cxx
Referenced by RDBCTestMetaData().
TSQLResultSet * TSQLDatabaseMetaData::GetBestRowIdentifier (const TString & catalog, const TString & schema, const TString & table, Int_t scope, Bool_t nullable) pure virtual
Implemented in ODBCDatabaseMetaData.
Definition at line 3119 of file MySQLDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 3119 of file MySQLDatabaseMetaData.cxx
References MySQLResultSetPrivate::Close(), con, fConnection, and TSQL::fImp.
TSQLResultSet * TSQLDatabaseMetaData::GetCatalogs () pure virtual
Implemented in ODBCDatabaseMetaData.
Definition at line 2849 of file MySQLDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 2849 of file MySQLDatabaseMetaData.cxx
References MySQLResultSetPrivate::Close(), con, fConnection, TSQL::fImp, MySQLConnectionPrivate::fMYSQL, MySQLResultSetPrivate::fMYSQL_RES, and TSQL::Throw().
TString TSQLDatabaseMetaData::GetCatalogSeparator () pure virtual
Implemented in ODBCDatabaseMetaData.
Definition at line 1659 of file MySQLDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 1659 of file MySQLDatabaseMetaData.cxx
Referenced by catalogInfo(), and RDBCTestMetaData().
TString TSQLDatabaseMetaData::GetCatalogTerm () pure virtual
Implemented in ODBCDatabaseMetaData.
Definition at line 1620 of file MySQLDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 1620 of file MySQLDatabaseMetaData.cxx
Referenced by catalogInfo(), and RDBCTestMetaData().
TSQLResultSet * TSQLDatabaseMetaData::GetColumnPrivileges (const TString & catalog, const TString & schema, const TString & table, const TString & columnNamePattern) pure virtual
Implemented in ODBCDatabaseMetaData.
Definition at line 3004 of file MySQLDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 3004 of file MySQLDatabaseMetaData.cxx
References MySQLResultSetPrivate::Close(), con, fConnection, TSQL::fImp, and TSQL::Throw().
TSQLResultSet * TSQLDatabaseMetaData::GetColumns (const TString & catalog, const TString & schemaPattern, const TString & tableNamePattern, const TString & columnNamePattern) pure virtual
Implemented in ODBCDatabaseMetaData.
Definition at line 2918 of file MySQLDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 2918 of file MySQLDatabaseMetaData.cxx
References MySQLResultSetPrivate::Close(), con, fConnection, and TSQL::fImp.
TSQLConnection* TSQLDatabaseMetaData::GetConnection () const inline
Definition at line 274 of file TSQLDatabaseMetaData.h.
View newest version in sPHENIX GitHub at line 274 of file TSQLDatabaseMetaData.h
References fConnection.
TSQLResultSet * TSQLDatabaseMetaData::GetCrossReference (const TString & primaryCatalog, const TString & primarySchema, const TString & primaryTable, const TString & foreignCatalog, const TString & foreignSchema, const TString & foreignTable) pure virtual
Implemented in ODBCDatabaseMetaData.
Definition at line 3461 of file MySQLDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 3461 of file MySQLDatabaseMetaData.cxx
References MySQLResultSetPrivate::Close(), con, fConnection, and TSQL::fImp.
Referenced by GetExportedKeys(), and GetImportedKeys().
TString TSQLDatabaseMetaData::GetDatabaseProductName () pure virtual
Implemented in ODBCDatabaseMetaData.
Definition at line 599 of file MySQLDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 599 of file MySQLDatabaseMetaData.cxx
Referenced by ClassImp(), productInfo(), and RDBCTestMetaData().
TString TSQLDatabaseMetaData::GetDatabaseProductVersion () pure virtual
Implemented in ODBCDatabaseMetaData.
Definition at line 612 of file MySQLDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 612 of file MySQLDatabaseMetaData.cxx
References TSQL::fImp, and MySQLConnectionPrivate::fMYSQL.
Referenced by productInfo(), and RDBCTestMetaData().
Int_t TSQLDatabaseMetaData::GetDefaultTransactionIsolation () pure virtual
Implemented in ODBCDatabaseMetaData.
Definition at line 2453 of file MySQLDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 2453 of file MySQLDatabaseMetaData.cxx
References kTRANSACTION_NONE.
Referenced by RDBCTestMetaData(), and transactionInfo().
Int_t TSQLDatabaseMetaData::GetDriverMajorVersion () pure virtual
Implemented in ODBCDatabaseMetaData.
Definition at line 667 of file MySQLDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 667 of file MySQLDatabaseMetaData.cxx
Referenced by RDBCTestMetaData().
Int_t TSQLDatabaseMetaData::GetDriverMinorVersion () pure virtual
Implemented in ODBCDatabaseMetaData.
Definition at line 679 of file MySQLDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 679 of file MySQLDatabaseMetaData.cxx
Referenced by RDBCTestMetaData().
TString TSQLDatabaseMetaData::GetDriverName () pure virtual
Implemented in ODBCDatabaseMetaData.
Definition at line 633 of file MySQLDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 633 of file MySQLDatabaseMetaData.cxx
Referenced by driverInfo(), and RDBCTestMetaData().
TString TSQLDatabaseMetaData::GetDriverVersion () pure virtual
Implemented in ODBCDatabaseMetaData.
Definition at line 646 of file MySQLDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 646 of file MySQLDatabaseMetaData.cxx
References str.
Referenced by driverInfo(), and RDBCTestMetaData().
TSQLResultSet * TSQLDatabaseMetaData::GetExportedKeys (const TString & catalog, const TString & schema, const TString & table) pure virtual
Implemented in ODBCDatabaseMetaData.
Definition at line 3367 of file MySQLDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 3367 of file MySQLDatabaseMetaData.cxx
References MySQLResultSetPrivate::Close(), con, fConnection, TSQL::fImp, and GetCrossReference().
TString TSQLDatabaseMetaData::GetExtraNameCharacters () pure virtual
Implemented in ODBCDatabaseMetaData.
Definition at line 993 of file MySQLDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 993 of file MySQLDatabaseMetaData.cxx
Referenced by RDBCTestMetaData().
TString TSQLDatabaseMetaData::GetIdentifierQuoteString () pure virtual
Implemented in ODBCDatabaseMetaData.
Definition at line 845 of file MySQLDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 845 of file MySQLDatabaseMetaData.cxx
Referenced by RDBCTestMetaData(), and schemaInfo().
TSQLResultSet * TSQLDatabaseMetaData::GetImportedKeys (const TString & catalog, const TString & schema, const TString & table) pure virtual
Implemented in ODBCDatabaseMetaData.
Definition at line 3273 of file MySQLDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 3273 of file MySQLDatabaseMetaData.cxx
References GetCrossReference().
TSQLResultSet * TSQLDatabaseMetaData::GetIndexInfo (const TString & catalog, const TString & schema, const TString & table, Bool_t unique, Bool_t approximate) pure virtual
Implemented in ODBCDatabaseMetaData.
Definition at line 3639 of file MySQLDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 3639 of file MySQLDatabaseMetaData.cxx
References MySQLResultSetPrivate::Close(), con, fConnection, and TSQL::fImp.
Int_t TSQLDatabaseMetaData::GetMaxBinaryLiteralLength () pure virtual
Implemented in ODBCDatabaseMetaData.
Definition at line 2121 of file MySQLDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 2121 of file MySQLDatabaseMetaData.cxx
References gMaxLiteralLength.
Referenced by RDBCTestMetaData().
Int_t TSQLDatabaseMetaData::GetMaxCatalogNameLength () pure virtual
Implemented in ODBCDatabaseMetaData.
Definition at line 2317 of file MySQLDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 2317 of file MySQLDatabaseMetaData.cxx
References gMaxDatabaseNameLength.
Referenced by RDBCTestMetaData().
Int_t TSQLDatabaseMetaData::GetMaxCharLiteralLength () pure virtual
Implemented in ODBCDatabaseMetaData.
Definition at line 2139 of file MySQLDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 2139 of file MySQLDatabaseMetaData.cxx
References gMaxLiteralLength.
Referenced by RDBCTestMetaData().
Int_t TSQLDatabaseMetaData::GetMaxColumnNameLength () pure virtual
Implemented in ODBCDatabaseMetaData.
Definition at line 2155 of file MySQLDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 2155 of file MySQLDatabaseMetaData.cxx
References gMaxColumnNameLength.
Referenced by RDBCTestMetaData().
Int_t TSQLDatabaseMetaData::GetMaxColumnsInGroupBy () pure virtual
Implemented in ODBCDatabaseMetaData.
Definition at line 2171 of file MySQLDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 2171 of file MySQLDatabaseMetaData.cxx
Referenced by RDBCTestMetaData().
Int_t TSQLDatabaseMetaData::GetMaxColumnsInIndex () pure virtual
Implemented in ODBCDatabaseMetaData.
Definition at line 2185 of file MySQLDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 2185 of file MySQLDatabaseMetaData.cxx
Referenced by RDBCTestMetaData().
Int_t TSQLDatabaseMetaData::GetMaxColumnsInOrderBy () pure virtual
Implemented in ODBCDatabaseMetaData.
Definition at line 2201 of file MySQLDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 2201 of file MySQLDatabaseMetaData.cxx
Referenced by RDBCTestMetaData().
Int_t TSQLDatabaseMetaData::GetMaxColumnsInSelect () pure virtual
Implemented in ODBCDatabaseMetaData.
Definition at line 2215 of file MySQLDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 2215 of file MySQLDatabaseMetaData.cxx
Referenced by RDBCTestMetaData().
Int_t TSQLDatabaseMetaData::GetMaxColumnsInTable () pure virtual
Implemented in ODBCDatabaseMetaData.
Definition at line 2229 of file MySQLDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 2229 of file MySQLDatabaseMetaData.cxx
Referenced by RDBCTestMetaData().
Int_t TSQLDatabaseMetaData::GetMaxConnections () pure virtual
Implemented in ODBCDatabaseMetaData.
Definition at line 2243 of file MySQLDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 2243 of file MySQLDatabaseMetaData.cxx
Referenced by RDBCTestMetaData().
Int_t TSQLDatabaseMetaData::GetMaxCursorNameLength () pure virtual
Implemented in ODBCDatabaseMetaData.
Definition at line 2259 of file MySQLDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 2259 of file MySQLDatabaseMetaData.cxx
Referenced by RDBCTestMetaData().
Int_t TSQLDatabaseMetaData::GetMaxIndexLength () pure virtual
Implemented in ODBCDatabaseMetaData.
Definition at line 2273 of file MySQLDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 2273 of file MySQLDatabaseMetaData.cxx
References gMaxIndexLength.
Referenced by RDBCTestMetaData().
Int_t TSQLDatabaseMetaData::GetMaxProcedureNameLength () pure virtual
Implemented in ODBCDatabaseMetaData.
Definition at line 2303 of file MySQLDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 2303 of file MySQLDatabaseMetaData.cxx
Referenced by RDBCTestMetaData().
Int_t TSQLDatabaseMetaData::GetMaxRowSize () pure virtual
Implemented in ODBCDatabaseMetaData.
Definition at line 2333 of file MySQLDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 2333 of file MySQLDatabaseMetaData.cxx
Referenced by RDBCTestMetaData().
Int_t TSQLDatabaseMetaData::GetMaxSchemaNameLength () pure virtual
Implemented in ODBCDatabaseMetaData.
Definition at line 2289 of file MySQLDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 2289 of file MySQLDatabaseMetaData.cxx
Referenced by RDBCTestMetaData().
Int_t TSQLDatabaseMetaData::GetMaxStatementLength () pure virtual
Implemented in ODBCDatabaseMetaData.
Definition at line 2361 of file MySQLDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 2361 of file MySQLDatabaseMetaData.cxx
Referenced by RDBCTestMetaData().
Int_t TSQLDatabaseMetaData::GetMaxStatements () pure virtual
Implemented in ODBCDatabaseMetaData.
Definition at line 2375 of file MySQLDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 2375 of file MySQLDatabaseMetaData.cxx
Referenced by RDBCTestMetaData().
Int_t TSQLDatabaseMetaData::GetMaxTableNameLength () pure virtual
Implemented in ODBCDatabaseMetaData.
Definition at line 2402 of file MySQLDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 2402 of file MySQLDatabaseMetaData.cxx
References gMaxTableNameLength.
Referenced by RDBCTestMetaData().
Int_t TSQLDatabaseMetaData::GetMaxTablesInSelect () pure virtual
Implemented in ODBCDatabaseMetaData.
Definition at line 2418 of file MySQLDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 2418 of file MySQLDatabaseMetaData.cxx
Referenced by RDBCTestMetaData().
Int_t TSQLDatabaseMetaData::GetMaxUserNameLength () pure virtual
Implemented in ODBCDatabaseMetaData.
Definition at line 2439 of file MySQLDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 2439 of file MySQLDatabaseMetaData.cxx
References gNameLength.
Referenced by RDBCTestMetaData().
TString TSQLDatabaseMetaData::GetNumericFunctions () pure virtual
Implemented in ODBCDatabaseMetaData.
Definition at line 891 of file MySQLDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 891 of file MySQLDatabaseMetaData.cxx
References str.
Referenced by funcInfo(), and RDBCTestMetaData().
TSQLResultSet * TSQLDatabaseMetaData::GetPrimaryKeys (const TString & catalog, const TString & schema, const TString & table) pure virtual
Implemented in ODBCDatabaseMetaData.
Definition at line 3231 of file MySQLDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 3231 of file MySQLDatabaseMetaData.cxx
References MySQLResultSetPrivate::Close(), con, fConnection, and TSQL::fImp.
TSQLResultSet * TSQLDatabaseMetaData::GetProcedureColumns (const TString & catalog, const TString & schemaPattern, const TString & procedureNamePattern, const TString & columnNamePattern) pure virtual
Implemented in ODBCDatabaseMetaData.
Definition at line 2609 of file MySQLDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 2609 of file MySQLDatabaseMetaData.cxx
References TSQL::Throw().
TSQLResultSet * TSQLDatabaseMetaData::GetProcedures (const TString & catalog, const TString & schemaPattern, const TString & procedureNamePattern) pure virtual
Implemented in ODBCDatabaseMetaData.
Definition at line 2558 of file MySQLDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 2558 of file MySQLDatabaseMetaData.cxx
References TSQL::Throw().
TString TSQLDatabaseMetaData::GetProcedureTerm () pure virtual
Implemented in ODBCDatabaseMetaData.
Definition at line 1603 of file MySQLDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 1603 of file MySQLDatabaseMetaData.cxx
Referenced by RDBCTestMetaData().
TSQLResultSet * TSQLDatabaseMetaData::GetSchemas () pure virtual
Implemented in ODBCDatabaseMetaData.
Definition at line 2817 of file MySQLDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 2817 of file MySQLDatabaseMetaData.cxx
References MySQLResultSetPrivate::Close(), con, fConnection, TSQL::fImp, and MySQLResultSetPrivate::fMYSQL_RES.
TString TSQLDatabaseMetaData::GetSchemaTerm () pure virtual
Implemented in ODBCDatabaseMetaData.
Definition at line 1570 of file MySQLDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 1570 of file MySQLDatabaseMetaData.cxx
Referenced by RDBCTestMetaData().
TString TSQLDatabaseMetaData::GetSearchStringEscape () pure virtual
Implemented in ODBCDatabaseMetaData.
Definition at line 967 of file MySQLDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 967 of file MySQLDatabaseMetaData.cxx
Referenced by RDBCTestMetaData().
TString TSQLDatabaseMetaData::GetSQLKeywords () pure virtual
Implemented in ODBCDatabaseMetaData.
Definition at line 873 of file MySQLDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 873 of file MySQLDatabaseMetaData.cxx
References str.
Referenced by keywordInfo(), and RDBCTestMetaData().
TString TSQLDatabaseMetaData::GetStringFunctions () pure virtual
Implemented in ODBCDatabaseMetaData.
Definition at line 909 of file MySQLDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 909 of file MySQLDatabaseMetaData.cxx
References str.
Referenced by funcInfo(), and RDBCTestMetaData().
TString TSQLDatabaseMetaData::GetSystemFunctions () pure virtual
Implemented in ODBCDatabaseMetaData.
Definition at line 930 of file MySQLDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 930 of file MySQLDatabaseMetaData.cxx
References str.
Referenced by funcInfo(), and RDBCTestMetaData().
TSQLResultSet * TSQLDatabaseMetaData::GetTablePrivileges (const TString & catalog, const TString & schemaPattern, const TString & tableNamePattern) pure virtual
Implemented in ODBCDatabaseMetaData.
Definition at line 3061 of file MySQLDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 3061 of file MySQLDatabaseMetaData.cxx
References MySQLResultSetPrivate::Close(), con, fConnection, TSQL::fImp, and TSQL::Throw().
TSQLResultSet * TSQLDatabaseMetaData::GetTables (const TString & catalog, const TString & schemaPattern, const TString & tableNamePattern, const TString & types) pure virtual
Implemented in ODBCDatabaseMetaData.
Definition at line 2691 of file MySQLDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 2691 of file MySQLDatabaseMetaData.cxx
References MySQLResultSetPrivate::Close(), con, Acts::Test::db, fConnection, TSQL::fImp, MySQLConnectionPrivate::fMYSQL, MySQLResultSetPrivate::fMYSQL_RES, MySQLConnectionPrivate::fURL, and TSQL::Throw().
Referenced by RDBCTestMetaData().
TString TSQLDatabaseMetaData::GetTableTerm () pure virtual
Implemented in ODBCDatabaseMetaData.
Definition at line 1588 of file MySQLDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 1588 of file MySQLDatabaseMetaData.cxx
Referenced by catalogInfo(), RDBCTestMetaData(), and schemaInfo().
TSQLResultSet * TSQLDatabaseMetaData::GetTableTypes () pure virtual
Implemented in ODBCDatabaseMetaData.
Definition at line 2884 of file MySQLDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 2884 of file MySQLDatabaseMetaData.cxx
References MySQLResultSetPrivate::Close(), con, fConnection, TSQL::fImp, and MySQLResultSetPrivate::fMYSQL_RES.
TString TSQLDatabaseMetaData::GetTimeDateFunctions () pure virtual
Implemented in ODBCDatabaseMetaData.
Definition at line 947 of file MySQLDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 947 of file MySQLDatabaseMetaData.cxx
References str.
Referenced by funcInfo(), and RDBCTestMetaData().
TSQLResultSet * TSQLDatabaseMetaData::GetTypeInfo () pure virtual
Implemented in ODBCDatabaseMetaData.
Definition at line 3568 of file MySQLDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 3568 of file MySQLDatabaseMetaData.cxx
References MySQLResultSetPrivate::Close(), con, fConnection, and TSQL::fImp.
virtual TString TSQLDatabaseMetaData::GetURL () const inline virtual
Definition at line 275 of file TSQLDatabaseMetaData.h.
View newest version in sPHENIX GitHub at line 275 of file TSQLDatabaseMetaData.h
References fUrl.
Referenced by TSQLConnection::GetName(), and TSQLConnection::Print().
TString TSQLDatabaseMetaData::GetUserName () pure virtual
Implemented in ODBCDatabaseMetaData.
Definition at line 485 of file MySQLDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 485 of file MySQLDatabaseMetaData.cxx
References TSQLStatement::ExecuteQuery(), fConnection, TSQLResultSet::GetString(), TSQLResultSet::Next(), and str.
Referenced by RDBCTestMetaData().
TSQLResultSet * TSQLDatabaseMetaData::GetVersionColumns (const TString & catalog, const TString & schema, const TString & table) pure virtual
Implemented in ODBCDatabaseMetaData.
Definition at line 3180 of file MySQLDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 3180 of file MySQLDatabaseMetaData.cxx
References MySQLResultSetPrivate::Close(), con, fConnection, TSQL::fImp, and TSQL::Throw().
Bool_t TSQLDatabaseMetaData::InsertsAreDetected (Int_t type) pure virtual
Implemented in ODBCDatabaseMetaData.
Definition at line 3934 of file MySQLDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 3934 of file MySQLDatabaseMetaData.cxx
Bool_t TSQLDatabaseMetaData::IsCatalogAtStart () pure virtual
Implemented in ODBCDatabaseMetaData.
Definition at line 1638 of file MySQLDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 1638 of file MySQLDatabaseMetaData.cxx
Referenced by catalogInfo(), and RDBCTestMetaData().
Bool_t TSQLDatabaseMetaData::IsReadOnly () pure virtual
Implemented in ODBCDatabaseMetaData.
Definition at line 510 of file MySQLDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 510 of file MySQLDatabaseMetaData.cxx
Referenced by RDBCTestMetaData().
Bool_t TSQLDatabaseMetaData::NullPlusNonNullIsNull () pure virtual
Implemented in ODBCDatabaseMetaData.
Definition at line 1055 of file MySQLDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 1055 of file MySQLDatabaseMetaData.cxx
Referenced by RDBCTestMetaData().
Bool_t TSQLDatabaseMetaData::NullsAreSortedAtEnd () pure virtual
Implemented in ODBCDatabaseMetaData.
Definition at line 583 of file MySQLDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 583 of file MySQLDatabaseMetaData.cxx
Referenced by RDBCTestMetaData().
Bool_t TSQLDatabaseMetaData::NullsAreSortedAtStart () pure virtual
Implemented in ODBCDatabaseMetaData.
Definition at line 567 of file MySQLDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 567 of file MySQLDatabaseMetaData.cxx
Referenced by RDBCTestMetaData().
Bool_t TSQLDatabaseMetaData::NullsAreSortedHigh () pure virtual
Implemented in ODBCDatabaseMetaData.
Definition at line 535 of file MySQLDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 535 of file MySQLDatabaseMetaData.cxx
Referenced by NullsAreSortedLow(), and RDBCTestMetaData().
Bool_t TSQLDatabaseMetaData::NullsAreSortedLow () pure virtual
Implemented in ODBCDatabaseMetaData.
Definition at line 551 of file MySQLDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 551 of file MySQLDatabaseMetaData.cxx
References NullsAreSortedHigh().
Referenced by RDBCTestMetaData().
Bool_t TSQLDatabaseMetaData::OthersDeletesAreVisible (Int_t type) pure virtual
Implemented in ODBCDatabaseMetaData.
Definition at line 3864 of file MySQLDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 3864 of file MySQLDatabaseMetaData.cxx
Bool_t TSQLDatabaseMetaData::OthersInsertsAreVisible (Int_t type) pure virtual
Implemented in ODBCDatabaseMetaData.
Definition at line 3881 of file MySQLDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 3881 of file MySQLDatabaseMetaData.cxx
Bool_t TSQLDatabaseMetaData::OthersUpdatesAreVisible (Int_t type) pure virtual
Implemented in ODBCDatabaseMetaData.
Definition at line 3847 of file MySQLDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 3847 of file MySQLDatabaseMetaData.cxx
Bool_t TSQLDatabaseMetaData::OwnDeletesAreVisible (Int_t type) pure virtual
Implemented in ODBCDatabaseMetaData.
Definition at line 3809 of file MySQLDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 3809 of file MySQLDatabaseMetaData.cxx
Referenced by rsInfo().
Bool_t TSQLDatabaseMetaData::OwnInsertsAreVisible (Int_t type) pure virtual
Implemented in ODBCDatabaseMetaData.
Definition at line 3828 of file MySQLDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 3828 of file MySQLDatabaseMetaData.cxx
Referenced by rsInfo().
Bool_t TSQLDatabaseMetaData::OwnUpdatesAreVisible (Int_t type) pure virtual
Implemented in ODBCDatabaseMetaData.
Definition at line 3789 of file MySQLDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 3789 of file MySQLDatabaseMetaData.cxx
Referenced by rsInfo().
void TSQLDatabaseMetaData::Set (TSQLConnection * connection, void * imp = 0) inline protected
Definition at line 29 of file TSQLDatabaseMetaData.h.
View newest version in sPHENIX GitHub at line 29 of file TSQLDatabaseMetaData.h
References fConnection, and TSQL::fImp.
void TSQLDatabaseMetaData::SetURL (const TString & url) inline protected
Definition at line 28 of file TSQLDatabaseMetaData.h.
View newest version in sPHENIX GitHub at line 28 of file TSQLDatabaseMetaData.h
References fUrl, and summary::url.
Referenced by TSQLConnection::SetURL().
Bool_t TSQLDatabaseMetaData::StoresLowerCaseIdentifiers () pure virtual
Implemented in ODBCDatabaseMetaData.
Definition at line 757 of file MySQLDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 757 of file MySQLDatabaseMetaData.cxx
Referenced by RDBCTestMetaData().
Bool_t TSQLDatabaseMetaData::StoresLowerCaseQuotedIdentifiers () pure virtual
Implemented in ODBCDatabaseMetaData.
Definition at line 817 of file MySQLDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 817 of file MySQLDatabaseMetaData.cxx
Referenced by RDBCTestMetaData().
Bool_t TSQLDatabaseMetaData::StoresMixedCaseIdentifiers () pure virtual
Implemented in ODBCDatabaseMetaData.
Definition at line 771 of file MySQLDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 771 of file MySQLDatabaseMetaData.cxx
Referenced by RDBCTestMetaData().
Bool_t TSQLDatabaseMetaData::StoresMixedCaseQuotedIdentifiers () pure virtual
Implemented in ODBCDatabaseMetaData.
Definition at line 831 of file MySQLDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 831 of file MySQLDatabaseMetaData.cxx
Referenced by RDBCTestMetaData().
Bool_t TSQLDatabaseMetaData::StoresUpperCaseIdentifiers () pure virtual
Implemented in ODBCDatabaseMetaData.
Definition at line 743 of file MySQLDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 743 of file MySQLDatabaseMetaData.cxx
Referenced by RDBCTestMetaData().
Bool_t TSQLDatabaseMetaData::StoresUpperCaseQuotedIdentifiers () pure virtual
Implemented in ODBCDatabaseMetaData.
Definition at line 803 of file MySQLDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 803 of file MySQLDatabaseMetaData.cxx
Referenced by RDBCTestMetaData().
Bool_t TSQLDatabaseMetaData::SupportsAlterTableWithAddColumn () pure virtual
Implemented in ODBCDatabaseMetaData.
Definition at line 1008 of file MySQLDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 1008 of file MySQLDatabaseMetaData.cxx
Referenced by RDBCTestMetaData().
Bool_t TSQLDatabaseMetaData::SupportsAlterTableWithDropColumn () pure virtual
Implemented in ODBCDatabaseMetaData.
Definition at line 1022 of file MySQLDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 1022 of file MySQLDatabaseMetaData.cxx
Referenced by RDBCTestMetaData().
Bool_t TSQLDatabaseMetaData::SupportsANSI92EntryLevelSQL () pure virtual
Implemented in ODBCDatabaseMetaData.
Definition at line 1472 of file MySQLDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 1472 of file MySQLDatabaseMetaData.cxx
Referenced by RDBCTestMetaData().
Bool_t TSQLDatabaseMetaData::SupportsANSI92FullSQL () pure virtual
Implemented in ODBCDatabaseMetaData.
Definition at line 1501 of file MySQLDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 1501 of file MySQLDatabaseMetaData.cxx
Referenced by RDBCTestMetaData().
Bool_t TSQLDatabaseMetaData::SupportsANSI92IntermediateSQL () pure virtual
Implemented in ODBCDatabaseMetaData.
Definition at line 1487 of file MySQLDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 1487 of file MySQLDatabaseMetaData.cxx
Referenced by RDBCTestMetaData().
Bool_t TSQLDatabaseMetaData::SupportsBatchUpdates () pure virtual
Implemented in ODBCDatabaseMetaData.
Definition at line 3951 of file MySQLDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 3951 of file MySQLDatabaseMetaData.cxx
Bool_t TSQLDatabaseMetaData::SupportsCatalogsInDataManipulation () pure virtual
Implemented in ODBCDatabaseMetaData.
Definition at line 1768 of file MySQLDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 1768 of file MySQLDatabaseMetaData.cxx
Referenced by catalogInfo(), and RDBCTestMetaData().
Bool_t TSQLDatabaseMetaData::SupportsCatalogsInIndexDefinitions () pure virtual
Implemented in ODBCDatabaseMetaData.
Definition at line 1841 of file MySQLDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 1841 of file MySQLDatabaseMetaData.cxx
Referenced by catalogInfo(), and RDBCTestMetaData().
Bool_t TSQLDatabaseMetaData::SupportsCatalogsInPrivilegeDefinitions () pure virtual
Implemented in ODBCDatabaseMetaData.
Definition at line 1859 of file MySQLDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 1859 of file MySQLDatabaseMetaData.cxx
Referenced by catalogInfo(), and RDBCTestMetaData().
Bool_t TSQLDatabaseMetaData::SupportsCatalogsInProcedureCalls () pure virtual
Implemented in ODBCDatabaseMetaData.
Definition at line 1808 of file MySQLDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 1808 of file MySQLDatabaseMetaData.cxx
Referenced by catalogInfo(), and RDBCTestMetaData().
Bool_t TSQLDatabaseMetaData::SupportsCatalogsInTableDefinitions () pure virtual
Implemented in ODBCDatabaseMetaData.
Definition at line 1823 of file MySQLDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 1823 of file MySQLDatabaseMetaData.cxx
Referenced by catalogInfo(), and RDBCTestMetaData().
Bool_t TSQLDatabaseMetaData::SupportsColumnAliasing () pure virtual
Implemented in ODBCDatabaseMetaData.
Definition at line 1036 of file MySQLDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 1036 of file MySQLDatabaseMetaData.cxx
Referenced by RDBCTestMetaData().
Bool_t TSQLDatabaseMetaData::SupportsConvert () pure virtual
Implemented in ODBCDatabaseMetaData.
Definition at line 1070 of file MySQLDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 1070 of file MySQLDatabaseMetaData.cxx
Referenced by RDBCTestMetaData().
Bool_t TSQLDatabaseMetaData::SupportsConvert (Int_t fromType, Int_t toType) pure virtual
Implemented in ODBCDatabaseMetaData.
Definition at line 1083 of file MySQLDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 1083 of file MySQLDatabaseMetaData.cxx
References kBIGINT, kBINARY, kBIT, kCHAR, kDATE, kDECIMAL, kDOUBLE, kFLOAT, kINTEGER, kLONGVARBINARY, kLONGVARCHAR, kNUMERIC, kREAL, kSMALLINT, kTIME, kTIMESTAMP, kTINYINT, kVARBINARY, and kVARCHAR.
Bool_t TSQLDatabaseMetaData::SupportsCoreSQLGrammar () pure virtual
Implemented in ODBCDatabaseMetaData.
Definition at line 1444 of file MySQLDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 1444 of file MySQLDatabaseMetaData.cxx
Referenced by RDBCTestMetaData().
Bool_t TSQLDatabaseMetaData::SupportsCorrelatedSubqueries () pure virtual
Implemented in ODBCDatabaseMetaData.
Definition at line 1987 of file MySQLDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 1987 of file MySQLDatabaseMetaData.cxx
Referenced by RDBCTestMetaData().
Bool_t TSQLDatabaseMetaData::SupportsDataDefinitionAndDataManipulationTransactions () pure virtual
Implemented in ODBCDatabaseMetaData.
Definition at line 2503 of file MySQLDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 2503 of file MySQLDatabaseMetaData.cxx
Referenced by RDBCTestMetaData(), and transactionInfo().
Bool_t TSQLDatabaseMetaData::SupportsDataManipulationTransactionsOnly () pure virtual
Implemented in ODBCDatabaseMetaData.
Definition at line 2517 of file MySQLDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 2517 of file MySQLDatabaseMetaData.cxx
Referenced by RDBCTestMetaData(), and transactionInfo().
Bool_t TSQLDatabaseMetaData::SupportsDifferentTableCorrelationNames () pure virtual
Implemented in ODBCDatabaseMetaData.
Definition at line 1270 of file MySQLDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 1270 of file MySQLDatabaseMetaData.cxx
Referenced by RDBCTestMetaData().
Bool_t TSQLDatabaseMetaData::SupportsExpressionsInOrderBy () pure virtual
Implemented in ODBCDatabaseMetaData.
Definition at line 1285 of file MySQLDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 1285 of file MySQLDatabaseMetaData.cxx
Referenced by RDBCTestMetaData().
Bool_t TSQLDatabaseMetaData::SupportsExtendedSQLGrammar () pure virtual
Implemented in ODBCDatabaseMetaData.
Definition at line 1458 of file MySQLDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 1458 of file MySQLDatabaseMetaData.cxx
Referenced by RDBCTestMetaData().
Bool_t TSQLDatabaseMetaData::SupportsFullOuterJoins () pure virtual
Implemented in ODBCDatabaseMetaData.
Definition at line 1542 of file MySQLDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 1542 of file MySQLDatabaseMetaData.cxx
Referenced by RDBCTestMetaData().
Bool_t TSQLDatabaseMetaData::SupportsGroupBy () pure virtual
Implemented in ODBCDatabaseMetaData.
Definition at line 1314 of file MySQLDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 1314 of file MySQLDatabaseMetaData.cxx
Referenced by RDBCTestMetaData().
Bool_t TSQLDatabaseMetaData::SupportsGroupByBeyondSelect () pure virtual
Implemented in ODBCDatabaseMetaData.
Definition at line 1345 of file MySQLDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 1345 of file MySQLDatabaseMetaData.cxx
Referenced by RDBCTestMetaData().
Bool_t TSQLDatabaseMetaData::SupportsGroupByUnrelated () pure virtual
Implemented in ODBCDatabaseMetaData.
Definition at line 1328 of file MySQLDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 1328 of file MySQLDatabaseMetaData.cxx
Referenced by RDBCTestMetaData().
Bool_t TSQLDatabaseMetaData::SupportsIntegrityEnhancementFacility () pure virtual
Implemented in ODBCDatabaseMetaData.
Definition at line 1515 of file MySQLDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 1515 of file MySQLDatabaseMetaData.cxx
Referenced by RDBCTestMetaData().
Bool_t TSQLDatabaseMetaData::SupportsLikeEscapeClause () pure virtual
Implemented in ODBCDatabaseMetaData.
Definition at line 1363 of file MySQLDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 1363 of file MySQLDatabaseMetaData.cxx
Referenced by RDBCTestMetaData().
Bool_t TSQLDatabaseMetaData::SupportsLimitedOuterJoins () pure virtual
Implemented in ODBCDatabaseMetaData.
Definition at line 1555 of file MySQLDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 1555 of file MySQLDatabaseMetaData.cxx
Referenced by RDBCTestMetaData().
Bool_t TSQLDatabaseMetaData::SupportsMinimumSQLGrammar () pure virtual
Implemented in ODBCDatabaseMetaData.
Definition at line 1429 of file MySQLDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 1429 of file MySQLDatabaseMetaData.cxx
Referenced by RDBCTestMetaData().
Bool_t TSQLDatabaseMetaData::SupportsMixedCaseIdentifiers () pure virtual
Implemented in ODBCDatabaseMetaData.
Definition at line 728 of file MySQLDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 728 of file MySQLDatabaseMetaData.cxx
Referenced by RDBCTestMetaData().
Bool_t TSQLDatabaseMetaData::SupportsMixedCaseQuotedIdentifiers () pure virtual
Implemented in ODBCDatabaseMetaData.
Definition at line 786 of file MySQLDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 786 of file MySQLDatabaseMetaData.cxx
Referenced by RDBCTestMetaData().
Bool_t TSQLDatabaseMetaData::SupportsMultipleResultSets () pure virtual
Implemented in ODBCDatabaseMetaData.
Definition at line 1379 of file MySQLDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 1379 of file MySQLDatabaseMetaData.cxx
Referenced by RDBCTestMetaData().
Bool_t TSQLDatabaseMetaData::SupportsMultipleTransactions () pure virtual
Implemented in ODBCDatabaseMetaData.
Definition at line 1393 of file MySQLDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 1393 of file MySQLDatabaseMetaData.cxx
Referenced by RDBCTestMetaData().
Bool_t TSQLDatabaseMetaData::SupportsNonNullableColumns () pure virtual
Implemented in ODBCDatabaseMetaData.
Definition at line 1408 of file MySQLDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 1408 of file MySQLDatabaseMetaData.cxx
Referenced by RDBCTestMetaData().
Bool_t TSQLDatabaseMetaData::SupportsOpenCursorsAcrossRollback () pure virtual
Implemented in ODBCDatabaseMetaData.
Definition at line 2057 of file MySQLDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 2057 of file MySQLDatabaseMetaData.cxx
Referenced by RDBCTestMetaData().
Bool_t TSQLDatabaseMetaData::SupportsOpenStatementsAcrossCommit () pure virtual
Implemented in ODBCDatabaseMetaData.
Definition at line 2085 of file MySQLDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 2085 of file MySQLDatabaseMetaData.cxx
Referenced by RDBCTestMetaData().
Bool_t TSQLDatabaseMetaData::SupportsOpenStatementsAcrossRollback () pure virtual
Implemented in ODBCDatabaseMetaData.
Definition at line 2103 of file MySQLDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 2103 of file MySQLDatabaseMetaData.cxx
Referenced by RDBCTestMetaData().
Bool_t TSQLDatabaseMetaData::SupportsOrderByUnrelated () pure virtual
Implemented in ODBCDatabaseMetaData.
Definition at line 1299 of file MySQLDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 1299 of file MySQLDatabaseMetaData.cxx
Referenced by RDBCTestMetaData().
Bool_t TSQLDatabaseMetaData::SupportsOuterJoins () pure virtual
Implemented in ODBCDatabaseMetaData.
Definition at line 1528 of file MySQLDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 1528 of file MySQLDatabaseMetaData.cxx
Referenced by RDBCTestMetaData().
Bool_t TSQLDatabaseMetaData::SupportsPositionedDelete () pure virtual
Implemented in ODBCDatabaseMetaData.
Definition at line 1877 of file MySQLDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 1877 of file MySQLDatabaseMetaData.cxx
Referenced by RDBCTestMetaData().
Bool_t TSQLDatabaseMetaData::SupportsPositionedUpdate () pure virtual
Implemented in ODBCDatabaseMetaData.
Definition at line 1890 of file MySQLDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 1890 of file MySQLDatabaseMetaData.cxx
Referenced by RDBCTestMetaData().
Bool_t TSQLDatabaseMetaData::SupportsResultSetConcurrency (Int_t type, Int_t concurrency) pure virtual
Implemented in ODBCDatabaseMetaData.
Definition at line 3767 of file MySQLDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 3767 of file MySQLDatabaseMetaData.cxx
References kCONCUR_READ_ONLY, and kTYPE_SCROLL_SENSITIVE.
Referenced by Compare(), DbForm::HandleConnect(), and rsInfo().
Bool_t TSQLDatabaseMetaData::SupportsResultSetType (Int_t type) pure virtual
Implemented in ODBCDatabaseMetaData.
Definition at line 3749 of file MySQLDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 3749 of file MySQLDatabaseMetaData.cxx
References kTYPE_FORWARD_ONLY, and kTYPE_SCROLL_INSENSITIVE.
Referenced by Compare(), DbForm::HandleConnect(), and rsInfo().
Bool_t TSQLDatabaseMetaData::SupportsSchemasInDataManipulation () pure virtual
Implemented in ODBCDatabaseMetaData.
Definition at line 1678 of file MySQLDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 1678 of file MySQLDatabaseMetaData.cxx
Referenced by RDBCTestMetaData(), and schemaInfo().
Bool_t TSQLDatabaseMetaData::SupportsSchemasInIndexDefinitions () pure virtual
Implemented in ODBCDatabaseMetaData.
Definition at line 1734 of file MySQLDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 1734 of file MySQLDatabaseMetaData.cxx
Referenced by RDBCTestMetaData(), and schemaInfo().
Bool_t TSQLDatabaseMetaData::SupportsSchemasInPrivilegeDefinitions () pure virtual
Implemented in ODBCDatabaseMetaData.
Definition at line 1750 of file MySQLDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 1750 of file MySQLDatabaseMetaData.cxx
Referenced by RDBCTestMetaData(), and schemaInfo().
Bool_t TSQLDatabaseMetaData::SupportsSchemasInProcedureCalls () pure virtual
Implemented in ODBCDatabaseMetaData.
Definition at line 1702 of file MySQLDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 1702 of file MySQLDatabaseMetaData.cxx
Referenced by RDBCTestMetaData(), and schemaInfo().
Bool_t TSQLDatabaseMetaData::SupportsSchemasInTableDefinitions () pure virtual
Implemented in ODBCDatabaseMetaData.
Definition at line 1715 of file MySQLDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 1715 of file MySQLDatabaseMetaData.cxx
Referenced by RDBCTestMetaData(), and schemaInfo().
Bool_t TSQLDatabaseMetaData::SupportsSelectForUpdate () pure virtual
Implemented in ODBCDatabaseMetaData.
Definition at line 1903 of file MySQLDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 1903 of file MySQLDatabaseMetaData.cxx
Referenced by RDBCTestMetaData().
Bool_t TSQLDatabaseMetaData::SupportsStoredProcedures () pure virtual
Implemented in ODBCDatabaseMetaData.
Definition at line 1916 of file MySQLDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 1916 of file MySQLDatabaseMetaData.cxx
Referenced by RDBCTestMetaData().
Bool_t TSQLDatabaseMetaData::SupportsSubqueriesInComparisons () pure virtual
Implemented in ODBCDatabaseMetaData.
Definition at line 1930 of file MySQLDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 1930 of file MySQLDatabaseMetaData.cxx
Referenced by RDBCTestMetaData().
Bool_t TSQLDatabaseMetaData::SupportsSubqueriesInExists () pure virtual
Implemented in ODBCDatabaseMetaData.
Definition at line 1945 of file MySQLDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 1945 of file MySQLDatabaseMetaData.cxx
Referenced by RDBCTestMetaData().
Bool_t TSQLDatabaseMetaData::SupportsSubqueriesInIns () pure virtual
Implemented in ODBCDatabaseMetaData.
Definition at line 1959 of file MySQLDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 1959 of file MySQLDatabaseMetaData.cxx
Referenced by RDBCTestMetaData().
Bool_t TSQLDatabaseMetaData::SupportsSubqueriesInQuantifieds () pure virtual
Implemented in ODBCDatabaseMetaData.
Definition at line 1973 of file MySQLDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 1973 of file MySQLDatabaseMetaData.cxx
Referenced by RDBCTestMetaData().
Bool_t TSQLDatabaseMetaData::SupportsTableCorrelationNames () pure virtual
Implemented in ODBCDatabaseMetaData.
Definition at line 1255 of file MySQLDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 1255 of file MySQLDatabaseMetaData.cxx
Referenced by RDBCTestMetaData().
Bool_t TSQLDatabaseMetaData::SupportsTransactionIsolationLevel (Int_t level) pure virtual
Implemented in ODBCDatabaseMetaData.
Definition at line 2483 of file MySQLDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 2483 of file MySQLDatabaseMetaData.cxx
Referenced by transactionInfo().
Bool_t TSQLDatabaseMetaData::SupportsTransactions () pure virtual
Implemented in ODBCDatabaseMetaData.
Definition at line 2469 of file MySQLDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 2469 of file MySQLDatabaseMetaData.cxx
Referenced by oproducer(), RDBCTestMetaData(), and transactionInfo().
Bool_t TSQLDatabaseMetaData::SupportsUnion () pure virtual
Implemented in ODBCDatabaseMetaData.
Definition at line 2001 of file MySQLDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 2001 of file MySQLDatabaseMetaData.cxx
Referenced by RDBCTestMetaData().
Bool_t TSQLDatabaseMetaData::SupportsUnionAll () pure virtual
Implemented in ODBCDatabaseMetaData.
Definition at line 2015 of file MySQLDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 2015 of file MySQLDatabaseMetaData.cxx
Referenced by RDBCTestMetaData().
Bool_t TSQLDatabaseMetaData::UpdatesAreDetected (Int_t type) pure virtual
Implemented in ODBCDatabaseMetaData.
Definition at line 3897 of file MySQLDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 3897 of file MySQLDatabaseMetaData.cxx
Bool_t TSQLDatabaseMetaData::UsesLocalFilePerTable () pure virtual
Implemented in ODBCDatabaseMetaData.
Definition at line 709 of file MySQLDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 709 of file MySQLDatabaseMetaData.cxx
Referenced by RDBCTestMetaData().
Bool_t TSQLDatabaseMetaData::UsesLocalFiles () pure virtual
Implemented in ODBCDatabaseMetaData.
Definition at line 691 of file MySQLDatabaseMetaData.cxx.
View newest version in sPHENIX GitHub at line 691 of file MySQLDatabaseMetaData.cxx
Referenced by RDBCTestMetaData().
Friends And Related Function Documentation
friend class TSQLConnection friend
Definition at line 19 of file TSQLDatabaseMetaData.h.
View newest version in sPHENIX GitHub at line 19 of file TSQLDatabaseMetaData.h
Member Data Documentation
TSQLConnection* TSQLDatabaseMetaData::fConnection protected
Definition at line 22 of file TSQLDatabaseMetaData.h.
View newest version in sPHENIX GitHub at line 22 of file TSQLDatabaseMetaData.h
Referenced by GetBestRowIdentifier(), GetCatalogs(), GetColumnPrivileges(), GetColumns(), GetConnection(), GetCrossReference(), GetExportedKeys(), GetIndexInfo(), GetPrimaryKeys(), GetSchemas(), GetTablePrivileges(), GetTables(), GetTableTypes(), GetTypeInfo(), GetUserName(), GetVersionColumns(), Set(), TSQLDatabaseMetaData(), and ~TSQLDatabaseMetaData().
TString TSQLDatabaseMetaData::fUrl protected
Definition at line 23 of file TSQLDatabaseMetaData.h.
View newest version in sPHENIX GitHub at line 23 of file TSQLDatabaseMetaData.h
Referenced by GetURL(), and SetURL().
The documentation for this class was generated from the following files:
RDBC/blob/master/include/RDBC/TSQLDatabaseMetaData.h
RDBC/blob/master/mysql/MySQLDatabaseMetaData.cxx
RDBC/blob/master/rdbc/TSQLDatabaseMetaData.cxx