Analysis Software: acts/blob/sPHENIX/Tests/UnitTests/Core/Surfaces/SurfaceLocalToGlobalRoundtripTests.cpp File Reference
SurfaceLocalToGlobalRoundtripTests.cpp File Reference
#include <boost/test/data/test_case.hpp>
#include <boost/test/unit_test.hpp>
#include "Acts/Definitions/Algebra.hpp"
#include "Acts/Definitions/Common.hpp"
#include "Acts/Geometry/GeometryContext.hpp"
#include "Acts/Surfaces/ConeSurface.hpp"
#include "Acts/Surfaces/CylinderSurface.hpp"
#include "Acts/Surfaces/DiscSurface.hpp"
#include "Acts/Surfaces/PerigeeSurface.hpp"
#include "Acts/Surfaces/PlaneSurface.hpp"
#include "Acts/Surfaces/StrawSurface.hpp"
#include "Acts/Surfaces/Surface.hpp"
#include "Acts/Tests/CommonHelpers/FloatComparisons.hpp"
#include "Acts/Utilities/Result.hpp"
#include "Acts/Utilities/UnitVectors.hpp"
#include <cmath>
#include <limits>
#include <memory>
#include <ostream>
#include <type_traits>
#include <utility>
#include <vector>
Functions
BOOST_DATA_TEST_CASE (ConeSurface, cones *posAngle *posPositiveNonzero *phis *thetas, surface, lphi, lz, phi, theta)
BOOST_DATA_TEST_CASE (CylinderSurface, cylinders *posSymmetric *posSymmetric *phis *thetas, surface, lrphi, lz, phi, theta)
BOOST_DATA_TEST_CASE (DiscSurface, discs *posPositive *posAngle *phis *thetas, surface, lr, lphi, phi, theta)
BOOST_DATA_TEST_CASE (PerigeeSurface, perigees *posSymmetric *posSymmetric *phis *thetasNoForwardBackward, surface, d0, z0, phi, theta)
BOOST_DATA_TEST_CASE (PlaneSurface, planes *posSymmetric *posSymmetric *phis *thetas, surface, l0, l1, phi, theta)
BOOST_DATA_TEST_CASE (StrawSurface, straws *posSymmetric *posSymmetric *phis *thetasNoForwardBackward, surface, lr, lz, phi, theta)
Function Documentation
BOOST_DATA_TEST_CASE (ConeSurface , cones *posAngle *posPositiveNonzero *phis * thetas, surface , lphi , lz , phi , theta)
Definition at line 118 of file SurfaceLocalToGlobalRoundtripTests.cpp.
View newest version in sPHENIX GitHub at line 118 of file SurfaceLocalToGlobalRoundtripTests.cpp
References physmon_track_finding_ttbar::r, and Acts::Test::runTest().
BOOST_DATA_TEST_CASE (CylinderSurface , cylinders *posSymmetric *posSymmetric *phis * thetas, surface , lrphi , lz , phi , theta)
Definition at line 128 of file SurfaceLocalToGlobalRoundtripTests.cpp.
View newest version in sPHENIX GitHub at line 128 of file SurfaceLocalToGlobalRoundtripTests.cpp
References Acts::Test::runTest().
BOOST_DATA_TEST_CASE (DiscSurface , discs *posPositive *posAngle *phis * thetas, surface , lr , lphi , phi , theta)
Definition at line 134 of file SurfaceLocalToGlobalRoundtripTests.cpp.
View newest version in sPHENIX GitHub at line 134 of file SurfaceLocalToGlobalRoundtripTests.cpp
References Acts::Test::runTest().
BOOST_DATA_TEST_CASE (PerigeeSurface , perigees *posSymmetric *posSymmetric *phis * thetasNoForwardBackward, surface , d0 , z0 , phi , theta)
Definition at line 140 of file SurfaceLocalToGlobalRoundtripTests.cpp.
View newest version in sPHENIX GitHub at line 140 of file SurfaceLocalToGlobalRoundtripTests.cpp
References Acts::Test::runTest().
BOOST_DATA_TEST_CASE (PlaneSurface , planes *posSymmetric *posSymmetric *phis * thetas, surface , l0 , l1 , phi , theta)
Definition at line 148 of file SurfaceLocalToGlobalRoundtripTests.cpp.
View newest version in sPHENIX GitHub at line 148 of file SurfaceLocalToGlobalRoundtripTests.cpp
References Acts::Test::runTest().
BOOST_DATA_TEST_CASE (StrawSurface , straws *posSymmetric *posSymmetric *phis * thetasNoForwardBackward, surface , lr , lz , phi , theta)
Definition at line 154 of file SurfaceLocalToGlobalRoundtripTests.cpp.
View newest version in sPHENIX GitHub at line 154 of file SurfaceLocalToGlobalRoundtripTests.cpp
References Acts::Test::runTest().