Analysis Software: ActsGeometry Class Reference
ActsGeometry Class Reference
#include <coresoftware/blob/master/offline/packages/trackbase/ActsGeometry.h>
Public Member Functions
ActsGeometry ()=default
~ActsGeometry ()
void setGeometry (ActsTrackingGeometry &tGeometry)
void setSurfMaps (ActsSurfaceMaps &surfMaps)
ActsTrackingGeometry & geometry ()
ActsSurfaceMaps & maps ()
void set_drift_velocity (double vd)
double get_drift_velocity ()
Eigen::Matrix< float, 3, 1 > getGlobalPositionF (TrkrDefs::cluskey key, TrkrCluster *cluster)
Acts::Vector3 getGlobalPosition (TrkrDefs::cluskey key, TrkrCluster *cluster)
Acts::Vector3 getGlobalPositionTpc (TrkrDefs::cluskey key, TrkrCluster *cluster)
Surface get_tpc_surface_from_coords (TrkrDefs::hitsetkey hitsetkey, Acts::Vector3 world, TrkrDefs::subsurfkey &subsurfkey)
Acts::Transform3 makeAffineTransform (Acts::Vector3 rotation, Acts::Vector3 translation)
Acts::Vector2 getLocalCoords (TrkrDefs::cluskey key, TrkrCluster *cluster)
Private Attributes
ActsTrackingGeometry m_tGeometry
ActsSurfaceMaps m_surfMaps
double _drift_velocity = 8.0e-3
Detailed Description
Definition at line 10 of file ActsGeometry.h.
View newest version in sPHENIX GitHub at line 10 of file ActsGeometry.h
Constructor & Destructor Documentation
ActsGeometry::ActsGeometry () default
ActsGeometry::~ActsGeometry () inline
Definition at line 14 of file ActsGeometry.h.
View newest version in sPHENIX GitHub at line 14 of file ActsGeometry.h
Member Function Documentation
ActsTrackingGeometry& ActsGeometry::geometry () inline
Definition at line 22 of file ActsGeometry.h.
View newest version in sPHENIX GitHub at line 22 of file ActsGeometry.h
References m_tGeometry.
Referenced by PHActsTrackPropagator::addTrackState(), PHTpcResiduals::addTrackState(), ActsPropagator::checkLayer(), TpcClusterBuilder::cluster_hits(), AlignmentTransformation::createMap(), DSTEmulator::evaluate_tracks(), ActsEvaluator::evaluateTrackFit(), ActsAlignmentStates::fillAlignmentStateMap(), ActsEvaluator::fillFittedTrackParams(), ActsEvaluator::fillProtoTrack(), TrackResiduals::fillStatesWithLineFit(), HelicalFitter::get_helix_surface_intersection(), CylinderGeom_Mvtx::get_local_from_world_coords(), CylinderGeomMicromegas::get_local_from_world_coords(), CylinderGeomIntt::get_local_from_world_coords(), CylinderGeomMicromegas::get_local_from_world_vect(), ActsAlignmentStates::get_projectionXY(), HelicalFitter::get_projectionXY(), get_tpc_surface_from_coords(), CylinderGeom_Mvtx::get_world_from_local_coords(), CylinderGeomMicromegas::get_world_from_local_coords(), CylinderGeomIntt::get_world_from_local_coords(), CylinderGeomMicromegas::get_world_from_local_vect(), HelicalFitter::getGlobalDerivativesXY(), getGlobalPosition(), getGlobalPositionTpc(), MakeMilleFiles::getLocalVtxDerivativesXY(), MakeSourceLinks::getSourceLinks(), PHActsTrkFitter::getSurfaceVector(), PHActsGSF::InitRun(), PHCosmicsTrkFitter::InitRun(), PHActsTrkFitter::InitRun(), PHCosmicsTrkFitter::loopTracks(), PHActsTrkFitter::loopTracks(), PHActsTrackProjection::makeCaloSurfacePtrs(), ActsPropagator::makeFastPropagator(), ActsPropagator::makePropagator(), PHActsGSF::makeSeed(), PHActsKDTreeSeeding::makeSpacePoint(), PHActsSiliconSeeding::makeSpacePoint(), ActsPropagator::makeTrackParams(), PHTpcResiduals::makeTrackParams(), AlignmentTransformation::newMakeTransform(), ActsPropagator::printTrackParams(), PHTpcClusterMover::process_event(), PHActsGSF::process_event(), HelicalFitter::process_event(), PHTpcResiduals::processTrack(), KshortReconstruction::projectTrackToCylinder(), KshortReconstruction::projectTrackToPoint(), SecondaryVertexFinder::projectTrackToPoint(), ActsPropagator::propagateTrack(), ActsPropagator::propagateTrackFast(), MakeSourceLinks::resetTransientTransformMap(), PHActsVertexPropagator::updateSvtxTrack(), PHActsTrackProjection::updateSvtxTrack(), and ActsEvaluator::visitTrackStates().
double ActsGeometry::get_drift_velocity () inline
Definition at line 28 of file ActsGeometry.h.
View newest version in sPHENIX GitHub at line 28 of file ActsGeometry.h
References _drift_velocity.
Referenced by PHSiliconTpcTrackMatching::checkCrossingMatches(), TpcClusterBuilder::cluster_hits(), TrackResiduals::convertTimeToZ(), HelicalFitter::convertTimeToZ(), TrackResiduals::fillHitTree(), ActsEvaluator::fillProtoTrack(), PHCosmicsTrkFitter::fillVectors(), PHSiliconTpcTrackMatching::getBunchCrossing(), TpcClusterizer::process_event(), and TpcDirectLaserReconstruction::process_track().
Surface ActsGeometry::get_tpc_surface_from_coords (TrkrDefs::hitsetkey hitsetkey, Acts::Vector3 world, TrkrDefs::subsurfkey & subsurfkey)
Definition at line 103 of file ActsGeometry.cc.
View newest version in sPHENIX GitHub at line 103 of file ActsGeometry.cc
References geometry(), TrkrDefs::getLayer(), layer, ActsSurfaceMaps::m_tpcSurfaceMap, maps(), round(), ActsTrackingGeometry::tpcSurfStepPhi, and ActsTrackingGeometry::tpcSurfStepZ.
Referenced by TpcClusterBuilder::cluster_hits(), and PHTpcClusterMover::process_event().
Acts::Vector3 ActsGeometry::getGlobalPosition (TrkrDefs::cluskey key, TrkrCluster * cluster)
If silicon/TPOT, the transform is one-to-one since the surface is planar
Definition at line 26 of file ActsGeometry.cc.
View newest version in sPHENIX GitHub at line 26 of file ActsGeometry.cc
References Acts::UnitConstants::cm, geometry(), getGlobalPositionTpc(), TrkrCluster::getLocalX(), TrkrCluster::getLocalY(), ActsSurfaceMaps::getSurface(), TrkrDefs::getTrkrId(), maps(), writeMapConfig::surface, and TrkrDefs::tpcId.
Referenced by TrackFitUtils::addClusters(), TrackFitUtils::addClustersOnLine(), PHCosmicTrackMerger::addKeys(), MakeMilleFiles::addTrackToMilleFile(), InttVertexFinder::calculateZvertex(), TrackSeed_v1::circleFitByTaubin(), g4evalfn::clusloc_PHG4(), G4Eval::TrkrClusterComparer::clusloc_PHG4(), g4evalfn::clusloc_SVTX(), G4Eval::TrkrClusterComparer::clusloc_SVTX(), TrackEvaluation::create_cluster(), QAG4SimulationMvtx::evaluate_clusters(), QAG4SimulationIntt::evaluate_clusters(), QAG4SimulationMicromegas::evaluate_clusters(), QAG4SimulationTpc::evaluate_clusters(), ActsAlignmentStates::fillAlignmentStateMap(), TrackResiduals::fillClusterTree(), TrkrNtuplizer::fillOutputNtuples(), SvtxEvaluator::fillOutputNtuples(), ActsEvaluator::fillProtoTrack(), PHActsKDTreeSeeding::fillTrackSeedContainer(), PHCASeeding::FillTree(), PHCosmicsTrkFitter::fillVectors(), TpcSpaceChargeReconstruction::get_global_position(), TrackSeed_v1::get_phi(), TrackSeedTrackMapConverter::getCosmicCharge(), PHMicromegasTpcTrackMatching::getGlobalPosition(), DSTEmulator::getGlobalPosition(), PHTpcResiduals::getGlobalPosition(), PHSimpleKFProp::getGlobalPosition(), SvtxClusterEval::getGlobalPosition(), PHCASeeding::getGlobalPosition(), PHGenFitTrkFitter::getGlobalPosition(), getGlobalPositionF(), PHCosmicTrackMerger::getGlobalPositions(), PHSiliconTpcTrackMatching::getInttCrossings(), dNdEtaINTT::GetRecoClusterInfo(), MakeSourceLinks::getSourceLinks(), TrackFitUtils::getTrackletClusters(), TrackSeed_v1::lineFit(), TrackerEventDisplay::makeJsonFile(), PHActsSiliconSeeding::makeSvtxTracks(), PHActsKDTreeSeeding::matchInttClusters(), PHActsSiliconSeeding::matchInttClusters(), SvtxEvaluator::printOutputInfo(), PHSiliconHelicalPropagator::process_event(), PHCosmicSiliconPropagator::process_event(), TrackSeedTrackMapConverter::process_event(), QAG4SimulationDistortions::process_event(), PHCosmicSeeder::process_event(), PHTpcClusterMover::process_event(), PHMicromegasTpcTrackMatching::process_event(), and PHTpcDeltaZCorrection::process_track().
Eigen::Matrix< float, 3, 1 > ActsGeometry::getGlobalPositionF (TrkrDefs::cluskey key, TrkrCluster * cluster)
Definition at line 17 of file ActsGeometry.cc.
View newest version in sPHENIX GitHub at line 17 of file ActsGeometry.cc
References getGlobalPosition().
Acts::Vector3 ActsGeometry::getGlobalPositionTpc (TrkrDefs::cluskey key, TrkrCluster * cluster)
Definition at line 62 of file ActsGeometry.cc.
View newest version in sPHENIX GitHub at line 62 of file ActsGeometry.cc
References _drift_velocity, Acts::UnitConstants::cm, geometry(), TrkrCluster::getLocalX(), TrkrCluster::getLocalY(), TpcDefs::getSide(), ActsSurfaceMaps::getSurface(), TrkrDefs::getTrkrId(), maps(), writeMapConfig::surface, and TrkrDefs::tpcId.
Referenced by getGlobalPosition().
Acts::Vector2 ActsGeometry::getLocalCoords (TrkrDefs::cluskey key, TrkrCluster * cluster)
Definition at line 176 of file ActsGeometry.cc.
View newest version in sPHENIX GitHub at line 176 of file ActsGeometry.cc
References _drift_velocity, TrkrCluster::getLocalX(), TrkrCluster::getLocalY(), TpcDefs::getSide(), TrkrDefs::getTrkrId(), and TrkrDefs::tpcId.
Referenced by PHCosmicsTrkFitter::getCharge(), and MakeSourceLinks::getSourceLinks().
Acts::Transform3 ActsGeometry::makeAffineTransform (Acts::Vector3 rotation, Acts::Vector3 translation)
Definition at line 159 of file ActsGeometry.cc.
View newest version in sPHENIX GitHub at line 159 of file ActsGeometry.cc
References alpha, and translation().
Referenced by MakeSourceLinks::getSourceLinks().
ActsSurfaceMaps& ActsGeometry::maps () inline
Definition at line 24 of file ActsGeometry.h.
View newest version in sPHENIX GitHub at line 24 of file ActsGeometry.h
References m_surfMaps.
Referenced by MakeMilleFiles::addTrackToMilleFile(), AlignmentTransformation::createMap(), DSTEmulator::evaluate_tracks(), TrackResiduals::fillHitTree(), TrackResiduals::fillStatesWithLineFit(), CylinderGeomMicromegas::find_strip_from_local_coords(), PHTruthClustering::G4ClusterSize(), SvtxTruthEval::G4ClusterSize(), CylinderGeomMicromegas::get_local_coordinates(), CylinderGeomMicromegas::get_local_from_world_coords(), CylinderGeomMicromegas::get_local_from_world_vect(), CylinderGeomMicromegas::get_strip_count(), CylinderGeomMicromegas::get_strip_length(), get_tpc_surface_from_coords(), CylinderGeomMicromegas::get_world_from_local_coords(), CylinderGeomMicromegas::get_world_from_local_vect(), PHCosmicsTrkFitter::getCharge(), getGlobalPosition(), getGlobalPositionTpc(), MakeMilleFiles::getLocalVtxDerivativesXY(), PHActsKDTreeSeeding::getMvtxSpacePoints(), PHActsSiliconSeeding::getSiliconSpacePoints(), MakeSourceLinks::getSourceLinks(), ActsEvaluator::getSurface(), PHActsTrkFitter::getSurfaceVector(), HelicalFitter::getTrackletClusterList(), PHActsTrkFitter::loopTracks(), PHActsKDTreeSeeding::matchInttClusters(), PHActsSiliconSeeding::matchInttClusters(), PHG4MvtxHitReco::process_event(), HelicalFitter::process_event(), PHTpcResiduals::processTrack(), and PHGenFitTrkFitter::ReFitTrack().
void ActsGeometry::set_drift_velocity (double vd) inline
Definition at line 27 of file ActsGeometry.h.
View newest version in sPHENIX GitHub at line 27 of file ActsGeometry.h
References _drift_velocity.
Referenced by MakeActsGeometry::InitRun().
void ActsGeometry::setGeometry (ActsTrackingGeometry & tGeometry) inline
Definition at line 16 of file ActsGeometry.h.
View newest version in sPHENIX GitHub at line 16 of file ActsGeometry.h
References m_tGeometry, and Acts::tGeometry.
Referenced by MakeActsGeometry::InitRun().
void ActsGeometry::setSurfMaps (ActsSurfaceMaps & surfMaps) inline
Definition at line 19 of file ActsGeometry.h.
View newest version in sPHENIX GitHub at line 19 of file ActsGeometry.h
References m_surfMaps.
Referenced by MakeActsGeometry::InitRun().
Member Data Documentation
double ActsGeometry::_drift_velocity = 8.0e-3 private
Definition at line 55 of file ActsGeometry.h.
View newest version in sPHENIX GitHub at line 55 of file ActsGeometry.h
Referenced by get_drift_velocity(), getGlobalPositionTpc(), getLocalCoords(), and set_drift_velocity().
ActsSurfaceMaps ActsGeometry::m_surfMaps private
Definition at line 53 of file ActsGeometry.h.
View newest version in sPHENIX GitHub at line 53 of file ActsGeometry.h
Referenced by maps(), and setSurfMaps().
ActsTrackingGeometry ActsGeometry::m_tGeometry private
Definition at line 52 of file ActsGeometry.h.
View newest version in sPHENIX GitHub at line 52 of file ActsGeometry.h
Referenced by geometry(), and setGeometry().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/trackbase/ActsGeometry.h
coresoftware/blob/master/offline/packages/trackbase/ActsGeometry.cc