Analysis Software: TrackSeedContainer Class Reference
TrackSeedContainer Class Reference
#include <coresoftware/blob/master/offline/packages/trackbase_historic/TrackSeedContainer.h>
Public Types
typedef std::vector< TrackSeed * > Container
typedef std::vector< TrackSeed * >
::const_iterator ConstIter
typedef std::vector< TrackSeed * >
::iterator Iter
Public Member Functions
~TrackSeedContainer () override
void identify (std::ostream &os=std::cout) const override
int isValid () const override
isValid returns non zero if object contains vailid data
PHObject * CloneMe () const override
Virtual copy constructor.
virtual bool empty () const
virtual std::size_t size () const
virtual void clear ()
virtual const TrackSeed * get (const std::size_t) const
virtual TrackSeed * get (const std::size_t)
virtual TrackSeed * insert (const TrackSeed *)
virtual void erase (const std::size_t)
virtual std::size_t index (ConstIter) const
virtual std::size_t index (Iter) const
virtual ConstIter begin () const
virtual ConstIter find (const std::size_t key) const
virtual std::size_t find (const TrackSeed *) const
virtual ConstIter end () const
virtual Iter begin ()
virtual Iter find (const std::size_t key)
virtual std::size_t find (const TrackSeed *)
virtual Iter end ()
Public Member Functions inherited from PHObject
PHObject ()
ctor
~PHObject () override
dtor
virtual PHObject * clone () const final
PHObject * Clone (const char *newname="") const final
void Copy (TObject &object) const final
virtual void Reset ()
Clear Event.
virtual int Integrate () const
virtual int Integrate (PHObject *)
virtual void CopyFrom (const PHObject *obj)
Protected Member Functions
TrackSeedContainer ()
Private Member Functions
ClassDefOverride (TrackSeedContainer, 1)
Detailed Description
Definition at line 12 of file TrackSeedContainer.h.
View newest version in sPHENIX GitHub at line 12 of file TrackSeedContainer.h
Member Typedef Documentation
typedef std::vector<TrackSeed*>::const_iterator TrackSeedContainer::ConstIter
Definition at line 16 of file TrackSeedContainer.h.
View newest version in sPHENIX GitHub at line 16 of file TrackSeedContainer.h
typedef std::vector<TrackSeed*> TrackSeedContainer::Container
Definition at line 15 of file TrackSeedContainer.h.
View newest version in sPHENIX GitHub at line 15 of file TrackSeedContainer.h
typedef std::vector<TrackSeed*>::iterator TrackSeedContainer::Iter
Definition at line 17 of file TrackSeedContainer.h.
View newest version in sPHENIX GitHub at line 17 of file TrackSeedContainer.h
Constructor & Destructor Documentation
TrackSeedContainer::~TrackSeedContainer () inline override
Definition at line 19 of file TrackSeedContainer.h.
View newest version in sPHENIX GitHub at line 19 of file TrackSeedContainer.h
TrackSeedContainer::TrackSeedContainer () inline protected
Definition at line 53 of file TrackSeedContainer.h.
View newest version in sPHENIX GitHub at line 53 of file TrackSeedContainer.h
Member Function Documentation
TrackSeedContainer::ConstIter TrackSeedContainer::begin (void) const virtual
Reimplemented in TrackSeedContainer_v1.
Definition at line 5 of file TrackSeedContainer.cc.
View newest version in sPHENIX GitHub at line 5 of file TrackSeedContainer.cc
References container.
Referenced by PHCosmicsTrkFitter::loopTracks(), PHActsTrkFitter::loopTracks(), PHSiliconTruthTrackSeeding::Process(), PHCosmicSeedCombiner::process_event(), TrackSeedTrackMapConverter::process_event(), FilterEvents::process_event(), helixResiduals::process_event(), FilterEventsUpsilon::process_event(), PHTpcTrackSeedCircleFit::process_event(), PHCosmicTrackMerger::process_event(), PHGenFitTrkFitter::process_event(), and DumpTrackSeedContainer::process_Node().
TrackSeedContainer::Iter TrackSeedContainer::begin (void) virtual
Reimplemented in TrackSeedContainer_v1.
Definition at line 21 of file TrackSeedContainer.cc.
View newest version in sPHENIX GitHub at line 21 of file TrackSeedContainer.cc
References container.
TrackSeedContainer::ClassDefOverride (TrackSeedContainer , 1) private
virtual void TrackSeedContainer::clear () inline virtual
Reimplemented in TrackSeedContainer_v1.
Definition at line 30 of file TrackSeedContainer.h.
View newest version in sPHENIX GitHub at line 30 of file TrackSeedContainer.h
PHObject* TrackSeedContainer::CloneMe () const inline override virtual
Virtual copy constructor.
Reimplemented from PHObject.
Reimplemented in TrackSeedContainer_v1.
Definition at line 26 of file TrackSeedContainer.h.
View newest version in sPHENIX GitHub at line 26 of file TrackSeedContainer.h
virtual bool TrackSeedContainer::empty () const inline virtual
Reimplemented in TrackSeedContainer_v1.
Definition at line 28 of file TrackSeedContainer.h.
View newest version in sPHENIX GitHub at line 28 of file TrackSeedContainer.h
TrackSeedContainer::ConstIter TrackSeedContainer::end (void) const virtual
Reimplemented in TrackSeedContainer_v1.
Definition at line 15 of file TrackSeedContainer.cc.
View newest version in sPHENIX GitHub at line 15 of file TrackSeedContainer.cc
References container.
Referenced by PHCosmicsTrkFitter::loopTracks(), PHActsTrkFitter::loopTracks(), PHSiliconTruthTrackSeeding::Process(), PHCosmicSeedCombiner::process_event(), TrackSeedTrackMapConverter::process_event(), FilterEvents::process_event(), helixResiduals::process_event(), FilterEventsUpsilon::process_event(), PHTpcTrackSeedCircleFit::process_event(), PHCosmicTrackMerger::process_event(), PHGenFitTrkFitter::process_event(), and DumpTrackSeedContainer::process_Node().
TrackSeedContainer::Iter TrackSeedContainer::end (void) virtual
Reimplemented in TrackSeedContainer_v1.
Definition at line 31 of file TrackSeedContainer.cc.
View newest version in sPHENIX GitHub at line 31 of file TrackSeedContainer.cc
References container.
virtual void TrackSeedContainer::erase (const std::size_t) inline virtual
Reimplemented in TrackSeedContainer_v1.
Definition at line 35 of file TrackSeedContainer.h.
View newest version in sPHENIX GitHub at line 35 of file TrackSeedContainer.h
Referenced by PHCosmicSeedCombiner::process_event(), PHSiliconSeedMerger::process_event(), PHCosmicTrackMerger::process_event(), and PHGhostRejection::rejectGhostTracks().
TrackSeedContainer::ConstIter TrackSeedContainer::find (const std::size_t key) const virtual
Reimplemented in TrackSeedContainer_v1.
Definition at line 10 of file TrackSeedContainer.cc.
View newest version in sPHENIX GitHub at line 10 of file TrackSeedContainer.cc
References container.
Referenced by PHSiliconTpcTrackMatching::getInttCrossings(), PHCosmicsTrkFitter::loopTracks(), PHActsTrkFitter::loopTracks(), PHSiliconHelicalPropagator::process_event(), PHCosmicSiliconPropagator::process_event(), and PHTrackCleaner::process_event().
virtual std::size_t TrackSeedContainer::find (const TrackSeed *) const inline virtual
Reimplemented in TrackSeedContainer_v1.
Definition at line 44 of file TrackSeedContainer.h.
View newest version in sPHENIX GitHub at line 44 of file TrackSeedContainer.h
TrackSeedContainer::Iter TrackSeedContainer::find (const std::size_t key) virtual
Reimplemented in TrackSeedContainer_v1.
Definition at line 26 of file TrackSeedContainer.cc.
View newest version in sPHENIX GitHub at line 26 of file TrackSeedContainer.cc
References container.
virtual std::size_t TrackSeedContainer::find (const TrackSeed *) inline virtual
Reimplemented in TrackSeedContainer_v1.
Definition at line 49 of file TrackSeedContainer.h.
View newest version in sPHENIX GitHub at line 49 of file TrackSeedContainer.h
virtual const TrackSeed* TrackSeedContainer::get (const std::size_t) const inline virtual
Reimplemented in TrackSeedContainer_v1.
Definition at line 32 of file TrackSeedContainer.h.
View newest version in sPHENIX GitHub at line 32 of file TrackSeedContainer.h
Referenced by PHSiliconTpcTrackMatching::checkCrossingMatches(), TrkrNtuplizer::fillOutputNtuples(), ActsEvaluator::fillProtoTrack(), PHSiliconTpcTrackMatching::findCrossingGeometrically(), PHSiliconTpcTrackMatching::findEtaPhiMatches(), PHSiliconTpcTrackMatching::getBunchCrossing(), PHCosmicsTrkFitter::loopTracks(), PHActsTrkFitter::loopTracks(), PHTruthTrackSeeding::Process(), PHSiliconHelicalPropagator::process_event(), PHCosmicSiliconPropagator::process_event(), PHCosmicSeedCombiner::process_event(), PHSiliconSeedMerger::process_event(), TrackSeedTrackMapConverter::process_event(), helixResiduals::process_event(), FilterEvents::process_event(), FilterEventsUpsilon::process_event(), PHCosmicTrackMerger::process_event(), PHTruthSiliconAssociation::process_event(), PHSiliconTpcTrackMatching::process_event(), PHMicromegasTpcTrackMatching::process_event(), PHSimpleKFProp::process_event(), HelicalFitter::process_event(), PHGenFitTrkFitter::process_event(), PHTpcDeltaZCorrection::process_tracks(), and PHGhostRejection::rejectGhostTracks().
virtual TrackSeed* TrackSeedContainer::get (const std::size_t) inline virtual
Reimplemented in TrackSeedContainer_v1.
Definition at line 33 of file TrackSeedContainer.h.
View newest version in sPHENIX GitHub at line 33 of file TrackSeedContainer.h
void TrackSeedContainer::identify (std::ostream & os = std::cout) const inline override virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from PHObject.
Reimplemented in TrackSeedContainer_v1.
Definition at line 21 of file TrackSeedContainer.h.
View newest version in sPHENIX GitHub at line 21 of file TrackSeedContainer.h
References os.
Referenced by PHTrackSeeding::CreateNodes(), PHActsSiliconSeeding::makeSvtxTracks(), and PHSiliconTruthTrackSeeding::Process().
virtual std::size_t TrackSeedContainer::index (ConstIter) const inline virtual
Interface to return the index corresponding to the track id of the container
Reimplemented in TrackSeedContainer_v1.
Definition at line 39 of file TrackSeedContainer.h.
View newest version in sPHENIX GitHub at line 39 of file TrackSeedContainer.h
Referenced by PHCosmicSeedCombiner::process_event(), TrackSeedTrackMapConverter::process_event(), helixResiduals::process_event(), and PHCosmicTrackMerger::process_event().
virtual std::size_t TrackSeedContainer::index (Iter) const inline virtual
Reimplemented in TrackSeedContainer_v1.
Definition at line 40 of file TrackSeedContainer.h.
View newest version in sPHENIX GitHub at line 40 of file TrackSeedContainer.h
virtual TrackSeed* TrackSeedContainer::insert (const TrackSeed *) inline virtual
Reimplemented in TrackSeedContainer_v1.
Definition at line 34 of file TrackSeedContainer.h.
View newest version in sPHENIX GitHub at line 34 of file TrackSeedContainer.h
Referenced by PHTruthSiliconAssociation::buildTrackSeed(), PHTruthTrackSeeding::buildTrackSeed(), PHActsKDTreeSeeding::fillTrackSeedContainer(), PHActsSiliconSeeding::makeSvtxTracks(), TrackContainerCombiner::mergeSeeds(), PHSiliconTruthTrackSeeding::Process(), PHTruthTrackSeeding::Process(), PHSiliconHelicalPropagator::process_event(), PHCosmicSiliconPropagator::process_event(), FilterEvents::process_event(), FilterEventsUpsilon::process_event(), PHCosmicSeeder::process_event(), PHTruthSiliconAssociation::process_event(), PHSiliconTpcTrackMatching::process_event(), PHHybridSeeding::publishSeeds(), PHCASeeding::publishSeeds(), and PHSimpleKFProp::publishSeeds().
int TrackSeedContainer::isValid () const inline override virtual
isValid returns non zero if object contains vailid data
Reimplemented from PHObject.
Reimplemented in TrackSeedContainer_v1.
Definition at line 25 of file TrackSeedContainer.h.
View newest version in sPHENIX GitHub at line 25 of file TrackSeedContainer.h
virtual std::size_t TrackSeedContainer::size (void) const inline virtual
Reimplemented in TrackSeedContainer_v1.
Definition at line 29 of file TrackSeedContainer.h.
View newest version in sPHENIX GitHub at line 29 of file TrackSeedContainer.h
Referenced by PHTruthSiliconAssociation::buildTrackSeed(), PHTruthTrackSeeding::buildTrackSeed(), TrkrNtuplizer::fillOutputNtuples(), PHSiliconTpcTrackMatching::findEtaPhiMatches(), PHCosmicsTrkFitter::loopTracks(), PHActsTrkFitter::loopTracks(), PHActsSiliconSeeding::makeSvtxTracks(), PHSiliconTruthTrackSeeding::Process(), PHTruthTrackSeeding::Process(), PHSiliconHelicalPropagator::process_event(), TrackContainerCombiner::process_event(), PHCosmicSiliconPropagator::process_event(), PHSiliconSeedMerger::process_event(), TrackSeedTrackMapConverter::process_event(), FilterEvents::process_event(), FilterEventsUpsilon::process_event(), PHTpcTrackSeedCircleFit::process_event(), PHCosmicTrackMerger::process_event(), PHTruthSiliconAssociation::process_event(), PHSiliconTpcTrackMatching::process_event(), PHMicromegasTpcTrackMatching::process_event(), PHSimpleKFProp::process_event(), HelicalFitter::process_event(), DumpTrackSeedContainer::process_Node(), PHTpcDeltaZCorrection::process_tracks(), and PHGhostRejection::rejectGhostTracks().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/trackbase_historic/TrackSeedContainer.h
coresoftware/blob/master/offline/packages/trackbase_historic/TrackSeedContainer.cc