Analysis Software: RDBC/blob/master/macros/RDBCemp.C File Reference
RDBCemp.C File Reference
#include <TError.h>
#include <TString.h>
#include <RDBC/TSQLDriverManager.h>
#include <RDBC/TSQLConnection.h>
#include <RDBC/TSQLDatabaseMetaData.h>
#include <RDBC/TSQLResultSet.h>
#include <RDBC/TSQLResultSetMetaData.h>
#include <RDBC/TSQLPreparedStatement.h>
#include <RDBC/TSQLCallableStatement.h>
#include <RDBC/TSQLTypes.h>
#include <TROOT.h>
#include <TGraph.h>
#include <TCanvas.h>
#include <TH1.h>
#include <TText.h>
#include <TStyle.h>
#include <TInterpreter.h>
#include <stdlib.h>
Functions
void DrawGraph (TGraph *graph, TString *labels, const TString &xname, Float_t xmin, Float_t xmax, Float_t ymin, Float_t ymax)
Int_t RDBCemp (const Text_t *dsn, const Text_t *usr="scott", const Text_t *pwd="tiger")
void Catch (TSQLException *e)
Function Documentation
void Catch (TSQLException * e)
Definition at line 204 of file RDBCemp.C.
View newest version in sPHENIX GitHub at line 204 of file RDBCemp.C
References TSQLException::GetMessage(), printf(), and str.
void DrawGraph (TGraph * graph, TString * labels, const TString & xname, Float_t xmin, Float_t xmax, Float_t ymin, Float_t ymax)
Definition at line 56 of file RDBCemp.C.
View newest version in sPHENIX GitHub at line 56 of file RDBCemp.C
References Data, dist(), j, step, t, xmin, and xpos.
Referenced by RDBCemp().
Int_t RDBCemp (const Text_t * dsn, const Text_t * usr = "scott", const Text_t * pwd = "tiger")
Definition at line 97 of file RDBCemp.C.
View newest version in sPHENIX GitHub at line 97 of file RDBCemp.C
References Acts::PhysicalConstants::c, DrawGraph(), TSQLStatement::ExecuteQuery(), TSQLDriverManager::GetConnection(), TSQLResultSet::GetFloat(), TSQLResultSet::GetInt(), TSQLResultSet::GetRow(), TSQLResultSet::GetString(), gr, gSQLDriverManager, i, TSQLResultSet::Next(), printf(), TSQL::SetHandler(), str, xmax, xmin, ymax, and ymin.