Analysis Software: analysis/blob/master/EMCal-LEDs/macro/display.C File Reference
display.C File Reference
#include <calobase/TowerInfoDefs.h>
Functions
void display (const string &inputFile="output/test.root", const string &outputDir="output", const string &run="0", bool do_waveforms=false)
Function Documentation
void display (const string & inputFile = "output/test.root", const string & outputDir = "output", const string & run = "0", bool do_waveforms = false)
Definition at line 4 of file display.C.
View newest version in sPHENIX GitHub at line 4 of file display.C
References channel(), TowerInfoDefs::decode_emcal(), TowerInfoDefs::encode_emcal(), KF_timing::etabin, TowerInfoDefs::getCaloTowerEtaBin(), TowerInfoDefs::getCaloTowerPhiBin(), h1, h2, i, digitization_config::input, j, outputDir, physmon_track_finding_ttbar::pt, tline, and to_string().
Referenced by hcal::evLoop(), hcal::hcal(), and main().