Analysis Software: BbcOutV2 Class Reference
BbcOutV2 Class Reference
#include <coresoftware/blob/master/offline/packages/mbd/BbcOutV2.h>
Public Member Functions
BbcOutV2 ()
~BbcOutV2 () override
void Reset () override
Clear Event from memory.
void identify (std::ostream &os=std::cout) const override
int isValid () const override
isValid returns non zero if object contains vailid data
Float_t get_zvtx () const override
get ZVertex determined by Bbc
Float_t get_zvtxerr () const override
get Error on ZVertex determined by Bbc
Float_t get_t0 () const override
get T0 determined by Bbc
Float_t get_t0err () const override
get Error on T0 determined by Bbc
void set_t0 (const Float_t t0, const Float_t t0err=0) override
void set_zvtx (const Float_t vtx, const Float_t vtxerr=0) override
set vertex
void set_zvtxerr (const Float_t vtxerr) override
void set_arm (const int iarm, const Short_t npmt, const Float_t chargesum, const Float_t timing) override
virtual void set_clocks (const Int_t ievt, const UShort_t iclk, const UShort_t ifemclk) override
Short_t get_npmt (const int iarm) const override
Float_t get_q (const int iarm) const override
Float_t get_time (const int iarm) const override
virtual Int_t get_evt () const override
virtual UShort_t get_clock () const override
virtual UShort_t get_femclock () const override
Public Member Functions inherited from BbcOut
~BbcOut () override
virtual void set_t0zvtx (const Float_t t0, const Float_t t0err, const Float_t vtx, const Float_t vtxerr)
virtual void FillFromClass (const BbcOut &old)
Public Member Functions inherited from PHObject
PHObject ()
ctor
~PHObject () override
dtor
virtual PHObject * CloneMe () const
Virtual copy constructor.
virtual PHObject * clone () const final
PHObject * Clone (const char *newname="") const final
void Copy (TObject &object) const final
virtual int Integrate () const
virtual int Integrate (PHObject *)
virtual void CopyFrom (const PHObject *obj)
Private Attributes
Float_t bz {std::numeric_limits<Float_t>::quiet_NaN()}
Float_t bzerr {std::numeric_limits<Float_t>::quiet_NaN()}
Float_t bt0 {std::numeric_limits<Float_t>::quiet_NaN()}
Float_t bt0err {std::numeric_limits<Float_t>::quiet_NaN()}
Float_t bqs {0}
Float_t bqn {0}
Float_t bts {std::numeric_limits<Float_t>::quiet_NaN()}
Float_t btn {std::numeric_limits<Float_t>::quiet_NaN()}
Short_t bns {0}
Short_t bnn {0}
Int_t evt {-1}
UShort_t clk {0}
UShort_t femclk {0}
Detailed Description
Definition at line 14 of file BbcOutV2.h.
View newest version in sPHENIX GitHub at line 14 of file BbcOutV2.h
Constructor & Destructor Documentation
BbcOutV2::BbcOutV2 () default
BbcOutV2::~BbcOutV2 () override default
Member Function Documentation
UShort_t BbcOutV2::get_clock () const override virtual
get XMIT Clock Counter
Reimplemented from BbcOut.
Definition at line 126 of file BbcOutV2.cc.
View newest version in sPHENIX GitHub at line 126 of file BbcOutV2.cc
References clk.
Int_t BbcOutV2::get_evt () const override virtual
get Event Number
Reimplemented from BbcOut.
Definition at line 121 of file BbcOutV2.cc.
View newest version in sPHENIX GitHub at line 121 of file BbcOutV2.cc
References evt.
UShort_t BbcOutV2::get_femclock () const override virtual
get FEM Clock Counter
Reimplemented from BbcOut.
Definition at line 131 of file BbcOutV2.cc.
View newest version in sPHENIX GitHub at line 131 of file BbcOutV2.cc
References femclk.
Short_t BbcOutV2::get_npmt (const int iarm) const override virtual
get Number of PMT's fired in North/South Bbc
Parameters
iarm Arm, use Bbc::North and Bbc::South
Reimplemented from BbcOut.
Definition at line 105 of file BbcOutV2.cc.
View newest version in sPHENIX GitHub at line 105 of file BbcOutV2.cc
References bnn, and bns.
Float_t BbcOutV2::get_q (const int iarm) const override virtual
get Number of Charged Particles into North/South Bbc
Parameters
iarm Arm, use Bbc::North and Bbc::South
Reimplemented from BbcOut.
Definition at line 111 of file BbcOutV2.cc.
View newest version in sPHENIX GitHub at line 111 of file BbcOutV2.cc
References bqn, and bqs.
Float_t BbcOutV2::get_t0 () const inline override virtual
get T0 determined by Bbc
Reimplemented from BbcOut.
Definition at line 40 of file BbcOutV2.h.
View newest version in sPHENIX GitHub at line 40 of file BbcOutV2.h
References bt0.
Float_t BbcOutV2::get_t0err () const inline override virtual
get Error on T0 determined by Bbc
Reimplemented from BbcOut.
Definition at line 43 of file BbcOutV2.h.
View newest version in sPHENIX GitHub at line 43 of file BbcOutV2.h
References bt0err.
Float_t BbcOutV2::get_time (const int iarm) const override virtual
get Timing of North/South Bbc
Parameters
iarm Arm, use Bbc::North and Bbc::South
Reimplemented from BbcOut.
Definition at line 116 of file BbcOutV2.cc.
View newest version in sPHENIX GitHub at line 116 of file BbcOutV2.cc
References btn, and bts.
Float_t BbcOutV2::get_zvtx () const inline override virtual
get ZVertex determined by Bbc
Reimplemented from BbcOut.
Definition at line 34 of file BbcOutV2.h.
View newest version in sPHENIX GitHub at line 34 of file BbcOutV2.h
References bz.
Float_t BbcOutV2::get_zvtxerr () const inline override virtual
get Error on ZVertex determined by Bbc
Reimplemented from BbcOut.
Definition at line 37 of file BbcOutV2.h.
View newest version in sPHENIX GitHub at line 37 of file BbcOutV2.h
References bzerr.
void BbcOutV2::identify (std::ostream & os = std::cout) const override virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from BbcOut.
Definition at line 48 of file BbcOutV2.cc.
View newest version in sPHENIX GitHub at line 48 of file BbcOutV2.cc
References bt0, bt0err, bz, and bzerr.
int BbcOutV2::isValid () const override virtual
isValid returns non zero if object contains vailid data
Reimplemented from BbcOut.
Definition at line 33 of file BbcOutV2.cc.
View newest version in sPHENIX GitHub at line 33 of file BbcOutV2.cc
References bt0.
void BbcOutV2::Reset () override virtual
Clear Event from memory.
Reimplemented from BbcOut.
Definition at line 12 of file BbcOutV2.cc.
View newest version in sPHENIX GitHub at line 12 of file BbcOutV2.cc
References bnn, bns, bqn, bqs, bt0, bt0err, btn, bts, bz, bzerr, clk, evt, and femclk.
void BbcOutV2::set_arm (const int iarm, const Short_t npmt, const Float_t chargesum, const Float_t timing) override virtual
Add Bbc North/South data containing Number of pmt's, Energy and Timing
Parameters
npmt Number of PMT's fired
energy Energy in North/South
timing Timing of North/South
iarm Arm, use Bbc::North and Bbc::South
Reimplemented from BbcOut.
Definition at line 76 of file BbcOutV2.cc.
View newest version in sPHENIX GitHub at line 76 of file BbcOutV2.cc
References bnn, bns, bqn, bqs, btn, bts, and charge().
void BbcOutV2::set_clocks (const Int_t ievt, const UShort_t iclk, const UShort_t ifemclk) override virtual
Add Bbc data containing evt, clk, and femclk
Parameters
ievt Event number
iclk XMIT clock
ifemclk FEM clock
Reimplemented from BbcOut.
Definition at line 97 of file BbcOutV2.cc.
View newest version in sPHENIX GitHub at line 97 of file BbcOutV2.cc
References clk, evt, and femclk.
void BbcOutV2::set_t0 (const Float_t t0, const Float_t t0err = 0) override virtual
set T0 for Bbc
Parameters
t0 Bbc T0
t0err Bbc T0 error
Reimplemented from BbcOut.
Definition at line 56 of file BbcOutV2.cc.
View newest version in sPHENIX GitHub at line 56 of file BbcOutV2.cc
References bt0, and bt0err.
void BbcOutV2::set_zvtx (const Float_t vtx, const Float_t vtxerr = 0) override virtual
set vertex
Reimplemented from BbcOut.
Definition at line 63 of file BbcOutV2.cc.
View newest version in sPHENIX GitHub at line 63 of file BbcOutV2.cc
References bz, and bzerr.
void BbcOutV2::set_zvtxerr (const Float_t vtxerr) override virtual
set Vtx Error for Bbc
Parameters
vtxerr Bbc Vtx Error
Reimplemented from BbcOut.
Definition at line 70 of file BbcOutV2.cc.
View newest version in sPHENIX GitHub at line 70 of file BbcOutV2.cc
References bzerr.
Member Data Documentation
Short_t BbcOutV2::bnn {0} private
Definition at line 111 of file BbcOutV2.h.
View newest version in sPHENIX GitHub at line 111 of file BbcOutV2.h
Referenced by get_npmt(), Reset(), and set_arm().
Short_t BbcOutV2::bns {0} private
Definition at line 110 of file BbcOutV2.h.
View newest version in sPHENIX GitHub at line 110 of file BbcOutV2.h
Referenced by get_npmt(), Reset(), and set_arm().
Float_t BbcOutV2::bqn {0} private
Definition at line 107 of file BbcOutV2.h.
View newest version in sPHENIX GitHub at line 107 of file BbcOutV2.h
Referenced by get_q(), Reset(), and set_arm().
Float_t BbcOutV2::bqs {0} private
Definition at line 106 of file BbcOutV2.h.
View newest version in sPHENIX GitHub at line 106 of file BbcOutV2.h
Referenced by get_q(), Reset(), and set_arm().
Float_t BbcOutV2::bt0 {std::numeric_limits<Float_t>::quiet_NaN()} private
Definition at line 104 of file BbcOutV2.h.
View newest version in sPHENIX GitHub at line 104 of file BbcOutV2.h
Referenced by get_t0(), identify(), isValid(), Reset(), and set_t0().
Float_t BbcOutV2::bt0err {std::numeric_limits<Float_t>::quiet_NaN()} private
Definition at line 105 of file BbcOutV2.h.
View newest version in sPHENIX GitHub at line 105 of file BbcOutV2.h
Referenced by get_t0err(), identify(), Reset(), and set_t0().
Float_t BbcOutV2::btn {std::numeric_limits<Float_t>::quiet_NaN()} private
Definition at line 109 of file BbcOutV2.h.
View newest version in sPHENIX GitHub at line 109 of file BbcOutV2.h
Referenced by get_time(), Reset(), and set_arm().
Float_t BbcOutV2::bts {std::numeric_limits<Float_t>::quiet_NaN()} private
Definition at line 108 of file BbcOutV2.h.
View newest version in sPHENIX GitHub at line 108 of file BbcOutV2.h
Referenced by get_time(), Reset(), and set_arm().
Float_t BbcOutV2::bz {std::numeric_limits<Float_t>::quiet_NaN()} private
Definition at line 102 of file BbcOutV2.h.
View newest version in sPHENIX GitHub at line 102 of file BbcOutV2.h
Referenced by get_zvtx(), identify(), Reset(), and set_zvtx().
Float_t BbcOutV2::bzerr {std::numeric_limits<Float_t>::quiet_NaN()} private
Definition at line 103 of file BbcOutV2.h.
View newest version in sPHENIX GitHub at line 103 of file BbcOutV2.h
Referenced by get_zvtxerr(), identify(), Reset(), set_zvtx(), and set_zvtxerr().
UShort_t BbcOutV2::clk {0} private
Definition at line 113 of file BbcOutV2.h.
View newest version in sPHENIX GitHub at line 113 of file BbcOutV2.h
Referenced by get_clock(), Reset(), and set_clocks().
Int_t BbcOutV2::evt {-1} private
Definition at line 112 of file BbcOutV2.h.
View newest version in sPHENIX GitHub at line 112 of file BbcOutV2.h
Referenced by get_evt(), Reset(), and set_clocks().
UShort_t BbcOutV2::femclk {0} private
Definition at line 114 of file BbcOutV2.h.
View newest version in sPHENIX GitHub at line 114 of file BbcOutV2.h
Referenced by get_femclock(), Reset(), and set_clocks().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/mbd/BbcOutV2.h
coresoftware/blob/master/offline/packages/mbd/BbcOutV2.cc