Analysis Software: ActsExamples::SequenceElement Class Reference
ActsExamples::SequenceElement Class Reference abstract
#include <acts/blob/sPHENIX/Examples/Framework/include/ActsExamples/Framework/SequenceElement.hpp>
Public Member Functions
virtual ~SequenceElement ()=default
virtual std::string name () const =0
The algorithm name.
virtual ProcessCode initialize ()=0
Initialize the algorithm.
virtual ProcessCode finalize ()=0
Finalize the algorithm.
virtual ProcessCode internalExecute (const AlgorithmContext &context)=0
const std::vector< const
DataHandleBase * > & writeHandles () const
const std::vector< const
DataHandleBase * > & readHandles () const
Private Member Functions
void registerWriteHandle (const DataHandleBase &handle)
void registerReadHandle (const DataHandleBase &handle)
Private Attributes
std::vector< const
DataHandleBase * > m_writeHandles
std::vector< const
DataHandleBase * > m_readHandles
Friends
template<typename T >
class WriteDataHandle
template<typename T >
class ReadDataHandle
Detailed Description
Event processing interface.
Definition at line 24 of file SequenceElement.hpp.
View newest version in sPHENIX GitHub at line 24 of file SequenceElement.hpp
Constructor & Destructor Documentation
virtual ActsExamples::SequenceElement::~SequenceElement () virtual default
Member Function Documentation
virtual ProcessCode ActsExamples::SequenceElement::finalize () pure virtual
Finalize the algorithm.
Implemented in ActsExamples::RootMeasurementWriter, ActsExamples::TrackFindingAlgorithm, ActsExamples::TrackFindingAlgorithmExaTrkX, ActsExamples::VertexPerformanceWriter, ActsExamples::TrackFindingFromPrototrackAlgorithm, ActsExamples::RootTrajectoryStatesWriter, ActsExamples::CKFPerformanceWriter, ActsExamples::RootMaterialTrackWriter, ActsExamples::RootTrajectorySummaryWriter, ActsExamples::RootTrackParameterWriter, ActsExamples::JsonSurfacesWriter, ActsExamples::CsvTrackingGeometryWriter, ActsExamples::RootPlanarClusterWriter, ActsExamples::TrackFitterPerformanceWriter, ActsExamples::CsvMeasurementWriter, ActsExamples::CsvTrackParameterWriter, ActsExamples::RootNuclearInteractionParametersWriter, ActsExamples::SeedingPerformanceWriter, ActsExamples::WriterT< write_data_t >, ActsExamples::RootPropagationStepsWriter, ActsExamples::WriterT< GeometryIdMultiset< T > >, ActsExamples::WriterT< std::vector< PropagationSteps > >, ActsExamples::WriterT< ProtoTrackContainer >, ActsExamples::WriterT< SimSeedContainer >, ActsExamples::WriterT< SimHitContainer >, ActsExamples::WriterT< std::vector< HepMC3::GenEvent > >, ActsExamples::WriterT< std::vector< std::vector< step_t > > >, ActsExamples::WriterT< std::unordered_map< size_t, Acts::RecordedMaterialTrack > >, ActsExamples::WriterT< TrajectoriesContainer >, ActsExamples::WriterT< SimSpacePointContainer >, ActsExamples::WriterT< GeometryIdMultimap< T > >, ActsExamples::WriterT< ExtractedSimulationProcessContainer >, ActsExamples::WriterT< std::vector< Acts::Vertex< Acts::BoundTrackParameters > > >, ActsExamples::WriterT< GeometryIdMultimap< Acts::PlanarModuleCluster > >, ActsExamples::WriterT< SimParticleContainer >, ActsExamples::WriterT< ConstTrackContainer >, ActsExamples::WriterT< MeasurementContainer >, ActsExamples::IAlgorithm, ActsExamples::CsvSpacepointWriter, ActsExamples::RootParticleWriter, ActsExamples::RootSpacepointWriter, ActsExamples::ObjPropagationStepsWriter< step_t >, ActsExamples::RootSimHitWriter, ActsExamples::EDM4hepMultiTrajectoryWriter, ActsExamples::EDM4hepSimHitWriter, ActsExamples::TrackFinderPerformanceWriter, ActsExamples::CsvProtoTrackWriter, ActsExamples::EDM4hepMeasurementWriter, ActsExamples::IReader, ActsExamples::EDM4hepTrackWriter, ActsExamples::EDM4hepParticleWriter, and Acts::Test::DummySequenceElement.
virtual ProcessCode ActsExamples::SequenceElement::initialize () pure virtual
Initialize the algorithm.
Implemented in ActsExamples::Geant4SimulationBase, ActsExamples::IAlgorithm, ActsExamples::IReader, ActsExamples::IWriter, and Acts::Test::DummySequenceElement.
virtual ProcessCode ActsExamples::SequenceElement::internalExecute (const AlgorithmContext & context) pure virtual
Internal method to execute the algorithm for one event.
Note
Usually, you should not override this method
Implemented in ActsExamples::IAlgorithm, ActsExamples::IReader, ActsExamples::IWriter, and Acts::Test::DummySequenceElement.
Referenced by Acts::Python::addFramework().
virtual std::string ActsExamples::SequenceElement::name () const pure virtual
The algorithm name.
Implemented in ActsExamples::RootAthenaNTupleReader, ActsExamples::EventGenerator, ActsExamples::CsvMeasurementReader, ActsExamples::CsvPlanarClusterReader, ActsExamples::JsonSurfacesWriter, ActsExamples::CsvTrackingGeometryWriter, ActsExamples::RootMaterialTrackReader, ActsExamples::CsvTrackParameterWriter, ActsExamples::RootTrajectorySummaryReader, ActsExamples::CsvSpacePointReader, ActsExamples::RootParticleReader, ActsExamples::RootSimHitReader, ActsExamples::WriterT< write_data_t >, ActsExamples::EDM4hepSimHitReader, ActsExamples::WriterT< GeometryIdMultiset< T > >, ActsExamples::WriterT< std::vector< PropagationSteps > >, ActsExamples::WriterT< ProtoTrackContainer >, ActsExamples::WriterT< SimSeedContainer >, ActsExamples::WriterT< SimHitContainer >, ActsExamples::WriterT< std::vector< HepMC3::GenEvent > >, ActsExamples::WriterT< std::vector< std::vector< step_t > > >, ActsExamples::WriterT< std::unordered_map< size_t, Acts::RecordedMaterialTrack > >, ActsExamples::WriterT< TrajectoriesContainer >, ActsExamples::WriterT< SimSpacePointContainer >, ActsExamples::WriterT< GeometryIdMultimap< T > >, ActsExamples::WriterT< ExtractedSimulationProcessContainer >, ActsExamples::WriterT< std::vector< Acts::Vertex< Acts::BoundTrackParameters > > >, ActsExamples::WriterT< GeometryIdMultimap< Acts::PlanarModuleCluster > >, ActsExamples::WriterT< SimParticleContainer >, ActsExamples::WriterT< ConstTrackContainer >, ActsExamples::WriterT< MeasurementContainer >, ActsExamples::CsvTrackParameterReader, ActsExamples::EDM4hepMeasurementReader, ActsExamples::CsvSimHitReader, ActsExamples::CsvParticleReader, ActsExamples::HepMC3AsciiReader, ActsExamples::EDM4hepTrackReader, ActsExamples::EDM4hepParticleReader, ActsExamples::IAlgorithm, and Acts::Test::DummySequenceElement.
Referenced by Acts::Python::addFramework(), and ActsExamples::DataHandleBase::fullName().
const std::vector< const DataHandleBase * > & ActsExamples::SequenceElement::readHandles () const
Definition at line 26 of file SequenceElement.cpp.
View newest version in sPHENIX GitHub at line 26 of file SequenceElement.cpp
References m_readHandles.
void ActsExamples::SequenceElement::registerReadHandle (const DataHandleBase & handle) private
Definition at line 17 of file SequenceElement.cpp.
View newest version in sPHENIX GitHub at line 17 of file SequenceElement.cpp
References m_readHandles.
void ActsExamples::SequenceElement::registerWriteHandle (const DataHandleBase & handle) private
Definition at line 13 of file SequenceElement.cpp.
View newest version in sPHENIX GitHub at line 13 of file SequenceElement.cpp
References m_writeHandles.
const std::vector< const DataHandleBase * > & ActsExamples::SequenceElement::writeHandles () const
Definition at line 21 of file SequenceElement.cpp.
View newest version in sPHENIX GitHub at line 21 of file SequenceElement.cpp
References m_writeHandles.
Friends And Related Function Documentation
template<typename T > friend class ReadDataHandle friend
Definition at line 52 of file SequenceElement.hpp.
View newest version in sPHENIX GitHub at line 52 of file SequenceElement.hpp
template<typename T > friend class WriteDataHandle friend
Definition at line 49 of file SequenceElement.hpp.
View newest version in sPHENIX GitHub at line 49 of file SequenceElement.hpp
Member Data Documentation
std::vector<const DataHandleBase*> ActsExamples::SequenceElement::m_readHandles private
Definition at line 55 of file SequenceElement.hpp.
View newest version in sPHENIX GitHub at line 55 of file SequenceElement.hpp
Referenced by readHandles(), and registerReadHandle().
std::vector<const DataHandleBase*> ActsExamples::SequenceElement::m_writeHandles private
Definition at line 54 of file SequenceElement.hpp.
View newest version in sPHENIX GitHub at line 54 of file SequenceElement.hpp
Referenced by registerWriteHandle(), and writeHandles().
The documentation for this class was generated from the following files:
acts/blob/sPHENIX/Examples/Framework/include/ActsExamples/Framework/SequenceElement.hpp
acts/blob/sPHENIX/Examples/Framework/src/Framework/SequenceElement.cpp