Analysis Software: G4Example01Subsystem Class Reference
G4Example01Subsystem Class Reference
example Fun4All module
#include <g4exampledetector/blob/master/simple/source/G4Example01Subsystem.h>
Public Member Functions
G4Example01Subsystem (const std::string &name="Example01")
constructor
virtual ~G4Example01Subsystem ()
destructor
virtual int Init (PHCompositeNode *)
virtual int process_event (PHCompositeNode *)
event processing
virtual PHG4Detector * GetDetector () const
accessors (reimplemented)
virtual PHG4SteppingAction * GetSteppingAction () const
return pointer to this subsystem stepping action
virtual void Print (const std::string &what="ALL") const
Print info (from SubsysReco)
Public Member Functions inherited from PHG4Subsystem
PHG4Subsystem (const std::string &name="Generic Subsystem")
constructor
~PHG4Subsystem (void) override
destructor
virtual int process_after_geant (PHCompositeNode *)
event processing
virtual PHG4EventAction * GetEventAction (void) const
return pointer to this subsystem event action
virtual PHG4TrackingAction * GetTrackingAction (void) const
return pointer to this subsystem stepping action
virtual PHG4DisplayAction * GetDisplayAction () const
return pointer to this subsystem display setting
virtual PHG4StackingAction * GetStackingAction () const
void OverlapCheck (const bool chk=true)
bool CheckOverlap () const
void SetMotherSubsystem (PHG4Subsystem *subsys)
PHG4Subsystem * GetMotherSubsystem () const
void SetLogicalVolume (G4LogicalVolume *vol)
G4LogicalVolume * GetLogicalVolume () const
virtual bool CanBeMotherSubsystem () const
virtual void AddProcesses (G4ParticleDefinition *)
virtual void DefineMaterials ()
Public Member Functions inherited from SubsysReco
~SubsysReco () override
virtual int End (PHCompositeNode *)
Called at the end of all processing.
virtual int EndRun (const int)
Called at the end of each run.
virtual int InitRun (PHCompositeNode *)
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Private Attributes
G4Example01Detector * m_Detector
detector geometry
PHG4SteppingAction * m_SteppingAction
particle tracking "stepping" action
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = std::numeric_limits<int>::max() - 10
}
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Detailed Description
example Fun4All module
The detector is constructed and registered via G4Example01Detector
See Also
G4Example01Detector
G4Example01Subsystem
Definition at line 25 of file G4Example01Subsystem.h.
View newest version in sPHENIX GitHub at line 25 of file G4Example01Subsystem.h
Constructor & Destructor Documentation
G4Example01Subsystem::G4Example01Subsystem (const std::string & name = "Example01")
constructor
Definition at line 18 of file G4Example01Subsystem.cc.
View newest version in sPHENIX GitHub at line 18 of file G4Example01Subsystem.cc
virtual G4Example01Subsystem::~G4Example01Subsystem () inline virtual
destructor
Definition at line 32 of file G4Example01Subsystem.h.
View newest version in sPHENIX GitHub at line 32 of file G4Example01Subsystem.h
Member Function Documentation
PHG4Detector * G4Example01Subsystem::GetDetector (void) const virtual
accessors (reimplemented)
Reimplemented from PHG4Subsystem.
Definition at line 78 of file G4Example01Subsystem.cc.
View newest version in sPHENIX GitHub at line 78 of file G4Example01Subsystem.cc
References m_Detector.
virtual PHG4SteppingAction* G4Example01Subsystem::GetSteppingAction (void) const inline virtual
return pointer to this subsystem stepping action
Reimplemented from PHG4Subsystem.
Definition at line 51 of file G4Example01Subsystem.h.
View newest version in sPHENIX GitHub at line 51 of file G4Example01Subsystem.h
References m_SteppingAction.
int G4Example01Subsystem::Init (PHCompositeNode * topNode) virtual
creates the m_Detector object and place it on the node tree, under "DETECTORS" node (or whatever) reates the stepping action and place it on the node tree, under "ACTIONS" node creates relevant hit nodes that will be populated by the stepping action and stored in the output DST
Reimplemented from SubsysReco.
Definition at line 26 of file G4Example01Subsystem.cc.
View newest version in sPHENIX GitHub at line 26 of file G4Example01Subsystem.cc
References PHCompositeNode::addNode(), PHG4Subsystem::CheckOverlap(), PHNodeIterator::findFirst(), m_Detector, m_SteppingAction, Fun4AllBase::Name(), and PHG4Detector::OverlapCheck().
void G4Example01Subsystem::Print (const std::string & what = "ALL") const virtual
Print info (from SubsysReco)
Reimplemented from SubsysReco.
Definition at line 67 of file G4Example01Subsystem.cc.
View newest version in sPHENIX GitHub at line 67 of file G4Example01Subsystem.cc
References m_Detector, and G4Example01Detector::Print().
Referenced by Fun4All_G4_Example01(), Fun4All_G4_Geantino(), and Fun4All_G4_Write_Dst().
int G4Example01Subsystem::process_event (PHCompositeNode * topNode) virtual
event processing
get all relevant nodes from top nodes (namely hit list) and pass that to the stepping action
Reimplemented from SubsysReco.
Definition at line 56 of file G4Example01Subsystem.cc.
View newest version in sPHENIX GitHub at line 56 of file G4Example01Subsystem.cc
References m_SteppingAction, and PHG4SteppingAction::SetInterfacePointers().
Member Data Documentation
G4Example01Detector* G4Example01Subsystem::m_Detector private
detector geometry
defives from PHG4Detector
Definition at line 58 of file G4Example01Subsystem.h.
View newest version in sPHENIX GitHub at line 58 of file G4Example01Subsystem.h
Referenced by GetDetector(), Init(), and Print().
PHG4SteppingAction* G4Example01Subsystem::m_SteppingAction private
particle tracking "stepping" action
derives from PHG4SteppingActions
Definition at line 62 of file G4Example01Subsystem.h.
View newest version in sPHENIX GitHub at line 62 of file G4Example01Subsystem.h
Referenced by GetSteppingAction(), Init(), and process_event().
The documentation for this class was generated from the following files:
g4exampledetector/blob/master/simple/source/G4Example01Subsystem.h
g4exampledetector/blob/master/simple/source/G4Example01Subsystem.cc