Analysis Software: macros/blob/master/calibrations/calo/calib_nov23/pimacs/wholeIter_Pi0EtaByEta.C File Reference
wholeIter_Pi0EtaByEta.C File Reference
#include <fun4all/SubsysReco.h>
#include <fun4all/Fun4AllServer.h>
#include <fun4all/Fun4AllInputManager.h>
#include <fun4all/Fun4AllRunNodeInputManager.h>
#include <fun4allraw/Fun4AllPrdfInputManager.h>
#include <fun4all/Fun4AllDstInputManager.h>
#include <fun4all/Fun4AllDstOutputManager.h>
#include <cdbobjects/CDBTTree.h>
#include <ffamodules/CDBInterface.h>
#include <caloreco/CaloTowerCalib.h>
#include <caloreco/RawClusterBuilderTemplate.h>
#include <calib_emc_pi0/CaloCalibEmc_Pi0.h>
#include <phool/recoConsts.h>
#include <fstream>
#include <string>
#include <TBranch.h>
#include <TLeaf.h>
#include <TChain.h>
#include <TTree.h>
Functions
void make_csv (const char *inf, const char *outf)
TTree * GetTChainMacro (TString ifs)
void make_cemcCDBTree (const char *infct, const char *outfct)
void wholeIter_Pi0EtaByEta (int nevents=-1, const int iteration=1, const char *fname="pi0input.list", const char *inputCDBfnameIn="inputcdb1.root", const char *outfileloc1="./", const char *outfileloc2="./")
Function Documentation
TTree* GetTChainMacro (TString ifs = "")
void make_cemcCDBTree (const char * infct, const char * outfct)
Definition at line 271 of file wholeIter_Pi0EtaByEta.C.
View newest version in sPHENIX GitHub at line 271 of file wholeIter_Pi0EtaByEta.C
References CDBTTree::Commit(), file, perf_headwind::input_file, line, generate_particle_data_table::output_file, CDBTTree::SetFloatValue(), and CDBTTree::WriteCDBTTree().
Referenced by wholeIter_Pi0EtaByEta().
void make_csv (const char * inf, const char * outf)
Definition at line 211 of file wholeIter_Pi0EtaByEta.C.
View newest version in sPHENIX GitHub at line 211 of file wholeIter_Pi0EtaByEta.C
References KFPMath::b, file, perf_headwind::input_file, j, nbranches, generate_particle_data_table::output_file, and tree.
Referenced by wholeIter_Pi0EtaByEta().
void wholeIter_Pi0EtaByEta (int nevents = -1, const int iteration = 1, const char * fname = "pi0input.list", const char * inputCDBfnameIn = "inputcdb1.root", const char * outfileloc1 = "./", const char * outfileloc2 = "./")
Definition at line 46 of file wholeIter_Pi0EtaByEta.C.
View newest version in sPHENIX GitHub at line 46 of file wholeIter_Pi0EtaByEta.C
References Fun4AllInputManager::AddFile(), Fun4AllInputManager::AddListFile(), RawClusterBuilderTemplate::Detector(), CaloCalibEmc_Pi0::End(), Fun4AllServer::End(), Fun4AllInputManager::fileopen(), CaloCalibEmc_Pi0::Fit_Histos_Etas96(), INTTVtxZ::fname, CaloCalibEmc_Pi0::Get_Histos(), in, CaloCalibEmc_Pi0::InitRun(), recoConsts::instance(), Fun4AllServer::instance(), RawClusterBuilderTemplate::LoadProfile(), CaloCalibEmc_Pi0::Loop(), make_cemcCDBTree(), make_csv(), nevents(), Fun4AllServer::PrintTimer(), Fun4AllServer::registerInputManager(), Fun4AllServer::registerSubsystem(), Fun4AllServer::run(), CaloTowerCalib::set_directURL(), PHFlag::set_StringFlag(), RawClusterBuilderTemplate::set_threshold_energy(), PHFlag::set_uint64Flag(), RawClusterBuilderTemplate::set_UseTowerInfo(), CaloCalibEmc_Pi0::set_UseTowerInfo(), CaloTowerCalib::setFieldName(), CaloCalibEmc_Pi0::setInputClusterNodeName(), RawClusterBuilderTemplate::setInputTowerNodeName(), CaloCalibEmc_Pi0::setInputTowerNodeName(), RawClusterBuilderTemplate::setOutputClusterNodeName(), to_string(), and Fun4AllBase::Verbosity().