Analysis Software: Acts::Experimental::detail::CylindricalDetectorHelper Namespace Reference
Acts::Experimental::detail::CylindricalDetectorHelper Namespace Reference
Functions
DetectorComponent::PortalContainer connectInR (const GeometryContext &gctx, std::vector< std::shared_ptr< DetectorVolume >> &volumes, const std::vector< unsigned int > &selectedOnly={}, Acts::Logging::Level logLevel=Acts::Logging::INFO)
Connect detector volumes in R.
DetectorComponent::PortalContainer connectInZ (const GeometryContext &gctx, std::vector< std::shared_ptr< DetectorVolume >> &volumes, const std::vector< unsigned int > &selectedOnly={}, Acts::Logging::Level logLevel=Acts::Logging::INFO)
Connect detector volumes in Z.
DetectorComponent::PortalContainer connectInPhi (const GeometryContext &gctx, std::vector< std::shared_ptr< DetectorVolume >> &volumes, const std::vector< unsigned int > &selectedOnly={}, Acts::Logging::Level logLevel=Acts::Logging::INFO)
Connect detector volumes in phi.
DetectorComponent::PortalContainer wrapInZR (const GeometryContext &gctx, std::vector< std::shared_ptr< DetectorVolume >> &volumes, Acts::Logging::Level logLevel=Acts::Logging::INFO)
Wrap detector volumes in R,Z.
DetectorComponent::PortalContainer connectInR (const GeometryContext &gctx, const std::vector< DetectorComponent::PortalContainer > &containers, const std::vector< unsigned int > &selectedOnly={}, Acts::Logging::Level logLevel=Acts::Logging::INFO)
Connect containers in R.
DetectorComponent::PortalContainer connectInZ (const GeometryContext &gctx, const std::vector< DetectorComponent::PortalContainer > &containers, const std::vector< unsigned int > &selectedOnly={}, Acts::Logging::Level logLevel=Acts::Logging::INFO)
Connect containers in Z.
DetectorComponent::PortalContainer connectInPhi (const GeometryContext &gctx, const std::vector< DetectorComponent::PortalContainer > &containers, const std::vector< unsigned int > &selectedOnly={}, Acts::Logging::Level logLevel=Acts::Logging::INFO)
Connect containers in Phi.
DetectorComponent::PortalContainer wrapInZR (const GeometryContext &gctx, const std::vector< DetectorComponent::PortalContainer > &containers, Acts::Logging::Level logLevel=Acts::Logging::INFO)
Wrap container in R,Z - this uses the cutout cylinder bounds.
template<typename volume_container_t >
std::array< std::vector
< ActsScalar >, 3u > rzphiBoundaries (const GeometryContext &gctx, const volume_container_t &volumes, Acts::Logging::Level logLevel=Acts::Logging::INFO)
Helper method to extract r,z,phi boundaries for eventual grid volume search.
Function Documentation
DetectorComponent::PortalContainer Acts::Experimental::detail::CylindricalDetectorHelper::connectInPhi (const GeometryContext & gctx, std::vector< std::shared_ptr< DetectorVolume >> & volumes, const std::vector< unsigned int > & selectedOnly = {}, Acts::Logging::Level logLevel = Acts::Logging::INFO)
Connect detector volumes in phi.
Parameters
gctx The geometry context
volumes the volumes
selectedOnly switch only selected boundaries
logLevel is the screen logging level
Note
a fair amount of consistency checking is done, and exceptions are thrown if any of the tests fail
Returns
a proto container with the outside portals
Referenced by BOOST_AUTO_TEST_CASE().
DetectorComponent::PortalContainer Acts::Experimental::detail::CylindricalDetectorHelper::connectInPhi (const GeometryContext & gctx, const std::vector< DetectorComponent::PortalContainer > & containers, const std::vector< unsigned int > & selectedOnly = {}, Acts::Logging::Level logLevel = Acts::Logging::INFO)
Connect containers in Phi.
Parameters
gctx The geometry context
containers the containers
selectedOnly switch only selected boundaries
logLevel is the screen logging level
Note
not much checking is done anymore, as the DetectorComponent::PortalContainer are assumed to come properly formed from the prior methods
Returns
a proto container with the outside portals
DetectorComponent::PortalContainer Acts::Experimental::detail::CylindricalDetectorHelper::connectInR (const GeometryContext & gctx, std::vector< std::shared_ptr< DetectorVolume >> & volumes, const std::vector< unsigned int > & selectedOnly = {}, Acts::Logging::Level logLevel = Acts::Logging::INFO)
Connect detector volumes in R.
Parameters
gctx The geometry context
volumes the volumes
selectedOnly switch only selected boundaries
logLevel is the screen logging level
Note
a fair amount of consistency checking is done, and exceptions are thrown if any of the tests fail
Returns
a proto container with the outside portals
Referenced by BOOST_AUTO_TEST_CASE(), and connectInR().
Acts::Experimental::DetectorComponent::PortalContainer Acts::Experimental::detail::CylindricalDetectorHelper::connectInR (const GeometryContext & gctx, const std::vector< DetectorComponent::PortalContainer > & containers, const std::vector< unsigned int > & selectedOnly = {}, Acts::Logging::Level logLevel = Acts::Logging::INFO) noexcept
Connect containers in R.
Parameters
gctx The geometry context
containers the containers
selectedOnly switch only selected boundaries
logLevel is the screen logging level
Note
not much checking is done anymore, as the DetectorComponent::PortalContainer are assumed to come properly formed from the prior methods
Returns
a proto container with the outside portals
Definition at line 932 of file CylindricalDetectorHelper.cpp.
View newest version in sPHENIX GitHub at line 932 of file CylindricalDetectorHelper.cpp
References ACTS_DEBUG, ACTS_LOCAL_LOGGER, connectInR(), end, Acts::getDefaultLogger(), telescope_simulation::logLevel, physmon_simulation::s, and physmon_ckf_tracking::u.
DetectorComponent::PortalContainer Acts::Experimental::detail::CylindricalDetectorHelper::connectInZ (const GeometryContext & gctx, std::vector< std::shared_ptr< DetectorVolume >> & volumes, const std::vector< unsigned int > & selectedOnly = {}, Acts::Logging::Level logLevel = Acts::Logging::INFO)
Connect detector volumes in Z.
Parameters
gctx The geometry context
volumes the volumes
selectedOnly switch only selected boundaries
logLevel is the screen logging level
Note
a fair amount of consistency checking is done, and exceptions are thrown if any of the tests fail
Returns
a proto container with the outside portals
Referenced by BOOST_AUTO_TEST_CASE(), and connectInZ().
Acts::Experimental::DetectorComponent::PortalContainer Acts::Experimental::detail::CylindricalDetectorHelper::connectInZ (const GeometryContext & gctx, const std::vector< DetectorComponent::PortalContainer > & containers, const std::vector< unsigned int > & selectedOnly = {}, Acts::Logging::Level logLevel = Acts::Logging::INFO) noexcept
Connect containers in Z.
Parameters
gctx The geometry context
containers the containers
selectedOnly switch only selected boundaries
logLevel is the screen logging level
Note
not much checking is done anymore, as the DetectorComponent::PortalContainer are assumed to come properly formed from the prior methods
Returns
a proto container with the outside portals
Definition at line 993 of file CylindricalDetectorHelper.cpp.
View newest version in sPHENIX GitHub at line 993 of file CylindricalDetectorHelper.cpp
References ACTS_DEBUG, ACTS_LOCAL_LOGGER, ACTS_VERBOSE, connectInZ(), end, Acts::getDefaultLogger(), telescope_simulation::logLevel, physmon_simulation::s, and physmon_ckf_tracking::u.
template<typename volume_container_t > std::array<std::vector<ActsScalar>, 3u> Acts::Experimental::detail::CylindricalDetectorHelper::rzphiBoundaries (const GeometryContext & gctx, const volume_container_t & volumes, Acts::Logging::Level logLevel = Acts::Logging::INFO)
Helper method to extract r,z,phi boundaries for eventual grid volume search.
Template Parameters
volume_container_t the type of the container
Parameters
gctx the geometry context of the call
volumes the volumes at input
logLevel is the screen logging level
Returns
extracted boundary values
Definition at line 179 of file CylindricalDetectorHelper.hpp.
View newest version in sPHENIX GitHub at line 179 of file CylindricalDetectorHelper.hpp
References ACTS_DEBUG, ACTS_LOCAL_LOGGER, Acts::ACTS_VERBOSE(), parse_cmake_options::begin, Acts::getDefaultLogger(), telescope_simulation::logLevel, Acts::Test::phiMin, size, physmon_ckf_tracking::u, and testSigmaEff::v.
Referenced by BOOST_AUTO_TEST_CASE(), and Acts::Experimental::IndexedRootVolumeFinderBuilder::construct().
DetectorComponent::PortalContainer Acts::Experimental::detail::CylindricalDetectorHelper::wrapInZR (const GeometryContext & gctx, std::vector< std::shared_ptr< DetectorVolume >> & volumes, Acts::Logging::Level logLevel = Acts::Logging::INFO)
Wrap detector volumes in R,Z.
Parameters
gctx The geometry context
volumes the volumes
logLevel is the screen logging level
Note
a fair amount of consistency checking is done, and exceptions are thrown if any of the tests fail
Returns
a proto container with the outside portals
Referenced by BOOST_AUTO_TEST_CASE().
DetectorComponent::PortalContainer Acts::Experimental::detail::CylindricalDetectorHelper::wrapInZR (const GeometryContext & gctx, const std::vector< DetectorComponent::PortalContainer > & containers, Acts::Logging::Level logLevel = Acts::Logging::INFO)
Wrap container in R,Z - this uses the cutout cylinder bounds.
Parameters
gctx The geometry context
containers the containers, i.e. the inner volume and the wrapping container
logLevel is the screen logging level
Note
not much checking is done anymore, as the DetectorComponent::PortalContainer are assumed to come properly formed from the prior methods
Returns
a proto container with the outside portals