Analysis Software: PHG4ParticleGeneratorD0 Class Reference
PHG4ParticleGeneratorD0 Class Reference
#include <coresoftware/blob/master/simulation/g4simulation/g4main/PHG4ParticleGeneratorD0.h>
Public Member Functions
PHG4ParticleGeneratorD0 (const std::string &name="D0GEN")
~PHG4ParticleGeneratorD0 () override
int InitRun (PHCompositeNode *topNode) override
int process_event (PHCompositeNode *topNode) override
void set_eta_range (const double eta_min, const double eta_max)
void set_rapidity_range (const double y_min, const double y_max)
void set_mom_range (const double mom_min, const double mom_max)
void set_pt_range (const double pt_min, const double pt_max)
void set_vtx_zrange (const double zmin, const double zmax)
void set_mass (const double mass)
Public Member Functions inherited from PHG4ParticleGeneratorBase
~PHG4ParticleGeneratorBase () override
virtual void set_name (const std::string &particle="proton")
virtual void set_pid (const int pid)
virtual void set_mom (const double x, const double y, const double z)
virtual void set_vtx (const double x, const double y, const double z)
virtual void set_vtx_z (const double z)
virtual void set_t0 (const double t)
virtual double get_vtx_x () const
virtual double get_vtx_y () const
virtual double get_vtx_z () const
virtual double get_t0 () const
void Print (const std::string &what="ALL") const override
virtual void PrintParticles (const std::string &what="ALL") const
virtual void AddParticle (const std::string &particle, const double x, const double y, const double z)
virtual void AddParticle (const int pid, const double x, const double y, const double z)
virtual void Embed (const int i=1)
virtual int ReuseExistingVertex (PHCompositeNode *topNode)
int get_reuse_existing_vertex () const
void set_reuse_existing_vertex (const int i=1)
void set_seed (const unsigned int iseed)
unsigned int get_seed () const
Public Member Functions inherited from SubsysReco
~SubsysReco () override
virtual int End (PHCompositeNode *)
Called at the end of all processing.
virtual int EndRun (const int)
Called at the end of each run.
virtual int Init (PHCompositeNode *)
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Protected Attributes
double vtx_zmin = -10.
double vtx_zmax = 10.
double y_min = 0.
double y_max = 0.
double eta_min = -1.
double eta_max = 1.
double mom_min = 0.
double mom_max = 10.
double pt_min = 4.
double pt_max = 4.
double mass = 1.86486
double m1 = 0.493677
double m2 = 0.13957018
TF1 * fsin = nullptr
TF1 * frap = nullptr
TF1 * fpt = nullptr
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = std::numeric_limits<int>::max() - 10
}
Protected Member Functions inherited from PHG4ParticleGeneratorBase
PHG4ParticleGeneratorBase (const std::string &name="GENERATORBASE")
int get_pdgcode (const std::string &name) const
std::string get_pdgname (const int pdgcode) const
double get_mass (const int pdgcode) const
void CheckAndCreateParticleVector ()
void SetParticleId (PHG4Particle *particle, PHG4InEvent *ineve)
gsl_rng * RandomGenerator () const
int EmbedFlag () const
std::vector< PHG4Particle * >
::iterator particlelist_begin ()
std::vector< PHG4Particle * >
::iterator particlelist_end ()
void ResetParticleList ()
Detailed Description
Definition at line 13 of file PHG4ParticleGeneratorD0.h.
View newest version in sPHENIX GitHub at line 13 of file PHG4ParticleGeneratorD0.h
Constructor & Destructor Documentation
PHG4ParticleGeneratorD0::PHG4ParticleGeneratorD0 (const std::string & name = "D0GEN")
Definition at line 25 of file PHG4ParticleGeneratorD0.cc.
View newest version in sPHENIX GitHub at line 25 of file PHG4ParticleGeneratorD0.cc
PHG4ParticleGeneratorD0::~PHG4ParticleGeneratorD0 () inline override
Definition at line 17 of file PHG4ParticleGeneratorD0.h.
View newest version in sPHENIX GitHub at line 17 of file PHG4ParticleGeneratorD0.h
Member Function Documentation
int PHG4ParticleGeneratorD0::InitRun (PHCompositeNode *) override virtual
Called for first event when run number is known. Typically this is where you may want to fetch data from database, because you know the run number.
Reimplemented from PHG4ParticleGeneratorBase.
Definition at line 73 of file PHG4ParticleGeneratorD0.cc.
View newest version in sPHENIX GitHub at line 73 of file PHG4ParticleGeneratorD0.cc
References Acts::UnitConstants::e, fpt, frap, fsin, Fun4AllBase::Name(), pt_max, pt_min, y_max, and y_min.
int PHG4ParticleGeneratorD0::process_event (PHCompositeNode *) override virtual
Called for each event. This is where you do the real work.
Reimplemented from PHG4ParticleGeneratorBase.
Definition at line 96 of file PHG4ParticleGeneratorD0.cc.
View newest version in sPHENIX GitHub at line 96 of file PHG4ParticleGeneratorD0.cc
References PHG4InEvent::AddEmbeddedParticle(), PHG4InEvent::AddParticle(), PHG4ParticleGeneratorBase::AddParticle(), PHG4InEvent::AddVtx(), Acts::UnitConstants::e, PHG4ParticleGeneratorBase::EmbedFlag(), eta, fpt, frap, fsin, PHG4ParticleGeneratorBase::get_t0(), PHG4ParticleGeneratorBase::get_vtx_x(), PHG4ParticleGeneratorBase::get_vtx_y(), PHG4ParticleGeneratorBase::get_vtx_z(), PHG4InEvent::identify(), m1, m2, mass, particle, PHG4ParticleGeneratorBase::particlelist_begin(), PHG4ParticleGeneratorBase::particlelist_end(), ActsTests::PropagationDatasets::phi, physmon_track_finding_ttbar::pt, pt_max, pt_min, PHG4ParticleGeneratorBase::RandomGenerator(), PHG4ParticleGeneratorBase::ResetParticleList(), PHG4ParticleGeneratorBase::ReuseExistingVertex(), PHG4ParticleGeneratorBase::set_t0(), PHG4ParticleGeneratorBase::set_vtx(), PHG4ParticleGeneratorBase::set_vtx_z(), PHG4ParticleGeneratorBase::SetParticleId(), tau, v1, v2, Fun4AllBase::Verbosity(), vtx_zmax, vtx_zmin, y, y_max, and y_min.
void PHG4ParticleGeneratorD0::set_eta_range (const double eta_min, const double eta_max)
Definition at line 31 of file PHG4ParticleGeneratorD0.cc.
View newest version in sPHENIX GitHub at line 31 of file PHG4ParticleGeneratorD0.cc
References eta_max, eta_min, and Acts::UnitConstants::min.
void PHG4ParticleGeneratorD0::set_mass (const double mass)
Definition at line 67 of file PHG4ParticleGeneratorD0.cc.
View newest version in sPHENIX GitHub at line 67 of file PHG4ParticleGeneratorD0.cc
References mass.
void PHG4ParticleGeneratorD0::set_mom_range (const double mom_min, const double mom_max)
Definition at line 45 of file PHG4ParticleGeneratorD0.cc.
View newest version in sPHENIX GitHub at line 45 of file PHG4ParticleGeneratorD0.cc
References Acts::UnitConstants::min, mom_max, and mom_min.
void PHG4ParticleGeneratorD0::set_pt_range (const double pt_min, const double pt_max)
Definition at line 52 of file PHG4ParticleGeneratorD0.cc.
View newest version in sPHENIX GitHub at line 52 of file PHG4ParticleGeneratorD0.cc
References Acts::UnitConstants::min, pt_max, and pt_min.
void PHG4ParticleGeneratorD0::set_rapidity_range (const double y_min, const double y_max)
Definition at line 38 of file PHG4ParticleGeneratorD0.cc.
View newest version in sPHENIX GitHub at line 38 of file PHG4ParticleGeneratorD0.cc
References Acts::UnitConstants::min, y_max, and y_min.
void PHG4ParticleGeneratorD0::set_vtx_zrange (const double zmin, const double zmax)
Definition at line 59 of file PHG4ParticleGeneratorD0.cc.
View newest version in sPHENIX GitHub at line 59 of file PHG4ParticleGeneratorD0.cc
References vtx_zmax, and vtx_zmin.
Member Data Documentation
double PHG4ParticleGeneratorD0::eta_max = 1. protected
Definition at line 35 of file PHG4ParticleGeneratorD0.h.
View newest version in sPHENIX GitHub at line 35 of file PHG4ParticleGeneratorD0.h
Referenced by set_eta_range().
double PHG4ParticleGeneratorD0::eta_min = -1. protected
Definition at line 34 of file PHG4ParticleGeneratorD0.h.
View newest version in sPHENIX GitHub at line 34 of file PHG4ParticleGeneratorD0.h
Referenced by set_eta_range().
TF1* PHG4ParticleGeneratorD0::fpt = nullptr protected
Definition at line 46 of file PHG4ParticleGeneratorD0.h.
View newest version in sPHENIX GitHub at line 46 of file PHG4ParticleGeneratorD0.h
Referenced by InitRun(), and process_event().
TF1* PHG4ParticleGeneratorD0::frap = nullptr protected
Definition at line 45 of file PHG4ParticleGeneratorD0.h.
View newest version in sPHENIX GitHub at line 45 of file PHG4ParticleGeneratorD0.h
Referenced by InitRun(), and process_event().
TF1* PHG4ParticleGeneratorD0::fsin = nullptr protected
Definition at line 44 of file PHG4ParticleGeneratorD0.h.
View newest version in sPHENIX GitHub at line 44 of file PHG4ParticleGeneratorD0.h
Referenced by InitRun(), and process_event().
double PHG4ParticleGeneratorD0::m1 = 0.493677 protected
Definition at line 41 of file PHG4ParticleGeneratorD0.h.
View newest version in sPHENIX GitHub at line 41 of file PHG4ParticleGeneratorD0.h
Referenced by process_event().
double PHG4ParticleGeneratorD0::m2 = 0.13957018 protected
Definition at line 42 of file PHG4ParticleGeneratorD0.h.
View newest version in sPHENIX GitHub at line 42 of file PHG4ParticleGeneratorD0.h
Referenced by process_event().
double PHG4ParticleGeneratorD0::mass = 1.86486 protected
Definition at line 40 of file PHG4ParticleGeneratorD0.h.
View newest version in sPHENIX GitHub at line 40 of file PHG4ParticleGeneratorD0.h
Referenced by process_event(), and set_mass().
double PHG4ParticleGeneratorD0::mom_max = 10. protected
Definition at line 37 of file PHG4ParticleGeneratorD0.h.
View newest version in sPHENIX GitHub at line 37 of file PHG4ParticleGeneratorD0.h
Referenced by set_mom_range().
double PHG4ParticleGeneratorD0::mom_min = 0. protected
Definition at line 36 of file PHG4ParticleGeneratorD0.h.
View newest version in sPHENIX GitHub at line 36 of file PHG4ParticleGeneratorD0.h
Referenced by set_mom_range().
double PHG4ParticleGeneratorD0::pt_max = 4. protected
Definition at line 39 of file PHG4ParticleGeneratorD0.h.
View newest version in sPHENIX GitHub at line 39 of file PHG4ParticleGeneratorD0.h
Referenced by InitRun(), process_event(), and set_pt_range().
double PHG4ParticleGeneratorD0::pt_min = 4. protected
Definition at line 38 of file PHG4ParticleGeneratorD0.h.
View newest version in sPHENIX GitHub at line 38 of file PHG4ParticleGeneratorD0.h
Referenced by InitRun(), process_event(), and set_pt_range().
double PHG4ParticleGeneratorD0::vtx_zmax = 10. protected
Definition at line 31 of file PHG4ParticleGeneratorD0.h.
View newest version in sPHENIX GitHub at line 31 of file PHG4ParticleGeneratorD0.h
Referenced by process_event(), and set_vtx_zrange().
double PHG4ParticleGeneratorD0::vtx_zmin = -10. protected
Definition at line 30 of file PHG4ParticleGeneratorD0.h.
View newest version in sPHENIX GitHub at line 30 of file PHG4ParticleGeneratorD0.h
Referenced by process_event(), and set_vtx_zrange().
double PHG4ParticleGeneratorD0::y_max = 0. protected
Definition at line 33 of file PHG4ParticleGeneratorD0.h.
View newest version in sPHENIX GitHub at line 33 of file PHG4ParticleGeneratorD0.h
Referenced by InitRun(), process_event(), and set_rapidity_range().
double PHG4ParticleGeneratorD0::y_min = 0. protected
Definition at line 32 of file PHG4ParticleGeneratorD0.h.
View newest version in sPHENIX GitHub at line 32 of file PHG4ParticleGeneratorD0.h
Referenced by InitRun(), process_event(), and set_rapidity_range().
The documentation for this class was generated from the following files:
coresoftware/blob/master/simulation/g4simulation/g4main/PHG4ParticleGeneratorD0.h
coresoftware/blob/master/simulation/g4simulation/g4main/PHG4ParticleGeneratorD0.cc