Analysis Software: MvtxEventInfov1 Class Reference
MvtxEventInfov1 Class Reference
#include <coresoftware/blob/master/offline/packages/trackbase/MvtxEventInfov1.h>
Public Member Functions
MvtxEventInfov1 ()=default
virtual ~MvtxEventInfov1 ()=default
dtor
PHObject * CloneMe () const override
Virtual copy constructor.
void Reset () override
Clear Event.
void identify (std::ostream &os=std::cout) const override
int isValid () const override
isValid returns non zero if object contains valid data
void set_number_HB (const int) override
int get_number_HB () const override
void set_strobe_BCO_L1_BCO (const uint64_t strobe_BCO, const uint64_t L1_BCO) override
unsigned int get_number_strobes () const override
unsigned int get_number_L1s () const override
std::set< uint64_t > get_strobe_BCOs () const override
std::set< uint64_t > get_L1_BCOs () const override
std::set< uint64_t > get_strobe_BCO_from_L1_BCO (const uint64_t ival) const override
std::set< uint64_t > get_L1_BCO_from_strobe_BCO (const uint64_t ival) const override
Public Member Functions inherited from MvtxEventInfo
MvtxEventInfo ()=default
virtual ~MvtxEventInfo ()=default
dtor
void set_floatval (const std::string &, const float)
float get_floatval (const std::string &) const
void set_intval (const std::string &, const int32_t)
int get_intval (const std::string &) const
void set_int64val (const std::string &, const int64_t)
int get_int64val (const std::string &) const
void set_uintval (const std::string &, const uint32_t)
int get_uintval (const std::string &) const
void set_uint64val (const std::string &, const uint64_t)
int get_uint64val (const std::string &) const
void set_stringval (const std::string &, const std::string &)
std::string get_stringval (const std::string &) const
virtual void set_strobe_BCO (const uint64_t)
Public Member Functions inherited from PHObject
PHObject ()
ctor
~PHObject () override
dtor
virtual PHObject * clone () const final
PHObject * Clone (const char *newname="") const final
void Copy (TObject &object) const final
virtual int Integrate () const
virtual int Integrate (PHObject *)
virtual void CopyFrom (const PHObject *obj)
Protected Attributes
std::set< strobe_L1_pair > m_strobe_BCO_L1_BCO
std::string m_number_L1_name = "Number L1"
std::string m_number_HB_name = "Number HB"
Protected Attributes inherited from MvtxEventInfo
std::map< std::string, int32_t > m_IntEventProperties
std::map< std::string, int64_t > m_Int64EventProperties
std::map< std::string, uint32_t > m_UintEventProperties
std::map< std::string, uint64_t > m_Uint64EventProperties
std::map< std::string, float > m_FloatEventProperties
std::map< std::string,
std::string > m_StringEventProperties
Private Member Functions
void warning (const std::string &func) const
Private Attributes
int m_number_HB = -1
Detailed Description
Definition at line 22 of file MvtxEventInfov1.h.
View newest version in sPHENIX GitHub at line 22 of file MvtxEventInfov1.h
Constructor & Destructor Documentation
MvtxEventInfov1::MvtxEventInfov1 () default
virtual MvtxEventInfov1::~MvtxEventInfov1 () virtual default
dtor
Member Function Documentation
PHObject * MvtxEventInfov1::CloneMe () const override virtual
Virtual copy constructor.
Reimplemented from MvtxEventInfo.
Definition at line 5 of file MvtxEventInfov1.cc.
View newest version in sPHENIX GitHub at line 5 of file MvtxEventInfov1.cc
References PHWHERE.
std::set< uint64_t > MvtxEventInfov1::get_L1_BCO_from_strobe_BCO (const uint64_t ival) const override virtual
Reimplemented from MvtxEventInfo.
Definition at line 174 of file MvtxEventInfov1.cc.
View newest version in sPHENIX GitHub at line 174 of file MvtxEventInfov1.cc
References m_strobe_BCO_L1_BCO.
Referenced by identify().
std::set< uint64_t > MvtxEventInfov1::get_L1_BCOs () const override virtual
Reimplemented from MvtxEventInfo.
Definition at line 145 of file MvtxEventInfov1.cc.
View newest version in sPHENIX GitHub at line 145 of file MvtxEventInfov1.cc
References m_strobe_BCO_L1_BCO.
int MvtxEventInfov1::get_number_HB () const override virtual
Reimplemented from MvtxEventInfo.
Definition at line 95 of file MvtxEventInfov1.cc.
View newest version in sPHENIX GitHub at line 95 of file MvtxEventInfov1.cc
References m_number_HB.
Referenced by identify().
unsigned int MvtxEventInfov1::get_number_L1s () const override virtual
Reimplemented from MvtxEventInfo.
Definition at line 119 of file MvtxEventInfov1.cc.
View newest version in sPHENIX GitHub at line 119 of file MvtxEventInfov1.cc
References m_strobe_BCO_L1_BCO.
Referenced by identify().
unsigned int MvtxEventInfov1::get_number_strobes () const override virtual
Reimplemented from MvtxEventInfo.
Definition at line 106 of file MvtxEventInfov1.cc.
View newest version in sPHENIX GitHub at line 106 of file MvtxEventInfov1.cc
References m_strobe_BCO_L1_BCO.
std::set< uint64_t > MvtxEventInfov1::get_strobe_BCO_from_L1_BCO (const uint64_t ival) const override virtual
Reimplemented from MvtxEventInfo.
Definition at line 158 of file MvtxEventInfov1.cc.
View newest version in sPHENIX GitHub at line 158 of file MvtxEventInfov1.cc
References m_strobe_BCO_L1_BCO.
std::set< uint64_t > MvtxEventInfov1::get_strobe_BCOs () const override virtual
Reimplemented from MvtxEventInfo.
Definition at line 132 of file MvtxEventInfov1.cc.
View newest version in sPHENIX GitHub at line 132 of file MvtxEventInfov1.cc
References m_strobe_BCO_L1_BCO.
Referenced by identify().
void MvtxEventInfov1::identify (std::ostream & os = std::cout) const override virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from MvtxEventInfo.
Definition at line 25 of file MvtxEventInfov1.cc.
View newest version in sPHENIX GitHub at line 25 of file MvtxEventInfov1.cc
References get_L1_BCO_from_strobe_BCO(), get_number_HB(), get_number_L1s(), get_strobe_BCOs(), MvtxEventInfo::m_FloatEventProperties, MvtxEventInfo::m_Int64EventProperties, MvtxEventInfo::m_IntEventProperties, m_number_HB_name, m_number_L1_name, MvtxEventInfo::m_StringEventProperties, MvtxEventInfo::m_Uint64EventProperties, and MvtxEventInfo::m_UintEventProperties.
int MvtxEventInfov1::isValid () const override virtual
isValid returns non zero if object contains valid data
Reimplemented from MvtxEventInfo.
Definition at line 84 of file MvtxEventInfov1.cc.
View newest version in sPHENIX GitHub at line 84 of file MvtxEventInfov1.cc
References PHWHERE.
void MvtxEventInfov1::Reset () override virtual
Clear Event.
Reimplemented from MvtxEventInfo.
Definition at line 11 of file MvtxEventInfov1.cc.
View newest version in sPHENIX GitHub at line 11 of file MvtxEventInfov1.cc
References MvtxEventInfo::m_FloatEventProperties, MvtxEventInfo::m_Int64EventProperties, MvtxEventInfo::m_IntEventProperties, MvtxEventInfo::m_StringEventProperties, m_strobe_BCO_L1_BCO, MvtxEventInfo::m_Uint64EventProperties, and MvtxEventInfo::m_UintEventProperties.
void MvtxEventInfov1::set_number_HB (const int ival) override virtual
Reimplemented from MvtxEventInfo.
Definition at line 90 of file MvtxEventInfov1.cc.
View newest version in sPHENIX GitHub at line 90 of file MvtxEventInfov1.cc
References m_number_HB.
void MvtxEventInfov1::set_strobe_BCO_L1_BCO (const uint64_t strobe_BCO, const uint64_t L1_BCO) override virtual
Reimplemented from MvtxEventInfo.
Definition at line 100 of file MvtxEventInfov1.cc.
View newest version in sPHENIX GitHub at line 100 of file MvtxEventInfov1.cc
References m_strobe_BCO_L1_BCO.
void MvtxEventInfov1::warning (const std::string & func) const private
Member Data Documentation
int MvtxEventInfov1::m_number_HB = -1 private
Definition at line 66 of file MvtxEventInfov1.h.
View newest version in sPHENIX GitHub at line 66 of file MvtxEventInfov1.h
Referenced by get_number_HB(), and set_number_HB().
std::string MvtxEventInfov1::m_number_HB_name = "Number HB" protected
Definition at line 61 of file MvtxEventInfov1.h.
View newest version in sPHENIX GitHub at line 61 of file MvtxEventInfov1.h
Referenced by identify().
std::string MvtxEventInfov1::m_number_L1_name = "Number L1" protected
Definition at line 60 of file MvtxEventInfov1.h.
View newest version in sPHENIX GitHub at line 60 of file MvtxEventInfov1.h
Referenced by identify().
std::set<strobe_L1_pair> MvtxEventInfov1::m_strobe_BCO_L1_BCO protected
Definition at line 58 of file MvtxEventInfov1.h.
View newest version in sPHENIX GitHub at line 58 of file MvtxEventInfov1.h
Referenced by get_L1_BCO_from_strobe_BCO(), get_L1_BCOs(), get_number_L1s(), get_number_strobes(), get_strobe_BCO_from_L1_BCO(), get_strobe_BCOs(), Reset(), and set_strobe_BCO_L1_BCO().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/trackbase/MvtxEventInfov1.h
coresoftware/blob/master/offline/packages/trackbase/MvtxEventInfov1.cc