Analysis Software: PHG4VertexSelection Class Reference
PHG4VertexSelection Class Reference
#include <coresoftware/blob/master/simulation/g4simulation/g4main/PHG4VertexSelection.h>
Public Member Functions
PHG4VertexSelection (const std::string &name="PHG4VertexSelection")
int InitRun (PHCompositeNode *) override
run initialization
int process_event (PHCompositeNode *topNode) override
event processing
void SetDefaultParameters () override
parameters
Public Member Functions inherited from SubsysReco
~SubsysReco () override
virtual int End (PHCompositeNode *)
Called at the end of all processing.
virtual int EndRun (const int)
Called at the end of each run.
virtual int Init (PHCompositeNode *)
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
void Print (const std::string &="ALL") const override
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Public Member Functions inherited from PHParameterInterface
PHParameterInterface (const std::string &name)
PHParameterInterface (const PHParameterInterface &)=delete
PHParameterInterface & operator= (PHParameterInterface const &)=delete
virtual ~PHParameterInterface ()
void set_paramname (const std::string &name)
void set_double_param (const std::string &name, const double dval)
double get_double_param (const std::string &name) const
void set_int_param (const std::string &name, const int ival)
int get_int_param (const std::string &name) const
void set_string_param (const std::string &name, const std::string &sval)
std::string get_string_param (const std::string &name) const
void UpdateParametersWithMacro ()
void SaveToNodeTree (PHCompositeNode *runNode, const std::string &nodename)
void PutOnParNode (PHCompositeNode *parNode, const std::string &nodename)
void Print () const
Private Attributes
double m_vertex_zcut = 10
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = std::numeric_limits<int>::max() - 10
}
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Protected Member Functions inherited from PHParameterInterface
void set_default_double_param (const std::string &name, const double dval)
void set_default_int_param (const std::string &name, const int ival)
void set_default_string_param (const std::string &name, const std::string &sval)
void InitializeParameters ()
Detailed Description
Definition at line 19 of file PHG4VertexSelection.h.
View newest version in sPHENIX GitHub at line 19 of file PHG4VertexSelection.h
Constructor & Destructor Documentation
PHG4VertexSelection::PHG4VertexSelection (const std::string & name = "PHG4VertexSelection")
Definition at line 20 of file PHG4VertexSelection.cc.
View newest version in sPHENIX GitHub at line 20 of file PHG4VertexSelection.cc
References PHParameterInterface::InitializeParameters().
Member Function Documentation
int PHG4VertexSelection::InitRun (PHCompositeNode *) override virtual
run initialization
Reimplemented from SubsysReco.
Definition at line 28 of file PHG4VertexSelection.cc.
View newest version in sPHENIX GitHub at line 28 of file PHG4VertexSelection.cc
References Fun4AllReturnCodes::EVENT_OK, PHParameterInterface::get_double_param(), m_vertex_zcut, and PHParameterInterface::UpdateParametersWithMacro().
int PHG4VertexSelection::process_event (PHCompositeNode * topNode) override virtual
event processing
Reimplemented from SubsysReco.
Definition at line 45 of file PHG4VertexSelection.cc.
View newest version in sPHENIX GitHub at line 45 of file PHG4VertexSelection.cc
References Fun4AllReturnCodes::DISCARDEVENT, Fun4AllReturnCodes::EVENT_OK, and m_vertex_zcut.
void PHG4VertexSelection::SetDefaultParameters () override virtual
parameters
Implements PHParameterInterface.
Definition at line 60 of file PHG4VertexSelection.cc.
View newest version in sPHENIX GitHub at line 60 of file PHG4VertexSelection.cc
References PHParameterInterface::set_default_double_param().
Member Data Documentation
double PHG4VertexSelection::m_vertex_zcut = 10 private
Definition at line 35 of file PHG4VertexSelection.h.
View newest version in sPHENIX GitHub at line 35 of file PHG4VertexSelection.h
Referenced by InitRun(), and process_event().
The documentation for this class was generated from the following files:
coresoftware/blob/master/simulation/g4simulation/g4main/PHG4VertexSelection.h
coresoftware/blob/master/simulation/g4simulation/g4main/PHG4VertexSelection.cc