Analysis Software: analysis/blob/master/JS-Jet/HCalJetPhiShift/offline/ExploreTTrees.C File Reference
ExploreTTrees.C File Reference
#include <iostream>
#include <string>
#include <vector>
#include <TFile.h>
#include <TTree.h>
#include <TChain.h>
Functions
double delta_phi (double phi1, double phi2)
double dR (double phi1, double phi2, double eta1, double eta2)
double phi_in_range (double phi)
bool tower_in_3x3 (float calo_eta, float calo_phi, float eta, float phi)
void ExploreTTrees ()
Variables
Int_t event
Float_t eta
Float_t phi
Float_t e
Float_t pt
Float_t vx
Float_t vy
Float_t vz
vector< int > id
int nTow_in
vector< float > eta_in
vector< float > phi_in
vector< float > e_in
vector< int > ieta_in
vector< int > iphi_in
int nTow_out
vector< float > eta_out
vector< float > phi_out
vector< float > e_out
vector< int > ieta_out
vector< int > iphi_out
int nTow_emc
vector< float > eta_emc
vector< float > phi_emc
vector< float > e_emc
vector< int > ieta_emc
vector< int > iphi_emc
TTree * fChain
Int_t fCurrent
pointer to the analyzed TTree or TChain
const int ncal = 3
current Tree number in a TChain
string cal_name [] = { "iHCal", "oHCal", "EMCal" }
string cal_tag [] = { "_in", "_out", "_emc" }
TString inFileName = "HCalJetPhiShift_10k.root"
int n_pt_bins [ncal] = {80,100,100}
double pt_bin_lo [ncal] = {0.,0.,0.}
double pt_bin_hi [ncal] = {4.,50.,20.}
double eta_max [ncal] = {1.1,1.1,1.152}
int n_eta_bins [ncal] = {24,24,96}
int n_phi_bins [ncal] = {64,64,256}
int * nTowers [ncal] = {&nTow_in, &nTow_out, &nTow_emc}
vector< float > * calo_eta [ncal] = {&eta_in, &eta_out, &eta_emc}
vector< float > * calo_phi [ncal] = {&phi_in, &phi_out, &phi_emc}
vector< float > * calo_e [ncal] = {&e_in, &e_out, &e_emc}
vector< int > * calo_ieta [ncal] = {&ieta_in, &ieta_out, &ieta_emc}
vector< int > * calo_iphi [ncal] = {&iphi_in, &iphi_out, &iphi_emc}
TH1D * hGeantPhi = new TH1D("hGeantPhi",";truth #phi",64,-M_PI,M_PI)
TH2D * hEMCal3x3 = new TH2D("hEMCal3x3","pion p_{T};E_{EMCal}^{3x3} about max-E tower [GeV]",30,0.,30.,120,0.,60.)
TH2D * hEMCal3x3_FINE = new TH2D("hEMCal3x3_FINE","pion p_{T};E_{EMCal}^{3x3} about max-E tower [GeV]",30,0.,30.,200.,0.,2.)
TH3D * hE_inner_vs_outer = new TH3D("hE_inner_vs_outer",";pion p_{T};total E deposited in iHCal;total E deposited in oHCal",60,0.,30.,100, 0., 10.,120,0.,60.)
TH3D * hDeltaPhi_fraction_HcalOverAll = new TH3D("hDeltaPhi_fraction_HcalOverAll",";pion p_{T};E_{HCals}/E_{all calos};oHCal #Delta#phi",60,0.,30.,100,0.,1.,160,-0.4,0.4)
TH3D * hDeltaPhi_fraction_oHcalOverHcals = new TH3D("hDeltaPhi_fraction_oHcalOverHcals",";pion p_{T};E_{oHCal}/E_{HCals};oHCal #Delta#phi",60,0.,30.,100,0.,1.,160,-0.4,0.4)
TH3D * hE_weighted_eta_phi [ncal]
TH3D * h_eta_phi [ncal]
TH2D * hPhi2D [ncal]
TH2D * hDeltaPhi_pt [ncal]
TH2D * hDeltaPhi_eta [ncal]
TH2D * hTowerEt_pionEt [ncal]
TH2D * hCaloEnergy_pionPt [ncal]
TH2D * hEnergy_fraction [ncal]
TH2D * hDeltaPhi_E [ncal]
TH2D * hDeltaPhi_iPhi [ncal]
TH2D * hDeltaPhi_fraction [ncal]
TH1D * hDeltaPhi [ncal]
TH1D * hCaloPhi [ncal]
TH1D * hTowerEt [ncal]
Function Documentation
double delta_phi (double phi1, double phi2)
Definition at line 63 of file ExploreTTrees.C.
View newest version in sPHENIX GitHub at line 63 of file ExploreTTrees.C
double dR (double phi1, double phi2, double eta1, double eta2)
Definition at line 70 of file ExploreTTrees.C.
View newest version in sPHENIX GitHub at line 70 of file ExploreTTrees.C
References delta_phi().
Referenced by draw_G4_bjet_truth_tagging(), draw_G4_dibjet_truth_tagging(), PIDplots::eID(), ExploreTTrees(), TruthJetTagging::hadron_tagging(), HFJetTruthTrigger::hadron_tagging(), Jet_reso(), Jet_reso_Iso(), main(), Langevin::Make(), HFJetTruthTrigger::parton_tagging(), RawClusterBuilderTopo::process_event(), ParticleFlowReco::process_event(), DetermineTowerBackground::process_event(), SoftLeptonTaggingTruth::process_Spectrum(), Acts::Legacy::AtlasSeedFinder< SpacePoint >::production3Sp(), ProtoTracklets(), Acts::AtlasStepper::step(), Conversion::vtxTrackRZ(), and RecoConversionEval::vtxTrackRZCut().
void ExploreTTrees ()
Definition at line 105 of file ExploreTTrees.C.
View newest version in sPHENIX GitHub at line 105 of file ExploreTTrees.C
References Acts::Test::at, cal_name, cal_tag, calo_e, calo_eta, calo_ieta, calo_iphi, calo_phi, delta_phi(), double(), dR(), Acts::UnitConstants::e, eta, myAnalysis::eta_max, event, f, std::tr1::f1, fChain, h_eta_phi, hCaloEnergy_pionPt, hCaloPhi, hDeltaPhi, hDeltaPhi_E, hDeltaPhi_eta, hDeltaPhi_fraction, hDeltaPhi_fraction_HcalOverAll, hDeltaPhi_fraction_oHcalOverHcals, hDeltaPhi_iPhi, hDeltaPhi_pt, hE_inner_vs_outer, hE_weighted_eta_phi, hEMCal3x3, hEMCal3x3_FINE, hEnergy_fraction, hGeantPhi, add_histos::histos, hPhi2D, hTowerEt, hTowerEt_pionEt, i, i_cal, configureMap::inFileName, j, n_eta_bins, n_phi_bins, n_pt_bins, ncal, nTowers, writeMapConfig::outFileName, ActsTests::PropagationDatasets::phi, phi_in_range(), Acts::Test::pos, physmon_track_finding_ttbar::pt, pt_bin_hi, pt_bin_lo, title, total_E, tower_in_3x3(), Acts::UnitConstants::us, vx, vy, and vz.
double phi_in_range (double phi)
Definition at line 76 of file ExploreTTrees.C.
View newest version in sPHENIX GitHub at line 76 of file ExploreTTrees.C
References ActsTests::PropagationDatasets::phi.
bool tower_in_3x3 (float calo_eta, float calo_phi, float eta, float phi)
Definition at line 82 of file ExploreTTrees.C.
View newest version in sPHENIX GitHub at line 82 of file ExploreTTrees.C
Referenced by ExploreTTrees().
Variable Documentation
string cal_name[] = { "iHCal", "oHCal", "EMCal" }
Definition at line 45 of file ExploreTTrees.C.
View newest version in sPHENIX GitHub at line 45 of file ExploreTTrees.C
string cal_tag[] = { "_in", "_out", "_emc" }
Definition at line 46 of file ExploreTTrees.C.
View newest version in sPHENIX GitHub at line 46 of file ExploreTTrees.C
vector<float>* calo_e[ncal] = {&e_in, &e_out, &e_emc}
Definition at line 59 of file ExploreTTrees.C.
View newest version in sPHENIX GitHub at line 59 of file ExploreTTrees.C
vector<float>* calo_eta[ncal] = {&eta_in, &eta_out, &eta_emc}
Definition at line 57 of file ExploreTTrees.C.
View newest version in sPHENIX GitHub at line 57 of file ExploreTTrees.C
vector<int>* calo_ieta[ncal] = {&ieta_in, &ieta_out, &ieta_emc}
Definition at line 60 of file ExploreTTrees.C.
View newest version in sPHENIX GitHub at line 60 of file ExploreTTrees.C
vector<int>* calo_iphi[ncal] = {&iphi_in, &iphi_out, &iphi_emc}
Definition at line 61 of file ExploreTTrees.C.
View newest version in sPHENIX GitHub at line 61 of file ExploreTTrees.C
vector<float>* calo_phi[ncal] = {&phi_in, &phi_out, &phi_emc}
Definition at line 58 of file ExploreTTrees.C.
View newest version in sPHENIX GitHub at line 58 of file ExploreTTrees.C
Float_t e
Definition at line 14 of file ExploreTTrees.C.
View newest version in sPHENIX GitHub at line 14 of file ExploreTTrees.C
vector<float> e_emc
Definition at line 36 of file ExploreTTrees.C.
View newest version in sPHENIX GitHub at line 36 of file ExploreTTrees.C
vector<float> e_in
Definition at line 24 of file ExploreTTrees.C.
View newest version in sPHENIX GitHub at line 24 of file ExploreTTrees.C
vector<float> e_out
Definition at line 30 of file ExploreTTrees.C.
View newest version in sPHENIX GitHub at line 30 of file ExploreTTrees.C
Float_t eta
Definition at line 12 of file ExploreTTrees.C.
View newest version in sPHENIX GitHub at line 12 of file ExploreTTrees.C
vector<float> eta_emc
Definition at line 34 of file ExploreTTrees.C.
View newest version in sPHENIX GitHub at line 34 of file ExploreTTrees.C
vector<float> eta_in
Definition at line 22 of file ExploreTTrees.C.
View newest version in sPHENIX GitHub at line 22 of file ExploreTTrees.C
double eta_max[ncal] = {1.1,1.1,1.152}
Definition at line 52 of file ExploreTTrees.C.
View newest version in sPHENIX GitHub at line 52 of file ExploreTTrees.C
vector<float> eta_out
Definition at line 28 of file ExploreTTrees.C.
View newest version in sPHENIX GitHub at line 28 of file ExploreTTrees.C
Int_t event
Definition at line 11 of file ExploreTTrees.C.
View newest version in sPHENIX GitHub at line 11 of file ExploreTTrees.C
TTree* fChain
Definition at line 40 of file ExploreTTrees.C.
View newest version in sPHENIX GitHub at line 40 of file ExploreTTrees.C
Int_t fCurrent
pointer to the analyzed TTree or TChain
Definition at line 41 of file ExploreTTrees.C.
View newest version in sPHENIX GitHub at line 41 of file ExploreTTrees.C
TH3D * h_eta_phi[ncal]
Definition at line 100 of file ExploreTTrees.C.
View newest version in sPHENIX GitHub at line 100 of file ExploreTTrees.C
Referenced by ExploreTTrees().
TH2D * hCaloEnergy_pionPt[ncal]
Definition at line 101 of file ExploreTTrees.C.
View newest version in sPHENIX GitHub at line 101 of file ExploreTTrees.C
Referenced by ExploreTTrees().
TH1D * hCaloPhi[ncal]
Definition at line 103 of file ExploreTTrees.C.
View newest version in sPHENIX GitHub at line 103 of file ExploreTTrees.C
Referenced by ExploreTTrees().
TH1D* hDeltaPhi[ncal]
Definition at line 103 of file ExploreTTrees.C.
View newest version in sPHENIX GitHub at line 103 of file ExploreTTrees.C
Referenced by ExploreTTrees().
TH2D * hDeltaPhi_E[ncal]
Definition at line 101 of file ExploreTTrees.C.
View newest version in sPHENIX GitHub at line 101 of file ExploreTTrees.C
Referenced by ExploreTTrees().
TH2D * hDeltaPhi_eta[ncal]
Definition at line 101 of file ExploreTTrees.C.
View newest version in sPHENIX GitHub at line 101 of file ExploreTTrees.C
Referenced by ExploreTTrees().
TH2D * hDeltaPhi_fraction[ncal]
Definition at line 101 of file ExploreTTrees.C.
View newest version in sPHENIX GitHub at line 101 of file ExploreTTrees.C
Referenced by ExploreTTrees().
TH3D* hDeltaPhi_fraction_HcalOverAll = new TH3D("hDeltaPhi_fraction_HcalOverAll",";pion p_{T};E_{HCals}/E_{all calos};oHCal #Delta#phi",60,0.,30.,100,0.,1.,160,-0.4,0.4)
Definition at line 97 of file ExploreTTrees.C.
View newest version in sPHENIX GitHub at line 97 of file ExploreTTrees.C
Referenced by ExploreTTrees().
TH3D* hDeltaPhi_fraction_oHcalOverHcals = new TH3D("hDeltaPhi_fraction_oHcalOverHcals",";pion p_{T};E_{oHCal}/E_{HCals};oHCal #Delta#phi",60,0.,30.,100,0.,1.,160,-0.4,0.4)
Definition at line 98 of file ExploreTTrees.C.
View newest version in sPHENIX GitHub at line 98 of file ExploreTTrees.C
Referenced by ExploreTTrees().
TH2D * hDeltaPhi_iPhi[ncal]
Definition at line 101 of file ExploreTTrees.C.
View newest version in sPHENIX GitHub at line 101 of file ExploreTTrees.C
Referenced by ExploreTTrees().
TH2D * hDeltaPhi_pt[ncal]
Definition at line 101 of file ExploreTTrees.C.
View newest version in sPHENIX GitHub at line 101 of file ExploreTTrees.C
Referenced by ExploreTTrees().
TH3D* hE_inner_vs_outer = new TH3D("hE_inner_vs_outer",";pion p_{T};total E deposited in iHCal;total E deposited in oHCal",60,0.,30.,100, 0., 10.,120,0.,60.)
Definition at line 96 of file ExploreTTrees.C.
View newest version in sPHENIX GitHub at line 96 of file ExploreTTrees.C
Referenced by ExploreTTrees().
TH3D* hE_weighted_eta_phi[ncal]
Definition at line 100 of file ExploreTTrees.C.
View newest version in sPHENIX GitHub at line 100 of file ExploreTTrees.C
Referenced by ExploreTTrees().
TH2D* hEMCal3x3 = new TH2D("hEMCal3x3","pion p_{T};E_{EMCal}^{3x3} about max-E tower [GeV]",30,0.,30.,120,0.,60.)
Definition at line 94 of file ExploreTTrees.C.
View newest version in sPHENIX GitHub at line 94 of file ExploreTTrees.C
Referenced by ExploreTTrees().
TH2D* hEMCal3x3_FINE = new TH2D("hEMCal3x3_FINE","pion p_{T};E_{EMCal}^{3x3} about max-E tower [GeV]",30,0.,30.,200.,0.,2.)
Definition at line 95 of file ExploreTTrees.C.
View newest version in sPHENIX GitHub at line 95 of file ExploreTTrees.C
Referenced by ExploreTTrees().
TH2D * hEnergy_fraction[ncal]
Definition at line 101 of file ExploreTTrees.C.
View newest version in sPHENIX GitHub at line 101 of file ExploreTTrees.C
Referenced by ExploreTTrees().
TH1D* hGeantPhi = new TH1D("hGeantPhi",";truth #phi",64,-M_PI,M_PI)
Definition at line 93 of file ExploreTTrees.C.
View newest version in sPHENIX GitHub at line 93 of file ExploreTTrees.C
Referenced by ExploreTTrees().
TH2D* hPhi2D[ncal]
Definition at line 101 of file ExploreTTrees.C.
View newest version in sPHENIX GitHub at line 101 of file ExploreTTrees.C
Referenced by ExploreTTrees().
TH1D * hTowerEt[ncal]
Definition at line 103 of file ExploreTTrees.C.
View newest version in sPHENIX GitHub at line 103 of file ExploreTTrees.C
Referenced by ExploreTTrees().
TH2D * hTowerEt_pionEt[ncal]
Definition at line 101 of file ExploreTTrees.C.
View newest version in sPHENIX GitHub at line 101 of file ExploreTTrees.C
Referenced by ExploreTTrees().
vector<int> id
Definition at line 19 of file ExploreTTrees.C.
View newest version in sPHENIX GitHub at line 19 of file ExploreTTrees.C
vector<int> ieta_emc
Definition at line 37 of file ExploreTTrees.C.
View newest version in sPHENIX GitHub at line 37 of file ExploreTTrees.C
vector<int> ieta_in
Definition at line 25 of file ExploreTTrees.C.
View newest version in sPHENIX GitHub at line 25 of file ExploreTTrees.C
vector<int> ieta_out
Definition at line 31 of file ExploreTTrees.C.
View newest version in sPHENIX GitHub at line 31 of file ExploreTTrees.C
TString inFileName = "HCalJetPhiShift_10k.root"
Definition at line 47 of file ExploreTTrees.C.
View newest version in sPHENIX GitHub at line 47 of file ExploreTTrees.C
vector<int> iphi_emc
Definition at line 38 of file ExploreTTrees.C.
View newest version in sPHENIX GitHub at line 38 of file ExploreTTrees.C
vector<int> iphi_in
Definition at line 26 of file ExploreTTrees.C.
View newest version in sPHENIX GitHub at line 26 of file ExploreTTrees.C
vector<int> iphi_out
Definition at line 32 of file ExploreTTrees.C.
View newest version in sPHENIX GitHub at line 32 of file ExploreTTrees.C
int n_eta_bins[ncal] = {24,24,96}
Definition at line 53 of file ExploreTTrees.C.
View newest version in sPHENIX GitHub at line 53 of file ExploreTTrees.C
int n_phi_bins[ncal] = {64,64,256}
Definition at line 54 of file ExploreTTrees.C.
View newest version in sPHENIX GitHub at line 54 of file ExploreTTrees.C
int n_pt_bins[ncal] = {80,100,100}
Definition at line 49 of file ExploreTTrees.C.
View newest version in sPHENIX GitHub at line 49 of file ExploreTTrees.C
const int ncal = 3
current Tree number in a TChain
Definition at line 44 of file ExploreTTrees.C.
View newest version in sPHENIX GitHub at line 44 of file ExploreTTrees.C
int nTow_emc
Definition at line 33 of file ExploreTTrees.C.
View newest version in sPHENIX GitHub at line 33 of file ExploreTTrees.C
int nTow_in
Definition at line 21 of file ExploreTTrees.C.
View newest version in sPHENIX GitHub at line 21 of file ExploreTTrees.C
int nTow_out
Definition at line 27 of file ExploreTTrees.C.
View newest version in sPHENIX GitHub at line 27 of file ExploreTTrees.C
int* nTowers[ncal] = {&nTow_in, &nTow_out, &nTow_emc}
Definition at line 56 of file ExploreTTrees.C.
View newest version in sPHENIX GitHub at line 56 of file ExploreTTrees.C
Float_t phi
Definition at line 13 of file ExploreTTrees.C.
View newest version in sPHENIX GitHub at line 13 of file ExploreTTrees.C
vector<float> phi_emc
Definition at line 35 of file ExploreTTrees.C.
View newest version in sPHENIX GitHub at line 35 of file ExploreTTrees.C
vector<float> phi_in
Definition at line 23 of file ExploreTTrees.C.
View newest version in sPHENIX GitHub at line 23 of file ExploreTTrees.C
vector<float> phi_out
Definition at line 29 of file ExploreTTrees.C.
View newest version in sPHENIX GitHub at line 29 of file ExploreTTrees.C
Float_t pt
Definition at line 15 of file ExploreTTrees.C.
View newest version in sPHENIX GitHub at line 15 of file ExploreTTrees.C
double pt_bin_hi[ncal] = {4.,50.,20.}
Definition at line 51 of file ExploreTTrees.C.
View newest version in sPHENIX GitHub at line 51 of file ExploreTTrees.C
double pt_bin_lo[ncal] = {0.,0.,0.}
Definition at line 50 of file ExploreTTrees.C.
View newest version in sPHENIX GitHub at line 50 of file ExploreTTrees.C
Float_t vx
Definition at line 16 of file ExploreTTrees.C.
View newest version in sPHENIX GitHub at line 16 of file ExploreTTrees.C
Float_t vy
Definition at line 17 of file ExploreTTrees.C.
View newest version in sPHENIX GitHub at line 17 of file ExploreTTrees.C
Float_t vz
Definition at line 18 of file ExploreTTrees.C.
View newest version in sPHENIX GitHub at line 18 of file ExploreTTrees.C