Analysis Software: ActsExamples::HepMC3Event Namespace Reference
ActsExamples::HepMC3Event Namespace Reference
Functions
void momentumUnit (HepMC3::GenEvent &event, const double momentumUnit)
Sets new units for momentums.
void lengthUnit (HepMC3::GenEvent &event, const double lengthUnit)
Sets new units for lengths.
void shiftPositionBy (HepMC3::GenEvent &event, const Acts::Vector3 &deltaPos, const double deltaTime)
Shifts the positioning of an event in space and time.
void shiftPositionTo (HepMC3::GenEvent &event, const Acts::Vector3 &pos, const double time)
Shifts the positioning of an event to a paint in space and time.
void shiftPositionTo (HepMC3::GenEvent &event, const Acts::Vector3 &pos)
Shifts the positioning of an event to a paint in space.
void shiftPositionTo (HepMC3::GenEvent &event, const double time)
Shifts the positioning of an event to a paint in time.
void addParticle (HepMC3::GenEvent &event, const std::shared_ptr< SimParticle > &particle)
Adds a new particle.
void addVertex (HepMC3::GenEvent &event, const std::shared_ptr< SimVertex > &vertex)
Adds a new vertex.
void removeParticle (HepMC3::GenEvent &event, const std::shared_ptr< SimParticle > &particle)
Removes a particle from the record.
void removeVertex (HepMC3::GenEvent &event, const std::shared_ptr< SimVertex > &vertex)
Removes a vertex from the record.
double momentumUnit (const HepMC3::GenEvent &event)
Getter of the unit of momentum used.
double lengthUnit (const HepMC3::GenEvent &event)
Getter of the unit of length used.
Acts::Vector3 eventPos (const HepMC3::GenEvent &event)
Getter of the position of the event.
double eventTime (const HepMC3::GenEvent &event)
Getter of the time of the event.
std::vector< SimParticle > particles (const HepMC3::GenEvent &event)
Get list of particles.
std::vector< std::unique_ptr
< SimVertex > > vertices (const HepMC3::GenEvent &event)
Get list of vertices.
std::vector< SimParticle > beams (const HepMC3::GenEvent &event)
Get beam particles.
std::vector< SimParticle > finalState (const HepMC3::GenEvent &event)
Get final state particles.
Function Documentation
void ActsExamples::HepMC3Event::addParticle (HepMC3::GenEvent & event, const std::shared_ptr< SimParticle > & particle)
Adds a new particle.
Adder
Parameters
event event in HepMC data type
particle new particle that will be added
Adder
Definition at line 172 of file HepMC3Event.cpp.
View newest version in sPHENIX GitHub at line 172 of file HepMC3Event.cpp
Referenced by ActsFatras::PDGtoG4Converter::fillPredefinedParticles().
void ActsExamples::HepMC3Event::addVertex (HepMC3::GenEvent & event, const std::shared_ptr< SimVertex > & vertex)
Adds a new vertex.
Parameters
event event in HepMC data type
vertex new vertex that will be added
Note
The statuses are not represented in Acts and therefore set to 0
Definition at line 178 of file HepMC3Event.cpp.
View newest version in sPHENIX GitHub at line 178 of file HepMC3Event.cpp
std::vector< ActsExamples::SimParticle > ActsExamples::HepMC3Event::beams (const HepMC3::GenEvent & event)
Get beam particles.
Parameters
event event in HepMC data type
Returns
List of beam particles
Definition at line 276 of file HepMC3Event.cpp.
View newest version in sPHENIX GitHub at line 276 of file HepMC3Event.cpp
References particle.
Referenced by main().
Acts::Vector3 ActsExamples::HepMC3Event::eventPos (const HepMC3::GenEvent & event)
Getter of the position of the event.
Parameters
event event in HepMC data type
Returns
vector to the location of the event
Definition at line 233 of file HepMC3Event.cpp.
View newest version in sPHENIX GitHub at line 233 of file HepMC3Event.cpp
References vec.
Referenced by main().
double ActsExamples::HepMC3Event::eventTime (const HepMC3::GenEvent & event)
Getter of the time of the event.
Parameters
event event in HepMC data type
Returns
time of the event
Definition at line 243 of file HepMC3Event.cpp.
View newest version in sPHENIX GitHub at line 243 of file HepMC3Event.cpp
Referenced by main(), and PHActsTrkFitter::process_event().
std::vector< ActsExamples::SimParticle > ActsExamples::HepMC3Event::finalState (const HepMC3::GenEvent & event)
Get final state particles.
Parameters
event event in HepMC data type
Returns
List of final state particles
Definition at line 289 of file HepMC3Event.cpp.
View newest version in sPHENIX GitHub at line 289 of file HepMC3Event.cpp
References particle, and particles.
Referenced by main(), and ActsFatras::PhotonConversion::run().
void ActsExamples::HepMC3Event::lengthUnit (HepMC3::GenEvent & event, const double lengthUnit)
Sets new units for lengths.
Note
The allowed units are mm and cm
Parameters
event event in HepMC data type
lengthUnit new unit of length
Definition at line 118 of file HepMC3Event.cpp.
View newest version in sPHENIX GitHub at line 118 of file HepMC3Event.cpp
References Acts::UnitConstants::cm, and Acts::UnitConstants::mm.
Referenced by Acts::Python::addMagneticField(), Acts::IntegrationTest::atlasBField(), main(), Acts::materialMapperRZ(), Acts::materialMapperXYZ(), Acts::IntegrationTest::readFieldXYZ(), and ActsExamples::Options::readMagneticField().
double ActsExamples::HepMC3Event::lengthUnit (const HepMC3::GenEvent & event)
Getter of the unit of length used.
Parameters
event event in HepMC data type
Returns
unit of length
Definition at line 226 of file HepMC3Event.cpp.
View newest version in sPHENIX GitHub at line 226 of file HepMC3Event.cpp
References Acts::UnitConstants::cm, and Acts::UnitConstants::mm.
void ActsExamples::HepMC3Event::momentumUnit (HepMC3::GenEvent & event, const double momentumUnit)
Sets new units for momentums.
Setter
Note
The allowed units are MeV and Gev
Parameters
event event in HepMC data type
momentumUnit new unit of momentum
Setter
Definition at line 101 of file HepMC3Event.cpp.
View newest version in sPHENIX GitHub at line 101 of file HepMC3Event.cpp
References Acts::UnitConstants::GeV, and Acts::UnitConstants::MeV.
Referenced by main().
double ActsExamples::HepMC3Event::momentumUnit (const HepMC3::GenEvent & event)
Getter of the unit of momentum used.
Getter
Parameters
event event in HepMC data type
Returns
unit of momentum
Getter
Definition at line 219 of file HepMC3Event.cpp.
View newest version in sPHENIX GitHub at line 219 of file HepMC3Event.cpp
References Acts::UnitConstants::GeV, and Acts::UnitConstants::MeV.
std::vector< ActsExamples::SimParticle > ActsExamples::HepMC3Event::particles (const HepMC3::GenEvent & event)
Get list of particles.
Parameters
event event in HepMC data type
Returns
List of particles
Definition at line 248 of file HepMC3Event.cpp.
View newest version in sPHENIX GitHub at line 248 of file HepMC3Event.cpp
References particle.
Referenced by main().
void ActsExamples::HepMC3Event::removeParticle (HepMC3::GenEvent & event, const std::shared_ptr< SimParticle > & particle)
Removes a particle from the record.
Remover
Parameters
event event in HepMC data type
particle particle that will be removed
Remover
Definition at line 188 of file HepMC3Event.cpp.
View newest version in sPHENIX GitHub at line 188 of file HepMC3Event.cpp
References train_ambiguity_solver::id.
void ActsExamples::HepMC3Event::removeVertex (HepMC3::GenEvent & event, const std::shared_ptr< SimVertex > & vertex)
Removes a vertex from the record.
Note
The identification of the vertex is potentially unstable (c.f. HepMC3Event::compareVertices())
Parameters
event event in HepMC data type
vertex vertex that will be removed
Definition at line 202 of file HepMC3Event.cpp.
View newest version in sPHENIX GitHub at line 202 of file HepMC3Event.cpp
void ActsExamples::HepMC3Event::shiftPositionBy (HepMC3::GenEvent & event, const Acts::Vector3 & deltaPos, const double deltaTime)
Shifts the positioning of an event in space and time.
Parameters
event event in HepMC data type
deltaPos relative spatial shift that will be applied
deltaTime relative time shift that will be applied
Definition at line 136 of file HepMC3Event.cpp.
View newest version in sPHENIX GitHub at line 136 of file HepMC3Event.cpp
References vec.
void ActsExamples::HepMC3Event::shiftPositionTo (HepMC3::GenEvent & event, const Acts::Vector3 & pos, const double time)
Shifts the positioning of an event to a paint in space and time.
Parameters
event event in HepMC data type
pos new position of the event
time new time of the event
Definition at line 145 of file HepMC3Event.cpp.
View newest version in sPHENIX GitHub at line 145 of file HepMC3Event.cpp
References Acts::Test::pos, and vec.
void ActsExamples::HepMC3Event::shiftPositionTo (HepMC3::GenEvent & event, const Acts::Vector3 & pos)
Shifts the positioning of an event to a paint in space.
Parameters
event event in HepMC data type
pos new position of the event
Definition at line 153 of file HepMC3Event.cpp.
View newest version in sPHENIX GitHub at line 153 of file HepMC3Event.cpp
References Acts::Test::pos, and vec.
void ActsExamples::HepMC3Event::shiftPositionTo (HepMC3::GenEvent & event, const double time)
Shifts the positioning of an event to a paint in time.
Parameters
event event in HepMC data type
time new time of the event
Definition at line 160 of file HepMC3Event.cpp.
View newest version in sPHENIX GitHub at line 160 of file HepMC3Event.cpp
References Acts::Test::time, and vec.
std::vector< std::unique_ptr< ActsExamples::SimVertex > > ActsExamples::HepMC3Event::vertices (const HepMC3::GenEvent & event)
Get list of vertices.
Parameters
event event in HepMC data type
Returns
List of vertices
Definition at line 264 of file HepMC3Event.cpp.
View newest version in sPHENIX GitHub at line 264 of file HepMC3Event.cpp
References ActsExamples::HepMC3Vertex::processVertex().
Referenced by ActsFatras::PlanarSurfaceMask::annulusMask(), ActsFatras::PlanarSurfaceMask::apply(), Acts::Test::BOOST_AUTO_TEST_CASE(), BOOST_AUTO_TEST_CASE(), Acts::TrapezoidVolumeBounds::boundingBox(), genfit::EventDisplay::boxCreator(), KFParticle_eventReconstruction::buildChain(), PHG4EPDDetector::construct_block(), Acts::ConvexPolygonBoundsBase::convex_impl(), Acts::ConvexPolygonBounds< N >::ConvexPolygonBounds(), Acts::Experimental::DetectorVolume::createBoundingBox(), Acts::CylinderBounds::createCircles(), Acts::TGeoSurfaceConverter::discComponents(), Acts::BoundaryCheck::distance(), ActsExamples::IterativeVertexFinderAlgorithm::execute(), ActsExamples::AdaptiveMultiVertexFinderAlgorithm::executeAfterSeederChoice(), Acts::Polyhedron::extent(), SvtxEvaluator::fillOutputNtuples(), PHG4GDMLWriteSolids::GenTrapWrite(), Acts::DiscTrapezoidBounds::inside(), Acts::DiamondBounds::inside(), Acts::CylinderBounds::inside(), Acts::AdaptiveMultiVertexFitter< input_track_t, linearizer_t >::isAlreadyInList(), Acts::BoundaryCheck::isInside(), main(), genfit::EventDisplay::makeLines(), ActsExamples::makeProtoVertices(), Acts::Polyhedron::move(), ActsFatras::PlanarSurfaceTestBeds::operator()(), Acts::GenericCuboidVolumeBounds::orientedSurfaces(), Acts::PerigeeSurface::polyhedronRepresentation(), Acts::StrawSurface::polyhedronRepresentation(), Acts::SurfaceStub::polyhedronRepresentation(), Acts::PlaneSurface::polyhedronRepresentation(), Acts::ConeSurface::polyhedronRepresentation(), Acts::CylinderSurface::polyhedronRepresentation(), PHActsVertexFinder::Process(), PHActsInitialVertexFinder::Process(), Acts::Test::readTracksAndVertexCSV(), Acts::VolumeView3DTest::run(), Acts::AxisAlignedBoundingBox< entity_t, value_t, DIM >::transformVertices(), Acts::ConvexPolygonBoundsBase::values(), and ActsExamples::VertexPerformanceWriter::writeT().