Analysis Software: ActsExamples::ParticleSelector Exception Reference
ActsExamples::ParticleSelector Exception Reference final
Select particles by applying some selection cuts.
#include <acts/blob/sPHENIX/Examples/Algorithms/TruthTracking/ActsExamples/TruthTracking/ParticleSelector.hpp>
Classes
struct Config
Public Member Functions
ParticleSelector (const Config &config, Acts::Logging::Level level)
ProcessCode execute (const AlgorithmContext &ctx) const final
const Config & config () const
Get readonly access to the config parameters.
Public Member Functions inherited from ActsExamples::IAlgorithm
IAlgorithm (std::string name, Acts::Logging::Level level=Acts::Logging::INFO)
std::string name () const override
The algorithm name.
ProcessCode internalExecute (const AlgorithmContext &context) final
ProcessCode initialize () override
Initialize the algorithm.
ProcessCode finalize () override
Finalize the algorithm.
Private Attributes
Config m_cfg
ReadDataHandle
< SimParticleContainer > m_inputParticles {this, "InputParticles"}
ReadDataHandle< IndexMultimap
< ActsFatras::Barcode > > m_inputMap
WriteDataHandle
< SimParticleContainer > m_outputParticles
Additional Inherited Members
Protected Member Functions inherited from ActsExamples::IAlgorithm
const Acts::Logger & logger () const
Detailed Description
Select particles by applying some selection cuts.
Definition at line 31 of file ParticleSelector.hpp.
View newest version in sPHENIX GitHub at line 31 of file ParticleSelector.hpp
Constructor & Destructor Documentation
ActsExamples::ParticleSelector::ParticleSelector (const Config & config, Acts::Logging::Level level)
Definition at line 23 of file ParticleSelector.cpp.
View newest version in sPHENIX GitHub at line 23 of file ParticleSelector.cpp
References ActsExamples::ParticleSelector::Config::absEtaMax, ActsExamples::ParticleSelector::Config::absEtaMin, ActsExamples::ParticleSelector::Config::absZMax, ActsExamples::ParticleSelector::Config::absZMin, ACTS_DEBUG, ActsExamples::ParticleSelector::Config::etaMax, ActsExamples::ParticleSelector::Config::etaMin, ActsExamples::WriteDataHandle< T >::initialize(), ActsExamples::ReadDataHandle< T >::initialize(), ActsExamples::ParticleSelector::Config::inputMeasurementParticlesMap, ActsExamples::ParticleSelector::Config::inputParticles, m_cfg, m_inputMap, m_inputParticles, m_outputParticles, ActsExamples::ParticleSelector::Config::measurementsMax, ActsExamples::ParticleSelector::Config::measurementsMin, ActsExamples::ParticleSelector::Config::mMax, ActsExamples::ParticleSelector::Config::mMin, ActsExamples::ParticleSelector::Config::outputParticles, ActsExamples::ParticleSelector::Config::phiMax, ActsExamples::ParticleSelector::Config::phiMin, ActsExamples::ParticleSelector::Config::ptMax, ActsExamples::ParticleSelector::Config::ptMin, ActsExamples::ParticleSelector::Config::removeCharged, ActsExamples::ParticleSelector::Config::removeNeutral, ActsExamples::ParticleSelector::Config::removeSecondaries, ActsExamples::ParticleSelector::Config::rhoMax, ActsExamples::ParticleSelector::Config::rhoMin, ActsExamples::ParticleSelector::Config::timeMax, and ActsExamples::ParticleSelector::Config::timeMin.
Member Function Documentation
const Config& ActsExamples::ParticleSelector::config () const inline
Get readonly access to the config parameters.
Definition at line 79 of file ParticleSelector.hpp.
View newest version in sPHENIX GitHub at line 79 of file ParticleSelector.hpp
References m_cfg.
ActsExamples::ProcessCode ActsExamples::ParticleSelector::execute (const AlgorithmContext & context) const final virtual
Execute the algorithm for one event.
This function must be implemented by subclasses.
Implements ActsExamples::IAlgorithm.
Definition at line 65 of file ParticleSelector.cpp.
View newest version in sPHENIX GitHub at line 65 of file ParticleSelector.cpp
References ACTS_DEBUG, ACTS_VERBOSE, KFPMath::b, distance(), Acts::UnitConstants::e, Acts::ePos2, eta, Acts::VectorHelpers::eta(), ActsExamples::AlgorithmContext::eventNumber, physmon_simulation::inputParticles, ActsExamples::invertIndexMultimap(), m_cfg(), Acts::UnitConstants::min, testing::internal::move(), physmon_simulation::outputParticles, merge_hashes::p, Acts::VectorHelpers::perp(), ActsTests::PropagationDatasets::phi, Acts::VectorHelpers::phi(), rho, SUCCESS, and ambiguity_solver_full_chain::x.
Member Data Documentation
Config ActsExamples::ParticleSelector::m_cfg private
Definition at line 82 of file ParticleSelector.hpp.
View newest version in sPHENIX GitHub at line 82 of file ParticleSelector.hpp
Referenced by config(), and ParticleSelector().
ReadDataHandle<IndexMultimap<ActsFatras::Barcode> > ActsExamples::ParticleSelector::m_inputMap private
Initial value:
{
      this, "InputMeasurementParticlesMap"}
Definition at line 85 of file ParticleSelector.hpp.
View newest version in sPHENIX GitHub at line 85 of file ParticleSelector.hpp
Referenced by ParticleSelector().
ReadDataHandle<SimParticleContainer> ActsExamples::ParticleSelector::m_inputParticles {this, "InputParticles"} private
Definition at line 84 of file ParticleSelector.hpp.
View newest version in sPHENIX GitHub at line 84 of file ParticleSelector.hpp
Referenced by ParticleSelector().
WriteDataHandle<SimParticleContainer> ActsExamples::ParticleSelector::m_outputParticles private
Initial value:
{this,
                                                          "OutputParticles"}
Definition at line 88 of file ParticleSelector.hpp.
View newest version in sPHENIX GitHub at line 88 of file ParticleSelector.hpp
Referenced by ParticleSelector().
The documentation for this exception was generated from the following files:
acts/blob/sPHENIX/Examples/Algorithms/TruthTracking/ActsExamples/TruthTracking/ParticleSelector.hpp
acts/blob/sPHENIX/Examples/Algorithms/TruthTracking/ActsExamples/TruthTracking/ParticleSelector.cpp