Analysis Software: PHG4FullProjSpacalCellReco Class Reference
PHG4FullProjSpacalCellReco Class Reference
#include <coresoftware/blob/master/simulation/g4simulation/g4detectors/PHG4FullProjSpacalCellReco.h>
Public Member Functions
PHG4FullProjSpacalCellReco (const std::string &name="SPACALCELLRECO")
~PHG4FullProjSpacalCellReco () override
int InitRun (PHCompositeNode *topNode) override
module initialization
int process_event (PHCompositeNode *topNode) override
event processing
int ResetEvent (PHCompositeNode *topNode) override
reset after event processing
void SetDefaultParameters () override
void Detector (const std::string &d)
void checkenergy (const int i=1)
void set_timing_window (const double tmin, const double tmax)
LightCollectionModel & get_light_collection_model ()
Public Member Functions inherited from SubsysReco
~SubsysReco () override
virtual int End (PHCompositeNode *)
Called at the end of all processing.
virtual int EndRun (const int)
Called at the end of each run.
virtual int Init (PHCompositeNode *)
virtual int Reset (PHCompositeNode *)
Reset.
void Print (const std::string &="ALL") const override
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Public Member Functions inherited from PHParameterInterface
PHParameterInterface (const std::string &name)
PHParameterInterface (const PHParameterInterface &)=delete
PHParameterInterface & operator= (PHParameterInterface const &)=delete
virtual ~PHParameterInterface ()
void set_paramname (const std::string &name)
void set_double_param (const std::string &name, const double dval)
double get_double_param (const std::string &name) const
void set_int_param (const std::string &name, const int ival)
int get_int_param (const std::string &name) const
void set_string_param (const std::string &name, const std::string &sval)
std::string get_string_param (const std::string &name) const
void UpdateParametersWithMacro ()
void SaveToNodeTree (PHCompositeNode *runNode, const std::string &nodename)
void PutOnParNode (PHCompositeNode *parNode, const std::string &nodename)
void Print () const
Protected Member Functions
int CheckEnergy (PHCompositeNode *topNode)
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Protected Member Functions inherited from Fun4AllBase
Fun4AllBase (const std::string &name="NONAME")
Protected Member Functions inherited from PHParameterInterface
void set_default_double_param (const std::string &name, const double dval)
void set_default_int_param (const std::string &name, const int ival)
void set_default_string_param (const std::string &name, const std::string &sval)
void InitializeParameters ()
Protected Attributes
std::string detector
std::string hitnodename
std::string cellnodename
std::string geonodename
std::string seggeonodename
double sum_energy_g4hit = 0
int chkenergyconservation = 0
std::map< unsigned int,
PHG4Cell * > celllist
double tmin = NAN
timing window size in ns. This is for a simple simulation of the ADC integration window starting from 0ns to this value. Default to infinity, i.e. include all hits
double tmax = NAN
double m_DeltaT = NAN
LightCollectionModel light_collection_model
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = std::numeric_limits<int>::max() - 10
}
Detailed Description
Definition at line 22 of file PHG4FullProjSpacalCellReco.h.
View newest version in sPHENIX GitHub at line 22 of file PHG4FullProjSpacalCellReco.h
Constructor & Destructor Documentation
PHG4FullProjSpacalCellReco::PHG4FullProjSpacalCellReco (const std::string & name = "SPACALCELLRECO")
Definition at line 53 of file PHG4FullProjSpacalCellReco.cc.
View newest version in sPHENIX GitHub at line 53 of file PHG4FullProjSpacalCellReco.cc
References PHParameterInterface::InitializeParameters().
PHG4FullProjSpacalCellReco::~PHG4FullProjSpacalCellReco () inline override
Definition at line 27 of file PHG4FullProjSpacalCellReco.h.
View newest version in sPHENIX GitHub at line 27 of file PHG4FullProjSpacalCellReco.h
Member Function Documentation
void PHG4FullProjSpacalCellReco::checkenergy (const int i = 1) inline
Definition at line 42 of file PHG4FullProjSpacalCellReco.h.
View newest version in sPHENIX GitHub at line 42 of file PHG4FullProjSpacalCellReco.h
References chkenergyconservation, and i.
int PHG4FullProjSpacalCellReco::CheckEnergy (PHCompositeNode * topNode) protected
Definition at line 488 of file PHG4FullProjSpacalCellReco.cc.
View newest version in sPHENIX GitHub at line 488 of file PHG4FullProjSpacalCellReco.cc
References cellnodename, Acts::UnitConstants::e, PHG4CellContainer::getCells(), Fun4AllBase::Name(), sum_energy_g4hit, and Fun4AllBase::Verbosity().
Referenced by process_event().
void PHG4FullProjSpacalCellReco::Detector (const std::string & d) inline
Definition at line 40 of file PHG4FullProjSpacalCellReco.h.
View newest version in sPHENIX GitHub at line 40 of file PHG4FullProjSpacalCellReco.h
Referenced by CEMC_Cells(), Fun4All_G4_Prototype2(), Fun4All_G4_Prototype3(), and Fun4All_G4_Prototype4().
LightCollectionModel& PHG4FullProjSpacalCellReco::get_light_collection_model () inline
Definition at line 47 of file PHG4FullProjSpacalCellReco.h.
View newest version in sPHENIX GitHub at line 47 of file PHG4FullProjSpacalCellReco.h
References light_collection_model.
Referenced by CEMC_Cells(), Fun4All_G4_Prototype2(), Fun4All_G4_Prototype3(), and Fun4All_G4_Prototype4().
int PHG4FullProjSpacalCellReco::InitRun (PHCompositeNode * topNode) override virtual
module initialization
Reimplemented from SubsysReco.
Definition at line 66 of file PHG4FullProjSpacalCellReco.cc.
View newest version in sPHENIX GitHub at line 66 of file PHG4FullProjSpacalCellReco.cc
References PHG4CylinderCellGeomContainer::AddLayerCellGeom(), PHCompositeNode::addNode(), assert, cellnodename, PHG4CylinderGeom_Spacalv3::geom_tower::centralZ, detector, dz, KF_timing::etabin, Fun4AllReturnCodes::EVENT_OK, PHNodeIterator::findFirst(), geonodename, PHG4CylinderGeom_Spacalv2::get_azimuthal_n_sec(), PHParameterInterface::get_double_param(), PHG4CylinderGeomv1::get_layer(), PHG4CylinderGeom_Spacalv3::get_max_phi_bin_in_sec(), PHG4CylinderGeom_Spacalv3::get_n_subtower_eta(), PHG4CylinderGeom_Spacalv3::get_n_subtower_phi(), PHG4CylinderGeomv1::get_radius(), PHG4CylinderGeom_Spacalv1::get_sector_map(), PHG4CylinderGeom_Spacalv3::get_sector_tower_map(), PHG4CylinderGeomv1::get_thickness(), PHG4CylinderGeom_Spacalv3::get_tower_radial_position(), PHG4CylinderGeom_Spacalv3::get_tower_z_phi_ID(), PHG4CylinderGeomContainer::GetFirstLayerGeom(), hitnodename, PHG4CylinderGeomContainer::identify(), PHG4CylinderCellGeom_Spacalv1::identify(), PHG4CylinderGeom_Spacalv3::identify(), m_DeltaT, Fun4AllBase::Name(), PHG4CylinderGeom_Spacalv3::geom_tower::NSubtowerY, PHG4CylinderGeom_Spacalv3::geom_tower::pDy1, PHG4CylinderGeom_Spacalv3::geom_tower::pDy2, myAnalysis::phi_min, PHWHERE, PHG4CylinderGeom_Spacalv3::geom_tower::pRotationAngleX, PHParameterInterface::PutOnParNode(), PHParameterInterface::SaveToNodeTree(), seggeonodename, PHG4CylinderCellGeom::set_binning(), PHG4CylinderCellGeom::set_etabins(), PHG4CylinderCellGeom_Spacalv1::set_etabounds(), PHG4CylinderCellGeom::set_etamin(), PHG4CylinderCellGeom::set_etastep(), PHG4CylinderCellGeom::set_layer(), PHG4CylinderCellGeom::set_phibins(), PHG4CylinderCellGeom::set_phimin(), PHG4CylinderCellGeom::set_phistep(), PHG4CylinderCellGeom::set_radius(), PHG4CylinderCellGeom::set_thickness(), PHG4CylinderCellGeom_Spacalv1::set_tower_z_ID_eta_bin_map(), PHG4CylinderCellGeom_Spacalv1::set_zbounds(), PHG4CellDefs::spacalbinning, PHG4CylinderGeom_Spacalv3::subtower_consistency_check(), tmax, tmin, PHParameterInterface::UpdateParametersWithMacro(), Fun4AllBase::Verbosity(), Fun4AllBase::VERBOSITY_SOME, and physmon_track_finding_ttbar::z.
int PHG4FullProjSpacalCellReco::process_event (PHCompositeNode * topNode) override virtual
event processing
Reimplemented from SubsysReco.
Definition at line 315 of file PHG4FullProjSpacalCellReco.cc.
View newest version in sPHENIX GitHub at line 315 of file PHG4FullProjSpacalCellReco.cc
References PHG4Cell::add_edep(), PHG4Cell::add_light_yield(), PHG4Cell::add_shower_edep(), PHG4CellContainer::AddCell(), assert, celllist, cellnodename, CheckEnergy(), chkenergyconservation, Acts::UnitConstants::e, KF_timing::etabin, Fun4AllReturnCodes::EVENT_OK, PHG4CylinderGeom_Spacalv3::scint_id_coder::fiber_ID, PHG4CellDefs::SpacalBinning::genkey(), geonodename, PHG4CellDefs::SpacalBinning::get_etabin(), PHG4CylinderCellGeom_Spacalv1::get_etabin_block(), LightCollectionModel::get_fiber_transmission(), PHG4CellDefs::SpacalBinning::get_fiberid(), LightCollectionModel::get_light_guide_efficiency(), PHG4Cell::get_light_yield(), PHG4CylinderGeom_Spacalv3::get_n_subtower_eta(), PHG4CylinderGeom_Spacalv3::get_n_subtower_phi(), PHG4CellDefs::SpacalBinning::get_phibin(), PHG4CylinderGeom_Spacalv3::get_sector_tower_map(), PHG4CylinderGeom_Spacalv3::get_tower_z_phi_ID(), PHG4CylinderCellGeomContainer::GetFirstLayerCellGeom(), PHG4CylinderGeomContainer::GetFirstLayerGeom(), PHG4HitContainer::getHits(), hitnodename, PHG4CylinderCellGeom_Spacalv1::identify(), PHG4CylinderGeom_Spacalv3::scint_id_coder::identify(), it, light_collection_model, m_DeltaT, Fun4AllBase::Name(), PHG4CylinderGeom_Spacalv3::scint_id_coder::sector_ID, seggeonodename, sum_energy_g4hit, tmax, tmin, PHG4CylinderGeom_Spacalv3::scint_id_coder::tower_ID, LightCollectionModel::use_fiber_model(), Fun4AllBase::Verbosity(), ambiguity_solver_full_chain::x, y, and physmon_track_finding_ttbar::z.
int PHG4FullProjSpacalCellReco::ResetEvent (PHCompositeNode * topNode) override virtual
reset after event processing
Reimplemented from SubsysReco.
Definition at line 60 of file PHG4FullProjSpacalCellReco.cc.
View newest version in sPHENIX GitHub at line 60 of file PHG4FullProjSpacalCellReco.cc
References Fun4AllReturnCodes::EVENT_OK, and sum_energy_g4hit.
void PHG4FullProjSpacalCellReco::set_timing_window (const double tmin, const double tmax)
Definition at line 528 of file PHG4FullProjSpacalCellReco.cc.
View newest version in sPHENIX GitHub at line 528 of file PHG4FullProjSpacalCellReco.cc
References PHParameterInterface::set_double_param().
Referenced by Fun4All_G4_Prototype2(), Fun4All_G4_Prototype3(), and Fun4All_G4_Prototype4().
void PHG4FullProjSpacalCellReco::SetDefaultParameters () override virtual
Implements PHParameterInterface.
Definition at line 520 of file PHG4FullProjSpacalCellReco.cc.
View newest version in sPHENIX GitHub at line 520 of file PHG4FullProjSpacalCellReco.cc
References PHParameterInterface::set_default_double_param().
Member Data Documentation
std::map<unsigned int, PHG4Cell *> PHG4FullProjSpacalCellReco::celllist protected
Definition at line 60 of file PHG4FullProjSpacalCellReco.h.
View newest version in sPHENIX GitHub at line 60 of file PHG4FullProjSpacalCellReco.h
Referenced by process_event().
std::string PHG4FullProjSpacalCellReco::cellnodename protected
Definition at line 54 of file PHG4FullProjSpacalCellReco.h.
View newest version in sPHENIX GitHub at line 54 of file PHG4FullProjSpacalCellReco.h
Referenced by CheckEnergy(), InitRun(), and process_event().
int PHG4FullProjSpacalCellReco::chkenergyconservation = 0 protected
Definition at line 59 of file PHG4FullProjSpacalCellReco.h.
View newest version in sPHENIX GitHub at line 59 of file PHG4FullProjSpacalCellReco.h
Referenced by checkenergy(), and process_event().
std::string PHG4FullProjSpacalCellReco::detector protected
Definition at line 52 of file PHG4FullProjSpacalCellReco.h.
View newest version in sPHENIX GitHub at line 52 of file PHG4FullProjSpacalCellReco.h
Referenced by InitRun().
std::string PHG4FullProjSpacalCellReco::geonodename protected
Definition at line 55 of file PHG4FullProjSpacalCellReco.h.
View newest version in sPHENIX GitHub at line 55 of file PHG4FullProjSpacalCellReco.h
Referenced by InitRun(), and process_event().
std::string PHG4FullProjSpacalCellReco::hitnodename protected
Definition at line 53 of file PHG4FullProjSpacalCellReco.h.
View newest version in sPHENIX GitHub at line 53 of file PHG4FullProjSpacalCellReco.h
Referenced by InitRun(), and process_event().
LightCollectionModel PHG4FullProjSpacalCellReco::light_collection_model protected
Definition at line 66 of file PHG4FullProjSpacalCellReco.h.
View newest version in sPHENIX GitHub at line 66 of file PHG4FullProjSpacalCellReco.h
Referenced by get_light_collection_model(), and process_event().
double PHG4FullProjSpacalCellReco::m_DeltaT = NAN protected
Definition at line 65 of file PHG4FullProjSpacalCellReco.h.
View newest version in sPHENIX GitHub at line 65 of file PHG4FullProjSpacalCellReco.h
Referenced by InitRun(), and process_event().
std::string PHG4FullProjSpacalCellReco::seggeonodename protected
Definition at line 56 of file PHG4FullProjSpacalCellReco.h.
View newest version in sPHENIX GitHub at line 56 of file PHG4FullProjSpacalCellReco.h
Referenced by InitRun(), and process_event().
double PHG4FullProjSpacalCellReco::sum_energy_g4hit = 0 protected
Definition at line 58 of file PHG4FullProjSpacalCellReco.h.
View newest version in sPHENIX GitHub at line 58 of file PHG4FullProjSpacalCellReco.h
Referenced by CheckEnergy(), process_event(), and ResetEvent().
double PHG4FullProjSpacalCellReco::tmax = NAN protected
Definition at line 64 of file PHG4FullProjSpacalCellReco.h.
View newest version in sPHENIX GitHub at line 64 of file PHG4FullProjSpacalCellReco.h
Referenced by InitRun(), and process_event().
double PHG4FullProjSpacalCellReco::tmin = NAN protected
timing window size in ns. This is for a simple simulation of the ADC integration window starting from 0ns to this value. Default to infinity, i.e. include all hits
Definition at line 63 of file PHG4FullProjSpacalCellReco.h.
View newest version in sPHENIX GitHub at line 63 of file PHG4FullProjSpacalCellReco.h
Referenced by InitRun(), and process_event().
The documentation for this class was generated from the following files:
coresoftware/blob/master/simulation/g4simulation/g4detectors/PHG4FullProjSpacalCellReco.h
coresoftware/blob/master/simulation/g4simulation/g4detectors/PHG4FullProjSpacalCellReco.cc