Analysis Software: GeometryVisualisationAndMaterialHandling Namespace Reference
GeometryVisualisationAndMaterialHandling Namespace Reference
Classes
class index_info
Functions
def dumper
def append_index_if_missing
def extract_coords
def dump_geo
def read_and_modify
Variables
tuple parser argparse.ArgumentParser()
string default ""
type str,
string help "Specify the input file for geometry visualisation"
string action "store_true"
tuple args parser.parse_args()
Function Documentation
def GeometryVisualisationAndMaterialHandling.append_index_if_missing (dictionary, name, index)
Definition at line 45 of file GeometryVisualisationAndMaterialHandling.py.
View newest version in sPHENIX GitHub at line 45 of file GeometryVisualisationAndMaterialHandling.py
Referenced by dump_geo().
def GeometryVisualisationAndMaterialHandling.dump_geo (filename, plot, output_folder, dump_steering, steering_file)
Definition at line 59 of file GeometryVisualisationAndMaterialHandling.py.
View newest version in sPHENIX GitHub at line 59 of file GeometryVisualisationAndMaterialHandling.py
References append_index_if_missing(), extract_coords(), Acts.open, print(), and str.
def GeometryVisualisationAndMaterialHandling.dumper (obj)
Definition at line 6 of file GeometryVisualisationAndMaterialHandling.py.
View newest version in sPHENIX GitHub at line 6 of file GeometryVisualisationAndMaterialHandling.py
def GeometryVisualisationAndMaterialHandling.extract_coords (coords, is_disc)
Definition at line 50 of file GeometryVisualisationAndMaterialHandling.py.
View newest version in sPHENIX GitHub at line 50 of file GeometryVisualisationAndMaterialHandling.py
Referenced by dump_geo(), and read_and_modify().
def GeometryVisualisationAndMaterialHandling.read_and_modify (filename, plot, output_folder, steering_file, output_file)
Definition at line 441 of file GeometryVisualisationAndMaterialHandling.py.
View newest version in sPHENIX GitHub at line 441 of file GeometryVisualisationAndMaterialHandling.py
References extract_coords(), Acts.open, print(), and str.
Variable Documentation
string GeometryVisualisationAndMaterialHandling.action "store_true"
Definition at line 736 of file GeometryVisualisationAndMaterialHandling.py.
View newest version in sPHENIX GitHub at line 736 of file GeometryVisualisationAndMaterialHandling.py
tuple GeometryVisualisationAndMaterialHandling.args parser.parse_args()
Definition at line 769 of file GeometryVisualisationAndMaterialHandling.py.
View newest version in sPHENIX GitHub at line 769 of file GeometryVisualisationAndMaterialHandling.py
string GeometryVisualisationAndMaterialHandling.default ""
Definition at line 729 of file GeometryVisualisationAndMaterialHandling.py.
View newest version in sPHENIX GitHub at line 729 of file GeometryVisualisationAndMaterialHandling.py
string GeometryVisualisationAndMaterialHandling.help "Specify the input file for geometry visualisation"
Definition at line 731 of file GeometryVisualisationAndMaterialHandling.py.
View newest version in sPHENIX GitHub at line 731 of file GeometryVisualisationAndMaterialHandling.py
tuple GeometryVisualisationAndMaterialHandling.parser argparse.ArgumentParser()
Definition at line 726 of file GeometryVisualisationAndMaterialHandling.py.
View newest version in sPHENIX GitHub at line 726 of file GeometryVisualisationAndMaterialHandling.py
GeometryVisualisationAndMaterialHandling.type str,
Definition at line 730 of file GeometryVisualisationAndMaterialHandling.py.
View newest version in sPHENIX GitHub at line 730 of file GeometryVisualisationAndMaterialHandling.py