Analysis Software: acts/blob/sPHENIX/Tests/UnitTests/Core/Detector/ReferenceGeneratorsTests.cpp File Reference
ReferenceGeneratorsTests.cpp File Reference
#include <boost/test/unit_test.hpp>
#include "Acts/Definitions/Algebra.hpp"
#include "Acts/Detector/detail/ReferenceGenerators.hpp"
#include "Acts/Geometry/GeometryContext.hpp"
#include "Acts/Surfaces/PlaneSurface.hpp"
#include "Acts/Surfaces/RectangleBounds.hpp"
#include "Acts/Surfaces/Surface.hpp"
#include "Acts/Utilities/BinningType.hpp"
#include <memory>
#include <utility>
#include <vector>
Functions
BOOST_AUTO_TEST_CASE (CenterReference)
BOOST_AUTO_TEST_CASE (BinningPositionReference)
BOOST_AUTO_TEST_CASE (PolyhedronReference)
Variables
Acts::GeometryContext tContext
auto rBounds = std::make_shared<Acts::RectangleBounds>(10, 20)
auto sTransform = Acts::Transform3::Identity()
auto pSurface
Function Documentation
BOOST_AUTO_TEST_CASE (CenterReference)
Definition at line 34 of file ReferenceGeneratorsTests.cpp.
View newest version in sPHENIX GitHub at line 34 of file ReferenceGeneratorsTests.cpp
References pSurface, Acts::Experimental::detail::CenterReferenceGenerator::references(), tContext, and physmon_ckf_tracking::u.
BOOST_AUTO_TEST_CASE (BinningPositionReference)
Definition at line 41 of file ReferenceGeneratorsTests.cpp.
View newest version in sPHENIX GitHub at line 41 of file ReferenceGeneratorsTests.cpp
References pSurface, Acts::Experimental::detail::BinningValueReferenceGenerator< bVAL >::references(), tContext, and physmon_ckf_tracking::u.
BOOST_AUTO_TEST_CASE (PolyhedronReference)
Definition at line 50 of file ReferenceGeneratorsTests.cpp.
View newest version in sPHENIX GitHub at line 50 of file ReferenceGeneratorsTests.cpp
References pSurface, Acts::Experimental::detail::PolyhedronReferenceGenerator< nSEGS, aBARY >::references(), tContext, and physmon_ckf_tracking::u.
Variable Documentation
auto pSurface
Initial value:
= Acts::Surface::makeShared<Acts::PlaneSurface>(
    sTransform.pretranslate(Acts::Vector3(20., 20., 100.)), std::move(rBounds))
Definition at line 29 of file ReferenceGeneratorsTests.cpp.
View newest version in sPHENIX GitHub at line 29 of file ReferenceGeneratorsTests.cpp
Referenced by Acts::Experimental::GeometryIdGenerator::assignGeometryId(), Acts::Test::Layers::BOOST_AUTO_TEST_CASE(), BOOST_AUTO_TEST_CASE(), Acts::Test::BOOST_AUTO_TEST_CASE(), Acts::DD4hepDetectorSurfaceFactory::constructPassiveComponents(), Acts::Svg::SurfaceConverter::convert(), Acts::Svg::DetectorVolumeConverter::convert(), Acts::Svg::IndexedSurfacesConverter::convertImpl(), ActsExamples::TrackFittingAlgorithm::execute(), ActsExamples::TrackFindingFromPrototrackAlgorithm::execute(), ActsExamples::AlignmentAlgorithm::execute(), ActsExamples::TrackFindingAlgorithm::execute(), ActsExamples::ResPlotTool::fill(), PHCosmicsTrkFitter::loopTracks(), PHActsTrkFitter::loopTracks(), Acts::CylinderVolumeBounds::orientedSurfaces(), PHActsGSF::process_event(), Acts::DD4hepDetectorSurfaceFactory::recursiveConstruct(), and ActsExamples::RootTrajectorySummaryWriter::writeT().
auto rBounds = std::make_shared<Acts::RectangleBounds>(10, 20)
Definition at line 27 of file ReferenceGeneratorsTests.cpp.
View newest version in sPHENIX GitHub at line 27 of file ReferenceGeneratorsTests.cpp
Referenced by Acts::Python::addOutput(), Acts::adjustBinUtility(), ActsFatras::PlanarSurfaceMask::apply(), Acts::Test::Layers::BOOST_AUTO_TEST_CASE(), Acts::Test::BOOST_AUTO_TEST_CASE(), BOOST_AUTO_TEST_CASE(), Acts::EventDataView3DTest::createDetector(), Acts::CylinderVolumeBounds::CylinderVolumeBounds(), Acts::DiscLayer::DiscLayer(), main(), Acts::Geant4ShapeConverter::planarBounds(), Acts::Geant4ShapeConverter::radialBounds(), Acts::Geant4ShapeConverter::rectangleBounds(), and Acts::SurfaceView3DTest::run().
auto sTransform = Acts::Transform3::Identity()
Definition at line 28 of file ReferenceGeneratorsTests.cpp.
View newest version in sPHENIX GitHub at line 28 of file ReferenceGeneratorsTests.cpp
Referenced by Acts::Experimental::detail::SupportHelper::addSupport(), BOOST_AUTO_TEST_CASE(), Acts::Test::BOOST_AUTO_TEST_CASE(), Acts::Svg::SurfaceArrayConverter::convert(), Acts::Experimental::detail::SupportHelper::cylindricalSupport(), Acts::Experimental::detail::SupportHelper::discSupport(), Acts::ConeSurface::localCartesianToBoundLocalDerivative(), Acts::CylinderSurface::localCartesianToBoundLocalDerivative(), Acts::surfaceFromJsonT(), Acts::SurfaceJsonConverter::toJson(), and Acts::SurfaceJsonConverter::toJsonDetray().
Acts::GeometryContext tContext
Definition at line 25 of file ReferenceGeneratorsTests.cpp.
View newest version in sPHENIX GitHub at line 25 of file ReferenceGeneratorsTests.cpp