Analysis Software: TpotMon Class Reference
TpotMon Class Reference
#include <OnlMon/blob/main/subsystems/tpot/TpotMon.h>
Classes
class detector_histograms_t
Public Types
using sample_window_t = std::pair< int, int >
Public Types inherited from OnlMon
enum { ACTIVE = -1, OK = 0, WARNING = 1, ERROR = 2 }
Public Member Functions
TpotMon (const std::string &name)
~TpotMon () override=default
int process_event (Event *evt) override
int Init () override
int BeginRun (const int runno) override
int Reset () override
void set_calibration_file (const std::string &value)
calibration file
void set_max_sample (int value)
max sample
void set_n_sigma (double value)
set number of RMS sigma used to defined static threshold on a given channel
void set_min_adc (double value)
set minimum ADC value, disregarding pedestal and RMS. This removes channels for which calibration has failed
void set_sample_window_signal (const sample_window_t &value)
Public Member Functions inherited from OnlMon
OnlMon (const std::string &name="NONE")
~OnlMon () override
virtual int process_event_common (Event *evt)
virtual int InitCommon (OnlMonServer *se)
virtual void identify (std::ostream &out=std::cout) const
virtual int BeginRunCommon (const int runno, OnlMonServer *se)
virtual int EndRun (const int)
virtual void SetStatus (const int newstatus)
virtual int ResetEvent ()
virtual void SetMonitorServerId (unsigned int i)
virtual unsigned int MonitorServerId () const
Public Member Functions inherited from OnlMonBase
OnlMonBase (const std::string &name="NONE")
virtual ~OnlMonBase ()
const std::string Name () const
void Name (const std::string &name)
virtual void Verbosity (const int i)
virtual int Verbosity () const
Private Member Functions
void setup_detector_bins (TH2Poly *)
setup bins in a TH2Poly. One bin per detector
void setup_resist_bins (TH2Poly *, MicromegasDefs::SegmentationType)
setup bins in TH2Poly, one bin per Resist sector
Private Attributes
int m_evtcnt = 0
keep track of number of events
double m_fullevtcnt = 0
keep track of number of 'full' triggers
MicromegasMapping m_mapping
mapping
MicromegasGeometry m_geometry
geometry
std::string m_calibration_filename
calibration filename
MicromegasCalibrationData m_calibration_data
calibration data
int m_max_sample = 100
max sample
sample_window_t m_sample_window_signal = {20, 40}
double m_n_sigma = 5
number of RMS sigma used to define threshold
double m_min_adc = 50
minimum ADC value, disregarding pedestal and RMS. This removes channels for which calibration has failed
TH1 * m_counters = nullptr
counter
TH2Poly * m_detector_multiplicity_z = nullptr
TPOT per/detector multiplicity.
TH2Poly * m_detector_multiplicity_phi = nullptr
TH2Poly * m_detector_occupancy_z = nullptr
TPOT per/detector occupancy.
TH2Poly * m_detector_occupancy_phi = nullptr
TH2Poly * m_resist_multiplicity_z = nullptr
TPOT per/detector multiplicity.
TH2Poly * m_resist_multiplicity_phi = nullptr
TH2Poly * m_resist_occupancy_z = nullptr
TPOT per/detector occupancy.
TH2Poly * m_resist_occupancy_phi = nullptr
std::map< int,
MicromegasGeometry::point_t > m_tile_centers
std::map< int,
detector_histograms_t > m_detector_histograms
Additional Inherited Members
Protected Attributes inherited from OnlMon
int status
unsigned int m_MonitorServerId = 0
TH1 * m_LocalFrameWorkVars = nullptr
Detailed Description
Definition at line 19 of file TpotMon.h.
View newest version in sPHENIX GitHub at line 19 of file TpotMon.h
Member Typedef Documentation
using TpotMon::sample_window_t = std::pair<int, int>
Definition at line 45 of file TpotMon.h.
View newest version in sPHENIX GitHub at line 45 of file TpotMon.h
Constructor & Destructor Documentation
TpotMon::TpotMon (const std::string & name)
Definition at line 49 of file TpotMon.cc.
View newest version in sPHENIX GitHub at line 49 of file TpotMon.cc
References m_calibration_filename.
TpotMon::~TpotMon () override default
Member Function Documentation
int TpotMon::BeginRun (const int runno) override virtual
Reimplemented from OnlMon.
Definition at line 209 of file TpotMon.cc.
View newest version in sPHENIX GitHub at line 209 of file TpotMon.cc
int TpotMon::Init () override virtual
Reimplemented from OnlMon.
Definition at line 65 of file TpotMon.cc.
View newest version in sPHENIX GitHub at line 65 of file TpotMon.cc
References MicromegasMapping::get_detname_sphenix(), MicromegasMapping::get_fee_id_list(), MicromegasMapping::get_hitsetkey(), MicromegasGeometry::get_tile_center(), MicromegasDefs::getTileId(), h, OnlMonServer::instance(), TpotMonDefs::kEventCounter, TpotMonDefs::kFullEventCounter, TpotMonDefs::kValidEventCounter, TpotMon::detector_histograms_t::m_adc_sample, m_calibration_data, m_calibration_filename, m_counters, TpotMon::detector_histograms_t::m_counts_sample, m_detector_histograms, m_detector_multiplicity_phi, m_detector_multiplicity_z, m_detector_occupancy_phi, m_detector_occupancy_z, m_geometry, TpotMon::detector_histograms_t::m_hit_charge, TpotMon::detector_histograms_t::m_hit_multiplicity, TpotMon::detector_histograms_t::m_hit_vs_channel, m_mapping, m_max_sample, m_resist_multiplicity_phi, m_resist_multiplicity_z, m_resist_occupancy_phi, m_resist_occupancy_z, m_tile_centers, testing::internal::move(), MicromegasCalibrationData::read(), Reset(), PHG4InttDefs::SEGMENTATION_PHI, PHG4InttDefs::SEGMENTATION_Z, setup_detector_bins(), setup_resist_bins(), and OnlMonBase::Verbosity().
int TpotMon::process_event (Event * evt) override virtual
Reimplemented from OnlMon.
Definition at line 217 of file TpotMon.cc.
View newest version in sPHENIX GitHub at line 217 of file TpotMon.cc
References channel(), double(), MicromegasMapping::get_hitsetkey(), MicromegasCalibrationData::get_pedestal(), MicromegasMapping::get_physical_strip(), MicromegasCalibrationData::get_rms(), Event::getEvtType(), Event::getPacket(), MicromegasDefs::getSegmentationType(), h, i, TpotMonDefs::kEventCounter, TpotMonDefs::kFullEventCounter, TpotMonDefs::kValidEventCounter, m_calibration_data, m_counters, m_detector_histograms, m_detector_multiplicity_phi, m_detector_multiplicity_z, m_detector_occupancy_phi, m_detector_occupancy_z, m_evtcnt, m_fullevtcnt, m_mapping, m_min_adc, m_n_sigma, MicromegasDefs::m_nchannels_fee, MicromegasDefs::m_nchannels_total, MicromegasDefs::m_packet_ids, m_resist_multiplicity_phi, m_resist_multiplicity_z, m_resist_occupancy_phi, m_resist_occupancy_z, m_sample_window_signal, m_tile_centers, MicromegasGeometry::m_tile_length, MicromegasGeometry::m_tile_width, full_chain_odd::multiplicity, pedestal(), rms(), PHG4InttDefs::SEGMENTATION_PHI, PHG4InttDefs::SEGMENTATION_Z, parse_cmake_options::source, and OnlMonBase::Verbosity().
int TpotMon::Reset () override virtual
Reimplemented from OnlMon.
Definition at line 369 of file TpotMon.cc.
View newest version in sPHENIX GitHub at line 369 of file TpotMon.cc
References h, m_detector_histograms, m_detector_multiplicity_phi, m_detector_multiplicity_z, m_detector_occupancy_phi, m_detector_occupancy_z, m_evtcnt, m_fullevtcnt, m_resist_multiplicity_phi, m_resist_multiplicity_z, m_resist_occupancy_phi, and m_resist_occupancy_z.
Referenced by Init().
void TpotMon::set_calibration_file (const std::string & value) inline
calibration file
Definition at line 31 of file TpotMon.h.
View newest version in sPHENIX GitHub at line 31 of file TpotMon.h
References m_calibration_filename, and value.
void TpotMon::set_max_sample (int value) inline
max sample
Definition at line 35 of file TpotMon.h.
View newest version in sPHENIX GitHub at line 35 of file TpotMon.h
References m_max_sample, and value.
void TpotMon::set_min_adc (double value) inline
set minimum ADC value, disregarding pedestal and RMS. This removes channels for which calibration has failed
Definition at line 42 of file TpotMon.h.
View newest version in sPHENIX GitHub at line 42 of file TpotMon.h
References m_min_adc, and value.
void TpotMon::set_n_sigma (double value) inline
set number of RMS sigma used to defined static threshold on a given channel
Definition at line 39 of file TpotMon.h.
View newest version in sPHENIX GitHub at line 39 of file TpotMon.h
References m_n_sigma, and value.
void TpotMon::set_sample_window_signal (const sample_window_t & value) inline
Definition at line 46 of file TpotMon.h.
View newest version in sPHENIX GitHub at line 46 of file TpotMon.h
References m_sample_window_signal, and value.
void TpotMon::setup_detector_bins (TH2Poly * h2) private
setup bins in a TH2Poly. One bin per detector
Definition at line 393 of file TpotMon.cc.
View newest version in sPHENIX GitHub at line 393 of file TpotMon.cc
References MicromegasGeometry::get_ntiles(), MicromegasGeometry::get_tile_boundaries(), i, and m_geometry.
Referenced by Init().
void TpotMon::setup_resist_bins (TH2Poly * h2, MicromegasDefs::SegmentationType segmentation) private
setup bins in TH2Poly, one bin per Resist sector
Definition at line 404 of file TpotMon.cc.
View newest version in sPHENIX GitHub at line 404 of file TpotMon.cc
References MicromegasGeometry::get_ntiles(), MicromegasGeometry::get_resist_boundaries(), m_geometry, and MicromegasGeometry::m_nresist.
Referenced by Init().
Member Data Documentation
MicromegasCalibrationData TpotMon::m_calibration_data private
calibration data
Definition at line 77 of file TpotMon.h.
View newest version in sPHENIX GitHub at line 77 of file TpotMon.h
Referenced by Init(), and process_event().
std::string TpotMon::m_calibration_filename private
calibration filename
Definition at line 74 of file TpotMon.h.
View newest version in sPHENIX GitHub at line 74 of file TpotMon.h
Referenced by Init(), set_calibration_file(), and TpotMon().
TH1* TpotMon::m_counters = nullptr private
counter
Definition at line 92 of file TpotMon.h.
View newest version in sPHENIX GitHub at line 92 of file TpotMon.h
Referenced by Init(), and process_event().
std::map<int, detector_histograms_t> TpotMon::m_detector_histograms private
Definition at line 137 of file TpotMon.h.
View newest version in sPHENIX GitHub at line 137 of file TpotMon.h
Referenced by Init(), process_event(), and Reset().
TH2Poly* TpotMon::m_detector_multiplicity_phi = nullptr private
Definition at line 96 of file TpotMon.h.
View newest version in sPHENIX GitHub at line 96 of file TpotMon.h
Referenced by Init(), process_event(), and Reset().
TH2Poly* TpotMon::m_detector_multiplicity_z = nullptr private
TPOT per/detector multiplicity.
Definition at line 95 of file TpotMon.h.
View newest version in sPHENIX GitHub at line 95 of file TpotMon.h
Referenced by Init(), process_event(), and Reset().
TH2Poly* TpotMon::m_detector_occupancy_phi = nullptr private
Definition at line 100 of file TpotMon.h.
View newest version in sPHENIX GitHub at line 100 of file TpotMon.h
Referenced by Init(), process_event(), and Reset().
TH2Poly* TpotMon::m_detector_occupancy_z = nullptr private
TPOT per/detector occupancy.
Definition at line 99 of file TpotMon.h.
View newest version in sPHENIX GitHub at line 99 of file TpotMon.h
Referenced by Init(), process_event(), and Reset().
int TpotMon::m_evtcnt = 0 private
keep track of number of events
Definition at line 58 of file TpotMon.h.
View newest version in sPHENIX GitHub at line 58 of file TpotMon.h
Referenced by process_event(), and Reset().
double TpotMon::m_fullevtcnt = 0 private
keep track of number of 'full' triggers
Definition at line 65 of file TpotMon.h.
View newest version in sPHENIX GitHub at line 65 of file TpotMon.h
Referenced by process_event(), and Reset().
MicromegasGeometry TpotMon::m_geometry private
geometry
Definition at line 71 of file TpotMon.h.
View newest version in sPHENIX GitHub at line 71 of file TpotMon.h
Referenced by Init(), setup_detector_bins(), and setup_resist_bins().
MicromegasMapping TpotMon::m_mapping private
mapping
Definition at line 68 of file TpotMon.h.
View newest version in sPHENIX GitHub at line 68 of file TpotMon.h
Referenced by Init(), and process_event().
int TpotMon::m_max_sample = 100 private
max sample
Definition at line 80 of file TpotMon.h.
View newest version in sPHENIX GitHub at line 80 of file TpotMon.h
Referenced by Init(), and set_max_sample().
double TpotMon::m_min_adc = 50 private
minimum ADC value, disregarding pedestal and RMS. This removes channels for which calibration has failed
Definition at line 89 of file TpotMon.h.
View newest version in sPHENIX GitHub at line 89 of file TpotMon.h
Referenced by process_event(), and set_min_adc().
double TpotMon::m_n_sigma = 5 private
number of RMS sigma used to define threshold
Definition at line 86 of file TpotMon.h.
View newest version in sPHENIX GitHub at line 86 of file TpotMon.h
Referenced by process_event(), and set_n_sigma().
TH2Poly* TpotMon::m_resist_multiplicity_phi = nullptr private
Definition at line 104 of file TpotMon.h.
View newest version in sPHENIX GitHub at line 104 of file TpotMon.h
Referenced by Init(), process_event(), and Reset().
TH2Poly* TpotMon::m_resist_multiplicity_z = nullptr private
TPOT per/detector multiplicity.
Definition at line 103 of file TpotMon.h.
View newest version in sPHENIX GitHub at line 103 of file TpotMon.h
Referenced by Init(), process_event(), and Reset().
TH2Poly* TpotMon::m_resist_occupancy_phi = nullptr private
Definition at line 108 of file TpotMon.h.
View newest version in sPHENIX GitHub at line 108 of file TpotMon.h
Referenced by Init(), process_event(), and Reset().
TH2Poly* TpotMon::m_resist_occupancy_z = nullptr private
TPOT per/detector occupancy.
Definition at line 107 of file TpotMon.h.
View newest version in sPHENIX GitHub at line 107 of file TpotMon.h
Referenced by Init(), process_event(), and Reset().
sample_window_t TpotMon::m_sample_window_signal = {20, 40} private
Definition at line 83 of file TpotMon.h.
View newest version in sPHENIX GitHub at line 83 of file TpotMon.h
Referenced by process_event(), and set_sample_window_signal().
std::map<int, MicromegasGeometry::point_t> TpotMon::m_tile_centers private
Definition at line 134 of file TpotMon.h.
View newest version in sPHENIX GitHub at line 134 of file TpotMon.h
Referenced by Init(), and process_event().
The documentation for this class was generated from the following files:
OnlMon/blob/main/subsystems/tpot/TpotMon.h
OnlMon/blob/main/subsystems/tpot/TpotMon.cc