Analysis Software: MakeSourceLinks Class Reference
MakeSourceLinks Class Reference
#include <coresoftware/blob/master/offline/packages/trackreco/MakeSourceLinks.h>
Public Member Functions
MakeSourceLinks ()=default
void setVerbosity (int verbosity)
void set_pp_mode (bool ispp)
void ignoreLayer (int layer)
SourceLinkVec getSourceLinks (TrackSeed *track, ActsTrackFittingAlgorithm::MeasurementContainer &measurements, TrkrClusterContainer *cluster_container, ActsGeometry *tGeometry, alignmentTransformationContainer *transformMapTransient, std::set< Acts::GeometryIdentifier > transient_id_set, short int crossing)
void resetTransientTransformMap (alignmentTransformationContainer *transformMapTransient, std::set< Acts::GeometryIdentifier > &transient_id_set, ActsGeometry *tGeometry)
Private Attributes
int m_verbosity = 0
bool m_pp_mode = false
std::set< int > m_ignoreLayer
TpcClusterZCrossingCorrection _clusterCrossingCorrection
TpcDistortionCorrectionContainer * _dcc_static {nullptr}
TpcDistortionCorrectionContainer * _dcc_average {nullptr}
TpcDistortionCorrectionContainer * _dcc_fluctuation {nullptr}
TpcDistortionCorrection _distortionCorrection
tpc distortion correction utility class
ClusterErrorPara _ClusErrPara
Detailed Description
This class contains the code that generates Acts source links and makes the modified GeoContext that applies cluster crossing and distortion corrections in the alignment transformations. It is used by all of the Acts track fitting modules.
Definition at line 41 of file MakeSourceLinks.h.
View newest version in sPHENIX GitHub at line 41 of file MakeSourceLinks.h
Constructor & Destructor Documentation
MakeSourceLinks::MakeSourceLinks () default
Member Function Documentation
SourceLinkVec MakeSourceLinks::getSourceLinks (TrackSeed * track, ActsTrackFittingAlgorithm::MeasurementContainer & measurements, TrkrClusterContainer * cluster_container, ActsGeometry * tGeometry, alignmentTransformationContainer * transformMapTransient, std::set< Acts::GeometryIdentifier > transient_id_set, short int crossing)
Make a safety check for clusters that couldn't be attached to a surface
Definition at line 36 of file MakeSourceLinks.cc.
View newest version in sPHENIX GitHub at line 36 of file MakeSourceLinks.cc
References _ClusErrPara, _clusterCrossingCorrection, _dcc_average, _dcc_fluctuation, _dcc_static, _distortionCorrection, TrackSeed::begin_cluster_keys(), Acts::UnitConstants::cm, Acts::UnitConstants::cm2, TpcClusterZCrossingCorrection::correctZ(), Acts::Test::cov, Acts::eBoundLoc0, Acts::eBoundLoc1, TrackSeed::end_cluster_keys(), TrkrClusterContainer::findCluster(), ActsGeometry::geometry(), PHTimer::get_accumulated_time(), ClusterErrorPara::get_clusterv5_modified_error(), TpcDistortionCorrection::get_corrected_position(), ActsTrackingGeometry::getGeoContext(), ActsGeometry::getGlobalPosition(), TrkrDefs::getLayer(), ActsGeometry::getLocalCoords(), TpcDefs::getSide(), ActsSurfaceMaps::getSurface(), alignmentTransformationContainer::getTransform(), TrkrDefs::getTrkrId(), i, index, loc, m_ignoreLayer, m_pp_mode, m_verbosity, ActsGeometry::makeAffineTransform(), ActsGeometry::maps(), PHWHERE, alignmentTransformationContainer::replaceTransform(), PHTimer::restart(), PHTimer::stop(), surf(), TrkrDefs::tpcId, and physmon_track_finding_ttbar::z.
Referenced by PHCosmicsTrkFitter::loopTracks(), PHActsTrkFitter::loopTracks(), and PHActsGSF::process_event().
void MakeSourceLinks::ignoreLayer (int layer) inline
Definition at line 50 of file MakeSourceLinks.h.
View newest version in sPHENIX GitHub at line 50 of file MakeSourceLinks.h
References m_ignoreLayer.
void MakeSourceLinks::resetTransientTransformMap (alignmentTransformationContainer * transformMapTransient, std::set< Acts::GeometryIdentifier > & transient_id_set, ActsGeometry * tGeometry)
Definition at line 210 of file MakeSourceLinks.cc.
View newest version in sPHENIX GitHub at line 210 of file MakeSourceLinks.cc
References ActsGeometry::geometry(), ActsTrackingGeometry::getGeoContext(), alignmentTransformationContainer::getTransform(), it, alignmentTransformationContainer::replaceTransform(), and Acts::Test::transform.
Referenced by PHCosmicsTrkFitter::loopTracks(), PHActsTrkFitter::loopTracks(), and PHActsGSF::process_event().
void MakeSourceLinks::set_pp_mode (bool ispp) inline
Definition at line 48 of file MakeSourceLinks.h.
View newest version in sPHENIX GitHub at line 48 of file MakeSourceLinks.h
References m_pp_mode.
Referenced by PHCosmicsTrkFitter::loopTracks(), PHActsTrkFitter::loopTracks(), and PHActsGSF::process_event().
void MakeSourceLinks::setVerbosity (int verbosity) inline
Definition at line 46 of file MakeSourceLinks.h.
View newest version in sPHENIX GitHub at line 46 of file MakeSourceLinks.h
References m_verbosity, and verbosity.
Referenced by PHCosmicsTrkFitter::loopTracks(), PHActsTrkFitter::loopTracks(), and PHActsGSF::process_event().
Member Data Documentation
ClusterErrorPara MakeSourceLinks::_ClusErrPara private
Definition at line 78 of file MakeSourceLinks.h.
View newest version in sPHENIX GitHub at line 78 of file MakeSourceLinks.h
Referenced by getSourceLinks().
TpcClusterZCrossingCorrection MakeSourceLinks::_clusterCrossingCorrection private
Definition at line 70 of file MakeSourceLinks.h.
View newest version in sPHENIX GitHub at line 70 of file MakeSourceLinks.h
Referenced by getSourceLinks().
TpcDistortionCorrectionContainer* MakeSourceLinks::_dcc_average {nullptr} private
Definition at line 72 of file MakeSourceLinks.h.
View newest version in sPHENIX GitHub at line 72 of file MakeSourceLinks.h
Referenced by getSourceLinks().
TpcDistortionCorrectionContainer* MakeSourceLinks::_dcc_fluctuation {nullptr} private
Definition at line 73 of file MakeSourceLinks.h.
View newest version in sPHENIX GitHub at line 73 of file MakeSourceLinks.h
Referenced by getSourceLinks().
TpcDistortionCorrectionContainer* MakeSourceLinks::_dcc_static {nullptr} private
Definition at line 71 of file MakeSourceLinks.h.
View newest version in sPHENIX GitHub at line 71 of file MakeSourceLinks.h
Referenced by getSourceLinks().
TpcDistortionCorrection MakeSourceLinks::_distortionCorrection private
tpc distortion correction utility class
Definition at line 76 of file MakeSourceLinks.h.
View newest version in sPHENIX GitHub at line 76 of file MakeSourceLinks.h
Referenced by getSourceLinks().
std::set<int> MakeSourceLinks::m_ignoreLayer private
Definition at line 68 of file MakeSourceLinks.h.
View newest version in sPHENIX GitHub at line 68 of file MakeSourceLinks.h
Referenced by getSourceLinks(), and ignoreLayer().
bool MakeSourceLinks::m_pp_mode = false private
Definition at line 67 of file MakeSourceLinks.h.
View newest version in sPHENIX GitHub at line 67 of file MakeSourceLinks.h
Referenced by getSourceLinks(), and set_pp_mode().
int MakeSourceLinks::m_verbosity = 0 private
Definition at line 66 of file MakeSourceLinks.h.
View newest version in sPHENIX GitHub at line 66 of file MakeSourceLinks.h
Referenced by getSourceLinks(), and setVerbosity().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/trackreco/MakeSourceLinks.h
coresoftware/blob/master/offline/packages/trackreco/MakeSourceLinks.cc