Analysis Software: intt_pool Class Reference
intt_pool Class Reference
#include <coresoftware/blob/master/offline/framework/fun4allraw/intt_pool.h>
Classes
struct intt_hit
Public Member Functions
intt_pool (const unsigned int required_depth=1000, const unsigned int low_mark=100)
virtual ~intt_pool ()
virtual int addPacket (Packet *p)
virtual void drain ()
virtual unsigned int rawValue (const int fee, const int index)
virtual int iValue (const int hit, const int field)
virtual int iValue (const int hit, const char *what)
virtual long long lValue (const int hit, const int field)
virtual long long lValue (const int hit, const char *what)
virtual unsigned int min_depth () const
virtual bool depth_ok () const
virtual int next ()
virtual void dump (OSTREAM &os=std::cout)
virtual int getIdentifier () const
void Verbosity (const int i)
void Name (const std::string &n)
std::string Name () const
Protected Member Functions
int intt_decode ()
int intt_decode_hitlist (std::vector< unsigned int > &, const int)
Protected Attributes
int verbosity {0}
int _is_decoded {0}
unsigned int _required_depth
unsigned int _low_mark
int _myPacketid {-1}
std::vector< unsigned int > fee_data [MAX_FEECOUNT]
std::vector< intt_hit * > intt_hits
std::array< unsigned int,
MAX_FEECOUNT > last_index
std::map< unsigned int, uint64_t > last_bco
std::string name
Static Protected Attributes
static const int MAX_FEECOUNT {16}
Detailed Description
Definition at line 16 of file intt_pool.h.
View newest version in sPHENIX GitHub at line 16 of file intt_pool.h
Constructor & Destructor Documentation
intt_pool::intt_pool (const unsigned int required_depth = 1000, const unsigned int low_mark = 100)
Definition at line 27 of file intt_pool.cc.
View newest version in sPHENIX GitHub at line 27 of file intt_pool.cc
References depth.
virtual intt_pool::~intt_pool () inline virtual
Definition at line 21 of file intt_pool.h.
View newest version in sPHENIX GitHub at line 21 of file intt_pool.h
Member Function Documentation
int intt_pool::addPacket (Packet * p) virtual
Definition at line 38 of file intt_pool.cc.
View newest version in sPHENIX GitHub at line 38 of file intt_pool.cc
References cerrfl, Packet::getIdentifier(), i, and Packet::iValue().
bool intt_pool::depth_ok () const virtual
Definition at line 244 of file intt_pool.cc.
View newest version in sPHENIX GitHub at line 244 of file intt_pool.cc
References verbosity.
Referenced by SingleInttPoolInput::FillPool().
virtual void intt_pool::drain () inline virtual
Definition at line 25 of file intt_pool.h.
View newest version in sPHENIX GitHub at line 25 of file intt_pool.h
References _low_mark.
void intt_pool::dump (OSTREAM & os = std::cout) virtual
Definition at line 603 of file intt_pool.cc.
View newest version in sPHENIX GitHub at line 603 of file intt_pool.cc
References F_ADC, F_AMPLITUDE, F_BCO, F_CHANNEL_ID, F_CHIP_ID, F_DATAWORD, F_FEE, F_FPHX_BCO, F_FULL_FPHX, F_FULL_ROC, and i.
virtual int intt_pool::getIdentifier () const inline virtual
Definition at line 43 of file intt_pool.h.
View newest version in sPHENIX GitHub at line 43 of file intt_pool.h
References _myPacketid.
Referenced by SingleInttPoolInput::FillPool().
int intt_pool::intt_decode () protected
Definition at line 273 of file intt_pool.cc.
View newest version in sPHENIX GitHub at line 273 of file intt_pool.cc
References parse_cmake_options::begin, coutfl, j, k, and size.
int intt_pool::intt_decode_hitlist (std::vector< unsigned int > & hitlist, const int fee) protected
Definition at line 538 of file intt_pool.cc.
View newest version in sPHENIX GitHub at line 538 of file intt_pool.cc
References intt_pool::intt_hit::adc, intt_pool::intt_hit::amplitude, BCO, intt_pool::intt_hit::bco, intt_pool::intt_hit::channel_id, intt_pool::intt_hit::chip_id, test_fpe::count, coutfl, intt_pool::intt_hit::event_counter, intt_pool::intt_hit::fee, intt_pool::intt_hit::FPHX_BCO, intt_pool::intt_hit::full_FPHX, intt_pool::intt_hit::full_ROC, i, verbosity, intt_pool::intt_hit::word, and ambiguity_solver_full_chain::x.
int intt_pool::iValue (const int hit, const int field) virtual
Definition at line 195 of file intt_pool.cc.
View newest version in sPHENIX GitHub at line 195 of file intt_pool.cc
References F_ADC, F_AMPLITUDE, F_CHANNEL_ID, F_CHIP_ID, F_DATAWORD, F_FEE, F_FPHX_BCO, F_FULL_FPHX, and F_FULL_ROC.
Referenced by SingleInttPoolInput::FillPool().
int intt_pool::iValue (const int hit, const char * what) virtual
Definition at line 83 of file intt_pool.cc.
View newest version in sPHENIX GitHub at line 83 of file intt_pool.cc
References F_ADC, F_AMPLITUDE, F_CHANNEL_ID, F_CHIP_ID, F_DATAWORD, F_FEE, F_FPHX_BCO, F_FULL_FPHX, and F_FULL_ROC.
long long intt_pool::lValue (const int hit, const int field) virtual
Definition at line 155 of file intt_pool.cc.
View newest version in sPHENIX GitHub at line 155 of file intt_pool.cc
References F_BCO.
Referenced by SingleInttPoolInput::FillPool().
long long intt_pool::lValue (const int hit, const char * what) virtual
Definition at line 170 of file intt_pool.cc.
View newest version in sPHENIX GitHub at line 170 of file intt_pool.cc
References F_BCO.
unsigned int intt_pool::min_depth () const virtual
Definition at line 183 of file intt_pool.cc.
View newest version in sPHENIX GitHub at line 183 of file intt_pool.cc
References size.
void intt_pool::Name (const std::string & n) inline
Definition at line 48 of file intt_pool.h.
View newest version in sPHENIX GitHub at line 48 of file intt_pool.h
References n, and name.
std::string intt_pool::Name () const inline
Definition at line 49 of file intt_pool.h.
View newest version in sPHENIX GitHub at line 49 of file intt_pool.h
References name.
int intt_pool::next () virtual
Definition at line 255 of file intt_pool.cc.
View newest version in sPHENIX GitHub at line 255 of file intt_pool.cc
Referenced by SingleInttPoolInput::FillPool().
unsigned int intt_pool::rawValue (const int fee, const int index) virtual
Definition at line 76 of file intt_pool.cc.
View newest version in sPHENIX GitHub at line 76 of file intt_pool.cc
References index, and size.
void intt_pool::Verbosity (const int i) inline
Definition at line 47 of file intt_pool.h.
View newest version in sPHENIX GitHub at line 47 of file intt_pool.h
References i, and verbosity.
Member Data Documentation
int intt_pool::_is_decoded {0} protected
Definition at line 60 of file intt_pool.h.
View newest version in sPHENIX GitHub at line 60 of file intt_pool.h
unsigned int intt_pool::_low_mark protected
Definition at line 63 of file intt_pool.h.
View newest version in sPHENIX GitHub at line 63 of file intt_pool.h
Referenced by drain().
int intt_pool::_myPacketid {-1} protected
Definition at line 64 of file intt_pool.h.
View newest version in sPHENIX GitHub at line 64 of file intt_pool.h
Referenced by getIdentifier().
unsigned int intt_pool::_required_depth protected
Definition at line 62 of file intt_pool.h.
View newest version in sPHENIX GitHub at line 62 of file intt_pool.h
std::vector<unsigned int> intt_pool::fee_data[MAX_FEECOUNT] protected
Definition at line 83 of file intt_pool.h.
View newest version in sPHENIX GitHub at line 83 of file intt_pool.h
std::vector<intt_hit *> intt_pool::intt_hits protected
Definition at line 84 of file intt_pool.h.
View newest version in sPHENIX GitHub at line 84 of file intt_pool.h
std::map<unsigned int, uint64_t> intt_pool::last_bco protected
Definition at line 87 of file intt_pool.h.
View newest version in sPHENIX GitHub at line 87 of file intt_pool.h
std::array<unsigned int,MAX_FEECOUNT> intt_pool::last_index protected
Definition at line 86 of file intt_pool.h.
View newest version in sPHENIX GitHub at line 86 of file intt_pool.h
const int intt_pool::MAX_FEECOUNT {16} static protected
Definition at line 57 of file intt_pool.h.
View newest version in sPHENIX GitHub at line 57 of file intt_pool.h
std::string intt_pool::name protected
Definition at line 88 of file intt_pool.h.
View newest version in sPHENIX GitHub at line 88 of file intt_pool.h
Referenced by cpp.tokenize.Token::__str__(), cpp.ast.Define::__str__(), cpp.ast.Parameter::__str__(), cpp.ast.Typedef::__str__(), cpp.ast._NestedType::__str__(), cpp.ast.Class::__str__(), cpp.ast.Function::__str__(), cpp.ast.Type::__str__(), cpp.ast._GenericDeclaration::FullName(), Name(), and cpp.ast.VariableDeclaration::ToString().
int intt_pool::verbosity {0} protected
Definition at line 59 of file intt_pool.h.
View newest version in sPHENIX GitHub at line 59 of file intt_pool.h
Referenced by Verbosity().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/framework/fun4allraw/intt_pool.h
coresoftware/blob/master/offline/framework/fun4allraw/intt_pool.cc