Analysis Software: EventplaneinfoMapv1 Class Reference
EventplaneinfoMapv1 Class Reference
#include <coresoftware/blob/master/offline/packages/eventplaneinfo/EventplaneinfoMapv1.h>
Public Member Functions
EventplaneinfoMapv1 ()=default
~EventplaneinfoMapv1 () override
void identify (std::ostream &os=std::cout) const override
void Reset () override
Clear Event.
void clear () override
const Eventplaneinfo * get (unsigned int idkey) const override
Eventplaneinfo * get (unsigned int idkey) override
Eventplaneinfo * insert (Eventplaneinfo *ep, EPTYPE type) override
ConstIter begin () const override
ConstIter find (unsigned int idkey) const override
ConstIter end () const override
Iter begin () override
Iter find (unsigned int idkey) override
Iter end () override
Public Member Functions inherited from EventplaneinfoMap
~EventplaneinfoMap () override
Public Member Functions inherited from PHObject
PHObject ()
ctor
~PHObject () override
dtor
virtual PHObject * CloneMe () const
Virtual copy constructor.
virtual PHObject * clone () const final
PHObject * Clone (const char *newname="") const final
void Copy (TObject &object) const final
virtual int isValid () const
isValid returns non zero if object contains vailid data
virtual int Integrate () const
virtual int Integrate (PHObject *)
virtual void CopyFrom (const PHObject *obj)
Private Member Functions
ClassDefOverride (EventplaneinfoMapv1, 1)
Private Attributes
std::map< unsigned int,
Eventplaneinfo * > _map
Additional Inherited Members
Public Types inherited from EventplaneinfoMap
enum EPTYPE {
UNDEFINED = 999, sEPDS = 0, sEPDN = 1, MBDS = 2,
MBDN = 3
}
typedef std::map< unsigned int,
Eventplaneinfo * >
::const_iterator ConstIter
typedef std::map< unsigned int,
Eventplaneinfo * >::iterator Iter
Protected Member Functions inherited from EventplaneinfoMap
EventplaneinfoMap ()
Detailed Description
Definition at line 13 of file EventplaneinfoMapv1.h.
View newest version in sPHENIX GitHub at line 13 of file EventplaneinfoMapv1.h
Constructor & Destructor Documentation
EventplaneinfoMapv1::EventplaneinfoMapv1 () default
EventplaneinfoMapv1::~EventplaneinfoMapv1 () override
Definition at line 9 of file EventplaneinfoMapv1.cc.
View newest version in sPHENIX GitHub at line 9 of file EventplaneinfoMapv1.cc
References clear().
Member Function Documentation
ConstIter EventplaneinfoMapv1::begin (void) const inline override virtual
Reimplemented from EventplaneinfoMap.
Definition at line 28 of file EventplaneinfoMapv1.h.
View newest version in sPHENIX GitHub at line 28 of file EventplaneinfoMapv1.h
References _map.
Iter EventplaneinfoMapv1::begin (void) inline override virtual
Reimplemented from EventplaneinfoMap.
Definition at line 32 of file EventplaneinfoMapv1.h.
View newest version in sPHENIX GitHub at line 32 of file EventplaneinfoMapv1.h
References _map.
EventplaneinfoMapv1::ClassDefOverride (EventplaneinfoMapv1 , 1) private
void EventplaneinfoMapv1::clear () override virtual
Reimplemented from EventplaneinfoMap.
Definition at line 24 of file EventplaneinfoMapv1.cc.
View newest version in sPHENIX GitHub at line 24 of file EventplaneinfoMapv1.cc
References _map.
Referenced by Reset(), and ~EventplaneinfoMapv1().
ConstIter EventplaneinfoMapv1::end (void) const inline override virtual
Reimplemented from EventplaneinfoMap.
Definition at line 30 of file EventplaneinfoMapv1.h.
View newest version in sPHENIX GitHub at line 30 of file EventplaneinfoMapv1.h
References _map.
Iter EventplaneinfoMapv1::end (void) inline override virtual
Reimplemented from EventplaneinfoMap.
Definition at line 34 of file EventplaneinfoMapv1.h.
View newest version in sPHENIX GitHub at line 34 of file EventplaneinfoMapv1.h
References _map.
ConstIter EventplaneinfoMapv1::find (unsigned int idkey) const inline override virtual
Reimplemented from EventplaneinfoMap.
Definition at line 29 of file EventplaneinfoMapv1.h.
View newest version in sPHENIX GitHub at line 29 of file EventplaneinfoMapv1.h
References _map.
Iter EventplaneinfoMapv1::find (unsigned int idkey) inline override virtual
Reimplemented from EventplaneinfoMap.
Definition at line 33 of file EventplaneinfoMapv1.h.
View newest version in sPHENIX GitHub at line 33 of file EventplaneinfoMapv1.h
References _map.
const Eventplaneinfo * EventplaneinfoMapv1::get (unsigned int idkey) const override virtual
Reimplemented from EventplaneinfoMap.
Definition at line 34 of file EventplaneinfoMapv1.cc.
View newest version in sPHENIX GitHub at line 34 of file EventplaneinfoMapv1.cc
References _map.
Eventplaneinfo * EventplaneinfoMapv1::get (unsigned int idkey) override virtual
Reimplemented from EventplaneinfoMap.
Definition at line 44 of file EventplaneinfoMapv1.cc.
View newest version in sPHENIX GitHub at line 44 of file EventplaneinfoMapv1.cc
References _map.
void EventplaneinfoMapv1::identify (std::ostream & os = std::cout) const override virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from EventplaneinfoMap.
Definition at line 14 of file EventplaneinfoMapv1.cc.
View newest version in sPHENIX GitHub at line 14 of file EventplaneinfoMapv1.cc
References _map, and Acts::UnitConstants::m.
Eventplaneinfo * EventplaneinfoMapv1::insert (Eventplaneinfo * ep, const EventplaneinfoMap::EPTYPE id) override virtual
Reimplemented from EventplaneinfoMap.
Definition at line 54 of file EventplaneinfoMapv1.cc.
View newest version in sPHENIX GitHub at line 54 of file EventplaneinfoMapv1.cc
References _map.
void EventplaneinfoMapv1::Reset () inline override virtual
Clear Event.
Reimplemented from PHObject.
Definition at line 20 of file EventplaneinfoMapv1.h.
View newest version in sPHENIX GitHub at line 20 of file EventplaneinfoMapv1.h
References clear().
Member Data Documentation
std::map<unsigned int, Eventplaneinfo*> EventplaneinfoMapv1::_map private
Definition at line 37 of file EventplaneinfoMapv1.h.
View newest version in sPHENIX GitHub at line 37 of file EventplaneinfoMapv1.h
Referenced by begin(), clear(), end(), find(), get(), identify(), and insert().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/eventplaneinfo/EventplaneinfoMapv1.h
coresoftware/blob/master/offline/packages/eventplaneinfo/EventplaneinfoMapv1.cc