Analysis Software: Acts::MutablePodioTrackStateContainer Exception Reference
Acts::MutablePodioTrackStateContainer Exception Reference final
#include <acts/blob/sPHENIX/Plugins/Podio/include/Acts/Plugins/Podio/PodioTrackStateContainer.hpp>
Public Member Functions
MutablePodioTrackStateContainer (PodioUtil::ConversionHelper &helper)
populateSurfaceBuffer (m_helper,*m_collection, m_surfaces)
ConstParameters parameters_impl (IndexType istate) const
Parameters parameters_impl (IndexType istate)
ConstCovariance covariance_impl (IndexType istate) const
Covariance covariance_impl (IndexType istate)
ConstCovariance jacobian_impl (IndexType istate) const
Covariance jacobian_impl (IndexType istate)
template<size_t measdim>
ConstTrackStateProxy::Measurement
< measdim > measurement_impl (IndexType index) const
template<size_t measdim>
TrackStateProxy::Measurement
< measdim > measurement_impl (IndexType index)
template<size_t measdim>
ConstTrackStateProxy::MeasurementCovariance
< measdim > measurementCovariance_impl (IndexType index) const
template<size_t measdim>
TrackStateProxy::MeasurementCovariance
< measdim > measurementCovariance_impl (IndexType index)
IndexType size_impl () const
std::any component_impl (HashedString key, IndexType istate) const
std::any component_impl (HashedString key, IndexType istate)
constexpr bool hasColumn_impl (HashedString key) const
constexpr bool has_impl (HashedString key, IndexType istate) const
IndexType addTrackState_impl (TrackStatePropMask mask=TrackStatePropMask::All, TrackIndexType iprevious=kTrackIndexInvalid)
void shareFrom_impl (TrackIndexType iself, TrackIndexType iother, TrackStatePropMask shareSource, TrackStatePropMask shareTarget)
void unset_impl (TrackStatePropMask target, TrackIndexType istate)
void clear_impl ()
template<typename T >
constexpr void addColumn_impl (const std::string &key)
void allocateCalibrated_impl (IndexType istate, size_t measdim)
void setUncalibratedSourceLink_impl (IndexType istate, const SourceLink &sourceLink)
void setReferenceSurface_impl (IndexType istate, std::shared_ptr< const Surface > surface)
MultiTrajectoryTraits::IndexType calibratedSize_impl (IndexType istate) const
SourceLink getUncalibratedSourceLink_impl (IndexType istate) const
const Surface * referenceSurface_impl (IndexType istate) const
void releaseInto (podio::Frame &frame, const std::string &suffix="")
Public Member Functions inherited from Acts::MultiTrajectory< MutablePodioTrackStateContainer >
ConstTrackStateProxy getTrackState (IndexType istate) const
TrackStateProxy getTrackState (IndexType istate)
void visitBackwards (IndexType iendpoint, F &&callable) const
auto reverseTrackStateRange (IndexType iendpoint) const
auto reverseTrackStateRange (IndexType iendpoint)
auto forwardTrackStateRange (IndexType istartpoint) const
auto forwardTrackStateRange (IndexType istartpoint)
void applyBackwards (IndexType iendpoint, F &&callable)
auto && convertToReadOnly () const
constexpr void clear ()
Clear the MultiTrajectory. Leaves the underlying storage untouched.
constexpr IndexType size () const
Returns the number of track states contained.
constexpr IndexType addTrackState (TrackStatePropMask mask=TrackStatePropMask::All, IndexType iprevious=kInvalid)
constexpr void addColumn (const std::string &key)
constexpr bool hasColumn (HashedString key) const
Public Attributes
m_jacs = std::make_unique<ActsPodioEdm::JacobianCollection>()
m_params = std::make_unique<ActsPodioEdm::BoundParametersCollection>()
Private Attributes
std::reference_wrapper
< PodioUtil::ConversionHelper > m_helper
std::unique_ptr
< ActsPodioEdm::TrackStateCollection > m_collection
std::unique_ptr
< ActsPodioEdm::BoundParametersCollection > m_params
std::unique_ptr
< ActsPodioEdm::JacobianCollection > m_jacs
std::vector< std::shared_ptr
< const Surface > > m_surfaces
std::unordered_map
< HashedString,
std::unique_ptr
< podio_detail::DynamicColumnBase > > m_dynamic
Friends
class PodioTrackStateContainerBase
class ConstPodioTrackStateContainer
Additional Inherited Members
Public Types inherited from Acts::PodioTrackStateContainerBase
using Parameters = typename detail_lt::Types< eBoundSize, false >::CoefficientsMap
using Covariance = typename detail_lt::Types< eBoundSize, false >::CovarianceMap
using ConstParameters = typename detail_lt::Types< eBoundSize, true >::CoefficientsMap
using ConstCovariance = typename detail_lt::Types< eBoundSize, true >::CovarianceMap
Public Types inherited from Acts::MultiTrajectory< MutablePodioTrackStateContainer >
using Derived = MutablePodioTrackStateContainer
using ConstTrackStateProxy = detail_lt::TrackStateProxy< Derived, MeasurementSizeMax, true >
using TrackStateProxy = detail_lt::TrackStateProxy< Derived, MeasurementSizeMax, false >
using IndexType = typename TrackStateProxy::IndexType
Static Public Attributes inherited from Acts::MultiTrajectory< MutablePodioTrackStateContainer >
static constexpr bool ReadOnly
static constexpr unsigned int MeasurementSizeMax
static constexpr IndexType kInvalid
Protected Member Functions inherited from Acts::MultiTrajectory< MutablePodioTrackStateContainer >
MultiTrajectory ()=default
constexpr bool has (HashedString key, IndexType istate) const
constexpr bool has (IndexType istate) const
constexpr
TrackStateProxy::Parameters parameters (IndexType parIdx)
constexpr
ConstTrackStateProxy::Parameters parameters (IndexType parIdx) const
constexpr
TrackStateProxy::Covariance covariance (IndexType covIdx)
constexpr
ConstTrackStateProxy::Covariance covariance (IndexType covIdx) const
constexpr
TrackStateProxy::Covariance jacobian (IndexType jacIdx)
constexpr
ConstTrackStateProxy::Covariance jacobian (IndexType jacIdx) const
constexpr
TrackStateProxy::template
Measurement< measdim > measurement (IndexType measIdx)
constexpr
ConstTrackStateProxy::template
Measurement< measdim > measurement (IndexType measIdx) const
constexpr
TrackStateProxy::template
MeasurementCovariance< measdim > measurementCovariance (IndexType covIdx)
constexpr
ConstTrackStateProxy::template
MeasurementCovariance< measdim > measurementCovariance (IndexType covIdx) const
IndexType calibratedSize (IndexType istate) const
constexpr void shareFrom (IndexType iself, IndexType iother, TrackStatePropMask shareSource, TrackStatePropMask shareTarget)
constexpr void unset (TrackStatePropMask target, IndexType istate)
constexpr T & component (IndexType istate)
constexpr T & component (HashedString key, IndexType istate)
constexpr const T & component (IndexType istate) const
constexpr const T & component (HashedString key, IndexType istate) const
void allocateCalibrated (IndexType istate, size_t measdim)
void setUncalibratedSourceLink (IndexType istate, SourceLink sourceLink)
SourceLink getUncalibratedSourceLink (IndexType istate) const
const Surface * referenceSurface (IndexType istate) const
void setReferenceSurface (IndexType istate, std::shared_ptr< const Surface > surface)
Static Protected Member Functions inherited from Acts::PodioTrackStateContainerBase
template<typename T >
static constexpr bool has_impl (T &instance, HashedString key, TrackIndexType istate)
template<bool EnsureConst, typename T >
static std::any component_impl (T &instance, HashedString key, TrackIndexType istate)
template<typename T >
static constexpr bool hasColumn_impl (T &instance, HashedString key)
static void populateSurfaceBuffer (const PodioUtil::ConversionHelper &helper, const ActsPodioEdm::TrackStateCollection &collection, std::vector< std::shared_ptr< const Surface >> &surfaces) noexcept
Detailed Description
Definition at line 382 of file PodioTrackStateContainer.hpp.
View newest version in sPHENIX GitHub at line 382 of file PodioTrackStateContainer.hpp
Constructor & Destructor Documentation
Acts::MutablePodioTrackStateContainer::MutablePodioTrackStateContainer (PodioUtil::ConversionHelper & helper) inline
Definition at line 386 of file PodioTrackStateContainer.hpp.
View newest version in sPHENIX GitHub at line 386 of file PodioTrackStateContainer.hpp
Member Function Documentation
template<typename T > constexpr void Acts::MutablePodioTrackStateContainer::addColumn_impl (const std::string & key) inline
Definition at line 600 of file PodioTrackStateContainer.hpp.
View newest version in sPHENIX GitHub at line 600 of file PodioTrackStateContainer.hpp
References Acts::hashString().
IndexType Acts::MutablePodioTrackStateContainer::addTrackState_impl (TrackStatePropMask mask = TrackStatePropMask::All, TrackIndexType iprevious = kTrackIndexInvalid) inline
Definition at line 468 of file PodioTrackStateContainer.hpp.
View newest version in sPHENIX GitHub at line 468 of file PodioTrackStateContainer.hpp
References ACTS_CHECK_BIT, assert, configureMap::data, Acts::MultiTrajectoryTraits::kInvalid, Acts::PodioUtil::kNoIdentifier, Acts::PodioUtil::kNoSurface, mask, and vec.
void Acts::MutablePodioTrackStateContainer::allocateCalibrated_impl (IndexType istate, size_t measdim) inline
Definition at line 605 of file PodioTrackStateContainer.hpp.
View newest version in sPHENIX GitHub at line 605 of file PodioTrackStateContainer.hpp
References assert, and configureMap::data.
MultiTrajectoryTraits::IndexType Acts::MutablePodioTrackStateContainer::calibratedSize_impl (IndexType istate) const inline
Definition at line 626 of file PodioTrackStateContainer.hpp.
View newest version in sPHENIX GitHub at line 626 of file PodioTrackStateContainer.hpp
void Acts::MutablePodioTrackStateContainer::clear_impl () inline
Definition at line 590 of file PodioTrackStateContainer.hpp.
View newest version in sPHENIX GitHub at line 590 of file PodioTrackStateContainer.hpp
References vec.
std::any Acts::MutablePodioTrackStateContainer::component_impl (HashedString key, IndexType istate) const inline
Definition at line 450 of file PodioTrackStateContainer.hpp.
View newest version in sPHENIX GitHub at line 450 of file PodioTrackStateContainer.hpp
std::any Acts::MutablePodioTrackStateContainer::component_impl (HashedString key, IndexType istate) inline
Definition at line 455 of file PodioTrackStateContainer.hpp.
View newest version in sPHENIX GitHub at line 455 of file PodioTrackStateContainer.hpp
ConstCovariance Acts::MutablePodioTrackStateContainer::covariance_impl (IndexType istate) const inline
Definition at line 403 of file PodioTrackStateContainer.hpp.
View newest version in sPHENIX GitHub at line 403 of file PodioTrackStateContainer.hpp
Covariance Acts::MutablePodioTrackStateContainer::covariance_impl (IndexType istate) inline
Definition at line 407 of file PodioTrackStateContainer.hpp.
View newest version in sPHENIX GitHub at line 407 of file PodioTrackStateContainer.hpp
SourceLink Acts::MutablePodioTrackStateContainer::getUncalibratedSourceLink_impl (IndexType istate) const inline
Definition at line 630 of file PodioTrackStateContainer.hpp.
View newest version in sPHENIX GitHub at line 630 of file PodioTrackStateContainer.hpp
References Acts::SourceLink::get().
constexpr bool Acts::MutablePodioTrackStateContainer::has_impl (HashedString key, IndexType istate) const inline
Definition at line 464 of file PodioTrackStateContainer.hpp.
View newest version in sPHENIX GitHub at line 464 of file PodioTrackStateContainer.hpp
References Acts::PodioTrackStateContainerBase::has_impl().
constexpr bool Acts::MutablePodioTrackStateContainer::hasColumn_impl (HashedString key) const inline
Definition at line 460 of file PodioTrackStateContainer.hpp.
View newest version in sPHENIX GitHub at line 460 of file PodioTrackStateContainer.hpp
References Acts::PodioTrackStateContainerBase::hasColumn_impl().
ConstCovariance Acts::MutablePodioTrackStateContainer::jacobian_impl (IndexType istate) const inline
Definition at line 411 of file PodioTrackStateContainer.hpp.
View newest version in sPHENIX GitHub at line 411 of file PodioTrackStateContainer.hpp
Covariance Acts::MutablePodioTrackStateContainer::jacobian_impl (IndexType istate) inline
Definition at line 416 of file PodioTrackStateContainer.hpp.
View newest version in sPHENIX GitHub at line 416 of file PodioTrackStateContainer.hpp
template<size_t measdim> ConstTrackStateProxy::Measurement<measdim> Acts::MutablePodioTrackStateContainer::measurement_impl (IndexType index) const inline
Definition at line 422 of file PodioTrackStateContainer.hpp.
View newest version in sPHENIX GitHub at line 422 of file PodioTrackStateContainer.hpp
template<size_t measdim> TrackStateProxy::Measurement<measdim> Acts::MutablePodioTrackStateContainer::measurement_impl (IndexType index) inline
Definition at line 429 of file PodioTrackStateContainer.hpp.
View newest version in sPHENIX GitHub at line 429 of file PodioTrackStateContainer.hpp
template<size_t measdim> ConstTrackStateProxy::MeasurementCovariance<measdim> Acts::MutablePodioTrackStateContainer::measurementCovariance_impl (IndexType index) const inline
Definition at line 436 of file PodioTrackStateContainer.hpp.
View newest version in sPHENIX GitHub at line 436 of file PodioTrackStateContainer.hpp
template<size_t measdim> TrackStateProxy::MeasurementCovariance<measdim> Acts::MutablePodioTrackStateContainer::measurementCovariance_impl (IndexType index) inline
Definition at line 442 of file PodioTrackStateContainer.hpp.
View newest version in sPHENIX GitHub at line 442 of file PodioTrackStateContainer.hpp
ConstParameters Acts::MutablePodioTrackStateContainer::parameters_impl (IndexType istate) const inline
Definition at line 395 of file PodioTrackStateContainer.hpp.
View newest version in sPHENIX GitHub at line 395 of file PodioTrackStateContainer.hpp
Parameters Acts::MutablePodioTrackStateContainer::parameters_impl (IndexType istate) inline
Definition at line 399 of file PodioTrackStateContainer.hpp.
View newest version in sPHENIX GitHub at line 399 of file PodioTrackStateContainer.hpp
Acts::MutablePodioTrackStateContainer::populateSurfaceBuffer (m_helper , * m_collection, m_surfaces)
const Surface* Acts::MutablePodioTrackStateContainer::referenceSurface_impl (IndexType istate) const inline
Definition at line 635 of file PodioTrackStateContainer.hpp.
View newest version in sPHENIX GitHub at line 635 of file PodioTrackStateContainer.hpp
void Acts::MutablePodioTrackStateContainer::releaseInto (podio::Frame & frame, const std::string & suffix = "") inline
Definition at line 639 of file PodioTrackStateContainer.hpp.
View newest version in sPHENIX GitHub at line 639 of file PodioTrackStateContainer.hpp
References col, testing::internal::move(), and physmon_simulation::s.
void Acts::MutablePodioTrackStateContainer::setReferenceSurface_impl (IndexType istate, std::shared_ptr< const Surface > surface) inline
Definition at line 618 of file PodioTrackStateContainer.hpp.
View newest version in sPHENIX GitHub at line 618 of file PodioTrackStateContainer.hpp
References Acts::PodioUtil::convertSurfaceToPodio(), and testing::internal::move().
void Acts::MutablePodioTrackStateContainer::setUncalibratedSourceLink_impl (IndexType istate, const SourceLink & sourceLink) inline
Definition at line 611 of file PodioTrackStateContainer.hpp.
View newest version in sPHENIX GitHub at line 611 of file PodioTrackStateContainer.hpp
References train_ambiguity_solver::id.
void Acts::MutablePodioTrackStateContainer::shareFrom_impl (TrackIndexType iself, TrackIndexType iother, TrackStatePropMask shareSource, TrackStatePropMask shareTarget) inline
Definition at line 514 of file PodioTrackStateContainer.hpp.
View newest version in sPHENIX GitHub at line 514 of file PodioTrackStateContainer.hpp
References ACTS_CHECK_BIT, assert, and Acts::MultiTrajectoryTraits::kInvalid.
IndexType Acts::MutablePodioTrackStateContainer::size_impl () const inline
Definition at line 448 of file PodioTrackStateContainer.hpp.
View newest version in sPHENIX GitHub at line 448 of file PodioTrackStateContainer.hpp
void Acts::MutablePodioTrackStateContainer::unset_impl (TrackStatePropMask target, TrackIndexType istate) inline
Definition at line 567 of file PodioTrackStateContainer.hpp.
View newest version in sPHENIX GitHub at line 567 of file PodioTrackStateContainer.hpp
References configureMap::data, and Acts::MultiTrajectoryTraits::kInvalid.
Friends And Related Function Documentation
friend class ConstPodioTrackStateContainer friend
Definition at line 656 of file PodioTrackStateContainer.hpp.
View newest version in sPHENIX GitHub at line 656 of file PodioTrackStateContainer.hpp
friend class PodioTrackStateContainerBase friend
Definition at line 655 of file PodioTrackStateContainer.hpp.
View newest version in sPHENIX GitHub at line 655 of file PodioTrackStateContainer.hpp
Member Data Documentation
std::unique_ptr<ActsPodioEdm::TrackStateCollection> Acts::MutablePodioTrackStateContainer::m_collection private
Definition at line 659 of file PodioTrackStateContainer.hpp.
View newest version in sPHENIX GitHub at line 659 of file PodioTrackStateContainer.hpp
std::unordered_map<HashedString, std::unique_ptr<podio_detail::DynamicColumnBase> > Acts::MutablePodioTrackStateContainer::m_dynamic private
Definition at line 666 of file PodioTrackStateContainer.hpp.
View newest version in sPHENIX GitHub at line 666 of file PodioTrackStateContainer.hpp
std::reference_wrapper<PodioUtil::ConversionHelper> Acts::MutablePodioTrackStateContainer::m_helper private
Definition at line 658 of file PodioTrackStateContainer.hpp.
View newest version in sPHENIX GitHub at line 658 of file PodioTrackStateContainer.hpp
Acts::MutablePodioTrackStateContainer::m_jacs = std::make_unique<ActsPodioEdm::JacobianCollection>()
Definition at line 389 of file PodioTrackStateContainer.hpp.
View newest version in sPHENIX GitHub at line 389 of file PodioTrackStateContainer.hpp
std::unique_ptr<ActsPodioEdm::JacobianCollection> Acts::MutablePodioTrackStateContainer::m_jacs private
Definition at line 661 of file PodioTrackStateContainer.hpp.
View newest version in sPHENIX GitHub at line 661 of file PodioTrackStateContainer.hpp
Acts::MutablePodioTrackStateContainer::m_params = std::make_unique<ActsPodioEdm::BoundParametersCollection>()
Definition at line 390 of file PodioTrackStateContainer.hpp.
View newest version in sPHENIX GitHub at line 390 of file PodioTrackStateContainer.hpp
std::unique_ptr<ActsPodioEdm::BoundParametersCollection> Acts::MutablePodioTrackStateContainer::m_params private
Definition at line 660 of file PodioTrackStateContainer.hpp.
View newest version in sPHENIX GitHub at line 660 of file PodioTrackStateContainer.hpp
std::vector<std::shared_ptr<const Surface> > Acts::MutablePodioTrackStateContainer::m_surfaces private
Definition at line 662 of file PodioTrackStateContainer.hpp.
View newest version in sPHENIX GitHub at line 662 of file PodioTrackStateContainer.hpp
The documentation for this exception was generated from the following file:
acts/blob/sPHENIX/Plugins/Podio/include/Acts/Plugins/Podio/PodioTrackStateContainer.hpp