Analysis Software: KFParticle_DST Class Reference
KFParticle_DST Class Reference
#include <coresoftware/blob/master/offline/packages/KFParticle_sPHENIX/KFParticle_DST.h>
Public Member Functions
KFParticle_DST ()=default
Constructor.
virtual ~KFParticle_DST ()=default
Destructor.
int createParticleNode (PHCompositeNode *topNode)
Places a KFParticle_Container and SvtxTrackMap on the node tree if they don't exist.
void fillParticleNode (PHCompositeNode *topNode, const KFParticle &motherParticle, const std::vector< KFParticle > &daughters, const std::vector< KFParticle > &intermediates)
Simultaneously fills a KFParticle_Container and SvtxTrackMap if they are enabled.
void fillParticleNode_Track (PHCompositeNode *topNode, const KFParticle &motherParticle, std::vector< KFParticle > daughters, std::vector< KFParticle > intermediates)
Called by fillParticleNode, fills an SvtxTrackMap.
void fillParticleNode_Particle (PHCompositeNode *topNode, const KFParticle &motherParticle, std::vector< KFParticle > daughters, std::vector< KFParticle > intermediates)
Called by fillParticleNode, fills a KFParitcle_Container.
void printNode (PHCompositeNode *topNode)
Prints contents of KFParticle_Containers and SvtxTrackMaps for an event if they are enabled.
Protected Attributes
bool m_has_intermediates_DST = false
bool m_write_track_container = true
bool m_write_particle_container = true
std::string m_container_name
Private Member Functions
SvtxTrack * buildSvtxTrack (const KFParticle &particle)
Private Attributes
SvtxTrackMap * m_recoTrackMap = nullptr
KFParticle_Container * m_recoParticleMap = nullptr
Detailed Description
Definition at line 14 of file KFParticle_DST.h.
View newest version in sPHENIX GitHub at line 14 of file KFParticle_DST.h
Constructor & Destructor Documentation
KFParticle_DST::KFParticle_DST () default
Constructor.
virtual KFParticle_DST::~KFParticle_DST () virtual default
Destructor.
Member Function Documentation
SvtxTrack * KFParticle_DST::buildSvtxTrack (const KFParticle & particle) private
Definition at line 263 of file KFParticle_DST.cc.
View newest version in sPHENIX GitHub at line 263 of file KFParticle_DST.cc
References KFParticle::GetChi2(), KFParticle::GetCovariance(), KFParticle::GetNDF(), KFParticleBase::GetPDG(), KFParticle::GetPx(), KFParticle::GetPy(), KFParticle::GetPz(), KFParticle::GetQ(), KFParticle::GetX(), KFParticle::GetY(), KFParticle::GetZ(), i, j, SvtxTrack::set_charge(), SvtxTrack::set_chisq(), SvtxTrack::set_error(), SvtxTrack::set_id(), SvtxTrack::set_ndf(), SvtxTrack::set_px(), SvtxTrack::set_py(), SvtxTrack::set_pz(), SvtxTrack::set_x(), SvtxTrack::set_y(), and SvtxTrack::set_z().
Referenced by fillParticleNode_Track().
int KFParticle_DST::createParticleNode (PHCompositeNode * topNode)
Places a KFParticle_Container and SvtxTrackMap on the node tree if they don't exist.
Definition at line 42 of file KFParticle_DST.cc.
View newest version in sPHENIX GitHub at line 42 of file KFParticle_DST.cc
References PHCompositeNode::addNode(), Fun4AllReturnCodes::EVENT_OK, PHNodeIterator::findFirst(), m_container_name, m_recoParticleMap, m_recoTrackMap, m_write_particle_container, m_write_track_container, and Acts::Test::pos.
Referenced by KFParticle_sPHENIX::Init().
void KFParticle_DST::fillParticleNode (PHCompositeNode * topNode, const KFParticle & motherParticle, const std::vector< KFParticle > & daughters, const std::vector< KFParticle > & intermediates)
Simultaneously fills a KFParticle_Container and SvtxTrackMap if they are enabled.
Definition at line 115 of file KFParticle_DST.cc.
View newest version in sPHENIX GitHub at line 115 of file KFParticle_DST.cc
References fillParticleNode_Particle(), fillParticleNode_Track(), m_write_particle_container, and m_write_track_container.
Referenced by KFParticle_sPHENIX::process_event().
void KFParticle_DST::fillParticleNode_Particle (PHCompositeNode * topNode, const KFParticle & motherParticle, std::vector< KFParticle > daughters, std::vector< KFParticle > intermediates)
Called by fillParticleNode, fills a KFParitcle_Container.
Definition at line 205 of file KFParticle_DST.cc.
View newest version in sPHENIX GitHub at line 205 of file KFParticle_DST.cc
References KFParticle_Container::insert(), k, m_container_name, m_has_intermediates_DST, m_recoParticleMap, and Acts::Test::pos.
Referenced by fillParticleNode().
void KFParticle_DST::fillParticleNode_Track (PHCompositeNode * topNode, const KFParticle & motherParticle, std::vector< KFParticle > daughters, std::vector< KFParticle > intermediates)
Called by fillParticleNode, fills an SvtxTrackMap.
Definition at line 129 of file KFParticle_DST.cc.
View newest version in sPHENIX GitHub at line 129 of file KFParticle_DST.cc
References buildSvtxTrack(), KFParticle_truthAndDetTools::getTrack(), Id(), SvtxTrackMap::insert(), k, m_container_name, m_has_intermediates_DST, m_recoTrackMap, Acts::Test::pos, PHObject::Reset(), and SvtxTrackMap::size().
Referenced by fillParticleNode().
void KFParticle_DST::printNode (PHCompositeNode * topNode)
Prints contents of KFParticle_Containers and SvtxTrackMaps for an event if they are enabled.
Definition at line 291 of file KFParticle_DST.cc.
View newest version in sPHENIX GitHub at line 291 of file KFParticle_DST.cc
References SvtxTrack::identify(), KFParticle_Tools::identify(), m_container_name, m_write_particle_container, m_write_track_container, particle, and Acts::Test::pos.
Referenced by KFParticle_sPHENIX::process_event().
Member Data Documentation
std::string KFParticle_DST::m_container_name protected
Definition at line 48 of file KFParticle_DST.h.
View newest version in sPHENIX GitHub at line 48 of file KFParticle_DST.h
Referenced by createParticleNode(), fillParticleNode_Particle(), fillParticleNode_Track(), printNode(), and KFParticle_sPHENIX::setContainerName().
bool KFParticle_DST::m_has_intermediates_DST = false protected
Definition at line 45 of file KFParticle_DST.h.
View newest version in sPHENIX GitHub at line 45 of file KFParticle_DST.h
Referenced by fillParticleNode_Particle(), fillParticleNode_Track(), and KFParticle_sPHENIX::hasIntermediateStates().
KFParticle_Container* KFParticle_DST::m_recoParticleMap = nullptr private
Definition at line 52 of file KFParticle_DST.h.
View newest version in sPHENIX GitHub at line 52 of file KFParticle_DST.h
Referenced by createParticleNode(), and fillParticleNode_Particle().
SvtxTrackMap* KFParticle_DST::m_recoTrackMap = nullptr private
Definition at line 51 of file KFParticle_DST.h.
View newest version in sPHENIX GitHub at line 51 of file KFParticle_DST.h
Referenced by createParticleNode(), and fillParticleNode_Track().
bool KFParticle_DST::m_write_particle_container = true protected
Definition at line 47 of file KFParticle_DST.h.
View newest version in sPHENIX GitHub at line 47 of file KFParticle_DST.h
Referenced by createParticleNode(), fillParticleNode(), printNode(), and KFParticle_sPHENIX::saveParticleContainer().
bool KFParticle_DST::m_write_track_container = true protected
Definition at line 46 of file KFParticle_DST.h.
View newest version in sPHENIX GitHub at line 46 of file KFParticle_DST.h
Referenced by createParticleNode(), fillParticleNode(), printNode(), and KFParticle_sPHENIX::saveTrackContainer().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/KFParticle_sPHENIX/KFParticle_DST.h
coresoftware/blob/master/offline/packages/KFParticle_sPHENIX/KFParticle_DST.cc