Analysis Software: ActsFatras::PlanarSurfaceDrift Struct Reference
ActsFatras::PlanarSurfaceDrift Struct Reference
#include <acts/blob/sPHENIX/Fatras/include/ActsFatras/Digitization/PlanarSurfaceDrift.hpp>
Public Types
using Segment2D = std::array< Acts::Vector2, 2 >
Shorthand for a 2D segment.
Public Member Functions
Segment2D toReadout (const Acts::GeometryContext &gctx, const Acts::Surface &surface, double thickness, const Acts::Vector3 &pos, const Acts::Vector3 &dir, const Acts::Vector3 &driftdir) const
Detailed Description
The PlanarSurfaceDrift takes an intersection in the nominal surface and projects the ends into the readout surface, which can be at : -1, 0, 1
A Lorentz drift angle can be applied.
Definition at line 26 of file PlanarSurfaceDrift.hpp.
View newest version in sPHENIX GitHub at line 26 of file PlanarSurfaceDrift.hpp
Member Typedef Documentation
using ActsFatras::PlanarSurfaceDrift::Segment2D = std::array<Acts::Vector2, 2>
Shorthand for a 2D segment.
Definition at line 28 of file PlanarSurfaceDrift.hpp.
View newest version in sPHENIX GitHub at line 28 of file PlanarSurfaceDrift.hpp
Member Function Documentation
ActsFatras::PlanarSurfaceDrift::Segment2D ActsFatras::PlanarSurfaceDrift::toReadout (const Acts::GeometryContext & gctx, const Acts::Surface & surface, double thickness, const Acts::Vector3 & pos, const Acts::Vector3 & dir, const Acts::Vector3 & driftdir) const
Drift the full 3D segment onto a surface 2D readout plane
Parameters
gctx The current Geometry context
surface The nominal intersection surface
thickness The emulated module/depletion thickness
pos The position in global coordinates
dir The direction in global coordinates
driftdir The drift direction in local (surface) coordinates
Note
a drift direction of (0,0,0) is drift to central plane any other a drift direction with driftDir.z() != 0. will result on a readout on either + 0.5*depletion or -0.5*depletion
Returns
a Segment on the readout surface
Note
without masking
Definition at line 16 of file PlanarSurfaceDrift.cpp.
View newest version in sPHENIX GitHub at line 16 of file PlanarSurfaceDrift.cpp
References entry, Acts::Test::pos, Acts::VectorHelpers::theta(), and Acts::Surface::transform().
Referenced by ActsFatras::BOOST_AUTO_TEST_CASE().
The documentation for this struct was generated from the following files:
acts/blob/sPHENIX/Fatras/include/ActsFatras/Digitization/PlanarSurfaceDrift.hpp
acts/blob/sPHENIX/Fatras/src/Digitization/PlanarSurfaceDrift.cpp