Analysis Software: sPHElectronPairv1 Class Reference
sPHElectronPairv1 Class Reference
#include <analysis/blob/master/EventMix/src/sPHElectronPairv1.h>
Public Member Functions
sPHElectronPairv1 ()
sPHElectronPairv1 (sPHElectronv1 *e1, sPHElectronv1 *e2)
virtual ~sPHElectronPairv1 ()
virtual void identify (std::ostream &os=std::cout) const
virtual void Reset ()
Clear Event.
virtual int isValid () const
isValid returns non zero if object contains vailid data
virtual PHObject * CloneMe () const
Virtual copy constructor.
virtual sPHElectron * get_first ()
virtual sPHElectron * get_second ()
virtual int get_id () const
virtual int get_type () const
virtual double get_mass () const
virtual double get_pt () const
virtual double get_eta () const
virtual double get_phiv () const
virtual double get_min_mass () const
virtual void set_id (int id)
virtual void set_type (int type)
virtual void set_min_mass (double mm)
Public Member Functions inherited from sPHElectronPair
virtual ~sPHElectronPair ()
Public Member Functions inherited from PHObject
PHObject ()
ctor
~PHObject () override
dtor
virtual PHObject * clone () const final
PHObject * Clone (const char *newname="") const final
void Copy (TObject &object) const final
virtual int Integrate () const
virtual int Integrate (PHObject *)
virtual void CopyFrom (const PHObject *obj)
Protected Attributes
int _id
int _type
double _min_mass
sPHElectronv1 _e1
sPHElectronv1 _e2
Additional Inherited Members
Protected Member Functions inherited from sPHElectronPair
sPHElectronPair ()
Detailed Description
Definition at line 11 of file sPHElectronPairv1.h.
View newest version in sPHENIX GitHub at line 11 of file sPHElectronPairv1.h
Constructor & Destructor Documentation
sPHElectronPairv1::sPHElectronPairv1 ()
Definition at line 5 of file sPHElectronPairv1.cc.
View newest version in sPHENIX GitHub at line 5 of file sPHElectronPairv1.cc
References _e1, _e2, _id, and _type.
Referenced by CloneMe().
sPHElectronPairv1::sPHElectronPairv1 (sPHElectronv1 * e1, sPHElectronv1 * e2)
Definition at line 13 of file sPHElectronPairv1.cc.
View newest version in sPHENIX GitHub at line 13 of file sPHElectronPairv1.cc
References _e1, _e2, _id, _type, and sPHElectronv1::get_id().
virtual sPHElectronPairv1::~sPHElectronPairv1 () inline virtual
Definition at line 16 of file sPHElectronPairv1.h.
View newest version in sPHENIX GitHub at line 16 of file sPHElectronPairv1.h
Member Function Documentation
virtual PHObject* sPHElectronPairv1::CloneMe () const inline virtual
Virtual copy constructor.
Reimplemented from sPHElectronPair.
Definition at line 22 of file sPHElectronPairv1.h.
View newest version in sPHENIX GitHub at line 22 of file sPHElectronPairv1.h
References sPHElectronPairv1().
Referenced by sPHElectronPairContainerv1::insert().
double sPHElectronPairv1::get_eta () const virtual
Reimplemented from sPHElectronPair.
Definition at line 53 of file sPHElectronPairv1.cc.
View newest version in sPHENIX GitHub at line 53 of file sPHElectronPairv1.cc
References _e1, _e2, sPHElectronv1::get_px(), sPHElectronv1::get_py(), and sPHElectronv1::get_pz().
Referenced by sPHAnalysis::process_event_pairs().
virtual sPHElectron* sPHElectronPairv1::get_first () inline virtual
Reimplemented from sPHElectronPair.
Definition at line 24 of file sPHElectronPairv1.h.
View newest version in sPHENIX GitHub at line 24 of file sPHElectronPairv1.h
References _e1.
Referenced by sPHAnalysis::process_event_pairs().
virtual int sPHElectronPairv1::get_id () const inline virtual
Reimplemented from sPHElectronPair.
Definition at line 27 of file sPHElectronPairv1.h.
View newest version in sPHENIX GitHub at line 27 of file sPHElectronPairv1.h
References _id.
Referenced by sPHElectronPairContainerv1::operator=(), and sPHElectronPairContainerv1::sPHElectronPairContainerv1().
double sPHElectronPairv1::get_mass () const virtual
Reimplemented from sPHElectronPair.
Definition at line 21 of file sPHElectronPairv1.cc.
View newest version in sPHENIX GitHub at line 21 of file sPHElectronPairv1.cc
References _e1, _e2, sPHElectronv1::get_px(), sPHElectronv1::get_py(), and sPHElectronv1::get_pz().
Referenced by PairMaker::MakeMixedPairs(), sPHAnalysis::process_event_pairs(), and PairMaker::process_event_test().
virtual double sPHElectronPairv1::get_min_mass () const inline virtual
Reimplemented from sPHElectronPair.
Definition at line 33 of file sPHElectronPairv1.h.
View newest version in sPHENIX GitHub at line 33 of file sPHElectronPairv1.h
References _min_mass.
double sPHElectronPairv1::get_phiv () const virtual
Reimplemented from sPHElectronPair.
Definition at line 69 of file sPHElectronPairv1.cc.
View newest version in sPHENIX GitHub at line 69 of file sPHElectronPairv1.cc
References _e1, _e2, CKF_timing_vs_mu::ax, sPHElectronv1::get_px(), sPHElectronv1::get_py(), sPHElectronv1::get_pz(), vx, vy, and vz.
double sPHElectronPairv1::get_pt () const virtual
Reimplemented from sPHElectronPair.
Definition at line 37 of file sPHElectronPairv1.cc.
View newest version in sPHENIX GitHub at line 37 of file sPHElectronPairv1.cc
References _e1, _e2, sPHElectronv1::get_px(), sPHElectronv1::get_py(), and sPHElectronv1::get_pz().
Referenced by sPHAnalysis::process_event_pairs().
virtual sPHElectron* sPHElectronPairv1::get_second () inline virtual
Reimplemented from sPHElectronPair.
Definition at line 25 of file sPHElectronPairv1.h.
View newest version in sPHENIX GitHub at line 25 of file sPHElectronPairv1.h
References _e2.
Referenced by sPHAnalysis::process_event_pairs().
virtual int sPHElectronPairv1::get_type () const inline virtual
Reimplemented from sPHElectronPair.
Definition at line 28 of file sPHElectronPairv1.h.
View newest version in sPHENIX GitHub at line 28 of file sPHElectronPairv1.h
References _type.
Referenced by sPHAnalysis::process_event_pairs().
virtual void sPHElectronPairv1::identify (std::ostream & os = std::cout) const inline virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from sPHElectronPair.
Definition at line 18 of file sPHElectronPairv1.h.
View newest version in sPHENIX GitHub at line 18 of file sPHElectronPairv1.h
References os.
virtual int sPHElectronPairv1::isValid () const inline virtual
isValid returns non zero if object contains vailid data
Reimplemented from sPHElectronPair.
Definition at line 21 of file sPHElectronPairv1.h.
View newest version in sPHENIX GitHub at line 21 of file sPHElectronPairv1.h
virtual void sPHElectronPairv1::Reset () inline virtual
Clear Event.
Reimplemented from sPHElectronPair.
Definition at line 20 of file sPHElectronPairv1.h.
View newest version in sPHENIX GitHub at line 20 of file sPHElectronPairv1.h
virtual void sPHElectronPairv1::set_id (int id) inline virtual
Reimplemented from sPHElectronPair.
Definition at line 35 of file sPHElectronPairv1.h.
View newest version in sPHENIX GitHub at line 35 of file sPHElectronPairv1.h
References _id, and train_ambiguity_solver::id.
virtual void sPHElectronPairv1::set_min_mass (double mm) inline virtual
Reimplemented from sPHElectronPair.
Definition at line 37 of file sPHElectronPairv1.h.
View newest version in sPHENIX GitHub at line 37 of file sPHElectronPairv1.h
References _min_mass, and Acts::UnitConstants::mm.
virtual void sPHElectronPairv1::set_type (int type) inline virtual
Reimplemented from sPHElectronPair.
Definition at line 36 of file sPHElectronPairv1.h.
View newest version in sPHENIX GitHub at line 36 of file sPHElectronPairv1.h
References _type, and parse_cmake_options::type.
Referenced by PairMaker::MakeMixedPairs(), and PairMaker::process_event_test().
Member Data Documentation
sPHElectronv1 sPHElectronPairv1::_e1 protected
Definition at line 44 of file sPHElectronPairv1.h.
View newest version in sPHENIX GitHub at line 44 of file sPHElectronPairv1.h
Referenced by get_eta(), get_first(), get_mass(), get_phiv(), get_pt(), and sPHElectronPairv1().
sPHElectronv1 sPHElectronPairv1::_e2 protected
Definition at line 45 of file sPHElectronPairv1.h.
View newest version in sPHENIX GitHub at line 45 of file sPHElectronPairv1.h
Referenced by get_eta(), get_mass(), get_phiv(), get_pt(), get_second(), and sPHElectronPairv1().
int sPHElectronPairv1::_id protected
Definition at line 41 of file sPHElectronPairv1.h.
View newest version in sPHENIX GitHub at line 41 of file sPHElectronPairv1.h
Referenced by get_id(), set_id(), and sPHElectronPairv1().
double sPHElectronPairv1::_min_mass protected
Definition at line 43 of file sPHElectronPairv1.h.
View newest version in sPHENIX GitHub at line 43 of file sPHElectronPairv1.h
Referenced by get_min_mass(), and set_min_mass().
int sPHElectronPairv1::_type protected
Definition at line 42 of file sPHElectronPairv1.h.
View newest version in sPHENIX GitHub at line 42 of file sPHElectronPairv1.h
Referenced by get_type(), set_type(), and sPHElectronPairv1().
The documentation for this class was generated from the following files:
analysis/blob/master/EventMix/src/sPHElectronPairv1.h
analysis/blob/master/EventMix/src/sPHElectronPairv1.cc