Analysis Software: TPCHitTrackDisplay Class Reference
TPCHitTrackDisplay Class Reference
#include <coresoftware/blob/master/offline/packages/TPCHitTrackDisplay/TPCHitTrackDisplay.h>
Public Member Functions
TPCHitTrackDisplay (const std::string &name="TPCHitTrackDisplay")
int Init (PHCompositeNode *)
int InitRun (PHCompositeNode *)
int process_event (PHCompositeNode *)
int EndRun (const int)
Called at the end of each run.
void set_pdgcode (const int thispdgcode)
void setCutADC (float value)
void setIncludeTracklessClusters (float value)
Public Member Functions inherited from SubsysReco
~SubsysReco () override
virtual int End (PHCompositeNode *)
Called at the end of all processing.
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
void Print (const std::string &="ALL") const override
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Private Member Functions
void SimulationOut (PHCompositeNode *)
Private Attributes
float m_cut_ADC
bool m_trackless_clusters
int _event
int _pdgcode
std::string _fileName
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = std::numeric_limits<int>::max() - 10
}
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Detailed Description
Definition at line 33 of file TPCHitTrackDisplay.h.
View newest version in sPHENIX GitHub at line 33 of file TPCHitTrackDisplay.h
Constructor & Destructor Documentation
TPCHitTrackDisplay::TPCHitTrackDisplay (const std::string & name = "TPCHitTrackDisplay")
Definition at line 61 of file TPCHitTrackDisplay.cc.
View newest version in sPHENIX GitHub at line 61 of file TPCHitTrackDisplay.cc
References _event.
Member Function Documentation
int TPCHitTrackDisplay::EndRun (const int) virtual
Called at the end of each run.
Reimplemented from SubsysReco.
Definition at line 105 of file TPCHitTrackDisplay.cc.
View newest version in sPHENIX GitHub at line 105 of file TPCHitTrackDisplay.cc
References Fun4AllReturnCodes::EVENT_OK.
int TPCHitTrackDisplay::Init (PHCompositeNode *) virtual
Called during initialization. Typically this is where you can book histograms, and e.g. register them to Fun4AllServer (so they can be output to file using Fun4AllServer::dumpHistos() method).
Reimplemented from SubsysReco.
Definition at line 76 of file TPCHitTrackDisplay.cc.
View newest version in sPHENIX GitHub at line 76 of file TPCHitTrackDisplay.cc
References Fun4AllReturnCodes::EVENT_OK.
int TPCHitTrackDisplay::InitRun (PHCompositeNode *) virtual
Called for first event when run number is known. Typically this is where you may want to fetch data from database, because you know the run number.
Reimplemented from SubsysReco.
Definition at line 81 of file TPCHitTrackDisplay.cc.
View newest version in sPHENIX GitHub at line 81 of file TPCHitTrackDisplay.cc
References Fun4AllReturnCodes::EVENT_OK.
int TPCHitTrackDisplay::process_event (PHCompositeNode *) virtual
Called for each event. This is where you do the real work.
Reimplemented from SubsysReco.
Definition at line 92 of file TPCHitTrackDisplay.cc.
View newest version in sPHENIX GitHub at line 92 of file TPCHitTrackDisplay.cc
References _event, Fun4AllReturnCodes::EVENT_OK, and SimulationOut().
void TPCHitTrackDisplay::set_pdgcode (const int thispdgcode) inline
Definition at line 50 of file TPCHitTrackDisplay.h.
View newest version in sPHENIX GitHub at line 50 of file TPCHitTrackDisplay.h
References _pdgcode.
void TPCHitTrackDisplay::setCutADC (float value) inline
Definition at line 53 of file TPCHitTrackDisplay.h.
View newest version in sPHENIX GitHub at line 53 of file TPCHitTrackDisplay.h
References m_cut_ADC, and value.
void TPCHitTrackDisplay::setIncludeTracklessClusters (float value) inline
Definition at line 56 of file TPCHitTrackDisplay.h.
View newest version in sPHENIX GitHub at line 56 of file TPCHitTrackDisplay.h
References m_trackless_clusters, and value.
void TPCHitTrackDisplay::SimulationOut (PHCompositeNode * topNode) private
Definition at line 216 of file TPCHitTrackDisplay.cc.
View newest version in sPHENIX GitHub at line 216 of file TPCHitTrackDisplay.cc
References _event, _fileName, _pdgcode, SvtxTrackMap::begin(), Acts::PhysicalConstants::c, clusters, SvtxTrackMap::end(), TrkrClusterContainer::findCluster(), INTTVtxZ::fname, material_mapping_optimisation::format, Acts::Test::geometry, CentralityInfov1::get_centile(), SvtxTrack::get_charge(), SvtxTrack::get_px(), SvtxTrack::get_py(), SvtxTrack::get_pz(), SvtxTrack::get_silicon_seed(), SvtxTrack::get_tpc_seed(), TrkrCluster::getAdc(), TrkrClusterContainer::getClusters(), TrkrClusterContainer::getHitSetKeys(), m_cut_ADC, m_trackless_clusters, out, PHWHERE, Acts::Test::pos, ambiguity_solver_full_chain::x, y, and physmon_track_finding_ttbar::z.
Referenced by process_event().
Member Data Documentation
int TPCHitTrackDisplay::_event private
Definition at line 64 of file TPCHitTrackDisplay.h.
View newest version in sPHENIX GitHub at line 64 of file TPCHitTrackDisplay.h
Referenced by process_event(), SimulationOut(), and TPCHitTrackDisplay().
std::string TPCHitTrackDisplay::_fileName private
Definition at line 66 of file TPCHitTrackDisplay.h.
View newest version in sPHENIX GitHub at line 66 of file TPCHitTrackDisplay.h
Referenced by SimulationOut().
int TPCHitTrackDisplay::_pdgcode private
Definition at line 65 of file TPCHitTrackDisplay.h.
View newest version in sPHENIX GitHub at line 65 of file TPCHitTrackDisplay.h
Referenced by set_pdgcode(), and SimulationOut().
float TPCHitTrackDisplay::m_cut_ADC private
Definition at line 60 of file TPCHitTrackDisplay.h.
View newest version in sPHENIX GitHub at line 60 of file TPCHitTrackDisplay.h
Referenced by setCutADC(), and SimulationOut().
bool TPCHitTrackDisplay::m_trackless_clusters private
Definition at line 61 of file TPCHitTrackDisplay.h.
View newest version in sPHENIX GitHub at line 61 of file TPCHitTrackDisplay.h
Referenced by setIncludeTracklessClusters(), and SimulationOut().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/TPCHitTrackDisplay/TPCHitTrackDisplay.h
coresoftware/blob/master/offline/packages/TPCHitTrackDisplay/TPCHitTrackDisplay.cc