Analysis Software: JetBkgdSub Class Reference
JetBkgdSub Class Reference
#include <analysis/blob/master/JS-Jet/JetBkgdSub/src/JetBkgdSub.h>
Public Member Functions
JetBkgdSub (const double jet_R=0.4, const std::string &outputfilename="jettree.root")
~JetBkgdSub () override
void doIterative (bool b=true)
void doAreaSub (bool b=true)
void doMultSub (bool b=true)
void doTruth (bool b=true)
void doData (bool b=true)
void doEmbed (bool b=true)
void doTowerECut (bool b=true)
void setEtaRange (double low, double high)
void setPtRange (double low, double high)
void setMinRecoPt (double pt)
void setVzCut (double cut)
void setTowerThreshold (double threshold)
void add_input (JetInput *input)
float LeadingR04TruthJet (PHCompositeNode *topNode)
int Init (PHCompositeNode *topNode) override
int process_event (PHCompositeNode *topNode) override
int ResetEvent (PHCompositeNode *topNode) override
Clean up after each event.
int End (PHCompositeNode *topNode) override
Called at the end of all processing.
void EstimateRhoMult (PHCompositeNode *topNode)
double GetMedian (std::vector< double > &v)
void GetCentInfo (PHCompositeNode *topNode)
float NSignalCorrection (float jet_pt, int cent)
Public Member Functions inherited from SubsysReco
~SubsysReco () override
virtual int EndRun (const int)
Called at the end of each run.
virtual int InitRun (PHCompositeNode *)
virtual int Reset (PHCompositeNode *)
Reset.
void Print (const std::string &="ALL") const override
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Private Attributes
double m_jet_R
std::string m_iter_input
std::string m_raw_input
std::string m_truth_input
std::string m_outputfilename
std::pair< double, double > m_etaRange
std::pair< double, double > m_ptRange
double _minrecopT
double m_vtxZ_cut
double m_towerThreshold
std::vector< JetInput * > _inputs
bool _doIterative
bool _doAreaSub
bool _doMultSub
bool _doTruth
bool _doData
bool _doEmbed
bool _doTowerECut
int m_event
int m_rhoA_jets
int m_mult_jets
int m_iter_jets
int m_truth_jets
int m_centrality
double m_mbd_NS
double m_rho_area
double m_rho_area_sigma
double m_rho_area_CEMC
double m_rho_area_sigma_CEMC
double m_rho_area_IHCAL
double m_rho_area_sigma_IHCAL
double m_rho_area_OHCAL
double m_rho_area_sigma_OHCAL
double m_rho_mult
float m_event_leading_truth_pt
TTree * m_tree
std::vector< float > m_iter_eta
std::vector< float > m_iter_phi
std::vector< float > m_iter_pt
std::vector< float > m_iter_pt_unsub
std::vector< float > m_rhoA_eta
std::vector< float > m_rhoA_phi
std::vector< float > m_rhoA_pt
std::vector< float > m_rhoA_area
std::vector< float > m_rhoA_pt_unsub
std::vector< int > m_mult_ncomponent
std::vector< float > m_mult_nsignal
std::vector< float > m_mult_eta
std::vector< float > m_mult_phi
std::vector< float > m_mult_pt
std::vector< float > m_mult_pt_unsub
std::vector< int > m_truth_ncomponent
std::vector< float > m_truth_eta
std::vector< float > m_truth_phi
std::vector< float > m_truth_pt
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = std::numeric_limits<int>::max() - 10
}
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Detailed Description
Definition at line 20 of file JetBkgdSub.h.
View newest version in sPHENIX GitHub at line 20 of file JetBkgdSub.h
Constructor & Destructor Documentation
JetBkgdSub::JetBkgdSub (const double jet_R = 0.4, const std::string & outputfilename = "jettree.root")
Definition at line 57 of file JetBkgdSub.cc.
View newest version in sPHENIX GitHub at line 57 of file JetBkgdSub.cc
JetBkgdSub::~JetBkgdSub () override
Definition at line 111 of file JetBkgdSub.cc.
View newest version in sPHENIX GitHub at line 111 of file JetBkgdSub.cc
References _inputs.
Member Function Documentation
void JetBkgdSub::add_input (JetInput * input) inline
Definition at line 56 of file JetBkgdSub.h.
View newest version in sPHENIX GitHub at line 56 of file JetBkgdSub.h
References _inputs.
Referenced by Fun4All_JetBkgd(), and Fun4All_JetBkgd_Embed().
void JetBkgdSub::doAreaSub (bool b = true) inline
Definition at line 31 of file JetBkgdSub.h.
View newest version in sPHENIX GitHub at line 31 of file JetBkgdSub.h
References _doAreaSub, and KFPMath::b.
Referenced by Fun4All_JetBkgd(), and Fun4All_JetBkgd_Embed().
void JetBkgdSub::doData (bool b = true) inline
Definition at line 34 of file JetBkgdSub.h.
View newest version in sPHENIX GitHub at line 34 of file JetBkgdSub.h
References _doData, and KFPMath::b.
Referenced by Fun4All_JetBkgd_Embed().
void JetBkgdSub::doEmbed (bool b = true) inline
Definition at line 35 of file JetBkgdSub.h.
View newest version in sPHENIX GitHub at line 35 of file JetBkgdSub.h
References _doEmbed, and KFPMath::b.
Referenced by Fun4All_JetBkgd_Embed().
void JetBkgdSub::doIterative (bool b = true) inline
Definition at line 30 of file JetBkgdSub.h.
View newest version in sPHENIX GitHub at line 30 of file JetBkgdSub.h
References _doIterative, and KFPMath::b.
Referenced by Fun4All_JetBkgd(), and Fun4All_JetBkgd_Embed().
void JetBkgdSub::doMultSub (bool b = true) inline
Definition at line 32 of file JetBkgdSub.h.
View newest version in sPHENIX GitHub at line 32 of file JetBkgdSub.h
References _doMultSub, and KFPMath::b.
Referenced by Fun4All_JetBkgd(), and Fun4All_JetBkgd_Embed().
void JetBkgdSub::doTowerECut (bool b = true) inline
Definition at line 36 of file JetBkgdSub.h.
View newest version in sPHENIX GitHub at line 36 of file JetBkgdSub.h
References _doTowerECut, and KFPMath::b.
Referenced by Fun4All_JetBkgd_Embed().
void JetBkgdSub::doTruth (bool b = true) inline
Definition at line 33 of file JetBkgdSub.h.
View newest version in sPHENIX GitHub at line 33 of file JetBkgdSub.h
References _doTruth, and KFPMath::b.
Referenced by Fun4All_JetBkgd(), and Fun4All_JetBkgd_Embed().
int JetBkgdSub::End (PHCompositeNode *) override virtual
Called at the end of all processing.
Reimplemented from SubsysReco.
Definition at line 911 of file JetBkgdSub.cc.
View newest version in sPHENIX GitHub at line 911 of file JetBkgdSub.cc
References PHTFileServer::cd(), Fun4AllReturnCodes::EVENT_OK, PHTFileServer::get(), m_outputfilename, and PHTFileServer::write().
void JetBkgdSub::EstimateRhoMult (PHCompositeNode * topNode)
Definition at line 683 of file JetBkgdSub.cc.
View newest version in sPHENIX GitHub at line 683 of file JetBkgdSub.cc
References _inputs, JetAlgo::get_jets(), GetMedian(), Jet::KT, and m_rho_mult.
Referenced by process_event().
void JetBkgdSub::GetCentInfo (PHCompositeNode * topNode)
Definition at line 585 of file JetBkgdSub.cc.
View newest version in sPHENIX GitHub at line 585 of file JetBkgdSub.cc
References _doData, PHNodeIterator::findFirst(), CentralityInfo::get_centile(), MbdOut::get_q(), CentralityInfo::get_quantity(), m_centrality, m_mbd_NS, and Fun4AllBase::Name().
Referenced by process_event().
double JetBkgdSub::GetMedian (std::vector< double > & v)
Definition at line 740 of file JetBkgdSub.cc.
View newest version in sPHENIX GitHub at line 740 of file JetBkgdSub.cc
References size, and Acts::Experimental::detail::BlueprintHelper::sort().
Referenced by EstimateRhoMult().
int JetBkgdSub::Init (PHCompositeNode *) override virtual
Called during initialization. Typically this is where you can book histograms, and e.g. register them to Fun4AllServer (so they can be output to file using Fun4AllServer::dumpHistos() method).
Reimplemented from SubsysReco.
Definition at line 120 of file JetBkgdSub.cc.
View newest version in sPHENIX GitHub at line 120 of file JetBkgdSub.cc
References _doAreaSub, _doIterative, _doMultSub, _doTruth, _minrecopT, Fun4AllReturnCodes::EVENT_OK, PHTFileServer::get(), m_centrality, m_etaRange, m_event, m_event_leading_truth_pt, m_iter_eta, m_iter_input, m_iter_jets, m_iter_phi, m_iter_pt, m_iter_pt_unsub, m_jet_R, m_mbd_NS, m_mult_eta, m_mult_jets, m_mult_ncomponent, m_mult_nsignal, m_mult_phi, m_mult_pt, m_mult_pt_unsub, m_outputfilename, m_ptRange, m_raw_input, m_rho_area, m_rho_area_CEMC, m_rho_area_IHCAL, m_rho_area_OHCAL, m_rho_area_sigma, m_rho_area_sigma_CEMC, m_rho_area_sigma_IHCAL, m_rho_area_sigma_OHCAL, m_rho_mult, m_rhoA_area, m_rhoA_eta, m_rhoA_jets, m_rhoA_phi, m_rhoA_pt, m_rhoA_pt_unsub, m_tree, m_truth_eta, m_truth_input, m_truth_jets, m_truth_ncomponent, m_truth_phi, m_truth_pt, PHTFileServer::open(), and to_string().
float JetBkgdSub::LeadingR04TruthJet (PHCompositeNode * topNode)
Definition at line 661 of file JetBkgdSub.cc.
View newest version in sPHENIX GitHub at line 661 of file JetBkgdSub.cc
References JetMap::begin(), JetMap::end(), and Jet::get_pt().
Referenced by process_event().
float JetBkgdSub::NSignalCorrection (float jet_pt, int cent)
Definition at line 758 of file JetBkgdSub.cc.
View newest version in sPHENIX GitHub at line 758 of file JetBkgdSub.cc
References m_jet_R.
Referenced by process_event().
int JetBkgdSub::process_event (PHCompositeNode *) override virtual
Called for each event. This is where you do the real work.
Reimplemented from SubsysReco.
Definition at line 215 of file JetBkgdSub.cc.
View newest version in sPHENIX GitHub at line 215 of file JetBkgdSub.cc
References _doAreaSub, _doData, _doEmbed, _doIterative, _doMultSub, _doTowerECut, _doTruth, _inputs, _minrecopT, Fun4AllReturnCodes::ABORTEVENT, antikt_algorithm, JetMap::begin(), channel(), mvtx_utils::comp(), TowerInfoContainer::encode_key(), RawTowerDefs::encode_towerid(), JetMap::end(), EstimateRhoMult(), Fun4AllReturnCodes::EVENT_OK, GlobalVertexMap::get(), Jet::get_comp_vec(), TowerInfo::get_energy(), Jet::get_eta(), JetContainer::get_jet(), Jet::get_phi(), TowerBackground::get_Psi2(), Jet::get_pt(), TowerInfoContainer::get_tower_at_channel(), TowerBackground::get_UE(), TowerBackground::get_v2(), GlobalVertex::get_z(), GetCentInfo(), TowerInfoContainer::getTowerEtaBin(), TowerInfoContainer::getTowerPhiBin(), RawTowerDefs::HCALIN, RawTowerDefs::HCALOUT, i, kt_algorithm, LeadingR04TruthJet(), m_centrality, m_etaRange, m_event, m_event_leading_truth_pt, m_iter_eta, m_iter_input, m_iter_jets, m_iter_phi, m_iter_pt, m_iter_pt_unsub, m_jet_R, m_mult_eta, m_mult_jets, m_mult_ncomponent, m_mult_nsignal, m_mult_phi, m_mult_pt, m_mult_pt_unsub, m_ptRange, m_raw_input, m_rho_area, m_rho_area_CEMC, m_rho_area_IHCAL, m_rho_area_OHCAL, m_rho_area_sigma, m_rho_area_sigma_CEMC, m_rho_area_sigma_IHCAL, m_rho_area_sigma_OHCAL, m_rho_mult, m_rhoA_area, m_rhoA_eta, m_rhoA_jets, m_rhoA_phi, m_rhoA_pt, m_rhoA_pt_unsub, m_towerThreshold, m_tree, m_truth_eta, m_truth_input, m_truth_jets, m_truth_ncomponent, m_truth_phi, m_truth_pt, m_vtxZ_cut, NSignalCorrection(), merge_hashes::p, physmon_track_finding_ttbar::pt, SelectorAbsEtaMax(), SelectorNHardest(), Jet::set_e(), Jet::set_px(), Jet::set_py(), Jet::set_pz(), JetContainer::size(), Jet::size_comp(), sorted_by_pt(), and Fun4AllBase::Verbosity().
int JetBkgdSub::ResetEvent (PHCompositeNode *) override virtual
Clean up after each event.
Reimplemented from SubsysReco.
Definition at line 629 of file JetBkgdSub.cc.
View newest version in sPHENIX GitHub at line 629 of file JetBkgdSub.cc
References Fun4AllReturnCodes::EVENT_OK, m_iter_eta, m_iter_phi, m_iter_pt, m_iter_pt_unsub, m_mult_eta, m_mult_ncomponent, m_mult_nsignal, m_mult_phi, m_mult_pt, m_mult_pt_unsub, m_rhoA_area, m_rhoA_eta, m_rhoA_phi, m_rhoA_pt, m_rhoA_pt_unsub, m_truth_eta, m_truth_ncomponent, m_truth_phi, and m_truth_pt.
void JetBkgdSub::setEtaRange (double low, double high) inline
Definition at line 38 of file JetBkgdSub.h.
View newest version in sPHENIX GitHub at line 38 of file JetBkgdSub.h
References m_etaRange.
Referenced by Fun4All_JetBkgd(), and Fun4All_JetBkgd_Embed().
void JetBkgdSub::setMinRecoPt (double pt) inline
Definition at line 50 of file JetBkgdSub.h.
View newest version in sPHENIX GitHub at line 50 of file JetBkgdSub.h
References _minrecopT, and physmon_track_finding_ttbar::pt.
Referenced by Fun4All_JetBkgd(), and Fun4All_JetBkgd_Embed().
void JetBkgdSub::setPtRange (double low, double high) inline
Definition at line 44 of file JetBkgdSub.h.
View newest version in sPHENIX GitHub at line 44 of file JetBkgdSub.h
References m_ptRange.
Referenced by Fun4All_JetBkgd(), and Fun4All_JetBkgd_Embed().
void JetBkgdSub::setTowerThreshold (double threshold) inline
Definition at line 54 of file JetBkgdSub.h.
View newest version in sPHENIX GitHub at line 54 of file JetBkgdSub.h
References m_towerThreshold.
Referenced by Fun4All_JetBkgd_Embed().
void JetBkgdSub::setVzCut (double cut) inline
Definition at line 52 of file JetBkgdSub.h.
View newest version in sPHENIX GitHub at line 52 of file JetBkgdSub.h
References m_vtxZ_cut.
Member Data Documentation
bool JetBkgdSub::_doAreaSub private
Definition at line 87 of file JetBkgdSub.h.
View newest version in sPHENIX GitHub at line 87 of file JetBkgdSub.h
Referenced by doAreaSub(), Init(), and process_event().
bool JetBkgdSub::_doData private
Definition at line 90 of file JetBkgdSub.h.
View newest version in sPHENIX GitHub at line 90 of file JetBkgdSub.h
Referenced by doData(), GetCentInfo(), and process_event().
bool JetBkgdSub::_doEmbed private
Definition at line 91 of file JetBkgdSub.h.
View newest version in sPHENIX GitHub at line 91 of file JetBkgdSub.h
Referenced by doEmbed(), and process_event().
bool JetBkgdSub::_doIterative private
Definition at line 86 of file JetBkgdSub.h.
View newest version in sPHENIX GitHub at line 86 of file JetBkgdSub.h
Referenced by doIterative(), Init(), and process_event().
bool JetBkgdSub::_doMultSub private
Definition at line 88 of file JetBkgdSub.h.
View newest version in sPHENIX GitHub at line 88 of file JetBkgdSub.h
Referenced by doMultSub(), Init(), and process_event().
bool JetBkgdSub::_doTowerECut private
Definition at line 92 of file JetBkgdSub.h.
View newest version in sPHENIX GitHub at line 92 of file JetBkgdSub.h
Referenced by doTowerECut(), and process_event().
bool JetBkgdSub::_doTruth private
Definition at line 89 of file JetBkgdSub.h.
View newest version in sPHENIX GitHub at line 89 of file JetBkgdSub.h
Referenced by doTruth(), Init(), and process_event().
std::vector<JetInput *> JetBkgdSub::_inputs private
Definition at line 85 of file JetBkgdSub.h.
View newest version in sPHENIX GitHub at line 85 of file JetBkgdSub.h
Referenced by add_input(), EstimateRhoMult(), process_event(), and ~JetBkgdSub().
double JetBkgdSub::_minrecopT private
Definition at line 82 of file JetBkgdSub.h.
View newest version in sPHENIX GitHub at line 82 of file JetBkgdSub.h
Referenced by Init(), process_event(), and setMinRecoPt().
int JetBkgdSub::m_centrality private
Definition at line 101 of file JetBkgdSub.h.
View newest version in sPHENIX GitHub at line 101 of file JetBkgdSub.h
Referenced by GetCentInfo(), Init(), and process_event().
std::pair<double, double> JetBkgdSub::m_etaRange private
Definition at line 80 of file JetBkgdSub.h.
View newest version in sPHENIX GitHub at line 80 of file JetBkgdSub.h
Referenced by Init(), process_event(), and setEtaRange().
int JetBkgdSub::m_event private
Definition at line 96 of file JetBkgdSub.h.
View newest version in sPHENIX GitHub at line 96 of file JetBkgdSub.h
Referenced by Init(), and process_event().
float JetBkgdSub::m_event_leading_truth_pt private
Definition at line 113 of file JetBkgdSub.h.
View newest version in sPHENIX GitHub at line 113 of file JetBkgdSub.h
Referenced by Init(), and process_event().
std::vector<float> JetBkgdSub::m_iter_eta private
Definition at line 118 of file JetBkgdSub.h.
View newest version in sPHENIX GitHub at line 118 of file JetBkgdSub.h
Referenced by Init(), process_event(), and ResetEvent().
std::string JetBkgdSub::m_iter_input private
Definition at line 76 of file JetBkgdSub.h.
View newest version in sPHENIX GitHub at line 76 of file JetBkgdSub.h
Referenced by Init(), and process_event().
int JetBkgdSub::m_iter_jets private
Definition at line 99 of file JetBkgdSub.h.
View newest version in sPHENIX GitHub at line 99 of file JetBkgdSub.h
Referenced by Init(), and process_event().
std::vector<float> JetBkgdSub::m_iter_phi private
Definition at line 119 of file JetBkgdSub.h.
View newest version in sPHENIX GitHub at line 119 of file JetBkgdSub.h
Referenced by Init(), process_event(), and ResetEvent().
std::vector<float> JetBkgdSub::m_iter_pt private
Definition at line 120 of file JetBkgdSub.h.
View newest version in sPHENIX GitHub at line 120 of file JetBkgdSub.h
Referenced by Init(), process_event(), and ResetEvent().
std::vector<float> JetBkgdSub::m_iter_pt_unsub private
Definition at line 121 of file JetBkgdSub.h.
View newest version in sPHENIX GitHub at line 121 of file JetBkgdSub.h
Referenced by Init(), process_event(), and ResetEvent().
double JetBkgdSub::m_jet_R private
Definition at line 75 of file JetBkgdSub.h.
View newest version in sPHENIX GitHub at line 75 of file JetBkgdSub.h
Referenced by Init(), NSignalCorrection(), and process_event().
double JetBkgdSub::m_mbd_NS private
Definition at line 102 of file JetBkgdSub.h.
View newest version in sPHENIX GitHub at line 102 of file JetBkgdSub.h
Referenced by GetCentInfo(), and Init().
std::vector<float> JetBkgdSub::m_mult_eta private
Definition at line 133 of file JetBkgdSub.h.
View newest version in sPHENIX GitHub at line 133 of file JetBkgdSub.h
Referenced by Init(), process_event(), and ResetEvent().
int JetBkgdSub::m_mult_jets private
Definition at line 98 of file JetBkgdSub.h.
View newest version in sPHENIX GitHub at line 98 of file JetBkgdSub.h
Referenced by Init(), and process_event().
std::vector<int> JetBkgdSub::m_mult_ncomponent private
Definition at line 131 of file JetBkgdSub.h.
View newest version in sPHENIX GitHub at line 131 of file JetBkgdSub.h
Referenced by Init(), process_event(), and ResetEvent().
std::vector<float> JetBkgdSub::m_mult_nsignal private
Definition at line 132 of file JetBkgdSub.h.
View newest version in sPHENIX GitHub at line 132 of file JetBkgdSub.h
Referenced by Init(), process_event(), and ResetEvent().
std::vector<float> JetBkgdSub::m_mult_phi private
Definition at line 134 of file JetBkgdSub.h.
View newest version in sPHENIX GitHub at line 134 of file JetBkgdSub.h
Referenced by Init(), process_event(), and ResetEvent().
std::vector<float> JetBkgdSub::m_mult_pt private
Definition at line 135 of file JetBkgdSub.h.
View newest version in sPHENIX GitHub at line 135 of file JetBkgdSub.h
Referenced by Init(), process_event(), and ResetEvent().
std::vector<float> JetBkgdSub::m_mult_pt_unsub private
Definition at line 136 of file JetBkgdSub.h.
View newest version in sPHENIX GitHub at line 136 of file JetBkgdSub.h
Referenced by Init(), process_event(), and ResetEvent().
std::string JetBkgdSub::m_outputfilename private
Definition at line 79 of file JetBkgdSub.h.
View newest version in sPHENIX GitHub at line 79 of file JetBkgdSub.h
Referenced by End(), and Init().
std::pair<double, double> JetBkgdSub::m_ptRange private
Definition at line 81 of file JetBkgdSub.h.
View newest version in sPHENIX GitHub at line 81 of file JetBkgdSub.h
Referenced by Init(), process_event(), and setPtRange().
std::string JetBkgdSub::m_raw_input private
Definition at line 77 of file JetBkgdSub.h.
View newest version in sPHENIX GitHub at line 77 of file JetBkgdSub.h
Referenced by Init(), and process_event().
double JetBkgdSub::m_rho_area private
Definition at line 103 of file JetBkgdSub.h.
View newest version in sPHENIX GitHub at line 103 of file JetBkgdSub.h
Referenced by Init(), and process_event().
double JetBkgdSub::m_rho_area_CEMC private
Definition at line 105 of file JetBkgdSub.h.
View newest version in sPHENIX GitHub at line 105 of file JetBkgdSub.h
Referenced by Init(), and process_event().
double JetBkgdSub::m_rho_area_IHCAL private
Definition at line 107 of file JetBkgdSub.h.
View newest version in sPHENIX GitHub at line 107 of file JetBkgdSub.h
Referenced by Init(), and process_event().
double JetBkgdSub::m_rho_area_OHCAL private
Definition at line 109 of file JetBkgdSub.h.
View newest version in sPHENIX GitHub at line 109 of file JetBkgdSub.h
Referenced by Init(), and process_event().
double JetBkgdSub::m_rho_area_sigma private
Definition at line 104 of file JetBkgdSub.h.
View newest version in sPHENIX GitHub at line 104 of file JetBkgdSub.h
Referenced by Init(), and process_event().
double JetBkgdSub::m_rho_area_sigma_CEMC private
Definition at line 106 of file JetBkgdSub.h.
View newest version in sPHENIX GitHub at line 106 of file JetBkgdSub.h
Referenced by Init(), and process_event().
double JetBkgdSub::m_rho_area_sigma_IHCAL private
Definition at line 108 of file JetBkgdSub.h.
View newest version in sPHENIX GitHub at line 108 of file JetBkgdSub.h
Referenced by Init(), and process_event().
double JetBkgdSub::m_rho_area_sigma_OHCAL private
Definition at line 110 of file JetBkgdSub.h.
View newest version in sPHENIX GitHub at line 110 of file JetBkgdSub.h
Referenced by Init(), and process_event().
double JetBkgdSub::m_rho_mult private
Definition at line 111 of file JetBkgdSub.h.
View newest version in sPHENIX GitHub at line 111 of file JetBkgdSub.h
Referenced by EstimateRhoMult(), Init(), and process_event().
std::vector<float> JetBkgdSub::m_rhoA_area private
Definition at line 127 of file JetBkgdSub.h.
View newest version in sPHENIX GitHub at line 127 of file JetBkgdSub.h
Referenced by Init(), process_event(), and ResetEvent().
std::vector<float> JetBkgdSub::m_rhoA_eta private
Definition at line 124 of file JetBkgdSub.h.
View newest version in sPHENIX GitHub at line 124 of file JetBkgdSub.h
Referenced by Init(), process_event(), and ResetEvent().
int JetBkgdSub::m_rhoA_jets private
Definition at line 97 of file JetBkgdSub.h.
View newest version in sPHENIX GitHub at line 97 of file JetBkgdSub.h
Referenced by Init(), and process_event().
std::vector<float> JetBkgdSub::m_rhoA_phi private
Definition at line 125 of file JetBkgdSub.h.
View newest version in sPHENIX GitHub at line 125 of file JetBkgdSub.h
Referenced by Init(), process_event(), and ResetEvent().
std::vector<float> JetBkgdSub::m_rhoA_pt private
Definition at line 126 of file JetBkgdSub.h.
View newest version in sPHENIX GitHub at line 126 of file JetBkgdSub.h
Referenced by Init(), process_event(), and ResetEvent().
std::vector<float> JetBkgdSub::m_rhoA_pt_unsub private
Definition at line 128 of file JetBkgdSub.h.
View newest version in sPHENIX GitHub at line 128 of file JetBkgdSub.h
Referenced by Init(), process_event(), and ResetEvent().
double JetBkgdSub::m_towerThreshold private
Definition at line 84 of file JetBkgdSub.h.
View newest version in sPHENIX GitHub at line 84 of file JetBkgdSub.h
Referenced by process_event(), and setTowerThreshold().
TTree* JetBkgdSub::m_tree private
Definition at line 116 of file JetBkgdSub.h.
View newest version in sPHENIX GitHub at line 116 of file JetBkgdSub.h
Referenced by Init(), and process_event().
std::vector<float> JetBkgdSub::m_truth_eta private
Definition at line 140 of file JetBkgdSub.h.
View newest version in sPHENIX GitHub at line 140 of file JetBkgdSub.h
Referenced by Init(), process_event(), and ResetEvent().
std::string JetBkgdSub::m_truth_input private
Definition at line 78 of file JetBkgdSub.h.
View newest version in sPHENIX GitHub at line 78 of file JetBkgdSub.h
Referenced by Init(), and process_event().
int JetBkgdSub::m_truth_jets private
Definition at line 100 of file JetBkgdSub.h.
View newest version in sPHENIX GitHub at line 100 of file JetBkgdSub.h
Referenced by Init(), and process_event().
std::vector<int> JetBkgdSub::m_truth_ncomponent private
Definition at line 139 of file JetBkgdSub.h.
View newest version in sPHENIX GitHub at line 139 of file JetBkgdSub.h
Referenced by Init(), process_event(), and ResetEvent().
std::vector<float> JetBkgdSub::m_truth_phi private
Definition at line 141 of file JetBkgdSub.h.
View newest version in sPHENIX GitHub at line 141 of file JetBkgdSub.h
Referenced by Init(), process_event(), and ResetEvent().
std::vector<float> JetBkgdSub::m_truth_pt private
Definition at line 142 of file JetBkgdSub.h.
View newest version in sPHENIX GitHub at line 142 of file JetBkgdSub.h
Referenced by Init(), process_event(), and ResetEvent().
double JetBkgdSub::m_vtxZ_cut private
Definition at line 83 of file JetBkgdSub.h.
View newest version in sPHENIX GitHub at line 83 of file JetBkgdSub.h
Referenced by process_event(), and setVzCut().
The documentation for this class was generated from the following files:
analysis/blob/master/JS-Jet/JetBkgdSub/src/JetBkgdSub.h
analysis/blob/master/JS-Jet/JetBkgdSub/src/JetBkgdSub.cc