Analysis Software: analysis/blob/master/ZDC-CALIB/zdc_calib.C File Reference
zdc_calib.C File Reference
Macros
#define Nmodules 3
Functions
bool calculateWeights (float energy, std::vector< std::vector< float > > &in_data, TVectorD &out_weights, TMatrixD &out_matrix)
void zdc_calib (TString filename="", float e=100)
Variables
float E_n
float no_booster_weight [3] = {1,1,1}
std::vector< float > skip_zdc_mod = {1,1,1}
float uncorr_lo = 133.138
float uncorr_hi = 224.234
Macro Definition Documentation
#define Nmodules 3
Definition at line 6 of file zdc_calib.C.
View newest version in sPHENIX GitHub at line 6 of file zdc_calib.C
Referenced by zdc_calib().
Function Documentation
bool calculateWeights (float energy, std::vector< std::vector< float > > & in_data, TVectorD & out_weights, TMatrixD & out_matrix)
Definition at line 17 of file zdc_calib.C.
View newest version in sPHENIX GitHub at line 17 of file zdc_calib.C
References Acts::Test::dim, double(), energy, i, and utils::status.
Referenced by zdc_calib().
void zdc_calib (TString filename = "", float e = 100)
Definition at line 76 of file zdc_calib.C.
View newest version in sPHENIX GitHub at line 76 of file zdc_calib.C
References calculateWeights(), configureMap::data, Acts::UnitConstants::e, event, filename, fout, i, Nmodules, no_booster_weight, sum(), uncorr_hi, uncorr_lo, ambiguity_solver_full_chain::x, y, and physmon_track_finding_ttbar::z.
Variable Documentation
float E_n
Definition at line 7 of file zdc_calib.C.
View newest version in sPHENIX GitHub at line 7 of file zdc_calib.C
float no_booster_weight[3] = {1,1,1}
Definition at line 9 of file zdc_calib.C.
View newest version in sPHENIX GitHub at line 9 of file zdc_calib.C
Referenced by zdc_calib().
std::vector<float> skip_zdc_mod = {1,1,1}
Definition at line 10 of file zdc_calib.C.
View newest version in sPHENIX GitHub at line 10 of file zdc_calib.C
float uncorr_hi = 224.234
Definition at line 14 of file zdc_calib.C.
View newest version in sPHENIX GitHub at line 14 of file zdc_calib.C
Referenced by zdc_calib().
float uncorr_lo = 133.138
Definition at line 13 of file zdc_calib.C.
View newest version in sPHENIX GitHub at line 13 of file zdc_calib.C
Referenced by zdc_calib().