Analysis Software: PHNodeDump Class Reference
PHNodeDump Class Reference
#include <coresoftware/blob/master/offline/packages/NodeDump/PHNodeDump.h>
Public Member Functions
PHNodeDump ()
~PHNodeDump () override
int CloseOutputFiles ()
int GetGlobalVars (PHCompositeNode *topNode)
int RunNumber ()
int EvtSequence ()
int AddIgnore (const std::string &name)
int Select (const std::string &name)
void SetOutDir (const std::string &dirname)
void SetPrecision (const int digits)
void PrintEvtSeq (const int i)
Public Member Functions inherited from PHNodeOperation
PHNodeOperation ()
virtual ~PHNodeOperation ()
void operator() (PHNode &o)
void operator() (PHNode *o)
virtual void Verbosity (const int i)
virtual int Verbosity () const
Private Member Functions
void perform (PHNode *) override
int AddDumpObject (const std::string &NodeName, PHNode *node)
int initdump (const std::string &newnode, DumpObject *dmp)
Private Attributes
std::map< std::string,
DumpObject * > dumpthis
std::set< std::string > ignore
std::set< std::string > exclusive
int runnumber = 0
int evtsequence = -9999
int fp_precision = -1
std::string outdir = "./"
int print_evtseq = 1
Additional Inherited Members
Protected Attributes inherited from PHNodeOperation
int verbosity
Detailed Description
Definition at line 14 of file PHNodeDump.h.
View newest version in sPHENIX GitHub at line 14 of file PHNodeDump.h
Constructor & Destructor Documentation
PHNodeDump::PHNodeDump () inline
Definition at line 17 of file PHNodeDump.h.
View newest version in sPHENIX GitHub at line 17 of file PHNodeDump.h
PHNodeDump::~PHNodeDump () override
Definition at line 77 of file PHNodeDump.cc.
View newest version in sPHENIX GitHub at line 77 of file PHNodeDump.cc
References dumpthis, exclusive, and ignore.
Member Function Documentation
int PHNodeDump::AddDumpObject (const std::string & NodeName, PHNode * node) private
Definition at line 170 of file PHNodeDump.cc.
View newest version in sPHENIX GitHub at line 170 of file PHNodeDump.cc
References exclusive, PHNode::getType(), ignore, initdump(), DumpObject::NoOutput(), print_evtseq, DumpObject::PrintEvtSeq(), and Acts::Test::tmp().
Referenced by perform().
int PHNodeDump::AddIgnore (const std::string & name)
Definition at line 89 of file PHNodeDump.cc.
View newest version in sPHENIX GitHub at line 89 of file PHNodeDump.cc
References ignore, and PHWHERE.
Referenced by Dumper::AddIgnore().
int PHNodeDump::CloseOutputFiles ()
Definition at line 160 of file PHNodeDump.cc.
View newest version in sPHENIX GitHub at line 160 of file PHNodeDump.cc
References dumpthis.
Referenced by Dumper::End().
int PHNodeDump::EvtSequence () inline
Definition at line 23 of file PHNodeDump.h.
View newest version in sPHENIX GitHub at line 23 of file PHNodeDump.h
References evtsequence.
Referenced by DumpObject::process_event().
int PHNodeDump::GetGlobalVars (PHCompositeNode * topNode)
Definition at line 113 of file PHNodeDump.cc.
View newest version in sPHENIX GitHub at line 113 of file PHNodeDump.cc
References evtsequence, EventHeader::get_EvtSequence(), RunHeader::get_RunNumber(), and runnumber.
Referenced by Dumper::process_event().
int PHNodeDump::initdump (const std::string & newnode, DumpObject * dmp) private
Definition at line 445 of file PHNodeDump.cc.
View newest version in sPHENIX GitHub at line 445 of file PHNodeDump.cc
References dumpthis, fp_precision, DumpObject::Init(), outdir, DumpObject::SetOutDir(), DumpObject::SetParentNodeDump(), and DumpObject::SetPrecision().
Referenced by AddDumpObject().
void PHNodeDump::perform (PHNode * node) override private virtual
Implements PHNodeOperation.
Definition at line 128 of file PHNodeDump.cc.
View newest version in sPHENIX GitHub at line 128 of file PHNodeDump.cc
References AddDumpObject(), dumpthis, PHNode::getName(), and PHNode::getType().
void PHNodeDump::PrintEvtSeq (const int i) inline
Definition at line 29 of file PHNodeDump.h.
View newest version in sPHENIX GitHub at line 29 of file PHNodeDump.h
References i, and print_evtseq.
Referenced by Dumper::End().
int PHNodeDump::RunNumber () inline
Definition at line 22 of file PHNodeDump.h.
View newest version in sPHENIX GitHub at line 22 of file PHNodeDump.h
References runnumber.
Referenced by DumpObject::process_event().
int PHNodeDump::Select (const std::string & name)
Definition at line 101 of file PHNodeDump.cc.
View newest version in sPHENIX GitHub at line 101 of file PHNodeDump.cc
References exclusive, and PHWHERE.
Referenced by Dumper::Select().
void PHNodeDump::SetOutDir (const std::string & dirname) inline
Definition at line 27 of file PHNodeDump.h.
View newest version in sPHENIX GitHub at line 27 of file PHNodeDump.h
References outdir.
Referenced by Dumper::SetOutDir().
void PHNodeDump::SetPrecision (const int digits) inline
Definition at line 28 of file PHNodeDump.h.
View newest version in sPHENIX GitHub at line 28 of file PHNodeDump.h
References fp_precision.
Referenced by Dumper::SetPrecision().
Member Data Documentation
std::map<std::string, DumpObject *> PHNodeDump::dumpthis private
Definition at line 35 of file PHNodeDump.h.
View newest version in sPHENIX GitHub at line 35 of file PHNodeDump.h
Referenced by CloseOutputFiles(), initdump(), perform(), and ~PHNodeDump().
int PHNodeDump::evtsequence = -9999 private
Definition at line 39 of file PHNodeDump.h.
View newest version in sPHENIX GitHub at line 39 of file PHNodeDump.h
Referenced by EvtSequence(), and GetGlobalVars().
std::set<std::string> PHNodeDump::exclusive private
Definition at line 37 of file PHNodeDump.h.
View newest version in sPHENIX GitHub at line 37 of file PHNodeDump.h
Referenced by AddDumpObject(), Select(), and ~PHNodeDump().
int PHNodeDump::fp_precision = -1 private
Definition at line 40 of file PHNodeDump.h.
View newest version in sPHENIX GitHub at line 40 of file PHNodeDump.h
Referenced by initdump(), and SetPrecision().
std::set<std::string> PHNodeDump::ignore private
Definition at line 36 of file PHNodeDump.h.
View newest version in sPHENIX GitHub at line 36 of file PHNodeDump.h
Referenced by AddDumpObject(), AddIgnore(), and ~PHNodeDump().
std::string PHNodeDump::outdir = "./" private
Definition at line 41 of file PHNodeDump.h.
View newest version in sPHENIX GitHub at line 41 of file PHNodeDump.h
Referenced by initdump(), and SetOutDir().
int PHNodeDump::print_evtseq = 1 private
Definition at line 42 of file PHNodeDump.h.
View newest version in sPHENIX GitHub at line 42 of file PHNodeDump.h
Referenced by AddDumpObject(), and PrintEvtSeq().
int PHNodeDump::runnumber = 0 private
Definition at line 38 of file PHNodeDump.h.
View newest version in sPHENIX GitHub at line 38 of file PHNodeDump.h
Referenced by GetGlobalVars(), and RunNumber().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/NodeDump/PHNodeDump.h
coresoftware/blob/master/offline/packages/NodeDump/PHNodeDump.cc