Analysis Software: Acts::RectangleBounds Class Reference
Acts::RectangleBounds Class Reference
#include <acts/blob/sPHENIX/Core/include/Acts/Surfaces/RectangleBounds.hpp>
Public Types
enum BoundValues : int {
eMinX = 0, eMinY = 1, eMaxX = 2, eMaxY = 3,
eSize = 4
}
Public Member Functions
RectangleBounds ()=delete
RectangleBounds (double halfX, double halfY) noexcept(false)
m_max ({halfX, halfY})
RectangleBounds (const std::array< double, eSize > &values) noexcept(false)
m_max ({values[eMaxX], values[eMaxY]})
RectangleBounds (const Vector2 &min, const Vector2 &max) noexcept(false)
~RectangleBounds () override=default
BoundsType type () const final
std::vector< double > values () const final
bool inside (const Vector2 &lposition, const BoundaryCheck &bcheck) const final
std::vector< Vector2 > vertices (unsigned int lseg=1) const final
const RectangleBounds & boundingBox () const final
std::ostream & toStream (std::ostream &sl) const final
double get (BoundValues bValue) const
double halfLengthX () const
Access to the half length in X.
double halfLengthY () const
Access to the half length in Y.
const Vector2 & min () const
const Vector2 & max () const
Private Member Functions
void checkConsistency () noexcept(false)
Private Attributes
Vector2 m_min
Vector2 m_max
Detailed Description
Bounds for a rectangular, planar surface - it can be used to for rectangles that are symmetrically centered around (0./0.) and for generic shifted rectangles
Definition at line 30 of file RectangleBounds.hpp.
View newest version in sPHENIX GitHub at line 30 of file RectangleBounds.hpp
Member Enumeration Documentation
enum Acts::RectangleBounds::BoundValues : int
Enumerator:
eMinX
eMinY
eMaxX
eMaxY
eSize
Definition at line 32 of file RectangleBounds.hpp.
View newest version in sPHENIX GitHub at line 32 of file RectangleBounds.hpp
Constructor & Destructor Documentation
Acts::RectangleBounds::RectangleBounds () delete
Acts::RectangleBounds::RectangleBounds (double halfX, double halfY) inline noexcept
Constructor with halflength in x and y - symmetric
Parameters
halfX halflength in X
halfY halflength in Y
Definition at line 46 of file RectangleBounds.hpp.
View newest version in sPHENIX GitHub at line 46 of file RectangleBounds.hpp
Acts::RectangleBounds::RectangleBounds (const std::array< double, eSize > & values) inline noexcept
Constructor - from fixed size array - generic
Parameters
values The parameter values
Definition at line 54 of file RectangleBounds.hpp.
View newest version in sPHENIX GitHub at line 54 of file RectangleBounds.hpp
References eMinX, eMinY, and values().
Acts::RectangleBounds::RectangleBounds (const Vector2 & min, const Vector2 & max) inline noexcept
Constructor - from min/max - generic
Parameters
min The left bottom corner
max The right top corning
Definition at line 64 of file RectangleBounds.hpp.
View newest version in sPHENIX GitHub at line 64 of file RectangleBounds.hpp
References checkConsistency().
Acts::RectangleBounds::~RectangleBounds () override default
Member Function Documentation
const Acts::RectangleBounds & Acts::RectangleBounds::boundingBox () const final virtual
Bounding box parameters
Returns
rectangle bounds for a bounding box
Implements Acts::PlanarBounds.
Definition at line 25 of file RectangleBounds.cpp.
View newest version in sPHENIX GitHub at line 25 of file RectangleBounds.cpp
void Acts::RectangleBounds::checkConsistency () inline private noexcept
Check the input values for consistency, will throw a logic_exception if consistency is not given
Definition at line 170 of file RectangleBounds.hpp.
View newest version in sPHENIX GitHub at line 170 of file RectangleBounds.hpp
References eMaxX, eMaxY, eMinX, and eMinY.
Referenced by RectangleBounds().
double Acts::RectangleBounds::get (BoundValues bValue) const inline
Access to the bound values
Parameters
bValue the class nested enum for the array access
Definition at line 154 of file RectangleBounds.hpp.
View newest version in sPHENIX GitHub at line 154 of file RectangleBounds.hpp
References assert, eMaxX, eMaxY, eMinX, eMinY, m_max, and m_min.
Referenced by Acts::adjustBinUtility(), Acts::MappingMaterialDecorator::binnedSurfaceMaterial(), and Acts::Test::BOOST_AUTO_TEST_CASE().
double Acts::RectangleBounds::halfLengthX () const inline
Access to the half length in X.
Definition at line 142 of file RectangleBounds.hpp.
View newest version in sPHENIX GitHub at line 142 of file RectangleBounds.hpp
References m_max, and m_min.
Referenced by Acts::Test::BOOST_AUTO_TEST_CASE(), and CylinderGeomMicromegas::find_strip_from_local_coords().
double Acts::RectangleBounds::halfLengthY () const inline
Access to the half length in Y.
Definition at line 146 of file RectangleBounds.hpp.
View newest version in sPHENIX GitHub at line 146 of file RectangleBounds.hpp
References m_max, and m_min.
Referenced by Acts::Test::BOOST_AUTO_TEST_CASE().
bool Acts::RectangleBounds::inside (const Vector2 & lposition, const BoundaryCheck & bcheck) const final virtual
Inside check for the bounds object driven by the boundary check directive Each Bounds has a method inside, which checks if a LocalPosition is inside the bounds Inside can be called without/with tolerances.
Parameters
lposition Local position (assumed to be in right surface frame)
bcheck boundary check directive
Returns
boolean indicator for the success of this operation
Implements Acts::SurfaceBounds.
Definition at line 14 of file RectangleBounds.cpp.
View newest version in sPHENIX GitHub at line 14 of file RectangleBounds.cpp
References Acts::BoundaryCheck::isInside(), m_max, and m_min.
Referenced by Acts::Test::BOOST_AUTO_TEST_CASE().
Acts::RectangleBounds::m_max ({halfX, halfY}) inline
Definition at line 47 of file RectangleBounds.hpp.
View newest version in sPHENIX GitHub at line 47 of file RectangleBounds.hpp
References Acts::Test::halfX, and Acts::Test::halfY.
Acts::RectangleBounds::m_max ({values[eMaxX], values[eMaxY]}) inline
Definition at line 56 of file RectangleBounds.hpp.
View newest version in sPHENIX GitHub at line 56 of file RectangleBounds.hpp
References eMaxX, eMaxY, and values().
const Vector2 & Acts::RectangleBounds::max () const inline
Get the max vertex defining the bounds
Returns
The max vertex
Definition at line 138 of file RectangleBounds.hpp.
View newest version in sPHENIX GitHub at line 138 of file RectangleBounds.hpp
References m_max.
Referenced by Acts::Test::BOOST_AUTO_TEST_CASE().
const Vector2 & Acts::RectangleBounds::min () const inline
Get the min vertex defining the bounds
Returns
The min vertex
Definition at line 134 of file RectangleBounds.hpp.
View newest version in sPHENIX GitHub at line 134 of file RectangleBounds.hpp
References m_min.
Referenced by Acts::Test::BOOST_AUTO_TEST_CASE().
std::ostream & Acts::RectangleBounds::toStream (std::ostream & sl) const final virtual
Output Method for std::ostream
Parameters
sl is the ostream for the dump
Implements Acts::SurfaceBounds.
Definition at line 30 of file RectangleBounds.cpp.
View newest version in sPHENIX GitHub at line 30 of file RectangleBounds.cpp
References Acts::UnitConstants::min.
SurfaceBounds::BoundsType Acts::RectangleBounds::type () const inline final virtual
Return the bounds type - for persistency optimization
Returns
is a BoundsType enum
Implements Acts::SurfaceBounds.
Definition at line 130 of file RectangleBounds.hpp.
View newest version in sPHENIX GitHub at line 130 of file RectangleBounds.hpp
References Acts::SurfaceBounds::eRectangle.
Referenced by Acts::Test::BOOST_AUTO_TEST_CASE().
std::vector< double > Acts::RectangleBounds::values () const inline final virtual
Access method for bound values, this is a dynamically sized vector containing the parameters needed to describe these bounds
Returns
of the stored values for this SurfaceBounds object
Implements Acts::SurfaceBounds.
Definition at line 150 of file RectangleBounds.hpp.
View newest version in sPHENIX GitHub at line 150 of file RectangleBounds.hpp
References m_max, and m_min.
Referenced by Acts::Test::BOOST_AUTO_TEST_CASE(), m_max(), and RectangleBounds().
std::vector< Acts::Vector2 > Acts::RectangleBounds::vertices (unsigned int lseg = 1) const final virtual
Return the vertices
Parameters
lseg the number of segments used to approximate and eventually curved line
Note
the number of segments is ignored in this representation
Returns
vector for vertices in 2D
Implements Acts::PlanarBounds.
Definition at line 19 of file RectangleBounds.cpp.
View newest version in sPHENIX GitHub at line 19 of file RectangleBounds.cpp
Referenced by Acts::Test::BOOST_AUTO_TEST_CASE(), and Acts::Test::dumpVertices().
Member Data Documentation
Vector2 Acts::RectangleBounds::m_max private
Definition at line 123 of file RectangleBounds.hpp.
View newest version in sPHENIX GitHub at line 123 of file RectangleBounds.hpp
Referenced by get(), halfLengthX(), halfLengthY(), inside(), max(), and values().
Vector2 Acts::RectangleBounds::m_min private
Definition at line 122 of file RectangleBounds.hpp.
View newest version in sPHENIX GitHub at line 122 of file RectangleBounds.hpp
Referenced by get(), halfLengthX(), halfLengthY(), inside(), min(), and values().
The documentation for this class was generated from the following files:
acts/blob/sPHENIX/Core/include/Acts/Surfaces/RectangleBounds.hpp
acts/blob/sPHENIX/Core/src/Surfaces/RectangleBounds.cpp