Analysis Software: TowerInfoContainer Class Reference
TowerInfoContainer Class Reference
#include <coresoftware/blob/master/offline/packages/CaloBase/TowerInfoContainer.h>
Public Types
enum DETECTOR {
EMCAL = 0, HCAL = 1, SEPD = 2, MBD = 3,
ZDC = 4, DETECTOR_INVALID = 9999
}
typedef std::map< unsigned int,
TowerInfo * > TowerMap
typedef TowerMap::const_iterator ConstIter
typedef TowerMap::iterator Iter
Public Member Functions
TowerInfoContainer ()=default
~TowerInfoContainer () override=default
void identify (std::ostream &os=std::cout) const override
virtual void Reset () override
Clear Event.
virtual TowerInfo * get_tower_at_channel (int)
virtual TowerInfo * get_tower_at_key (int)
virtual size_t size () const
virtual unsigned int encode_key (unsigned int)
virtual unsigned int decode_key (unsigned int)
virtual unsigned int encode_epd (unsigned int)
virtual unsigned int encode_hcal (unsigned int)
virtual unsigned int encode_emcal (unsigned int)
virtual unsigned int encode_mbd (unsigned int)
virtual unsigned int encode_zdc (unsigned int)
virtual unsigned int decode_epd (unsigned int)
virtual unsigned int decode_hcal (unsigned int)
virtual unsigned int decode_emcal (unsigned int)
virtual unsigned int decode_mbd (unsigned int)
virtual unsigned int decode_zdc (unsigned int)
virtual unsigned int getTowerPhiBin (unsigned int)
virtual unsigned int getTowerEtaBin (unsigned int)
virtual DETECTOR get_detectorid () const
Public Member Functions inherited from PHObject
PHObject ()
ctor
~PHObject () override
dtor
virtual PHObject * CloneMe () const
Virtual copy constructor.
virtual PHObject * clone () const final
PHObject * Clone (const char *newname="") const final
void Copy (TObject &object) const final
virtual int isValid () const
isValid returns non zero if object contains vailid data
virtual int Integrate () const
virtual int Integrate (PHObject *)
virtual void CopyFrom (const PHObject *obj)
Private Member Functions
ClassDefOverride (TowerInfoContainer, 1)
Detailed Description
Definition at line 11 of file TowerInfoContainer.h.
View newest version in sPHENIX GitHub at line 11 of file TowerInfoContainer.h
Member Typedef Documentation
typedef TowerMap::const_iterator TowerInfoContainer::ConstIter
Definition at line 15 of file TowerInfoContainer.h.
View newest version in sPHENIX GitHub at line 15 of file TowerInfoContainer.h
typedef TowerMap::iterator TowerInfoContainer::Iter
Definition at line 16 of file TowerInfoContainer.h.
View newest version in sPHENIX GitHub at line 16 of file TowerInfoContainer.h
typedef std::map<unsigned int, TowerInfo*> TowerInfoContainer::TowerMap
Definition at line 14 of file TowerInfoContainer.h.
View newest version in sPHENIX GitHub at line 14 of file TowerInfoContainer.h
Member Enumeration Documentation
enum TowerInfoContainer::DETECTOR
Enumerator:
EMCAL
HCAL
SEPD
MBD
ZDC
DETECTOR_INVALID
Definition at line 18 of file TowerInfoContainer.h.
View newest version in sPHENIX GitHub at line 18 of file TowerInfoContainer.h
Constructor & Destructor Documentation
TowerInfoContainer::TowerInfoContainer () default
TowerInfoContainer::~TowerInfoContainer () override default
Member Function Documentation
TowerInfoContainer::ClassDefOverride (TowerInfoContainer , 1) private
unsigned int TowerInfoContainer::decode_emcal (unsigned int tower_key) virtual
Definition at line 44 of file TowerInfoContainer.cc.
View newest version in sPHENIX GitHub at line 44 of file TowerInfoContainer.cc
References TowerInfoDefs::decode_emcal(), and index.
Referenced by TowerInfoContainerv1::decode_key(), TowerInfoContainerv3::decode_key(), and TowerInfoContainerv2::decode_key().
unsigned int TowerInfoContainer::decode_epd (unsigned int tower_key) virtual
Definition at line 38 of file TowerInfoContainer.cc.
View newest version in sPHENIX GitHub at line 38 of file TowerInfoContainer.cc
References TowerInfoDefs::decode_epd(), and index.
Referenced by TowerInfoContainerv1::decode_key(), TowerInfoContainerv3::decode_key(), and TowerInfoContainerv2::decode_key().
unsigned int TowerInfoContainer::decode_hcal (unsigned int tower_key) virtual
Definition at line 50 of file TowerInfoContainer.cc.
View newest version in sPHENIX GitHub at line 50 of file TowerInfoContainer.cc
References TowerInfoDefs::decode_hcal(), and index.
Referenced by TowerInfoContainerv1::decode_key(), TowerInfoContainerv3::decode_key(), and TowerInfoContainerv2::decode_key().
virtual unsigned int TowerInfoContainer::decode_key (unsigned int) inline virtual
Reimplemented in TowerInfoContainerv1, TowerInfoContainerv2, and TowerInfoContainerv3.
Definition at line 38 of file TowerInfoContainer.h.
View newest version in sPHENIX GitHub at line 38 of file TowerInfoContainer.h
Referenced by RawClusterPositionCorrection::process_event(), PHG4EPDModuleReco::process_event(), RetowerCEMC::process_event(), and pi0EtaByEta::process_towers().
unsigned int TowerInfoContainer::decode_mbd (unsigned int tower_key) virtual
Definition at line 56 of file TowerInfoContainer.cc.
View newest version in sPHENIX GitHub at line 56 of file TowerInfoContainer.cc
References TowerInfoDefs::decode_mbd(), and index.
Referenced by TowerInfoContainerv1::decode_key(), TowerInfoContainerv3::decode_key(), and TowerInfoContainerv2::decode_key().
unsigned int TowerInfoContainer::decode_zdc (unsigned int tower_key) virtual
Definition at line 61 of file TowerInfoContainer.cc.
View newest version in sPHENIX GitHub at line 61 of file TowerInfoContainer.cc
References TowerInfoDefs::decode_zdc(), and index.
Referenced by TowerInfoContainerv1::decode_key(), TowerInfoContainerv3::decode_key(), and TowerInfoContainerv2::decode_key().
unsigned int TowerInfoContainer::encode_emcal (unsigned int towerIndex) virtual
Definition at line 15 of file TowerInfoContainer.cc.
View newest version in sPHENIX GitHub at line 15 of file TowerInfoContainer.cc
References TowerInfoDefs::encode_emcal().
Referenced by TowerInfoContainerv1::encode_key(), TowerInfoContainerv3::encode_key(), and TowerInfoContainerv2::encode_key().
unsigned int TowerInfoContainer::encode_epd (unsigned int towerIndex) virtual
Definition at line 9 of file TowerInfoContainer.cc.
View newest version in sPHENIX GitHub at line 9 of file TowerInfoContainer.cc
References TowerInfoDefs::encode_epd().
Referenced by TowerInfoContainerv1::encode_key(), TowerInfoContainerv3::encode_key(), and TowerInfoContainerv2::encode_key().
unsigned int TowerInfoContainer::encode_hcal (unsigned int towerIndex) virtual
Definition at line 21 of file TowerInfoContainer.cc.
View newest version in sPHENIX GitHub at line 21 of file TowerInfoContainer.cc
References TowerInfoDefs::encode_hcal().
Referenced by TowerInfoContainerv1::encode_key(), TowerInfoContainerv3::encode_key(), and TowerInfoContainerv2::encode_key().
virtual unsigned int TowerInfoContainer::encode_key (unsigned int) inline virtual
Reimplemented in TowerInfoContainerv1, TowerInfoContainerv2, and TowerInfoContainerv3.
Definition at line 37 of file TowerInfoContainer.h.
View newest version in sPHENIX GitHub at line 37 of file TowerInfoContainer.h
Referenced by HCalJetPhiShift::FillTTree(), TowerJetInput::get_input(), Emcal_Tower_Masking::process_event(), RawClusterBuilderTemplate::process_event(), RawClusterBuilderTopo::process_event(), CaloTowerCalib::process_event(), CaloTowerStatus::process_event(), G4TowerNtuple::process_event(), ClusterIso::process_event(), SubtractTowers::process_event(), CopyAndSubtractJets::process_event(), RetowerCEMC::process_event(), DetermineTowerBackground::process_event(), CaloTriggerSim::process_event(), caloTowerEmbed::process_event(), caloTreeGen::process_event(), JetBkgdSub::process_event(), LiteCaloEval::process_event(), JetValidation::process_event(), EMJetVal::process_event(), sPHAnalysis_calo::process_event_data(), HCalCalibTree::process_towers(), CaloAna::process_towers(), CaloValid::process_towers(), and pi0EtaByEta::process_towers().
unsigned int TowerInfoContainer::encode_mbd (unsigned int towerIndex) virtual
Definition at line 27 of file TowerInfoContainer.cc.
View newest version in sPHENIX GitHub at line 27 of file TowerInfoContainer.cc
References TowerInfoDefs::encode_mbd().
Referenced by TowerInfoContainerv1::encode_key(), TowerInfoContainerv3::encode_key(), and TowerInfoContainerv2::encode_key().
unsigned int TowerInfoContainer::encode_zdc (unsigned int towerIndex) virtual
Definition at line 32 of file TowerInfoContainer.cc.
View newest version in sPHENIX GitHub at line 32 of file TowerInfoContainer.cc
References TowerInfoDefs::encode_zdc().
Referenced by TowerInfoContainerv1::encode_key(), TowerInfoContainerv3::encode_key(), and TowerInfoContainerv2::encode_key().
virtual DETECTOR TowerInfoContainer::get_detectorid () const inline virtual
Reimplemented in TowerInfoContainerv1, TowerInfoContainerv2, and TowerInfoContainerv3.
Definition at line 55 of file TowerInfoContainer.h.
View newest version in sPHENIX GitHub at line 55 of file TowerInfoContainer.h
References DETECTOR_INVALID.
virtual TowerInfo* TowerInfoContainer::get_tower_at_channel (int) inline virtual
Reimplemented in TowerInfoContainerv1, TowerInfoContainerv2, TowerInfoContainerv3, and BbcPmtInfoContainerV1.
Definition at line 33 of file TowerInfoContainer.h.
View newest version in sPHENIX GitHub at line 33 of file TowerInfoContainer.h
Referenced by MinimumBiasClassifier::FillMinimumBiasInfo(), HCalJetPhiShift::FillTTree(), TowerJetInput::get_input(), MultiDetectorMultiplicity::getEMCalTotalEnergy(), MultiDetectorMultiplicity::getIHCalTotalEnergy(), MultiDetectorMultiplicity::getOHCalTotalEnergy(), MultiDetectorMultiplicity::getsEPDTotalEnergy(), BbcCheck::process_emcal(), RawClusterBuilderTemplate::process_event(), Emcal_Tower_Masking::process_event(), RawClusterPositionCorrection::process_event(), EventPlaneReco::process_event(), PHG4EPDModuleReco::process_event(), CaloTowerBuilder::process_event(), CaloTowerCalib::process_event(), CaloTowerStatus::process_event(), RawClusterBuilderTopo::process_event(), G4TowerNtuple::process_event(), SubtractTowers::process_event(), ClusterIso::process_event(), RetowerCEMC::process_event(), CopyAndSubtractJets::process_event(), CaloTriggerSim::process_event(), caloTowerEmbed::process_event(), DetermineTowerBackground::process_event(), CaloWaveformSim::process_event(), JetNconstituents::process_event(), JetBkgdSub::process_event(), LiteCaloEval::process_event(), JetValidation::process_event(), EMJetVal::process_event(), sPHAnalysis_calo::process_event_data(), BbcCheck::process_ihcal(), DumpTowerInfoContainer::process_Node(), BbcCheck::process_ohcal(), CaloTowerBuilder::process_sim(), HCalCalibTree::process_towers(), CaloAna::process_towers(), CaloValid::process_towers(), pi0EtaByEta::process_towers(), and BbcCheck::process_zdc().
virtual TowerInfo* TowerInfoContainer::get_tower_at_key (int) inline virtual
Reimplemented in TowerInfoContainerv1, TowerInfoContainerv2, and TowerInfoContainerv3.
Definition at line 34 of file TowerInfoContainer.h.
View newest version in sPHENIX GitHub at line 34 of file TowerInfoContainer.h
Referenced by PHActsTrackProjection::getSquareTowerEnergies(), PHG4InnerHcalSteppingAction::NoHitSteppingAction(), PHG4OuterHcalSteppingAction::NoHitSteppingAction(), PHG4IHCalSteppingAction::NoHitSteppingAction(), PHG4OHCalSteppingAction::NoHitSteppingAction(), PHG4SpacalSteppingAction::NoHitSteppingAction(), RawClusterDeadHotMask::process_event(), TowerInfoDeadHotMask::process_event(), RawTowerBuilder::process_event(), RawTowerDeadTowerInterp::process_event(), HcalRawTowerBuilder::process_event(), RawTowerDigitizer::process_event(), and PHGenFitTrackProjection::process_event().
unsigned int TowerInfoContainer::getTowerEtaBin (unsigned int key) virtual
Definition at line 73 of file TowerInfoContainer.cc.
View newest version in sPHENIX GitHub at line 73 of file TowerInfoContainer.cc
References KF_timing::etabin, and TowerInfoDefs::getCaloTowerEtaBin().
Referenced by HCalJetPhiShift::FillTTree(), TowerJetInput::get_input(), Emcal_Tower_Masking::process_event(), RawClusterBuilderTemplate::process_event(), RunTowerInfo::process_event(), RawClusterBuilderTopo::process_event(), RawTowerCalibration::process_event(), G4TowerNtuple::process_event(), ClusterIso::process_event(), SubtractTowers::process_event(), CopyAndSubtractJets::process_event(), RetowerCEMC::process_event(), CaloTriggerSim::process_event(), DetermineTowerBackground::process_event(), caloTowerEmbed::process_event(), JetBkgdSub::process_event(), LiteCaloEval::process_event(), JetValidation::process_event(), EMJetVal::process_event(), sPHAnalysis_calo::process_event_data(), HCalCalibTree::process_towers(), CaloAna::process_towers(), CaloValid::process_towers(), and pi0EtaByEta::process_towers().
unsigned int TowerInfoContainer::getTowerPhiBin (unsigned int key) virtual
Definition at line 67 of file TowerInfoContainer.cc.
View newest version in sPHENIX GitHub at line 67 of file TowerInfoContainer.cc
References TowerInfoDefs::getCaloTowerPhiBin().
Referenced by HCalJetPhiShift::FillTTree(), TowerJetInput::get_input(), Emcal_Tower_Masking::process_event(), RawClusterBuilderTemplate::process_event(), RunTowerInfo::process_event(), RawClusterBuilderTopo::process_event(), RawTowerCalibration::process_event(), G4TowerNtuple::process_event(), ClusterIso::process_event(), SubtractTowers::process_event(), CopyAndSubtractJets::process_event(), RetowerCEMC::process_event(), CaloTriggerSim::process_event(), DetermineTowerBackground::process_event(), caloTowerEmbed::process_event(), JetBkgdSub::process_event(), LiteCaloEval::process_event(), JetValidation::process_event(), EMJetVal::process_event(), sPHAnalysis_calo::process_event_data(), HCalCalibTree::process_towers(), CaloAna::process_towers(), CaloValid::process_towers(), and pi0EtaByEta::process_towers().
void TowerInfoContainer::identify (std::ostream & os = std::cout) const override virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from PHObject.
Reimplemented in TowerInfoContainerv1, TowerInfoContainerv2, and TowerInfoContainerv3.
Definition at line 4 of file TowerInfoContainer.cc.
View newest version in sPHENIX GitHub at line 4 of file TowerInfoContainer.cc
virtual void TowerInfoContainer::Reset () inline override virtual
Clear Event.
Reimplemented from PHObject.
Reimplemented in TowerInfoContainerv1, TowerInfoContainerv2, TowerInfoContainerv3, and BbcPmtInfoContainerV1.
Definition at line 32 of file TowerInfoContainer.h.
View newest version in sPHENIX GitHub at line 32 of file TowerInfoContainer.h
virtual size_t TowerInfoContainer::size (void) const inline virtual
Reimplemented in TowerInfoContainerv1, TowerInfoContainerv2, TowerInfoContainerv3, and BbcPmtInfoContainerV1.
Definition at line 35 of file TowerInfoContainer.h.
View newest version in sPHENIX GitHub at line 35 of file TowerInfoContainer.h
Referenced by MinimumBiasClassifier::FillMinimumBiasInfo(), HCalJetPhiShift::FillTTree(), TowerJetInput::get_input(), MultiDetectorMultiplicity::getEMCalTotalEnergy(), MultiDetectorMultiplicity::getIHCalTotalEnergy(), MultiDetectorMultiplicity::getOHCalTotalEnergy(), MultiDetectorMultiplicity::getsEPDTotalEnergy(), BbcCheck::process_emcal(), RawClusterBuilderTemplate::process_event(), Emcal_Tower_Masking::process_event(), EventPlaneReco::process_event(), CaloTowerCalib::process_event(), CaloTowerStatus::process_event(), RawClusterBuilderTopo::process_event(), G4TowerNtuple::process_event(), ClusterIso::process_event(), SubtractTowers::process_event(), RetowerCEMC::process_event(), CaloTriggerSim::process_event(), caloTowerEmbed::process_event(), DetermineTowerBackground::process_event(), caloTreeGen::process_event(), hcal_towerid::process_event(), towerid::process_event(), LiteCaloEval::process_event(), sPHAnalysis_calo::process_event_data(), BbcCheck::process_ihcal(), DumpTowerInfoContainer::process_Node(), BbcCheck::process_ohcal(), CaloTowerBuilder::process_sim(), HCalCalibTree::process_towers(), CaloAna::process_towers(), CaloValid::process_towers(), pi0EtaByEta::process_towers(), and BbcCheck::process_zdc().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/CaloBase/TowerInfoContainer.h
coresoftware/blob/master/offline/packages/CaloBase/TowerInfoContainer.cc