Analysis Software: acts/blob/sPHENIX/Tests/UnitTests/Core/Utilities/MultiIndexTests.cpp File Reference
MultiIndexTests.cpp File Reference
#include <boost/test/unit_test.hpp>
#include "Acts/Utilities/MultiIndex.hpp"
#include <array>
#include <cstddef>
#include <cstdint>
#include <unordered_set>
#include <boost/mpl/list.hpp>
Typedefs
using Index32 = Acts::MultiIndex< uint32_t, 16, 8, 8 >
using Index64 = Acts::MultiIndex< uint64_t, 13, 17, 21, 13 >
using Indices = boost::mpl::list< Index32, Index64 >
Functions
BOOST_AUTO_TEST_CASE_TEMPLATE (triviality, T, Indices)
BOOST_AUTO_TEST_CASE (index32_construct)
BOOST_AUTO_TEST_CASE (index32_set)
BOOST_AUTO_TEST_CASE (index32_set_overflow)
BOOST_AUTO_TEST_CASE (index64_set_overflow)
BOOST_AUTO_TEST_CASE (index32_encode)
BOOST_AUTO_TEST_CASE (index64_encode)
BOOST_AUTO_TEST_CASE (uint32_sibling)
BOOST_AUTO_TEST_CASE (uint64_sibling)
BOOST_AUTO_TEST_CASE (uint32_descendant)
BOOST_AUTO_TEST_CASE (uint64_descendant)
BOOST_AUTO_TEST_CASE (index32_as_key)
BOOST_AUTO_TEST_CASE (index64_as_key)
Typedef Documentation
using Index32 = Acts::MultiIndex<uint32_t, 16, 8, 8>
Definition at line 21 of file MultiIndexTests.cpp.
View newest version in sPHENIX GitHub at line 21 of file MultiIndexTests.cpp
using Index64 = Acts::MultiIndex<uint64_t, 13, 17, 21, 13>
Definition at line 23 of file MultiIndexTests.cpp.
View newest version in sPHENIX GitHub at line 23 of file MultiIndexTests.cpp
using Indices = boost::mpl::list<Index32, Index64>
Definition at line 24 of file MultiIndexTests.cpp.
View newest version in sPHENIX GitHub at line 24 of file MultiIndexTests.cpp
Function Documentation
BOOST_AUTO_TEST_CASE (index32_construct)
Definition at line 38 of file MultiIndexTests.cpp.
View newest version in sPHENIX GitHub at line 38 of file MultiIndexTests.cpp
References ambiguity_solver_full_chain::idx, Acts::MultiIndex< T, BitsPerLevel >::level(), physmon_ckf_tracking::u, and Acts::MultiIndex< T, BitsPerLevel >::value().
BOOST_AUTO_TEST_CASE (index32_set)
Definition at line 57 of file MultiIndexTests.cpp.
View newest version in sPHENIX GitHub at line 57 of file MultiIndexTests.cpp
References ambiguity_solver_full_chain::idx, Acts::MultiIndex< T, BitsPerLevel >::level(), Acts::MultiIndex< T, BitsPerLevel >::set(), physmon_ckf_tracking::u, Acts::MultiIndex< T, BitsPerLevel >::value(), and Acts::MultiIndex< T, BitsPerLevel >::Zeros().
BOOST_AUTO_TEST_CASE (index32_set_overflow)
Definition at line 73 of file MultiIndexTests.cpp.
View newest version in sPHENIX GitHub at line 73 of file MultiIndexTests.cpp
References physmon_ckf_tracking::u, and Acts::MultiIndex< T, BitsPerLevel >::Zeros().
BOOST_AUTO_TEST_CASE (index64_set_overflow)
Definition at line 89 of file MultiIndexTests.cpp.
View newest version in sPHENIX GitHub at line 89 of file MultiIndexTests.cpp
References physmon_ckf_tracking::u, and Acts::MultiIndex< T, BitsPerLevel >::Zeros().
BOOST_AUTO_TEST_CASE (index32_encode)
Definition at line 106 of file MultiIndexTests.cpp.
View newest version in sPHENIX GitHub at line 106 of file MultiIndexTests.cpp
References Acts::MultiIndex< T, BitsPerLevel >::Encode(), physmon_ckf_tracking::u, and Acts::MultiIndex< T, BitsPerLevel >::Zeros().
BOOST_AUTO_TEST_CASE (index64_encode)
Definition at line 131 of file MultiIndexTests.cpp.
View newest version in sPHENIX GitHub at line 131 of file MultiIndexTests.cpp
References Acts::MultiIndex< T, BitsPerLevel >::Encode(), physmon_ckf_tracking::u, and Acts::MultiIndex< T, BitsPerLevel >::Zeros().
BOOST_AUTO_TEST_CASE (uint32_sibling)
Definition at line 166 of file MultiIndexTests.cpp.
View newest version in sPHENIX GitHub at line 166 of file MultiIndexTests.cpp
References Acts::MultiIndex< T, BitsPerLevel >::Encode(), ambiguity_solver_full_chain::idx, and physmon_ckf_tracking::u.
BOOST_AUTO_TEST_CASE (uint64_sibling)
Definition at line 173 of file MultiIndexTests.cpp.
View newest version in sPHENIX GitHub at line 173 of file MultiIndexTests.cpp
References Acts::MultiIndex< T, BitsPerLevel >::Encode(), ambiguity_solver_full_chain::idx, and physmon_ckf_tracking::u.
BOOST_AUTO_TEST_CASE (uint32_descendant)
Definition at line 182 of file MultiIndexTests.cpp.
View newest version in sPHENIX GitHub at line 182 of file MultiIndexTests.cpp
References Acts::MultiIndex< T, BitsPerLevel >::Encode(), ambiguity_solver_full_chain::idx, and physmon_ckf_tracking::u.
BOOST_AUTO_TEST_CASE (uint64_descendant)
Definition at line 190 of file MultiIndexTests.cpp.
View newest version in sPHENIX GitHub at line 190 of file MultiIndexTests.cpp
References Acts::MultiIndex< T, BitsPerLevel >::Encode(), ambiguity_solver_full_chain::idx, and physmon_ckf_tracking::u.
BOOST_AUTO_TEST_CASE (index32_as_key)
Definition at line 207 of file MultiIndexTests.cpp.
View newest version in sPHENIX GitHub at line 207 of file MultiIndexTests.cpp
References test_fpe::count, Acts::MultiIndex< T, BitsPerLevel >::Encode(), size, and physmon_ckf_tracking::u.
BOOST_AUTO_TEST_CASE (index64_as_key)
Definition at line 223 of file MultiIndexTests.cpp.
View newest version in sPHENIX GitHub at line 223 of file MultiIndexTests.cpp
References test_fpe::count, Acts::MultiIndex< T, BitsPerLevel >::Encode(), size, and physmon_ckf_tracking::u.
BOOST_AUTO_TEST_CASE_TEMPLATE (triviality , T , Indices)
Definition at line 26 of file MultiIndexTests.cpp.
View newest version in sPHENIX GitHub at line 26 of file MultiIndexTests.cpp