Analysis Software: Acts::Vertex< input_track_t > Class Template Reference
Acts::Vertex< input_track_t > Class Template Reference
Class for storing vertex objects.
#include <acts/blob/sPHENIX/Core/include/Acts/Vertexing/Vertex.hpp>
Public Member Functions
Vertex ()=default
Default constructor.
Vertex (const Vector3 &position)
Construct for vertex at given 3d-position, sets covariance to zero.
Vertex (const Vector4 &position)
Construct for vertex at given 4d-position, sets covariance to zero.
Vertex (const Vector3 &position, const SquareMatrix3 &covariance, const std::vector< TrackAtVertex< input_track_t >> &tracks)
Vertex constructor.
Vertex (const Vector4 &position, const SquareMatrix4 &covariance, const std::vector< TrackAtVertex< input_track_t >> &tracks)
Vertex constructor.
Vector3 position () const
ActsScalar time () const
const Vector4 & fullPosition () const
SquareMatrix3 covariance () const
const SquareMatrix4 & fullCovariance () const
const std::vector
< TrackAtVertex< input_track_t > > & tracks () const
std::pair< double, double > fitQuality () const
void setPosition (const Vector3 &position, ActsScalar time=0)
Set position and time.
void setFullPosition (const Vector4 &fullPosition)
Set position and time.
void setTime (ActsScalar time)
Sets time.
void setCovariance (const SquareMatrix3 &covariance)
Sets 3x3 covariance.
void setFullCovariance (const SquareMatrix4 &covariance)
Sets 4x4 covariance.
void setTracksAtVertex (const std::vector< TrackAtVertex< input_track_t >> &tracks)
void setFitQuality (double chiSquared, double numberDoF)
void setFitQuality (std::pair< double, double > fitQuality)
Private Attributes
Vector4 m_position = Vector4::Zero()
SquareMatrix4 m_covariance = SquareMatrix4::Zero()
std::vector< TrackAtVertex
< input_track_t > > m_tracksAtVertex
double m_chiSquared = 0.
double m_numberDoF = 0.
Detailed Description
template<typename input_track_t>
class Acts::Vertex< input_track_t >
Class for storing vertex objects.
Template Parameters
input_track_t Track object type
Definition at line 23 of file Vertex.hpp.
View newest version in sPHENIX GitHub at line 23 of file Vertex.hpp
Constructor & Destructor Documentation
template<typename input_track_t> Acts::Vertex< input_track_t >::Vertex () default
Default constructor.
template<typename input_track_t > Vertex::Vertex (const Vector3 & position)
Construct for vertex at given 3d-position, sets covariance to zero.
Parameters
position Vertex position
Definition at line 10 of file Vertex.ipp.
View newest version in sPHENIX GitHub at line 10 of file Vertex.ipp
References Acts::ePos0, Acts::ePos1, and Acts::ePos2.
template<typename input_track_t > Vertex::Vertex (const Vector4 & position)
Construct for vertex at given 4d-position, sets covariance to zero.
Parameters
position Vertex position
Definition at line 17 of file Vertex.ipp.
View newest version in sPHENIX GitHub at line 17 of file Vertex.ipp
template<typename input_track_t> Vertex::Vertex (const Vector3 & position, const SquareMatrix3 & covariance, const std::vector< TrackAtVertex< input_track_t >> & tracks)
Vertex constructor.
Parameters
position Vertex position
covariance Position covariance matrix
tracks Vector of tracks associated with the vertex
Definition at line 21 of file Vertex.ipp.
View newest version in sPHENIX GitHub at line 21 of file Vertex.ipp
References Acts::ePos0, Acts::ePos1, Acts::ePos2, Acts::Vertex< input_track_t >::m_covariance, and Acts::Vertex< input_track_t >::m_position.
template<typename input_track_t> Vertex::Vertex (const Vector4 & position, const SquareMatrix4 & covariance, const std::vector< TrackAtVertex< input_track_t >> & tracks)
Vertex constructor.
Parameters
position Full vertex position
covariance 4x4 covariance matrix
tracks Vector of tracks associated with the vertex
Definition at line 32 of file Vertex.ipp.
View newest version in sPHENIX GitHub at line 32 of file Vertex.ipp
Member Function Documentation
template<typename input_track_t > Acts::SquareMatrix3 Vertex::covariance () const
Returns
Returns position covariance
Definition at line 55 of file Vertex.ipp.
View newest version in sPHENIX GitHub at line 55 of file Vertex.ipp
References Acts::ePos0.
Referenced by Acts::Test::BOOST_AUTO_TEST_CASE(), PHActsVertexFitter::createActsSvtxVertex(), Acts::ImpactPointEstimator< input_track_t, propagator_t, propagator_options_t >::getImpactParameters(), Acts::KalmanVertexUpdater::updatePosition(), and PHActsVertexFitter::updateSvtxVertex().
template<typename input_track_t > std::pair< double, double > Vertex::fitQuality () const
Returns
Returns pair of (chi2, numberDoF)
Definition at line 71 of file Vertex.ipp.
View newest version in sPHENIX GitHub at line 71 of file Vertex.ipp
Referenced by PHActsVertexFitter::createActsSvtxVertex(), Acts::IterativeVertexFinder< vfitter_t, sfinder_t >::find(), Acts::AdaptiveMultiVertexFitter< input_track_t, linearizer_t >::fitImpl(), Acts::IterativeVertexFinder< vfitter_t, sfinder_t >::reassignTracksToNewVertex(), Acts::KalmanVertexUpdater::detail::update(), and PHActsVertexFitter::updateSvtxVertex().
template<typename input_track_t > const Acts::SquareMatrix4 & Vertex::fullCovariance () const
Returns
Returns 4x4 covariance
Definition at line 60 of file Vertex.ipp.
View newest version in sPHENIX GitHub at line 60 of file Vertex.ipp
Referenced by Acts::Test::BOOST_AUTO_TEST_CASE(), Acts::AdaptiveGridDensityVertexFinder< trkGridSize, vfitter_t >::find(), Acts::GridDensityVertexFinder< mainGridSize, trkGridSize, vfitter_t >::find(), Acts::AdaptiveMultiVertexFitter< input_track_t, linearizer_t >::fitImpl(), Acts::IterativeVertexFinder< vfitter_t, sfinder_t >::getCompatibility(), Acts::ImpactPointEstimator< input_track_t, propagator_t, propagator_options_t >::getImpactParameters(), Acts::AdaptiveMultiVertexFinder< vfitter_t, sfinder_t >::isMergedVertex(), and Acts::KalmanVertexTrackUpdater::update().
template<typename input_track_t > const Acts::Vector4 & Vertex::fullPosition () const
Returns
Returns 4-position
Definition at line 50 of file Vertex.ipp.
View newest version in sPHENIX GitHub at line 50 of file Vertex.ipp
Referenced by Acts::AdaptiveMultiVertexFinder< vfitter_t, sfinder_t >::find(), Acts::AdaptiveMultiVertexFitter< input_track_t, linearizer_t >::fitImpl(), Acts::IterativeVertexFinder< vfitter_t, sfinder_t >::getCompatibility(), Acts::AdaptiveMultiVertexFinder< vfitter_t, sfinder_t >::isMergedVertex(), Acts::IterativeVertexFinder< vfitter_t, sfinder_t >::reassignTracksToNewVertex(), Acts::IterativeVertexFinder< vfitter_t, sfinder_t >::removeUsedCompatibleTracks(), and Acts::KalmanVertexTrackUpdater::update().
template<typename input_track_t > Acts::Vector3 Vertex::position () const
Returns
Returns 3-position
Definition at line 40 of file Vertex.ipp.
View newest version in sPHENIX GitHub at line 40 of file Vertex.ipp
References Acts::VectorHelpers::position().
Referenced by Acts::Test::BOOST_AUTO_TEST_CASE(), PHActsVertexFitter::createActsSvtxVertex(), Acts::IterativeVertexFinder< vfitter_t, sfinder_t >::fillTracksToFit(), Acts::AdaptiveMultiVertexFinder< vfitter_t, sfinder_t >::find(), PHActsVertexFitter::fitVertex(), Acts::ImpactPointEstimator< input_track_t, propagator_t, propagator_options_t >::get3DLifetimeSignOfTrack(), Acts::ImpactPointEstimator< input_track_t, propagator_t, propagator_options_t >::getImpactParameters(), Acts::ImpactPointEstimator< input_track_t, propagator_t, propagator_options_t >::getLifetimeSignOfTrack(), Acts::KalmanVertexUpdater::updatePosition(), PHActsVertexFitter::updateSvtxVertex(), and Acts::KalmanVertexUpdater::detail::vertexPositionChi2().
template<typename input_track_t > void Vertex::setCovariance (const SquareMatrix3 & covariance)
Sets 3x3 covariance.
Parameters
covariance Position covariance matrix
Definition at line 95 of file Vertex.ipp.
View newest version in sPHENIX GitHub at line 95 of file Vertex.ipp
References Acts::ePos0.
Referenced by Acts::Test::BOOST_AUTO_TEST_CASE(), Acts::TrackDensityVertexFinder< vfitter_t, track_density_t >::find(), ActsExamples::RootAthenaNTupleReader::read(), and Acts::Test::readTracksAndVertexCSV().
template<typename input_track_t > void Vertex::setFitQuality (double chiSquared, double numberDoF)
Parameters
chiSquared Chi2 of fit
numberDoF Number of degrees of freedom
Definition at line 114 of file Vertex.ipp.
View newest version in sPHENIX GitHub at line 114 of file Vertex.ipp
Referenced by Acts::Test::BOOST_AUTO_TEST_CASE(), and Acts::FullBilloirVertexFitter< input_track_t, linearizer_t >::fit().
template<typename input_track_t > void Vertex::setFitQuality (std::pair< double, double > fitQuality)
Parameters
fitQuality pair of (chi2, numberDoF)
Definition at line 121 of file Vertex.ipp.
View newest version in sPHENIX GitHub at line 121 of file Vertex.ipp
template<typename input_track_t > void Vertex::setFullCovariance (const SquareMatrix4 & covariance)
Sets 4x4 covariance.
Parameters
covariance The 4x4 covariance matrix
Definition at line 102 of file Vertex.ipp.
View newest version in sPHENIX GitHub at line 102 of file Vertex.ipp
References covariance().
Referenced by Acts::Test::BOOST_AUTO_TEST_CASE(), ActsExamples::VertexFitterAlgorithm::execute(), Acts::AdaptiveGridDensityVertexFinder< trkGridSize, vfitter_t >::find(), Acts::GridDensityVertexFinder< mainGridSize, trkGridSize, vfitter_t >::find(), Acts::FullBilloirVertexFitter< input_track_t, linearizer_t >::fit(), and Acts::AdaptiveMultiVertexFinder< vfitter_t, sfinder_t >::getIPSignificance().
template<typename input_track_t > void Vertex::setFullPosition (const Vector4 & fullPosition)
Set position and time.
Parameters
fullPosition Vertex position and time
Definition at line 85 of file Vertex.ipp.
View newest version in sPHENIX GitHub at line 85 of file Vertex.ipp
Referenced by Acts::Test::BOOST_AUTO_TEST_CASE(), ActsExamples::VertexFitterAlgorithm::execute(), and Acts::FullBilloirVertexFitter< input_track_t, linearizer_t >::fit().
template<typename input_track_t > void Vertex::setPosition (const Vector3 & position, ActsScalar time = 0)
Set position and time.
Parameters
position Vertex position
time The time
Definition at line 76 of file Vertex.ipp.
View newest version in sPHENIX GitHub at line 76 of file Vertex.ipp
References Acts::ePos0, Acts::ePos1, Acts::ePos2, Acts::eTime, and Acts::Test::time.
Referenced by Acts::Test::BOOST_AUTO_TEST_CASE(), ActsExamples::RootAthenaNTupleReader::read(), and Acts::Test::readTracksAndVertexCSV().
template<typename input_track_t > void Vertex::setTime (ActsScalar time)
Sets time.
Parameters
time The time
Definition at line 90 of file Vertex.ipp.
View newest version in sPHENIX GitHub at line 90 of file Vertex.ipp
References Acts::eTime, and Acts::Test::time.
template<typename input_track_t> void Vertex::setTracksAtVertex (const std::vector< TrackAtVertex< input_track_t >> & tracks)
Parameters
tracks Vector of tracks at vertex
Definition at line 108 of file Vertex.ipp.
View newest version in sPHENIX GitHub at line 108 of file Vertex.ipp
References tracks().
Referenced by Acts::Test::BOOST_AUTO_TEST_CASE(), Acts::FullBilloirVertexFitter< input_track_t, linearizer_t >::fit(), and Acts::IterativeVertexFinder< vfitter_t, sfinder_t >::removeUsedCompatibleTracks().
template<typename input_track_t > Acts::ActsScalar Vertex::time () const
Returns
Returns time
Definition at line 45 of file Vertex.ipp.
View newest version in sPHENIX GitHub at line 45 of file Vertex.ipp
References Acts::eTime.
Referenced by PHActsVertexFitter::createActsSvtxVertex(), Acts::ImpactPointEstimator< input_track_t, propagator_t, propagator_options_t >::getImpactParameters(), and PHActsVertexFitter::updateSvtxVertex().
template<typename input_track_t > const std::vector< Acts::TrackAtVertex< input_track_t > > & Vertex::tracks () const
Returns
Returns vector of tracks associated with the vertex
Definition at line 66 of file Vertex.ipp.
View newest version in sPHENIX GitHub at line 66 of file Vertex.ipp
Referenced by Acts::IterativeVertexFinder< vfitter_t, sfinder_t >::countSignificantTracks(), and Acts::IterativeVertexFinder< vfitter_t, sfinder_t >::removeUsedCompatibleTracks().
Member Data Documentation
template<typename input_track_t> double Acts::Vertex< input_track_t >::m_chiSquared = 0. private
Definition at line 116 of file Vertex.hpp.
View newest version in sPHENIX GitHub at line 116 of file Vertex.hpp
template<typename input_track_t> SquareMatrix4 Acts::Vertex< input_track_t >::m_covariance = SquareMatrix4::Zero() private
Definition at line 114 of file Vertex.hpp.
View newest version in sPHENIX GitHub at line 114 of file Vertex.hpp
Referenced by Acts::Vertex< input_track_t >::Vertex().
template<typename input_track_t> double Acts::Vertex< input_track_t >::m_numberDoF = 0. private
Definition at line 117 of file Vertex.hpp.
View newest version in sPHENIX GitHub at line 117 of file Vertex.hpp
template<typename input_track_t> Vector4 Acts::Vertex< input_track_t >::m_position = Vector4::Zero() private
Definition at line 113 of file Vertex.hpp.
View newest version in sPHENIX GitHub at line 113 of file Vertex.hpp
Referenced by Acts::Vertex< input_track_t >::Vertex().
template<typename input_track_t> std::vector<TrackAtVertex<input_track_t> > Acts::Vertex< input_track_t >::m_tracksAtVertex private
Definition at line 115 of file Vertex.hpp.
View newest version in sPHENIX GitHub at line 115 of file Vertex.hpp
The documentation for this class was generated from the following files:
acts/blob/sPHENIX/Core/include/Acts/Vertexing/Vertex.hpp
acts/blob/sPHENIX/Core/include/Acts/Vertexing/Vertex.ipp