Analysis Software: SvtxAlignmentStateMap Class Reference
SvtxAlignmentStateMap Class Reference
#include <coresoftware/blob/master/offline/packages/trackbase_historic/SvtxAlignmentStateMap.h>
Public Types
typedef std::vector
< SvtxAlignmentState * > StateVec
typedef std::map< unsigned int,
StateVec > StateMap
typedef StateMap::const_iterator ConstIter
typedef StateMap::iterator Iter
Public Member Functions
~SvtxAlignmentStateMap () override
void identify (std::ostream &os=std::cout) const override
int isValid () const override
isValid returns non zero if object contains vailid data
PHObject * CloneMe () const override
Virtual copy constructor.
virtual bool empty () const
virtual std::size_t size () const
virtual std::size_t count (unsigned int) const
virtual void clear ()
virtual const StateVec get (unsigned int) const
virtual StateVec get (unsigned int)
virtual StateVec insertWithKey (unsigned int, StateVec)
virtual std::size_t erase (unsigned int)
virtual ConstIter begin () const
virtual ConstIter find (unsigned int) const
virtual ConstIter end () const
virtual Iter begin ()
virtual Iter find (unsigned int)
virtual Iter end ()
Public Member Functions inherited from PHObject
PHObject ()
ctor
~PHObject () override
dtor
virtual PHObject * clone () const final
PHObject * Clone (const char *newname="") const final
void Copy (TObject &object) const final
virtual void Reset ()
Clear Event.
virtual int Integrate () const
virtual int Integrate (PHObject *)
virtual void CopyFrom (const PHObject *obj)
Protected Member Functions
SvtxAlignmentStateMap ()
Private Member Functions
ClassDefOverride (SvtxAlignmentStateMap, 1)
Detailed Description
Definition at line 11 of file SvtxAlignmentStateMap.h.
View newest version in sPHENIX GitHub at line 11 of file SvtxAlignmentStateMap.h
Member Typedef Documentation
typedef StateMap::const_iterator SvtxAlignmentStateMap::ConstIter
Definition at line 16 of file SvtxAlignmentStateMap.h.
View newest version in sPHENIX GitHub at line 16 of file SvtxAlignmentStateMap.h
typedef StateMap::iterator SvtxAlignmentStateMap::Iter
Definition at line 17 of file SvtxAlignmentStateMap.h.
View newest version in sPHENIX GitHub at line 17 of file SvtxAlignmentStateMap.h
typedef std::map<unsigned int, StateVec> SvtxAlignmentStateMap::StateMap
Definition at line 15 of file SvtxAlignmentStateMap.h.
View newest version in sPHENIX GitHub at line 15 of file SvtxAlignmentStateMap.h
typedef std::vector<SvtxAlignmentState*> SvtxAlignmentStateMap::StateVec
Definition at line 14 of file SvtxAlignmentStateMap.h.
View newest version in sPHENIX GitHub at line 14 of file SvtxAlignmentStateMap.h
Constructor & Destructor Documentation
SvtxAlignmentStateMap::~SvtxAlignmentStateMap () inline override
Definition at line 19 of file SvtxAlignmentStateMap.h.
View newest version in sPHENIX GitHub at line 19 of file SvtxAlignmentStateMap.h
SvtxAlignmentStateMap::SvtxAlignmentStateMap () inline protected
Definition at line 47 of file SvtxAlignmentStateMap.h.
View newest version in sPHENIX GitHub at line 47 of file SvtxAlignmentStateMap.h
Member Function Documentation
SvtxAlignmentStateMap::ConstIter SvtxAlignmentStateMap::begin (void) const virtual
Reimplemented in SvtxAlignmentStateMap_v1.
Definition at line 8 of file SvtxAlignmentStateMap.cc.
View newest version in sPHENIX GitHub at line 8 of file SvtxAlignmentStateMap.cc
SvtxAlignmentStateMap::Iter SvtxAlignmentStateMap::begin (void) virtual
Reimplemented in SvtxAlignmentStateMap_v1.
Definition at line 23 of file SvtxAlignmentStateMap.cc.
View newest version in sPHENIX GitHub at line 23 of file SvtxAlignmentStateMap.cc
SvtxAlignmentStateMap::ClassDefOverride (SvtxAlignmentStateMap , 1) private
virtual void SvtxAlignmentStateMap::clear () inline virtual
Reimplemented in SvtxAlignmentStateMap_v1.
Definition at line 31 of file SvtxAlignmentStateMap.h.
View newest version in sPHENIX GitHub at line 31 of file SvtxAlignmentStateMap.h
PHObject* SvtxAlignmentStateMap::CloneMe () const inline override virtual
Virtual copy constructor.
Reimplemented from PHObject.
Reimplemented in SvtxAlignmentStateMap_v1.
Definition at line 26 of file SvtxAlignmentStateMap.h.
View newest version in sPHENIX GitHub at line 26 of file SvtxAlignmentStateMap.h
virtual std::size_t SvtxAlignmentStateMap::count (unsigned int) const inline virtual
Reimplemented in SvtxAlignmentStateMap_v1.
Definition at line 30 of file SvtxAlignmentStateMap.h.
View newest version in sPHENIX GitHub at line 30 of file SvtxAlignmentStateMap.h
virtual bool SvtxAlignmentStateMap::empty () const inline virtual
Reimplemented in SvtxAlignmentStateMap_v1.
Definition at line 28 of file SvtxAlignmentStateMap.h.
View newest version in sPHENIX GitHub at line 28 of file SvtxAlignmentStateMap.h
SvtxAlignmentStateMap::ConstIter SvtxAlignmentStateMap::end (void) const virtual
Reimplemented in SvtxAlignmentStateMap_v1.
Definition at line 18 of file SvtxAlignmentStateMap.cc.
View newest version in sPHENIX GitHub at line 18 of file SvtxAlignmentStateMap.cc
SvtxAlignmentStateMap::Iter SvtxAlignmentStateMap::end (void) virtual
Reimplemented in SvtxAlignmentStateMap_v1.
Definition at line 33 of file SvtxAlignmentStateMap.cc.
View newest version in sPHENIX GitHub at line 33 of file SvtxAlignmentStateMap.cc
virtual std::size_t SvtxAlignmentStateMap::erase (unsigned int) inline virtual
Reimplemented in SvtxAlignmentStateMap_v1.
Definition at line 36 of file SvtxAlignmentStateMap.h.
View newest version in sPHENIX GitHub at line 36 of file SvtxAlignmentStateMap.h
SvtxAlignmentStateMap::ConstIter SvtxAlignmentStateMap::find (unsigned int) const virtual
Reimplemented in SvtxAlignmentStateMap_v1.
Definition at line 13 of file SvtxAlignmentStateMap.cc.
View newest version in sPHENIX GitHub at line 13 of file SvtxAlignmentStateMap.cc
SvtxAlignmentStateMap::Iter SvtxAlignmentStateMap::find (unsigned int) virtual
Reimplemented in SvtxAlignmentStateMap_v1.
Definition at line 28 of file SvtxAlignmentStateMap.cc.
View newest version in sPHENIX GitHub at line 28 of file SvtxAlignmentStateMap.cc
virtual const StateVec SvtxAlignmentStateMap::get (unsigned int) const inline virtual
Reimplemented in SvtxAlignmentStateMap_v1.
Definition at line 33 of file SvtxAlignmentStateMap.h.
View newest version in sPHENIX GitHub at line 33 of file SvtxAlignmentStateMap.h
virtual StateVec SvtxAlignmentStateMap::get (unsigned int) inline virtual
Reimplemented in SvtxAlignmentStateMap_v1.
Definition at line 34 of file SvtxAlignmentStateMap.h.
View newest version in sPHENIX GitHub at line 34 of file SvtxAlignmentStateMap.h
void SvtxAlignmentStateMap::identify (std::ostream & os = std::cout) const inline override virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from PHObject.
Reimplemented in SvtxAlignmentStateMap_v1.
Definition at line 21 of file SvtxAlignmentStateMap.h.
View newest version in sPHENIX GitHub at line 21 of file SvtxAlignmentStateMap.h
References os.
virtual StateVec SvtxAlignmentStateMap::insertWithKey (unsigned int , StateVec) inline virtual
Reimplemented in SvtxAlignmentStateMap_v1.
Definition at line 35 of file SvtxAlignmentStateMap.h.
View newest version in sPHENIX GitHub at line 35 of file SvtxAlignmentStateMap.h
Referenced by ActsAlignmentStates::fillAlignmentStateMap(), and HelicalFitter::process_event().
int SvtxAlignmentStateMap::isValid () const inline override virtual
isValid returns non zero if object contains vailid data
Reimplemented from PHObject.
Reimplemented in SvtxAlignmentStateMap_v1.
Definition at line 25 of file SvtxAlignmentStateMap.h.
View newest version in sPHENIX GitHub at line 25 of file SvtxAlignmentStateMap.h
virtual std::size_t SvtxAlignmentStateMap::size (void) const inline virtual
Reimplemented in SvtxAlignmentStateMap_v1.
Definition at line 29 of file SvtxAlignmentStateMap.h.
View newest version in sPHENIX GitHub at line 29 of file SvtxAlignmentStateMap.h
Referenced by MakeMilleFiles::process_event().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/trackbase_historic/SvtxAlignmentStateMap.h
coresoftware/blob/master/offline/packages/trackbase_historic/SvtxAlignmentStateMap.cc