Analysis Software: TrkrCluster Class Reference
TrkrCluster Class Reference
Base class for cluster object.
#include <coresoftware/blob/master/offline/packages/trackbase/TrkrCluster.h>
Public Member Functions
~TrkrCluster () override=default
dtor
void identify (std::ostream &os=std::cout) const override
void Reset () override
Clear Event.
int isValid () const override
isValid returns non zero if object contains vailid data
virtual void CopyFrom (const TrkrCluster &)
copy content from base class
virtual void CopyFrom (TrkrCluster *)
copy content from base class
virtual float getLocalX () const
virtual void setLocalX (float)
virtual float getLocalY () const
virtual void setLocalY (float)
virtual void setAdc (unsigned int)
virtual unsigned int getAdc () const
virtual void setMaxAdc (uint16_t)
virtual unsigned int getMaxAdc () const
virtual char getOverlap () const
virtual void setOverlap (char)
virtual char getEdge () const
virtual void setEdge (char)
virtual void setTime (const float)
virtual float getTime () const
virtual char getSize () const
virtual float getPhiSize () const
virtual float getZSize () const
virtual float getPhiError () const
virtual float getRPhiError () const
virtual float getZError () const
virtual void setActsLocalError (unsigned int, unsigned int, float)
Acts functions, for Acts modules use only.
virtual float getActsLocalError (unsigned int, unsigned int) const
virtual TrkrDefs::subsurfkey getSubSurfKey () const
virtual void setSubSurfKey (TrkrDefs::subsurfkey)
virtual float getX () const
virtual void setX (float)
virtual float getY () const
virtual void setY (float)
virtual float getZ () const
virtual void setZ (float)
virtual float getPosition (int) const
virtual void setPosition (int, float)
virtual void setGlobal ()
virtual void setLocal ()
virtual bool isGlobal () const
virtual float getError (unsigned int, unsigned int) const
virtual void setError (unsigned int, unsigned int, float)
virtual float getSize (unsigned int, unsigned int) const
virtual void setSize (unsigned int, unsigned int, float)
Public Member Functions inherited from PHObject
PHObject ()
ctor
~PHObject () override
dtor
virtual PHObject * CloneMe () const
Virtual copy constructor.
virtual PHObject * clone () const final
PHObject * Clone (const char *newname="") const final
void Copy (TObject &object) const final
virtual int Integrate () const
virtual int Integrate (PHObject *)
virtual void CopyFrom (const PHObject *obj)
Protected Member Functions
TrkrCluster ()=default
Detailed Description
Base class for cluster object.
Virtual base class for cluster object used for all tracking subsystems
Definition at line 25 of file TrkrCluster.h.
View newest version in sPHENIX GitHub at line 25 of file TrkrCluster.h
Constructor & Destructor Documentation
TrkrCluster::~TrkrCluster () override default
dtor
TrkrCluster::TrkrCluster () protected default
Member Function Documentation
virtual void TrkrCluster::CopyFrom (const TrkrCluster &) inline virtual
copy content from base class
Reimplemented in TrkrClusterv4, TrkrClusterv5, TrkrClusterv1, TrkrClusterv2, and TrkrClusterv3.
Definition at line 45 of file TrkrCluster.h.
View newest version in sPHENIX GitHub at line 45 of file TrkrCluster.h
Referenced by TrkrClusterv2::CopyFrom(), TrkrClusterv3::CopyFrom(), TrkrClusterv1::CopyFrom(), TrkrClusterv5::CopyFrom(), and TrkrClusterv4::CopyFrom().
virtual void TrkrCluster::CopyFrom (TrkrCluster *) inline virtual
copy content from base class
Reimplemented in TrkrClusterv4, TrkrClusterv5, TrkrClusterv1, TrkrClusterv2, and TrkrClusterv3.
Definition at line 49 of file TrkrCluster.h.
View newest version in sPHENIX GitHub at line 49 of file TrkrCluster.h
virtual float TrkrCluster::getActsLocalError (unsigned int , unsigned int) const inline virtual
Reimplemented in TrkrClusterv2, and TrkrClusterv3.
Definition at line 87 of file TrkrCluster.h.
View newest version in sPHENIX GitHub at line 87 of file TrkrCluster.h
Referenced by TrkrNtuplizer::calculateClusterError(), SvtxEvaluator::calculateClusterError(), TrkrClusterv2::CopyFrom(), TrkrClusterv3::CopyFrom(), PHActsKDTreeSeeding::makeSpacePoint(), and TrackSeedTrackMapConverter::process_event().
virtual unsigned int TrkrCluster::getAdc () const inline virtual
Reimplemented in TrkrClusterv2, TrkrClusterv4, TrkrClusterv5, TrkrClusterv3, TrkrClusterv1, and TpcPrototypeCluster.
Definition at line 64 of file TrkrCluster.h.
View newest version in sPHENIX GitHub at line 64 of file TrkrCluster.h
Referenced by SvtxClusterEval::all_clusters_from(), TrkrClusterv3::CopyFrom(), TrkrClusterv2::CopyFrom(), TrkrClusterv1::CopyFrom(), TrkrClusterv4::CopyFrom(), TrkrClusterv5::CopyFrom(), TrkrNtuplizer::fillOutputNtuples(), SvtxEvaluator::fillOutputNtuples(), dNdEtaINTT::GetRecoClusterInfo(), TrackerEventDisplay::makeJsonFile(), TpcClusterCleaner::process_event(), TPCGemGainCalb::process_event(), DumpTrkrClusterContainer::process_Node(), and TPCHitTrackDisplay::SimulationOut().
virtual char TrkrCluster::getEdge () const inline virtual
Reimplemented in TrkrClusterv4, and TrkrClusterv5.
Definition at line 69 of file TrkrCluster.h.
View newest version in sPHENIX GitHub at line 69 of file TrkrCluster.h
Referenced by TrkrClusterv4::CopyFrom(), TrkrClusterv5::CopyFrom(), TrackResiduals::fillClusterBranches(), SvtxEvaluator::fillOutputNtuples(), ClusterErrorPara::get_clusterv5_modified_error(), and ClusterErrorPara::tpc_phi_error().
virtual float TrkrCluster::getError (unsigned int , unsigned int) const inline virtual
Reimplemented in TrkrClusterv4, TrkrClusterv5, TrkrClusterv3, TrkrClusterv2, TrkrClusterv1, and TpcPrototypeCluster.
Definition at line 104 of file TrkrCluster.h.
View newest version in sPHENIX GitHub at line 104 of file TrkrCluster.h
Referenced by TrkrClusterv2::CopyFrom(), and TrkrClusterv1::CopyFrom().
virtual float TrkrCluster::getLocalX () const inline virtual
Reimplemented in TrkrClusterv2, TrkrClusterv4, TrkrClusterv5, and TrkrClusterv3.
Definition at line 55 of file TrkrCluster.h.
View newest version in sPHENIX GitHub at line 55 of file TrkrCluster.h
Referenced by SvtxClusterEval::all_clusters_from(), TrkrClusterv3::CopyFrom(), TrkrClusterv2::CopyFrom(), TrkrClusterv4::CopyFrom(), TrkrClusterv5::CopyFrom(), TrackResiduals::fillClusterBranches(), TrkrNtuplizer::fillOutputNtuples(), ActsGeometry::getGlobalPosition(), ActsGeometry::getGlobalPositionTpc(), ActsGeometry::getLocalCoords(), PHActsKDTreeSeeding::makeSpacePoint(), PHActsSiliconSeeding::makeSpacePoint(), and PHMicromegasTpcTrackMatching::process_event().
virtual float TrkrCluster::getLocalY () const inline virtual
Reimplemented in TrkrClusterv2, TrkrClusterv4, TrkrClusterv5, and TrkrClusterv3.
Definition at line 57 of file TrkrCluster.h.
View newest version in sPHENIX GitHub at line 57 of file TrkrCluster.h
Referenced by SvtxClusterEval::all_clusters_from(), TrackResiduals::convertTimeToZ(), HelicalFitter::convertTimeToZ(), TrkrClusterv2::CopyFrom(), TrkrClusterv3::CopyFrom(), TrkrClusterv5::CopyFrom(), TrkrClusterv4::CopyFrom(), TrackResiduals::fillClusterBranches(), TrkrNtuplizer::fillOutputNtuples(), ActsGeometry::getGlobalPosition(), ActsGeometry::getGlobalPositionTpc(), ActsGeometry::getLocalCoords(), PHActsKDTreeSeeding::makeSpacePoint(), PHActsSiliconSeeding::makeSpacePoint(), and PHMicromegasTpcTrackMatching::process_event().
virtual unsigned int TrkrCluster::getMaxAdc () const inline virtual
Reimplemented in TrkrClusterv4, and TrkrClusterv5.
Definition at line 66 of file TrkrCluster.h.
View newest version in sPHENIX GitHub at line 66 of file TrkrCluster.h
Referenced by TrkrClusterv5::CopyFrom(), TrkrNtuplizer::fillOutputNtuples(), SvtxEvaluator::fillOutputNtuples(), ClusterErrorPara::tpc_phi_error(), and ClusterErrorPara::tpc_z_error().
virtual char TrkrCluster::getOverlap () const inline virtual
Reimplemented in TrkrClusterv4, and TrkrClusterv5.
Definition at line 67 of file TrkrCluster.h.
View newest version in sPHENIX GitHub at line 67 of file TrkrCluster.h
Referenced by TrkrClusterv4::CopyFrom(), TrkrClusterv5::CopyFrom(), TrackResiduals::fillClusterBranches(), SvtxEvaluator::fillOutputNtuples(), and ClusterErrorPara::get_clusterv5_modified_error().
virtual float TrkrCluster::getPhiError () const inline virtual
Reimplemented in TrkrClusterv3, TrkrClusterv2, TrkrClusterv1, and TpcPrototypeCluster.
Definition at line 81 of file TrkrCluster.h.
View newest version in sPHENIX GitHub at line 81 of file TrkrCluster.h
Referenced by TrkrClusterv5::CopyFrom(), and SVReco::MakeGenFitTrack().
virtual float TrkrCluster::getPhiSize () const inline virtual
Reimplemented in TrkrClusterv4, TrkrClusterv5, TrkrClusterv3, TrkrClusterv2, TrkrClusterv1, and TpcPrototypeCluster.
Definition at line 79 of file TrkrCluster.h.
View newest version in sPHENIX GitHub at line 79 of file TrkrCluster.h
Referenced by TrkrClusterv4::CopyFrom(), TrkrClusterv5::CopyFrom(), TrackResiduals::fillClusterBranches(), TrkrNtuplizer::fillOutputNtuples(), SvtxEvaluator::fillOutputNtuples(), ClusterErrorPara::get_clusterv5_modified_error(), dNdEtaINTT::GetRecoClusterInfo(), ClusterErrorPara::intt_phi_error(), ClusterErrorPara::mm_phi_error(), ClusterErrorPara::mvtx_phi_error(), ClusterErrorPara::mvtx_z_error(), G4Eval::TrkrClusterComparer::operator()(), and ClusterErrorPara::tpc_phi_error().
virtual float TrkrCluster::getPosition (int) const inline virtual
Reimplemented in TrkrClusterv1, TrkrClusterv2, TrkrClusterv4, TrkrClusterv5, TpcPrototypeCluster, and TrkrClusterv3.
Definition at line 99 of file TrkrCluster.h.
View newest version in sPHENIX GitHub at line 99 of file TrkrCluster.h
Referenced by TpcPrototypeGenFitTrkFitter::DisplayCluster(), SVReco::MakeGenFitTrack(), G4Eval::TrkrClusterComparer::operator()(), TpcPrototypeGenFitTrkFinder::process_event(), and TpcPrototypeGenFitTrkFitter::ReFitTrack().
virtual float TrkrCluster::getRPhiError () const inline virtual
Reimplemented in TrkrClusterv4, TrkrClusterv2, TrkrClusterv5, TrkrClusterv1, TpcPrototypeCluster, and TrkrClusterv3.
Definition at line 82 of file TrkrCluster.h.
View newest version in sPHENIX GitHub at line 82 of file TrkrCluster.h
Referenced by ALICEKF::ALICEKalmanFilter(), TrackEvaluation::create_cluster(), TpcPrototypeGenFitTrkFitter::DisplayCluster(), ClusterErrorPara::get_clusterv5_modified_error(), PHActsSiliconSeeding::makeSpacePoint(), TpcClusterCleaner::process_event(), DumpTrkrClusterContainer::process_Node(), TpcPrototypeGenFitTrkFitter::ReFitTrack(), and PHGenFitTrkFitter::ReFitTrack().
virtual char TrkrCluster::getSize () const inline virtual
Reimplemented in TrkrClusterv4, and TrkrClusterv5.
Definition at line 73 of file TrkrCluster.h.
View newest version in sPHENIX GitHub at line 73 of file TrkrCluster.h
Referenced by TrkrClusterv2::CopyFrom(), TrkrClusterv1::CopyFrom(), TrkrNtuplizer::fillOutputNtuples(), TpcPrototypeCluster::getZSize(), TrkrClusterv1::getZSize(), TrkrClusterv2::getZSize(), TrkrClusterv2::identify(), TrkrClusterv1::identify(), TpcPrototypeCluster::identify(), TrkrClusterv2::isValid(), TrkrClusterv1::isValid(), and TpcPrototypeCluster::isValid().
virtual float TrkrCluster::getSize (unsigned int , unsigned int) const inline virtual
Reimplemented in TrkrClusterv4, TrkrClusterv5, TrkrClusterv3, TrkrClusterv2, TrkrClusterv1, and TpcPrototypeCluster.
Definition at line 106 of file TrkrCluster.h.
View newest version in sPHENIX GitHub at line 106 of file TrkrCluster.h
virtual TrkrDefs::subsurfkey TrkrCluster::getSubSurfKey () const inline virtual
Reimplemented in TrkrClusterv2, TrkrClusterv4, TrkrClusterv5, and TrkrClusterv3.
Definition at line 88 of file TrkrCluster.h.
View newest version in sPHENIX GitHub at line 88 of file TrkrCluster.h
Referenced by TrkrClusterv2::CopyFrom(), TrkrClusterv3::CopyFrom(), TrkrClusterv4::CopyFrom(), TrkrClusterv5::CopyFrom(), and ActsSurfaceMaps::getSurface().
virtual float TrkrCluster::getTime () const inline virtual
Definition at line 72 of file TrkrCluster.h.
View newest version in sPHENIX GitHub at line 72 of file TrkrCluster.h
virtual float TrkrCluster::getX () const inline virtual
Reimplemented in TrkrClusterv4, TrkrClusterv5, TrkrClusterv3, TrkrClusterv1, TrkrClusterv2, and TpcPrototypeCluster.
Definition at line 93 of file TrkrCluster.h.
View newest version in sPHENIX GitHub at line 93 of file TrkrCluster.h
Referenced by TrkrClusterv2::CopyFrom(), TrkrClusterv1::CopyFrom(), Conversion::dist(), KFParticle_truthAndDetTools::fillDetectorBranch(), PHSiliconTruthTrackSeeding::Process(), and TPCGemGainCalb::process_event().
virtual float TrkrCluster::getY () const inline virtual
Reimplemented in TrkrClusterv4, TrkrClusterv5, TrkrClusterv3, TrkrClusterv1, TrkrClusterv2, and TpcPrototypeCluster.
Definition at line 95 of file TrkrCluster.h.
View newest version in sPHENIX GitHub at line 95 of file TrkrCluster.h
Referenced by TrkrClusterv2::CopyFrom(), TrkrClusterv1::CopyFrom(), Conversion::dist(), KFParticle_truthAndDetTools::fillDetectorBranch(), PHSiliconTruthTrackSeeding::Process(), and TPCGemGainCalb::process_event().
virtual float TrkrCluster::getZ () const inline virtual
Reimplemented in TrkrClusterv4, TrkrClusterv5, TrkrClusterv3, TrkrClusterv1, TrkrClusterv2, and TpcPrototypeCluster.
Definition at line 97 of file TrkrCluster.h.
View newest version in sPHENIX GitHub at line 97 of file TrkrCluster.h
Referenced by TrkrClusterv2::CopyFrom(), TrkrClusterv1::CopyFrom(), Conversion::dist(), KFParticle_truthAndDetTools::fillDetectorBranch(), and SvtxClusterEval::gtrackid_and_layer_by_nhit().
virtual float TrkrCluster::getZError () const inline virtual
Reimplemented in TrkrClusterv4, TrkrClusterv2, TrkrClusterv5, TrkrClusterv1, TpcPrototypeCluster, and TrkrClusterv3.
Definition at line 83 of file TrkrCluster.h.
View newest version in sPHENIX GitHub at line 83 of file TrkrCluster.h
Referenced by TrkrClusterv5::CopyFrom(), TrackEvaluation::create_cluster(), TpcPrototypeGenFitTrkFitter::DisplayCluster(), ClusterErrorPara::get_clusterv5_modified_error(), SVReco::MakeGenFitTrack(), PHActsSiliconSeeding::makeSpacePoint(), TpcClusterCleaner::process_event(), DumpTrkrClusterContainer::process_Node(), TpcPrototypeGenFitTrkFitter::ReFitTrack(), and PHGenFitTrkFitter::ReFitTrack().
virtual float TrkrCluster::getZSize () const inline virtual
Reimplemented in TrkrClusterv4, TrkrClusterv5, TrkrClusterv3, TrkrClusterv2, TrkrClusterv1, and TpcPrototypeCluster.
Definition at line 80 of file TrkrCluster.h.
View newest version in sPHENIX GitHub at line 80 of file TrkrCluster.h
Referenced by TrkrClusterv4::CopyFrom(), TrkrClusterv5::CopyFrom(), TrackResiduals::fillClusterBranches(), TrkrNtuplizer::fillOutputNtuples(), SvtxEvaluator::fillOutputNtuples(), dNdEtaINTT::GetRecoClusterInfo(), ClusterErrorPara::intt_z_error(), ClusterErrorPara::mm_z_error(), ClusterErrorPara::mvtx_phi_error(), ClusterErrorPara::mvtx_z_error(), and G4Eval::TrkrClusterComparer::operator()().
void TrkrCluster::identify (std::ostream & os = std::cout) const inline override virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from PHObject.
Reimplemented in TpcPrototypeCluster, TrkrClusterv1, TrkrClusterv4, TrkrClusterv5, TrkrClusterv2, and TrkrClusterv3.
Definition at line 33 of file TrkrCluster.h.
View newest version in sPHENIX GitHub at line 33 of file TrkrCluster.h
References os.
Referenced by TpcPrototypeGenFitTrkFitter::DisplayCluster(), TpcPrototypeUnpacker::exportDSTCluster(), TpcPrototypeGenFitTrkFitter::MakeTpcPrototypeTrack(), SvtxEvaluator::printOutputInfo(), and PHTruthClustering::process_event().
virtual bool TrkrCluster::isGlobal () const inline virtual
Reimplemented in TrkrClusterv1, and TrkrClusterv2.
Definition at line 103 of file TrkrCluster.h.
View newest version in sPHENIX GitHub at line 103 of file TrkrCluster.h
Referenced by TrkrClusterv2::CopyFrom(), and TrkrClusterv1::CopyFrom().
int TrkrCluster::isValid () const inline override virtual
isValid returns non zero if object contains vailid data
Reimplemented from PHObject.
Reimplemented in TpcPrototypeCluster, TrkrClusterv1, TrkrClusterv4, TrkrClusterv5, TrkrClusterv2, and TrkrClusterv3.
Definition at line 38 of file TrkrCluster.h.
View newest version in sPHENIX GitHub at line 38 of file TrkrCluster.h
void TrkrCluster::Reset () inline override virtual
Clear Event.
Reimplemented from PHObject.
Reimplemented in TpcPrototypeCluster, TrkrClusterv1, TrkrClusterv4, TrkrClusterv5, TrkrClusterv2, and TrkrClusterv3.
Definition at line 37 of file TrkrCluster.h.
View newest version in sPHENIX GitHub at line 37 of file TrkrCluster.h
virtual void TrkrCluster::setActsLocalError (unsigned int , unsigned int , float) inline virtual
Acts functions, for Acts modules use only.
Reimplemented in TrkrClusterv2, and TrkrClusterv3.
Definition at line 86 of file TrkrCluster.h.
View newest version in sPHENIX GitHub at line 86 of file TrkrCluster.h
virtual void TrkrCluster::setAdc (unsigned int) inline virtual
Reimplemented in TrkrClusterv2, TrkrClusterv4, TrkrClusterv5, TrkrClusterv3, TrkrClusterv1, and TpcPrototypeCluster.
Definition at line 63 of file TrkrCluster.h.
View newest version in sPHENIX GitHub at line 63 of file TrkrCluster.h
virtual void TrkrCluster::setEdge (char) inline virtual
Reimplemented in TrkrClusterv4, and TrkrClusterv5.
Definition at line 70 of file TrkrCluster.h.
View newest version in sPHENIX GitHub at line 70 of file TrkrCluster.h
virtual void TrkrCluster::setError (unsigned int , unsigned int , float) inline virtual
Reimplemented in TrkrClusterv4, TrkrClusterv5, TrkrClusterv3, TrkrClusterv2, TrkrClusterv1, and TpcPrototypeCluster.
Definition at line 105 of file TrkrCluster.h.
View newest version in sPHENIX GitHub at line 105 of file TrkrCluster.h
virtual void TrkrCluster::setGlobal () inline virtual
Reimplemented in TrkrClusterv1, TrkrClusterv2, and TpcPrototypeCluster.
Definition at line 101 of file TrkrCluster.h.
View newest version in sPHENIX GitHub at line 101 of file TrkrCluster.h
virtual void TrkrCluster::setLocal () inline virtual
Reimplemented in TrkrClusterv1, TrkrClusterv2, and TpcPrototypeCluster.
Definition at line 102 of file TrkrCluster.h.
View newest version in sPHENIX GitHub at line 102 of file TrkrCluster.h
virtual void TrkrCluster::setLocalX (float) inline virtual
Reimplemented in TrkrClusterv2, TrkrClusterv4, TrkrClusterv5, and TrkrClusterv3.
Definition at line 56 of file TrkrCluster.h.
View newest version in sPHENIX GitHub at line 56 of file TrkrCluster.h
virtual void TrkrCluster::setLocalY (float) inline virtual
Reimplemented in TrkrClusterv2, TrkrClusterv4, TrkrClusterv5, and TrkrClusterv3.
Definition at line 58 of file TrkrCluster.h.
View newest version in sPHENIX GitHub at line 58 of file TrkrCluster.h
virtual void TrkrCluster::setMaxAdc (uint16_t) inline virtual
Reimplemented in TrkrClusterv4, and TrkrClusterv5.
Definition at line 65 of file TrkrCluster.h.
View newest version in sPHENIX GitHub at line 65 of file TrkrCluster.h
virtual void TrkrCluster::setOverlap (char) inline virtual
Reimplemented in TrkrClusterv4, and TrkrClusterv5.
Definition at line 68 of file TrkrCluster.h.
View newest version in sPHENIX GitHub at line 68 of file TrkrCluster.h
virtual void TrkrCluster::setPosition (int , float) inline virtual
Reimplemented in TrkrClusterv1, TrkrClusterv2, TrkrClusterv4, TrkrClusterv5, TpcPrototypeCluster, and TrkrClusterv3.
Definition at line 100 of file TrkrCluster.h.
View newest version in sPHENIX GitHub at line 100 of file TrkrCluster.h
virtual void TrkrCluster::setSize (unsigned int , unsigned int , float) inline virtual
Reimplemented in TrkrClusterv4, TrkrClusterv5, TrkrClusterv3, TrkrClusterv2, TrkrClusterv1, and TpcPrototypeCluster.
Definition at line 107 of file TrkrCluster.h.
View newest version in sPHENIX GitHub at line 107 of file TrkrCluster.h
virtual void TrkrCluster::setSubSurfKey (TrkrDefs::subsurfkey) inline virtual
Reimplemented in TrkrClusterv2, TrkrClusterv4, TrkrClusterv5, and TrkrClusterv3.
Definition at line 89 of file TrkrCluster.h.
View newest version in sPHENIX GitHub at line 89 of file TrkrCluster.h
virtual void TrkrCluster::setTime (const float) inline virtual
Definition at line 71 of file TrkrCluster.h.
View newest version in sPHENIX GitHub at line 71 of file TrkrCluster.h
virtual void TrkrCluster::setX (float) inline virtual
Reimplemented in TrkrClusterv4, TrkrClusterv5, TrkrClusterv3, TrkrClusterv1, TrkrClusterv2, and TpcPrototypeCluster.
Definition at line 94 of file TrkrCluster.h.
View newest version in sPHENIX GitHub at line 94 of file TrkrCluster.h
virtual void TrkrCluster::setY (float) inline virtual
Reimplemented in TrkrClusterv4, TrkrClusterv5, TrkrClusterv3, TrkrClusterv1, TrkrClusterv2, and TpcPrototypeCluster.
Definition at line 96 of file TrkrCluster.h.
View newest version in sPHENIX GitHub at line 96 of file TrkrCluster.h
virtual void TrkrCluster::setZ (float) inline virtual
Reimplemented in TrkrClusterv4, TrkrClusterv5, TrkrClusterv3, TrkrClusterv1, TrkrClusterv2, and TpcPrototypeCluster.
Definition at line 98 of file TrkrCluster.h.
View newest version in sPHENIX GitHub at line 98 of file TrkrCluster.h
The documentation for this class was generated from the following file:
coresoftware/blob/master/offline/packages/trackbase/TrkrCluster.h