Analysis Software: macros/blob/master/calibrations/calo/emcal_calib_year1/doTscFit.C File Reference
doTscFit.C File Reference
#include <cdbobjects/CDBTTree.h>
#include <litecaloeval/LiteCaloEval.h>
#include "TowerInfoDefs.h"
Functions
void TSCtoCDBTTree (const char *infile, const char *outputfile)
void mergeCDBTTrees (const char *infile1, const char *infile2, const char *outputfile)
void doTscFit (const std::string &hist_fname="base/combine_out/out1.root", const std::string &calib_fname="base/local_calib_copy.root")
Function Documentation
void doTscFit (const std::string & hist_fname = "base/combine_out/out1.root", const std::string & calib_fname = "base/local_calib_copy.root")
Definition at line 15 of file doTscFit.C.
View newest version in sPHENIX GitHub at line 15 of file doTscFit.C
References LiteCaloEval::CaloType(), LiteCaloEval::CEMC, LiteCaloEval::FitRelativeShifts(), LiteCaloEval::Get_Histos(), LiteCaloEval::m_mymaxbin, LiteCaloEval::m_myminbin, mergeCDBTTrees(), Acts::Test::pos, LiteCaloEval::setFitMax(), LiteCaloEval::setFitMin(), and TSCtoCDBTTree().
void mergeCDBTTrees (const char * infile1, const char * infile2, const char * outputfile)
void TSCtoCDBTTree (const char * infile, const char * outputfile)