Analysis Software: JetKinematicCheck Class Reference
JetKinematicCheck Class Reference
#include <analysis/blob/master/JS-Jet/JetAnalysis/src/JetKinematicCheck.h>
Public Member Functions
JetKinematicCheck (const std::string &recojetnameR02="AntiKt_Tower_r02", const std::string &recojetnameR04="AntiKt_Tower_r04", const std::string &outputfilename="JetKinematicCheck")
~JetKinematicCheck () override
void setEtaRange (double low, double high)
void setPtRange (double low, double high)
std::vector< std::string > GetCentLabels ()
std::vector< int > GetMarkerColors ()
int Init (PHCompositeNode *topNode) override
int InitRun (PHCompositeNode *topNode) override
int process_event (PHCompositeNode *topNode) override
int ResetEvent (PHCompositeNode *topNode) override
Clean up internals after each event.
int EndRun (const int runnumber) override
Called at the end of each run.
int End (PHCompositeNode *topNode) override
Called at the end of all processing.
int Reset (PHCompositeNode *) override
Reset.
void Print (const std::string &what="ALL") const override
Public Member Functions inherited from SubsysReco
~SubsysReco () override
void Print (const std::string &="ALL") const override
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Private Attributes
std::string m_recoJetNameR02
std::string m_recoJetNameR04
std::string m_outputFileName
std::pair< double, double > m_etaRange
std::pair< double, double > m_ptRange
int cent_N
int m_nJet
int m_centrality
float m_impactparam
int ncent
std::vector< int > m_id
std::vector< int > m_nComponent
std::vector< float > m_eta
std::vector< float > m_phi
std::vector< float > m_pt
std::vector< float > m_radii
TH2 * jet_spectra_r02 = nullptr
TH1 * jet_spectra_r02_proj [11] = {nullptr}
TH2 * jet_spectra_r04 = nullptr
TH1 * jet_spectra_r04_proj [11] = {nullptr}
TH3 * jet_eta_phi_r02 = nullptr
TH2 * jet_eta_phi_r02_proj [11] = {nullptr}
TH3 * jet_eta_phi_r04 = nullptr
TH2 * jet_eta_phi_r04_proj [11] = {nullptr}
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = std::numeric_limits<int>::max() - 10
}
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Detailed Description
Definition at line 18 of file JetKinematicCheck.h.
View newest version in sPHENIX GitHub at line 18 of file JetKinematicCheck.h
Constructor & Destructor Documentation
JetKinematicCheck::JetKinematicCheck (const std::string & recojetnameR02 = "AntiKt_Tower_r02", const std::string & recojetnameR04 = "AntiKt_Tower_r04", const std::string & outputfilename = "JetKinematicCheck")
Definition at line 37 of file JetKinematicCheck.cc.
View newest version in sPHENIX GitHub at line 37 of file JetKinematicCheck.cc
JetKinematicCheck::~JetKinematicCheck () override
Definition at line 50 of file JetKinematicCheck.cc.
View newest version in sPHENIX GitHub at line 50 of file JetKinematicCheck.cc
Member Function Documentation
int JetKinematicCheck::End (PHCompositeNode * topNode) override virtual
Called at the end of all processing.
Reimplemented from SubsysReco.
Definition at line 188 of file JetKinematicCheck.cc.
View newest version in sPHENIX GitHub at line 188 of file JetKinematicCheck.cc
References PHTFileServer::cd(), Fun4AllReturnCodes::EVENT_OK, PHTFileServer::get(), GetCentLabels(), GetMarkerColors(), i, jet_eta_phi_r02, jet_eta_phi_r02_proj, jet_eta_phi_r04, jet_eta_phi_r04_proj, jet_spectra_r02, jet_spectra_r02_proj, jet_spectra_r04, jet_spectra_r04_proj, m_etaRange, m_outputFileName, m_ptRange, and ncent.
int JetKinematicCheck::EndRun (const int runnumber) override virtual
Called at the end of each run.
Reimplemented from SubsysReco.
Definition at line 181 of file JetKinematicCheck.cc.
View newest version in sPHENIX GitHub at line 181 of file JetKinematicCheck.cc
References Fun4AllReturnCodes::EVENT_OK.
std::vector< std::string > JetKinematicCheck::GetCentLabels ()
Definition at line 56 of file JetKinematicCheck.cc.
View newest version in sPHENIX GitHub at line 56 of file JetKinematicCheck.cc
Referenced by End().
std::vector< int > JetKinematicCheck::GetMarkerColors ()
Definition at line 65 of file JetKinematicCheck.cc.
View newest version in sPHENIX GitHub at line 65 of file JetKinematicCheck.cc
Referenced by End().
int JetKinematicCheck::Init (PHCompositeNode * topNode) override virtual
Called during initialization. Typically this is where you can book histograms, and e.g. register them to Fun4AllServer (so they can be output to file using Fun4AllServer::dumpHistos() method).
Reimplemented from SubsysReco.
Definition at line 75 of file JetKinematicCheck.cc.
View newest version in sPHENIX GitHub at line 75 of file JetKinematicCheck.cc
References Fun4AllReturnCodes::EVENT_OK, PHTFileServer::get(), jet_eta_phi_r02, jet_eta_phi_r04, jet_spectra_r02, jet_spectra_r04, m_outputFileName, and PHTFileServer::open().
int JetKinematicCheck::InitRun (PHCompositeNode * topNode) override virtual
Called for first event when run number is known. Typically this is where you may want to fetch data from database, because you know the run number. A place to book histograms which have to know the run number.
Reimplemented from SubsysReco.
Definition at line 97 of file JetKinematicCheck.cc.
View newest version in sPHENIX GitHub at line 97 of file JetKinematicCheck.cc
References Fun4AllReturnCodes::EVENT_OK.
void JetKinematicCheck::Print (const std::string & what = "ALL") const override virtual
Print out some info about this module.
Parameters
what can be used to specify what to print exactly.
Reimplemented from Fun4AllBase.
Definition at line 341 of file JetKinematicCheck.cc.
View newest version in sPHENIX GitHub at line 341 of file JetKinematicCheck.cc
int JetKinematicCheck::process_event (PHCompositeNode * topNode) override virtual
Called for each event. This is where you do the real work.
Reimplemented from SubsysReco.
Definition at line 105 of file JetKinematicCheck.cc.
View newest version in sPHENIX GitHub at line 105 of file JetKinematicCheck.cc
References JetMap::begin(), JetMap::end(), Fun4AllReturnCodes::EVENT_OK, CentralityInfo::get_centile(), Jet::get_eta(), Jet::get_phi(), Jet::get_pt(), i, jet_eta_phi_r02, jet_eta_phi_r04, jet_spectra_r02, jet_spectra_r04, m_centrality, m_etaRange, m_ptRange, m_radii, m_recoJetNameR02, and m_recoJetNameR04.
int JetKinematicCheck::Reset (PHCompositeNode * topNode) override virtual
Reset.
Reimplemented from SubsysReco.
Definition at line 334 of file JetKinematicCheck.cc.
View newest version in sPHENIX GitHub at line 334 of file JetKinematicCheck.cc
References Fun4AllReturnCodes::EVENT_OK.
int JetKinematicCheck::ResetEvent (PHCompositeNode * topNode) override virtual
Clean up internals after each event.
Reimplemented from SubsysReco.
Definition at line 169 of file JetKinematicCheck.cc.
View newest version in sPHENIX GitHub at line 169 of file JetKinematicCheck.cc
References test_fpe::count, and Fun4AllReturnCodes::EVENT_OK.
void JetKinematicCheck::setEtaRange (double low, double high) inline
Definition at line 30 of file JetKinematicCheck.h.
View newest version in sPHENIX GitHub at line 30 of file JetKinematicCheck.h
References m_etaRange.
Referenced by Fun4All_JetVal().
void JetKinematicCheck::setPtRange (double low, double high) inline
Definition at line 37 of file JetKinematicCheck.h.
View newest version in sPHENIX GitHub at line 37 of file JetKinematicCheck.h
References m_ptRange.
Referenced by Fun4All_JetVal().
Member Data Documentation
int JetKinematicCheck::cent_N private
Definition at line 88 of file JetKinematicCheck.h.
View newest version in sPHENIX GitHub at line 88 of file JetKinematicCheck.h
TH3* JetKinematicCheck::jet_eta_phi_r02 = nullptr private
Definition at line 110 of file JetKinematicCheck.h.
View newest version in sPHENIX GitHub at line 110 of file JetKinematicCheck.h
Referenced by End(), Init(), and process_event().
TH2* JetKinematicCheck::jet_eta_phi_r02_proj[11] = {nullptr} private
Definition at line 111 of file JetKinematicCheck.h.
View newest version in sPHENIX GitHub at line 111 of file JetKinematicCheck.h
Referenced by End().
TH3* JetKinematicCheck::jet_eta_phi_r04 = nullptr private
Definition at line 112 of file JetKinematicCheck.h.
View newest version in sPHENIX GitHub at line 112 of file JetKinematicCheck.h
Referenced by End(), Init(), and process_event().
TH2* JetKinematicCheck::jet_eta_phi_r04_proj[11] = {nullptr} private
Definition at line 113 of file JetKinematicCheck.h.
View newest version in sPHENIX GitHub at line 113 of file JetKinematicCheck.h
Referenced by End().
TH2* JetKinematicCheck::jet_spectra_r02 = nullptr private
Definition at line 106 of file JetKinematicCheck.h.
View newest version in sPHENIX GitHub at line 106 of file JetKinematicCheck.h
Referenced by End(), Init(), and process_event().
TH1* JetKinematicCheck::jet_spectra_r02_proj[11] = {nullptr} private
Definition at line 107 of file JetKinematicCheck.h.
View newest version in sPHENIX GitHub at line 107 of file JetKinematicCheck.h
Referenced by End().
TH2* JetKinematicCheck::jet_spectra_r04 = nullptr private
Definition at line 108 of file JetKinematicCheck.h.
View newest version in sPHENIX GitHub at line 108 of file JetKinematicCheck.h
Referenced by End(), Init(), and process_event().
TH1* JetKinematicCheck::jet_spectra_r04_proj[11] = {nullptr} private
Definition at line 109 of file JetKinematicCheck.h.
View newest version in sPHENIX GitHub at line 109 of file JetKinematicCheck.h
Referenced by End().
int JetKinematicCheck::m_centrality private
Definition at line 93 of file JetKinematicCheck.h.
View newest version in sPHENIX GitHub at line 93 of file JetKinematicCheck.h
Referenced by process_event().
std::vector<float> JetKinematicCheck::m_eta private
Definition at line 100 of file JetKinematicCheck.h.
View newest version in sPHENIX GitHub at line 100 of file JetKinematicCheck.h
std::pair<double, double> JetKinematicCheck::m_etaRange private
Definition at line 86 of file JetKinematicCheck.h.
View newest version in sPHENIX GitHub at line 86 of file JetKinematicCheck.h
Referenced by End(), process_event(), and setEtaRange().
std::vector<int> JetKinematicCheck::m_id private
Definition at line 98 of file JetKinematicCheck.h.
View newest version in sPHENIX GitHub at line 98 of file JetKinematicCheck.h
float JetKinematicCheck::m_impactparam private
Definition at line 94 of file JetKinematicCheck.h.
View newest version in sPHENIX GitHub at line 94 of file JetKinematicCheck.h
std::vector<int> JetKinematicCheck::m_nComponent private
Definition at line 99 of file JetKinematicCheck.h.
View newest version in sPHENIX GitHub at line 99 of file JetKinematicCheck.h
int JetKinematicCheck::m_nJet private
Definition at line 92 of file JetKinematicCheck.h.
View newest version in sPHENIX GitHub at line 92 of file JetKinematicCheck.h
std::string JetKinematicCheck::m_outputFileName private
Definition at line 85 of file JetKinematicCheck.h.
View newest version in sPHENIX GitHub at line 85 of file JetKinematicCheck.h
Referenced by End(), and Init().
std::vector<float> JetKinematicCheck::m_phi private
Definition at line 101 of file JetKinematicCheck.h.
View newest version in sPHENIX GitHub at line 101 of file JetKinematicCheck.h
std::vector<float> JetKinematicCheck::m_pt private
Definition at line 102 of file JetKinematicCheck.h.
View newest version in sPHENIX GitHub at line 102 of file JetKinematicCheck.h
std::pair<double, double> JetKinematicCheck::m_ptRange private
Definition at line 87 of file JetKinematicCheck.h.
View newest version in sPHENIX GitHub at line 87 of file JetKinematicCheck.h
Referenced by End(), process_event(), and setPtRange().
std::vector<float> JetKinematicCheck::m_radii private
Definition at line 103 of file JetKinematicCheck.h.
View newest version in sPHENIX GitHub at line 103 of file JetKinematicCheck.h
Referenced by process_event().
std::string JetKinematicCheck::m_recoJetNameR02 private
Definition at line 83 of file JetKinematicCheck.h.
View newest version in sPHENIX GitHub at line 83 of file JetKinematicCheck.h
Referenced by process_event().
std::string JetKinematicCheck::m_recoJetNameR04 private
Definition at line 84 of file JetKinematicCheck.h.
View newest version in sPHENIX GitHub at line 84 of file JetKinematicCheck.h
Referenced by process_event().
int JetKinematicCheck::ncent private
Definition at line 95 of file JetKinematicCheck.h.
View newest version in sPHENIX GitHub at line 95 of file JetKinematicCheck.h
Referenced by End().
The documentation for this class was generated from the following files:
analysis/blob/master/JS-Jet/JetAnalysis/src/JetKinematicCheck.h
analysis/blob/master/JS-Jet/JetAnalysis/src/JetKinematicCheck.cc