Analysis Software: acts/blob/sPHENIX/Examples/Scripts/TrackingPerformance/boundParamResolution.C File Reference
boundParamResolution.C File Reference
#include <array>
#include <iostream>
#include <map>
#include <string>
#include <vector>
#include <TCanvas.h>
#include <TColor.h>
#include <TDirectory.h>
#include <TError.h>
#include <TF1.h>
#include <TFile.h>
#include <TH1F.h>
#include <TH2F.h>
#include <TLegend.h>
#include <TMath.h>
#include <TProfile2D.h>
#include <TStyle.h>
#include <TTree.h>
#include "CommonUtils.h"
#include "TreeReader.h"
Functions
int boundParamResolution (const std::string &inFile, const std::string &treeName, const std::string &outFile, bool predicted=true, bool filtered=true, bool smoothed=true, bool fitFiltered=true, bool fitPredicted=true, bool fitSmoothed=true, const std::string &saveAs="")
Function Documentation
int boundParamResolution (const std::string & inFile, const std::string & treeName, const std::string & outFile, bool predicted = true, bool filtered = true, bool smoothed = true, bool fitFiltered = true, bool fitPredicted = true, bool fitSmoothed = true, const std::string & saveAs = "")
Plot the bound parameter resolutions
(loc1, phi, theta, q/p, t) at all track states from root file produced by the RootTrajectoryStatesWriter
Parameters
inFile the input root file
treeName the input tree name (default: 'trackstates)
outFile the output root file
pTypes the track parameter types (prt, flt, smt)
saveAs the plot saving type
Helper method to make a volLayId string for identification & cut
ensures a unique identification
Helper method to estimate the ranges
Takes identification & cut from the first one
Always fill (-1,-1), (vol, -1), (vol, lay)
Definition at line 44 of file boundParamResolution.C.
View newest version in sPHENIX GitHub at line 44 of file boundParamResolution.C
References adaptColorPalette(), drawOptions, fid, file, TrackStatesReader::filtered, TrackStatesReader::g_x_flt, TrackStatesReader::g_x_prt, TrackStatesReader::g_x_smt, TrackStatesReader::g_y_flt, TrackStatesReader::g_y_prt, TrackStatesReader::g_y_smt, TrackStatesReader::g_z_flt, TrackStatesReader::g_z_prt, TrackStatesReader::g_z_smt, Acts::EventDataView3DTest::gauss(), TreeReader::getEntry(), i, j, TrackStatesReader::layer_id, CKF_timing_vs_mu::mu, perf_headwind::name, TrackStatesReader::nMeasurements, out, TrackStatesReader::predicted, TrackStatesReader::pull_LOC0_flt, TrackStatesReader::pull_LOC0_prt, TrackStatesReader::pull_LOC0_smt, TrackStatesReader::pull_LOC1_flt, TrackStatesReader::pull_LOC1_prt, TrackStatesReader::pull_LOC1_smt, TrackStatesReader::pull_PHI_flt, TrackStatesReader::pull_PHI_prt, TrackStatesReader::pull_PHI_smt, TrackStatesReader::pull_QOP_flt, TrackStatesReader::pull_QOP_prt, TrackStatesReader::pull_QOP_smt, TrackStatesReader::pull_T_flt, TrackStatesReader::pull_T_prt, TrackStatesReader::pull_T_smt, TrackStatesReader::pull_THETA_flt, TrackStatesReader::pull_THETA_prt, TrackStatesReader::pull_THETA_smt, check_smearing_config::ref, TrackStatesReader::res_LOC0_flt, TrackStatesReader::res_LOC0_prt, TrackStatesReader::res_LOC0_smt, TrackStatesReader::res_LOC1_flt, TrackStatesReader::res_LOC1_prt, TrackStatesReader::res_LOC1_smt, TrackStatesReader::res_PHI_flt, TrackStatesReader::res_PHI_prt, TrackStatesReader::res_PHI_smt, TrackStatesReader::res_QOP_flt, TrackStatesReader::res_QOP_prt, TrackStatesReader::res_QOP_smt, TrackStatesReader::res_T_flt, TrackStatesReader::res_T_prt, TrackStatesReader::res_T_smt, TrackStatesReader::res_THETA_flt, TrackStatesReader::res_THETA_prt, TrackStatesReader::res_THETA_smt, setHistStyle(), sigma, TrackStatesReader::smoothed, to_string(), tree, parse_cmake_options::type, and TrackStatesReader::volume_id.
Referenced by main().