Analysis Software: coresoftware/blob/master/simulation/g4simulation/g4eval/compressor_generator.h File Reference
compressor_generator.h File Reference
#include <map>
#include <random>
#include <set>
#include <utility>
#include <vector>
#include "RtypesCore.h"
Functions
UShort_t residesIn (Float_t raw, std::vector< Float_t > *dict)
Float_t approx (std::vector< UShort_t > *order, std::vector< Float_t > *dict, std::vector< size_t > *cnt, Int_t n_entries, std::default_random_engine &generator, std::normal_distribution< double > &distribution, size_t maxNumClusters)
Int_t newLoc (std::vector< Int_t > *loc_vec, std::vector< std::vector< Int_t >> *loc_vec_vec)
void removeDiff (Float_t distance, Float_t min, std::map< Float_t, std::set< Float_t >> *distance_min_set_map)
void addDiff (Float_t distance, Float_t min, std::map< Float_t, std::set< Float_t >> *distance_min_set_map)
Function Documentation
void addDiff (Float_t distance, Float_t min, std::map< Float_t, std::set< Float_t >> * distance_min_set_map)
Float_t approx (std::vector< UShort_t > * order, std::vector< Float_t > * dict, std::vector< size_t > * cnt, Int_t n_entries, std::default_random_engine & generator, std::normal_distribution< double > & distribution, size_t maxNumClusters)
approx() compresses data generated by a normal distribution and returns the maximum absolute difference between the actual and approximated data.
Definition at line 50 of file compressor_generator.h.
View newest version in sPHENIX GitHub at line 50 of file compressor_generator.h
References addDiff(), double(), index, j, loc, Acts::UnitConstants::min, newLoc(), next, removeDiff(), and physmon_simulation::s.
Int_t newLoc (std::vector< Int_t > * loc_vec, std::vector< std::vector< Int_t >> * loc_vec_vec)
Definition at line 148 of file compressor_generator.h.
View newest version in sPHENIX GitHub at line 148 of file compressor_generator.h
References loc.
void removeDiff (Float_t distance, Float_t min, std::map< Float_t, std::set< Float_t >> * distance_min_set_map)
UShort_t residesIn (Float_t raw, std::vector< Float_t > * dict)
Compression algorithm for use in the CMSSW and sPHENIX projects. Using 16-bit short integers to store 32-bit floating-point values. Author: fishy.nosp@m.u@ii.nosp@m.i.org.nosp@m..tw June 8, 2021
Definition at line 17 of file compressor_generator.h.
View newest version in sPHENIX GitHub at line 17 of file compressor_generator.h
References Acts::Test::at, and i.
Referenced by DSTCompressor::compressPhi(), and DSTCompressor::compressZ().