Analysis Software: TpcSpaceChargeMatrixContainer Class Reference
TpcSpaceChargeMatrixContainer Class Reference
Cluster container object.
#include <coresoftware/blob/master/offline/packages/tpccalib/TpcSpaceChargeMatrixContainer.h>
Public Member Functions
TpcSpaceChargeMatrixContainer ()
constructor
~TpcSpaceChargeMatrixContainer () override=default
destructor
accessors
void identify (std::ostream &os=std::cout) const override
identify object
virtual void get_grid_dimensions (int &phibins, int &rbins, int &zbins) const
get grid dimensions
virtual int get_grid_size () const
get total grid size
virtual int get_cell_index (int iphibin, int irbin, int izbin) const
get grid index for given sub-indexes
virtual int get_entries (int cell_index) const
get entries for a given cell
virtual float get_lhs (int cell_index, int i, int j) const
get left hand side
virtual float get_rhs (int cell_index, int i) const
get right hand side
modifiers
void Reset () override
reset method
virtual void set_grid_dimensions (int phibins, int rbins, int zbins)
set grid dimensions
virtual void add_to_entries (int cell_index)
increment cell entries
virtual void add_to_entries (int cell_index, int value)
increment cell entries
virtual void add_to_lhs (int cell_index, int i, int j, float value)
increment left hand side matrix
virtual void add_to_rhs (int cell_index, int i, float value)
increment right hand side column
virtual bool add (const TpcSpaceChargeMatrixContainer &other)
add content from other container, returns true on success
Public Member Functions inherited from PHObject
PHObject ()
ctor
~PHObject () override
dtor
virtual PHObject * CloneMe () const
Virtual copy constructor.
virtual PHObject * clone () const final
PHObject * Clone (const char *newname="") const final
void Copy (TObject &object) const final
virtual int isValid () const
isValid returns non zero if object contains vailid data
virtual int isValid (const float) const
virtual int isValid (const double) const
virtual int isValid (const int) const
virtual int isValid (const unsigned int) const
virtual int isImplemented (const float f) const
virtual int isImplemented (const double f) const
virtual int isImplemented (const int i) const
virtual int isImplemented (const unsigned int i) const
virtual int Integrate () const
virtual int Integrate (PHObject *obj)
virtual void CopyFrom (const PHObject *obj)
Detailed Description
Cluster container object.
Definition at line 18 of file TpcSpaceChargeMatrixContainer.h.
View newest version in sPHENIX GitHub at line 18 of file TpcSpaceChargeMatrixContainer.h
Constructor & Destructor Documentation
TpcSpaceChargeMatrixContainer::TpcSpaceChargeMatrixContainer () inline
constructor
Definition at line 23 of file TpcSpaceChargeMatrixContainer.h.
View newest version in sPHENIX GitHub at line 23 of file TpcSpaceChargeMatrixContainer.h
TpcSpaceChargeMatrixContainer::~TpcSpaceChargeMatrixContainer () override default
destructor
Member Function Documentation
virtual bool TpcSpaceChargeMatrixContainer::add (const TpcSpaceChargeMatrixContainer & other) inline virtual
add content from other container, returns true on success
Reimplemented in TpcSpaceChargeMatrixContainerv1.
Definition at line 94 of file TpcSpaceChargeMatrixContainer.h.
View newest version in sPHENIX GitHub at line 94 of file TpcSpaceChargeMatrixContainer.h
virtual void TpcSpaceChargeMatrixContainer::add_to_entries (int cell_index) inline virtual
increment cell entries
Reimplemented in TpcSpaceChargeMatrixContainerv1.
Definition at line 78 of file TpcSpaceChargeMatrixContainer.h.
View newest version in sPHENIX GitHub at line 78 of file TpcSpaceChargeMatrixContainer.h
virtual void TpcSpaceChargeMatrixContainer::add_to_entries (int cell_index, int value) inline virtual
increment cell entries
Reimplemented in TpcSpaceChargeMatrixContainerv1.
Definition at line 82 of file TpcSpaceChargeMatrixContainer.h.
View newest version in sPHENIX GitHub at line 82 of file TpcSpaceChargeMatrixContainer.h
virtual void TpcSpaceChargeMatrixContainer::add_to_lhs (int cell_index, int i, int j, float value) inline virtual
increment left hand side matrix
Reimplemented in TpcSpaceChargeMatrixContainerv1.
Definition at line 86 of file TpcSpaceChargeMatrixContainer.h.
View newest version in sPHENIX GitHub at line 86 of file TpcSpaceChargeMatrixContainer.h
virtual void TpcSpaceChargeMatrixContainer::add_to_rhs (int cell_index, int i, float value) inline virtual
increment right hand side column
Reimplemented in TpcSpaceChargeMatrixContainerv1.
Definition at line 90 of file TpcSpaceChargeMatrixContainer.h.
View newest version in sPHENIX GitHub at line 90 of file TpcSpaceChargeMatrixContainer.h
virtual int TpcSpaceChargeMatrixContainer::get_cell_index (int iphibin, int irbin, int izbin) const inline virtual
get grid index for given sub-indexes
Reimplemented in TpcSpaceChargeMatrixContainerv1.
Definition at line 45 of file TpcSpaceChargeMatrixContainer.h.
View newest version in sPHENIX GitHub at line 45 of file TpcSpaceChargeMatrixContainer.h
virtual int TpcSpaceChargeMatrixContainer::get_entries (int cell_index) const inline virtual
get entries for a given cell
Reimplemented in TpcSpaceChargeMatrixContainerv1.
Definition at line 49 of file TpcSpaceChargeMatrixContainer.h.
View newest version in sPHENIX GitHub at line 49 of file TpcSpaceChargeMatrixContainer.h
Referenced by TpcSpaceChargeMatrixContainerv1::add().
virtual void TpcSpaceChargeMatrixContainer::get_grid_dimensions (int & phibins, int & rbins, int & zbins) const inline virtual
get grid dimensions
Reimplemented in TpcSpaceChargeMatrixContainerv1.
Definition at line 37 of file TpcSpaceChargeMatrixContainer.h.
View newest version in sPHENIX GitHub at line 37 of file TpcSpaceChargeMatrixContainer.h
Referenced by TpcSpaceChargeMatrixInversion::add(), and TpcSpaceChargeMatrixContainerv1::add().
virtual int TpcSpaceChargeMatrixContainer::get_grid_size () const inline virtual
get total grid size
Reimplemented in TpcSpaceChargeMatrixContainerv1.
Definition at line 41 of file TpcSpaceChargeMatrixContainer.h.
View newest version in sPHENIX GitHub at line 41 of file TpcSpaceChargeMatrixContainer.h
virtual float TpcSpaceChargeMatrixContainer::get_lhs (int cell_index, int i, int j) const inline virtual
get left hand side
Reimplemented in TpcSpaceChargeMatrixContainerv1.
Definition at line 53 of file TpcSpaceChargeMatrixContainer.h.
View newest version in sPHENIX GitHub at line 53 of file TpcSpaceChargeMatrixContainer.h
Referenced by TpcSpaceChargeMatrixContainerv1::add().
virtual float TpcSpaceChargeMatrixContainer::get_rhs (int cell_index, int i) const inline virtual
get right hand side
Reimplemented in TpcSpaceChargeMatrixContainerv1.
Definition at line 57 of file TpcSpaceChargeMatrixContainer.h.
View newest version in sPHENIX GitHub at line 57 of file TpcSpaceChargeMatrixContainer.h
Referenced by TpcSpaceChargeMatrixContainerv1::add().
void TpcSpaceChargeMatrixContainer::identify (std::ostream & os = std::cout) const inline override virtual
identify object
Reimplemented from PHObject.
Reimplemented in TpcSpaceChargeMatrixContainerv1.
Definition at line 33 of file TpcSpaceChargeMatrixContainer.h.
View newest version in sPHENIX GitHub at line 33 of file TpcSpaceChargeMatrixContainer.h
void TpcSpaceChargeMatrixContainer::Reset () inline override virtual
reset method
Reimplemented from PHObject.
Reimplemented in TpcSpaceChargeMatrixContainerv1.
Definition at line 66 of file TpcSpaceChargeMatrixContainer.h.
View newest version in sPHENIX GitHub at line 66 of file TpcSpaceChargeMatrixContainer.h
virtual void TpcSpaceChargeMatrixContainer::set_grid_dimensions (int phibins, int rbins, int zbins) inline virtual
set grid dimensions
Parameters
phibins the number of bins in the azimuth direction
zbins the number of bins along z
Reimplemented in TpcSpaceChargeMatrixContainerv1.
Definition at line 74 of file TpcSpaceChargeMatrixContainer.h.
View newest version in sPHENIX GitHub at line 74 of file TpcSpaceChargeMatrixContainer.h
The documentation for this class was generated from the following file:
coresoftware/blob/master/offline/packages/tpccalib/TpcSpaceChargeMatrixContainer.h