Analysis Software: daq_device_pluginexample Class Reference
daq_device_pluginexample Class Reference
#include <rcdaq/blob/master/daq_device_pluginexample.h>
Public Member Functions
daq_device_pluginexample (const int eventtype, const int subeventid, const int n_words=32, const int trigger_enabled=0)
~daq_device_pluginexample ()
void identify (std::ostream &os=std::cout) const
int max_length (const int etype) const
int put_data (const int etype, int *adr, const int length)
int init ()
int rearm (const int etype)
Public Member Functions inherited from daq_device
daq_device ()
virtual ~daq_device ()
virtual int endrun ()
virtual int subeventid () const
Protected Attributes
subevtdata_ptr sevt
unsigned int number_of_words
pulserTriggerHandler * th
Protected Attributes inherited from daq_device
long m_subeventid
long m_eventType
Additional Inherited Members
Static Public Member Functions inherited from daq_device
static int formatPacketHdr (int *adr)
Detailed Description
Definition at line 21 of file daq_device_pluginexample.h.
View newest version in sPHENIX GitHub at line 21 of file daq_device_pluginexample.h
Constructor & Destructor Documentation
daq_device_pluginexample::daq_device_pluginexample (const int eventtype, const int subeventid, const int n_words = 32, const int trigger_enabled = 0)
Definition at line 8 of file daq_device_pluginexample.cc.
View newest version in sPHENIX GitHub at line 8 of file daq_device_pluginexample.cc
References registerTriggerHandler().
daq_device_pluginexample::~daq_device_pluginexample ()
Definition at line 28 of file daq_device_pluginexample.cc.
View newest version in sPHENIX GitHub at line 28 of file daq_device_pluginexample.cc
References clearTriggerHandler().
Member Function Documentation
void daq_device_pluginexample::identify (std::ostream & os = std::cout) const virtual
Implements daq_device.
Definition at line 79 of file daq_device_pluginexample.cc.
View newest version in sPHENIX GitHub at line 79 of file daq_device_pluginexample.cc
int daq_device_pluginexample::init (void) virtual
Reimplemented from daq_device.
Definition at line 100 of file daq_device_pluginexample.cc.
View newest version in sPHENIX GitHub at line 100 of file daq_device_pluginexample.cc
int daq_device_pluginexample::max_length (const int etype) const virtual
Implements daq_device.
Definition at line 94 of file daq_device_pluginexample.cc.
View newest version in sPHENIX GitHub at line 94 of file daq_device_pluginexample.cc
References SEVTHEADERLENGTH.
int daq_device_pluginexample::put_data (const int etype, int * adr, const int length) virtual
Implements daq_device.
Definition at line 38 of file daq_device_pluginexample.cc.
View newest version in sPHENIX GitHub at line 38 of file daq_device_pluginexample.cc
References for(), ID4EVT, and SEVTHEADERLENGTH.
int daq_device_pluginexample::rearm (const int etype) virtual
Reimplemented from daq_device.
Definition at line 107 of file daq_device_pluginexample.cc.
View newest version in sPHENIX GitHub at line 107 of file daq_device_pluginexample.cc
Member Data Documentation
unsigned int daq_device_pluginexample::number_of_words protected
Definition at line 48 of file daq_device_pluginexample.h.
View newest version in sPHENIX GitHub at line 48 of file daq_device_pluginexample.h
subevtdata_ptr daq_device_pluginexample::sevt protected
Definition at line 47 of file daq_device_pluginexample.h.
View newest version in sPHENIX GitHub at line 47 of file daq_device_pluginexample.h
pulserTriggerHandler* daq_device_pluginexample::th protected
Definition at line 49 of file daq_device_pluginexample.h.
View newest version in sPHENIX GitHub at line 49 of file daq_device_pluginexample.h
The documentation for this class was generated from the following files:
rcdaq/blob/master/daq_device_pluginexample.h
rcdaq/blob/master/daq_device_pluginexample.cc