Analysis Software: ActsExamples::DefaultHoughFunctions Namespace Reference
ActsExamples::DefaultHoughFunctions Namespace Reference
Typedefs
using ResultDouble = Acts::Result< double >
using ResultBool = Acts::Result< bool >
using ResultUnsigned = Acts::Result< unsigned >
Functions
ResultDouble fieldCorrectionDefault (unsigned region, double y, double r)
ResultUnsigned findLayerIDDefault (double r)
ResultBool inSliceDefault (double z, unsigned layer, int slice)
Typedef Documentation
using ActsExamples::DefaultHoughFunctions::ResultBool = typedef Acts::Result<bool>
Definition at line 30 of file DefaultHoughFunctions.hpp.
View newest version in sPHENIX GitHub at line 30 of file DefaultHoughFunctions.hpp
using ActsExamples::DefaultHoughFunctions::ResultDouble = typedef Acts::Result<double>
Definition at line 29 of file DefaultHoughFunctions.hpp.
View newest version in sPHENIX GitHub at line 29 of file DefaultHoughFunctions.hpp
using ActsExamples::DefaultHoughFunctions::ResultUnsigned = typedef Acts::Result<unsigned>
Definition at line 31 of file DefaultHoughFunctions.hpp.
View newest version in sPHENIX GitHub at line 31 of file DefaultHoughFunctions.hpp
Function Documentation
ResultDouble ActsExamples::DefaultHoughFunctions::fieldCorrectionDefault (unsigned region, double y, double r)
Definition at line 33 of file DefaultHoughFunctions.hpp.
View newest version in sPHENIX GitHub at line 33 of file DefaultHoughFunctions.hpp
References physmon_track_finding_ttbar::r.
Referenced by ActsExamples::HoughTransformSeeder::HoughTransformSeeder(), and runHoughExample().
ResultUnsigned ActsExamples::DefaultHoughFunctions::findLayerIDDefault (double r)
shouldn't be here, this won't be used
Definition at line 41 of file DefaultHoughFunctions.hpp.
View newest version in sPHENIX GitHub at line 41 of file DefaultHoughFunctions.hpp
Referenced by ActsExamples::HoughTransformSeeder::HoughTransformSeeder(), and runHoughExample().
ResultBool ActsExamples::DefaultHoughFunctions::inSliceDefault (double z, unsigned layer, int slice)
Definition at line 69 of file DefaultHoughFunctions.hpp.
View newest version in sPHENIX GitHub at line 69 of file DefaultHoughFunctions.hpp
Referenced by ActsExamples::HoughTransformSeeder::HoughTransformSeeder(), and runHoughExample().