Analysis Software: Acts::Test::DetectorElementStub Class Reference
Acts::Test::DetectorElementStub Class Reference
#include <acts/blob/sPHENIX/Tests/CommonHelpers/Acts/Tests/CommonHelpers/DetectorElementStub.hpp>
Public Member Functions
DetectorElementStub ()
DetectorElementStub (const Transform3 &transform)
DetectorElementStub (const Transform3 &transform, std::shared_ptr< const CylinderBounds > cBounds, double thickness, std::shared_ptr< const ISurfaceMaterial > material=nullptr)
DetectorElementStub (const Transform3 &transform, std::shared_ptr< const PlanarBounds > pBounds, double thickness, std::shared_ptr< const ISurfaceMaterial > material=nullptr)
DetectorElementStub (const Transform3 &transform, std::shared_ptr< const LineBounds > lBounds, double thickness, std::shared_ptr< const ISurfaceMaterial > material=nullptr)
~DetectorElementStub () override=default
Destructor.
const Transform3 & transform (const GeometryContext &gctx) const override
const Surface & surface () const override
Return surface associated with this detector element.
Surface & surface () override
Non-const access to surface associated with this detector element.
double thickness () const override
The maximal thickness of the detector element wrt normal axis.
Public Member Functions inherited from Acts::DetectorElementBase
DetectorElementBase ()=default
virtual ~DetectorElementBase ()=default
Private Attributes
Transform3 m_elementTransform
the transform for positioning in 3D space
std::shared_ptr< Surface > m_elementSurface {nullptr}
the surface represented by it
double m_elementThickness {0.}
the element thickness
Detailed Description
This is a lightweight type of detector element, it simply implements the base class.
Definition at line 32 of file DetectorElementStub.hpp.
View newest version in sPHENIX GitHub at line 32 of file DetectorElementStub.hpp
Constructor & Destructor Documentation
Acts::Test::DetectorElementStub::DetectorElementStub () inline
Definition at line 34 of file DetectorElementStub.hpp.
View newest version in sPHENIX GitHub at line 34 of file DetectorElementStub.hpp
Acts::Test::DetectorElementStub::DetectorElementStub (const Transform3 & transform) inline
Definition at line 36 of file DetectorElementStub.hpp.
View newest version in sPHENIX GitHub at line 36 of file DetectorElementStub.hpp
Acts::Test::DetectorElementStub::DetectorElementStub (const Transform3 & transform, std::shared_ptr< const CylinderBounds > cBounds, double thickness, std::shared_ptr< const ISurfaceMaterial > material = nullptr) inline
Constructor for single sided detector element
bound to a Line Surface
Parameters
transform places the element in global frame
cBounds is the cylindrical bounds
thickness is the module thickness
material is the (optional) Surface material associated to it
Definition at line 46 of file DetectorElementStub.hpp.
View newest version in sPHENIX GitHub at line 46 of file DetectorElementStub.hpp
References m_elementSurface, material, and testing::internal::move().
Acts::Test::DetectorElementStub::DetectorElementStub (const Transform3 & transform, std::shared_ptr< const PlanarBounds > pBounds, double thickness, std::shared_ptr< const ISurfaceMaterial > material = nullptr) inline
Constructor for single sided detector element
bound to a Plane Surface
Parameters
transform places the element in global frame
pBounds is the planar bounds for the planar detector element
thickness is the module thickness
material is the (optional) Surface material associated to it
Definition at line 65 of file DetectorElementStub.hpp.
View newest version in sPHENIX GitHub at line 65 of file DetectorElementStub.hpp
References m_elementSurface, material, and testing::internal::move().
Acts::Test::DetectorElementStub::DetectorElementStub (const Transform3 & transform, std::shared_ptr< const LineBounds > lBounds, double thickness, std::shared_ptr< const ISurfaceMaterial > material = nullptr) inline
Constructor for single sided detector element
bound to a Line Surface
Parameters
transform places the element in global frame
dBounds is the line bounds for the line like detector element
thickness is the module thickness
material is the (optional) Surface material associated to it
Definition at line 84 of file DetectorElementStub.hpp.
View newest version in sPHENIX GitHub at line 84 of file DetectorElementStub.hpp
References m_elementSurface, material, and testing::internal::move().
Acts::Test::DetectorElementStub::~DetectorElementStub () override default
Destructor.
Member Function Documentation
const Surface & Acts::Test::DetectorElementStub::surface () const inline override virtual
Return surface associated with this detector element.
Implements Acts::DetectorElementBase.
Definition at line 129 of file DetectorElementStub.hpp.
View newest version in sPHENIX GitHub at line 129 of file DetectorElementStub.hpp
References m_elementSurface.
Referenced by BOOST_AUTO_TEST_CASE().
Surface & Acts::Test::DetectorElementStub::surface () inline override virtual
Non-const access to surface associated with this detector element.
Implements Acts::DetectorElementBase.
Definition at line 133 of file DetectorElementStub.hpp.
View newest version in sPHENIX GitHub at line 133 of file DetectorElementStub.hpp
References m_elementSurface.
double Acts::Test::DetectorElementStub::thickness () const inline override virtual
The maximal thickness of the detector element wrt normal axis.
Implements Acts::DetectorElementBase.
Definition at line 137 of file DetectorElementStub.hpp.
View newest version in sPHENIX GitHub at line 137 of file DetectorElementStub.hpp
References m_elementThickness.
const Transform3 & Acts::Test::DetectorElementStub::transform (const GeometryContext & gctx) const inline override virtual
Return local to global transform associated with this identifier
Parameters
gctx The current geometry context object, e.g. alignment
Note
this is called from the surface().transform() in the PROXY mode
Implements Acts::DetectorElementBase.
Definition at line 124 of file DetectorElementStub.hpp.
View newest version in sPHENIX GitHub at line 124 of file DetectorElementStub.hpp
References m_elementTransform.
Member Data Documentation
std::shared_ptr<Surface> Acts::Test::DetectorElementStub::m_elementSurface {nullptr} private
the surface represented by it
Definition at line 119 of file DetectorElementStub.hpp.
View newest version in sPHENIX GitHub at line 119 of file DetectorElementStub.hpp
Referenced by DetectorElementStub(), and surface().
double Acts::Test::DetectorElementStub::m_elementThickness {0.} private
the element thickness
Definition at line 121 of file DetectorElementStub.hpp.
View newest version in sPHENIX GitHub at line 121 of file DetectorElementStub.hpp
Referenced by thickness().
Transform3 Acts::Test::DetectorElementStub::m_elementTransform private
the transform for positioning in 3D space
Definition at line 117 of file DetectorElementStub.hpp.
View newest version in sPHENIX GitHub at line 117 of file DetectorElementStub.hpp
Referenced by transform().
The documentation for this class was generated from the following file:
acts/blob/sPHENIX/Tests/CommonHelpers/Acts/Tests/CommonHelpers/DetectorElementStub.hpp