Analysis Software: Acts::VertexInfo< input_track_t > Struct Template Reference
Acts::VertexInfo< input_track_t > Struct Template Reference
Helper struct for storing vertex related information.
#include <acts/blob/sPHENIX/Core/include/Acts/Vertexing/AMVFInfo.hpp>
Public Member Functions
VertexInfo ()=default
VertexInfo (const Acts::Vertex< input_track_t > &vtx, const Acts::Vector4D &pos)
Public Attributes
Acts::Vertex< input_track_t > constraintVertex
Acts::Vector4D linPoint {Acts::Vector4D::Zero()}
Acts::Vector4D oldPosition {Acts::Vector4D::Zero()}
Acts::Vector4D seedPosition {Acts::Vector4D::Zero()}
bool relinearize = true
std::vector< const
input_track_t * > trackLinks
std::map< const input_track_t
*, const BoundTrackParameters > ip3dParams
Detailed Description
template<typename input_track_t>
struct Acts::VertexInfo< input_track_t >
Helper struct for storing vertex related information.
Definition at line 21 of file AMVFInfo.hpp.
View newest version in sPHENIX GitHub at line 21 of file AMVFInfo.hpp
Constructor & Destructor Documentation
template<typename input_track_t> Acts::VertexInfo< input_track_t >::VertexInfo () default
template<typename input_track_t> Acts::VertexInfo< input_track_t >::VertexInfo (const Acts::Vertex< input_track_t > & vtx, const Acts::Vector4D & pos) inline
Definition at line 24 of file AMVFInfo.hpp.
View newest version in sPHENIX GitHub at line 24 of file AMVFInfo.hpp
Member Data Documentation
template<typename input_track_t> Acts::Vertex<input_track_t> Acts::VertexInfo< input_track_t >::constraintVertex
Definition at line 31 of file AMVFInfo.hpp.
View newest version in sPHENIX GitHub at line 31 of file AMVFInfo.hpp
template<typename input_track_t> std::map<const input_track_t*, const BoundTrackParameters> Acts::VertexInfo< input_track_t >::ip3dParams
Definition at line 48 of file AMVFInfo.hpp.
View newest version in sPHENIX GitHub at line 48 of file AMVFInfo.hpp
Referenced by Acts::AdaptiveMultiVertexFitter< input_track_t, linearizer_t >::setAllVertexCompatibilities().
template<typename input_track_t> Acts::Vector4D Acts::VertexInfo< input_track_t >::linPoint {Acts::Vector4D::Zero()}
Definition at line 34 of file AMVFInfo.hpp.
View newest version in sPHENIX GitHub at line 34 of file AMVFInfo.hpp
Referenced by Acts::AdaptiveMultiVertexFitter< input_track_t, linearizer_t >::fitImpl(), and Acts::AdaptiveMultiVertexFitter< input_track_t, linearizer_t >::setAllVertexCompatibilities().
template<typename input_track_t> Acts::Vector4D Acts::VertexInfo< input_track_t >::oldPosition {Acts::Vector4D::Zero()}
Definition at line 37 of file AMVFInfo.hpp.
View newest version in sPHENIX GitHub at line 37 of file AMVFInfo.hpp
Referenced by Acts::AdaptiveMultiVertexFitter< input_track_t, linearizer_t >::fitImpl(), and Acts::AdaptiveMultiVertexFitter< input_track_t, linearizer_t >::setAllVertexCompatibilities().
template<typename input_track_t> bool Acts::VertexInfo< input_track_t >::relinearize = true
Definition at line 43 of file AMVFInfo.hpp.
View newest version in sPHENIX GitHub at line 43 of file AMVFInfo.hpp
Referenced by Acts::AdaptiveMultiVertexFitter< input_track_t, linearizer_t >::fitImpl().
template<typename input_track_t> Acts::Vector4D Acts::VertexInfo< input_track_t >::seedPosition {Acts::Vector4D::Zero()}
Definition at line 40 of file AMVFInfo.hpp.
View newest version in sPHENIX GitHub at line 40 of file AMVFInfo.hpp
template<typename input_track_t> std::vector<const input_track_t*> Acts::VertexInfo< input_track_t >::trackLinks
Definition at line 46 of file AMVFInfo.hpp.
View newest version in sPHENIX GitHub at line 46 of file AMVFInfo.hpp
Referenced by Acts::AdaptiveMultiVertexFitter< input_track_t, linearizer_t >::setAllVertexCompatibilities(), and Acts::AdaptiveMultiVertexFitter< input_track_t, linearizer_t >::setWeightsAndUpdate().
The documentation for this struct was generated from the following file:
acts/blob/sPHENIX/Core/include/Acts/Vertexing/AMVFInfo.hpp