Analysis Software: TpcClusterBuilder Class Reference
TpcClusterBuilder Class Reference
#include <coresoftware/blob/master/simulation/g4simulation/g4tpc/TpcClusterBuilder.h>
Public Member Functions
TpcClusterBuilder ()
void fixme_check ()
void fixme_short_check ()
void cluster_hits (TrkrTruthTrack *track)
void addhitset (TrkrDefs::hitsetkey, TrkrDefs::hitkey, float neffelectrons)
void set_current_track (TrkrTruthTrack *_trkrtruthtrack)
void print (TrkrTruthTrackContainer *, int nclusprint=-1)
void print_file (TrkrTruthTrackContainer *, std::string)
void set_verbosity (int verbosity_level)
~TpcClusterBuilder ()
void clear_hitsetkey_cnt ()
void set_pixel_thresholdrat (double val)
void set_input_nodes (TrkrClusterContainer *_truth_cluster_container, ActsGeometry *_ActsGeometry, PHG4TpcCylinderGeomContainer *_geom_container, ClusHitsVerbosev1 *_clushitsverbose)
Public Attributes
bool b_collect_hits { false }
bool needs_input_nodes = true
Private Member Functions
double square (double)
double square (float)
Private Attributes
TrkrClusterContainer * m_clusterlist { nullptr }
ActsGeometry * m_tGeometry { nullptr }
PHG4TpcCylinderGeomContainer * geom_container { nullptr }
TrkrHitSetContainer * m_hits { new TrkrHitSetContainerv1() }
std::map< TrkrDefs::hitsetkey,
unsigned int > hitsetkey_cnt {}
int n_tracks {0}
int verbosity {0}
double AdcClockPeriod = 53.0
double m_sampa_tbias = 39.6
double m_pixel_thresholdrat { 0.01 }
ClusHitsVerbosev1 * mClusHitsVerbose { nullptr }
Detailed Description
Definition at line 43 of file TpcClusterBuilder.h.
View newest version in sPHENIX GitHub at line 43 of file TpcClusterBuilder.h
Constructor & Destructor Documentation
TpcClusterBuilder::TpcClusterBuilder () inline
Definition at line 63 of file TpcClusterBuilder.h.
View newest version in sPHENIX GitHub at line 63 of file TpcClusterBuilder.h
TpcClusterBuilder::~TpcClusterBuilder () inline
Definition at line 81 of file TpcClusterBuilder.h.
View newest version in sPHENIX GitHub at line 81 of file TpcClusterBuilder.h
References m_hits.
Member Function Documentation
void TpcClusterBuilder::addhitset (TrkrDefs::hitsetkey hitsetkey, TrkrDefs::hitkey hitkey, float neffelectrons)
Definition at line 310 of file TpcClusterBuilder.cc.
View newest version in sPHENIX GitHub at line 310 of file TpcClusterBuilder.cc
References TrkrHit::addEnergy(), b_collect_hits, TrkrHitSetContainer::findOrAddHitSet(), and m_hits.
Referenced by PHG4TpcPadPlaneReadout::MapToPadPlane().
void TpcClusterBuilder::clear_hitsetkey_cnt ()
Definition at line 335 of file TpcClusterBuilder.cc.
View newest version in sPHENIX GitHub at line 335 of file TpcClusterBuilder.cc
References hitsetkey_cnt.
Referenced by PHG4TpcElectronDrift::process_event().
void TpcClusterBuilder::cluster_hits (TrkrTruthTrack * track)
Definition at line 35 of file TpcClusterBuilder.cc.
View newest version in sPHENIX GitHub at line 35 of file TpcClusterBuilder.cc
References _, AdcClockPeriod, TrkrTruthTrack::addCluster(), TrkrClusterContainer::addClusterSpecifyKey(), ClusHitsVerbosev1::addPhiCutHit(), ClusHitsVerbosev1::addPhiHit(), ClusHitsVerbosev1::addZCutHit(), ClusHitsVerbosev1::addZHit(), Acts::UnitConstants::cm, TrkrDefs::genClusKey(), geom_container, ActsGeometry::geometry(), ActsGeometry::get_drift_velocity(), PHG4TpcCylinderGeom::get_phi(), PHG4TpcCylinderGeom::get_phibins(), PHG4TpcCylinderGeom::get_radius(), ActsGeometry::get_tpc_surface_from_coords(), PHG4TpcCylinderGeom::get_zbins(), PHG4TpcCylinderGeom::get_zcenter(), ActsTrackingGeometry::getGeoContext(), TrkrHitSet::getHits(), TrkrHitSetContainer::getHitSets(), TrkrDefs::getLayer(), PHG4TpcCylinderGeomContainer::GetLayerCellGeom(), TpcDefs::getPad(), TrkrTruthTrack::getPt(), TpcDefs::getSectorId(), TpcDefs::getSide(), TpcDefs::getTBin(), TrkrTruthTrack::getTrackid(), hitsetkey_cnt, it, layer, m_clusterlist, m_hits, m_pixel_thresholdrat, m_sampa_tbias, m_tGeometry, mClusHitsVerbose, MATSCAN::phibins, phisize, ClusHitsVerbosev1::push_hits(), TrkrHitSetContainer::Reset(), TrkrClusterv4::setAdc(), writeMapConfig::surface, t, TrkrDefs::tpcId, and verbosity.
Referenced by PHG4TpcElectronDrift::process_event().
void TpcClusterBuilder::fixme_check ()
void TpcClusterBuilder::fixme_short_check ()
void TpcClusterBuilder::print (TrkrTruthTrackContainer * truth_tracks, int nclusprint = -1)
Definition at line 339 of file TpcClusterBuilder.cc.
View newest version in sPHENIX GitHub at line 339 of file TpcClusterBuilder.cc
References TrkrDefs::getClusIndex(), TrkrDefs::getHitSetKeyFromClusKey(), TrkrTruthTrackContainer::getMap(), printf(), and verbosity.
Referenced by PHG4TpcElectronDrift::process_event().
void TpcClusterBuilder::print_file (TrkrTruthTrackContainer * truth_tracks, std::string ofile_name)
Definition at line 371 of file TpcClusterBuilder.cc.
View newest version in sPHENIX GitHub at line 371 of file TpcClusterBuilder.cc
References C, TrkrClusterContainer::findCluster(), fout, TrkrDefs::getClusIndex(), TrkrDefs::getHitSetKeyFromClusKey(), TrkrTruthTrackContainer::getMap(), and m_clusterlist.
Referenced by PHG4TpcElectronDrift::process_event().
void TpcClusterBuilder::set_current_track (TrkrTruthTrack * _trkrtruthtrack)
void TpcClusterBuilder::set_input_nodes (TrkrClusterContainer * _truth_cluster_container, ActsGeometry * _ActsGeometry, PHG4TpcCylinderGeomContainer * _geom_container, ClusHitsVerbosev1 * _clushitsverbose)
Definition at line 403 of file TpcClusterBuilder.cc.
View newest version in sPHENIX GitHub at line 403 of file TpcClusterBuilder.cc
References geom_container, m_clusterlist, m_tGeometry, mClusHitsVerbose, and needs_input_nodes.
Referenced by PHG4TpcElectronDrift::process_event().
void TpcClusterBuilder::set_pixel_thresholdrat (double val) inline
Definition at line 105 of file TpcClusterBuilder.h.
View newest version in sPHENIX GitHub at line 105 of file TpcClusterBuilder.h
References m_pixel_thresholdrat.
Referenced by PHG4TpcElectronDrift::set_pixel_thresholdrat().
void TpcClusterBuilder::set_verbosity (int verbosity_level)
Definition at line 33 of file TpcClusterBuilder.cc.
View newest version in sPHENIX GitHub at line 33 of file TpcClusterBuilder.cc
References verbosity.
double TpcClusterBuilder::square (double v) private
Definition at line 30 of file TpcClusterBuilder.cc.
View newest version in sPHENIX GitHub at line 30 of file TpcClusterBuilder.cc
References testSigmaEff::v.
double TpcClusterBuilder::square (float v) private
Definition at line 31 of file TpcClusterBuilder.cc.
View newest version in sPHENIX GitHub at line 31 of file TpcClusterBuilder.cc
References testSigmaEff::v.
Member Data Documentation
double TpcClusterBuilder::AdcClockPeriod = 53.0 private
Definition at line 91 of file TpcClusterBuilder.h.
View newest version in sPHENIX GitHub at line 91 of file TpcClusterBuilder.h
Referenced by cluster_hits().
bool TpcClusterBuilder::b_collect_hits { false }
Definition at line 72 of file TpcClusterBuilder.h.
View newest version in sPHENIX GitHub at line 72 of file TpcClusterBuilder.h
Referenced by addhitset(), and PHG4TpcElectronDrift::process_event().
PHG4TpcCylinderGeomContainer* TpcClusterBuilder::geom_container { nullptr } private
Definition at line 49 of file TpcClusterBuilder.h.
View newest version in sPHENIX GitHub at line 49 of file TpcClusterBuilder.h
Referenced by cluster_hits(), and set_input_nodes().
std::map<TrkrDefs::hitsetkey,unsigned int> TpcClusterBuilder::hitsetkey_cnt {} private
Definition at line 54 of file TpcClusterBuilder.h.
View newest version in sPHENIX GitHub at line 54 of file TpcClusterBuilder.h
Referenced by clear_hitsetkey_cnt(), and cluster_hits().
TrkrClusterContainer* TpcClusterBuilder::m_clusterlist { nullptr } private
Definition at line 47 of file TpcClusterBuilder.h.
View newest version in sPHENIX GitHub at line 47 of file TpcClusterBuilder.h
Referenced by cluster_hits(), print_file(), and set_input_nodes().
TrkrHitSetContainer* TpcClusterBuilder::m_hits { new TrkrHitSetContainerv1() } private
Definition at line 52 of file TpcClusterBuilder.h.
View newest version in sPHENIX GitHub at line 52 of file TpcClusterBuilder.h
Referenced by addhitset(), cluster_hits(), and ~TpcClusterBuilder().
double TpcClusterBuilder::m_pixel_thresholdrat { 0.01 } private
Definition at line 100 of file TpcClusterBuilder.h.
View newest version in sPHENIX GitHub at line 100 of file TpcClusterBuilder.h
Referenced by cluster_hits(), and set_pixel_thresholdrat().
double TpcClusterBuilder::m_sampa_tbias = 39.6 private
Definition at line 95 of file TpcClusterBuilder.h.
View newest version in sPHENIX GitHub at line 95 of file TpcClusterBuilder.h
Referenced by cluster_hits().
ActsGeometry* TpcClusterBuilder::m_tGeometry { nullptr } private
Definition at line 48 of file TpcClusterBuilder.h.
View newest version in sPHENIX GitHub at line 48 of file TpcClusterBuilder.h
Referenced by cluster_hits(), and set_input_nodes().
ClusHitsVerbosev1* TpcClusterBuilder::mClusHitsVerbose { nullptr } private
Definition at line 101 of file TpcClusterBuilder.h.
View newest version in sPHENIX GitHub at line 101 of file TpcClusterBuilder.h
Referenced by cluster_hits(), and set_input_nodes().
int TpcClusterBuilder::n_tracks {0} private
Definition at line 59 of file TpcClusterBuilder.h.
View newest version in sPHENIX GitHub at line 59 of file TpcClusterBuilder.h
bool TpcClusterBuilder::needs_input_nodes = true
Definition at line 106 of file TpcClusterBuilder.h.
View newest version in sPHENIX GitHub at line 106 of file TpcClusterBuilder.h
Referenced by PHG4TpcElectronDrift::process_event(), and set_input_nodes().
int TpcClusterBuilder::verbosity {0} private
Definition at line 60 of file TpcClusterBuilder.h.
View newest version in sPHENIX GitHub at line 60 of file TpcClusterBuilder.h
Referenced by cluster_hits(), print(), and set_verbosity().
The documentation for this class was generated from the following files:
coresoftware/blob/master/simulation/g4simulation/g4tpc/TpcClusterBuilder.h
coresoftware/blob/master/simulation/g4simulation/g4tpc/TpcClusterBuilder.cc