Analysis Software: Acts::Test::Layers Namespace Reference
Acts::Test::Layers Namespace Reference
Functions
BOOST_AUTO_TEST_CASE (ConeLayerConstruction)
Unit test for creating compliant/non-compliant ConeLayer object.
BOOST_AUTO_TEST_CASE (CylinderLayerConstruction)
Unit test for creating compliant/non-compliant CylinderLayer object.
BOOST_AUTO_TEST_CASE (CylinderLayerProperties)
Unit test for testing Layer properties.
BOOST_AUTO_TEST_CASE (DiscLayerConstruction)
Unit test for creating compliant/non-compliant DiscLayer object.
BOOST_AUTO_TEST_CASE (DiscLayerProperties)
Unit test for testing Layer properties.
BOOST_AUTO_TEST_CASE (GenericApproachDescriptorConstruction)
BOOST_AUTO_TEST_CASE (GenericApproachDescriptorProperties)
Unit test for testing GenericApproachDescriptor properties.
BOOST_AUTO_TEST_CASE (GenericApproachNoOverstepping)
BOOST_AUTO_TEST_CASE (LayerConstruction)
Unit test for creating compliant/non-compliant Layer object.
BOOST_AUTO_TEST_CASE (LayerProperties)
Unit test for testing Layer properties.
BOOST_AUTO_TEST_CASE (NavigationLayerConstruction)
Unit test for creating compliant/non-compliant NavigationLayer object.
BOOST_AUTO_TEST_CASE (NavigationLayerProperties)
Unit test for testing NavigationLayer properties.
BOOST_AUTO_TEST_CASE (PlaneLayerConstruction)
Unit test for creating compliant/non-compliant PlaneLayer object.
BOOST_AUTO_TEST_CASE (PlaneLayerProperties)
Unit test for testing Layer properties.
BOOST_AUTO_TEST_CASE (ProtoLayerHelperTests)
BOOST_AUTO_TEST_CASE (ProtoLayerTests)
Variables
GeometryContext tgContext = GeometryContext()
Function Documentation
Acts::Test::Layers::BOOST_AUTO_TEST_CASE (ProtoLayerHelperTests)
Cylindrical section ------------------------------------------———
Disc section ---------------------------------------------——
Ring layout section ------------------------------------------------—
Definition at line 35 of file ProtoLayerHelperTests.cpp.
View newest version in sPHENIX GitHub at line 35 of file ProtoLayerHelperTests.cpp
References Acts::binR, Acts::binZ, Acts::ObjVisualization3D< T >::clear(), Acts::GeometryView3D::drawSurface(), Acts::getDefaultLogger(), layer, Acts::ProtoLayerHelper::protoLayers(), Acts::Test::CylindricalTrackingGeometry::surfacesCylinder(), Acts::Test::CylindricalTrackingGeometry::surfacesRing(), tgContext, to_string(), Acts::Logging::VERBOSE, and Acts::ObjVisualization3D< T >::write().
Acts::Test::Layers::BOOST_AUTO_TEST_CASE (ProtoLayerTests)
Definition at line 38 of file ProtoLayerTests.cpp.
View newest version in sPHENIX GitHub at line 38 of file ProtoLayerTests.cpp
References Acts::binR, Acts::binX, Acts::binY, Acts::binZ, CHECK_CLOSE_ABS, Acts::UnitConstants::e, and tgContext.
Acts::Test::Layers::BOOST_AUTO_TEST_CASE (ConeLayerConstruction)
Unit test for creating compliant/non-compliant ConeLayer object.
Constructor with transform pointer
Definition at line 39 of file ConeLayerTests.cpp.
View newest version in sPHENIX GitHub at line 39 of file ConeLayerTests.cpp
References Acts::active, alpha, Acts::ConeLayer::create(), testing::internal::move(), Acts::passive, rBounds, thickness, and translation().
Acts::Test::Layers::BOOST_AUTO_TEST_CASE (NavigationLayerConstruction)
Unit test for creating compliant/non-compliant NavigationLayer object.
Definition at line 40 of file NavigationLayerTests.cpp.
View newest version in sPHENIX GitHub at line 40 of file NavigationLayerTests.cpp
References Acts::NavigationLayer::create(), testing::internal::move(), Acts::navigation, pSurface, and thickness.
Acts::Test::Layers::BOOST_AUTO_TEST_CASE (DiscLayerConstruction)
Unit test for creating compliant/non-compliant DiscLayer object.
Construction
Definition at line 45 of file DiscLayerTests.cpp.
View newest version in sPHENIX GitHub at line 45 of file DiscLayerTests.cpp
References Acts::DiscLayer::create(), testing::internal::move(), Acts::passive, rBounds, thickness, and translation().
Acts::Test::Layers::BOOST_AUTO_TEST_CASE (CylinderLayerConstruction)
Unit test for creating compliant/non-compliant CylinderLayer object.
Construction
Definition at line 46 of file CylinderLayerTests.cpp.
View newest version in sPHENIX GitHub at line 46 of file CylinderLayerTests.cpp
References CHECK_CLOSE_REL, Acts::CylinderLayer::create(), Acts::UnitConstants::e, testing::internal::move(), Acts::passive, rBounds, thickness, and translation().
Acts::Test::Layers::BOOST_AUTO_TEST_CASE (LayerConstruction)
Unit test for creating compliant/non-compliant Layer object.
Minimum possible construction (default constructor is deleted)
Need an approach descriptor for the next level of complexity:
Construction with (minimal) approach descriptor
Definition at line 46 of file LayerTests.cpp.
View newest version in sPHENIX GitHub at line 46 of file LayerTests.cpp
References Acts::LayerStub::constructedOk(), testing::internal::move(), and thickness.
Acts::Test::Layers::BOOST_AUTO_TEST_CASE (PlaneLayerConstruction)
Unit test for creating compliant/non-compliant PlaneLayer object.
Constructor with transform pointer
Definition at line 46 of file PlaneLayerTests.cpp.
View newest version in sPHENIX GitHub at line 46 of file PlaneLayerTests.cpp
References Acts::active, Acts::binZ, Acts::PlaneLayer::create(), Acts::Test::halfX, Acts::Test::halfY, testing::internal::move(), Acts::passive, rBounds, Acts::SurfaceArrayCreator::surfaceArrayOnPlane(), tgContext, thickness, and translation().
Acts::Test::Layers::BOOST_AUTO_TEST_CASE (GenericApproachDescriptorConstruction)
Unit test for creating compliant/non-compliant GenericApproachDescriptor object
Definition at line 49 of file GenericApproachDescriptorTests.cpp.
View newest version in sPHENIX GitHub at line 49 of file GenericApproachDescriptorTests.cpp
Acts::Test::Layers::BOOST_AUTO_TEST_CASE (NavigationLayerProperties)
Unit test for testing NavigationLayer properties.
Definition at line 54 of file NavigationLayerTests.cpp.
View newest version in sPHENIX GitHub at line 54 of file NavigationLayerTests.cpp
References KFPMath::b, Acts::binZ, Acts::NavigationLayer::create(), testing::internal::move(), Acts::Test::origin(), pSurface, tgContext, and thickness.
Acts::Test::Layers::BOOST_AUTO_TEST_CASE (GenericApproachDescriptorProperties)
Unit test for testing GenericApproachDescriptor properties.
Definition at line 65 of file GenericApproachDescriptorTests.cpp.
View newest version in sPHENIX GitHub at line 65 of file GenericApproachDescriptorTests.cpp
References Acts::GenericApproachDescriptor::approachSurface(), CHECK_CLOSE_REL, Acts::GenericApproachDescriptor::containedSurfaces(), Acts::UnitConstants::e, i, Acts::Test::origin(), Acts::GenericApproachDescriptor::registerLayer(), Acts::s_onSurfaceTolerance, tgContext, Acts::Test::tolerance, and Acts::UnitConstants::um.
Acts::Test::Layers::BOOST_AUTO_TEST_CASE (LayerProperties)
Unit test for testing Layer properties.
Constructor
surfaceArray()
thickness()
isOnLayer() (delegates to the Surface 'isOnSurface()')
approachDescriptor(), retrieved as a pointer.
nextLayer()
trackingVolume()
layerType()
Definition at line 66 of file LayerTests.cpp.
View newest version in sPHENIX GitHub at line 66 of file LayerTests.cpp
References Acts::Layer::approachDescriptor(), gpos, Acts::Layer::isOnLayer(), Acts::Layer::layerType(), testing::internal::move(), Acts::Layer::nextLayer(), Acts::passive, Acts::Test::pos, rBounds, Acts::Layer::surfaceArray(), tgContext, thickness, Acts::Layer::thickness(), and Acts::Layer::trackingVolume().
Acts::Test::Layers::BOOST_AUTO_TEST_CASE (DiscLayerProperties)
Unit test for testing Layer properties.
Definition at line 85 of file DiscLayerTests.cpp.
View newest version in sPHENIX GitHub at line 85 of file DiscLayerTests.cpp
References Acts::DiscLayer::create(), and translation().
Acts::Test::Layers::BOOST_AUTO_TEST_CASE (CylinderLayerProperties)
Unit test for testing Layer properties.
Definition at line 90 of file CylinderLayerTests.cpp.
View newest version in sPHENIX GitHub at line 90 of file CylinderLayerTests.cpp
References Acts::CylinderLayer::create(), and translation().
Acts::Test::Layers::BOOST_AUTO_TEST_CASE (PlaneLayerProperties)
Unit test for testing Layer properties.
Definition at line 92 of file PlaneLayerTests.cpp.
View newest version in sPHENIX GitHub at line 92 of file PlaneLayerTests.cpp
References Acts::PlaneLayer::create(), Acts::Test::halfX, Acts::Test::halfY, and translation().
Acts::Test::Layers::BOOST_AUTO_TEST_CASE (GenericApproachNoOverstepping)
Unit test for testing GenericApproachDescriptor overstepping
for the approach estimate, there is no overstepping tolerance allowed
Definition at line 101 of file GenericApproachDescriptorTests.cpp.
View newest version in sPHENIX GitHub at line 101 of file GenericApproachDescriptorTests.cpp
References Acts::GenericApproachDescriptor::approachSurface(), CHECK_CLOSE_ABS, Acts::Test::origin(), Acts::s_epsilon, Acts::s_onSurfaceTolerance, Acts::Test::tolerance, and Acts::UnitConstants::um.
Variable Documentation
GeometryContext Acts::Test::Layers::tgContext = GeometryContext()
Definition at line 43 of file GenericApproachDescriptorTests.cpp.
View newest version in sPHENIX GitHub at line 43 of file GenericApproachDescriptorTests.cpp
Referenced by BOOST_AUTO_TEST_CASE().