Analysis Software: analysis/blob/master/pi0Efficiency/macros/gen/Fun4All_G4_Calo.C File Reference
Fun4All_G4_Calo.C File Reference
#include <GlobalVariables.C>
#include <../../pi0Efficiency.h>
#include <DisplayOn.C>
#include <G4Setup_sPHENIX.C>
#include <G4_Bbc.C>
#include <G4_CaloTrigger.C>
#include <G4_DSTReader.C>
#include <G4_Global.C>
#include <G4_HIJetReco.C>
#include <G4_Input.C>
#include <G4_Jets.C>
#include <G4_ParticleFlow.C>
#include <G4_Production.C>
#include <G4_TopoClusterReco.C>
#include <G4_Tracking.C>
#include <G4_User.C>
#include <ffamodules/FlagHandler.h>
#include <ffamodules/XploadInterface.h>
#include <fun4all/Fun4AllDstOutputManager.h>
#include <fun4all/Fun4AllOutputManager.h>
#include <fun4all/Fun4AllServer.h>
#include <phool/PHRandomSeed.h>
#include <phool/recoConsts.h>
Macros
#define MACRO_FUN4ALLG4CALO_C
Functions
int Fun4All_G4_Calo (const int nEvents=1, const string &inputFile0="g4hits.list", const string &outputFile="G4sPHENIX_calo.root", const string &outdir=".")
Macro Definition Documentation
#define MACRO_FUN4ALLG4CALO_C
Definition at line 2 of file Fun4All_G4_Calo.C.
View newest version in sPHENIX GitHub at line 2 of file Fun4All_G4_Calo.C
Function Documentation
int Fun4All_G4_Calo (const int nEvents = 1, const string & inputFile0 = "g4hits.list", const string & outputFile = "G4sPHENIX_calo.root", const string & outdir = ".")
Definition at line 39 of file Fun4All_G4_Calo.C.
View newest version in sPHENIX GitHub at line 39 of file Fun4All_G4_Calo.C
References Fun4AllDstOutputManager::AddNode(), Bbc_Reco(), Enable::CALOTRIGGER, CaloTrigger_Sim(), Enable::CEMC, Enable::CEMC_CELL, CEMC_Cells(), Enable::CEMC_CLUSTER, CEMC_Clusters(), Enable::CEMC_EVAL, Enable::CEMC_TOWER, CEMC_Towers(), filter::config, Enable::DISPLAY, DisplayOn(), DstCompress(), Enable::DSTOUT, Enable::DSTOUT_COMPRESS, Fun4AllServer::End(), G4Init(), G4Setup(), Enable::GLOBAL_FASTSIM, Global_FastSim(), Global_Reco(), Enable::GLOBAL_RECO, Enable::HCALIN_CELL, Enable::HCALIN_CLUSTER, Enable::HCALIN_TOWER, HCALInner_Cells(), HCALInner_Clusters(), HCALInner_Towers(), Enable::HCALOUT_CELL, Enable::HCALOUT_CLUSTER, Enable::HCALOUT_TOWER, HCALOuter_Cells(), HCALOuter_Clusters(), HCALOuter_Towers(), Input::HEPMC, HIJetReco(), Enable::HIJETS, InputInit(), InputManagers(), InputRegister(), recoConsts::instance(), Fun4AllServer::instance(), Enable::INTT_CELL, Intt_Cells(), Enable::INTT_CLUSTER, Intt_Clustering(), Jet_Reco(), Enable::JETS, INPUTREADHITS::listfile, Enable::MICROMEGAS_CELL, Micromegas_Cells(), Enable::MICROMEGAS_CLUSTER, Micromegas_Clustering(), Enable::MVTX_CELL, Mvtx_Cells(), Enable::MVTX_CLUSTER, Mvtx_Clustering(), out, DstOut::OutputDir, DstOut::OutputFile, Enable::PARTICLEFLOW, ParticleFlow(), Acts::Test::pos, Enable::PRODUCTION, Production_CreateOutputDir(), Input::READHITS, Fun4AllServer::registerOutputManager(), Fun4AllServer::registerSubsystem(), Fun4AllServer::run(), PHFlag::set_StringFlag(), PHFlag::set_uint64Flag(), ShowerCompress(), CDB::timestamp, Enable::TOPOCLUSTER, TopoClusterReco(), Enable::TPC_CELL, TPC_Cells(), Enable::TPC_CLUSTER, TPC_Clustering(), Tracking_Reco(), Enable::TRACKING_TRACK, TrackingInit(), PHRandomSeed::Verbosity(), Fun4AllBase::Verbosity(), and Input::VERBOSITY.