Analysis Software: OnCal Class Reference
OnCal Class Reference abstract
#include <coresoftware/blob/master/calibrations/framework/oncal/OnCal.h>
Public Member Functions
virtual ~OnCal ()
int process_event (PHCompositeNode *topNode) override
int End (PHCompositeNode *topNode) override=0
Called at the end of all processing.
virtual void CommitToPdbCal (const int value)=0
virtual int VerificationOK () const =0
virtual int CommitedToPdbCalOK () const =0
virtual void CommitNoVerify (const int)
virtual void identify (std::ostream &out=std::cout) const
virtual int BeginRun (const int)
int EndRun (const int) override
Called at the end of each run.
int Reset (PHCompositeNode *) override
Reset.
int ResetEvent (PHCompositeNode *) override
Clean up after each event.
virtual void DumpCalib () const
unsigned int AllDone () const
void AllDone (const int i)
void AddComment (const std::string &adcom)
std::string Comment () const
int GetPdbCalTables (std::vector< std::string > &vec) const
virtual int CopyTables (const int FromRun, const int ToRun, const int commit) const
virtual int CreateCalibration (const int, const std::string &, std::string &, const int)
virtual std::vector< std::string > GetLocalFileList () const
Public Member Functions inherited from SubsysReco
~SubsysReco () override
virtual int Init (PHCompositeNode *)
virtual int InitRun (PHCompositeNode *)
void Print (const std::string &="ALL") const override
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Protected Member Functions
OnCal (const std::string &Name)
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Protected Member Functions inherited from Fun4AllBase
Fun4AllBase (const std::string &name="NONAME")
Protected Attributes
std::string m_Comment
std::vector< std::string > pdbcaltables
std::vector< std::string > pdbcalclasses
std::vector< std::pair< int,
int > > bankids
std::vector< std::string > localfilelist
unsigned int alldone
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = std::numeric_limits<int>::max() - 10
}
Detailed Description
Definition at line 12 of file OnCal.h.
View newest version in sPHENIX GitHub at line 12 of file OnCal.h
Constructor & Destructor Documentation
virtual OnCal::~OnCal () inline virtual
Definition at line 15 of file OnCal.h.
View newest version in sPHENIX GitHub at line 15 of file OnCal.h
OnCal::OnCal (const std::string & Name) protected
Definition at line 11 of file OnCal.cc.
View newest version in sPHENIX GitHub at line 11 of file OnCal.cc
Member Function Documentation
void OnCal::AddComment (const std::string & adcom)
Definition at line 32 of file OnCal.cc.
View newest version in sPHENIX GitHub at line 32 of file OnCal.cc
References m_Comment.
unsigned int OnCal::AllDone () const inline
Definition at line 38 of file OnCal.h.
View newest version in sPHENIX GitHub at line 38 of file OnCal.h
References alldone.
Referenced by OnCalServer::process_event().
void OnCal::AllDone (const int i) inline
Definition at line 39 of file OnCal.h.
View newest version in sPHENIX GitHub at line 39 of file OnCal.h
References alldone, and i.
virtual int OnCal::BeginRun (const int) inline virtual
Definition at line 32 of file OnCal.h.
View newest version in sPHENIX GitHub at line 32 of file OnCal.h
std::string OnCal::Comment () const inline
Definition at line 41 of file OnCal.h.
View newest version in sPHENIX GitHub at line 41 of file OnCal.h
References m_Comment.
Referenced by OnCalServer::End().
virtual int OnCal::CommitedToPdbCalOK () const pure virtual
Referenced by OnCalServer::CreateCalibrationUpdateStatus(), and OnCalServer::End().
virtual void OnCal::CommitNoVerify (const int) inline virtual
Definition at line 28 of file OnCal.h.
View newest version in sPHENIX GitHub at line 28 of file OnCal.h
virtual void OnCal::CommitToPdbCal (const int value) pure virtual
int OnCal::CopyTables (const int FromRun, const int ToRun, const int commit) const virtual
Definition at line 46 of file OnCal.cc.
View newest version in sPHENIX GitHub at line 46 of file OnCal.cc
References PHWHERE.
Referenced by OnCalServer::CopyTables().
virtual int OnCal::CreateCalibration (const int , const std::string & , std::string & , const int) inline virtual
Definition at line 48 of file OnCal.h.
View newest version in sPHENIX GitHub at line 48 of file OnCal.h
Referenced by OnCalServer::CreateCalibration().
virtual void OnCal::DumpCalib () const inline virtual
Definition at line 36 of file OnCal.h.
View newest version in sPHENIX GitHub at line 36 of file OnCal.h
int OnCal::End (PHCompositeNode *) override pure virtual
Called at the end of all processing.
Reimplemented from SubsysReco.
Definition at line 23 of file OnCal.cc.
View newest version in sPHENIX GitHub at line 23 of file OnCal.cc
int OnCal::EndRun (const int) inline override virtual
Called at the end of each run.
Reimplemented from SubsysReco.
Definition at line 33 of file OnCal.h.
View newest version in sPHENIX GitHub at line 33 of file OnCal.h
virtual std::vector<std::string> OnCal::GetLocalFileList () const inline virtual
Definition at line 49 of file OnCal.h.
View newest version in sPHENIX GitHub at line 49 of file OnCal.h
References localfilelist.
Referenced by OnCalServer::CreateCalibrationUpdateStatus().
int OnCal::GetPdbCalTables (std::vector< std::string > & vec) const inline
Definition at line 42 of file OnCal.h.
View newest version in sPHENIX GitHub at line 42 of file OnCal.h
References pdbcaltables.
Referenced by OnCalServer::SyncCalibTimeStampsToOnCal().
virtual void OnCal::identify (std::ostream & out = std::cout) const inline virtual
Definition at line 31 of file OnCal.h.
View newest version in sPHENIX GitHub at line 31 of file OnCal.h
References Fun4AllBase::Name(), and out.
int OnCal::process_event (PHCompositeNode *) override virtual
Called for each event. This is where you do the real work.
Reimplemented from SubsysReco.
Definition at line 17 of file OnCal.cc.
View newest version in sPHENIX GitHub at line 17 of file OnCal.cc
References Fun4AllBase::Name().
int OnCal::Reset (PHCompositeNode *) inline override virtual
Reset.
Reimplemented from SubsysReco.
Definition at line 34 of file OnCal.h.
View newest version in sPHENIX GitHub at line 34 of file OnCal.h
int OnCal::ResetEvent (PHCompositeNode *) inline override virtual
Clean up after each event.
Reimplemented from SubsysReco.
Definition at line 35 of file OnCal.h.
View newest version in sPHENIX GitHub at line 35 of file OnCal.h
virtual int OnCal::VerificationOK () const pure virtual
Referenced by OnCalServer::CreateCalibrationUpdateStatus(), and OnCalServer::End().
Member Data Documentation
unsigned int OnCal::alldone protected
Definition at line 58 of file OnCal.h.
View newest version in sPHENIX GitHub at line 58 of file OnCal.h
Referenced by AllDone().
std::vector<std::pair<int, int> > OnCal::bankids protected
Definition at line 56 of file OnCal.h.
View newest version in sPHENIX GitHub at line 56 of file OnCal.h
std::vector<std::string> OnCal::localfilelist protected
Definition at line 57 of file OnCal.h.
View newest version in sPHENIX GitHub at line 57 of file OnCal.h
Referenced by GetLocalFileList().
std::string OnCal::m_Comment protected
Definition at line 53 of file OnCal.h.
View newest version in sPHENIX GitHub at line 53 of file OnCal.h
Referenced by AddComment(), and Comment().
std::vector<std::string> OnCal::pdbcalclasses protected
Definition at line 55 of file OnCal.h.
View newest version in sPHENIX GitHub at line 55 of file OnCal.h
std::vector<std::string> OnCal::pdbcaltables protected
Definition at line 54 of file OnCal.h.
View newest version in sPHENIX GitHub at line 54 of file OnCal.h
Referenced by GetPdbCalTables().
The documentation for this class was generated from the following files:
coresoftware/blob/master/calibrations/framework/oncal/OnCal.h
coresoftware/blob/master/calibrations/framework/oncal/OnCal.cc