Analysis Software: acts/blob/sPHENIX/Examples/Detectors/DD4hepDetector/src/OpenDataDetector/ODDServiceHelper.hpp File Reference
ODDServiceHelper.hpp File Reference
#include "DD4hep/DetFactoryHelper.h"
Functions
template<typename volume_t >
void buildBarrelRouting (Detector &oddd, volume_t &barrelVolume, const xml_comp_t &x_routing, const std::vector< double > &layerR)
template<typename volume_t >
void buildEndcapRouting (Detector &oddd, volume_t &endcapVolume, const xml_comp_t &x_routing, const std::vector< double > &endcapZ)
template<typename volume_t >
void buildSupportCylinder (Detector &oddd, volume_t &motherVolume, const xml_comp_t &x_mother_comp, std::vector< double > &layerR)
template<typename volume_t >
void buildCoolingRings (Detector &oddd, volume_t &motherVolume, const xml_comp_t &x_mother_comp)
Function Documentation
template<typename volume_t > void buildBarrelRouting (Detector & oddd, volume_t & barrelVolume, const xml_comp_t & x_routing, const std::vector< double > & layerR)
Helper method to build service routing for the Barrel type
Template Parameters
volume_t the Type of volume (Volume, Assembly)
Parameters
odd the top level detector
barrelVolume the volume to put the routing on
x_routing the xml description of the routing
layerR the layer radii to connect
Definition at line 25 of file ODDServiceHelper.hpp.
View newest version in sPHENIX GitHub at line 25 of file ODDServiceHelper.hpp
References BlackHoleGeometry::gap, M_PI, n, and phi.
Referenced by create_element().
template<typename volume_t > void buildCoolingRings (Detector & oddd, volume_t & motherVolume, const xml_comp_t & x_mother_comp)
Helper method to build a cyoindrical like passive structure
Template Parameters
volume_t the Type of volume (Volume, Assembly)
Parameters
odd the top level detector
endcapVolume the volume to put the routing on
x_mother_comp the xml description of teh mother component
layerR the layer radii contaienr to add the new one
Definition at line 196 of file ODDServiceHelper.hpp.
View newest version in sPHENIX GitHub at line 196 of file ODDServiceHelper.hpp
References dz, M_PI, phi, and r.
Referenced by create_element().
template<typename volume_t > void buildEndcapRouting (Detector & oddd, volume_t & endcapVolume, const xml_comp_t & x_routing, const std::vector< double > & endcapZ)
Helper method to build service routing for the Endcap type
Template Parameters
volume_t the Type of volume (Volume, Assembly)
Parameters
odd the top level detector
endcapVolume the volume to put the routing on
x_routing the xml description of the routing
endcapZ the layer z positions to connect
Definition at line 94 of file ODDServiceHelper.hpp.
View newest version in sPHENIX GitHub at line 94 of file ODDServiceHelper.hpp
References kdfinder::abs(), BlackHoleGeometry::gap, M_PI, n, phi, and r.
Referenced by create_element().
template<typename volume_t > void buildSupportCylinder (Detector & oddd, volume_t & motherVolume, const xml_comp_t & x_mother_comp, std::vector< double > & layerR)
Helper method to build a cyoindrical like passive structure
Template Parameters
volume_t the Type of volume (Volume, Assembly)
Parameters
odd the top level detector
endcapVolume the volume to put the routing on
x_mother_comp the xml description of teh mother component
layerR the layer radii contaienr to add the new one
Definition at line 160 of file ODDServiceHelper.hpp.
View newest version in sPHENIX GitHub at line 160 of file ODDServiceHelper.hpp
Referenced by create_element().