Analysis Software: Jetscape::LiquefierBase Class Reference
Jetscape::LiquefierBase Class Reference
#include <JETSCAPE/blob/main/src/framework/LiquefierBase.h>
Public Member Functions
LiquefierBase ()
~LiquefierBase ()
void add_a_droplet (Droplet droplet_in)
int get_drop_stat () const
int get_miss_stat () const
int get_neg_stat () const
Droplet get_a_droplet (const int idx) const
void check_energy_momentum_conservation (const std::vector< Parton > &pIn, std::vector< Parton > &pOut)
void filter_partons (std::vector< Parton > &pOut)
void add_hydro_sources (std::vector< Parton > &pIn, std::vector< Parton > &pOut)
const bool get_GetHydroCellSignalConnected ()
void set_GetHydroCellSignalConnected (bool m_GetHydroCellSignalConnected)
int get_dropletlist_size () const
Jetscape::real get_dropletlist_total_energy () const
virtual void smearing_kernel (Jetscape::real tau, Jetscape::real x, Jetscape::real y, Jetscape::real eta, const Droplet drop_i, std::array< Jetscape::real, 4 > &jmu) const
void get_source (Jetscape::real tau, Jetscape::real x, Jetscape::real y, Jetscape::real eta, std::array< Jetscape::real, 4 > &jmu) const
virtual void Clear ()
Public Attributes
sigslot::signal5< double,
double, double, double,
std::unique_ptr< FluidCellInfo >
&, sigslot::multi_threaded_local > GetHydroCellSignal
Core signal to receive information from the medium.
Private Attributes
std::vector< Droplet > dropletlist
bool GetHydroCellSignalConnected
const int drop_stat
const int miss_stat
const int neg_stat
const Jetscape::real hydro_source_abs_err
Detailed Description
Definition at line 48 of file LiquefierBase.h.
View newest version in sPHENIX GitHub at line 48 of file LiquefierBase.h
Constructor & Destructor Documentation
Jetscape::LiquefierBase::LiquefierBase ()
Definition at line 20 of file LiquefierBase.cc.
View newest version in sPHENIX GitHub at line 20 of file LiquefierBase.cc
References GetHydroCellSignalConnected.
Jetscape::LiquefierBase::~LiquefierBase () inline
Definition at line 59 of file LiquefierBase.h.
View newest version in sPHENIX GitHub at line 59 of file LiquefierBase.h
References Clear().
Member Function Documentation
void Jetscape::LiquefierBase::add_a_droplet (Droplet droplet_in) inline
Definition at line 61 of file LiquefierBase.h.
View newest version in sPHENIX GitHub at line 61 of file LiquefierBase.h
References dropletlist.
Referenced by add_hydro_sources(), and TEST().
void Jetscape::LiquefierBase::add_hydro_sources (std::vector< Parton > & pIn, std::vector< Parton > & pOut)
Definition at line 146 of file LiquefierBase.cc.
View newest version in sPHENIX GitHub at line 146 of file LiquefierBase.cc
References add_a_droplet(), check_energy_momentum_conservation(), drop_stat, filter_partons(), hydro_source_abs_err, miss_stat, neg_stat, Jetscape::FourVector::t(), Jetscape::FourVector::x(), Jetscape::FourVector::y(), and Jetscape::FourVector::z().
Referenced by TEST().
void Jetscape::LiquefierBase::check_energy_momentum_conservation (const std::vector< Parton > & pIn, std::vector< Parton > & pOut)
This function check the energy momentum conservation at the vertex If vertex does not conserve energy and momentum, a p_missing will be added to the pOut list
Definition at line 50 of file LiquefierBase.cc.
View newest version in sPHENIX GitHub at line 50 of file LiquefierBase.cc
References hydro_source_abs_err, JSWARN, miss_stat, Jetscape::FourVector::t(), Jetscape::FourVector::x(), Jetscape::FourVector::y(), and Jetscape::FourVector::z().
Referenced by add_hydro_sources(), and TEST().
void Jetscape::LiquefierBase::Clear (void) virtual
Definition at line 219 of file LiquefierBase.cc.
View newest version in sPHENIX GitHub at line 219 of file LiquefierBase.cc
References dropletlist.
Referenced by TEST(), and ~LiquefierBase().
void Jetscape::LiquefierBase::filter_partons (std::vector< Parton > & pOut)
Definition at line 89 of file LiquefierBase.cc.
View newest version in sPHENIX GitHub at line 89 of file LiquefierBase.cc
References drop_stat, GetHydroCellSignal, miss_stat, and neg_stat.
Referenced by add_hydro_sources(), and TEST().
Droplet Jetscape::LiquefierBase::get_a_droplet (const int idx) const inline
Definition at line 67 of file LiquefierBase.h.
View newest version in sPHENIX GitHub at line 67 of file LiquefierBase.h
References dropletlist.
Referenced by TEST().
int Jetscape::LiquefierBase::get_drop_stat () const inline
Definition at line 63 of file LiquefierBase.h.
View newest version in sPHENIX GitHub at line 63 of file LiquefierBase.h
References drop_stat.
Referenced by TEST().
int Jetscape::LiquefierBase::get_dropletlist_size () const inline
Definition at line 88 of file LiquefierBase.h.
View newest version in sPHENIX GitHub at line 88 of file LiquefierBase.h
References dropletlist.
Referenced by TEST().
Jetscape::real Jetscape::LiquefierBase::get_dropletlist_total_energy () const
Definition at line 221 of file LiquefierBase.cc.
View newest version in sPHENIX GitHub at line 221 of file LiquefierBase.cc
References dropletlist, and total_E.
const bool Jetscape::LiquefierBase::get_GetHydroCellSignalConnected () inline
Definition at line 80 of file LiquefierBase.h.
View newest version in sPHENIX GitHub at line 80 of file LiquefierBase.h
References GetHydroCellSignalConnected.
int Jetscape::LiquefierBase::get_miss_stat () const inline
Definition at line 64 of file LiquefierBase.h.
View newest version in sPHENIX GitHub at line 64 of file LiquefierBase.h
References miss_stat.
int Jetscape::LiquefierBase::get_neg_stat () const inline
Definition at line 65 of file LiquefierBase.h.
View newest version in sPHENIX GitHub at line 65 of file LiquefierBase.h
References neg_stat.
void Jetscape::LiquefierBase::get_source (Jetscape::real tau, Jetscape::real x, Jetscape::real y, Jetscape::real eta, std::array< Jetscape::real, 4 > & jmu) const
Definition at line 26 of file LiquefierBase.cc.
View newest version in sPHENIX GitHub at line 26 of file LiquefierBase.cc
References dropletlist, i, and smearing_kernel().
void Jetscape::LiquefierBase::set_GetHydroCellSignalConnected (bool m_GetHydroCellSignalConnected) inline
Definition at line 84 of file LiquefierBase.h.
View newest version in sPHENIX GitHub at line 84 of file LiquefierBase.h
References GetHydroCellSignalConnected.
virtual void Jetscape::LiquefierBase::smearing_kernel (Jetscape::real tau, Jetscape::real x, Jetscape::real y, Jetscape::real eta, const Droplet drop_i, std::array< Jetscape::real, 4 > & jmu) const inline virtual
Reimplemented in Jetscape::CausalLiquefier.
Definition at line 92 of file LiquefierBase.h.
View newest version in sPHENIX GitHub at line 92 of file LiquefierBase.h
Referenced by get_source().
Member Data Documentation
const int Jetscape::LiquefierBase::drop_stat private
Definition at line 52 of file LiquefierBase.h.
View newest version in sPHENIX GitHub at line 52 of file LiquefierBase.h
Referenced by add_hydro_sources(), filter_partons(), and get_drop_stat().
std::vector<Droplet> Jetscape::LiquefierBase::dropletlist private
Definition at line 50 of file LiquefierBase.h.
View newest version in sPHENIX GitHub at line 50 of file LiquefierBase.h
Referenced by add_a_droplet(), Clear(), get_a_droplet(), get_dropletlist_size(), get_dropletlist_total_energy(), and get_source().
sigslot::signal5<double, double, double, double, std::unique_ptr<FluidCellInfo> &, sigslot::multi_threaded_local> Jetscape::LiquefierBase::GetHydroCellSignal
Core signal to receive information from the medium.
Definition at line 78 of file LiquefierBase.h.
View newest version in sPHENIX GitHub at line 78 of file LiquefierBase.h
Referenced by filter_partons().
bool Jetscape::LiquefierBase::GetHydroCellSignalConnected private
Definition at line 51 of file LiquefierBase.h.
View newest version in sPHENIX GitHub at line 51 of file LiquefierBase.h
Referenced by get_GetHydroCellSignalConnected(), LiquefierBase(), and set_GetHydroCellSignalConnected().
const Jetscape::real Jetscape::LiquefierBase::hydro_source_abs_err private
Definition at line 55 of file LiquefierBase.h.
View newest version in sPHENIX GitHub at line 55 of file LiquefierBase.h
Referenced by add_hydro_sources(), and check_energy_momentum_conservation().
const int Jetscape::LiquefierBase::miss_stat private
Definition at line 53 of file LiquefierBase.h.
View newest version in sPHENIX GitHub at line 53 of file LiquefierBase.h
Referenced by add_hydro_sources(), check_energy_momentum_conservation(), filter_partons(), and get_miss_stat().
const int Jetscape::LiquefierBase::neg_stat private
Definition at line 54 of file LiquefierBase.h.
View newest version in sPHENIX GitHub at line 54 of file LiquefierBase.h
Referenced by add_hydro_sources(), filter_partons(), and get_neg_stat().
The documentation for this class was generated from the following files:
JETSCAPE/blob/main/src/framework/LiquefierBase.h
JETSCAPE/blob/main/src/framework/LiquefierBase.cc