Analysis Software: Jetscape::Parton Class Reference
Jetscape::Parton Class Reference
#include <JETSCAPE/blob/main/src/framework/JetScapeParticles.h>
Public Member Functions
virtual void set_mean_form_time ()
virtual void set_form_time (double form_time)
virtual double form_time ()
virtual const double mean_form_time ()
virtual void reset_p (double px, double py, double pz)
virtual void set_color (unsigned int col)
sets the color of the parton
virtual void set_anti_color (unsigned int acol)
sets anti-color of the parton
virtual void set_max_color (unsigned int col)
sets the color of the parton
virtual void set_min_color (unsigned int col)
sets the color of the parton
virtual void set_min_anti_color (unsigned int acol)
sets anti-color of the parton
bool isPhoton (int pid)
Parton (int label, int id, int stat, const FourVector &p, const FourVector &x)
Parton (int label, int id, int stat, double pt, double eta, double phi, double e, double *x=0)
Parton (const Parton &srp)
Parton & operator= (Parton &c)
Parton & operator= (const Parton &c)
const double t ()
void set_t (double t)
virtuality of particle, : rescales the spatial component
unsigned int color ()
returns the color of the parton
unsigned int anti_color ()
returns the anti-color of the parton
unsigned int max_color ()
unsigned int min_color ()
unsigned int min_anti_color ()
const int edgeid () const
void set_edgeid (const int id)
void set_shower (const shared_ptr< PartonShower > pShower)
void set_shower (const weak_ptr< PartonShower > pShower)
const weak_ptr< PartonShower > shower () const
std::vector< Parton > parents ()
Public Member Functions inherited from Jetscape::JetScapeParticleBase
void reset_momentum (const double px, const double py, const double pz, const double e)
void reset_momentum (const FourVector &p)
fjcore::PseudoJet GetPseudoJet () const
No implicit cast to PseudoJet is allowed, provide a conversion.
JetScapeParticleBase ()
JetScapeParticleBase (int label, int id, int stat, const FourVector &p, const FourVector &x)
JetScapeParticleBase (int label, int id, int stat, double pt, double eta, double phi, double e, double *x=0)
JetScapeParticleBase (int label, int id, int stat, const FourVector &p, const FourVector &x, double mass)
JetScapeParticleBase (const JetScapeParticleBase &srp)
virtual ~JetScapeParticleBase ()
void clear ()
void set_label (int label)
void set_id (int id)
void set_stat (int stat)
void set_x (double x[4])
void init_jet_v ()
void set_jet_v (double v[4])
void set_jet_v (FourVector j)
bool SetController (string controller="")
void UnsetController ()
const int pid () const
const int pstat () const
const int plabel () const
const double time () const
std::vector< JetScapeParticleBase > parents ()
const FourVector p_in () const
const FourVector & x_in () const
const FourVector & jet_v () const
const double restmass ()
const double p (int i)
double pl ()
const double nu ()
const double t_max ()
virtual JetScapeParticleBase & operator= (JetScapeParticleBase &c)
virtual JetScapeParticleBase & operator= (const JetScapeParticleBase &c)
string GetController () const
bool GetControlled () const
Protected Member Functions
void initialize_form_time ()
void CheckAcceptability (int id)
restrict to a few pids only.
Protected Member Functions inherited from Jetscape::JetScapeParticleBase
void set_restmass (double mass_input)
shouldn't be called from the outside, needs to be consistent with PID
Protected Attributes
double mean_form_time_
Mean formation time.
double form_time_
event by event formation time
unsigned int Color_
Large Nc color of parton.
unsigned int antiColor_
Large Nc anti-color of parton.
unsigned int MaxColor_
the running maximum color
unsigned int MinColor_
color of the parent
unsigned int MinAntiColor_
anti-color of the parent
weak_ptr< PartonShower > pShower_
shower that this parton belongs to
int edgeid_
Position in the shower graph.
Protected Attributes inherited from Jetscape::JetScapeParticleBase
int pid_
particle id
int pstat_
status of particle
int plabel_
the line number in the event record
double mass_
rest mass of the particle
FourVector x_in_
position of particle
FourVector jet_v_
jet four vector, without gamma factor (so not really a four vector)
bool controlled_ = false
check whether a module claimed responsibility of this particle
string controller_ = ""
Additional Inherited Members
Static Public Attributes inherited from Jetscape::JetScapeParticleBase
static Pythia8::Pythia InternalHelperPythia
Detailed Description
Definition at line 310 of file JetScapeParticles.h.
View newest version in sPHENIX GitHub at line 310 of file JetScapeParticles.h
Constructor & Destructor Documentation
Jetscape::Parton::Parton (int label, int id, int stat, const FourVector & p, const FourVector & x)
Definition at line 254 of file JetScapeParticles.cc.
View newest version in sPHENIX GitHub at line 254 of file JetScapeParticles.cc
References assert, CheckAcceptability(), initialize_form_time(), Jetscape::JetScapeParticleBase::InternalHelperPythia, isPhoton(), set_anti_color(), set_color(), set_edgeid(), set_max_color(), set_min_anti_color(), set_min_color(), and set_shower().
Jetscape::Parton::Parton (int label, int id, int stat, double pt, double eta, double phi, double e, double * x = 0)
Definition at line 271 of file JetScapeParticles.cc.
View newest version in sPHENIX GitHub at line 271 of file JetScapeParticles.cc
References assert, CheckAcceptability(), initialize_form_time(), Jetscape::JetScapeParticleBase::InternalHelperPythia, isPhoton(), set_anti_color(), set_color(), set_edgeid(), set_max_color(), set_min_anti_color(), set_min_color(), and set_shower().
Jetscape::Parton::Parton (const Parton & srp)
Definition at line 238 of file JetScapeParticles.cc.
View newest version in sPHENIX GitHub at line 238 of file JetScapeParticles.cc
References antiColor_, Color_, edgeid(), form_time_, MaxColor_, MinAntiColor_, MinColor_, set_edgeid(), set_shower(), and shower().
Member Function Documentation
unsigned int Jetscape::Parton::anti_color ()
returns the anti-color of the parton
Definition at line 435 of file JetScapeParticles.cc.
View newest version in sPHENIX GitHub at line 435 of file JetScapeParticles.cc
References antiColor_.
void Jetscape::Parton::CheckAcceptability (int id) protected
restrict to a few pids only.
Definition at line 289 of file JetScapeParticles.cc.
View newest version in sPHENIX GitHub at line 289 of file JetScapeParticles.cc
References train_ambiguity_solver::id, and JSWARN.
Referenced by Parton().
unsigned int Jetscape::Parton::color ()
returns the color of the parton
Definition at line 433 of file JetScapeParticles.cc.
View newest version in sPHENIX GitHub at line 433 of file JetScapeParticles.cc
References Color_.
const int Jetscape::Parton::edgeid () const
Definition at line 405 of file JetScapeParticles.cc.
View newest version in sPHENIX GitHub at line 405 of file JetScapeParticles.cc
References edgeid_.
Referenced by operator=(), and Parton().
double Jetscape::Parton::form_time () virtual
Definition at line 347 of file JetScapeParticles.cc.
View newest version in sPHENIX GitHub at line 347 of file JetScapeParticles.cc
References form_time_.
Referenced by set_form_time(), and set_t().
void Jetscape::Parton::initialize_form_time () protected
Definition at line 345 of file JetScapeParticles.cc.
View newest version in sPHENIX GitHub at line 345 of file JetScapeParticles.cc
References form_time_.
Referenced by Parton().
bool Jetscape::Parton::isPhoton (int pid)
Definition at line 443 of file JetScapeParticles.cc.
View newest version in sPHENIX GitHub at line 443 of file JetScapeParticles.cc
References Jetscape::photonid.
Referenced by Parton().
unsigned int Jetscape::Parton::max_color ()
Definition at line 441 of file JetScapeParticles.cc.
View newest version in sPHENIX GitHub at line 441 of file JetScapeParticles.cc
References MaxColor_.
const double Jetscape::Parton::mean_form_time () virtual
Definition at line 349 of file JetScapeParticles.cc.
View newest version in sPHENIX GitHub at line 349 of file JetScapeParticles.cc
References mean_form_time_.
unsigned int Jetscape::Parton::min_anti_color ()
Definition at line 439 of file JetScapeParticles.cc.
View newest version in sPHENIX GitHub at line 439 of file JetScapeParticles.cc
References MinAntiColor_.
unsigned int Jetscape::Parton::min_color ()
Definition at line 437 of file JetScapeParticles.cc.
View newest version in sPHENIX GitHub at line 437 of file JetScapeParticles.cc
References MinColor_.
Parton & Jetscape::Parton::operator= (Parton & c)
Definition at line 317 of file JetScapeParticles.cc.
View newest version in sPHENIX GitHub at line 317 of file JetScapeParticles.cc
References antiColor_, Color_, edgeid(), form_time_, Jetscape::JetScapeParticleBase::operator=(), set_edgeid(), set_shower(), and shower().
Referenced by Jetscape::Photon::operator=().
Parton & Jetscape::Parton::operator= (const Parton & c)
Definition at line 328 of file JetScapeParticles.cc.
View newest version in sPHENIX GitHub at line 328 of file JetScapeParticles.cc
References antiColor_, Color_, edgeid(), form_time_, Jetscape::JetScapeParticleBase::operator=(), set_edgeid(), set_shower(), and shower().
std::vector< Parton > Jetscape::Parton::parents ()
Definition at line 420 of file JetScapeParticles.cc.
View newest version in sPHENIX GitHub at line 420 of file JetScapeParticles.cc
References edgeid_, node::in_edges_begin(), node::in_edges_end(), pShower_, and fixGDML::root.
void Jetscape::Parton::reset_p (double px, double py, double pz) virtual
Definition at line 391 of file JetScapeParticles.cc.
View newest version in sPHENIX GitHub at line 391 of file JetScapeParticles.cc
References Acts::UnitConstants::e, and Jetscape::JetScapeParticleBase::reset_momentum().
void Jetscape::Parton::set_anti_color (unsigned int acol) virtual
sets anti-color of the parton
Definition at line 397 of file JetScapeParticles.cc.
View newest version in sPHENIX GitHub at line 397 of file JetScapeParticles.cc
References antiColor_.
Referenced by Parton(), and HybridHadronization::stringprep().
void Jetscape::Parton::set_color (unsigned int col) virtual
sets the color of the parton
Definition at line 395 of file JetScapeParticles.cc.
View newest version in sPHENIX GitHub at line 395 of file JetScapeParticles.cc
References col, and Color_.
Referenced by Parton(), and HybridHadronization::stringprep().
void Jetscape::Parton::set_edgeid (const int id)
Definition at line 407 of file JetScapeParticles.cc.
View newest version in sPHENIX GitHub at line 407 of file JetScapeParticles.cc
References edgeid_, and train_ambiguity_solver::id.
Referenced by operator=(), and Parton().
void Jetscape::Parton::set_form_time (double form_time) virtual
Definition at line 343 of file JetScapeParticles.cc.
View newest version in sPHENIX GitHub at line 343 of file JetScapeParticles.cc
References form_time(), and form_time_.
void Jetscape::Parton::set_max_color (unsigned int col) virtual
sets the color of the parton
Definition at line 399 of file JetScapeParticles.cc.
View newest version in sPHENIX GitHub at line 399 of file JetScapeParticles.cc
References col, and MaxColor_.
Referenced by Parton().
void Jetscape::Parton::set_mean_form_time () virtual
Definition at line 339 of file JetScapeParticles.cc.
View newest version in sPHENIX GitHub at line 339 of file JetScapeParticles.cc
References Acts::UnitConstants::e, Jetscape::fmToGeVinv, mean_form_time_, Jetscape::rounding_error, and t().
void Jetscape::Parton::set_min_anti_color (unsigned int acol) virtual
sets anti-color of the parton
Definition at line 403 of file JetScapeParticles.cc.
View newest version in sPHENIX GitHub at line 403 of file JetScapeParticles.cc
References MinAntiColor_.
Referenced by Parton().
void Jetscape::Parton::set_min_color (unsigned int col) virtual
sets the color of the parton
Definition at line 401 of file JetScapeParticles.cc.
View newest version in sPHENIX GitHub at line 401 of file JetScapeParticles.cc
References col, and MinColor_.
Referenced by Parton().
void Jetscape::Parton::set_shower (const shared_ptr< PartonShower > pShower)
Definition at line 409 of file JetScapeParticles.cc.
View newest version in sPHENIX GitHub at line 409 of file JetScapeParticles.cc
References pShower_.
Referenced by operator=(), and Parton().
void Jetscape::Parton::set_shower (const weak_ptr< PartonShower > pShower)
Definition at line 414 of file JetScapeParticles.cc.
View newest version in sPHENIX GitHub at line 414 of file JetScapeParticles.cc
References pShower_.
void Jetscape::Parton::set_t (double t)
virtuality of particle, : rescales the spatial component
Definition at line 366 of file JetScapeParticles.cc.
View newest version in sPHENIX GitHub at line 366 of file JetScapeParticles.cc
References Jetscape::FourVector::comp(), Acts::UnitConstants::e, form_time(), Jetscape::JetScapeParticleBase::jet_v_, Jetscape::JetScapeParticleBase::reset_momentum(), and Jetscape::JetScapeParticleBase::restmass().
const weak_ptr< PartonShower > Jetscape::Parton::shower () const
Definition at line 418 of file JetScapeParticles.cc.
View newest version in sPHENIX GitHub at line 418 of file JetScapeParticles.cc
References pShower_.
Referenced by Martini::isCoherent(), operator=(), and Parton().
const double Jetscape::Parton::t ()
: Fix
Definition at line 351 of file JetScapeParticles.cc.
View newest version in sPHENIX GitHub at line 351 of file JetScapeParticles.cc
References Acts::UnitConstants::e, and Jetscape::JetScapeParticleBase::restmass().
Referenced by set_mean_form_time().
Member Data Documentation
unsigned int Jetscape::Parton::antiColor_ protected
Large Nc anti-color of parton.
Definition at line 362 of file JetScapeParticles.h.
View newest version in sPHENIX GitHub at line 362 of file JetScapeParticles.h
Referenced by anti_color(), operator=(), Parton(), and set_anti_color().
unsigned int Jetscape::Parton::Color_ protected
Large Nc color of parton.
Definition at line 361 of file JetScapeParticles.h.
View newest version in sPHENIX GitHub at line 361 of file JetScapeParticles.h
Referenced by color(), operator=(), Parton(), and set_color().
int Jetscape::Parton::edgeid_ protected
Position in the shower graph.
Definition at line 368 of file JetScapeParticles.h.
View newest version in sPHENIX GitHub at line 368 of file JetScapeParticles.h
Referenced by edgeid(), parents(), and set_edgeid().
double Jetscape::Parton::form_time_ protected
event by event formation time
Definition at line 360 of file JetScapeParticles.h.
View newest version in sPHENIX GitHub at line 360 of file JetScapeParticles.h
Referenced by form_time(), initialize_form_time(), operator=(), Parton(), and set_form_time().
unsigned int Jetscape::Parton::MaxColor_ protected
the running maximum color
Definition at line 363 of file JetScapeParticles.h.
View newest version in sPHENIX GitHub at line 363 of file JetScapeParticles.h
Referenced by max_color(), Parton(), and set_max_color().
double Jetscape::Parton::mean_form_time_ protected
Mean formation time.
Definition at line 359 of file JetScapeParticles.h.
View newest version in sPHENIX GitHub at line 359 of file JetScapeParticles.h
Referenced by mean_form_time(), and set_mean_form_time().
unsigned int Jetscape::Parton::MinAntiColor_ protected
anti-color of the parent
Definition at line 365 of file JetScapeParticles.h.
View newest version in sPHENIX GitHub at line 365 of file JetScapeParticles.h
Referenced by min_anti_color(), Parton(), and set_min_anti_color().
unsigned int Jetscape::Parton::MinColor_ protected
color of the parent
Definition at line 364 of file JetScapeParticles.h.
View newest version in sPHENIX GitHub at line 364 of file JetScapeParticles.h
Referenced by min_color(), Parton(), and set_min_color().
weak_ptr<PartonShower> Jetscape::Parton::pShower_ protected
shower that this parton belongs to
Definition at line 367 of file JetScapeParticles.h.
View newest version in sPHENIX GitHub at line 367 of file JetScapeParticles.h
Referenced by parents(), set_shower(), and shower().
The documentation for this class was generated from the following files:
JETSCAPE/blob/main/src/framework/JetScapeParticles.h
JETSCAPE/blob/main/src/framework/JetScapeParticles.cc