Analysis Software: ClusHitsVerbose Class Reference
ClusHitsVerbose Class Reference
#include <coresoftware/blob/master/offline/packages/trackbase/ClusHitsVerbose.h>
Public Types
using BinData = std::pair< int, int >
using Vector = std::vector< BinData >
using Map = std::map< TrkrDefs::cluskey, std::array< Vector, 4 >>
using VecInt = std::vector< int >
using PairVector = std::pair< VecInt, VecInt >
Public Member Functions
void Reset () override
Clear Event.
virtual bool hasClusKey (TrkrDefs::cluskey) const
virtual Vector & phiBins (TrkrDefs::cluskey)
virtual Vector & zBins (TrkrDefs::cluskey)
virtual Vector & phiCutBins (TrkrDefs::cluskey)
virtual Vector & zCutBins (TrkrDefs::cluskey)
virtual Map & getMap ()
virtual PairVector phiBins_pvecIE (TrkrDefs::cluskey)
virtual PairVector phiCutBins_pvecIE (TrkrDefs::cluskey)
virtual PairVector zBins_pvecIE (TrkrDefs::cluskey)
virtual PairVector zCutBins_pvecIE (TrkrDefs::cluskey)
virtual void addPhiHit (int, int)
virtual void addZHit (int, int)
virtual void addPhiCutHit (int, int)
virtual void addZCutHit (int, int)
virtual void push_hits (TrkrDefs::cluskey)
void identify (std::ostream &os=std::cout) const override
Public Member Functions inherited from PHObject
PHObject ()
ctor
~PHObject () override
dtor
virtual PHObject * CloneMe () const
Virtual copy constructor.
virtual PHObject * clone () const final
PHObject * Clone (const char *newname="") const final
void Copy (TObject &object) const final
virtual int isValid () const
isValid returns non zero if object contains vailid data
virtual int Integrate () const
virtual int Integrate (PHObject *)
virtual void CopyFrom (const PHObject *obj)
Protected Member Functions
ClusHitsVerbose ()=default
Detailed Description
Definition at line 12 of file ClusHitsVerbose.h.
View newest version in sPHENIX GitHub at line 12 of file ClusHitsVerbose.h
Member Typedef Documentation
using ClusHitsVerbose::BinData = std::pair<int,int>
Definition at line 15 of file ClusHitsVerbose.h.
View newest version in sPHENIX GitHub at line 15 of file ClusHitsVerbose.h
using ClusHitsVerbose::Map = std::map<TrkrDefs::cluskey, std::array<Vector,4>>
Definition at line 17 of file ClusHitsVerbose.h.
View newest version in sPHENIX GitHub at line 17 of file ClusHitsVerbose.h
using ClusHitsVerbose::PairVector = std::pair<VecInt,VecInt>
Definition at line 31 of file ClusHitsVerbose.h.
View newest version in sPHENIX GitHub at line 31 of file ClusHitsVerbose.h
using ClusHitsVerbose::VecInt = std::vector<int>
Definition at line 30 of file ClusHitsVerbose.h.
View newest version in sPHENIX GitHub at line 30 of file ClusHitsVerbose.h
using ClusHitsVerbose::Vector = std::vector<BinData>
Definition at line 16 of file ClusHitsVerbose.h.
View newest version in sPHENIX GitHub at line 16 of file ClusHitsVerbose.h
Constructor & Destructor Documentation
ClusHitsVerbose::ClusHitsVerbose () protected default
Member Function Documentation
virtual void ClusHitsVerbose::addPhiCutHit (int , int) inline virtual
Reimplemented in ClusHitsVerbosev1.
Definition at line 38 of file ClusHitsVerbose.h.
View newest version in sPHENIX GitHub at line 38 of file ClusHitsVerbose.h
virtual void ClusHitsVerbose::addPhiHit (int , int) inline virtual
Reimplemented in ClusHitsVerbosev1.
Definition at line 36 of file ClusHitsVerbose.h.
View newest version in sPHENIX GitHub at line 36 of file ClusHitsVerbose.h
Referenced by MvtxClusterizer::ClusterMvtx().
virtual void ClusHitsVerbose::addZCutHit (int , int) inline virtual
Reimplemented in ClusHitsVerbosev1.
Definition at line 39 of file ClusHitsVerbose.h.
View newest version in sPHENIX GitHub at line 39 of file ClusHitsVerbose.h
virtual void ClusHitsVerbose::addZHit (int , int) inline virtual
Reimplemented in ClusHitsVerbosev1.
Definition at line 37 of file ClusHitsVerbose.h.
View newest version in sPHENIX GitHub at line 37 of file ClusHitsVerbose.h
Referenced by MvtxClusterizer::ClusterMvtx().
ClusHitsVerbose::Map & ClusHitsVerbose::getMap () virtual
Reimplemented in ClusHitsVerbosev1.
Definition at line 30 of file ClusHitsVerbose.cc.
View newest version in sPHENIX GitHub at line 30 of file ClusHitsVerbose.cc
virtual bool ClusHitsVerbose::hasClusKey (TrkrDefs::cluskey) const inline virtual
Reimplemented in ClusHitsVerbosev1.
Definition at line 21 of file ClusHitsVerbose.h.
View newest version in sPHENIX GitHub at line 21 of file ClusHitsVerbose.h
void ClusHitsVerbose::identify (std::ostream & os = std::cout) const inline override virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from PHObject.
Reimplemented in ClusHitsVerbosev1.
Definition at line 43 of file ClusHitsVerbose.h.
View newest version in sPHENIX GitHub at line 43 of file ClusHitsVerbose.h
References os.
ClusHitsVerbose::Vector & ClusHitsVerbose::phiBins (TrkrDefs::cluskey) virtual
Reimplemented in ClusHitsVerbosev1.
Definition at line 10 of file ClusHitsVerbose.cc.
View newest version in sPHENIX GitHub at line 10 of file ClusHitsVerbose.cc
ClusHitsVerbose::PairVector ClusHitsVerbose::phiBins_pvecIE (TrkrDefs::cluskey) virtual
Reimplemented in ClusHitsVerbosev1.
Definition at line 35 of file ClusHitsVerbose.cc.
View newest version in sPHENIX GitHub at line 35 of file ClusHitsVerbose.cc
ClusHitsVerbose::Vector & ClusHitsVerbose::phiCutBins (TrkrDefs::cluskey) virtual
Reimplemented in ClusHitsVerbosev1.
Definition at line 20 of file ClusHitsVerbose.cc.
View newest version in sPHENIX GitHub at line 20 of file ClusHitsVerbose.cc
ClusHitsVerbose::PairVector ClusHitsVerbose::phiCutBins_pvecIE (TrkrDefs::cluskey) virtual
Reimplemented in ClusHitsVerbosev1.
Definition at line 39 of file ClusHitsVerbose.cc.
View newest version in sPHENIX GitHub at line 39 of file ClusHitsVerbose.cc
virtual void ClusHitsVerbose::push_hits (TrkrDefs::cluskey) inline virtual
Reimplemented in ClusHitsVerbosev1.
Definition at line 40 of file ClusHitsVerbose.h.
View newest version in sPHENIX GitHub at line 40 of file ClusHitsVerbose.h
Referenced by MvtxClusterizer::ClusterMvtx().
void ClusHitsVerbose::Reset () inline override virtual
Clear Event.
Reimplemented from PHObject.
Reimplemented in ClusHitsVerbosev1.
Definition at line 19 of file ClusHitsVerbose.h.
View newest version in sPHENIX GitHub at line 19 of file ClusHitsVerbose.h
ClusHitsVerbose::Vector & ClusHitsVerbose::zBins (TrkrDefs::cluskey) virtual
Reimplemented in ClusHitsVerbosev1.
Definition at line 15 of file ClusHitsVerbose.cc.
View newest version in sPHENIX GitHub at line 15 of file ClusHitsVerbose.cc
ClusHitsVerbose::PairVector ClusHitsVerbose::zBins_pvecIE (TrkrDefs::cluskey) virtual
Reimplemented in ClusHitsVerbosev1.
Definition at line 43 of file ClusHitsVerbose.cc.
View newest version in sPHENIX GitHub at line 43 of file ClusHitsVerbose.cc
ClusHitsVerbose::Vector & ClusHitsVerbose::zCutBins (TrkrDefs::cluskey) virtual
Reimplemented in ClusHitsVerbosev1.
Definition at line 25 of file ClusHitsVerbose.cc.
View newest version in sPHENIX GitHub at line 25 of file ClusHitsVerbose.cc
ClusHitsVerbose::PairVector ClusHitsVerbose::zCutBins_pvecIE (TrkrDefs::cluskey) virtual
Reimplemented in ClusHitsVerbosev1.
Definition at line 47 of file ClusHitsVerbose.cc.
View newest version in sPHENIX GitHub at line 47 of file ClusHitsVerbose.cc
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/trackbase/ClusHitsVerbose.h
coresoftware/blob/master/offline/packages/trackbase/ClusHitsVerbose.cc