Analysis Software: EventNumberCheck Class Reference
EventNumberCheck Class Reference
#include <coresoftware/blob/master/offline/framework/ffarawmodules/EventNumberCheck.h>
Public Member Functions
EventNumberCheck (const std::string &name="EventNumberCheck")
~EventNumberCheck () override
int Init (PHCompositeNode *topNode) override
int process_event (PHCompositeNode *topNode) override
void MyPrdfNode (const std::string &name)
Public Member Functions inherited from SubsysReco
~SubsysReco () override
virtual int End (PHCompositeNode *)
Called at the end of all processing.
virtual int EndRun (const int)
Called at the end of each run.
virtual int InitRun (PHCompositeNode *)
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
void Print (const std::string &="ALL") const override
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Private Member Functions
void CheckFem (int nw)
Private Attributes
Packet * plist [10000]
int previous_event_clkdiff {0}
std::set< int > m_EventSeen
std::string m_MyPrdfNode {"PRDF"}
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = std::numeric_limits<int>::max() - 10
}
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Detailed Description
Definition at line 16 of file EventNumberCheck.h.
View newest version in sPHENIX GitHub at line 16 of file EventNumberCheck.h
Constructor & Destructor Documentation
EventNumberCheck::EventNumberCheck (const std::string & name = "EventNumberCheck")
Definition at line 24 of file EventNumberCheck.cc.
View newest version in sPHENIX GitHub at line 24 of file EventNumberCheck.cc
EventNumberCheck::~EventNumberCheck () inline override
Definition at line 21 of file EventNumberCheck.h.
View newest version in sPHENIX GitHub at line 21 of file EventNumberCheck.h
Member Function Documentation
void EventNumberCheck::CheckFem (int nw) private
Definition at line 57 of file EventNumberCheck.cc.
View newest version in sPHENIX GitHub at line 57 of file EventNumberCheck.cc
References Packet::getIdentifier(), i, Packet::iValue(), j, plist, previous_event_clkdiff, and Fun4AllBase::Verbosity().
int EventNumberCheck::Init (PHCompositeNode *) override virtual
Called during initialization. Typically this is where you can book histograms, and e.g. register them to Fun4AllServer (so they can be output to file using Fun4AllServer::dumpHistos() method).
Reimplemented from SubsysReco.
Definition at line 30 of file EventNumberCheck.cc.
View newest version in sPHENIX GitHub at line 30 of file EventNumberCheck.cc
References Fun4AllReturnCodes::EVENT_OK.
void EventNumberCheck::MyPrdfNode (const std::string & name) inline
Definition at line 29 of file EventNumberCheck.h.
View newest version in sPHENIX GitHub at line 29 of file EventNumberCheck.h
References m_MyPrdfNode, and perf_headwind::name.
int EventNumberCheck::process_event (PHCompositeNode *) override virtual
Called for each event. This is where you do the real work.
Reimplemented from SubsysReco.
Definition at line 36 of file EventNumberCheck.cc.
View newest version in sPHENIX GitHub at line 36 of file EventNumberCheck.cc
References Fun4AllReturnCodes::EVENT_OK, Fun4AllServer::EventNumber(), Event::getEvtSequence(), Event::getPacketList(), Event::identify(), Fun4AllServer::instance(), m_EventSeen, m_MyPrdfNode, and plist.
Member Data Documentation
std::set<int> EventNumberCheck::m_EventSeen private
Definition at line 35 of file EventNumberCheck.h.
View newest version in sPHENIX GitHub at line 35 of file EventNumberCheck.h
Referenced by process_event().
std::string EventNumberCheck::m_MyPrdfNode {"PRDF"} private
Definition at line 36 of file EventNumberCheck.h.
View newest version in sPHENIX GitHub at line 36 of file EventNumberCheck.h
Referenced by MyPrdfNode(), and process_event().
Packet* EventNumberCheck::plist[10000] private
Definition at line 33 of file EventNumberCheck.h.
View newest version in sPHENIX GitHub at line 33 of file EventNumberCheck.h
Referenced by CheckFem(), and process_event().
int EventNumberCheck::previous_event_clkdiff {0} private
Definition at line 34 of file EventNumberCheck.h.
View newest version in sPHENIX GitHub at line 34 of file EventNumberCheck.h
Referenced by CheckFem().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/framework/ffarawmodules/EventNumberCheck.h
coresoftware/blob/master/offline/framework/ffarawmodules/EventNumberCheck.cc