Analysis Software: analysis/blob/master/EICAnalysis/macros/leptoquarks_analysis/event_topology_reco.C File Reference
event_topology_reco.C File Reference
#include "tau_commons.h"
Functions
double Average (vector< double > v)
int event_topology_reco ()
Function Documentation
double Average (vector< double > v)
Plot missing trasnverse energy and other event-wise observables
Written by nils..nosp@m.feeg.nosp@m.e@sto.nosp@m.nybr.nosp@m.ook.e.nosp@m.du & sean..nosp@m.jeff.nosp@m.as@st.nosp@m.onyb.nosp@m.rook..nosp@m.edu
Definition at line 10 of file event_topology_reco.C.
View newest version in sPHENIX GitHub at line 10 of file event_topology_reco.C
References i, and sum().
int event_topology_reco ()
Definition at line 19 of file event_topology_reco.C.
View newest version in sPHENIX GitHub at line 19 of file event_topology_reco.C
References KFPMath::b, delta_phi(), f, file, Acts::UnitConstants::g, i, j, k, nevents(), seed, t, and parse_cmake_options::type.