Analysis Software: TruthJetInput Class Reference
TruthJetInput Class Reference
#include <coresoftware/blob/master/simulation/g4simulation/g4jets/TruthJetInput.h>
Public Member Functions
TruthJetInput (Jet::SRC input)
~TruthJetInput () override
void add_embedding_flag (const int embed_stream_id)
void identify (std::ostream &os=std::cout) override
Jet::SRC get_src () override
std::vector< Jet * > get_input (PHCompositeNode *topNode) override
void set_eta_range (float eta_min, float eta_max)
Public Member Functions inherited from JetInput
virtual ~JetInput ()
virtual int Verbosity () const
virtual void Verbosity (int i)
Private Member Functions
bool use_embed_stream ()
Private Attributes
Jet::SRC m_Input = Jet::VOID
float m_EtaMin = -4.
float m_EtaMax = 4.
std::vector< int > m_EmbedID
Additional Inherited Members
Protected Member Functions inherited from JetInput
JetInput ()
Detailed Description
Definition at line 12 of file TruthJetInput.h.
View newest version in sPHENIX GitHub at line 12 of file TruthJetInput.h
Constructor & Destructor Documentation
TruthJetInput::TruthJetInput (Jet::SRC input)
Definition at line 21 of file TruthJetInput.cc.
View newest version in sPHENIX GitHub at line 21 of file TruthJetInput.cc
TruthJetInput::~TruthJetInput () inline override
Definition at line 16 of file TruthJetInput.h.
View newest version in sPHENIX GitHub at line 16 of file TruthJetInput.h
Member Function Documentation
void TruthJetInput::add_embedding_flag (const int embed_stream_id) inline
by default, TruthJetInput process all truth primary particle. However, it can be configured to read only one or more embedded stream via add_embedding_flag() It can be useful for reconstruct truth jet for embedded pythia jets only, etc. Call add_embedding_flag() multiple times to add multiple embed stream
Definition at line 22 of file TruthJetInput.h.
View newest version in sPHENIX GitHub at line 22 of file TruthJetInput.h
References m_EmbedID.
Referenced by Fun4All_Condor(), HIJetReco(), and run_macro().
std::vector< Jet * > TruthJetInput::get_input (PHCompositeNode * topNode) override virtual
Reimplemented from JetInput.
Definition at line 40 of file TruthJetInput.cc.
View newest version in sPHENIX GitHub at line 40 of file TruthJetInput.cc
References eta, PHG4Particle::get_e(), PHG4Particle::get_pid(), PHG4Particle::get_px(), PHG4Particle::get_py(), PHG4Particle::get_pz(), PHG4Particle::get_track_id(), PHG4TruthInfoContainer::GetPrimaryParticleRange(), Jet::insert_comp(), PHG4TruthInfoContainer::isEmbeded(), m_EmbedID, m_EtaMax, m_EtaMin, Jet::PARTICLE, PHWHERE, Jet::set_e(), Jet::set_px(), Jet::set_py(), Jet::set_pz(), use_embed_stream(), and JetInput::Verbosity().
Jet::SRC TruthJetInput::get_src () inline override virtual
Reimplemented from JetInput.
Definition at line 29 of file TruthJetInput.h.
View newest version in sPHENIX GitHub at line 29 of file TruthJetInput.h
References m_Input.
void TruthJetInput::identify (std::ostream & os = std::cout) override virtual
Reimplemented from JetInput.
Definition at line 26 of file TruthJetInput.cc.
View newest version in sPHENIX GitHub at line 26 of file TruthJetInput.cc
References it, m_EmbedID, and use_embed_stream().
void TruthJetInput::set_eta_range (float eta_min, float eta_max) inline
Definition at line 33 of file TruthJetInput.h.
View newest version in sPHENIX GitHub at line 33 of file TruthJetInput.h
References myAnalysis::eta_max, myAnalysis::eta_min, m_EtaMax, and m_EtaMin.
bool TruthJetInput::use_embed_stream () inline private
Definition at line 48 of file TruthJetInput.h.
View newest version in sPHENIX GitHub at line 48 of file TruthJetInput.h
References m_EmbedID.
Referenced by get_input(), and identify().
Member Data Documentation
std::vector<int> TruthJetInput::m_EmbedID private
if empty: process all primary particles if non-empty: only process primary particles in the selected embed stream.
Definition at line 46 of file TruthJetInput.h.
View newest version in sPHENIX GitHub at line 46 of file TruthJetInput.h
Referenced by add_embedding_flag(), get_input(), identify(), and use_embed_stream().
float TruthJetInput::m_EtaMax = 4. private
Definition at line 42 of file TruthJetInput.h.
View newest version in sPHENIX GitHub at line 42 of file TruthJetInput.h
Referenced by get_input(), and set_eta_range().
float TruthJetInput::m_EtaMin = -4. private
Definition at line 41 of file TruthJetInput.h.
View newest version in sPHENIX GitHub at line 41 of file TruthJetInput.h
Referenced by get_input(), and set_eta_range().
Jet::SRC TruthJetInput::m_Input = Jet::VOID private
Definition at line 40 of file TruthJetInput.h.
View newest version in sPHENIX GitHub at line 40 of file TruthJetInput.h
Referenced by get_src().
The documentation for this class was generated from the following files:
coresoftware/blob/master/simulation/g4simulation/g4jets/TruthJetInput.h
coresoftware/blob/master/simulation/g4simulation/g4jets/TruthJetInput.cc