Analysis Software: acts/blob/sPHENIX/Tests/UnitTests/Core/Material/AverageMaterialsTests.cpp File Reference
AverageMaterialsTests.cpp File Reference
#include <boost/test/unit_test.hpp>
#include "Acts/Material/Material.hpp"
#include "Acts/Material/MaterialSlab.hpp"
#include "Acts/Material/detail/AverageMaterials.hpp"
#include "Acts/Tests/CommonHelpers/FloatComparisons.hpp"
#include "Acts/Tests/CommonHelpers/PredefinedMaterials.hpp"
#include <cmath>
#include <limits>
Functions
BOOST_AUTO_TEST_CASE (CombineSlabsVacuum)
BOOST_AUTO_TEST_CASE (CombineSlabsPercent)
BOOST_AUTO_TEST_CASE (CombineSlabsUnit)
BOOST_AUTO_TEST_CASE (CombineSlabsPercentZeroVacuum)
BOOST_AUTO_TEST_CASE (CombineSlabsUnitZeroVacuum)
BOOST_AUTO_TEST_CASE (CombineSlabsPercentUnit)
BOOST_AUTO_TEST_CASE (CombineSlabsUnitZero)
BOOST_AUTO_TEST_CASE (CombineSlabsEqualThicknessVacuum)
BOOST_AUTO_TEST_CASE (CombineSlabs)
Function Documentation
BOOST_AUTO_TEST_CASE (CombineSlabsVacuum)
Definition at line 40 of file AverageMaterialsTests.cpp.
View newest version in sPHENIX GitHub at line 40 of file AverageMaterialsTests.cpp
References Acts::detail::combineSlabs().
BOOST_AUTO_TEST_CASE (CombineSlabsPercent)
Definition at line 59 of file AverageMaterialsTests.cpp.
View newest version in sPHENIX GitHub at line 59 of file AverageMaterialsTests.cpp
References Acts::detail::combineSlabs().
BOOST_AUTO_TEST_CASE (CombineSlabsUnit)
Definition at line 70 of file AverageMaterialsTests.cpp.
View newest version in sPHENIX GitHub at line 70 of file AverageMaterialsTests.cpp
References Acts::detail::combineSlabs().
BOOST_AUTO_TEST_CASE (CombineSlabsPercentZeroVacuum)
Definition at line 83 of file AverageMaterialsTests.cpp.
View newest version in sPHENIX GitHub at line 83 of file AverageMaterialsTests.cpp
References Acts::detail::combineSlabs().
BOOST_AUTO_TEST_CASE (CombineSlabsUnitZeroVacuum)
Definition at line 103 of file AverageMaterialsTests.cpp.
View newest version in sPHENIX GitHub at line 103 of file AverageMaterialsTests.cpp
References Acts::detail::combineSlabs().
BOOST_AUTO_TEST_CASE (CombineSlabsPercentUnit)
Definition at line 125 of file AverageMaterialsTests.cpp.
View newest version in sPHENIX GitHub at line 125 of file AverageMaterialsTests.cpp
References Acts::detail::combineSlabs().
BOOST_AUTO_TEST_CASE (CombineSlabsUnitZero)
Definition at line 152 of file AverageMaterialsTests.cpp.
View newest version in sPHENIX GitHub at line 152 of file AverageMaterialsTests.cpp
References Acts::detail::combineSlabs(), and KFPMath::zero().
BOOST_AUTO_TEST_CASE (CombineSlabsEqualThicknessVacuum)
Definition at line 175 of file AverageMaterialsTests.cpp.
View newest version in sPHENIX GitHub at line 175 of file AverageMaterialsTests.cpp
References CHECK_CLOSE_REL, Acts::detail::combineSlabs(), eps, f, and Acts::Test::makeSilicon().
BOOST_AUTO_TEST_CASE (CombineSlabs)
Definition at line 218 of file AverageMaterialsTests.cpp.
View newest version in sPHENIX GitHub at line 218 of file AverageMaterialsTests.cpp
References Acts::detail::combineSlabs(), f, and Acts::Material::fromMolarDensity().