Analysis Software: GlobalVertexFastSimReco Class Reference
GlobalVertexFastSimReco Class Reference
simple truth vertex smearing algorithm
#include <coresoftware/blob/master/simulation/g4simulation/g4vertex/GlobalVertexFastSimReco.h>
Public Member Functions
GlobalVertexFastSimReco (const std::string &name="GlobalVertexFastSimReco")
~GlobalVertexFastSimReco () override
int InitRun (PHCompositeNode *topNode) override
int process_event (PHCompositeNode *topNode) override
void set_x_smearing (const float x_smear)
void set_y_smearing (const float y_smear)
void set_z_smearing (const float z_smear)
void set_t_smearing (const float t_smear)
Public Member Functions inherited from SubsysReco
~SubsysReco () override
virtual int End (PHCompositeNode *)
Called at the end of all processing.
virtual int EndRun (const int)
Called at the end of each run.
virtual int Init (PHCompositeNode *)
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
void Print (const std::string &="ALL") const override
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Private Member Functions
int CreateNodes (PHCompositeNode *topNode)
Private Attributes
float _x_smear = std::numeric_limits<float>::quiet_NaN()
float _y_smear = std::numeric_limits<float>::quiet_NaN()
float _z_smear = std::numeric_limits<float>::quiet_NaN()
float _t_smear = std::numeric_limits<float>::quiet_NaN()
gsl_rng * RandomGenerator = nullptr
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = std::numeric_limits<int>::max() - 10
}
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Detailed Description
simple truth vertex smearing algorithm
Definition at line 25 of file GlobalVertexFastSimReco.h.
View newest version in sPHENIX GitHub at line 25 of file GlobalVertexFastSimReco.h
Constructor & Destructor Documentation
GlobalVertexFastSimReco::GlobalVertexFastSimReco (const std::string & name = "GlobalVertexFastSimReco")
Definition at line 30 of file GlobalVertexFastSimReco.cc.
View newest version in sPHENIX GitHub at line 30 of file GlobalVertexFastSimReco.cc
References RandomGenerator.
GlobalVertexFastSimReco::~GlobalVertexFastSimReco () override
Definition at line 36 of file GlobalVertexFastSimReco.cc.
View newest version in sPHENIX GitHub at line 36 of file GlobalVertexFastSimReco.cc
References RandomGenerator.
Member Function Documentation
int GlobalVertexFastSimReco::CreateNodes (PHCompositeNode * topNode) private
Definition at line 140 of file GlobalVertexFastSimReco.cc.
View newest version in sPHENIX GitHub at line 140 of file GlobalVertexFastSimReco.cc
References Fun4AllReturnCodes::ABORTRUN, PHCompositeNode::addNode(), Fun4AllReturnCodes::EVENT_OK, PHNodeIterator::findFirst(), and PHWHERE.
Referenced by InitRun().
int GlobalVertexFastSimReco::InitRun (PHCompositeNode *) override virtual
Called for first event when run number is known. Typically this is where you may want to fetch data from database, because you know the run number.
Reimplemented from SubsysReco.
Definition at line 41 of file GlobalVertexFastSimReco.cc.
View newest version in sPHENIX GitHub at line 41 of file GlobalVertexFastSimReco.cc
References _t_smear, _x_smear, _y_smear, _z_smear, CreateNodes(), gsl_rng_set(), PHWHERE, RandomGenerator, seed, and Fun4AllBase::Verbosity().
int GlobalVertexFastSimReco::process_event (PHCompositeNode *) override virtual
Called for each event. This is where you do the real work.
Reimplemented from SubsysReco.
Definition at line 69 of file GlobalVertexFastSimReco.cc.
View newest version in sPHENIX GitHub at line 69 of file GlobalVertexFastSimReco.cc
References _t_smear, _x_smear, _y_smear, _z_smear, Fun4AllReturnCodes::EVENT_OK, PHG4VtxPoint::get_t(), PHG4VtxPoint::get_x(), PHG4VtxPoint::get_y(), PHG4VtxPoint::get_z(), PHG4TruthInfoContainer::GetPrimaryVertexIndex(), PHG4TruthInfoContainer::GetPrimaryVtx(), i, GlobalVertexMap::insert(), j, PHWHERE, RandomGenerator, GlobalVertex::set_error(), GlobalVertex::set_t(), GlobalVertex::set_t_err(), GlobalVertex::set_x(), GlobalVertex::set_y(), GlobalVertex::set_z(), GlobalVertex::SMEARED, GlobalVertex::TRUTH, and Fun4AllBase::Verbosity().
void GlobalVertexFastSimReco::set_t_smearing (const float t_smear) inline
Definition at line 37 of file GlobalVertexFastSimReco.h.
View newest version in sPHENIX GitHub at line 37 of file GlobalVertexFastSimReco.h
References _t_smear.
Referenced by Global_FastSim().
void GlobalVertexFastSimReco::set_x_smearing (const float x_smear) inline
Definition at line 34 of file GlobalVertexFastSimReco.h.
View newest version in sPHENIX GitHub at line 34 of file GlobalVertexFastSimReco.h
References _x_smear.
Referenced by Global_FastSim().
void GlobalVertexFastSimReco::set_y_smearing (const float y_smear) inline
Definition at line 35 of file GlobalVertexFastSimReco.h.
View newest version in sPHENIX GitHub at line 35 of file GlobalVertexFastSimReco.h
References _y_smear.
Referenced by Global_FastSim().
void GlobalVertexFastSimReco::set_z_smearing (const float z_smear) inline
Definition at line 36 of file GlobalVertexFastSimReco.h.
View newest version in sPHENIX GitHub at line 36 of file GlobalVertexFastSimReco.h
References _z_smear.
Referenced by Global_FastSim().
Member Data Documentation
float GlobalVertexFastSimReco::_t_smear = std::numeric_limits<float>::quiet_NaN() private
Definition at line 45 of file GlobalVertexFastSimReco.h.
View newest version in sPHENIX GitHub at line 45 of file GlobalVertexFastSimReco.h
Referenced by InitRun(), process_event(), and set_t_smearing().
float GlobalVertexFastSimReco::_x_smear = std::numeric_limits<float>::quiet_NaN() private
Definition at line 42 of file GlobalVertexFastSimReco.h.
View newest version in sPHENIX GitHub at line 42 of file GlobalVertexFastSimReco.h
Referenced by InitRun(), process_event(), and set_x_smearing().
float GlobalVertexFastSimReco::_y_smear = std::numeric_limits<float>::quiet_NaN() private
Definition at line 43 of file GlobalVertexFastSimReco.h.
View newest version in sPHENIX GitHub at line 43 of file GlobalVertexFastSimReco.h
Referenced by InitRun(), process_event(), and set_y_smearing().
float GlobalVertexFastSimReco::_z_smear = std::numeric_limits<float>::quiet_NaN() private
Definition at line 44 of file GlobalVertexFastSimReco.h.
View newest version in sPHENIX GitHub at line 44 of file GlobalVertexFastSimReco.h
Referenced by InitRun(), process_event(), and set_z_smearing().
gsl_rng* GlobalVertexFastSimReco::RandomGenerator = nullptr private
Definition at line 46 of file GlobalVertexFastSimReco.h.
View newest version in sPHENIX GitHub at line 46 of file GlobalVertexFastSimReco.h
Referenced by GlobalVertexFastSimReco(), InitRun(), process_event(), and ~GlobalVertexFastSimReco().
The documentation for this class was generated from the following files:
coresoftware/blob/master/simulation/g4simulation/g4vertex/GlobalVertexFastSimReco.h
coresoftware/blob/master/simulation/g4simulation/g4vertex/GlobalVertexFastSimReco.cc