Analysis Software: Acts::PerigeeSurface Class Reference
Acts::PerigeeSurface Class Reference
#include <acts/blob/sPHENIX/Core/include/Acts/Surfaces/PerigeeSurface.hpp>
Public Member Functions
~PerigeeSurface () override=default
Destructor - defaulted.
PerigeeSurface ()=delete
Default Constructor - deleted.
PerigeeSurface & operator= (const PerigeeSurface &other)
SurfaceType type () const final
Return the surface type.
std::string name () const final
Return properly formatted class name for screen output */.
std::ostream & toStream (const GeometryContext &gctx, std::ostream &sl) const final
Polyhedron polyhedronRepresentation (const GeometryContext &gctx, size_t lseg) const final
Public Member Functions inherited from Acts::LineSurface
~LineSurface () override=default
LineSurface ()=delete
LineSurface & operator= (const LineSurface &other)
Vector3 normal (const GeometryContext &gctx, const Vector2 &lposition) const final
Vector3 binningPosition (const GeometryContext &gctx, BinningValue bValue) const final
RotationMatrix3 referenceFrame (const GeometryContext &gctx, const Vector3 &position, const Vector3 &direction) const final
BoundToFreeMatrix boundToFreeJacobian (const GeometryContext &gctx, const BoundVector &boundParams) const final
FreeToPathMatrix freeToPathDerivative (const GeometryContext &gctx, const FreeVector &parameters) const final
Vector3 localToGlobal (const GeometryContext &gctx, const Vector2 &lposition, const Vector3 &direction) const final
Result< Vector2 > globalToLocal (const GeometryContext &gctx, const Vector3 &position, const Vector3 &direction, double tolerance=s_onSurfaceTolerance) const final
SurfaceMultiIntersection intersect (const GeometryContext &gctx, const Vector3 &position, const Vector3 &direction, const BoundaryCheck &bcheck=false, ActsScalar tolerance=s_onSurfaceTolerance) const final
double pathCorrection (const GeometryContext &gctx, const Vector3 &position, const Vector3 &direction) const override
const SurfaceBounds & bounds () const final
This method returns the bounds of the surface by reference.
AlignmentToPathMatrix alignmentToPathDerivative (const GeometryContext &gctx, const FreeVector &parameters) const final
ActsMatrix< 2, 3 > localCartesianToBoundLocalDerivative (const GeometryContext &gctx, const Vector3 &position) const final
Vector3 lineDirection (const GeometryContext &gctx) const
Public Member Functions inherited from Acts::Surface
virtual ~Surface ()
std::shared_ptr< Surface > getSharedPtr ()
std::shared_ptr< const Surface > getSharedPtr () const
Surface & operator= (const Surface &other)
virtual bool operator== (const Surface &other) const
virtual bool operator!= (const Surface &sf) const
virtual const Transform3 & transform (const GeometryContext &gctx) const
virtual Vector3 center (const GeometryContext &gctx) const
virtual Vector3 normal (const GeometryContext &gctx, const Vector3 &position) const
virtual Vector3 normal (const GeometryContext &gctx) const
const DetectorElementBase * associatedDetectorElement () const
const Layer * associatedLayer () const
void associateLayer (const Layer &lay)
const ISurfaceMaterial * surfaceMaterial () const
const std::shared_ptr< const
ISurfaceMaterial > & surfaceMaterialSharedPtr () const
void assignDetectorElement (const DetectorElementBase &detelement)
void assignSurfaceMaterial (std::shared_ptr< const ISurfaceMaterial > material)
bool isOnSurface (const GeometryContext &gctx, const Vector3 &position, const Vector3 &direction, const BoundaryCheck &bcheck=true) const
virtual bool insideBounds (const Vector2 &lposition, const BoundaryCheck &bcheck=true) const
virtual FreeToBoundMatrix freeToBoundJacobian (const GeometryContext &gctx, const FreeVector &parameters) const
std::string toString (const GeometryContext &gctx) const
AlignmentToBoundMatrix alignmentToBoundDerivative (const GeometryContext &gctx, const FreeVector &parameters, const FreeVector &pathDerivative) const
Public Member Functions inherited from Acts::GeometryObject
GeometryObject ()=default
Defaulted constructor.
GeometryObject (const GeometryObject &)=default
Defaulted copy constructor.
GeometryObject (const GeometryIdentifier &geometryId)
GeometryObject & operator= (const GeometryObject &geometryId)
const GeometryIdentifier & geometryId () const
virtual double binningPositionValue (const GeometryContext &gctx, BinningValue bValue) const
void assignGeometryId (const GeometryIdentifier &geometryId)
Protected Member Functions
PerigeeSurface (const Vector3 &gp)
PerigeeSurface (const Transform3 &transform)
PerigeeSurface (const PerigeeSurface &other)
PerigeeSurface (const GeometryContext &gctx, const PerigeeSurface &other, const Transform3 &shift)
Protected Member Functions inherited from Acts::LineSurface
LineSurface (const Transform3 &transform, double radius, double halez)
LineSurface (const Transform3 &transform, std::shared_ptr< const LineBounds > lbounds=nullptr)
LineSurface (std::shared_ptr< const LineBounds > lbounds, const DetectorElementBase &detelement)
LineSurface (const LineSurface &other)
LineSurface (const GeometryContext &gctx, const LineSurface &other, const Transform3 &shift)
Protected Member Functions inherited from Acts::Surface
Surface (const Transform3 &transform=Transform3::Identity())
Surface (const Surface &other)
Surface (const DetectorElementBase &detelement)
Surface (const GeometryContext &gctx, const Surface &other, const Transform3 &shift)
Private Attributes
friend Surface
Additional Inherited Members
Public Types inherited from Acts::Surface
enum SurfaceType {
Cone = 0, Cylinder = 1, Disc = 2, Perigee = 3,
Plane = 4, Straw = 5, Curvilinear = 6, Other = 7
}
Static Public Member Functions inherited from Acts::Surface
template<class T , typename... Args>
static std::shared_ptr< T > makeShared (Args &&...args)
Static Public Attributes inherited from Acts::Surface
static std::array< std::string,
SurfaceType::Other > s_surfaceTypeNames
Helper strings for screen output.
Protected Attributes inherited from Acts::LineSurface
std::shared_ptr< const LineBounds > m_bounds
bounds (shared)
Detailed Description
Class describing the Line to which the Perigee refers to. The Surface axis is fixed to be the z-axis of the Tracking frame. It inherits from StraingLineSurface.
Definition at line 30 of file PerigeeSurface.hpp.
View newest version in sPHENIX GitHub at line 30 of file PerigeeSurface.hpp
Constructor & Destructor Documentation
Acts::PerigeeSurface::PerigeeSurface (const Vector3 & gp) protected
Constructor from GlobalPosition
Parameters
gp position where the perigee is centered
Definition at line 18 of file PerigeeSurface.cpp.
View newest version in sPHENIX GitHub at line 18 of file PerigeeSurface.cpp
Acts::PerigeeSurface::PerigeeSurface (const Transform3 & transform) protected
Constructor with a Transform - needed for tilt
Parameters
transform is the transform for position and tilting
Definition at line 21 of file PerigeeSurface.cpp.
View newest version in sPHENIX GitHub at line 21 of file PerigeeSurface.cpp
Acts::PerigeeSurface::PerigeeSurface (const PerigeeSurface & other) protected
Copy constructor
Parameters
other is the source surface to be copied
Definition at line 24 of file PerigeeSurface.cpp.
View newest version in sPHENIX GitHub at line 24 of file PerigeeSurface.cpp
Acts::PerigeeSurface::PerigeeSurface (const GeometryContext & gctx, const PerigeeSurface & other, const Transform3 & shift) protected
Copy constructor - with shift
Parameters
gctx The current geometry context object, e.g. alignment
other is the source cone surface
shift is the additional transform applied after copying
Definition at line 27 of file PerigeeSurface.cpp.
View newest version in sPHENIX GitHub at line 27 of file PerigeeSurface.cpp
Acts::PerigeeSurface::~PerigeeSurface () override default
Destructor - defaulted.
Acts::PerigeeSurface::PerigeeSurface () delete
Default Constructor - deleted.
Member Function Documentation
std::string Acts::PerigeeSurface::name () const final virtual
Return properly formatted class name for screen output */.
Reimplemented from Acts::LineSurface.
Definition at line 44 of file PerigeeSurface.cpp.
View newest version in sPHENIX GitHub at line 44 of file PerigeeSurface.cpp
Acts::PerigeeSurface & Acts::PerigeeSurface::operator= (const PerigeeSurface & other)
Assignment operator
Parameters
other is the source surface to be assigned
Definition at line 32 of file PerigeeSurface.cpp.
View newest version in sPHENIX GitHub at line 32 of file PerigeeSurface.cpp
References Acts::LineSurface::operator=().
Acts::Polyhedron Acts::PerigeeSurface::polyhedronRepresentation (const GeometryContext & gctx, size_t lseg) const final virtual
Return a Polyhedron for the surfaces
Parameters
gctx The current geometry context object, e.g. alignment
lseg is ignored for a perigee
Note
ignored
Returns
A list of vertices and a face/facett description of it
Implements Acts::Surface.
Definition at line 60 of file PerigeeSurface.cpp.
View newest version in sPHENIX GitHub at line 60 of file PerigeeSurface.cpp
References left(), Acts::Test::transform, and ActsExamples::HepMC3Event::vertices().
std::ostream & Acts::PerigeeSurface::toStream (const GeometryContext & gctx, std::ostream & sl) const final virtual
Output Method for std::ostream
Parameters
gctx The current geometry context object, e.g. alignment
sl is the ostream to be dumped into
Returns
ostreamn object which was streamed into
Reimplemented from Acts::Surface.
Definition at line 48 of file PerigeeSurface.cpp.
View newest version in sPHENIX GitHub at line 48 of file PerigeeSurface.cpp
Acts::Surface::SurfaceType Acts::PerigeeSurface::type () const final virtual
Return the surface type.
Implements Acts::Surface.
Definition at line 40 of file PerigeeSurface.cpp.
View newest version in sPHENIX GitHub at line 40 of file PerigeeSurface.cpp
References Acts::Surface::Perigee.
Member Data Documentation
friend Acts::PerigeeSurface::Surface private
Definition at line 32 of file PerigeeSurface.hpp.
View newest version in sPHENIX GitHub at line 32 of file PerigeeSurface.hpp
The documentation for this class was generated from the following files:
acts/blob/sPHENIX/Core/include/Acts/Surfaces/PerigeeSurface.hpp
acts/blob/sPHENIX/Core/src/Surfaces/PerigeeSurface.cpp