Analysis Software: Acts::JsonMaterialDecorator Class Reference
Acts::JsonMaterialDecorator Class Reference
Material decorator from Json format.
#include <acts/blob/sPHENIX/Plugins/Json/include/Acts/Plugins/Json/JsonMaterialDecorator.hpp>
Public Types
using SurfaceMaterialMap = std::map< GeometryIdentifier, std::shared_ptr< const ISurfaceMaterial >>
using VolumeMaterialMap = std::map< GeometryIdentifier, std::shared_ptr< const IVolumeMaterial >>
Public Member Functions
JsonMaterialDecorator (const MaterialMapJsonConverter::Config &rConfig, const std::string &jFileName, Acts::Logging::Level level, bool clearSurfaceMaterial=true, bool clearVolumeMaterial=true)
void decorate (Surface &surface) const final
void decorate (TrackingVolume &volume) const final
Public Member Functions inherited from Acts::IMaterialDecorator
virtual ~IMaterialDecorator ()=default
Virtual Destructor.
Private Member Functions
const Logger & logger () const
Private Attributes
MaterialMapJsonConverter::Config m_readerConfig
SurfaceMaterialMap m_surfaceMaterialMap
VolumeMaterialMap m_volumeMaterialMap
bool m_clearSurfaceMaterial {true}
bool m_clearVolumeMaterial {true}
std::unique_ptr< const Logger > m_logger
Detailed Description
Material decorator from Json format.
This reads in material maps for surfaces and volumes from a json file
Definition at line 30 of file JsonMaterialDecorator.hpp.
View newest version in sPHENIX GitHub at line 30 of file JsonMaterialDecorator.hpp
Member Typedef Documentation
using Acts::JsonMaterialDecorator::SurfaceMaterialMap = std::map<GeometryIdentifier, std::shared_ptr<const ISurfaceMaterial>>
Definition at line 33 of file JsonMaterialDecorator.hpp.
View newest version in sPHENIX GitHub at line 33 of file JsonMaterialDecorator.hpp
using Acts::JsonMaterialDecorator::VolumeMaterialMap = std::map<GeometryIdentifier, std::shared_ptr<const IVolumeMaterial>>
Definition at line 36 of file JsonMaterialDecorator.hpp.
View newest version in sPHENIX GitHub at line 36 of file JsonMaterialDecorator.hpp
Constructor & Destructor Documentation
Acts::JsonMaterialDecorator::JsonMaterialDecorator (const MaterialMapJsonConverter::Config & rConfig, const std::string & jFileName, Acts::Logging::Level level, bool clearSurfaceMaterial = true, bool clearVolumeMaterial = true)
Definition at line 21 of file JsonMaterialDecorator.cpp.
View newest version in sPHENIX GitHub at line 21 of file JsonMaterialDecorator.cpp
References Acts::getDefaultLogger().
Member Function Documentation
void Acts::JsonMaterialDecorator::decorate (Surface & surface) const final virtual
Decorate a surface
Parameters
surface the non-cost surface that is decorated
Implements Acts::IMaterialDecorator.
Definition at line 54 of file JsonMaterialDecorator.cpp.
View newest version in sPHENIX GitHub at line 54 of file JsonMaterialDecorator.cpp
References Acts::ACTS_VERBOSE(), Acts::Surface::assignSurfaceMaterial(), Acts::GeometryObject::geometryId(), m_clearSurfaceMaterial, and m_surfaceMaterialMap.
void Acts::JsonMaterialDecorator::decorate (TrackingVolume & volume) const final virtual
Decorate a TrackingVolume
Parameters
volume the non-cost volume that is decorated
Implements Acts::IMaterialDecorator.
Definition at line 72 of file JsonMaterialDecorator.cpp.
View newest version in sPHENIX GitHub at line 72 of file JsonMaterialDecorator.cpp
References Acts::ACTS_VERBOSE(), Acts::TrackingVolume::assignVolumeMaterial(), Acts::GeometryObject::geometryId(), m_clearVolumeMaterial, and m_volumeMaterialMap.
const Logger& Acts::JsonMaterialDecorator::logger () const inline private
Definition at line 64 of file JsonMaterialDecorator.hpp.
View newest version in sPHENIX GitHub at line 64 of file JsonMaterialDecorator.hpp
References m_logger.
Member Data Documentation
bool Acts::JsonMaterialDecorator::m_clearSurfaceMaterial {true} private
Definition at line 59 of file JsonMaterialDecorator.hpp.
View newest version in sPHENIX GitHub at line 59 of file JsonMaterialDecorator.hpp
Referenced by decorate().
bool Acts::JsonMaterialDecorator::m_clearVolumeMaterial {true} private
Definition at line 60 of file JsonMaterialDecorator.hpp.
View newest version in sPHENIX GitHub at line 60 of file JsonMaterialDecorator.hpp
Referenced by decorate().
std::unique_ptr<const Logger> Acts::JsonMaterialDecorator::m_logger private
Definition at line 62 of file JsonMaterialDecorator.hpp.
View newest version in sPHENIX GitHub at line 62 of file JsonMaterialDecorator.hpp
Referenced by logger().
MaterialMapJsonConverter::Config Acts::JsonMaterialDecorator::m_readerConfig private
Definition at line 55 of file JsonMaterialDecorator.hpp.
View newest version in sPHENIX GitHub at line 55 of file JsonMaterialDecorator.hpp
SurfaceMaterialMap Acts::JsonMaterialDecorator::m_surfaceMaterialMap private
Definition at line 56 of file JsonMaterialDecorator.hpp.
View newest version in sPHENIX GitHub at line 56 of file JsonMaterialDecorator.hpp
Referenced by decorate().
VolumeMaterialMap Acts::JsonMaterialDecorator::m_volumeMaterialMap private
Definition at line 57 of file JsonMaterialDecorator.hpp.
View newest version in sPHENIX GitHub at line 57 of file JsonMaterialDecorator.hpp
Referenced by decorate().
The documentation for this class was generated from the following files:
acts/blob/sPHENIX/Plugins/Json/include/Acts/Plugins/Json/JsonMaterialDecorator.hpp
acts/blob/sPHENIX/Plugins/Json/src/JsonMaterialDecorator.cpp