Analysis Software: Acts::detail::FacesHelper Struct Reference
Acts::detail::FacesHelper Struct Reference
Helper for writing out faces for polyhedron representation.
#include <acts/blob/sPHENIX/Core/include/Acts/Surfaces/detail/FacesHelper.hpp>
Public Types
using FaceVector = std::vector< Polyhedron::FaceType >
Static Public Member Functions
static std::pair< FaceVector,
FaceVector > convexFaceMesh (const std::vector< Vector3 > &vertices, bool centerLast=false)
This method words for all convex type surface setups It includes:
static std::pair< FaceVector,
FaceVector > cylindricalFaceMesh (const std::vector< Vector3 > &vertices, bool fullTwoPi=true)
This method works for all concentric type surface setups It includes :
Detailed Description
Helper for writing out faces for polyhedron representation.
Definition at line 23 of file FacesHelper.hpp.
View newest version in sPHENIX GitHub at line 23 of file FacesHelper.hpp
Member Typedef Documentation
using Acts::detail::FacesHelper::FaceVector = std::vector<Polyhedron::FaceType>
Definition at line 24 of file FacesHelper.hpp.
View newest version in sPHENIX GitHub at line 24 of file FacesHelper.hpp
Member Function Documentation
static std::pair<FaceVector, FaceVector> Acts::detail::FacesHelper::convexFaceMesh (const std::vector< Vector3 > & vertices, bool centerLast = false) inline static
This method words for all convex type surface setups It includes:
Rectangle / Triangle / Polygon Full disc, ellipse, half ring
Parameters
vertices The vector of vertices
centerLast Boolean indicator if the center is given for a better triangulation method as last element of the vector
Triangular mesh construction
Definition at line 34 of file FacesHelper.hpp.
View newest version in sPHENIX GitHub at line 34 of file FacesHelper.hpp
References it, and offset.
Referenced by Acts::EventDataView3D::drawCovarianceCartesian(), and Acts::PlaneSurface::polyhedronRepresentation().
static std::pair<FaceVector, FaceVector> Acts::detail::FacesHelper::cylindricalFaceMesh (const std::vector< Vector3 > & vertices, bool fullTwoPi = true) inline static
This method works for all concentric type surface setups It includes :
Cylinder (concentric bows on each side, separated by z)
Cut-off cone
The single requirement is that the #vertices are equal and the input vector is splittable in half into the two bows.
Parameters
vertices The vector of vertices
fullTwoPi The indicator if the concentric face is closed
Definition at line 66 of file FacesHelper.hpp.
View newest version in sPHENIX GitHub at line 66 of file FacesHelper.hpp
Referenced by Acts::StrawSurface::polyhedronRepresentation(), Acts::PlaneSurface::polyhedronRepresentation(), Acts::ConeSurface::polyhedronRepresentation(), and Acts::CylinderSurface::polyhedronRepresentation().
The documentation for this struct was generated from the following file:
acts/blob/sPHENIX/Core/include/Acts/Surfaces/detail/FacesHelper.hpp