Analysis Software: ActsExamples::Contextual::PayloadDecorator Class Reference
ActsExamples::Contextual::PayloadDecorator Class Reference
A mockup service that rotates the modules in a simple tracking geometry.
#include <acts/blob/sPHENIX/Examples/Detectors/ContextualDetector/include/ActsExamples/ContextualDetector/PayloadDecorator.hpp>
Classes
struct Config
nested configuration struct
Public Member Functions
PayloadDecorator (const Config &cfg, std::unique_ptr< const Acts::Logger > logger=Acts::getDefaultLogger("PayloadDecorator", Acts::Logging::INFO))
virtual ~PayloadDecorator ()=default
Virtual destructor.
ProcessCode decorate (AlgorithmContext &context) finaloverride
decorates (adds, modifies) the AlgorithmContext with a geometric rotation per event
const std::string & name () const finaloverride
decorator name() for screen output
Public Member Functions inherited from ActsExamples::IContextDecorator
virtual ~IContextDecorator ()=default
Virtual destructor.
Private Member Functions
const Acts::Logger & logger () const
Private access to the logging instance.
void parseGeometry (const Acts::TrackingGeometry &tGeometry)
Private Attributes
Config m_cfg
the configuration class
std::unique_ptr< const
Acts::Logger > m_logger
std::string m_name = "PayloadDecorator"
!< the logging instance
std::vector< Acts::Transform3D > m_nominalStore
Map of nominal transforms.
Detailed Description
A mockup service that rotates the modules in a simple tracking geometry.
It acts on the PayloadDetectorElement, i.e. the geometry context carries the full transform store (payload)
Definition at line 32 of file PayloadDecorator.hpp.
View newest version in sPHENIX GitHub at line 32 of file PayloadDecorator.hpp
Constructor & Destructor Documentation
ActsExamples::Contextual::PayloadDecorator::PayloadDecorator (const Config & cfg, std::unique_ptr< const Acts::Logger > logger = Acts::getDefaultLogger("PayloadDecorator", Acts::Logging::INFO))
Constructor
Parameters
cfg Configuration struct
logger The logging framework
Definition at line 14 of file PayloadDecorator.cpp.
View newest version in sPHENIX GitHub at line 14 of file PayloadDecorator.cpp
References m_cfg, parseGeometry(), and ActsExamples::Contextual::PayloadDecorator::Config::trackingGeometry.
virtual ActsExamples::Contextual::PayloadDecorator::~PayloadDecorator () virtual default
Virtual destructor.
Member Function Documentation
ActsExamples::ProcessCode ActsExamples::Contextual::PayloadDecorator::decorate (AlgorithmContext & context) final override virtual
decorates (adds, modifies) the AlgorithmContext with a geometric rotation per event
Note
If decorators depend on each other, they have to be added in order.
Parameters
context the bare (or at least non-const) Event context
Implements ActsExamples::IContextDecorator.
Definition at line 24 of file PayloadDecorator.cpp.
View newest version in sPHENIX GitHub at line 24 of file PayloadDecorator.cpp
References ACTS_VERBOSE, ActsExamples::Contextual::PayloadDetectorElement::ContextType::alignmentStore, ActsExamples::AlgorithmContext::eventNumber, ActsExamples::AlgorithmContext::geoContext, testing::internal::move(), and SUCCESS.
const Acts::Logger& ActsExamples::Contextual::PayloadDecorator::logger () const inline private
Private access to the logging instance.
Definition at line 79 of file PayloadDecorator.hpp.
View newest version in sPHENIX GitHub at line 79 of file PayloadDecorator.hpp
References m_logger.
const std::string& ActsExamples::Contextual::PayloadDecorator::name () const inline final override virtual
decorator name() for screen output
Implements ActsExamples::IContextDecorator.
Definition at line 68 of file PayloadDecorator.hpp.
View newest version in sPHENIX GitHub at line 68 of file PayloadDecorator.hpp
References m_name.
void ActsExamples::Contextual::PayloadDecorator::parseGeometry (const Acts::TrackingGeometry & tGeometry) private
Populate the nominal transforms this parses the TrackingGeometry and fills the nominal store
Parameters
tGeometry the tracking geometry
Definition at line 44 of file PayloadDecorator.cpp.
View newest version in sPHENIX GitHub at line 44 of file PayloadDecorator.cpp
References testing::internal::move(), and Acts::TrackingGeometry::visitSurfaces().
Referenced by PayloadDecorator().
Member Data Documentation
Config ActsExamples::Contextual::PayloadDecorator::m_cfg private
the configuration class
Definition at line 71 of file PayloadDecorator.hpp.
View newest version in sPHENIX GitHub at line 71 of file PayloadDecorator.hpp
Referenced by PayloadDecorator().
std::unique_ptr<const Acts::Logger> ActsExamples::Contextual::PayloadDecorator::m_logger private
Definition at line 72 of file PayloadDecorator.hpp.
View newest version in sPHENIX GitHub at line 72 of file PayloadDecorator.hpp
Referenced by logger().
std::string ActsExamples::Contextual::PayloadDecorator::m_name = "PayloadDecorator" private
!< the logging instance
Definition at line 73 of file PayloadDecorator.hpp.
View newest version in sPHENIX GitHub at line 73 of file PayloadDecorator.hpp
Referenced by name().
std::vector<Acts::Transform3D> ActsExamples::Contextual::PayloadDecorator::m_nominalStore private
Map of nominal transforms.
Definition at line 76 of file PayloadDecorator.hpp.
View newest version in sPHENIX GitHub at line 76 of file PayloadDecorator.hpp
The documentation for this class was generated from the following files:
acts/blob/sPHENIX/Examples/Detectors/ContextualDetector/include/ActsExamples/ContextualDetector/PayloadDecorator.hpp
acts/blob/sPHENIX/Examples/Detectors/ContextualDetector/src/PayloadDecorator.cpp