Analysis Software: PHG4MvtxSupport Class Reference
PHG4MvtxSupport Class Reference
#include <coresoftware/blob/master/simulation/g4simulation/g4mvtx/PHG4MvtxSupport.h>
Public Member Functions
PHG4MvtxSupport (PHG4MvtxDetector *detector, PHG4MvtxDisplayAction *dispAct, bool overlapCheck)
virtual ~PHG4MvtxSupport ()
void ConstructMvtxSupport (G4LogicalVolume *&lv)
Private Member Functions
void CreateMvtxSupportMaterials ()
void CreateEndWheelsSideN (G4AssemblyVolume *&av)
void CreateEndWheelsSideS (G4AssemblyVolume *&av)
void CreateConeLayers (G4AssemblyVolume *&av)
void CreateCYSS (G4AssemblyVolume *&av)
void CreateServiceBarrel (G4AssemblyVolume *&av)
void GetEndWheelSideN (const int lay, G4AssemblyVolume *&endWheel)
void GetEndWheelSideS (const int lay, G4AssemblyVolume *&endWheel)
void GetConeVolume (int lay, G4AssemblyVolume *&av)
void CreateCable (PHG4MvtxCable *object, G4AssemblyVolume &assemblyVolume)
void CreateCableBundle (G4AssemblyVolume &assemblyVolume, const std::string &superName, bool enableSignal, bool enableCooling, bool enablePower, double x1, double x2, double y1, double y2, double z1, double z2)
G4AssemblyVolume * buildBarrelCable ()
G4AssemblyVolume * buildLayerCables (const int &lay)
Private Attributes
PHG4MvtxDetector * m_Detector {nullptr}
PHG4MvtxDisplayAction * m_DisplayAction {nullptr}
G4AssemblyVolume * m_avSupport {nullptr}
G4AssemblyVolume * m_avBarrelCable {nullptr}
std::array< G4AssemblyVolume
*, PHG4MvtxDefs::kNLayers > m_avLayerCable {nullptr, nullptr, nullptr}
bool m_overlapCheck {false}
Detailed Description
Definition at line 15 of file PHG4MvtxSupport.h.
View newest version in sPHENIX GitHub at line 15 of file PHG4MvtxSupport.h
Constructor & Destructor Documentation
PHG4MvtxSupport::PHG4MvtxSupport (PHG4MvtxDetector * detector, PHG4MvtxDisplayAction * dispAct, bool overlapCheck)
Definition at line 72 of file PHG4MvtxSupport.cc.
View newest version in sPHENIX GitHub at line 72 of file PHG4MvtxSupport.cc
PHG4MvtxSupport::~PHG4MvtxSupport () virtual
Definition at line 80 of file PHG4MvtxSupport.cc.
View newest version in sPHENIX GitHub at line 80 of file PHG4MvtxSupport.cc
References m_avBarrelCable, m_avLayerCable, and m_avSupport.
Member Function Documentation
G4AssemblyVolume * PHG4MvtxSupport::buildBarrelCable () private
Definition at line 1125 of file PHG4MvtxSupport.cc.
View newest version in sPHENIX GitHub at line 1125 of file PHG4MvtxSupport.cc
References ServiceProperties::BarrelCableEnd, ServiceProperties::BarrelCableStart, Acts::UnitConstants::cm, CreateCableBundle(), ServiceProperties::sEndWheelSNHolesZdist, ServiceProperties::sEndWStepHoleZdist, and ServiceProperties::sEndWStepHoleZpos.
Referenced by ConstructMvtxSupport().
G4AssemblyVolume * PHG4MvtxSupport::buildLayerCables (const int & lay) private
Definition at line 1138 of file PHG4MvtxSupport.cc.
View newest version in sPHENIX GitHub at line 1138 of file PHG4MvtxSupport.cc
References ServiceProperties::BarrelCableStart, CreateCableBundle(), Acts::UnitConstants::mm, ServiceProperties::sEndWheelSNHolesZdist, ServiceProperties::sEndWStepHoleZdist, ServiceProperties::sEndWStepHoleZpos, and to_string().
Referenced by ConstructMvtxSupport().
void PHG4MvtxSupport::ConstructMvtxSupport (G4LogicalVolume *& lv)
Definition at line 1161 of file PHG4MvtxSupport.cc.
View newest version in sPHENIX GitHub at line 1161 of file PHG4MvtxSupport.cc
References ServiceProperties::BarrelRadius, buildBarrelCable(), buildLayerCables(), ServiceProperties::cableRotate, Acts::UnitConstants::cm, CreateConeLayers(), CreateCYSS(), CreateEndWheelsSideN(), CreateEndWheelsSideS(), CreateMvtxSupportMaterials(), CreateServiceBarrel(), deg, i, PHG4MvtxDefs::kNLayers, PHG4MvtxDefs::kNStave, m_avBarrelCable, m_avLayerCable, m_avSupport, m_overlapCheck, PHG4MvtxDefs::mvtxdat, ActsTests::PropagationDatasets::phi, and Ra.
Referenced by PHG4MvtxDetector::ConstructMvtxPassiveVol().
void PHG4MvtxSupport::CreateCable (PHG4MvtxCable * object, G4AssemblyVolume & assemblyVolume) private
Definition at line 904 of file PHG4MvtxSupport.cc.
View newest version in sPHENIX GitHub at line 904 of file PHG4MvtxSupport.cc
References PHG4MvtxDisplayAction::AddVolume(), PHG4MvtxDetector::FillSupportLVArray(), PHG4MvtxCable::get_color(), PHG4MvtxCable::get_name(), PHG4Detector::GetDetectorMaterial(), i, G4PLUGDOOR::length, m_Detector, m_DisplayAction, and Acts::Test::transform.
Referenced by CreateCableBundle().
void PHG4MvtxSupport::CreateCableBundle (G4AssemblyVolume & assemblyVolume, const std::string & superName, bool enableSignal, bool enableCooling, bool enablePower, double x1, double x2, double y1, double y2, double z1, double z2) private
Definition at line 959 of file PHG4MvtxSupport.cc.
View newest version in sPHENIX GitHub at line 959 of file PHG4MvtxSupport.cc
References Acts::UnitConstants::cm, CreateCable(), material_mapping_optimisation::format, and str.
Referenced by buildBarrelCable(), and buildLayerCables().
void PHG4MvtxSupport::CreateConeLayers (G4AssemblyVolume *& av) private
Definition at line 485 of file PHG4MvtxSupport.cc.
View newest version in sPHENIX GitHub at line 485 of file PHG4MvtxSupport.cc
References GetConeVolume(), and PHG4MvtxDefs::kNLayers.
Referenced by ConstructMvtxSupport().
void PHG4MvtxSupport::CreateCYSS (G4AssemblyVolume *& av) private
Definition at line 560 of file PHG4MvtxSupport.cc.
View newest version in sPHENIX GitHub at line 560 of file PHG4MvtxSupport.cc
References PHG4MvtxDisplayAction::AddVolume(), PHG4MvtxDetector::FillSupportLVArray(), PHG4Detector::GetDetectorMaterial(), m_Detector, m_DisplayAction, Acts::UnitConstants::mm, Ra, Acts::UnitConstants::rad, ServiceProperties::sCYSSFlgSsfConesf, ServiceProperties::sCYSSFlgSsfCylsf, ServiceProperties::sCYSSFlgSsfFlgNsf, ServiceProperties::sCYSSFlgSsfRibsf, ServiceProperties::sEndWheelNLen, ServiceProperties::sEndWheelSNHolesZdist, ServiceProperties::sEndWStepHoleZdist, and ServiceProperties::sEndWStepHoleZpos.
Referenced by ConstructMvtxSupport().
void PHG4MvtxSupport::CreateEndWheelsSideN (G4AssemblyVolume *& av) private
Definition at line 134 of file PHG4MvtxSupport.cc.
View newest version in sPHENIX GitHub at line 134 of file PHG4MvtxSupport.cc
References GetEndWheelSideN(), and PHG4MvtxDefs::kNLayers.
Referenced by ConstructMvtxSupport().
void PHG4MvtxSupport::CreateEndWheelsSideS (G4AssemblyVolume *& av) private
Definition at line 318 of file PHG4MvtxSupport.cc.
View newest version in sPHENIX GitHub at line 318 of file PHG4MvtxSupport.cc
References GetEndWheelSideS(), and PHG4MvtxDefs::kNLayers.
Referenced by ConstructMvtxSupport().
void PHG4MvtxSupport::CreateMvtxSupportMaterials () private
Definition at line 100 of file PHG4MvtxSupport.cc.
View newest version in sPHENIX GitHub at line 100 of file PHG4MvtxSupport.cc
References Acts::UnitConstants::cm3, Acts::UnitConstants::g, PHG4Detector::GetDetectorElement(), PHG4Detector::GetDetectorMaterial(), and material.
Referenced by ConstructMvtxSupport().
void PHG4MvtxSupport::CreateServiceBarrel (G4AssemblyVolume *& av) private
Definition at line 814 of file PHG4MvtxSupport.cc.
View newest version in sPHENIX GitHub at line 814 of file PHG4MvtxSupport.cc
References PHG4MvtxDisplayAction::AddVolume(), PHG4MvtxDetector::FillSupportLVArray(), PHG4Detector::GetDetectorMaterial(), m_Detector, m_DisplayAction, Acts::UnitConstants::mm, Ra, ServiceProperties::sCYSSFlgSsfFlgNsf, ServiceProperties::sEndWheelNLen, ServiceProperties::sEndWheelSNHolesZdist, ServiceProperties::sEndWStepHoleZdist, and ServiceProperties::sEndWStepHoleZpos.
Referenced by ConstructMvtxSupport().
void PHG4MvtxSupport::GetConeVolume (int lay, G4AssemblyVolume *& av) private
Definition at line 494 of file PHG4MvtxSupport.cc.
View newest version in sPHENIX GitHub at line 494 of file PHG4MvtxSupport.cc
References PHG4MvtxDisplayAction::AddVolume(), PHG4MvtxDetector::FillSupportLVArray(), PHG4Detector::GetDetectorMaterial(), m_Detector, m_DisplayAction, Acts::UnitConstants::mm, Ra, Acts::UnitConstants::rad, ServiceProperties::sEndWheelSNHolesZdist, ServiceProperties::sEndWStepHoleZdist, ServiceProperties::sEndWStepHoleZpos, and to_string().
Referenced by CreateConeLayers().
void PHG4MvtxSupport::GetEndWheelSideN (const int lay, G4AssemblyVolume *& endWheel) private
Definition at line 143 of file PHG4MvtxSupport.cc.
View newest version in sPHENIX GitHub at line 143 of file PHG4MvtxSupport.cc
References PHG4MvtxDisplayAction::AddVolume(), deg, INTTVtxZ::dphi, PHG4MvtxDetector::FillSupportLVArray(), PHG4Detector::GetDetectorMaterial(), j, PHG4MvtxDefs::kNStave, PHG4MvtxDefs::kPhi0, m_Detector, m_DisplayAction, Acts::UnitConstants::mm, PHG4MvtxDefs::mvtxdat, ActsTests::PropagationDatasets::phi, MATSCAN::phimin, Ra, Acts::UnitConstants::rad, ServiceProperties::sEndWheelNLen, ServiceProperties::sEndWheelSNHolesZdist, ServiceProperties::sEndWStepHoleZdist, ServiceProperties::sEndWStepHoleZpos, to_string(), and xpos.
Referenced by CreateEndWheelsSideN().
void PHG4MvtxSupport::GetEndWheelSideS (const int lay, G4AssemblyVolume *& endWheel) private
Definition at line 327 of file PHG4MvtxSupport.cc.
View newest version in sPHENIX GitHub at line 327 of file PHG4MvtxSupport.cc
References PHG4MvtxDisplayAction::AddVolume(), deg, INTTVtxZ::dphi, PHG4MvtxDetector::FillSupportLVArray(), PHG4Detector::GetDetectorMaterial(), j, PHG4MvtxDefs::kNStave, PHG4MvtxDefs::kPhi0, m_Detector, m_DisplayAction, Acts::UnitConstants::mm, PHG4MvtxDefs::mvtxdat, ActsTests::PropagationDatasets::phi, MATSCAN::phimin, Ra, Acts::UnitConstants::rad, ServiceProperties::sEndWheelSNHolesZdist, ServiceProperties::sEndWStepHoleZdist, ServiceProperties::sEndWStepHoleZpos, to_string(), and xpos.
Referenced by CreateEndWheelsSideS().
Member Data Documentation
G4AssemblyVolume* PHG4MvtxSupport::m_avBarrelCable {nullptr} private
Definition at line 49 of file PHG4MvtxSupport.h.
View newest version in sPHENIX GitHub at line 49 of file PHG4MvtxSupport.h
Referenced by ConstructMvtxSupport(), and ~PHG4MvtxSupport().
std::array<G4AssemblyVolume *, PHG4MvtxDefs::kNLayers> PHG4MvtxSupport::m_avLayerCable {nullptr, nullptr, nullptr} private
Definition at line 50 of file PHG4MvtxSupport.h.
View newest version in sPHENIX GitHub at line 50 of file PHG4MvtxSupport.h
Referenced by ConstructMvtxSupport(), and ~PHG4MvtxSupport().
G4AssemblyVolume* PHG4MvtxSupport::m_avSupport {nullptr} private
Definition at line 48 of file PHG4MvtxSupport.h.
View newest version in sPHENIX GitHub at line 48 of file PHG4MvtxSupport.h
Referenced by ConstructMvtxSupport(), and ~PHG4MvtxSupport().
PHG4MvtxDetector* PHG4MvtxSupport::m_Detector {nullptr} private
Definition at line 25 of file PHG4MvtxSupport.h.
View newest version in sPHENIX GitHub at line 25 of file PHG4MvtxSupport.h
Referenced by CreateCable(), CreateCYSS(), CreateServiceBarrel(), GetConeVolume(), GetEndWheelSideN(), and GetEndWheelSideS().
PHG4MvtxDisplayAction* PHG4MvtxSupport::m_DisplayAction {nullptr} private
Definition at line 26 of file PHG4MvtxSupport.h.
View newest version in sPHENIX GitHub at line 26 of file PHG4MvtxSupport.h
Referenced by CreateCable(), CreateCYSS(), CreateServiceBarrel(), GetConeVolume(), GetEndWheelSideN(), and GetEndWheelSideS().
bool PHG4MvtxSupport::m_overlapCheck {false} private
Definition at line 52 of file PHG4MvtxSupport.h.
View newest version in sPHENIX GitHub at line 52 of file PHG4MvtxSupport.h
Referenced by ConstructMvtxSupport().
The documentation for this class was generated from the following files:
coresoftware/blob/master/simulation/g4simulation/g4mvtx/PHG4MvtxSupport.h
coresoftware/blob/master/simulation/g4simulation/g4mvtx/PHG4MvtxSupport.cc