Analysis Software: EmbRecoMatchContainer Class Reference
EmbRecoMatchContainer Class Reference
#include <coresoftware/blob/master/simulation/g4simulation/g4tracking/EmbRecoMatchContainer.h>
Public Types
using Vector = std::vector< EmbRecoMatch * >
using ConstIterator = Vector::const_iterator
using ConstRange = std::pair< ConstIterator, ConstIterator >
using Map_nMatches = std::map< unsigned short, unsigned short >
Public Member Functions
void Reset () override
reset method
virtual unsigned short nMatches () const
add a match set
virtual unsigned short nTruthUnmatched () const
virtual std::vector< unsigned
short > & ids_TruthUnmatched ()
virtual std::vector< unsigned
short > ids_TruthMatched () const
virtual std::vector< unsigned
short > ids_RecoMatched () const
virtual std::map< unsigned
short, unsigned short > & map_nRecoPerTruth ()
virtual std::map< unsigned
short, unsigned short > & map_nTruthPerReco ()
virtual ConstRange getMatchedRange () const
virtual Vector & getMatches ()
virtual void addMatch (EmbRecoMatch *)
virtual bool hasTruthMatch (unsigned short)
virtual bool hasRecoMatch (unsigned short)
virtual EmbRecoMatch * getMatchTruth (unsigned short, unsigned short=0)
virtual EmbRecoMatch * getMatchReco (unsigned short, unsigned short=0)
virtual void checkfill_idsTruthUnmatched (unsigned short)
virtual void sort ()
void identify (std::ostream &os=std::cout) const override
Public Member Functions inherited from PHObject
PHObject ()
ctor
~PHObject () override
dtor
virtual PHObject * CloneMe () const
Virtual copy constructor.
virtual PHObject * clone () const final
PHObject * Clone (const char *newname="") const final
void Copy (TObject &object) const final
virtual int isValid () const
isValid returns non zero if object contains vailid data
virtual int Integrate () const
virtual int Integrate (PHObject *)
virtual void CopyFrom (const PHObject *obj)
Protected Member Functions
EmbRecoMatchContainer ()=default
Detailed Description
Definition at line 11 of file EmbRecoMatchContainer.h.
View newest version in sPHENIX GitHub at line 11 of file EmbRecoMatchContainer.h
Member Typedef Documentation
using EmbRecoMatchContainer::ConstIterator = Vector::const_iterator
Definition at line 15 of file EmbRecoMatchContainer.h.
View newest version in sPHENIX GitHub at line 15 of file EmbRecoMatchContainer.h
using EmbRecoMatchContainer::ConstRange = std::pair<ConstIterator, ConstIterator>
Definition at line 16 of file EmbRecoMatchContainer.h.
View newest version in sPHENIX GitHub at line 16 of file EmbRecoMatchContainer.h
using EmbRecoMatchContainer::Map_nMatches = std::map<unsigned short, unsigned short>
Definition at line 17 of file EmbRecoMatchContainer.h.
View newest version in sPHENIX GitHub at line 17 of file EmbRecoMatchContainer.h
using EmbRecoMatchContainer::Vector = std::vector<EmbRecoMatch*>
Definition at line 14 of file EmbRecoMatchContainer.h.
View newest version in sPHENIX GitHub at line 14 of file EmbRecoMatchContainer.h
Constructor & Destructor Documentation
EmbRecoMatchContainer::EmbRecoMatchContainer () protected default
Member Function Documentation
virtual void EmbRecoMatchContainer::addMatch (EmbRecoMatch *) inline virtual
Reimplemented in EmbRecoMatchContainerv1.
Definition at line 38 of file EmbRecoMatchContainer.h.
View newest version in sPHENIX GitHub at line 38 of file EmbRecoMatchContainer.h
virtual void EmbRecoMatchContainer::checkfill_idsTruthUnmatched (unsigned short) inline virtual
Reimplemented in EmbRecoMatchContainerv1.
Definition at line 44 of file EmbRecoMatchContainer.h.
View newest version in sPHENIX GitHub at line 44 of file EmbRecoMatchContainer.h
EmbRecoMatchContainer::ConstRange EmbRecoMatchContainer::getMatchedRange () const virtual
Reimplemented in EmbRecoMatchContainerv1.
Definition at line 10 of file EmbRecoMatchContainer.cc.
View newest version in sPHENIX GitHub at line 10 of file EmbRecoMatchContainer.cc
EmbRecoMatchContainer::Vector & EmbRecoMatchContainer::getMatches () virtual
Reimplemented in EmbRecoMatchContainerv1.
Definition at line 13 of file EmbRecoMatchContainer.cc.
View newest version in sPHENIX GitHub at line 13 of file EmbRecoMatchContainer.cc
Referenced by FillTruthRecoMatchMap::process_event(), and FillTruthRecoMatchTree::process_event().
virtual EmbRecoMatch* EmbRecoMatchContainer::getMatchReco (unsigned short , unsigned short = 0) inline virtual
Reimplemented in EmbRecoMatchContainerv1.
Definition at line 42 of file EmbRecoMatchContainer.h.
View newest version in sPHENIX GitHub at line 42 of file EmbRecoMatchContainer.h
virtual EmbRecoMatch* EmbRecoMatchContainer::getMatchTruth (unsigned short , unsigned short = 0) inline virtual
Reimplemented in EmbRecoMatchContainerv1.
Definition at line 41 of file EmbRecoMatchContainer.h.
View newest version in sPHENIX GitHub at line 41 of file EmbRecoMatchContainer.h
virtual bool EmbRecoMatchContainer::hasRecoMatch (unsigned short) inline virtual
Reimplemented in EmbRecoMatchContainerv1.
Definition at line 40 of file EmbRecoMatchContainer.h.
View newest version in sPHENIX GitHub at line 40 of file EmbRecoMatchContainer.h
virtual bool EmbRecoMatchContainer::hasTruthMatch (unsigned short) inline virtual
Reimplemented in EmbRecoMatchContainerv1.
Definition at line 39 of file EmbRecoMatchContainer.h.
View newest version in sPHENIX GitHub at line 39 of file EmbRecoMatchContainer.h
void EmbRecoMatchContainer::identify (std::ostream & os = std::cout) const inline override virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from PHObject.
Reimplemented in EmbRecoMatchContainerv1.
Definition at line 49 of file EmbRecoMatchContainer.h.
View newest version in sPHENIX GitHub at line 49 of file EmbRecoMatchContainer.h
References os.
virtual std::vector<unsigned short> EmbRecoMatchContainer::ids_RecoMatched () const inline virtual
Reimplemented in EmbRecoMatchContainerv1.
Definition at line 30 of file EmbRecoMatchContainer.h.
View newest version in sPHENIX GitHub at line 30 of file EmbRecoMatchContainer.h
Referenced by g4evalfn::unmatchedSvtxTrkIds(), and G4Eval::unmatchedSvtxTrkIds().
virtual std::vector<unsigned short> EmbRecoMatchContainer::ids_TruthMatched () const inline virtual
Reimplemented in EmbRecoMatchContainerv1.
Definition at line 29 of file EmbRecoMatchContainer.h.
View newest version in sPHENIX GitHub at line 29 of file EmbRecoMatchContainer.h
std::vector< unsigned short > & EmbRecoMatchContainer::ids_TruthUnmatched () virtual
Reimplemented in EmbRecoMatchContainerv1.
Definition at line 16 of file EmbRecoMatchContainer.cc.
View newest version in sPHENIX GitHub at line 16 of file EmbRecoMatchContainer.cc
Referenced by FillTruthRecoMatchTree::process_event().
std::map< unsigned short, unsigned short > & EmbRecoMatchContainer::map_nRecoPerTruth () virtual
Reimplemented in EmbRecoMatchContainerv1.
Definition at line 19 of file EmbRecoMatchContainer.cc.
View newest version in sPHENIX GitHub at line 19 of file EmbRecoMatchContainer.cc
std::map< unsigned short, unsigned short > & EmbRecoMatchContainer::map_nTruthPerReco () virtual
Reimplemented in EmbRecoMatchContainerv1.
Definition at line 22 of file EmbRecoMatchContainer.cc.
View newest version in sPHENIX GitHub at line 22 of file EmbRecoMatchContainer.cc
virtual unsigned short EmbRecoMatchContainer::nMatches () const inline virtual
add a match set
Reimplemented in EmbRecoMatchContainerv1.
Definition at line 25 of file EmbRecoMatchContainer.h.
View newest version in sPHENIX GitHub at line 25 of file EmbRecoMatchContainer.h
virtual unsigned short EmbRecoMatchContainer::nTruthUnmatched () const inline virtual
Reimplemented in EmbRecoMatchContainerv1.
Definition at line 26 of file EmbRecoMatchContainer.h.
View newest version in sPHENIX GitHub at line 26 of file EmbRecoMatchContainer.h
void EmbRecoMatchContainer::Reset () inline override virtual
reset method
Reimplemented from PHObject.
Reimplemented in EmbRecoMatchContainerv1.
Definition at line 22 of file EmbRecoMatchContainer.h.
View newest version in sPHENIX GitHub at line 22 of file EmbRecoMatchContainer.h
virtual void EmbRecoMatchContainer::sort () inline virtual
Reimplemented in EmbRecoMatchContainerv1.
Definition at line 46 of file EmbRecoMatchContainer.h.
View newest version in sPHENIX GitHub at line 46 of file EmbRecoMatchContainer.h
The documentation for this class was generated from the following files:
coresoftware/blob/master/simulation/g4simulation/g4tracking/EmbRecoMatchContainer.h
coresoftware/blob/master/simulation/g4simulation/g4tracking/EmbRecoMatchContainer.cc