Analysis Software: Fatras::Test Namespace Reference
Fatras::Test Namespace Reference
Classes
struct Particle
Particle for testing acts-fatras core functionality.
struct Generator
needed are : generator, detector, particle
struct Detector
The detector.
struct SterileProcess
Physics process that does not trigger a break.
struct FatalProcess
Physics process that DOES trigger a break.
struct Selector
The selector.
struct EnergyDecreaser
The scattering formula.
struct Object
needed are : object, environment
struct Environment
struct FeatureSelector
struct NameSelector
struct EnvironmentSelector
Typedefs
typedef std::mt19937 Generator
the generator
Functions
BOOST_AUTO_TEST_CASE (PhysicsLists_test)
BOOST_DATA_TEST_CASE (Process_test_, bdata::random((bdata::seed=20, bdata::distribution=std::uniform_real_distribution<>(0., 1.)))^bdata::random((bdata::seed=21, bdata::distribution=std::uniform_real_distribution<>(0., 1.)))^bdata::random((bdata::seed=22, bdata::distribution=std::uniform_real_distribution<>(0., 1.)))^bdata::random((bdata::seed=23, bdata::distribution=std::uniform_real_distribution<>(1., 100.)))^bdata::xrange(100), x, y, z, p, index)
Test the scattering implementation.
BOOST_AUTO_TEST_CASE (SelectorList_test)
std::ofstream os ("EnergyLoss.csv", std::ofstream::out|std::ofstream::trunc)
BOOST_DATA_TEST_CASE (EnergyLoss_test_, bdata::random((bdata::seed=20, bdata::distribution=std::uniform_real_distribution<>(0., 1.)))^bdata::random((bdata::seed=21, bdata::distribution=std::uniform_real_distribution<>(0., 1.)))^bdata::random((bdata::seed=22, bdata::distribution=std::uniform_real_distribution<>(0., 1.)))^bdata::random((bdata::seed=23, bdata::distribution=std::uniform_real_distribution<>(1.5, 10.5)))^bdata::xrange(10000), x, y, z, p, index)
Test the scattering implementation.
std::ofstream os ("ScatteringAngles.csv", std::ofstream::out|std::ofstream::trunc)
BOOST_DATA_TEST_CASE (HighlandScattering_test_, bdata::random((bdata::seed=20, bdata::distribution=std::uniform_real_distribution<>(0., 1.)))^bdata::random((bdata::seed=21, bdata::distribution=std::uniform_real_distribution<>(0., 1.)))^bdata::random((bdata::seed=22, bdata::distribution=std::uniform_real_distribution<>(0., 1.)))^bdata::random((bdata::seed=23, bdata::distribution=std::uniform_real_distribution<>(0.5, 10.5)))^bdata::xrange(10000), x, y, z, p, index)
Test the scattering implementation.
BOOST_AUTO_TEST_CASE (Kinematic_cast_tests)
BOOST_AUTO_TEST_CASE (PdgSelectors_test)
BOOST_AUTO_TEST_CASE (SelectorHelper_tests)
Variables
Generator generator
Acts::Material berilium
bool write_csv = true
write CSV flag
double m = 134.9766 * Acts::units::_MeV
double m_muon = 0.51099891 * Acts::units::_MeV
double m_e = 105.658367 * Acts::units::_MeV
double m_pion = 134.9766 * Acts::units::_MeV
Typedef Documentation
typedef std::mt19937 Fatras::Test::Generator
the generator
Definition at line 37 of file ProcessTests.cpp.
View newest version in sPHENIX GitHub at line 37 of file ProcessTests.cpp
Function Documentation
Fatras::Test::BOOST_AUTO_TEST_CASE (Kinematic_cast_tests)
Definition at line 35 of file KinematicCastsTests.cpp.
View newest version in sPHENIX GitHub at line 35 of file KinematicCastsTests.cpp
References Acts::UnitConstants::e, m, position, and Acts::Test::tolerance.
Fatras::Test::BOOST_AUTO_TEST_CASE (SelectorHelper_tests)
Definition at line 38 of file SelectorHelpersTests.cpp.
View newest version in sPHENIX GitHub at line 38 of file SelectorHelpersTests.cpp
References m_pion, position, Fatras::Max< cast_t >::valMax, Fatras::Range< cast_t >::valMax, Fatras::Min< cast_t >::valMin, and Fatras::Range< cast_t >::valMin.
Fatras::Test::BOOST_AUTO_TEST_CASE (PdgSelectors_test)
Definition at line 39 of file PdgSelectorsTests.cpp.
View newest version in sPHENIX GitHub at line 39 of file PdgSelectorsTests.cpp
References electron, m_e, m_muon, momentum, and position.
Fatras::Test::BOOST_AUTO_TEST_CASE (PhysicsLists_test)
empty physics_list
sterile test should never send the abort command
sterile test should not send the abort command
fatal test should send abort command
fatal test should send abort command
Definition at line 62 of file PhysicsListTests.cpp.
View newest version in sPHENIX GitHub at line 62 of file PhysicsListTests.cpp
References generator, Acts::detail::Extendable< extensions_t >::get(), in, out, and Fatras::Test::SterileProcess::some_parameter.
Fatras::Test::BOOST_AUTO_TEST_CASE (SelectorList_test)
Definition at line 80 of file SelectorListTests.cpp.
View newest version in sPHENIX GitHub at line 80 of file SelectorListTests.cpp
References Fatras::Test::Object::feature, Acts::detail::Extendable< selectors...>::get(), Fatras::Test::Object::name, Fatras::Test::Environment::pickFeature, Fatras::Test::FeatureSelector::select_on, and Fatras::Test::NameSelector::select_on.
Fatras::Test::BOOST_DATA_TEST_CASE (EnergyLoss_test_ , bdata:: random(bdata::seed=20,bdata::distribution=std::uniform_real_distribution<>(0., 1.)))^bdata::random((bdata::seed=21,bdata::distribution=std::uniform_real_distribution<>(0., 1.)))^bdata::random((bdata::seed=22,bdata::distribution=std::uniform_real_distribution<>(0., 1.)))^bdata::random((bdata::seed=23,bdata::distribution=std::uniform_real_distribution<>(1.5, 10.5)))^bdata::xrange(10000, x , y , z , p , index)
Test the scattering implementation.
position at 0.,0.,0
Definition at line 65 of file EnergyLossTests.cpp.
View newest version in sPHENIX GitHub at line 65 of file EnergyLossTests.cpp
References berilium, E, Fatras::Test::Particle::E(), generator, index, m, Fatras::Test::Particle::m(), momentum, os(), merge_hashes::p, particle, Fatras::Test::Particle::pdg(), position, write_csv, ambiguity_solver_full_chain::x, y, and physmon_track_finding_ttbar::z.
Fatras::Test::BOOST_DATA_TEST_CASE (HighlandScattering_test_ , bdata:: random(bdata::seed=20,bdata::distribution=std::uniform_real_distribution<>(0., 1.)))^bdata::random((bdata::seed=21,bdata::distribution=std::uniform_real_distribution<>(0., 1.)))^bdata::random((bdata::seed=22,bdata::distribution=std::uniform_real_distribution<>(0., 1.)))^bdata::random((bdata::seed=23,bdata::distribution=std::uniform_real_distribution<>(0.5, 10.5)))^bdata::xrange(10000, x , y , z , p , index)
Test the scattering implementation.
position at 0.,0.,0
Definition at line 66 of file ScatteringTests.cpp.
View newest version in sPHENIX GitHub at line 66 of file ScatteringTests.cpp
References berilium, generator, index, m, momentum, os(), out, merge_hashes::p, Fatras::Test::Particle::p(), particle, position, write_csv, ambiguity_solver_full_chain::x, y, and physmon_track_finding_ttbar::z.
Fatras::Test::BOOST_DATA_TEST_CASE (Process_test_ , bdata:: random(bdata::seed=20,bdata::distribution=std::uniform_real_distribution<>(0., 1.)))^bdata::random((bdata::seed=21,bdata::distribution=std::uniform_real_distribution<>(0., 1.)))^bdata::random((bdata::seed=22,bdata::distribution=std::uniform_real_distribution<>(0., 1.)))^bdata::random((bdata::seed=23,bdata::distribution=std::uniform_real_distribution<>(1., 100.)))^bdata::xrange(100, x , y , z , p , index)
Test the scattering implementation.
position at 0.,0.,0
Definition at line 68 of file ProcessTests.cpp.
View newest version in sPHENIX GitHub at line 68 of file ProcessTests.cpp
References generator, m, momentum, Fatras::Test::Particle::momentum(), merge_hashes::p, particle, position, ambiguity_solver_full_chain::x, y, and physmon_track_finding_ttbar::z.
std::ofstream Fatras::Test::os ("EnergyLoss.csv" , std::ofstream::out|std::ofstream::trunc)
Referenced by BOOST_DATA_TEST_CASE().
std::ofstream Fatras::Test::os ("ScatteringAngles.csv" , std::ofstream::out|std::ofstream::trunc)
Variable Documentation
Acts::Material Fatras::Test::berilium
Initial value:
= Acts::Material(352.8, 407., 9.012, 4.,
                                         1.848 / (au::_cm * au::_cm * au::_cm))
Definition at line 46 of file EnergyLossTests.cpp.
View newest version in sPHENIX GitHub at line 46 of file EnergyLossTests.cpp
Referenced by BOOST_DATA_TEST_CASE().
Generator Fatras::Test::generator
Definition at line 43 of file EnergyLossTests.cpp.
View newest version in sPHENIX GitHub at line 43 of file EnergyLossTests.cpp
Referenced by BOOST_AUTO_TEST_CASE(), BOOST_AUTO_TEST_CASE(), BOOST_DATA_TEST_CASE(), BOOST_DATA_TEST_CASE(), DSTCompressor::compress_gaussian_dist(), Fun4All_G4_sPHENIX(), main(), ActsFatras::LandauDistribution::operator()(), PHG4PileupGenerator::set_generator(), and ActsFatras::SingleParticleSimulation< propagator_t, interactions_t, hit_surface_selector_t, decay_t >::simulate().
double Fatras::Test::m = 134.9766 * Acts::units::_MeV
Definition at line 32 of file KinematicCastsTests.cpp.
View newest version in sPHENIX GitHub at line 32 of file KinematicCastsTests.cpp
Referenced by BOOST_AUTO_TEST_CASE(), and BOOST_DATA_TEST_CASE().
double Fatras::Test::m_e = 105.658367 * Acts::units::_MeV
Definition at line 33 of file PdgSelectorsTests.cpp.
View newest version in sPHENIX GitHub at line 33 of file PdgSelectorsTests.cpp
Referenced by ana_hijbkg(), and BOOST_AUTO_TEST_CASE().
double Fatras::Test::m_muon = 0.51099891 * Acts::units::_MeV
Definition at line 32 of file PdgSelectorsTests.cpp.
View newest version in sPHENIX GitHub at line 32 of file PdgSelectorsTests.cpp
Referenced by BOOST_AUTO_TEST_CASE().
double Fatras::Test::m_pion = 134.9766 * Acts::units::_MeV
Definition at line 34 of file PdgSelectorsTests.cpp.
View newest version in sPHENIX GitHub at line 34 of file PdgSelectorsTests.cpp
Referenced by BOOST_AUTO_TEST_CASE().
bool Fatras::Test::write_csv = true
write CSV flag
Definition at line 60 of file EnergyLossTests.cpp.
View newest version in sPHENIX GitHub at line 60 of file EnergyLossTests.cpp
Referenced by BOOST_DATA_TEST_CASE().