Analysis Software: analysis/blob/master/QuarkoniaBG/upsilons_sphenix_5yesrs.C File Reference
upsilons_sphenix_5yesrs.C File Reference
Functions
gStyle SetOptStat (0)
gStyle SetOptTitle (0)
cfitall Range (5.572152,-447.647, 14.4962, 1837.109)
cfitall SetFillColor (0)
cfitall SetBorderMode (0)
cfitall SetBorderSize (2)
cfitall SetTickx (1)
cfitall SetTicky (1)
cfitall SetLeftMargin (0.16)
cfitall SetRightMargin (0.05)
cfitall SetTopMargin (0.05)
cfitall SetBottomMargin (0.16)
cfitall SetFrameBorderMode (0)
hhfit_15 SetBinContent (1,-5.188214e+10)
hhfit_15 SetBinContent (2,-4.693237e+10)
hhfit_15 SetBinContent (3,-4.245483e+10)
hhfit_15 SetBinContent (4,-3.840447e+10)
hhfit_15 SetBinContent (5,-3.474053e+10)
hhfit_15 SetBinContent (6,-3.142614e+10)
hhfit_15 SetBinContent (7,-2.842796e+10)
hhfit_15 SetBinContent (8,-2.571582e+10)
hhfit_15 SetBinContent (9,-2.326242e+10)
hhfit_15 SetBinContent (10,-2.104309e+10)
hhfit_15 SetBinContent (11,-1.90355e+10)
hhfit_15 SetBinContent (12,-1.721943e+10)
hhfit_15 SetBinContent (13,-1.557663e+10)
hhfit_15 SetBinContent (14,-1.409056e+10)
hhfit_15 SetBinContent (15,-1.274626e+10)
hhfit_15 SetBinContent (16,-1.153022e+10)
hhfit_15 SetBinContent (17,-1.043019e+10)
hhfit_15 SetBinContent (18,-9.435104e+09)
hhfit_15 SetBinContent (19,-8.534957e+09)
hhfit_15 SetBinContent (20,-7.720688e+09)
hhfit_15 SetBinContent (21,-6.984103e+09)
hhfit_15 SetBinContent (22,-6.317791e+09)
hhfit_15 SetBinContent (23,-5.715048e+09)
hhfit_15 SetBinContent (24,-5.169809e+09)
hhfit_15 SetBinContent (25,-4.676589e+09)
hhfit_15 SetBinContent (26,-4.230423e+09)
hhfit_15 SetBinContent (27,-3.826823e+09)
hhfit_15 SetBinContent (28,-3.461729e+09)
hhfit_15 SetBinContent (29,-3.131466e+09)
hhfit_15 SetBinContent (30,-2.832711e+09)
hhfit_15 SetBinContent (31,-2.562459e+09)
hhfit_15 SetBinContent (32,-2.31799e+09)
hhfit_15 SetBinContent (33,-2.096845e+09)
hhfit_15 SetBinContent (34,-1.896797e+09)
hhfit_15 SetBinContent (35,-1.715835e+09)
hhfit_15 SetBinContent (36,-1.552137e+09)
hhfit_15 SetBinContent (37,-1.404057e+09)
hhfit_15 SetBinContent (38,-1.270104e+09)
hhfit_15 SetBinContent (39,-1.148931e+09)
hhfit_15 SetBinContent (40,-1.039319e+09)
hhfit_15 SetBinContent (41,-9.401634e+08)
hhfit_15 SetBinContent (42,-8.50468e+08)
hhfit_15 SetBinContent (43,-7.693299e+08)
hhfit_15 SetBinContent (44,-6.959327e+08)
hhfit_15 SetBinContent (45,-6.295379e+08)
hhfit_15 SetBinContent (46,-5.694774e+08)
hhfit_15 SetBinContent (47,-5.15147e+08)
hhfit_15 SetBinContent (48,-4.659999e+08)
hhfit_15 SetBinContent (49,-4.215416e+08)
hhfit_15 SetBinContent (50,-3.813248e+08)
hhfit_15 SetBinContent (51,-3.449449e+08)
hhfit_15 SetBinContent (52,-3.120357e+08)
hhfit_15 SetBinContent (53,-2.822663e+08)
hhfit_15 SetBinContent (54,-2.553369e+08)
hhfit_15 SetBinContent (55,-2.309767e+08)
hhfit_15 SetBinContent (56,-2.089406e+08)
hhfit_15 SetBinContent (57,-1.890068e+08)
hhfit_15 SetBinContent (58,-1.709748e+08)
hhfit_15 SetBinContent (59,-1.546631e+08)
hhfit_15 SetBinContent (60,-1.399076e+08)
hhfit_15 SetBinContent (61,-1.265599e+08)
hhfit_15 SetBinContent (62,-1.144856e+08)
hhfit_15 SetBinContent (63,-1.035632e+08)
hhfit_15 SetBinContent (64,-9.368283e+07)
hhfit_15 SetBinContent (65,-8.474511e+07)
hhfit_15 SetBinContent (66,-7.666008e+07)
hhfit_15 SetBinContent (67,-6.93464e+07)
hhfit_15 SetBinContent (68,-6.273047e+07)
hhfit_15 SetBinContent (69,-5.674573e+07)
hhfit_15 SetBinContent (70,-5.133196e+07)
hhfit_15 SetBinContent (71,-4.643468e+07)
hhfit_15 SetBinContent (72,-4.200462e+07)
hhfit_15 SetBinContent (73,-3.799721e+07)
hhfit_15 SetBinContent (74,-3.437212e+07)
hhfit_15 SetBinContent (75,-3.109288e+07)
hhfit_15 SetBinContent (76,-2.81265e+07)
hhfit_15 SetBinContent (77,-2.544311e+07)
hhfit_15 SetBinContent (78,-2.301574e+07)
hhfit_15 SetBinContent (79,-2.081994e+07)
hhfit_15 SetBinContent (80,-1.883364e+07)
hhfit_15 SetBinContent (81,-1.703683e+07)
hhfit_15 SetBinContent (82,-1.541145e+07)
hhfit_15 SetBinContent (83,-1.394113e+07)
hhfit_15 SetBinContent (84,-1.261109e+07)
hhfit_15 SetBinContent (85,-1.140794e+07)
hhfit_15 SetBinContent (86,-1.031958e+07)
hhfit_15 SetBinContent (87,-9335050)
hhfit_15 SetBinContent (88,-8444448)
hhfit_15 SetBinContent (89,-7638814)
hhfit_15 SetBinContent (90,-6910040)
hhfit_15 SetBinContent (91,-6250794)
hhfit_15 SetBinContent (92,-5654443)
hhfit_15 SetBinContent (93,-5114986)
hhfit_15 SetBinContent (94,-4626996)
hhfit_15 SetBinContent (95,-4185562)
hhfit_15 SetBinContent (96,-3786242)
hhfit_15 SetBinContent (97,-3425019)
hhfit_15 SetBinContent (98,-3098258)
hhfit_15 SetBinContent (99,-2802672)
hhfit_15 SetBinContent (100,-2535286)
hhfit_15 SetBinContent (101,-2293386)
hhfit_15 SetBinContent (102,-2074582)
hhfit_15 SetBinContent (103,-1876671)
hhfit_15 SetBinContent (104,-1697619)
hhfit_15 SetBinContent (105,-1535656)
hhfit_15 SetBinContent (106,-1389145)
hhfit_15 SetBinContent (107,-1256613)
hhfit_15 SetBinContent (108,-1136725)
hhfit_15 SetBinContent (109,-1028277)
hhfit_15 SetBinContent (110,-930164.5)
hhfit_15 SetBinContent (111,-841424.2)
hhfit_15 SetBinContent (112,-761147.6)
hhfit_15 SetBinContent (113,-688520.7)
hhfit_15 SetBinContent (114,-622843)
hhfit_15 SetBinContent (115,-563405.4)
hhfit_15 SetBinContent (116,-509643.1)
hhfit_15 SetBinContent (117,-461031.2)
hhfit_15 SetBinContent (118,-417045.4)
hhfit_15 SetBinContent (119,-377252.1)
hhfit_15 SetBinContent (120,-341269.9)
hhfit_15 SetBinContent (121,-308687.8)
hhfit_15 SetBinContent (122,-279247)
hhfit_15 SetBinContent (123,-252603.2)
hhfit_15 SetBinContent (124,-228489.4)
hhfit_15 SetBinContent (125,-206691.9)
hhfit_15 SetBinContent (126,-186968.5)
hhfit_15 SetBinContent (127,-169126.7)
hhfit_15 SetBinContent (128,-152994)
hhfit_15 SetBinContent (129,-138396)
hhfit_15 SetBinContent (130,-125190.8)
hhfit_15 SetBinContent (131,-113240.5)
hhfit_15 SetBinContent (132,-102420.9)
hhfit_15 SetBinContent (133,-92649.37)
hhfit_15 SetBinContent (134,-83813.43)
hhfit_15 SetBinContent (135,-75808.14)
hhfit_15 SetBinContent (136,-68574.01)
hhfit_15 SetBinContent (137,-62049.24)
hhfit_15 SetBinContent (138,-56100.97)
hhfit_15 SetBinContent (139,-50754.61)
hhfit_15 SetBinContent (140,-45904.26)
hhfit_15 SetBinContent (141, 1150.816)
hhfit_15 SetBinContent (142, 1290.73)
hhfit_15 SetBinContent (143, 1110.376)
hhfit_15 SetBinContent (144, 1201.841)
hhfit_15 SetBinContent (145, 884.7713)
hhfit_15 SetBinContent (146, 979.6972)
hhfit_15 SetBinContent (147, 1011.332)
hhfit_15 SetBinContent (148, 837.8418)
hhfit_15 SetBinContent (149, 926.085)
hhfit_15 SetBinContent (150, 646.836)
hhfit_15 SetBinContent (151, 836.9824)
hhfit_15 SetBinContent (152, 790.7051)
hhfit_15 SetBinContent (153, 677.6414)
hhfit_15 SetBinContent (154, 776.032)
hhfit_15 SetBinContent (155, 940.8545)
hhfit_15 SetBinContent (156, 728.9438)
hhfit_15 SetBinContent (157, 810.101)
hhfit_15 SetBinContent (158, 774.1922)
hhfit_15 SetBinContent (159, 582.2378)
hhfit_15 SetBinContent (160, 617.4926)
hhfit_15 SetBinContent (161, 627.5197)
hhfit_15 SetBinContent (162, 666.2558)
hhfit_15 SetBinContent (163, 705.0713)
hhfit_15 SetBinContent (164, 701.8243)
hhfit_15 SetBinContent (165, 672.9092)
hhfit_15 SetBinContent (166, 573.3015)
hhfit_15 SetBinContent (167, 720.5971)
hhfit_15 SetBinContent (168, 580.0489)
hhfit_15 SetBinContent (169, 583.5997)
hhfit_15 SetBinContent (170, 589.9113)
hhfit_15 SetBinContent (171, 599.3915)
hhfit_15 SetBinContent (172, 536.2187)
hhfit_15 SetBinContent (173, 525.3632)
hhfit_15 SetBinContent (174, 551.6073)
hhfit_15 SetBinContent (175, 532.5635)
hhfit_15 SetBinContent (176, 643.6904)
hhfit_15 SetBinContent (177, 573.3071)
hhfit_15 SetBinContent (178, 602.6074)
hhfit_15 SetBinContent (179, 569.6708)
hhfit_15 SetBinContent (180, 545.4739)
hhfit_15 SetBinContent (181, 506.9003)
hhfit_15 SetBinContent (182, 655.749)
hhfit_15 SetBinContent (183, 609.7432)
hhfit_15 SetBinContent (184, 722.5366)
hhfit_15 SetBinContent (185, 794.7208)
hhfit_15 SetBinContent (186, 818.8311)
hhfit_15 SetBinContent (187, 970.3515)
hhfit_15 SetBinContent (188, 1329.72)
hhfit_15 SetBinContent (189, 1589.332)
hhfit_15 SetBinContent (190, 1490.547)
hhfit_15 SetBinContent (191, 1321.689)
hhfit_15 SetBinContent (192, 811.0498)
hhfit_15 SetBinContent (193, 569.8961)
hhfit_15 SetBinContent (194, 354.4673)
hhfit_15 SetBinContent (195, 322.9805)
hhfit_15 SetBinContent (196, 304.6322)
hhfit_15 SetBinContent (197, 305.5997)
hhfit_15 SetBinContent (198, 313.0439)
hhfit_15 SetBinContent (199, 368.1101)
hhfit_15 SetBinContent (200, 341.9297)
hhfit_15 SetBinContent (201, 324.6216)
hhfit_15 SetBinContent (202, 312.2936)
hhfit_15 SetBinContent (203, 292.0427)
hhfit_15 SetBinContent (204, 241.9572)
hhfit_15 SetBinContent (205, 243.1166)
hhfit_15 SetBinContent (206, 207.5929)
hhfit_15 SetBinContent (207, 256.4514)
hhfit_15 SetBinContent (208, 211.751)
hhfit_15 SetBinContent (209, 170.5449)
hhfit_15 SetBinContent (210, 223.8815)
hhfit_15 SetBinContent (211, 224.8044)
hhfit_15 SetBinContent (212, 201.353)
hhfit_15 SetBinContent (213, 168.5631)
hhfit_15 SetBinContent (214, 158.4669)
hhfit_15 SetBinContent (215, 163.0936)
hhfit_15 SetBinContent (216, 171.4698)
hhfit_15 SetBinContent (217, 178.6193)
hhfit_15 SetBinContent (218, 146.5637)
hhfit_15 SetBinContent (219, 127.3226)
hhfit_15 SetBinContent (220, 192.9137)
hhfit_15 SetBinContent (221, 130.353)
hhfit_15 SetBinContent (222, 157.655)
hhfit_15 SetBinContent (223, 154.8327)
hhfit_15 SetBinContent (224, 148.8981)
hhfit_15 SetBinContent (225, 121.8619)
hhfit_15 SetBinContent (226, 132.7337)
hhfit_15 SetBinContent (227, 133.5223)
hhfit_15 SetBinContent (228, 117.2357)
hhfit_15 SetBinContent (229, 125.8811)
hhfit_15 SetBinContent (230, 104.4648)
hhfit_15 SetBinContent (231, 124.9929)
hhfit_15 SetBinContent (232, 88.47062)
hhfit_15 SetBinContent (233, 114.9027)
hhfit_15 SetBinContent (234, 97.29363)
hhfit_15 SetBinContent (235, 98.64724)
hhfit_15 SetBinContent (236, 96.9671)
hhfit_15 SetBinContent (237, 115.2565)
hhfit_15 SetBinContent (238, 93.5182)
hhfit_15 SetBinContent (239, 118.755)
hhfit_15 SetBinContent (240, 88.96916)
hhfit_15 SetBinContent (241, 93.16291)
hhfit_15 SetBinContent (242, 106.3382)
hhfit_15 SetBinContent (243, 93.49672)
hhfit_15 SetBinContent (244, 94.64014)
hhfit_15 SetBinContent (245, 79.76988)
hhfit_15 SetBinContent (246, 68.88723)
hhfit_15 SetBinContent (247, 72.9934)
hhfit_15 SetBinContent (248, 62.08943)
hhfit_15 SetBinContent (249, 71.1763)
hhfit_15 SetBinContent (250, 78.25489)
hhfit_15 SetBinContent (251, 68.32597)
hhfit_15 SetBinContent (252, 73.39028)
hhfit_15 SetBinContent (253, 70.44845)
hhfit_15 SetBinContent (254, 62.50107)
hhfit_15 SetBinContent (255, 53.54867)
hhfit_15 SetBinContent (256, 49.59173)
hhfit_15 SetBinContent (257, 49.63068)
hhfit_15 SetBinContent (258, 67.66591)
hhfit_15 SetBinContent (259, 55.69779)
hhfit_15 SetBinContent (260, 44.72662)
hhfit_15 SetBinContent (261, 54.7527)
hhfit_15 SetBinContent (262, 53.77629)
hhfit_15 SetBinContent (263, 50.79764)
hhfit_15 SetBinContent (264, 43.81694)
hhfit_15 SetBinContent (265, 41.83441)
hhfit_15 SetBinContent (266, 41.85021)
hhfit_15 SetBinContent (267, 45.8645)
hhfit_15 SetBinContent (268, 35.87742)
hhfit_15 SetBinContent (269, 43.88912)
hhfit_15 SetBinContent (270, 42.8997)
hhfit_15 SetBinContent (271, 31.90927)
hhfit_15 SetBinContent (272, 36.91792)
hhfit_15 SetBinContent (273, 37.92575)
hhfit_15 SetBinContent (274, 33.93284)
hhfit_15 SetBinContent (275, 39.93924)
hhfit_15 SetBinContent (276, 30.94504)
hhfit_15 SetBinContent (277, 29.95028)
hhfit_15 SetBinContent (278, 31.95503)
hhfit_15 SetBinContent (279, 30.95932)
hhfit_15 SetBinContent (280,-0.03680116)
hhfit_15 SetBinContent (281,-0.03329018)
hhfit_15 SetBinContent (282,-0.03011416)
hhfit_15 SetBinContent (283,-0.02724115)
hhfit_15 SetBinContent (284,-0.02464223)
hhfit_15 SetBinContent (285,-0.02229126)
hhfit_15 SetBinContent (286,-0.02016459)
hhfit_15 SetBinContent (287,-0.0182408)
hhfit_15 SetBinContent (288,-0.01650056)
hhfit_15 SetBinContent (289,-0.01492634)
hhfit_15 SetBinContent (290,-0.0135023)
hhfit_15 SetBinContent (291,-0.01221413)
hhfit_15 SetBinContent (292,-0.01104885)
hhfit_15 SetBinContent (293,-0.009994747)
hhfit_15 SetBinContent (294,-0.009041207)
hhfit_15 SetBinContent (295,-0.00817864)
hhfit_15 SetBinContent (296,-0.007398364)
hhfit_15 SetBinContent (297,-0.00669253)
hhfit_15 SetBinContent (298,-0.006054036)
hhfit_15 SetBinContent (299,-0.005476456)
hhfit_15 SetBinContent (300,-0.00495398)
hhfit_15 SetBinContent (301,-0.00448135)
hhfit_15 SetBinContent (302,-0.004053811)
hhfit_15 SetBinContent (303,-0.003667061)
hhfit_15 SetBinContent (304,-0.003317209)
hhfit_15 SetBinContent (305,-0.003000734)
hhfit_15 SetBinContent (306,-0.002714451)
hhfit_15 SetBinContent (307,-0.002455482)
hhfit_15 SetBinContent (308,-0.002221219)
hhfit_15 SetBinContent (309,-0.002009306)
hhfit_15 SetBinContent (310,-0.00181761)
hhfit_15 SetBinContent (311,-0.001644202)
hhfit_15 SetBinContent (312,-0.001487339)
hhfit_15 SetBinContent (313,-0.001345441)
hhfit_15 SetBinContent (314,-0.00121708)
hhfit_15 SetBinContent (315,-0.001100966)
hhfit_15 SetBinContent (316,-0.0009959291)
hhfit_15 SetBinContent (317,-0.0009009135)
hhfit_15 SetBinContent (318,-0.0008149627)
hhfit_15 SetBinContent (319,-0.0007372119)
hhfit_15 SetBinContent (320,-0.0006668789)
hhfit_15 SetBinContent (321,-0.000603256)
hhfit_15 SetBinContent (322,-0.0005457029)
hhfit_15 SetBinContent (323,-0.0004936406)
hhfit_15 SetBinContent (324,-0.0004465453)
hhfit_15 SetBinContent (325,-0.0004039431)
hhfit_15 SetBinContent (326,-0.0003654053)
hhfit_15 SetBinContent (327,-0.0003305441)
hhfit_15 SetBinContent (328,-0.0002990089)
hhfit_15 SetBinContent (329,-0.0002704822)
hhfit_15 SetBinContent (330,-0.0002446771)
hhfit_15 SetBinContent (331,-0.0002213339)
hhfit_15 SetBinContent (332,-0.0002002178)
hhfit_15 SetBinContent (333,-0.0001811162)
hhfit_15 SetBinContent (334,-0.000163837)
hhfit_15 SetBinContent (335,-0.0001482063)
hhfit_15 SetBinContent (336,-0.0001340668)
hhfit_15 SetBinContent (337,-0.0001212763)
hhfit_15 SetBinContent (338,-0.000109706)
hhfit_15 SetBinContent (339,-9.923962e-05)
hhfit_15 SetBinContent (340,-8.977176e-05)
hhfit_15 SetBinContent (341,-8.120717e-05)
hhfit_15 SetBinContent (342,-7.345967e-05)
hhfit_15 SetBinContent (343,-6.645132e-05)
hhfit_15 SetBinContent (344,-6.01116e-05)
hhfit_15 SetBinContent (345,-5.437671e-05)
hhfit_15 SetBinContent (346,-4.918895e-05)
hhfit_15 SetBinContent (347,-4.449612e-05)
hhfit_15 SetBinContent (348,-4.025101e-05)
hhfit_15 SetBinContent (349,-3.64109e-05)
hhfit_15 SetBinContent (350,-3.293716e-05)
hhfit_15 SetBinContent (351,-2.979482e-05)
hhfit_15 SetBinContent (352,-2.695227e-05)
hhfit_15 SetBinContent (353,-2.438091e-05)
hhfit_15 SetBinContent (354,-2.205488e-05)
hhfit_15 SetBinContent (355,-1.995075e-05)
hhfit_15 SetBinContent (356,-1.804737e-05)
hhfit_15 SetBinContent (357,-1.632558e-05)
hhfit_15 SetBinContent (358,-1.476805e-05)
hhfit_15 SetBinContent (359,-1.335912e-05)
hhfit_15 SetBinContent (360,-1.20846e-05)
hhfit_15 SetBinContent (361,-1.093168e-05)
hhfit_15 SetBinContent (362,-9.888758e-06)
hhfit_15 SetBinContent (363,-8.94533e-06)
hhfit_15 SetBinContent (364,-8.091909e-06)
hhfit_15 SetBinContent (365,-7.319908e-06)
hhfit_15 SetBinContent (366,-6.621559e-06)
hhfit_15 SetBinContent (367,-5.989836e-06)
hhfit_15 SetBinContent (368,-5.418381e-06)
hhfit_15 SetBinContent (369,-4.901446e-06)
hhfit_15 SetBinContent (370,-4.433828e-06)
hhfit_15 SetBinContent (371,-4.010823e-06)
hhfit_15 SetBinContent (372,-3.628174e-06)
hhfit_15 SetBinContent (373,-3.282031e-06)
hhfit_15 SetBinContent (374,-2.968912e-06)
hhfit_15 SetBinContent (375,-2.685666e-06)
hhfit_15 SetBinContent (376,-2.429443e-06)
hhfit_15 SetBinContent (377,-2.197664e-06)
hhfit_15 SetBinContent (378,-1.987998e-06)
hhfit_15 SetBinContent (379,-1.798335e-06)
hhfit_15 SetBinContent (380,-1.626766e-06)
hhfit_15 SetBinContent (381,-1.471566e-06)
hhfit_15 SetBinContent (382,-1.331173e-06)
hhfit_15 SetBinContent (383,-1.204174e-06)
hhfit_15 SetBinContent (384,-1.089291e-06)
hhfit_15 SetBinContent (385,-9.853678e-07)
hhfit_15 SetBinContent (386,-8.913597e-07)
hhfit_15 SetBinContent (387,-8.063204e-07)
hhfit_15 SetBinContent (388,-7.293942e-07)
hhfit_15 SetBinContent (389,-6.59807e-07)
hhfit_15 SetBinContent (390,-5.968587e-07)
hhfit_15 SetBinContent (391,-5.39916e-07)
hhfit_15 SetBinContent (392,-4.884058e-07)
hhfit_15 SetBinContent (393,-4.418099e-07)
hhfit_15 SetBinContent (394,-3.996595e-07)
hhfit_15 SetBinContent (395,-3.615303e-07)
hhfit_15 SetBinContent (396,-3.270389e-07)
hhfit_15 SetBinContent (397,-2.95838e-07)
hhfit_15 SetBinContent (398,-2.676139e-07)
hhfit_15 SetBinContent (399,-2.420824e-07)
hhfit_15 SetBinContent (400,-2.189868e-07)
hhfit_15 SetBinContent (401, 485)
hhfit_15 SetBinError (1, 227776.5)
hhfit_15 SetBinError (2, 216638.8)
hhfit_15 SetBinError (3, 206045.7)
hhfit_15 SetBinError (4, 195970.6)
hhfit_15 SetBinError (5, 186388.1)
hhfit_15 SetBinError (6, 177274.2)
hhfit_15 SetBinError (7, 168605.9)
hhfit_15 SetBinError (8, 160361.5)
hhfit_15 SetBinError (9, 152520.2)
hhfit_15 SetBinError (10, 145062.4)
hhfit_15 SetBinError (11, 137969.2)
hhfit_15 SetBinError (12, 131222.8)
hhfit_15 SetBinError (13, 124806.4)
hhfit_15 SetBinError (14, 118703.7)
hhfit_15 SetBinError (15, 112899.3)
hhfit_15 SetBinError (16, 107378.8)
hhfit_15 SetBinError (17, 102128.3)
hhfit_15 SetBinError (18, 97134.46)
hhfit_15 SetBinError (19, 92384.83)
hhfit_15 SetBinError (20, 87867.44)
hhfit_15 SetBinError (21, 83570.94)
hhfit_15 SetBinError (22, 79484.53)
hhfit_15 SetBinError (23, 75597.94)
hhfit_15 SetBinError (24, 71901.39)
hhfit_15 SetBinError (25, 68385.59)
hhfit_15 SetBinError (26, 65041.7)
hhfit_15 SetBinError (27, 61861.32)
hhfit_15 SetBinError (28, 58836.46)
hhfit_15 SetBinError (29, 55959.5)
hhfit_15 SetBinError (30, 53223.22)
hhfit_15 SetBinError (31, 50620.74)
hhfit_15 SetBinError (32, 48145.51)
hhfit_15 SetBinError (33, 45791.32)
hhfit_15 SetBinError (34, 43552.23)
hhfit_15 SetBinError (35, 41422.64)
hhfit_15 SetBinError (36, 39397.17)
hhfit_15 SetBinError (37, 37470.75)
hhfit_15 SetBinError (38, 35638.52)
hhfit_15 SetBinError (39, 33895.89)
hhfit_15 SetBinError (40, 32238.46)
hhfit_15 SetBinError (41, 30662.08)
hhfit_15 SetBinError (42, 29162.78)
hhfit_15 SetBinError (43, 27736.8)
hhfit_15 SetBinError (44, 26380.54)
hhfit_15 SetBinError (45, 25090.59)
hhfit_15 SetBinError (46, 23863.73)
hhfit_15 SetBinError (47, 22696.85)
hhfit_15 SetBinError (48, 21587.03)
hhfit_15 SetBinError (49, 20531.48)
hhfit_15 SetBinError (50, 19527.54)
hhfit_15 SetBinError (51, 18572.69)
hhfit_15 SetBinError (52, 17664.53)
hhfit_15 SetBinError (53, 16800.78)
hhfit_15 SetBinError (54, 15979.27)
hhfit_15 SetBinError (55, 15197.92)
hhfit_15 SetBinError (56, 14454.78)
hhfit_15 SetBinError (57, 13747.98)
hhfit_15 SetBinError (58, 13075.73)
hhfit_15 SetBinError (59, 12436.36)
hhfit_15 SetBinError (60, 11828.26)
hhfit_15 SetBinError (61, 11249.88)
hhfit_15 SetBinError (62, 10699.79)
hhfit_15 SetBinError (63, 10176.6)
hhfit_15 SetBinError (64, 9678.989)
hhfit_15 SetBinError (65, 9205.711)
hhfit_15 SetBinError (66, 8755.574)
hhfit_15 SetBinError (67, 8327.448)
hhfit_15 SetBinError (68, 7920.257)
hhfit_15 SetBinError (69, 7532.976)
hhfit_15 SetBinError (70, 7164.632)
hhfit_15 SetBinError (71, 6814.3)
hhfit_15 SetBinError (72, 6481.097)
hhfit_15 SetBinError (73, 6164.188)
hhfit_15 SetBinError (74, 5862.774)
hhfit_15 SetBinError (75, 5576.099)
hhfit_15 SetBinError (76, 5303.442)
hhfit_15 SetBinError (77, 5044.117)
hhfit_15 SetBinError (78, 4797.472)
hhfit_15 SetBinError (79, 4562.888)
hhfit_15 SetBinError (80, 4339.774)
hhfit_15 SetBinError (81, 4127.57)
hhfit_15 SetBinError (82, 3925.742)
hhfit_15 SetBinError (83, 3733.783)
hhfit_15 SetBinError (84, 3551.21)
hhfit_15 SetBinError (85, 3377.565)
hhfit_15 SetBinError (86, 3212.41)
hhfit_15 SetBinError (87, 3055.331)
hhfit_15 SetBinError (88, 2905.933)
hhfit_15 SetBinError (89, 2763.84)
hhfit_15 SetBinError (90, 2628.695)
hhfit_15 SetBinError (91, 2500.159)
hhfit_15 SetBinError (92, 2377.907)
hhfit_15 SetBinError (93, 2261.633)
hhfit_15 SetBinError (94, 2151.045)
hhfit_15 SetBinError (95, 2045.864)
hhfit_15 SetBinError (96, 1945.827)
hhfit_15 SetBinError (97, 1850.681)
hhfit_15 SetBinError (98, 1760.187)
hhfit_15 SetBinError (99, 1674.118)
hhfit_15 SetBinError (100, 1592.258)
hhfit_15 SetBinError (101, 1514.408)
hhfit_15 SetBinError (102, 1440.36)
hhfit_15 SetBinError (103, 1369.925)
hhfit_15 SetBinError (104, 1302.943)
hhfit_15 SetBinError (105, 1239.234)
hhfit_15 SetBinError (106, 1178.639)
hhfit_15 SetBinError (107, 1121.008)
hhfit_15 SetBinError (108, 1066.194)
hhfit_15 SetBinError (109, 1014.06)
hhfit_15 SetBinError (110, 964.4804)
hhfit_15 SetBinError (111, 917.319)
hhfit_15 SetBinError (112, 872.4652)
hhfit_15 SetBinError (113, 829.81)
hhfit_15 SetBinError (114, 789.2281)
hhfit_15 SetBinError (115, 750.6473)
hhfit_15 SetBinError (116, 713.9504)
hhfit_15 SetBinError (117, 679.0325)
hhfit_15 SetBinError (118, 645.8308)
hhfit_15 SetBinError (119, 614.2557)
hhfit_15 SetBinError (120, 584.2122)
hhfit_15 SetBinError (121, 555.667)
hhfit_15 SetBinError (122, 528.4874)
hhfit_15 SetBinError (123, 502.6482)
hhfit_15 SetBinError (124, 478.0851)
hhfit_15 SetBinError (125, 454.7064)
hhfit_15 SetBinError (126, 432.4772)
hhfit_15 SetBinError (127, 411.3353)
hhfit_15 SetBinError (128, 391.2186)
hhfit_15 SetBinError (129, 372.0914)
hhfit_15 SetBinError (130, 353.8994)
hhfit_15 SetBinError (131, 336.6044)
hhfit_15 SetBinError (132, 320.1702)
hhfit_15 SetBinError (133, 304.515)
hhfit_15 SetBinError (134, 289.6195)
hhfit_15 SetBinError (135, 275.4744)
hhfit_15 SetBinError (136, 262.0077)
hhfit_15 SetBinError (137, 249.1611)
hhfit_15 SetBinError (138, 237.0379)
hhfit_15 SetBinError (139, 225.4343)
hhfit_15 SetBinError (140, 214.4301)
hhfit_15 SetBinError (141, 290.2916)
hhfit_15 SetBinError (142, 276.5489)
hhfit_15 SetBinError (143, 262.9175)
hhfit_15 SetBinError (144, 250.4559)
hhfit_15 SetBinError (145, 237.784)
hhfit_15 SetBinError (146, 226.5531)
hhfit_15 SetBinError (147, 215.7653)
hhfit_15 SetBinError (148, 205.0272)
hhfit_15 SetBinError (149, 195.4326)
hhfit_15 SetBinError (150, 185.3623)
hhfit_15 SetBinError (151, 177.0113)
hhfit_15 SetBinError (152, 168.4556)
hhfit_15 SetBinError (153, 160.1011)
hhfit_15 SetBinError (154, 152.807)
hhfit_15 SetBinError (155, 146.1545)
hhfit_15 SetBinError (156, 138.5679)
hhfit_15 SetBinError (157, 132.3628)
hhfit_15 SetBinError (158, 126.0548)
hhfit_15 SetBinError (159, 119.3975)
hhfit_15 SetBinError (160, 113.9584)
hhfit_15 SetBinError (161, 108.7036)
hhfit_15 SetBinError (162, 103.8641)
hhfit_15 SetBinError (163, 99.30221)
hhfit_15 SetBinError (164, 94.78489)
hhfit_15 SetBinError (165, 90.36089)
hhfit_15 SetBinError (166, 85.73621)
hhfit_15 SetBinError (167, 82.7732)
hhfit_15 SetBinError (168, 78.26846)
hhfit_15 SetBinError (169, 74.83582)
hhfit_15 SetBinError (170, 71.61067)
hhfit_15 SetBinError (171, 68.59015)
hhfit_15 SetBinError (172, 65.19035)
hhfit_15 SetBinError (173, 62.32685)
hhfit_15 SetBinError (174, 59.91989)
hhfit_15 SetBinError (175, 57.28382)
hhfit_15 SetBinError (176, 55.94917)
hhfit_15 SetBinError (177, 53.12902)
hhfit_15 SetBinError (178, 51.35555)
hhfit_15 SetBinError (179, 49.0951)
hhfit_15 SetBinError (180, 47.01623)
hhfit_15 SetBinError (181, 44.86758)
hhfit_15 SetBinError (182, 44.92495)
hhfit_15 SetBinError (183, 42.92152)
hhfit_15 SetBinError (184, 42.86564)
hhfit_15 SetBinError (185, 42.46503)
hhfit_15 SetBinError (186, 41.60732)
hhfit_15 SetBinError (187, 42.37509)
hhfit_15 SetBinError (188, 45.56622)
hhfit_15 SetBinError (189, 47.58853)
hhfit_15 SetBinError (190, 45.84161)
hhfit_15 SetBinError (191, 43.29332)
hhfit_15 SetBinError (192, 36.20705)
hhfit_15 SetBinError (193, 31.97036)
hhfit_15 SetBinError (194, 27.6321)
hhfit_15 SetBinError (195, 26.32526)
hhfit_15 SetBinError (196, 25.28572)
hhfit_15 SetBinError (197, 24.66577)
hhfit_15 SetBinError (198, 24.22718)
hhfit_15 SetBinError (199, 24.81713)
hhfit_15 SetBinError (200, 23.79223)
hhfit_15 SetBinError (201, 22.96472)
hhfit_15 SetBinError (202, 22.26447)
hhfit_15 SetBinError (203, 21.39994)
hhfit_15 SetBinError (204, 19.80007)
hhfit_15 SetBinError (205, 19.46493)
hhfit_15 SetBinError (206, 18.1771)
hhfit_15 SetBinError (207, 19.17156)
hhfit_15 SetBinError (208, 17.67057)
hhfit_15 SetBinError (209, 16.16957)
hhfit_15 SetBinError (210, 17.49624)
hhfit_15 SetBinError (211, 17.29727)
hhfit_15 SetBinError (212, 16.39045)
hhfit_15 SetBinError (213, 15.14718)
hhfit_15 SetBinError (214, 14.61277)
hhfit_15 SetBinError (215, 14.59131)
hhfit_15 SetBinError (216, 14.71496)
hhfit_15 SetBinError (217, 14.81151)
hhfit_15 SetBinError (218, 13.54387)
hhfit_15 SetBinError (219, 12.67586)
hhfit_15 SetBinError (220, 14.93607)
hhfit_15 SetBinError (221, 12.55576)
hhfit_15 SetBinError (222, 13.50352)
hhfit_15 SetBinError (223, 13.31042)
hhfit_15 SetBinError (224, 13.00392)
hhfit_15 SetBinError (225, 11.83799)
hhfit_15 SetBinError (226, 12.21746)
hhfit_15 SetBinError (227, 12.18514)
hhfit_15 SetBinError (228, 11.43522)
hhfit_15 SetBinError (229, 11.7524)
hhfit_15 SetBinError (230, 10.74873)
hhfit_15 SetBinError (231, 11.61925)
hhfit_15 SetBinError (232, 9.875697)
hhfit_15 SetBinError (233, 11.09492)
hhfit_15 SetBinError (234, 10.23261)
hhfit_15 SetBinError (235, 10.26415)
hhfit_15 SetBinError (236, 10.15051)
hhfit_15 SetBinError (237, 10.98834)
hhfit_15 SetBinError (238, 9.9238)
hhfit_15 SetBinError (239, 11.10158)
hhfit_15 SetBinError (240, 9.64525)
hhfit_15 SetBinError (241, 9.840584)
hhfit_15 SetBinError (242, 10.47195)
hhfit_15 SetBinError (243, 9.823608)
hhfit_15 SetBinError (244, 9.86711)
hhfit_15 SetBinError (245, 9.068083)
hhfit_15 SetBinError (246, 8.432839)
hhfit_15 SetBinError (247, 8.660635)
hhfit_15 SetBinError (248, 7.994409)
hhfit_15 SetBinError (249, 8.53368)
hhfit_15 SetBinError (250, 8.930012)
hhfit_15 SetBinError (251, 8.347097)
hhfit_15 SetBinError (252, 8.637692)
hhfit_15 SetBinError (253, 8.458815)
hhfit_15 SetBinError (254, 7.968622)
hhfit_15 SetBinError (255, 7.379115)
hhfit_15 SetBinError (256, 7.099878)
hhfit_15 SetBinError (257, 7.097135)
hhfit_15 SetBinError (258, 8.266443)
hhfit_15 SetBinError (259, 7.50348)
hhfit_15 SetBinError (260, 6.72855)
hhfit_15 SetBinError (261, 7.432853)
hhfit_15 SetBinError (262, 7.363675)
hhfit_15 SetBinError (263, 7.155583)
hhfit_15 SetBinError (264, 6.647034)
hhfit_15 SetBinError (265, 6.493504)
hhfit_15 SetBinError (266, 6.492287)
hhfit_15 SetBinError (267, 6.792312)
hhfit_15 SetBinError (268, 6.010206)
hhfit_15 SetBinError (269, 6.641602)
hhfit_15 SetBinError (270, 6.565082)
hhfit_15 SetBinError (271, 5.664868)
hhfit_15 SetBinError (272, 6.089506)
hhfit_15 SetBinError (273, 6.170433)
hhfit_15 SetBinError (274, 5.836708)
hhfit_15 SetBinError (275, 6.329357)
hhfit_15 SetBinError (276, 5.572698)
hhfit_15 SetBinError (277, 5.481762)
hhfit_15 SetBinError (278, 5.660828)
hhfit_15 SetBinError (279, 5.571417)
hhfit_15 SetBinError (280, 0.1918363)
hhfit_15 SetBinError (281, 0.182456)
hhfit_15 SetBinError (282, 0.1735343)
hhfit_15 SetBinError (283, 0.1650489)
hhfit_15 SetBinError (284, 0.1569784)
hhfit_15 SetBinError (285, 0.1493026)
hhfit_15 SetBinError (286, 0.1420021)
hhfit_15 SetBinError (287, 0.1350585)
hhfit_15 SetBinError (288, 0.1284545)
hhfit_15 SetBinError (289, 0.1221734)
hhfit_15 SetBinError (290, 0.1161994)
hhfit_15 SetBinError (291, 0.1105176)
hhfit_15 SetBinError (292, 0.1051135)
hhfit_15 SetBinError (293, 0.09997373)
hhfit_15 SetBinError (294, 0.09508526)
hhfit_15 SetBinError (295, 0.09043583)
hhfit_15 SetBinError (296, 0.08601374)
hhfit_15 SetBinError (297, 0.08180789)
hhfit_15 SetBinError (298, 0.07780768)
hhfit_15 SetBinError (299, 0.07400308)
hhfit_15 SetBinError (300, 0.07038452)
hhfit_15 SetBinError (301, 0.06694289)
hhfit_15 SetBinError (302, 0.06366955)
hhfit_15 SetBinError (303, 0.06055627)
hhfit_15 SetBinError (304, 0.05759521)
hhfit_15 SetBinError (305, 0.05477895)
hhfit_15 SetBinError (306, 0.0521004)
hhfit_15 SetBinError (307, 0.04955282)
hhfit_15 SetBinError (308, 0.04712981)
hhfit_15 SetBinError (309, 0.04482528)
hhfit_15 SetBinError (310, 0.04263343)
hhfit_15 SetBinError (311, 0.04054876)
hhfit_15 SetBinError (312, 0.03856603)
hhfit_15 SetBinError (313, 0.03668025)
hhfit_15 SetBinError (314, 0.03488668)
hhfit_15 SetBinError (315, 0.0331808)
hhfit_15 SetBinError (316, 0.03155835)
hhfit_15 SetBinError (317, 0.03001522)
hhfit_15 SetBinError (318, 0.02854755)
hhfit_15 SetBinError (319, 0.02715165)
hhfit_15 SetBinError (320, 0.025824)
hhfit_15 SetBinError (321, 0.02456127)
hhfit_15 SetBinError (322, 0.02336028)
hhfit_15 SetBinError (323, 0.02221802)
hhfit_15 SetBinError (324, 0.02113162)
hhfit_15 SetBinError (325, 0.02009834)
hhfit_15 SetBinError (326, 0.01911558)
hhfit_15 SetBinError (327, 0.01818087)
hhfit_15 SetBinError (328, 0.01729187)
hhfit_15 SetBinError (329, 0.01644634)
hhfit_15 SetBinError (330, 0.01564216)
hhfit_15 SetBinError (331, 0.0148773)
hhfit_15 SetBinError (332, 0.01414983)
hhfit_15 SetBinError (333, 0.01345794)
hhfit_15 SetBinError (334, 0.01279988)
hhfit_15 SetBinError (335, 0.012174)
hhfit_15 SetBinError (336, 0.01157872)
hhfit_15 SetBinError (337, 0.01101255)
hhfit_15 SetBinError (338, 0.01047406)
hhfit_15 SetBinError (339, 0.009961908)
hhfit_15 SetBinError (340, 0.009474796)
hhfit_15 SetBinError (341, 0.009011502)
hhfit_15 SetBinError (342, 0.008570862)
hhfit_15 SetBinError (343, 0.008151768)
hhfit_15 SetBinError (344, 0.007753167)
hhfit_15 SetBinError (345, 0.007374056)
hhfit_15 SetBinError (346, 0.007013483)
hhfit_15 SetBinError (347, 0.006670541)
hhfit_15 SetBinError (348, 0.006344369)
hhfit_15 SetBinError (349, 0.006034145)
hhfit_15 SetBinError (350, 0.00573909)
hhfit_15 SetBinError (351, 0.005458463)
hhfit_15 SetBinError (352, 0.005191558)
hhfit_15 SetBinError (353, 0.004937703)
hhfit_15 SetBinError (354, 0.004696262)
hhfit_15 SetBinError (355, 0.004466626)
hhfit_15 SetBinError (356, 0.00424822)
hhfit_15 SetBinError (357, 0.004040492)
hhfit_15 SetBinError (358, 0.003842922)
hhfit_15 SetBinError (359, 0.003655013)
hhfit_15 SetBinError (360, 0.003476292)
hhfit_15 SetBinError (361, 0.00330631)
hhfit_15 SetBinError (362, 0.003144639)
hhfit_15 SetBinError (363, 0.002990874)
hhfit_15 SetBinError (364, 0.002844628)
hhfit_15 SetBinError (365, 0.002705533)
hhfit_15 SetBinError (366, 0.002573239)
hhfit_15 SetBinError (367, 0.002447414)
hhfit_15 SetBinError (368, 0.002327742)
hhfit_15 SetBinError (369, 0.002213921)
hhfit_15 SetBinError (370, 0.002105666)
hhfit_15 SetBinError (371, 0.002002704)
hhfit_15 SetBinError (372, 0.001904777)
hhfit_15 SetBinError (373, 0.001811638)
hhfit_15 SetBinError (374, 0.001723053)
hhfit_15 SetBinError (375, 0.0016388)
hhfit_15 SetBinError (376, 0.001558667)
hhfit_15 SetBinError (377, 0.001482452)
hhfit_15 SetBinError (378, 0.001409964)
hhfit_15 SetBinError (379, 0.00134102)
hhfit_15 SetBinError (380, 0.001275448)
hhfit_15 SetBinError (381, 0.001213081)
hhfit_15 SetBinError (382, 0.001153765)
hhfit_15 SetBinError (383, 0.001097348)
hhfit_15 SetBinError (384, 0.001043691)
hhfit_15 SetBinError (385, 0.0009926569)
hhfit_15 SetBinError (386, 0.0009441185)
hhfit_15 SetBinError (387, 0.0008979534)
hhfit_15 SetBinError (388, 0.0008540458)
hhfit_15 SetBinError (389, 0.000812285)
hhfit_15 SetBinError (390, 0.0007725663)
hhfit_15 SetBinError (391, 0.0007347898)
hhfit_15 SetBinError (392, 0.0006988604)
hhfit_15 SetBinError (393, 0.0006646878)
hhfit_15 SetBinError (394, 0.0006321863)
hhfit_15 SetBinError (395, 0.0006012739)
hhfit_15 SetBinError (396, 0.0005718731)
hhfit_15 SetBinError (397, 0.00054391)
hhfit_15 SetBinError (398, 0.0005173141)
hhfit_15 SetBinError (399, 0.0004920187)
hhfit_15 SetBinError (400, 0.0004679602)
hhfit_15 SetBinError (401, 22.02272)
hhfit_15 SetEntries (1.50226e+08)
hhfit_15 SetStats (0)
fSandB SetRange (7, 14)
fSandB SetName ("fSandB")
fSandB SetTitle ("SandB_CBFunction")
fSandB SetSavedPoint (0, 1093.994)
fSandB SetSavedPoint (1, 1059.108)
fSandB SetSavedPoint (2, 1025.519)
fSandB SetSavedPoint (3, 993.1896)
fSandB SetSavedPoint (4, 962.0871)
fSandB SetSavedPoint (5, 932.1793)
fSandB SetSavedPoint (6, 903.4367)
fSandB SetSavedPoint (7, 875.8324)
fSandB SetSavedPoint (8, 849.342)
fSandB SetSavedPoint (9, 823.9441)
fSandB SetSavedPoint (10, 799.6205)
fSandB SetSavedPoint (11, 776.3565)
fSandB SetSavedPoint (12, 754.1414)
fSandB SetSavedPoint (13, 732.969)
fSandB SetSavedPoint (14, 712.8388)
fSandB SetSavedPoint (15, 693.7566)
fSandB SetSavedPoint (16, 675.7362)
fSandB SetSavedPoint (17, 658.801)
fSandB SetSavedPoint (18, 642.9868)
fSandB SetSavedPoint (19, 628.3451)
fSandB SetSavedPoint (20, 614.948)
fSandB SetSavedPoint (21, 602.8953)
fSandB SetSavedPoint (22, 592.3243)
fSandB SetSavedPoint (23, 583.4256)
fSandB SetSavedPoint (24, 576.466)
fSandB SetSavedPoint (25, 571.8265)
fSandB SetSavedPoint (26, 570.0644)
fSandB SetSavedPoint (27, 572.023)
fSandB SetSavedPoint (28, 579.0349)
fSandB SetSavedPoint (29, 593.3292)
fSandB SetSavedPoint (30, 618.9313)
fSandB SetSavedPoint (31, 663.9317)
fSandB SetSavedPoint (32, 747.3954)
fSandB SetSavedPoint (33, 927.8926)
fSandB SetSavedPoint (34, 1369.484)
fSandB SetSavedPoint (35, 1592.219)
fSandB SetSavedPoint (36, 1267.255)
fSandB SetSavedPoint (37, 746.1414)
fSandB SetSavedPoint (38, 425.9642)
fSandB SetSavedPoint (39, 319.6932)
fSandB SetSavedPoint (40, 299.7456)
fSandB SetSavedPoint (41, 305.0574)
fSandB SetSavedPoint (42, 334.9328)
fSandB SetSavedPoint (43, 348.3685)
fSandB SetSavedPoint (44, 315.6217)
fSandB SetSavedPoint (45, 266.0266)
fSandB SetSavedPoint (46, 235.6509)
fSandB SetSavedPoint (47, 228.3579)
fSandB SetSavedPoint (48, 221.5825)
fSandB SetSavedPoint (49, 206.835)
fSandB SetSavedPoint (50, 191.0306)
fSandB SetSavedPoint (51, 179.9124)
fSandB SetSavedPoint (52, 172.4525)
fSandB SetSavedPoint (53, 166.3374)
fSandB SetSavedPoint (54, 160.6255)
fSandB SetSavedPoint (55, 155.1289)
fSandB SetSavedPoint (56, 149.8215)
fSandB SetSavedPoint (57, 144.6957)
fSandB SetSavedPoint (58, 139.7453)
fSandB SetSavedPoint (59, 134.9642)
fSandB SetSavedPoint (60, 130.3468)
fSandB SetSavedPoint (61, 125.8873)
fSandB SetSavedPoint (62, 121.5804)
fSandB SetSavedPoint (63, 117.4208)
fSandB SetSavedPoint (64, 113.4035)
fSandB SetSavedPoint (65, 109.5237)
fSandB SetSavedPoint (66, 105.7766)
fSandB SetSavedPoint (67, 102.1577)
fSandB SetSavedPoint (68, 98.66267)
fSandB SetSavedPoint (69, 95.28718)
fSandB SetSavedPoint (70, 92.02716)
fSandB SetSavedPoint (71, 88.87868)
fSandB SetSavedPoint (72, 85.83792)
fSandB SetSavedPoint (73, 82.90119)
fSandB SetSavedPoint (74, 80.06493)
fSandB SetSavedPoint (75, 77.3257)
fSandB SetSavedPoint (76, 74.6802)
fSandB SetSavedPoint (77, 72.1252)
fSandB SetSavedPoint (78, 69.65761)
fSandB SetSavedPoint (79, 67.27445)
fSandB SetSavedPoint (80, 64.97282)
fSandB SetSavedPoint (81, 62.74994)
fSandB SetSavedPoint (82, 60.60311)
fSandB SetSavedPoint (83, 58.52972)
fSandB SetSavedPoint (84, 56.52727)
fSandB SetSavedPoint (85, 54.59333)
fSandB SetSavedPoint (86, 52.72556)
fSandB SetSavedPoint (87, 50.92168)
fSandB SetSavedPoint (88, 49.17952)
fSandB SetSavedPoint (89, 47.49697)
fSandB SetSavedPoint (90, 45.87198)
fSandB SetSavedPoint (91, 44.30258)
fSandB SetSavedPoint (92, 42.78688)
fSandB SetSavedPoint (93, 41.32303)
fSandB SetSavedPoint (94, 39.90927)
fSandB SetSavedPoint (95, 38.54387)
fSandB SetSavedPoint (96, 37.22519)
fSandB SetSavedPoint (97, 35.95162)
fSandB SetSavedPoint (98, 34.72162)
fSandB SetSavedPoint (99, 33.53371)
fSandB SetSavedPoint (100, 32.38644)
fSandB SetSavedPoint (101, 7)
fSandB SetSavedPoint (102, 14)
fSandB SetFillColor (19)
fSandB SetFillStyle (0)
fSandB SetMarkerStyle (20)
fSandB SetMarkerSize (1.2)
fSandB SetLineColor (ci)
fSandB SetLineWidth (3)
fSandB SetChisquare (29415.07)
fSandB SetNDF (134)
fSandB GetXaxis () -> SetLabelFont(42)
fSandB GetYaxis () -> SetLabelFont(42)
fSandB SetParameter (0, 1268.46)
fSandB SetParError (0, 17.99564)
fSandB SetParLimits (0, 0, 1000000)
fSandB SetParameter (1, 0.98)
fSandB SetParError (1, 0)
fSandB SetParLimits (1, 0.98, 0.98)
fSandB SetParameter (2, 0.93)
fSandB SetParError (2, 0)
fSandB SetParLimits (2, 0.93, 0.93)
fSandB SetParameter (3, 9.443952)
fSandB SetParError (3, 0.001998171)
fSandB SetParLimits (3, 9, 10)
fSandB SetParameter (4, 0.1)
fSandB SetParError (4, 0)
fSandB SetParLimits (4, 0.1, 0.1)
fSandB SetParameter (5, 108.148)
fSandB SetParError (5, 9.880456)
fSandB SetParLimits (5, 0, 1000000)
fSandB SetParameter (6, 24.05268)
fSandB SetParError (6, 8.311877)
fSandB SetParLimits (6, 0, 1000000)
fSandB SetParameter (7, 10.44003)
fSandB SetParError (7, 0.0295512)
fSandB SetParLimits (7, 0, 0)
fSandB SetParameter (8,-0.4973067)
fSandB SetParError (8, 0.003352394)
fSandB SetParLimits (8,-0.6, 0)
hhfit_15 GetListOfFunctions () -> Add(fSandB)
hhfit_15 SetLineWidth (2)
hhfit_15 GetZaxis () -> SetLabelFont(42)
hhfit_15 Draw ("")
fmycorrbg SetLineStyle (2)
fmycorrbg SetParameter (0, 10.4037)
fmycorrbg SetParError (0, 0)
fmycorrbg SetParLimits (0, 0, 0)
fmycorrbg SetParameter (1,-0.4926829)
fmycorrbg SetParLimits (1, 0, 0)
fmycorrbg Draw ("same")
fTCBfordave SetRange (5, 14)
fTCBfordave SetName ("fTCBfordave")
fTCBfordave SetSavedPoint (0, 2834.58)
fTCBfordave SetSavedPoint (1, 2713.273)
fTCBfordave SetSavedPoint (2, 2597.268)
fTCBfordave SetSavedPoint (3, 2486.337)
fTCBfordave SetSavedPoint (4, 2380.263)
fTCBfordave SetSavedPoint (5, 2278.836)
fTCBfordave SetSavedPoint (6, 2181.858)
fTCBfordave SetSavedPoint (7, 2089.139)
fTCBfordave SetSavedPoint (8, 2000.497)
fTCBfordave SetSavedPoint (9, 1915.758)
fTCBfordave SetSavedPoint (10, 1834.757)
fTCBfordave SetSavedPoint (11, 1757.335)
fTCBfordave SetSavedPoint (12, 1683.34)
fTCBfordave SetSavedPoint (13, 1612.63)
fTCBfordave SetSavedPoint (14, 1545.067)
fTCBfordave SetSavedPoint (15, 1480.519)
fTCBfordave SetSavedPoint (16, 1418.861)
fTCBfordave SetSavedPoint (17, 1359.976)
fTCBfordave SetSavedPoint (18, 1303.75)
fTCBfordave SetSavedPoint (19, 1250.077)
fTCBfordave SetSavedPoint (20, 1198.854)
fTCBfordave SetSavedPoint (21, 1149.987)
fTCBfordave SetSavedPoint (22, 1103.383)
fTCBfordave SetSavedPoint (23, 1058.96)
fTCBfordave SetSavedPoint (24, 1016.637)
fTCBfordave SetSavedPoint (25, 976.3398)
fTCBfordave SetSavedPoint (26, 938.0013)
fTCBfordave SetSavedPoint (27, 901.5593)
fTCBfordave SetSavedPoint (28, 866.9584)
fTCBfordave SetSavedPoint (29, 834.1501)
fTCBfordave SetSavedPoint (30, 803.0939)
fTCBfordave SetSavedPoint (31, 773.7583)
fTCBfordave SetSavedPoint (32, 746.1222)
fTCBfordave SetSavedPoint (33, 720.1769)
fTCBfordave SetSavedPoint (34, 695.9295)
fTCBfordave SetSavedPoint (35, 673.4068)
fTCBfordave SetSavedPoint (36, 652.6615)
fTCBfordave SetSavedPoint (37, 633.7811)
fTCBfordave SetSavedPoint (38, 616.902)
fTCBfordave SetSavedPoint (39, 602.2309)
fTCBfordave SetSavedPoint (40, 590.0801)
fTCBfordave SetSavedPoint (41, 580.9272)
fTCBfordave SetSavedPoint (42, 575.5234)
fTCBfordave SetSavedPoint (43, 575.1002)
fTCBfordave SetSavedPoint (44, 581.8044)
fTCBfordave SetSavedPoint (45, 599.719)
fTCBfordave SetSavedPoint (46, 637.6725)
fTCBfordave SetSavedPoint (47, 719.0518)
fTCBfordave SetSavedPoint (48, 934.0337)
fTCBfordave SetSavedPoint (49, 1542.987)
fTCBfordave SetSavedPoint (50, 1396.432)
fTCBfordave SetSavedPoint (51, 681.8101)
fTCBfordave SetSavedPoint (52, 390.0515)
fTCBfordave SetSavedPoint (53, 364.0826)
fTCBfordave SetSavedPoint (54, 397.7762)
fTCBfordave SetSavedPoint (55, 530.7048)
fTCBfordave SetSavedPoint (56, 561.6844)
fTCBfordave SetSavedPoint (57, 392.0961)
fTCBfordave SetSavedPoint (58, 315.6501)
fTCBfordave SetSavedPoint (59, 377.5301)
fTCBfordave SetSavedPoint (60, 336.5859)
fTCBfordave SetSavedPoint (61, 229.0872)
fTCBfordave SetSavedPoint (62, 184.0371)
fTCBfordave SetSavedPoint (63, 172.0421)
fTCBfordave SetSavedPoint (64, 164.4233)
fTCBfordave SetSavedPoint (65, 157.2897)
fTCBfordave SetSavedPoint (66, 150.4676)
fTCBfordave SetSavedPoint (67, 143.9414)
fTCBfordave SetSavedPoint (68, 137.6983)
fTCBfordave SetSavedPoint (69, 131.7259)
fTCBfordave SetSavedPoint (70, 126.0126)
fTCBfordave SetSavedPoint (71, 120.5471)
fTCBfordave SetSavedPoint (72, 115.3186)
fTCBfordave SetSavedPoint (73, 110.3169)
fTCBfordave SetSavedPoint (74, 105.5322)
fTCBfordave SetSavedPoint (75, 100.955)
fTCBfordave SetSavedPoint (76, 96.57626)
fTCBfordave SetSavedPoint (77, 92.38749)
fTCBfordave SetSavedPoint (78, 88.38039)
fTCBfordave SetSavedPoint (79, 84.54709)
fTCBfordave SetSavedPoint (80, 80.88005)
fTCBfordave SetSavedPoint (81, 77.37206)
fTCBfordave SetSavedPoint (82, 74.01622)
fTCBfordave SetSavedPoint (83, 70.80593)
fTCBfordave SetSavedPoint (84, 67.73488)
fTCBfordave SetSavedPoint (85, 64.79703)
fTCBfordave SetSavedPoint (86, 61.98661)
fTCBfordave SetSavedPoint (87, 59.29808)
fTCBfordave SetSavedPoint (88, 56.72616)
fTCBfordave SetSavedPoint (89, 54.26579)
fTCBfordave SetSavedPoint (90, 51.91213)
fTCBfordave SetSavedPoint (91, 49.66056)
fTCBfordave SetSavedPoint (92, 47.50664)
fTCBfordave SetSavedPoint (93, 45.44615)
fTCBfordave SetSavedPoint (94, 43.47503)
fTCBfordave SetSavedPoint (95, 41.58939)
fTCBfordave SetSavedPoint (96, 39.78555)
fTCBfordave SetSavedPoint (97, 38.05994)
fTCBfordave SetSavedPoint (98, 36.40917)
fTCBfordave SetSavedPoint (99, 34.83001)
fTCBfordave SetSavedPoint (100, 33.31933)
fTCBfordave SetSavedPoint (101, 5)
fTCBfordave SetParLimits (2, 0, 0)
fTCBfordave SetParError (3, 0)
fTCBfordave SetParLimits (3, 0, 0)
fTCBfordave SetParLimits (4, 0, 0)
fTCBfordave SetParameter (5, 314.7931)
fTCBfordave SetParError (5, 0)
fTCBfordave SetParLimits (5, 0, 0)
fTCBfordave SetParameter (6, 179.6679)
fTCBfordave SetParError (6, 0)
fTCBfordave SetParLimits (6, 0, 0)
fTCBfordave SetParError (7, 0)
fTCBfordave SetParError (8, 0)
fTCBfordave SetParLimits (8, 0, 0)
tex SetTextFont (42)
tex SetTextSize (0.035)
tex Draw ()
cfitall Modified ()
cfitall cd ()
cfitall SetSelected (cfitall)
Variables
TCanvas * cfitall = new TCanvas("cfitall", "FIT all pT",272,51,800,640)
TH1D * hhfit_15 = new TH1D("hhfit_15","",400,0,20)
TF1 * fSandB = new TF1("*fSandB",7,14,9)
Int_t ci = TColor::GetColor("#ff0000")
TColor * color
TF1 * fmycorrbg = new TF1("fmycorrbg","exp([0]+[1]*x)",7,14)
TF1 * fTCBfordave = new TF1("*fTCBfordave",5,14,9)
TLatex * tex = new TLatex(10.1,1141.614,"sPHENIX Simulation")
Function Documentation
cfitall cd ()
hhfit_15 Draw ("")
fmycorrbg Draw ("same")
tex Draw ()
hhfit_15 GetListOfFunctions () -> Add(fSandB)
fSandB GetXaxis () -> SetLabelFont(42)
Definition at line 45 of file 200pp_pythia8_CTEQ6L_7GeV_ALL.cfg_eneg_DSTReader.root_Draw_HFJetTruth_CrossSection2RAA.C.
View newest version in sPHENIX GitHub at line 45 of file 200pp_pythia8_CTEQ6L_7GeV_ALL.cfg_eneg_DSTReader.root_Draw_HFJetTruth_CrossSection2RAA.C
fSandB GetYaxis () -> SetLabelFont(42)
Definition at line 51 of file 200pp_pythia8_CTEQ6L_7GeV_ALL.cfg_eneg_DSTReader.root_Draw_HFJetTruth_CrossSection2RAA.C.
View newest version in sPHENIX GitHub at line 51 of file 200pp_pythia8_CTEQ6L_7GeV_ALL.cfg_eneg_DSTReader.root_Draw_HFJetTruth_CrossSection2RAA.C
hhfit_15 GetZaxis () -> SetLabelFont(42)
cfitall Modified ()
cfitall Range (5. 572152, -447. 647, 14. 4962, 1837. 109)
hhfit_15 SetBinContent (1 , -5.188214e+ 10)
hhfit_15 SetBinContent (2 , -4.693237e+ 10)
hhfit_15 SetBinContent (3 , -4.245483e+ 10)
hhfit_15 SetBinContent (4 , -3.840447e+ 10)
hhfit_15 SetBinContent (5 , -3.474053e+ 10)
hhfit_15 SetBinContent (6 , -3.142614e+ 10)
hhfit_15 SetBinContent (7 , -2.842796e+ 10)
hhfit_15 SetBinContent (8 , -2.571582e+ 10)
hhfit_15 SetBinContent (9 , -2.326242e+ 10)
hhfit_15 SetBinContent (10 , -2.104309e+ 10)
hhfit_15 SetBinContent (11 , -1.90355e+ 10)
hhfit_15 SetBinContent (12 , -1.721943e+ 10)
hhfit_15 SetBinContent (13 , -1.557663e+ 10)
hhfit_15 SetBinContent (14 , -1.409056e+ 10)
hhfit_15 SetBinContent (15 , -1.274626e+ 10)
hhfit_15 SetBinContent (16 , -1.153022e+ 10)
hhfit_15 SetBinContent (17 , -1.043019e+ 10)
hhfit_15 SetBinContent (18 , -9.435104e+ 09)
hhfit_15 SetBinContent (19 , -8.534957e+ 09)
hhfit_15 SetBinContent (20 , -7.720688e+ 09)
hhfit_15 SetBinContent (21 , -6.984103e+ 09)
hhfit_15 SetBinContent (22 , -6.317791e+ 09)
hhfit_15 SetBinContent (23 , -5.715048e+ 09)
hhfit_15 SetBinContent (24 , -5.169809e+ 09)
hhfit_15 SetBinContent (25 , -4.676589e+ 09)
hhfit_15 SetBinContent (26 , -4.230423e+ 09)
hhfit_15 SetBinContent (27 , -3.826823e+ 09)
hhfit_15 SetBinContent (28 , -3.461729e+ 09)
hhfit_15 SetBinContent (29 , -3.131466e+ 09)
hhfit_15 SetBinContent (30 , -2.832711e+ 09)
hhfit_15 SetBinContent (31 , -2.562459e+ 09)
hhfit_15 SetBinContent (32 , -2.31799e+ 09)
hhfit_15 SetBinContent (33 , -2.096845e+ 09)
hhfit_15 SetBinContent (34 , -1.896797e+ 09)
hhfit_15 SetBinContent (35 , -1.715835e+ 09)
hhfit_15 SetBinContent (36 , -1.552137e+ 09)
hhfit_15 SetBinContent (37 , -1.404057e+ 09)
hhfit_15 SetBinContent (38 , -1.270104e+ 09)
hhfit_15 SetBinContent (39 , -1.148931e+ 09)
hhfit_15 SetBinContent (40 , -1.039319e+ 09)
hhfit_15 SetBinContent (41 , -9.401634e+ 08)
hhfit_15 SetBinContent (42 , -8.50468e+ 08)
hhfit_15 SetBinContent (43 , -7.693299e+ 08)
hhfit_15 SetBinContent (44 , -6.959327e+ 08)
hhfit_15 SetBinContent (45 , -6.295379e+ 08)
hhfit_15 SetBinContent (46 , -5.694774e+ 08)
hhfit_15 SetBinContent (47 , -5.15147e+ 08)
hhfit_15 SetBinContent (48 , -4.659999e+ 08)
hhfit_15 SetBinContent (49 , -4.215416e+ 08)
hhfit_15 SetBinContent (50 , -3.813248e+ 08)
hhfit_15 SetBinContent (51 , -3.449449e+ 08)
hhfit_15 SetBinContent (52 , -3.120357e+ 08)
hhfit_15 SetBinContent (53 , -2.822663e+ 08)
hhfit_15 SetBinContent (54 , -2.553369e+ 08)
hhfit_15 SetBinContent (55 , -2.309767e+ 08)
hhfit_15 SetBinContent (56 , -2.089406e+ 08)
hhfit_15 SetBinContent (57 , -1.890068e+ 08)
hhfit_15 SetBinContent (58 , -1.709748e+ 08)
hhfit_15 SetBinContent (59 , -1.546631e+ 08)
hhfit_15 SetBinContent (60 , -1.399076e+ 08)
hhfit_15 SetBinContent (61 , -1.265599e+ 08)
hhfit_15 SetBinContent (62 , -1.144856e+ 08)
hhfit_15 SetBinContent (63 , -1.035632e+ 08)
hhfit_15 SetBinContent (64 , -9.368283e+ 07)
hhfit_15 SetBinContent (65 , -8.474511e+ 07)
hhfit_15 SetBinContent (66 , -7.666008e+ 07)
hhfit_15 SetBinContent (67 , -6.93464e+ 07)
hhfit_15 SetBinContent (68 , -6.273047e+ 07)
hhfit_15 SetBinContent (69 , -5.674573e+ 07)
hhfit_15 SetBinContent (70 , -5.133196e+ 07)
hhfit_15 SetBinContent (71 , -4.643468e+ 07)
hhfit_15 SetBinContent (72 , -4.200462e+ 07)
hhfit_15 SetBinContent (73 , -3.799721e+ 07)
hhfit_15 SetBinContent (74 , -3.437212e+ 07)
hhfit_15 SetBinContent (75 , -3.109288e+ 07)
hhfit_15 SetBinContent (76 , -2.81265e+ 07)
hhfit_15 SetBinContent (77 , -2.544311e+ 07)
hhfit_15 SetBinContent (78 , -2.301574e+ 07)
hhfit_15 SetBinContent (79 , -2.081994e+ 07)
hhfit_15 SetBinContent (80 , -1.883364e+ 07)
hhfit_15 SetBinContent (81 , -1.703683e+ 07)
hhfit_15 SetBinContent (82 , -1.541145e+ 07)
hhfit_15 SetBinContent (83 , -1.394113e+ 07)
hhfit_15 SetBinContent (84 , -1.261109e+ 07)
hhfit_15 SetBinContent (85 , -1.140794e+ 07)
hhfit_15 SetBinContent (86 , -1.031958e+ 07)
hhfit_15 SetBinContent (87 , - 9335050)
hhfit_15 SetBinContent (88 , - 8444448)
hhfit_15 SetBinContent (89 , - 7638814)
hhfit_15 SetBinContent (90 , - 6910040)
hhfit_15 SetBinContent (91 , - 6250794)
hhfit_15 SetBinContent (92 , - 5654443)
hhfit_15 SetBinContent (93 , - 5114986)
hhfit_15 SetBinContent (94 , - 4626996)
hhfit_15 SetBinContent (95 , - 4185562)
hhfit_15 SetBinContent (96 , - 3786242)
hhfit_15 SetBinContent (97 , - 3425019)
hhfit_15 SetBinContent (98 , - 3098258)
hhfit_15 SetBinContent (99 , - 2802672)
hhfit_15 SetBinContent (100 , - 2535286)
hhfit_15 SetBinContent (101 , - 2293386)
hhfit_15 SetBinContent (102 , - 2074582)
hhfit_15 SetBinContent (103 , - 1876671)
hhfit_15 SetBinContent (104 , - 1697619)
hhfit_15 SetBinContent (105 , - 1535656)
hhfit_15 SetBinContent (106 , - 1389145)
hhfit_15 SetBinContent (107 , - 1256613)
hhfit_15 SetBinContent (108 , - 1136725)
hhfit_15 SetBinContent (109 , - 1028277)
hhfit_15 SetBinContent (110 , -930164. 5)
hhfit_15 SetBinContent (111 , -841424. 2)
hhfit_15 SetBinContent (112 , -761147. 6)
hhfit_15 SetBinContent (113 , -688520. 7)
hhfit_15 SetBinContent (114 , - 622843)
hhfit_15 SetBinContent (115 , -563405. 4)
hhfit_15 SetBinContent (116 , -509643. 1)
hhfit_15 SetBinContent (117 , -461031. 2)
hhfit_15 SetBinContent (118 , -417045. 4)
hhfit_15 SetBinContent (119 , -377252. 1)
hhfit_15 SetBinContent (120 , -341269. 9)
hhfit_15 SetBinContent (121 , -308687. 8)
hhfit_15 SetBinContent (122 , - 279247)
hhfit_15 SetBinContent (123 , -252603. 2)
hhfit_15 SetBinContent (124 , -228489. 4)
hhfit_15 SetBinContent (125 , -206691. 9)
hhfit_15 SetBinContent (126 , -186968. 5)
hhfit_15 SetBinContent (127 , -169126. 7)
hhfit_15 SetBinContent (128 , - 152994)
hhfit_15 SetBinContent (129 , - 138396)
hhfit_15 SetBinContent (130 , -125190. 8)
hhfit_15 SetBinContent (131 , -113240. 5)
hhfit_15 SetBinContent (132 , -102420. 9)
hhfit_15 SetBinContent (133 , -92649. 37)
hhfit_15 SetBinContent (134 , -83813. 43)
hhfit_15 SetBinContent (135 , -75808. 14)
hhfit_15 SetBinContent (136 , -68574. 01)
hhfit_15 SetBinContent (137 , -62049. 24)
hhfit_15 SetBinContent (138 , -56100. 97)
hhfit_15 SetBinContent (139 , -50754. 61)
hhfit_15 SetBinContent (140 , -45904. 26)
hhfit_15 SetBinContent (141 , 1150. 816)
hhfit_15 SetBinContent (142 , 1290. 73)
hhfit_15 SetBinContent (143 , 1110. 376)
hhfit_15 SetBinContent (144 , 1201. 841)
hhfit_15 SetBinContent (145 , 884. 7713)
hhfit_15 SetBinContent (146 , 979. 6972)
hhfit_15 SetBinContent (147 , 1011. 332)
hhfit_15 SetBinContent (148 , 837. 8418)
hhfit_15 SetBinContent (149 , 926. 085)
hhfit_15 SetBinContent (150 , 646. 836)
hhfit_15 SetBinContent (151 , 836. 9824)
hhfit_15 SetBinContent (152 , 790. 7051)
hhfit_15 SetBinContent (153 , 677. 6414)
hhfit_15 SetBinContent (154 , 776. 032)
hhfit_15 SetBinContent (155 , 940. 8545)
hhfit_15 SetBinContent (156 , 728. 9438)
hhfit_15 SetBinContent (157 , 810. 101)
hhfit_15 SetBinContent (158 , 774. 1922)
hhfit_15 SetBinContent (159 , 582. 2378)
hhfit_15 SetBinContent (160 , 617. 4926)
hhfit_15 SetBinContent (161 , 627. 5197)
hhfit_15 SetBinContent (162 , 666. 2558)
hhfit_15 SetBinContent (163 , 705. 0713)
hhfit_15 SetBinContent (164 , 701. 8243)
hhfit_15 SetBinContent (165 , 672. 9092)
hhfit_15 SetBinContent (166 , 573. 3015)
hhfit_15 SetBinContent (167 , 720. 5971)
hhfit_15 SetBinContent (168 , 580. 0489)
hhfit_15 SetBinContent (169 , 583. 5997)
hhfit_15 SetBinContent (170 , 589. 9113)
hhfit_15 SetBinContent (171 , 599. 3915)
hhfit_15 SetBinContent (172 , 536. 2187)
hhfit_15 SetBinContent (173 , 525. 3632)
hhfit_15 SetBinContent (174 , 551. 6073)
hhfit_15 SetBinContent (175 , 532. 5635)
hhfit_15 SetBinContent (176 , 643. 6904)
hhfit_15 SetBinContent (177 , 573. 3071)
hhfit_15 SetBinContent (178 , 602. 6074)
hhfit_15 SetBinContent (179 , 569. 6708)
hhfit_15 SetBinContent (180 , 545. 4739)
hhfit_15 SetBinContent (181 , 506. 9003)
hhfit_15 SetBinContent (182 , 655. 749)
hhfit_15 SetBinContent (183 , 609. 7432)
hhfit_15 SetBinContent (184 , 722. 5366)
hhfit_15 SetBinContent (185 , 794. 7208)
hhfit_15 SetBinContent (186 , 818. 8311)
hhfit_15 SetBinContent (187 , 970. 3515)
hhfit_15 SetBinContent (188 , 1329. 72)
hhfit_15 SetBinContent (189 , 1589. 332)
hhfit_15 SetBinContent (190 , 1490. 547)
hhfit_15 SetBinContent (191 , 1321. 689)
hhfit_15 SetBinContent (192 , 811. 0498)
hhfit_15 SetBinContent (193 , 569. 8961)
hhfit_15 SetBinContent (194 , 354. 4673)
hhfit_15 SetBinContent (195 , 322. 9805)
hhfit_15 SetBinContent (196 , 304. 6322)
hhfit_15 SetBinContent (197 , 305. 5997)
hhfit_15 SetBinContent (198 , 313. 0439)
hhfit_15 SetBinContent (199 , 368. 1101)
hhfit_15 SetBinContent (200 , 341. 9297)
hhfit_15 SetBinContent (201 , 324. 6216)
hhfit_15 SetBinContent (202 , 312. 2936)
hhfit_15 SetBinContent (203 , 292. 0427)
hhfit_15 SetBinContent (204 , 241. 9572)
hhfit_15 SetBinContent (205 , 243. 1166)
hhfit_15 SetBinContent (206 , 207. 5929)
hhfit_15 SetBinContent (207 , 256. 4514)
hhfit_15 SetBinContent (208 , 211. 751)
hhfit_15 SetBinContent (209 , 170. 5449)
hhfit_15 SetBinContent (210 , 223. 8815)
hhfit_15 SetBinContent (211 , 224. 8044)
hhfit_15 SetBinContent (212 , 201. 353)
hhfit_15 SetBinContent (213 , 168. 5631)
hhfit_15 SetBinContent (214 , 158. 4669)
hhfit_15 SetBinContent (215 , 163. 0936)
hhfit_15 SetBinContent (216 , 171. 4698)
hhfit_15 SetBinContent (217 , 178. 6193)
hhfit_15 SetBinContent (218 , 146. 5637)
hhfit_15 SetBinContent (219 , 127. 3226)
hhfit_15 SetBinContent (220 , 192. 9137)
hhfit_15 SetBinContent (221 , 130. 353)
hhfit_15 SetBinContent (222 , 157. 655)
hhfit_15 SetBinContent (223 , 154. 8327)
hhfit_15 SetBinContent (224 , 148. 8981)
hhfit_15 SetBinContent (225 , 121. 8619)
hhfit_15 SetBinContent (226 , 132. 7337)
hhfit_15 SetBinContent (227 , 133. 5223)
hhfit_15 SetBinContent (228 , 117. 2357)
hhfit_15 SetBinContent (229 , 125. 8811)
hhfit_15 SetBinContent (230 , 104. 4648)
hhfit_15 SetBinContent (231 , 124. 9929)
hhfit_15 SetBinContent (232 , 88. 47062)
hhfit_15 SetBinContent (233 , 114. 9027)
hhfit_15 SetBinContent (234 , 97. 29363)
hhfit_15 SetBinContent (235 , 98. 64724)
hhfit_15 SetBinContent (236 , 96. 9671)
hhfit_15 SetBinContent (237 , 115. 2565)
hhfit_15 SetBinContent (238 , 93. 5182)
hhfit_15 SetBinContent (239 , 118. 755)
hhfit_15 SetBinContent (240 , 88. 96916)
hhfit_15 SetBinContent (241 , 93. 16291)
hhfit_15 SetBinContent (242 , 106. 3382)
hhfit_15 SetBinContent (243 , 93. 49672)
hhfit_15 SetBinContent (244 , 94. 64014)
hhfit_15 SetBinContent (245 , 79. 76988)
hhfit_15 SetBinContent (246 , 68. 88723)
hhfit_15 SetBinContent (247 , 72. 9934)
hhfit_15 SetBinContent (248 , 62. 08943)
hhfit_15 SetBinContent (249 , 71. 1763)
hhfit_15 SetBinContent (250 , 78. 25489)
hhfit_15 SetBinContent (251 , 68. 32597)
hhfit_15 SetBinContent (252 , 73. 39028)
hhfit_15 SetBinContent (253 , 70. 44845)
hhfit_15 SetBinContent (254 , 62. 50107)
hhfit_15 SetBinContent (255 , 53. 54867)
hhfit_15 SetBinContent (256 , 49. 59173)
hhfit_15 SetBinContent (257 , 49. 63068)
hhfit_15 SetBinContent (258 , 67. 66591)
hhfit_15 SetBinContent (259 , 55. 69779)
hhfit_15 SetBinContent (260 , 44. 72662)
hhfit_15 SetBinContent (261 , 54. 7527)
hhfit_15 SetBinContent (262 , 53. 77629)
hhfit_15 SetBinContent (263 , 50. 79764)
hhfit_15 SetBinContent (264 , 43. 81694)
hhfit_15 SetBinContent (265 , 41. 83441)
hhfit_15 SetBinContent (266 , 41. 85021)
hhfit_15 SetBinContent (267 , 45. 8645)
hhfit_15 SetBinContent (268 , 35. 87742)
hhfit_15 SetBinContent (269 , 43. 88912)
hhfit_15 SetBinContent (270 , 42. 8997)
hhfit_15 SetBinContent (271 , 31. 90927)
hhfit_15 SetBinContent (272 , 36. 91792)
hhfit_15 SetBinContent (273 , 37. 92575)
hhfit_15 SetBinContent (274 , 33. 93284)
hhfit_15 SetBinContent (275 , 39. 93924)
hhfit_15 SetBinContent (276 , 30. 94504)
hhfit_15 SetBinContent (277 , 29. 95028)
hhfit_15 SetBinContent (278 , 31. 95503)
hhfit_15 SetBinContent (279 , 30. 95932)
hhfit_15 SetBinContent (280 , -0. 03680116)
hhfit_15 SetBinContent (281 , -0. 03329018)
hhfit_15 SetBinContent (282 , -0. 03011416)
hhfit_15 SetBinContent (283 , -0. 02724115)
hhfit_15 SetBinContent (284 , -0. 02464223)
hhfit_15 SetBinContent (285 , -0. 02229126)
hhfit_15 SetBinContent (286 , -0. 02016459)
hhfit_15 SetBinContent (287 , -0. 0182408)
hhfit_15 SetBinContent (288 , -0. 01650056)
hhfit_15 SetBinContent (289 , -0. 01492634)
hhfit_15 SetBinContent (290 , -0. 0135023)
hhfit_15 SetBinContent (291 , -0. 01221413)
hhfit_15 SetBinContent (292 , -0. 01104885)
hhfit_15 SetBinContent (293 , -0. 009994747)
hhfit_15 SetBinContent (294 , -0. 009041207)
hhfit_15 SetBinContent (295 , -0. 00817864)
hhfit_15 SetBinContent (296 , -0. 007398364)
hhfit_15 SetBinContent (297 , -0. 00669253)
hhfit_15 SetBinContent (298 , -0. 006054036)
hhfit_15 SetBinContent (299 , -0. 005476456)
hhfit_15 SetBinContent (300 , -0. 00495398)
hhfit_15 SetBinContent (301 , -0. 00448135)
hhfit_15 SetBinContent (302 , -0. 004053811)
hhfit_15 SetBinContent (303 , -0. 003667061)
hhfit_15 SetBinContent (304 , -0. 003317209)
hhfit_15 SetBinContent (305 , -0. 003000734)
hhfit_15 SetBinContent (306 , -0. 002714451)
hhfit_15 SetBinContent (307 , -0. 002455482)
hhfit_15 SetBinContent (308 , -0. 002221219)
hhfit_15 SetBinContent (309 , -0. 002009306)
hhfit_15 SetBinContent (310 , -0. 00181761)
hhfit_15 SetBinContent (311 , -0. 001644202)
hhfit_15 SetBinContent (312 , -0. 001487339)
hhfit_15 SetBinContent (313 , -0. 001345441)
hhfit_15 SetBinContent (314 , -0. 00121708)
hhfit_15 SetBinContent (315 , -0. 001100966)
hhfit_15 SetBinContent (316 , -0. 0009959291)
hhfit_15 SetBinContent (317 , -0. 0009009135)
hhfit_15 SetBinContent (318 , -0. 0008149627)
hhfit_15 SetBinContent (319 , -0. 0007372119)
hhfit_15 SetBinContent (320 , -0. 0006668789)
hhfit_15 SetBinContent (321 , -0. 000603256)
hhfit_15 SetBinContent (322 , -0. 0005457029)
hhfit_15 SetBinContent (323 , -0. 0004936406)
hhfit_15 SetBinContent (324 , -0. 0004465453)
hhfit_15 SetBinContent (325 , -0. 0004039431)
hhfit_15 SetBinContent (326 , -0. 0003654053)
hhfit_15 SetBinContent (327 , -0. 0003305441)
hhfit_15 SetBinContent (328 , -0. 0002990089)
hhfit_15 SetBinContent (329 , -0. 0002704822)
hhfit_15 SetBinContent (330 , -0. 0002446771)
hhfit_15 SetBinContent (331 , -0. 0002213339)
hhfit_15 SetBinContent (332 , -0. 0002002178)
hhfit_15 SetBinContent (333 , -0. 0001811162)
hhfit_15 SetBinContent (334 , -0. 000163837)
hhfit_15 SetBinContent (335 , -0. 0001482063)
hhfit_15 SetBinContent (336 , -0. 0001340668)
hhfit_15 SetBinContent (337 , -0. 0001212763)
hhfit_15 SetBinContent (338 , -0. 000109706)
hhfit_15 SetBinContent (339 , -9.923962e- 05)
hhfit_15 SetBinContent (340 , -8.977176e- 05)
hhfit_15 SetBinContent (341 , -8.120717e- 05)
hhfit_15 SetBinContent (342 , -7.345967e- 05)
hhfit_15 SetBinContent (343 , -6.645132e- 05)
hhfit_15 SetBinContent (344 , -6.01116e- 05)
hhfit_15 SetBinContent (345 , -5.437671e- 05)
hhfit_15 SetBinContent (346 , -4.918895e- 05)
hhfit_15 SetBinContent (347 , -4.449612e- 05)
hhfit_15 SetBinContent (348 , -4.025101e- 05)
hhfit_15 SetBinContent (349 , -3.64109e- 05)
hhfit_15 SetBinContent (350 , -3.293716e- 05)
hhfit_15 SetBinContent (351 , -2.979482e- 05)
hhfit_15 SetBinContent (352 , -2.695227e- 05)
hhfit_15 SetBinContent (353 , -2.438091e- 05)
hhfit_15 SetBinContent (354 , -2.205488e- 05)
hhfit_15 SetBinContent (355 , -1.995075e- 05)
hhfit_15 SetBinContent (356 , -1.804737e- 05)
hhfit_15 SetBinContent (357 , -1.632558e- 05)
hhfit_15 SetBinContent (358 , -1.476805e- 05)
hhfit_15 SetBinContent (359 , -1.335912e- 05)
hhfit_15 SetBinContent (360 , -1.20846e- 05)
hhfit_15 SetBinContent (361 , -1.093168e- 05)
hhfit_15 SetBinContent (362 , -9.888758e- 06)
hhfit_15 SetBinContent (363 , -8.94533e- 06)
hhfit_15 SetBinContent (364 , -8.091909e- 06)
hhfit_15 SetBinContent (365 , -7.319908e- 06)
hhfit_15 SetBinContent (366 , -6.621559e- 06)
hhfit_15 SetBinContent (367 , -5.989836e- 06)
hhfit_15 SetBinContent (368 , -5.418381e- 06)
hhfit_15 SetBinContent (369 , -4.901446e- 06)
hhfit_15 SetBinContent (370 , -4.433828e- 06)
hhfit_15 SetBinContent (371 , -4.010823e- 06)
hhfit_15 SetBinContent (372 , -3.628174e- 06)
hhfit_15 SetBinContent (373 , -3.282031e- 06)
hhfit_15 SetBinContent (374 , -2.968912e- 06)
hhfit_15 SetBinContent (375 , -2.685666e- 06)
hhfit_15 SetBinContent (376 , -2.429443e- 06)
hhfit_15 SetBinContent (377 , -2.197664e- 06)
hhfit_15 SetBinContent (378 , -1.987998e- 06)
hhfit_15 SetBinContent (379 , -1.798335e- 06)
hhfit_15 SetBinContent (380 , -1.626766e- 06)
hhfit_15 SetBinContent (381 , -1.471566e- 06)
hhfit_15 SetBinContent (382 , -1.331173e- 06)
hhfit_15 SetBinContent (383 , -1.204174e- 06)
hhfit_15 SetBinContent (384 , -1.089291e- 06)
hhfit_15 SetBinContent (385 , -9.853678e- 07)
hhfit_15 SetBinContent (386 , -8.913597e- 07)
hhfit_15 SetBinContent (387 , -8.063204e- 07)
hhfit_15 SetBinContent (388 , -7.293942e- 07)
hhfit_15 SetBinContent (389 , -6.59807e- 07)
hhfit_15 SetBinContent (390 , -5.968587e- 07)
hhfit_15 SetBinContent (391 , -5.39916e- 07)
hhfit_15 SetBinContent (392 , -4.884058e- 07)
hhfit_15 SetBinContent (393 , -4.418099e- 07)
hhfit_15 SetBinContent (394 , -3.996595e- 07)
hhfit_15 SetBinContent (395 , -3.615303e- 07)
hhfit_15 SetBinContent (396 , -3.270389e- 07)
hhfit_15 SetBinContent (397 , -2.95838e- 07)
hhfit_15 SetBinContent (398 , -2.676139e- 07)
hhfit_15 SetBinContent (399 , -2.420824e- 07)
hhfit_15 SetBinContent (400 , -2.189868e- 07)
hhfit_15 SetBinContent (401 , 485)
hhfit_15 SetBinError (1 , 227776. 5)
hhfit_15 SetBinError (2 , 216638. 8)
hhfit_15 SetBinError (3 , 206045. 7)
hhfit_15 SetBinError (4 , 195970. 6)
hhfit_15 SetBinError (5 , 186388. 1)
hhfit_15 SetBinError (6 , 177274. 2)
hhfit_15 SetBinError (7 , 168605. 9)
hhfit_15 SetBinError (8 , 160361. 5)
hhfit_15 SetBinError (9 , 152520. 2)
hhfit_15 SetBinError (10 , 145062. 4)
hhfit_15 SetBinError (11 , 137969. 2)
hhfit_15 SetBinError (12 , 131222. 8)
hhfit_15 SetBinError (13 , 124806. 4)
hhfit_15 SetBinError (14 , 118703. 7)
hhfit_15 SetBinError (15 , 112899. 3)
hhfit_15 SetBinError (16 , 107378. 8)
hhfit_15 SetBinError (17 , 102128. 3)
hhfit_15 SetBinError (18 , 97134. 46)
hhfit_15 SetBinError (19 , 92384. 83)
hhfit_15 SetBinError (20 , 87867. 44)
hhfit_15 SetBinError (21 , 83570. 94)
hhfit_15 SetBinError (22 , 79484. 53)
hhfit_15 SetBinError (23 , 75597. 94)
hhfit_15 SetBinError (24 , 71901. 39)
hhfit_15 SetBinError (25 , 68385. 59)
hhfit_15 SetBinError (26 , 65041. 7)
hhfit_15 SetBinError (27 , 61861. 32)
hhfit_15 SetBinError (28 , 58836. 46)
hhfit_15 SetBinError (29 , 55959. 5)
hhfit_15 SetBinError (30 , 53223. 22)
hhfit_15 SetBinError (31 , 50620. 74)
hhfit_15 SetBinError (32 , 48145. 51)
hhfit_15 SetBinError (33 , 45791. 32)
hhfit_15 SetBinError (34 , 43552. 23)
hhfit_15 SetBinError (35 , 41422. 64)
hhfit_15 SetBinError (36 , 39397. 17)
hhfit_15 SetBinError (37 , 37470. 75)
hhfit_15 SetBinError (38 , 35638. 52)
hhfit_15 SetBinError (39 , 33895. 89)
hhfit_15 SetBinError (40 , 32238. 46)
hhfit_15 SetBinError (41 , 30662. 08)
hhfit_15 SetBinError (42 , 29162. 78)
hhfit_15 SetBinError (43 , 27736. 8)
hhfit_15 SetBinError (44 , 26380. 54)
hhfit_15 SetBinError (45 , 25090. 59)
hhfit_15 SetBinError (46 , 23863. 73)
hhfit_15 SetBinError (47 , 22696. 85)
hhfit_15 SetBinError (48 , 21587. 03)
hhfit_15 SetBinError (49 , 20531. 48)
hhfit_15 SetBinError (50 , 19527. 54)
hhfit_15 SetBinError (51 , 18572. 69)
hhfit_15 SetBinError (52 , 17664. 53)
hhfit_15 SetBinError (53 , 16800. 78)
hhfit_15 SetBinError (54 , 15979. 27)
hhfit_15 SetBinError (55 , 15197. 92)
hhfit_15 SetBinError (56 , 14454. 78)
hhfit_15 SetBinError (57 , 13747. 98)
hhfit_15 SetBinError (58 , 13075. 73)
hhfit_15 SetBinError (59 , 12436. 36)
hhfit_15 SetBinError (60 , 11828. 26)
hhfit_15 SetBinError (61 , 11249. 88)
hhfit_15 SetBinError (62 , 10699. 79)
hhfit_15 SetBinError (63 , 10176. 6)
hhfit_15 SetBinError (64 , 9678. 989)
hhfit_15 SetBinError (65 , 9205. 711)
hhfit_15 SetBinError (66 , 8755. 574)
hhfit_15 SetBinError (67 , 8327. 448)
hhfit_15 SetBinError (68 , 7920. 257)
hhfit_15 SetBinError (69 , 7532. 976)
hhfit_15 SetBinError (70 , 7164. 632)
hhfit_15 SetBinError (71 , 6814. 3)
hhfit_15 SetBinError (72 , 6481. 097)
hhfit_15 SetBinError (73 , 6164. 188)
hhfit_15 SetBinError (74 , 5862. 774)
hhfit_15 SetBinError (75 , 5576. 099)
hhfit_15 SetBinError (76 , 5303. 442)
hhfit_15 SetBinError (77 , 5044. 117)
hhfit_15 SetBinError (78 , 4797. 472)
hhfit_15 SetBinError (79 , 4562. 888)
hhfit_15 SetBinError (80 , 4339. 774)
hhfit_15 SetBinError (81 , 4127. 57)
hhfit_15 SetBinError (82 , 3925. 742)
hhfit_15 SetBinError (83 , 3733. 783)
hhfit_15 SetBinError (84 , 3551. 21)
hhfit_15 SetBinError (85 , 3377. 565)
hhfit_15 SetBinError (86 , 3212. 41)
hhfit_15 SetBinError (87 , 3055. 331)
hhfit_15 SetBinError (88 , 2905. 933)
hhfit_15 SetBinError (89 , 2763. 84)
hhfit_15 SetBinError (90 , 2628. 695)
hhfit_15 SetBinError (91 , 2500. 159)
hhfit_15 SetBinError (92 , 2377. 907)
hhfit_15 SetBinError (93 , 2261. 633)
hhfit_15 SetBinError (94 , 2151. 045)
hhfit_15 SetBinError (95 , 2045. 864)
hhfit_15 SetBinError (96 , 1945. 827)
hhfit_15 SetBinError (97 , 1850. 681)
hhfit_15 SetBinError (98 , 1760. 187)
hhfit_15 SetBinError (99 , 1674. 118)
hhfit_15 SetBinError (100 , 1592. 258)
hhfit_15 SetBinError (101 , 1514. 408)
hhfit_15 SetBinError (102 , 1440. 36)
hhfit_15 SetBinError (103 , 1369. 925)
hhfit_15 SetBinError (104 , 1302. 943)
hhfit_15 SetBinError (105 , 1239. 234)
hhfit_15 SetBinError (106 , 1178. 639)
hhfit_15 SetBinError (107 , 1121. 008)
hhfit_15 SetBinError (108 , 1066. 194)
hhfit_15 SetBinError (109 , 1014. 06)
hhfit_15 SetBinError (110 , 964. 4804)
hhfit_15 SetBinError (111 , 917. 319)
hhfit_15 SetBinError (112 , 872. 4652)
hhfit_15 SetBinError (113 , 829. 81)
hhfit_15 SetBinError (114 , 789. 2281)
hhfit_15 SetBinError (115 , 750. 6473)
hhfit_15 SetBinError (116 , 713. 9504)
hhfit_15 SetBinError (117 , 679. 0325)
hhfit_15 SetBinError (118 , 645. 8308)
hhfit_15 SetBinError (119 , 614. 2557)
hhfit_15 SetBinError (120 , 584. 2122)
hhfit_15 SetBinError (121 , 555. 667)
hhfit_15 SetBinError (122 , 528. 4874)
hhfit_15 SetBinError (123 , 502. 6482)
hhfit_15 SetBinError (124 , 478. 0851)
hhfit_15 SetBinError (125 , 454. 7064)
hhfit_15 SetBinError (126 , 432. 4772)
hhfit_15 SetBinError (127 , 411. 3353)
hhfit_15 SetBinError (128 , 391. 2186)
hhfit_15 SetBinError (129 , 372. 0914)
hhfit_15 SetBinError (130 , 353. 8994)
hhfit_15 SetBinError (131 , 336. 6044)
hhfit_15 SetBinError (132 , 320. 1702)
hhfit_15 SetBinError (133 , 304. 515)
hhfit_15 SetBinError (134 , 289. 6195)
hhfit_15 SetBinError (135 , 275. 4744)
hhfit_15 SetBinError (136 , 262. 0077)
hhfit_15 SetBinError (137 , 249. 1611)
hhfit_15 SetBinError (138 , 237. 0379)
hhfit_15 SetBinError (139 , 225. 4343)
hhfit_15 SetBinError (140 , 214. 4301)
hhfit_15 SetBinError (141 , 290. 2916)
hhfit_15 SetBinError (142 , 276. 5489)
hhfit_15 SetBinError (143 , 262. 9175)
hhfit_15 SetBinError (144 , 250. 4559)
hhfit_15 SetBinError (145 , 237. 784)
hhfit_15 SetBinError (146 , 226. 5531)
hhfit_15 SetBinError (147 , 215. 7653)
hhfit_15 SetBinError (148 , 205. 0272)
hhfit_15 SetBinError (149 , 195. 4326)
hhfit_15 SetBinError (150 , 185. 3623)
hhfit_15 SetBinError (151 , 177. 0113)
hhfit_15 SetBinError (152 , 168. 4556)
hhfit_15 SetBinError (153 , 160. 1011)
hhfit_15 SetBinError (154 , 152. 807)
hhfit_15 SetBinError (155 , 146. 1545)
hhfit_15 SetBinError (156 , 138. 5679)
hhfit_15 SetBinError (157 , 132. 3628)
hhfit_15 SetBinError (158 , 126. 0548)
hhfit_15 SetBinError (159 , 119. 3975)
hhfit_15 SetBinError (160 , 113. 9584)
hhfit_15 SetBinError (161 , 108. 7036)
hhfit_15 SetBinError (162 , 103. 8641)
hhfit_15 SetBinError (163 , 99. 30221)
hhfit_15 SetBinError (164 , 94. 78489)
hhfit_15 SetBinError (165 , 90. 36089)
hhfit_15 SetBinError (166 , 85. 73621)
hhfit_15 SetBinError (167 , 82. 7732)
hhfit_15 SetBinError (168 , 78. 26846)
hhfit_15 SetBinError (169 , 74. 83582)
hhfit_15 SetBinError (170 , 71. 61067)
hhfit_15 SetBinError (171 , 68. 59015)
hhfit_15 SetBinError (172 , 65. 19035)
hhfit_15 SetBinError (173 , 62. 32685)
hhfit_15 SetBinError (174 , 59. 91989)
hhfit_15 SetBinError (175 , 57. 28382)
hhfit_15 SetBinError (176 , 55. 94917)
hhfit_15 SetBinError (177 , 53. 12902)
hhfit_15 SetBinError (178 , 51. 35555)
hhfit_15 SetBinError (179 , 49. 0951)
hhfit_15 SetBinError (180 , 47. 01623)
hhfit_15 SetBinError (181 , 44. 86758)
hhfit_15 SetBinError (182 , 44. 92495)
hhfit_15 SetBinError (183 , 42. 92152)
hhfit_15 SetBinError (184 , 42. 86564)
hhfit_15 SetBinError (185 , 42. 46503)
hhfit_15 SetBinError (186 , 41. 60732)
hhfit_15 SetBinError (187 , 42. 37509)
hhfit_15 SetBinError (188 , 45. 56622)
hhfit_15 SetBinError (189 , 47. 58853)
hhfit_15 SetBinError (190 , 45. 84161)
hhfit_15 SetBinError (191 , 43. 29332)
hhfit_15 SetBinError (192 , 36. 20705)
hhfit_15 SetBinError (193 , 31. 97036)
hhfit_15 SetBinError (194 , 27. 6321)
hhfit_15 SetBinError (195 , 26. 32526)
hhfit_15 SetBinError (196 , 25. 28572)
hhfit_15 SetBinError (197 , 24. 66577)
hhfit_15 SetBinError (198 , 24. 22718)
hhfit_15 SetBinError (199 , 24. 81713)
hhfit_15 SetBinError (200 , 23. 79223)
hhfit_15 SetBinError (201 , 22. 96472)
hhfit_15 SetBinError (202 , 22. 26447)
hhfit_15 SetBinError (203 , 21. 39994)
hhfit_15 SetBinError (204 , 19. 80007)
hhfit_15 SetBinError (205 , 19. 46493)
hhfit_15 SetBinError (206 , 18. 1771)
hhfit_15 SetBinError (207 , 19. 17156)
hhfit_15 SetBinError (208 , 17. 67057)
hhfit_15 SetBinError (209 , 16. 16957)
hhfit_15 SetBinError (210 , 17. 49624)
hhfit_15 SetBinError (211 , 17. 29727)
hhfit_15 SetBinError (212 , 16. 39045)
hhfit_15 SetBinError (213 , 15. 14718)
hhfit_15 SetBinError (214 , 14. 61277)
hhfit_15 SetBinError (215 , 14. 59131)
hhfit_15 SetBinError (216 , 14. 71496)
hhfit_15 SetBinError (217 , 14. 81151)
hhfit_15 SetBinError (218 , 13. 54387)
hhfit_15 SetBinError (219 , 12. 67586)
hhfit_15 SetBinError (220 , 14. 93607)
hhfit_15 SetBinError (221 , 12. 55576)
hhfit_15 SetBinError (222 , 13. 50352)
hhfit_15 SetBinError (223 , 13. 31042)
hhfit_15 SetBinError (224 , 13. 00392)
hhfit_15 SetBinError (225 , 11. 83799)
hhfit_15 SetBinError (226 , 12. 21746)
hhfit_15 SetBinError (227 , 12. 18514)
hhfit_15 SetBinError (228 , 11. 43522)
hhfit_15 SetBinError (229 , 11. 7524)
hhfit_15 SetBinError (230 , 10. 74873)
hhfit_15 SetBinError (231 , 11. 61925)
hhfit_15 SetBinError (232 , 9. 875697)
hhfit_15 SetBinError (233 , 11. 09492)
hhfit_15 SetBinError (234 , 10. 23261)
hhfit_15 SetBinError (235 , 10. 26415)
hhfit_15 SetBinError (236 , 10. 15051)
hhfit_15 SetBinError (237 , 10. 98834)
hhfit_15 SetBinError (238 , 9. 9238)
hhfit_15 SetBinError (239 , 11. 10158)
hhfit_15 SetBinError (240 , 9. 64525)
hhfit_15 SetBinError (241 , 9. 840584)
hhfit_15 SetBinError (242 , 10. 47195)
hhfit_15 SetBinError (243 , 9. 823608)
hhfit_15 SetBinError (244 , 9. 86711)
hhfit_15 SetBinError (245 , 9. 068083)
hhfit_15 SetBinError (246 , 8. 432839)
hhfit_15 SetBinError (247 , 8. 660635)
hhfit_15 SetBinError (248 , 7. 994409)
hhfit_15 SetBinError (249 , 8. 53368)
hhfit_15 SetBinError (250 , 8. 930012)
hhfit_15 SetBinError (251 , 8. 347097)
hhfit_15 SetBinError (252 , 8. 637692)
hhfit_15 SetBinError (253 , 8. 458815)
hhfit_15 SetBinError (254 , 7. 968622)
hhfit_15 SetBinError (255 , 7. 379115)
hhfit_15 SetBinError (256 , 7. 099878)
hhfit_15 SetBinError (257 , 7. 097135)
hhfit_15 SetBinError (258 , 8. 266443)
hhfit_15 SetBinError (259 , 7. 50348)
hhfit_15 SetBinError (260 , 6. 72855)
hhfit_15 SetBinError (261 , 7. 432853)
hhfit_15 SetBinError (262 , 7. 363675)
hhfit_15 SetBinError (263 , 7. 155583)
hhfit_15 SetBinError (264 , 6. 647034)
hhfit_15 SetBinError (265 , 6. 493504)
hhfit_15 SetBinError (266 , 6. 492287)
hhfit_15 SetBinError (267 , 6. 792312)
hhfit_15 SetBinError (268 , 6. 010206)
hhfit_15 SetBinError (269 , 6. 641602)
hhfit_15 SetBinError (270 , 6. 565082)
hhfit_15 SetBinError (271 , 5. 664868)
hhfit_15 SetBinError (272 , 6. 089506)
hhfit_15 SetBinError (273 , 6. 170433)
hhfit_15 SetBinError (274 , 5. 836708)
hhfit_15 SetBinError (275 , 6. 329357)
hhfit_15 SetBinError (276 , 5. 572698)
hhfit_15 SetBinError (277 , 5. 481762)
hhfit_15 SetBinError (278 , 5. 660828)
hhfit_15 SetBinError (279 , 5. 571417)
hhfit_15 SetBinError (280 , 0. 1918363)
hhfit_15 SetBinError (281 , 0. 182456)
hhfit_15 SetBinError (282 , 0. 1735343)
hhfit_15 SetBinError (283 , 0. 1650489)
hhfit_15 SetBinError (284 , 0. 1569784)
hhfit_15 SetBinError (285 , 0. 1493026)
hhfit_15 SetBinError (286 , 0. 1420021)
hhfit_15 SetBinError (287 , 0. 1350585)
hhfit_15 SetBinError (288 , 0. 1284545)
hhfit_15 SetBinError (289 , 0. 1221734)
hhfit_15 SetBinError (290 , 0. 1161994)
hhfit_15 SetBinError (291 , 0. 1105176)
hhfit_15 SetBinError (292 , 0. 1051135)
hhfit_15 SetBinError (293 , 0. 09997373)
hhfit_15 SetBinError (294 , 0. 09508526)
hhfit_15 SetBinError (295 , 0. 09043583)
hhfit_15 SetBinError (296 , 0. 08601374)
hhfit_15 SetBinError (297 , 0. 08180789)
hhfit_15 SetBinError (298 , 0. 07780768)
hhfit_15 SetBinError (299 , 0. 07400308)
hhfit_15 SetBinError (300 , 0. 07038452)
hhfit_15 SetBinError (301 , 0. 06694289)
hhfit_15 SetBinError (302 , 0. 06366955)
hhfit_15 SetBinError (303 , 0. 06055627)
hhfit_15 SetBinError (304 , 0. 05759521)
hhfit_15 SetBinError (305 , 0. 05477895)
hhfit_15 SetBinError (306 , 0. 0521004)
hhfit_15 SetBinError (307 , 0. 04955282)
hhfit_15 SetBinError (308 , 0. 04712981)
hhfit_15 SetBinError (309 , 0. 04482528)
hhfit_15 SetBinError (310 , 0. 04263343)
hhfit_15 SetBinError (311 , 0. 04054876)
hhfit_15 SetBinError (312 , 0. 03856603)
hhfit_15 SetBinError (313 , 0. 03668025)
hhfit_15 SetBinError (314 , 0. 03488668)
hhfit_15 SetBinError (315 , 0. 0331808)
hhfit_15 SetBinError (316 , 0. 03155835)
hhfit_15 SetBinError (317 , 0. 03001522)
hhfit_15 SetBinError (318 , 0. 02854755)
hhfit_15 SetBinError (319 , 0. 02715165)
hhfit_15 SetBinError (320 , 0. 025824)
hhfit_15 SetBinError (321 , 0. 02456127)
hhfit_15 SetBinError (322 , 0. 02336028)
hhfit_15 SetBinError (323 , 0. 02221802)
hhfit_15 SetBinError (324 , 0. 02113162)
hhfit_15 SetBinError (325 , 0. 02009834)
hhfit_15 SetBinError (326 , 0. 01911558)
hhfit_15 SetBinError (327 , 0. 01818087)
hhfit_15 SetBinError (328 , 0. 01729187)
hhfit_15 SetBinError (329 , 0. 01644634)
hhfit_15 SetBinError (330 , 0. 01564216)
hhfit_15 SetBinError (331 , 0. 0148773)
hhfit_15 SetBinError (332 , 0. 01414983)
hhfit_15 SetBinError (333 , 0. 01345794)
hhfit_15 SetBinError (334 , 0. 01279988)
hhfit_15 SetBinError (335 , 0. 012174)
hhfit_15 SetBinError (336 , 0. 01157872)
hhfit_15 SetBinError (337 , 0. 01101255)
hhfit_15 SetBinError (338 , 0. 01047406)
hhfit_15 SetBinError (339 , 0. 009961908)
hhfit_15 SetBinError (340 , 0. 009474796)
hhfit_15 SetBinError (341 , 0. 009011502)
hhfit_15 SetBinError (342 , 0. 008570862)
hhfit_15 SetBinError (343 , 0. 008151768)
hhfit_15 SetBinError (344 , 0. 007753167)
hhfit_15 SetBinError (345 , 0. 007374056)
hhfit_15 SetBinError (346 , 0. 007013483)
hhfit_15 SetBinError (347 , 0. 006670541)
hhfit_15 SetBinError (348 , 0. 006344369)
hhfit_15 SetBinError (349 , 0. 006034145)
hhfit_15 SetBinError (350 , 0. 00573909)
hhfit_15 SetBinError (351 , 0. 005458463)
hhfit_15 SetBinError (352 , 0. 005191558)
hhfit_15 SetBinError (353 , 0. 004937703)
hhfit_15 SetBinError (354 , 0. 004696262)
hhfit_15 SetBinError (355 , 0. 004466626)
hhfit_15 SetBinError (356 , 0. 00424822)
hhfit_15 SetBinError (357 , 0. 004040492)
hhfit_15 SetBinError (358 , 0. 003842922)
hhfit_15 SetBinError (359 , 0. 003655013)
hhfit_15 SetBinError (360 , 0. 003476292)
hhfit_15 SetBinError (361 , 0. 00330631)
hhfit_15 SetBinError (362 , 0. 003144639)
hhfit_15 SetBinError (363 , 0. 002990874)
hhfit_15 SetBinError (364 , 0. 002844628)
hhfit_15 SetBinError (365 , 0. 002705533)
hhfit_15 SetBinError (366 , 0. 002573239)
hhfit_15 SetBinError (367 , 0. 002447414)
hhfit_15 SetBinError (368 , 0. 002327742)
hhfit_15 SetBinError (369 , 0. 002213921)
hhfit_15 SetBinError (370 , 0. 002105666)
hhfit_15 SetBinError (371 , 0. 002002704)
hhfit_15 SetBinError (372 , 0. 001904777)
hhfit_15 SetBinError (373 , 0. 001811638)
hhfit_15 SetBinError (374 , 0. 001723053)
hhfit_15 SetBinError (375 , 0. 0016388)
hhfit_15 SetBinError (376 , 0. 001558667)
hhfit_15 SetBinError (377 , 0. 001482452)
hhfit_15 SetBinError (378 , 0. 001409964)
hhfit_15 SetBinError (379 , 0. 00134102)
hhfit_15 SetBinError (380 , 0. 001275448)
hhfit_15 SetBinError (381 , 0. 001213081)
hhfit_15 SetBinError (382 , 0. 001153765)
hhfit_15 SetBinError (383 , 0. 001097348)
hhfit_15 SetBinError (384 , 0. 001043691)
hhfit_15 SetBinError (385 , 0. 0009926569)
hhfit_15 SetBinError (386 , 0. 0009441185)
hhfit_15 SetBinError (387 , 0. 0008979534)
hhfit_15 SetBinError (388 , 0. 0008540458)
hhfit_15 SetBinError (389 , 0. 000812285)
hhfit_15 SetBinError (390 , 0. 0007725663)
hhfit_15 SetBinError (391 , 0. 0007347898)
hhfit_15 SetBinError (392 , 0. 0006988604)
hhfit_15 SetBinError (393 , 0. 0006646878)
hhfit_15 SetBinError (394 , 0. 0006321863)
hhfit_15 SetBinError (395 , 0. 0006012739)
hhfit_15 SetBinError (396 , 0. 0005718731)
hhfit_15 SetBinError (397 , 0. 00054391)
hhfit_15 SetBinError (398 , 0. 0005173141)
hhfit_15 SetBinError (399 , 0. 0004920187)
hhfit_15 SetBinError (400 , 0. 0004679602)
hhfit_15 SetBinError (401 , 22. 02272)
cfitall SetBorderMode (0)
cfitall SetBorderSize (2)
cfitall SetBottomMargin (0. 16)
fSandB SetChisquare (29415. 07)
hhfit_15 SetEntries (1.50226e+ 08)
cfitall SetFillColor (0)
fTCBfordave SetFillColor (19)
fSandB SetFillStyle (0)
cfitall SetFrameBorderMode (0)
cfitall SetLeftMargin (0. 16)
fSandB SetLineColor (ci)
fTCBfordave SetLineStyle (2)
fSandB SetLineWidth (3)
hhfit_15 SetLineWidth (2)
fSandB SetMarkerSize (1. 2)
fSandB SetMarkerStyle (20)
fSandB SetName ("fSandB")
fTCBfordave SetName ("fTCBfordave")
fSandB SetNDF (134)
gStyle SetOptStat (0)
gStyle SetOptTitle (0)
fTCBfordave SetParameter (0 , 1268. 46)
Referenced by analyzeClusterEtIso(), CalculateSigmaDca(), SDeltaPtCutStudy::CreateSigmaGraphs(), draw_hists_3D(), GetSubtractedDist(), KFParticleTopoReconstructor::Init(), SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::InitFuncs(), Jet_reso_Iso(), QuickDeltaPtExtractor(), and KFParticleTopoReconstructor::TransportPVTracksToPrimVertex().
fTCBfordave SetParameter (1 , 0. 98)
fTCBfordave SetParameter (2 , 0. 93)
fTCBfordave SetParameter (3 , 9. 443952)
fTCBfordave SetParameter (4 , 0. 1)
fSandB SetParameter (5 , 108. 148)
fSandB SetParameter (6 , 24. 05268)
fTCBfordave SetParameter (7 , 10. 44003)
fTCBfordave SetParameter (8 , -0. 4973067)
fmycorrbg SetParameter (0 , 10. 4037)
fmycorrbg SetParameter (1 , -0. 4926829)
fTCBfordave SetParameter (5 , 314. 7931)
fTCBfordave SetParameter (6 , 179. 6679)
fSandB SetParError (0 , 17. 99564)
fTCBfordave SetParError (1 , 0)
fTCBfordave SetParError (2 , 0)
fSandB SetParError (3 , 0. 001998171)
fTCBfordave SetParError (4 , 0)
fSandB SetParError (5 , 9. 880456)
fSandB SetParError (6 , 8. 311877)
fSandB SetParError (7 , 0. 0295512)
fSandB SetParError (8 , 0. 003352394)
fTCBfordave SetParError (0 , 0)
fTCBfordave SetParError (3 , 0)
fTCBfordave SetParError (5 , 0)
fTCBfordave SetParError (6 , 0)
fTCBfordave SetParError (7 , 0)
fTCBfordave SetParError (8 , 0)
fSandB SetParLimits (0 , 0 , 1000000)
Referenced by draw_hists_3D(), fitShape(), hLabHelper::fitShape(), hLabHelper::getDetectorTiming(), stack::getStackTime(), tileHelper::getYFit(), tileHelper::tileImpact(), and tileHelper::tilePattern().
fSandB SetParLimits (1 , 0. 98, 0. 98)
fSandB SetParLimits (2 , 0. 93, 0. 93)
fSandB SetParLimits (3 , 9 , 10)
fSandB SetParLimits (4 , 0. 1, 0. 1)
fSandB SetParLimits (5 , 0 , 1000000)
fSandB SetParLimits (6 , 0 , 1000000)
fTCBfordave SetParLimits (7 , 0 , 0)
fSandB SetParLimits (8 , -0. 6, 0)
fTCBfordave SetParLimits (0 , 0 , 0)
fTCBfordave SetParLimits (1 , 0 , 0)
fTCBfordave SetParLimits (2 , 0 , 0)
fTCBfordave SetParLimits (3 , 0 , 0)
fTCBfordave SetParLimits (4 , 0 , 0)
fTCBfordave SetParLimits (5 , 0 , 0)
fTCBfordave SetParLimits (6 , 0 , 0)
fTCBfordave SetParLimits (8 , 0 , 0)
fSandB SetRange (7 , 14)
Referenced by Jet_reso_Iso().
fTCBfordave SetRange (5 , 14)
cfitall SetRightMargin (0. 05)
fSandB SetSavedPoint (0 , 1093. 994)
fSandB SetSavedPoint (1 , 1059. 108)
fSandB SetSavedPoint (2 , 1025. 519)
fSandB SetSavedPoint (3 , 993. 1896)
fSandB SetSavedPoint (4 , 962. 0871)
fSandB SetSavedPoint (5 , 932. 1793)
fSandB SetSavedPoint (6 , 903. 4367)
fSandB SetSavedPoint (7 , 875. 8324)
fSandB SetSavedPoint (8 , 849. 342)
fSandB SetSavedPoint (9 , 823. 9441)
fSandB SetSavedPoint (10 , 799. 6205)
fSandB SetSavedPoint (11 , 776. 3565)
fSandB SetSavedPoint (12 , 754. 1414)
fSandB SetSavedPoint (13 , 732. 969)
fSandB SetSavedPoint (14 , 712. 8388)
fSandB SetSavedPoint (15 , 693. 7566)
fSandB SetSavedPoint (16 , 675. 7362)
fSandB SetSavedPoint (17 , 658. 801)
fSandB SetSavedPoint (18 , 642. 9868)
fSandB SetSavedPoint (19 , 628. 3451)
fSandB SetSavedPoint (20 , 614. 948)
fSandB SetSavedPoint (21 , 602. 8953)
fSandB SetSavedPoint (22 , 592. 3243)
fSandB SetSavedPoint (23 , 583. 4256)
fSandB SetSavedPoint (24 , 576. 466)
fSandB SetSavedPoint (25 , 571. 8265)
fSandB SetSavedPoint (26 , 570. 0644)
fSandB SetSavedPoint (27 , 572. 023)
fSandB SetSavedPoint (28 , 579. 0349)
fSandB SetSavedPoint (29 , 593. 3292)
fSandB SetSavedPoint (30 , 618. 9313)
fSandB SetSavedPoint (31 , 663. 9317)
fSandB SetSavedPoint (32 , 747. 3954)
fSandB SetSavedPoint (33 , 927. 8926)
fSandB SetSavedPoint (34 , 1369. 484)
fSandB SetSavedPoint (35 , 1592. 219)
fSandB SetSavedPoint (36 , 1267. 255)
fSandB SetSavedPoint (37 , 746. 1414)
fSandB SetSavedPoint (38 , 425. 9642)
fSandB SetSavedPoint (39 , 319. 6932)
fSandB SetSavedPoint (40 , 299. 7456)
fSandB SetSavedPoint (41 , 305. 0574)
fSandB SetSavedPoint (42 , 334. 9328)
fSandB SetSavedPoint (43 , 348. 3685)
fSandB SetSavedPoint (44 , 315. 6217)
fSandB SetSavedPoint (45 , 266. 0266)
fSandB SetSavedPoint (46 , 235. 6509)
fSandB SetSavedPoint (47 , 228. 3579)
fSandB SetSavedPoint (48 , 221. 5825)
fSandB SetSavedPoint (49 , 206. 835)
fSandB SetSavedPoint (50 , 191. 0306)
fSandB SetSavedPoint (51 , 179. 9124)
fSandB SetSavedPoint (52 , 172. 4525)
fSandB SetSavedPoint (53 , 166. 3374)
fSandB SetSavedPoint (54 , 160. 6255)
fSandB SetSavedPoint (55 , 155. 1289)
fSandB SetSavedPoint (56 , 149. 8215)
fSandB SetSavedPoint (57 , 144. 6957)
fSandB SetSavedPoint (58 , 139. 7453)
fSandB SetSavedPoint (59 , 134. 9642)
fSandB SetSavedPoint (60 , 130. 3468)
fSandB SetSavedPoint (61 , 125. 8873)
fSandB SetSavedPoint (62 , 121. 5804)
fSandB SetSavedPoint (63 , 117. 4208)
fSandB SetSavedPoint (64 , 113. 4035)
fSandB SetSavedPoint (65 , 109. 5237)
fSandB SetSavedPoint (66 , 105. 7766)
fSandB SetSavedPoint (67 , 102. 1577)
fSandB SetSavedPoint (68 , 98. 66267)
fSandB SetSavedPoint (69 , 95. 28718)
fSandB SetSavedPoint (70 , 92. 02716)
fSandB SetSavedPoint (71 , 88. 87868)
fSandB SetSavedPoint (72 , 85. 83792)
fSandB SetSavedPoint (73 , 82. 90119)
fSandB SetSavedPoint (74 , 80. 06493)
fSandB SetSavedPoint (75 , 77. 3257)
fSandB SetSavedPoint (76 , 74. 6802)
fSandB SetSavedPoint (77 , 72. 1252)
fSandB SetSavedPoint (78 , 69. 65761)
fSandB SetSavedPoint (79 , 67. 27445)
fSandB SetSavedPoint (80 , 64. 97282)
fSandB SetSavedPoint (81 , 62. 74994)
fSandB SetSavedPoint (82 , 60. 60311)
fSandB SetSavedPoint (83 , 58. 52972)
fSandB SetSavedPoint (84 , 56. 52727)
fSandB SetSavedPoint (85 , 54. 59333)
fSandB SetSavedPoint (86 , 52. 72556)
fSandB SetSavedPoint (87 , 50. 92168)
fSandB SetSavedPoint (88 , 49. 17952)
fSandB SetSavedPoint (89 , 47. 49697)
fSandB SetSavedPoint (90 , 45. 87198)
fSandB SetSavedPoint (91 , 44. 30258)
fSandB SetSavedPoint (92 , 42. 78688)
fSandB SetSavedPoint (93 , 41. 32303)
fSandB SetSavedPoint (94 , 39. 90927)
fSandB SetSavedPoint (95 , 38. 54387)
fSandB SetSavedPoint (96 , 37. 22519)
fSandB SetSavedPoint (97 , 35. 95162)
fSandB SetSavedPoint (98 , 34. 72162)
fSandB SetSavedPoint (99 , 33. 53371)
fSandB SetSavedPoint (100 , 32. 38644)
fSandB SetSavedPoint (101 , 7)
fTCBfordave SetSavedPoint (102 , 14)
fTCBfordave SetSavedPoint (0 , 2834. 58)
fTCBfordave SetSavedPoint (1 , 2713. 273)
fTCBfordave SetSavedPoint (2 , 2597. 268)
fTCBfordave SetSavedPoint (3 , 2486. 337)
fTCBfordave SetSavedPoint (4 , 2380. 263)
fTCBfordave SetSavedPoint (5 , 2278. 836)
fTCBfordave SetSavedPoint (6 , 2181. 858)
fTCBfordave SetSavedPoint (7 , 2089. 139)
fTCBfordave SetSavedPoint (8 , 2000. 497)
fTCBfordave SetSavedPoint (9 , 1915. 758)
fTCBfordave SetSavedPoint (10 , 1834. 757)
fTCBfordave SetSavedPoint (11 , 1757. 335)
fTCBfordave SetSavedPoint (12 , 1683. 34)
fTCBfordave SetSavedPoint (13 , 1612. 63)
fTCBfordave SetSavedPoint (14 , 1545. 067)
fTCBfordave SetSavedPoint (15 , 1480. 519)
fTCBfordave SetSavedPoint (16 , 1418. 861)
fTCBfordave SetSavedPoint (17 , 1359. 976)
fTCBfordave SetSavedPoint (18 , 1303. 75)
fTCBfordave SetSavedPoint (19 , 1250. 077)
fTCBfordave SetSavedPoint (20 , 1198. 854)
fTCBfordave SetSavedPoint (21 , 1149. 987)
fTCBfordave SetSavedPoint (22 , 1103. 383)
fTCBfordave SetSavedPoint (23 , 1058. 96)
fTCBfordave SetSavedPoint (24 , 1016. 637)
fTCBfordave SetSavedPoint (25 , 976. 3398)
fTCBfordave SetSavedPoint (26 , 938. 0013)
fTCBfordave SetSavedPoint (27 , 901. 5593)
fTCBfordave SetSavedPoint (28 , 866. 9584)
fTCBfordave SetSavedPoint (29 , 834. 1501)
fTCBfordave SetSavedPoint (30 , 803. 0939)
fTCBfordave SetSavedPoint (31 , 773. 7583)
fTCBfordave SetSavedPoint (32 , 746. 1222)
fTCBfordave SetSavedPoint (33 , 720. 1769)
fTCBfordave SetSavedPoint (34 , 695. 9295)
fTCBfordave SetSavedPoint (35 , 673. 4068)
fTCBfordave SetSavedPoint (36 , 652. 6615)
fTCBfordave SetSavedPoint (37 , 633. 7811)
fTCBfordave SetSavedPoint (38 , 616. 902)
fTCBfordave SetSavedPoint (39 , 602. 2309)
fTCBfordave SetSavedPoint (40 , 590. 0801)
fTCBfordave SetSavedPoint (41 , 580. 9272)
fTCBfordave SetSavedPoint (42 , 575. 5234)
fTCBfordave SetSavedPoint (43 , 575. 1002)
fTCBfordave SetSavedPoint (44 , 581. 8044)
fTCBfordave SetSavedPoint (45 , 599. 719)
fTCBfordave SetSavedPoint (46 , 637. 6725)
fTCBfordave SetSavedPoint (47 , 719. 0518)
fTCBfordave SetSavedPoint (48 , 934. 0337)
fTCBfordave SetSavedPoint (49 , 1542. 987)
fTCBfordave SetSavedPoint (50 , 1396. 432)
fTCBfordave SetSavedPoint (51 , 681. 8101)
fTCBfordave SetSavedPoint (52 , 390. 0515)
fTCBfordave SetSavedPoint (53 , 364. 0826)
fTCBfordave SetSavedPoint (54 , 397. 7762)
fTCBfordave SetSavedPoint (55 , 530. 7048)
fTCBfordave SetSavedPoint (56 , 561. 6844)
fTCBfordave SetSavedPoint (57 , 392. 0961)
fTCBfordave SetSavedPoint (58 , 315. 6501)
fTCBfordave SetSavedPoint (59 , 377. 5301)
fTCBfordave SetSavedPoint (60 , 336. 5859)
fTCBfordave SetSavedPoint (61 , 229. 0872)
fTCBfordave SetSavedPoint (62 , 184. 0371)
fTCBfordave SetSavedPoint (63 , 172. 0421)
fTCBfordave SetSavedPoint (64 , 164. 4233)
fTCBfordave SetSavedPoint (65 , 157. 2897)
fTCBfordave SetSavedPoint (66 , 150. 4676)
fTCBfordave SetSavedPoint (67 , 143. 9414)
fTCBfordave SetSavedPoint (68 , 137. 6983)
fTCBfordave SetSavedPoint (69 , 131. 7259)
fTCBfordave SetSavedPoint (70 , 126. 0126)
fTCBfordave SetSavedPoint (71 , 120. 5471)
fTCBfordave SetSavedPoint (72 , 115. 3186)
fTCBfordave SetSavedPoint (73 , 110. 3169)
fTCBfordave SetSavedPoint (74 , 105. 5322)
fTCBfordave SetSavedPoint (75 , 100. 955)
fTCBfordave SetSavedPoint (76 , 96. 57626)
fTCBfordave SetSavedPoint (77 , 92. 38749)
fTCBfordave SetSavedPoint (78 , 88. 38039)
fTCBfordave SetSavedPoint (79 , 84. 54709)
fTCBfordave SetSavedPoint (80 , 80. 88005)
fTCBfordave SetSavedPoint (81 , 77. 37206)
fTCBfordave SetSavedPoint (82 , 74. 01622)
fTCBfordave SetSavedPoint (83 , 70. 80593)
fTCBfordave SetSavedPoint (84 , 67. 73488)
fTCBfordave SetSavedPoint (85 , 64. 79703)
fTCBfordave SetSavedPoint (86 , 61. 98661)
fTCBfordave SetSavedPoint (87 , 59. 29808)
fTCBfordave SetSavedPoint (88 , 56. 72616)
fTCBfordave SetSavedPoint (89 , 54. 26579)
fTCBfordave SetSavedPoint (90 , 51. 91213)
fTCBfordave SetSavedPoint (91 , 49. 66056)
fTCBfordave SetSavedPoint (92 , 47. 50664)
fTCBfordave SetSavedPoint (93 , 45. 44615)
fTCBfordave SetSavedPoint (94 , 43. 47503)
fTCBfordave SetSavedPoint (95 , 41. 58939)
fTCBfordave SetSavedPoint (96 , 39. 78555)
fTCBfordave SetSavedPoint (97 , 38. 05994)
fTCBfordave SetSavedPoint (98 , 36. 40917)
fTCBfordave SetSavedPoint (99 , 34. 83001)
fTCBfordave SetSavedPoint (100 , 33. 31933)
fTCBfordave SetSavedPoint (101 , 5)
cfitall SetSelected (cfitall)
hhfit_15 SetStats (0)
tex SetTextFont (42)
tex SetTextSize (0. 035)
Referenced by DrawCutLabel(), CemcMonDraw::DrawSecond(), and CemcMonDraw::FindHotTower().
cfitall SetTickx (1)
cfitall SetTicky (1)
fTCBfordave SetTitle ("SandB_CBFunction")
cfitall SetTopMargin (0. 05)
Variable Documentation
TCanvas* cfitall = new TCanvas("cfitall", "FIT all pT",272,51,800,640)
Definition at line 4 of file upsilons_sphenix_5yesrs.C.
View newest version in sPHENIX GitHub at line 4 of file upsilons_sphenix_5yesrs.C
Referenced by centrality_newplotbg_newsupp(), newplotbg_newsupp(), newplotbg_newsupp_2021(), newplotbg_newsupp_2022(), and newplotbg_newsupp_2022_60pct().
ci = TColor::GetColor("#ff0000")
Definition at line 940 of file upsilons_sphenix_5yesrs.C.
View newest version in sPHENIX GitHub at line 940 of file upsilons_sphenix_5yesrs.C
TColor* color
Definition at line 941 of file upsilons_sphenix_5yesrs.C.
View newest version in sPHENIX GitHub at line 941 of file upsilons_sphenix_5yesrs.C
TF1* fmycorrbg = new TF1("fmycorrbg","exp([0]+[1]*x)",7,14)
Definition at line 1006 of file upsilons_sphenix_5yesrs.C.
View newest version in sPHENIX GitHub at line 1006 of file upsilons_sphenix_5yesrs.C
Referenced by centrality_newplotbg_newsupp(), newplotbg_newsupp(), newplotbg_newsupp_2021(), newplotbg_newsupp_2022(), and newplotbg_newsupp_2022_60pct().
TF1* fSandB = new TF1("*fSandB",7,14,9)
Definition at line 826 of file upsilons_sphenix_5yesrs.C.
View newest version in sPHENIX GitHub at line 826 of file upsilons_sphenix_5yesrs.C
Referenced by centrality_newplotbg_newsupp(), fit_vs_directcount(), newplotbg_dAu_vscent_2022(), newplotbg_newsupp(), newplotbg_newsupp_2021(), newplotbg_newsupp_2022(), newplotbg_newsupp_2022_60pct(), and newplotbg_vscent_2022().
TF1* fTCBfordave = new TF1("*fTCBfordave",5,14,9)
Definition at line 1034 of file upsilons_sphenix_5yesrs.C.
View newest version in sPHENIX GitHub at line 1034 of file upsilons_sphenix_5yesrs.C
TH1D* hhfit_15 = new TH1D("hhfit_15","",400,0,20)
Definition at line 20 of file upsilons_sphenix_5yesrs.C.
View newest version in sPHENIX GitHub at line 20 of file upsilons_sphenix_5yesrs.C
tex = new TLatex(10.1,1141.614,"sPHENIX Simulation")
Definition at line 1190 of file upsilons_sphenix_5yesrs.C.
View newest version in sPHENIX GitHub at line 1190 of file upsilons_sphenix_5yesrs.C
Referenced by Draw_hitmap(), AnnularFieldSim::GenerateDistortionMaps(), AnnularFieldSim::GenerateSeparateDistortionMaps(), han(), han_BUP2020(), makeLcD0(), makeLcD0_BUP2020(), makeLcD0_BUP2022(), and sphenix_han().