Analysis Software: Acts::Svg::TrackingGeometryConverter Namespace Reference
Acts::Svg::TrackingGeometryConverter Namespace Reference
Classes
struct Options
Nested Options struct for the writing configuration.
struct State
State object to collect geometry-wise information.
Functions
std::vector< actsvg::svg::object > convert (const GeometryContext &gctx, const TrackingGeometry &tGeometry, const Options &cOptions)
void convert (const GeometryContext &gctx, const TrackingVolume &tVolume, const Options &cOptions, State &cState)
Function Documentation
std::vector< actsvg::svg::object > Acts::Svg::TrackingGeometryConverter::convert (const GeometryContext & gctx, const TrackingGeometry & tGeometry, const Options & cOptions)
Write svg files per tracking geometry
Parameters
gctx the geometry context
tGeometry the tracking geometry
cOptions the conversion options
Returns
a vector of svg objects
Definition at line 15 of file TrackingGeometrySvgConverter.cpp.
View newest version in sPHENIX GitHub at line 15 of file TrackingGeometrySvgConverter.cpp
References Acts::Svg::DetectorConverter::convert(), Acts::Svg::TrackingGeometryConverter::State::finalViews, Acts::Svg::group(), Acts::TrackingGeometry::highestTrackingVolume(), Acts::Svg::TrackingGeometryConverter::Options::prefix, Acts::Svg::TrackingGeometryConverter::State::xyCrossSection, and Acts::Svg::TrackingGeometryConverter::State::zrCrossSection.
Referenced by BOOST_AUTO_TEST_CASE(), Acts::Svg::TrackingGeometryProjections::convert(), and ActsExamples::SvgTrackingGeometryWriter::write().
void Acts::Svg::TrackingGeometryConverter::convert (const GeometryContext & gctx, const TrackingVolume & tVolume, const Options & cOptions, TrackingGeometryConverter::State & cState)
Recursivele conversion of volumes
Parameters
gctx the geometry context
tVolume the tracking volume
cOptions the conversion options
cState [in,out] the conversion state collecting the input
Definition at line 41 of file TrackingGeometrySvgConverter.cpp.
View newest version in sPHENIX GitHub at line 41 of file TrackingGeometrySvgConverter.cpp
References Acts::BinnedArray< T >::arrayObjects(), Acts::TrackingVolume::confinedLayers(), Acts::TrackingVolume::confinedVolumes(), Acts::Svg::DetectorConverter::convert(), Acts::Surface::Cylinder, Acts::Svg::LayerConverter::eCrossSectionXY, Acts::Svg::LayerConverter::eCrossSectionZR, Acts::GeometryHierarchyMap< value_t >::end(), Acts::Svg::TrackingGeometryConverter::State::finalViews, Acts::GeometryHierarchyMap< value_t >::find(), Acts::GeometryIdentifier::layer(), layer, Acts::Svg::TrackingGeometryConverter::Options::layerOptions, Acts::Svg::TrackingGeometryConverter::Options::prefix, to_string(), Acts::GeometryIdentifier::volume(), Acts::Svg::TrackingGeometryConverter::State::xyCrossSection, and Acts::Svg::TrackingGeometryConverter::State::zrCrossSection.