Analysis Software: TpcRawHit Class Reference
TpcRawHit Class Reference
#include <coresoftware/blob/master/offline/framework/ffarawobjects/TpcRawHit.h>
Public Member Functions
TpcRawHit ()=default
virtual ~TpcRawHit ()=default
virtual uint64_t get_bco () const
virtual void set_bco (const uint64_t)
virtual uint64_t get_gtm_bco () const
virtual void set_gtm_bco (const uint64_t)
virtual int32_t get_packetid () const
virtual void set_packetid (const int32_t)
virtual uint16_t get_fee () const
virtual void set_fee (const uint16_t)
virtual uint16_t get_channel () const
virtual void set_channel (const uint16_t)
virtual uint16_t get_sampaaddress () const
virtual void set_sampaaddress (const uint16_t)
virtual uint16_t get_sampachannel () const
virtual void set_sampachannel (const uint16_t)
virtual uint16_t get_samples () const
virtual void set_samples (const uint16_t)
virtual uint16_t get_adc (size_t) const
virtual void set_adc (size_t, const uint16_t)
Public Member Functions inherited from PHObject
PHObject ()
ctor
~PHObject () override
dtor
virtual PHObject * CloneMe () const
Virtual copy constructor.
virtual PHObject * clone () const final
PHObject * Clone (const char *newname="") const final
void Copy (TObject &object) const final
virtual void identify (std::ostream &os=std::cout) const
virtual void Reset ()
Clear Event.
virtual int isValid () const
isValid returns non zero if object contains vailid data
virtual int Integrate () const
virtual int Integrate (PHObject *)
virtual void CopyFrom (const PHObject *obj)
Detailed Description
Definition at line 9 of file TpcRawHit.h.
View newest version in sPHENIX GitHub at line 9 of file TpcRawHit.h
Constructor & Destructor Documentation
TpcRawHit::TpcRawHit () default
virtual TpcRawHit::~TpcRawHit () virtual default
Member Function Documentation
virtual uint16_t TpcRawHit::get_adc (size_t) const inline virtual
Reimplemented in TpcRawHitv1.
Definition at line 41 of file TpcRawHit.h.
View newest version in sPHENIX GitHub at line 41 of file TpcRawHit.h
Referenced by TpcCombinedRawDataUnpacker::process_event(), DumpTpcRawHitContainer::process_Node(), and TpcRawHitv1::TpcRawHitv1().
virtual uint64_t TpcRawHit::get_bco () const inline virtual
Reimplemented in TpcRawHitv1.
Definition at line 17 of file TpcRawHit.h.
View newest version in sPHENIX GitHub at line 17 of file TpcRawHit.h
Referenced by TpcRawHitContainerv1::identify(), TpcCheck::process_event(), DumpTpcRawHitContainer::process_Node(), and TpcRawHitv1::TpcRawHitv1().
virtual uint16_t TpcRawHit::get_channel () const inline virtual
Reimplemented in TpcRawHitv1.
Definition at line 29 of file TpcRawHit.h.
View newest version in sPHENIX GitHub at line 29 of file TpcRawHit.h
Referenced by TpcCombinedRawDataUnpacker::process_event(), and TpcRawHitv1::TpcRawHitv1().
virtual uint16_t TpcRawHit::get_fee () const inline virtual
Reimplemented in TpcRawHitv1.
Definition at line 26 of file TpcRawHit.h.
View newest version in sPHENIX GitHub at line 26 of file TpcRawHit.h
Referenced by TpcCombinedRawDataUnpacker::process_event(), DumpTpcRawHitContainer::process_Node(), and TpcRawHitv1::TpcRawHitv1().
virtual uint64_t TpcRawHit::get_gtm_bco () const inline virtual
Reimplemented in TpcRawHitv1.
Definition at line 20 of file TpcRawHit.h.
View newest version in sPHENIX GitHub at line 20 of file TpcRawHit.h
Referenced by StreamingCheck::process_event(), TpcCombinedRawDataUnpacker::process_event(), DumpTpcRawHitContainer::process_Node(), and TpcRawHitv1::TpcRawHitv1().
virtual int32_t TpcRawHit::get_packetid () const inline virtual
Reimplemented in TpcRawHitv1.
Definition at line 23 of file TpcRawHit.h.
View newest version in sPHENIX GitHub at line 23 of file TpcRawHit.h
Referenced by TpcCombinedRawDataUnpacker::process_event(), DumpTpcRawHitContainer::process_Node(), and TpcRawHitv1::TpcRawHitv1().
virtual uint16_t TpcRawHit::get_sampaaddress () const inline virtual
Reimplemented in TpcRawHitv1.
Definition at line 32 of file TpcRawHit.h.
View newest version in sPHENIX GitHub at line 32 of file TpcRawHit.h
Referenced by TpcCombinedRawDataUnpacker::process_event(), DumpTpcRawHitContainer::process_Node(), and TpcRawHitv1::TpcRawHitv1().
virtual uint16_t TpcRawHit::get_sampachannel () const inline virtual
Reimplemented in TpcRawHitv1.
Definition at line 35 of file TpcRawHit.h.
View newest version in sPHENIX GitHub at line 35 of file TpcRawHit.h
Referenced by TpcCombinedRawDataUnpacker::process_event(), DumpTpcRawHitContainer::process_Node(), and TpcRawHitv1::TpcRawHitv1().
virtual uint16_t TpcRawHit::get_samples () const inline virtual
Reimplemented in TpcRawHitv1.
Definition at line 38 of file TpcRawHit.h.
View newest version in sPHENIX GitHub at line 38 of file TpcRawHit.h
Referenced by TpcCombinedRawDataUnpacker::process_event(), DumpTpcRawHitContainer::process_Node(), and TpcRawHitv1::TpcRawHitv1().
virtual void TpcRawHit::set_adc (size_t , const uint16_t) inline virtual
Reimplemented in TpcRawHitv1.
Definition at line 42 of file TpcRawHit.h.
View newest version in sPHENIX GitHub at line 42 of file TpcRawHit.h
Referenced by SingleTpcPoolInput::FillPool().
virtual void TpcRawHit::set_bco (const uint64_t) inline virtual
Reimplemented in TpcRawHitv1.
Definition at line 18 of file TpcRawHit.h.
View newest version in sPHENIX GitHub at line 18 of file TpcRawHit.h
Referenced by SingleTpcPoolInput::FillPool().
virtual void TpcRawHit::set_channel (const uint16_t) inline virtual
Reimplemented in TpcRawHitv1.
Definition at line 30 of file TpcRawHit.h.
View newest version in sPHENIX GitHub at line 30 of file TpcRawHit.h
Referenced by SingleTpcPoolInput::FillPool().
virtual void TpcRawHit::set_fee (const uint16_t) inline virtual
Reimplemented in TpcRawHitv1.
Definition at line 27 of file TpcRawHit.h.
View newest version in sPHENIX GitHub at line 27 of file TpcRawHit.h
Referenced by SingleTpcPoolInput::FillPool().
virtual void TpcRawHit::set_gtm_bco (const uint64_t) inline virtual
Reimplemented in TpcRawHitv1.
Definition at line 21 of file TpcRawHit.h.
View newest version in sPHENIX GitHub at line 21 of file TpcRawHit.h
Referenced by SingleTpcPoolInput::FillPool().
virtual void TpcRawHit::set_packetid (const int32_t) inline virtual
Reimplemented in TpcRawHitv1.
Definition at line 24 of file TpcRawHit.h.
View newest version in sPHENIX GitHub at line 24 of file TpcRawHit.h
Referenced by SingleTpcPoolInput::FillPool().
virtual void TpcRawHit::set_sampaaddress (const uint16_t) inline virtual
Reimplemented in TpcRawHitv1.
Definition at line 33 of file TpcRawHit.h.
View newest version in sPHENIX GitHub at line 33 of file TpcRawHit.h
Referenced by SingleTpcPoolInput::FillPool().
virtual void TpcRawHit::set_sampachannel (const uint16_t) inline virtual
Reimplemented in TpcRawHitv1.
Definition at line 36 of file TpcRawHit.h.
View newest version in sPHENIX GitHub at line 36 of file TpcRawHit.h
Referenced by SingleTpcPoolInput::FillPool().
virtual void TpcRawHit::set_samples (const uint16_t) inline virtual
Reimplemented in TpcRawHitv1.
Definition at line 39 of file TpcRawHit.h.
View newest version in sPHENIX GitHub at line 39 of file TpcRawHit.h
Referenced by SingleTpcPoolInput::FillPool().
The documentation for this class was generated from the following file:
coresoftware/blob/master/offline/framework/ffarawobjects/TpcRawHit.h