Analysis Software: analysis/blob/master/Prototype3/EMCal/ShowerCalib_PositionDependent/simulations/make_fmod_calibrations.C File Reference
make_fmod_calibrations.C File Reference
#include "SetOKStyle.C"
Functions
void make_fmod_calibrations ()
void instantiate ()
void write ()
void write_recals_to_text ()
void fit ()
void loop_tree ()
vector< double > GetBeamMom ()
Variables
TTree * tree
const int nbins = 17
float bins [nbins]
TH1F * resolutions3x3 [nbins-1][nbins-1]
TF1 * fits3x3 [nbins-1][nbins-1]
float recal_consts3x3 [nbins-1][nbins-1]
TH1F * resolutions5x5 [nbins-1][nbins-1]
TF1 * fits5x5 [nbins-1][nbins-1]
float recal_consts5x5 [nbins-1][nbins-1]
Function Documentation
void fit ()
Definition at line 97 of file make_fmod_calibrations.C.
View newest version in sPHENIX GitHub at line 97 of file make_fmod_calibrations.C
References fits3x3, fits5x5, i, j, perf_headwind::name, nbins, recal_consts3x3, recal_consts5x5, resolutions3x3, and resolutions5x5.
Referenced by Acts::Python::addTrackFitting(), Acts::Test::BOOST_AUTO_TEST_CASE(), ambiguity_solver_full_chain::clusterTracks(), DrawCluster_AnaP(), DrawTowerSum_AnaP(), EMCDistribution_Fast(), EMCDistribution_PeakSample_Fast(), Fe55::Fe55(), Fe55::FitG(), listEventiterator::getNextIterator(), make_fmod_calibrations(), numericInverse(), peaks(), plot_jets(), Fe55::PlotXfit(), Fe55::PlotXlines(), ambiguity_solver_full_chain::prepareInferenceData(), train_ambiguity_solver::prepareTrainingData(), sipmCalib(), spmcalib(), TrackClusterEnergy(), TrackingQA(), and VertexingQA().
vector<double> GetBeamMom ()
Definition at line 202 of file make_fmod_calibrations.C.
View newest version in sPHENIX GitHub at line 202 of file make_fmod_calibrations.C
References momentum, t, and tree.
void instantiate ()
Definition at line 37 of file make_fmod_calibrations.C.
View newest version in sPHENIX GitHub at line 37 of file make_fmod_calibrations.C
References i, j, perf_headwind::name, nbins, resolutions3x3, and resolutions5x5.
Referenced by make_fmod_calibrations().
void loop_tree ()
Definition at line 141 of file make_fmod_calibrations.C.
View newest version in sPHENIX GitHub at line 141 of file make_fmod_calibrations.C
References bins, Proto3ShowerCalib::Eval_Run::getbeammom(), Proto3ShowerCalib::Eval_Cluster::getfmodeta(), Proto3ShowerCalib::Eval_Cluster::getfmodphi(), Proto3ShowerCalib::Eval_Cluster::getsumE(), i, j, nbins, resolutions3x3, resolutions5x5, utils::run, and tree.
Referenced by make_fmod_calibrations().
void make_fmod_calibrations ()
Definition at line 14 of file make_fmod_calibrations.C.
View newest version in sPHENIX GitHub at line 14 of file make_fmod_calibrations.C
References bins, f, fit(), i, instantiate(), loop_tree(), nbins, SetOKStyle(), tree, write(), and write_recals_to_text().
void write ()
Definition at line 55 of file make_fmod_calibrations.C.
View newest version in sPHENIX GitHub at line 55 of file make_fmod_calibrations.C
References i, j, nbins, add_histos::outfile, resolutions3x3, and resolutions5x5.
Referenced by Acts::Python::addJson(), Acts::Python::addOutput(), Acts::Python::addSvg(), Acts::AxisAlignedBoundingBox< entity_t, value_t, DIM >::draw(), main(), make_fmod_calibrations(), trento::Output::operator()(), gtest_output_test.GTestOutputTest::testOutput(), release_docs.WikiBrancher::UpdateLinksInBranchedFiles(), ActsExamples::ObjTrackingGeometryWriter::write(), testing::internal::posix::Write(), MvtxCombinedRawDataDecoder::writeMvtxEventHeader(), prdfoStream::writen(), remote_msg_buffer::writen(), oamlBuffer::writen(), writen(), olzoBuffer::writeout(), ogzBuffer::writeout(), ospBuffer::writeout(), ophBuffer::writeout(), HFTrackEfficiency::writeOutputFile(), HFTrackEfficiency::writeSelectedTrackMap(), truthDecayTester::writeTuple(), and QAG4SimulationTruthDecay::writeTuple().
void write_recals_to_text ()
Definition at line 66 of file make_fmod_calibrations.C.
View newest version in sPHENIX GitHub at line 66 of file make_fmod_calibrations.C
References i, j, nbins, recal_consts3x3, and recal_consts5x5.
Referenced by make_fmod_calibrations().
Variable Documentation
float bins[nbins]
Definition at line 5 of file make_fmod_calibrations.C.
View newest version in sPHENIX GitHub at line 5 of file make_fmod_calibrations.C
Referenced by Acts::Python::addMagneticField(), Acts::Python::addTrackFinding(), BinLog(), BinLogX(), BinLogY(), Acts::BinnedArrayXD< T >::BinnedArrayXD(), CheckDeltaPtWithBoundaryMasks(), chopHard(), TpcSpaceChargeReconstructionHelper::copy_histogram(), Acts::createProtoMaterial(), DataAna(), DataAna2(), Acts::MappingMaterialDecorator::decorate(), errorOf1DHistograms(), Acts::from_json(), Acts::IndexedSurfacesJsonConverter::fromJson(), jetHistogrammer::Init(), loop_tree(), main(), make_fmod_calibrations(), MaterialHistograms::MaterialHistograms(), Acts::BinnedArrayXD< T >::object(), plotembed_vscent(), plotpirej(), plotTimes(), QuickWeirdTuplePlotter(), ActsExamples::Options::readMagneticField(), ActsExamples::CsvBFieldWriter::run(), Acts::to_json(), useLogBins(), QAHistManagerDef::useLogBins(), SoftLeptonTaggingTruth::useLogBins(), and ActsExamples::RootMaterialWriter::writeMaterial().
TF1* fits3x3[nbins-1][nbins-1]
Definition at line 8 of file make_fmod_calibrations.C.
View newest version in sPHENIX GitHub at line 8 of file make_fmod_calibrations.C
Referenced by fit().
TF1* fits5x5[nbins-1][nbins-1]
Definition at line 11 of file make_fmod_calibrations.C.
View newest version in sPHENIX GitHub at line 11 of file make_fmod_calibrations.C
Referenced by fit().
const int nbins = 17
Definition at line 4 of file make_fmod_calibrations.C.
View newest version in sPHENIX GitHub at line 4 of file make_fmod_calibrations.C
float recal_consts3x3[nbins-1][nbins-1]
Definition at line 9 of file make_fmod_calibrations.C.
View newest version in sPHENIX GitHub at line 9 of file make_fmod_calibrations.C
Referenced by fit(), and write_recals_to_text().
float recal_consts5x5[nbins-1][nbins-1]
Definition at line 12 of file make_fmod_calibrations.C.
View newest version in sPHENIX GitHub at line 12 of file make_fmod_calibrations.C
Referenced by fit(), and write_recals_to_text().
TH1F* resolutions3x3[nbins-1][nbins-1]
Definition at line 7 of file make_fmod_calibrations.C.
View newest version in sPHENIX GitHub at line 7 of file make_fmod_calibrations.C
Referenced by fit(), instantiate(), loop_tree(), and write().
TH1F* resolutions5x5[nbins-1][nbins-1]
Definition at line 10 of file make_fmod_calibrations.C.
View newest version in sPHENIX GitHub at line 10 of file make_fmod_calibrations.C
Referenced by fit(), instantiate(), loop_tree(), and write().
TTree* tree
Definition at line 3 of file make_fmod_calibrations.C.
View newest version in sPHENIX GitHub at line 3 of file make_fmod_calibrations.C
Referenced by Acts::Python::addMagneticField(), ana_hijbkg(), ana_starlight(), AnalyzeResiduals(), Acts::Test::BOOST_AUTO_TEST_CASE(), Acts::Test::BOOST_FIXTURE_TEST_CASE(), boundParamResolution(), Cone_Plots(), Acts::SeedFinderOrthogonal< external_spacepoint_t >::createSeeds(), eic_sphenix_fill_xq2(), eic_sphenix_test_smearing(), eic_unsmeared_eta_p(), eicsmear_check_calorimeter(), eicsmear_check_tracking(), eicsmear_dvmp_tree(), Fill(), generate_ep_dis(), GetBeamMom(), hera_dis_fillbins(), analysis::InitRun(), jetrtrack::InitRun(), BuildEdgesKDTree< Dim >::invoke(), JetReso(), loop_tree(), main(), make_csv(), make_fmod_calibrations(), ActsExamples::makeMagneticFieldMapRzFromRoot(), ActsExamples::makeMagneticFieldMapXyzFromRoot(), makePlot_EtaDistribution(), MatchJets(), momentumDistributions(), printBField(), printHits(), analysis::process_event(), jetrtrack::process_event(), ActsExamples::Options::readMagneticField(), track_kinematics(), TSQLResultSet::Tree(), dfs::tree_edges_begin(), bfs::tree_edges_begin(), dfs::tree_edges_end(), bfs::tree_edges_end(), and writeTimeOrderedDistortions().