Analysis Software: analysis/blob/master/EMCal-LEDs/macro/event-display.C File Reference
event-display.C File Reference
#include <calobase/TowerInfoDefs.h>
#include <string>
#include <vector>
#include <iostream>
#include <fstream>
#include <TH2F.h>
#include <TFile.h>
#include <TTree.h>
#include <TLine.h>
#include <TCanvas.h>
Namespaces
namespace myAnalysis
Functions
void myAnalysis::init (const string &input_CEMC, const string &outputFile="event-display/test.json", const string &input_HCALIN="", const string &input_HCALOUT="")
void myAnalysis::analyze ()
void myAnalysis::finalize (const string &run, const string &event)
void test_hcal ()
void event_display (const string &run, const string &event, const string &input_CEMC, const string &outputFile="event-display/test.json", const string &input_HCALIN="", const string &input_HCALOUT="")
int main (int argc, char *argv[])
Variables
ofstream myAnalysis::output
TFile * myAnalysis::finput_CEMC = 0
TFile * myAnalysis::finput_HCALIN = 0
TFile * myAnalysis::finput_HCALOUT = 0
TTree * myAnalysis::tree_CEMC
TTree * myAnalysis::tree_HCALIN
TTree * myAnalysis::tree_HCALOUT
TH2F * myAnalysis::h2ADC_CEMC
TH2F * myAnalysis::h2ADC_HCALIN
TH2F * myAnalysis::h2ADC_HCALOUT
TH1F * myAnalysis::hADC_CEMC
TH1F * myAnalysis::hADC_HCALIN
TH1F * myAnalysis::hADC_HCALOUT
UInt_t myAnalysis::eta_bins = 96
Float_t myAnalysis::eta_min = -0.5
Float_t myAnalysis::eta_max = 95.5
UInt_t myAnalysis::phi_bins = 256
Float_t myAnalysis::phi_min = -0.5
Float_t myAnalysis::phi_max = 255.5
UInt_t myAnalysis::etabin_max = 95
UInt_t myAnalysis::phibin_max = 255
UInt_t myAnalysis::channels_bins = 24576
UInt_t myAnalysis::channels_min = 0
UInt_t myAnalysis::channels_max = 24576
UInt_t myAnalysis::eta_hcal_bins = 24
Float_t myAnalysis::eta_hcal_min = -0.5
Float_t myAnalysis::eta_hcal_max = 23.5
UInt_t myAnalysis::phi_hcal_bins = 64
Float_t myAnalysis::phi_hcal_min = -0.5
Float_t myAnalysis::phi_hcal_max = 63.5
UInt_t myAnalysis::channels_hcal_bins = 1536
UInt_t myAnalysis::channels_hcal_min = 0
UInt_t myAnalysis::channels_hcal_max = 1536
const float myAnalysis::eta_map []
const float myAnalysis::phi_map []
UInt_t myAnalysis::ADC_bins = 65
Float_t myAnalysis::ADC_min = 0
Float_t myAnalysis::ADC_max = 1.3e3
Function Documentation
void event_display (const string & run, const string & event, const string & input_CEMC, const string & outputFile = "event-display/test.json", const string & input_HCALIN = "", const string & input_HCALOUT = "")
Definition at line 458 of file event-display.C.
View newest version in sPHENIX GitHub at line 458 of file event-display.C
References myAnalysis::analyze(), myAnalysis::finalize(), and myAnalysis::init().
Referenced by main().
int main (int argc, char * argv[])
Definition at line 470 of file event-display.C.
View newest version in sPHENIX GitHub at line 470 of file event-display.C
References event, event_display(), check_smearing_config::output, and utils::run.
void test_hcal ()
Definition at line 442 of file event-display.C.
View newest version in sPHENIX GitHub at line 442 of file event-display.C
References channel(), myAnalysis::channels_hcal_bins, TowerInfoDefs::encode_hcal(), KF_timing::etabin, TowerInfoDefs::getCaloTowerEtaBin(), and TowerInfoDefs::getCaloTowerPhiBin().