Analysis Software: GlobalVertexv1 Class Reference
GlobalVertexv1 Class Reference
#include <coresoftware/blob/master/offline/packages/globalvertex/GlobalVertexv1.h>
Public Member Functions
GlobalVertexv1 (const GlobalVertex::VTXTYPE id=GlobalVertex::UNDEFINED)
~GlobalVertexv1 () override=default
void identify (std::ostream &os=std::cout) const override
void Reset () override
Clear Event.
int isValid () const override
isValid returns non zero if object contains vailid data
PHObject * CloneMe () const override
Virtual copy constructor.
unsigned int get_id () const override
void set_id (unsigned int id) override
float get_t () const override
void set_t (float t) override
float get_t_err () const override
void set_t_err (float t_err) override
float get_x () const override
void set_x (float x) override
float get_y () const override
void set_y (float y) override
float get_z () const override
void set_z (float z) override
float get_chisq () const override
void set_chisq (float chisq) override
unsigned int get_ndof () const override
void set_ndof (unsigned int ndof) override
float get_position (unsigned int coor) const override
void set_position (unsigned int coor, float xi) override
float get_error (unsigned int i, unsigned int j) const override
void set_error (unsigned int i, unsigned int j, float value) override
bool empty_vtxids () const override
size_t size_vtxids () const override
size_t count_vtxids (GlobalVertex::VTXTYPE type) const override
void clear_vtxids () override
void insert_vtxids (GlobalVertex::VTXTYPE type, unsigned int vtxid) override
size_t erase_vtxids (GlobalVertex::VTXTYPE type) override
void erase_vtxids (GlobalVertex::VtxIter iter) override
void erase_vtxids (GlobalVertex::VtxIter first, GlobalVertex::VtxIter last) override
GlobalVertex::ConstVtxIter begin_vtxids () const override
GlobalVertex::ConstVtxIter find_vtxids (GlobalVertex::VTXTYPE type) const override
GlobalVertex::ConstVtxIter end_vtxids () const override
GlobalVertex::VtxIter begin_vtxids () override
GlobalVertex::VtxIter find_vtxids (GlobalVertex::VTXTYPE type) override
GlobalVertex::VtxIter end_vtxids () override
Public Member Functions inherited from GlobalVertex
~GlobalVertex () override
virtual unsigned int get_beam_crossing () const
virtual void set_beam_crossing (unsigned int)
virtual bool empty_vtxs () const
virtual size_t size_vtxs () const
virtual size_t count_vtxs (VTXTYPE) const
virtual void clear_vtxs ()
virtual void insert_vtx (VTXTYPE, const Vertex *)
virtual size_t erase_vtxs (VTXTYPE)
virtual void erase_vtxs (VertexIter)
virtual ConstVertexIter begin_vertexes () const
virtual ConstVertexIter find_vertexes (VTXTYPE type) const
virtual ConstVertexIter end_vertexes () const
virtual VertexIter begin_vertexes ()
virtual VertexIter find_vertexes (VTXTYPE type)
virtual VertexIter end_vertexes ()
Public Member Functions inherited from PHObject
PHObject ()
ctor
~PHObject () override
dtor
virtual PHObject * clone () const final
PHObject * Clone (const char *newname="") const final
void Copy (TObject &object) const final
virtual int Integrate () const
virtual int Integrate (PHObject *)
virtual void CopyFrom (const PHObject *obj)
Private Member Functions
unsigned int covar_index (unsigned int i, unsigned int j) const
ClassDefOverride (GlobalVertexv1, 1)
Private Attributes
unsigned int _id = std::numeric_limits<unsigned int>::max()
float _t = std::numeric_limits<float>::quiet_NaN()
float _t_err = std::numeric_limits<float>::quiet_NaN()
float _pos [3] = {}
float _chisq = std::numeric_limits<float>::quiet_NaN()
unsigned int _ndof = std::numeric_limits<unsigned int>::max()
float _err [6] = {}
std::map
< GlobalVertex::VTXTYPE,
unsigned int > _vtx_ids
Additional Inherited Members
Public Types inherited from GlobalVertex
enum VTXTYPE {
UNDEFINED = 0, TRUTH = 100, SMEARED = 200, MBD = 300,
SVTX = 400, SVTX_MBD = 500
}
typedef std::vector< const
Vertex * > VertexVector
typedef std::map
< GlobalVertex::VTXTYPE,
VertexVector >::const_iterator ConstVertexIter
typedef std::map
< GlobalVertex::VTXTYPE,
VertexVector >::iterator VertexIter
typedef std::map
< GlobalVertex::VTXTYPE,
unsigned int >::const_iterator ConstVtxIter
typedef std::map
< GlobalVertex::VTXTYPE,
unsigned int >::iterator VtxIter
Protected Member Functions inherited from GlobalVertex
GlobalVertex ()
Detailed Description
Definition at line 16 of file GlobalVertexv1.h.
View newest version in sPHENIX GitHub at line 16 of file GlobalVertexv1.h
Constructor & Destructor Documentation
GlobalVertexv1::GlobalVertexv1 (const GlobalVertex::VTXTYPE id = GlobalVertex::UNDEFINED)
Definition at line 5 of file GlobalVertexv1.cc.
View newest version in sPHENIX GitHub at line 5 of file GlobalVertexv1.cc
References _err, _pos, parse_cmake_options::begin, and end.
Referenced by CloneMe(), and Reset().
GlobalVertexv1::~GlobalVertexv1 () override default
Member Function Documentation
GlobalVertex::ConstVtxIter GlobalVertexv1::begin_vtxids () const inline override virtual
Reimplemented from GlobalVertex.
Definition at line 75 of file GlobalVertexv1.h.
View newest version in sPHENIX GitHub at line 75 of file GlobalVertexv1.h
References _vtx_ids.
Referenced by identify().
GlobalVertex::VtxIter GlobalVertexv1::begin_vtxids () inline override virtual
Reimplemented from GlobalVertex.
Definition at line 79 of file GlobalVertexv1.h.
View newest version in sPHENIX GitHub at line 79 of file GlobalVertexv1.h
References _vtx_ids.
GlobalVertexv1::ClassDefOverride (GlobalVertexv1 , 1) private
void GlobalVertexv1::clear_vtxids () inline override virtual
Reimplemented from GlobalVertex.
Definition at line 69 of file GlobalVertexv1.h.
View newest version in sPHENIX GitHub at line 69 of file GlobalVertexv1.h
References _vtx_ids.
PHObject* GlobalVertexv1::CloneMe () const inline override virtual
Virtual copy constructor.
Reimplemented from GlobalVertex.
Definition at line 27 of file GlobalVertexv1.h.
View newest version in sPHENIX GitHub at line 27 of file GlobalVertexv1.h
References GlobalVertexv1().
size_t GlobalVertexv1::count_vtxids (GlobalVertex::VTXTYPE type) const inline override virtual
Reimplemented from GlobalVertex.
Definition at line 67 of file GlobalVertexv1.h.
View newest version in sPHENIX GitHub at line 67 of file GlobalVertexv1.h
References _vtx_ids.
unsigned int GlobalVertexv1::covar_index (unsigned int i, unsigned int j) const private
Definition at line 103 of file GlobalVertexv1.cc.
View newest version in sPHENIX GitHub at line 103 of file GlobalVertexv1.cc
References swap().
Referenced by get_error(), and set_error().
bool GlobalVertexv1::empty_vtxids () const inline override virtual
Reimplemented from GlobalVertex.
Definition at line 65 of file GlobalVertexv1.h.
View newest version in sPHENIX GitHub at line 65 of file GlobalVertexv1.h
References _vtx_ids.
GlobalVertex::ConstVtxIter GlobalVertexv1::end_vtxids () const inline override virtual
Reimplemented from GlobalVertex.
Definition at line 77 of file GlobalVertexv1.h.
View newest version in sPHENIX GitHub at line 77 of file GlobalVertexv1.h
References _vtx_ids.
Referenced by identify().
GlobalVertex::VtxIter GlobalVertexv1::end_vtxids () inline override virtual
Reimplemented from GlobalVertex.
Definition at line 81 of file GlobalVertexv1.h.
View newest version in sPHENIX GitHub at line 81 of file GlobalVertexv1.h
References _vtx_ids.
size_t GlobalVertexv1::erase_vtxids (GlobalVertex::VTXTYPE type) inline override virtual
Reimplemented from GlobalVertex.
Definition at line 71 of file GlobalVertexv1.h.
View newest version in sPHENIX GitHub at line 71 of file GlobalVertexv1.h
References _vtx_ids.
void GlobalVertexv1::erase_vtxids (GlobalVertex::VtxIter iter) inline override virtual
Reimplemented from GlobalVertex.
Definition at line 72 of file GlobalVertexv1.h.
View newest version in sPHENIX GitHub at line 72 of file GlobalVertexv1.h
References _vtx_ids.
void GlobalVertexv1::erase_vtxids (GlobalVertex::VtxIter first, GlobalVertex::VtxIter last) inline override virtual
Reimplemented from GlobalVertex.
Definition at line 73 of file GlobalVertexv1.h.
View newest version in sPHENIX GitHub at line 73 of file GlobalVertexv1.h
References _vtx_ids.
GlobalVertex::ConstVtxIter GlobalVertexv1::find_vtxids (GlobalVertex::VTXTYPE type) const inline override virtual
Reimplemented from GlobalVertex.
Definition at line 76 of file GlobalVertexv1.h.
View newest version in sPHENIX GitHub at line 76 of file GlobalVertexv1.h
References _vtx_ids.
GlobalVertex::VtxIter GlobalVertexv1::find_vtxids (GlobalVertex::VTXTYPE type) inline override virtual
Reimplemented from GlobalVertex.
Definition at line 80 of file GlobalVertexv1.h.
View newest version in sPHENIX GitHub at line 80 of file GlobalVertexv1.h
References _vtx_ids.
float GlobalVertexv1::get_chisq () const inline override virtual
Reimplemented from GlobalVertex.
Definition at line 49 of file GlobalVertexv1.h.
View newest version in sPHENIX GitHub at line 49 of file GlobalVertexv1.h
References _chisq.
Referenced by identify().
float GlobalVertexv1::get_error (unsigned int i, unsigned int j) const override virtual
Reimplemented from GlobalVertex.
Definition at line 98 of file GlobalVertexv1.cc.
View newest version in sPHENIX GitHub at line 98 of file GlobalVertexv1.cc
References _err, and covar_index().
Referenced by identify(), and isValid().
unsigned int GlobalVertexv1::get_id () const inline override virtual
Reimplemented from GlobalVertex.
Definition at line 31 of file GlobalVertexv1.h.
View newest version in sPHENIX GitHub at line 31 of file GlobalVertexv1.h
References _id.
Referenced by identify().
unsigned int GlobalVertexv1::get_ndof () const inline override virtual
Reimplemented from GlobalVertex.
Definition at line 52 of file GlobalVertexv1.h.
View newest version in sPHENIX GitHub at line 52 of file GlobalVertexv1.h
References _ndof.
Referenced by identify().
float GlobalVertexv1::get_position (unsigned int coor) const inline override virtual
Reimplemented from GlobalVertex.
Definition at line 55 of file GlobalVertexv1.h.
View newest version in sPHENIX GitHub at line 55 of file GlobalVertexv1.h
References _pos.
Referenced by identify().
float GlobalVertexv1::get_t () const inline override virtual
Reimplemented from GlobalVertex.
Definition at line 34 of file GlobalVertexv1.h.
View newest version in sPHENIX GitHub at line 34 of file GlobalVertexv1.h
References _t.
Referenced by identify().
float GlobalVertexv1::get_t_err () const inline override virtual
Reimplemented from GlobalVertex.
Definition at line 37 of file GlobalVertexv1.h.
View newest version in sPHENIX GitHub at line 37 of file GlobalVertexv1.h
References _t_err.
float GlobalVertexv1::get_x () const inline override virtual
Reimplemented from GlobalVertex.
Definition at line 40 of file GlobalVertexv1.h.
View newest version in sPHENIX GitHub at line 40 of file GlobalVertexv1.h
References _pos.
float GlobalVertexv1::get_y () const inline override virtual
Reimplemented from GlobalVertex.
Definition at line 43 of file GlobalVertexv1.h.
View newest version in sPHENIX GitHub at line 43 of file GlobalVertexv1.h
References _pos.
float GlobalVertexv1::get_z () const inline override virtual
Reimplemented from GlobalVertex.
Definition at line 46 of file GlobalVertexv1.h.
View newest version in sPHENIX GitHub at line 46 of file GlobalVertexv1.h
References _pos.
void GlobalVertexv1::identify (std::ostream & os = std::cout) const override virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from GlobalVertex.
Definition at line 12 of file GlobalVertexv1.cc.
View newest version in sPHENIX GitHub at line 12 of file GlobalVertexv1.cc
References begin_vtxids(), end_vtxids(), get_chisq(), get_error(), get_id(), get_ndof(), get_position(), and get_t().
void GlobalVertexv1::insert_vtxids (GlobalVertex::VTXTYPE type, unsigned int vtxid) inline override virtual
Reimplemented from GlobalVertex.
Definition at line 70 of file GlobalVertexv1.h.
View newest version in sPHENIX GitHub at line 70 of file GlobalVertexv1.h
References _vtx_ids.
int GlobalVertexv1::isValid () const override virtual
isValid returns non zero if object contains vailid data
Reimplemented from GlobalVertex.
Definition at line 49 of file GlobalVertexv1.cc.
View newest version in sPHENIX GitHub at line 49 of file GlobalVertexv1.cc
References _chisq, _ndof, _pos, _t, _t_err, _vtx_ids, get_error(), i, and j.
void GlobalVertexv1::Reset () inline override virtual
Clear Event.
Reimplemented from PHObject.
Definition at line 25 of file GlobalVertexv1.h.
View newest version in sPHENIX GitHub at line 25 of file GlobalVertexv1.h
References GlobalVertexv1().
void GlobalVertexv1::set_chisq (float chisq) inline override virtual
Reimplemented from GlobalVertex.
Definition at line 50 of file GlobalVertexv1.h.
View newest version in sPHENIX GitHub at line 50 of file GlobalVertexv1.h
References _chisq.
void GlobalVertexv1::set_error (unsigned int i, unsigned int j, float value) override virtual
Reimplemented from GlobalVertex.
Definition at line 92 of file GlobalVertexv1.cc.
View newest version in sPHENIX GitHub at line 92 of file GlobalVertexv1.cc
References _err, covar_index(), and value.
void GlobalVertexv1::set_id (unsigned int id) inline override virtual
Reimplemented from GlobalVertex.
Definition at line 32 of file GlobalVertexv1.h.
View newest version in sPHENIX GitHub at line 32 of file GlobalVertexv1.h
References _id, and train_ambiguity_solver::id.
void GlobalVertexv1::set_ndof (unsigned int ndof) inline override virtual
Reimplemented from GlobalVertex.
Definition at line 53 of file GlobalVertexv1.h.
View newest version in sPHENIX GitHub at line 53 of file GlobalVertexv1.h
References _ndof.
void GlobalVertexv1::set_position (unsigned int coor, float xi) inline override virtual
Reimplemented from GlobalVertex.
Definition at line 56 of file GlobalVertexv1.h.
View newest version in sPHENIX GitHub at line 56 of file GlobalVertexv1.h
References _pos.
void GlobalVertexv1::set_t (float t) inline override virtual
Reimplemented from GlobalVertex.
Definition at line 35 of file GlobalVertexv1.h.
View newest version in sPHENIX GitHub at line 35 of file GlobalVertexv1.h
References _t, and t.
void GlobalVertexv1::set_t_err (float t_err) inline override virtual
Reimplemented from GlobalVertex.
Definition at line 38 of file GlobalVertexv1.h.
View newest version in sPHENIX GitHub at line 38 of file GlobalVertexv1.h
References _t_err.
void GlobalVertexv1::set_x (float x) inline override virtual
Reimplemented from GlobalVertex.
Definition at line 41 of file GlobalVertexv1.h.
View newest version in sPHENIX GitHub at line 41 of file GlobalVertexv1.h
References _pos, and ambiguity_solver_full_chain::x.
void GlobalVertexv1::set_y (float y) inline override virtual
Reimplemented from GlobalVertex.
Definition at line 44 of file GlobalVertexv1.h.
View newest version in sPHENIX GitHub at line 44 of file GlobalVertexv1.h
References _pos, and y.
void GlobalVertexv1::set_z (float z) inline override virtual
Reimplemented from GlobalVertex.
Definition at line 47 of file GlobalVertexv1.h.
View newest version in sPHENIX GitHub at line 47 of file GlobalVertexv1.h
References _pos, and physmon_track_finding_ttbar::z.
size_t GlobalVertexv1::size_vtxids () const inline override virtual
Reimplemented from GlobalVertex.
Definition at line 66 of file GlobalVertexv1.h.
View newest version in sPHENIX GitHub at line 66 of file GlobalVertexv1.h
References _vtx_ids.
Member Data Documentation
float GlobalVertexv1::_chisq = std::numeric_limits<float>::quiet_NaN() private
Definition at line 90 of file GlobalVertexv1.h.
View newest version in sPHENIX GitHub at line 90 of file GlobalVertexv1.h
Referenced by get_chisq(), isValid(), and set_chisq().
float GlobalVertexv1::_err[6] = {} private
Definition at line 92 of file GlobalVertexv1.h.
View newest version in sPHENIX GitHub at line 92 of file GlobalVertexv1.h
Referenced by get_error(), GlobalVertexv1(), and set_error().
unsigned int GlobalVertexv1::_id = std::numeric_limits<unsigned int>::max() private
Definition at line 86 of file GlobalVertexv1.h.
View newest version in sPHENIX GitHub at line 86 of file GlobalVertexv1.h
Referenced by get_id(), and set_id().
unsigned int GlobalVertexv1::_ndof = std::numeric_limits<unsigned int>::max() private
Definition at line 91 of file GlobalVertexv1.h.
View newest version in sPHENIX GitHub at line 91 of file GlobalVertexv1.h
Referenced by get_ndof(), isValid(), and set_ndof().
float GlobalVertexv1::_pos[3] = {} private
Definition at line 89 of file GlobalVertexv1.h.
View newest version in sPHENIX GitHub at line 89 of file GlobalVertexv1.h
Referenced by get_position(), get_x(), get_y(), get_z(), GlobalVertexv1(), isValid(), set_position(), set_x(), set_y(), and set_z().
float GlobalVertexv1::_t = std::numeric_limits<float>::quiet_NaN() private
Definition at line 87 of file GlobalVertexv1.h.
View newest version in sPHENIX GitHub at line 87 of file GlobalVertexv1.h
Referenced by get_t(), isValid(), and set_t().
float GlobalVertexv1::_t_err = std::numeric_limits<float>::quiet_NaN() private
Definition at line 88 of file GlobalVertexv1.h.
View newest version in sPHENIX GitHub at line 88 of file GlobalVertexv1.h
Referenced by get_t_err(), isValid(), and set_t_err().
std::map<GlobalVertex::VTXTYPE, unsigned int> GlobalVertexv1::_vtx_ids private
Definition at line 93 of file GlobalVertexv1.h.
View newest version in sPHENIX GitHub at line 93 of file GlobalVertexv1.h
Referenced by begin_vtxids(), clear_vtxids(), count_vtxids(), empty_vtxids(), end_vtxids(), erase_vtxids(), find_vtxids(), insert_vtxids(), isValid(), and size_vtxids().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/globalvertex/GlobalVertexv1.h
coresoftware/blob/master/offline/packages/globalvertex/GlobalVertexv1.cc