Analysis Software: acts/blob/sPHENIX/Examples/Run/Reconstruction/Common/RecCKFTracks.cpp File Reference
RecCKFTracks.cpp File Reference
#include "Acts/Utilities/Logger.hpp"
#include "ActsExamples/Detector/IBaseDetector.hpp"
#include "ActsExamples/Framework/Sequencer.hpp"
#include "ActsExamples/Framework/WhiteBoard.hpp"
#include "ActsExamples/Geometry/CommonGeometry.hpp"
#include "ActsExamples/Io/Csv/CsvMultiTrajectoryWriter.hpp"
#include "ActsExamples/Io/Csv/CsvParticleReader.hpp"
#include "ActsExamples/Io/Csv/CsvSimHitReader.hpp"
#include "ActsExamples/Io/Performance/CKFPerformanceWriter.hpp"
#include "ActsExamples/Io/Performance/TrackFinderPerformanceWriter.hpp"
#include "ActsExamples/Io/Root/RootTrajectoryStatesWriter.hpp"
#include "ActsExamples/Io/Root/RootTrajectorySummaryWriter.hpp"
#include "ActsExamples/Options/CommonOptions.hpp"
#include "ActsExamples/Options/CsvOptionsReader.hpp"
#include "ActsExamples/Options/CsvOptionsWriter.hpp"
#include "ActsExamples/Options/DigitizationOptions.hpp"
#include "ActsExamples/Options/MagneticFieldOptions.hpp"
#include "ActsExamples/Options/SpacePointMakerOptions.hpp"
#include "ActsExamples/Options/TrackFindingOptions.hpp"
#include "ActsExamples/Options/TrackFittingOptions.hpp"
#include "ActsExamples/Reconstruction/ReconstructionBase.hpp"
#include "ActsExamples/TrackFinding/SeedingAlgorithm.hpp"
#include "ActsExamples/TrackFinding/SpacePointMaker.hpp"
#include "ActsExamples/TrackFinding/TrackFindingAlgorithm.hpp"
#include "ActsExamples/TrackFinding/TrackParamsEstimationAlgorithm.hpp"
#include "ActsExamples/TruthTracking/TruthSeedSelector.hpp"
#include "ActsExamples/TruthTracking/TruthTrackFinder.hpp"
#include "ActsExamples/Utilities/Options.hpp"
#include "ActsExamples/Utilities/Paths.hpp"
#include "ActsExamples/Utilities/SeedsToPrototracks.hpp"
#include "ActsExamples/Utilities/TracksToTrajectories.hpp"
#include <Acts/Definitions/Units.hpp>
#include <filesystem>
#include <memory>
Functions
void addRecCKFOptions (ActsExamples::Options::Description &desc)
int runRecCKFTracks (int argc, char *argv[], const std::shared_ptr< ActsExamples::IBaseDetector > &detector)
Function Documentation
void addRecCKFOptions (ActsExamples::Options::Description & desc)
The options for running CKF reco
Parameters
desc The options description to add options to
Definition at line 53 of file RecCKFTracks.cpp.
View newest version in sPHENIX GitHub at line 53 of file RecCKFTracks.cpp
Referenced by runRecCKFTracks().
int runRecCKFTracks (int argc, char * argv[], const std::shared_ptr< ActsExamples::IBaseDetector > & detector)
Definition at line 64 of file RecCKFTracks.cpp.
View newest version in sPHENIX GitHub at line 64 of file RecCKFTracks.cpp
References ActsExamples::Sequencer::addAlgorithm(), ActsExamples::Sequencer::addContextDecorator(), ActsExamples::Options::addCsvWriterOptions(), ActsExamples::Options::addDigitizationOptions(), ActsExamples::Options::addFittingOptions(), ActsExamples::Options::addGeometryOptions(), ActsExamples::Options::addInputOptions(), ActsExamples::Options::addMagneticFieldOptions(), ActsExamples::Options::addMaterialOptions(), ActsExamples::Options::addOutputOptions(), ActsExamples::Options::addParticleSmearingOptions(), ActsExamples::Options::addRandomNumbersOptions(), addRecCKFOptions(), ActsExamples::Options::addSequencerOptions(), ActsExamples::Options::addSpacePointMakerOptions(), ActsExamples::Options::addTrackFindingOptions(), ActsExamples::Sequencer::addWriter(), Acts::SeedFinderOptions::beamPos, Acts::SpacePointGridOptions::bFieldInZ, Acts::SeedFinderOptions::bFieldInZ, ActsExamples::TrackParamsEstimationAlgorithm::Config::bFieldMin, ActsExamples::Geometry::build(), trento::random::canonical(), Acts::SeedFinderConfig< SpacePoint >::collisionRegionMax, Acts::SeedFinderConfig< SpacePoint >::collisionRegionMin, Acts::SeedFinderConfig< SpacePoint >::cotThetaMax, Acts::SpacePointGridConfig::cotThetaMax, Acts::SpacePointGridConfig::deltaRMax, Acts::SeedFinderConfig< SpacePoint >::deltaRMax, Acts::SeedFilterConfig::deltaRMin, Acts::SeedFinderConfig< SpacePoint >::deltaRMin, ActsExamples::CKFPerformanceWriter::Config::duplicatedPredictor, ActsExamples::ensureWritableDirectory(), conf::env, ActsExamples::TrackFinderPerformanceWriter::Config::filePath, ActsExamples::CKFPerformanceWriter::Config::filePath, ActsExamples::RootTrajectorySummaryWriter::Config::filePath, ActsExamples::RootTrajectoryStatesWriter::Config::filePath, Acts::Test::geometry, Acts::getDefaultLogger(), ActsExamples::SeedingAlgorithm::Config::gridConfig, ActsExamples::SeedingAlgorithm::Config::gridOptions, Acts::SeedFinderConfig< SpacePoint >::impactMax, ActsExamples::TrackParamsEstimationAlgorithm::Config::initialSigmas, ActsExamples::TrackParamsEstimationAlgorithm::Config::initialVarInflation, material_mapping_optimisation::inputDir, ActsExamples::TrackFinderPerformanceWriter::Config::inputMeasurementParticlesMap, ActsExamples::TruthTrackFinder::Config::inputMeasurementParticlesMap, ActsExamples::TruthSeedSelector::Config::inputMeasurementParticlesMap, ActsExamples::CKFPerformanceWriter::Config::inputMeasurementParticlesMap, ActsExamples::CsvMultiTrajectoryWriter::Config::inputMeasurementParticlesMap, ActsExamples::RootTrajectorySummaryWriter::Config::inputMeasurementParticlesMap, ActsExamples::RootTrajectoryStatesWriter::Config::inputMeasurementParticlesMap, ActsExamples::SpacePointMaker::Config::inputMeasurements, ActsExamples::RootTrajectoryStatesWriter::Config::inputMeasurementSimHitsMap, ActsExamples::TrackFinderPerformanceWriter::Config::inputParticles, ActsExamples::TruthTrackFinder::Config::inputParticles, ActsExamples::TruthSeedSelector::Config::inputParticles, ActsExamples::CKFPerformanceWriter::Config::inputParticles, ActsExamples::RootTrajectorySummaryWriter::Config::inputParticles, ActsExamples::RootTrajectoryStatesWriter::Config::inputParticles, physmon_simulation::inputParticles, ActsExamples::TrackFinderPerformanceWriter::Config::inputProtoTracks, ActsExamples::SeedsToPrototracks::Config::inputSeeds, ActsExamples::TrackParamsEstimationAlgorithm::Config::inputSeeds, ActsExamples::RootTrajectoryStatesWriter::Config::inputSimHits, ActsExamples::SpacePointMaker::Config::inputSourceLinks, ActsExamples::SeedingAlgorithm::Config::inputSpacePoints, ActsExamples::TracksToTrajectories::Config::inputTracks, ActsExamples::CKFPerformanceWriter::Config::inputTrajectories, ActsExamples::CsvMultiTrajectoryWriter::Config::inputTrajectories, ActsExamples::RootTrajectorySummaryWriter::Config::inputTrajectories, ActsExamples::RootTrajectoryStatesWriter::Config::inputTrajectories, Acts::MLTrackClassifier::isDuplicate(), telescope_simulation::logLevel, ActsTests::PropagationDatasets::magneticField, ActsExamples::TrackParamsEstimationAlgorithm::Config::magneticField, ActsExamples::Options::makeDefaultOptions(), Acts::SeedFilterConfig::maxSeedsPerSpM, Acts::SeedFinderConfig< SpacePoint >::maxSeedsPerSpM, Acts::SpacePointGridConfig::minPt, Acts::SeedFinderConfig< SpacePoint >::minPt, ActsExamples::TruthSeedSelector::Config::nHitsMin, outputDir, ActsExamples::CsvMultiTrajectoryWriter::Config::outputDir, ActsExamples::TruthSeedSelector::Config::outputParticles, ActsExamples::SeedsToPrototracks::Config::outputProtoTracks, ActsExamples::TruthTrackFinder::Config::outputProtoTracks, ActsExamples::SeedingAlgorithm::Config::outputSeeds, ActsExamples::SpacePointMaker::Config::outputSpacePoints, ActsExamples::TrackParamsEstimationAlgorithm::Config::outputTrackParameters, ActsExamples::Options::parse(), path, ActsExamples::TruthSeedSelector::Config::ptMin, Acts::SeedFinderConfig< SpacePoint >::radLengthPerSeed, ActsExamples::Options::readLogLevel(), ActsExamples::Options::readMagneticField(), ActsExamples::Options::readRandomNumbersConfig(), ActsExamples::Options::readSequencerConfig(), ActsExamples::Options::readSpacePointMakerConfig(), ActsExamples::Options::readTrackFindingConfig(), Acts::SpacePointGridConfig::rMax, Acts::SeedFinderConfig< SpacePoint >::rMax, physmon_simulation::rnd, ActsExamples::Sequencer::run(), ActsExamples::SeedingAlgorithm::Config::seedFilterConfig, ActsExamples::SeedingAlgorithm::Config::seedFinderConfig, ActsExamples::SeedingAlgorithm::Config::seedFinderOptions, setupDigitization(), setupParticleReading(), setupParticleSmearing(), setupSimHitReading(), Acts::SeedFinderConfig< SpacePoint >::sigmaScattering, Acts::trackingGeometry(), ActsExamples::SpacePointMaker::Config::trackingGeometry, ActsExamples::TrackParamsEstimationAlgorithm::Config::trackingGeometry, ActsExamples::RootTrajectorySummaryWriter::Config::treeName, ActsExamples::RootTrajectoryStatesWriter::Config::treeName, ckf::truthEstimatedSeeded, ckf::truthSmearedSeeded, Acts::SpacePointGridConfig::zMax, Acts::SeedFinderConfig< SpacePoint >::zMax, Acts::SpacePointGridConfig::zMin, and Acts::SeedFinderConfig< SpacePoint >::zMin.
Referenced by main().