Analysis Software: Acts::HomogeneousSurfaceMaterial Class Reference
Acts::HomogeneousSurfaceMaterial Class Reference
#include <acts/blob/sPHENIX/Core/include/Acts/Material/HomogeneousSurfaceMaterial.hpp>
Public Member Functions
HomogeneousSurfaceMaterial ()=default
Default Constructor - defaulted.
HomogeneousSurfaceMaterial (const MaterialSlab &full, double splitFactor=1., MappingType mappingType=MappingType::Default)
HomogeneousSurfaceMaterial (const HomogeneousSurfaceMaterial &hsm)=default
HomogeneousSurfaceMaterial (HomogeneousSurfaceMaterial &&hsm)=default
~HomogeneousSurfaceMaterial () override=default
Destructor.
HomogeneousSurfaceMaterial & operator= (const HomogeneousSurfaceMaterial &hsm)=default
HomogeneousSurfaceMaterial & operator= (HomogeneousSurfaceMaterial &&hsm)=default
HomogeneousSurfaceMaterial & operator*= (double scale) final
bool operator== (const HomogeneousSurfaceMaterial &hsm) const
const MaterialSlab & materialSlab (const Vector2 &lp) const final
const MaterialSlab & materialSlab (const Vector3 &gp) const final
const MaterialSlab & materialSlab (size_t bin0, size_t bin1) const final
std::ostream & toStream (std::ostream &sl) const final
Public Member Functions inherited from Acts::ISurfaceMaterial
ISurfaceMaterial ()=default
Constructor.
ISurfaceMaterial (double splitFactor)
ISurfaceMaterial (double splitFactor, Acts::MappingType mappingType)
virtual ~ISurfaceMaterial ()=default
Destructor.
double factor (Direction pDir, MaterialUpdateStage mStage) const
MappingType mappingType () const
MaterialSlab materialSlab (const Vector2 &lp, Direction pDir, MaterialUpdateStage mStage) const
MaterialSlab materialSlab (const Vector3 &gp, Direction pDir, MaterialUpdateStage mStage) const
Private Attributes
MaterialSlab m_fullMaterial = MaterialSlab()
The five different MaterialSlab.
Additional Inherited Members
Protected Attributes inherited from Acts::ISurfaceMaterial
double m_splitFactor {1.}
the split factor in favour of oppositePre
MappingType m_mappingType
Use the default mapping type by default.
Detailed Description
It extends the ISurfaceMaterial virtual base class to describe a simple homogeneous material on a surface
Definition at line 24 of file HomogeneousSurfaceMaterial.hpp.
View newest version in sPHENIX GitHub at line 24 of file HomogeneousSurfaceMaterial.hpp
Constructor & Destructor Documentation
Acts::HomogeneousSurfaceMaterial::HomogeneousSurfaceMaterial () default
Default Constructor - defaulted.
Acts::HomogeneousSurfaceMaterial::HomogeneousSurfaceMaterial (const MaterialSlab & full, double splitFactor = 1., Acts::MappingType mappingType = MappingType::Default)
Explicit constructor
Parameters
full are the full material properties
splitFactor is the split for pre/post update
mappingType is the type of surface mapping associated to the surface
Definition at line 15 of file HomogeneousSurfaceMaterial.cpp.
View newest version in sPHENIX GitHub at line 15 of file HomogeneousSurfaceMaterial.cpp
Acts::HomogeneousSurfaceMaterial::HomogeneousSurfaceMaterial (const HomogeneousSurfaceMaterial & hsm) default
Copy Constructor
Parameters
hsm is the source material
Acts::HomogeneousSurfaceMaterial::HomogeneousSurfaceMaterial (HomogeneousSurfaceMaterial && hsm) default
Copy Move Constructor
Parameters
hsm is the source material
Acts::HomogeneousSurfaceMaterial::~HomogeneousSurfaceMaterial () override default
Destructor.
Member Function Documentation
const MaterialSlab & Acts::HomogeneousSurfaceMaterial::materialSlab (const Vector2 & lp) const inline final virtual
Return method for full material description of the Surface
from local coordinate on the surface
Parameters
lp is the local position used for the (eventual) lookup
Returns
const MaterialSlab
Note
the input parameter is ignored
Implements Acts::ISurfaceMaterial.
Definition at line 104 of file HomogeneousSurfaceMaterial.hpp.
View newest version in sPHENIX GitHub at line 104 of file HomogeneousSurfaceMaterial.hpp
References m_fullMaterial.
Referenced by Acts::Test::BOOST_AUTO_TEST_CASE().
const MaterialSlab & Acts::HomogeneousSurfaceMaterial::materialSlab (const Vector3 & gp) const inline final virtual
Return method for full material description of the Surface
from the global coordinates
Parameters
gp is the global position used for the (eventual) lookup
Returns
const MaterialSlab
Note
the input parameter is ignored
Implements Acts::ISurfaceMaterial.
Definition at line 109 of file HomogeneousSurfaceMaterial.hpp.
View newest version in sPHENIX GitHub at line 109 of file HomogeneousSurfaceMaterial.hpp
References m_fullMaterial.
const MaterialSlab & Acts::HomogeneousSurfaceMaterial::materialSlab (size_t bin0, size_t bin1) const inline final virtual
Direct access via bins to the MaterialSlab
Parameters
bin0 is the material bin in dimension 0
bin1 is the material bin in dimension 1
Note
the input parameters are ignored
Implements Acts::ISurfaceMaterial.
Definition at line 114 of file HomogeneousSurfaceMaterial.hpp.
View newest version in sPHENIX GitHub at line 114 of file HomogeneousSurfaceMaterial.hpp
References m_fullMaterial.
Acts::HomogeneousSurfaceMaterial & Acts::HomogeneousSurfaceMaterial::operator*= (double scale) final virtual
Scale operator
it is effectively a thickness scaling
Parameters
scale is the scale factor
Implements Acts::ISurfaceMaterial.
Definition at line 19 of file HomogeneousSurfaceMaterial.cpp.
View newest version in sPHENIX GitHub at line 19 of file HomogeneousSurfaceMaterial.cpp
HomogeneousSurfaceMaterial& Acts::HomogeneousSurfaceMaterial::operator= (const HomogeneousSurfaceMaterial & hsm) default
Assignment operator
Parameters
hsm is the source material
HomogeneousSurfaceMaterial& Acts::HomogeneousSurfaceMaterial::operator= (HomogeneousSurfaceMaterial && hsm) default
Assignment Move operator
Parameters
hsm is the source material
bool Acts::HomogeneousSurfaceMaterial::operator== (const HomogeneousSurfaceMaterial & hsm) const inline
Equality operator
Parameters
hsm is the source material
Definition at line 119 of file HomogeneousSurfaceMaterial.hpp.
View newest version in sPHENIX GitHub at line 119 of file HomogeneousSurfaceMaterial.hpp
References m_fullMaterial.
std::ostream & Acts::HomogeneousSurfaceMaterial::toStream (std::ostream & sl) const final virtual
Output Method for std::ostream
Parameters
sl The outoput stream
Implements Acts::ISurfaceMaterial.
Definition at line 25 of file HomogeneousSurfaceMaterial.cpp.
View newest version in sPHENIX GitHub at line 25 of file HomogeneousSurfaceMaterial.cpp
Member Data Documentation
MaterialSlab Acts::HomogeneousSurfaceMaterial::m_fullMaterial = MaterialSlab() private
The five different MaterialSlab.
Definition at line 101 of file HomogeneousSurfaceMaterial.hpp.
View newest version in sPHENIX GitHub at line 101 of file HomogeneousSurfaceMaterial.hpp
Referenced by materialSlab(), and operator==().
The documentation for this class was generated from the following files:
acts/blob/sPHENIX/Core/include/Acts/Material/HomogeneousSurfaceMaterial.hpp
acts/blob/sPHENIX/Core/src/Material/HomogeneousSurfaceMaterial.cpp