Analysis Software: acts/blob/sPHENIX/Tests/UnitTests/Fatras/Physics/ScatteringTests.cpp File Reference
ScatteringTests.cpp File Reference
#include <boost/test/data/test_case.hpp>
#include <boost/test/unit_test.hpp>
#include "Acts/Tests/CommonHelpers/FloatComparisons.hpp"
#include "Acts/Tests/CommonHelpers/PredefinedMaterials.hpp"
#include "ActsFatras/EventData/Particle.hpp"
#include "ActsFatras/Physics/ElectroMagnetic/Scattering.hpp"
#include <cstdint>
#include <limits>
#include <random>
#include "Dataset.hpp"
Functions
BOOST_DATA_TEST_CASE (GeneralMixture, Dataset::parameters, pdg, phi, lambda, p, seed)
BOOST_DATA_TEST_CASE (GaussianMixture, Dataset::parameters, pdg, phi, lambda, p, seed)
BOOST_DATA_TEST_CASE (Highland, Dataset::parameters, pdg, phi, lambda, p, seed)
Function Documentation
BOOST_DATA_TEST_CASE (GeneralMixture , Dataset::parameters , pdg , phi , lambda , p , seed)
Definition at line 46 of file ScatteringTests.cpp.
View newest version in sPHENIX GitHub at line 46 of file ScatteringTests.cpp
References Dataset::makeParticle(), and train_ambiguity_solver::test.
BOOST_DATA_TEST_CASE (GaussianMixture , Dataset::parameters , pdg , phi , lambda , p , seed)
Definition at line 52 of file ScatteringTests.cpp.
View newest version in sPHENIX GitHub at line 52 of file ScatteringTests.cpp
References Dataset::makeParticle(), merge_hashes::p, pdg, ActsTests::PropagationDatasets::phi, and train_ambiguity_solver::test.
BOOST_DATA_TEST_CASE (Highland , Dataset::parameters , pdg , phi , lambda , p , seed)
Definition at line 58 of file ScatteringTests.cpp.
View newest version in sPHENIX GitHub at line 58 of file ScatteringTests.cpp
References Dataset::makeParticle(), merge_hashes::p, pdg, ActsTests::PropagationDatasets::phi, and train_ambiguity_solver::test.