Analysis Software: InvokeHelper< Result, ArgumentTuple > Class Template Reference
InvokeHelper< Result, ArgumentTuple > Class Template Reference
#include <JETSCAPE/blob/main/external_packages/googletest/googlemock/include/gmock/gmock-generated-actions.h>
Public Member Functions
void VoidFromVoid ()
void VoidFromString (char *)
Static Public Member Functions
static void StaticVoidFromVoid ()
static void StaticVoidFromString (char *)
static int StaticIntFromString (char *)
static bool StaticBoolFromString (const char *)
Detailed Description
template<typename Result, typename ArgumentTuple>
class InvokeHelper< Result, ArgumentTuple >
Definition at line 51 of file gmock-generated-actions.h.
View newest version in sPHENIX GitHub at line 51 of file gmock-generated-actions.h
Member Function Documentation
template<typename Result , typename ArgumentTuple > static bool InvokeHelper< Result, ArgumentTuple >::StaticBoolFromString (const char *) inline static
Definition at line 230 of file gmock_link_test.h.
View newest version in sPHENIX GitHub at line 230 of file gmock_link_test.h
Referenced by TEST().
template<typename Result , typename ArgumentTuple > static int InvokeHelper< Result, ArgumentTuple >::StaticIntFromString (char *) inline static
Definition at line 229 of file gmock_link_test.h.
View newest version in sPHENIX GitHub at line 229 of file gmock_link_test.h
Referenced by TEST().
template<typename Result , typename ArgumentTuple > static void InvokeHelper< Result, ArgumentTuple >::StaticVoidFromString (char *) inline static
Definition at line 227 of file gmock_link_test.h.
View newest version in sPHENIX GitHub at line 227 of file gmock_link_test.h
Referenced by TEST().
template<typename Result , typename ArgumentTuple > static void InvokeHelper< Result, ArgumentTuple >::StaticVoidFromVoid () inline static
Definition at line 225 of file gmock_link_test.h.
View newest version in sPHENIX GitHub at line 225 of file gmock_link_test.h
Referenced by TEST().
template<typename Result , typename ArgumentTuple > void InvokeHelper< Result, ArgumentTuple >::VoidFromString (char *) inline
Definition at line 228 of file gmock_link_test.h.
View newest version in sPHENIX GitHub at line 228 of file gmock_link_test.h
Referenced by TEST().
template<typename Result , typename ArgumentTuple > void InvokeHelper< Result, ArgumentTuple >::VoidFromVoid () inline
Definition at line 226 of file gmock_link_test.h.
View newest version in sPHENIX GitHub at line 226 of file gmock_link_test.h
Referenced by TEST().
The documentation for this class was generated from the following files:
JETSCAPE/blob/main/external_packages/googletest/googlemock/include/gmock/gmock-generated-actions.h
JETSCAPE/blob/main/external_packages/googletest/googlemock/test/gmock_link_test.h