Analysis Software: SingleStreamingInput Class Reference
SingleStreamingInput Class Reference
#include <coresoftware/blob/master/offline/framework/fun4allraw/SingleStreamingInput.h>
Public Member Functions
SingleStreamingInput (const std::string &name, Fun4AllEvtInputPoolManager *inman)
SingleStreamingInput (const std::string &name)
~SingleStreamingInput () override
virtual Eventiterator * GetEventIterator ()
virtual void FillPool (const uint64_t)
virtual void FillPool (const unsigned int=1)
virtual void RunNumber (const int runno)
virtual int RunNumber () const
virtual int fileopen (const std::string &filename) override
virtual int fileclose () override
virtual int AllDone () const
virtual void AllDone (const int i)
virtual void EventNumberOffset (const int i)
virtual void Print (const std::string &what="ALL") const override
virtual void CleanupUsedPackets (const uint64_t)
virtual bool CheckPoolDepth (const uint64_t bclk)
virtual void ClearCurrentEvent ()
virtual Eventiterator * GetEventiterator () const
virtual
Fun4AllEvtInputPoolManager * InputManager ()
virtual void InputManager (Fun4AllEvtInputPoolManager *in)
virtual
Fun4AllStreamingInputManager * StreamingInputManager ()
virtual void StreamingInputManager (Fun4AllStreamingInputManager *in)
virtual void CreateDSTNode (PHCompositeNode *)
virtual void ConfigureStreamingInputManager ()
virtual void SubsystemEnum (const int id)
virtual int SubsystemEnum () const
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Public Member Functions inherited from InputFileHandler
InputFileHandler ()=default
virtual ~InputFileHandler ()=default
int OpenNextFile ()
int AddListFile (const std::string &filename)
int AddFile (const std::string &filename)
void AddToFileOpened (const std::string &filename)
void Print (const std::string &what="ALL") const
int IsOpen () const
void IsOpen (const int i)
void SetVerbosity (const int i)
int GetVerbosity () const
void UpdateFileList ()
void FileName (const std::string &fn)
const std::string FileName () const
Private Attributes
Eventiterator * m_EventIterator = nullptr
Fun4AllEvtInputPoolManager * m_InputMgr = nullptr
Fun4AllStreamingInputManager * m_StreamingInputMgr = nullptr
unsigned int m_EventNumberOffset = 1
int m_RunNumber = 0
int m_EventsThisFile = 0
int m_AllDone = 0
int m_SubsystemEnum {0}
std::map< uint64_t, std::set
< int > > m_BeamClockFEE
std::map< int, uint64_t > m_FEEBclkMap
std::set< uint64_t > m_BclkStack
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = std::numeric_limits<int>::max() - 10
}
Protected Member Functions inherited from Fun4AllBase
Fun4AllBase (const std::string &name="NONAME")
Detailed Description
Definition at line 17 of file SingleStreamingInput.h.
View newest version in sPHENIX GitHub at line 17 of file SingleStreamingInput.h
Constructor & Destructor Documentation
SingleStreamingInput::SingleStreamingInput (const std::string & name, Fun4AllEvtInputPoolManager * inman) explicit
Definition at line 15 of file SingleStreamingInput.cc.
View newest version in sPHENIX GitHub at line 15 of file SingleStreamingInput.cc
SingleStreamingInput::SingleStreamingInput (const std::string & name) explicit
Definition at line 21 of file SingleStreamingInput.cc.
View newest version in sPHENIX GitHub at line 21 of file SingleStreamingInput.cc
SingleStreamingInput::~SingleStreamingInput () override
Definition at line 26 of file SingleStreamingInput.cc.
View newest version in sPHENIX GitHub at line 26 of file SingleStreamingInput.cc
References m_EventIterator.
Member Function Documentation
virtual int SingleStreamingInput::AllDone () const inline virtual
Definition at line 30 of file SingleStreamingInput.h.
View newest version in sPHENIX GitHub at line 30 of file SingleStreamingInput.h
References m_AllDone.
Referenced by SingleGl1PoolInput::FillPool(), SingleTpcPoolInput::FillPool(), SingleMicromegasPoolInput::FillPool(), SingleInttPoolInput::FillPool(), SingleMvtxPoolInput::FillPool(), SingleTpcPoolInput::GetSomeMoreEvents(), SingleGl1PoolInput::GetSomeMoreEvents(), SingleMicromegasPoolInput::GetSomeMoreEvents(), SingleInttPoolInput::GetSomeMoreEvents(), and SingleMvtxPoolInput::GetSomeMoreEvents().
virtual void SingleStreamingInput::AllDone (const int i) inline virtual
Definition at line 31 of file SingleStreamingInput.h.
View newest version in sPHENIX GitHub at line 31 of file SingleStreamingInput.h
References i, and m_AllDone.
bool SingleStreamingInput::CheckPoolDepth (const uint64_t bclk) virtual
Reimplemented in SingleMvtxPoolInput, SingleInttPoolInput, SingleGl1PoolInput, and SingleTpcPoolInput.
Definition at line 109 of file SingleStreamingInput.cc.
View newest version in sPHENIX GitHub at line 109 of file SingleStreamingInput.cc
References m_FEEBclkMap, and Fun4AllBase::Verbosity().
virtual void SingleStreamingInput::CleanupUsedPackets (const uint64_t) inline virtual
Reimplemented in SingleMvtxPoolInput, SingleInttPoolInput, SingleMicromegasPoolInput, SingleGl1PoolInput, and SingleTpcPoolInput.
Definition at line 34 of file SingleStreamingInput.h.
View newest version in sPHENIX GitHub at line 34 of file SingleStreamingInput.h
Referenced by ClearCurrentEvent().
void SingleStreamingInput::ClearCurrentEvent () virtual
Reimplemented in SingleMvtxPoolInput, SingleInttPoolInput, SingleGl1PoolInput, SingleMicromegasPoolInput, and SingleTpcPoolInput.
Definition at line 136 of file SingleStreamingInput.cc.
View newest version in sPHENIX GitHub at line 136 of file SingleStreamingInput.cc
References CleanupUsedPackets(), m_BclkStack, and m_BeamClockFEE.
virtual void SingleStreamingInput::ConfigureStreamingInputManager () inline virtual
Reimplemented in SingleMvtxPoolInput, SingleInttPoolInput, SingleMicromegasPoolInput, and SingleTpcPoolInput.
Definition at line 43 of file SingleStreamingInput.h.
View newest version in sPHENIX GitHub at line 43 of file SingleStreamingInput.h
Referenced by Fun4AllStreamingInputManager::registerStreamingInput().
virtual void SingleStreamingInput::CreateDSTNode (PHCompositeNode *) inline virtual
Reimplemented in SingleMvtxPoolInput, SingleInttPoolInput, SingleGl1PoolInput, SingleMicromegasPoolInput, and SingleTpcPoolInput.
Definition at line 42 of file SingleStreamingInput.h.
View newest version in sPHENIX GitHub at line 42 of file SingleStreamingInput.h
Referenced by Fun4AllStreamingInputManager::registerStreamingInput().
virtual void SingleStreamingInput::EventNumberOffset (const int i) inline virtual
Definition at line 32 of file SingleStreamingInput.h.
View newest version in sPHENIX GitHub at line 32 of file SingleStreamingInput.h
References i, and m_EventNumberOffset.
int SingleStreamingInput::fileclose () override virtual
Reimplemented from InputFileHandler.
Definition at line 63 of file SingleStreamingInput.cc.
View newest version in sPHENIX GitHub at line 63 of file SingleStreamingInput.cc
References InputFileHandler::IsOpen(), m_EventIterator, Fun4AllBase::Name(), and InputFileHandler::UpdateFileList().
Referenced by fileopen(), SingleGl1PoolInput::FillPool(), SingleTpcPoolInput::FillPool(), SingleMicromegasPoolInput::FillPool(), SingleInttPoolInput::FillPool(), and SingleMvtxPoolInput::FillPool().
int SingleStreamingInput::fileopen (const std::string & filename) override virtual
Reimplemented from InputFileHandler.
Definition at line 31 of file SingleStreamingInput.cc.
View newest version in sPHENIX GitHub at line 31 of file SingleStreamingInput.cc
References InputFileHandler::AddToFileOpened(), fileclose(), InputFileHandler::FileName(), INTTVtxZ::fname, InputFileHandler::IsOpen(), FROG::location(), m_EventIterator, m_EventsThisFile, Fun4AllBase::Name(), PHWHERE, utils::status, and Fun4AllBase::Verbosity().
virtual void SingleStreamingInput::FillPool (const uint64_t) inline virtual
Definition at line 24 of file SingleStreamingInput.h.
View newest version in sPHENIX GitHub at line 24 of file SingleStreamingInput.h
virtual void SingleStreamingInput::FillPool (const unsigned int = 1) inline virtual
Reimplemented in SingleMvtxPoolInput, SingleInttPoolInput, SingleMicromegasPoolInput, SingleGl1PoolInput, and SingleTpcPoolInput.
Definition at line 25 of file SingleStreamingInput.h.
View newest version in sPHENIX GitHub at line 25 of file SingleStreamingInput.h
virtual Eventiterator* SingleStreamingInput::GetEventIterator () inline virtual
Definition at line 23 of file SingleStreamingInput.h.
View newest version in sPHENIX GitHub at line 23 of file SingleStreamingInput.h
References m_EventIterator.
virtual Eventiterator* SingleStreamingInput::GetEventiterator () const inline virtual
Definition at line 37 of file SingleStreamingInput.h.
View newest version in sPHENIX GitHub at line 37 of file SingleStreamingInput.h
References m_EventIterator.
Referenced by SingleGl1PoolInput::FillPool(), SingleTpcPoolInput::FillPool(), SingleMicromegasPoolInput::FillPool(), SingleInttPoolInput::FillPool(), and SingleMvtxPoolInput::FillPool().
virtual Fun4AllEvtInputPoolManager* SingleStreamingInput::InputManager () inline virtual
Definition at line 38 of file SingleStreamingInput.h.
View newest version in sPHENIX GitHub at line 38 of file SingleStreamingInput.h
References m_InputMgr.
virtual void SingleStreamingInput::InputManager (Fun4AllEvtInputPoolManager * in) inline virtual
Definition at line 39 of file SingleStreamingInput.h.
View newest version in sPHENIX GitHub at line 39 of file SingleStreamingInput.h
References in, and m_InputMgr.
void SingleStreamingInput::Print (const std::string & what = "ALL") const override virtual
Print out some info about this module.
Parameters
what can be used to specify what to print exactly.
Reimplemented from Fun4AllBase.
Reimplemented in SingleMvtxPoolInput, SingleInttPoolInput, SingleGl1PoolInput, SingleMicromegasPoolInput, and SingleTpcPoolInput.
Definition at line 79 of file SingleStreamingInput.cc.
View newest version in sPHENIX GitHub at line 79 of file SingleStreamingInput.cc
References m_BclkStack, m_BeamClockFEE, and m_FEEBclkMap.
virtual void SingleStreamingInput::RunNumber (const int runno) inline virtual
Definition at line 26 of file SingleStreamingInput.h.
View newest version in sPHENIX GitHub at line 26 of file SingleStreamingInput.h
References m_RunNumber.
virtual int SingleStreamingInput::RunNumber () const inline virtual
Definition at line 27 of file SingleStreamingInput.h.
View newest version in sPHENIX GitHub at line 27 of file SingleStreamingInput.h
References m_RunNumber.
Referenced by SingleGl1PoolInput::FillPool(), SingleTpcPoolInput::FillPool(), SingleMicromegasPoolInput::FillPool(), SingleInttPoolInput::FillPool(), and SingleMvtxPoolInput::FillPool().
virtual Fun4AllStreamingInputManager* SingleStreamingInput::StreamingInputManager () inline virtual
Definition at line 40 of file SingleStreamingInput.h.
View newest version in sPHENIX GitHub at line 40 of file SingleStreamingInput.h
References m_StreamingInputMgr.
Referenced by SingleTpcPoolInput::ConfigureStreamingInputManager(), SingleMicromegasPoolInput::ConfigureStreamingInputManager(), SingleInttPoolInput::ConfigureStreamingInputManager(), SingleMvtxPoolInput::ConfigureStreamingInputManager(), SingleGl1PoolInput::FillPool(), SingleTpcPoolInput::FillPool(), SingleMicromegasPoolInput::FillPool(), SingleInttPoolInput::FillPool(), SingleMvtxPoolInput::FillPool(), and Fun4AllStreamingInputManager::registerStreamingInput().
virtual void SingleStreamingInput::StreamingInputManager (Fun4AllStreamingInputManager * in) inline virtual
Definition at line 41 of file SingleStreamingInput.h.
View newest version in sPHENIX GitHub at line 41 of file SingleStreamingInput.h
References in, and m_StreamingInputMgr.
virtual void SingleStreamingInput::SubsystemEnum (const int id) inline virtual
Definition at line 44 of file SingleStreamingInput.h.
View newest version in sPHENIX GitHub at line 44 of file SingleStreamingInput.h
References train_ambiguity_solver::id, and m_SubsystemEnum.
virtual int SingleStreamingInput::SubsystemEnum () const inline virtual
Definition at line 45 of file SingleStreamingInput.h.
View newest version in sPHENIX GitHub at line 45 of file SingleStreamingInput.h
References m_SubsystemEnum.
Referenced by SingleGl1PoolInput::SingleGl1PoolInput(), SingleInttPoolInput::SingleInttPoolInput(), SingleMicromegasPoolInput::SingleMicromegasPoolInput(), and SingleTpcPoolInput::SingleTpcPoolInput().
Member Data Documentation
int SingleStreamingInput::m_AllDone = 0 private
Definition at line 54 of file SingleStreamingInput.h.
View newest version in sPHENIX GitHub at line 54 of file SingleStreamingInput.h
Referenced by AllDone().
std::set<uint64_t> SingleStreamingInput::m_BclkStack private
Definition at line 58 of file SingleStreamingInput.h.
View newest version in sPHENIX GitHub at line 58 of file SingleStreamingInput.h
Referenced by ClearCurrentEvent(), and Print().
std::map<uint64_t, std::set<int> > SingleStreamingInput::m_BeamClockFEE private
Definition at line 56 of file SingleStreamingInput.h.
View newest version in sPHENIX GitHub at line 56 of file SingleStreamingInput.h
Referenced by ClearCurrentEvent(), and Print().
Eventiterator* SingleStreamingInput::m_EventIterator = nullptr private
Definition at line 48 of file SingleStreamingInput.h.
View newest version in sPHENIX GitHub at line 48 of file SingleStreamingInput.h
Referenced by fileclose(), fileopen(), GetEventIterator(), GetEventiterator(), and ~SingleStreamingInput().
unsigned int SingleStreamingInput::m_EventNumberOffset = 1 private
Definition at line 51 of file SingleStreamingInput.h.
View newest version in sPHENIX GitHub at line 51 of file SingleStreamingInput.h
Referenced by EventNumberOffset().
int SingleStreamingInput::m_EventsThisFile = 0 private
Definition at line 53 of file SingleStreamingInput.h.
View newest version in sPHENIX GitHub at line 53 of file SingleStreamingInput.h
Referenced by fileopen().
std::map<int, uint64_t> SingleStreamingInput::m_FEEBclkMap private
Definition at line 57 of file SingleStreamingInput.h.
View newest version in sPHENIX GitHub at line 57 of file SingleStreamingInput.h
Referenced by CheckPoolDepth(), and Print().
Fun4AllEvtInputPoolManager* SingleStreamingInput::m_InputMgr = nullptr private
Definition at line 49 of file SingleStreamingInput.h.
View newest version in sPHENIX GitHub at line 49 of file SingleStreamingInput.h
Referenced by InputManager().
int SingleStreamingInput::m_RunNumber = 0 private
Definition at line 52 of file SingleStreamingInput.h.
View newest version in sPHENIX GitHub at line 52 of file SingleStreamingInput.h
Referenced by RunNumber().
Fun4AllStreamingInputManager* SingleStreamingInput::m_StreamingInputMgr = nullptr private
Definition at line 50 of file SingleStreamingInput.h.
View newest version in sPHENIX GitHub at line 50 of file SingleStreamingInput.h
Referenced by StreamingInputManager().
int SingleStreamingInput::m_SubsystemEnum {0} private
Definition at line 55 of file SingleStreamingInput.h.
View newest version in sPHENIX GitHub at line 55 of file SingleStreamingInput.h
Referenced by SubsystemEnum().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/framework/fun4allraw/SingleStreamingInput.h
coresoftware/blob/master/offline/framework/fun4allraw/SingleStreamingInput.cc