Analysis Software: kdfinder::Helix< T > Class Template Reference
kdfinder::Helix< T > Class Template Reference
#include <coresoftware/blob/master/offline/packages/PHTpcTracker/externals/kdfinder.hpp>
Public Member Functions
Helix (T c, T dip, T phase, const TVector< T > &o, int h=-1)
curvature, dip angle, phase, origin, h
Helix (const TVector< T > &p, const TVector< T > &o, T B, T q)
virtual ~Helix ()
T dipAngle () const
T curvature () const
T phase () const
T xcenter () const
T ycenter () const
T h () const
const TVector< T > & origin () const
TVector< double > momentum (T B) const
TVector< T > momentumAt (T s, T B) const
int charge (T B) const
T geometricSignedDistance (T x, T y)
T curvatureSignedDistance (T x, T y)
T geometricSignedDistance (const TVector< T > &pos)
T curvatureSignedDistance (const TVector< T > &pos)
void setParameters (T c, T dip, T phase, const TVector< T > &o, int h)
T x (T s) const
coordinates of helix at point s
T y (T s) const
T z (T s) const
TVector< T > at (T s) const
T cx (T s=0) const
pointing vector of helix at point s
T cy (T s=0) const
T cz (T s=0) const
TVector< T > cat (T s) const
T period () const
returns period length of helix
std::pair< T, T > pathLength (T r) const
path length at given r (cylindrical r)
std::pair< T, T > pathLength (T r, T x, T y)
path length at given r (cylindrical r, cylinder axis at x,y)
T pathLength (const TVector< T > &p, bool scanPeriods=true) const
path length at distance of closest approach to a given point
T pathLength (const TVector< T > &r, const TVector< T > &n) const
path length at intersection with plane
T pathLength (T x, T y) const
path length at distance of closest approach in the xy-plane to a given point
std::pair< T, T > pathLengths (const Helix &, T minStepSize=10 *0.0001, T minRange=10) const
path lengths at dca between two helices
T distance (const TVector< T > &p, bool scanPeriods=true) const
minimal distance between point and helix
bool valid (T world=1.e+5) const
checks for valid parametrization
int bad (T WorldSize=1.e+5) const
virtual void moveOrigin (T s)
move the origin along the helix to s which becomes then s=0
Static Public Attributes
static constexpr T NoSolution = 3.e+33
Protected Member Functions
Helix ()
void setCurvature (T val)
void setPhase (T val)
void setDipAngle (T val)
T fudgePathLength (const TVector< T > &p) const
value of S where distance in x-y plane is minimal
Protected Attributes
bool mSingularity = false
TVector< T > mOrigin
T mDipAngle = 0
T mCurvature = 0
T mPhase = 0
int mH = 0
T mCosDipAngle = 0
T mSinDipAngle = 0
T mCosPhase = 0
T mSinPhase = 0
Static Protected Attributes
static constexpr T meter = 100.0
static constexpr T meter2 = meter * meter
static constexpr T second = 1.0
static constexpr T nanosecond = 1.e-9
static constexpr T GeV = 1.0
static constexpr T MeV = 1.e-3
static constexpr T volt = 1.e-6 * MeV
static constexpr T c_light = 2.99792458e+8 * meter / second
static constexpr T tesla = 1.0
Detailed Description
template<class T>
class kdfinder::Helix< T >
Definition at line 443 of file kdfinder.hpp.
View newest version in sPHENIX GitHub at line 443 of file kdfinder.hpp
Constructor & Destructor Documentation
template<class T> kdfinder::Helix< T >::Helix (T c, T dip, T phase, const TVector< T > & o, int h = -1) inline
curvature, dip angle, phase, origin, h
Definition at line 447 of file kdfinder.hpp.
View newest version in sPHENIX GitHub at line 447 of file kdfinder.hpp
References kdfinder::Helix< T >::h(), and kdfinder::Helix< T >::setParameters().
template<class T> kdfinder::Helix< T >::Helix (const TVector< T > & p, const TVector< T > & o, T B, T q) inline
Definition at line 450 of file kdfinder.hpp.
View newest version in sPHENIX GitHub at line 450 of file kdfinder.hpp
References kdfinder::abs(), kdfinder::Helix< T >::c_light, kdfinder::Helix< T >::GeV, M_PI, kdfinder::Helix< T >::mCosDipAngle, kdfinder::Helix< T >::meter, kdfinder::Helix< T >::mH, kdfinder::Helix< T >::mOrigin, kdfinder::Helix< T >::nanosecond, kdfinder::TVector< T >::perp(), kdfinder::Helix< T >::setCurvature(), kdfinder::Helix< T >::setDipAngle(), kdfinder::Helix< T >::setPhase(), kdfinder::Helix< T >::tesla, kdfinder::TVector< T >::x(), kdfinder::TVector< T >::y(), and kdfinder::TVector< T >::z().
template<class T> virtual kdfinder::Helix< T >::~Helix () inline virtual
Definition at line 466 of file kdfinder.hpp.
View newest version in sPHENIX GitHub at line 466 of file kdfinder.hpp
template<class T> kdfinder::Helix< T >::Helix () inline protected
Definition at line 1101 of file kdfinder.hpp.
View newest version in sPHENIX GitHub at line 1101 of file kdfinder.hpp
Member Function Documentation
template<class T> TVector<T> kdfinder::Helix< T >::at (T s) const inline
Definition at line 608 of file kdfinder.hpp.
View newest version in sPHENIX GitHub at line 608 of file kdfinder.hpp
References kdfinder::Helix< T >::x(), kdfinder::Helix< T >::y(), and kdfinder::Helix< T >::z().
Referenced by kdfinder::Helix< T >::distance(), kdfinder::find_vertex_seeds(), kdfinder::Helix< T >::geometricSignedDistance(), kdfinder::Helix< T >::moveOrigin(), kdfinder::Helix< T >::pathLength(), and kdfinder::Helix< T >::pathLengths().
template<class T> int kdfinder::Helix< T >::bad (T WorldSize = 1.e+5) const inline
Definition at line 1042 of file kdfinder.hpp.
View newest version in sPHENIX GitHub at line 1042 of file kdfinder.hpp
References kdfinder::abs(), M_PI, kdfinder::Helix< T >::mCurvature, kdfinder::Helix< T >::mDipAngle, kdfinder::Helix< T >::mH, kdfinder::Helix< T >::mOrigin, Acts::UnitConstants::T, and WorldSize().
Referenced by kdfinder::Helix< T >::valid().
template<class T> TVector<T> kdfinder::Helix< T >::cat (T s) const inline
Definition at line 637 of file kdfinder.hpp.
View newest version in sPHENIX GitHub at line 637 of file kdfinder.hpp
References kdfinder::Helix< T >::cx(), kdfinder::Helix< T >::cy(), and kdfinder::Helix< T >::cz().
template<class T> int kdfinder::Helix< T >::charge (T B) const inline
Definition at line 516 of file kdfinder.hpp.
View newest version in sPHENIX GitHub at line 516 of file kdfinder.hpp
References kdfinder::Helix< T >::mH.
template<class T> T kdfinder::Helix< T >::curvature () const inline
Definition at line 469 of file kdfinder.hpp.
View newest version in sPHENIX GitHub at line 469 of file kdfinder.hpp
References kdfinder::Helix< T >::mCurvature.
Referenced by kdfinder::Helix< T >::pathLengths().
template<class T> T kdfinder::Helix< T >::curvatureSignedDistance (T x, T y) inline
Definition at line 547 of file kdfinder.hpp.
View newest version in sPHENIX GitHub at line 547 of file kdfinder.hpp
References kdfinder::abs(), kdfinder::Helix< T >::geometricSignedDistance(), kdfinder::Helix< T >::mH, and kdfinder::Helix< T >::mSingularity.
Referenced by kdfinder::Helix< T >::curvatureSignedDistance().
template<class T> T kdfinder::Helix< T >::curvatureSignedDistance (const TVector< T > & pos) inline
Definition at line 563 of file kdfinder.hpp.
View newest version in sPHENIX GitHub at line 563 of file kdfinder.hpp
References kdfinder::Helix< T >::curvatureSignedDistance(), kdfinder::Helix< T >::distance(), Acts::UnitConstants::T, kdfinder::TVector< T >::x(), and kdfinder::TVector< T >::y().
template<class T> T kdfinder::Helix< T >::cx (T s = 0) const inline
pointing vector of helix at point s
Definition at line 614 of file kdfinder.hpp.
View newest version in sPHENIX GitHub at line 614 of file kdfinder.hpp
References kdfinder::Helix< T >::mCosDipAngle, kdfinder::Helix< T >::mCurvature, kdfinder::Helix< T >::mH, kdfinder::Helix< T >::mPhase, kdfinder::Helix< T >::mSingularity, kdfinder::Helix< T >::mSinPhase, and Acts::UnitConstants::s.
Referenced by kdfinder::Helix< T >::cat(), hijing(), pygrvd(), pygrvl(), pygrvm(), pyrnm3(), pyrnmq(), and pytbdy().
template<class T> T kdfinder::Helix< T >::cy (T s = 0) const inline
Definition at line 623 of file kdfinder.hpp.
View newest version in sPHENIX GitHub at line 623 of file kdfinder.hpp
References kdfinder::Helix< T >::mCosDipAngle, kdfinder::Helix< T >::mCosPhase, kdfinder::Helix< T >::mCurvature, kdfinder::Helix< T >::mH, kdfinder::Helix< T >::mPhase, kdfinder::Helix< T >::mSingularity, and Acts::UnitConstants::s.
Referenced by kdfinder::Helix< T >::cat().
template<class T> T kdfinder::Helix< T >::cz (T s = 0) const inline
Definition at line 632 of file kdfinder.hpp.
View newest version in sPHENIX GitHub at line 632 of file kdfinder.hpp
References kdfinder::Helix< T >::mSinDipAngle.
Referenced by kdfinder::Helix< T >::cat().
template<class T> T kdfinder::Helix< T >::dipAngle () const inline
Definition at line 468 of file kdfinder.hpp.
View newest version in sPHENIX GitHub at line 468 of file kdfinder.hpp
References kdfinder::Helix< T >::mDipAngle.
template<class T> T kdfinder::Helix< T >::distance (const TVector< T > & p, bool scanPeriods = true) const inline
minimal distance between point and helix
Definition at line 1031 of file kdfinder.hpp.
View newest version in sPHENIX GitHub at line 1031 of file kdfinder.hpp
References kdfinder::abs(), kdfinder::Helix< T >::at(), and kdfinder::Helix< T >::pathLength().
Referenced by kdfinder::Helix< T >::curvatureSignedDistance(), kdfinder::Helix< T >::geometricSignedDistance(), and kdfinder::Helix< T >::pathLengths().
template<class T> T kdfinder::Helix< T >::fudgePathLength (const TVector< T > & p) const inline protected
value of S where distance in x-y plane is minimal
Definition at line 1144 of file kdfinder.hpp.
View newest version in sPHENIX GitHub at line 1144 of file kdfinder.hpp
References dx, dy, kdfinder::Helix< T >::mCosDipAngle, kdfinder::Helix< T >::mCosPhase, kdfinder::Helix< T >::mCurvature, kdfinder::Helix< T >::mH, kdfinder::Helix< T >::mOrigin, kdfinder::Helix< T >::mSingularity, kdfinder::Helix< T >::mSinPhase, Acts::UnitConstants::s, Acts::UnitConstants::T, kdfinder::TVector< T >::x(), and kdfinder::TVector< T >::y().
Referenced by kdfinder::Helix< T >::pathLength().
template<class T> T kdfinder::Helix< T >::geometricSignedDistance (T x, T y) inline
Definition at line 521 of file kdfinder.hpp.
View newest version in sPHENIX GitHub at line 521 of file kdfinder.hpp
References kdfinder::Helix< T >::at(), Acts::VectorHelpers::cross(), kdfinder::Helix< T >::momentumAt(), kdfinder::Helix< T >::mSingularity, kdfinder::Helix< T >::pathLength(), kdfinder::TVector< T >::perp(), position, kdfinder::TVector< T >::setZ(), Acts::UnitConstants::T, kdfinder::Helix< T >::tesla, kdfinder::TVector< T >::x(), and kdfinder::TVector< T >::y().
Referenced by kdfinder::Helix< T >::curvatureSignedDistance(), and kdfinder::Helix< T >::geometricSignedDistance().
template<class T> T kdfinder::Helix< T >::geometricSignedDistance (const TVector< T > & pos) inline
Definition at line 556 of file kdfinder.hpp.
View newest version in sPHENIX GitHub at line 556 of file kdfinder.hpp
References kdfinder::Helix< T >::distance(), kdfinder::Helix< T >::geometricSignedDistance(), Acts::UnitConstants::T, kdfinder::TVector< T >::x(), and kdfinder::TVector< T >::y().
template<class T> T kdfinder::Helix< T >::h () const inline
Definition at line 493 of file kdfinder.hpp.
View newest version in sPHENIX GitHub at line 493 of file kdfinder.hpp
References kdfinder::Helix< T >::mH.
Referenced by kdfinder::Helix< T >::Helix(), and kdfinder::Helix< T >::pathLengths().
template<class T> TVector<double> kdfinder::Helix< T >::momentum (T B) const inline
Definition at line 497 of file kdfinder.hpp.
View newest version in sPHENIX GitHub at line 497 of file kdfinder.hpp
References kdfinder::Helix< T >::c_light, kdfinder::Helix< T >::GeV, M_PI, kdfinder::Helix< T >::mCurvature, kdfinder::Helix< T >::mDipAngle, kdfinder::Helix< T >::meter, kdfinder::Helix< T >::mH, kdfinder::Helix< T >::mPhase, kdfinder::Helix< T >::mSingularity, kdfinder::Helix< T >::nanosecond, Acts::UnitConstants::T, and kdfinder::Helix< T >::tesla.
Referenced by kdfinder::Helix< T >::momentumAt().
template<class T> TVector<T> kdfinder::Helix< T >::momentumAt (T s, T B) const inline
Definition at line 509 of file kdfinder.hpp.
View newest version in sPHENIX GitHub at line 509 of file kdfinder.hpp
References kdfinder::Helix< T >::momentum(), and kdfinder::Helix< T >::moveOrigin().
Referenced by kdfinder::Helix< T >::geometricSignedDistance().
template<class T> virtual void kdfinder::Helix< T >::moveOrigin (T s) inline virtual
move the origin along the helix to s which becomes then s=0
Definition at line 1083 of file kdfinder.hpp.
View newest version in sPHENIX GitHub at line 1083 of file kdfinder.hpp
References kdfinder::Helix< T >::at(), kdfinder::Helix< T >::mOrigin, kdfinder::Helix< T >::mSingularity, kdfinder::Helix< T >::setPhase(), Acts::UnitConstants::T, kdfinder::TVector< T >::x(), kdfinder::Helix< T >::xcenter(), kdfinder::TVector< T >::y(), and kdfinder::Helix< T >::ycenter().
Referenced by kdfinder::Helix< T >::momentumAt().
template<class T> const TVector<T>& kdfinder::Helix< T >::origin () const inline
Definition at line 495 of file kdfinder.hpp.
View newest version in sPHENIX GitHub at line 495 of file kdfinder.hpp
References kdfinder::Helix< T >::mOrigin.
template<class T> std::pair<T, T> kdfinder::Helix< T >::pathLength (T r) const inline
path length at given r (cylindrical r)
Definition at line 653 of file kdfinder.hpp.
View newest version in sPHENIX GitHub at line 653 of file kdfinder.hpp
References kdfinder::Helix< T >::mCosDipAngle, kdfinder::Helix< T >::mCosPhase, kdfinder::Helix< T >::mCurvature, kdfinder::Helix< T >::mH, kdfinder::Helix< T >::mOrigin, kdfinder::Helix< T >::mPhase, kdfinder::Helix< T >::mSingularity, kdfinder::Helix< T >::mSinPhase, p, kdfinder::Helix< T >::period(), r, swap(), Acts::UnitConstants::T, t1, t2, and value.
Referenced by kdfinder::Helix< T >::distance(), kdfinder::find_vertex_seeds(), kdfinder::Helix< T >::geometricSignedDistance(), kdfinder::Helix< T >::pathLength(), and kdfinder::Helix< T >::pathLengths().
template<class T> std::pair<T, T> kdfinder::Helix< T >::pathLength (T r, T x, T y) inline
path length at given r (cylindrical r, cylinder axis at x,y)
Definition at line 755 of file kdfinder.hpp.
View newest version in sPHENIX GitHub at line 755 of file kdfinder.hpp
References kdfinder::Helix< T >::mOrigin, kdfinder::Helix< T >::pathLength(), Acts::UnitConstants::T, and x0.
template<class T> T kdfinder::Helix< T >::pathLength (const TVector< T > & p, bool scanPeriods = true) const inline
path length at distance of closest approach to a given point
Definition at line 769 of file kdfinder.hpp.
View newest version in sPHENIX GitHub at line 769 of file kdfinder.hpp
References kdfinder::abs(), kdfinder::Helix< T >::at(), d, dx, dy, dz, kdfinder::Helix< T >::fudgePathLength(), i, j, kdfinder::Helix< T >::mCosDipAngle, kdfinder::Helix< T >::mCosPhase, kdfinder::Helix< T >::mCurvature, kdfinder::Helix< T >::mH, kdfinder::Helix< T >::mOrigin, kdfinder::Helix< T >::mPhase, kdfinder::Helix< T >::mSinDipAngle, kdfinder::Helix< T >::mSingularity, kdfinder::Helix< T >::mSinPhase, kdfinder::Helix< T >::period(), Acts::UnitConstants::s, Acts::UnitConstants::T, kdfinder::TVector< T >::x(), kdfinder::TVector< T >::y(), and kdfinder::TVector< T >::z().
template<class T> T kdfinder::Helix< T >::pathLength (const TVector< T > & r, const TVector< T > & n) const inline
path length at intersection with plane
Definition at line 848 of file kdfinder.hpp.
View newest version in sPHENIX GitHub at line 848 of file kdfinder.hpp
References KFPMath::a, A, deltas(), i, kdfinder::Helix< T >::mCosDipAngle, kdfinder::Helix< T >::mCosPhase, kdfinder::Helix< T >::mCurvature, kdfinder::Helix< T >::mH, kdfinder::Helix< T >::mOrigin, kdfinder::Helix< T >::mPhase, kdfinder::Helix< T >::mSinDipAngle, kdfinder::Helix< T >::mSingularity, kdfinder::Helix< T >::mSinPhase, kdfinder::Helix< T >::NoSolution, r, Acts::UnitConstants::s, t, Acts::UnitConstants::T, Acts::UnitConstants::u, kdfinder::TVector< T >::x(), kdfinder::TVector< T >::y(), and kdfinder::TVector< T >::z().
template<class T> T kdfinder::Helix< T >::pathLength (T x, T y) const inline
path length at distance of closest approach in the xy-plane to a given point
Definition at line 928 of file kdfinder.hpp.
View newest version in sPHENIX GitHub at line 928 of file kdfinder.hpp
References kdfinder::Helix< T >::fudgePathLength().
template<class T> std::pair<T, T> kdfinder::Helix< T >::pathLengths (const Helix< T > & , T minStepSize = 10 * 0.0001, T minRange = 10) const inline
path lengths at dca between two helices
Definition at line 934 of file kdfinder.hpp.
View newest version in sPHENIX GitHub at line 934 of file kdfinder.hpp
References KFPMath::a, kdfinder::Helix< T >::at(), KFPMath::b, kdfinder::Helix< T >::curvature(), d, kdfinder::Helix< T >::distance(), dx, dy, Acts::UnitConstants::g, kdfinder::Helix< T >::h(), k, max, kdfinder::Helix< T >::mCosDipAngle, kdfinder::Helix< T >::mCosPhase, kdfinder::Helix< T >::mOrigin, kdfinder::Helix< T >::mSinDipAngle, kdfinder::Helix< T >::mSingularity, kdfinder::Helix< T >::mSinPhase, kdfinder::Helix< T >::NoSolution, kdfinder::Helix< T >::pathLength(), r1, r2, Acts::UnitConstants::s, s1, Acts::UnitConstants::T, kdfinder::Helix< T >::x(), kdfinder::Helix< T >::xcenter(), kdfinder::Helix< T >::y(), and kdfinder::Helix< T >::ycenter().
template<class T> T kdfinder::Helix< T >::period () const inline
returns period length of helix
Definition at line 643 of file kdfinder.hpp.
View newest version in sPHENIX GitHub at line 643 of file kdfinder.hpp
References M_PI, max, kdfinder::Helix< T >::mCosDipAngle, kdfinder::Helix< T >::mCurvature, kdfinder::Helix< T >::mH, and kdfinder::Helix< T >::mSingularity.
Referenced by kdfinder::Helix< T >::pathLength().
template<class T> T kdfinder::Helix< T >::phase () const inline
Definition at line 470 of file kdfinder.hpp.
View newest version in sPHENIX GitHub at line 470 of file kdfinder.hpp
References kdfinder::Helix< T >::mPhase.
template<class T> void kdfinder::Helix< T >::setCurvature (T val) inline protected
Definition at line 1103 of file kdfinder.hpp.
View newest version in sPHENIX GitHub at line 1103 of file kdfinder.hpp
References M_PI, kdfinder::Helix< T >::mCurvature, kdfinder::Helix< T >::mH, kdfinder::Helix< T >::mPhase, kdfinder::Helix< T >::mSingularity, and kdfinder::Helix< T >::setPhase().
Referenced by kdfinder::Helix< T >::Helix(), and kdfinder::Helix< T >::setParameters().
template<class T> void kdfinder::Helix< T >::setDipAngle (T val) inline protected
Definition at line 1136 of file kdfinder.hpp.
View newest version in sPHENIX GitHub at line 1136 of file kdfinder.hpp
References kdfinder::Helix< T >::mCosDipAngle, kdfinder::Helix< T >::mDipAngle, and kdfinder::Helix< T >::mSinDipAngle.
Referenced by kdfinder::Helix< T >::Helix(), and kdfinder::Helix< T >::setParameters().
template<class T> void kdfinder::Helix< T >::setParameters (T c, T dip, T phase, const TVector< T > & o, int h) inline
Definition at line 570 of file kdfinder.hpp.
View newest version in sPHENIX GitHub at line 570 of file kdfinder.hpp
References M_PI, kdfinder::Helix< T >::mH, kdfinder::Helix< T >::mOrigin, kdfinder::Helix< T >::mPhase, kdfinder::Helix< T >::mSingularity, kdfinder::Helix< T >::setCurvature(), kdfinder::Helix< T >::setDipAngle(), and kdfinder::Helix< T >::setPhase().
Referenced by kdfinder::Helix< T >::Helix().
template<class T> void kdfinder::Helix< T >::setPhase (T val) inline protected
Definition at line 1125 of file kdfinder.hpp.
View newest version in sPHENIX GitHub at line 1125 of file kdfinder.hpp
References M_PI, kdfinder::Helix< T >::mCosPhase, kdfinder::Helix< T >::mPhase, and kdfinder::Helix< T >::mSinPhase.
Referenced by kdfinder::Helix< T >::Helix(), kdfinder::Helix< T >::moveOrigin(), kdfinder::Helix< T >::setCurvature(), and kdfinder::Helix< T >::setParameters().
template<class T> bool kdfinder::Helix< T >::valid (T world = 1.e+5) const inline
checks for valid parametrization
Definition at line 1037 of file kdfinder.hpp.
View newest version in sPHENIX GitHub at line 1037 of file kdfinder.hpp
References kdfinder::Helix< T >::bad(), and Acts::Test::world.
template<class T> T kdfinder::Helix< T >::x (T s) const inline
coordinates of helix at point s
Definition at line 585 of file kdfinder.hpp.
View newest version in sPHENIX GitHub at line 585 of file kdfinder.hpp
References kdfinder::Helix< T >::mCosDipAngle, kdfinder::Helix< T >::mCosPhase, kdfinder::Helix< T >::mCurvature, kdfinder::Helix< T >::mH, kdfinder::Helix< T >::mOrigin, kdfinder::Helix< T >::mPhase, kdfinder::Helix< T >::mSingularity, and kdfinder::Helix< T >::mSinPhase.
Referenced by kdfinder::Helix< T >::at(), and kdfinder::Helix< T >::pathLengths().
template<class T> T kdfinder::Helix< T >::xcenter () const inline
Definition at line 471 of file kdfinder.hpp.
View newest version in sPHENIX GitHub at line 471 of file kdfinder.hpp
References kdfinder::Helix< T >::mCosPhase, kdfinder::Helix< T >::mCurvature, kdfinder::Helix< T >::mOrigin, and kdfinder::Helix< T >::mSingularity.
Referenced by kdfinder::Helix< T >::moveOrigin(), and kdfinder::Helix< T >::pathLengths().
template<class T> T kdfinder::Helix< T >::y (T s) const inline
Definition at line 594 of file kdfinder.hpp.
View newest version in sPHENIX GitHub at line 594 of file kdfinder.hpp
References kdfinder::Helix< T >::mCosDipAngle, kdfinder::Helix< T >::mCosPhase, kdfinder::Helix< T >::mCurvature, kdfinder::Helix< T >::mH, kdfinder::Helix< T >::mOrigin, kdfinder::Helix< T >::mPhase, kdfinder::Helix< T >::mSingularity, and kdfinder::Helix< T >::mSinPhase.
Referenced by kdfinder::Helix< T >::at(), and kdfinder::Helix< T >::pathLengths().
template<class T> T kdfinder::Helix< T >::ycenter () const inline
Definition at line 482 of file kdfinder.hpp.
View newest version in sPHENIX GitHub at line 482 of file kdfinder.hpp
References kdfinder::Helix< T >::mCurvature, kdfinder::Helix< T >::mOrigin, kdfinder::Helix< T >::mSingularity, and kdfinder::Helix< T >::mSinPhase.
Referenced by kdfinder::Helix< T >::moveOrigin(), and kdfinder::Helix< T >::pathLengths().
template<class T> T kdfinder::Helix< T >::z (T s) const inline
Definition at line 603 of file kdfinder.hpp.
View newest version in sPHENIX GitHub at line 603 of file kdfinder.hpp
References kdfinder::Helix< T >::mOrigin, and kdfinder::Helix< T >::mSinDipAngle.
Referenced by kdfinder::Helix< T >::at().
Member Data Documentation
template<class T> constexpr T kdfinder::Helix< T >::c_light = 2.99792458e+8 * meter / second static protected
Definition at line 1180 of file kdfinder.hpp.
View newest version in sPHENIX GitHub at line 1180 of file kdfinder.hpp
Referenced by kdfinder::Helix< T >::Helix(), and kdfinder::Helix< T >::momentum().
template<class T> constexpr T kdfinder::Helix< T >::GeV = 1.0 static protected
Definition at line 1177 of file kdfinder.hpp.
View newest version in sPHENIX GitHub at line 1177 of file kdfinder.hpp
Referenced by kdfinder::Helix< T >::Helix(), and kdfinder::Helix< T >::momentum().
template<class T> T kdfinder::Helix< T >::mCosDipAngle = 0 protected
Definition at line 1168 of file kdfinder.hpp.
View newest version in sPHENIX GitHub at line 1168 of file kdfinder.hpp
Referenced by kdfinder::Helix< T >::cx(), kdfinder::Helix< T >::cy(), kdfinder::Helix< T >::fudgePathLength(), kdfinder::Helix< T >::Helix(), kdfinder::Helix< T >::pathLength(), kdfinder::Helix< T >::pathLengths(), kdfinder::Helix< T >::period(), kdfinder::Helix< T >::setDipAngle(), kdfinder::Helix< T >::x(), and kdfinder::Helix< T >::y().
template<class T> T kdfinder::Helix< T >::mCosPhase = 0 protected
Definition at line 1170 of file kdfinder.hpp.
View newest version in sPHENIX GitHub at line 1170 of file kdfinder.hpp
Referenced by kdfinder::Helix< T >::cy(), kdfinder::Helix< T >::fudgePathLength(), kdfinder::Helix< T >::pathLength(), kdfinder::Helix< T >::pathLengths(), kdfinder::Helix< T >::setPhase(), kdfinder::Helix< T >::x(), kdfinder::Helix< T >::xcenter(), and kdfinder::Helix< T >::y().
template<class T> T kdfinder::Helix< T >::mCurvature = 0 protected
Definition at line 1164 of file kdfinder.hpp.
View newest version in sPHENIX GitHub at line 1164 of file kdfinder.hpp
Referenced by kdfinder::Helix< T >::bad(), kdfinder::Helix< T >::curvature(), kdfinder::Helix< T >::cx(), kdfinder::Helix< T >::cy(), kdfinder::Helix< T >::fudgePathLength(), kdfinder::Helix< T >::momentum(), kdfinder::Helix< T >::pathLength(), kdfinder::Helix< T >::period(), kdfinder::Helix< T >::setCurvature(), kdfinder::Helix< T >::x(), kdfinder::Helix< T >::xcenter(), kdfinder::Helix< T >::y(), and kdfinder::Helix< T >::ycenter().
template<class T> T kdfinder::Helix< T >::mDipAngle = 0 protected
Definition at line 1163 of file kdfinder.hpp.
View newest version in sPHENIX GitHub at line 1163 of file kdfinder.hpp
Referenced by kdfinder::Helix< T >::bad(), kdfinder::Helix< T >::dipAngle(), kdfinder::Helix< T >::momentum(), and kdfinder::Helix< T >::setDipAngle().
template<class T> constexpr T kdfinder::Helix< T >::meter = 100.0 static protected
Definition at line 1173 of file kdfinder.hpp.
View newest version in sPHENIX GitHub at line 1173 of file kdfinder.hpp
Referenced by kdfinder::Helix< T >::Helix(), and kdfinder::Helix< T >::momentum().
template<class T> constexpr T kdfinder::Helix< T >::meter2 = meter * meter static protected
Definition at line 1174 of file kdfinder.hpp.
View newest version in sPHENIX GitHub at line 1174 of file kdfinder.hpp
template<class T> constexpr T kdfinder::Helix< T >::MeV = 1.e-3 static protected
Definition at line 1178 of file kdfinder.hpp.
View newest version in sPHENIX GitHub at line 1178 of file kdfinder.hpp
template<class T> int kdfinder::Helix< T >::mH = 0 protected
Definition at line 1166 of file kdfinder.hpp.
View newest version in sPHENIX GitHub at line 1166 of file kdfinder.hpp
Referenced by kdfinder::Helix< T >::bad(), kdfinder::Helix< T >::charge(), kdfinder::Helix< T >::curvatureSignedDistance(), kdfinder::Helix< T >::cx(), kdfinder::Helix< T >::cy(), kdfinder::Helix< T >::fudgePathLength(), kdfinder::Helix< T >::h(), kdfinder::Helix< T >::Helix(), kdfinder::Helix< T >::momentum(), kdfinder::Helix< T >::pathLength(), kdfinder::Helix< T >::period(), kdfinder::Helix< T >::setCurvature(), kdfinder::Helix< T >::setParameters(), kdfinder::Helix< T >::x(), and kdfinder::Helix< T >::y().
template<class T> TVector<T> kdfinder::Helix< T >::mOrigin protected
Definition at line 1162 of file kdfinder.hpp.
View newest version in sPHENIX GitHub at line 1162 of file kdfinder.hpp
Referenced by kdfinder::Helix< T >::bad(), kdfinder::Helix< T >::fudgePathLength(), kdfinder::Helix< T >::Helix(), kdfinder::Helix< T >::moveOrigin(), kdfinder::Helix< T >::origin(), kdfinder::Helix< T >::pathLength(), kdfinder::Helix< T >::pathLengths(), kdfinder::Helix< T >::setParameters(), kdfinder::Helix< T >::x(), kdfinder::Helix< T >::xcenter(), kdfinder::Helix< T >::y(), kdfinder::Helix< T >::ycenter(), and kdfinder::Helix< T >::z().
template<class T> T kdfinder::Helix< T >::mPhase = 0 protected
Definition at line 1165 of file kdfinder.hpp.
View newest version in sPHENIX GitHub at line 1165 of file kdfinder.hpp
Referenced by kdfinder::Helix< T >::cx(), kdfinder::Helix< T >::cy(), kdfinder::Helix< T >::momentum(), kdfinder::Helix< T >::pathLength(), kdfinder::Helix< T >::phase(), kdfinder::Helix< T >::setCurvature(), kdfinder::Helix< T >::setParameters(), kdfinder::Helix< T >::setPhase(), kdfinder::Helix< T >::x(), and kdfinder::Helix< T >::y().
template<class T> T kdfinder::Helix< T >::mSinDipAngle = 0 protected
Definition at line 1169 of file kdfinder.hpp.
View newest version in sPHENIX GitHub at line 1169 of file kdfinder.hpp
Referenced by kdfinder::Helix< T >::cz(), kdfinder::Helix< T >::pathLength(), kdfinder::Helix< T >::pathLengths(), kdfinder::Helix< T >::setDipAngle(), and kdfinder::Helix< T >::z().
template<class T> bool kdfinder::Helix< T >::mSingularity = false protected
Definition at line 1161 of file kdfinder.hpp.
View newest version in sPHENIX GitHub at line 1161 of file kdfinder.hpp
Referenced by kdfinder::Helix< T >::curvatureSignedDistance(), kdfinder::Helix< T >::cx(), kdfinder::Helix< T >::cy(), kdfinder::Helix< T >::fudgePathLength(), kdfinder::Helix< T >::geometricSignedDistance(), kdfinder::Helix< T >::momentum(), kdfinder::Helix< T >::moveOrigin(), kdfinder::Helix< T >::pathLength(), kdfinder::Helix< T >::pathLengths(), kdfinder::Helix< T >::period(), kdfinder::Helix< T >::setCurvature(), kdfinder::Helix< T >::setParameters(), kdfinder::Helix< T >::x(), kdfinder::Helix< T >::xcenter(), kdfinder::Helix< T >::y(), and kdfinder::Helix< T >::ycenter().
template<class T> T kdfinder::Helix< T >::mSinPhase = 0 protected
Definition at line 1171 of file kdfinder.hpp.
View newest version in sPHENIX GitHub at line 1171 of file kdfinder.hpp
Referenced by kdfinder::Helix< T >::cx(), kdfinder::Helix< T >::fudgePathLength(), kdfinder::Helix< T >::pathLength(), kdfinder::Helix< T >::pathLengths(), kdfinder::Helix< T >::setPhase(), kdfinder::Helix< T >::x(), kdfinder::Helix< T >::y(), and kdfinder::Helix< T >::ycenter().
template<class T> constexpr T kdfinder::Helix< T >::nanosecond = 1.e-9 static protected
Definition at line 1176 of file kdfinder.hpp.
View newest version in sPHENIX GitHub at line 1176 of file kdfinder.hpp
Referenced by kdfinder::Helix< T >::Helix(), and kdfinder::Helix< T >::momentum().
template<class T> constexpr T kdfinder::Helix< T >::NoSolution = 3.e+33 static
Definition at line 1098 of file kdfinder.hpp.
View newest version in sPHENIX GitHub at line 1098 of file kdfinder.hpp
Referenced by kdfinder::Helix< T >::pathLength(), and kdfinder::Helix< T >::pathLengths().
template<class T> constexpr T kdfinder::Helix< T >::second = 1.0 static protected
Definition at line 1175 of file kdfinder.hpp.
View newest version in sPHENIX GitHub at line 1175 of file kdfinder.hpp
Referenced by PHTpcTrackFollower::get_projected_coordinate().
template<class T> constexpr T kdfinder::Helix< T >::tesla = 1.0 static protected
Definition at line 1181 of file kdfinder.hpp.
View newest version in sPHENIX GitHub at line 1181 of file kdfinder.hpp
Referenced by kdfinder::Helix< T >::geometricSignedDistance(), kdfinder::Helix< T >::Helix(), and kdfinder::Helix< T >::momentum().
template<class T> constexpr T kdfinder::Helix< T >::volt = 1.e-6 * MeV static protected
Definition at line 1179 of file kdfinder.hpp.
View newest version in sPHENIX GitHub at line 1179 of file kdfinder.hpp
The documentation for this class was generated from the following file:
coresoftware/blob/master/offline/packages/PHTpcTracker/externals/kdfinder.hpp