Analysis Software: alignmentTransformationContainer Class Reference
alignmentTransformationContainer Class Reference
Container class for Alignment transformations.
#include <coresoftware/blob/master/offline/packages/trackbase/alignmentTransformationContainer.h>
Public Member Functions
alignmentTransformationContainer ()
virtual ~alignmentTransformationContainer ()
void Reset ()
void identify (std::ostream &os=std::cout)
void addTransform (Acts::GeometryIdentifier, Acts::Transform3)
Acts::Transform3 & getTransform (Acts::GeometryIdentifier id)
void replaceTransform (const Acts::GeometryIdentifier id, Acts::Transform3 transform)
const std::vector< std::vector
< Acts::Transform3 > > & getMap () const
void setMisalignmentFactor (uint8_t layer, double factor)
const double & getMisalignmentFactor (uint8_t layer) const
Public Member Functions inherited from Acts::ContextType
ContextType ()=default
template<typename T >
ContextType (T &&value)
Static Public Attributes
static bool use_alignment = false
Private Member Functions
unsigned int getsphlayer (Acts::GeometryIdentifier)
ClassDef (alignmentTransformationContainer, 1)
Private Attributes
std::map< unsigned int,
unsigned int > base_layer_map = { {10, 0}, {12,3}, {14,7}, {16,55} }
std::vector< std::vector
< Acts::Transform3 > > transformVec
std::map< uint8_t, double > m_misalignmentFactor
Map of TrkrDefs::Layer to misalignment factor.
Detailed Description
Container class for Alignment transformations.
Association object holding transformations associated with given tracker hitset
Definition at line 30 of file alignmentTransformationContainer.h.
View newest version in sPHENIX GitHub at line 30 of file alignmentTransformationContainer.h
Constructor & Destructor Documentation
alignmentTransformationContainer::alignmentTransformationContainer ()
Definition at line 18 of file alignmentTransformationContainer.cc.
View newest version in sPHENIX GitHub at line 18 of file alignmentTransformationContainer.cc
References layer, and m_misalignmentFactor.
virtual alignmentTransformationContainer::~alignmentTransformationContainer () inline virtual
Definition at line 37 of file alignmentTransformationContainer.h.
View newest version in sPHENIX GitHub at line 37 of file alignmentTransformationContainer.h
Member Function Documentation
void alignmentTransformationContainer::addTransform (Acts::GeometryIdentifier id, Acts::Transform3 transform)
Definition at line 76 of file alignmentTransformationContainer.cc.
View newest version in sPHENIX GitHub at line 76 of file alignmentTransformationContainer.cc
References getsphlayer(), Acts::Test::transform, and transformVec.
Referenced by AlignmentTransformation::createMap().
alignmentTransformationContainer::ClassDef (alignmentTransformationContainer , 1) private
const std::vector< std::vector< Acts::Transform3 > > & alignmentTransformationContainer::getMap () const
Definition at line 150 of file alignmentTransformationContainer.cc.
View newest version in sPHENIX GitHub at line 150 of file alignmentTransformationContainer.cc
References transformVec.
Referenced by sPHENIXActsDetectorElement::transform().
const double& alignmentTransformationContainer::getMisalignmentFactor (uint8_t layer) const inline
Definition at line 46 of file alignmentTransformationContainer.h.
View newest version in sPHENIX GitHub at line 46 of file alignmentTransformationContainer.h
References m_misalignmentFactor.
unsigned int alignmentTransformationContainer::getsphlayer (Acts::GeometryIdentifier id) private
Definition at line 155 of file alignmentTransformationContainer.cc.
View newest version in sPHENIX GitHub at line 155 of file alignmentTransformationContainer.cc
References base_layer_map, and layer.
Referenced by addTransform(), getTransform(), and replaceTransform().
Acts::Transform3 & alignmentTransformationContainer::getTransform (Acts::GeometryIdentifier id)
Definition at line 119 of file alignmentTransformationContainer.cc.
View newest version in sPHENIX GitHub at line 119 of file alignmentTransformationContainer.cc
References getsphlayer(), and transformVec.
Referenced by MakeSourceLinks::getSourceLinks(), and MakeSourceLinks::resetTransientTransformMap().
void alignmentTransformationContainer::identify (std::ostream & os = std::cout)
Definition at line 53 of file alignmentTransformationContainer.cc.
View newest version in sPHENIX GitHub at line 53 of file alignmentTransformationContainer.cc
References i, and transformVec.
void alignmentTransformationContainer::replaceTransform (const Acts::GeometryIdentifier id, Acts::Transform3 transform)
Definition at line 134 of file alignmentTransformationContainer.cc.
View newest version in sPHENIX GitHub at line 134 of file alignmentTransformationContainer.cc
References getsphlayer(), Acts::Test::transform, and transformVec.
Referenced by MakeSourceLinks::getSourceLinks(), and MakeSourceLinks::resetTransientTransformMap().
void alignmentTransformationContainer::Reset ()
Definition at line 36 of file alignmentTransformationContainer.cc.
View newest version in sPHENIX GitHub at line 36 of file alignmentTransformationContainer.cc
References i, and transformVec.
void alignmentTransformationContainer::setMisalignmentFactor (uint8_t layer, double factor)
Definition at line 25 of file alignmentTransformationContainer.cc.
View newest version in sPHENIX GitHub at line 25 of file alignmentTransformationContainer.cc
References it, and m_misalignmentFactor.
Referenced by AlignmentTransformation::misalignmentFactor().
Member Data Documentation
std::map<unsigned int, unsigned int> alignmentTransformationContainer::base_layer_map = { {10, 0}, {12,3}, {14,7}, {16,55} } private
Definition at line 53 of file alignmentTransformationContainer.h.
View newest version in sPHENIX GitHub at line 53 of file alignmentTransformationContainer.h
Referenced by getsphlayer().
std::map<uint8_t, double> alignmentTransformationContainer::m_misalignmentFactor private
Map of TrkrDefs::Layer to misalignment factor.
Definition at line 58 of file alignmentTransformationContainer.h.
View newest version in sPHENIX GitHub at line 58 of file alignmentTransformationContainer.h
Referenced by alignmentTransformationContainer(), getMisalignmentFactor(), and setMisalignmentFactor().
std::vector< std::vector<Acts::Transform3> > alignmentTransformationContainer::transformVec private
Definition at line 55 of file alignmentTransformationContainer.h.
View newest version in sPHENIX GitHub at line 55 of file alignmentTransformationContainer.h
Referenced by addTransform(), getMap(), getTransform(), identify(), replaceTransform(), and Reset().
bool alignmentTransformationContainer::use_alignment = false static
Definition at line 47 of file alignmentTransformationContainer.h.
View newest version in sPHENIX GitHub at line 47 of file alignmentTransformationContainer.h
Referenced by AlignmentTransformation::createMap(), TrackResiduals::fillClusterBranches(), TpcClusterizer::process_event(), HelicalFitter::process_event(), and sPHENIXActsDetectorElement::transform().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/trackbase/alignmentTransformationContainer.h
coresoftware/blob/master/offline/packages/trackbase/alignmentTransformationContainer.cc