Analysis Software: coresoftware/blob/master/calibrations/calorimeter/calo_emc_pi0_tbt/macro/runLCELoop.C File Reference
runLCELoop.C File Reference
#include <calib_emc_pi0/CaloCalibEmc_Pi0.h>
Functions
void runLCELoop (int nevents=-1, const char *ifile="treetest_g4cemc_eval.root", const char *ofile="treetest1_g4cemc_eval.root")
Function Documentation
void runLCELoop (int nevents = -1, const char * ifile = "treetest_g4cemc_eval.root", const char * ofile = "treetest1_g4cemc_eval.root")
Definition at line 2 of file runLCELoop.C.
View newest version in sPHENIX GitHub at line 2 of file runLCELoop.C
References CaloCalibEmc_Pi0::End(), CaloCalibEmc_Pi0::InitRun(), CaloCalibEmc_Pi0::Loop(), nevents(), and ofile.