Analysis Software: acts/blob/sPHENIX/Examples/Run/Common/src/GeometryExampleBase.cpp File Reference
GeometryExampleBase.cpp File Reference
#include "ActsExamples/Detector/IBaseDetector.hpp"
#include "ActsExamples/Framework/AlgorithmContext.hpp"
#include "ActsExamples/Framework/IContextDecorator.hpp"
#include "ActsExamples/Framework/WhiteBoard.hpp"
#include "ActsExamples/Geometry/CommonGeometry.hpp"
#include "ActsExamples/Io/Csv/CsvTrackingGeometryWriter.hpp"
#include "ActsExamples/Io/Json/JsonMaterialWriter.hpp"
#include "ActsExamples/Io/Json/JsonSurfacesWriter.hpp"
#include "ActsExamples/Io/Root/RootMaterialWriter.hpp"
#include "ActsExamples/Options/CommonOptions.hpp"
#include "ActsExamples/Options/CsvOptionsWriter.hpp"
#include "ActsExamples/Options/JsonOptionsWriter.hpp"
#include "ActsExamples/Plugins/Obj/ObjTrackingGeometryWriter.hpp"
#include "ActsExamples/Plugins/Obj/ObjWriterOptions.hpp"
#include "ActsExamples/Utilities/Options.hpp"
#include "ActsExamples/Utilities/Paths.hpp"
#include <Acts/Geometry/GeometryContext.hpp>
#include <Acts/Geometry/TrackingGeometry.hpp>
#include <Acts/Utilities/Logger.hpp>
#include <memory>
#include <string>
#include <vector>
Functions
int processGeometry (int argc, char *argv[], ActsExamples::IBaseDetector &detector)
method to process a geometry
Function Documentation
int processGeometry (int argc, char * argv[], ActsExamples::IBaseDetector & detector)
method to process a geometry
Parameters
detector The detector descriptor instance
Decorate the context
Definition at line 33 of file GeometryExampleBase.cpp.
View newest version in sPHENIX GitHub at line 33 of file GeometryExampleBase.cpp
References ActsExamples::Options::addCsvWriterOptions(), ActsExamples::Options::addGeometryOptions(), ActsExamples::Options::addJsonWriterOptions(), ActsExamples::Options::addMaterialOptions(), ActsExamples::Options::addObjWriterOptions(), ActsExamples::IBaseDetector::addOptions(), ActsExamples::Options::addOutputOptions(), ActsExamples::Options::addSequencerOptions(), ActsExamples::Geometry::build(), Acts::MaterialMapJsonConverter::Config::context, ActsExamples::JsonMaterialWriter::Config::converterCfg, ActsExamples::Sequencer::Config::events, ActsExamples::JsonMaterialWriter::Config::fileName, ActsExamples::RootMaterialWriter::Config::filePath, material_mapping_optimisation::format, ActsExamples::AlgorithmContext::geoContext, Acts::Test::geometry, Acts::getDefaultLogger(), telescope_simulation::logLevel, ActsExamples::Options::makeDefaultOptions(), testing::internal::move(), nEvents, outputDir, ActsExamples::CsvTrackingGeometryWriter::Config::outputDir, ActsExamples::Options::parse(), Acts::MaterialMapJsonConverter::Config::processApproaches, Acts::MaterialMapJsonConverter::Config::processBoundaries, Acts::MaterialMapJsonConverter::Config::processDenseVolumes, Acts::MaterialMapJsonConverter::Config::processNonMaterial, Acts::MaterialMapJsonConverter::Config::processRepresenting, Acts::MaterialMapJsonConverter::Config::processSensitives, Acts::MaterialMapJsonConverter::Config::processVolumes, ActsExamples::Options::readJsonSurfacesWriterConfig(), ActsExamples::Options::readLogLevel(), ActsExamples::Options::readObjTrackingGeometryWriterConfig(), ActsExamples::Options::readSequencerConfig(), SUCCESS, Acts::tGeometry, to_string(), ActsExamples::CsvTrackingGeometryWriter::Config::trackingGeometry, ActsExamples::JsonMaterialWriter::write(), ActsExamples::RootMaterialWriter::write(), ActsExamples::JsonMaterialWriter::Config::writeFormat, and ActsExamples::CsvTrackingGeometryWriter::Config::writePerEvent.
Referenced by main().