Analysis Software: TrackStateInfo_v1 Class Reference
TrackStateInfo_v1 Class Reference
#include <coresoftware/blob/master/offline/packages/trackbase_historic/TrackStateInfo_v1.h>
Public Member Functions
TrackStateInfo_v1 ()=default
~TrackStateInfo_v1 () override=default
void identify (std::ostream &os=std::cout) const override
void Reset () override
Clear Event.
PHObject * CloneMe () const override
Virtual copy constructor.
void CopyFrom (const TrackStateInfo &) override
copy content from base class
void CopyFrom (TrackStateInfo *source) override
copy content from base class
float get_x () const override
void set_x (float x) override
float get_y () const override
void set_y (float y) override
float get_z () const override
void set_z (float z) override
float get_pos (unsigned int i) const override
float get_px () const override
void set_px (float px) override
float get_py () const override
void set_py (float py) override
float get_pz () const override
void set_pz (float pz) override
float get_mom (unsigned int i) const override
float get_p () const override
float get_pt () const override
float get_eta () const override
float get_phi () const override
float get_covariance (int i, int j) const override
void set_covariance (int i, int j, float value) override
Public Member Functions inherited from TrackStateInfo
TrackStateInfo ()=default
~TrackStateInfo () override=default
int isValid () const override
isValid returns non zero if object contains vailid data
Public Member Functions inherited from PHObject
PHObject ()
ctor
~PHObject () override
dtor
virtual PHObject * clone () const final
PHObject * Clone (const char *newname="") const final
void Copy (TObject &object) const final
virtual int Integrate () const
virtual int Integrate (PHObject *)
virtual void CopyFrom (const PHObject *obj)
Private Attributes
float m_Momentum [3] = {std::numeric_limits<float>::quiet_NaN()}
float m_Position [3] = {std::numeric_limits<float>::quiet_NaN()}
float m_Covariance [21] = {std::numeric_limits<float>::quiet_NaN()}
Detailed Description
Definition at line 16 of file TrackStateInfo_v1.h.
View newest version in sPHENIX GitHub at line 16 of file TrackStateInfo_v1.h
Constructor & Destructor Documentation
TrackStateInfo_v1::TrackStateInfo_v1 () default
Referenced by CloneMe(), and Reset().
TrackStateInfo_v1::~TrackStateInfo_v1 () override default
Member Function Documentation
PHObject* TrackStateInfo_v1::CloneMe () const inline override virtual
Virtual copy constructor.
Reimplemented from TrackStateInfo.
Definition at line 40 of file TrackStateInfo_v1.h.
View newest version in sPHENIX GitHub at line 40 of file TrackStateInfo_v1.h
References TrackStateInfo_v1().
void TrackStateInfo_v1::CopyFrom (const TrackStateInfo &) inline override virtual
copy content from base class
Reimplemented from TrackStateInfo.
Definition at line 45 of file TrackStateInfo_v1.h.
View newest version in sPHENIX GitHub at line 45 of file TrackStateInfo_v1.h
Referenced by CopyFrom().
void TrackStateInfo_v1::CopyFrom (TrackStateInfo *) inline override virtual
copy content from base class
Reimplemented from TrackStateInfo.
Definition at line 46 of file TrackStateInfo_v1.h.
View newest version in sPHENIX GitHub at line 46 of file TrackStateInfo_v1.h
References CopyFrom().
float TrackStateInfo_v1::get_covariance (int i, int j) const override virtual
Reimplemented from TrackStateInfo.
Definition at line 22 of file TrackStateInfo_v1.cc.
View newest version in sPHENIX GitHub at line 22 of file TrackStateInfo_v1.cc
References m_Covariance.
Referenced by SvtxTrackInfo_v1::get_covariance().
float TrackStateInfo_v1::get_eta () const inline override virtual
Reimplemented from TrackStateInfo.
Definition at line 79 of file TrackStateInfo_v1.h.
View newest version in sPHENIX GitHub at line 79 of file TrackStateInfo_v1.h
References get_pt(), and get_pz().
float TrackStateInfo_v1::get_mom (unsigned int i) const inline override virtual
Reimplemented from TrackStateInfo.
Definition at line 75 of file TrackStateInfo_v1.h.
View newest version in sPHENIX GitHub at line 75 of file TrackStateInfo_v1.h
References i, and m_Momentum.
Referenced by SvtxTrackInfo_v1::get_mom().
float TrackStateInfo_v1::get_p () const inline override virtual
Reimplemented from TrackStateInfo.
Definition at line 77 of file TrackStateInfo_v1.h.
View newest version in sPHENIX GitHub at line 77 of file TrackStateInfo_v1.h
References get_px(), get_py(), and get_pz().
float TrackStateInfo_v1::get_phi () const inline override virtual
Reimplemented from TrackStateInfo.
Definition at line 80 of file TrackStateInfo_v1.h.
View newest version in sPHENIX GitHub at line 80 of file TrackStateInfo_v1.h
References get_px(), and get_py().
float TrackStateInfo_v1::get_pos (unsigned int i) const inline override virtual
Reimplemented from TrackStateInfo.
Definition at line 64 of file TrackStateInfo_v1.h.
View newest version in sPHENIX GitHub at line 64 of file TrackStateInfo_v1.h
References i, and m_Position.
Referenced by SvtxTrackInfo_v1::get_pos().
float TrackStateInfo_v1::get_pt () const inline override virtual
Reimplemented from TrackStateInfo.
Definition at line 78 of file TrackStateInfo_v1.h.
View newest version in sPHENIX GitHub at line 78 of file TrackStateInfo_v1.h
References get_px(), and get_py().
Referenced by get_eta().
float TrackStateInfo_v1::get_px () const inline override virtual
Reimplemented from TrackStateInfo.
Definition at line 66 of file TrackStateInfo_v1.h.
View newest version in sPHENIX GitHub at line 66 of file TrackStateInfo_v1.h
References m_Momentum.
Referenced by get_p(), get_phi(), get_pt(), and SvtxTrackInfo_v1::get_px().
float TrackStateInfo_v1::get_py () const inline override virtual
Reimplemented from TrackStateInfo.
Definition at line 69 of file TrackStateInfo_v1.h.
View newest version in sPHENIX GitHub at line 69 of file TrackStateInfo_v1.h
References m_Momentum.
Referenced by get_p(), get_phi(), get_pt(), and SvtxTrackInfo_v1::get_py().
float TrackStateInfo_v1::get_pz () const inline override virtual
Reimplemented from TrackStateInfo.
Definition at line 72 of file TrackStateInfo_v1.h.
View newest version in sPHENIX GitHub at line 72 of file TrackStateInfo_v1.h
References m_Momentum.
Referenced by get_eta(), get_p(), and SvtxTrackInfo_v1::get_pz().
float TrackStateInfo_v1::get_x () const inline override virtual
Reimplemented from TrackStateInfo.
Definition at line 55 of file TrackStateInfo_v1.h.
View newest version in sPHENIX GitHub at line 55 of file TrackStateInfo_v1.h
References m_Position.
Referenced by SvtxTrackInfo_v1::get_x().
float TrackStateInfo_v1::get_y () const inline override virtual
Reimplemented from TrackStateInfo.
Definition at line 58 of file TrackStateInfo_v1.h.
View newest version in sPHENIX GitHub at line 58 of file TrackStateInfo_v1.h
References m_Position.
Referenced by SvtxTrackInfo_v1::get_y().
float TrackStateInfo_v1::get_z () const inline override virtual
Reimplemented from TrackStateInfo.
Definition at line 61 of file TrackStateInfo_v1.h.
View newest version in sPHENIX GitHub at line 61 of file TrackStateInfo_v1.h
References m_Position.
Referenced by SvtxTrackInfo_v1::get_z().
void TrackStateInfo_v1::identify (std::ostream & os = std::cout) const inline override virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from TrackStateInfo.
Definition at line 34 of file TrackStateInfo_v1.h.
View newest version in sPHENIX GitHub at line 34 of file TrackStateInfo_v1.h
References os.
void TrackStateInfo_v1::Reset () inline override virtual
Clear Event.
Reimplemented from PHObject.
Definition at line 38 of file TrackStateInfo_v1.h.
View newest version in sPHENIX GitHub at line 38 of file TrackStateInfo_v1.h
References TrackStateInfo_v1().
void TrackStateInfo_v1::set_covariance (int i, int j, float value) override virtual
Reimplemented from TrackStateInfo.
Definition at line 26 of file TrackStateInfo_v1.cc.
View newest version in sPHENIX GitHub at line 26 of file TrackStateInfo_v1.cc
References m_Covariance, and value.
Referenced by SvtxTrackInfo_v1::set_covariance().
void TrackStateInfo_v1::set_px (float px) inline override virtual
Reimplemented from TrackStateInfo.
Definition at line 67 of file TrackStateInfo_v1.h.
View newest version in sPHENIX GitHub at line 67 of file TrackStateInfo_v1.h
References m_Momentum.
Referenced by SvtxTrackInfo_v1::set_px().
void TrackStateInfo_v1::set_py (float py) inline override virtual
Reimplemented from TrackStateInfo.
Definition at line 70 of file TrackStateInfo_v1.h.
View newest version in sPHENIX GitHub at line 70 of file TrackStateInfo_v1.h
References m_Momentum.
Referenced by SvtxTrackInfo_v1::set_py().
void TrackStateInfo_v1::set_pz (float pz) inline override virtual
Reimplemented from TrackStateInfo.
Definition at line 73 of file TrackStateInfo_v1.h.
View newest version in sPHENIX GitHub at line 73 of file TrackStateInfo_v1.h
References m_Momentum.
Referenced by SvtxTrackInfo_v1::set_pz().
void TrackStateInfo_v1::set_x (float x) inline override virtual
Reimplemented from TrackStateInfo.
Definition at line 56 of file TrackStateInfo_v1.h.
View newest version in sPHENIX GitHub at line 56 of file TrackStateInfo_v1.h
References m_Position, and ambiguity_solver_full_chain::x.
Referenced by SvtxTrackInfo_v1::set_x().
void TrackStateInfo_v1::set_y (float y) inline override virtual
Reimplemented from TrackStateInfo.
Definition at line 59 of file TrackStateInfo_v1.h.
View newest version in sPHENIX GitHub at line 59 of file TrackStateInfo_v1.h
References m_Position, and y.
Referenced by SvtxTrackInfo_v1::set_y().
void TrackStateInfo_v1::set_z (float z) inline override virtual
Reimplemented from TrackStateInfo.
Definition at line 62 of file TrackStateInfo_v1.h.
View newest version in sPHENIX GitHub at line 62 of file TrackStateInfo_v1.h
References m_Position, and physmon_track_finding_ttbar::z.
Referenced by SvtxTrackInfo_v1::set_z().
Member Data Documentation
float TrackStateInfo_v1::m_Covariance[21] = {std::numeric_limits<float>::quiet_NaN()} private
Definition at line 91 of file TrackStateInfo_v1.h.
View newest version in sPHENIX GitHub at line 91 of file TrackStateInfo_v1.h
Referenced by get_covariance(), and set_covariance().
float TrackStateInfo_v1::m_Momentum[3] = {std::numeric_limits<float>::quiet_NaN()} private
Definition at line 89 of file TrackStateInfo_v1.h.
View newest version in sPHENIX GitHub at line 89 of file TrackStateInfo_v1.h
Referenced by get_mom(), get_px(), get_py(), get_pz(), set_px(), set_py(), and set_pz().
float TrackStateInfo_v1::m_Position[3] = {std::numeric_limits<float>::quiet_NaN()} private
Definition at line 90 of file TrackStateInfo_v1.h.
View newest version in sPHENIX GitHub at line 90 of file TrackStateInfo_v1.h
Referenced by get_pos(), get_x(), get_y(), get_z(), set_x(), set_y(), and set_z().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/trackbase_historic/TrackStateInfo_v1.h
coresoftware/blob/master/offline/packages/trackbase_historic/TrackStateInfo_v1.cc