Analysis Software: analysis/blob/master/JS-Jet/Calibrations/MC-Calibrations/Jet_reso_Iso.C File Reference
Jet_reso_Iso.C File Reference
#include "sPhenixStyle.h"
#include "sPhenixStyle.C"
Functions
bool isIso (int thisRjet, int thisTjet, vector< float > *rJetpT, vector< float > *tJetpT, vector< float > *rJetEta, vector< float > *tJetEta, vector< float > *rJetPhi, vector< float > *tJetPhi, float minDr, TH1F *&rDist, TH1F *&tDist)
void Jet_reso_Iso (float jetR=4, float isoParam=1, int applyCorr=0, int isLin=0)
Function Documentation
bool isIso (int thisRjet, int thisTjet, vector< float > * rJetpT, vector< float > * tJetpT, vector< float > * rJetEta, vector< float > * tJetEta, vector< float > * rJetPhi, vector< float > * tJetPhi, float minDr, TH1F *& rDist, TH1F *& tDist)
Definition at line 374 of file Jet_reso_Iso.C.
View newest version in sPHENIX GitHub at line 374 of file Jet_reso_Iso.C
References INTTVtxZ::dphi, Fill(), i, and physmon_track_finding_ttbar::minPt.
Referenced by Jet_reso_Iso().
void Jet_reso_Iso (float jetR = 4, float isoParam = 1, int applyCorr = 0, int isLin = 0)
Definition at line 11 of file Jet_reso_Iso.C.
View newest version in sPHENIX GitHub at line 11 of file Jet_reso_Iso.C
References Acts::Test::at, Acts::PhysicalConstants::c, cd(), Close(), dR(), Draw(), energy, eta, myAnalysis::eta_bins, GetXaxis(), i, isIso(), leg, ActsTests::PropagationDatasets::phi, myAnalysis::phi_bins, physmon_track_finding_ttbar::pt, SetLineColor(), SetLogy(), SetParameter(), SetRange(), SetsPhenixStyle(), sigma, and Write().