Analysis Software: FilterEvents Class Reference
FilterEvents Class Reference
#include <analysis/blob/master/FilterEvents/src/FilterEvents.h>
Public Member Functions
FilterEvents (const std::string &name="FilterEvents")
virtual ~FilterEvents ()
int Init (PHCompositeNode *topNode)
int InitRun (PHCompositeNode *topNode)
int process_event (PHCompositeNode *topNode)
int End (PHCompositeNode *topNode)
Called at the end of all processing.
void get_dca (SvtxTrack *track, SvtxVertexMap_v1 *vertexmap, double &DCA, double &DCAxy)
void get_dca_SvtxEval (SvtxTrack *track, SvtxVertexMap_v1 *vertexmap, double &dca3dxy, double &dca3dz, double &dca3dxysigma, double &dca3dzsigma)
void setCuts (double ptCut, double dcaCut, double chi2ndofCut, bool CEMCuse)
Public Member Functions inherited from SubsysReco
~SubsysReco () override
virtual int EndRun (const int)
Called at the end of each run.
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
void Print (const std::string &="ALL") const override
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Protected Member Functions
int GetNodes (PHCompositeNode *topNode)
TVector3 GetProjectionCEMC (SvtxTrack *track)
RawCluster * MatchClusterCEMC (SvtxTrack *track, RawClusterContainer *cemc_clusters, double &dphi, double &deta, double Zvtx)
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Protected Member Functions inherited from Fun4AllBase
Fun4AllBase (const std::string &name="NONAME")
Protected Attributes
PHCompositeNode * _topNode
SvtxTrackMap * _trackmap
SvtxVertexMap_v1 * _vtxmap
RawClusterContainer * _cemc_clusters
TrackSeedContainer * _trackseedcontainer_svtx
TrackSeedContainer * _trackseedcontainer_silicon
TrackSeedContainer * _trackseedcontainer_tpc
TrkrClusterContainerv4 * _trkrclusters
SvtxTrackMap * _trackmap_ee
RawClusterContainer * _cemc_clusters_ee
std::string outnodename_trackmap
std::string outnodename_cemc_clusters
int EventNumber
int goodEventNumber
double pt_cut
double dca_cut
double chi2ndof_cut
bool CEMC_use
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = std::numeric_limits<int>::max() - 10
}
Detailed Description
Definition at line 18 of file FilterEvents.h.
View newest version in sPHENIX GitHub at line 18 of file FilterEvents.h
Constructor & Destructor Documentation
FilterEvents::FilterEvents (const std::string & name = "FilterEvents")
Definition at line 48 of file FilterEvents.cc.
View newest version in sPHENIX GitHub at line 48 of file FilterEvents.cc
References CEMC_use, chi2ndof_cut, dca_cut, EventNumber, goodEventNumber, outnodename_cemc_clusters, outnodename_trackmap, and pt_cut.
virtual FilterEvents::~FilterEvents () inline virtual
Definition at line 23 of file FilterEvents.h.
View newest version in sPHENIX GitHub at line 23 of file FilterEvents.h
Member Function Documentation
int FilterEvents::End (PHCompositeNode *) virtual
Called at the end of all processing.
Reimplemented from SubsysReco.
Definition at line 462 of file FilterEvents.cc.
View newest version in sPHENIX GitHub at line 462 of file FilterEvents.cc
References Fun4AllReturnCodes::EVENT_OK, EventNumber, and goodEventNumber.
void FilterEvents::get_dca (SvtxTrack * track, SvtxVertexMap_v1 * vertexmap, double & DCA, double & DCAxy)
Definition at line 469 of file FilterEvents.cc.
View newest version in sPHENIX GitHub at line 469 of file FilterEvents.cc
References KFParticle::Chi2(), KFParticle::Create(), SvtxVertexMap_v1::get(), SvtxTrack::get_charge(), SvtxTrack::get_chisq(), SvtxTrack::get_error(), SvtxTrack::get_id(), SvtxTrack::get_ndf(), SvtxTrack::get_px(), SvtxTrack::get_py(), SvtxTrack::get_pz(), SvtxTrack::get_vertex_id(), SvtxVertex::get_x(), SvtxTrack::get_x(), SvtxTrack::get_y(), SvtxTrack::get_z(), KFParticleBase::GetDistanceFromVertex(), KFParticle::GetDistanceFromVertexXY(), i, j, KFParticle::NDF(), particle, and KFParticleBase::SetId().
Referenced by process_event().
void FilterEvents::get_dca_SvtxEval (SvtxTrack * track, SvtxVertexMap_v1 * vertexmap, double & dca3dxy, double & dca3dz, double & dca3dxysigma, double & dca3dzsigma)
Definition at line 530 of file FilterEvents.cc.
View newest version in sPHENIX GitHub at line 530 of file FilterEvents.cc
References SvtxVertexMap_v1::get(), SvtxTrack::get_error(), SvtxTrack::get_px(), SvtxTrack::get_py(), SvtxTrack::get_pz(), SvtxTrack::get_vertex_id(), SvtxTrack::get_x(), SvtxTrack::get_y(), SvtxTrack::get_z(), i, j, ActsTests::PropagationDatasets::phi, Acts::Test::pos, and physmon_track_finding_ttbar::r.
Referenced by process_event().
int FilterEvents::GetNodes (PHCompositeNode * topNode) protected
Definition at line 119 of file FilterEvents.cc.
View newest version in sPHENIX GitHub at line 119 of file FilterEvents.cc
References _cemc_clusters, _cemc_clusters_ee, _topNode, _trackmap, _trackmap_ee, _trackseedcontainer_silicon, _trackseedcontainer_svtx, _trackseedcontainer_tpc, _trkrclusters, _vtxmap, Fun4AllReturnCodes::ABORTEVENT, CEMC_use, Fun4AllReturnCodes::EVENT_OK, outnodename_cemc_clusters, outnodename_trackmap, and PHWHERE.
Referenced by process_event().
TVector3 FilterEvents::GetProjectionCEMC (SvtxTrack * track) protected
Definition at line 164 of file FilterEvents.cc.
View newest version in sPHENIX GitHub at line 164 of file FilterEvents.cc
References SvtxTrack::begin_states(), SvtxTrack::end_states(), SvtxTrackState::get_pathlength(), SvtxTrack::get_state(), SvtxTrackState::get_x(), SvtxTrackState::get_y(), SvtxTrackState::get_z(), and proj().
Referenced by process_event().
int FilterEvents::Init (PHCompositeNode *) virtual
Called during initialization. Typically this is where you can book histograms, and e.g. register them to Fun4AllServer (so they can be output to file using Fun4AllServer::dumpHistos() method).
Reimplemented from SubsysReco.
Definition at line 63 of file FilterEvents.cc.
View newest version in sPHENIX GitHub at line 63 of file FilterEvents.cc
References _cemc_clusters_ee, Fun4AllReturnCodes::ABORTEVENT, PHCompositeNode::addNode(), CEMC_use, Fun4AllReturnCodes::EVENT_OK, PHNodeIterator::findFirst(), outnodename_cemc_clusters, outnodename_trackmap, and PHWHERE.
int FilterEvents::InitRun (PHCompositeNode *) virtual
Called for first event when run number is known. Typically this is where you may want to fetch data from database, because you know the run number.
Reimplemented from SubsysReco.
Definition at line 112 of file FilterEvents.cc.
View newest version in sPHENIX GitHub at line 112 of file FilterEvents.cc
References Fun4AllReturnCodes::EVENT_OK.
RawCluster * FilterEvents::MatchClusterCEMC (SvtxTrack * track, RawClusterContainer * cemc_clusters, double & dphi, double & deta, double Zvtx) protected
Definition at line 191 of file FilterEvents.cc.
View newest version in sPHENIX GitHub at line 191 of file FilterEvents.cc
References SvtxTrack::begin_states(), dist(), SvtxTrack::end_states(), RawCluster::get_ecore(), SvtxTrackState::get_pathlength(), RawCluster::get_r(), SvtxTrack::get_state(), SvtxTrackState::get_x(), RawCluster::get_x(), SvtxTrackState::get_y(), RawCluster::get_y(), SvtxTrackState::get_z(), RawCluster::get_z(), RawClusterContainer::getClusters(), and proj().
Referenced by process_event().
int FilterEvents::process_event (PHCompositeNode *) virtual
Called for each event. This is where you do the real work.
Reimplemented from SubsysReco.
Definition at line 247 of file FilterEvents.cc.
View newest version in sPHENIX GitHub at line 247 of file FilterEvents.cc
References _cemc_clusters, _trackmap, _trackmap_ee, _trackseedcontainer_silicon, _trackseedcontainer_svtx, _trackseedcontainer_tpc, _trkrclusters, _vtxmap, Fun4AllReturnCodes::ABORTEVENT, RawClusterContainer::AddCluster(), TrkrClusterContainerv4::addClusterSpecifyKey(), GlobalVertexMap::begin(), SvtxTrackMap::begin(), TrackSeedContainer::begin(), TrackSeed::begin_cluster_keys(), cemc_deta, cemc_dphi, CEMC_use, chi2ndof_cut, PHObject::CloneMe(), SvtxTrackSeed_v1::CloneMe(), TrackSeed::CloneMe(), RawCluster::CloneMe(), INTTVtxZ::dca, dca_cut, dist(), GlobalVertexMap::end(), SvtxTrackMap::end(), TrackSeedContainer::end(), TrackSeed::end_cluster_keys(), Fun4AllReturnCodes::EVENT_OK, EventNumber, TrkrClusterContainerv4::findCluster(), TrackSeedContainer::get(), SvtxTrack::get_chisq(), get_dca(), get_dca_SvtxEval(), RawCluster::get_ecore(), GlobalVertex::get_id(), SvtxTrack::get_ndf(), TrackSeed::get_pt(), SvtxTrack::get_px(), SvtxTrack::get_py(), SvtxTrack::get_pz(), RawCluster::get_r(), SvtxTrack::get_silicon_seed(), SvtxTrackSeed_v1::get_silicon_seed_index(), SvtxTrack::get_tpc_seed(), SvtxTrackSeed_v1::get_tpc_seed_index(), RawCluster::get_x(), RawCluster::get_y(), GlobalVertex::get_z(), RawCluster::get_z(), RawClusterContainer::getClusters(), GetNodes(), GetProjectionCEMC(), goodEventNumber, i, SvtxTrackMap::insert(), TrackSeedContainer::insert(), it, MatchClusterCEMC(), PHWHERE, proj(), physmon_track_finding_ttbar::pt, pt_cut, TrkrClusterContainerv4::Reset(), RawClusterContainer::Reset(), PHObject::Reset(), seed, SvtxTrackMap::size(), TrackSeedContainer::size(), RawClusterContainer::size(), TrkrClusterContainerv4::size(), TrackSeed::size_cluster_keys(), and Acts::Test::tmp().
void FilterEvents::setCuts (double ptCut, double dcaCut, double chi2ndofCut, bool CEMCuse) inline
Definition at line 35 of file FilterEvents.h.
View newest version in sPHENIX GitHub at line 35 of file FilterEvents.h
References CEMC_use, chi2ndof_cut, dca_cut, and pt_cut.
Member Data Documentation
RawClusterContainer* FilterEvents::_cemc_clusters protected
Definition at line 52 of file FilterEvents.h.
View newest version in sPHENIX GitHub at line 52 of file FilterEvents.h
Referenced by GetNodes(), and process_event().
RawClusterContainer* FilterEvents::_cemc_clusters_ee protected
Definition at line 59 of file FilterEvents.h.
View newest version in sPHENIX GitHub at line 59 of file FilterEvents.h
Referenced by GetNodes(), and Init().
PHCompositeNode* FilterEvents::_topNode protected
Definition at line 48 of file FilterEvents.h.
View newest version in sPHENIX GitHub at line 48 of file FilterEvents.h
Referenced by GetNodes().
SvtxTrackMap* FilterEvents::_trackmap protected
Definition at line 49 of file FilterEvents.h.
View newest version in sPHENIX GitHub at line 49 of file FilterEvents.h
Referenced by GetNodes(), and process_event().
SvtxTrackMap* FilterEvents::_trackmap_ee protected
Definition at line 58 of file FilterEvents.h.
View newest version in sPHENIX GitHub at line 58 of file FilterEvents.h
Referenced by GetNodes(), and process_event().
TrackSeedContainer* FilterEvents::_trackseedcontainer_silicon protected
Definition at line 54 of file FilterEvents.h.
View newest version in sPHENIX GitHub at line 54 of file FilterEvents.h
Referenced by GetNodes(), and process_event().
TrackSeedContainer* FilterEvents::_trackseedcontainer_svtx protected
Definition at line 53 of file FilterEvents.h.
View newest version in sPHENIX GitHub at line 53 of file FilterEvents.h
Referenced by GetNodes(), and process_event().
TrackSeedContainer* FilterEvents::_trackseedcontainer_tpc protected
Definition at line 55 of file FilterEvents.h.
View newest version in sPHENIX GitHub at line 55 of file FilterEvents.h
Referenced by GetNodes(), and process_event().
TrkrClusterContainerv4* FilterEvents::_trkrclusters protected
Definition at line 56 of file FilterEvents.h.
View newest version in sPHENIX GitHub at line 56 of file FilterEvents.h
Referenced by GetNodes(), and process_event().
SvtxVertexMap_v1* FilterEvents::_vtxmap protected
Definition at line 50 of file FilterEvents.h.
View newest version in sPHENIX GitHub at line 50 of file FilterEvents.h
Referenced by GetNodes(), and process_event().
bool FilterEvents::CEMC_use protected
Definition at line 71 of file FilterEvents.h.
View newest version in sPHENIX GitHub at line 71 of file FilterEvents.h
Referenced by FilterEvents(), GetNodes(), Init(), process_event(), and setCuts().
double FilterEvents::chi2ndof_cut protected
Definition at line 69 of file FilterEvents.h.
View newest version in sPHENIX GitHub at line 69 of file FilterEvents.h
Referenced by FilterEvents(), process_event(), and setCuts().
double FilterEvents::dca_cut protected
Definition at line 68 of file FilterEvents.h.
View newest version in sPHENIX GitHub at line 68 of file FilterEvents.h
Referenced by FilterEvents(), process_event(), and setCuts().
int FilterEvents::EventNumber protected
Definition at line 64 of file FilterEvents.h.
View newest version in sPHENIX GitHub at line 64 of file FilterEvents.h
Referenced by End(), FilterEvents(), and process_event().
int FilterEvents::goodEventNumber protected
Definition at line 65 of file FilterEvents.h.
View newest version in sPHENIX GitHub at line 65 of file FilterEvents.h
Referenced by End(), FilterEvents(), and process_event().
std::string FilterEvents::outnodename_cemc_clusters protected
Definition at line 62 of file FilterEvents.h.
View newest version in sPHENIX GitHub at line 62 of file FilterEvents.h
Referenced by FilterEvents(), GetNodes(), and Init().
std::string FilterEvents::outnodename_trackmap protected
Definition at line 61 of file FilterEvents.h.
View newest version in sPHENIX GitHub at line 61 of file FilterEvents.h
Referenced by FilterEvents(), GetNodes(), and Init().
double FilterEvents::pt_cut protected
Definition at line 67 of file FilterEvents.h.
View newest version in sPHENIX GitHub at line 67 of file FilterEvents.h
Referenced by FilterEvents(), process_event(), and setCuts().
The documentation for this class was generated from the following files:
analysis/blob/master/FilterEvents/src/FilterEvents.h
analysis/blob/master/FilterEvents/src/FilterEvents.cc