Analysis Software: Jetscape::Hadronization Class Reference
Jetscape::Hadronization Class Reference
#include <JETSCAPE/blob/main/src/framework/Hadronization.h>
Public Member Functions
Hadronization ()
virtual ~Hadronization ()
virtual shared_ptr< Hadronization > Clone () const
virtual void Init ()
virtual void Exec ()
virtual void DoHadronization (vector< vector< shared_ptr< Parton >>> &pIn, vector< shared_ptr< Hadron >> &hOut, vector< shared_ptr< Parton >> &pOut)
virtual void WriteTask (weak_ptr< JetScapeWriter > w)
virtual void Clear ()
void GetHadrons (vector< shared_ptr< Hadron >> &signal)
vector< shared_ptr< Hadron > > GetHadrons ()
vector< shared_ptr< Parton > > GetOutPartons ()
void AddInPartons (vector< vector< shared_ptr< Parton >>> ip)
void SetTransformPartonsConnected (bool m_TransformPartonsConnected)
const bool GetTransformPartonsConnected ()
void SetGetHydroHyperSurfaceConnected (bool m_GetHydroHyperSurfaceConnected)
const bool GetGetHydroHyperSurfaceConnected ()
void SetGetHydroCellSignalConnected (bool m_GetHydroCellSignalConnected)
const bool GetGetHydroCellSignalConnected ()
void AddInHadrons (vector< shared_ptr< Hadron >> ih)
void DeleteHadrons ()
void DeleteRealHadrons ()
Public Member Functions inherited from Jetscape::JetScapeModuleBase
JetScapeModuleBase ()
JetScapeModuleBase (string m_name)
virtual ~JetScapeModuleBase ()
void SetXMLMainFileName (string m_name)
string GetXMLMainFileName ()
void SetXMLUserFileName (string m_name)
string GetXMLUserFileName ()
shared_ptr< std::mt19937 > GetMt19937Generator ()
tinyxml2::XMLElement * GetXMLElement (std::initializer_list< const char * > path, bool isRequired=true)
std::string GetXMLElementText (std::initializer_list< const char * > path, bool isRequired=true)
int GetXMLElementInt (std::initializer_list< const char * > path, bool isRequired=true)
double GetXMLElementDouble (std::initializer_list< const char * > path, bool isRequired=true)
Public Member Functions inherited from Jetscape::JetScapeTask
JetScapeTask ()
virtual ~JetScapeTask ()
virtual void Finish ()
virtual void ExecuteTasks ()
virtual void ExecuteTask ()
virtual void InitTask ()
virtual void InitTasks ()
virtual void ClearTasks ()
virtual void ClearTask ()
virtual void FinishTask ()
virtual void FinishTasks ()
virtual void WriteTasks (weak_ptr< JetScapeWriter > w)
virtual void CollectHeader (weak_ptr< JetScapeWriter > w)
virtual void CollectHeaders (weak_ptr< JetScapeWriter > w)
virtual void Add (shared_ptr< JetScapeTask > m_tasks)
virtual const int GetMyTaskNumber () const
const vector< shared_ptr
< JetScapeTask > > GetTaskList () const
shared_ptr< JetScapeTask > GetTaskAt (int i)
void EraseTaskLast ()
void EraseTaskAt (int i)
void ResizeTaskList (int i)
void ClearTaskList ()
int GetNumberOfTasks ()
const bool GetActive () const
void SetActive (bool m_active_exec)
void SetId (string m_id)
const string GetId () const
const shared_ptr
< JetScapeModuleMutex > GetMutex () const
void SetMutex (shared_ptr< JetScapeModuleMutex > m_mutex)
Public Member Functions inherited from sigslot::has_slots< sigslot::multi_threaded_local >
has_slots ()
has_slots (const has_slots &hs)
void signal_connect (_signal_base< sigslot::multi_threaded_local > *sender)
void signal_disconnect (_signal_base< sigslot::multi_threaded_local > *sender)
virtual ~has_slots ()
void disconnect_all ()
Public Attributes
sigslot::signal3< vector
< vector< shared_ptr< Parton >
> > &, vector< shared_ptr
< Hadron > > &, vector
< shared_ptr< Parton >
> &, multi_threaded_local > TransformPartons
sigslot::signal2
< Jetscape::real, std::vector
< SurfaceCellInfo >
&, multi_threaded_local > GetHydroHyperSurface
sigslot::signal5< double,
double, double, double,
std::unique_ptr< FluidCellInfo >
&, multi_threaded_local > GetHydroCellSignal
Private Member Functions
void DoHadronize ()
Private Attributes
vector< vector< shared_ptr
< Parton > > > inPartons
vector< shared_ptr< Hadron > > outHadrons
vector< shared_ptr< Parton > > outPartons
bool TransformPartonsConnected
bool HydroHyperSurfaceConnected_
bool GetHydroCellSignalConnected_
Additional Inherited Members
Static Public Member Functions inherited from Jetscape::JetScapeModuleBase
static int GetCurrentEvent ()
static void IncrementCurrentEvent ()
Detailed Description
Definition at line 30 of file Hadronization.h.
View newest version in sPHENIX GitHub at line 30 of file Hadronization.h
Constructor & Destructor Documentation
Jetscape::Hadronization::Hadronization ()
Definition at line 28 of file Hadronization.cc.
View newest version in sPHENIX GitHub at line 28 of file Hadronization.cc
References SetId().
Jetscape::Hadronization::~Hadronization () virtual
Definition at line 35 of file Hadronization.cc.
View newest version in sPHENIX GitHub at line 35 of file Hadronization.cc
Member Function Documentation
void Jetscape::Hadronization::AddInHadrons (vector< shared_ptr< Hadron >> ih) inline
Definition at line 84 of file Hadronization.h.
View newest version in sPHENIX GitHub at line 84 of file Hadronization.h
References outHadrons.
void Jetscape::Hadronization::AddInPartons (vector< vector< shared_ptr< Parton >>> ip) inline
Definition at line 61 of file Hadronization.h.
View newest version in sPHENIX GitHub at line 61 of file Hadronization.h
References inPartons.
void Jetscape::Hadronization::Clear (void) virtual
A virtual function to define a default Clear() function for a JetScapeModuleBase. It can be overridden by different modules/tasks.
Reimplemented from Jetscape::JetScapeModuleBase.
Definition at line 37 of file Hadronization.cc.
View newest version in sPHENIX GitHub at line 37 of file Hadronization.cc
References VERBOSESHOWER.
virtual shared_ptr<Hadronization> Jetscape::Hadronization::Clone () const inline virtual
Reimplemented in Jetscape::HadronizationModule< Derived >, Jetscape::HadronizationModule< ColoredHadronization >, Jetscape::HadronizationModule< ColorlessHadronization >, and Jetscape::HadronizationModule< HybridHadronization >.
Definition at line 35 of file Hadronization.h.
View newest version in sPHENIX GitHub at line 35 of file Hadronization.h
void Jetscape::Hadronization::DeleteHadrons ()
Definition at line 100 of file Hadronization.cc.
View newest version in sPHENIX GitHub at line 100 of file Hadronization.cc
Referenced by Jetscape::HadronizationManager::DeleteHadrons().
void Jetscape::Hadronization::DeleteRealHadrons ()
Definition at line 104 of file Hadronization.cc.
View newest version in sPHENIX GitHub at line 104 of file Hadronization.cc
Referenced by Jetscape::HadronizationManager::DeleteRealHadrons().
virtual void Jetscape::Hadronization::DoHadronization (vector< vector< shared_ptr< Parton >>> & pIn, vector< shared_ptr< Hadron >> & hOut, vector< shared_ptr< Parton >> & pOut) inline virtual
Reimplemented in HybridHadronization, ColorlessHadronization, and ColoredHadronization.
Definition at line 38 of file Hadronization.h.
View newest version in sPHENIX GitHub at line 38 of file Hadronization.h
void Jetscape::Hadronization::DoHadronize () private
Definition at line 57 of file Hadronization.cc.
View newest version in sPHENIX GitHub at line 57 of file Hadronization.cc
References VERBOSE.
void Jetscape::Hadronization::Exec () virtual
A virtual function to define a default Exec() function for a JetScapeModuleBase. It can be overridden by different modules/tasks.
Reimplemented from Jetscape::JetScapeModuleBase.
Definition at line 68 of file Hadronization.cc.
View newest version in sPHENIX GitHub at line 68 of file Hadronization.cc
References VERBOSE.
const bool Jetscape::Hadronization::GetGetHydroCellSignalConnected () inline
Definition at line 80 of file Hadronization.h.
View newest version in sPHENIX GitHub at line 80 of file Hadronization.h
References GetHydroCellSignalConnected_.
const bool Jetscape::Hadronization::GetGetHydroHyperSurfaceConnected () inline
Definition at line 73 of file Hadronization.h.
View newest version in sPHENIX GitHub at line 73 of file Hadronization.h
References HydroHyperSurfaceConnected_.
void Jetscape::Hadronization::GetHadrons (vector< shared_ptr< Hadron >> & signal) inline
Definition at line 44 of file Hadronization.h.
View newest version in sPHENIX GitHub at line 44 of file Hadronization.h
References outHadrons, and signal().
Referenced by Jetscape::HadronizationManager::GetHadrons().
vector<shared_ptr<Hadron> > Jetscape::Hadronization::GetHadrons () inline
Definition at line 58 of file Hadronization.h.
View newest version in sPHENIX GitHub at line 58 of file Hadronization.h
References outHadrons.
vector<shared_ptr<Parton> > Jetscape::Hadronization::GetOutPartons () inline
Definition at line 59 of file Hadronization.h.
View newest version in sPHENIX GitHub at line 59 of file Hadronization.h
References outPartons.
const bool Jetscape::Hadronization::GetTransformPartonsConnected () inline
Definition at line 66 of file Hadronization.h.
View newest version in sPHENIX GitHub at line 66 of file Hadronization.h
References TransformPartonsConnected.
void Jetscape::Hadronization::Init () virtual
A virtual function for a default initialization of a JetScapeModuleBase. It also checks whether a XML file is loaded or not.
Reimplemented from Jetscape::JetScapeModuleBase.
Reimplemented in HybridHadronization, ColorlessHadronization, and ColoredHadronization.
Definition at line 42 of file Hadronization.cc.
View newest version in sPHENIX GitHub at line 42 of file Hadronization.cc
References Init(), JSINFO, and JSWARN.
void Jetscape::Hadronization::SetGetHydroCellSignalConnected (bool m_GetHydroCellSignalConnected) inline
Definition at line 77 of file Hadronization.h.
View newest version in sPHENIX GitHub at line 77 of file Hadronization.h
References GetHydroCellSignalConnected_.
void Jetscape::Hadronization::SetGetHydroHyperSurfaceConnected (bool m_GetHydroHyperSurfaceConnected) inline
Definition at line 70 of file Hadronization.h.
View newest version in sPHENIX GitHub at line 70 of file Hadronization.h
References HydroHyperSurfaceConnected_.
void Jetscape::Hadronization::SetTransformPartonsConnected (bool m_TransformPartonsConnected) inline
Definition at line 63 of file Hadronization.h.
View newest version in sPHENIX GitHub at line 63 of file Hadronization.h
References TransformPartonsConnected.
void Jetscape::Hadronization::WriteTask (weak_ptr< JetScapeWriter > w) virtual
A virtual function to define a default WriteTask() function for a JetScapeTask. It can be overridden by different modules/tasks. Current setup: Every task gets handed a pointer to the writer and can add any information it likes to it (using predefined functions like WriteComment()) This is maximally flexible but makes it difficult to properly store information for a variety of outputs. E.g., sigmaGen: A HardProcess can easily write the xsec to any stream-type output using WriteComment. But to set it in a HepMC file, either HardProcess needs to make a case-by-case selection, meaning a new file format would need to percolate through multiple base classes, or the writer needs to know this information and implement WriteEvent appropriately. The latter is obviously better, but it's non-trivial to collect this information.
Reimplemented from Jetscape::JetScapeTask.
Reimplemented in HybridHadronization, ColorlessHadronization, and ColoredHadronization.
Definition at line 79 of file Hadronization.cc.
View newest version in sPHENIX GitHub at line 79 of file Hadronization.cc
References f, h, i, size, to_string(), and VERBOSE.
Member Data Documentation
sigslot::signal5<double, double, double, double, std::unique_ptr<FluidCellInfo> &, multi_threaded_local> Jetscape::Hadronization::GetHydroCellSignal
Definition at line 55 of file Hadronization.h.
View newest version in sPHENIX GitHub at line 55 of file Hadronization.h
bool Jetscape::Hadronization::GetHydroCellSignalConnected_ private
Definition at line 101 of file Hadronization.h.
View newest version in sPHENIX GitHub at line 101 of file Hadronization.h
Referenced by GetGetHydroCellSignalConnected(), and SetGetHydroCellSignalConnected().
sigslot::signal2<Jetscape::real, std::vector<SurfaceCellInfo> &, multi_threaded_local> Jetscape::Hadronization::GetHydroHyperSurface
Definition at line 51 of file Hadronization.h.
View newest version in sPHENIX GitHub at line 51 of file Hadronization.h
bool Jetscape::Hadronization::HydroHyperSurfaceConnected_ private
Definition at line 100 of file Hadronization.h.
View newest version in sPHENIX GitHub at line 100 of file Hadronization.h
Referenced by GetGetHydroHyperSurfaceConnected(), and SetGetHydroHyperSurfaceConnected().
vector<vector<shared_ptr<Parton> > > Jetscape::Hadronization::inPartons private
Definition at line 94 of file Hadronization.h.
View newest version in sPHENIX GitHub at line 94 of file Hadronization.h
Referenced by AddInPartons().
vector<shared_ptr<Hadron> > Jetscape::Hadronization::outHadrons private
Definition at line 95 of file Hadronization.h.
View newest version in sPHENIX GitHub at line 95 of file Hadronization.h
Referenced by AddInHadrons(), and GetHadrons().
vector<shared_ptr<Parton> > Jetscape::Hadronization::outPartons private
Definition at line 96 of file Hadronization.h.
View newest version in sPHENIX GitHub at line 96 of file Hadronization.h
Referenced by GetOutPartons().
sigslot::signal3<vector<vector<shared_ptr<Parton> > > &, vector<shared_ptr<Hadron> > &, vector<shared_ptr<Parton> > &, multi_threaded_local> Jetscape::Hadronization::TransformPartons
Definition at line 48 of file Hadronization.h.
View newest version in sPHENIX GitHub at line 48 of file Hadronization.h
bool Jetscape::Hadronization::TransformPartonsConnected private
Definition at line 99 of file Hadronization.h.
View newest version in sPHENIX GitHub at line 99 of file Hadronization.h
Referenced by GetTransformPartonsConnected(), and SetTransformPartonsConnected().
The documentation for this class was generated from the following files:
JETSCAPE/blob/main/src/framework/Hadronization.h
JETSCAPE/blob/main/src/framework/Hadronization.cc