Analysis Software: ActsExamples::PlotHelpers::Binning Class Reference
ActsExamples::PlotHelpers::Binning Class Reference
Nested binning struct for booking plots.
#include <acts/blob/sPHENIX/Examples/Framework/include/ActsExamples/Utilities/Helpers.hpp>
Public Member Functions
Binning ()
m_bins (std::move(bins))
const auto & title () const
auto nBins () const
const double * data () const
auto low () const
auto high () const
Private Attributes
std::string m_title
std::vector< double > m_bins
Detailed Description
Nested binning struct for booking plots.
Definition at line 32 of file Helpers.hpp.
View newest version in sPHENIX GitHub at line 32 of file Helpers.hpp
Constructor & Destructor Documentation
ActsExamples::PlotHelpers::Binning::Binning () inline
Definition at line 34 of file Helpers.hpp.
View newest version in sPHENIX GitHub at line 34 of file Helpers.hpp
Member Function Documentation
const double* ActsExamples::PlotHelpers::Binning::data () const inline
Definition at line 52 of file Helpers.hpp.
View newest version in sPHENIX GitHub at line 52 of file Helpers.hpp
References m_bins.
Referenced by ActsExamples::PlotHelpers::bookEff(), ActsExamples::PlotHelpers::bookHisto(), and ActsExamples::PlotHelpers::bookProf().
auto ActsExamples::PlotHelpers::Binning::high () const inline
Definition at line 54 of file Helpers.hpp.
View newest version in sPHENIX GitHub at line 54 of file Helpers.hpp
References m_bins.
Referenced by ActsExamples::PlotHelpers::bookProf().
auto ActsExamples::PlotHelpers::Binning::low () const inline
Definition at line 53 of file Helpers.hpp.
View newest version in sPHENIX GitHub at line 53 of file Helpers.hpp
References m_bins.
Referenced by ActsExamples::PlotHelpers::bookProf(), dofistatescat(), doinstatescat(), getinspliti(), getpnorad1(), getspliti(), getsscat(), pycba2(), pycbal(), pycmq2(), pycmqr(), and pycrth().
ActsExamples::PlotHelpers::Binning::m_bins (std:: movebins) inline
Definition at line 48 of file Helpers.hpp.
View newest version in sPHENIX GitHub at line 48 of file Helpers.hpp
auto ActsExamples::PlotHelpers::Binning::nBins () const inline
Definition at line 51 of file Helpers.hpp.
View newest version in sPHENIX GitHub at line 51 of file Helpers.hpp
References m_bins.
Referenced by ActsExamples::PlotHelpers::bookEff(), ActsExamples::PlotHelpers::bookHisto(), ActsExamples::PlotHelpers::bookProf(), and ActsExamples::ResPlotTool::refinement().
const auto& ActsExamples::PlotHelpers::Binning::title () const inline
Definition at line 50 of file Helpers.hpp.
View newest version in sPHENIX GitHub at line 50 of file Helpers.hpp
References m_title.
Referenced by ActsExamples::PlotHelpers::bookHisto(), and ActsExamples::PlotHelpers::bookProf().
Member Data Documentation
std::vector<double> ActsExamples::PlotHelpers::Binning::m_bins private
Definition at line 58 of file Helpers.hpp.
View newest version in sPHENIX GitHub at line 58 of file Helpers.hpp
Referenced by data(), high(), low(), and nBins().
std::string ActsExamples::PlotHelpers::Binning::m_title private
Definition at line 57 of file Helpers.hpp.
View newest version in sPHENIX GitHub at line 57 of file Helpers.hpp
Referenced by title().
The documentation for this class was generated from the following file:
acts/blob/sPHENIX/Examples/Framework/include/ActsExamples/Utilities/Helpers.hpp