Analysis Software: tpc_pool Class Reference
tpc_pool Class Reference
#include <coresoftware/blob/master/offline/framework/fun4allraw/tpc_pool.h>
Classes
struct bco_compare
struct gtm_payload
struct sampa_waveform
Public Member Functions
tpc_pool (const unsigned int required_depth, const unsigned int low_mark=1000000)
virtual ~tpc_pool ()
virtual int addPacket (Packet *)
int next ()
int iValue (const int ch, const int sample)
SAMPA waveform interfaces.
int iValue (const int, const char *what)
long long lValue (const int channel, const char *what)
Expose the Level 1 trigger and endat taggers.
void dump (std::ostream &os=std::cout)
virtual bool depth_ok () const
virtual void drain ()
virtual unsigned int min_depth () const
Protected Types
typedef std::multiset
< sampa_waveform
*, bco_compare > waveform_set
Protected Member Functions
int tpc_decode ()
unsigned short reverseBits (const unsigned short x) const
unsigned short crc16 (const unsigned int fee, const unsigned int index, const int l) const
int find_header (const unsigned int xx, const std::vector< unsigned short > &orig)
int decode_gtm_data (unsigned short gtm[16])
int cacheIterator (const int n)
Protected Attributes
int _is_decoded
unsigned int _required_depth
unsigned int _low_mark
unsigned int _progress_index
std::vector< unsigned short > _thebuffer
waveform_set waveforms
waveform_set::iterator _cached_iter
int _last_requested_element
std::vector< unsigned short > fee_data [MAX_FEECOUNT]
std::vector< gtm_payload * > gtm_data
Static Protected Attributes
static const unsigned short MAGIC_KEY_0 = 0xfe
static const unsigned short MAGIC_KEY_1 = 0x00
static const unsigned short FEE_MAGIC_KEY = 0xba00
static const unsigned short GTM_MAGIC_KEY = 0xbb00
static const unsigned short GTM_LVL1_ACCEPT_MAGIC_KEY = 0xbbf0
static const unsigned short GTM_ENDAT_MAGIC_KEY = 0xbbf1
static const unsigned short MAX_FEECOUNT = 26
static const unsigned short MAX_CHANNELS = 8*32
static const unsigned short HEADER_LENGTH = 7
Detailed Description
Definition at line 12 of file tpc_pool.h.
View newest version in sPHENIX GitHub at line 12 of file tpc_pool.h
Member Typedef Documentation
typedef std::multiset< sampa_waveform* , bco_compare> tpc_pool::waveform_set protected
Definition at line 111 of file tpc_pool.h.
View newest version in sPHENIX GitHub at line 111 of file tpc_pool.h
Constructor & Destructor Documentation
tpc_pool::tpc_pool (const unsigned int required_depth, const unsigned int low_mark = 1000000)
Definition at line 14 of file tpc_pool.cc.
View newest version in sPHENIX GitHub at line 14 of file tpc_pool.cc
References depth.
tpc_pool::~tpc_pool () virtual
Definition at line 45 of file tpc_pool.cc.
View newest version in sPHENIX GitHub at line 45 of file tpc_pool.cc
Member Function Documentation
int tpc_pool::addPacket (Packet * p) virtual
Definition at line 100 of file tpc_pool.cc.
View newest version in sPHENIX GitHub at line 100 of file tpc_pool.cc
References KFPMath::b, Packet::fillIntArray(), Packet::getDataLength(), i, Packet::identify(), testSigmaEff::l2, and ambiguity_solver_full_chain::x.
int tpc_pool::cacheIterator (const int n) protected
Definition at line 129 of file tpc_pool.cc.
View newest version in sPHENIX GitHub at line 129 of file tpc_pool.cc
References i, it, n, and next.
unsigned short tpc_pool::crc16 (const unsigned int fee, const unsigned int index, const int l) const protected
Definition at line 675 of file tpc_pool.cc.
View newest version in sPHENIX GitHub at line 675 of file tpc_pool.cc
References i, k, and ambiguity_solver_full_chain::x.
int tpc_pool::decode_gtm_data (unsigned short gtm[16]) protected
Definition at line 148 of file tpc_pool.cc.
View newest version in sPHENIX GitHub at line 148 of file tpc_pool.cc
References tpc_pool::gtm_payload::bco, tpc_pool::gtm_payload::endat_count, tpc_pool::gtm_payload::is_endat, tpc_pool::gtm_payload::is_lvl1, tpc_pool::gtm_payload::last_bco, tpc_pool::gtm_payload::lvl1_count, tpc_pool::gtm_payload::modebits, and tpc_pool::gtm_payload::pkt_type.
bool tpc_pool::depth_ok () const virtual
Definition at line 93 of file tpc_pool.cc.
View newest version in sPHENIX GitHub at line 93 of file tpc_pool.cc
virtual void tpc_pool::drain () inline virtual
Definition at line 33 of file tpc_pool.h.
View newest version in sPHENIX GitHub at line 33 of file tpc_pool.h
References _low_mark.
void tpc_pool::dump (std::ostream & os = std::cout)
Definition at line 607 of file tpc_pool.cc.
View newest version in sPHENIX GitHub at line 607 of file tpc_pool.cc
References i, j, and k.
int tpc_pool::find_header (const unsigned int xx, const std::vector< unsigned short > & orig) protected
Definition at line 557 of file tpc_pool.cc.
View newest version in sPHENIX GitHub at line 557 of file tpc_pool.cc
References HEADER_LENGTH, i, and Acts::Test::pos.
int tpc_pool::iValue (const int ch, const int sample)
SAMPA waveform interfaces.
Definition at line 444 of file tpc_pool.cc.
View newest version in sPHENIX GitHub at line 444 of file tpc_pool.cc
References Acts::UnitConstants::m.
int tpc_pool::iValue (const int n, const char * what)
Definition at line 463 of file tpc_pool.cc.
View newest version in sPHENIX GitHub at line 463 of file tpc_pool.cc
long long tpc_pool::lValue (const int channel, const char * what)
Expose the Level 1 trigger and endat taggers.
Definition at line 366 of file tpc_pool.cc.
View newest version in sPHENIX GitHub at line 366 of file tpc_pool.cc
References i, and n.
virtual unsigned int tpc_pool::min_depth () const inline virtual
Definition at line 34 of file tpc_pool.h.
View newest version in sPHENIX GitHub at line 34 of file tpc_pool.h
References _thebuffer.
int tpc_pool::next ()
Definition at line 63 of file tpc_pool.cc.
View newest version in sPHENIX GitHub at line 63 of file tpc_pool.cc
unsigned short tpc_pool::reverseBits (const unsigned short x) const protected
Definition at line 662 of file tpc_pool.cc.
View newest version in sPHENIX GitHub at line 662 of file tpc_pool.cc
References n, and ambiguity_solver_full_chain::x.
int tpc_pool::tpc_decode () protected
Definition at line 190 of file tpc_pool.cc.
View newest version in sPHENIX GitHub at line 190 of file tpc_pool.cc
References tpc_pool::sampa_waveform::adc_length, tpc_pool::sampa_waveform::bx_timestamp, tpc_pool::sampa_waveform::channel, tpc_pool::sampa_waveform::checksum, tpc_pool::sampa_waveform::fee, HEADER_LENGTH, i, index, tpc_pool::sampa_waveform::pkt_length, Acts::Test::pos, tpc_pool::sampa_waveform::sampa_address, tpc_pool::sampa_waveform::sampa_channel, size, tpc_pool::sampa_waveform::valid, and tpc_pool::sampa_waveform::waveform.
Member Data Documentation
waveform_set::iterator tpc_pool::_cached_iter protected
Definition at line 119 of file tpc_pool.h.
View newest version in sPHENIX GitHub at line 119 of file tpc_pool.h
int tpc_pool::_is_decoded protected
Definition at line 61 of file tpc_pool.h.
View newest version in sPHENIX GitHub at line 61 of file tpc_pool.h
int tpc_pool::_last_requested_element protected
Definition at line 120 of file tpc_pool.h.
View newest version in sPHENIX GitHub at line 120 of file tpc_pool.h
unsigned int tpc_pool::_low_mark protected
Definition at line 64 of file tpc_pool.h.
View newest version in sPHENIX GitHub at line 64 of file tpc_pool.h
Referenced by drain().
unsigned int tpc_pool::_progress_index protected
Definition at line 66 of file tpc_pool.h.
View newest version in sPHENIX GitHub at line 66 of file tpc_pool.h
unsigned int tpc_pool::_required_depth protected
Definition at line 63 of file tpc_pool.h.
View newest version in sPHENIX GitHub at line 63 of file tpc_pool.h
std::vector<unsigned short> tpc_pool::_thebuffer protected
Definition at line 71 of file tpc_pool.h.
View newest version in sPHENIX GitHub at line 71 of file tpc_pool.h
Referenced by min_depth().
std::vector<unsigned short> tpc_pool::fee_data[MAX_FEECOUNT] protected
Definition at line 122 of file tpc_pool.h.
View newest version in sPHENIX GitHub at line 122 of file tpc_pool.h
const unsigned short tpc_pool::FEE_MAGIC_KEY = 0xba00 static protected
Definition at line 43 of file tpc_pool.h.
View newest version in sPHENIX GitHub at line 43 of file tpc_pool.h
std::vector<gtm_payload *> tpc_pool::gtm_data protected
Definition at line 124 of file tpc_pool.h.
View newest version in sPHENIX GitHub at line 124 of file tpc_pool.h
const unsigned short tpc_pool::GTM_ENDAT_MAGIC_KEY = 0xbbf1 static protected
Definition at line 46 of file tpc_pool.h.
View newest version in sPHENIX GitHub at line 46 of file tpc_pool.h
const unsigned short tpc_pool::GTM_LVL1_ACCEPT_MAGIC_KEY = 0xbbf0 static protected
Definition at line 45 of file tpc_pool.h.
View newest version in sPHENIX GitHub at line 45 of file tpc_pool.h
const unsigned short tpc_pool::GTM_MAGIC_KEY = 0xbb00 static protected
Definition at line 44 of file tpc_pool.h.
View newest version in sPHENIX GitHub at line 44 of file tpc_pool.h
const unsigned short tpc_pool::HEADER_LENGTH = 7 static protected
Definition at line 50 of file tpc_pool.h.
View newest version in sPHENIX GitHub at line 50 of file tpc_pool.h
const unsigned short tpc_pool::MAGIC_KEY_0 = 0xfe static protected
Definition at line 40 of file tpc_pool.h.
View newest version in sPHENIX GitHub at line 40 of file tpc_pool.h
const unsigned short tpc_pool::MAGIC_KEY_1 = 0x00 static protected
Definition at line 41 of file tpc_pool.h.
View newest version in sPHENIX GitHub at line 41 of file tpc_pool.h
const unsigned short tpc_pool::MAX_CHANNELS = 8*32 static protected
Definition at line 49 of file tpc_pool.h.
View newest version in sPHENIX GitHub at line 49 of file tpc_pool.h
const unsigned short tpc_pool::MAX_FEECOUNT = 26 static protected
Definition at line 48 of file tpc_pool.h.
View newest version in sPHENIX GitHub at line 48 of file tpc_pool.h
waveform_set tpc_pool::waveforms protected
Definition at line 114 of file tpc_pool.h.
View newest version in sPHENIX GitHub at line 114 of file tpc_pool.h
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/framework/fun4allraw/tpc_pool.h
coresoftware/blob/master/offline/framework/fun4allraw/tpc_pool.cc