Analysis Software: ActsExamples::Telescope::TelescopeDetector Struct Reference
ActsExamples::Telescope::TelescopeDetector Struct Reference
#include <acts/blob/sPHENIX/Examples/Detectors/TelescopeDetector/include/ActsExamples/TelescopeDetector/TelescopeDetector.hpp>
Classes
struct Config
Public Types
using DetectorElement = ActsExamples::Telescope::TelescopeDetectorElement
using DetectorElementPtr = std::shared_ptr< DetectorElement >
using DetectorStore = std::vector< DetectorElementPtr >
using ContextDecorators = std::vector< std::shared_ptr< ActsExamples::IContextDecorator >>
using TrackingGeometryPtr = std::shared_ptr< const Acts::TrackingGeometry >
Public Member Functions
std::pair< TrackingGeometryPtr,
ContextDecorators > finalize (const Config &cfg, const std::shared_ptr< const Acts::IMaterialDecorator > &mdecorator)
Public Attributes
Config config
DetectorStore detectorStore
The store of the detector elements (lifetime: job)
Detailed Description
Definition at line 37 of file TelescopeDetector.hpp.
View newest version in sPHENIX GitHub at line 37 of file TelescopeDetector.hpp
Member Typedef Documentation
using ActsExamples::Telescope::TelescopeDetector::ContextDecorators = std::vector<std::shared_ptr<ActsExamples::IContextDecorator>>
Definition at line 43 of file TelescopeDetector.hpp.
View newest version in sPHENIX GitHub at line 43 of file TelescopeDetector.hpp
using ActsExamples::Telescope::TelescopeDetector::DetectorElement = ActsExamples::Telescope::TelescopeDetectorElement
Definition at line 38 of file TelescopeDetector.hpp.
View newest version in sPHENIX GitHub at line 38 of file TelescopeDetector.hpp
using ActsExamples::Telescope::TelescopeDetector::DetectorElementPtr = std::shared_ptr<DetectorElement>
Definition at line 39 of file TelescopeDetector.hpp.
View newest version in sPHENIX GitHub at line 39 of file TelescopeDetector.hpp
using ActsExamples::Telescope::TelescopeDetector::DetectorStore = std::vector<DetectorElementPtr>
Definition at line 40 of file TelescopeDetector.hpp.
View newest version in sPHENIX GitHub at line 40 of file TelescopeDetector.hpp
using ActsExamples::Telescope::TelescopeDetector::TrackingGeometryPtr = std::shared_ptr<const Acts::TrackingGeometry>
Definition at line 44 of file TelescopeDetector.hpp.
View newest version in sPHENIX GitHub at line 44 of file TelescopeDetector.hpp
Member Function Documentation
auto ActsExamples::Telescope::TelescopeDetector::finalize (const Config & cfg, const std::shared_ptr< const Acts::IMaterialDecorator > & mdecorator)
Return the telescope detector
Definition at line 19 of file TelescopeDetector.cpp.
View newest version in sPHENIX GitHub at line 19 of file TelescopeDetector.cpp
References ActsExamples::Telescope::buildDetector(), cfg, filter::config, testing::internal::move(), telescope_simulation::positions, Acts::Experimental::detail::BlueprintHelper::sort(), and truth_tracking_telescope::stereos.
Referenced by ActsExamples::TelescopeDetectorWithOptions::finalize().
Member Data Documentation
Config ActsExamples::Telescope::TelescopeDetector::config
Definition at line 56 of file TelescopeDetector.hpp.
View newest version in sPHENIX GitHub at line 56 of file TelescopeDetector.hpp
DetectorStore ActsExamples::Telescope::TelescopeDetector::detectorStore
The store of the detector elements (lifetime: job)
Definition at line 58 of file TelescopeDetector.hpp.
View newest version in sPHENIX GitHub at line 58 of file TelescopeDetector.hpp
The documentation for this struct was generated from the following files:
acts/blob/sPHENIX/Examples/Detectors/TelescopeDetector/include/ActsExamples/TelescopeDetector/TelescopeDetector.hpp
acts/blob/sPHENIX/Examples/Detectors/TelescopeDetector/src/TelescopeDetector.cpp