Analysis Software: CDBTTree Class Reference
CDBTTree Class Reference
#include <coresoftware/blob/master/offline/database/cdbobjects/CDBTTree.h>
Public Member Functions
CDBTTree ()=default
CDBTTree (const std::string &fname)
~CDBTTree ()
void SetFloatValue (int channel, const std::string &name, float value)
void SetDoubleValue (int channel, const std::string &name, double value)
void SetIntValue (int channel, const std::string &name, int value)
void SetUInt64Value (int channel, const std::string &name, uint64_t value)
void Commit ()
void SetSingleFloatValue (const std::string &name, float value)
void SetSingleDoubleValue (const std::string &name, double value)
void SetSingleIntValue (const std::string &name, int value)
void SetSingleUInt64Value (const std::string &name, uint64_t value)
void CommitSingle ()
void WriteCDBTTree ()
void WriteSingleCDBTTree ()
void WriteMultipleCDBTTree ()
void Print ()
void LoadCalibrations ()
float GetSingleFloatValue (const std::string &name, int verbose=1)
float GetFloatValue (int channel, const std::string &name, int verbose=1)
double GetSingleDoubleValue (const std::string &name, int verbose=1)
double GetDoubleValue (int channel, const std::string &name, int verbose=1)
int GetSingleIntValue (const std::string &name, int verbose=1)
int GetIntValue (int channel, const std::string &name, int verbose=1)
uint64_t GetSingleUInt64Value (const std::string &name, int verbose=1)
uint64_t GetUInt64Value (int channel, const std::string &name, int verbose=1)
Private Types
enum { SingleEntries = 0, MultipleEntries = 1 }
Private Attributes
const std::string m_TTreeName [2] = {"Single", "Multiple"}
TTree * m_TTree [2] = {nullptr}
bool m_Locked [2] = {false}
std::string m_Filename
std::map< int, std::map
< std::string, float > > m_FloatEntryMap
std::map< std::string, float > m_SingleFloatEntryMap
std::map< int, std::map
< std::string, double > > m_DoubleEntryMap
std::map< std::string, double > m_SingleDoubleEntryMap
std::map< int, std::map
< std::string, int > > m_IntEntryMap
std::map< std::string, int > m_SingleIntEntryMap
std::map< int, std::map
< std::string, uint64_t > > m_UInt64EntryMap
std::map< std::string, uint64_t > m_SingleUInt64EntryMap
Detailed Description
Definition at line 10 of file CDBTTree.h.
View newest version in sPHENIX GitHub at line 10 of file CDBTTree.h
Member Enumeration Documentation
anonymous enum private
Enumerator:
SingleEntries
MultipleEntries
Definition at line 41 of file CDBTTree.h.
View newest version in sPHENIX GitHub at line 41 of file CDBTTree.h
Constructor & Destructor Documentation
CDBTTree::CDBTTree () default
CDBTTree::CDBTTree (const std::string & fname) explicit
Definition at line 23 of file CDBTTree.cc.
View newest version in sPHENIX GitHub at line 23 of file CDBTTree.cc
CDBTTree::~CDBTTree ()
Definition at line 28 of file CDBTTree.cc.
View newest version in sPHENIX GitHub at line 28 of file CDBTTree.cc
References m_FloatEntryMap, and m_SingleFloatEntryMap.
Member Function Documentation
void CDBTTree::Commit ()
Definition at line 102 of file CDBTTree.cc.
View newest version in sPHENIX GitHub at line 102 of file CDBTTree.cc
References m_Locked, and MultipleEntries.
Referenced by TimerStats::End(), TPCPedestalCalibration::End(), hcal_towerid::End(), make_cemcCDBTree(), mergeCDBTTrees(), TestCDBTTree(), TSCtoCDBTTree(), MicromegasHotChannelMapData::write(), MicromegasCalibrationData::write(), and towerid::WriteCDBTree().
void CDBTTree::CommitSingle ()
Definition at line 296 of file CDBTTree.cc.
View newest version in sPHENIX GitHub at line 296 of file CDBTTree.cc
References m_Locked, and SingleEntries.
Referenced by TestCDBTTree(), TestWrite(), and MicromegasHotChannelMapData::write().
double CDBTTree::GetDoubleValue (int channel, const std::string & name, int verbose = 1)
Definition at line 724 of file CDBTTree.cc.
View newest version in sPHENIX GitHub at line 724 of file CDBTTree.cc
References LoadCalibrations(), m_DoubleEntryMap, perf_headwind::name, and PHWHERE.
Referenced by CaloGeomMapping::CreateGeomNode(), CentralityReco::Download_centralityScale(), TpcCombinedRawDataUnpacker::process_event(), TpcRawDataDecoder::process_event(), MicromegasCalibrationData::read(), Read(), and InttSurveyMapv1::v_LoadFromCDBTTree().
float CDBTTree::GetFloatValue (int channel, const std::string & name, int verbose = 1)
Definition at line 668 of file CDBTTree.cc.
View newest version in sPHENIX GitHub at line 668 of file CDBTTree.cc
References LoadCalibrations(), m_FloatEntryMap, perf_headwind::name, and PHWHERE.
Referenced by CentralityReco::Download_centralityDivisions(), MbdCalib::Download_Gains(), MbdCalib::Download_Shapes(), MbdCalib::Download_Slew(), MbdCalib::Download_TQT0(), MbdCalib::Download_TTT0(), CaloAna::fitEtaSlices(), pi0EtaByEta::fitEtaSlices(), RawClusterPositionCorrection::InitRun(), mergeCDBTTrees(), CaloTowerCalib::process_event(), CaloTowerStatus::process_event(), RawTowerCalibration::process_event(), RawTowerDigitizer::process_event(), CaloWaveformSim::process_event(), and Read().
int CDBTTree::GetIntValue (int channel, const std::string & name, int verbose = 1)
Definition at line 780 of file CDBTTree.cc.
View newest version in sPHENIX GitHub at line 780 of file CDBTTree.cc
References LoadCalibrations(), m_IntEntryMap, Acts::UnitConstants::min, perf_headwind::name, and PHWHERE.
Referenced by MbdCalib::Download_SampMax(), MbdCalib::Download_Shapes(), MbdCalib::Download_Slew(), EMCalDeadmap(), DeadHotMapLoader::InitRun(), MvtxCombinedRawDataDecoder::InitRun(), InttCombinedRawDataDecoder::LoadHotChannelMapLocal(), InttCombinedRawDataDecoder::LoadHotChannelMapRemote(), CaloTowerStatus::process_event(), TpcCombinedRawDataUnpacker::process_event(), TpcRawDataDecoder::process_event(), MicromegasHotChannelMapData::read(), Read(), InttMaskedChannelSetv1::v_LoadFromCDBTTree(), and InttSurveyMapv1::v_LoadFromCDBTTree().
double CDBTTree::GetSingleDoubleValue (const std::string & name, int verbose = 1)
Definition at line 697 of file CDBTTree.cc.
View newest version in sPHENIX GitHub at line 697 of file CDBTTree.cc
References LoadCalibrations(), m_SingleDoubleEntryMap, and perf_headwind::name.
float CDBTTree::GetSingleFloatValue (const std::string & name, int verbose = 1)
Definition at line 641 of file CDBTTree.cc.
View newest version in sPHENIX GitHub at line 641 of file CDBTTree.cc
References LoadCalibrations(), m_SingleFloatEntryMap, and perf_headwind::name.
Referenced by Read().
int CDBTTree::GetSingleIntValue (const std::string & name, int verbose = 1)
Definition at line 753 of file CDBTTree.cc.
View newest version in sPHENIX GitHub at line 753 of file CDBTTree.cc
References LoadCalibrations(), m_SingleIntEntryMap, Acts::UnitConstants::min, and perf_headwind::name.
Referenced by MvtxCombinedRawDataDecoder::InitRun(), InttCombinedRawDataDecoder::LoadHotChannelMapLocal(), InttCombinedRawDataDecoder::LoadHotChannelMapRemote(), MicromegasHotChannelMapData::read(), InttMaskedChannelSetv1::v_LoadFromCDBTTree(), and InttSurveyMapv1::v_LoadFromCDBTTree().
uint64_t CDBTTree::GetSingleUInt64Value (const std::string & name, int verbose = 1)
Definition at line 809 of file CDBTTree.cc.
View newest version in sPHENIX GitHub at line 809 of file CDBTTree.cc
References LoadCalibrations(), m_SingleUInt64EntryMap, and perf_headwind::name.
uint64_t CDBTTree::GetUInt64Value (int channel, const std::string & name, int verbose = 1)
Definition at line 836 of file CDBTTree.cc.
View newest version in sPHENIX GitHub at line 836 of file CDBTTree.cc
References LoadCalibrations(), m_UInt64EntryMap, perf_headwind::name, and PHWHERE.
void CDBTTree::LoadCalibrations ()
Definition at line 480 of file CDBTTree.cc.
View newest version in sPHENIX GitHub at line 480 of file CDBTTree.cc
References entry, f, ckf::field, testing::internal::GetTypeName(), m_DoubleEntryMap, m_Filename, m_FloatEntryMap, m_IntEntryMap, m_SingleDoubleEntryMap, m_SingleFloatEntryMap, m_SingleIntEntryMap, m_SingleUInt64EntryMap, m_TTree, m_TTreeName, m_UInt64EntryMap, Acts::UnitConstants::min, MultipleEntries, and SingleEntries.
Referenced by CaloGeomMapping::CreateGeomNode(), CentralityReco::Download_centralityDivisions(), CentralityReco::Download_centralityScale(), MbdCalib::Download_Gains(), MbdCalib::Download_SampMax(), MbdCalib::Download_Shapes(), MbdCalib::Download_Slew(), MbdCalib::Download_TQT0(), MbdCalib::Download_TTT0(), GetDoubleValue(), GetFloatValue(), GetIntValue(), GetSingleDoubleValue(), GetSingleFloatValue(), GetSingleIntValue(), GetSingleUInt64Value(), GetUInt64Value(), TpcCombinedRawDataUnpacker::Init(), TpcRawDataDecoder::Init(), InttMaskedChannelSet::LoadFromCDB(), InttSurveyMap::LoadFromCDB(), InttMaskedChannelSet::LoadFromFile(), InttSurveyMap::LoadFromFile(), InttCombinedRawDataDecoder::LoadHotChannelMapLocal(), InttCombinedRawDataDecoder::LoadHotChannelMapRemote(), MicromegasCalibrationData::read(), MicromegasHotChannelMapData::read(), and Read().
void CDBTTree::Print ()
Definition at line 330 of file CDBTTree.cc.
View newest version in sPHENIX GitHub at line 330 of file CDBTTree.cc
References ckf::field, m_DoubleEntryMap, m_FloatEntryMap, m_IntEntryMap, m_SingleDoubleEntryMap, m_SingleFloatEntryMap, m_SingleIntEntryMap, m_SingleUInt64EntryMap, and m_UInt64EntryMap.
Referenced by CentralityReco::Download_centralityDivisions(), TPCPedestalCalibration::End(), Read(), and TestCDBTTree().
void CDBTTree::SetDoubleValue (int channel, const std::string & name, double value)
Definition at line 51 of file CDBTTree.cc.
View newest version in sPHENIX GitHub at line 51 of file CDBTTree.cc
References channel(), m_DoubleEntryMap, m_Locked, MultipleEntries, and perf_headwind::name.
Referenced by TestCDBTTree(), TestWrite(), and MicromegasCalibrationData::write().
void CDBTTree::SetFloatValue (int channel, const std::string & name, float value)
Definition at line 34 of file CDBTTree.cc.
View newest version in sPHENIX GitHub at line 34 of file CDBTTree.cc
References channel(), m_FloatEntryMap, m_Locked, MultipleEntries, and perf_headwind::name.
Referenced by TPCPedestalCalibration::EndRun(), make_cemcCDBTree(), mergeCDBTTrees(), TimerStats::process_event(), TestCDBTTree(), TestWrite(), and TSCtoCDBTTree().
void CDBTTree::SetIntValue (int channel, const std::string & name, int value)
Definition at line 68 of file CDBTTree.cc.
View newest version in sPHENIX GitHub at line 68 of file CDBTTree.cc
References channel(), m_IntEntryMap, m_Locked, MultipleEntries, and perf_headwind::name.
Referenced by hcal_towerid::End(), TPCPedestalCalibration::EndRun(), TestCDBTTree(), TestWrite(), MicromegasHotChannelMapData::write(), and towerid::WriteCDBTree().
void CDBTTree::SetSingleDoubleValue (const std::string & name, double value)
Definition at line 245 of file CDBTTree.cc.
View newest version in sPHENIX GitHub at line 245 of file CDBTTree.cc
References m_Locked, m_SingleDoubleEntryMap, perf_headwind::name, SingleEntries, and value.
Referenced by TestCDBTTree(), and TestWrite().
void CDBTTree::SetSingleFloatValue (const std::string & name, float value)
Definition at line 228 of file CDBTTree.cc.
View newest version in sPHENIX GitHub at line 228 of file CDBTTree.cc
References m_Locked, m_SingleFloatEntryMap, perf_headwind::name, SingleEntries, and value.
Referenced by TestCDBTTree(), and TestWrite().
void CDBTTree::SetSingleIntValue (const std::string & name, int value)
Definition at line 262 of file CDBTTree.cc.
View newest version in sPHENIX GitHub at line 262 of file CDBTTree.cc
References m_Locked, m_SingleIntEntryMap, perf_headwind::name, SingleEntries, and value.
Referenced by TestCDBTTree(), TestWrite(), and MicromegasHotChannelMapData::write().
void CDBTTree::SetSingleUInt64Value (const std::string & name, uint64_t value)
Definition at line 279 of file CDBTTree.cc.
View newest version in sPHENIX GitHub at line 279 of file CDBTTree.cc
References m_Locked, m_SingleUInt64EntryMap, perf_headwind::name, SingleEntries, and value.
Referenced by TestCDBTTree(), and TestWrite().
void CDBTTree::SetUInt64Value (int channel, const std::string & name, uint64_t value)
Definition at line 85 of file CDBTTree.cc.
View newest version in sPHENIX GitHub at line 85 of file CDBTTree.cc
References channel(), m_Locked, m_UInt64EntryMap, MultipleEntries, and perf_headwind::name.
Referenced by TestCDBTTree(), and TestWrite().
void CDBTTree::WriteCDBTTree ()
Definition at line 440 of file CDBTTree.cc.
View newest version in sPHENIX GitHub at line 440 of file CDBTTree.cc
References f, m_DoubleEntryMap, m_Filename, m_FloatEntryMap, m_IntEntryMap, m_Locked, m_SingleDoubleEntryMap, m_SingleFloatEntryMap, m_SingleIntEntryMap, m_SingleUInt64EntryMap, m_TTree, m_UInt64EntryMap, MultipleEntries, SingleEntries, WriteMultipleCDBTTree(), and WriteSingleCDBTTree().
Referenced by TimerStats::End(), TPCPedestalCalibration::End(), hcal_towerid::End(), make_cemcCDBTree(), mergeCDBTTrees(), TestCDBTTree(), TSCtoCDBTTree(), MicromegasHotChannelMapData::write(), MicromegasCalibrationData::write(), and towerid::WriteCDBTree().
void CDBTTree::WriteMultipleCDBTTree ()
Definition at line 107 of file CDBTTree.cc.
View newest version in sPHENIX GitHub at line 107 of file CDBTTree.cc
References test_examples::ids, m_DoubleEntryMap, m_FloatEntryMap, m_IntEntryMap, m_TTree, m_TTreeName, m_UInt64EntryMap, Acts::UnitConstants::min, and MultipleEntries.
Referenced by WriteCDBTTree().
void CDBTTree::WriteSingleCDBTTree ()
Definition at line 302 of file CDBTTree.cc.
View newest version in sPHENIX GitHub at line 302 of file CDBTTree.cc
References ckf::field, m_SingleDoubleEntryMap, m_SingleFloatEntryMap, m_SingleIntEntryMap, m_SingleUInt64EntryMap, m_TTree, m_TTreeName, and SingleEntries.
Referenced by WriteCDBTTree().
Member Data Documentation
std::map<int, std::map<std::string, double> > CDBTTree::m_DoubleEntryMap private
Definition at line 53 of file CDBTTree.h.
View newest version in sPHENIX GitHub at line 53 of file CDBTTree.h
Referenced by GetDoubleValue(), LoadCalibrations(), Print(), SetDoubleValue(), WriteCDBTTree(), and WriteMultipleCDBTTree().
std::string CDBTTree::m_Filename private
Definition at line 50 of file CDBTTree.h.
View newest version in sPHENIX GitHub at line 50 of file CDBTTree.h
Referenced by LoadCalibrations(), and WriteCDBTTree().
std::map<int, std::map<std::string, float> > CDBTTree::m_FloatEntryMap private
Definition at line 51 of file CDBTTree.h.
View newest version in sPHENIX GitHub at line 51 of file CDBTTree.h
Referenced by GetFloatValue(), LoadCalibrations(), Print(), SetFloatValue(), WriteCDBTTree(), WriteMultipleCDBTTree(), and ~CDBTTree().
std::map<int, std::map<std::string, int> > CDBTTree::m_IntEntryMap private
Definition at line 55 of file CDBTTree.h.
View newest version in sPHENIX GitHub at line 55 of file CDBTTree.h
Referenced by GetIntValue(), LoadCalibrations(), Print(), SetIntValue(), WriteCDBTTree(), and WriteMultipleCDBTTree().
bool CDBTTree::m_Locked[2] = {false} private
Definition at line 48 of file CDBTTree.h.
View newest version in sPHENIX GitHub at line 48 of file CDBTTree.h
Referenced by Commit(), CommitSingle(), SetDoubleValue(), SetFloatValue(), SetIntValue(), SetSingleDoubleValue(), SetSingleFloatValue(), SetSingleIntValue(), SetSingleUInt64Value(), SetUInt64Value(), and WriteCDBTTree().
std::map<std::string, double> CDBTTree::m_SingleDoubleEntryMap private
Definition at line 54 of file CDBTTree.h.
View newest version in sPHENIX GitHub at line 54 of file CDBTTree.h
Referenced by GetSingleDoubleValue(), LoadCalibrations(), Print(), SetSingleDoubleValue(), WriteCDBTTree(), and WriteSingleCDBTTree().
std::map<std::string, float> CDBTTree::m_SingleFloatEntryMap private
Definition at line 52 of file CDBTTree.h.
View newest version in sPHENIX GitHub at line 52 of file CDBTTree.h
Referenced by GetSingleFloatValue(), LoadCalibrations(), Print(), SetSingleFloatValue(), WriteCDBTTree(), WriteSingleCDBTTree(), and ~CDBTTree().
std::map<std::string, int> CDBTTree::m_SingleIntEntryMap private
Definition at line 56 of file CDBTTree.h.
View newest version in sPHENIX GitHub at line 56 of file CDBTTree.h
Referenced by GetSingleIntValue(), LoadCalibrations(), Print(), SetSingleIntValue(), WriteCDBTTree(), and WriteSingleCDBTTree().
std::map<std::string, uint64_t> CDBTTree::m_SingleUInt64EntryMap private
Definition at line 58 of file CDBTTree.h.
View newest version in sPHENIX GitHub at line 58 of file CDBTTree.h
Referenced by GetSingleUInt64Value(), LoadCalibrations(), Print(), SetSingleUInt64Value(), WriteCDBTTree(), and WriteSingleCDBTTree().
TTree* CDBTTree::m_TTree[2] = {nullptr} private
Definition at line 47 of file CDBTTree.h.
View newest version in sPHENIX GitHub at line 47 of file CDBTTree.h
Referenced by LoadCalibrations(), WriteCDBTTree(), WriteMultipleCDBTTree(), and WriteSingleCDBTTree().
const std::string CDBTTree::m_TTreeName[2] = {"Single", "Multiple"} private
Definition at line 46 of file CDBTTree.h.
View newest version in sPHENIX GitHub at line 46 of file CDBTTree.h
Referenced by LoadCalibrations(), WriteMultipleCDBTTree(), and WriteSingleCDBTTree().
std::map<int, std::map<std::string, uint64_t> > CDBTTree::m_UInt64EntryMap private
Definition at line 57 of file CDBTTree.h.
View newest version in sPHENIX GitHub at line 57 of file CDBTTree.h
Referenced by GetUInt64Value(), LoadCalibrations(), Print(), SetUInt64Value(), WriteCDBTTree(), and WriteMultipleCDBTTree().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/database/cdbobjects/CDBTTree.h
coresoftware/blob/master/offline/database/cdbobjects/CDBTTree.cc