Analysis Software: PHG4PSTOFSteppingAction Class Reference
PHG4PSTOFSteppingAction Class Reference
#include <coresoftware/blob/master/simulation/g4simulation/g4detectors/PHG4PSTOFSteppingAction.h>
Public Member Functions
PHG4PSTOFSteppingAction (PHG4PSTOFDetector *, const PHParametersContainer *)
constructor
~PHG4PSTOFSteppingAction () override
destructor
bool UserSteppingAction (const G4Step *, bool) override
stepping action
void SetInterfacePointers (PHCompositeNode *) override
reimplemented from base class
Public Member Functions inherited from PHG4SteppingAction
PHG4SteppingAction (const std::string &name, const int i=0)
virtual ~PHG4SteppingAction ()
virtual void Verbosity (const int i)
virtual int Verbosity () const
virtual int Init ()
virtual int InitWithNode (PHCompositeNode *)
virtual double GetScintLightYield (const G4Step *step)
get scintillation photon count. It require a custom set SCINTILLATIONYIELD property to work
virtual double GetVisibleEnergyDeposition (const G4Step *step)
get amount of energy that can make scintillation light, in Unit of GeV.
virtual void StoreLocalCoordinate (PHG4Hit *hit, const G4Step *step, const bool do_prepoint, const bool do_postpoint)
Extract local coordinate of the hit and save to PHG4Hit.
virtual void Print (const std::string &) const
std::string GetName () const
void SetName (const std::string &name)
virtual void SetLightCorrection (const double inner_radius, const double inner_corr, const double outer_radius, const double outer_corr)
virtual double GetLightCorrection (const double r) const
virtual double GetLightCorrection (const double xpos, const double ypos) const
virtual bool ValidCorrection () const
virtual void SetHitNodeName (const std::string &, const std::string &)
Set the G4HIT node names from Subsystem rather than constructing your own.
Private Attributes
PHG4PSTOFDetector * detector_ = nullptr
pointer to the detector
PHG4HitContainer * hits_ = nullptr
pointer to hit container
PHG4Hit * hit = nullptr
PHG4HitContainer * savehitcontainer = nullptr
G4VPhysicalVolume * savevolpre = nullptr
G4VPhysicalVolume * savevolpost = nullptr
int savetrackid = -1
int saveprestepstatus = -1
int savepoststepstatus = -1
double edepsum = 0.
double eionsum = 0.
Detailed Description
Definition at line 16 of file PHG4PSTOFSteppingAction.h.
View newest version in sPHENIX GitHub at line 16 of file PHG4PSTOFSteppingAction.h
Constructor & Destructor Documentation
PHG4PSTOFSteppingAction::PHG4PSTOFSteppingAction (PHG4PSTOFDetector * detector, const PHParametersContainer *)
constructor
Definition at line 40 of file PHG4PSTOFSteppingAction.cc.
View newest version in sPHENIX GitHub at line 40 of file PHG4PSTOFSteppingAction.cc
PHG4PSTOFSteppingAction::~PHG4PSTOFSteppingAction () override
destructor
Definition at line 46 of file PHG4PSTOFSteppingAction.cc.
View newest version in sPHENIX GitHub at line 46 of file PHG4PSTOFSteppingAction.cc
References hit.
Member Function Documentation
void PHG4PSTOFSteppingAction::SetInterfacePointers (PHCompositeNode * topNode) override virtual
reimplemented from base class
Reimplemented from PHG4SteppingAction.
Definition at line 281 of file PHG4PSTOFSteppingAction.cc.
View newest version in sPHENIX GitHub at line 281 of file PHG4PSTOFSteppingAction.cc
References detector_, PHG4Detector::GetName(), hits_, and PHG4PSTOFDetector::SuperDetector().
bool PHG4PSTOFSteppingAction::UserSteppingAction (const G4Step * aStep, bool) override virtual
stepping action
Implements PHG4SteppingAction.
Definition at line 56 of file PHG4PSTOFSteppingAction.cc.
View newest version in sPHENIX GitHub at line 56 of file PHG4PSTOFSteppingAction.cc
References PHG4HitContainer::AddHit(), Acts::UnitConstants::cm, detector_, edepsum, eionsum, PHG4Hit::get_hit_id(), PHG4Hit::get_x(), PHG4HitContainer::GetID(), PHG4SteppingAction::GetName(), PHG4StepStatusDecode::GetStepStatus(), Acts::UnitConstants::GeV, hit, hits_, PHG4PSTOFDetector::IsInPSTOF(), merge_hashes::p, PHWHERE, PHG4Hit::Reset(), savehitcontainer, savepoststepstatus, saveprestepstatus, savetrackid, savevolpost, savevolpre, PHG4Hit::set_edep(), PHG4Hit::set_eion(), PHG4Hit::set_layer(), PHG4Hit::set_t(), PHG4Hit::set_trkid(), PHG4Hit::set_x(), PHG4Hit::set_y(), and PHG4Hit::set_z().
Member Data Documentation
PHG4PSTOFDetector* PHG4PSTOFSteppingAction::detector_ = nullptr private
pointer to the detector
Definition at line 33 of file PHG4PSTOFSteppingAction.h.
View newest version in sPHENIX GitHub at line 33 of file PHG4PSTOFSteppingAction.h
Referenced by SetInterfacePointers(), and UserSteppingAction().
double PHG4PSTOFSteppingAction::edepsum = 0. private
Definition at line 44 of file PHG4PSTOFSteppingAction.h.
View newest version in sPHENIX GitHub at line 44 of file PHG4PSTOFSteppingAction.h
Referenced by UserSteppingAction().
double PHG4PSTOFSteppingAction::eionsum = 0. private
Definition at line 45 of file PHG4PSTOFSteppingAction.h.
View newest version in sPHENIX GitHub at line 45 of file PHG4PSTOFSteppingAction.h
Referenced by UserSteppingAction().
PHG4Hit* PHG4PSTOFSteppingAction::hit = nullptr private
Definition at line 36 of file PHG4PSTOFSteppingAction.h.
View newest version in sPHENIX GitHub at line 36 of file PHG4PSTOFSteppingAction.h
Referenced by UserSteppingAction(), and ~PHG4PSTOFSteppingAction().
PHG4HitContainer* PHG4PSTOFSteppingAction::hits_ = nullptr private
pointer to hit container
Definition at line 35 of file PHG4PSTOFSteppingAction.h.
View newest version in sPHENIX GitHub at line 35 of file PHG4PSTOFSteppingAction.h
Referenced by SetInterfacePointers(), and UserSteppingAction().
PHG4HitContainer* PHG4PSTOFSteppingAction::savehitcontainer = nullptr private
Definition at line 37 of file PHG4PSTOFSteppingAction.h.
View newest version in sPHENIX GitHub at line 37 of file PHG4PSTOFSteppingAction.h
Referenced by UserSteppingAction().
int PHG4PSTOFSteppingAction::savepoststepstatus = -1 private
Definition at line 43 of file PHG4PSTOFSteppingAction.h.
View newest version in sPHENIX GitHub at line 43 of file PHG4PSTOFSteppingAction.h
Referenced by UserSteppingAction().
int PHG4PSTOFSteppingAction::saveprestepstatus = -1 private
Definition at line 42 of file PHG4PSTOFSteppingAction.h.
View newest version in sPHENIX GitHub at line 42 of file PHG4PSTOFSteppingAction.h
Referenced by UserSteppingAction().
int PHG4PSTOFSteppingAction::savetrackid = -1 private
Definition at line 41 of file PHG4PSTOFSteppingAction.h.
View newest version in sPHENIX GitHub at line 41 of file PHG4PSTOFSteppingAction.h
Referenced by UserSteppingAction().
G4VPhysicalVolume* PHG4PSTOFSteppingAction::savevolpost = nullptr private
Definition at line 40 of file PHG4PSTOFSteppingAction.h.
View newest version in sPHENIX GitHub at line 40 of file PHG4PSTOFSteppingAction.h
Referenced by UserSteppingAction().
G4VPhysicalVolume* PHG4PSTOFSteppingAction::savevolpre = nullptr private
Definition at line 39 of file PHG4PSTOFSteppingAction.h.
View newest version in sPHENIX GitHub at line 39 of file PHG4PSTOFSteppingAction.h
Referenced by UserSteppingAction().
The documentation for this class was generated from the following files:
coresoftware/blob/master/simulation/g4simulation/g4detectors/PHG4PSTOFSteppingAction.h
coresoftware/blob/master/simulation/g4simulation/g4detectors/PHG4PSTOFSteppingAction.cc