Analysis Software: SvtxTrackMap Class Reference
SvtxTrackMap Class Reference
#include <coresoftware/blob/master/offline/packages/trackbase_historic/SvtxTrackMap.h>
Public Types
typedef std::map< unsigned int,
SvtxTrack * > TrackMap
typedef std::map< unsigned int,
SvtxTrack * >::const_iterator ConstIter
typedef std::map< unsigned int,
SvtxTrack * >::iterator Iter
Public Member Functions
~SvtxTrackMap () override
void identify (std::ostream &os=std::cout) const override
int isValid () const override
isValid returns non zero if object contains vailid data
PHObject * CloneMe () const override
Virtual copy constructor.
virtual bool empty () const
virtual size_t size () const
virtual size_t count (unsigned int) const
virtual void clear ()
virtual const SvtxTrack * get (unsigned int) const
virtual SvtxTrack * get (unsigned int)
virtual SvtxTrack * insert (const SvtxTrack *)
virtual SvtxTrack * insertWithKey (const SvtxTrack *, unsigned int)
virtual size_t erase (unsigned int)
virtual ConstIter begin () const
virtual ConstIter find (unsigned int idkey) const
virtual ConstIter end () const
virtual Iter begin ()
virtual Iter find (unsigned int idkey)
virtual Iter end ()
Public Member Functions inherited from PHObject
PHObject ()
ctor
~PHObject () override
dtor
virtual PHObject * clone () const final
PHObject * Clone (const char *newname="") const final
void Copy (TObject &object) const final
virtual void Reset ()
Clear Event.
virtual int Integrate () const
virtual int Integrate (PHObject *)
virtual void CopyFrom (const PHObject *obj)
Protected Member Functions
SvtxTrackMap ()
Private Member Functions
ClassDefOverride (SvtxTrackMap, 1)
Detailed Description
Definition at line 11 of file SvtxTrackMap.h.
View newest version in sPHENIX GitHub at line 11 of file SvtxTrackMap.h
Member Typedef Documentation
typedef std::map<unsigned int, SvtxTrack*>::const_iterator SvtxTrackMap::ConstIter
Definition at line 15 of file SvtxTrackMap.h.
View newest version in sPHENIX GitHub at line 15 of file SvtxTrackMap.h
typedef std::map<unsigned int, SvtxTrack*>::iterator SvtxTrackMap::Iter
Definition at line 16 of file SvtxTrackMap.h.
View newest version in sPHENIX GitHub at line 16 of file SvtxTrackMap.h
typedef std::map<unsigned int, SvtxTrack*> SvtxTrackMap::TrackMap
Definition at line 14 of file SvtxTrackMap.h.
View newest version in sPHENIX GitHub at line 14 of file SvtxTrackMap.h
Constructor & Destructor Documentation
SvtxTrackMap::~SvtxTrackMap () inline override
Definition at line 18 of file SvtxTrackMap.h.
View newest version in sPHENIX GitHub at line 18 of file SvtxTrackMap.h
SvtxTrackMap::SvtxTrackMap () inline protected
Definition at line 47 of file SvtxTrackMap.h.
View newest version in sPHENIX GitHub at line 47 of file SvtxTrackMap.h
Member Function Documentation
SvtxTrackMap::ConstIter SvtxTrackMap::begin (void) const virtual
Reimplemented in SvtxTrackMap_v2, and SvtxTrackMap_v1.
Definition at line 8 of file SvtxTrackMap.cc.
View newest version in sPHENIX GitHub at line 8 of file SvtxTrackMap.cc
Referenced by LeptoquarksReco::AddTrackInformation(), TrkrNtuplizer::all_tracks_from(), PHTruthVertexing::assignTracksVertices(), PHSimpleVertexFinder::checkDCAs(), cemcReco::coneSum(), PhotonJet::ConeSum(), TrkrNtuplizer::create_cache_track_from_cluster(), TpcPrototypeGenFitTrkFinder::fill_eval_tree(), TpcPrototypeGenFitTrkFitter::fill_eval_tree(), PHG4TrackFastSimEval::fill_track_tree(), FastTrackingEval::fill_tree(), GenFitTrackProp::fill_tree(), psTOFTimezeroEval::fillOutputNtuples(), SvtxEvaluatorHaiwang::fillOutputNtuples(), EventEvaluator::fillOutputNtuples(), TrackProjectionTools::FindClosestTrack(), TrackProjectorPlaneECAL::get_best_track(), TrackJetInput::get_input(), MultiDetectorMultiplicity::getFilteredNtracks(), HFTriggerMVA::getMaxEMCalEnergy(), PhotonJet::GetRecoHadronsAndJets(), QAG4SimulationKFParticle::getTrack(), SVReco::InitEvent(), HFTrigger::makeAllTracks(), HFTriggerMVA::makeAllTracks(), psTOFTimezeroEval::printInputInfo(), SvtxEvaluatorHaiwang::printInputInfo(), TrkrNtuplizer::printInputInfo(), SvtxEvaluator::printInputInfo(), PHTrackSetCopyMerging::Process(), SvtxSimPerformanceCheckReco::process_event(), FilterEvents::process_event(), FilterEventsUpsilon::process_event(), SimpleTrackingAnalysis::process_event(), ParticleFlowReco::process_event(), BJetModule::process_event(), PHTrackSelector::process_event(), PHTrackCleaner::process_event(), QAG4SimulationTracking::process_event(), PHTpcClusterMover::process_event(), PJTranslator::process_event(), PHGenFitTrackProjection::process_event(), RecoConversionEval::process_event(), ElectronID::process_event(), KshortReconstruction::process_event(), PHRaveVertexing::process_event(), jetrtrack::process_event(), BDiJetModule::process_event(), TruthConversionEval::process_event(), SecondaryVertexFinder::process_event(), TpcPrototypeGenFitTrkFitter::process_event(), PHGenFitTrkFitter::process_event(), sPHAnalysis::process_event_test(), sPHAnalysis::process_event_upsilons(), DumpSvtxTrackMap::process_Node(), TpcDirectLaserReconstruction::process_tracks(), PHFlowJetMaker::run_particle_flow(), TPCHitTrackDisplay::SimulationOut(), and g4evalfn::unmatchedSvtxTrkIds().
SvtxTrackMap::Iter SvtxTrackMap::begin (void) virtual
Reimplemented in SvtxTrackMap_v2, and SvtxTrackMap_v1.
Definition at line 24 of file SvtxTrackMap.cc.
View newest version in sPHENIX GitHub at line 24 of file SvtxTrackMap.cc
SvtxTrackMap::ClassDefOverride (SvtxTrackMap , 1) private
virtual void SvtxTrackMap::clear () inline virtual
Reimplemented in SvtxTrackMap_v1, and SvtxTrackMap_v2.
Definition at line 30 of file SvtxTrackMap.h.
View newest version in sPHENIX GitHub at line 30 of file SvtxTrackMap.h
Referenced by PHCosmicsTrkFitter::process_event(), and PHActsTrkFitter::process_event().
PHObject* SvtxTrackMap::CloneMe () const inline override virtual
Virtual copy constructor.
Reimplemented from PHObject.
Reimplemented in SvtxTrackMap_v1, and SvtxTrackMap_v2.
Definition at line 25 of file SvtxTrackMap.h.
View newest version in sPHENIX GitHub at line 25 of file SvtxTrackMap.h
virtual size_t SvtxTrackMap::count (unsigned int) const inline virtual
Reimplemented in SvtxTrackMap_v1, and SvtxTrackMap_v2.
Definition at line 29 of file SvtxTrackMap.h.
View newest version in sPHENIX GitHub at line 29 of file SvtxTrackMap.h
virtual bool SvtxTrackMap::empty () const inline virtual
Reimplemented in SvtxTrackMap_v1, and SvtxTrackMap_v2.
Definition at line 27 of file SvtxTrackMap.h.
View newest version in sPHENIX GitHub at line 27 of file SvtxTrackMap.h
Referenced by PHG4TrackFastSim::process_event(), TpcPrototypeGenFitTrkFitter::process_event(), and PHGenFitTrkFitter::process_event().
SvtxTrackMap::ConstIter SvtxTrackMap::end (void) const virtual
Reimplemented in SvtxTrackMap_v2, and SvtxTrackMap_v1.
Definition at line 18 of file SvtxTrackMap.cc.
View newest version in sPHENIX GitHub at line 18 of file SvtxTrackMap.cc
Referenced by LeptoquarksReco::AddTrackInformation(), TrkrNtuplizer::all_tracks_from(), PHTruthVertexing::assignTracksVertices(), PHSimpleVertexFinder::checkDCAs(), cemcReco::coneSum(), PhotonJet::ConeSum(), TrkrNtuplizer::create_cache_track_from_cluster(), TpcPrototypeGenFitTrkFinder::fill_eval_tree(), TpcPrototypeGenFitTrkFitter::fill_eval_tree(), PHG4TrackFastSimEval::fill_track_tree(), FastTrackingEval::fill_tree(), GenFitTrackProp::fill_tree(), PHG4TrackFastSimEval::fill_vertex_tree(), psTOFTimezeroEval::fillOutputNtuples(), SvtxEvaluatorHaiwang::fillOutputNtuples(), EventEvaluator::fillOutputNtuples(), TrackProjectionTools::FindClosestTrack(), TrackProjectorPlaneECAL::get_best_track(), TrackJetInput::get_input(), MakeMilleFiles::getEventVertex(), MultiDetectorMultiplicity::getFilteredNtracks(), HFTriggerMVA::getMaxEMCalEnergy(), PhotonJet::GetRecoHadronsAndJets(), QAG4SimulationKFParticle::getTrack(), SVReco::InitEvent(), HFTrigger::makeAllTracks(), HFTriggerMVA::makeAllTracks(), SvtxEvaluatorHaiwang::printInputInfo(), psTOFTimezeroEval::printInputInfo(), TrkrNtuplizer::printInputInfo(), SvtxEvaluator::printInputInfo(), PHTrackSetCopyMerging::Process(), SvtxSimPerformanceCheckReco::process_event(), FilterEvents::process_event(), FilterEventsUpsilon::process_event(), SimpleTrackingAnalysis::process_event(), ParticleFlowReco::process_event(), BJetModule::process_event(), PHTrackCleaner::process_event(), PHTrackSelector::process_event(), QAG4SimulationTracking::process_event(), PHTpcClusterMover::process_event(), PJTranslator::process_event(), PHGenFitTrackProjection::process_event(), RecoConversionEval::process_event(), MakeMilleFiles::process_event(), ElectronID::process_event(), KshortReconstruction::process_event(), PHRaveVertexing::process_event(), jetrtrack::process_event(), BDiJetModule::process_event(), TruthConversionEval::process_event(), SecondaryVertexFinder::process_event(), TpcPrototypeGenFitTrkFitter::process_event(), PHGenFitTrkFitter::process_event(), sPHAnalysis::process_event_test(), sPHAnalysis::process_event_upsilons(), DumpSvtxTrackMap::process_Node(), TpcDirectLaserReconstruction::process_tracks(), PHFlowJetMaker::run_particle_flow(), TPCHitTrackDisplay::SimulationOut(), and g4evalfn::unmatchedSvtxTrkIds().
SvtxTrackMap::Iter SvtxTrackMap::end (void) virtual
Reimplemented in SvtxTrackMap_v2, and SvtxTrackMap_v1.
Definition at line 34 of file SvtxTrackMap.cc.
View newest version in sPHENIX GitHub at line 34 of file SvtxTrackMap.cc
virtual size_t SvtxTrackMap::erase (unsigned int) inline virtual
Reimplemented in SvtxTrackMap_v2, and SvtxTrackMap_v1.
Definition at line 36 of file SvtxTrackMap.h.
View newest version in sPHENIX GitHub at line 36 of file SvtxTrackMap.h
Referenced by PHActsInitialVertexFinder::getIVFTracks(), PHTrackSelector::process_event(), PHTrackCleaner::process_event(), TpcPrototypeGenFitTrkFitter::process_event(), and PHGenFitTrkFitter::process_event().
SvtxTrackMap::ConstIter SvtxTrackMap::find (unsigned int idkey) const virtual
Reimplemented in SvtxTrackMap_v2, and SvtxTrackMap_v1.
Definition at line 13 of file SvtxTrackMap.cc.
View newest version in sPHENIX GitHub at line 13 of file SvtxTrackMap.cc
Referenced by PHActsToSvtxTracks::createSvtxTrack(), PHG4TrackFastSimEval::fill_vertex_tree(), PHActsVertexFinder::fillVertexMap(), PHActsInitialVertexFinder::fillVertexMap(), MakeMilleFiles::getEventVertex(), MakeMilleFiles::process_event(), and PHActsVertexFinder::updateTrackDCA().
SvtxTrackMap::Iter SvtxTrackMap::find (unsigned int idkey) virtual
Reimplemented in SvtxTrackMap_v2, and SvtxTrackMap_v1.
Definition at line 29 of file SvtxTrackMap.cc.
View newest version in sPHENIX GitHub at line 29 of file SvtxTrackMap.cc
virtual const SvtxTrack* SvtxTrackMap::get (unsigned int) const inline virtual
Reimplemented in SvtxTrackMap_v1, and SvtxTrackMap_v2.
Definition at line 32 of file SvtxTrackMap.h.
View newest version in sPHENIX GitHub at line 32 of file SvtxTrackMap.h
Referenced by SvtxTrackEval::all_tracks_from(), JetRecoEval::all_truth_hits(), SvtxVertexEval::all_truth_particles(), JetRecoEval::all_truth_particles(), SvtxTrackEval::best_track_from(), BuildResonanceJetTaggingTree::findMatchedTruthD0(), HFTrackEfficiency::findTracks(), TrackProjectorPlaneECAL::get_best_track(), JetRecoEval::get_energy_contribution(), SvtxVertexEval::get_ntracks_contribution(), PHActsVertexFinder::getTracks(), PHActsInitialVertexFinder::Process(), QAG4SimulationVertex::process_event(), PHTrackCleaner::process_event(), PHActsVertexPropagator::process_event(), PHSimpleVertexFinder::process_event(), ElectronID::process_event(), FillTruthRecoMatchTree::process_event(), PairMaker::process_event_test(), PHActsVertexPropagator::setVtxChi2(), and PHActsInitialVertexFinder::sortTracks().
virtual SvtxTrack* SvtxTrackMap::get (unsigned int) inline virtual
Reimplemented in SvtxTrackMap_v1, and SvtxTrackMap_v2.
Definition at line 33 of file SvtxTrackMap.h.
View newest version in sPHENIX GitHub at line 33 of file SvtxTrackMap.h
void SvtxTrackMap::identify (std::ostream & os = std::cout) const inline override virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from PHObject.
Reimplemented in SvtxTrackMap_v1, and SvtxTrackMap_v2.
Definition at line 20 of file SvtxTrackMap.h.
View newest version in sPHENIX GitHub at line 20 of file SvtxTrackMap.h
References os.
virtual SvtxTrack* SvtxTrackMap::insert (const SvtxTrack *) inline virtual
Reimplemented in SvtxTrackMap_v1, and SvtxTrackMap_v2.
Definition at line 34 of file SvtxTrackMap.h.
View newest version in sPHENIX GitHub at line 34 of file SvtxTrackMap.h
Referenced by PHG4TpcDirectLaser::AppendLaserTrack(), KFParticle_DST::fillParticleNode_Track(), PHTrackSetCopyMerging::Process(), TrackSeedTrackMapConverter::process_event(), FilterEventsUpsilon::process_event(), FilterEvents::process_event(), TpcPrototypeGenFitTrkFinder::process_event(), PHCosmicsTrkFitter::process_event(), PHG4TrackFastSim::process_event(), PHActsTrkFitter::process_event(), TpcPrototypeGenFitTrkFitter::process_event(), and PHGenFitTrkFitter::process_event().
virtual SvtxTrack* SvtxTrackMap::insertWithKey (const SvtxTrack * , unsigned int) inline virtual
Reimplemented in SvtxTrackMap_v2.
Definition at line 35 of file SvtxTrackMap.h.
View newest version in sPHENIX GitHub at line 35 of file SvtxTrackMap.h
Referenced by HFTrackEfficiency::findTracks(), PHCosmicsTrkFitter::loopTracks(), PHActsTrkFitter::loopTracks(), HelicalFitter::process_event(), and SecondaryVertexFinder::process_event().
int SvtxTrackMap::isValid () const inline override virtual
isValid returns non zero if object contains vailid data
Reimplemented from PHObject.
Reimplemented in SvtxTrackMap_v1, and SvtxTrackMap_v2.
Definition at line 24 of file SvtxTrackMap.h.
View newest version in sPHENIX GitHub at line 24 of file SvtxTrackMap.h
virtual size_t SvtxTrackMap::size (void) const inline virtual
Reimplemented in SvtxTrackMap_v1, and SvtxTrackMap_v2.
Definition at line 28 of file SvtxTrackMap.h.
View newest version in sPHENIX GitHub at line 28 of file SvtxTrackMap.h
Referenced by PHG4TrackFastSimEval::fill_track_tree(), TrkrNtuplizer::fillOutputNtuples(), SvtxEvaluator::fillOutputNtuples(), KFParticle_DST::fillParticleNode_Track(), PHActsInitialVertexFinder::getTrackPointers(), PHCosmicsTrkFitter::loopTracks(), PHActsTrkFitter::loopTracks(), FillTruthRecoMatchTree::print_mvtx_diagnostics(), SvtxEvaluatorHaiwang::printInputInfo(), psTOFTimezeroEval::printInputInfo(), TrkrNtuplizer::printInputInfo(), SvtxEvaluator::printInputInfo(), psTOFTimezeroEval::printOutputInfo(), SvtxEvaluatorHaiwang::printOutputInfo(), TrkrNtuplizer::printOutputInfo(), SvtxEvaluator::printOutputInfo(), PHActsInitialVertexFinder::Process(), FilterEvents::process_event(), FilterEventsUpsilon::process_event(), PHTrackCleaner::process_event(), PHTrackSelector::process_event(), PHTpcClusterMover::process_event(), PHSimpleVertexFinder::process_event(), PJTranslator::process_event(), MakeMilleFiles::process_event(), TpcPrototypeGenFitTrkFinder::process_event(), KFParticle_sPHENIX::process_event(), PHCosmicsTrkFitter::process_event(), SecondaryVertexFinder::process_event(), PHActsTrkFitter::process_event(), FillTruthRecoMatchTree::process_event(), sPHAnalysis::process_event_filtered(), PairMaker::process_event_test(), sPHAnalysis::process_event_test(), sPHAnalysis::process_event_upsilons(), DumpSvtxTrackMap::process_Node(), PHTpcResiduals::processTracks(), and PHActsInitialVertexFinder::sortTracks().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/trackbase_historic/SvtxTrackMap.h
coresoftware/blob/master/offline/packages/trackbase_historic/SvtxTrackMap.cc