Analysis Software: PseudoJet Class Reference
PseudoJet Class Reference
#include <JETSCAPE/blob/main/external_packages/fjcore.hh>
Classes
class InexistentUserInfo
class UserInfoBase
Public Types
enum {
X =0, Y =1, Z =2, T =3,
NUM_COORDINATES =4, SIZE =NUM_COORDINATES
}
Public Member Functions
PseudoJet ()
PseudoJet (const double px, const double py, const double pz, const double E)
template<class L >
PseudoJet (const L &some_four_vector)
PseudoJet (bool)
virtual ~PseudoJet ()
double E () const
double e () const
double px () const
double py () const
double pz () const
double phi () const
double phi_std () const
double phi_02pi () const
double rap () const
double rapidity () const
double pseudorapidity () const
double eta () const
double pt2 () const
double pt () const
double perp2 () const
double perp () const
double kt2 () const
double m2 () const
double m () const
double mperp2 () const
double mperp () const
double mt2 () const
double mt () const
double modp2 () const
double modp () const
double Et () const
double Et2 () const
double operator() (int i) const
double operator[] (int i) const
double kt_distance (const PseudoJet &other) const
double plain_distance (const PseudoJet &other) const
double squared_distance (const PseudoJet &other) const
double delta_R (const PseudoJet &other) const
double delta_phi_to (const PseudoJet &other) const
double beam_distance () const
std::valarray< double > four_mom () const
PseudoJet & boost (const PseudoJet &prest)
PseudoJet & unboost (const PseudoJet &prest)
void operator*= (double)
void operator/= (double)
void operator+= (const PseudoJet &)
void operator-= (const PseudoJet &)
void reset (double px, double py, double pz, double E)
void reset (const PseudoJet &psjet)
template<class L >
void reset (const L &some_four_vector)
void reset_PtYPhiM (double pt_in, double y_in, double phi_in, double m_in=0.0)
void reset_momentum (double px, double py, double pz, double E)
void reset_momentum (const PseudoJet &pj)
void reset_momentum_PtYPhiM (double pt, double y, double phi, double m=0.0)
template<class L >
void reset_momentum (const L &some_four_vector)
void set_cached_rap_phi (double rap, double phi)
int user_index () const
void set_user_index (const int index)
void set_user_info (UserInfoBase *user_info_in)
template<class L >
const L & user_info () const
bool has_user_info () const
template<class L >
bool has_user_info () const
const UserInfoBase * user_info_ptr () const
const SharedPtr< UserInfoBase > & user_info_shared_ptr () const
SharedPtr< UserInfoBase > & user_info_shared_ptr ()
std::string description () const
bool has_associated_cluster_sequence () const
bool has_associated_cs () const
bool has_valid_cluster_sequence () const
bool has_valid_cs () const
const ClusterSequence * associated_cluster_sequence () const
const ClusterSequence * associated_cs () const
const ClusterSequence * validated_cluster_sequence () const
const ClusterSequence * validated_cs () const
void set_structure_shared_ptr (const SharedPtr< PseudoJetStructureBase > &structure)
bool has_structure () const
const PseudoJetStructureBase * structure_ptr () const
PseudoJetStructureBase * structure_non_const_ptr ()
const PseudoJetStructureBase * validated_structure_ptr () const
const SharedPtr
< PseudoJetStructureBase > & structure_shared_ptr () const
template<typename StructureType >
const StructureType & structure () const
template<typename TransformerType >
bool has_structure_of () const
template<typename TransformerType >
const
TransformerType::StructureType & structure_of () const
virtual bool has_partner (PseudoJet &partner) const
virtual bool has_child (PseudoJet &child) const
virtual bool has_parents (PseudoJet &parent1, PseudoJet &parent2) const
virtual bool contains (const PseudoJet &constituent) const
virtual bool is_inside (const PseudoJet &jet) const
virtual bool has_constituents () const
virtual std::vector< PseudoJet > constituents () const
virtual bool has_exclusive_subjets () const
std::vector< PseudoJet > exclusive_subjets (const double dcut) const
int n_exclusive_subjets (const double dcut) const
std::vector< PseudoJet > exclusive_subjets (int nsub) const
std::vector< PseudoJet > exclusive_subjets_up_to (int nsub) const
double exclusive_subdmerge (int nsub) const
double exclusive_subdmerge_max (int nsub) const
virtual bool has_pieces () const
virtual std::vector< PseudoJet > pieces () const
int cluster_hist_index () const
void set_cluster_hist_index (const int index)
int cluster_sequence_history_index () const
void set_cluster_sequence_history_index (const int index)
Protected Attributes
SharedPtr< PseudoJetStructureBase > _structure
SharedPtr< UserInfoBase > _user_info
Private Member Functions
void _finish_init ()
void _reset_indices ()
void _ensure_valid_rap_phi () const
void _set_rap_phi () const
Private Attributes
double _px
double _py
double _pz
double _E
double _phi
double _rap
double _kt2
int _cluster_hist_index
int _user_index
Friends
PseudoJet operator* (double, const PseudoJet &)
Detailed Description
Definition at line 520 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 520 of file fjcore.hh
Member Enumeration Documentation
anonymous enum
Enumerator:
X
Y
Z
T
NUM_COORDINATES
SIZE
Definition at line 574 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 574 of file fjcore.hh
Constructor & Destructor Documentation
PseudoJet::PseudoJet () inline
Definition at line 522 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 522 of file fjcore.hh
References _finish_init(), and _reset_indices().
Referenced by join(), and Selector::sum().
PseudoJet::PseudoJet (const double px, const double py, const double pz, const double E)
template<class L > PseudoJet::PseudoJet (const L & some_four_vector) inline
Definition at line 749 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 749 of file fjcore.hh
References reset().
PseudoJet::PseudoJet (bool) inline
Definition at line 525 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 525 of file fjcore.hh
virtual PseudoJet::~PseudoJet () inline virtual
Definition at line 526 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 526 of file fjcore.hh
Member Function Documentation
void PseudoJet::_ensure_valid_rap_phi () const inline private
Definition at line 696 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 696 of file fjcore.hh
References _phi, and _set_rap_phi().
Referenced by phi_02pi(), phi_std(), and rap().
void PseudoJet::_finish_init () private
Definition at line 3749 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 3749 of file fjcore.cc
References pseudojet_invalid_phi, and pseudojet_invalid_rap.
Referenced by PseudoJet(), reset(), and reset_momentum().
void PseudoJet::_reset_indices () inline private
Definition at line 752 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 752 of file fjcore.hh
References _structure, _user_info, SharedPtr< T >::reset(), set_cluster_hist_index(), and set_user_index().
Referenced by PseudoJet(), reset(), and reset_PtYPhiM().
void PseudoJet::_set_rap_phi () const private
Definition at line 3754 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 3754 of file fjcore.cc
References E, Acts::UnitConstants::m2, MaxRap, and twopi.
Referenced by _ensure_valid_rap_phi().
const ClusterSequence * PseudoJet::associated_cluster_sequence () const
Definition at line 3962 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 3962 of file fjcore.cc
Referenced by associated_cs().
const ClusterSequence* PseudoJet::associated_cs () const inline
Definition at line 647 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 647 of file fjcore.hh
References associated_cluster_sequence().
double PseudoJet::beam_distance () const inline
Definition at line 572 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 572 of file fjcore.hh
References _kt2.
PseudoJet & PseudoJet::boost (const PseudoJet & prest)
Definition at line 3870 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 3870 of file fjcore.cc
References assert, and E.
Referenced by avscatcen(), getscatterer(), maxscatcen(), and medinit().
int PseudoJet::cluster_hist_index () const inline
Definition at line 680 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 680 of file fjcore.hh
References _cluster_hist_index.
Referenced by cluster_sequence_history_index().
int PseudoJet::cluster_sequence_history_index () const inline
Definition at line 682 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 682 of file fjcore.hh
References cluster_hist_index().
vector< PseudoJet > PseudoJet::constituents () const virtual
Definition at line 4010 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 4010 of file fjcore.cc
bool PseudoJet::contains (const PseudoJet & constituent) const virtual
Definition at line 4001 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 4001 of file fjcore.cc
double PseudoJet::delta_phi_to (const PseudoJet & other) const
Definition at line 3948 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 3948 of file fjcore.cc
References INTTVtxZ::dphi, ActsTests::PropagationDatasets::phi, pi, and twopi.
double PseudoJet::delta_R (const PseudoJet & other) const inline
Definition at line 568 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 568 of file fjcore.hh
References squared_distance().
string PseudoJet::description () const
Definition at line 3954 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 3954 of file fjcore.cc
double PseudoJet::E () const inline
Definition at line 527 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 527 of file fjcore.hh
References _E.
Referenced by dot_product().
double PseudoJet::e () const inline
Definition at line 528 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 528 of file fjcore.hh
References _E.
double PseudoJet::Et () const inline
Definition at line 560 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 560 of file fjcore.hh
References _E, _kt2, and _pz.
double PseudoJet::Et2 () const inline
Definition at line 561 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 561 of file fjcore.hh
References _E, _kt2, and _pz.
double PseudoJet::eta () const inline
Definition at line 546 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 546 of file fjcore.hh
References pseudorapidity().
double PseudoJet::exclusive_subdmerge (int nsub) const
Definition at line 4035 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 4035 of file fjcore.cc
double PseudoJet::exclusive_subdmerge_max (int nsub) const
Definition at line 4038 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 4038 of file fjcore.cc
std::vector<PseudoJet> PseudoJet::exclusive_subjets (const double dcut) const
std::vector<PseudoJet> PseudoJet::exclusive_subjets (int nsub) const
std::vector< PseudoJet > PseudoJet::exclusive_subjets_up_to (int nsub) const
Definition at line 4022 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 4022 of file fjcore.cc
valarray< double > PseudoJet::four_mom () const
Definition at line 3772 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 3772 of file fjcore.cc
bool PseudoJet::has_associated_cluster_sequence () const
Definition at line 3959 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 3959 of file fjcore.cc
Referenced by has_associated_cs().
bool PseudoJet::has_associated_cs () const inline
Definition at line 643 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 643 of file fjcore.hh
References has_associated_cluster_sequence().
bool PseudoJet::has_child (PseudoJet & child) const virtual
Definition at line 3995 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 3995 of file fjcore.cc
bool PseudoJet::has_constituents () const virtual
Definition at line 4007 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 4007 of file fjcore.cc
bool PseudoJet::has_exclusive_subjets () const virtual
Definition at line 4013 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 4013 of file fjcore.cc
bool PseudoJet::has_parents (PseudoJet & parent1, PseudoJet & parent2) const virtual
Definition at line 3998 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 3998 of file fjcore.cc
bool PseudoJet::has_partner (PseudoJet & partner) const virtual
Definition at line 3992 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 3992 of file fjcore.cc
bool PseudoJet::has_pieces () const virtual
Definition at line 4041 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 4041 of file fjcore.cc
bool PseudoJet::has_structure () const
Definition at line 3975 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 3975 of file fjcore.cc
template<typename TransformerType > bool PseudoJet::has_structure_of () const
Definition at line 791 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 791 of file fjcore.hh
References _structure, and SharedPtr< T >::get().
bool PseudoJet::has_user_info () const inline
Definition at line 625 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 625 of file fjcore.hh
References _user_info, and SharedPtr< T >::get().
template<class L > bool PseudoJet::has_user_info () const inline
Definition at line 629 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 629 of file fjcore.hh
References _user_info, SharedPtr< T >::get(), and Acts::IntegrationTest::L.
bool PseudoJet::has_valid_cluster_sequence () const
Definition at line 3966 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 3966 of file fjcore.cc
Referenced by has_valid_cs().
bool PseudoJet::has_valid_cs () const inline
Definition at line 645 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 645 of file fjcore.hh
References has_valid_cluster_sequence().
bool PseudoJet::is_inside (const PseudoJet & jet) const virtual
Definition at line 4004 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 4004 of file fjcore.cc
double PseudoJet::kt2 () const inline
Definition at line 551 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 551 of file fjcore.hh
References _kt2.
Referenced by getqvec(), hijing(), makeinsplit(), and pyptis().
double PseudoJet::kt_distance (const PseudoJet & other) const
Definition at line 3934 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 3934 of file fjcore.cc
References distance(), INTTVtxZ::dphi, Acts::UnitConstants::min, ActsTests::PropagationDatasets::phi, pi, and twopi.
double PseudoJet::m () const inline
Definition at line 758 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 758 of file fjcore.hh
References m2(), and Acts::UnitConstants::mm.
double PseudoJet::m2 () const inline
Definition at line 552 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 552 of file fjcore.hh
References _E, _kt2, and _pz.
Referenced by m().
double PseudoJet::modp () const inline
Definition at line 559 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 559 of file fjcore.hh
References _kt2, and _pz.
double PseudoJet::modp2 () const inline
Definition at line 558 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 558 of file fjcore.hh
References _kt2, and _pz.
double PseudoJet::mperp () const inline
Definition at line 555 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 555 of file fjcore.hh
References mperp2().
double PseudoJet::mperp2 () const inline
Definition at line 554 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 554 of file fjcore.hh
References _E, and _pz.
Referenced by mperp(), and mt().
double PseudoJet::mt () const inline
Definition at line 557 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 557 of file fjcore.hh
References mperp2().
Referenced by pysugi(), pytbhb(), pytbhg(), pytbhq(), and quench().
double PseudoJet::mt2 () const inline
Definition at line 556 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 556 of file fjcore.hh
References _E, and _pz.
int PseudoJet::n_exclusive_subjets (const double dcut) const
Definition at line 4019 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 4019 of file fjcore.cc
double PseudoJet::operator() (int i) const
Definition at line 3780 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 3780 of file fjcore.cc
References Acts::UnitConstants::e, check_license::err(), Acts::UnitConstants::T, TauVsDIS_MachineLearning_Differentiation::X, TauVsDIS_MachineLearning_Differentiation::Y, and SVM_v1::Z.
void PseudoJet::operator*= (double coeff)
Definition at line 3828 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 3828 of file fjcore.cc
void PseudoJet::operator+= (const PseudoJet & other_jet)
Definition at line 3839 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 3839 of file fjcore.cc
void PseudoJet::operator-= (const PseudoJet & other_jet)
Definition at line 3846 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 3846 of file fjcore.cc
void PseudoJet::operator/= (double coeff)
Definition at line 3836 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 3836 of file fjcore.cc
double PseudoJet::operator[] (int i) const inline
Definition at line 563 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 563 of file fjcore.hh
References i.
double PseudoJet::perp () const inline
Definition at line 550 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 550 of file fjcore.hh
References _kt2.
double PseudoJet::perp2 () const inline
Definition at line 549 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 549 of file fjcore.hh
References _kt2.
double PseudoJet::phi () const inline
Definition at line 532 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 532 of file fjcore.hh
References phi_02pi().
double PseudoJet::phi_02pi () const inline
Definition at line 536 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 536 of file fjcore.hh
References _ensure_valid_rap_phi(), and _phi.
Referenced by phi().
double PseudoJet::phi_std () const inline
Definition at line 533 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 533 of file fjcore.hh
References _ensure_valid_rap_phi(), _phi, pi, and twopi.
std::vector< PseudoJet > PseudoJet::pieces () const virtual
Definition at line 4044 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 4044 of file fjcore.cc
Referenced by join().
double PseudoJet::plain_distance (const PseudoJet & other) const
Definition at line 3942 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 3942 of file fjcore.cc
References INTTVtxZ::dphi, ActsTests::PropagationDatasets::phi, pi, and twopi.
Referenced by squared_distance().
double PseudoJet::pseudorapidity () const
Definition at line 3797 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 3797 of file fjcore.cc
References MaxRap, Acts::VectorHelpers::perp(), pi, and ActsTests::PropagationDatasets::theta.
Referenced by eta().
double PseudoJet::pt () const inline
Definition at line 548 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 548 of file fjcore.hh
References _kt2.
Referenced by Selector::scalar_pt_sum().
double PseudoJet::pt2 () const inline
Definition at line 547 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 547 of file fjcore.hh
References _kt2.
Referenced by dokinematics(), fjet(), fjetrig(), g(), getqvec(), gphoton(), pyevwt(), pyhiremn(), pykcut(), pymirm(), pyprep(), pyptfs(), pyptis(), and pyptmi().
double PseudoJet::px () const inline
Definition at line 529 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 529 of file fjcore.hh
References _px.
Referenced by avscatcen(), dot_product(), getscatterer(), getsscat(), hijsrt(), luptdi(), lustrf(), maxscatcen(), pyhiscat(), pyptdi(), pyscat(), and pystrf().
double PseudoJet::py () const inline
Definition at line 530 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 530 of file fjcore.hh
References _py.
Referenced by avscatcen(), dot_product(), getscatterer(), getsscat(), hijsrt(), luptdi(), lustrf(), maxscatcen(), pyhiscat(), pyptdi(), pyscat(), and pystrf().
double PseudoJet::pz () const inline
Definition at line 531 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 531 of file fjcore.hh
References _pz.
Referenced by __example_6.f__(), __example_7.f__(), __example_8.f__(), avscatcen(), dot_product(), getqvec(), getscatterer(), getsscat(), hijsrt(), makeinsplit(), makesplitting(), maxscatcen(), pybesq(), pydiff(), pyhidiff(), pyhiremn(), pyhiscat(), pyscat(), and sorted_by_pz().
double PseudoJet::rap () const inline
Definition at line 540 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 540 of file fjcore.hh
References _ensure_valid_rap_phi(), and _rap.
Referenced by rapidity().
double PseudoJet::rapidity () const inline
Definition at line 544 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 544 of file fjcore.hh
References rap().
void PseudoJet::reset (double px, double py, double pz, double E) inline
Definition at line 762 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 762 of file fjcore.hh
References _E, _finish_init(), _px, _py, _pz, and _reset_indices().
Referenced by PseudoJet(), and reset().
void PseudoJet::reset (const PseudoJet & psjet) inline
Definition at line 582 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 582 of file fjcore.hh
template<class L > void PseudoJet::reset (const L & some_four_vector) inline
Definition at line 585 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 585 of file fjcore.hh
References reset().
void PseudoJet::reset_momentum (double px, double py, double pz, double E) inline
Definition at line 770 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 770 of file fjcore.hh
References _E, _finish_init(), _px, _py, and _pz.
Referenced by reset_momentum().
void PseudoJet::reset_momentum (const PseudoJet & pj) inline
Definition at line 777 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 777 of file fjcore.hh
References _E, _kt2, _phi, _px, _py, _pz, and _rap.
template<class L > void PseudoJet::reset_momentum (const L & some_four_vector) inline
Definition at line 601 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 601 of file fjcore.hh
References reset_momentum().
void PseudoJet::reset_momentum_PtYPhiM (double pt, double y, double phi, double m = 0.0)
Definition at line 3911 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 3911 of file fjcore.cc
References assert, and twopi.
Referenced by reset_PtYPhiM().
void PseudoJet::reset_PtYPhiM (double pt_in, double y_in, double phi_in, double m_in = 0.0) inline
Definition at line 594 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 594 of file fjcore.hh
References _reset_indices(), and reset_momentum_PtYPhiM().
void PseudoJet::set_cached_rap_phi (double rap, double phi)
Definition at line 3906 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 3906 of file fjcore.cc
References phi_in, and twopi.
void PseudoJet::set_cluster_hist_index (const int index) inline
Definition at line 681 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 681 of file fjcore.hh
References _cluster_hist_index, and index.
Referenced by _reset_indices(), and set_cluster_sequence_history_index().
void PseudoJet::set_cluster_sequence_history_index (const int index) inline
Definition at line 684 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 684 of file fjcore.hh
References set_cluster_hist_index().
void PseudoJet::set_structure_shared_ptr (const SharedPtr< PseudoJetStructureBase > & structure)
Definition at line 3972 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 3972 of file fjcore.cc
void PseudoJet::set_user_index (const int index) inline
Definition at line 607 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 607 of file fjcore.hh
References _user_index, and index.
Referenced by _reset_indices().
void PseudoJet::set_user_info (UserInfoBase * user_info_in) inline
Definition at line 617 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 617 of file fjcore.hh
References _user_info, and SharedPtr< T >::reset().
double PseudoJet::squared_distance (const PseudoJet & other) const inline
Definition at line 566 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 566 of file fjcore.hh
References plain_distance().
Referenced by delta_R().
template<typename StructureType > const StructureType & PseudoJet::structure () const
Definition at line 787 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 787 of file fjcore.hh
References validated_structure_ptr().
PseudoJetStructureBase * PseudoJet::structure_non_const_ptr ()
Definition at line 3981 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 3981 of file fjcore.cc
template<typename TransformerType > const TransformerType::StructureType & PseudoJet::structure_of () const
Definition at line 796 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 796 of file fjcore.hh
References _structure.
const PseudoJetStructureBase * PseudoJet::structure_ptr () const
Definition at line 3978 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 3978 of file fjcore.cc
const SharedPtr< PseudoJetStructureBase > & PseudoJet::structure_shared_ptr () const
Definition at line 3989 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 3989 of file fjcore.cc
PseudoJet & PseudoJet::unboost (const PseudoJet & prest)
Definition at line 3885 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 3885 of file fjcore.cc
References assert, and E.
int PseudoJet::user_index () const inline
Definition at line 606 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 606 of file fjcore.hh
References _user_index.
template<class L > const L& PseudoJet::user_info () const inline
Definition at line 621 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 621 of file fjcore.hh
References _user_info, SharedPtr< T >::get(), and Acts::IntegrationTest::L.
const UserInfoBase* PseudoJet::user_info_ptr () const inline
Definition at line 632 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 632 of file fjcore.hh
References _user_info, and SharedPtr< T >::get().
const SharedPtr<UserInfoBase>& PseudoJet::user_info_shared_ptr () const inline
Definition at line 635 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 635 of file fjcore.hh
References _user_info.
SharedPtr<UserInfoBase>& PseudoJet::user_info_shared_ptr () inline
Definition at line 638 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 638 of file fjcore.hh
References _user_info.
const ClusterSequence* PseudoJet::validated_cluster_sequence () const inline
Definition at line 648 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 648 of file fjcore.hh
References validated_cs().
const ClusterSequence * PseudoJet::validated_cs () const
Definition at line 3969 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 3969 of file fjcore.cc
Referenced by validated_cluster_sequence().
const PseudoJetStructureBase * PseudoJet::validated_structure_ptr () const
Definition at line 3984 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 3984 of file fjcore.cc
Referenced by structure().
Friends And Related Function Documentation
PseudoJet operator* (double , const PseudoJet &) friend
Definition at line 3816 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 3816 of file fjcore.cc
Member Data Documentation
int PseudoJet::_cluster_hist_index private
Definition at line 693 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 693 of file fjcore.hh
Referenced by cluster_hist_index(), and set_cluster_hist_index().
double PseudoJet::_E private
Definition at line 690 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 690 of file fjcore.hh
Referenced by E(), e(), Et(), Et2(), m2(), mperp2(), mt2(), reset(), and reset_momentum().
double PseudoJet::_kt2 private
Definition at line 692 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 692 of file fjcore.hh
Referenced by beam_distance(), Et(), Et2(), kt2(), m2(), modp(), modp2(), perp(), perp2(), pt(), pt2(), and reset_momentum().
double PseudoJet::_phi mutable private
Definition at line 691 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 691 of file fjcore.hh
Referenced by _ensure_valid_rap_phi(), phi_02pi(), phi_std(), and reset_momentum().
double PseudoJet::_px private
Definition at line 690 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 690 of file fjcore.hh
Referenced by px(), reset(), and reset_momentum().
double PseudoJet::_py private
Definition at line 690 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 690 of file fjcore.hh
Referenced by py(), reset(), and reset_momentum().
double PseudoJet::_pz private
Definition at line 690 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 690 of file fjcore.hh
Referenced by Et(), Et2(), m2(), modp(), modp2(), mperp2(), mt2(), pz(), reset(), and reset_momentum().
double PseudoJet::_rap mutable private
Definition at line 691 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 691 of file fjcore.hh
Referenced by rap(), and reset_momentum().
SharedPtr<PseudoJetStructureBase> PseudoJet::_structure protected
Definition at line 687 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 687 of file fjcore.hh
Referenced by _reset_indices(), has_structure_of(), and structure_of().
int PseudoJet::_user_index private
Definition at line 693 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 693 of file fjcore.hh
Referenced by set_user_index(), and user_index().
SharedPtr<UserInfoBase> PseudoJet::_user_info protected
Definition at line 688 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 688 of file fjcore.hh
Referenced by _reset_indices(), has_user_info(), set_user_info(), user_info(), user_info_ptr(), and user_info_shared_ptr().
The documentation for this class was generated from the following files:
JETSCAPE/blob/main/external_packages/fjcore.hh
JETSCAPE/blob/main/external_packages/fjcore.cc