Analysis Software: BranchComparisonHarness Struct Reference
BranchComparisonHarness Struct Reference
#include <acts/blob/sPHENIX/Examples/Scripts/compareRootFiles.hpp>
Classes
class EventLoaderT
class IEventLoader
struct TreeMetadata
class UnsupportedBranchType
Public Types
using TreeComparator = std::function< bool()>
Public Member Functions
void loadCurrentEvent ()
Static Public Member Functions
static BranchComparisonHarness create (TreeMetadata &treeMetadata, const std::string &branchName, const EDataType dataType, const std::string &className)
Public Attributes
std::string branchName
HomogeneousPair< AnyVector > eventData
HomogeneousPair< std::pair
< IndexComparator,
IndexSwapper > > sortHarness
TreeComparator eventDataEqual
std::function< void()> dumpEventData
Static Private Member Functions
template<typename T >
static BranchComparisonHarness create (TreeMetadata &treeMetadata, const std::string &branchName)
static BranchComparisonHarness createVector (TreeMetadata &treeMetadata, const std::string &branchName, const std::string elemType)
template<typename T >
static std::string toString (const T &data)
template<typename U >
static std::string toString (const std::vector< U > &vector)
Private Attributes
std::unique_ptr< IEventLoader > m_eventLoaderPtr
Detailed Description
Definition at line 248 of file compareRootFiles.hpp.
View newest version in sPHENIX GitHub at line 248 of file compareRootFiles.hpp
Member Typedef Documentation
using BranchComparisonHarness::TreeComparator = std::function<bool()>
Definition at line 269 of file compareRootFiles.hpp.
View newest version in sPHENIX GitHub at line 269 of file compareRootFiles.hpp
Member Function Documentation
static BranchComparisonHarness BranchComparisonHarness::create (TreeMetadata & treeMetadata, const std::string & branchName, const EDataType dataType, const std::string & className) inline static
Definition at line 288 of file compareRootFiles.hpp.
View newest version in sPHENIX GitHub at line 288 of file compareRootFiles.hpp
References branchName, createVector(), and testing::internal::move().
Referenced by compareRootFiles().
template<typename T > static BranchComparisonHarness BranchComparisonHarness::create (TreeMetadata & treeMetadata, const std::string & branchName) inline static private
Definition at line 341 of file compareRootFiles.hpp.
View newest version in sPHENIX GitHub at line 341 of file compareRootFiles.hpp
References branchName, compare(), dumpEventData, BranchComparisonHarness::TreeMetadata::entryCount, eventData, eventDataEqual, i, j, m_eventLoaderPtr, testing::internal::move(), sortHarness, swap(), toString(), BranchComparisonHarness::TreeMetadata::tree1Reader, and BranchComparisonHarness::TreeMetadata::tree2Reader.
static BranchComparisonHarness BranchComparisonHarness::createVector (TreeMetadata & treeMetadata, const std::string & branchName, const std::string elemType) inline static private
Definition at line 442 of file compareRootFiles.hpp.
View newest version in sPHENIX GitHub at line 442 of file compareRootFiles.hpp
References CREATE_VECTOR__HANDLE_INTEGER_TYPE, and CREATE_VECTOR__HANDLE_TYPE.
Referenced by create().
void BranchComparisonHarness::loadCurrentEvent () inline
Definition at line 258 of file compareRootFiles.hpp.
View newest version in sPHENIX GitHub at line 258 of file compareRootFiles.hpp
template<typename T > static std::string BranchComparisonHarness::toString (const T & data) inline static private
Definition at line 475 of file compareRootFiles.hpp.
View newest version in sPHENIX GitHub at line 475 of file compareRootFiles.hpp
References configureMap::data.
Referenced by create().
template<typename U > static std::string BranchComparisonHarness::toString (const std::vector< U > & vector) inline static private
Definition at line 482 of file compareRootFiles.hpp.
View newest version in sPHENIX GitHub at line 482 of file compareRootFiles.hpp
References configureMap::data.
Member Data Documentation
std::string BranchComparisonHarness::branchName
Definition at line 250 of file compareRootFiles.hpp.
View newest version in sPHENIX GitHub at line 250 of file compareRootFiles.hpp
Referenced by create().
std::function<void()> BranchComparisonHarness::dumpEventData
Definition at line 274 of file compareRootFiles.hpp.
View newest version in sPHENIX GitHub at line 274 of file compareRootFiles.hpp
Referenced by create().
HomogeneousPair<AnyVector> BranchComparisonHarness::eventData
Definition at line 253 of file compareRootFiles.hpp.
View newest version in sPHENIX GitHub at line 253 of file compareRootFiles.hpp
Referenced by create().
TreeComparator BranchComparisonHarness::eventDataEqual
Definition at line 270 of file compareRootFiles.hpp.
View newest version in sPHENIX GitHub at line 270 of file compareRootFiles.hpp
Referenced by create().
std::unique_ptr<IEventLoader> BranchComparisonHarness::m_eventLoaderPtr private
Definition at line 438 of file compareRootFiles.hpp.
View newest version in sPHENIX GitHub at line 438 of file compareRootFiles.hpp
Referenced by create().
HomogeneousPair<std::pair<IndexComparator, IndexSwapper> > BranchComparisonHarness::sortHarness
Definition at line 263 of file compareRootFiles.hpp.
View newest version in sPHENIX GitHub at line 263 of file compareRootFiles.hpp
Referenced by create().
The documentation for this struct was generated from the following file:
acts/blob/sPHENIX/Examples/Scripts/compareRootFiles.hpp