Analysis Software: analysis/blob/master/EMCal-LEDs/macro/read-LEDs.C File Reference
read-LEDs.C File Reference
#include <calobase/TowerInfoDefs.h>
#include <string>
#include <vector>
#include <iostream>
#include <TH2F.h>
#include <TFile.h>
#include <TTree.h>
Namespaces
namespace myAnalysis
Functions
void myAnalysis::init (const string &inputFile="data/LEDTowerBuilder.root")
void myAnalysis::analyze (UInt_t nevents=0)
void myAnalysis::finalize (const string &outputFile="output/test.root")
void convert_channel_to_tower_bin ()
void read_LEDs (const string &inputFile="data/LEDTowerBuilder.root", const string &outputFile="output/test.root", UInt_t nevents=0)
int main (int argc, char *argv[])
Variables
TFile * myAnalysis::input
TTree * myAnalysis::led_tree
TH1F * myAnalysis::hTime
TH1F * myAnalysis::hADC
TH1F * myAnalysis::hadc
TH1F * myAnalysis::hPed
TH1F * myAnalysis::hChannels
TH2F * myAnalysis::h2TimeVsChannel
TH2F * myAnalysis::h2ADCVsChannel
TH2F * myAnalysis::h2PedVsChannel
TH2F * myAnalysis::h2ADCVsTime
TH2F * myAnalysis::h2PedVsTime
TH2F * myAnalysis::h2ADCVsPed
TH2F * myAnalysis::h2TimeVsChannel_scat
TH2F * myAnalysis::h2ADCVsChannel_scat
TH2F * myAnalysis::h2PedVsChannel_scat
TH2F * myAnalysis::h2ADCVsTime_scat
TH2F * myAnalysis::h2PedVsTime_scat
TH2F * myAnalysis::h2ADCVsPed_scat
vector< TH2F * > myAnalysis::h2adcVsTime
UInt_t myAnalysis::time_bins = 32
Float_t myAnalysis::time_min = 0-0.5
Float_t myAnalysis::time_max = 32-0.5
UInt_t myAnalysis::adc_bins = 1800
Float_t myAnalysis::adc_min = 0
Float_t myAnalysis::adc_max = 18000
UInt_t myAnalysis::ped_bins = 1650
Float_t myAnalysis::ped_min = 0
Float_t myAnalysis::ped_max = 16500
Function Documentation
void convert_channel_to_tower_bin ()
Definition at line 262 of file read-LEDs.C.
View newest version in sPHENIX GitHub at line 262 of file read-LEDs.C
References TowerInfoDefs::encode_emcal(), KF_timing::etabin, TowerInfoDefs::getCaloTowerEtaBin(), TowerInfoDefs::getCaloTowerPhiBin(), and i.
int main (int argc, char * argv[])
Definition at line 284 of file read-LEDs.C.
View newest version in sPHENIX GitHub at line 284 of file read-LEDs.C
References physmon_vertexing::events, digitization_config::input, check_smearing_config::output, and read_LEDs().
void read_LEDs (const string & inputFile = "data/LEDTowerBuilder.root", const string & outputFile = "output/test.root", UInt_t nevents = 0)
Definition at line 272 of file read-LEDs.C.
View newest version in sPHENIX GitHub at line 272 of file read-LEDs.C
References myAnalysis::analyze(), myAnalysis::finalize(), myAnalysis::init(), and nevents().
Referenced by main().