Analysis Software: analysis/blob/master/AndersonAnalysisModules/ColdQcdCorrelatorAnalysis/SCorrelatorJetTree/Fun4All_RunCorrelatorJetTree.C File Reference
Fun4All_RunCorrelatorJetTree.C File Reference
#include <vector>
#include <string>
#include <cstdlib>
#include <utility>
#include <FROG.h>
#include <G4_Magnet.C>
#include <fun4all/Fun4AllDstInputManager.h>
#include <g4main/Fun4AllDstPileupInputManager.h>
#include <Trkr_QA.C>
#include <Trkr_Reco.C>
#include <Trkr_Eval.C>
#include <Trkr_RecoInit.C>
#include <Trkr_Clustering.C>
#include <Trkr_Diagnostics.C>
#include <G4_TrkrSimulation.C>
#include <g4eval/SvtxEvaluator.h>
#include <g4eval/SvtxTruthRecoTableEval.h>
#include <caloreco/RawClusterBuilderTopo.h>
#include <particleflowreco/ParticleFlowReco.h>
#include "/sphenix/user/danderson/install/include/scorrelatorjettree/SCorrelatorJetTree.h"
Functions
void Fun4All_RunCorrelatorJetTree (const vector< string > &sInput=SInDefault, const string sOutput=SOutDefault, const int nEvents=NEvtDefault, const int verbosity=VerbDefault)
Variables
static const int NEvtDefault = 10
static const int VerbDefault = 0
static const size_t NTopoClusts = 2
static const size_t NTopoPar = 3
static const string SOutDefault = "testingPAuInput.root"
static const vector< string > SInDefault
Function Documentation
void Fun4All_RunCorrelatorJetTree (const vector< string > & sInput = SInDefault, const string sOutput = SOutDefault, const int nEvents = NEvtDefault, const int verbosity = VerbDefault)
Definition at line 80 of file Fun4All_RunCorrelatorJetTree.C.
View newest version in sPHENIX GitHub at line 80 of file Fun4All_RunCorrelatorJetTree.C
References Fun4AllServer::instance(), Intt_Cells(), Intt_Clustering(), Load(), G4MAGNET::magfield_rescale, MagnetFieldInit(), MagnetInit(), Enable::MICROMEGAS, Micromegas_Cells(), Micromegas_Clustering(), Mvtx_Cells(), Mvtx_Clustering(), nEvents, NTopoClusts, NTopoPar, utils::run, HeavyFlavorReco::runTracking, to_string(), TPC_Cells(), TPC_Clustering(), Tracking_Reco(), TrackingInit(), verbosity, and Verbosity().
Variable Documentation
const int NEvtDefault = 10 static
Definition at line 61 of file Fun4All_RunCorrelatorJetTree.C.
View newest version in sPHENIX GitHub at line 61 of file Fun4All_RunCorrelatorJetTree.C
const size_t NTopoClusts = 2 static
Definition at line 63 of file Fun4All_RunCorrelatorJetTree.C.
View newest version in sPHENIX GitHub at line 63 of file Fun4All_RunCorrelatorJetTree.C
Referenced by Fun4All_RunCorrelatorJetTree().
const size_t NTopoPar = 3 static
Definition at line 64 of file Fun4All_RunCorrelatorJetTree.C.
View newest version in sPHENIX GitHub at line 64 of file Fun4All_RunCorrelatorJetTree.C
Referenced by Fun4All_RunCorrelatorJetTree().
const vector<string> SInDefault static
Initial value:
= {
  "DST_GLOBAL_pythia8_Jet10_sHijing_pAu_0_10fm_500kHz_bkg_0_10fm-0000000009-00009.root",
  "DST_TRKR_G4HIT_pythia8_Jet10_sHijing_pAu_0_10fm_500kHz_bkg_0_10fm-0000000009-00009.root",
  "DST_TRACKSEEDS_pythia8_Jet10_sHijing_pAu_0_10fm_500kHz_bkg_0_10fm-0000000009-00009.root",
  "DST_TRKR_CLUSTER_pythia8_Jet10_sHijing_pAu_0_10fm_500kHz_bkg_0_10fm-0000000009-00009.root",
  "DST_TRACKS_pythia8_Jet10_sHijing_pAu_0_10fm_500kHz_bkg_0_10fm-0000000009-00009.root",
  "DST_CALO_G4HIT_pythia8_Jet10_sHijing_pAu_0_10fm_500kHz_bkg_0_10fm-0000000009-00009.root",
  "DST_CALO_CLUSTER_pythia8_Jet10_sHijing_pAu_0_10fm_500kHz_bkg_0_10fm-0000000009-00009.root",
  "DST_TRUTH_G4HIT_pythia8_Jet10_sHijing_pAu_0_10fm_500kHz_bkg_0_10fm-0000000009-00009.root",
  "DST_TRUTH_pythia8_Jet10_sHijing_pAu_0_10fm_500kHz_bkg_0_10fm-0000000009-00009.root"
}
Definition at line 66 of file Fun4All_RunCorrelatorJetTree.C.
View newest version in sPHENIX GitHub at line 66 of file Fun4All_RunCorrelatorJetTree.C
const string SOutDefault = "testingPAuInput.root" static
Definition at line 65 of file Fun4All_RunCorrelatorJetTree.C.
View newest version in sPHENIX GitHub at line 65 of file Fun4All_RunCorrelatorJetTree.C
const int VerbDefault = 0 static
Definition at line 62 of file Fun4All_RunCorrelatorJetTree.C.
View newest version in sPHENIX GitHub at line 62 of file Fun4All_RunCorrelatorJetTree.C