Analysis Software: Acts::TorchEdgeClassifier Exception Reference
Acts::TorchEdgeClassifier Exception Reference final
#include <acts/blob/sPHENIX/Plugins/ExaTrkX/include/Acts/Plugins/ExaTrkX/TorchEdgeClassifier.hpp>
Classes
struct Config
Public Member Functions
TorchEdgeClassifier (const Config &cfg, std::unique_ptr< const Logger > logger)
~TorchEdgeClassifier ()
std::tuple< std::any, std::any,
std::any > operator() (std::any nodes, std::any edges, int deviceHint=-1) override
Config config () const
Public Member Functions inherited from Acts::EdgeClassificationBase
virtual ~EdgeClassificationBase ()=default
Private Member Functions
const auto & logger () const
Private Attributes
std::unique_ptr< const
Acts::Logger > m_logger
Config m_cfg
c10::DeviceType m_deviceType
std::unique_ptr
< torch::jit::Module > m_model
Detailed Description
Definition at line 26 of file TorchEdgeClassifier.hpp.
View newest version in sPHENIX GitHub at line 26 of file TorchEdgeClassifier.hpp
Constructor & Destructor Documentation
Acts::TorchEdgeClassifier::TorchEdgeClassifier (const Config & cfg, std::unique_ptr< const Logger > logger)
Definition at line 20 of file TorchEdgeClassifier.cpp.
View newest version in sPHENIX GitHub at line 20 of file TorchEdgeClassifier.cpp
References ACTS_DEBUG, ACTS_INFO, Acts::UnitConstants::e, m_cfg, m_deviceType, m_model, and Acts::TorchEdgeClassifier::Config::modelPath.
Acts::TorchEdgeClassifier::~TorchEdgeClassifier ()
Definition at line 43 of file TorchEdgeClassifier.cpp.
View newest version in sPHENIX GitHub at line 43 of file TorchEdgeClassifier.cpp
Member Function Documentation
Config Acts::TorchEdgeClassifier::config () const inline
Definition at line 42 of file TorchEdgeClassifier.hpp.
View newest version in sPHENIX GitHub at line 42 of file TorchEdgeClassifier.hpp
References m_cfg().
const auto& Acts::TorchEdgeClassifier::logger () const inline private
Definition at line 46 of file TorchEdgeClassifier.hpp.
View newest version in sPHENIX GitHub at line 46 of file TorchEdgeClassifier.hpp
References m_logger.
Referenced by operator()().
std::tuple< std::any, std::any, std::any > Acts::TorchEdgeClassifier::operator() (std::any nodes, std::any edges, int deviceHint = -1) override virtual
Perform edge classification
Parameters
nodes Node tensor with shape (n_nodes, n_node_features)
edges Edge-index tensor with shape (2, n_edges)
deviceHint Which GPU to pick. Not relevant for CPU-only builds
Returns
(node_tensor, edge_tensor, score_tensor)
Implements Acts::EdgeClassificationBase.
Definition at line 45 of file TorchEdgeClassifier.cpp.
View newest version in sPHENIX GitHub at line 45 of file TorchEdgeClassifier.cpp
References ACTS_DEBUG, Acts::ACTS_VERBOSE(), Acts::TorchEdgeClassifier::Config::cut, logger(), m_cfg, m_deviceType, m_model, mask, testing::internal::move(), Acts::TorchEdgeClassifier::Config::nChunks, Acts::TorchEdgeClassifier::Config::numFeatures, check_smearing_config::output, TauVsDIS_MachineLearning_Differentiation::results, and Acts::TorchEdgeClassifier::Config::undirected.
Member Data Documentation
Config Acts::TorchEdgeClassifier::m_cfg private
Definition at line 48 of file TorchEdgeClassifier.hpp.
View newest version in sPHENIX GitHub at line 48 of file TorchEdgeClassifier.hpp
Referenced by operator()(), and TorchEdgeClassifier().
c10::DeviceType Acts::TorchEdgeClassifier::m_deviceType private
Definition at line 49 of file TorchEdgeClassifier.hpp.
View newest version in sPHENIX GitHub at line 49 of file TorchEdgeClassifier.hpp
Referenced by operator()(), and TorchEdgeClassifier().
std::unique_ptr<const Acts::Logger> Acts::TorchEdgeClassifier::m_logger private
Definition at line 45 of file TorchEdgeClassifier.hpp.
View newest version in sPHENIX GitHub at line 45 of file TorchEdgeClassifier.hpp
std::unique_ptr<torch::jit::Module> Acts::TorchEdgeClassifier::m_model private
Definition at line 50 of file TorchEdgeClassifier.hpp.
View newest version in sPHENIX GitHub at line 50 of file TorchEdgeClassifier.hpp
Referenced by operator()(), and TorchEdgeClassifier().
The documentation for this exception was generated from the following files:
acts/blob/sPHENIX/Plugins/ExaTrkX/include/Acts/Plugins/ExaTrkX/TorchEdgeClassifier.hpp
acts/blob/sPHENIX/Plugins/ExaTrkX/src/TorchEdgeClassifier.cpp