Analysis Software: G4Eval::ClusCntr Class Reference
G4Eval::ClusCntr Class Reference
#include <coresoftware/blob/master/simulation/g4simulation/g4eval/g4evaltools.h>
Public Member Functions
ClusCntr (TrkrClusterComparer *_=nullptr)
TrkrClusterContainer * get_PHG4_clusters ()
TrkrClusterContainer * get_SVTX_clusters ()
void reset ()
std::array< int, 3 > find_matches ()
std::array< int, 3 > find_matches (TrkrTruthTrack *g4_track, SvtxTrack *sv_track)
int phg4_n_matched ()
int svtx_n_matched ()
int phg4_nclus ()
int svtx_nclus ()
int addClusKeys (SvtxTrack *)
int addClusKeys (TrkrTruthTrack *)
std::array< int, 5 > svtx_cntclus ()
std::array< int, 5 > phg4_cntclus ()
std::array< int, 5 > svtx_cnt_matchedclus ()
std::array< int, 5 > phg4_cnt_matchedclus ()
std::vector< ClusLoc > phg4_clusloc_all ()
std::vector< ClusLoc > phg4_clusloc_unmatched ()
std::vector< ClusLoc > svtx_clusloc_all ()
std::vector< ClusLoc > svtx_clusloc_unmatched ()
std::vector< ClusLoc > clusloc_matched ()
void set_comparer (TrkrClusterComparer *_comp)
Public Attributes
Vector svtx_keys {}
Vector phg4_keys {}
double match_stat {0}
std::vector< bool > svtx_matches
std::vector< bool > phg4_matches
Private Types
using Vector = std::vector< std::pair< TrkrDefs::hitsetkey, TrkrDefs::cluskey >>
using Iter = Vector::iterator
Private Member Functions
std::array< int, 5 > cntclus (Vector &keys)
std::array< int, 5 > cnt_matchedclus (Vector &keys, std::vector< bool > &matches)
Private Attributes
TrkrClusterComparer * comp
Detailed Description
Definition at line 124 of file g4evaltools.h.
View newest version in sPHENIX GitHub at line 124 of file g4evaltools.h
Member Typedef Documentation
using G4Eval::ClusCntr::Iter = Vector::iterator private
Definition at line 128 of file g4evaltools.h.
View newest version in sPHENIX GitHub at line 128 of file g4evaltools.h
using G4Eval::ClusCntr::Vector = std::vector<std::pair<TrkrDefs::hitsetkey, TrkrDefs::cluskey>> private
Definition at line 127 of file g4evaltools.h.
View newest version in sPHENIX GitHub at line 127 of file g4evaltools.h
Constructor & Destructor Documentation
G4Eval::ClusCntr::ClusCntr (TrkrClusterComparer * _ = nullptr) inline
Definition at line 135 of file g4evaltools.h.
View newest version in sPHENIX GitHub at line 135 of file g4evaltools.h
References _.
Member Function Documentation
int G4Eval::ClusCntr::addClusKeys (SvtxTrack *)
Referenced by FillTruthRecoMatchTree::print_mvtx_diagnostics(), and FillTruthRecoMatchTree::process_event().
int G4Eval::ClusCntr::addClusKeys (TrkrTruthTrack *)
std::vector<ClusLoc> G4Eval::ClusCntr::clusloc_matched ()
Referenced by FillTruthRecoMatchTree::process_event().
std::array<int, 5> G4Eval::ClusCntr::cnt_matchedclus (Vector & keys, std::vector< bool > & matches) private
Referenced by phg4_cnt_matchedclus(), and svtx_cnt_matchedclus().
std::array<int, 5> G4Eval::ClusCntr::cntclus (Vector & keys) private
Referenced by phg4_cntclus(), and svtx_cntclus().
std::array<int, 3> G4Eval::ClusCntr::find_matches ()
Referenced by FillTruthRecoMatchTree::process_event().
std::array<int, 3> G4Eval::ClusCntr::find_matches (TrkrTruthTrack * g4_track, SvtxTrack * sv_track)
TrkrClusterContainer* G4Eval::ClusCntr::get_PHG4_clusters ()
Referenced by FillTruthRecoMatchTree::print_mvtx_diagnostics(), and FillTruthRecoMatchTree::process_event().
TrkrClusterContainer* G4Eval::ClusCntr::get_SVTX_clusters ()
Referenced by FillTruthRecoMatchTree::print_mvtx_diagnostics(), and FillTruthRecoMatchTree::process_event().
std::vector<ClusLoc> G4Eval::ClusCntr::phg4_clusloc_all ()
Referenced by FillTruthRecoMatchTree::process_event().
std::vector<ClusLoc> G4Eval::ClusCntr::phg4_clusloc_unmatched ()
Referenced by FillTruthRecoMatchTree::process_event().
std::array<int, 5> G4Eval::ClusCntr::phg4_cnt_matchedclus () inline
Definition at line 166 of file g4evaltools.h.
View newest version in sPHENIX GitHub at line 166 of file g4evaltools.h
References cnt_matchedclus(), phg4_keys, and phg4_matches.
Referenced by FillTruthRecoMatchTree::process_event().
std::array<int, 5> G4Eval::ClusCntr::phg4_cntclus () inline
Definition at line 163 of file g4evaltools.h.
View newest version in sPHENIX GitHub at line 163 of file g4evaltools.h
References cntclus(), and phg4_keys.
Referenced by FillTruthRecoMatchTree::print_mvtx_diagnostics(), and FillTruthRecoMatchTree::process_event().
int G4Eval::ClusCntr::phg4_n_matched ()
int G4Eval::ClusCntr::phg4_nclus () inline
Definition at line 153 of file g4evaltools.h.
View newest version in sPHENIX GitHub at line 153 of file g4evaltools.h
References phg4_keys.
void G4Eval::ClusCntr::reset ()
void G4Eval::ClusCntr::set_comparer (TrkrClusterComparer * _comp) inline
Definition at line 175 of file g4evaltools.h.
View newest version in sPHENIX GitHub at line 175 of file g4evaltools.h
References comp.
std::vector<ClusLoc> G4Eval::ClusCntr::svtx_clusloc_all ()
Referenced by FillTruthRecoMatchTree::process_event().
std::vector<ClusLoc> G4Eval::ClusCntr::svtx_clusloc_unmatched ()
Referenced by FillTruthRecoMatchTree::process_event().
std::array<int, 5> G4Eval::ClusCntr::svtx_cnt_matchedclus () inline
Definition at line 165 of file g4evaltools.h.
View newest version in sPHENIX GitHub at line 165 of file g4evaltools.h
References cnt_matchedclus(), svtx_keys, and svtx_matches.
std::array<int, 5> G4Eval::ClusCntr::svtx_cntclus () inline
Definition at line 162 of file g4evaltools.h.
View newest version in sPHENIX GitHub at line 162 of file g4evaltools.h
References cntclus(), and svtx_keys.
Referenced by FillTruthRecoMatchTree::print_mvtx_diagnostics(), and FillTruthRecoMatchTree::process_event().
int G4Eval::ClusCntr::svtx_n_matched ()
int G4Eval::ClusCntr::svtx_nclus () inline
Definition at line 154 of file g4evaltools.h.
View newest version in sPHENIX GitHub at line 154 of file g4evaltools.h
References svtx_keys.
Member Data Documentation
TrkrClusterComparer* G4Eval::ClusCntr::comp private
Definition at line 130 of file g4evaltools.h.
View newest version in sPHENIX GitHub at line 130 of file g4evaltools.h
Referenced by set_comparer().
double G4Eval::ClusCntr::match_stat {0}
Definition at line 143 of file g4evaltools.h.
View newest version in sPHENIX GitHub at line 143 of file g4evaltools.h
Vector G4Eval::ClusCntr::phg4_keys {}
Definition at line 141 of file g4evaltools.h.
View newest version in sPHENIX GitHub at line 141 of file g4evaltools.h
Referenced by phg4_cnt_matchedclus(), phg4_cntclus(), and phg4_nclus().
std::vector<bool> G4Eval::ClusCntr::phg4_matches
Definition at line 157 of file g4evaltools.h.
View newest version in sPHENIX GitHub at line 157 of file g4evaltools.h
Referenced by phg4_cnt_matchedclus().
Vector G4Eval::ClusCntr::svtx_keys {}
Definition at line 140 of file g4evaltools.h.
View newest version in sPHENIX GitHub at line 140 of file g4evaltools.h
Referenced by svtx_cnt_matchedclus(), svtx_cntclus(), and svtx_nclus().
std::vector<bool> G4Eval::ClusCntr::svtx_matches
Definition at line 156 of file g4evaltools.h.
View newest version in sPHENIX GitHub at line 156 of file g4evaltools.h
Referenced by svtx_cnt_matchedclus().
The documentation for this class was generated from the following file:
coresoftware/blob/master/simulation/g4simulation/g4eval/g4evaltools.h