Analysis Software: tinyxml2::XMLNode Class Reference
tinyxml2::XMLNode Class Reference abstract
#include <JETSCAPE/blob/main/external_packages/tinyxml2.h>
Public Member Functions
const XMLDocument * GetDocument () const
Get the XMLDocument that owns this XMLNode.
XMLDocument * GetDocument ()
Get the XMLDocument that owns this XMLNode.
virtual XMLElement * ToElement ()
Safely cast to an Element, or null.
virtual XMLText * ToText ()
Safely cast to Text, or null.
virtual XMLComment * ToComment ()
Safely cast to a Comment, or null.
virtual XMLDocument * ToDocument ()
Safely cast to a Document, or null.
virtual XMLDeclaration * ToDeclaration ()
Safely cast to a Declaration, or null.
virtual XMLUnknown * ToUnknown ()
Safely cast to an Unknown, or null.
virtual const XMLElement * ToElement () const
virtual const XMLText * ToText () const
virtual const XMLComment * ToComment () const
virtual const XMLDocument * ToDocument () const
virtual const XMLDeclaration * ToDeclaration () const
virtual const XMLUnknown * ToUnknown () const
const char * Value () const
void SetValue (const char *val, bool staticMem=false)
const XMLNode * Parent () const
Get the parent of this node on the DOM.
XMLNode * Parent ()
bool NoChildren () const
Returns true if this node has no children.
const XMLNode * FirstChild () const
Get the first child node, or null if none exists.
XMLNode * FirstChild ()
const XMLElement * FirstChildElement (const char *name=0) const
XMLElement * FirstChildElement (const char *name=0)
const XMLNode * LastChild () const
Get the last child node, or null if none exists.
XMLNode * LastChild ()
const XMLElement * LastChildElement (const char *name=0) const
XMLElement * LastChildElement (const char *name=0)
const XMLNode * PreviousSibling () const
Get the previous (left) sibling node of this node.
XMLNode * PreviousSibling ()
const XMLElement * PreviousSiblingElement (const char *name=0) const
Get the previous (left) sibling element of this node, with an optionally supplied name.
XMLElement * PreviousSiblingElement (const char *name=0)
const XMLNode * NextSibling () const
Get the next (right) sibling node of this node.
XMLNode * NextSibling ()
const XMLElement * NextSiblingElement (const char *name=0) const
Get the next (right) sibling element of this node, with an optionally supplied name.
XMLElement * NextSiblingElement (const char *name=0)
XMLNode * InsertEndChild (XMLNode *addThis)
XMLNode * LinkEndChild (XMLNode *addThis)
XMLNode * InsertFirstChild (XMLNode *addThis)
XMLNode * InsertAfterChild (XMLNode *afterThis, XMLNode *addThis)
void DeleteChildren ()
void DeleteChild (XMLNode *node)
virtual XMLNode * ShallowClone (XMLDocument *document) const =0
virtual bool ShallowEqual (const XMLNode *compare) const =0
virtual bool Accept (XMLVisitor *visitor) const =0
void SetUserData (void *userData)
void * GetUserData () const
Protected Member Functions
XMLNode (XMLDocument *)
virtual ~XMLNode ()
virtual char * ParseDeep (char *, StrPair *)
Protected Attributes
XMLDocument * _document
XMLNode * _parent
StrPair _value
XMLNode * _firstChild
XMLNode * _lastChild
XMLNode * _prev
XMLNode * _next
void * _userData
Private Member Functions
void Unlink (XMLNode *child)
void InsertChildPreamble (XMLNode *insertThis) const
const XMLElement * ToElementWithName (const char *name) const
XMLNode (const XMLNode &)
XMLNode & operator= (const XMLNode &)
Static Private Member Functions
static void DeleteNode (XMLNode *node)
Private Attributes
MemPool * _memPool
Friends
class XMLDocument
class XMLElement
Detailed Description
XMLNode is a base class for every object that is in the XML Document Object Model (DOM), except XMLAttributes. Nodes have siblings, a parent, and children which can be navigated. A node is always in a XMLDocument. The type of a XMLNode can be queried, and it can be cast to its more defined type.
A XMLDocument allocates memory for all its Nodes. When the XMLDocument gets deleted, all its Nodes will also be deleted.
    A Document can contain:     Element (container or leaf)
                                                Comment (leaf)
                                                Unknown (leaf)
                                                Declaration( leaf )
    An Element can contain:     Element (container or leaf)
                                                Text    (leaf)
                                                Attributes (not on tree)
                                                Comment (leaf)
                                                Unknown (leaf)
Definition at line 632 of file tinyxml2.h.
View newest version in sPHENIX GitHub at line 632 of file tinyxml2.h
Constructor & Destructor Documentation
tinyxml2::XMLNode::XMLNode (XMLDocument * doc) protected
Definition at line 725 of file tinyxml2.cc.
View newest version in sPHENIX GitHub at line 725 of file tinyxml2.cc
tinyxml2::XMLNode::~XMLNode () protected virtual
Definition at line 736 of file tinyxml2.cc.
View newest version in sPHENIX GitHub at line 736 of file tinyxml2.cc
References _parent, DeleteChildren(), and Unlink().
Referenced by DeleteNode().
tinyxml2::XMLNode::XMLNode (const XMLNode &) private
Member Function Documentation
virtual bool tinyxml2::XMLNode::Accept (XMLVisitor * visitor) const pure virtual
Accept a hierarchical visit of the nodes in the TinyXML-2 DOM. Every node in the XML tree will be conditionally visited and the host will be called back via the XMLVisitor interface.
This is essentially a SAX interface for TinyXML-2. (Note however it doesn't re-parse the XML for the callbacks, so the performance of TinyXML-2 is unchanged by using this interface versus any other.)
The interface has been based on ideas from:
http://www.saxproject.org/
http://c2.com/cgi/wiki?HierarchicalVisitorPattern
Which are both good references for "visiting".
An example of using Accept():
XMLPrinter printer;
tinyxmlDoc.Accept(&printer);
const char* xmlcstr = printer.CStr();
Implemented in tinyxml2::XMLDocument, tinyxml2::XMLElement, tinyxml2::XMLUnknown, tinyxml2::XMLDeclaration, tinyxml2::XMLComment, and tinyxml2::XMLText.
void tinyxml2::XMLNode::DeleteChild (XMLNode * node)
Delete a child of this node.
Definition at line 795 of file tinyxml2.cc.
View newest version in sPHENIX GitHub at line 795 of file tinyxml2.cc
References _document, _parent, DeleteNode(), TIXMLASSERT, and Unlink().
Referenced by DeleteChildren(), and tinyxml2::XMLDocument::DeleteNode().
void tinyxml2::XMLNode::DeleteChildren ()
Delete all the children of this node.
Definition at line 763 of file tinyxml2.cc.
View newest version in sPHENIX GitHub at line 763 of file tinyxml2.cc
References _firstChild, _lastChild, DeleteChild(), and TIXMLASSERT.
Referenced by tinyxml2::XMLDocument::Clear(), tinyxml2::XMLDocument::Parse(), and ~XMLNode().
void tinyxml2::XMLNode::DeleteNode (XMLNode * node) static private
Definition at line 1043 of file tinyxml2.cc.
View newest version in sPHENIX GitHub at line 1043 of file tinyxml2.cc
References _memPool, tinyxml2::MemPool::Free(), and ~XMLNode().
Referenced by DeleteChild(), tinyxml2::XMLDocument::DeleteNode(), and ParseDeep().
const XMLNode* tinyxml2::XMLNode::FirstChild () const inline
Get the first child node, or null if none exists.
Definition at line 724 of file tinyxml2.h.
View newest version in sPHENIX GitHub at line 724 of file tinyxml2.h
Referenced by tinyxml2::XMLElement::Accept(), tinyxml2::XMLDocument::Accept(), tinyxml2::XMLElement::GetText(), ParseDeep(), tinyxml2::XMLElement::QueryBoolText(), tinyxml2::XMLElement::QueryDoubleText(), tinyxml2::XMLElement::QueryFloatText(), tinyxml2::XMLElement::QueryInt64Text(), tinyxml2::XMLElement::QueryIntText(), tinyxml2::XMLElement::QueryUnsignedText(), and tinyxml2::XMLElement::SetText().
XMLNode* tinyxml2::XMLNode::FirstChild () inline
Definition at line 728 of file tinyxml2.h.
View newest version in sPHENIX GitHub at line 728 of file tinyxml2.h
const XMLElement * tinyxml2::XMLNode::FirstChildElement (const char * name = 0) const
Get the first child element, or optionally the first child element with the specified name.
Definition at line 897 of file tinyxml2.cc.
View newest version in sPHENIX GitHub at line 897 of file tinyxml2.cc
References _firstChild, and fixGDML::element.
Referenced by Jetscape::JetScape::CompareElementsFromXML(), Jetscape::JetScape::DetermineTaskListFromXML(), Jetscape::JetScape::DetermineWritersFromXML(), Jetscape::JetScapeXML::GetXMLElementMain(), Jetscape::JetScapeXML::GetXMLElementUser(), HybridHadronization::Init(), PythiaGun::InitTask(), epemGun::InitTask(), Jetscape::JetScapeTaskSupport::ReadSeedFromXML(), Jetscape::JetScape::recurseToBuild(), Jetscape::JetScape::recurseToSearch(), and Jetscape::JetScape::SetModuleId().
XMLElement* tinyxml2::XMLNode::FirstChildElement (const char * name = 0) inline
Definition at line 737 of file tinyxml2.h.
View newest version in sPHENIX GitHub at line 737 of file tinyxml2.h
References perf_headwind::name.
const XMLDocument* tinyxml2::XMLNode::GetDocument () const inline
Get the XMLDocument that owns this XMLNode.
Definition at line 639 of file tinyxml2.h.
View newest version in sPHENIX GitHub at line 639 of file tinyxml2.h
References TIXMLASSERT.
Referenced by tinyxml2::XMLElement::SetText().
XMLDocument* tinyxml2::XMLNode::GetDocument () inline
Get the XMLDocument that owns this XMLNode.
Definition at line 644 of file tinyxml2.h.
View newest version in sPHENIX GitHub at line 644 of file tinyxml2.h
References TIXMLASSERT.
void* tinyxml2::XMLNode::GetUserData () const inline
Get user data set into the XMLNode. TinyXML-2 in no way processes or interprets user data. It is initially 0.
Definition at line 886 of file tinyxml2.h.
View newest version in sPHENIX GitHub at line 886 of file tinyxml2.h
XMLNode * tinyxml2::XMLNode::InsertAfterChild (XMLNode * afterThis, XMLNode * addThis)
Add a node after the specified child node. If the child node is already part of the document, it is moved from its old location to the new location. Returns the addThis argument or 0 if the afterThis node is not a child of this node, or if the node does not belong to the same document.
Definition at line 866 of file tinyxml2.cc.
View newest version in sPHENIX GitHub at line 866 of file tinyxml2.cc
References _document, _next, _parent, _prev, InsertChildPreamble(), InsertEndChild(), and TIXMLASSERT.
void tinyxml2::XMLNode::InsertChildPreamble (XMLNode * insertThis) const private
Definition at line 1053 of file tinyxml2.cc.
View newest version in sPHENIX GitHub at line 1053 of file tinyxml2.cc
References _document, _memPool, _parent, tinyxml2::MemPool::SetTracked(), TIXMLASSERT, and Unlink().
Referenced by InsertAfterChild(), InsertEndChild(), and InsertFirstChild().
XMLNode * tinyxml2::XMLNode::InsertEndChild (XMLNode * addThis)
Add a child node as the last (right) child. If the child node is already part of the document, it is moved from its old location to the new location. Returns the addThis argument or 0 if the node does not belong to the same document.
Definition at line 805 of file tinyxml2.cc.
View newest version in sPHENIX GitHub at line 805 of file tinyxml2.cc
References _document, _firstChild, _lastChild, _next, _parent, _prev, InsertChildPreamble(), and TIXMLASSERT.
Referenced by InsertAfterChild(), and ParseDeep().
XMLNode * tinyxml2::XMLNode::InsertFirstChild (XMLNode * addThis)
Add a child node as the first (left) child. If the child node is already part of the document, it is moved from its old location to the new location. Returns the addThis argument or 0 if the node does not belong to the same document.
Definition at line 835 of file tinyxml2.cc.
View newest version in sPHENIX GitHub at line 835 of file tinyxml2.cc
References _document, _firstChild, _lastChild, _next, _parent, _prev, InsertChildPreamble(), and TIXMLASSERT.
Referenced by tinyxml2::XMLElement::SetText().
const XMLNode* tinyxml2::XMLNode::LastChild () const inline
Get the last child node, or null if none exists.
Definition at line 742 of file tinyxml2.h.
View newest version in sPHENIX GitHub at line 742 of file tinyxml2.h
XMLNode* tinyxml2::XMLNode::LastChild () inline
Definition at line 746 of file tinyxml2.h.
View newest version in sPHENIX GitHub at line 746 of file tinyxml2.h
const XMLElement * tinyxml2::XMLNode::LastChildElement (const char * name = 0) const
Get the last child element or optionally the last child element with the specified name.
Definition at line 909 of file tinyxml2.cc.
View newest version in sPHENIX GitHub at line 909 of file tinyxml2.cc
References _lastChild, and fixGDML::element.
XMLElement* tinyxml2::XMLNode::LastChildElement (const char * name = 0) inline
Definition at line 755 of file tinyxml2.h.
View newest version in sPHENIX GitHub at line 755 of file tinyxml2.h
References perf_headwind::name.
XMLNode* tinyxml2::XMLNode::LinkEndChild (XMLNode * addThis) inline
Definition at line 800 of file tinyxml2.h.
View newest version in sPHENIX GitHub at line 800 of file tinyxml2.h
const XMLNode* tinyxml2::XMLNode::NextSibling () const inline
Get the next (right) sibling node of this node.
Definition at line 776 of file tinyxml2.h.
View newest version in sPHENIX GitHub at line 776 of file tinyxml2.h
Referenced by ParseDeep().
XMLNode* tinyxml2::XMLNode::NextSibling () inline
Definition at line 780 of file tinyxml2.h.
View newest version in sPHENIX GitHub at line 780 of file tinyxml2.h
const XMLElement * tinyxml2::XMLNode::NextSiblingElement (const char * name = 0) const
Get the next (right) sibling element of this node, with an optionally supplied name.
Definition at line 921 of file tinyxml2.cc.
View newest version in sPHENIX GitHub at line 921 of file tinyxml2.cc
References _next, and fixGDML::element.
Referenced by Jetscape::JetScape::DetermineTaskListFromXML(), HybridHadronization::Init(), Jetscape::JetScape::recurseToBuild(), Jetscape::JetScape::recurseToSearch(), and Jetscape::JetScape::SetModuleId().
XMLElement* tinyxml2::XMLNode::NextSiblingElement (const char * name = 0) inline
Definition at line 787 of file tinyxml2.h.
View newest version in sPHENIX GitHub at line 787 of file tinyxml2.h
References perf_headwind::name.
bool tinyxml2::XMLNode::NoChildren () const inline
Returns true if this node has no children.
Definition at line 719 of file tinyxml2.h.
View newest version in sPHENIX GitHub at line 719 of file tinyxml2.h
Referenced by tinyxml2::XMLDocument::Parse().
XMLNode& tinyxml2::XMLNode::operator= (const XMLNode &) private
const XMLNode* tinyxml2::XMLNode::Parent () const inline
Get the parent of this node on the DOM.
Definition at line 710 of file tinyxml2.h.
View newest version in sPHENIX GitHub at line 710 of file tinyxml2.h
Referenced by tinyxml2::XMLPrinter::VisitEnter().
XMLNode* tinyxml2::XMLNode::Parent () inline
Definition at line 714 of file tinyxml2.h.
View newest version in sPHENIX GitHub at line 714 of file tinyxml2.h
char * tinyxml2::XMLNode::ParseDeep (char * p, StrPair * parentEnd) protected virtual
Reimplemented in tinyxml2::XMLElement, tinyxml2::XMLUnknown, tinyxml2::XMLDeclaration, tinyxml2::XMLComment, and tinyxml2::XMLText.
Definition at line 945 of file tinyxml2.cc.
View newest version in sPHENIX GitHub at line 945 of file tinyxml2.cc
References _document, _memPool, _value, tinyxml2::XMLElement::CLOSING, tinyxml2::XMLElement::ClosingType(), DeleteNode(), tinyxml2::StrPair::Empty(), tinyxml2::XMLDocument::Error(), FirstChild(), tinyxml2::StrPair::GetStr(), tinyxml2::XMLDocument::Identify(), InsertEndChild(), tinyxml2::XMLElement::Name(), NextSibling(), tinyxml2::XMLElement::OPEN, merge_hashes::p, ParseDeep(), tinyxml2::XMLDocument::SetError(), tinyxml2::MemPool::SetTracked(), tinyxml2::XMLUtil::StringEqual(), TIXMLASSERT, ToDeclaration(), ToDocument(), ToElement(), tinyxml2::StrPair::TransferTo(), Value(), tinyxml2::XML_ERROR_MISMATCHED_ELEMENT, tinyxml2::XML_ERROR_PARSING, and tinyxml2::XML_ERROR_PARSING_DECLARATION.
Referenced by tinyxml2::XMLDocument::Parse(), ParseDeep(), and tinyxml2::XMLElement::ParseDeep().
const XMLNode* tinyxml2::XMLNode::PreviousSibling () const inline
Get the previous (left) sibling node of this node.
Definition at line 760 of file tinyxml2.h.
View newest version in sPHENIX GitHub at line 760 of file tinyxml2.h
XMLNode* tinyxml2::XMLNode::PreviousSibling () inline
Definition at line 764 of file tinyxml2.h.
View newest version in sPHENIX GitHub at line 764 of file tinyxml2.h
const XMLElement * tinyxml2::XMLNode::PreviousSiblingElement (const char * name = 0) const
Get the previous (left) sibling element of this node, with an optionally supplied name.
Definition at line 933 of file tinyxml2.cc.
View newest version in sPHENIX GitHub at line 933 of file tinyxml2.cc
References _prev, and fixGDML::element.
XMLElement* tinyxml2::XMLNode::PreviousSiblingElement (const char * name = 0) inline
Definition at line 771 of file tinyxml2.h.
View newest version in sPHENIX GitHub at line 771 of file tinyxml2.h
References perf_headwind::name.
void tinyxml2::XMLNode::SetUserData (void * userData) inline
Set user data into the XMLNode. TinyXML-2 in no way processes or interprets user data. It is initially 0.
Definition at line 879 of file tinyxml2.h.
View newest version in sPHENIX GitHub at line 879 of file tinyxml2.h
void tinyxml2::XMLNode::SetValue (const char * val, bool staticMem = false)
Set the Value of an XML node.
See Also
Value()
Definition at line 752 of file tinyxml2.cc.
View newest version in sPHENIX GitHub at line 752 of file tinyxml2.cc
References _value, tinyxml2::StrPair::SetInternedStr(), and tinyxml2::StrPair::SetStr().
Referenced by tinyxml2::XMLElement::SetText().
virtual XMLNode* tinyxml2::XMLNode::ShallowClone (XMLDocument * document) const pure virtual
Make a copy of this node, but not its children. You may pass in a Document pointer that will be the owner of the new Node. If the 'document' is null, then the node returned will be allocated from the current Document. (this->GetDocument())
Note: if called on a XMLDocument, this will return null.
Implemented in tinyxml2::XMLDocument, tinyxml2::XMLElement, tinyxml2::XMLUnknown, tinyxml2::XMLDeclaration, tinyxml2::XMLComment, and tinyxml2::XMLText.
virtual bool tinyxml2::XMLNode::ShallowEqual (const XMLNode * compare) const pure virtual
Test if 2 nodes are the same, but don't test children. The 2 nodes do not need to be in the same Document.
Note: if called on a XMLDocument, this will return false.
Implemented in tinyxml2::XMLDocument, tinyxml2::XMLElement, tinyxml2::XMLUnknown, tinyxml2::XMLDeclaration, tinyxml2::XMLComment, and tinyxml2::XMLText.
virtual XMLComment* tinyxml2::XMLNode::ToComment () inline virtual
Safely cast to a Comment, or null.
Reimplemented in tinyxml2::XMLComment.
Definition at line 658 of file tinyxml2.h.
View newest version in sPHENIX GitHub at line 658 of file tinyxml2.h
Referenced by tinyxml2::XMLComment::ShallowEqual().
virtual const XMLComment* tinyxml2::XMLNode::ToComment () const inline virtual
Reimplemented in tinyxml2::XMLComment.
Definition at line 680 of file tinyxml2.h.
View newest version in sPHENIX GitHub at line 680 of file tinyxml2.h
virtual XMLDeclaration* tinyxml2::XMLNode::ToDeclaration () inline virtual
Safely cast to a Declaration, or null.
Reimplemented in tinyxml2::XMLDeclaration.
Definition at line 666 of file tinyxml2.h.
View newest version in sPHENIX GitHub at line 666 of file tinyxml2.h
Referenced by ParseDeep(), and tinyxml2::XMLDeclaration::ShallowEqual().
virtual const XMLDeclaration* tinyxml2::XMLNode::ToDeclaration () const inline virtual
Reimplemented in tinyxml2::XMLDeclaration.
Definition at line 686 of file tinyxml2.h.
View newest version in sPHENIX GitHub at line 686 of file tinyxml2.h
virtual XMLDocument* tinyxml2::XMLNode::ToDocument () inline virtual
Safely cast to a Document, or null.
Reimplemented in tinyxml2::XMLDocument.
Definition at line 662 of file tinyxml2.h.
View newest version in sPHENIX GitHub at line 662 of file tinyxml2.h
Referenced by ParseDeep(), and Value().
virtual const XMLDocument* tinyxml2::XMLNode::ToDocument () const inline virtual
Reimplemented in tinyxml2::XMLDocument.
Definition at line 683 of file tinyxml2.h.
View newest version in sPHENIX GitHub at line 683 of file tinyxml2.h
virtual XMLElement* tinyxml2::XMLNode::ToElement () inline virtual
Safely cast to an Element, or null.
Reimplemented in tinyxml2::XMLElement.
Definition at line 650 of file tinyxml2.h.
View newest version in sPHENIX GitHub at line 650 of file tinyxml2.h
Referenced by ParseDeep(), tinyxml2::XMLElement::ShallowEqual(), ToElementWithName(), and tinyxml2::XMLPrinter::VisitEnter().
virtual const XMLElement* tinyxml2::XMLNode::ToElement () const inline virtual
Reimplemented in tinyxml2::XMLElement.
Definition at line 674 of file tinyxml2.h.
View newest version in sPHENIX GitHub at line 674 of file tinyxml2.h
const XMLElement * tinyxml2::XMLNode::ToElementWithName (const char * name) const private
Definition at line 1064 of file tinyxml2.cc.
View newest version in sPHENIX GitHub at line 1064 of file tinyxml2.cc
References fixGDML::element, perf_headwind::name, tinyxml2::XMLElement::Name(), tinyxml2::XMLUtil::StringEqual(), and ToElement().
virtual XMLText* tinyxml2::XMLNode::ToText () inline virtual
Safely cast to Text, or null.
Reimplemented in tinyxml2::XMLText.
Definition at line 654 of file tinyxml2.h.
View newest version in sPHENIX GitHub at line 654 of file tinyxml2.h
Referenced by tinyxml2::XMLElement::GetText(), tinyxml2::XMLElement::QueryBoolText(), tinyxml2::XMLElement::QueryDoubleText(), tinyxml2::XMLElement::QueryFloatText(), tinyxml2::XMLElement::QueryInt64Text(), tinyxml2::XMLElement::QueryIntText(), tinyxml2::XMLElement::QueryUnsignedText(), tinyxml2::XMLElement::SetText(), and tinyxml2::XMLText::ShallowEqual().
virtual const XMLText* tinyxml2::XMLNode::ToText () const inline virtual
Reimplemented in tinyxml2::XMLText.
Definition at line 677 of file tinyxml2.h.
View newest version in sPHENIX GitHub at line 677 of file tinyxml2.h
virtual XMLUnknown* tinyxml2::XMLNode::ToUnknown () inline virtual
Safely cast to an Unknown, or null.
Reimplemented in tinyxml2::XMLUnknown.
Definition at line 670 of file tinyxml2.h.
View newest version in sPHENIX GitHub at line 670 of file tinyxml2.h
Referenced by tinyxml2::XMLUnknown::ShallowEqual().
virtual const XMLUnknown* tinyxml2::XMLNode::ToUnknown () const inline virtual
Reimplemented in tinyxml2::XMLUnknown.
Definition at line 689 of file tinyxml2.h.
View newest version in sPHENIX GitHub at line 689 of file tinyxml2.h
void tinyxml2::XMLNode::Unlink (XMLNode * child) private
Definition at line 773 of file tinyxml2.cc.
View newest version in sPHENIX GitHub at line 773 of file tinyxml2.cc
References _document, _firstChild, _lastChild, _next, _parent, _prev, and TIXMLASSERT.
Referenced by DeleteChild(), InsertChildPreamble(), and ~XMLNode().
const char * tinyxml2::XMLNode::Value () const
The meaning of 'value' changes for the specific type.
Document:       empty (NULL is returned, not an empty string)
Element:        name of the element
Comment:        the comment text
Unknown:        the tag contents
Text:           the text string
Definition at line 744 of file tinyxml2.cc.
View newest version in sPHENIX GitHub at line 744 of file tinyxml2.cc
References _value, tinyxml2::StrPair::GetStr(), and ToDocument().
Referenced by tinyxml2::XMLElement::GetText(), ParseDeep(), tinyxml2::XMLElement::QueryBoolText(), tinyxml2::XMLElement::QueryDoubleText(), tinyxml2::XMLElement::QueryFloatText(), tinyxml2::XMLElement::QueryInt64Text(), tinyxml2::XMLElement::QueryIntText(), tinyxml2::XMLElement::QueryUnsignedText(), tinyxml2::XMLText::ShallowClone(), tinyxml2::XMLComment::ShallowClone(), tinyxml2::XMLDeclaration::ShallowClone(), tinyxml2::XMLUnknown::ShallowClone(), tinyxml2::XMLElement::ShallowClone(), tinyxml2::XMLText::ShallowEqual(), tinyxml2::XMLComment::ShallowEqual(), tinyxml2::XMLDeclaration::ShallowEqual(), tinyxml2::XMLUnknown::ShallowEqual(), and tinyxml2::XMLPrinter::Visit().
Friends And Related Function Documentation
friend class XMLDocument friend
Definition at line 634 of file tinyxml2.h.
View newest version in sPHENIX GitHub at line 634 of file tinyxml2.h
friend class XMLElement friend
Definition at line 635 of file tinyxml2.h.
View newest version in sPHENIX GitHub at line 635 of file tinyxml2.h
Member Data Documentation
XMLDocument* tinyxml2::XMLNode::_document protected
Definition at line 894 of file tinyxml2.h.
View newest version in sPHENIX GitHub at line 894 of file tinyxml2.h
Referenced by tinyxml2::XMLElement::CreateAttribute(), DeleteChild(), tinyxml2::XMLDocument::DeleteNode(), InsertAfterChild(), InsertChildPreamble(), InsertEndChild(), InsertFirstChild(), tinyxml2::XMLElement::ParseAttributes(), ParseDeep(), tinyxml2::XMLText::ParseDeep(), tinyxml2::XMLComment::ParseDeep(), tinyxml2::XMLDeclaration::ParseDeep(), tinyxml2::XMLUnknown::ParseDeep(), tinyxml2::XMLText::ShallowClone(), tinyxml2::XMLComment::ShallowClone(), tinyxml2::XMLDeclaration::ShallowClone(), tinyxml2::XMLUnknown::ShallowClone(), tinyxml2::XMLElement::ShallowClone(), Unlink(), and tinyxml2::XMLDocument::XMLDocument().
XMLNode* tinyxml2::XMLNode::_firstChild protected
Definition at line 898 of file tinyxml2.h.
View newest version in sPHENIX GitHub at line 898 of file tinyxml2.h
Referenced by DeleteChildren(), FirstChildElement(), InsertEndChild(), InsertFirstChild(), and Unlink().
XMLNode* tinyxml2::XMLNode::_lastChild protected
Definition at line 899 of file tinyxml2.h.
View newest version in sPHENIX GitHub at line 899 of file tinyxml2.h
Referenced by DeleteChildren(), InsertEndChild(), InsertFirstChild(), LastChildElement(), and Unlink().
MemPool* tinyxml2::XMLNode::_memPool private
Definition at line 907 of file tinyxml2.h.
View newest version in sPHENIX GitHub at line 907 of file tinyxml2.h
Referenced by DeleteNode(), tinyxml2::XMLDocument::DeleteNode(), tinyxml2::XMLDocument::Identify(), InsertChildPreamble(), and ParseDeep().
XMLNode* tinyxml2::XMLNode::_next protected
Definition at line 902 of file tinyxml2.h.
View newest version in sPHENIX GitHub at line 902 of file tinyxml2.h
Referenced by InsertAfterChild(), InsertEndChild(), InsertFirstChild(), NextSiblingElement(), and Unlink().
XMLNode* tinyxml2::XMLNode::_parent protected
Definition at line 895 of file tinyxml2.h.
View newest version in sPHENIX GitHub at line 895 of file tinyxml2.h
Referenced by DeleteChild(), tinyxml2::XMLDocument::DeleteNode(), InsertAfterChild(), InsertChildPreamble(), InsertEndChild(), InsertFirstChild(), Unlink(), and ~XMLNode().
XMLNode* tinyxml2::XMLNode::_prev protected
Definition at line 901 of file tinyxml2.h.
View newest version in sPHENIX GitHub at line 901 of file tinyxml2.h
Referenced by InsertAfterChild(), InsertEndChild(), InsertFirstChild(), PreviousSiblingElement(), and Unlink().
void* tinyxml2::XMLNode::_userData protected
Definition at line 904 of file tinyxml2.h.
View newest version in sPHENIX GitHub at line 904 of file tinyxml2.h
StrPair tinyxml2::XMLNode::_value mutable protected
Definition at line 896 of file tinyxml2.h.
View newest version in sPHENIX GitHub at line 896 of file tinyxml2.h
Referenced by ParseDeep(), tinyxml2::XMLText::ParseDeep(), tinyxml2::XMLComment::ParseDeep(), tinyxml2::XMLDeclaration::ParseDeep(), tinyxml2::XMLUnknown::ParseDeep(), tinyxml2::XMLElement::ParseDeep(), SetValue(), and Value().
The documentation for this class was generated from the following files:
JETSCAPE/blob/main/external_packages/tinyxml2.h
JETSCAPE/blob/main/external_packages/tinyxml2.cc