Analysis Software: Acts::MeasurementSelector Class Reference
Acts::MeasurementSelector Class Reference
Measurement selection struct selecting those measurements compatible with the given track parameter against provided criteria on one surface.
#include <acts/blob/sPHENIX/Core/include/Acts/TrackFinding/MeasurementSelector.hpp>
Public Types
using Config = Acts::GeometryHierarchyMap< MeasurementSelectorCuts >
Public Member Functions
MeasurementSelector ()=default
Default constructor.
MeasurementSelector (Config config)
Constructor with config and (non-owning) logger.
template<typename traj_t >
Result< std::pair< typename
std::vector< typename
traj_t::TrackStateProxy >
::iterator, typename
std::vector< typename
traj_t::TrackStateProxy >
::iterator > > select (std::vector< typename traj_t::TrackStateProxy > &candidates, bool &isOutlier, const Logger &logger) const
Function that select the measurements compatible with the given track parameter on a surface.
Private Member Functions
double calculateChi2 (double *fullCalibrated, double *fullCalibratedCovariance, TrackStateTraits< MultiTrajectoryTraits::MeasurementSizeMax, false >::Parameters predicted, TrackStateTraits< MultiTrajectoryTraits::MeasurementSizeMax, false >::Covariance predictedCovariance, TrackStateTraits< MultiTrajectoryTraits::MeasurementSizeMax, false >::Projector projector, unsigned int calibratedSize) const
Static Private Member Functions
template<typename traj_t , typename cut_value_t >
static cut_value_t VariableCut (const typename traj_t::TrackStateProxy &trackState, const Acts::MeasurementSelector::Config::Iterator selector, const std::vector< cut_value_t > &cuts, const Logger &logger)
Private Attributes
Config m_config
Detailed Description
Measurement selection struct selecting those measurements compatible with the given track parameter against provided criteria on one surface.
The selection criteria could be allowed maximum chi2 and allowed maximum number of measurements on one surface
If there is no compatible measurement, the measurement with the minimum chi2 will be selected and the status will be tagged as an outlier
Definition at line 54 of file MeasurementSelector.hpp.
View newest version in sPHENIX GitHub at line 54 of file MeasurementSelector.hpp
Member Typedef Documentation
using Acts::MeasurementSelector::Config = Acts::GeometryHierarchyMap<MeasurementSelectorCuts>
Geometry-dependent cut configuration.
Different components on the geometry can require different cut settings. The configuration must either contain explicit settings for all geometry components that are used or contain a global default.
Definition at line 61 of file MeasurementSelector.hpp.
View newest version in sPHENIX GitHub at line 61 of file MeasurementSelector.hpp
Constructor & Destructor Documentation
Acts::MeasurementSelector::MeasurementSelector () default
Default constructor.
Acts::MeasurementSelector::MeasurementSelector (Config config) inline
Constructor with config and (non-owning) logger.
Parameters
config a config instance
Definition at line 68 of file MeasurementSelector.hpp.
View newest version in sPHENIX GitHub at line 68 of file MeasurementSelector.hpp
Member Function Documentation
double Acts::MeasurementSelector::calculateChi2 (double * fullCalibrated, double * fullCalibratedCovariance, TrackStateTraits< MultiTrajectoryTraits::MeasurementSizeMax, false >::Parameters predicted, TrackStateTraits< MultiTrajectoryTraits::MeasurementSizeMax, false >::Covariance predictedCovariance, TrackStateTraits< MultiTrajectoryTraits::MeasurementSizeMax, false >::Projector projector, unsigned int calibratedSize) const private
Definition at line 18 of file MeasurementSelector.cpp.
View newest version in sPHENIX GitHub at line 18 of file MeasurementSelector.cpp
References H, N, value, and Acts::visit_measurement().
Referenced by select().
template<typename traj_t > Result<std::pair< typename std::vector<typename traj_t::TrackStateProxy>::iterator, typename std::vector<typename traj_t::TrackStateProxy>::iterator> > Acts::MeasurementSelector::select (std::vector< typename traj_t::TrackStateProxy > & candidates, bool & isOutlier, const Logger & logger) const inline
Function that select the measurements compatible with the given track parameter on a surface.
Parameters
candidates The track state candidates which already contain predicted parameters
isOutlier The indicator for outlier or not
logger The logger wrapper
Returns
Pair of iterators into candidates marking the range of selected candidates
Definition at line 84 of file MeasurementSelector.hpp.
View newest version in sPHENIX GitHub at line 84 of file MeasurementSelector.hpp
References Acts::ACTS_VERBOSE(), assert, calculateChi2(), cuts, configureMap::data, distance(), Acts::GeometryHierarchyMap< value_t >::end(), Acts::GeometryHierarchyMap< value_t >::find(), logger(), m_config, Acts::MultiTrajectoryTraits::MeasurementSizeMax, next, Acts::Experimental::detail::BlueprintHelper::sort(), writeMapConfig::surface, and swap().
template<typename traj_t , typename cut_value_t > static cut_value_t Acts::MeasurementSelector::VariableCut (const typename traj_t::TrackStateProxy & trackState, const Acts::MeasurementSelector::Config::Iterator selector, const std::vector< cut_value_t > & cuts, const Logger & logger) inline static private
Definition at line 210 of file MeasurementSelector.hpp.
View newest version in sPHENIX GitHub at line 210 of file MeasurementSelector.hpp
References Acts::ACTS_VERBOSE(), Acts::eBoundTheta, and eta.
Member Data Documentation
Config Acts::MeasurementSelector::m_config private
Definition at line 244 of file MeasurementSelector.hpp.
View newest version in sPHENIX GitHub at line 244 of file MeasurementSelector.hpp
Referenced by select().
The documentation for this class was generated from the following files:
acts/blob/sPHENIX/Core/include/Acts/TrackFinding/MeasurementSelector.hpp
acts/blob/sPHENIX/Core/src/TrackFinding/MeasurementSelector.cpp