Analysis Software: tinyxml2::StrPair Class Reference
tinyxml2::StrPair Class Reference
#include <JETSCAPE/blob/main/external_packages/tinyxml2.h>
Public Types
enum {
NEEDS_ENTITY_PROCESSING = 0x01, NEEDS_NEWLINE_NORMALIZATION = 0x02, NEEDS_WHITESPACE_COLLAPSING = 0x04, TEXT_ELEMENT = NEEDS_ENTITY_PROCESSING | NEEDS_NEWLINE_NORMALIZATION,
TEXT_ELEMENT_LEAVE_ENTITIES = NEEDS_NEWLINE_NORMALIZATION, ATTRIBUTE_NAME = 0, ATTRIBUTE_VALUE = NEEDS_ENTITY_PROCESSING | NEEDS_NEWLINE_NORMALIZATION, ATTRIBUTE_VALUE_LEAVE_ENTITIES = NEEDS_NEWLINE_NORMALIZATION,
COMMENT = NEEDS_NEWLINE_NORMALIZATION
}
Public Member Functions
StrPair ()
~StrPair ()
void Set (char *start, char *end, int flags)
const char * GetStr ()
bool Empty () const
void SetInternedStr (const char *str)
void SetStr (const char *str, int flags=0)
char * ParseText (char *in, const char *endTag, int strFlags)
char * ParseName (char *in)
void TransferTo (StrPair *other)
void Reset ()
Private Types
enum { NEEDS_FLUSH = 0x100, NEEDS_DELETE = 0x200 }
Private Member Functions
void CollapseWhitespace ()
StrPair (const StrPair &other)
void operator= (StrPair &other)
Private Attributes
int _flags
char * _start
char * _end
Detailed Description
Definition at line 122 of file tinyxml2.h.
View newest version in sPHENIX GitHub at line 122 of file tinyxml2.h
Member Enumeration Documentation
anonymous enum
Enumerator:
NEEDS_ENTITY_PROCESSING
NEEDS_NEWLINE_NORMALIZATION
NEEDS_WHITESPACE_COLLAPSING
TEXT_ELEMENT
TEXT_ELEMENT_LEAVE_ENTITIES
ATTRIBUTE_NAME
ATTRIBUTE_VALUE
ATTRIBUTE_VALUE_LEAVE_ENTITIES
COMMENT
Definition at line 125 of file tinyxml2.h.
View newest version in sPHENIX GitHub at line 125 of file tinyxml2.h
anonymous enum private
Enumerator:
NEEDS_FLUSH
NEEDS_DELETE
Definition at line 172 of file tinyxml2.h.
View newest version in sPHENIX GitHub at line 172 of file tinyxml2.h
Constructor & Destructor Documentation
tinyxml2::StrPair::StrPair () inline
Definition at line 138 of file tinyxml2.h.
View newest version in sPHENIX GitHub at line 138 of file tinyxml2.h
tinyxml2::StrPair::~StrPair ()
Definition at line 138 of file tinyxml2.cc.
View newest version in sPHENIX GitHub at line 138 of file tinyxml2.cc
References Reset().
tinyxml2::StrPair::StrPair (const StrPair & other) private
Member Function Documentation
void tinyxml2::StrPair::CollapseWhitespace () private
Definition at line 234 of file tinyxml2.cc.
View newest version in sPHENIX GitHub at line 234 of file tinyxml2.cc
References _flags, _start, tinyxml2::XMLUtil::IsWhiteSpace(), NEEDS_DELETE, merge_hashes::p, tinyxml2::XMLUtil::SkipWhiteSpace(), and TIXMLASSERT.
Referenced by GetStr().
bool tinyxml2::StrPair::Empty () const inline
Definition at line 152 of file tinyxml2.h.
View newest version in sPHENIX GitHub at line 152 of file tinyxml2.h
References _end, and _start.
Referenced by tinyxml2::XMLNode::ParseDeep(), tinyxml2::XMLElement::ParseDeep(), and tinyxml2::XMLDocument::PrintError().
const char * tinyxml2::StrPair::GetStr ()
Definition at line 263 of file tinyxml2.cc.
View newest version in sPHENIX GitHub at line 263 of file tinyxml2.cc
References _end, _flags, _start, CollapseWhitespace(), tinyxml2::entities, tinyxml2::XMLUtil::GetCharacterRef(), i, tinyxml2::Entity::length, LF, NEEDS_DELETE, NEEDS_ENTITY_PROCESSING, NEEDS_FLUSH, NEEDS_NEWLINE_NORMALIZATION, NEEDS_WHITESPACE_COLLAPSING, tinyxml2::NUM_ENTITIES, merge_hashes::p, tinyxml2::Entity::pattern, TIXMLASSERT, and tinyxml2::Entity::value.
Referenced by tinyxml2::XMLAttribute::Name(), tinyxml2::XMLNode::ParseDeep(), tinyxml2::XMLDocument::PrintError(), tinyxml2::XMLNode::Value(), and tinyxml2::XMLAttribute::Value().
void tinyxml2::StrPair::operator= (StrPair & other) private
char * tinyxml2::StrPair::ParseName (char * in)
Definition at line 214 of file tinyxml2.cc.
View newest version in sPHENIX GitHub at line 214 of file tinyxml2.cc
References tinyxml2::XMLUtil::IsNameChar(), tinyxml2::XMLUtil::IsNameStartChar(), merge_hashes::p, Set(), and start.
Referenced by tinyxml2::XMLAttribute::ParseDeep(), and tinyxml2::XMLElement::ParseDeep().
char * tinyxml2::StrPair::ParseText (char * in, const char * endTag, int strFlags)
Definition at line 192 of file tinyxml2.cc.
View newest version in sPHENIX GitHub at line 192 of file tinyxml2.cc
References G4PLUGDOOR::length, merge_hashes::p, Set(), start, and TIXMLASSERT.
Referenced by tinyxml2::XMLText::ParseDeep(), tinyxml2::XMLComment::ParseDeep(), tinyxml2::XMLDeclaration::ParseDeep(), tinyxml2::XMLUnknown::ParseDeep(), and tinyxml2::XMLAttribute::ParseDeep().
void tinyxml2::StrPair::Reset ()
Definition at line 168 of file tinyxml2.cc.
View newest version in sPHENIX GitHub at line 168 of file tinyxml2.cc
References _end, _flags, _start, and NEEDS_DELETE.
Referenced by Set(), tinyxml2::XMLDocument::SetError(), SetInternedStr(), SetStr(), TransferTo(), and ~StrPair().
void tinyxml2::StrPair::Set (char * start, char * end, int flags) inline
Definition at line 141 of file tinyxml2.h.
View newest version in sPHENIX GitHub at line 141 of file tinyxml2.h
References _end, _flags, _start, end, NEEDS_FLUSH, Reset(), start, and TIXMLASSERT.
Referenced by ParseName(), and ParseText().
void tinyxml2::StrPair::SetInternedStr (const char * str) inline
Definition at line 156 of file tinyxml2.h.
View newest version in sPHENIX GitHub at line 156 of file tinyxml2.h
References _start, Reset(), and str.
Referenced by tinyxml2::XMLNode::SetValue().
void tinyxml2::StrPair::SetStr (const char * str, int flags = 0)
Definition at line 179 of file tinyxml2.cc.
View newest version in sPHENIX GitHub at line 179 of file tinyxml2.cc
References _end, _flags, _start, NEEDS_DELETE, Reset(), and TIXMLASSERT.
Referenced by tinyxml2::XMLAttribute::SetAttribute(), tinyxml2::XMLDocument::SetError(), tinyxml2::XMLAttribute::SetName(), and tinyxml2::XMLNode::SetValue().
void tinyxml2::StrPair::TransferTo (StrPair * other)
Definition at line 144 of file tinyxml2.cc.
View newest version in sPHENIX GitHub at line 144 of file tinyxml2.cc
References _end, _flags, _start, Reset(), and TIXMLASSERT.
Referenced by tinyxml2::XMLNode::ParseDeep().
Member Data Documentation
char* tinyxml2::StrPair::_end private
Definition at line 179 of file tinyxml2.h.
View newest version in sPHENIX GitHub at line 179 of file tinyxml2.h
Referenced by Empty(), GetStr(), Reset(), Set(), SetStr(), and TransferTo().
int tinyxml2::StrPair::_flags private
Definition at line 177 of file tinyxml2.h.
View newest version in sPHENIX GitHub at line 177 of file tinyxml2.h
Referenced by CollapseWhitespace(), GetStr(), Reset(), Set(), SetStr(), and TransferTo().
char* tinyxml2::StrPair::_start private
Definition at line 178 of file tinyxml2.h.
View newest version in sPHENIX GitHub at line 178 of file tinyxml2.h
Referenced by CollapseWhitespace(), Empty(), GetStr(), Reset(), Set(), SetInternedStr(), SetStr(), and TransferTo().
The documentation for this class was generated from the following files:
JETSCAPE/blob/main/external_packages/tinyxml2.h
JETSCAPE/blob/main/external_packages/tinyxml2.cc