Analysis Software: MBDStudy Class Reference
MBDStudy Class Reference
#include <analysis/blob/master/BBCStudy/Mwibanda/MBDStudy.h>
Public Member Functions
MBDStudy (const std::string &name="MBDStudy")
int Init (PHCompositeNode *)
int InitRun (PHCompositeNode *)
int process_event (PHCompositeNode *)
int End (PHCompositeNode *)
Called at the end of all processing.
void set_savefile (const char *f)
void set_tres (const Float_t tr)
Public Member Functions inherited from SubsysReco
~SubsysReco () override
virtual int EndRun (const int)
Called at the end of each run.
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
void Print (const std::string &="ALL") const override
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Private Member Functions
void CheckDST (PHCompositeNode *topNode)
void GetNodes (PHCompositeNode *)
Private Attributes
std::string _savefname
TFile * _savefile
int nprocessed {0}
TTree * _tree
Int_t f_evt
Float_t f_bimp
Int_t f_ncoll
Int_t f_npart
Float_t f_vx
Float_t f_vy
Float_t f_vz
Float_t f_vt
Short_t f_mbdn [2]
Float_t f_mbdq [2]
Float_t f_mbdt [2]
Float_t f_mbdte [2]
Float_t f_mbdz
Float_t f_mbdt0
TH1 * h_mbdq [128]
TH1 * h_mbdqtot [2]
TH2 * h2_mbdqtot
TH1 * h_ztrue
TH1 * h_tdiff
TH2 * h2_tdiff_ch
TCanvas * c_mbdt
TH1 * hevt_mbdt [2]
TF1 * gaussian
std::map< int, int > _pids
TDatabasePDG * _pdg
TRandom3 * _rndm
Float_t _tres
PHG4TruthInfoContainer * _truth_container
PHG4HitContainer * _mbdhits
EventHeader * _evtheader
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = std::numeric_limits<int>::max() - 10
}
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Detailed Description
Definition at line 26 of file MBDStudy.h.
View newest version in sPHENIX GitHub at line 26 of file MBDStudy.h
Constructor & Destructor Documentation
MBDStudy::MBDStudy (const std::string & name = "MBDStudy")
Definition at line 111 of file MBDStudy.cc.
View newest version in sPHENIX GitHub at line 111 of file MBDStudy.cc
Member Function Documentation
void MBDStudy::CheckDST (PHCompositeNode * topNode) private
Definition at line 586 of file MBDStudy.cc.
View newest version in sPHENIX GitHub at line 586 of file MBDStudy.cc
References f_evt, f_mbdq, f_mbdz, MbdOut::get_q(), MbdOut::get_zvtx(), and PHWHERE.
int MBDStudy::End (PHCompositeNode *) virtual
Called at the end of all processing.
Reimplemented from SubsysReco.
Definition at line 562 of file MBDStudy.cc.
View newest version in sPHENIX GitHub at line 562 of file MBDStudy.cc
References _pids, _savefile, npart(), and train_ambiguity_solver::pid.
void MBDStudy::GetNodes (PHCompositeNode * topNode) private
Definition at line 544 of file MBDStudy.cc.
View newest version in sPHENIX GitHub at line 544 of file MBDStudy.cc
References _evtheader, _mbdhits, _truth_container, f_evt, and PHWHERE.
Referenced by InitRun().
int MBDStudy::Init (PHCompositeNode *) virtual
Called during initialization. Typically this is where you can book histograms, and e.g. register them to Fun4AllServer (so they can be output to file using Fun4AllServer::dumpHistos() method).
Reimplemented from SubsysReco.
Definition at line 124 of file MBDStudy.cc.
View newest version in sPHENIX GitHub at line 124 of file MBDStudy.cc
References _pdg, _rndm, _savefile, _savefname, _tree, c_mbdt, f_bimp, f_evt, f_mbdn, f_mbdq, f_mbdt, f_mbdt0, f_mbdte, f_mbdz, f_ncoll, f_npart, f_vx, f_vy, f_vz, gaussian, h2_mbdqtot, h2_tdiff_ch, h_mbdq, h_mbdqtot, h_tdiff, h_ztrue, hevt_mbdt, perf_headwind::name, PHWHERE, and title.
int MBDStudy::InitRun (PHCompositeNode *) virtual
Called for first event when run number is known. Typically this is where you may want to fetch data from database, because you know the run number.
Reimplemented from SubsysReco.
Definition at line 195 of file MBDStudy.cc.
View newest version in sPHENIX GitHub at line 195 of file MBDStudy.cc
References GetNodes().
int MBDStudy::process_event (PHCompositeNode *) virtual
Called for each event. This is where you do the real work.
Reimplemented from SubsysReco.
Definition at line 204 of file MBDStudy.cc.
View newest version in sPHENIX GitHub at line 204 of file MBDStudy.cc
References _evtheader, _mbdhits, _pdg, _pids, _rndm, _tree, _tres, _truth_container, parse_cmake_options::begin, C, c_mbdt, charge(), end, f_bimp, f_evt, f_mbdn, f_mbdq, f_mbdt, f_mbdt0, f_mbdte, f_mbdz, f_ncoll, f_npart, f_vt, f_vx, f_vy, f_vz, gaussian, PHG4Particle::get_e(), PHG4Hit::get_edep(), EventHeader::get_EvtSequence(), EventHeader::get_ImpactParameter(), PHG4Particle::get_IonCharge(), PHG4Hit::get_layer(), EventHeader::get_ncoll(), EventHeader::get_npart(), PHG4Hit::get_path_length(), PHG4Particle::get_pid(), PHG4Particle::get_px(), PHG4Particle::get_py(), PHG4Particle::get_pz(), PHG4VtxPoint::get_t(), PHG4Hit::get_t(), PHG4Particle::get_track_id(), PHG4Hit::get_trkid(), PHG4VtxPoint::get_x(), PHG4Hit::get_x(), PHG4VtxPoint::get_y(), PHG4Hit::get_y(), PHG4VtxPoint::get_z(), PHG4Hit::get_z(), PHG4HitContainer::getHits(), PHG4TruthInfoContainer::GetNumVertices(), PHG4TruthInfoContainer::GetParticle(), PHG4TruthInfoContainer::GetPrimaryVertexIndex(), PHG4TruthInfoContainer::GetPrimaryVtx(), PHG4TruthInfoContainer::GetVtxRange(), h2_mbdqtot, h2_tdiff_ch, h_mbdq, h_mbdqtot, h_tdiff, h_ztrue, hevt_mbdt, PHG4Particle::isIon(), perf_headwind::name, nprocessed, PHWHERE, train_ambiguity_solver::pid, Acts::Experimental::detail::BlueprintHelper::sort(), TubeLoc, v4, and v_ckov.
void MBDStudy::set_savefile (const char * f) inline
Definition at line 46 of file MBDStudy.h.
View newest version in sPHENIX GitHub at line 46 of file MBDStudy.h
References _savefname, and f.
void MBDStudy::set_tres (const Float_t tr) inline
Definition at line 48 of file MBDStudy.h.
View newest version in sPHENIX GitHub at line 48 of file MBDStudy.h
References _tres.
Member Data Documentation
EventHeader* MBDStudy::_evtheader private
Definition at line 102 of file MBDStudy.h.
View newest version in sPHENIX GitHub at line 102 of file MBDStudy.h
Referenced by GetNodes(), and process_event().
PHG4HitContainer* MBDStudy::_mbdhits private
Definition at line 101 of file MBDStudy.h.
View newest version in sPHENIX GitHub at line 101 of file MBDStudy.h
Referenced by GetNodes(), and process_event().
TDatabasePDG* MBDStudy::_pdg private
Definition at line 92 of file MBDStudy.h.
View newest version in sPHENIX GitHub at line 92 of file MBDStudy.h
Referenced by Init(), and process_event().
std::map<int,int> MBDStudy::_pids private
Definition at line 89 of file MBDStudy.h.
View newest version in sPHENIX GitHub at line 89 of file MBDStudy.h
Referenced by End(), and process_event().
TRandom3* MBDStudy::_rndm private
Definition at line 93 of file MBDStudy.h.
View newest version in sPHENIX GitHub at line 93 of file MBDStudy.h
Referenced by Init(), and process_event().
TFile* MBDStudy::_savefile private
Definition at line 57 of file MBDStudy.h.
View newest version in sPHENIX GitHub at line 57 of file MBDStudy.h
Referenced by End(), and Init().
std::string MBDStudy::_savefname private
Definition at line 56 of file MBDStudy.h.
View newest version in sPHENIX GitHub at line 56 of file MBDStudy.h
Referenced by Init(), and set_savefile().
TTree* MBDStudy::_tree private
Definition at line 62 of file MBDStudy.h.
View newest version in sPHENIX GitHub at line 62 of file MBDStudy.h
Referenced by Init(), and process_event().
Float_t MBDStudy::_tres private
Definition at line 94 of file MBDStudy.h.
View newest version in sPHENIX GitHub at line 94 of file MBDStudy.h
Referenced by process_event(), and set_tres().
PHG4TruthInfoContainer* MBDStudy::_truth_container private
Definition at line 100 of file MBDStudy.h.
View newest version in sPHENIX GitHub at line 100 of file MBDStudy.h
Referenced by GetNodes(), and process_event().
TCanvas* MBDStudy::c_mbdt private
Definition at line 85 of file MBDStudy.h.
View newest version in sPHENIX GitHub at line 85 of file MBDStudy.h
Referenced by Init(), and process_event().
Float_t MBDStudy::f_bimp private
Definition at line 64 of file MBDStudy.h.
View newest version in sPHENIX GitHub at line 64 of file MBDStudy.h
Referenced by Init(), and process_event().
Int_t MBDStudy::f_evt private
Definition at line 63 of file MBDStudy.h.
View newest version in sPHENIX GitHub at line 63 of file MBDStudy.h
Referenced by CheckDST(), GetNodes(), Init(), and process_event().
Short_t MBDStudy::f_mbdn[2] private
Definition at line 71 of file MBDStudy.h.
View newest version in sPHENIX GitHub at line 71 of file MBDStudy.h
Referenced by Init(), and process_event().
Float_t MBDStudy::f_mbdq[2] private
Definition at line 72 of file MBDStudy.h.
View newest version in sPHENIX GitHub at line 72 of file MBDStudy.h
Referenced by CheckDST(), Init(), and process_event().
Float_t MBDStudy::f_mbdt[2] private
Definition at line 73 of file MBDStudy.h.
View newest version in sPHENIX GitHub at line 73 of file MBDStudy.h
Referenced by Init(), and process_event().
Float_t MBDStudy::f_mbdt0 private
Definition at line 76 of file MBDStudy.h.
View newest version in sPHENIX GitHub at line 76 of file MBDStudy.h
Referenced by Init(), and process_event().
Float_t MBDStudy::f_mbdte[2] private
Definition at line 74 of file MBDStudy.h.
View newest version in sPHENIX GitHub at line 74 of file MBDStudy.h
Referenced by Init(), and process_event().
Float_t MBDStudy::f_mbdz private
Definition at line 75 of file MBDStudy.h.
View newest version in sPHENIX GitHub at line 75 of file MBDStudy.h
Referenced by CheckDST(), Init(), and process_event().
Int_t MBDStudy::f_ncoll private
Definition at line 65 of file MBDStudy.h.
View newest version in sPHENIX GitHub at line 65 of file MBDStudy.h
Referenced by Init(), and process_event().
Int_t MBDStudy::f_npart private
Definition at line 66 of file MBDStudy.h.
View newest version in sPHENIX GitHub at line 66 of file MBDStudy.h
Referenced by Init(), and process_event().
Float_t MBDStudy::f_vt private
Definition at line 70 of file MBDStudy.h.
View newest version in sPHENIX GitHub at line 70 of file MBDStudy.h
Referenced by process_event().
Float_t MBDStudy::f_vx private
Definition at line 67 of file MBDStudy.h.
View newest version in sPHENIX GitHub at line 67 of file MBDStudy.h
Referenced by Init(), and process_event().
Float_t MBDStudy::f_vy private
Definition at line 68 of file MBDStudy.h.
View newest version in sPHENIX GitHub at line 68 of file MBDStudy.h
Referenced by Init(), and process_event().
Float_t MBDStudy::f_vz private
Definition at line 69 of file MBDStudy.h.
View newest version in sPHENIX GitHub at line 69 of file MBDStudy.h
Referenced by Init(), and process_event().
TF1* MBDStudy::gaussian private
Definition at line 87 of file MBDStudy.h.
View newest version in sPHENIX GitHub at line 87 of file MBDStudy.h
Referenced by Init(), and process_event().
TH2* MBDStudy::h2_mbdqtot private
Definition at line 80 of file MBDStudy.h.
View newest version in sPHENIX GitHub at line 80 of file MBDStudy.h
Referenced by Init(), and process_event().
TH2* MBDStudy::h2_tdiff_ch private
Definition at line 83 of file MBDStudy.h.
View newest version in sPHENIX GitHub at line 83 of file MBDStudy.h
Referenced by Init(), and process_event().
TH1* MBDStudy::h_mbdq[128] private
Definition at line 78 of file MBDStudy.h.
View newest version in sPHENIX GitHub at line 78 of file MBDStudy.h
Referenced by Init(), and process_event().
TH1* MBDStudy::h_mbdqtot[2] private
Definition at line 79 of file MBDStudy.h.
View newest version in sPHENIX GitHub at line 79 of file MBDStudy.h
Referenced by Init(), and process_event().
TH1* MBDStudy::h_tdiff private
Definition at line 82 of file MBDStudy.h.
View newest version in sPHENIX GitHub at line 82 of file MBDStudy.h
Referenced by Init(), and process_event().
TH1* MBDStudy::h_ztrue private
Definition at line 81 of file MBDStudy.h.
View newest version in sPHENIX GitHub at line 81 of file MBDStudy.h
Referenced by Init(), and process_event().
TH1* MBDStudy::hevt_mbdt[2] private
Definition at line 86 of file MBDStudy.h.
View newest version in sPHENIX GitHub at line 86 of file MBDStudy.h
Referenced by Init(), and process_event().
int MBDStudy::nprocessed {0} private
Definition at line 59 of file MBDStudy.h.
View newest version in sPHENIX GitHub at line 59 of file MBDStudy.h
Referenced by process_event().
The documentation for this class was generated from the following files:
analysis/blob/master/BBCStudy/Mwibanda/MBDStudy.h
analysis/blob/master/BBCStudy/Mwibanda/MBDStudy.cc