Analysis Software: analysis/blob/master/HF-Jet/TruthGeneration/projections/200pp_pythia8_CTEQ6L_7GeV_ALL.cfg_eneg_DSTReader.root_Draw_HFJetTruth_CrossSection2RAA.C File Reference
200pp_pythia8_CTEQ6L_7GeV_ALL.cfg_eneg_DSTReader.root_Draw_HFJetTruth_CrossSection2RAA.C File Reference
Functions
gStyle SetOptFit (1)
gStyle SetOptStat (0)
gStyle SetOptTitle (0)
Draw_HFJetTruth_CrossSection2RAA Range (0, 0, 1, 1)
Draw_HFJetTruth_CrossSection2RAA SetFillColor (0)
Draw_HFJetTruth_CrossSection2RAA SetBorderMode (0)
Draw_HFJetTruth_CrossSection2RAA SetBorderSize (2)
Draw_HFJetTruth_CrossSection2RAA SetTickx (1)
Draw_HFJetTruth_CrossSection2RAA SetTicky (1)
Draw_HFJetTruth_CrossSection2RAA SetLeftMargin (0.16)
Draw_HFJetTruth_CrossSection2RAA SetRightMargin (0.05)
Draw_HFJetTruth_CrossSection2RAA SetTopMargin (0.05)
Draw_HFJetTruth_CrossSection2RAA SetBottomMargin (0.16)
Draw_HFJetTruth_CrossSection2RAA SetFrameBorderMode (0)
Draw_HFJetTruth_CrossSection2RAA_1 Draw ()
Draw_HFJetTruth_CrossSection2RAA_1 cd ()
Draw_HFJetTruth_CrossSection2RAA_1 Range (7.911393,-0.243038, 52.21519, 1.275949)
hframe__2 SetMinimum (0)
hframe__2 SetMaximum (1.2)
hframe__2 SetDirectory (0)
hframe__2 SetStats (0)
hframe__2 SetLineWidth (2)
hframe__2 SetMarkerStyle (20)
hframe__2 SetMarkerSize (1.2)
hframe__2 GetXaxis () -> SetTitle("Transverse Momentum [GeV/#it
hframe__2 GetYaxis () -> SetTitle("#it
Au Au entry SetLineColor (1)
entry SetLineStyle (1)
entry SetLineWidth (1)
entry SetMarkerColor (1)
entry SetMarkerStyle (21)
entry SetMarkerSize (1)
entry SetTextFont (42)
Draw_HFJetTruth_CrossSection2RAA_1 Modified ()
Draw_HFJetTruth_CrossSection2RAA SetSelected (Draw_HFJetTruth_CrossSection2RAA)
Variables
TPad * Draw_HFJetTruth_CrossSection2RAA_1 = new TPad("Draw_HFJetTruth_CrossSection2RAA_1", "Draw_HFJetTruth_CrossSection2RAA_1",0.01,0.01,0.99,0.99)
TH1F * hframe__2 = new TH1F("hframe__2","",1000,15,50)
_
Au Au C
entry =leg->AddEntry("NULL","PYTHIA-8 #it{b}-jet, Anti-k_{T} R=0.4, |#eta|<0.7, CTEQ6L","")
Function Documentation
Draw_HFJetTruth_InvMass_CrossSection2RAARatio_Theory_deta0 cd ()
Referenced by analyzeClusterEtIso(), CalculateSigmaDca(), CheckDeltaPtWithBoundaryMasks(), SDeltaPtCutStudy::CloseFiles(), STrackMatcherComparator::CloseInput(), SColdQcdCorrelatorAnalysis::SBaseQAPlugin< SCheckTrackPairsConfig >::CloseOutput(), STrackMatcherComparator::CloseOutput(), SColdQcdCorrelatorAnalysis::SEnergyCorrelator::CloseOutputFile(), CompareOldVsNewPlots(), STrackCutStudy::ConstructPlots(), tower::display(), stack::displayEvent(), stack::displayStackSummary(), hcal::displaySummary(), stack::displayTowerSummary(), DoPercentDifference(), draw_hists_3D(), drawCanvas_invMass(), drawCorr(), DrawCutLabel(), PktSizeMonDraw::DrawFirst(), CemcMonDraw::DrawSecond(), ElectronID::End(), mbdAnalysis::End(), hijbkg_upc::End(), isoCluster::End(), quickHIJING::End(), singlePhotonClusterAna::End(), pi0ClusterAna::End(), caloTreeGen::End(), AnaMvtxTestBeam2019::End(), pythiaEMCalAna::End(), hcal_towerid::End(), pi0Efficiency::End(), FullJetFinder::End(), cemcReco::End(), STrackCutStudy::End(), SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::End(), towerid::FillHistograms(), SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::InitHists(), SColdQcdCorrelatorAnalysis::SBaseQAPlugin< SCheckTrackPairsConfig >::InitOutput(), Jet_reso_Iso(), MakeNewMatcherPlots(), MakeNewMatcherTuplePlots(), MakeOldEvaluatorPlots(), SDeltaPtCutStudy::MakePlots(), MakePrettyPlot(), MakeRatioComparisonPlot(), STrackMatcherComparator::MakeRatiosAndPlots(), mg_parse_multipart(), numericInverse(), plot(), pygrvd(), pygrvl(), pygrvm(), QuickDeltaPtExtractor(), QuickTreePlotter(), QuickTuplePlotter(), QuickWeirdTuplePlotter(), ActsExamples::CsvMeasurementReader::read(), tileHelper::runtilesummary::runtilesummary(), SColdQcdCorrelatorAnalysis::SLambdaJetHunter::SaveAndCloseOutput(), STrackMatcherComparator::SaveHistograms(), STrackCutStudy::SaveHists(), SColdQcdCorrelatorAnalysis::SCheckTrackPairs::SaveOutput(), SDeltaPtCutStudy::SaveOutput(), SColdQcdCorrelatorAnalysis::SEnergyCorrelator::SaveOutput(), SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::SaveOutput(), sccalib(), sipmCalib(), spmcalib(), and tileHelper::tilePattern().
Draw_HFJetTruth_CrossSection2RAA_1 Draw ()
hframe__2 GetXaxis () -> SetTitle("Transverse Momentum [GeV/#it
Definition at line 45 of file 200pp_pythia8_CTEQ6L_7GeV_ALL.cfg_eneg_DSTReader.root_Draw_HFJetTruth_CrossSection2RAA.C.
View newest version in sPHENIX GitHub at line 45 of file 200pp_pythia8_CTEQ6L_7GeV_ALL.cfg_eneg_DSTReader.root_Draw_HFJetTruth_CrossSection2RAA.C
hframe__2 GetYaxis () -> SetTitle("#it
Definition at line 51 of file 200pp_pythia8_CTEQ6L_7GeV_ALL.cfg_eneg_DSTReader.root_Draw_HFJetTruth_CrossSection2RAA.C.
View newest version in sPHENIX GitHub at line 51 of file 200pp_pythia8_CTEQ6L_7GeV_ALL.cfg_eneg_DSTReader.root_Draw_HFJetTruth_CrossSection2RAA.C
Draw_HFJetTruth_InvMass_CrossSection2RAARatio_Theory_deta0 Modified ()
Referenced by OM().
Draw_HFJetTruth_CrossSection2RAA Range (0 , 0 , 1 , 1)
Referenced by draw_hists_3D(), and RunTowerInfo::process_event().
Draw_HFJetTruth_CrossSection2RAA_1 Range (7. 911393, -0. 243038, 52. 21519, 1. 275949)
Draw_HFJetTruth_InvMass_CrossSection2RAARatio_Theory_deta0 SetBorderMode (0)
Referenced by CalculateSigmaDca(), CompareOldVsNewPlots(), STrackCutStudy::ConstructPlots(), DoPercentDifference(), SDeltaPtCutStudy::MakePlots(), MakePrettyPlot(), MakeRatioComparisonPlot(), STrackMatcherComparator::MakeRatiosAndPlots(), and QuickDeltaPtExtractor().
Draw_HFJetTruth_InvMass_CrossSection2RAARatio_Theory_deta0 SetBorderSize (2)
Referenced by analyzeClusterEtIso(), CalculateSigmaDca(), CompareOldVsNewPlots(), STrackCutStudy::ConstructPlots(), DoPercentDifference(), draw_hists_3D(), drawCorr(), CemcMonDraw::DrawSecond(), SDeltaPtCutStudy::MakePlots(), MakePrettyPlot(), MakeRatioComparisonPlot(), STrackMatcherComparator::MakeRatiosAndPlots(), numericInverse(), and QuickDeltaPtExtractor().
Draw_HFJetTruth_InvMass_CrossSection2RAARatio_Theory_deta0 SetBottomMargin (0. 16)
Referenced by CalculateSigmaDca(), CompareOldVsNewPlots(), STrackCutStudy::ConstructPlots(), DoPercentDifference(), getPad(), SDeltaPtCutStudy::MakePlots(), MakePrettyPlot(), MakeRatioComparisonPlot(), STrackMatcherComparator::MakeRatiosAndPlots(), and QuickDeltaPtExtractor().
Graph_Graph1D_y11 SetDirectory (0)
Referenced by Fun4AllHistoManager::registerHisto().
leg SetFillColor (0)
cfitall SetFrameBorderMode (0)
Referenced by CompareOldVsNewPlots(), STrackCutStudy::ConstructPlots(), DoPercentDifference(), SDeltaPtCutStudy::MakePlots(), MakePrettyPlot(), MakeRatioComparisonPlot(), STrackMatcherComparator::MakeRatiosAndPlots(), and QuickDeltaPtExtractor().
Draw_HFJetTruth_InvMass_CrossSection2RAARatio_Theory_deta0 SetLeftMargin (0. 16)
Referenced by CalculateSigmaDca(), CompareOldVsNewPlots(), STrackCutStudy::ConstructPlots(), DoPercentDifference(), getPad(), SDeltaPtCutStudy::MakePlots(), MakePrettyPlot(), MakeRatioComparisonPlot(), STrackMatcherComparator::MakeRatiosAndPlots(), and QuickDeltaPtExtractor().
entry SetLineColor (1)
Referenced by analyzeClusterEtIso(), CalculateSigmaDca(), CompareOldVsNewPlots(), STrackCutStudy::ConstructPlots(), SDeltaPtCutStudy::CreateSigmaGraphs(), DoPercentDifference(), INTTVtxZ::Draw_1DEffComp(), Draw_BDiJetImbalance(), draw_hists_3D(), drawCanvas_invMass(), CemcMonDraw::DrawSecond(), Jet_reso_Iso(), STrackCutStudy::MakeCutText(), SDeltaPtCutStudy::MakePlots(), MakePrettyPlot(), MakeRatioComparisonPlot(), STrackMatcherComparator::MakeRatiosAndPlots(), numericInverse(), plot(), PlotLine(), QuickDeltaPtExtractor(), sccalib(), SetHistoStyle(), STrackCutStudy::SetHistStyles(), and SDeltaPtCutStudy::SetStyles().
entry SetLineStyle (1)
Referenced by analyzeClusterEtIso(), CalculateSigmaDca(), CompareOldVsNewPlots(), STrackCutStudy::ConstructPlots(), SDeltaPtCutStudy::CreateSigmaGraphs(), DoPercentDifference(), drawCanvas_invMass(), drawCorr(), CemcMonDraw::DrawSecond(), STrackCutStudy::MakeCutText(), SDeltaPtCutStudy::MakePlots(), MakePrettyPlot(), MakeRatioComparisonPlot(), STrackMatcherComparator::MakeRatiosAndPlots(), numericInverse(), PlotLine(), QuickDeltaPtExtractor(), STrackCutStudy::SetHistStyles(), and SDeltaPtCutStudy::SetStyles().
tex SetLineWidth (2)
Referenced by CalculateSigmaDca(), CompareOldVsNewPlots(), SDeltaPtCutStudy::CreateSigmaGraphs(), DoPercentDifference(), draw_hists_3D(), SDeltaPtCutStudy::MakePlots(), MakePrettyPlot(), MakeRatioComparisonPlot(), STrackMatcherComparator::MakeRatiosAndPlots(), plot(), PlotLine(), QuickDeltaPtExtractor(), and SDeltaPtCutStudy::SetStyles().
entry SetLineWidth (1)
entry SetMarkerColor (1)
Referenced by analyzeClusterEtIso(), CalculateSigmaDca(), CompareOldVsNewPlots(), DoPercentDifference(), INTTVtxZ::Draw_1DEffComp(), draw_hists_3D(), drawCorr(), MakePrettyPlot(), MakeRatioComparisonPlot(), STrackMatcherComparator::MakeRatiosAndPlots(), numericInverse(), QuickDeltaPtExtractor(), SetHistoStyle(), STrackCutStudy::SetHistStyles(), and SDeltaPtCutStudy::SetStyles().
fTCBfordave SetMarkerSize (1. 2)
Referenced by INTTVtxZ::Draw_1DEffComp(), and SetHistoStyle().
entry SetMarkerSize (1)
fTCBfordave SetMarkerStyle (20)
Referenced by CalculateSigmaDca(), CompareOldVsNewPlots(), DoPercentDifference(), INTTVtxZ::Draw_1DEffComp(), drawCorr(), MakePrettyPlot(), MakeRatioComparisonPlot(), STrackMatcherComparator::MakeRatiosAndPlots(), QuickDeltaPtExtractor(), SetHistoStyle(), STrackCutStudy::SetHistStyles(), and SDeltaPtCutStudy::SetStyles().
entry SetMarkerStyle (21)
hframe__2 SetMaximum (1. 2)
Referenced by plot().
hframe__2 SetMinimum (0)
gStyle SetOptFit (1)
gStyle SetOptStat (0)
Referenced by towerid::CalculateCutOffs(), CemcMonDraw::DrawFirst(), CemcMonDraw::DrawSecond(), CemcMonDraw::DrawThird(), and plot().
gStyle SetOptTitle (0)
Draw_HFJetTruth_InvMass_CrossSection2RAARatio_Theory_deta0 SetRightMargin (0. 05)
Draw_HFJetTruth_CrossSection2RAA SetSelected (Draw_HFJetTruth_CrossSection2RAA)
Graph_ge_h_b_copyv216497604924 SetStats (0)
Referenced by SetHistoStyle().
tex SetTextFont (42)
Referenced by CalculateSigmaDca(), CompareOldVsNewPlots(), STrackCutStudy::ConstructPlots(), DoPercentDifference(), DrawCutLabel(), STrackCutStudy::MakeCutText(), SDeltaPtCutStudy::MakePlots(), MakePrettyPlot(), MakeRatioComparisonPlot(), STrackMatcherComparator::MakeRatiosAndPlots(), and QuickDeltaPtExtractor().
Draw_HFJetTruth_InvMass_CrossSection2RAARatio_Theory_deta0 SetTickx (1)
Draw_HFJetTruth_InvMass_CrossSection2RAARatio_Theory_deta0 SetTicky (1)
Draw_HFJetTruth_InvMass_CrossSection2RAARatio_Theory_deta0 SetTopMargin (0. 05)
Referenced by CalculateSigmaDca(), CompareOldVsNewPlots(), STrackCutStudy::ConstructPlots(), DoPercentDifference(), getPad(), SDeltaPtCutStudy::MakePlots(), MakePrettyPlot(), MakeRatioComparisonPlot(), STrackMatcherComparator::MakeRatiosAndPlots(), and QuickDeltaPtExtractor().
Variable Documentation
_
Definition at line 51 of file 200pp_pythia8_CTEQ6L_7GeV_ALL.cfg_eneg_DSTReader.root_Draw_HFJetTruth_CrossSection2RAA.C.
View newest version in sPHENIX GitHub at line 51 of file 200pp_pythia8_CTEQ6L_7GeV_ALL.cfg_eneg_DSTReader.root_Draw_HFJetTruth_CrossSection2RAA.C
Au Au C
Definition at line 51 of file 200pp_pythia8_CTEQ6L_7GeV_ALL.cfg_eneg_DSTReader.root_Draw_HFJetTruth_CrossSection2RAA.C.
View newest version in sPHENIX GitHub at line 51 of file 200pp_pythia8_CTEQ6L_7GeV_ALL.cfg_eneg_DSTReader.root_Draw_HFJetTruth_CrossSection2RAA.C
TPad* Draw_HFJetTruth_CrossSection2RAA_1 = new TPad("Draw_HFJetTruth_CrossSection2RAA_1", "Draw_HFJetTruth_CrossSection2RAA_1",0.01,0.01,0.99,0.99)
Definition at line 21 of file 200pp_pythia8_CTEQ6L_7GeV_ALL.cfg_eneg_DSTReader.root_Draw_HFJetTruth_CrossSection2RAA.C.
View newest version in sPHENIX GitHub at line 21 of file 200pp_pythia8_CTEQ6L_7GeV_ALL.cfg_eneg_DSTReader.root_Draw_HFJetTruth_CrossSection2RAA.C
entry =leg->AddEntry("NULL","PYTHIA-8 #it{b}-jet, Anti-k_{T} R=0.4, |#eta|<0.7, CTEQ6L","")
Definition at line 134 of file 200pp_pythia8_CTEQ6L_7GeV_ALL.cfg_eneg_DSTReader.root_Draw_HFJetTruth_CrossSection2RAA.C.
View newest version in sPHENIX GitHub at line 134 of file 200pp_pythia8_CTEQ6L_7GeV_ALL.cfg_eneg_DSTReader.root_Draw_HFJetTruth_CrossSection2RAA.C
Referenced by AN_dp_sPHENIX(), Acts::Test::BOOST_DATA_TEST_CASE(), compareAssignedRealPos(), D0_BUP2020_AN_3yr(), D0_BUP2020_AN_5yr_comparison(), D0_BUP2020_AuAu_RAA_3yr(), D0_BUP2020_AuAu_v1_5y_compare(), D0_BUP2020_AuAu_v2_3yr(), D0_BUP2020_AuAu_v2_3yr_20wk_comp(), D0_BUP2020_pAu_C0_5_v2_3yr(), D0_BUP2020_pAu_v2_3yr(), D0_BUP2020OOArAr_RAA_5yr(), D0_BUP2020OOArAr_RAA_flat_5yr(), D0_BUP2020OOArAr_v2_5yr(), Acts::AdaptiveMultiVertexFinder< vfitter_t, sfinder_t >::deleteLastVertex(), SColdQcdCorrelatorAnalysis::SEnergyCorrelator::DoCorrelatorCalculation(), DrawCalibratedE_PlotTestBeam(), DrawCluster_Res_2Fit(), DrawCluster_Res_2Fit_1DSpacalNoSVX(), DrawCluster_Res_2Fit_1DSpacalNoSVX_Eta3(), DrawCluster_Res_2Fit_2DSpacalNoSVX(), DrawCluster_Res_2Fit_Electron_NoSVX(), DrawTowerSum_Res_2Fit_1DSpacalNoSVX(), DrawTowerSum_Res_2Fit_1DSpacalNoSVX_Eta3(), eicsmear_dvmp_plot(), OnCalServer::findRunNumInDB(), ActsExamples::from_json(), Acts::GeometryHierarchyMapJsonConverter< value_t, decorator_t >::fromJson(), RawTower_Temperature::get_eventnumber_from_entry(), RawTower_Temperature::get_temperature_from_entry(), RawTower_Temperature::get_time_from_entry(), IsolatedTrackAnalysis::getClusters(), IsolatedTrackAnalysis::getTracks(), TrkrHitSetv1::identify(), TrkrTruthTrackContainerv1::identify(), TrkrHitTruthAssocv1::identify(), TrkrClusterIterationMapv1::identify(), TrkrClusterHitAssocv1::identify(), TrackPidAssoc::identify(), Lc_BUP2020_AuAu_3yr(), Lc_BUP2022_AuAu_3yr(), CDBTTree::LoadCalibrations(), lurobo(), FillTruthRecoMatchTree::print_mvtx_diagnostics(), FillTruthRecoMatchMap::process_event(), PHG4TruthEventAction::ProcessShowers(), OnlMonClient::PutHistoInMap(), ClusHitsVerbosev1::pvecIE(), ActsExamples::RootSimHitReader::read(), ActsExamples::RootParticleReader::read(), ActsExamples::RootTrajectorySummaryReader::read(), ActsExamples::RootMaterialTrackReader::read(), ActsExamples::RootAthenaNTupleReader::read(), OnlMonClient::registerHisto(), TrkrTruthTrackContainerv1::Reset(), rootTrackClusterEnergy(), rootTruckatedMean(), ThermalPartonSampler::sample_2p1d(), ThermalPartonSampler::sample_3p1d(), sphenix_han(), ActsExamples::to_json(), Acts::GeometryHierarchyMapJsonConverter< value_t, decorator_t >::toJson(), ActsFatras::PlanarSurfaceDrift::toReadout(), Acts::Experimental::MultiLayerSurfacesUpdatorImpl< grid_t, path_generator >::update(), Acts::Experimental::IndexedUpdatorImpl< VariableBoundIndexGrid1, DetectorVolumesCollection, DetectorVolumeFiller >::update(), OnCalServer::updateDB(), OnCalServer::updateDBRunRange(), OnlMonClient::updateHistoMap(), vegas(), ActsExamples::CsvPlanarClusterWriter::writeT(), and ActsExamples::RootPlanarClusterWriter::writeT().
TH1F* hframe__2 = new TH1F("hframe__2","",1000,15,50)
Definition at line 37 of file 200pp_pythia8_CTEQ6L_7GeV_ALL.cfg_eneg_DSTReader.root_Draw_HFJetTruth_CrossSection2RAA.C.
View newest version in sPHENIX GitHub at line 37 of file 200pp_pythia8_CTEQ6L_7GeV_ALL.cfg_eneg_DSTReader.root_Draw_HFJetTruth_CrossSection2RAA.C