Analysis Software: sPHElectronv1 Class Reference
sPHElectronv1 Class Reference
#include <analysis/blob/master/EventMix/src/sPHElectronv1.h>
Public Member Functions
sPHElectronv1 ()
sPHElectronv1 (const SvtxTrack *)
sPHElectronv1 (const sPHElectronv1 &electron)
sPHElectronv1 & operator= (const sPHElectronv1 &electron)
virtual ~sPHElectronv1 ()
virtual void identify (std::ostream &os=std::cout) const
virtual void Reset ()
Clear Event.
virtual int isValid () const
isValid returns non zero if object contains vailid data
virtual PHObject * CloneMe () const
Virtual copy constructor.
virtual unsigned int get_id () const
virtual int get_charge () const
virtual double get_px () const
virtual double get_py () const
virtual double get_pz () const
virtual double get_dphi () const
virtual double get_deta () const
virtual double get_emce () const
virtual double get_e3x3 () const
virtual double get_e5x5 () const
virtual double get_chi2 () const
virtual unsigned int get_ndf () const
virtual double get_zvtx () const
virtual double get_dca2d () const
virtual double get_dca2d_error () const
virtual double get_dca3d_xy () const
virtual double get_dca3d_z () const
virtual int get_nmvtx () const
virtual int get_ntpc () const
virtual double get_cemc_ecore () const
virtual double get_cemc_chi2 () const
virtual double get_cemc_prob () const
virtual double get_cemc_dphi () const
virtual double get_cemc_deta () const
virtual double get_hcalin_e () const
virtual double get_hcalin_dphi () const
virtual double get_hcalin_deta () const
virtual void set_id (unsigned int id)
virtual void set_charge (int charge)
virtual void set_px (double px)
virtual void set_py (double py)
virtual void set_pz (double pz)
virtual void set_dphi (double dphi)
virtual void set_deta (double deta)
virtual void set_emce (double emce)
virtual void set_e3x3 (double e3x3)
virtual void set_e5x5 (double e5x5)
virtual void set_chi2 (double a)
virtual void set_ndf (unsigned int a)
virtual void set_zvtx (double a)
virtual void set_dca2d (double a)
virtual void set_dca2d_error (double a)
virtual void set_dca3d_xy (double a)
virtual void set_dca3d_z (double a)
virtual void set_nmvtx (int i)
virtual void set_ntpc (int i)
virtual void set_cemc_ecore (double a)
virtual void set_cemc_chi2 (double a)
virtual void set_cemc_prob (double a)
virtual void set_cemc_dphi (double a)
virtual void set_cemc_deta (double a)
virtual void set_hcalin_e (double a)
virtual void set_hcalin_dphi (double a)
virtual void set_hcalin_deta (double a)
Public Member Functions inherited from sPHElectron
virtual ~sPHElectron ()
Public Member Functions inherited from PHObject
PHObject ()
ctor
~PHObject () override
dtor
virtual PHObject * clone () const final
PHObject * Clone (const char *newname="") const final
void Copy (TObject &object) const final
virtual int Integrate () const
virtual int Integrate (PHObject *)
virtual void CopyFrom (const PHObject *obj)
Protected Attributes
unsigned int _id
int _charge
double _px
double _py
double _pz
double _dphi
double _deta
double _emce
double _e3x3
double _e5x5
double _chi2
unsigned int _ndf
double _zvtx
double _dca2d
double _dca2d_error
double _dca3d_xy
double _dca3d_z
int _nmvtx
int _ntpc
double _cemc_ecore
double _cemc_chi2
double _cemc_prob
double _cemc_dphi
double _cemc_deta
double _hcalin_e
double _hcalin_dphi
double _hcalin_deta
Additional Inherited Members
Protected Member Functions inherited from sPHElectron
sPHElectron ()
Detailed Description
Definition at line 12 of file sPHElectronv1.h.
View newest version in sPHENIX GitHub at line 12 of file sPHElectronv1.h
Constructor & Destructor Documentation
sPHElectronv1::sPHElectronv1 ()
Definition at line 9 of file sPHElectronv1.cc.
View newest version in sPHENIX GitHub at line 9 of file sPHElectronv1.cc
References _cemc_chi2, _cemc_deta, _cemc_dphi, _cemc_ecore, _cemc_prob, _charge, _chi2, _dca2d, _dca2d_error, _dca3d_xy, _dca3d_z, _deta, _dphi, _e3x3, _e5x5, _emce, _hcalin_deta, _hcalin_dphi, _hcalin_e, _id, _ndf, _nmvtx, _ntpc, _px, _py, _pz, and _zvtx.
Referenced by CloneMe().
sPHElectronv1::sPHElectronv1 (const SvtxTrack * trk)
Definition at line 44 of file sPHElectronv1.cc.
View newest version in sPHENIX GitHub at line 44 of file sPHElectronv1.cc
References _cemc_chi2, _cemc_deta, _cemc_dphi, _cemc_ecore, _cemc_prob, _charge, _chi2, _dca2d, _dca2d_error, _dca3d_xy, _dca3d_z, _deta, _dphi, _e3x3, _e5x5, _emce, _hcalin_deta, _hcalin_dphi, _hcalin_e, _id, _ndf, _nmvtx, _ntpc, _px, _py, _pz, _zvtx, SvtxTrack::begin_cluster_keys(), Enable::CEMC, SvtxTrack::end_cluster_keys(), SvtxTrack::get_cal_cluster_e(), SvtxTrack::get_cal_deta(), SvtxTrack::get_cal_dphi(), SvtxTrack::get_cal_energy_3x3(), SvtxTrack::get_cal_energy_5x5(), SvtxTrack::get_charge(), SvtxTrack::get_chisq(), SvtxTrack::get_dca2d(), SvtxTrack::get_dca2d_error(), SvtxTrack::get_dca3d_xy(), SvtxTrack::get_dca3d_z(), SvtxTrack::get_id(), SvtxTrack::get_ndf(), SvtxTrack::get_px(), SvtxTrack::get_py(), SvtxTrack::get_pz(), SvtxTrack::get_z(), TrkrDefs::getTrkrId(), and RawTowerDefs::HCALIN.
sPHElectronv1::sPHElectronv1 (const sPHElectronv1 & electron)
Definition at line 86 of file sPHElectronv1.cc.
View newest version in sPHENIX GitHub at line 86 of file sPHElectronv1.cc
References electron.
virtual sPHElectronv1::~sPHElectronv1 () inline virtual
Definition at line 20 of file sPHElectronv1.h.
View newest version in sPHENIX GitHub at line 20 of file sPHElectronv1.h
Member Function Documentation
virtual PHObject* sPHElectronv1::CloneMe () const inline virtual
Virtual copy constructor.
Reimplemented from sPHElectron.
Definition at line 25 of file sPHElectronv1.h.
View newest version in sPHENIX GitHub at line 25 of file sPHElectronv1.h
References sPHElectronv1().
virtual double sPHElectronv1::get_cemc_chi2 () const inline virtual
Reimplemented from sPHElectron.
Definition at line 50 of file sPHElectronv1.h.
View newest version in sPHENIX GitHub at line 50 of file sPHElectronv1.h
References _cemc_chi2.
Referenced by operator=().
virtual double sPHElectronv1::get_cemc_deta () const inline virtual
Reimplemented from sPHElectron.
Definition at line 53 of file sPHElectronv1.h.
View newest version in sPHENIX GitHub at line 53 of file sPHElectronv1.h
References _cemc_deta.
Referenced by operator=().
virtual double sPHElectronv1::get_cemc_dphi () const inline virtual
Reimplemented from sPHElectron.
Definition at line 52 of file sPHElectronv1.h.
View newest version in sPHENIX GitHub at line 52 of file sPHElectronv1.h
References _cemc_dphi.
Referenced by operator=().
virtual double sPHElectronv1::get_cemc_ecore () const inline virtual
Reimplemented from sPHElectron.
Definition at line 49 of file sPHElectronv1.h.
View newest version in sPHENIX GitHub at line 49 of file sPHElectronv1.h
References _cemc_ecore.
Referenced by operator=().
virtual double sPHElectronv1::get_cemc_prob () const inline virtual
Reimplemented from sPHElectron.
Definition at line 51 of file sPHElectronv1.h.
View newest version in sPHENIX GitHub at line 51 of file sPHElectronv1.h
References _cemc_prob.
Referenced by operator=().
virtual int sPHElectronv1::get_charge () const inline virtual
Reimplemented from sPHElectron.
Definition at line 28 of file sPHElectronv1.h.
View newest version in sPHENIX GitHub at line 28 of file sPHElectronv1.h
References _charge.
Referenced by PairMaker::MakeMixedPairs(), and operator=().
virtual double sPHElectronv1::get_chi2 () const inline virtual
Reimplemented from sPHElectron.
Definition at line 38 of file sPHElectronv1.h.
View newest version in sPHENIX GitHub at line 38 of file sPHElectronv1.h
References _chi2.
Referenced by operator=(), and sPHAnalysis::process_event_pairs().
virtual double sPHElectronv1::get_dca2d () const inline virtual
Reimplemented from sPHElectron.
Definition at line 41 of file sPHElectronv1.h.
View newest version in sPHENIX GitHub at line 41 of file sPHElectronv1.h
References _dca2d.
Referenced by operator=(), and sPHAnalysis::process_event_pairs().
virtual double sPHElectronv1::get_dca2d_error () const inline virtual
Reimplemented from sPHElectron.
Definition at line 42 of file sPHElectronv1.h.
View newest version in sPHENIX GitHub at line 42 of file sPHElectronv1.h
References _dca2d_error.
Referenced by operator=().
virtual double sPHElectronv1::get_dca3d_xy () const inline virtual
Reimplemented from sPHElectron.
Definition at line 43 of file sPHElectronv1.h.
View newest version in sPHENIX GitHub at line 43 of file sPHElectronv1.h
References _dca3d_xy.
Referenced by operator=(), and sPHAnalysis::process_event_pairs().
virtual double sPHElectronv1::get_dca3d_z () const inline virtual
Reimplemented from sPHElectron.
Definition at line 44 of file sPHElectronv1.h.
View newest version in sPHENIX GitHub at line 44 of file sPHElectronv1.h
References _dca3d_z.
Referenced by operator=(), and sPHAnalysis::process_event_pairs().
virtual double sPHElectronv1::get_deta () const inline virtual
Reimplemented from sPHElectron.
Definition at line 33 of file sPHElectronv1.h.
View newest version in sPHENIX GitHub at line 33 of file sPHElectronv1.h
References _deta.
Referenced by operator=().
virtual double sPHElectronv1::get_dphi () const inline virtual
Reimplemented from sPHElectron.
Definition at line 32 of file sPHElectronv1.h.
View newest version in sPHENIX GitHub at line 32 of file sPHElectronv1.h
References _dphi.
Referenced by operator=().
virtual double sPHElectronv1::get_e3x3 () const inline virtual
Reimplemented from sPHElectron.
Definition at line 35 of file sPHElectronv1.h.
View newest version in sPHENIX GitHub at line 35 of file sPHElectronv1.h
References _e3x3.
Referenced by operator=(), and sPHAnalysis::process_event_pairs().
virtual double sPHElectronv1::get_e5x5 () const inline virtual
Reimplemented from sPHElectron.
Definition at line 36 of file sPHElectronv1.h.
View newest version in sPHENIX GitHub at line 36 of file sPHElectronv1.h
References _e5x5.
Referenced by operator=().
virtual double sPHElectronv1::get_emce () const inline virtual
Reimplemented from sPHElectron.
Definition at line 34 of file sPHElectronv1.h.
View newest version in sPHENIX GitHub at line 34 of file sPHElectronv1.h
References _emce.
Referenced by operator=(), and sPHAnalysis::process_event_pairs().
virtual double sPHElectronv1::get_hcalin_deta () const inline virtual
Reimplemented from sPHElectron.
Definition at line 56 of file sPHElectronv1.h.
View newest version in sPHENIX GitHub at line 56 of file sPHElectronv1.h
References _hcalin_deta.
Referenced by operator=().
virtual double sPHElectronv1::get_hcalin_dphi () const inline virtual
Reimplemented from sPHElectron.
Definition at line 55 of file sPHElectronv1.h.
View newest version in sPHENIX GitHub at line 55 of file sPHElectronv1.h
References _hcalin_dphi.
Referenced by operator=().
virtual double sPHElectronv1::get_hcalin_e () const inline virtual
Reimplemented from sPHElectron.
Definition at line 54 of file sPHElectronv1.h.
View newest version in sPHENIX GitHub at line 54 of file sPHElectronv1.h
References _hcalin_e.
Referenced by operator=().
virtual unsigned int sPHElectronv1::get_id () const inline virtual
Reimplemented from sPHElectron.
Definition at line 27 of file sPHElectronv1.h.
View newest version in sPHENIX GitHub at line 27 of file sPHElectronv1.h
References _id.
Referenced by operator=(), and sPHElectronPairv1::sPHElectronPairv1().
virtual unsigned int sPHElectronv1::get_ndf () const inline virtual
Reimplemented from sPHElectron.
Definition at line 39 of file sPHElectronv1.h.
View newest version in sPHENIX GitHub at line 39 of file sPHElectronv1.h
References _ndf.
Referenced by operator=(), and sPHAnalysis::process_event_pairs().
virtual int sPHElectronv1::get_nmvtx () const inline virtual
Reimplemented from sPHElectron.
Definition at line 46 of file sPHElectronv1.h.
View newest version in sPHENIX GitHub at line 46 of file sPHElectronv1.h
References _nmvtx.
Referenced by operator=(), and sPHAnalysis::process_event_pairs().
virtual int sPHElectronv1::get_ntpc () const inline virtual
Reimplemented from sPHElectron.
Definition at line 47 of file sPHElectronv1.h.
View newest version in sPHENIX GitHub at line 47 of file sPHElectronv1.h
References _ntpc.
Referenced by operator=(), and sPHAnalysis::process_event_pairs().
virtual double sPHElectronv1::get_px () const inline virtual
Reimplemented from sPHElectron.
Definition at line 29 of file sPHElectronv1.h.
View newest version in sPHENIX GitHub at line 29 of file sPHElectronv1.h
References _px.
Referenced by sPHElectronPairv1::get_eta(), sPHElectronPairv1::get_mass(), sPHElectronPairv1::get_phiv(), sPHElectronPairv1::get_pt(), operator=(), and sPHAnalysis::process_event_pairs().
virtual double sPHElectronv1::get_py () const inline virtual
Reimplemented from sPHElectron.
Definition at line 30 of file sPHElectronv1.h.
View newest version in sPHENIX GitHub at line 30 of file sPHElectronv1.h
References _py.
Referenced by sPHElectronPairv1::get_eta(), sPHElectronPairv1::get_mass(), sPHElectronPairv1::get_phiv(), sPHElectronPairv1::get_pt(), operator=(), and sPHAnalysis::process_event_pairs().
virtual double sPHElectronv1::get_pz () const inline virtual
Reimplemented from sPHElectron.
Definition at line 31 of file sPHElectronv1.h.
View newest version in sPHENIX GitHub at line 31 of file sPHElectronv1.h
References _pz.
Referenced by sPHElectronPairv1::get_eta(), sPHElectronPairv1::get_mass(), sPHElectronPairv1::get_phiv(), sPHElectronPairv1::get_pt(), operator=(), and sPHAnalysis::process_event_pairs().
virtual double sPHElectronv1::get_zvtx () const inline virtual
Reimplemented from sPHElectron.
Definition at line 40 of file sPHElectronv1.h.
View newest version in sPHENIX GitHub at line 40 of file sPHElectronv1.h
References _zvtx.
Referenced by PairMaker::MakeMixedPairs(), and operator=().
void sPHElectronv1::identify (std::ostream & os = std::cout) const virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from sPHElectron.
Definition at line 128 of file sPHElectronv1.cc.
View newest version in sPHENIX GitHub at line 128 of file sPHElectronv1.cc
int sPHElectronv1::isValid () const virtual
isValid returns non zero if object contains vailid data
Reimplemented from sPHElectron.
Definition at line 134 of file sPHElectronv1.cc.
View newest version in sPHENIX GitHub at line 134 of file sPHElectronv1.cc
References _charge.
sPHElectronv1 & sPHElectronv1::operator= (const sPHElectronv1 & electron)
Definition at line 92 of file sPHElectronv1.cc.
View newest version in sPHENIX GitHub at line 92 of file sPHElectronv1.cc
References _cemc_chi2, _cemc_deta, _cemc_dphi, _cemc_ecore, _cemc_prob, _charge, _chi2, _dca2d, _dca2d_error, _dca3d_xy, _dca3d_z, _deta, _dphi, _e3x3, _e5x5, _emce, _hcalin_deta, _hcalin_dphi, _hcalin_e, _id, _ndf, _nmvtx, _ntpc, _px, _py, _pz, _zvtx, get_cemc_chi2(), get_cemc_deta(), get_cemc_dphi(), get_cemc_ecore(), get_cemc_prob(), get_charge(), get_chi2(), get_dca2d(), get_dca2d_error(), get_dca3d_xy(), get_dca3d_z(), get_deta(), get_dphi(), get_e3x3(), get_e5x5(), get_emce(), get_hcalin_deta(), get_hcalin_dphi(), get_hcalin_e(), get_id(), get_ndf(), get_nmvtx(), get_ntpc(), get_px(), get_py(), get_pz(), and get_zvtx().
virtual void sPHElectronv1::Reset () inline virtual
Clear Event.
Reimplemented from sPHElectron.
Definition at line 23 of file sPHElectronv1.h.
View newest version in sPHENIX GitHub at line 23 of file sPHElectronv1.h
virtual void sPHElectronv1::set_cemc_chi2 (double a) inline virtual
Reimplemented from sPHElectron.
Definition at line 81 of file sPHElectronv1.h.
View newest version in sPHENIX GitHub at line 81 of file sPHElectronv1.h
References _cemc_chi2, and KFPMath::a.
Referenced by PairMaker::process_event_test().
virtual void sPHElectronv1::set_cemc_deta (double a) inline virtual
Reimplemented from sPHElectron.
Definition at line 84 of file sPHElectronv1.h.
View newest version in sPHENIX GitHub at line 84 of file sPHElectronv1.h
References _cemc_deta, and KFPMath::a.
virtual void sPHElectronv1::set_cemc_dphi (double a) inline virtual
Reimplemented from sPHElectron.
Definition at line 83 of file sPHElectronv1.h.
View newest version in sPHENIX GitHub at line 83 of file sPHElectronv1.h
References _cemc_dphi, and KFPMath::a.
virtual void sPHElectronv1::set_cemc_ecore (double a) inline virtual
Reimplemented from sPHElectron.
Definition at line 80 of file sPHElectronv1.h.
View newest version in sPHENIX GitHub at line 80 of file sPHElectronv1.h
References _cemc_ecore, and KFPMath::a.
Referenced by PairMaker::process_event_test().
virtual void sPHElectronv1::set_cemc_prob (double a) inline virtual
Reimplemented from sPHElectron.
Definition at line 82 of file sPHElectronv1.h.
View newest version in sPHENIX GitHub at line 82 of file sPHElectronv1.h
References _cemc_prob, and KFPMath::a.
Referenced by PairMaker::process_event_test().
virtual void sPHElectronv1::set_charge (int charge) inline virtual
Reimplemented from sPHElectron.
Definition at line 59 of file sPHElectronv1.h.
View newest version in sPHENIX GitHub at line 59 of file sPHElectronv1.h
References _charge, and charge().
virtual void sPHElectronv1::set_chi2 (double a) inline virtual
Reimplemented from sPHElectron.
Definition at line 69 of file sPHElectronv1.h.
View newest version in sPHENIX GitHub at line 69 of file sPHElectronv1.h
References _chi2, and KFPMath::a.
virtual void sPHElectronv1::set_dca2d (double a) inline virtual
Reimplemented from sPHElectron.
Definition at line 72 of file sPHElectronv1.h.
View newest version in sPHENIX GitHub at line 72 of file sPHElectronv1.h
References _dca2d, and KFPMath::a.
virtual void sPHElectronv1::set_dca2d_error (double a) inline virtual
Reimplemented from sPHElectron.
Definition at line 73 of file sPHElectronv1.h.
View newest version in sPHENIX GitHub at line 73 of file sPHElectronv1.h
References _dca2d_error, and KFPMath::a.
virtual void sPHElectronv1::set_dca3d_xy (double a) inline virtual
Reimplemented from sPHElectron.
Definition at line 74 of file sPHElectronv1.h.
View newest version in sPHENIX GitHub at line 74 of file sPHElectronv1.h
References _dca3d_xy, and KFPMath::a.
virtual void sPHElectronv1::set_dca3d_z (double a) inline virtual
Reimplemented from sPHElectron.
Definition at line 75 of file sPHElectronv1.h.
View newest version in sPHENIX GitHub at line 75 of file sPHElectronv1.h
References _dca3d_z, and KFPMath::a.
virtual void sPHElectronv1::set_deta (double deta) inline virtual
Reimplemented from sPHElectron.
Definition at line 64 of file sPHElectronv1.h.
View newest version in sPHENIX GitHub at line 64 of file sPHElectronv1.h
References _deta.
virtual void sPHElectronv1::set_dphi (double dphi) inline virtual
Reimplemented from sPHElectron.
Definition at line 63 of file sPHElectronv1.h.
View newest version in sPHENIX GitHub at line 63 of file sPHElectronv1.h
References _dphi, and INTTVtxZ::dphi.
virtual void sPHElectronv1::set_e3x3 (double e3x3) inline virtual
Reimplemented from sPHElectron.
Definition at line 66 of file sPHElectronv1.h.
View newest version in sPHENIX GitHub at line 66 of file sPHElectronv1.h
References _e3x3.
virtual void sPHElectronv1::set_e5x5 (double e5x5) inline virtual
Reimplemented from sPHElectron.
Definition at line 67 of file sPHElectronv1.h.
View newest version in sPHENIX GitHub at line 67 of file sPHElectronv1.h
References _e5x5.
virtual void sPHElectronv1::set_emce (double emce) inline virtual
Reimplemented from sPHElectron.
Definition at line 65 of file sPHElectronv1.h.
View newest version in sPHENIX GitHub at line 65 of file sPHElectronv1.h
References _emce.
virtual void sPHElectronv1::set_hcalin_deta (double a) inline virtual
Reimplemented from sPHElectron.
Definition at line 87 of file sPHElectronv1.h.
View newest version in sPHENIX GitHub at line 87 of file sPHElectronv1.h
References _hcalin_deta, and KFPMath::a.
virtual void sPHElectronv1::set_hcalin_dphi (double a) inline virtual
Reimplemented from sPHElectron.
Definition at line 86 of file sPHElectronv1.h.
View newest version in sPHENIX GitHub at line 86 of file sPHElectronv1.h
References _hcalin_dphi, and KFPMath::a.
virtual void sPHElectronv1::set_hcalin_e (double a) inline virtual
Reimplemented from sPHElectron.
Definition at line 85 of file sPHElectronv1.h.
View newest version in sPHENIX GitHub at line 85 of file sPHElectronv1.h
References _hcalin_e, and KFPMath::a.
virtual void sPHElectronv1::set_id (unsigned int id) inline virtual
Reimplemented from sPHElectron.
Definition at line 58 of file sPHElectronv1.h.
View newest version in sPHENIX GitHub at line 58 of file sPHElectronv1.h
References _id, and train_ambiguity_solver::id.
virtual void sPHElectronv1::set_ndf (unsigned int a) inline virtual
Reimplemented from sPHElectron.
Definition at line 70 of file sPHElectronv1.h.
View newest version in sPHENIX GitHub at line 70 of file sPHElectronv1.h
References _ndf, and KFPMath::a.
virtual void sPHElectronv1::set_nmvtx (int i) inline virtual
Reimplemented from sPHElectron.
Definition at line 77 of file sPHElectronv1.h.
View newest version in sPHENIX GitHub at line 77 of file sPHElectronv1.h
References _nmvtx, and i.
virtual void sPHElectronv1::set_ntpc (int i) inline virtual
Reimplemented from sPHElectron.
Definition at line 78 of file sPHElectronv1.h.
View newest version in sPHENIX GitHub at line 78 of file sPHElectronv1.h
References _ntpc, and i.
virtual void sPHElectronv1::set_px (double px) inline virtual
Reimplemented from sPHElectron.
Definition at line 60 of file sPHElectronv1.h.
View newest version in sPHENIX GitHub at line 60 of file sPHElectronv1.h
References _px.
virtual void sPHElectronv1::set_py (double py) inline virtual
Reimplemented from sPHElectron.
Definition at line 61 of file sPHElectronv1.h.
View newest version in sPHENIX GitHub at line 61 of file sPHElectronv1.h
References _py.
virtual void sPHElectronv1::set_pz (double pz) inline virtual
Reimplemented from sPHElectron.
Definition at line 62 of file sPHElectronv1.h.
View newest version in sPHENIX GitHub at line 62 of file sPHElectronv1.h
References _pz.
virtual void sPHElectronv1::set_zvtx (double a) inline virtual
Reimplemented from sPHElectron.
Definition at line 71 of file sPHElectronv1.h.
View newest version in sPHENIX GitHub at line 71 of file sPHElectronv1.h
References _zvtx, and KFPMath::a.
Referenced by PairMaker::process_event_test().
Member Data Documentation
double sPHElectronv1::_cemc_chi2 protected
Definition at line 114 of file sPHElectronv1.h.
View newest version in sPHENIX GitHub at line 114 of file sPHElectronv1.h
Referenced by get_cemc_chi2(), operator=(), set_cemc_chi2(), and sPHElectronv1().
double sPHElectronv1::_cemc_deta protected
Definition at line 117 of file sPHElectronv1.h.
View newest version in sPHENIX GitHub at line 117 of file sPHElectronv1.h
Referenced by get_cemc_deta(), operator=(), set_cemc_deta(), and sPHElectronv1().
double sPHElectronv1::_cemc_dphi protected
Definition at line 116 of file sPHElectronv1.h.
View newest version in sPHENIX GitHub at line 116 of file sPHElectronv1.h
Referenced by get_cemc_dphi(), operator=(), set_cemc_dphi(), and sPHElectronv1().
double sPHElectronv1::_cemc_ecore protected
Definition at line 113 of file sPHElectronv1.h.
View newest version in sPHENIX GitHub at line 113 of file sPHElectronv1.h
Referenced by get_cemc_ecore(), operator=(), set_cemc_ecore(), and sPHElectronv1().
double sPHElectronv1::_cemc_prob protected
Definition at line 115 of file sPHElectronv1.h.
View newest version in sPHENIX GitHub at line 115 of file sPHElectronv1.h
Referenced by get_cemc_prob(), operator=(), set_cemc_prob(), and sPHElectronv1().
int sPHElectronv1::_charge protected
Definition at line 92 of file sPHElectronv1.h.
View newest version in sPHENIX GitHub at line 92 of file sPHElectronv1.h
Referenced by get_charge(), isValid(), operator=(), set_charge(), and sPHElectronv1().
double sPHElectronv1::_chi2 protected
Definition at line 102 of file sPHElectronv1.h.
View newest version in sPHENIX GitHub at line 102 of file sPHElectronv1.h
Referenced by get_chi2(), operator=(), set_chi2(), and sPHElectronv1().
double sPHElectronv1::_dca2d protected
Definition at line 105 of file sPHElectronv1.h.
View newest version in sPHENIX GitHub at line 105 of file sPHElectronv1.h
Referenced by get_dca2d(), operator=(), set_dca2d(), and sPHElectronv1().
double sPHElectronv1::_dca2d_error protected
Definition at line 106 of file sPHElectronv1.h.
View newest version in sPHENIX GitHub at line 106 of file sPHElectronv1.h
Referenced by get_dca2d_error(), operator=(), set_dca2d_error(), and sPHElectronv1().
double sPHElectronv1::_dca3d_xy protected
Definition at line 107 of file sPHElectronv1.h.
View newest version in sPHENIX GitHub at line 107 of file sPHElectronv1.h
Referenced by get_dca3d_xy(), operator=(), set_dca3d_xy(), and sPHElectronv1().
double sPHElectronv1::_dca3d_z protected
Definition at line 108 of file sPHElectronv1.h.
View newest version in sPHENIX GitHub at line 108 of file sPHElectronv1.h
Referenced by get_dca3d_z(), operator=(), set_dca3d_z(), and sPHElectronv1().
double sPHElectronv1::_deta protected
Definition at line 97 of file sPHElectronv1.h.
View newest version in sPHENIX GitHub at line 97 of file sPHElectronv1.h
Referenced by get_deta(), operator=(), set_deta(), and sPHElectronv1().
double sPHElectronv1::_dphi protected
Definition at line 96 of file sPHElectronv1.h.
View newest version in sPHENIX GitHub at line 96 of file sPHElectronv1.h
Referenced by get_dphi(), operator=(), set_dphi(), and sPHElectronv1().
double sPHElectronv1::_e3x3 protected
Definition at line 99 of file sPHElectronv1.h.
View newest version in sPHENIX GitHub at line 99 of file sPHElectronv1.h
Referenced by get_e3x3(), operator=(), set_e3x3(), and sPHElectronv1().
double sPHElectronv1::_e5x5 protected
Definition at line 100 of file sPHElectronv1.h.
View newest version in sPHENIX GitHub at line 100 of file sPHElectronv1.h
Referenced by get_e5x5(), operator=(), set_e5x5(), and sPHElectronv1().
double sPHElectronv1::_emce protected
Definition at line 98 of file sPHElectronv1.h.
View newest version in sPHENIX GitHub at line 98 of file sPHElectronv1.h
Referenced by get_emce(), operator=(), set_emce(), and sPHElectronv1().
double sPHElectronv1::_hcalin_deta protected
Definition at line 120 of file sPHElectronv1.h.
View newest version in sPHENIX GitHub at line 120 of file sPHElectronv1.h
Referenced by get_hcalin_deta(), operator=(), set_hcalin_deta(), and sPHElectronv1().
double sPHElectronv1::_hcalin_dphi protected
Definition at line 119 of file sPHElectronv1.h.
View newest version in sPHENIX GitHub at line 119 of file sPHElectronv1.h
Referenced by get_hcalin_dphi(), operator=(), set_hcalin_dphi(), and sPHElectronv1().
double sPHElectronv1::_hcalin_e protected
Definition at line 118 of file sPHElectronv1.h.
View newest version in sPHENIX GitHub at line 118 of file sPHElectronv1.h
Referenced by get_hcalin_e(), operator=(), set_hcalin_e(), and sPHElectronv1().
unsigned int sPHElectronv1::_id protected
Definition at line 91 of file sPHElectronv1.h.
View newest version in sPHENIX GitHub at line 91 of file sPHElectronv1.h
Referenced by get_id(), operator=(), set_id(), and sPHElectronv1().
unsigned int sPHElectronv1::_ndf protected
Definition at line 103 of file sPHElectronv1.h.
View newest version in sPHENIX GitHub at line 103 of file sPHElectronv1.h
Referenced by get_ndf(), operator=(), set_ndf(), and sPHElectronv1().
int sPHElectronv1::_nmvtx protected
Definition at line 110 of file sPHElectronv1.h.
View newest version in sPHENIX GitHub at line 110 of file sPHElectronv1.h
Referenced by get_nmvtx(), operator=(), set_nmvtx(), and sPHElectronv1().
int sPHElectronv1::_ntpc protected
Definition at line 111 of file sPHElectronv1.h.
View newest version in sPHENIX GitHub at line 111 of file sPHElectronv1.h
Referenced by get_ntpc(), operator=(), set_ntpc(), and sPHElectronv1().
double sPHElectronv1::_px protected
Definition at line 93 of file sPHElectronv1.h.
View newest version in sPHENIX GitHub at line 93 of file sPHElectronv1.h
Referenced by get_px(), operator=(), set_px(), and sPHElectronv1().
double sPHElectronv1::_py protected
Definition at line 94 of file sPHElectronv1.h.
View newest version in sPHENIX GitHub at line 94 of file sPHElectronv1.h
Referenced by get_py(), operator=(), set_py(), and sPHElectronv1().
double sPHElectronv1::_pz protected
Definition at line 95 of file sPHElectronv1.h.
View newest version in sPHENIX GitHub at line 95 of file sPHElectronv1.h
Referenced by get_pz(), operator=(), set_pz(), and sPHElectronv1().
double sPHElectronv1::_zvtx protected
Definition at line 104 of file sPHElectronv1.h.
View newest version in sPHENIX GitHub at line 104 of file sPHElectronv1.h
Referenced by get_zvtx(), operator=(), set_zvtx(), and sPHElectronv1().
The documentation for this class was generated from the following files:
analysis/blob/master/EventMix/src/sPHElectronv1.h
analysis/blob/master/EventMix/src/sPHElectronv1.cc