Analysis Software: Acts::Svg::SurfaceArrayConverter Namespace Reference
Acts::Svg::SurfaceArrayConverter Namespace Reference
Classes
struct Options
Nested options struct.
Functions
std::tuple< std::vector
< ProtoSurfaces >, ProtoGrid,
std::vector< ProtoAssociations > > convert (const GeometryContext &gctx, const SurfaceArray &surfaceArray, const Options &cOptions)
Function Documentation
std::tuple< std::vector< Acts::Svg::ProtoSurfaces >, Acts::Svg::ProtoGrid, std::vector< Acts::Svg::ProtoAssociations > > Acts::Svg::SurfaceArrayConverter::convert (const GeometryContext & gctx, const SurfaceArray & surfaceArray, const Options & cOptions)
Convert a surface array into needed constituents
Parameters
gtcx is the geometry context of the conversion call
surfaceArray is the surface to convert
cOptions the conversion options
Note
the type of view is auto-generated from the binning information
Returns
a collection of proto surface object and a grid, and associations
Definition at line 18 of file SurfaceArraySvgConverter.cpp.
View newest version in sPHENIX GitHub at line 18 of file SurfaceArraySvgConverter.cpp
References alpha, Acts::SurfaceArray::binningValues(), Acts::binPhi, Acts::binR, Acts::binZ, Acts::Svg::SurfaceConverter::convert(), Acts::Svg::DetectorConverter::convert(), Acts::Test::cSurface, distance(), Acts::GeometryHierarchyMap< value_t >::end(), Acts::GeometryHierarchyMap< value_t >::find(), Acts::SurfaceArray::getAxes(), Acts::SurfaceArray::neighbors(), Acts::VectorHelpers::perp(), sTransform, Acts::Svg::SurfaceConverter::Options::style, Acts::SurfaceArray::surfaces(), Acts::Svg::SurfaceArrayConverter::Options::surfaceStyles, Acts::Svg::SurfaceConverter::Options::templateSurface, train_ambiguity_solver::test, to_string(), and Acts::Svg::View::xy().