Analysis Software: Acts::RadialBounds Class Reference
Acts::RadialBounds Class Reference
#include <acts/blob/sPHENIX/Core/include/Acts/Surfaces/RadialBounds.hpp>
Public Types
enum BoundValues {
eMinR = 0, eMaxR = 1, eHalfPhiSector = 2, eAveragePhi = 3,
eSize = 4
}
Public Member Functions
RadialBounds ()=delete
RadialBounds (double minR, double maxR, double halfPhi=M_PI, double avgPhi=0.) noexcept(false)
RadialBounds (const std::array< double, eSize > &values) noexcept(false)
~RadialBounds () override=default
SurfaceBounds::BoundsType type () const final
std::vector< double > values () const final
bool inside (const Vector2D &lposition, const BoundaryCheck &bcheck) const final
std::ostream & toStream (std::ostream &sl) const final
double rMin () const final
Return method for inner Radius.
double rMax () const final
Return method for outer Radius.
double get (BoundValues bValue) const
bool coversFullAzimuth () const final
Returns true for full phi coverage.
bool insideRadialBounds (double R, double tolerance=0.) const final
double binningValueR () const final
Return a reference radius for binning.
double binningValuePhi () const final
Return a reference radius for binning.
Private Member Functions
void checkConsistency () noexcept(false)
Vector2D shifted (const Vector2D &lposition) const
std::vector< Vector2D > vertices (unsigned int lseg) const final
Private Attributes
std::array< double, eSize > m_values
Detailed Description
Class to describe the bounds for a planar DiscSurface. By providing an argument for hphisec, the bounds can be restricted to a phi-range around the center position.
Definition at line 27 of file RadialBounds.hpp.
View newest version in sPHENIX GitHub at line 27 of file RadialBounds.hpp
Member Enumeration Documentation
enum Acts::RadialBounds::BoundValues
Enumerator:
eMinR
eMaxR
eHalfPhiSector
eAveragePhi
eSize
Definition at line 29 of file RadialBounds.hpp.
View newest version in sPHENIX GitHub at line 29 of file RadialBounds.hpp
Constructor & Destructor Documentation
Acts::RadialBounds::RadialBounds () delete
Acts::RadialBounds::RadialBounds (double minR, double maxR, double halfPhi = M_PI, double avgPhi = 0.) inline noexcept
Constructor for full disc of symmetric disc around phi=0
Parameters
minR The inner radius (0 for full disc)
maxR The outer radius
halfPhi The half opening angle (Pi for full angular coverage)
avgPhi The average phi for the disc/ring sector
Definition at line 45 of file RadialBounds.hpp.
View newest version in sPHENIX GitHub at line 45 of file RadialBounds.hpp
References maxR, and minR.
Acts::RadialBounds::RadialBounds (const std::array< double, eSize > & values) inline noexcept
Constructor from array values
Parameters
values The bound values
Definition at line 54 of file RadialBounds.hpp.
View newest version in sPHENIX GitHub at line 54 of file RadialBounds.hpp
References checkConsistency().
Acts::RadialBounds::~RadialBounds () override default
Member Function Documentation
double Acts::RadialBounds::binningValuePhi () const inline final virtual
Return a reference radius for binning.
Implements Acts::DiscBounds.
Definition at line 151 of file RadialBounds.hpp.
View newest version in sPHENIX GitHub at line 151 of file RadialBounds.hpp
References eAveragePhi.
double Acts::RadialBounds::binningValueR () const inline final virtual
Return a reference radius for binning.
Implements Acts::DiscBounds.
Definition at line 147 of file RadialBounds.hpp.
View newest version in sPHENIX GitHub at line 147 of file RadialBounds.hpp
References eMaxR, and eMinR.
void Acts::RadialBounds::checkConsistency () inline private noexcept
Check the input values for consistency, will throw a logic_exception if consistency is not given
Definition at line 161 of file RadialBounds.hpp.
View newest version in sPHENIX GitHub at line 161 of file RadialBounds.hpp
References eAveragePhi, eHalfPhiSector, eMaxR, eMinR, M_PI, and Acts::detail::radian_sym().
Referenced by RadialBounds().
bool Acts::RadialBounds::coversFullAzimuth () const inline final virtual
Returns true for full phi coverage.
Implements Acts::DiscBounds.
Definition at line 139 of file RadialBounds.hpp.
View newest version in sPHENIX GitHub at line 139 of file RadialBounds.hpp
References eHalfPhiSector, and M_PI.
double Acts::RadialBounds::get (BoundValues bValue) const inline
Access to the bound values
Parameters
bValue the class nested enum for the array access
Definition at line 90 of file RadialBounds.hpp.
View newest version in sPHENIX GitHub at line 90 of file RadialBounds.hpp
References m_values.
Referenced by Acts::adjustBinUtility(), Acts::Test::BOOST_AUTO_TEST_CASE(), and Acts::JsonGeometryConverter::DefaultBin().
bool Acts::RadialBounds::inside (const Vector2D & lposition, const BoundaryCheck & bcheck) const final virtual
For disc surfaces the local position in (r,phi) is checked
Parameters
lposition local position to be checked
bcheck boundary check directive
Returns
is a boolean indicating the operation success
Implements Acts::SurfaceBounds.
Definition at line 31 of file RadialBounds.cpp.
View newest version in sPHENIX GitHub at line 31 of file RadialBounds.cpp
References Acts::BoundaryCheck::isInside().
Referenced by Acts::Test::BOOST_AUTO_TEST_CASE().
bool Acts::RadialBounds::insideRadialBounds (double R, double tolerance = 0.) const inline final virtual
Checks if this is inside the radial coverage given the a tolerance
Implements Acts::DiscBounds.
Definition at line 143 of file RadialBounds.hpp.
View newest version in sPHENIX GitHub at line 143 of file RadialBounds.hpp
References eMaxR, and eMinR.
double Acts::RadialBounds::rMax () const inline final virtual
Return method for outer Radius.
Implements Acts::DiscBounds.
Definition at line 135 of file RadialBounds.hpp.
View newest version in sPHENIX GitHub at line 135 of file RadialBounds.hpp
References eMaxR.
Referenced by Acts::JsonGeometryConverter::addSurfaceToJson(), Acts::CylinderVolumeBuilder::analyzeContent(), Acts::JsonGeometryConverter::DefaultBin(), Acts::CylinderVolumeHelper::estimateAndCheckDimension(), and ActsExamples::RootMaterialTrackWriter::writeT().
double Acts::RadialBounds::rMin () const inline final virtual
Return method for inner Radius.
Implements Acts::DiscBounds.
Definition at line 131 of file RadialBounds.hpp.
View newest version in sPHENIX GitHub at line 131 of file RadialBounds.hpp
References eMinR.
Referenced by Acts::JsonGeometryConverter::addSurfaceToJson(), Acts::CylinderVolumeBuilder::analyzeContent(), Acts::JsonGeometryConverter::DefaultBin(), Acts::CylinderVolumeHelper::estimateAndCheckDimension(), and ActsExamples::RootMaterialTrackWriter::writeT().
Acts::Vector2D Acts::RadialBounds::shifted (const Vector2D & lposition) const private
Private helper method to shift a local position within the bounds
Parameters
lposition The local position in polar coordinates
Definition at line 22 of file RadialBounds.cpp.
View newest version in sPHENIX GitHub at line 22 of file RadialBounds.cpp
References Acts::eBoundLoc0, Acts::eBoundLoc1, and Acts::detail::radian_sym().
std::ostream & Acts::RadialBounds::toStream (std::ostream & sl) const final virtual
Outstream operator
Parameters
sl is the ostream to be dumped into
Implements Acts::SurfaceBounds.
Definition at line 44 of file RadialBounds.cpp.
View newest version in sPHENIX GitHub at line 44 of file RadialBounds.cpp
Referenced by Acts::Test::BOOST_AUTO_TEST_CASE().
Acts::SurfaceBounds::BoundsType Acts::RadialBounds::type () const final virtual
Return the bounds type - for persistency optimization
Returns
is a BoundsType enum
Implements Acts::SurfaceBounds.
Definition at line 18 of file RadialBounds.cpp.
View newest version in sPHENIX GitHub at line 18 of file RadialBounds.cpp
References Acts::SurfaceBounds::eDisc.
Referenced by Acts::Test::BOOST_AUTO_TEST_CASE().
std::vector< double > Acts::RadialBounds::values () const inline final virtual
Return the bound values as dynamically sized vector
Returns
this returns a copy of the internal values
Implements Acts::SurfaceBounds.
Definition at line 155 of file RadialBounds.hpp.
View newest version in sPHENIX GitHub at line 155 of file RadialBounds.hpp
References m_values.
Referenced by Acts::Test::BOOST_AUTO_TEST_CASE().
std::vector< Acts::Vector2D > Acts::RadialBounds::vertices (unsigned int lseg) const final private virtual
This method returns the xy coordinates of vertices along the radial bounds
Parameters
lseg the number of segments used to approximate and eventually curved line
Note
that the extremas are given, which may slightly alter the number of segments returned
Returns
vector for vertices in 2D
Implements Acts::DiscBounds.
Definition at line 38 of file RadialBounds.cpp.
View newest version in sPHENIX GitHub at line 38 of file RadialBounds.cpp
References Acts::detail::VerticesHelper::circularVertices().
Member Data Documentation
std::array<double, eSize> Acts::RadialBounds::m_values private
Definition at line 106 of file RadialBounds.hpp.
View newest version in sPHENIX GitHub at line 106 of file RadialBounds.hpp
Referenced by get(), and values().
The documentation for this class was generated from the following files:
acts/blob/sPHENIX/Core/include/Acts/Surfaces/RadialBounds.hpp
acts/blob/sPHENIX/Core/src/Surfaces/RadialBounds.cpp