Analysis Software: INTTVtxZ Namespace Reference
INTTVtxZ Namespace Reference
Functions
def Draw_1Dhist_fitGaussian
def Draw_HistGraph
def Draw_1DEff
def Draw_1DEffComp
def Draw_2Dhist_eff
Variables
float TickSize 0.03
float AxisTitleSize 0.05
float AxisLabelSize 0.04
float LeftMargin 0.15
float RightMargin 0.08
float TopMargin 0.08
float BottomMargin 0.13
tuple parser OptionParser(usage="usage: %prog ver [options -h]")
infiledir opt.infiledir
outdirprefix opt.outdirprefix
tuple dphi float(opt.dphi)
tuple dca float(opt.dca)
string dphitext '{:.3f}'
string dcadtext '{:.3f}'
string plotpath './RecoPV_ana/'
string fname '{}/dphi{}deg_dca{}cm/INTTVtxZ.root'
tuple df ROOT.RDataFrame('minitree', fname)
tuple nparr_NClusInner df.AsNumpy(columns=['NClusLayer1'])
list NclusInner_percentile []
list Binedge_NclusInner_percentile [0]
list NclusInner_percentile_cut [0]
int NpercentileDiv 20
list l_hM_DiffVtxZ []
tuple hM_NClusInner_NtruthVtx1 TH1F('hM_NClusInner_NtruthVtx1', 'hM_NClusInner_NtruthVtx1', NpercentileDiv, np.asarray(Binedge_NclusInner_percentile))
tuple hM_NClusInner_NtruthVtx1_absdiffle5cm TH1F('hM_NClusInner_NtruthVtx1_absdiffle5cm', 'hM_NClusInner_NtruthVtx1_absdiffle5cm', NpercentileDiv, np.asarray(Binedge_NclusInner_percentile))
tuple hM_NClusInner_NtruthVtx1_absdiffle2cm TH1F('hM_NClusInner_NtruthVtx1_absdiffle2cm', 'hM_NClusInner_NtruthVtx1_absdiffle2cm', NpercentileDiv, np.asarray(Binedge_NclusInner_percentile))
tuple hM_NClusInner_NtruthVtx1_absdiffle1cm TH1F('hM_NClusInner_NtruthVtx1_absdiffle1cm', 'hM_NClusInner_NtruthVtx1_absdiffle1cm', NpercentileDiv, np.asarray(Binedge_NclusInner_percentile))
tuple hM_Centrality_NtruthVtx1 TH1F('hM_Centrality_NtruthVtx1', 'hM_Centrality_NtruthVtx1', 10, 0, 10)
tuple hM_Centrality_NtruthVtx1_absdiffle5cm TH1F('hM_Centrality_NtruthVtx1_absdiffle5cm', 'hM_Centrality_NtruthVtx1_absdiffle5cm', 10, 0, 10)
tuple hM_Centrality_NtruthVtx1_absdiffle2cm TH1F('hM_Centrality_NtruthVtx1_absdiffle2cm', 'hM_Centrality_NtruthVtx1_absdiffle2cm', 10, 0, 10)
tuple hM_Centrality_NtruthVtx1_absdiffle1cm TH1F('hM_Centrality_NtruthVtx1_absdiffle1cm', 'hM_Centrality_NtruthVtx1_absdiffle1cm', 10, 0, 10)
tuple hM_NClusInner_TruthPVz_NtruthVtx1 TH2F('hM_NClusInner_TruthPVz_NtruthVtx1', 'hM_NClusInner_TruthPVz_NtruthVtx1', NpercentileDiv, np.asarray(Binedge_NclusInner_percentile), 20, -45, 5)
tuple hM_NClusInner_TruthPVz_NtruthVtx1_absdiffle5cm TH2F('hM_NClusInner_TruthPVz_NtruthVtx1_absdiffle5cm', 'hM_NClusInner_TruthPVz_NtruthVtx1_absdiffle5cm', NpercentileDiv, np.asarray(Binedge_NclusInner_percentile), 20, -45, 5)
tuple hM_NClusInner_TruthPVz_NtruthVtx1_absdiffle2cm TH2F('hM_NClusInner_TruthPVz_NtruthVtx1_absdiffle2cm', 'hM_NClusInner_TruthPVz_NtruthVtx1_absdiffle2cm', NpercentileDiv, np.asarray(Binedge_NclusInner_percentile), 20, -45, 5)
tuple hM_NClusInner_TruthPVz_NtruthVtx1_absdiffle1cm TH2F('hM_NClusInner_TruthPVz_NtruthVtx1_absdiffle1cm', 'hM_NClusInner_TruthPVz_NtruthVtx1_absdiffle1cm', NpercentileDiv, np.asarray(Binedge_NclusInner_percentile), 20, -45, 5)
tuple hM_Centrality_TruthPVz_NtruthVtx1 TH2F('hM_Centrality_TruthPVz_NtruthVtx1', 'hM_Centrality_TruthPVz_NtruthVtx1', 10, 0, 10, 20, -45, 5)
tuple hM_Centrality_TruthPVz_NtruthVtx1_absdiffle5cm TH2F('hM_Centrality_TruthPVz_NtruthVtx1_absdiffle5cm', 'hM_Centrality_TruthPVz_NtruthVtx1_absdiffle5cm', 10, 0, 10, 20, -45, 5)
tuple hM_Centrality_TruthPVz_NtruthVtx1_absdiffle2cm TH2F('hM_Centrality_TruthPVz_NtruthVtx1_absdiffle2cm', 'hM_Centrality_TruthPVz_NtruthVtx1_absdiffle2cm', 10, 0, 10, 20, -45, 5)
tuple hM_Centrality_TruthPVz_NtruthVtx1_absdiffle1cm TH2F('hM_Centrality_TruthPVz_NtruthVtx1_absdiffle1cm', 'hM_Centrality_TruthPVz_NtruthVtx1_absdiffle1cm', 10, 0, 10, 20, -45, 5)
tuple f TFile(fname, 'r')
tuple tree f.Get('minitree')
tuple idx int(((tree.Centrality_mbd / 5) - 1) / 2)
tuple centbin int(((tree.Centrality_mbd / 5) - 1) / 2)
list l_res_vtxZ []
list l_reserr_vtxZ []
tuple h_resolution_cent TH1F('h_resolution_cent', 'h_resolution_cent', 10, 0, 10)
tuple h_bias_cent TH1F('h_bias_cent', 'h_bias_cent', 10, 0, 10)
tuple err_RecoPVEff_NClusInner_absdiffle5cm TGraphAsymmErrors()
tuple err_RecoPVEff_NClusInner_absdiffle2cm TGraphAsymmErrors()
tuple err_RecoPVEff_NClusInner_absdiffle1cm TGraphAsymmErrors()
list list_eff_NClusInner [err_RecoPVEff_NClusInner_absdiffle5cm, err_RecoPVEff_NClusInner_absdiffle2cm, err_RecoPVEff_NClusInner_absdiffle1cm]
list list_color ['#03001C', '#035397', '#9B0000']
list list_leg ['|\Deltaz(PV_{Reco},PV_{Truth})|\leq5cm', '|\Deltaz(PV_{Reco},PV_{Truth})|\leq2cm', '|\Deltaz(PV_{Reco},PV_{Truth})|\leq1cm']
tuple err_RecoPVEff_Centrality_absdiffle5cm TGraphAsymmErrors()
tuple err_RecoPVEff_Centrality_absdiffle2cm TGraphAsymmErrors()
tuple err_RecoPVEff_Centrality_absdiffle1cm TGraphAsymmErrors()
list list_eff_Centrality [err_RecoPVEff_Centrality_absdiffle5cm, err_RecoPVEff_Centrality_absdiffle2cm, err_RecoPVEff_Centrality_absdiffle1cm]
tuple eff_RecoPVEff_NClusInner_TruthPVz_absdiffle5cm hM_NClusInner_TruthPVz_NtruthVtx1_absdiffle5cm.Clone()
tuple eff_RecoPVEff_NClusInner_TruthPVz_absdiffle2cm hM_NClusInner_TruthPVz_NtruthVtx1_absdiffle2cm.Clone()
tuple eff_RecoPVEff_NClusInner_TruthPVz_absdiffle1cm hM_NClusInner_TruthPVz_NtruthVtx1_absdiffle1cm.Clone()
tuple eff_RecoPVEff_Centrality_TruthPVz_absdiffle5cm hM_Centrality_TruthPVz_NtruthVtx1_absdiffle5cm.Clone()
tuple eff_RecoPVEff_Centrality_TruthPVz_absdiffle2cm hM_Centrality_TruthPVz_NtruthVtx1_absdiffle2cm.Clone()
tuple eff_RecoPVEff_Centrality_TruthPVz_absdiffle1cm hM_Centrality_TruthPVz_NtruthVtx1_absdiffle1cm.Clone()
Function Documentation
def INTTVtxZ.Draw_1DEff (EffErr, logx, XaxisName, axesrange, outname)
Definition at line 137 of file INTTVtxZ.py.
View newest version in sPHENIX GitHub at line 137 of file INTTVtxZ.py
References if(), and SetTitle().
def INTTVtxZ.Draw_1DEffComp (leff, lcolor, logx, XaxisName, NdivisionArg, legtext, axesrange, outname)
Definition at line 174 of file INTTVtxZ.py.
View newest version in sPHENIX GitHub at line 174 of file INTTVtxZ.py
References Draw(), Acts.enumerate(), GetXaxis(), GetYaxis(), if(), SetLineColor(), SetMarkerColor(), SetMarkerSize(), SetMarkerStyle(), and SetTitle().
def INTTVtxZ.Draw_1Dhist_fitGaussian (hist, norm1, logy, ymaxscale, XaxisName, Ytitle_unit, outname)
Definition at line 26 of file INTTVtxZ.py.
View newest version in sPHENIX GitHub at line 26 of file INTTVtxZ.py
References material_mapping_optimisation.format, if(), and SetTitle().
def INTTVtxZ.Draw_2Dhist_eff (hist, logx, logy, logz, norm1, rmargin, XaxisName, YaxisName, drawopt, outname)
Definition at line 227 of file INTTVtxZ.py.
View newest version in sPHENIX GitHub at line 227 of file INTTVtxZ.py
References if(), and SetTitle().
def INTTVtxZ.Draw_HistGraph (h, xaxistitle, yaxistitle, yaxisrange, xaxisbinlabel, outname)
Definition at line 104 of file INTTVtxZ.py.
View newest version in sPHENIX GitHub at line 104 of file INTTVtxZ.py
References if(), and SetTitle().
Variable Documentation
float INTTVtxZ.AxisLabelSize 0.04
Definition at line 19 of file INTTVtxZ.py.
View newest version in sPHENIX GitHub at line 19 of file INTTVtxZ.py
float INTTVtxZ.AxisTitleSize 0.05
Definition at line 18 of file INTTVtxZ.py.
View newest version in sPHENIX GitHub at line 18 of file INTTVtxZ.py
list INTTVtxZ.Binedge_NclusInner_percentile [0]
Definition at line 299 of file INTTVtxZ.py.
View newest version in sPHENIX GitHub at line 299 of file INTTVtxZ.py
float INTTVtxZ.BottomMargin 0.13
Definition at line 23 of file INTTVtxZ.py.
View newest version in sPHENIX GitHub at line 23 of file INTTVtxZ.py
tuple INTTVtxZ.centbin int(((tree.Centrality_mbd / 5) - 1) / 2)
Definition at line 355 of file INTTVtxZ.py.
View newest version in sPHENIX GitHub at line 355 of file INTTVtxZ.py
Referenced by PairMaker.MakeMixedPairs(), and PairMaker.process_event_test().
tuple INTTVtxZ.dca float(opt.dca)
Definition at line 285 of file INTTVtxZ.py.
View newest version in sPHENIX GitHub at line 285 of file INTTVtxZ.py
Referenced by TrackFitUtils.addClusters(), TrackFitUtils.addClustersOnLine(), PHSimpleVertexFinder.dcaTwoLines(), EMCalCalib.eval_photon(), EMCalAna.eval_trk(), PHSimpleVertexFinder.findDcaTwoTracks(), main(), FilterEvents.process_event(), TpcDirectLaserReconstruction.process_track(), SvtxTrack_v1.set_dca(), SvtxTrack_v2.set_dca(), SvtxTrack_v3.set_dca(), HelicalFitter.set_dca_cut(), and KFParticle_sPHENIX.setMaximumDaughterDCA().
string INTTVtxZ.dcadtext '{:.3f}'
Definition at line 287 of file INTTVtxZ.py.
View newest version in sPHENIX GitHub at line 287 of file INTTVtxZ.py
tuple INTTVtxZ.df ROOT.RDataFrame('minitree', fname)
Definition at line 296 of file INTTVtxZ.py.
View newest version in sPHENIX GitHub at line 296 of file INTTVtxZ.py
tuple INTTVtxZ.dphi float(opt.dphi)
Definition at line 284 of file INTTVtxZ.py.
View newest version in sPHENIX GitHub at line 284 of file INTTVtxZ.py
Referenced by LazyTiling9Alt._bj_dist(), LazyTiling9._bj_dist(), LazyTiling25._bj_dist(), ClusterSequence._bj_dist(), LazyTiling9Alt._bj_dist_not_periodic(), LazyTiling9._bj_dist_not_periodic(), LazyTiling25._bj_dist_not_periodic(), LazyTiling9._distance_to_tile(), LazyTiling25._distance_to_tile(), ALICEKF.ALICEKalmanFilter(), g4evalfn.calc_match_statistic(), ParticleFlowReco.calculate_dR(), RawClusterBuilderTopo.calculate_dR(), TrackSeed_v1.circleFitByTaubin(), cluster_resolution(), PHG4EtaPhiParameterization.ComputeDimensions(), FieldMapsLaplace.ComputeE(), cemcReco.coneSum(), PhotonJet.ConeSum(), PHG4InttDetector.ConstructIntt(), PHG4BbcDetector.ConstructMe(), PseudoJet.delta_phi_to(), DeltaPhi(), Conversion.DeltaPhi(), HFJetTruthTrigger.deltaR(), DirectPhotonPythia.deltaR(), deltaR(), TruthJetTagging.deltaR(), Tile.distance_to_bottom(), Tile.distance_to_left_bottom(), Tile.distance_to_left_top(), Tile.distance_to_right_bottom(), Tile.distance_to_right_top(), Tile.distance_to_top(), PHCosmicSeedCombiner.dphiCut(), TracksInJets.dR(), BJetModule.dR(), Draw_BDiJetImbalance(), draw_G4_bjet_truth_tagging(), draw_G4_dibjet_truth_tagging(), Acts::EventDataView3D.drawCovarianceAngular(), QAG4SimulationIntt.evaluate_clusters(), QAG4SimulationMvtx.evaluate_clusters(), QAG4SimulationTpc.evaluate_clusters(), helixResiduals.fill_residuals(), ChargeMapReader.FillChargeHistogram(), TrkrNtuplizer.fillOutputNtuples(), TrackSeed_v1.get_phi(), RawTowerGeomContainer_Cylinderv1.get_phibin(), PHG4TpcDistortion.get_x_distortion_cartesian(), PHG4TpcDistortion.get_y_distortion_cartesian(), PHCosmicsTrkFitter.getCharge(), TrackProjectionTools.getCluster(), PHActsTrackProjection.getClusterProperties(), TrackSeedTrackMapConverter.getCosmicCharge(), PHG4MvtxSupport.GetEndWheelSideN(), PHG4MvtxSupport.GetEndWheelSideS(), PhotonJet.GetRecoHadronsAndJets(), PhotonJet.GetRecoHadronsAndJetsAA(), AnaTutorial.getReconstructedJets(), AnaTutorial.getTruthJets(), Acts::AnnulusBounds.inside(), isIso(), PseudoJet.kt_distance(), main(), PHActsKDTreeSeeding.matchInttClusters(), PHActsSiliconSeeding.matchInttClusters(), MatchJets(), TrkrClusterIsMatcher.operator()(), SW_PhiRange.pass(), PseudoJet.plain_distance(), plot_residuals(), TpcPrototypeClusterizer.process_event(), PHCosmicSeedCombiner.process_event(), ParticleFlowReco.process_event(), CaloTriggerSim.process_event(), DetermineTowerBackground.process_event(), PHGenFitTrackProjection.process_event(), PhotonJet.process_event(), AnaMvtxTelescopeHits.process_event(), PHTpcCentralMembraneClusterizer.process_event(), jetrtrack.process_event(), analysis.process_event(), BDiJetModule.process_event(), RandomConeAna.process_event(), PHTpcCentralMembraneMatcher.process_event(), PHSimpleKFProp.PropagateTrack(), ChargeMapReader.RegenerateCharge(), ChargeMapReader.RegenerateDensity(), VtxRegressor.regress(), SvtxTrack_v1.set_cal_dphi(), SvtxTrack_v2.set_cal_dphi(), SvtxTrack_v3.set_cal_dphi(), sPHElectronv1.set_dphi(), PHG4TpcCylinderGeom.set_phi_bias(), PHG4HcalPrototypeDetector.SetInnerHcalDPhi(), PHG4HcalPrototypeDetector.SetOuterHcalDPhi(), test_surface(), testCuts(), TrackCaloDist(), and VtxRegressor.VtxRegressor().
string INTTVtxZ.dphitext '{:.3f}'
Definition at line 286 of file INTTVtxZ.py.
View newest version in sPHENIX GitHub at line 286 of file INTTVtxZ.py
tuple INTTVtxZ.eff_RecoPVEff_Centrality_TruthPVz_absdiffle1cm hM_Centrality_TruthPVz_NtruthVtx1_absdiffle1cm.Clone()
Definition at line 435 of file INTTVtxZ.py.
View newest version in sPHENIX GitHub at line 435 of file INTTVtxZ.py
tuple INTTVtxZ.eff_RecoPVEff_Centrality_TruthPVz_absdiffle2cm hM_Centrality_TruthPVz_NtruthVtx1_absdiffle2cm.Clone()
Definition at line 433 of file INTTVtxZ.py.
View newest version in sPHENIX GitHub at line 433 of file INTTVtxZ.py
tuple INTTVtxZ.eff_RecoPVEff_Centrality_TruthPVz_absdiffle5cm hM_Centrality_TruthPVz_NtruthVtx1_absdiffle5cm.Clone()
Definition at line 431 of file INTTVtxZ.py.
View newest version in sPHENIX GitHub at line 431 of file INTTVtxZ.py
tuple INTTVtxZ.eff_RecoPVEff_NClusInner_TruthPVz_absdiffle1cm hM_NClusInner_TruthPVz_NtruthVtx1_absdiffle1cm.Clone()
Definition at line 424 of file INTTVtxZ.py.
View newest version in sPHENIX GitHub at line 424 of file INTTVtxZ.py
tuple INTTVtxZ.eff_RecoPVEff_NClusInner_TruthPVz_absdiffle2cm hM_NClusInner_TruthPVz_NtruthVtx1_absdiffle2cm.Clone()
Definition at line 422 of file INTTVtxZ.py.
View newest version in sPHENIX GitHub at line 422 of file INTTVtxZ.py
tuple INTTVtxZ.eff_RecoPVEff_NClusInner_TruthPVz_absdiffle5cm hM_NClusInner_TruthPVz_NtruthVtx1_absdiffle5cm.Clone()
Definition at line 420 of file INTTVtxZ.py.
View newest version in sPHENIX GitHub at line 420 of file INTTVtxZ.py
tuple INTTVtxZ.err_RecoPVEff_Centrality_absdiffle1cm TGraphAsymmErrors()
Definition at line 414 of file INTTVtxZ.py.
View newest version in sPHENIX GitHub at line 414 of file INTTVtxZ.py
tuple INTTVtxZ.err_RecoPVEff_Centrality_absdiffle2cm TGraphAsymmErrors()
Definition at line 412 of file INTTVtxZ.py.
View newest version in sPHENIX GitHub at line 412 of file INTTVtxZ.py
tuple INTTVtxZ.err_RecoPVEff_Centrality_absdiffle5cm TGraphAsymmErrors()
Definition at line 409 of file INTTVtxZ.py.
View newest version in sPHENIX GitHub at line 409 of file INTTVtxZ.py
tuple INTTVtxZ.err_RecoPVEff_NClusInner_absdiffle1cm TGraphAsymmErrors()
Definition at line 402 of file INTTVtxZ.py.
View newest version in sPHENIX GitHub at line 402 of file INTTVtxZ.py
tuple INTTVtxZ.err_RecoPVEff_NClusInner_absdiffle2cm TGraphAsymmErrors()
Definition at line 400 of file INTTVtxZ.py.
View newest version in sPHENIX GitHub at line 400 of file INTTVtxZ.py
tuple INTTVtxZ.err_RecoPVEff_NClusInner_absdiffle5cm TGraphAsymmErrors()
Definition at line 398 of file INTTVtxZ.py.
View newest version in sPHENIX GitHub at line 398 of file INTTVtxZ.py
tuple INTTVtxZ.f TFile(fname, 'r')
Definition at line 340 of file INTTVtxZ.py.
View newest version in sPHENIX GitHub at line 340 of file INTTVtxZ.py
string INTTVtxZ.fname '{}/dphi{}deg_dca{}cm/INTTVtxZ.root'
Definition at line 293 of file INTTVtxZ.py.
View newest version in sPHENIX GitHub at line 293 of file INTTVtxZ.py
Referenced by PHG4GDMLWrite.AddModule(), Acts::Test.BOOST_AUTO_TEST_CASE(), CBfitter_jpsi_1state(), hLabHelper.decoderun(), Draw(), Draw_hotmap(), dst_simple_towerslope_runmacro(), EdepPercentSmall(), EdepSmall(), evaluate_cluster_track_matching(), Fun4AllPrdfInputManager.fileopen(), Fun4AllOscarInputManager.fileopen(), SinglePrdfInput.fileopen(), SingleStreamingInput.fileopen(), Fun4AllHepMCInputManager.fileopen(), Fun4All_Calo(), Fun4All_CaloAna(), Fun4All_CaloProduction(), Fun4All_CaloProduction_PreQM23(), Fun4All_CaloWaveFormSim(), Fun4All_EMCal_Hist(), Fun4All_EMCal_sp(), Fun4All_FillChargesMap_300evts_MDC2(), Fun4All_FillDCMap(), Fun4All_HCalCalib(), Fun4All_Templates(), Fun4All_Year1(), G4TTree(), get_alignment(), hLabHelper.getFileLists(), GetOnePlot(), Hijing(), RawClusterBuilderTemplate.InitRun(), MakeOnePlot(), Neutrals(), newplotbg_dAu_vscent_2022(), newplotbg_vscent_2022(), DumpObject.OpenOutFile(), Fun4AllMonitoring.OutFileName(), Fun4AllMonitoring.PrintsMaps(), RecoInfoExport.process_event(), quarkonia_reconstruction_embedded(), Read(), MvtxAlign.ReadAlignmentParFile(), MvtxPrototype2Align.ReadAlignmentParFile(), PHParameters.ReadFromFile(), MbdEvent.ReadSyncFile(), RecalibratorMakeOnePlot(), run(), runpairs(), hLabHelper.runToPRDFFile(), hLabHelper.runToRootFile(), PHPythia6.save_ascii(), HcalRawTowerBuilder.set_decal_filename(), showsig(), ShSizeHist(), ShSizePrep(), TPCHitTrackDisplay.SimulationOut(), PHG4GDMLWriteSolids.TessellatedWrite(), TestCDBHistos(), TestCDBTTree(), TestWrite(), ThreeGraphs(), TMVA_D0_D0bar(), towerslope_dst_runner(), tree2csv(), tsdst_plus_tsfit(), upsilon_raa_sphenix_estimator(), wholeIter_Pi0EtaByEta(), PHParametersContainer.WriteToFile(), PdbParameterMapContainer.WriteToFile(), and PHParameters.WriteToFile().
tuple INTTVtxZ.h_bias_cent TH1F('h_bias_cent', 'h_bias_cent', 10, 0, 10)
Definition at line 384 of file INTTVtxZ.py.
View newest version in sPHENIX GitHub at line 384 of file INTTVtxZ.py
tuple INTTVtxZ.h_resolution_cent TH1F('h_resolution_cent', 'h_resolution_cent', 10, 0, 10)
Definition at line 383 of file INTTVtxZ.py.
View newest version in sPHENIX GitHub at line 383 of file INTTVtxZ.py
tuple INTTVtxZ.hM_Centrality_NtruthVtx1 TH1F('hM_Centrality_NtruthVtx1', 'hM_Centrality_NtruthVtx1', 10, 0, 10)
Definition at line 326 of file INTTVtxZ.py.
View newest version in sPHENIX GitHub at line 326 of file INTTVtxZ.py
tuple INTTVtxZ.hM_Centrality_NtruthVtx1_absdiffle1cm TH1F('hM_Centrality_NtruthVtx1_absdiffle1cm', 'hM_Centrality_NtruthVtx1_absdiffle1cm', 10, 0, 10)
Definition at line 329 of file INTTVtxZ.py.
View newest version in sPHENIX GitHub at line 329 of file INTTVtxZ.py
tuple INTTVtxZ.hM_Centrality_NtruthVtx1_absdiffle2cm TH1F('hM_Centrality_NtruthVtx1_absdiffle2cm', 'hM_Centrality_NtruthVtx1_absdiffle2cm', 10, 0, 10)
Definition at line 328 of file INTTVtxZ.py.
View newest version in sPHENIX GitHub at line 328 of file INTTVtxZ.py
tuple INTTVtxZ.hM_Centrality_NtruthVtx1_absdiffle5cm TH1F('hM_Centrality_NtruthVtx1_absdiffle5cm', 'hM_Centrality_NtruthVtx1_absdiffle5cm', 10, 0, 10)
Definition at line 327 of file INTTVtxZ.py.
View newest version in sPHENIX GitHub at line 327 of file INTTVtxZ.py
tuple INTTVtxZ.hM_Centrality_TruthPVz_NtruthVtx1 TH2F('hM_Centrality_TruthPVz_NtruthVtx1', 'hM_Centrality_TruthPVz_NtruthVtx1', 10, 0, 10, 20, -45, 5)
Definition at line 334 of file INTTVtxZ.py.
View newest version in sPHENIX GitHub at line 334 of file INTTVtxZ.py
tuple INTTVtxZ.hM_Centrality_TruthPVz_NtruthVtx1_absdiffle1cm TH2F('hM_Centrality_TruthPVz_NtruthVtx1_absdiffle1cm', 'hM_Centrality_TruthPVz_NtruthVtx1_absdiffle1cm', 10, 0, 10, 20, -45, 5)
Definition at line 337 of file INTTVtxZ.py.
View newest version in sPHENIX GitHub at line 337 of file INTTVtxZ.py
tuple INTTVtxZ.hM_Centrality_TruthPVz_NtruthVtx1_absdiffle2cm TH2F('hM_Centrality_TruthPVz_NtruthVtx1_absdiffle2cm', 'hM_Centrality_TruthPVz_NtruthVtx1_absdiffle2cm', 10, 0, 10, 20, -45, 5)
Definition at line 336 of file INTTVtxZ.py.
View newest version in sPHENIX GitHub at line 336 of file INTTVtxZ.py
tuple INTTVtxZ.hM_Centrality_TruthPVz_NtruthVtx1_absdiffle5cm TH2F('hM_Centrality_TruthPVz_NtruthVtx1_absdiffle5cm', 'hM_Centrality_TruthPVz_NtruthVtx1_absdiffle5cm', 10, 0, 10, 20, -45, 5)
Definition at line 335 of file INTTVtxZ.py.
View newest version in sPHENIX GitHub at line 335 of file INTTVtxZ.py
tuple INTTVtxZ.hM_NClusInner_NtruthVtx1 TH1F('hM_NClusInner_NtruthVtx1', 'hM_NClusInner_NtruthVtx1', NpercentileDiv, np.asarray(Binedge_NclusInner_percentile))
Definition at line 322 of file INTTVtxZ.py.
View newest version in sPHENIX GitHub at line 322 of file INTTVtxZ.py
tuple INTTVtxZ.hM_NClusInner_NtruthVtx1_absdiffle1cm TH1F('hM_NClusInner_NtruthVtx1_absdiffle1cm', 'hM_NClusInner_NtruthVtx1_absdiffle1cm', NpercentileDiv, np.asarray(Binedge_NclusInner_percentile))
Definition at line 325 of file INTTVtxZ.py.
View newest version in sPHENIX GitHub at line 325 of file INTTVtxZ.py
tuple INTTVtxZ.hM_NClusInner_NtruthVtx1_absdiffle2cm TH1F('hM_NClusInner_NtruthVtx1_absdiffle2cm', 'hM_NClusInner_NtruthVtx1_absdiffle2cm', NpercentileDiv, np.asarray(Binedge_NclusInner_percentile))
Definition at line 324 of file INTTVtxZ.py.
View newest version in sPHENIX GitHub at line 324 of file INTTVtxZ.py
tuple INTTVtxZ.hM_NClusInner_NtruthVtx1_absdiffle5cm TH1F('hM_NClusInner_NtruthVtx1_absdiffle5cm', 'hM_NClusInner_NtruthVtx1_absdiffle5cm', NpercentileDiv, np.asarray(Binedge_NclusInner_percentile))
Definition at line 323 of file INTTVtxZ.py.
View newest version in sPHENIX GitHub at line 323 of file INTTVtxZ.py
tuple INTTVtxZ.hM_NClusInner_TruthPVz_NtruthVtx1 TH2F('hM_NClusInner_TruthPVz_NtruthVtx1', 'hM_NClusInner_TruthPVz_NtruthVtx1', NpercentileDiv, np.asarray(Binedge_NclusInner_percentile), 20, -45, 5)
Definition at line 330 of file INTTVtxZ.py.
View newest version in sPHENIX GitHub at line 330 of file INTTVtxZ.py
tuple INTTVtxZ.hM_NClusInner_TruthPVz_NtruthVtx1_absdiffle1cm TH2F('hM_NClusInner_TruthPVz_NtruthVtx1_absdiffle1cm', 'hM_NClusInner_TruthPVz_NtruthVtx1_absdiffle1cm', NpercentileDiv, np.asarray(Binedge_NclusInner_percentile), 20, -45, 5)
Definition at line 333 of file INTTVtxZ.py.
View newest version in sPHENIX GitHub at line 333 of file INTTVtxZ.py
tuple INTTVtxZ.hM_NClusInner_TruthPVz_NtruthVtx1_absdiffle2cm TH2F('hM_NClusInner_TruthPVz_NtruthVtx1_absdiffle2cm', 'hM_NClusInner_TruthPVz_NtruthVtx1_absdiffle2cm', NpercentileDiv, np.asarray(Binedge_NclusInner_percentile), 20, -45, 5)
Definition at line 332 of file INTTVtxZ.py.
View newest version in sPHENIX GitHub at line 332 of file INTTVtxZ.py
tuple INTTVtxZ.hM_NClusInner_TruthPVz_NtruthVtx1_absdiffle5cm TH2F('hM_NClusInner_TruthPVz_NtruthVtx1_absdiffle5cm', 'hM_NClusInner_TruthPVz_NtruthVtx1_absdiffle5cm', NpercentileDiv, np.asarray(Binedge_NclusInner_percentile), 20, -45, 5)
Definition at line 331 of file INTTVtxZ.py.
View newest version in sPHENIX GitHub at line 331 of file INTTVtxZ.py
tuple INTTVtxZ.idx int(((tree.Centrality_mbd / 5) - 1) / 2)
Definition at line 345 of file INTTVtxZ.py.
View newest version in sPHENIX GitHub at line 345 of file INTTVtxZ.py
INTTVtxZ.infiledir opt.infiledir
Definition at line 282 of file INTTVtxZ.py.
View newest version in sPHENIX GitHub at line 282 of file INTTVtxZ.py
list INTTVtxZ.l_hM_DiffVtxZ []
Definition at line 312 of file INTTVtxZ.py.
View newest version in sPHENIX GitHub at line 312 of file INTTVtxZ.py
list INTTVtxZ.l_res_vtxZ []
Definition at line 381 of file INTTVtxZ.py.
View newest version in sPHENIX GitHub at line 381 of file INTTVtxZ.py
list INTTVtxZ.l_reserr_vtxZ []
Definition at line 382 of file INTTVtxZ.py.
View newest version in sPHENIX GitHub at line 382 of file INTTVtxZ.py
float INTTVtxZ.LeftMargin 0.15
Definition at line 20 of file INTTVtxZ.py.
View newest version in sPHENIX GitHub at line 20 of file INTTVtxZ.py
list INTTVtxZ.list_color ['#03001C', '#035397', '#9B0000']
Definition at line 405 of file INTTVtxZ.py.
View newest version in sPHENIX GitHub at line 405 of file INTTVtxZ.py
list INTTVtxZ.list_eff_Centrality [err_RecoPVEff_Centrality_absdiffle5cm, err_RecoPVEff_Centrality_absdiffle2cm, err_RecoPVEff_Centrality_absdiffle1cm]
Definition at line 416 of file INTTVtxZ.py.
View newest version in sPHENIX GitHub at line 416 of file INTTVtxZ.py
list INTTVtxZ.list_eff_NClusInner [err_RecoPVEff_NClusInner_absdiffle5cm, err_RecoPVEff_NClusInner_absdiffle2cm, err_RecoPVEff_NClusInner_absdiffle1cm]
Definition at line 404 of file INTTVtxZ.py.
View newest version in sPHENIX GitHub at line 404 of file INTTVtxZ.py
list INTTVtxZ.list_leg ['|\Deltaz(PV_{Reco},PV_{Truth})|\leq5cm', '|\Deltaz(PV_{Reco},PV_{Truth})|\leq2cm', '|\Deltaz(PV_{Reco},PV_{Truth})|\leq1cm']
Definition at line 406 of file INTTVtxZ.py.
View newest version in sPHENIX GitHub at line 406 of file INTTVtxZ.py
list INTTVtxZ.NclusInner_percentile []
Definition at line 298 of file INTTVtxZ.py.
View newest version in sPHENIX GitHub at line 298 of file INTTVtxZ.py
list INTTVtxZ.NclusInner_percentile_cut [0]
Definition at line 300 of file INTTVtxZ.py.
View newest version in sPHENIX GitHub at line 300 of file INTTVtxZ.py
tuple INTTVtxZ.nparr_NClusInner df.AsNumpy(columns=['NClusLayer1'])
Definition at line 297 of file INTTVtxZ.py.
View newest version in sPHENIX GitHub at line 297 of file INTTVtxZ.py
int INTTVtxZ.NpercentileDiv 20
Definition at line 301 of file INTTVtxZ.py.
View newest version in sPHENIX GitHub at line 301 of file INTTVtxZ.py
INTTVtxZ.outdirprefix opt.outdirprefix
Definition at line 283 of file INTTVtxZ.py.
View newest version in sPHENIX GitHub at line 283 of file INTTVtxZ.py
tuple INTTVtxZ.parser OptionParser(usage="usage: %prog ver [options -h]")
Definition at line 273 of file INTTVtxZ.py.
View newest version in sPHENIX GitHub at line 273 of file INTTVtxZ.py
string INTTVtxZ.plotpath './RecoPV_ana/'
Definition at line 289 of file INTTVtxZ.py.
View newest version in sPHENIX GitHub at line 289 of file INTTVtxZ.py
float INTTVtxZ.RightMargin 0.08
Definition at line 21 of file INTTVtxZ.py.
View newest version in sPHENIX GitHub at line 21 of file INTTVtxZ.py
float INTTVtxZ.TickSize 0.03
Definition at line 17 of file INTTVtxZ.py.
View newest version in sPHENIX GitHub at line 17 of file INTTVtxZ.py
float INTTVtxZ.TopMargin 0.08
Definition at line 22 of file INTTVtxZ.py.
View newest version in sPHENIX GitHub at line 22 of file INTTVtxZ.py
tuple INTTVtxZ.tree f.Get('minitree')
Definition at line 341 of file INTTVtxZ.py.
View newest version in sPHENIX GitHub at line 341 of file INTTVtxZ.py