Analysis Software: Acts::Test::CubicTrackingGeometry Struct Reference
Acts::Test::CubicTrackingGeometry Struct Reference
#include <acts/blob/sPHENIX/Tests/CommonHelpers/Acts/Tests/CommonHelpers/CubicTrackingGeometry.hpp>
Public Member Functions
CubicTrackingGeometry (const GeometryContext &gctx)
std::shared_ptr< const
TrackingGeometry > operator() ()
Call operator to build the standard cubic tracking geometry.
Public Attributes
RotationMatrix3 rotation = RotationMatrix3::Identity()
std::shared_ptr< const
RectangleBounds > rBounds = nullptr
std::shared_ptr< const
ISurfaceMaterial > surfaceMaterial = nullptr
std::vector< std::unique_ptr
< const DetectorElementStub > > detectorStore = {}
std::reference_wrapper< const
GeometryContext > geoContext
Detailed Description
Definition at line 40 of file CubicTrackingGeometry.hpp.
View newest version in sPHENIX GitHub at line 40 of file CubicTrackingGeometry.hpp
Constructor & Destructor Documentation
Acts::Test::CubicTrackingGeometry::CubicTrackingGeometry (const GeometryContext & gctx) inline
Default constructor for the Cubic tracking geometry
Parameters
gctx the geometry context for this geometry at building time
Definition at line 44 of file CubicTrackingGeometry.hpp.
View newest version in sPHENIX GitHub at line 44 of file CubicTrackingGeometry.hpp
References Acts::Test::makeBeryllium(), rBounds, rotation, and surfaceMaterial.
Member Function Documentation
std::shared_ptr<const TrackingGeometry> Acts::Test::CubicTrackingGeometry::operator() () inline
Call operator to build the standard cubic tracking geometry.
Definition at line 66 of file CubicTrackingGeometry.hpp.
View newest version in sPHENIX GitHub at line 66 of file CubicTrackingGeometry.hpp
References Acts::arbitrary, Acts::Surface::associateLayer(), Acts::binX, Acts::PlaneLayer::create(), Acts::TrackingVolume::create(), detectorStore, Acts::Test::eps, geoContext, Acts::getDefaultLogger(), i, Acts::Logging::INFO, Acts::LayerArrayCreator::layerArray(), testing::internal::move(), Acts::negativeFaceYZ, Acts::open, Acts::positiveFaceYZ, rBounds, rotation, and surfaceMaterial.
Member Data Documentation
std::vector<std::unique_ptr<const DetectorElementStub> > Acts::Test::CubicTrackingGeometry::detectorStore = {}
Definition at line 205 of file CubicTrackingGeometry.hpp.
View newest version in sPHENIX GitHub at line 205 of file CubicTrackingGeometry.hpp
Referenced by operator()().
std::reference_wrapper<const GeometryContext> Acts::Test::CubicTrackingGeometry::geoContext
Definition at line 207 of file CubicTrackingGeometry.hpp.
View newest version in sPHENIX GitHub at line 207 of file CubicTrackingGeometry.hpp
Referenced by operator()().
std::shared_ptr<const RectangleBounds> Acts::Test::CubicTrackingGeometry::rBounds = nullptr
Definition at line 202 of file CubicTrackingGeometry.hpp.
View newest version in sPHENIX GitHub at line 202 of file CubicTrackingGeometry.hpp
Referenced by CubicTrackingGeometry(), and operator()().
RotationMatrix3 Acts::Test::CubicTrackingGeometry::rotation = RotationMatrix3::Identity()
Definition at line 201 of file CubicTrackingGeometry.hpp.
View newest version in sPHENIX GitHub at line 201 of file CubicTrackingGeometry.hpp
Referenced by CubicTrackingGeometry(), and operator()().
std::shared_ptr<const ISurfaceMaterial> Acts::Test::CubicTrackingGeometry::surfaceMaterial = nullptr
Definition at line 203 of file CubicTrackingGeometry.hpp.
View newest version in sPHENIX GitHub at line 203 of file CubicTrackingGeometry.hpp
Referenced by CubicTrackingGeometry(), and operator()().
The documentation for this struct was generated from the following file:
acts/blob/sPHENIX/Tests/CommonHelpers/Acts/Tests/CommonHelpers/CubicTrackingGeometry.hpp