Analysis Software: Acts::PodioTrackStateContainerBase Class Reference
Acts::PodioTrackStateContainerBase Class Reference
#include <acts/blob/sPHENIX/Plugins/Podio/include/Acts/Plugins/Podio/PodioTrackStateContainer.hpp>
Public Types
using Parameters = typename detail_lt::Types< eBoundSize, false >::CoefficientsMap
using Covariance = typename detail_lt::Types< eBoundSize, false >::CovarianceMap
using ConstParameters = typename detail_lt::Types< eBoundSize, true >::CoefficientsMap
using ConstCovariance = typename detail_lt::Types< eBoundSize, true >::CovarianceMap
Static Protected Member Functions
template<typename T >
static constexpr bool has_impl (T &instance, HashedString key, TrackIndexType istate)
template<bool EnsureConst, typename T >
static std::any component_impl (T &instance, HashedString key, TrackIndexType istate)
template<typename T >
static constexpr bool hasColumn_impl (T &instance, HashedString key)
static void populateSurfaceBuffer (const PodioUtil::ConversionHelper &helper, const ActsPodioEdm::TrackStateCollection &collection, std::vector< std::shared_ptr< const Surface >> &surfaces) noexcept
Detailed Description
Definition at line 42 of file PodioTrackStateContainer.hpp.
View newest version in sPHENIX GitHub at line 42 of file PodioTrackStateContainer.hpp
Member Typedef Documentation
using Acts::PodioTrackStateContainerBase::ConstCovariance = typename detail_lt::Types<eBoundSize, true>::CovarianceMap
Definition at line 52 of file PodioTrackStateContainer.hpp.
View newest version in sPHENIX GitHub at line 52 of file PodioTrackStateContainer.hpp
using Acts::PodioTrackStateContainerBase::ConstParameters = typename detail_lt::Types<eBoundSize, true>::CoefficientsMap
Definition at line 50 of file PodioTrackStateContainer.hpp.
View newest version in sPHENIX GitHub at line 50 of file PodioTrackStateContainer.hpp
using Acts::PodioTrackStateContainerBase::Covariance = typename detail_lt::Types<eBoundSize, false>::CovarianceMap
Definition at line 47 of file PodioTrackStateContainer.hpp.
View newest version in sPHENIX GitHub at line 47 of file PodioTrackStateContainer.hpp
using Acts::PodioTrackStateContainerBase::Parameters = typename detail_lt::Types<eBoundSize, false>::CoefficientsMap
Definition at line 45 of file PodioTrackStateContainer.hpp.
View newest version in sPHENIX GitHub at line 45 of file PodioTrackStateContainer.hpp
Member Function Documentation
template<bool EnsureConst, typename T > static std::any Acts::PodioTrackStateContainerBase::component_impl (T & instance, HashedString key, TrackIndexType istate) inline static protected
Definition at line 94 of file PodioTrackStateContainer.hpp.
View newest version in sPHENIX GitHub at line 94 of file PodioTrackStateContainer.hpp
References assert, col, configureMap::data, and it.
template<typename T > static constexpr bool Acts::PodioTrackStateContainerBase::has_impl (T & instance, HashedString key, TrackIndexType istate) inline static protected
Definition at line 56 of file PodioTrackStateContainer.hpp.
View newest version in sPHENIX GitHub at line 56 of file PodioTrackStateContainer.hpp
References configureMap::data, Acts::MultiTrajectoryTraits::kInvalid, and Acts::PodioUtil::kNoIdentifier.
Referenced by Acts::MutablePodioTrackStateContainer::has_impl().
template<typename T > static constexpr bool Acts::PodioTrackStateContainerBase::hasColumn_impl (T & instance, HashedString key) inline static protected
Definition at line 145 of file PodioTrackStateContainer.hpp.
View newest version in sPHENIX GitHub at line 145 of file PodioTrackStateContainer.hpp
Referenced by Acts::MutablePodioTrackStateContainer::hasColumn_impl().
static void Acts::PodioTrackStateContainerBase::populateSurfaceBuffer (const PodioUtil::ConversionHelper & helper, const ActsPodioEdm::TrackStateCollection & collection, std::vector< std::shared_ptr< const Surface >> & surfaces) inline static protected noexcept
Definition at line 166 of file PodioTrackStateContainer.hpp.
View newest version in sPHENIX GitHub at line 166 of file PodioTrackStateContainer.hpp
References Acts::PodioUtil::convertSurfaceFromPodio().
The documentation for this class was generated from the following file:
acts/blob/sPHENIX/Plugins/Podio/include/Acts/Plugins/Podio/PodioTrackStateContainer.hpp