Analysis Software: tpc_hits Class Reference
tpc_hits Class Reference
#include <coresoftware/blob/master/offline/packages/rawtodst/tpc_hits.h>
Public Member Functions
tpc_hits (const std::string &name="tpc_hits")
~tpc_hits () override
int Init (PHCompositeNode *topNode) override
int InitRun (PHCompositeNode *topNode) override
int process_event (PHCompositeNode *topNode) override
int End (PHCompositeNode *topNode) override
Clean up internals after each event.
Public Member Functions inherited from SubsysReco
~SubsysReco () override
virtual int EndRun (const int)
Called at the end of each run.
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
void Print (const std::string &="ALL") const override
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Protected Attributes
Fun4AllHistoManager * hm = nullptr
Reset.
std::string _filename
TrkrHitSet * m_hitset [layercount] = {}
TPCMap M
int starting_BCO
int rollover_value
int current_BCOBIN
Static Protected Attributes
static const int layercount = 16
static const int layeroffset = 7 + 16
Private Attributes
TH2 * _h_hit_XY = nullptr
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = std::numeric_limits<int>::max() - 10
}
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Detailed Description
Definition at line 24 of file tpc_hits.h.
View newest version in sPHENIX GitHub at line 24 of file tpc_hits.h
Constructor & Destructor Documentation
tpc_hits::tpc_hits (const std::string & name = "tpc_hits")
Definition at line 32 of file tpc_hits.cc.
View newest version in sPHENIX GitHub at line 32 of file tpc_hits.cc
References current_BCOBIN, M, rollover_value, TPCMap::setMapNames(), and starting_BCO.
tpc_hits::~tpc_hits () override
Definition at line 45 of file tpc_hits.cc.
View newest version in sPHENIX GitHub at line 45 of file tpc_hits.cc
References hm.
Member Function Documentation
int tpc_hits::End (PHCompositeNode * topNode) override virtual
Clean up internals after each event.
Called at the end of each run. Called at the end of all processing.
Reimplemented from SubsysReco.
Definition at line 273 of file tpc_hits.cc.
View newest version in sPHENIX GitHub at line 273 of file tpc_hits.cc
References _filename, Fun4AllHistoManager::dumpHistos(), Fun4AllReturnCodes::EVENT_OK, and hm.
int tpc_hits::Init (PHCompositeNode *) override virtual
Called during initialization. Typically this is where you can book histograms, and e.g. register them to Fun4AllServer (so they can be output to file using Fun4AllServer::dumpHistos() method).
Reimplemented from SubsysReco.
Definition at line 52 of file tpc_hits.cc.
View newest version in sPHENIX GitHub at line 52 of file tpc_hits.cc
References _h_hit_XY, Fun4AllReturnCodes::EVENT_OK, hm, and Fun4AllHistoManager::registerHisto().
int tpc_hits::InitRun (PHCompositeNode * topNode) override virtual
Called for first event when run number is known. Typically this is where you may want to fetch data from database, because you know the run number. A place to book histograms which have to know the run number.
Reimplemented from SubsysReco.
Definition at line 65 of file tpc_hits.cc.
View newest version in sPHENIX GitHub at line 65 of file tpc_hits.cc
References current_BCOBIN, Fun4AllReturnCodes::EVENT_OK, PHNodeIterator::findFirst(), PHDataNode< T >::print(), rollover_value, and starting_BCO.
int tpc_hits::process_event (PHCompositeNode * topNode) override virtual
Called for each event. This is where you do the real work.
special events
Reimplemented from SubsysReco.
Definition at line 110 of file tpc_hits.cc.
View newest version in sPHENIX GitHub at line 110 of file tpc_hits.cc
References _h_hit_XY, assert, channel(), current_BCOBIN, Fun4AllReturnCodes::DISCARDEVENT, Fun4AllReturnCodes::EVENT_OK, TpcDefs::genHitKey(), TpcDefs::genHitSetKey(), Event::getEvtType(), TPCMap::getLayer(), Event::getPacket(), TPCMap::getPad(), TPCMap::getPhi(), TPCMap::getR(), Packet::iValue(), layer, M, m_hitset, merge_hashes::p, ActsTests::PropagationDatasets::phi, Acts::IntegrationTest::R, rollover_value, physmon_simulation::s, starting_BCO, t, and Fun4AllBase::Verbosity().
Member Data Documentation
std::string tpc_hits::_filename protected
Definition at line 61 of file tpc_hits.h.
View newest version in sPHENIX GitHub at line 61 of file tpc_hits.h
Referenced by End().
TH2* tpc_hits::_h_hit_XY = nullptr private
Definition at line 80 of file tpc_hits.h.
View newest version in sPHENIX GitHub at line 80 of file tpc_hits.h
Referenced by Init(), and process_event().
int tpc_hits::current_BCOBIN protected
Definition at line 76 of file tpc_hits.h.
View newest version in sPHENIX GitHub at line 76 of file tpc_hits.h
Referenced by InitRun(), process_event(), and tpc_hits().
Fun4AllHistoManager* tpc_hits::hm = nullptr protected
Reset.
Definition at line 60 of file tpc_hits.h.
View newest version in sPHENIX GitHub at line 60 of file tpc_hits.h
Referenced by End(), Init(), and ~tpc_hits().
const int tpc_hits::layercount = 16 static protected
Definition at line 63 of file tpc_hits.h.
View newest version in sPHENIX GitHub at line 63 of file tpc_hits.h
const int tpc_hits::layeroffset = 7 + 16 static protected
Definition at line 64 of file tpc_hits.h.
View newest version in sPHENIX GitHub at line 64 of file tpc_hits.h
TPCMap tpc_hits::M protected
Definition at line 72 of file tpc_hits.h.
View newest version in sPHENIX GitHub at line 72 of file tpc_hits.h
Referenced by process_event(), and tpc_hits().
TrkrHitSet* tpc_hits::m_hitset[layercount] = {} protected
Definition at line 67 of file tpc_hits.h.
View newest version in sPHENIX GitHub at line 67 of file tpc_hits.h
Referenced by process_event().
int tpc_hits::rollover_value protected
Definition at line 75 of file tpc_hits.h.
View newest version in sPHENIX GitHub at line 75 of file tpc_hits.h
Referenced by InitRun(), process_event(), and tpc_hits().
int tpc_hits::starting_BCO protected
Definition at line 74 of file tpc_hits.h.
View newest version in sPHENIX GitHub at line 74 of file tpc_hits.h
Referenced by InitRun(), process_event(), and tpc_hits().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/rawtodst/tpc_hits.h
coresoftware/blob/master/offline/packages/rawtodst/tpc_hits.cc