Analysis Software: OnlMon/blob/main/macros/ServerFuncs.C File Reference
ServerFuncs.C File Reference
#include <onlmon/OnlMonServer.h>
#include <pmonitor/pmonitor.h>
Functions
void CleanUpServer ()
void start_server (const std::string &prdffile="")
Function Documentation
void CleanUpServer ()
Definition at line 37 of file ServerFuncs.C.
View newest version in sPHENIX GitHub at line 37 of file ServerFuncs.C
References OnlMonServer::instance(), and pclose().
Referenced by start_server().
void start_server (const std::string & prdffile = "")
Definition at line 10 of file ServerFuncs.C.
View newest version in sPHENIX GitHub at line 10 of file ServerFuncs.C
References CleanUpServer(), OnlMonServer::EndRun(), OnlMonServer::instance(), pfileopen(), pidentify(), prun(), rcdaqopen(), OnlMonServer::RunNumber(), and OnlMonServer::WriteHistoFile().
Referenced by run_bbc_server(), run_cemc_server(), run_cemc_server_SEB00(), run_cemc_server_SEB01(), run_daq_server(), run_example_server0(), run_example_server1(), run_hcal_server(), run_intt_server(), run_ll1_server(), run_mvtx_server(), run_pktsize_server(), run_sepd_server(), run_tpc_server(), run_tpot_server(), and run_zdc_server().