Analysis Software: acts/blob/sPHENIX/Tests/IntegrationTests/PropagationStraightLine.cpp File Reference
PropagationStraightLine.cpp File Reference
#include <boost/test/data/test_case.hpp>
#include <boost/test/unit_test.hpp>
#include "Acts/Geometry/GeometryContext.hpp"
#include "Acts/MagneticField/MagneticFieldContext.hpp"
#include "Acts/Propagator/Propagator.hpp"
#include "Acts/Propagator/RiddersPropagator.hpp"
#include "Acts/Propagator/StraightLineStepper.hpp"
#include <limits>
#include "PropagationDatasets.hpp"
#include "PropagationTests.hpp"
Functions
BOOST_DATA_TEST_CASE (ForwardBackward, ds::phi *ds::theta *ds::absMomentum *ds::chargeNonZero *ds::pathLength, phi, theta, p, q, s)
BOOST_DATA_TEST_CASE (ToCylinderAlongZ, ds::phi *ds::thetaWithoutBeam *ds::absMomentum *ds::chargeNonZero *ds::pathLength, phi, theta, p, q, s)
BOOST_DATA_TEST_CASE (ToDisc, ds::phi *ds::theta *ds::absMomentum *ds::chargeNonZero *ds::pathLength, phi, theta, p, q, s)
BOOST_DATA_TEST_CASE (ToPlane, ds::phi *ds::theta *ds::absMomentum *ds::chargeNonZero *ds::pathLength, phi, theta, p, q, s)
BOOST_DATA_TEST_CASE (ToStrawAlongZ, ds::phi *ds::thetaWithoutBeam *ds::absMomentum *ds::chargeNonZero *ds::pathLength, phi, theta, p, q, s)
BOOST_DATA_TEST_CASE (CovarianceCurvilinear, ds::phi *ds::theta *ds::absMomentum *ds::chargeNonZero *ds::pathLength, phi, theta, p, q, s)
BOOST_DATA_TEST_CASE (CovarianceToCylinderAlongZ, ds::phiWithoutAmbiguity *ds::thetaWithoutBeam *ds::absMomentum *ds::chargeNonZero *ds::pathLength, phi, theta, p, q, s)
BOOST_DATA_TEST_CASE (CovarianceToDisc, ds::phiWithoutAmbiguity *ds::thetaWithoutBeam *ds::absMomentum *ds::chargeNonZero *ds::pathLength, phi, theta, p, q, s)
BOOST_DATA_TEST_CASE (CovarianceToPlane, ds::phi *ds::theta *ds::absMomentum *ds::chargeNonZero *ds::pathLength, phi, theta, p, q, s)
BOOST_DATA_TEST_CASE (CovarianceToStrawAlongZ, ds::phi *ds::thetaWithoutBeam *ds::absMomentum *ds::chargeNonZero *ds::pathLength, phi, theta, p, q, s)
Function Documentation
BOOST_DATA_TEST_CASE (ForwardBackward , ds::phi *ds::theta *ds::absMomentum *ds::chargeNonZero *ds::pathLength , phi , theta , p , q , s)
Definition at line 51 of file PropagationStraightLine.cpp.
View newest version in sPHENIX GitHub at line 51 of file PropagationStraightLine.cpp
References geoCtx, magCtx, makeParametersCurvilinear(), and runForwardBackwardTest().
BOOST_DATA_TEST_CASE (ToCylinderAlongZ , ds::phi *ds::thetaWithoutBeam *ds::absMomentum *ds::chargeNonZero *ds::pathLength , phi , theta , p , q , s)
Definition at line 63 of file PropagationStraightLine.cpp.
View newest version in sPHENIX GitHub at line 63 of file PropagationStraightLine.cpp
References geoCtx, magCtx, makeParametersCurvilinear(), merge_hashes::p, ActsTests::PropagationDatasets::phi, runToSurfaceTest(), physmon_simulation::s, and ActsTests::PropagationDatasets::theta.
BOOST_DATA_TEST_CASE (ToDisc , ds::phi *ds::theta *ds::absMomentum *ds::chargeNonZero *ds::pathLength , phi , theta , p , q , s)
Definition at line 72 of file PropagationStraightLine.cpp.
View newest version in sPHENIX GitHub at line 72 of file PropagationStraightLine.cpp
References geoCtx, magCtx, makeParametersCurvilinear(), merge_hashes::p, ActsTests::PropagationDatasets::phi, runToSurfaceTest(), physmon_simulation::s, and ActsTests::PropagationDatasets::theta.
BOOST_DATA_TEST_CASE (ToPlane , ds::phi *ds::theta *ds::absMomentum *ds::chargeNonZero *ds::pathLength , phi , theta , p , q , s)
Definition at line 81 of file PropagationStraightLine.cpp.
View newest version in sPHENIX GitHub at line 81 of file PropagationStraightLine.cpp
References geoCtx, magCtx, makeParametersCurvilinear(), merge_hashes::p, ActsTests::PropagationDatasets::phi, runToSurfaceTest(), physmon_simulation::s, and ActsTests::PropagationDatasets::theta.
BOOST_DATA_TEST_CASE (ToStrawAlongZ , ds::phi *ds::thetaWithoutBeam *ds::absMomentum *ds::chargeNonZero *ds::pathLength , phi , theta , p , q , s)
Definition at line 91 of file PropagationStraightLine.cpp.
View newest version in sPHENIX GitHub at line 91 of file PropagationStraightLine.cpp
References geoCtx, magCtx, makeParametersCurvilinear(), merge_hashes::p, ActsTests::PropagationDatasets::phi, runToSurfaceTest(), physmon_simulation::s, and ActsTests::PropagationDatasets::theta.
BOOST_DATA_TEST_CASE (CovarianceCurvilinear , ds::phi *ds::theta *ds::absMomentum *ds::chargeNonZero *ds::pathLength , phi , theta , p , q , s)
Definition at line 102 of file PropagationStraightLine.cpp.
View newest version in sPHENIX GitHub at line 102 of file PropagationStraightLine.cpp
References geoCtx, magCtx, makeParametersCurvilinearWithCovariance(), merge_hashes::p, ActsTests::PropagationDatasets::phi, runForwardComparisonTest(), physmon_simulation::s, and ActsTests::PropagationDatasets::theta.
BOOST_DATA_TEST_CASE (CovarianceToCylinderAlongZ , ds::phiWithoutAmbiguity *ds::thetaWithoutBeam *ds::absMomentum *ds::chargeNonZero *ds::pathLength , phi , theta , p , q , s)
Definition at line 112 of file PropagationStraightLine.cpp.
View newest version in sPHENIX GitHub at line 112 of file PropagationStraightLine.cpp
References geoCtx, magCtx, makeParametersCurvilinearWithCovariance(), merge_hashes::p, ActsTests::PropagationDatasets::phi, runToSurfaceComparisonTest(), physmon_simulation::s, and ActsTests::PropagationDatasets::theta.
BOOST_DATA_TEST_CASE (CovarianceToDisc , ds::phiWithoutAmbiguity *ds::thetaWithoutBeam *ds::absMomentum *ds::chargeNonZero *ds::pathLength , phi , theta , p , q , s)
Definition at line 122 of file PropagationStraightLine.cpp.
View newest version in sPHENIX GitHub at line 122 of file PropagationStraightLine.cpp
References geoCtx, magCtx, makeParametersCurvilinearWithCovariance(), merge_hashes::p, ActsTests::PropagationDatasets::phi, runToSurfaceComparisonTest(), physmon_simulation::s, and ActsTests::PropagationDatasets::theta.
BOOST_DATA_TEST_CASE (CovarianceToPlane , ds::phi *ds::theta *ds::absMomentum *ds::chargeNonZero *ds::pathLength , phi , theta , p , q , s)
Definition at line 132 of file PropagationStraightLine.cpp.
View newest version in sPHENIX GitHub at line 132 of file PropagationStraightLine.cpp
References geoCtx, magCtx, makeParametersCurvilinearWithCovariance(), merge_hashes::p, ActsTests::PropagationDatasets::phi, runToSurfaceComparisonTest(), physmon_simulation::s, and ActsTests::PropagationDatasets::theta.
BOOST_DATA_TEST_CASE (CovarianceToStrawAlongZ , ds::phi *ds::thetaWithoutBeam *ds::absMomentum *ds::chargeNonZero *ds::pathLength , phi , theta , p , q , s)
Definition at line 142 of file PropagationStraightLine.cpp.
View newest version in sPHENIX GitHub at line 142 of file PropagationStraightLine.cpp
References geoCtx, magCtx, makeParametersCurvilinearWithCovariance(), merge_hashes::p, ActsTests::PropagationDatasets::phi, runToSurfaceComparisonTest(), physmon_simulation::s, and ActsTests::PropagationDatasets::theta.