Analysis Software: acts/blob/sPHENIX/Tests/UnitTests/Core/EventData/MultiTrajectoryTests.cpp File Reference
MultiTrajectoryTests.cpp File Reference
#include <boost/test/data/test_case.hpp>
#include <boost/test/tools/context.hpp>
#include <boost/test/unit_test.hpp>
#include "Acts/Definitions/Algebra.hpp"
#include "Acts/Definitions/TrackParametrization.hpp"
#include "Acts/Definitions/Units.hpp"
#include "Acts/EventData/MultiTrajectory.hpp"
#include "Acts/EventData/TrackParameters.hpp"
#include "Acts/EventData/TrackStatePropMask.hpp"
#include "Acts/EventData/VectorMultiTrajectory.hpp"
#include "Acts/Geometry/GeometryContext.hpp"
#include "Acts/Geometry/GeometryIdentifier.hpp"
#include "Acts/Tests/CommonHelpers/FloatComparisons.hpp"
#include "Acts/Tests/CommonHelpers/MultiTrajectoryTestsCommon.hpp"
#include "Acts/Tests/CommonHelpers/TestSourceLink.hpp"
#include "Acts/Tests/CommonHelpers/TestTrackState.hpp"
#include <algorithm>
#include <array>
#include <ostream>
#include <random>
#include <stdexcept>
#include <string>
#include <type_traits>
#include <utility>
#include <variant>
#include <vector>
Functions
BOOST_AUTO_TEST_CASE (Build)
BOOST_AUTO_TEST_CASE (ConstCorrectness)
BOOST_AUTO_TEST_CASE (Clear)
BOOST_AUTO_TEST_CASE (ApplyWithAbort)
BOOST_AUTO_TEST_CASE (AddTrackStateWithBitMask)
BOOST_AUTO_TEST_CASE (TrackStateProxyCrossTalk)
BOOST_AUTO_TEST_CASE (TrackStateReassignment)
BOOST_DATA_TEST_CASE (TrackStateProxyStorage, bd::make({1u, 2u}), nMeasurements)
BOOST_AUTO_TEST_CASE (TrackStateProxyAllocations)
BOOST_AUTO_TEST_CASE (TrackStateProxyGetMask)
BOOST_AUTO_TEST_CASE (TrackStateProxyCopy)
BOOST_AUTO_TEST_CASE (TrackStateProxyCopyDiffMTJ)
BOOST_AUTO_TEST_CASE (ProxyAssignment)
BOOST_AUTO_TEST_CASE (CopyFromConst)
BOOST_AUTO_TEST_CASE (TrackStateProxyShare)
BOOST_AUTO_TEST_CASE (MultiTrajectoryExtraColumns)
BOOST_AUTO_TEST_CASE (MultiTrajectoryExtraColumnsRuntime)
BOOST_AUTO_TEST_CASE (MemoryStats)
Function Documentation
BOOST_AUTO_TEST_CASE (Build)
Definition at line 67 of file MultiTrajectoryTests.cpp.
View newest version in sPHENIX GitHub at line 67 of file MultiTrajectoryTests.cpp
BOOST_AUTO_TEST_CASE (ConstCorrectness)
Definition at line 72 of file MultiTrajectoryTests.cpp.
View newest version in sPHENIX GitHub at line 72 of file MultiTrajectoryTests.cpp
References Acts::MultiTrajectory< derived_t >::addTrackState(), Acts::MultiTrajectory< derived_t >::getTrackState(), testing::internal::move(), Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::predicted(), Acts::MultiTrajectory< derived_t >::ReadOnly, Acts::MultiTrajectory< derived_t >::size(), and t.
BOOST_AUTO_TEST_CASE (Clear)
Definition at line 116 of file MultiTrajectoryTests.cpp.
View newest version in sPHENIX GitHub at line 116 of file MultiTrajectoryTests.cpp
BOOST_AUTO_TEST_CASE (ApplyWithAbort)
Definition at line 121 of file MultiTrajectoryTests.cpp.
View newest version in sPHENIX GitHub at line 121 of file MultiTrajectoryTests.cpp
BOOST_AUTO_TEST_CASE (AddTrackStateWithBitMask)
Definition at line 126 of file MultiTrajectoryTests.cpp.
View newest version in sPHENIX GitHub at line 126 of file MultiTrajectoryTests.cpp
BOOST_AUTO_TEST_CASE (TrackStateProxyCrossTalk)
Definition at line 132 of file MultiTrajectoryTests.cpp.
View newest version in sPHENIX GitHub at line 132 of file MultiTrajectoryTests.cpp
References conftest::rng().
BOOST_AUTO_TEST_CASE (TrackStateReassignment)
Definition at line 137 of file MultiTrajectoryTests.cpp.
View newest version in sPHENIX GitHub at line 137 of file MultiTrajectoryTests.cpp
References conftest::rng().
BOOST_AUTO_TEST_CASE (TrackStateProxyAllocations)
Definition at line 148 of file MultiTrajectoryTests.cpp.
View newest version in sPHENIX GitHub at line 148 of file MultiTrajectoryTests.cpp
References conftest::rng().
BOOST_AUTO_TEST_CASE (TrackStateProxyGetMask)
Definition at line 153 of file MultiTrajectoryTests.cpp.
View newest version in sPHENIX GitHub at line 153 of file MultiTrajectoryTests.cpp
BOOST_AUTO_TEST_CASE (TrackStateProxyCopy)
Definition at line 158 of file MultiTrajectoryTests.cpp.
View newest version in sPHENIX GitHub at line 158 of file MultiTrajectoryTests.cpp
References conftest::rng().
BOOST_AUTO_TEST_CASE (TrackStateProxyCopyDiffMTJ)
Definition at line 163 of file MultiTrajectoryTests.cpp.
View newest version in sPHENIX GitHub at line 163 of file MultiTrajectoryTests.cpp
BOOST_AUTO_TEST_CASE (ProxyAssignment)
Definition at line 168 of file MultiTrajectoryTests.cpp.
View newest version in sPHENIX GitHub at line 168 of file MultiTrajectoryTests.cpp
BOOST_AUTO_TEST_CASE (CopyFromConst)
Definition at line 173 of file MultiTrajectoryTests.cpp.
View newest version in sPHENIX GitHub at line 173 of file MultiTrajectoryTests.cpp
BOOST_AUTO_TEST_CASE (TrackStateProxyShare)
Definition at line 178 of file MultiTrajectoryTests.cpp.
View newest version in sPHENIX GitHub at line 178 of file MultiTrajectoryTests.cpp
References conftest::rng().
BOOST_AUTO_TEST_CASE (MultiTrajectoryExtraColumns)
Definition at line 183 of file MultiTrajectoryTests.cpp.
View newest version in sPHENIX GitHub at line 183 of file MultiTrajectoryTests.cpp
BOOST_AUTO_TEST_CASE (MultiTrajectoryExtraColumnsRuntime)
Definition at line 188 of file MultiTrajectoryTests.cpp.
View newest version in sPHENIX GitHub at line 188 of file MultiTrajectoryTests.cpp
BOOST_AUTO_TEST_CASE (MemoryStats)
Definition at line 193 of file MultiTrajectoryTests.cpp.
View newest version in sPHENIX GitHub at line 193 of file MultiTrajectoryTests.cpp
References Acts::PhysicalConstants::c, h, histogram(), out, conftest::rng(), Acts::detail_vmt::VectorMultiTrajectoryBase::statistics(), t, Acts::detail_vmt::VectorMultiTrajectoryBase::Statistics::toStream(), physmon_ckf_tracking::u, and testSigmaEff::v.
BOOST_DATA_TEST_CASE (TrackStateProxyStorage , bd:: make{1u, 2u}, nMeasurements)
Definition at line 142 of file MultiTrajectoryTests.cpp.
View newest version in sPHENIX GitHub at line 142 of file MultiTrajectoryTests.cpp
References physmon_ckf_tracking::u.