Analysis Software: sPHAnalysis Class Reference
sPHAnalysis Class Reference
#include <analysis/blob/master/EventMix/ana/sPHAnalysis.h>
Public Member Functions
sPHAnalysis (const std::string &name="sPHAnalysis", const std::string &filename="test.root")
virtual ~sPHAnalysis ()
int Init (PHCompositeNode *topNode)
int InitRun (PHCompositeNode *topNode)
int process_event (PHCompositeNode *topNode)
int End (PHCompositeNode *topNode)
Called at the end of all processing.
void set_whattodo (int what)
Public Member Functions inherited from SubsysReco
~SubsysReco () override
virtual int EndRun (const int)
Called at the end of each run.
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
void Print (const std::string &="ALL") const override
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Protected Member Functions
int process_event_hepmc (PHCompositeNode *topNode)
int process_event_pythiaupsilon (PHCompositeNode *topNode)
int process_event_upsilons (PHCompositeNode *topNode)
int process_event_test (PHCompositeNode *topNode)
int process_event_bimp (PHCompositeNode *topNode)
int process_event_pairs (PHCompositeNode *topNode)
int process_event_notracking (PHCompositeNode *topNode)
int process_event_filtered (PHCompositeNode *topNode)
HepMC::GenParticle * GetParent (HepMC::GenParticle *, HepMC::GenEvent *)
RawCluster * MatchClusterCEMC (SvtxTrack *track, RawClusterContainer *cemc_clusters, double &dphi, double &deta, double Zvtx, int what)
double Get_CAL_e3x3 (SvtxTrack *track, RawTowerContainer *_towersRawOH, RawTowerGeomContainer *_geomOH, int what, double Zvtx, double &dphi, double &deta)
TVector3 GetProjectionToCalorimeter (SvtxTrack *track, int what)
bool isElectron (SvtxTrack *trk)
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Protected Member Functions inherited from Fun4AllBase
Fun4AllBase (const std::string &name="NONAME")
Protected Attributes
TFile * OutputNtupleFile
std::string OutputFileName
TNtuple * ntp_notracking
TNtuple * ntppid
TNtuple * ntpb
TNtuple * ntp1
TNtuple * ntp2
TNtuple * ntpmc1
TNtuple * ntpmc2
TH1D * hmult
TH1D * hmass
TH1D * hgmass
TH1D * hgmass0
TH1D * hgmass09
TH1D * hdphi
TH1D * hdeta
TH1D * heop
TH1D * heop3x3
TH1D * heop5x5
TH1D * hdca2d
TH1D * hdca3dxy
TH1D * hdca3dz
TH1D * hchi2
TH1D * hndf
TH1D * hquality
TH1D * h_notracking_etabins_em
TH1D * h_notracking_phibins_em
TH1D * h_notracking_etabins
TH1D * h_notracking_phibins
TH1D * h_notracking_etabinsout
TH1D * h_notracking_phibinsout
TH1D * h_notracking_eoh
TH1D * test
int EventNumber
TRandom * _rng
TF1 * fsin = nullptr
int _whattodo
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = std::numeric_limits<int>::max() - 10
}
Detailed Description
Definition at line 24 of file sPHAnalysis.h.
View newest version in sPHENIX GitHub at line 24 of file sPHAnalysis.h
Constructor & Destructor Documentation
sPHAnalysis::sPHAnalysis (const std::string & name = "sPHAnalysis", const std::string & filename = "test.root")
Definition at line 80 of file sPHAnalysis.cc.
View newest version in sPHENIX GitHub at line 80 of file sPHAnalysis.cc
References _rng, _whattodo, EventNumber, filename, hchi2, hdca2d, hdca3dxy, hdca3dz, hdeta, hdphi, heop, heop3x3, heop5x5, hgmass, hgmass0, hgmass09, hmass, hndf, hquality, ntp1, OutputFileName, and OutputNtupleFile.
virtual sPHAnalysis::~sPHAnalysis () inline virtual
Definition at line 29 of file sPHAnalysis.h.
View newest version in sPHENIX GitHub at line 29 of file sPHAnalysis.h
Member Function Documentation
int sPHAnalysis::End (PHCompositeNode *) virtual
Called at the end of all processing.
Reimplemented from SubsysReco.
Definition at line 1563 of file sPHAnalysis.cc.
View newest version in sPHENIX GitHub at line 1563 of file sPHAnalysis.cc
References Fun4AllReturnCodes::EVENT_OK, EventNumber, and OutputNtupleFile.
double sPHAnalysis::Get_CAL_e3x3 (SvtxTrack * track, RawTowerContainer * _towersRawOH, RawTowerGeomContainer * _geomOH, int what, double Zvtx, double & dphi, double & deta) protected
Definition at line 762 of file sPHAnalysis.cc.
View newest version in sPHENIX GitHub at line 762 of file sPHAnalysis.cc
References SvtxTrack::begin_states(), dist(), SvtxTrack::end_states(), RawTowerGeom::get_bineta(), RawTowerGeom::get_binphi(), RawTowerGeom::get_center_x(), RawTowerGeom::get_center_y(), RawTowerGeom::get_center_z(), RawTower::get_energy(), RawTower::get_key(), SvtxTrackState::get_pathlength(), SvtxTrack::get_state(), RawTowerGeomContainer::get_tower_geometry(), SvtxTrackState::get_x(), SvtxTrackState::get_y(), SvtxTrackState::get_z(), RawTowerContainer::getTower(), RawTowerContainer::getTowers(), i, j, and proj().
Referenced by process_event_test().
HepMC::GenParticle * sPHAnalysis::GetParent (HepMC::GenParticle * p, HepMC::GenEvent * event) protected
Definition at line 405 of file sPHAnalysis.cc.
View newest version in sPHENIX GitHub at line 405 of file sPHAnalysis.cc
TVector3 sPHAnalysis::GetProjectionToCalorimeter (SvtxTrack * track, int what) protected
Definition at line 1205 of file sPHAnalysis.cc.
View newest version in sPHENIX GitHub at line 1205 of file sPHAnalysis.cc
References SvtxTrack::begin_states(), SvtxTrack::end_states(), SvtxTrackState::get_pathlength(), SvtxTrack::get_state(), SvtxTrackState::get_x(), SvtxTrackState::get_y(), SvtxTrackState::get_z(), and proj().
int sPHAnalysis::Init (PHCompositeNode *) virtual
Called during initialization. Typically this is where you can book histograms, and e.g. register them to Fun4AllServer (so they can be output to file using Fun4AllServer::dumpHistos() method).
Reimplemented from SubsysReco.
Definition at line 108 of file sPHAnalysis.cc.
View newest version in sPHENIX GitHub at line 108 of file sPHAnalysis.cc
References _rng, Fun4AllReturnCodes::EVENT_OK, h_notracking_eoh, h_notracking_etabins, h_notracking_etabins_em, h_notracking_etabinsout, h_notracking_phibins, h_notracking_phibins_em, h_notracking_phibinsout, hchi2, hdca2d, hdca3dxy, hdca3dz, hdeta, hdphi, heop, heop3x3, heop5x5, hgmass, hgmass0, hgmass09, hmass, hmult, hndf, hquality, ntp1, ntp2, ntp_notracking, ntpb, ntpmc1, ntpmc2, ntppid, OutputFileName, OutputNtupleFile, and test.
int sPHAnalysis::InitRun (PHCompositeNode *) virtual
Called for first event when run number is known. Typically this is where you may want to fetch data from database, because you know the run number.
Reimplemented from SubsysReco.
Definition at line 170 of file sPHAnalysis.cc.
View newest version in sPHENIX GitHub at line 170 of file sPHAnalysis.cc
References Fun4AllReturnCodes::EVENT_OK.
bool sPHAnalysis::isElectron (SvtxTrack * trk) protected
Definition at line 1542 of file sPHAnalysis.cc.
View newest version in sPHENIX GitHub at line 1542 of file sPHAnalysis.cc
References Enable::CEMC, SvtxTrack::get_cal_energy_3x3(), SvtxTrack::get_px(), SvtxTrack::get_py(), SvtxTrack::get_pz(), and physmon_track_finding_ttbar::pt.
RawCluster * sPHAnalysis::MatchClusterCEMC (SvtxTrack * track, RawClusterContainer * cemc_clusters, double & dphi, double & deta, double Zvtx, int what) protected
Definition at line 1235 of file sPHAnalysis.cc.
View newest version in sPHENIX GitHub at line 1235 of file sPHAnalysis.cc
References SvtxTrack::begin_states(), dist(), SvtxTrack::end_states(), RawCluster::get_ecore(), SvtxTrackState::get_pathlength(), RawCluster::get_r(), SvtxTrack::get_state(), SvtxTrackState::get_x(), RawCluster::get_x(), SvtxTrackState::get_y(), RawCluster::get_y(), SvtxTrackState::get_z(), RawCluster::get_z(), RawClusterContainer::getClusters(), and proj().
Referenced by process_event_test(), and process_event_upsilons().
int sPHAnalysis::process_event (PHCompositeNode *) virtual
Called for each event. This is where you do the real work.
Reimplemented from SubsysReco.
Definition at line 179 of file sPHAnalysis.cc.
View newest version in sPHENIX GitHub at line 179 of file sPHAnalysis.cc
References _whattodo, Fun4AllReturnCodes::ABORTRUN, process_event_filtered(), process_event_notracking(), process_event_pairs(), process_event_pythiaupsilon(), process_event_test(), and process_event_upsilons().
int sPHAnalysis::process_event_bimp (PHCompositeNode * topNode) protected
Definition at line 376 of file sPHAnalysis.cc.
View newest version in sPHENIX GitHub at line 376 of file sPHAnalysis.cc
References Fun4AllReturnCodes::ABORTEVENT, event, Fun4AllReturnCodes::EVENT_OK, EventNumber, ntpb, PHWHERE, PHHepMCGenEventMap::rbegin(), PHHepMCGenEventMap::rend(), and Acts::Test::tmp().
int sPHAnalysis::process_event_filtered (PHCompositeNode * topNode) protected
Definition at line 834 of file sPHAnalysis.cc.
View newest version in sPHENIX GitHub at line 834 of file sPHAnalysis.cc
References Fun4AllReturnCodes::ABORTEVENT, EventNumber, PHWHERE, SvtxTrackMap::size(), RawClusterContainer::size(), and TrkrClusterContainer::size().
Referenced by process_event().
int sPHAnalysis::process_event_hepmc (PHCompositeNode * topNode) protected
Definition at line 203 of file sPHAnalysis.cc.
View newest version in sPHENIX GitHub at line 203 of file sPHAnalysis.cc
References _rng, Fun4AllReturnCodes::ABORTEVENT, PHHepMCGenEvent::addEvent(), eta, event, Fun4AllReturnCodes::EVENT_OK, EventNumber, fsin, PHHepMCGenEventMap::insert_event(), Acts::UnitConstants::m2, mass, npart(), ActsTests::PropagationDatasets::phi, PHWHERE, PHCompositeNode::print(), physmon_track_finding_ttbar::pt, PHHepMCGenEventMap::rbegin(), PHHepMCGenEventMap::rend(), testSigmaEff::v, v1, v2, and y.
int sPHAnalysis::process_event_notracking (PHCompositeNode * topNode) protected
Definition at line 557 of file sPHAnalysis.cc.
View newest version in sPHENIX GitHub at line 557 of file sPHAnalysis.cc
References Fun4AllReturnCodes::ABORTEVENT, GlobalVertexMap::begin(), GlobalVertexMap::end(), Fun4AllReturnCodes::EVENT_OK, EventNumber, RawTowerGeom::get_bineta(), RawTowerGeom::get_binphi(), RawTowerGeom::get_center_x(), RawTowerGeom::get_center_y(), RawTowerGeom::get_center_z(), RawCluster::get_ecore(), RawTower::get_energy(), GlobalVertex::get_id(), RawTower::get_key(), RawTowerGeom::get_phi(), RawTowerGeomContainer::get_tower_geometry(), RawCluster::get_x(), RawCluster::get_y(), GlobalVertex::get_z(), RawCluster::get_z(), RawClusterContainer::getClusters(), RawTowerContainer::getTower(), RawTowerContainer::getTowers(), h_notracking_eoh, h_notracking_etabins, h_notracking_etabins_em, h_notracking_etabinsout, h_notracking_phibins, h_notracking_phibins_em, h_notracking_phibinsout, i, j, ntp_notracking, PHWHERE, Pt(), RawClusterContainer::size(), and Acts::Test::tmp().
Referenced by process_event().
int sPHAnalysis::process_event_pairs (PHCompositeNode * topNode) protected
Definition at line 308 of file sPHAnalysis.cc.
View newest version in sPHENIX GitHub at line 308 of file sPHAnalysis.cc
References sPHElectronPairContainerv1::begin(), double(), electron, sPHElectronPairContainerv1::end(), Fun4AllReturnCodes::EVENT_OK, EventNumber, sPHElectronv1::get_chi2(), sPHElectronv1::get_dca2d(), sPHElectronv1::get_dca3d_xy(), sPHElectronv1::get_dca3d_z(), sPHElectronv1::get_e3x3(), sPHElectronv1::get_emce(), sPHElectronPairv1::get_eta(), sPHElectronPairv1::get_first(), sPHElectronPairv1::get_mass(), sPHElectronv1::get_ndf(), sPHElectronv1::get_nmvtx(), sPHElectronv1::get_ntpc(), sPHElectronPairv1::get_pt(), sPHElectronv1::get_px(), sPHElectronv1::get_py(), sPHElectronv1::get_pz(), sPHElectronPairv1::get_second(), sPHElectronPairv1::get_type(), ntp1, sPHElectronPairContainerv1::size(), and Acts::Test::tmp().
Referenced by process_event().
int sPHAnalysis::process_event_pythiaupsilon (PHCompositeNode * topNode) protected
Definition at line 431 of file sPHAnalysis.cc.
View newest version in sPHENIX GitHub at line 431 of file sPHAnalysis.cc
References Fun4AllReturnCodes::ABORTEVENT, Acts::UnitConstants::e, eta, event, Fun4AllReturnCodes::EVENT_OK, EventNumber, testing::internal::Log(), Acts::UnitConstants::m, mass, npart(), ntpmc2, merge_hashes::p, Acts::VectorHelpers::perp(), PHWHERE, train_ambiguity_solver::pid, PHCompositeNode::print(), physmon_track_finding_ttbar::pt, PHHepMCGenEventMap::rbegin(), PHHepMCGenEventMap::rend(), utils::status, test, Acts::Test::tmp(), and parse_cmake_options::type.
Referenced by process_event().
int sPHAnalysis::process_event_test (PHCompositeNode * topNode) protected
Definition at line 874 of file sPHAnalysis.cc.
View newest version in sPHENIX GitHub at line 874 of file sPHAnalysis.cc
References Fun4AllReturnCodes::ABORTEVENT, GlobalVertexMap::begin(), SvtxTrackMap::begin(), cemc_deta, cemc_dphi, charge(), GlobalVertexMap::end(), SvtxTrackMap::end(), eta, Fun4AllReturnCodes::EVENT_OK, EventNumber, Get_CAL_e3x3(), SvtxTrack::get_charge(), SvtxTrack::get_chisq(), SvtxTrack::get_dca3d_xy(), RawCluster::get_ecore(), RawCluster::get_energy(), SvtxTrack::get_eta(), GlobalVertex::get_id(), SvtxTrack::get_ndf(), RawCluster::get_prob(), SvtxTrack::get_px(), SvtxTrack::get_py(), SvtxTrack::get_pz(), SvtxTrack::get_silicon_seed(), SvtxTrack::get_tpc_seed(), GlobalVertex::get_z(), TrkrDefs::getLayer(), TrkrDefs::getTrkrId(), hmult, TrkrDefs::inttId, layer, MatchClusterCEMC(), TrkrDefs::mvtxId, npart(), ntpb, ntppid, PHWHERE, physmon_track_finding_ttbar::pt, SvtxTrackMap::size(), and RawClusterContainer::size().
Referenced by process_event().
int sPHAnalysis::process_event_upsilons (PHCompositeNode * topNode) protected
Definition at line 1299 of file sPHAnalysis.cc.
View newest version in sPHENIX GitHub at line 1299 of file sPHAnalysis.cc
References Fun4AllReturnCodes::ABORTEVENT, GlobalVertexMap::begin(), SvtxTrackMap::begin(), cemc_deta, cemc_dphi, charge(), GlobalVertexMap::end(), SvtxTrackMap::end(), eta, Fun4AllReturnCodes::EVENT_OK, EventNumber, SvtxTrack::get_charge(), SvtxTrack::get_chisq(), SvtxTrack::get_dca3d_xy(), RawCluster::get_ecore(), SvtxTrack::get_eta(), GlobalVertex::get_id(), SvtxTrack::get_ndf(), SvtxTrack::get_px(), SvtxTrack::get_py(), SvtxTrack::get_pz(), SvtxTrack::get_silicon_seed(), SvtxTrack::get_tpc_seed(), SvtxTrack::get_x(), SvtxTrack::get_y(), GlobalVertex::get_z(), SvtxTrack::get_z(), TrkrDefs::getLayer(), TrkrDefs::getTrkrId(), hmass, i, TrkrDefs::inttId, j, layer, mass, MatchClusterCEMC(), TrkrDefs::mvtxId, ntp2, PHWHERE, PHCompositeNode::print(), physmon_track_finding_ttbar::pt, SvtxVertexMap::size(), SvtxTrackMap::size(), and Acts::Test::tmp().
Referenced by process_event().
void sPHAnalysis::set_whattodo (int what) inline
Definition at line 36 of file sPHAnalysis.h.
View newest version in sPHENIX GitHub at line 36 of file sPHAnalysis.h
References _whattodo.
Referenced by runanae(), runanajpsi(), runanaK(), runanapi(), and runanapythiaupsilon().
Member Data Documentation
TRandom* sPHAnalysis::_rng protected
Definition at line 96 of file sPHAnalysis.h.
View newest version in sPHENIX GitHub at line 96 of file sPHAnalysis.h
Referenced by Init(), process_event_hepmc(), and sPHAnalysis().
int sPHAnalysis::_whattodo protected
Definition at line 99 of file sPHAnalysis.h.
View newest version in sPHENIX GitHub at line 99 of file sPHAnalysis.h
Referenced by process_event(), set_whattodo(), and sPHAnalysis().
int sPHAnalysis::EventNumber protected
Definition at line 94 of file sPHAnalysis.h.
View newest version in sPHENIX GitHub at line 94 of file sPHAnalysis.h
Referenced by End(), process_event_bimp(), process_event_filtered(), process_event_hepmc(), process_event_notracking(), process_event_pairs(), process_event_pythiaupsilon(), process_event_test(), process_event_upsilons(), and sPHAnalysis().
TF1* sPHAnalysis::fsin = nullptr protected
Definition at line 97 of file sPHAnalysis.h.
View newest version in sPHENIX GitHub at line 97 of file sPHAnalysis.h
Referenced by process_event_hepmc().
TH1D* sPHAnalysis::h_notracking_eoh protected
Definition at line 90 of file sPHAnalysis.h.
View newest version in sPHENIX GitHub at line 90 of file sPHAnalysis.h
Referenced by Init(), and process_event_notracking().
TH1D* sPHAnalysis::h_notracking_etabins protected
Definition at line 86 of file sPHAnalysis.h.
View newest version in sPHENIX GitHub at line 86 of file sPHAnalysis.h
Referenced by Init(), and process_event_notracking().
TH1D* sPHAnalysis::h_notracking_etabins_em protected
Definition at line 84 of file sPHAnalysis.h.
View newest version in sPHENIX GitHub at line 84 of file sPHAnalysis.h
Referenced by Init(), and process_event_notracking().
TH1D* sPHAnalysis::h_notracking_etabinsout protected
Definition at line 88 of file sPHAnalysis.h.
View newest version in sPHENIX GitHub at line 88 of file sPHAnalysis.h
Referenced by Init(), and process_event_notracking().
TH1D* sPHAnalysis::h_notracking_phibins protected
Definition at line 87 of file sPHAnalysis.h.
View newest version in sPHENIX GitHub at line 87 of file sPHAnalysis.h
Referenced by Init(), and process_event_notracking().
TH1D* sPHAnalysis::h_notracking_phibins_em protected
Definition at line 85 of file sPHAnalysis.h.
View newest version in sPHENIX GitHub at line 85 of file sPHAnalysis.h
Referenced by Init(), and process_event_notracking().
TH1D* sPHAnalysis::h_notracking_phibinsout protected
Definition at line 89 of file sPHAnalysis.h.
View newest version in sPHENIX GitHub at line 89 of file sPHAnalysis.h
Referenced by Init(), and process_event_notracking().
TH1D* sPHAnalysis::hchi2 protected
Definition at line 81 of file sPHAnalysis.h.
View newest version in sPHENIX GitHub at line 81 of file sPHAnalysis.h
Referenced by Init(), and sPHAnalysis().
TH1D* sPHAnalysis::hdca2d protected
Definition at line 78 of file sPHAnalysis.h.
View newest version in sPHENIX GitHub at line 78 of file sPHAnalysis.h
Referenced by Init(), and sPHAnalysis().
TH1D* sPHAnalysis::hdca3dxy protected
Definition at line 79 of file sPHAnalysis.h.
View newest version in sPHENIX GitHub at line 79 of file sPHAnalysis.h
Referenced by Init(), and sPHAnalysis().
TH1D* sPHAnalysis::hdca3dz protected
Definition at line 80 of file sPHAnalysis.h.
View newest version in sPHENIX GitHub at line 80 of file sPHAnalysis.h
Referenced by Init(), and sPHAnalysis().
TH1D* sPHAnalysis::hdeta protected
Definition at line 74 of file sPHAnalysis.h.
View newest version in sPHENIX GitHub at line 74 of file sPHAnalysis.h
Referenced by Init(), and sPHAnalysis().
TH1D* sPHAnalysis::hdphi protected
Definition at line 73 of file sPHAnalysis.h.
View newest version in sPHENIX GitHub at line 73 of file sPHAnalysis.h
Referenced by Init(), and sPHAnalysis().
TH1D* sPHAnalysis::heop protected
Definition at line 75 of file sPHAnalysis.h.
View newest version in sPHENIX GitHub at line 75 of file sPHAnalysis.h
Referenced by Init(), and sPHAnalysis().
TH1D* sPHAnalysis::heop3x3 protected
Definition at line 76 of file sPHAnalysis.h.
View newest version in sPHENIX GitHub at line 76 of file sPHAnalysis.h
Referenced by Init(), and sPHAnalysis().
TH1D* sPHAnalysis::heop5x5 protected
Definition at line 77 of file sPHAnalysis.h.
View newest version in sPHENIX GitHub at line 77 of file sPHAnalysis.h
Referenced by Init(), and sPHAnalysis().
TH1D* sPHAnalysis::hgmass protected
Definition at line 70 of file sPHAnalysis.h.
View newest version in sPHENIX GitHub at line 70 of file sPHAnalysis.h
Referenced by Init(), and sPHAnalysis().
TH1D* sPHAnalysis::hgmass0 protected
Definition at line 71 of file sPHAnalysis.h.
View newest version in sPHENIX GitHub at line 71 of file sPHAnalysis.h
Referenced by Init(), and sPHAnalysis().
TH1D* sPHAnalysis::hgmass09 protected
Definition at line 72 of file sPHAnalysis.h.
View newest version in sPHENIX GitHub at line 72 of file sPHAnalysis.h
Referenced by Init(), and sPHAnalysis().
TH1D* sPHAnalysis::hmass protected
Definition at line 69 of file sPHAnalysis.h.
View newest version in sPHENIX GitHub at line 69 of file sPHAnalysis.h
Referenced by Init(), process_event_upsilons(), and sPHAnalysis().
TH1D* sPHAnalysis::hmult protected
Definition at line 68 of file sPHAnalysis.h.
View newest version in sPHENIX GitHub at line 68 of file sPHAnalysis.h
Referenced by Init(), and process_event_test().
TH1D* sPHAnalysis::hndf protected
Definition at line 82 of file sPHAnalysis.h.
View newest version in sPHENIX GitHub at line 82 of file sPHAnalysis.h
Referenced by Init(), and sPHAnalysis().
TH1D* sPHAnalysis::hquality protected
Definition at line 83 of file sPHAnalysis.h.
View newest version in sPHENIX GitHub at line 83 of file sPHAnalysis.h
Referenced by Init(), and sPHAnalysis().
TNtuple* sPHAnalysis::ntp1 protected
Definition at line 63 of file sPHAnalysis.h.
View newest version in sPHENIX GitHub at line 63 of file sPHAnalysis.h
Referenced by Init(), process_event_pairs(), and sPHAnalysis().
TNtuple* sPHAnalysis::ntp2 protected
Definition at line 64 of file sPHAnalysis.h.
View newest version in sPHENIX GitHub at line 64 of file sPHAnalysis.h
Referenced by Init(), and process_event_upsilons().
TNtuple* sPHAnalysis::ntp_notracking protected
Definition at line 60 of file sPHAnalysis.h.
View newest version in sPHENIX GitHub at line 60 of file sPHAnalysis.h
Referenced by Init(), and process_event_notracking().
TNtuple* sPHAnalysis::ntpb protected
Definition at line 62 of file sPHAnalysis.h.
View newest version in sPHENIX GitHub at line 62 of file sPHAnalysis.h
Referenced by Init(), process_event_bimp(), and process_event_test().
TNtuple* sPHAnalysis::ntpmc1 protected
Definition at line 65 of file sPHAnalysis.h.
View newest version in sPHENIX GitHub at line 65 of file sPHAnalysis.h
Referenced by Init().
TNtuple* sPHAnalysis::ntpmc2 protected
Definition at line 66 of file sPHAnalysis.h.
View newest version in sPHENIX GitHub at line 66 of file sPHAnalysis.h
Referenced by Init(), and process_event_pythiaupsilon().
TNtuple* sPHAnalysis::ntppid protected
Definition at line 61 of file sPHAnalysis.h.
View newest version in sPHENIX GitHub at line 61 of file sPHAnalysis.h
Referenced by Init(), and process_event_test().
std::string sPHAnalysis::OutputFileName protected
Definition at line 58 of file sPHAnalysis.h.
View newest version in sPHENIX GitHub at line 58 of file sPHAnalysis.h
Referenced by Init(), and sPHAnalysis().
TFile* sPHAnalysis::OutputNtupleFile protected
Definition at line 57 of file sPHAnalysis.h.
View newest version in sPHENIX GitHub at line 57 of file sPHAnalysis.h
Referenced by End(), Init(), and sPHAnalysis().
TH1D* sPHAnalysis::test protected
Definition at line 92 of file sPHAnalysis.h.
View newest version in sPHENIX GitHub at line 92 of file sPHAnalysis.h
Referenced by Init(), and process_event_pythiaupsilon().
The documentation for this class was generated from the following files:
analysis/blob/master/EventMix/ana/sPHAnalysis.h
analysis/blob/master/EventMix/ana/sPHAnalysis.cc