Analysis Software: direction_indicator Class Reference
direction_indicator Class Reference
#include <JETSCAPE/blob/main/external_packages/gtl/include/GTL/pq_node.h>
Private Member Functions
direction_indicator (node n_, int id_)
PQ_KIND kind () const
void write (ostream &os, int)
p_node * P ()
q_node * Q ()
direction_indicator * D ()
pq_leaf * L ()
Private Attributes
bool direction
Friends
class planarity
class pq_tree
Additional Inherited Members
Protected Types inherited from pq_node
enum PQ_KIND { P_NODE, Q_NODE, LEAF, DIR }
enum PQ_MARK { UNMARKED, QUEUED, BLOCKED, UNBLOCKED }
typedef symlist< pq_node * >
::iterator iterator
Protected Member Functions inherited from pq_node
pq_node (node n_, int id_)
virtual ~pq_node ()
virtual void partial (iterator)
virtual void full (iterator)
virtual void clear ()
Protected Attributes inherited from pq_node
int pert_children
int pert_leaves
bool is_endmost
pq_node * father
PQ_MARK mark
symlist< pq_node * > sons
iterator pos
list< pq_node * >::iterator lpos
node n
int id
node up
int up_id
Detailed Description
Definition at line 689 of file pq_node.h.
View newest version in sPHENIX GitHub at line 689 of file pq_node.h
Constructor & Destructor Documentation
direction_indicator::direction_indicator (node n_, int id_) inline private
Definition at line 695 of file pq_node.h.
View newest version in sPHENIX GitHub at line 695 of file pq_node.h
Member Function Documentation
direction_indicator* direction_indicator::D () inline private virtual
Implements pq_node.
Definition at line 742 of file pq_node.h.
View newest version in sPHENIX GitHub at line 742 of file pq_node.h
Referenced by pq_tree::dfs(), planarity::examine_obstruction(), pq_tree::remove_dir_ind(), and pq_tree::replace_pert().
PQ_KIND direction_indicator::kind () const inline private virtual
Implements pq_node.
Definition at line 705 of file pq_node.h.
View newest version in sPHENIX GitHub at line 705 of file pq_node.h
References pq_node::DIR.
pq_leaf* direction_indicator::L () inline private virtual
Implements pq_node.
Definition at line 751 of file pq_node.h.
View newest version in sPHENIX GitHub at line 751 of file pq_node.h
References assert.
p_node* direction_indicator::P () inline private virtual
Implements pq_node.
Definition at line 722 of file pq_node.h.
View newest version in sPHENIX GitHub at line 722 of file pq_node.h
References assert.
q_node* direction_indicator::Q () inline private virtual
Implements pq_node.
Definition at line 732 of file pq_node.h.
View newest version in sPHENIX GitHub at line 732 of file pq_node.h
References assert.
void direction_indicator::write (ostream & os, int _id) private virtual
Implements pq_node.
Definition at line 351 of file pq_node.cpp.
View newest version in sPHENIX GitHub at line 351 of file pq_node.cpp
References pq_node::BLOCKED, pq_node::mark, and pq_node::UNBLOCKED.
Friends And Related Function Documentation
friend class planarity friend
Definition at line 774 of file pq_node.h.
View newest version in sPHENIX GitHub at line 774 of file pq_node.h
friend class pq_tree friend
Definition at line 780 of file pq_node.h.
View newest version in sPHENIX GitHub at line 780 of file pq_node.h
Member Data Documentation
bool direction_indicator::direction private
Definition at line 764 of file pq_node.h.
View newest version in sPHENIX GitHub at line 764 of file pq_node.h
Referenced by pq_tree::dfs(), planarity::examine_obstruction(), and pq_tree::replace_pert().
The documentation for this class was generated from the following files:
JETSCAPE/blob/main/external_packages/gtl/include/GTL/pq_node.h
JETSCAPE/blob/main/external_packages/gtl/src/pq_node.cpp