Analysis Software: ActsExamples::SvgTrackingGeometryWriter Class Reference
ActsExamples::SvgTrackingGeometryWriter Class Reference
#include <acts/blob/sPHENIX/Examples/Io/Svg/include/ActsExamples/Io/Svg/SvgTrackingGeometryWriter.hpp>
Classes
class Config
Public Member Functions
SvgTrackingGeometryWriter (const Config &config, Acts::Logging::Level level)
std::string name () const
ActsExamples::ProcessCode write (const AlgorithmContext &context, const Acts::TrackingGeometry &tGeometry)
Private Member Functions
const Acts::Logger & logger () const
Private access to the logging instance.
Private Attributes
std::unique_ptr< const
Acts::Logger > m_logger
the logger instance
Config m_cfg
the config class
std::mutex m_writeMutex
Mutex used to protect multi-threaded writes.
Detailed Description
An Svg writer for the geometry: TrackingGeometry master It delegates the writing to the converter from the Svg plugin
Definition at line 32 of file SvgTrackingGeometryWriter.hpp.
View newest version in sPHENIX GitHub at line 32 of file SvgTrackingGeometryWriter.hpp
Constructor & Destructor Documentation
ActsExamples::SvgTrackingGeometryWriter::SvgTrackingGeometryWriter (const Config & config, Acts::Logging::Level level)
Constructor
Parameters
config is the configuration class
level the log level
Definition at line 20 of file SvgTrackingGeometryWriter.cpp.
View newest version in sPHENIX GitHub at line 20 of file SvgTrackingGeometryWriter.cpp
Member Function Documentation
const Acts::Logger& ActsExamples::SvgTrackingGeometryWriter::logger () const inline private
Private access to the logging instance.
Definition at line 69 of file SvgTrackingGeometryWriter.hpp.
View newest version in sPHENIX GitHub at line 69 of file SvgTrackingGeometryWriter.hpp
References m_logger.
std::string ActsExamples::SvgTrackingGeometryWriter::name () const
Framework name() method
Returns
the name of the tool
Definition at line 25 of file SvgTrackingGeometryWriter.cpp.
View newest version in sPHENIX GitHub at line 25 of file SvgTrackingGeometryWriter.cpp
ActsExamples::ProcessCode ActsExamples::SvgTrackingGeometryWriter::write (const AlgorithmContext & context, const Acts::TrackingGeometry & tGeometry)
The write interface
Parameters
context the Algorithm/Event context of this call
tGeometry is the geometry to be written out
Returns
ProcessCode to indicate success/failure
Definition at line 29 of file SvgTrackingGeometryWriter.cpp.
View newest version in sPHENIX GitHub at line 29 of file SvgTrackingGeometryWriter.cpp
References ACTS_DEBUG, Acts::Svg::TrackingGeometryConverter::convert(), ActsExamples::AlgorithmContext::geoContext, ActsExamples::joinPaths(), m_cfg(), SUCCESS, and Acts::Svg::toFile().
Member Data Documentation
Config ActsExamples::SvgTrackingGeometryWriter::m_cfg private
the config class
Definition at line 64 of file SvgTrackingGeometryWriter.hpp.
View newest version in sPHENIX GitHub at line 64 of file SvgTrackingGeometryWriter.hpp
std::unique_ptr<const Acts::Logger> ActsExamples::SvgTrackingGeometryWriter::m_logger private
the logger instance
Definition at line 62 of file SvgTrackingGeometryWriter.hpp.
View newest version in sPHENIX GitHub at line 62 of file SvgTrackingGeometryWriter.hpp
Referenced by logger().
std::mutex ActsExamples::SvgTrackingGeometryWriter::m_writeMutex private
Mutex used to protect multi-threaded writes.
Definition at line 66 of file SvgTrackingGeometryWriter.hpp.
View newest version in sPHENIX GitHub at line 66 of file SvgTrackingGeometryWriter.hpp
The documentation for this class was generated from the following files:
acts/blob/sPHENIX/Examples/Io/Svg/include/ActsExamples/Io/Svg/SvgTrackingGeometryWriter.hpp
acts/blob/sPHENIX/Examples/Io/Svg/src/SvgTrackingGeometryWriter.cpp