Analysis Software: acts/blob/sPHENIX/Tests/IntegrationTests/Fatras/FatrasSimulationTests.cpp File Reference
FatrasSimulationTests.cpp File Reference
#include <boost/test/data/test_case.hpp>
#include <boost/test/unit_test.hpp>
#include "Acts/Definitions/ParticleData.hpp"
#include "Acts/EventData/TrackParameters.hpp"
#include "Acts/MagneticField/ConstantBField.hpp"
#include "Acts/Propagator/EigenStepper.hpp"
#include "Acts/Propagator/Navigator.hpp"
#include "Acts/Propagator/StraightLineStepper.hpp"
#include "Acts/Tests/CommonHelpers/CylindricalTrackingGeometry.hpp"
#include "Acts/Utilities/Logger.hpp"
#include "Acts/Utilities/UnitVectors.hpp"
#include "ActsFatras/Kernel/InteractionList.hpp"
#include "ActsFatras/Kernel/Simulation.hpp"
#include "ActsFatras/Physics/Decay/NoDecay.hpp"
#include "ActsFatras/Physics/StandardInteractions.hpp"
#include "ActsFatras/Selectors/ParticleSelectors.hpp"
#include "ActsFatras/Selectors/SurfaceSelectors.hpp"
#include <algorithm>
#include <random>
Functions
BOOST_DATA_TEST_CASE (FatrasSimulation, dataset, pdg, phi, eta, p, numParticles)
Function Documentation
BOOST_DATA_TEST_CASE (FatrasSimulation , dataset , pdg , phi , eta , p , numParticles)
Definition at line 153 of file FatrasSimulationTests.cpp.
View newest version in sPHENIX GitHub at line 153 of file FatrasSimulationTests.cpp
References DEBUG, eta, Acts::findCharge(), Fatras::Test::generator, geoCtx, Acts::getDefaultLogger(), i, digitization_config::input, telescope_simulation::logLevel, magCtx, Acts::makeDirectionFromPhiEta(), testing::internal::move(), Acts::Test::navigator, merge_hashes::p, pdg, ActsTests::PropagationDatasets::phi, train_ambiguity_solver::pid, ActsFatras::Particle::setAbsoluteMomentum(), ActsFatras::Particle::setDirection(), ActsFatras::Barcode::setParticle(), ActsFatras::Barcode::setVertexPrimary(), Acts::trackingGeometry(), and physmon_ckf_tracking::u.