Analysis Software: PHG4EPDDetector Class Reference
PHG4EPDDetector Class Reference
#include <coresoftware/blob/master/simulation/g4simulation/g4epd/PHG4EPDDetector.h>
Public Member Functions
PHG4EPDDetector (PHG4Subsystem *subsys, PHCompositeNode *node, PHParameters *parameters, std::string const &name)
void ConstructMe (G4LogicalVolume *world) override
int IsInDetector (G4VPhysicalVolume *) const
uint32_t module_id_for (uint32_t index, uint32_t slice, uint32_t side)
uint32_t module_id_for (G4VPhysicalVolume *volume)
void SuperDetector (std::string const &name)
const std::string SuperDetector () const
PHG4EPDDisplayAction * GetDisplayAction ()
Public Member Functions inherited from PHG4Detector
PHG4Detector ()=delete
constructor
PHG4Detector (PHG4Subsystem *subsys, PHCompositeNode *Node, const std::string &nam)
virtual ~PHG4Detector (void)
destructor
virtual void Construct (G4LogicalVolume *world) final
construct method
virtual void PostConstruction ()
Optional PostConstruction call after all geometry is constructed.
virtual void Verbosity (const int v)
virtual int Verbosity () const
virtual G4UserSteppingAction * GetSteppingAction ()
virtual std::string GetName () const
virtual void OverlapCheck (const bool chk)
virtual bool OverlapCheck () const
virtual void Print (const std::string &="ALL") const
virtual int DisplayVolume (G4VSolid *volume, G4LogicalVolume *logvol, G4RotationMatrix *rotm=nullptr)
virtual int DisplayVolume (G4LogicalVolume *checksolid, G4LogicalVolume *logvol, G4RotationMatrix *rotm=nullptr)
virtual PHCompositeNode * topNode ()
virtual PHG4Subsystem * GetMySubsystem ()
Private Member Functions
G4ExtrudedSolid * construct_block (int32_t index)
Private Attributes
PHG4EPDDisplayAction * m_DisplayAction = nullptr
PHParameters * m_Params = nullptr
int m_ActiveFlag = 0
int m_SupportActiveFlag = 0
std::set< G4LogicalVolume * > m_SupportLogVolSet
std::set< G4LogicalVolume * > m_ActiveLogVolSet
std::map< G4VPhysicalVolume
*, uint32_t > m_volumes
std::string superdetector
Additional Inherited Members
Static Public Member Functions inherited from PHG4Detector
static G4Material * GetDetectorMaterial (const std::string &name, const bool quit=true)
static G4Element * GetDetectorElement (const std::string &name, const bool quit=true)
Detailed Description
Definition at line 23 of file PHG4EPDDetector.h.
View newest version in sPHENIX GitHub at line 23 of file PHG4EPDDetector.h
Constructor & Destructor Documentation
PHG4EPDDetector::PHG4EPDDetector (PHG4Subsystem * subsys, PHCompositeNode * node, PHParameters * parameters, std::string const & name)
Definition at line 30 of file PHG4EPDDetector.cc.
View newest version in sPHENIX GitHub at line 30 of file PHG4EPDDetector.cc
Member Function Documentation
G4ExtrudedSolid * PHG4EPDDetector::construct_block (int32_t index) private
Definition at line 157 of file PHG4EPDDetector.cc.
View newest version in sPHENIX GitHub at line 157 of file PHG4EPDDetector.cc
References coordinates, double(), dz, i, index, CKF_timing_vs_mu::label, Acts::UnitConstants::mm, to_string(), ActsExamples::HepMC3Event::vertices(), ambiguity_solver_full_chain::x, and y.
Referenced by ConstructMe().
void PHG4EPDDetector::ConstructMe (G4LogicalVolume * world) override virtual
Implements PHG4Detector.
Definition at line 42 of file PHG4EPDDetector.cc.
View newest version in sPHENIX GitHub at line 42 of file PHG4EPDDetector.cc
References PHG4EPDDisplayAction::AddVolume(), Acts::UnitConstants::cm, construct_block(), PHParameters::get_double_param(), PHG4Detector::GetDetectorMaterial(), GetDisplayAction(), i, k, CKF_timing_vs_mu::label, m_ActiveLogVolSet, m_Params, m_volumes, material, module_id_for(), PHG4Detector::OverlapCheck(), and to_string().
PHG4EPDDisplayAction* PHG4EPDDetector::GetDisplayAction () inline
Definition at line 41 of file PHG4EPDDetector.h.
View newest version in sPHENIX GitHub at line 41 of file PHG4EPDDetector.h
References m_DisplayAction.
Referenced by ConstructMe().
int PHG4EPDDetector::IsInDetector (G4VPhysicalVolume * volume) const
Definition at line 90 of file PHG4EPDDetector.cc.
View newest version in sPHENIX GitHub at line 90 of file PHG4EPDDetector.cc
References m_ActiveFlag, m_ActiveLogVolSet, m_SupportActiveFlag, and m_SupportLogVolSet.
Referenced by PHG4EPDSteppingAction::UserSteppingAction().
uint32_t PHG4EPDDetector::module_id_for (uint32_t index, uint32_t slice, uint32_t side)
Definition at line 110 of file PHG4EPDDetector.cc.
View newest version in sPHENIX GitHub at line 110 of file PHG4EPDDetector.cc
References EPDDefs::make_epd_key().
Referenced by ConstructMe(), and PHG4EPDSteppingAction::UserSteppingAction().
uint32_t PHG4EPDDetector::module_id_for (G4VPhysicalVolume * volume)
Definition at line 115 of file PHG4EPDDetector.cc.
View newest version in sPHENIX GitHub at line 115 of file PHG4EPDDetector.cc
References m_volumes.
void PHG4EPDDetector::SuperDetector (std::string const & name) inline
Definition at line 38 of file PHG4EPDDetector.h.
View newest version in sPHENIX GitHub at line 38 of file PHG4EPDDetector.h
References perf_headwind::name, and superdetector.
Referenced by PHG4EPDSubsystem::InitRunSubsystem().
const std::string PHG4EPDDetector::SuperDetector () const inline
Definition at line 39 of file PHG4EPDDetector.h.
View newest version in sPHENIX GitHub at line 39 of file PHG4EPDDetector.h
References superdetector.
Member Data Documentation
int PHG4EPDDetector::m_ActiveFlag = 0 private
Definition at line 49 of file PHG4EPDDetector.h.
View newest version in sPHENIX GitHub at line 49 of file PHG4EPDDetector.h
Referenced by IsInDetector().
std::set<G4LogicalVolume*> PHG4EPDDetector::m_ActiveLogVolSet private
Definition at line 53 of file PHG4EPDDetector.h.
View newest version in sPHENIX GitHub at line 53 of file PHG4EPDDetector.h
Referenced by ConstructMe(), and IsInDetector().
PHG4EPDDisplayAction* PHG4EPDDetector::m_DisplayAction = nullptr private
Definition at line 46 of file PHG4EPDDetector.h.
View newest version in sPHENIX GitHub at line 46 of file PHG4EPDDetector.h
Referenced by GetDisplayAction().
PHParameters* PHG4EPDDetector::m_Params = nullptr private
Definition at line 47 of file PHG4EPDDetector.h.
View newest version in sPHENIX GitHub at line 47 of file PHG4EPDDetector.h
Referenced by ConstructMe().
int PHG4EPDDetector::m_SupportActiveFlag = 0 private
Definition at line 50 of file PHG4EPDDetector.h.
View newest version in sPHENIX GitHub at line 50 of file PHG4EPDDetector.h
Referenced by IsInDetector().
std::set<G4LogicalVolume*> PHG4EPDDetector::m_SupportLogVolSet private
Definition at line 52 of file PHG4EPDDetector.h.
View newest version in sPHENIX GitHub at line 52 of file PHG4EPDDetector.h
Referenced by IsInDetector().
std::map<G4VPhysicalVolume*, uint32_t> PHG4EPDDetector::m_volumes private
Definition at line 55 of file PHG4EPDDetector.h.
View newest version in sPHENIX GitHub at line 55 of file PHG4EPDDetector.h
Referenced by ConstructMe(), and module_id_for().
std::string PHG4EPDDetector::superdetector private
Definition at line 57 of file PHG4EPDDetector.h.
View newest version in sPHENIX GitHub at line 57 of file PHG4EPDDetector.h
Referenced by SuperDetector().
The documentation for this class was generated from the following files:
coresoftware/blob/master/simulation/g4simulation/g4epd/PHG4EPDDetector.h
coresoftware/blob/master/simulation/g4simulation/g4epd/PHG4EPDDetector.cc