Analysis Software: analysis/blob/master/Prototype2/EMCal/macros/SaveCanvas.m File Reference
SaveCanvas.m File Reference
Functions
set (fig,'Units','points') set(fig
set (fig, 'PaperPosition',[0 0 pos(3) pos(4)])
set (fig, 'PaperSize',[pos(3) pos(4)])
print (fig, '-dpng','-r100',[savename '.png'])
print (fig, '-dpdf',[savename '.pdf'])
print (fig, '-depsc',[savename '.eps'])
saveas (fig,[savename '.pdf'])
disp (['Updated Save canvas:Saved to 'savename '.png/.eps/.fig'])
Variables
function prefix
end savename = [savename '.' get(fig,'Name')]
paperunits
points pos = get(fig,'position')
Function Documentation
disp ()
print (fig , '-dpng' , '-r100')
Referenced by acts._adapter::_make_config_adapter(), acts.examples.Sequencer::_printFpeSummary(), TPC_Cluster_Drift_Animator::animate_clusters(), TPC_Cluster_Drift_Animator_beam::animate_clusters(), TPC_Cluster_Drift_Animator::animate_scatters(), TPC_Cluster_Drift_Animator_beam::animate_scatters(), test_examples::assert_entries(), gtest_uninitialized_test::AssertEq(), gtest_env_var_test::AssertEq(), pr_commands::atlas(), check_fpe_masks::check(), generate_particle_data_table::clang_format(), utils::create_file_list(), utils::create_jobs(), plot_DataSimComp::Draw_1Dhist_datasimcomp(), plot_DataSimComp::Draw_1Dhist_datasimcomp_v2(), plot_DataSimComp::Draw_2Dhist_datasimcomp(), acts.examples::dump_args(), acts.examples::dump_args_calls(), GeometryVisualisationAndMaterialHandling::dump_geo(), release::evaluate_version_bump(), utils::event_display(), python_algorithm.PyAlg1::execute(), warnings_filter.WarningsFilter::filter(), fjetResol(), acts.examples.Sequencer.FpeMask::fromFile(), release::generate_changelog(), tgeo-response2json::generate_empty_config(), RecoPV_optimization::get2DTable(), release::get_parsed_commit_range(), utils::get_status(), Acts::getDefaultLogger(), acts.examples.simulation::getG4DetectorConstructionFactory(), tgeo-response2json::getopts(), writeMapConfig::getSurfaceMaterial(), cpp.tokenize::GetTokens(), utils::hadd(), quick_view::help(), global-time-converter::help(), hijing(), hijset(), itafun(), check_end_of_file::main(), make_inp_lists::main(), plot-woods-saxon::main(), main(), generic_plotter::main(), tgeo-response2json::main(), check_include_guards::main(), check_license::main(), parse_clang_tidy::main(), Orion_tuning::main(), Optuna_tuning::main(), smearing-config::main(), fuse_gtest_files::main(), cpp.tokenize::main(), cpp.ast::main(), release::make_release(), makeCondorJobs::makeCondorJob(), Acts::operator<<(), parse_clang_tidy::parse_clang_tidy_item(), release::pr_action(), print_units_physical_constants::print_constants(), ActsExamples::Options::detail::printDoubles(), cpp.ast::PrintIndentifiers(), ActsExamples::Options::detail::printIntegers(), tgeo-response2json::process(), pyptfs(), pyptis(), pytbdy(), GeometryVisualisationAndMaterialHandling::read_and_modify(), TPC_Cluster_Drift_Animator::read_cluster_pos(), TPC_Cluster_Drift_Animator_beam::read_cluster_pos(), cpp.utils::ReadFile(), gtest_throw_on_failure_test::Run(), utils::run_analysis(), bfield_writing::runBFieldWriting(), itk_seeding::runITkSeedingFromCsv(), material_mapping_optimisation::runMaterialMappingVariance(), propagation::runPropagation(), set_range(), material_mapping_optimisation::surfaceExperiment(), test_base::test_constructors(), test_examples::test_event_recording(), test_examples::test_exatrkx(), test_fpe::test_fpe_context(), test_examples::test_full_chain_odd_example(), test_examples::test_full_chain_odd_example_pythia_geant4(), test_examples::test_geant4(), test_examples::test_ML_Ambiguity_Solver(), train_ambiguity_solver::train(), tgeo-response2json::usage(), ActsExamples::SensitiveSteppingAction::UserSteppingAction(), fuse_gtest_files::VerifyFileExists(), and fuse_gtest_files::VerifyOutputFile().
print (fig , '-dpdf')
print (fig , '-depsc')
saveas (fig)
set (fig , 'Units' , 'points')
set (fig , 'PaperPosition')
set (fig , 'PaperSize')
Variable Documentation
paperunits
Definition at line 11 of file SaveCanvas.m.
View newest version in sPHENIX GitHub at line 11 of file SaveCanvas.m
points pos = get(fig,'position')
Definition at line 12 of file SaveCanvas.m.
View newest version in sPHENIX GitHub at line 12 of file SaveCanvas.m
Referenced by init(), and medinit().
prefix
Initial value:
= SaveCanvas(savename,fig)
if nargin <= 1
    fig = gcf
Definition at line 1 of file SaveCanvas.m.
View newest version in sPHENIX GitHub at line 1 of file SaveCanvas.m
Referenced by testing::gmock_generated_actions_test::ACTION_P2(), noiPads::add_pad(), Acts::Python::addSvg(), Draw(), MvtxMonDraw::DrawHitMap(), PgPostBankBackupManager::getBankBaseName(), SubSystem::GetCanvases(), PHG4CylinderGeom_Spacalv3::ImportParameters(), PHG4CylinderGeom_Spacalv1::ImportParameters(), noiPads::init(), noiUniqueName(), ActsExamples::perEventFilepath(), ElectronID::process_event(), and VertexingQA().
end savename = [savename '.' get(fig,'Name')]
Definition at line 7 of file SaveCanvas.m.
View newest version in sPHENIX GitHub at line 7 of file SaveCanvas.m