Analysis Software: ActsExamples::SimSpacePoint Class Reference
ActsExamples::SimSpacePoint Class Reference
Space point representation of a measurement suitable for track seeding.
#include <acts/blob/sPHENIX/Examples/Framework/include/ActsExamples/EventData/SimSpacePoint.hpp>
Public Member Functions
template<typename position_t >
SimSpacePoint (const Eigen::MatrixBase< position_t > &pos, float varRho, float varZ, boost::container::static_vector< Acts::SourceLink, 2 > sourceLinks, const float topHalfStripLength, const float bottomHalfStripLength, const Acts::Vector3 &topStripDirection, const Acts::Vector3 &bottomStripDirection, const Acts::Vector3 &stripCenterDistance, const Acts::Vector3 &topStripCenterPosition)
template<typename position_t >
SimSpacePoint (const Eigen::MatrixBase< position_t > &pos, Scalar varRho, Scalar varZ, boost::container::static_vector< Acts::SourceLink, 2 > sourceLinks)
constexpr Scalar x () const
constexpr Scalar y () const
constexpr Scalar z () const
constexpr Scalar r () const
constexpr Scalar varianceR () const
constexpr Scalar varianceZ () const
const
boost::container::static_vector
< Acts::SourceLink, 2 > & sourceLinks () const
constexpr float topHalfStripLength () const
constexpr float bottomHalfStripLength () const
Acts::Vector3 topStripDirection () const
Acts::Vector3 bottomStripDirection () const
Acts::Vector3 stripCenterDistance () const
Acts::Vector3 topStripCenterPosition () const
constexpr bool validDoubleMeasurementDetails () const
Private Types
using Scalar = Acts::ActsScalar
Private Attributes
Scalar m_x
Scalar m_y
Scalar m_z
Scalar m_rho
Scalar m_varianceRho
Scalar m_varianceZ
boost::container::static_vector
< Acts::SourceLink, 2 > m_sourceLinks
float m_topHalfStripLength = 0
float m_bottomHalfStripLength = 0
Acts::Vector3 m_topStripDirection = {0, 0, 0}
Acts::Vector3 m_bottomStripDirection = {0, 0, 0}
Acts::Vector3 m_stripCenterDistance = {0, 0, 0}
Acts::Vector3 m_topStripCenterPosition = {0, 0, 0}
bool m_validDoubleMeasurementDetails = false
Detailed Description
Space point representation of a measurement suitable for track seeding.
Definition at line 25 of file SimSpacePoint.hpp.
View newest version in sPHENIX GitHub at line 25 of file SimSpacePoint.hpp
Member Typedef Documentation
using ActsExamples::SimSpacePoint::Scalar = Acts::ActsScalar private
Definition at line 26 of file SimSpacePoint.hpp.
View newest version in sPHENIX GitHub at line 26 of file SimSpacePoint.hpp
Constructor & Destructor Documentation
template<typename position_t > ActsExamples::SimSpacePoint::SimSpacePoint (const Eigen::MatrixBase< position_t > & pos, float varRho, float varZ, boost::container::static_vector< Acts::SourceLink, 2 > sourceLinks, const float topHalfStripLength, const float bottomHalfStripLength, const Acts::Vector3 & topStripDirection, const Acts::Vector3 & bottomStripDirection, const Acts::Vector3 & stripCenterDistance, const Acts::Vector3 & topStripCenterPosition) inline
Construct the space point from global position and selected variances.
Template Parameters
position_t Input position type
Parameters
pos Global position
varRho Measurement variance of the global transverse distance
varZ Measurement variance of the global longitudinal position
sourceLinks sourceLinks of the measurements
topHalfStripLength half of the length of the top strip
bottomHalfStripLength half of the length of the bottom strip
topStripDirection direction of the top strip
bottomStripDirection direction of the bottom strip
stripCenterDistance distance between the center of the two strips
topStripCenterPosition position of the center of the top strip
validDoubleMeasurementDetails boolean to check if double measurements are valid
Definition at line 44 of file SimSpacePoint.hpp.
View newest version in sPHENIX GitHub at line 44 of file SimSpacePoint.hpp
template<typename position_t > ActsExamples::SimSpacePoint::SimSpacePoint (const Eigen::MatrixBase< position_t > & pos, Scalar varRho, Scalar varZ, boost::container::static_vector< Acts::SourceLink, 2 > sourceLinks) inline
Construct the space point from global position and selected variances.
Template Parameters
position_t Input position type
Parameters
pos Global position
varRho Measurement variance of the global transverse distance
varZ Measurement variance of the global longitudinal position
sourceLinks sourceLinks of the measurements
Definition at line 77 of file SimSpacePoint.hpp.
View newest version in sPHENIX GitHub at line 77 of file SimSpacePoint.hpp
Member Function Documentation
constexpr float ActsExamples::SimSpacePoint::bottomHalfStripLength () const inline
Definition at line 103 of file SimSpacePoint.hpp.
View newest version in sPHENIX GitHub at line 103 of file SimSpacePoint.hpp
References m_bottomHalfStripLength.
Referenced by ActsExamples::SeedingAlgorithm::SeedingAlgorithm().
Acts::Vector3 ActsExamples::SimSpacePoint::bottomStripDirection () const inline
Definition at line 107 of file SimSpacePoint.hpp.
View newest version in sPHENIX GitHub at line 107 of file SimSpacePoint.hpp
References m_bottomStripDirection.
Referenced by ActsExamples::SeedingAlgorithm::SeedingAlgorithm().
constexpr Scalar ActsExamples::SimSpacePoint::r () const inline
Definition at line 93 of file SimSpacePoint.hpp.
View newest version in sPHENIX GitHub at line 93 of file SimSpacePoint.hpp
References m_rho.
Referenced by ActsExamples::TruthSeedingAlgorithm::execute().
const boost::container::static_vector<Acts::SourceLink, 2>& ActsExamples::SimSpacePoint::sourceLinks () const inline
Definition at line 97 of file SimSpacePoint.hpp.
View newest version in sPHENIX GitHub at line 97 of file SimSpacePoint.hpp
References m_sourceLinks.
Referenced by ActsExamples::findSpacePointForIndex(), and ActsExamples::operator==().
Acts::Vector3 ActsExamples::SimSpacePoint::stripCenterDistance () const inline
Definition at line 108 of file SimSpacePoint.hpp.
View newest version in sPHENIX GitHub at line 108 of file SimSpacePoint.hpp
References m_stripCenterDistance.
Referenced by ActsExamples::SeedingAlgorithm::SeedingAlgorithm().
constexpr float ActsExamples::SimSpacePoint::topHalfStripLength () const inline
Definition at line 102 of file SimSpacePoint.hpp.
View newest version in sPHENIX GitHub at line 102 of file SimSpacePoint.hpp
References m_topHalfStripLength.
Referenced by ActsExamples::SeedingAlgorithm::SeedingAlgorithm().
Acts::Vector3 ActsExamples::SimSpacePoint::topStripCenterPosition () const inline
Definition at line 109 of file SimSpacePoint.hpp.
View newest version in sPHENIX GitHub at line 109 of file SimSpacePoint.hpp
References m_topStripCenterPosition.
Referenced by ActsExamples::SeedingAlgorithm::SeedingAlgorithm().
Acts::Vector3 ActsExamples::SimSpacePoint::topStripDirection () const inline
Definition at line 106 of file SimSpacePoint.hpp.
View newest version in sPHENIX GitHub at line 106 of file SimSpacePoint.hpp
References m_topStripDirection.
Referenced by ActsExamples::SeedingAlgorithm::SeedingAlgorithm().
constexpr bool ActsExamples::SimSpacePoint::validDoubleMeasurementDetails () const inline
Definition at line 112 of file SimSpacePoint.hpp.
View newest version in sPHENIX GitHub at line 112 of file SimSpacePoint.hpp
References m_validDoubleMeasurementDetails.
constexpr Scalar ActsExamples::SimSpacePoint::varianceR () const inline
Definition at line 94 of file SimSpacePoint.hpp.
View newest version in sPHENIX GitHub at line 94 of file SimSpacePoint.hpp
References m_varianceRho.
Referenced by ActsExamples::SeedingOrthogonalAlgorithm::execute(), ActsExamples::SeedingFTFAlgorithm::execute(), ActsExamples::SeedingAlgorithm::execute(), and ActsExamples::operator==().
constexpr Scalar ActsExamples::SimSpacePoint::varianceZ () const inline
Definition at line 95 of file SimSpacePoint.hpp.
View newest version in sPHENIX GitHub at line 95 of file SimSpacePoint.hpp
References m_varianceZ.
Referenced by ActsExamples::SeedingOrthogonalAlgorithm::execute(), ActsExamples::SeedingFTFAlgorithm::execute(), ActsExamples::SeedingAlgorithm::execute(), and ActsExamples::operator==().
constexpr Scalar ActsExamples::SimSpacePoint::x () const inline
Definition at line 90 of file SimSpacePoint.hpp.
View newest version in sPHENIX GitHub at line 90 of file SimSpacePoint.hpp
References m_x.
Referenced by ActsExamples::SeedingOrthogonalAlgorithm::execute(), ActsExamples::SeedingFTFAlgorithm::execute(), ActsExamples::SeedingAlgorithm::execute(), and ActsExamples::operator==().
constexpr Scalar ActsExamples::SimSpacePoint::y () const inline
Definition at line 91 of file SimSpacePoint.hpp.
View newest version in sPHENIX GitHub at line 91 of file SimSpacePoint.hpp
References m_y.
Referenced by ActsExamples::SeedingOrthogonalAlgorithm::execute(), ActsExamples::SeedingFTFAlgorithm::execute(), ActsExamples::SeedingAlgorithm::execute(), and ActsExamples::operator==().
constexpr Scalar ActsExamples::SimSpacePoint::z () const inline
Definition at line 92 of file SimSpacePoint.hpp.
View newest version in sPHENIX GitHub at line 92 of file SimSpacePoint.hpp
References m_z.
Referenced by ActsExamples::SeedingOrthogonalAlgorithm::execute(), ActsExamples::SeedingFTFAlgorithm::execute(), ActsExamples::TruthSeedingAlgorithm::execute(), ActsExamples::SeedingAlgorithm::execute(), and ActsExamples::operator==().
Member Data Documentation
float ActsExamples::SimSpacePoint::m_bottomHalfStripLength = 0 private
Definition at line 132 of file SimSpacePoint.hpp.
View newest version in sPHENIX GitHub at line 132 of file SimSpacePoint.hpp
Referenced by bottomHalfStripLength().
Acts::Vector3 ActsExamples::SimSpacePoint::m_bottomStripDirection = {0, 0, 0} private
Definition at line 136 of file SimSpacePoint.hpp.
View newest version in sPHENIX GitHub at line 136 of file SimSpacePoint.hpp
Referenced by bottomStripDirection().
Scalar ActsExamples::SimSpacePoint::m_rho private
Definition at line 121 of file SimSpacePoint.hpp.
View newest version in sPHENIX GitHub at line 121 of file SimSpacePoint.hpp
Referenced by r().
boost::container::static_vector<Acts::SourceLink, 2> ActsExamples::SimSpacePoint::m_sourceLinks private
Definition at line 127 of file SimSpacePoint.hpp.
View newest version in sPHENIX GitHub at line 127 of file SimSpacePoint.hpp
Referenced by sourceLinks().
Acts::Vector3 ActsExamples::SimSpacePoint::m_stripCenterDistance = {0, 0, 0} private
Definition at line 138 of file SimSpacePoint.hpp.
View newest version in sPHENIX GitHub at line 138 of file SimSpacePoint.hpp
Referenced by stripCenterDistance().
float ActsExamples::SimSpacePoint::m_topHalfStripLength = 0 private
Definition at line 130 of file SimSpacePoint.hpp.
View newest version in sPHENIX GitHub at line 130 of file SimSpacePoint.hpp
Referenced by topHalfStripLength().
Acts::Vector3 ActsExamples::SimSpacePoint::m_topStripCenterPosition = {0, 0, 0} private
Definition at line 140 of file SimSpacePoint.hpp.
View newest version in sPHENIX GitHub at line 140 of file SimSpacePoint.hpp
Referenced by topStripCenterPosition().
Acts::Vector3 ActsExamples::SimSpacePoint::m_topStripDirection = {0, 0, 0} private
Definition at line 134 of file SimSpacePoint.hpp.
View newest version in sPHENIX GitHub at line 134 of file SimSpacePoint.hpp
Referenced by topStripDirection().
bool ActsExamples::SimSpacePoint::m_validDoubleMeasurementDetails = false private
Definition at line 141 of file SimSpacePoint.hpp.
View newest version in sPHENIX GitHub at line 141 of file SimSpacePoint.hpp
Referenced by validDoubleMeasurementDetails().
Scalar ActsExamples::SimSpacePoint::m_varianceRho private
Definition at line 123 of file SimSpacePoint.hpp.
View newest version in sPHENIX GitHub at line 123 of file SimSpacePoint.hpp
Referenced by varianceR().
Scalar ActsExamples::SimSpacePoint::m_varianceZ private
Definition at line 124 of file SimSpacePoint.hpp.
View newest version in sPHENIX GitHub at line 124 of file SimSpacePoint.hpp
Referenced by varianceZ().
Scalar ActsExamples::SimSpacePoint::m_x private
Definition at line 118 of file SimSpacePoint.hpp.
View newest version in sPHENIX GitHub at line 118 of file SimSpacePoint.hpp
Referenced by x().
Scalar ActsExamples::SimSpacePoint::m_y private
Definition at line 119 of file SimSpacePoint.hpp.
View newest version in sPHENIX GitHub at line 119 of file SimSpacePoint.hpp
Referenced by y().
Scalar ActsExamples::SimSpacePoint::m_z private
Definition at line 120 of file SimSpacePoint.hpp.
View newest version in sPHENIX GitHub at line 120 of file SimSpacePoint.hpp
Referenced by z().
The documentation for this class was generated from the following file:
acts/blob/sPHENIX/Examples/Framework/include/ActsExamples/EventData/SimSpacePoint.hpp