Analysis Software: nanoflann::CArray< T, N > Class Template Reference
nanoflann::CArray< T, N > Class Template Reference
Auxiliary metaprogramming stuff
#include <coresoftware/blob/master/offline/packages/trackreco/nanoflann.hpp>
Public Types
enum { static_size = N }
typedef T value_type
typedef T * iterator
typedef const T * const_iterator
typedef T & reference
typedef const T & const_reference
typedef std::size_t size_type
typedef std::ptrdiff_t difference_type
typedef std::reverse_iterator
< iterator > reverse_iterator
typedef std::reverse_iterator
< const_iterator > const_reverse_iterator
Public Member Functions
iterator begin ()
const_iterator begin () const
iterator end ()
const_iterator end () const
reverse_iterator rbegin ()
const_reverse_iterator rbegin () const
reverse_iterator rend ()
const_reverse_iterator rend () const
reference operator[] (size_type i)
const_reference operator[] (size_type i) const
reference at (size_type i)
const_reference at (size_type i) const
reference front ()
const_reference front () const
reference back ()
const_reference back () const
void resize (const size_t nElements)
void swap (CArray< T, N > &y)
const T * data () const
T * data ()
template<typename T2 >
CArray< T, N > & operator= (const CArray< T2, N > &rhs)
void assign (const T &value)
void assign (const size_t n, const T &value)
Static Public Member Functions
static size_type size ()
static bool empty ()
static size_type max_size ()
Public Attributes
T elems [N]
Static Private Member Functions
static void rangecheck (size_type i)
Detailed Description
template<typename T, std::size_t N>
class nanoflann::CArray< T, N >
A STL container (as wrapper) for arrays of constant size defined at compile time (class imported from the MRPT project) This code is an adapted version from Boost, modifed for its integration within MRPT (JLBC, Dec/2009) (Renamed array -> CArray to avoid possible potential conflicts). See http://www.josuttis.com/cppcode for details and the latest version. See http://www.boost.org/libs/array for Documentation. for documentation.
(C) Copyright Nicolai M. Josuttis 2001. Permission to copy, use, modify, sell and distribute this software is granted provided this copyright notice appears in all copies. This software is provided "as is" without express or implied warranty, and with no claim as to its suitability for any purpose.
29 Jan 2004 - minor fixes (Nico Josuttis) 04 Dec 2003 - update to synch with library TR1 (Alisdair Meredith) 23 Aug 2002 - fix for Non-MSVC compilers combined with MSVC libraries. 05 Aug 2001 - minor update (Nico Josuttis) 20 Jan 2001 - STLport fix (Beman Dawes) 29 Sep 2000 - Initial Revision (Nico Josuttis)
Jan 30, 2004
Definition at line 645 of file nanoflann.hpp.
View newest version in sPHENIX GitHub at line 645 of file nanoflann.hpp
Member Typedef Documentation
template<typename T, std::size_t N> typedef const T* nanoflann::CArray< T, N >::const_iterator
Definition at line 654 of file nanoflann.hpp.
View newest version in sPHENIX GitHub at line 654 of file nanoflann.hpp
template<typename T, std::size_t N> typedef const T& nanoflann::CArray< T, N >::const_reference
Definition at line 656 of file nanoflann.hpp.
View newest version in sPHENIX GitHub at line 656 of file nanoflann.hpp
template<typename T, std::size_t N> typedef std::reverse_iterator<const_iterator> nanoflann::CArray< T, N >::const_reverse_iterator
Definition at line 669 of file nanoflann.hpp.
View newest version in sPHENIX GitHub at line 669 of file nanoflann.hpp
template<typename T, std::size_t N> typedef std::ptrdiff_t nanoflann::CArray< T, N >::difference_type
Definition at line 658 of file nanoflann.hpp.
View newest version in sPHENIX GitHub at line 658 of file nanoflann.hpp
template<typename T, std::size_t N> typedef T* nanoflann::CArray< T, N >::iterator
Definition at line 653 of file nanoflann.hpp.
View newest version in sPHENIX GitHub at line 653 of file nanoflann.hpp
template<typename T, std::size_t N> typedef T& nanoflann::CArray< T, N >::reference
Definition at line 655 of file nanoflann.hpp.
View newest version in sPHENIX GitHub at line 655 of file nanoflann.hpp
template<typename T, std::size_t N> typedef std::reverse_iterator<iterator> nanoflann::CArray< T, N >::reverse_iterator
Definition at line 668 of file nanoflann.hpp.
View newest version in sPHENIX GitHub at line 668 of file nanoflann.hpp
template<typename T, std::size_t N> typedef std::size_t nanoflann::CArray< T, N >::size_type
Definition at line 657 of file nanoflann.hpp.
View newest version in sPHENIX GitHub at line 657 of file nanoflann.hpp
template<typename T, std::size_t N> typedef T nanoflann::CArray< T, N >::value_type
Definition at line 652 of file nanoflann.hpp.
View newest version in sPHENIX GitHub at line 652 of file nanoflann.hpp
Member Enumeration Documentation
template<typename T, std::size_t N> anonymous enum
Enumerator:
static_size
Definition at line 714 of file nanoflann.hpp.
View newest version in sPHENIX GitHub at line 714 of file nanoflann.hpp
Member Function Documentation
template<typename T, std::size_t N> void nanoflann::CArray< T, N >::assign (const T & value) inline
Definition at line 738 of file nanoflann.hpp.
View newest version in sPHENIX GitHub at line 738 of file nanoflann.hpp
References i, and N.
Referenced by nanoflann::KDTreeSingleIndexAdaptor< Distance, DatasetAdaptor, DIM, IndexType >::findNeighbors().
template<typename T, std::size_t N> void nanoflann::CArray< T, N >::assign (const size_t n, const T & value) inline
Definition at line 743 of file nanoflann.hpp.
View newest version in sPHENIX GitHub at line 743 of file nanoflann.hpp
References assert, i, and N.
template<typename T, std::size_t N> reference nanoflann::CArray< T, N >::at (size_type i) inline
Definition at line 695 of file nanoflann.hpp.
View newest version in sPHENIX GitHub at line 695 of file nanoflann.hpp
References i.
template<typename T, std::size_t N> const_reference nanoflann::CArray< T, N >::at (size_type i) const inline
Definition at line 700 of file nanoflann.hpp.
View newest version in sPHENIX GitHub at line 700 of file nanoflann.hpp
References i.
template<typename T, std::size_t N> reference nanoflann::CArray< T, N >::back () inline
Definition at line 708 of file nanoflann.hpp.
View newest version in sPHENIX GitHub at line 708 of file nanoflann.hpp
References N.
template<typename T, std::size_t N> const_reference nanoflann::CArray< T, N >::back () const inline
Definition at line 709 of file nanoflann.hpp.
View newest version in sPHENIX GitHub at line 709 of file nanoflann.hpp
References N.
template<typename T, std::size_t N> iterator nanoflann::CArray< T, N >::begin (void) inline
Definition at line 661 of file nanoflann.hpp.
View newest version in sPHENIX GitHub at line 661 of file nanoflann.hpp
Referenced by nanoflann::CArray< T, N >::operator=(), and nanoflann::CArray< T, N >::swap().
template<typename T, std::size_t N> const_iterator nanoflann::CArray< T, N >::begin (void) const inline
Definition at line 662 of file nanoflann.hpp.
View newest version in sPHENIX GitHub at line 662 of file nanoflann.hpp
template<typename T, std::size_t N> const T* nanoflann::CArray< T, N >::data () const inline
Definition at line 726 of file nanoflann.hpp.
View newest version in sPHENIX GitHub at line 726 of file nanoflann.hpp
template<typename T, std::size_t N> T* nanoflann::CArray< T, N >::data () inline
Definition at line 728 of file nanoflann.hpp.
View newest version in sPHENIX GitHub at line 728 of file nanoflann.hpp
template<typename T, std::size_t N> static bool nanoflann::CArray< T, N >::empty () inline static
Definition at line 712 of file nanoflann.hpp.
View newest version in sPHENIX GitHub at line 712 of file nanoflann.hpp
template<typename T, std::size_t N> iterator nanoflann::CArray< T, N >::end (void) inline
Definition at line 663 of file nanoflann.hpp.
View newest version in sPHENIX GitHub at line 663 of file nanoflann.hpp
References N.
Referenced by nanoflann::CArray< T, N >::operator=().
template<typename T, std::size_t N> const_iterator nanoflann::CArray< T, N >::end (void) const inline
Definition at line 664 of file nanoflann.hpp.
View newest version in sPHENIX GitHub at line 664 of file nanoflann.hpp
References N.
template<typename T, std::size_t N> reference nanoflann::CArray< T, N >::front () inline
Definition at line 706 of file nanoflann.hpp.
View newest version in sPHENIX GitHub at line 706 of file nanoflann.hpp
template<typename T, std::size_t N> const_reference nanoflann::CArray< T, N >::front () const inline
Definition at line 707 of file nanoflann.hpp.
View newest version in sPHENIX GitHub at line 707 of file nanoflann.hpp
template<typename T, std::size_t N> static size_type nanoflann::CArray< T, N >::max_size () inline static
Definition at line 713 of file nanoflann.hpp.
View newest version in sPHENIX GitHub at line 713 of file nanoflann.hpp
References N.
template<typename T, std::size_t N> template<typename T2 > CArray<T, N>& nanoflann::CArray< T, N >::operator= (const CArray< T2, N > & rhs) inline
Definition at line 732 of file nanoflann.hpp.
View newest version in sPHENIX GitHub at line 732 of file nanoflann.hpp
References parse_cmake_options::begin, nanoflann::CArray< T, N >::begin(), and nanoflann::CArray< T, N >::end().
template<typename T, std::size_t N> reference nanoflann::CArray< T, N >::operator[] (size_type i) inline
Definition at line 692 of file nanoflann.hpp.
View newest version in sPHENIX GitHub at line 692 of file nanoflann.hpp
References i.
template<typename T, std::size_t N> const_reference nanoflann::CArray< T, N >::operator[] (size_type i) const inline
Definition at line 693 of file nanoflann.hpp.
View newest version in sPHENIX GitHub at line 693 of file nanoflann.hpp
References i.
template<typename T, std::size_t N> static void nanoflann::CArray< T, N >::rangecheck (size_type i) inline static private
Definition at line 751 of file nanoflann.hpp.
View newest version in sPHENIX GitHub at line 751 of file nanoflann.hpp
References nanoflann::KNNResultSet< DistanceType, IndexType, CountType >::size().
template<typename T, std::size_t N> reverse_iterator nanoflann::CArray< T, N >::rbegin () inline
Definition at line 684 of file nanoflann.hpp.
View newest version in sPHENIX GitHub at line 684 of file nanoflann.hpp
References end.
template<typename T, std::size_t N> const_reverse_iterator nanoflann::CArray< T, N >::rbegin () const inline
Definition at line 688 of file nanoflann.hpp.
View newest version in sPHENIX GitHub at line 688 of file nanoflann.hpp
References end.
template<typename T, std::size_t N> reverse_iterator nanoflann::CArray< T, N >::rend () inline
Definition at line 689 of file nanoflann.hpp.
View newest version in sPHENIX GitHub at line 689 of file nanoflann.hpp
References parse_cmake_options::begin.
template<typename T, std::size_t N> const_reverse_iterator nanoflann::CArray< T, N >::rend () const inline
Definition at line 690 of file nanoflann.hpp.
View newest version in sPHENIX GitHub at line 690 of file nanoflann.hpp
References parse_cmake_options::begin.
template<typename T, std::size_t N> void nanoflann::CArray< T, N >::resize (const size_t nElements) inline
This method has no effects in this class, but raises an exception if the expected size does not match
Definition at line 719 of file nanoflann.hpp.
View newest version in sPHENIX GitHub at line 719 of file nanoflann.hpp
References N.
template<typename T, std::size_t N> static size_type nanoflann::CArray< T, N >::size (void) inline static
Definition at line 711 of file nanoflann.hpp.
View newest version in sPHENIX GitHub at line 711 of file nanoflann.hpp
References N.
template<typename T, std::size_t N> void nanoflann::CArray< T, N >::swap (CArray< T, N > & y) inline
Definition at line 724 of file nanoflann.hpp.
View newest version in sPHENIX GitHub at line 724 of file nanoflann.hpp
References parse_cmake_options::begin, nanoflann::CArray< T, N >::begin(), and end.
Member Data Documentation
template<typename T, std::size_t N> T nanoflann::CArray< T, N >::elems[N]
Definition at line 648 of file nanoflann.hpp.
View newest version in sPHENIX GitHub at line 648 of file nanoflann.hpp
The documentation for this class was generated from the following file:
coresoftware/blob/master/offline/packages/trackreco/nanoflann.hpp