Analysis Software: prototype/blob/master/macros/tpc2019/SaveCanvas.C File Reference
SaveCanvas.C File Reference
#include <TList.h>
#include <TClass.h>
#include <TCanvas.h>
#include <TPad.h>
#include <TString.h>
#include <TDirectory.h>
#include <TFile.h>
#include <TStyle.h>
#include <TObject.h>
#include <TSystem.h>
#include <TH1F.h>
#include <iostream>
Macros
#define SaveCanvas_C
Functions
void SavePad (TPad *p)
Service function to SaveCanvas()
void SaveCanvas (TCanvas *c, TString name="", Bool_t bEPS=kTRUE)
Save canvas to multiple formats.
void example_save_canvas ()
example to use this SaveCanvas()
Macro Definition Documentation
#define SaveCanvas_C
Definition at line 13 of file SaveCanvas.C.
View newest version in sPHENIX GitHub at line 13 of file SaveCanvas.C
Function Documentation
void example_save_canvas ()
example to use this SaveCanvas()
Output: The canvas data will be saved to RootFileName.root, as well as RootFileName.png for presentation and RootFileName.eps for Latex
How to use RootFileName.root open RootFileName.root with root. It contains the canvas object "CanvasTest", which can be redraw with CanvasTest -> Draw() It also contains a copy of the histograms and graphs data for use in root again, e.g. root [3] h1->GetBinContent(30)
Definition at line 136 of file SaveCanvas.C.
View newest version in sPHENIX GitHub at line 136 of file SaveCanvas.C
References h1, and SaveCanvas().
void SaveCanvas (TCanvas * c, TString name = "", Bool_t bEPS = kTRUE)
Save canvas to multiple formats.
Parameters
[in] c pointer to the canvas
[in] name Base of the file name. The default is the name of the cavas
[in] bEPS true = save .eps and .pdf format too.
Definition at line 81 of file SaveCanvas.C.
View newest version in sPHENIX GitHub at line 81 of file SaveCanvas.C
References f, perf_headwind::name, SavePad(), ambiguity_solver_full_chain::x, and y.
void SavePad (TPad * p)
Service function to SaveCanvas()
Definition at line 33 of file SaveCanvas.C.
View newest version in sPHENIX GitHub at line 33 of file SaveCanvas.C
References next, merge_hashes::p, and SavePad().