Analysis Software: PHActsTrkFitter Class Reference
PHActsTrkFitter Class Reference
#include <coresoftware/blob/master/offline/packages/trackreco/PHActsTrkFitter.h>
Public Member Functions
PHActsTrkFitter (const std::string &name="PHActsTrkFitter")
Default constructor.
~PHActsTrkFitter () override=default
Destructor.
int End (PHCompositeNode *topNode) override
End, write and close files.
int InitRun (PHCompositeNode *topNode) override
Get and create nodes.
int process_event (PHCompositeNode *topNode) override
Process each event by calling the fitter.
int ResetEvent (PHCompositeNode *topNode) override
Clean up after each event.
void doTimeAnalysis (bool timeAnalysis)
Do some internal time benchmarking analysis.
void fitSiliconMMs (bool fitSiliconMMs)
Run the direct navigator to fit only tracks with silicon+MM hits.
void setUseMicromegas (bool value)
require micromegas in SiliconMM fits
void setUpdateSvtxTrackStates (bool fillSvtxTrackStates)
void useActsEvaluator (bool actsEvaluator)
void setEvaluatorName (const std::string &name)
void setFieldMap (const std::string &fieldMap)
void setAbsPdgHypothesis (unsigned int pHypothesis)
void commissioning (bool com)
void useOutlierFinder (bool outlier)
void SetIteration (int iter)
void set_track_map_name (const std::string &map_name)
void set_seed_track_map_name (const std::string &map_name)
void set_pp_mode (bool ispp)
Set flag for pp running.
void ignoreLayer (int layer)
Public Member Functions inherited from SubsysReco
~SubsysReco () override
virtual int EndRun (const int)
Called at the end of each run.
virtual int Init (PHCompositeNode *)
virtual int Reset (PHCompositeNode *)
Reset.
void Print (const std::string &="ALL") const override
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Private Member Functions
int getNodes (PHCompositeNode *topNode)
Get all the nodes.
int createNodes (PHCompositeNode *topNode)
Create new nodes.
void loopTracks (Acts::Logging::Level logLevel)
void updateSvtxTrack (std::vector< Acts::MultiTrajectoryTraits::IndexType > &tips, Trajectory::IndexedParameters &paramsMap, ActsTrackFittingAlgorithm::TrackContainer &tracks, SvtxTrack *track)
Convert the acts track fit result to an svtx track.
ActsTrackFittingAlgorithm::TrackFitterResult fitTrack (const std::vector< Acts::SourceLink > &sourceLinks, const ActsTrackFittingAlgorithm::TrackParameters &seed, const ActsTrackFittingAlgorithm::GeneralFitterOptions &kfOptions, const SurfacePtrVec &surfSequence, const CalibratorAdapter &calibrator, ActsTrackFittingAlgorithm::TrackContainer &tracks)
SourceLinkVec getSurfaceVector (const SourceLinkVec &sourceLinks, SurfacePtrVec &surfaces) const
void checkSurfaceVec (SurfacePtrVec &surfaces) const
bool getTrackFitResult (FitResult &fitOutput, TrackSeed *seed, SvtxTrack *track, ActsTrackFittingAlgorithm::TrackContainer &tracks, const ActsTrackFittingAlgorithm::MeasurementContainer &measurements)
Acts::BoundSquareMatrix setDefaultCovariance () const
void printTrackSeed (const ActsTrackFittingAlgorithm::TrackParameters &seed) const
Private Attributes
int m_event = 0
Event counter.
ActsGeometry * m_tGeometry = nullptr
Options that Acts::Fitter needs to run from MakeActsGeometry.
ActsTrackFittingAlgorithm::Config m_fitCfg
Configuration containing the fitting function instance.
alignmentTransformationContainer * m_alignmentTransformationMap = nullptr
TrackMap containing SvtxTracks.
alignmentTransformationContainer * m_alignmentTransformationMapTransient = nullptr
std::set
< Acts::GeometryIdentifier > m_transient_id_set
Acts::GeometryContext m_transient_geocontext
SvtxTrackMap * m_trackMap = nullptr
SvtxTrackMap * m_directedTrackMap = nullptr
TrkrClusterContainer * m_clusterContainer = nullptr
TrackSeedContainer * m_seedMap = nullptr
TrackSeedContainer * m_tpcSeeds = nullptr
TrackSeedContainer * m_siliconSeeds = nullptr
int m_nBadFits = 0
Number of acts fits that returned an error.
bool m_fitSiliconMMs = false
bool m_useMicromegas = true
requires micromegas present when fitting silicon-MM surfaces
bool m_fillSvtxTrackStates = true
A bool to update the SvtxTrackState information (or not)
bool m_useOutlierFinder = false
A bool to use the chi2 outlier finder in the track fitting.
ResidualOutlierFinder m_outlierFinder
bool m_pp_mode = false
Flag for pp running.
short int max_bunch_search = 2
bool m_actsEvaluator = false
std::unique_ptr< ActsEvaluator > m_evaluator = nullptr
std::string m_evalname = "ActsEvaluator.root"
std::map< const unsigned int,
Trajectory > * m_trajectories = nullptr
SvtxTrackMap * m_seedTracks = nullptr
TpcClusterZCrossingCorrection m_clusterCrossingCorrection
TpcDistortionCorrectionContainer * _dcc_static {nullptr}
TpcDistortionCorrectionContainer * _dcc_average {nullptr}
TpcDistortionCorrectionContainer * _dcc_fluctuation {nullptr}
TpcDistortionCorrection _distortionCorrection
tpc distortion correction utility class
ClusterErrorPara _ClusErrPara
std::set< int > m_ignoreLayer
std::string m_fieldMap = ""
int _n_iteration = 0
std::string _track_map_name = "SvtxTrackMap"
std::string _seed_track_map_name = "SeedTrackMap"
unsigned int m_pHypothesis = 211
Default particle assumption to pion.
SvtxAlignmentStateMap * m_alignmentStateMap = nullptr
ActsAlignmentStates m_alignStates
bool m_commissioning = false
bool m_timeAnalysis = false
Variables for doing event time execution analysis.
TFile * m_timeFile = nullptr
TH1 * h_eventTime = nullptr
TH2 * h_fitTime = nullptr
TH1 * h_updateTime = nullptr
TH1 * h_stateTime = nullptr
TH1 * h_rotTime = nullptr
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = std::numeric_limits<int>::max() - 10
}
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Detailed Description
Definition at line 56 of file PHActsTrkFitter.h.
View newest version in sPHENIX GitHub at line 56 of file PHActsTrkFitter.h
Constructor & Destructor Documentation
PHActsTrkFitter::PHActsTrkFitter (const std::string & name = "PHActsTrkFitter")
Default constructor.
Definition at line 77 of file PHActsTrkFitter.cc.
View newest version in sPHENIX GitHub at line 77 of file PHActsTrkFitter.cc
PHActsTrkFitter::~PHActsTrkFitter () override default
Destructor.
Member Function Documentation
void PHActsTrkFitter::checkSurfaceVec (SurfacePtrVec & surfaces) const private
Implement a check to ensure surfaces are sorted
Subtract one so we don't skip a surface
Subtract one so we don't skip a surface
Definition at line 771 of file PHActsTrkFitter.cc.
View newest version in sPHENIX GitHub at line 771 of file PHActsTrkFitter.cc
References i, and writeMapConfig::surface.
Referenced by getSurfaceVector().
void PHActsTrkFitter::commissioning (bool com) inline
Definition at line 112 of file PHActsTrkFitter.h.
View newest version in sPHENIX GitHub at line 112 of file PHActsTrkFitter.h
References com, and m_commissioning.
int PHActsTrkFitter::createNodes (PHCompositeNode * topNode) private
Create new nodes.
Copy this trackmap, then use it for the rest of processing
Definition at line 979 of file PHActsTrkFitter.cc.
View newest version in sPHENIX GitHub at line 979 of file PHActsTrkFitter.cc
References _seed_track_map_name, _track_map_name, PHCompositeNode::addNode(), Fun4AllReturnCodes::EVENT_OK, PHNodeIterator::findFirst(), m_actsEvaluator, m_alignmentStateMap, m_directedTrackMap, m_fitSiliconMMs, m_seedTracks, m_trackMap, and m_trajectories.
Referenced by InitRun().
void PHActsTrkFitter::doTimeAnalysis (bool timeAnalysis) inline
Do some internal time benchmarking analysis.
Definition at line 77 of file PHActsTrkFitter.h.
View newest version in sPHENIX GitHub at line 77 of file PHActsTrkFitter.h
References m_timeAnalysis.
int PHActsTrkFitter::End (PHCompositeNode * topNode) override virtual
End, write and close files.
Reimplemented from SubsysReco.
Definition at line 236 of file PHActsTrkFitter.cc.
View newest version in sPHENIX GitHub at line 236 of file PHActsTrkFitter.cc
References Fun4AllReturnCodes::EVENT_OK, h_eventTime, h_fitTime, h_rotTime, h_stateTime, h_updateTime, m_actsEvaluator, m_evaluator, m_nBadFits, m_timeAnalysis, m_timeFile, and Fun4AllBase::Verbosity().
void PHActsTrkFitter::fitSiliconMMs (bool fitSiliconMMs) inline
Run the direct navigator to fit only tracks with silicon+MM hits.
Definition at line 80 of file PHActsTrkFitter.h.
View newest version in sPHENIX GitHub at line 80 of file PHActsTrkFitter.h
References m_fitSiliconMMs.
ActsTrackFittingAlgorithm::TrackFitterResult PHActsTrkFitter::fitTrack (const std::vector< Acts::SourceLink > & sourceLinks, const ActsTrackFittingAlgorithm::TrackParameters & seed, const ActsTrackFittingAlgorithm::GeneralFitterOptions & kfOptions, const SurfacePtrVec & surfSequence, const CalibratorAdapter & calibrator, ActsTrackFittingAlgorithm::TrackContainer & tracks) private
Helper function to call either the regular navigation or direct navigation, depending on m_fitSiliconMMs
Definition at line 704 of file PHActsTrkFitter.cc.
View newest version in sPHENIX GitHub at line 704 of file PHActsTrkFitter.cc
References ActsTrackFittingAlgorithm::Config::dFit, ActsTrackFittingAlgorithm::Config::fit, m_fitCfg, m_fitSiliconMMs, seed, and tracks().
Referenced by loopTracks().
int PHActsTrkFitter::getNodes (PHCompositeNode * topNode) private
Get all the nodes.
Definition at line 1058 of file PHActsTrkFitter.cc.
View newest version in sPHENIX GitHub at line 1058 of file PHActsTrkFitter.cc
References _dcc_average, _dcc_fluctuation, _dcc_static, Fun4AllReturnCodes::ABORTEVENT, Fun4AllReturnCodes::EVENT_OK, m_alignmentTransformationMap, m_alignmentTransformationMapTransient, m_clusterContainer, m_seedMap, m_siliconSeeds, m_tGeometry, m_tpcSeeds, and PHWHERE.
Referenced by InitRun().
SourceLinkVec PHActsTrkFitter::getSurfaceVector (const SourceLinkVec & sourceLinks, SurfacePtrVec & surfaces) const private
Functions to get list of sorted surfaces for direct navigation, if applicable
Surfaces need to be sorted in order, i.e. from smallest to largest radius extending from target surface Add a check to ensure this
Definition at line 724 of file PHActsTrkFitter.cc.
View newest version in sPHENIX GitHub at line 724 of file PHActsTrkFitter.cc
References checkSurfaceVec(), ActsGeometry::geometry(), ActsSourceLink::geometryId(), ActsSurfaceMaps::isMicromegasSurface(), ActsSurfaceMaps::isTpcSurface(), m_tGeometry, m_useMicromegas, ActsGeometry::maps(), surf(), ActsTrackingGeometry::tGeometry, and Fun4AllBase::Verbosity().
Referenced by loopTracks().
bool PHActsTrkFitter::getTrackFitResult (FitResult & fitOutput, TrackSeed * seed, SvtxTrack * track, ActsTrackFittingAlgorithm::TrackContainer & tracks, const ActsTrackFittingAlgorithm::MeasurementContainer & measurements) private
Make a trajectory state for storage, which conforms to Acts track fit analysis tool
Get position, momentum from the Acts output. Update the values of the proto track
Definition at line 628 of file PHActsTrkFitter.cc.
View newest version in sPHENIX GitHub at line 628 of file PHActsTrkFitter.cc
References ActsAlignmentStates::fillAlignmentStateMap(), PHTimer::get_accumulated_time(), SvtxTrack::get_id(), SvtxTrack::get_silicon_seed(), SvtxTrack::get_tpc_seed(), Acts::Surface::getSharedPtr(), h_updateTime, m_actsEvaluator, m_alignStates, m_commissioning, m_evaluator, m_timeAnalysis, m_trajectories, m_transient_geocontext, Acts::GenericBoundTrackParameters< particle_hypothesis_t >::referenceSurface(), PHTimer::restart(), PHTimer::stop(), trajectory, updateSvtxTrack(), and Fun4AllBase::Verbosity().
Referenced by loopTracks().
void PHActsTrkFitter::ignoreLayer (int layer) inline
Definition at line 123 of file PHActsTrkFitter.h.
View newest version in sPHENIX GitHub at line 123 of file PHActsTrkFitter.h
References m_ignoreLayer.
int PHActsTrkFitter::InitRun (PHCompositeNode * topNode) override virtual
Get and create nodes.
Reimplemented from SubsysReco.
Definition at line 83 of file PHActsTrkFitter.cc.
View newest version in sPHENIX GitHub at line 83 of file PHActsTrkFitter.cc
References _dcc_average, _dcc_fluctuation, _dcc_static, Fun4AllReturnCodes::ABORTEVENT, ActsAlignmentStates::actsGeometry(), ResidualOutlierFinder::chi2Cuts, ActsAlignmentStates::clusters(), createNodes(), ActsTrackFittingAlgorithm::Config::dFit, ActsAlignmentStates::distortionContainers(), Fun4AllReturnCodes::EVENT_OK, Acts::Logging::FATAL, ActsAlignmentStates::fieldMap(), ActsTrackFittingAlgorithm::Config::fit, ActsGeometry::geometry(), Acts::getDefaultLogger(), getNodes(), h_eventTime, h_fitTime, h_rotTime, h_stateTime, h_updateTime, physmon_simulation::level, m_actsEvaluator, m_alignmentStateMap, m_alignStates, m_clusterContainer, m_evalname, m_evaluator, m_fieldMap, m_fitCfg, m_outlierFinder, m_tGeometry, m_timeAnalysis, m_timeFile, m_useOutlierFinder, ActsTrackingGeometry::magField, ActsTrackFittingAlgorithm::makeDirectedKalmanFitterFunction(), ActsTrackFittingAlgorithm::makeKalmanFitterFunction(), Fun4AllBase::Name(), ActsAlignmentStates::stateMap(), ActsTrackingGeometry::tGeometry, Acts::Logging::VERBOSE, ResidualOutlierFinder::verbosity, ActsAlignmentStates::verbosity(), and Fun4AllBase::Verbosity().
void PHActsTrkFitter::loopTracks (Acts::Logging::Level logLevel) private
A track seed is made for every tpc seed. Not every tpc seed has a silicon match, we skip those cases completely in pp running
Need to also check that the tpc seed wasn't removed by the ghost finder
If using directed navigation, collect surface list to navigate
Reset the track seed with the dummy covariance
Set host of propagator options for Acts to do e.g. material integration
Check that the track fit result did not return an error
Track fit failed, get rid of the track from the map
Definition at line 265 of file PHActsTrkFitter.cc.
View newest version in sPHENIX GitHub at line 265 of file PHActsTrkFitter.cc
References TrackSeedContainer::begin(), ActsTrackingGeometry::calibContext, charge(), Acts::UnitConstants::cm, Acts::Test::cov, Acts::GenericBoundTrackParameters< particle_hypothesis_t >::create(), TrackSeedContainer::end(), TrackSeedContainer::find(), fitTrack(), ActsGeometry::geometry(), TrackSeedContainer::get(), PHTimer::get_accumulated_time(), TrackSeed::get_crossing(), TrackSeed::get_crossing_estimate(), SvtxTrack_v4::get_quality(), TrackSeed::get_silicon_seed_index(), TrackSeed::get_tpc_seed_index(), TrackSeed::get_x(), Acts::getDefaultLogger(), MakeSourceLinks::getSourceLinks(), getSurfaceVector(), getTrackFitResult(), i, SvtxTrackMap::insertWithKey(), is_valid(), ActsSurfaceMaps::isMicromegasSurface(), logger(), m_alignmentTransformationMapTransient, m_clusterContainer, m_directedTrackMap, m_fieldMap, m_fitSiliconMMs, m_nBadFits, m_pp_mode, m_seedMap, m_siliconSeeds, m_tGeometry, m_tpcSeeds, m_trackMap, m_transient_geocontext, m_transient_id_set, m_useMicromegas, ActsTrackingGeometry::magFieldContext, ActsGeometry::maps(), max_bunch_search, momentum, Acts::UnitConstants::ns, ActsTests::PropagationDatasets::phi, Acts::ParticleHypothesis::pion(), position, printTrackSeed(), pSurface, physmon_track_finding_ttbar::pt, MakeSourceLinks::resetTransientTransformMap(), PHTimer::restart(), seed, SvtxTrack_v4::set_crossing(), SvtxTrack_v4::set_id(), MakeSourceLinks::set_pp_mode(), SvtxTrack_v4::set_silicon_seed(), SvtxTrack_v4::set_tpc_seed(), setDefaultCovariance(), MakeSourceLinks::setVerbosity(), SvtxTrackMap::size(), TrackSeedContainer::size(), PHTimer::stop(), writeMapConfig::surface, tracks(), value, and Fun4AllBase::Verbosity().
Referenced by process_event().
void PHActsTrkFitter::printTrackSeed (const ActsTrackFittingAlgorithm::TrackParameters & seed) const private
Definition at line 962 of file PHActsTrkFitter.cc.
View newest version in sPHENIX GitHub at line 962 of file PHActsTrkFitter.cc
References Acts::GenericBoundTrackParameters< particle_hypothesis_t >::absoluteMomentum(), Acts::GenericBoundTrackParameters< particle_hypothesis_t >::charge(), m_transient_geocontext, Acts::GenericBoundTrackParameters< particle_hypothesis_t >::momentum(), PHWHERE, and Acts::GenericBoundTrackParameters< particle_hypothesis_t >::position().
Referenced by loopTracks().
int PHActsTrkFitter::process_event (PHCompositeNode * topNode) override virtual
Process each event by calling the fitter.
Fill an additional track map if using the acts evaluator for proto track comparison to fitted track
wipe at the beginning of every new fit pass, so that the seeds are whatever is currently in SvtxTrackMap
Reimplemented from SubsysReco.
Definition at line 162 of file PHActsTrkFitter.cc.
View newest version in sPHENIX GitHub at line 162 of file PHActsTrkFitter.cc
References SvtxTrackMap::clear(), Fun4AllReturnCodes::EVENT_OK, ActsExamples::HepMC3Event::eventTime(), Acts::Logging::FATAL, PHTimer::get_accumulated_time(), h_eventTime, SvtxTrackMap::insert(), telescope_simulation::logLevel, loopTracks(), m_actsEvaluator, m_evaluator, m_event, m_seedTracks, m_timeAnalysis, m_trackMap, PHWHERE, PHTimer::restart(), SvtxTrackMap::size(), PHTimer::stop(), Acts::Logging::VERBOSE, and Fun4AllBase::Verbosity().
int PHActsTrkFitter::ResetEvent (PHCompositeNode *) override virtual
Clean up after each event.
Reimplemented from SubsysReco.
Definition at line 224 of file PHActsTrkFitter.cc.
View newest version in sPHENIX GitHub at line 224 of file PHActsTrkFitter.cc
References Fun4AllReturnCodes::EVENT_OK, m_trajectories, and Fun4AllBase::Verbosity().
void PHActsTrkFitter::set_pp_mode (bool ispp) inline
Set flag for pp running.
Definition at line 121 of file PHActsTrkFitter.h.
View newest version in sPHENIX GitHub at line 121 of file PHActsTrkFitter.h
References m_pp_mode.
void PHActsTrkFitter::set_seed_track_map_name (const std::string & map_name) inline
Definition at line 118 of file PHActsTrkFitter.h.
View newest version in sPHENIX GitHub at line 118 of file PHActsTrkFitter.h
References _seed_track_map_name.
void PHActsTrkFitter::set_track_map_name (const std::string & map_name) inline
Definition at line 117 of file PHActsTrkFitter.h.
View newest version in sPHENIX GitHub at line 117 of file PHActsTrkFitter.h
References _track_map_name.
void PHActsTrkFitter::setAbsPdgHypothesis (unsigned int pHypothesis) inline
Definition at line 107 of file PHActsTrkFitter.h.
View newest version in sPHENIX GitHub at line 107 of file PHActsTrkFitter.h
References m_pHypothesis.
Acts::BoundSquareMatrix PHActsTrkFitter::setDefaultCovariance () const private
Acts cares about the track covariance as it helps the KF know whether or not to trust the initial track seed or not. We reset it here to some loose values as it helps Acts improve the fitting. If the covariance is too loose, it won't be able to propagate, but if it is too tight, it will just "believe" the track seed over the hit data
If we are using distortions, then we need to blow up the covariance a bit since the seed was created with distorted TPC clusters
Acts takes this value very seriously - tuned to be in a "sweet spot"
Definition at line 917 of file PHActsTrkFitter.cc.
View newest version in sPHENIX GitHub at line 917 of file PHActsTrkFitter.cc
References Acts::Test::cov, Acts::UnitConstants::degree, Acts::eBoundLoc0, Acts::eBoundLoc1, Acts::eBoundPhi, Acts::eBoundQOverP, Acts::eBoundTheta, Acts::eBoundTime, m_fitSiliconMMs, Acts::UnitConstants::ns, and Acts::UnitConstants::um.
Referenced by loopTracks().
void PHActsTrkFitter::setEvaluatorName (const std::string & name) inline
Definition at line 101 of file PHActsTrkFitter.h.
View newest version in sPHENIX GitHub at line 101 of file PHActsTrkFitter.h
References m_evalname, and perf_headwind::name.
void PHActsTrkFitter::setFieldMap (const std::string & fieldMap) inline
Definition at line 102 of file PHActsTrkFitter.h.
View newest version in sPHENIX GitHub at line 102 of file PHActsTrkFitter.h
References m_fieldMap.
void PHActsTrkFitter::SetIteration (int iter) inline
Definition at line 116 of file PHActsTrkFitter.h.
View newest version in sPHENIX GitHub at line 116 of file PHActsTrkFitter.h
References _n_iteration.
void PHActsTrkFitter::setUpdateSvtxTrackStates (bool fillSvtxTrackStates) inline
Definition at line 91 of file PHActsTrkFitter.h.
View newest version in sPHENIX GitHub at line 91 of file PHActsTrkFitter.h
References m_fillSvtxTrackStates.
void PHActsTrkFitter::setUseMicromegas (bool value) inline
require micromegas in SiliconMM fits
Definition at line 86 of file PHActsTrkFitter.h.
View newest version in sPHENIX GitHub at line 86 of file PHActsTrkFitter.h
References m_useMicromegas, and value.
void PHActsTrkFitter::updateSvtxTrack (std::vector< Acts::MultiTrajectoryTraits::IndexType > & tips, Trajectory::IndexedParameters & paramsMap, ActsTrackFittingAlgorithm::TrackContainer & tracks, SvtxTrack * track) private
Convert the acts track fit result to an svtx track.
only one track tip in the track fit Trajectory
Acts default unit is mm. So convert to cm
Definition at line 819 of file PHActsTrkFitter.cc.
View newest version in sPHENIX GitHub at line 819 of file PHActsTrkFitter.cc
References SvtxTrack::clear_states(), Acts::UnitConstants::cm, ActsTransformations::fillSvtxTrackStates(), PHTimer::get_accumulated_time(), h_stateTime, i, SvtxTrack::identify(), SvtxTrack::insert_state(), j, m_fillSvtxTrackStates, m_fitSiliconMMs, m_timeAnalysis, m_transient_geocontext, out, PHTimer::restart(), ActsTransformations::rotateActsCovToSvtxTrack(), SvtxTrack::set_charge(), SvtxTrack::set_chisq(), SvtxTrack::set_error(), SvtxTrack::set_ndf(), SvtxTrack::set_px(), SvtxTrack::set_py(), SvtxTrack::set_pz(), SvtxTrackState_v1::set_x(), SvtxTrack::set_x(), SvtxTrackState_v1::set_y(), SvtxTrack::set_y(), SvtxTrackState_v1::set_z(), SvtxTrack::set_z(), ActsTransformations::setVerbosity(), PHTimer::stop(), Acts::MultiTrajectoryHelpers::trajectoryState(), and Fun4AllBase::Verbosity().
Referenced by getTrackFitResult().
void PHActsTrkFitter::useActsEvaluator (bool actsEvaluator) inline
Definition at line 96 of file PHActsTrkFitter.h.
View newest version in sPHENIX GitHub at line 96 of file PHActsTrkFitter.h
References m_actsEvaluator.
void PHActsTrkFitter::useOutlierFinder (bool outlier) inline
Definition at line 114 of file PHActsTrkFitter.h.
View newest version in sPHENIX GitHub at line 114 of file PHActsTrkFitter.h
References m_useOutlierFinder.
Member Data Documentation
ClusterErrorPara PHActsTrkFitter::_ClusErrPara private
Definition at line 224 of file PHActsTrkFitter.h.
View newest version in sPHENIX GitHub at line 224 of file PHActsTrkFitter.h
TpcDistortionCorrectionContainer* PHActsTrkFitter::_dcc_average {nullptr} private
Definition at line 218 of file PHActsTrkFitter.h.
View newest version in sPHENIX GitHub at line 218 of file PHActsTrkFitter.h
Referenced by getNodes(), and InitRun().
TpcDistortionCorrectionContainer* PHActsTrkFitter::_dcc_fluctuation {nullptr} private
Definition at line 219 of file PHActsTrkFitter.h.
View newest version in sPHENIX GitHub at line 219 of file PHActsTrkFitter.h
Referenced by getNodes(), and InitRun().
TpcDistortionCorrectionContainer* PHActsTrkFitter::_dcc_static {nullptr} private
Definition at line 217 of file PHActsTrkFitter.h.
View newest version in sPHENIX GitHub at line 217 of file PHActsTrkFitter.h
Referenced by getNodes(), and InitRun().
TpcDistortionCorrection PHActsTrkFitter::_distortionCorrection private
tpc distortion correction utility class
Definition at line 222 of file PHActsTrkFitter.h.
View newest version in sPHENIX GitHub at line 222 of file PHActsTrkFitter.h
int PHActsTrkFitter::_n_iteration = 0 private
Definition at line 230 of file PHActsTrkFitter.h.
View newest version in sPHENIX GitHub at line 230 of file PHActsTrkFitter.h
Referenced by SetIteration().
std::string PHActsTrkFitter::_seed_track_map_name = "SeedTrackMap" private
Definition at line 232 of file PHActsTrkFitter.h.
View newest version in sPHENIX GitHub at line 232 of file PHActsTrkFitter.h
Referenced by createNodes(), and set_seed_track_map_name().
std::string PHActsTrkFitter::_track_map_name = "SvtxTrackMap" private
Definition at line 231 of file PHActsTrkFitter.h.
View newest version in sPHENIX GitHub at line 231 of file PHActsTrkFitter.h
Referenced by createNodes(), and set_track_map_name().
TH1* PHActsTrkFitter::h_eventTime = nullptr private
Definition at line 244 of file PHActsTrkFitter.h.
View newest version in sPHENIX GitHub at line 244 of file PHActsTrkFitter.h
Referenced by End(), InitRun(), and process_event().
TH2* PHActsTrkFitter::h_fitTime = nullptr private
Definition at line 245 of file PHActsTrkFitter.h.
View newest version in sPHENIX GitHub at line 245 of file PHActsTrkFitter.h
Referenced by End(), and InitRun().
TH1* PHActsTrkFitter::h_rotTime = nullptr private
Definition at line 248 of file PHActsTrkFitter.h.
View newest version in sPHENIX GitHub at line 248 of file PHActsTrkFitter.h
Referenced by End(), and InitRun().
TH1* PHActsTrkFitter::h_stateTime = nullptr private
Definition at line 247 of file PHActsTrkFitter.h.
View newest version in sPHENIX GitHub at line 247 of file PHActsTrkFitter.h
Referenced by End(), InitRun(), and updateSvtxTrack().
TH1* PHActsTrkFitter::h_updateTime = nullptr private
Definition at line 246 of file PHActsTrkFitter.h.
View newest version in sPHENIX GitHub at line 246 of file PHActsTrkFitter.h
Referenced by End(), getTrackFitResult(), and InitRun().
bool PHActsTrkFitter::m_actsEvaluator = false private
Definition at line 209 of file PHActsTrkFitter.h.
View newest version in sPHENIX GitHub at line 209 of file PHActsTrkFitter.h
Referenced by createNodes(), End(), getTrackFitResult(), InitRun(), process_event(), and useActsEvaluator().
SvtxAlignmentStateMap* PHActsTrkFitter::m_alignmentStateMap = nullptr private
Definition at line 237 of file PHActsTrkFitter.h.
View newest version in sPHENIX GitHub at line 237 of file PHActsTrkFitter.h
Referenced by createNodes(), and InitRun().
alignmentTransformationContainer* PHActsTrkFitter::m_alignmentTransformationMap = nullptr private
TrackMap containing SvtxTracks.
Definition at line 175 of file PHActsTrkFitter.h.
View newest version in sPHENIX GitHub at line 175 of file PHActsTrkFitter.h
Referenced by getNodes().
alignmentTransformationContainer* PHActsTrkFitter::m_alignmentTransformationMapTransient = nullptr private
Definition at line 176 of file PHActsTrkFitter.h.
View newest version in sPHENIX GitHub at line 176 of file PHActsTrkFitter.h
Referenced by getNodes(), and loopTracks().
ActsAlignmentStates PHActsTrkFitter::m_alignStates private
Definition at line 238 of file PHActsTrkFitter.h.
View newest version in sPHENIX GitHub at line 238 of file PHActsTrkFitter.h
Referenced by getTrackFitResult(), and InitRun().
TrkrClusterContainer* PHActsTrkFitter::m_clusterContainer = nullptr private
Definition at line 181 of file PHActsTrkFitter.h.
View newest version in sPHENIX GitHub at line 181 of file PHActsTrkFitter.h
Referenced by getNodes(), InitRun(), and loopTracks().
TpcClusterZCrossingCorrection PHActsTrkFitter::m_clusterCrossingCorrection private
Definition at line 216 of file PHActsTrkFitter.h.
View newest version in sPHENIX GitHub at line 216 of file PHActsTrkFitter.h
bool PHActsTrkFitter::m_commissioning = false private
Definition at line 239 of file PHActsTrkFitter.h.
View newest version in sPHENIX GitHub at line 239 of file PHActsTrkFitter.h
Referenced by commissioning(), and getTrackFitResult().
SvtxTrackMap* PHActsTrkFitter::m_directedTrackMap = nullptr private
Definition at line 180 of file PHActsTrkFitter.h.
View newest version in sPHENIX GitHub at line 180 of file PHActsTrkFitter.h
Referenced by createNodes(), and loopTracks().
std::string PHActsTrkFitter::m_evalname = "ActsEvaluator.root" private
Definition at line 211 of file PHActsTrkFitter.h.
View newest version in sPHENIX GitHub at line 211 of file PHActsTrkFitter.h
Referenced by InitRun(), and setEvaluatorName().
std::unique_ptr<ActsEvaluator> PHActsTrkFitter::m_evaluator = nullptr private
Definition at line 210 of file PHActsTrkFitter.h.
View newest version in sPHENIX GitHub at line 210 of file PHActsTrkFitter.h
Referenced by End(), getTrackFitResult(), InitRun(), and process_event().
int PHActsTrkFitter::m_event = 0 private
Event counter.
Definition at line 166 of file PHActsTrkFitter.h.
View newest version in sPHENIX GitHub at line 166 of file PHActsTrkFitter.h
Referenced by process_event().
std::string PHActsTrkFitter::m_fieldMap = "" private
Definition at line 228 of file PHActsTrkFitter.h.
View newest version in sPHENIX GitHub at line 228 of file PHActsTrkFitter.h
Referenced by InitRun(), loopTracks(), and setFieldMap().
bool PHActsTrkFitter::m_fillSvtxTrackStates = true private
A bool to update the SvtxTrackState information (or not)
Definition at line 197 of file PHActsTrkFitter.h.
View newest version in sPHENIX GitHub at line 197 of file PHActsTrkFitter.h
Referenced by setUpdateSvtxTrackStates(), and updateSvtxTrack().
ActsTrackFittingAlgorithm::Config PHActsTrkFitter::m_fitCfg private
Configuration containing the fitting function instance.
Definition at line 172 of file PHActsTrkFitter.h.
View newest version in sPHENIX GitHub at line 172 of file PHActsTrkFitter.h
Referenced by fitTrack(), and InitRun().
bool PHActsTrkFitter::m_fitSiliconMMs = false private
Boolean to use normal tracking geometry navigator or the Acts::DirectedNavigator with a list of sorted silicon+MM surfaces
Definition at line 191 of file PHActsTrkFitter.h.
View newest version in sPHENIX GitHub at line 191 of file PHActsTrkFitter.h
Referenced by createNodes(), fitSiliconMMs(), fitTrack(), loopTracks(), setDefaultCovariance(), and updateSvtxTrack().
std::set<int> PHActsTrkFitter::m_ignoreLayer private
Definition at line 226 of file PHActsTrkFitter.h.
View newest version in sPHENIX GitHub at line 226 of file PHActsTrkFitter.h
Referenced by ignoreLayer().
int PHActsTrkFitter::m_nBadFits = 0 private
Number of acts fits that returned an error.
Definition at line 187 of file PHActsTrkFitter.h.
View newest version in sPHENIX GitHub at line 187 of file PHActsTrkFitter.h
Referenced by End(), and loopTracks().
ResidualOutlierFinder PHActsTrkFitter::m_outlierFinder private
Definition at line 201 of file PHActsTrkFitter.h.
View newest version in sPHENIX GitHub at line 201 of file PHActsTrkFitter.h
Referenced by InitRun().
unsigned int PHActsTrkFitter::m_pHypothesis = 211 private
Default particle assumption to pion.
Definition at line 235 of file PHActsTrkFitter.h.
View newest version in sPHENIX GitHub at line 235 of file PHActsTrkFitter.h
Referenced by setAbsPdgHypothesis().
bool PHActsTrkFitter::m_pp_mode = false private
Flag for pp running.
Definition at line 204 of file PHActsTrkFitter.h.
View newest version in sPHENIX GitHub at line 204 of file PHActsTrkFitter.h
Referenced by loopTracks(), and set_pp_mode().
TrackSeedContainer* PHActsTrkFitter::m_seedMap = nullptr private
Definition at line 182 of file PHActsTrkFitter.h.
View newest version in sPHENIX GitHub at line 182 of file PHActsTrkFitter.h
Referenced by getNodes(), and loopTracks().
SvtxTrackMap* PHActsTrkFitter::m_seedTracks = nullptr private
Definition at line 214 of file PHActsTrkFitter.h.
View newest version in sPHENIX GitHub at line 214 of file PHActsTrkFitter.h
Referenced by createNodes(), and process_event().
TrackSeedContainer* PHActsTrkFitter::m_siliconSeeds = nullptr private
Definition at line 184 of file PHActsTrkFitter.h.
View newest version in sPHENIX GitHub at line 184 of file PHActsTrkFitter.h
Referenced by getNodes(), and loopTracks().
ActsGeometry* PHActsTrkFitter::m_tGeometry = nullptr private
Options that Acts::Fitter needs to run from MakeActsGeometry.
Definition at line 169 of file PHActsTrkFitter.h.
View newest version in sPHENIX GitHub at line 169 of file PHActsTrkFitter.h
Referenced by getNodes(), getSurfaceVector(), InitRun(), and loopTracks().
bool PHActsTrkFitter::m_timeAnalysis = false private
Variables for doing event time execution analysis.
Definition at line 242 of file PHActsTrkFitter.h.
View newest version in sPHENIX GitHub at line 242 of file PHActsTrkFitter.h
Referenced by doTimeAnalysis(), End(), getTrackFitResult(), InitRun(), process_event(), and updateSvtxTrack().
TFile* PHActsTrkFitter::m_timeFile = nullptr private
Definition at line 243 of file PHActsTrkFitter.h.
View newest version in sPHENIX GitHub at line 243 of file PHActsTrkFitter.h
Referenced by End(), and InitRun().
TrackSeedContainer* PHActsTrkFitter::m_tpcSeeds = nullptr private
Definition at line 183 of file PHActsTrkFitter.h.
View newest version in sPHENIX GitHub at line 183 of file PHActsTrkFitter.h
Referenced by getNodes(), and loopTracks().
SvtxTrackMap* PHActsTrkFitter::m_trackMap = nullptr private
Definition at line 179 of file PHActsTrkFitter.h.
View newest version in sPHENIX GitHub at line 179 of file PHActsTrkFitter.h
Referenced by createNodes(), loopTracks(), and process_event().
std::map<const unsigned int, Trajectory>* PHActsTrkFitter::m_trajectories = nullptr private
Definition at line 213 of file PHActsTrkFitter.h.
View newest version in sPHENIX GitHub at line 213 of file PHActsTrkFitter.h
Referenced by createNodes(), getTrackFitResult(), and ResetEvent().
Acts::GeometryContext PHActsTrkFitter::m_transient_geocontext private
Definition at line 178 of file PHActsTrkFitter.h.
View newest version in sPHENIX GitHub at line 178 of file PHActsTrkFitter.h
Referenced by getTrackFitResult(), loopTracks(), printTrackSeed(), and updateSvtxTrack().
std::set< Acts::GeometryIdentifier> PHActsTrkFitter::m_transient_id_set private
Definition at line 177 of file PHActsTrkFitter.h.
View newest version in sPHENIX GitHub at line 177 of file PHActsTrkFitter.h
Referenced by loopTracks().
bool PHActsTrkFitter::m_useMicromegas = true private
requires micromegas present when fitting silicon-MM surfaces
Definition at line 194 of file PHActsTrkFitter.h.
View newest version in sPHENIX GitHub at line 194 of file PHActsTrkFitter.h
Referenced by getSurfaceVector(), loopTracks(), and setUseMicromegas().
bool PHActsTrkFitter::m_useOutlierFinder = false private
A bool to use the chi2 outlier finder in the track fitting.
Definition at line 200 of file PHActsTrkFitter.h.
View newest version in sPHENIX GitHub at line 200 of file PHActsTrkFitter.h
Referenced by InitRun(), and useOutlierFinder().
short int PHActsTrkFitter::max_bunch_search = 2 private
Definition at line 207 of file PHActsTrkFitter.h.
View newest version in sPHENIX GitHub at line 207 of file PHActsTrkFitter.h
Referenced by loopTracks().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/trackreco/PHActsTrkFitter.h
coresoftware/blob/master/offline/packages/trackreco/PHActsTrkFitter.cc