Analysis Software: PHG4CylinderGeomv4 Class Reference
PHG4CylinderGeomv4 Class Reference
#include <coresoftware/blob/master/simulation/g4simulation/g4detectors/PHG4CylinderGeomv4.h>
Public Member Functions
PHG4CylinderGeomv4 ()=default
PHG4CylinderGeomv4 (const int lnsensors, const int lnz, const int nspc, int nsc, const int nstag, const double lr, const double rs, const double szs, const double sps, const double sxo, double syo, const double szsp, const double sys, const double tck, const double st)
~PHG4CylinderGeomv4 () override
void identify (std::ostream &os=std::cout) const override
void set_layer (const int i) override
int get_layer () const override
double get_radius () const override
void find_segment_center (const int segment_z_bin, const int segment_phi_bin, double location[]) override
void find_strip_center (const int segment_z_bin, const int segment_phi_bin, const int strip_column, const int strip_index, double location[]) override
double get_thickness () const override
double get_strip_y_spacing () const override
double get_strip_z_spacing () const override
double get_strip_tilt () const override
int get_N_strip_columns () const override
int get_N_strips_per_column () const override
int get_N_sensors_in_layer () const override
double get_sensor_x_offset () const
double get_sensor_y_offset () const
Public Member Functions inherited from PHG4CylinderGeom
~PHG4CylinderGeom () override
virtual double get_zmin () const
virtual double get_zmax () const
virtual int get_nscint () const
virtual double get_tiltangle () const
virtual double get_phi_slat_zero () const
virtual void set_radius (const double)
virtual void set_thickness (const double)
virtual void set_zmin (const double)
virtual void set_zmax (const double)
virtual void set_nscint (const int)
virtual void set_tiltangle (const double)
virtual void set_phi_slat_zero (const double)
virtual void find_strip_index_values (const int, const double, const double, int &, int &)
virtual void find_strip_center_local_coords (const int, const int, const int, double[])
virtual double get_pixel_z () const
virtual double get_pixel_x () const
virtual double get_pixel_thickness () const
virtual void ImportParameters (const PHParameters &)
load parameters from PHParameters, which interface to Database/XML/ROOT files
Public Member Functions inherited from PHObject
PHObject ()
ctor
~PHObject () override
dtor
virtual PHObject * CloneMe () const
Virtual copy constructor.
virtual PHObject * clone () const final
PHObject * Clone (const char *newname="") const final
void Copy (TObject &object) const final
virtual void Reset ()
Clear Event.
virtual int isValid () const
isValid returns non zero if object contains vailid data
virtual int Integrate () const
virtual int Integrate (PHObject *)
virtual void CopyFrom (const PHObject *obj)
Protected Attributes
int N_sensors_in_layer {-1}
int layer {-1}
double layer_radius {std::numeric_limits<double>::quiet_NaN()}
double radius_stagger {std::numeric_limits<double>::quiet_NaN()}
int layer_NZ {-1}
double segment_z_step {std::numeric_limits<double>::quiet_NaN()}
double segment_phi_step {std::numeric_limits<double>::quiet_NaN()}
double sensor_x_offset {std::numeric_limits<double>::quiet_NaN()}
double sensor_y_offset {std::numeric_limits<double>::quiet_NaN()}
int N_strip_columns {-1}
int N_strips_per_column {-1}
int N_staggers {-1}
double strip_z_spacing {std::numeric_limits<double>::quiet_NaN()}
double strip_y_spacing {std::numeric_limits<double>::quiet_NaN()}
double thickness {std::numeric_limits<double>::quiet_NaN()}
double strip_tilt {std::numeric_limits<double>::quiet_NaN()}
Additional Inherited Members
Protected Member Functions inherited from PHG4CylinderGeom
PHG4CylinderGeom ()
Detailed Description
Definition at line 10 of file PHG4CylinderGeomv4.h.
View newest version in sPHENIX GitHub at line 10 of file PHG4CylinderGeomv4.h
Constructor & Destructor Documentation
PHG4CylinderGeomv4::PHG4CylinderGeomv4 () default
PHG4CylinderGeomv4::PHG4CylinderGeomv4 (const int lnsensors, const int lnz, const int nspc, int nsc, const int nstag, const double lr, const double rs, const double szs, const double sps, const double sxo, double syo, const double szsp, const double sys, const double tck, const double st) inline
Definition at line 14 of file PHG4CylinderGeomv4.h.
View newest version in sPHENIX GitHub at line 14 of file PHG4CylinderGeomv4.h
PHG4CylinderGeomv4::~PHG4CylinderGeomv4 () inline override
Definition at line 48 of file PHG4CylinderGeomv4.h.
View newest version in sPHENIX GitHub at line 48 of file PHG4CylinderGeomv4.h
Member Function Documentation
void PHG4CylinderGeomv4::find_segment_center (const int segment_z_bin, const int segment_phi_bin, double location[]) override virtual
Reimplemented from PHG4CylinderGeom.
Definition at line 26 of file PHG4CylinderGeomv4.cc.
View newest version in sPHENIX GitHub at line 26 of file PHG4CylinderGeomv4.cc
References double(), layer_NZ, layer_radius, N_staggers, ActsTests::PropagationDatasets::phi, radius_stagger, segment_phi_step, and segment_z_step.
Referenced by find_strip_center().
void PHG4CylinderGeomv4::find_strip_center (const int segment_z_bin, const int segment_phi_bin, const int strip_column, const int strip_index, double location[]) override virtual
Reimplemented from PHG4CylinderGeom.
Definition at line 48 of file PHG4CylinderGeomv4.cc.
View newest version in sPHENIX GitHub at line 48 of file PHG4CylinderGeomv4.cc
References double(), find_segment_center(), N_strip_columns, N_strips_per_column, ActsTests::PropagationDatasets::phi, segment_phi_step, sensor_x_offset, sensor_y_offset, strip_y_spacing, strip_z_spacing, ambiguity_solver_full_chain::x, and y.
int PHG4CylinderGeomv4::get_layer () const inline override virtual
Reimplemented from PHG4CylinderGeom.
Definition at line 54 of file PHG4CylinderGeomv4.h.
View newest version in sPHENIX GitHub at line 54 of file PHG4CylinderGeomv4.h
References layer.
int PHG4CylinderGeomv4::get_N_sensors_in_layer () const inline override virtual
Reimplemented from PHG4CylinderGeom.
Definition at line 66 of file PHG4CylinderGeomv4.h.
View newest version in sPHENIX GitHub at line 66 of file PHG4CylinderGeomv4.h
References N_sensors_in_layer.
int PHG4CylinderGeomv4::get_N_strip_columns () const inline override virtual
Reimplemented from PHG4CylinderGeom.
Definition at line 64 of file PHG4CylinderGeomv4.h.
View newest version in sPHENIX GitHub at line 64 of file PHG4CylinderGeomv4.h
References N_strip_columns.
int PHG4CylinderGeomv4::get_N_strips_per_column () const inline override virtual
Reimplemented from PHG4CylinderGeom.
Definition at line 65 of file PHG4CylinderGeomv4.h.
View newest version in sPHENIX GitHub at line 65 of file PHG4CylinderGeomv4.h
References N_strips_per_column.
double PHG4CylinderGeomv4::get_radius () const inline override virtual
Reimplemented from PHG4CylinderGeom.
Definition at line 55 of file PHG4CylinderGeomv4.h.
View newest version in sPHENIX GitHub at line 55 of file PHG4CylinderGeomv4.h
References layer_radius.
double PHG4CylinderGeomv4::get_sensor_x_offset () const inline
Definition at line 69 of file PHG4CylinderGeomv4.h.
View newest version in sPHENIX GitHub at line 69 of file PHG4CylinderGeomv4.h
References sensor_x_offset.
double PHG4CylinderGeomv4::get_sensor_y_offset () const inline
Definition at line 70 of file PHG4CylinderGeomv4.h.
View newest version in sPHENIX GitHub at line 70 of file PHG4CylinderGeomv4.h
References sensor_y_offset.
double PHG4CylinderGeomv4::get_strip_tilt () const inline override virtual
Reimplemented from PHG4CylinderGeom.
Definition at line 63 of file PHG4CylinderGeomv4.h.
View newest version in sPHENIX GitHub at line 63 of file PHG4CylinderGeomv4.h
References strip_tilt.
double PHG4CylinderGeomv4::get_strip_y_spacing () const inline override virtual
Reimplemented from PHG4CylinderGeom.
Definition at line 61 of file PHG4CylinderGeomv4.h.
View newest version in sPHENIX GitHub at line 61 of file PHG4CylinderGeomv4.h
References strip_y_spacing.
double PHG4CylinderGeomv4::get_strip_z_spacing () const inline override virtual
Reimplemented from PHG4CylinderGeom.
Definition at line 62 of file PHG4CylinderGeomv4.h.
View newest version in sPHENIX GitHub at line 62 of file PHG4CylinderGeomv4.h
References strip_z_spacing.
double PHG4CylinderGeomv4::get_thickness () const inline override virtual
Reimplemented from PHG4CylinderGeom.
Definition at line 60 of file PHG4CylinderGeomv4.h.
View newest version in sPHENIX GitHub at line 60 of file PHG4CylinderGeomv4.h
References thickness.
void PHG4CylinderGeomv4::identify (std::ostream & os = std::cout) const override virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from PHG4CylinderGeom.
Definition at line 5 of file PHG4CylinderGeomv4.cc.
View newest version in sPHENIX GitHub at line 5 of file PHG4CylinderGeomv4.cc
References layer, layer_NZ, layer_radius, N_sensors_in_layer, N_staggers, N_strip_columns, N_strips_per_column, radius_stagger, segment_phi_step, segment_z_step, sensor_x_offset, sensor_y_offset, strip_tilt, strip_y_spacing, and strip_z_spacing.
void PHG4CylinderGeomv4::set_layer (const int i) inline override virtual
Reimplemented from PHG4CylinderGeom.
Definition at line 53 of file PHG4CylinderGeomv4.h.
View newest version in sPHENIX GitHub at line 53 of file PHG4CylinderGeomv4.h
References i, and layer.
Member Data Documentation
int PHG4CylinderGeomv4::layer {-1} protected
Definition at line 74 of file PHG4CylinderGeomv4.h.
View newest version in sPHENIX GitHub at line 74 of file PHG4CylinderGeomv4.h
Referenced by get_layer(), identify(), and set_layer().
int PHG4CylinderGeomv4::layer_NZ {-1} protected
Definition at line 79 of file PHG4CylinderGeomv4.h.
View newest version in sPHENIX GitHub at line 79 of file PHG4CylinderGeomv4.h
Referenced by find_segment_center(), and identify().
double PHG4CylinderGeomv4::layer_radius {std::numeric_limits<double>::quiet_NaN()} protected
Definition at line 77 of file PHG4CylinderGeomv4.h.
View newest version in sPHENIX GitHub at line 77 of file PHG4CylinderGeomv4.h
Referenced by find_segment_center(), get_radius(), and identify().
int PHG4CylinderGeomv4::N_sensors_in_layer {-1} protected
Definition at line 73 of file PHG4CylinderGeomv4.h.
View newest version in sPHENIX GitHub at line 73 of file PHG4CylinderGeomv4.h
Referenced by get_N_sensors_in_layer(), and identify().
int PHG4CylinderGeomv4::N_staggers {-1} protected
Definition at line 90 of file PHG4CylinderGeomv4.h.
View newest version in sPHENIX GitHub at line 90 of file PHG4CylinderGeomv4.h
Referenced by find_segment_center(), and identify().
int PHG4CylinderGeomv4::N_strip_columns {-1} protected
Definition at line 88 of file PHG4CylinderGeomv4.h.
View newest version in sPHENIX GitHub at line 88 of file PHG4CylinderGeomv4.h
Referenced by find_strip_center(), get_N_strip_columns(), and identify().
int PHG4CylinderGeomv4::N_strips_per_column {-1} protected
Definition at line 89 of file PHG4CylinderGeomv4.h.
View newest version in sPHENIX GitHub at line 89 of file PHG4CylinderGeomv4.h
Referenced by find_strip_center(), get_N_strips_per_column(), and identify().
double PHG4CylinderGeomv4::radius_stagger {std::numeric_limits<double>::quiet_NaN()} protected
Definition at line 78 of file PHG4CylinderGeomv4.h.
View newest version in sPHENIX GitHub at line 78 of file PHG4CylinderGeomv4.h
Referenced by find_segment_center(), and identify().
double PHG4CylinderGeomv4::segment_phi_step {std::numeric_limits<double>::quiet_NaN()} protected
Definition at line 81 of file PHG4CylinderGeomv4.h.
View newest version in sPHENIX GitHub at line 81 of file PHG4CylinderGeomv4.h
Referenced by find_segment_center(), find_strip_center(), and identify().
double PHG4CylinderGeomv4::segment_z_step {std::numeric_limits<double>::quiet_NaN()} protected
Definition at line 80 of file PHG4CylinderGeomv4.h.
View newest version in sPHENIX GitHub at line 80 of file PHG4CylinderGeomv4.h
Referenced by find_segment_center(), and identify().
double PHG4CylinderGeomv4::sensor_x_offset {std::numeric_limits<double>::quiet_NaN()} protected
Definition at line 82 of file PHG4CylinderGeomv4.h.
View newest version in sPHENIX GitHub at line 82 of file PHG4CylinderGeomv4.h
Referenced by find_strip_center(), get_sensor_x_offset(), and identify().
double PHG4CylinderGeomv4::sensor_y_offset {std::numeric_limits<double>::quiet_NaN()} protected
Definition at line 83 of file PHG4CylinderGeomv4.h.
View newest version in sPHENIX GitHub at line 83 of file PHG4CylinderGeomv4.h
Referenced by find_strip_center(), get_sensor_y_offset(), and identify().
double PHG4CylinderGeomv4::strip_tilt {std::numeric_limits<double>::quiet_NaN()} protected
Definition at line 94 of file PHG4CylinderGeomv4.h.
View newest version in sPHENIX GitHub at line 94 of file PHG4CylinderGeomv4.h
Referenced by get_strip_tilt(), and identify().
double PHG4CylinderGeomv4::strip_y_spacing {std::numeric_limits<double>::quiet_NaN()} protected
Definition at line 92 of file PHG4CylinderGeomv4.h.
View newest version in sPHENIX GitHub at line 92 of file PHG4CylinderGeomv4.h
Referenced by find_strip_center(), get_strip_y_spacing(), and identify().
double PHG4CylinderGeomv4::strip_z_spacing {std::numeric_limits<double>::quiet_NaN()} protected
Definition at line 91 of file PHG4CylinderGeomv4.h.
View newest version in sPHENIX GitHub at line 91 of file PHG4CylinderGeomv4.h
Referenced by find_strip_center(), get_strip_z_spacing(), and identify().
double PHG4CylinderGeomv4::thickness {std::numeric_limits<double>::quiet_NaN()} protected
Definition at line 93 of file PHG4CylinderGeomv4.h.
View newest version in sPHENIX GitHub at line 93 of file PHG4CylinderGeomv4.h
Referenced by get_thickness().
The documentation for this class was generated from the following files:
coresoftware/blob/master/simulation/g4simulation/g4detectors/PHG4CylinderGeomv4.h
coresoftware/blob/master/simulation/g4simulation/g4detectors/PHG4CylinderGeomv4.cc