Analysis Software: PHCompositeNode Class Reference
PHCompositeNode Class Reference
#include <coresoftware/blob/master/offline/framework/phool/PHCompositeNode.h>
Public Member Functions
PHCompositeNode (const std::string &)
~PHCompositeNode () override
bool addNode (PHNode *)
void prune () override
void print (const std::string &="") override
bool write (PHIOManager *, const std::string &="") override
Public Member Functions inherited from PHNode
PHNode (const std::string &)
PHNode (const std::string &, const std::string &)
virtual ~PHNode ()
PHNode * getParent () const
bool isPersistent () const
void makePersistent ()
const std::string getObjectType () const
const std::string getType () const
const std::string getName () const
const std::string getClass () const
void setParent (PHNode *p)
void setName (const std::string &n)
void setObjectType (const std::string &n)
virtual void setResetFlag (const bool b)
virtual bool getResetFlag () const
void makeTransient ()
Protected Member Functions
void forgetMe (PHNode *) override
Protected Attributes
PHPointerList< PHNode > subNodes
int deleteMe = 0
Protected Attributes inherited from PHNode
PHNode * parent = nullptr
bool persistent = true
std::string type = "PHNode"
std::string objecttype
std::string name
bool reset_able = true
std::string objectclass
Private Member Functions
PHCompositeNode ()=delete
Friends
class PHNodeIterator
Detailed Description
Definition at line 14 of file PHCompositeNode.h.
View newest version in sPHENIX GitHub at line 14 of file PHCompositeNode.h
Constructor & Destructor Documentation
PHCompositeNode::PHCompositeNode (const std::string & n) explicit
Definition at line 16 of file PHCompositeNode.cc.
View newest version in sPHENIX GitHub at line 16 of file PHCompositeNode.cc
References PHNode::type.
PHCompositeNode::~PHCompositeNode () override
Definition at line 22 of file PHCompositeNode.cc.
View newest version in sPHENIX GitHub at line 22 of file PHCompositeNode.cc
References PHPointerList< T >::clearAndDestroy(), deleteMe, and subNodes.
PHCompositeNode::PHCompositeNode () private delete
Referenced by PHG4OHCalDetector::AddGeometryNode(), PHG4IHCalDetector::AddGeometryNode(), PHG4OuterHcalDetector::AddGeometryNode(), PHG4InnerHcalDetector::AddGeometryNode(), PHTruthTrackSeeding::CreateNodes(), PHG4InnerHcalSteppingAction::CreateNodeTree(), PHG4OuterHcalSteppingAction::CreateNodeTree(), PHG4IHCalSteppingAction::CreateNodeTree(), PHG4OHCalSteppingAction::CreateNodeTree(), PHTruthClustering::GetNodes(), and PHG4SpacalSteppingAction::InitWithNode().
Member Function Documentation
bool PHCompositeNode::addNode (PHNode * newNode)
Definition at line 34 of file PHCompositeNode.cc.
View newest version in sPHENIX GitHub at line 34 of file PHCompositeNode.cc
References PHPointerList< T >::append(), PHNode::getName(), PHWHERE, PHNode::setParent(), and subNodes.
Referenced by PHG4SpacalDetector::AddCellGeometryNode(), PHG4OHCalDetector::AddGeometryNode(), PHG4EICMvtxDetector::AddGeometryNode(), PHG4IHCalDetector::AddGeometryNode(), PHG4MvtxDetector::AddGeometryNode(), PHG4InttDetector::AddGeometryNode(), PHG4OuterHcalDetector::AddGeometryNode(), PHG4InnerHcalDetector::AddGeometryNode(), PHNodeIterator::addNode(), PHG4SpacalDetector::AddTowerGeometryNode(), PHG4HcalDetector::ConstructMe(), PHG4SpacalPrototype4Detector::ConstructMe(), PHG4SpacalPrototypeDetector::ConstructMe(), PHG4SpacalDetector::ConstructMe(), PHFlowJetMaker::create_node_tree(), AlignmentTransformation::createAlignmentTransformContainer(), DecayFinder::createDecayNode(), SingleMicromegasPoolInput::CreateDSTNode(), SingleTpcPoolInput::CreateDSTNode(), SingleGl1PoolInput::CreateDSTNode(), SingleInttPoolInput::CreateDSTNode(), SingleMvtxPoolInput::CreateDSTNode(), CaloGeomMapping::CreateGeomNode(), ResonanceJetTagging::createJetNode(), TreeMaker::CreateNode(), SubtractTowersCS::CreateNode(), RetowerCEMC::CreateNode(), SubtractTowers::CreateNode(), CaloTriggerSim::CreateNode(), PHG4CentralityReco::CreateNode(), CopyAndSubtractJets::CreateNode(), DetermineTowerBackground::CreateNode(), ParticleFlowReco::CreateNode(), JetMultSub::CreateNode(), CentralityReco::CreateNodes(), RawClusterBuilderGraph::CreateNodes(), MinimumBiasClassifier::CreateNodes(), TrackingIterationCounter::createNodes(), MbdReco::createNodes(), SvtxTruthRecoTableEval::createNodes(), MbdVertexFastSimReco::CreateNodes(), FastPid_RICH::CreateNodes(), InttVertexFinder::createNodes(), GlobalVertexFastSimReco::CreateNodes(), PHTrackClusterAssociator::createNodes(), PHCosmicSeeder::createNodes(), PHActsKDTreeSeeding::createNodes(), RICHParticleID::CreateNodes(), GlobalVertexReco::CreateNodes(), PHSimpleVertexFinder::CreateNodes(), PHInitVertexing::CreateNodes(), PHActsVertexFitter::createNodes(), MbdDigitization::CreateNodes(), PHActsToSvtxTracks::createNodes(), EventPlaneReco::CreateNodes(), PHActsVertexFinder::createNodes(), FillTruthRecoMatchMap::createNodes(), RawClusterBuilderTemplate::CreateNodes(), PHTrackSetMerging::CreateNodes(), PHG4EPDModuleReco::CreateNodes(), RawTowerBuilder::CreateNodes(), RawTowerBuilderByHitIndex::CreateNodes(), PHTrackSeeding::CreateNodes(), PHActsInitialVertexFinder::createNodes(), JetHepMCLoader::CreateNodes(), PHTruthTrackSeeding::CreateNodes(), RawClusterBuilderTopo::CreateNodes(), FillTruthRecoMatchTree::createNodes(), HcalRawTowerBuilder::CreateNodes(), HelicalFitter::CreateNodes(), PHCosmicsTrkFitter::createNodes(), PHActsSiliconSeeding::createNodes(), PHRaveVertexing::CreateNodes(), TpcPrototypeGenFitTrkFinder::CreateNodes(), PHActsTrkFitter::createNodes(), RawTowerCalibration::CreateNodes(), MakeActsGeometry::createNodes(), PHG4TrackFastSim::CreateNodes(), RawTowerDigitizer::CreateNodes(), TpcPrototypeGenFitTrkFitter::CreateNodes(), EventInfoSummary::CreateNodeTree(), RunInfoUnpackPRDF::CreateNodeTree(), SyncReco::CreateNodeTree(), GenericUnpackPRDF::CreateNodeTree(), TempInfoUnpackPRDF::CreateNodeTree(), CaloUnpackPRDF::CreateNodeTree(), RawClusterPositionCorrection::CreateNodeTree(), CaloTowerBuilder::CreateNodeTree(), Emcal_Tower_Masking::CreateNodeTree(), CaloTowerCalib::CreateNodeTree(), MvtxRunInfoUnpackPRDF::CreateNodeTree(), SaveTowerInfo::CreateNodeTree(), PHG4InnerHcalSteppingAction::CreateNodeTree(), MvtxPrototype2UnpackPRDF::CreateNodeTree(), PHG4OuterHcalSteppingAction::CreateNodeTree(), PHG4IHCalSteppingAction::CreateNodeTree(), MvtxUnpackPRDF::CreateNodeTree(), ReadEICFiles::CreateNodeTree(), PHG4OHCalSteppingAction::CreateNodeTree(), CaloWaveformSim::CreateNodeTree(), SecondaryVertexFinder::CreateOutputNode(), KFParticle_DST::createParticleNode(), PHSiliconHelicalPropagator::createSeedContainer(), PHCosmicSiliconPropagator::createSeedContainer(), Fun4AllHepMCInputManager::Fun4AllHepMCInputManager(), Fun4AllOscarInputManager::Fun4AllOscarInputManager(), Fun4AllPrdfInputManager::Fun4AllPrdfInputManager(), Fun4AllPrdfInputPoolManager::Fun4AllPrdfInputPoolManager(), Fun4AllServer::getNode(), TrackSeedTrackMapConverter::getNodes(), PHTpcClusterMover::GetNodes(), PHTrackSelector::GetNodes(), PHTruthClustering::GetNodes(), PHSiliconTpcTrackMatching::GetNodes(), PHTruthSiliconAssociation::GetNodes(), PHTpcCentralMembraneClusterizer::GetNodes(), PHTpcCentralMembraneMatcher::GetNodes(), ElectronID::GetNodes(), MakeSimpleTree::Init(), PHG4HeadReco::Init(), HeadReco::Init(), HepMCCompress::Init(), G4ScintillatorSlatTTree::Init(), G4RawTowerTTree::Init(), G4ScintillatorTowerTTree::Init(), G4HitTTree::Init(), EventCombiner::Init(), HepMCNodeReader::Init(), PairMaker::Init(), FilterEvents::Init(), FilterEventsUpsilon::Init(), PHG4SectorSubsystem::Init(), PHG4EnvelopeSubsystem::Init(), PJTranslator::Init(), PHG4CEmcTestBeamSubsystem::Init(), G4Example01Subsystem::Init(), PHG4HcalPrototypeSubsystem::Init(), HFTrackEfficiency::Init(), Fun4AllServer::InitNodeTree(), Fun4AllPrdfOutputManager::InitPrdfNode(), PHG4InEventReadBack::InitRun(), PHG4InEventCompress::InitRun(), Prototype2RawTowerBuilder::InitRun(), TpcPrototypeClusterizer::InitRun(), PHG4Prototype2HcalCellReco::InitRun(), InttCombinedRawDataDecoder::InitRun(), PHG4ParticleGeneratorBase::InitRun(), CosmicSpray::InitRun(), JetProbeMaker::InitRun(), PHG4HcalCellReco::InitRun(), PHG4EPDModuleReco::InitRun(), PHG4InttDigitizer::InitRun(), HcalRawTowerBuilder::InitRun(), InttRawDataDecoder::InitRun(), PHG4BlockCellReco::InitRun(), PHG4CylinderCellReco::InitRun(), PHG4DetectorSubsystem::InitRun(), PHG4TruthSubsystem::InitRun(), PHG4DetectorGroupSubsystem::InitRun(), MvtxPrototype2Clusterizer::InitRun(), PHG4ParticleGeneratorVectorMeson::InitRun(), PHG4SimpleEventGenerator::InitRun(), PHG4FullProjSpacalCellReco::InitRun(), PHG4TpcPadPlane::InitRun(), PHG4TpcDirectLaser::InitRun(), TpcSimpleClusterizer::InitRun(), InttClusterizer::InitRun(), TpcCombinedRawDataUnpacker::InitRun(), DeadHotMapLoader::InitRun(), PHG4InttDeadMapLoader::InitRun(), TpcRawWriter::InitRun(), PHG4InttHitReco::InitRun(), TpcClusterizer::InitRun(), PHG4HcalSubsystem::InitRun(), MvtxCombinedRawDataDecoder::InitRun(), MvtxClusterizer::InitRun(), PHG4TpcElectronDrift::InitRun(), TpcPrototypeUnpacker::InitRun(), PHG4EPDSubsystem::InitRunSubsystem(), PHG4OuterHcalSubsystem::InitRunSubsystem(), PHG4OHCalSubsystem::InitRunSubsystem(), PHG4InnerHcalSubsystem::InitRunSubsystem(), PHG4ZDCSubsystem::InitRunSubsystem(), PHG4IHCalSubsystem::InitRunSubsystem(), PHG4SpacalPrototype4Subsystem::InitRunSubsystem(), BeamLineMagnetSubsystem::InitRunSubsystem(), PHG4Prototype2InnerHcalSubsystem::InitRunSubsystem(), PHG4Prototype2OuterHcalSubsystem::InitRunSubsystem(), PHG4TpcSubsystem::InitRunSubsystem(), PHG4Prototype3InnerHcalSubsystem::InitRunSubsystem(), PHG4CylinderSubsystem::InitRunSubsystem(), PHG4SpacalPrototypeSubsystem::InitRunSubsystem(), PHG4ConeSubsystem::InitRunSubsystem(), PHG4BlockSubsystem::InitRunSubsystem(), PHG4EICMvtxSubsystem::InitRunSubsystem(), PHG4MvtxSubsystem::InitRunSubsystem(), PHG4InttSubsystem::InitRunSubsystem(), PHG4TpcEndCapSubsystem::InitRunSubsystem(), G4Example02Subsystem::InitRunSubsystem(), G4Example03Subsystem::InitRunSubsystem(), PHG4SpacalSubsystem::InitRunSubsystem(), PHG4BbcSubsystem::InitRunSubsystem(), PHG4PSTOFSubsystem::InitRunSubsystem(), PHG4SpacalSteppingAction::InitWithNode(), PHParameterInterface::PutOnParNode(), PHParameterContainerInterface::PutOnParNode(), and PHG4Reco::setupInputEventNodeReader().
void PHCompositeNode::forgetMe (PHNode * child) override protected virtual
Implements PHNode.
Definition at line 76 of file PHCompositeNode.cc.
View newest version in sPHENIX GitHub at line 76 of file PHCompositeNode.cc
References deleteMe, PHPointerListIterator< T >::pos(), PHPointerList< T >::removeAt(), and subNodes.
void PHCompositeNode::print (const std::string & path = "") override virtual
Implements PHNode.
Definition at line 118 of file PHCompositeNode.cc.
View newest version in sPHENIX GitHub at line 118 of file PHCompositeNode.cc
References PHNode::name, path, PHNode::print(), subNodes, and PHNode::type.
Referenced by PHG4SpacalDetector::AddCellGeometryNode(), analysis::Init(), jetrtrack::Init(), FillTruthRecoMatchMap::Init(), FillTruthRecoMatchTree::Init(), Emcal_Tower_Masking::InitRun(), CaloTowerStatus::InitRun(), LEDTowerBuilder::InitRun(), caloTowerEmbed::InitRun(), PHG4OuterHcalSteppingAction::InitWithNode(), PHG4InnerHcalSteppingAction::InitWithNode(), PHG4IHCalSteppingAction::InitWithNode(), PHG4OHCalSteppingAction::InitWithNode(), PHNodeIterator::print(), sPHAnalysis_calo::process_event_data(), sPHAnalysis::process_event_hepmc(), sPHAnalysis::process_event_pythiaupsilon(), PairMaker::process_event_test(), sPHAnalysis_calo::process_event_test(), and sPHAnalysis::process_event_upsilons().
void PHCompositeNode::prune () override virtual
Implements PHNode.
Definition at line 57 of file PHCompositeNode.cc.
View newest version in sPHENIX GitHub at line 57 of file PHCompositeNode.cc
References PHNode::isPersistent(), PHPointerListIterator< T >::pos(), PHNode::prune(), PHPointerList< T >::removeAt(), and subNodes.
bool PHCompositeNode::write (PHIOManager * IOManager, const std::string & path = "") override virtual
Implements PHNode.
Definition at line 98 of file PHCompositeNode.cc.
View newest version in sPHENIX GitHub at line 98 of file PHCompositeNode.cc
References phooldefs::branchpathdelim, PHNode::name, subNodes, and PHNode::write().
Referenced by PHNodeIOManager::write(), and PHRawOManager::write().
Friends And Related Function Documentation
friend class PHNodeIterator friend
Definition at line 16 of file PHCompositeNode.h.
View newest version in sPHENIX GitHub at line 16 of file PHCompositeNode.h
Member Data Documentation
int PHCompositeNode::deleteMe = 0 protected
Definition at line 43 of file PHCompositeNode.h.
View newest version in sPHENIX GitHub at line 43 of file PHCompositeNode.h
Referenced by forgetMe(), and ~PHCompositeNode().
PHPointerList<PHNode> PHCompositeNode::subNodes protected
Definition at line 42 of file PHCompositeNode.h.
View newest version in sPHENIX GitHub at line 42 of file PHCompositeNode.h
Referenced by addNode(), PHNodeIterator::cd(), PHNodeIterator::findFirst(), PHNodeIterator::forEach(), forgetMe(), PHNodeIterator::ls(), print(), prune(), write(), and ~PHCompositeNode().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/framework/phool/PHCompositeNode.h
coresoftware/blob/master/offline/framework/phool/PHCompositeNode.cc