Analysis Software: Acts::Volume Class Reference
Acts::Volume Class Reference
#include <acts/blob/sPHENIX/Core/include/Acts/Geometry/Volume.hpp>
Public Types
using BoundingBox = AxisAlignedBoundingBox< Volume, ActsScalar, 3 >
Public Member Functions
Volume (const Transform3 &transform, VolumeBoundsPtr volbounds)
Volume (const Volume &vol, const Transform3 &shift=Transform3::Identity())
Volume ()=delete
virtual ~Volume ()=default
Volume & operator= (const Volume &vol)
const Transform3 & transform () const
Return methods for geometry transform.
const Transform3 & itransform () const
Returns the inverted transform of this volume.
const Vector3 & center () const
returns the center of the volume
const VolumeBounds & volumeBounds () const
returns the volumeBounds()
BoundingBox boundingBox (const Vector3 &envelope={0, 0, 0}) const
const BoundingBox & orientedBoundingBox () const
bool inside (const Vector3 &gpos, double tol=0.) const
Vector3 binningPosition (const GeometryContext &gctx, BinningValue bValue) const override
Public Member Functions inherited from Acts::GeometryObject
GeometryObject ()=default
Defaulted constructor.
GeometryObject (const GeometryObject &)=default
Defaulted copy constructor.
GeometryObject (const GeometryIdentifier &geometryId)
GeometryObject & operator= (const GeometryObject &geometryId)
const GeometryIdentifier & geometryId () const
virtual double binningPositionValue (const GeometryContext &gctx, BinningValue bValue) const
void assignGeometryId (const GeometryIdentifier &geometryId)
Protected Attributes
Transform3 m_transform
Transform3 m_itransform
Vector3 m_center
VolumeBoundsPtr m_volumeBounds
BoundingBox m_orientedBoundingBox
Protected Attributes inherited from Acts::GeometryObject
GeometryIdentifier m_geometryId
Detailed Description
It inhertis of GeometryObject for TDD identification
Base class for all volumes inside the tracking realm, it defines the interface for inherited Volume classes regarding the geometrical information.
Definition at line 33 of file Volume.hpp.
View newest version in sPHENIX GitHub at line 33 of file Volume.hpp
Member Typedef Documentation
using Acts::Volume::BoundingBox = AxisAlignedBoundingBox<Volume, ActsScalar, 3>
Definition at line 35 of file Volume.hpp.
View newest version in sPHENIX GitHub at line 35 of file Volume.hpp
Constructor & Destructor Documentation
Acts::Volume::Volume (const Transform3 & transform, VolumeBoundsPtr volbounds)
Explicit constructor with shared arguments
Parameters
transform is the transform to position the volume in 3D space
volbounds is the volume boundary definitions
Note
This will automatically build an oriented bounding box with an envelope value of (0.05, 0.05, 0.05)mm
Acts::Volume::Volume (const Volume & vol, const Transform3 & shift = Transform3::Identity())
Copy Constructor - with optional shift
Parameters
vol is the source volume for the copy
shift is the optional shift applied as : shift * vol.transform()
Note
This will automatically build an oriented bounding box with an envelope value of (0.05, 0.05, 0.05)mm
Acts::Volume::Volume () delete
virtual Acts::Volume::~Volume () virtual default
Member Function Documentation
Acts::Vector3 Acts::Volume::binningPosition (const GeometryContext & gctx, Acts::BinningValue bValue) const override virtual
The binning position method
as default the center is given, but may be overloaded
Parameters
gctx The current geometry context object, e.g. alignment
bValue is the binning value schema
Returns
vector 3D that can be used for the binning
Implements Acts::GeometryObject.
Definition at line 38 of file Volume.cpp.
View newest version in sPHENIX GitHub at line 38 of file Volume.cpp
References Acts::binR, Acts::binRPhi, and m_volumeBounds().
Referenced by Acts::TrackingVolume::glueTrackingVolume().
Acts::Volume::BoundingBox Acts::Volume::boundingBox (const Vector3 & envelope = {0, 0, 0}) const
Construct bounding box for this shape
Parameters
envelope Optional envelope to add / subtract from min/max
Returns
Constructed bounding box pointing to this volume
Definition at line 70 of file Volume.cpp.
View newest version in sPHENIX GitHub at line 70 of file Volume.cpp
References m_transform(), and m_volumeBounds().
const Vector3 & Acts::Volume::center () const inline
returns the center of the volume
Definition at line 116 of file Volume.hpp.
View newest version in sPHENIX GitHub at line 116 of file Volume.hpp
References m_center.
Referenced by Acts::Test::BOOST_AUTO_TEST_CASE().
bool Acts::Volume::inside (const Vector3 & gpos, double tol = 0.) const
Inside() method for checks
Parameters
gpos is the position to be checked
tol is the tolerance parameter
Returns
boolean indicator if the position is inside
Definition at line 60 of file Volume.cpp.
View newest version in sPHENIX GitHub at line 60 of file Volume.cpp
References Acts::Test::transform.
Referenced by Acts::Test::BOOST_AUTO_TEST_CASE().
const Transform3 & Acts::Volume::itransform () const inline
Returns the inverted transform of this volume.
Definition at line 112 of file Volume.hpp.
View newest version in sPHENIX GitHub at line 112 of file Volume.hpp
References m_itransform.
Referenced by Acts::Test::BOOST_AUTO_TEST_CASE().
Acts::Volume & Acts::Volume::operator= (const Volume & vol)
Assignment operator
Parameters
vol is the source volume to be copied
Definition at line 51 of file Volume.cpp.
View newest version in sPHENIX GitHub at line 51 of file Volume.cpp
References m_center(), m_center, m_transform(), m_transform, m_volumeBounds(), and m_volumeBounds.
const Acts::Volume::BoundingBox & Acts::Volume::orientedBoundingBox () const
Construct oriented bounding box for this shape
Returns
Constructed oriented bounding box pointing to this volume
Definition at line 75 of file Volume.cpp.
View newest version in sPHENIX GitHub at line 75 of file Volume.cpp
References m_orientedBoundingBox().
Referenced by Acts::Test::BOOST_AUTO_TEST_CASE().
const Transform3 & Acts::Volume::transform () const inline
Return methods for geometry transform.
Definition at line 108 of file Volume.hpp.
View newest version in sPHENIX GitHub at line 108 of file Volume.hpp
References m_transform.
Referenced by Acts::adjustBinUtility(), and Acts::Test::BOOST_AUTO_TEST_CASE().
const VolumeBounds & Acts::Volume::volumeBounds () const inline
returns the volumeBounds()
Definition at line 120 of file Volume.hpp.
View newest version in sPHENIX GitHub at line 120 of file Volume.hpp
References m_volumeBounds.
Referenced by Acts::adjustBinUtility(), Acts::Test::BOOST_AUTO_TEST_CASE(), Acts::AbstractVolume::createBoundarySurfaces(), Acts::TrackingVolume::createBoundarySurfaces(), and Acts::operator<<().
Member Data Documentation
Vector3 Acts::Volume::m_center protected
Definition at line 103 of file Volume.hpp.
View newest version in sPHENIX GitHub at line 103 of file Volume.hpp
Referenced by center(), and operator=().
Transform3 Acts::Volume::m_itransform protected
Definition at line 102 of file Volume.hpp.
View newest version in sPHENIX GitHub at line 102 of file Volume.hpp
Referenced by itransform().
BoundingBox Acts::Volume::m_orientedBoundingBox protected
Definition at line 105 of file Volume.hpp.
View newest version in sPHENIX GitHub at line 105 of file Volume.hpp
Transform3 Acts::Volume::m_transform protected
Definition at line 101 of file Volume.hpp.
View newest version in sPHENIX GitHub at line 101 of file Volume.hpp
Referenced by operator=(), and transform().
VolumeBoundsPtr Acts::Volume::m_volumeBounds protected
Definition at line 104 of file Volume.hpp.
View newest version in sPHENIX GitHub at line 104 of file Volume.hpp
Referenced by operator=(), and volumeBounds().
The documentation for this class was generated from the following files:
acts/blob/sPHENIX/Core/include/Acts/Geometry/Volume.hpp
acts/blob/sPHENIX/Core/src/Geometry/Volume.cpp