Analysis Software: odbc::DriverManager Class Reference
odbc::DriverManager Class Reference
#include <RDBC/blob/master/include/RDBC/odbc++/drivermanager.h>
Static Public Member Functions
static Connection * getConnection (const ODBCXX_STRING &dsn, const ODBCXX_STRING &user, const ODBCXX_STRING &password)
static Connection * getConnection (const ODBCXX_STRING &connectString)
static int getLoginTimeout ()
static void setLoginTimeout (int seconds)
static DataSourceList * getDataSources ()
static DriverList * getDrivers ()
static void shutdown ()
Private Member Functions
DriverManager ()
Static Private Member Functions
static void _checkInit ()
static Connection * _createConnection ()
Static Private Attributes
static SQLHENV henv_
static ErrorHandler * eh_
static int loginTimeout_
Detailed Description
The DriverManager.
Definition at line 99 of file drivermanager.h.
View newest version in sPHENIX GitHub at line 99 of file drivermanager.h
Constructor & Destructor Documentation
odbc::DriverManager::DriverManager () private
Member Function Documentation
static void odbc::DriverManager::_checkInit () static private
static Connection* odbc::DriverManager::_createConnection () static private
static Connection* odbc::DriverManager::getConnection (const ODBCXX_STRING & dsn, const ODBCXX_STRING & user, const ODBCXX_STRING & password) static
Opens a connection by it's DSN, a username and a password
Referenced by OnlMonClient::CacheRunDB(), OnlMonServer::CacheRunDB(), ClassImpQ(), OnlMonStatusDB::GetConnection(), PktSizeDBodbc::GetConnection(), FROG::GetConnection(), OnlMonDBodbc::GetConnection(), RunToTimePg::GetConnection(), OnCalDBodbc::GetLastCalibratedRun(), RunDBodbc::GetRunNumbers(), ODBCConnection::ODBCConnection(), and RunDBodbc::RunType().
static Connection* odbc::DriverManager::getConnection (const ODBCXX_STRING & connectString) static
Opens a connection using an ODBC connect string.
Parameters
connectString Usually something like "DSN=db;uid=user;pwd=password"
static DataSourceList* odbc::DriverManager::getDataSources () static
Fetch a list of all available data sources
Referenced by ODBCConnection::RefreshDataSources().
static DriverList* odbc::DriverManager::getDrivers () static
Fetch a list of the available drivers
Referenced by ODBCConnection::RefreshDrivers().
static int odbc::DriverManager::getLoginTimeout () static
Gets the current login timeout in seconds.
Returns
The current login timeout in seconds, or 0 if disabled.
Referenced by ODBCConnection::GetLoginTimeout().
static void odbc::DriverManager::setLoginTimeout (int seconds) static
Sets the login timeout in seconds
Parameters
seconds The number of seconds to wait for a connection to open. Set to 0 to disable.
Referenced by ODBCConnection::SetLoginTimeout().
static void odbc::DriverManager::shutdown () static
Should be called before an application is to exit and after all connections have been closed.
Referenced by ODBCConnection::Shutdown().
Member Data Documentation
ErrorHandler* odbc::DriverManager::eh_ static private
Definition at line 102 of file drivermanager.h.
View newest version in sPHENIX GitHub at line 102 of file drivermanager.h
SQLHENV odbc::DriverManager::henv_ static private
Definition at line 101 of file drivermanager.h.
View newest version in sPHENIX GitHub at line 101 of file drivermanager.h
int odbc::DriverManager::loginTimeout_ static private
Definition at line 103 of file drivermanager.h.
View newest version in sPHENIX GitHub at line 103 of file drivermanager.h
The documentation for this class was generated from the following file:
RDBC/blob/master/include/RDBC/odbc++/drivermanager.h