Analysis Software: Vertex Class Reference
Vertex Class Reference
#include <coresoftware/blob/master/offline/packages/globalvertex/Vertex.h>
Public Types
typedef std::set< unsigned int > TrackSet
typedef std::set< unsigned int >
::const_iterator ConstTrackIter
typedef std::set< unsigned int >
::iterator TrackIter
Public Member Functions
~Vertex () override
void identify (std::ostream &os=std::cout) const override
PHObject * CloneMe () const override
Virtual copy constructor.
int isValid () const override
isValid returns non zero if object contains vailid data
virtual unsigned int get_id () const
virtual void set_id (unsigned int)
virtual float get_t () const
virtual void set_t (float)
virtual float get_t0 () const
virtual void set_t0 (float t0)
virtual float get_t_err () const
virtual void set_t_err (float)
virtual float get_x () const
virtual void set_x (float)
virtual float get_y () const
virtual void set_y (float)
virtual float get_z () const
virtual void set_z (float)
virtual float get_chisq () const
virtual void set_chisq (float)
virtual unsigned int get_ndof () const
virtual void set_ndof (unsigned int)
virtual float get_position (unsigned int) const
virtual void set_position (unsigned int, float)
virtual float get_error (unsigned int, unsigned int) const
virtual void set_error (unsigned int, unsigned int, float)
virtual unsigned int get_beam_crossing () const
virtual void set_beam_crossing (unsigned int)
virtual void set_bbc_ns (int, int, float, float)
virtual int get_bbc_npmt (int) const
virtual float get_z_err () const
virtual void set_z_err (float)
virtual float get_bbc_q (int) const
virtual float get_bbc_t (int) const
virtual void clear_tracks ()
virtual bool empty_tracks ()
virtual size_t size_tracks () const
virtual void insert_track (unsigned int)
virtual size_t erase_track (unsigned int)
virtual ConstTrackIter begin_tracks () const
virtual ConstTrackIter find_track (unsigned int trackid) const
virtual ConstTrackIter end_tracks () const
virtual TrackIter begin_tracks ()
virtual TrackIter find_track (unsigned int trackid)
virtual TrackIter end_tracks ()
Public Member Functions inherited from PHObject
PHObject ()
ctor
~PHObject () override
dtor
virtual PHObject * clone () const final
PHObject * Clone (const char *newname="") const final
void Copy (TObject &object) const final
virtual void Reset ()
Clear Event.
virtual int Integrate () const
virtual int Integrate (PHObject *)
virtual void CopyFrom (const PHObject *obj)
Private Member Functions
ClassDefOverride (Vertex, 1)
Detailed Description
Definition at line 11 of file Vertex.h.
View newest version in sPHENIX GitHub at line 11 of file Vertex.h
Member Typedef Documentation
typedef std::set<unsigned int>::const_iterator Vertex::ConstTrackIter
Definition at line 15 of file Vertex.h.
View newest version in sPHENIX GitHub at line 15 of file Vertex.h
typedef std::set<unsigned int>::iterator Vertex::TrackIter
Definition at line 16 of file Vertex.h.
View newest version in sPHENIX GitHub at line 16 of file Vertex.h
typedef std::set<unsigned int> Vertex::TrackSet
Definition at line 14 of file Vertex.h.
View newest version in sPHENIX GitHub at line 14 of file Vertex.h
Constructor & Destructor Documentation
Vertex::~Vertex () inline override
Definition at line 18 of file Vertex.h.
View newest version in sPHENIX GitHub at line 18 of file Vertex.h
Member Function Documentation
Vertex::ConstTrackIter Vertex::begin_tracks () const virtual
Reimplemented in SvtxVertex, SvtxVertex_v1, and SvtxVertex_v2.
Definition at line 5 of file Vertex.cc.
View newest version in sPHENIX GitHub at line 5 of file Vertex.cc
References DummyTrackSet.
Referenced by SvtxVertexEval::all_truth_particles(), and SvtxVertexEval::get_ntracks_contribution().
Vertex::TrackIter Vertex::begin_tracks () virtual
Reimplemented in SvtxVertex, SvtxVertex_v1, and SvtxVertex_v2.
Definition at line 20 of file Vertex.cc.
View newest version in sPHENIX GitHub at line 20 of file Vertex.cc
References DummyTrackSet.
Vertex::ClassDefOverride (Vertex , 1) private
virtual void Vertex::clear_tracks () inline virtual
Reimplemented in SvtxVertex, SvtxVertex_v1, and SvtxVertex_v2.
Definition at line 76 of file Vertex.h.
View newest version in sPHENIX GitHub at line 76 of file Vertex.h
PHObject* Vertex::CloneMe () const inline override virtual
Virtual copy constructor.
Reimplemented from PHObject.
Definition at line 23 of file Vertex.h.
View newest version in sPHENIX GitHub at line 23 of file Vertex.h
virtual bool Vertex::empty_tracks () inline virtual
Reimplemented in SvtxVertex, SvtxVertex_v1, and SvtxVertex_v2.
Definition at line 77 of file Vertex.h.
View newest version in sPHENIX GitHub at line 77 of file Vertex.h
Vertex::ConstTrackIter Vertex::end_tracks () const virtual
Reimplemented in SvtxVertex, SvtxVertex_v1, and SvtxVertex_v2.
Definition at line 15 of file Vertex.cc.
View newest version in sPHENIX GitHub at line 15 of file Vertex.cc
References DummyTrackSet.
Referenced by SvtxVertexEval::all_truth_particles(), and SvtxVertexEval::get_ntracks_contribution().
Vertex::TrackIter Vertex::end_tracks () virtual
Reimplemented in SvtxVertex, SvtxVertex_v1, and SvtxVertex_v2.
Definition at line 30 of file Vertex.cc.
View newest version in sPHENIX GitHub at line 30 of file Vertex.cc
References DummyTrackSet.
virtual size_t Vertex::erase_track (unsigned int) inline virtual
Reimplemented in SvtxVertex, SvtxVertex_v1, and SvtxVertex_v2.
Definition at line 80 of file Vertex.h.
View newest version in sPHENIX GitHub at line 80 of file Vertex.h
Vertex::ConstTrackIter Vertex::find_track (unsigned int trackid) const virtual
Reimplemented in SvtxVertex, SvtxVertex_v1, and SvtxVertex_v2.
Definition at line 10 of file Vertex.cc.
View newest version in sPHENIX GitHub at line 10 of file Vertex.cc
References DummyTrackSet.
Vertex::TrackIter Vertex::find_track (unsigned int trackid) virtual
Reimplemented in SvtxVertex, SvtxVertex_v1, and SvtxVertex_v2.
Definition at line 25 of file Vertex.cc.
View newest version in sPHENIX GitHub at line 25 of file Vertex.cc
References DummyTrackSet.
virtual int Vertex::get_bbc_npmt (int) const inline virtual
Reimplemented in MbdVertex.
Definition at line 68 of file Vertex.h.
View newest version in sPHENIX GitHub at line 68 of file Vertex.h
virtual float Vertex::get_bbc_q (int) const inline virtual
Reimplemented in MbdVertex.
Definition at line 72 of file Vertex.h.
View newest version in sPHENIX GitHub at line 72 of file Vertex.h
virtual float Vertex::get_bbc_t (int) const inline virtual
Reimplemented in MbdVertex.
Definition at line 73 of file Vertex.h.
View newest version in sPHENIX GitHub at line 73 of file Vertex.h
virtual unsigned int Vertex::get_beam_crossing () const inline virtual
Reimplemented in SvtxVertex_v2, MbdVertexv2, and MbdVertex.
Definition at line 63 of file Vertex.h.
View newest version in sPHENIX GitHub at line 63 of file Vertex.h
virtual float Vertex::get_chisq () const inline virtual
Reimplemented in SvtxVertex, SvtxVertex_v1, and SvtxVertex_v2.
Definition at line 50 of file Vertex.h.
View newest version in sPHENIX GitHub at line 50 of file Vertex.h
virtual float Vertex::get_error (unsigned int , unsigned int) const inline virtual
Reimplemented in SvtxVertex, SvtxVertex_v1, and SvtxVertex_v2.
Definition at line 59 of file Vertex.h.
View newest version in sPHENIX GitHub at line 59 of file Vertex.h
virtual unsigned int Vertex::get_id () const inline virtual
Reimplemented in SvtxVertex, SvtxVertex_v1, SvtxVertex_v2, MbdVertexv1, MbdVertexv2, and MbdVertex.
Definition at line 28 of file Vertex.h.
View newest version in sPHENIX GitHub at line 28 of file Vertex.h
virtual unsigned int Vertex::get_ndof () const inline virtual
Reimplemented in SvtxVertex, SvtxVertex_v1, and SvtxVertex_v2.
Definition at line 53 of file Vertex.h.
View newest version in sPHENIX GitHub at line 53 of file Vertex.h
virtual float Vertex::get_position (unsigned int) const inline virtual
Reimplemented in SvtxVertex, SvtxVertex_v1, SvtxVertex_v2, and MbdVertexv2.
Definition at line 56 of file Vertex.h.
View newest version in sPHENIX GitHub at line 56 of file Vertex.h
virtual float Vertex::get_t () const inline virtual
Reimplemented in SvtxVertex, SvtxVertex_v1, SvtxVertex_v2, MbdVertexv1, MbdVertexv2, and MbdVertex.
Definition at line 31 of file Vertex.h.
View newest version in sPHENIX GitHub at line 31 of file Vertex.h
Referenced by get_t0().
virtual float Vertex::get_t0 () const inline virtual
Reimplemented in SvtxVertex, and SvtxVertex_v1.
Definition at line 35 of file Vertex.h.
View newest version in sPHENIX GitHub at line 35 of file Vertex.h
References get_t().
virtual float Vertex::get_t_err () const inline virtual
Reimplemented in MbdVertexv1, MbdVertexv2, and MbdVertex.
Definition at line 38 of file Vertex.h.
View newest version in sPHENIX GitHub at line 38 of file Vertex.h
virtual float Vertex::get_x () const inline virtual
Reimplemented in SvtxVertex, SvtxVertex_v1, MbdVertexv2, and SvtxVertex_v2.
Definition at line 41 of file Vertex.h.
View newest version in sPHENIX GitHub at line 41 of file Vertex.h
Referenced by SvtxEvaluator::fillOutputNtuples().
virtual float Vertex::get_y () const inline virtual
Reimplemented in SvtxVertex, SvtxVertex_v1, SvtxVertex_v2, and MbdVertexv2.
Definition at line 44 of file Vertex.h.
View newest version in sPHENIX GitHub at line 44 of file Vertex.h
Referenced by SvtxEvaluator::fillOutputNtuples().
virtual float Vertex::get_z () const inline virtual
Reimplemented in SvtxVertex, SvtxVertex_v1, SvtxVertex_v2, MbdVertexv2, MbdVertexv1, and MbdVertex.
Definition at line 47 of file Vertex.h.
View newest version in sPHENIX GitHub at line 47 of file Vertex.h
Referenced by SvtxEvaluator::fillOutputNtuples().
virtual float Vertex::get_z_err () const inline virtual
Reimplemented in MbdVertexv2, MbdVertexv1, and MbdVertex.
Definition at line 69 of file Vertex.h.
View newest version in sPHENIX GitHub at line 69 of file Vertex.h
void Vertex::identify (std::ostream & os = std::cout) const inline override virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from PHObject.
Definition at line 22 of file Vertex.h.
View newest version in sPHENIX GitHub at line 22 of file Vertex.h
References os.
virtual void Vertex::insert_track (unsigned int) inline virtual
Reimplemented in SvtxVertex, SvtxVertex_v1, and SvtxVertex_v2.
Definition at line 79 of file Vertex.h.
View newest version in sPHENIX GitHub at line 79 of file Vertex.h
int Vertex::isValid () const inline override virtual
isValid returns non zero if object contains vailid data
Reimplemented from PHObject.
Definition at line 24 of file Vertex.h.
View newest version in sPHENIX GitHub at line 24 of file Vertex.h
virtual void Vertex::set_bbc_ns (int , int , float , float) inline virtual
Reimplemented in MbdVertex.
Definition at line 67 of file Vertex.h.
View newest version in sPHENIX GitHub at line 67 of file Vertex.h
virtual void Vertex::set_beam_crossing (unsigned int) inline virtual
Reimplemented in SvtxVertex_v2, MbdVertexv2, and MbdVertex.
Definition at line 64 of file Vertex.h.
View newest version in sPHENIX GitHub at line 64 of file Vertex.h
virtual void Vertex::set_chisq (float) inline virtual
Reimplemented in SvtxVertex, SvtxVertex_v1, and SvtxVertex_v2.
Definition at line 51 of file Vertex.h.
View newest version in sPHENIX GitHub at line 51 of file Vertex.h
virtual void Vertex::set_error (unsigned int , unsigned int , float) inline virtual
Reimplemented in SvtxVertex, SvtxVertex_v1, and SvtxVertex_v2.
Definition at line 60 of file Vertex.h.
View newest version in sPHENIX GitHub at line 60 of file Vertex.h
virtual void Vertex::set_id (unsigned int) inline virtual
Reimplemented in SvtxVertex, SvtxVertex_v1, SvtxVertex_v2, MbdVertexv1, MbdVertexv2, and MbdVertex.
Definition at line 29 of file Vertex.h.
View newest version in sPHENIX GitHub at line 29 of file Vertex.h
virtual void Vertex::set_ndof (unsigned int) inline virtual
Reimplemented in SvtxVertex, SvtxVertex_v1, and SvtxVertex_v2.
Definition at line 54 of file Vertex.h.
View newest version in sPHENIX GitHub at line 54 of file Vertex.h
virtual void Vertex::set_position (unsigned int , float) inline virtual
Reimplemented in SvtxVertex, SvtxVertex_v1, and SvtxVertex_v2.
Definition at line 57 of file Vertex.h.
View newest version in sPHENIX GitHub at line 57 of file Vertex.h
virtual void Vertex::set_t (float) inline virtual
Reimplemented in SvtxVertex, SvtxVertex_v1, SvtxVertex_v2, MbdVertexv1, MbdVertexv2, and MbdVertex.
Definition at line 32 of file Vertex.h.
View newest version in sPHENIX GitHub at line 32 of file Vertex.h
Referenced by set_t0().
virtual void Vertex::set_t0 (float t0) inline virtual
Reimplemented in SvtxVertex, and SvtxVertex_v1.
Definition at line 36 of file Vertex.h.
View newest version in sPHENIX GitHub at line 36 of file Vertex.h
References set_t().
virtual void Vertex::set_t_err (float) inline virtual
Reimplemented in MbdVertexv1, MbdVertexv2, and MbdVertex.
Definition at line 39 of file Vertex.h.
View newest version in sPHENIX GitHub at line 39 of file Vertex.h
virtual void Vertex::set_x (float) inline virtual
Reimplemented in SvtxVertex, SvtxVertex_v1, and SvtxVertex_v2.
Definition at line 42 of file Vertex.h.
View newest version in sPHENIX GitHub at line 42 of file Vertex.h
virtual void Vertex::set_y (float) inline virtual
Reimplemented in SvtxVertex, SvtxVertex_v1, and SvtxVertex_v2.
Definition at line 45 of file Vertex.h.
View newest version in sPHENIX GitHub at line 45 of file Vertex.h
virtual void Vertex::set_z (float) inline virtual
Reimplemented in SvtxVertex, SvtxVertex_v1, SvtxVertex_v2, MbdVertexv2, MbdVertexv1, and MbdVertex.
Definition at line 48 of file Vertex.h.
View newest version in sPHENIX GitHub at line 48 of file Vertex.h
virtual void Vertex::set_z_err (float) inline virtual
Reimplemented in MbdVertexv2, MbdVertexv1, and MbdVertex.
Definition at line 70 of file Vertex.h.
View newest version in sPHENIX GitHub at line 70 of file Vertex.h
virtual size_t Vertex::size_tracks () const inline virtual
Reimplemented in SvtxVertex, SvtxVertex_v1, and SvtxVertex_v2.
Definition at line 78 of file Vertex.h.
View newest version in sPHENIX GitHub at line 78 of file Vertex.h
Referenced by SvtxEvaluator::fillOutputNtuples().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/globalvertex/Vertex.h
coresoftware/blob/master/offline/packages/globalvertex/Vertex.cc