Analysis Software: ActsExamples::Generic::GenericDetectorElement Class Reference
ActsExamples::Generic::GenericDetectorElement Class Reference
#include <acts/blob/sPHENIX/Examples/Detectors/GenericDetector/include/ActsExamples/GenericDetector/GenericDetectorElement.hpp>
Public Types
using ContextType = Acts::GeometryContext
Broadcast the ContextType.
Public Member Functions
GenericDetectorElement (const Identifier identifier, std::shared_ptr< const Acts::Transform3 > transform, std::shared_ptr< const Acts::PlanarBounds > pBounds, double thickness, std::shared_ptr< const Acts::ISurfaceMaterial > material=nullptr, std::shared_ptr< const Acts::DigitizationModule > digitizationModule=nullptr)
GenericDetectorElement (const Identifier identifier, std::shared_ptr< const Acts::Transform3 > transform, std::shared_ptr< const Acts::DiscBounds > dBounds, double thickness, std::shared_ptr< const Acts::ISurfaceMaterial > material=nullptr, std::shared_ptr< const Acts::DigitizationModule > digitizationModule=nullptr)
Identifier identifier () const final
Identifier.
const Acts::Transform3 & transform (const Acts::GeometryContext &gctx) const override
const Acts::Surface & surface () const override
Return surface associated with this detector element.
Acts::Surface & surface () override
Non-cost access to surface associated with this detector element.
void assignIdentifier (const Identifier &identifier)
Set the identifier after construction (sometimes needed)
double thickness () const override
The maximal thickness of the detector element wrt normal axis.
const std::shared_ptr< const
Acts::DigitizationModule > digitizationModule () const override
Retrieve the DigitizationModule.
Private Attributes
Identifier m_elementIdentifier
std::shared_ptr< const
Acts::Transform3 > m_elementTransform
the transform for positioning in 3D space
std::shared_ptr< Acts::Surface > m_elementSurface
the surface represented by it
double m_elementThickness
the element thickness
std::shared_ptr< const
Acts::PlanarBounds > m_elementPlanarBounds = nullptr
store either
std::shared_ptr< const
Acts::DiscBounds > m_elementDiscBounds = nullptr
std::shared_ptr< const
Acts::DigitizationModule > m_digitizationModule
The Digitization module.
Detailed Description
This is a lightweight type of detector element, it simply implements the base class.
Definition at line 37 of file GenericDetectorElement.hpp.
View newest version in sPHENIX GitHub at line 37 of file GenericDetectorElement.hpp
Member Typedef Documentation
using ActsExamples::Generic::GenericDetectorElement::ContextType = Acts::GeometryContext
Broadcast the ContextType.
Definition at line 40 of file GenericDetectorElement.hpp.
View newest version in sPHENIX GitHub at line 40 of file GenericDetectorElement.hpp
Constructor & Destructor Documentation
ActsExamples::Generic::GenericDetectorElement::GenericDetectorElement (const Identifier identifier, std::shared_ptr< const Acts::Transform3 > transform, std::shared_ptr< const Acts::PlanarBounds > pBounds, double thickness, std::shared_ptr< const Acts::ISurfaceMaterial > material = nullptr, std::shared_ptr< const Acts::DigitizationModule > digitizationModule = nullptr)
Constructor for single sided detector element
bound to a Plane Surface
Parameters
identifier is the module identifier
transform is the transform that element the layer in 3D frame
pBounds is the planar bounds for the planar detector element
thickness is the module thickness
material is the (optional) Surface material associated to it
Definition at line 16 of file GenericDetectorElement.cpp.
View newest version in sPHENIX GitHub at line 16 of file GenericDetectorElement.cpp
References m_elementSurface, and testing::internal::move().
ActsExamples::Generic::GenericDetectorElement::GenericDetectorElement (const Identifier identifier, std::shared_ptr< const Acts::Transform3 > transform, std::shared_ptr< const Acts::DiscBounds > dBounds, double thickness, std::shared_ptr< const Acts::ISurfaceMaterial > material = nullptr, std::shared_ptr< const Acts::DigitizationModule > digitizationModule = nullptr)
Constructor for single sided detector element
bound to a Disc Surface
Parameters
identifier is the module identifier
transform is the transform that element the layer in 3D frame
dBounds is the planar bounds for the disc like detector element
thickness is the module thickness
material is the (optional) Surface material associated to it
Definition at line 34 of file GenericDetectorElement.cpp.
View newest version in sPHENIX GitHub at line 34 of file GenericDetectorElement.cpp
References m_elementSurface, and testing::internal::move().
Member Function Documentation
void ActsExamples::Generic::GenericDetectorElement::assignIdentifier (const Identifier & identifier) inline
Set the identifier after construction (sometimes needed)
Definition at line 120 of file GenericDetectorElement.hpp.
View newest version in sPHENIX GitHub at line 120 of file GenericDetectorElement.hpp
References identifier().
const std::shared_ptr< const Acts::DigitizationModule > ActsExamples::Generic::GenericDetectorElement::digitizationModule () const inline override virtual
Retrieve the DigitizationModule.
Implements Acts::IdentifiedDetectorElement.
Definition at line 150 of file GenericDetectorElement.hpp.
View newest version in sPHENIX GitHub at line 150 of file GenericDetectorElement.hpp
References m_digitizationModule.
Identifier ActsExamples::Generic::GenericDetectorElement::identifier () const inline final virtual
Identifier.
Implements Acts::IdentifiedDetectorElement.
Definition at line 125 of file GenericDetectorElement.hpp.
View newest version in sPHENIX GitHub at line 125 of file GenericDetectorElement.hpp
References m_elementIdentifier.
Referenced by assignIdentifier(), and ActsExamples::Contextual::ExternallyAlignedDetectorElement::transform().
const Acts::Surface & ActsExamples::Generic::GenericDetectorElement::surface () const inline override virtual
Return surface associated with this detector element.
Implements Acts::DetectorElementBase.
Definition at line 137 of file GenericDetectorElement.hpp.
View newest version in sPHENIX GitHub at line 137 of file GenericDetectorElement.hpp
References m_elementSurface.
Acts::Surface & ActsExamples::Generic::GenericDetectorElement::surface () inline override virtual
Non-cost access to surface associated with this detector element.
Implements Acts::DetectorElementBase.
Definition at line 141 of file GenericDetectorElement.hpp.
View newest version in sPHENIX GitHub at line 141 of file GenericDetectorElement.hpp
References m_elementSurface.
double ActsExamples::Generic::GenericDetectorElement::thickness () const inline override virtual
The maximal thickness of the detector element wrt normal axis.
Implements Acts::DetectorElementBase.
Definition at line 145 of file GenericDetectorElement.hpp.
View newest version in sPHENIX GitHub at line 145 of file GenericDetectorElement.hpp
References m_elementThickness.
const Acts::Transform3 & ActsExamples::Generic::GenericDetectorElement::transform (const Acts::GeometryContext & gctx) const inline override virtual
Return local to global transform associated with this detector element
Parameters
gctx The current geometry context object, e.g. alignment
Note
this is called from the surface().transform(gctx) in the PROXY mode
Implements Acts::DetectorElementBase.
Definition at line 131 of file GenericDetectorElement.hpp.
View newest version in sPHENIX GitHub at line 131 of file GenericDetectorElement.hpp
References m_elementTransform.
Member Data Documentation
std::shared_ptr<const Acts::DigitizationModule> ActsExamples::Generic::GenericDetectorElement::m_digitizationModule private
Initial value:
=
      nullptr
The Digitization module.
Definition at line 116 of file GenericDetectorElement.hpp.
View newest version in sPHENIX GitHub at line 116 of file GenericDetectorElement.hpp
Referenced by digitizationModule().
std::shared_ptr<const Acts::DiscBounds> ActsExamples::Generic::GenericDetectorElement::m_elementDiscBounds = nullptr private
Definition at line 114 of file GenericDetectorElement.hpp.
View newest version in sPHENIX GitHub at line 114 of file GenericDetectorElement.hpp
Identifier ActsExamples::Generic::GenericDetectorElement::m_elementIdentifier private
the element representation identifier
Definition at line 105 of file GenericDetectorElement.hpp.
View newest version in sPHENIX GitHub at line 105 of file GenericDetectorElement.hpp
Referenced by identifier().
std::shared_ptr<const Acts::PlanarBounds> ActsExamples::Generic::GenericDetectorElement::m_elementPlanarBounds = nullptr private
store either
Definition at line 113 of file GenericDetectorElement.hpp.
View newest version in sPHENIX GitHub at line 113 of file GenericDetectorElement.hpp
std::shared_ptr<Acts::Surface> ActsExamples::Generic::GenericDetectorElement::m_elementSurface private
the surface represented by it
Definition at line 109 of file GenericDetectorElement.hpp.
View newest version in sPHENIX GitHub at line 109 of file GenericDetectorElement.hpp
Referenced by GenericDetectorElement(), and surface().
double ActsExamples::Generic::GenericDetectorElement::m_elementThickness private
the element thickness
Definition at line 111 of file GenericDetectorElement.hpp.
View newest version in sPHENIX GitHub at line 111 of file GenericDetectorElement.hpp
Referenced by thickness().
std::shared_ptr<const Acts::Transform3> ActsExamples::Generic::GenericDetectorElement::m_elementTransform private
the transform for positioning in 3D space
Definition at line 107 of file GenericDetectorElement.hpp.
View newest version in sPHENIX GitHub at line 107 of file GenericDetectorElement.hpp
Referenced by transform().
The documentation for this class was generated from the following files:
acts/blob/sPHENIX/Examples/Detectors/GenericDetector/include/ActsExamples/GenericDetector/GenericDetectorElement.hpp
acts/blob/sPHENIX/Examples/Detectors/GenericDetector/src/GenericDetectorElement.cpp