Analysis Software: PHHybridSeeding Class Reference
PHHybridSeeding Class Reference
#include <coresoftware/blob/master/offline/packages/trackreco/PHHybridSeeding.h>
Public Member Functions
PHHybridSeeding (const std::string &name="PHHybridSeeding", double max_sin_phi=1000., double fieldDir=1, double search_radius1=3., double search_angle1=M_PI/8., size_t min_track_size1=10, double search_radius2=6., double search_angle2=M_PI/8., size_t min_track_size2=5, size_t nthreads=1)
~PHHybridSeeding () override
void set_field_dir (const double rescale)
void setSearchRadius (double r1, double r2)
void setSearchAngle (double a1, double a2)
void setMinTrackSize (size_t n1, size_t n2)
void setNThreads (size_t n)
void setMinFitTrackSize (size_t s)
Public Member Functions inherited from PHTrackSeeding
PHTrackSeeding (const std::string &name="PHTrackSeeding")
~PHTrackSeeding () override
int InitRun (PHCompositeNode *topNode) override
int process_event (PHCompositeNode *topNode) override
int End (PHCompositeNode *topNode) override
Called at the end of all processing.
void set_track_map_name (const std::string &map_name)
void set_do_hit_association (bool do_assoc)
void SetUseTruthClusters (bool setit)
void SetIteration (int iter)
Public Member Functions inherited from SubsysReco
~SubsysReco () override
virtual int EndRun (const int)
Called at the end of each run.
virtual int Init (PHCompositeNode *)
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
void Print (const std::string &="ALL") const override
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Protected Member Functions
int Setup (PHCompositeNode *topNode) override
int Process (PHCompositeNode *topNode) override
int InitializeGeometry (PHCompositeNode *topNode)
int End () override
Called in SubsysReco::End.
Private Member Functions
void publishSeeds (std::vector< SvtxTrack_v3 > seeds)
Private Attributes
std::vector< double > _radii_all
fetch node pointers
std::vector< double > _vertex_ids
std::vector< double > _vertex_x
std::vector< double > _vertex_y
std::vector< double > _vertex_z
std::vector< double > _vertex_xerr
std::vector< double > _vertex_yerr
std::vector< double > _vertex_zerr
std::map< int, unsigned int > _layer_ilayer_map_all
std::map< int, unsigned int > _layer_ilayer_map
double _max_sin_phi
double _fieldDir
double _search_radius1
double _search_angle1
size_t _min_track_size1
double _search_radius2
double _search_angle2
size_t _min_track_size2
size_t _nthreads
size_t _min_fit_track_size = 5
std::shared_ptr< ALICEKF > fitter
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = std::numeric_limits<int>::max() - 10
}
Protected Attributes inherited from PHTrackSeeding
TrkrClusterContainer * _cluster_map = nullptr
TrkrClusterHitAssoc * _cluster_hit_map = nullptr
TrkrClusterIterationMapv1 * _iteration_map
int _n_iteration
bool do_hit_assoc = true
SvtxVertexMap * _vertex_map = nullptr
TrackSeedContainer * _track_map = nullptr
TrkrHitSetContainer * _hitsets = nullptr
std::string _track_map_name = "TpcTrackSeedContainer"
bool _use_truth_clusters = false
Detailed Description
Definition at line 40 of file PHHybridSeeding.h.
View newest version in sPHENIX GitHub at line 40 of file PHHybridSeeding.h
Constructor & Destructor Documentation
PHHybridSeeding::PHHybridSeeding (const std::string & name = "PHHybridSeeding", double max_sin_phi = 1000., double fieldDir = 1, double search_radius1 = 3., double search_angle1 = M_PI/8., size_t min_track_size1 = 10, double search_radius2 = 6., double search_angle2 = M_PI/8., size_t min_track_size2 = 5, size_t nthreads = 1)
Definition at line 75 of file PHHybridSeeding.cc.
View newest version in sPHENIX GitHub at line 75 of file PHHybridSeeding.cc
PHHybridSeeding::~PHHybridSeeding () inline override
Definition at line 56 of file PHHybridSeeding.h.
View newest version in sPHENIX GitHub at line 56 of file PHHybridSeeding.h
Member Function Documentation
int PHHybridSeeding::End () override protected virtual
Called in SubsysReco::End.
Implements PHTrackSeeding.
Definition at line 354 of file PHHybridSeeding.cc.
View newest version in sPHENIX GitHub at line 354 of file PHHybridSeeding.cc
References Fun4AllReturnCodes::EVENT_OK, and Fun4AllBase::Verbosity().
int PHHybridSeeding::InitializeGeometry (PHCompositeNode * topNode) protected
Definition at line 100 of file PHHybridSeeding.cc.
View newest version in sPHENIX GitHub at line 100 of file PHHybridSeeding.cc
References _layer_ilayer_map, _layer_ilayer_map_all, _radii_all, Fun4AllReturnCodes::EVENT_OK, PHG4TpcCylinderGeomContainer::get_begin_end(), PHG4CylinderGeom::get_layer(), PHG4TpcCylinderGeom::get_layer(), PHG4TpcCylinderGeom::get_radius(), PHG4CylinderGeom::get_radius(), PHG4TpcCylinderGeom::get_thickness(), PHG4CylinderGeom::get_thickness(), and findNode::getClass().
Referenced by Setup().
int PHHybridSeeding::Process (PHCompositeNode * topNode) override protected virtual
process event interface for trackers, called in process_event. implemented in derived classes
Implements PHTrackSeeding.
Definition at line 233 of file PHHybridSeeding.cc.
View newest version in sPHENIX GitHub at line 233 of file PHHybridSeeding.cc
References PHTrackSeeding::_cluster_map, PHTrackSeeding::_hitsets, _min_track_size1, _min_track_size2, _nthreads, _search_angle1, _search_angle2, _search_radius1, _search_radius2, _vertex_ids, PHTrackSeeding::_vertex_map, _vertex_x, _vertex_xerr, _vertex_y, _vertex_yerr, _vertex_z, _vertex_zerr, SvtxVertexMap::begin(), Acts::PhysicalConstants::c, SvtxVertexMap::end(), Fun4AllReturnCodes::EVENT_OK, fitter, SvtxVertex::get_error(), SvtxVertex::get_id(), SvtxVertex::get_x(), SvtxVertex::get_y(), SvtxVertex::get_z(), TrkrDefs::getLayer(), i, k, publishSeeds(), testSigmaEff::v, and Fun4AllBase::Verbosity().
void PHHybridSeeding::publishSeeds (std::vector< SvtxTrack_v3 > seeds) private
Definition at line 313 of file PHHybridSeeding.cc.
View newest version in sPHENIX GitHub at line 313 of file PHHybridSeeding.cc
References PHTrackSeeding::_track_map, i, and TrackSeedContainer::insert().
Referenced by Process().
void PHHybridSeeding::set_field_dir (const double rescale) inline
Definition at line 60 of file PHHybridSeeding.h.
View newest version in sPHENIX GitHub at line 60 of file PHHybridSeeding.h
References _fieldDir.
void PHHybridSeeding::setMinFitTrackSize (size_t s) inline
Definition at line 76 of file PHHybridSeeding.h.
View newest version in sPHENIX GitHub at line 76 of file PHHybridSeeding.h
References _min_fit_track_size, and physmon_simulation::s.
void PHHybridSeeding::setMinTrackSize (size_t n1, size_t n2) inline
Definition at line 74 of file PHHybridSeeding.h.
View newest version in sPHENIX GitHub at line 74 of file PHHybridSeeding.h
References _min_track_size1, and _min_track_size2.
void PHHybridSeeding::setNThreads (size_t n) inline
Definition at line 75 of file PHHybridSeeding.h.
View newest version in sPHENIX GitHub at line 75 of file PHHybridSeeding.h
References _nthreads, and n.
void PHHybridSeeding::setSearchAngle (double a1, double a2) inline
Definition at line 73 of file PHHybridSeeding.h.
View newest version in sPHENIX GitHub at line 73 of file PHHybridSeeding.h
References _search_angle1, _search_angle2, and KFPMath::a2.
void PHHybridSeeding::setSearchRadius (double r1, double r2) inline
Definition at line 72 of file PHHybridSeeding.h.
View newest version in sPHENIX GitHub at line 72 of file PHHybridSeeding.h
References _search_radius1, _search_radius2, r1, and r2.
int PHHybridSeeding::Setup (PHCompositeNode * topNode) override protected virtual
setup interface for trackers, called in InitRun, setup things like pointers to nodes. overrided in derived classes
Reimplemented from PHTrackSeeding.
Definition at line 321 of file PHHybridSeeding.cc.
View newest version in sPHENIX GitHub at line 321 of file PHHybridSeeding.cc
References PHTrackSeeding::_cluster_map, _fieldDir, _max_sin_phi, _min_fit_track_size, PHTrackSeeding::_vertex_map, Fun4AllReturnCodes::ABORTEVENT, Fun4AllReturnCodes::EVENT_OK, fitter, InitializeGeometry(), PHWHERE, PHTrackSeeding::Setup(), Acts::tGeometry, and Fun4AllBase::Verbosity().
Member Data Documentation
double PHHybridSeeding::_fieldDir private
Definition at line 106 of file PHHybridSeeding.h.
View newest version in sPHENIX GitHub at line 106 of file PHHybridSeeding.h
Referenced by set_field_dir(), and Setup().
std::map<int, unsigned int> PHHybridSeeding::_layer_ilayer_map private
Definition at line 101 of file PHHybridSeeding.h.
View newest version in sPHENIX GitHub at line 101 of file PHHybridSeeding.h
Referenced by InitializeGeometry().
std::map<int, unsigned int> PHHybridSeeding::_layer_ilayer_map_all private
Definition at line 100 of file PHHybridSeeding.h.
View newest version in sPHENIX GitHub at line 100 of file PHHybridSeeding.h
Referenced by InitializeGeometry().
double PHHybridSeeding::_max_sin_phi private
Definition at line 105 of file PHHybridSeeding.h.
View newest version in sPHENIX GitHub at line 105 of file PHHybridSeeding.h
Referenced by Setup().
size_t PHHybridSeeding::_min_fit_track_size = 5 private
Definition at line 114 of file PHHybridSeeding.h.
View newest version in sPHENIX GitHub at line 114 of file PHHybridSeeding.h
Referenced by setMinFitTrackSize(), and Setup().
size_t PHHybridSeeding::_min_track_size1 private
Definition at line 109 of file PHHybridSeeding.h.
View newest version in sPHENIX GitHub at line 109 of file PHHybridSeeding.h
Referenced by Process(), and setMinTrackSize().
size_t PHHybridSeeding::_min_track_size2 private
Definition at line 112 of file PHHybridSeeding.h.
View newest version in sPHENIX GitHub at line 112 of file PHHybridSeeding.h
Referenced by Process(), and setMinTrackSize().
size_t PHHybridSeeding::_nthreads private
Definition at line 113 of file PHHybridSeeding.h.
View newest version in sPHENIX GitHub at line 113 of file PHHybridSeeding.h
Referenced by Process(), and setNThreads().
std::vector<double> PHHybridSeeding::_radii_all private
fetch node pointers
Definition at line 90 of file PHHybridSeeding.h.
View newest version in sPHENIX GitHub at line 90 of file PHHybridSeeding.h
Referenced by InitializeGeometry().
double PHHybridSeeding::_search_angle1 private
Definition at line 108 of file PHHybridSeeding.h.
View newest version in sPHENIX GitHub at line 108 of file PHHybridSeeding.h
Referenced by Process(), and setSearchAngle().
double PHHybridSeeding::_search_angle2 private
Definition at line 111 of file PHHybridSeeding.h.
View newest version in sPHENIX GitHub at line 111 of file PHHybridSeeding.h
Referenced by Process(), and setSearchAngle().
double PHHybridSeeding::_search_radius1 private
Definition at line 107 of file PHHybridSeeding.h.
View newest version in sPHENIX GitHub at line 107 of file PHHybridSeeding.h
Referenced by Process(), and setSearchRadius().
double PHHybridSeeding::_search_radius2 private
Definition at line 110 of file PHHybridSeeding.h.
View newest version in sPHENIX GitHub at line 110 of file PHHybridSeeding.h
Referenced by Process(), and setSearchRadius().
std::vector<double> PHHybridSeeding::_vertex_ids private
Definition at line 92 of file PHHybridSeeding.h.
View newest version in sPHENIX GitHub at line 92 of file PHHybridSeeding.h
Referenced by Process().
std::vector<double> PHHybridSeeding::_vertex_x private
Definition at line 93 of file PHHybridSeeding.h.
View newest version in sPHENIX GitHub at line 93 of file PHHybridSeeding.h
Referenced by Process().
std::vector<double> PHHybridSeeding::_vertex_xerr private
Definition at line 96 of file PHHybridSeeding.h.
View newest version in sPHENIX GitHub at line 96 of file PHHybridSeeding.h
Referenced by Process().
std::vector<double> PHHybridSeeding::_vertex_y private
Definition at line 94 of file PHHybridSeeding.h.
View newest version in sPHENIX GitHub at line 94 of file PHHybridSeeding.h
Referenced by Process().
std::vector<double> PHHybridSeeding::_vertex_yerr private
Definition at line 97 of file PHHybridSeeding.h.
View newest version in sPHENIX GitHub at line 97 of file PHHybridSeeding.h
Referenced by Process().
std::vector<double> PHHybridSeeding::_vertex_z private
Definition at line 95 of file PHHybridSeeding.h.
View newest version in sPHENIX GitHub at line 95 of file PHHybridSeeding.h
Referenced by Process().
std::vector<double> PHHybridSeeding::_vertex_zerr private
Definition at line 98 of file PHHybridSeeding.h.
View newest version in sPHENIX GitHub at line 98 of file PHHybridSeeding.h
Referenced by Process().
std::shared_ptr<ALICEKF> PHHybridSeeding::fitter private
Definition at line 115 of file PHHybridSeeding.h.
View newest version in sPHENIX GitHub at line 115 of file PHHybridSeeding.h
Referenced by Process(), and Setup().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/trackreco/PHHybridSeeding.h
coresoftware/blob/master/offline/packages/trackreco/PHHybridSeeding.cc