Analysis Software: PHG4ParticleSvtxMap Class Reference
PHG4ParticleSvtxMap Class Reference
#include <coresoftware/blob/master/offline/packages/trackbase_historic/PHG4ParticleSvtxMap.h>
Public Types
typedef std::map< float,
std::set< unsigned int > > WeightedRecoTrackMap
Truth->reco map with structure <g4part id, std::map< weight, std::set<reco track id>>>
typedef std::map< int,
WeightedRecoTrackMap > Map
typedef std::map< int,
WeightedRecoTrackMap >
::const_iterator ConstIter
typedef std::map< int,
WeightedRecoTrackMap >
::iterator Iter
Public Member Functions
~PHG4ParticleSvtxMap () override
void identify (std::ostream &os=std::cout) const override
int isValid () const override
isValid returns non zero if object contains vailid data
PHObject * CloneMe () const override
Virtual copy constructor.
void Reset () override
Clear Event.
virtual bool empty () const
virtual std::size_t size () const
virtual std::size_t count (const int) const
virtual void clear ()
virtual bool processed () const
virtual void setProcessed (const bool)
virtual const
WeightedRecoTrackMap & get (const int) const
virtual WeightedRecoTrackMap & get (const int)
virtual WeightedRecoTrackMap insert (const int, const WeightedRecoTrackMap)
virtual std::size_t erase (const int)
virtual ConstIter begin () const
virtual ConstIter find (const int) const
virtual ConstIter end () const
virtual Iter begin ()
virtual Iter find (const int)
virtual Iter end ()
Public Member Functions inherited from PHObject
PHObject ()
ctor
~PHObject () override
dtor
virtual PHObject * clone () const final
PHObject * Clone (const char *newname="") const final
void Copy (TObject &object) const final
virtual int Integrate () const
virtual int Integrate (PHObject *)
virtual void CopyFrom (const PHObject *obj)
Protected Member Functions
PHG4ParticleSvtxMap ()
Private Member Functions
ClassDefOverride (PHG4ParticleSvtxMap, 1)
Detailed Description
Definition at line 10 of file PHG4ParticleSvtxMap.h.
View newest version in sPHENIX GitHub at line 10 of file PHG4ParticleSvtxMap.h
Member Typedef Documentation
typedef std::map<int, WeightedRecoTrackMap>::const_iterator PHG4ParticleSvtxMap::ConstIter
Definition at line 16 of file PHG4ParticleSvtxMap.h.
View newest version in sPHENIX GitHub at line 16 of file PHG4ParticleSvtxMap.h
typedef std::map<int, WeightedRecoTrackMap>::iterator PHG4ParticleSvtxMap::Iter
Definition at line 17 of file PHG4ParticleSvtxMap.h.
View newest version in sPHENIX GitHub at line 17 of file PHG4ParticleSvtxMap.h
typedef std::map<int, WeightedRecoTrackMap> PHG4ParticleSvtxMap::Map
Definition at line 15 of file PHG4ParticleSvtxMap.h.
View newest version in sPHENIX GitHub at line 15 of file PHG4ParticleSvtxMap.h
typedef std::map<float, std::set<unsigned int> > PHG4ParticleSvtxMap::WeightedRecoTrackMap
Truth->reco map with structure <g4part id, std::map< weight, std::set<reco track id>>>
Definition at line 14 of file PHG4ParticleSvtxMap.h.
View newest version in sPHENIX GitHub at line 14 of file PHG4ParticleSvtxMap.h
Constructor & Destructor Documentation
PHG4ParticleSvtxMap::~PHG4ParticleSvtxMap () inline override
Definition at line 19 of file PHG4ParticleSvtxMap.h.
View newest version in sPHENIX GitHub at line 19 of file PHG4ParticleSvtxMap.h
PHG4ParticleSvtxMap::PHG4ParticleSvtxMap () inline protected
Definition at line 52 of file PHG4ParticleSvtxMap.h.
View newest version in sPHENIX GitHub at line 52 of file PHG4ParticleSvtxMap.h
Member Function Documentation
PHG4ParticleSvtxMap::ConstIter PHG4ParticleSvtxMap::begin (void) const virtual
Reimplemented in PHG4ParticleSvtxMap_v1.
Definition at line 21 of file PHG4ParticleSvtxMap.cc.
View newest version in sPHENIX GitHub at line 21 of file PHG4ParticleSvtxMap.cc
References DummyPHG4ParticleSvtxMap.
PHG4ParticleSvtxMap::Iter PHG4ParticleSvtxMap::begin (void) virtual
Reimplemented in PHG4ParticleSvtxMap_v1.
Definition at line 37 of file PHG4ParticleSvtxMap.cc.
View newest version in sPHENIX GitHub at line 37 of file PHG4ParticleSvtxMap.cc
References DummyPHG4ParticleSvtxMap.
PHG4ParticleSvtxMap::ClassDefOverride (PHG4ParticleSvtxMap , 1) private
virtual void PHG4ParticleSvtxMap::clear () inline virtual
Reimplemented in PHG4ParticleSvtxMap_v1.
Definition at line 33 of file PHG4ParticleSvtxMap.h.
View newest version in sPHENIX GitHub at line 33 of file PHG4ParticleSvtxMap.h
PHObject* PHG4ParticleSvtxMap::CloneMe () const inline override virtual
Virtual copy constructor.
Reimplemented from PHObject.
Reimplemented in PHG4ParticleSvtxMap_v1.
Definition at line 27 of file PHG4ParticleSvtxMap.h.
View newest version in sPHENIX GitHub at line 27 of file PHG4ParticleSvtxMap.h
virtual std::size_t PHG4ParticleSvtxMap::count (const int) const inline virtual
Reimplemented in PHG4ParticleSvtxMap_v1.
Definition at line 32 of file PHG4ParticleSvtxMap.h.
View newest version in sPHENIX GitHub at line 32 of file PHG4ParticleSvtxMap.h
virtual bool PHG4ParticleSvtxMap::empty () const inline virtual
Reimplemented in PHG4ParticleSvtxMap_v1.
Definition at line 30 of file PHG4ParticleSvtxMap.h.
View newest version in sPHENIX GitHub at line 30 of file PHG4ParticleSvtxMap.h
PHG4ParticleSvtxMap::ConstIter PHG4ParticleSvtxMap::end (void) const virtual
Reimplemented in PHG4ParticleSvtxMap_v1.
Definition at line 31 of file PHG4ParticleSvtxMap.cc.
View newest version in sPHENIX GitHub at line 31 of file PHG4ParticleSvtxMap.cc
References DummyPHG4ParticleSvtxMap.
PHG4ParticleSvtxMap::Iter PHG4ParticleSvtxMap::end (void) virtual
Reimplemented in PHG4ParticleSvtxMap_v1.
Definition at line 47 of file PHG4ParticleSvtxMap.cc.
View newest version in sPHENIX GitHub at line 47 of file PHG4ParticleSvtxMap.cc
References DummyPHG4ParticleSvtxMap.
virtual std::size_t PHG4ParticleSvtxMap::erase (const int) inline virtual
Reimplemented in PHG4ParticleSvtxMap_v1.
Definition at line 41 of file PHG4ParticleSvtxMap.h.
View newest version in sPHENIX GitHub at line 41 of file PHG4ParticleSvtxMap.h
PHG4ParticleSvtxMap::ConstIter PHG4ParticleSvtxMap::find (const int) const virtual
Reimplemented in PHG4ParticleSvtxMap_v1.
Definition at line 26 of file PHG4ParticleSvtxMap.cc.
View newest version in sPHENIX GitHub at line 26 of file PHG4ParticleSvtxMap.cc
References DummyPHG4ParticleSvtxMap.
PHG4ParticleSvtxMap::Iter PHG4ParticleSvtxMap::find (const int) virtual
Reimplemented in PHG4ParticleSvtxMap_v1.
Definition at line 42 of file PHG4ParticleSvtxMap.cc.
View newest version in sPHENIX GitHub at line 42 of file PHG4ParticleSvtxMap.cc
References DummyPHG4ParticleSvtxMap.
const PHG4ParticleSvtxMap::WeightedRecoTrackMap & PHG4ParticleSvtxMap::get (const int) const virtual
Reimplemented in PHG4ParticleSvtxMap_v1.
Definition at line 6 of file PHG4ParticleSvtxMap.cc.
View newest version in sPHENIX GitHub at line 6 of file PHG4ParticleSvtxMap.cc
References emptyRecoMap.
Referenced by SvtxTrackEval::all_tracks_from(), SvtxTrackEval::best_track_from(), and PHG4ParticleSvtxMap_v1::get().
PHG4ParticleSvtxMap::WeightedRecoTrackMap & PHG4ParticleSvtxMap::get (const int) virtual
Reimplemented in PHG4ParticleSvtxMap_v1.
Definition at line 11 of file PHG4ParticleSvtxMap.cc.
View newest version in sPHENIX GitHub at line 11 of file PHG4ParticleSvtxMap.cc
References emptyRecoMap.
void PHG4ParticleSvtxMap::identify (std::ostream & os = std::cout) const inline override virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from PHObject.
Reimplemented in PHG4ParticleSvtxMap_v1.
Definition at line 21 of file PHG4ParticleSvtxMap.h.
View newest version in sPHENIX GitHub at line 21 of file PHG4ParticleSvtxMap.h
References os.
Referenced by SvtxTruthRecoTableEval::ResetEvent().
PHG4ParticleSvtxMap::WeightedRecoTrackMap PHG4ParticleSvtxMap::insert (const int , const WeightedRecoTrackMap) virtual
Reimplemented in PHG4ParticleSvtxMap_v1.
Definition at line 16 of file PHG4ParticleSvtxMap.cc.
View newest version in sPHENIX GitHub at line 16 of file PHG4ParticleSvtxMap.cc
References emptyRecoMap.
Referenced by SvtxTruthRecoTableEval::fillTruthMap(), and FillTruthRecoMatchMap::process_event().
int PHG4ParticleSvtxMap::isValid () const inline override virtual
isValid returns non zero if object contains vailid data
Reimplemented from PHObject.
Reimplemented in PHG4ParticleSvtxMap_v1.
Definition at line 26 of file PHG4ParticleSvtxMap.h.
View newest version in sPHENIX GitHub at line 26 of file PHG4ParticleSvtxMap.h
virtual bool PHG4ParticleSvtxMap::processed () const inline virtual
Reimplemented in PHG4ParticleSvtxMap_v1.
Definition at line 35 of file PHG4ParticleSvtxMap.h.
View newest version in sPHENIX GitHub at line 35 of file PHG4ParticleSvtxMap.h
Referenced by SvtxTrackEval::all_tracks_from(), and SvtxTrackEval::best_track_from().
void PHG4ParticleSvtxMap::Reset () inline override virtual
Clear Event.
Reimplemented from PHObject.
Reimplemented in PHG4ParticleSvtxMap_v1.
Definition at line 28 of file PHG4ParticleSvtxMap.h.
View newest version in sPHENIX GitHub at line 28 of file PHG4ParticleSvtxMap.h
virtual void PHG4ParticleSvtxMap::setProcessed (const bool) inline virtual
Reimplemented in PHG4ParticleSvtxMap_v1.
Definition at line 36 of file PHG4ParticleSvtxMap.h.
View newest version in sPHENIX GitHub at line 36 of file PHG4ParticleSvtxMap.h
Referenced by SvtxTruthRecoTableEval::fillTruthMap().
virtual std::size_t PHG4ParticleSvtxMap::size (void) const inline virtual
Reimplemented in PHG4ParticleSvtxMap_v1.
Definition at line 31 of file PHG4ParticleSvtxMap.h.
View newest version in sPHENIX GitHub at line 31 of file PHG4ParticleSvtxMap.h
Referenced by DumpPHG4ParticleSvtxMap::process_Node().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/trackbase_historic/PHG4ParticleSvtxMap.h
coresoftware/blob/master/offline/packages/trackbase_historic/PHG4ParticleSvtxMap.cc