Analysis Software: ActsExamples::VolumeAssociationTest Exception Reference
ActsExamples::VolumeAssociationTest Exception Reference final
#include <acts/blob/sPHENIX/Examples/Algorithms/Geometry/include/ActsExamples/Geometry/VolumeAssociationTest.hpp>
Classes
struct Config
Nested Configuration struct.
Public Member Functions
VolumeAssociationTest (const Config &cfg, Acts::Logging::Level level=Acts::Logging::INFO)
ProcessCode execute (const AlgorithmContext &ctx) const override
const Config & config () const
Const access to the config.
Public Member Functions inherited from ActsExamples::IAlgorithm
IAlgorithm (std::string name, Acts::Logging::Level level=Acts::Logging::INFO)
std::string name () const override
The algorithm name.
ProcessCode internalExecute (const AlgorithmContext &context) final
ProcessCode initialize () override
Initialize the algorithm.
ProcessCode finalize () override
Finalize the algorithm.
Private Attributes
Config m_cfg
The algorithm configuration.
Additional Inherited Members
Protected Member Functions inherited from ActsExamples::IAlgorithm
const Acts::Logger & logger () const
Detailed Description
This is a test algorithm that checks the unique volume identification and association for Detector objects
Definition at line 27 of file VolumeAssociationTest.hpp.
View newest version in sPHENIX GitHub at line 27 of file VolumeAssociationTest.hpp
Constructor & Destructor Documentation
ActsExamples::VolumeAssociationTest::VolumeAssociationTest (const Config & cfg, Acts::Logging::Level level = Acts::Logging::INFO)
Construct the volume association test algorithm
Parameters
cfg is the algorithm configuration
level is the logging level
Definition at line 20 of file VolumeAssociationTest.cpp.
View newest version in sPHENIX GitHub at line 20 of file VolumeAssociationTest.cpp
References ActsExamples::VolumeAssociationTest::Config::detector, m_cfg, ActsExamples::VolumeAssociationTest::Config::randomNumbers, and ActsExamples::VolumeAssociationTest::Config::randomRange.
Member Function Documentation
const Config& ActsExamples::VolumeAssociationTest::config () const inline
Const access to the config.
Definition at line 57 of file VolumeAssociationTest.hpp.
View newest version in sPHENIX GitHub at line 57 of file VolumeAssociationTest.hpp
References m_cfg.
ActsExamples::ProcessCode ActsExamples::VolumeAssociationTest::execute (const AlgorithmContext & ctx) const override virtual
Run the random point association test
Parameters
ctx is the algorithm context with event information
Returns
a process code indication success or failure
Implements ActsExamples::IAlgorithm.
Definition at line 35 of file VolumeAssociationTest.cpp.
View newest version in sPHENIX GitHub at line 35 of file VolumeAssociationTest.cpp
References ACTS_ERROR, ActsExamples::AlgorithmContext::geoContext, it, m_cfg(), ActsTests::PropagationDatasets::phi, Acts::Test::phiDist(), Acts::Test::pos, physmon_track_finding_ttbar::r, conftest::rng(), SUCCESS, physmon_ckf_tracking::u, and physmon_track_finding_ttbar::z.
Member Data Documentation
Config ActsExamples::VolumeAssociationTest::m_cfg private
The algorithm configuration.
Definition at line 61 of file VolumeAssociationTest.hpp.
View newest version in sPHENIX GitHub at line 61 of file VolumeAssociationTest.hpp
Referenced by config(), and VolumeAssociationTest().
The documentation for this exception was generated from the following files:
acts/blob/sPHENIX/Examples/Algorithms/Geometry/include/ActsExamples/Geometry/VolumeAssociationTest.hpp
acts/blob/sPHENIX/Examples/Algorithms/Geometry/src/VolumeAssociationTest.cpp