Analysis Software: TpcRawWriter Class Reference
TpcRawWriter Class Reference
#include <coresoftware/blob/master/offline/packages/tpc/TpcRawWriter.h>
Public Member Functions
TpcRawWriter (const std::string &name="TpcRawWriter")
~TpcRawWriter () override=default
int InitRun (PHCompositeNode *topNode) override
int process_event (PHCompositeNode *topNode) override
int End (PHCompositeNode *topNode) override
Called at the end of all processing.
void set_sector_fiducial_cut (const double cut)
void set_do_hit_association (bool do_assoc)
void set_do_wedge_emulation (bool do_wedge)
void set_do_sequential (bool do_seq)
void set_max_cluster_half_size_phi (unsigned short size)
void set_max_cluster_half_size_z (unsigned short size)
void set_drift_velocity_scale (double value)
Public Member Functions inherited from SubsysReco
~SubsysReco () override
virtual int EndRun (const int)
Called at the end of each run.
virtual int Init (PHCompositeNode *)
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
void Print (const std::string &="ALL") const override
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Private Attributes
TrkrHitSetContainer * m_hits = nullptr
RawHitSetContainerv1 * m_rawhits = nullptr
TrkrClusterContainer * m_clusterlist = nullptr
TrkrClusterHitAssoc * m_clusterhitassoc = nullptr
ActsGeometry * m_tGeometry = nullptr
bool do_hit_assoc = true
bool do_wedge_emulation = true
bool do_sequential = false
double pedestal = 74.4
double SectorFiducialCut = 0.5
unsigned short MaxClusterHalfSizePhi = 3
unsigned short MaxClusterHalfSizeZ = 5
double m_drift_velocity_scale = 1.0
drift velocity scale factor
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = std::numeric_limits<int>::max() - 10
}
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Detailed Description
Definition at line 27 of file TpcRawWriter.h.
View newest version in sPHENIX GitHub at line 27 of file TpcRawWriter.h
Constructor & Destructor Documentation
TpcRawWriter::TpcRawWriter (const std::string & name = "TpcRawWriter")
Definition at line 58 of file TpcRawWriter.cc.
View newest version in sPHENIX GitHub at line 58 of file TpcRawWriter.cc
References PHWHERE.
TpcRawWriter::~TpcRawWriter () override default
Member Function Documentation
int TpcRawWriter::End (PHCompositeNode *) override virtual
Called at the end of all processing.
Reimplemented from SubsysReco.
Definition at line 589 of file TpcRawWriter.cc.
View newest version in sPHENIX GitHub at line 589 of file TpcRawWriter.cc
References Fun4AllReturnCodes::EVENT_OK.
int TpcRawWriter::InitRun (PHCompositeNode *) override virtual
Called for first event when run number is known. Typically this is where you may want to fetch data from database, because you know the run number.
Reimplemented from SubsysReco.
Definition at line 63 of file TpcRawWriter.cc.
View newest version in sPHENIX GitHub at line 63 of file TpcRawWriter.cc
References Fun4AllReturnCodes::ABORTRUN, PHCompositeNode::addNode(), Fun4AllReturnCodes::EVENT_OK, PHNodeIterator::findFirst(), m_rawhits, and PHWHERE.
int TpcRawWriter::process_event (PHCompositeNode *) override virtual
Called for each event. This is where you do the real work.
Reimplemented from SubsysReco.
Definition at line 133 of file TpcRawWriter.cc.
View newest version in sPHENIX GitHub at line 133 of file TpcRawWriter.cc
References Fun4AllReturnCodes::ABORTRUN, RawHitSetv1::addHit(), RawHitSet::addHit(), test_fpe::count, Fun4AllReturnCodes::EVENT_OK, PHNodeIterator::findFirst(), RawHitSetContainerv1::findHitSet(), RawHitSetContainerv1::findOrAddHitSet(), PHG4TpcCylinderGeom::get_phibins(), PHG4TpcCylinderGeom::get_zbins(), MvtxDefs::getCol(), InttDefs::getCol(), TrkrHitSet::getHits(), TrkrHitSetContainer::getHitSets(), TrkrDefs::getLayer(), PHG4TpcCylinderGeomContainer::GetLayerCellGeom(), TpcDefs::getPad(), MvtxDefs::getRow(), InttDefs::getRow(), TpcDefs::getSectorId(), MicromegasDefs::getStrip(), TpcDefs::getTBin(), TrkrDefs::inttId, it, layer, m_clusterhitassoc, m_clusterlist, m_hits, m_rawhits, m_tGeometry, RawHitSetv1::m_tpchits, TrkrDefs::micromegasId, TrkrDefs::mvtxId, nphi, nz, pedestal, PHWHERE, RawHitv1::setAdc(), RawHitv1::setPhiBin(), RawHitv1::setTBin(), RawHitSetv1::setTpcPhiBins(), and TrkrDefs::tpcId.
void TpcRawWriter::set_do_hit_association (bool do_assoc) inline
Definition at line 38 of file TpcRawWriter.h.
View newest version in sPHENIX GitHub at line 38 of file TpcRawWriter.h
References do_hit_assoc.
void TpcRawWriter::set_do_sequential (bool do_seq) inline
Definition at line 40 of file TpcRawWriter.h.
View newest version in sPHENIX GitHub at line 40 of file TpcRawWriter.h
References do_sequential.
void TpcRawWriter::set_do_wedge_emulation (bool do_wedge) inline
Definition at line 39 of file TpcRawWriter.h.
View newest version in sPHENIX GitHub at line 39 of file TpcRawWriter.h
References do_wedge_emulation.
void TpcRawWriter::set_drift_velocity_scale (double value) inline
Definition at line 43 of file TpcRawWriter.h.
View newest version in sPHENIX GitHub at line 43 of file TpcRawWriter.h
References m_drift_velocity_scale, and value.
void TpcRawWriter::set_max_cluster_half_size_phi (unsigned short size) inline
Definition at line 41 of file TpcRawWriter.h.
View newest version in sPHENIX GitHub at line 41 of file TpcRawWriter.h
References MaxClusterHalfSizePhi, and size.
void TpcRawWriter::set_max_cluster_half_size_z (unsigned short size) inline
Definition at line 42 of file TpcRawWriter.h.
View newest version in sPHENIX GitHub at line 42 of file TpcRawWriter.h
References MaxClusterHalfSizeZ, and size.
void TpcRawWriter::set_sector_fiducial_cut (const double cut) inline
Definition at line 37 of file TpcRawWriter.h.
View newest version in sPHENIX GitHub at line 37 of file TpcRawWriter.h
References SectorFiducialCut.
Member Data Documentation
bool TpcRawWriter::do_hit_assoc = true private
Definition at line 53 of file TpcRawWriter.h.
View newest version in sPHENIX GitHub at line 53 of file TpcRawWriter.h
Referenced by set_do_hit_association().
bool TpcRawWriter::do_sequential = false private
Definition at line 55 of file TpcRawWriter.h.
View newest version in sPHENIX GitHub at line 55 of file TpcRawWriter.h
Referenced by set_do_sequential().
bool TpcRawWriter::do_wedge_emulation = true private
Definition at line 54 of file TpcRawWriter.h.
View newest version in sPHENIX GitHub at line 54 of file TpcRawWriter.h
Referenced by set_do_wedge_emulation().
TrkrClusterHitAssoc* TpcRawWriter::m_clusterhitassoc = nullptr private
Definition at line 50 of file TpcRawWriter.h.
View newest version in sPHENIX GitHub at line 50 of file TpcRawWriter.h
Referenced by process_event().
TrkrClusterContainer* TpcRawWriter::m_clusterlist = nullptr private
Definition at line 49 of file TpcRawWriter.h.
View newest version in sPHENIX GitHub at line 49 of file TpcRawWriter.h
Referenced by process_event().
double TpcRawWriter::m_drift_velocity_scale = 1.0 private
drift velocity scale factor
Definition at line 63 of file TpcRawWriter.h.
View newest version in sPHENIX GitHub at line 63 of file TpcRawWriter.h
Referenced by set_drift_velocity_scale().
TrkrHitSetContainer* TpcRawWriter::m_hits = nullptr private
Definition at line 47 of file TpcRawWriter.h.
View newest version in sPHENIX GitHub at line 47 of file TpcRawWriter.h
Referenced by process_event().
RawHitSetContainerv1* TpcRawWriter::m_rawhits = nullptr private
Definition at line 48 of file TpcRawWriter.h.
View newest version in sPHENIX GitHub at line 48 of file TpcRawWriter.h
Referenced by InitRun(), and process_event().
ActsGeometry* TpcRawWriter::m_tGeometry = nullptr private
Definition at line 52 of file TpcRawWriter.h.
View newest version in sPHENIX GitHub at line 52 of file TpcRawWriter.h
Referenced by process_event().
unsigned short TpcRawWriter::MaxClusterHalfSizePhi = 3 private
Definition at line 58 of file TpcRawWriter.h.
View newest version in sPHENIX GitHub at line 58 of file TpcRawWriter.h
Referenced by set_max_cluster_half_size_phi().
unsigned short TpcRawWriter::MaxClusterHalfSizeZ = 5 private
Definition at line 59 of file TpcRawWriter.h.
View newest version in sPHENIX GitHub at line 59 of file TpcRawWriter.h
Referenced by set_max_cluster_half_size_z().
double TpcRawWriter::pedestal = 74.4 private
Definition at line 56 of file TpcRawWriter.h.
View newest version in sPHENIX GitHub at line 56 of file TpcRawWriter.h
Referenced by process_event().
double TpcRawWriter::SectorFiducialCut = 0.5 private
Definition at line 57 of file TpcRawWriter.h.
View newest version in sPHENIX GitHub at line 57 of file TpcRawWriter.h
Referenced by set_sector_fiducial_cut().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/tpc/TpcRawWriter.h
coresoftware/blob/master/offline/packages/tpc/TpcRawWriter.cc