Analysis Software: Emcal_Tower_Masking Class Reference
Emcal_Tower_Masking Class Reference
#include <analysis/blob/master/EMCal-commissioning/emcal_tower_masking/src/Emcal_Tower_Masking.h>
Public Member Functions
Emcal_Tower_Masking (const std::string &name="Emcal_Tower_Masking")
~Emcal_Tower_Masking () override
int Init (PHCompositeNode *topNode) override
int InitRun (PHCompositeNode *topNode) override
int process_event (PHCompositeNode *topNode) override
int ResetEvent (PHCompositeNode *topNode) override
Clean up after each event.
int EndRun (const int runnumber) override
Called at the end of each run.
int End (PHCompositeNode *topNode) override
Called at the end of all processing.
int Reset (PHCompositeNode *) override
Reset.
void Print (const std::string &what="ALL") const override
void CreateNodeTree (PHCompositeNode *topNode)
void addhottower (int etabin, int phibin)
void addpacketmask (int packetnum)
Public Member Functions inherited from SubsysReco
~SubsysReco () override
void Print (const std::string &="ALL") const override
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Private Attributes
std::vector< unsigned int > etamasklist
std::vector< unsigned int > phimasklist
std::vector< unsigned int > packetmasklist
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = std::numeric_limits<int>::max() - 10
}
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Detailed Description
Definition at line 12 of file Emcal_Tower_Masking.h.
View newest version in sPHENIX GitHub at line 12 of file Emcal_Tower_Masking.h
Constructor & Destructor Documentation
Emcal_Tower_Masking::Emcal_Tower_Masking (const std::string & name = "Emcal_Tower_Masking")
Definition at line 34 of file Emcal_Tower_Masking.cc.
View newest version in sPHENIX GitHub at line 34 of file Emcal_Tower_Masking.cc
Emcal_Tower_Masking::~Emcal_Tower_Masking () override
Definition at line 40 of file Emcal_Tower_Masking.cc.
View newest version in sPHENIX GitHub at line 40 of file Emcal_Tower_Masking.cc
Member Function Documentation
void Emcal_Tower_Masking::addhottower (int etabin, int phibin) inline
Definition at line 30 of file Emcal_Tower_Masking.h.
View newest version in sPHENIX GitHub at line 30 of file Emcal_Tower_Masking.h
References etamasklist, and phimasklist.
void Emcal_Tower_Masking::addpacketmask (int packetnum) inline
Definition at line 35 of file Emcal_Tower_Masking.h.
View newest version in sPHENIX GitHub at line 35 of file Emcal_Tower_Masking.h
References packetmasklist.
void Emcal_Tower_Masking::CreateNodeTree (PHCompositeNode * topNode)
Definition at line 178 of file Emcal_Tower_Masking.cc.
View newest version in sPHENIX GitHub at line 178 of file Emcal_Tower_Masking.cc
References PHCompositeNode::addNode(), and PHNodeIterator::findFirst().
Referenced by InitRun().
int Emcal_Tower_Masking::End (PHCompositeNode *) override virtual
Called at the end of all processing.
Reimplemented from SubsysReco.
Definition at line 161 of file Emcal_Tower_Masking.cc.
View newest version in sPHENIX GitHub at line 161 of file Emcal_Tower_Masking.cc
References Fun4AllReturnCodes::EVENT_OK.
int Emcal_Tower_Masking::EndRun (const int) override virtual
Called at the end of each run.
Reimplemented from SubsysReco.
Definition at line 155 of file Emcal_Tower_Masking.cc.
View newest version in sPHENIX GitHub at line 155 of file Emcal_Tower_Masking.cc
References Fun4AllReturnCodes::EVENT_OK.
int Emcal_Tower_Masking::Init (PHCompositeNode *) override virtual
Called during initialization. Typically this is where you can book histograms, and e.g. register them to Fun4AllServer (so they can be output to file using Fun4AllServer::dumpHistos() method).
Reimplemented from SubsysReco.
Definition at line 45 of file Emcal_Tower_Masking.cc.
View newest version in sPHENIX GitHub at line 45 of file Emcal_Tower_Masking.cc
References Fun4AllReturnCodes::EVENT_OK.
int Emcal_Tower_Masking::InitRun (PHCompositeNode *) override virtual
Called for first event when run number is known. Typically this is where you may want to fetch data from database, because you know the run number.
Reimplemented from SubsysReco.
Definition at line 52 of file Emcal_Tower_Masking.cc.
View newest version in sPHENIX GitHub at line 52 of file Emcal_Tower_Masking.cc
References CreateNodeTree(), Fun4AllReturnCodes::EVENT_OK, and PHCompositeNode::print().
void Emcal_Tower_Masking::Print (const std::string & what = "ALL") const override virtual
Print out some info about this module.
Parameters
what can be used to specify what to print exactly.
Reimplemented from Fun4AllBase.
Definition at line 173 of file Emcal_Tower_Masking.cc.
View newest version in sPHENIX GitHub at line 173 of file Emcal_Tower_Masking.cc
int Emcal_Tower_Masking::process_event (PHCompositeNode *) override virtual
Called for each event. This is where you do the real work.
Reimplemented from SubsysReco.
Definition at line 60 of file Emcal_Tower_Masking.cc.
View newest version in sPHENIX GitHub at line 60 of file Emcal_Tower_Masking.cc
References channel(), TowerInfoContainer::encode_key(), etamasklist, Fun4AllReturnCodes::EVENT_OK, TowerInfo::get_energy(), TowerInfo::get_time(), TowerInfoContainer::get_tower_at_channel(), TowerInfoContainer::getTowerEtaBin(), TowerInfoContainer::getTowerPhiBin(), i, GlobalVertexMap::insert(), j, packetmasklist, phimasklist, TowerInfo::set_energy(), TowerInfo::set_time(), GlobalVertexMap::size(), and TowerInfoContainer::size().
int Emcal_Tower_Masking::Reset (PHCompositeNode *) override virtual
Reset.
Reimplemented from SubsysReco.
Definition at line 167 of file Emcal_Tower_Masking.cc.
View newest version in sPHENIX GitHub at line 167 of file Emcal_Tower_Masking.cc
References Fun4AllReturnCodes::EVENT_OK.
int Emcal_Tower_Masking::ResetEvent (PHCompositeNode *) override virtual
Clean up after each event.
Reimplemented from SubsysReco.
Definition at line 148 of file Emcal_Tower_Masking.cc.
View newest version in sPHENIX GitHub at line 148 of file Emcal_Tower_Masking.cc
References Fun4AllReturnCodes::EVENT_OK.
Member Data Documentation
std::vector<unsigned int> Emcal_Tower_Masking::etamasklist private
Definition at line 41 of file Emcal_Tower_Masking.h.
View newest version in sPHENIX GitHub at line 41 of file Emcal_Tower_Masking.h
Referenced by addhottower(), and process_event().
std::vector<unsigned int> Emcal_Tower_Masking::packetmasklist private
Definition at line 43 of file Emcal_Tower_Masking.h.
View newest version in sPHENIX GitHub at line 43 of file Emcal_Tower_Masking.h
Referenced by addpacketmask(), and process_event().
std::vector<unsigned int> Emcal_Tower_Masking::phimasklist private
Definition at line 42 of file Emcal_Tower_Masking.h.
View newest version in sPHENIX GitHub at line 42 of file Emcal_Tower_Masking.h
Referenced by addhottower(), and process_event().
The documentation for this class was generated from the following files:
analysis/blob/master/EMCal-commissioning/emcal_tower_masking/src/Emcal_Tower_Masking.h
analysis/blob/master/EMCal-commissioning/emcal_tower_masking/src/Emcal_Tower_Masking.cc