Analysis Software: ActsExamples::AmbiguityResolutionMLAlgorithm Exception Reference
ActsExamples::AmbiguityResolutionMLAlgorithm Exception Reference final
#include <acts/blob/sPHENIX/Examples/Algorithms/TrackFindingML/include/ActsExamples/TrackFindingML/AmbiguityResolutionMLAlgorithm.hpp>
Classes
struct Config
Public Member Functions
AmbiguityResolutionMLAlgorithm (Config cfg, Acts::Logging::Level lvl)
ProcessCode execute (const AlgorithmContext &ctx) const final
const Config & config () const
Const access to the config.
Public Member Functions inherited from ActsExamples::AmbiguityResolutionML
AmbiguityResolutionML (std::string name, Acts::Logging::Level lvl)
Public Member Functions inherited from ActsExamples::IAlgorithm
IAlgorithm (std::string name, Acts::Logging::Level level=Acts::Logging::INFO)
std::string name () const override
The algorithm name.
ProcessCode internalExecute (const AlgorithmContext &context) final
ProcessCode initialize () override
Initialize the algorithm.
ProcessCode finalize () override
Finalize the algorithm.
Private Attributes
Config m_cfg
Acts::AmbiguityTrackClassifier m_duplicateClassifier
ReadDataHandle
< ConstTrackContainer > m_inputTracks {this, "InputTracks"}
WriteDataHandle
< ConstTrackContainer > m_outputTracks {this, "OutputTracks"}
Additional Inherited Members
Protected Member Functions inherited from ActsExamples::AmbiguityResolutionML
std::multimap< int, std::pair
< int, std::vector< int > > > mapTrackHits (const ConstTrackContainer &tracks, int nMeasurementsMin) const
ConstTrackContainer prepareOutputTrack (const ConstTrackContainer &tracks, std::vector< int > &goodTracks) const
Detailed Description
Evicts tracks that seem to be duplicated and fake.
The implementation works as follows: 1) Cluster together nearby tracks using shared hits 2) For each track use a neural network to compute a score 3) In each cluster keep the track with the highest score
Definition at line 26 of file AmbiguityResolutionMLAlgorithm.hpp.
View newest version in sPHENIX GitHub at line 26 of file AmbiguityResolutionMLAlgorithm.hpp
Constructor & Destructor Documentation
ActsExamples::AmbiguityResolutionMLAlgorithm::AmbiguityResolutionMLAlgorithm (Config cfg, Acts::Logging::Level lvl)
Construct the ambiguity resolution algorithm.
Parameters
cfg is the algorithm configuration
lvl is the logging level
Definition at line 16 of file AmbiguityResolutionMLAlgorithm.cpp.
View newest version in sPHENIX GitHub at line 16 of file AmbiguityResolutionMLAlgorithm.cpp
References ActsExamples::WriteDataHandle< T >::initialize(), ActsExamples::ReadDataHandle< T >::initialize(), ActsExamples::AmbiguityResolutionMLAlgorithm::Config::inputTracks, m_cfg, m_inputTracks, m_outputTracks, and ActsExamples::AmbiguityResolutionMLAlgorithm::Config::outputTracks.
Member Function Documentation
const Config& ActsExamples::AmbiguityResolutionMLAlgorithm::config () const inline
Const access to the config.
Definition at line 52 of file AmbiguityResolutionMLAlgorithm.hpp.
View newest version in sPHENIX GitHub at line 52 of file AmbiguityResolutionMLAlgorithm.hpp
References m_cfg.
ActsExamples::ProcessCode ActsExamples::AmbiguityResolutionMLAlgorithm::execute (const AlgorithmContext & ctx) const final virtual
Run the ambiguity resolution algorithm.
Parameters
cxt is the algorithm context with event information
Returns
a process code indication success or failure
Implements ActsExamples::IAlgorithm.
Definition at line 33 of file AmbiguityResolutionMLAlgorithm.cpp.
View newest version in sPHENIX GitHub at line 33 of file AmbiguityResolutionMLAlgorithm.cpp
References Acts::detail::clusterDuplicateTracks(), m_cfg(), testing::internal::move(), truth_tracking_gsf_refitting::outputTracks, SUCCESS, and tracks().
Member Data Documentation
Config ActsExamples::AmbiguityResolutionMLAlgorithm::m_cfg private
Definition at line 55 of file AmbiguityResolutionMLAlgorithm.hpp.
View newest version in sPHENIX GitHub at line 55 of file AmbiguityResolutionMLAlgorithm.hpp
Referenced by AmbiguityResolutionMLAlgorithm(), and config().
Acts::AmbiguityTrackClassifier ActsExamples::AmbiguityResolutionMLAlgorithm::m_duplicateClassifier private
Definition at line 57 of file AmbiguityResolutionMLAlgorithm.hpp.
View newest version in sPHENIX GitHub at line 57 of file AmbiguityResolutionMLAlgorithm.hpp
ReadDataHandle<ConstTrackContainer> ActsExamples::AmbiguityResolutionMLAlgorithm::m_inputTracks {this, "InputTracks"} private
Definition at line 58 of file AmbiguityResolutionMLAlgorithm.hpp.
View newest version in sPHENIX GitHub at line 58 of file AmbiguityResolutionMLAlgorithm.hpp
Referenced by AmbiguityResolutionMLAlgorithm().
WriteDataHandle<ConstTrackContainer> ActsExamples::AmbiguityResolutionMLAlgorithm::m_outputTracks {this, "OutputTracks"} private
Definition at line 59 of file AmbiguityResolutionMLAlgorithm.hpp.
View newest version in sPHENIX GitHub at line 59 of file AmbiguityResolutionMLAlgorithm.hpp
Referenced by AmbiguityResolutionMLAlgorithm().
The documentation for this exception was generated from the following files:
acts/blob/sPHENIX/Examples/Algorithms/TrackFindingML/include/ActsExamples/TrackFindingML/AmbiguityResolutionMLAlgorithm.hpp
acts/blob/sPHENIX/Examples/Algorithms/TrackFindingML/src/AmbiguityResolutionMLAlgorithm.cpp