Analysis Software: Acts::MultiEigenStepperLoop< extensionlist_t, component_reducer_t, auctioneer_t >::ComponentProxy Struct Reference
Acts::MultiEigenStepperLoop< extensionlist_t, component_reducer_t, auctioneer_t >::ComponentProxy Struct Reference
#include <acts/blob/sPHENIX/Core/include/Acts/Propagator/MultiEigenStepperLoop.hpp>
Public Types
using Base = ComponentProxyBase< typename State::Component >
Public Member Functions
ComponentProxy (typename State::Component &c, const State &s)
auto & status ()
auto & weight ()
auto & pathAccumulated ()
auto & pars ()
auto & derivative ()
auto & jacTransport ()
auto & cov ()
auto & jacobian ()
auto & jacToGlobal ()
template<typename propagator_state_t >
auto singleState (propagator_state_t &state)
Result< typename
SingleStepper::BoundState > boundState (const Surface &surface, bool transportCov, const FreeToBoundCorrection &freeToBoundCorrection)
void update (const FreeVector &freeParams, const BoundVector &boundParams, const Covariance &covariance, const Surface &surface)
Public Member Functions inherited from Acts::MultiEigenStepperLoop< extensionlist_t, component_reducer_t, auctioneer_t >::ComponentProxyBase< State::Component >
ComponentProxyBase (State::Component &c)
auto status () const
auto weight () const
auto pathAccumulated () const
const auto & pars () const
const auto & derivative () const
const auto & jacTransport () const
const auto & cov () const
const auto & jacobian () const
const auto & jacToGlobal () const
auto singleState (const propagator_state_t &state) const
const auto & singleStepper (const MultiEigenStepperLoop &stepper) const
Public Attributes
const State & all_state
Public Attributes inherited from Acts::MultiEigenStepperLoop< extensionlist_t, component_reducer_t, auctioneer_t >::ComponentProxyBase< State::Component >
State::Component & cmp
Detailed Description
template<typename extensionlist_t = StepperExtensionList<DefaultExtension>, typename component_reducer_t = WeightedComponentReducerLoop, typename auctioneer_t = detail::VoidAuctioneer>
struct Acts::MultiEigenStepperLoop< extensionlist_t, component_reducer_t, auctioneer_t >::ComponentProxy
A proxy struct which allows access to a single component of the multi-component state. It has the semantics of a mutable reference, i.e. it requires a mutable reference of the single-component state it represents
Definition at line 425 of file MultiEigenStepperLoop.hpp.
View newest version in sPHENIX GitHub at line 425 of file MultiEigenStepperLoop.hpp
Member Typedef Documentation
template<typename extensionlist_t = StepperExtensionList<DefaultExtension>, typename component_reducer_t = WeightedComponentReducerLoop, typename auctioneer_t = detail::VoidAuctioneer> using Acts::MultiEigenStepperLoop< extensionlist_t, component_reducer_t, auctioneer_t >::ComponentProxy::Base = ComponentProxyBase<typename State::Component>
Definition at line 426 of file MultiEigenStepperLoop.hpp.
View newest version in sPHENIX GitHub at line 426 of file MultiEigenStepperLoop.hpp
Constructor & Destructor Documentation
template<typename extensionlist_t = StepperExtensionList<DefaultExtension>, typename component_reducer_t = WeightedComponentReducerLoop, typename auctioneer_t = detail::VoidAuctioneer> Acts::MultiEigenStepperLoop< extensionlist_t, component_reducer_t, auctioneer_t >::ComponentProxy::ComponentProxy (typename State::Component & c, const State & s) inline
Definition at line 445 of file MultiEigenStepperLoop.hpp.
View newest version in sPHENIX GitHub at line 445 of file MultiEigenStepperLoop.hpp
Member Function Documentation
template<typename extensionlist_t = StepperExtensionList<DefaultExtension>, typename component_reducer_t = WeightedComponentReducerLoop, typename auctioneer_t = detail::VoidAuctioneer> Result<typename SingleStepper::BoundState> Acts::MultiEigenStepperLoop< extensionlist_t, component_reducer_t, auctioneer_t >::ComponentProxy::boundState (const Surface & surface, bool transportCov, const FreeToBoundCorrection & freeToBoundCorrection) inline
Definition at line 471 of file MultiEigenStepperLoop.hpp.
View newest version in sPHENIX GitHub at line 471 of file MultiEigenStepperLoop.hpp
References Acts::detail::boundState(), root_event_diff_np::cmp(), Acts::Test::cov, and pars.
template<typename extensionlist_t = StepperExtensionList<DefaultExtension>, typename component_reducer_t = WeightedComponentReducerLoop, typename auctioneer_t = detail::VoidAuctioneer> auto& Acts::MultiEigenStepperLoop< extensionlist_t, component_reducer_t, auctioneer_t >::ComponentProxy::cov () inline
Definition at line 456 of file MultiEigenStepperLoop.hpp.
View newest version in sPHENIX GitHub at line 456 of file MultiEigenStepperLoop.hpp
References root_event_diff_np::cmp().
template<typename extensionlist_t = StepperExtensionList<DefaultExtension>, typename component_reducer_t = WeightedComponentReducerLoop, typename auctioneer_t = detail::VoidAuctioneer> auto& Acts::MultiEigenStepperLoop< extensionlist_t, component_reducer_t, auctioneer_t >::ComponentProxy::derivative () inline
Definition at line 454 of file MultiEigenStepperLoop.hpp.
View newest version in sPHENIX GitHub at line 454 of file MultiEigenStepperLoop.hpp
References root_event_diff_np::cmp().
template<typename extensionlist_t = StepperExtensionList<DefaultExtension>, typename component_reducer_t = WeightedComponentReducerLoop, typename auctioneer_t = detail::VoidAuctioneer> auto& Acts::MultiEigenStepperLoop< extensionlist_t, component_reducer_t, auctioneer_t >::ComponentProxy::jacobian () inline
Definition at line 457 of file MultiEigenStepperLoop.hpp.
View newest version in sPHENIX GitHub at line 457 of file MultiEigenStepperLoop.hpp
References root_event_diff_np::cmp().
template<typename extensionlist_t = StepperExtensionList<DefaultExtension>, typename component_reducer_t = WeightedComponentReducerLoop, typename auctioneer_t = detail::VoidAuctioneer> auto& Acts::MultiEigenStepperLoop< extensionlist_t, component_reducer_t, auctioneer_t >::ComponentProxy::jacToGlobal () inline
Definition at line 458 of file MultiEigenStepperLoop.hpp.
View newest version in sPHENIX GitHub at line 458 of file MultiEigenStepperLoop.hpp
References root_event_diff_np::cmp().
template<typename extensionlist_t = StepperExtensionList<DefaultExtension>, typename component_reducer_t = WeightedComponentReducerLoop, typename auctioneer_t = detail::VoidAuctioneer> auto& Acts::MultiEigenStepperLoop< extensionlist_t, component_reducer_t, auctioneer_t >::ComponentProxy::jacTransport () inline
Definition at line 455 of file MultiEigenStepperLoop.hpp.
View newest version in sPHENIX GitHub at line 455 of file MultiEigenStepperLoop.hpp
References root_event_diff_np::cmp().
template<typename extensionlist_t = StepperExtensionList<DefaultExtension>, typename component_reducer_t = WeightedComponentReducerLoop, typename auctioneer_t = detail::VoidAuctioneer> auto& Acts::MultiEigenStepperLoop< extensionlist_t, component_reducer_t, auctioneer_t >::ComponentProxy::pars () inline
Definition at line 453 of file MultiEigenStepperLoop.hpp.
View newest version in sPHENIX GitHub at line 453 of file MultiEigenStepperLoop.hpp
References root_event_diff_np::cmp().
template<typename extensionlist_t = StepperExtensionList<DefaultExtension>, typename component_reducer_t = WeightedComponentReducerLoop, typename auctioneer_t = detail::VoidAuctioneer> auto& Acts::MultiEigenStepperLoop< extensionlist_t, component_reducer_t, auctioneer_t >::ComponentProxy::pathAccumulated () inline
Definition at line 452 of file MultiEigenStepperLoop.hpp.
View newest version in sPHENIX GitHub at line 452 of file MultiEigenStepperLoop.hpp
References root_event_diff_np::cmp().
template<typename extensionlist_t = StepperExtensionList<DefaultExtension>, typename component_reducer_t = WeightedComponentReducerLoop, typename auctioneer_t = detail::VoidAuctioneer> template<typename propagator_state_t > auto Acts::MultiEigenStepperLoop< extensionlist_t, component_reducer_t, auctioneer_t >::ComponentProxy::singleState (propagator_state_t & state) inline
Definition at line 461 of file MultiEigenStepperLoop.hpp.
View newest version in sPHENIX GitHub at line 461 of file MultiEigenStepperLoop.hpp
References root_event_diff_np::cmp().
template<typename extensionlist_t = StepperExtensionList<DefaultExtension>, typename component_reducer_t = WeightedComponentReducerLoop, typename auctioneer_t = detail::VoidAuctioneer> auto& Acts::MultiEigenStepperLoop< extensionlist_t, component_reducer_t, auctioneer_t >::ComponentProxy::status () inline
Definition at line 450 of file MultiEigenStepperLoop.hpp.
View newest version in sPHENIX GitHub at line 450 of file MultiEigenStepperLoop.hpp
References root_event_diff_np::cmp().
template<typename extensionlist_t = StepperExtensionList<DefaultExtension>, typename component_reducer_t = WeightedComponentReducerLoop, typename auctioneer_t = detail::VoidAuctioneer> void Acts::MultiEigenStepperLoop< extensionlist_t, component_reducer_t, auctioneer_t >::ComponentProxy::update (const FreeVector & freeParams, const BoundVector & boundParams, const Covariance & covariance, const Surface & surface) inline
Definition at line 481 of file MultiEigenStepperLoop.hpp.
View newest version in sPHENIX GitHub at line 481 of file MultiEigenStepperLoop.hpp
References Acts::Surface::boundToFreeJacobian(), root_event_diff_np::cmp(), and covariance().
template<typename extensionlist_t = StepperExtensionList<DefaultExtension>, typename component_reducer_t = WeightedComponentReducerLoop, typename auctioneer_t = detail::VoidAuctioneer> auto& Acts::MultiEigenStepperLoop< extensionlist_t, component_reducer_t, auctioneer_t >::ComponentProxy::weight () inline
Definition at line 451 of file MultiEigenStepperLoop.hpp.
View newest version in sPHENIX GitHub at line 451 of file MultiEigenStepperLoop.hpp
References root_event_diff_np::cmp().
Member Data Documentation
template<typename extensionlist_t = StepperExtensionList<DefaultExtension>, typename component_reducer_t = WeightedComponentReducerLoop, typename auctioneer_t = detail::VoidAuctioneer> const State& Acts::MultiEigenStepperLoop< extensionlist_t, component_reducer_t, auctioneer_t >::ComponentProxy::all_state
Definition at line 443 of file MultiEigenStepperLoop.hpp.
View newest version in sPHENIX GitHub at line 443 of file MultiEigenStepperLoop.hpp
The documentation for this struct was generated from the following file:
acts/blob/sPHENIX/Core/include/Acts/Propagator/MultiEigenStepperLoop.hpp