Analysis Software: acts/blob/sPHENIX/Tests/UnitTests/Core/Navigation/NavigationStateUpdatorsTests.cpp File Reference
NavigationStateUpdatorsTests.cpp File Reference
#include <boost/test/unit_test.hpp>
#include "Acts/Definitions/Algebra.hpp"
#include "Acts/Geometry/GeometryContext.hpp"
#include "Acts/Navigation/NavigationState.hpp"
#include "Acts/Navigation/NavigationStateFillers.hpp"
#include "Acts/Navigation/NavigationStateUpdators.hpp"
#include "Acts/Utilities/BinningType.hpp"
#include "Acts/Utilities/IAxis.hpp"
#include "Acts/Utilities/detail/AxisFwd.hpp"
#include <algorithm>
#include <array>
#include <cstddef>
#include <memory>
#include <tuple>
#include <utility>
#include <vector>
#include "../Surfaces/SurfaceStub.hpp"
Classes
class Acts::Experimental::DetectorVolume
Define a dummy detector volume.
class Acts::Experimental::Detector
A detector.
struct Acts::Experimental::AllPortalsExtractor
Helper extractors: all portals.
struct Acts::Experimental::AllSurfacesExtractor
Helper extractors: all surfaces.
struct Acts::Experimental::IndexedSurfacesExtractor
Helper extractors: indexed surfaces.
class Acts::TestAxis
class Acts::MultiGrid1D
class Acts::MultiGrid2D
Namespaces
namespace Acts
Acts includes to create all necessary definitions.
namespace Acts::Experimental
Typedefs
using SingleVolumeUpdator = Acts::Experimental::SingleObjectImpl< Acts::Experimental::DetectorVolume, Acts::Experimental::DetectorVolumeFiller >
using AllSurfacesProvider = Acts::Experimental::StaticUpdatorImpl< Acts::Experimental::AllSurfacesExtractor, Acts::Experimental::SurfacesFiller >
using AllPortalsProvider = Acts::Experimental::StaticUpdatorImpl< Acts::Experimental::AllPortalsExtractor, Acts::Experimental::PortalsFiller >
Functions
BOOST_AUTO_TEST_CASE (SingleDetectorVolumeUpdator)
BOOST_AUTO_TEST_CASE (AllSurfaces)
BOOST_AUTO_TEST_CASE (AllPortals)
BOOST_AUTO_TEST_CASE (AllPortalsAllSurfaces)
BOOST_AUTO_TEST_CASE (AllPortalsGrid1DSurfaces)
BOOST_AUTO_TEST_CASE (AllPortalsGrid2DSurfaces)
Variables
Acts::GeometryContext tContext
auto surfaceA = Acts::Surface::makeShared<Acts::SurfaceStub>()
auto surfaceB = Acts::Surface::makeShared<Acts::SurfaceStub>()
auto surfaceC = Acts::Surface::makeShared<Acts::SurfaceStub>()
auto pSurfaceA = Acts::Surface::makeShared<Acts::SurfaceStub>()
auto pSurfaceB = Acts::Surface::makeShared<Acts::SurfaceStub>()
auto portalA = Acts::Experimental::Portal::makeShared(pSurfaceA)
auto portalB = Acts::Experimental::Portal::makeShared(pSurfaceB)
Typedef Documentation
using AllPortalsProvider = Acts::Experimental::StaticUpdatorImpl< Acts::Experimental::AllPortalsExtractor, Acts::Experimental::PortalsFiller>
Definition at line 171 of file NavigationStateUpdatorsTests.cpp.
View newest version in sPHENIX GitHub at line 171 of file NavigationStateUpdatorsTests.cpp
using AllSurfacesProvider = Acts::Experimental::StaticUpdatorImpl< Acts::Experimental::AllSurfacesExtractor, Acts::Experimental::SurfacesFiller>
Definition at line 168 of file NavigationStateUpdatorsTests.cpp.
View newest version in sPHENIX GitHub at line 168 of file NavigationStateUpdatorsTests.cpp
using SingleVolumeUpdator = Acts::Experimental::SingleObjectImpl< Acts::Experimental::DetectorVolume, Acts::Experimental::DetectorVolumeFiller>
Definition at line 164 of file NavigationStateUpdatorsTests.cpp.
View newest version in sPHENIX GitHub at line 164 of file NavigationStateUpdatorsTests.cpp
Function Documentation
BOOST_AUTO_TEST_CASE (SingleDetectorVolumeUpdator)
Definition at line 184 of file NavigationStateUpdatorsTests.cpp.
View newest version in sPHENIX GitHub at line 184 of file NavigationStateUpdatorsTests.cpp
References Acts::Experimental::NavigationState::currentVolume, nState, and Acts::Experimental::SingleObjectImpl< object_type, filler_type >::update().
BOOST_AUTO_TEST_CASE (AllSurfaces)
Definition at line 196 of file NavigationStateUpdatorsTests.cpp.
View newest version in sPHENIX GitHub at line 196 of file NavigationStateUpdatorsTests.cpp
References Acts::Experimental::NavigationState::currentVolume, nState, portalA, portalB, surfaceA, surfaceB, surfaceC, Acts::Experimental::NavigationState::surfaceCandidates, physmon_ckf_tracking::u, and Acts::Experimental::StaticUpdatorImpl< extractor_type, filler_type >::update().
BOOST_AUTO_TEST_CASE (AllPortals)
Definition at line 210 of file NavigationStateUpdatorsTests.cpp.
View newest version in sPHENIX GitHub at line 210 of file NavigationStateUpdatorsTests.cpp
References Acts::Experimental::NavigationState::currentVolume, nState, portalA, portalB, surfaceA, surfaceB, surfaceC, Acts::Experimental::NavigationState::surfaceCandidates, physmon_ckf_tracking::u, and Acts::Experimental::StaticUpdatorImpl< extractor_type, filler_type >::update().
BOOST_AUTO_TEST_CASE (AllPortalsAllSurfaces)
Definition at line 224 of file NavigationStateUpdatorsTests.cpp.
View newest version in sPHENIX GitHub at line 224 of file NavigationStateUpdatorsTests.cpp
References Acts::Experimental::NavigationState::currentVolume, nState, portalA, portalB, surfaceA, surfaceB, surfaceC, Acts::Experimental::NavigationState::surfaceCandidates, physmon_ckf_tracking::u, and Acts::Experimental::StaticUpdatorImpl< extractor_type, filler_type >::update().
BOOST_AUTO_TEST_CASE (AllPortalsGrid1DSurfaces)
Definition at line 245 of file NavigationStateUpdatorsTests.cpp.
View newest version in sPHENIX GitHub at line 245 of file NavigationStateUpdatorsTests.cpp
References Acts::binR, Acts::Experimental::NavigationState::currentVolume, grid(), testing::internal::move(), nState, portalA, portalB, surfaceA, surfaceB, surfaceC, Acts::Experimental::NavigationState::surfaceCandidates, and physmon_ckf_tracking::u.
BOOST_AUTO_TEST_CASE (AllPortalsGrid2DSurfaces)
Definition at line 271 of file NavigationStateUpdatorsTests.cpp.
View newest version in sPHENIX GitHub at line 271 of file NavigationStateUpdatorsTests.cpp
References Acts::binR, Acts::binZ, Acts::Experimental::NavigationState::currentVolume, grid(), testing::internal::move(), nState, portalA, portalB, surfaceA, surfaceB, surfaceC, Acts::Experimental::NavigationState::surfaceCandidates, and physmon_ckf_tracking::u.
Variable Documentation
auto portalA = Acts::Experimental::Portal::makeShared(pSurfaceA)
Definition at line 179 of file NavigationStateUpdatorsTests.cpp.
View newest version in sPHENIX GitHub at line 179 of file NavigationStateUpdatorsTests.cpp
Referenced by BOOST_AUTO_TEST_CASE().
auto portalB = Acts::Experimental::Portal::makeShared(pSurfaceB)
Definition at line 180 of file NavigationStateUpdatorsTests.cpp.
View newest version in sPHENIX GitHub at line 180 of file NavigationStateUpdatorsTests.cpp
Referenced by BOOST_AUTO_TEST_CASE().
auto pSurfaceA = Acts::Surface::makeShared<Acts::SurfaceStub>()
Definition at line 177 of file NavigationStateUpdatorsTests.cpp.
View newest version in sPHENIX GitHub at line 177 of file NavigationStateUpdatorsTests.cpp
Referenced by BOOST_AUTO_TEST_CASE().
auto pSurfaceB = Acts::Surface::makeShared<Acts::SurfaceStub>()
Definition at line 178 of file NavigationStateUpdatorsTests.cpp.
View newest version in sPHENIX GitHub at line 178 of file NavigationStateUpdatorsTests.cpp
Referenced by BOOST_AUTO_TEST_CASE().
auto surfaceA = Acts::Surface::makeShared<Acts::SurfaceStub>()
Definition at line 173 of file NavigationStateUpdatorsTests.cpp.
View newest version in sPHENIX GitHub at line 173 of file NavigationStateUpdatorsTests.cpp
Referenced by BOOST_AUTO_TEST_CASE().
auto surfaceB = Acts::Surface::makeShared<Acts::SurfaceStub>()
Definition at line 174 of file NavigationStateUpdatorsTests.cpp.
View newest version in sPHENIX GitHub at line 174 of file NavigationStateUpdatorsTests.cpp
Referenced by BOOST_AUTO_TEST_CASE().
auto surfaceC = Acts::Surface::makeShared<Acts::SurfaceStub>()
Definition at line 175 of file NavigationStateUpdatorsTests.cpp.
View newest version in sPHENIX GitHub at line 175 of file NavigationStateUpdatorsTests.cpp
Referenced by BOOST_AUTO_TEST_CASE().
Acts::GeometryContext tContext
Definition at line 31 of file NavigationStateUpdatorsTests.cpp.
View newest version in sPHENIX GitHub at line 31 of file NavigationStateUpdatorsTests.cpp