Analysis Software: Acts::SurfaceArray::ISurfaceGridLookup Struct Reference
Acts::SurfaceArray::ISurfaceGridLookup Struct Reference abstract
Base interface for all surface lookups.
#include <acts/blob/sPHENIX/Core/include/Acts/Surfaces/SurfaceArray.hpp>
Public Member Functions
virtual void fill (const GeometryContext &gctx, const SurfaceVector &surfaces)=0
Fill provided surfaces into the contained Grid.
virtual size_t completeBinning (const GeometryContext &gctx, const SurfaceVector &surfaces)=0
Attempts to fix sub-optimal binning by filling closest Surfaces into empty bin.
virtual SurfaceVector & lookup (const Vector3 &position)=0
Performs lookup at pos and returns bin content as reference.
virtual const SurfaceVector & lookup (const Vector3 &position) const =0
Performs lookup at pos and returns bin content as const reference.
virtual SurfaceVector & lookup (size_t bin)=0
Performs lookup at global bin and returns bin content as reference.
virtual const SurfaceVector & lookup (size_t bin) const =0
Performs lookup at global bin and returns bin content as const reference.
virtual const SurfaceVector & neighbors (const Vector3 &position) const =0
Performs a lookup at pos, but returns neighbors as well.
virtual size_t size () const =0
Returns the total size of the grid (including under/overflow bins)
virtual Vector3 getBinCenter (size_t bin) const =0
Gets the center position of bin bin in global coordinates.
virtual std::vector< const
IAxis * > getAxes () const =0
Returns copies of the axes used in the grid as AnyAxis.
virtual size_t dimensions () const =0
Get the number of dimensions of the grid.
virtual bool isValidBin (size_t bin) const =0
Checks if global bin is valid.
virtual std::vector< BinningValue > binningValues () const
The binning values described by this surface grid lookup They are in order of the axes (optional) and empty for eingle lookups.
virtual ~ISurfaceGridLookup ()=0
Pure virtual destructor.
Detailed Description
Base interface for all surface lookups.
Definition at line 35 of file SurfaceArray.hpp.
View newest version in sPHENIX GitHub at line 35 of file SurfaceArray.hpp
Constructor & Destructor Documentation
Acts::SurfaceArray::ISurfaceGridLookup::~ISurfaceGridLookup () pure virtual default
Pure virtual destructor.
Member Function Documentation
virtual std::vector<BinningValue> Acts::SurfaceArray::ISurfaceGridLookup::binningValues () const inline virtual
The binning values described by this surface grid lookup They are in order of the axes (optional) and empty for eingle lookups.
Reimplemented in Acts::SurfaceArray::SurfaceGridLookup< Axes >.
Definition at line 110 of file SurfaceArray.hpp.
View newest version in sPHENIX GitHub at line 110 of file SurfaceArray.hpp
virtual size_t Acts::SurfaceArray::ISurfaceGridLookup::completeBinning (const GeometryContext & gctx, const SurfaceVector & surfaces) pure virtual
Attempts to fix sub-optimal binning by filling closest Surfaces into empty bin.
Parameters
gctx The current geometry context object, e.g. alignment
surfaces The surface pointers to fill
Returns
number of bins that were filled
Implemented in Acts::SurfaceArray::SurfaceGridLookup< Axes >.
Referenced by Acts::SurfaceArrayCreator::completeBinning().
virtual size_t Acts::SurfaceArray::ISurfaceGridLookup::dimensions () const pure virtual
Get the number of dimensions of the grid.
Returns
number of dimensions
Implemented in Acts::SurfaceArray::SurfaceGridLookup< Axes >.
virtual void Acts::SurfaceArray::ISurfaceGridLookup::fill (const GeometryContext & gctx, const SurfaceVector & surfaces) pure virtual
Fill provided surfaces into the contained Grid.
Parameters
gctx The current geometry context object, e.g. alignment
surfaces Input surface pointers
Implemented in Acts::SurfaceArray::SurfaceGridLookup< Axes >.
Referenced by Acts::SurfaceArrayCreator::surfaceArrayOnCylinder(), Acts::SurfaceArrayCreator::surfaceArrayOnDisc(), and Acts::SurfaceArrayCreator::surfaceArrayOnPlane().
virtual std::vector<const IAxis*> Acts::SurfaceArray::ISurfaceGridLookup::getAxes () const pure virtual
Returns copies of the axes used in the grid as AnyAxis.
Returns
The axes
Note
This returns copies. Use for introspection and querying.
Implemented in Acts::SurfaceArray::SurfaceGridLookup< Axes >.
Referenced by Acts::SurfaceArrayCreator::surfaceArrayOnCylinder(), and Acts::SurfaceArrayCreator::surfaceArrayOnDisc().
virtual Vector3 Acts::SurfaceArray::ISurfaceGridLookup::getBinCenter (size_t bin) const pure virtual
Gets the center position of bin bin in global coordinates.
Parameters
bin the global bin index
Returns
The bin center
Implemented in Acts::SurfaceArray::SurfaceGridLookup< Axes >.
virtual bool Acts::SurfaceArray::ISurfaceGridLookup::isValidBin (size_t bin) const pure virtual
Checks if global bin is valid.
Parameters
bin the global bin index
Returns
bool if the bin is valid
Note
Valid means that the index points to a bin which is not a under or overflow bin or out of range in any axis.
Implemented in Acts::SurfaceArray::SurfaceGridLookup< Axes >.
virtual SurfaceVector& Acts::SurfaceArray::ISurfaceGridLookup::lookup (const Vector3 & position) pure virtual
Performs lookup at pos and returns bin content as reference.
Parameters
position Lookup position
Returns
SurfaceVector at given bin
Implemented in Acts::SurfaceArray::SurfaceGridLookup< Axes >.
virtual const SurfaceVector& Acts::SurfaceArray::ISurfaceGridLookup::lookup (const Vector3 & position) const pure virtual
Performs lookup at pos and returns bin content as const reference.
Parameters
position Lookup position
Returns
SurfaceVector at given bin
Implemented in Acts::SurfaceArray::SurfaceGridLookup< Axes >.
virtual SurfaceVector& Acts::SurfaceArray::ISurfaceGridLookup::lookup (size_t bin) pure virtual
Performs lookup at global bin and returns bin content as reference.
Parameters
bin Global lookup bin
Returns
SurfaceVector at given bin
Implemented in Acts::SurfaceArray::SurfaceGridLookup< Axes >.
virtual const SurfaceVector& Acts::SurfaceArray::ISurfaceGridLookup::lookup (size_t bin) const pure virtual
Performs lookup at global bin and returns bin content as const reference.
Parameters
bin Global lookup bin
Returns
SurfaceVector at given bin
Implemented in Acts::SurfaceArray::SurfaceGridLookup< Axes >.
virtual const SurfaceVector& Acts::SurfaceArray::ISurfaceGridLookup::neighbors (const Vector3 & position) const pure virtual
Performs a lookup at pos, but returns neighbors as well.
Parameters
position Lookup position
Returns
SurfaceVector at given bin. Copy of all bins selected
Implemented in Acts::SurfaceArray::SurfaceGridLookup< Axes >.
virtual size_t Acts::SurfaceArray::ISurfaceGridLookup::size () const pure virtual
Returns the total size of the grid (including under/overflow bins)
Returns
Size of the grid data structure
Implemented in Acts::SurfaceArray::SurfaceGridLookup< Axes >.
The documentation for this struct was generated from the following files:
acts/blob/sPHENIX/Core/include/Acts/Surfaces/SurfaceArray.hpp
acts/blob/sPHENIX/Core/src/Surfaces/SurfaceArray.cpp