Analysis Software: FilterEventsUpsilon Class Reference
FilterEventsUpsilon Class Reference
#include <analysis/blob/master/FilterEventsUpsilon/src/FilterEventsUpsilon.h>
Public Member Functions
FilterEventsUpsilon (const std::string &name="FilterEventsUpsilon")
virtual ~FilterEventsUpsilon ()
int Init (PHCompositeNode *topNode)
int InitRun (PHCompositeNode *topNode)
int process_event (PHCompositeNode *topNode)
int End (PHCompositeNode *topNode)
Called at the end of all processing.
Public Member Functions inherited from SubsysReco
~SubsysReco () override
virtual int EndRun (const int)
Called at the end of each run.
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
void Print (const std::string &="ALL") const override
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Protected Member Functions
int GetNodes (PHCompositeNode *topNode)
TVector3 GetProjectionCEMC (SvtxTrack *track)
RawCluster * MatchClusterCEMC (SvtxTrack *track, RawClusterContainer *cemc_clusters, double &dphi, double &deta, double Zvtx)
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Protected Member Functions inherited from Fun4AllBase
Fun4AllBase (const std::string &name="NONAME")
Protected Attributes
PHCompositeNode * _topNode
SvtxTrackMap * _trackmap
SvtxVertexMap * _vtxmap
RawClusterContainer * _cemc_clusters
TrackSeedContainer * _trackseedcontainer_svtx
TrackSeedContainer * _trackseedcontainer_silicon
TrackSeedContainer * _trackseedcontainer_tpc
TrkrClusterContainer * _trkrclusters
SvtxTrackMap * _trackmap_ee
RawClusterContainer * _cemc_clusters_ee
std::string outnodename_trackmap
std::string outnodename_cemc_clusters
int EventNumber
int goodEventNumber
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = std::numeric_limits<int>::max() - 10
}
Detailed Description
Definition at line 18 of file FilterEventsUpsilon.h.
View newest version in sPHENIX GitHub at line 18 of file FilterEventsUpsilon.h
Constructor & Destructor Documentation
FilterEventsUpsilon::FilterEventsUpsilon (const std::string & name = "FilterEventsUpsilon")
Definition at line 45 of file FilterEventsUpsilon.cc.
View newest version in sPHENIX GitHub at line 45 of file FilterEventsUpsilon.cc
References EventNumber, goodEventNumber, outnodename_cemc_clusters, and outnodename_trackmap.
virtual FilterEventsUpsilon::~FilterEventsUpsilon () inline virtual
Definition at line 23 of file FilterEventsUpsilon.h.
View newest version in sPHENIX GitHub at line 23 of file FilterEventsUpsilon.h
Member Function Documentation
int FilterEventsUpsilon::End (PHCompositeNode *) virtual
Called at the end of all processing.
Reimplemented from SubsysReco.
Definition at line 428 of file FilterEventsUpsilon.cc.
View newest version in sPHENIX GitHub at line 428 of file FilterEventsUpsilon.cc
References Fun4AllReturnCodes::EVENT_OK, EventNumber, and goodEventNumber.
int FilterEventsUpsilon::GetNodes (PHCompositeNode * topNode) protected
Definition at line 110 of file FilterEventsUpsilon.cc.
View newest version in sPHENIX GitHub at line 110 of file FilterEventsUpsilon.cc
References _cemc_clusters, _cemc_clusters_ee, _topNode, _trackmap, _trackmap_ee, _trackseedcontainer_silicon, _trackseedcontainer_svtx, _trackseedcontainer_tpc, _trkrclusters, Fun4AllReturnCodes::ABORTEVENT, Fun4AllReturnCodes::EVENT_OK, outnodename_cemc_clusters, outnodename_trackmap, and PHWHERE.
Referenced by process_event().
TVector3 FilterEventsUpsilon::GetProjectionCEMC (SvtxTrack * track) protected
Definition at line 151 of file FilterEventsUpsilon.cc.
View newest version in sPHENIX GitHub at line 151 of file FilterEventsUpsilon.cc
References SvtxTrack::begin_states(), SvtxTrack::end_states(), SvtxTrackState::get_pathlength(), SvtxTrack::get_state(), SvtxTrackState::get_x(), SvtxTrackState::get_y(), SvtxTrackState::get_z(), and proj().
Referenced by process_event().
int FilterEventsUpsilon::Init (PHCompositeNode *) virtual
Called during initialization. Typically this is where you can book histograms, and e.g. register them to Fun4AllServer (so they can be output to file using Fun4AllServer::dumpHistos() method).
Reimplemented from SubsysReco.
Definition at line 55 of file FilterEventsUpsilon.cc.
View newest version in sPHENIX GitHub at line 55 of file FilterEventsUpsilon.cc
References _cemc_clusters_ee, Fun4AllReturnCodes::ABORTEVENT, PHCompositeNode::addNode(), Fun4AllReturnCodes::EVENT_OK, PHNodeIterator::findFirst(), outnodename_cemc_clusters, outnodename_trackmap, and PHWHERE.
int FilterEventsUpsilon::InitRun (PHCompositeNode *) virtual
Called for first event when run number is known. Typically this is where you may want to fetch data from database, because you know the run number.
Reimplemented from SubsysReco.
Definition at line 103 of file FilterEventsUpsilon.cc.
View newest version in sPHENIX GitHub at line 103 of file FilterEventsUpsilon.cc
References Fun4AllReturnCodes::EVENT_OK.
RawCluster * FilterEventsUpsilon::MatchClusterCEMC (SvtxTrack * track, RawClusterContainer * cemc_clusters, double & dphi, double & deta, double Zvtx) protected
Definition at line 178 of file FilterEventsUpsilon.cc.
View newest version in sPHENIX GitHub at line 178 of file FilterEventsUpsilon.cc
References SvtxTrack::begin_states(), dist(), SvtxTrack::end_states(), RawCluster::get_ecore(), SvtxTrackState::get_pathlength(), RawCluster::get_r(), SvtxTrack::get_state(), SvtxTrackState::get_x(), RawCluster::get_x(), SvtxTrackState::get_y(), RawCluster::get_y(), SvtxTrackState::get_z(), RawCluster::get_z(), RawClusterContainer::getClusters(), and proj().
Referenced by process_event().
int FilterEventsUpsilon::process_event (PHCompositeNode *) virtual
Called for each event. This is where you do the real work.
Reimplemented from SubsysReco.
Definition at line 234 of file FilterEventsUpsilon.cc.
View newest version in sPHENIX GitHub at line 234 of file FilterEventsUpsilon.cc
References _cemc_clusters, _trackmap, _trackmap_ee, _trackseedcontainer_silicon, _trackseedcontainer_svtx, _trackseedcontainer_tpc, _trkrclusters, Fun4AllReturnCodes::ABORTEVENT, RawClusterContainer::AddCluster(), TrkrClusterContainer::addClusterSpecifyKey(), GlobalVertexMap::begin(), SvtxTrackMap::begin(), TrackSeedContainer::begin(), TrackSeed::begin_cluster_keys(), cemc_deta, cemc_dphi, PHObject::CloneMe(), SvtxTrackSeed_v1::CloneMe(), TrackSeed::CloneMe(), RawCluster::CloneMe(), dist(), GlobalVertexMap::end(), SvtxTrackMap::end(), TrackSeedContainer::end(), TrackSeed::end_cluster_keys(), Fun4AllReturnCodes::EVENT_OK, EventNumber, TrkrClusterContainer::findCluster(), TrackSeedContainer::get(), RawCluster::get_ecore(), GlobalVertex::get_id(), TrackSeed::get_pt(), SvtxTrack::get_px(), SvtxTrack::get_py(), SvtxTrack::get_pz(), RawCluster::get_r(), SvtxTrack::get_silicon_seed(), SvtxTrackSeed_v1::get_silicon_seed_index(), SvtxTrack::get_tpc_seed(), SvtxTrackSeed_v1::get_tpc_seed_index(), RawCluster::get_x(), RawCluster::get_y(), GlobalVertex::get_z(), RawCluster::get_z(), RawClusterContainer::getClusters(), GetNodes(), GetProjectionCEMC(), goodEventNumber, i, TrackSeedContainer::insert(), SvtxTrackMap::insert(), MatchClusterCEMC(), PHWHERE, proj(), physmon_track_finding_ttbar::pt, RawClusterContainer::Reset(), PHObject::Reset(), TrkrClusterContainer::Reset(), seed, SvtxTrackMap::size(), TrackSeedContainer::size(), RawClusterContainer::size(), TrkrClusterContainer::size(), TrackSeed::size_cluster_keys(), and Acts::Test::tmp().
Member Data Documentation
RawClusterContainer* FilterEventsUpsilon::_cemc_clusters protected
Definition at line 40 of file FilterEventsUpsilon.h.
View newest version in sPHENIX GitHub at line 40 of file FilterEventsUpsilon.h
Referenced by GetNodes(), and process_event().
RawClusterContainer* FilterEventsUpsilon::_cemc_clusters_ee protected
Definition at line 47 of file FilterEventsUpsilon.h.
View newest version in sPHENIX GitHub at line 47 of file FilterEventsUpsilon.h
Referenced by GetNodes(), and Init().
PHCompositeNode* FilterEventsUpsilon::_topNode protected
Definition at line 36 of file FilterEventsUpsilon.h.
View newest version in sPHENIX GitHub at line 36 of file FilterEventsUpsilon.h
Referenced by GetNodes().
SvtxTrackMap* FilterEventsUpsilon::_trackmap protected
Definition at line 37 of file FilterEventsUpsilon.h.
View newest version in sPHENIX GitHub at line 37 of file FilterEventsUpsilon.h
Referenced by GetNodes(), and process_event().
SvtxTrackMap* FilterEventsUpsilon::_trackmap_ee protected
Definition at line 46 of file FilterEventsUpsilon.h.
View newest version in sPHENIX GitHub at line 46 of file FilterEventsUpsilon.h
Referenced by GetNodes(), and process_event().
TrackSeedContainer* FilterEventsUpsilon::_trackseedcontainer_silicon protected
Definition at line 42 of file FilterEventsUpsilon.h.
View newest version in sPHENIX GitHub at line 42 of file FilterEventsUpsilon.h
Referenced by GetNodes(), and process_event().
TrackSeedContainer* FilterEventsUpsilon::_trackseedcontainer_svtx protected
Definition at line 41 of file FilterEventsUpsilon.h.
View newest version in sPHENIX GitHub at line 41 of file FilterEventsUpsilon.h
Referenced by GetNodes(), and process_event().
TrackSeedContainer* FilterEventsUpsilon::_trackseedcontainer_tpc protected
Definition at line 43 of file FilterEventsUpsilon.h.
View newest version in sPHENIX GitHub at line 43 of file FilterEventsUpsilon.h
Referenced by GetNodes(), and process_event().
TrkrClusterContainer* FilterEventsUpsilon::_trkrclusters protected
Definition at line 44 of file FilterEventsUpsilon.h.
View newest version in sPHENIX GitHub at line 44 of file FilterEventsUpsilon.h
Referenced by GetNodes(), and process_event().
SvtxVertexMap* FilterEventsUpsilon::_vtxmap protected
Definition at line 38 of file FilterEventsUpsilon.h.
View newest version in sPHENIX GitHub at line 38 of file FilterEventsUpsilon.h
int FilterEventsUpsilon::EventNumber protected
Definition at line 52 of file FilterEventsUpsilon.h.
View newest version in sPHENIX GitHub at line 52 of file FilterEventsUpsilon.h
Referenced by End(), FilterEventsUpsilon(), and process_event().
int FilterEventsUpsilon::goodEventNumber protected
Definition at line 53 of file FilterEventsUpsilon.h.
View newest version in sPHENIX GitHub at line 53 of file FilterEventsUpsilon.h
Referenced by End(), FilterEventsUpsilon(), and process_event().
std::string FilterEventsUpsilon::outnodename_cemc_clusters protected
Definition at line 50 of file FilterEventsUpsilon.h.
View newest version in sPHENIX GitHub at line 50 of file FilterEventsUpsilon.h
Referenced by FilterEventsUpsilon(), GetNodes(), and Init().
std::string FilterEventsUpsilon::outnodename_trackmap protected
Definition at line 49 of file FilterEventsUpsilon.h.
View newest version in sPHENIX GitHub at line 49 of file FilterEventsUpsilon.h
Referenced by FilterEventsUpsilon(), GetNodes(), and Init().
The documentation for this class was generated from the following files:
analysis/blob/master/FilterEventsUpsilon/src/FilterEventsUpsilon.h
analysis/blob/master/FilterEventsUpsilon/src/FilterEventsUpsilon.cc