Analysis Software: SharedPtr< T >::__SharedCountingPtr Class Reference
SharedPtr< T >::__SharedCountingPtr Class Reference
#include <JETSCAPE/blob/main/external_packages/fjcore.hh>
Public Member Functions
__SharedCountingPtr ()
template<class Y >
__SharedCountingPtr (Y *ptr)
~__SharedCountingPtr ()
T * get () const
long use_count () const
long operator++ ()
long operator-- ()
long operator++ (int)
long operator-- (int)
void set_count (const long &count)
Private Attributes
T * _ptr
the pointer we're counting the references to
long _count
the number of references
Detailed Description
template<class T>
class SharedPtr< T >::__SharedCountingPtr
Definition at line 354 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 354 of file fjcore.hh
Constructor & Destructor Documentation
template<class T> SharedPtr< T >::__SharedCountingPtr::__SharedCountingPtr () inline
Definition at line 356 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 356 of file fjcore.hh
template<class T> template<class Y > SharedPtr< T >::__SharedCountingPtr::__SharedCountingPtr (Y * ptr) inline explicit
Definition at line 357 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 357 of file fjcore.hh
template<class T> SharedPtr< T >::__SharedCountingPtr::~__SharedCountingPtr () inline
Definition at line 358 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 358 of file fjcore.hh
References SharedPtr< T >::__SharedCountingPtr::_ptr.
Member Function Documentation
template<class T> T* SharedPtr< T >::__SharedCountingPtr::get (void) const inline
Definition at line 361 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 361 of file fjcore.hh
References SharedPtr< T >::__SharedCountingPtr::_ptr.
Referenced by SharedPtr< MinHeap >::get(), SharedPtr< MinHeap >::operator()(), SharedPtr< MinHeap >::operator*(), and SharedPtr< MinHeap >::operator->().
template<class T> long SharedPtr< T >::__SharedCountingPtr::operator++ () inline
Definition at line 363 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 363 of file fjcore.hh
References SharedPtr< T >::__SharedCountingPtr::_count.
template<class T> long SharedPtr< T >::__SharedCountingPtr::operator++ (int) inline
Definition at line 365 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 365 of file fjcore.hh
References SharedPtr< T >::__SharedCountingPtr::_count.
template<class T> long SharedPtr< T >::__SharedCountingPtr::operator-- () inline
Definition at line 364 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 364 of file fjcore.hh
References SharedPtr< T >::__SharedCountingPtr::_count.
template<class T> long SharedPtr< T >::__SharedCountingPtr::operator-- (int) inline
Definition at line 366 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 366 of file fjcore.hh
References SharedPtr< T >::__SharedCountingPtr::_count.
template<class T> void SharedPtr< T >::__SharedCountingPtr::set_count (const long & count) inline
Definition at line 367 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 367 of file fjcore.hh
References SharedPtr< T >::__SharedCountingPtr::_count, and test_fpe::count.
Referenced by SharedPtr< MinHeap >::set_count().
template<class T> long SharedPtr< T >::__SharedCountingPtr::use_count () const inline
Definition at line 362 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 362 of file fjcore.hh
References SharedPtr< T >::__SharedCountingPtr::_count.
Referenced by SharedPtr< MinHeap >::_decrease_count(), and SharedPtr< MinHeap >::use_count().
Member Data Documentation
template<class T> long SharedPtr< T >::__SharedCountingPtr::_count private
the number of references
Definition at line 372 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 372 of file fjcore.hh
Referenced by SharedPtr< T >::__SharedCountingPtr::operator++(), SharedPtr< T >::__SharedCountingPtr::operator--(), SharedPtr< T >::__SharedCountingPtr::set_count(), and SharedPtr< T >::__SharedCountingPtr::use_count().
template<class T> T* SharedPtr< T >::__SharedCountingPtr::_ptr private
the pointer we're counting the references to
Definition at line 371 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 371 of file fjcore.hh
Referenced by SharedPtr< T >::__SharedCountingPtr::get(), and SharedPtr< T >::__SharedCountingPtr::~__SharedCountingPtr().
The documentation for this class was generated from the following file:
JETSCAPE/blob/main/external_packages/fjcore.hh