Analysis Software: SmashWrapper Class Reference
SmashWrapper Class Reference
#include <JETSCAPE/blob/main/src/afterburner/SmashWrapper.h>
Public Member Functions
void smash_particles_to_JS_hadrons (const smash::Particles &smash_particles, std::vector< shared_ptr< Hadron >> &JS_hadrons)
SmashWrapper ()
void InitTask ()
void ExecuteTask ()
void WriteTask (weak_ptr< JetScapeWriter > w)
Public Member Functions inherited from Jetscape::Afterburner
Afterburner ()
~Afterburner ()
virtual void Init ()
virtual void Exec ()
Public Member Functions inherited from Jetscape::JetScapeModuleBase
JetScapeModuleBase ()
JetScapeModuleBase (string m_name)
virtual ~JetScapeModuleBase ()
virtual void Clear ()
void SetXMLMainFileName (string m_name)
string GetXMLMainFileName ()
void SetXMLUserFileName (string m_name)
string GetXMLUserFileName ()
shared_ptr< std::mt19937 > GetMt19937Generator ()
tinyxml2::XMLElement * GetXMLElement (std::initializer_list< const char * > path, bool isRequired=true)
std::string GetXMLElementText (std::initializer_list< const char * > path, bool isRequired=true)
int GetXMLElementInt (std::initializer_list< const char * > path, bool isRequired=true)
double GetXMLElementDouble (std::initializer_list< const char * > path, bool isRequired=true)
Public Member Functions inherited from Jetscape::JetScapeTask
JetScapeTask ()
virtual ~JetScapeTask ()
virtual void Finish ()
virtual void ExecuteTasks ()
virtual void InitTasks ()
virtual void ClearTasks ()
virtual void ClearTask ()
virtual void FinishTask ()
virtual void FinishTasks ()
virtual void WriteTasks (weak_ptr< JetScapeWriter > w)
virtual void CollectHeader (weak_ptr< JetScapeWriter > w)
virtual void CollectHeaders (weak_ptr< JetScapeWriter > w)
virtual void Add (shared_ptr< JetScapeTask > m_tasks)
virtual const int GetMyTaskNumber () const
const vector< shared_ptr
< JetScapeTask > > GetTaskList () const
shared_ptr< JetScapeTask > GetTaskAt (int i)
void EraseTaskLast ()
void EraseTaskAt (int i)
void ResizeTaskList (int i)
void ClearTaskList ()
int GetNumberOfTasks ()
const bool GetActive () const
void SetActive (bool m_active_exec)
void SetId (string m_id)
const string GetId () const
const shared_ptr
< JetScapeModuleMutex > GetMutex () const
void SetMutex (shared_ptr< JetScapeModuleMutex > m_mutex)
Public Member Functions inherited from sigslot::has_slots< sigslot::multi_threaded_local >
has_slots ()
has_slots (const has_slots &hs)
void signal_connect (_signal_base< sigslot::multi_threaded_local > *sender)
void signal_disconnect (_signal_base< sigslot::multi_threaded_local > *sender)
virtual ~has_slots ()
void disconnect_all ()
Private Attributes
bool only_final_decays_ = false
double end_time_ = -1.0
shared_ptr< smash::Experiment
< AfterburnerModus > > smash_experiment_
Static Private Attributes
static RegisterJetScapeModule
< SmashWrapper > reg
Additional Inherited Members
Static Public Member Functions inherited from Jetscape::JetScapeModuleBase
static int GetCurrentEvent ()
static void IncrementCurrentEvent ()
Protected Member Functions inherited from Jetscape::Afterburner
std::vector< std::vector
< std::shared_ptr< Hadron > > > GatherAfterburnerHadrons ()
Gather all hadrons from soft particlization and fragmentation.
std::vector< std::vector
< std::shared_ptr< Hadron > > > GetSoftParticlizationHadrons ()
Get the events of soft particlization hadrons.
std::vector< std::shared_ptr
< Hadron > > GetFragmentationHadrons ()
Get the list of fragmentation hadrons.
Protected Attributes inherited from Jetscape::Afterburner
std::vector< std::vector
< std::shared_ptr< Hadron > > > dummy
std::uniform_real_distribution
< double > ZeroOneDistribution
std::shared_ptr
< std::uniform_int_distribution
< int > > rand_int_ptr_
Detailed Description
Definition at line 66 of file SmashWrapper.h.
View newest version in sPHENIX GitHub at line 66 of file SmashWrapper.h
Constructor & Destructor Documentation
SmashWrapper::SmashWrapper ()
Definition at line 32 of file SmashWrapper.cc.
View newest version in sPHENIX GitHub at line 32 of file SmashWrapper.cc
References SetId().
Member Function Documentation
void SmashWrapper::ExecuteTask () virtual
A virtual function to define a default ExecuteTask() function for a JetScapeTask. It can be overridden by different modules/tasks.
Reimplemented from Jetscape::JetScapeTask.
Definition at line 77 of file SmashWrapper.cc.
View newest version in sPHENIX GitHub at line 77 of file SmashWrapper.cc
References i, AfterburnerModus::jetscape_hadrons_, JSINFO, geant4_parallel::n_events, and AfterburnerModus::reset_event_numbering().
void SmashWrapper::InitTask () virtual
A virtual function to define a default InitTask() function for a JetScapeTask. It can be overridden by different modules/tasks.
Reimplemented from Jetscape::JetScapeTask.
Definition at line 34 of file SmashWrapper.cc.
View newest version in sPHENIX GitHub at line 34 of file SmashWrapper.cc
References filter::config, JSINFO, and path.
void SmashWrapper::smash_particles_to_JS_hadrons (const smash::Particles & smash_particles, std::vector< shared_ptr< Hadron >> & JS_hadrons)
Definition at line 136 of file SmashWrapper.cc.
View newest version in sPHENIX GitHub at line 136 of file SmashWrapper.cc
References merge_hashes::p, particle, and physmon_track_finding_ttbar::r.
void SmashWrapper::WriteTask (weak_ptr< JetScapeWriter > w) virtual
A virtual function to define a default WriteTask() function for a JetScapeTask. It can be overridden by different modules/tasks. Current setup: Every task gets handed a pointer to the writer and can add any information it likes to it (using predefined functions like WriteComment()) This is maximally flexible but makes it difficult to properly store information for a variety of outputs. E.g., sigmaGen: A HardProcess can easily write the xsec to any stream-type output using WriteComment. But to set it in a HepMC file, either HardProcess needs to make a case-by-case selection, meaning a new file format would need to percolate through multiple base classes, or the writer needs to know this information and implement WriteEvent appropriately. The latter is obviously better, but it's non-trivial to collect this information.
Reimplemented from Jetscape::JetScapeTask.
Definition at line 104 of file SmashWrapper.cc.
View newest version in sPHENIX GitHub at line 104 of file SmashWrapper.cc
References event, f, i, AfterburnerModus::jetscape_hadrons_, JSINFO, and to_string().
Member Data Documentation
double SmashWrapper::end_time_ = -1.0 private
Definition at line 69 of file SmashWrapper.h.
View newest version in sPHENIX GitHub at line 69 of file SmashWrapper.h
bool SmashWrapper::only_final_decays_ = false private
Definition at line 68 of file SmashWrapper.h.
View newest version in sPHENIX GitHub at line 68 of file SmashWrapper.h
RegisterJetScapeModule< SmashWrapper > SmashWrapper::reg static private
Definition at line 73 of file SmashWrapper.h.
View newest version in sPHENIX GitHub at line 73 of file SmashWrapper.h
shared_ptr<smash::Experiment<AfterburnerModus> > SmashWrapper::smash_experiment_ private
Definition at line 70 of file SmashWrapper.h.
View newest version in sPHENIX GitHub at line 70 of file SmashWrapper.h
The documentation for this class was generated from the following files:
JETSCAPE/blob/main/src/afterburner/SmashWrapper.h
JETSCAPE/blob/main/src/afterburner/SmashWrapper.cc