Analysis Software: CaloCalibEmc_Pi0 Class Reference
CaloCalibEmc_Pi0 Class Reference
#include <coresoftware/blob/master/calibrations/calorimeter/calo_emc_pi0_tbt/CaloCalibEmc_Pi0.h>
Public Member Functions
CaloCalibEmc_Pi0 (const std::string &name="CaloCalibEmc_Pi0", const std::string &fnm="outJF")
~CaloCalibEmc_Pi0 () override=default
int InitRun (PHCompositeNode *topNode) override
int process_event (PHCompositeNode *topNode) override
int End (PHCompositeNode *topNode) override
Called at the end of all processing.
void Loop (int nevts, const std::string &filename, TTree *intree=0, const std::string &ifileCorr="")
void Loop_for_eta_slices (int nevts, const std::string &filename, TTree *intree=0, const std::string &ifileCorr="")
void Fit_Histos_Etas96 (const std::string &infilent)
void Fit_Histos (const std::string &infilent)
void Fit_Histos_Eta_Phi_Add96 (const std::string &infilent)
void Fit_Histos_Eta_Phi_Add32 (const std::string &infilent)
void set_centrality_nclusters_cut (int n)
void Add_32 ()
void Add_96 ()
void Get_Histos (const std::string &infile, const std::string &outfile)
void set_UseTowerInfo (const int useMode)
void setInputClusterNodeName (const std::string &inpNodenm)
void setInputTowerNodeName (const std::string &inpNodenm)
void set_calibSetMassVal (float insetval)
Public Member Functions inherited from SubsysReco
~SubsysReco () override
virtual int EndRun (const int)
Called at the end of each run.
virtual int Init (PHCompositeNode *)
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
void Print (const std::string &="ALL") const override
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Private Attributes
float _setMassVal {0.152}
int m_ievent {0}
std::string m_Filename
TFile * cal_output {nullptr}
std::string _caloname {"CEMC"}
std::string _inputnodename
std::string _inputtownodename
int m_cent_nclus_cut {0}
std::array< std::array< TH1 *, 258 >, 96 > cemc_hist_eta_phi {}
std::array< TH1 *, 96 > eta_hist {}
TH2F * mass_eta {nullptr}
TH3F * mass_eta_phi {nullptr}
TH1F * h_totalClusters {nullptr}
TH3F * pt1_ptpi0_alpha {nullptr}
TH2F * fitp1_eta_phi2d {nullptr}
TH1F * pairInvMassTotal {nullptr}
TTree * _eventTree {nullptr}
int _eventNumber {-1}
int _nClusters {-1}
float _clusterIDs [10000] {0}
float _clusterEnergies [10000] {0}
float _clusterPts [10000] {0}
float _clusterEtas [10000] {0}
float _clusterPhis [10000] {0}
int maxTowerEta {-1}
int maxTowerPhi {-1}
int _maxTowerEtas [10000] {0}
int _maxTowerPhis [10000] {0}
float alphaCut {-1.}
TFile * f_temp {nullptr}
int m_UseTowerInfo {0}
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = std::numeric_limits<int>::max() - 10
}
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Detailed Description
Definition at line 23 of file CaloCalibEmc_Pi0.h.
View newest version in sPHENIX GitHub at line 23 of file CaloCalibEmc_Pi0.h
Constructor & Destructor Documentation
CaloCalibEmc_Pi0::CaloCalibEmc_Pi0 (const std::string & name = "CaloCalibEmc_Pi0", const std::string & fnm = "outJF")
Definition at line 44 of file CaloCalibEmc_Pi0.cc.
View newest version in sPHENIX GitHub at line 44 of file CaloCalibEmc_Pi0.cc
References cemc_hist_eta_phi, and eta_hist.
CaloCalibEmc_Pi0::~CaloCalibEmc_Pi0 () override default
Member Function Documentation
void CaloCalibEmc_Pi0::Add_32 ()
Definition at line 1728 of file CaloCalibEmc_Pi0.cc.
View newest version in sPHENIX GitHub at line 1728 of file CaloCalibEmc_Pi0.cc
References cemc_hist_eta_phi.
Referenced by save_corr_value2().
void CaloCalibEmc_Pi0::Add_96 ()
Definition at line 1752 of file CaloCalibEmc_Pi0.cc.
View newest version in sPHENIX GitHub at line 1752 of file CaloCalibEmc_Pi0.cc
References cemc_hist_eta_phi.
Referenced by save_correc_value().
int CaloCalibEmc_Pi0::End (PHCompositeNode * topNode) override virtual
Called at the end of all processing.
Reimplemented from SubsysReco.
Definition at line 395 of file CaloCalibEmc_Pi0.cc.
View newest version in sPHENIX GitHub at line 395 of file CaloCalibEmc_Pi0.cc
References cal_output, Fun4AllReturnCodes::EVENT_OK, and f_temp.
Referenced by runCCPi0Loop(), runLCELoop(), save_corr_value2(), save_correc_value(), and wholeIter_Pi0EtaByEta().
void CaloCalibEmc_Pi0::Fit_Histos (const std::string & infilent)
Definition at line 859 of file CaloCalibEmc_Pi0.cc.
View newest version in sPHENIX GitHub at line 859 of file CaloCalibEmc_Pi0.cc
References cal_output, cemc_hist_eta_phi, ci, std::tr1::f1, std::tr1::f2, fitp1_eta_phi2d, and to_string().
Referenced by save_correc_value().
void CaloCalibEmc_Pi0::Fit_Histos_Eta_Phi_Add32 (const std::string & infilent)
Definition at line 1251 of file CaloCalibEmc_Pi0.cc.
View newest version in sPHENIX GitHub at line 1251 of file CaloCalibEmc_Pi0.cc
References cal_output, cemc_hist_eta_phi, ci, std::tr1::f1, std::tr1::f2, fitp1_eta_phi2d, and to_string().
void CaloCalibEmc_Pi0::Fit_Histos_Eta_Phi_Add96 (const std::string & infilent)
Definition at line 1050 of file CaloCalibEmc_Pi0.cc.
View newest version in sPHENIX GitHub at line 1050 of file CaloCalibEmc_Pi0.cc
References cal_output, cemc_hist_eta_phi, ci, std::tr1::f1, std::tr1::f2, fitp1_eta_phi2d, and to_string().
Referenced by save_correc_value().
void CaloCalibEmc_Pi0::Fit_Histos_Etas96 (const std::string & infilent)
Definition at line 1419 of file CaloCalibEmc_Pi0.cc.
View newest version in sPHENIX GitHub at line 1419 of file CaloCalibEmc_Pi0.cc
References _setMassVal, cal_output, ci, eta_hist, std::tr1::f1, std::tr1::f2, i, and to_string().
Referenced by wholeIter_Pi0EtaByEta().
void CaloCalibEmc_Pi0::Get_Histos (const std::string & infile, const std::string & outfile)
Definition at line 1699 of file CaloCalibEmc_Pi0.cc.
View newest version in sPHENIX GitHub at line 1699 of file CaloCalibEmc_Pi0.cc
References KFPMath::b, cal_output, cemc_hist_eta_phi, eta_hist, i, j, add_histos::outfile, and to_string().
Referenced by save_corr_value2(), save_correc_value(), and wholeIter_Pi0EtaByEta().
int CaloCalibEmc_Pi0::InitRun (PHCompositeNode * topNode) override virtual
Called for first event when run number is known. Typically this is where you may want to fetch data from database, because you know the run number. A place to book histograms which have to know the run number.
Reimplemented from SubsysReco.
Definition at line 56 of file CaloCalibEmc_Pi0.cc.
View newest version in sPHENIX GitHub at line 56 of file CaloCalibEmc_Pi0.cc
References _clusterEnergies, _clusterEtas, _clusterIDs, _clusterPhis, _clusterPts, _eventNumber, _eventTree, _maxTowerEtas, _maxTowerPhis, _nClusters, KFPMath::b, cal_output, eta_hist, Fun4AllReturnCodes::EVENT_OK, fitp1_eta_phi2d, h_totalClusters, i, m_Filename, m_ievent, mass_eta, mass_eta_phi, pairInvMassTotal, pt1_ptpi0_alpha, and to_string().
Referenced by runCCPi0Loop(), runLCELoop(), and wholeIter_Pi0EtaByEta().
void CaloCalibEmc_Pi0::Loop (int nevts, const std::string & filename, TTree * intree = 0, const std::string & ifileCorr = "")
Definition at line 416 of file CaloCalibEmc_Pi0.cc.
View newest version in sPHENIX GitHub at line 416 of file CaloCalibEmc_Pi0.cc
References _clusterEnergies, _clusterEtas, _clusterPhis, _clusterPts, _maxTowerEtas, _maxTowerPhis, _nClusters, alphaCut, ci, E, eta, eta_hist, f, i, j, mass_eta, mass_eta_phi, pairInvMassTotal, ActsTests::PropagationDatasets::phi, physmon_track_finding_ttbar::pt, pt1_ptpi0_alpha, and ambiguity_solver_full_chain::t1.
Referenced by runCCPi0Loop(), runLCELoop(), and wholeIter_Pi0EtaByEta().
void CaloCalibEmc_Pi0::Loop_for_eta_slices (int nevts, const std::string & filename, TTree * intree = 0, const std::string & ifileCorr = "")
Definition at line 674 of file CaloCalibEmc_Pi0.cc.
View newest version in sPHENIX GitHub at line 674 of file CaloCalibEmc_Pi0.cc
References _clusterEnergies, _clusterEtas, _clusterPhis, _clusterPts, _maxTowerEtas, _maxTowerPhis, _nClusters, alphaCut, cemc_hist_eta_phi, ci, E, eta, eta_hist, f, i, j, ActsTests::PropagationDatasets::phi, physmon_track_finding_ttbar::pt, and ambiguity_solver_full_chain::t1.
int CaloCalibEmc_Pi0::process_event (PHCompositeNode * topNode) override virtual
Called for each event. This is where you do the real work.
Reimplemented from SubsysReco.
Definition at line 114 of file CaloCalibEmc_Pi0.cc.
View newest version in sPHENIX GitHub at line 114 of file CaloCalibEmc_Pi0.cc
References _caloname, _clusterEnergies, _clusterEtas, _clusterIDs, _clusterPhis, _clusterPts, _eventNumber, _eventTree, _inputnodename, _inputtownodename, _maxTowerEtas, _maxTowerPhis, _nClusters, Fun4AllReturnCodes::ABORTEVENT, alphaCut, GlobalVertexMap::begin(), cemc_hist_eta_phi, RawTowerDefs::decode_index1(), RawTowerDefs::decode_index2(), GlobalVertexMap::empty(), eta_hist, Fun4AllReturnCodes::EVENT_OK, RawTower::get_bineta(), RawTower::get_binphi(), RawCluster::get_chi2(), RawCluster::get_ecore(), RawCluster::get_id(), RawCluster::get_towers(), GlobalVertex::get_x(), GlobalVertex::get_y(), GlobalVertex::get_z(), RawClusterContainer::getClusters(), RawClusterUtility::GetECoreVec(), RawTowerContainer::getTower(), m_cent_nclus_cut, m_ievent, m_UseTowerInfo, mass_eta, maxTowerEta, maxTowerPhi, pairInvMassTotal, PHWHERE, pt1_ptpi0_alpha, vx, vy, and vz.
void CaloCalibEmc_Pi0::set_calibSetMassVal (float insetval) inline
Definition at line 75 of file CaloCalibEmc_Pi0.h.
View newest version in sPHENIX GitHub at line 75 of file CaloCalibEmc_Pi0.h
References _setMassVal.
void CaloCalibEmc_Pi0::set_centrality_nclusters_cut (int n) inline
Definition at line 53 of file CaloCalibEmc_Pi0.h.
View newest version in sPHENIX GitHub at line 53 of file CaloCalibEmc_Pi0.h
References m_cent_nclus_cut, and n.
Referenced by Fun4All_pi0tbt_SIMPLE_EMBED().
void CaloCalibEmc_Pi0::set_UseTowerInfo (const int useMode) inline
Definition at line 60 of file CaloCalibEmc_Pi0.h.
View newest version in sPHENIX GitHub at line 60 of file CaloCalibEmc_Pi0.h
References m_UseTowerInfo.
Referenced by clus_dst_simple_superfastcalib(), dst_simple_towerslope_runmacro(), spiNo2(), srundst_mdc2_clustest(), and wholeIter_Pi0EtaByEta().
void CaloCalibEmc_Pi0::setInputClusterNodeName (const std::string & inpNodenm) inline
Definition at line 65 of file CaloCalibEmc_Pi0.h.
View newest version in sPHENIX GitHub at line 65 of file CaloCalibEmc_Pi0.h
References _inputnodename.
Referenced by wholeIter_Pi0EtaByEta().
void CaloCalibEmc_Pi0::setInputTowerNodeName (const std::string & inpNodenm) inline
Definition at line 70 of file CaloCalibEmc_Pi0.h.
View newest version in sPHENIX GitHub at line 70 of file CaloCalibEmc_Pi0.h
References _inputtownodename.
Referenced by wholeIter_Pi0EtaByEta().
Member Data Documentation
std::string CaloCalibEmc_Pi0::_caloname {"CEMC"} private
Definition at line 88 of file CaloCalibEmc_Pi0.h.
View newest version in sPHENIX GitHub at line 88 of file CaloCalibEmc_Pi0.h
Referenced by process_event().
float CaloCalibEmc_Pi0::_clusterEnergies[10000] {0} private
Definition at line 110 of file CaloCalibEmc_Pi0.h.
View newest version in sPHENIX GitHub at line 110 of file CaloCalibEmc_Pi0.h
Referenced by InitRun(), Loop(), Loop_for_eta_slices(), and process_event().
float CaloCalibEmc_Pi0::_clusterEtas[10000] {0} private
Definition at line 112 of file CaloCalibEmc_Pi0.h.
View newest version in sPHENIX GitHub at line 112 of file CaloCalibEmc_Pi0.h
Referenced by InitRun(), Loop(), Loop_for_eta_slices(), and process_event().
float CaloCalibEmc_Pi0::_clusterIDs[10000] {0} private
Definition at line 109 of file CaloCalibEmc_Pi0.h.
View newest version in sPHENIX GitHub at line 109 of file CaloCalibEmc_Pi0.h
Referenced by InitRun(), and process_event().
float CaloCalibEmc_Pi0::_clusterPhis[10000] {0} private
Definition at line 113 of file CaloCalibEmc_Pi0.h.
View newest version in sPHENIX GitHub at line 113 of file CaloCalibEmc_Pi0.h
Referenced by InitRun(), Loop(), Loop_for_eta_slices(), and process_event().
float CaloCalibEmc_Pi0::_clusterPts[10000] {0} private
Definition at line 111 of file CaloCalibEmc_Pi0.h.
View newest version in sPHENIX GitHub at line 111 of file CaloCalibEmc_Pi0.h
Referenced by InitRun(), Loop(), Loop_for_eta_slices(), and process_event().
int CaloCalibEmc_Pi0::_eventNumber {-1} private
Definition at line 107 of file CaloCalibEmc_Pi0.h.
View newest version in sPHENIX GitHub at line 107 of file CaloCalibEmc_Pi0.h
Referenced by InitRun(), and process_event().
TTree* CaloCalibEmc_Pi0::_eventTree {nullptr} private
Definition at line 105 of file CaloCalibEmc_Pi0.h.
View newest version in sPHENIX GitHub at line 105 of file CaloCalibEmc_Pi0.h
Referenced by InitRun(), and process_event().
std::string CaloCalibEmc_Pi0::_inputnodename private
Definition at line 89 of file CaloCalibEmc_Pi0.h.
View newest version in sPHENIX GitHub at line 89 of file CaloCalibEmc_Pi0.h
Referenced by process_event(), and setInputClusterNodeName().
std::string CaloCalibEmc_Pi0::_inputtownodename private
Definition at line 90 of file CaloCalibEmc_Pi0.h.
View newest version in sPHENIX GitHub at line 90 of file CaloCalibEmc_Pi0.h
Referenced by process_event(), and setInputTowerNodeName().
int CaloCalibEmc_Pi0::_maxTowerEtas[10000] {0} private
Definition at line 118 of file CaloCalibEmc_Pi0.h.
View newest version in sPHENIX GitHub at line 118 of file CaloCalibEmc_Pi0.h
Referenced by InitRun(), Loop(), Loop_for_eta_slices(), and process_event().
int CaloCalibEmc_Pi0::_maxTowerPhis[10000] {0} private
Definition at line 119 of file CaloCalibEmc_Pi0.h.
View newest version in sPHENIX GitHub at line 119 of file CaloCalibEmc_Pi0.h
Referenced by InitRun(), Loop(), Loop_for_eta_slices(), and process_event().
int CaloCalibEmc_Pi0::_nClusters {-1} private
Definition at line 108 of file CaloCalibEmc_Pi0.h.
View newest version in sPHENIX GitHub at line 108 of file CaloCalibEmc_Pi0.h
Referenced by InitRun(), Loop(), Loop_for_eta_slices(), and process_event().
float CaloCalibEmc_Pi0::_setMassVal {0.152} private
Definition at line 82 of file CaloCalibEmc_Pi0.h.
View newest version in sPHENIX GitHub at line 82 of file CaloCalibEmc_Pi0.h
Referenced by Fit_Histos_Etas96(), and set_calibSetMassVal().
float CaloCalibEmc_Pi0::alphaCut {-1.} private
Definition at line 121 of file CaloCalibEmc_Pi0.h.
View newest version in sPHENIX GitHub at line 121 of file CaloCalibEmc_Pi0.h
Referenced by Loop(), Loop_for_eta_slices(), and process_event().
TFile* CaloCalibEmc_Pi0::cal_output {nullptr} private
Definition at line 87 of file CaloCalibEmc_Pi0.h.
View newest version in sPHENIX GitHub at line 87 of file CaloCalibEmc_Pi0.h
Referenced by End(), Fit_Histos(), Fit_Histos_Eta_Phi_Add32(), Fit_Histos_Eta_Phi_Add96(), Fit_Histos_Etas96(), Get_Histos(), and InitRun().
std::array<std::array<TH1 *, 258>, 96> CaloCalibEmc_Pi0::cemc_hist_eta_phi {} private
Definition at line 96 of file CaloCalibEmc_Pi0.h.
View newest version in sPHENIX GitHub at line 96 of file CaloCalibEmc_Pi0.h
Referenced by Add_32(), Add_96(), CaloCalibEmc_Pi0(), Fit_Histos(), Fit_Histos_Eta_Phi_Add32(), Fit_Histos_Eta_Phi_Add96(), Get_Histos(), Loop_for_eta_slices(), and process_event().
std::array<TH1 *, 96> CaloCalibEmc_Pi0::eta_hist {} private
Definition at line 97 of file CaloCalibEmc_Pi0.h.
View newest version in sPHENIX GitHub at line 97 of file CaloCalibEmc_Pi0.h
Referenced by CaloCalibEmc_Pi0(), Fit_Histos_Etas96(), Get_Histos(), InitRun(), Loop(), Loop_for_eta_slices(), and process_event().
TFile* CaloCalibEmc_Pi0::f_temp {nullptr} private
Definition at line 130 of file CaloCalibEmc_Pi0.h.
View newest version in sPHENIX GitHub at line 130 of file CaloCalibEmc_Pi0.h
Referenced by End().
TH2F* CaloCalibEmc_Pi0::fitp1_eta_phi2d {nullptr} private
Definition at line 102 of file CaloCalibEmc_Pi0.h.
View newest version in sPHENIX GitHub at line 102 of file CaloCalibEmc_Pi0.h
Referenced by Fit_Histos(), Fit_Histos_Eta_Phi_Add32(), Fit_Histos_Eta_Phi_Add96(), and InitRun().
TH1F* CaloCalibEmc_Pi0::h_totalClusters {nullptr} private
Definition at line 100 of file CaloCalibEmc_Pi0.h.
View newest version in sPHENIX GitHub at line 100 of file CaloCalibEmc_Pi0.h
Referenced by InitRun().
int CaloCalibEmc_Pi0::m_cent_nclus_cut {0} private
Definition at line 92 of file CaloCalibEmc_Pi0.h.
View newest version in sPHENIX GitHub at line 92 of file CaloCalibEmc_Pi0.h
Referenced by process_event(), and set_centrality_nclusters_cut().
std::string CaloCalibEmc_Pi0::m_Filename private
Definition at line 86 of file CaloCalibEmc_Pi0.h.
View newest version in sPHENIX GitHub at line 86 of file CaloCalibEmc_Pi0.h
Referenced by InitRun().
int CaloCalibEmc_Pi0::m_ievent {0} private
Definition at line 85 of file CaloCalibEmc_Pi0.h.
View newest version in sPHENIX GitHub at line 85 of file CaloCalibEmc_Pi0.h
Referenced by InitRun(), and process_event().
int CaloCalibEmc_Pi0::m_UseTowerInfo {0} private
Definition at line 132 of file CaloCalibEmc_Pi0.h.
View newest version in sPHENIX GitHub at line 132 of file CaloCalibEmc_Pi0.h
Referenced by process_event(), and set_UseTowerInfo().
TH2F* CaloCalibEmc_Pi0::mass_eta {nullptr} private
Definition at line 98 of file CaloCalibEmc_Pi0.h.
View newest version in sPHENIX GitHub at line 98 of file CaloCalibEmc_Pi0.h
Referenced by InitRun(), Loop(), and process_event().
TH3F* CaloCalibEmc_Pi0::mass_eta_phi {nullptr} private
Definition at line 99 of file CaloCalibEmc_Pi0.h.
View newest version in sPHENIX GitHub at line 99 of file CaloCalibEmc_Pi0.h
Referenced by InitRun(), and Loop().
int CaloCalibEmc_Pi0::maxTowerEta {-1} private
Definition at line 115 of file CaloCalibEmc_Pi0.h.
View newest version in sPHENIX GitHub at line 115 of file CaloCalibEmc_Pi0.h
Referenced by process_event().
int CaloCalibEmc_Pi0::maxTowerPhi {-1} private
Definition at line 116 of file CaloCalibEmc_Pi0.h.
View newest version in sPHENIX GitHub at line 116 of file CaloCalibEmc_Pi0.h
Referenced by process_event().
TH1F* CaloCalibEmc_Pi0::pairInvMassTotal {nullptr} private
Definition at line 103 of file CaloCalibEmc_Pi0.h.
View newest version in sPHENIX GitHub at line 103 of file CaloCalibEmc_Pi0.h
Referenced by InitRun(), Loop(), and process_event().
TH3F* CaloCalibEmc_Pi0::pt1_ptpi0_alpha {nullptr} private
Definition at line 101 of file CaloCalibEmc_Pi0.h.
View newest version in sPHENIX GitHub at line 101 of file CaloCalibEmc_Pi0.h
Referenced by InitRun(), Loop(), and process_event().
The documentation for this class was generated from the following files:
coresoftware/blob/master/calibrations/calorimeter/calo_emc_pi0_tbt/CaloCalibEmc_Pi0.h
coresoftware/blob/master/calibrations/calorimeter/calo_emc_pi0_tbt/CaloCalibEmc_Pi0.cc