Analysis Software: Acts::AnnealingUtility Class Reference
Acts::AnnealingUtility Class Reference
Implements a deterministic thermodynamic annealing scheme Ref. (1): CERN-THESIS-2010-027.
#include <acts/blob/sPHENIX/Core/include/Acts/Utilities/AnnealingUtility.hpp>
Classes
struct Config
The configuration struct.
struct State
The annealing state Resetting the state is done by just creating a new instance.
Public Member Functions
AnnealingUtility (const Config &cfg=Config())
Constructor.
void anneal (State &state) const
Does the actual annealing step.
double getWeight (State &state, double chi2, const std::vector< double > &allChi2) const
Weight access.
double getWeight (State &state, double chi2) const
Weight access.
Private Attributes
Config m_cfg
Configuration object.
std::vector< double > m_gaussCutTempVec
Detailed Description
Implements a deterministic thermodynamic annealing scheme Ref. (1): CERN-THESIS-2010-027.
Definition at line 19 of file AnnealingUtility.hpp.
View newest version in sPHENIX GitHub at line 19 of file AnnealingUtility.hpp
Constructor & Destructor Documentation
Acts::AnnealingUtility::AnnealingUtility (const Config & cfg = Config()) inline
Constructor.
Definition at line 44 of file AnnealingUtility.hpp.
View newest version in sPHENIX GitHub at line 44 of file AnnealingUtility.hpp
References cfg, and m_gaussCutTempVec.
Member Function Documentation
void Acts::AnnealingUtility::anneal (State & state) const
Does the actual annealing step.
Definition at line 28 of file AnnealingUtility.cpp.
View newest version in sPHENIX GitHub at line 28 of file AnnealingUtility.cpp
References Acts::AnnealingUtility::State::currentTemperatureIndex, Acts::AnnealingUtility::State::equilibriumReached, m_cfg, and Acts::AnnealingUtility::Config::setOfTemperatures.
Referenced by Acts::Test::BOOST_AUTO_TEST_CASE().
double Acts::AnnealingUtility::getWeight (State & state, double chi2, const std::vector< double > & allChi2) const
Weight access.
Parameters
state The state object
chi2 Chi^2 for e.g. current track, i.e. compatibility of track to current vertex candidate
allChi2 Vector of all chi^2 values, i.e. e.g. compatibilities of current track to all vertices it is currently attached to
Returns
Calculated weight according to Eq.(5.46) in Ref.(1)
Definition at line 36 of file AnnealingUtility.cpp.
View newest version in sPHENIX GitHub at line 36 of file AnnealingUtility.cpp
References Acts::AnnealingUtility::State::currentTemperatureIndex, ambiguity_solver_full_chain::idx, and m_cfg().
Referenced by Acts::Test::BOOST_AUTO_TEST_CASE().
double Acts::AnnealingUtility::getWeight (State & state, double chi2) const
Weight access.
Parameters
state The state object
chi2 Chi^2
Returns
Calculated weight
Definition at line 53 of file AnnealingUtility.cpp.
View newest version in sPHENIX GitHub at line 53 of file AnnealingUtility.cpp
References Acts::AnnealingUtility::State::currentTemperatureIndex, and m_cfg().
Member Data Documentation
Config Acts::AnnealingUtility::m_cfg private
Configuration object.
Definition at line 76 of file AnnealingUtility.hpp.
View newest version in sPHENIX GitHub at line 76 of file AnnealingUtility.hpp
Referenced by anneal().
std::vector<double> Acts::AnnealingUtility::m_gaussCutTempVec private
Definition at line 80 of file AnnealingUtility.hpp.
View newest version in sPHENIX GitHub at line 80 of file AnnealingUtility.hpp
Referenced by AnnealingUtility().
The documentation for this class was generated from the following files:
acts/blob/sPHENIX/Core/include/Acts/Utilities/AnnealingUtility.hpp
acts/blob/sPHENIX/Core/src/Utilities/AnnealingUtility.cpp