Analysis Software: macros/blob/master/common/G4_Input.C File Reference
G4_Input.C File Reference
#include <GlobalVariables.C>
#include <G4_TrkrVariables.C>
#include <phpythia6/PHPythia6.h>
#include <phpythia8/PHPythia8.h>
#include <g4main/CosmicSpray.h>
#include <g4main/HepMCNodeReader.h>
#include <g4main/PHG4IonGun.h>
#include <g4main/PHG4ParticleGenerator.h>
#include <g4main/PHG4ParticleGeneratorD0.h>
#include <g4main/PHG4ParticleGeneratorVectorMeson.h>
#include <g4main/PHG4ParticleGun.h>
#include <g4main/PHG4SimpleEventGenerator.h>
#include <g4main/ReadEICFiles.h>
#include <fermimotionafterburner/FermimotionAfterburner.h>
#include <hijingflipafterburner/HIJINGFlipAfterburner.h>
#include <reactionplaneafterburner/ReactionPlaneAfterburner.h>
#include <phhepmc/Fun4AllHepMCInputManager.h>
#include <phhepmc/Fun4AllHepMCPileupInputManager.h>
#include <phhepmc/HepMCFlowAfterBurner.h>
#include <phhepmc/PHHepMCGenHelper.h>
#include <fun4all/Fun4AllDstInputManager.h>
#include <fun4all/Fun4AllDummyInputManager.h>
#include <fun4all/Fun4AllInputManager.h>
#include <fun4all/Fun4AllNoSyncDstInputManager.h>
#include <fun4all/Fun4AllServer.h>
#include <set>
Namespaces
namespace Input
namespace INPUTHEPMC
namespace INPUTREADEIC
namespace INPUTREADHITS
namespace INPUTEMBED
namespace PYTHIA6
namespace PYTHIA8
namespace PILEUP
namespace INPUTGENERATOR
namespace INPUTMANAGER
Macros
#define MACRO_G4INPUT_C
Functions
void Input::ApplysPHENIXBeamParameter (PHHepMCGenHelper *HepMCGen, const Input::BeamConfiguration &beam_config)
void Input::ApplysPHENIXBeamParameter (PHHepMCGenHelper *HepMCGen)
void Input::ApplyEICBeamParameter (PHHepMCGenHelper *HepMCGen)
void InputInit ()
void InputRegister ()
void InputManagers ()
Variables
bool Input::PYTHIA6 = false
int Input::PYTHIA6_EmbedId = 0
bool Input::PYTHIA8 = false
int Input::PYTHIA8_EmbedId = 0
bool Input::DZERO = false
int Input::DZERO_NUMBER = 1
int Input::DZERO_VERBOSITY = 0
std::set< int > Input::DZERO_EmbedIds
bool Input::GUN = false
int Input::GUN_NUMBER = 1
int Input::GUN_VERBOSITY = 0
std::set< int > Input::GUN_EmbedIds
bool Input::IONGUN = false
int Input::IONGUN_NUMBER = 1
int Input::IONGUN_VERBOSITY = 0
std::set< int > Input::IONGUN_EmbedIds
bool Input::PGEN = false
int Input::PGEN_NUMBER = 1
int Input::PGEN_VERBOSITY = 0
std::set< int > Input::PGEN_EmbedIds
bool Input::SIMPLE = false
int Input::SIMPLE_NUMBER = 1
int Input::SIMPLE_VERBOSITY = 0
int Input::UPSILON_NUMBER = 1
int Input::UPSILON_VERBOSITY = 0
double Input::PILEUPRATE = 0.
bool Input::READHITS = false
int Input::VERBOSITY = 0
int Input::EmbedId = 1
bool Input::COSMIC = false
double Input::COSMIC_R = 650.
string INPUTHEPMC::filename
string INPUTHEPMC::listfile
bool INPUTHEPMC::FLOW = false
int INPUTHEPMC::FLOW_VERBOSITY = 0
bool INPUTHEPMC::FERMIMOTION = false
bool INPUTHEPMC::HIJINGFLIP = false
bool INPUTHEPMC::REACTIONPLANERAND = false
string INPUTREADEIC::filename
map< unsigned int, std::string > INPUTREADHITS::filename
map< unsigned int, std::string > INPUTREADHITS::listfile
map< unsigned int, std::string > INPUTEMBED::filename
map< unsigned int, std::string > INPUTEMBED::listfile
bool INPUTEMBED::REPEAT = true
string PYTHIA6::config_file = string(getenv("CALIBRATIONROOT")) + "/Generators/phpythia6.cfg"
string PYTHIA8::config_file = string(getenv("CALIBRATIONROOT")) + "/Generators/phpythia8.cfg"
string PILEUP::pileupfile = "/sphenix/sim/sim01/sphnxpro/MDC1/sHijing_HepMC/data/sHijing_0_20fm-0000000001-00000.dat"
double PILEUP::TpcDriftVelocity = G4TPC::tpc_drift_velocity_sim
std::vector< PHG4IonGun * > INPUTGENERATOR::IonGun
std::vector
< PHG4ParticleGenerator * > INPUTGENERATOR::ParticleGenerator
std::vector
< PHG4ParticleGeneratorD0 * > INPUTGENERATOR::DZeroMesonGenerator
std::vector
< PHG4ParticleGeneratorVectorMeson * > INPUTGENERATOR::VectorMesonGenerator
std::vector
< PHG4SimpleEventGenerator * > INPUTGENERATOR::SimpleEventGenerator
std::vector< PHG4ParticleGun * > INPUTGENERATOR::Gun
PHPythia6 * INPUTGENERATOR::Pythia6 = nullptr
PHPythia8 * INPUTGENERATOR::Pythia8 = nullptr
ReadEICFiles * INPUTGENERATOR::EICFileReader = nullptr
CosmicSpray * INPUTGENERATOR::Cosmic = nullptr
Fun4AllHepMCInputManager * INPUTMANAGER::HepMCInputManager = nullptr
Fun4AllHepMCPileupInputManager * INPUTMANAGER::HepMCPileupInputManager = nullptr
Macro Definition Documentation
#define MACRO_G4INPUT_C
Definition at line 2 of file G4_Input.C.
View newest version in sPHENIX GitHub at line 2 of file G4_Input.C
Function Documentation
void InputInit ()
Definition at line 285 of file G4_Input.C.
View newest version in sPHENIX GitHub at line 285 of file G4_Input.C
References PYTHIA6::config_file, PYTHIA8::config_file, Input::DZERO, Input::DZERO_EmbedIds, Input::DZERO_NUMBER, INPUTGENERATOR::DZeroMesonGenerator, Input::EMBED, PHG4ParticleGeneratorBase::Embed(), Input::EmbedId, INPUTHEPMC::FLOW, Input::GUN, INPUTGENERATOR::Gun, Input::GUN_EmbedIds, Input::GUN_NUMBER, Input::HEPMC, INPUTMANAGER::HepMCInputManager, INPUTMANAGER::HepMCPileupInputManager, i, Fun4AllServer::instance(), Input::IONGUN, INPUTGENERATOR::IonGun, Input::IONGUN_EmbedIds, Input::IONGUN_NUMBER, perf_headwind::name, INPUTGENERATOR::ParticleGenerator, Input::PGEN, Input::PGEN_EmbedIds, Input::PGEN_NUMBER, Input::PILEUPRATE, Input::PYTHIA6, INPUTGENERATOR::Pythia6, Input::PYTHIA6_EmbedId, Input::PYTHIA8, INPUTGENERATOR::Pythia8, Input::PYTHIA8_EmbedId, Input::READHITS, PHPythia6::set_config_file(), PHPythia8::set_config_file(), PHHepMCGenHelper::set_embedding_id(), PHPythia6::set_embedding_id(), Input::SIMPLE, Input::SIMPLE_NUMBER, INPUTGENERATOR::SimpleEventGenerator, to_string(), Input::UPSILON, Input::UPSILON_EmbedIds, Input::UPSILON_NUMBER, and INPUTGENERATOR::VectorMesonGenerator.
Referenced by Fun4All_AnaTutorial_sPHENIX(), Fun4All_AnaTutorial_sPHENIX_Jets(), Fun4All_BHG(), Fun4All_G4_Calo(), Fun4All_G4_EICDetector_AnaTutorial(), Fun4All_G4_sPHENIX(), Fun4All_G4_sPHENIX_ForTrackCutStudy(), Fun4All_G4_sPHENIX_ForTrackCutStudy_EmbedScanOff(), Fun4All_G4_sPHENIX_ForTrackCutStudy_EmbedScanOn(), Fun4All_G4_sPHENIX_ForTrackCutStudy_WithPileup_EmbedScanOff(), Fun4All_G4_sPHENIX_ForTrackCutStudy_WithPileup_EmbedScanOn(), Fun4All_HCalJetPhiShift(), Fun4All_Pi0Gen_sPHENIX(), Fun4All_pi0tbt_SIMPLE_EMBED(), Fun4All_RunNewTruthMatcher(), Fun4All_SinglePhotonGen_sPHENIX(), Fun4All_SinglePi0Gen_sPHENIX(), Fun4AllPythia(), run_calo_fromMDC2Hits_towslope_Fun4All_G4_Calo(), rundst_spiNo(), and spiNo2().
void InputManagers ()
Definition at line 542 of file G4_Input.C.
View newest version in sPHENIX GitHub at line 542 of file G4_Input.C
References Fun4AllInputManager::AddFile(), Fun4AllInputManager::AddListFile(), parse_cmake_options::begin, Input::EMBED, INPUTHEPMC::filename, INPUTREADHITS::filename, INPUTEMBED::filename, Fun4AllInputManager::fileopen(), Fun4AllHepMCInputManager::fileopen(), Input::HEPMC, INPUTMANAGER::HepMCInputManager, INPUTMANAGER::HepMCPileupInputManager, in, Fun4AllServer::instance(), INPUTHEPMC::listfile, INPUTREADHITS::listfile, INPUTEMBED::listfile, PILEUP::pileupfile, Input::PILEUPRATE, TRACKING::pp_extended_readout_time, TRACKING::pp_mode, Input::READHITS, Fun4AllServer::registerInputManager(), Fun4AllInputManager::Repeat(), INPUTEMBED::REPEAT, Fun4AllHepMCPileupInputManager::set_collision_rate(), Fun4AllHepMCPileupInputManager::set_time_window(), Fun4AllHepMCPileupInputManager::SignalInputManager(), to_string(), PILEUP::TpcDriftVelocity, Fun4AllBase::Verbosity(), and Input::VERBOSITY.
Referenced by Fun4All_AnaTutorial_sPHENIX(), Fun4All_AnaTutorial_sPHENIX_Jets(), Fun4All_G4_Calo(), Fun4All_G4_EICDetector_AnaTutorial(), Fun4All_G4_sPHENIX(), Fun4All_G4_sPHENIX_ForTrackCutStudy(), Fun4All_G4_sPHENIX_ForTrackCutStudy_EmbedScanOff(), Fun4All_G4_sPHENIX_ForTrackCutStudy_EmbedScanOn(), Fun4All_G4_sPHENIX_ForTrackCutStudy_WithPileup_EmbedScanOff(), Fun4All_G4_sPHENIX_ForTrackCutStudy_WithPileup_EmbedScanOn(), Fun4All_HCalJetPhiShift(), Fun4All_Pi0Gen_sPHENIX(), Fun4All_pi0tbt_SIMPLE_EMBED(), Fun4All_ReadDST_TPCML(), Fun4All_RunNewTruthMatcher(), Fun4All_SinglePhotonGen_sPHENIX(), Fun4All_SinglePi0Gen_sPHENIX(), Fun4AllPythia(), run_calo_fromMDC2Hits_towslope_Fun4All_G4_Calo(), rundst_spiNo(), and spiNo2().
void InputRegister ()
Definition at line 424 of file G4_Input.C.
View newest version in sPHENIX GitHub at line 424 of file G4_Input.C
References Input::COSMIC, INPUTGENERATOR::Cosmic, Input::COSMIC_R, Input::DZERO, Input::DZERO_VERBOSITY, INPUTGENERATOR::DZeroMesonGenerator, INPUTGENERATOR::EICFileReader, INPUTHEPMC::FERMIMOTION, INPUTREADEIC::filename, INPUTHEPMC::FLOW, INPUTHEPMC::FLOW_VERBOSITY, Input::GUN, INPUTGENERATOR::Gun, Input::GUN_VERBOSITY, Input::HEPMC, INPUTHEPMC::HIJINGFLIP, Fun4AllServer::instance(), Input::IONGUN, INPUTGENERATOR::IonGun, Input::IONGUN_VERBOSITY, ReadEICFiles::OpenInputFile(), INPUTGENERATOR::ParticleGenerator, Input::PGEN, Input::PGEN_VERBOSITY, Input::PYTHIA6, INPUTGENERATOR::Pythia6, Input::PYTHIA8, INPUTGENERATOR::Pythia8, INPUTHEPMC::REACTIONPLANERAND, Input::READEIC, Fun4AllServer::registerSubsystem(), Input::SIMPLE, Input::SIMPLE_VERBOSITY, INPUTGENERATOR::SimpleEventGenerator, Input::UPSILON, Input::UPSILON_VERBOSITY, INPUTGENERATOR::VectorMesonGenerator, verbosity, Fun4AllBase::Verbosity(), and Input::VERBOSITY.
Referenced by Fun4All_AnaTutorial_sPHENIX(), Fun4All_AnaTutorial_sPHENIX_Jets(), Fun4All_BHG(), Fun4All_G4_Calo(), Fun4All_G4_EICDetector_AnaTutorial(), Fun4All_G4_sPHENIX(), Fun4All_G4_sPHENIX_ForTrackCutStudy(), Fun4All_G4_sPHENIX_ForTrackCutStudy_EmbedScanOff(), Fun4All_G4_sPHENIX_ForTrackCutStudy_EmbedScanOn(), Fun4All_G4_sPHENIX_ForTrackCutStudy_WithPileup_EmbedScanOff(), Fun4All_G4_sPHENIX_ForTrackCutStudy_WithPileup_EmbedScanOn(), Fun4All_HCalJetPhiShift(), Fun4All_Pi0Gen_sPHENIX(), Fun4All_pi0tbt_SIMPLE_EMBED(), Fun4All_RunNewTruthMatcher(), Fun4All_SinglePhotonGen_sPHENIX(), Fun4All_SinglePi0Gen_sPHENIX(), Fun4AllPythia(), run_calo_fromMDC2Hits_towslope_Fun4All_G4_Calo(), rundst_spiNo(), and spiNo2().