Analysis Software: cpp.ast.TypeConverter Class Reference
cpp.ast.TypeConverter Class Reference
Public Member Functions
def __init__
def ToType
def DeclarationToParts
def ToParameters
def CreateReturnType
def GetTemplateIndices
Public Attributes
namespace_stack
Private Member Functions
def _GetTemplateEnd
Detailed Description
Definition at line 458 of file ast.py.
View newest version in sPHENIX GitHub at line 458 of file ast.py
Constructor & Destructor Documentation
def cpp.ast.TypeConverter.__init__ (self, namespace_stack)
Definition at line 460 of file ast.py.
View newest version in sPHENIX GitHub at line 460 of file ast.py
Member Function Documentation
def cpp.ast.TypeConverter._GetTemplateEnd (self, tokens, start) private
Definition at line 463 of file ast.py.
View newest version in sPHENIX GitHub at line 463 of file ast.py
Referenced by cpp.ast.TypeConverter.DeclarationToParts(), and cpp.ast.TypeConverter.ToType().
def cpp.ast.TypeConverter.CreateReturnType (self, return_type_seq)
Definition at line 652 of file ast.py.
View newest version in sPHENIX GitHub at line 652 of file ast.py
References cpp.ast.TypeConverter.DeclarationToParts().
def cpp.ast.TypeConverter.DeclarationToParts (self, parts, needs_name_removed)
Definition at line 536 of file ast.py.
View newest version in sPHENIX GitHub at line 536 of file ast.py
References cpp.ast.TypeConverter._GetTemplateEnd(), Acts.enumerate(), join(), and cpp.ast.TypeConverter.ToType().
Referenced by cpp.ast.TypeConverter.CreateReturnType(), and cpp.ast.TypeConverter.ToParameters().
def cpp.ast.TypeConverter.GetTemplateIndices (self, names)
Definition at line 666 of file ast.py.
View newest version in sPHENIX GitHub at line 666 of file ast.py
def cpp.ast.TypeConverter.ToParameters (self, tokens)
Definition at line 591 of file ast.py.
View newest version in sPHENIX GitHub at line 591 of file ast.py
References cpp.ast.TypeConverter.DeclarationToParts().
def cpp.ast.TypeConverter.ToType (self, tokens)
Convert [Token,...] to [Class(...), ] useful for base classes.
For example, code like class Foo : public Bar<x, y> { ... };
the "Bar<x, y>" portion gets converted to an AST.
Returns:
  [Class(...), ...]
Definition at line 477 of file ast.py.
View newest version in sPHENIX GitHub at line 477 of file ast.py
References cpp.ast.TypeConverter._GetTemplateEnd(), join(), and cpp.ast.TypeConverter.ToType().
Referenced by cpp.ast.TypeConverter.DeclarationToParts(), and cpp.ast.TypeConverter.ToType().
Member Data Documentation
cpp.ast.TypeConverter.namespace_stack
Definition at line 461 of file ast.py.
View newest version in sPHENIX GitHub at line 461 of file ast.py
Referenced by cpp.ast.AstBuilder._CreateVariable(), cpp.ast.AstBuilder._GetClass(), cpp.ast.AstBuilder._GetMethod(), cpp.ast.AstBuilder.handle_friend(), and cpp.ast.AstBuilder.handle_typedef().
The documentation for this class was generated from the following file:
JETSCAPE/blob/main/external_packages/googletest/googlemock/scripts/generator/cpp/ast.py