Analysis Software: OnlMon/blob/main/macros/CommonFuncs.C File Reference
CommonFuncs.C File Reference
#include <onlmon/OnlMonClient.h>
Macros
#define MACROS_COMMONFUNCS_C
Functions
void CreateHostList (const int online=0)
void CleanUpClient ()
void ClearCanvases ()
Macro Definition Documentation
#define MACROS_COMMONFUNCS_C
Definition at line 2 of file CommonFuncs.C.
View newest version in sPHENIX GitHub at line 2 of file CommonFuncs.C
Function Documentation
void CleanUpClient ()
Definition at line 47 of file CommonFuncs.C.
View newest version in sPHENIX GitHub at line 47 of file CommonFuncs.C
References OnlMonClient::instance().
void ClearCanvases ()
Definition at line 55 of file CommonFuncs.C.
View newest version in sPHENIX GitHub at line 55 of file CommonFuncs.C
void CreateHostList (const int online = 0)
Definition at line 6 of file CommonFuncs.C.
View newest version in sPHENIX GitHub at line 6 of file CommonFuncs.C
References OnlMonClient::AddServerHost(), f, i, OnlMonClient::instance(), and to_string().
Referenced by bbcDrawInit(), cemcDrawInit(), daqDrawInit(), exampleDrawInit(), ihcalDrawInit(), inttDrawInit(), ll1DrawInit(), mvtxDrawInit(), ohcalDrawInit(), sepdDrawInit(), tpcDrawInit(), tpotDrawInit(), and zdcDrawInit().