Analysis Software: cl::detail Namespace Reference
cl::detail Namespace Reference
Classes
struct GetInfoHelper
struct GetInfoHelper< Func, VECTOR_CLASS< T > >
struct GetInfoHelper< Func, VECTOR_CLASS< char * > >
struct GetInfoHelper< Func, STRING_CLASS >
struct param_traits
struct GetInfoFunctor0
struct GetInfoFunctor1
struct ReferenceHandler
struct ReferenceHandler< cl_device_id >
struct ReferenceHandler< cl_platform_id >
struct ReferenceHandler< cl_context >
struct ReferenceHandler< cl_command_queue >
struct ReferenceHandler< cl_mem >
struct ReferenceHandler< cl_sampler >
struct ReferenceHandler< cl_program >
struct ReferenceHandler< cl_kernel >
struct ReferenceHandler< cl_event >
class Wrapper
struct KernelArgumentHandler
struct KernelArgumentHandler< LocalSpaceArg >
Functions
__PARAM_NAME_INFO_1_0 (__DECLARE_PARAM_TRAITS)
template<typename Func , typename T >
cl_int getInfo (Func f, cl_uint name, T *param)
template<typename Func , typename Arg0 , typename T >
cl_int getInfo (Func f, const Arg0 &arg0, cl_uint name, T *param)
template<typename Func , typename Arg0 , typename Arg1 , typename T >
cl_int getInfo (Func f, const Arg0 &arg0, const Arg1 &arg1, cl_uint name, T *param)
static cl_int errHandler (cl_int err, const char *errStr=NULL)
Function Documentation
cl::detail::__PARAM_NAME_INFO_1_0 (__DECLARE_PARAM_TRAITS)
static cl_int cl::detail::errHandler (cl_int err, const char * errStr = NULL) inline static
Definition at line 1148 of file cl.hpp.
View newest version in sPHENIX GitHub at line 1148 of file cl.hpp
References check_license::err().
Referenced by cl::Buffer::Buffer(), cl::BufferGL::BufferGL(), cl::BufferRenderGL::BufferRenderGL(), cl::Program::build(), cl::CommandQueue::CommandQueue(), cl::Context::Context(), cl::Program::createKernels(), cl::CommandQueue::enqueueAcquireGLObjects(), cl::CommandQueue::enqueueBarrier(), cl::CommandQueue::enqueueCopyBuffer(), cl::CommandQueue::enqueueCopyBufferToImage(), cl::CommandQueue::enqueueCopyImage(), cl::CommandQueue::enqueueCopyImageToBuffer(), cl::CommandQueue::enqueueMapBuffer(), cl::CommandQueue::enqueueMapImage(), cl::CommandQueue::enqueueMarker(), cl::CommandQueue::enqueueNativeKernel(), cl::CommandQueue::enqueueNDRangeKernel(), cl::CommandQueue::enqueueReadBuffer(), cl::CommandQueue::enqueueReadImage(), cl::CommandQueue::enqueueReleaseGLObjects(), cl::CommandQueue::enqueueTask(), cl::CommandQueue::enqueueUnmapMemObject(), cl::CommandQueue::enqueueWaitForEvents(), cl::CommandQueue::enqueueWriteBuffer(), cl::CommandQueue::enqueueWriteImage(), cl::CommandQueue::finish(), cl::CommandQueue::flush(), cl::Platform::get(), cl::Program::getBuildInfo(), cl::Platform::getDevices(), cl::Image::getImageInfo(), cl::Device::getInfo(), cl::Platform::getInfo(), cl::Context::getInfo(), cl::Event::getInfo(), cl::Memory::getInfo(), cl::Sampler::getInfo(), cl::Kernel::getInfo(), cl::Program::getInfo(), cl::CommandQueue::getInfo(), cl::BufferGL::getObjectInfo(), cl::BufferRenderGL::getObjectInfo(), cl::Event::getProfilingInfo(), cl::Context::getSupportedImageFormats(), cl::Kernel::getWorkGroupInfo(), cl::Image2D::Image2D(), cl::Image2DGL::Image2DGL(), cl::Image3D::Image3D(), cl::Image3DGL::Image3DGL(), cl::Kernel::Kernel(), cl::Program::Program(), cl::Sampler::Sampler(), cl::Kernel::setArg(), cl::Event::wait(), cl::Event::waitForEvents(), and cl::WaitForEvents().
template<typename Func , typename T > cl_int cl::detail::getInfo (Func f, cl_uint name, T * param) inline
Definition at line 959 of file cl.hpp.
View newest version in sPHENIX GitHub at line 959 of file cl.hpp
References cl::detail::GetInfoHelper< Functor, T >::get().
Referenced by cl::Program::getBuildInfo(), cl::Image::getImageInfo(), cl::Device::getInfo(), cl::Platform::getInfo(), cl::Context::getInfo(), cl::Event::getInfo(), cl::Memory::getInfo(), cl::Sampler::getInfo(), cl::Kernel::getInfo(), cl::Program::getInfo(), cl::CommandQueue::getInfo(), cl::Event::getProfilingInfo(), and cl::Kernel::getWorkGroupInfo().
template<typename Func , typename Arg0 , typename T > cl_int cl::detail::getInfo (Func f, const Arg0 & arg0, cl_uint name, T * param) inline
Definition at line 984 of file cl.hpp.
View newest version in sPHENIX GitHub at line 984 of file cl.hpp
References f, and Acts::UnitConstants::T.
template<typename Func , typename Arg0 , typename Arg1 , typename T > cl_int cl::detail::getInfo (Func f, const Arg0 & arg0, const Arg1 & arg1, cl_uint name, T * param) inline
Definition at line 993 of file cl.hpp.
View newest version in sPHENIX GitHub at line 993 of file cl.hpp
References f, and Acts::UnitConstants::T.