Analysis Software: SColdQcdCorrelatorAnalysis::SCorrelatorJetTree Class Reference
SColdQcdCorrelatorAnalysis::SCorrelatorJetTree Class Reference
#include <analysis/blob/master/AndersonAnalysisModules/ColdQcdCorrelatorAnalysis/SCorrelatorJetTree/src/SCorrelatorJetTree.h>
Public Types
enum ALGO { ANTIKT = 0, KT = 1, CAMBRIDGE = 2 }
enum RECOMB {
E_SCHEME = 0, PT_SCHEME = 1, PT2_SCHEME = 2, ET_SCHEME = 3,
ET2_SCHEME = 4
}
Public Member Functions
SCorrelatorJetTree (const string &name="SCorrelatorJetTree", const string &outFile="correlator_jet_tree.root", const bool isMC=false, const bool isEmbed=false, const bool debug=false)
~SCorrelatorJetTree () override
int Init (PHCompositeNode *) override
int process_event (PHCompositeNode *) override
int End (PHCompositeNode *) override
Called at the end of all processing.
void SetAddTracks (const bool addTracks)
void SetAddFlow (const bool addFlow)
void SetAddECal (const bool addECal)
void SetAddHCal (const bool addHCal)
void SetDoVertexCut (const bool doVtx)
void SetDoQualityPlots (const bool doQA)
void SetRequireSiSeeds (const bool require)
void SetUseOnlyPrimVtx (const bool primary)
void SetMaskTpcSectors (const bool mask)
void SetCheckWeirdTrks (const bool check)
void SetSaveDST (const bool doSave)
void SetIsMC (const bool isMC)
void SetIsEmbed (const bool isEmbed)
void SetJetR (const double jetR)
void SetJetType (const uint32_t type)
void SetJetTreeName (const string name)
void SetEvtVzRange (const pair< double, double > vzRange)
void SetEvtVrRange (const pair< double, double > vrRange)
void SetParPtRange (const pair< double, double > ptRange)
void SetParEtaRange (const pair< double, double > etaRange)
void SetTrackPtRange (const pair< double, double > ptRange)
void SetTrackEtaRange (const pair< double, double > etaRange)
void SetTrackQualityRange (const pair< double, double > qualRange)
void SetTrackNMvtxRange (const pair< double, double > nMvtxRange)
void SetTrackNInttRange (const pair< double, double > nInttRange)
void SetTrackNTpcRange (const pair< double, double > nTpcRange)
void SetTrackDcaRangeXY (const pair< double, double > dcaRangeXY)
void SetTrackDcaRangeZ (const pair< double, double > dcaRangeZ)
void SetTrackDeltaPtRange (const pair< double, double > deltaPtRange)
void SetTrackDcaSigmaParameters (const bool doDcaSigmaCut, const pair< double, double > ptFitMax, const pair< double, double > nSigma, const vector< double > paramDcaXY, const vector< double > paramDcaZ)
void SetFlowPtRange (const pair< double, double > ptRange)
void SetFlowEtaRange (const pair< double, double > etaRange)
void SetECalPtRange (const pair< double, double > ptRange)
void SetECalEtaRange (const pair< double, double > etaRange)
void SetHCalPtRange (const pair< double, double > ptRange)
void SetHCalEtaRange (const pair< double, double > etaRange)
void SetJetAlgo (const ALGO jetAlgo)
void SetRecombScheme (const RECOMB recombScheme)
void SetJetParameters (const double rJet, const uint32_t jetType, const ALGO jetAlgo, const RECOMB recombScheme)
bool GetDoVtxCut ()
bool GetDoQualityPlots ()
bool GetRequireSiSeeds ()
bool GetUseOnlyPrimVtx ()
bool GetDoDcaSigmaCut ()
bool GetMaskTpcSectors ()
bool GetCheckWeirdTrks ()
bool GetSaveDST ()
bool GetIsMC ()
bool GetIsEmbed ()
bool GetDoDebug ()
bool GetAddTracks ()
bool GetAddFlow ()
bool GetAddECal ()
bool GetAddHCal ()
string GetJetTreeName ()
double GetEvtMinVz ()
double GetEvtMaxVz ()
double GetEvtMinVr ()
double GetEvtMaxVr ()
double GetParMinPt ()
double GetParMaxPt ()
double GetParMinEta ()
double GetParMaxEta ()
double GetTrackMinPt ()
double GetTrackMaxPt ()
double GetTrackMinEta ()
double GetTrackMaxEta ()
double GetTrackMinQual ()
double GetTrackMaxQual ()
double GetTrackMinNMvtx ()
double GetTrackMaxNMvtx ()
double GetTrackMinNIntt ()
double GetTrackMaxNIntt ()
double GetTrackMinNTpc ()
double GetTrackMaxNTpc ()
double GetTrackMinDcaXY ()
double GetTrackMaxDcaXY ()
double GetTrackMinDcaZ ()
double GetTrackMaxDcaZ ()
double GetTrackMinDeltaPt ()
double GetTrackMaxDeltaPt ()
double GetFlowMinPt ()
double GetFlowMaxPt ()
double GetFlowMinEta ()
double GetFlowMaxEta ()
double GetECalMinPt ()
double GetECalMaxPt ()
double GetECalMinEta ()
double GetECalMaxEta ()
double GetHCalMinPt ()
double GetHCalMaxPt ()
double GetHCalMinEta ()
double GetHCalMaxEta ()
double GetJetR ()
uint32_t GetJetType ()
JetAlgorithm GetJetAlgo ()
RecombinationScheme GetRecombScheme ()
Public Member Functions inherited from SubsysReco
~SubsysReco () override
virtual int EndRun (const int)
Called at the end of each run.
virtual int InitRun (PHCompositeNode *)
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
void Print (const std::string &="ALL") const override
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Private Types
enum CONST {
NPart = 2, NComp = 3, NParam = 4, NRange = 2,
NMoment = 2, NInfoQA = 9, NJetType = 2, NCstType = 5,
NObjType = 9, NDirectory = 6, NMvtxLayer = 3, NInttLayer = 8,
NTpcLayer = 48, NTpcSector = 12
}
enum SUBSYS { MVTX, INTT, TPC }
enum CST_TYPE {
PART_CST, TRACK_CST, FLOW_CST, ECAL_CST,
HCAL_CST
}
enum OBJECT {
TRACK, ECLUST, HCLUST, FLOW,
PART, TJET, RJET, TCST,
RCST
}
enum INFO {
PT, ETA, PHI, ENE,
QUAL, DCAXY, DCAZ, DELTAPT,
NTPC
}
Private Member Functions
bool IsGoodVertex (const CLHEP::Hep3Vector vtx)
void GetEventVariables (PHCompositeNode *topNode)
void GetPartonInfo (PHCompositeNode *topNode)
long GetNumTrks (PHCompositeNode *topNode)
long GetNumChrgPars (PHCompositeNode *topNode)
double GetSumECalEne (PHCompositeNode *topNode)
double GetSumHCalEne (PHCompositeNode *topNode)
double GetSumParEne (PHCompositeNode *topNode)
CLHEP::Hep3Vector GetRecoVtx (PHCompositeNode *topNode)
void FindTrueJets (PHCompositeNode *topNode)
void FindRecoJets (PHCompositeNode *topNode)
void AddParticles (PHCompositeNode *topNode, vector< PseudoJet > &particles, map< int, pair< Jet::SRC, int >> &fjMap)
void AddTracks (PHCompositeNode *topNode, vector< PseudoJet > &particles, map< int, pair< Jet::SRC, int >> &fjMap)
void AddFlow (PHCompositeNode *topNode, vector< PseudoJet > &particles, map< int, pair< Jet::SRC, int >> &fjMap)
void AddECal (PHCompositeNode *topNode, vector< PseudoJet > &particles, map< int, pair< Jet::SRC, int >> &fjMap)
void AddHCal (PHCompositeNode *topNode, vector< PseudoJet > &particles, map< int, pair< Jet::SRC, int >> &fjMap)
bool IsGoodParticle (HepMC::GenParticle *par, const bool ignoreCharge=false)
bool IsGoodTrack (SvtxTrack *track, PHCompositeNode *topNode)
bool IsGoodFlow (ParticleFlowElement *flow)
bool IsGoodECal (CLHEP::Hep3Vector &hepVecECal)
bool IsGoodHCal (CLHEP::Hep3Vector &hepVecHCal)
bool IsGoodTrackSeed (SvtxTrack *track)
bool IsGoodTrackPhi (SvtxTrack *track, const float phiMaskSize=0.01)
bool IsFromPrimaryVtx (SvtxTrack *track, PHCompositeNode *topNode)
bool IsOutgoingParton (HepMC::GenParticle *par)
pair< double, double > GetTrackDcaPair (SvtxTrack *track, PHCompositeNode *topNode)
CLHEP::Hep3Vector GetTrackVertex (SvtxTrack *track, PHCompositeNode *topNode)
double GetTrackDeltaPt (SvtxTrack *track)
float GetParticleCharge (const int pid)
int GetNumLayer (SvtxTrack *track, const uint8_t subsys=0)
int GetNumClust (SvtxTrack *track, const uint8_t subsys=0)
int GetMatchID (SvtxTrack *track)
void InitVariables ()
void InitHists ()
void InitTuples ()
void InitTrees ()
void InitFuncs ()
void InitEvals (PHCompositeNode *topNode)
void FillTrueTree ()
void FillRecoTree ()
void SaveOutput ()
void ResetVariables ()
void DetermineEvtsToGrab (PHCompositeNode *topNode)
int CreateJetNode (PHCompositeNode *topNode)
int GetEmbedID (PHCompositeNode *topNode, const int iEvtToGrab=1)
SvtxTrackMap * GetTrackMap (PHCompositeNode *topNode)
GlobalVertex * GetGlobalVertex (PHCompositeNode *topNode, const int iVtxToGrab=-1)
GlobalVertexMap * GetVertexMap (PHCompositeNode *topNode)
HepMC::GenEvent * GetMcEvent (PHCompositeNode *topNode, const int iEvtToGrab=1)
RawClusterContainer * GetClusterStore (PHCompositeNode *topNode, const TString sNodeName)
ParticleFlowElementContainer * GetFlowStore (PHCompositeNode *topNode)
Private Attributes
Fun4AllHistoManager * m_histMan = NULL
SvtxEvalStack * m_evalStack = NULL
SvtxTrackEval * m_trackEval = NULL
TFile * m_outFile = NULL
TTree * m_recoTree = NULL
TTree * m_trueTree = NULL
string m_outFileName = ""
string m_jetTreeName = ""
JetMapv1 * m_recoJetMap = NULL
JetMapv1 * m_trueJetMap = NULL
bool isMvtxLayerHit [CONST::NMvtxLayer] = {false}
bool isInttLayerHit [CONST::NInttLayer] = {false}
bool isTpcLayerHit [CONST::NTpcLayer] = {false}
TH1D * m_hJetArea [CONST::NJetType]
TH1D * m_hJetNumCst [CONST::NJetType]
TH1D * m_hNumObject [CONST::NObjType]
TH1D * m_hSumCstEne [CONST::NCstType]
TH1D * m_hObjectQA [CONST::NObjType][CONST::NInfoQA]
TH1D * m_hNumCstAccept [CONST::NCstType][CONST::NMoment]
TNtuple * m_ntTrkQA = NULL
TNtuple * m_ntWeirdTracks = NULL
bool m_doVtxCut = false
bool m_doQualityPlots = true
bool m_requireSiSeeds = true
bool m_useOnlyPrimVtx = true
bool m_doDcaSigmaCut = false
bool m_maskTpcSectors = false
bool m_saveDST = false
bool m_isMC = true
bool m_isEmbed = false
bool m_doDebug = false
bool m_checkWeirdTrks = false
bool m_addTracks = true
bool m_addFlow = false
bool m_addECal = false
bool m_addHCal = false
vector< int > m_vecEvtsToGrab
map< int, int > m_mapCstToEmbedID
double m_evtVzRange [CONST::NRange] = {-10., 10.}
double m_evtVrRange [CONST::NRange] = {0.0, 0.418}
double m_parPtRange [CONST::NRange] = {0.1, 9999.}
double m_parEtaRange [CONST::NRange] = {-1.1, 1.1}
double m_trkPtRange [CONST::NRange] = {0.1, 100.}
double m_trkEtaRange [CONST::NRange] = {-1.1, 1.1}
double m_trkQualRange [CONST::NRange] = {-1., 10.}
double m_trkNMvtxRange [CONST::NRange] = {2., 100.}
double m_trkNInttRange [CONST::NRange] = {1., 100.}
double m_trkNTpcRange [CONST::NRange] = {25., 100.}
double m_trkDcaRangeXY [CONST::NRange] = {-5., 5.}
double m_trkDcaRangeZ [CONST::NRange] = {-5., 5.}
double m_trkDeltaPtRange [CONST::NRange] = {0., 0.5}
double m_flowPtRange [CONST::NRange] = {0., 9999.}
double m_flowEtaRange [CONST::NRange] = {-1.1, 1.1}
double m_ecalPtRange [CONST::NRange] = {0., 9999.}
double m_ecalEtaRange [CONST::NRange] = {-1.1, 1.1}
double m_hcalPtRange [CONST::NRange] = {0., 9999.}
double m_hcalEtaRange [CONST::NRange] = {-1.1, 1.1}
TF1 * m_fSigDcaXY = NULL
TF1 * m_fSigDcaZ = NULL
double m_dcaPtFitMaxXY = 15.
double m_dcaPtFitMaxZ = 15.
double m_nSigCutXY = 1.
double m_nSigCutZ = 1.
array< double, CONST::NParam > m_parSigDcaXY = {1., 1., 1., 1.}
array< double, CONST::NParam > m_parSigDcaZ = {1., 1., 1., 1.}
double m_jetR = 0.4
uint32_t m_jetType = 0
JetAlgorithm m_jetAlgo = antikt_algorithm
JetDefinition * m_trueJetDef = NULL
JetDefinition * m_recoJetDef = NULL
ClusterSequence * m_trueClust = NULL
ClusterSequence * m_recoClust = NULL
RecombinationScheme m_recombScheme = pt_scheme
long long m_partonID [CONST::NPart]
CLHEP::Hep3Vector m_partonMom [CONST::NPart]
CLHEP::Hep3Vector m_trueVtx
CLHEP::Hep3Vector m_recoVtx
vector< PseudoJet > m_trueJets
vector< PseudoJet > m_recoJets
unsigned long m_trueNumJets
long long m_truePartonID [CONST::NPart]
double m_truePartonMomX [CONST::NPart]
double m_truePartonMomY [CONST::NPart]
double m_truePartonMomZ [CONST::NPart]
double m_trueVtxX
double m_trueVtxY
double m_trueVtxZ
double m_trueSumPar
long m_trueNumChrgPars
vector< unsigned long > m_trueJetNCst
vector< unsigned int > m_trueJetID
vector< double > m_trueJetE
vector< double > m_trueJetPt
vector< double > m_trueJetEta
vector< double > m_trueJetPhi
vector< double > m_trueJetArea
vector< vector< int > > m_trueCstID
vector< vector< int > > m_trueCstEmbedID
vector< vector< double > > m_trueCstZ
vector< vector< double > > m_trueCstDr
vector< vector< double > > m_trueCstE
vector< vector< double > > m_trueCstPt
vector< vector< double > > m_trueCstEta
vector< vector< double > > m_trueCstPhi
unsigned long m_recoNumJets
double m_recoVtxX
double m_recoVtxY
double m_recoVtxZ
double m_recoSumECal
double m_recoSumHCal
long m_recoNumTrks
vector< unsigned long > m_recoJetNCst
vector< unsigned int > m_recoJetID
vector< double > m_recoJetE
vector< double > m_recoJetPt
vector< double > m_recoJetEta
vector< double > m_recoJetPhi
vector< double > m_recoJetArea
vector< vector< int > > m_recoCstMatchID
vector< vector< double > > m_recoCstZ
vector< vector< double > > m_recoCstDr
vector< vector< double > > m_recoCstE
vector< vector< double > > m_recoCstPt
vector< vector< double > > m_recoCstEta
vector< vector< double > > m_recoCstPhi
Additional Inherited Members
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Detailed Description
Definition at line 121 of file SCorrelatorJetTree.h.
View newest version in sPHENIX GitHub at line 121 of file SCorrelatorJetTree.h
Member Enumeration Documentation
enum SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::ALGO
Enumerator:
ANTIKT
KT
CAMBRIDGE
Definition at line 126 of file SCorrelatorJetTree.h.
View newest version in sPHENIX GitHub at line 126 of file SCorrelatorJetTree.h
enum SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::CONST private
Enumerator:
NPart
NComp
NParam
NRange
NMoment
NInfoQA
NJetType
NCstType
NObjType
NDirectory
NMvtxLayer
NInttLayer
NTpcLayer
NTpcSector
Definition at line 259 of file SCorrelatorJetTree.h.
View newest version in sPHENIX GitHub at line 259 of file SCorrelatorJetTree.h
enum SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::CST_TYPE private
Enumerator:
PART_CST
TRACK_CST
FLOW_CST
ECAL_CST
HCAL_CST
Definition at line 278 of file SCorrelatorJetTree.h.
View newest version in sPHENIX GitHub at line 278 of file SCorrelatorJetTree.h
enum SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::INFO private
Enumerator:
PT
ETA
PHI
ENE
QUAL
DCAXY
DCAZ
DELTAPT
NTPC
Definition at line 280 of file SCorrelatorJetTree.h.
View newest version in sPHENIX GitHub at line 280 of file SCorrelatorJetTree.h
enum SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::OBJECT private
Enumerator:
TRACK
ECLUST
HCLUST
FLOW
PART
TJET
RJET
TCST
RCST
Definition at line 279 of file SCorrelatorJetTree.h.
View newest version in sPHENIX GitHub at line 279 of file SCorrelatorJetTree.h
enum SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::RECOMB
Enumerator:
E_SCHEME
PT_SCHEME
PT2_SCHEME
ET_SCHEME
ET2_SCHEME
Definition at line 131 of file SCorrelatorJetTree.h.
View newest version in sPHENIX GitHub at line 131 of file SCorrelatorJetTree.h
enum SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::SUBSYS private
Enumerator:
MVTX
INTT
TPC
Definition at line 277 of file SCorrelatorJetTree.h.
View newest version in sPHENIX GitHub at line 277 of file SCorrelatorJetTree.h
Constructor & Destructor Documentation
SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::SCorrelatorJetTree (const string & name = "SCorrelatorJetTree", const string & outFile = "correlator_jet_tree.root", const bool isMC = false, const bool isEmbed = false, const bool debug = false)
Definition at line 32 of file SCorrelatorJetTree.cc.
View newest version in sPHENIX GitHub at line 32 of file SCorrelatorJetTree.cc
References Acts::Test::debug, InitVariables(), m_doDebug, m_isEmbed, m_isMC, and m_outFileName.
SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::~SCorrelatorJetTree () override
Definition at line 48 of file SCorrelatorJetTree.cc.
View newest version in sPHENIX GitHub at line 48 of file SCorrelatorJetTree.cc
References m_doDebug, m_evalStack, m_histMan, m_recoClust, m_recoJetDef, m_trackEval, m_trueClust, and m_trueJetDef.
Member Function Documentation
void SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::AddECal (PHCompositeNode * topNode, vector< PseudoJet > & particles, map< int, pair< Jet::SRC, int >> & fjMap) private
Definition at line 485 of file SCorrelatorJetTree.jet.h.
View newest version in sPHENIX GitHub at line 485 of file SCorrelatorJetTree.jet.h
References Enable::CEMC_CLUSTER, Fill(), SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::GetClusterStore(), RawClusterUtility::GetECoreVec(), SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::GetGlobalVertex(), and PT.
void SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::AddFlow (PHCompositeNode * topNode, vector< PseudoJet > & particles, map< int, pair< Jet::SRC, int >> & fjMap) private
Definition at line 412 of file SCorrelatorJetTree.jet.h.
View newest version in sPHENIX GitHub at line 412 of file SCorrelatorJetTree.jet.h
References Fill(), INPUTHEPMC::FLOW, SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::GetFlowStore(), and PT.
void SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::AddHCal (PHCompositeNode * topNode, vector< PseudoJet > & particles, map< int, pair< Jet::SRC, int >> & fjMap) private
Definition at line 575 of file SCorrelatorJetTree.jet.h.
View newest version in sPHENIX GitHub at line 575 of file SCorrelatorJetTree.jet.h
References Fill(), SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::GetClusterStore(), RawClusterUtility::GetECoreVec(), SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::GetGlobalVertex(), Enable::HCALIN_CLUSTER, Enable::HCALOUT_CLUSTER, and PT.
void SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::AddParticles (PHCompositeNode * topNode, vector< PseudoJet > & particles, map< int, pair< Jet::SRC, int >> & fjMap) private
Definition at line 79 of file SCorrelatorJetTree.jet.h.
View newest version in sPHENIX GitHub at line 79 of file SCorrelatorJetTree.jet.h
References Fill(), SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::GetEmbedID(), SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::GetMcEvent(), momentum, PT, and utils::status.
void SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::AddTracks (PHCompositeNode * topNode, vector< PseudoJet > & particles, map< int, pair< Jet::SRC, int >> & fjMap) private
Definition at line 158 of file SCorrelatorJetTree.jet.h.
View newest version in sPHENIX GitHub at line 158 of file SCorrelatorJetTree.jet.h
References parse_cmake_options::begin, end, Fill(), SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::GetMatchID(), SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::GetNumClust(), SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::GetNumLayer(), SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::GetTrackDcaPair(), SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::GetTrackDeltaPt(), SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::GetTrackMap(), SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::GetTrackVertex(), g4evalfn::INTT, g4evalfn::MVTX, PT, and g4evalfn::TPC.
int SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::CreateJetNode (PHCompositeNode * topNode) private
Definition at line 1001 of file SCorrelatorJetTree.sys.h.
View newest version in sPHENIX GitHub at line 1001 of file SCorrelatorJetTree.sys.h
References Fun4AllReturnCodes::EVENT_OK, PHNodeIterator::findFirst(), and Acts::Test::pos.
Referenced by Init().
void SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::DetermineEvtsToGrab (PHCompositeNode * topNode) private
Definition at line 975 of file SCorrelatorJetTree.sys.h.
View newest version in sPHENIX GitHub at line 975 of file SCorrelatorJetTree.sys.h
References parse_cmake_options::begin, and end.
Referenced by process_event().
int SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::End (PHCompositeNode *) override virtual
Called at the end of all processing.
Reimplemented from SubsysReco.
Definition at line 174 of file SCorrelatorJetTree.cc.
View newest version in sPHENIX GitHub at line 174 of file SCorrelatorJetTree.cc
References cd(), Close(), Fun4AllReturnCodes::EVENT_OK, m_doDebug, m_outFile, SaveOutput(), and Fun4AllBase::Verbosity().
void SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::FillRecoTree () private
Definition at line 645 of file SCorrelatorJetTree.sys.h.
View newest version in sPHENIX GitHub at line 645 of file SCorrelatorJetTree.sys.h
References Fill(), and PT.
Referenced by process_event().
void SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::FillTrueTree () private
Definition at line 483 of file SCorrelatorJetTree.sys.h.
View newest version in sPHENIX GitHub at line 483 of file SCorrelatorJetTree.sys.h
References Fill(), and PT.
Referenced by process_event().
void SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::FindRecoJets (PHCompositeNode * topNode) private
Definition at line 50 of file SCorrelatorJetTree.jet.h.
View newest version in sPHENIX GitHub at line 50 of file SCorrelatorJetTree.jet.h
References Best, and particles.
Referenced by process_event().
void SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::FindTrueJets (PHCompositeNode * topNode) private
Definition at line 24 of file SCorrelatorJetTree.jet.h.
View newest version in sPHENIX GitHub at line 24 of file SCorrelatorJetTree.jet.h
References Best, and particles.
Referenced by process_event().
bool SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::GetAddECal () inline
Definition at line 206 of file SCorrelatorJetTree.h.
View newest version in sPHENIX GitHub at line 206 of file SCorrelatorJetTree.h
bool SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::GetAddFlow () inline
Definition at line 205 of file SCorrelatorJetTree.h.
View newest version in sPHENIX GitHub at line 205 of file SCorrelatorJetTree.h
bool SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::GetAddHCal () inline
Definition at line 207 of file SCorrelatorJetTree.h.
View newest version in sPHENIX GitHub at line 207 of file SCorrelatorJetTree.h
bool SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::GetAddTracks () inline
Definition at line 204 of file SCorrelatorJetTree.h.
View newest version in sPHENIX GitHub at line 204 of file SCorrelatorJetTree.h
bool SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::GetCheckWeirdTrks () inline
Definition at line 199 of file SCorrelatorJetTree.h.
View newest version in sPHENIX GitHub at line 199 of file SCorrelatorJetTree.h
RawClusterContainer * SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::GetClusterStore (PHCompositeNode * topNode, const TString sNodeName) private
Definition at line 1220 of file SCorrelatorJetTree.sys.h.
View newest version in sPHENIX GitHub at line 1220 of file SCorrelatorJetTree.sys.h
References assert, and PHWHERE.
bool SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::GetDoDcaSigmaCut () inline
Definition at line 197 of file SCorrelatorJetTree.h.
View newest version in sPHENIX GitHub at line 197 of file SCorrelatorJetTree.h
bool SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::GetDoDebug () inline
Definition at line 203 of file SCorrelatorJetTree.h.
View newest version in sPHENIX GitHub at line 203 of file SCorrelatorJetTree.h
bool SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::GetDoQualityPlots () inline
Definition at line 194 of file SCorrelatorJetTree.h.
View newest version in sPHENIX GitHub at line 194 of file SCorrelatorJetTree.h
bool SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::GetDoVtxCut () inline
Definition at line 193 of file SCorrelatorJetTree.h.
View newest version in sPHENIX GitHub at line 193 of file SCorrelatorJetTree.h
double SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::GetECalMaxEta () inline
Definition at line 244 of file SCorrelatorJetTree.h.
View newest version in sPHENIX GitHub at line 244 of file SCorrelatorJetTree.h
double SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::GetECalMaxPt () inline
Definition at line 242 of file SCorrelatorJetTree.h.
View newest version in sPHENIX GitHub at line 242 of file SCorrelatorJetTree.h
double SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::GetECalMinEta () inline
Definition at line 243 of file SCorrelatorJetTree.h.
View newest version in sPHENIX GitHub at line 243 of file SCorrelatorJetTree.h
double SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::GetECalMinPt () inline
Definition at line 241 of file SCorrelatorJetTree.h.
View newest version in sPHENIX GitHub at line 241 of file SCorrelatorJetTree.h
int SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::GetEmbedID (PHCompositeNode * topNode, const int iEvtToGrab = 1) private
Definition at line 1075 of file SCorrelatorJetTree.sys.h.
View newest version in sPHENIX GitHub at line 1075 of file SCorrelatorJetTree.sys.h
References assert, and PHWHERE.
void SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::GetEventVariables (PHCompositeNode * topNode) private
Definition at line 43 of file SCorrelatorJetTree.evt.h.
View newest version in sPHENIX GitHub at line 43 of file SCorrelatorJetTree.evt.h
References SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::GetNumTrks(), and SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::GetRecoVtx().
Referenced by process_event().
double SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::GetEvtMaxVr () inline
Definition at line 214 of file SCorrelatorJetTree.h.
View newest version in sPHENIX GitHub at line 214 of file SCorrelatorJetTree.h
double SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::GetEvtMaxVz () inline
Definition at line 212 of file SCorrelatorJetTree.h.
View newest version in sPHENIX GitHub at line 212 of file SCorrelatorJetTree.h
double SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::GetEvtMinVr () inline
Definition at line 213 of file SCorrelatorJetTree.h.
View newest version in sPHENIX GitHub at line 213 of file SCorrelatorJetTree.h
double SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::GetEvtMinVz () inline
Definition at line 211 of file SCorrelatorJetTree.h.
View newest version in sPHENIX GitHub at line 211 of file SCorrelatorJetTree.h
double SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::GetFlowMaxEta () inline
Definition at line 240 of file SCorrelatorJetTree.h.
View newest version in sPHENIX GitHub at line 240 of file SCorrelatorJetTree.h
double SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::GetFlowMaxPt () inline
Definition at line 238 of file SCorrelatorJetTree.h.
View newest version in sPHENIX GitHub at line 238 of file SCorrelatorJetTree.h
double SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::GetFlowMinEta () inline
Definition at line 239 of file SCorrelatorJetTree.h.
View newest version in sPHENIX GitHub at line 239 of file SCorrelatorJetTree.h
double SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::GetFlowMinPt () inline
Definition at line 237 of file SCorrelatorJetTree.h.
View newest version in sPHENIX GitHub at line 237 of file SCorrelatorJetTree.h
ParticleFlowElementContainer * SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::GetFlowStore (PHCompositeNode * topNode) private
Definition at line 1241 of file SCorrelatorJetTree.sys.h.
View newest version in sPHENIX GitHub at line 1241 of file SCorrelatorJetTree.sys.h
References assert, and PHWHERE.
GlobalVertex * SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::GetGlobalVertex (PHCompositeNode * topNode, const int iVtxToGrab = -1) private
Definition at line 1126 of file SCorrelatorJetTree.sys.h.
View newest version in sPHENIX GitHub at line 1126 of file SCorrelatorJetTree.sys.h
References assert, parse_cmake_options::begin, SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::GetVertexMap(), and PHWHERE.
double SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::GetHCalMaxEta () inline
Definition at line 248 of file SCorrelatorJetTree.h.
View newest version in sPHENIX GitHub at line 248 of file SCorrelatorJetTree.h
double SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::GetHCalMaxPt () inline
Definition at line 246 of file SCorrelatorJetTree.h.
View newest version in sPHENIX GitHub at line 246 of file SCorrelatorJetTree.h
double SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::GetHCalMinEta () inline
Definition at line 247 of file SCorrelatorJetTree.h.
View newest version in sPHENIX GitHub at line 247 of file SCorrelatorJetTree.h
double SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::GetHCalMinPt () inline
Definition at line 245 of file SCorrelatorJetTree.h.
View newest version in sPHENIX GitHub at line 245 of file SCorrelatorJetTree.h
bool SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::GetIsEmbed () inline
Definition at line 202 of file SCorrelatorJetTree.h.
View newest version in sPHENIX GitHub at line 202 of file SCorrelatorJetTree.h
bool SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::GetIsMC () inline
Definition at line 201 of file SCorrelatorJetTree.h.
View newest version in sPHENIX GitHub at line 201 of file SCorrelatorJetTree.h
JetAlgorithm SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::GetJetAlgo () inline
Definition at line 253 of file SCorrelatorJetTree.h.
View newest version in sPHENIX GitHub at line 253 of file SCorrelatorJetTree.h
double SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::GetJetR () inline
Definition at line 251 of file SCorrelatorJetTree.h.
View newest version in sPHENIX GitHub at line 251 of file SCorrelatorJetTree.h
string SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::GetJetTreeName () inline
Definition at line 208 of file SCorrelatorJetTree.h.
View newest version in sPHENIX GitHub at line 208 of file SCorrelatorJetTree.h
uint32_t SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::GetJetType () inline
Definition at line 252 of file SCorrelatorJetTree.h.
View newest version in sPHENIX GitHub at line 252 of file SCorrelatorJetTree.h
bool SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::GetMaskTpcSectors () inline
Definition at line 198 of file SCorrelatorJetTree.h.
View newest version in sPHENIX GitHub at line 198 of file SCorrelatorJetTree.h
int SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::GetMatchID (SvtxTrack * track) private
Definition at line 725 of file SCorrelatorJetTree.cst.h.
View newest version in sPHENIX GitHub at line 725 of file SCorrelatorJetTree.cst.h
References Verbosity().
HepMC::GenEvent * SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::GetMcEvent (PHCompositeNode * topNode, const int iEvtToGrab = 1) private
Definition at line 1182 of file SCorrelatorJetTree.sys.h.
View newest version in sPHENIX GitHub at line 1182 of file SCorrelatorJetTree.sys.h
References assert, and PHWHERE.
long SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::GetNumChrgPars (PHCompositeNode * topNode) private
Definition at line 135 of file SCorrelatorJetTree.evt.h.
View newest version in sPHENIX GitHub at line 135 of file SCorrelatorJetTree.evt.h
References SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::GetMcEvent(), and utils::status.
int SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::GetNumClust (SvtxTrack * track, const uint8_t subsys = 0) private
Definition at line 645 of file SCorrelatorJetTree.cst.h.
View newest version in sPHENIX GitHub at line 645 of file SCorrelatorJetTree.cst.h
References assert, TrkrDefs::getLayer(), g4evalfn::INTT, SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::IsGoodTrackSeed(), layer, g4evalfn::MVTX, seed, g4evalfn::TPC, and Verbosity().
int SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::GetNumLayer (SvtxTrack * track, const uint8_t subsys = 0) private
Definition at line 516 of file SCorrelatorJetTree.cst.h.
View newest version in sPHENIX GitHub at line 516 of file SCorrelatorJetTree.cst.h
References assert, TrkrDefs::getLayer(), g4evalfn::INTT, SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::IsGoodTrackSeed(), layer, g4evalfn::MVTX, seed, g4evalfn::TPC, and Verbosity().
long SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::GetNumTrks (PHCompositeNode * topNode) private
Definition at line 107 of file SCorrelatorJetTree.evt.h.
View newest version in sPHENIX GitHub at line 107 of file SCorrelatorJetTree.evt.h
References parse_cmake_options::begin, end, and SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::GetTrackMap().
double SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::GetParMaxEta () inline
Definition at line 218 of file SCorrelatorJetTree.h.
View newest version in sPHENIX GitHub at line 218 of file SCorrelatorJetTree.h
double SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::GetParMaxPt () inline
Definition at line 216 of file SCorrelatorJetTree.h.
View newest version in sPHENIX GitHub at line 216 of file SCorrelatorJetTree.h
double SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::GetParMinEta () inline
Definition at line 217 of file SCorrelatorJetTree.h.
View newest version in sPHENIX GitHub at line 217 of file SCorrelatorJetTree.h
double SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::GetParMinPt () inline
Definition at line 215 of file SCorrelatorJetTree.h.
View newest version in sPHENIX GitHub at line 215 of file SCorrelatorJetTree.h
float SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::GetParticleCharge (const int pid) private
Definition at line 371 of file SCorrelatorJetTree.cst.h.
View newest version in sPHENIX GitHub at line 371 of file SCorrelatorJetTree.cst.h
References charge(), and Verbosity().
void SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::GetPartonInfo (PHCompositeNode * topNode) private
Definition at line 64 of file SCorrelatorJetTree.evt.h.
View newest version in sPHENIX GitHub at line 64 of file SCorrelatorJetTree.evt.h
References SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::GetMcEvent(), SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::IsOutgoingParton(), momentum, and position.
Referenced by process_event().
RecombinationScheme SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::GetRecombScheme () inline
Definition at line 254 of file SCorrelatorJetTree.h.
View newest version in sPHENIX GitHub at line 254 of file SCorrelatorJetTree.h
CLHEP::Hep3Vector SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::GetRecoVtx (PHCompositeNode * topNode) private
Definition at line 301 of file SCorrelatorJetTree.evt.h.
View newest version in sPHENIX GitHub at line 301 of file SCorrelatorJetTree.evt.h
References SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::GetGlobalVertex().
bool SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::GetRequireSiSeeds () inline
Definition at line 195 of file SCorrelatorJetTree.h.
View newest version in sPHENIX GitHub at line 195 of file SCorrelatorJetTree.h
bool SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::GetSaveDST () inline
Definition at line 200 of file SCorrelatorJetTree.h.
View newest version in sPHENIX GitHub at line 200 of file SCorrelatorJetTree.h
double SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::GetSumECalEne (PHCompositeNode * topNode) private
Definition at line 166 of file SCorrelatorJetTree.evt.h.
View newest version in sPHENIX GitHub at line 166 of file SCorrelatorJetTree.evt.h
References SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::GetClusterStore(), RawClusterUtility::GetECoreVec(), and SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::GetGlobalVertex().
double SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::GetSumHCalEne (PHCompositeNode * topNode) private
Definition at line 206 of file SCorrelatorJetTree.evt.h.
View newest version in sPHENIX GitHub at line 206 of file SCorrelatorJetTree.evt.h
References SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::GetClusterStore(), RawClusterUtility::GetECoreVec(), and SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::GetGlobalVertex().
double SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::GetSumParEne (PHCompositeNode * topNode) private
Definition at line 271 of file SCorrelatorJetTree.evt.h.
View newest version in sPHENIX GitHub at line 271 of file SCorrelatorJetTree.evt.h
References SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::GetMcEvent(), momentum, and utils::status.
pair< double, double > SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::GetTrackDcaPair (SvtxTrack * track, PHCompositeNode * topNode) private
Definition at line 305 of file SCorrelatorJetTree.cst.h.
View newest version in sPHENIX GitHub at line 305 of file SCorrelatorJetTree.cst.h
References TrackAnalysisUtils::get_dca(), and SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::GetGlobalVertex().
double SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::GetTrackDeltaPt (SvtxTrack * track) private
Definition at line 343 of file SCorrelatorJetTree.cst.h.
View newest version in sPHENIX GitHub at line 343 of file SCorrelatorJetTree.cst.h
SvtxTrackMap * SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::GetTrackMap (PHCompositeNode * topNode) private
Definition at line 1105 of file SCorrelatorJetTree.sys.h.
View newest version in sPHENIX GitHub at line 1105 of file SCorrelatorJetTree.sys.h
References assert, and PHWHERE.
double SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::GetTrackMaxDcaXY () inline
Definition at line 232 of file SCorrelatorJetTree.h.
View newest version in sPHENIX GitHub at line 232 of file SCorrelatorJetTree.h
double SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::GetTrackMaxDcaZ () inline
Definition at line 234 of file SCorrelatorJetTree.h.
View newest version in sPHENIX GitHub at line 234 of file SCorrelatorJetTree.h
double SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::GetTrackMaxDeltaPt () inline
Definition at line 236 of file SCorrelatorJetTree.h.
View newest version in sPHENIX GitHub at line 236 of file SCorrelatorJetTree.h
double SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::GetTrackMaxEta () inline
Definition at line 222 of file SCorrelatorJetTree.h.
View newest version in sPHENIX GitHub at line 222 of file SCorrelatorJetTree.h
double SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::GetTrackMaxNIntt () inline
Definition at line 228 of file SCorrelatorJetTree.h.
View newest version in sPHENIX GitHub at line 228 of file SCorrelatorJetTree.h
double SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::GetTrackMaxNMvtx () inline
Definition at line 226 of file SCorrelatorJetTree.h.
View newest version in sPHENIX GitHub at line 226 of file SCorrelatorJetTree.h
double SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::GetTrackMaxNTpc () inline
Definition at line 230 of file SCorrelatorJetTree.h.
View newest version in sPHENIX GitHub at line 230 of file SCorrelatorJetTree.h
double SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::GetTrackMaxPt () inline
Definition at line 220 of file SCorrelatorJetTree.h.
View newest version in sPHENIX GitHub at line 220 of file SCorrelatorJetTree.h
double SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::GetTrackMaxQual () inline
Definition at line 224 of file SCorrelatorJetTree.h.
View newest version in sPHENIX GitHub at line 224 of file SCorrelatorJetTree.h
double SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::GetTrackMinDcaXY () inline
Definition at line 231 of file SCorrelatorJetTree.h.
View newest version in sPHENIX GitHub at line 231 of file SCorrelatorJetTree.h
double SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::GetTrackMinDcaZ () inline
Definition at line 233 of file SCorrelatorJetTree.h.
View newest version in sPHENIX GitHub at line 233 of file SCorrelatorJetTree.h
double SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::GetTrackMinDeltaPt () inline
Definition at line 235 of file SCorrelatorJetTree.h.
View newest version in sPHENIX GitHub at line 235 of file SCorrelatorJetTree.h
double SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::GetTrackMinEta () inline
Definition at line 221 of file SCorrelatorJetTree.h.
View newest version in sPHENIX GitHub at line 221 of file SCorrelatorJetTree.h
double SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::GetTrackMinNIntt () inline
Definition at line 227 of file SCorrelatorJetTree.h.
View newest version in sPHENIX GitHub at line 227 of file SCorrelatorJetTree.h
double SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::GetTrackMinNMvtx () inline
Definition at line 225 of file SCorrelatorJetTree.h.
View newest version in sPHENIX GitHub at line 225 of file SCorrelatorJetTree.h
double SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::GetTrackMinNTpc () inline
Definition at line 229 of file SCorrelatorJetTree.h.
View newest version in sPHENIX GitHub at line 229 of file SCorrelatorJetTree.h
double SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::GetTrackMinPt () inline
Definition at line 219 of file SCorrelatorJetTree.h.
View newest version in sPHENIX GitHub at line 219 of file SCorrelatorJetTree.h
double SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::GetTrackMinQual () inline
Definition at line 223 of file SCorrelatorJetTree.h.
View newest version in sPHENIX GitHub at line 223 of file SCorrelatorJetTree.h
CLHEP::Hep3Vector SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::GetTrackVertex (SvtxTrack * track, PHCompositeNode * topNode) private
Definition at line 324 of file SCorrelatorJetTree.cst.h.
View newest version in sPHENIX GitHub at line 324 of file SCorrelatorJetTree.cst.h
References SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::GetGlobalVertex().
bool SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::GetUseOnlyPrimVtx () inline
Definition at line 196 of file SCorrelatorJetTree.h.
View newest version in sPHENIX GitHub at line 196 of file SCorrelatorJetTree.h
GlobalVertexMap * SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::GetVertexMap (PHCompositeNode * topNode) private
Definition at line 1157 of file SCorrelatorJetTree.sys.h.
View newest version in sPHENIX GitHub at line 1157 of file SCorrelatorJetTree.sys.h
References assert, and PHWHERE.
int SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::Init (PHCompositeNode *) override virtual
Called during initialization. Typically this is where you can book histograms, and e.g. register them to Fun4AllServer (so they can be output to file using Fun4AllServer::dumpHistos() method).
Reimplemented from SubsysReco.
Definition at line 88 of file SCorrelatorJetTree.cc.
View newest version in sPHENIX GitHub at line 88 of file SCorrelatorJetTree.cc
References CreateJetNode(), Fun4AllReturnCodes::EVENT_OK, InitFuncs(), InitHists(), InitTrees(), InitTuples(), m_doDebug, m_outFile, m_outFileName, m_saveDST, and Fun4AllBase::Verbosity().
void SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::InitEvals (PHCompositeNode * topNode) private
Definition at line 457 of file SCorrelatorJetTree.sys.h.
View newest version in sPHENIX GitHub at line 457 of file SCorrelatorJetTree.sys.h
References assert.
Referenced by process_event().
void SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::InitFuncs () private
Definition at line 273 of file SCorrelatorJetTree.sys.h.
View newest version in sPHENIX GitHub at line 273 of file SCorrelatorJetTree.sys.h
References SetParameter().
Referenced by Init().
void SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::InitHists () private
Definition at line 101 of file SCorrelatorJetTree.sys.h.
View newest version in sPHENIX GitHub at line 101 of file SCorrelatorJetTree.sys.h
References cd(), INPUTHEPMC::FLOW, nEtaBins, NRange, and PT.
Referenced by Init().
void SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::InitTrees () private
Definition at line 389 of file SCorrelatorJetTree.sys.h.
View newest version in sPHENIX GitHub at line 389 of file SCorrelatorJetTree.sys.h
References Branch().
Referenced by Init().
void SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::InitTuples () private
Definition at line 296 of file SCorrelatorJetTree.sys.h.
View newest version in sPHENIX GitHub at line 296 of file SCorrelatorJetTree.sys.h
Referenced by Init().
void SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::InitVariables () private
Definition at line 23 of file SCorrelatorJetTree.sys.h.
View newest version in sPHENIX GitHub at line 23 of file SCorrelatorJetTree.sys.h
Referenced by SCorrelatorJetTree().
bool SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::IsFromPrimaryVtx (SvtxTrack * track, PHCompositeNode * topNode) private
Definition at line 283 of file SCorrelatorJetTree.cst.h.
View newest version in sPHENIX GitHub at line 283 of file SCorrelatorJetTree.cst.h
References SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::GetGlobalVertex().
bool SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::IsGoodECal (CLHEP::Hep3Vector & hepVecECal) private
Definition at line 155 of file SCorrelatorJetTree.cst.h.
View newest version in sPHENIX GitHub at line 155 of file SCorrelatorJetTree.cst.h
References Verbosity().
bool SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::IsGoodFlow (ParticleFlowElement * flow) private
Definition at line 138 of file SCorrelatorJetTree.cst.h.
View newest version in sPHENIX GitHub at line 138 of file SCorrelatorJetTree.cst.h
References Verbosity().
bool SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::IsGoodHCal (CLHEP::Hep3Vector & hepVecHCal) private
Definition at line 173 of file SCorrelatorJetTree.cst.h.
View newest version in sPHENIX GitHub at line 173 of file SCorrelatorJetTree.cst.h
References Verbosity().
bool SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::IsGoodParticle (HepMC::GenParticle * par, const bool ignoreCharge = false) private
Definition at line 23 of file SCorrelatorJetTree.cst.h.
View newest version in sPHENIX GitHub at line 23 of file SCorrelatorJetTree.cst.h
References SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::GetParticleCharge(), momentum, and Verbosity().
bool SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::IsGoodTrack (SvtxTrack * track, PHCompositeNode * topNode) private
Definition at line 58 of file SCorrelatorJetTree.cst.h.
View newest version in sPHENIX GitHub at line 58 of file SCorrelatorJetTree.cst.h
References SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::GetNumLayer(), SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::GetTrackDcaPair(), SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::GetTrackDeltaPt(), SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::GetTrackVertex(), g4evalfn::INTT, SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::IsFromPrimaryVtx(), SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::IsGoodTrackSeed(), g4evalfn::MVTX, g4evalfn::TPC, and Verbosity().
bool SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::IsGoodTrackPhi (SvtxTrack * track, const float phiMaskSize = 0.01) private
Definition at line 214 of file SCorrelatorJetTree.cst.h.
View newest version in sPHENIX GitHub at line 214 of file SCorrelatorJetTree.cst.h
References Verbosity().
bool SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::IsGoodTrackSeed (SvtxTrack * track) private
Definition at line 192 of file SCorrelatorJetTree.cst.h.
View newest version in sPHENIX GitHub at line 192 of file SCorrelatorJetTree.cst.h
References Verbosity().
bool SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::IsGoodVertex (const CLHEP::Hep3Vector vtx) private
Definition at line 23 of file SCorrelatorJetTree.evt.h.
View newest version in sPHENIX GitHub at line 23 of file SCorrelatorJetTree.evt.h
Referenced by process_event().
bool SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::IsOutgoingParton (HepMC::GenParticle * par) private
Definition at line 258 of file SCorrelatorJetTree.cst.h.
View newest version in sPHENIX GitHub at line 258 of file SCorrelatorJetTree.cst.h
References train_ambiguity_solver::pid, utils::status, and Verbosity().
int SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::process_event (PHCompositeNode *) override virtual
Called for each event. This is where you do the real work.
Reimplemented from SubsysReco.
Definition at line 117 of file SCorrelatorJetTree.cc.
View newest version in sPHENIX GitHub at line 117 of file SCorrelatorJetTree.cc
References DetermineEvtsToGrab(), Fun4AllReturnCodes::DISCARDEVENT, Fun4AllReturnCodes::EVENT_OK, FillRecoTree(), FillTrueTree(), FindRecoJets(), FindTrueJets(), GetEventVariables(), GetPartonInfo(), InitEvals(), IsGoodVertex(), m_doDebug, m_doVtxCut, m_isMC, m_recoVtx, ResetVariables(), and Fun4AllBase::Verbosity().
void SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::ResetVariables () private
Definition at line 898 of file SCorrelatorJetTree.sys.h.
View newest version in sPHENIX GitHub at line 898 of file SCorrelatorJetTree.sys.h
Referenced by process_event().
void SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::SaveOutput () private
Definition at line 791 of file SCorrelatorJetTree.sys.h.
View newest version in sPHENIX GitHub at line 791 of file SCorrelatorJetTree.sys.h
References cd(), configureMap::data, INPUTHEPMC::FLOW, PT, and Write().
Referenced by End().
void SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::SetAddECal (const bool addECal) inline
Definition at line 151 of file SCorrelatorJetTree.h.
View newest version in sPHENIX GitHub at line 151 of file SCorrelatorJetTree.h
void SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::SetAddFlow (const bool addFlow) inline
Definition at line 150 of file SCorrelatorJetTree.h.
View newest version in sPHENIX GitHub at line 150 of file SCorrelatorJetTree.h
void SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::SetAddHCal (const bool addHCal) inline
Definition at line 152 of file SCorrelatorJetTree.h.
View newest version in sPHENIX GitHub at line 152 of file SCorrelatorJetTree.h
void SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::SetAddTracks (const bool addTracks) inline
Definition at line 149 of file SCorrelatorJetTree.h.
View newest version in sPHENIX GitHub at line 149 of file SCorrelatorJetTree.h
void SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::SetCheckWeirdTrks (const bool check) inline
Definition at line 158 of file SCorrelatorJetTree.h.
View newest version in sPHENIX GitHub at line 158 of file SCorrelatorJetTree.h
References check_fpe_masks::check().
void SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::SetDoQualityPlots (const bool doQA) inline
Definition at line 154 of file SCorrelatorJetTree.h.
View newest version in sPHENIX GitHub at line 154 of file SCorrelatorJetTree.h
void SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::SetDoVertexCut (const bool doVtx) inline
Definition at line 153 of file SCorrelatorJetTree.h.
View newest version in sPHENIX GitHub at line 153 of file SCorrelatorJetTree.h
void SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::SetECalEtaRange (const pair< double, double > etaRange)
Definition at line 220 of file SCorrelatorJetTree.io.h.
View newest version in sPHENIX GitHub at line 220 of file SCorrelatorJetTree.io.h
void SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::SetECalPtRange (const pair< double, double > ptRange)
Definition at line 210 of file SCorrelatorJetTree.io.h.
View newest version in sPHENIX GitHub at line 210 of file SCorrelatorJetTree.io.h
void SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::SetEvtVrRange (const pair< double, double > vrRange)
Definition at line 33 of file SCorrelatorJetTree.io.h.
View newest version in sPHENIX GitHub at line 33 of file SCorrelatorJetTree.io.h
void SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::SetEvtVzRange (const pair< double, double > vzRange)
Definition at line 23 of file SCorrelatorJetTree.io.h.
View newest version in sPHENIX GitHub at line 23 of file SCorrelatorJetTree.io.h
void SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::SetFlowEtaRange (const pair< double, double > etaRange)
Definition at line 200 of file SCorrelatorJetTree.io.h.
View newest version in sPHENIX GitHub at line 200 of file SCorrelatorJetTree.io.h
void SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::SetFlowPtRange (const pair< double, double > ptRange)
Definition at line 190 of file SCorrelatorJetTree.io.h.
View newest version in sPHENIX GitHub at line 190 of file SCorrelatorJetTree.io.h
void SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::SetHCalEtaRange (const pair< double, double > etaRange)
Definition at line 240 of file SCorrelatorJetTree.io.h.
View newest version in sPHENIX GitHub at line 240 of file SCorrelatorJetTree.io.h
void SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::SetHCalPtRange (const pair< double, double > ptRange)
Definition at line 230 of file SCorrelatorJetTree.io.h.
View newest version in sPHENIX GitHub at line 230 of file SCorrelatorJetTree.io.h
void SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::SetIsEmbed (const bool isEmbed) inline
Definition at line 161 of file SCorrelatorJetTree.h.
View newest version in sPHENIX GitHub at line 161 of file SCorrelatorJetTree.h
void SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::SetIsMC (const bool isMC) inline
Definition at line 160 of file SCorrelatorJetTree.h.
View newest version in sPHENIX GitHub at line 160 of file SCorrelatorJetTree.h
void SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::SetJetAlgo (const ALGO jetAlgo)
Definition at line 250 of file SCorrelatorJetTree.io.h.
View newest version in sPHENIX GitHub at line 250 of file SCorrelatorJetTree.io.h
References antikt_algorithm, cambridge_algorithm, and kt_algorithm.
void SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::SetJetParameters (const double rJet, const uint32_t jetType, const ALGO jetAlgo, const RECOMB recombScheme)
Definition at line 300 of file SCorrelatorJetTree.io.h.
View newest version in sPHENIX GitHub at line 300 of file SCorrelatorJetTree.io.h
void SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::SetJetR (const double jetR) inline
Definition at line 162 of file SCorrelatorJetTree.h.
View newest version in sPHENIX GitHub at line 162 of file SCorrelatorJetTree.h
void SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::SetJetTreeName (const string name) inline
Definition at line 164 of file SCorrelatorJetTree.h.
View newest version in sPHENIX GitHub at line 164 of file SCorrelatorJetTree.h
References perf_headwind::name.
void SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::SetJetType (const uint32_t type) inline
Definition at line 163 of file SCorrelatorJetTree.h.
View newest version in sPHENIX GitHub at line 163 of file SCorrelatorJetTree.h
References parse_cmake_options::type.
void SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::SetMaskTpcSectors (const bool mask) inline
Definition at line 157 of file SCorrelatorJetTree.h.
View newest version in sPHENIX GitHub at line 157 of file SCorrelatorJetTree.h
References mask.
void SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::SetParEtaRange (const pair< double, double > etaRange)
Definition at line 53 of file SCorrelatorJetTree.io.h.
View newest version in sPHENIX GitHub at line 53 of file SCorrelatorJetTree.io.h
void SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::SetParPtRange (const pair< double, double > ptRange)
Definition at line 43 of file SCorrelatorJetTree.io.h.
View newest version in sPHENIX GitHub at line 43 of file SCorrelatorJetTree.io.h
void SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::SetRecombScheme (const RECOMB recombScheme)
Definition at line 272 of file SCorrelatorJetTree.io.h.
View newest version in sPHENIX GitHub at line 272 of file SCorrelatorJetTree.io.h
References E_scheme, Et2_scheme, Et_scheme, pt2_scheme, and pt_scheme.
void SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::SetRequireSiSeeds (const bool require) inline
Definition at line 155 of file SCorrelatorJetTree.h.
View newest version in sPHENIX GitHub at line 155 of file SCorrelatorJetTree.h
References Acts::Concepts::require.
void SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::SetSaveDST (const bool doSave) inline
Definition at line 159 of file SCorrelatorJetTree.h.
View newest version in sPHENIX GitHub at line 159 of file SCorrelatorJetTree.h
void SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::SetTrackDcaRangeXY (const pair< double, double > dcaRangeXY)
Definition at line 123 of file SCorrelatorJetTree.io.h.
View newest version in sPHENIX GitHub at line 123 of file SCorrelatorJetTree.io.h
void SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::SetTrackDcaRangeZ (const pair< double, double > dcaRangeZ)
Definition at line 133 of file SCorrelatorJetTree.io.h.
View newest version in sPHENIX GitHub at line 133 of file SCorrelatorJetTree.io.h
void SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::SetTrackDcaSigmaParameters (const bool doDcaSigmaCut, const pair< double, double > ptFitMax, const pair< double, double > nSigma, const vector< double > paramDcaXY, const vector< double > paramDcaZ)
Definition at line 153 of file SCorrelatorJetTree.io.h.
View newest version in sPHENIX GitHub at line 153 of file SCorrelatorJetTree.io.h
References assert, and out.
void SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::SetTrackDeltaPtRange (const pair< double, double > deltaPtRange)
Definition at line 143 of file SCorrelatorJetTree.io.h.
View newest version in sPHENIX GitHub at line 143 of file SCorrelatorJetTree.io.h
void SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::SetTrackEtaRange (const pair< double, double > etaRange)
Definition at line 73 of file SCorrelatorJetTree.io.h.
View newest version in sPHENIX GitHub at line 73 of file SCorrelatorJetTree.io.h
void SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::SetTrackNInttRange (const pair< double, double > nInttRange)
Definition at line 103 of file SCorrelatorJetTree.io.h.
View newest version in sPHENIX GitHub at line 103 of file SCorrelatorJetTree.io.h
void SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::SetTrackNMvtxRange (const pair< double, double > nMvtxRange)
Definition at line 93 of file SCorrelatorJetTree.io.h.
View newest version in sPHENIX GitHub at line 93 of file SCorrelatorJetTree.io.h
void SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::SetTrackNTpcRange (const pair< double, double > nTpcRange)
Definition at line 113 of file SCorrelatorJetTree.io.h.
View newest version in sPHENIX GitHub at line 113 of file SCorrelatorJetTree.io.h
void SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::SetTrackPtRange (const pair< double, double > ptRange)
Definition at line 63 of file SCorrelatorJetTree.io.h.
View newest version in sPHENIX GitHub at line 63 of file SCorrelatorJetTree.io.h
void SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::SetTrackQualityRange (const pair< double, double > qualRange)
Definition at line 83 of file SCorrelatorJetTree.io.h.
View newest version in sPHENIX GitHub at line 83 of file SCorrelatorJetTree.io.h
void SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::SetUseOnlyPrimVtx (const bool primary) inline
Definition at line 156 of file SCorrelatorJetTree.h.
View newest version in sPHENIX GitHub at line 156 of file SCorrelatorJetTree.h
Member Data Documentation
bool SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::isInttLayerHit[CONST::NInttLayer] = {false} private
Definition at line 357 of file SCorrelatorJetTree.h.
View newest version in sPHENIX GitHub at line 357 of file SCorrelatorJetTree.h
bool SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::isMvtxLayerHit[CONST::NMvtxLayer] = {false} private
Definition at line 356 of file SCorrelatorJetTree.h.
View newest version in sPHENIX GitHub at line 356 of file SCorrelatorJetTree.h
bool SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::isTpcLayerHit[CONST::NTpcLayer] = {false} private
Definition at line 358 of file SCorrelatorJetTree.h.
View newest version in sPHENIX GitHub at line 358 of file SCorrelatorJetTree.h
bool SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::m_addECal = false private
Definition at line 386 of file SCorrelatorJetTree.h.
View newest version in sPHENIX GitHub at line 386 of file SCorrelatorJetTree.h
bool SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::m_addFlow = false private
Definition at line 385 of file SCorrelatorJetTree.h.
View newest version in sPHENIX GitHub at line 385 of file SCorrelatorJetTree.h
bool SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::m_addHCal = false private
Definition at line 387 of file SCorrelatorJetTree.h.
View newest version in sPHENIX GitHub at line 387 of file SCorrelatorJetTree.h
bool SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::m_addTracks = true private
Definition at line 384 of file SCorrelatorJetTree.h.
View newest version in sPHENIX GitHub at line 384 of file SCorrelatorJetTree.h
bool SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::m_checkWeirdTrks = false private
Definition at line 383 of file SCorrelatorJetTree.h.
View newest version in sPHENIX GitHub at line 383 of file SCorrelatorJetTree.h
double SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::m_dcaPtFitMaxXY = 15. private
Definition at line 424 of file SCorrelatorJetTree.h.
View newest version in sPHENIX GitHub at line 424 of file SCorrelatorJetTree.h
double SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::m_dcaPtFitMaxZ = 15. private
Definition at line 425 of file SCorrelatorJetTree.h.
View newest version in sPHENIX GitHub at line 425 of file SCorrelatorJetTree.h
bool SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::m_doDcaSigmaCut = false private
Definition at line 377 of file SCorrelatorJetTree.h.
View newest version in sPHENIX GitHub at line 377 of file SCorrelatorJetTree.h
bool SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::m_doDebug = false private
Definition at line 382 of file SCorrelatorJetTree.h.
View newest version in sPHENIX GitHub at line 382 of file SCorrelatorJetTree.h
Referenced by End(), Init(), process_event(), SCorrelatorJetTree(), and ~SCorrelatorJetTree().
bool SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::m_doQualityPlots = true private
Definition at line 374 of file SCorrelatorJetTree.h.
View newest version in sPHENIX GitHub at line 374 of file SCorrelatorJetTree.h
bool SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::m_doVtxCut = false private
Definition at line 373 of file SCorrelatorJetTree.h.
View newest version in sPHENIX GitHub at line 373 of file SCorrelatorJetTree.h
Referenced by process_event().
double SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::m_ecalEtaRange[CONST::NRange] = {-1.1, 1.1} private
Definition at line 417 of file SCorrelatorJetTree.h.
View newest version in sPHENIX GitHub at line 417 of file SCorrelatorJetTree.h
double SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::m_ecalPtRange[CONST::NRange] = {0., 9999.} private
Definition at line 416 of file SCorrelatorJetTree.h.
View newest version in sPHENIX GitHub at line 416 of file SCorrelatorJetTree.h
SvtxEvalStack* SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::m_evalStack = NULL private
Definition at line 343 of file SCorrelatorJetTree.h.
View newest version in sPHENIX GitHub at line 343 of file SCorrelatorJetTree.h
Referenced by ~SCorrelatorJetTree().
double SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::m_evtVrRange[CONST::NRange] = {0.0, 0.418} private
Definition at line 394 of file SCorrelatorJetTree.h.
View newest version in sPHENIX GitHub at line 394 of file SCorrelatorJetTree.h
double SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::m_evtVzRange[CONST::NRange] = {-10., 10.} private
Definition at line 393 of file SCorrelatorJetTree.h.
View newest version in sPHENIX GitHub at line 393 of file SCorrelatorJetTree.h
double SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::m_flowEtaRange[CONST::NRange] = {-1.1, 1.1} private
Definition at line 413 of file SCorrelatorJetTree.h.
View newest version in sPHENIX GitHub at line 413 of file SCorrelatorJetTree.h
double SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::m_flowPtRange[CONST::NRange] = {0., 9999.} private
Definition at line 412 of file SCorrelatorJetTree.h.
View newest version in sPHENIX GitHub at line 412 of file SCorrelatorJetTree.h
TF1* SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::m_fSigDcaXY = NULL private
Definition at line 422 of file SCorrelatorJetTree.h.
View newest version in sPHENIX GitHub at line 422 of file SCorrelatorJetTree.h
TF1* SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::m_fSigDcaZ = NULL private
Definition at line 423 of file SCorrelatorJetTree.h.
View newest version in sPHENIX GitHub at line 423 of file SCorrelatorJetTree.h
double SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::m_hcalEtaRange[CONST::NRange] = {-1.1, 1.1} private
Definition at line 419 of file SCorrelatorJetTree.h.
View newest version in sPHENIX GitHub at line 419 of file SCorrelatorJetTree.h
double SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::m_hcalPtRange[CONST::NRange] = {0., 9999.} private
Definition at line 418 of file SCorrelatorJetTree.h.
View newest version in sPHENIX GitHub at line 418 of file SCorrelatorJetTree.h
Fun4AllHistoManager* SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::m_histMan = NULL private
Definition at line 342 of file SCorrelatorJetTree.h.
View newest version in sPHENIX GitHub at line 342 of file SCorrelatorJetTree.h
Referenced by ~SCorrelatorJetTree().
TH1D* SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::m_hJetArea[CONST::NJetType] private
Definition at line 363 of file SCorrelatorJetTree.h.
View newest version in sPHENIX GitHub at line 363 of file SCorrelatorJetTree.h
TH1D* SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::m_hJetNumCst[CONST::NJetType] private
Definition at line 364 of file SCorrelatorJetTree.h.
View newest version in sPHENIX GitHub at line 364 of file SCorrelatorJetTree.h
TH1D* SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::m_hNumCstAccept[CONST::NCstType][CONST::NMoment] private
Definition at line 368 of file SCorrelatorJetTree.h.
View newest version in sPHENIX GitHub at line 368 of file SCorrelatorJetTree.h
TH1D* SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::m_hNumObject[CONST::NObjType] private
Definition at line 365 of file SCorrelatorJetTree.h.
View newest version in sPHENIX GitHub at line 365 of file SCorrelatorJetTree.h
TH1D* SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::m_hObjectQA[CONST::NObjType][CONST::NInfoQA] private
Definition at line 367 of file SCorrelatorJetTree.h.
View newest version in sPHENIX GitHub at line 367 of file SCorrelatorJetTree.h
TH1D* SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::m_hSumCstEne[CONST::NCstType] private
Definition at line 366 of file SCorrelatorJetTree.h.
View newest version in sPHENIX GitHub at line 366 of file SCorrelatorJetTree.h
bool SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::m_isEmbed = false private
Definition at line 381 of file SCorrelatorJetTree.h.
View newest version in sPHENIX GitHub at line 381 of file SCorrelatorJetTree.h
Referenced by SCorrelatorJetTree().
bool SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::m_isMC = true private
Definition at line 380 of file SCorrelatorJetTree.h.
View newest version in sPHENIX GitHub at line 380 of file SCorrelatorJetTree.h
Referenced by process_event(), and SCorrelatorJetTree().
JetAlgorithm SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::m_jetAlgo = antikt_algorithm private
Definition at line 434 of file SCorrelatorJetTree.h.
View newest version in sPHENIX GitHub at line 434 of file SCorrelatorJetTree.h
double SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::m_jetR = 0.4 private
Definition at line 432 of file SCorrelatorJetTree.h.
View newest version in sPHENIX GitHub at line 432 of file SCorrelatorJetTree.h
string SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::m_jetTreeName = "" private
Definition at line 351 of file SCorrelatorJetTree.h.
View newest version in sPHENIX GitHub at line 351 of file SCorrelatorJetTree.h
uint32_t SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::m_jetType = 0 private
Definition at line 433 of file SCorrelatorJetTree.h.
View newest version in sPHENIX GitHub at line 433 of file SCorrelatorJetTree.h
map<int, int> SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::m_mapCstToEmbedID private
Definition at line 389 of file SCorrelatorJetTree.h.
View newest version in sPHENIX GitHub at line 389 of file SCorrelatorJetTree.h
bool SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::m_maskTpcSectors = false private
Definition at line 378 of file SCorrelatorJetTree.h.
View newest version in sPHENIX GitHub at line 378 of file SCorrelatorJetTree.h
double SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::m_nSigCutXY = 1. private
Definition at line 426 of file SCorrelatorJetTree.h.
View newest version in sPHENIX GitHub at line 426 of file SCorrelatorJetTree.h
double SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::m_nSigCutZ = 1. private
Definition at line 427 of file SCorrelatorJetTree.h.
View newest version in sPHENIX GitHub at line 427 of file SCorrelatorJetTree.h
TNtuple* SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::m_ntTrkQA = NULL private
Definition at line 369 of file SCorrelatorJetTree.h.
View newest version in sPHENIX GitHub at line 369 of file SCorrelatorJetTree.h
TNtuple* SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::m_ntWeirdTracks = NULL private
Definition at line 370 of file SCorrelatorJetTree.h.
View newest version in sPHENIX GitHub at line 370 of file SCorrelatorJetTree.h
TFile* SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::m_outFile = NULL private
Definition at line 347 of file SCorrelatorJetTree.h.
View newest version in sPHENIX GitHub at line 347 of file SCorrelatorJetTree.h
Referenced by End(), and Init().
string SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::m_outFileName = "" private
Definition at line 350 of file SCorrelatorJetTree.h.
View newest version in sPHENIX GitHub at line 350 of file SCorrelatorJetTree.h
Referenced by Init(), and SCorrelatorJetTree().
double SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::m_parEtaRange[CONST::NRange] = {-1.1, 1.1} private
Definition at line 398 of file SCorrelatorJetTree.h.
View newest version in sPHENIX GitHub at line 398 of file SCorrelatorJetTree.h
double SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::m_parPtRange[CONST::NRange] = {0.1, 9999.} private
Definition at line 397 of file SCorrelatorJetTree.h.
View newest version in sPHENIX GitHub at line 397 of file SCorrelatorJetTree.h
array<double, CONST::NParam> SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::m_parSigDcaXY = {1., 1., 1., 1.} private
Definition at line 428 of file SCorrelatorJetTree.h.
View newest version in sPHENIX GitHub at line 428 of file SCorrelatorJetTree.h
array<double, CONST::NParam> SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::m_parSigDcaZ = {1., 1., 1., 1.} private
Definition at line 429 of file SCorrelatorJetTree.h.
View newest version in sPHENIX GitHub at line 429 of file SCorrelatorJetTree.h
long long SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::m_partonID[CONST::NPart] private
Definition at line 442 of file SCorrelatorJetTree.h.
View newest version in sPHENIX GitHub at line 442 of file SCorrelatorJetTree.h
CLHEP::Hep3Vector SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::m_partonMom[CONST::NPart] private
Definition at line 443 of file SCorrelatorJetTree.h.
View newest version in sPHENIX GitHub at line 443 of file SCorrelatorJetTree.h
ClusterSequence* SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::m_recoClust = NULL private
Definition at line 438 of file SCorrelatorJetTree.h.
View newest version in sPHENIX GitHub at line 438 of file SCorrelatorJetTree.h
Referenced by ~SCorrelatorJetTree().
vector<vector<double> > SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::m_recoCstDr private
Definition at line 497 of file SCorrelatorJetTree.h.
View newest version in sPHENIX GitHub at line 497 of file SCorrelatorJetTree.h
vector<vector<double> > SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::m_recoCstE private
Definition at line 498 of file SCorrelatorJetTree.h.
View newest version in sPHENIX GitHub at line 498 of file SCorrelatorJetTree.h
vector<vector<double> > SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::m_recoCstEta private
Definition at line 500 of file SCorrelatorJetTree.h.
View newest version in sPHENIX GitHub at line 500 of file SCorrelatorJetTree.h
vector<vector<int> > SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::m_recoCstMatchID private
Definition at line 495 of file SCorrelatorJetTree.h.
View newest version in sPHENIX GitHub at line 495 of file SCorrelatorJetTree.h
vector<vector<double> > SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::m_recoCstPhi private
Definition at line 501 of file SCorrelatorJetTree.h.
View newest version in sPHENIX GitHub at line 501 of file SCorrelatorJetTree.h
vector<vector<double> > SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::m_recoCstPt private
Definition at line 499 of file SCorrelatorJetTree.h.
View newest version in sPHENIX GitHub at line 499 of file SCorrelatorJetTree.h
vector<vector<double> > SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::m_recoCstZ private
Definition at line 496 of file SCorrelatorJetTree.h.
View newest version in sPHENIX GitHub at line 496 of file SCorrelatorJetTree.h
vector<double> SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::m_recoJetArea private
Definition at line 493 of file SCorrelatorJetTree.h.
View newest version in sPHENIX GitHub at line 493 of file SCorrelatorJetTree.h
JetDefinition* SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::m_recoJetDef = NULL private
Definition at line 436 of file SCorrelatorJetTree.h.
View newest version in sPHENIX GitHub at line 436 of file SCorrelatorJetTree.h
Referenced by ~SCorrelatorJetTree().
vector<double> SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::m_recoJetE private
Definition at line 489 of file SCorrelatorJetTree.h.
View newest version in sPHENIX GitHub at line 489 of file SCorrelatorJetTree.h
vector<double> SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::m_recoJetEta private
Definition at line 491 of file SCorrelatorJetTree.h.
View newest version in sPHENIX GitHub at line 491 of file SCorrelatorJetTree.h
vector<unsigned int> SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::m_recoJetID private
Definition at line 488 of file SCorrelatorJetTree.h.
View newest version in sPHENIX GitHub at line 488 of file SCorrelatorJetTree.h
JetMapv1* SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::m_recoJetMap = NULL private
Definition at line 352 of file SCorrelatorJetTree.h.
View newest version in sPHENIX GitHub at line 352 of file SCorrelatorJetTree.h
vector<unsigned long> SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::m_recoJetNCst private
Definition at line 487 of file SCorrelatorJetTree.h.
View newest version in sPHENIX GitHub at line 487 of file SCorrelatorJetTree.h
vector<double> SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::m_recoJetPhi private
Definition at line 492 of file SCorrelatorJetTree.h.
View newest version in sPHENIX GitHub at line 492 of file SCorrelatorJetTree.h
vector<double> SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::m_recoJetPt private
Definition at line 490 of file SCorrelatorJetTree.h.
View newest version in sPHENIX GitHub at line 490 of file SCorrelatorJetTree.h
vector<PseudoJet> SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::m_recoJets private
Definition at line 447 of file SCorrelatorJetTree.h.
View newest version in sPHENIX GitHub at line 447 of file SCorrelatorJetTree.h
RecombinationScheme SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::m_recombScheme = pt_scheme private
Definition at line 439 of file SCorrelatorJetTree.h.
View newest version in sPHENIX GitHub at line 439 of file SCorrelatorJetTree.h
unsigned long SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::m_recoNumJets private
Definition at line 479 of file SCorrelatorJetTree.h.
View newest version in sPHENIX GitHub at line 479 of file SCorrelatorJetTree.h
long SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::m_recoNumTrks private
Definition at line 485 of file SCorrelatorJetTree.h.
View newest version in sPHENIX GitHub at line 485 of file SCorrelatorJetTree.h
double SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::m_recoSumECal private
Definition at line 483 of file SCorrelatorJetTree.h.
View newest version in sPHENIX GitHub at line 483 of file SCorrelatorJetTree.h
double SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::m_recoSumHCal private
Definition at line 484 of file SCorrelatorJetTree.h.
View newest version in sPHENIX GitHub at line 484 of file SCorrelatorJetTree.h
TTree* SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::m_recoTree = NULL private
Definition at line 348 of file SCorrelatorJetTree.h.
View newest version in sPHENIX GitHub at line 348 of file SCorrelatorJetTree.h
CLHEP::Hep3Vector SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::m_recoVtx private
Definition at line 445 of file SCorrelatorJetTree.h.
View newest version in sPHENIX GitHub at line 445 of file SCorrelatorJetTree.h
Referenced by process_event().
double SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::m_recoVtxX private
Definition at line 480 of file SCorrelatorJetTree.h.
View newest version in sPHENIX GitHub at line 480 of file SCorrelatorJetTree.h
double SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::m_recoVtxY private
Definition at line 481 of file SCorrelatorJetTree.h.
View newest version in sPHENIX GitHub at line 481 of file SCorrelatorJetTree.h
double SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::m_recoVtxZ private
Definition at line 482 of file SCorrelatorJetTree.h.
View newest version in sPHENIX GitHub at line 482 of file SCorrelatorJetTree.h
bool SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::m_requireSiSeeds = true private
Definition at line 375 of file SCorrelatorJetTree.h.
View newest version in sPHENIX GitHub at line 375 of file SCorrelatorJetTree.h
bool SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::m_saveDST = false private
Definition at line 379 of file SCorrelatorJetTree.h.
View newest version in sPHENIX GitHub at line 379 of file SCorrelatorJetTree.h
Referenced by Init().
SvtxTrackEval* SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::m_trackEval = NULL private
Definition at line 344 of file SCorrelatorJetTree.h.
View newest version in sPHENIX GitHub at line 344 of file SCorrelatorJetTree.h
Referenced by ~SCorrelatorJetTree().
double SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::m_trkDcaRangeXY[CONST::NRange] = {-5., 5.} private
Definition at line 407 of file SCorrelatorJetTree.h.
View newest version in sPHENIX GitHub at line 407 of file SCorrelatorJetTree.h
double SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::m_trkDcaRangeZ[CONST::NRange] = {-5., 5.} private
Definition at line 408 of file SCorrelatorJetTree.h.
View newest version in sPHENIX GitHub at line 408 of file SCorrelatorJetTree.h
double SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::m_trkDeltaPtRange[CONST::NRange] = {0., 0.5} private
Definition at line 409 of file SCorrelatorJetTree.h.
View newest version in sPHENIX GitHub at line 409 of file SCorrelatorJetTree.h
double SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::m_trkEtaRange[CONST::NRange] = {-1.1, 1.1} private
Definition at line 402 of file SCorrelatorJetTree.h.
View newest version in sPHENIX GitHub at line 402 of file SCorrelatorJetTree.h
double SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::m_trkNInttRange[CONST::NRange] = {1., 100.} private
Definition at line 405 of file SCorrelatorJetTree.h.
View newest version in sPHENIX GitHub at line 405 of file SCorrelatorJetTree.h
double SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::m_trkNMvtxRange[CONST::NRange] = {2., 100.} private
Definition at line 404 of file SCorrelatorJetTree.h.
View newest version in sPHENIX GitHub at line 404 of file SCorrelatorJetTree.h
double SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::m_trkNTpcRange[CONST::NRange] = {25., 100.} private
Definition at line 406 of file SCorrelatorJetTree.h.
View newest version in sPHENIX GitHub at line 406 of file SCorrelatorJetTree.h
double SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::m_trkPtRange[CONST::NRange] = {0.1, 100.} private
Definition at line 401 of file SCorrelatorJetTree.h.
View newest version in sPHENIX GitHub at line 401 of file SCorrelatorJetTree.h
double SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::m_trkQualRange[CONST::NRange] = {-1., 10.} private
Definition at line 403 of file SCorrelatorJetTree.h.
View newest version in sPHENIX GitHub at line 403 of file SCorrelatorJetTree.h
ClusterSequence* SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::m_trueClust = NULL private
Definition at line 437 of file SCorrelatorJetTree.h.
View newest version in sPHENIX GitHub at line 437 of file SCorrelatorJetTree.h
Referenced by ~SCorrelatorJetTree().
vector<vector<double> > SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::m_trueCstDr private
Definition at line 472 of file SCorrelatorJetTree.h.
View newest version in sPHENIX GitHub at line 472 of file SCorrelatorJetTree.h
vector<vector<double> > SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::m_trueCstE private
Definition at line 473 of file SCorrelatorJetTree.h.
View newest version in sPHENIX GitHub at line 473 of file SCorrelatorJetTree.h
vector<vector<int> > SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::m_trueCstEmbedID private
Definition at line 470 of file SCorrelatorJetTree.h.
View newest version in sPHENIX GitHub at line 470 of file SCorrelatorJetTree.h
vector<vector<double> > SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::m_trueCstEta private
Definition at line 475 of file SCorrelatorJetTree.h.
View newest version in sPHENIX GitHub at line 475 of file SCorrelatorJetTree.h
vector<vector<int> > SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::m_trueCstID private
Definition at line 469 of file SCorrelatorJetTree.h.
View newest version in sPHENIX GitHub at line 469 of file SCorrelatorJetTree.h
vector<vector<double> > SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::m_trueCstPhi private
Definition at line 476 of file SCorrelatorJetTree.h.
View newest version in sPHENIX GitHub at line 476 of file SCorrelatorJetTree.h
vector<vector<double> > SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::m_trueCstPt private
Definition at line 474 of file SCorrelatorJetTree.h.
View newest version in sPHENIX GitHub at line 474 of file SCorrelatorJetTree.h
vector<vector<double> > SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::m_trueCstZ private
Definition at line 471 of file SCorrelatorJetTree.h.
View newest version in sPHENIX GitHub at line 471 of file SCorrelatorJetTree.h
vector<double> SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::m_trueJetArea private
Definition at line 467 of file SCorrelatorJetTree.h.
View newest version in sPHENIX GitHub at line 467 of file SCorrelatorJetTree.h
JetDefinition* SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::m_trueJetDef = NULL private
Definition at line 435 of file SCorrelatorJetTree.h.
View newest version in sPHENIX GitHub at line 435 of file SCorrelatorJetTree.h
Referenced by ~SCorrelatorJetTree().
vector<double> SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::m_trueJetE private
Definition at line 463 of file SCorrelatorJetTree.h.
View newest version in sPHENIX GitHub at line 463 of file SCorrelatorJetTree.h
vector<double> SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::m_trueJetEta private
Definition at line 465 of file SCorrelatorJetTree.h.
View newest version in sPHENIX GitHub at line 465 of file SCorrelatorJetTree.h
vector<unsigned int> SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::m_trueJetID private
Definition at line 462 of file SCorrelatorJetTree.h.
View newest version in sPHENIX GitHub at line 462 of file SCorrelatorJetTree.h
JetMapv1* SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::m_trueJetMap = NULL private
Definition at line 353 of file SCorrelatorJetTree.h.
View newest version in sPHENIX GitHub at line 353 of file SCorrelatorJetTree.h
vector<unsigned long> SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::m_trueJetNCst private
Definition at line 461 of file SCorrelatorJetTree.h.
View newest version in sPHENIX GitHub at line 461 of file SCorrelatorJetTree.h
vector<double> SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::m_trueJetPhi private
Definition at line 466 of file SCorrelatorJetTree.h.
View newest version in sPHENIX GitHub at line 466 of file SCorrelatorJetTree.h
vector<double> SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::m_trueJetPt private
Definition at line 464 of file SCorrelatorJetTree.h.
View newest version in sPHENIX GitHub at line 464 of file SCorrelatorJetTree.h
vector<PseudoJet> SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::m_trueJets private
Definition at line 446 of file SCorrelatorJetTree.h.
View newest version in sPHENIX GitHub at line 446 of file SCorrelatorJetTree.h
long SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::m_trueNumChrgPars private
Definition at line 459 of file SCorrelatorJetTree.h.
View newest version in sPHENIX GitHub at line 459 of file SCorrelatorJetTree.h
unsigned long SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::m_trueNumJets private
Definition at line 450 of file SCorrelatorJetTree.h.
View newest version in sPHENIX GitHub at line 450 of file SCorrelatorJetTree.h
long long SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::m_truePartonID[CONST::NPart] private
Definition at line 451 of file SCorrelatorJetTree.h.
View newest version in sPHENIX GitHub at line 451 of file SCorrelatorJetTree.h
double SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::m_truePartonMomX[CONST::NPart] private
Definition at line 452 of file SCorrelatorJetTree.h.
View newest version in sPHENIX GitHub at line 452 of file SCorrelatorJetTree.h
double SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::m_truePartonMomY[CONST::NPart] private
Definition at line 453 of file SCorrelatorJetTree.h.
View newest version in sPHENIX GitHub at line 453 of file SCorrelatorJetTree.h
double SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::m_truePartonMomZ[CONST::NPart] private
Definition at line 454 of file SCorrelatorJetTree.h.
View newest version in sPHENIX GitHub at line 454 of file SCorrelatorJetTree.h
double SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::m_trueSumPar private
Definition at line 458 of file SCorrelatorJetTree.h.
View newest version in sPHENIX GitHub at line 458 of file SCorrelatorJetTree.h
TTree* SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::m_trueTree = NULL private
Definition at line 349 of file SCorrelatorJetTree.h.
View newest version in sPHENIX GitHub at line 349 of file SCorrelatorJetTree.h
CLHEP::Hep3Vector SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::m_trueVtx private
Definition at line 444 of file SCorrelatorJetTree.h.
View newest version in sPHENIX GitHub at line 444 of file SCorrelatorJetTree.h
double SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::m_trueVtxX private
Definition at line 455 of file SCorrelatorJetTree.h.
View newest version in sPHENIX GitHub at line 455 of file SCorrelatorJetTree.h
double SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::m_trueVtxY private
Definition at line 456 of file SCorrelatorJetTree.h.
View newest version in sPHENIX GitHub at line 456 of file SCorrelatorJetTree.h
double SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::m_trueVtxZ private
Definition at line 457 of file SCorrelatorJetTree.h.
View newest version in sPHENIX GitHub at line 457 of file SCorrelatorJetTree.h
bool SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::m_useOnlyPrimVtx = true private
Definition at line 376 of file SCorrelatorJetTree.h.
View newest version in sPHENIX GitHub at line 376 of file SCorrelatorJetTree.h
vector<int> SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::m_vecEvtsToGrab private
Definition at line 388 of file SCorrelatorJetTree.h.
View newest version in sPHENIX GitHub at line 388 of file SCorrelatorJetTree.h
The documentation for this class was generated from the following files:
analysis/blob/master/AndersonAnalysisModules/ColdQcdCorrelatorAnalysis/SCorrelatorJetTree/src/SCorrelatorJetTree.h
analysis/blob/master/AndersonAnalysisModules/ColdQcdCorrelatorAnalysis/SCorrelatorJetTree/src/SCorrelatorJetTree.cc
analysis/blob/master/AndersonAnalysisModules/ColdQcdCorrelatorAnalysis/SCorrelatorJetTree/src/SCorrelatorJetTree.cst.h
analysis/blob/master/AndersonAnalysisModules/ColdQcdCorrelatorAnalysis/SCorrelatorJetTree/src/SCorrelatorJetTree.evt.h
analysis/blob/master/AndersonAnalysisModules/ColdQcdCorrelatorAnalysis/SCorrelatorJetTree/src/SCorrelatorJetTree.io.h
analysis/blob/master/AndersonAnalysisModules/ColdQcdCorrelatorAnalysis/SCorrelatorJetTree/src/SCorrelatorJetTree.jet.h
analysis/blob/master/AndersonAnalysisModules/ColdQcdCorrelatorAnalysis/SCorrelatorJetTree/src/SCorrelatorJetTree.sys.h