Analysis Software: EicEventHeaderv1 Class Reference
EicEventHeaderv1 Class Reference
#include <coresoftware/blob/master/simulation/g4simulation/g4main/EicEventHeaderv1.h>
Classes
union u_property
convert between 32bit inputs and storage type prop_storage_t
Public Member Functions
EicEventHeaderv1 ()
EicEventHeaderv1 (const EicEventHeader *eicevt)
~EicEventHeaderv1 () override
void Reset () override
Clear Event.
bool has_property (const PROPERTY prop_id) const override
float get_property_float (const PROPERTY prop_id) const override
int get_property_int (const PROPERTY prop_id) const override
unsigned int get_property_uint (const PROPERTY prop_id) const override
void set_property (const PROPERTY prop_id, const float value) override
void set_property (const PROPERTY prop_id, const int value) override
void set_property (const PROPERTY prop_id, const unsigned int value) override
void set_eventgenerator_type (const int i) override
int get_eventgenerator_type () const override
void set_milou_weight (const float val) override
float get_milou_weight () const override
void set_milou_trueX (const float val) override
float get_milou_trueX () const override
void set_milou_trueQ2 (const float val) override
float get_milou_trueQ2 () const override
void set_demp_weight (const float val) override
float get_demp_weight () const override
Public Member Functions inherited from EicEventHeader
EicEventHeader ()
~EicEventHeader () override
void identify (std::ostream &os=std::cout) const override
void CopyFrom (const PHObject *phobj) override
Public Member Functions inherited from PHObject
PHObject ()
ctor
~PHObject () override
dtor
virtual PHObject * CloneMe () const
Virtual copy constructor.
virtual PHObject * clone () const final
PHObject * Clone (const char *newname="") const final
void Copy (TObject &object) const final
virtual int isValid () const
isValid returns non zero if object contains vailid data
virtual int Integrate () const
virtual int Integrate (PHObject *)
Protected Types
typedef uint8_t prop_id_t
storage types for properties
typedef uint32_t prop_storage_t
typedef std::map< prop_id_t,
prop_storage_t > prop_map_t
Protected Member Functions
unsigned int get_property_nocheck (const PROPERTY prop_id) const override
void set_property_nocheck (const PROPERTY prop_id, const unsigned int ui) override
Protected Attributes
prop_map_t prop_map
container for properties
Protected Attributes inherited from EicEventHeader
std::map< std::string, double > evInfo
Additional Inherited Members
Public Types inherited from EicEventHeader
enum PROPERTY {
prop_eventgen = 1, prop_milou_weight = 2, prop_milou_truex = 3, prop_milou_trueq2 = 4,
prop_demp_weight = 5, prop_MAX_NUMBER = UCHAR_MAX
}
enum PROPERTY_TYPE { type_int = 1, type_uint = 2, type_float = 3, type_unknown = -1 }
enum EvtGen { Milou = 1, DEMP = 2 }
Static Public Member Functions inherited from EicEventHeader
static std::pair< const
std::string, PROPERTY_TYPE > get_property_info (PROPERTY prop_id)
static bool check_property (const PROPERTY prop_id, const PROPERTY_TYPE prop_type)
static std::string get_property_type (const PROPERTY_TYPE prop_type)
Detailed Description
Definition at line 12 of file EicEventHeaderv1.h.
View newest version in sPHENIX GitHub at line 12 of file EicEventHeaderv1.h
Member Typedef Documentation
typedef uint8_t EicEventHeaderv1::prop_id_t protected
storage types for properties
Definition at line 52 of file EicEventHeaderv1.h.
View newest version in sPHENIX GitHub at line 52 of file EicEventHeaderv1.h
typedef std::map<prop_id_t, prop_storage_t> EicEventHeaderv1::prop_map_t protected
Definition at line 54 of file EicEventHeaderv1.h.
View newest version in sPHENIX GitHub at line 54 of file EicEventHeaderv1.h
typedef uint32_t EicEventHeaderv1::prop_storage_t protected
Definition at line 53 of file EicEventHeaderv1.h.
View newest version in sPHENIX GitHub at line 53 of file EicEventHeaderv1.h
Constructor & Destructor Documentation
EicEventHeaderv1::EicEventHeaderv1 () inline
Definition at line 15 of file EicEventHeaderv1.h.
View newest version in sPHENIX GitHub at line 15 of file EicEventHeaderv1.h
EicEventHeaderv1::EicEventHeaderv1 (const EicEventHeader * eicevt) explicit
Definition at line 14 of file EicEventHeaderv1.cc.
View newest version in sPHENIX GitHub at line 14 of file EicEventHeaderv1.cc
EicEventHeaderv1::~EicEventHeaderv1 () inline override
Definition at line 17 of file EicEventHeaderv1.h.
View newest version in sPHENIX GitHub at line 17 of file EicEventHeaderv1.h
Member Function Documentation
float EicEventHeaderv1::get_demp_weight () const inline override virtual
Reimplemented from EicEventHeader.
Definition at line 45 of file EicEventHeaderv1.h.
View newest version in sPHENIX GitHub at line 45 of file EicEventHeaderv1.h
References get_property_float(), and EicEventHeader::prop_demp_weight.
int EicEventHeaderv1::get_eventgenerator_type () const inline override virtual
Reimplemented from EicEventHeader.
Definition at line 33 of file EicEventHeaderv1.h.
View newest version in sPHENIX GitHub at line 33 of file EicEventHeaderv1.h
References get_property_int(), and EicEventHeader::prop_eventgen.
float EicEventHeaderv1::get_milou_trueQ2 () const inline override virtual
Reimplemented from EicEventHeader.
Definition at line 41 of file EicEventHeaderv1.h.
View newest version in sPHENIX GitHub at line 41 of file EicEventHeaderv1.h
References get_property_float(), and EicEventHeader::prop_milou_trueq2.
float EicEventHeaderv1::get_milou_trueX () const inline override virtual
Reimplemented from EicEventHeader.
Definition at line 39 of file EicEventHeaderv1.h.
View newest version in sPHENIX GitHub at line 39 of file EicEventHeaderv1.h
References get_property_float(), and EicEventHeader::prop_milou_truex.
float EicEventHeaderv1::get_milou_weight () const inline override virtual
Reimplemented from EicEventHeader.
Definition at line 37 of file EicEventHeaderv1.h.
View newest version in sPHENIX GitHub at line 37 of file EicEventHeaderv1.h
References get_property_float(), and EicEventHeader::prop_milou_weight.
float EicEventHeaderv1::get_property_float (const PROPERTY prop_id) const override virtual
Reimplemented from EicEventHeader.
Definition at line 30 of file EicEventHeaderv1.cc.
View newest version in sPHENIX GitHub at line 30 of file EicEventHeaderv1.cc
References EicEventHeaderv1::u_property::fdata, i, and PHWHERE.
Referenced by get_demp_weight(), get_milou_trueQ2(), get_milou_trueX(), and get_milou_weight().
int EicEventHeaderv1::get_property_int (const PROPERTY prop_id) const override virtual
Reimplemented from EicEventHeader.
Definition at line 47 of file EicEventHeaderv1.cc.
View newest version in sPHENIX GitHub at line 47 of file EicEventHeaderv1.cc
References i, EicEventHeaderv1::u_property::idata, and PHWHERE.
Referenced by get_eventgenerator_type().
unsigned int EicEventHeaderv1::get_property_nocheck (const PROPERTY prop_id) const override protected virtual
Reimplemented from EicEventHeader.
Definition at line 122 of file EicEventHeaderv1.cc.
View newest version in sPHENIX GitHub at line 122 of file EicEventHeaderv1.cc
unsigned int EicEventHeaderv1::get_property_uint (const PROPERTY prop_id) const override virtual
Reimplemented from EicEventHeader.
Definition at line 65 of file EicEventHeaderv1.cc.
View newest version in sPHENIX GitHub at line 65 of file EicEventHeaderv1.cc
References i, PHWHERE, and EicEventHeaderv1::u_property::uidata.
bool EicEventHeaderv1::has_property (const PROPERTY prop_id) const override virtual
Reimplemented from EicEventHeader.
Definition at line 24 of file EicEventHeaderv1.cc.
View newest version in sPHENIX GitHub at line 24 of file EicEventHeaderv1.cc
References i.
void EicEventHeaderv1::Reset () override virtual
Clear Event.
Reimplemented from EicEventHeader.
Definition at line 19 of file EicEventHeaderv1.cc.
View newest version in sPHENIX GitHub at line 19 of file EicEventHeaderv1.cc
void EicEventHeaderv1::set_demp_weight (const float val) inline override virtual
Reimplemented from EicEventHeader.
Definition at line 44 of file EicEventHeaderv1.h.
View newest version in sPHENIX GitHub at line 44 of file EicEventHeaderv1.h
References EicEventHeader::prop_demp_weight, and set_property().
void EicEventHeaderv1::set_eventgenerator_type (const int i) inline override virtual
Reimplemented from EicEventHeader.
Definition at line 32 of file EicEventHeaderv1.h.
View newest version in sPHENIX GitHub at line 32 of file EicEventHeaderv1.h
References EicEventHeader::prop_eventgen, and set_property().
void EicEventHeaderv1::set_milou_trueQ2 (const float val) inline override virtual
Reimplemented from EicEventHeader.
Definition at line 40 of file EicEventHeaderv1.h.
View newest version in sPHENIX GitHub at line 40 of file EicEventHeaderv1.h
References EicEventHeader::prop_milou_trueq2, and set_property().
void EicEventHeaderv1::set_milou_trueX (const float val) inline override virtual
Reimplemented from EicEventHeader.
Definition at line 38 of file EicEventHeaderv1.h.
View newest version in sPHENIX GitHub at line 38 of file EicEventHeaderv1.h
References EicEventHeader::prop_milou_truex, and set_property().
void EicEventHeaderv1::set_milou_weight (const float val) inline override virtual
Reimplemented from EicEventHeader.
Definition at line 36 of file EicEventHeaderv1.h.
View newest version in sPHENIX GitHub at line 36 of file EicEventHeaderv1.h
References EicEventHeader::prop_milou_weight, and set_property().
void EicEventHeaderv1::set_property (const PROPERTY prop_id, const float value) override virtual
Reimplemented from EicEventHeader.
Definition at line 82 of file EicEventHeaderv1.cc.
View newest version in sPHENIX GitHub at line 82 of file EicEventHeaderv1.cc
References EicEventHeaderv1::u_property::get_storage(), and PHWHERE.
Referenced by set_demp_weight(), set_eventgenerator_type(), set_milou_trueQ2(), set_milou_trueX(), and set_milou_weight().
void EicEventHeaderv1::set_property (const PROPERTY prop_id, const int value) override virtual
Reimplemented from EicEventHeader.
Definition at line 95 of file EicEventHeaderv1.cc.
View newest version in sPHENIX GitHub at line 95 of file EicEventHeaderv1.cc
References EicEventHeaderv1::u_property::get_storage(), and PHWHERE.
void EicEventHeaderv1::set_property (const PROPERTY prop_id, const unsigned int value) override virtual
Reimplemented from EicEventHeader.
Definition at line 108 of file EicEventHeaderv1.cc.
View newest version in sPHENIX GitHub at line 108 of file EicEventHeaderv1.cc
References EicEventHeaderv1::u_property::get_storage(), and PHWHERE.
void EicEventHeaderv1::set_property_nocheck (const PROPERTY prop_id, const unsigned int ui) inline override protected virtual
Reimplemented from EicEventHeader.
Definition at line 49 of file EicEventHeaderv1.h.
View newest version in sPHENIX GitHub at line 49 of file EicEventHeaderv1.h
References prop_map.
Member Data Documentation
prop_map_t EicEventHeaderv1::prop_map protected
container for properties
Definition at line 82 of file EicEventHeaderv1.h.
View newest version in sPHENIX GitHub at line 82 of file EicEventHeaderv1.h
Referenced by set_property_nocheck().
The documentation for this class was generated from the following files:
coresoftware/blob/master/simulation/g4simulation/g4main/EicEventHeaderv1.h
coresoftware/blob/master/simulation/g4simulation/g4main/EicEventHeaderv1.cc