Analysis Software: PHG4CylinderCellGeom_Spacalv1 Class Reference
PHG4CylinderCellGeom_Spacalv1 Class Reference
PHG4CylinderCellGeom_Spacalv1.
#include <coresoftware/blob/master/simulation/g4simulation/g4detectors/PHG4CylinderCellGeom_Spacalv1.h>
Public Types
typedef std::pair< double, double > bound_t
typedef std::map< int, bound_t > bound_map_t
typedef std::map< int, int > tower_z_ID_eta_bin_map_t
map tower_z_ID -> eta_bin number
Public Member Functions
PHG4CylinderCellGeom_Spacalv1 ()
~PHG4CylinderCellGeom_Spacalv1 () override
void identify (std::ostream &os=std::cout) const override
std::pair< double, double > get_zbounds (const int ibin) const override
std::pair< double, double > get_etabounds (const int ibin) const override
double get_etacenter (const int ibin) const override
double get_zcenter (const int ibin) const override
int get_etabin (const double eta) const override
int get_zbin (const double z) const override
void set_zbounds (const int ibin, const std::pair< double, double > &bounds)
void set_etabounds (const int ibin, const std::pair< double, double > &bounds)
const bound_map_t & get_eta_bound_map () const
void set_eta_bound_map (const bound_map_t &etaBoundMap)
const bound_map_t & get_z_bound_map () const
void set_z_bound_map (const bound_map_t &boundMap)
const tower_z_ID_eta_bin_map_t & get_tower_z_ID_eta_bin_map () const
map tower_z_ID -> eta_bin number
virtual int get_etabin_block (const int tower_z_ID) const
void set_tower_z_ID_eta_bin_map (const tower_z_ID_eta_bin_map_t &m)
map tower_z_ID -> eta_bin number for blocks
Public Member Functions inherited from PHG4CylinderCellGeom
PHG4CylinderCellGeom ()=default
~PHG4CylinderCellGeom () override=default
int get_layer () const
double get_radius () const
double get_thickness () const
int get_binning () const
int get_zbins () const
int get_phibins () const
double get_zmin () const
double get_phistep () const
double get_phimin () const
double get_zstep () const
int get_etabins () const
double get_etastep () const
double get_etamin () const
virtual std::pair< double, double > get_phibounds (const int ibin) const
virtual double get_phicenter (const int ibin) const
virtual int get_phibin (const double phi) const
void set_layer (const int i)
void set_binning (const int i)
void set_radius (const double r)
void set_thickness (const double t)
void set_zbins (const int i)
void set_zmin (const double z)
void set_zstep (const double z)
void set_phibins (const int i)
void set_phistep (const double phi)
void set_phimin (const double phi)
void set_etabins (const int i)
void set_etamin (const double z)
void set_etastep (const double z)
Public Member Functions inherited from PHObject
PHObject ()
ctor
~PHObject () override
dtor
virtual PHObject * CloneMe () const
Virtual copy constructor.
virtual PHObject * clone () const final
PHObject * Clone (const char *newname="") const final
void Copy (TObject &object) const final
virtual void Reset ()
Clear Event.
virtual int isValid () const
isValid returns non zero if object contains vailid data
virtual int Integrate () const
virtual int Integrate (PHObject *)
virtual void CopyFrom (const PHObject *obj)
Protected Member Functions
void map_consistency_check () const
Protected Member Functions inherited from PHG4CylinderCellGeom
void check_binning_method (const int i) const
void check_binning_method_eta (const std::string &src="") const
void check_binning_method_phi (const std::string &src="") const
std::string methodname (const int i) const
Protected Attributes
bound_map_t z_bound_map
bound_map_t eta_bound_map
tower_z_ID_eta_bin_map_t tower_z_ID_eta_bin_map
map tower_z_ID -> eta_bin number for blocks
Protected Attributes inherited from PHG4CylinderCellGeom
int layer = -999
int binning = 0
double radius = NAN
int nzbins = -1
double zmin = NAN
double zstep = NAN
int nphibins = -1
double phimin = -M_PI
double phistep = NAN
double thickness = NAN
Detailed Description
PHG4CylinderCellGeom_Spacalv1.
Definition at line 25 of file PHG4CylinderCellGeom_Spacalv1.h.
View newest version in sPHENIX GitHub at line 25 of file PHG4CylinderCellGeom_Spacalv1.h
Member Typedef Documentation
typedef std::map<int, bound_t> PHG4CylinderCellGeom_Spacalv1::bound_map_t
Definition at line 52 of file PHG4CylinderCellGeom_Spacalv1.h.
View newest version in sPHENIX GitHub at line 52 of file PHG4CylinderCellGeom_Spacalv1.h
typedef std::pair<double, double> PHG4CylinderCellGeom_Spacalv1::bound_t
Definition at line 51 of file PHG4CylinderCellGeom_Spacalv1.h.
View newest version in sPHENIX GitHub at line 51 of file PHG4CylinderCellGeom_Spacalv1.h
typedef std::map<int, int> PHG4CylinderCellGeom_Spacalv1::tower_z_ID_eta_bin_map_t
map tower_z_ID -> eta_bin number
Definition at line 81 of file PHG4CylinderCellGeom_Spacalv1.h.
View newest version in sPHENIX GitHub at line 81 of file PHG4CylinderCellGeom_Spacalv1.h
Constructor & Destructor Documentation
PHG4CylinderCellGeom_Spacalv1::PHG4CylinderCellGeom_Spacalv1 () default
PHG4CylinderCellGeom_Spacalv1::~PHG4CylinderCellGeom_Spacalv1 () override
Definition at line 24 of file PHG4CylinderCellGeom_Spacalv1.cc.
View newest version in sPHENIX GitHub at line 24 of file PHG4CylinderCellGeom_Spacalv1.cc
Member Function Documentation
const bound_map_t& PHG4CylinderCellGeom_Spacalv1::get_eta_bound_map () const inline
Definition at line 55 of file PHG4CylinderCellGeom_Spacalv1.h.
View newest version in sPHENIX GitHub at line 55 of file PHG4CylinderCellGeom_Spacalv1.h
References eta_bound_map, and map_consistency_check().
int PHG4CylinderCellGeom_Spacalv1::get_etabin (const double eta) const override virtual
Reimplemented from PHG4CylinderCellGeom.
Definition at line 145 of file PHG4CylinderCellGeom_Spacalv1.cc.
View newest version in sPHENIX GitHub at line 145 of file PHG4CylinderCellGeom_Spacalv1.cc
int PHG4CylinderCellGeom_Spacalv1::get_etabin_block (const int tower_z_ID) const virtual
Definition at line 166 of file PHG4CylinderCellGeom_Spacalv1.cc.
View newest version in sPHENIX GitHub at line 166 of file PHG4CylinderCellGeom_Spacalv1.cc
Referenced by CaloWaveformSim::maphitetaphi(), PHG4SpacalSteppingAction::NoHitSteppingAction(), PHG4FullProjSpacalCellReco::process_event(), EMCalAna::process_event_SF(), and CaloWaveFormSim::process_g4hits().
pair< double, double > PHG4CylinderCellGeom_Spacalv1::get_etabounds (const int ibin) const override virtual
Reimplemented from PHG4CylinderCellGeom.
Definition at line 119 of file PHG4CylinderCellGeom_Spacalv1.cc.
View newest version in sPHENIX GitHub at line 119 of file PHG4CylinderCellGeom_Spacalv1.cc
References identify, and PHG4CylinderCellDefs::spacalbinning.
double PHG4CylinderCellGeom_Spacalv1::get_etacenter (const int ibin) const override virtual
Reimplemented from PHG4CylinderCellGeom.
Definition at line 160 of file PHG4CylinderCellGeom_Spacalv1.cc.
View newest version in sPHENIX GitHub at line 160 of file PHG4CylinderCellGeom_Spacalv1.cc
const tower_z_ID_eta_bin_map_t& PHG4CylinderCellGeom_Spacalv1::get_tower_z_ID_eta_bin_map () const inline
map tower_z_ID -> eta_bin number
Definition at line 85 of file PHG4CylinderCellGeom_Spacalv1.h.
View newest version in sPHENIX GitHub at line 85 of file PHG4CylinderCellGeom_Spacalv1.h
References tower_z_ID_eta_bin_map.
const bound_map_t& PHG4CylinderCellGeom_Spacalv1::get_z_bound_map () const inline
Definition at line 68 of file PHG4CylinderCellGeom_Spacalv1.h.
View newest version in sPHENIX GitHub at line 68 of file PHG4CylinderCellGeom_Spacalv1.h
References map_consistency_check(), and z_bound_map.
int PHG4CylinderCellGeom_Spacalv1::get_zbin (const double z) const override virtual
Reimplemented from PHG4CylinderCellGeom.
Definition at line 138 of file PHG4CylinderCellGeom_Spacalv1.cc.
View newest version in sPHENIX GitHub at line 138 of file PHG4CylinderCellGeom_Spacalv1.cc
pair< double, double > PHG4CylinderCellGeom_Spacalv1::get_zbounds (const int ibin) const override virtual
Reimplemented from PHG4CylinderCellGeom.
Definition at line 100 of file PHG4CylinderCellGeom_Spacalv1.cc.
View newest version in sPHENIX GitHub at line 100 of file PHG4CylinderCellGeom_Spacalv1.cc
References identify, and PHG4CylinderCellDefs::spacalbinning.
double PHG4CylinderCellGeom_Spacalv1::get_zcenter (const int ibin) const override virtual
Reimplemented from PHG4CylinderCellGeom.
Definition at line 153 of file PHG4CylinderCellGeom_Spacalv1.cc.
View newest version in sPHENIX GitHub at line 153 of file PHG4CylinderCellGeom_Spacalv1.cc
void PHG4CylinderCellGeom_Spacalv1::identify (std::ostream & os = std::cout) const override virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from PHG4CylinderCellGeom.
Definition at line 29 of file PHG4CylinderCellGeom_Spacalv1.cc.
View newest version in sPHENIX GitHub at line 29 of file PHG4CylinderCellGeom_Spacalv1.cc
References KFPMath::b, and PHG4CylinderCellGeom::identify().
Referenced by PHG4FullProjSpacalCellReco::InitRun(), PHG4SpacalSteppingAction::NoHitSteppingAction(), and PHG4FullProjSpacalCellReco::process_event().
void PHG4CylinderCellGeom_Spacalv1::map_consistency_check () const protected
Definition at line 60 of file PHG4CylinderCellGeom_Spacalv1.cc.
View newest version in sPHENIX GitHub at line 60 of file PHG4CylinderCellGeom_Spacalv1.cc
Referenced by get_eta_bound_map(), and get_z_bound_map().
void PHG4CylinderCellGeom_Spacalv1::set_eta_bound_map (const bound_map_t & etaBoundMap) inline
Definition at line 62 of file PHG4CylinderCellGeom_Spacalv1.h.
View newest version in sPHENIX GitHub at line 62 of file PHG4CylinderCellGeom_Spacalv1.h
References eta_bound_map.
void PHG4CylinderCellGeom_Spacalv1::set_etabounds (const int ibin, const std::pair< double, double > & bounds)
Definition at line 92 of file PHG4CylinderCellGeom_Spacalv1.cc.
View newest version in sPHENIX GitHub at line 92 of file PHG4CylinderCellGeom_Spacalv1.cc
References assert, bounds, and configureMap::ibin.
Referenced by PHG4SpacalDetector::AddCellGeometryNode(), and PHG4FullProjSpacalCellReco::InitRun().
void PHG4CylinderCellGeom_Spacalv1::set_tower_z_ID_eta_bin_map (const tower_z_ID_eta_bin_map_t & m) inline
map tower_z_ID -> eta_bin number for blocks
Definition at line 95 of file PHG4CylinderCellGeom_Spacalv1.h.
View newest version in sPHENIX GitHub at line 95 of file PHG4CylinderCellGeom_Spacalv1.h
References Acts::UnitConstants::m, and tower_z_ID_eta_bin_map.
Referenced by PHG4SpacalDetector::AddCellGeometryNode(), and PHG4FullProjSpacalCellReco::InitRun().
void PHG4CylinderCellGeom_Spacalv1::set_z_bound_map (const bound_map_t & boundMap) inline
Definition at line 75 of file PHG4CylinderCellGeom_Spacalv1.h.
View newest version in sPHENIX GitHub at line 75 of file PHG4CylinderCellGeom_Spacalv1.h
References z_bound_map.
void PHG4CylinderCellGeom_Spacalv1::set_zbounds (const int ibin, const std::pair< double, double > & bounds)
Definition at line 85 of file PHG4CylinderCellGeom_Spacalv1.cc.
View newest version in sPHENIX GitHub at line 85 of file PHG4CylinderCellGeom_Spacalv1.cc
References assert, bounds, and configureMap::ibin.
Referenced by PHG4SpacalDetector::AddCellGeometryNode(), and PHG4FullProjSpacalCellReco::InitRun().
Member Data Documentation
bound_map_t PHG4CylinderCellGeom_Spacalv1::eta_bound_map protected
Definition at line 105 of file PHG4CylinderCellGeom_Spacalv1.h.
View newest version in sPHENIX GitHub at line 105 of file PHG4CylinderCellGeom_Spacalv1.h
Referenced by get_eta_bound_map(), and set_eta_bound_map().
tower_z_ID_eta_bin_map_t PHG4CylinderCellGeom_Spacalv1::tower_z_ID_eta_bin_map protected
map tower_z_ID -> eta_bin number for blocks
Definition at line 108 of file PHG4CylinderCellGeom_Spacalv1.h.
View newest version in sPHENIX GitHub at line 108 of file PHG4CylinderCellGeom_Spacalv1.h
Referenced by get_tower_z_ID_eta_bin_map(), and set_tower_z_ID_eta_bin_map().
bound_map_t PHG4CylinderCellGeom_Spacalv1::z_bound_map protected
Definition at line 104 of file PHG4CylinderCellGeom_Spacalv1.h.
View newest version in sPHENIX GitHub at line 104 of file PHG4CylinderCellGeom_Spacalv1.h
Referenced by get_z_bound_map(), and set_z_bound_map().
The documentation for this class was generated from the following files:
coresoftware/blob/master/simulation/g4simulation/g4detectors/PHG4CylinderCellGeom_Spacalv1.h
coresoftware/blob/master/simulation/g4simulation/g4detectors/PHG4CylinderCellGeom_Spacalv1.cc