Analysis Software: TrkrTruthTrackContainerv1 Class Reference
TrkrTruthTrackContainerv1 Class Reference
Cluster container object.
#include <coresoftware/blob/master/simulation/g4simulation/g4tracking/TrkrTruthTrackContainerv1.h>
Public Member Functions
void Reset () override
reset method
void addTruthTrack (TrkrTruthTrack *) override
add a Track
TrkrTruthTrack * getTruthTrack (unsigned int trackid) override
TrkrTruthTrack * getTruthTrack (unsigned int trackid, PHG4TruthInfoContainer *) override
ConstRange getTruthTrackRange () const override
bool hasTrackid (unsigned int trackid) const override
Map & getMap () override
TrkrTruthTrackContainerv1 ()=default
void identify (std::ostream &os=std::cout) const override
int nhw_virt () override
Public Member Functions inherited from TrkrTruthTrackContainer
int nhw ()
int nhw_cc ()
Public Member Functions inherited from PHObject
PHObject ()
ctor
~PHObject () override
dtor
virtual PHObject * CloneMe () const
Virtual copy constructor.
virtual PHObject * clone () const final
PHObject * Clone (const char *newname="") const final
void Copy (TObject &object) const final
virtual int isValid () const
isValid returns non zero if object contains vailid data
virtual int Integrate () const
virtual int Integrate (PHObject *)
virtual void CopyFrom (const PHObject *obj)
Private Attributes
Map m_data {}
Additional Inherited Members
Public Types inherited from TrkrTruthTrackContainer
using Map = std::map< unsigned int, TrkrTruthTrack * >
using Iterator = Map::iterator
using ConstIterator = Map::const_iterator
using Range = std::pair< Iterator, Iterator >
using ConstRange = std::pair< ConstIterator, ConstIterator >
Protected Member Functions inherited from TrkrTruthTrackContainer
TrkrTruthTrackContainer ()=default
Detailed Description
Cluster container object.
Definition at line 18 of file TrkrTruthTrackContainerv1.h.
View newest version in sPHENIX GitHub at line 18 of file TrkrTruthTrackContainerv1.h
Constructor & Destructor Documentation
TrkrTruthTrackContainerv1::TrkrTruthTrackContainerv1 () default
Member Function Documentation
void TrkrTruthTrackContainerv1::addTruthTrack (TrkrTruthTrack *) override virtual
add a Track
Reimplemented from TrkrTruthTrackContainer.
Definition at line 25 of file TrkrTruthTrackContainerv1.cc.
View newest version in sPHENIX GitHub at line 25 of file TrkrTruthTrackContainerv1.cc
References TrkrTruthTrack::getTrackid(), hasTrackid(), train_ambiguity_solver::id, m_data, and PHWHERE.
TrkrTruthTrackContainer::Map & TrkrTruthTrackContainerv1::getMap () override virtual
Reimplemented from TrkrTruthTrackContainer.
Definition at line 76 of file TrkrTruthTrackContainerv1.cc.
View newest version in sPHENIX GitHub at line 76 of file TrkrTruthTrackContainerv1.cc
References m_data.
TrkrTruthTrack * TrkrTruthTrackContainerv1::getTruthTrack (unsigned int trackid) override virtual
Reimplemented from TrkrTruthTrackContainer.
Definition at line 35 of file TrkrTruthTrackContainerv1.cc.
View newest version in sPHENIX GitHub at line 35 of file TrkrTruthTrackContainerv1.cc
References hasTrackid(), m_data, and PHWHERE.
TrkrTruthTrack * TrkrTruthTrackContainerv1::getTruthTrack (unsigned int trackid, PHG4TruthInfoContainer * truth_info) override virtual
Reimplemented from TrkrTruthTrackContainer.
Definition at line 46 of file TrkrTruthTrackContainerv1.cc.
View newest version in sPHENIX GitHub at line 46 of file TrkrTruthTrackContainerv1.cc
References PHG4Particle::get_vtx_id(), PHG4TruthInfoContainer::GetParticle(), PHG4TruthInfoContainer::GetVtx(), hasTrackid(), train_ambiguity_solver::id, m_data, particle, and PHWHERE.
TrkrTruthTrackContainer::ConstRange TrkrTruthTrackContainerv1::getTruthTrackRange () const override virtual
Reimplemented from TrkrTruthTrackContainer.
Definition at line 66 of file TrkrTruthTrackContainerv1.cc.
View newest version in sPHENIX GitHub at line 66 of file TrkrTruthTrackContainerv1.cc
References m_data.
bool TrkrTruthTrackContainerv1::hasTrackid (unsigned int trackid) const override virtual
Reimplemented from TrkrTruthTrackContainer.
Definition at line 71 of file TrkrTruthTrackContainerv1.cc.
View newest version in sPHENIX GitHub at line 71 of file TrkrTruthTrackContainerv1.cc
References m_data.
Referenced by addTruthTrack(), and getTruthTrack().
void TrkrTruthTrackContainerv1::identify (std::ostream & os = std::cout) const override virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from TrkrTruthTrackContainer.
Definition at line 81 of file TrkrTruthTrackContainerv1.cc.
View newest version in sPHENIX GitHub at line 81 of file TrkrTruthTrackContainerv1.cc
References entry, and m_data.
int TrkrTruthTrackContainerv1::nhw_virt () inline override virtual
Reimplemented from TrkrTruthTrackContainer.
Definition at line 33 of file TrkrTruthTrackContainerv1.h.
View newest version in sPHENIX GitHub at line 33 of file TrkrTruthTrackContainerv1.h
void TrkrTruthTrackContainerv1::Reset () override virtual
reset method
Reimplemented from TrkrTruthTrackContainer.
Definition at line 16 of file TrkrTruthTrackContainerv1.cc.
View newest version in sPHENIX GitHub at line 16 of file TrkrTruthTrackContainerv1.cc
References entry, and m_data.
Member Data Documentation
Map TrkrTruthTrackContainerv1::m_data {} private
Definition at line 37 of file TrkrTruthTrackContainerv1.h.
View newest version in sPHENIX GitHub at line 37 of file TrkrTruthTrackContainerv1.h
Referenced by addTruthTrack(), getMap(), getTruthTrack(), getTruthTrackRange(), hasTrackid(), identify(), and Reset().
The documentation for this class was generated from the following files:
coresoftware/blob/master/simulation/g4simulation/g4tracking/TrkrTruthTrackContainerv1.h
coresoftware/blob/master/simulation/g4simulation/g4tracking/TrkrTruthTrackContainerv1.cc