Analysis Software: Acts::GainMatrixSmoother Class Reference
Acts::GainMatrixSmoother Class Reference
#include <acts/blob/sPHENIX/Core/include/Acts/TrackFitting/GainMatrixSmoother.hpp>
Public Types
using GetParameters = Acts::Delegate< TrackStateTraits< MultiTrajectoryTraits::MeasurementSizeMax, false >::Parameters(void *)>
using GetCovariance = Acts::Delegate< TrackStateTraits< MultiTrajectoryTraits::MeasurementSizeMax, false >::Covariance(void *)>
Public Member Functions
template<typename traj_t >
Result< void > operator() (const GeometryContext &gctx, traj_t &trajectory, size_t entryIndex, const Logger &logger=getDummyLogger()) const
Result< void > calculate (void *ts, void *prev_ts, const GetParameters &filtered, const GetCovariance &filteredCovariance, const GetParameters &smoothed, const GetParameters &predicted, const GetCovariance &predictedCovariance, const GetCovariance &smoothedCovariance, const GetCovariance &jacobian, const Logger &logger) const
Detailed Description
Kalman trajectory smoother based on gain matrix formalism.
This implements not a single smoothing step, but the full backwards smoothing procedure for a filtered, forward trajectory using the stored linearization.
Definition at line 30 of file GainMatrixSmoother.hpp.
View newest version in sPHENIX GitHub at line 30 of file GainMatrixSmoother.hpp
Member Typedef Documentation
using Acts::GainMatrixSmoother::GetCovariance = Acts::Delegate<TrackStateTraits<MultiTrajectoryTraits::MeasurementSizeMax, false>::Covariance(void*)>
Definition at line 134 of file GainMatrixSmoother.hpp.
View newest version in sPHENIX GitHub at line 134 of file GainMatrixSmoother.hpp
using Acts::GainMatrixSmoother::GetParameters = Acts::Delegate<TrackStateTraits<MultiTrajectoryTraits::MeasurementSizeMax, false>::Parameters(void*)>
Definition at line 131 of file GainMatrixSmoother.hpp.
View newest version in sPHENIX GitHub at line 131 of file GainMatrixSmoother.hpp
Member Function Documentation
Result< void > Acts::GainMatrixSmoother::calculate (void * ts, void * prev_ts, const GetParameters & filtered, const GetCovariance & filteredCovariance, const GetParameters & smoothed, const GetParameters & predicted, const GetCovariance & predictedCovariance, const GetCovariance & smoothedCovariance, const GetCovariance & jacobian, const Logger & logger) const
Definition at line 21 of file GainMatrixSmoother.cpp.
View newest version in sPHENIX GitHub at line 21 of file GainMatrixSmoother.cpp
References ACTS_DEBUG, Acts::ACTS_VERBOSE(), and G.
Referenced by operator()().
template<typename traj_t > Result<void> Acts::GainMatrixSmoother::operator() (const GeometryContext & gctx, traj_t & trajectory, size_t entryIndex, const Logger & logger = getDummyLogger()) const inline
Run the Kalman smoothing for one trajectory.
Parameters
[in] gctx The geometry context for the smoothing
[in,out] trajectory The trajectory to be smoothed
[in] entryIndex The index of state to start the smoothing
[in] logger Where to write logging information to
Definition at line 39 of file GainMatrixSmoother.hpp.
View newest version in sPHENIX GitHub at line 39 of file GainMatrixSmoother.hpp
References Acts::ACTS_VERBOSE(), assert, calculate(), acts::error, and logger().
The documentation for this class was generated from the following files:
acts/blob/sPHENIX/Core/include/Acts/TrackFitting/GainMatrixSmoother.hpp
acts/blob/sPHENIX/Core/src/TrackFitting/GainMatrixSmoother.cpp