Analysis Software: FlagSavev1 Class Reference
FlagSavev1 Class Reference
#include <coresoftware/blob/master/offline/framework/ffaobjects/FlagSavev1.h>
Public Member Functions
FlagSavev1 ()=default
ctor
~FlagSavev1 () override=default
dtor
PHObject * CloneMe () const override
Virtual copy constructor.
void Reset () override
Clear Event.
int isValid () const override
isValid returns non zero if object contains valid data
void identify (std::ostream &os=std::cout) const override
int FillFromPHFlag (const PHFlag *flags, const bool clearold) override
int PutFlagsBack (PHFlag *flags, const bool overwrite) override
Public Member Functions inherited from FlagSave
~FlagSave () override
dtor
Public Member Functions inherited from PHObject
PHObject ()
ctor
~PHObject () override
dtor
virtual PHObject * clone () const final
PHObject * Clone (const char *newname="") const final
void Copy (TObject &object) const final
virtual int Integrate () const
virtual int Integrate (PHObject *)
virtual void CopyFrom (const PHObject *obj)
Private Member Functions
void ClearAll ()
int FillIntFromPHFlag (const PHFlag *flags)
int Filluint64FromPHFlag (const PHFlag *flags)
int FillDoubleFromPHFlag (const PHFlag *flags)
int FillFloatFromPHFlag (const PHFlag *flags)
int FillStringFromPHFlag (const PHFlag *flags)
int PutIntToPHFlag (PHFlag *flags, const bool overwrite)
int Putuint64ToPHFlag (PHFlag *flags, const bool overwrite)
int PutDoubleToPHFlag (PHFlag *flags, const bool overwrite)
int PutFloatToPHFlag (PHFlag *flags, const bool overwrite)
int PutStringToPHFlag (PHFlag *flags, const bool overwrite)
void PrintIntFlag (std::ostream &os) const
void Printuint64Flag (std::ostream &os) const
void PrintDoubleFlag (std::ostream &os) const
void PrintFloatFlag (std::ostream &os) const
void PrintStringFlag (std::ostream &os) const
Private Attributes
std::map< std::string, int > intflag
std::map< std::string, double > doubleflag
std::map< std::string, float > floatflag
std::map< std::string,
std::string > stringflag
std::map< std::string, uint64_t > m_uint64flag_map
Detailed Description
Definition at line 17 of file FlagSavev1.h.
View newest version in sPHENIX GitHub at line 17 of file FlagSavev1.h
Constructor & Destructor Documentation
FlagSavev1::FlagSavev1 () default
ctor
Referenced by CloneMe().
FlagSavev1::~FlagSavev1 () override default
dtor
Member Function Documentation
void FlagSavev1::ClearAll () private
Definition at line 289 of file FlagSavev1.cc.
View newest version in sPHENIX GitHub at line 289 of file FlagSavev1.cc
References doubleflag, floatflag, intflag, m_uint64flag_map, and stringflag.
Referenced by FillFromPHFlag().
PHObject * FlagSavev1::CloneMe () const override virtual
Virtual copy constructor.
Reimplemented from PHObject.
Definition at line 11 of file FlagSavev1.cc.
View newest version in sPHENIX GitHub at line 11 of file FlagSavev1.cc
References doubleflag, FlagSavev1(), floatflag, intflag, m_uint64flag_map, and stringflag.
int FlagSavev1::FillDoubleFromPHFlag (const PHFlag * flags) private
Definition at line 94 of file FlagSavev1.cc.
View newest version in sPHENIX GitHub at line 94 of file FlagSavev1.cc
References doubleflag, and PHFlag::DoubleMap().
Referenced by FillFromPHFlag().
int FlagSavev1::FillFloatFromPHFlag (const PHFlag * flags) private
Definition at line 105 of file FlagSavev1.cc.
View newest version in sPHENIX GitHub at line 105 of file FlagSavev1.cc
References floatflag, and PHFlag::FloatMap().
Referenced by FillFromPHFlag().
int FlagSavev1::FillFromPHFlag (const PHFlag * , const bool) override virtual
Flags are read during InitRun() and written during End() Fills DST object with flags, if clearold is set, old flags from previous files which were deleted will not be saved
Reimplemented from FlagSave.
Definition at line 48 of file FlagSavev1.cc.
View newest version in sPHENIX GitHub at line 48 of file FlagSavev1.cc
References ClearAll(), FillDoubleFromPHFlag(), FillFloatFromPHFlag(), FillIntFromPHFlag(), FillStringFromPHFlag(), and Filluint64FromPHFlag().
int FlagSavev1::FillIntFromPHFlag (const PHFlag * flags) private
Definition at line 72 of file FlagSavev1.cc.
View newest version in sPHENIX GitHub at line 72 of file FlagSavev1.cc
References intflag, and PHFlag::IntMap().
Referenced by FillFromPHFlag().
int FlagSavev1::FillStringFromPHFlag (const PHFlag * flags) private
Definition at line 116 of file FlagSavev1.cc.
View newest version in sPHENIX GitHub at line 116 of file FlagSavev1.cc
References digitization_config::input, stringflag, and PHFlag::StringMap().
Referenced by FillFromPHFlag().
int FlagSavev1::Filluint64FromPHFlag (const PHFlag * flags) private
Definition at line 83 of file FlagSavev1.cc.
View newest version in sPHENIX GitHub at line 83 of file FlagSavev1.cc
References m_uint64flag_map, and PHFlag::uint64Map().
Referenced by FillFromPHFlag().
void FlagSavev1::identify (std::ostream & os = std::cout) const override virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from FlagSave.
Definition at line 37 of file FlagSavev1.cc.
View newest version in sPHENIX GitHub at line 37 of file FlagSavev1.cc
References PrintDoubleFlag(), PrintFloatFlag(), PrintIntFlag(), PrintStringFlag(), and Printuint64Flag().
int FlagSavev1::isValid () const override virtual
isValid returns non zero if object contains valid data
Reimplemented from FlagSave.
Definition at line 24 of file FlagSavev1.cc.
View newest version in sPHENIX GitHub at line 24 of file FlagSavev1.cc
References doubleflag, floatflag, intflag, m_uint64flag_map, and stringflag.
void FlagSavev1::PrintDoubleFlag (std::ostream & os) const private
Definition at line 244 of file FlagSavev1.cc.
View newest version in sPHENIX GitHub at line 244 of file FlagSavev1.cc
References doubleflag.
Referenced by identify().
void FlagSavev1::PrintFloatFlag (std::ostream & os) const private
Definition at line 259 of file FlagSavev1.cc.
View newest version in sPHENIX GitHub at line 259 of file FlagSavev1.cc
References floatflag.
Referenced by identify().
void FlagSavev1::PrintIntFlag (std::ostream & os) const private
Definition at line 214 of file FlagSavev1.cc.
View newest version in sPHENIX GitHub at line 214 of file FlagSavev1.cc
References intflag.
Referenced by identify().
void FlagSavev1::PrintStringFlag (std::ostream & os) const private
Definition at line 274 of file FlagSavev1.cc.
View newest version in sPHENIX GitHub at line 274 of file FlagSavev1.cc
References stringflag.
Referenced by identify().
void FlagSavev1::Printuint64Flag (std::ostream & os) const private
Definition at line 229 of file FlagSavev1.cc.
View newest version in sPHENIX GitHub at line 229 of file FlagSavev1.cc
References m_uint64flag_map.
Referenced by identify().
int FlagSavev1::PutDoubleToPHFlag (PHFlag * flags, const bool overwrite) private
Definition at line 163 of file FlagSavev1.cc.
View newest version in sPHENIX GitHub at line 163 of file FlagSavev1.cc
References doubleflag, PHFlag::get_DoubleFlag(), and PHFlag::set_DoubleFlag().
Referenced by PutFlagsBack().
int FlagSavev1::PutFlagsBack (PHFlag * , const bool) override virtual
Read back flags from the DST, if overwrite is set: flags from DST object will overwrite flag values set in the macro
Reimplemented from FlagSave.
Definition at line 62 of file FlagSavev1.cc.
View newest version in sPHENIX GitHub at line 62 of file FlagSavev1.cc
References PutDoubleToPHFlag(), PutFloatToPHFlag(), PutIntToPHFlag(), PutStringToPHFlag(), and Putuint64ToPHFlag().
int FlagSavev1::PutFloatToPHFlag (PHFlag * flags, const bool overwrite) private
Definition at line 180 of file FlagSavev1.cc.
View newest version in sPHENIX GitHub at line 180 of file FlagSavev1.cc
References floatflag, PHFlag::get_FloatFlag(), and PHFlag::set_FloatFlag().
Referenced by PutFlagsBack().
int FlagSavev1::PutIntToPHFlag (PHFlag * flags, const bool overwrite) private
Definition at line 129 of file FlagSavev1.cc.
View newest version in sPHENIX GitHub at line 129 of file FlagSavev1.cc
References PHFlag::get_IntFlag(), intflag, and PHFlag::set_IntFlag().
Referenced by PutFlagsBack().
int FlagSavev1::PutStringToPHFlag (PHFlag * flags, const bool overwrite) private
Definition at line 197 of file FlagSavev1.cc.
View newest version in sPHENIX GitHub at line 197 of file FlagSavev1.cc
References PHFlag::get_StringFlag(), PHFlag::set_StringFlag(), and stringflag.
Referenced by PutFlagsBack().
int FlagSavev1::Putuint64ToPHFlag (PHFlag * flags, const bool overwrite) private
Definition at line 146 of file FlagSavev1.cc.
View newest version in sPHENIX GitHub at line 146 of file FlagSavev1.cc
References PHFlag::get_uint64Flag(), m_uint64flag_map, and PHFlag::set_uint64Flag().
Referenced by PutFlagsBack().
void FlagSavev1::Reset () inline override virtual
Clear Event.
Reimplemented from FlagSave.
Definition at line 28 of file FlagSavev1.h.
View newest version in sPHENIX GitHub at line 28 of file FlagSavev1.h
Member Data Documentation
std::map<std::string, double> FlagSavev1::doubleflag private
Definition at line 60 of file FlagSavev1.h.
View newest version in sPHENIX GitHub at line 60 of file FlagSavev1.h
Referenced by ClearAll(), CloneMe(), FillDoubleFromPHFlag(), isValid(), PrintDoubleFlag(), and PutDoubleToPHFlag().
std::map<std::string, float> FlagSavev1::floatflag private
Definition at line 61 of file FlagSavev1.h.
View newest version in sPHENIX GitHub at line 61 of file FlagSavev1.h
Referenced by ClearAll(), CloneMe(), FillFloatFromPHFlag(), isValid(), PrintFloatFlag(), and PutFloatToPHFlag().
std::map<std::string, int> FlagSavev1::intflag private
Definition at line 59 of file FlagSavev1.h.
View newest version in sPHENIX GitHub at line 59 of file FlagSavev1.h
Referenced by ClearAll(), CloneMe(), FillIntFromPHFlag(), isValid(), PrintIntFlag(), and PutIntToPHFlag().
std::map<std::string, uint64_t> FlagSavev1::m_uint64flag_map private
Definition at line 63 of file FlagSavev1.h.
View newest version in sPHENIX GitHub at line 63 of file FlagSavev1.h
Referenced by ClearAll(), CloneMe(), Filluint64FromPHFlag(), isValid(), Printuint64Flag(), and Putuint64ToPHFlag().
std::map<std::string, std::string> FlagSavev1::stringflag private
Definition at line 62 of file FlagSavev1.h.
View newest version in sPHENIX GitHub at line 62 of file FlagSavev1.h
Referenced by ClearAll(), CloneMe(), FillStringFromPHFlag(), isValid(), PrintStringFlag(), and PutStringToPHFlag().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/framework/ffaobjects/FlagSavev1.h
coresoftware/blob/master/offline/framework/ffaobjects/FlagSavev1.cc