Analysis Software: RunDBodbc Class Reference
RunDBodbc Class Reference
#include <OnlMon/blob/main/onlmondatabase/RunDBodbc.h>
Public Member Functions
RunDBodbc ()
virtual ~RunDBodbc ()
void identify () const
std::string RunType (const int runno=0) const
void Verbosity (const int i)
int GetRunNumbers (std::set< int > &result, const std::string &type, const int nruns, const int lastrunexclusive) const
Private Attributes
int verbosity = 0
std::string dbname = "daq"
std::string dbowner = "phnxrc"
std::string dbpasswd = ""
Detailed Description
Definition at line 7 of file RunDBodbc.h.
View newest version in sPHENIX GitHub at line 7 of file RunDBodbc.h
Constructor & Destructor Documentation
RunDBodbc::RunDBodbc () inline
Definition at line 10 of file RunDBodbc.h.
View newest version in sPHENIX GitHub at line 10 of file RunDBodbc.h
virtual RunDBodbc::~RunDBodbc () inline virtual
Definition at line 11 of file RunDBodbc.h.
View newest version in sPHENIX GitHub at line 11 of file RunDBodbc.h
Member Function Documentation
int RunDBodbc::GetRunNumbers (std::set< int > & result, const std::string & type, const int nruns, const int lastrunexclusive) const
Definition at line 145 of file RunDBodbc.cc.
View newest version in sPHENIX GitHub at line 145 of file RunDBodbc.cc
References runCondor_beamspot::cmd, con, odbc::Connection::createStatement(), dbname, dbowner, dbpasswd, Acts::UnitConstants::e, odbc::Statement::executeQuery(), odbc::DriverManager::getConnection(), odbc::ResultSet::getInt(), odbc::SQLException::getMessage(), odbc::ResultSet::next(), runnumber, and verbosity.
Referenced by PktSizeMonDraw::loadpreviousruns().
void RunDBodbc::identify () const
Definition at line 21 of file RunDBodbc.cc.
View newest version in sPHENIX GitHub at line 21 of file RunDBodbc.cc
References dbname, dbowner, and dbpasswd.
std::string RunDBodbc::RunType (const int runno = 0) const
Definition at line 30 of file RunDBodbc.cc.
View newest version in sPHENIX GitHub at line 30 of file RunDBodbc.cc
References runCondor_beamspot::cmd, con, odbc::Connection::createStatement(), dbname, dbowner, dbpasswd, Acts::UnitConstants::e, odbc::Statement::executeQuery(), odbc::DriverManager::getConnection(), odbc::ResultSet::getInt(), odbc::ResultSet::getLong(), odbc::SQLException::getMessage(), odbc::ResultSet::getString(), odbc::ResultSet::next(), and verbosity.
Referenced by PktSizeMonDraw::DrawHistory(), and OnlMonHtml::runInit().
void RunDBodbc::Verbosity (const int i) inline
Definition at line 15 of file RunDBodbc.h.
View newest version in sPHENIX GitHub at line 15 of file RunDBodbc.h
References i, and verbosity.
Member Data Documentation
std::string RunDBodbc::dbname = "daq" private
Definition at line 20 of file RunDBodbc.h.
View newest version in sPHENIX GitHub at line 20 of file RunDBodbc.h
Referenced by GetRunNumbers(), identify(), and RunType().
std::string RunDBodbc::dbowner = "phnxrc" private
Definition at line 21 of file RunDBodbc.h.
View newest version in sPHENIX GitHub at line 21 of file RunDBodbc.h
Referenced by GetRunNumbers(), identify(), and RunType().
std::string RunDBodbc::dbpasswd = "" private
Definition at line 22 of file RunDBodbc.h.
View newest version in sPHENIX GitHub at line 22 of file RunDBodbc.h
Referenced by GetRunNumbers(), identify(), and RunType().
int RunDBodbc::verbosity = 0 private
Definition at line 19 of file RunDBodbc.h.
View newest version in sPHENIX GitHub at line 19 of file RunDBodbc.h
Referenced by GetRunNumbers(), RunType(), and Verbosity().
The documentation for this class was generated from the following files:
OnlMon/blob/main/onlmondatabase/RunDBodbc.h
OnlMon/blob/main/onlmondatabase/RunDBodbc.cc