Analysis Software: ActsExamples::TrackModifier Exception Reference
ActsExamples::TrackModifier Exception Reference final
Select tracks by applying some selection cuts.
#include <acts/blob/sPHENIX/Examples/Algorithms/TruthTracking/ActsExamples/TruthTracking/TrackModifier.hpp>
Classes
struct Config
Public Member Functions
TrackModifier (const Config &config, Acts::Logging::Level level)
ProcessCode execute (const AlgorithmContext &ctx) const final
const Config & config () const
Get readonly access to the config parameters.
Public Member Functions inherited from ActsExamples::IAlgorithm
IAlgorithm (std::string name, Acts::Logging::Level level=Acts::Logging::INFO)
std::string name () const override
The algorithm name.
ProcessCode internalExecute (const AlgorithmContext &context) final
ProcessCode initialize () override
Initialize the algorithm.
ProcessCode finalize () override
Finalize the algorithm.
Private Attributes
Config m_cfg
ReadDataHandle
< TrackParametersContainer > m_inputTrackParameters
ReadDataHandle
< TrajectoriesContainer > m_inputTrajectories
WriteDataHandle
< TrackParametersContainer > m_outputTrackParameters
WriteDataHandle
< TrajectoriesContainer > m_outputTrajectories
Additional Inherited Members
Protected Member Functions inherited from ActsExamples::IAlgorithm
const Acts::Logger & logger () const
Detailed Description
Select tracks by applying some selection cuts.
Definition at line 25 of file TrackModifier.hpp.
View newest version in sPHENIX GitHub at line 25 of file TrackModifier.hpp
Constructor & Destructor Documentation
ActsExamples::TrackModifier::TrackModifier (const Config & config, Acts::Logging::Level level)
Definition at line 27 of file TrackModifier.cpp.
View newest version in sPHENIX GitHub at line 27 of file TrackModifier.cpp
References ActsExamples::TrackModifier::Config::inputTrackParameters, ActsExamples::TrackModifier::Config::inputTrajectories, m_cfg, m_inputTrackParameters, m_inputTrajectories, m_outputTrackParameters, m_outputTrajectories, ActsExamples::DataHandleBase::maybeInitialize(), ActsExamples::TrackModifier::Config::outputTrackParameters, and ActsExamples::TrackModifier::Config::outputTrajectories.
Member Function Documentation
const Config& ActsExamples::TrackModifier::config () const inline
Get readonly access to the config parameters.
Definition at line 54 of file TrackModifier.hpp.
View newest version in sPHENIX GitHub at line 54 of file TrackModifier.hpp
References m_cfg.
ActsExamples::ProcessCode ActsExamples::TrackModifier::execute (const AlgorithmContext & context) const final virtual
Execute the algorithm for one event.
This function must be implemented by subclasses.
Implements ActsExamples::IAlgorithm.
Definition at line 50 of file TrackModifier.cpp.
View newest version in sPHENIX GitHub at line 50 of file TrackModifier.cpp
References Acts::Test::cov, Acts::eBoundTime, i, truth_tracking_gsf_refitting::inputTrajectories, m_cfg(), testing::internal::move(), truth_tracking_gsf_refitting::outputTrajectories, Dataset::parameters, and SUCCESS.
Member Data Documentation
Config ActsExamples::TrackModifier::m_cfg private
Definition at line 57 of file TrackModifier.hpp.
View newest version in sPHENIX GitHub at line 57 of file TrackModifier.hpp
Referenced by config(), and TrackModifier().
ReadDataHandle<TrackParametersContainer> ActsExamples::TrackModifier::m_inputTrackParameters private
Initial value:
{
      this, "InputTrackParameters"}
Definition at line 59 of file TrackModifier.hpp.
View newest version in sPHENIX GitHub at line 59 of file TrackModifier.hpp
Referenced by TrackModifier().
ReadDataHandle<TrajectoriesContainer> ActsExamples::TrackModifier::m_inputTrajectories private
Initial value:
{
      this, "InputTrajectories"}
Definition at line 61 of file TrackModifier.hpp.
View newest version in sPHENIX GitHub at line 61 of file TrackModifier.hpp
Referenced by TrackModifier().
WriteDataHandle<TrackParametersContainer> ActsExamples::TrackModifier::m_outputTrackParameters private
Initial value:
{
      this, "OutputTrackParameters"}
Definition at line 64 of file TrackModifier.hpp.
View newest version in sPHENIX GitHub at line 64 of file TrackModifier.hpp
Referenced by TrackModifier().
WriteDataHandle<TrajectoriesContainer> ActsExamples::TrackModifier::m_outputTrajectories private
Initial value:
{
      this, "OutputTrajectories"}
Definition at line 66 of file TrackModifier.hpp.
View newest version in sPHENIX GitHub at line 66 of file TrackModifier.hpp
Referenced by TrackModifier().
The documentation for this exception was generated from the following files:
acts/blob/sPHENIX/Examples/Algorithms/TruthTracking/ActsExamples/TruthTracking/TrackModifier.hpp
acts/blob/sPHENIX/Examples/Algorithms/TruthTracking/ActsExamples/TruthTracking/TrackModifier.cpp