Analysis Software: OnlMonHtml Class Reference
OnlMonHtml Class Reference
#include <OnlMon/blob/main/onlmonclient/OnlMonHtml.h>
Public Member Functions
OnlMonHtml (const std::string &topdir)
OnlMonHtml (const OnlMonHtml &)=delete
delete copy ctor and assignment opertor (cppcheck)
OnlMonHtml & operator= (const OnlMonHtml &)=delete
virtual ~OnlMonHtml ()
void addMenu (const std::string &header, const std::string &path, const std::string &relfilename)
void namer (const std::string &header, const std::string &basefilename, const std::string &ext, std::string &fullfilename, std::string &filename)
std::string registerPage (const std::string &header, const std::string &path, const std::string &basefilename, const std::string &ext)
void runNumber (const int runnumber)
int runNumber () const
void verbosity (const int v)
int verbosity () const
Protected Member Functions
void plainHtmlMenu (const std::set< std::string > &)
void runInit ()
std::string runRange ()
Protected Attributes
RunDBodbc * rundb = nullptr
int fVerbosity = 0
int fRunNumber = 0
std::string fHtmlDir
std::string fHtmlRunDir
Detailed Description
Definition at line 12 of file OnlMonHtml.h.
View newest version in sPHENIX GitHub at line 12 of file OnlMonHtml.h
Constructor & Destructor Documentation
OnlMonHtml::OnlMonHtml (const std::string & topdir) explicit
Definition at line 74 of file OnlMonHtml.cc.
View newest version in sPHENIX GitHub at line 74 of file OnlMonHtml.cc
References fHtmlDir, and rundb.
OnlMonHtml::OnlMonHtml (const OnlMonHtml &) explicit delete
delete copy ctor and assignment opertor (cppcheck)
OnlMonHtml::~OnlMonHtml () virtual
Definition at line 84 of file OnlMonHtml.cc.
View newest version in sPHENIX GitHub at line 84 of file OnlMonHtml.cc
References rundb.
Member Function Documentation
void OnlMonHtml::addMenu (const std::string & header, const std::string & path, const std::string & relfilename)
Generate a bit of the navigation menu for a given file (link).
Parameters
path the path as it will appear in the menu
relfilename the filename that will be served when using path in the menu (must not be a fullpathname, but a plain filename).
Definition at line 93 of file OnlMonHtml.cc.
View newest version in sPHENIX GitHub at line 93 of file OnlMonHtml.cc
References fHtmlRunDir, in, test_fpe::lines, out, plainHtmlMenu(), Acts::Experimental::detail::BlueprintHelper::sort(), and verbosity().
Referenced by OnlMonClient::htmlAddMenu(), and registerPage().
void OnlMonHtml::namer (const std::string & header, const std::string & basefilename, const std::string & ext, std::string & fullfilename, std::string & filename)
Generate filenames, to be used to produce e.g. gif or html files.
Parameters
drawer the OnlMonDraw child class for which filename must be built
basefilename the beginning of the filename (will be completed e.g. with the run number by this method)
ext the extension of the file (e.g. gif or html)
Returns
fullfilename = path+filename of the generated filename.
filename = only filename of the generated filename
Definition at line 241 of file OnlMonHtml.cc.
View newest version in sPHENIX GitHub at line 241 of file OnlMonHtml.cc
References fHtmlRunDir, runNumber(), and verbosity().
Referenced by OnlMonClient::htmlNamer(), and registerPage().
OnlMonHtml& OnlMonHtml::operator= (const OnlMonHtml &) delete
void OnlMonHtml::plainHtmlMenu (const std::set< std::string > & olines) protected
Definition at line 158 of file OnlMonHtml.cc.
View newest version in sPHENIX GitHub at line 158 of file OnlMonHtml.cc
References test_fpe::count, fHtmlRunDir, i, it, join(), line, perf_headwind::name, out, and Acts::Test::pos.
Referenced by addMenu().
std::string OnlMonHtml::registerPage (const std::string & header, const std::string & path, const std::string & basefilename, const std::string & ext)
Generate a full filename from specified pieces, and register the file to the navigation menu
Parameters
drawer the OnlMonDraw child class for which filename must be built
path the path that will be used in the navigation menu
basefilename the beginning of the filename (will be completed e.g. with the run number by this method)
ext the extension of the file (e.g. gif or html)
Returns
the full filename (i.e. full path + filename)
Definition at line 276 of file OnlMonHtml.cc.
View newest version in sPHENIX GitHub at line 276 of file OnlMonHtml.cc
References addMenu(), filename, and namer().
Referenced by OnlMonClient::htmlRegisterPage().
void OnlMonHtml::runInit () protected
Definition at line 290 of file OnlMonHtml.cc.
View newest version in sPHENIX GitHub at line 290 of file OnlMonHtml.cc
References fHtmlDir, fHtmlRunDir, fRunNumber, rundb, runNumber(), runRange(), RunDBodbc::RunType(), and verbosity().
Referenced by runNumber().
void OnlMonHtml::runNumber (const int runnumber)
Definition at line 401 of file OnlMonHtml.cc.
View newest version in sPHENIX GitHub at line 401 of file OnlMonHtml.cc
References fRunNumber, runInit(), and runnumber.
Referenced by OnlMonClient::MakeHtml().
int OnlMonHtml::runNumber () const inline
Definition at line 58 of file OnlMonHtml.h.
View newest version in sPHENIX GitHub at line 58 of file OnlMonHtml.h
References fRunNumber.
Referenced by namer(), runInit(), and runRange().
std::string OnlMonHtml::runRange () protected
Definition at line 409 of file OnlMonHtml.cc.
View newest version in sPHENIX GitHub at line 409 of file OnlMonHtml.cc
References runNumber(), physmon_simulation::s, and start.
Referenced by runInit().
void OnlMonHtml::verbosity (const int v) inline
Definition at line 60 of file OnlMonHtml.h.
View newest version in sPHENIX GitHub at line 60 of file OnlMonHtml.h
References fVerbosity, and testSigmaEff::v.
Referenced by OnlMonClient::Verbosity().
int OnlMonHtml::verbosity () const inline
Definition at line 61 of file OnlMonHtml.h.
View newest version in sPHENIX GitHub at line 61 of file OnlMonHtml.h
References fVerbosity.
Referenced by addMenu(), namer(), and runInit().
Member Data Documentation
std::string OnlMonHtml::fHtmlDir protected
Definition at line 73 of file OnlMonHtml.h.
View newest version in sPHENIX GitHub at line 73 of file OnlMonHtml.h
Referenced by OnlMonHtml(), and runInit().
std::string OnlMonHtml::fHtmlRunDir protected
Definition at line 74 of file OnlMonHtml.h.
View newest version in sPHENIX GitHub at line 74 of file OnlMonHtml.h
Referenced by addMenu(), namer(), plainHtmlMenu(), and runInit().
int OnlMonHtml::fRunNumber = 0 protected
Definition at line 71 of file OnlMonHtml.h.
View newest version in sPHENIX GitHub at line 71 of file OnlMonHtml.h
Referenced by runInit(), and runNumber().
int OnlMonHtml::fVerbosity = 0 protected
Definition at line 70 of file OnlMonHtml.h.
View newest version in sPHENIX GitHub at line 70 of file OnlMonHtml.h
Referenced by verbosity().
RunDBodbc* OnlMonHtml::rundb = nullptr protected
Definition at line 68 of file OnlMonHtml.h.
View newest version in sPHENIX GitHub at line 68 of file OnlMonHtml.h
Referenced by OnlMonHtml(), runInit(), and ~OnlMonHtml().
The documentation for this class was generated from the following files:
OnlMon/blob/main/onlmonclient/OnlMonHtml.h
OnlMon/blob/main/onlmonclient/OnlMonHtml.cc