Analysis Software: ActsExamples::IndexSourceLink Exception Reference
ActsExamples::IndexSourceLink Exception Reference final
#include <acts/blob/sPHENIX/Examples/Framework/include/ActsExamples/EventData/IndexSourceLink.hpp>
Classes
struct SurfaceAccessor
Public Member Functions
constexpr IndexSourceLink (Acts::GeometryIdentifier gid, Index idx)
Construct from geometry identifier and index.
IndexSourceLink ()=default
satisfy SourceLinkConcept.
IndexSourceLink (const IndexSourceLink &)=default
IndexSourceLink (IndexSourceLink &&)=default
IndexSourceLink & operator= (const IndexSourceLink &)=default
IndexSourceLink & operator= (IndexSourceLink &&)=default
constexpr Index index () const
Access the index.
Acts::GeometryIdentifier geometryId () const
Private Attributes
Acts::GeometryIdentifier m_geometryId
Index m_index = 0
Friends
bool operator== (const IndexSourceLink &lhs, const IndexSourceLink &rhs)
bool operator!= (const IndexSourceLink &lhs, const IndexSourceLink &rhs)
Detailed Description
A source link that stores just an index.
This is intentionally kept as barebones as possible. The source link is just a reference and will be copied, moved around, etc. often. Keeping it small and separate from the actual, potentially large, measurement data should result in better overall performance. Using an index instead of e.g. a pointer, means source link and measurement are decoupled and the measurement representation can be easily changed without having to also change the source link.
Definition at line 30 of file IndexSourceLink.hpp.
View newest version in sPHENIX GitHub at line 30 of file IndexSourceLink.hpp
Constructor & Destructor Documentation
constexpr ActsExamples::IndexSourceLink::IndexSourceLink (Acts::GeometryIdentifier gid, Index idx) inline
Construct from geometry identifier and index.
Definition at line 33 of file IndexSourceLink.hpp.
View newest version in sPHENIX GitHub at line 33 of file IndexSourceLink.hpp
ActsExamples::IndexSourceLink::IndexSourceLink () default
satisfy SourceLinkConcept.
ActsExamples::IndexSourceLink::IndexSourceLink (const IndexSourceLink &) default
ActsExamples::IndexSourceLink::IndexSourceLink (IndexSourceLink &&) default
Member Function Documentation
Acts::GeometryIdentifier ActsExamples::IndexSourceLink::geometryId () const inline
Definition at line 47 of file IndexSourceLink.hpp.
View newest version in sPHENIX GitHub at line 47 of file IndexSourceLink.hpp
References m_geometryId.
constexpr Index ActsExamples::IndexSourceLink::index () const inline
Access the index.
Definition at line 45 of file IndexSourceLink.hpp.
View newest version in sPHENIX GitHub at line 45 of file IndexSourceLink.hpp
References m_index.
Referenced by ActsExamples::PassThroughCalibrator::calibrate(), ActsExamples::TruthSeedingAlgorithm::execute(), ActsExamples::identifyContributingParticles(), ActsExamples::RootSpacepointWriter::writeT(), and ActsExamples::CsvSpacepointWriter::writeT().
IndexSourceLink& ActsExamples::IndexSourceLink::operator= (const IndexSourceLink &) default
IndexSourceLink& ActsExamples::IndexSourceLink::operator= (IndexSourceLink &&) default
Friends And Related Function Documentation
bool operator!= (const IndexSourceLink & lhs, const IndexSourceLink & rhs) friend
Definition at line 67 of file IndexSourceLink.hpp.
View newest version in sPHENIX GitHub at line 67 of file IndexSourceLink.hpp
bool operator== (const IndexSourceLink & lhs, const IndexSourceLink & rhs) friend
Definition at line 62 of file IndexSourceLink.hpp.
View newest version in sPHENIX GitHub at line 62 of file IndexSourceLink.hpp
Member Data Documentation
Acts::GeometryIdentifier ActsExamples::IndexSourceLink::m_geometryId private
Definition at line 59 of file IndexSourceLink.hpp.
View newest version in sPHENIX GitHub at line 59 of file IndexSourceLink.hpp
Referenced by geometryId().
Index ActsExamples::IndexSourceLink::m_index = 0 private
Definition at line 60 of file IndexSourceLink.hpp.
View newest version in sPHENIX GitHub at line 60 of file IndexSourceLink.hpp
Referenced by index().
The documentation for this exception was generated from the following file:
acts/blob/sPHENIX/Examples/Framework/include/ActsExamples/EventData/IndexSourceLink.hpp