Analysis Software: TrkrClusterCrossingAssocv1 Class Reference
TrkrClusterCrossingAssocv1 Class Reference
Class for associating clusters to the bunch crossing that created them.
#include <coresoftware/blob/master/offline/packages/trackbase/TrkrClusterCrossingAssocv1.h>
Public Member Functions
TrkrClusterCrossingAssocv1 ()=default
void Reset () override
Clear Event.
void identify (std::ostream &os=std::cout) const override
void addAssoc (TrkrDefs::cluskey, short int) override
Add association between cluster and hit.
ConstRange getCrossings (TrkrDefs::cluskey) const override
ConstRange getAll () const override
unsigned int size (void) const override
Private Member Functions
ClassDefOverride (TrkrClusterCrossingAssocv1, 1)
Private Attributes
std::multimap
< TrkrDefs::cluskey, short int > m_map
Additional Inherited Members
Public Types inherited from TrkrClusterCrossingAssoc
using Map = std::multimap< TrkrDefs::cluskey, short int >
using ConstIterator = Map::const_iterator
using ConstRange = std::pair< Map::const_iterator, Map::const_iterator >
Protected Member Functions inherited from TrkrClusterCrossingAssoc
TrkrClusterCrossingAssoc ()=default
Detailed Description
Class for associating clusters to the bunch crossing that created them.
Store the associations between clusters and beam crossings.
Definition at line 25 of file TrkrClusterCrossingAssocv1.h.
View newest version in sPHENIX GitHub at line 25 of file TrkrClusterCrossingAssocv1.h
Constructor & Destructor Documentation
TrkrClusterCrossingAssocv1::TrkrClusterCrossingAssocv1 () default
Member Function Documentation
void TrkrClusterCrossingAssocv1::addAssoc (TrkrDefs::cluskey ckey, short hidx) override virtual
Add association between cluster and hit.
Parameters
[in] ckey Cluster key
[in] bunch crossing number
Implements TrkrClusterCrossingAssoc.
Definition at line 50 of file TrkrClusterCrossingAssocv1.cc.
View newest version in sPHENIX GitHub at line 50 of file TrkrClusterCrossingAssocv1.cc
References m_map.
TrkrClusterCrossingAssocv1::ClassDefOverride (TrkrClusterCrossingAssocv1 , 1) private
TrkrClusterCrossingAssocv1::ConstRange TrkrClusterCrossingAssocv1::getAll () const override virtual
Implements TrkrClusterCrossingAssoc.
Definition at line 72 of file TrkrClusterCrossingAssocv1.cc.
View newest version in sPHENIX GitHub at line 72 of file TrkrClusterCrossingAssocv1.cc
References m_map.
TrkrClusterCrossingAssocv1::ConstRange TrkrClusterCrossingAssocv1::getCrossings (TrkrDefs::cluskey ckey) const override virtual
Implements TrkrClusterCrossingAssoc.
Definition at line 57 of file TrkrClusterCrossingAssocv1.cc.
View newest version in sPHENIX GitHub at line 57 of file TrkrClusterCrossingAssocv1.cc
References m_map.
void TrkrClusterCrossingAssocv1::identify (std::ostream & os = std::cout) const override virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from PHObject.
Definition at line 32 of file TrkrClusterCrossingAssocv1.cc.
View newest version in sPHENIX GitHub at line 32 of file TrkrClusterCrossingAssocv1.cc
References TrkrDefs::getLayer(), m_map, and size().
void TrkrClusterCrossingAssocv1::Reset () override virtual
Clear Event.
Reimplemented from TrkrClusterCrossingAssoc.
Definition at line 19 of file TrkrClusterCrossingAssocv1.cc.
View newest version in sPHENIX GitHub at line 19 of file TrkrClusterCrossingAssocv1.cc
References m_map.
unsigned int TrkrClusterCrossingAssocv1::size (void) const override virtual
Reimplemented from TrkrClusterCrossingAssoc.
Definition at line 64 of file TrkrClusterCrossingAssocv1.cc.
View newest version in sPHENIX GitHub at line 64 of file TrkrClusterCrossingAssocv1.cc
References m_map.
Referenced by identify().
Member Data Documentation
std::multimap<TrkrDefs::cluskey, short int> TrkrClusterCrossingAssocv1::m_map private
Definition at line 45 of file TrkrClusterCrossingAssocv1.h.
View newest version in sPHENIX GitHub at line 45 of file TrkrClusterCrossingAssocv1.h
Referenced by addAssoc(), getAll(), getCrossings(), identify(), Reset(), and size().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/trackbase/TrkrClusterCrossingAssocv1.h
coresoftware/blob/master/offline/packages/trackbase/TrkrClusterCrossingAssocv1.cc