Analysis Software: Acts::TGeoPrimitivesHelper Struct Reference
Acts::TGeoPrimitivesHelper Struct Reference
#include <acts/blob/sPHENIX/Plugins/TGeo/include/Acts/Plugins/TGeo/TGeoPrimitivesHelper.hpp>
Static Public Member Functions
static Transform3 makeTransform (const Eigen::Vector3d &rotationMatrixCol0, const Eigen::Vector3d &rotationMatrixCol1, const Eigen::Vector3d &rotationMatrixCol2, const Eigen::Vector3d &translation)
static bool match (const char *first, const char *second)
static bool match (const std::vector< std::string > &first, const char *second)
Detailed Description
Definition at line 18 of file TGeoPrimitivesHelper.hpp.
View newest version in sPHENIX GitHub at line 18 of file TGeoPrimitivesHelper.hpp
Member Function Documentation
static Transform3 Acts::TGeoPrimitivesHelper::makeTransform (const Eigen::Vector3d & rotationMatrixCol0, const Eigen::Vector3d & rotationMatrixCol1, const Eigen::Vector3d & rotationMatrixCol2, const Eigen::Vector3d & translation) inline static
Helper method to create a transform from Rotation matrix vectors:
Parameters
rotationMatrixCol0
rotationMatrixCol1
rotationMatrixCol2 And translation
translation
Definition at line 26 of file TGeoPrimitivesHelper.hpp.
View newest version in sPHENIX GitHub at line 26 of file TGeoPrimitivesHelper.hpp
References translation().
Referenced by Acts::DD4hepVolumeBuilder::convertTransform(), Acts::DD4hepLayerBuilder::convertTransform(), and Acts::TGeoParser::select().
bool Acts::TGeoPrimitivesHelper::match (const char * first, const char * second) static
Private helper method : match string with wildcards
Parameters
first is the one with the potential wildcard
second is the test string
Definition at line 11 of file TGeoPrimitivesHelper.cpp.
View newest version in sPHENIX GitHub at line 11 of file TGeoPrimitivesHelper.cpp
Referenced by Acts::Test::BOOST_AUTO_TEST_CASE(), and Acts::TGeoParser::select().
bool Acts::TGeoPrimitivesHelper::match (const std::vector< std::string > & first, const char * second) static
Private helper method : match string with wildcards Method that uses the match method with wild cards and performs it on an input list
Parameters
first is the one with the potential wildcard
second is the test string
Definition at line 39 of file TGeoPrimitivesHelper.cpp.
View newest version in sPHENIX GitHub at line 39 of file TGeoPrimitivesHelper.cpp
References f.
The documentation for this struct was generated from the following files:
acts/blob/sPHENIX/Plugins/TGeo/include/Acts/Plugins/TGeo/TGeoPrimitivesHelper.hpp
acts/blob/sPHENIX/Plugins/TGeo/src/TGeoPrimitivesHelper.cpp