Analysis Software: ActsExamples Namespace Reference
ActsExamples Namespace Reference
Namespaces
namespace Contextual
namespace DD4hep
namespace DefaultHoughFunctions
namespace detail
namespace Digitization
namespace EDM4hepUtil
namespace Geant4
namespace Generic
namespace Geometry
namespace HepMC3Event
namespace HepMC3Particle
namespace HepMC3Vertex
namespace JsonSurfacesReader
namespace Options
namespace PlotHelpers
namespace Simulation
namespace tbbWrap
namespace Telescope
Classes
exception AlignmentAlgorithm
exception GreedyAmbiguityResolutionAlgorithm
exception DigitizationAlgorithm
Algorithm that turns simulated hits into measurements by truth smearing.
struct GeometricConfig
struct DigiComponentsConfig
class DigitizationConfig
struct DigitizationConfigurator
struct DigitizedParameters
struct ModuleValue
class ModuleClusters
exception PlanarSteppingAlgorithm
Create planar clusters from simulation hits.
struct ParameterSmearingConfig
exception FatrasSimulation
Fast track simulation using the Acts propagation and navigation.
exception DDG4DetectorConstruction
Construct the Geant4 detector from a DD4hep description.
exception DDG4DetectorConstructionFactory
class DetectorConstructionFactory
struct EventStore
Common event store for all Geant4 related sub algorithms.
exception GdmlDetectorConstruction
Construct the Geant4 detector from a Gdml file.
exception GdmlDetectorConstructionFactory
struct Geant4Handle
class Geant4Manager
Allows easy instantiation of a Geant4Handle object.
class Geant4SimulationBase
Abstracts common Geant4 Acts algorithm behaviour.
exception Geant4Simulation
Algorithm to run Geant4 simulation in the ActsExamples framework.
exception Geant4MaterialRecording
class MagneticFieldWrapper
class MaterialPhysicsList
Stripped down physics list to Geantinos and only Transport This speeds up the initialization of the MaterialRecording job.
class MaterialSteppingAction
Collects the RecordedMaterialSlab entities.
class ParticleKillAction
class ParticleTrackingAction
class PhysicsListFactory
A factory around G4VUserPhysicsList which allows on demand instantiation.
exception PhysicsListFactoryFunction
Convenience implementation of PhysicsListFactory from std::function.
class SensitiveSteppingAction
class SensitiveSurfaceMapper
class SimParticleTranslation
class SteppingActionList
exception EventRecording
exception EventGenerator
struct FixedMultiplicityGenerator
struct PoissonMultiplicityGenerator
class ParametricParticleGenerator
struct FixedVertexGenerator
struct GaussianVertexGenerator
class Pythia8Generator
exception VolumeAssociationTest
exception HepMCProcessExtractor
This class extracts a certain process from a HepMC event record.
class IMaterialWriter
class MaterialMapping
Initiates and executes material mapping.
class HitsPrinter
Print hits within some geometric region-of-interest.
class ParticlesPrinter
Print all particles.
class TrackParametersPrinter
Print track parameters.
class PropagationAlgorithm
this test algorithm performs test propagation within the Acts::Propagator
class PropagatorInterface
Propagator wrapper.
class ConcretePropagator
Concrete instance of a propagator.
struct HoughMeasurementStruct
exception HoughTransformSeeder
Construct track seeds from space points.
exception SeedingAlgorithm
Construct track seeds from space points.
exception SeedingFTFAlgorithm
exception SeedingOrthogonalAlgorithm
Construct track seeds from space points.
exception SpacePointMaker
exception TrackFindingAlgorithm
exception TrackParamsEstimationAlgorithm
exception PrototracksToParameters
exception TrackFindingAlgorithmExaTrkX
exception TrackFindingFromPrototrackAlgorithm
class AmbiguityResolutionML
exception AmbiguityResolutionMLAlgorithm
exception AmbiguityResolutionMLDBScanAlgorithm
exception RefittingAlgorithm
struct RefittingCalibrator
exception SurfaceSortingAlgorithm
class TrackFitterFunction
exception TrackFittingAlgorithm
exception ParticleSelector
Select particles by applying some selection cuts.
exception ParticleSmearing
exception TrackModifier
Select tracks by applying some selection cuts.
exception TrackParameterSelector
Select tracks by applying some selection cuts.
exception TruthSeedingAlgorithm
Construct track seeds from particles.
exception TruthSeedSelector
exception TruthTrackFinder
exception TruthVertexFinder
Group particles into proto vertices using truth information.
exception MeasurementMapSelector
exception PrototracksToSeeds
exception SeedsToPrototracks
exception TrackSelectorAlgorithm
Select tracks by applying some selection cuts.
exception TracksToTrajectories
exception TrajectoriesToPrototracks
exception AdaptiveMultiVertexFinderAlgorithm
exception IterativeVertexFinderAlgorithm
exception SingleSeedVertexFinderAlgorithm
exception TutorialVertexFinderAlgorithm
exception VertexFitterAlgorithm
struct ScalableBFieldContext
The ScalableBField-specific magnetic field context.
exception ScalableBField
A constant magnetic field that is scaled depending on the event context.
class ScalableBFieldService
class MockupSectorBuilder
struct TGeoDetector
class TGeoITkModuleSplitter
TGeoITkModuleSplitter.
struct Cluster
Simple struct holding cluster information.
struct ExtractedSimulationProcess
struct GeometryIdMultisetAccessor
exception IndexSourceLink
struct IndexSourceLinkAccessor
class MeasurementCalibrator
Abstract base class for measurement-based calibration.
class PassThroughCalibrator
class MeasurementCalibratorAdapter
class ScalingCalibrator
class SimSpacePoint
Space point representation of a measurement suitable for track seeding.
struct SimVertex
A simultated vertex e.g. from a physics process.
struct Trajectories
struct AlgorithmContext
Aggregated information to run one algorithm over one event.
class DataHandleBase
exception WriteDataHandle
exception ReadDataHandle
class IAlgorithm
class IContextDecorator
Decorator for the AlgorithmContext with additional event specific information.
class IReader
class IWriter
class RandomNumbers
< Mersenne Twister
class SequenceElement
class FpeFailure
Custom exception class so FPE failures can be caught.
class SequenceConfigurationException
class Sequencer
class WhiteBoard
class WriterT
class GroupBy
class Range
class DuplicationPlotTool
class EffPlotTool
class FakeRatePlotTool
class ResPlotTool
struct ParticleHitCount
Associate a particle to its hit count within a proto track.
class TrackSummaryPlotTool
class NeuralCalibrator
class CsvBFieldWriter
Writer for B-fields that outputs field data in CSV format.
exception CsvMeasurementReader
class CsvMeasurementWriter
class CsvMultiTrajectoryWriter
exception CsvParticleReader
exception CsvParticleWriter
exception CsvPlanarClusterReader
exception CsvPlanarClusterWriter
class CsvProtoTrackWriter
exception CsvSimHitReader
exception CsvSimHitWriter
exception CsvSpacePointReader
exception CsvSpacepointWriter
class CsvTrackingGeometryWriter
exception CsvTrackParameterReader
exception CsvTrackParameterWriter
struct ParticleData
struct SimHitData
struct TruthHitData
struct HitData
struct MeasurementSimHitLink
struct MeasurementData
struct CellData
struct CellDataLegacy
struct SurfaceData
struct LayerVolumeData
struct SpacePointData
struct SurfaceGridData
struct SpacepointData
struct TrackParameterData
struct ProtoTrackData
exception EDM4hepMeasurementReader
exception EDM4hepMeasurementWriter
class EDM4hepMultiTrajectoryWriter
exception EDM4hepParticleReader
exception EDM4hepParticleWriter
exception EDM4hepSimHitReader
exception EDM4hepSimHitWriter
class EDM4hepTrackReader
class EDM4hepTrackWriter
exception HepMC3AsciiReader
HepMC3 event reader.
exception HepMC3AsciiWriter
HepMC3 event writer.
class JsonMaterialWriter
class JsonSpacePointWriter
class JsonSurfacesWriter
exception RootNuclearInteractionParametersWriter
class ObjPropagationStepsWriter
class ObjSpacePointWriter
class ObjTrackingGeometryWriter
exception CKFPerformanceWriter
exception SeedingPerformanceWriter
exception TrackFinderPerformanceWriter
exception TrackFitterPerformanceWriter
class VertexPerformanceWriter
class RootAthenaNTupleReader
class RootBFieldWriter
class RootMaterialDecorator
Read the collection of SurfaceMaterial & VolumeMaterial.
class RootMaterialTrackReader
Reads in MaterialTrack information from a root file and fills it into a format to be understood by the MaterialMapping algorithm.
class RootMaterialTrackWriter
Writes out MaterialTrack collections from a root file.
class RootMaterialWriter
Material decorator from Root format.
class RootMeasurementWriter
class RootParticleReader
Reads in Particles information from a root file.
exception RootParticleWriter
class RootPlanarClusterWriter
class RootPropagationStepsWriter
class RootSimHitReader
exception RootSimHitWriter
exception RootSpacepointWriter
exception RootTrackParameterWriter
class RootTrajectoryStatesWriter
class RootTrajectorySummaryReader
Reads in TrackParameter information from a root file and fills it into a Acts::BoundTrackParameter format.
class RootTrajectorySummaryWriter
struct AccessorXYZ
struct AccessorPositionXYZ
exception SvgPointWriter
class SvgTrackingGeometryWriter
struct AlignedDetectorWithOptions
class GenericDetectorWithOptions
class IBaseDetector
class TelescopeDetectorWithOptions
class TGeoDetectorWithOptions
class DD4hepDetectorWithOptions
struct HelloData
An example data object to be shared via the event store.
class HelloLoggerAlgorithm
A simple algorithm that just prints hello world.
class HelloRandomAlgorithm
An example algorithm that uses the random number generator to generate data.
class HelloWhiteBoardAlgorithm
Example algorithm that reads/writes data from/to the event store.
Typedefs
using SmearingConfig = std::vector< ParameterSmearingConfig >
using RecordedMaterial = Acts::MaterialInteractor::result_type
Using some short hands for Recorded Material.
using RecordedMaterialTrack = std::pair< std::pair< Acts::Vector3, Acts::Vector3 >, RecordedMaterial >
using PropagationOutput = std::pair< std::vector< Acts::detail::Step >, RecordedMaterial >
Finally the output of the propagation test.
using HoughHist = vector2D< std::pair< int, std::unordered_set< unsigned >>>
using TrackHitList = std::map< const double, const Index >
using BetheHeitlerApprox = Acts::AtlasBetheHeitlerApprox< 6, 5 >
using HitSimHitsRange = Range< IndexMultimap< Index >::const_iterator >
A range within a hit-simhits map.
using ClusterContainer = std::vector< Cluster >
Clusters have a one-to-one relation with measurements.
using ExtractedSimulationProcessContainer = std::vector< ExtractedSimulationProcess >
template<typename T >
using GeometryIdMultiset = boost::container::flat_multiset< T, detail::CompareGeometryId >
template<typename T >
using GeometryIdMultimap = GeometryIdMultiset< std::pair< Acts::GeometryIdentifier, T >>
using Index = uint32_t
template<typename value_t >
using IndexMultimap = boost::container::flat_multimap< Index, value_t >
using IndexSourceLinkContainer = GeometryIdMultiset< IndexSourceLink >
using Measurement = ::Acts::BoundVariantMeasurement
Variable measurement type that can contain all possible combinations.
using MeasurementContainer = std::vector< Measurement >
using ProtoTrack = boost::container::small_vector< Index, 3 >
A proto track is a collection of hits identified by their indices.
using ProtoTrackContainer = std::vector< ProtoTrack >
Container of proto tracks. Each proto track is identified by its index.
using ProtoVertex = std::vector< Index >
A proto vertex is a collection of tracks identified by their indices.
using ProtoVertexContainer = std::vector< ProtoVertex >
Container of proto vertices. Each proto vertex is identified by its index.
using SimBarcode = ::ActsFatras::Barcode
using SimHit = ::ActsFatras::Hit
using SimHitContainer = GeometryIdMultiset< SimHit >
Store hits ordered by geometry identifier.
using SimParticle = ::ActsFatras::Particle
using SimParticleContainer = ::boost::container::flat_set< SimParticle, detail::CompareParticleId >
Store particles ordered by particle identifier.
using SimSeed = Acts::Seed< SimSpacePoint >
using SimSeedContainer = std::vector< SimSeed >
Container of sim seed.
using SimSpacePointContainer = std::vector< SimSpacePoint >
Container of space points.
using TrackParameters = ::Acts::BoundTrackParameters
(Reconstructed) track parameters e.g. close to the vertex.
using TrackParametersContainer = std::vector< TrackParameters >
Container of reconstructed track states for multiple tracks.
using TrackContainer = Acts::TrackContainer< Acts::VectorTrackContainer, Acts::VectorMultiTrajectory, std::shared_ptr >
using ConstTrackContainer = Acts::TrackContainer< Acts::ConstVectorTrackContainer, Acts::ConstVectorMultiTrajectory, std::shared_ptr >
using TrajectoriesContainer = std::vector< Trajectories >
Container for multiple trajectories.
using RandomEngine = std::mt19937
The random number generator used in the framework.
using IterationCallback) = void(*)(
using DigiConfigContainer = Acts::GeometryHierarchyMap< DigiComponentsConfig >
using DigiConfigConverter = Acts::GeometryHierarchyMapJsonConverter< DigiComponentsConfig >
using PropagationSteps = std::vector< Acts::detail::Step >
using TrackParameterWriter = WriterT< TrackParametersContainer >
using HelloDataCollection = std::vector< HelloData >
Enumerations
enum HoughHitType { SP = 0, MEASUREMENT = 1 }
enum ProcessCode
enum JsonFormat : uint8_t
enum OutputFormat : uint8_t
Functions
Measurement createMeasurement (const DigitizedParameters &dParams, const IndexSourceLink &isl) noexcept(false)
template<size_t kMeasDIM>
std::tuple< std::array
< Acts::BoundIndices, kMeasDIM >
, Acts::ActsVector< kMeasDIM >
, Acts::ActsSquareMatrix
< kMeasDIM > > measurementConstituents (const DigitizedParameters &dParams)
int getCellRow (const ModuleValue &mval)
int getCellColumn (const ActsExamples::ModuleValue &mval)
int & getCellLabel (ActsExamples::ModuleValue &mval)
void clusterAddCell (std::vector< ModuleValue > &cl, const ModuleValue &ce)
std::shared_ptr
< TrackFitterFunction > makeKalmanFitterFunction (std::shared_ptr< const Acts::TrackingGeometry > trackingGeometry, std::shared_ptr< const Acts::MagneticFieldProvider > magneticField, bool multipleScattering=true, bool energyLoss=true, double reverseFilteringMomThreshold=0.0, Acts::FreeToBoundCorrection freeToBoundCorrection=Acts::FreeToBoundCorrection(), const Acts::Logger &logger=*Acts::getDefaultLogger("Kalman", Acts::Logging::INFO))
std::shared_ptr
< TrackFitterFunction > makeGsfFitterFunction (std::shared_ptr< const Acts::TrackingGeometry > trackingGeometry, std::shared_ptr< const Acts::MagneticFieldProvider > magneticField, BetheHeitlerApprox betheHeitlerApprox, std::size_t maxComponents, double weightCutoff, Acts::MixtureReductionMethod finalReductionMethod, bool abortOnError, bool disableAllMaterialHandling, const Acts::Logger &logger)
std::shared_ptr
< TrackFitterFunction > makeGlobalChiSquareFitterFunction (std::shared_ptr< const Acts::TrackingGeometry > trackingGeometry, std::shared_ptr< const Acts::MagneticFieldProvider > magneticField, bool multipleScattering=true, bool energyLoss=true, Acts::FreeToBoundCorrection freeToBoundCorrection=Acts::FreeToBoundCorrection(), const Acts::Logger &logger=*Acts::getDefaultLogger("Gx2f", Acts::Logging::INFO))
std::vector< const
Acts::BoundTrackParameters * > makeTrackParametersPointerContainer (const TrackParametersContainer &trackParameters)
auto makeParameterContainers (const ActsExamples::AlgorithmContext &ctx, const ReadDataHandle< std::vector< Acts::BoundTrackParameters >> &inputTrackParametersHandle, const ReadDataHandle< TrajectoriesContainer > &inputTrajectoriesHandle)
ProtoVertexContainer makeProtoVertices (const TrackParametersContainer &trackParameters, const std::vector< Acts::Vertex< Acts::BoundTrackParameters >> &vertices)
detail::InterpolatedMagneticField2 makeMagneticFieldMapRzFromRoot (const std::function< size_t(std::array< size_t, 2 > binsRZ, std::array< size_t, 2 > nBinsRZ)> &localToGlobalBin, const std::string &fieldMapFile, const std::string &treeName, Acts::ActsScalar lengthUnit, Acts::ActsScalar BFieldUnit, bool firstQuadrant=false)
detail::InterpolatedMagneticField3 makeMagneticFieldMapXyzFromRoot (const std::function< size_t(std::array< size_t, 3 > binsXYZ, std::array< size_t, 3 > nBinsXYZ)> &localToGlobalBin, const std::string &fieldMapFile, const std::string &treeName, Acts::ActsScalar lengthUnit, Acts::ActsScalar BFieldUnit, bool firstOctant=false)
detail::InterpolatedMagneticField2 makeMagneticFieldMapRzFromText (const std::function< size_t(std::array< size_t, 2 > binsRZ, std::array< size_t, 2 > nBinsRZ)> &localToGlobalBin, const std::string &fieldMapFile, Acts::ActsScalar lengthUnit, Acts::ActsScalar BFieldUnit, bool firstQuadrant=false)
detail::InterpolatedMagneticField3 makeMagneticFieldMapXyzFromText (const std::function< size_t(std::array< size_t, 3 > binsXYZ, std::array< size_t, 3 > nBinsXYZ)> &localToGlobalBin, const std::string &fieldMapFile, Acts::ActsScalar lengthUnit, Acts::ActsScalar BFieldUnit, bool firstOctant=false)
void from_json (const nlohmann::json &j, ActsExamples::TGeoITkModuleSplitter::Config &msc)
void to_json (nlohmann::json &j, const ActsExamples::TGeoITkModuleSplitter::Config &msc)
template<typename T >
void from_json (const nlohmann::json &j, ActsExamples::TGeoDetector::Config::LayerTriplet< T > &ltr)
Read layer configuration triplets.
template<typename T >
void to_json (nlohmann::json &j, const ActsExamples::TGeoDetector::Config::LayerTriplet< T > &ltr)
Write layer configuration triplets.
void from_json (const nlohmann::json &j, ActsExamples::TGeoDetector::Config::Volume &vol)
Read volume struct.
void to_json (nlohmann::json &j, const TGeoDetector::Config::Volume &vol)
Write volume struct.
std::tuple< Acts::Vector2,
Acts::Vector4, Acts::Vector3 > averageSimHits (const Acts::GeometryContext &gCtx, const Acts::Surface &surface, const SimHitContainer &simHits, const HitSimHitsRange &hitSimHitsRange, const Acts::Logger &logger)
template<typename T >
Range< typename
GeometryIdMultiset< T >
::const_iterator > selectVolume (const GeometryIdMultiset< T > &container, Acts::GeometryIdentifier::Value volume)
Select all elements within the given volume.
template<typename T >
auto selectVolume (const GeometryIdMultiset< T > &container, Acts::GeometryIdentifier id)
Select all elements within the given volume.
template<typename T >
Range< typename
GeometryIdMultiset< T >
::const_iterator > selectLayer (const GeometryIdMultiset< T > &container, Acts::GeometryIdentifier::Value volume, Acts::GeometryIdentifier::Value layer)
Select all elements within the given layer.
template<typename T >
auto selectLayer (const GeometryIdMultiset< T > &container, Acts::GeometryIdentifier id)
template<typename T >
Range< typename
GeometryIdMultiset< T >
::const_iterator > selectModule (const GeometryIdMultiset< T > &container, Acts::GeometryIdentifier geoId)
Select all elements for the given module / sensitive surface.
template<typename T >
auto selectModule (const GeometryIdMultiset< T > &container, Acts::GeometryIdentifier::Value volume, Acts::GeometryIdentifier::Value layer, Acts::GeometryIdentifier::Value module)
Select all elements for the given module / sensitive surface.
template<typename T >
Range< typename
GeometryIdMultiset< T >
::const_iterator > selectLowestNonZeroGeometryObject (const GeometryIdMultiset< T > &container, Acts::GeometryIdentifier geoId)
template<typename T >
GroupBy< typename
GeometryIdMultiset< T >
::const_iterator,
detail::GeometryIdGetter > groupByModule (const GeometryIdMultiset< T > &container)
Iterate over groups of elements belonging to each module/ sensitive surface.
template<typename value_t >
boost::container::flat_multimap
< value_t, Index > invertIndexMultimap (const IndexMultimap< value_t > &multimap)
GroupBy
< SimParticleContainer::const_iterator,
detail::PrimaryVertexIdGetter > groupByPrimaryVertex (const SimParticleContainer &container)
Iterate over groups of particles belonging to the same primary vertex.
GroupBy
< SimParticleContainer::const_iterator,
detail::SecondaryVertexIdGetter > groupBySecondaryVertex (const SimParticleContainer &container)
bool operator== (const SimSpacePoint &lhs, const SimSpacePoint &rhs)
std::ostream & operator<< (std::ostream &os, const ActsExamples::Sequencer::FpeMask &m)
ProtoTrack seedToPrototrack (const SimSeed &seed)
const SimSpacePoint * findSpacePointForIndex (Index index, const SimSpacePointContainer &spacepoints)
SimSeed prototrackToSeed (const ProtoTrack &track, const SimSpacePointContainer &spacepoints)
template<typename Container , typename KeyGetter >
auto makeGroupBy (const Container &container, KeyGetter keyGetter) -> GroupBy< decltype(std::begin(container)), KeyGetter >
Construct the group-by proxy for a container.
std::string ensureWritableDirectory (const std::string &dir)
std::string joinPaths (const std::string &dir, const std::string &name)
Join dir and name into one path with correct handling of empty dirs.
std::string perEventFilepath (const std::string &dir, const std::string &name, size_t event)
std::pair< size_t, size_t > determineEventFilesRange (const std::string &dir, const std::string &name)
template<typename Iterator >
Range< Iterator > makeRange (Iterator begin, Iterator end)
template<typename Iterator >
Range< Iterator > makeRange (std::pair< Iterator, Iterator > range)
void identifyContributingParticles (const IndexMultimap< ActsFatras::Barcode > &hitParticlesMap, const ProtoTrack &protoTrack, std::vector< ParticleHitCount > &particleHitCounts)
void identifyContributingParticles (const IndexMultimap< ActsFatras::Barcode > &hitParticlesMap, const Trajectories &trajectories, size_t trajectoryTip, std::vector< ParticleHitCount > &particleHitCounts)
template void CsvBFieldWriter::run< CsvBFieldWriter::CoordinateType::XYZ, true > (const Config< CoordinateType::XYZ, true > &, Acts::Logging::Level)
template void CsvBFieldWriter::run< CsvBFieldWriter::CoordinateType::RZ, true > (const Config< CoordinateType::RZ, true > &, Acts::Logging::Level)
template void CsvBFieldWriter::run< CsvBFieldWriter::CoordinateType::XYZ, false > (const Config< CoordinateType::XYZ, false > &, Acts::Logging::Level)
template void CsvBFieldWriter::run< CsvBFieldWriter::CoordinateType::RZ, false > (const Config< CoordinateType::RZ, false > &, Acts::Logging::Level)
void to_json (nlohmann::json &j, const ParameterSmearingConfig &psc)
void from_json (const nlohmann::json &j, ParameterSmearingConfig &psc)
void to_json (nlohmann::json &j, const GeometricConfig &gdc)
void from_json (const nlohmann::json &j, GeometricConfig &gdc)
void to_json (nlohmann::json &j, const SmearingConfig &sdc)
void from_json (const nlohmann::json &j, SmearingConfig &sdc)
void to_json (nlohmann::json &j, const DigiComponentsConfig &dc)
void from_json (const nlohmann::json &j, DigiComponentsConfig &dc)
Acts::GeometryHierarchyMap
< DigiComponentsConfig > readDigiConfigFromJson (const std::string &path)
void writeDigiConfigToJson (const Acts::GeometryHierarchyMap< DigiComponentsConfig > &cfg, const std::string &path)
void from_json (const nlohmann::json &data, Acts::GeometryIdentifier &geoId)
void to_json (nlohmann::json &data, const Acts::GeometryIdentifier &geoId)
void from_json (const nlohmann::json &data, std::vector< Acts::GeometryIdentifier > &geoIdList)
void to_json (nlohmann::json &data, const std::vector< Acts::GeometryIdentifier > &geoIdList)
std::vector
< Acts::GeometryIdentifier > readJsonGeometryList (const std::string &path)
void writeJsonGeometryList (const std::vector< Acts::GeometryIdentifier > &geoIdList, const std::string &path)
void setupMaterialRecording (const ActsExamples::Options::Variables &vars, ActsExamples::Sequencer &sequencer, std::shared_ptr< DetectorConstructionFactory > detectorConstructionFactory)
void setupGeant4Simulation (const ActsExamples::Options::Variables &vars, ActsExamples::Sequencer &sequencer, std::shared_ptr< DetectorConstructionFactory > detectorConstructionFactory, std::shared_ptr< const Acts::TrackingGeometry > trackingGeometry, std::shared_ptr< const Acts::MagneticFieldProvider > magneticField)
int runMaterialRecording (const ActsExamples::Options::Variables &vars, std::shared_ptr< ActsExamples::DetectorConstructionFactory > detectorConstructionFactory)
int runGeant4Simulation (const ActsExamples::Options::Variables &vars, std::shared_ptr< ActsExamples::DetectorConstructionFactory > detectorConstructionFactory, std::shared_ptr< const Acts::TrackingGeometry > trackingGeometry)
int runMaterialRecording (const ActsExamples::Options::Variables &vars, std::shared_ptr< DetectorConstructionFactory > detectorConstructionFactory)
int runGeant4Simulation (const ActsExamples::Options::Variables &vars, std::shared_ptr< DetectorConstructionFactory > detectorConstructionFactory, std::shared_ptr< const Acts::TrackingGeometry > trackingGeometry)
std::ostream & operator<< (std::ostream &os, const HelloData &data)
Variables
thread_local std::vector
< std::shared_ptr
< HoughMeasurementStruct > > houghMeasurementStructs
constexpr double NaNdouble = std::numeric_limits<double>::quiet_NaN()
NaN values for TTree variables.
constexpr float NaNfloat = std::numeric_limits<float>::quiet_NaN()
constexpr float NaNint = std::numeric_limits<int>::quiet_NaN()
static Acts::Svg::Style s_layerStyle = layerStyle()
static Acts::Svg::Style s_pointStyle = pointStyle()
static Acts::Svg::Style s_infoStyle = infoStyle()
static
Acts::Svg::TrackingGeometryConverter::Options s_trackingGeometryOptions
static
Acts::Svg::TrackingGeometryConverter::Options s_backgroundTrackingGeometryOptions = backgroundGeometryOptions()
Detailed Description
In case several sensitive modules have the same segmentation it can and should be shared between these modules to save memory and time. In Acts the Acts::DigitizationModule is used to describe the geometric digitization on a detector module. This Acts::DigitizationModule should be shared amongst the modules with the same segmentation. In order to create it there are currently two helper functions implemented (ActsExamples::DD4hep::rectangleDigiModule(),ActsExamples::DD4hep::trapezoidalDigiModule) which return the digitization module from DD4hep input. Afterwards an ActsExtension from the same Acts::DigitizationModule can be created and attached for all modules sharing the same segmentation.
Below you can find an example (in pseudo code) how to share the same Acts::DigitizationModule amongst modules (DetElements) which have the same segmentation in your DD4hep detector constructor:
Create the Acts::DigitizationModule which should be shared amongst the different modules using the global function with the dimensions of the module and its DD4hep Segmentation. Where sensDet is the corresponding DD4hep SensitiveDetector.
auto digiModule = Acts::rectangularDigiModule(halflengthX,
                                              halflnegthY,
                                              thickness,
                                              sensDet.readout().segmentation());
Now loop over all modules which have the same segmentation, create the Acts::ActsExtension from the digitization module and attach the extension to the DD4hep::DetElement of the module (named 'moduleDetelement' here),
for ('loop over modules') {
  ...
      Acts::ActsExtension* moduleExtension
      = new Acts::ActsExtension(digiModule);
  moduleDetElement.addExtension<Acts::ActsExtension>(moduleExtension);
}
Parameters
digiModule the Acts::DigitizationModule
Note
in order to create the shared Acts::DigitizationModule from DD4hep segmentation please use the global functions rectangleDigiModule() and trapezoidalDigiModule().
If one wants to build the Acts Tracking Geometry with DD4hep input these extension should be used during the construction of the DD4hep geometry i.e. in the DD4hep detector constructors. First the ActsExtension configuration object should be created and then attached to the DD4hep DetElement.
Example for a layer DetElement (layer_detElement) where also parameters for material mapping are handed over:
Acts::ActsExtension::Config layConfig;
layConfig.isLayer               = true;
layConfig.axes                  = "XZy";
layConfig.materialBins1         = 50;
layConfig.materialBins2                        = 100;
layConfig.layerMaterialPosition = Acts::LayerMaterialPos::inner
Acts::ActsExtension* layerExtension = new
Acts::ActsExtension(layConfig);
layer_detElement.addExtension<Acts::ActsExtension>(layerExtension);
In case several sensitive detector modules have the same segmentation an extension using the second constructor (with the segmentation as parameter) (or the function setSegmentation()) should be created once and then be attached to all the DetElements which have that same segmentation. In this way only one Acts::DigitizationModule is created and shared between all detector elements with the same segmentation which saves memory and time. If this extension is not set and the DetElement is sensitive and has a readout, a unique Acts::DigitizationModule will be created for this DetElement.
Typedef Documentation
using ActsExamples::BetheHeitlerApprox = typedef Acts::AtlasBetheHeitlerApprox<6, 5>
This type is used in the Examples framework for the Bethe-Heitler approximation
Definition at line 75 of file TrackFitterFunction.hpp.
View newest version in sPHENIX GitHub at line 75 of file TrackFitterFunction.hpp
using ActsExamples::ClusterContainer = typedef std::vector<Cluster>
Clusters have a one-to-one relation with measurements.
Definition at line 26 of file Cluster.hpp.
View newest version in sPHENIX GitHub at line 26 of file Cluster.hpp
using ActsExamples::ConstTrackContainer = typedef Acts::TrackContainer<Acts::ConstVectorTrackContainer, Acts::ConstVectorMultiTrajectory, std::shared_ptr>
Definition at line 31 of file Track.hpp.
View newest version in sPHENIX GitHub at line 31 of file Track.hpp
using ActsExamples::DigiConfigContainer = typedef Acts::GeometryHierarchyMap<DigiComponentsConfig>
Definition at line 47 of file JsonDigitizationConfig.hpp.
View newest version in sPHENIX GitHub at line 47 of file JsonDigitizationConfig.hpp
using ActsExamples::DigiConfigConverter = typedef Acts::GeometryHierarchyMapJsonConverter<DigiComponentsConfig>
Definition at line 49 of file JsonDigitizationConfig.hpp.
View newest version in sPHENIX GitHub at line 49 of file JsonDigitizationConfig.hpp
using ActsExamples::ExtractedSimulationProcessContainer = typedef std::vector<ExtractedSimulationProcess>
Definition at line 26 of file ExtractedSimulationProcess.hpp.
View newest version in sPHENIX GitHub at line 26 of file ExtractedSimulationProcess.hpp
template<typename T > using ActsExamples::GeometryIdMultimap = typedef GeometryIdMultiset<std::pair<Acts::GeometryIdentifier, T>>
Store elements indexed by an geometry id.
Template Parameters
T type to be stored
The behaviour is the same as for the GeometryIdMultiset except that the stored elements do not know their geometry id themself. When iterating the iterator elements behave as for the std::map, i.e.
for (const auto& entry: elements) {
    auto id = entry.first; // geometry id
    const auto& el = entry.second; // stored element
Definition at line 102 of file GeometryContainers.hpp.
View newest version in sPHENIX GitHub at line 102 of file GeometryContainers.hpp
template<typename T > using ActsExamples::GeometryIdMultiset = typedef boost::container::flat_multiset<T, detail::CompareGeometryId>
Store elements that know their detector geometry id, e.g. simulation hits.
Template Parameters
T type to be stored, must be compatible with CompareGeometryId
The container stores an arbitrary number of elements for any geometry id. Elements can be retrieved via the geometry id; elements can be selected for a specific geometry id or for a larger range, e.g. a volume or a layer within the geometry hierarchy using the helper functions below. Elements can also be accessed by index that uniquely identifies each element regardless of geometry id.
Definition at line 85 of file GeometryContainers.hpp.
View newest version in sPHENIX GitHub at line 85 of file GeometryContainers.hpp
using ActsExamples::HelloDataCollection = typedef std::vector<HelloData>
Definition at line 29 of file HelloData.hpp.
View newest version in sPHENIX GitHub at line 29 of file HelloData.hpp
using ActsExamples::HitSimHitsRange = typedef Range<IndexMultimap<Index>::const_iterator>
A range within a hit-simhits map.
Definition at line 24 of file AverageSimHits.hpp.
View newest version in sPHENIX GitHub at line 24 of file AverageSimHits.hpp
using ActsExamples::HoughHist = typedef vector2D<std::pair<int, std::unordered_set<unsigned>>>
Used in multiple places. The 2d vector refers to the 2d houghHist. For a single layer, the int refers to the number of hits in the bin of the houghHist For the total houghHist, the int counts the number of layers with one or more hit in that bin An houghHist is a 2d array of points, where each point has a value. The value starts as the number of hit layers, but can change with effects like a convolution. Also stored are indices of all hits that contributed to each bin. Size m_houghHistSize_y * m_houghHistSize_x. (NOTE y is row coordinate) For now, what is stored is actually the index of the object in the vectors, so we can get the Index layer
Definition at line 131 of file HoughTransformSeeder.hpp.
View newest version in sPHENIX GitHub at line 131 of file HoughTransformSeeder.hpp
using ActsExamples::Index = typedef uint32_t
Index type to reference elements in a container.
We do not expect to have more than 2^32 elements in any given container so a fixed sized integer type is sufficient.
Definition at line 21 of file Index.hpp.
View newest version in sPHENIX GitHub at line 21 of file Index.hpp
template<typename value_t > using ActsExamples::IndexMultimap = typedef boost::container::flat_multimap<Index, value_t>
Store elements that are identified by an index, e.g. in another container.
Each index can have zero or more associated elements. A typical case could be to store all generating particles for a hit where the hit is identified by its index in the hit container.
Definition at line 29 of file Index.hpp.
View newest version in sPHENIX GitHub at line 29 of file Index.hpp
using ActsExamples::IndexSourceLinkContainer = typedef GeometryIdMultiset<IndexSourceLink>
Container of index source links.
Since the source links provide a .geometryId() accessor, they can be stored in an ordered geometry container.
Definition at line 77 of file IndexSourceLink.hpp.
View newest version in sPHENIX GitHub at line 77 of file IndexSourceLink.hpp
using ActsExamples::IterationCallback = typedef void (*)(
Definition at line 40 of file Sequencer.hpp.
View newest version in sPHENIX GitHub at line 40 of file Sequencer.hpp
using ActsExamples::Measurement = typedef ::Acts::BoundVariantMeasurement
Variable measurement type that can contain all possible combinations.
Definition at line 18 of file Measurement.hpp.
View newest version in sPHENIX GitHub at line 18 of file Measurement.hpp
using ActsExamples::MeasurementContainer = typedef std::vector<Measurement>
Container of measurements.
In contrast to the source links, the measurements themself must not be orderable. The source links stored in the measurements are treated as opaque here and no ordering is enforced on the stored measurements.
Definition at line 25 of file Measurement.hpp.
View newest version in sPHENIX GitHub at line 25 of file Measurement.hpp
using ActsExamples::PropagationOutput = typedef std::pair<std::vector<Acts::detail::Step>, RecordedMaterial>
Finally the output of the propagation test.
Definition at line 62 of file PropagationAlgorithm.hpp.
View newest version in sPHENIX GitHub at line 62 of file PropagationAlgorithm.hpp
using ActsExamples::PropagationSteps = typedef std::vector<Acts::detail::Step>
Definition at line 27 of file RootPropagationStepsWriter.hpp.
View newest version in sPHENIX GitHub at line 27 of file RootPropagationStepsWriter.hpp
using ActsExamples::ProtoTrack = typedef boost::container::small_vector<Index, 3>
A proto track is a collection of hits identified by their indices.
Definition at line 20 of file ProtoTrack.hpp.
View newest version in sPHENIX GitHub at line 20 of file ProtoTrack.hpp
using ActsExamples::ProtoTrackContainer = typedef std::vector<ProtoTrack>
Container of proto tracks. Each proto track is identified by its index.
Definition at line 22 of file ProtoTrack.hpp.
View newest version in sPHENIX GitHub at line 22 of file ProtoTrack.hpp
using ActsExamples::ProtoVertex = typedef std::vector<Index>
A proto vertex is a collection of tracks identified by their indices.
Definition at line 18 of file ProtoVertex.hpp.
View newest version in sPHENIX GitHub at line 18 of file ProtoVertex.hpp
using ActsExamples::ProtoVertexContainer = typedef std::vector<ProtoVertex>
Container of proto vertices. Each proto vertex is identified by its index.
Definition at line 20 of file ProtoVertex.hpp.
View newest version in sPHENIX GitHub at line 20 of file ProtoVertex.hpp
using ActsExamples::RandomEngine = typedef std::mt19937
The random number generator used in the framework.
Definition at line 28 of file RandomNumbers.hpp.
View newest version in sPHENIX GitHub at line 28 of file RandomNumbers.hpp
using ActsExamples::RecordedMaterial = typedef Acts::MaterialInteractor::result_type
Using some short hands for Recorded Material.
Definition at line 52 of file PropagationAlgorithm.hpp.
View newest version in sPHENIX GitHub at line 52 of file PropagationAlgorithm.hpp
using ActsExamples::RecordedMaterialTrack = typedef std::pair<std::pair<Acts::Vector3, Acts::Vector3>, RecordedMaterial>
And recorded material track
this is start: position, start momentum and the Recorded material
Definition at line 58 of file PropagationAlgorithm.hpp.
View newest version in sPHENIX GitHub at line 58 of file PropagationAlgorithm.hpp
using ActsExamples::SimBarcode = typedef ::ActsFatras::Barcode
Definition at line 16 of file SimHit.hpp.
View newest version in sPHENIX GitHub at line 16 of file SimHit.hpp
using ActsExamples::SimHit = typedef ::ActsFatras::Hit
Definition at line 18 of file SimHit.hpp.
View newest version in sPHENIX GitHub at line 18 of file SimHit.hpp
using ActsExamples::SimHitContainer = typedef GeometryIdMultiset<SimHit>
Store hits ordered by geometry identifier.
Definition at line 20 of file SimHit.hpp.
View newest version in sPHENIX GitHub at line 20 of file SimHit.hpp
using ActsExamples::SimParticle = typedef ::ActsFatras::Particle
Definition at line 50 of file SimParticle.hpp.
View newest version in sPHENIX GitHub at line 50 of file SimParticle.hpp
using ActsExamples::SimParticleContainer = typedef ::boost::container::flat_set<SimParticle, detail::CompareParticleId>
Store particles ordered by particle identifier.
Definition at line 53 of file SimParticle.hpp.
View newest version in sPHENIX GitHub at line 53 of file SimParticle.hpp
using ActsExamples::SimSeed = typedef Acts::Seed<SimSpacePoint>
Definition at line 18 of file SimSeed.hpp.
View newest version in sPHENIX GitHub at line 18 of file SimSeed.hpp
using ActsExamples::SimSeedContainer = typedef std::vector<SimSeed>
Container of sim seed.
Definition at line 20 of file SimSeed.hpp.
View newest version in sPHENIX GitHub at line 20 of file SimSeed.hpp
using ActsExamples::SimSpacePointContainer = typedef std::vector<SimSpacePoint>
Container of space points.
Definition at line 161 of file SimSpacePoint.hpp.
View newest version in sPHENIX GitHub at line 161 of file SimSpacePoint.hpp
using ActsExamples::SmearingConfig = typedef std::vector<ParameterSmearingConfig>
Definition at line 28 of file SmearingConfig.hpp.
View newest version in sPHENIX GitHub at line 28 of file SmearingConfig.hpp
using ActsExamples::TrackContainer = typedef Acts::TrackContainer<Acts::VectorTrackContainer, Acts::VectorMultiTrajectory, std::shared_ptr>
Definition at line 27 of file Track.hpp.
View newest version in sPHENIX GitHub at line 27 of file Track.hpp
using ActsExamples::TrackHitList = typedef std::map<const double, const Index>
Definition at line 30 of file SurfaceSortingAlgorithm.hpp.
View newest version in sPHENIX GitHub at line 30 of file SurfaceSortingAlgorithm.hpp
using ActsExamples::TrackParameters = typedef ::Acts::BoundTrackParameters
(Reconstructed) track parameters e.g. close to the vertex.
Definition at line 21 of file Track.hpp.
View newest version in sPHENIX GitHub at line 21 of file Track.hpp
using ActsExamples::TrackParametersContainer = typedef std::vector<TrackParameters>
Container of reconstructed track states for multiple tracks.
Definition at line 23 of file Track.hpp.
View newest version in sPHENIX GitHub at line 23 of file Track.hpp
using ActsExamples::TrackParameterWriter = typedef WriterT<TrackParametersContainer>
Definition at line 33 of file RootTrackParameterWriter.hpp.
View newest version in sPHENIX GitHub at line 33 of file RootTrackParameterWriter.hpp
using ActsExamples::TrajectoriesContainer = typedef std::vector<Trajectories>
Container for multiple trajectories.
Definition at line 110 of file Trajectories.hpp.
View newest version in sPHENIX GitHub at line 110 of file Trajectories.hpp
Enumeration Type Documentation
enum ActsExamples::HoughHitType
Enumerator:
SP
MEASUREMENT
Definition at line 133 of file HoughTransformSeeder.hpp.
View newest version in sPHENIX GitHub at line 133 of file HoughTransformSeeder.hpp
enum ActsExamples::JsonFormat : uint8_t
Definition at line 46 of file JsonMaterialWriter.hpp.
View newest version in sPHENIX GitHub at line 46 of file JsonMaterialWriter.hpp
enum ActsExamples::OutputFormat : uint8_t
Definition at line 22 of file CommonOptions.hpp.
View newest version in sPHENIX GitHub at line 22 of file CommonOptions.hpp
enum ActsExamples::ProcessCode
Definition at line 12 of file ProcessCode.hpp.
View newest version in sPHENIX GitHub at line 12 of file ProcessCode.hpp
Function Documentation
std::tuple<Acts::Vector2, Acts::Vector4, Acts::Vector3> ActsExamples::averageSimHits (const Acts::GeometryContext & gCtx, const Acts::Surface & surface, const SimHitContainer & simHits, const HitSimHitsRange & hitSimHitsRange, const Acts::Logger & logger) inline
Create (average) truth representation for selected simulated hits.
Parameters
gCtx The geometry context for this
surface The reference surface of the measurement
simHits The simulated hits container
hitSimHitsRange Selection of simulated hits from the container
Returns
a local position, a 4D global position, a direction
If more than one simulated hit is selected, the average truth information is returned.
Definition at line 36 of file AverageSimHits.hpp.
View newest version in sPHENIX GitHub at line 36 of file AverageSimHits.hpp
References _, ACTS_WARNING, Acts::GeometryObject::geometryId(), Acts::Surface::globalToLocal(), n, and physmon_ckf_tracking::u.
Referenced by ActsExamples::RootTrackParameterWriter::writeT(), ActsExamples::RootTrajectoryStatesWriter::writeT(), and ActsExamples::RootMeasurementWriter::writeT().
void ActsExamples::clusterAddCell (std::vector< ModuleValue > & cl, const ModuleValue & ce)
Definition at line 88 of file ModuleClusters.cpp.
View newest version in sPHENIX GitHub at line 88 of file ModuleClusters.cpp
Referenced by Acts::Ccl::internal::mergeClustersImpl().
ActsExamples::Measurement ActsExamples::createMeasurement (const DigitizedParameters & dParams, const IndexSourceLink & isl) noexcept
Helper method for created a measurement from digitized parameters
Parameters
dParams The digitized parameters of variable size
isl The indexed source link for the measurement
To be used also by the e I/O system
Returns
a variant measurement
Definition at line 19 of file MeasurementCreation.cpp.
View newest version in sPHENIX GitHub at line 19 of file MeasurementCreation.cpp
References Acts::Test::cov, ActsExamples::DigitizedParameters::indices, testing::internal::move(), to_string(), and physmon_ckf_tracking::u.
Referenced by ActsExamples::DigitizationAlgorithm::execute(), ActsExamples::CsvMeasurementReader::read(), and ActsExamples::EDM4hepUtil::readMeasurement().
template void ActsExamples::CsvBFieldWriter::run< CsvBFieldWriter::CoordinateType::RZ, false > (const Config< CoordinateType::RZ, false > & , Acts::Logging::Level)
template void ActsExamples::CsvBFieldWriter::run< CsvBFieldWriter::CoordinateType::RZ, true > (const Config< CoordinateType::RZ, true > & , Acts::Logging::Level)
template void ActsExamples::CsvBFieldWriter::run< CsvBFieldWriter::CoordinateType::XYZ, false > (const Config< CoordinateType::XYZ, false > & , Acts::Logging::Level)
template void ActsExamples::CsvBFieldWriter::run< CsvBFieldWriter::CoordinateType::XYZ, true > (const Config< CoordinateType::XYZ, true > & , Acts::Logging::Level)
std::pair< size_t, size_t > ActsExamples::determineEventFilesRange (const std::string & dir, const std::string & name)
Determine the range of available events in a directory of per-event files.
dir input directory, current directory if empty name base filename
Returns
first and last+1 event number
{0, 0} when no matching files could be found
Event files must be named [<dir>/]event<XXXXXXXXX>-<name> to be considered
Definition at line 61 of file Paths.cpp.
View newest version in sPHENIX GitHub at line 61 of file Paths.cpp
References ACTS_LOCAL_LOGGER, ACTS_VERBOSE, event, Acts::Concepts::exists, f, filename, Acts::getDefaultLogger(), Acts::Logging::INFO, Acts::UnitConstants::min, path, and physmon_ckf_tracking::u.
Referenced by ActsExamples::CsvMeasurementReader::CsvMeasurementReader(), and ActsExamples::CsvSpacePointReader::CsvSpacePointReader().
std::string ActsExamples::ensureWritableDirectory (const std::string & dir)
Ensure that the given directory exists and is writable.
Returns
Canonical path to the directory.
Will create missing directories and throw on any error.
Definition at line 25 of file Paths.cpp.
View newest version in sPHENIX GitHub at line 25 of file Paths.cpp
References trento::random::canonical(), Acts::Concepts::exists, and path.
Referenced by main(), runDetectorAlignment(), runDigitizationExample(), runHoughExample(), runMaterialRecording(), runMeasurementsToSP(), runRecCKFTracks(), runRecTruthTracks(), runSeedingExample(), and ActsExamples::Simulation::setupOutput().
const ActsExamples::SimSpacePoint * ActsExamples::findSpacePointForIndex (ActsExamples::Index index, const SimSpacePointContainer & spacepoints)
Definition at line 30 of file EventDataTransforms.cpp.
View newest version in sPHENIX GitHub at line 30 of file EventDataTransforms.cpp
References index, and ActsExamples::SimSpacePoint::sourceLinks().
Referenced by prototrackToSeed(), and ActsExamples::CsvProtoTrackWriter::writeT().
void ActsExamples::from_json (const nlohmann::json & data, Acts::GeometryIdentifier & geoId)
Definition at line 14 of file JsonGeometryList.cpp.
View newest version in sPHENIX GitHub at line 14 of file JsonGeometryList.cpp
References Jetscape::null, Acts::GeometryIdentifier::setApproach(), Acts::GeometryIdentifier::setBoundary(), Acts::GeometryIdentifier::setLayer(), Acts::GeometryIdentifier::setSensitive(), Acts::GeometryIdentifier::setVolume(), and physmon_ckf_tracking::u.
void ActsExamples::from_json (const nlohmann::json & data, std::vector< Acts::GeometryIdentifier > & geoIdList)
Definition at line 43 of file JsonGeometryList.cpp.
View newest version in sPHENIX GitHub at line 43 of file JsonGeometryList.cpp
References entry, and Acts::from_json().
void ActsExamples::from_json (const nlohmann::json & j, ActsExamples::ParameterSmearingConfig & psc)
Definition at line 120 of file JsonDigitizationConfig.cpp.
View newest version in sPHENIX GitHub at line 120 of file JsonDigitizationConfig.cpp
References Acts::from_json(), ActsExamples::ParameterSmearingConfig::index, and ActsExamples::ParameterSmearingConfig::smearFunction.
void ActsExamples::from_json (const nlohmann::json & j, ActsExamples::GeometricConfig & gdc)
Definition at line 140 of file JsonDigitizationConfig.cpp.
View newest version in sPHENIX GitHub at line 140 of file JsonDigitizationConfig.cpp
References ActsExamples::GeometricConfig::chargeSmearer, ActsExamples::GeometricConfig::digital, Acts::from_json(), ActsExamples::GeometricConfig::indices, ActsExamples::GeometricConfig::segmentation, ActsExamples::GeometricConfig::thickness, and ActsExamples::GeometricConfig::threshold.
void ActsExamples::from_json (const nlohmann::json & j, SmearingConfig & sdc)
void ActsExamples::from_json (const nlohmann::json & j, ActsExamples::DigiComponentsConfig & dc)
Definition at line 178 of file JsonDigitizationConfig.cpp.
View newest version in sPHENIX GitHub at line 178 of file JsonDigitizationConfig.cpp
References Acts::from_json(), ActsExamples::DigiComponentsConfig::geometricDigiConfig, and ActsExamples::DigiComponentsConfig::smearingDigiConfig.
void ActsExamples::from_json (const nlohmann::json & j, ActsExamples::TGeoITkModuleSplitter::Config & msc)
Definition at line 77 of file JsonTGeoDetectorConfig.hpp.
View newest version in sPHENIX GitHub at line 77 of file JsonTGeoDetectorConfig.hpp
References ActsExamples::TGeoITkModuleSplitter::Config::barrelMap, and ActsExamples::TGeoITkModuleSplitter::Config::discMap.
template<typename T > void ActsExamples::from_json (const nlohmann::json & j, ActsExamples::TGeoDetector::Config::LayerTriplet< T > & ltr)
Read layer configuration triplets.
Definition at line 94 of file JsonTGeoDetectorConfig.hpp.
View newest version in sPHENIX GitHub at line 94 of file JsonTGeoDetectorConfig.hpp
References ActsExamples::TGeoDetector::Config::LayerTriplet< T >::at(), ActsExamples::TGeoDetector::Config::LayerTriplet< T >::central, ActsExamples::TGeoDetector::Config::LayerTriplet< T >::positive, and Acts::UnitConstants::T.
void ActsExamples::from_json (const nlohmann::json & j, ActsExamples::TGeoDetector::Config::Volume & vol)
Read volume struct.
Definition at line 111 of file JsonTGeoDetectorConfig.hpp.
View newest version in sPHENIX GitHub at line 111 of file JsonTGeoDetectorConfig.hpp
References ActsExamples::TGeoDetector::Config::LayerTriplet< T >::at(), ActsExamples::TGeoITkModuleSplitter::Config::barrelMap, ActsExamples::TGeoDetector::Config::Volume::barrelMap, ActsExamples::TGeoDetector::Config::Volume::binning0, ActsExamples::TGeoDetector::Config::Volume::binning1, ActsExamples::TGeoDetector::Config::Volume::binTolerancePhi, ActsExamples::TGeoDetector::Config::Volume::binToleranceR, ActsExamples::TGeoDetector::Config::Volume::binToleranceZ, ActsExamples::TGeoDetector::Config::Volume::cylinderDiscSplit, Acts::TGeoCylinderDiscSplitter::Config::cylinderLongitudinalSegments, ActsExamples::TGeoDetector::Config::Volume::cylinderNPhiSegments, ActsExamples::TGeoDetector::Config::Volume::cylinderNZSegments, Acts::TGeoCylinderDiscSplitter::Config::cylinderPhiSegments, ActsExamples::TGeoITkModuleSplitter::Config::discMap, ActsExamples::TGeoDetector::Config::Volume::discMap, ActsExamples::TGeoDetector::Config::Volume::discNPhiSegments, ActsExamples::TGeoDetector::Config::Volume::discNRSegments, Acts::TGeoCylinderDiscSplitter::Config::discPhiSegments, Acts::TGeoCylinderDiscSplitter::Config::discRadialSegments, ActsExamples::TGeoDetector::Config::Volume::itkModuleSplit, ActsExamples::TGeoDetector::Config::Volume::layers, ActsExamples::TGeoDetector::Config::Volume::name, ActsExamples::TGeoDetector::Config::Volume::rRange, ActsExamples::TGeoDetector::Config::Volume::sensitiveAxes, ActsExamples::TGeoDetector::Config::Volume::sensitiveNames, ActsExamples::TGeoDetector::Config::Volume::splitTolR, ActsExamples::TGeoDetector::Config::Volume::splitTolZ, ActsExamples::TGeoDetector::Config::Volume::subVolumeName, and ActsExamples::TGeoDetector::Config::Volume::zRange.
int ActsExamples::getCellColumn (const ActsExamples::ModuleValue & mval)
Definition at line 77 of file ModuleClusters.cpp.
View newest version in sPHENIX GitHub at line 77 of file ModuleClusters.cpp
References ActsExamples::ModuleValue::value.
Referenced by Acts::Ccl::Connect1D< Cell >::operator()(), Acts::Ccl::internal::Compare< Cell, 2 >::operator()(), and Acts::Ccl::internal::Compare< Cell, 1 >::operator()().
int& ActsExamples::getCellLabel (ActsExamples::ModuleValue & mval)
Definition at line 84 of file ModuleClusters.cpp.
View newest version in sPHENIX GitHub at line 84 of file ModuleClusters.cpp
References ActsExamples::ModuleValue::label.
Referenced by Acts::Ccl::internal::getConnections(), Acts::Ccl::labelClusters(), Acts::Ccl::mergeClusters(), and Acts::Ccl::internal::mergeClustersImpl().
int ActsExamples::getCellRow (const ModuleValue & mval)
Definition at line 70 of file ModuleClusters.cpp.
View newest version in sPHENIX GitHub at line 70 of file ModuleClusters.cpp
References ActsExamples::ModuleValue::value.
Referenced by Acts::Ccl::internal::Compare< Cell, 2 >::operator()().
template<typename T > GroupBy<typename GeometryIdMultiset<T>::const_iterator, detail::GeometryIdGetter> ActsExamples::groupByModule (const GeometryIdMultiset< T > & container) inline
Iterate over groups of elements belonging to each module/ sensitive surface.
Definition at line 213 of file GeometryContainers.hpp.
View newest version in sPHENIX GitHub at line 213 of file GeometryContainers.hpp
References makeGroupBy().
Referenced by ActsExamples::DigitizationAlgorithm::execute(), ActsExamples::PlanarSteppingAlgorithm::execute(), ActsExamples::CsvPlanarClusterWriter::writeT(), and ActsExamples::RootPlanarClusterWriter::writeT().
GroupBy<SimParticleContainer::const_iterator, detail::PrimaryVertexIdGetter> ActsExamples::groupByPrimaryVertex (const SimParticleContainer & container) inline
Iterate over groups of particles belonging to the same primary vertex.
Definition at line 58 of file SimParticle.hpp.
View newest version in sPHENIX GitHub at line 58 of file SimParticle.hpp
References makeGroupBy().
Referenced by ActsExamples::TruthVertexFinder::execute().
GroupBy<SimParticleContainer::const_iterator, detail::SecondaryVertexIdGetter> ActsExamples::groupBySecondaryVertex (const SimParticleContainer & container) inline
Iterate over groups of particles belonging to the same secondary vertex.
For each primary vertex, this yields one group of particles belonging directly to the primary vertex (secondary vertex id 0) and a group for each secondary vertex.
Definition at line 69 of file SimParticle.hpp.
View newest version in sPHENIX GitHub at line 69 of file SimParticle.hpp
References makeGroupBy().
Referenced by ActsExamples::TruthVertexFinder::execute(), and ActsExamples::ParticleSmearing::execute().
void ActsExamples::identifyContributingParticles (const IndexMultimap< ActsFatras::Barcode > & hitParticlesMap, const ProtoTrack & protoTrack, std::vector< ParticleHitCount > & particleHitCounts)
Identify all particles that contribute to the proto track.
Parameters
[in] hitParticlesMap Map hit indices to contributing particles
[in] protoTrack The proto track to classify
[out] particleHitCounts List of contributing particles
The list of contributing particles is ordered according to their hit count, i.e. the first element is the majority particle that contributes the most hits to the track. There can be both hits without a generating particle (noise hits) and hits that have more than one generating particle. The sum of the particle hit count must not be identical to the size of the proto track.
Definition at line 51 of file TrackClassification.cpp.
View newest version in sPHENIX GitHub at line 51 of file TrackClassification.cpp
References makeRange().
Referenced by ActsExamples::TrackFinderPerformanceWriter::Impl::write(), ActsExamples::SeedingPerformanceWriter::writeT(), ActsExamples::TrackFitterPerformanceWriter::writeT(), ActsExamples::CsvMultiTrajectoryWriter::writeT(), ActsExamples::RootTrackParameterWriter::writeT(), ActsExamples::CKFPerformanceWriter::writeT(), ActsExamples::RootTrajectorySummaryWriter::writeT(), ActsExamples::RootTrajectoryStatesWriter::writeT(), ActsExamples::VertexPerformanceWriter::writeT(), and ActsExamples::EDM4hepUtil::writeTrajectory().
void ActsExamples::identifyContributingParticles (const IndexMultimap< ActsFatras::Barcode > & hitParticlesMap, const Trajectories & trajectories, size_t trajectoryTip, std::vector< ParticleHitCount > & particleHitCounts)
Identify all particles that contribute to a trajectory.
Parameters
[in] hitParticlesMap Map hit indices to contributing particles
[in] trajectories The input trajectories to classify
[in] trajectoryTip Which trajectory in the trajectories to use
[out] particleHitCounts List of contributing particles
See identifyContributingParticles for proto tracks for further information.
Definition at line 66 of file TrackClassification.cpp.
View newest version in sPHENIX GitHub at line 66 of file TrackClassification.cpp
References ActsExamples::Trajectories::hasTrajectory(), ActsExamples::IndexSourceLink::index(), makeRange(), Acts::MeasurementFlag, ActsExamples::Trajectories::multiTrajectory(), filter::state, and Acts::MultiTrajectory< derived_t >::visitBackwards().
template<typename value_t > boost::container::flat_multimap<value_t, Index> ActsExamples::invertIndexMultimap (const IndexMultimap< value_t > & multimap) inline
Invert the multimap, i.e. from a -> {b...} to b -> {a...}.
Note
This assumes that the value in the initial multimap is itself a sortable index-like object, as would be the case when mapping e.g. hit ids to particle ids/ barcodes.
Definition at line 37 of file Index.hpp.
View newest version in sPHENIX GitHub at line 37 of file Index.hpp
References i, index, and value.
Referenced by ActsExamples::TruthTrackFinder::execute(), ActsExamples::ParticleSelector::execute(), ActsExamples::TruthSeedingAlgorithm::execute(), ActsExamples::TruthSeedSelector::execute(), and ActsExamples::TrackFinderPerformanceWriter::Impl::write().
std::string ActsExamples::joinPaths (const std::string & dir, const std::string & name)
Join dir and name into one path with correct handling of empty dirs.
Definition at line 38 of file Paths.cpp.
View newest version in sPHENIX GitHub at line 38 of file Paths.cpp
References perf_headwind::name.
Referenced by Acts::GeometryView3D::drawLayer(), Acts::GeometryView3D::drawSurfaceArray(), Acts::GeometryView3D::drawTrackingVolume(), ActsExamples::CsvTrackingGeometryWriter::finalize(), ActsExamples::JsonSurfacesWriter::finalize(), main(), materialValidationExample(), propagationExample(), runDigitizationExample(), runMaterialRecording(), ActsExamples::Simulation::setupOutput(), and ActsExamples::SvgTrackingGeometryWriter::write().
std::shared_ptr< ActsExamples::TrackFitterFunction > ActsExamples::makeGlobalChiSquareFitterFunction (std::shared_ptr< const Acts::TrackingGeometry > trackingGeometry, std::shared_ptr< const Acts::MagneticFieldProvider > magneticField, bool multipleScattering = true, bool energyLoss = true, Acts::FreeToBoundCorrection freeToBoundCorrection = Acts::FreeToBoundCorrection(), const Acts::Logger & logger = *Acts::getDefaultLogger("Gx2f", Acts::Logging::INFO))
Makes a fitter function object for the Global Chi Square Fitter (GX2F)
Parameters
trackingGeometry the trackingGeometry for the propagator
magneticField the magnetic field for the propagator
multipleScattering bool
energyLoss bool
freeToBoundCorrection bool
logger a logger instance
Definition at line 126 of file GlobalChiSquareFitterFunction.cpp.
View newest version in sPHENIX GitHub at line 126 of file GlobalChiSquareFitterFunction.cpp
References cfg, Acts::Logger::cloneWithSuffix(), testing::internal::move(), Acts::Test::navigator, propagation_timing::stepper, and digitization_config::trackingGeometry.
Referenced by Acts::Python::addTrackFitting().
template<typename Container , typename KeyGetter > auto ActsExamples::makeGroupBy (const Container & container, KeyGetter keyGetter) -> GroupBy<decltype(std::begin(container)), KeyGetter>
Construct the group-by proxy for a container.
Definition at line 136 of file GroupBy.hpp.
View newest version in sPHENIX GitHub at line 136 of file GroupBy.hpp
References parse_cmake_options::begin, container, end, and testing::internal::move().
Referenced by ActsExamples::HoughTransformSeeder::addMeasurements(), ActsExamples::SpacePointMaker::execute(), groupByModule(), groupByPrimaryVertex(), and groupBySecondaryVertex().
std::shared_ptr< TrackFitterFunction > ActsExamples::makeGsfFitterFunction (std::shared_ptr< const Acts::TrackingGeometry > trackingGeometry, std::shared_ptr< const Acts::MagneticFieldProvider > magneticField, BetheHeitlerApprox betheHeitlerApprox, std::size_t maxComponents, double weightCutoff, Acts::MixtureReductionMethod finalReductionMethod, bool abortOnError, bool disableAllMaterialHandling, const Acts::Logger & logger)
Makes a fitter function object for the GSF
Parameters
trackingGeometry the trackingGeometry for the propagator
magneticField the magnetic field for the propagator
betheHeitlerApprox The object that encapsulates the approximation.
maxComponents number of maximum components in the track state
abortOnError whether to call std::abort on an error
disableAllMaterialHandling run the GSF like a KF (no energy loss, always 1 component, ...)
logger a logger instance
Definition at line 169 of file GsfFitterFunction.cpp.
View newest version in sPHENIX GitHub at line 169 of file GsfFitterFunction.cpp
References cfg, Acts::Logger::cloneWithSuffix(), testing::internal::move(), Acts::Test::navigator, propagation_timing::stepper, and digitization_config::trackingGeometry.
Referenced by Acts::Python::addTrackFitting().
std::shared_ptr< ActsExamples::TrackFitterFunction > ActsExamples::makeKalmanFitterFunction (std::shared_ptr< const Acts::TrackingGeometry > trackingGeometry, std::shared_ptr< const Acts::MagneticFieldProvider > magneticField, bool multipleScattering = true, bool energyLoss = true, double reverseFilteringMomThreshold = 0.0, Acts::FreeToBoundCorrection freeToBoundCorrection = Acts::FreeToBoundCorrection(), const Acts::Logger & logger = *Acts::getDefaultLogger("Kalman", Acts::Logging::INFO))
Makes a fitter function object for the Kalman Filter
Definition at line 151 of file KalmanFitterFunction.cpp.
View newest version in sPHENIX GitHub at line 151 of file KalmanFitterFunction.cpp
References cfg, Acts::Logger::cloneWithSuffix(), testing::internal::move(), Acts::Test::navigator, propagation_timing::stepper, and digitization_config::trackingGeometry.
Referenced by Acts::Python::addTrackFitting(), runDetectorAlignment(), and runRecTruthTracks().
ActsExamples::detail::InterpolatedMagneticField2 ActsExamples::makeMagneticFieldMapRzFromRoot (const std::function< size_t(std::array< size_t, 2 > binsRZ, std::array< size_t, 2 > nBinsRZ)> & localToGlobalBin, const std::string & fieldMapFile, const std::string & treeName, Acts::ActsScalar lengthUnit, Acts::ActsScalar BFieldUnit, bool firstQuadrant = false)
Method to setup the FieldMap
Parameters
localToGlobalBin Function mapping the local bins of r,z to the global bin of the map magnetic field value e.g.: we have small grid with the values: r={2,3}, z ={4,5}, the corresponding indices are i(r) and j(z), the globalIndex is M and the field map is:
|| r | i || z | j || |B(r,z)| || M ||
|| 2 | 0 || 4 | 0 || 2.323 || 0 || || 2 | 0 || 5 | 1 || 2.334 || 1 || || 3 | 1 || 4 | 0 || 2.325 || 2 || || 3 | 1 || 5 | 1 || 2.331 || 3 ||
In this case the function would look like:
[](std::array<size_t, 2> binsRZ, std::array<size_t, 2> nBinsRZ) {
   return (binsRZ.at(0) * nBinsRZ.at(1) + binsRZ.at(1));
}
Parameters
[in] fieldMapFile Path to file containing field map in txt format
[in] treeName The name of the root tree
[in] lengthUnit The unit of the grid points
[in] BFieldUnit The unit of the magnetic field
[in] firstQuadrant Flag if set to true indicating that only the first quadrant of the grid points and the BField values has been given and that the BFieldMap should be created symmetrically for all quadrants. e.g. we have the grid values r={0,1} with BFieldValues={2,3} on the r axis. If the flag is set to true the r-axis grid values will be set to {-1,0,1} and the BFieldValues will be set to {3,2,3}.
[1] Read in field map file
[2] use helper function in core
Definition at line 21 of file FieldMapRootIo.cpp.
View newest version in sPHENIX GitHub at line 21 of file FieldMapRootIo.cpp
References Acts::IntegrationTest::bField, Acts::IntegrationTest::Bz, Acts::fieldMapRZ(), i, physmon_track_finding_ttbar::r, tree, and physmon_track_finding_ttbar::z.
Referenced by Acts::Python::addMagneticField(), and ActsExamples::Options::readMagneticField().
ActsExamples::detail::InterpolatedMagneticField2 ActsExamples::makeMagneticFieldMapRzFromText (const std::function< size_t(std::array< size_t, 2 > binsRZ, std::array< size_t, 2 > nBinsRZ)> & localToGlobalBin, const std::string & fieldMapFile, Acts::ActsScalar lengthUnit, Acts::ActsScalar BFieldUnit, bool firstQuadrant = false)
Method to setup the FieldMapper
Parameters
localToGlobalBin Function mapping the local bins of r,z to the global bin of the map magnetic field value e.g.: we have small grid with the values: r={2,3}, z ={4,5}, the corresponding indices are i(r) and j(z), the globalIndex is M and the field map is:
|| r | i || z | j || |B(r,z)| || M ||
|| 2 | 0 || 4 | 0 || 2.323 || 0 || || 2 | 0 || 5 | 1 || 2.334 || 1 || || 3 | 1 || 4 | 0 || 2.325 || 2 || || 3 | 1 || 5 | 1 || 2.331 || 3 ||
In this case the function would look like:
[](std::array<size_t, 2> binsRZ, std::array<size_t, 2> nBinsRZ) {
   return (binsRZ.at(0) * nBinsRZ.at(1) + binsRZ.at(1));
}
Parameters
[in] fieldMapFile Path to file containing field map in txt format
[in] lengthUnit The unit of the grid points
[in] BFieldUnit The unit of the magnetic field
Note
This information is only used as a hint for the required size of the internal vectors. A correct value is not needed, but will help to speed up the field map initialization process.
Parameters
[in] firstQuadrant Flag if set to true indicating that only the first quadrant of the grid points and the BField values has been given and that the BFieldMap should be created symmetrically for all quadrants. e.g. we have the grid values r={0,1} with BFieldValues={2,3} on the r axis. If the flag is set to true the r-axis grid values will be set to {-1,0,1} and the BFieldValues will be set to {3,2,3}.
[1] Read in field map file
[2] use helper function in core
Definition at line 21 of file FieldMapTextIo.cpp.
View newest version in sPHENIX GitHub at line 21 of file FieldMapTextIo.cpp
References Acts::IntegrationTest::bField, Acts::fieldMapRZ(), in, line, physmon_track_finding_ttbar::r, Acts::Test::tmp(), and physmon_track_finding_ttbar::z.
Referenced by Acts::Python::addMagneticField(), and ActsExamples::Options::readMagneticField().
ActsExamples::detail::InterpolatedMagneticField3 ActsExamples::makeMagneticFieldMapXyzFromRoot (const std::function< size_t(std::array< size_t, 3 > binsXYZ, std::array< size_t, 3 > nBinsXYZ)> & localToGlobalBin, const std::string & fieldMapFile, const std::string & treeName, Acts::ActsScalar lengthUnit, Acts::ActsScalar BFieldUnit, bool firstOctant = false)
Method to setup the FieldMap
Parameters
localToGlobalBin Function mapping the local bins of x,y,z to the global bin of the map magnetic field value e.g.: we have small grid with the values: x={2,3}, y={3,4}, z ={4,5}, the corresponding indices are i(x), j(y) and z(k), the globalIndex is M and the field map is:
|| x | i || y | j || z | k || |B(x,y,z)| || M ||
|| 2 | 0 || 3 | 0 || 4 | 0 || 2.323 || 0 || || 2 | 0 || 3 | 0 || 5 | 1 || 2.334 || 1 || || 2 | 0 || 4 | 1 || 4 | 0 || 2.325 || 2 || || 2 | 0 || 4 | 1 || 5 | 1 || 2.331 || 3 || || 3 | 1 || 3 | 0 || 4 | 0 || 2.323 || 4 || || 3 | 1 || 3 | 0 || 5 | 1 || 2.334 || 5 || || 3 | 1 || 4 | 1 || 4 | 0 || 2.325 || 6 || || 3 | 1 || 4 | 1 || 5 | 1 || 2.331 || 7 ||
In this case the function would look like:
[](std::array<size_t, 3> binsXYZ, std::array<size_t, 3> nBinsXYZ) {
  return (binsXYZ.at(0) * (nBinsXYZ.at(1) * nBinsXYZ.at(2))
       + binsXYZ.at(1) * nBinsXYZ.at(2)
       + binsXYZ.at(2));
}
Parameters
[in] fieldMapFile Path to file containing field map in txt format
[in] treeName The name of the root tree
[in] lengthUnit The unit of the grid points
[in] BFieldUnit The unit of the magnetic field
[in] firstOctant Flag if set to true indicating that only the first octant of the grid points and the BField values has been given and that the BFieldMap should be created symmetrically for all quadrants. e.g. we have the grid values z={0,1} with BFieldValues={2,3} on the r axis. If the flag is set to true the z-axis grid values will be set to {-1,0,1} and the BFieldValues will be set to {3,2,3}.
[1] Read in field map file
Definition at line 72 of file FieldMapRootIo.cpp.
View newest version in sPHENIX GitHub at line 72 of file FieldMapRootIo.cpp
References Acts::IntegrationTest::bField, Acts::IntegrationTest::Bz, Acts::fieldMapXYZ(), i, tree, ambiguity_solver_full_chain::x, y, and physmon_track_finding_ttbar::z.
Referenced by Acts::Python::addMagneticField(), and ActsExamples::Options::readMagneticField().
ActsExamples::detail::InterpolatedMagneticField3 ActsExamples::makeMagneticFieldMapXyzFromText (const std::function< size_t(std::array< size_t, 3 > binsXYZ, std::array< size_t, 3 > nBinsXYZ)> & localToGlobalBin, const std::string & fieldMapFile, Acts::ActsScalar lengthUnit, Acts::ActsScalar BFieldUnit, bool firstOctant = false)
Method to setup the FieldMapper
Parameters
localToGlobalBin Function mapping the local bins of x,y,z to the global bin of the map magnetic field value e.g.: we have small grid with the values: x={2,3}, y={3,4}, z ={4,5}, the corresponding indices are i(x), j(y) and z(k), the globalIndex is M and the field map is:
|| x | i || y | j || z | k || |B(x,y,z)| || M ||
|| 2 | 0 || 3 | 0 || 4 | 0 || 2.323 || 0 || || 2 | 0 || 3 | 0 || 5 | 1 || 2.334 || 1 || || 2 | 0 || 4 | 1 || 4 | 0 || 2.325 || 2 || || 2 | 0 || 4 | 1 || 5 | 1 || 2.331 || 3 || || 3 | 1 || 3 | 0 || 4 | 0 || 2.323 || 4 || || 3 | 1 || 3 | 0 || 5 | 1 || 2.334 || 5 || || 3 | 1 || 4 | 1 || 4 | 0 || 2.325 || 6 || || 3 | 1 || 4 | 1 || 5 | 1 || 2.331 || 7 ||
In this case the function would look like:
[](std::array<size_t, 3> binsXYZ, std::array<size_t, 3> nBinsXYZ) {
  return (binsXYZ.at(0) * (nBinsXYZ.at(1) * nBinsXYZ.at(2))
       + binsXYZ.at(1) * nBinsXYZ.at(2)
       + binsXYZ.at(2));
}
Parameters
[in] fieldMapFile Path to file containing field map in txt format
[in] lengthUnit The unit of the grid points
[in] BFieldUnit The unit of the magnetic field
Note
This information is only used as a hint for the required size of the internal vectors. A correct value is not needed, but will help to speed up the field map initialization process.
Parameters
[in] firstOctant Flag if set to true indicating that only the first octant of the grid points and the BField values has been given and that the BFieldMap should be created symmetrically for all quadrants. e.g. we have the grid values z={0,1} with BFieldValues={2,3} on the r axis. If the flag is set to true the z-axis grid values will be set to {-1,0,1} and the BFieldValues will be set to {3,2,3}.
[1] Read in field map file
Definition at line 64 of file FieldMapTextIo.cpp.
View newest version in sPHENIX GitHub at line 64 of file FieldMapTextIo.cpp
References Acts::IntegrationTest::bField, Acts::fieldMapXYZ(), in, line, Acts::Test::tmp(), ambiguity_solver_full_chain::x, y, and physmon_track_finding_ttbar::z.
Referenced by Acts::Python::addMagneticField(), and ActsExamples::Options::readMagneticField().
auto ActsExamples::makeParameterContainers (const ActsExamples::AlgorithmContext & ctx, const ReadDataHandle< std::vector< Acts::BoundTrackParameters >> & inputTrackParametersHandle, const ReadDataHandle< TrajectoriesContainer > & inputTrajectoriesHandle) inline
Definition at line 38 of file VertexingHelpers.hpp.
View newest version in sPHENIX GitHub at line 38 of file VertexingHelpers.hpp
References truth_tracking_gsf_refitting::inputTrajectories, std::tr1::make_tuple(), makeTrackParametersPointerContainer(), and Acts::Test::tmp().
Referenced by ActsExamples::IterativeVertexFinderAlgorithm::execute(), ActsExamples::VertexFitterAlgorithm::execute(), and ActsExamples::AdaptiveMultiVertexFinderAlgorithm::executeAfterSeederChoice().
ProtoVertexContainer ActsExamples::makeProtoVertices (const TrackParametersContainer & trackParameters, const std::vector< Acts::Vertex< Acts::BoundTrackParameters >> & vertices) inline
Create proto vertices from reconstructed vertices.
Parameters
trackParameters input track parameters container
vertices reconstructed vertices
Returns
proto vertices corresponding to the reconstructed vertices
Assumes that the original parameters pointers in the vertices point to elements in the given input track parameters container. If that is not the case the behaviour is undefined.
Definition at line 77 of file VertexingHelpers.hpp.
View newest version in sPHENIX GitHub at line 77 of file VertexingHelpers.hpp
References distance(), testing::internal::move(), and ActsExamples::HepMC3Event::vertices().
Referenced by ActsExamples::IterativeVertexFinderAlgorithm::execute(), and ActsExamples::AdaptiveMultiVertexFinderAlgorithm::executeAfterSeederChoice().
template<typename Iterator > Range<Iterator> ActsExamples::makeRange (Iterator begin, Iterator end)
Definition at line 47 of file Range.hpp.
View newest version in sPHENIX GitHub at line 47 of file Range.hpp
References parse_cmake_options::begin, and end.
Referenced by ActsExamples::TruthTrackFinder::execute(), ActsExamples::HitsPrinter::execute(), ActsExamples::TruthSeedingAlgorithm::execute(), ActsExamples::TruthSeedSelector::execute(), identifyContributingParticles(), ActsExamples::GroupBy< Iterator, KeyGetter >::GroupIterator::operator*(), ActsExamples::CsvPlanarClusterReader::read(), selectLayer(), selectLowestNonZeroGeometryObject(), selectModule(), selectVolume(), ActsExamples::TrackFinderPerformanceWriter::Impl::write(), ActsExamples::CsvMeasurementWriter::writeT(), ActsExamples::RootTrackParameterWriter::writeT(), ActsExamples::RootTrajectoryStatesWriter::writeT(), and ActsExamples::RootMeasurementWriter::writeT().
template<typename Iterator > Range<Iterator> ActsExamples::makeRange (std::pair< Iterator, Iterator > range)
Definition at line 52 of file Range.hpp.
View newest version in sPHENIX GitHub at line 52 of file Range.hpp
std::vector<const Acts::BoundTrackParameters*> ActsExamples::makeTrackParametersPointerContainer (const TrackParametersContainer & trackParameters) inline
Create a pointers container for all track parameters in the input container.
Parameters
trackParameters input examples track parameters container
Returns
track parameters pointer container referencing the input tracks
Definition at line 27 of file VertexingHelpers.hpp.
View newest version in sPHENIX GitHub at line 27 of file VertexingHelpers.hpp
Referenced by ActsExamples::TutorialVertexFinderAlgorithm::execute(), and makeParameterContainers().
template<size_t kMeasDIM> std::tuple<std::array<Acts::BoundIndices, kMeasDIM>, Acts::ActsVector<kMeasDIM>, Acts::ActsSquareMatrix<kMeasDIM> > ActsExamples::measurementConstituents (const DigitizedParameters & dParams)
Construct the constituents of a measurement.
Template Parameters
kMeasDIM the full dimension of the measurement
Parameters
dParams the struct of arrays of parameters to be created
Returns
a tuple of constituents for a measurement
Definition at line 57 of file MeasurementCreation.hpp.
View newest version in sPHENIX GitHub at line 57 of file MeasurementCreation.hpp
References Acts::Test::cov, ei(), ActsExamples::DigitizedParameters::indices, ActsExamples::DigitizedParameters::values, and ActsExamples::DigitizedParameters::variances.
std::ostream& ActsExamples::operator<< (std::ostream & os, const HelloData & data) inline
Definition at line 24 of file HelloData.hpp.
View newest version in sPHENIX GitHub at line 24 of file HelloData.hpp
References ActsExamples::HelloData::a, ActsExamples::HelloData::b, os, ActsExamples::HelloData::t, and ActsExamples::HelloData::x.
std::ostream & ActsExamples::operator<< (std::ostream & os, const ActsExamples::Sequencer::FpeMask & m)
Definition at line 686 of file Sequencer.cpp.
View newest version in sPHENIX GitHub at line 686 of file Sequencer.cpp
References ActsExamples::Sequencer::FpeMask::count, ActsExamples::Sequencer::FpeMask::file, ActsExamples::Sequencer::FpeMask::lines, os, and ActsExamples::Sequencer::FpeMask::type.
bool ActsExamples::operator== (const SimSpacePoint & lhs, const SimSpacePoint & rhs) inline
Definition at line 144 of file SimSpacePoint.hpp.
View newest version in sPHENIX GitHub at line 144 of file SimSpacePoint.hpp
References ActsExamples::SimSpacePoint::sourceLinks(), ActsExamples::SimSpacePoint::varianceR(), ActsExamples::SimSpacePoint::varianceZ(), ActsExamples::SimSpacePoint::x(), ActsExamples::SimSpacePoint::y(), and ActsExamples::SimSpacePoint::z().
std::string ActsExamples::perEventFilepath (const std::string & dir, const std::string & name, size_t event)
Construct a file path of the form [<dir>/]event<XXXXXXXXX>-<name>.
dir output directory, current directory if empty name basic filename event event number
Definition at line 47 of file Paths.cpp.
View newest version in sPHENIX GitHub at line 47 of file Paths.cpp
References perf_headwind::name, and prefix.
Referenced by ActsExamples::HepMC3AsciiReader::read(), ActsExamples::CsvParticleReader::read(), ActsExamples::CsvSimHitReader::read(), ActsExamples::CsvTrackParameterReader::read(), ActsExamples::CsvSpacePointReader::read(), ActsExamples::CsvTrackParameterWriter::write(), ActsExamples::CsvTrackingGeometryWriter::write(), ActsExamples::JsonSurfacesWriter::write(), ActsExamples::ObjSpacePointWriter< T >::writeT(), ActsExamples::HepMC3AsciiWriter::writeT(), ActsExamples::JsonSpacePointWriter< T >::writeT(), ActsExamples::CsvProtoTrackWriter::writeT(), ActsExamples::CsvSimHitWriter::writeT(), ActsExamples::CsvParticleWriter::writeT(), ActsExamples::ObjPropagationStepsWriter< step_t >::writeT(), ActsExamples::CsvSpacepointWriter::writeT(), ActsExamples::CsvMultiTrajectoryWriter::writeT(), ActsExamples::CsvMeasurementWriter::writeT(), ActsExamples::CsvPlanarClusterWriter::writeT(), and ActsExamples::SvgPointWriter< T, Acc >::writeT().
ActsExamples::SimSeed ActsExamples::prototrackToSeed (const ProtoTrack & track, const SimSpacePointContainer & spacepoints)
Definition at line 48 of file EventDataTransforms.cpp.
View newest version in sPHENIX GitHub at line 48 of file EventDataTransforms.cpp
References KFPMath::a, KFPMath::b, findSpacePointForIndex(), index, Acts::UnitConstants::m, Acts::UnitConstants::ps, physmon_simulation::s, Acts::Experimental::detail::BlueprintHelper::sort(), t, to_string(), and Acts::Test::transform.
Referenced by ActsExamples::PrototracksToSeeds::execute().
Acts::GeometryHierarchyMap< ActsExamples::DigiComponentsConfig > ActsExamples::readDigiConfigFromJson (const std::string & path)
Definition at line 191 of file JsonDigitizationConfig.cpp.
View newest version in sPHENIX GitHub at line 191 of file JsonDigitizationConfig.cpp
References in, and infile.
Referenced by Acts::Python::addDigitization(), digitization_config::runDigitizationConfig(), runDigitizationConfigExample(), runDigitizationExample(), and setupDigitization().
std::vector< Acts::GeometryIdentifier > ActsExamples::readJsonGeometryList (const std::string & path)
Definition at line 62 of file JsonGeometryList.cpp.
View newest version in sPHENIX GitHub at line 62 of file JsonGeometryList.cpp
References configureMap::data, Acts::from_json(), in, and infile.
Referenced by Acts::Python::addExampleAlgorithms(), ActsExamples::Options::readSpacePointMakerConfig(), and runDetectorAlignment().
int ActsExamples::runGeant4Simulation (const ActsExamples::Options::Variables & vars, std::shared_ptr< ActsExamples::DetectorConstructionFactory > detectorConstructionFactory, std::shared_ptr< const Acts::TrackingGeometry > trackingGeometry)
Specific setup: Geant4 Simulation
Parameters
vars the parsed variables
detectorConstructionFactory is the detector construction factory to be used
trackingGeometry the tracking geometry for the sennsitive mapping
Referenced by main().
int ActsExamples::runGeant4Simulation (const ActsExamples::Options::Variables & vars, std::shared_ptr< DetectorConstructionFactory > detectorConstructionFactory, std::shared_ptr< const Acts::TrackingGeometry > trackingGeometry)
Definition at line 140 of file Geant4Common.cpp.
View newest version in sPHENIX GitHub at line 140 of file Geant4Common.cpp
References ActsTests::PropagationDatasets::magneticField, testing::internal::move(), physmon_simulation::randomNumbers, ActsExamples::Options::readMagneticField(), ActsExamples::Options::readRandomNumbersConfig(), ActsExamples::Options::readSequencerConfig(), setupGeant4Simulation(), ActsExamples::Simulation::setupInput(), and ActsExamples::Simulation::setupOutput().
int ActsExamples::runMaterialRecording (const ActsExamples::Options::Variables & vars, std::shared_ptr< ActsExamples::DetectorConstructionFactory > detectorConstructionFactory)
Specific setup: Material Recording
Parameters
vars the parsed variables
detectorConstructionFactory is the detector construction factory to be used
Referenced by conftest::_do_material_recording(), and main().
int ActsExamples::runMaterialRecording (const ActsExamples::Options::Variables & vars, std::shared_ptr< DetectorConstructionFactory > detectorConstructionFactory)
Definition at line 96 of file Geant4Common.cpp.
View newest version in sPHENIX GitHub at line 96 of file Geant4Common.cpp
References ActsExamples::Sequencer::addReader(), ActsExamples::Sequencer::addWriter(), ActsExamples::RootMaterialTrackWriter::Config::collection, ensureWritableDirectory(), ActsExamples::RootMaterialTrackWriter::Config::filePath, joinPaths(), ActsExamples::Simulation::kMaterialTracks, ActsExamples::Simulation::kParticlesInitial, telescope_simulation::logLevel, testing::internal::move(), outputDir, ActsExamples::RootMaterialTrackWriter::Config::prePostStep, ActsExamples::Options::readLogLevel(), ActsExamples::Options::readParticleGunOptions(), ActsExamples::Options::readRandomNumbersConfig(), ActsExamples::Options::readSequencerConfig(), ActsExamples::RootMaterialTrackWriter::Config::recalculateTotals, physmon_simulation::rnd, ActsExamples::Sequencer::run(), and setupMaterialRecording().
ActsExamples::ProtoTrack ActsExamples::seedToPrototrack (const SimSeed & seed)
Definition at line 17 of file EventDataTransforms.cpp.
View newest version in sPHENIX GitHub at line 17 of file EventDataTransforms.cpp
References Acts::Seed< SpacePoint >::sp().
Referenced by ActsExamples::SeedsToPrototracks::execute(), and ActsExamples::SeedingPerformanceWriter::writeT().
template<typename T > Range<typename GeometryIdMultiset<T>::const_iterator> ActsExamples::selectLayer (const GeometryIdMultiset< T > & container, Acts::GeometryIdentifier::Value volume, Acts::GeometryIdentifier::Value layer) inline
Select all elements within the given layer.
Definition at line 131 of file GeometryContainers.hpp.
View newest version in sPHENIX GitHub at line 131 of file GeometryContainers.hpp
References root_event_diff_np::cmp(), end, makeRange(), Acts::GeometryIdentifier::setLayer(), Acts::GeometryIdentifier::setVolume(), and physmon_ckf_tracking::u.
Referenced by Acts::Python::addExampleAlgorithms(), ActsExamples::HitsPrinter::execute(), selectLayer(), and selectLowestNonZeroGeometryObject().
template<typename T > auto ActsExamples::selectLayer (const GeometryIdMultiset< T > & container, Acts::GeometryIdentifier id) inline
Definition at line 150 of file GeometryContainers.hpp.
View newest version in sPHENIX GitHub at line 150 of file GeometryContainers.hpp
References layer, and selectLayer().
template<typename T > Range<typename GeometryIdMultiset<T>::const_iterator> ActsExamples::selectLowestNonZeroGeometryObject (const GeometryIdMultiset< T > & container, Acts::GeometryIdentifier geoId) inline
Select all elements for the lowest non-zero identifier component.
Zero values of lower components are interpreted as wildcard search patterns that select all element at the given geometry hierarchy and below. This only applies to the lower components and not to intermediate zeros.
Examples:
volume=2,layer=0,module=3 -> select all elements in the module
volume=1,layer=2,module=0 -> select all elements in the layer
volume=3,layer=0,module=0 -> select all elements in the volume
Note
An identifier with all components set to zero selects the whole input container.
Boundary and approach surfaces do not really fit into the geometry hierarchy and must be set to zero for the selection. If they are set on an input identifier, the behaviour of this search method is undefined.
Definition at line 193 of file GeometryContainers.hpp.
View newest version in sPHENIX GitHub at line 193 of file GeometryContainers.hpp
References Acts::GeometryIdentifier::approach(), assert, Acts::GeometryIdentifier::boundary(), Acts::GeometryIdentifier::layer(), makeRange(), selectLayer(), selectModule(), selectVolume(), Acts::GeometryIdentifier::sensitive(), physmon_ckf_tracking::u, and Acts::GeometryIdentifier::volume().
Referenced by ActsExamples::HoughTransformSeeder::addMeasurements(), ActsExamples::MeasurementMapSelector::execute(), and ActsExamples::SpacePointMaker::execute().
template<typename T > Range<typename GeometryIdMultiset<T>::const_iterator> ActsExamples::selectModule (const GeometryIdMultiset< T > & container, Acts::GeometryIdentifier geoId) inline
Select all elements for the given module / sensitive surface.
Definition at line 157 of file GeometryContainers.hpp.
View newest version in sPHENIX GitHub at line 157 of file GeometryContainers.hpp
References makeRange().
Referenced by Acts::Python::addExampleAlgorithms(), ActsExamples::HitsPrinter::execute(), selectLowestNonZeroGeometryObject(), and selectModule().
template<typename T > auto ActsExamples::selectModule (const GeometryIdMultiset< T > & container, Acts::GeometryIdentifier::Value volume, Acts::GeometryIdentifier::Value layer, Acts::GeometryIdentifier::Value module) inline
Select all elements for the given module / sensitive surface.
Definition at line 165 of file GeometryContainers.hpp.
View newest version in sPHENIX GitHub at line 165 of file GeometryContainers.hpp
References selectModule().
template<typename T > Range<typename GeometryIdMultiset<T>::const_iterator> ActsExamples::selectVolume (const GeometryIdMultiset< T > & container, Acts::GeometryIdentifier::Value volume) inline
Select all elements within the given volume.
Definition at line 106 of file GeometryContainers.hpp.
View newest version in sPHENIX GitHub at line 106 of file GeometryContainers.hpp
References root_event_diff_np::cmp(), end, makeRange(), Acts::GeometryIdentifier::setVolume(), and physmon_ckf_tracking::u.
Referenced by Acts::Python::addExampleAlgorithms(), ActsExamples::HitsPrinter::execute(), selectLowestNonZeroGeometryObject(), and selectVolume().
template<typename T > auto ActsExamples::selectVolume (const GeometryIdMultiset< T > & container, Acts::GeometryIdentifier id) inline
Select all elements within the given volume.
Definition at line 124 of file GeometryContainers.hpp.
View newest version in sPHENIX GitHub at line 124 of file GeometryContainers.hpp
References selectVolume().
void ActsExamples::setupGeant4Simulation (const ActsExamples::Options::Variables & vars, ActsExamples::Sequencer & sequencer, std::shared_ptr< DetectorConstructionFactory > detectorConstructionFactory, std::shared_ptr< const Acts::TrackingGeometry > trackingGeometry, std::shared_ptr< const Acts::MagneticFieldProvider > magneticField)
Main function for running Geant4 simulation with a specific detector.
Parameters
vars the parsed variables
sequencer the event sequencer
detectorConstructionFactory is the detector construction factory to be used
trackingGeometry the tracking geometry for the sennsitive mapping
magneticField the ACTS magnetic field to be wrapped
Definition at line 71 of file Geant4Common.cpp.
View newest version in sPHENIX GitHub at line 71 of file Geant4Common.cpp
References ActsExamples::Sequencer::addAlgorithm(), ActsExamples::Geant4SimulationBase::Config::detectorConstructionFactory, ActsExamples::Simulation::kParticlesFinal, ActsExamples::Simulation::kParticlesInitial, ActsExamples::Simulation::kParticlesSelection, ActsExamples::Simulation::kSimHits, testing::internal::move(), and seed.
Referenced by runGeant4Simulation().
void ActsExamples::setupMaterialRecording (const ActsExamples::Options::Variables & vars, ActsExamples::Sequencer & sequencer, std::shared_ptr< DetectorConstructionFactory > detectorConstructionFactory)
Main function for running Geant4 material recording with a specific detector.
Parameters
vars the parsed variables
sequencer the event sequencer
detectorConstructionFactory is the detector construction factory to be used
trackingGeometry the tracking geometry for the sennsitive mapping
magneticField the ACTS magnetic field to be wrapped
Definition at line 50 of file Geant4Common.cpp.
View newest version in sPHENIX GitHub at line 50 of file Geant4Common.cpp
References ActsExamples::Sequencer::addAlgorithm(), ActsExamples::Geant4SimulationBase::Config::detectorConstructionFactory, ActsExamples::Simulation::kMaterialTracks, ActsExamples::Simulation::kParticlesInitial, testing::internal::move(), and seed.
Referenced by runMaterialRecording().
void ActsExamples::to_json (nlohmann::json & data, const Acts::GeometryIdentifier & geoId)
Definition at line 24 of file JsonGeometryList.cpp.
View newest version in sPHENIX GitHub at line 24 of file JsonGeometryList.cpp
References Acts::GeometryIdentifier::approach(), Acts::GeometryIdentifier::boundary(), Acts::GeometryIdentifier::layer(), Acts::GeometryIdentifier::sensitive(), physmon_ckf_tracking::u, and Acts::GeometryIdentifier::volume().
void ActsExamples::to_json (nlohmann::json & j, const ParameterSmearingConfig & psc)
Definition at line 114 of file JsonDigitizationConfig.cpp.
View newest version in sPHENIX GitHub at line 114 of file JsonDigitizationConfig.cpp
References ActsExamples::ParameterSmearingConfig::index, ActsExamples::ParameterSmearingConfig::smearFunction, and Acts::to_json().
void ActsExamples::to_json (nlohmann::json & j, const GeometricConfig & gdc)
Definition at line 126 of file JsonDigitizationConfig.cpp.
View newest version in sPHENIX GitHub at line 126 of file JsonDigitizationConfig.cpp
References ActsExamples::GeometricConfig::chargeSmearer, ActsExamples::GeometricConfig::digital, ambiguity_solver_full_chain::idx, ActsExamples::GeometricConfig::indices, ActsExamples::GeometricConfig::segmentation, ActsExamples::GeometricConfig::thickness, ActsExamples::GeometricConfig::threshold, and Acts::to_json().
void ActsExamples::to_json (nlohmann::json & data, const std::vector< Acts::GeometryIdentifier > & geoIdList)
Definition at line 52 of file JsonGeometryList.cpp.
View newest version in sPHENIX GitHub at line 52 of file JsonGeometryList.cpp
References entry, and Acts::to_json().
void ActsExamples::to_json (nlohmann::json & j, const SmearingConfig & sdc)
void ActsExamples::to_json (nlohmann::json & j, const DigiComponentsConfig & dc)
Definition at line 168 of file JsonDigitizationConfig.cpp.
View newest version in sPHENIX GitHub at line 168 of file JsonDigitizationConfig.cpp
References ActsExamples::DigiComponentsConfig::geometricDigiConfig, ActsExamples::GeometricConfig::indices, and ActsExamples::DigiComponentsConfig::smearingDigiConfig.
void ActsExamples::to_json (nlohmann::json & j, const ActsExamples::TGeoITkModuleSplitter::Config & msc)
Definition at line 86 of file JsonTGeoDetectorConfig.hpp.
View newest version in sPHENIX GitHub at line 86 of file JsonTGeoDetectorConfig.hpp
References ActsExamples::TGeoITkModuleSplitter::Config::barrelMap, and ActsExamples::TGeoITkModuleSplitter::Config::discMap.
template<typename T > void ActsExamples::to_json (nlohmann::json & j, const ActsExamples::TGeoDetector::Config::LayerTriplet< T > & ltr)
Write layer configuration triplets.
Definition at line 103 of file JsonTGeoDetectorConfig.hpp.
View newest version in sPHENIX GitHub at line 103 of file JsonTGeoDetectorConfig.hpp
References ActsExamples::TGeoDetector::Config::LayerTriplet< T >::central, and ActsExamples::TGeoDetector::Config::LayerTriplet< T >::positive.
void ActsExamples::to_json (nlohmann::json & j, const TGeoDetector::Config::Volume & vol)
Write volume struct.
Definition at line 159 of file JsonTGeoDetectorConfig.hpp.
View newest version in sPHENIX GitHub at line 159 of file JsonTGeoDetectorConfig.hpp
References ActsExamples::TGeoITkModuleSplitter::Config::barrelMap, ActsExamples::TGeoDetector::Config::Volume::barrelMap, ActsExamples::TGeoDetector::Config::Volume::binning0, ActsExamples::TGeoDetector::Config::Volume::binning1, ActsExamples::TGeoDetector::Config::Volume::binTolerancePhi, ActsExamples::TGeoDetector::Config::Volume::binToleranceR, ActsExamples::TGeoDetector::Config::Volume::binToleranceZ, ActsExamples::TGeoDetector::Config::Volume::cylinderDiscSplit, Acts::TGeoCylinderDiscSplitter::Config::cylinderLongitudinalSegments, ActsExamples::TGeoDetector::Config::Volume::cylinderNPhiSegments, ActsExamples::TGeoDetector::Config::Volume::cylinderNZSegments, Acts::TGeoCylinderDiscSplitter::Config::cylinderPhiSegments, ActsExamples::TGeoITkModuleSplitter::Config::discMap, ActsExamples::TGeoDetector::Config::Volume::discMap, ActsExamples::TGeoDetector::Config::Volume::discNPhiSegments, ActsExamples::TGeoDetector::Config::Volume::discNRSegments, Acts::TGeoCylinderDiscSplitter::Config::discPhiSegments, Acts::TGeoCylinderDiscSplitter::Config::discRadialSegments, ActsExamples::TGeoDetector::Config::Volume::itkModuleSplit, ActsExamples::TGeoDetector::Config::Volume::layers, ActsExamples::TGeoDetector::Config::Volume::name, ActsExamples::TGeoDetector::Config::Volume::rRange, ActsExamples::TGeoDetector::Config::Volume::sensitiveAxes, ActsExamples::TGeoDetector::Config::Volume::sensitiveNames, ActsExamples::TGeoDetector::Config::Volume::splitTolR, ActsExamples::TGeoDetector::Config::Volume::splitTolZ, ActsExamples::TGeoDetector::Config::Volume::subVolumeName, and ActsExamples::TGeoDetector::Config::Volume::zRange.
void ActsExamples::writeDigiConfigToJson (const Acts::GeometryHierarchyMap< DigiComponentsConfig > & cfg, const std::string & path)
Definition at line 203 of file JsonDigitizationConfig.cpp.
View newest version in sPHENIX GitHub at line 203 of file JsonDigitizationConfig.cpp
References out, and add_histos::outfile.
Referenced by Acts::Python::addDigitization(), digitization_config::runDigitizationConfig(), runDigitizationConfigExample(), runDigitizationExample(), and setupDigitization().
void ActsExamples::writeJsonGeometryList (const std::vector< Acts::GeometryIdentifier > & geoIdList, const std::string & path)
Definition at line 73 of file JsonGeometryList.cpp.
View newest version in sPHENIX GitHub at line 73 of file JsonGeometryList.cpp
References configureMap::data, out, add_histos::outfile, and Acts::to_json().
Variable Documentation
thread_local std::vector<std::shared_ptr<HoughMeasurementStruct> > ActsExamples::houghMeasurementStructs
Definition at line 150 of file HoughTransformSeeder.hpp.
View newest version in sPHENIX GitHub at line 150 of file HoughTransformSeeder.hpp
Referenced by ActsExamples::HoughTransformSeeder::addMeasurements(), ActsExamples::HoughTransformSeeder::addSpacePoints(), ActsExamples::HoughTransformSeeder::createLayerHoughHist(), and ActsExamples::HoughTransformSeeder::execute().
constexpr double ActsExamples::NaNdouble = std::numeric_limits<double>::quiet_NaN()
NaN values for TTree variables.
Definition at line 27 of file WriterT.hpp.
View newest version in sPHENIX GitHub at line 27 of file WriterT.hpp
constexpr float ActsExamples::NaNfloat = std::numeric_limits<float>::quiet_NaN()
Definition at line 28 of file WriterT.hpp.
View newest version in sPHENIX GitHub at line 28 of file WriterT.hpp
Referenced by ActsExamples::RootTrajectorySummaryWriter::writeT().
constexpr float ActsExamples::NaNint = std::numeric_limits<int>::quiet_NaN()
Definition at line 29 of file WriterT.hpp.
View newest version in sPHENIX GitHub at line 29 of file WriterT.hpp
Acts::Svg::TrackingGeometryConverter::Options ActsExamples::s_backgroundTrackingGeometryOptions = backgroundGeometryOptions() static
Definition at line 119 of file SvgDefaults.hpp.
View newest version in sPHENIX GitHub at line 119 of file SvgDefaults.hpp
Acts::Svg::Style ActsExamples::s_infoStyle = infoStyle() static
Definition at line 113 of file SvgDefaults.hpp.
View newest version in sPHENIX GitHub at line 113 of file SvgDefaults.hpp
Acts::Svg::Style ActsExamples::s_layerStyle = layerStyle() static
Definition at line 109 of file SvgDefaults.hpp.
View newest version in sPHENIX GitHub at line 109 of file SvgDefaults.hpp
Acts::Svg::Style ActsExamples::s_pointStyle = pointStyle() static
Definition at line 111 of file SvgDefaults.hpp.
View newest version in sPHENIX GitHub at line 111 of file SvgDefaults.hpp
Acts::Svg::TrackingGeometryConverter::Options ActsExamples::s_trackingGeometryOptions static
Initial value:
=
    trackingGeometryOptions()
Definition at line 115 of file SvgDefaults.hpp.
View newest version in sPHENIX GitHub at line 115 of file SvgDefaults.hpp