Analysis Software: acts/blob/sPHENIX/Examples/Run/Digitization/Common/DigitizationConfigExample.cpp File Reference
DigitizationConfigExample.cpp File Reference
#include "Acts/Geometry/GeometryHierarchyMap.hpp"
#include "Acts/Geometry/TrackingGeometry.hpp"
#include "ActsExamples/Detector/IBaseDetector.hpp"
#include "ActsExamples/Digitization/DigitizationConfigurator.hpp"
#include "ActsExamples/Geometry/CommonGeometry.hpp"
#include "ActsExamples/Io/Json/JsonDigitizationConfig.hpp"
#include "ActsExamples/Options/CommonOptions.hpp"
#include "ActsExamples/Options/DigitizationOptions.hpp"
#include "ActsExamples/Utilities/Options.hpp"
#include "ActsExamples/Utilities/Paths.hpp"
#include <fstream>
#include <memory>
#include <boost/program_options.hpp>
#include "DigitizationInput.hpp"
Functions
int runDigitizationConfigExample (int argc, char *argv[], const std::shared_ptr< ActsExamples::IBaseDetector > &detector)
Function Documentation
int runDigitizationConfigExample (int argc, char * argv[], const std::shared_ptr< ActsExamples::IBaseDetector > & detector)
Definition at line 29 of file DigitizationConfigExample.cpp.
View newest version in sPHENIX GitHub at line 29 of file DigitizationConfigExample.cpp
References ActsExamples::Options::addDigitizationOptions(), ActsExamples::Options::addGeometryOptions(), ActsExamples::Options::addMaterialOptions(), ActsExamples::Options::addSequencerOptions(), ActsExamples::Geometry::build(), ActsExamples::DigitizationConfigurator::compactify, Acts::Test::geometry, ActsExamples::DigitizationConfigurator::inputDigiComponents, ActsExamples::Options::makeDefaultOptions(), ActsExamples::DigitizationConfigurator::outputDigiComponents, ActsExamples::Options::parse(), ActsExamples::readDigiConfigFromJson(), and ActsExamples::writeDigiConfigToJson().
Referenced by main().