Analysis Software: MvtxMonDraw Class Reference
MvtxMonDraw Class Reference
#include <OnlMon/blob/main/subsystems/mvtx/MvtxMonDraw.h>
Public Types
enum Quality { Good, Medium, Bad }
Public Member Functions
MvtxMonDraw (const std::string &name)
~MvtxMonDraw () override
int Init () override
int Draw (const std::string &what="ALL") override
int MakeHtml (const std::string &what="ALL") override
int SavePlot (const std::string &what="ALL", const std::string &type="png") override
int PublishHistogram (TCanvas *c, int pad, TH1 *h, const char *opt="")
int PublishHistogram (TPad *p, TH1 *h, const char *opt="")
int PublishHistogram (TPad *p, int pad, TH1 *h, const char *opt="")
void PublishStatistics (TCanvas *c, OnlMonClient *cl)
template<typename T >
int MergeServers (T *h)
void formatPaveText (TPaveText *aPT, float aTextSize, Color_t aTextColor, short aTextAlign, const char *aText)
std::vector< Quality > analyseForError (TH2Poly *over1, TH2Poly *over2, TH2Poly *over3, TH1 *decErr)
void DrawPave (std::vector< MvtxMonDraw::Quality > status, int position, const char *what="")
Public Member Functions inherited from OnlMonDraw
OnlMonDraw (const std::string &name="NONE")
virtual ~OnlMonDraw ()
virtual int MakePS (const std::string &what="ALL")
const std::string Name () const
void Verbosity (const int i)
int Verbosity () const
Public Attributes
const int NStaves [NLAYERS] = { 12, 16, 20 }
const int StaveBoundary [NLAYERS+1] = { 0, 12, 28, 48}
std::string mLaneStatusFlag [NFlags] = { "WARNING", "ERROR", "FAULT" }
Static Public Attributes
static const int NSTAVE = 48
static const int NCHIP = 9
static const int NLAYERS = 3
static constexpr int NFlags = 3
Private Member Functions
int MakeCanvas (const std::string &name)
int DrawFirst (const std::string &what="ALL")
int DrawSecond (const std::string &what="ALL")
int DrawHitMap (const std::string &what="ALL")
int DrawGeneral (const std::string &what="ALL")
int DrawFEE (const std::string &what="ALL")
int DrawOCC (const std::string &what="ALL")
int DrawFHR (const std::string &what="ALL")
int DrawHistory (const std::string &what="ALL")
time_t getTime ()
Private Attributes
const int chipmapoffset [3] = { 0, 12, 28}
int TimeOffsetTicks = -1
TCanvas * TC [6] = {nullptr}
TPad * transparent [1] = {nullptr}
TPad * Pad [6] = {nullptr}
TGraphErrors * gr [6] = {nullptr}
OnlMonDB * dbvars [NFlx] = {nullptr}
int maxbadchips = 2
Static Private Attributes
static const int NFlx = 6
static constexpr int NCols = 1024
static constexpr int NRows = 512
static constexpr int NPixels = NRows * NCols
Additional Inherited Members
Protected Member Functions inherited from OnlMonDraw
virtual int DrawDeadServer (TPad *transparent)
Protected Attributes inherited from OnlMonDraw
std::string ThisName
int verbosity = 0
Detailed Description
Definition at line 19 of file MvtxMonDraw.h.
View newest version in sPHENIX GitHub at line 19 of file MvtxMonDraw.h
Member Enumeration Documentation
enum MvtxMonDraw::Quality
Enumerator:
Good
Medium
Bad
Definition at line 47 of file MvtxMonDraw.h.
View newest version in sPHENIX GitHub at line 47 of file MvtxMonDraw.h
Constructor & Destructor Documentation
MvtxMonDraw::MvtxMonDraw (const std::string & name)
Definition at line 32 of file MvtxMonDraw.cc.
View newest version in sPHENIX GitHub at line 32 of file MvtxMonDraw.cc
References dbvars, NFlx, and TimeOffsetTicks.
MvtxMonDraw::~MvtxMonDraw () inline override
Definition at line 24 of file MvtxMonDraw.h.
View newest version in sPHENIX GitHub at line 24 of file MvtxMonDraw.h
Member Function Documentation
std::vector< MvtxMonDraw::Quality > MvtxMonDraw::analyseForError (TH2Poly * over1, TH2Poly * over2, TH2Poly * over3, TH1 * decErr)
Definition at line 1315 of file MvtxMonDraw.cc.
View newest version in sPHENIX GitHub at line 1315 of file MvtxMonDraw.cc
References configureMap::ibin, maxbadchips, NFlags, NLAYERS, NSTAVE, NStaves, and StaveBoundary.
Referenced by DrawGeneral().
int MvtxMonDraw::Draw (const std::string & what = "ALL") override virtual
Reimplemented from OnlMonDraw.
Definition at line 205 of file MvtxMonDraw.cc.
View newest version in sPHENIX GitHub at line 205 of file MvtxMonDraw.cc
References DrawFEE(), DrawFHR(), DrawGeneral(), DrawHistory(), DrawHitMap(), and DrawOCC().
Referenced by DrawFEE(), MakeHtml(), and SavePlot().
int MvtxMonDraw::DrawFEE (const std::string & what = "ALL") private
Definition at line 567 of file MvtxMonDraw.cc.
View newest version in sPHENIX GitHub at line 567 of file MvtxMonDraw.cc
References Draw(), OnlMonClient::getHisto(), i, OnlMonClient::instance(), MakeCanvas(), mLaneStatusFlag, NFlx, Pad, PublishHistogram(), PublishStatistics(), and TC.
Referenced by Draw().
int MvtxMonDraw::DrawFHR (const std::string & what = "ALL") private
Definition at line 885 of file MvtxMonDraw.cc.
View newest version in sPHENIX GitHub at line 885 of file MvtxMonDraw.cc
References OnlMonClient::getHisto(), OnlMonClient::instance(), MakeCanvas(), NFlx, Pad, PublishHistogram(), PublishStatistics(), and TC.
Referenced by Draw().
int MvtxMonDraw::DrawFirst (const std::string & what = "ALL") private
int MvtxMonDraw::DrawGeneral (const std::string & what = "ALL") private
Definition at line 363 of file MvtxMonDraw.cc.
View newest version in sPHENIX GitHub at line 363 of file MvtxMonDraw.cc
References analyseForError(), DrawPave(), formatPaveText(), OnlMonClient::getHisto(), i, OnlMonClient::instance(), MakeCanvas(), NFlx, Pad, physmon_track_finding_ttbar::pt, PublishHistogram(), PublishStatistics(), utils::status, TC, and to_string().
Referenced by Draw().
int MvtxMonDraw::DrawHistory (const std::string & what = "ALL") private
Definition at line 1093 of file MvtxMonDraw.cc.
View newest version in sPHENIX GitHub at line 1093 of file MvtxMonDraw.cc
References parse_cmake_options::begin, dbvars, end, OnlMonDB::GetVar(), gr, i, MakeCanvas(), n, NFlx, Pad, runnumber, TC, Acts::Test::time, TimeOffsetTicks, CDB::timestamp, ambiguity_solver_full_chain::x, and y.
Referenced by Draw().
int MvtxMonDraw::DrawHitMap (const std::string & what = "ALL") private
Definition at line 247 of file MvtxMonDraw.cc.
View newest version in sPHENIX GitHub at line 247 of file MvtxMonDraw.cc
References chipmapoffset, OnlMonClient::getHisto(), i, OnlMonClient::instance(), MakeCanvas(), NCHIP, NFlx, Pad, prefix, PublishHistogram(), PublishStatistics(), and TC.
Referenced by Draw().
int MvtxMonDraw::DrawOCC (const std::string & what = "ALL") private
Definition at line 705 of file MvtxMonDraw.cc.
View newest version in sPHENIX GitHub at line 705 of file MvtxMonDraw.cc
References Acts::UnitConstants::e, OnlMonClient::getHisto(), i, OnlMonClient::instance(), MakeCanvas(), NFlx, NStaves, Pad, physmon_track_finding_ttbar::pt, PublishHistogram(), PublishStatistics(), StaveBoundary, ambiguity_solver_full_chain::t1, TC, and Acts::Test::tmp().
Referenced by Draw().
void MvtxMonDraw::DrawPave (std::vector< MvtxMonDraw::Quality > status, int position, const char * what = "")
Definition at line 1415 of file MvtxMonDraw.cc.
View newest version in sPHENIX GitHub at line 1415 of file MvtxMonDraw.cc
References physmon_track_finding_ttbar::pt.
Referenced by DrawGeneral().
int MvtxMonDraw::DrawSecond (const std::string & what = "ALL") private
void MvtxMonDraw::formatPaveText (TPaveText * aPT, float aTextSize, Color_t aTextColor, short aTextAlign, const char * aText)
Definition at line 1305 of file MvtxMonDraw.cc.
View newest version in sPHENIX GitHub at line 1305 of file MvtxMonDraw.cc
Referenced by DrawGeneral().
time_t MvtxMonDraw::getTime () private
Definition at line 1432 of file MvtxMonDraw.cc.
View newest version in sPHENIX GitHub at line 1432 of file MvtxMonDraw.cc
References OnlMonClient::EventTime(), and OnlMonClient::instance().
int MvtxMonDraw::Init () override virtual
Reimplemented from OnlMonDraw.
Definition at line 45 of file MvtxMonDraw.cc.
View newest version in sPHENIX GitHub at line 45 of file MvtxMonDraw.cc
int MvtxMonDraw::MakeCanvas (const std::string & name) private
Definition at line 50 of file MvtxMonDraw.cc.
View newest version in sPHENIX GitHub at line 50 of file MvtxMonDraw.cc
References OnlMonClient::GetDisplaySizeX(), OnlMonClient::GetDisplaySizeY(), OnlMonClient::instance(), Pad, TC, and transparent.
Referenced by DrawFEE(), DrawFHR(), DrawGeneral(), DrawHistory(), DrawHitMap(), and DrawOCC().
int MvtxMonDraw::MakeHtml (const std::string & what = "ALL") override virtual
Reimplemented from OnlMonDraw.
Definition at line 1052 of file MvtxMonDraw.cc.
View newest version in sPHENIX GitHub at line 1052 of file MvtxMonDraw.cc
References OnlMonClient::CanvasToPng(), Draw(), OnlMonClient::htmlRegisterPage(), OnlMonClient::instance(), TC, and to_string().
template<typename T > int MvtxMonDraw::MergeServers (T * h)
Definition at line 1263 of file MvtxMonDraw.cc.
View newest version in sPHENIX GitHub at line 1263 of file MvtxMonDraw.cc
References NFlx, and Acts::UnitConstants::T.
int MvtxMonDraw::PublishHistogram (TCanvas * c, int pad, TH1 * h, const char * opt = "")
Definition at line 1222 of file MvtxMonDraw.cc.
View newest version in sPHENIX GitHub at line 1222 of file MvtxMonDraw.cc
Referenced by DrawFEE(), DrawFHR(), DrawGeneral(), DrawHitMap(), DrawOCC(), and PublishHistogram().
int MvtxMonDraw::PublishHistogram (TPad * p, TH1 * h, const char * opt = "")
Definition at line 1250 of file MvtxMonDraw.cc.
View newest version in sPHENIX GitHub at line 1250 of file MvtxMonDraw.cc
References Acts::PhysicalConstants::c, and PublishHistogram().
int MvtxMonDraw::PublishHistogram (TPad * p, int pad, TH1 * h, const char * opt = "")
Definition at line 1238 of file MvtxMonDraw.cc.
View newest version in sPHENIX GitHub at line 1238 of file MvtxMonDraw.cc
References Acts::PhysicalConstants::c, and PublishHistogram().
void MvtxMonDraw::PublishStatistics (TCanvas * c, OnlMonClient * cl)
Definition at line 1285 of file MvtxMonDraw.cc.
View newest version in sPHENIX GitHub at line 1285 of file MvtxMonDraw.cc
References OnlMonClient::EventTime(), OnlMonClient::RunNumber(), OnlMonDraw::ThisName, and transparent.
Referenced by DrawFEE(), DrawFHR(), DrawGeneral(), DrawHitMap(), and DrawOCC().
int MvtxMonDraw::SavePlot (const std::string & what = "ALL", const std::string & type = "png") override virtual
Reimplemented from OnlMonDraw.
Definition at line 1028 of file MvtxMonDraw.cc.
View newest version in sPHENIX GitHub at line 1028 of file MvtxMonDraw.cc
References OnlMonClient::CanvasToPng(), Draw(), filename, OnlMonClient::instance(), OnlMonClient::RunNumber(), TC, OnlMonDraw::ThisName, and to_string().
Member Data Documentation
const int MvtxMonDraw::chipmapoffset[3] = { 0, 12, 28} private
Definition at line 56 of file MvtxMonDraw.h.
View newest version in sPHENIX GitHub at line 56 of file MvtxMonDraw.h
Referenced by DrawHitMap().
OnlMonDB* MvtxMonDraw::dbvars[NFlx] = {nullptr} private
Definition at line 73 of file MvtxMonDraw.h.
View newest version in sPHENIX GitHub at line 73 of file MvtxMonDraw.h
Referenced by DrawHistory(), and MvtxMonDraw().
TGraphErrors* MvtxMonDraw::gr[6] = {nullptr} private
Definition at line 72 of file MvtxMonDraw.h.
View newest version in sPHENIX GitHub at line 72 of file MvtxMonDraw.h
Referenced by DrawHistory().
int MvtxMonDraw::maxbadchips = 2 private
Definition at line 77 of file MvtxMonDraw.h.
View newest version in sPHENIX GitHub at line 77 of file MvtxMonDraw.h
Referenced by analyseForError().
std::string MvtxMonDraw::mLaneStatusFlag[NFlags] = { "WARNING", "ERROR", "FAULT" }
Definition at line 37 of file MvtxMonDraw.h.
View newest version in sPHENIX GitHub at line 37 of file MvtxMonDraw.h
Referenced by DrawFEE().
const int MvtxMonDraw::NCHIP = 9 static
Definition at line 32 of file MvtxMonDraw.h.
View newest version in sPHENIX GitHub at line 32 of file MvtxMonDraw.h
Referenced by DrawHitMap().
constexpr int MvtxMonDraw::NCols = 1024 static private
Definition at line 53 of file MvtxMonDraw.h.
View newest version in sPHENIX GitHub at line 53 of file MvtxMonDraw.h
constexpr int MvtxMonDraw::NFlags = 3 static
Definition at line 34 of file MvtxMonDraw.h.
View newest version in sPHENIX GitHub at line 34 of file MvtxMonDraw.h
Referenced by analyseForError(), and mvtxDrawInit().
const int MvtxMonDraw::NFlx = 6 static private
Definition at line 52 of file MvtxMonDraw.h.
View newest version in sPHENIX GitHub at line 52 of file MvtxMonDraw.h
Referenced by DrawFEE(), DrawFHR(), DrawGeneral(), DrawHistory(), DrawHitMap(), DrawOCC(), MergeServers(), and MvtxMonDraw().
const int MvtxMonDraw::NLAYERS = 3 static
Definition at line 33 of file MvtxMonDraw.h.
View newest version in sPHENIX GitHub at line 33 of file MvtxMonDraw.h
Referenced by analyseForError().
constexpr int MvtxMonDraw::NPixels = NRows * NCols static private
Definition at line 55 of file MvtxMonDraw.h.
View newest version in sPHENIX GitHub at line 55 of file MvtxMonDraw.h
constexpr int MvtxMonDraw::NRows = 512 static private
Definition at line 54 of file MvtxMonDraw.h.
View newest version in sPHENIX GitHub at line 54 of file MvtxMonDraw.h
const int MvtxMonDraw::NSTAVE = 48 static
Definition at line 31 of file MvtxMonDraw.h.
View newest version in sPHENIX GitHub at line 31 of file MvtxMonDraw.h
Referenced by analyseForError().
const int MvtxMonDraw::NStaves[NLAYERS] = { 12, 16, 20 }
Definition at line 35 of file MvtxMonDraw.h.
View newest version in sPHENIX GitHub at line 35 of file MvtxMonDraw.h
Referenced by analyseForError(), and DrawOCC().
TPad* MvtxMonDraw::Pad[6] = {nullptr} private
Definition at line 71 of file MvtxMonDraw.h.
View newest version in sPHENIX GitHub at line 71 of file MvtxMonDraw.h
Referenced by DrawFEE(), DrawFHR(), DrawGeneral(), DrawHistory(), DrawHitMap(), DrawOCC(), and MakeCanvas().
const int MvtxMonDraw::StaveBoundary[NLAYERS+1] = { 0, 12, 28, 48}
Definition at line 36 of file MvtxMonDraw.h.
View newest version in sPHENIX GitHub at line 36 of file MvtxMonDraw.h
Referenced by analyseForError(), and DrawOCC().
TCanvas* MvtxMonDraw::TC[6] = {nullptr} private
Definition at line 69 of file MvtxMonDraw.h.
View newest version in sPHENIX GitHub at line 69 of file MvtxMonDraw.h
Referenced by DrawFEE(), DrawFHR(), DrawGeneral(), DrawHistory(), DrawHitMap(), DrawOCC(), MakeCanvas(), MakeHtml(), and SavePlot().
int MvtxMonDraw::TimeOffsetTicks = -1 private
Definition at line 68 of file MvtxMonDraw.h.
View newest version in sPHENIX GitHub at line 68 of file MvtxMonDraw.h
Referenced by DrawHistory(), and MvtxMonDraw().
TPad* MvtxMonDraw::transparent[1] = {nullptr} private
Definition at line 70 of file MvtxMonDraw.h.
View newest version in sPHENIX GitHub at line 70 of file MvtxMonDraw.h
Referenced by MakeCanvas(), and PublishStatistics().
The documentation for this class was generated from the following files:
OnlMon/blob/main/subsystems/mvtx/MvtxMonDraw.h
OnlMon/blob/main/subsystems/mvtx/MvtxMonDraw.cc