Analysis Software: ActsExamples::Digitization::Uniform Struct Reference
ActsExamples::Digitization::Uniform Struct Reference
#include <acts/blob/sPHENIX/Examples/Algorithms/Digitization/include/ActsExamples/Digitization/Smearers.hpp>
Public Member Functions
Uniform (double pitch, const std::pair< double, double > &range_)
Construct with a.
Uniform (Acts::BinningData &&bd)
Acts::Result< std::pair
< double, double > > operator() (double value, RandomEngine &rnd) const
Public Attributes
Acts::BinningData binningData
Detailed Description
Uniform smearing of a single parameter within bounds.
It estimates the bin borders and smears uniformly between them
Definition at line 136 of file Smearers.hpp.
View newest version in sPHENIX GitHub at line 136 of file Smearers.hpp
Constructor & Destructor Documentation
ActsExamples::Digitization::Uniform::Uniform (double pitch, const std::pair< double, double > & range_) inline
Construct with a.
Parameters
pitch standard deviation and
range
Definition at line 140 of file Smearers.hpp.
View newest version in sPHENIX GitHub at line 140 of file Smearers.hpp
ActsExamples::Digitization::Uniform::Uniform (Acts::BinningData && bd) inline
Constructor with a binning data in order to get the bin borders.
Parameters
bu the binning data
Definition at line 148 of file Smearers.hpp.
View newest version in sPHENIX GitHub at line 148 of file Smearers.hpp
Member Function Documentation
Acts::Result<std::pair<double, double> > ActsExamples::Digitization::Uniform::operator() (double value, RandomEngine & rnd) const inline
Call operator for the SmearFunction caller interface.
Parameters
value parameter to be smeared
rnd random generator to be used for the call
Returns
a Result is uniformly distributed between bin borders
Definition at line 156 of file Smearers.hpp.
View newest version in sPHENIX GitHub at line 156 of file Smearers.hpp
References binningData, Acts::BinningData::boundaries(), dist(), test_detectors::lower, Acts::BinningData::max, Acts::BinningData::min, and Acts::BinningData::search().
Member Data Documentation
Acts::BinningData ActsExamples::Digitization::Uniform::binningData
Definition at line 137 of file Smearers.hpp.
View newest version in sPHENIX GitHub at line 137 of file Smearers.hpp
Referenced by operator()().
The documentation for this struct was generated from the following file:
acts/blob/sPHENIX/Examples/Algorithms/Digitization/include/ActsExamples/Digitization/Smearers.hpp