Analysis Software: SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::TrkInfo Struct Reference
SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::TrkInfo Struct Reference
#include <analysis/blob/master/AndersonAnalysisModules/ColdQcdCorrelatorAnalysis/SCorrelatorUtilities/src/TrkTools.h>
Public Member Functions
void SetInfo (SvtxTrack *track, PHCompositeNode *topNode)
void Reset ()
TrkInfo ()
~TrkInfo ()
TrkInfo (SvtxTrack *track, PHCompositeNode *topNode)
Static Public Member Functions
static vector< string > GetListOfMembers ()
Public Attributes
int id = numeric_limits<int>::max()
int nMvtxLayer = numeric_limits<int>::max()
int nInttLayer = numeric_limits<int>::max()
int nTpcLayer = numeric_limits<int>::max()
int nMvtxClust = numeric_limits<int>::max()
int nInttClust = numeric_limits<int>::max()
int nTpcClust = numeric_limits<int>::max()
double phi = numeric_limits<double>::max()
double ene = numeric_limits<double>::max()
double px = numeric_limits<double>::max()
double py = numeric_limits<double>::max()
double pz = numeric_limits<double>::max()
double pt = numeric_limits<double>::max()
double eta = numeric_limits<double>::max()
double dcaXY = numeric_limits<double>::max()
double dcaZ = numeric_limits<double>::max()
double ptErr = numeric_limits<double>::max()
double quality = numeric_limits<double>::max()
double vtxX = numeric_limits<double>::max()
double vtxY = numeric_limits<double>::max()
double vtxZ = numeric_limits<double>::max()
Friends
bool operator< (const TrkInfo &lhs, const TrkInfo &rhs)
bool operator> (const TrkInfo &lhs, const TrkInfo &rhs)
bool operator<= (const TrkInfo &lhs, const TrkInfo &rhs)
bool operator>= (const TrkInfo &lhs, const TrkInfo &rhs)
Detailed Description
Definition at line 62 of file TrkTools.h.
View newest version in sPHENIX GitHub at line 62 of file TrkTools.h
Constructor & Destructor Documentation
SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::TrkInfo::TrkInfo () inline
Definition at line 235 of file TrkTools.h.
View newest version in sPHENIX GitHub at line 235 of file TrkTools.h
SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::TrkInfo::~TrkInfo () inline
Definition at line 236 of file TrkTools.h.
View newest version in sPHENIX GitHub at line 236 of file TrkTools.h
SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::TrkInfo::TrkInfo (SvtxTrack * track, PHCompositeNode * topNode) inline
Definition at line 239 of file TrkTools.h.
View newest version in sPHENIX GitHub at line 239 of file TrkTools.h
Member Function Documentation
static vector<string> SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::TrkInfo::GetListOfMembers () inline static
Definition at line 143 of file TrkTools.h.
View newest version in sPHENIX GitHub at line 143 of file TrkTools.h
void SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::TrkInfo::Reset () inline
Definition at line 118 of file TrkTools.h.
View newest version in sPHENIX GitHub at line 118 of file TrkTools.h
References eta, ActsTests::PropagationDatasets::phi, and physmon_track_finding_ttbar::pt.
void SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::TrkInfo::SetInfo (SvtxTrack * track, PHCompositeNode * topNode) inline
Definition at line 87 of file TrkTools.h.
View newest version in sPHENIX GitHub at line 87 of file TrkTools.h
References eta, SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::GetNumClust(), SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::GetNumLayer(), SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::GetTrackDcaPair(), SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::GetTrackDeltaPt(), SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::GetTrackVertex(), Intt(), Mvtx(), ActsTests::PropagationDatasets::phi, and physmon_track_finding_ttbar::pt.
Friends And Related Function Documentation
bool operator< (const TrkInfo & lhs, const TrkInfo & rhs) friend
Definition at line 171 of file TrkTools.h.
View newest version in sPHENIX GitHub at line 171 of file TrkTools.h
bool operator<= (const TrkInfo & lhs, const TrkInfo & rhs) friend
Definition at line 231 of file TrkTools.h.
View newest version in sPHENIX GitHub at line 231 of file TrkTools.h
bool operator> (const TrkInfo & lhs, const TrkInfo & rhs) friend
Definition at line 201 of file TrkTools.h.
View newest version in sPHENIX GitHub at line 201 of file TrkTools.h
bool operator>= (const TrkInfo & lhs, const TrkInfo & rhs) friend
Definition at line 232 of file TrkTools.h.
View newest version in sPHENIX GitHub at line 232 of file TrkTools.h
Member Data Documentation
double SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::TrkInfo::dcaXY = numeric_limits<double>::max()
Definition at line 79 of file TrkTools.h.
View newest version in sPHENIX GitHub at line 79 of file TrkTools.h
Referenced by SColdQcdCorrelatorAnalysis::SCheckTrackPairs::DoDoubleTrackLoop(), Fun4All_RunCorrelatorQAModules(), and SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::IsInSigmaDcaCut().
double SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::TrkInfo::dcaZ = numeric_limits<double>::max()
Definition at line 80 of file TrkTools.h.
View newest version in sPHENIX GitHub at line 80 of file TrkTools.h
Referenced by SColdQcdCorrelatorAnalysis::SCheckTrackPairs::DoDoubleTrackLoop(), Fun4All_RunCorrelatorQAModules(), and SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::IsInSigmaDcaCut().
double SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::TrkInfo::ene = numeric_limits<double>::max()
Definition at line 73 of file TrkTools.h.
View newest version in sPHENIX GitHub at line 73 of file TrkTools.h
Referenced by SColdQcdCorrelatorAnalysis::SCheckTrackPairs::DoDoubleTrackLoop().
double SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::TrkInfo::eta = numeric_limits<double>::max()
Definition at line 78 of file TrkTools.h.
View newest version in sPHENIX GitHub at line 78 of file TrkTools.h
Referenced by SColdQcdCorrelatorAnalysis::SCheckTrackPairs::DoDoubleTrackLoop(), and Fun4All_RunCorrelatorQAModules().
int SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::TrkInfo::id = numeric_limits<int>::max()
Definition at line 65 of file TrkTools.h.
View newest version in sPHENIX GitHub at line 65 of file TrkTools.h
Referenced by SColdQcdCorrelatorAnalysis::SCheckTrackPairs::DoDoubleTrackLoop().
int SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::TrkInfo::nInttClust = numeric_limits<int>::max()
Definition at line 70 of file TrkTools.h.
View newest version in sPHENIX GitHub at line 70 of file TrkTools.h
Referenced by SColdQcdCorrelatorAnalysis::SCheckTrackPairs::DoDoubleTrackLoop().
int SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::TrkInfo::nInttLayer = numeric_limits<int>::max()
Definition at line 67 of file TrkTools.h.
View newest version in sPHENIX GitHub at line 67 of file TrkTools.h
Referenced by SColdQcdCorrelatorAnalysis::SCheckTrackPairs::DoDoubleTrackLoop(), and Fun4All_RunCorrelatorQAModules().
int SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::TrkInfo::nMvtxClust = numeric_limits<int>::max()
Definition at line 69 of file TrkTools.h.
View newest version in sPHENIX GitHub at line 69 of file TrkTools.h
Referenced by SColdQcdCorrelatorAnalysis::SCheckTrackPairs::DoDoubleTrackLoop().
int SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::TrkInfo::nMvtxLayer = numeric_limits<int>::max()
Definition at line 66 of file TrkTools.h.
View newest version in sPHENIX GitHub at line 66 of file TrkTools.h
Referenced by SColdQcdCorrelatorAnalysis::SCheckTrackPairs::DoDoubleTrackLoop(), and Fun4All_RunCorrelatorQAModules().
int SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::TrkInfo::nTpcClust = numeric_limits<int>::max()
Definition at line 71 of file TrkTools.h.
View newest version in sPHENIX GitHub at line 71 of file TrkTools.h
Referenced by SColdQcdCorrelatorAnalysis::SCheckTrackPairs::DoDoubleTrackLoop().
int SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::TrkInfo::nTpcLayer = numeric_limits<int>::max()
Definition at line 68 of file TrkTools.h.
View newest version in sPHENIX GitHub at line 68 of file TrkTools.h
Referenced by SColdQcdCorrelatorAnalysis::SCheckTrackPairs::DoDoubleTrackLoop(), and Fun4All_RunCorrelatorQAModules().
double SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::TrkInfo::phi = numeric_limits<double>::max()
Definition at line 72 of file TrkTools.h.
View newest version in sPHENIX GitHub at line 72 of file TrkTools.h
Referenced by SColdQcdCorrelatorAnalysis::SCheckTrackPairs::DoDoubleTrackLoop().
double SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::TrkInfo::pt = numeric_limits<double>::max()
Definition at line 77 of file TrkTools.h.
View newest version in sPHENIX GitHub at line 77 of file TrkTools.h
Referenced by SColdQcdCorrelatorAnalysis::SCheckTrackPairs::DoDoubleTrackLoop(), Fun4All_RunCorrelatorQAModules(), and SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::IsInSigmaDcaCut().
double SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::TrkInfo::ptErr = numeric_limits<double>::max()
Definition at line 81 of file TrkTools.h.
View newest version in sPHENIX GitHub at line 81 of file TrkTools.h
Referenced by SColdQcdCorrelatorAnalysis::SCheckTrackPairs::DoDoubleTrackLoop(), and Fun4All_RunCorrelatorQAModules().
double SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::TrkInfo::px = numeric_limits<double>::max()
Definition at line 74 of file TrkTools.h.
View newest version in sPHENIX GitHub at line 74 of file TrkTools.h
Referenced by SColdQcdCorrelatorAnalysis::SCheckTrackPairs::DoDoubleTrackLoop().
double SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::TrkInfo::py = numeric_limits<double>::max()
Definition at line 75 of file TrkTools.h.
View newest version in sPHENIX GitHub at line 75 of file TrkTools.h
Referenced by SColdQcdCorrelatorAnalysis::SCheckTrackPairs::DoDoubleTrackLoop().
double SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::TrkInfo::pz = numeric_limits<double>::max()
Definition at line 76 of file TrkTools.h.
View newest version in sPHENIX GitHub at line 76 of file TrkTools.h
Referenced by SColdQcdCorrelatorAnalysis::SCheckTrackPairs::DoDoubleTrackLoop().
double SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::TrkInfo::quality = numeric_limits<double>::max()
Definition at line 82 of file TrkTools.h.
View newest version in sPHENIX GitHub at line 82 of file TrkTools.h
Referenced by SColdQcdCorrelatorAnalysis::SCheckTrackPairs::DoDoubleTrackLoop(), and Fun4All_RunCorrelatorQAModules().
double SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::TrkInfo::vtxX = numeric_limits<double>::max()
Definition at line 83 of file TrkTools.h.
View newest version in sPHENIX GitHub at line 83 of file TrkTools.h
Referenced by SColdQcdCorrelatorAnalysis::SCheckTrackPairs::DoDoubleTrackLoop().
double SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::TrkInfo::vtxY = numeric_limits<double>::max()
Definition at line 84 of file TrkTools.h.
View newest version in sPHENIX GitHub at line 84 of file TrkTools.h
Referenced by SColdQcdCorrelatorAnalysis::SCheckTrackPairs::DoDoubleTrackLoop().
double SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::TrkInfo::vtxZ = numeric_limits<double>::max()
Definition at line 85 of file TrkTools.h.
View newest version in sPHENIX GitHub at line 85 of file TrkTools.h
Referenced by SColdQcdCorrelatorAnalysis::SCheckTrackPairs::DoDoubleTrackLoop().
The documentation for this struct was generated from the following file:
analysis/blob/master/AndersonAnalysisModules/ColdQcdCorrelatorAnalysis/SCorrelatorUtilities/src/TrkTools.h