Analysis Software: G4Example01SteppingAction Class Reference
G4Example01SteppingAction Class Reference
#include <g4exampledetector/blob/master/simple/source/G4Example01SteppingAction.h>
Public Member Functions
G4Example01SteppingAction (G4Example01Detector *)
constructor
virtual ~G4Example01SteppingAction ()
destructor
virtual bool UserSteppingAction (const G4Step *, bool)
stepping action
virtual void SetInterfacePointers (PHCompositeNode *)
reimplemented from base class
Public Member Functions inherited from PHG4SteppingAction
PHG4SteppingAction (const std::string &name, const int i=0)
virtual ~PHG4SteppingAction ()
virtual void Verbosity (const int i)
virtual int Verbosity () const
virtual int Init ()
virtual int InitWithNode (PHCompositeNode *)
virtual double GetScintLightYield (const G4Step *step)
get scintillation photon count. It require a custom set SCINTILLATIONYIELD property to work
virtual double GetVisibleEnergyDeposition (const G4Step *step)
get amount of energy that can make scintillation light, in Unit of GeV.
virtual void StoreLocalCoordinate (PHG4Hit *hit, const G4Step *step, const bool do_prepoint, const bool do_postpoint)
Extract local coordinate of the hit and save to PHG4Hit.
virtual void Print (const std::string &) const
std::string GetName () const
void SetName (const std::string &name)
virtual void SetLightCorrection (const double inner_radius, const double inner_corr, const double outer_radius, const double outer_corr)
virtual double GetLightCorrection (const double r) const
virtual double GetLightCorrection (const double xpos, const double ypos) const
virtual bool ValidCorrection () const
virtual void SetHitNodeName (const std::string &, const std::string &)
Set the G4HIT node names from Subsystem rather than constructing your own.
Private Attributes
G4Example01Detector * m_Detector
pointer to the detector
PHG4HitContainer * m_HitContainer
pointer to hit container
PHG4Hit * m_Hit
PHG4HitContainer * m_SaveHitContainer
G4VPhysicalVolume * m_SaveVolPre
G4VPhysicalVolume * m_SaveVolPost
int m_SaveTrackId
int m_SavePreStepStatus
int m_SavePostStepStatus
double m_EdepSum
double m_EionSum
Detailed Description
Definition at line 15 of file G4Example01SteppingAction.h.
View newest version in sPHENIX GitHub at line 15 of file G4Example01SteppingAction.h
Constructor & Destructor Documentation
G4Example01SteppingAction::G4Example01SteppingAction (G4Example01Detector * detector)
constructor
Definition at line 41 of file G4Example01SteppingAction.cc.
View newest version in sPHENIX GitHub at line 41 of file G4Example01SteppingAction.cc
G4Example01SteppingAction::~G4Example01SteppingAction () virtual
destructor
Definition at line 57 of file G4Example01SteppingAction.cc.
View newest version in sPHENIX GitHub at line 57 of file G4Example01SteppingAction.cc
References m_Hit.
Member Function Documentation
void G4Example01SteppingAction::SetInterfacePointers (PHCompositeNode * topNode) virtual
reimplemented from base class
Reimplemented from PHG4SteppingAction.
Definition at line 277 of file G4Example01SteppingAction.cc.
View newest version in sPHENIX GitHub at line 277 of file G4Example01SteppingAction.cc
References PHG4Detector::GetName(), m_Detector, and m_HitContainer.
bool G4Example01SteppingAction::UserSteppingAction (const G4Step * aStep, bool was_used) virtual
stepping action
Implements PHG4SteppingAction.
Definition at line 67 of file G4Example01SteppingAction.cc.
View newest version in sPHENIX GitHub at line 67 of file G4Example01SteppingAction.cc
References PHG4HitContainer::AddHit(), Acts::UnitConstants::cm, PHG4Hit::get_hit_id(), PHG4Hit::get_x(), PHG4HitContainer::GetID(), PHG4SteppingAction::GetName(), PHG4StepStatusDecode::GetStepStatus(), Acts::UnitConstants::GeV, G4Example01Detector::IsInDetector(), m_Detector, m_EdepSum, m_EionSum, m_Hit, m_HitContainer, m_SaveHitContainer, m_SavePostStepStatus, m_SavePreStepStatus, m_SaveTrackId, m_SaveVolPost, m_SaveVolPre, merge_hashes::p, PHG4Hit::Reset(), PHG4Hit::set_edep(), PHG4Hit::set_eion(), PHG4Hit::set_layer(), PHG4Hit::set_t(), PHG4Hit::set_trkid(), PHG4Hit::set_x(), PHG4Hit::set_y(), and PHG4Hit::set_z().
Member Data Documentation
G4Example01Detector* G4Example01SteppingAction::m_Detector private
pointer to the detector
Definition at line 32 of file G4Example01SteppingAction.h.
View newest version in sPHENIX GitHub at line 32 of file G4Example01SteppingAction.h
Referenced by SetInterfacePointers(), and UserSteppingAction().
double G4Example01SteppingAction::m_EdepSum private
Definition at line 43 of file G4Example01SteppingAction.h.
View newest version in sPHENIX GitHub at line 43 of file G4Example01SteppingAction.h
Referenced by UserSteppingAction().
double G4Example01SteppingAction::m_EionSum private
Definition at line 44 of file G4Example01SteppingAction.h.
View newest version in sPHENIX GitHub at line 44 of file G4Example01SteppingAction.h
Referenced by UserSteppingAction().
PHG4Hit* G4Example01SteppingAction::m_Hit private
Definition at line 35 of file G4Example01SteppingAction.h.
View newest version in sPHENIX GitHub at line 35 of file G4Example01SteppingAction.h
Referenced by UserSteppingAction(), and ~G4Example01SteppingAction().
PHG4HitContainer* G4Example01SteppingAction::m_HitContainer private
pointer to hit container
Definition at line 34 of file G4Example01SteppingAction.h.
View newest version in sPHENIX GitHub at line 34 of file G4Example01SteppingAction.h
Referenced by SetInterfacePointers(), and UserSteppingAction().
PHG4HitContainer* G4Example01SteppingAction::m_SaveHitContainer private
Definition at line 36 of file G4Example01SteppingAction.h.
View newest version in sPHENIX GitHub at line 36 of file G4Example01SteppingAction.h
Referenced by UserSteppingAction().
int G4Example01SteppingAction::m_SavePostStepStatus private
Definition at line 42 of file G4Example01SteppingAction.h.
View newest version in sPHENIX GitHub at line 42 of file G4Example01SteppingAction.h
Referenced by UserSteppingAction().
int G4Example01SteppingAction::m_SavePreStepStatus private
Definition at line 41 of file G4Example01SteppingAction.h.
View newest version in sPHENIX GitHub at line 41 of file G4Example01SteppingAction.h
Referenced by UserSteppingAction().
int G4Example01SteppingAction::m_SaveTrackId private
Definition at line 40 of file G4Example01SteppingAction.h.
View newest version in sPHENIX GitHub at line 40 of file G4Example01SteppingAction.h
Referenced by UserSteppingAction().
G4VPhysicalVolume* G4Example01SteppingAction::m_SaveVolPost private
Definition at line 39 of file G4Example01SteppingAction.h.
View newest version in sPHENIX GitHub at line 39 of file G4Example01SteppingAction.h
Referenced by UserSteppingAction().
G4VPhysicalVolume* G4Example01SteppingAction::m_SaveVolPre private
Definition at line 38 of file G4Example01SteppingAction.h.
View newest version in sPHENIX GitHub at line 38 of file G4Example01SteppingAction.h
Referenced by UserSteppingAction().
The documentation for this class was generated from the following files:
g4exampledetector/blob/master/simple/source/G4Example01SteppingAction.h
g4exampledetector/blob/master/simple/source/G4Example01SteppingAction.cc