Analysis Software: RawTowerGeom Class Reference
RawTowerGeom Class Reference
#include <coresoftware/blob/master/offline/packages/CaloBase/RawTowerGeom.h>
Public Member Functions
~RawTowerGeom () override
void identify (std::ostream &os=std::cout) const override
virtual void set_id (RawTowerDefs::keytype)
virtual RawTowerDefs::keytype get_id () const
virtual int get_bineta () const
virtual int get_binphi () const
virtual int get_binl () const
virtual int get_column () const
virtual int get_row () const
virtual void set_center_x (double)
virtual void set_center_y (double)
virtual void set_center_z (double)
virtual void set_size_x (double)
virtual void set_size_y (double)
virtual void set_size_z (double)
virtual double get_center_x () const
virtual double get_center_y () const
virtual double get_center_z () const
virtual double get_size_x () const
virtual double get_size_y () const
virtual double get_size_z () const
virtual double get_volume () const
virtual double get_center_radius () const
virtual double get_eta () const
virtual double get_theta () const
virtual double get_phi () const
virtual void set_tower_type (int)
virtual int get_tower_type () const
virtual double get_roty () const
virtual double get_rotz () const
virtual void set_roty (double)
virtual void set_rotz (double)
Public Member Functions inherited from PHObject
PHObject ()
ctor
~PHObject () override
dtor
virtual PHObject * CloneMe () const
Virtual copy constructor.
virtual PHObject * clone () const final
PHObject * Clone (const char *newname="") const final
void Copy (TObject &object) const final
virtual void Reset ()
Clear Event.
virtual int isValid () const
isValid returns non zero if object contains vailid data
virtual int Integrate () const
virtual int Integrate (PHObject *)
virtual void CopyFrom (const PHObject *obj)
Protected Member Functions
RawTowerGeom ()
Detailed Description
Definition at line 12 of file RawTowerGeom.h.
View newest version in sPHENIX GitHub at line 12 of file RawTowerGeom.h
Constructor & Destructor Documentation
RawTowerGeom::~RawTowerGeom () inline override
Definition at line 15 of file RawTowerGeom.h.
View newest version in sPHENIX GitHub at line 15 of file RawTowerGeom.h
RawTowerGeom::RawTowerGeom () inline protected
Definition at line 193 of file RawTowerGeom.h.
View newest version in sPHENIX GitHub at line 193 of file RawTowerGeom.h
Member Function Documentation
virtual int RawTowerGeom::get_bineta () const inline virtual
Reimplemented in RawTowerGeomv4, RawTowerGeomv1, RawTowerGeomv3, and RawTowerGeomv2.
Definition at line 27 of file RawTowerGeom.h.
View newest version in sPHENIX GitHub at line 27 of file RawTowerGeom.h
References PHOOL_VIRTUAL_WARN.
Referenced by sPHAnalysis::Get_CAL_e3x3(), IsolatedTrackAnalysis::getSimTowers(), IsolatedTrackAnalysis::getTowers(), RawClusterDeadHotMask::process_event(), TowerInfoDeadHotMask::process_event(), RawTowerDeadTowerInterp::process_event(), RetowerCEMC::process_event(), TruthCaloTree::process_event(), sPHAnalysis::process_event_notracking(), sPHAnalysis_calo::process_event_test(), CaloAna::process_towers(), and pi0EtaByEta::process_towers().
virtual int RawTowerGeom::get_binl () const inline virtual
Reimplemented in RawTowerGeomv3.
Definition at line 39 of file RawTowerGeom.h.
View newest version in sPHENIX GitHub at line 39 of file RawTowerGeom.h
References PHOOL_VIRTUAL_WARN.
virtual int RawTowerGeom::get_binphi () const inline virtual
Reimplemented in RawTowerGeomv4, RawTowerGeomv1, RawTowerGeomv3, and RawTowerGeomv2.
Definition at line 33 of file RawTowerGeom.h.
View newest version in sPHENIX GitHub at line 33 of file RawTowerGeom.h
References PHOOL_VIRTUAL_WARN.
Referenced by sPHAnalysis::Get_CAL_e3x3(), IsolatedTrackAnalysis::getSimTowers(), IsolatedTrackAnalysis::getTowers(), RawClusterDeadHotMask::process_event(), TowerInfoDeadHotMask::process_event(), RawTowerDeadTowerInterp::process_event(), TruthCaloTree::process_event(), sPHAnalysis::process_event_notracking(), sPHAnalysis_calo::process_event_test(), CaloAna::process_towers(), and pi0EtaByEta::process_towers().
virtual double RawTowerGeom::get_center_radius () const inline virtual
Reimplemented in RawTowerGeomv3, RawTowerGeomv2, RawTowerGeomv4, and RawTowerGeomv1.
Definition at line 135 of file RawTowerGeom.h.
View newest version in sPHENIX GitHub at line 135 of file RawTowerGeom.h
References PHOOL_VIRTUAL_WARN.
Referenced by TowerJetInput::get_input(), and MyJetAnalysis::process_event().
virtual double RawTowerGeom::get_center_x () const inline virtual
Reimplemented in RawTowerGeomv3, RawTowerGeomv2, RawTowerGeomv4, and RawTowerGeomv1.
Definition at line 93 of file RawTowerGeom.h.
View newest version in sPHENIX GitHub at line 93 of file RawTowerGeom.h
References PHOOL_VIRTUAL_WARN.
Referenced by PHG4OHCalDetector::AddGeometryNode(), PHG4IHCalDetector::AddGeometryNode(), PHG4OuterHcalDetector::AddGeometryNode(), PHG4InnerHcalDetector::AddGeometryNode(), PHG4SpacalDetector::AddTowerGeometryNode(), CaloGeomMapping::CreateGeomNode(), RawTowerBuilder::CreateNodes(), RawClusterBuilderTopo::export_clusters(), CaloEvaluator::fillOutputNtuples(), sPHAnalysis::Get_CAL_e3x3(), TowerJetInput::get_input(), TrackProjectionTools::getE33Forward(), ClusterIso::getTowerEta(), RawClusterBuilderTemplate::InitRun(), HcalRawTowerBuilder::InitRun(), RawClusterBuilderGraph::process_event(), MyJetAnalysis::process_event(), sPHAnalysis::process_event_notracking(), and sPHAnalysis_calo::process_event_test().
virtual double RawTowerGeom::get_center_y () const inline virtual
Reimplemented in RawTowerGeomv3, RawTowerGeomv2, RawTowerGeomv4, and RawTowerGeomv1.
Definition at line 99 of file RawTowerGeom.h.
View newest version in sPHENIX GitHub at line 99 of file RawTowerGeom.h
References PHOOL_VIRTUAL_WARN.
Referenced by CaloGeomMapping::CreateGeomNode(), RawClusterBuilderTopo::export_clusters(), CaloEvaluator::fillOutputNtuples(), sPHAnalysis::Get_CAL_e3x3(), TowerJetInput::get_input(), TrackProjectionTools::getE33Forward(), ClusterIso::getTowerEta(), RawClusterBuilderTemplate::InitRun(), RawClusterBuilderGraph::process_event(), MyJetAnalysis::process_event(), sPHAnalysis::process_event_notracking(), and sPHAnalysis_calo::process_event_test().
virtual double RawTowerGeom::get_center_z () const inline virtual
Reimplemented in RawTowerGeomv3, RawTowerGeomv2, RawTowerGeomv4, and RawTowerGeomv1.
Definition at line 105 of file RawTowerGeom.h.
View newest version in sPHENIX GitHub at line 105 of file RawTowerGeom.h
References PHOOL_VIRTUAL_WARN.
Referenced by CaloGeomMapping::CreateGeomNode(), RawClusterBuilderTopo::export_clusters(), CaloEvaluator::fillOutputNtuples(), sPHAnalysis::Get_CAL_e3x3(), TowerJetInput::get_input(), ClusterIso::getTowerEta(), RawClusterBuilderTemplate::InitRun(), RawClusterBuilderGraph::process_event(), MyJetAnalysis::process_event(), sPHAnalysis::process_event_notracking(), and sPHAnalysis_calo::process_event_test().
virtual int RawTowerGeom::get_column () const inline virtual
Reimplemented in RawTowerGeomv4, RawTowerGeomv3, RawTowerGeomv1, and RawTowerGeomv2.
Definition at line 45 of file RawTowerGeom.h.
View newest version in sPHENIX GitHub at line 45 of file RawTowerGeom.h
References PHOOL_VIRTUAL_WARN.
Referenced by EpFinderEval::fill_tree(), and Calib::fill_tree().
virtual double RawTowerGeom::get_eta () const inline virtual
Reimplemented in RawTowerGeomv3, RawTowerGeomv2, RawTowerGeomv4, and RawTowerGeomv1.
Definition at line 141 of file RawTowerGeom.h.
View newest version in sPHENIX GitHub at line 141 of file RawTowerGeom.h
References PHOOL_VIRTUAL_WARN.
Referenced by DISKinematicsReco::AddGlobalCalorimeterInformation(), LeptoquarksReco::AddGlobalEventInformation(), LeptoquarksReco::AddJetStructureInformation(), TreeMaker::CopyAndMakeJets(), RawClusterBuilderTopo::export_clusters(), EpFinderEval::fill_tree(), Calib::fill_tree(), CaloEvaluator::fillOutputNtuples(), HCalJetPhiShift::FillTTree(), IsolatedTrackAnalysis::getSimTowers(), ClusterIso::getTowerEta(), IsolatedTrackAnalysis::getTowers(), RawClusterBuilderTopo::process_event(), ClusterIso::process_event(), SubtractTowers::process_event(), ParticleFlowReco::process_event(), RetowerCEMC::process_event(), CopyAndSubtractJets::process_event(), DetermineTowerBackground::process_event(), CaloTriggerSim::process_event(), caloTowerEmbed::process_event(), TruthCaloTree::process_event(), and MyJetAnalysis::process_event().
virtual RawTowerDefs::keytype RawTowerGeom::get_id () const inline virtual
Reimplemented in RawTowerGeomv4, RawTowerGeomv1, RawTowerGeomv3, and RawTowerGeomv2.
Definition at line 21 of file RawTowerGeom.h.
View newest version in sPHENIX GitHub at line 21 of file RawTowerGeom.h
References PHOOL_VIRTUAL_WARN.
Referenced by RawTowerGeomContainerv1::add_tower_geometry(), and RawClusterBuilderTemplate::InitRun().
virtual double RawTowerGeom::get_phi () const inline virtual
Reimplemented in RawTowerGeomv3, RawTowerGeomv2, RawTowerGeomv4, and RawTowerGeomv1.
Definition at line 153 of file RawTowerGeom.h.
View newest version in sPHENIX GitHub at line 153 of file RawTowerGeom.h
References PHOOL_VIRTUAL_WARN.
Referenced by DISKinematicsReco::AddGlobalCalorimeterInformation(), LeptoquarksReco::AddGlobalEventInformation(), LeptoquarksReco::AddJetStructureInformation(), TreeMaker::CopyAndMakeJets(), RawClusterBuilderTopo::export_clusters(), EpFinderEval::fill_tree(), Calib::fill_tree(), CaloEvaluator::fillOutputNtuples(), HCalJetPhiShift::FillTTree(), IsolatedTrackAnalysis::getSimTowers(), IsolatedTrackAnalysis::getTowers(), RawClusterBuilderTopo::process_event(), ClusterIso::process_event(), SubtractTowers::process_event(), ParticleFlowReco::process_event(), CopyAndSubtractJets::process_event(), RetowerCEMC::process_event(), caloTowerEmbed::process_event(), CaloTriggerSim::process_event(), DetermineTowerBackground::process_event(), TruthCaloTree::process_event(), MyJetAnalysis::process_event(), sPHAnalysis::process_event_notracking(), and sPHAnalysis_calo::process_event_test().
virtual double RawTowerGeom::get_roty () const inline virtual
Reimplemented in RawTowerGeomv4.
Definition at line 170 of file RawTowerGeom.h.
View newest version in sPHENIX GitHub at line 170 of file RawTowerGeom.h
References PHOOL_VIRTUAL_WARN.
virtual double RawTowerGeom::get_rotz () const inline virtual
Reimplemented in RawTowerGeomv4.
Definition at line 175 of file RawTowerGeom.h.
View newest version in sPHENIX GitHub at line 175 of file RawTowerGeom.h
References PHOOL_VIRTUAL_WARN.
virtual int RawTowerGeom::get_row () const inline virtual
Reimplemented in RawTowerGeomv4, RawTowerGeomv3, RawTowerGeomv1, and RawTowerGeomv2.
Definition at line 51 of file RawTowerGeom.h.
View newest version in sPHENIX GitHub at line 51 of file RawTowerGeom.h
References PHOOL_VIRTUAL_WARN.
Referenced by EpFinderEval::fill_tree(), and Calib::fill_tree().
virtual double RawTowerGeom::get_size_x () const inline virtual
Reimplemented in RawTowerGeomv3, and RawTowerGeomv2.
Definition at line 111 of file RawTowerGeom.h.
View newest version in sPHENIX GitHub at line 111 of file RawTowerGeom.h
References PHOOL_VIRTUAL_WARN.
Referenced by TrackProjectionTools::getE33Forward(), and RawTowerGeomv4::identify().
virtual double RawTowerGeom::get_size_y () const inline virtual
Reimplemented in RawTowerGeomv3, and RawTowerGeomv2.
Definition at line 117 of file RawTowerGeom.h.
View newest version in sPHENIX GitHub at line 117 of file RawTowerGeom.h
References PHOOL_VIRTUAL_WARN.
Referenced by TrackProjectionTools::getE33Forward(), and RawTowerGeomv4::identify().
virtual double RawTowerGeom::get_size_z () const inline virtual
Reimplemented in RawTowerGeomv3, and RawTowerGeomv2.
Definition at line 123 of file RawTowerGeom.h.
View newest version in sPHENIX GitHub at line 123 of file RawTowerGeom.h
References PHOOL_VIRTUAL_WARN.
Referenced by RawTowerGeomv4::identify(), and RawClusterBuilderTemplate::InitRun().
virtual double RawTowerGeom::get_theta () const inline virtual
Reimplemented in RawTowerGeomv3, RawTowerGeomv4, and RawTowerGeomv1.
Definition at line 147 of file RawTowerGeom.h.
View newest version in sPHENIX GitHub at line 147 of file RawTowerGeom.h
References PHOOL_VIRTUAL_WARN.
virtual int RawTowerGeom::get_tower_type () const inline virtual
Reimplemented in RawTowerGeomv3, and RawTowerGeomv4.
Definition at line 164 of file RawTowerGeom.h.
View newest version in sPHENIX GitHub at line 164 of file RawTowerGeom.h
References PHOOL_VIRTUAL_WARN.
Referenced by RawTowerCalibration::process_event().
virtual double RawTowerGeom::get_volume () const inline virtual
Reimplemented in RawTowerGeomv3, and RawTowerGeomv2.
Definition at line 129 of file RawTowerGeom.h.
View newest version in sPHENIX GitHub at line 129 of file RawTowerGeom.h
References PHOOL_VIRTUAL_WARN.
void RawTowerGeom::identify (std::ostream & os = std::cout) const override virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from PHObject.
Reimplemented in RawTowerGeomv4, RawTowerGeomv1, RawTowerGeomv3, and RawTowerGeomv2.
Definition at line 5 of file RawTowerGeom.cc.
View newest version in sPHENIX GitHub at line 5 of file RawTowerGeom.cc
Referenced by RawTowerGeomContainerv1::add_tower_geometry().
virtual void RawTowerGeom::set_center_x (double) inline virtual
Reimplemented in RawTowerGeomv3, RawTowerGeomv4, RawTowerGeomv1, and RawTowerGeomv2.
Definition at line 57 of file RawTowerGeom.h.
View newest version in sPHENIX GitHub at line 57 of file RawTowerGeom.h
References PHOOL_VIRTUAL_WARN.
Referenced by CaloGeomMapping::CreateGeomNode(), and RawTowerBuilderByHitIndex::ReadGeometryFromTable().
virtual void RawTowerGeom::set_center_y (double) inline virtual
Reimplemented in RawTowerGeomv3, RawTowerGeomv4, RawTowerGeomv1, and RawTowerGeomv2.
Definition at line 63 of file RawTowerGeom.h.
View newest version in sPHENIX GitHub at line 63 of file RawTowerGeom.h
References PHOOL_VIRTUAL_WARN.
Referenced by CaloGeomMapping::CreateGeomNode(), and RawTowerBuilderByHitIndex::ReadGeometryFromTable().
virtual void RawTowerGeom::set_center_z (double) inline virtual
Reimplemented in RawTowerGeomv3, RawTowerGeomv4, RawTowerGeomv1, and RawTowerGeomv2.
Definition at line 69 of file RawTowerGeom.h.
View newest version in sPHENIX GitHub at line 69 of file RawTowerGeom.h
References PHOOL_VIRTUAL_WARN.
Referenced by CaloGeomMapping::CreateGeomNode(), and RawTowerBuilderByHitIndex::ReadGeometryFromTable().
virtual void RawTowerGeom::set_id (RawTowerDefs::keytype) inline virtual
Reimplemented in RawTowerGeomv4, RawTowerGeomv1, RawTowerGeomv3, and RawTowerGeomv2.
Definition at line 19 of file RawTowerGeom.h.
View newest version in sPHENIX GitHub at line 19 of file RawTowerGeom.h
References PHOOL_VIRTUAL_WARN.
virtual void RawTowerGeom::set_roty (double) inline virtual
Reimplemented in RawTowerGeomv4.
Definition at line 181 of file RawTowerGeom.h.
View newest version in sPHENIX GitHub at line 181 of file RawTowerGeom.h
References PHOOL_VIRTUAL_WARN.
virtual void RawTowerGeom::set_rotz (double) inline virtual
Reimplemented in RawTowerGeomv4.
Definition at line 186 of file RawTowerGeom.h.
View newest version in sPHENIX GitHub at line 186 of file RawTowerGeom.h
References PHOOL_VIRTUAL_WARN.
virtual void RawTowerGeom::set_size_x (double) inline virtual
Reimplemented in RawTowerGeomv3, and RawTowerGeomv2.
Definition at line 75 of file RawTowerGeom.h.
View newest version in sPHENIX GitHub at line 75 of file RawTowerGeom.h
References PHOOL_VIRTUAL_WARN.
Referenced by RawTowerBuilderByHitIndex::ReadGeometryFromTable().
virtual void RawTowerGeom::set_size_y (double) inline virtual
Reimplemented in RawTowerGeomv3, and RawTowerGeomv2.
Definition at line 81 of file RawTowerGeom.h.
View newest version in sPHENIX GitHub at line 81 of file RawTowerGeom.h
References PHOOL_VIRTUAL_WARN.
Referenced by RawTowerBuilderByHitIndex::ReadGeometryFromTable().
virtual void RawTowerGeom::set_size_z (double) inline virtual
Reimplemented in RawTowerGeomv3, and RawTowerGeomv2.
Definition at line 87 of file RawTowerGeom.h.
View newest version in sPHENIX GitHub at line 87 of file RawTowerGeom.h
References PHOOL_VIRTUAL_WARN.
Referenced by RawTowerBuilderByHitIndex::ReadGeometryFromTable().
virtual void RawTowerGeom::set_tower_type (int) inline virtual
Reimplemented in RawTowerGeomv3, and RawTowerGeomv4.
Definition at line 159 of file RawTowerGeom.h.
View newest version in sPHENIX GitHub at line 159 of file RawTowerGeom.h
References PHOOL_VIRTUAL_WARN.
Referenced by RawTowerBuilderByHitIndex::ReadGeometryFromTable().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/CaloBase/RawTowerGeom.h
coresoftware/blob/master/offline/packages/CaloBase/RawTowerGeom.cc