Analysis Software: pythia6/blob/master/pythiaeRHIC/erhic/pythia_radgen_extras.f File Reference
pythia_radgen_extras.f File Reference
Functions/Subroutines
subroutine mkf2 (DQ2, DX, A, Z, DF2, DF1)
subroutine mkr (DQ2, DX, DR)
subroutine r1990 (DQ2, DX, DR, DELTAR)
subroutine r1998 (DQ2, DX, DR, DELTAR)
DOUBLE PRECISION function dr1998 (DX, DQ2)
subroutine mkasym (dQ2, dX, A, Z, dA1, dA2)
double precision function fdilut (dQ2, dx, A)
double precision function f2allm (x, q2)
subroutine f2pyth (x, q2, f1, f2, z)
Function/Subroutine Documentation
DOUBLE PRECISION function dr1998 (double precision DX, double precision DQ2)
Definition at line 240 of file pythia_radgen_extras.f.
View newest version in sPHENIX GitHub at line 240 of file pythia_radgen_extras.f
Referenced by r1998().
double precision function f2allm (x, q2)
Definition at line 317 of file pythia_radgen_extras.f.
View newest version in sPHENIX GitHub at line 317 of file pythia_radgen_extras.f
References s, Acts::InternalSpacePoint< SpacePoint >::sp(), sHelix::w(), x, and z.
Referenced by mkf2().
subroutine f2pyth (double precision x, double precision q2, double precision f1, double precision f2, integer z)
Definition at line 400 of file pythia_radgen_extras.f.
View newest version in sPHENIX GitHub at line 400 of file pythia_radgen_extras.f
References alpha, eps, eta, f2(), i, mint, msti, mstp, Jetscape::JetScapeParticleBase::nu(), pari, parp, pi, pyint1, pypars, pypdfu(), r, vint, x, and z.
Referenced by mkf2().
double precision function fdilut (double precision dQ2, double precision dx, integer A)
Definition at line 273 of file pythia_radgen_extras.f.
View newest version in sPHENIX GitHub at line 273 of file pythia_radgen_extras.f
References dz.
Referenced by strf().
subroutine mkasym (double precision dQ2, double precision dX, integer A, integer Z, double precision dA1, double precision dA2)
Definition at line 257 of file pythia_radgen_extras.f.
View newest version in sPHENIX GitHub at line 257 of file pythia_radgen_extras.f
Referenced by strf().
subroutine mkf2 (double precision DQ2, double precision DX, integer A, integer Z, double precision DF2, double precision DF1)
Definition at line 6 of file pythia_radgen_extras.f.
View newest version in sPHENIX GitHub at line 6 of file pythia_radgen_extras.f
References f2allm(), f2pyth(), mkr(), pypdfu(), and z.
Referenced by pygaga(), and strf().
subroutine mkr (double precision DQ2, double precision DX, double precision DR)
Definition at line 99 of file pythia_radgen_extras.f.
View newest version in sPHENIX GitHub at line 99 of file pythia_radgen_extras.f
References r1990(), and r1998().
Referenced by mkf2(), and strf().
subroutine r1990 (double precision DQ2, double precision DX, double precision DR, double precision DELTAR)
Definition at line 128 of file pythia_radgen_extras.f.
View newest version in sPHENIX GitHub at line 128 of file pythia_radgen_extras.f
References Acts::Logger::log(), and r.
Referenced by mkr().
subroutine r1998 (double precision DQ2, double precision DX, double precision DR, double precision DELTAR)
Definition at line 183 of file pythia_radgen_extras.f.
View newest version in sPHENIX GitHub at line 183 of file pythia_radgen_extras.f
References c, dr1998(), and Acts::Logger::log().
Referenced by mkr().