Analysis Software: Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly > Class Template Reference
Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly > Class Template Reference
#include <acts/blob/sPHENIX/Core/include/Acts/EventData/MultiTrajectory.hpp>
Public Types
using Parameters = typename TrackStateTraits< M, ReadOnly >::Parameters
using Covariance = typename TrackStateTraits< M, ReadOnly >::Covariance
using ConstParameters = typename TrackStateTraits< M, true >::Parameters
using ConstCovariance = typename TrackStateTraits< M, true >::Covariance
template<size_t N>
using Measurement = typename TrackStateTraits< N, ReadOnly >::Measurement
template<size_t N>
using MeasurementCovariance = typename TrackStateTraits< N, ReadOnly >::MeasurementCovariance
template<size_t N>
using ConstMeasurement = typename TrackStateTraits< N, true >::Measurement
template<size_t N>
using ConstMeasurementCovariance = typename TrackStateTraits< N, true >::MeasurementCovariance
using IndexType = TrackIndexType
using Projector = typename TrackStateTraits< M, ReadOnly >::Projector
using EffectiveProjector = Eigen::Matrix< typename Projector::Scalar, Eigen::Dynamic, Eigen::Dynamic, TrackStateTraits< M, ReadOnly >::ProjectorFlags, M, eBoundSize >
using Trajectory = trajectory_t
Public Member Functions
TrackStateProxy (const TrackStateProxy< Trajectory, M, false > &other)
template<bool RO = ReadOnly, typename = std::enable_if_t<!RO>>
void shareFrom (TrackStatePropMask shareSource, TrackStatePropMask shareTarget)
template<bool RO = ReadOnly, bool ReadOnlyOther, typename = std::enable_if_t<!RO>>
void shareFrom (const TrackStateProxy< Trajectory, M, ReadOnlyOther > &other, TrackStatePropMask component)
template<bool RO = ReadOnly, bool ReadOnlyOther, typename = std::enable_if_t<!RO>>
void shareFrom (const TrackStateProxy< Trajectory, M, ReadOnlyOther > &other, TrackStatePropMask shareSource, TrackStatePropMask shareTarget)
template<ACTS_CONCEPT(TrackStateProxyConcept) track_state_proxy_t, bool RO = ReadOnly, typename = std::enable_if_t<!RO>>
void copyFrom (const track_state_proxy_t &other, TrackStatePropMask mask=TrackStatePropMask::All, bool onlyAllocated=true)
template<bool RO = ReadOnly, typename = std::enable_if_t<!RO>>
void unset (TrackStatePropMask target)
const Surface & referenceSurface () const
bool hasReferenceSurface () const
template<bool RO = ReadOnly, typename = std::enable_if_t<!RO>>
void setReferenceSurface (std::shared_ptr< const Surface > srf)
template<HashedString key>
constexpr bool has () const
constexpr bool has (HashedString key) const
constexpr bool has (std::string_view key) const
template<typename T , HashedString key, bool RO = ReadOnly, typename = std::enable_if_t<!RO>>
constexpr T & component ()
template<typename T , bool RO = ReadOnly, typename = std::enable_if_t<!RO>>
constexpr T & component (HashedString key)
template<typename T , bool RO = ReadOnly, typename = std::enable_if_t<!RO>>
constexpr T & component (std::string_view key)
template<typename T , HashedString key>
constexpr const T & component () const
template<typename T >
constexpr const T & component (HashedString key) const
template<typename T >
constexpr const T & component (std::string_view key) const
ConstParameters parameters () const
ConstCovariance covariance () const
ConstParameters predicted () const
template<bool RO = ReadOnly, typename = std::enable_if_t<!RO>>
Parameters predicted ()
ConstCovariance predictedCovariance () const
template<bool RO = ReadOnly, typename = std::enable_if_t<!RO>>
Covariance predictedCovariance ()
bool hasPredicted () const
ConstParameters filtered () const
template<bool RO = ReadOnly, typename = std::enable_if_t<!RO>>
Parameters filtered ()
ConstCovariance filteredCovariance () const
template<bool RO = ReadOnly, typename = std::enable_if_t<!RO>>
Covariance filteredCovariance ()
bool hasFiltered () const
ConstParameters smoothed () const
template<bool RO = ReadOnly, typename = std::enable_if_t<!RO>>
Parameters smoothed ()
ConstCovariance smoothedCovariance () const
template<bool RO = ReadOnly, typename = std::enable_if_t<!RO>>
Covariance smoothedCovariance ()
bool hasSmoothed () const
ConstCovariance jacobian () const
template<bool RO = ReadOnly, typename = std::enable_if_t<!RO>>
Covariance jacobian ()
bool hasJacobian () const
Projector projector () const
bool hasProjector () const
EffectiveProjector effectiveProjector () const
template<typename Derived , bool RO = ReadOnly, typename = std::enable_if_t<!RO>>
void setProjector (const Eigen::MatrixBase< Derived > &projector)
ProjectorBitset projectorBitset () const
template<bool RO = ReadOnly, typename = std::enable_if_t<!RO>>
void setProjectorBitset (ProjectorBitset proj)
SourceLink getUncalibratedSourceLink () const
template<bool RO = ReadOnly, typename = std::enable_if_t<!RO>>
void setUncalibratedSourceLink (SourceLink sourceLink)
bool hasUncalibratedSourceLink () const
bool hasCalibrated () const
template<size_t measdim>
ConstMeasurement< measdim > calibrated () const
template<size_t measdim, bool RO = ReadOnly, typename = std::enable_if_t<!RO>>
Measurement< measdim > calibrated ()
template<size_t measdim>
ConstMeasurementCovariance
< measdim > calibratedCovariance () const
template<size_t measdim, bool RO = ReadOnly, typename = std::enable_if_t<!RO>>
MeasurementCovariance< measdim > calibratedCovariance ()
template<bool RO = ReadOnly, typename = std::enable_if_t<!RO>>
auto effectiveCalibrated ()
auto effectiveCalibrated () const
template<bool RO = ReadOnly, typename = std::enable_if_t<!RO>>
auto effectiveCalibratedCovariance ()
auto effectiveCalibratedCovariance () const
IndexType calibratedSize () const
template<size_t kMeasurementSize, bool RO = ReadOnly, typename = std::enable_if_t<!RO>>
void setCalibrated (const Acts::Measurement< BoundIndices, kMeasurementSize > &meas)
void allocateCalibrated (size_t measdim)
template<bool RO = ReadOnly, typename = std::enable_if_t<!RO>>
double & chi2 ()
double chi2 () const
template<bool RO = ReadOnly, typename = std::enable_if_t<!RO>>
double & pathLength ()
double pathLength () const
template<bool RO = ReadOnly, typename = std::enable_if_t<!RO>>
TrackStateType typeFlags ()
ConstTrackStateType typeFlags () const
template<bool RO = ReadOnly, typename = std::enable_if_t<!RO>>
MultiTrajectory< Trajectory > & trajectory ()
const MultiTrajectory
< Trajectory > & trajectory () const
Public Attributes
m_istate
Static Public Attributes
static constexpr IndexType kInvalid = kTrackIndexInvalid
Private Member Functions
TrackStateProxy (ConstIf< MultiTrajectory< Trajectory >, ReadOnly > &trajectory, IndexType istate)
Private Attributes
TransitiveConstPointer
< ConstIf< MultiTrajectory
< Trajectory >, ReadOnly > > m_traj
IndexType m_istate
Friends
class Acts::MultiTrajectory< Trajectory >
class TrackStateProxy< Trajectory, M, true >
class TrackStateProxy< Trajectory, M, false >
Detailed Description
template<typename trajectory_t, size_t M, bool ReadOnly = true>
class Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >
Proxy object to access a single point on the trajectory.
Template Parameters
SourceLink Type to link back to an original measurement
M Maximum number of measurement dimensions
ReadOnly true for read-only access to underlying storage
Definition at line 137 of file MultiTrajectory.hpp.
View newest version in sPHENIX GitHub at line 137 of file MultiTrajectory.hpp
Member Typedef Documentation
template<typename trajectory_t, size_t M, bool ReadOnly = true> using Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::ConstCovariance = typename TrackStateTraits<M, true>::Covariance
Definition at line 142 of file MultiTrajectory.hpp.
View newest version in sPHENIX GitHub at line 142 of file MultiTrajectory.hpp
template<typename trajectory_t, size_t M, bool ReadOnly = true> template<size_t N> using Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::ConstMeasurement = typename TrackStateTraits<N, true>::Measurement
Definition at line 150 of file MultiTrajectory.hpp.
View newest version in sPHENIX GitHub at line 150 of file MultiTrajectory.hpp
template<typename trajectory_t, size_t M, bool ReadOnly = true> template<size_t N> using Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::ConstMeasurementCovariance = typename TrackStateTraits<N, true>::MeasurementCovariance
Definition at line 153 of file MultiTrajectory.hpp.
View newest version in sPHENIX GitHub at line 153 of file MultiTrajectory.hpp
template<typename trajectory_t, size_t M, bool ReadOnly = true> using Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::ConstParameters = typename TrackStateTraits<M, true>::Parameters
Definition at line 141 of file MultiTrajectory.hpp.
View newest version in sPHENIX GitHub at line 141 of file MultiTrajectory.hpp
template<typename trajectory_t, size_t M, bool ReadOnly = true> using Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::Covariance = typename TrackStateTraits<M, ReadOnly>::Covariance
Definition at line 140 of file MultiTrajectory.hpp.
View newest version in sPHENIX GitHub at line 140 of file MultiTrajectory.hpp
template<typename trajectory_t, size_t M, bool ReadOnly = true> using Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::EffectiveProjector = Eigen::Matrix<typename Projector::Scalar, Eigen::Dynamic, Eigen::Dynamic, TrackStateTraits<M, ReadOnly>::ProjectorFlags, M, eBoundSize>
Definition at line 166 of file MultiTrajectory.hpp.
View newest version in sPHENIX GitHub at line 166 of file MultiTrajectory.hpp
template<typename trajectory_t, size_t M, bool ReadOnly = true> using Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::IndexType = TrackIndexType
Definition at line 155 of file MultiTrajectory.hpp.
View newest version in sPHENIX GitHub at line 155 of file MultiTrajectory.hpp
template<typename trajectory_t, size_t M, bool ReadOnly = true> template<size_t N> using Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::Measurement = typename TrackStateTraits<N, ReadOnly>::Measurement
Definition at line 145 of file MultiTrajectory.hpp.
View newest version in sPHENIX GitHub at line 145 of file MultiTrajectory.hpp
template<typename trajectory_t, size_t M, bool ReadOnly = true> template<size_t N> using Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::MeasurementCovariance = typename TrackStateTraits<N, ReadOnly>::MeasurementCovariance
Definition at line 148 of file MultiTrajectory.hpp.
View newest version in sPHENIX GitHub at line 148 of file MultiTrajectory.hpp
template<typename trajectory_t, size_t M, bool ReadOnly = true> using Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::Parameters = typename TrackStateTraits<M, ReadOnly>::Parameters
Definition at line 139 of file MultiTrajectory.hpp.
View newest version in sPHENIX GitHub at line 139 of file MultiTrajectory.hpp
template<typename trajectory_t, size_t M, bool ReadOnly = true> using Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::Projector = typename TrackStateTraits<M, ReadOnly>::Projector
Definition at line 162 of file MultiTrajectory.hpp.
View newest version in sPHENIX GitHub at line 162 of file MultiTrajectory.hpp
template<typename trajectory_t, size_t M, bool ReadOnly = true> using Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::Trajectory = trajectory_t
Definition at line 168 of file MultiTrajectory.hpp.
View newest version in sPHENIX GitHub at line 168 of file MultiTrajectory.hpp
Constructor & Destructor Documentation
template<typename trajectory_t, size_t M, bool ReadOnly = true> Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::TrackStateProxy (const TrackStateProxy< Trajectory, M, false > & other) inline
Definition at line 172 of file MultiTrajectory.hpp.
View newest version in sPHENIX GitHub at line 172 of file MultiTrajectory.hpp
template<typename trajectory_t, size_t M, bool ReadOnly = true> Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::TrackStateProxy (ConstIf< MultiTrajectory< Trajectory >, ReadOnly > & trajectory, IndexType istate) private
Member Function Documentation
template<typename trajectory_t, size_t M, bool ReadOnly = true> void Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::allocateCalibrated (size_t measdim) inline
Definition at line 901 of file MultiTrajectory.hpp.
View newest version in sPHENIX GitHub at line 901 of file MultiTrajectory.hpp
References Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::m_istate, and Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::m_traj.
Referenced by Calibrator::calibrate(), ActsExamples::RefittingCalibrator::calibrate(), ActsExamples::PassThroughCalibrator::calibrate(), Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::copyFrom(), and Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::setCalibrated().
template<typename trajectory_t, size_t M, bool ReadOnly = true> template<size_t measdim> ConstMeasurement<measdim> Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::calibrated () const inline
Full calibrated measurement vector. Might contain additional zeroed dimensions.
Returns
The measurement vector
Note
Const version
Definition at line 762 of file MultiTrajectory.hpp.
View newest version in sPHENIX GitHub at line 762 of file MultiTrajectory.hpp
References assert, Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::has(), Acts::hashString(), Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::m_istate, and Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::m_traj.
template<typename trajectory_t, size_t M, bool ReadOnly = true> template<size_t measdim, bool RO = ReadOnly, typename = std::enable_if_t<!RO>> Measurement<measdim> Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::calibrated () inline
Full calibrated measurement vector. Might contain additional zeroed dimensions.
Returns
The measurement vector
Note
Mutable version
Definition at line 773 of file MultiTrajectory.hpp.
View newest version in sPHENIX GitHub at line 773 of file MultiTrajectory.hpp
References assert, Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::has(), Acts::hashString(), Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::m_istate, and Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::m_traj.
template<typename trajectory_t, size_t M, bool ReadOnly = true> template<size_t measdim> ConstMeasurementCovariance<measdim> Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::calibratedCovariance () const inline
Full calibrated measurement covariance matrix. The effective covariance is located in the top left corner, everything else is zeroed.
Returns
The measurement covariance matrix
Note
Const version
Definition at line 783 of file MultiTrajectory.hpp.
View newest version in sPHENIX GitHub at line 783 of file MultiTrajectory.hpp
References assert, Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::has(), Acts::hashString(), Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::m_istate, and Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::m_traj.
template<typename trajectory_t, size_t M, bool ReadOnly = true> template<size_t measdim, bool RO = ReadOnly, typename = std::enable_if_t<!RO>> MeasurementCovariance<measdim> Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::calibratedCovariance () inline
Full calibrated measurement covariance matrix. The effective covariance is located in the top left corner, everything else is zeroed.
Returns
The measurement covariance matrix
Note
Mutable version
Definition at line 794 of file MultiTrajectory.hpp.
View newest version in sPHENIX GitHub at line 794 of file MultiTrajectory.hpp
References assert, Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::has(), Acts::hashString(), Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::m_istate, and Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::m_traj.
template<typename trajectory_t, size_t M, bool ReadOnly = true> IndexType Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::calibratedSize () const inline
Return the (dynamic) number of dimensions stored for this measurement.
Note
The underlying storage is overallocated to MeasurementSizeMax regardless of this value
Returns
The number of dimensions
Definition at line 869 of file MultiTrajectory.hpp.
View newest version in sPHENIX GitHub at line 869 of file MultiTrajectory.hpp
References Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::m_istate, and Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::m_traj.
Referenced by Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::effectiveCalibrated(), Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::effectiveCalibratedCovariance(), Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::effectiveProjector(), and ResidualOutlierFinder::operator()().
template<typename trajectory_t, size_t M, bool ReadOnly = true> template<bool RO = ReadOnly, typename = std::enable_if_t<!RO>> double& Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::chi2 () inline
Getter/setter for chi2 value associated with the track state This overload returns a mutable reference, which allows setting a new value directly into the backing store.
Note
this overload is only enabled in case the proxy is not read-only
Returns
Mutable reference to the chi2 value
Definition at line 911 of file MultiTrajectory.hpp.
View newest version in sPHENIX GitHub at line 911 of file MultiTrajectory.hpp
References Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::component(), double(), and Acts::hashString().
Referenced by Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::copyFrom().
template<typename trajectory_t, size_t M, bool ReadOnly = true> double Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::chi2 () const inline
Getter for the chi2 value associated with the track state. This overload returns a copy of the chi2 value, and thus does not allow modification of the value in the backing storage.
Returns
the chi2 value of the track state
Definition at line 919 of file MultiTrajectory.hpp.
View newest version in sPHENIX GitHub at line 919 of file MultiTrajectory.hpp
References Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::component(), double(), and Acts::hashString().
template<typename trajectory_t, size_t M, bool ReadOnly = true> template<typename T , HashedString key, bool RO = ReadOnly, typename = std::enable_if_t<!RO>> constexpr T& Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::component () inline
Retrieve a mutable reference to a component
Template Parameters
T The type of the component to access
key String key for the component to access
Returns
Mutable reference to the component given by key
Definition at line 456 of file MultiTrajectory.hpp.
View newest version in sPHENIX GitHub at line 456 of file MultiTrajectory.hpp
References Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::m_istate, and Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::m_traj.
Referenced by Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::chi2(), Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::filtered(), Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::filteredCovariance(), Acts::detail_lt::TrackStateRange< reverse, trajectory_t, M, ReadOnly >::Iterator::operator++(), Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::pathLength(), Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::predicted(), Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::predictedCovariance(), Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::projectorBitset(), Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::setProjector(), Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::setProjectorBitset(), Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::smoothed(), Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::smoothedCovariance(), and Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::typeFlags().
template<typename trajectory_t, size_t M, bool ReadOnly = true> template<typename T , bool RO = ReadOnly, typename = std::enable_if_t<!RO>> constexpr T& Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::component (HashedString key) inline
Retrieve a mutable reference to a component
Template Parameters
T The type of the component to access
Parameters
key String key for the component to access
Returns
Mutable reference to the component given by key
Definition at line 465 of file MultiTrajectory.hpp.
View newest version in sPHENIX GitHub at line 465 of file MultiTrajectory.hpp
References Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::m_istate, and Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::m_traj.
template<typename trajectory_t, size_t M, bool ReadOnly = true> template<typename T , bool RO = ReadOnly, typename = std::enable_if_t<!RO>> constexpr T& Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::component (std::string_view key) inline
Retrieve a mutable reference to a component
Template Parameters
T The type of the component to access
Parameters
key String key for the component to access
Note
This might hash the key at runtime instead of compile-time
Returns
Mutable reference to the component given by key
Definition at line 475 of file MultiTrajectory.hpp.
View newest version in sPHENIX GitHub at line 475 of file MultiTrajectory.hpp
References Acts::hashString(), Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::m_istate, and Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::m_traj.
template<typename trajectory_t, size_t M, bool ReadOnly = true> template<typename T , HashedString key> constexpr const T& Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::component () const inline
Retrieve a const reference to a component
Template Parameters
T The type of the component to access
key String key for the component to access
Returns
Const reference to the component given by key
Definition at line 484 of file MultiTrajectory.hpp.
View newest version in sPHENIX GitHub at line 484 of file MultiTrajectory.hpp
References Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::m_istate, and Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::m_traj.
template<typename trajectory_t, size_t M, bool ReadOnly = true> template<typename T > constexpr const T& Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::component (HashedString key) const inline
Retrieve a const reference to a component
Template Parameters
T The type of the component to access
Parameters
key String key for the component to access
Returns
Const reference to the component given by key
Definition at line 493 of file MultiTrajectory.hpp.
View newest version in sPHENIX GitHub at line 493 of file MultiTrajectory.hpp
References Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::m_istate, and Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::m_traj.
template<typename trajectory_t, size_t M, bool ReadOnly = true> template<typename T > constexpr const T& Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::component (std::string_view key) const inline
Retrieve a const reference to a component
Template Parameters
T The type of the component to access
Parameters
key String key for the component to access
Note
This might hash the key at runtime instead of compile-time
Returns
Const reference to the component given by key
Definition at line 503 of file MultiTrajectory.hpp.
View newest version in sPHENIX GitHub at line 503 of file MultiTrajectory.hpp
References Acts::hashString(), Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::m_istate, and Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::m_traj.
template<typename trajectory_t, size_t M, bool ReadOnly = true> template<ACTS_CONCEPT(TrackStateProxyConcept) track_state_proxy_t, bool RO = ReadOnly, typename = std::enable_if_t<!RO>> void Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::copyFrom (const track_state_proxy_t & other, TrackStatePropMask mask = TrackStatePropMask::All, bool onlyAllocated = true) inline
Copy the contents of another track state proxy into this one
Parameters
other The other track state to copy from
mask An optional mask to determine what to copy from
onlyAllocated Whether to only copy allocated components
Note
If the this track state proxy does not have compatible allocations with the source track state proxy, and onlyAllocated is false, an exception is thrown.
The mask parameter will not cause a copy of components that are not allocated in the source track state proxy.
Definition at line 270 of file MultiTrajectory.hpp.
View newest version in sPHENIX GitHub at line 270 of file MultiTrajectory.hpp
References ACTS_CHECK_BIT, Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::allocateCalibrated(), Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::chi2(), upload::dest, Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::filtered(), Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::filteredCovariance(), Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::has(), Acts::hashString(), Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::jacobian(), mask, N, Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::pathLength(), Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::predicted(), Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::predictedCovariance(), Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::setProjectorBitset(), Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::setReferenceSurface(), Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::setUncalibratedSourceLink(), Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::smoothed(), Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::smoothedCovariance(), Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::typeFlags(), value, and Acts::visit_measurement().
template<typename D , size_t M, bool ReadOnly> auto Acts::detail_lt::TrackStateProxy< D, M, ReadOnly >::covariance () const inline
Track parameters covariance matrix. This tries to be somewhat smart and return the first parameters that are set in this order: predicted -> filtered -> smoothed
Returns
one of predicted, filtered or smoothed covariances
Definition at line 62 of file MultiTrajectory.ipp.
View newest version in sPHENIX GitHub at line 62 of file MultiTrajectory.ipp
template<typename trajectory_t, size_t M, bool ReadOnly = true> template<bool RO = ReadOnly, typename = std::enable_if_t<!RO>> auto Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::effectiveCalibrated () inline
Dynamic measurement vector with only the valid dimensions.
Returns
The effective calibrated measurement vector
Note
Mutable version
Definition at line 803 of file MultiTrajectory.hpp.
View newest version in sPHENIX GitHub at line 803 of file MultiTrajectory.hpp
References Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::calibratedSize(), configureMap::data, N, value, and Acts::visit_measurement().
template<typename trajectory_t, size_t M, bool ReadOnly = true> auto Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::effectiveCalibrated () const inline
Dynamic measurement vector with only the valid dimensions.
Returns
The effective calibrated measurement vector
Note
Const version
Definition at line 819 of file MultiTrajectory.hpp.
View newest version in sPHENIX GitHub at line 819 of file MultiTrajectory.hpp
References Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::calibratedSize(), configureMap::data, N, value, and Acts::visit_measurement().
template<typename trajectory_t, size_t M, bool ReadOnly = true> template<bool RO = ReadOnly, typename = std::enable_if_t<!RO>> auto Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::effectiveCalibratedCovariance () inline
Dynamic measurement covariance matrix with only the valid dimensions.
Returns
The effective calibrated covariance matrix
Note
Mutable version
Definition at line 836 of file MultiTrajectory.hpp.
View newest version in sPHENIX GitHub at line 836 of file MultiTrajectory.hpp
References Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::calibratedSize(), configureMap::data, N, value, and Acts::visit_measurement().
template<typename trajectory_t, size_t M, bool ReadOnly = true> auto Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::effectiveCalibratedCovariance () const inline
Dynamic measurement covariance matrix with only the valid dimensions.
Returns
The effective calibrated covariance matrix
Note
Const version
Definition at line 852 of file MultiTrajectory.hpp.
View newest version in sPHENIX GitHub at line 852 of file MultiTrajectory.hpp
References Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::calibratedSize(), configureMap::data, N, value, and Acts::visit_measurement().
template<typename trajectory_t, size_t M, bool ReadOnly = true> EffectiveProjector Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::effectiveProjector () const inline
Returns the projector (measurement mapping function) for this track state. It is derived from the uncalibrated measurement
Note
This function returns the effective projector. This means it is of dimension NxM, where N is the actual dimension of the measurement.
Returns
The effective projector
Definition at line 678 of file MultiTrajectory.hpp.
View newest version in sPHENIX GitHub at line 678 of file MultiTrajectory.hpp
References Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::calibratedSize(), and Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::projector().
template<typename trajectory_t, size_t M, bool ReadOnly = true> ConstParameters Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::filtered () const inline
Filtered track parameters vector
Returns
The filtered parameters
Note
Const version
Definition at line 557 of file MultiTrajectory.hpp.
View newest version in sPHENIX GitHub at line 557 of file MultiTrajectory.hpp
References assert, Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::component(), Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::has(), Acts::hashString(), and Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::m_traj.
Referenced by Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::copyFrom().
template<typename trajectory_t, size_t M, bool ReadOnly = true> template<bool RO = ReadOnly, typename = std::enable_if_t<!RO>> Parameters Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::filtered () inline
Filtered track parameters vector
Returns
The filtered parameters
Note
Mutable version
Definition at line 567 of file MultiTrajectory.hpp.
View newest version in sPHENIX GitHub at line 567 of file MultiTrajectory.hpp
References assert, Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::component(), Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::has(), Acts::hashString(), and Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::m_traj.
template<typename trajectory_t, size_t M, bool ReadOnly = true> ConstCovariance Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::filteredCovariance () const inline
Filtered track parameters covariance matrix
Returns
The filtered parameters covariance
Note
Const version
Definition at line 576 of file MultiTrajectory.hpp.
View newest version in sPHENIX GitHub at line 576 of file MultiTrajectory.hpp
References assert, Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::component(), Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::has(), Acts::hashString(), and Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::m_traj.
Referenced by Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::copyFrom().
template<typename trajectory_t, size_t M, bool ReadOnly = true> template<bool RO = ReadOnly, typename = std::enable_if_t<!RO>> Covariance Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::filteredCovariance () inline
Filtered track parameters covariance matrix
Returns
The filtered parameters covariance
Note
Mutable version
Definition at line 586 of file MultiTrajectory.hpp.
View newest version in sPHENIX GitHub at line 586 of file MultiTrajectory.hpp
References assert, Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::component(), Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::has(), Acts::hashString(), and Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::m_traj.
template<typename D , size_t M, bool ReadOnly> auto Acts::detail_lt::TrackStateProxy< D, M, ReadOnly >::getUncalibratedSourceLink () const inline
Uncalibrated measurement in the form of a source link. Const version
Returns
The uncalibrated measurement source link
Definition at line 81 of file MultiTrajectory.ipp.
View newest version in sPHENIX GitHub at line 81 of file MultiTrajectory.ipp
References assert, and Acts::hashString().
template<typename trajectory_t, size_t M, bool ReadOnly = true> template<HashedString key> constexpr bool Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::has () const inline
Check if a component is set
Template Parameters
key Hashed string key to check for
Returns
true if the component exists, false if not
Definition at line 431 of file MultiTrajectory.hpp.
View newest version in sPHENIX GitHub at line 431 of file MultiTrajectory.hpp
References Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::m_istate, and Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::m_traj.
Referenced by Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::calibrated(), Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::calibratedCovariance(), Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::copyFrom(), Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::filtered(), Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::filteredCovariance(), Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::has(), Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::hasCalibrated(), Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::hasFiltered(), Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::hasJacobian(), Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::hasPredicted(), Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::hasProjector(), Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::hasSmoothed(), Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::hasUncalibratedSourceLink(), Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::jacobian(), Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::predicted(), Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::predictedCovariance(), Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::projectorBitset(), Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::setProjector(), Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::setProjectorBitset(), Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::smoothed(), and Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::smoothedCovariance().
template<typename trajectory_t, size_t M, bool ReadOnly = true> constexpr bool Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::has (HashedString key) const inline
Check if a component is set
Parameters
key Hashed string key to check for
Returns
true if the component exists, false if not
Definition at line 438 of file MultiTrajectory.hpp.
View newest version in sPHENIX GitHub at line 438 of file MultiTrajectory.hpp
References Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::m_istate, and Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::m_traj.
template<typename trajectory_t, size_t M, bool ReadOnly = true> constexpr bool Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::has (std::string_view key) const inline
Check if a component is set
Parameters
key String key to check for
Note
This might hash the key at runtime instead of compile-time
Returns
true if the component exists, false if not
Definition at line 446 of file MultiTrajectory.hpp.
View newest version in sPHENIX GitHub at line 446 of file MultiTrajectory.hpp
References Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::has(), and Acts::hashString().
template<typename trajectory_t, size_t M, bool ReadOnly = true> bool Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::hasCalibrated () const inline
Check if the point has an associated calibrated measurement.
Returns
Whether it is set
Definition at line 755 of file MultiTrajectory.hpp.
View newest version in sPHENIX GitHub at line 755 of file MultiTrajectory.hpp
References Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::has(), and Acts::hashString().
Referenced by ResidualOutlierFinder::operator()(), and Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::setCalibrated().
template<typename trajectory_t, size_t M, bool ReadOnly = true> bool Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::hasFiltered () const inline
Return whether filtered parameters+covariance is set
Returns
Whether it is set
Definition at line 594 of file MultiTrajectory.hpp.
View newest version in sPHENIX GitHub at line 594 of file MultiTrajectory.hpp
References Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::has(), and Acts::hashString().
template<typename trajectory_t, size_t M, bool ReadOnly = true> bool Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::hasJacobian () const inline
Returns whether a jacobian is set for this trackstate
Returns
Whether it is set
Definition at line 657 of file MultiTrajectory.hpp.
View newest version in sPHENIX GitHub at line 657 of file MultiTrajectory.hpp
References Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::has(), and Acts::hashString().
template<typename trajectory_t, size_t M, bool ReadOnly = true> bool Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::hasPredicted () const inline
Check whether the predicted parameters+covariance is set
Returns
Whether it is set or not
Definition at line 552 of file MultiTrajectory.hpp.
View newest version in sPHENIX GitHub at line 552 of file MultiTrajectory.hpp
References Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::has(), and Acts::hashString().
Referenced by ResidualOutlierFinder::operator()().
template<typename trajectory_t, size_t M, bool ReadOnly = true> bool Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::hasProjector () const inline
Returns whether a projector is set
Returns
Whether it is set
Definition at line 670 of file MultiTrajectory.hpp.
View newest version in sPHENIX GitHub at line 670 of file MultiTrajectory.hpp
References Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::has(), and Acts::hashString().
template<typename trajectory_t, size_t M, bool ReadOnly = true> bool Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::hasReferenceSurface () const inline
Returns if the track state has a non nullptr surface associated
Returns
whether a surface exists or not
Definition at line 411 of file MultiTrajectory.hpp.
View newest version in sPHENIX GitHub at line 411 of file MultiTrajectory.hpp
References Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::m_istate, and Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::m_traj.
Referenced by Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::referenceSurface().
template<typename trajectory_t, size_t M, bool ReadOnly = true> bool Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::hasSmoothed () const inline
Return whether smoothed parameters+covariance is set
Returns
Whether it is set
Definition at line 636 of file MultiTrajectory.hpp.
View newest version in sPHENIX GitHub at line 636 of file MultiTrajectory.hpp
References Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::has(), and Acts::hashString().
template<typename trajectory_t, size_t M, bool ReadOnly = true> bool Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::hasUncalibratedSourceLink () const inline
Check if the point has an associated uncalibrated measurement.
Returns
Whether it is set
Definition at line 749 of file MultiTrajectory.hpp.
View newest version in sPHENIX GitHub at line 749 of file MultiTrajectory.hpp
References Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::has(), and Acts::hashString().
template<typename trajectory_t, size_t M, bool ReadOnly = true> ConstCovariance Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::jacobian () const inline
Returns the jacobian from the previous trackstate to this one
Returns
The jacobian matrix
Note
Const version
Definition at line 641 of file MultiTrajectory.hpp.
View newest version in sPHENIX GitHub at line 641 of file MultiTrajectory.hpp
References assert, Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::has(), Acts::hashString(), Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::m_istate, and Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::m_traj.
Referenced by Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::copyFrom().
template<typename trajectory_t, size_t M, bool ReadOnly = true> template<bool RO = ReadOnly, typename = std::enable_if_t<!RO>> Covariance Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::jacobian () inline
Returns the jacobian from the previous trackstate to this one
Returns
The jacobian matrix
Note
Mutable version
Definition at line 650 of file MultiTrajectory.hpp.
View newest version in sPHENIX GitHub at line 650 of file MultiTrajectory.hpp
References assert, Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::has(), Acts::hashString(), Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::m_istate, and Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::m_traj.
template<typename D , size_t M, bool ReadOnly> auto Acts::detail_lt::TrackStateProxy< D, M, ReadOnly >::parameters () const inline
Track parameters vector. This tries to be somewhat smart and return the first parameters that are set in this order: predicted -> filtered -> smoothed
Returns
one of predicted, filtered or smoothed parameters
Definition at line 50 of file MultiTrajectory.ipp.
View newest version in sPHENIX GitHub at line 50 of file MultiTrajectory.ipp
template<typename trajectory_t, size_t M, bool ReadOnly = true> template<bool RO = ReadOnly, typename = std::enable_if_t<!RO>> double& Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::pathLength () inline
Getter for the path length associated with the track state. This overloaded is only enabled if not read-only, and returns a mutable reference.
Returns
Mutable reference to the pathlength.
Definition at line 926 of file MultiTrajectory.hpp.
View newest version in sPHENIX GitHub at line 926 of file MultiTrajectory.hpp
References Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::component(), double(), and Acts::hashString().
Referenced by Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::copyFrom().
template<typename trajectory_t, size_t M, bool ReadOnly = true> double Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::pathLength () const inline
Getter for the path length. Returns a copy of the path length value.
Returns
The path length of this track state
Definition at line 932 of file MultiTrajectory.hpp.
View newest version in sPHENIX GitHub at line 932 of file MultiTrajectory.hpp
References Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::component(), double(), and Acts::hashString().
template<typename trajectory_t, size_t M, bool ReadOnly = true> ConstParameters Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::predicted () const inline
Predicted track parameters vector
Returns
The predicted parameters
Definition at line 522 of file MultiTrajectory.hpp.
View newest version in sPHENIX GitHub at line 522 of file MultiTrajectory.hpp
References assert, Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::component(), Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::has(), Acts::hashString(), and Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::m_traj.
Referenced by BOOST_AUTO_TEST_CASE(), Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::copyFrom(), and ResidualOutlierFinder::operator()().
template<typename trajectory_t, size_t M, bool ReadOnly = true> template<bool RO = ReadOnly, typename = std::enable_if_t<!RO>> Parameters Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::predicted () inline
Definition at line 529 of file MultiTrajectory.hpp.
View newest version in sPHENIX GitHub at line 529 of file MultiTrajectory.hpp
References assert, Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::component(), Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::has(), Acts::hashString(), and Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::m_traj.
template<typename trajectory_t, size_t M, bool ReadOnly = true> ConstCovariance Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::predictedCovariance () const inline
Predicted track parameters covariance matrix.
Returns
The predicted track parameter covariance
Definition at line 537 of file MultiTrajectory.hpp.
View newest version in sPHENIX GitHub at line 537 of file MultiTrajectory.hpp
References assert, Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::component(), Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::has(), Acts::hashString(), and Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::m_traj.
Referenced by Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::copyFrom(), and ResidualOutlierFinder::operator()().
template<typename trajectory_t, size_t M, bool ReadOnly = true> template<bool RO = ReadOnly, typename = std::enable_if_t<!RO>> Covariance Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::predictedCovariance () inline
Definition at line 544 of file MultiTrajectory.hpp.
View newest version in sPHENIX GitHub at line 544 of file MultiTrajectory.hpp
References assert, Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::component(), Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::has(), Acts::hashString(), and Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::m_traj.
template<typename D , size_t M, bool ReadOnly> auto Acts::detail_lt::TrackStateProxy< D, M, ReadOnly >::projector () const inline
Returns the projector (measurement mapping function) for this track state. It is derived from the uncalibrated measurement
Note
This function returns the overallocated projector. This means it is of dimension MxM, where M is the maximum number of measurement dimensions. The NxM submatrix, where N is the actual dimension of the measurement, is located in the top left corner, everything else is zero.
Returns
The overallocated projector
Definition at line 74 of file MultiTrajectory.ipp.
View newest version in sPHENIX GitHub at line 74 of file MultiTrajectory.ipp
References assert, and Acts::hashString().
Referenced by Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::effectiveProjector(), and ResidualOutlierFinder::operator()().
template<typename trajectory_t, size_t M, bool ReadOnly = true> ProjectorBitset Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::projectorBitset () const inline
Get the projector bitset, a compressed form of a projection matrix
Note
This is mainly to copy explicitly a projector from one state to another. Use the projector or effectiveProjector method if you want to access the matrix.
Returns
The projector bitset
Definition at line 720 of file MultiTrajectory.hpp.
View newest version in sPHENIX GitHub at line 720 of file MultiTrajectory.hpp
References assert, Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::component(), Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::has(), and Acts::hashString().
Referenced by Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::setProjector().
template<typename trajectory_t, size_t M, bool ReadOnly = true> const Surface& Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::referenceSurface () const inline
Reference surface.
Returns
the reference surface
Definition at line 403 of file MultiTrajectory.hpp.
View newest version in sPHENIX GitHub at line 403 of file MultiTrajectory.hpp
References assert, Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::hasReferenceSurface(), Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::m_istate, and Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::m_traj.
Referenced by ActsExamples::RefittingCalibrator::RefittingSourceLink::geometryId(), and ResidualOutlierFinder::operator()().
template<typename trajectory_t, size_t M, bool ReadOnly = true> template<size_t kMeasurementSize, bool RO = ReadOnly, typename = std::enable_if_t<!RO>> void Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::setCalibrated (const Acts::Measurement< BoundIndices, kMeasurementSize > & meas) inline
Overwrite existing measurement data.
Template Parameters
kMeasurementSize Size of the calibrated measurement
Parameters
meas The measurement object to set
Note
This assumes this TrackState stores it's own calibrated measurement. If storage is shared with another TrackState, both will be overwritten!. Also assumes none of the calibrated components is invalid (i.e. unset) for this TrackState.
This does not set the reference surface.
Definition at line 883 of file MultiTrajectory.hpp.
View newest version in sPHENIX GitHub at line 883 of file MultiTrajectory.hpp
References Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::allocateCalibrated(), assert, Acts::Measurement< indices_t, kSize >::covariance(), Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::hasCalibrated(), Acts::Measurement< indices_t, kSize >::parameters(), Acts::Measurement< indices_t, kSize >::projector(), and Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::setProjector().
Referenced by Calibrator::calibrate(), and ActsExamples::PassThroughCalibrator::calibrate().
template<typename trajectory_t, size_t M, bool ReadOnly = true> template<typename Derived , bool RO = ReadOnly, typename = std::enable_if_t<!RO>> void Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::setProjector (const Eigen::MatrixBase< Derived > & projector) inline
Set the projector on this track state This will convert the projector to a more compact bitset representation and store it.
Parameters
projector The projector in the form of a dense matrix
Note
projector is assumed to only have 0s or 1s as components.
Definition at line 689 of file MultiTrajectory.hpp.
View newest version in sPHENIX GitHub at line 689 of file MultiTrajectory.hpp
References assert, Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::component(), Acts::eBoundSize, Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::has(), Acts::hashString(), Acts::matrixToBitset(), Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::projectorBitset(), and parse_cmake_options::rows.
Referenced by Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::setCalibrated().
template<typename trajectory_t, size_t M, bool ReadOnly = true> template<bool RO = ReadOnly, typename = std::enable_if_t<!RO>> void Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::setProjectorBitset (ProjectorBitset proj) inline
Set the projector bitset, a compressed form of a projection matrix
Parameters
proj The projector bitset
Note
This is mainly to copy explicitly a projector from one state to another. If you have a projection matrix, set it with setProjector.
Definition at line 731 of file MultiTrajectory.hpp.
View newest version in sPHENIX GitHub at line 731 of file MultiTrajectory.hpp
References assert, Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::component(), Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::has(), and Acts::hashString().
Referenced by ActsExamples::RefittingCalibrator::calibrate(), and Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::copyFrom().
template<typename trajectory_t, size_t M, bool ReadOnly = true> template<bool RO = ReadOnly, typename = std::enable_if_t<!RO>> void Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::setReferenceSurface (std::shared_ptr< const Surface > srf) inline
Set the reference surface to a given value
Parameters
srf Shared pointer to the surface to set
Note
This overload is only present in case ReadOnly is false.
Definition at line 422 of file MultiTrajectory.hpp.
View newest version in sPHENIX GitHub at line 422 of file MultiTrajectory.hpp
References Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::m_istate, Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::m_traj, and testing::internal::move().
Referenced by Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::copyFrom().
template<typename trajectory_t, size_t M, bool ReadOnly = true> template<bool RO = ReadOnly, typename = std::enable_if_t<!RO>> void Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::setUncalibratedSourceLink (SourceLink sourceLink) inline
Set an uncalibrated source link
Parameters
sourceLink The uncalibrated source link to set
Definition at line 743 of file MultiTrajectory.hpp.
View newest version in sPHENIX GitHub at line 743 of file MultiTrajectory.hpp
References Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::m_istate, Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::m_traj, and testing::internal::move().
Referenced by Calibrator::calibrate(), ActsExamples::RefittingCalibrator::calibrate(), ActsExamples::PassThroughCalibrator::calibrate(), and Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::copyFrom().
template<typename trajectory_t, size_t M, bool ReadOnly = true> template<bool RO = ReadOnly, typename = std::enable_if_t<!RO>> void Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::shareFrom (TrackStatePropMask shareSource, TrackStatePropMask shareTarget) inline
Share a shareable component within this track state
Parameters
shareSource Which component to share from
shareTarget Which component to share as. This should be different from as shareSource, e.g. predicted can be shared as filtered.
Note
Shareable components are predicted, filtered, smoothed, calibrated, jacobian, or projector. See TrackStatePropMask.
Definition at line 219 of file MultiTrajectory.hpp.
View newest version in sPHENIX GitHub at line 219 of file MultiTrajectory.hpp
Referenced by Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::shareFrom().
template<typename trajectory_t, size_t M, bool ReadOnly = true> template<bool RO = ReadOnly, bool ReadOnlyOther, typename = std::enable_if_t<!RO>> void Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::shareFrom (const TrackStateProxy< Trajectory, M, ReadOnlyOther > & other, TrackStatePropMask component) inline
Share a shareable component from another track state.
Parameters
other Track state proxy to share component from
component Which component to share.
Note
Shareable components are predicted, filtered, smoothed, calibrated, jacobian, or projector. See TrackStatePropMask.
The track states both need to be stored in the same MultiTrajectory instance
Definition at line 233 of file MultiTrajectory.hpp.
View newest version in sPHENIX GitHub at line 233 of file MultiTrajectory.hpp
References Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::shareFrom().
template<typename trajectory_t, size_t M, bool ReadOnly = true> template<bool RO = ReadOnly, bool ReadOnlyOther, typename = std::enable_if_t<!RO>> void Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::shareFrom (const TrackStateProxy< Trajectory, M, ReadOnlyOther > & other, TrackStatePropMask shareSource, TrackStatePropMask shareTarget) inline
Share a shareable component from another track state
Parameters
shareSource Which component to share from
shareTarget Which component to share as. This can be be different from as shareSource, e.g. predicted can be shared as filtered.
Note
Shareable components are predicted, filtered, smoothed, calibrated, jacobian, or projector. See TrackStatePropMask.
Definition at line 246 of file MultiTrajectory.hpp.
View newest version in sPHENIX GitHub at line 246 of file MultiTrajectory.hpp
References ACTS_CHECK_BIT, assert, Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::m_istate, and Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::m_traj.
template<typename trajectory_t, size_t M, bool ReadOnly = true> ConstParameters Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::smoothed () const inline
Smoothed track parameters vector
Returns
The smoothed parameters
Note
Const version
Definition at line 599 of file MultiTrajectory.hpp.
View newest version in sPHENIX GitHub at line 599 of file MultiTrajectory.hpp
References assert, Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::component(), Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::has(), Acts::hashString(), and Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::m_traj.
Referenced by Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::copyFrom().
template<typename trajectory_t, size_t M, bool ReadOnly = true> template<bool RO = ReadOnly, typename = std::enable_if_t<!RO>> Parameters Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::smoothed () inline
Smoothed track parameters vector
Returns
The smoothed parameters
Note
Mutable version
Definition at line 609 of file MultiTrajectory.hpp.
View newest version in sPHENIX GitHub at line 609 of file MultiTrajectory.hpp
References assert, Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::component(), Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::has(), Acts::hashString(), and Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::m_traj.
template<typename trajectory_t, size_t M, bool ReadOnly = true> ConstCovariance Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::smoothedCovariance () const inline
Smoothed track parameters covariance matrix
Returns
the parameter covariance matrix
Note
Const version
Definition at line 618 of file MultiTrajectory.hpp.
View newest version in sPHENIX GitHub at line 618 of file MultiTrajectory.hpp
References assert, Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::component(), Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::has(), Acts::hashString(), and Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::m_traj.
Referenced by Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::copyFrom().
template<typename trajectory_t, size_t M, bool ReadOnly = true> template<bool RO = ReadOnly, typename = std::enable_if_t<!RO>> Covariance Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::smoothedCovariance () inline
Smoothed track parameters covariance matrix
Returns
the parameter covariance matrix
Note
Mutable version
Definition at line 628 of file MultiTrajectory.hpp.
View newest version in sPHENIX GitHub at line 628 of file MultiTrajectory.hpp
References assert, Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::component(), Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::has(), Acts::hashString(), and Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::m_traj.
template<typename trajectory_t, size_t M, bool ReadOnly = true> template<bool RO = ReadOnly, typename = std::enable_if_t<!RO>> MultiTrajectory<Trajectory>& Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::trajectory () inline
Definition at line 954 of file MultiTrajectory.hpp.
View newest version in sPHENIX GitHub at line 954 of file MultiTrajectory.hpp
References Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::m_traj.
template<typename trajectory_t, size_t M, bool ReadOnly = true> const MultiTrajectory<Trajectory>& Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::trajectory () const inline
Definition at line 958 of file MultiTrajectory.hpp.
View newest version in sPHENIX GitHub at line 958 of file MultiTrajectory.hpp
References Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::m_traj.
template<typename trajectory_t, size_t M, bool ReadOnly = true> template<bool RO = ReadOnly, typename = std::enable_if_t<!RO>> TrackStateType Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::typeFlags () inline
Getter for the type flags associated with the track state. This overloaded is only enabled if not read-only, and returns a mutable reference.
Returns
reference to the type flags.
Definition at line 941 of file MultiTrajectory.hpp.
View newest version in sPHENIX GitHub at line 941 of file MultiTrajectory.hpp
References Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::component(), and Acts::hashString().
Referenced by Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::copyFrom().
template<typename trajectory_t, size_t M, bool ReadOnly = true> ConstTrackStateType Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::typeFlags () const inline
Getter for the type flags. Returns a copy of the type flags value.
Returns
The type flags of this track state
Definition at line 948 of file MultiTrajectory.hpp.
View newest version in sPHENIX GitHub at line 948 of file MultiTrajectory.hpp
References Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::component(), and Acts::hashString().
template<typename trajectory_t, size_t M, bool ReadOnly = true> template<bool RO = ReadOnly, typename = std::enable_if_t<!RO>> void Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::unset (TrackStatePropMask target) inline
Unset an optional track state component
Parameters
target The component to unset
Definition at line 397 of file MultiTrajectory.hpp.
View newest version in sPHENIX GitHub at line 397 of file MultiTrajectory.hpp
References Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::m_istate, and Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::m_traj.
Friends And Related Function Documentation
template<typename trajectory_t, size_t M, bool ReadOnly = true> friend class Acts::MultiTrajectory< Trajectory > friend
Definition at line 968 of file MultiTrajectory.hpp.
View newest version in sPHENIX GitHub at line 968 of file MultiTrajectory.hpp
template<typename trajectory_t, size_t M, bool ReadOnly = true> friend class TrackStateProxy< Trajectory, M, false > friend
Definition at line 970 of file MultiTrajectory.hpp.
View newest version in sPHENIX GitHub at line 970 of file MultiTrajectory.hpp
template<typename trajectory_t, size_t M, bool ReadOnly = true> friend class TrackStateProxy< Trajectory, M, true > friend
Definition at line 969 of file MultiTrajectory.hpp.
View newest version in sPHENIX GitHub at line 969 of file MultiTrajectory.hpp
Member Data Documentation
template<typename trajectory_t, size_t M, bool ReadOnly = true> constexpr IndexType Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::kInvalid = kTrackIndexInvalid static
Definition at line 156 of file MultiTrajectory.hpp.
View newest version in sPHENIX GitHub at line 156 of file MultiTrajectory.hpp
Referenced by Acts::MultiTrajectory< ConstPodioTrackStateContainer >::forwardTrackStateRange(), Acts::detail_lt::TrackStateRange< reverse, trajectory_t, M, ReadOnly >::Iterator::operator++(), and Acts::MultiTrajectory< ConstPodioTrackStateContainer >::reverseTrackStateRange().
template<typename trajectory_t, size_t M, bool ReadOnly = true> Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::m_istate
Definition at line 173 of file MultiTrajectory.hpp.
View newest version in sPHENIX GitHub at line 173 of file MultiTrajectory.hpp
Referenced by Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::allocateCalibrated(), Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::calibrated(), Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::calibratedCovariance(), Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::calibratedSize(), Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::component(), Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::has(), Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::hasReferenceSurface(), Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::jacobian(), Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::referenceSurface(), Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::setReferenceSurface(), Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::setUncalibratedSourceLink(), Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::shareFrom(), and Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::unset().
template<typename trajectory_t, size_t M, bool ReadOnly = true> IndexType Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::m_istate private
Definition at line 966 of file MultiTrajectory.hpp.
View newest version in sPHENIX GitHub at line 966 of file MultiTrajectory.hpp
template<typename trajectory_t, size_t M, bool ReadOnly = true> TransitiveConstPointer<ConstIf<MultiTrajectory<Trajectory>, ReadOnly> > Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::m_traj private
Definition at line 965 of file MultiTrajectory.hpp.
View newest version in sPHENIX GitHub at line 965 of file MultiTrajectory.hpp
Referenced by Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::allocateCalibrated(), Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::calibrated(), Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::calibratedCovariance(), Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::calibratedSize(), Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::component(), Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::filtered(), Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::filteredCovariance(), Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::has(), Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::hasReferenceSurface(), Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::jacobian(), Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::predicted(), Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::predictedCovariance(), Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::referenceSurface(), Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::setReferenceSurface(), Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::setUncalibratedSourceLink(), Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::shareFrom(), Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::smoothed(), Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::smoothedCovariance(), Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::trajectory(), and Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::unset().
The documentation for this class was generated from the following files:
acts/blob/sPHENIX/Core/include/Acts/EventData/MultiTrajectory.hpp
acts/blob/sPHENIX/Core/include/Acts/EventData/MultiTrajectory.ipp