Analysis Software: JetInput Class Reference
JetInput Class Reference
#include <coresoftware/blob/master/offline/packages/jetbase/JetInput.h>
Public Member Functions
virtual ~JetInput ()
virtual void identify (std::ostream &os=std::cout)
virtual Jet::SRC get_src ()
virtual std::vector< Jet * > get_input (PHCompositeNode *)
virtual int Verbosity () const
virtual void Verbosity (int i)
Protected Member Functions
JetInput ()
Private Attributes
int m_Verbosity
Detailed Description
Definition at line 11 of file JetInput.h.
View newest version in sPHENIX GitHub at line 11 of file JetInput.h
Constructor & Destructor Documentation
virtual JetInput::~JetInput () inline virtual
Definition at line 14 of file JetInput.h.
View newest version in sPHENIX GitHub at line 14 of file JetInput.h
JetInput::JetInput () inline protected
Definition at line 31 of file JetInput.h.
View newest version in sPHENIX GitHub at line 31 of file JetInput.h
Member Function Documentation
virtual std::vector<Jet*> JetInput::get_input (PHCompositeNode *) inline virtual
Reimplemented in TruthJetInput, ClusterJetInput, JetProbeInput, ParticleFlowJetInput, TowerJetInput, and TrackJetInput.
Definition at line 23 of file JetInput.h.
View newest version in sPHENIX GitHub at line 23 of file JetInput.h
virtual Jet::SRC JetInput::get_src () inline virtual
Reimplemented in TruthJetInput, ClusterJetInput, JetProbeInput, TowerJetInput, and TrackJetInput.
Definition at line 21 of file JetInput.h.
View newest version in sPHENIX GitHub at line 21 of file JetInput.h
References Jet::VOID.
virtual void JetInput::identify (std::ostream & os = std::cout) inline virtual
Reimplemented in ParticleFlowJetInput, TruthJetInput, ClusterJetInput, JetProbeInput, TowerJetInput, and TrackJetInput.
Definition at line 16 of file JetInput.h.
View newest version in sPHENIX GitHub at line 16 of file JetInput.h
References os.
virtual int JetInput::Verbosity () const inline virtual
Definition at line 27 of file JetInput.h.
View newest version in sPHENIX GitHub at line 27 of file JetInput.h
References m_Verbosity.
Referenced by TrackJetInput::get_input(), TowerJetInput::get_input(), JetProbeInput::get_input(), and TruthJetInput::get_input().
virtual void JetInput::Verbosity (int i) inline virtual
Definition at line 28 of file JetInput.h.
View newest version in sPHENIX GitHub at line 28 of file JetInput.h
References i, and m_Verbosity.
Member Data Documentation
int JetInput::m_Verbosity private
Definition at line 37 of file JetInput.h.
View newest version in sPHENIX GitHub at line 37 of file JetInput.h
Referenced by Verbosity().
The documentation for this class was generated from the following file:
coresoftware/blob/master/offline/packages/jetbase/JetInput.h