Analysis Software: ActsFatras::Geant4Decay Class Reference
ActsFatras::Geant4Decay Class Reference
Handle particle decays using the Geant4 decay models.
#include <acts/blob/sPHENIX/Fatras/Geant4/include/ActsFatras/Geant4/Geant4Decay.hpp>
Public Types
using Scalar = Particle::Scalar
Public Member Functions
Geant4Decay ()
Constructor.
template<typename generator_t >
Scalar generateProperTimeLimit (generator_t &generator, const Particle &particle) const
template<typename generator_t >
std::vector< Particle > run (generator_t &generator, Particle &particle) const
Private Member Functions
std::vector< Particle > decayParticle (const Particle &parent) const
Private Attributes
G4RunManager * m_g4RunManager
for dummy G4 initialization
PDGtoG4Converter m_pdgToG4Conv
Handle for converting a PDG ID into a Geant4 particle.
Detailed Description
Handle particle decays using the Geant4 decay models.
Definition at line 28 of file Geant4Decay.hpp.
View newest version in sPHENIX GitHub at line 28 of file Geant4Decay.hpp
Member Typedef Documentation
using ActsFatras::Geant4Decay::Scalar = Particle::Scalar
Definition at line 30 of file Geant4Decay.hpp.
View newest version in sPHENIX GitHub at line 30 of file Geant4Decay.hpp
Constructor & Destructor Documentation
ActsFatras::Geant4Decay::Geant4Decay ()
Constructor.
Definition at line 23 of file Geant4Decay.cpp.
View newest version in sPHENIX GitHub at line 23 of file Geant4Decay.cpp
Member Function Documentation
std::vector< ActsFatras::Particle > ActsFatras::Geant4Decay::decayParticle (const Particle & parent) const private
This function evaluates the decay products of a given particle
Parameters
[in] parent The decaying particle
Returns
Vector containing the decay products
Definition at line 26 of file Geant4Decay.cpp.
View newest version in sPHENIX GitHub at line 26 of file Geant4Decay.cpp
References channel(), Acts::eEnergy, Acts::eMom0, Acts::eMom1, Acts::eMom2, ActsFatras::Particle::fourMomentum(), ActsFatras::Particle::fourPosition(), Acts::UnitConstants::GeV, i, ActsFatras::Barcode::makeDescendant(), testing::internal::move(), ActsFatras::Particle::particleId(), pdg, ActsFatras::Particle::pdg(), ActsFatras::Particle::setPosition4(), and ActsFatras::Particle::setProcess().
Referenced by run().
template<typename generator_t > Particle::Scalar ActsFatras::Geant4Decay::generateProperTimeLimit (generator_t & generator, const Particle & particle) const
Generate the particle life time.
Template Parameters
generator_t Type of the random number generator
Parameters
[in,out] generator The random number generator
[in] particle The particle that gets a lifetime assigned
Returns
Proper time limit of the particle
Definition at line 70 of file Geant4Decay.hpp.
View newest version in sPHENIX GitHub at line 70 of file Geant4Decay.hpp
References Acts::eMuon, ActsFatras::PDGtoG4Converter::getParticleDefinition(), m_pdgToG4Conv, Acts::makeAbsolutePdgParticle(), Acts::UnitConstants::mm, ActsFatras::Particle::pdg(), physmon_simulation::s, and tau.
template<typename generator_t > std::vector< Particle > ActsFatras::Geant4Decay::run (generator_t & generator, Particle & particle) const
Decay the particle and create the decay products.
Template Parameters
generator_t Type of the random number generator
Parameters
[in,out] particle The particle that may decay
Returns
Vector containing decay products
Definition at line 97 of file Geant4Decay.hpp.
View newest version in sPHENIX GitHub at line 97 of file Geant4Decay.hpp
References decayParticle().
Member Data Documentation
G4RunManager* ActsFatras::Geant4Decay::m_g4RunManager mutable private
for dummy G4 initialization
Definition at line 63 of file Geant4Decay.hpp.
View newest version in sPHENIX GitHub at line 63 of file Geant4Decay.hpp
PDGtoG4Converter ActsFatras::Geant4Decay::m_pdgToG4Conv private
Handle for converting a PDG ID into a Geant4 particle.
Definition at line 66 of file Geant4Decay.hpp.
View newest version in sPHENIX GitHub at line 66 of file Geant4Decay.hpp
Referenced by generateProperTimeLimit().
The documentation for this class was generated from the following files:
acts/blob/sPHENIX/Fatras/Geant4/include/ActsFatras/Geant4/Geant4Decay.hpp
acts/blob/sPHENIX/Fatras/Geant4/src/Geant4Decay.cpp