Analysis Software: plot_DataSimComp Namespace Reference
plot_DataSimComp Namespace Reference
Functions
def Draw_1Dhist_datasimcomp
def Draw_1Dhist_datasimcomp_v2
def Draw_2Dhist_datasimcomp
Variables
tuple parser OptionParser(usage='usage: %prog ver [options -h]')
datahistdir opt.datahistdir
simhistdir opt.simhistdir
simlegtext opt.simlegtext
plotdir opt.plotdir
tuple hM_NClusLayer1_data GetHistogram("{}/hists_merged.root".format(datahistdir), 'hM_NClusLayer1')
tuple hM_NPrototkl_data GetHistogram("{}/hists_merged.root".format(datahistdir), 'hM_NPrototkl')
tuple hM_NRecotkl_Raw_data GetHistogram("{}/hists_merged.root".format(datahistdir), 'hM_NRecotkl_Raw')
tuple hM_dEta_reco_data GetHistogram("{}/hists_merged.root".format(datahistdir), 'hM_dEta_reco')
tuple hM_dEta_reco_altrange_data GetHistogram("{}/hists_merged.root".format(datahistdir), 'hM_dEta_reco_altrange')
tuple hM_dEta_reco_altrange_Nclusle4000_data GetHistogram("{}/hists_merged.root".format(datahistdir), 'hM_dEta_reco_altrange_Nclusle4000')
tuple hM_dEta_reco_altrange_Nclusgt4000_data GetHistogram("{}/hists_merged.root".format(datahistdir), 'hM_dEta_reco_altrange_Nclusgt4000')
tuple hM_dPhi_reco_data GetHistogram("{}/hists_merged.root".format(datahistdir), 'hM_dPhi_reco')
tuple hM_dPhi_reco_altrange_data GetHistogram("{}/hists_merged.root".format(datahistdir), 'hM_dPhi_reco_altrange')
tuple hM_dPhi_reco_altrange_Nclusle4000_data GetHistogram("{}/hists_merged.root".format(datahistdir), 'hM_dPhi_reco_altrange_Nclusle4000')
tuple hM_dPhi_reco_altrange_Nclusgt4000_data GetHistogram("{}/hists_merged.root".format(datahistdir), 'hM_dPhi_reco_altrange_Nclusgt4000')
tuple hM_dR_reco_data GetHistogram("{}/hists_merged.root".format(datahistdir), 'hM_dR_reco')
tuple hM_dR_reco_Nclusle4000_data GetHistogram("{}/hists_merged.root".format(datahistdir), 'hM_dR_reco_Nclusle4000')
tuple hM_dR_reco_Nclusgt4000_data GetHistogram("{}/hists_merged.root".format(datahistdir), 'hM_dR_reco_Nclusgt4000')
tuple hM_Eta_reco_data GetHistogram("{}/hists_merged.root".format(datahistdir), 'hM_Eta_reco')
tuple hM_Eta_reco_Nclusle4000_data GetHistogram("{}/hists_merged.root".format(datahistdir), 'hM_Eta_reco_Nclusle4000')
tuple hM_Eta_reco_Nclusgt4000_data GetHistogram("{}/hists_merged.root".format(datahistdir), 'hM_Eta_reco_Nclusgt4000')
tuple hM_Phi_reco_data GetHistogram("{}/hists_merged.root".format(datahistdir), 'hM_Phi_reco')
tuple hM_Phi_reco_Nclusle4000_data GetHistogram("{}/hists_merged.root".format(datahistdir), 'hM_Phi_reco_Nclusle4000')
tuple hM_Phi_reco_Nclusgt4000_data GetHistogram("{}/hists_merged.root".format(datahistdir), 'hM_Phi_reco_Nclusgt4000')
tuple hM_RecoPVz_data GetHistogram("{}/hists_merged.root".format(datahistdir), 'hM_RecoPVz')
tuple hM_RecoPVz_Nclusle4000_data GetHistogram("{}/hists_merged.root".format(datahistdir), 'hM_RecoPVz_Nclusle4000')
tuple hM_RecoPVz_Nclusgt4000_data GetHistogram("{}/hists_merged.root".format(datahistdir), 'hM_RecoPVz_Nclusgt4000')
tuple hM_clusphi_data GetHistogram("{}/hists_merged.root".format(datahistdir), 'hM_clusphi')
tuple hM_cluseta_data GetHistogram("{}/hists_merged.root".format(datahistdir), 'hM_cluseta')
tuple hM_clusphisize_data GetHistogram("{}/hists_merged.root".format(datahistdir), 'hM_clusphisize')
tuple hM_cluseta_clusphisize_data GetHistogram("{}/hists_merged.root".format(datahistdir), 'hM_cluseta_clusphisize')
tuple hM_clusphi_clusphisize_data GetHistogram("{}/hists_merged.root".format(datahistdir), 'hM_clusphi_clusphisize')
list l_hM_NClusLayer1_sim []
list l_hM_NPrototkl_sim []
list l_hM_NRecotkl_Raw_sim []
list l_hM_dEta_reco_sim []
list l_hM_dEta_reco_altrange_sim []
list l_hM_dPhi_reco_sim []
list l_hM_dPhi_reco_altrange_sim []
list l_hM_dR_reco_sim []
list l_hM_Eta_reco_sim []
list l_hM_Phi_reco_sim []
list l_hM_RecoPVz_sim []
list l_hM_clusphi_sim []
list l_hM_cluseta_sim []
list l_hM_clusphisize_sim []
list l_hM_cluseta_clusphisize_sim []
list l_hM_clusphi_clusphisize_sim []
Function Documentation
def plot_DataSimComp.Draw_1Dhist_datasimcomp (hdata, hsims, gpadmargin, norm, logy, ymaxscale, XaxisName, Ytitle_unit, prelim, simlegtex, outname)
Definition at line 17 of file plot_DataSimComp.py.
View newest version in sPHENIX GitHub at line 17 of file plot_DataSimComp.py
References plotUtil.colorset(), Acts.enumerate(), material_mapping_optimisation.format, if(), print(), and SetTitle().
def plot_DataSimComp.Draw_1Dhist_datasimcomp_v2 (hdata1, hdata2, hsim, gpadmargin, norm, logy, ymaxscale, XaxisName, Ytitle_unit, legtext, prelim, outname)
Definition at line 114 of file plot_DataSimComp.py.
View newest version in sPHENIX GitHub at line 114 of file plot_DataSimComp.py
References material_mapping_optimisation.format, if(), print(), and SetTitle().
def plot_DataSimComp.Draw_2Dhist_datasimcomp (hdata, hsim, logz, norm, rmargin, XaxisName, YaxisName, outname)
Definition at line 197 of file plot_DataSimComp.py.
View newest version in sPHENIX GitHub at line 197 of file plot_DataSimComp.py
References material_mapping_optimisation.format, if(), print(), and SetTitle().
Variable Documentation
plot_DataSimComp.datahistdir opt.datahistdir
Definition at line 255 of file plot_DataSimComp.py.
View newest version in sPHENIX GitHub at line 255 of file plot_DataSimComp.py
tuple plot_DataSimComp.hM_cluseta_clusphisize_data GetHistogram("{}/hists_merged.root".format(datahistdir), 'hM_cluseta_clusphisize')
Definition at line 301 of file plot_DataSimComp.py.
View newest version in sPHENIX GitHub at line 301 of file plot_DataSimComp.py
tuple plot_DataSimComp.hM_cluseta_data GetHistogram("{}/hists_merged.root".format(datahistdir), 'hM_cluseta')
Definition at line 299 of file plot_DataSimComp.py.
View newest version in sPHENIX GitHub at line 299 of file plot_DataSimComp.py
tuple plot_DataSimComp.hM_clusphi_clusphisize_data GetHistogram("{}/hists_merged.root".format(datahistdir), 'hM_clusphi_clusphisize')
Definition at line 302 of file plot_DataSimComp.py.
View newest version in sPHENIX GitHub at line 302 of file plot_DataSimComp.py
tuple plot_DataSimComp.hM_clusphi_data GetHistogram("{}/hists_merged.root".format(datahistdir), 'hM_clusphi')
Definition at line 298 of file plot_DataSimComp.py.
View newest version in sPHENIX GitHub at line 298 of file plot_DataSimComp.py
tuple plot_DataSimComp.hM_clusphisize_data GetHistogram("{}/hists_merged.root".format(datahistdir), 'hM_clusphisize')
Definition at line 300 of file plot_DataSimComp.py.
View newest version in sPHENIX GitHub at line 300 of file plot_DataSimComp.py
tuple plot_DataSimComp.hM_dEta_reco_altrange_data GetHistogram("{}/hists_merged.root".format(datahistdir), 'hM_dEta_reco_altrange')
Definition at line 279 of file plot_DataSimComp.py.
View newest version in sPHENIX GitHub at line 279 of file plot_DataSimComp.py
tuple plot_DataSimComp.hM_dEta_reco_altrange_Nclusgt4000_data GetHistogram("{}/hists_merged.root".format(datahistdir), 'hM_dEta_reco_altrange_Nclusgt4000')
Definition at line 281 of file plot_DataSimComp.py.
View newest version in sPHENIX GitHub at line 281 of file plot_DataSimComp.py
tuple plot_DataSimComp.hM_dEta_reco_altrange_Nclusle4000_data GetHistogram("{}/hists_merged.root".format(datahistdir), 'hM_dEta_reco_altrange_Nclusle4000')
Definition at line 280 of file plot_DataSimComp.py.
View newest version in sPHENIX GitHub at line 280 of file plot_DataSimComp.py
tuple plot_DataSimComp.hM_dEta_reco_data GetHistogram("{}/hists_merged.root".format(datahistdir), 'hM_dEta_reco')
Definition at line 278 of file plot_DataSimComp.py.
View newest version in sPHENIX GitHub at line 278 of file plot_DataSimComp.py
tuple plot_DataSimComp.hM_dPhi_reco_altrange_data GetHistogram("{}/hists_merged.root".format(datahistdir), 'hM_dPhi_reco_altrange')
Definition at line 283 of file plot_DataSimComp.py.
View newest version in sPHENIX GitHub at line 283 of file plot_DataSimComp.py
tuple plot_DataSimComp.hM_dPhi_reco_altrange_Nclusgt4000_data GetHistogram("{}/hists_merged.root".format(datahistdir), 'hM_dPhi_reco_altrange_Nclusgt4000')
Definition at line 285 of file plot_DataSimComp.py.
View newest version in sPHENIX GitHub at line 285 of file plot_DataSimComp.py
tuple plot_DataSimComp.hM_dPhi_reco_altrange_Nclusle4000_data GetHistogram("{}/hists_merged.root".format(datahistdir), 'hM_dPhi_reco_altrange_Nclusle4000')
Definition at line 284 of file plot_DataSimComp.py.
View newest version in sPHENIX GitHub at line 284 of file plot_DataSimComp.py
tuple plot_DataSimComp.hM_dPhi_reco_data GetHistogram("{}/hists_merged.root".format(datahistdir), 'hM_dPhi_reco')
Definition at line 282 of file plot_DataSimComp.py.
View newest version in sPHENIX GitHub at line 282 of file plot_DataSimComp.py
tuple plot_DataSimComp.hM_dR_reco_data GetHistogram("{}/hists_merged.root".format(datahistdir), 'hM_dR_reco')
Definition at line 286 of file plot_DataSimComp.py.
View newest version in sPHENIX GitHub at line 286 of file plot_DataSimComp.py
tuple plot_DataSimComp.hM_dR_reco_Nclusgt4000_data GetHistogram("{}/hists_merged.root".format(datahistdir), 'hM_dR_reco_Nclusgt4000')
Definition at line 288 of file plot_DataSimComp.py.
View newest version in sPHENIX GitHub at line 288 of file plot_DataSimComp.py
tuple plot_DataSimComp.hM_dR_reco_Nclusle4000_data GetHistogram("{}/hists_merged.root".format(datahistdir), 'hM_dR_reco_Nclusle4000')
Definition at line 287 of file plot_DataSimComp.py.
View newest version in sPHENIX GitHub at line 287 of file plot_DataSimComp.py
tuple plot_DataSimComp.hM_Eta_reco_data GetHistogram("{}/hists_merged.root".format(datahistdir), 'hM_Eta_reco')
Definition at line 289 of file plot_DataSimComp.py.
View newest version in sPHENIX GitHub at line 289 of file plot_DataSimComp.py
tuple plot_DataSimComp.hM_Eta_reco_Nclusgt4000_data GetHistogram("{}/hists_merged.root".format(datahistdir), 'hM_Eta_reco_Nclusgt4000')
Definition at line 291 of file plot_DataSimComp.py.
View newest version in sPHENIX GitHub at line 291 of file plot_DataSimComp.py
tuple plot_DataSimComp.hM_Eta_reco_Nclusle4000_data GetHistogram("{}/hists_merged.root".format(datahistdir), 'hM_Eta_reco_Nclusle4000')
Definition at line 290 of file plot_DataSimComp.py.
View newest version in sPHENIX GitHub at line 290 of file plot_DataSimComp.py
tuple plot_DataSimComp.hM_NClusLayer1_data GetHistogram("{}/hists_merged.root".format(datahistdir), 'hM_NClusLayer1')
Definition at line 275 of file plot_DataSimComp.py.
View newest version in sPHENIX GitHub at line 275 of file plot_DataSimComp.py
tuple plot_DataSimComp.hM_NPrototkl_data GetHistogram("{}/hists_merged.root".format(datahistdir), 'hM_NPrototkl')
Definition at line 276 of file plot_DataSimComp.py.
View newest version in sPHENIX GitHub at line 276 of file plot_DataSimComp.py
tuple plot_DataSimComp.hM_NRecotkl_Raw_data GetHistogram("{}/hists_merged.root".format(datahistdir), 'hM_NRecotkl_Raw')
Definition at line 277 of file plot_DataSimComp.py.
View newest version in sPHENIX GitHub at line 277 of file plot_DataSimComp.py
tuple plot_DataSimComp.hM_Phi_reco_data GetHistogram("{}/hists_merged.root".format(datahistdir), 'hM_Phi_reco')
Definition at line 292 of file plot_DataSimComp.py.
View newest version in sPHENIX GitHub at line 292 of file plot_DataSimComp.py
tuple plot_DataSimComp.hM_Phi_reco_Nclusgt4000_data GetHistogram("{}/hists_merged.root".format(datahistdir), 'hM_Phi_reco_Nclusgt4000')
Definition at line 294 of file plot_DataSimComp.py.
View newest version in sPHENIX GitHub at line 294 of file plot_DataSimComp.py
tuple plot_DataSimComp.hM_Phi_reco_Nclusle4000_data GetHistogram("{}/hists_merged.root".format(datahistdir), 'hM_Phi_reco_Nclusle4000')
Definition at line 293 of file plot_DataSimComp.py.
View newest version in sPHENIX GitHub at line 293 of file plot_DataSimComp.py
tuple plot_DataSimComp.hM_RecoPVz_data GetHistogram("{}/hists_merged.root".format(datahistdir), 'hM_RecoPVz')
Definition at line 295 of file plot_DataSimComp.py.
View newest version in sPHENIX GitHub at line 295 of file plot_DataSimComp.py
tuple plot_DataSimComp.hM_RecoPVz_Nclusgt4000_data GetHistogram("{}/hists_merged.root".format(datahistdir), 'hM_RecoPVz_Nclusgt4000')
Definition at line 297 of file plot_DataSimComp.py.
View newest version in sPHENIX GitHub at line 297 of file plot_DataSimComp.py
tuple plot_DataSimComp.hM_RecoPVz_Nclusle4000_data GetHistogram("{}/hists_merged.root".format(datahistdir), 'hM_RecoPVz_Nclusle4000')
Definition at line 296 of file plot_DataSimComp.py.
View newest version in sPHENIX GitHub at line 296 of file plot_DataSimComp.py
list plot_DataSimComp.l_hM_cluseta_clusphisize_sim []
Definition at line 318 of file plot_DataSimComp.py.
View newest version in sPHENIX GitHub at line 318 of file plot_DataSimComp.py
list plot_DataSimComp.l_hM_cluseta_sim []
Definition at line 316 of file plot_DataSimComp.py.
View newest version in sPHENIX GitHub at line 316 of file plot_DataSimComp.py
list plot_DataSimComp.l_hM_clusphi_clusphisize_sim []
Definition at line 319 of file plot_DataSimComp.py.
View newest version in sPHENIX GitHub at line 319 of file plot_DataSimComp.py
list plot_DataSimComp.l_hM_clusphi_sim []
Definition at line 315 of file plot_DataSimComp.py.
View newest version in sPHENIX GitHub at line 315 of file plot_DataSimComp.py
list plot_DataSimComp.l_hM_clusphisize_sim []
Definition at line 317 of file plot_DataSimComp.py.
View newest version in sPHENIX GitHub at line 317 of file plot_DataSimComp.py
list plot_DataSimComp.l_hM_dEta_reco_altrange_sim []
Definition at line 308 of file plot_DataSimComp.py.
View newest version in sPHENIX GitHub at line 308 of file plot_DataSimComp.py
list plot_DataSimComp.l_hM_dEta_reco_sim []
Definition at line 307 of file plot_DataSimComp.py.
View newest version in sPHENIX GitHub at line 307 of file plot_DataSimComp.py
list plot_DataSimComp.l_hM_dPhi_reco_altrange_sim []
Definition at line 310 of file plot_DataSimComp.py.
View newest version in sPHENIX GitHub at line 310 of file plot_DataSimComp.py
list plot_DataSimComp.l_hM_dPhi_reco_sim []
Definition at line 309 of file plot_DataSimComp.py.
View newest version in sPHENIX GitHub at line 309 of file plot_DataSimComp.py
list plot_DataSimComp.l_hM_dR_reco_sim []
Definition at line 311 of file plot_DataSimComp.py.
View newest version in sPHENIX GitHub at line 311 of file plot_DataSimComp.py
list plot_DataSimComp.l_hM_Eta_reco_sim []
Definition at line 312 of file plot_DataSimComp.py.
View newest version in sPHENIX GitHub at line 312 of file plot_DataSimComp.py
list plot_DataSimComp.l_hM_NClusLayer1_sim []
Definition at line 304 of file plot_DataSimComp.py.
View newest version in sPHENIX GitHub at line 304 of file plot_DataSimComp.py
list plot_DataSimComp.l_hM_NPrototkl_sim []
Definition at line 305 of file plot_DataSimComp.py.
View newest version in sPHENIX GitHub at line 305 of file plot_DataSimComp.py
list plot_DataSimComp.l_hM_NRecotkl_Raw_sim []
Definition at line 306 of file plot_DataSimComp.py.
View newest version in sPHENIX GitHub at line 306 of file plot_DataSimComp.py
list plot_DataSimComp.l_hM_Phi_reco_sim []
Definition at line 313 of file plot_DataSimComp.py.
View newest version in sPHENIX GitHub at line 313 of file plot_DataSimComp.py
list plot_DataSimComp.l_hM_RecoPVz_sim []
Definition at line 314 of file plot_DataSimComp.py.
View newest version in sPHENIX GitHub at line 314 of file plot_DataSimComp.py
tuple plot_DataSimComp.parser OptionParser(usage='usage: %prog ver [options -h]')
Definition at line 245 of file plot_DataSimComp.py.
View newest version in sPHENIX GitHub at line 245 of file plot_DataSimComp.py
plot_DataSimComp.plotdir opt.plotdir
Definition at line 258 of file plot_DataSimComp.py.
View newest version in sPHENIX GitHub at line 258 of file plot_DataSimComp.py
plot_DataSimComp.simhistdir opt.simhistdir
Definition at line 256 of file plot_DataSimComp.py.
View newest version in sPHENIX GitHub at line 256 of file plot_DataSimComp.py
plot_DataSimComp.simlegtext opt.simlegtext
Definition at line 257 of file plot_DataSimComp.py.
View newest version in sPHENIX GitHub at line 257 of file plot_DataSimComp.py