Analysis Software: testing::internal::MatchesRegexMatcher Class Reference
testing::internal::MatchesRegexMatcher Class Reference
#include <JETSCAPE/blob/main/external_packages/googletest/googlemock/include/gmock/gmock-matchers.h>
Public Member Functions
MatchesRegexMatcher (const RE *regex, bool full_match)
template<typename CharType >
bool MatchAndExplain (CharType *s, MatchResultListener *listener) const
template<class MatcheeStringType >
bool MatchAndExplain (const MatcheeStringType &s, MatchResultListener *) const
void DescribeTo (::std::ostream *os) const
void DescribeNegationTo (::std::ostream *os) const
Private Member Functions
GTEST_DISALLOW_ASSIGN_ (MatchesRegexMatcher)
Private Attributes
const internal::linked_ptr
< const RE > regex_
const bool full_match_
Detailed Description
Definition at line 1326 of file gmock-matchers.h.
View newest version in sPHENIX GitHub at line 1326 of file gmock-matchers.h
Constructor & Destructor Documentation
testing::internal::MatchesRegexMatcher::MatchesRegexMatcher (const RE * regex, bool full_match) inline
Definition at line 1328 of file gmock-matchers.h.
View newest version in sPHENIX GitHub at line 1328 of file gmock-matchers.h
Member Function Documentation
void testing::internal::MatchesRegexMatcher::DescribeNegationTo (::std::ostream * os) const inline
Definition at line 1359 of file gmock-matchers.h.
View newest version in sPHENIX GitHub at line 1359 of file gmock-matchers.h
References full_match_, os, testing::internal::RE::pattern(), testing::internal::UniversalPrinter< T >::Print(), and regex_.
void testing::internal::MatchesRegexMatcher::DescribeTo (::std::ostream * os) const inline
Definition at line 1353 of file gmock-matchers.h.
View newest version in sPHENIX GitHub at line 1353 of file gmock-matchers.h
References full_match_, os, testing::internal::RE::pattern(), testing::internal::UniversalPrinter< T >::Print(), and regex_.
testing::internal::MatchesRegexMatcher::GTEST_DISALLOW_ASSIGN_ (MatchesRegexMatcher) private
template<typename CharType > bool testing::internal::MatchesRegexMatcher::MatchAndExplain (CharType * s, MatchResultListener * listener) const inline
Definition at line 1337 of file gmock-matchers.h.
View newest version in sPHENIX GitHub at line 1337 of file gmock-matchers.h
template<class MatcheeStringType > bool testing::internal::MatchesRegexMatcher::MatchAndExplain (const MatcheeStringType & s, MatchResultListener *) const inline
Definition at line 1346 of file gmock-matchers.h.
View newest version in sPHENIX GitHub at line 1346 of file gmock-matchers.h
References full_match_, testing::internal::RE::FullMatch(), testing::internal::RE::PartialMatch(), and regex_.
Member Data Documentation
const bool testing::internal::MatchesRegexMatcher::full_match_ private
Definition at line 1367 of file gmock-matchers.h.
View newest version in sPHENIX GitHub at line 1367 of file gmock-matchers.h
Referenced by DescribeNegationTo(), DescribeTo(), and MatchAndExplain().
const internal::linked_ptr<const RE> testing::internal::MatchesRegexMatcher::regex_ private
Definition at line 1366 of file gmock-matchers.h.
View newest version in sPHENIX GitHub at line 1366 of file gmock-matchers.h
Referenced by DescribeNegationTo(), DescribeTo(), and MatchAndExplain().
The documentation for this class was generated from the following file:
JETSCAPE/blob/main/external_packages/googletest/googlemock/include/gmock/gmock-matchers.h