Analysis Software: ActsExamples::CsvPlanarClusterWriter Exception Reference
ActsExamples::CsvPlanarClusterWriter Exception Reference final
#include <acts/blob/sPHENIX/Examples/Io/Csv/include/ActsExamples/Io/Csv/CsvPlanarClusterWriter.hpp>
Classes
struct Config
Public Member Functions
CsvPlanarClusterWriter (const Config &cfg, Acts::Logging::Level lvl)
Public Member Functions inherited from ActsExamples::WriterT< GeometryIdMultimap< Acts::PlanarModuleCluster > >
WriterT (std::string objectName, std::string writerName, Acts::Logging::Level level)
std::string name () const finaloverride
Provide the name of the writer.
ProcessCode write (const AlgorithmContext &context) finaloverride
Read the object and call the type-specific member function.
ProcessCode endRun () override
No-op default implementation.
Public Member Functions inherited from ActsExamples::IWriter
virtual ~IWriter ()=default
Protected Member Functions
ProcessCode writeT (const AlgorithmContext &ctx, const GeometryIdMultimap< Acts::PlanarModuleCluster > &clusters) finaloverride
Protected Member Functions inherited from ActsExamples::WriterT< GeometryIdMultimap< Acts::PlanarModuleCluster > >
const Acts::Logger & logger () const
Private Attributes
Config m_cfg
Detailed Description
Write out a planar cluster collection in comma-separated-value format.
This writes multiples file per event containing information about the space points, local constituent cells, and hit-particle truth mapping into the configured output directory. By default it writes to the current working directory. Files are named using the following schema
event000000001-cells.csv
event000000001-hits.csv
event000000001-truth.csv
event000000002-cells.csv
event000000002-hits.csv
event000000002-truth.csv
...
and each line in the file corresponds to one hit/cluster.
Definition at line 36 of file CsvPlanarClusterWriter.hpp.
View newest version in sPHENIX GitHub at line 36 of file CsvPlanarClusterWriter.hpp
Constructor & Destructor Documentation
ActsExamples::CsvPlanarClusterWriter::CsvPlanarClusterWriter (const Config & cfg, Acts::Logging::Level lvl)
Construct the cluster writer.
cfg is the configuration object lvl is the logging level
Definition at line 25 of file CsvPlanarClusterWriter.cpp.
View newest version in sPHENIX GitHub at line 25 of file CsvPlanarClusterWriter.cpp
References ActsExamples::CsvPlanarClusterWriter::Config::inputSimulatedHits, and m_cfg.
Member Function Documentation
ActsExamples::ProcessCode ActsExamples::CsvPlanarClusterWriter::writeT (const AlgorithmContext & ctx, const GeometryIdMultimap< Acts::PlanarModuleCluster > & clusters) final override protected virtual
Type-specific write implementation.
Parameters
[in] ctx is the algorithm context
[in] particles are the particle to be written
Implements ActsExamples::WriterT< GeometryIdMultimap< Acts::PlanarModuleCluster > >.
Definition at line 35 of file CsvPlanarClusterWriter.cpp.
View newest version in sPHENIX GitHub at line 35 of file CsvPlanarClusterWriter.cpp
References ACTS_FATAL, dfe::io_dsv_impl::NamedTupleDsvWriter< Delimiter, NamedTuple >::append(), c, ActsExamples::CellData::ch0, ActsExamples::CellData::ch1, ActsExamples::TruthHitData::deltae, ActsExamples::TruthHitData::deltapx, ActsExamples::TruthHitData::deltapy, ActsExamples::TruthHitData::deltapz, Acts::PlanarModuleCluster::digitizationCells(), entry, ActsExamples::AlgorithmContext::eventNumber, ActsExamples::AlgorithmContext::eventStore, ActsExamples::AlgorithmContext::geoContext, ActsExamples::TruthHitData::geometry_id, ActsExamples::HitData::geometry_id, ActsExamples::WhiteBoard::get(), Acts::UnitConstants::GeV, ActsExamples::TruthHitData::hit_id, ActsExamples::HitData::hit_id, ActsExamples::CellData::hit_id, ActsExamples::TruthHitData::index, it, Acts::GeometryIdentifier::layer(), ActsExamples::HitData::layer_id, Acts::UnitConstants::mm, ActsExamples::HitData::module_id, Acts::UnitConstants::ns, Dataset::parameters, Acts::Measurement< source_link_t, parameter_indices_t, params >::parameters(), ActsExamples::TruthHitData::particle_id, ActsExamples::perEventFilepath(), Acts::Measurement< source_link_t, parameter_indices_t, params >::referenceObject(), Acts::GeometryIdentifier::sensitive(), Acts::Measurement< source_link_t, parameter_indices_t, params >::sourceLink(), SUCCESS, ActsExamples::HitData::t, ActsExamples::TruthHitData::te, ActsExamples::CellData::timestamp, ActsExamples::TruthHitData::tpx, ActsExamples::TruthHitData::tpy, ActsExamples::TruthHitData::tpz, ActsExamples::TruthHitData::tt, ActsExamples::TruthHitData::tx, ActsExamples::TruthHitData::ty, ActsExamples::TruthHitData::tz, Acts::GeometryIdentifier::value(), ActsExamples::CellData::value, Acts::GeometryIdentifier::volume(), ActsExamples::HitData::volume_id, ActsExamples::HitData::x, ActsExamples::HitData::y, and ActsExamples::HitData::z.
Member Data Documentation
Config ActsExamples::CsvPlanarClusterWriter::m_cfg private
Definition at line 66 of file CsvPlanarClusterWriter.hpp.
View newest version in sPHENIX GitHub at line 66 of file CsvPlanarClusterWriter.hpp
Referenced by CsvPlanarClusterWriter().
The documentation for this exception was generated from the following files:
acts/blob/sPHENIX/Examples/Io/Csv/include/ActsExamples/Io/Csv/CsvPlanarClusterWriter.hpp
acts/blob/sPHENIX/Examples/Io/Csv/src/CsvPlanarClusterWriter.cpp