Analysis Software: acts/blob/sPHENIX/Tests/UnitTests/Core/Material/MaterialSlabTests.cpp File Reference
MaterialSlabTests.cpp File Reference
#include <boost/test/unit_test.hpp>
#include "Acts/Material/Material.hpp"
#include "Acts/Material/MaterialSlab.hpp"
#include "Acts/Tests/CommonHelpers/FloatComparisons.hpp"
#include <limits>
#include <vector>
Functions
BOOST_AUTO_TEST_CASE (construct_simple)
BOOST_AUTO_TEST_CASE (construct_compound)
BOOST_AUTO_TEST_CASE (scale_thickness)
Variables
static constexpr auto eps = 2 * std::numeric_limits<float>::epsilon()
Function Documentation
BOOST_AUTO_TEST_CASE (construct_simple)
construct from material and thickness
Definition at line 22 of file MaterialSlabTests.cpp.
View newest version in sPHENIX GitHub at line 22 of file MaterialSlabTests.cpp
References CHECK_CLOSE_REL, eps, Acts::Material::fromMolarDensity(), Acts::MaterialSlab::thickness(), Acts::MaterialSlab::thicknessInL0(), and Acts::MaterialSlab::thicknessInX0().
BOOST_AUTO_TEST_CASE (construct_compound)
Definition at line 32 of file MaterialSlabTests.cpp.
View newest version in sPHENIX GitHub at line 32 of file MaterialSlabTests.cpp
References KFPMath::a, KFPMath::b, Acts::PhysicalConstants::c, CHECK_CLOSE_REL, and eps.
BOOST_AUTO_TEST_CASE (scale_thickness)
Definition at line 66 of file MaterialSlabTests.cpp.
View newest version in sPHENIX GitHub at line 66 of file MaterialSlabTests.cpp
References CHECK_CLOSE_REL, eps, Acts::Material::fromMassDensity(), Acts::Material::massDensity(), material, Acts::MaterialSlab::material(), Acts::MaterialSlab::scaleThickness(), Acts::MaterialSlab::thickness(), Acts::MaterialSlab::thicknessInL0(), and Acts::MaterialSlab::thicknessInX0().
Variable Documentation
constexpr auto eps = 2 * std::numeric_limits<float>::epsilon() static
Definition at line 18 of file MaterialSlabTests.cpp.
View newest version in sPHENIX GitHub at line 18 of file MaterialSlabTests.cpp
Referenced by BOOST_AUTO_TEST_CASE().