Analysis Software: fatras Namespace Reference
fatras Namespace Reference
Functions
def runFatras
Variables
u acts.UnitConstants
tuple gdc acts.examples.GenericDetector.Config()
tuple detector acts.examples.GenericDetector()
tuple field acts.ConstantBField(acts.Vector3(0, 0, 2 * u.T))
Function Documentation
def fatras.runFatras (trackingGeometry, field, outputDir, s)
Definition at line 11 of file fatras.py.
View newest version in sPHENIX GitHub at line 11 of file fatras.py
References acts.examples.simulation.addFatras(), acts.examples.simulation.addParticleGun(), and acts.examples.simulation.EtaConfig.
Variable Documentation
tuple fatras.detector acts.examples.GenericDetector()
Definition at line 34 of file fatras.py.
View newest version in sPHENIX GitHub at line 34 of file fatras.py
tuple fatras.field acts.ConstantBField(acts.Vector3(0, 0, 2 * u.T))
Definition at line 37 of file fatras.py.
View newest version in sPHENIX GitHub at line 37 of file fatras.py
tuple fatras.gdc acts.examples.GenericDetector.Config()
Definition at line 33 of file fatras.py.
View newest version in sPHENIX GitHub at line 33 of file fatras.py
Referenced by BOOST_AUTO_TEST_CASE().
fatras.u acts.UnitConstants
Definition at line 8 of file fatras.py.
View newest version in sPHENIX GitHub at line 8 of file fatras.py