Analysis Software: ActsExamples::CsvTrackParameterWriter Exception Reference
ActsExamples::CsvTrackParameterWriter Exception Reference final
#include <acts/blob/sPHENIX/Examples/Io/Csv/include/ActsExamples/Io/Csv/CsvTrackParameterWriter.hpp>
Classes
struct Config
Public Member Functions
CsvTrackParameterWriter (const Config &config, Acts::Logging::Level level)
~CsvTrackParameterWriter () override
Virtual destructor.
std::string name () const override
Provide the name of the writer.
ProcessCode write (const AlgorithmContext &ctx) override
Read the object and call the type-specific member function.
ProcessCode finalize () override
No-op default implementation.
const Config & config () const
Get readonly access to the config parameters.
Public Member Functions inherited from ActsExamples::IWriter
ProcessCode internalExecute (const AlgorithmContext &context) final
ProcessCode initialize () override
Fulfil the algorithm interface.
Public Member Functions inherited from ActsExamples::SequenceElement
virtual ~SequenceElement ()=default
const std::vector< const
DataHandleBase * > & writeHandles () const
const std::vector< const
DataHandleBase * > & readHandles () const
Private Attributes
Config m_cfg
std::unique_ptr< const
Acts::Logger > m_logger
ReadDataHandle< std::vector
< Acts::BoundTrackParameters > > m_inputTrackParameters {this, "InputTrackParameters"}
ReadDataHandle
< TrajectoriesContainer > m_inputTrajectories
Detailed Description
Write track parameters in comma-separated-value format.
This writes one file per event in the configured input directory and filename. Files are assumed to be named using the following schema
event000000001-<stem>.csv
event000000002-<stem>.csv
and each line in the file corresponds to one track parameter.
Definition at line 36 of file CsvTrackParameterWriter.hpp.
View newest version in sPHENIX GitHub at line 36 of file CsvTrackParameterWriter.hpp
Constructor & Destructor Documentation
ActsExamples::CsvTrackParameterWriter::CsvTrackParameterWriter (const Config & config, Acts::Logging::Level level)
Constructor with
Parameters
config configuration struct
level logging level
Definition at line 24 of file CsvTrackParameterWriter.cpp.
View newest version in sPHENIX GitHub at line 24 of file CsvTrackParameterWriter.cpp
References ActsExamples::CsvTrackParameterWriter::Config::inputTrackParameters, ActsExamples::CsvTrackParameterWriter::Config::inputTrajectories, m_cfg, m_inputTrackParameters, m_inputTrajectories, and ActsExamples::DataHandleBase::maybeInitialize().
ActsExamples::CsvTrackParameterWriter::~CsvTrackParameterWriter () override default
Virtual destructor.
Member Function Documentation
const Config& ActsExamples::CsvTrackParameterWriter::config () const inline
Get readonly access to the config parameters.
Definition at line 69 of file CsvTrackParameterWriter.hpp.
View newest version in sPHENIX GitHub at line 69 of file CsvTrackParameterWriter.hpp
References m_cfg.
ActsExamples::ProcessCode ActsExamples::CsvTrackParameterWriter::finalize () override virtual
No-op default implementation.
Implements ActsExamples::SequenceElement.
Definition at line 44 of file CsvTrackParameterWriter.cpp.
View newest version in sPHENIX GitHub at line 44 of file CsvTrackParameterWriter.cpp
References SUCCESS.
std::string ActsExamples::CsvTrackParameterWriter::name () const override virtual
Provide the name of the writer.
Implements ActsExamples::SequenceElement.
Definition at line 40 of file CsvTrackParameterWriter.cpp.
View newest version in sPHENIX GitHub at line 40 of file CsvTrackParameterWriter.cpp
ActsExamples::ProcessCode ActsExamples::CsvTrackParameterWriter::write (const AlgorithmContext & ctx) override virtual
Read the object and call the type-specific member function.
Implements ActsExamples::IWriter.
Definition at line 49 of file CsvTrackParameterWriter.cpp.
View newest version in sPHENIX GitHub at line 49 of file CsvTrackParameterWriter.cpp
References Acts::Test::cov, configureMap::data, Acts::eBoundLoc0, Acts::eBoundLoc1, Acts::eBoundPhi, Acts::eBoundQOverP, Acts::eBoundTheta, ActsExamples::AlgorithmContext::eventNumber, truth_tracking_gsf_refitting::inputTrajectories, m_cfg(), path, ActsExamples::perEventFilepath(), SUCCESS, Acts::Test::tmp(), physmon_simulation::tp, and writer.
Member Data Documentation
Config ActsExamples::CsvTrackParameterWriter::m_cfg private
Definition at line 72 of file CsvTrackParameterWriter.hpp.
View newest version in sPHENIX GitHub at line 72 of file CsvTrackParameterWriter.hpp
Referenced by config(), and CsvTrackParameterWriter().
ReadDataHandle<std::vector<Acts::BoundTrackParameters> > ActsExamples::CsvTrackParameterWriter::m_inputTrackParameters {this, "InputTrackParameters"} private
Definition at line 76 of file CsvTrackParameterWriter.hpp.
View newest version in sPHENIX GitHub at line 76 of file CsvTrackParameterWriter.hpp
Referenced by CsvTrackParameterWriter().
ReadDataHandle<TrajectoriesContainer> ActsExamples::CsvTrackParameterWriter::m_inputTrajectories private
Initial value:
{
      this, "InputTrajectories"}
Definition at line 77 of file CsvTrackParameterWriter.hpp.
View newest version in sPHENIX GitHub at line 77 of file CsvTrackParameterWriter.hpp
Referenced by CsvTrackParameterWriter().
std::unique_ptr<const Acts::Logger> ActsExamples::CsvTrackParameterWriter::m_logger private
Definition at line 73 of file CsvTrackParameterWriter.hpp.
View newest version in sPHENIX GitHub at line 73 of file CsvTrackParameterWriter.hpp
The documentation for this exception was generated from the following files:
acts/blob/sPHENIX/Examples/Io/Csv/include/ActsExamples/Io/Csv/CsvTrackParameterWriter.hpp
acts/blob/sPHENIX/Examples/Io/Csv/src/CsvTrackParameterWriter.cpp