Analysis Software: macros/blob/master/TrackingProduction/Fun4All_TrkrHitSet_Unpacker.C File Reference
Fun4All_TrkrHitSet_Unpacker.C File Reference
#include <GlobalVariables.C>
#include <fun4all/Fun4AllDstInputManager.h>
#include <fun4all/Fun4AllDstOutputManager.h>
#include <fun4all/Fun4AllInputManager.h>
#include <fun4all/Fun4AllOutputManager.h>
#include <fun4all/Fun4AllRunNodeInputManager.h>
#include <fun4all/Fun4AllServer.h>
#include <ffamodules/CDBInterface.h>
#include <phool/recoConsts.h>
#include <intt/InttCombinedRawDataDecoder.h>
#include <micromegas/MicromegasCombinedDataDecoder.h>
#include <mvtx/MvtxCombinedRawDataDecoder.h>
#include <tpc/TpcCombinedRawDataUnpacker.h>
#include <stdio.h>
Functions
void Fun4All_TrkrHitSet_Unpacker (const int nEvents=2, const int runnumber=26048, const std::string outfilename="cosmics", const std::string dir="/sphenix/lustre01/sphnxpro/commissioning/aligned_streaming_all_3/", const std::string file="cosmics-")
Function Documentation
void Fun4All_TrkrHitSet_Unpacker (const int nEvents = 2, const int runnumber = 26048, const std::string outfilename = "cosmics", const std::string dir = "/sphenix/lustre01/sphnxpro/commissioning/aligned_streaming_all_3/", const std::string file = "cosmics-")
Definition at line 32 of file Fun4All_TrkrHitSet_Unpacker.C.
View newest version in sPHENIX GitHub at line 32 of file Fun4All_TrkrHitSet_Unpacker.C
References Fun4AllInputManager::AddFile(), Enable::CDB, file, filename, CDBInterface::getUrl(), recoConsts::instance(), CDBInterface::instance(), Fun4AllServer::instance(), InttCombinedRawDataDecoder::LoadHotChannelMapRemote(), out, runnumber, Fun4AllOutputManager::StripNode(), and Fun4AllBase::Verbosity().