Analysis Software: InttNameSpace Namespace Reference
InttNameSpace Namespace Reference
Classes
struct RawData_s
struct Online_s
struct Offline_s
struct RawDataComparator
struct OnlineComparator
struct OfflineComparator
Typedefs
typedef uint32_t OnlineKey_t
Functions
int FelixFromPacket (int)
struct InttNameSpace::RawData_s RawFromPacket (int const, int const, Packet *)
void RawFromHit (struct InttNameSpace::RawData_s &, InttRawHit *)
struct Online_s ToOnline (struct Offline_s const &)
struct Offline_s ToOffline (struct Online_s const &)
struct RawData_s ToRawData (struct Online_s const &)
struct Online_s ToOnline (struct RawData_s const &)
struct RawData_s ToRawData (struct Offline_s const &)
struct Offline_s ToOffline (struct RawData_s const &)
Variables
const std::map< int, int > Packet_Id
Typedef Documentation
typedef uint32_t InttNameSpace::OnlineKey_t
Definition at line 23 of file InttMapping.h.
View newest version in sPHENIX GitHub at line 23 of file InttMapping.h
Function Documentation
int InttNameSpace::FelixFromPacket (int packetid)
Definition at line 23 of file InttMapping.cc.
View newest version in sPHENIX GitHub at line 23 of file InttMapping.cc
References packetid.
Referenced by RawFromHit().
void InttNameSpace::RawFromHit (struct InttNameSpace::RawData_s & s, InttRawHit * h)
Definition at line 58 of file InttMapping.cc.
View newest version in sPHENIX GitHub at line 58 of file InttMapping.cc
References InttNameSpace::RawData_s::channel, InttNameSpace::RawData_s::chip, InttNameSpace::RawData_s::felix_channel, InttNameSpace::RawData_s::felix_server, FelixFromPacket(), InttRawHit::get_channel_id(), InttRawHit::get_chip_id(), InttRawHit::get_fee(), and InttRawHit::get_packetid().
Referenced by InttCombinedRawDataDecoder::process_event(), and InttCombinedRawDataConverter::process_event().
struct InttNameSpace::RawData_s InttNameSpace::RawFromPacket (int const _i, int const _n, Packet * _p) read
Definition at line 39 of file InttMapping.cc.
View newest version in sPHENIX GitHub at line 39 of file InttMapping.cc
References InttNameSpace::RawData_s::channel, InttNameSpace::RawData_s::chip, InttNameSpace::RawData_s::felix_channel, InttNameSpace::RawData_s::felix_server, Packet_Id, and physmon_simulation::s.
Referenced by InttRawDataDecoder::process_event(), and InttRawDataConverter::process_event().
struct InttNameSpace::Offline_s InttNameSpace::ToOffline (struct Online_s const & _s) read
Definition at line 103 of file InttMapping.cc.
View newest version in sPHENIX GitHub at line 103 of file InttMapping.cc
References InttNameSpace::Offline_s::ladder_phi, InttNameSpace::Offline_s::ladder_z, InttNameSpace::Offline_s::layer, physmon_simulation::s, InttNameSpace::Offline_s::strip_x, and InttNameSpace::Offline_s::strip_y.
Referenced by InttCombinedRawDataDecoder::process_event(), InttRawDataDecoder::process_event(), and ToOffline().
struct InttNameSpace::Offline_s InttNameSpace::ToOffline (struct RawData_s const & _s) read
Definition at line 167 of file InttMapping.cc.
View newest version in sPHENIX GitHub at line 167 of file InttMapping.cc
References ToOffline(), and ToOnline().
struct InttNameSpace::Online_s InttNameSpace::ToOnline (struct Offline_s const & _s) read
Definition at line 66 of file InttMapping.cc.
View newest version in sPHENIX GitHub at line 66 of file InttMapping.cc
References InttNameSpace::Online_s::arm, InttNameSpace::Online_s::chn, InttNameSpace::Online_s::chp, InttNameSpace::Online_s::ldr, and InttNameSpace::Online_s::lyr.
Referenced by InttCombinedRawDataConverter::process_event(), InttRawDataConverter::process_event(), ToOffline(), and ToRawData().
struct InttNameSpace::Online_s InttNameSpace::ToOnline (struct RawData_s const & _s) read
Definition at line 151 of file InttMapping.cc.
View newest version in sPHENIX GitHub at line 151 of file InttMapping.cc
References InttNameSpace::Online_s::chn, InttNameSpace::Online_s::chp, InttFelix::RawDataToOnline(), and physmon_simulation::s.
struct InttNameSpace::RawData_s InttNameSpace::ToRawData (struct Online_s const & _s) read
Definition at line 140 of file InttMapping.cc.
View newest version in sPHENIX GitHub at line 140 of file InttMapping.cc
References InttNameSpace::RawData_s::channel, InttNameSpace::RawData_s::chip, InttFelix::OnlineToRawData(), and physmon_simulation::s.
Referenced by ToRawData().
struct InttNameSpace::RawData_s InttNameSpace::ToRawData (struct Offline_s const & _s) read
Definition at line 162 of file InttMapping.cc.
View newest version in sPHENIX GitHub at line 162 of file InttMapping.cc
References ToOnline(), and ToRawData().
Variable Documentation
const std::map< int, int > InttNameSpace::Packet_Id
Initial value:
=
    {
        {3001, 0},
        {3002, 1},
        {3003, 2},
        {3004, 3},
        {3005, 4},
        {3006, 5},
        {3007, 6},
        {3008, 7},
}
Definition at line 11 of file InttMapping.cc.
View newest version in sPHENIX GitHub at line 11 of file InttMapping.cc
Referenced by InttRawDataDecoder::process_event(), InttRawDataConverter::process_event(), and RawFromPacket().