Analysis Software: PHTruthVertexing Class Reference
PHTruthVertexing Class Reference
Vertexing using truth info.
#include <coresoftware/blob/master/offline/packages/trackreco/PHTruthVertexing.h>
Public Member Functions
PHTruthVertexing (const std::string &name="PHTruthVertexing")
~PHTruthVertexing () override
void set_vertex_error (const float &x_err, const float &y_err, const float &z_err)
const std::vector< float > & get_vertex_error () const
void associate_tracks (bool associate_tracks)
void set_embed_only (bool embed_only)
void set_track_map_name (std::string &name)
Public Member Functions inherited from PHInitVertexing
PHInitVertexing (const std::string &name="PHInitVertexing")
~PHInitVertexing () override=default
int InitRun (PHCompositeNode *topNode) override
int process_event (PHCompositeNode *topNode) override
Public Member Functions inherited from SubsysReco
~SubsysReco () override
virtual int EndRun (const int)
Called at the end of each run.
virtual int Init (PHCompositeNode *)
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
void Print (const std::string &="ALL") const override
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Protected Member Functions
int Setup (PHCompositeNode *topNode) override
int Process (PHCompositeNode *topNode) override
int End (PHCompositeNode *) override
Called at the end of all processing.
Private Member Functions
int GetNodes (PHCompositeNode *topNode)
fetch node pointers
void assignTracksVertices (PHCompositeNode *topNode)
Private Attributes
PHG4TruthInfoContainer * _g4truth_container
std::vector< float > _vertex_error
manually assigned vertex error (standard dev), cm
bool _embed_only
bool _associate_tracks = false
std::string _track_map_name = "SvtxTrackMap"
gsl_rng * m_RandomGenerator
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = std::numeric_limits<int>::max() - 10
}
Protected Attributes inherited from PHInitVertexing
TrkrClusterContainer * _cluster_map = nullptr
SvtxVertexMap * _vertex_map = nullptr
Detailed Description
Vertexing using truth info.
Definition at line 28 of file PHTruthVertexing.h.
View newest version in sPHENIX GitHub at line 28 of file PHTruthVertexing.h
Constructor & Destructor Documentation
PHTruthVertexing::PHTruthVertexing (const std::string & name = "PHTruthVertexing")
Definition at line 27 of file PHTruthVertexing.cc.
View newest version in sPHENIX GitHub at line 27 of file PHTruthVertexing.cc
PHTruthVertexing::~PHTruthVertexing () override
Definition at line 43 of file PHTruthVertexing.cc.
View newest version in sPHENIX GitHub at line 43 of file PHTruthVertexing.cc
References m_RandomGenerator.
Member Function Documentation
void PHTruthVertexing::assignTracksVertices (PHCompositeNode * topNode) private
Definition at line 135 of file PHTruthVertexing.cc.
View newest version in sPHENIX GitHub at line 135 of file PHTruthVertexing.cc
References _track_map_name, PHInitVertexing::_vertex_map, SvtxTrackMap::begin(), SvtxVertexMap::begin(), dz, SvtxTrackMap::end(), SvtxVertexMap::end(), SvtxVertexMap::find(), PHWHERE, and Fun4AllBase::Verbosity().
Referenced by Process().
void PHTruthVertexing::associate_tracks (bool associate_tracks) inline
Definition at line 46 of file PHTruthVertexing.h.
View newest version in sPHENIX GitHub at line 46 of file PHTruthVertexing.h
References _associate_tracks.
Referenced by Fun4All_G4_sPHENIX(), and vertexing().
int PHTruthVertexing::End (PHCompositeNode *) override protected virtual
Called at the end of all processing.
Reimplemented from SubsysReco.
Definition at line 200 of file PHTruthVertexing.cc.
View newest version in sPHENIX GitHub at line 200 of file PHTruthVertexing.cc
References Fun4AllReturnCodes::EVENT_OK.
const std::vector<float>& PHTruthVertexing::get_vertex_error () const inline
Definition at line 42 of file PHTruthVertexing.h.
View newest version in sPHENIX GitHub at line 42 of file PHTruthVertexing.h
References _vertex_error.
int PHTruthVertexing::GetNodes (PHCompositeNode * topNode) private
fetch node pointers
Definition at line 189 of file PHTruthVertexing.cc.
View newest version in sPHENIX GitHub at line 189 of file PHTruthVertexing.cc
References _g4truth_container, Fun4AllReturnCodes::ABORTEVENT, Fun4AllReturnCodes::EVENT_OK, and PHWHERE.
Referenced by Setup().
int PHTruthVertexing::Process (PHCompositeNode * topNode) override protected virtual
process event interface for trackers, called in process_event. implemented in derived classes
Implements PHInitVertexing.
Definition at line 58 of file PHTruthVertexing.cc.
View newest version in sPHENIX GitHub at line 58 of file PHTruthVertexing.cc
References _associate_tracks, _g4truth_container, _vertex_error, PHInitVertexing::_vertex_map, assignTracksVertices(), Fun4AllReturnCodes::EVENT_OK, PHG4TruthInfoContainer::GetPrimaryVtxRange(), i, SvtxVertexMap::identify(), SvtxVertexMap::insert(), PHG4TruthInfoContainer::isEmbededVtx(), j, m_RandomGenerator, Acts::Test::pos, SvtxVertex::set_chisq(), SvtxVertex::set_error(), SvtxVertex::set_id(), SvtxVertex::set_ndof(), SvtxVertex::set_t(), SvtxVertex::set_x(), SvtxVertex::set_y(), SvtxVertex::set_z(), and Fun4AllBase::Verbosity().
void PHTruthVertexing::set_embed_only (bool embed_only) inline
Definition at line 50 of file PHTruthVertexing.h.
View newest version in sPHENIX GitHub at line 50 of file PHTruthVertexing.h
References _embed_only.
void PHTruthVertexing::set_track_map_name (std::string & name) inline
Definition at line 54 of file PHTruthVertexing.h.
View newest version in sPHENIX GitHub at line 54 of file PHTruthVertexing.h
References _track_map_name, and perf_headwind::name.
void PHTruthVertexing::set_vertex_error (const float & x_err, const float & y_err, const float & z_err) inline
Definition at line 34 of file PHTruthVertexing.h.
View newest version in sPHENIX GitHub at line 34 of file PHTruthVertexing.h
References _vertex_error.
int PHTruthVertexing::Setup (PHCompositeNode * topNode) override protected virtual
setup interface for trackers, called in InitRun, setup things like pointers to nodes. overrided in derived classes
Reimplemented from PHInitVertexing.
Definition at line 47 of file PHTruthVertexing.cc.
View newest version in sPHENIX GitHub at line 47 of file PHTruthVertexing.cc
References Fun4AllReturnCodes::EVENT_OK, GetNodes(), and PHInitVertexing::Setup().
Member Data Documentation
bool PHTruthVertexing::_associate_tracks = false private
Definition at line 76 of file PHTruthVertexing.h.
View newest version in sPHENIX GitHub at line 76 of file PHTruthVertexing.h
Referenced by associate_tracks(), and Process().
bool PHTruthVertexing::_embed_only private
Definition at line 75 of file PHTruthVertexing.h.
View newest version in sPHENIX GitHub at line 75 of file PHTruthVertexing.h
Referenced by set_embed_only().
PHG4TruthInfoContainer* PHTruthVertexing::_g4truth_container private
Definition at line 70 of file PHTruthVertexing.h.
View newest version in sPHENIX GitHub at line 70 of file PHTruthVertexing.h
Referenced by GetNodes(), and Process().
std::string PHTruthVertexing::_track_map_name = "SvtxTrackMap" private
Definition at line 77 of file PHTruthVertexing.h.
View newest version in sPHENIX GitHub at line 77 of file PHTruthVertexing.h
Referenced by assignTracksVertices(), and set_track_map_name().
std::vector<float> PHTruthVertexing::_vertex_error private
manually assigned vertex error (standard dev), cm
Definition at line 73 of file PHTruthVertexing.h.
View newest version in sPHENIX GitHub at line 73 of file PHTruthVertexing.h
Referenced by get_vertex_error(), Process(), and set_vertex_error().
gsl_rng* PHTruthVertexing::m_RandomGenerator private
Definition at line 78 of file PHTruthVertexing.h.
View newest version in sPHENIX GitHub at line 78 of file PHTruthVertexing.h
Referenced by Process(), and ~PHTruthVertexing().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/trackreco/PHTruthVertexing.h
coresoftware/blob/master/offline/packages/trackreco/PHTruthVertexing.cc