Analysis Software: PHG4BbcDetector Class Reference
PHG4BbcDetector Class Reference
#include <coresoftware/blob/master/simulation/g4simulation/g4detectors/PHG4BbcDetector.h>
Public Member Functions
PHG4BbcDetector (PHG4Subsystem *subsys, PHCompositeNode *Node, PHParameters *params, const std::string &dnam="BBC")
constructor
~PHG4BbcDetector () override
destructor
void ConstructMe (G4LogicalVolume *world) override
construct BBC/MBD
void ConstructSupport (G4LogicalVolume *world)
void Print (const std::string &what="ALL") const override
int IsInBbc (G4VPhysicalVolume *) const
void SuperDetector (const std::string &name)
const std::string SuperDetector () const
PHG4BbcDisplayAction * GetDisplayAction ()
Public Member Functions inherited from PHG4Detector
PHG4Detector ()=delete
constructor
PHG4Detector (PHG4Subsystem *subsys, PHCompositeNode *Node, const std::string &nam)
virtual ~PHG4Detector (void)
destructor
virtual void Construct (G4LogicalVolume *world) final
construct method
virtual void PostConstruction ()
Optional PostConstruction call after all geometry is constructed.
virtual void Verbosity (const int v)
virtual int Verbosity () const
virtual G4UserSteppingAction * GetSteppingAction ()
virtual std::string GetName () const
virtual void OverlapCheck (const bool chk)
virtual bool OverlapCheck () const
virtual int DisplayVolume (G4VSolid *volume, G4LogicalVolume *logvol, G4RotationMatrix *rotm=nullptr)
virtual int DisplayVolume (G4LogicalVolume *checksolid, G4LogicalVolume *logvol, G4RotationMatrix *rotm=nullptr)
virtual PHCompositeNode * topNode ()
virtual PHG4Subsystem * GetMySubsystem ()
Protected Attributes
PHG4BbcDisplayAction * m_DisplayAction = nullptr
PHParameters * m_Params = nullptr
int m_ActiveFlag = 0
int m_SupportActiveFlag = 0
float m_bbcz = NAN
float front_bbcz = NAN
std::set< G4LogicalVolume * > m_PhysLogicalVolSet
std::set< G4LogicalVolume * > m_SupportLogicalVolSet
std::string m_SuperDetector
Additional Inherited Members
Static Public Member Functions inherited from PHG4Detector
static G4Material * GetDetectorMaterial (const std::string &name, const bool quit=true)
static G4Element * GetDetectorElement (const std::string &name, const bool quit=true)
Detailed Description
Definition at line 19 of file PHG4BbcDetector.h.
View newest version in sPHENIX GitHub at line 19 of file PHG4BbcDetector.h
Constructor & Destructor Documentation
PHG4BbcDetector::PHG4BbcDetector (PHG4Subsystem * subsys, PHCompositeNode * Node, PHParameters * params, const std::string & dnam = "BBC")
constructor
Definition at line 37 of file PHG4BbcDetector.cc.
View newest version in sPHENIX GitHub at line 37 of file PHG4BbcDetector.cc
PHG4BbcDetector::~PHG4BbcDetector () inline override
destructor
Definition at line 26 of file PHG4BbcDetector.h.
View newest version in sPHENIX GitHub at line 26 of file PHG4BbcDetector.h
Member Function Documentation
void PHG4BbcDetector::ConstructMe (G4LogicalVolume * world) override virtual
construct BBC/MBD
Implements PHG4Detector.
Definition at line 70 of file PHG4BbcDetector.cc.
View newest version in sPHENIX GitHub at line 70 of file PHG4BbcDetector.cc
References PHG4BbcDisplayAction::AddVolume(), Acts::UnitConstants::cm, Acts::UnitConstants::cm3, ConstructSupport(), deg, INTTVtxZ::dphi, Acts::UnitConstants::g, PHFlag::get_StringFlag(), PHG4Detector::GetDetectorMaterial(), GetDisplayAction(), recoConsts::instance(), m_bbcz, m_PhysLogicalVolSet, m_SupportLogicalVolSet, PHG4Detector::OverlapCheck(), TubeLoc, G4WORLD::WorldMaterial, and xpos.
void PHG4BbcDetector::ConstructSupport (G4LogicalVolume * world)
Definition at line 437 of file PHG4BbcDetector.cc.
View newest version in sPHENIX GitHub at line 437 of file PHG4BbcDetector.cc
References PHG4BbcDisplayAction::AddVolume(), Acts::UnitConstants::cm, Acts::UnitConstants::cm3, deg, front_bbcz, Acts::UnitConstants::g, PHFlag::get_StringFlag(), PHG4Detector::GetDetectorMaterial(), GetDisplayAction(), recoConsts::instance(), PHG4Detector::OverlapCheck(), G4WORLD::WorldMaterial, and xpos.
Referenced by ConstructMe().
PHG4BbcDisplayAction* PHG4BbcDetector::GetDisplayAction () inline
Definition at line 41 of file PHG4BbcDetector.h.
View newest version in sPHENIX GitHub at line 41 of file PHG4BbcDetector.h
References m_DisplayAction.
Referenced by ConstructMe(), and ConstructSupport().
int PHG4BbcDetector::IsInBbc (G4VPhysicalVolume * volume) const
Definition at line 49 of file PHG4BbcDetector.cc.
View newest version in sPHENIX GitHub at line 49 of file PHG4BbcDetector.cc
References m_ActiveFlag, m_PhysLogicalVolSet, m_SupportActiveFlag, and m_SupportLogicalVolSet.
Referenced by PHG4BbcSteppingAction::UserSteppingAction().
void PHG4BbcDetector::Print (const std::string & what = "ALL") const override virtual
Reimplemented from PHG4Detector.
Definition at line 654 of file PHG4BbcDetector.cc.
View newest version in sPHENIX GitHub at line 654 of file PHG4BbcDetector.cc
Referenced by PHG4BbcSubsystem::Print().
void PHG4BbcDetector::SuperDetector (const std::string & name) inline
Definition at line 38 of file PHG4BbcDetector.h.
View newest version in sPHENIX GitHub at line 38 of file PHG4BbcDetector.h
References m_SuperDetector, and perf_headwind::name.
Referenced by PHG4BbcSubsystem::InitRunSubsystem().
const std::string PHG4BbcDetector::SuperDetector () const inline
Definition at line 39 of file PHG4BbcDetector.h.
View newest version in sPHENIX GitHub at line 39 of file PHG4BbcDetector.h
References m_SuperDetector.
Member Data Documentation
float PHG4BbcDetector::front_bbcz = NAN protected
Definition at line 52 of file PHG4BbcDetector.h.
View newest version in sPHENIX GitHub at line 52 of file PHG4BbcDetector.h
Referenced by ConstructSupport().
int PHG4BbcDetector::m_ActiveFlag = 0 protected
Definition at line 48 of file PHG4BbcDetector.h.
View newest version in sPHENIX GitHub at line 48 of file PHG4BbcDetector.h
Referenced by IsInBbc().
float PHG4BbcDetector::m_bbcz = NAN protected
Definition at line 51 of file PHG4BbcDetector.h.
View newest version in sPHENIX GitHub at line 51 of file PHG4BbcDetector.h
Referenced by ConstructMe().
PHG4BbcDisplayAction* PHG4BbcDetector::m_DisplayAction = nullptr protected
Definition at line 44 of file PHG4BbcDetector.h.
View newest version in sPHENIX GitHub at line 44 of file PHG4BbcDetector.h
Referenced by GetDisplayAction().
PHParameters* PHG4BbcDetector::m_Params = nullptr protected
Definition at line 46 of file PHG4BbcDetector.h.
View newest version in sPHENIX GitHub at line 46 of file PHG4BbcDetector.h
std::set<G4LogicalVolume *> PHG4BbcDetector::m_PhysLogicalVolSet protected
Definition at line 54 of file PHG4BbcDetector.h.
View newest version in sPHENIX GitHub at line 54 of file PHG4BbcDetector.h
Referenced by ConstructMe(), and IsInBbc().
std::string PHG4BbcDetector::m_SuperDetector protected
Definition at line 57 of file PHG4BbcDetector.h.
View newest version in sPHENIX GitHub at line 57 of file PHG4BbcDetector.h
Referenced by SuperDetector().
int PHG4BbcDetector::m_SupportActiveFlag = 0 protected
Definition at line 49 of file PHG4BbcDetector.h.
View newest version in sPHENIX GitHub at line 49 of file PHG4BbcDetector.h
Referenced by IsInBbc().
std::set<G4LogicalVolume *> PHG4BbcDetector::m_SupportLogicalVolSet protected
Definition at line 55 of file PHG4BbcDetector.h.
View newest version in sPHENIX GitHub at line 55 of file PHG4BbcDetector.h
Referenced by ConstructMe(), and IsInBbc().
The documentation for this class was generated from the following files:
coresoftware/blob/master/simulation/g4simulation/g4detectors/PHG4BbcDetector.h
coresoftware/blob/master/simulation/g4simulation/g4detectors/PHG4BbcDetector.cc