Analysis Software: Acts::detail::grid_helper_impl< N > Struct Template Reference
Acts::detail::grid_helper_impl< N > Struct Template Reference
#include <acts/blob/sPHENIX/Core/include/Acts/Utilities/detail/grid_helper.hpp>
Static Public Member Functions
template<class... Axes>
static void getBinCenter (std::array< ActsScalar, sizeof...(Axes)> &center, const std::array< size_t, sizeof...(Axes)> &localIndices, const std::tuple< Axes...> &axes)
template<class... Axes>
static void getGlobalBin (const std::array< size_t, sizeof...(Axes)> &localBins, const std::tuple< Axes...> &axes, size_t &bin, size_t &area)
template<class Point , class... Axes>
static void getLocalBinIndices (const Point &point, const std::tuple< Axes...> &axes, std::array< size_t, sizeof...(Axes)> &indices)
template<class... Axes>
static void getLocalBinIndices (size_t &bin, const std::tuple< Axes...> &axes, size_t &area, std::array< size_t, sizeof...(Axes)> &indices)
template<class... Axes>
static void getLowerLeftBinEdge (std::array< ActsScalar, sizeof...(Axes)> &llEdge, const std::array< size_t, sizeof...(Axes)> &localIndices, const std::tuple< Axes...> &axes)
template<class... Axes>
static void getLowerLeftBinIndices (std::array< size_t, sizeof...(Axes)> &localIndices, const std::tuple< Axes...> &axes)
template<class... Axes>
static void getNBins (const std::tuple< Axes...> &axes, std::array< size_t, sizeof...(Axes)> &nBinsArray)
template<class... Axes>
static void getAxes (const std::tuple< Axes...> &axes, std::array< const IAxis *, sizeof...(Axes)> &axesArr)
template<class... Axes>
static void getUpperRightBinEdge (std::array< ActsScalar, sizeof...(Axes)> &urEdge, const std::array< size_t, sizeof...(Axes)> &localIndices, const std::tuple< Axes...> &axes)
template<class... Axes>
static void getUpperRightBinIndices (std::array< size_t, sizeof...(Axes)> &localIndices, const std::tuple< Axes...> &axes)
template<class... Axes>
static void getMin (const std::tuple< Axes...> &axes, std::array< ActsScalar, sizeof...(Axes)> &minArray)
template<class... Axes>
static void getMax (const std::tuple< Axes...> &axes, std::array< ActsScalar, sizeof...(Axes)> &maxArray)
template<class... Axes>
static void getWidth (const std::tuple< Axes...> &axes, std::array< ActsScalar, sizeof...(Axes)> &widthArray)
template<class Point , class... Axes>
static bool isInside (const Point &position, const std::tuple< Axes...> &axes)
template<class... Axes>
static void neighborHoodIndices (const std::array< size_t, sizeof...(Axes)> &localIndices, std::pair< int, int > sizes, const std::tuple< Axes...> &axes, std::array< NeighborHoodIndices, sizeof...(Axes)> &neighborIndices)
template<class... Axes>
static void neighborHoodIndices (const std::array< size_t, sizeof...(Axes)> &localIndices, std::array< std::pair< int, int >, sizeof...(Axes)> sizes, const std::tuple< Axes...> &axes, std::array< NeighborHoodIndices, sizeof...(Axes)> &neighborIndices)
template<class... Axes>
static void exteriorBinIndices (std::array< size_t, sizeof...(Axes)> &idx, std::array< bool, sizeof...(Axes)> isExterior, std::set< size_t > &combinations, const std::tuple< Axes...> &axes)
Detailed Description
template<size_t N>
struct Acts::detail::grid_helper_impl< N >
Definition at line 166 of file grid_helper.hpp.
View newest version in sPHENIX GitHub at line 166 of file grid_helper.hpp
Member Function Documentation
template<size_t N> template<class... Axes> static void Acts::detail::grid_helper_impl< N >::exteriorBinIndices (std::array< size_t, sizeof...(Axes)> & idx, std::array< bool, sizeof...(Axes)> isExterior, std::set< size_t > & combinations, const std::tuple< Axes...> & axes) inline static
Definition at line 316 of file grid_helper.hpp.
View newest version in sPHENIX GitHub at line 316 of file grid_helper.hpp
References Acts::detail::grid_helper_impl< N >::getNBins(), i, ambiguity_solver_full_chain::idx, and N.
Referenced by Acts::detail::grid_helper::exteriorBinIndices().
template<size_t N> template<class... Axes> static void Acts::detail::grid_helper_impl< N >::getAxes (const std::tuple< Axes...> & axes, std::array< const IAxis *, sizeof...(Axes)> & axesArr) inline static
Definition at line 234 of file grid_helper.hpp.
View newest version in sPHENIX GitHub at line 234 of file grid_helper.hpp
References N.
template<size_t N> template<class... Axes> static void Acts::detail::grid_helper_impl< N >::getBinCenter (std::array< ActsScalar, sizeof...(Axes)> & center, const std::array< size_t, sizeof...(Axes)> & localIndices, const std::tuple< Axes...> & axes) inline static
Definition at line 168 of file grid_helper.hpp.
View newest version in sPHENIX GitHub at line 168 of file grid_helper.hpp
References Acts::Experimental::detail::localIndices(), and N.
Referenced by Acts::detail::grid_helper_impl< 0u >::getBinCenter(), and Acts::detail::grid_helper::getBinCenter().
template<size_t N> template<class... Axes> static void Acts::detail::grid_helper_impl< N >::getGlobalBin (const std::array< size_t, sizeof...(Axes)> & localBins, const std::tuple< Axes...> & axes, size_t & bin, size_t & area) inline static
Definition at line 177 of file grid_helper.hpp.
View newest version in sPHENIX GitHub at line 177 of file grid_helper.hpp
References N.
Referenced by Acts::detail::grid_helper_impl< 0u >::exteriorBinIndices(), and Acts::detail::grid_helper::getGlobalBin().
template<size_t N> template<class Point , class... Axes> static void Acts::detail::grid_helper_impl< N >::getLocalBinIndices (const Point & point, const std::tuple< Axes...> & axes, std::array< size_t, sizeof...(Axes)> & indices) inline static
Definition at line 188 of file grid_helper.hpp.
View newest version in sPHENIX GitHub at line 188 of file grid_helper.hpp
References N.
Referenced by Acts::detail::grid_helper_impl< N >::getLocalBinIndices(), and Acts::detail::grid_helper::getLocalBinIndices().
template<size_t N> template<class... Axes> static void Acts::detail::grid_helper_impl< N >::getLocalBinIndices (size_t & bin, const std::tuple< Axes...> & axes, size_t & area, std::array< size_t, sizeof...(Axes)> & indices) inline static
Definition at line 197 of file grid_helper.hpp.
View newest version in sPHENIX GitHub at line 197 of file grid_helper.hpp
References Acts::detail::grid_helper_impl< N >::getLocalBinIndices(), and N.
template<size_t N> template<class... Axes> static void Acts::detail::grid_helper_impl< N >::getLowerLeftBinEdge (std::array< ActsScalar, sizeof...(Axes)> & llEdge, const std::array< size_t, sizeof...(Axes)> & localIndices, const std::tuple< Axes...> & axes) inline static
Definition at line 209 of file grid_helper.hpp.
View newest version in sPHENIX GitHub at line 209 of file grid_helper.hpp
References Acts::Experimental::detail::localIndices(), and N.
Referenced by Acts::detail::grid_helper::getLowerLeftBinEdge().
template<size_t N> template<class... Axes> static void Acts::detail::grid_helper_impl< N >::getLowerLeftBinIndices (std::array< size_t, sizeof...(Axes)> & localIndices, const std::tuple< Axes...> & axes) inline static
Definition at line 218 of file grid_helper.hpp.
View newest version in sPHENIX GitHub at line 218 of file grid_helper.hpp
References Acts::Experimental::detail::localIndices(), and N.
Referenced by Acts::detail::grid_helper::getLowerLeftBinIndices().
template<size_t N> template<class... Axes> static void Acts::detail::grid_helper_impl< N >::getMax (const std::tuple< Axes...> & axes, std::array< ActsScalar, sizeof...(Axes)> & maxArray) inline static
Definition at line 265 of file grid_helper.hpp.
View newest version in sPHENIX GitHub at line 265 of file grid_helper.hpp
References N.
Referenced by Acts::detail::grid_helper_impl< 0u >::getMax().
template<size_t N> template<class... Axes> static void Acts::detail::grid_helper_impl< N >::getMin (const std::tuple< Axes...> & axes, std::array< ActsScalar, sizeof...(Axes)> & minArray) inline static
Definition at line 258 of file grid_helper.hpp.
View newest version in sPHENIX GitHub at line 258 of file grid_helper.hpp
References N.
Referenced by Acts::detail::grid_helper_impl< 0u >::getMin().
template<size_t N> template<class... Axes> static void Acts::detail::grid_helper_impl< N >::getNBins (const std::tuple< Axes...> & axes, std::array< size_t, sizeof...(Axes)> & nBinsArray) inline static
Definition at line 226 of file grid_helper.hpp.
View newest version in sPHENIX GitHub at line 226 of file grid_helper.hpp
References N.
Referenced by Acts::detail::grid_helper_impl< N >::exteriorBinIndices(), Acts::detail::grid_helper_impl< 0u >::exteriorBinIndices(), and Acts::detail::grid_helper_impl< 0u >::getNBins().
template<size_t N> template<class... Axes> static void Acts::detail::grid_helper_impl< N >::getUpperRightBinEdge (std::array< ActsScalar, sizeof...(Axes)> & urEdge, const std::array< size_t, sizeof...(Axes)> & localIndices, const std::tuple< Axes...> & axes) inline static
Definition at line 241 of file grid_helper.hpp.
View newest version in sPHENIX GitHub at line 241 of file grid_helper.hpp
References Acts::Experimental::detail::localIndices(), and N.
Referenced by Acts::detail::grid_helper::getUpperRightBinEdge().
template<size_t N> template<class... Axes> static void Acts::detail::grid_helper_impl< N >::getUpperRightBinIndices (std::array< size_t, sizeof...(Axes)> & localIndices, const std::tuple< Axes...> & axes) inline static
Definition at line 250 of file grid_helper.hpp.
View newest version in sPHENIX GitHub at line 250 of file grid_helper.hpp
References Acts::Experimental::detail::localIndices(), and N.
Referenced by Acts::detail::grid_helper::getUpperRightBinIndices().
template<size_t N> template<class... Axes> static void Acts::detail::grid_helper_impl< N >::getWidth (const std::tuple< Axes...> & axes, std::array< ActsScalar, sizeof...(Axes)> & widthArray) inline static
Definition at line 272 of file grid_helper.hpp.
View newest version in sPHENIX GitHub at line 272 of file grid_helper.hpp
References N.
template<size_t N> template<class Point , class... Axes> static bool Acts::detail::grid_helper_impl< N >::isInside (const Point & position, const std::tuple< Axes...> & axes) inline static
Definition at line 279 of file grid_helper.hpp.
View newest version in sPHENIX GitHub at line 279 of file grid_helper.hpp
References N.
Referenced by Acts::detail::grid_helper_impl< 0u >::isInside(), and Acts::detail::grid_helper::isInside().
template<size_t N> template<class... Axes> static void Acts::detail::grid_helper_impl< N >::neighborHoodIndices (const std::array< size_t, sizeof...(Axes)> & localIndices, std::pair< int, int > sizes, const std::tuple< Axes...> & axes, std::array< NeighborHoodIndices, sizeof...(Axes)> & neighborIndices) inline static
Definition at line 285 of file grid_helper.hpp.
View newest version in sPHENIX GitHub at line 285 of file grid_helper.hpp
References Acts::Experimental::detail::localIndices(), and N.
Referenced by Acts::detail::grid_helper_impl< N >::neighborHoodIndices(), Acts::detail::grid_helper_impl< 0u >::neighborHoodIndices(), and Acts::detail::grid_helper::neighborHoodIndices().
template<size_t N> template<class... Axes> static void Acts::detail::grid_helper_impl< N >::neighborHoodIndices (const std::array< size_t, sizeof...(Axes)> & localIndices, std::array< std::pair< int, int >, sizeof...(Axes)> sizes, const std::tuple< Axes...> & axes, std::array< NeighborHoodIndices, sizeof...(Axes)> & neighborIndices) inline static
Definition at line 300 of file grid_helper.hpp.
View newest version in sPHENIX GitHub at line 300 of file grid_helper.hpp
References Acts::Experimental::detail::localIndices(), N, and Acts::detail::grid_helper_impl< N >::neighborHoodIndices().
The documentation for this struct was generated from the following file:
acts/blob/sPHENIX/Core/include/Acts/Utilities/detail/grid_helper.hpp