Analysis Software: RDBCBench Class Reference
RDBCBench Class Reference
Public Member Functions
RDBCBench (TSQLConnection *conn, Bool_t init)
~RDBCBench ()
void ReportDone ()
Private Member Functions
void StopThreads ()
void CreateDatabase ()
void DropDatabase ()
int DoOne (int bid, int tid, int aid, int delta)
int GetRandomID (int type)
int GetRandomInt (int lo, int hi)
Private Attributes
TSQLConnection * fConn
TList * fListOfClients
TStopwatch fTimer
Friends
class ClientThread
Detailed Description
Definition at line 63 of file RDBCbench.C.
View newest version in sPHENIX GitHub at line 63 of file RDBCbench.C
Constructor & Destructor Documentation
RDBCBench::RDBCBench (TSQLConnection * conn, Bool_t init)
Definition at line 136 of file RDBCbench.C.
View newest version in sPHENIX GitHub at line 136 of file RDBCbench.C
References ClientThread, CreateDatabase(), DropDatabase(), fConn, fListOfClients, fTimer, gClients, ClientThread::GetThread(), gTxnPerClient, i, printf(), and ClientThread::Start().
RDBCBench::~RDBCBench () inline
Definition at line 83 of file RDBCbench.C.
View newest version in sPHENIX GitHub at line 83 of file RDBCbench.C
References fConn, and fListOfClients.
Member Function Documentation
void RDBCBench::CreateDatabase () private
Definition at line 231 of file RDBCbench.C.
View newest version in sPHENIX GitHub at line 231 of file RDBCbench.C
References TSQL::ClearWarnings(), TSQLConnection::CreateStatement(), TSQLStatement::ExecuteUpdate(), fConn, i, naccounts, nbranches, ntellers, str, and tps.
Referenced by RDBCBench().
int RDBCBench::DoOne (int bid, int tid, int aid, int delta) private
Definition at line 333 of file RDBCbench.C.
View newest version in sPHENIX GitHub at line 333 of file RDBCbench.C
References TSQL::ClearWarnings(), TSQLConnection::CreateStatement(), TSQLStatement::ExecuteQuery(), TSQLStatement::ExecuteUpdate(), fConn, TSQLResultSet::GetInt(), TSQLResultSet::Next(), and TSQL::SetHandler().
Referenced by ClientThread::Run().
void RDBCBench::DropDatabase () private
Definition at line 307 of file RDBCbench.C.
View newest version in sPHENIX GitHub at line 307 of file RDBCbench.C
References TSQLConnection::CreateStatement(), TSQLStatement::ExecuteUpdate(), fConn, TSQL::SetHandler(), str, and TSQL::UnsetHandler().
Referenced by RDBCBench().
int RDBCBench::GetRandomID (int type) private
Definition at line 207 of file RDBCbench.C.
View newest version in sPHENIX GitHub at line 207 of file RDBCbench.C
References GetRandomInt(), kACCOUNT, kBRANCH, kTELLER, Acts::UnitConstants::min, naccounts, nbranches, ntellers, and tps.
Referenced by ClientThread::Run().
int RDBCBench::GetRandomInt (int lo, int hi) private
Definition at line 196 of file RDBCbench.C.
View newest version in sPHENIX GitHub at line 196 of file RDBCbench.C
Referenced by GetRandomID(), and ClientThread::Run().
void RDBCBench::ReportDone ()
Definition at line 162 of file RDBCbench.C.
View newest version in sPHENIX GitHub at line 162 of file RDBCbench.C
References failed_transactions, fTimer, gClients, printf(), StopThreads(), and transaction_count.
Referenced by ClientThread::Run().
void RDBCBench::StopThreads () private
Definition at line 188 of file RDBCbench.C.
View newest version in sPHENIX GitHub at line 188 of file RDBCbench.C
References fListOfClients.
Referenced by ReportDone().
Friends And Related Function Documentation
friend class ClientThread friend
Definition at line 65 of file RDBCbench.C.
View newest version in sPHENIX GitHub at line 65 of file RDBCbench.C
Referenced by RDBCBench().
Member Data Documentation
TSQLConnection* RDBCBench::fConn private
Definition at line 70 of file RDBCbench.C.
View newest version in sPHENIX GitHub at line 70 of file RDBCbench.C
Referenced by CreateDatabase(), DoOne(), DropDatabase(), RDBCBench(), and ~RDBCBench().
TList* RDBCBench::fListOfClients private
Definition at line 71 of file RDBCbench.C.
View newest version in sPHENIX GitHub at line 71 of file RDBCbench.C
Referenced by RDBCBench(), StopThreads(), and ~RDBCBench().
TStopwatch RDBCBench::fTimer private
Definition at line 72 of file RDBCbench.C.
View newest version in sPHENIX GitHub at line 72 of file RDBCbench.C
Referenced by RDBCBench(), and ReportDone().
The documentation for this class was generated from the following file:
RDBC/blob/master/macros/RDBCbench.C