Analysis Software: SvtxVertex_v1 Class Reference
SvtxVertex_v1 Class Reference
#include <coresoftware/blob/master/offline/packages/globalvertex/SvtxVertex_v1.h>
Public Member Functions
SvtxVertex_v1 ()
~SvtxVertex_v1 () override
void identify (std::ostream &os=std::cout) const override
void Reset () override
Clear Event.
int isValid () const override
isValid returns non zero if object contains vailid data
PHObject * CloneMe () const override
Virtual copy constructor.
unsigned int get_id () const override
void set_id (unsigned int id) override
float get_t0 () const override
void set_t0 (float t0) override
float get_t () const override
void set_t (float t0) override
float get_x () const override
void set_x (float x) override
float get_y () const override
void set_y (float y) override
float get_z () const override
void set_z (float z) override
float get_chisq () const override
void set_chisq (float chisq) override
unsigned int get_ndof () const override
void set_ndof (unsigned int ndof) override
float get_position (unsigned int coor) const override
void set_position (unsigned int coor, float xi) override
float get_error (unsigned int i, unsigned int j) const override
void set_error (unsigned int i, unsigned int j, float value) override
void clear_tracks () override
bool empty_tracks () override
size_t size_tracks () const override
void insert_track (unsigned int trackid) override
size_t erase_track (unsigned int trackid) override
ConstTrackIter begin_tracks () const override
ConstTrackIter find_track (unsigned int trackid) const override
ConstTrackIter end_tracks () const override
TrackIter begin_tracks () override
TrackIter find_track (unsigned int trackid) override
TrackIter end_tracks () override
Public Member Functions inherited from SvtxVertex
~SvtxVertex () override
Public Member Functions inherited from Vertex
~Vertex () override
void identify (std::ostream &os=std::cout) const override
PHObject * CloneMe () const override
Virtual copy constructor.
int isValid () const override
isValid returns non zero if object contains vailid data
virtual float get_t_err () const
virtual void set_t_err (float)
virtual unsigned int get_beam_crossing () const
virtual void set_beam_crossing (unsigned int)
virtual void set_bbc_ns (int, int, float, float)
virtual int get_bbc_npmt (int) const
virtual float get_z_err () const
virtual void set_z_err (float)
virtual float get_bbc_q (int) const
virtual float get_bbc_t (int) const
Public Member Functions inherited from PHObject
PHObject ()
ctor
~PHObject () override
dtor
virtual PHObject * clone () const final
PHObject * Clone (const char *newname="") const final
void Copy (TObject &object) const final
virtual int Integrate () const
virtual int Integrate (PHObject *)
virtual void CopyFrom (const PHObject *obj)
Private Member Functions
unsigned int covar_index (unsigned int i, unsigned int j) const
ClassDefOverride (SvtxVertex_v1, 1)
Private Attributes
unsigned int _id
float _t0
float _pos [3]
float _chisq
unsigned int _ndof
float _err [6]
std::set< unsigned int > _track_ids
Additional Inherited Members
Public Types inherited from Vertex
typedef std::set< unsigned int > TrackSet
typedef std::set< unsigned int >
::const_iterator ConstTrackIter
typedef std::set< unsigned int >
::iterator TrackIter
Protected Member Functions inherited from SvtxVertex
ClassDefOverride (SvtxVertex, 1)
Detailed Description
Definition at line 12 of file SvtxVertex_v1.h.
View newest version in sPHENIX GitHub at line 12 of file SvtxVertex_v1.h
Constructor & Destructor Documentation
SvtxVertex_v1::SvtxVertex_v1 ()
Definition at line 8 of file SvtxVertex_v1.cc.
View newest version in sPHENIX GitHub at line 8 of file SvtxVertex_v1.cc
References _pos, i, j, and set_error().
Referenced by CloneMe(), and Reset().
SvtxVertex_v1::~SvtxVertex_v1 () inline override
Definition at line 16 of file SvtxVertex_v1.h.
View newest version in sPHENIX GitHub at line 16 of file SvtxVertex_v1.h
Member Function Documentation
ConstTrackIter SvtxVertex_v1::begin_tracks () const inline override virtual
Reimplemented from SvtxVertex.
Definition at line 65 of file SvtxVertex_v1.h.
View newest version in sPHENIX GitHub at line 65 of file SvtxVertex_v1.h
References _track_ids.
Referenced by identify().
TrackIter SvtxVertex_v1::begin_tracks () inline override virtual
Reimplemented from SvtxVertex.
Definition at line 68 of file SvtxVertex_v1.h.
View newest version in sPHENIX GitHub at line 68 of file SvtxVertex_v1.h
References _track_ids.
SvtxVertex_v1::ClassDefOverride (SvtxVertex_v1 , 1) private
void SvtxVertex_v1::clear_tracks () inline override virtual
Reimplemented from SvtxVertex.
Definition at line 60 of file SvtxVertex_v1.h.
View newest version in sPHENIX GitHub at line 60 of file SvtxVertex_v1.h
References _track_ids.
PHObject* SvtxVertex_v1::CloneMe () const inline override virtual
Virtual copy constructor.
Reimplemented from SvtxVertex.
Definition at line 23 of file SvtxVertex_v1.h.
View newest version in sPHENIX GitHub at line 23 of file SvtxVertex_v1.h
References SvtxVertex_v1().
unsigned int SvtxVertex_v1::covar_index (unsigned int i, unsigned int j) const private
Definition at line 98 of file SvtxVertex_v1.cc.
View newest version in sPHENIX GitHub at line 98 of file SvtxVertex_v1.cc
References swap().
Referenced by get_error(), and set_error().
bool SvtxVertex_v1::empty_tracks () inline override virtual
Reimplemented from SvtxVertex.
Definition at line 61 of file SvtxVertex_v1.h.
View newest version in sPHENIX GitHub at line 61 of file SvtxVertex_v1.h
References _track_ids.
ConstTrackIter SvtxVertex_v1::end_tracks () const inline override virtual
Reimplemented from SvtxVertex.
Definition at line 67 of file SvtxVertex_v1.h.
View newest version in sPHENIX GitHub at line 67 of file SvtxVertex_v1.h
References _track_ids.
Referenced by identify().
TrackIter SvtxVertex_v1::end_tracks () inline override virtual
Reimplemented from SvtxVertex.
Definition at line 70 of file SvtxVertex_v1.h.
View newest version in sPHENIX GitHub at line 70 of file SvtxVertex_v1.h
References _track_ids.
size_t SvtxVertex_v1::erase_track (unsigned int trackid) inline override virtual
Reimplemented from SvtxVertex.
Definition at line 64 of file SvtxVertex_v1.h.
View newest version in sPHENIX GitHub at line 64 of file SvtxVertex_v1.h
References _track_ids.
ConstTrackIter SvtxVertex_v1::find_track (unsigned int trackid) const inline override virtual
Reimplemented from SvtxVertex.
Definition at line 66 of file SvtxVertex_v1.h.
View newest version in sPHENIX GitHub at line 66 of file SvtxVertex_v1.h
References _track_ids.
TrackIter SvtxVertex_v1::find_track (unsigned int trackid) inline override virtual
Reimplemented from SvtxVertex.
Definition at line 69 of file SvtxVertex_v1.h.
View newest version in sPHENIX GitHub at line 69 of file SvtxVertex_v1.h
References _track_ids.
float SvtxVertex_v1::get_chisq () const inline override virtual
Reimplemented from SvtxVertex.
Definition at line 45 of file SvtxVertex_v1.h.
View newest version in sPHENIX GitHub at line 45 of file SvtxVertex_v1.h
References _chisq.
Referenced by identify().
float SvtxVertex_v1::get_error (unsigned int i, unsigned int j) const override virtual
Reimplemented from SvtxVertex.
Definition at line 93 of file SvtxVertex_v1.cc.
View newest version in sPHENIX GitHub at line 93 of file SvtxVertex_v1.cc
References _err, and covar_index().
Referenced by identify(), and isValid().
unsigned int SvtxVertex_v1::get_id () const inline override virtual
Reimplemented from SvtxVertex.
Definition at line 27 of file SvtxVertex_v1.h.
View newest version in sPHENIX GitHub at line 27 of file SvtxVertex_v1.h
References _id.
Referenced by identify().
unsigned int SvtxVertex_v1::get_ndof () const inline override virtual
Reimplemented from SvtxVertex.
Definition at line 48 of file SvtxVertex_v1.h.
View newest version in sPHENIX GitHub at line 48 of file SvtxVertex_v1.h
References _ndof.
Referenced by identify().
float SvtxVertex_v1::get_position (unsigned int coor) const inline override virtual
Reimplemented from SvtxVertex.
Definition at line 51 of file SvtxVertex_v1.h.
View newest version in sPHENIX GitHub at line 51 of file SvtxVertex_v1.h
References _pos.
Referenced by PHGenFitTrkFitter::FillSvtxVertexMap(), and identify().
float SvtxVertex_v1::get_t () const inline override virtual
Reimplemented from SvtxVertex.
Definition at line 33 of file SvtxVertex_v1.h.
View newest version in sPHENIX GitHub at line 33 of file SvtxVertex_v1.h
References _t0.
Referenced by get_t0(), and identify().
float SvtxVertex_v1::get_t0 () const inline override virtual
Reimplemented from SvtxVertex.
Definition at line 30 of file SvtxVertex_v1.h.
View newest version in sPHENIX GitHub at line 30 of file SvtxVertex_v1.h
References get_t().
float SvtxVertex_v1::get_x () const inline override virtual
Reimplemented from SvtxVertex.
Definition at line 36 of file SvtxVertex_v1.h.
View newest version in sPHENIX GitHub at line 36 of file SvtxVertex_v1.h
References _pos.
float SvtxVertex_v1::get_y () const inline override virtual
Reimplemented from SvtxVertex.
Definition at line 39 of file SvtxVertex_v1.h.
View newest version in sPHENIX GitHub at line 39 of file SvtxVertex_v1.h
References _pos.
float SvtxVertex_v1::get_z () const inline override virtual
Reimplemented from SvtxVertex.
Definition at line 42 of file SvtxVertex_v1.h.
View newest version in sPHENIX GitHub at line 42 of file SvtxVertex_v1.h
References _pos.
void SvtxVertex_v1::identify (std::ostream & os = std::cout) const override virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from SvtxVertex.
Definition at line 27 of file SvtxVertex_v1.cc.
View newest version in sPHENIX GitHub at line 27 of file SvtxVertex_v1.cc
References begin_tracks(), end_tracks(), get_chisq(), get_error(), get_id(), get_ndof(), get_position(), and get_t().
void SvtxVertex_v1::insert_track (unsigned int trackid) inline override virtual
Reimplemented from SvtxVertex.
Definition at line 63 of file SvtxVertex_v1.h.
View newest version in sPHENIX GitHub at line 63 of file SvtxVertex_v1.h
References _track_ids.
Referenced by PHGenFitTrkFitter::FillSvtxVertexMap().
int SvtxVertex_v1::isValid () const override virtual
isValid returns non zero if object contains vailid data
Reimplemented from SvtxVertex.
Definition at line 65 of file SvtxVertex_v1.cc.
View newest version in sPHENIX GitHub at line 65 of file SvtxVertex_v1.cc
References _chisq, _id, _ndof, _pos, _t0, _track_ids, get_error(), i, and j.
void SvtxVertex_v1::Reset () inline override virtual
Clear Event.
Reimplemented from PHObject.
Definition at line 21 of file SvtxVertex_v1.h.
View newest version in sPHENIX GitHub at line 21 of file SvtxVertex_v1.h
References SvtxVertex_v1().
void SvtxVertex_v1::set_chisq (float chisq) inline override virtual
Reimplemented from SvtxVertex.
Definition at line 46 of file SvtxVertex_v1.h.
View newest version in sPHENIX GitHub at line 46 of file SvtxVertex_v1.h
References _chisq.
Referenced by PHGenFitTrkFitter::FillSvtxVertexMap().
void SvtxVertex_v1::set_error (unsigned int i, unsigned int j, float value) override virtual
Reimplemented from SvtxVertex.
Definition at line 87 of file SvtxVertex_v1.cc.
View newest version in sPHENIX GitHub at line 87 of file SvtxVertex_v1.cc
References _err, covar_index(), and value.
Referenced by PHGenFitTrkFitter::FillSvtxVertexMap(), and SvtxVertex_v1().
void SvtxVertex_v1::set_id (unsigned int id) inline override virtual
Reimplemented from SvtxVertex.
Definition at line 28 of file SvtxVertex_v1.h.
View newest version in sPHENIX GitHub at line 28 of file SvtxVertex_v1.h
References _id, and train_ambiguity_solver::id.
void SvtxVertex_v1::set_ndof (unsigned int ndof) inline override virtual
Reimplemented from SvtxVertex.
Definition at line 49 of file SvtxVertex_v1.h.
View newest version in sPHENIX GitHub at line 49 of file SvtxVertex_v1.h
References _ndof.
Referenced by PHGenFitTrkFitter::FillSvtxVertexMap().
void SvtxVertex_v1::set_position (unsigned int coor, float xi) inline override virtual
Reimplemented from SvtxVertex.
Definition at line 52 of file SvtxVertex_v1.h.
View newest version in sPHENIX GitHub at line 52 of file SvtxVertex_v1.h
References _pos.
Referenced by PHGenFitTrkFitter::FillSvtxVertexMap().
void SvtxVertex_v1::set_t (float t0) inline override virtual
Reimplemented from SvtxVertex.
Definition at line 34 of file SvtxVertex_v1.h.
View newest version in sPHENIX GitHub at line 34 of file SvtxVertex_v1.h
References _t0.
Referenced by set_t0().
void SvtxVertex_v1::set_t0 (float t0) inline override virtual
Reimplemented from SvtxVertex.
Definition at line 31 of file SvtxVertex_v1.h.
View newest version in sPHENIX GitHub at line 31 of file SvtxVertex_v1.h
References set_t().
void SvtxVertex_v1::set_x (float x) inline override virtual
Reimplemented from SvtxVertex.
Definition at line 37 of file SvtxVertex_v1.h.
View newest version in sPHENIX GitHub at line 37 of file SvtxVertex_v1.h
References _pos, and ambiguity_solver_full_chain::x.
void SvtxVertex_v1::set_y (float y) inline override virtual
Reimplemented from SvtxVertex.
Definition at line 40 of file SvtxVertex_v1.h.
View newest version in sPHENIX GitHub at line 40 of file SvtxVertex_v1.h
References _pos, and y.
void SvtxVertex_v1::set_z (float z) inline override virtual
Reimplemented from SvtxVertex.
Definition at line 43 of file SvtxVertex_v1.h.
View newest version in sPHENIX GitHub at line 43 of file SvtxVertex_v1.h
References _pos, and physmon_track_finding_ttbar::z.
size_t SvtxVertex_v1::size_tracks () const inline override virtual
Reimplemented from SvtxVertex.
Definition at line 62 of file SvtxVertex_v1.h.
View newest version in sPHENIX GitHub at line 62 of file SvtxVertex_v1.h
References _track_ids.
Member Data Documentation
float SvtxVertex_v1::_chisq private
Definition at line 78 of file SvtxVertex_v1.h.
View newest version in sPHENIX GitHub at line 78 of file SvtxVertex_v1.h
Referenced by get_chisq(), isValid(), and set_chisq().
float SvtxVertex_v1::_err[6] private
Definition at line 80 of file SvtxVertex_v1.h.
View newest version in sPHENIX GitHub at line 80 of file SvtxVertex_v1.h
Referenced by get_error(), and set_error().
unsigned int SvtxVertex_v1::_id private
Definition at line 75 of file SvtxVertex_v1.h.
View newest version in sPHENIX GitHub at line 75 of file SvtxVertex_v1.h
Referenced by get_id(), isValid(), and set_id().
unsigned int SvtxVertex_v1::_ndof private
Definition at line 79 of file SvtxVertex_v1.h.
View newest version in sPHENIX GitHub at line 79 of file SvtxVertex_v1.h
Referenced by get_ndof(), isValid(), and set_ndof().
float SvtxVertex_v1::_pos[3] private
Definition at line 77 of file SvtxVertex_v1.h.
View newest version in sPHENIX GitHub at line 77 of file SvtxVertex_v1.h
Referenced by get_position(), get_x(), get_y(), get_z(), isValid(), set_position(), set_x(), set_y(), set_z(), and SvtxVertex_v1().
float SvtxVertex_v1::_t0 private
Definition at line 76 of file SvtxVertex_v1.h.
View newest version in sPHENIX GitHub at line 76 of file SvtxVertex_v1.h
Referenced by get_t(), isValid(), and set_t().
std::set<unsigned int> SvtxVertex_v1::_track_ids private
Definition at line 81 of file SvtxVertex_v1.h.
View newest version in sPHENIX GitHub at line 81 of file SvtxVertex_v1.h
Referenced by begin_tracks(), clear_tracks(), empty_tracks(), end_tracks(), erase_track(), find_track(), insert_track(), isValid(), and size_tracks().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/globalvertex/SvtxVertex_v1.h
coresoftware/blob/master/offline/packages/globalvertex/SvtxVertex_v1.cc