Analysis Software: Acts::ConeLayer Class Reference
Acts::ConeLayer Class Reference
#include <acts/blob/sPHENIX/Core/include/Acts/Geometry/ConeLayer.hpp>
Public Member Functions
ConeLayer ()=delete
ConeLayer (const ConeLayer &cla)=delete
~ConeLayer () override=default
ConeLayer & operator= (const ConeLayer &)=delete
const ConeSurface & surfaceRepresentation () const override
Transforms the layer into a Surface representation for extrapolation.
ConeSurface & surfaceRepresentation () override
Public Member Functions inherited from Acts::ConeSurface
~ConeSurface () override=default
ConeSurface ()=delete
ConeSurface & operator= (const ConeSurface &other)
Vector3 binningPosition (const GeometryContext &gctx, BinningValue bValue) const final
SurfaceType type () const override
Return the surface type.
RotationMatrix3 referenceFrame (const GeometryContext &gctx, const Vector3 &position, const Vector3 &direction) const final
Vector3 normal (const GeometryContext &gctx, const Vector2 &lposition) const final
Vector3 normal (const GeometryContext &gctx, const Vector3 &position) const final
virtual Vector3 rotSymmetryAxis (const GeometryContext &gctx) const
const ConeBounds & bounds () const final
This method returns the ConeBounds by reference.
Vector3 localToGlobal (const GeometryContext &gctx, const Vector2 &lposition, const Vector3 &direction) const final
Result< Vector2 > globalToLocal (const GeometryContext &gctx, const Vector3 &position, const Vector3 &direction, double tolerance=s_onSurfaceTolerance) const final
SurfaceMultiIntersection intersect (const GeometryContext &gctx, const Vector3 &position, const Vector3 &direction, const BoundaryCheck &bcheck=false, double tolerance=s_onSurfaceTolerance) const final
double pathCorrection (const GeometryContext &gctx, const Vector3 &position, const Vector3 &direction) const final
Polyhedron polyhedronRepresentation (const GeometryContext &gctx, size_t lseg) const override
std::string name () const override
Return properly formatted class name for screen output.
AlignmentToPathMatrix alignmentToPathDerivative (const GeometryContext &gctx, const FreeVector &parameters) const final
ActsMatrix< 2, 3 > localCartesianToBoundLocalDerivative (const GeometryContext &gctx, const Vector3 &position) const final
Public Member Functions inherited from Acts::Surface
virtual ~Surface ()
std::shared_ptr< Surface > getSharedPtr ()
std::shared_ptr< const Surface > getSharedPtr () const
Surface & operator= (const Surface &other)
virtual bool operator== (const Surface &other) const
virtual bool operator!= (const Surface &sf) const
virtual const Transform3 & transform (const GeometryContext &gctx) const
virtual Vector3 center (const GeometryContext &gctx) const
virtual Vector3 normal (const GeometryContext &gctx) const
const DetectorElementBase * associatedDetectorElement () const
const Layer * associatedLayer () const
void associateLayer (const Layer &lay)
const ISurfaceMaterial * surfaceMaterial () const
const std::shared_ptr< const
ISurfaceMaterial > & surfaceMaterialSharedPtr () const
void assignDetectorElement (const DetectorElementBase &detelement)
void assignSurfaceMaterial (std::shared_ptr< const ISurfaceMaterial > material)
bool isOnSurface (const GeometryContext &gctx, const Vector3 &position, const Vector3 &direction, const BoundaryCheck &bcheck=true) const
virtual bool insideBounds (const Vector2 &lposition, const BoundaryCheck &bcheck=true) const
virtual BoundToFreeMatrix boundToFreeJacobian (const GeometryContext &gctx, const BoundVector &boundParams) const
virtual FreeToBoundMatrix freeToBoundJacobian (const GeometryContext &gctx, const FreeVector &parameters) const
virtual FreeToPathMatrix freeToPathDerivative (const GeometryContext &gctx, const FreeVector &parameters) const
virtual std::ostream & toStream (const GeometryContext &gctx, std::ostream &sl) const
std::string toString (const GeometryContext &gctx) const
AlignmentToBoundMatrix alignmentToBoundDerivative (const GeometryContext &gctx, const FreeVector &parameters, const FreeVector &pathDerivative) const
Public Member Functions inherited from Acts::GeometryObject
GeometryObject ()=default
Defaulted constructor.
GeometryObject (const GeometryObject &)=default
Defaulted copy constructor.
GeometryObject (const GeometryIdentifier &geometryId)
GeometryObject & operator= (const GeometryObject &geometryId)
const GeometryIdentifier & geometryId () const
virtual double binningPositionValue (const GeometryContext &gctx, BinningValue bValue) const
void assignGeometryId (const GeometryIdentifier &geometryId)
Public Member Functions inherited from Acts::Layer
Layer ()=delete
Default Constructor - deleted.
Layer (const Layer &)=delete
Copy Constructor - deleted.
virtual ~Layer ()=default
Destructor.
Layer & operator= (const Layer &layer)=delete
const SurfaceArray * surfaceArray () const
Return the entire SurfaceArray, returns a nullptr if no SurfaceArray.
SurfaceArray * surfaceArray ()
Non-const version.
double thickness () const
virtual bool isOnLayer (const GeometryContext &gctx, const Vector3 &position, const BoundaryCheck &bcheck=true) const
const ApproachDescriptor * approachDescriptor () const
Return method for the approach descriptor, can be nullptr.
ApproachDescriptor * approachDescriptor ()
Non-const version of the approach descriptor.
template<typename options_t >
bool resolve (const options_t &options) const
virtual bool resolve (bool resolveSensitive, bool resolveMaterial, bool resolvePassive) const
boost::container::small_vector
< SurfaceIntersection, 10 > compatibleSurfaces (const GeometryContext &gctx, const Vector3 &position, const Vector3 &direction, const NavigationOptions< Surface > &options) const
Decompose Layer into (compatible) surfaces.
SurfaceIntersection surfaceOnApproach (const GeometryContext &gctx, const Vector3 &position, const Vector3 &direction, const NavigationOptions< Layer > &options) const
const Layer * nextLayer (const GeometryContext &gctx, const Vector3 &position, const Vector3 &direction) const
const TrackingVolume * trackingVolume () const
const AbstractVolume * representingVolume () const
LayerType layerType () const
return the LayerType
Static Public Member Functions
static MutableLayerPtr create (const Transform3 &transform, std::shared_ptr< const ConeBounds > cbounds, std::unique_ptr< SurfaceArray > surfaceArray, double thickness=0., std::unique_ptr< ApproachDescriptor > ad=nullptr, LayerType laytyp=Acts::active)
Protected Member Functions
ConeLayer (const Transform3 &transform, std::shared_ptr< const ConeBounds > cbounds, std::unique_ptr< SurfaceArray > surfaceArray, double thickness=0., std::unique_ptr< ApproachDescriptor > ade=nullptr, LayerType laytyp=Acts::active)
ConeLayer (const ConeLayer &cla, const Transform3 &shift)
Protected Member Functions inherited from Acts::ConeSurface
ConeSurface (const Transform3 &transform, double alpha, bool symmetric=false)
ConeSurface (const Transform3 &transform, double alpha, double zmin, double zmax, double halfPhi=M_PI)
ConeSurface (const Transform3 &transform, std::shared_ptr< const ConeBounds > cbounds)
ConeSurface (const ConeSurface &other)
ConeSurface (const GeometryContext &gctx, const ConeSurface &other, const Transform3 &shift)
Protected Member Functions inherited from Acts::Surface
Surface (const Transform3 &transform=Transform3::Identity())
Surface (const Surface &other)
Surface (const DetectorElementBase &detelement)
Surface (const GeometryContext &gctx, const Surface &other, const Transform3 &shift)
Protected Member Functions inherited from Acts::Layer
Layer (std::unique_ptr< SurfaceArray > surfaceArray, double thickness=0., std::unique_ptr< ApproachDescriptor > ades=nullptr, LayerType laytyp=passive)
void encloseTrackingVolume (const TrackingVolume &tvol)
Additional Inherited Members
Public Types inherited from Acts::Surface
enum SurfaceType {
Cone = 0, Cylinder = 1, Disc = 2, Perigee = 3,
Plane = 4, Straw = 5, Curvilinear = 6, Other = 7
}
Static Public Attributes inherited from Acts::Surface
static std::array< std::string,
SurfaceType::Other > s_surfaceTypeNames
Helper strings for screen output.
Protected Attributes inherited from Acts::ConeSurface
std::shared_ptr< const ConeBounds > m_bounds
bounds (shared)
Protected Attributes inherited from Acts::Layer
NextLayers m_nextLayers
the previous Layer according to BinGenUtils
const BinUtility * m_nextLayerUtility = nullptr
std::unique_ptr< const
SurfaceArray > m_surfaceArray = nullptr
double m_layerThickness = 0.
Thickness of the Layer.
std::unique_ptr< const
ApproachDescriptor > m_approachDescriptor = nullptr
const TrackingVolume * m_trackingVolume = nullptr
the enclosing TrackingVolume
std::unique_ptr< AbstractVolume > m_representingVolume = nullptr
LayerType m_layerType
make a passive/active either way
int m_ssRepresentingSurface = 0
sub structure indication
int m_ssSensitiveSurfaces = 0
int m_ssApproachSurfaces = 0
Detailed Description
Class to describe a conical detector layer for tracking, it inhertis from both, Layer base class and ConeSurface class
Definition at line 29 of file ConeLayer.hpp.
View newest version in sPHENIX GitHub at line 29 of file ConeLayer.hpp
Constructor & Destructor Documentation
Acts::ConeLayer::ConeLayer () delete
Referenced by create().
Acts::ConeLayer::ConeLayer (const ConeLayer & cla) delete
Acts::ConeLayer::~ConeLayer () override default
Acts::ConeLayer::ConeLayer (const Transform3 & transform, std::shared_ptr< const ConeBounds > cbounds, std::unique_ptr< SurfaceArray > surfaceArray, double thickness = 0., std::unique_ptr< ApproachDescriptor > ade = nullptr, LayerType laytyp = Acts::active) protected
Private constructor with arguments
Parameters
transform is the 3D transform that positions the layer in 3D frame
cbounds is the conical bound description
surfaceArray is the array of sensitive surfaces
thickness is the layer thickness along the normal axis
ade is the approach descriptor for navigation towards the layer
laytyp is the layer type
Definition at line 17 of file ConeLayer.cpp.
View newest version in sPHENIX GitHub at line 17 of file ConeLayer.cpp
Acts::ConeLayer::ConeLayer (const ConeLayer & cla, const Transform3 & shift) protected
Private copy constructor with shift, called by create(args*)
Parameters
cla is the source clone layer
shift is the additional shift applied after copying
Member Function Documentation
static MutableLayerPtr Acts::ConeLayer::create (const Transform3 & transform, std::shared_ptr< const ConeBounds > cbounds, std::unique_ptr< SurfaceArray > surfaceArray, double thickness = 0., std::unique_ptr< ApproachDescriptor > ad = nullptr, LayerType laytyp = Acts::active) inline static
Factory for shared layer
Parameters
transform is the 3D transform that positions the layer in 3D frame
cbounds is the conical bound description
surfaceArray is the array of sensitive surfaces
thickness is the layer thickness along the normal axis
ad is the approach descriptor for navigation towards the layer
laytyp is the layer type
Returns
is a shared pointer to a layer
Definition at line 43 of file ConeLayer.hpp.
View newest version in sPHENIX GitHub at line 43 of file ConeLayer.hpp
References ConeLayer(), testing::internal::move(), and Acts::Layer::thickness().
Referenced by Acts::Test::Layers::BOOST_AUTO_TEST_CASE().
ConeLayer& Acts::ConeLayer::operator= (const ConeLayer &) delete
const Acts::ConeSurface & Acts::ConeLayer::surfaceRepresentation () const override virtual
Transforms the layer into a Surface representation for extrapolation.
Implements Acts::Layer.
Definition at line 26 of file ConeLayer.cpp.
View newest version in sPHENIX GitHub at line 26 of file ConeLayer.cpp
Acts::ConeSurface & Acts::ConeLayer::surfaceRepresentation () override virtual
Implements Acts::Layer.
Definition at line 30 of file ConeLayer.cpp.
View newest version in sPHENIX GitHub at line 30 of file ConeLayer.cpp
The documentation for this class was generated from the following files:
acts/blob/sPHENIX/Core/include/Acts/Geometry/ConeLayer.hpp
acts/blob/sPHENIX/Core/src/Geometry/ConeLayer.cpp