Analysis Software: OnlMonServer Class Reference
OnlMonServer Class Reference
#include <OnlMon/blob/main/onlmonserver/OnlMonServer.h>
Public Member Functions
~OnlMonServer () override
OnlMonServer (const OnlMonServer &)=delete
OnlMonServer & operator= (const OnlMonServer &)=delete
void registerHisto (const std::string &monitorname, const std::string &hname, TH1 *h1d, const int replace=0)
void registerHisto (const OnlMon *monitor, TH1 *h1d)
void registerCommonHisto (TH1 *h1d)
TH1 * getHisto (const std::string &subsys, const std::string &hname) const
TH1 * getCommonHisto (const std::string &hname) const
TH1 * getHisto (const unsigned int ihisto) const
const std::string getHistoName (const unsigned int ihisto) const
unsigned int nHistos () const
int RunNumber () const
void RunNumber (const int irun)
int EventNumber () const
void EventNumber (const int iev)
int PortNumber () const
void PortNumber (const int i)
void Print (const std::string &what="ALL", std::ostream &os=std::cout) const
void PrintFile (const std::string &fname) const
void InitAll ()
void registerMonitor (OnlMon *Monitor)
OnlMon * getMonitor (const std::string &name)
void dumpHistos (const std::string &filename)
int process_event (Event *)
int Reset ()
int BeginRun (const int runno)
int EndRun (const int runno)
int WriteHistoFile ()
uint64_t CurrentTicks () const
void CurrentTicks (const uint64_t ival)
uint64_t BorTicks () const
void BorTicks (const uint64_t ival)
int BadEvents () const
void AddBadEvent ()
void BadEvents (const int ibad)
int WriteLogFile (const std::string &name, const std::string &msg) const
int IsPacketActive (const unsigned int ipkt)
int SetSubsystemStatus (OnlMon *Monitor, const int status)
int SetSubsystemRunStatus (OnlMon *Monitor, const int status)
int LookAtMe (OnlMon *Monitor, const int level, const std::string &message)
std::string GetRunType () const
int send_message (const OnlMon *Monitor, const int msgsource, const int severity, const std::string &err_message, const int msgtype) const
void SetThreadId (const pthread_t &id)
void clearactivepackets ()
int isStandaloneRun () const
int isCosmicRun () const
int run_empty (const int nevents)
std::map< std::string,
std::map< std::string, TH1 * >
>::const_iterator monibegin ()
std::map< std::string,
std::map< std::string, TH1 * >
>::const_iterator moniend ()
std::vector< OnlMon * >
::const_iterator monitor_vec_begin ()
std::vector< OnlMon * >
::const_iterator monitor_vec_end ()
Public Member Functions inherited from OnlMonBase
OnlMonBase (const std::string &name="NONE")
virtual ~OnlMonBase ()
const std::string Name () const
void Name (const std::string &name)
virtual void Verbosity (const int i)
virtual int Verbosity () const
Static Public Member Functions
static OnlMonServer * instance ()
Private Member Functions
OnlMonServer (const std::string &name="OnlMonServer")
int send_message (const int severity, const std::string &err_message, const int msgtype) const
int CacheRunDB (const int runno)
void registerHisto (const std::string &hname, TH1 *h1d, const int replace=0)
Private Attributes
int runnumber = -1
int eventnumber = 0
int portnumber = OnlMonDefs::MONIPORT
int badevents = 0
uint64_t currentticks = 0
uint64_t borticks = 0
int activepacketsinit = 0
unsigned int scaledtrigmask = 0xFFFFFFFF
int scaledtrigmask_used = 0
int standalone = 0
int cosmicrun = 0
std::string TriggerConfig = "UNKNOWN"
std::string RunType = "UNKNOWN"
TH1 * serverrunning = nullptr
OnlMonStatusDB * statusDB = nullptr
OnlMonStatusDB * RunStatusDB = nullptr
std::map< const std::string,
TH1 * > CommonHistoMap
std::vector< OnlMon * > MonitorList
std::set< unsigned int > activepackets
std::map< std::string,
MessageSystem * > MsgSystem
std::map< std::string,
std::map< std::string, TH1 * > > MonitorHistoSet
pthread_mutex_t mutex
pthread_t serverthreadid = 0
Static Private Attributes
static OnlMonServer * __instance = nullptr
Additional Inherited Members
Protected Attributes inherited from OnlMonBase
std::string ThisName
int verbosity = 0
Detailed Description
Definition at line 23 of file OnlMonServer.h.
View newest version in sPHENIX GitHub at line 23 of file OnlMonServer.h
Constructor & Destructor Documentation
OnlMonServer::~OnlMonServer () override
Definition at line 64 of file OnlMonServer.cc.
View newest version in sPHENIX GitHub at line 64 of file OnlMonServer.cc
References CommonHistoMap, MonitorHistoSet, MonitorList, MsgSystem, mutex, RunStatusDB, serverrunning, serverthreadid, statusDB, and OnlMonBase::Verbosity().
OnlMonServer::OnlMonServer (const OnlMonServer &) explicit delete
Referenced by instance().
OnlMonServer::OnlMonServer (const std::string & name = "OnlMonServer") private
Definition at line 51 of file OnlMonServer.cc.
View newest version in sPHENIX GitHub at line 51 of file OnlMonServer.cc
References InitAll(), MsgSystem, mutex, RunStatusDB, statusDB, and OnlMonBase::ThisName.
Member Function Documentation
void OnlMonServer::AddBadEvent () inline
Definition at line 68 of file OnlMonServer.h.
View newest version in sPHENIX GitHub at line 68 of file OnlMonServer.h
References badevents.
Referenced by process_event().
int OnlMonServer::BadEvents () const inline
Definition at line 67 of file OnlMonServer.h.
View newest version in sPHENIX GitHub at line 67 of file OnlMonServer.h
References badevents.
Referenced by process_event().
void OnlMonServer::BadEvents (const int ibad) inline
Definition at line 69 of file OnlMonServer.h.
View newest version in sPHENIX GitHub at line 69 of file OnlMonServer.h
References badevents.
int OnlMonServer::BeginRun (const int runno)
Definition at line 443 of file OnlMonServer.cc.
View newest version in sPHENIX GitHub at line 443 of file OnlMonServer.cc
References activepacketsinit, CacheRunDB(), i, MonitorList, and printf().
Referenced by process_event().
uint64_t OnlMonServer::BorTicks () const inline
Definition at line 64 of file OnlMonServer.h.
View newest version in sPHENIX GitHub at line 64 of file OnlMonServer.h
References borticks.
Referenced by process_event().
void OnlMonServer::BorTicks (const uint64_t ival) inline
Definition at line 65 of file OnlMonServer.h.
View newest version in sPHENIX GitHub at line 65 of file OnlMonServer.h
References borticks.
int OnlMonServer::CacheRunDB (const int runno) private
Definition at line 642 of file OnlMonServer.cc.
View newest version in sPHENIX GitHub at line 642 of file OnlMonServer.cc
References borticks, runCondor_beamspot::cmd, con, cosmicrun, odbc::Connection::createStatement(), Acts::UnitConstants::e, odbc::Statement::executeQuery(), odbc::DriverManager::getConnection(), odbc::ResultSet::getInt(), odbc::SQLException::getMessage(), odbc::ResultSet::getString(), odbc::ResultSet::next(), printf(), RunType, standalone, TriggerConfig, and OnlMonBase::verbosity.
Referenced by BeginRun().
void OnlMonServer::clearactivepackets () inline
Definition at line 91 of file OnlMonServer.h.
View newest version in sPHENIX GitHub at line 91 of file OnlMonServer.h
References activepackets.
uint64_t OnlMonServer::CurrentTicks () const inline
Definition at line 62 of file OnlMonServer.h.
View newest version in sPHENIX GitHub at line 62 of file OnlMonServer.h
References currentticks.
Referenced by OnlMonDB::DBcommit(), MyMon::process_event(), process_event(), and WriteLogFile().
void OnlMonServer::CurrentTicks (const uint64_t ival) inline
Definition at line 63 of file OnlMonServer.h.
View newest version in sPHENIX GitHub at line 63 of file OnlMonServer.h
References currentticks.
void OnlMonServer::dumpHistos (const std::string & filename)
Definition at line 130 of file OnlMonServer.cc.
View newest version in sPHENIX GitHub at line 130 of file OnlMonServer.cc
References MonitorHistoSet.
int OnlMonServer::EndRun (const int runno)
Definition at line 463 of file OnlMonServer.cc.
View newest version in sPHENIX GitHub at line 463 of file OnlMonServer.cc
References i, and MonitorList.
Referenced by process_event(), and start_server().
int OnlMonServer::EventNumber () const inline
Definition at line 44 of file OnlMonServer.h.
View newest version in sPHENIX GitHub at line 44 of file OnlMonServer.h
References eventnumber.
Referenced by process_event().
void OnlMonServer::EventNumber (const int iev) inline
Definition at line 45 of file OnlMonServer.h.
View newest version in sPHENIX GitHub at line 45 of file OnlMonServer.h
References eventnumber.
TH1 * OnlMonServer::getCommonHisto (const std::string & hname) const
Definition at line 366 of file OnlMonServer.cc.
View newest version in sPHENIX GitHub at line 366 of file OnlMonServer.cc
References CommonHistoMap, TauVsDIS_MachineLearning_Differentiation::msg, MSG_SEV_ERROR, Print(), and send_message().
Referenced by OnlMon::InitCommon().
TH1 * OnlMonServer::getHisto (const std::string & subsys, const std::string & hname) const
Definition at line 342 of file OnlMonServer.cc.
View newest version in sPHENIX GitHub at line 342 of file OnlMonServer.cc
References MonitorHistoSet, TauVsDIS_MachineLearning_Differentiation::msg, MSG_SEV_ERROR, Print(), send_message(), and OnlMonBase::Verbosity().
Referenced by handleconnection().
TH1 * OnlMonServer::getHisto (const unsigned int ihisto) const
Definition at line 284 of file OnlMonServer.cc.
View newest version in sPHENIX GitHub at line 284 of file OnlMonServer.cc
References CommonHistoMap, i, TauVsDIS_MachineLearning_Differentiation::msg, MSG_SEV_ERROR, MSG_SEV_INFORMATIONAL, send_message(), size, and OnlMonBase::Verbosity().
const std::string OnlMonServer::getHistoName (const unsigned int ihisto) const
Definition at line 314 of file OnlMonServer.cc.
View newest version in sPHENIX GitHub at line 314 of file OnlMonServer.cc
References CommonHistoMap, i, TauVsDIS_MachineLearning_Differentiation::msg, MSG_SEV_ERROR, MSG_SEV_INFORMATIONAL, send_message(), size, and OnlMonBase::verbosity.
OnlMon * OnlMonServer::getMonitor (const std::string & name)
Definition at line 249 of file OnlMonServer.cc.
View newest version in sPHENIX GitHub at line 249 of file OnlMonServer.cc
References MonitorList.
std::string OnlMonServer::GetRunType () const inline
Definition at line 79 of file OnlMonServer.h.
View newest version in sPHENIX GitHub at line 79 of file OnlMonServer.h
References RunType.
Referenced by SetSubsystemRunStatus(), and SetSubsystemStatus().
void OnlMonServer::InitAll ()
Definition at line 117 of file OnlMonServer.cc.
View newest version in sPHENIX GitHub at line 117 of file OnlMonServer.cc
References TauVsDIS_MachineLearning_Differentiation::msg, MSG_SEV_FATAL, send_message(), and serverrunning.
Referenced by OnlMonServer().
OnlMonServer * OnlMonServer::instance () static
Definition at line 41 of file OnlMonServer.cc.
View newest version in sPHENIX GitHub at line 41 of file OnlMonServer.cc
References __instance, and OnlMonServer().
Referenced by CleanUpServer(), OnlMonDB::DBcommit(), handleconnection(), LL1Mon::Init(), DaqMon::Init(), MyMon::Init(), PktSizeMon::Init(), BbcMon::Init(), SepdMon::Init(), HcalMon::Init(), ZdcMon::Init(), CemcMon::Init(), TpcMon::Init(), TpotMon::Init(), InttMon::Init(), MvtxMon::Init(), pinit(), MyMon::process_event(), PktSizeMon::process_event(), BbcMon::process_event(), MvtxMon::process_event(), process_event(), PktSizeMon::putmapinhisto(), PktSizeMon::Reset(), run_bbc_server(), run_cemc_server(), run_cemc_server_SEB00(), run_cemc_server_SEB01(), run_daq_server(), run_example_server0(), run_example_server1(), run_hcal_server(), run_intt_server(), run_ll1_server(), run_mvtx_server(), run_pktsize_server(), run_sepd_server(), run_tpc_server(), run_tpot_server(), run_zdc_server(), MessageSystem::send_message(), server(), OnlMon::SetStatus(), start_server(), and PktSizeMon::UpdateDB().
int OnlMonServer::isCosmicRun () const inline
Definition at line 94 of file OnlMonServer.h.
View newest version in sPHENIX GitHub at line 94 of file OnlMonServer.h
References cosmicrun.
int OnlMonServer::IsPacketActive (const unsigned int ipkt)
int OnlMonServer::isStandaloneRun () const inline
Definition at line 93 of file OnlMonServer.h.
View newest version in sPHENIX GitHub at line 93 of file OnlMonServer.h
References standalone.
int OnlMonServer::LookAtMe (OnlMon * Monitor, const int level, const std::string & message)
Definition at line 763 of file OnlMonServer.cc.
View newest version in sPHENIX GitHub at line 763 of file OnlMonServer.cc
References OnlMonBase::Name().
std::map<std::string, std::map<std::string, TH1 *> >::const_iterator OnlMonServer::monibegin () inline
Definition at line 97 of file OnlMonServer.h.
View newest version in sPHENIX GitHub at line 97 of file OnlMonServer.h
References MonitorHistoSet.
Referenced by handleconnection().
std::map<std::string, std::map<std::string, TH1 *> >::const_iterator OnlMonServer::moniend () inline
Definition at line 98 of file OnlMonServer.h.
View newest version in sPHENIX GitHub at line 98 of file OnlMonServer.h
References MonitorHistoSet.
Referenced by handleconnection().
std::vector<OnlMon *>::const_iterator OnlMonServer::monitor_vec_begin () inline
Definition at line 99 of file OnlMonServer.h.
View newest version in sPHENIX GitHub at line 99 of file OnlMonServer.h
References MonitorList.
Referenced by handleconnection().
std::vector<OnlMon *>::const_iterator OnlMonServer::monitor_vec_end () inline
Definition at line 100 of file OnlMonServer.h.
View newest version in sPHENIX GitHub at line 100 of file OnlMonServer.h
References MonitorList.
Referenced by handleconnection().
unsigned int OnlMonServer::nHistos () const inline
Definition at line 41 of file OnlMonServer.h.
View newest version in sPHENIX GitHub at line 41 of file OnlMonServer.h
References CommonHistoMap.
Referenced by handleconnection().
OnlMonServer& OnlMonServer::operator= (const OnlMonServer &) delete
int OnlMonServer::PortNumber () const inline
Definition at line 46 of file OnlMonServer.h.
View newest version in sPHENIX GitHub at line 46 of file OnlMonServer.h
References portnumber.
Referenced by Print(), and server().
void OnlMonServer::PortNumber (const int i) inline
Definition at line 47 of file OnlMonServer.h.
View newest version in sPHENIX GitHub at line 47 of file OnlMonServer.h
References i, and portnumber.
void OnlMonServer::Print (const std::string & what = "ALL", std::ostream & os = std::cout) const
Definition at line 474 of file OnlMonServer.cc.
View newest version in sPHENIX GitHub at line 474 of file OnlMonServer.cc
References activepackets, CommonHistoMap, MonitorHistoSet, MonitorList, and PortNumber().
Referenced by getCommonHisto(), getHisto(), and PrintFile().
void OnlMonServer::PrintFile (const std::string & fname) const
Definition at line 532 of file OnlMonServer.cc.
View newest version in sPHENIX GitHub at line 532 of file OnlMonServer.cc
References fout, and Print().
int OnlMonServer::process_event (Event * evt)
Definition at line 396 of file OnlMonServer.cc.
View newest version in sPHENIX GitHub at line 396 of file OnlMonServer.cc
References i, and MonitorList.
Referenced by process_event(), and run_empty().
void OnlMonServer::registerCommonHisto (TH1 * h1d)
Definition at line 147 of file OnlMonServer.cc.
View newest version in sPHENIX GitHub at line 147 of file OnlMonServer.cc
References CommonHistoMap, and h1d.
Referenced by pinit().
void OnlMonServer::registerHisto (const std::string & monitorname, const std::string & hname, TH1 * h1d, const int replace = 0)
Definition at line 159 of file OnlMonServer.cc.
View newest version in sPHENIX GitHub at line 159 of file OnlMonServer.cc
References h1d, and MonitorHistoSet.
Referenced by DaqMon::Init(), LL1Mon::Init(), MyMon::Init(), PktSizeMon::Init(), BbcMon::Init(), SepdMon::Init(), ZdcMon::Init(), CemcMon::Init(), HcalMon::Init(), TpcMon::Init(), InttMon::Init(), MvtxMon::Init(), OnlMon::InitCommon(), PktSizeMon::putmapinhisto(), registerHisto(), and PktSizeMon::Reset().
void OnlMonServer::registerHisto (const OnlMon * monitor, TH1 * h1d)
Definition at line 153 of file OnlMonServer.cc.
View newest version in sPHENIX GitHub at line 153 of file OnlMonServer.cc
References h1d, OnlMonBase::Name(), and registerHisto().
void OnlMonServer::registerHisto (const std::string & hname, TH1 * h1d, const int replace = 0) private
Definition at line 196 of file OnlMonServer.cc.
View newest version in sPHENIX GitHub at line 196 of file OnlMonServer.cc
References CommonHistoMap, h1d, TauVsDIS_MachineLearning_Differentiation::msg, MSG_SEV_INFORMATIONAL, MSG_SEV_WARNING, send_message(), and OnlMonBase::verbosity.
void OnlMonServer::registerMonitor (OnlMon * Monitor)
Definition at line 262 of file OnlMonServer.cc.
View newest version in sPHENIX GitHub at line 262 of file OnlMonServer.cc
References OnlMon::Init(), OnlMon::InitCommon(), MonitorList, TauVsDIS_MachineLearning_Differentiation::msg, MSG_SEV_SEVEREERROR, MsgSystem, OnlMonBase::Name(), and send_message().
Referenced by run_bbc_server(), run_cemc_server(), run_cemc_server_SEB00(), run_cemc_server_SEB01(), run_daq_server(), run_example_server0(), run_example_server1(), run_hcal_server(), run_intt_server(), run_ll1_server(), run_mvtx_server(), run_pktsize_server(), run_sepd_server(), run_tpc_server(), and run_zdc_server().
int OnlMonServer::Reset ()
Definition at line 413 of file OnlMonServer.cc.
View newest version in sPHENIX GitHub at line 413 of file OnlMonServer.cc
References CommonHistoMap, eventnumber, i, MonitorHistoSet, MonitorList, and MsgSystem.
Referenced by process_event().
int OnlMonServer::run_empty (const int nevents)
Definition at line 382 of file OnlMonServer.cc.
View newest version in sPHENIX GitHub at line 382 of file OnlMonServer.cc
References i, nevents(), and process_event().
int OnlMonServer::RunNumber () const inline
Definition at line 42 of file OnlMonServer.h.
View newest version in sPHENIX GitHub at line 42 of file OnlMonServer.h
References runnumber.
Referenced by OnlMonDB::DBcommit(), process_event(), send_message(), start_server(), WriteHistoFile(), and WriteLogFile().
void OnlMonServer::RunNumber (const int irun)
Definition at line 539 of file OnlMonServer.cc.
View newest version in sPHENIX GitHub at line 539 of file OnlMonServer.cc
References runnumber.
int OnlMonServer::send_message (const OnlMon * Monitor, const int msgsource, const int severity, const std::string & err_message, const int msgtype) const
Definition at line 572 of file OnlMonServer.cc.
View newest version in sPHENIX GitHub at line 572 of file OnlMonServer.cc
References eventnumber, TauVsDIS_MachineLearning_Differentiation::msg, MSG_SEV_WARNING, MsgSystem, OnlMonBase::Name(), RunNumber(), OnlMonBase::ThisName, and WriteLogFile().
Referenced by getCommonHisto(), getHisto(), getHistoName(), InitAll(), MyMon::process_event(), PktSizeMon::process_event(), BbcMon::process_event(), MvtxMon::process_event(), registerHisto(), registerMonitor(), and PktSizeMon::UpdateDB().
int OnlMonServer::send_message (const int severity, const std::string & err_message, const int msgtype) const private
Definition at line 597 of file OnlMonServer.cc.
View newest version in sPHENIX GitHub at line 597 of file OnlMonServer.cc
References MSG_SOURCE_UNSPECIFIED, MsgSystem, and OnlMonBase::ThisName.
int OnlMonServer::SetSubsystemRunStatus (OnlMon * Monitor, const int status)
Definition at line 754 of file OnlMonServer.cc.
View newest version in sPHENIX GitHub at line 754 of file OnlMonServer.cc
References GetRunType(), OnlMonBase::Name(), runnumber, RunStatusDB, utils::status, and OnlMonStatusDB::UpdateStatus().
Referenced by OnlMon::SetStatus().
int OnlMonServer::SetSubsystemStatus (OnlMon * Monitor, const int status)
Definition at line 745 of file OnlMonServer.cc.
View newest version in sPHENIX GitHub at line 745 of file OnlMonServer.cc
References GetRunType(), OnlMonBase::Name(), runnumber, utils::status, statusDB, and OnlMonStatusDB::UpdateStatus().
void OnlMonServer::SetThreadId (const pthread_t & id) inline
Definition at line 86 of file OnlMonServer.h.
View newest version in sPHENIX GitHub at line 86 of file OnlMonServer.h
References train_ambiguity_solver::id, and serverthreadid.
Referenced by pinit().
int OnlMonServer::WriteHistoFile ()
Definition at line 547 of file OnlMonServer.cc.
View newest version in sPHENIX GitHub at line 547 of file OnlMonServer.cc
References filename, MonitorHistoSet, RunNumber(), to_string(), and OnlMonBase::Verbosity().
Referenced by handleconnection(), process_event(), and start_server().
int OnlMonServer::WriteLogFile (const std::string & name, const std::string & msg) const
Definition at line 604 of file OnlMonServer.cc.
View newest version in sPHENIX GitHub at line 604 of file OnlMonServer.cc
References CurrentTicks(), eventnumber, fout, gtest_output_test::message, TauVsDIS_MachineLearning_Differentiation::msg, RunNumber(), and RunType.
Referenced by MessageSystem::send_message(), and send_message().
Member Data Documentation
OnlMonServer * OnlMonServer::__instance = nullptr static private
Definition at line 108 of file OnlMonServer.h.
View newest version in sPHENIX GitHub at line 108 of file OnlMonServer.h
Referenced by instance().
std::set<unsigned int> OnlMonServer::activepackets private
Definition at line 128 of file OnlMonServer.h.
View newest version in sPHENIX GitHub at line 128 of file OnlMonServer.h
Referenced by clearactivepackets(), and Print().
int OnlMonServer::activepacketsinit = 0 private
Definition at line 115 of file OnlMonServer.h.
View newest version in sPHENIX GitHub at line 115 of file OnlMonServer.h
Referenced by BeginRun().
int OnlMonServer::badevents = 0 private
Definition at line 112 of file OnlMonServer.h.
View newest version in sPHENIX GitHub at line 112 of file OnlMonServer.h
Referenced by AddBadEvent(), and BadEvents().
uint64_t OnlMonServer::borticks = 0 private
Definition at line 114 of file OnlMonServer.h.
View newest version in sPHENIX GitHub at line 114 of file OnlMonServer.h
Referenced by BorTicks(), and CacheRunDB().
std::map<const std::string, TH1 *> OnlMonServer::CommonHistoMap private
Definition at line 126 of file OnlMonServer.h.
View newest version in sPHENIX GitHub at line 126 of file OnlMonServer.h
Referenced by getCommonHisto(), getHisto(), getHistoName(), nHistos(), Print(), registerCommonHisto(), registerHisto(), Reset(), and ~OnlMonServer().
int OnlMonServer::cosmicrun = 0 private
Definition at line 119 of file OnlMonServer.h.
View newest version in sPHENIX GitHub at line 119 of file OnlMonServer.h
Referenced by CacheRunDB(), and isCosmicRun().
uint64_t OnlMonServer::currentticks = 0 private
Definition at line 113 of file OnlMonServer.h.
View newest version in sPHENIX GitHub at line 113 of file OnlMonServer.h
Referenced by CurrentTicks().
int OnlMonServer::eventnumber = 0 private
Definition at line 110 of file OnlMonServer.h.
View newest version in sPHENIX GitHub at line 110 of file OnlMonServer.h
Referenced by EventNumber(), Reset(), send_message(), and WriteLogFile().
std::map<std::string, std::map<std::string, TH1 *> > OnlMonServer::MonitorHistoSet private
Definition at line 130 of file OnlMonServer.h.
View newest version in sPHENIX GitHub at line 130 of file OnlMonServer.h
Referenced by dumpHistos(), getHisto(), monibegin(), moniend(), Print(), registerHisto(), Reset(), WriteHistoFile(), and ~OnlMonServer().
std::vector<OnlMon *> OnlMonServer::MonitorList private
Definition at line 127 of file OnlMonServer.h.
View newest version in sPHENIX GitHub at line 127 of file OnlMonServer.h
Referenced by BeginRun(), EndRun(), getMonitor(), monitor_vec_begin(), monitor_vec_end(), Print(), process_event(), registerMonitor(), Reset(), and ~OnlMonServer().
std::map<std::string, MessageSystem *> OnlMonServer::MsgSystem private
Definition at line 129 of file OnlMonServer.h.
View newest version in sPHENIX GitHub at line 129 of file OnlMonServer.h
Referenced by OnlMonServer(), registerMonitor(), Reset(), send_message(), and ~OnlMonServer().
pthread_mutex_t OnlMonServer::mutex private
Definition at line 131 of file OnlMonServer.h.
View newest version in sPHENIX GitHub at line 131 of file OnlMonServer.h
Referenced by OnlMonServer(), and ~OnlMonServer().
int OnlMonServer::portnumber = OnlMonDefs::MONIPORT private
Definition at line 111 of file OnlMonServer.h.
View newest version in sPHENIX GitHub at line 111 of file OnlMonServer.h
Referenced by PortNumber().
int OnlMonServer::runnumber = -1 private
Definition at line 109 of file OnlMonServer.h.
View newest version in sPHENIX GitHub at line 109 of file OnlMonServer.h
Referenced by RunNumber(), SetSubsystemRunStatus(), and SetSubsystemStatus().
OnlMonStatusDB* OnlMonServer::RunStatusDB = nullptr private
Definition at line 125 of file OnlMonServer.h.
View newest version in sPHENIX GitHub at line 125 of file OnlMonServer.h
Referenced by OnlMonServer(), SetSubsystemRunStatus(), and ~OnlMonServer().
std::string OnlMonServer::RunType = "UNKNOWN" private
Definition at line 121 of file OnlMonServer.h.
View newest version in sPHENIX GitHub at line 121 of file OnlMonServer.h
Referenced by CacheRunDB(), GetRunType(), and WriteLogFile().
unsigned int OnlMonServer::scaledtrigmask = 0xFFFFFFFF private
Definition at line 116 of file OnlMonServer.h.
View newest version in sPHENIX GitHub at line 116 of file OnlMonServer.h
int OnlMonServer::scaledtrigmask_used = 0 private
Definition at line 117 of file OnlMonServer.h.
View newest version in sPHENIX GitHub at line 117 of file OnlMonServer.h
TH1* OnlMonServer::serverrunning = nullptr private
Definition at line 123 of file OnlMonServer.h.
View newest version in sPHENIX GitHub at line 123 of file OnlMonServer.h
Referenced by InitAll(), and ~OnlMonServer().
pthread_t OnlMonServer::serverthreadid = 0 private
Definition at line 132 of file OnlMonServer.h.
View newest version in sPHENIX GitHub at line 132 of file OnlMonServer.h
Referenced by SetThreadId(), and ~OnlMonServer().
int OnlMonServer::standalone = 0 private
Definition at line 118 of file OnlMonServer.h.
View newest version in sPHENIX GitHub at line 118 of file OnlMonServer.h
Referenced by CacheRunDB(), and isStandaloneRun().
OnlMonStatusDB* OnlMonServer::statusDB = nullptr private
Definition at line 124 of file OnlMonServer.h.
View newest version in sPHENIX GitHub at line 124 of file OnlMonServer.h
Referenced by OnlMonServer(), SetSubsystemStatus(), and ~OnlMonServer().
std::string OnlMonServer::TriggerConfig = "UNKNOWN" private
Definition at line 120 of file OnlMonServer.h.
View newest version in sPHENIX GitHub at line 120 of file OnlMonServer.h
Referenced by CacheRunDB().
The documentation for this class was generated from the following files:
OnlMon/blob/main/onlmonserver/OnlMonServer.h
OnlMon/blob/main/onlmonserver/OnlMonServer.cc