Analysis Software: Acts::Experimental::VolumeStructureBuilder Class Reference
Acts::Experimental::VolumeStructureBuilder Class Reference
#include <acts/blob/sPHENIX/Core/include/Acts/Detector/VolumeStructureBuilder.hpp>
Classes
struct Config
Nexted configuration struct.
Public Member Functions
VolumeStructureBuilder (const Config &cfg, std::unique_ptr< const Logger > mlogger=getDefaultLogger("VolumeStructureBuilder", Logging::INFO))
ExternalStructure construct (const GeometryContext &gctx) const final
Public Member Functions inherited from Acts::Experimental::IExternalStructureBuilder
virtual ~IExternalStructureBuilder ()=default
Private Member Functions
const Logger & logger () const
Private access method to the logger.
Private Attributes
Config m_cfg
configuration object
std::unique_ptr< const Logger > m_logger
logging instance
Detailed Description
This class provides the external detector volume structure, configured either from:
a volume extent
from an array with volume bounds identification
Note
A starting transform (defaulted to identity) can be provided, in case of volume bounds construction from an Acts::Extent object, the transform steming from the extent definition will be applied on top of the provided starting transform. In case of volume bounds construction from an array of values, the starting transform is already the final volume placement.
Definition at line 37 of file VolumeStructureBuilder.hpp.
View newest version in sPHENIX GitHub at line 37 of file VolumeStructureBuilder.hpp
Constructor & Destructor Documentation
Acts::Experimental::VolumeStructureBuilder::VolumeStructureBuilder (const Config & cfg, std::unique_ptr< const Logger > mlogger = getDefaultLogger("VolumeStructureBuilder", Logging::INFO))
Constructor
Parameters
cfg is the configuration struct
mlogger logging instance for screen output
Definition at line 22 of file VolumeStructureBuilder.cpp.
View newest version in sPHENIX GitHub at line 22 of file VolumeStructureBuilder.cpp
References Acts::Experimental::VolumeStructureBuilder::Config::boundsType, Acts::Experimental::VolumeStructureBuilder::Config::boundValues, Acts::Experimental::VolumeStructureBuilder::Config::extent, and m_cfg.
Member Function Documentation
Acts::Experimental::ExternalStructure Acts::Experimental::VolumeStructureBuilder::construct (const GeometryContext & gctx) const final virtual
The interface definition for internal structure creation
Parameters
gctx the geometry context at the creation of the internal structure
Returns
a consistent set of detector volume internals
Implements Acts::Experimental::IExternalStructureBuilder.
Definition at line 39 of file VolumeStructureBuilder.cpp.
View newest version in sPHENIX GitHub at line 39 of file VolumeStructureBuilder.cpp
References ACTS_DEBUG, Acts::ACTS_VERBOSE(), Acts::binPhi, Acts::binR, Acts::binX, Acts::binY, Acts::binZ, Acts::Experimental::defaultPortalGenerator(), Acts::GenericCuboidVolumeBounds::BoundValues::eSize, m_cfg(), testing::internal::move(), to_string(), Acts::toString(), and physmon_ckf_tracking::u.
Referenced by BOOST_AUTO_TEST_CASE().
const Logger& Acts::Experimental::VolumeStructureBuilder::logger () const inline private
Private access method to the logger.
Definition at line 74 of file VolumeStructureBuilder.hpp.
View newest version in sPHENIX GitHub at line 74 of file VolumeStructureBuilder.hpp
References m_logger.
Member Data Documentation
Config Acts::Experimental::VolumeStructureBuilder::m_cfg private
configuration object
Definition at line 71 of file VolumeStructureBuilder.hpp.
View newest version in sPHENIX GitHub at line 71 of file VolumeStructureBuilder.hpp
Referenced by VolumeStructureBuilder().
std::unique_ptr<const Logger> Acts::Experimental::VolumeStructureBuilder::m_logger private
logging instance
Definition at line 77 of file VolumeStructureBuilder.hpp.
View newest version in sPHENIX GitHub at line 77 of file VolumeStructureBuilder.hpp
Referenced by logger().
The documentation for this class was generated from the following files:
acts/blob/sPHENIX/Core/include/Acts/Detector/VolumeStructureBuilder.hpp
acts/blob/sPHENIX/Core/src/Detector/VolumeStructureBuilder.cpp