Analysis Software: ast.TypeConverter Class Reference
ast.TypeConverter Class Reference
Public Member Functions
def __init__
def ToType
def DeclarationToParts
def ToParameters
def CreateReturnType
def GetTemplateIndices
Public Attributes
namespace_stack
Private Member Functions
def _GetTemplateEnd
Detailed Description
Definition at line 458 of file ast.py.
View newest version in sPHENIX GitHub at line 458 of file ast.py
Constructor & Destructor Documentation
def ast.TypeConverter.__init__ (self, namespace_stack)
Definition at line 460 of file ast.py.
View newest version in sPHENIX GitHub at line 460 of file ast.py
Member Function Documentation
def ast.TypeConverter._GetTemplateEnd (self, tokens, start) private
Definition at line 463 of file ast.py.
View newest version in sPHENIX GitHub at line 463 of file ast.py
Referenced by ast.TypeConverter.DeclarationToParts(), and ast.TypeConverter.ToType().
def ast.TypeConverter.CreateReturnType (self, return_type_seq)
Definition at line 652 of file ast.py.
View newest version in sPHENIX GitHub at line 652 of file ast.py
References ast.TypeConverter.DeclarationToParts().
def ast.TypeConverter.DeclarationToParts (self, parts, needs_name_removed)
Definition at line 536 of file ast.py.
View newest version in sPHENIX GitHub at line 536 of file ast.py
References ast.TypeConverter._GetTemplateEnd(), keywords.IsKeyword(), join(), and ast.TypeConverter.ToType().
Referenced by ast.TypeConverter.CreateReturnType(), and ast.TypeConverter.ToParameters().
def ast.TypeConverter.GetTemplateIndices (self, names)
Definition at line 666 of file ast.py.
View newest version in sPHENIX GitHub at line 666 of file ast.py
def ast.TypeConverter.ToParameters (self, tokens)
Definition at line 591 of file ast.py.
View newest version in sPHENIX GitHub at line 591 of file ast.py
References ast.TypeConverter.DeclarationToParts().
def ast.TypeConverter.ToType (self, tokens)
Convert [Token,...] to [Class(...), ] useful for base classes.
For example, code like class Foo : public Bar<x, y> { ... };
the "Bar<x, y>" portion gets converted to an AST.
Returns:
  [Class(...), ...]
Definition at line 477 of file ast.py.
View newest version in sPHENIX GitHub at line 477 of file ast.py
References ast.TypeConverter._GetTemplateEnd(), keywords.IsKeyword(), join(), and ast.TypeConverter.ToType().
Referenced by ast.TypeConverter.DeclarationToParts(), and ast.TypeConverter.ToType().
Member Data Documentation
ast.TypeConverter.namespace_stack
Definition at line 461 of file ast.py.
View newest version in sPHENIX GitHub at line 461 of file ast.py
Referenced by ast.AstBuilder._CreateVariable(), ast.AstBuilder._GetClass(), ast.AstBuilder._GetMethod(), ast.AstBuilder.handle_friend(), and ast.AstBuilder.handle_typedef().
The documentation for this class was generated from the following file:
JETSCAPE/blob/master/external_packages/googletest/googlemock/scripts/generator/cpp/ast.py