Analysis Software: pbpb2p76_new Namespace Reference
pbpb2p76_new Namespace Reference
Functions
def add_e2e3
def add_avg_ed
def add_ed
Variables
string collision_system 'pbpb5020'
string path '/lustre/nyx/hyihp/lpang/trento_ini/%s'
tuple dat np.loadtxt('/lustre/nyx/hyihp/lpang/trento_ini/%s.log'%collision_system)
list entropy dat[:, 3]
tuple centrality Centrality(entropy)
list cents
Function Documentation
def pbpb2p76_new.add_avg_ed (h5, cent = "20_30", n = 2)
add weighted average sd to h5, in the eccn/sd_mean
Definition at line 50 of file pbpb2p76_new.py.
View newest version in sPHENIX GitHub at line 50 of file pbpb2p76_new.py
References print(), and average.weighted_average().
Referenced by add_ed().
def pbpb2p76_new.add_e2e3 (h5, cent_min, cent_max)
add ecc2, ecc3 distribution for this centrlaity bin in hdf5 file
   add smin, smax for this centrality bin in hdf5 file
Definition at line 31 of file pbpb2p76_new.py.
View newest version in sPHENIX GitHub at line 31 of file pbpb2p76_new.py
Referenced by add_ed().
def pbpb2p76_new.add_ed (h5, cent_min, cent_max, nx = 100, ny = 100)
add the <ed>_2 which is the ed distribution rotated by participant plane phi_2
and add the <ed>_3 which is the ed distribution rotated by participant plane phi_3
for events in this centrality class, for all the ecc2, ecc3 bins in their probability
distribution function
Definition at line 62 of file pbpb2p76_new.py.
View newest version in sPHENIX GitHub at line 62 of file pbpb2p76_new.py
References add_avg_ed(), add_e2e3(), and print().
Variable Documentation
tuple pbpb2p76_new.centrality Centrality(entropy)
Definition at line 28 of file pbpb2p76_new.py.
View newest version in sPHENIX GitHub at line 28 of file pbpb2p76_new.py
list pbpb2p76_new.cents
Initial value:
 [(0, 5), (0, 10), (5, 10), (10, 20), (20, 30),
              (0, 20), (10, 30), (30, 40), (30, 50), (40, 50), (0, 80)]
Definition at line 140 of file pbpb2p76_new.py.
View newest version in sPHENIX GitHub at line 140 of file pbpb2p76_new.py
string pbpb2p76_new.collision_system 'pbpb5020'
Definition at line 19 of file pbpb2p76_new.py.
View newest version in sPHENIX GitHub at line 19 of file pbpb2p76_new.py
Referenced by Jetscape::TrentoInitial.Exec().
tuple pbpb2p76_new.dat np.loadtxt('/lustre/nyx/hyihp/lpang/trento_ini/%s.log'%collision_system)
Definition at line 23 of file pbpb2p76_new.py.
View newest version in sPHENIX GitHub at line 23 of file pbpb2p76_new.py
list pbpb2p76_new.entropy dat[:, 3]
Definition at line 25 of file pbpb2p76_new.py.
View newest version in sPHENIX GitHub at line 25 of file pbpb2p76_new.py
string pbpb2p76_new.path '/lustre/nyx/hyihp/lpang/trento_ini/%s'
Definition at line 21 of file pbpb2p76_new.py.
View newest version in sPHENIX GitHub at line 21 of file pbpb2p76_new.py