Analysis Software: PHGenIntegralv1 Class Reference
PHGenIntegralv1 Class Reference
PHGenIntegralv1.
#include <coresoftware/blob/master/generators/phhepmc/PHGenIntegralv1.h>
Public Member Functions
PHGenIntegralv1 ()
PHGenIntegralv1 (const std::string &description)
~PHGenIntegralv1 () override
PHObject * CloneMe () const override
Virtual copy constructor.
int isValid () const override
isValid returns non zero if object contains vailid data
void identify (std::ostream &os=std::cout) const override
void Reset () override
Clear Event.
int Integrate () const override
int Integrate (PHObject *) override
For integral objects, e.g. integrated luminosity counter, integrate with another object from another run.
void CopyFrom (const PHObject *obj) override
Double_t get_Integrated_Lumi () const override
Integrated luminosity in pb^-1.
void set_Integrated_Lumi (Double_t integratedLumi) override
Integrated luminosity in pb^-1.
ULong64_t get_N_Generator_Accepted_Event () const override
Number of accepted events in the event generator. This can be higher than m_NProcessedEvent depending on trigger on the event generator.
void set_N_Generator_Accepted_Event (ULong64_t nGeneratorAcceptedEvent) override
Number of accepted events in the event generator. This can be higher than m_NProcessedEvent depending on trigger on the event generator.
ULong64_t get_N_Processed_Event () const override
Number of processed events in the Fun4All cycles.
void set_N_Processed_Event (ULong64_t nProcessedEvent) override
Number of processed events in the Fun4All cycles.
Double_t get_Sum_Of_Weight () const override
void set_Sum_Of_Weight (Double_t sumOfWeight) override
const std::string & get_Description () const override
description on the source
void set_Description (const std::string &description) override
description on the source
Public Member Functions inherited from PHGenIntegral
PHGenIntegral ()
~PHGenIntegral () override
virtual Double_t get_CrossSection_Processed_Event () const
cross sections for the processed events in pb
virtual Double_t get_CrossSection_Generator_Accepted_Event () const
cross sections for the events accepted by the event generator in pb
Public Member Functions inherited from PHObject
PHObject ()
ctor
~PHObject () override
dtor
virtual PHObject * clone () const final
PHObject * Clone (const char *newname="") const final
void Copy (TObject &object) const final
Private Attributes
ULong64_t m_NProcessedEvent
Number of processed events in the Fun4All cycles.
ULong64_t m_NGeneratorAcceptedEvent
Number of accepted events in the event generator. This can be higher than m_NProcessedEvent depending on trigger on the event generator.
Double_t m_IntegratedLumi
Integrated luminosity in pb^-1.
Double_t m_SumOfWeight
std::string m_Description
description on the source
Detailed Description
PHGenIntegralv1.
Definition at line 24 of file PHGenIntegralv1.h.
View newest version in sPHENIX GitHub at line 24 of file PHGenIntegralv1.h
Constructor & Destructor Documentation
PHGenIntegralv1::PHGenIntegralv1 ()
Definition at line 20 of file PHGenIntegralv1.cc.
View newest version in sPHENIX GitHub at line 20 of file PHGenIntegralv1.cc
Referenced by CloneMe().
PHGenIntegralv1::PHGenIntegralv1 (const std::string & description) explicit
Definition at line 28 of file PHGenIntegralv1.cc.
View newest version in sPHENIX GitHub at line 28 of file PHGenIntegralv1.cc
PHGenIntegralv1::~PHGenIntegralv1 () inline override
Definition at line 29 of file PHGenIntegralv1.h.
View newest version in sPHENIX GitHub at line 29 of file PHGenIntegralv1.h
Member Function Documentation
PHObject* PHGenIntegralv1::CloneMe () const inline override virtual
Virtual copy constructor.
Reimplemented from PHObject.
Definition at line 31 of file PHGenIntegralv1.h.
View newest version in sPHENIX GitHub at line 31 of file PHGenIntegralv1.h
References PHGenIntegralv1().
void PHGenIntegralv1::CopyFrom (const PHObject * obj) override virtual
Reimplemented from PHObject.
Definition at line 84 of file PHGenIntegralv1.cc.
View newest version in sPHENIX GitHub at line 84 of file PHGenIntegralv1.cc
References PHGenIntegral::get_Description(), PHGenIntegral::get_Integrated_Lumi(), PHGenIntegral::get_N_Generator_Accepted_Event(), PHGenIntegral::get_N_Processed_Event(), PHGenIntegral::get_Sum_Of_Weight(), PHObject::identify(), m_Description, m_IntegratedLumi, m_NGeneratorAcceptedEvent, m_NProcessedEvent, and m_SumOfWeight.
const std::string& PHGenIntegralv1::get_Description () const inline override virtual
description on the source
Reimplemented from PHGenIntegral.
Definition at line 94 of file PHGenIntegralv1.h.
View newest version in sPHENIX GitHub at line 94 of file PHGenIntegralv1.h
References m_Description.
Referenced by identify().
Double_t PHGenIntegralv1::get_Integrated_Lumi () const inline override virtual
Integrated luminosity in pb^-1.
Reimplemented from PHGenIntegral.
Definition at line 42 of file PHGenIntegralv1.h.
View newest version in sPHENIX GitHub at line 42 of file PHGenIntegralv1.h
References m_IntegratedLumi.
Referenced by identify().
ULong64_t PHGenIntegralv1::get_N_Generator_Accepted_Event () const inline override virtual
Number of accepted events in the event generator. This can be higher than m_NProcessedEvent depending on trigger on the event generator.
Reimplemented from PHGenIntegral.
Definition at line 54 of file PHGenIntegralv1.h.
View newest version in sPHENIX GitHub at line 54 of file PHGenIntegralv1.h
References m_NGeneratorAcceptedEvent.
Referenced by identify().
ULong64_t PHGenIntegralv1::get_N_Processed_Event () const inline override virtual
Number of processed events in the Fun4All cycles.
Reimplemented from PHGenIntegral.
Definition at line 66 of file PHGenIntegralv1.h.
View newest version in sPHENIX GitHub at line 66 of file PHGenIntegralv1.h
References m_NProcessedEvent.
Referenced by identify().
Double_t PHGenIntegralv1::get_Sum_Of_Weight () const inline override virtual
Sum of weight assigned to the events by the generators. Event weight is normally 1 and thus equal to number of the generated event and is uninteresting. However, there are several cases where one may have nontrivial event weights, e.g. using user hooks in Pythia8 generators to reweight the phase space
Reimplemented from PHGenIntegral.
Definition at line 80 of file PHGenIntegralv1.h.
View newest version in sPHENIX GitHub at line 80 of file PHGenIntegralv1.h
References m_SumOfWeight.
Referenced by identify().
void PHGenIntegralv1::identify (std::ostream & os = std::cout) const override virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from PHObject.
Definition at line 36 of file PHGenIntegralv1.cc.
View newest version in sPHENIX GitHub at line 36 of file PHGenIntegralv1.cc
References PHGenIntegral::get_CrossSection_Generator_Accepted_Event(), PHGenIntegral::get_CrossSection_Processed_Event(), get_Description(), get_Integrated_Lumi(), get_N_Generator_Accepted_Event(), get_N_Processed_Event(), and get_Sum_Of_Weight().
int PHGenIntegralv1::Integrate () const inline override virtual
Reimplemented from PHObject.
Definition at line 36 of file PHGenIntegralv1.h.
View newest version in sPHENIX GitHub at line 36 of file PHGenIntegralv1.h
int PHGenIntegralv1::Integrate (PHObject * incoming_object) override virtual
For integral objects, e.g. integrated luminosity counter, integrate with another object from another run.
Reimplemented from PHObject.
Definition at line 54 of file PHGenIntegralv1.cc.
View newest version in sPHENIX GitHub at line 54 of file PHGenIntegralv1.cc
References PHGenIntegral::get_Description(), PHGenIntegral::get_Integrated_Lumi(), PHGenIntegral::get_N_Generator_Accepted_Event(), PHGenIntegral::get_N_Processed_Event(), PHGenIntegral::get_Sum_Of_Weight(), PHObject::identify(), m_Description, m_IntegratedLumi, m_NGeneratorAcceptedEvent, m_NProcessedEvent, and m_SumOfWeight.
int PHGenIntegralv1::isValid () const inline override virtual
isValid returns non zero if object contains vailid data
Reimplemented from PHObject.
Definition at line 32 of file PHGenIntegralv1.h.
View newest version in sPHENIX GitHub at line 32 of file PHGenIntegralv1.h
void PHGenIntegralv1::Reset () override virtual
Clear Event.
Reimplemented from PHObject.
Definition at line 45 of file PHGenIntegralv1.cc.
View newest version in sPHENIX GitHub at line 45 of file PHGenIntegralv1.cc
References m_Description, m_IntegratedLumi, m_NGeneratorAcceptedEvent, m_NProcessedEvent, and m_SumOfWeight.
void PHGenIntegralv1::set_Description (const std::string & description) inline override virtual
description on the source
Reimplemented from PHGenIntegral.
Definition at line 100 of file PHGenIntegralv1.h.
View newest version in sPHENIX GitHub at line 100 of file PHGenIntegralv1.h
References description, and m_Description.
void PHGenIntegralv1::set_Integrated_Lumi (Double_t integratedLumi) inline override virtual
Integrated luminosity in pb^-1.
Reimplemented from PHGenIntegral.
Definition at line 48 of file PHGenIntegralv1.h.
View newest version in sPHENIX GitHub at line 48 of file PHGenIntegralv1.h
References m_IntegratedLumi.
void PHGenIntegralv1::set_N_Generator_Accepted_Event (ULong64_t nGeneratorAcceptedEvent) inline override virtual
Number of accepted events in the event generator. This can be higher than m_NProcessedEvent depending on trigger on the event generator.
Reimplemented from PHGenIntegral.
Definition at line 60 of file PHGenIntegralv1.h.
View newest version in sPHENIX GitHub at line 60 of file PHGenIntegralv1.h
References m_NGeneratorAcceptedEvent.
void PHGenIntegralv1::set_N_Processed_Event (ULong64_t nProcessedEvent) inline override virtual
Number of processed events in the Fun4All cycles.
Reimplemented from PHGenIntegral.
Definition at line 72 of file PHGenIntegralv1.h.
View newest version in sPHENIX GitHub at line 72 of file PHGenIntegralv1.h
References m_NProcessedEvent.
void PHGenIntegralv1::set_Sum_Of_Weight (Double_t sumOfWeight) inline override virtual
Sum of weight assigned to the events by the generators. Event weight is normally 1 and thus equal to number of the generated event and is uninteresting. However, there are several cases where one may have nontrivial event weights, e.g. using user hooks in Pythia8 generators to reweight the phase space
Reimplemented from PHGenIntegral.
Definition at line 88 of file PHGenIntegralv1.h.
View newest version in sPHENIX GitHub at line 88 of file PHGenIntegralv1.h
References m_SumOfWeight.
Member Data Documentation
std::string PHGenIntegralv1::m_Description private
description on the source
Definition at line 121 of file PHGenIntegralv1.h.
View newest version in sPHENIX GitHub at line 121 of file PHGenIntegralv1.h
Referenced by CopyFrom(), get_Description(), Integrate(), Reset(), and set_Description().
Double_t PHGenIntegralv1::m_IntegratedLumi private
Integrated luminosity in pb^-1.
Definition at line 113 of file PHGenIntegralv1.h.
View newest version in sPHENIX GitHub at line 113 of file PHGenIntegralv1.h
Referenced by CopyFrom(), get_Integrated_Lumi(), Integrate(), Reset(), and set_Integrated_Lumi().
ULong64_t PHGenIntegralv1::m_NGeneratorAcceptedEvent private
Number of accepted events in the event generator. This can be higher than m_NProcessedEvent depending on trigger on the event generator.
Definition at line 110 of file PHGenIntegralv1.h.
View newest version in sPHENIX GitHub at line 110 of file PHGenIntegralv1.h
Referenced by CopyFrom(), get_N_Generator_Accepted_Event(), Integrate(), Reset(), and set_N_Generator_Accepted_Event().
ULong64_t PHGenIntegralv1::m_NProcessedEvent private
Number of processed events in the Fun4All cycles.
Definition at line 107 of file PHGenIntegralv1.h.
View newest version in sPHENIX GitHub at line 107 of file PHGenIntegralv1.h
Referenced by CopyFrom(), get_N_Processed_Event(), Integrate(), Reset(), and set_N_Processed_Event().
Double_t PHGenIntegralv1::m_SumOfWeight private
Sum of weight assigned to the events by the generators. Event weight is normally 1 and thus equal to number of the generated event and is uninteresting. However, there are several cases where one may have nontrivial event weights, e.g. using user hooks in Pythia8 generators to reweight the phase space
Definition at line 118 of file PHGenIntegralv1.h.
View newest version in sPHENIX GitHub at line 118 of file PHGenIntegralv1.h
Referenced by CopyFrom(), get_Sum_Of_Weight(), Integrate(), Reset(), and set_Sum_Of_Weight().
The documentation for this class was generated from the following files:
coresoftware/blob/master/generators/phhepmc/PHGenIntegralv1.h
coresoftware/blob/master/generators/phhepmc/PHGenIntegralv1.cc