Analysis Software: Acts::ProtoLayerHelper Class Reference
Acts::ProtoLayerHelper Class Reference
#include <acts/blob/sPHENIX/Core/include/Acts/Geometry/ProtoLayerHelper.hpp>
Classes
struct Config
Public Types
using SortingConfig = std::pair< BinningValue, double >
Public Member Functions
ProtoLayerHelper (const Config &config, std::unique_ptr< const Logger > logger=getDefaultLogger("ProtoLayerHelper", Logging::INFO))
~ProtoLayerHelper ()=default
std::vector< ProtoLayer > protoLayers (const GeometryContext &gctx, const std::vector< const Surface * > &surfaces, const SortingConfig &sorting) const
std::vector< ProtoLayer > protoLayers (const GeometryContext &gctx, const std::vector< const Surface * > &surfaces, const std::vector< SortingConfig > &sortings) const
Private Member Functions
const Logger & logger () const
Private access to logger.
Private Attributes
std::unique_ptr< const Logger > m_logger
Logging instance.
Detailed Description
This class is designed to parse a vector of Surfaces and sort them into corresponding proto layers.
Definition at line 31 of file ProtoLayerHelper.hpp.
View newest version in sPHENIX GitHub at line 31 of file ProtoLayerHelper.hpp
Member Typedef Documentation
using Acts::ProtoLayerHelper::SortingConfig = std::pair<BinningValue, double>
Definition at line 33 of file ProtoLayerHelper.hpp.
View newest version in sPHENIX GitHub at line 33 of file ProtoLayerHelper.hpp
Constructor & Destructor Documentation
Acts::ProtoLayerHelper::ProtoLayerHelper (const Config & config, std::unique_ptr< const Logger > logger = getDefaultLogger("ProtoLayerHelper", Logging::INFO)) inline
Constructor with explicit config
Parameters
config Explicit config struct
logger logging instance
Definition at line 41 of file ProtoLayerHelper.hpp.
View newest version in sPHENIX GitHub at line 41 of file ProtoLayerHelper.hpp
Acts::ProtoLayerHelper::~ProtoLayerHelper () default
Member Function Documentation
const Logger& Acts::ProtoLayerHelper::logger () const inline private
Private access to logger.
Definition at line 76 of file ProtoLayerHelper.hpp.
View newest version in sPHENIX GitHub at line 76 of file ProtoLayerHelper.hpp
References m_logger.
std::vector< Acts::ProtoLayer > Acts::ProtoLayerHelper::protoLayers (const GeometryContext & gctx, const std::vector< const Surface * > & surfaces, const SortingConfig & sorting) const
Sort the surfaces into ProtoLayers
Parameters
gctx The geometry context (usually building context at this stage)
surfaces The surfaces to be sorted into arrays
sorting The sorting setup, one single sorting
Returns
A vector of ProtoLayers
Helper function to find/create the cluster of surfaces where the Extent belongs to. In case none is found, a new one is inserted
Parameters
extent The test extent for finding the cluster
Returns
the reference of the SurfaceCluster for insertion
Definition at line 20 of file ProtoLayerHelper.cpp.
View newest version in sPHENIX GitHub at line 20 of file ProtoLayerHelper.cpp
References Acts::ACTS_VERBOSE(), and clusters.
Referenced by Acts::Test::Layers::BOOST_AUTO_TEST_CASE().
std::vector< Acts::ProtoLayer > Acts::ProtoLayerHelper::protoLayers (const GeometryContext & gctx, const std::vector< const Surface * > & surfaces, const std::vector< SortingConfig > & sortings) const
Sort the surfaces into ProtoLayers, sequential sorting
Parameters
gctx The geometry context (usually building context at this stage)
surfaces The surfaces to be sorted into arrays
sortings The sequential sorting setup
Returns
A vector of ProtoLayers
Definition at line 62 of file ProtoLayerHelper.cpp.
View newest version in sPHENIX GitHub at line 62 of file ProtoLayerHelper.cpp
References ACTS_DEBUG, Acts::ACTS_VERBOSE(), and Acts::binningValueNames().
Member Data Documentation
std::unique_ptr<const Logger> Acts::ProtoLayerHelper::m_logger private
Logging instance.
Definition at line 73 of file ProtoLayerHelper.hpp.
View newest version in sPHENIX GitHub at line 73 of file ProtoLayerHelper.hpp
Referenced by logger().
The documentation for this class was generated from the following files:
acts/blob/sPHENIX/Core/include/Acts/Geometry/ProtoLayerHelper.hpp
acts/blob/sPHENIX/Core/src/Geometry/ProtoLayerHelper.cpp