Analysis Software: MbdPmtHitV1 Class Reference
MbdPmtHitV1 Class Reference
#include <coresoftware/blob/master/offline/packages/mbd/MbdPmtHitV1.h>
Public Member Functions
MbdPmtHitV1 ()
~MbdPmtHitV1 () override=default
void Reset () override
Just does a clear.
void Clear (Option_t *="") override
Clear is used by TClonesArray to reset the tower to initial state without calling destructor/constructor.
Short_t get_pmt () const override
PMT number.
Float_t get_q () const override
Effective Nch in PMT.
Float_t get_tt () const override
Time from time channel.
Float_t get_time () const override
Float_t get_tq () const override
Time from charge channel.
void set_pmt (const Short_t pmt, const Float_t q, const Float_t tt, const Float_t tq) override
void identify (std::ostream &os=std::cout) const override
Prints out exact identity of object.
virtual int isValid () const override
isValid returns non zero if object contains valid data
Public Member Functions inherited from MbdPmtHit
MbdPmtHit ()
virtual ~MbdPmtHit () override=default
Public Member Functions inherited from PHObject
PHObject ()
ctor
~PHObject () override
dtor
virtual PHObject * CloneMe () const
Virtual copy constructor.
virtual PHObject * clone () const final
PHObject * Clone (const char *newname="") const final
void Copy (TObject &object) const final
virtual int Integrate () const
virtual int Integrate (PHObject *)
virtual void CopyFrom (const PHObject *obj)
Private Attributes
Short_t bpmt {-1}
Float_t bq {std::numeric_limits<float>::quiet_NaN()}
Float_t btt {std::numeric_limits<float>::quiet_NaN()}
Float_t btq {std::numeric_limits<float>::quiet_NaN()}
Detailed Description
Definition at line 10 of file MbdPmtHitV1.h.
View newest version in sPHENIX GitHub at line 10 of file MbdPmtHitV1.h
Constructor & Destructor Documentation
MbdPmtHitV1::MbdPmtHitV1 () inline
Definition at line 13 of file MbdPmtHitV1.h.
View newest version in sPHENIX GitHub at line 13 of file MbdPmtHitV1.h
MbdPmtHitV1::~MbdPmtHitV1 () override default
Member Function Documentation
void MbdPmtHitV1::Clear (Option_t * = "") override
Clear is used by TClonesArray to reset the tower to initial state without calling destructor/constructor.
Definition at line 8 of file MbdPmtHitV1.cc.
View newest version in sPHENIX GitHub at line 8 of file MbdPmtHitV1.cc
References bpmt, bq, btq, and btt.
Referenced by Reset().
Short_t MbdPmtHitV1::get_pmt () const inline override virtual
PMT number.
Reimplemented from MbdPmtHit.
Definition at line 23 of file MbdPmtHitV1.h.
View newest version in sPHENIX GitHub at line 23 of file MbdPmtHitV1.h
References bpmt.
Float_t MbdPmtHitV1::get_q () const inline override virtual
Effective Nch in PMT.
Reimplemented from MbdPmtHit.
Definition at line 26 of file MbdPmtHitV1.h.
View newest version in sPHENIX GitHub at line 26 of file MbdPmtHitV1.h
References bq.
Float_t MbdPmtHitV1::get_time () const inline override virtual
Reimplemented from MbdPmtHit.
Definition at line 30 of file MbdPmtHitV1.h.
View newest version in sPHENIX GitHub at line 30 of file MbdPmtHitV1.h
References btt.
Referenced by isValid().
Float_t MbdPmtHitV1::get_tq () const inline override virtual
Time from charge channel.
Reimplemented from MbdPmtHit.
Definition at line 33 of file MbdPmtHitV1.h.
View newest version in sPHENIX GitHub at line 33 of file MbdPmtHitV1.h
References btq.
Float_t MbdPmtHitV1::get_tt () const inline override virtual
Time from time channel.
Reimplemented from MbdPmtHit.
Definition at line 29 of file MbdPmtHitV1.h.
View newest version in sPHENIX GitHub at line 29 of file MbdPmtHitV1.h
References btt.
void MbdPmtHitV1::identify (std::ostream & os = std::cout) const override virtual
Prints out exact identity of object.
Reimplemented from MbdPmtHit.
Definition at line 17 of file MbdPmtHitV1.cc.
View newest version in sPHENIX GitHub at line 17 of file MbdPmtHitV1.cc
References bpmt, bq, btq, and btt.
virtual int MbdPmtHitV1::isValid () const inline override virtual
isValid returns non zero if object contains valid data
Reimplemented from MbdPmtHit.
Definition at line 47 of file MbdPmtHitV1.h.
View newest version in sPHENIX GitHub at line 47 of file MbdPmtHitV1.h
References get_time().
void MbdPmtHitV1::Reset () override virtual
Just does a clear.
Reimplemented from PHObject.
Definition at line 3 of file MbdPmtHitV1.cc.
View newest version in sPHENIX GitHub at line 3 of file MbdPmtHitV1.cc
References Clear().
void MbdPmtHitV1::set_pmt (const Short_t pmt, const Float_t q, const Float_t tt, const Float_t tq) inline override virtual
Reimplemented from MbdPmtHit.
Definition at line 35 of file MbdPmtHitV1.h.
View newest version in sPHENIX GitHub at line 35 of file MbdPmtHitV1.h
References bpmt, bq, btq, and btt.
Member Data Documentation
Short_t MbdPmtHitV1::bpmt {-1} private
Definition at line 54 of file MbdPmtHitV1.h.
View newest version in sPHENIX GitHub at line 54 of file MbdPmtHitV1.h
Referenced by Clear(), get_pmt(), identify(), and set_pmt().
Float_t MbdPmtHitV1::bq {std::numeric_limits<float>::quiet_NaN()} private
Definition at line 55 of file MbdPmtHitV1.h.
View newest version in sPHENIX GitHub at line 55 of file MbdPmtHitV1.h
Referenced by Clear(), get_q(), identify(), and set_pmt().
Float_t MbdPmtHitV1::btq {std::numeric_limits<float>::quiet_NaN()} private
Definition at line 57 of file MbdPmtHitV1.h.
View newest version in sPHENIX GitHub at line 57 of file MbdPmtHitV1.h
Referenced by Clear(), get_tq(), identify(), and set_pmt().
Float_t MbdPmtHitV1::btt {std::numeric_limits<float>::quiet_NaN()} private
Definition at line 56 of file MbdPmtHitV1.h.
View newest version in sPHENIX GitHub at line 56 of file MbdPmtHitV1.h
Referenced by Clear(), get_time(), get_tt(), identify(), and set_pmt().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/mbd/MbdPmtHitV1.h
coresoftware/blob/master/offline/packages/mbd/MbdPmtHitV1.cc