Analysis Software: SyncObject Class Reference
SyncObject Class Reference
#include <coresoftware/blob/master/offline/framework/ffaobjects/SyncObject.h>
Public Member Functions
SyncObject ()=default
ctor - daughter class copy ctor needs this
SyncObject (const SyncObject &source)=default
copy ctor daughter class copy ctor needs also this
~SyncObject () override
dtor
void Reset () override
Clear Sync.
void identify (std::ostream &os=std::cout) const override
int isValid () const override
isValid returns non zero if object contains valid data
PHObject * CloneMe () const override
Virtual copy constructor.
SyncObject & operator= (const SyncObject &source)
virtual int Different (const SyncObject *other) const
virtual void EventCounter (const int)
set Event Counter
virtual void EventNumber (const int)
set Event Number
virtual void SegmentNumber (const int)
set Segment Number
virtual void RunNumber (const int)
set Run Number
Public Member Functions inherited from PHObject
PHObject ()
ctor
~PHObject () override
dtor
virtual PHObject * clone () const final
PHObject * Clone (const char *newname="") const final
void Copy (TObject &object) const final
virtual int Integrate () const
virtual int Integrate (PHObject *)
virtual void CopyFrom (const PHObject *obj)
Protected Member Functions
virtual int EventNumber () const
get Event Number
virtual int EventCounter () const
get Event Counter
virtual int RunNumber () const
get Run Number
virtual int SegmentNumber () const
get Segment Number
Friends
class SyncObjectv1
class Fun4AllDstInputManager
class Fun4AllDstPileupInputManager
class DumpSyncObject
class SegmentSelect
Detailed Description
Definition at line 11 of file SyncObject.h.
View newest version in sPHENIX GitHub at line 11 of file SyncObject.h
Constructor & Destructor Documentation
SyncObject::SyncObject () default
ctor - daughter class copy ctor needs this
SyncObject::SyncObject (const SyncObject & source) default
copy ctor daughter class copy ctor needs also this
SyncObject::~SyncObject () inline override
dtor
Definition at line 19 of file SyncObject.h.
View newest version in sPHENIX GitHub at line 19 of file SyncObject.h
Member Function Documentation
PHObject * SyncObject::CloneMe () const override virtual
Virtual copy constructor.
Reimplemented from PHObject.
Reimplemented in SyncObjectv1.
Definition at line 28 of file SyncObject.cc.
View newest version in sPHENIX GitHub at line 28 of file SyncObject.cc
Referenced by Fun4AllDstInputManager::GetSyncObject(), Fun4AllPrdfInputManager::GetSyncObject(), Fun4AllPrdfInputPoolManager::GetSyncObject(), and Fun4AllStreamingInputManager::GetSyncObject().
int SyncObject::Different (const SyncObject * other) const virtual
Definition at line 47 of file SyncObject.cc.
View newest version in sPHENIX GitHub at line 47 of file SyncObject.cc
References EventNumber(), and RunNumber().
Referenced by Fun4AllDstInputManager::SyncIt(), Fun4AllPrdfInputManager::SyncIt(), Fun4AllPrdfInputPoolManager::SyncIt(), and Fun4AllStreamingInputManager::SyncIt().
virtual void SyncObject::EventCounter (const int) inline virtual
set Event Counter
Reimplemented in SyncObjectv1.
Definition at line 36 of file SyncObject.h.
View newest version in sPHENIX GitHub at line 36 of file SyncObject.h
Referenced by operator=(), SyncReco::process_event(), DumpSyncObject::process_Node(), Fun4AllPrdfInputManager::run(), Fun4AllDstInputManager::SyncIt(), and SyncObjectv1::SyncObjectv1().
virtual int SyncObject::EventCounter () const inline protected virtual
get Event Counter
Reimplemented in SyncObjectv1.
Definition at line 51 of file SyncObject.h.
View newest version in sPHENIX GitHub at line 51 of file SyncObject.h
Referenced by operator=().
virtual void SyncObject::EventNumber (const int) inline virtual
set Event Number
Reimplemented in SyncObjectv1.
Definition at line 39 of file SyncObject.h.
View newest version in sPHENIX GitHub at line 39 of file SyncObject.h
Referenced by Different(), operator=(), SyncReco::process_event(), DumpSyncObject::process_Node(), Fun4AllPrdfInputManager::run(), Fun4AllDstInputManager::SyncIt(), and SyncObjectv1::SyncObjectv1().
virtual int SyncObject::EventNumber () const inline protected virtual
get Event Number
Reimplemented in SyncObjectv1.
Definition at line 49 of file SyncObject.h.
View newest version in sPHENIX GitHub at line 49 of file SyncObject.h
Referenced by Different(), and operator=().
void SyncObject::identify (std::ostream & os = std::cout) const override virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from PHObject.
Reimplemented in SyncObjectv1.
Definition at line 15 of file SyncObject.cc.
View newest version in sPHENIX GitHub at line 15 of file SyncObject.cc
Referenced by SyncReco::process_event(), and Fun4AllDstInputManager::SyncIt().
int SyncObject::isValid () const override virtual
isValid returns non zero if object contains valid data
Reimplemented from PHObject.
Reimplemented in SyncObjectv1.
Definition at line 21 of file SyncObject.cc.
View newest version in sPHENIX GitHub at line 21 of file SyncObject.cc
References PHWHERE.
Referenced by DumpSyncObject::process_Node().
SyncObject & SyncObject::operator= (const SyncObject & source)
Definition at line 35 of file SyncObject.cc.
View newest version in sPHENIX GitHub at line 35 of file SyncObject.cc
References EventCounter(), EventNumber(), RunNumber(), and SegmentNumber().
void SyncObject::Reset () override virtual
Clear Sync.
Reimplemented from PHObject.
Reimplemented in SyncObjectv1.
Definition at line 9 of file SyncObject.cc.
View newest version in sPHENIX GitHub at line 9 of file SyncObject.cc
References PHWHERE.
Referenced by Fun4AllPrdfInputManager::ResetEvent().
virtual void SyncObject::RunNumber (const int) inline virtual
set Run Number
Reimplemented in SyncObjectv1.
Definition at line 45 of file SyncObject.h.
View newest version in sPHENIX GitHub at line 45 of file SyncObject.h
Referenced by Different(), SyncReco::InitRun(), operator=(), SyncReco::process_event(), DumpSyncObject::process_Node(), Fun4AllPrdfInputManager::run(), Fun4AllDstInputManager::SyncIt(), and SyncObjectv1::SyncObjectv1().
virtual int SyncObject::RunNumber () const inline protected virtual
get Run Number
Reimplemented in SyncObjectv1.
Definition at line 53 of file SyncObject.h.
View newest version in sPHENIX GitHub at line 53 of file SyncObject.h
Referenced by Different(), and operator=().
virtual void SyncObject::SegmentNumber (const int) inline virtual
set Segment Number
Reimplemented in SyncObjectv1.
Definition at line 42 of file SyncObject.h.
View newest version in sPHENIX GitHub at line 42 of file SyncObject.h
Referenced by operator=(), SyncReco::process_event(), DumpSyncObject::process_Node(), Fun4AllPrdfInputManager::run(), Fun4AllDstInputManager::SyncIt(), and SyncObjectv1::SyncObjectv1().
virtual int SyncObject::SegmentNumber () const inline protected virtual
get Segment Number
Reimplemented in SyncObjectv1.
Definition at line 55 of file SyncObject.h.
View newest version in sPHENIX GitHub at line 55 of file SyncObject.h
Referenced by operator=().
Friends And Related Function Documentation
friend class DumpSyncObject friend
Definition at line 61 of file SyncObject.h.
View newest version in sPHENIX GitHub at line 61 of file SyncObject.h
friend class Fun4AllDstInputManager friend
Definition at line 59 of file SyncObject.h.
View newest version in sPHENIX GitHub at line 59 of file SyncObject.h
friend class Fun4AllDstPileupInputManager friend
Definition at line 60 of file SyncObject.h.
View newest version in sPHENIX GitHub at line 60 of file SyncObject.h
friend class SegmentSelect friend
Definition at line 62 of file SyncObject.h.
View newest version in sPHENIX GitHub at line 62 of file SyncObject.h
friend class SyncObjectv1 friend
Definition at line 58 of file SyncObject.h.
View newest version in sPHENIX GitHub at line 58 of file SyncObject.h
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/framework/ffaobjects/SyncObject.h
coresoftware/blob/master/offline/framework/ffaobjects/SyncObject.cc