Analysis Software: PHG4HcalCellReco Class Reference
PHG4HcalCellReco Class Reference
#include <coresoftware/blob/master/simulation/g4simulation/g4detectors/PHG4HcalCellReco.h>
Public Member Functions
PHG4HcalCellReco (const std::string &name="HcalCellReco")
~PHG4HcalCellReco () override
int InitRun (PHCompositeNode *topNode) override
module initialization
int process_event (PHCompositeNode *topNode) override
event processing
void SetDefaultParameters () override
void Detector (const std::string &d)
void checkenergy (const int i=1)
void set_timing_window (const double tmi, const double tma)
void set_fixed_energy (const double efix)
Public Member Functions inherited from SubsysReco
~SubsysReco () override
virtual int End (PHCompositeNode *)
Called at the end of all processing.
virtual int EndRun (const int)
Called at the end of each run.
virtual int Init (PHCompositeNode *)
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
void Print (const std::string &="ALL") const override
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Public Member Functions inherited from PHParameterInterface
PHParameterInterface (const std::string &name)
PHParameterInterface (const PHParameterInterface &)=delete
PHParameterInterface & operator= (PHParameterInterface const &)=delete
virtual ~PHParameterInterface ()
void set_paramname (const std::string &name)
void set_double_param (const std::string &name, const double dval)
double get_double_param (const std::string &name) const
void set_int_param (const std::string &name, const int ival)
int get_int_param (const std::string &name) const
void set_string_param (const std::string &name, const std::string &sval)
std::string get_string_param (const std::string &name) const
void UpdateParametersWithMacro ()
void SaveToNodeTree (PHCompositeNode *runNode, const std::string &nodename)
void PutOnParNode (PHCompositeNode *parNode, const std::string &nodename)
void Print () const
Protected Member Functions
int CheckEnergy (PHCompositeNode *topNode)
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Protected Member Functions inherited from Fun4AllBase
Fun4AllBase (const std::string &name="NONAME")
Protected Member Functions inherited from PHParameterInterface
void set_default_double_param (const std::string &name, const double dval)
void set_default_int_param (const std::string &name, const int ival)
void set_default_string_param (const std::string &name, const std::string &sval)
void InitializeParameters ()
Protected Attributes
std::string detector
std::string hitnodename
std::string cellnodename
int chkenergyconservation = 0
double tmin = NAN
double tmax = NAN
double m_DeltaT = NAN
double m_FixedEnergy = NAN
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = std::numeric_limits<int>::max() - 10
}
Detailed Description
Definition at line 15 of file PHG4HcalCellReco.h.
View newest version in sPHENIX GitHub at line 15 of file PHG4HcalCellReco.h
Constructor & Destructor Documentation
PHG4HcalCellReco::PHG4HcalCellReco (const std::string & name = "HcalCellReco")
Definition at line 41 of file PHG4HcalCellReco.cc.
View newest version in sPHENIX GitHub at line 41 of file PHG4HcalCellReco.cc
References PHParameterInterface::InitializeParameters().
PHG4HcalCellReco::~PHG4HcalCellReco () inline override
Definition at line 20 of file PHG4HcalCellReco.h.
View newest version in sPHENIX GitHub at line 20 of file PHG4HcalCellReco.h
Member Function Documentation
void PHG4HcalCellReco::checkenergy (const int i = 1) inline
Definition at line 31 of file PHG4HcalCellReco.h.
View newest version in sPHENIX GitHub at line 31 of file PHG4HcalCellReco.h
References chkenergyconservation, and i.
int PHG4HcalCellReco::CheckEnergy (PHCompositeNode * topNode) protected
Definition at line 221 of file PHG4HcalCellReco.cc.
View newest version in sPHENIX GitHub at line 221 of file PHG4HcalCellReco.cc
References cellnodename, Acts::UnitConstants::e, PHG4HitContainer::getHits(), hitnodename, Fun4AllBase::Name(), and Fun4AllBase::Verbosity().
Referenced by process_event().
void PHG4HcalCellReco::Detector (const std::string & d) inline
Definition at line 30 of file PHG4HcalCellReco.h.
View newest version in sPHENIX GitHub at line 30 of file PHG4HcalCellReco.h
Referenced by HCALInner_Cells(), and HCALOuter_Cells().
int PHG4HcalCellReco::InitRun (PHCompositeNode * topNode) override virtual
module initialization
Reimplemented from SubsysReco.
Definition at line 48 of file PHG4HcalCellReco.cc.
View newest version in sPHENIX GitHub at line 48 of file PHG4HcalCellReco.cc
References PHCompositeNode::addNode(), cellnodename, detector, Fun4AllReturnCodes::EVENT_OK, PHNodeIterator::findFirst(), PHParameterInterface::get_double_param(), hitnodename, m_DeltaT, Fun4AllBase::Name(), PHWHERE, PHParameterInterface::PutOnParNode(), PHParameterInterface::SaveToNodeTree(), tmax, tmin, and PHParameterInterface::UpdateParametersWithMacro().
int PHG4HcalCellReco::process_event (PHCompositeNode * topNode) override virtual
event processing
Reimplemented from SubsysReco.
Definition at line 113 of file PHG4HcalCellReco.cc.
View newest version in sPHENIX GitHub at line 113 of file PHG4HcalCellReco.cc
References PHG4Cell::add_edep(), PHG4Cell::add_eion(), PHG4Cell::add_light_yield(), PHG4Cell::add_raw_light_yield(), PHG4CellContainer::AddCell(), cellnodename, CheckEnergy(), chkenergyconservation, COLUMNDIM, Fun4AllReturnCodes::EVENT_OK, PHG4CellDefs::ScintillatorSlatBinning::genkey(), PHG4HitContainer::getHits(), PHG4HitDefs::hit_idbits, hitnodename, m_DeltaT, m_FixedEnergy, Fun4AllBase::Name(), ROWDIM, tmax, tmin, and Fun4AllBase::Verbosity().
void PHG4HcalCellReco::set_fixed_energy (const double efix) inline
Definition at line 35 of file PHG4HcalCellReco.h.
View newest version in sPHENIX GitHub at line 35 of file PHG4HcalCellReco.h
References m_FixedEnergy.
void PHG4HcalCellReco::set_timing_window (const double tmi, const double tma)
Definition at line 267 of file PHG4HcalCellReco.cc.
View newest version in sPHENIX GitHub at line 267 of file PHG4HcalCellReco.cc
References PHParameterInterface::set_double_param().
void PHG4HcalCellReco::SetDefaultParameters () override virtual
Implements PHParameterInterface.
Definition at line 259 of file PHG4HcalCellReco.cc.
View newest version in sPHENIX GitHub at line 259 of file PHG4HcalCellReco.cc
References PHParameterInterface::set_default_double_param().
Member Data Documentation
std::string PHG4HcalCellReco::cellnodename protected
Definition at line 41 of file PHG4HcalCellReco.h.
View newest version in sPHENIX GitHub at line 41 of file PHG4HcalCellReco.h
Referenced by CheckEnergy(), InitRun(), and process_event().
int PHG4HcalCellReco::chkenergyconservation = 0 protected
Definition at line 43 of file PHG4HcalCellReco.h.
View newest version in sPHENIX GitHub at line 43 of file PHG4HcalCellReco.h
Referenced by checkenergy(), and process_event().
std::string PHG4HcalCellReco::detector protected
Definition at line 39 of file PHG4HcalCellReco.h.
View newest version in sPHENIX GitHub at line 39 of file PHG4HcalCellReco.h
Referenced by InitRun().
std::string PHG4HcalCellReco::hitnodename protected
Definition at line 40 of file PHG4HcalCellReco.h.
View newest version in sPHENIX GitHub at line 40 of file PHG4HcalCellReco.h
Referenced by CheckEnergy(), InitRun(), and process_event().
double PHG4HcalCellReco::m_DeltaT = NAN protected
Definition at line 47 of file PHG4HcalCellReco.h.
View newest version in sPHENIX GitHub at line 47 of file PHG4HcalCellReco.h
Referenced by InitRun(), and process_event().
double PHG4HcalCellReco::m_FixedEnergy = NAN protected
Definition at line 48 of file PHG4HcalCellReco.h.
View newest version in sPHENIX GitHub at line 48 of file PHG4HcalCellReco.h
Referenced by process_event(), and set_fixed_energy().
double PHG4HcalCellReco::tmax = NAN protected
Definition at line 46 of file PHG4HcalCellReco.h.
View newest version in sPHENIX GitHub at line 46 of file PHG4HcalCellReco.h
Referenced by InitRun(), and process_event().
double PHG4HcalCellReco::tmin = NAN protected
Definition at line 45 of file PHG4HcalCellReco.h.
View newest version in sPHENIX GitHub at line 45 of file PHG4HcalCellReco.h
Referenced by InitRun(), and process_event().
The documentation for this class was generated from the following files:
coresoftware/blob/master/simulation/g4simulation/g4detectors/PHG4HcalCellReco.h
coresoftware/blob/master/simulation/g4simulation/g4detectors/PHG4HcalCellReco.cc