Analysis Software: daqPRDFEvent Class Reference
daqPRDFEvent Class Reference
#include <rcdaq/blob/master/daqPRDFEvent.h>
Public Member Functions
daqPRDFEvent (int *, const int maxlength, const int irun, const int itype, const int eseq)
~daqPRDFEvent ()
int prepare_next ()
int prepare_next (const int, const int)
int addSubevent (const int etype, daq_device *)
Public Member Functions inherited from daqEvent
virtual ~daqEvent ()
virtual void set_event_type (const int)
Additional Inherited Members
Protected Attributes inherited from daqEvent
int * event_base
int current
evtdata_ptr evthdr
int max_length
int left
Detailed Description
Definition at line 7 of file daqPRDFEvent.h.
View newest version in sPHENIX GitHub at line 7 of file daqPRDFEvent.h
Constructor & Destructor Documentation
daqPRDFEvent::daqPRDFEvent (int * where, const int maxlength, const int irun, const int itype, const int eseq)
Definition at line 7 of file daqPRDFEvent.cc.
View newest version in sPHENIX GitHub at line 7 of file daqPRDFEvent.cc
References daqEvent::event_base, evt_data::evt_type, daqEvent::evthdr, G4PLUGDOOR::length, daqEvent::max_length, and prepare_next().
daqPRDFEvent::~daqPRDFEvent () inline
Definition at line 15 of file daqPRDFEvent.h.
View newest version in sPHENIX GitHub at line 15 of file daqPRDFEvent.h
Member Function Documentation
int daqPRDFEvent::addSubevent (const int etype, daq_device * dev) virtual
Implements daqEvent.
Definition at line 18 of file daqPRDFEvent.cc.
View newest version in sPHENIX GitHub at line 18 of file daqPRDFEvent.cc
References daqEvent::current, evt_data::data, evt_data::evt_length, daqEvent::evthdr, daqEvent::left, and daq_device::put_data().
int daqPRDFEvent::prepare_next () virtual
Implements daqEvent.
Definition at line 33 of file daqPRDFEvent.cc.
View newest version in sPHENIX GitHub at line 33 of file daqPRDFEvent.cc
Referenced by daqPRDFEvent().
int daqPRDFEvent::prepare_next (const int evtseq, const int irun) virtual
Implements daqEvent.
Definition at line 38 of file daqPRDFEvent.cc.
View newest version in sPHENIX GitHub at line 38 of file daqPRDFEvent.cc
References daqEvent::current, evt_data::data, evt_data::date, evt_data::evt_length, evt_data::evt_sequence, daqEvent::evthdr, EVTHEADERLENGTH, daqEvent::left, daqEvent::max_length, evt_data::reserved, evt_data::run_number, evt_data::time, and Acts::Test::time.
The documentation for this class was generated from the following files:
rcdaq/blob/master/daqPRDFEvent.h
rcdaq/blob/master/daqPRDFEvent.cc