Analysis Software: CaloTriggerInfo Class Reference
CaloTriggerInfo Class Reference
#include <coresoftware/blob/master/offline/packages/trigger/CaloTriggerInfo.h>
Public Member Functions
~CaloTriggerInfo () override
void identify (std::ostream &os=std::cout) const override
int isValid () const override
isValid returns non zero if object contains vailid data
virtual void set_best_EMCal_2x2_E (const float)
virtual void set_best_EMCal_2x2_eta (const float)
virtual void set_best_EMCal_2x2_phi (const float)
virtual float get_best_EMCal_2x2_E () const
virtual float get_best_EMCal_2x2_eta () const
virtual float get_best_EMCal_2x2_phi () const
virtual void set_best_EMCal_4x4_E (const float)
virtual void set_best_EMCal_4x4_eta (const float)
virtual void set_best_EMCal_4x4_phi (const float)
virtual float get_best_EMCal_4x4_E () const
virtual float get_best_EMCal_4x4_eta () const
virtual float get_best_EMCal_4x4_phi () const
virtual void set_best2_EMCal_4x4_E (const float)
virtual void set_best2_EMCal_4x4_eta (const float)
virtual void set_best2_EMCal_4x4_phi (const float)
virtual float get_best2_EMCal_4x4_E () const
virtual float get_best2_EMCal_4x4_eta () const
virtual float get_best2_EMCal_4x4_phi () const
virtual void set_best_FullCalo_0p2x0p2_E (const float)
virtual void set_best_FullCalo_0p2x0p2_eta (const float)
virtual void set_best_FullCalo_0p2x0p2_phi (const float)
virtual float get_best_FullCalo_0p2x0p2_E () const
virtual float get_best_FullCalo_0p2x0p2_eta () const
virtual float get_best_FullCalo_0p2x0p2_phi () const
virtual void set_best_FullCalo_0p4x0p4_E (const float)
virtual void set_best_FullCalo_0p4x0p4_eta (const float)
virtual void set_best_FullCalo_0p4x0p4_phi (const float)
virtual float get_best_FullCalo_0p4x0p4_E () const
virtual float get_best_FullCalo_0p4x0p4_eta () const
virtual float get_best_FullCalo_0p4x0p4_phi () const
virtual void set_best_FullCalo_0p6x0p6_E (const float)
virtual void set_best_FullCalo_0p6x0p6_eta (const float)
virtual void set_best_FullCalo_0p6x0p6_phi (const float)
virtual float get_best_FullCalo_0p6x0p6_E () const
virtual float get_best_FullCalo_0p6x0p6_eta () const
virtual float get_best_FullCalo_0p6x0p6_phi () const
virtual void set_best_FullCalo_0p8x0p8_E (const float)
virtual void set_best_FullCalo_0p8x0p8_eta (const float)
virtual void set_best_FullCalo_0p8x0p8_phi (const float)
virtual float get_best_FullCalo_0p8x0p8_E () const
virtual float get_best_FullCalo_0p8x0p8_eta () const
virtual float get_best_FullCalo_0p8x0p8_phi () const
virtual void set_best_FullCalo_1p0x1p0_E (const float)
virtual void set_best_FullCalo_1p0x1p0_eta (const float)
virtual void set_best_FullCalo_1p0x1p0_phi (const float)
virtual float get_best_FullCalo_1p0x1p0_E () const
virtual float get_best_FullCalo_1p0x1p0_eta () const
virtual float get_best_FullCalo_1p0x1p0_phi () const
Public Member Functions inherited from PHObject
PHObject ()
ctor
~PHObject () override
dtor
virtual PHObject * CloneMe () const
Virtual copy constructor.
virtual PHObject * clone () const final
PHObject * Clone (const char *newname="") const final
void Copy (TObject &object) const final
virtual void Reset ()
Clear Event.
virtual int Integrate () const
virtual int Integrate (PHObject *)
virtual void CopyFrom (const PHObject *obj)
Protected Member Functions
CaloTriggerInfo ()
Private Member Functions
ClassDefOverride (CaloTriggerInfo, 1)
Detailed Description
Definition at line 6 of file CaloTriggerInfo.h.
View newest version in sPHENIX GitHub at line 6 of file CaloTriggerInfo.h
Constructor & Destructor Documentation
CaloTriggerInfo::~CaloTriggerInfo () inline override
Definition at line 9 of file CaloTriggerInfo.h.
View newest version in sPHENIX GitHub at line 9 of file CaloTriggerInfo.h
CaloTriggerInfo::CaloTriggerInfo () inline protected
Definition at line 87 of file CaloTriggerInfo.h.
View newest version in sPHENIX GitHub at line 87 of file CaloTriggerInfo.h
Member Function Documentation
CaloTriggerInfo::ClassDefOverride (CaloTriggerInfo , 1) private
virtual float CaloTriggerInfo::get_best2_EMCal_4x4_E () const inline virtual
Reimplemented in CaloTriggerInfov1.
Definition at line 37 of file CaloTriggerInfo.h.
View newest version in sPHENIX GitHub at line 37 of file CaloTriggerInfo.h
Referenced by DumpCaloTriggerInfo::process_Node().
virtual float CaloTriggerInfo::get_best2_EMCal_4x4_eta () const inline virtual
Reimplemented in CaloTriggerInfov1.
Definition at line 38 of file CaloTriggerInfo.h.
View newest version in sPHENIX GitHub at line 38 of file CaloTriggerInfo.h
Referenced by DumpCaloTriggerInfo::process_Node().
virtual float CaloTriggerInfo::get_best2_EMCal_4x4_phi () const inline virtual
Reimplemented in CaloTriggerInfov1.
Definition at line 39 of file CaloTriggerInfo.h.
View newest version in sPHENIX GitHub at line 39 of file CaloTriggerInfo.h
Referenced by DumpCaloTriggerInfo::process_Node().
virtual float CaloTriggerInfo::get_best_EMCal_2x2_E () const inline virtual
Reimplemented in CaloTriggerInfov1.
Definition at line 19 of file CaloTriggerInfo.h.
View newest version in sPHENIX GitHub at line 19 of file CaloTriggerInfo.h
Referenced by DumpCaloTriggerInfo::process_Node().
virtual float CaloTriggerInfo::get_best_EMCal_2x2_eta () const inline virtual
Reimplemented in CaloTriggerInfov1.
Definition at line 20 of file CaloTriggerInfo.h.
View newest version in sPHENIX GitHub at line 20 of file CaloTriggerInfo.h
Referenced by DumpCaloTriggerInfo::process_Node().
virtual float CaloTriggerInfo::get_best_EMCal_2x2_phi () const inline virtual
Reimplemented in CaloTriggerInfov1.
Definition at line 21 of file CaloTriggerInfo.h.
View newest version in sPHENIX GitHub at line 21 of file CaloTriggerInfo.h
Referenced by DumpCaloTriggerInfo::process_Node().
virtual float CaloTriggerInfo::get_best_EMCal_4x4_E () const inline virtual
Reimplemented in CaloTriggerInfov1.
Definition at line 28 of file CaloTriggerInfo.h.
View newest version in sPHENIX GitHub at line 28 of file CaloTriggerInfo.h
Referenced by AnaTutorial::getEMCalClusters(), and DumpCaloTriggerInfo::process_Node().
virtual float CaloTriggerInfo::get_best_EMCal_4x4_eta () const inline virtual
Reimplemented in CaloTriggerInfov1.
Definition at line 29 of file CaloTriggerInfo.h.
View newest version in sPHENIX GitHub at line 29 of file CaloTriggerInfo.h
Referenced by DumpCaloTriggerInfo::process_Node().
virtual float CaloTriggerInfo::get_best_EMCal_4x4_phi () const inline virtual
Reimplemented in CaloTriggerInfov1.
Definition at line 30 of file CaloTriggerInfo.h.
View newest version in sPHENIX GitHub at line 30 of file CaloTriggerInfo.h
Referenced by DumpCaloTriggerInfo::process_Node().
virtual float CaloTriggerInfo::get_best_FullCalo_0p2x0p2_E () const inline virtual
Reimplemented in CaloTriggerInfov1.
Definition at line 46 of file CaloTriggerInfo.h.
View newest version in sPHENIX GitHub at line 46 of file CaloTriggerInfo.h
Referenced by DumpCaloTriggerInfo::process_Node().
virtual float CaloTriggerInfo::get_best_FullCalo_0p2x0p2_eta () const inline virtual
Reimplemented in CaloTriggerInfov1.
Definition at line 47 of file CaloTriggerInfo.h.
View newest version in sPHENIX GitHub at line 47 of file CaloTriggerInfo.h
Referenced by DumpCaloTriggerInfo::process_Node().
virtual float CaloTriggerInfo::get_best_FullCalo_0p2x0p2_phi () const inline virtual
Reimplemented in CaloTriggerInfov1.
Definition at line 48 of file CaloTriggerInfo.h.
View newest version in sPHENIX GitHub at line 48 of file CaloTriggerInfo.h
Referenced by DumpCaloTriggerInfo::process_Node().
virtual float CaloTriggerInfo::get_best_FullCalo_0p4x0p4_E () const inline virtual
Reimplemented in CaloTriggerInfov1.
Definition at line 55 of file CaloTriggerInfo.h.
View newest version in sPHENIX GitHub at line 55 of file CaloTriggerInfo.h
Referenced by DumpCaloTriggerInfo::process_Node().
virtual float CaloTriggerInfo::get_best_FullCalo_0p4x0p4_eta () const inline virtual
Reimplemented in CaloTriggerInfov1.
Definition at line 56 of file CaloTriggerInfo.h.
View newest version in sPHENIX GitHub at line 56 of file CaloTriggerInfo.h
Referenced by DumpCaloTriggerInfo::process_Node().
virtual float CaloTriggerInfo::get_best_FullCalo_0p4x0p4_phi () const inline virtual
Reimplemented in CaloTriggerInfov1.
Definition at line 57 of file CaloTriggerInfo.h.
View newest version in sPHENIX GitHub at line 57 of file CaloTriggerInfo.h
Referenced by DumpCaloTriggerInfo::process_Node().
virtual float CaloTriggerInfo::get_best_FullCalo_0p6x0p6_E () const inline virtual
Reimplemented in CaloTriggerInfov1.
Definition at line 64 of file CaloTriggerInfo.h.
View newest version in sPHENIX GitHub at line 64 of file CaloTriggerInfo.h
Referenced by DumpCaloTriggerInfo::process_Node().
virtual float CaloTriggerInfo::get_best_FullCalo_0p6x0p6_eta () const inline virtual
Reimplemented in CaloTriggerInfov1.
Definition at line 65 of file CaloTriggerInfo.h.
View newest version in sPHENIX GitHub at line 65 of file CaloTriggerInfo.h
Referenced by DumpCaloTriggerInfo::process_Node().
virtual float CaloTriggerInfo::get_best_FullCalo_0p6x0p6_phi () const inline virtual
Reimplemented in CaloTriggerInfov1.
Definition at line 66 of file CaloTriggerInfo.h.
View newest version in sPHENIX GitHub at line 66 of file CaloTriggerInfo.h
Referenced by DumpCaloTriggerInfo::process_Node().
virtual float CaloTriggerInfo::get_best_FullCalo_0p8x0p8_E () const inline virtual
Reimplemented in CaloTriggerInfov1.
Definition at line 73 of file CaloTriggerInfo.h.
View newest version in sPHENIX GitHub at line 73 of file CaloTriggerInfo.h
Referenced by DumpCaloTriggerInfo::process_Node().
virtual float CaloTriggerInfo::get_best_FullCalo_0p8x0p8_eta () const inline virtual
Reimplemented in CaloTriggerInfov1.
Definition at line 74 of file CaloTriggerInfo.h.
View newest version in sPHENIX GitHub at line 74 of file CaloTriggerInfo.h
Referenced by DumpCaloTriggerInfo::process_Node().
virtual float CaloTriggerInfo::get_best_FullCalo_0p8x0p8_phi () const inline virtual
Reimplemented in CaloTriggerInfov1.
Definition at line 75 of file CaloTriggerInfo.h.
View newest version in sPHENIX GitHub at line 75 of file CaloTriggerInfo.h
Referenced by DumpCaloTriggerInfo::process_Node().
virtual float CaloTriggerInfo::get_best_FullCalo_1p0x1p0_E () const inline virtual
Reimplemented in CaloTriggerInfov1.
Definition at line 82 of file CaloTriggerInfo.h.
View newest version in sPHENIX GitHub at line 82 of file CaloTriggerInfo.h
Referenced by DumpCaloTriggerInfo::process_Node().
virtual float CaloTriggerInfo::get_best_FullCalo_1p0x1p0_eta () const inline virtual
Reimplemented in CaloTriggerInfov1.
Definition at line 83 of file CaloTriggerInfo.h.
View newest version in sPHENIX GitHub at line 83 of file CaloTriggerInfo.h
Referenced by DumpCaloTriggerInfo::process_Node().
virtual float CaloTriggerInfo::get_best_FullCalo_1p0x1p0_phi () const inline virtual
Reimplemented in CaloTriggerInfov1.
Definition at line 84 of file CaloTriggerInfo.h.
View newest version in sPHENIX GitHub at line 84 of file CaloTriggerInfo.h
Referenced by DumpCaloTriggerInfo::process_Node().
void CaloTriggerInfo::identify (std::ostream & os = std::cout) const inline override virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from PHObject.
Reimplemented in CaloTriggerInfov1.
Definition at line 11 of file CaloTriggerInfo.h.
View newest version in sPHENIX GitHub at line 11 of file CaloTriggerInfo.h
References os.
int CaloTriggerInfo::isValid () const inline override virtual
isValid returns non zero if object contains vailid data
Reimplemented from PHObject.
Reimplemented in CaloTriggerInfov1.
Definition at line 12 of file CaloTriggerInfo.h.
View newest version in sPHENIX GitHub at line 12 of file CaloTriggerInfo.h
virtual void CaloTriggerInfo::set_best2_EMCal_4x4_E (const float) inline virtual
Reimplemented in CaloTriggerInfov1.
Definition at line 33 of file CaloTriggerInfo.h.
View newest version in sPHENIX GitHub at line 33 of file CaloTriggerInfo.h
Referenced by CaloTriggerSim::FillNode().
virtual void CaloTriggerInfo::set_best2_EMCal_4x4_eta (const float) inline virtual
Reimplemented in CaloTriggerInfov1.
Definition at line 34 of file CaloTriggerInfo.h.
View newest version in sPHENIX GitHub at line 34 of file CaloTriggerInfo.h
Referenced by CaloTriggerSim::FillNode().
virtual void CaloTriggerInfo::set_best2_EMCal_4x4_phi (const float) inline virtual
Reimplemented in CaloTriggerInfov1.
Definition at line 35 of file CaloTriggerInfo.h.
View newest version in sPHENIX GitHub at line 35 of file CaloTriggerInfo.h
Referenced by CaloTriggerSim::FillNode().
virtual void CaloTriggerInfo::set_best_EMCal_2x2_E (const float) inline virtual
Reimplemented in CaloTriggerInfov1.
Definition at line 15 of file CaloTriggerInfo.h.
View newest version in sPHENIX GitHub at line 15 of file CaloTriggerInfo.h
Referenced by CaloTriggerSim::FillNode().
virtual void CaloTriggerInfo::set_best_EMCal_2x2_eta (const float) inline virtual
Reimplemented in CaloTriggerInfov1.
Definition at line 16 of file CaloTriggerInfo.h.
View newest version in sPHENIX GitHub at line 16 of file CaloTriggerInfo.h
Referenced by CaloTriggerSim::FillNode().
virtual void CaloTriggerInfo::set_best_EMCal_2x2_phi (const float) inline virtual
Reimplemented in CaloTriggerInfov1.
Definition at line 17 of file CaloTriggerInfo.h.
View newest version in sPHENIX GitHub at line 17 of file CaloTriggerInfo.h
Referenced by CaloTriggerSim::FillNode().
virtual void CaloTriggerInfo::set_best_EMCal_4x4_E (const float) inline virtual
Reimplemented in CaloTriggerInfov1.
Definition at line 24 of file CaloTriggerInfo.h.
View newest version in sPHENIX GitHub at line 24 of file CaloTriggerInfo.h
Referenced by CaloTriggerSim::FillNode().
virtual void CaloTriggerInfo::set_best_EMCal_4x4_eta (const float) inline virtual
Reimplemented in CaloTriggerInfov1.
Definition at line 25 of file CaloTriggerInfo.h.
View newest version in sPHENIX GitHub at line 25 of file CaloTriggerInfo.h
Referenced by CaloTriggerSim::FillNode().
virtual void CaloTriggerInfo::set_best_EMCal_4x4_phi (const float) inline virtual
Reimplemented in CaloTriggerInfov1.
Definition at line 26 of file CaloTriggerInfo.h.
View newest version in sPHENIX GitHub at line 26 of file CaloTriggerInfo.h
Referenced by CaloTriggerSim::FillNode().
virtual void CaloTriggerInfo::set_best_FullCalo_0p2x0p2_E (const float) inline virtual
Reimplemented in CaloTriggerInfov1.
Definition at line 42 of file CaloTriggerInfo.h.
View newest version in sPHENIX GitHub at line 42 of file CaloTriggerInfo.h
Referenced by CaloTriggerSim::FillNode().
virtual void CaloTriggerInfo::set_best_FullCalo_0p2x0p2_eta (const float) inline virtual
Reimplemented in CaloTriggerInfov1.
Definition at line 43 of file CaloTriggerInfo.h.
View newest version in sPHENIX GitHub at line 43 of file CaloTriggerInfo.h
Referenced by CaloTriggerSim::FillNode().
virtual void CaloTriggerInfo::set_best_FullCalo_0p2x0p2_phi (const float) inline virtual
Reimplemented in CaloTriggerInfov1.
Definition at line 44 of file CaloTriggerInfo.h.
View newest version in sPHENIX GitHub at line 44 of file CaloTriggerInfo.h
Referenced by CaloTriggerSim::FillNode().
virtual void CaloTriggerInfo::set_best_FullCalo_0p4x0p4_E (const float) inline virtual
Reimplemented in CaloTriggerInfov1.
Definition at line 51 of file CaloTriggerInfo.h.
View newest version in sPHENIX GitHub at line 51 of file CaloTriggerInfo.h
Referenced by CaloTriggerSim::FillNode().
virtual void CaloTriggerInfo::set_best_FullCalo_0p4x0p4_eta (const float) inline virtual
Reimplemented in CaloTriggerInfov1.
Definition at line 52 of file CaloTriggerInfo.h.
View newest version in sPHENIX GitHub at line 52 of file CaloTriggerInfo.h
Referenced by CaloTriggerSim::FillNode().
virtual void CaloTriggerInfo::set_best_FullCalo_0p4x0p4_phi (const float) inline virtual
Reimplemented in CaloTriggerInfov1.
Definition at line 53 of file CaloTriggerInfo.h.
View newest version in sPHENIX GitHub at line 53 of file CaloTriggerInfo.h
Referenced by CaloTriggerSim::FillNode().
virtual void CaloTriggerInfo::set_best_FullCalo_0p6x0p6_E (const float) inline virtual
Reimplemented in CaloTriggerInfov1.
Definition at line 60 of file CaloTriggerInfo.h.
View newest version in sPHENIX GitHub at line 60 of file CaloTriggerInfo.h
Referenced by CaloTriggerSim::FillNode().
virtual void CaloTriggerInfo::set_best_FullCalo_0p6x0p6_eta (const float) inline virtual
Reimplemented in CaloTriggerInfov1.
Definition at line 61 of file CaloTriggerInfo.h.
View newest version in sPHENIX GitHub at line 61 of file CaloTriggerInfo.h
Referenced by CaloTriggerSim::FillNode().
virtual void CaloTriggerInfo::set_best_FullCalo_0p6x0p6_phi (const float) inline virtual
Reimplemented in CaloTriggerInfov1.
Definition at line 62 of file CaloTriggerInfo.h.
View newest version in sPHENIX GitHub at line 62 of file CaloTriggerInfo.h
Referenced by CaloTriggerSim::FillNode().
virtual void CaloTriggerInfo::set_best_FullCalo_0p8x0p8_E (const float) inline virtual
Reimplemented in CaloTriggerInfov1.
Definition at line 69 of file CaloTriggerInfo.h.
View newest version in sPHENIX GitHub at line 69 of file CaloTriggerInfo.h
Referenced by CaloTriggerSim::FillNode().
virtual void CaloTriggerInfo::set_best_FullCalo_0p8x0p8_eta (const float) inline virtual
Reimplemented in CaloTriggerInfov1.
Definition at line 70 of file CaloTriggerInfo.h.
View newest version in sPHENIX GitHub at line 70 of file CaloTriggerInfo.h
Referenced by CaloTriggerSim::FillNode().
virtual void CaloTriggerInfo::set_best_FullCalo_0p8x0p8_phi (const float) inline virtual
Reimplemented in CaloTriggerInfov1.
Definition at line 71 of file CaloTriggerInfo.h.
View newest version in sPHENIX GitHub at line 71 of file CaloTriggerInfo.h
Referenced by CaloTriggerSim::FillNode().
virtual void CaloTriggerInfo::set_best_FullCalo_1p0x1p0_E (const float) inline virtual
Reimplemented in CaloTriggerInfov1.
Definition at line 78 of file CaloTriggerInfo.h.
View newest version in sPHENIX GitHub at line 78 of file CaloTriggerInfo.h
Referenced by CaloTriggerSim::FillNode().
virtual void CaloTriggerInfo::set_best_FullCalo_1p0x1p0_eta (const float) inline virtual
Reimplemented in CaloTriggerInfov1.
Definition at line 79 of file CaloTriggerInfo.h.
View newest version in sPHENIX GitHub at line 79 of file CaloTriggerInfo.h
Referenced by CaloTriggerSim::FillNode().
virtual void CaloTriggerInfo::set_best_FullCalo_1p0x1p0_phi (const float) inline virtual
Reimplemented in CaloTriggerInfov1.
Definition at line 80 of file CaloTriggerInfo.h.
View newest version in sPHENIX GitHub at line 80 of file CaloTriggerInfo.h
Referenced by CaloTriggerSim::FillNode().
The documentation for this class was generated from the following file:
coresoftware/blob/master/offline/packages/trigger/CaloTriggerInfo.h