Analysis Software: ActsExamples::ParticleSmearing Exception Reference
ActsExamples::ParticleSmearing Exception Reference final
#include <acts/blob/sPHENIX/Examples/Algorithms/TruthTracking/ActsExamples/TruthTracking/ParticleSmearing.hpp>
Classes
struct Config
Public Member Functions
ParticleSmearing (const Config &config, Acts::Logging::Level level)
ProcessCode execute (const AlgorithmContext &ctx) const override
const Config & config () const
Get readonly access to the config parameters.
Public Member Functions inherited from ActsExamples::IAlgorithm
IAlgorithm (std::string name, Acts::Logging::Level level=Acts::Logging::INFO)
std::string name () const override
The algorithm name.
ProcessCode internalExecute (const AlgorithmContext &context) final
ProcessCode initialize () override
Initialize the algorithm.
ProcessCode finalize () override
Finalize the algorithm.
Private Attributes
Config m_cfg
ReadDataHandle
< SimParticleContainer > m_inputParticles {this, "InputParticles"}
WriteDataHandle
< TrackParametersContainer > m_outputTrackParameters
Additional Inherited Members
Protected Member Functions inherited from ActsExamples::IAlgorithm
const Acts::Logger & logger () const
Detailed Description
Create track states by smearing truth particle information.
Particles are smeared in the perigee frame anchored at their true vertex position. The d0 and z0 parameters are always defined within that perigee frame and not globally. The generated bound parameters are stored in the same order as the input particles.
Definition at line 37 of file ParticleSmearing.hpp.
View newest version in sPHENIX GitHub at line 37 of file ParticleSmearing.hpp
Constructor & Destructor Documentation
ActsExamples::ParticleSmearing::ParticleSmearing (const Config & config, Acts::Logging::Level level)
Definition at line 33 of file ParticleSmearing.cpp.
View newest version in sPHENIX GitHub at line 33 of file ParticleSmearing.cpp
References ACTS_INFO, ActsExamples::WriteDataHandle< T >::initialize(), ActsExamples::ReadDataHandle< T >::initialize(), ActsExamples::ParticleSmearing::Config::inputParticles, m_cfg, m_inputParticles, m_outputTrackParameters, ActsExamples::ParticleSmearing::Config::outputTrackParameters, ActsExamples::ParticleSmearing::Config::particleHypothesis, and ActsExamples::ParticleSmearing::Config::randomNumbers.
Member Function Documentation
const Config& ActsExamples::ParticleSmearing::config () const inline
Get readonly access to the config parameters.
Definition at line 78 of file ParticleSmearing.hpp.
View newest version in sPHENIX GitHub at line 78 of file ParticleSmearing.hpp
References m_cfg.
ActsExamples::ProcessCode ActsExamples::ParticleSmearing::execute (const AlgorithmContext & context) const override virtual
Execute the algorithm for one event.
This function must be implemented by subclasses.
Implements ActsExamples::IAlgorithm.
Definition at line 55 of file ParticleSmearing.cpp.
View newest version in sPHENIX GitHub at line 55 of file ParticleSmearing.cpp
References ACTS_VERBOSE, Acts::Test::cov, Acts::eBoundLoc0, Acts::eBoundLoc1, Acts::eBoundPhi, Acts::eBoundQOverP, Acts::eBoundSize, Acts::eBoundTheta, Acts::eBoundTime, ActsExamples::AlgorithmContext::geoContext, ActsExamples::groupBySecondaryVertex(), i, m_cfg(), Acts::detail::normalizePhiTheta(), merge_hashes::p, Dataset::parameters, particle, particleHypothesis, particles, ActsTests::PropagationDatasets::phi, Acts::VectorHelpers::phi(), physmon_track_finding_ttbar::pt, conftest::rng(), ActsTests::PropagationDatasets::theta, Acts::VectorHelpers::theta(), and Acts::Test::time.
Member Data Documentation
Config ActsExamples::ParticleSmearing::m_cfg private
Definition at line 81 of file ParticleSmearing.hpp.
View newest version in sPHENIX GitHub at line 81 of file ParticleSmearing.hpp
Referenced by config(), and ParticleSmearing().
ReadDataHandle<SimParticleContainer> ActsExamples::ParticleSmearing::m_inputParticles {this, "InputParticles"} private
Definition at line 83 of file ParticleSmearing.hpp.
View newest version in sPHENIX GitHub at line 83 of file ParticleSmearing.hpp
Referenced by ParticleSmearing().
WriteDataHandle<TrackParametersContainer> ActsExamples::ParticleSmearing::m_outputTrackParameters private
Initial value:
{
      this, "OutputTrackParameters"}
Definition at line 85 of file ParticleSmearing.hpp.
View newest version in sPHENIX GitHub at line 85 of file ParticleSmearing.hpp
Referenced by ParticleSmearing().
The documentation for this exception was generated from the following files:
acts/blob/sPHENIX/Examples/Algorithms/TruthTracking/ActsExamples/TruthTracking/ParticleSmearing.hpp
acts/blob/sPHENIX/Examples/Algorithms/TruthTracking/ActsExamples/TruthTracking/ParticleSmearing.cpp