Analysis Software: acts/blob/sPHENIX/Tests/IntegrationTests/PropagationEigenConstant.cpp File Reference
PropagationEigenConstant.cpp File Reference
#include <boost/test/data/test_case.hpp>
#include <boost/test/unit_test.hpp>
#include "Acts/Geometry/GeometryContext.hpp"
#include "Acts/MagneticField/ConstantBField.hpp"
#include "Acts/MagneticField/MagneticFieldContext.hpp"
#include "Acts/Propagator/EigenStepper.hpp"
#include "Acts/Propagator/Propagator.hpp"
#include "Acts/Propagator/RiddersPropagator.hpp"
#include <limits>
#include "PropagationDatasets.hpp"
#include "PropagationTests.hpp"
Functions
BOOST_DATA_TEST_CASE (ForwardBackward, ds::phi *ds::theta *ds::absMomentum *ds::chargeNonZero *ds::pathLength *ds::magneticField, phi, theta, p, q, s, bz)
BOOST_DATA_TEST_CASE (ToCylinderAlongZ, ds::phi *ds::thetaWithoutBeam *ds::absMomentum *ds::chargeNonZero *ds::pathLength *ds::magneticField, phi, theta, p, q, s, bz)
BOOST_DATA_TEST_CASE (ToDisc, ds::phi *ds::theta *ds::absMomentum *ds::chargeNonZero *ds::pathLength *ds::magneticField, phi, theta, p, q, s, bz)
BOOST_DATA_TEST_CASE (ToPlane, ds::phi *ds::theta *ds::absMomentum *ds::chargeNonZero *ds::pathLength *ds::magneticField, phi, theta, p, q, s, bz)
BOOST_DATA_TEST_CASE (ToStrawAlongZ, ds::phi *ds::thetaWithoutBeam *ds::absMomentum *ds::chargeNonZero *ds::pathLength *ds::magneticField, phi, theta, p, q, s, bz)
BOOST_DATA_TEST_CASE (CovarianceCurvilinear, ds::phi *ds::theta *ds::absMomentum *ds::chargeNonZero *ds::pathLength *ds::magneticField, phi, theta, p, q, s, bz)
BOOST_DATA_TEST_CASE (CovarianceToCylinderAlongZ, ds::phiWithoutAmbiguity *ds::thetaWithoutBeam *ds::absMomentum *ds::chargeNonZero *ds::pathLength *ds::magneticField, phi, theta, p, q, s, bz)
BOOST_DATA_TEST_CASE (CovarianceToDisc, ds::phi *ds::thetaWithoutBeam *ds::absMomentum *ds::chargeNonZero *ds::pathLength *ds::magneticField, phi, theta, p, q, s, bz)
BOOST_DATA_TEST_CASE (CovarianceToPlane, ds::phi *ds::theta *ds::absMomentum *ds::chargeNonZero *ds::pathLength *ds::magneticField, phi, theta, p, q, s, bz)
BOOST_DATA_TEST_CASE (CovarianceToStrawAlongZ, ds::phi *ds::thetaWithoutBeam *ds::absMomentum *ds::chargeNonZero *ds::pathLength *ds::magneticField, phi, theta, p, q, s, bz)
Function Documentation
BOOST_DATA_TEST_CASE (ForwardBackward , ds::phi *ds::theta *ds::absMomentum *ds::chargeNonZero *ds::pathLength *ds::magneticField , phi , theta , p , q , s , bz)
Definition at line 62 of file PropagationEigenConstant.cpp.
View newest version in sPHENIX GitHub at line 62 of file PropagationEigenConstant.cpp
References geoCtx, magCtx, makeParametersCurvilinear(), and runForwardBackwardTest().
BOOST_DATA_TEST_CASE (ToCylinderAlongZ , ds::phi *ds::thetaWithoutBeam *ds::absMomentum *ds::chargeNonZero *ds::pathLength *ds::magneticField , phi , theta , p , q , s , bz)
Definition at line 74 of file PropagationEigenConstant.cpp.
View newest version in sPHENIX GitHub at line 74 of file PropagationEigenConstant.cpp
References geoCtx, magCtx, makeParametersCurvilinear(), merge_hashes::p, ActsTests::PropagationDatasets::phi, runToSurfaceTest(), physmon_simulation::s, and ActsTests::PropagationDatasets::theta.
BOOST_DATA_TEST_CASE (ToDisc , ds::phi *ds::theta *ds::absMomentum *ds::chargeNonZero *ds::pathLength *ds::magneticField , phi , theta , p , q , s , bz)
Definition at line 83 of file PropagationEigenConstant.cpp.
View newest version in sPHENIX GitHub at line 83 of file PropagationEigenConstant.cpp
References geoCtx, magCtx, makeParametersCurvilinear(), merge_hashes::p, ActsTests::PropagationDatasets::phi, runToSurfaceTest(), physmon_simulation::s, and ActsTests::PropagationDatasets::theta.
BOOST_DATA_TEST_CASE (ToPlane , ds::phi *ds::theta *ds::absMomentum *ds::chargeNonZero *ds::pathLength *ds::magneticField , phi , theta , p , q , s , bz)
Definition at line 92 of file PropagationEigenConstant.cpp.
View newest version in sPHENIX GitHub at line 92 of file PropagationEigenConstant.cpp
References geoCtx, magCtx, makeParametersCurvilinear(), merge_hashes::p, ActsTests::PropagationDatasets::phi, runToSurfaceTest(), physmon_simulation::s, and ActsTests::PropagationDatasets::theta.
BOOST_DATA_TEST_CASE (ToStrawAlongZ , ds::phi *ds::thetaWithoutBeam *ds::absMomentum *ds::chargeNonZero *ds::pathLength *ds::magneticField , phi , theta , p , q , s , bz)
Definition at line 102 of file PropagationEigenConstant.cpp.
View newest version in sPHENIX GitHub at line 102 of file PropagationEigenConstant.cpp
References geoCtx, magCtx, makeParametersCurvilinear(), merge_hashes::p, ActsTests::PropagationDatasets::phi, runToSurfaceTest(), physmon_simulation::s, and ActsTests::PropagationDatasets::theta.
BOOST_DATA_TEST_CASE (CovarianceCurvilinear , ds::phi *ds::theta *ds::absMomentum *ds::chargeNonZero *ds::pathLength *ds::magneticField , phi , theta , p , q , s , bz)
Definition at line 113 of file PropagationEigenConstant.cpp.
View newest version in sPHENIX GitHub at line 113 of file PropagationEigenConstant.cpp
References geoCtx, magCtx, makeParametersCurvilinearWithCovariance(), merge_hashes::p, ActsTests::PropagationDatasets::phi, runForwardComparisonTest(), physmon_simulation::s, and ActsTests::PropagationDatasets::theta.
BOOST_DATA_TEST_CASE (CovarianceToCylinderAlongZ , ds::phiWithoutAmbiguity *ds::thetaWithoutBeam *ds::absMomentum *ds::chargeNonZero *ds::pathLength *ds::magneticField , phi , theta , p , q , s , bz)
Definition at line 123 of file PropagationEigenConstant.cpp.
View newest version in sPHENIX GitHub at line 123 of file PropagationEigenConstant.cpp
References geoCtx, magCtx, makeParametersCurvilinearWithCovariance(), merge_hashes::p, ActsTests::PropagationDatasets::phi, runToSurfaceComparisonTest(), physmon_simulation::s, and ActsTests::PropagationDatasets::theta.
BOOST_DATA_TEST_CASE (CovarianceToDisc , ds::phi *ds::thetaWithoutBeam *ds::absMomentum *ds::chargeNonZero *ds::pathLength *ds::magneticField , phi , theta , p , q , s , bz)
Definition at line 134 of file PropagationEigenConstant.cpp.
View newest version in sPHENIX GitHub at line 134 of file PropagationEigenConstant.cpp
References geoCtx, magCtx, makeParametersCurvilinearWithCovariance(), merge_hashes::p, ActsTests::PropagationDatasets::phi, runToSurfaceComparisonTest(), physmon_simulation::s, and ActsTests::PropagationDatasets::theta.
BOOST_DATA_TEST_CASE (CovarianceToPlane , ds::phi *ds::theta *ds::absMomentum *ds::chargeNonZero *ds::pathLength *ds::magneticField , phi , theta , p , q , s , bz)
Definition at line 144 of file PropagationEigenConstant.cpp.
View newest version in sPHENIX GitHub at line 144 of file PropagationEigenConstant.cpp
References geoCtx, magCtx, makeParametersCurvilinearWithCovariance(), merge_hashes::p, ActsTests::PropagationDatasets::phi, runToSurfaceComparisonTest(), physmon_simulation::s, and ActsTests::PropagationDatasets::theta.
BOOST_DATA_TEST_CASE (CovarianceToStrawAlongZ , ds::phi *ds::thetaWithoutBeam *ds::absMomentum *ds::chargeNonZero *ds::pathLength *ds::magneticField , phi , theta , p , q , s , bz)
Definition at line 154 of file PropagationEigenConstant.cpp.
View newest version in sPHENIX GitHub at line 154 of file PropagationEigenConstant.cpp
References geoCtx, magCtx, makeParametersCurvilinearWithCovariance(), merge_hashes::p, ActsTests::PropagationDatasets::phi, runToSurfaceComparisonTest(), physmon_simulation::s, and ActsTests::PropagationDatasets::theta.