Analysis Software: ActsExamples::SimMultiTrajectory Struct Reference
ActsExamples::SimMultiTrajectory Struct Reference
Struct for truth track fitting/finding result with Acts::KalmanFitter/Acts::CombinatorialKalmanFilter.
#include <acts/blob/sPHENIX/Examples/Framework/include/ActsExamples/EventData/SimMultiTrajectory.hpp>
Public Member Functions
SimMultiTrajectory ()=default
Default constructor.
SimMultiTrajectory (const Acts::MultiTrajectory< SimSourceLink > &multiTraj, const std::vector< size_t > &tTips, const IndexedParams &parameters)
Constructor from multiTrajectory and fitted track parameters.
SimMultiTrajectory (const SimMultiTrajectory &rhs)
Copy constructor.
SimMultiTrajectory (SimMultiTrajectory &&rhs)
Copy move constructor.
~SimMultiTrajectory ()=default
Default destructor.
SimMultiTrajectory & operator= (const SimMultiTrajectory &rhs)
assignment operator
SimMultiTrajectory & operator= (SimMultiTrajectory &&rhs)
assignment move operator
bool hasTrajectory (const size_t &entryIndex) const
Indicator if a trajectory exists.
bool hasTrackParameters (const size_t &entryIndex) const
Indicator if there is fitted track parameters for one trajectory.
std::pair< std::vector< size_t >
, Acts::MultiTrajectory
< SimSourceLink > > trajectory () const
Getter for multiTrajectory.
const Acts::BoundTrackParameters & trackParameters (const size_t &entryIndex) const
Getter of fitted track parameters for one trajectory.
std::vector< ParticleHitCount > identifyMajorityParticle (const size_t &entryIndex) const
Counter of associated truth particles for one trajectory.
Private Attributes
Acts::MultiTrajectory
< SimSourceLink > m_multiTrajectory
std::vector< size_t > m_trackTips = {}
IndexedParams m_trackParameters = {}
Detailed Description
Struct for truth track fitting/finding result with Acts::KalmanFitter/Acts::CombinatorialKalmanFilter.
It contains a MultiTrajectory with a vector of entry indices for individual trajectories, and a map of fitted parameters indexed by the entry index. In case of track fitting, there is at most one trajectory in the MultiTrajectory; In case of track finding, there could be multiple trajectories in the MultiTrajectory.
Note
The MultiTrajectory is thought to be empty if there is no entry index
Definition at line 32 of file SimMultiTrajectory.hpp.
View newest version in sPHENIX GitHub at line 32 of file SimMultiTrajectory.hpp
Constructor & Destructor Documentation
ActsExamples::SimMultiTrajectory::SimMultiTrajectory () default
Default constructor.
ActsExamples::SimMultiTrajectory::SimMultiTrajectory (const Acts::MultiTrajectory< SimSourceLink > & multiTraj, const std::vector< size_t > & tTips, const IndexedParams & parameters) inline
Constructor from multiTrajectory and fitted track parameters.
Parameters
multiTraj The multiTrajectory
tTips The entry indices for trajectories in multiTrajectory
parameters The fitted track parameters indexed by trajectory entry index
Definition at line 44 of file SimMultiTrajectory.hpp.
View newest version in sPHENIX GitHub at line 44 of file SimMultiTrajectory.hpp
ActsExamples::SimMultiTrajectory::SimMultiTrajectory (const SimMultiTrajectory & rhs) inline
Copy constructor.
Parameters
rhs The source SimMultiTrajectory
Definition at line 54 of file SimMultiTrajectory.hpp.
View newest version in sPHENIX GitHub at line 54 of file SimMultiTrajectory.hpp
ActsExamples::SimMultiTrajectory::SimMultiTrajectory (SimMultiTrajectory && rhs) inline
Copy move constructor.
Parameters
rhs The source SimMultiTrajectory
Definition at line 62 of file SimMultiTrajectory.hpp.
View newest version in sPHENIX GitHub at line 62 of file SimMultiTrajectory.hpp
ActsExamples::SimMultiTrajectory::~SimMultiTrajectory () default
Default destructor.
Member Function Documentation
bool ActsExamples::SimMultiTrajectory::hasTrackParameters (const size_t & entryIndex) const inline
Indicator if there is fitted track parameters for one trajectory.
Parameters
entryIndex The trajectory entry index
Returns
Whether having fitted track parameters or not
Definition at line 105 of file SimMultiTrajectory.hpp.
View newest version in sPHENIX GitHub at line 105 of file SimMultiTrajectory.hpp
References m_trackParameters.
bool ActsExamples::SimMultiTrajectory::hasTrajectory (const size_t & entryIndex) const inline
Indicator if a trajectory exists.
Parameters
entryIndex The trajectory entry index
Returns
Whether there is trajectory with provided entry index
Definition at line 96 of file SimMultiTrajectory.hpp.
View newest version in sPHENIX GitHub at line 96 of file SimMultiTrajectory.hpp
References count, and m_trackTips.
Referenced by identifyMajorityParticle().
std::vector< ActsExamples::ParticleHitCount > ActsExamples::SimMultiTrajectory::identifyMajorityParticle (const size_t & entryIndex) const
Counter of associated truth particles for one trajectory.
Parameters
entryIndex The trajectory entry index
Returns
The truth particle counts in ascending order
Definition at line 12 of file SimMultiTrajectory.cpp.
View newest version in sPHENIX GitHub at line 12 of file SimMultiTrajectory.cpp
References hasTrajectory(), ActsExamples::ParticleHitCount::hitCount, it, m_multiTrajectory, m_trackTips, Acts::MeasurementFlag, Acts::UnitConstants::u, and Acts::MultiTrajectory< source_link_t >::visitBackwards().
SimMultiTrajectory& ActsExamples::SimMultiTrajectory::operator= (const SimMultiTrajectory & rhs) inline
assignment operator
Parameters
rhs The source SimMultiTrajectory
Definition at line 74 of file SimMultiTrajectory.hpp.
View newest version in sPHENIX GitHub at line 74 of file SimMultiTrajectory.hpp
References m_multiTrajectory, m_trackParameters, and m_trackTips.
SimMultiTrajectory& ActsExamples::SimMultiTrajectory::operator= (SimMultiTrajectory && rhs) inline
assignment move operator
Parameters
rhs The source SimMultiTrajectory
Definition at line 84 of file SimMultiTrajectory.hpp.
View newest version in sPHENIX GitHub at line 84 of file SimMultiTrajectory.hpp
References m_multiTrajectory, m_trackParameters, m_trackTips, and testing::internal::move().
const Acts::BoundTrackParameters& ActsExamples::SimMultiTrajectory::trackParameters (const size_t & entryIndex) const inline
Getter of fitted track parameters for one trajectory.
Parameters
entryIndex The trajectory entry index
Returns
The fitted track parameters of the trajectory
Definition at line 124 of file SimMultiTrajectory.hpp.
View newest version in sPHENIX GitHub at line 124 of file SimMultiTrajectory.hpp
References it, m_trackParameters, and nlohmann::to_string().
std::pair<std::vector<size_t>, Acts::MultiTrajectory<SimSourceLink> > ActsExamples::SimMultiTrajectory::trajectory () const inline
Getter for multiTrajectory.
Returns
The multiTrajectory with trajectory entry indices
Note
It could return an empty multiTrajectory
Definition at line 115 of file SimMultiTrajectory.hpp.
View newest version in sPHENIX GitHub at line 115 of file SimMultiTrajectory.hpp
References m_multiTrajectory, and m_trackTips.
Member Data Documentation
Acts::MultiTrajectory<SimSourceLink> ActsExamples::SimMultiTrajectory::m_multiTrajectory private
Definition at line 146 of file SimMultiTrajectory.hpp.
View newest version in sPHENIX GitHub at line 146 of file SimMultiTrajectory.hpp
Referenced by identifyMajorityParticle(), operator=(), and trajectory().
IndexedParams ActsExamples::SimMultiTrajectory::m_trackParameters = {} private
Definition at line 152 of file SimMultiTrajectory.hpp.
View newest version in sPHENIX GitHub at line 152 of file SimMultiTrajectory.hpp
Referenced by hasTrackParameters(), operator=(), and trackParameters().
std::vector<size_t> ActsExamples::SimMultiTrajectory::m_trackTips = {} private
Definition at line 149 of file SimMultiTrajectory.hpp.
View newest version in sPHENIX GitHub at line 149 of file SimMultiTrajectory.hpp
Referenced by hasTrajectory(), identifyMajorityParticle(), operator=(), and trajectory().
The documentation for this struct was generated from the following files:
acts/blob/sPHENIX/Examples/Framework/include/ActsExamples/EventData/SimMultiTrajectory.hpp
acts/blob/sPHENIX/Examples/Framework/src/EventData/SimMultiTrajectory.cpp