Analysis Software: testing::internal::UnitTestImpl Class Reference
testing::internal::UnitTestImpl Class Reference
#include <JETSCAPE/blob/main/external_packages/googletest/googletest/src/gtest-internal-inl.h>
Public Types
enum ReactionToSharding { HONOR_SHARDING_PROTOCOL, IGNORE_SHARDING_PROTOCOL }
Public Member Functions
UnitTestImpl (UnitTest *parent)
virtual ~UnitTestImpl ()
TestPartResultReporterInterface * GetGlobalTestPartResultReporter ()
void SetGlobalTestPartResultReporter (TestPartResultReporterInterface *reporter)
TestPartResultReporterInterface * GetTestPartResultReporterForCurrentThread ()
void SetTestPartResultReporterForCurrentThread (TestPartResultReporterInterface *reporter)
int successful_test_case_count () const
int failed_test_case_count () const
int total_test_case_count () const
int test_case_to_run_count () const
int successful_test_count () const
int failed_test_count () const
int reportable_disabled_test_count () const
int disabled_test_count () const
int reportable_test_count () const
int total_test_count () const
int test_to_run_count () const
TimeInMillis start_timestamp () const
TimeInMillis elapsed_time () const
bool Passed () const
bool Failed () const
const TestCase * GetTestCase (int i) const
TestCase * GetMutableTestCase (int i)
TestEventListeners * listeners ()
TestResult * current_test_result ()
const TestResult * ad_hoc_test_result () const
void set_os_stack_trace_getter (OsStackTraceGetterInterface *getter)
OsStackTraceGetterInterface * os_stack_trace_getter ()
std::string CurrentOsStackTraceExceptTop (int skip_count) GTEST_NO_INLINE_
TestCase * GetTestCase (const char *test_case_name, const char *type_param, Test::SetUpTestCaseFunc set_up_tc, Test::TearDownTestCaseFunc tear_down_tc)
void AddTestInfo (Test::SetUpTestCaseFunc set_up_tc, Test::TearDownTestCaseFunc tear_down_tc, TestInfo *test_info)
void set_current_test_case (TestCase *a_current_test_case)
void set_current_test_info (TestInfo *a_current_test_info)
void RegisterParameterizedTests ()
bool RunAllTests ()
void ClearNonAdHocTestResult ()
void ClearAdHocTestResult ()
void RecordProperty (const TestProperty &test_property)
int FilterTests (ReactionToSharding shard_tests)
void ListTestsMatchingFilter ()
const TestCase * current_test_case () const
TestInfo * current_test_info ()
const TestInfo * current_test_info () const
std::vector< Environment * > & environments ()
std::vector< TraceInfo > & gtest_trace_stack ()
const std::vector< TraceInfo > & gtest_trace_stack () const
void ConfigureXmlOutput ()
void PostFlagParsingInit ()
int random_seed () const
internal::Random * random ()
void ShuffleTests ()
void UnshuffleTests ()
bool catch_exceptions () const
Private Member Functions
void set_catch_exceptions (bool value)
GTEST_DISALLOW_COPY_AND_ASSIGN_ (UnitTestImpl)
Private Attributes
UnitTest *const parent_
internal::FilePath original_working_dir_
DefaultGlobalTestPartResultReporter default_global_test_part_result_reporter_
DefaultPerThreadTestPartResultReporter default_per_thread_test_part_result_reporter_
TestPartResultReporterInterface * global_test_part_result_repoter_
internal::Mutex global_test_part_result_reporter_mutex_
internal::ThreadLocal
< TestPartResultReporterInterface * > per_thread_test_part_result_reporter_
std::vector< Environment * > environments_
std::vector< TestCase * > test_cases_
std::vector< int > test_case_indices_
int last_death_test_case_
TestCase * current_test_case_
TestInfo * current_test_info_
TestResult ad_hoc_test_result_
TestEventListeners listeners_
OsStackTraceGetterInterface * os_stack_trace_getter_
bool post_flag_parse_init_performed_
int random_seed_
internal::Random random_
TimeInMillis start_timestamp_
TimeInMillis elapsed_time_
internal::ThreadLocal
< std::vector< TraceInfo > > gtest_trace_stack_
bool catch_exceptions_
Friends
class ::testing::UnitTest
Detailed Description
Definition at line 499 of file gtest-internal-inl.h.
View newest version in sPHENIX GitHub at line 499 of file gtest-internal-inl.h
Member Enumeration Documentation
enum testing::internal::UnitTestImpl::ReactionToSharding
Enumerator:
HONOR_SHARDING_PROTOCOL
IGNORE_SHARDING_PROTOCOL
Definition at line 717 of file gtest-internal-inl.h.
View newest version in sPHENIX GitHub at line 717 of file gtest-internal-inl.h
Constructor & Destructor Documentation
testing::internal::UnitTestImpl::UnitTestImpl (UnitTest * parent) explicit
Definition at line 4325 of file gtest.cc.
View newest version in sPHENIX GitHub at line 4325 of file gtest.cc
References listeners(), and testing::TestEventListeners::SetDefaultResultPrinter().
testing::internal::UnitTestImpl::~UnitTestImpl () virtual
Definition at line 4357 of file gtest.cc.
View newest version in sPHENIX GitHub at line 4357 of file gtest.cc
References environments_, testing::internal::ForEach(), os_stack_trace_getter_, and test_cases_.
Member Function Documentation
const TestResult* testing::internal::UnitTestImpl::ad_hoc_test_result () const inline
Definition at line 597 of file gtest-internal-inl.h.
View newest version in sPHENIX GitHub at line 597 of file gtest-internal-inl.h
Referenced by testing::UnitTest::ad_hoc_test_result().
void testing::internal::UnitTestImpl::AddTestInfo (Test::SetUpTestCaseFunc set_up_tc, Test::TearDownTestCaseFunc tear_down_tc, TestInfo * test_info) inline
Definition at line 645 of file gtest-internal-inl.h.
View newest version in sPHENIX GitHub at line 645 of file gtest-internal-inl.h
References testing::internal::FilePath::GetCurrentDir(), GTEST_CHECK_, original_working_dir_, testing::TestInfo::test_case_name(), and testing::TestInfo::type_param().
Referenced by testing::internal::MakeAndRegisterTestInfo().
bool testing::internal::UnitTestImpl::catch_exceptions () const inline
Definition at line 803 of file gtest-internal-inl.h.
View newest version in sPHENIX GitHub at line 803 of file gtest-internal-inl.h
void testing::internal::UnitTestImpl::ClearAdHocTestResult () inline
Definition at line 707 of file gtest-internal-inl.h.
View newest version in sPHENIX GitHub at line 707 of file gtest-internal-inl.h
void testing::internal::UnitTestImpl::ClearNonAdHocTestResult () inline
Definition at line 702 of file gtest-internal-inl.h.
View newest version in sPHENIX GitHub at line 702 of file gtest-internal-inl.h
References testing::TestCase::ClearTestCaseResult(), and testing::internal::ForEach().
Referenced by RunAllTests().
void testing::internal::UnitTestImpl::ConfigureXmlOutput ()
Definition at line 4400 of file gtest.cc.
View newest version in sPHENIX GitHub at line 4400 of file gtest.cc
References testing::internal::UnitTestOptions::GetAbsolutePathToOutputFile(), testing::internal::UnitTestOptions::GetOutputFormat(), listeners(), printf(), testing::TestEventListeners::SetDefaultXmlGenerator(), and conf::stdout.
Referenced by PostFlagParsingInit().
const TestCase* testing::internal::UnitTestImpl::current_test_case () const inline
Definition at line 733 of file gtest-internal-inl.h.
View newest version in sPHENIX GitHub at line 733 of file gtest-internal-inl.h
Referenced by testing::UnitTest::current_test_case(), and testing::Test::HasSameFixtureClass().
TestInfo* testing::internal::UnitTestImpl::current_test_info () inline
Definition at line 734 of file gtest-internal-inl.h.
View newest version in sPHENIX GitHub at line 734 of file gtest-internal-inl.h
Referenced by testing::UnitTest::current_test_info(), and testing::Test::HasSameFixtureClass().
const TestInfo* testing::internal::UnitTestImpl::current_test_info () const inline
Definition at line 735 of file gtest-internal-inl.h.
View newest version in sPHENIX GitHub at line 735 of file gtest-internal-inl.h
TestResult * testing::internal::UnitTestImpl::current_test_result ()
Definition at line 4932 of file gtest.cc.
View newest version in sPHENIX GitHub at line 4932 of file gtest.cc
References ad_hoc_test_result_, current_test_info_, and testing::TestInfo::result_.
Referenced by testing::Test::HasFatalFailure(), testing::Test::HasNonfatalFailure(), and testing::internal::DefaultGlobalTestPartResultReporter::ReportTestPartResult().
std::string testing::internal::UnitTestImpl::CurrentOsStackTraceExceptTop (int skip_count)
Definition at line 796 of file gtest.cc.
View newest version in sPHENIX GitHub at line 796 of file gtest.cc
References testing::internal::OsStackTraceGetterInterface::CurrentStackTrace(), GTEST_FLAG, and os_stack_trace_getter().
Referenced by testing::internal::GetCurrentOsStackTraceExceptTop(), and testing::internal::AssertHelper::operator=().
int testing::internal::UnitTestImpl::disabled_test_count () const
Definition at line 767 of file gtest.cc.
View newest version in sPHENIX GitHub at line 767 of file gtest.cc
References testing::TestCase::disabled_test_count(), testing::internal::SumOverTestCaseList(), and test_cases_.
Referenced by testing::UnitTest::disabled_test_count().
TimeInMillis testing::internal::UnitTestImpl::elapsed_time () const inline
Definition at line 564 of file gtest-internal-inl.h.
View newest version in sPHENIX GitHub at line 564 of file gtest-internal-inl.h
Referenced by testing::UnitTest::elapsed_time().
std::vector<Environment*>& testing::internal::UnitTestImpl::environments () inline
Definition at line 739 of file gtest-internal-inl.h.
View newest version in sPHENIX GitHub at line 739 of file gtest-internal-inl.h
Referenced by testing::UnitTest::AddEnvironment().
bool testing::internal::UnitTestImpl::Failed () const inline
Definition at line 571 of file gtest-internal-inl.h.
View newest version in sPHENIX GitHub at line 571 of file gtest-internal-inl.h
Referenced by testing::UnitTest::Failed().
int testing::internal::UnitTestImpl::failed_test_case_count () const
Definition at line 735 of file gtest.cc.
View newest version in sPHENIX GitHub at line 735 of file gtest.cc
References testing::internal::CountIf(), test_cases_, and testing::internal::TestCaseFailed().
Referenced by testing::UnitTest::failed_test_case_count().
int testing::internal::UnitTestImpl::failed_test_count () const
Definition at line 756 of file gtest.cc.
View newest version in sPHENIX GitHub at line 756 of file gtest.cc
References testing::TestCase::failed_test_count(), testing::internal::SumOverTestCaseList(), and test_cases_.
Referenced by testing::UnitTest::failed_test_count().
int testing::internal::UnitTestImpl::FilterTests (ReactionToSharding shard_tests)
Definition at line 4789 of file gtest.cc.
View newest version in sPHENIX GitHub at line 4789 of file gtest.cc
References testing::internal::UnitTestOptions::FilterMatchesTest(), GTEST_FLAG, HONOR_SHARDING_PROTOCOL, i, IGNORE_SHARDING_PROTOCOL, testing::internal::Int32FromEnvOrDie(), testing::TestInfo::is_disabled_, j, testing::kDisableTestFilter, testing::kTestShardIndex, testing::kTestTotalShards, testing::TestInfo::matches_filter_, testing::internal::UnitTestOptions::MatchesFilter(), testing::TestInfo::name(), testing::TestCase::name(), testing::TestCase::set_should_run(), testing::TestCase::should_run(), testing::TestInfo::should_run_, testing::internal::ShouldRunTestOnShard(), test_cases_, and testing::TestCase::test_info_list().
Referenced by RunAllTests().
TestPartResultReporterInterface * testing::internal::UnitTestImpl::GetGlobalTestPartResultReporter ()
Definition at line 705 of file gtest.cc.
View newest version in sPHENIX GitHub at line 705 of file gtest.cc
References global_test_part_result_reporter_mutex_, and global_test_part_result_repoter_.
Referenced by testing::ScopedFakeTestPartResultReporter::Init(), and testing::internal::DefaultPerThreadTestPartResultReporter::ReportTestPartResult().
TestCase* testing::internal::UnitTestImpl::GetMutableTestCase (int i) inline
Definition at line 584 of file gtest-internal-inl.h.
View newest version in sPHENIX GitHub at line 584 of file gtest-internal-inl.h
References testing::internal::GetElementOr(), and index.
Referenced by testing::UnitTest::GetMutableTestCase(), and RunAllTests().
const TestCase* testing::internal::UnitTestImpl::GetTestCase (int i) const inline
Definition at line 577 of file gtest-internal-inl.h.
View newest version in sPHENIX GitHub at line 577 of file gtest-internal-inl.h
References testing::internal::GetElementOr(), i, and index.
Referenced by testing::UnitTest::GetTestCase().
TestCase * testing::internal::UnitTestImpl::GetTestCase (const char * test_case_name, const char * type_param, Test::SetUpTestCaseFunc set_up_tc, Test::TearDownTestCaseFunc tear_down_tc)
Definition at line 4502 of file gtest.cc.
View newest version in sPHENIX GitHub at line 4502 of file gtest.cc
References testing::kDeathTestCaseFilter, last_death_test_case_, testing::internal::UnitTestOptions::MatchesFilter(), test_case_indices_, test_cases_, and gmock_test_utils::TestCase.
TestPartResultReporterInterface * testing::internal::UnitTestImpl::GetTestPartResultReporterForCurrentThread ()
Definition at line 719 of file gtest.cc.
View newest version in sPHENIX GitHub at line 719 of file gtest.cc
References testing::internal::ThreadLocal< T >::get(), and per_thread_test_part_result_reporter_.
Referenced by testing::ScopedFakeTestPartResultReporter::Init().
testing::internal::UnitTestImpl::GTEST_DISALLOW_COPY_AND_ASSIGN_ (UnitTestImpl) private
std::vector<TraceInfo>& testing::internal::UnitTestImpl::gtest_trace_stack () inline
Definition at line 742 of file gtest-internal-inl.h.
View newest version in sPHENIX GitHub at line 742 of file gtest-internal-inl.h
Referenced by testing::UnitTest::PopGTestTrace().
const std::vector<TraceInfo>& testing::internal::UnitTestImpl::gtest_trace_stack () const inline
Definition at line 745 of file gtest-internal-inl.h.
View newest version in sPHENIX GitHub at line 745 of file gtest-internal-inl.h
TestEventListeners* testing::internal::UnitTestImpl::listeners () inline
Definition at line 590 of file gtest-internal-inl.h.
View newest version in sPHENIX GitHub at line 590 of file gtest-internal-inl.h
Referenced by ConfigureXmlOutput(), testing::UnitTest::listeners(), PostFlagParsingInit(), testing::internal::DefaultGlobalTestPartResultReporter::ReportTestPartResult(), RunAllTests(), and UnitTestImpl().
void testing::internal::UnitTestImpl::ListTestsMatchingFilter ()
Definition at line 4865 of file gtest.cc.
View newest version in sPHENIX GitHub at line 4865 of file gtest.cc
References i, j, testing::internal::kTypeParamLabel, testing::internal::kValueParamLabel, testing::TestInfo::matches_filter_, testing::TestInfo::name(), testing::TestCase::name(), printf(), testing::internal::PrintOnOneLine(), conf::stdout, test_cases_, testing::TestCase::test_info_list(), testing::TestCase::type_param(), and testing::TestInfo::value_param().
Referenced by RunAllTests().
OsStackTraceGetterInterface * testing::internal::UnitTestImpl::os_stack_trace_getter ()
Definition at line 4918 of file gtest.cc.
View newest version in sPHENIX GitHub at line 4918 of file gtest.cc
References os_stack_trace_getter_.
Referenced by CurrentOsStackTraceExceptTop(), testing::Test::Run(), testing::TestInfo::Run(), and testing::TestCase::Run().
bool testing::internal::UnitTestImpl::Passed () const inline
Definition at line 567 of file gtest-internal-inl.h.
View newest version in sPHENIX GitHub at line 567 of file gtest-internal-inl.h
Referenced by testing::UnitTest::Passed(), and RunAllTests().
void testing::internal::UnitTestImpl::PostFlagParsingInit ()
Definition at line 4436 of file gtest.cc.
View newest version in sPHENIX GitHub at line 4436 of file gtest.cc
References testing::TestEventListeners::Append(), ConfigureXmlOutput(), listeners(), post_flag_parse_init_performed_, and RegisterParameterizedTests().
Referenced by testing::internal::InitGoogleTestImpl(), and RunAllTests().
internal::Random* testing::internal::UnitTestImpl::random () inline
Definition at line 792 of file gtest-internal-inl.h.
View newest version in sPHENIX GitHub at line 792 of file gtest-internal-inl.h
Referenced by RunAllTests(), and ShuffleTests().
int testing::internal::UnitTestImpl::random_seed () const inline
Definition at line 789 of file gtest-internal-inl.h.
View newest version in sPHENIX GitHub at line 789 of file gtest-internal-inl.h
Referenced by testing::UnitTest::random_seed(), and RunAllTests().
void testing::internal::UnitTestImpl::RecordProperty (const TestProperty & test_property)
Definition at line 4372 of file gtest.cc.
View newest version in sPHENIX GitHub at line 4372 of file gtest.cc
References ad_hoc_test_result_, testing::TestCase::ad_hoc_test_result_, current_test_case_, current_test_info_, testing::TestResult::RecordProperty(), and testing::TestInfo::result_.
Referenced by testing::UnitTest::RecordProperty().
void testing::internal::UnitTestImpl::RegisterParameterizedTests ()
Definition at line 2617 of file gtest.cc.
View newest version in sPHENIX GitHub at line 2617 of file gtest.cc
Referenced by PostFlagParsingInit().
int testing::internal::UnitTestImpl::reportable_disabled_test_count () const
Definition at line 761 of file gtest.cc.
View newest version in sPHENIX GitHub at line 761 of file gtest.cc
References testing::TestCase::reportable_disabled_test_count(), testing::internal::SumOverTestCaseList(), and test_cases_.
Referenced by testing::UnitTest::reportable_disabled_test_count().
int testing::internal::UnitTestImpl::reportable_test_count () const
Definition at line 772 of file gtest.cc.
View newest version in sPHENIX GitHub at line 772 of file gtest.cc
References testing::TestCase::reportable_test_count(), testing::internal::SumOverTestCaseList(), and test_cases_.
Referenced by testing::UnitTest::reportable_test_count().
bool testing::internal::UnitTestImpl::RunAllTests ()
Definition at line 4551 of file gtest.cc.
View newest version in sPHENIX GitHub at line 4551 of file gtest.cc
References ClearNonAdHocTestResult(), elapsed_time_, environments_, FilterTests(), testing::internal::ForEach(), testing::internal::g_help_flag, GetMutableTestCase(), testing::internal::GetNextRandomSeed(), testing::internal::GetRandomSeedFromFlag(), testing::internal::GetTimeInMillis(), GTEST_FLAG, testing::internal::GTestIsInitialized(), testing::Test::HasFatalFailure(), HONOR_SHARDING_PROTOCOL, i, IGNORE_SHARDING_PROTOCOL, testing::kTestShardIndex, testing::kTestTotalShards, listeners(), ListTestsMatchingFilter(), testing::TestEventListener::OnEnvironmentsSetUpEnd(), testing::TestEventListener::OnEnvironmentsSetUpStart(), testing::TestEventListener::OnEnvironmentsTearDownEnd(), testing::TestEventListener::OnEnvironmentsTearDownStart(), testing::TestEventListener::OnTestIterationEnd(), testing::TestEventListener::OnTestIterationStart(), testing::TestEventListener::OnTestProgramEnd(), testing::TestEventListener::OnTestProgramStart(), parent_, Passed(), PostFlagParsingInit(), printf(), random(), random_seed(), random_seed_, testing::TestEventListeners::repeater(), testing::internal::Random::Reseed(), testing::TestCase::Run(), testing::internal::SetUpEnvironment(), testing::internal::ShouldShard(), ShuffleTests(), start, start_timestamp_, testing::internal::TearDownEnvironment(), total_test_case_count(), UnshuffleTests(), and testing::internal::WriteToShardStatusFileIfNeeded().
Referenced by testing::UnitTest::Run().
void testing::internal::UnitTestImpl::set_catch_exceptions (bool value) inline private
Definition at line 810 of file gtest-internal-inl.h.
View newest version in sPHENIX GitHub at line 810 of file gtest-internal-inl.h
References value.
Referenced by testing::UnitTest::Run().
void testing::internal::UnitTestImpl::set_current_test_case (TestCase * a_current_test_case) inline
Definition at line 676 of file gtest-internal-inl.h.
View newest version in sPHENIX GitHub at line 676 of file gtest-internal-inl.h
Referenced by testing::TestCase::Run().
void testing::internal::UnitTestImpl::set_current_test_info (TestInfo * a_current_test_info) inline
Definition at line 683 of file gtest-internal-inl.h.
View newest version in sPHENIX GitHub at line 683 of file gtest-internal-inl.h
Referenced by testing::TestInfo::Run().
void testing::internal::UnitTestImpl::set_os_stack_trace_getter (OsStackTraceGetterInterface * getter)
Definition at line 4907 of file gtest.cc.
View newest version in sPHENIX GitHub at line 4907 of file gtest.cc
References os_stack_trace_getter_.
void testing::internal::UnitTestImpl::SetGlobalTestPartResultReporter (TestPartResultReporterInterface * reporter)
Definition at line 711 of file gtest.cc.
View newest version in sPHENIX GitHub at line 711 of file gtest.cc
References global_test_part_result_reporter_mutex_, and global_test_part_result_repoter_.
Referenced by testing::ScopedFakeTestPartResultReporter::Init(), and testing::ScopedFakeTestPartResultReporter::~ScopedFakeTestPartResultReporter().
void testing::internal::UnitTestImpl::SetTestPartResultReporterForCurrentThread (TestPartResultReporterInterface * reporter)
Definition at line 724 of file gtest.cc.
View newest version in sPHENIX GitHub at line 724 of file gtest.cc
References per_thread_test_part_result_reporter_, and testing::internal::ThreadLocal< T >::set().
Referenced by testing::internal::HasNewFatalFailureHelper::HasNewFatalFailureHelper(), testing::ScopedFakeTestPartResultReporter::Init(), testing::internal::HasNewFatalFailureHelper::~HasNewFatalFailureHelper(), and testing::ScopedFakeTestPartResultReporter::~ScopedFakeTestPartResultReporter().
void testing::internal::UnitTestImpl::ShuffleTests ()
Definition at line 4939 of file gtest.cc.
View newest version in sPHENIX GitHub at line 4939 of file gtest.cc
References i, last_death_test_case_, random(), testing::internal::ShuffleRange(), test_case_indices_, and test_cases_.
Referenced by RunAllTests().
TimeInMillis testing::internal::UnitTestImpl::start_timestamp () const inline
Definition at line 561 of file gtest-internal-inl.h.
View newest version in sPHENIX GitHub at line 561 of file gtest-internal-inl.h
Referenced by testing::UnitTest::start_timestamp().
int testing::internal::UnitTestImpl::successful_test_case_count () const
Definition at line 730 of file gtest.cc.
View newest version in sPHENIX GitHub at line 730 of file gtest.cc
References testing::internal::CountIf(), test_cases_, and testing::internal::TestCasePassed().
Referenced by testing::UnitTest::successful_test_case_count().
int testing::internal::UnitTestImpl::successful_test_count () const
Definition at line 751 of file gtest.cc.
View newest version in sPHENIX GitHub at line 751 of file gtest.cc
References testing::TestCase::successful_test_count(), testing::internal::SumOverTestCaseList(), and test_cases_.
Referenced by testing::UnitTest::successful_test_count().
int testing::internal::UnitTestImpl::test_case_to_run_count () const
Definition at line 746 of file gtest.cc.
View newest version in sPHENIX GitHub at line 746 of file gtest.cc
References testing::internal::CountIf(), testing::internal::ShouldRunTestCase(), and test_cases_.
Referenced by testing::UnitTest::test_case_to_run_count().
int testing::internal::UnitTestImpl::test_to_run_count () const
Definition at line 782 of file gtest.cc.
View newest version in sPHENIX GitHub at line 782 of file gtest.cc
References testing::internal::SumOverTestCaseList(), test_cases_, and testing::TestCase::test_to_run_count().
Referenced by testing::UnitTest::test_to_run_count().
int testing::internal::UnitTestImpl::total_test_case_count () const
Definition at line 740 of file gtest.cc.
View newest version in sPHENIX GitHub at line 740 of file gtest.cc
References test_cases_.
Referenced by RunAllTests(), and testing::UnitTest::total_test_case_count().
int testing::internal::UnitTestImpl::total_test_count () const
Definition at line 777 of file gtest.cc.
View newest version in sPHENIX GitHub at line 777 of file gtest.cc
References testing::internal::SumOverTestCaseList(), test_cases_, and testing::TestCase::total_test_count().
Referenced by testing::UnitTest::total_test_count().
void testing::internal::UnitTestImpl::UnshuffleTests ()
Definition at line 4954 of file gtest.cc.
View newest version in sPHENIX GitHub at line 4954 of file gtest.cc
References i, test_case_indices_, and test_cases_.
Referenced by RunAllTests().
Friends And Related Function Documentation
friend class ::testing::UnitTest friend
Definition at line 806 of file gtest-internal-inl.h.
View newest version in sPHENIX GitHub at line 806 of file gtest-internal-inl.h
Member Data Documentation
TestResult testing::internal::UnitTestImpl::ad_hoc_test_result_ private
Definition at line 880 of file gtest-internal-inl.h.
View newest version in sPHENIX GitHub at line 880 of file gtest-internal-inl.h
Referenced by current_test_result(), and RecordProperty().
bool testing::internal::UnitTestImpl::catch_exceptions_ private
Definition at line 920 of file gtest-internal-inl.h.
View newest version in sPHENIX GitHub at line 920 of file gtest-internal-inl.h
TestCase* testing::internal::UnitTestImpl::current_test_case_ private
Definition at line 864 of file gtest-internal-inl.h.
View newest version in sPHENIX GitHub at line 864 of file gtest-internal-inl.h
Referenced by RecordProperty().
TestInfo* testing::internal::UnitTestImpl::current_test_info_ private
Definition at line 870 of file gtest-internal-inl.h.
View newest version in sPHENIX GitHub at line 870 of file gtest-internal-inl.h
Referenced by current_test_result(), and RecordProperty().
DefaultGlobalTestPartResultReporter testing::internal::UnitTestImpl::default_global_test_part_result_reporter_ private
Definition at line 820 of file gtest-internal-inl.h.
View newest version in sPHENIX GitHub at line 820 of file gtest-internal-inl.h
DefaultPerThreadTestPartResultReporter testing::internal::UnitTestImpl::default_per_thread_test_part_result_reporter_ private
Definition at line 822 of file gtest-internal-inl.h.
View newest version in sPHENIX GitHub at line 822 of file gtest-internal-inl.h
TimeInMillis testing::internal::UnitTestImpl::elapsed_time_ private
Definition at line 906 of file gtest-internal-inl.h.
View newest version in sPHENIX GitHub at line 906 of file gtest-internal-inl.h
Referenced by RunAllTests().
std::vector<Environment*> testing::internal::UnitTestImpl::environments_ private
Definition at line 836 of file gtest-internal-inl.h.
View newest version in sPHENIX GitHub at line 836 of file gtest-internal-inl.h
Referenced by RunAllTests(), and ~UnitTestImpl().
internal::Mutex testing::internal::UnitTestImpl::global_test_part_result_reporter_mutex_ private
Definition at line 828 of file gtest-internal-inl.h.
View newest version in sPHENIX GitHub at line 828 of file gtest-internal-inl.h
Referenced by GetGlobalTestPartResultReporter(), and SetGlobalTestPartResultReporter().
TestPartResultReporterInterface* testing::internal::UnitTestImpl::global_test_part_result_repoter_ private
Definition at line 825 of file gtest-internal-inl.h.
View newest version in sPHENIX GitHub at line 825 of file gtest-internal-inl.h
Referenced by GetGlobalTestPartResultReporter(), and SetGlobalTestPartResultReporter().
internal::ThreadLocal<std::vector<TraceInfo> > testing::internal::UnitTestImpl::gtest_trace_stack_ private
Definition at line 916 of file gtest-internal-inl.h.
View newest version in sPHENIX GitHub at line 916 of file gtest-internal-inl.h
int testing::internal::UnitTestImpl::last_death_test_case_ private
Definition at line 858 of file gtest-internal-inl.h.
View newest version in sPHENIX GitHub at line 858 of file gtest-internal-inl.h
Referenced by GetTestCase(), and ShuffleTests().
TestEventListeners testing::internal::UnitTestImpl::listeners_ private
Definition at line 884 of file gtest-internal-inl.h.
View newest version in sPHENIX GitHub at line 884 of file gtest-internal-inl.h
internal::FilePath testing::internal::UnitTestImpl::original_working_dir_ private
Definition at line 817 of file gtest-internal-inl.h.
View newest version in sPHENIX GitHub at line 817 of file gtest-internal-inl.h
Referenced by testing::UnitTest::original_working_dir().
OsStackTraceGetterInterface* testing::internal::UnitTestImpl::os_stack_trace_getter_ private
Definition at line 890 of file gtest-internal-inl.h.
View newest version in sPHENIX GitHub at line 890 of file gtest-internal-inl.h
Referenced by os_stack_trace_getter(), set_os_stack_trace_getter(), and ~UnitTestImpl().
UnitTest* const testing::internal::UnitTestImpl::parent_ private
Definition at line 813 of file gtest-internal-inl.h.
View newest version in sPHENIX GitHub at line 813 of file gtest-internal-inl.h
Referenced by RunAllTests().
internal::ThreadLocal<TestPartResultReporterInterface*> testing::internal::UnitTestImpl::per_thread_test_part_result_reporter_ private
Definition at line 832 of file gtest-internal-inl.h.
View newest version in sPHENIX GitHub at line 832 of file gtest-internal-inl.h
Referenced by GetTestPartResultReporterForCurrentThread(), and SetTestPartResultReporterForCurrentThread().
bool testing::internal::UnitTestImpl::post_flag_parse_init_performed_ private
Definition at line 893 of file gtest-internal-inl.h.
View newest version in sPHENIX GitHub at line 893 of file gtest-internal-inl.h
Referenced by PostFlagParsingInit().
internal::Random testing::internal::UnitTestImpl::random_ private
Definition at line 899 of file gtest-internal-inl.h.
View newest version in sPHENIX GitHub at line 899 of file gtest-internal-inl.h
int testing::internal::UnitTestImpl::random_seed_ private
Definition at line 896 of file gtest-internal-inl.h.
View newest version in sPHENIX GitHub at line 896 of file gtest-internal-inl.h
Referenced by RunAllTests().
TimeInMillis testing::internal::UnitTestImpl::start_timestamp_ private
Definition at line 903 of file gtest-internal-inl.h.
View newest version in sPHENIX GitHub at line 903 of file gtest-internal-inl.h
Referenced by RunAllTests().
std::vector<int> testing::internal::UnitTestImpl::test_case_indices_ private
Definition at line 846 of file gtest-internal-inl.h.
View newest version in sPHENIX GitHub at line 846 of file gtest-internal-inl.h
Referenced by GetTestCase(), ShuffleTests(), and UnshuffleTests().
std::vector<TestCase*> testing::internal::UnitTestImpl::test_cases_ private
Definition at line 840 of file gtest-internal-inl.h.
View newest version in sPHENIX GitHub at line 840 of file gtest-internal-inl.h
Referenced by disabled_test_count(), failed_test_case_count(), failed_test_count(), FilterTests(), GetTestCase(), ListTestsMatchingFilter(), reportable_disabled_test_count(), reportable_test_count(), ShuffleTests(), successful_test_case_count(), successful_test_count(), test_case_to_run_count(), test_to_run_count(), total_test_case_count(), total_test_count(), UnshuffleTests(), and ~UnitTestImpl().
The documentation for this class was generated from the following files:
JETSCAPE/blob/main/external_packages/googletest/googletest/src/gtest-internal-inl.h
JETSCAPE/blob/main/external_packages/googletest/googletest/src/gtest.cc