Analysis Software: SvtxClusterEval Class Reference
SvtxClusterEval Class Reference
#include <coresoftware/blob/master/simulation/g4simulation/g4eval/SvtxClusterEval.h>
Public Member Functions
SvtxClusterEval (PHCompositeNode *topNode)
virtual ~SvtxClusterEval ()
void next_event (PHCompositeNode *topNode)
void do_caching (bool do_cache)
void set_strict (bool strict)
void set_verbosity (int verbosity)
SvtxHitEval * get_hit_eval ()
SvtxTruthEval * get_truth_eval ()
std::set< PHG4Hit * > all_truth_hits (TrkrDefs::cluskey cluster)
PHG4Hit * max_truth_hit_by_energy (TrkrDefs::cluskey)
std::map< TrkrDefs::cluskey,
std::shared_ptr< TrkrCluster > > all_truth_clusters (TrkrDefs::cluskey cluster_key)
std::pair< TrkrDefs::cluskey,
std::shared_ptr< TrkrCluster > > max_truth_cluster_by_energy (TrkrDefs::cluskey cluster_key)
PHG4Hit * all_truth_hits_by_nhit (TrkrDefs::cluskey cluster)
std::pair< int, int > gtrackid_and_layer_by_nhit (TrkrDefs::cluskey cluster)
std::set< PHG4Particle * > all_truth_particles (TrkrDefs::cluskey)
PHG4Particle * max_truth_particle_by_energy (TrkrDefs::cluskey)
PHG4Particle * max_truth_particle_by_cluster_energy (TrkrDefs::cluskey)
std::set< TrkrDefs::cluskey > all_clusters_from (PHG4Particle *truthparticle)
std::set< TrkrDefs::cluskey > all_clusters_from (PHG4Hit *truthhit)
TrkrDefs::cluskey best_cluster_from (PHG4Hit *truthhit)
TrkrDefs::cluskey best_cluster_by_nhit (int gid, int layer)
void FillRecoClusterFromG4HitCache ()
float get_energy_contribution (TrkrDefs::cluskey cluster_key, PHG4Particle *truthparticle)
float get_energy_contribution (TrkrDefs::cluskey cluster_key, PHG4Hit *truthhit)
std::pair< TrkrDefs::cluskey,
TrkrCluster * > reco_cluster_from_truth_cluster (TrkrDefs::cluskey, const std::shared_ptr< TrkrCluster > &gclus)
unsigned int get_errors ()
Private Member Functions
void get_node_pointers (PHCompositeNode *topNode)
void fill_cluster_layer_map ()
bool has_node_pointers ()
float fast_approx_atan2 (float y, float x)
float fast_approx_atan2 (float y2x)
Acts::Vector3 getGlobalPosition (TrkrDefs::cluskey cluster_key, TrkrCluster *cluster)
Private Attributes
SvtxHitEval _hiteval
TrkrClusterContainer * _clustermap = nullptr
TrkrClusterHitAssoc * _cluster_hit_map = nullptr
TrkrHitTruthAssoc * _hit_truth_map = nullptr
PHG4TruthInfoContainer * _truthinfo = nullptr
PHG4HitContainer * _g4hits_tpc = nullptr
PHG4HitContainer * _g4hits_intt = nullptr
PHG4HitContainer * _g4hits_mvtx = nullptr
PHG4HitContainer * _g4hits_mms = nullptr
ActsGeometry * _tgeometry = nullptr
bool _strict = false
int _verbosity = 0
unsigned int _errors = 0
bool _do_cache = true
std::map< TrkrDefs::cluskey,
std::set< PHG4Hit * > > _cache_all_truth_hits
std::map< TrkrDefs::cluskey,
std::map< TrkrDefs::cluskey,
std::shared_ptr< TrkrCluster > > > _cache_all_truth_clusters
std::map< TrkrDefs::cluskey,
PHG4Hit * > _cache_max_truth_hit_by_energy
std::map< TrkrDefs::cluskey,
std::pair< TrkrDefs::cluskey,
std::shared_ptr< TrkrCluster > > > _cache_max_truth_cluster_by_energy
std::map< TrkrDefs::cluskey,
std::set< PHG4Particle * > > _cache_all_truth_particles
std::map< TrkrDefs::cluskey,
PHG4Particle * > _cache_max_truth_particle_by_energy
std::map< TrkrDefs::cluskey,
PHG4Particle * > _cache_max_truth_particle_by_cluster_energy
std::map< PHG4Particle
*, std::set< TrkrDefs::cluskey > > _cache_all_clusters_from_particle
std::map< PHG4Hit *, std::set
< TrkrDefs::cluskey > > _cache_all_clusters_from_g4hit
std::map< PHG4Hit
*, TrkrDefs::cluskey > _cache_best_cluster_from_g4hit
std::map< std::pair< int, int >
, TrkrDefs::cluskey > _cache_best_cluster_from_gtrackid_layer
std::map< std::pair
< TrkrDefs::cluskey,
PHG4Particle * >, float > _cache_get_energy_contribution_g4particle
std::map< std::pair
< TrkrDefs::cluskey, PHG4Hit * >
, float > _cache_get_energy_contribution_g4hit
std::map< std::shared_ptr
< TrkrCluster >, std::pair
< TrkrDefs::cluskey,
TrkrCluster * > > _cache_reco_cluster_from_truth_cluster
const float sig_tpc_rphi_inner = 220e-04
const float sig_tpc_rphi_mid = 155e-04
const float sig_tpc_rphi_outer = 165e-04
const float sig_tpc_z = 750e-04
const float sig_intt_rphi = 17e-04
const float range_intt_z = 0.9
const float sig_mvtx_rphi = 4.0e-04
const float sig_mvtx_z = 4.7e-04
const float sig_mms_rphi_55 = 100e-04
const float sig_mms_z_56 = 200e-04
std::multimap< unsigned int,
innerMap > _clusters_per_layer
Static Private Attributes
static constexpr float _clusters_searching_window = 0.1f
cluster azimuthal searching window in _clusters_per_layer. Unit: rad
Detailed Description
Definition at line 29 of file SvtxClusterEval.h.
View newest version in sPHENIX GitHub at line 29 of file SvtxClusterEval.h
Constructor & Destructor Documentation
SvtxClusterEval::SvtxClusterEval (PHCompositeNode * topNode)
Definition at line 33 of file SvtxClusterEval.cc.
View newest version in sPHENIX GitHub at line 33 of file SvtxClusterEval.cc
References get_node_pointers().
SvtxClusterEval::~SvtxClusterEval () virtual
Definition at line 39 of file SvtxClusterEval.cc.
View newest version in sPHENIX GitHub at line 39 of file SvtxClusterEval.cc
References _errors, and _verbosity.
Member Function Documentation
std::set< TrkrDefs::cluskey > SvtxClusterEval::all_clusters_from (PHG4Particle * truthparticle)
Definition at line 922 of file SvtxClusterEval.cc.
View newest version in sPHENIX GitHub at line 922 of file SvtxClusterEval.cc
References _cache_all_clusters_from_particle, _do_cache, _errors, _strict, assert, clusters, FillRecoClusterFromG4HitCache(), and has_node_pointers().
Referenced by best_cluster_from(), QAG4SimulationMicromegas::evaluate_clusters(), SvtxEvaluatorHaiwang::fillOutputNtuples(), psTOFTimezeroEval::fillOutputNtuples(), SvtxEvaluator::fillOutputNtuples(), SvtxEvaluatorHaiwang::printOutputInfo(), psTOFTimezeroEval::printOutputInfo(), SvtxEvaluator::printOutputInfo(), QAG4SimulationVertex::process_event(), HFMLTriggerInterface::process_event(), TrackClusterEvaluator::processRecoTracks(), TrackClusterEvaluator::processTruthTracks(), and reco_cluster_from_truth_cluster().
std::set< TrkrDefs::cluskey > SvtxClusterEval::all_clusters_from (PHG4Hit * truthhit)
Definition at line 1003 of file SvtxClusterEval.cc.
View newest version in sPHENIX GitHub at line 1003 of file SvtxClusterEval.cc
References _cache_all_clusters_from_g4hit, _cluster_hit_map, _clustermap, _clusters_per_layer, _errors, _strict, _verbosity, all_truth_hits(), assert, clusters, fill_cluster_layer_map(), TrkrCluster::getAdc(), TrkrClusterContainer::getClusters(), TrkrClusterHitAssoc::getHits(), TrkrClusterContainer::getHitSetKeys(), TrkrDefs::getLayer(), TrkrCluster::getLocalX(), TrkrCluster::getLocalY(), gtrackID, has_node_pointers(), it, and layer.
std::map< TrkrDefs::cluskey, std::shared_ptr< TrkrCluster > > SvtxClusterEval::all_truth_clusters (TrkrDefs::cluskey cluster_key)
Definition at line 72 of file SvtxClusterEval.cc.
View newest version in sPHENIX GitHub at line 72 of file SvtxClusterEval.cc
References _cache_all_truth_clusters, _do_cache, all_truth_particles(), get_truth_eval(), TrkrDefs::getLayer(), particle, and particles.
std::set< PHG4Hit * > SvtxClusterEval::all_truth_hits (TrkrDefs::cluskey cluster)
Definition at line 338 of file SvtxClusterEval.cc.
View newest version in sPHENIX GitHub at line 338 of file SvtxClusterEval.cc
References _cache_all_truth_hits, _cluster_hit_map, _do_cache, _errors, _g4hits_intt, _g4hits_mms, _g4hits_mvtx, _g4hits_tpc, _hit_truth_map, PHG4HitContainer::findHit(), TrkrHitTruthAssoc::getG4Hits(), TrkrClusterHitAssoc::getHits(), TrkrDefs::getHitSetKeyFromClusKey(), TrkrDefs::getTrkrId(), has_node_pointers(), TrkrDefs::inttId, TrkrDefs::micromegasId, TrkrDefs::mvtxId, and TrkrDefs::tpcId.
Referenced by all_clusters_from(), SvtxTrackEval::all_tracks_from(), SvtxTrackEval::all_truth_hits(), all_truth_particles(), get_energy_contribution(), and max_truth_hit_by_energy().
PHG4Hit * SvtxClusterEval::all_truth_hits_by_nhit (TrkrDefs::cluskey cluster)
Definition at line 414 of file SvtxClusterEval.cc.
View newest version in sPHENIX GitHub at line 414 of file SvtxClusterEval.cc
References _cluster_hit_map, _clustermap, _errors, _g4hits_intt, _g4hits_mms, _g4hits_mvtx, _g4hits_tpc, _hit_truth_map, _verbosity, TrkrClusterContainer::findCluster(), PHG4HitContainer::findHit(), PHG4Hit::get_avg_x(), PHG4Hit::get_avg_y(), PHG4Hit::get_avg_z(), PHG4Hit::get_layer(), TrkrHitTruthAssoc::getG4Hits(), getGlobalPosition(), TrkrClusterHitAssoc::getHits(), TrkrDefs::getHitSetKeyFromClusKey(), TrkrDefs::getLayer(), TrkrDefs::getTrkrId(), has_node_pointers(), TrkrDefs::inttId, it, layer, TrkrDefs::micromegasId, TrkrDefs::mvtxId, TrkrDefs::tpcId, and vec.
std::set< PHG4Particle * > SvtxClusterEval::all_truth_particles (TrkrDefs::cluskey cluster_key)
Definition at line 780 of file SvtxClusterEval.cc.
View newest version in sPHENIX GitHub at line 780 of file SvtxClusterEval.cc
References _cache_all_truth_particles, _do_cache, _errors, _strict, all_truth_hits(), assert, SvtxTruthEval::get_particle(), get_truth_eval(), has_node_pointers(), and particle.
Referenced by SvtxTrackEval::all_tracks_from(), all_truth_clusters(), SvtxTrackEval::all_truth_particles(), SvtxTrackEval::calc_cluster_contribution(), SvtxEvaluator::fillOutputNtuples(), FillRecoClusterFromG4HitCache(), SvtxTrackEval::get_layer_range_contribution(), SvtxTrackEval::get_nclusters_contribution_by_layer(), max_truth_particle_by_cluster_energy(), and max_truth_particle_by_energy().
TrkrDefs::cluskey SvtxClusterEval::best_cluster_by_nhit (int gid, int layer)
Definition at line 1132 of file SvtxClusterEval.cc.
View newest version in sPHENIX GitHub at line 1132 of file SvtxClusterEval.cc
References _cache_best_cluster_from_gtrackid_layer, _clustermap, _errors, _verbosity, TrkrClusterContainer::getClusters(), TrkrClusterContainer::getHitSetKeys(), TrkrDefs::getLayer(), gtrackid_and_layer_by_nhit(), has_node_pointers(), and TrkrClusterContainer::size().
Referenced by PHTruthTrackSeeding::Process().
TrkrDefs::cluskey SvtxClusterEval::best_cluster_from (PHG4Hit * truthhit)
Definition at line 1208 of file SvtxClusterEval.cc.
View newest version in sPHENIX GitHub at line 1208 of file SvtxClusterEval.cc
References _cache_best_cluster_from_g4hit, _do_cache, _errors, _strict, all_clusters_from(), assert, clusters, energy, get_energy_contribution(), and has_node_pointers().
Referenced by psTOFTimezeroEval::fillOutputNtuples(), SvtxEvaluatorHaiwang::fillOutputNtuples(), and SvtxEvaluator::fillOutputNtuples().
void SvtxClusterEval::do_caching (bool do_cache) inline
Definition at line 36 of file SvtxClusterEval.h.
View newest version in sPHENIX GitHub at line 36 of file SvtxClusterEval.h
References _do_cache, _hiteval, and SvtxHitEval::do_caching().
Referenced by SvtxTrackEval::do_caching(), and PHTruthTrackSeeding::Setup().
float SvtxClusterEval::fast_approx_atan2 (float y, float x) private
Fast approximation of atan2() for cluster searching From https://www.dsprelated.com/showarticle/1052.php
Definition at line 1446 of file SvtxClusterEval.cc.
View newest version in sPHENIX GitHub at line 1446 of file SvtxClusterEval.cc
References F, ambiguity_solver_full_chain::x, y, and physmon_track_finding_ttbar::z.
float SvtxClusterEval::fast_approx_atan2 (float y2x) private
Definition at line 1498 of file SvtxClusterEval.cc.
View newest version in sPHENIX GitHub at line 1498 of file SvtxClusterEval.cc
References physmon_track_finding_ttbar::z.
void SvtxClusterEval::fill_cluster_layer_map () private
Definition at line 1388 of file SvtxClusterEval.cc.
View newest version in sPHENIX GitHub at line 1388 of file SvtxClusterEval.cc
References _clustermap, _clusters_per_layer, _clusters_searching_window, TrkrClusterContainer::getClusters(), getGlobalPosition(), TrkrClusterContainer::getHitSetKeys(), TrkrDefs::getLayer(), and it.
Referenced by all_clusters_from().
void SvtxClusterEval::FillRecoClusterFromG4HitCache ()
Definition at line 959 of file SvtxClusterEval.cc.
View newest version in sPHENIX GitHub at line 959 of file SvtxClusterEval.cc
References _cache_all_clusters_from_particle, _clustermap, _truthinfo, all_truth_particles(), clusters, TrkrClusterContainer::getClusters(), TrkrClusterContainer::getHitSetKeys(), PHG4TruthInfoContainer::GetParticleRange(), and particles.
Referenced by all_clusters_from().
float SvtxClusterEval::get_energy_contribution (TrkrDefs::cluskey cluster_key, PHG4Particle * truthparticle)
Definition at line 1258 of file SvtxClusterEval.cc.
View newest version in sPHENIX GitHub at line 1258 of file SvtxClusterEval.cc
References _cache_get_energy_contribution_g4particle, _do_cache, _errors, _strict, all_truth_hits(), assert, energy, get_truth_eval(), and has_node_pointers().
Referenced by best_cluster_from(), psTOFTimezeroEval::fillOutputNtuples(), SvtxEvaluatorHaiwang::fillOutputNtuples(), SvtxEvaluator::fillOutputNtuples(), and max_truth_particle_by_energy().
float SvtxClusterEval::get_energy_contribution (TrkrDefs::cluskey cluster_key, PHG4Hit * truthhit)
Definition at line 1308 of file SvtxClusterEval.cc.
View newest version in sPHENIX GitHub at line 1308 of file SvtxClusterEval.cc
References _cache_get_energy_contribution_g4hit, _do_cache, _errors, _strict, all_truth_hits(), assert, energy, PHG4Hit::get_hit_id(), and has_node_pointers().
unsigned int SvtxClusterEval::get_errors () inline
Definition at line 85 of file SvtxClusterEval.h.
View newest version in sPHENIX GitHub at line 85 of file SvtxClusterEval.h
References _errors, _hiteval, and SvtxHitEval::get_errors().
Referenced by SvtxTrackEval::get_errors().
SvtxHitEval* SvtxClusterEval::get_hit_eval () inline
Definition at line 53 of file SvtxClusterEval.h.
View newest version in sPHENIX GitHub at line 53 of file SvtxClusterEval.h
References _hiteval.
Referenced by SvtxTrackEval::get_hit_eval().
void SvtxClusterEval::get_node_pointers (PHCompositeNode * topNode) private
Need a catch for if the node corrected cluster node exists but hasn't been filled yet, in e.g. the case of truth track seeding
Definition at line 1356 of file SvtxClusterEval.cc.
View newest version in sPHENIX GitHub at line 1356 of file SvtxClusterEval.cc
References _cluster_hit_map, _clustermap, _g4hits_intt, _g4hits_mms, _g4hits_mvtx, _g4hits_tpc, _hit_truth_map, _tgeometry, _truthinfo, and TrkrClusterContainer::size().
Referenced by next_event(), and SvtxClusterEval().
SvtxTruthEval* SvtxClusterEval::get_truth_eval () inline
Definition at line 54 of file SvtxClusterEval.h.
View newest version in sPHENIX GitHub at line 54 of file SvtxClusterEval.h
References _hiteval, and SvtxHitEval::get_truth_eval().
Referenced by all_truth_clusters(), all_truth_particles(), get_energy_contribution(), SvtxTrackEval::get_truth_eval(), max_truth_cluster_by_energy(), max_truth_particle_by_cluster_energy(), and reco_cluster_from_truth_cluster().
Acts::Vector3 SvtxClusterEval::getGlobalPosition (TrkrDefs::cluskey cluster_key, TrkrCluster * cluster) private
Definition at line 1507 of file SvtxClusterEval.cc.
View newest version in sPHENIX GitHub at line 1507 of file SvtxClusterEval.cc
References _tgeometry, and ActsGeometry::getGlobalPosition().
Referenced by all_truth_hits_by_nhit(), fill_cluster_layer_map(), gtrackid_and_layer_by_nhit(), max_truth_cluster_by_energy(), and reco_cluster_from_truth_cluster().
std::pair< int, int > SvtxClusterEval::gtrackid_and_layer_by_nhit (TrkrDefs::cluskey cluster)
Definition at line 558 of file SvtxClusterEval.cc.
View newest version in sPHENIX GitHub at line 558 of file SvtxClusterEval.cc
References _cluster_hit_map, _clustermap, _errors, _g4hits_intt, _g4hits_mms, _g4hits_mvtx, _g4hits_tpc, _hit_truth_map, _truthinfo, _verbosity, TrkrClusterContainer::findCluster(), PHG4HitContainer::findHit(), PHG4Hit::get_avg_x(), PHG4Hit::get_avg_y(), PHG4Hit::get_avg_z(), PHG4Hit::get_layer(), PHG4Particle::get_px(), PHG4Particle::get_py(), PHG4Particle::get_pz(), PHG4Hit::get_trkid(), PHG4Particle::get_vtx_id(), PHG4VtxPoint::get_z(), TrkrHitTruthAssoc::getG4Hits(), getGlobalPosition(), TrkrClusterHitAssoc::getHits(), TrkrDefs::getHitSetKeyFromClusKey(), TrkrDefs::getLayer(), PHG4TruthInfoContainer::GetParticle(), TrkrDefs::getTrkrId(), PHG4TruthInfoContainer::GetVtx(), TrkrCluster::getZ(), gpx, gpy, gpz, has_node_pointers(), TrkrDefs::inttId, it, layer, TrkrDefs::micromegasId, TrkrDefs::mvtxId, TrkrDefs::tpcId, and vec.
Referenced by best_cluster_by_nhit().
bool SvtxClusterEval::has_node_pointers () private
Definition at line 1423 of file SvtxClusterEval.cc.
View newest version in sPHENIX GitHub at line 1423 of file SvtxClusterEval.cc
References _clustermap, _strict, _truthinfo, and assert.
Referenced by all_clusters_from(), all_truth_hits(), all_truth_hits_by_nhit(), all_truth_particles(), best_cluster_by_nhit(), best_cluster_from(), get_energy_contribution(), gtrackid_and_layer_by_nhit(), max_truth_hit_by_energy(), max_truth_particle_by_cluster_energy(), and max_truth_particle_by_energy().
std::pair< TrkrDefs::cluskey, std::shared_ptr< TrkrCluster > > SvtxClusterEval::max_truth_cluster_by_energy (TrkrDefs::cluskey cluster_key)
Definition at line 101 of file SvtxClusterEval.cc.
View newest version in sPHENIX GitHub at line 101 of file SvtxClusterEval.cc
References _cache_max_truth_cluster_by_energy, _clustermap, _do_cache, _verbosity, SvtxTruthEval::all_truth_clusters(), dz, TrkrClusterContainer::findCluster(), PHG4Particle::get_track_id(), get_truth_eval(), getGlobalPosition(), TrkrDefs::getLayer(), gr, gx, gy, gz, max_truth_particle_by_cluster_energy(), physmon_track_finding_ttbar::r, range_intt_z, sig_intt_rphi, sig_mms_rphi_55, sig_mms_z_56, sig_mvtx_rphi, sig_mvtx_z, sig_tpc_rphi_inner, sig_tpc_rphi_mid, sig_tpc_rphi_outer, and sig_tpc_z.
Referenced by SvtxEvaluator::fillOutputNtuples(), ActsEvaluator::getGlobalTruthHit(), TrackClusterEvaluator::processRecoTracks(), and TrackClusterEvaluator::processTruthTracks().
PHG4Hit * SvtxClusterEval::max_truth_hit_by_energy (TrkrDefs::cluskey cluster_key)
Definition at line 742 of file SvtxClusterEval.cc.
View newest version in sPHENIX GitHub at line 742 of file SvtxClusterEval.cc
References _cache_max_truth_hit_by_energy, _do_cache, _errors, all_truth_hits(), PHG4Hit::get_edep(), and has_node_pointers().
Referenced by psTOFTimezeroEval::fillOutputNtuples(), SvtxEvaluatorHaiwang::fillOutputNtuples(), SvtxEvaluator::fillOutputNtuples(), psTOFTimezeroEval::printOutputInfo(), SvtxEvaluatorHaiwang::printOutputInfo(), and SvtxEvaluator::printOutputInfo().
PHG4Particle * SvtxClusterEval::max_truth_particle_by_cluster_energy (TrkrDefs::cluskey cluster_key)
Definition at line 828 of file SvtxClusterEval.cc.
View newest version in sPHENIX GitHub at line 828 of file SvtxClusterEval.cc
References _cache_max_truth_particle_by_cluster_energy, _do_cache, _errors, SvtxTruthEval::all_truth_clusters(), all_truth_particles(), Acts::UnitConstants::e, get_truth_eval(), TrkrDefs::getLayer(), has_node_pointers(), layer, particle, and particles.
Referenced by SvtxEvaluator::fillOutputNtuples(), dNdEtaINTT::GetRecoClusterInfo(), QAG4SimulationKFParticle::getTruthTrack(), and max_truth_cluster_by_energy().
PHG4Particle * SvtxClusterEval::max_truth_particle_by_energy (TrkrDefs::cluskey cluster_key)
Definition at line 878 of file SvtxClusterEval.cc.
View newest version in sPHENIX GitHub at line 878 of file SvtxClusterEval.cc
References _cache_max_truth_particle_by_energy, _do_cache, _errors, all_truth_particles(), Acts::UnitConstants::e, get_energy_contribution(), has_node_pointers(), particle, and particles.
void SvtxClusterEval::next_event (PHCompositeNode * topNode)
Definition at line 50 of file SvtxClusterEval.cc.
View newest version in sPHENIX GitHub at line 50 of file SvtxClusterEval.cc
References _cache_all_clusters_from_g4hit, _cache_all_clusters_from_particle, _cache_all_truth_clusters, _cache_all_truth_hits, _cache_all_truth_particles, _cache_best_cluster_from_g4hit, _cache_best_cluster_from_gtrackid_layer, _cache_get_energy_contribution_g4hit, _cache_get_energy_contribution_g4particle, _cache_max_truth_cluster_by_energy, _cache_max_truth_hit_by_energy, _cache_max_truth_particle_by_cluster_energy, _cache_max_truth_particle_by_energy, _clusters_per_layer, _hiteval, get_node_pointers(), and SvtxHitEval::next_event().
Referenced by SvtxTrackEval::next_event(), and PHTruthTrackSeeding::Process().
std::pair< TrkrDefs::cluskey, TrkrCluster * > SvtxClusterEval::reco_cluster_from_truth_cluster (TrkrDefs::cluskey ckey, const std::shared_ptr< TrkrCluster > & gclus)
Definition at line 214 of file SvtxClusterEval.cc.
View newest version in sPHENIX GitHub at line 214 of file SvtxClusterEval.cc
References _cache_reco_cluster_from_truth_cluster, _clustermap, _do_cache, _verbosity, all_clusters_from(), dz, TrkrClusterContainer::findCluster(), get_truth_eval(), SvtxTruthEval::get_truth_hits_from_truth_cluster(), getGlobalPosition(), TrkrDefs::getLayer(), gr, gx, gy, gz, range_intt_z, sig_intt_rphi, sig_mms_rphi_55, sig_mms_z_56, sig_mvtx_rphi, sig_mvtx_z, sig_tpc_rphi_inner, sig_tpc_rphi_mid, sig_tpc_rphi_outer, and sig_tpc_z.
Referenced by QAG4SimulationTpc::evaluate_clusters(), and SvtxEvaluator::fillOutputNtuples().
void SvtxClusterEval::set_strict (bool strict) inline
Definition at line 41 of file SvtxClusterEval.h.
View newest version in sPHENIX GitHub at line 41 of file SvtxClusterEval.h
References _hiteval, _strict, and SvtxHitEval::set_strict().
Referenced by SvtxTrackEval::set_strict().
void SvtxClusterEval::set_verbosity (int verbosity) inline
Definition at line 46 of file SvtxClusterEval.h.
View newest version in sPHENIX GitHub at line 46 of file SvtxClusterEval.h
References _hiteval, _verbosity, SvtxHitEval::set_verbosity(), and verbosity.
Referenced by SvtxTrackEval::set_verbosity().
Member Data Documentation
std::map<PHG4Hit*, std::set<TrkrDefs::cluskey> > SvtxClusterEval::_cache_all_clusters_from_g4hit private
Definition at line 124 of file SvtxClusterEval.h.
View newest version in sPHENIX GitHub at line 124 of file SvtxClusterEval.h
Referenced by all_clusters_from(), and next_event().
std::map<PHG4Particle*, std::set<TrkrDefs::cluskey> > SvtxClusterEval::_cache_all_clusters_from_particle private
Definition at line 123 of file SvtxClusterEval.h.
View newest version in sPHENIX GitHub at line 123 of file SvtxClusterEval.h
Referenced by all_clusters_from(), FillRecoClusterFromG4HitCache(), and next_event().
std::map<TrkrDefs::cluskey, std::map<TrkrDefs::cluskey, std::shared_ptr<TrkrCluster> > > SvtxClusterEval::_cache_all_truth_clusters private
Definition at line 117 of file SvtxClusterEval.h.
View newest version in sPHENIX GitHub at line 117 of file SvtxClusterEval.h
Referenced by all_truth_clusters(), and next_event().
std::map<TrkrDefs::cluskey, std::set<PHG4Hit*> > SvtxClusterEval::_cache_all_truth_hits private
Definition at line 116 of file SvtxClusterEval.h.
View newest version in sPHENIX GitHub at line 116 of file SvtxClusterEval.h
Referenced by all_truth_hits(), and next_event().
std::map<TrkrDefs::cluskey, std::set<PHG4Particle*> > SvtxClusterEval::_cache_all_truth_particles private
Definition at line 120 of file SvtxClusterEval.h.
View newest version in sPHENIX GitHub at line 120 of file SvtxClusterEval.h
Referenced by all_truth_particles(), and next_event().
std::map<PHG4Hit*, TrkrDefs::cluskey> SvtxClusterEval::_cache_best_cluster_from_g4hit private
Definition at line 125 of file SvtxClusterEval.h.
View newest version in sPHENIX GitHub at line 125 of file SvtxClusterEval.h
Referenced by best_cluster_from(), and next_event().
std::map<std::pair<int, int>, TrkrDefs::cluskey> SvtxClusterEval::_cache_best_cluster_from_gtrackid_layer private
Definition at line 126 of file SvtxClusterEval.h.
View newest version in sPHENIX GitHub at line 126 of file SvtxClusterEval.h
Referenced by best_cluster_by_nhit(), and next_event().
std::map<std::pair<TrkrDefs::cluskey, PHG4Hit*>, float> SvtxClusterEval::_cache_get_energy_contribution_g4hit private
Definition at line 128 of file SvtxClusterEval.h.
View newest version in sPHENIX GitHub at line 128 of file SvtxClusterEval.h
Referenced by get_energy_contribution(), and next_event().
std::map<std::pair<TrkrDefs::cluskey, PHG4Particle*>, float> SvtxClusterEval::_cache_get_energy_contribution_g4particle private
Definition at line 127 of file SvtxClusterEval.h.
View newest version in sPHENIX GitHub at line 127 of file SvtxClusterEval.h
Referenced by get_energy_contribution(), and next_event().
std::map<TrkrDefs::cluskey, std::pair<TrkrDefs::cluskey, std::shared_ptr<TrkrCluster> > > SvtxClusterEval::_cache_max_truth_cluster_by_energy private
Definition at line 119 of file SvtxClusterEval.h.
View newest version in sPHENIX GitHub at line 119 of file SvtxClusterEval.h
Referenced by max_truth_cluster_by_energy(), and next_event().
std::map<TrkrDefs::cluskey, PHG4Hit*> SvtxClusterEval::_cache_max_truth_hit_by_energy private
Definition at line 118 of file SvtxClusterEval.h.
View newest version in sPHENIX GitHub at line 118 of file SvtxClusterEval.h
Referenced by max_truth_hit_by_energy(), and next_event().
std::map<TrkrDefs::cluskey, PHG4Particle*> SvtxClusterEval::_cache_max_truth_particle_by_cluster_energy private
Definition at line 122 of file SvtxClusterEval.h.
View newest version in sPHENIX GitHub at line 122 of file SvtxClusterEval.h
Referenced by max_truth_particle_by_cluster_energy(), and next_event().
std::map<TrkrDefs::cluskey, PHG4Particle*> SvtxClusterEval::_cache_max_truth_particle_by_energy private
Definition at line 121 of file SvtxClusterEval.h.
View newest version in sPHENIX GitHub at line 121 of file SvtxClusterEval.h
Referenced by max_truth_particle_by_energy(), and next_event().
std::map<std::shared_ptr<TrkrCluster>, std::pair<TrkrDefs::cluskey, TrkrCluster*> > SvtxClusterEval::_cache_reco_cluster_from_truth_cluster private
Definition at line 129 of file SvtxClusterEval.h.
View newest version in sPHENIX GitHub at line 129 of file SvtxClusterEval.h
Referenced by reco_cluster_from_truth_cluster().
TrkrClusterHitAssoc* SvtxClusterEval::_cluster_hit_map = nullptr private
Definition at line 100 of file SvtxClusterEval.h.
View newest version in sPHENIX GitHub at line 100 of file SvtxClusterEval.h
Referenced by all_clusters_from(), all_truth_hits(), all_truth_hits_by_nhit(), get_node_pointers(), and gtrackid_and_layer_by_nhit().
TrkrClusterContainer* SvtxClusterEval::_clustermap = nullptr private
Definition at line 99 of file SvtxClusterEval.h.
View newest version in sPHENIX GitHub at line 99 of file SvtxClusterEval.h
Referenced by all_clusters_from(), all_truth_hits_by_nhit(), best_cluster_by_nhit(), fill_cluster_layer_map(), FillRecoClusterFromG4HitCache(), get_node_pointers(), gtrackid_and_layer_by_nhit(), has_node_pointers(), max_truth_cluster_by_energy(), and reco_cluster_from_truth_cluster().
std::multimap<unsigned int, innerMap> SvtxClusterEval::_clusters_per_layer private
Definition at line 145 of file SvtxClusterEval.h.
View newest version in sPHENIX GitHub at line 145 of file SvtxClusterEval.h
Referenced by all_clusters_from(), fill_cluster_layer_map(), and next_event().
constexpr float SvtxClusterEval::_clusters_searching_window = 0.1f static private
cluster azimuthal searching window in _clusters_per_layer. Unit: rad
Definition at line 144 of file SvtxClusterEval.h.
View newest version in sPHENIX GitHub at line 144 of file SvtxClusterEval.h
Referenced by fill_cluster_layer_map().
bool SvtxClusterEval::_do_cache = true private
Definition at line 115 of file SvtxClusterEval.h.
View newest version in sPHENIX GitHub at line 115 of file SvtxClusterEval.h
Referenced by all_clusters_from(), all_truth_clusters(), all_truth_hits(), all_truth_particles(), best_cluster_from(), do_caching(), get_energy_contribution(), max_truth_cluster_by_energy(), max_truth_hit_by_energy(), max_truth_particle_by_cluster_energy(), max_truth_particle_by_energy(), and reco_cluster_from_truth_cluster().
unsigned int SvtxClusterEval::_errors = 0 private
Definition at line 111 of file SvtxClusterEval.h.
View newest version in sPHENIX GitHub at line 111 of file SvtxClusterEval.h
Referenced by all_clusters_from(), all_truth_hits(), all_truth_hits_by_nhit(), all_truth_particles(), best_cluster_by_nhit(), best_cluster_from(), get_energy_contribution(), get_errors(), gtrackid_and_layer_by_nhit(), max_truth_hit_by_energy(), max_truth_particle_by_cluster_energy(), max_truth_particle_by_energy(), and ~SvtxClusterEval().
PHG4HitContainer* SvtxClusterEval::_g4hits_intt = nullptr private
Definition at line 104 of file SvtxClusterEval.h.
View newest version in sPHENIX GitHub at line 104 of file SvtxClusterEval.h
Referenced by all_truth_hits(), all_truth_hits_by_nhit(), get_node_pointers(), and gtrackid_and_layer_by_nhit().
PHG4HitContainer* SvtxClusterEval::_g4hits_mms = nullptr private
Definition at line 106 of file SvtxClusterEval.h.
View newest version in sPHENIX GitHub at line 106 of file SvtxClusterEval.h
Referenced by all_truth_hits(), all_truth_hits_by_nhit(), get_node_pointers(), and gtrackid_and_layer_by_nhit().
PHG4HitContainer* SvtxClusterEval::_g4hits_mvtx = nullptr private
Definition at line 105 of file SvtxClusterEval.h.
View newest version in sPHENIX GitHub at line 105 of file SvtxClusterEval.h
Referenced by all_truth_hits(), all_truth_hits_by_nhit(), get_node_pointers(), and gtrackid_and_layer_by_nhit().
PHG4HitContainer* SvtxClusterEval::_g4hits_tpc = nullptr private
Definition at line 103 of file SvtxClusterEval.h.
View newest version in sPHENIX GitHub at line 103 of file SvtxClusterEval.h
Referenced by all_truth_hits(), all_truth_hits_by_nhit(), get_node_pointers(), and gtrackid_and_layer_by_nhit().
TrkrHitTruthAssoc* SvtxClusterEval::_hit_truth_map = nullptr private
Definition at line 101 of file SvtxClusterEval.h.
View newest version in sPHENIX GitHub at line 101 of file SvtxClusterEval.h
Referenced by all_truth_hits(), all_truth_hits_by_nhit(), get_node_pointers(), and gtrackid_and_layer_by_nhit().
SvtxHitEval SvtxClusterEval::_hiteval private
Definition at line 98 of file SvtxClusterEval.h.
View newest version in sPHENIX GitHub at line 98 of file SvtxClusterEval.h
Referenced by do_caching(), get_errors(), get_hit_eval(), get_truth_eval(), next_event(), set_strict(), and set_verbosity().
bool SvtxClusterEval::_strict = false private
Definition at line 109 of file SvtxClusterEval.h.
View newest version in sPHENIX GitHub at line 109 of file SvtxClusterEval.h
Referenced by all_clusters_from(), all_truth_particles(), best_cluster_from(), get_energy_contribution(), has_node_pointers(), and set_strict().
ActsGeometry* SvtxClusterEval::_tgeometry = nullptr private
Definition at line 107 of file SvtxClusterEval.h.
View newest version in sPHENIX GitHub at line 107 of file SvtxClusterEval.h
Referenced by get_node_pointers(), and getGlobalPosition().
PHG4TruthInfoContainer* SvtxClusterEval::_truthinfo = nullptr private
Definition at line 102 of file SvtxClusterEval.h.
View newest version in sPHENIX GitHub at line 102 of file SvtxClusterEval.h
Referenced by FillRecoClusterFromG4HitCache(), get_node_pointers(), gtrackid_and_layer_by_nhit(), and has_node_pointers().
int SvtxClusterEval::_verbosity = 0 private
Definition at line 110 of file SvtxClusterEval.h.
View newest version in sPHENIX GitHub at line 110 of file SvtxClusterEval.h
Referenced by all_clusters_from(), all_truth_hits_by_nhit(), best_cluster_by_nhit(), gtrackid_and_layer_by_nhit(), max_truth_cluster_by_energy(), reco_cluster_from_truth_cluster(), set_verbosity(), and ~SvtxClusterEval().
const float SvtxClusterEval::range_intt_z = 0.9 private
Definition at line 137 of file SvtxClusterEval.h.
View newest version in sPHENIX GitHub at line 137 of file SvtxClusterEval.h
Referenced by max_truth_cluster_by_energy(), and reco_cluster_from_truth_cluster().
const float SvtxClusterEval::sig_intt_rphi = 17e-04 private
Definition at line 136 of file SvtxClusterEval.h.
View newest version in sPHENIX GitHub at line 136 of file SvtxClusterEval.h
Referenced by max_truth_cluster_by_energy(), and reco_cluster_from_truth_cluster().
const float SvtxClusterEval::sig_mms_rphi_55 = 100e-04 private
Definition at line 140 of file SvtxClusterEval.h.
View newest version in sPHENIX GitHub at line 140 of file SvtxClusterEval.h
Referenced by max_truth_cluster_by_energy(), and reco_cluster_from_truth_cluster().
const float SvtxClusterEval::sig_mms_z_56 = 200e-04 private
Definition at line 141 of file SvtxClusterEval.h.
View newest version in sPHENIX GitHub at line 141 of file SvtxClusterEval.h
Referenced by max_truth_cluster_by_energy(), and reco_cluster_from_truth_cluster().
const float SvtxClusterEval::sig_mvtx_rphi = 4.0e-04 private
Definition at line 138 of file SvtxClusterEval.h.
View newest version in sPHENIX GitHub at line 138 of file SvtxClusterEval.h
Referenced by max_truth_cluster_by_energy(), and reco_cluster_from_truth_cluster().
const float SvtxClusterEval::sig_mvtx_z = 4.7e-04 private
Definition at line 139 of file SvtxClusterEval.h.
View newest version in sPHENIX GitHub at line 139 of file SvtxClusterEval.h
Referenced by max_truth_cluster_by_energy(), and reco_cluster_from_truth_cluster().
const float SvtxClusterEval::sig_tpc_rphi_inner = 220e-04 private
Definition at line 132 of file SvtxClusterEval.h.
View newest version in sPHENIX GitHub at line 132 of file SvtxClusterEval.h
Referenced by max_truth_cluster_by_energy(), and reco_cluster_from_truth_cluster().
const float SvtxClusterEval::sig_tpc_rphi_mid = 155e-04 private
Definition at line 133 of file SvtxClusterEval.h.
View newest version in sPHENIX GitHub at line 133 of file SvtxClusterEval.h
Referenced by max_truth_cluster_by_energy(), and reco_cluster_from_truth_cluster().
const float SvtxClusterEval::sig_tpc_rphi_outer = 165e-04 private
Definition at line 134 of file SvtxClusterEval.h.
View newest version in sPHENIX GitHub at line 134 of file SvtxClusterEval.h
Referenced by max_truth_cluster_by_energy(), and reco_cluster_from_truth_cluster().
const float SvtxClusterEval::sig_tpc_z = 750e-04 private
Definition at line 135 of file SvtxClusterEval.h.
View newest version in sPHENIX GitHub at line 135 of file SvtxClusterEval.h
Referenced by max_truth_cluster_by_energy(), and reco_cluster_from_truth_cluster().
The documentation for this class was generated from the following files:
coresoftware/blob/master/simulation/g4simulation/g4eval/SvtxClusterEval.h
coresoftware/blob/master/simulation/g4simulation/g4eval/SvtxClusterEval.cc