Analysis Software: CentralityInfov1 Class Reference
CentralityInfov1 Class Reference
#include <coresoftware/blob/master/offline/packages/centrality/CentralityInfov1.h>
Public Member Functions
CentralityInfov1 ()=default
~CentralityInfov1 () override
void identify (std::ostream &os=std::cout) const override
void Reset () override
Clear Event.
int isValid () const override
isValid returns non zero if object contains vailid data
bool has_quantity (const PROP prop_id) const override
float get_quantity (const PROP prop_id) const override
void set_quantity (const PROP prop_id, const float value) override
bool has_centile (const PROP prop_id) const override
float get_centile (const PROP prop_id) const override
void set_centile (const PROP prop_id, const float value) override
Public Member Functions inherited from CentralityInfo
~CentralityInfo () override
virtual bool has_centrality_bin (const PROP) const
virtual int get_centrality_bin (const PROP) const
virtual void set_centrality_bin (const PROP, const int)
Public Member Functions inherited from PHObject
PHObject ()
ctor
~PHObject () override
dtor
virtual PHObject * CloneMe () const
Virtual copy constructor.
virtual PHObject * clone () const final
PHObject * Clone (const char *newname="") const final
void Copy (TObject &object) const final
virtual int Integrate () const
virtual int Integrate (PHObject *)
virtual void CopyFrom (const PHObject *obj)
Private Member Functions
ClassDefOverride (CentralityInfov1, 1)
Private Attributes
std::map< int, float > _quantity_map
std::map< int, float > _centile_map
Additional Inherited Members
Public Types inherited from CentralityInfo
enum PROP {
mbd_N = 0, mbd_S = 1, mbd_NS = 2, epd_N = 3,
epd_S = 4, epd_NS = 5, bimp = 6
}
Protected Member Functions inherited from CentralityInfo
CentralityInfo ()
Detailed Description
Definition at line 9 of file CentralityInfov1.h.
View newest version in sPHENIX GitHub at line 9 of file CentralityInfov1.h
Constructor & Destructor Documentation
CentralityInfov1::CentralityInfov1 () default
CentralityInfov1::~CentralityInfov1 () inline override
Definition at line 13 of file CentralityInfov1.h.
View newest version in sPHENIX GitHub at line 13 of file CentralityInfov1.h
Member Function Documentation
CentralityInfov1::ClassDefOverride (CentralityInfov1 , 1) private
float CentralityInfov1::get_centile (const PROP prop_id) const override virtual
Reimplemented from CentralityInfo.
Definition at line 50 of file CentralityInfov1.cc.
View newest version in sPHENIX GitHub at line 50 of file CentralityInfov1.cc
References _centile_map, and has_centile().
Referenced by CentralityInfov2::identify(), and TPCHitTrackDisplay::SimulationOut().
float CentralityInfov1::get_quantity (const PROP prop_id) const override virtual
Reimplemented from CentralityInfo.
Definition at line 28 of file CentralityInfov1.cc.
View newest version in sPHENIX GitHub at line 28 of file CentralityInfov1.cc
References _quantity_map, and has_quantity().
bool CentralityInfov1::has_centile (const PROP prop_id) const override virtual
Reimplemented from CentralityInfo.
Definition at line 40 of file CentralityInfov1.cc.
View newest version in sPHENIX GitHub at line 40 of file CentralityInfov1.cc
References _centile_map.
Referenced by get_centile(), and CentralityInfov2::identify().
bool CentralityInfov1::has_quantity (const PROP prop_id) const override virtual
Reimplemented from CentralityInfo.
Definition at line 18 of file CentralityInfov1.cc.
View newest version in sPHENIX GitHub at line 18 of file CentralityInfov1.cc
References _quantity_map.
Referenced by get_quantity().
void CentralityInfov1::identify (std::ostream & os = std::cout) const override virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from CentralityInfo.
Reimplemented in CentralityInfov2.
Definition at line 5 of file CentralityInfov1.cc.
View newest version in sPHENIX GitHub at line 5 of file CentralityInfov1.cc
int CentralityInfov1::isValid () const inline override virtual
isValid returns non zero if object contains vailid data
Reimplemented from CentralityInfo.
Definition at line 17 of file CentralityInfov1.h.
View newest version in sPHENIX GitHub at line 17 of file CentralityInfov1.h
void CentralityInfov1::Reset () override virtual
Clear Event.
Reimplemented from PHObject.
Reimplemented in CentralityInfov2.
Definition at line 12 of file CentralityInfov1.cc.
View newest version in sPHENIX GitHub at line 12 of file CentralityInfov1.cc
References _centile_map, and _quantity_map.
void CentralityInfov1::set_centile (const PROP prop_id, const float value) override virtual
Reimplemented from CentralityInfo.
Definition at line 45 of file CentralityInfov1.cc.
View newest version in sPHENIX GitHub at line 45 of file CentralityInfov1.cc
References _centile_map, and value.
void CentralityInfov1::set_quantity (const PROP prop_id, const float value) override virtual
Reimplemented from CentralityInfo.
Definition at line 23 of file CentralityInfov1.cc.
View newest version in sPHENIX GitHub at line 23 of file CentralityInfov1.cc
References _quantity_map, and value.
Member Data Documentation
std::map<int, float> CentralityInfov1::_centile_map private
Definition at line 29 of file CentralityInfov1.h.
View newest version in sPHENIX GitHub at line 29 of file CentralityInfov1.h
Referenced by get_centile(), has_centile(), Reset(), and set_centile().
std::map<int, float> CentralityInfov1::_quantity_map private
Definition at line 28 of file CentralityInfov1.h.
View newest version in sPHENIX GitHub at line 28 of file CentralityInfov1.h
Referenced by get_quantity(), has_quantity(), Reset(), and set_quantity().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/centrality/CentralityInfov1.h
coresoftware/blob/master/offline/packages/centrality/CentralityInfov1.cc