Analysis Software: shower2 Class Reference
shower2 Class Reference
Public Member Functions
shower2 ()
virtual ~shower2 ()
node new_vertex (shared_ptr< vertex > v)
void new_parton (node s, node t, unique_ptr< parton > p)
void save_node_info_handler (ostream *o, node n) const
void save_edge_info_handler (ostream *o, edge n) const
double GetEdgeValue (edge n) const
int GetNodeValue (node n) const
bool GetFinal (edge e) const
void pre_clear_handler ()
vector< weak_ptr< parton > > GetPartons ()
shower2 ()
virtual ~shower2 ()
node new_vertex (int x)
void new_parton (node s, node t, unique_ptr< parton > p)
void save_edge_info_handler (ostream *o, edge n) const
double GetEdgeValue (edge n) const
int GetNodeValue (node n) const
bool GetFinal (edge e) const
void post_new_edge_handler (edge e)
void pre_clear_handler ()
shower2 ()
virtual ~shower2 ()
node new_vertex (shared_ptr< vertex > v)
void new_parton (node s, node t, unique_ptr< parton > p)
void save_node_info_handler (ostream *o, node n) const
void save_edge_info_handler (ostream *o, edge n) const
void load_edge_info_handler (edge e, GML_pair *read)
void load_node_info_handler (node n, GML_pair *read)
double GetEdgeValue (edge n) const
int GetNodeValue (node n) const
bool GetFinal (edge e) const
void pre_clear_handler ()
vector< weak_ptr< parton > > GetPartons ()
shower2 ()
virtual ~shower2 ()
node new_vertex (shared_ptr< vertex > v)
void new_parton (node s, node t, unique_ptr< parton > p)
void save_node_info_handler (ostream *o, node n) const
void save_edge_info_handler (ostream *o, edge n) const
void load_edge_info_handler (edge e, GML_pair *read)
void load_node_info_handler (node n, GML_pair *read)
double GetEdgeValue (edge n) const
int GetNodeValue (node n) const
bool GetFinal (edge e) const
void pre_clear_handler ()
vector< weak_ptr< parton > > GetPartons ()
Public Member Functions inherited from graph
graph ()
graph (const graph &G)
graph (const graph &G, const list< node > &nodes)
graph (const graph &G, list< node >::const_iterator it, list< node >::const_iterator end)
virtual ~graph ()
void make_directed ()
void make_undirected ()
bool is_directed () const
bool is_undirected () const
bool is_bidirected (edge_map< edge > &rev) const
bool is_connected () const
bool is_acyclic () const
int number_of_nodes () const
int number_of_edges () const
node center () const
virtual node new_node ()
virtual edge new_edge (node s, node t)
virtual edge new_edge (const list< node > &sources, const list< node > &targets)
void del_node (node n)
void del_all_nodes ()
void del_edge (edge e)
void del_all_edges ()
void clear ()
node_iterator nodes_begin () const
node_iterator nodes_end () const
edge_iterator edges_begin () const
edge_iterator edges_end () const
list< node > all_nodes () const
list< edge > all_edges () const
node choose_node () const
void hide_edge (edge e)
void restore_edge (edge e)
list< edge > hide_node (node n)
void restore_node (node n)
void induced_subgraph (list< node > &subgraph_nodes)
void restore_graph ()
list< edge > insert_reverse_edges ()
GML_error load (const string &filename, bool preserve_ids=false)
GML_error load (const char *filename, bool preserve_ids=false)
int save (const char *filename) const
void save (ostream *file=&cout) const
virtual void pre_new_node_handler ()
virtual void post_new_node_handler (node n)
virtual void pre_del_node_handler (node n)
virtual void post_del_node_handler ()
virtual void pre_hide_node_handler (node n)
virtual void post_hide_node_handler (node n)
virtual void pre_restore_node_handler (node n)
virtual void post_restore_node_handler (node n)
virtual void pre_new_edge_handler (node s, node t)
virtual void pre_del_edge_handler (edge e)
virtual void post_del_edge_handler (node, node)
virtual void pre_hide_edge_handler (edge e)
virtual void post_hide_edge_handler (edge e)
virtual void pre_restore_edge_handler (edge e)
virtual void post_restore_edge_handler (edge e)
virtual void post_clear_handler ()
virtual void pre_make_directed_handler ()
virtual void post_make_directed_handler ()
virtual void pre_make_undirected_handler ()
virtual void post_make_undirected_handler ()
virtual void pre_graph_save_handler (ostream *os) const
virtual void save_graph_info_handler (ostream *) const
virtual void after_graph_save_handler (ostream *) const
virtual void top_level_key_handler (GML_pair *list)
virtual void load_graph_info_handler (GML_pair *list)
int number_of_ids (node) const
int number_of_ids (edge) const
Private Attributes
node_map< shared_ptr< vertex > > XX
edge_map< shared_ptr< parton > > PP
node_map< int > XX
Additional Inherited Members
Public Types inherited from graph
typedef list< node >
::const_iterator node_iterator
typedef list< edge >
::const_iterator edge_iterator
Detailed Description
Definition at line 45 of file graph_test.cpp.
View newest version in sPHENIX GitHub at line 45 of file graph_test.cpp
Constructor & Destructor Documentation
shower2::shower2 () inline
Definition at line 49 of file graph_test.cpp.
View newest version in sPHENIX GitHub at line 49 of file graph_test.cpp
virtual shower2::~shower2 () inline virtual
Definition at line 50 of file graph_test.cpp.
View newest version in sPHENIX GitHub at line 50 of file graph_test.cpp
shower2::shower2 () inline
Definition at line 72 of file my_test2.cc.
View newest version in sPHENIX GitHub at line 72 of file my_test2.cc
virtual shower2::~shower2 () inline virtual
Definition at line 73 of file my_test2.cc.
View newest version in sPHENIX GitHub at line 73 of file my_test2.cc
shower2::shower2 () inline
Definition at line 41 of file my_test3.cc.
View newest version in sPHENIX GitHub at line 41 of file my_test3.cc
virtual shower2::~shower2 () inline virtual
Definition at line 42 of file my_test3.cc.
View newest version in sPHENIX GitHub at line 42 of file my_test3.cc
shower2::shower2 () inline
Definition at line 40 of file my_test4.cc.
View newest version in sPHENIX GitHub at line 40 of file my_test4.cc
virtual shower2::~shower2 () inline virtual
Definition at line 41 of file my_test4.cc.
View newest version in sPHENIX GitHub at line 41 of file my_test4.cc
Member Function Documentation
double shower2::GetEdgeValue (edge n) const inline
Definition at line 61 of file graph_test.cpp.
View newest version in sPHENIX GitHub at line 61 of file graph_test.cpp
References n, and PP.
double shower2::GetEdgeValue (edge n) const inline
Definition at line 81 of file my_test2.cc.
View newest version in sPHENIX GitHub at line 81 of file my_test2.cc
References n, and PP.
double shower2::GetEdgeValue (edge n) const inline
Definition at line 129 of file my_test4.cc.
View newest version in sPHENIX GitHub at line 129 of file my_test4.cc
References n, and PP.
double shower2::GetEdgeValue (edge n) const inline
Definition at line 130 of file my_test3.cc.
View newest version in sPHENIX GitHub at line 130 of file my_test3.cc
References n, and PP.
bool shower2::GetFinal (edge e) const inline
Definition at line 63 of file graph_test.cpp.
View newest version in sPHENIX GitHub at line 63 of file graph_test.cpp
References Acts::UnitConstants::e, and PP.
bool shower2::GetFinal (edge e) const inline
Definition at line 83 of file my_test2.cc.
View newest version in sPHENIX GitHub at line 83 of file my_test2.cc
References Acts::UnitConstants::e, and PP.
bool shower2::GetFinal (edge e) const inline
Definition at line 131 of file my_test4.cc.
View newest version in sPHENIX GitHub at line 131 of file my_test4.cc
References Acts::UnitConstants::e, and PP.
bool shower2::GetFinal (edge e) const inline
Definition at line 132 of file my_test3.cc.
View newest version in sPHENIX GitHub at line 132 of file my_test3.cc
References Acts::UnitConstants::e, and PP.
int shower2::GetNodeValue (node n) const inline
Definition at line 62 of file graph_test.cpp.
View newest version in sPHENIX GitHub at line 62 of file graph_test.cpp
References n, and XX.
int shower2::GetNodeValue (node n) const inline
Definition at line 82 of file my_test2.cc.
View newest version in sPHENIX GitHub at line 82 of file my_test2.cc
References n, and XX.
int shower2::GetNodeValue (node n) const inline
Definition at line 130 of file my_test4.cc.
View newest version in sPHENIX GitHub at line 130 of file my_test4.cc
References n, and XX.
int shower2::GetNodeValue (node n) const inline
Definition at line 131 of file my_test3.cc.
View newest version in sPHENIX GitHub at line 131 of file my_test3.cc
References n, and XX.
vector<weak_ptr<parton> > shower2::GetPartons () inline
Definition at line 98 of file graph_test.cpp.
View newest version in sPHENIX GitHub at line 98 of file graph_test.cpp
References graph::all_edges(), it, n, and PP.
vector<weak_ptr<parton> > shower2::GetPartons () inline
Definition at line 166 of file my_test4.cc.
View newest version in sPHENIX GitHub at line 166 of file my_test4.cc
References graph::all_edges(), it, n, and PP.
vector<weak_ptr<parton> > shower2::GetPartons () inline
Definition at line 167 of file my_test3.cc.
View newest version in sPHENIX GitHub at line 167 of file my_test3.cc
References graph::all_edges(), it, n, and PP.
void shower2::load_edge_info_handler (edge e, GML_pair * list) inline virtual
Called after an edge is created. The whole list of key-value-pairs belonging to this edge is passed to this handler together with the edge itself.
Parameters
<code>e</code> edge parsed
<code>list</code> pointer to the list of key-value-pairs of this edge.
See Also
graph::load
Reimplemented from graph.
Definition at line 53 of file my_test4.cc.
View newest version in sPHENIX GitHub at line 53 of file my_test4.cc
References Acts::UnitConstants::e, GML_pair_val::floating, GML_pair::key, GML_pair::next, PP, ActsExamples::JsonSurfacesReader::read(), Acts::Test::tmp(), and GML_pair::value.
void shower2::load_edge_info_handler (edge e, GML_pair * list) inline virtual
Called after an edge is created. The whole list of key-value-pairs belonging to this edge is passed to this handler together with the edge itself.
Parameters
<code>e</code> edge parsed
<code>list</code> pointer to the list of key-value-pairs of this edge.
See Also
graph::load
Reimplemented from graph.
Definition at line 54 of file my_test3.cc.
View newest version in sPHENIX GitHub at line 54 of file my_test3.cc
References Acts::UnitConstants::e, GML_pair_val::floating, GML_pair::key, GML_pair::next, PP, ActsExamples::JsonSurfacesReader::read(), Acts::Test::tmp(), and GML_pair::value.
void shower2::load_node_info_handler (node n, GML_pair * list) inline virtual
Called after a node is created. The whole list of key-value-pairs belonging to this node is passed to this handler together with the node itself.
Parameters
<code>n</code> node parsed
<code>list</code> pointer to the list of key-value-pairs of this node.
See Also
graph::load
Reimplemented from graph.
Definition at line 71 of file my_test4.cc.
View newest version in sPHENIX GitHub at line 71 of file my_test4.cc
References i, GML_pair_val::integer, GML_pair::key, physmon_simulation::level, n, GML_pair::next, ActsExamples::JsonSurfacesReader::read(), Acts::Test::tmp(), GML_pair::value, and XX.
void shower2::load_node_info_handler (node n, GML_pair * list) inline virtual
Called after a node is created. The whole list of key-value-pairs belonging to this node is passed to this handler together with the node itself.
Parameters
<code>n</code> node parsed
<code>list</code> pointer to the list of key-value-pairs of this node.
See Also
graph::load
Reimplemented from graph.
Definition at line 72 of file my_test3.cc.
View newest version in sPHENIX GitHub at line 72 of file my_test3.cc
References i, GML_pair_val::integer, GML_pair::key, physmon_simulation::level, n, GML_pair::next, ActsExamples::JsonSurfacesReader::read(), Acts::Test::tmp(), GML_pair::value, and XX.
void shower2::new_parton (node s, node t, unique_ptr< parton > p) inline
Definition at line 45 of file my_test4.cc.
View newest version in sPHENIX GitHub at line 45 of file my_test4.cc
References Acts::UnitConstants::e, testing::internal::move(), graph::new_edge(), and PP.
void shower2::new_parton (node s, node t, unique_ptr< parton > p) inline
Definition at line 46 of file my_test3.cc.
View newest version in sPHENIX GitHub at line 46 of file my_test3.cc
References Acts::UnitConstants::e, testing::internal::move(), graph::new_edge(), and PP.
void shower2::new_parton (node s, node t, unique_ptr< parton > p) inline
Definition at line 54 of file graph_test.cpp.
View newest version in sPHENIX GitHub at line 54 of file graph_test.cpp
References Acts::UnitConstants::e, testing::internal::move(), graph::new_edge(), and PP.
void shower2::new_parton (node s, node t, unique_ptr< parton > p) inline
Definition at line 77 of file my_test2.cc.
View newest version in sPHENIX GitHub at line 77 of file my_test2.cc
References Acts::UnitConstants::e, testing::internal::move(), graph::new_edge(), and PP.
node shower2::new_vertex (shared_ptr< vertex > v) inline
Definition at line 43 of file my_test4.cc.
View newest version in sPHENIX GitHub at line 43 of file my_test4.cc
References n, graph::new_node(), testSigmaEff::v, and XX.
node shower2::new_vertex (shared_ptr< vertex > v) inline
Definition at line 44 of file my_test3.cc.
View newest version in sPHENIX GitHub at line 44 of file my_test3.cc
References n, graph::new_node(), testSigmaEff::v, and XX.
node shower2::new_vertex (shared_ptr< vertex > v) inline
Definition at line 52 of file graph_test.cpp.
View newest version in sPHENIX GitHub at line 52 of file graph_test.cpp
References n, graph::new_node(), testSigmaEff::v, and XX.
node shower2::new_vertex (int x) inline
Definition at line 75 of file my_test2.cc.
View newest version in sPHENIX GitHub at line 75 of file my_test2.cc
References n, graph::new_node(), ambiguity_solver_full_chain::x, and XX.
void shower2::post_new_edge_handler (edge e) inline virtual
Virtual function called after a new edge was inserted; can be redefined in a derived class for customization
Parameters
<code>e</code> created edge
See Also
graph::new_edge
Reimplemented from graph.
Definition at line 85 of file my_test2.cc.
View newest version in sPHENIX GitHub at line 85 of file my_test2.cc
void shower2::pre_clear_handler () inline virtual
Virtual function called before performing clear; can be redefined in a derived class for customization. Please note: Although nodes and edges are deleted during graph::clear this is not achieved by calling graph::del_node and graph::del_edge, which is why the correspondig handler will not be called.
See Also
graph::clear
Reimplemented from graph.
Definition at line 66 of file graph_test.cpp.
View newest version in sPHENIX GitHub at line 66 of file graph_test.cpp
References graph::edges_begin(), graph::edges_end(), graph::nodes_begin(), graph::nodes_end(), PP, and XX.
void shower2::pre_clear_handler () inline virtual
Virtual function called before performing clear; can be redefined in a derived class for customization. Please note: Although nodes and edges are deleted during graph::clear this is not achieved by calling graph::del_node and graph::del_edge, which is why the correspondig handler will not be called.
See Also
graph::clear
Reimplemented from graph.
Definition at line 86 of file my_test2.cc.
View newest version in sPHENIX GitHub at line 86 of file my_test2.cc
References graph::edges_begin(), graph::edges_end(), and PP.
void shower2::pre_clear_handler () inline virtual
Virtual function called before performing clear; can be redefined in a derived class for customization. Please note: Although nodes and edges are deleted during graph::clear this is not achieved by calling graph::del_node and graph::del_edge, which is why the correspondig handler will not be called.
See Also
graph::clear
Reimplemented from graph.
Definition at line 134 of file my_test4.cc.
View newest version in sPHENIX GitHub at line 134 of file my_test4.cc
References graph::edges_begin(), graph::edges_end(), graph::nodes_begin(), graph::nodes_end(), PP, and XX.
void shower2::pre_clear_handler () inline virtual
Virtual function called before performing clear; can be redefined in a derived class for customization. Please note: Although nodes and edges are deleted during graph::clear this is not achieved by calling graph::del_node and graph::del_edge, which is why the correspondig handler will not be called.
See Also
graph::clear
Reimplemented from graph.
Definition at line 135 of file my_test3.cc.
View newest version in sPHENIX GitHub at line 135 of file my_test3.cc
References graph::edges_begin(), graph::edges_end(), graph::nodes_begin(), graph::nodes_end(), PP, and XX.
void shower2::save_edge_info_handler (ostream * , edge) const inline virtual
Called before the closing bracket of the list belonging to the key of edge e is written. This can be used to write information belonging to the edge e and thus should appear within the list associated with this edge.
Parameters
<code>os</code> output stream.
See Also
graph::save
Reimplemented from graph.
Definition at line 51 of file my_test4.cc.
View newest version in sPHENIX GitHub at line 51 of file my_test4.cc
References n, and PP.
void shower2::save_edge_info_handler (ostream * , edge) const inline virtual
Called before the closing bracket of the list belonging to the key of edge e is written. This can be used to write information belonging to the edge e and thus should appear within the list associated with this edge.
Parameters
<code>os</code> output stream.
See Also
graph::save
Reimplemented from graph.
Definition at line 52 of file my_test3.cc.
View newest version in sPHENIX GitHub at line 52 of file my_test3.cc
References n, and PP.
void shower2::save_edge_info_handler (ostream * , edge) const inline virtual
Called before the closing bracket of the list belonging to the key of edge e is written. This can be used to write information belonging to the edge e and thus should appear within the list associated with this edge.
Parameters
<code>os</code> output stream.
See Also
graph::save
Reimplemented from graph.
Definition at line 60 of file graph_test.cpp.
View newest version in sPHENIX GitHub at line 60 of file graph_test.cpp
References n, and PP.
void shower2::save_edge_info_handler (ostream * , edge) const inline virtual
Called before the closing bracket of the list belonging to the key of edge e is written. This can be used to write information belonging to the edge e and thus should appear within the list associated with this edge.
Parameters
<code>os</code> output stream.
See Also
graph::save
Reimplemented from graph.
Definition at line 80 of file my_test2.cc.
View newest version in sPHENIX GitHub at line 80 of file my_test2.cc
References n, and PP.
void shower2::save_node_info_handler (ostream * , node) const inline virtual
Called before the closing bracket of the list belonging to the key of node n is written. This can be used to write information belonging to the node n and thus should appear within the list associated with this node.
Parameters
<code>os</code> output stream.
See Also
graph::save
Reimplemented from graph.
Definition at line 50 of file my_test4.cc.
View newest version in sPHENIX GitHub at line 50 of file my_test4.cc
References n, and XX.
void shower2::save_node_info_handler (ostream * , node) const inline virtual
Called before the closing bracket of the list belonging to the key of node n is written. This can be used to write information belonging to the node n and thus should appear within the list associated with this node.
Parameters
<code>os</code> output stream.
See Also
graph::save
Reimplemented from graph.
Definition at line 51 of file my_test3.cc.
View newest version in sPHENIX GitHub at line 51 of file my_test3.cc
References n, and XX.
void shower2::save_node_info_handler (ostream * , node) const inline virtual
Called before the closing bracket of the list belonging to the key of node n is written. This can be used to write information belonging to the node n and thus should appear within the list associated with this node.
Parameters
<code>os</code> output stream.
See Also
graph::save
Reimplemented from graph.
Definition at line 59 of file graph_test.cpp.
View newest version in sPHENIX GitHub at line 59 of file graph_test.cpp
References n, and XX.
Member Data Documentation
edge_map< shared_ptr< parton > > shower2::PP private
Definition at line 116 of file graph_test.cpp.
View newest version in sPHENIX GitHub at line 116 of file graph_test.cpp
Referenced by GetEdgeValue(), GetFinal(), GetPartons(), load_edge_info_handler(), new_parton(), pre_clear_handler(), and save_edge_info_handler().
node_map<int> shower2::XX private
Definition at line 97 of file my_test2.cc.
View newest version in sPHENIX GitHub at line 97 of file my_test2.cc
node_map< shared_ptr< vertex > > shower2::XX private
Definition at line 115 of file graph_test.cpp.
View newest version in sPHENIX GitHub at line 115 of file graph_test.cpp
Referenced by GetNodeValue(), load_node_info_handler(), new_vertex(), pre_clear_handler(), and save_node_info_handler().
The documentation for this class was generated from the following files:
JETSCAPE/blob/main/external_packages/gtl/tests/graph_test.cpp
JETSCAPE/blob/main/external_packages/gtl/tests/my_test2.cc
JETSCAPE/blob/main/external_packages/gtl/tests/my_test3.cc
JETSCAPE/blob/main/external_packages/gtl/tests/my_test4.cc