Analysis Software: analysis/blob/master/dNdEta_Run2023/analysis_INTT/src/Tracklet.h File Reference
Tracklet.h File Reference
#include <TTree.h>
#include "GenHadron.h"
#include "Hit.h"
#include "Utilities.h"
Classes
class Tracklet
class TrackletData
Functions
void SetMinitree (TTree *outTree, TrackletData &tkldata)
void ResetVec (TrackletData &tkldata)
bool compare_dR (Tracklet *a, Tracklet *b)
void ProtoTracklets (TrackletData &tkldata, float cutdr)
void RecoTracklets (TrackletData &tkldata)
void GenMatch_Recotkl (TrackletData &tkldata)
Function Documentation
bool compare_dR (Tracklet * a, Tracklet * b)
Definition at line 210 of file Tracklet.h.
View newest version in sPHENIX GitHub at line 210 of file Tracklet.h
References Tracklet::dR().
Referenced by RecoTracklets().
void GenMatch_Recotkl (TrackletData & tkldata)
Definition at line 277 of file Tracklet.h.
View newest version in sPHENIX GitHub at line 277 of file Tracklet.h
References physmon_track_finding_ttbar::deltaR, TrackletData::GenHadron_matched_E, TrackletData::GenHadron_matched_eta, TrackletData::GenHadron_matched_phi, TrackletData::GenHadron_matched_Pt, TrackletData::GenHadrons, TrackletData::NRecotkl_GenMatched, TrackletData::recotklgm_deta, TrackletData::recotklgm_dphi, TrackletData::recotklgm_dR, TrackletData::recotklgm_eta, TrackletData::recotklgm_phi, TrackletData::RecoTkls, and TrackletData::RecoTkls_GenMatched.
Referenced by main().
void ProtoTracklets (TrackletData & tkldata, float cutdr)
Definition at line 212 of file Tracklet.h.
View newest version in sPHENIX GitHub at line 212 of file Tracklet.h
References deltaPhi(), Tracklet::dEta(), Tracklet::dPhi(), Tracklet::dR(), dR(), Hit::Eta(), Tracklet::Hit1(), TrackletData::layers, TrackletData::NPrototkl, Hit::Phi(), TrackletData::prototkl_deta, TrackletData::prototkl_dphi, TrackletData::prototkl_dR, TrackletData::prototkl_eta, TrackletData::prototkl_phi, and TrackletData::ProtoTkls.
Referenced by main().
void RecoTracklets (TrackletData & tkldata)
Definition at line 249 of file Tracklet.h.
View newest version in sPHENIX GitHub at line 249 of file Tracklet.h
References compare_dR(), TrackletData::NRecotkl_Raw, TrackletData::ProtoTkls, TrackletData::recotklraw_deta, TrackletData::recotklraw_dphi, TrackletData::recotklraw_dR, TrackletData::recotklraw_eta, TrackletData::recotklraw_phi, TrackletData::RecoTkls, and Acts::Experimental::detail::BlueprintHelper::sort().
Referenced by main().
void ResetVec (TrackletData & tkldata)
Definition at line 176 of file Tracklet.h.
View newest version in sPHENIX GitHub at line 176 of file Tracklet.h
References CleanVec(), TrackletData::GenHadron_E, TrackletData::GenHadron_eta, TrackletData::GenHadron_matched_E, TrackletData::GenHadron_matched_eta, TrackletData::GenHadron_matched_phi, TrackletData::GenHadron_matched_Pt, TrackletData::GenHadron_phi, TrackletData::GenHadron_Pt, TrackletData::GenHadrons, i, TrackletData::layers, TrackletData::prototkl_deta, TrackletData::prototkl_dphi, TrackletData::prototkl_dR, TrackletData::prototkl_eta, TrackletData::prototkl_phi, TrackletData::ProtoTkls, TrackletData::recotklgm_deta, TrackletData::recotklgm_dphi, TrackletData::recotklgm_dR, TrackletData::recotklgm_eta, TrackletData::recotklgm_phi, TrackletData::recotklraw_deta, TrackletData::recotklraw_dphi, TrackletData::recotklraw_dR, TrackletData::recotklraw_eta, TrackletData::recotklraw_phi, and TrackletData::RecoTkls.
Referenced by main().
void SetMinitree (TTree * outTree, TrackletData & tkldata)
Definition at line 125 of file Tracklet.h.
View newest version in sPHENIX GitHub at line 125 of file Tracklet.h
References TrackletData::Centrality_mbd, TrackletData::Centrality_mbdquantity, TrackletData::cluseta, TrackletData::clusphi, TrackletData::clusphisize, TrackletData::cluszsize, TrackletData::event, TrackletData::GenHadron_E, TrackletData::GenHadron_eta, TrackletData::GenHadron_matched_E, TrackletData::GenHadron_matched_eta, TrackletData::GenHadron_matched_phi, TrackletData::GenHadron_matched_Pt, TrackletData::GenHadron_phi, TrackletData::GenHadron_Pt, TrackletData::isdata, TrackletData::NClusLayer1, TrackletData::NPrototkl, TrackletData::NRecotkl_GenMatched, TrackletData::NRecotkl_Raw, TrackletData::process, TrackletData::prototkl_deta, TrackletData::prototkl_dphi, TrackletData::prototkl_dR, TrackletData::prototkl_eta, TrackletData::prototkl_phi, TrackletData::pu0_sel, TrackletData::PV_x, TrackletData::PV_y, TrackletData::PV_z, TrackletData::recotklgm_deta, TrackletData::recotklgm_dphi, TrackletData::recotklgm_dR, TrackletData::recotklgm_eta, TrackletData::recotklgm_phi, TrackletData::recotklraw_deta, TrackletData::recotklraw_dphi, TrackletData::recotklraw_dR, TrackletData::recotklraw_eta, TrackletData::recotklraw_phi, TrackletData::trig, TrackletData::TruthPV_x, TrackletData::TruthPV_y, and TrackletData::TruthPV_z.
Referenced by main().