Analysis Software: ActsExamples::HepMC3Particle Struct Reference
ActsExamples::HepMC3Particle Struct Reference
Helper struct to convert HepMC3 particles to internal format.
#include <acts/blob/sPHENIX/Examples/Io/HepMC3/include/ActsExamples/Plugins/HepMC3/HepMC3Particle.hpp>
Public Member Functions
std::unique_ptr< SimParticle > particle (const std::shared_ptr< HepMC3::GenParticle > particle)
Returns the particle translated into Acts.
int id (const std::shared_ptr< HepMC3::GenParticle > particle)
Returns the id of the particle translated into Acts.
std::unique_ptr< SimVertex > productionVertex (const std::shared_ptr< HepMC3::GenParticle > particle)
Returns the production vertex of the particle translated into Acts.
std::unique_ptr< SimVertex > endVertex (const std::shared_ptr< HepMC3::GenParticle > particle)
Returns the end vertex of the particle translated into Acts.
int pdgID (const std::shared_ptr< HepMC3::GenParticle > particle)
Returns the PDG code of a particle translated into Acts.
Acts::Vector3D momentum (const std::shared_ptr< HepMC3::GenParticle > particle)
Returns the momentum of a particle translated into Acts.
double energy (const std::shared_ptr< HepMC3::GenParticle > particle)
Returns the energy of a particle translated into Acts.
double mass (const std::shared_ptr< HepMC3::GenParticle > particle)
Returns the mass of a particle translated into Acts.
double charge (const std::shared_ptr< HepMC3::GenParticle > particle)
Returns the charge of a particle translated into Acts.
void pdgID (std::shared_ptr< HepMC3::GenParticle > particle, const int pid)
Sets the PDG code of a particle translated from Acts.
void momentum (std::shared_ptr< HepMC3::GenParticle > particle, const Acts::Vector3D &mom)
Sets the momentum of a particle translated from Acts.
void energy (std::shared_ptr< HepMC3::GenParticle > particle, const double energy)
Sets the energy of a particle translated from Acts.
void mass (std::shared_ptr< HepMC3::GenParticle > particle, const double mass)
Sets the mass of a particle translated from Acts.
Detailed Description
Helper struct to convert HepMC3 particles to internal format.
Definition at line 22 of file HepMC3Particle.hpp.
View newest version in sPHENIX GitHub at line 22 of file HepMC3Particle.hpp
Member Function Documentation
double ActsExamples::HepMC3Particle::charge (const std::shared_ptr< HepMC3::GenParticle > particle)
Returns the charge of a particle translated into Acts.
Parameters
particle HepMC3::GenParticle particle
Returns
charge of the particle
Definition at line 82 of file HepMC3Particle.cpp.
View newest version in sPHENIX GitHub at line 82 of file HepMC3Particle.cpp
References charge.
std::unique_ptr< ActsExamples::SimVertex > ActsExamples::HepMC3Particle::endVertex (const std::shared_ptr< HepMC3::GenParticle > particle)
Returns the end vertex of the particle translated into Acts.
Parameters
particle HepMC3::GenParticle particle
Returns
end vertex of the particle
Definition at line 46 of file HepMC3Particle.cpp.
View newest version in sPHENIX GitHub at line 46 of file HepMC3Particle.cpp
References ActsExamples::HepMC3Vertex::processVertex().
double ActsExamples::HepMC3Particle::energy (const std::shared_ptr< HepMC3::GenParticle > particle)
Returns the energy of a particle translated into Acts.
Parameters
particle HepMC3::GenParticle particle
Returns
energy of the particle
Definition at line 72 of file HepMC3Particle.cpp.
View newest version in sPHENIX GitHub at line 72 of file HepMC3Particle.cpp
void ActsExamples::HepMC3Particle::energy (std::shared_ptr< HepMC3::GenParticle > particle, const double energy)
Sets the energy of a particle translated from Acts.
Parameters
particle HepMC3::GenParticle particle
energy energy that will be set
Definition at line 98 of file HepMC3Particle.cpp.
View newest version in sPHENIX GitHub at line 98 of file HepMC3Particle.cpp
References energy.
int ActsExamples::HepMC3Particle::id (const std::shared_ptr< HepMC3::GenParticle > particle)
Returns the id of the particle translated into Acts.
Parameters
particle HepMC3::GenParticle particle
Returns
id of the particle
Definition at line 27 of file HepMC3Particle.cpp.
View newest version in sPHENIX GitHub at line 27 of file HepMC3Particle.cpp
double ActsExamples::HepMC3Particle::mass (const std::shared_ptr< HepMC3::GenParticle > particle)
Returns the mass of a particle translated into Acts.
Parameters
particle HepMC3::GenParticle particle
Returns
mass of the particle
Definition at line 77 of file HepMC3Particle.cpp.
View newest version in sPHENIX GitHub at line 77 of file HepMC3Particle.cpp
void ActsExamples::HepMC3Particle::mass (std::shared_ptr< HepMC3::GenParticle > particle, const double mass)
Sets the mass of a particle translated from Acts.
Parameters
particle HepMC3::GenParticle particle
mass mass that will be set
Definition at line 105 of file HepMC3Particle.cpp.
View newest version in sPHENIX GitHub at line 105 of file HepMC3Particle.cpp
Acts::Vector3D ActsExamples::HepMC3Particle::momentum (const std::shared_ptr< HepMC3::GenParticle > particle)
Returns the momentum of a particle translated into Acts.
Parameters
particle HepMC3::GenParticle particle
Returns
momentum of the particle
Definition at line 63 of file HepMC3Particle.cpp.
View newest version in sPHENIX GitHub at line 63 of file HepMC3Particle.cpp
void ActsExamples::HepMC3Particle::momentum (std::shared_ptr< HepMC3::GenParticle > particle, const Acts::Vector3D & mom)
Sets the momentum of a particle translated from Acts.
Parameters
particle HepMC3::GenParticle particle
mom momentum that will be set
Definition at line 92 of file HepMC3Particle.cpp.
View newest version in sPHENIX GitHub at line 92 of file HepMC3Particle.cpp
std::unique_ptr< ActsExamples::SimParticle > ActsExamples::HepMC3Particle::particle (const std::shared_ptr< HepMC3::GenParticle > particle)
Returns the particle translated into Acts.
Parameters
particle HepMC3::GenParticle particle
Returns
corresponding Acts particle
Definition at line 14 of file HepMC3Particle.cpp.
View newest version in sPHENIX GitHub at line 14 of file HepMC3Particle.cpp
References charge, testing::internal::move(), ActsFatras::Particle::setAbsMomentum(), ActsFatras::Particle::setDirection(), and ActsFatras::Barcode::setParticle().
Referenced by ActsExamples::HepMC3Event::beams(), ActsExamples::HepMC3Event::finalState(), ActsExamples::HepMC3Vertex::genParticlesToActs(), and ActsExamples::HepMC3Event::particles().
int ActsExamples::HepMC3Particle::pdgID (const std::shared_ptr< HepMC3::GenParticle > particle)
Returns the PDG code of a particle translated into Acts.
Parameters
particle HepMC3::GenParticle particle
Returns
PDG code of the particle
Definition at line 58 of file HepMC3Particle.cpp.
View newest version in sPHENIX GitHub at line 58 of file HepMC3Particle.cpp
void ActsExamples::HepMC3Particle::pdgID (std::shared_ptr< HepMC3::GenParticle > particle, const int pid)
Sets the PDG code of a particle translated from Acts.
Parameters
particle HepMC3::GenParticle particle
pid PDG code that will be set
Definition at line 87 of file HepMC3Particle.cpp.
View newest version in sPHENIX GitHub at line 87 of file HepMC3Particle.cpp
std::unique_ptr< ActsExamples::SimVertex > ActsExamples::HepMC3Particle::productionVertex (const std::shared_ptr< HepMC3::GenParticle > particle)
Returns the production vertex of the particle translated into Acts.
Parameters
particle HepMC3::GenParticle particle
Returns
production vertex of the particle
Definition at line 33 of file HepMC3Particle.cpp.
View newest version in sPHENIX GitHub at line 33 of file HepMC3Particle.cpp
References ActsExamples::HepMC3Vertex::processVertex().
The documentation for this struct was generated from the following files:
acts/blob/sPHENIX/Examples/Io/HepMC3/include/ActsExamples/Plugins/HepMC3/HepMC3Particle.hpp
acts/blob/sPHENIX/Examples/Io/HepMC3/src/HepMC3Particle.cpp