Analysis Software: PHTpcTrackFollower Class Reference
PHTpcTrackFollower Class Reference
#include <coresoftware/blob/master/offline/packages/PHTpcTracker/PHTpcTrackFollower.h>
Public Member Functions
PHTpcTrackFollower ()
virtual ~PHTpcTrackFollower ()
std::vector< PHGenFit2::Track * > followTracks (std::vector< kdfinder::TrackCandidate< double > * > &candidates, PHField *B, PHTpcLookup *lookup, PHGenFit2::Fitter *fitter)
PHGenFit2::Track * propagateTrack (kdfinder::TrackCandidate< double > *candidate, PHTpcLookup *lookup, PHGenFit2::Fitter *fitter)
void set_optimization_helix (bool opt=true)
void set_optimization_precise_fit (bool opt=true)
Protected Member Functions
PHGenFit2::Track * candidate_to_genfit (kdfinder::TrackCandidate< double > *candidate)
PHGenFit::SpacepointMeasurement2 * hit_to_measurement (std::vector< double > &hit)
int get_track_layer (PHGenFit2::Track *track, int dir=1)
int get_track_layer (genfit::Track *gftrack, int dir=1)
std::pair
< genfit::MeasuredStateOnPlane
*, double > get_projected_coordinate (genfit::Track *gftrack, int dir, double radius)
std::pair
< genfit::MeasuredStateOnPlane
*, double > get_projected_coordinate (genfit::Track *gftrack, int dir, const TVector3 &point)
int followTrack (PHGenFit2::Track *track, PHTpcLookup *lookup, PHGenFit2::Fitter *fitter, int dir=1)
Private Attributes
bool mOptHelix
bool mOptPreciseFit
Detailed Description
Definition at line 49 of file PHTpcTrackFollower.h.
View newest version in sPHENIX GitHub at line 49 of file PHTpcTrackFollower.h
Constructor & Destructor Documentation
PHTpcTrackFollower::PHTpcTrackFollower ()
Definition at line 54 of file PHTpcTrackFollower.cc.
View newest version in sPHENIX GitHub at line 54 of file PHTpcTrackFollower.cc
virtual PHTpcTrackFollower::~PHTpcTrackFollower () inline virtual
Definition at line 53 of file PHTpcTrackFollower.h.
View newest version in sPHENIX GitHub at line 53 of file PHTpcTrackFollower.h
Member Function Documentation
PHGenFit2::Track * PHTpcTrackFollower::candidate_to_genfit (kdfinder::TrackCandidate< double > * candidate) protected
Definition at line 297 of file PHTpcTrackFollower.cc.
View newest version in sPHENIX GitHub at line 297 of file PHTpcTrackFollower.cc
References PHGenFit2::Track::addMeasurements(), kdfinder::TrackCandidate< T >::getHit(), kdfinder::TrackCandidate< T >::getMomForHit(), kdfinder::TrackCandidate< T >::getPosForHit(), hit_to_measurement(), i, kdfinder::TrackCandidate< T >::nhits(), and kdfinder::TrackCandidate< T >::sign().
Referenced by propagateTrack().
int PHTpcTrackFollower::followTrack (PHGenFit2::Track * track, PHTpcLookup * lookup, PHGenFit2::Fitter * fitter, int dir = 1) protected
Definition at line 523 of file PHTpcTrackFollower.cc.
View newest version in sPHENIX GitHub at line 523 of file PHTpcTrackFollower.cc
References PHGenFit2::Track::addMeasurement(), centrality::dist(), PHTpcLookup::find(), get_projected_coordinate(), get_track_layer(), PHGenFit2::Track::getGenFitTrack(), hit_to_measurement(), i, layer, LOG_DEBUG, LOG_DEBUG_IF, LOG_ERROR, max, p, Acts::Test::pos, PHGenFit2::Fitter::processTrackPartially(), PHTpcConst::TPC_LAYERS_DELTAR, PHTpcConst::TPC_LAYERS_MAX, and PHTpcConst::TPC_LAYERS_RADIUS.
Referenced by propagateTrack().
std::vector< PHGenFit2::Track * > PHTpcTrackFollower::followTracks (std::vector< kdfinder::TrackCandidate< double > * > & candidates, PHField * B, PHTpcLookup * lookup, PHGenFit2::Fitter * fitter)
Definition at line 60 of file PHTpcTrackFollower.cc.
View newest version in sPHENIX GitHub at line 60 of file PHTpcTrackFollower.cc
References KFPMath::a, KFPMath::b, PHGenFit2::Track::get_cluster_keys(), genfit::FitStatus::getChi2(), PHGenFit2::Track::getGenFitTrack(), genfit::Track::getKalmanFitStatus(), genfit::FitStatus::getNdf(), genfit::FitStatus::getNFailedPoints(), genfit::Track::getNumPoints(), i, it, j, LOG_DEBUG, kdfinder::TrackCandidate< T >::nhits(), and propagateTrack().
Referenced by PHTpcTracker::Process().
std::pair< genfit::MeasuredStateOnPlane *, double > PHTpcTrackFollower::get_projected_coordinate (genfit::Track * gftrack, int dir, double radius) protected
Definition at line 402 of file PHTpcTrackFollower.cc.
View newest version in sPHENIX GitHub at line 402 of file PHTpcTrackFollower.cc
References Acts::IntegrationTest::Bz, charge, genfit::MeasuredStateOnPlane::clone(), genfit::StateOnPlane::extrapolateToCylinder(), genfit::StateOnPlane::getCharge(), genfit::FieldManager::getFieldVal(), genfit::KalmanFitterInfo::getFittedState(), genfit::FieldManager::getInstance(), genfit::TrackPoint::getKalmanFitterInfo(), genfit::Track::getPointWithMeasurementAndFitterInfo(), genfit::StateOnPlane::getPosMom(), Acts::UnitConstants::h, LOG_DEBUG, mOptHelix, Acts::Test::pos, Acts::UnitConstants::s, and kdfinder::Helix< T >::second.
Referenced by followTrack().
std::pair< genfit::MeasuredStateOnPlane *, double > PHTpcTrackFollower::get_projected_coordinate (genfit::Track * gftrack, int dir, const TVector3 & point) protected
Definition at line 486 of file PHTpcTrackFollower.cc.
View newest version in sPHENIX GitHub at line 486 of file PHTpcTrackFollower.cc
References genfit::MeasuredStateOnPlane::clone(), genfit::StateOnPlane::extrapolateToPoint(), genfit::KalmanFitterInfo::getFittedState(), genfit::TrackPoint::getKalmanFitterInfo(), genfit::Track::getPointWithMeasurementAndFitterInfo(), and LOG_DEBUG.
int PHTpcTrackFollower::get_track_layer (PHGenFit2::Track * track, int dir = 1) protected
Definition at line 343 of file PHTpcTrackFollower.cc.
View newest version in sPHENIX GitHub at line 343 of file PHTpcTrackFollower.cc
References PHGenFit2::Track::getGenFitTrack().
Referenced by followTrack().
int PHTpcTrackFollower::get_track_layer (genfit::Track * gftrack, int dir = 1) protected
Definition at line 348 of file PHTpcTrackFollower.cc.
View newest version in sPHENIX GitHub at line 348 of file PHTpcTrackFollower.cc
References genfit::KalmanFitterInfo::getFittedState(), genfit::TrackPoint::getKalmanFitterInfo(), genfit::StateOnPlane::getMom(), genfit::Track::getNumPoints(), genfit::Track::getPointWithMeasurementAndFitterInfo(), genfit::StateOnPlane::getPos(), genfit::Track::hasKalmanFitStatus(), i, layer, LOG_DEBUG, LOG_ERROR, Acts::Test::pos, PHTpcConst::TPC_LAYERS_DELTAR, PHTpcConst::TPC_LAYERS_MAX, and PHTpcConst::TPC_LAYERS_RADIUS.
PHGenFit::SpacepointMeasurement2 * PHTpcTrackFollower::hit_to_measurement (std::vector< double > & hit) protected
Definition at line 334 of file PHTpcTrackFollower.cc.
View newest version in sPHENIX GitHub at line 334 of file PHTpcTrackFollower.cc
References Acts::Test::pos, and PHGenFit::Measurement::set_cluster_key().
Referenced by candidate_to_genfit(), and followTrack().
PHGenFit2::Track * PHTpcTrackFollower::propagateTrack (kdfinder::TrackCandidate< double > * candidate, PHTpcLookup * lookup, PHGenFit2::Fitter * fitter)
Definition at line 151 of file PHTpcTrackFollower.cc.
View newest version in sPHENIX GitHub at line 151 of file PHTpcTrackFollower.cc
References candidate_to_genfit(), genfit::Track::checkConsistency(), followTrack(), genfit::FitStatus::getChi2(), PHGenFit2::Track::getGenFitTrack(), kdfinder::TrackCandidate< T >::getHits(), genfit::Track::getKalmanFitStatus(), kdfinder::TrackCandidate< T >::getMomForHit(), genfit::FitStatus::getNdf(), genfit::FitStatus::getNFailedPoints(), genfit::Track::getNumPoints(), kdfinder::TrackCandidate< T >::getPosForHit(), genfit::Track::hasFitStatus(), LOG_DEBUG, kdfinder::TrackCandidate< T >::momentum(), mOptPreciseFit, PHGenFit2::Fitter::processTrack1(), PHGenFit2::Fitter::processTrack5(), and PHTpcConst::TPC_LAYERS_MAX.
Referenced by followTracks().
void PHTpcTrackFollower::set_optimization_helix (bool opt = true) inline
Definition at line 61 of file PHTpcTrackFollower.h.
View newest version in sPHENIX GitHub at line 61 of file PHTpcTrackFollower.h
References mOptHelix.
Referenced by PHTpcTracker::set_track_follower_optimization_helix().
void PHTpcTrackFollower::set_optimization_precise_fit (bool opt = true) inline
Definition at line 62 of file PHTpcTrackFollower.h.
View newest version in sPHENIX GitHub at line 62 of file PHTpcTrackFollower.h
References mOptPreciseFit.
Referenced by PHTpcTracker::set_track_follower_optimization_precise_fit().
Member Data Documentation
bool PHTpcTrackFollower::mOptHelix private
Definition at line 74 of file PHTpcTrackFollower.h.
View newest version in sPHENIX GitHub at line 74 of file PHTpcTrackFollower.h
Referenced by get_projected_coordinate(), and set_optimization_helix().
bool PHTpcTrackFollower::mOptPreciseFit private
Definition at line 75 of file PHTpcTrackFollower.h.
View newest version in sPHENIX GitHub at line 75 of file PHTpcTrackFollower.h
Referenced by propagateTrack(), and set_optimization_precise_fit().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/PHTpcTracker/PHTpcTrackFollower.h
coresoftware/blob/master/offline/packages/PHTpcTracker/PHTpcTrackFollower.cc