Analysis Software: Acts::detail::grid_helper_impl< 0u > Struct Template Reference
Acts::detail::grid_helper_impl< 0u > Struct Template Reference
#include <acts/blob/sPHENIX/Core/include/Acts/Utilities/detail/grid_helper.hpp>
Static Public Member Functions
template<class... Axes>
static void getBinCenter (std::array< ActsScalar, sizeof...(Axes)> &center, const std::array< size_t, sizeof...(Axes)> &localIndices, const std::tuple< Axes...> &axes)
template<class... Axes>
static void getGlobalBin (const std::array< size_t, sizeof...(Axes)> &localBins, const std::tuple< Axes...> &, size_t &bin, size_t &area)
template<class Point , class... Axes>
static void getLocalBinIndices (const Point &point, const std::tuple< Axes...> &axes, std::array< size_t, sizeof...(Axes)> &indices)
template<class... Axes>
static void getLocalBinIndices (size_t &bin, const std::tuple< Axes...> &, size_t &area, std::array< size_t, sizeof...(Axes)> &indices)
template<class... Axes>
static void getLowerLeftBinEdge (std::array< ActsScalar, sizeof...(Axes)> &llEdge, const std::array< size_t, sizeof...(Axes)> &localIndices, const std::tuple< Axes...> &axes)
template<class... Axes>
static void getLowerLeftBinIndices (std::array< size_t, sizeof...(Axes)> &localIndices, const std::tuple< Axes...> &axes)
template<class... Axes>
static void getNBins (const std::tuple< Axes...> &axes, std::array< size_t, sizeof...(Axes)> &nBinsArray)
template<class... Axes>
static void getAxes (const std::tuple< Axes...> &axes, std::array< const IAxis *, sizeof...(Axes)> &axesArr)
template<class... Axes>
static void getUpperRightBinEdge (std::array< ActsScalar, sizeof...(Axes)> &urEdge, const std::array< size_t, sizeof...(Axes)> &localIndices, const std::tuple< Axes...> &axes)
template<class... Axes>
static void getUpperRightBinIndices (std::array< size_t, sizeof...(Axes)> &localIndices, const std::tuple< Axes...> &axes)
template<class... Axes>
static void getMin (const std::tuple< Axes...> &axes, std::array< ActsScalar, sizeof...(Axes)> &minArray)
template<class... Axes>
static void getMax (const std::tuple< Axes...> &axes, std::array< ActsScalar, sizeof...(Axes)> &maxArray)
template<class... Axes>
static void getWidth (const std::tuple< Axes...> &axes, std::array< ActsScalar, sizeof...(Axes)> &widthArray)
template<class Point , class... Axes>
static bool isInside (const Point &position, const std::tuple< Axes...> &axes)
template<class... Axes>
static void neighborHoodIndices (const std::array< size_t, sizeof...(Axes)> &localIndices, std::pair< int, int > sizes, const std::tuple< Axes...> &axes, std::array< NeighborHoodIndices, sizeof...(Axes)> &neighborIndices)
template<class... Axes>
static void neighborHoodIndices (const std::array< size_t, sizeof...(Axes)> &localIndices, std::array< std::pair< int, int >, sizeof...(Axes)> sizes, const std::tuple< Axes...> &axes, std::array< NeighborHoodIndices, sizeof...(Axes)> &neighborIndices)
template<class... Axes>
static void exteriorBinIndices (std::array< size_t, sizeof...(Axes)> &idx, std::array< bool, sizeof...(Axes)> isExterior, std::set< size_t > &combinations, const std::tuple< Axes...> &axes)
Detailed Description
template<>
struct Acts::detail::grid_helper_impl< 0u >
Definition at line 332 of file grid_helper.hpp.
View newest version in sPHENIX GitHub at line 332 of file grid_helper.hpp
Member Function Documentation
template<class... Axes> static void Acts::detail::grid_helper_impl< 0u >::exteriorBinIndices (std::array< size_t, sizeof...(Axes)> & idx, std::array< bool, sizeof...(Axes)> isExterior, std::set< size_t > & combinations, const std::tuple< Axes...> & axes) inline static
Definition at line 458 of file grid_helper.hpp.
View newest version in sPHENIX GitHub at line 458 of file grid_helper.hpp
References Acts::detail::grid_helper_impl< N >::getGlobalBin(), Acts::detail::grid_helper_impl< N >::getNBins(), i, ambiguity_solver_full_chain::idx, N, and physmon_ckf_tracking::u.
template<class... Axes> static void Acts::detail::grid_helper_impl< 0u >::getAxes (const std::tuple< Axes...> & axes, std::array< const IAxis *, sizeof...(Axes)> & axesArr) inline static
Definition at line 389 of file grid_helper.hpp.
View newest version in sPHENIX GitHub at line 389 of file grid_helper.hpp
References physmon_ckf_tracking::u.
template<class... Axes> static void Acts::detail::grid_helper_impl< 0u >::getBinCenter (std::array< ActsScalar, sizeof...(Axes)> & center, const std::array< size_t, sizeof...(Axes)> & localIndices, const std::tuple< Axes...> & axes) inline static
Definition at line 334 of file grid_helper.hpp.
View newest version in sPHENIX GitHub at line 334 of file grid_helper.hpp
References Acts::detail::grid_helper_impl< N >::getBinCenter(), Acts::Experimental::detail::localIndices(), and physmon_ckf_tracking::u.
template<class... Axes> static void Acts::detail::grid_helper_impl< 0u >::getGlobalBin (const std::array< size_t, sizeof...(Axes)> & localBins, const std::tuple< Axes...> & , size_t & bin, size_t & area) inline static
Definition at line 342 of file grid_helper.hpp.
View newest version in sPHENIX GitHub at line 342 of file grid_helper.hpp
References physmon_ckf_tracking::u.
template<class Point , class... Axes> static void Acts::detail::grid_helper_impl< 0u >::getLocalBinIndices (const Point & point, const std::tuple< Axes...> & axes, std::array< size_t, sizeof...(Axes)> & indices) inline static
Definition at line 349 of file grid_helper.hpp.
View newest version in sPHENIX GitHub at line 349 of file grid_helper.hpp
References physmon_ckf_tracking::u.
template<class... Axes> static void Acts::detail::grid_helper_impl< 0u >::getLocalBinIndices (size_t & bin, const std::tuple< Axes...> & , size_t & area, std::array< size_t, sizeof...(Axes)> & indices) inline static
Definition at line 357 of file grid_helper.hpp.
View newest version in sPHENIX GitHub at line 357 of file grid_helper.hpp
References physmon_ckf_tracking::u.
template<class... Axes> static void Acts::detail::grid_helper_impl< 0u >::getLowerLeftBinEdge (std::array< ActsScalar, sizeof...(Axes)> & llEdge, const std::array< size_t, sizeof...(Axes)> & localIndices, const std::tuple< Axes...> & axes) inline static
Definition at line 367 of file grid_helper.hpp.
View newest version in sPHENIX GitHub at line 367 of file grid_helper.hpp
References Acts::Experimental::detail::localIndices(), and physmon_ckf_tracking::u.
template<class... Axes> static void Acts::detail::grid_helper_impl< 0u >::getLowerLeftBinIndices (std::array< size_t, sizeof...(Axes)> & localIndices, const std::tuple< Axes...> & axes) inline static
Definition at line 375 of file grid_helper.hpp.
View newest version in sPHENIX GitHub at line 375 of file grid_helper.hpp
References Acts::Experimental::detail::localIndices(), and physmon_ckf_tracking::u.
template<class... Axes> static void Acts::detail::grid_helper_impl< 0u >::getMax (const std::tuple< Axes...> & axes, std::array< ActsScalar, sizeof...(Axes)> & maxArray) inline static
Definition at line 416 of file grid_helper.hpp.
View newest version in sPHENIX GitHub at line 416 of file grid_helper.hpp
References Acts::detail::grid_helper_impl< N >::getMax(), and physmon_ckf_tracking::u.
template<class... Axes> static void Acts::detail::grid_helper_impl< 0u >::getMin (const std::tuple< Axes...> & axes, std::array< ActsScalar, sizeof...(Axes)> & minArray) inline static
Definition at line 410 of file grid_helper.hpp.
View newest version in sPHENIX GitHub at line 410 of file grid_helper.hpp
References Acts::detail::grid_helper_impl< N >::getMin(), and physmon_ckf_tracking::u.
template<class... Axes> static void Acts::detail::grid_helper_impl< 0u >::getNBins (const std::tuple< Axes...> & axes, std::array< size_t, sizeof...(Axes)> & nBinsArray) inline static
Definition at line 382 of file grid_helper.hpp.
View newest version in sPHENIX GitHub at line 382 of file grid_helper.hpp
References Acts::detail::grid_helper_impl< N >::getNBins(), and physmon_ckf_tracking::u.
template<class... Axes> static void Acts::detail::grid_helper_impl< 0u >::getUpperRightBinEdge (std::array< ActsScalar, sizeof...(Axes)> & urEdge, const std::array< size_t, sizeof...(Axes)> & localIndices, const std::tuple< Axes...> & axes) inline static
Definition at line 395 of file grid_helper.hpp.
View newest version in sPHENIX GitHub at line 395 of file grid_helper.hpp
References Acts::Experimental::detail::localIndices(), and physmon_ckf_tracking::u.
template<class... Axes> static void Acts::detail::grid_helper_impl< 0u >::getUpperRightBinIndices (std::array< size_t, sizeof...(Axes)> & localIndices, const std::tuple< Axes...> & axes) inline static
Definition at line 403 of file grid_helper.hpp.
View newest version in sPHENIX GitHub at line 403 of file grid_helper.hpp
References Acts::Experimental::detail::localIndices(), and physmon_ckf_tracking::u.
template<class... Axes> static void Acts::detail::grid_helper_impl< 0u >::getWidth (const std::tuple< Axes...> & axes, std::array< ActsScalar, sizeof...(Axes)> & widthArray) inline static
Definition at line 422 of file grid_helper.hpp.
View newest version in sPHENIX GitHub at line 422 of file grid_helper.hpp
References physmon_ckf_tracking::u.
template<class Point , class... Axes> static bool Acts::detail::grid_helper_impl< 0u >::isInside (const Point & position, const std::tuple< Axes...> & axes) inline static
Definition at line 428 of file grid_helper.hpp.
View newest version in sPHENIX GitHub at line 428 of file grid_helper.hpp
References Acts::detail::grid_helper_impl< N >::isInside(), and physmon_ckf_tracking::u.
template<class... Axes> static void Acts::detail::grid_helper_impl< 0u >::neighborHoodIndices (const std::array< size_t, sizeof...(Axes)> & localIndices, std::pair< int, int > sizes, const std::tuple< Axes...> & axes, std::array< NeighborHoodIndices, sizeof...(Axes)> & neighborIndices) inline static
Definition at line 433 of file grid_helper.hpp.
View newest version in sPHENIX GitHub at line 433 of file grid_helper.hpp
References Acts::Experimental::detail::localIndices(), Acts::detail::grid_helper_impl< N >::neighborHoodIndices(), and physmon_ckf_tracking::u.
template<class... Axes> static void Acts::detail::grid_helper_impl< 0u >::neighborHoodIndices (const std::array< size_t, sizeof...(Axes)> & localIndices, std::array< std::pair< int, int >, sizeof...(Axes)> sizes, const std::tuple< Axes...> & axes, std::array< NeighborHoodIndices, sizeof...(Axes)> & neighborIndices) inline static
Definition at line 445 of file grid_helper.hpp.
View newest version in sPHENIX GitHub at line 445 of file grid_helper.hpp
References Acts::Experimental::detail::localIndices(), Acts::detail::grid_helper_impl< N >::neighborHoodIndices(), and physmon_ckf_tracking::u.
The documentation for this struct was generated from the following file:
acts/blob/sPHENIX/Core/include/Acts/Utilities/detail/grid_helper.hpp