Analysis Software: TrkrHitv2 Class Reference
TrkrHitv2 Class Reference
Base class for hit object.
#include <coresoftware/blob/master/offline/packages/trackbase/TrkrHitv2.h>
Public Member Functions
TrkrHitv2 ()
ctor
~TrkrHitv2 () override
dtor
void identify (std::ostream &os=std::cout) const override
void Reset () override
Clear Event.
int isValid () const override
isValid returns non zero if object contains vailid data
void addEnergy (const double edep) override
double getEnergy () override
void setAdc (const unsigned int adc) override
unsigned int getAdc () override
Public Member Functions inherited from TrkrHit
~TrkrHit () override
dtor
Public Member Functions inherited from PHObject
PHObject ()
ctor
~PHObject () override
dtor
virtual PHObject * CloneMe () const
Virtual copy constructor.
virtual PHObject * clone () const final
PHObject * Clone (const char *newname="") const final
void Copy (TObject &object) const final
virtual int Integrate () const
virtual int Integrate (PHObject *)
virtual void CopyFrom (const PHObject *obj)
Protected Member Functions
ClassDefOverride (TrkrHitv2, 1)
Protected Member Functions inherited from TrkrHit
ClassDefOverride (TrkrHit, 1)
Protected Attributes
unsigned short m_adc = 0
Detailed Description
Base class for hit object.
This is the empyt virtual base class for a hit object. Each subsystem should implement an inherited version which contains the actual storage information.
Definition at line 24 of file TrkrHitv2.h.
View newest version in sPHENIX GitHub at line 24 of file TrkrHitv2.h
Constructor & Destructor Documentation
TrkrHitv2::TrkrHitv2 ()
ctor
Definition at line 4 of file TrkrHitv2.cc.
View newest version in sPHENIX GitHub at line 4 of file TrkrHitv2.cc
TrkrHitv2::~TrkrHitv2 () inline override
dtor
Definition at line 31 of file TrkrHitv2.h.
View newest version in sPHENIX GitHub at line 31 of file TrkrHitv2.h
Member Function Documentation
void TrkrHitv2::addEnergy (const double edep) override virtual
Reimplemented from TrkrHit.
Definition at line 9 of file TrkrHitv2.cc.
View newest version in sPHENIX GitHub at line 9 of file TrkrHitv2.cc
References double(), and m_adc.
Referenced by PHG4MicromegasHitReco::process_event().
TrkrHitv2::ClassDefOverride (TrkrHitv2 , 1) protected
unsigned int TrkrHitv2::getAdc () override virtual
Reimplemented from TrkrHit.
Definition at line 38 of file TrkrHitv2.cc.
View newest version in sPHENIX GitHub at line 38 of file TrkrHitv2.cc
References m_adc.
double TrkrHitv2::getEnergy () override virtual
Reimplemented from TrkrHit.
Definition at line 25 of file TrkrHitv2.cc.
View newest version in sPHENIX GitHub at line 25 of file TrkrHitv2.cc
References m_adc.
void TrkrHitv2::identify (std::ostream & os = std::cout) const inline override virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from TrkrHit.
Definition at line 33 of file TrkrHitv2.h.
View newest version in sPHENIX GitHub at line 33 of file TrkrHitv2.h
References m_adc, and os.
int TrkrHitv2::isValid () const inline override virtual
isValid returns non zero if object contains vailid data
Reimplemented from TrkrHit.
Definition at line 38 of file TrkrHitv2.h.
View newest version in sPHENIX GitHub at line 38 of file TrkrHitv2.h
void TrkrHitv2::Reset () inline override virtual
Clear Event.
Reimplemented from TrkrHit.
Definition at line 37 of file TrkrHitv2.h.
View newest version in sPHENIX GitHub at line 37 of file TrkrHitv2.h
void TrkrHitv2::setAdc (const unsigned int adc) override virtual
Reimplemented from TrkrHit.
Definition at line 30 of file TrkrHitv2.cc.
View newest version in sPHENIX GitHub at line 30 of file TrkrHitv2.cc
References m_adc.
Referenced by MicromegasRawDataDecoder::process_event(), and MicromegasCombinedDataDecoder::process_event().
Member Data Documentation
unsigned short TrkrHitv2::m_adc = 0 protected
Definition at line 50 of file TrkrHitv2.h.
View newest version in sPHENIX GitHub at line 50 of file TrkrHitv2.h
Referenced by addEnergy(), getAdc(), getEnergy(), identify(), and setAdc().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/trackbase/TrkrHitv2.h
coresoftware/blob/master/offline/packages/trackbase/TrkrHitv2.cc