Analysis Software: macros/blob/master/calibrations/calo/emcal_calib_year1/track_calib/do_eta_fit_emc.C File Reference
do_eta_fit_emc.C File Reference
#include <GlobalVariables.C>
#include "litecaloeval/LiteCaloEval.h"
Functions
void do_eta_fit_emc (const char *reffile="condor/combine_out/out_sum.root", const char *infile="condor/combine_out/out_23746.root", const char *modfile="calib.root")
Function Documentation
void do_eta_fit_emc (const char * reffile = "condor/combine_out/out_sum.root", const char * infile = "condor/combine_out/out_23746.root", const char * modfile = "calib.root")
create LCE objects, one for a mod set of histos (modlce) and other for non mod set of histos (reflce)
set the calo type to run over
get histograms for not mod histos
get histograms for mod histos
set the fit range
Definition at line 7 of file do_eta_fit_emc.C.
View newest version in sPHENIX GitHub at line 7 of file do_eta_fit_emc.C
References LiteCaloEval::CaloType(), LiteCaloEval::CEMC, LiteCaloEval::FitRelativeShifts(), LiteCaloEval::Get_Histos(), infile, LiteCaloEval::setFitMax(), LiteCaloEval::setFitMin(), and t.