Analysis Software: prototype/blob/master/macros/tpc2019/DrawTPCFEE.C File Reference
DrawTPCFEE.C File Reference
#include <TChain.h>
#include <TFile.h>
#include <TGraphAsymmErrors.h>
#include <TGraphErrors.h>
#include <TH1.h>
#include <TH2.h>
#include <TH3.h>
#include <TLatex.h>
#include <TLegend.h>
#include <TString.h>
#include <cassert>
#include <cmath>
#include "SaveCanvas.C"
#include "sPhenixStyle.C"
Functions
void DrawTPCFEE (const char *infile="data/pulser/tpc_fee_pulser-0000ALL-0000.evt_TPCFEETestRecov1.root")
void HitPositionCheck ()
void AmplitudeCheck ()
void EventCheck ()
void ChannelCheck ()
Variables
TFile * _file0 = NULL
TString description
TChain * eventT = NULL
TChain * chanT = NULL
TH1 * hNormalization = NULL
int total_event = 0
Function Documentation
void AmplitudeCheck ()
Definition at line 139 of file DrawTPCFEE.C.
View newest version in sPHENIX GitHub at line 139 of file DrawTPCFEE.C
References _file0, assert, eventT, hNormalization, ambiguity_solver_full_chain::idx, merge_hashes::p, and SaveCanvas().
void ChannelCheck ()
Definition at line 417 of file DrawTPCFEE.C.
View newest version in sPHENIX GitHub at line 417 of file DrawTPCFEE.C
References _file0, assert, chanT, hNormalization, ambiguity_solver_full_chain::idx, merge_hashes::p, and SaveCanvas().
void DrawTPCFEE (const char * infile = "data/pulser/tpc_fee_pulser-0000ALL-0000.evt_TPCFEETestRecov1.root")
Definition at line 34 of file DrawTPCFEE.C.
View newest version in sPHENIX GitHub at line 34 of file DrawTPCFEE.C
References _file0, AmplitudeCheck(), assert, ChannelCheck(), chanT, EventCheck(), eventT, f, h, HitPositionCheck(), hNormalization, infile, n, next, and SetsPhenixStyle().
void EventCheck ()
Definition at line 171 of file DrawTPCFEE.C.
View newest version in sPHENIX GitHub at line 171 of file DrawTPCFEE.C
References _file0, assert, eventT, hNormalization, ambiguity_solver_full_chain::idx, merge_hashes::p, and SaveCanvas().
void HitPositionCheck ()
Definition at line 107 of file DrawTPCFEE.C.
View newest version in sPHENIX GitHub at line 107 of file DrawTPCFEE.C
References _file0, assert, eventT, hNormalization, ambiguity_solver_full_chain::idx, merge_hashes::p, and SaveCanvas().
Variable Documentation
TFile* _file0 = NULL
Definition at line 23 of file DrawTPCFEE.C.
View newest version in sPHENIX GitHub at line 23 of file DrawTPCFEE.C
TChain* chanT = NULL
Definition at line 28 of file DrawTPCFEE.C.
View newest version in sPHENIX GitHub at line 28 of file DrawTPCFEE.C
TString description
Definition at line 24 of file DrawTPCFEE.C.
View newest version in sPHENIX GitHub at line 24 of file DrawTPCFEE.C
TChain* eventT = NULL
Definition at line 27 of file DrawTPCFEE.C.
View newest version in sPHENIX GitHub at line 27 of file DrawTPCFEE.C
TH1* hNormalization = NULL
Definition at line 30 of file DrawTPCFEE.C.
View newest version in sPHENIX GitHub at line 30 of file DrawTPCFEE.C
int total_event = 0
Definition at line 32 of file DrawTPCFEE.C.
View newest version in sPHENIX GitHub at line 32 of file DrawTPCFEE.C