Analysis Software: PHG4Reco Class Reference
PHG4Reco Class Reference
Runs G4 as a subsystem.
#include <coresoftware/blob/master/simulation/g4simulation/g4main/PHG4Reco.h>
Public Types
enum DecayerOptions { kGEANTInternalDecayer = 0, kPYTHIA6Decayer = 1, kEvtGenDecayer = 2 }
Public Member Functions
PHG4Reco (const std::string &name="PHG4RECO")
constructor
~PHG4Reco () override
destructor
int Init (PHCompositeNode *) override
full initialization
int InitRun (PHCompositeNode *topNode) override
int process_event (PHCompositeNode *) override
event processing method
int ResetEvent (PHCompositeNode *) override
Clean up after each event.
void Print (const std::string &what=std::string()) const override
print info
void registerSubsystem (PHG4Subsystem *subsystem)
register subsystem
int ApplyCommand (const std::string &cmd)
interface to G4 cmd interpreter
int StartGui ()
start the gui
int InitField (PHCompositeNode *topNode)
void set_field (const float tesla)
set default magnetic field strength with a constant magnetic field. Only valid if set_field_map() is not used. If available, Field map setting on DST take higher priority.
void set_field_map (const std::string &fmap, const PHFieldConfig::FieldConfigTypes dim)
void set_field_rescale (const float rescale)
set default scaling factor for input magnetic field map. If available, Field map setting on DST take higher priority.
void set_force_decay (EDecayType force_decay_type)
void set_decayer (DecayerOptions type)
void export_geometry (bool b, const std::string &filename="sPHENIXGeom.root")
export geometry to root file
void save_DST_geometry (bool b)
Save geometry from Geant4 to DST.
void SetWorldSizeX (const double sx)
void SetWorldSizeY (const double sy)
void SetWorldSizeZ (const double sz)
double GetWorldSizeX () const
double GetWorldSizeY () const
double GetWorldSizeZ () const
void SetWorldShape (const std::string &s)
void SetWorldMaterial (const std::string &s)
void SetPhysicsList (const std::string &s)
void set_rapidity_coverage (const double eta)
int setupInputEventNodeReader (PHCompositeNode *)
PHG4Subsystem * getSubsystem (const std::string &name)
PHG4DisplayAction * GetDisplayAction ()
void Dump_GDML (const std::string &filename)
void Dump_G4_GDML (const std::string &filename)
void G4Verbosity (const int i)
void setDisableUserActions (bool b=true)
disable event/track/stepping actions to reduce resource consumption for G4 running only. E.g. dose analysis
void ApplyDisplayAction ()
void CustomizeEvtGenDecay (const std::string &DecayFile)
Public Member Functions inherited from SubsysReco
~SubsysReco () override
virtual int End (PHCompositeNode *)
Called at the end of all processing.
virtual int EndRun (const int)
Called at the end of each run.
virtual int Reset (PHCompositeNode *)
Reset.
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Static Public Member Functions
static void G4Seed (const unsigned int i)
Private Member Functions
int InitUImanager ()
void DefineMaterials ()
void DefineRegions ()
Static Private Member Functions
static void g4guithread (void *ptr)
Private Attributes
float m_MagneticField = 0.
float m_MagneticFieldRescale = 1.0
double m_WorldSize [3] {1000., 1000., 1000.}
G4TBMagneticFieldSetup * m_Field = nullptr
magnetic field
G4RunManager * m_RunManager = nullptr
pointer to geant run manager
PHG4UIsession * m_UISession = nullptr
pointer to geant ui session
PHG4PhenixDetector * m_Detector = nullptr
pointer to detector
PHG4PhenixEventAction * m_EventAction = nullptr
pointer to main event action
PHG4PhenixStackingAction * m_StackingAction = nullptr
pointer to main stacking action
PHG4PhenixSteppingAction * m_SteppingAction = nullptr
pointer to main stepping action
PHG4PhenixTrackingAction * m_TrackingAction = nullptr
pointer to main tracking action
PHG4DisplayAction * m_DisplayAction = nullptr
display attribute setting
PHG4PrimaryGeneratorAction * m_GeneratorAction = nullptr
event generator (read from PHG4INEVENT node)
std::list< PHG4Subsystem * > m_SubsystemList
list of subsystems
G4VisManager * m_VisManager = nullptr
G4UImessenger * m_Fun4AllMessenger = nullptr
G4UImanager * m_UImanager = nullptr
double m_EtaCoverage = 1.0
PHFieldConfig::FieldConfigTypes m_FieldConfigType = PHFieldConfig::kFieldUniform
std::string m_FieldMapFile = "NONE"
std::string m_WorldShape = "G4Tubs"
std::string m_WorldMaterial = "G4_AIR"
std::string m_PhysicsList = "FTFP_BERT"
bool m_ExportGeometry = false
std::string m_ExportGeomFilename = "sPHENIXGeom.root"
bool m_ActiveForceDecayFlag = false
DecayerOptions m_Decayer = kEvtGenDecayer
std::string EvtGenDecayFile = ""
bool CustomizeDecay = false
EDecayType m_ForceDecayType = kAll
bool m_SaveDstGeometryFlag = true
bool m_disableUserActions = false
Additional Inherited Members
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Detailed Description
Runs G4 as a subsystem.
Definition at line 37 of file PHG4Reco.h.
View newest version in sPHENIX GitHub at line 37 of file PHG4Reco.h
Member Enumeration Documentation
enum PHG4Reco::DecayerOptions
Enumerator:
kGEANTInternalDecayer
kPYTHIA6Decayer
kEvtGenDecayer
Definition at line 40 of file PHG4Reco.h.
View newest version in sPHENIX GitHub at line 40 of file PHG4Reco.h
Constructor & Destructor Documentation
PHG4Reco::PHG4Reco (const std::string & name = "PHG4RECO") explicit
constructor
Definition at line 114 of file PHG4Reco.cc.
View newest version in sPHENIX GitHub at line 114 of file PHG4Reco.cc
PHG4Reco::~PHG4Reco () override
destructor
Definition at line 122 of file PHG4Reco.cc.
View newest version in sPHENIX GitHub at line 122 of file PHG4Reco.cc
References m_DisplayAction, m_Field, m_Fun4AllMessenger, m_RunManager, m_SubsystemList, m_UISession, and m_VisManager.
Member Function Documentation
int PHG4Reco::ApplyCommand (const std::string & cmd)
interface to G4 cmd interpreter
Definition at line 611 of file PHG4Reco.cc.
View newest version in sPHENIX GitHub at line 611 of file PHG4Reco.cc
References InitUImanager(), and m_UImanager.
Referenced by ConstructGeometry(), DisplayOn(), Fun4All_G4_EICIR(), Fun4All_G4_fsPHENIX_FastSim(), Fun4All_G4_fsPHENIX_pi0(), Fun4All_Generator_Display(), G4Cmd(), and matscan().
void PHG4Reco::ApplyDisplayAction ()
Definition at line 1088 of file PHG4Reco.cc.
View newest version in sPHENIX GitHub at line 1088 of file PHG4Reco.cc
References parse_cmake_options::action, PHG4DisplayAction::ApplyDisplayAction(), PHG4PhenixDetector::GetPhysicalVolume(), m_Detector, m_DisplayAction, m_SubsystemList, and Fun4AllBase::Verbosity().
Referenced by ConstructGeometry(), DisplayOn(), Fun4All_Generator_Display(), and QTGui().
void PHG4Reco::CustomizeEvtGenDecay (const std::string & DecayFile) inline
Definition at line 143 of file PHG4Reco.h.
View newest version in sPHENIX GitHub at line 143 of file PHG4Reco.h
References CustomizeDecay, EVTGENDECAYER::DecayFile, and EvtGenDecayFile.
Referenced by G4Setup().
void PHG4Reco::DefineMaterials () private
Definition at line 771 of file PHG4Reco.cc.
View newest version in sPHENIX GitHub at line 771 of file PHG4Reco.cc
References KFPMath::a, Acts::UnitConstants::cm3, Acts::UnitConstants::eV, Acts::UnitConstants::g, Acts::UnitConstants::kg, Acts::UnitConstants::m3, perf_headwind::name, and physmon_track_finding_ttbar::z.
Referenced by Init().
void PHG4Reco::DefineRegions () private
Definition at line 1043 of file PHG4Reco.cc.
View newest version in sPHENIX GitHub at line 1043 of file PHG4Reco.cc
Referenced by Init().
void PHG4Reco::Dump_G4_GDML (const std::string & filename)
Definition at line 605 of file PHG4Reco.cc.
View newest version in sPHENIX GitHub at line 605 of file PHG4Reco.cc
References PHG4GDMLUtility::Dump_G4_GDML(), PHG4PhenixDetector::GetPhysicalVolume(), and m_Detector.
void PHG4Reco::Dump_GDML (const std::string & filename)
Definition at line 598 of file PHG4Reco.cc.
View newest version in sPHENIX GitHub at line 598 of file PHG4Reco.cc
References PHG4GDMLUtility::Dump_GDML(), PHG4PhenixDetector::GetPhysicalVolume(), and m_Detector.
Referenced by InitRun().
void PHG4Reco::export_geometry (bool b, const std::string & filename = "sPHENIXGeom.root") inline
export geometry to root file
Definition at line 109 of file PHG4Reco.h.
View newest version in sPHENIX GitHub at line 109 of file PHG4Reco.h
References KFPMath::b, filename, m_ExportGeometry, and m_ExportGeomFilename.
static void PHG4Reco::g4guithread (void * ptr) static private
void PHG4Reco::G4Seed (const unsigned int i) static
Definition at line 758 of file PHG4Reco.cc.
View newest version in sPHENIX GitHub at line 758 of file PHG4Reco.cc
References PHRandomSeed::Verbosity().
Referenced by Init().
void PHG4Reco::G4Verbosity (const int i)
Definition at line 1080 of file PHG4Reco.cc.
View newest version in sPHENIX GitHub at line 1080 of file PHG4Reco.cc
References m_RunManager.
PHG4DisplayAction* PHG4Reco::GetDisplayAction () inline
Definition at line 133 of file PHG4Reco.h.
View newest version in sPHENIX GitHub at line 133 of file PHG4Reco.h
References m_DisplayAction.
PHG4Subsystem * PHG4Reco::getSubsystem (const std::string & name)
Definition at line 1063 of file PHG4Reco.cc.
View newest version in sPHENIX GitHub at line 1063 of file PHG4Reco.cc
References m_SubsystemList, perf_headwind::name, and Fun4AllBase::Verbosity().
double PHG4Reco::GetWorldSizeX () const inline
Definition at line 120 of file PHG4Reco.h.
View newest version in sPHENIX GitHub at line 120 of file PHG4Reco.h
References m_WorldSize.
double PHG4Reco::GetWorldSizeY () const inline
Definition at line 121 of file PHG4Reco.h.
View newest version in sPHENIX GitHub at line 121 of file PHG4Reco.h
References m_WorldSize.
Referenced by WorldSize().
double PHG4Reco::GetWorldSizeZ () const inline
Definition at line 122 of file PHG4Reco.h.
View newest version in sPHENIX GitHub at line 122 of file PHG4Reco.h
References m_WorldSize.
Referenced by Fun4All_G4_W(), G4Setup(), and WorldSize().
int PHG4Reco::Init (PHCompositeNode * topNode) override virtual
full initialization
Reimplemented from SubsysReco.
Definition at line 140 of file PHG4Reco.cc.
View newest version in sPHENIX GitHub at line 140 of file PHG4Reco.cc
References CustomizeDecay, EvtGenExtDecayerPhysics::CustomizeEvtGenDecay(), DefineMaterials(), DefineRegions(), EvtGenDecayFile, G4Seed(), kEvtGenDecayer, kGEANTInternalDecayer, kPYTHIA6Decayer, m_ActiveForceDecayFlag, m_Decayer, m_ForceDecayType, m_PhysicsList, m_RunManager, m_SubsystemList, m_UISession, P6DExtDecayerPhysics::SetForceDecay(), and Fun4AllBase::Verbosity().
int PHG4Reco::InitField (PHCompositeNode * topNode)
Definition at line 272 of file PHG4Reco.cc.
View newest version in sPHENIX GitHub at line 272 of file PHG4Reco.cc
References assert, Fun4AllReturnCodes::EVENT_OK, PHFieldUtility::GetFieldMapNode(), CDBInterface::getUrl(), CDBInterface::instance(), m_Field, m_FieldConfigType, m_FieldMapFile, m_MagneticField, m_MagneticFieldRescale, summary::url, and Fun4AllBase::Verbosity().
Referenced by InitRun().
int PHG4Reco::InitRun (PHCompositeNode *) override virtual
Called for first event when run number is known. Typically this is where you may want to fetch data from database, because you know the run number.
Reimplemented from SubsysReco.
Definition at line 309 of file PHG4Reco.cc.
View newest version in sPHENIX GitHub at line 309 of file PHG4Reco.cc
References parse_cmake_options::action, PHG4PhenixTrackingAction::AddAction(), PHG4PhenixSteppingAction::AddAction(), PHG4PhenixStackingAction::AddAction(), PHG4PhenixEventAction::AddAction(), PHG4PhenixDetector::AddDetector(), Acts::UnitConstants::cm, Dump_GDML(), Fun4AllReturnCodes::EVENT_OK, PHGeomUtility::ExportGeomtry(), filename, PHGeomUtility::GenerateGeometryFileName(), PHGeomUtility::ImportGeomFile(), InitField(), recoConsts::instance(), m_Detector, m_disableUserActions, m_DisplayAction, m_EventAction, m_ExportGeometry, m_ExportGeomFilename, m_RunManager, m_SaveDstGeometryFlag, m_StackingAction, m_SteppingAction, m_SubsystemList, m_TrackingAction, m_UISession, m_WorldMaterial, m_WorldShape, m_WorldSize, Fun4AllBase::Name(), particle, PHWHERE, PHGeomUtility::RemoveGeometryFile(), PHFlag::set_FloatFlag(), PHFlag::set_StringFlag(), setupInputEventNodeReader(), PHG4PhenixDetector::SetWorldMaterial(), PHG4PhenixDetector::SetWorldShape(), PHG4PhenixDetector::SetWorldSizeX(), PHG4PhenixDetector::SetWorldSizeY(), PHG4PhenixDetector::SetWorldSizeZ(), PHG4UIsession::Verbosity(), PHRandomSeed::Verbosity(), PHG4PhenixDetector::Verbosity(), and Fun4AllBase::Verbosity().
Referenced by ConstructGeometry(), DisplayOn(), Fun4All_Generator_Display(), matscan(), and QTGui().
int PHG4Reco::InitUImanager () private
Definition at line 632 of file PHG4Reco.cc.
View newest version in sPHENIX GitHub at line 632 of file PHG4Reco.cc
References m_UImanager, and m_VisManager.
Referenced by ApplyCommand(), and StartGui().
void PHG4Reco::Print (const std::string & what = std::string()) const override virtual
print info
Reimplemented from SubsysReco.
Definition at line 716 of file PHG4Reco.cc.
View newest version in sPHENIX GitHub at line 716 of file PHG4Reco.cc
References m_SubsystemList.
int PHG4Reco::process_event (PHCompositeNode * topNode) override virtual
event processing method
Reimplemented from SubsysReco.
Definition at line 646 of file PHG4Reco.cc.
View newest version in sPHENIX GitHub at line 646 of file PHG4Reco.cc
References Fun4AllReturnCodes::ABORTEVENT, Acts::UnitConstants::e, PHG4InEvent::identify(), m_GeneratorAction, m_RunManager, m_SubsystemList, PHWHERE, PHG4PrimaryGeneratorAction::SetInEvent(), PHRandomSeed::Verbosity(), and Fun4AllBase::Verbosity().
void PHG4Reco::registerSubsystem (PHG4Subsystem * subsystem) inline
register subsystem
Definition at line 69 of file PHG4Reco.h.
View newest version in sPHENIX GitHub at line 69 of file PHG4Reco.h
References m_SubsystemList.
Referenced by AerogelSetup(), BeamLineDefineBeamPipe(), BeamLineDefineMagnets(), BlackHole(), CEmc_1DProjectiveSpacal(), CEmc_2DProjectiveSpacal(), CEmcAlbedo(), ConstructGeometry(), DIRCSetup(), EEMCSetup(), EPD(), FEMCSetup(), FGEMSetup(), FHCALSetup(), Fun4All_G4_block(), Fun4All_G4_Calos(), Fun4All_G4_Cylinder(), Fun4All_G4_Example01(), Fun4All_G4_Example02(), Fun4All_G4_Example03(), Fun4All_G4_Geantino(), Fun4All_G4_IonGun(), Fun4All_G4_LeadBrick(), Fun4All_G4_Momentum(), Fun4All_G4_Momentum_Projection(), Fun4All_G4_Momentum_Projection_Calorimeters(), Fun4All_G4_Momentum_Projection_Detectors(), Fun4All_G4_MyDetector(), Fun4All_G4_Prototype2(), Fun4All_G4_Prototype3(), Fun4All_G4_Prototype4(), Fun4All_G4_TPC(), Fun4All_G4_W(), Fun4All_G4_Write_Dst(), Fun4All_MCEventGen(), G4Setup(), HCalInner(), HCalInner_SupportRing(), HCalOuter(), Intt(), IRSetup(), Magnet(), make_GEM_station(), make_piston(), Mbd(), Micromegas(), Mvtx(), Pipe(), PlugDoor(), PSTOF(), RICHSetup(), Svtx(), TPC(), TPC_Endcaps(), and ZDCSetup().
int PHG4Reco::ResetEvent (PHCompositeNode * topNode) override virtual
Clean up after each event.
Reimplemented from SubsysReco.
Definition at line 707 of file PHG4Reco.cc.
View newest version in sPHENIX GitHub at line 707 of file PHG4Reco.cc
References m_SubsystemList.
void PHG4Reco::save_DST_geometry (bool b) inline
Save geometry from Geant4 to DST.
Definition at line 116 of file PHG4Reco.h.
View newest version in sPHENIX GitHub at line 116 of file PHG4Reco.h
References KFPMath::b, and m_SaveDstGeometryFlag.
Referenced by Fun4All_G4_Example01(), Fun4All_G4_Example02(), Fun4All_G4_Example03(), Fun4All_G4_Geantino(), Fun4All_G4_MyDetector(), Fun4All_G4_TPC(), Fun4All_G4_Write_Dst(), Fun4All_Generator_Display(), and G4Setup().
void PHG4Reco::set_decayer (DecayerOptions type) inline
Definition at line 106 of file PHG4Reco.h.
View newest version in sPHENIX GitHub at line 106 of file PHG4Reco.h
References m_Decayer, and parse_cmake_options::type.
void PHG4Reco::set_field (const float tesla) inline
set default magnetic field strength with a constant magnetic field. Only valid if set_field_map() is not used. If available, Field map setting on DST take higher priority.
Definition at line 83 of file PHG4Reco.h.
View newest version in sPHENIX GitHub at line 83 of file PHG4Reco.h
References m_MagneticField.
Referenced by ConstructGeometry(), Fun4All_G4_block(), Fun4All_G4_Cylinder(), Fun4All_G4_Example01(), Fun4All_G4_Example02(), Fun4All_G4_Example03(), Fun4All_G4_Geantino(), Fun4All_G4_IonGun(), Fun4All_G4_LeadBrick(), Fun4All_G4_Momentum(), Fun4All_G4_Momentum_Projection(), Fun4All_G4_Momentum_Projection_Calorimeters(), Fun4All_G4_Momentum_Projection_Detectors(), Fun4All_G4_MyDetector(), Fun4All_G4_Prototype2(), Fun4All_G4_Prototype3(), Fun4All_G4_Prototype4(), Fun4All_G4_TPC(), Fun4All_G4_W(), Fun4All_G4_Write_Dst(), Fun4All_Generator_Display(), and G4Setup().
void PHG4Reco::set_field_map (const std::string & fmap, const PHFieldConfig::FieldConfigTypes dim) inline
Set default field map. If available, Field map setting on DST take higher priority.
Parameters
[in] fmap Field map ROOT file
[in] dim Field map format. See PHFieldConfig::FieldConfigTypes for available formats.
Definition at line 91 of file PHG4Reco.h.
View newest version in sPHENIX GitHub at line 91 of file PHG4Reco.h
References Acts::Test::dim, m_FieldConfigType, and m_FieldMapFile.
Referenced by G4Setup().
void PHG4Reco::set_field_rescale (const float rescale) inline
set default scaling factor for input magnetic field map. If available, Field map setting on DST take higher priority.
Definition at line 98 of file PHG4Reco.h.
View newest version in sPHENIX GitHub at line 98 of file PHG4Reco.h
References m_MagneticFieldRescale.
Referenced by Fun4All_G4_W(), and G4Setup().
void PHG4Reco::set_force_decay (EDecayType force_decay_type) inline
Definition at line 100 of file PHG4Reco.h.
View newest version in sPHENIX GitHub at line 100 of file PHG4Reco.h
References m_ActiveForceDecayFlag, and m_ForceDecayType.
Referenced by G4Setup().
void PHG4Reco::set_rapidity_coverage (const double eta)
Definition at line 752 of file PHG4Reco.cc.
View newest version in sPHENIX GitHub at line 752 of file PHG4Reco.cc
References eta, m_EtaCoverage, and PHG4Utils::SetPseudoRapidityCoverage().
Referenced by Fun4All_Generator_Display(), and G4Setup().
void PHG4Reco::setDisableUserActions (bool b = true) inline
disable event/track/stepping actions to reduce resource consumption for G4 running only. E.g. dose analysis
Definition at line 140 of file PHG4Reco.h.
View newest version in sPHENIX GitHub at line 140 of file PHG4Reco.h
References KFPMath::b, and m_disableUserActions.
void PHG4Reco::SetPhysicsList (const std::string & s) inline
Definition at line 125 of file PHG4Reco.h.
View newest version in sPHENIX GitHub at line 125 of file PHG4Reco.h
References m_PhysicsList, and physmon_simulation::s.
Referenced by Fun4All_G4_block(), Fun4All_G4_IonGun(), Fun4All_G4_LeadBrick(), Fun4All_G4_W(), and WorldInit().
int PHG4Reco::setupInputEventNodeReader (PHCompositeNode * topNode)
Definition at line 730 of file PHG4Reco.cc.
View newest version in sPHENIX GitHub at line 730 of file PHG4Reco.cc
References PHCompositeNode::addNode(), PHNodeIterator::findFirst(), m_GeneratorAction, and m_RunManager.
Referenced by InitRun().
void PHG4Reco::SetWorldMaterial (const std::string & s) inline
Definition at line 124 of file PHG4Reco.h.
View newest version in sPHENIX GitHub at line 124 of file PHG4Reco.h
References m_WorldMaterial, and physmon_simulation::s.
Referenced by Fun4All_G4_block(), Fun4All_G4_Calos(), Fun4All_G4_IonGun(), Fun4All_G4_LeadBrick(), Fun4All_G4_W(), G4Setup(), and WorldInit().
void PHG4Reco::SetWorldShape (const std::string & s) inline
Definition at line 123 of file PHG4Reco.h.
View newest version in sPHENIX GitHub at line 123 of file PHG4Reco.h
References m_WorldShape, and physmon_simulation::s.
Referenced by Fun4All_G4_block(), Fun4All_G4_IonGun(), Fun4All_G4_LeadBrick(), and Fun4All_G4_W().
void PHG4Reco::SetWorldSizeX (const double sx) inline
Definition at line 117 of file PHG4Reco.h.
View newest version in sPHENIX GitHub at line 117 of file PHG4Reco.h
References m_WorldSize.
Referenced by Fun4All_G4_block(), Fun4All_G4_IonGun(), Fun4All_G4_LeadBrick(), and Fun4All_G4_W().
void PHG4Reco::SetWorldSizeY (const double sy) inline
Definition at line 118 of file PHG4Reco.h.
View newest version in sPHENIX GitHub at line 118 of file PHG4Reco.h
References m_WorldSize.
Referenced by Fun4All_G4_block(), Fun4All_G4_IonGun(), Fun4All_G4_LeadBrick(), Fun4All_G4_W(), and WorldSize().
void PHG4Reco::SetWorldSizeZ (const double sz) inline
Definition at line 119 of file PHG4Reco.h.
View newest version in sPHENIX GitHub at line 119 of file PHG4Reco.h
References m_WorldSize.
Referenced by Fun4All_G4_block(), Fun4All_G4_IonGun(), Fun4All_G4_LeadBrick(), Fun4All_G4_W(), IRSetup(), and WorldSize().
int PHG4Reco::StartGui ()
start the gui
Definition at line 619 of file PHG4Reco.cc.
View newest version in sPHENIX GitHub at line 619 of file PHG4Reco.cc
References check_smearing_config::args, InitUImanager(), and m_UImanager.
Referenced by QTGui().
Member Data Documentation
bool PHG4Reco::CustomizeDecay = false private
Definition at line 217 of file PHG4Reco.h.
View newest version in sPHENIX GitHub at line 217 of file PHG4Reco.h
Referenced by CustomizeEvtGenDecay(), and Init().
std::string PHG4Reco::EvtGenDecayFile = "" private
Definition at line 216 of file PHG4Reco.h.
View newest version in sPHENIX GitHub at line 216 of file PHG4Reco.h
Referenced by CustomizeEvtGenDecay(), and Init().
bool PHG4Reco::m_ActiveForceDecayFlag = false private
Definition at line 213 of file PHG4Reco.h.
View newest version in sPHENIX GitHub at line 213 of file PHG4Reco.h
Referenced by Init(), and set_force_decay().
DecayerOptions PHG4Reco::m_Decayer = kEvtGenDecayer private
Definition at line 215 of file PHG4Reco.h.
View newest version in sPHENIX GitHub at line 215 of file PHG4Reco.h
Referenced by Init(), and set_decayer().
PHG4PhenixDetector* PHG4Reco::m_Detector = nullptr private
pointer to detector
Definition at line 169 of file PHG4Reco.h.
View newest version in sPHENIX GitHub at line 169 of file PHG4Reco.h
Referenced by ApplyDisplayAction(), Dump_G4_GDML(), Dump_GDML(), and InitRun().
bool PHG4Reco::m_disableUserActions = false private
Definition at line 222 of file PHG4Reco.h.
View newest version in sPHENIX GitHub at line 222 of file PHG4Reco.h
Referenced by InitRun(), and setDisableUserActions().
PHG4DisplayAction* PHG4Reco::m_DisplayAction = nullptr private
display attribute setting
derives from PHG4DisplayAction
Definition at line 185 of file PHG4Reco.h.
View newest version in sPHENIX GitHub at line 185 of file PHG4Reco.h
Referenced by ApplyDisplayAction(), GetDisplayAction(), InitRun(), and ~PHG4Reco().
double PHG4Reco::m_EtaCoverage = 1.0 private
Definition at line 201 of file PHG4Reco.h.
View newest version in sPHENIX GitHub at line 201 of file PHG4Reco.h
Referenced by set_rapidity_coverage().
PHG4PhenixEventAction* PHG4Reco::m_EventAction = nullptr private
pointer to main event action
Definition at line 172 of file PHG4Reco.h.
View newest version in sPHENIX GitHub at line 172 of file PHG4Reco.h
Referenced by InitRun().
bool PHG4Reco::m_ExportGeometry = false private
Definition at line 208 of file PHG4Reco.h.
View newest version in sPHENIX GitHub at line 208 of file PHG4Reco.h
Referenced by export_geometry(), and InitRun().
std::string PHG4Reco::m_ExportGeomFilename = "sPHENIXGeom.root" private
Definition at line 209 of file PHG4Reco.h.
View newest version in sPHENIX GitHub at line 209 of file PHG4Reco.h
Referenced by export_geometry(), and InitRun().
G4TBMagneticFieldSetup* PHG4Reco::m_Field = nullptr private
magnetic field
Definition at line 160 of file PHG4Reco.h.
View newest version in sPHENIX GitHub at line 160 of file PHG4Reco.h
Referenced by InitField(), and ~PHG4Reco().
PHFieldConfig::FieldConfigTypes PHG4Reco::m_FieldConfigType = PHFieldConfig::kFieldUniform private
Definition at line 202 of file PHG4Reco.h.
View newest version in sPHENIX GitHub at line 202 of file PHG4Reco.h
Referenced by InitField(), and set_field_map().
std::string PHG4Reco::m_FieldMapFile = "NONE" private
Definition at line 203 of file PHG4Reco.h.
View newest version in sPHENIX GitHub at line 203 of file PHG4Reco.h
Referenced by InitField(), and set_field_map().
EDecayType PHG4Reco::m_ForceDecayType = kAll private
Definition at line 219 of file PHG4Reco.h.
View newest version in sPHENIX GitHub at line 219 of file PHG4Reco.h
Referenced by Init(), and set_force_decay().
G4UImessenger* PHG4Reco::m_Fun4AllMessenger = nullptr private
Definition at line 197 of file PHG4Reco.h.
View newest version in sPHENIX GitHub at line 197 of file PHG4Reco.h
Referenced by ~PHG4Reco().
PHG4PrimaryGeneratorAction* PHG4Reco::m_GeneratorAction = nullptr private
event generator (read from PHG4INEVENT node)
Definition at line 188 of file PHG4Reco.h.
View newest version in sPHENIX GitHub at line 188 of file PHG4Reco.h
Referenced by process_event(), and setupInputEventNodeReader().
float PHG4Reco::m_MagneticField = 0. private
Definition at line 155 of file PHG4Reco.h.
View newest version in sPHENIX GitHub at line 155 of file PHG4Reco.h
Referenced by InitField(), and set_field().
float PHG4Reco::m_MagneticFieldRescale = 1.0 private
Definition at line 156 of file PHG4Reco.h.
View newest version in sPHENIX GitHub at line 156 of file PHG4Reco.h
Referenced by InitField(), and set_field_rescale().
std::string PHG4Reco::m_PhysicsList = "FTFP_BERT" private
Definition at line 206 of file PHG4Reco.h.
View newest version in sPHENIX GitHub at line 206 of file PHG4Reco.h
Referenced by Init(), and SetPhysicsList().
G4RunManager* PHG4Reco::m_RunManager = nullptr private
pointer to geant run manager
Definition at line 163 of file PHG4Reco.h.
View newest version in sPHENIX GitHub at line 163 of file PHG4Reco.h
Referenced by G4Verbosity(), Init(), InitRun(), process_event(), setupInputEventNodeReader(), and ~PHG4Reco().
bool PHG4Reco::m_SaveDstGeometryFlag = true private
Definition at line 221 of file PHG4Reco.h.
View newest version in sPHENIX GitHub at line 221 of file PHG4Reco.h
Referenced by InitRun(), and save_DST_geometry().
PHG4PhenixStackingAction* PHG4Reco::m_StackingAction = nullptr private
pointer to main stacking action
Definition at line 175 of file PHG4Reco.h.
View newest version in sPHENIX GitHub at line 175 of file PHG4Reco.h
Referenced by InitRun().
PHG4PhenixSteppingAction* PHG4Reco::m_SteppingAction = nullptr private
pointer to main stepping action
Definition at line 178 of file PHG4Reco.h.
View newest version in sPHENIX GitHub at line 178 of file PHG4Reco.h
Referenced by InitRun().
std::list<PHG4Subsystem *> PHG4Reco::m_SubsystemList private
list of subsystems
Definition at line 191 of file PHG4Reco.h.
View newest version in sPHENIX GitHub at line 191 of file PHG4Reco.h
Referenced by ApplyDisplayAction(), getSubsystem(), Init(), InitRun(), Print(), process_event(), registerSubsystem(), ResetEvent(), and ~PHG4Reco().
PHG4PhenixTrackingAction* PHG4Reco::m_TrackingAction = nullptr private
pointer to main tracking action
Definition at line 181 of file PHG4Reco.h.
View newest version in sPHENIX GitHub at line 181 of file PHG4Reco.h
Referenced by InitRun().
G4UImanager* PHG4Reco::m_UImanager = nullptr private
Definition at line 200 of file PHG4Reco.h.
View newest version in sPHENIX GitHub at line 200 of file PHG4Reco.h
Referenced by ApplyCommand(), InitUImanager(), and StartGui().
PHG4UIsession* PHG4Reco::m_UISession = nullptr private
pointer to geant ui session
Definition at line 166 of file PHG4Reco.h.
View newest version in sPHENIX GitHub at line 166 of file PHG4Reco.h
Referenced by Init(), InitRun(), and ~PHG4Reco().
G4VisManager* PHG4Reco::m_VisManager = nullptr private
Definition at line 194 of file PHG4Reco.h.
View newest version in sPHENIX GitHub at line 194 of file PHG4Reco.h
Referenced by InitUImanager(), and ~PHG4Reco().
std::string PHG4Reco::m_WorldMaterial = "G4_AIR" private
Definition at line 205 of file PHG4Reco.h.
View newest version in sPHENIX GitHub at line 205 of file PHG4Reco.h
Referenced by InitRun(), and SetWorldMaterial().
std::string PHG4Reco::m_WorldShape = "G4Tubs" private
Definition at line 204 of file PHG4Reco.h.
View newest version in sPHENIX GitHub at line 204 of file PHG4Reco.h
Referenced by InitRun(), and SetWorldShape().
double PHG4Reco::m_WorldSize[3] {1000., 1000., 1000.} private
Definition at line 157 of file PHG4Reco.h.
View newest version in sPHENIX GitHub at line 157 of file PHG4Reco.h
Referenced by GetWorldSizeX(), GetWorldSizeY(), GetWorldSizeZ(), InitRun(), SetWorldSizeX(), SetWorldSizeY(), and SetWorldSizeZ().
The documentation for this class was generated from the following files:
coresoftware/blob/master/simulation/g4simulation/g4main/PHG4Reco.h
coresoftware/blob/master/simulation/g4simulation/g4main/PHG4Reco.cc