Analysis Software: cl::Image Class Reference
cl::Image Class Reference
Base class interface for all images.
#include <JETSCAPE/blob/main/external_packages/clvisc_wrapper/include/cl.hpp>
Public Member Functions
template<typename T >
cl_int getImageInfo (cl_image_info name, T *param) const
template<cl_int name>
detail::param_traits
< detail::cl_image_info, name >
::param_type getImageInfo (cl_int *err=NULL) const
Public Member Functions inherited from cl::Memory
Memory ()
Memory (const Memory &memory)
Memory & operator= (const Memory &rhs)
template<typename T >
cl_int getInfo (cl_mem_info name, T *param) const
template<cl_int name>
detail::param_traits
< detail::cl_mem_info, name >
::param_type getInfo (cl_int *err=NULL) const
Public Member Functions inherited from cl::detail::Wrapper< cl_mem >
Wrapper ()
Wrapper (const Wrapper< cl_type > &rhs)
~Wrapper ()
Wrapper< cl_type > & operator= (const Wrapper< cl_type > &rhs)
cl_type operator() () const
cl_type & operator() ()
Protected Member Functions
Image ()
Image (const Image &image)
Image & operator= (const Image &rhs)
Additional Inherited Members
Public Types inherited from cl::detail::Wrapper< cl_mem >
typedef cl_mem cl_type
Protected Attributes inherited from cl::detail::Wrapper< cl_mem >
cl_type object_
Detailed Description
Base class interface for all images.
Definition at line 1939 of file cl.hpp.
View newest version in sPHENIX GitHub at line 1939 of file cl.hpp
Constructor & Destructor Documentation
cl::Image::Image () inline protected
Definition at line 1942 of file cl.hpp.
View newest version in sPHENIX GitHub at line 1942 of file cl.hpp
cl::Image::Image (const Image & image) inline protected
Definition at line 1944 of file cl.hpp.
View newest version in sPHENIX GitHub at line 1944 of file cl.hpp
Member Function Documentation
template<typename T > cl_int cl::Image::getImageInfo (cl_image_info name, T * param) const inline
Definition at line 1955 of file cl.hpp.
View newest version in sPHENIX GitHub at line 1955 of file cl.hpp
References cl::detail::errHandler(), cl::detail::getInfo(), and cl::detail::Wrapper< cl_mem >::object_.
Referenced by getImageInfo().
template<cl_int name> detail::param_traits<detail::cl_image_info, name>::param_type cl::Image::getImageInfo (cl_int * err = NULL) const inline
Definition at line 1964 of file cl.hpp.
View newest version in sPHENIX GitHub at line 1964 of file cl.hpp
References getImageInfo(), and perf_headwind::name.
Image& cl::Image::operator= (const Image & rhs) inline protected
Definition at line 1946 of file cl.hpp.
View newest version in sPHENIX GitHub at line 1946 of file cl.hpp
References cl::Memory::operator=().
Referenced by cl::Image2D::operator=(), and cl::Image3D::operator=().
The documentation for this class was generated from the following file:
JETSCAPE/blob/main/external_packages/clvisc_wrapper/include/cl.hpp