Analysis Software: SepdMonDraw Class Reference
SepdMonDraw Class Reference
#include <OnlMon/blob/main/subsystems/sepd/SepdMonDraw.h>
Public Member Functions
SepdMonDraw (const std::string &name)
~SepdMonDraw () override
int Init () override
int Draw (const std::string &what="ALL") override
int MakeHtml (const std::string &what="ALL") override
int SavePlot (const std::string &what="ALL", const std::string &type="png") override
Public Member Functions inherited from OnlMonDraw
OnlMonDraw (const std::string &name="NONE")
virtual ~OnlMonDraw ()
virtual int MakePS (const std::string &what="ALL")
const std::string Name () const
void Verbosity (const int i)
int Verbosity () const
Protected Member Functions
int MakeCanvas (const std::string &name)
int DrawFirst (const std::string &what="ALL")
int DrawSecond (const std::string &what="ALL")
int DrawThird (const std::string &what="ALL")
int DrawFourth (const std::string &what="ALL")
int DrawFifth (const std::string &what="ALL")
time_t getTime ()
Protected Member Functions inherited from OnlMonDraw
virtual int DrawDeadServer (TPad *transparent)
Protected Attributes
TCanvas * TC [9] = {nullptr}
TPad * transparent [9] = {nullptr}
TPad * Pad [18] = {nullptr}
TPad * warning [18] = {nullptr}
TGraphErrors * gr [2] = {nullptr}
Protected Attributes inherited from OnlMonDraw
std::string ThisName
int verbosity = 0
Detailed Description
Definition at line 15 of file SepdMonDraw.h.
View newest version in sPHENIX GitHub at line 15 of file SepdMonDraw.h
Constructor & Destructor Documentation
SepdMonDraw::SepdMonDraw (const std::string & name)
Definition at line 24 of file SepdMonDraw.cc.
View newest version in sPHENIX GitHub at line 24 of file SepdMonDraw.cc
SepdMonDraw::~SepdMonDraw () inline override
Definition at line 20 of file SepdMonDraw.h.
View newest version in sPHENIX GitHub at line 20 of file SepdMonDraw.h
Member Function Documentation
int SepdMonDraw::Draw (const std::string & what = "ALL") override virtual
Reimplemented from OnlMonDraw.
Definition at line 128 of file SepdMonDraw.cc.
View newest version in sPHENIX GitHub at line 128 of file SepdMonDraw.cc
References DrawFifth(), DrawFirst(), DrawFourth(), and DrawSecond().
Referenced by MakeHtml(), and SavePlot().
int SepdMonDraw::DrawFifth (const std::string & what = "ALL") protected
Definition at line 474 of file SepdMonDraw.cc.
View newest version in sPHENIX GitHub at line 474 of file SepdMonDraw.cc
References OnlMonDraw::DrawDeadServer(), OnlMonClient::getHisto(), getTime(), i, OnlMonClient::instance(), leg, MakeCanvas(), Pad, OnlMonClient::RunNumber(), TC, transparent, warning, xmax, xmin, ymax, and ymin.
Referenced by Draw().
int SepdMonDraw::DrawFirst (const std::string & what = "ALL") protected
Definition at line 175 of file SepdMonDraw.cc.
View newest version in sPHENIX GitHub at line 175 of file SepdMonDraw.cc
References con, OnlMonDraw::DrawDeadServer(), OnlMonClient::EventTime(), OnlMonClient::getHisto(), OnlMonClient::instance(), MakeCanvas(), Acts::Test::nbinsx, Acts::Test::nbinsy, Pad, OnlMonClient::RunNumber(), TC, OnlMonDraw::ThisName, and transparent.
Referenced by Draw().
int SepdMonDraw::DrawFourth (const std::string & what = "ALL") protected
Definition at line 354 of file SepdMonDraw.cc.
View newest version in sPHENIX GitHub at line 354 of file SepdMonDraw.cc
References OnlMonDraw::DrawDeadServer(), OnlMonClient::getHisto(), getTime(), OnlMonClient::instance(), MakeCanvas(), Pad, OnlMonClient::RunNumber(), TC, OnlMonDraw::ThisName, and transparent.
Referenced by Draw().
int SepdMonDraw::DrawSecond (const std::string & what = "ALL") protected
Definition at line 259 of file SepdMonDraw.cc.
View newest version in sPHENIX GitHub at line 259 of file SepdMonDraw.cc
References OnlMonDraw::DrawDeadServer(), OnlMonClient::EventTime(), OnlMonClient::getHisto(), OnlMonClient::instance(), MakeCanvas(), Pad, OnlMonClient::RunNumber(), TC, OnlMonDraw::ThisName, and transparent.
Referenced by Draw().
int SepdMonDraw::DrawThird (const std::string & what = "ALL") protected
Definition at line 313 of file SepdMonDraw.cc.
View newest version in sPHENIX GitHub at line 313 of file SepdMonDraw.cc
References OnlMonDraw::DrawDeadServer(), OnlMonClient::EventTime(), OnlMonClient::getHisto(), OnlMonClient::instance(), MakeCanvas(), Pad, OnlMonClient::RunNumber(), TC, OnlMonDraw::ThisName, and transparent.
time_t SepdMonDraw::getTime () protected
Definition at line 821 of file SepdMonDraw.cc.
View newest version in sPHENIX GitHub at line 821 of file SepdMonDraw.cc
References OnlMonClient::EventTime(), and OnlMonClient::instance().
Referenced by DrawFifth(), and DrawFourth().
int SepdMonDraw::Init () override virtual
Reimplemented from OnlMonDraw.
Definition at line 30 of file SepdMonDraw.cc.
View newest version in sPHENIX GitHub at line 30 of file SepdMonDraw.cc
int SepdMonDraw::MakeCanvas (const std::string & name) protected
Definition at line 35 of file SepdMonDraw.cc.
View newest version in sPHENIX GitHub at line 35 of file SepdMonDraw.cc
References OnlMonClient::GetDisplaySizeX(), OnlMonClient::GetDisplaySizeY(), OnlMonClient::instance(), Pad, TC, transparent, and warning.
Referenced by DrawFifth(), DrawFirst(), DrawFourth(), DrawSecond(), and DrawThird().
int SepdMonDraw::MakeHtml (const std::string & what = "ALL") override virtual
Reimplemented from OnlMonDraw.
Definition at line 780 of file SepdMonDraw.cc.
View newest version in sPHENIX GitHub at line 780 of file SepdMonDraw.cc
References OnlMonClient::CanvasToPng(), Draw(), OnlMonClient::htmlRegisterPage(), OnlMonClient::instance(), TC, and to_string().
int SepdMonDraw::SavePlot (const std::string & what = "ALL", const std::string & type = "png") override virtual
Reimplemented from OnlMonDraw.
Definition at line 757 of file SepdMonDraw.cc.
View newest version in sPHENIX GitHub at line 757 of file SepdMonDraw.cc
References OnlMonClient::CanvasToPng(), Draw(), filename, OnlMonClient::instance(), OnlMonClient::RunNumber(), TC, OnlMonDraw::ThisName, and to_string().
Member Data Documentation
TGraphErrors* SepdMonDraw::gr[2] = {nullptr} protected
Definition at line 40 of file SepdMonDraw.h.
View newest version in sPHENIX GitHub at line 40 of file SepdMonDraw.h
TPad* SepdMonDraw::Pad[18] = {nullptr} protected
Definition at line 38 of file SepdMonDraw.h.
View newest version in sPHENIX GitHub at line 38 of file SepdMonDraw.h
Referenced by DrawFifth(), DrawFirst(), DrawFourth(), DrawSecond(), DrawThird(), and MakeCanvas().
TCanvas* SepdMonDraw::TC[9] = {nullptr} protected
Definition at line 36 of file SepdMonDraw.h.
View newest version in sPHENIX GitHub at line 36 of file SepdMonDraw.h
Referenced by DrawFifth(), DrawFirst(), DrawFourth(), DrawSecond(), DrawThird(), MakeCanvas(), MakeHtml(), and SavePlot().
TPad* SepdMonDraw::transparent[9] = {nullptr} protected
Definition at line 37 of file SepdMonDraw.h.
View newest version in sPHENIX GitHub at line 37 of file SepdMonDraw.h
Referenced by DrawFifth(), DrawFirst(), DrawFourth(), DrawSecond(), DrawThird(), and MakeCanvas().
TPad* SepdMonDraw::warning[18] = {nullptr} protected
Definition at line 39 of file SepdMonDraw.h.
View newest version in sPHENIX GitHub at line 39 of file SepdMonDraw.h
Referenced by DrawFifth(), and MakeCanvas().
The documentation for this class was generated from the following files:
OnlMon/blob/main/subsystems/sepd/SepdMonDraw.h
OnlMon/blob/main/subsystems/sepd/SepdMonDraw.cc