Analysis Software: PayloadDetector Struct Reference
PayloadDetector Struct Reference
#include <acts/blob/sPHENIX/Examples/Detectors/ContextualDetector/include/ActsExamples/ContextualDetector/PayloadDetector.hpp>
Public Types
using DetectorElement = ActsExamples::Contextual::PayloadDetectorElement
using DetectorElementPtr = std::shared_ptr< DetectorElement >
using Decorator = ActsExamples::Contextual::PayloadDecorator
using DetectorStore = std::vector< std::vector< DetectorElementPtr >>
Public Types inherited from ActsExamples::IBaseDetector
using ContextDecorators = std::vector< std::shared_ptr< ActsExamples::IContextDecorator >>
using TrackingGeometryPtr = std::shared_ptr< const Acts::TrackingGeometry >
Public Member Functions
void addOptions (boost::program_options::options_description &opt) const override
std::pair
< ActsExamples::IBaseDetector::TrackingGeometryPtr,
ContextDecorators > finalize (const boost::program_options::variables_map &vm, std::shared_ptr< const Acts::IMaterialDecorator > mdecorator) override
Public Member Functions inherited from ActsExamples::IBaseDetector
virtual ~IBaseDetector ()=default
Public Attributes
DetectorStore detectorStore
The Store of the detector elements (lifetime: job)
Detailed Description
Definition at line 24 of file PayloadDetector.hpp.
View newest version in sPHENIX GitHub at line 24 of file PayloadDetector.hpp
Member Typedef Documentation
using PayloadDetector::Decorator = ActsExamples::Contextual::PayloadDecorator
Definition at line 27 of file PayloadDetector.hpp.
View newest version in sPHENIX GitHub at line 27 of file PayloadDetector.hpp
using PayloadDetector::DetectorElement = ActsExamples::Contextual::PayloadDetectorElement
Definition at line 25 of file PayloadDetector.hpp.
View newest version in sPHENIX GitHub at line 25 of file PayloadDetector.hpp
using PayloadDetector::DetectorElementPtr = std::shared_ptr<DetectorElement>
Definition at line 26 of file PayloadDetector.hpp.
View newest version in sPHENIX GitHub at line 26 of file PayloadDetector.hpp
using PayloadDetector::DetectorStore = std::vector<std::vector<DetectorElementPtr>>
Definition at line 28 of file PayloadDetector.hpp.
View newest version in sPHENIX GitHub at line 28 of file PayloadDetector.hpp
Member Function Documentation
void PayloadDetector::addOptions (boost::program_options::options_description & opt) const override virtual
Add the generic geometry options
Implements ActsExamples::IBaseDetector.
Definition at line 24 of file PayloadDetector.cpp.
View newest version in sPHENIX GitHub at line 24 of file PayloadDetector.cpp
References ActsExamples::Options::addBFieldOptions(), ActsExamples::Options::addGenericGeometryOptions(), and M_PI.
auto PayloadDetector::finalize (const boost::program_options::variables_map & vm, std::shared_ptr< const Acts::IMaterialDecorator > mdecorator) override virtual
return the generic detector - with payload context decorator
Implements ActsExamples::IBaseDetector.
Definition at line 40 of file PayloadDetector.cpp.
View newest version in sPHENIX GitHub at line 40 of file PayloadDetector.cpp
References Acts::getDefaultLogger(), testing::internal::move(), ActsExamples::Contextual::PayloadDecorator::Config::rotationStep, ActsExamples::BField::BFieldScalor::Config::scalor, and ActsExamples::Contextual::PayloadDecorator::Config::trackingGeometry.
Member Data Documentation
DetectorStore PayloadDetector::detectorStore
The Store of the detector elements (lifetime: job)
Definition at line 31 of file PayloadDetector.hpp.
View newest version in sPHENIX GitHub at line 31 of file PayloadDetector.hpp
The documentation for this struct was generated from the following files:
acts/blob/sPHENIX/Examples/Detectors/ContextualDetector/include/ActsExamples/ContextualDetector/PayloadDetector.hpp
acts/blob/sPHENIX/Examples/Detectors/ContextualDetector/src/PayloadDetector.cpp