Analysis Software: ActsExamples::SurfaceSortingAlgorithm Exception Reference
ActsExamples::SurfaceSortingAlgorithm Exception Reference final
#include <acts/blob/sPHENIX/Examples/Algorithms/TrackFitting/include/ActsExamples/TrackFitting/SurfaceSortingAlgorithm.hpp>
Classes
struct Config
Public Types
using HitSimHitsMap = IndexMultimap< Index >
Public Member Functions
SurfaceSortingAlgorithm (Config cfg, Acts::Logging::Level level)
ActsExamples::ProcessCode execute (const AlgorithmContext &ctx) const final
const Config & config () const
Get readonly access to the config parameters.
Public Member Functions inherited from ActsExamples::IAlgorithm
IAlgorithm (std::string name, Acts::Logging::Level level=Acts::Logging::INFO)
std::string name () const override
The algorithm name.
ProcessCode internalExecute (const AlgorithmContext &context) final
ProcessCode initialize () override
Initialize the algorithm.
ProcessCode finalize () override
Finalize the algorithm.
Private Attributes
Config m_cfg
ReadDataHandle
< ProtoTrackContainer > m_inputProtoTracks
ReadDataHandle< SimHitContainer > m_inputSimHits {this, "InputSimHits"}
ReadDataHandle< HitSimHitsMap > m_inputMeasurementSimHitsMap
WriteDataHandle
< ProtoTrackContainer > m_outputProtoTracks
Additional Inherited Members
Protected Member Functions inherited from ActsExamples::IAlgorithm
const Acts::Logger & logger () const
Detailed Description
Definition at line 32 of file SurfaceSortingAlgorithm.hpp.
View newest version in sPHENIX GitHub at line 32 of file SurfaceSortingAlgorithm.hpp
Member Typedef Documentation
using ActsExamples::SurfaceSortingAlgorithm::HitSimHitsMap = IndexMultimap<Index>
Definition at line 34 of file SurfaceSortingAlgorithm.hpp.
View newest version in sPHENIX GitHub at line 34 of file SurfaceSortingAlgorithm.hpp
Constructor & Destructor Documentation
ActsExamples::SurfaceSortingAlgorithm::SurfaceSortingAlgorithm (Config cfg, Acts::Logging::Level level)
Definition at line 25 of file SurfaceSortingAlgorithm.cpp.
View newest version in sPHENIX GitHub at line 25 of file SurfaceSortingAlgorithm.cpp
References ActsExamples::WriteDataHandle< T >::initialize(), ActsExamples::ReadDataHandle< T >::initialize(), ActsExamples::SurfaceSortingAlgorithm::Config::inputMeasurementSimHitsMap, ActsExamples::SurfaceSortingAlgorithm::Config::inputProtoTracks, ActsExamples::SurfaceSortingAlgorithm::Config::inputSimHits, m_cfg, m_inputMeasurementSimHitsMap, m_inputProtoTracks, m_inputSimHits, m_outputProtoTracks, and ActsExamples::SurfaceSortingAlgorithm::Config::outputProtoTracks.
Member Function Documentation
const Config& ActsExamples::SurfaceSortingAlgorithm::config () const inline
Get readonly access to the config parameters.
Definition at line 52 of file SurfaceSortingAlgorithm.hpp.
View newest version in sPHENIX GitHub at line 52 of file SurfaceSortingAlgorithm.hpp
References m_cfg.
ActsExamples::ProcessCode ActsExamples::SurfaceSortingAlgorithm::execute (const AlgorithmContext & context) const final virtual
Execute the algorithm for one event.
This function must be implemented by subclasses.
Map will now be sorted by truth hit time
Implements ActsExamples::IAlgorithm.
Definition at line 48 of file SurfaceSortingAlgorithm.cpp.
View newest version in sPHENIX GitHub at line 48 of file SurfaceSortingAlgorithm.cpp
References testing::internal::move(), SUCCESS, and Acts::Test::time.
Member Data Documentation
Config ActsExamples::SurfaceSortingAlgorithm::m_cfg private
Definition at line 55 of file SurfaceSortingAlgorithm.hpp.
View newest version in sPHENIX GitHub at line 55 of file SurfaceSortingAlgorithm.hpp
Referenced by config(), and SurfaceSortingAlgorithm().
ReadDataHandle<HitSimHitsMap> ActsExamples::SurfaceSortingAlgorithm::m_inputMeasurementSimHitsMap private
Initial value:
{
      this, "InputMeasurementSimHitsMap"}
Definition at line 60 of file SurfaceSortingAlgorithm.hpp.
View newest version in sPHENIX GitHub at line 60 of file SurfaceSortingAlgorithm.hpp
Referenced by SurfaceSortingAlgorithm().
ReadDataHandle<ProtoTrackContainer> ActsExamples::SurfaceSortingAlgorithm::m_inputProtoTracks private
Initial value:
{this,
                                                         "InputProtoTracks"}
Definition at line 57 of file SurfaceSortingAlgorithm.hpp.
View newest version in sPHENIX GitHub at line 57 of file SurfaceSortingAlgorithm.hpp
Referenced by SurfaceSortingAlgorithm().
ReadDataHandle<SimHitContainer> ActsExamples::SurfaceSortingAlgorithm::m_inputSimHits {this, "InputSimHits"} private
Definition at line 59 of file SurfaceSortingAlgorithm.hpp.
View newest version in sPHENIX GitHub at line 59 of file SurfaceSortingAlgorithm.hpp
Referenced by SurfaceSortingAlgorithm().
WriteDataHandle<ProtoTrackContainer> ActsExamples::SurfaceSortingAlgorithm::m_outputProtoTracks private
Initial value:
{this,
                                                           "OutputProtoTracks"}
Definition at line 62 of file SurfaceSortingAlgorithm.hpp.
View newest version in sPHENIX GitHub at line 62 of file SurfaceSortingAlgorithm.hpp
Referenced by SurfaceSortingAlgorithm().
The documentation for this exception was generated from the following files:
acts/blob/sPHENIX/Examples/Algorithms/TrackFitting/include/ActsExamples/TrackFitting/SurfaceSortingAlgorithm.hpp
acts/blob/sPHENIX/Examples/Algorithms/TrackFitting/src/SurfaceSortingAlgorithm.cpp