Analysis Software: Fun4AllDstInputManager Class Reference
Fun4AllDstInputManager Class Reference
#include <coresoftware/blob/master/offline/framework/fun4all/Fun4AllDstInputManager.h>
Public Member Functions
Fun4AllDstInputManager (const std::string &name="DUMMY", const std::string &nodename="DST", const std::string &topnodename="TOP")
~Fun4AllDstInputManager () override
int fileopen (const std::string &filenam) override
int fileclose () override
int run (const int nevents=0) override
int GetSyncObject (SyncObject **mastersync) override
int SyncIt (const SyncObject *mastersync) override
int BranchSelect (const std::string &branch, const int iflag) override
int setBranches () override
virtual int setSyncBranches (PHNodeIOManager *iman)
void Print (const std::string &what="ALL") const override
int PushBackEvents (const int i) override
int HasSyncObject () const override
Public Member Functions inherited from Fun4AllInputManager
~Fun4AllInputManager () override
virtual int ReadInRunNode (PHCompositeNode *)
std::string FileName () const
void FileName (const std::string &fn)
void Print (const std::string &what="ALL") const override
virtual int skip (const int nevt)
virtual int NoSyncPushBackEvents (const int)
int AddFile (const std::string &filename)
int AddListFile (const std::string &filename, const int do_it=0)
int registerSubsystem (SubsysReco *subsystem)
virtual int RejectEvent ()
void Repeat (const int i=-1)
virtual void setSyncManager (Fun4AllSyncManager *master)
virtual int ResetFileList ()
virtual int ResetEvent ()
virtual void SetRunNumber (const int runno)
virtual int RunNumber () const
void AddToFileOpened (const std::string &filename)
std::pair< std::list
< std::string >
::const_iterator, std::list
< std::string >
::const_iterator > FileOpenListBeginEnd ()
std::string InputNode ()
void InputNode (const std::string &innode)
std::string TopNodeName () const
bool FileListEmpty () const
virtual int IsOpen () const
virtual int SkipForThisManager (const int)
virtual std::string GetString (const std::string &) const
const std::list< std::string > GetFileList () const
const std::list< std::string > GetFileOpenedList () const
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Protected Member Functions
int ReadNextEventSyncObject ()
void ReadRunTTree (const int i)
void IManager (PHNodeIOManager *iman)
PHNodeIOManager * IManager ()
void runNode (PHCompositeNode *node)
PHCompositeNode * runNode ()
void runNodeCopy (PHCompositeNode *node)
PHCompositeNode * runNodeCopy ()
void runNodeSum (PHCompositeNode *node)
PHCompositeNode * runNodeSum ()
std::string RunNodeName () const
Protected Member Functions inherited from Fun4AllInputManager
Fun4AllInputManager (const std::string &name="DUMMY", const std::string &nodename="DST", const std::string &topnodename="TOP")
void UpdateFileList ()
int OpenNextFile ()
void IsOpen (const int i)
Fun4AllSyncManager * MySyncManager ()
Protected Member Functions inherited from Fun4AllBase
Fun4AllBase (const std::string &name="NONAME")
Protected Attributes
std::string fullfilename
Private Attributes
int m_ReadRunTTree = 1
int events_total = 0
int events_thisfile = 0
int events_skipped_during_sync = 0
int m_HaveSyncObject = 0
std::map< const std::string, int > branchread
std::string syncbranchname
PHCompositeNode * dstNode = nullptr
PHCompositeNode * m_RunNode = nullptr
PHCompositeNode * m_RunNodeCopy = nullptr
PHCompositeNode * m_RunNodeSum = nullptr
PHNodeIOManager * m_IManager = nullptr
SyncObject * syncobject = nullptr
std::string RunNode = "RUN"
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = std::numeric_limits<int>::max() - 10
}
Detailed Description
Definition at line 15 of file Fun4AllDstInputManager.h.
View newest version in sPHENIX GitHub at line 15 of file Fun4AllDstInputManager.h
Constructor & Destructor Documentation
Fun4AllDstInputManager::Fun4AllDstInputManager (const std::string & name = "DUMMY", const std::string & nodename = "DST", const std::string & topnodename = "TOP")
Definition at line 36 of file Fun4AllDstInputManager.cc.
View newest version in sPHENIX GitHub at line 36 of file Fun4AllDstInputManager.cc
Fun4AllDstInputManager::~Fun4AllDstInputManager () override
Definition at line 42 of file Fun4AllDstInputManager.cc.
View newest version in sPHENIX GitHub at line 42 of file Fun4AllDstInputManager.cc
References m_IManager, and m_RunNodeSum.
Member Function Documentation
int Fun4AllDstInputManager::BranchSelect (const std::string & branch, const int iflag) override virtual
Reimplemented from Fun4AllInputManager.
Definition at line 518 of file Fun4AllDstInputManager.cc.
View newest version in sPHENIX GitHub at line 518 of file Fun4AllDstInputManager.cc
References branchread, Fun4AllInputManager::IsOpen(), and Fun4AllBase::Verbosity().
int Fun4AllDstInputManager::fileclose () override virtual
Reimplemented from Fun4AllInputManager.
Definition at line 220 of file Fun4AllDstInputManager.cc.
View newest version in sPHENIX GitHub at line 220 of file Fun4AllDstInputManager.cc
References Fun4AllInputManager::IsOpen(), m_HaveSyncObject, m_IManager, Fun4AllBase::Name(), and Fun4AllInputManager::UpdateFileList().
Referenced by fileopen(), Fun4AllRunNodeInputManager::fileopen(), ReadNextEventSyncObject(), run(), and SyncIt().
int Fun4AllDstInputManager::fileopen (const std::string & filenam) override virtual
Reimplemented from Fun4AllInputManager.
Reimplemented in Fun4AllRunNodeInputManager.
Definition at line 49 of file Fun4AllDstInputManager.cc.
View newest version in sPHENIX GitHub at line 49 of file Fun4AllDstInputManager.cc
References Fun4AllInputManager::AddToFileOpened(), dstNode, events_thisfile, fileclose(), Fun4AllInputManager::FileName(), PHNodeIterator::forEach(), fullfilename, RunHeader::get_RunNumber(), PHNode::getName(), Fun4AllServer::getNode(), Fun4AllInputManager::InputNode(), Fun4AllServer::instance(), PHNodeIOManager::isFunctional(), Fun4AllInputManager::IsOpen(), FROG::location(), m_HaveSyncObject, m_IManager, m_ReadRunTTree, m_RunNode, m_RunNodeCopy, m_RunNodeSum, Fun4AllBase::Name(), PHNodeIOManager::NodeExist(), PHReadOnly, PHRunTree, PHWHERE, PHNodeIOManager::print(), PHNodeIOManager::read(), PHNodeIntegrate::RunNode(), RunNode, PHNodeIntegrate::RunSumNode(), setBranches(), Fun4AllInputManager::SetRunNumber(), Fun4AllInputManager::TopNodeName(), and Fun4AllBase::Verbosity().
int Fun4AllDstInputManager::GetSyncObject (SyncObject ** mastersync) override virtual
Reimplemented from Fun4AllInputManager.
Reimplemented in Fun4AllRunNodeInputManager, and Fun4AllNoSyncDstInputManager.
Definition at line 235 of file Fun4AllDstInputManager.cc.
View newest version in sPHENIX GitHub at line 235 of file Fun4AllDstInputManager.cc
References assert, SyncObject::CloneMe(), Fun4AllReturnCodes::SYNC_OK, and syncobject.
int Fun4AllDstInputManager::HasSyncObject () const override virtual
Reimplemented from Fun4AllInputManager.
Reimplemented in Fun4AllNoSyncDstInputManager, and Fun4AllRunNodeInputManager.
Definition at line 649 of file Fun4AllDstInputManager.cc.
View newest version in sPHENIX GitHub at line 649 of file Fun4AllDstInputManager.cc
References Fun4AllInputManager::IsOpen(), m_HaveSyncObject, and PHWHERE.
void Fun4AllDstInputManager::IManager (PHNodeIOManager * iman) inline protected
Definition at line 35 of file Fun4AllDstInputManager.h.
View newest version in sPHENIX GitHub at line 35 of file Fun4AllDstInputManager.h
References m_IManager.
PHNodeIOManager* Fun4AllDstInputManager::IManager () inline protected
Definition at line 36 of file Fun4AllDstInputManager.h.
View newest version in sPHENIX GitHub at line 36 of file Fun4AllDstInputManager.h
References m_IManager.
Referenced by Fun4AllRunNodeInputManager::fileopen().
void Fun4AllDstInputManager::Print (const std::string & what = "ALL") const override virtual
Print out some info about this module.
Parameters
what can be used to specify what to print exactly.
Reimplemented from Fun4AllBase.
Definition at line 599 of file Fun4AllDstInputManager.cc.
View newest version in sPHENIX GitHub at line 599 of file Fun4AllDstInputManager.cc
References branchread, m_IManager, Fun4AllBase::Name(), Fun4AllInputManager::Print(), and PHNodeIOManager::print().
int Fun4AllDstInputManager::PushBackEvents (const int i) override virtual
Reimplemented from Fun4AllInputManager.
Reimplemented in Fun4AllRunNodeInputManager.
Definition at line 635 of file Fun4AllDstInputManager.cc.
View newest version in sPHENIX GitHub at line 635 of file Fun4AllDstInputManager.cc
References PHIOManager::getEventNumber(), i, m_IManager, Fun4AllBase::Name(), PHWHERE, and PHIOManager::setEventNumber().
Referenced by Fun4AllNoSyncDstInputManager::NoSyncPushBackEvents(), Fun4AllNoSyncDstInputManager::SkipForThisManager(), and SyncIt().
int Fun4AllDstInputManager::ReadNextEventSyncObject () protected
Definition at line 414 of file Fun4AllDstInputManager.cc.
View newest version in sPHENIX GitHub at line 414 of file Fun4AllDstInputManager.cc
References phooldefs::branchpathdelim, dstNode, fileclose(), PHNodeIOManager::GetBranchMap(), PHIOManager::getEventNumber(), m_IManager, Fun4AllBase::Name(), Fun4AllInputManager::OpenNextFile(), PHWHERE, PHNodeIOManager::read(), PHNodeIOManager::readSpecific(), PHIOManager::setEventNumber(), Fun4AllReturnCodes::SYNC_FAIL, syncbranchname, and Fun4AllBase::Verbosity().
Referenced by SyncIt().
void Fun4AllDstInputManager::ReadRunTTree (const int i) inline protected
Definition at line 34 of file Fun4AllDstInputManager.h.
View newest version in sPHENIX GitHub at line 34 of file Fun4AllDstInputManager.h
References i, and m_ReadRunTTree.
Referenced by Fun4AllNoSyncDstInputManager::NoRunTTree().
int Fun4AllDstInputManager::run (const int nevents = 0) override virtual
Reimplemented from Fun4AllInputManager.
Reimplemented in Fun4AllRunNodeInputManager.
Definition at line 160 of file Fun4AllDstInputManager.cc.
View newest version in sPHENIX GitHub at line 160 of file Fun4AllDstInputManager.cc
References dstNode, dummy, Fun4AllReturnCodes::EVENT_OK, events_thisfile, events_total, fileclose(), Fun4AllInputManager::FileListEmpty(), Fun4AllInputManager::IsOpen(), m_IManager, Fun4AllBase::Name(), Fun4AllInputManager::OpenNextFile(), PHNodeIOManager::read(), Fun4AllInputManager::RejectEvent(), syncobject, and Fun4AllBase::Verbosity().
void Fun4AllDstInputManager::runNode (PHCompositeNode * node) inline protected
Definition at line 37 of file Fun4AllDstInputManager.h.
View newest version in sPHENIX GitHub at line 37 of file Fun4AllDstInputManager.h
References m_RunNode.
PHCompositeNode* Fun4AllDstInputManager::runNode () inline protected
Definition at line 38 of file Fun4AllDstInputManager.h.
View newest version in sPHENIX GitHub at line 38 of file Fun4AllDstInputManager.h
References m_RunNode.
Referenced by Fun4AllRunNodeInputManager::fileopen().
void Fun4AllDstInputManager::runNodeCopy (PHCompositeNode * node) inline protected
Definition at line 39 of file Fun4AllDstInputManager.h.
View newest version in sPHENIX GitHub at line 39 of file Fun4AllDstInputManager.h
References m_RunNodeCopy.
PHCompositeNode* Fun4AllDstInputManager::runNodeCopy () inline protected
Definition at line 40 of file Fun4AllDstInputManager.h.
View newest version in sPHENIX GitHub at line 40 of file Fun4AllDstInputManager.h
References m_RunNodeCopy.
std::string Fun4AllDstInputManager::RunNodeName () const inline protected
Definition at line 43 of file Fun4AllDstInputManager.h.
View newest version in sPHENIX GitHub at line 43 of file Fun4AllDstInputManager.h
References RunNode.
Referenced by Fun4AllRunNodeInputManager::fileopen().
void Fun4AllDstInputManager::runNodeSum (PHCompositeNode * node) inline protected
Definition at line 41 of file Fun4AllDstInputManager.h.
View newest version in sPHENIX GitHub at line 41 of file Fun4AllDstInputManager.h
References m_RunNodeSum.
PHCompositeNode* Fun4AllDstInputManager::runNodeSum () inline protected
Definition at line 42 of file Fun4AllDstInputManager.h.
View newest version in sPHENIX GitHub at line 42 of file Fun4AllDstInputManager.h
References m_RunNodeSum.
int Fun4AllDstInputManager::setBranches () override virtual
Reimplemented from Fun4AllInputManager.
Definition at line 560 of file Fun4AllDstInputManager.cc.
View newest version in sPHENIX GitHub at line 560 of file Fun4AllDstInputManager.cc
References branchread, m_IManager, Fun4AllBase::Name(), PHWHERE, PHNodeIOManager::selectObjectToRead(), setSyncBranches(), and Fun4AllBase::Verbosity().
Referenced by fileopen().
int Fun4AllDstInputManager::setSyncBranches (PHNodeIOManager * iman) virtual
Reimplemented in Fun4AllRunNodeInputManager, and Fun4AllNoSyncDstInputManager.
Definition at line 589 of file Fun4AllDstInputManager.cc.
View newest version in sPHENIX GitHub at line 589 of file Fun4AllDstInputManager.cc
References i, and PHNodeIOManager::selectObjectToRead().
Referenced by setBranches().
int Fun4AllDstInputManager::SyncIt (const SyncObject * mastersync) override virtual
Reimplemented from Fun4AllInputManager.
Reimplemented in Fun4AllRunNodeInputManager, and Fun4AllNoSyncDstInputManager.
Definition at line 256 of file Fun4AllDstInputManager.cc.
View newest version in sPHENIX GitHub at line 256 of file Fun4AllDstInputManager.cc
References SyncObject::Different(), dstNode, dummy, SyncObject::EventCounter(), SyncObject::EventNumber(), events_skipped_during_sync, fileclose(), SyncObject::identify(), m_IManager, Fun4AllBase::Name(), PHWHERE, PushBackEvents(), PHNodeIOManager::read(), ReadNextEventSyncObject(), SyncObject::RunNumber(), SyncObject::SegmentNumber(), Fun4AllReturnCodes::SYNC_FAIL, Fun4AllReturnCodes::SYNC_OK, syncobject, and Fun4AllBase::Verbosity().
Member Data Documentation
std::map<const std::string, int> Fun4AllDstInputManager::branchread private
Definition at line 52 of file Fun4AllDstInputManager.h.
View newest version in sPHENIX GitHub at line 52 of file Fun4AllDstInputManager.h
Referenced by BranchSelect(), Print(), and setBranches().
PHCompositeNode* Fun4AllDstInputManager::dstNode = nullptr private
Definition at line 54 of file Fun4AllDstInputManager.h.
View newest version in sPHENIX GitHub at line 54 of file Fun4AllDstInputManager.h
Referenced by fileopen(), ReadNextEventSyncObject(), run(), and SyncIt().
int Fun4AllDstInputManager::events_skipped_during_sync = 0 private
Definition at line 50 of file Fun4AllDstInputManager.h.
View newest version in sPHENIX GitHub at line 50 of file Fun4AllDstInputManager.h
Referenced by SyncIt().
int Fun4AllDstInputManager::events_thisfile = 0 private
Definition at line 49 of file Fun4AllDstInputManager.h.
View newest version in sPHENIX GitHub at line 49 of file Fun4AllDstInputManager.h
Referenced by fileopen(), and run().
int Fun4AllDstInputManager::events_total = 0 private
Definition at line 48 of file Fun4AllDstInputManager.h.
View newest version in sPHENIX GitHub at line 48 of file Fun4AllDstInputManager.h
Referenced by run().
std::string Fun4AllDstInputManager::fullfilename protected
Definition at line 44 of file Fun4AllDstInputManager.h.
View newest version in sPHENIX GitHub at line 44 of file Fun4AllDstInputManager.h
Referenced by fileopen(), and Fun4AllRunNodeInputManager::fileopen().
int Fun4AllDstInputManager::m_HaveSyncObject = 0 private
Definition at line 51 of file Fun4AllDstInputManager.h.
View newest version in sPHENIX GitHub at line 51 of file Fun4AllDstInputManager.h
Referenced by fileclose(), fileopen(), and HasSyncObject().
PHNodeIOManager* Fun4AllDstInputManager::m_IManager = nullptr private
Definition at line 58 of file Fun4AllDstInputManager.h.
View newest version in sPHENIX GitHub at line 58 of file Fun4AllDstInputManager.h
Referenced by fileclose(), fileopen(), IManager(), Print(), PushBackEvents(), ReadNextEventSyncObject(), run(), setBranches(), SyncIt(), and ~Fun4AllDstInputManager().
int Fun4AllDstInputManager::m_ReadRunTTree = 1 private
Definition at line 47 of file Fun4AllDstInputManager.h.
View newest version in sPHENIX GitHub at line 47 of file Fun4AllDstInputManager.h
Referenced by fileopen(), and ReadRunTTree().
PHCompositeNode* Fun4AllDstInputManager::m_RunNode = nullptr private
Definition at line 55 of file Fun4AllDstInputManager.h.
View newest version in sPHENIX GitHub at line 55 of file Fun4AllDstInputManager.h
Referenced by fileopen(), and runNode().
PHCompositeNode* Fun4AllDstInputManager::m_RunNodeCopy = nullptr private
Definition at line 56 of file Fun4AllDstInputManager.h.
View newest version in sPHENIX GitHub at line 56 of file Fun4AllDstInputManager.h
Referenced by fileopen(), and runNodeCopy().
PHCompositeNode* Fun4AllDstInputManager::m_RunNodeSum = nullptr private
Definition at line 57 of file Fun4AllDstInputManager.h.
View newest version in sPHENIX GitHub at line 57 of file Fun4AllDstInputManager.h
Referenced by fileopen(), runNodeSum(), and ~Fun4AllDstInputManager().
std::string Fun4AllDstInputManager::RunNode = "RUN" private
Definition at line 60 of file Fun4AllDstInputManager.h.
View newest version in sPHENIX GitHub at line 60 of file Fun4AllDstInputManager.h
Referenced by fileopen(), and RunNodeName().
std::string Fun4AllDstInputManager::syncbranchname private
Definition at line 53 of file Fun4AllDstInputManager.h.
View newest version in sPHENIX GitHub at line 53 of file Fun4AllDstInputManager.h
Referenced by ReadNextEventSyncObject().
SyncObject* Fun4AllDstInputManager::syncobject = nullptr private
Definition at line 59 of file Fun4AllDstInputManager.h.
View newest version in sPHENIX GitHub at line 59 of file Fun4AllDstInputManager.h
Referenced by GetSyncObject(), run(), and SyncIt().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/framework/fun4all/Fun4AllDstInputManager.h
coresoftware/blob/master/offline/framework/fun4all/Fun4AllDstInputManager.cc