Analysis Software: Acts::VectorMultiTrajectory Exception Reference
Acts::VectorMultiTrajectory Exception Reference final
#include <acts/blob/sPHENIX/Core/include/Acts/EventData/VectorMultiTrajectory.hpp>
Public Member Functions
VectorMultiTrajectory ()=default
VectorMultiTrajectory (const VectorMultiTrajectory &other)
void reserve (std::size_t n)
void shareFrom_impl (IndexType iself, IndexType iother, TrackStatePropMask shareSource, TrackStatePropMask shareTarget)
void unset_impl (TrackStatePropMask target, IndexType istate)
constexpr bool has_impl (HashedString key, IndexType istate) const
IndexType size_impl () const
void clear_impl ()
std::any component_impl (HashedString key, IndexType istate)
std::any component_impl (HashedString key, IndexType istate) const
template<typename T >
constexpr void addColumn_impl (const std::string &key)
constexpr bool hasColumn_impl (HashedString key) const
void allocateCalibrated_impl (IndexType istate, size_t measdim)
void setUncalibratedSourceLink_impl (IndexType istate, SourceLink sourceLink)
void setReferenceSurface_impl (IndexType istate, std::shared_ptr< const Surface > surface)
Public Member Functions inherited from Acts::detail_vmt::VectorMultiTrajectoryBase
template<typename T >
Statistics statistics (T &instance) const
IndexType calibratedSize_impl (IndexType istate) const
SourceLink getUncalibratedSourceLink_impl (IndexType istate) const
const Surface * referenceSurface_impl (IndexType istate) const
Public Member Functions inherited from Acts::MultiTrajectory< VectorMultiTrajectory >
ConstTrackStateProxy getTrackState (IndexType istate) const
TrackStateProxy getTrackState (IndexType istate)
void visitBackwards (IndexType iendpoint, F &&callable) const
auto reverseTrackStateRange (IndexType iendpoint) const
auto reverseTrackStateRange (IndexType iendpoint)
auto forwardTrackStateRange (IndexType istartpoint) const
auto forwardTrackStateRange (IndexType istartpoint)
void applyBackwards (IndexType iendpoint, F &&callable)
auto && convertToReadOnly () const
constexpr void clear ()
Clear the MultiTrajectory. Leaves the underlying storage untouched.
constexpr IndexType size () const
Returns the number of track states contained.
constexpr IndexType addTrackState (TrackStatePropMask mask=TrackStatePropMask::All, IndexType iprevious=kInvalid)
constexpr void addColumn (const std::string &key)
constexpr bool hasColumn (HashedString key) const
Private Attributes
friend MultiTrajectory< VectorMultiTrajectory >
Additional Inherited Members
Public Types inherited from Acts::MultiTrajectory< VectorMultiTrajectory >
using Derived = VectorMultiTrajectory
using ConstTrackStateProxy = detail_lt::TrackStateProxy< Derived, MeasurementSizeMax, true >
using TrackStateProxy = detail_lt::TrackStateProxy< Derived, MeasurementSizeMax, false >
using IndexType = typename TrackStateProxy::IndexType
Static Public Attributes inherited from Acts::MultiTrajectory< VectorMultiTrajectory >
static constexpr bool ReadOnly
static constexpr unsigned int MeasurementSizeMax
static constexpr IndexType kInvalid
Protected Member Functions inherited from Acts::detail_vmt::VectorMultiTrajectoryBase
VectorMultiTrajectoryBase ()=default
VectorMultiTrajectoryBase (const VectorMultiTrajectoryBase &other)
VectorMultiTrajectoryBase (VectorMultiTrajectoryBase &&other)=default
Protected Member Functions inherited from Acts::MultiTrajectory< VectorMultiTrajectory >
MultiTrajectory ()=default
constexpr bool has (HashedString key, IndexType istate) const
constexpr bool has (IndexType istate) const
constexpr
TrackStateProxy::Parameters parameters (IndexType parIdx)
constexpr
ConstTrackStateProxy::Parameters parameters (IndexType parIdx) const
constexpr
TrackStateProxy::Covariance covariance (IndexType covIdx)
constexpr
ConstTrackStateProxy::Covariance covariance (IndexType covIdx) const
constexpr
TrackStateProxy::Covariance jacobian (IndexType jacIdx)
constexpr
ConstTrackStateProxy::Covariance jacobian (IndexType jacIdx) const
constexpr
TrackStateProxy::template
Measurement< measdim > measurement (IndexType measIdx)
constexpr
ConstTrackStateProxy::template
Measurement< measdim > measurement (IndexType measIdx) const
constexpr
TrackStateProxy::template
MeasurementCovariance< measdim > measurementCovariance (IndexType covIdx)
constexpr
ConstTrackStateProxy::template
MeasurementCovariance< measdim > measurementCovariance (IndexType covIdx) const
IndexType calibratedSize (IndexType istate) const
constexpr void shareFrom (IndexType iself, IndexType iother, TrackStatePropMask shareSource, TrackStatePropMask shareTarget)
constexpr void unset (TrackStatePropMask target, IndexType istate)
constexpr T & component (IndexType istate)
constexpr T & component (HashedString key, IndexType istate)
constexpr const T & component (IndexType istate) const
constexpr const T & component (HashedString key, IndexType istate) const
void allocateCalibrated (IndexType istate, size_t measdim)
void setUncalibratedSourceLink (IndexType istate, SourceLink sourceLink)
SourceLink getUncalibratedSourceLink (IndexType istate) const
const Surface * referenceSurface (IndexType istate) const
void setReferenceSurface (IndexType istate, std::shared_ptr< const Surface > surface)
Static Protected Member Functions inherited from Acts::detail_vmt::VectorMultiTrajectoryBase
template<typename T >
static constexpr bool has_impl (T &instance, HashedString key, IndexType istate)
template<bool EnsureConst, typename T >
static std::any component_impl (T &instance, HashedString key, IndexType istate)
template<typename T >
static constexpr bool hasColumn_impl (T &instance, HashedString key)
Protected Attributes inherited from Acts::detail_vmt::VectorMultiTrajectoryBase
m_previous {other.m_previous}
m_next {other.m_next}
m_params {other.m_params}
m_cov {other.m_cov}
m_meas {other.m_meas}
m_measOffset {other.m_measOffset}
m_measCov {other.m_measCov}
m_measCovOffset {other.m_measCovOffset}
m_jac {other.m_jac}
m_sourceLinks {other.m_sourceLinks}
m_projectors {other.m_projectors}
m_referenceSurfaces
std::vector< IndexData > m_index
index to map track states to the corresponding
std::vector< IndexType > m_previous
std::vector< IndexType > m_next
std::vector< typename
detail_lt::Types< eBoundSize >
::Coefficients > m_params
std::vector< typename
detail_lt::Types< eBoundSize >
::Covariance > m_cov
std::vector< double > m_meas
std::vector
< MultiTrajectoryTraits::IndexType > m_measOffset
std::vector< double > m_measCov
std::vector
< MultiTrajectoryTraits::IndexType > m_measCovOffset
std::vector< typename
detail_lt::Types< eBoundSize >
::Covariance > m_jac
std::vector< std::optional
< SourceLink > > m_sourceLinks
std::vector< ProjectorBitset > m_projectors
std::vector< std::shared_ptr
< const Surface > > m_referenceSurfaces
std::unordered_map
< HashedString,
std::unique_ptr
< detail::DynamicColumnBase > > m_dynamic
Detailed Description
Definition at line 341 of file VectorMultiTrajectory.hpp.
View newest version in sPHENIX GitHub at line 341 of file VectorMultiTrajectory.hpp
Constructor & Destructor Documentation
Acts::VectorMultiTrajectory::VectorMultiTrajectory () default
Acts::VectorMultiTrajectory::VectorMultiTrajectory (const VectorMultiTrajectory & other) inline
Definition at line 350 of file VectorMultiTrajectory.hpp.
View newest version in sPHENIX GitHub at line 350 of file VectorMultiTrajectory.hpp
Member Function Documentation
template<typename T > constexpr void Acts::VectorMultiTrajectory::addColumn_impl (const std::string & key) inline
Definition at line 448 of file VectorMultiTrajectory.hpp.
View newest version in sPHENIX GitHub at line 448 of file VectorMultiTrajectory.hpp
References Acts::hashString(), and Acts::detail_vmt::VectorMultiTrajectoryBase::m_dynamic.
void Acts::VectorMultiTrajectory::allocateCalibrated_impl (IndexType istate, size_t measdim) inline
Definition at line 457 of file VectorMultiTrajectory.hpp.
View newest version in sPHENIX GitHub at line 457 of file VectorMultiTrajectory.hpp
References Acts::eBoundSize, Acts::detail_vmt::kInvalid, Acts::detail_vmt::VectorMultiTrajectoryBase::m_index, Acts::detail_vmt::VectorMultiTrajectoryBase::m_meas, Acts::detail_vmt::VectorMultiTrajectoryBase::m_measCov, Acts::detail_vmt::VectorMultiTrajectoryBase::m_measCovOffset, Acts::detail_vmt::VectorMultiTrajectoryBase::m_measOffset, and throw_assert.
void Acts::VectorMultiTrajectory::clear_impl ()
Definition at line 170 of file VectorMultiTrajectory.cpp.
View newest version in sPHENIX GitHub at line 170 of file VectorMultiTrajectory.cpp
References Acts::detail_vmt::VectorMultiTrajectoryBase::m_cov, Acts::detail_vmt::VectorMultiTrajectoryBase::m_index, Acts::detail_vmt::VectorMultiTrajectoryBase::m_jac, Acts::detail_vmt::VectorMultiTrajectoryBase::m_meas, Acts::detail_vmt::VectorMultiTrajectoryBase::m_measCov, Acts::detail_vmt::VectorMultiTrajectoryBase::m_measCovOffset, Acts::detail_vmt::VectorMultiTrajectoryBase::m_measOffset, Acts::detail_vmt::VectorMultiTrajectoryBase::m_next, Acts::detail_vmt::VectorMultiTrajectoryBase::m_params, Acts::detail_vmt::VectorMultiTrajectoryBase::m_previous, Acts::detail_vmt::VectorMultiTrajectoryBase::m_projectors, Acts::detail_vmt::VectorMultiTrajectoryBase::m_referenceSurfaces, Acts::detail_vmt::VectorMultiTrajectoryBase::m_sourceLinks, and vec.
std::any Acts::VectorMultiTrajectory::component_impl (HashedString key, IndexType istate) inline
Definition at line 437 of file VectorMultiTrajectory.hpp.
View newest version in sPHENIX GitHub at line 437 of file VectorMultiTrajectory.hpp
std::any Acts::VectorMultiTrajectory::component_impl (HashedString key, IndexType istate) const inline
Definition at line 442 of file VectorMultiTrajectory.hpp.
View newest version in sPHENIX GitHub at line 442 of file VectorMultiTrajectory.hpp
constexpr bool Acts::VectorMultiTrajectory::has_impl (HashedString key, IndexType istate) const inline
Definition at line 427 of file VectorMultiTrajectory.hpp.
View newest version in sPHENIX GitHub at line 427 of file VectorMultiTrajectory.hpp
References Acts::detail_vmt::VectorMultiTrajectoryBase::has_impl().
constexpr bool Acts::VectorMultiTrajectory::hasColumn_impl (HashedString key) const inline
Definition at line 453 of file VectorMultiTrajectory.hpp.
View newest version in sPHENIX GitHub at line 453 of file VectorMultiTrajectory.hpp
References Acts::detail_vmt::VectorMultiTrajectoryBase::hasColumn_impl().
void Acts::VectorMultiTrajectory::reserve (std::size_t n)
Definition at line 227 of file VectorMultiTrajectory.cpp.
View newest version in sPHENIX GitHub at line 227 of file VectorMultiTrajectory.cpp
References Acts::detail_vmt::VectorMultiTrajectoryBase::m_cov, Acts::detail_vmt::VectorMultiTrajectoryBase::m_index, Acts::detail_vmt::VectorMultiTrajectoryBase::m_jac, Acts::detail_vmt::VectorMultiTrajectoryBase::m_meas, Acts::detail_vmt::VectorMultiTrajectoryBase::m_measCov, Acts::detail_vmt::VectorMultiTrajectoryBase::m_measCovOffset, Acts::detail_vmt::VectorMultiTrajectoryBase::m_measOffset, Acts::detail_vmt::VectorMultiTrajectoryBase::m_next, Acts::detail_vmt::VectorMultiTrajectoryBase::m_params, Acts::detail_vmt::VectorMultiTrajectoryBase::m_previous, Acts::detail_vmt::VectorMultiTrajectoryBase::m_projectors, Acts::detail_vmt::VectorMultiTrajectoryBase::m_referenceSurfaces, Acts::detail_vmt::VectorMultiTrajectoryBase::m_sourceLinks, and vec.
void Acts::VectorMultiTrajectory::setReferenceSurface_impl (IndexType istate, std::shared_ptr< const Surface > surface) inline
Definition at line 480 of file VectorMultiTrajectory.hpp.
View newest version in sPHENIX GitHub at line 480 of file VectorMultiTrajectory.hpp
References Acts::detail_vmt::VectorMultiTrajectoryBase::m_referenceSurfaces, and testing::internal::move().
void Acts::VectorMultiTrajectory::setUncalibratedSourceLink_impl (IndexType istate, SourceLink sourceLink) inline
Definition at line 476 of file VectorMultiTrajectory.hpp.
View newest version in sPHENIX GitHub at line 476 of file VectorMultiTrajectory.hpp
References Acts::detail_vmt::VectorMultiTrajectoryBase::m_index, Acts::detail_vmt::VectorMultiTrajectoryBase::m_sourceLinks, and testing::internal::move().
void Acts::VectorMultiTrajectory::shareFrom_impl (IndexType iself, IndexType iother, TrackStatePropMask shareSource, TrackStatePropMask shareTarget)
Definition at line 90 of file VectorMultiTrajectory.cpp.
View newest version in sPHENIX GitHub at line 90 of file VectorMultiTrajectory.cpp
References ACTS_CHECK_BIT, assert, Acts::MultiTrajectory< VectorMultiTrajectory >::getTrackState(), Acts::detail_vmt::VectorMultiTrajectoryBase::IndexData::ifiltered, Acts::detail_vmt::VectorMultiTrajectoryBase::IndexData::ijacobian, Acts::detail_vmt::VectorMultiTrajectoryBase::IndexData::ipredicted, Acts::detail_vmt::VectorMultiTrajectoryBase::IndexData::ismoothed, Acts::MultiTrajectory< VectorMultiTrajectory >::kInvalid, and Acts::detail_vmt::VectorMultiTrajectoryBase::m_index.
IndexType Acts::VectorMultiTrajectory::size_impl () const inline
Definition at line 431 of file VectorMultiTrajectory.hpp.
View newest version in sPHENIX GitHub at line 431 of file VectorMultiTrajectory.hpp
References Acts::detail_vmt::VectorMultiTrajectoryBase::m_index.
void Acts::VectorMultiTrajectory::unset_impl (TrackStatePropMask target, IndexType istate)
Definition at line 144 of file VectorMultiTrajectory.cpp.
View newest version in sPHENIX GitHub at line 144 of file VectorMultiTrajectory.cpp
References Acts::MultiTrajectory< VectorMultiTrajectory >::kInvalid, Acts::detail_vmt::VectorMultiTrajectoryBase::m_index, Acts::detail_vmt::VectorMultiTrajectoryBase::m_measCovOffset, and Acts::detail_vmt::VectorMultiTrajectoryBase::m_measOffset.
Member Data Documentation
friend Acts::VectorMultiTrajectory::MultiTrajectory< VectorMultiTrajectory > private
Definition at line 345 of file VectorMultiTrajectory.hpp.
View newest version in sPHENIX GitHub at line 345 of file VectorMultiTrajectory.hpp
The documentation for this exception was generated from the following files:
acts/blob/sPHENIX/Core/include/Acts/EventData/VectorMultiTrajectory.hpp
acts/blob/sPHENIX/Core/src/EventData/VectorMultiTrajectory.cpp