Analysis Software: common Namespace Reference
common Namespace Reference
Functions
def getOpenDataDetectorDirectory
def GetCommandOutput
def GetSvnInfo
def GetSvnTrunk
def IsInGTestSvn
def IsInGMockSvn
Variables
string __author__ 'wan@google.com (Zhanyong Wan)'
tuple _SVN_INFO_URL_RE re.compile(r'^URL: https://(\w+)\.googlecode\.com/svn(.*)')
Function Documentation
def common.GetCommandOutput (command)
Runs the shell command and returns its stdout as a list of lines.
Definition at line 46 of file common.py.
View newest version in sPHENIX GitHub at line 46 of file common.py
Referenced by GetSvnInfo().
def common.getOpenDataDetectorDirectory ()
Returns path to ODD files
Located here so that the sources location can be obtained. The ODD files are not necessarily installed.
Definition at line 4 of file common.py.
View newest version in sPHENIX GitHub at line 4 of file common.py
Referenced by conftest._do_material_recording(), conftest.detector_config(), material_recording.main(), physmon_common.makeSetup(), event_recording.runEventRecording(), geant4.runGeant4(), geant4_parallel.runGeant4EventRange(), material_mapping_optimisation.runMaterialMappingVariance(), test_reader.test_edm4hep_simhit_reader(), test_examples.test_full_chain_odd_example(), test_examples.test_full_chain_odd_example_pythia_geant4(), test_examples.test_geant4(), test_writer.test_json_material_writer(), test_examples.test_material_mapping(), test_examples.test_ML_Ambiguity_Solver(), test_detectors.test_odd(), test_writer.test_root_material_writer(), and test_examples.test_volume_material_mapping().
def common.GetSvnInfo ()
Returns the project name and the current SVN workspace's root path.
Definition at line 55 of file common.py.
View newest version in sPHENIX GitHub at line 55 of file common.py
References GetCommandOutput().
Referenced by release_docs.WikiBrancher.__init__(), GetSvnTrunk(), IsInGMockSvn(), and IsInGTestSvn().
def common.GetSvnTrunk ()
Returns the current SVN workspace's trunk root path.
Definition at line 69 of file common.py.
View newest version in sPHENIX GitHub at line 69 of file common.py
References GetSvnInfo().
def common.IsInGMockSvn ()
Definition at line 81 of file common.py.
View newest version in sPHENIX GitHub at line 81 of file common.py
References GetSvnInfo().
def common.IsInGTestSvn ()
Definition at line 76 of file common.py.
View newest version in sPHENIX GitHub at line 76 of file common.py
References GetSvnInfo().
Variable Documentation
string common.__author__ 'wan@google.com (Zhanyong Wan)'
Definition at line 31 of file common.py.
View newest version in sPHENIX GitHub at line 31 of file common.py
tuple common._SVN_INFO_URL_RE re.compile(r'^URL: https://(\w+)\.googlecode\.com/svn(.*)')
Definition at line 43 of file common.py.
View newest version in sPHENIX GitHub at line 43 of file common.py