Analysis Software: SelectorWorker Class Reference
SelectorWorker Class Reference abstract
#include <JETSCAPE/blob/main/external_packages/fjcore.hh>
Public Member Functions
virtual ~SelectorWorker ()
virtual bool pass (const PseudoJet &jet) const =0
virtual void terminator (std::vector< const PseudoJet * > &jets) const
virtual bool applies_jet_by_jet () const
virtual std::string description () const
virtual bool takes_reference () const
virtual void set_reference (const PseudoJet &)
virtual SelectorWorker * copy ()
virtual void get_rapidity_extent (double &rapmin, double &rapmax) const
virtual bool is_geometric () const
virtual bool has_finite_area () const
virtual bool has_known_area () const
virtual double known_area () const
Detailed Description
Definition at line 834 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 834 of file fjcore.hh
Constructor & Destructor Documentation
virtual SelectorWorker::~SelectorWorker () inline virtual
Definition at line 836 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 836 of file fjcore.hh
Member Function Documentation
virtual bool SelectorWorker::applies_jet_by_jet () const inline virtual
Reimplemented in SW_NHardest, SW_Or, SW_BinaryOperator, and SW_Not.
Definition at line 843 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 843 of file fjcore.hh
Referenced by Selector::applies_jet_by_jet().
virtual SelectorWorker* SelectorWorker::copy () inline virtual
Reimplemented in SW_Mult, SW_Or, SW_And, and SW_Not.
Definition at line 849 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 849 of file fjcore.hh
Referenced by Selector::_copy_worker_if_needed().
virtual std::string SelectorWorker::description () const inline virtual
Reimplemented in SW_IsZero, SW_NHardest, SW_PhiRange, SW_QuantityRange< QuantityType >, SW_QuantityRange< QuantityAbsRap >, SW_QuantityRange< QuantityRap >, SW_QuantityMax< QuantityAbsRap >, SW_QuantityMax< QuantityRap >, SW_QuantityMin< QuantityRap >, SW_Mult, SW_Or, SW_And, and SW_Not.
Definition at line 844 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 844 of file fjcore.hh
Referenced by Selector::description().
virtual void SelectorWorker::get_rapidity_extent (double & rapmin, double & rapmax) const inline virtual
Reimplemented in SW_AbsRapRange, SW_AbsRapMax, SW_RapRange, SW_RapMax, SW_RapMin, SW_Or, and SW_And.
Definition at line 852 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 852 of file fjcore.hh
Referenced by Selector::get_rapidity_extent().
bool SelectorWorker::has_finite_area () const virtual
Definition at line 4263 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 4263 of file fjcore.cc
Referenced by Selector::has_finite_area().
virtual bool SelectorWorker::has_known_area () const inline virtual
Reimplemented in SW_AbsRapRange, SW_AbsRapMax, and SW_RapRange.
Definition at line 858 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 858 of file fjcore.hh
virtual bool SelectorWorker::is_geometric () const inline virtual
Reimplemented in SW_PhiRange, SW_QuantityRange< QuantityType >, SW_QuantityRange< QuantityAbsRap >, SW_QuantityRange< QuantityRap >, SW_QuantityMax< QuantityAbsRap >, SW_QuantityMax< QuantityRap >, SW_QuantityMin< QuantityRap >, SW_BinaryOperator, and SW_Not.
Definition at line 856 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 856 of file fjcore.hh
Referenced by Selector::is_geometric().
virtual double SelectorWorker::known_area () const inline virtual
Reimplemented in SW_RapPhiRange, SW_AbsRapRange, SW_AbsRapMax, and SW_RapRange.
Definition at line 859 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 859 of file fjcore.hh
virtual bool SelectorWorker::pass (const PseudoJet & jet) const pure virtual
Implemented in SW_IsZero, SW_NHardest, SW_PhiRange, SW_QuantityRange< QuantityType >, SW_QuantityRange< QuantityAbsRap >, SW_QuantityRange< QuantityRap >, SW_QuantityMax< QuantityAbsRap >, SW_QuantityMax< QuantityRap >, SW_QuantityMin< QuantityRap >, SW_Or, SW_And, and SW_Not.
Referenced by Selector::pass(), and terminator().
virtual void SelectorWorker::set_reference (const PseudoJet &) inline virtual
Reimplemented in SW_BinaryOperator, and SW_Not.
Definition at line 846 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 846 of file fjcore.hh
Referenced by Selector::set_reference().
virtual bool SelectorWorker::takes_reference () const inline virtual
Reimplemented in SW_BinaryOperator, and SW_Not.
Definition at line 845 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 845 of file fjcore.hh
Referenced by Selector::takes_reference().
virtual void SelectorWorker::terminator (std::vector< const PseudoJet * > & jets) const inline virtual
Reimplemented in SW_NHardest, SW_Mult, SW_Or, SW_And, and SW_Not.
Definition at line 838 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 838 of file fjcore.hh
References i, and pass().
Referenced by Selector::nullify_non_selected(), SW_Not::terminator(), SW_And::terminator(), SW_Or::terminator(), and SW_Mult::terminator().
The documentation for this class was generated from the following files:
JETSCAPE/blob/main/external_packages/fjcore.hh
JETSCAPE/blob/main/external_packages/fjcore.cc