Analysis Software: ActsExamples::TutorialVertexFinderAlgorithm Exception Reference
ActsExamples::TutorialVertexFinderAlgorithm Exception Reference final
#include <acts/blob/sPHENIX/Examples/Algorithms/Vertexing/include/ActsExamples/Vertexing/TutorialVertexFinderAlgorithm.hpp>
Classes
struct Config
Public Member Functions
TutorialVertexFinderAlgorithm (const Config &cfg, Acts::Logging::Level lvl)
ProcessCode execute (const AlgorithmContext &ctx) const final
const Config & config () const
Get readonly access to the config parameters.
Public Member Functions inherited from ActsExamples::IAlgorithm
IAlgorithm (std::string name, Acts::Logging::Level level=Acts::Logging::INFO)
std::string name () const override
The algorithm name.
ProcessCode internalExecute (const AlgorithmContext &context) final
ProcessCode initialize () override
Initialize the algorithm.
ProcessCode finalize () override
Finalize the algorithm.
Private Attributes
Config m_cfg
ReadDataHandle< std::vector
< Acts::BoundTrackParameters > > m_inputTrackParameters {this, "InputTrackParameters"}
ReadDataHandle
< TrajectoriesContainer > m_inputTrajectories
WriteDataHandle
< ProtoVertexContainer > m_outputProtoVertices
Additional Inherited Members
Protected Member Functions inherited from ActsExamples::IAlgorithm
const Acts::Logger & logger () const
Detailed Description
Definition at line 32 of file TutorialVertexFinderAlgorithm.hpp.
View newest version in sPHENIX GitHub at line 32 of file TutorialVertexFinderAlgorithm.hpp
Constructor & Destructor Documentation
ActsExamples::TutorialVertexFinderAlgorithm::TutorialVertexFinderAlgorithm (const Config & cfg, Acts::Logging::Level lvl)
Definition at line 19 of file TutorialVertexFinderAlgorithm.cpp.
View newest version in sPHENIX GitHub at line 19 of file TutorialVertexFinderAlgorithm.cpp
References ActsExamples::WriteDataHandle< T >::initialize(), ActsExamples::TutorialVertexFinderAlgorithm::Config::inputTrackParameters, ActsExamples::TutorialVertexFinderAlgorithm::Config::inputTrajectories, m_cfg, m_inputTrackParameters, m_inputTrajectories, m_outputProtoVertices, ActsExamples::DataHandleBase::maybeInitialize(), and ActsExamples::TutorialVertexFinderAlgorithm::Config::outputProtoVertices.
Member Function Documentation
const Config& ActsExamples::TutorialVertexFinderAlgorithm::config () const inline
Get readonly access to the config parameters.
Definition at line 54 of file TutorialVertexFinderAlgorithm.hpp.
View newest version in sPHENIX GitHub at line 54 of file TutorialVertexFinderAlgorithm.hpp
References m_cfg.
ActsExamples::ProcessCode ActsExamples::TutorialVertexFinderAlgorithm::execute (const AlgorithmContext & ctx) const final virtual
Find vertices.
Parameters
ctx is the algorithm context with event information
Returns
a process code indication success or failure
Implements ActsExamples::IAlgorithm.
Definition at line 35 of file TutorialVertexFinderAlgorithm.cpp.
View newest version in sPHENIX GitHub at line 35 of file TutorialVertexFinderAlgorithm.cpp
References ActsExamples::makeTrackParametersPointerContainer(), and SUCCESS.
Member Data Documentation
Config ActsExamples::TutorialVertexFinderAlgorithm::m_cfg private
Definition at line 57 of file TutorialVertexFinderAlgorithm.hpp.
View newest version in sPHENIX GitHub at line 57 of file TutorialVertexFinderAlgorithm.hpp
Referenced by config(), and TutorialVertexFinderAlgorithm().
ReadDataHandle<std::vector<Acts::BoundTrackParameters> > ActsExamples::TutorialVertexFinderAlgorithm::m_inputTrackParameters {this, "InputTrackParameters"} private
Definition at line 60 of file TutorialVertexFinderAlgorithm.hpp.
View newest version in sPHENIX GitHub at line 60 of file TutorialVertexFinderAlgorithm.hpp
Referenced by TutorialVertexFinderAlgorithm().
ReadDataHandle<TrajectoriesContainer> ActsExamples::TutorialVertexFinderAlgorithm::m_inputTrajectories private
Initial value:
{
      this, "InputTrajectories"}
Definition at line 62 of file TutorialVertexFinderAlgorithm.hpp.
View newest version in sPHENIX GitHub at line 62 of file TutorialVertexFinderAlgorithm.hpp
Referenced by TutorialVertexFinderAlgorithm().
WriteDataHandle<ProtoVertexContainer> ActsExamples::TutorialVertexFinderAlgorithm::m_outputProtoVertices private
Initial value:
{
      this, "OutputProtoVertices"}
Definition at line 65 of file TutorialVertexFinderAlgorithm.hpp.
View newest version in sPHENIX GitHub at line 65 of file TutorialVertexFinderAlgorithm.hpp
Referenced by TutorialVertexFinderAlgorithm().
The documentation for this exception was generated from the following files:
acts/blob/sPHENIX/Examples/Algorithms/Vertexing/include/ActsExamples/Vertexing/TutorialVertexFinderAlgorithm.hpp
acts/blob/sPHENIX/Examples/Algorithms/Vertexing/src/TutorialVertexFinderAlgorithm.cpp