Analysis Software: Jetscape::JetScapeEventHeader Class Reference
Jetscape::JetScapeEventHeader Class Reference
#include <JETSCAPE/blob/main/src/framework/JetScapeEventHeader.h>
Public Member Functions
JetScapeEventHeader ()
double GetSigmaGen ()
void SetSigmaGen (double d)
Initial Hard Process: Set cross section.
double GetSigmaErr ()
void SetSigmaErr (double d)
Initial Hard Process: Set uncertainty on the cross section.
double GetPtHat ()
Initial Hard Process: pt-hat.
void SetPtHat (double d)
double GetEventWeight ()
Initial Hard Process: Get additionally created weight (e.g. pythia.event().weight())
void SetEventWeight (double d)
Initial Hard Process: Set additionally created weight (e.g. pythia.event().weight())
double GetNpart ()
Initial State: Get number of participants.
void SetNpart (double d)
Initial State: Get number of participants.
double GetNcoll ()
Initial State: Get number of binary collisions.
void SetNcoll (double d)
Initial State: Get number of binary collisions.
double GetTotalEntropy ()
Initial State: Get total entropy.
void SetTotalEntropy (double d)
Initial State: Get total entropy.
double GetEventPlaneAngle ()
Hydro: Get (2nd order) event plane angle.
void SetEventPlaneAngle (double d)
Hydro: Set (2nd order) event plane angle.
Private Attributes
double SigmaGen = -1
double SigmaErr = -1
double PtHat = -1
double EventWeight = 1
double Npart = -1
double Ncoll = -1
double TotalEntropy = -1
double EventPlaneAngle = -999
Detailed Description
Container for a multitude of event-related information such as xsec, centrality, ...
Definition at line 25 of file JetScapeEventHeader.h.
View newest version in sPHENIX GitHub at line 25 of file JetScapeEventHeader.h
Constructor & Destructor Documentation
Jetscape::JetScapeEventHeader::JetScapeEventHeader () inline
Definition at line 28 of file JetScapeEventHeader.h.
View newest version in sPHENIX GitHub at line 28 of file JetScapeEventHeader.h
Member Function Documentation
double Jetscape::JetScapeEventHeader::GetEventPlaneAngle () inline
Hydro: Get (2nd order) event plane angle.
Definition at line 80 of file JetScapeEventHeader.h.
View newest version in sPHENIX GitHub at line 80 of file JetScapeEventHeader.h
References EventPlaneAngle.
Referenced by Jetscape::JetScapeWriterHepMC::WriteHeaderToFile(), and Jetscape::JetScapeWriterRootHepMC::WriteHeaderToFile().
double Jetscape::JetScapeEventHeader::GetEventWeight () inline
Initial Hard Process: Get additionally created weight (e.g. pythia.event().weight())
Definition at line 58 of file JetScapeEventHeader.h.
View newest version in sPHENIX GitHub at line 58 of file JetScapeEventHeader.h
References EventWeight.
Referenced by Jetscape::JetScapeWriterAsciiGZ::WriteHeaderToFile().
double Jetscape::JetScapeEventHeader::GetNcoll () inline
Initial State: Get number of binary collisions.
Definition at line 69 of file JetScapeEventHeader.h.
View newest version in sPHENIX GitHub at line 69 of file JetScapeEventHeader.h
References Ncoll.
Referenced by Jetscape::JetScapeWriterHepMC::WriteHeaderToFile(), and Jetscape::JetScapeWriterRootHepMC::WriteHeaderToFile().
double Jetscape::JetScapeEventHeader::GetNpart () inline
Initial State: Get number of participants.
Definition at line 64 of file JetScapeEventHeader.h.
View newest version in sPHENIX GitHub at line 64 of file JetScapeEventHeader.h
References Npart.
Referenced by Jetscape::JetScapeWriterHepMC::WriteHeaderToFile(), and Jetscape::JetScapeWriterRootHepMC::WriteHeaderToFile().
double Jetscape::JetScapeEventHeader::GetPtHat () inline
Initial Hard Process: pt-hat.
Definition at line 54 of file JetScapeEventHeader.h.
View newest version in sPHENIX GitHub at line 54 of file JetScapeEventHeader.h
References PtHat.
double Jetscape::JetScapeEventHeader::GetSigmaErr () inline
Initial Hard Process: Get uncertainty on the cross section Note: In most cases, this value becomes more smaller as more events are created. It is recommended to use the last event's value
Definition at line 49 of file JetScapeEventHeader.h.
View newest version in sPHENIX GitHub at line 49 of file JetScapeEventHeader.h
References SigmaErr.
Referenced by Jetscape::JetScapeWriterAsciiGZ::WriteHeaderToFile().
double Jetscape::JetScapeEventHeader::GetSigmaGen () inline
Initial Hard Process: Get cross section Note: In most cases, this value becomes more precise as more events are created. It is recommended to use the last event's value
Definition at line 42 of file JetScapeEventHeader.h.
View newest version in sPHENIX GitHub at line 42 of file JetScapeEventHeader.h
References SigmaGen.
Referenced by Jetscape::JetScapeWriterAsciiGZ::WriteHeaderToFile().
double Jetscape::JetScapeEventHeader::GetTotalEntropy () inline
Initial State: Get total entropy.
Definition at line 74 of file JetScapeEventHeader.h.
View newest version in sPHENIX GitHub at line 74 of file JetScapeEventHeader.h
References TotalEntropy.
void Jetscape::JetScapeEventHeader::SetEventPlaneAngle (double d) inline
Hydro: Set (2nd order) event plane angle.
Definition at line 82 of file JetScapeEventHeader.h.
View newest version in sPHENIX GitHub at line 82 of file JetScapeEventHeader.h
References EventPlaneAngle.
void Jetscape::JetScapeEventHeader::SetEventWeight (double d) inline
Initial Hard Process: Set additionally created weight (e.g. pythia.event().weight())
Definition at line 60 of file JetScapeEventHeader.h.
View newest version in sPHENIX GitHub at line 60 of file JetScapeEventHeader.h
References EventWeight.
void Jetscape::JetScapeEventHeader::SetNcoll (double d) inline
Initial State: Get number of binary collisions.
Definition at line 71 of file JetScapeEventHeader.h.
View newest version in sPHENIX GitHub at line 71 of file JetScapeEventHeader.h
References Ncoll.
void Jetscape::JetScapeEventHeader::SetNpart (double d) inline
Initial State: Get number of participants.
Definition at line 66 of file JetScapeEventHeader.h.
View newest version in sPHENIX GitHub at line 66 of file JetScapeEventHeader.h
References Npart.
void Jetscape::JetScapeEventHeader::SetPtHat (double d) inline
Definition at line 55 of file JetScapeEventHeader.h.
View newest version in sPHENIX GitHub at line 55 of file JetScapeEventHeader.h
References PtHat.
void Jetscape::JetScapeEventHeader::SetSigmaErr (double d) inline
Initial Hard Process: Set uncertainty on the cross section.
Definition at line 51 of file JetScapeEventHeader.h.
View newest version in sPHENIX GitHub at line 51 of file JetScapeEventHeader.h
References SigmaErr.
void Jetscape::JetScapeEventHeader::SetSigmaGen (double d) inline
Initial Hard Process: Set cross section.
Definition at line 44 of file JetScapeEventHeader.h.
View newest version in sPHENIX GitHub at line 44 of file JetScapeEventHeader.h
References SigmaGen.
void Jetscape::JetScapeEventHeader::SetTotalEntropy (double d) inline
Initial State: Get total entropy.
Definition at line 76 of file JetScapeEventHeader.h.
View newest version in sPHENIX GitHub at line 76 of file JetScapeEventHeader.h
References TotalEntropy.
Member Data Documentation
double Jetscape::JetScapeEventHeader::EventPlaneAngle = -999 private
Definition at line 97 of file JetScapeEventHeader.h.
View newest version in sPHENIX GitHub at line 97 of file JetScapeEventHeader.h
Referenced by GetEventPlaneAngle(), and SetEventPlaneAngle().
double Jetscape::JetScapeEventHeader::EventWeight = 1 private
Definition at line 89 of file JetScapeEventHeader.h.
View newest version in sPHENIX GitHub at line 89 of file JetScapeEventHeader.h
Referenced by GetEventWeight(), and SetEventWeight().
double Jetscape::JetScapeEventHeader::Ncoll = -1 private
Definition at line 93 of file JetScapeEventHeader.h.
View newest version in sPHENIX GitHub at line 93 of file JetScapeEventHeader.h
Referenced by GetNcoll(), and SetNcoll().
double Jetscape::JetScapeEventHeader::Npart = -1 private
Definition at line 92 of file JetScapeEventHeader.h.
View newest version in sPHENIX GitHub at line 92 of file JetScapeEventHeader.h
Referenced by GetNpart(), and SetNpart().
double Jetscape::JetScapeEventHeader::PtHat = -1 private
Definition at line 88 of file JetScapeEventHeader.h.
View newest version in sPHENIX GitHub at line 88 of file JetScapeEventHeader.h
Referenced by GetPtHat(), and SetPtHat().
double Jetscape::JetScapeEventHeader::SigmaErr = -1 private
Definition at line 87 of file JetScapeEventHeader.h.
View newest version in sPHENIX GitHub at line 87 of file JetScapeEventHeader.h
Referenced by GetSigmaErr(), and SetSigmaErr().
double Jetscape::JetScapeEventHeader::SigmaGen = -1 private
Definition at line 86 of file JetScapeEventHeader.h.
View newest version in sPHENIX GitHub at line 86 of file JetScapeEventHeader.h
Referenced by GetSigmaGen(), and SetSigmaGen().
double Jetscape::JetScapeEventHeader::TotalEntropy = -1 private
Definition at line 94 of file JetScapeEventHeader.h.
View newest version in sPHENIX GitHub at line 94 of file JetScapeEventHeader.h
Referenced by GetTotalEntropy(), and SetTotalEntropy().
The documentation for this class was generated from the following file:
JETSCAPE/blob/main/src/framework/JetScapeEventHeader.h