Analysis Software: ElogHandler Class Reference
ElogHandler Class Reference
#include <rcdaq/blob/master/eloghandler.h>
Public Member Functions
ElogHandler (const std::string h, const int p, const std::string name)
virtual ~ElogHandler ()
virtual int BegrunLog (const int run, std::string who, std::string filename)
virtual int EndrunLog (const int run, std::string who, const int events, const double volume=0, time_t starttime=0)
virtual std::string getHost () const
virtual int getPort () const
virtual std::string getLogbookName () const
Protected Attributes
std::string hostname
std::string logbookname
int port
Detailed Description
Definition at line 9 of file eloghandler.h.
View newest version in sPHENIX GitHub at line 9 of file eloghandler.h
Constructor & Destructor Documentation
ElogHandler::ElogHandler (const std::string h, const int p, const std::string name)
Definition at line 8 of file eloghandler.cc.
View newest version in sPHENIX GitHub at line 8 of file eloghandler.cc
References h, perf_headwind::name, and merge_hashes::p.
virtual ElogHandler::~ElogHandler () inline virtual
Definition at line 17 of file eloghandler.h.
View newest version in sPHENIX GitHub at line 17 of file eloghandler.h
Member Function Documentation
int ElogHandler::BegrunLog (const int run, std::string who, std::string filename) virtual
Definition at line 15 of file eloghandler.cc.
View newest version in sPHENIX GitHub at line 15 of file eloghandler.cc
Referenced by daq_begin(), and main().
int ElogHandler::EndrunLog (const int run, std::string who, const int events, const double volume = 0, time_t starttime = 0) virtual
Definition at line 32 of file eloghandler.cc.
View newest version in sPHENIX GitHub at line 32 of file eloghandler.cc
References Acts::Test::time.
Referenced by daq_end(), and main().
virtual std::string ElogHandler::getHost () const inline virtual
Definition at line 22 of file eloghandler.h.
View newest version in sPHENIX GitHub at line 22 of file eloghandler.h
References hostname.
Referenced by daq_status().
virtual std::string ElogHandler::getLogbookName () const inline virtual
Definition at line 24 of file eloghandler.h.
View newest version in sPHENIX GitHub at line 24 of file eloghandler.h
Referenced by daq_status().
virtual int ElogHandler::getPort () const inline virtual
Definition at line 23 of file eloghandler.h.
View newest version in sPHENIX GitHub at line 23 of file eloghandler.h
References port.
Referenced by daq_status().
Member Data Documentation
std::string ElogHandler::hostname protected
Definition at line 24 of file eloghandler.h.
View newest version in sPHENIX GitHub at line 24 of file eloghandler.h
Referenced by getHost().
std::string ElogHandler::logbookname protected
Definition at line 30 of file eloghandler.h.
View newest version in sPHENIX GitHub at line 30 of file eloghandler.h
int ElogHandler::port protected
Definition at line 31 of file eloghandler.h.
View newest version in sPHENIX GitHub at line 31 of file eloghandler.h
Referenced by getPort().
The documentation for this class was generated from the following files:
rcdaq/blob/master/eloghandler.h
rcdaq/blob/master/eloghandler.cc