Analysis Software: MvtxStandaloneTracking Class Reference
MvtxStandaloneTracking Class Reference
#include <prototype/blob/master/offline/packages/MvtxPrototype1/MvtxStandaloneTracking.h>
Classes
struct MvtxTrack
Public Types
typedef std::vector< MvtxTrack > MvtxTrackList
typedef std::vector< MvtxTrack > MvtxTrackList
Public Member Functions
MvtxStandaloneTracking ()
ctor
~MvtxStandaloneTracking ()
dtor
void RunTracking (PHCompositeNode *topNode, MvtxTrackList &trklst, std::vector< int > &lyrs)
run tracking
void RunGhostRejection (MvtxTrackList &trklst)
reject ghosts
void SetWindowX (float w)
set association window
void SetWindowZ (float w)
void SetGhostRejection (bool yn)
set ghost rejection
void Verbosity (int v)
set verbosity
MvtxStandaloneTracking ()
ctor
~MvtxStandaloneTracking ()
dtor
void RunTracking (PHCompositeNode *topNode, MvtxTrackList &trklst, std::vector< int > &lyrs)
run tracking
void RunGhostRejection (MvtxTrackList &trklst)
reject ghosts
void SetWindowX (float w)
set association window
void SetWindowZ (float w)
void SetGhostRejection (bool yn)
set ghost rejection
void Verbosity (int v)
set verbosity
Private Member Functions
void AssociateClusters (MvtxTrackList &trklst, std::vector< int > &lyrs)
Associate clusters into track candidates.
void TrackFitXY (MvtxTrack &trk)
Fit track in x vs y.
void TrackFitZY (MvtxTrack &trk)
Fit track in z vs y.
TVectorD SolveGLS (TMatrixD &X, TVectorD &y, TMatrixD &L)
Generalized least squares fitter.
double CalcSlope (double x0, double y0, double x1, double y1)
double CalcIntecept (double x0, double y0, double m)
double CalcProjection (double x, double m, double b)
void PrintTrackCandidates (MvtxTrackList &trklst)
Print out track candidate information.
void AssociateClusters (MvtxTrackList &trklst, std::vector< int > &lyrs)
Associate clusters into track candidates.
void TrackFitXY (MvtxTrack &trk)
Fit track in x vs y.
void TrackFitZY (MvtxTrack &trk)
Fit track in z vs y.
TVectorD SolveGLS (TMatrixD &X, TVectorD &y, TMatrixD &L)
Generalized least squares fitter.
double CalcSlope (double x0, double y0, double x1, double y1)
double CalcIntecept (double x0, double y0, double m)
double CalcProjection (double x, double m, double b)
void PrintTrackCandidates (MvtxTrackList &trklst)
Print out track candidate information.
Private Attributes
TrkrClusterContainer * clusters_
Cluster node.
float window_x_
window size in x & z
float window_z_
bool ghostrejection_
ghost rejection
int verbosity_
Static Private Attributes
static const int NLYR = 4
Detailed Description
Definition at line 14 of file MvtxStandaloneTracking.h.
View newest version in sPHENIX GitHub at line 14 of file MvtxStandaloneTracking.h
Member Typedef Documentation
typedef std::vector<MvtxTrack> MvtxStandaloneTracking::MvtxTrackList
Definition at line 30 of file MvtxStandaloneTracking.h.
View newest version in sPHENIX GitHub at line 30 of file MvtxStandaloneTracking.h
typedef std::vector<MvtxTrack> MvtxStandaloneTracking::MvtxTrackList
Definition at line 32 of file MvtxStandaloneTracking.h.
View newest version in sPHENIX GitHub at line 32 of file MvtxStandaloneTracking.h
Constructor & Destructor Documentation
MvtxStandaloneTracking::MvtxStandaloneTracking ()
ctor
Definition at line 20 of file MvtxStandaloneTracking.C.
View newest version in sPHENIX GitHub at line 20 of file MvtxStandaloneTracking.C
MvtxStandaloneTracking::~MvtxStandaloneTracking ()
dtor
Definition at line 29 of file MvtxStandaloneTracking.C.
View newest version in sPHENIX GitHub at line 29 of file MvtxStandaloneTracking.C
MvtxStandaloneTracking::MvtxStandaloneTracking ()
ctor
MvtxStandaloneTracking::~MvtxStandaloneTracking ()
dtor
Member Function Documentation
void MvtxStandaloneTracking::AssociateClusters (MvtxTrackList & trklst, std::vector< int > & lyrs) private
Associate clusters into track candidates.
Definition at line 87 of file MvtxStandaloneTracking.C.
View newest version in sPHENIX GitHub at line 87 of file MvtxStandaloneTracking.C
References CalcIntecept(), CalcProjection(), CalcSlope(), MvtxStandaloneTracking::MvtxTrack::ClusterList, clusters_, window_x_, and window_z_.
Referenced by RunTracking().
void MvtxStandaloneTracking::AssociateClusters (MvtxTrackList & trklst, std::vector< int > & lyrs) private
Associate clusters into track candidates.
double MvtxStandaloneTracking::CalcIntecept (double x0, double y0, double m) private
Definition at line 461 of file MvtxStandaloneTracking.C.
View newest version in sPHENIX GitHub at line 461 of file MvtxStandaloneTracking.C
References Acts::UnitConstants::m.
Referenced by AssociateClusters().
double MvtxStandaloneTracking::CalcIntecept (double x0, double y0, double m) private
double MvtxStandaloneTracking::CalcProjection (double x, double m, double b) private
Definition at line 467 of file MvtxStandaloneTracking.C.
View newest version in sPHENIX GitHub at line 467 of file MvtxStandaloneTracking.C
References KFPMath::b.
Referenced by AssociateClusters().
double MvtxStandaloneTracking::CalcProjection (double x, double m, double b) private
double MvtxStandaloneTracking::CalcSlope (double x0, double y0, double x1, double y1) private
Definition at line 455 of file MvtxStandaloneTracking.C.
View newest version in sPHENIX GitHub at line 455 of file MvtxStandaloneTracking.C
References x0.
Referenced by AssociateClusters().
double MvtxStandaloneTracking::CalcSlope (double x0, double y0, double x1, double y1) private
void MvtxStandaloneTracking::PrintTrackCandidates (MvtxTrackList & trklst) private
Print out track candidate information.
Definition at line 420 of file MvtxStandaloneTracking.C.
View newest version in sPHENIX GitHub at line 420 of file MvtxStandaloneTracking.C
References i, j, and PHWHERE.
Referenced by RunTracking().
void MvtxStandaloneTracking::PrintTrackCandidates (MvtxTrackList & trklst) private
Print out track candidate information.
void MvtxStandaloneTracking::RunGhostRejection (MvtxTrackList & trklst)
reject ghosts
Definition at line 176 of file MvtxStandaloneTracking.C.
View newest version in sPHENIX GitHub at line 176 of file MvtxStandaloneTracking.C
References i, it, PHWHERE, and verbosity_.
Referenced by RunTracking().
void MvtxStandaloneTracking::RunGhostRejection (MvtxTrackList & trklst)
reject ghosts
void MvtxStandaloneTracking::RunTracking (PHCompositeNode * topNode, MvtxTrackList & trklst, std::vector< int > & lyrs)
run tracking
Definition at line 34 of file MvtxStandaloneTracking.C.
View newest version in sPHENIX GitHub at line 34 of file MvtxStandaloneTracking.C
References AssociateClusters(), clusters_, ghostrejection_, PHWHERE, PrintTrackCandidates(), RunGhostRejection(), TrackFitXY(), TrackFitZY(), and verbosity_.
Referenced by AnaMvtxPrototype1::process_event(), and AnaMvtxTestBeam2019::process_event().
void MvtxStandaloneTracking::RunTracking (PHCompositeNode * topNode, MvtxTrackList & trklst, std::vector< int > & lyrs)
run tracking
void MvtxStandaloneTracking::SetGhostRejection (bool yn) inline
set ghost rejection
Definition at line 49 of file MvtxStandaloneTracking.h.
View newest version in sPHENIX GitHub at line 49 of file MvtxStandaloneTracking.h
Referenced by Fun4All_TestBeam().
void MvtxStandaloneTracking::SetGhostRejection (bool yn) inline
set ghost rejection
Definition at line 51 of file MvtxStandaloneTracking.h.
View newest version in sPHENIX GitHub at line 51 of file MvtxStandaloneTracking.h
References ghostrejection_, and yn.
void MvtxStandaloneTracking::SetWindowX (float w) inline
set association window
Definition at line 45 of file MvtxStandaloneTracking.h.
View newest version in sPHENIX GitHub at line 45 of file MvtxStandaloneTracking.h
References window_x_.
Referenced by AnaMvtxPrototype1::AnaMvtxPrototype1(), and Fun4All_TestBeam().
void MvtxStandaloneTracking::SetWindowX (float w) inline
set association window
Definition at line 47 of file MvtxStandaloneTracking.h.
View newest version in sPHENIX GitHub at line 47 of file MvtxStandaloneTracking.h
References window_x_.
void MvtxStandaloneTracking::SetWindowZ (float w) inline
Definition at line 46 of file MvtxStandaloneTracking.h.
View newest version in sPHENIX GitHub at line 46 of file MvtxStandaloneTracking.h
References window_z_.
Referenced by AnaMvtxPrototype1::AnaMvtxPrototype1(), and Fun4All_TestBeam().
void MvtxStandaloneTracking::SetWindowZ (float w) inline
Definition at line 48 of file MvtxStandaloneTracking.h.
View newest version in sPHENIX GitHub at line 48 of file MvtxStandaloneTracking.h
References window_z_.
TVectorD MvtxStandaloneTracking::SolveGLS (TMatrixD & X, TVectorD & y, TMatrixD & L) private
Generalized least squares fitter.
Definition at line 283 of file MvtxStandaloneTracking.C.
View newest version in sPHENIX GitHub at line 283 of file MvtxStandaloneTracking.C
References A, KFPMath::b, i, physmon_simulation::s, TauVsDIS_MachineLearning_Differentiation::X, and y.
Referenced by TrackFitXY(), and TrackFitZY().
TVectorD MvtxStandaloneTracking::SolveGLS (TMatrixD & X, TVectorD & y, TMatrixD & L) private
Generalized least squares fitter.
void MvtxStandaloneTracking::TrackFitXY (MvtxTrack & trk) private
Fit track in x vs y.
Definition at line 310 of file MvtxStandaloneTracking.C.
View newest version in sPHENIX GitHub at line 310 of file MvtxStandaloneTracking.C
References Acts::Test::at, MvtxStandaloneTracking::MvtxTrack::b_xy, Acts::PhysicalConstants::c, MvtxStandaloneTracking::MvtxTrack::chi2_xy, MvtxStandaloneTracking::MvtxTrack::ClusterList, double(), MvtxStandaloneTracking::MvtxTrack::dx, Acts::UnitConstants::m, MvtxStandaloneTracking::MvtxTrack::m_xy, n, size, SolveGLS(), TauVsDIS_MachineLearning_Differentiation::X, ambiguity_solver_full_chain::x, x0, and y.
Referenced by RunTracking().
void MvtxStandaloneTracking::TrackFitXY (MvtxTrack & trk) private
Fit track in x vs y.
void MvtxStandaloneTracking::TrackFitZY (MvtxTrack & trk) private
Fit track in z vs y.
Definition at line 365 of file MvtxStandaloneTracking.C.
View newest version in sPHENIX GitHub at line 365 of file MvtxStandaloneTracking.C
References Acts::Test::at, MvtxStandaloneTracking::MvtxTrack::b_zy, Acts::PhysicalConstants::c, MvtxStandaloneTracking::MvtxTrack::chi2_zy, MvtxStandaloneTracking::MvtxTrack::ClusterList, double(), MvtxStandaloneTracking::MvtxTrack::dz, dz, Acts::UnitConstants::m, MvtxStandaloneTracking::MvtxTrack::m_zy, n, size, SolveGLS(), TauVsDIS_MachineLearning_Differentiation::X, y, and physmon_track_finding_ttbar::z.
Referenced by RunTracking().
void MvtxStandaloneTracking::TrackFitZY (MvtxTrack & trk) private
Fit track in z vs y.
void MvtxStandaloneTracking::Verbosity (int v) inline
set verbosity
Definition at line 52 of file MvtxStandaloneTracking.h.
View newest version in sPHENIX GitHub at line 52 of file MvtxStandaloneTracking.h
References testSigmaEff::v, and verbosity_.
Referenced by AnaMvtxPrototype1::AnaMvtxPrototype1(), and Fun4All_TestBeam().
void MvtxStandaloneTracking::Verbosity (int v) inline
set verbosity
Definition at line 54 of file MvtxStandaloneTracking.h.
View newest version in sPHENIX GitHub at line 54 of file MvtxStandaloneTracking.h
References testSigmaEff::v, and verbosity_.
Member Data Documentation
TrkrClusterContainer * MvtxStandaloneTracking::clusters_ private
Cluster node.
Definition at line 77 of file MvtxStandaloneTracking.h.
View newest version in sPHENIX GitHub at line 77 of file MvtxStandaloneTracking.h
Referenced by AssociateClusters(), and RunTracking().
bool MvtxStandaloneTracking::ghostrejection_ private
ghost rejection
Definition at line 84 of file MvtxStandaloneTracking.h.
View newest version in sPHENIX GitHub at line 84 of file MvtxStandaloneTracking.h
Referenced by RunTracking(), and SetGhostRejection().
static const int MvtxStandaloneTracking::NLYR = 4 static private
Definition at line 89 of file MvtxStandaloneTracking.h.
View newest version in sPHENIX GitHub at line 89 of file MvtxStandaloneTracking.h
int MvtxStandaloneTracking::verbosity_ private
Definition at line 87 of file MvtxStandaloneTracking.h.
View newest version in sPHENIX GitHub at line 87 of file MvtxStandaloneTracking.h
Referenced by RunGhostRejection(), RunTracking(), and Verbosity().
float MvtxStandaloneTracking::window_x_ private
window size in x & z
Definition at line 80 of file MvtxStandaloneTracking.h.
View newest version in sPHENIX GitHub at line 80 of file MvtxStandaloneTracking.h
Referenced by AssociateClusters(), and SetWindowX().
float MvtxStandaloneTracking::window_z_ private
Definition at line 81 of file MvtxStandaloneTracking.h.
View newest version in sPHENIX GitHub at line 81 of file MvtxStandaloneTracking.h
Referenced by AssociateClusters(), and SetWindowZ().
The documentation for this class was generated from the following files:
prototype/blob/master/offline/packages/MvtxPrototype1/MvtxStandaloneTracking.h
prototype/blob/master/offline/packages/MvtxPrototype2/MvtxStandaloneTracking.h
prototype/blob/master/offline/packages/MvtxPrototype1/MvtxStandaloneTracking.C
prototype/blob/master/offline/packages/MvtxPrototype2/MvtxStandaloneTracking.cc