Analysis Software: HelicalFitter Class Reference
HelicalFitter Class Reference
#include <coresoftware/blob/master/offline/packages/TrackerMillepedeAlignment/HelicalFitter.h>
Public Member Functions
HelicalFitter (const std::string &name="HelicalFitter")
~HelicalFitter () override
void SetDefaultParameters () override
void set_field_dir (const double rescale)
void set_field (const std::string &field)
int InitRun (PHCompositeNode *topNode) override
int process_event (PHCompositeNode *) override
int End (PHCompositeNode *) override
Called at the end of all processing.
void set_silicon_track_map_name (const std::string &map_name)
void set_track_map_name (const std::string &map_name)
void set_use_event_vertex (bool flag)
void set_datafile_name (const std::string &file)
void set_steeringfile_name (const std::string &file)
void set_mvtx_grouping (int group)
void set_intt_grouping (int group)
void set_tpc_grouping (int group)
void set_mms_grouping (int group)
void set_test_output (bool test)
void set_intt_layer_fixed (unsigned int layer)
void set_mvtx_layer_fixed (unsigned int layer, unsigned int clamshell)
void set_tpc_sector_fixed (unsigned int region, unsigned int sector, unsigned int side)
void set_layer_param_fixed (unsigned int layer, unsigned int param)
void set_ntuplefile_name (const std::string &file)
void set_fitted_subsystems (bool si, bool tpc, bool full)
void set_error_inflation_factor (unsigned int layer, float factor)
void set_vertex (Acts::Vector3 inVertex, Acts::Vector3 inVertex_uncertainty)
void set_vtx_sigma (float x_sigma, float y_sigma)
std::vector< float > fitClusters (std::vector< Acts::Vector3 > &global_vec, std::vector< TrkrDefs::cluskey > cluskey_vec)
void getTrackletClusters (TrackSeed *_track, std::vector< Acts::Vector3 > &global_vec, std::vector< TrkrDefs::cluskey > &cluskey_vec)
Acts::Vector3 get_helix_pca (std::vector< float > &fitpars, Acts::Vector3 global)
void correctTpcGlobalPositions (std::vector< Acts::Vector3 > global_vec, std::vector< TrkrDefs::cluskey > cluskey_vec)
unsigned int addSiliconClusters (std::vector< float > &fitpars, std::vector< Acts::Vector3 > &global_vec, std::vector< TrkrDefs::cluskey > &cluskey_vec)
void set_dca_cut (float dca)
Public Member Functions inherited from SubsysReco
~SubsysReco () override
virtual int EndRun (const int)
Called at the end of each run.
virtual int Init (PHCompositeNode *)
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
void Print (const std::string &="ALL") const override
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Public Member Functions inherited from PHParameterInterface
PHParameterInterface (const std::string &name)
PHParameterInterface (const PHParameterInterface &)=delete
PHParameterInterface & operator= (PHParameterInterface const &)=delete
virtual ~PHParameterInterface ()
void set_paramname (const std::string &name)
void set_double_param (const std::string &name, const double dval)
double get_double_param (const std::string &name) const
void set_int_param (const std::string &name, const int ival)
int get_int_param (const std::string &name) const
void set_string_param (const std::string &name, const std::string &sval)
std::string get_string_param (const std::string &name) const
void UpdateParametersWithMacro ()
void SaveToNodeTree (PHCompositeNode *runNode, const std::string &nodename)
void PutOnParNode (PHCompositeNode *parNode, const std::string &nodename)
void Print () const
Private Member Functions
int GetNodes (PHCompositeNode *topNode)
int CreateNodes (PHCompositeNode *topNode)
void getTrackletClusterList (TrackSeed *tracklet, std::vector< TrkrDefs::cluskey > &cluskey_vec)
Acts::Vector3 getPCALinePoint (Acts::Vector3 global, Acts::Vector3 tangent, Acts::Vector3 posref)
Acts::Vector3 get_line_plane_intersection (Acts::Vector3 PCA, Acts::Vector3 tangent, Acts::Vector3 sensor_center, Acts::Vector3 sensor_normal)
std::pair< Acts::Vector3,
Acts::Vector3 > get_helix_tangent (const std::vector< float > &fitpars, Acts::Vector3 global)
Acts::Vector3 get_helix_surface_intersection (Surface surf, std::vector< float > &fitpars, Acts::Vector3 global)
Acts::Vector3 get_helix_surface_intersection (Surface surf, std::vector< float > &fitpars, Acts::Vector3 global, Acts::Vector3 &pca, Acts::Vector3 &tangent)
Acts::Vector3 get_helix_vtx (Acts::Vector3 event_vtx, const std::vector< float > &fitpars)
float convertTimeToZ (TrkrDefs::cluskey cluster_key, TrkrCluster *cluster)
void makeTpcGlobalCorrections (TrkrDefs::cluskey cluster_key, short int crossing, Acts::Vector3 &global)
Acts::Vector2 getClusterError (TrkrCluster *cluster, TrkrDefs::cluskey cluskey, Acts::Vector3 &global)
bool is_tpc_sector_fixed (unsigned int layer, unsigned int sector, unsigned int side)
bool is_mvtx_layer_fixed (unsigned int layer, unsigned int stave)
bool is_intt_layer_fixed (unsigned int layer)
bool is_layer_param_fixed (unsigned int layer, unsigned int param)
void getLocalDerivativesXY (Surface surf, Acts::Vector3 global, const std::vector< float > &fitpars, float lcl_derivativeX[5], float lcl_derivativeY[5], unsigned int layer)
void getLocalVtxDerivativesXY (SvtxTrack &track, Acts::Vector3 track_vtx, const std::vector< float > &fitpars, float lcl_derivativeX[5], float lcl_derivativeY[5])
void getGlobalDerivativesXY (Surface surf, Acts::Vector3 global, Acts::Vector3 fitpoint, const std::vector< float > &fitpars, float glb_derivativeX[6], float glbl_derivativeY[6], unsigned int layer)
void getGlobalVtxDerivativesXY (SvtxTrack &track, Acts::Vector3 track_vtx, float glbl_derivativeX[3], float glbl_derivativeY[3])
void get_projectionXY (Surface surf, std::pair< Acts::Vector3, Acts::Vector3 > tangent, Acts::Vector3 &projX, Acts::Vector3 &projY)
void get_projectionVtxXY (SvtxTrack &track, Acts::Vector3 event_vtx, Acts::Vector3 &projX, Acts::Vector3 &projY)
float getVertexResidual (Acts::Vector3 vtx)
void get_dca (SvtxTrack &track, float &dca3dxy, float &dca3dz, float &dca3dxysigma, float &dca3dzsigma, Acts::Vector3 vertex)
Acts::Vector3 globalvtxToLocalvtx (SvtxTrack &track, Acts::Vector3 event_vertex)
Acts::Vector3 globalvtxToLocalvtx (SvtxTrack &track, Acts::Vector3 event_vertex, Acts::Vector3 PCA)
Acts::Vector3 localvtxToGlobalvtx (SvtxTrack &track, Acts::Vector3 event_vtx, Acts::Vector3 PCA)
Private Attributes
Mille * _mille
TpcClusterZCrossingCorrection m_clusterCrossingCorrection
TpcDistortionCorrectionContainer * _dcc_static {nullptr}
TpcDistortionCorrectionContainer * _dcc_average {nullptr}
TpcDistortionCorrectionContainer * _dcc_fluctuation {nullptr}
bool test_output = false
ClusterErrorPara _ClusErrPara
std::set< std::pair< unsigned
int, unsigned int > > fixed_mvtx_layers
std::set< unsigned int > fixed_intt_layers
std::set< unsigned int > fixed_sectors
std::set< std::pair< unsigned
int, unsigned int > > fixed_layer_params
AlignmentDefs::mvtxGrp mvtx_grp = AlignmentDefs::mvtxGrp::snsr
AlignmentDefs::inttGrp intt_grp = AlignmentDefs::inttGrp::chp
AlignmentDefs::tpcGrp tpc_grp = AlignmentDefs::tpcGrp::htst
AlignmentDefs::mmsGrp mms_grp = AlignmentDefs::mmsGrp::tl
TpcDistortionCorrection _distortionCorrection
tpc distortion correction utility class
TrackSeedContainer * _track_map_tpc {nullptr}
TrackSeedContainer * _track_map_silicon {nullptr}
TrkrClusterContainer * _cluster_map {nullptr}
ActsGeometry * _tGeometry {nullptr}
std::string data_outfilename = ("mille_helical_output_data_file.bin")
std::string steering_outfilename = ("steer_helical.txt")
std::string ntuple_outfilename = ("HF_ntuple.root")
bool fitsilicon = true
bool fittpc = false
bool fitfulltrack = false
float dca_cut = 0.19
SvtxTrackMap * m_trackmap = nullptr
SvtxAlignmentStateMap * m_alignmentmap = nullptr
std::string _field
int _fieldDir = -1
std::map< unsigned int, float > _layerMisalignment
std::string _track_map_name = "TpcTrackSeedContainer"
std::string _silicon_track_map_name = "SiliconTrackSeedContainer"
bool make_ntuple = true
TNtuple * ntp {nullptr}
TNtuple * track_ntp {nullptr}
TFile * fout {nullptr}
bool use_event_vertex = false
int event = 0
Acts::Vector3 vertexPosition
Acts::Vector3 vertexPosUncertainty
Acts::Vector2 vtx_sigma
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = std::numeric_limits<int>::max() - 10
}
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Protected Member Functions inherited from PHParameterInterface
void set_default_double_param (const std::string &name, const double dval)
void set_default_int_param (const std::string &name, const int ival)
void set_default_string_param (const std::string &name, const std::string &sval)
void InitializeParameters ()
Detailed Description
Definition at line 34 of file HelicalFitter.h.
View newest version in sPHENIX GitHub at line 34 of file HelicalFitter.h
Constructor & Destructor Documentation
HelicalFitter::HelicalFitter (const std::string & name = "HelicalFitter")
Definition at line 54 of file HelicalFitter.cc.
View newest version in sPHENIX GitHub at line 54 of file HelicalFitter.cc
References PHParameterInterface::InitializeParameters(), vertexPosition, and vtx_sigma.
HelicalFitter::~HelicalFitter () override
Definition at line 69 of file HelicalFitter.cc.
View newest version in sPHENIX GitHub at line 69 of file HelicalFitter.cc
Member Function Documentation
unsigned int HelicalFitter::addSiliconClusters (std::vector< float > & fitpars, std::vector< Acts::Vector3 > & global_vec, std::vector< TrkrDefs::cluskey > & cluskey_vec)
Definition at line 1222 of file HelicalFitter.cc.
View newest version in sPHENIX GitHub at line 1222 of file HelicalFitter.cc
References _cluster_map, _tGeometry, TrackFitUtils::addClusters(), and dca_cut.
float HelicalFitter::convertTimeToZ (TrkrDefs::cluskey cluster_key, TrkrCluster * cluster) private
Definition at line 878 of file HelicalFitter.cc.
View newest version in sPHENIX GitHub at line 878 of file HelicalFitter.cc
References _tGeometry, ActsGeometry::get_drift_velocity(), TrkrCluster::getLocalY(), TpcDefs::getSide(), and physmon_track_finding_ttbar::z.
Referenced by process_event().
void HelicalFitter::correctTpcGlobalPositions (std::vector< Acts::Vector3 > global_vec, std::vector< TrkrDefs::cluskey > cluskey_vec)
Definition at line 1297 of file HelicalFitter.cc.
View newest version in sPHENIX GitHub at line 1297 of file HelicalFitter.cc
References TrkrDefs::getTrkrId(), makeTpcGlobalCorrections(), and TrkrDefs::tpcId.
Referenced by process_event().
int HelicalFitter::CreateNodes (PHCompositeNode * topNode) private
Definition at line 785 of file HelicalFitter.cc.
View newest version in sPHENIX GitHub at line 785 of file HelicalFitter.cc
References PHCompositeNode::addNode(), Fun4AllReturnCodes::EVENT_OK, PHNodeIterator::findFirst(), m_alignmentmap, and m_trackmap.
Referenced by InitRun().
int HelicalFitter::End (PHCompositeNode *) override virtual
Called at the end of all processing.
Reimplemented from SubsysReco.
Definition at line 772 of file HelicalFitter.cc.
View newest version in sPHENIX GitHub at line 772 of file HelicalFitter.cc
References _mille, Fun4AllReturnCodes::EVENT_OK, fout, and make_ntuple.
std::vector< float > HelicalFitter::fitClusters (std::vector< Acts::Vector3 > & global_vec, std::vector< TrkrDefs::cluskey > cluskey_vec)
Definition at line 939 of file HelicalFitter.cc.
View newest version in sPHENIX GitHub at line 939 of file HelicalFitter.cc
References TrackFitUtils::fitClusters().
Referenced by helixResiduals::fill_residuals().
void HelicalFitter::get_dca (SvtxTrack & track, float & dca3dxy, float & dca3dz, float & dca3dxysigma, float & dca3dzsigma, Acts::Vector3 vertex) private
Definition at line 1328 of file HelicalFitter.cc.
View newest version in sPHENIX GitHub at line 1328 of file HelicalFitter.cc
References SvtxTrack::get_error(), SvtxTrack::get_px(), SvtxTrack::get_py(), SvtxTrack::get_pz(), SvtxTrack::get_x(), SvtxTrack::get_y(), SvtxTrack::get_z(), i, j, ActsTests::PropagationDatasets::phi, physmon_track_finding_ttbar::r, and Fun4AllBase::Verbosity().
Referenced by process_event().
Acts::Vector3 HelicalFitter::get_helix_pca (std::vector< float > & fitpars, Acts::Vector3 global)
Definition at line 860 of file HelicalFitter.cc.
View newest version in sPHENIX GitHub at line 860 of file HelicalFitter.cc
References TrackFitUtils::get_helix_pca().
Referenced by helixResiduals::fill_residuals().
Acts::Vector3 HelicalFitter::get_helix_surface_intersection (Surface surf, std::vector< float > & fitpars, Acts::Vector3 global) private
Definition at line 667 of file HelicalFitter.cc.
View newest version in sPHENIX GitHub at line 667 of file HelicalFitter.cc
References _tGeometry, ActsGeometry::geometry(), get_helix_tangent(), get_line_plane_intersection(), ActsTrackingGeometry::getGeoContext(), and line.
Referenced by getLocalDerivativesXY(), and process_event().
Acts::Vector3 HelicalFitter::get_helix_surface_intersection (Surface surf, std::vector< float > & fitpars, Acts::Vector3 global, Acts::Vector3 & pca, Acts::Vector3 & tangent) private
Definition at line 686 of file HelicalFitter.cc.
View newest version in sPHENIX GitHub at line 686 of file HelicalFitter.cc
References _tGeometry, ActsGeometry::geometry(), get_helix_tangent(), get_line_plane_intersection(), ActsTrackingGeometry::getGeoContext(), and line.
std::pair< Acts::Vector3, Acts::Vector3 > HelicalFitter::get_helix_tangent (const std::vector< float > & fitpars, Acts::Vector3 global) private
Definition at line 733 of file HelicalFitter.cc.
View newest version in sPHENIX GitHub at line 733 of file HelicalFitter.cc
References TrackFitUtils::get_helix_tangent().
Referenced by get_helix_surface_intersection(), getGlobalDerivativesXY(), getLocalDerivativesXY(), and process_event().
Acts::Vector3 HelicalFitter::get_helix_vtx (Acts::Vector3 event_vtx, const std::vector< float > & fitpars) private
Definition at line 707 of file HelicalFitter.cc.
View newest version in sPHENIX GitHub at line 707 of file HelicalFitter.cc
References TrackFitUtils::get_circle_point_pca().
Referenced by getLocalVtxDerivativesXY().
Acts::Vector3 HelicalFitter::get_line_plane_intersection (Acts::Vector3 PCA, Acts::Vector3 tangent, Acts::Vector3 sensor_center, Acts::Vector3 sensor_normal) private
Definition at line 716 of file HelicalFitter.cc.
View newest version in sPHENIX GitHub at line 716 of file HelicalFitter.cc
Referenced by get_helix_surface_intersection().
void HelicalFitter::get_projectionVtxXY (SvtxTrack & track, Acts::Vector3 event_vtx, Acts::Vector3 & projX, Acts::Vector3 & projY) private
Definition at line 1199 of file HelicalFitter.cc.
View newest version in sPHENIX GitHub at line 1199 of file HelicalFitter.cc
References SvtxTrack::get_px(), SvtxTrack::get_py(), SvtxTrack::get_pz(), localvtxToGlobalvtx(), TauVsDIS_MachineLearning_Differentiation::X, and TauVsDIS_MachineLearning_Differentiation::Y.
Referenced by getGlobalVtxDerivativesXY(), and getLocalVtxDerivativesXY().
void HelicalFitter::get_projectionXY (Surface surf, std::pair< Acts::Vector3, Acts::Vector3 > tangent, Acts::Vector3 & projX, Acts::Vector3 & projY) private
Definition at line 1175 of file HelicalFitter.cc.
View newest version in sPHENIX GitHub at line 1175 of file HelicalFitter.cc
References _tGeometry, Acts::UnitConstants::cm, ActsGeometry::geometry(), ActsTrackingGeometry::getGeoContext(), TauVsDIS_MachineLearning_Differentiation::X, TauVsDIS_MachineLearning_Differentiation::Y, and SVM_v1::Z.
Referenced by getGlobalDerivativesXY(), and getLocalDerivativesXY().
Acts::Vector2 HelicalFitter::getClusterError (TrkrCluster * cluster, TrkrDefs::cluskey cluskey, Acts::Vector3 & global) private
Definition at line 944 of file HelicalFitter.cc.
View newest version in sPHENIX GitHub at line 944 of file HelicalFitter.cc
References _ClusErrPara, and ClusterErrorPara::get_clusterv5_modified_error().
Referenced by process_event().
void HelicalFitter::getGlobalDerivativesXY (Surface surf, Acts::Vector3 global, Acts::Vector3 fitpoint, const std::vector< float > & fitpars, float glb_derivativeX[6], float glbl_derivativeY[6], unsigned int layer) private
Definition at line 1082 of file HelicalFitter.cc.
View newest version in sPHENIX GitHub at line 1082 of file HelicalFitter.cc
References _tGeometry, Acts::UnitConstants::cm, ActsGeometry::geometry(), get_helix_tangent(), get_projectionXY(), ActsTrackingGeometry::getGeoContext(), OM(), and Fun4AllBase::Verbosity().
Referenced by process_event().
void HelicalFitter::getGlobalVtxDerivativesXY (SvtxTrack & track, Acts::Vector3 track_vtx, float glbl_derivativeX[3], float glbl_derivativeY[3]) private
Definition at line 1140 of file HelicalFitter.cc.
View newest version in sPHENIX GitHub at line 1140 of file HelicalFitter.cc
References get_projectionVtxXY(), SvtxTrack::get_px(), SvtxTrack::get_py(), SvtxTrack::get_pz(), SvtxTrack::get_x(), SvtxTrack::get_y(), SvtxTrack::get_z(), and i.
Referenced by process_event().
void HelicalFitter::getLocalDerivativesXY (Surface surf, Acts::Vector3 global, const std::vector< float > & fitpars, float lcl_derivativeX[5], float lcl_derivativeY[5], unsigned int layer) private
Definition at line 959 of file HelicalFitter.cc.
View newest version in sPHENIX GitHub at line 959 of file HelicalFitter.cc
References get_helix_surface_intersection(), get_helix_tangent(), get_projectionXY(), and Fun4AllBase::Verbosity().
Referenced by process_event().
void HelicalFitter::getLocalVtxDerivativesXY (SvtxTrack & track, Acts::Vector3 track_vtx, const std::vector< float > & fitpars, float lcl_derivativeX[5], float lcl_derivativeY[5]) private
Definition at line 1016 of file HelicalFitter.cc.
View newest version in sPHENIX GitHub at line 1016 of file HelicalFitter.cc
References get_helix_vtx(), get_projectionVtxXY(), SvtxTrack::get_px(), SvtxTrack::get_py(), SvtxTrack::get_pz(), SvtxTrack::get_x(), SvtxTrack::get_y(), SvtxTrack::get_z(), globalvtxToLocalvtx(), and Fun4AllBase::Verbosity().
Referenced by process_event().
int HelicalFitter::GetNodes (PHCompositeNode * topNode) private
Definition at line 823 of file HelicalFitter.cc.
View newest version in sPHENIX GitHub at line 823 of file HelicalFitter.cc
References _cluster_map, _silicon_track_map_name, _tGeometry, _track_map_name, _track_map_silicon, _track_map_tpc, Fun4AllReturnCodes::ABORTEVENT, Fun4AllReturnCodes::EVENT_OK, and PHWHERE.
Referenced by InitRun().
Acts::Vector3 HelicalFitter::getPCALinePoint (Acts::Vector3 global, Acts::Vector3 tangent, Acts::Vector3 posref) private
Definition at line 866 of file HelicalFitter.cc.
View newest version in sPHENIX GitHub at line 866 of file HelicalFitter.cc
void HelicalFitter::getTrackletClusterList (TrackSeed * tracklet, std::vector< TrkrDefs::cluskey > & cluskey_vec) private
Make a safety check for clusters that couldn't be attached to a surface
Definition at line 912 of file HelicalFitter.cc.
View newest version in sPHENIX GitHub at line 912 of file HelicalFitter.cc
References _cluster_map, _tGeometry, TrackSeed::begin_cluster_keys(), TrackSeed::end_cluster_keys(), TrkrClusterContainer::findCluster(), TrkrDefs::getLayer(), ActsSurfaceMaps::getSurface(), layer, ActsGeometry::maps(), and surf().
Referenced by getTrackletClusters(), and process_event().
void HelicalFitter::getTrackletClusters (TrackSeed * _track, std::vector< Acts::Vector3 > & global_vec, std::vector< TrkrDefs::cluskey > & cluskey_vec)
Definition at line 905 of file HelicalFitter.cc.
View newest version in sPHENIX GitHub at line 905 of file HelicalFitter.cc
References _cluster_map, _tGeometry, getTrackletClusterList(), and TrackFitUtils::getTrackletClusters().
Referenced by helixResiduals::fill_residuals().
float HelicalFitter::getVertexResidual (Acts::Vector3 vtx) private
Definition at line 1314 of file HelicalFitter.cc.
View newest version in sPHENIX GitHub at line 1314 of file HelicalFitter.cc
References ActsTests::PropagationDatasets::phi, physmon_track_finding_ttbar::r, and Fun4AllBase::Verbosity().
Acts::Vector3 HelicalFitter::globalvtxToLocalvtx (SvtxTrack & track, Acts::Vector3 event_vertex) private
Definition at line 1378 of file HelicalFitter.cc.
View newest version in sPHENIX GitHub at line 1378 of file HelicalFitter.cc
References SvtxTrack::get_px(), SvtxTrack::get_py(), SvtxTrack::get_pz(), SvtxTrack::get_x(), SvtxTrack::get_y(), SvtxTrack::get_z(), ActsTests::PropagationDatasets::phi, physmon_track_finding_ttbar::r, and Fun4AllBase::Verbosity().
Referenced by getLocalVtxDerivativesXY().
Acts::Vector3 HelicalFitter::globalvtxToLocalvtx (SvtxTrack & track, Acts::Vector3 event_vertex, Acts::Vector3 PCA) private
Definition at line 1411 of file HelicalFitter.cc.
View newest version in sPHENIX GitHub at line 1411 of file HelicalFitter.cc
References SvtxTrack::get_px(), SvtxTrack::get_py(), SvtxTrack::get_pz(), ActsTests::PropagationDatasets::phi, physmon_track_finding_ttbar::r, and Fun4AllBase::Verbosity().
int HelicalFitter::InitRun (PHCompositeNode *) override virtual
Called for first event when run number is known. Typically this is where you may want to fetch data from database, because you know the run number.
Reimplemented from SubsysReco.
Definition at line 75 of file HelicalFitter.cc.
View newest version in sPHENIX GitHub at line 75 of file HelicalFitter.cc
References _mille, AlignmentDefs::chp, AlignmentDefs::clamshl, CreateNodes(), data_outfilename, Fun4AllReturnCodes::EVENT_OK, fout, GetNodes(), AlignmentDefs::htst, intt_grp, AlignmentDefs::inttbrl, AlignmentDefs::inttlyr, AlignmentDefs::lad, make_ntuple, Acts::UnitConstants::mm, mms_grp, mvtx_grp, AlignmentDefs::mvtxlyr, ntp, ntuple_outfilename, AlignmentDefs::sctr, AlignmentDefs::snsr, steering_outfilename, AlignmentDefs::stv, test_output, AlignmentDefs::tl, physmon_simulation::tp, tpc_grp, track_ntp, and PHParameterInterface::UpdateParametersWithMacro().
Referenced by helixResiduals::InitRun().
bool HelicalFitter::is_intt_layer_fixed (unsigned int layer) private
Definition at line 1228 of file HelicalFitter.cc.
View newest version in sPHENIX GitHub at line 1228 of file HelicalFitter.cc
References fixed_intt_layers, and it.
Referenced by process_event().
bool HelicalFitter::is_layer_param_fixed (unsigned int layer, unsigned int param) private
Definition at line 1261 of file HelicalFitter.cc.
View newest version in sPHENIX GitHub at line 1261 of file HelicalFitter.cc
References fixed_layer_params, and it.
Referenced by process_event().
bool HelicalFitter::is_mvtx_layer_fixed (unsigned int layer, unsigned int stave) private
Definition at line 1238 of file HelicalFitter.cc.
View newest version in sPHENIX GitHub at line 1238 of file HelicalFitter.cc
References fixed_mvtx_layers, and it.
Referenced by process_event().
bool HelicalFitter::is_tpc_sector_fixed (unsigned int layer, unsigned int sector, unsigned int side) private
Definition at line 1285 of file HelicalFitter.cc.
View newest version in sPHENIX GitHub at line 1285 of file HelicalFitter.cc
References fixed_sectors, AlignmentDefs::getTpcRegion(), and it.
Referenced by process_event().
Acts::Vector3 HelicalFitter::localvtxToGlobalvtx (SvtxTrack & track, Acts::Vector3 event_vtx, Acts::Vector3 PCA) private
Definition at line 1443 of file HelicalFitter.cc.
View newest version in sPHENIX GitHub at line 1443 of file HelicalFitter.cc
References SvtxTrack::get_px(), SvtxTrack::get_py(), SvtxTrack::get_pz(), ActsTests::PropagationDatasets::phi, physmon_track_finding_ttbar::r, and Fun4AllBase::Verbosity().
Referenced by get_projectionVtxXY().
void HelicalFitter::makeTpcGlobalCorrections (TrkrDefs::cluskey cluster_key, short int crossing, Acts::Vector3 & global) private
Definition at line 892 of file HelicalFitter.cc.
View newest version in sPHENIX GitHub at line 892 of file HelicalFitter.cc
References _dcc_average, _dcc_fluctuation, _dcc_static, _distortionCorrection, TpcClusterZCrossingCorrection::correctZ(), TpcDistortionCorrection::get_corrected_position(), TpcDefs::getSide(), m_clusterCrossingCorrection, and physmon_track_finding_ttbar::z.
Referenced by correctTpcGlobalPositions().
int HelicalFitter::process_event (PHCompositeNode *) override virtual
Called for each event. This is where you do the real work.
use the track seed functions to help get the track trajectory values in the usual coordinates
Reimplemented from SubsysReco.
Definition at line 146 of file HelicalFitter.cc.
View newest version in sPHENIX GitHub at line 146 of file HelicalFitter.cc
References _cluster_map, _layerMisalignment, _mille, _tGeometry, _track_map_silicon, _track_map_tpc, TrackFitUtils::addClusters(), Acts::UnitConstants::cm, convertTimeToZ(), correctTpcGlobalPositions(), dca_cut, Mille::end(), event, Fun4AllReturnCodes::EVENT_OK, TrkrClusterContainer::findCluster(), TrackFitUtils::fitClusters(), fitfulltrack, fitsilicon, fittpc, ActsGeometry::geometry(), TrackSeedContainer::get(), TrackSeed::get_charge(), TrackFitUtils::get_circle_point_pca(), TrackSeed::get_crossing(), get_dca(), get_helix_surface_intersection(), get_helix_tangent(), TrackSeed_v1::get_px(), TrackSeed_v1::get_py(), TrackSeed_v1::get_pz(), TrackSeed_v1::get_x(), TrackSeed_v1::get_y(), TrackSeed_v1::get_z(), MvtxDefs::getChipId(), getClusterError(), ActsTrackingGeometry::getGeoContext(), getGlobalDerivativesXY(), getGlobalVtxDerivativesXY(), AlignmentDefs::getInttGlobalLabels(), InttDefs::getLadderPhiId(), InttDefs::getLadderZId(), TrkrDefs::getLayer(), getLocalDerivativesXY(), getLocalVtxDerivativesXY(), AlignmentDefs::getMvtxClamshell(), AlignmentDefs::getMvtxGlobalLabels(), TpcDefs::getSectorId(), TpcDefs::getSide(), MvtxDefs::getStaveId(), ActsSurfaceMaps::getSurface(), AlignmentDefs::getTpcGlobalLabels(), getTrackletClusterList(), TrackFitUtils::getTrackletClusters(), TrkrDefs::getTrkrId(), AlignmentDefs::glbl_vtx_label, i, TrackSeed_v1::insert_cluster_key(), SvtxAlignmentStateMap::insertWithKey(), SvtxTrackMap::insertWithKey(), intt_grp, TrkrDefs::inttId, is_intt_layer_fixed(), is_layer_param_fixed(), is_mvtx_layer_fixed(), is_tpc_sector_fixed(), layer, m_alignmentmap, m_trackmap, make_ntuple, ActsGeometry::maps(), Mille::mille(), mvtx_grp, TrkrDefs::mvtxId, AlignmentDefs::NGL, AlignmentDefs::NGLVTX, AlignmentDefs::NLC, ntp, ActsTests::PropagationDatasets::phi, PHWHERE, physmon_track_finding_ttbar::r, SvtxTrack_v4::set_charge(), SvtxTrack_v4::set_crossing(), SvtxTrack_v4::set_id(), SvtxTrack_v4::set_px(), SvtxTrack_v4::set_py(), SvtxTrack_v4::set_pz(), TrackSeed_v1::set_qOverR(), SvtxTrack_v4::set_silicon_seed(), TrackSeed_v1::set_slope(), SvtxTrack_v4::set_tpc_seed(), SvtxTrackState_v1::set_x(), SvtxTrack_v4::set_x(), TrackSeed_v1::set_X0(), SvtxTrack_v4::set_y(), TrackSeed_v1::set_Y0(), SvtxTrack_v4::set_z(), TrackSeed_v1::set_Z0(), TrackSeedContainer::size(), surf(), tpc_grp, TrkrDefs::tpcId, track_ntp, Acts::Test::transform, alignmentTransformationContainer::use_alignment, use_event_vertex, Fun4AllBase::Verbosity(), and vtx_sigma.
void HelicalFitter::set_datafile_name (const std::string & file) inline
Definition at line 62 of file HelicalFitter.h.
View newest version in sPHENIX GitHub at line 62 of file HelicalFitter.h
References data_outfilename, and file.
void HelicalFitter::set_dca_cut (float dca) inline
Definition at line 102 of file HelicalFitter.h.
View newest version in sPHENIX GitHub at line 102 of file HelicalFitter.h
References INTTVtxZ::dca, and dca_cut.
void HelicalFitter::set_error_inflation_factor (unsigned int layer, float factor) inline
Definition at line 77 of file HelicalFitter.h.
View newest version in sPHENIX GitHub at line 77 of file HelicalFitter.h
References _layerMisalignment.
void HelicalFitter::set_field (const std::string & field) inline
Definition at line 50 of file HelicalFitter.h.
View newest version in sPHENIX GitHub at line 50 of file HelicalFitter.h
References _field, and ckf::field.
void HelicalFitter::set_field_dir (const double rescale) inline
Definition at line 44 of file HelicalFitter.h.
View newest version in sPHENIX GitHub at line 44 of file HelicalFitter.h
References _fieldDir.
void HelicalFitter::set_fitted_subsystems (bool si, bool tpc, bool full) inline
Definition at line 75 of file HelicalFitter.h.
View newest version in sPHENIX GitHub at line 75 of file HelicalFitter.h
References fitfulltrack, fitsilicon, and fittpc.
void HelicalFitter::set_intt_grouping (int group) inline
Definition at line 65 of file HelicalFitter.h.
View newest version in sPHENIX GitHub at line 65 of file HelicalFitter.h
References intt_grp.
void HelicalFitter::set_intt_layer_fixed (unsigned int layer)
Definition at line 1250 of file HelicalFitter.cc.
View newest version in sPHENIX GitHub at line 1250 of file HelicalFitter.cc
References fixed_intt_layers.
void HelicalFitter::set_layer_param_fixed (unsigned int layer, unsigned int param)
Definition at line 1272 of file HelicalFitter.cc.
View newest version in sPHENIX GitHub at line 1272 of file HelicalFitter.cc
References fixed_layer_params.
void HelicalFitter::set_mms_grouping (int group) inline
Definition at line 67 of file HelicalFitter.h.
View newest version in sPHENIX GitHub at line 67 of file HelicalFitter.h
References mms_grp.
void HelicalFitter::set_mvtx_grouping (int group) inline
Definition at line 64 of file HelicalFitter.h.
View newest version in sPHENIX GitHub at line 64 of file HelicalFitter.h
References mvtx_grp.
void HelicalFitter::set_mvtx_layer_fixed (unsigned int layer, unsigned int clamshell)
Definition at line 1255 of file HelicalFitter.cc.
View newest version in sPHENIX GitHub at line 1255 of file HelicalFitter.cc
References fixed_mvtx_layers.
void HelicalFitter::set_ntuplefile_name (const std::string & file) inline
Definition at line 73 of file HelicalFitter.h.
View newest version in sPHENIX GitHub at line 73 of file HelicalFitter.h
References file, and ntuple_outfilename.
void HelicalFitter::set_silicon_track_map_name (const std::string & map_name) inline
Definition at line 58 of file HelicalFitter.h.
View newest version in sPHENIX GitHub at line 58 of file HelicalFitter.h
References _silicon_track_map_name.
void HelicalFitter::set_steeringfile_name (const std::string & file) inline
Definition at line 63 of file HelicalFitter.h.
View newest version in sPHENIX GitHub at line 63 of file HelicalFitter.h
References file, and steering_outfilename.
void HelicalFitter::set_test_output (bool test) inline
Definition at line 68 of file HelicalFitter.h.
View newest version in sPHENIX GitHub at line 68 of file HelicalFitter.h
References train_ambiguity_solver::test, and test_output.
void HelicalFitter::set_tpc_grouping (int group) inline
Definition at line 66 of file HelicalFitter.h.
View newest version in sPHENIX GitHub at line 66 of file HelicalFitter.h
References tpc_grp.
void HelicalFitter::set_tpc_sector_fixed (unsigned int region, unsigned int sector, unsigned int side)
Definition at line 1278 of file HelicalFitter.cc.
View newest version in sPHENIX GitHub at line 1278 of file HelicalFitter.cc
References fixed_sectors.
void HelicalFitter::set_track_map_name (const std::string & map_name) inline
Definition at line 59 of file HelicalFitter.h.
View newest version in sPHENIX GitHub at line 59 of file HelicalFitter.h
References _track_map_name.
void HelicalFitter::set_use_event_vertex (bool flag) inline
Definition at line 61 of file HelicalFitter.h.
View newest version in sPHENIX GitHub at line 61 of file HelicalFitter.h
References use_event_vertex.
void HelicalFitter::set_vertex (Acts::Vector3 inVertex, Acts::Vector3 inVertex_uncertainty) inline
Definition at line 82 of file HelicalFitter.h.
View newest version in sPHENIX GitHub at line 82 of file HelicalFitter.h
References vertexPosition, and vertexPosUncertainty.
void HelicalFitter::set_vtx_sigma (float x_sigma, float y_sigma) inline
Definition at line 88 of file HelicalFitter.h.
View newest version in sPHENIX GitHub at line 88 of file HelicalFitter.h
References vtx_sigma.
void HelicalFitter::SetDefaultParameters () override virtual
Implements PHParameterInterface.
Definition at line 138 of file HelicalFitter.cc.
View newest version in sPHENIX GitHub at line 138 of file HelicalFitter.cc
Member Data Documentation
ClusterErrorPara HelicalFitter::_ClusErrPara private
Definition at line 158 of file HelicalFitter.h.
View newest version in sPHENIX GitHub at line 158 of file HelicalFitter.h
Referenced by getClusterError().
TrkrClusterContainer* HelicalFitter::_cluster_map {nullptr} private
Definition at line 177 of file HelicalFitter.h.
View newest version in sPHENIX GitHub at line 177 of file HelicalFitter.h
Referenced by addSiliconClusters(), GetNodes(), getTrackletClusterList(), getTrackletClusters(), and process_event().
TpcDistortionCorrectionContainer* HelicalFitter::_dcc_average {nullptr} private
Definition at line 153 of file HelicalFitter.h.
View newest version in sPHENIX GitHub at line 153 of file HelicalFitter.h
Referenced by makeTpcGlobalCorrections().
TpcDistortionCorrectionContainer* HelicalFitter::_dcc_fluctuation {nullptr} private
Definition at line 154 of file HelicalFitter.h.
View newest version in sPHENIX GitHub at line 154 of file HelicalFitter.h
Referenced by makeTpcGlobalCorrections().
TpcDistortionCorrectionContainer* HelicalFitter::_dcc_static {nullptr} private
Definition at line 152 of file HelicalFitter.h.
View newest version in sPHENIX GitHub at line 152 of file HelicalFitter.h
Referenced by makeTpcGlobalCorrections().
TpcDistortionCorrection HelicalFitter::_distortionCorrection private
tpc distortion correction utility class
Definition at line 172 of file HelicalFitter.h.
View newest version in sPHENIX GitHub at line 172 of file HelicalFitter.h
Referenced by makeTpcGlobalCorrections().
std::string HelicalFitter::_field private
Definition at line 193 of file HelicalFitter.h.
View newest version in sPHENIX GitHub at line 193 of file HelicalFitter.h
Referenced by set_field().
int HelicalFitter::_fieldDir = -1 private
Definition at line 194 of file HelicalFitter.h.
View newest version in sPHENIX GitHub at line 194 of file HelicalFitter.h
Referenced by set_field_dir().
std::map<unsigned int, float> HelicalFitter::_layerMisalignment private
Definition at line 195 of file HelicalFitter.h.
View newest version in sPHENIX GitHub at line 195 of file HelicalFitter.h
Referenced by process_event(), and set_error_inflation_factor().
Mille* HelicalFitter::_mille private
Definition at line 106 of file HelicalFitter.h.
View newest version in sPHENIX GitHub at line 106 of file HelicalFitter.h
Referenced by End(), InitRun(), and process_event().
std::string HelicalFitter::_silicon_track_map_name = "SiliconTrackSeedContainer" private
Definition at line 198 of file HelicalFitter.h.
View newest version in sPHENIX GitHub at line 198 of file HelicalFitter.h
Referenced by GetNodes(), and set_silicon_track_map_name().
ActsGeometry* HelicalFitter::_tGeometry {nullptr} private
Definition at line 178 of file HelicalFitter.h.
View newest version in sPHENIX GitHub at line 178 of file HelicalFitter.h
Referenced by addSiliconClusters(), convertTimeToZ(), get_helix_surface_intersection(), get_projectionXY(), getGlobalDerivativesXY(), GetNodes(), getTrackletClusterList(), getTrackletClusters(), and process_event().
std::string HelicalFitter::_track_map_name = "TpcTrackSeedContainer" private
Definition at line 197 of file HelicalFitter.h.
View newest version in sPHENIX GitHub at line 197 of file HelicalFitter.h
Referenced by GetNodes(), and set_track_map_name().
TrackSeedContainer* HelicalFitter::_track_map_silicon {nullptr} private
Definition at line 176 of file HelicalFitter.h.
View newest version in sPHENIX GitHub at line 176 of file HelicalFitter.h
Referenced by GetNodes(), and process_event().
TrackSeedContainer* HelicalFitter::_track_map_tpc {nullptr} private
Definition at line 175 of file HelicalFitter.h.
View newest version in sPHENIX GitHub at line 175 of file HelicalFitter.h
Referenced by GetNodes(), and process_event().
std::string HelicalFitter::data_outfilename = ("mille_helical_output_data_file.bin") private
Definition at line 180 of file HelicalFitter.h.
View newest version in sPHENIX GitHub at line 180 of file HelicalFitter.h
Referenced by InitRun(), and set_datafile_name().
float HelicalFitter::dca_cut = 0.19 private
Definition at line 188 of file HelicalFitter.h.
View newest version in sPHENIX GitHub at line 188 of file HelicalFitter.h
Referenced by addSiliconClusters(), process_event(), and set_dca_cut().
int HelicalFitter::event = 0 private
Definition at line 207 of file HelicalFitter.h.
View newest version in sPHENIX GitHub at line 207 of file HelicalFitter.h
Referenced by process_event().
bool HelicalFitter::fitfulltrack = false private
Definition at line 186 of file HelicalFitter.h.
View newest version in sPHENIX GitHub at line 186 of file HelicalFitter.h
Referenced by process_event(), and set_fitted_subsystems().
bool HelicalFitter::fitsilicon = true private
Definition at line 184 of file HelicalFitter.h.
View newest version in sPHENIX GitHub at line 184 of file HelicalFitter.h
Referenced by process_event(), and set_fitted_subsystems().
bool HelicalFitter::fittpc = false private
Definition at line 185 of file HelicalFitter.h.
View newest version in sPHENIX GitHub at line 185 of file HelicalFitter.h
Referenced by process_event(), and set_fitted_subsystems().
std::set<unsigned int> HelicalFitter::fixed_intt_layers private
Definition at line 161 of file HelicalFitter.h.
View newest version in sPHENIX GitHub at line 161 of file HelicalFitter.h
Referenced by is_intt_layer_fixed(), and set_intt_layer_fixed().
std::set<std::pair<unsigned int,unsigned int> > HelicalFitter::fixed_layer_params private
Definition at line 163 of file HelicalFitter.h.
View newest version in sPHENIX GitHub at line 163 of file HelicalFitter.h
Referenced by is_layer_param_fixed(), and set_layer_param_fixed().
std::set<std::pair<unsigned int,unsigned int> > HelicalFitter::fixed_mvtx_layers private
Definition at line 160 of file HelicalFitter.h.
View newest version in sPHENIX GitHub at line 160 of file HelicalFitter.h
Referenced by is_mvtx_layer_fixed(), and set_mvtx_layer_fixed().
std::set<unsigned int> HelicalFitter::fixed_sectors private
Definition at line 162 of file HelicalFitter.h.
View newest version in sPHENIX GitHub at line 162 of file HelicalFitter.h
Referenced by is_tpc_sector_fixed(), and set_tpc_sector_fixed().
TFile* HelicalFitter::fout {nullptr} private
Definition at line 203 of file HelicalFitter.h.
View newest version in sPHENIX GitHub at line 203 of file HelicalFitter.h
Referenced by End(), and InitRun().
AlignmentDefs::inttGrp HelicalFitter::intt_grp = AlignmentDefs::inttGrp::chp private
Definition at line 167 of file HelicalFitter.h.
View newest version in sPHENIX GitHub at line 167 of file HelicalFitter.h
Referenced by InitRun(), process_event(), and set_intt_grouping().
SvtxAlignmentStateMap* HelicalFitter::m_alignmentmap = nullptr private
Definition at line 191 of file HelicalFitter.h.
View newest version in sPHENIX GitHub at line 191 of file HelicalFitter.h
Referenced by CreateNodes(), and process_event().
TpcClusterZCrossingCorrection HelicalFitter::m_clusterCrossingCorrection private
Definition at line 151 of file HelicalFitter.h.
View newest version in sPHENIX GitHub at line 151 of file HelicalFitter.h
Referenced by makeTpcGlobalCorrections().
SvtxTrackMap* HelicalFitter::m_trackmap = nullptr private
Definition at line 190 of file HelicalFitter.h.
View newest version in sPHENIX GitHub at line 190 of file HelicalFitter.h
Referenced by CreateNodes(), and process_event().
bool HelicalFitter::make_ntuple = true private
Definition at line 200 of file HelicalFitter.h.
View newest version in sPHENIX GitHub at line 200 of file HelicalFitter.h
Referenced by End(), InitRun(), and process_event().
AlignmentDefs::mmsGrp HelicalFitter::mms_grp = AlignmentDefs::mmsGrp::tl private
Definition at line 169 of file HelicalFitter.h.
View newest version in sPHENIX GitHub at line 169 of file HelicalFitter.h
Referenced by InitRun(), and set_mms_grouping().
AlignmentDefs::mvtxGrp HelicalFitter::mvtx_grp = AlignmentDefs::mvtxGrp::snsr private
Definition at line 166 of file HelicalFitter.h.
View newest version in sPHENIX GitHub at line 166 of file HelicalFitter.h
Referenced by InitRun(), process_event(), and set_mvtx_grouping().
TNtuple* HelicalFitter::ntp {nullptr} private
Definition at line 201 of file HelicalFitter.h.
View newest version in sPHENIX GitHub at line 201 of file HelicalFitter.h
Referenced by InitRun(), and process_event().
std::string HelicalFitter::ntuple_outfilename = ("HF_ntuple.root") private
Definition at line 182 of file HelicalFitter.h.
View newest version in sPHENIX GitHub at line 182 of file HelicalFitter.h
Referenced by InitRun(), and set_ntuplefile_name().
std::string HelicalFitter::steering_outfilename = ("steer_helical.txt") private
Definition at line 181 of file HelicalFitter.h.
View newest version in sPHENIX GitHub at line 181 of file HelicalFitter.h
Referenced by InitRun(), and set_steeringfile_name().
bool HelicalFitter::test_output = false private
Definition at line 156 of file HelicalFitter.h.
View newest version in sPHENIX GitHub at line 156 of file HelicalFitter.h
Referenced by InitRun(), and set_test_output().
AlignmentDefs::tpcGrp HelicalFitter::tpc_grp = AlignmentDefs::tpcGrp::htst private
Definition at line 168 of file HelicalFitter.h.
View newest version in sPHENIX GitHub at line 168 of file HelicalFitter.h
Referenced by InitRun(), process_event(), and set_tpc_grouping().
TNtuple* HelicalFitter::track_ntp {nullptr} private
Definition at line 202 of file HelicalFitter.h.
View newest version in sPHENIX GitHub at line 202 of file HelicalFitter.h
Referenced by InitRun(), and process_event().
bool HelicalFitter::use_event_vertex = false private
Definition at line 205 of file HelicalFitter.h.
View newest version in sPHENIX GitHub at line 205 of file HelicalFitter.h
Referenced by process_event(), and set_use_event_vertex().
Acts::Vector3 HelicalFitter::vertexPosition private
Definition at line 209 of file HelicalFitter.h.
View newest version in sPHENIX GitHub at line 209 of file HelicalFitter.h
Referenced by HelicalFitter(), and set_vertex().
Acts::Vector3 HelicalFitter::vertexPosUncertainty private
Definition at line 210 of file HelicalFitter.h.
View newest version in sPHENIX GitHub at line 210 of file HelicalFitter.h
Referenced by set_vertex().
Acts::Vector2 HelicalFitter::vtx_sigma private
Definition at line 211 of file HelicalFitter.h.
View newest version in sPHENIX GitHub at line 211 of file HelicalFitter.h
Referenced by HelicalFitter(), process_event(), and set_vtx_sigma().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/TrackerMillepedeAlignment/HelicalFitter.h
coresoftware/blob/master/offline/packages/TrackerMillepedeAlignment/HelicalFitter.cc