Analysis Software: ClientHistoList Class Reference
ClientHistoList Class Reference
#include <OnlMon/blob/main/onlmonclient/ClientHistoList.h>
Public Member Functions
ClientHistoList ()
ClientHistoList (const std::string &subsys)
virtual ~ClientHistoList ()
TH1 * Histo () const
void Histo (TH1 *Histo)
const std::string ServerHost () const
void ServerHost (const std::string &ServerHost)
const std::string SubSystem () const
void SubSystem (const std::string &SubSystem)
void ServerPort (const int port)
int ServerPort () const
void identify (std::ostream &os=std::cout) const
Protected Attributes
TH1 * histo
int serverport
std::string serverhost
std::string subsystem
Detailed Description
Definition at line 9 of file ClientHistoList.h.
View newest version in sPHENIX GitHub at line 9 of file ClientHistoList.h
Constructor & Destructor Documentation
ClientHistoList::ClientHistoList ()
Definition at line 5 of file ClientHistoList.cc.
View newest version in sPHENIX GitHub at line 5 of file ClientHistoList.cc
ClientHistoList::ClientHistoList (const std::string & subsys) explicit
Definition at line 13 of file ClientHistoList.cc.
View newest version in sPHENIX GitHub at line 13 of file ClientHistoList.cc
ClientHistoList::~ClientHistoList () virtual
Definition at line 22 of file ClientHistoList.cc.
View newest version in sPHENIX GitHub at line 22 of file ClientHistoList.cc
References histo.
Member Function Documentation
TH1 * ClientHistoList::Histo () const
Definition at line 27 of file ClientHistoList.cc.
View newest version in sPHENIX GitHub at line 27 of file ClientHistoList.cc
References histo.
Referenced by Histo(), and OnlMonClient::updateHistoMap().
void ClientHistoList::Histo (TH1 * Histo)
Definition at line 32 of file ClientHistoList.cc.
View newest version in sPHENIX GitHub at line 32 of file ClientHistoList.cc
References Histo(), and histo.
void ClientHistoList::identify (std::ostream & os = std::cout) const
Definition at line 62 of file ClientHistoList.cc.
View newest version in sPHENIX GitHub at line 62 of file ClientHistoList.cc
References histo, serverhost, serverport, and subsystem.
const std::string ClientHistoList::ServerHost () const
Definition at line 39 of file ClientHistoList.cc.
View newest version in sPHENIX GitHub at line 39 of file ClientHistoList.cc
References serverhost.
Referenced by OnlMonClient::PutHistoInMap(), and ServerHost().
void ClientHistoList::ServerHost (const std::string & ServerHost)
Definition at line 44 of file ClientHistoList.cc.
View newest version in sPHENIX GitHub at line 44 of file ClientHistoList.cc
References ServerHost(), and serverhost.
void ClientHistoList::ServerPort (const int port)
Definition at line 70 of file ClientHistoList.cc.
View newest version in sPHENIX GitHub at line 70 of file ClientHistoList.cc
References serverport.
Referenced by OnlMonClient::PutHistoInMap().
int ClientHistoList::ServerPort () const
Definition at line 76 of file ClientHistoList.cc.
View newest version in sPHENIX GitHub at line 76 of file ClientHistoList.cc
References serverport.
const std::string ClientHistoList::SubSystem () const
Definition at line 51 of file ClientHistoList.cc.
View newest version in sPHENIX GitHub at line 51 of file ClientHistoList.cc
References subsystem.
Referenced by OnlMonClient::registerHisto(), and SubSystem().
void ClientHistoList::SubSystem (const std::string & SubSystem)
Definition at line 56 of file ClientHistoList.cc.
View newest version in sPHENIX GitHub at line 56 of file ClientHistoList.cc
References SubSystem(), and subsystem.
Member Data Documentation
TH1* ClientHistoList::histo protected
Definition at line 28 of file ClientHistoList.h.
View newest version in sPHENIX GitHub at line 28 of file ClientHistoList.h
Referenced by Histo(), identify(), and ~ClientHistoList().
std::string ClientHistoList::serverhost protected
Definition at line 30 of file ClientHistoList.h.
View newest version in sPHENIX GitHub at line 30 of file ClientHistoList.h
Referenced by identify(), and ServerHost().
int ClientHistoList::serverport protected
Definition at line 29 of file ClientHistoList.h.
View newest version in sPHENIX GitHub at line 29 of file ClientHistoList.h
Referenced by identify(), and ServerPort().
std::string ClientHistoList::subsystem protected
Definition at line 31 of file ClientHistoList.h.
View newest version in sPHENIX GitHub at line 31 of file ClientHistoList.h
Referenced by identify(), and SubSystem().
The documentation for this class was generated from the following files:
OnlMon/blob/main/onlmonclient/ClientHistoList.h
OnlMon/blob/main/onlmonclient/ClientHistoList.cc