Analysis Software: g4evalfn Namespace Reference
g4evalfn Namespace Reference
Enumerations
enum DET { MVTX =0, INTT =1, TPC =2, TPOT =3 }
Functions
int trklayer_det (int layer)
int trklayer_det (TrkrDefs::hitsetkey key)
int trklayer_det (TrkrDefs::cluskey key)
std::vector< int > unmatchedSvtxTrkIds (EmbRecoMatchContainer *matches, SvtxTrackMap *m_SvtxTrackMap)
TrkrClusLoc clusloc_PHG4 (TrkrClusterIsMatcher *ismatcher, TrkrDefs::cluskey key)
TrkrClusLoc clusloc_SVTX (TrkrClusterIsMatcher *ismatcher, TrkrDefs::cluskey key)
float calc_match_statistic (TrkrClusterIsMatcher *ismatcher, TrkrDefs::cluskey key_A, TrkrDefs::cluskey key_B)
float abs_dphi (float aphi, float bphi)
Enumeration Type Documentation
enum g4evalfn::DET
Enumerator:
MVTX
INTT
TPC
TPOT
Definition at line 12 of file g4evalfn.h.
View newest version in sPHENIX GitHub at line 12 of file g4evalfn.h
Function Documentation
float g4evalfn::abs_dphi (float aphi, float bphi) inline
Definition at line 21 of file g4evalfn.h.
View newest version in sPHENIX GitHub at line 21 of file g4evalfn.h
Referenced by calc_match_statistic(), and TrkrClusterIsMatcher::operator()().
float g4evalfn::calc_match_statistic (TrkrClusterIsMatcher * ismatcher, TrkrDefs::cluskey key_A, TrkrDefs::cluskey key_B)
Definition at line 64 of file g4evalfn.cc.
View newest version in sPHENIX GitHub at line 64 of file g4evalfn.cc
References abs_dphi(), INTTVtxZ::dphi, TrkrClusterContainer::findCluster(), TrkrDefs::getLayer(), layer, TrkrClusterIsMatcher::m_RecoClusters, TrkrClusterIsMatcher::m_TruthClusters, TrkrClusterIsMatcher::single_bin_phi_TPC, TrkrClusterIsMatcher::single_bin_t_TPC, TrkrClusterIsMatcher::single_pixel_phi_INTT, TrkrClusterIsMatcher::single_pixel_phi_MVTX, TrkrClusterIsMatcher::single_pixel_z_MVTX, TrkrClusterIsMatcher::tol_pitch_phi, TrkrClusterIsMatcher::tol_pitch_z_MVTX, TrkrClusterIsMatcher::tol_step_t_TPC, and trklayer_det().
Referenced by TrackClusEvaluator::find_matches().
TrkrClusLoc g4evalfn::clusloc_PHG4 (TrkrClusterIsMatcher * ismatcher, TrkrDefs::cluskey key)
Definition at line 48 of file g4evalfn.cc.
View newest version in sPHENIX GitHub at line 48 of file g4evalfn.cc
References TrkrClusterContainer::findCluster(), ActsGeometry::getGlobalPosition(), TrkrDefs::getLayer(), TrkrClusterIsMatcher::m_ActsGeometry, and TrkrClusterIsMatcher::m_TruthClusters.
Referenced by TrackClusEvaluator::clusloc_matched(), TrackClusEvaluator::phg4_clusloc_all(), and TrackClusEvaluator::phg4_clusloc_unmatched().
TrkrClusLoc g4evalfn::clusloc_SVTX (TrkrClusterIsMatcher * ismatcher, TrkrDefs::cluskey key)
Definition at line 56 of file g4evalfn.cc.
View newest version in sPHENIX GitHub at line 56 of file g4evalfn.cc
References TrkrClusterContainer::findCluster(), ActsGeometry::getGlobalPosition(), TrkrDefs::getLayer(), TrkrClusterIsMatcher::m_ActsGeometry, and TrkrClusterIsMatcher::m_RecoClusters.
Referenced by TrackClusEvaluator::svtx_clusloc_all(), and TrackClusEvaluator::svtx_clusloc_unmatched().
int g4evalfn::trklayer_det (int layer)
Definition at line 15 of file g4evalfn.cc.
View newest version in sPHENIX GitHub at line 15 of file g4evalfn.cc
References INTT, MVTX, TPC, and TPOT.
Referenced by calc_match_statistic(), TrackClusEvaluator::cnt_matchedclus(), TrackClusEvaluator::cntclus(), TrkrClusterIsMatcher::operator()(), and trklayer_det().
int g4evalfn::trklayer_det (TrkrDefs::hitsetkey key)
Definition at line 22 of file g4evalfn.cc.
View newest version in sPHENIX GitHub at line 22 of file g4evalfn.cc
References TrkrDefs::getLayer(), and trklayer_det().
int g4evalfn::trklayer_det (TrkrDefs::cluskey key)
Definition at line 26 of file g4evalfn.cc.
View newest version in sPHENIX GitHub at line 26 of file g4evalfn.cc
References TrkrDefs::getLayer(), and trklayer_det().
std::vector< int > g4evalfn::unmatchedSvtxTrkIds (EmbRecoMatchContainer * matches, SvtxTrackMap * m_SvtxTrackMap)
Definition at line 31 of file g4evalfn.cc.
View newest version in sPHENIX GitHub at line 31 of file g4evalfn.cc
References SvtxTrackMap::begin(), SvtxTrackMap::end(), EmbRecoMatchContainer::ids_RecoMatched(), and Acts::Experimental::detail::BlueprintHelper::sort().