Analysis Software: analysis/blob/master/Prototype2/EMCal/macros/getMeanRMS.C File Reference
getMeanRMS.C File Reference
#include <cmath>
#include <vector>
#include <TFile.h>
#include <TString.h>
#include <TLine.h>
#include <TGraph.h>
#include <TLatex.h>
#include <TAxis.h>
#include <TGraphErrors.h>
#include <TMultiGraph.h>
#include <TLegend.h>
#include <TCanvas.h>
#include <TF1.h>
#include <TH1.h>
#include <TMath.h>
#include <cassert>
#include <iostream>
#include <fstream>
#include "SaveCanvas.C"
Functions
Double_t langaufun (Double_t *x, Double_t *par)
void getMeanRMS (void)
Function Documentation
void getMeanRMS (void)
Definition at line 80 of file getMeanRMS.C.
View newest version in sPHENIX GitHub at line 80 of file getMeanRMS.C
References _file0, assert, check_license::err(), gr, h, i, j, langaufun(), leg, Acts::UnitConstants::min, CKF_timing_vs_mu::mu, perf_headwind::name, rms(), and SaveCanvas().
Double_t langaufun (Double_t * x, Double_t * par)
Definition at line 23 of file getMeanRMS.C.
View newest version in sPHENIX GitHub at line 23 of file getMeanRMS.C
References i, step, and sum().
Referenced by getMeanRMS(), and langaufit().