Analysis Software: macros/blob/master/calibrations/calo/tower_slope_macro/G4_HcalIn_ref.C File Reference
G4_HcalIn_ref.C File Reference
#include <GlobalVariables.C>
#include <QA.C>
#include <g4calo/HcalRawTowerBuilder.h>
#include <g4calo/RawTowerDigitizer.h>
#include <g4detectors/PHG4CylinderSubsystem.h>
#include <g4detectors/PHG4HcalCellReco.h>
#include <g4detectors/PHG4InnerHcalSubsystem.h>
#include <g4eval/CaloEvaluator.h>
#include <g4main/PHG4Reco.h>
#include <caloreco/RawClusterBuilderGraph.h>
#include <caloreco/RawClusterBuilderTemplate.h>
#include <caloreco/RawTowerCalibration.h>
#include <qa_modules/QAG4SimulationCalorimeter.h>
#include <fun4all/Fun4AllServer.h>
Namespaces
namespace Enable
namespace G4HCALIN
Macros
#define MACRO_G4HCALINREF_C
Enumerations
enum G4HCALIN::enu_HCalIn_clusterizer { G4HCALIN::kHCalInGraphClusterizer, G4HCALIN::kHCalInTemplateClusterizer, G4HCALIN::kHCalInGraphClusterizer, G4HCALIN::kHCalInTemplateClusterizer }
Functions
void HCalInner_SupportRing (PHG4Reco *g4Reco)
A rough version of the inner HCal support ring, from Richie's CAD drawing. - Jin.
void HCalInnerInit (const int iflag=0)
double HCalInner (PHG4Reco *g4Reco, double radius, const int crossings)
void HCALInner_Cells ()
void HCALInner_Towers ()
void HCALInner_Clusters ()
void HCALInner_Eval (const std::string &outputfile)
void HCALInner_QA ()
Variables
bool Enable::HCALIN = false
bool Enable::HCALIN_ABSORBER = false
bool Enable::HCALIN_OVERLAPCHECK = false
bool Enable::HCALIN_CELL = false
bool Enable::HCALIN_TOWER = false
bool Enable::HCALIN_CLUSTER = false
bool Enable::HCALIN_EVAL = false
bool Enable::HCALIN_QA = false
bool Enable::HCALIN_SUPPORT = false
int Enable::HCALIN_VERBOSITY = 0
double G4HCALIN::support_ring_outer_radius = 178.0 - 0.001
double G4HCALIN::support_ring_z_ring2 = (2150 + 2175) / 2. / 10.
double G4HCALIN::dz = 25. / 10.
bool G4HCALIN::inner_hcal_material_Al = true
int G4HCALIN::inner_hcal_eic = 0
RawTowerDigitizer::enu_digi_algorithm G4HCALIN::TowerDigi = RawTowerDigitizer::kSimple_photon_digitization
enu_HCalIn_clusterizer G4HCALIN::HCalIn_clusterizer = kHCalInTemplateClusterizer
template clusterizer, RawClusterBuilderTemplate, as developed by Sasha Bazilevsky
Macro Definition Documentation
#define MACRO_G4HCALINREF_C
Definition at line 3 of file G4_HcalIn_ref.C.
View newest version in sPHENIX GitHub at line 3 of file G4_HcalIn_ref.C
Function Documentation
double HCalInner (PHG4Reco * g4Reco, double radius, const int crossings)
Definition at line 95 of file G4_HcalIn_ref.C.
View newest version in sPHENIX GitHub at line 95 of file G4_HcalIn_ref.C
References Enable::ABSORBER, PHG4DetectorSubsystem::get_double_param(), Enable::HCALIN_ABSORBER, Enable::HCALIN_OVERLAPCHECK, Enable::HCALIN_VERBOSITY, HCalInner_SupportRing(), G4HCALIN::inner_hcal_material_Al, no_overlapp, PHG4DetectorSubsystem::OverlapCheck(), Enable::OVERLAPCHECK, PHG4Reco::registerSubsystem(), PHG4DetectorSubsystem::set_string_param(), PHG4DetectorSubsystem::SetAbsorberActive(), PHG4DetectorSubsystem::SetActive(), PHG4DetectorSubsystem::SuperDetector(), verbosity, and Enable::VERBOSITY.
void HCALInner_Cells ()
Definition at line 213 of file G4_HcalIn_ref.C.
View newest version in sPHENIX GitHub at line 213 of file G4_HcalIn_ref.C
References PHG4HcalCellReco::Detector(), Enable::HCALIN_VERBOSITY, Fun4AllServer::instance(), Fun4AllServer::registerSubsystem(), verbosity, and Enable::VERBOSITY.
void HCALInner_Clusters ()
Definition at line 302 of file G4_HcalIn_ref.C.
View newest version in sPHENIX GitHub at line 302 of file G4_HcalIn_ref.C
References RawClusterBuilderGraph::Detector(), RawClusterBuilderTemplate::Detector(), G4HCALIN::HCalIn_clusterizer, Enable::HCALIN_VERBOSITY, Fun4AllServer::instance(), G4HCALIN::kHCalInGraphClusterizer, G4HCALIN::kHCalInTemplateClusterizer, Fun4AllServer::registerSubsystem(), RawClusterBuilderTemplate::SetCylindricalGeometry(), verbosity, Enable::VERBOSITY, and Fun4AllBase::Verbosity().
void HCALInner_Eval (const std::string & outputfile)
Definition at line 331 of file G4_HcalIn_ref.C.
View newest version in sPHENIX GitHub at line 331 of file G4_HcalIn_ref.C
References Enable::HCALIN_VERBOSITY, Fun4AllServer::instance(), Fun4AllServer::registerSubsystem(), verbosity, Enable::VERBOSITY, and Fun4AllBase::Verbosity().
void HCALInner_QA ()
Definition at line 343 of file G4_HcalIn_ref.C.
View newest version in sPHENIX GitHub at line 343 of file G4_HcalIn_ref.C
References Enable::HCALIN_VERBOSITY, Fun4AllServer::instance(), Enable::QA_VERBOSITY, Fun4AllServer::registerSubsystem(), verbosity, and Fun4AllBase::Verbosity().
Referenced by Fun4All_AnaTutorial_sPHENIX(), Fun4All_AnaTutorial_sPHENIX_Jets(), Fun4All_G4_sPHENIX(), Fun4All_G4_sPHENIX_ForTrackCutStudy(), Fun4All_G4_sPHENIX_ForTrackCutStudy_EmbedScanOff(), Fun4All_G4_sPHENIX_ForTrackCutStudy_EmbedScanOn(), Fun4All_G4_sPHENIX_ForTrackCutStudy_WithPileup_EmbedScanOff(), Fun4All_G4_sPHENIX_ForTrackCutStudy_WithPileup_EmbedScanOn(), Fun4All_Pi0Gen_sPHENIX(), Fun4All_pi0tbt_SIMPLE_EMBED(), Fun4All_RunNewTruthMatcher(), Fun4All_SinglePhotonGen_sPHENIX(), and Fun4All_SinglePi0Gen_sPHENIX().
void HCalInner_SupportRing (PHG4Reco * g4Reco)
A rough version of the inner HCal support ring, from Richie's CAD drawing. - Jin.
Definition at line 176 of file G4_HcalIn_ref.C.
View newest version in sPHENIX GitHub at line 176 of file G4_HcalIn_ref.C
References G4HCALIN::dz, Enable::HCALIN_SUPPORT, i, G4HCALIN::inner_hcal_eic, PHG4Reco::registerSubsystem(), PHG4DetectorSubsystem::set_double_param(), PHG4DetectorSubsystem::set_int_param(), PHG4DetectorSubsystem::set_string_param(), PHG4DetectorSubsystem::SetActive(), PHG4DetectorSubsystem::SuperDetector(), Enable::SUPPORT, G4HCALIN::support_ring_outer_radius, and G4HCALIN::support_ring_z_ring2.
void HCALInner_Towers ()
Definition at line 237 of file G4_HcalIn_ref.C.
View newest version in sPHENIX GitHub at line 237 of file G4_HcalIn_ref.C
References HcalRawTowerBuilder::Detector(), RawTowerCalibration::Detector(), RawTowerDigitizer::Detector(), Acts::UnitConstants::e, Enable::HCALIN_VERBOSITY, G4HCALIN::inner_hcal_material_Al, Fun4AllServer::instance(), RawTowerCalibration::kDbfile_tbt_gain_corr, RawTowerDigitizer::kNo_digitization, Fun4AllServer::registerSubsystem(), RawTowerCalibration::set_calib_algorithm(), RawTowerCalibration::set_calib_const_GeV_ADC(), RawTowerCalibration::set_CalibrationFileName(), RawTowerDigitizer::set_digi_algorithm(), RawTowerCalibration::set_pedstal_ADC(), RawTowerDigitizer::set_pedstal_central_ADC(), RawTowerDigitizer::set_pedstal_width_ADC(), RawTowerDigitizer::set_photonelec_ADC(), RawTowerDigitizer::set_photonelec_yield_visible_GeV(), HcalRawTowerBuilder::set_sim_tower_node_prefix(), RawTowerCalibration::set_UseConditionsDB(), RawTowerDigitizer::set_zero_suppression_ADC(), G4HCALIN::TowerDigi, verbosity, Enable::VERBOSITY, and Fun4AllBase::Verbosity().
void HCalInnerInit (const int iflag = 0)
Definition at line 84 of file G4_HcalIn_ref.C.
View newest version in sPHENIX GitHub at line 84 of file G4_HcalIn_ref.C
References G4HCALIN::dz, G4HCALIN::inner_hcal_eic, BlackHoleGeometry::max_radius, BlackHoleGeometry::max_z, Acts::UnitConstants::min, BlackHoleGeometry::min_z, G4HCALIN::support_ring_outer_radius, and G4HCALIN::support_ring_z_ring2.