Analysis Software: ReadMLPnew Class Reference
ReadMLPnew Class Reference
Public Member Functions
ReadMLPnew (std::vector< std::string > &theInputVars)
virtual ~ReadMLPnew ()
double GetMvaValue (const std::vector< double > &inputValues) const override
Public Member Functions inherited from IClassifierReader
IClassifierReader ()
virtual ~IClassifierReader ()
bool IsStatusClean () const
IClassifierReader ()
virtual ~IClassifierReader ()
bool IsStatusClean () const
IClassifierReader ()
virtual ~IClassifierReader ()
bool IsStatusClean () const
IClassifierReader ()
virtual ~IClassifierReader ()
bool IsStatusClean () const
IClassifierReader ()
virtual ~IClassifierReader ()
bool IsStatusClean () const
IClassifierReader ()
virtual ~IClassifierReader ()
bool IsStatusClean () const
IClassifierReader ()
virtual ~IClassifierReader ()
bool IsStatusClean () const
IClassifierReader ()
virtual ~IClassifierReader ()
bool IsStatusClean () const
IClassifierReader ()
virtual ~IClassifierReader ()
bool IsStatusClean () const
IClassifierReader ()
virtual ~IClassifierReader ()
bool IsStatusClean () const
IClassifierReader ()
virtual ~IClassifierReader ()
bool IsStatusClean () const
IClassifierReader ()
virtual ~IClassifierReader ()
bool IsStatusClean () const
IClassifierReader ()
virtual ~IClassifierReader ()
bool IsStatusClean () const
IClassifierReader ()
virtual ~IClassifierReader ()
bool IsStatusClean () const
IClassifierReader ()
virtual ~IClassifierReader ()
bool IsStatusClean () const
IClassifierReader ()
virtual ~IClassifierReader ()
bool IsStatusClean () const
IClassifierReader ()
virtual ~IClassifierReader ()
bool IsStatusClean () const
IClassifierReader ()
virtual ~IClassifierReader ()
bool IsStatusClean () const
IClassifierReader ()
virtual ~IClassifierReader ()
bool IsStatusClean () const
IClassifierReader ()
virtual ~IClassifierReader ()
bool IsStatusClean () const
IClassifierReader ()
virtual ~IClassifierReader ()
bool IsStatusClean () const
IClassifierReader ()
virtual ~IClassifierReader ()
bool IsStatusClean () const
IClassifierReader ()
virtual ~IClassifierReader ()
bool IsStatusClean () const
IClassifierReader ()
virtual ~IClassifierReader ()
bool IsStatusClean () const
IClassifierReader ()
virtual ~IClassifierReader ()
bool IsStatusClean () const
IClassifierReader ()
virtual ~IClassifierReader ()
bool IsStatusClean () const
Private Member Functions
void Clear ()
void InitTransform_1 ()
void Transform_1 (std::vector< double > &iv, int sigOrBgd) const
void InitTransform ()
void Transform (std::vector< double > &iv, int sigOrBgd) const
size_t GetNvar () const
char GetType (int ivar) const
double NormVariable (double x, double xmin, double xmax) const
void Initialize ()
double GetMvaValue__ (const std::vector< double > &inputValues) const
double ActivationFnc (double x) const
double OutputActivationFnc (double x) const
Private Attributes
double fOff_1 [3][4]
double fScal_1 [3][4]
const char * fClassName
const size_t fNvars
double fVmin [4]
double fVmax [4]
char fType [4]
double fWeightMatrix0to1 [15][5]
double fWeightMatrix1to2 [1][15]
Additional Inherited Members
Protected Attributes inherited from IClassifierReader
bool fStatusIsClean
Detailed Description
Definition at line 101 of file TMVAClassification_MLPnew.class.C.
View newest version in sPHENIX GitHub at line 101 of file TMVAClassification_MLPnew.class.C
Constructor & Destructor Documentation
ReadMLPnew::ReadMLPnew (std::vector< std::string > & theInputVars) inline
Definition at line 106 of file TMVAClassification_MLPnew.class.C.
View newest version in sPHENIX GitHub at line 106 of file TMVAClassification_MLPnew.class.C
References fClassName, fNvars, IClassifierReader::fStatusIsClean, fType, fVmax, fVmin, Initialize(), and InitTransform().
virtual ReadMLPnew::~ReadMLPnew () inline virtual
Definition at line 159 of file TMVAClassification_MLPnew.class.C.
View newest version in sPHENIX GitHub at line 159 of file TMVAClassification_MLPnew.class.C
References Clear().
Member Function Documentation
double ReadMLPnew::ActivationFnc (double x) const private
Definition at line 348 of file TMVAClassification_MLPnew.class.C.
View newest version in sPHENIX GitHub at line 348 of file TMVAClassification_MLPnew.class.C
References KFPMath::a, KFPMath::b, and ambiguity_solver_full_chain::x.
Referenced by GetMvaValue__().
void ReadMLPnew::Clear () inline private
Definition at line 363 of file TMVAClassification_MLPnew.class.C.
View newest version in sPHENIX GitHub at line 363 of file TMVAClassification_MLPnew.class.C
Referenced by ~ReadMLPnew().
double ReadMLPnew::GetMvaValue (const std::vector< double > & inputValues) const inline override virtual
Implements IClassifierReader.
Definition at line 366 of file TMVAClassification_MLPnew.class.C.
View newest version in sPHENIX GitHub at line 366 of file TMVAClassification_MLPnew.class.C
References fClassName, GetMvaValue__(), IClassifierReader::IsStatusClean(), and Transform().
double ReadMLPnew::GetMvaValue__ (const std::vector< double > & inputValues) const inline private
Definition at line 306 of file TMVAClassification_MLPnew.class.C.
View newest version in sPHENIX GitHub at line 306 of file TMVAClassification_MLPnew.class.C
References ActivationFnc(), fWeightMatrix0to1, fWeightMatrix1to2, i, and OutputActivationFnc().
Referenced by GetMvaValue().
size_t ReadMLPnew::GetNvar () const inline private
Definition at line 186 of file TMVAClassification_MLPnew.class.C.
View newest version in sPHENIX GitHub at line 186 of file TMVAClassification_MLPnew.class.C
References fNvars.
char ReadMLPnew::GetType (int ivar) const inline private
Definition at line 187 of file TMVAClassification_MLPnew.class.C.
View newest version in sPHENIX GitHub at line 187 of file TMVAClassification_MLPnew.class.C
References fType.
void ReadMLPnew::Initialize () inline private
Definition at line 214 of file TMVAClassification_MLPnew.class.C.
View newest version in sPHENIX GitHub at line 214 of file TMVAClassification_MLPnew.class.C
References fWeightMatrix0to1, and fWeightMatrix1to2.
Referenced by ReadMLPnew().
void ReadMLPnew::InitTransform () inline private
Definition at line 483 of file TMVAClassification_MLPnew.class.C.
View newest version in sPHENIX GitHub at line 483 of file TMVAClassification_MLPnew.class.C
References InitTransform_1().
Referenced by ReadMLPnew().
void ReadMLPnew::InitTransform_1 () inline private
Definition at line 386 of file TMVAClassification_MLPnew.class.C.
View newest version in sPHENIX GitHub at line 386 of file TMVAClassification_MLPnew.class.C
References fOff_1, and fScal_1.
Referenced by InitTransform().
double ReadMLPnew::NormVariable (double x, double xmin, double xmax) const inline private
Definition at line 192 of file TMVAClassification_MLPnew.class.C.
View newest version in sPHENIX GitHub at line 192 of file TMVAClassification_MLPnew.class.C
References xmin.
double ReadMLPnew::OutputActivationFnc (double x) const private
Definition at line 357 of file TMVAClassification_MLPnew.class.C.
View newest version in sPHENIX GitHub at line 357 of file TMVAClassification_MLPnew.class.C
Referenced by GetMvaValue__().
void ReadMLPnew::Transform (std::vector< double > & iv, int sigOrBgd) const inline private
Definition at line 489 of file TMVAClassification_MLPnew.class.C.
View newest version in sPHENIX GitHub at line 489 of file TMVAClassification_MLPnew.class.C
References Transform_1().
Referenced by GetMvaValue().
void ReadMLPnew::Transform_1 (std::vector< double > & iv, int sigOrBgd) const inline private
Definition at line 442 of file TMVAClassification_MLPnew.class.C.
View newest version in sPHENIX GitHub at line 442 of file TMVAClassification_MLPnew.class.C
References fNvars, fOff_1, fScal_1, and offset.
Referenced by Transform().
Member Data Documentation
const char* ReadMLPnew::fClassName private
Definition at line 183 of file TMVAClassification_MLPnew.class.C.
View newest version in sPHENIX GitHub at line 183 of file TMVAClassification_MLPnew.class.C
Referenced by GetMvaValue(), and ReadMLPnew().
const size_t ReadMLPnew::fNvars private
Definition at line 185 of file TMVAClassification_MLPnew.class.C.
View newest version in sPHENIX GitHub at line 185 of file TMVAClassification_MLPnew.class.C
Referenced by GetNvar(), ReadMLPnew(), and Transform_1().
double ReadMLPnew::fOff_1[3][4] private
Definition at line 175 of file TMVAClassification_MLPnew.class.C.
View newest version in sPHENIX GitHub at line 175 of file TMVAClassification_MLPnew.class.C
Referenced by InitTransform_1(), and Transform_1().
double ReadMLPnew::fScal_1[3][4] private
Definition at line 176 of file TMVAClassification_MLPnew.class.C.
View newest version in sPHENIX GitHub at line 176 of file TMVAClassification_MLPnew.class.C
Referenced by InitTransform_1(), and Transform_1().
char ReadMLPnew::fType[4] private
Definition at line 198 of file TMVAClassification_MLPnew.class.C.
View newest version in sPHENIX GitHub at line 198 of file TMVAClassification_MLPnew.class.C
Referenced by GetType(), and ReadMLPnew().
double ReadMLPnew::fVmax[4] private
Definition at line 191 of file TMVAClassification_MLPnew.class.C.
View newest version in sPHENIX GitHub at line 191 of file TMVAClassification_MLPnew.class.C
Referenced by ReadMLPnew().
double ReadMLPnew::fVmin[4] private
Definition at line 190 of file TMVAClassification_MLPnew.class.C.
View newest version in sPHENIX GitHub at line 190 of file TMVAClassification_MLPnew.class.C
Referenced by ReadMLPnew().
double ReadMLPnew::fWeightMatrix0to1[15][5] private
Definition at line 209 of file TMVAClassification_MLPnew.class.C.
View newest version in sPHENIX GitHub at line 209 of file TMVAClassification_MLPnew.class.C
Referenced by GetMvaValue__(), and Initialize().
double ReadMLPnew::fWeightMatrix1to2[1][15] private
Definition at line 210 of file TMVAClassification_MLPnew.class.C.
View newest version in sPHENIX GitHub at line 210 of file TMVAClassification_MLPnew.class.C
Referenced by GetMvaValue__(), and Initialize().
The documentation for this class was generated from the following file:
analysis/blob/master/HF-Particle/HFTrigger/weights/woutCaloAndMinTrack/TMVAClassification_MLPnew.class.C