Analysis Software: hijbkg_upc Class Reference
hijbkg_upc Class Reference
#include <analysis/blob/master/hbcup/src/hijbkg_upc.h>
Public Member Functions
hijbkg_upc (const std::string &name="hijbkg_upc")
~hijbkg_upc () override
int Init (PHCompositeNode *topNode) override
int InitRun (PHCompositeNode *topNode) override
int process_event (PHCompositeNode *topNode) override
int ResetEvent (PHCompositeNode *topNode) override
Clean up internals after each event.
int EndRun (const int runnumber) override
Called at the end of each run.
int End (PHCompositeNode *topNode) override
Called at the end of all processing.
int Reset (PHCompositeNode *) override
Reset.
void Print (const std::string &what="ALL") const override
Public Member Functions inherited from SubsysReco
~SubsysReco () override
void Print (const std::string &="ALL") const override
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Private Member Functions
int isStableCharged (int pid)
float getpT (PHG4Particle *particle)
float getPhi (PHG4Particle *particle)
float getEta (PHG4Particle *particle)
float getP (PHG4Particle *particle)
Private Attributes
TTree * T
int m_evt
Float_t m_cent = 0
Float_t m_b = 0
TParticle m_part [2]
std::vector< int > m_pid = {0}
std::vector< Float_t > m_pt = {0}
std::vector< Float_t > m_eta = {0}
std::vector< Float_t > m_phi = {0}
std::vector< Float_t > m_e = {0}
std::vector< Float_t > m_p = {0}
Float_t m_psi2 = 0
std::string Outfile
TFile * out
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = std::numeric_limits<int>::max() - 10
}
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Detailed Description
Definition at line 16 of file hijbkg_upc.h.
View newest version in sPHENIX GitHub at line 16 of file hijbkg_upc.h
Constructor & Destructor Documentation
hijbkg_upc::hijbkg_upc (const std::string & name = "hijbkg_upc")
Definition at line 28 of file hijbkg_upc.cc.
View newest version in sPHENIX GitHub at line 28 of file hijbkg_upc.cc
hijbkg_upc::~hijbkg_upc () override
Definition at line 35 of file hijbkg_upc.cc.
View newest version in sPHENIX GitHub at line 35 of file hijbkg_upc.cc
Member Function Documentation
int hijbkg_upc::End (PHCompositeNode * topNode) override virtual
Called at the end of all processing.
Reimplemented from SubsysReco.
Definition at line 174 of file hijbkg_upc.cc.
View newest version in sPHENIX GitHub at line 174 of file hijbkg_upc.cc
References cd(), Close(), Fun4AllReturnCodes::EVENT_OK, out, T, and Write().
int hijbkg_upc::EndRun (const int runnumber) override virtual
Called at the end of each run.
Reimplemented from SubsysReco.
Definition at line 167 of file hijbkg_upc.cc.
View newest version in sPHENIX GitHub at line 167 of file hijbkg_upc.cc
References Fun4AllReturnCodes::EVENT_OK.
float hijbkg_upc::getEta (PHG4Particle * particle) private
Definition at line 212 of file hijbkg_upc.cc.
View newest version in sPHENIX GitHub at line 212 of file hijbkg_upc.cc
References merge_hashes::p.
Referenced by process_event().
float hijbkg_upc::getP (PHG4Particle * particle) private
Definition at line 240 of file hijbkg_upc.cc.
View newest version in sPHENIX GitHub at line 240 of file hijbkg_upc.cc
References merge_hashes::p.
float hijbkg_upc::getPhi (PHG4Particle * particle) private
Definition at line 223 of file hijbkg_upc.cc.
View newest version in sPHENIX GitHub at line 223 of file hijbkg_upc.cc
References ActsTests::PropagationDatasets::phi.
float hijbkg_upc::getpT (PHG4Particle * particle) private
Definition at line 230 of file hijbkg_upc.cc.
View newest version in sPHENIX GitHub at line 230 of file hijbkg_upc.cc
References physmon_track_finding_ttbar::pt.
Referenced by process_event().
int hijbkg_upc::Init (PHCompositeNode * topNode) override virtual
Called during initialization. Typically this is where you can book histograms, and e.g. register them to Fun4AllServer (so they can be output to file using Fun4AllServer::dumpHistos() method).
Reimplemented from SubsysReco.
Definition at line 41 of file hijbkg_upc.cc.
View newest version in sPHENIX GitHub at line 41 of file hijbkg_upc.cc
References Branch(), Fun4AllReturnCodes::EVENT_OK, m_b, m_cent, m_evt, m_part, out, and T.
int hijbkg_upc::InitRun (PHCompositeNode * topNode) override virtual
Called for first event when run number is known. Typically this is where you may want to fetch data from database, because you know the run number. A place to book histograms which have to know the run number.
Reimplemented from SubsysReco.
Definition at line 68 of file hijbkg_upc.cc.
View newest version in sPHENIX GitHub at line 68 of file hijbkg_upc.cc
References Fun4AllReturnCodes::EVENT_OK.
int hijbkg_upc::isStableCharged (int pid) private
Definition at line 198 of file hijbkg_upc.cc.
View newest version in sPHENIX GitHub at line 198 of file hijbkg_upc.cc
Referenced by process_event().
void hijbkg_upc::Print (const std::string & what = "ALL") const override virtual
Print out some info about this module.
Parameters
what can be used to specify what to print exactly.
Reimplemented from Fun4AllBase.
Definition at line 192 of file hijbkg_upc.cc.
View newest version in sPHENIX GitHub at line 192 of file hijbkg_upc.cc
int hijbkg_upc::process_event (PHCompositeNode * topNode) override virtual
Called for each event. This is where you do the real work.
Reimplemented from SubsysReco.
Definition at line 75 of file hijbkg_upc.cc.
View newest version in sPHENIX GitHub at line 75 of file hijbkg_upc.cc
References Fun4AllReturnCodes::ABORTEVENT, Acts::UnitConstants::e, eta, Fun4AllReturnCodes::EVENT_OK, PHG4Particle::get_e(), EventHeader::get_EvtSequence(), PHG4Particle::get_pid(), PHG4Particle::get_px(), PHG4Particle::get_py(), PHG4Particle::get_pz(), getEta(), getpT(), isStableCharged(), m_evt, m_part, ntracks, PHWHERE, train_ambiguity_solver::pid, physmon_track_finding_ttbar::pt, and T.
int hijbkg_upc::Reset (PHCompositeNode * topNode) override virtual
Reset.
Reimplemented from SubsysReco.
Definition at line 185 of file hijbkg_upc.cc.
View newest version in sPHENIX GitHub at line 185 of file hijbkg_upc.cc
References Fun4AllReturnCodes::EVENT_OK.
int hijbkg_upc::ResetEvent (PHCompositeNode * topNode) override virtual
Clean up internals after each event.
Reimplemented from SubsysReco.
Definition at line 154 of file hijbkg_upc.cc.
View newest version in sPHENIX GitHub at line 154 of file hijbkg_upc.cc
References Fun4AllReturnCodes::EVENT_OK, m_e, m_eta, m_phi, m_pid, and m_pt.
Member Data Documentation
Float_t hijbkg_upc::m_b = 0 private
Definition at line 62 of file hijbkg_upc.h.
View newest version in sPHENIX GitHub at line 62 of file hijbkg_upc.h
Referenced by Init().
Float_t hijbkg_upc::m_cent = 0 private
Definition at line 61 of file hijbkg_upc.h.
View newest version in sPHENIX GitHub at line 61 of file hijbkg_upc.h
Referenced by Init().
std::vector<Float_t> hijbkg_upc::m_e = {0} private
Definition at line 69 of file hijbkg_upc.h.
View newest version in sPHENIX GitHub at line 69 of file hijbkg_upc.h
Referenced by ResetEvent().
std::vector<Float_t> hijbkg_upc::m_eta = {0} private
Definition at line 67 of file hijbkg_upc.h.
View newest version in sPHENIX GitHub at line 67 of file hijbkg_upc.h
Referenced by ResetEvent().
int hijbkg_upc::m_evt private
Definition at line 60 of file hijbkg_upc.h.
View newest version in sPHENIX GitHub at line 60 of file hijbkg_upc.h
Referenced by Init(), and process_event().
std::vector<Float_t> hijbkg_upc::m_p = {0} private
Definition at line 70 of file hijbkg_upc.h.
View newest version in sPHENIX GitHub at line 70 of file hijbkg_upc.h
TParticle hijbkg_upc::m_part[2] private
Definition at line 63 of file hijbkg_upc.h.
View newest version in sPHENIX GitHub at line 63 of file hijbkg_upc.h
Referenced by Init(), and process_event().
std::vector<Float_t> hijbkg_upc::m_phi = {0} private
Definition at line 68 of file hijbkg_upc.h.
View newest version in sPHENIX GitHub at line 68 of file hijbkg_upc.h
Referenced by ResetEvent().
std::vector<int> hijbkg_upc::m_pid = {0} private
Definition at line 65 of file hijbkg_upc.h.
View newest version in sPHENIX GitHub at line 65 of file hijbkg_upc.h
Referenced by ResetEvent().
Float_t hijbkg_upc::m_psi2 = 0 private
Definition at line 71 of file hijbkg_upc.h.
View newest version in sPHENIX GitHub at line 71 of file hijbkg_upc.h
std::vector<Float_t> hijbkg_upc::m_pt = {0} private
Definition at line 66 of file hijbkg_upc.h.
View newest version in sPHENIX GitHub at line 66 of file hijbkg_upc.h
Referenced by ResetEvent().
TFile* hijbkg_upc::out private
Definition at line 74 of file hijbkg_upc.h.
View newest version in sPHENIX GitHub at line 74 of file hijbkg_upc.h
Referenced by End(), and Init().
std::string hijbkg_upc::Outfile private
Definition at line 73 of file hijbkg_upc.h.
View newest version in sPHENIX GitHub at line 73 of file hijbkg_upc.h
TTree* hijbkg_upc::T private
Definition at line 59 of file hijbkg_upc.h.
View newest version in sPHENIX GitHub at line 59 of file hijbkg_upc.h
Referenced by End(), Init(), and process_event().
The documentation for this class was generated from the following files:
analysis/blob/master/hbcup/src/hijbkg_upc.h
analysis/blob/master/hbcup/src/hijbkg_upc.cc