Analysis Software: acts/blob/sPHENIX/Tests/UnitTests/Alignment/Kernel/AlignmentTests.cpp File Reference
AlignmentTests.cpp File Reference
#include <boost/test/unit_test.hpp>
#include "Acts/Definitions/Units.hpp"
#include "Acts/EventData/TrackParameters.hpp"
#include "Acts/Geometry/CuboidVolumeBounds.hpp"
#include "Acts/Geometry/CuboidVolumeBuilder.hpp"
#include "Acts/Geometry/GeometryContext.hpp"
#include "Acts/Geometry/LayerArrayCreator.hpp"
#include "Acts/Geometry/LayerCreator.hpp"
#include "Acts/Geometry/PlaneLayer.hpp"
#include "Acts/Geometry/SurfaceArrayCreator.hpp"
#include "Acts/Geometry/TrackingGeometry.hpp"
#include "Acts/Geometry/TrackingGeometryBuilder.hpp"
#include "Acts/Geometry/TrackingVolume.hpp"
#include "Acts/MagneticField/ConstantBField.hpp"
#include "Acts/MagneticField/MagneticFieldContext.hpp"
#include "Acts/Material/HomogeneousSurfaceMaterial.hpp"
#include "Acts/Material/ISurfaceMaterial.hpp"
#include "Acts/Propagator/EigenStepper.hpp"
#include "Acts/Propagator/Navigator.hpp"
#include "Acts/Propagator/Propagator.hpp"
#include "Acts/Propagator/StraightLineStepper.hpp"
#include "Acts/Surfaces/PlaneSurface.hpp"
#include "Acts/Surfaces/RectangleBounds.hpp"
#include "Acts/Tests/CommonHelpers/DetectorElementStub.hpp"
#include "Acts/Tests/CommonHelpers/FloatComparisons.hpp"
#include "Acts/Tests/CommonHelpers/MeasurementsCreator.hpp"
#include "Acts/Tests/CommonHelpers/PredefinedMaterials.hpp"
#include "Acts/Tests/CommonHelpers/TestSourceLink.hpp"
#include "Acts/TrackFitting/GainMatrixSmoother.hpp"
#include "Acts/TrackFitting/GainMatrixUpdater.hpp"
#include "Acts/TrackFitting/KalmanFitter.hpp"
#include "Acts/TrackFitting/detail/KalmanGlobalCovariance.hpp"
#include "Acts/Utilities/CalibrationContext.hpp"
#include "ActsAlignment/Kernel/Alignment.hpp"
#include <cmath>
#include <random>
#include <string>
Functions
BOOST_AUTO_TEST_CASE (ZeroFieldKalmanAlignment)
Unit test for KF-based alignment algorithm.
Function Documentation
BOOST_AUTO_TEST_CASE (ZeroFieldKalmanAlignment)
Unit test for KF-based alignment algorithm.
Definition at line 277 of file AlignmentTests.cpp.
View newest version in sPHENIX GitHub at line 277 of file AlignmentTests.cpp
References ActsAlignment::AlignmentOptions< fit_options_t >::alignedDetElements, Acts::Test::calCtx, CHECK_CLOSE_ABS, Acts::UnitConstants::e, conf::extensions, Acts::KalmanFitterOptions< traj_t >::geoContext, geoCtx, Acts::Test::geometry, Acts::getDefaultLogger(), Acts::Logging::INFO, magCtx, makeConstantFieldPropagator(), ActsAlignment::AlignmentOptions< fit_options_t >::maxIterations, testing::internal::move(), proj(), and Acts::KalmanFitterOptions< traj_t >::referenceSurface.