Analysis Software: Jetscape::JetScapeSignalManager Class Reference
Jetscape::JetScapeSignalManager Class Reference
#include <JETSCAPE/blob/main/src/framework/JetScapeSignalManager.h>
Public Member Functions
void SetInitialStatePointer (shared_ptr< InitialState > m_initial)
weak_ptr< InitialState > GetInitialStatePointer ()
void SetPreEquilibriumPointer (shared_ptr< PreequilibriumDynamics > m_pre_eq)
weak_ptr< PreequilibriumDynamics > GetPreEquilibriumPointer ()
void SetHydroPointer (shared_ptr< FluidDynamics > m_hydro)
weak_ptr< FluidDynamics > GetHydroPointer ()
void SetSoftParticlizationPointer (shared_ptr< SoftParticlization > m_soft)
weak_ptr< SoftParticlization > GetSoftParticlizationPointer ()
void SetJetEnergyLossManagerPointer (shared_ptr< JetEnergyLossManager > m_jloss)
weak_ptr< JetEnergyLossManager > GetJetEnergyLossManagerPointer ()
void SetHardProcessPointer (shared_ptr< HardProcess > m_hardp)
weak_ptr< HardProcess > GetHardProcessPointer ()
void SetWriterPointer (shared_ptr< JetScapeWriter > m_writer)
weak_ptr< JetScapeWriter > GetWriterPointer ()
void SetHadronizationManagerPointer (shared_ptr< HadronizationManager > m_hadro)
weak_ptr< HadronizationManager > GetHadronizationManagerPointer ()
void SetPartonPrinterPointer (shared_ptr< PartonPrinter > m_pprinter)
weak_ptr< PartonPrinter > GetPartonPrinterPointer ()
void SetHadronPrinterPointer (shared_ptr< HadronPrinter > m_hprinter)
weak_ptr< HadronPrinter > GetHadronPrinterPointer ()
void SetEnergyLossPointer (shared_ptr< JetEnergyLoss > m_eloss)
weak_ptr< JetEnergyLoss > GetEnergyLossPointer ()
void ConnectJetSignal (shared_ptr< JetEnergyLoss > j)
void ConnectEdensitySignal (shared_ptr< JetEnergyLoss > j)
void ConnectGetHydroTau0Signal (shared_ptr< JetEnergyLoss > j)
void ConnectGetHydroCellSignal (shared_ptr< JetEnergyLoss > j)
void ConnectGetHydroCellSignal (shared_ptr< LiquefierBase > l)
void ConnectGetHydroCellSignal (shared_ptr< Hadronization > h)
void ConnectGetHardPartonListSignal (shared_ptr< JetEnergyLossManager > jm)
void ConnectSentInPartonsSignal (shared_ptr< JetEnergyLoss > j, shared_ptr< JetEnergyLoss > j2)
void ConnectGetFinalPartonListSignal (shared_ptr< HadronizationManager > hm)
void ConnectTransformPartonsSignal (shared_ptr< Hadronization > h, shared_ptr< Hadronization > h2)
void ConnectGetFinalHadronListSignal (shared_ptr< HadronPrinter > h)
void ConnectGetHydroHyperSurfaceSignal (shared_ptr< Hadronization > h)
void DisconnectSignal ()
void CleanUp ()
int GetNumberOfJetSignals ()
int GetNumberOfEdensitySignals ()
int GetNumberOfGetHydroCellSignals ()
void PrintJetSignalMap ()
void PrintEdensitySignalMap ()
void PrintGetHydroCellSignalMap ()
void PrintSentInPartonsSignalMap ()
void PrintTransformPartonsSignalMap ()
Static Public Member Functions
static JetScapeSignalManager * Instance ()
Private Member Functions
JetScapeSignalManager ()
JetScapeSignalManager (JetScapeSignalManager const &)
Private Attributes
weak_ptr< InitialState > initial_state
weak_ptr< PreequilibriumDynamics > pre_equilibrium
weak_ptr< FluidDynamics > hydro
weak_ptr< JetEnergyLossManager > jloss
weak_ptr< HardProcess > hardp
weak_ptr< JetScapeWriter > writer
weak_ptr< HadronizationManager > hadro
weak_ptr< Afterburner > afterburner
weak_ptr< PartonPrinter > pprinter
weak_ptr< HadronPrinter > hprinter
weak_ptr< JetEnergyLoss > eloss
weak_ptr< SoftParticlization > softparticlization
int num_jet_signals = 0
int num_edensity_signals = 0
int num_GetHydroCellSignals = 0
int num_SentInPartons = 0
int num_TransformPartons = 0
map< int, weak_ptr
< JetEnergyLoss > > jet_signal_map
map< int, weak_ptr
< JetEnergyLoss > > edensity_signal_map
map< int, weak_ptr
< JetEnergyLoss > > GetHydroCellSignal_map
map< int, weak_ptr
< JetEnergyLoss > > SentInPartons_map
map< int, weak_ptr
< Hadronization > > TransformPartons_map
Static Private Attributes
static JetScapeSignalManager * m_pInstance = NULL
Detailed Description
Definition at line 43 of file JetScapeSignalManager.h.
View newest version in sPHENIX GitHub at line 43 of file JetScapeSignalManager.h
Constructor & Destructor Documentation
Jetscape::JetScapeSignalManager::JetScapeSignalManager () inline private
Definition at line 147 of file JetScapeSignalManager.h.
View newest version in sPHENIX GitHub at line 147 of file JetScapeSignalManager.h
Jetscape::JetScapeSignalManager::JetScapeSignalManager (JetScapeSignalManager const &) inline private
Definition at line 148 of file JetScapeSignalManager.h.
View newest version in sPHENIX GitHub at line 148 of file JetScapeSignalManager.h
Member Function Documentation
void Jetscape::JetScapeSignalManager::CleanUp ()
Definition at line 184 of file JetScapeSignalManager.cc.
View newest version in sPHENIX GitHub at line 184 of file JetScapeSignalManager.cc
References i, and VERBOSE.
void Jetscape::JetScapeSignalManager::ConnectEdensitySignal (shared_ptr< JetEnergyLoss > j)
Definition at line 79 of file JetScapeSignalManager.cc.
View newest version in sPHENIX GitHub at line 79 of file JetScapeSignalManager.cc
void Jetscape::JetScapeSignalManager::ConnectGetFinalHadronListSignal (shared_ptr< HadronPrinter > h)
Definition at line 163 of file JetScapeSignalManager.cc.
View newest version in sPHENIX GitHub at line 163 of file JetScapeSignalManager.cc
Referenced by Jetscape::HadronPrinter::Init().
void Jetscape::JetScapeSignalManager::ConnectGetFinalPartonListSignal (shared_ptr< HadronizationManager > hm)
Definition at line 46 of file JetScapeSignalManager.cc.
View newest version in sPHENIX GitHub at line 46 of file JetScapeSignalManager.cc
void Jetscape::JetScapeSignalManager::ConnectGetHardPartonListSignal (shared_ptr< JetEnergyLossManager > jm)
Definition at line 35 of file JetScapeSignalManager.cc.
View newest version in sPHENIX GitHub at line 35 of file JetScapeSignalManager.cc
void Jetscape::JetScapeSignalManager::ConnectGetHydroCellSignal (shared_ptr< JetEnergyLoss > j)
Definition at line 103 of file JetScapeSignalManager.cc.
View newest version in sPHENIX GitHub at line 103 of file JetScapeSignalManager.cc
void Jetscape::JetScapeSignalManager::ConnectGetHydroCellSignal (shared_ptr< LiquefierBase > l)
Definition at line 117 of file JetScapeSignalManager.cc.
View newest version in sPHENIX GitHub at line 117 of file JetScapeSignalManager.cc
void Jetscape::JetScapeSignalManager::ConnectGetHydroCellSignal (shared_ptr< Hadronization > h)
Definition at line 128 of file JetScapeSignalManager.cc.
View newest version in sPHENIX GitHub at line 128 of file JetScapeSignalManager.cc
void Jetscape::JetScapeSignalManager::ConnectGetHydroHyperSurfaceSignal (shared_ptr< Hadronization > h)
Definition at line 172 of file JetScapeSignalManager.cc.
View newest version in sPHENIX GitHub at line 172 of file JetScapeSignalManager.cc
void Jetscape::JetScapeSignalManager::ConnectGetHydroTau0Signal (shared_ptr< JetEnergyLoss > j)
Definition at line 92 of file JetScapeSignalManager.cc.
View newest version in sPHENIX GitHub at line 92 of file JetScapeSignalManager.cc
void Jetscape::JetScapeSignalManager::ConnectJetSignal (shared_ptr< JetEnergyLoss > j)
Definition at line 67 of file JetScapeSignalManager.cc.
View newest version in sPHENIX GitHub at line 67 of file JetScapeSignalManager.cc
void Jetscape::JetScapeSignalManager::ConnectSentInPartonsSignal (shared_ptr< JetEnergyLoss > j, shared_ptr< JetEnergyLoss > j2)
Definition at line 139 of file JetScapeSignalManager.cc.
View newest version in sPHENIX GitHub at line 139 of file JetScapeSignalManager.cc
void Jetscape::JetScapeSignalManager::ConnectTransformPartonsSignal (shared_ptr< Hadronization > h, shared_ptr< Hadronization > h2)
Definition at line 150 of file JetScapeSignalManager.cc.
View newest version in sPHENIX GitHub at line 150 of file JetScapeSignalManager.cc
void Jetscape::JetScapeSignalManager::DisconnectSignal () inline
Definition at line 132 of file JetScapeSignalManager.h.
View newest version in sPHENIX GitHub at line 132 of file JetScapeSignalManager.h
weak_ptr<JetEnergyLoss> Jetscape::JetScapeSignalManager::GetEnergyLossPointer () inline
Definition at line 113 of file JetScapeSignalManager.h.
View newest version in sPHENIX GitHub at line 113 of file JetScapeSignalManager.h
weak_ptr<HadronizationManager> Jetscape::JetScapeSignalManager::GetHadronizationManagerPointer () inline
Definition at line 94 of file JetScapeSignalManager.h.
View newest version in sPHENIX GitHub at line 94 of file JetScapeSignalManager.h
weak_ptr<HadronPrinter> Jetscape::JetScapeSignalManager::GetHadronPrinterPointer () inline
Definition at line 106 of file JetScapeSignalManager.h.
View newest version in sPHENIX GitHub at line 106 of file JetScapeSignalManager.h
weak_ptr<HardProcess> Jetscape::JetScapeSignalManager::GetHardProcessPointer () inline
Definition at line 83 of file JetScapeSignalManager.h.
View newest version in sPHENIX GitHub at line 83 of file JetScapeSignalManager.h
weak_ptr<FluidDynamics> Jetscape::JetScapeSignalManager::GetHydroPointer () inline
Definition at line 63 of file JetScapeSignalManager.h.
View newest version in sPHENIX GitHub at line 63 of file JetScapeSignalManager.h
Referenced by HybridHadronization::DoHadronization().
weak_ptr<InitialState> Jetscape::JetScapeSignalManager::GetInitialStatePointer () inline
Definition at line 53 of file JetScapeSignalManager.h.
View newest version in sPHENIX GitHub at line 53 of file JetScapeSignalManager.h
weak_ptr<JetEnergyLossManager> Jetscape::JetScapeSignalManager::GetJetEnergyLossManagerPointer () inline
Definition at line 76 of file JetScapeSignalManager.h.
View newest version in sPHENIX GitHub at line 76 of file JetScapeSignalManager.h
int Jetscape::JetScapeSignalManager::GetNumberOfEdensitySignals () inline
Definition at line 137 of file JetScapeSignalManager.h.
View newest version in sPHENIX GitHub at line 137 of file JetScapeSignalManager.h
int Jetscape::JetScapeSignalManager::GetNumberOfGetHydroCellSignals () inline
Definition at line 138 of file JetScapeSignalManager.h.
View newest version in sPHENIX GitHub at line 138 of file JetScapeSignalManager.h
int Jetscape::JetScapeSignalManager::GetNumberOfJetSignals () inline
Definition at line 136 of file JetScapeSignalManager.h.
View newest version in sPHENIX GitHub at line 136 of file JetScapeSignalManager.h
weak_ptr<PartonPrinter> Jetscape::JetScapeSignalManager::GetPartonPrinterPointer () inline
Definition at line 101 of file JetScapeSignalManager.h.
View newest version in sPHENIX GitHub at line 101 of file JetScapeSignalManager.h
weak_ptr<PreequilibriumDynamics> Jetscape::JetScapeSignalManager::GetPreEquilibriumPointer () inline
Definition at line 58 of file JetScapeSignalManager.h.
View newest version in sPHENIX GitHub at line 58 of file JetScapeSignalManager.h
weak_ptr<SoftParticlization> Jetscape::JetScapeSignalManager::GetSoftParticlizationPointer () inline
Definition at line 68 of file JetScapeSignalManager.h.
View newest version in sPHENIX GitHub at line 68 of file JetScapeSignalManager.h
weak_ptr<JetScapeWriter> Jetscape::JetScapeSignalManager::GetWriterPointer () inline
Definition at line 88 of file JetScapeSignalManager.h.
View newest version in sPHENIX GitHub at line 88 of file JetScapeSignalManager.h
References writer.
JetScapeSignalManager * Jetscape::JetScapeSignalManager::Instance () static
Definition at line 26 of file JetScapeSignalManager.cc.
View newest version in sPHENIX GitHub at line 26 of file JetScapeSignalManager.cc
References JSINFO.
Referenced by HybridHadronization::DoHadronization(), Jetscape::HadronPrinter::Init(), and Jetscape::JetScape::SetPointers().
void Jetscape::JetScapeSignalManager::PrintEdensitySignalMap ()
Definition at line 235 of file JetScapeSignalManager.cc.
View newest version in sPHENIX GitHub at line 235 of file JetScapeSignalManager.cc
References VERBOSE, and ambiguity_solver_full_chain::x.
void Jetscape::JetScapeSignalManager::PrintGetHydroCellSignalMap ()
Definition at line 245 of file JetScapeSignalManager.cc.
View newest version in sPHENIX GitHub at line 245 of file JetScapeSignalManager.cc
References VERBOSE, and ambiguity_solver_full_chain::x.
void Jetscape::JetScapeSignalManager::PrintJetSignalMap ()
Definition at line 225 of file JetScapeSignalManager.cc.
View newest version in sPHENIX GitHub at line 225 of file JetScapeSignalManager.cc
References VERBOSE, and ambiguity_solver_full_chain::x.
void Jetscape::JetScapeSignalManager::PrintSentInPartonsSignalMap ()
Definition at line 255 of file JetScapeSignalManager.cc.
View newest version in sPHENIX GitHub at line 255 of file JetScapeSignalManager.cc
References VERBOSE, and ambiguity_solver_full_chain::x.
void Jetscape::JetScapeSignalManager::PrintTransformPartonsSignalMap ()
Definition at line 265 of file JetScapeSignalManager.cc.
View newest version in sPHENIX GitHub at line 265 of file JetScapeSignalManager.cc
References VERBOSE, and ambiguity_solver_full_chain::x.
void Jetscape::JetScapeSignalManager::SetEnergyLossPointer (shared_ptr< JetEnergyLoss > m_eloss) inline
Definition at line 109 of file JetScapeSignalManager.h.
View newest version in sPHENIX GitHub at line 109 of file JetScapeSignalManager.h
void Jetscape::JetScapeSignalManager::SetHadronizationManagerPointer (shared_ptr< HadronizationManager > m_hadro) inline
Definition at line 91 of file JetScapeSignalManager.h.
View newest version in sPHENIX GitHub at line 91 of file JetScapeSignalManager.h
Referenced by Jetscape::JetScape::SetPointers().
void Jetscape::JetScapeSignalManager::SetHadronPrinterPointer (shared_ptr< HadronPrinter > m_hprinter) inline
Definition at line 103 of file JetScapeSignalManager.h.
View newest version in sPHENIX GitHub at line 103 of file JetScapeSignalManager.h
Referenced by Jetscape::JetScape::SetPointers().
void Jetscape::JetScapeSignalManager::SetHardProcessPointer (shared_ptr< HardProcess > m_hardp) inline
Definition at line 80 of file JetScapeSignalManager.h.
View newest version in sPHENIX GitHub at line 80 of file JetScapeSignalManager.h
Referenced by Jetscape::JetScape::SetPointers().
void Jetscape::JetScapeSignalManager::SetHydroPointer (shared_ptr< FluidDynamics > m_hydro) inline
Definition at line 62 of file JetScapeSignalManager.h.
View newest version in sPHENIX GitHub at line 62 of file JetScapeSignalManager.h
Referenced by Jetscape::JetScape::SetPointers().
void Jetscape::JetScapeSignalManager::SetInitialStatePointer (shared_ptr< InitialState > m_initial) inline
Definition at line 50 of file JetScapeSignalManager.h.
View newest version in sPHENIX GitHub at line 50 of file JetScapeSignalManager.h
Referenced by Jetscape::JetScape::SetPointers().
void Jetscape::JetScapeSignalManager::SetJetEnergyLossManagerPointer (shared_ptr< JetEnergyLossManager > m_jloss) inline
Definition at line 73 of file JetScapeSignalManager.h.
View newest version in sPHENIX GitHub at line 73 of file JetScapeSignalManager.h
Referenced by Jetscape::JetScape::SetPointers().
void Jetscape::JetScapeSignalManager::SetPartonPrinterPointer (shared_ptr< PartonPrinter > m_pprinter) inline
Definition at line 98 of file JetScapeSignalManager.h.
View newest version in sPHENIX GitHub at line 98 of file JetScapeSignalManager.h
Referenced by Jetscape::JetScape::SetPointers().
void Jetscape::JetScapeSignalManager::SetPreEquilibriumPointer (shared_ptr< PreequilibriumDynamics > m_pre_eq) inline
Definition at line 55 of file JetScapeSignalManager.h.
View newest version in sPHENIX GitHub at line 55 of file JetScapeSignalManager.h
Referenced by Jetscape::JetScape::SetPointers().
void Jetscape::JetScapeSignalManager::SetSoftParticlizationPointer (shared_ptr< SoftParticlization > m_soft) inline
Definition at line 65 of file JetScapeSignalManager.h.
View newest version in sPHENIX GitHub at line 65 of file JetScapeSignalManager.h
Referenced by Jetscape::JetScape::SetPointers().
void Jetscape::JetScapeSignalManager::SetWriterPointer (shared_ptr< JetScapeWriter > m_writer) inline
Definition at line 85 of file JetScapeSignalManager.h.
View newest version in sPHENIX GitHub at line 85 of file JetScapeSignalManager.h
References writer.
Referenced by Jetscape::JetScape::SetPointers().
Member Data Documentation
weak_ptr<Afterburner> Jetscape::JetScapeSignalManager::afterburner private
Definition at line 158 of file JetScapeSignalManager.h.
View newest version in sPHENIX GitHub at line 158 of file JetScapeSignalManager.h
map<int, weak_ptr<JetEnergyLoss> > Jetscape::JetScapeSignalManager::edensity_signal_map private
Definition at line 171 of file JetScapeSignalManager.h.
View newest version in sPHENIX GitHub at line 171 of file JetScapeSignalManager.h
weak_ptr<JetEnergyLoss> Jetscape::JetScapeSignalManager::eloss private
Definition at line 161 of file JetScapeSignalManager.h.
View newest version in sPHENIX GitHub at line 161 of file JetScapeSignalManager.h
map<int, weak_ptr<JetEnergyLoss> > Jetscape::JetScapeSignalManager::GetHydroCellSignal_map private
Definition at line 172 of file JetScapeSignalManager.h.
View newest version in sPHENIX GitHub at line 172 of file JetScapeSignalManager.h
weak_ptr<HadronizationManager> Jetscape::JetScapeSignalManager::hadro private
Definition at line 157 of file JetScapeSignalManager.h.
View newest version in sPHENIX GitHub at line 157 of file JetScapeSignalManager.h
weak_ptr<HardProcess> Jetscape::JetScapeSignalManager::hardp private
Definition at line 155 of file JetScapeSignalManager.h.
View newest version in sPHENIX GitHub at line 155 of file JetScapeSignalManager.h
weak_ptr<HadronPrinter> Jetscape::JetScapeSignalManager::hprinter private
Definition at line 160 of file JetScapeSignalManager.h.
View newest version in sPHENIX GitHub at line 160 of file JetScapeSignalManager.h
weak_ptr<FluidDynamics> Jetscape::JetScapeSignalManager::hydro private
Definition at line 153 of file JetScapeSignalManager.h.
View newest version in sPHENIX GitHub at line 153 of file JetScapeSignalManager.h
weak_ptr<InitialState> Jetscape::JetScapeSignalManager::initial_state private
Definition at line 151 of file JetScapeSignalManager.h.
View newest version in sPHENIX GitHub at line 151 of file JetScapeSignalManager.h
map<int, weak_ptr<JetEnergyLoss> > Jetscape::JetScapeSignalManager::jet_signal_map private
Definition at line 170 of file JetScapeSignalManager.h.
View newest version in sPHENIX GitHub at line 170 of file JetScapeSignalManager.h
weak_ptr<JetEnergyLossManager> Jetscape::JetScapeSignalManager::jloss private
Definition at line 154 of file JetScapeSignalManager.h.
View newest version in sPHENIX GitHub at line 154 of file JetScapeSignalManager.h
JetScapeSignalManager * Jetscape::JetScapeSignalManager::m_pInstance = NULL static private
Definition at line 148 of file JetScapeSignalManager.h.
View newest version in sPHENIX GitHub at line 148 of file JetScapeSignalManager.h
int Jetscape::JetScapeSignalManager::num_edensity_signals = 0 private
Definition at line 165 of file JetScapeSignalManager.h.
View newest version in sPHENIX GitHub at line 165 of file JetScapeSignalManager.h
int Jetscape::JetScapeSignalManager::num_GetHydroCellSignals = 0 private
Definition at line 166 of file JetScapeSignalManager.h.
View newest version in sPHENIX GitHub at line 166 of file JetScapeSignalManager.h
int Jetscape::JetScapeSignalManager::num_jet_signals = 0 private
Definition at line 164 of file JetScapeSignalManager.h.
View newest version in sPHENIX GitHub at line 164 of file JetScapeSignalManager.h
int Jetscape::JetScapeSignalManager::num_SentInPartons = 0 private
Definition at line 167 of file JetScapeSignalManager.h.
View newest version in sPHENIX GitHub at line 167 of file JetScapeSignalManager.h
int Jetscape::JetScapeSignalManager::num_TransformPartons = 0 private
Definition at line 168 of file JetScapeSignalManager.h.
View newest version in sPHENIX GitHub at line 168 of file JetScapeSignalManager.h
weak_ptr<PartonPrinter> Jetscape::JetScapeSignalManager::pprinter private
Definition at line 159 of file JetScapeSignalManager.h.
View newest version in sPHENIX GitHub at line 159 of file JetScapeSignalManager.h
weak_ptr<PreequilibriumDynamics> Jetscape::JetScapeSignalManager::pre_equilibrium private
Definition at line 152 of file JetScapeSignalManager.h.
View newest version in sPHENIX GitHub at line 152 of file JetScapeSignalManager.h
map<int, weak_ptr<JetEnergyLoss> > Jetscape::JetScapeSignalManager::SentInPartons_map private
Definition at line 174 of file JetScapeSignalManager.h.
View newest version in sPHENIX GitHub at line 174 of file JetScapeSignalManager.h
weak_ptr<SoftParticlization> Jetscape::JetScapeSignalManager::softparticlization private
Definition at line 162 of file JetScapeSignalManager.h.
View newest version in sPHENIX GitHub at line 162 of file JetScapeSignalManager.h
map<int, weak_ptr<Hadronization> > Jetscape::JetScapeSignalManager::TransformPartons_map private
Definition at line 175 of file JetScapeSignalManager.h.
View newest version in sPHENIX GitHub at line 175 of file JetScapeSignalManager.h
weak_ptr<JetScapeWriter> Jetscape::JetScapeSignalManager::writer private
Definition at line 156 of file JetScapeSignalManager.h.
View newest version in sPHENIX GitHub at line 156 of file JetScapeSignalManager.h
The documentation for this class was generated from the following files:
JETSCAPE/blob/main/src/framework/JetScapeSignalManager.h
JETSCAPE/blob/main/src/framework/JetScapeSignalManager.cc