Analysis Software: Acts::CKFSourceLinkSelector Struct Reference
Acts::CKFSourceLinkSelector Struct Reference
Source link selection struct selecting those source links compatible with the given track parameter against provided criteria on one surface.
#include <acts/blob/sPHENIX/Core/include/Acts/TrackFinding/CKFSourceLinkSelector.hpp>
Public Types
using Config = Acts::GeometryHierarchyMap< SourceLinkSelectorCuts >
Public Member Functions
CKFSourceLinkSelector ()=default
Default constructor.
CKFSourceLinkSelector (Config cfg)
Constructor with config and (non-owning) logger.
template<typename calibrator_t , typename source_link_t >
Result< void > operator() (const calibrator_t &calibrator, const BoundTrackParameters &predictedParams, const std::vector< source_link_t > &sourcelinks, std::vector< std::pair< size_t, double >> &sourcelinkChi2, std::vector< size_t > &sourcelinkCandidateIndices, bool &isOutlier, LoggerWrapper logger) const
Operater that select the source links compatible with the given track parameter on a surface.
Public Attributes
Config m_config
The config.
Detailed Description
Source link selection struct selecting those source links compatible with the given track parameter against provided criteria on one surface.
The selection criteria could be allowed maximum chi2 and allowed maximum number of source links on one surface
If there is no compatible source link, the source link with the mininum chi2 will be selected and the status will be tagged as an outlier
Definition at line 45 of file CKFSourceLinkSelector.hpp.
View newest version in sPHENIX GitHub at line 45 of file CKFSourceLinkSelector.hpp
Member Typedef Documentation
using Acts::CKFSourceLinkSelector::Config = Acts::GeometryHierarchyMap<SourceLinkSelectorCuts>
Geometry-dependent cut configuration.
Different components on the geometry can require different cut settings. The configuration must either contain explicit settings for all geometry components that are used or contain a global default.
Definition at line 52 of file CKFSourceLinkSelector.hpp.
View newest version in sPHENIX GitHub at line 52 of file CKFSourceLinkSelector.hpp
Constructor & Destructor Documentation
Acts::CKFSourceLinkSelector::CKFSourceLinkSelector () default
Default constructor.
Acts::CKFSourceLinkSelector::CKFSourceLinkSelector (Config cfg) inline
Constructor with config and (non-owning) logger.
Parameters
config a config instance
logger a logger instance
Definition at line 60 of file CKFSourceLinkSelector.hpp.
View newest version in sPHENIX GitHub at line 60 of file CKFSourceLinkSelector.hpp
Member Function Documentation
template<typename calibrator_t , typename source_link_t > Result<void> Acts::CKFSourceLinkSelector::operator() (const calibrator_t & calibrator, const BoundTrackParameters & predictedParams, const std::vector< source_link_t > & sourcelinks, std::vector< std::pair< size_t, double >> & sourcelinkChi2, std::vector< size_t > & sourcelinkCandidateIndices, bool & isOutlier, LoggerWrapper logger) const inline
Operater that select the source links compatible with the given track parameter on a surface.
Template Parameters
calibrator_t The type of calibrator
source_link_t The type of source link
Parameters
calibrator The measurement calibrator
predictedParams The predicted track parameter on a surface
sourcelinks The pool of source links
sourcelinkChi2 The container for index and chi2 of intermediate source link candidates
sourcelinkCandidateIndices The container for index of final source link candidates
isOutlier The indicator for outlier or not
Definition at line 78 of file CKFSourceLinkSelector.hpp.
View newest version in sPHENIX GitHub at line 78 of file CKFSourceLinkSelector.hpp
References ACTS_DEBUG, ACTS_VERBOSE, assert, Acts::SingleBoundTrackParameters< charge_t >::covariance(), cuts, Acts::GeometryHierarchyMap< value_t >::end(), Acts::GeometryHierarchyMap< value_t >::find(), Acts::GeometryObject::geometryId(), H, id, index, m_config, max, min, Acts::SingleBoundTrackParameters< charge_t >::parameters(), and Acts::SingleBoundTrackParameters< charge_t >::referenceSurface().
Member Data Documentation
Config Acts::CKFSourceLinkSelector::m_config
The config.
Definition at line 192 of file CKFSourceLinkSelector.hpp.
View newest version in sPHENIX GitHub at line 192 of file CKFSourceLinkSelector.hpp
Referenced by operator()().
The documentation for this struct was generated from the following file:
acts/blob/sPHENIX/Core/include/Acts/TrackFinding/CKFSourceLinkSelector.hpp