Analysis Software: acts/blob/sPHENIX/Examples/Python/src/Geant4Component.cpp File Reference
Geant4Component.cpp File Reference
#include "Acts/Definitions/Algebra.hpp"
#include "Acts/Detector/Detector.hpp"
#include "Acts/Geometry/TrackingGeometry.hpp"
#include "Acts/MagneticField/MagneticFieldProvider.hpp"
#include "Acts/Plugins/Geant4/Geant4DetectorElement.hpp"
#include "Acts/Plugins/Geant4/Geant4DetectorSurfaceFactory.hpp"
#include "Acts/Plugins/Geant4/Geant4PhysicalVolumeSelectors.hpp"
#include "Acts/Plugins/Python/Utilities.hpp"
#include "Acts/Utilities/Logger.hpp"
#include "ActsExamples/Framework/AlgorithmContext.hpp"
#include "ActsExamples/Framework/IContextDecorator.hpp"
#include "ActsExamples/Geant4/DetectorConstructionFactory.hpp"
#include "ActsExamples/Geant4/GdmlDetectorConstruction.hpp"
#include "ActsExamples/Geant4/Geant4Manager.hpp"
#include "ActsExamples/Geant4/Geant4Simulation.hpp"
#include "ActsExamples/Geant4Detector/Geant4Detector.hpp"
#include "ActsExamples/MuonSpectrometerMockupDetector/MockupSectorBuilder.hpp"
#include "ActsExamples/TelescopeDetector/TelescopeDetector.hpp"
#include "ActsExamples/TelescopeDetector/TelescopeG4DetectorConstruction.hpp"
#include <array>
#include <memory>
#include <optional>
#include <string>
#include <tuple>
#include <unordered_map>
#include <utility>
#include <vector>
#include <G4RunManager.hh>
#include <G4Transform3D.hh>
#include <G4UserEventAction.hh>
#include <G4UserRunAction.hh>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
Namespaces
namespace Acts
Acts includes to create all necessary definitions.
namespace ActsExamples
namespace Acts::Python
Functions
void Acts::Python::addGeant4HepMC3 (Context &ctx)
PYBIND11_MODULE (ActsPythonBindingsGeant4, mod)
Function Documentation
PYBIND11_MODULE (ActsPythonBindingsGeant4 , mod)
Helper function to test if the autmotaic geometry conversion works
Parameters
gdmlFileName is the name of the GDML file
sensitiveMatches is a list of strings to match sensitive volumes
passiveMatches is a list of strings to match passive volumes
Definition at line 67 of file Geant4Component.cpp.
View newest version in sPHENIX GitHub at line 67 of file Geant4Component.cpp
References ACTS_PYTHON_MEMBER, ACTS_PYTHON_STRUCT_BEGIN, ACTS_PYTHON_STRUCT_END, Acts::Python::addGeant4HepMC3(), Acts::PhysicalConstants::c, cfg, filter::Config, filter::config, ActsExamples::GdmlDetectorConstruction::Construct(), Acts::Geant4DetectorSurfaceFactory::construct(), event_recording::detectorConstructionFactory, Acts::UnitConstants::g, Acts::getDefaultLogger(), Acts::Logging::INFO, myAnalysis::init(), physmon_simulation::inputParticles, physmon_simulation::killAfterTime, physmon_simulation::killSecondaries, physmon_simulation::killVolume, logger(), telescope_simulation::logLevel, ActsTests::PropagationDatasets::magneticField, Acts::Python::Context::modules, testing::internal::move(), Acts::UnitConstants::ms, perf_headwind::name, nominal, Acts::UnitConstants::ns, ckf::options, physmon_simulation::outputParticlesFinal, physmon_simulation::outputParticlesInitial, physmon_simulation::outputSimHits, Acts::passive, Acts::Geant4DetectorSurfaceFactory::Options::passiveSurfaceSelector, physmon_simulation::randomNumbers, Acts::Geant4DetectorSurfaceFactory::Options::sensitiveSurfaceSelector, and digitization_config::trackingGeometry.