Analysis Software: InttSurveyMapv1 Class Reference
InttSurveyMapv1 Class Reference
#include <coresoftware/blob/master/offline/packages/intt/InttSurveyMapv1.h>
Public Types
typedef InttMap::Offline_s key_t
typedef std::map
< InttMap::Offline_s,
Eigen::Affine3d,
InttMap::OfflineComparator > map_t
typedef Eigen::Affine3d val_t
Public Types inherited from InttSurveyMap
typedef std::map
< InttMap::Offline_s,
Eigen::Affine3d,
InttMap::OfflineComparator > map_t
typedef InttMap::Offline_s key_t
typedef Eigen::Affine3d val_t
Public Member Functions
InttSurveyMapv1 ()=default
~InttSurveyMapv1 () override
void identify (std::ostream &=std::cout) const override
std::size_t size () const override
Public Member Functions inherited from InttSurveyMap
InttSurveyMap ()=default
~InttSurveyMap () override=default
int LoadFromFile (std::string const &="InttSurveyMap.root")
int LoadFromCDB (std::string const &="InttSurveyMap")
virtual val_t const * GetAbsoluteTransform (key_t) const
virtual val_t const * GetRelativeTransform (key_t) const
Public Member Functions inherited from PHObject
PHObject ()
ctor
~PHObject () override
dtor
virtual PHObject * CloneMe () const
Virtual copy constructor.
virtual PHObject * clone () const final
PHObject * Clone (const char *newname="") const final
void Copy (TObject &object) const final
virtual void Reset ()
Clear Event.
virtual int isValid () const
isValid returns non zero if object contains vailid data
virtual int Integrate () const
virtual int Integrate (PHObject *)
virtual void CopyFrom (const PHObject *obj)
Protected Member Functions
int v_LoadFromCDBTTree (CDBTTree &) override
int v_LookupAbsoluteTransform (key_t const &, map_t::const_iterator &) const override
int v_LookupRelativeTransform (key_t const &, map_t::const_iterator &) const override
Private Attributes
map_t * m_absolute_transforms = nullptr
map_t * m_relative_transforms = nullptr
Detailed Description
Definition at line 11 of file InttSurveyMapv1.h.
View newest version in sPHENIX GitHub at line 11 of file InttSurveyMapv1.h
Member Typedef Documentation
typedef InttMap::Offline_s InttSurveyMap::key_t
Definition at line 21 of file InttSurveyMap.h.
View newest version in sPHENIX GitHub at line 21 of file InttSurveyMap.h
typedef std::map<InttMap::Offline_s, Eigen::Affine3d, InttMap::OfflineComparator> InttSurveyMap::map_t
Definition at line 20 of file InttSurveyMap.h.
View newest version in sPHENIX GitHub at line 20 of file InttSurveyMap.h
typedef Eigen::Affine3d InttSurveyMap::val_t
Definition at line 22 of file InttSurveyMap.h.
View newest version in sPHENIX GitHub at line 22 of file InttSurveyMap.h
Constructor & Destructor Documentation
InttSurveyMapv1::InttSurveyMapv1 () default
InttSurveyMapv1::~InttSurveyMapv1 () override
Definition at line 7 of file InttSurveyMapv1.cc.
View newest version in sPHENIX GitHub at line 7 of file InttSurveyMapv1.cc
References m_absolute_transforms, and m_relative_transforms.
Member Function Documentation
void InttSurveyMapv1::identify (std::ostream & os = std::cout) const override virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from InttSurveyMap.
Definition at line 13 of file InttSurveyMapv1.cc.
View newest version in sPHENIX GitHub at line 13 of file InttSurveyMapv1.cc
References size().
std::size_t InttSurveyMapv1::size (void) const override virtual
Reimplemented from InttSurveyMap.
Definition at line 21 of file InttSurveyMapv1.cc.
View newest version in sPHENIX GitHub at line 21 of file InttSurveyMapv1.cc
Referenced by identify().
int InttSurveyMapv1::v_LoadFromCDBTTree (CDBTTree & cdbttree) override protected virtual
Reimplemented from InttSurveyMap.
Definition at line 26 of file InttSurveyMapv1.cc.
View newest version in sPHENIX GitHub at line 26 of file InttSurveyMapv1.cc
References material_mapping_optimisation::format, CDBTTree::GetDoubleValue(), CDBTTree::GetIntValue(), CDBTTree::GetSingleIntValue(), i, InttMap::Offline_s::ladder_phi, InttMap::Offline_s::ladder_z, InttMap::Offline_s::layer, m_absolute_transforms, m_relative_transforms, n, N, str, InttMap::Offline_s::strip_phi, and InttMap::Offline_s::strip_z.
int InttSurveyMapv1::v_LookupAbsoluteTransform (key_t const & k, map_t::const_iterator & itr) const override protected virtual
Reimplemented from InttSurveyMap.
Definition at line 71 of file InttSurveyMapv1.cc.
View newest version in sPHENIX GitHub at line 71 of file InttSurveyMapv1.cc
References m_absolute_transforms.
int InttSurveyMapv1::v_LookupRelativeTransform (key_t const & k, map_t::const_iterator & itr) const override protected virtual
Reimplemented from InttSurveyMap.
Definition at line 83 of file InttSurveyMapv1.cc.
View newest version in sPHENIX GitHub at line 83 of file InttSurveyMapv1.cc
References m_relative_transforms.
Member Data Documentation
map_t* InttSurveyMapv1::m_absolute_transforms = nullptr private
Definition at line 31 of file InttSurveyMapv1.h.
View newest version in sPHENIX GitHub at line 31 of file InttSurveyMapv1.h
Referenced by v_LoadFromCDBTTree(), v_LookupAbsoluteTransform(), and ~InttSurveyMapv1().
map_t* InttSurveyMapv1::m_relative_transforms = nullptr private
Definition at line 32 of file InttSurveyMapv1.h.
View newest version in sPHENIX GitHub at line 32 of file InttSurveyMapv1.h
Referenced by v_LoadFromCDBTTree(), v_LookupRelativeTransform(), and ~InttSurveyMapv1().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/intt/InttSurveyMapv1.h
coresoftware/blob/master/offline/packages/intt/InttSurveyMapv1.cc