Analysis Software: TpcRawDataDecoder Class Reference
TpcRawDataDecoder Class Reference
#include <coresoftware/blob/master/offline/packages/tpc/TpcRawDataDecoder.h>
Classes
struct ped_tpc_map
Public Member Functions
TpcRawDataDecoder (const std::string &name="TpcRawDataDecoder")
~TpcRawDataDecoder () override
int Init (PHCompositeNode *topNode) override
int InitRun (PHCompositeNode *topNode) override
int process_event (PHCompositeNode *topNode) override
int End (PHCompositeNode *topNode) override
Clean up internals after each event.
Public Member Functions inherited from SubsysReco
~SubsysReco () override
virtual int EndRun (const int)
Called at the end of each run.
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
void Print (const std::string &="ALL") const override
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Protected Attributes
Fun4AllHistoManager * hm = nullptr
Reset.
std::string _filename
int _ievent = 0
TNtuple * h_Alive = nullptr
CDBTTree * m_cdbttree = nullptr
CDBInterface * m_cdb = nullptr
int starting_BCO
int rollover_value
int current_BCOBIN
Static Protected Attributes
static const int layercount = 16
static const int layeroffset = 7 + 16
Private Attributes
int m_Debug = 0
TH2 * _h_hit_XY = nullptr
TH2 * _h_hit_XY_ADCcut = nullptr
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = std::numeric_limits<int>::max() - 10
}
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Detailed Description
Definition at line 27 of file TpcRawDataDecoder.h.
View newest version in sPHENIX GitHub at line 27 of file TpcRawDataDecoder.h
Constructor & Destructor Documentation
TpcRawDataDecoder::TpcRawDataDecoder (const std::string & name = "TpcRawDataDecoder")
Definition at line 45 of file TpcRawDataDecoder.cc.
View newest version in sPHENIX GitHub at line 45 of file TpcRawDataDecoder.cc
References current_BCOBIN, rollover_value, and starting_BCO.
TpcRawDataDecoder::~TpcRawDataDecoder () override
Definition at line 102 of file TpcRawDataDecoder.cc.
View newest version in sPHENIX GitHub at line 102 of file TpcRawDataDecoder.cc
References hm.
Member Function Documentation
int TpcRawDataDecoder::End (PHCompositeNode * topNode) override virtual
Clean up internals after each event.
Called at the end of each run. Called at the end of all processing.
Reimplemented from SubsysReco.
Definition at line 489 of file TpcRawDataDecoder.cc.
View newest version in sPHENIX GitHub at line 489 of file TpcRawDataDecoder.cc
References _filename, Fun4AllHistoManager::dumpHistos(), Fun4AllReturnCodes::EVENT_OK, hm, and m_Debug.
int TpcRawDataDecoder::Init (PHCompositeNode *) override virtual
Called during initialization. Typically this is where you can book histograms, and e.g. register them to Fun4AllServer (so they can be output to file using Fun4AllServer::dumpHistos() method).
Reimplemented from SubsysReco.
Definition at line 109 of file TpcRawDataDecoder.cc.
View newest version in sPHENIX GitHub at line 109 of file TpcRawDataDecoder.cc
References _h_hit_XY, _h_hit_XY_ADCcut, Fun4AllReturnCodes::EVENT_OK, CDBInterface::getUrl(), hm, CDBInterface::instance(), CDBTTree::LoadCalibrations(), m_cdb, m_cdbttree, m_Debug, and Fun4AllHistoManager::registerHisto().
int TpcRawDataDecoder::InitRun (PHCompositeNode * topNode) override virtual
Called for first event when run number is known. Typically this is where you may want to fetch data from database, because you know the run number. A place to book histograms which have to know the run number.
Reimplemented from SubsysReco.
Definition at line 148 of file TpcRawDataDecoder.cc.
View newest version in sPHENIX GitHub at line 148 of file TpcRawDataDecoder.cc
References current_BCOBIN, Fun4AllReturnCodes::EVENT_OK, PHNodeIterator::findFirst(), PHDataNode< T >::print(), rollover_value, and starting_BCO.
int TpcRawDataDecoder::process_event (PHCompositeNode * topNode) override virtual
Called for each event. This is where you do the real work.
special events
Reimplemented from SubsysReco.
Definition at line 193 of file TpcRawDataDecoder.cc.
View newest version in sPHENIX GitHub at line 193 of file TpcRawDataDecoder.cc
References _filename, _h_hit_XY, _h_hit_XY_ADCcut, _ievent, Fun4AllReturnCodes::ABORTRUN, assert, channel(), current_BCOBIN, Fun4AllReturnCodes::DISCARDEVENT, Fun4AllReturnCodes::EVENT_OK, PHG4TpcCylinderGeom::find_phibin(), TpcDefs::genHitKey(), TpcDefs::genHitSetKey(), CDBTTree::GetDoubleValue(), Event::getEvtType(), CDBTTree::GetIntValue(), PHG4TpcCylinderGeomContainer::GetLayerCellGeom(), Event::getPacket(), Packet::iValue(), layer, Packet::lValue(), m_cdbttree, m_Debug, merge_hashes::p, pedestal(), ActsTests::PropagationDatasets::phi, PHWHERE, Acts::IntegrationTest::R, rollover_value, physmon_simulation::s, starting_BCO, t, and Fun4AllBase::Verbosity().
Member Data Documentation
std::string TpcRawDataDecoder::_filename protected
Definition at line 65 of file TpcRawDataDecoder.h.
View newest version in sPHENIX GitHub at line 65 of file TpcRawDataDecoder.h
Referenced by End(), and process_event().
TH2* TpcRawDataDecoder::_h_hit_XY = nullptr private
Definition at line 101 of file TpcRawDataDecoder.h.
View newest version in sPHENIX GitHub at line 101 of file TpcRawDataDecoder.h
Referenced by Init(), and process_event().
TH2* TpcRawDataDecoder::_h_hit_XY_ADCcut = nullptr private
Definition at line 102 of file TpcRawDataDecoder.h.
View newest version in sPHENIX GitHub at line 102 of file TpcRawDataDecoder.h
Referenced by Init(), and process_event().
int TpcRawDataDecoder::_ievent = 0 protected
Definition at line 69 of file TpcRawDataDecoder.h.
View newest version in sPHENIX GitHub at line 69 of file TpcRawDataDecoder.h
Referenced by process_event().
int TpcRawDataDecoder::current_BCOBIN protected
Definition at line 95 of file TpcRawDataDecoder.h.
View newest version in sPHENIX GitHub at line 95 of file TpcRawDataDecoder.h
Referenced by InitRun(), process_event(), and TpcRawDataDecoder().
TNtuple* TpcRawDataDecoder::h_Alive = nullptr protected
Definition at line 77 of file TpcRawDataDecoder.h.
View newest version in sPHENIX GitHub at line 77 of file TpcRawDataDecoder.h
Fun4AllHistoManager* TpcRawDataDecoder::hm = nullptr protected
Reset.
Definition at line 64 of file TpcRawDataDecoder.h.
View newest version in sPHENIX GitHub at line 64 of file TpcRawDataDecoder.h
Referenced by End(), Init(), and ~TpcRawDataDecoder().
const int TpcRawDataDecoder::layercount = 16 static protected
Definition at line 67 of file TpcRawDataDecoder.h.
View newest version in sPHENIX GitHub at line 67 of file TpcRawDataDecoder.h
const int TpcRawDataDecoder::layeroffset = 7 + 16 static protected
Definition at line 68 of file TpcRawDataDecoder.h.
View newest version in sPHENIX GitHub at line 68 of file TpcRawDataDecoder.h
CDBInterface* TpcRawDataDecoder::m_cdb = nullptr protected
Definition at line 79 of file TpcRawDataDecoder.h.
View newest version in sPHENIX GitHub at line 79 of file TpcRawDataDecoder.h
Referenced by Init().
CDBTTree* TpcRawDataDecoder::m_cdbttree = nullptr protected
Definition at line 78 of file TpcRawDataDecoder.h.
View newest version in sPHENIX GitHub at line 78 of file TpcRawDataDecoder.h
Referenced by Init(), and process_event().
int TpcRawDataDecoder::m_Debug = 0 private
Definition at line 98 of file TpcRawDataDecoder.h.
View newest version in sPHENIX GitHub at line 98 of file TpcRawDataDecoder.h
Referenced by End(), Init(), and process_event().
int TpcRawDataDecoder::rollover_value protected
Definition at line 94 of file TpcRawDataDecoder.h.
View newest version in sPHENIX GitHub at line 94 of file TpcRawDataDecoder.h
Referenced by InitRun(), process_event(), and TpcRawDataDecoder().
int TpcRawDataDecoder::starting_BCO protected
Definition at line 93 of file TpcRawDataDecoder.h.
View newest version in sPHENIX GitHub at line 93 of file TpcRawDataDecoder.h
Referenced by InitRun(), process_event(), and TpcRawDataDecoder().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/tpc/TpcRawDataDecoder.h
coresoftware/blob/master/offline/packages/tpc/TpcRawDataDecoder.cc