Analysis Software: generate_particle_data_table Namespace Reference
generate_particle_data_table Namespace Reference
Functions
def main
def generate_code
def clang_format
Variables
string CODE_HEADER
output_file sys.stdout
Function Documentation
def generate_particle_data_table.clang_format (content)
Format the given content using clang-format and return it.
Definition at line 84 of file generate_particle_data_table.py.
View newest version in sPHENIX GitHub at line 84 of file generate_particle_data_table.py
References material_mapping_optimisation.format, and print().
Referenced by main().
def generate_particle_data_table.generate_code (table)
Generate
Definition at line 52 of file generate_particle_data_table.py.
View newest version in sPHENIX GitHub at line 52 of file generate_particle_data_table.py
References Acts.enumerate(), and join().
Referenced by main().
def generate_particle_data_table.main (output_file)
Generate the code and write it to the given output file.
Definition at line 13 of file generate_particle_data_table.py.
View newest version in sPHENIX GitHub at line 13 of file generate_particle_data_table.py
References clang_format(), and generate_code().
Variable Documentation
string generate_particle_data_table.CODE_HEADER
Initial value:
 """\
 // This file is part of the Acts project.
 //
 // Copyright (C) 2020 CERN for the benefit of the Acts project
 //
 // This Source Code Form is subject to the terms of the Mozilla Public
 // License, v. 2.0. If a copy of the MPL was not distributed with this
 // file, You can obtain one at http://mozilla.org/MPL/2.0/.
 // The entries within this file have been automatically created using the
 // particle data files from the 2019 edition of the Review of Particle Physics
 // by the Berkeley Particle Data Group.
 #pragma once
 #include <cstdint>
 // Rows within the particle data table are sorted by their signed PDG particle
 // number and are then stored column-wise. Since the PDG particle number column
 // is sorted it can be used to quickly search for the index of a particle
 // within all column arrays.
 """
Definition at line 27 of file generate_particle_data_table.py.
View newest version in sPHENIX GitHub at line 27 of file generate_particle_data_table.py
tuple generate_particle_data_table.output_file sys.stdout
Definition at line 109 of file generate_particle_data_table.py.
View newest version in sPHENIX GitHub at line 109 of file generate_particle_data_table.py
Referenced by Jetscape::JetScapeWriterFinalStateStream< T >.Close(), Fun4All_PRDF(), Fun4All_TestBeam(), Jetscape::JetScapeWriterStream< T >.Init(), Jetscape::JetScapeWriterFinalStateStream< T >.Init(), make_cemcCDBTree(), make_csv(), testing::internal::XmlUnitTestResultPrinter.OnTestIterationEnd(), Jetscape::JetScapeWriterStream< T >.Write(), Jetscape::JetScapeWriterFinalStateStream< T >.WriteEvent(), Jetscape::JetScapeWriterStream< T >.WriteInitFileXMLMain(), and Jetscape::JetScapeWriterStream< T >.WriteInitFileXMLUser().