Analysis Software: RawTowerv2 Class Reference
RawTowerv2 Class Reference
RawTowerv1 but allow flexible tags.
#include <coresoftware/blob/master/offline/packages/CaloBase/RawTowerv2.h>
Public Member Functions
RawTowerv2 ()
RawTowerv2 (const RawTower &tower)
RawTowerv2 (RawTowerDefs::keytype id)
RawTowerv2 (const unsigned int ieta, const unsigned int iphi)
RawTowerv2 (const RawTowerDefs::CalorimeterId caloid, const unsigned int ieta, const unsigned int iphi)
~RawTowerv2 () override
void Reset () override
Clear Event.
int isValid () const override
isValid returns non zero if object contains vailid data
void identify (std::ostream &os=std::cout) const override
double get_scint_gammas () const override
energy assigned to the tower. Depending on stage of process and DST node name, it could be energy deposition, light yield or calibrated energies
void set_scint_gammas (const double e) override
scint_gammas assigned to the tower. Depending on stage of process and DST node name, it could be scint_gammas deposition, light yield or calibrated energies
double get_cerenkov_gammas () const override
energy assigned to the tower. Depending on stage of process and DST node name, it could be energy deposition, light yield or calibrated energies
void set_cerenkov_gammas (const double e) override
cerenkov_gammas assigned to the tower. Depending on stage of process and DST node name, it could be cerenkov_gammas deposition, light yield or calibrated energies
bool has_property (const PROPERTY prop_id) const override
double get_property (const PROPERTY prop_id) const override
void set_property (const PROPERTY prop_id, const double value) override
Public Member Functions inherited from RawTowerv1
RawTowerv1 ()
RawTowerv1 (const RawTower &tower)
RawTowerv1 (RawTowerDefs::keytype id)
RawTowerv1 (const unsigned int ieta, const unsigned int iphi)
RawTowerv1 (const RawTowerDefs::CalorimeterId caloid, const unsigned int ieta, const unsigned int iphi)
~RawTowerv1 () override
void set_id (RawTowerDefs::keytype id) override
RawTowerDefs::keytype get_id () const override
int get_bineta () const override
int get_binphi () const override
int get_binl () const override
return layer ID assigned to tower
double get_energy () const override
energy assigned to the tower. Depending on stage of process and DST node name, it could be energy deposition, light yield or calibrated energies
void set_energy (const double e) override
energy assigned to the tower. Depending on stage of process and DST node name, it could be energy deposition, light yield or calibrated energies
float get_time () const override
Time stamp assigned to the tower. Depending on the tower maker, it could be rise time or peak time.
void set_time (const float t) override
Time stamp assigned to the tower. Depending on the tower maker, it could be rise time or peak time.
bool empty_g4cells () const override
size_t size_g4cells () const override
RawTower::CellConstRange get_g4cells () const override
RawTower::CellIterator find_g4cell (CellKeyType id) override
RawTower::CellConstIterator find_g4cell (CellKeyType id) const override
void add_ecell (const CellKeyType g4cellid, const float ecell) override
void clear_g4cells () override
bool empty_g4showers () const override
size_t size_g4showers () const override
RawTower::ShowerConstRange get_g4showers () const override
RawTower::ShowerIterator find_g4shower (int id) override
RawTower::ShowerConstIterator find_g4shower (int id) const override
void add_eshower (const int g4showerid, const float eshower) override
void clear_g4showers () override
Public Member Functions inherited from RawTower
~RawTower () override
virtual void set_key (RawTowerDefs::keytype id)
virtual RawTowerDefs::keytype get_key () const
virtual int get_bintheta () const
virtual int get_column () const
virtual int get_row () const
Public Member Functions inherited from PHObject
PHObject ()
ctor
~PHObject () override
dtor
virtual PHObject * CloneMe () const
Virtual copy constructor.
virtual PHObject * clone () const final
PHObject * Clone (const char *newname="") const final
void Copy (TObject &object) const final
virtual int Integrate () const
virtual int Integrate (PHObject *)
virtual void CopyFrom (const PHObject *obj)
Protected Types
typedef uint8_t prop_id_t
typedef std::map< prop_id_t,
double > prop_map_t
Protected Attributes
prop_map_t prop_map
container for additional property
Protected Attributes inherited from RawTowerv1
RawTowerDefs::keytype towerid = ~0
double energy = 0.
float time = NAN
CellMap ecells
ShowerMap eshowers
Additional Inherited Members
Public Types inherited from RawTower
enum PROPERTY { prop_scint_gammas = 1, prop_cerenkov_gammas = 2, prop_MAX_NUMBER = UCHAR_MAX }
typedef unsigned long long CellKeyType
key type for cell map which should be consistent with CellKeyType
typedef std::map< CellKeyType,
float > CellMap
typedef CellMap::iterator CellIterator
typedef CellMap::const_iterator CellConstIterator
typedef std::pair
< CellIterator, CellIterator > CellRange
typedef std::pair
< CellConstIterator,
CellConstIterator > CellConstRange
typedef std::map< int, float > ShowerMap
typedef ShowerMap::iterator ShowerIterator
typedef ShowerMap::const_iterator ShowerConstIterator
typedef std::pair
< ShowerIterator,
ShowerIterator > ShowerRange
typedef std::pair
< ShowerConstIterator,
ShowerConstIterator > ShowerConstRange
Static Public Member Functions inherited from RawTower
static const std::string get_property_info (PROPERTY prop_id)
Protected Member Functions inherited from RawTower
RawTower ()
virtual unsigned int get_property_nocheck (const PROPERTY) const
virtual void set_property_nocheck (const PROPERTY, const unsigned int)
Detailed Description
RawTowerv1 but allow flexible tags.
Definition at line 13 of file RawTowerv2.h.
View newest version in sPHENIX GitHub at line 13 of file RawTowerv2.h
Member Typedef Documentation
typedef uint8_t RawTowerv2::prop_id_t protected
Definition at line 39 of file RawTowerv2.h.
View newest version in sPHENIX GitHub at line 39 of file RawTowerv2.h
typedef std::map<prop_id_t, double> RawTowerv2::prop_map_t protected
Definition at line 40 of file RawTowerv2.h.
View newest version in sPHENIX GitHub at line 40 of file RawTowerv2.h
Constructor & Destructor Documentation
RawTowerv2::RawTowerv2 () default
RawTowerv2::RawTowerv2 (const RawTower & tower)
Definition at line 13 of file RawTowerv2.cc.
View newest version in sPHENIX GitHub at line 13 of file RawTowerv2.cc
References RawTower::get_property(), RawTower::has_property(), and set_property().
RawTowerv2::RawTowerv2 (RawTowerDefs::keytype id)
Definition at line 29 of file RawTowerv2.cc.
View newest version in sPHENIX GitHub at line 29 of file RawTowerv2.cc
RawTowerv2::RawTowerv2 (const unsigned int ieta, const unsigned int iphi)
Definition at line 34 of file RawTowerv2.cc.
View newest version in sPHENIX GitHub at line 34 of file RawTowerv2.cc
RawTowerv2::RawTowerv2 (const RawTowerDefs::CalorimeterId caloid, const unsigned int ieta, const unsigned int iphi)
Definition at line 39 of file RawTowerv2.cc.
View newest version in sPHENIX GitHub at line 39 of file RawTowerv2.cc
RawTowerv2::~RawTowerv2 () inline override
Definition at line 22 of file RawTowerv2.h.
View newest version in sPHENIX GitHub at line 22 of file RawTowerv2.h
Member Function Documentation
double RawTowerv2::get_cerenkov_gammas () const inline override virtual
energy assigned to the tower. Depending on stage of process and DST node name, it could be energy deposition, light yield or calibrated energies
Reimplemented from RawTower.
Definition at line 30 of file RawTowerv2.h.
View newest version in sPHENIX GitHub at line 30 of file RawTowerv2.h
References get_property(), and RawTower::prop_cerenkov_gammas.
double RawTowerv2::get_property (const PROPERTY prop_id) const override virtual
Reimplemented from RawTower.
Definition at line 76 of file RawTowerv2.cc.
View newest version in sPHENIX GitHub at line 76 of file RawTowerv2.cc
References i, and prop_map.
Referenced by get_cerenkov_gammas(), get_scint_gammas(), and identify().
double RawTowerv2::get_scint_gammas () const inline override virtual
energy assigned to the tower. Depending on stage of process and DST node name, it could be energy deposition, light yield or calibrated energies
Reimplemented from RawTower.
Definition at line 28 of file RawTowerv2.h.
View newest version in sPHENIX GitHub at line 28 of file RawTowerv2.h
References get_property(), and RawTower::prop_scint_gammas.
bool RawTowerv2::has_property (const PROPERTY prop_id) const override virtual
Reimplemented from RawTower.
Definition at line 69 of file RawTowerv2.cc.
View newest version in sPHENIX GitHub at line 69 of file RawTowerv2.cc
References i, and prop_map.
void RawTowerv2::identify (std::ostream & os = std::cout) const override virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from RawTowerv1.
Definition at line 56 of file RawTowerv2.cc.
View newest version in sPHENIX GitHub at line 56 of file RawTowerv2.cc
References RawTowerv1::get_bineta(), RawTowerv1::get_binphi(), RawTowerv1::get_energy(), get_property(), RawTower::get_property_info(), i, and prop_map.
int RawTowerv2::isValid () const override virtual
isValid returns non zero if object contains vailid data
Reimplemented from RawTowerv1.
Definition at line 51 of file RawTowerv2.cc.
View newest version in sPHENIX GitHub at line 51 of file RawTowerv2.cc
References RawTowerv1::isValid().
void RawTowerv2::Reset () override virtual
Clear Event.
Reimplemented from RawTowerv1.
Definition at line 45 of file RawTowerv2.cc.
View newest version in sPHENIX GitHub at line 45 of file RawTowerv2.cc
References prop_map, and RawTowerv1::Reset().
void RawTowerv2::set_cerenkov_gammas (const double) inline override virtual
cerenkov_gammas assigned to the tower. Depending on stage of process and DST node name, it could be cerenkov_gammas deposition, light yield or calibrated energies
Reimplemented from RawTower.
Definition at line 31 of file RawTowerv2.h.
View newest version in sPHENIX GitHub at line 31 of file RawTowerv2.h
References RawTower::prop_cerenkov_gammas, and set_property().
void RawTowerv2::set_property (const PROPERTY prop_id, const double value) override virtual
Reimplemented from RawTower.
Definition at line 88 of file RawTowerv2.cc.
View newest version in sPHENIX GitHub at line 88 of file RawTowerv2.cc
References prop_map, and value.
Referenced by RawTowerv2(), set_cerenkov_gammas(), and set_scint_gammas().
void RawTowerv2::set_scint_gammas (const double) inline override virtual
scint_gammas assigned to the tower. Depending on stage of process and DST node name, it could be scint_gammas deposition, light yield or calibrated energies
Reimplemented from RawTower.
Definition at line 29 of file RawTowerv2.h.
View newest version in sPHENIX GitHub at line 29 of file RawTowerv2.h
References RawTower::prop_scint_gammas, and set_property().
Member Data Documentation
prop_map_t RawTowerv2::prop_map protected
container for additional property
Definition at line 42 of file RawTowerv2.h.
View newest version in sPHENIX GitHub at line 42 of file RawTowerv2.h
Referenced by get_property(), has_property(), identify(), Reset(), and set_property().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/CaloBase/RawTowerv2.h
coresoftware/blob/master/offline/packages/CaloBase/RawTowerv2.cc