Analysis Software: TSQLDate Class Reference
TSQLDate Class Reference
#include <RDBC/blob/master/include/RDBC/TSQLTypes.h>
Public Member Functions
TSQLDate (Int_t year, Int_t month, Int_t day)
TSQLDate ()
TSQLDate (UInt_t t)
TSQLDate (const TSQLDate &d)
virtual ~TSQLDate ()
TSQLDate & operator= (const TSQLDate &d)
Int_t GetYear () const
Int_t GetMonth () const
Int_t GetDay () const
void SetYear (Int_t year)
void SetMonth (Int_t month)
void SetDay (Int_t day)
TString ToString () const
Detailed Description
Definition at line 49 of file TSQLTypes.h.
View newest version in sPHENIX GitHub at line 49 of file TSQLTypes.h
Constructor & Destructor Documentation
TSQLDate::TSQLDate (Int_t year, Int_t month, Int_t day)
TSQLDate::TSQLDate () inline
Definition at line 54 of file TSQLTypes.h.
View newest version in sPHENIX GitHub at line 54 of file TSQLTypes.h
TSQLDate::TSQLDate (UInt_t t) inline
Definition at line 55 of file TSQLTypes.h.
View newest version in sPHENIX GitHub at line 55 of file TSQLTypes.h
References t.
TSQLDate::TSQLDate (const TSQLDate & d) inline
Definition at line 57 of file TSQLTypes.h.
View newest version in sPHENIX GitHub at line 57 of file TSQLTypes.h
virtual TSQLDate::~TSQLDate () inline virtual
Definition at line 58 of file TSQLTypes.h.
View newest version in sPHENIX GitHub at line 58 of file TSQLTypes.h
Member Function Documentation
Int_t TSQLDate::GetDay () const inline
Definition at line 65 of file TSQLTypes.h.
View newest version in sPHENIX GitHub at line 65 of file TSQLTypes.h
Referenced by ODBCPreparedStatement::SetDate(), ODBCCallableStatement::SetDate(), SetMonth(), SetYear(), and ODBCResultSet::UpdateDate().
Int_t TSQLDate::GetMonth () const inline
Definition at line 64 of file TSQLTypes.h.
View newest version in sPHENIX GitHub at line 64 of file TSQLTypes.h
Referenced by ODBCPreparedStatement::SetDate(), ODBCCallableStatement::SetDate(), SetDay(), SetYear(), and ODBCResultSet::UpdateDate().
Int_t TSQLDate::GetYear () const inline
Definition at line 63 of file TSQLTypes.h.
View newest version in sPHENIX GitHub at line 63 of file TSQLTypes.h
Referenced by ODBCPreparedStatement::SetDate(), ODBCCallableStatement::SetDate(), SetDay(), SetMonth(), and ODBCResultSet::UpdateDate().
TSQLDate & TSQLDate::operator= (const TSQLDate & d) inline
Definition at line 143 of file TSQLTypes.h.
View newest version in sPHENIX GitHub at line 143 of file TSQLTypes.h
void TSQLDate::SetDay (Int_t day)
Definition at line 67 of file TSQLTypes.cxx.
View newest version in sPHENIX GitHub at line 67 of file TSQLTypes.cxx
References GetMonth(), GetYear(), and Set().
void TSQLDate::SetMonth (Int_t month)
Definition at line 59 of file TSQLTypes.cxx.
View newest version in sPHENIX GitHub at line 59 of file TSQLTypes.cxx
References GetDay(), GetYear(), and Set().
void TSQLDate::SetYear (Int_t year)
Definition at line 51 of file TSQLTypes.cxx.
View newest version in sPHENIX GitHub at line 51 of file TSQLTypes.cxx
References GetDay(), GetMonth(), and Set().
TString TSQLDate::ToString () const
Definition at line 75 of file TSQLTypes.cxx.
View newest version in sPHENIX GitHub at line 75 of file TSQLTypes.cxx
References str.
The documentation for this class was generated from the following files:
RDBC/blob/master/include/RDBC/TSQLTypes.h
RDBC/blob/master/rdbc/TSQLTypes.cxx