Analysis Software: ActsExamples::SeedingFTFAlgorithm Exception Reference
ActsExamples::SeedingFTFAlgorithm Exception Reference final
#include <acts/blob/sPHENIX/Examples/Algorithms/TrackFinding/include/ActsExamples/TrackFinding/SeedingFTFAlgorithm.hpp>
Classes
struct Config
Public Member Functions
SeedingFTFAlgorithm (Config cfg, Acts::Logging::Level lvl)
ProcessCode execute (const AlgorithmContext &ctx) const override
const Config & config () const
std::map< std::pair< int, int >
, std::pair< int, int > > Make_ACTS_FTF_Map () const
std::vector< Acts::FTF_SP
< SimSpacePoint > > Make_FTF_spacePoints (const AlgorithmContext &ctx, std::map< std::pair< int, int >, std::pair< int, int >> map) const
std::vector
< Acts::TrigInDetSiLayer > LayerNumbering () const
Public Member Functions inherited from ActsExamples::IAlgorithm
IAlgorithm (std::string name, Acts::Logging::Level level=Acts::Logging::INFO)
std::string name () const override
The algorithm name.
ProcessCode internalExecute (const AlgorithmContext &context) final
ProcessCode initialize () override
Initialize the algorithm.
ProcessCode finalize () override
Finalize the algorithm.
Private Attributes
Config m_cfg
std::unique_ptr
< Acts::TrigFTF_GNN_Geometry
< SimSpacePoint > > mGNNgeo
std::vector< std::unique_ptr
< ReadDataHandle
< SimSpacePointContainer > > > m_inputSpacePoints {}
WriteDataHandle< SimSeedContainer > m_outputSeeds {this, "OutputSeeds"}
ReadDataHandle
< IndexSourceLinkContainer > m_inputSourceLinks
Additional Inherited Members
Protected Member Functions inherited from ActsExamples::IAlgorithm
const Acts::Logger & logger () const
Detailed Description
Definition at line 31 of file SeedingFTFAlgorithm.hpp.
View newest version in sPHENIX GitHub at line 31 of file SeedingFTFAlgorithm.hpp
Constructor & Destructor Documentation
ActsExamples::SeedingFTFAlgorithm::SeedingFTFAlgorithm (Config cfg, Acts::Logging::Level lvl)
Parameters
cfg is the algorithm configuration
lvl is the logging level
Definition at line 38 of file SeedingFTFAlgorithm.cpp.
View newest version in sPHENIX GitHub at line 38 of file SeedingFTFAlgorithm.cpp
References ActsExamples::SeedingFTFAlgorithm::Config::ACTS_FTF_Map, Acts::SeedFinderFTFConfig< SpacePoint >::calculateDerivedQuantities(), Acts::SeedFinderOptions::calculateDerivedQuantities(), Acts::SeedFinderFTFConfig< SpacePoint >::fastrack_input_file, in, ActsExamples::WriteDataHandle< T >::initialize(), ActsExamples::ReadDataHandle< T >::initialize(), ActsExamples::SeedingFTFAlgorithm::Config::inputSourceLinks, ActsExamples::SeedingFTFAlgorithm::Config::inputSpacePoints, ActsExamples::SeedingFTFAlgorithm::Config::layerMappingFile, LayerNumbering(), m_cfg, m_inputSourceLinks, m_inputSpacePoints, Acts::SeedFinderFTFConfig< SpacePoint >::m_layerGeometry, m_outputSeeds, Make_ACTS_FTF_Map(), mGNNgeo, ActsExamples::SeedingFTFAlgorithm::Config::outputSeeds, Acts::SeedFinderFTFConfig< SpacePoint >::seedFilter, ActsExamples::SeedingFTFAlgorithm::Config::seedFilterConfig, ActsExamples::SeedingFTFAlgorithm::Config::seedFinderConfig, ActsExamples::SeedingFTFAlgorithm::Config::seedFinderOptions, to_string(), Acts::SeedFilterConfig::toInternalUnits(), Acts::SeedFinderFTFConfig< SpacePoint >::toInternalUnits(), and Acts::SeedFinderOptions::toInternalUnits().
Member Function Documentation
const Config& ActsExamples::SeedingFTFAlgorithm::config () const inline
Definition at line 66 of file SeedingFTFAlgorithm.hpp.
View newest version in sPHENIX GitHub at line 66 of file SeedingFTFAlgorithm.hpp
References m_cfg.
ActsExamples::ProcessCode ActsExamples::SeedingFTFAlgorithm::execute (const AlgorithmContext & ctx) const override virtual
Parameters
txt is the algorithm context with event information
Returns
a process code indication success or failure
Implements ActsExamples::IAlgorithm.
Definition at line 92 of file SeedingFTFAlgorithm.cpp.
View newest version in sPHENIX GitHub at line 92 of file SeedingFTFAlgorithm.cpp
References ACTS_DEBUG, Acts::SeedFinderFTF< external_spacepoint_t >::createSeeds(), Acts::SeedFinderFTF< external_spacepoint_t >::createSeeds_old(), Acts::SeedFinderFTF< external_spacepoint_t >::loadSpacePoints(), m_cfg(), testing::internal::move(), position, SUCCESS, ActsExamples::SimSpacePoint::varianceR(), ActsExamples::SimSpacePoint::varianceZ(), ActsExamples::SimSpacePoint::x(), ActsExamples::SimSpacePoint::y(), and ActsExamples::SimSpacePoint::z().
std::vector< Acts::TrigInDetSiLayer > ActsExamples::SeedingFTFAlgorithm::LayerNumbering () const
Definition at line 252 of file SeedingFTFAlgorithm.cpp.
View newest version in sPHENIX GitHub at line 252 of file SeedingFTFAlgorithm.cpp
References release::app, Acts::Surface::bounds(), Acts::Surface::center(), distance(), fout, Acts::GeometryObject::geometryId(), i, index, Acts::GeometryIdentifier::layer(), Acts::Surface::localToGlobal(), m_cfg(), Acts::UnitConstants::min, n, out, Acts::GeometryIdentifier::sensitive(), writeMapConfig::surface, Acts::SurfaceBounds::values(), and Acts::GeometryIdentifier::volume().
Referenced by SeedingFTFAlgorithm().
std::map< std::pair< int, int >, std::pair< int, int > > ActsExamples::SeedingFTFAlgorithm::Make_ACTS_FTF_Map () const
Definition at line 139 of file SeedingFTFAlgorithm.cpp.
View newest version in sPHENIX GitHub at line 139 of file SeedingFTFAlgorithm.cpp
References configureMap::data, i, line, and m_cfg().
Referenced by SeedingFTFAlgorithm().
std::vector< Acts::FTF_SP< ActsExamples::SimSpacePoint > > ActsExamples::SeedingFTFAlgorithm::Make_FTF_spacePoints (const AlgorithmContext & ctx, std::map< std::pair< int, int >, std::pair< int, int >> map) const
Definition at line 170 of file SeedingFTFAlgorithm.cpp.
View newest version in sPHENIX GitHub at line 170 of file SeedingFTFAlgorithm.cpp
References ACTS_VERBOSE, and ACTS_WARNING.
Member Data Documentation
Config ActsExamples::SeedingFTFAlgorithm::m_cfg private
Definition at line 79 of file SeedingFTFAlgorithm.hpp.
View newest version in sPHENIX GitHub at line 79 of file SeedingFTFAlgorithm.hpp
Referenced by config(), and SeedingFTFAlgorithm().
ReadDataHandle<IndexSourceLinkContainer> ActsExamples::SeedingFTFAlgorithm::m_inputSourceLinks private
Initial value:
{
      this, "InputSourceLinks"}
Definition at line 88 of file SeedingFTFAlgorithm.hpp.
View newest version in sPHENIX GitHub at line 88 of file SeedingFTFAlgorithm.hpp
Referenced by SeedingFTFAlgorithm().
std::vector<std::unique_ptr<ReadDataHandle<SimSpacePointContainer> > > ActsExamples::SeedingFTFAlgorithm::m_inputSpacePoints {} private
Definition at line 84 of file SeedingFTFAlgorithm.hpp.
View newest version in sPHENIX GitHub at line 84 of file SeedingFTFAlgorithm.hpp
Referenced by SeedingFTFAlgorithm().
WriteDataHandle<SimSeedContainer> ActsExamples::SeedingFTFAlgorithm::m_outputSeeds {this, "OutputSeeds"} private
Definition at line 86 of file SeedingFTFAlgorithm.hpp.
View newest version in sPHENIX GitHub at line 86 of file SeedingFTFAlgorithm.hpp
Referenced by SeedingFTFAlgorithm().
std::unique_ptr<Acts::TrigFTF_GNN_Geometry<SimSpacePoint> > ActsExamples::SeedingFTFAlgorithm::mGNNgeo private
Definition at line 81 of file SeedingFTFAlgorithm.hpp.
View newest version in sPHENIX GitHub at line 81 of file SeedingFTFAlgorithm.hpp
Referenced by SeedingFTFAlgorithm().
The documentation for this exception was generated from the following files:
acts/blob/sPHENIX/Examples/Algorithms/TrackFinding/include/ActsExamples/TrackFinding/SeedingFTFAlgorithm.hpp
acts/blob/sPHENIX/Examples/Algorithms/TrackFinding/src/SeedingFTFAlgorithm.cpp