Analysis Software: InttVertexFinder Class Reference
InttVertexFinder Class Reference
#include <coresoftware/blob/master/offline/packages/intt/InttVertexFinder.h>
Public Member Functions
InttVertexFinder (const std::string &name="InttVertexFinder")
~InttVertexFinder () override
int Init (PHCompositeNode *) override
module initialization
int InitRun (PHCompositeNode *topNode) override
run initialization
int process_event (PHCompositeNode *topNode) override
event processing
int End (PHCompositeNode *) override
end of process
void setBeamCenter (double x=0, double y=0)
Public Member Functions inherited from SubsysReco
~SubsysReco () override
virtual int EndRun (const int)
Called at the end of each run.
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
void Print (const std::string &="ALL") const override
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Private Member Functions
int createNodes (PHCompositeNode *topNode)
double calculateZvertex (double *zcenter=nullptr, double *zrms=nullptr, double *zmean=nullptr)
Private Attributes
InttVertexMap * m_inttvertexmap = nullptr
ActsGeometry * m_tGeometry = nullptr
TrkrClusterContainer * m_clusterlist = nullptr
TH1 * h_zvtxseed_ = nullptr
double xbeam_ = 0.
double ybeam_ = 0.
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = std::numeric_limits<int>::max() - 10
}
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Detailed Description
Definition at line 14 of file InttVertexFinder.h.
View newest version in sPHENIX GitHub at line 14 of file InttVertexFinder.h
Constructor & Destructor Documentation
InttVertexFinder::InttVertexFinder (const std::string & name = "InttVertexFinder")
Definition at line 31 of file InttVertexFinder.cc.
View newest version in sPHENIX GitHub at line 31 of file InttVertexFinder.cc
InttVertexFinder::~InttVertexFinder () override
Definition at line 36 of file InttVertexFinder.cc.
View newest version in sPHENIX GitHub at line 36 of file InttVertexFinder.cc
References h_zvtxseed_.
Member Function Documentation
double InttVertexFinder::calculateZvertex (double * zcenter = nullptr, double * zrms = nullptr, double * zmean = nullptr) private
Definition at line 141 of file InttVertexFinder.cc.
View newest version in sPHENIX GitHub at line 141 of file InttVertexFinder.cc
References parse_cmake_options::begin, c2, clusters, TrkrClusterContainer::getClusters(), ActsGeometry::getGlobalPosition(), TrkrClusterContainer::getHitSetKeys(), h_zvtxseed_, TrkrDefs::inttId, layer, m_clusterlist, m_tGeometry, ActsTests::PropagationDatasets::phi, Acts::Test::pos, physmon_ckf_tracking::u, Fun4AllBase::Verbosity(), vz, xbeam_, and ybeam_.
Referenced by process_event().
int InttVertexFinder::createNodes (PHCompositeNode * topNode) private
Definition at line 70 of file InttVertexFinder.cc.
View newest version in sPHENIX GitHub at line 70 of file InttVertexFinder.cc
References Fun4AllReturnCodes::ABORTEVENT, PHCompositeNode::addNode(), Fun4AllReturnCodes::EVENT_OK, PHNodeIterator::findFirst(), m_inttvertexmap, and PHWHERE.
Referenced by InitRun().
int InttVertexFinder::End (PHCompositeNode *) inline override virtual
end of process
Reimplemented from SubsysReco.
Definition at line 30 of file InttVertexFinder.h.
View newest version in sPHENIX GitHub at line 30 of file InttVertexFinder.h
int InttVertexFinder::Init (PHCompositeNode *) override virtual
module initialization
Reimplemented from SubsysReco.
Definition at line 41 of file InttVertexFinder.cc.
View newest version in sPHENIX GitHub at line 41 of file InttVertexFinder.cc
References Fun4AllReturnCodes::EVENT_OK, and h_zvtxseed_.
int InttVertexFinder::InitRun (PHCompositeNode * topNode) override virtual
run initialization
Reimplemented from SubsysReco.
Definition at line 49 of file InttVertexFinder.cc.
View newest version in sPHENIX GitHub at line 49 of file InttVertexFinder.cc
References Fun4AllReturnCodes::ABORTEVENT, createNodes(), Fun4AllReturnCodes::EVENT_OK, Fun4AllBase::Verbosity(), xbeam_, and ybeam_.
int InttVertexFinder::process_event (PHCompositeNode * topNode) override virtual
event processing
Reimplemented from SubsysReco.
Definition at line 99 of file InttVertexFinder.cc.
View newest version in sPHENIX GitHub at line 99 of file InttVertexFinder.cc
References Fun4AllReturnCodes::ABORTEVENT, Fun4AllReturnCodes::ABORTRUN, calculateZvertex(), Fun4AllReturnCodes::EVENT_OK, InttVertexMap::insert(), m_clusterlist, m_inttvertexmap, m_tGeometry, PHWHERE, and Fun4AllBase::Verbosity().
void InttVertexFinder::setBeamCenter (double x = 0, double y = 0) inline
Definition at line 32 of file InttVertexFinder.h.
View newest version in sPHENIX GitHub at line 32 of file InttVertexFinder.h
References ambiguity_solver_full_chain::x, xbeam_, y, and ybeam_.
Member Data Documentation
TH1* InttVertexFinder::h_zvtxseed_ = nullptr private
Definition at line 48 of file InttVertexFinder.h.
View newest version in sPHENIX GitHub at line 48 of file InttVertexFinder.h
Referenced by calculateZvertex(), Init(), and ~InttVertexFinder().
TrkrClusterContainer* InttVertexFinder::m_clusterlist = nullptr private
Definition at line 46 of file InttVertexFinder.h.
View newest version in sPHENIX GitHub at line 46 of file InttVertexFinder.h
Referenced by calculateZvertex(), and process_event().
InttVertexMap* InttVertexFinder::m_inttvertexmap = nullptr private
Definition at line 44 of file InttVertexFinder.h.
View newest version in sPHENIX GitHub at line 44 of file InttVertexFinder.h
Referenced by createNodes(), and process_event().
ActsGeometry* InttVertexFinder::m_tGeometry = nullptr private
Definition at line 45 of file InttVertexFinder.h.
View newest version in sPHENIX GitHub at line 45 of file InttVertexFinder.h
Referenced by calculateZvertex(), and process_event().
double InttVertexFinder::xbeam_ = 0. private
Definition at line 52 of file InttVertexFinder.h.
View newest version in sPHENIX GitHub at line 52 of file InttVertexFinder.h
Referenced by calculateZvertex(), InitRun(), and setBeamCenter().
double InttVertexFinder::ybeam_ = 0. private
Definition at line 53 of file InttVertexFinder.h.
View newest version in sPHENIX GitHub at line 53 of file InttVertexFinder.h
Referenced by calculateZvertex(), InitRun(), and setBeamCenter().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/intt/InttVertexFinder.h
coresoftware/blob/master/offline/packages/intt/InttVertexFinder.cc