Analysis Software: macros/blob/master/common/G4_Micromegas.C File Reference
G4_Micromegas.C File Reference
#include <GlobalVariables.C>
#include <G4_Intt.C>
#include <G4_Mvtx.C>
#include <G4_TPC.C>
#include <g4micromegas/PHG4MicromegasDigitizer.h>
#include <g4micromegas/PHG4MicromegasHitReco.h>
#include <g4micromegas/PHG4MicromegasSubsystem.h>
#include <g4main/PHG4Reco.h>
#include <micromegas/MicromegasClusterizer.h>
#include <fun4all/Fun4AllServer.h>
Namespaces
namespace Enable
namespace G4MICROMEGAS
Macros
#define MACRO_G4MICROMEGAS_C
Enumerations
enum G4MICROMEGAS::Config {
G4MICROMEGAS::CONFIG_MINIMAL, G4MICROMEGAS::CONFIG_PHI_ONE_RING, G4MICROMEGAS::CONFIG_Z_ONE_SECTOR, G4MICROMEGAS::CONFIG_BASELINE,
G4MICROMEGAS::CONFIG_MAXIMAL
}
Functions
void MicromegasInit ()
void Micromegas (PHG4Reco *g4Reco)
void Micromegas_Cells ()
void Micromegas_Clustering ()
Variables
bool Enable::MICROMEGAS = false
bool Enable::MICROMEGAS_CELL = false
bool Enable::MICROMEGAS_CLUSTER = false
int G4MICROMEGAS::n_micromegas_layer = 2
Config G4MICROMEGAS::CONFIG = CONFIG_BASELINE
Macro Definition Documentation
#define MACRO_G4MICROMEGAS_C
Definition at line 2 of file G4_Micromegas.C.
View newest version in sPHENIX GitHub at line 2 of file G4_Micromegas.C
Function Documentation
void Micromegas (PHG4Reco * g4Reco)
Definition at line 65 of file G4_Micromegas.C.
View newest version in sPHENIX GitHub at line 65 of file G4_Micromegas.C
References Acts::UnitConstants::mm, G4TPC::n_gas_layer, G4INTT::n_intt_layer, G4MVTX::n_maps_layer, and PHG4Reco::registerSubsystem().
Referenced by G4Setup().
void Micromegas_Cells ()
Definition at line 75 of file G4_Micromegas.C.
View newest version in sPHENIX GitHub at line 75 of file G4_Micromegas.C
References G4MICROMEGAS::CONFIG, G4MICROMEGAS::CONFIG_BASELINE, G4MICROMEGAS::CONFIG_MAXIMAL, G4MICROMEGAS::CONFIG_MINIMAL, G4MICROMEGAS::CONFIG_PHI_ONE_RING, G4MICROMEGAS::CONFIG_Z_ONE_SECTOR, i, Fun4AllServer::instance(), G4PLUGDOOR::length, M_PI, phi, and Fun4AllBase::Verbosity().
Referenced by Fun4All_AnaTutorial_sPHENIX(), Fun4All_AnaTutorial_sPHENIX_Jets(), and Fun4All_G4_sPHENIX().
void Micromegas_Clustering ()
Definition at line 177 of file G4_Micromegas.C.
View newest version in sPHENIX GitHub at line 177 of file G4_Micromegas.C
References Fun4AllServer::instance().
Referenced by Fun4All_AnaTutorial_sPHENIX(), Fun4All_AnaTutorial_sPHENIX_Jets(), and Fun4All_G4_sPHENIX().
void MicromegasInit ()
Definition at line 45 of file G4_Micromegas.C.
View newest version in sPHENIX GitHub at line 45 of file G4_Micromegas.C
References Enable::INTT, max, BlackHoleGeometry::max_radius, BlackHoleGeometry::max_z, min, BlackHoleGeometry::min_z, Enable::MVTX, G4TPC::n_gas_layer, G4INTT::n_intt_layer, G4MVTX::n_maps_layer, and Enable::TPC.
Referenced by G4Init().