Analysis Software: ActsExamples::RefittingCalibrator Struct Reference
ActsExamples::RefittingCalibrator Struct Reference
#include <acts/blob/sPHENIX/Examples/Algorithms/TrackFitting/include/ActsExamples/TrackFitting/RefittingCalibrator.hpp>
Classes
struct RefittingSourceLink
Public Types
using Proxy = Acts::VectorMultiTrajectory::TrackStateProxy
using ConstProxy = Acts::ConstVectorMultiTrajectory::ConstTrackStateProxy
Public Member Functions
void calibrate (const Acts::GeometryContext &gctx, const Acts::CalibrationContext &cctx, const Acts::SourceLink &sourceLink, Proxy trackState) const
Detailed Description
Definition at line 26 of file RefittingCalibrator.hpp.
View newest version in sPHENIX GitHub at line 26 of file RefittingCalibrator.hpp
Member Typedef Documentation
using ActsExamples::RefittingCalibrator::ConstProxy = Acts::ConstVectorMultiTrajectory::ConstTrackStateProxy
Definition at line 28 of file RefittingCalibrator.hpp.
View newest version in sPHENIX GitHub at line 28 of file RefittingCalibrator.hpp
using ActsExamples::RefittingCalibrator::Proxy = Acts::VectorMultiTrajectory::TrackStateProxy
Definition at line 27 of file RefittingCalibrator.hpp.
View newest version in sPHENIX GitHub at line 27 of file RefittingCalibrator.hpp
Member Function Documentation
void ActsExamples::RefittingCalibrator::calibrate (const Acts::GeometryContext & gctx, const Acts::CalibrationContext & cctx, const Acts::SourceLink & sourceLink, Proxy trackState) const
Definition at line 18 of file RefittingCalibrator.cpp.
View newest version in sPHENIX GitHub at line 18 of file RefittingCalibrator.cpp
References Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::allocateCalibrated(), Acts::SourceLink::get(), N, Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::setProjectorBitset(), Acts::detail_lt::TrackStateProxy< trajectory_t, M, ReadOnly >::setUncalibratedSourceLink(), Size(), value, and Acts::visit_measurement().
The documentation for this struct was generated from the following files:
acts/blob/sPHENIX/Examples/Algorithms/TrackFitting/include/ActsExamples/TrackFitting/RefittingCalibrator.hpp
acts/blob/sPHENIX/Examples/Algorithms/TrackFitting/src/RefittingCalibrator.cpp