Analysis Software: PHG4ConeDetector Class Reference
PHG4ConeDetector Class Reference
#include <coresoftware/blob/master/simulation/g4simulation/g4detectors/PHG4ConeDetector.h>
Public Member Functions
PHG4ConeDetector (PHG4Subsystem *subsys, PHCompositeNode *Node, PHParameters *parameters, const std::string &dnam, const int lyr=0)
constructor
~PHG4ConeDetector (void) override
destructor
void ConstructMe (G4LogicalVolume *world) override
construct
void SuperDetector (const std::string &name)
const std::string SuperDetector () const
int get_Layer () const
volume accessors
bool IsInConeActive (G4VPhysicalVolume *)
Public Member Functions inherited from PHG4Detector
PHG4Detector ()=delete
constructor
PHG4Detector (PHG4Subsystem *subsys, PHCompositeNode *Node, const std::string &nam)
virtual ~PHG4Detector (void)
destructor
virtual void Construct (G4LogicalVolume *world) final
construct method
virtual void PostConstruction ()
Optional PostConstruction call after all geometry is constructed.
virtual void Verbosity (const int v)
virtual int Verbosity () const
virtual G4UserSteppingAction * GetSteppingAction ()
virtual std::string GetName () const
virtual void OverlapCheck (const bool chk)
virtual bool OverlapCheck () const
virtual void Print (const std::string &="ALL") const
virtual int DisplayVolume (G4VSolid *volume, G4LogicalVolume *logvol, G4RotationMatrix *rotm=nullptr)
virtual int DisplayVolume (G4LogicalVolume *checksolid, G4LogicalVolume *logvol, G4RotationMatrix *rotm=nullptr)
virtual PHCompositeNode * topNode ()
virtual PHG4Subsystem * GetMySubsystem ()
Private Attributes
PHParameters * m_Params = nullptr
G4VPhysicalVolume * m_ConePhysVol = nullptr
PHG4ConeDisplayAction * m_DisplayAction = nullptr
int layer = -9999
std::string superdetector
Additional Inherited Members
Static Public Member Functions inherited from PHG4Detector
static G4Material * GetDetectorMaterial (const std::string &name, const bool quit=true)
static G4Element * GetDetectorElement (const std::string &name, const bool quit=true)
Detailed Description
Definition at line 17 of file PHG4ConeDetector.h.
View newest version in sPHENIX GitHub at line 17 of file PHG4ConeDetector.h
Constructor & Destructor Documentation
PHG4ConeDetector::PHG4ConeDetector (PHG4Subsystem * subsys, PHCompositeNode * Node, PHParameters * parameters, const std::string & dnam, const int lyr = 0)
constructor
Definition at line 26 of file PHG4ConeDetector.cc.
View newest version in sPHENIX GitHub at line 26 of file PHG4ConeDetector.cc
PHG4ConeDetector::~PHG4ConeDetector (void) inline override
destructor
Definition at line 24 of file PHG4ConeDetector.h.
View newest version in sPHENIX GitHub at line 24 of file PHG4ConeDetector.h
Member Function Documentation
void PHG4ConeDetector::ConstructMe (G4LogicalVolume * world) override virtual
construct
Implements PHG4Detector.
Definition at line 46 of file PHG4ConeDetector.cc.
View newest version in sPHENIX GitHub at line 46 of file PHG4ConeDetector.cc
References Acts::UnitConstants::cm, deg, PHParameters::get_double_param(), PHParameters::get_string_param(), PHG4Detector::GetDetectorMaterial(), PHG4Detector::GetMySubsystem(), PHG4Detector::GetName(), m_ConePhysVol, m_DisplayAction, m_Params, PHG4Detector::OverlapCheck(), PHG4Subsystem::SetLogicalVolume(), and PHG4ConeDisplayAction::SetMyVolume().
int PHG4ConeDetector::get_Layer () const inline
Definition at line 38 of file PHG4ConeDetector.h.
View newest version in sPHENIX GitHub at line 38 of file PHG4ConeDetector.h
References layer.
Referenced by PHG4ConeSteppingAction::UserSteppingAction().
bool PHG4ConeDetector::IsInConeActive (G4VPhysicalVolume * volume)
Definition at line 36 of file PHG4ConeDetector.cc.
View newest version in sPHENIX GitHub at line 36 of file PHG4ConeDetector.cc
References m_ConePhysVol.
Referenced by PHG4ConeSteppingAction::UserSteppingAction().
void PHG4ConeDetector::SuperDetector (const std::string & name) inline
Definition at line 36 of file PHG4ConeDetector.h.
View newest version in sPHENIX GitHub at line 36 of file PHG4ConeDetector.h
References perf_headwind::name, and superdetector.
Referenced by PHG4ConeSubsystem::InitRunSubsystem(), and PHG4ConeSteppingAction::SetInterfacePointers().
const std::string PHG4ConeDetector::SuperDetector () const inline
Definition at line 37 of file PHG4ConeDetector.h.
View newest version in sPHENIX GitHub at line 37 of file PHG4ConeDetector.h
References superdetector.
Member Data Documentation
int PHG4ConeDetector::layer = -9999 private
Definition at line 46 of file PHG4ConeDetector.h.
View newest version in sPHENIX GitHub at line 46 of file PHG4ConeDetector.h
Referenced by get_Layer().
G4VPhysicalVolume* PHG4ConeDetector::m_ConePhysVol = nullptr private
Definition at line 43 of file PHG4ConeDetector.h.
View newest version in sPHENIX GitHub at line 43 of file PHG4ConeDetector.h
Referenced by ConstructMe(), and IsInConeActive().
PHG4ConeDisplayAction* PHG4ConeDetector::m_DisplayAction = nullptr private
Definition at line 44 of file PHG4ConeDetector.h.
View newest version in sPHENIX GitHub at line 44 of file PHG4ConeDetector.h
Referenced by ConstructMe().
PHParameters* PHG4ConeDetector::m_Params = nullptr private
Definition at line 41 of file PHG4ConeDetector.h.
View newest version in sPHENIX GitHub at line 41 of file PHG4ConeDetector.h
Referenced by ConstructMe().
std::string PHG4ConeDetector::superdetector private
Definition at line 47 of file PHG4ConeDetector.h.
View newest version in sPHENIX GitHub at line 47 of file PHG4ConeDetector.h
Referenced by SuperDetector().
The documentation for this class was generated from the following files:
coresoftware/blob/master/simulation/g4simulation/g4detectors/PHG4ConeDetector.h
coresoftware/blob/master/simulation/g4simulation/g4detectors/PHG4ConeDetector.cc