Analysis Software: analysis/blob/master/AndersonAnalysisModules/TrackStudies/STrackCutStudy/macros/QuickDeltaPtExtractor.C File Reference
QuickDeltaPtExtractor.C File Reference
#include <iostream>
#include "TH1.h"
#include "TH2.h"
#include "TF1.h"
#include "TPad.h"
#include "TFile.h"
#include "TLine.h"
#include "TGraph.h"
#include "TError.h"
#include "TString.h"
#include "TNtuple.h"
#include "TLegend.h"
#include "TPaveText.h"
#include "TDirectory.h"
Functions
void QuickDeltaPtExtractor (const TString sInput=SInDef, const TString sOutput=SOutDef)
Variables
static const Ssiz_t NTxt = 3
static const Ssiz_t NPad = 2
static const Ssiz_t NPar = 3
static const Ssiz_t NVtx = 4
static const Ssiz_t NRange = 2
static const Ssiz_t NProj = 8
static const Ssiz_t NTrkCuts = 6
static const Ssiz_t NDPtCuts = 7
static const Ssiz_t NSigCuts = 5
static const TString SInTrack = "ntp_track"
static const TString SInTruth = "ntp_gtrack"
static const TString SInDef = "input/embed_only/final_merge/sPhenixG4_forPtCheck_embedScanOn_embedOnly.pt2040n100pim.d8m5y2023.root"
static const TString SOutDef = "varyDeltaPtCut.withPtDependentDeltaPtCut.pt2040n100pim.d10m5y2023.root"
Function Documentation
void QuickDeltaPtExtractor (const TString sInput = SInDef, const TString sOutput = SOutDef)
Definition at line 48 of file QuickDeltaPtExtractor.C.
View newest version in sPHENIX GitHub at line 48 of file QuickDeltaPtExtractor.C
References AddEntry(), cd(), Close(), cuts, Data, Draw(), Fill(), material_mapping_optimisation::flush, SColdQcdCorrelatorAnalysis::SCorrelatorUtilities::GetEntry(), GetParameter(), GetXaxis(), GetYaxis(), GetZaxis(), leg, line, NDPtCuts, NPad, NPar, NProj, NRange, NSigCuts, NTrkCuts, NTxt, NVtx, ProjectionY, Reset(), SetBorderMode(), SetBorderSize(), SetBottomMargin(), SetBranchAddress(), SetFillColor(), SetFillStyle(), SetFrameBorderMode(), SetLeftMargin(), SetLineColor(), SetLineStyle(), SetLineWidth(), SetLogy(), SetMarkerColor(), SetMarkerStyle(), SetName(), SetParameter(), SetRightMargin(), SetTextFont(), SetTitle(), SetTopMargin(), SInTrack, SInTruth, width, and Write().
Variable Documentation
const Ssiz_t NDPtCuts = 7 static
Definition at line 37 of file QuickDeltaPtExtractor.C.
View newest version in sPHENIX GitHub at line 37 of file QuickDeltaPtExtractor.C
Referenced by QuickDeltaPtExtractor().
const Ssiz_t NPad = 2 static
Definition at line 31 of file QuickDeltaPtExtractor.C.
View newest version in sPHENIX GitHub at line 31 of file QuickDeltaPtExtractor.C
Referenced by QuickDeltaPtExtractor(), and SDeltaPtCutStudy::SetStyles().
const Ssiz_t NPar = 3 static
Definition at line 32 of file QuickDeltaPtExtractor.C.
View newest version in sPHENIX GitHub at line 32 of file QuickDeltaPtExtractor.C
Referenced by QuickDeltaPtExtractor().
const Ssiz_t NProj = 8 static
Definition at line 35 of file QuickDeltaPtExtractor.C.
View newest version in sPHENIX GitHub at line 35 of file QuickDeltaPtExtractor.C
Referenced by QuickDeltaPtExtractor().
const Ssiz_t NRange = 2 static
Definition at line 34 of file QuickDeltaPtExtractor.C.
View newest version in sPHENIX GitHub at line 34 of file QuickDeltaPtExtractor.C
Referenced by SDeltaPtCutStudy::InitHists(), SColdQcdCorrelatorAnalysis::SCorrelatorJetTree::InitHists(), STrackCutStudy::InitHists(), and QuickDeltaPtExtractor().
const Ssiz_t NSigCuts = 5 static
Definition at line 38 of file QuickDeltaPtExtractor.C.
View newest version in sPHENIX GitHub at line 38 of file QuickDeltaPtExtractor.C
Referenced by QuickDeltaPtExtractor().
const Ssiz_t NTrkCuts = 6 static
Definition at line 36 of file QuickDeltaPtExtractor.C.
View newest version in sPHENIX GitHub at line 36 of file QuickDeltaPtExtractor.C
Referenced by SDeltaPtCutStudy::MakePlots(), and QuickDeltaPtExtractor().
const Ssiz_t NTxt = 3 static
Definition at line 30 of file QuickDeltaPtExtractor.C.
View newest version in sPHENIX GitHub at line 30 of file QuickDeltaPtExtractor.C
Referenced by QuickDeltaPtExtractor().
const Ssiz_t NVtx = 4 static
Definition at line 33 of file QuickDeltaPtExtractor.C.
View newest version in sPHENIX GitHub at line 33 of file QuickDeltaPtExtractor.C
Referenced by STrackCutStudy::ConstructPlots(), STrackCutStudy::MakeCutText(), SDeltaPtCutStudy::MakePlots(), and QuickDeltaPtExtractor().
const TString SInDef = "input/embed_only/final_merge/sPhenixG4_forPtCheck_embedScanOn_embedOnly.pt2040n100pim.d8m5y2023.root" static
Definition at line 43 of file QuickDeltaPtExtractor.C.
View newest version in sPHENIX GitHub at line 43 of file QuickDeltaPtExtractor.C
const TString SInTrack = "ntp_track" static
Definition at line 39 of file QuickDeltaPtExtractor.C.
View newest version in sPHENIX GitHub at line 39 of file QuickDeltaPtExtractor.C
Referenced by QuickDeltaPtExtractor().
const TString SInTruth = "ntp_gtrack" static
Definition at line 40 of file QuickDeltaPtExtractor.C.
View newest version in sPHENIX GitHub at line 40 of file QuickDeltaPtExtractor.C
Referenced by QuickDeltaPtExtractor().
const TString SOutDef = "varyDeltaPtCut.withPtDependentDeltaPtCut.pt2040n100pim.d10m5y2023.root" static
Definition at line 44 of file QuickDeltaPtExtractor.C.
View newest version in sPHENIX GitHub at line 44 of file QuickDeltaPtExtractor.C