Analysis Software: JETSCAPE/blob/main/external_packages/trento/test/test_event.cxx File Reference
test_event.cxx File Reference
#include "../src/event.h"
#include "catch.hpp"
#include "util.h"
#include "../src/nucleus.h"
#include "../src/random.h"
Functions
TEST_CASE ("event")
Function Documentation
TEST_CASE ("event")
Definition at line 15 of file test_event.cxx.
View newest version in sPHENIX GitHub at line 15 of file test_event.cxx
References KFPMath::a, A, KFPMath::b, CHECK, trento::Nucleus::create(), dy, Acts::UnitConstants::e, event, make_var_map(), n, norm, npart(), merge_hashes::p, ActsTests::PropagationDatasets::phi, profile(), sum(), t, ambiguity_solver_full_chain::t1, ambiguity_solver_full_chain::t2, thickness, ambiguity_solver_full_chain::x, xsec, and y.