Analysis Software: PHG4CylinderCellContainer Class Reference
PHG4CylinderCellContainer Class Reference
#include <coresoftware/blob/master/simulation/g4simulation/g4detectors/PHG4CylinderCellContainer.h>
Public Types
typedef std::map
< PHG4CylinderCellDefs::keytype,
PHG4CylinderCell * > Map
typedef Map::iterator Iterator
typedef Map::const_iterator ConstIterator
typedef std::pair< Iterator,
Iterator > Range
typedef std::pair
< ConstIterator, ConstIterator > ConstRange
typedef std::set< int >
::const_iterator LayerIter
typedef std::pair< LayerIter,
LayerIter > LayerRange
Public Member Functions
PHG4CylinderCellContainer ()
~PHG4CylinderCellContainer () override
void identify (std::ostream &os=std::cout) const override
void Reset () override
Clear Event.
ConstIterator AddCylinderCell (const unsigned int detid, PHG4CylinderCell *newcylinderCell)
ConstIterator AddCylinderCellSpecifyKey (const PHG4CylinderCellDefs::keytype key, PHG4CylinderCell *newcylinderCell)
void RemoveCylinderCell (PHG4CylinderCellDefs::keytype key)
preferred removal method, key is currently the cell id
void RemoveCylinderCell (PHG4CylinderCell *cell)
inefficent, use key where possible instead
Iterator findOrAddCylinderCell (PHG4CylinderCellDefs::keytype key)
PHG4CylinderCellDefs::keytype genkey (const unsigned int detid)
ConstRange getCylinderCells (const unsigned int detid) const
return all cylinderCells matching a given detid
ConstRange getCylinderCells (void) const
return all hist
PHG4CylinderCell * findCylinderCell (PHG4CylinderCellDefs::keytype key)
unsigned int size (void) const
unsigned int num_layers (void) const
LayerRange getLayers () const
double getTotalEdep () const
Public Member Functions inherited from PHObject
PHObject ()
ctor
~PHObject () override
dtor
virtual PHObject * CloneMe () const
Virtual copy constructor.
virtual PHObject * clone () const final
PHObject * Clone (const char *newname="") const final
void Copy (TObject &object) const final
virtual int isValid () const
isValid returns non zero if object contains vailid data
virtual int Integrate () const
virtual int Integrate (PHObject *)
virtual void CopyFrom (const PHObject *obj)
Protected Attributes
Map cellmap
std::set< int > layers
Detailed Description
Definition at line 17 of file PHG4CylinderCellContainer.h.
View newest version in sPHENIX GitHub at line 17 of file PHG4CylinderCellContainer.h
Member Typedef Documentation
typedef Map::const_iterator PHG4CylinderCellContainer::ConstIterator
Definition at line 22 of file PHG4CylinderCellContainer.h.
View newest version in sPHENIX GitHub at line 22 of file PHG4CylinderCellContainer.h
typedef std::pair<ConstIterator, ConstIterator> PHG4CylinderCellContainer::ConstRange
Definition at line 24 of file PHG4CylinderCellContainer.h.
View newest version in sPHENIX GitHub at line 24 of file PHG4CylinderCellContainer.h
typedef Map::iterator PHG4CylinderCellContainer::Iterator
Definition at line 21 of file PHG4CylinderCellContainer.h.
View newest version in sPHENIX GitHub at line 21 of file PHG4CylinderCellContainer.h
typedef std::set<int>::const_iterator PHG4CylinderCellContainer::LayerIter
Definition at line 25 of file PHG4CylinderCellContainer.h.
View newest version in sPHENIX GitHub at line 25 of file PHG4CylinderCellContainer.h
typedef std::pair<LayerIter, LayerIter> PHG4CylinderCellContainer::LayerRange
Definition at line 26 of file PHG4CylinderCellContainer.h.
View newest version in sPHENIX GitHub at line 26 of file PHG4CylinderCellContainer.h
typedef std::map<PHG4CylinderCellDefs::keytype, PHG4CylinderCell *> PHG4CylinderCellContainer::Map
Definition at line 20 of file PHG4CylinderCellContainer.h.
View newest version in sPHENIX GitHub at line 20 of file PHG4CylinderCellContainer.h
typedef std::pair<Iterator, Iterator> PHG4CylinderCellContainer::Range
Definition at line 23 of file PHG4CylinderCellContainer.h.
View newest version in sPHENIX GitHub at line 23 of file PHG4CylinderCellContainer.h
Constructor & Destructor Documentation
PHG4CylinderCellContainer::PHG4CylinderCellContainer () inline
Definition at line 28 of file PHG4CylinderCellContainer.h.
View newest version in sPHENIX GitHub at line 28 of file PHG4CylinderCellContainer.h
PHG4CylinderCellContainer::~PHG4CylinderCellContainer () inline override
Definition at line 30 of file PHG4CylinderCellContainer.h.
View newest version in sPHENIX GitHub at line 30 of file PHG4CylinderCellContainer.h
Member Function Documentation
PHG4CylinderCellContainer::ConstIterator PHG4CylinderCellContainer::AddCylinderCell (const unsigned int detid, PHG4CylinderCell * newcylinderCell)
Definition at line 60 of file PHG4CylinderCellContainer.cc.
View newest version in sPHENIX GitHub at line 60 of file PHG4CylinderCellContainer.cc
References PHG4CellDefs::SizeBinning::genkey(), PHG4CylinderCell::get_layer(), and PHG4CylinderCell::set_cell_id().
PHG4CylinderCellContainer::ConstIterator PHG4CylinderCellContainer::AddCylinderCellSpecifyKey (const PHG4CylinderCellDefs::keytype key, PHG4CylinderCell * newcylinderCell)
Definition at line 70 of file PHG4CylinderCellContainer.cc.
View newest version in sPHENIX GitHub at line 70 of file PHG4CylinderCellContainer.cc
References PHG4CylinderCell::get_layer(), and PHG4CylinderCell::set_cell_id().
PHG4CylinderCell * PHG4CylinderCellContainer::findCylinderCell (PHG4CylinderCellDefs::keytype key)
Definition at line 124 of file PHG4CylinderCellContainer.cc.
View newest version in sPHENIX GitHub at line 124 of file PHG4CylinderCellContainer.cc
References it.
PHG4CylinderCellContainer::Iterator PHG4CylinderCellContainer::findOrAddCylinderCell (PHG4CylinderCellDefs::keytype key)
Definition at line 109 of file PHG4CylinderCellContainer.cc.
View newest version in sPHENIX GitHub at line 109 of file PHG4CylinderCellContainer.cc
References PHG4CylinderCell::get_layer(), it, and PHG4CylinderCell::set_cell_id().
PHG4CylinderCellDefs::keytype PHG4CylinderCellContainer::genkey (const unsigned int detid)
Definition at line 40 of file PHG4CylinderCellContainer.cc.
View newest version in sPHENIX GitHub at line 40 of file PHG4CylinderCellContainer.cc
References PHG4CylinderCellDefs::cell_idbits, and PHG4CylinderCellDefs::keybits.
PHG4CylinderCellContainer::ConstRange PHG4CylinderCellContainer::getCylinderCells (const unsigned int detid) const
return all cylinderCells matching a given detid
Definition at line 84 of file PHG4CylinderCellContainer.cc.
View newest version in sPHENIX GitHub at line 84 of file PHG4CylinderCellContainer.cc
References PHG4CylinderCellDefs::cell_idbits, and PHG4CylinderCellDefs::keybits.
Referenced by DumpPHG4CylinderCellContainer::process_Node().
PHG4CylinderCellContainer::ConstRange PHG4CylinderCellContainer::getCylinderCells (void) const
return all hist
Definition at line 103 of file PHG4CylinderCellContainer.cc.
View newest version in sPHENIX GitHub at line 103 of file PHG4CylinderCellContainer.cc
LayerRange PHG4CylinderCellContainer::getLayers () const inline
Definition at line 83 of file PHG4CylinderCellContainer.h.
View newest version in sPHENIX GitHub at line 83 of file PHG4CylinderCellContainer.h
References layers.
double PHG4CylinderCellContainer::getTotalEdep () const
Definition at line 137 of file PHG4CylinderCellContainer.cc.
View newest version in sPHENIX GitHub at line 137 of file PHG4CylinderCellContainer.cc
void PHG4CylinderCellContainer::identify (std::ostream & os = std::cout) const override virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from PHObject.
Definition at line 21 of file PHG4CylinderCellContainer.cc.
View newest version in sPHENIX GitHub at line 21 of file PHG4CylinderCellContainer.cc
References identify, and size.
unsigned int PHG4CylinderCellContainer::num_layers (void) const inline
Definition at line 79 of file PHG4CylinderCellContainer.h.
View newest version in sPHENIX GitHub at line 79 of file PHG4CylinderCellContainer.h
References layers.
void PHG4CylinderCellContainer::RemoveCylinderCell (PHG4CylinderCellDefs::keytype key) inline
preferred removal method, key is currently the cell id
Definition at line 40 of file PHG4CylinderCellContainer.h.
View newest version in sPHENIX GitHub at line 40 of file PHG4CylinderCellContainer.h
References cellmap.
void PHG4CylinderCellContainer::RemoveCylinderCell (PHG4CylinderCell * cell) inline
inefficent, use key where possible instead
Definition at line 46 of file PHG4CylinderCellContainer.h.
View newest version in sPHENIX GitHub at line 46 of file PHG4CylinderCellContainer.h
References cellmap.
void PHG4CylinderCellContainer::Reset () override virtual
Clear Event.
Reimplemented from PHObject.
Definition at line 11 of file PHG4CylinderCellContainer.cc.
View newest version in sPHENIX GitHub at line 11 of file PHG4CylinderCellContainer.cc
unsigned int PHG4CylinderCellContainer::size (void) const inline
Definition at line 75 of file PHG4CylinderCellContainer.h.
View newest version in sPHENIX GitHub at line 75 of file PHG4CylinderCellContainer.h
References cellmap.
Referenced by DumpPHG4CylinderCellContainer::process_Node().
Member Data Documentation
Map PHG4CylinderCellContainer::cellmap protected
Definition at line 91 of file PHG4CylinderCellContainer.h.
View newest version in sPHENIX GitHub at line 91 of file PHG4CylinderCellContainer.h
Referenced by RemoveCylinderCell(), and size().
std::set<int> PHG4CylinderCellContainer::layers protected
Definition at line 92 of file PHG4CylinderCellContainer.h.
View newest version in sPHENIX GitHub at line 92 of file PHG4CylinderCellContainer.h
Referenced by getLayers(), and num_layers().
The documentation for this class was generated from the following files:
coresoftware/blob/master/simulation/g4simulation/g4detectors/PHG4CylinderCellContainer.h
coresoftware/blob/master/simulation/g4simulation/g4detectors/PHG4CylinderCellContainer.cc