Analysis Software: SvtxVertex Class Reference
SvtxVertex Class Reference
#include <coresoftware/blob/master/offline/packages/globalvertex/SvtxVertex.h>
Public Member Functions
~SvtxVertex () override
void identify (std::ostream &os=std::cout) const override
int isValid () const override
isValid returns non zero if object contains vailid data
PHObject * CloneMe () const override
Virtual copy constructor.
virtual unsigned int get_id () const override
virtual void set_id (unsigned int) override
virtual float get_t0 () const override
virtual void set_t0 (float t0) override
virtual float get_t () const override
virtual void set_t (float) override
virtual float get_x () const override
virtual void set_x (float) override
virtual float get_y () const override
virtual void set_y (float) override
virtual float get_z () const override
virtual void set_z (float) override
virtual float get_chisq () const override
virtual void set_chisq (float) override
virtual unsigned int get_ndof () const override
virtual void set_ndof (unsigned int) override
virtual float get_position (unsigned int) const override
virtual void set_position (unsigned int, float) override
virtual float get_error (unsigned int, unsigned int) const override
virtual void set_error (unsigned int, unsigned int, float) override
virtual void clear_tracks () override
virtual bool empty_tracks () override
virtual size_t size_tracks () const override
virtual void insert_track (unsigned int) override
virtual size_t erase_track (unsigned int) override
virtual ConstTrackIter begin_tracks () const override
virtual ConstTrackIter find_track (unsigned int trackid) const override
virtual ConstTrackIter end_tracks () const override
virtual TrackIter begin_tracks () override
virtual TrackIter find_track (unsigned int trackid) override
virtual TrackIter end_tracks () override
Public Member Functions inherited from Vertex
~Vertex () override
void identify (std::ostream &os=std::cout) const override
PHObject * CloneMe () const override
Virtual copy constructor.
int isValid () const override
isValid returns non zero if object contains vailid data
virtual float get_t_err () const
virtual void set_t_err (float)
virtual unsigned int get_beam_crossing () const
virtual void set_beam_crossing (unsigned int)
virtual void set_bbc_ns (int, int, float, float)
virtual int get_bbc_npmt (int) const
virtual float get_z_err () const
virtual void set_z_err (float)
virtual float get_bbc_q (int) const
virtual float get_bbc_t (int) const
Public Member Functions inherited from PHObject
PHObject ()
ctor
~PHObject () override
dtor
virtual PHObject * clone () const final
PHObject * Clone (const char *newname="") const final
void Copy (TObject &object) const final
virtual void Reset ()
Clear Event.
virtual int Integrate () const
virtual int Integrate (PHObject *)
virtual void CopyFrom (const PHObject *obj)
Protected Member Functions
ClassDefOverride (SvtxVertex, 1)
Additional Inherited Members
Public Types inherited from Vertex
typedef std::set< unsigned int > TrackSet
typedef std::set< unsigned int >
::const_iterator ConstTrackIter
typedef std::set< unsigned int >
::iterator TrackIter
Detailed Description
Definition at line 12 of file SvtxVertex.h.
View newest version in sPHENIX GitHub at line 12 of file SvtxVertex.h
Constructor & Destructor Documentation
SvtxVertex::~SvtxVertex () inline override
Definition at line 16 of file SvtxVertex.h.
View newest version in sPHENIX GitHub at line 16 of file SvtxVertex.h
Member Function Documentation
SvtxVertex::ConstTrackIter SvtxVertex::begin_tracks () const override virtual
Reimplemented from Vertex.
Reimplemented in SvtxVertex_v1, and SvtxVertex_v2.
Definition at line 5 of file SvtxVertex.cc.
View newest version in sPHENIX GitHub at line 5 of file SvtxVertex.cc
References trackSet.
Referenced by PHG4TrackFastSimEval::fill_vertex_tree(), QAG4SimulationVertex::process_event(), and GlobalVertexReco::process_event().
SvtxVertex::TrackIter SvtxVertex::begin_tracks () override virtual
Reimplemented from Vertex.
Reimplemented in SvtxVertex_v1, and SvtxVertex_v2.
Definition at line 20 of file SvtxVertex.cc.
View newest version in sPHENIX GitHub at line 20 of file SvtxVertex.cc
References trackSet.
SvtxVertex::ClassDefOverride (SvtxVertex , 1) protected
virtual void SvtxVertex::clear_tracks () inline override virtual
Reimplemented from Vertex.
Reimplemented in SvtxVertex_v1, and SvtxVertex_v2.
Definition at line 63 of file SvtxVertex.h.
View newest version in sPHENIX GitHub at line 63 of file SvtxVertex.h
PHObject* SvtxVertex::CloneMe () const inline override virtual
Virtual copy constructor.
Reimplemented from PHObject.
Reimplemented in SvtxVertex_v1, and SvtxVertex_v2.
Definition at line 26 of file SvtxVertex.h.
View newest version in sPHENIX GitHub at line 26 of file SvtxVertex.h
Referenced by SvtxVertexMap_v1::insert_clone().
virtual bool SvtxVertex::empty_tracks () inline override virtual
Reimplemented from Vertex.
Reimplemented in SvtxVertex_v1, and SvtxVertex_v2.
Definition at line 64 of file SvtxVertex.h.
View newest version in sPHENIX GitHub at line 64 of file SvtxVertex.h
SvtxVertex::ConstTrackIter SvtxVertex::end_tracks () const override virtual
Reimplemented from Vertex.
Reimplemented in SvtxVertex_v1, and SvtxVertex_v2.
Definition at line 15 of file SvtxVertex.cc.
View newest version in sPHENIX GitHub at line 15 of file SvtxVertex.cc
References trackSet.
Referenced by PHG4TrackFastSimEval::fill_vertex_tree(), QAG4SimulationVertex::process_event(), and GlobalVertexReco::process_event().
SvtxVertex::TrackIter SvtxVertex::end_tracks () override virtual
Reimplemented from Vertex.
Reimplemented in SvtxVertex_v1, and SvtxVertex_v2.
Definition at line 30 of file SvtxVertex.cc.
View newest version in sPHENIX GitHub at line 30 of file SvtxVertex.cc
References trackSet.
virtual size_t SvtxVertex::erase_track (unsigned int) inline override virtual
Reimplemented from Vertex.
Reimplemented in SvtxVertex_v1, and SvtxVertex_v2.
Definition at line 67 of file SvtxVertex.h.
View newest version in sPHENIX GitHub at line 67 of file SvtxVertex.h
SvtxVertex::ConstTrackIter SvtxVertex::find_track (unsigned int trackid) const override virtual
Reimplemented from Vertex.
Reimplemented in SvtxVertex_v1, and SvtxVertex_v2.
Definition at line 10 of file SvtxVertex.cc.
View newest version in sPHENIX GitHub at line 10 of file SvtxVertex.cc
References trackSet.
SvtxVertex::TrackIter SvtxVertex::find_track (unsigned int trackid) override virtual
Reimplemented from Vertex.
Reimplemented in SvtxVertex_v1, and SvtxVertex_v2.
Definition at line 25 of file SvtxVertex.cc.
View newest version in sPHENIX GitHub at line 25 of file SvtxVertex.cc
References trackSet.
virtual float SvtxVertex::get_chisq () const inline override virtual
Reimplemented from Vertex.
Reimplemented in SvtxVertex_v1, and SvtxVertex_v2.
Definition at line 48 of file SvtxVertex.h.
View newest version in sPHENIX GitHub at line 48 of file SvtxVertex.h
Referenced by KFParticle_Tools::makeVertex(), TpcPrototypeGenFitTrkFitter::ReFitTrack(), and PHGenFitTrkFitter::ReFitTrack().
virtual float SvtxVertex::get_error (unsigned int , unsigned int) const inline override virtual
Reimplemented from Vertex.
Reimplemented in SvtxVertex_v1, and SvtxVertex_v2.
Definition at line 57 of file SvtxVertex.h.
View newest version in sPHENIX GitHub at line 57 of file SvtxVertex.h
Referenced by PHG4TrackFastSimEval::fill_vertex_tree(), BDiJetModule::FillVertexMap(), SVReco::MakeGenFitTrack(), SVReco::MakeSvtxTrack(), PHGenFitTrkFitter::MakeSvtxTrack(), KFParticle_Tools::makeVertex(), Conversion::PHG4VtxPointToSvtxVertex(), PHHybridSeeding::Process(), GlobalVertexReco::process_event(), TpcPrototypeGenFitTrkFitter::ReFitTrack(), and PHGenFitTrkFitter::ReFitTrack().
virtual unsigned int SvtxVertex::get_id () const inline override virtual
Reimplemented from Vertex.
Reimplemented in SvtxVertex_v1, and SvtxVertex_v2.
Definition at line 30 of file SvtxVertex.h.
View newest version in sPHENIX GitHub at line 30 of file SvtxVertex.h
Referenced by PHG4TrackFastSimEval::fill_vertex_tree(), IsolatedTrackAnalysis::getTracks(), SvtxVertexMap_v1::operator=(), PHHybridSeeding::Process(), GlobalVertexReco::process_event(), and SvtxVertexMap_v1::SvtxVertexMap_v1().
virtual unsigned int SvtxVertex::get_ndof () const inline override virtual
Reimplemented from Vertex.
Reimplemented in SvtxVertex_v1, and SvtxVertex_v2.
Definition at line 51 of file SvtxVertex.h.
View newest version in sPHENIX GitHub at line 51 of file SvtxVertex.h
Referenced by KFParticle_Tools::makeVertex(), TpcPrototypeGenFitTrkFitter::ReFitTrack(), and PHGenFitTrkFitter::ReFitTrack().
virtual float SvtxVertex::get_position (unsigned int) const inline override virtual
Reimplemented from Vertex.
Reimplemented in SvtxVertex_v1, and SvtxVertex_v2.
Definition at line 54 of file SvtxVertex.h.
View newest version in sPHENIX GitHub at line 54 of file SvtxVertex.h
virtual float SvtxVertex::get_t () const inline override virtual
Reimplemented from Vertex.
Reimplemented in SvtxVertex_v1, and SvtxVertex_v2.
Definition at line 36 of file SvtxVertex.h.
View newest version in sPHENIX GitHub at line 36 of file SvtxVertex.h
Referenced by get_t0().
virtual float SvtxVertex::get_t0 () const inline override virtual
Reimplemented from Vertex.
Reimplemented in SvtxVertex_v1.
Definition at line 33 of file SvtxVertex.h.
View newest version in sPHENIX GitHub at line 33 of file SvtxVertex.h
References get_t().
virtual float SvtxVertex::get_x () const inline override virtual
Reimplemented from Vertex.
Reimplemented in SvtxVertex_v1, and SvtxVertex_v2.
Definition at line 39 of file SvtxVertex.h.
View newest version in sPHENIX GitHub at line 39 of file SvtxVertex.h
Referenced by PHG4TrackFastSimEval::fill_vertex_tree(), psTOFTimezeroEval::fillOutputNtuples(), SvtxEvaluatorHaiwang::fillOutputNtuples(), EventEvaluator::fillOutputNtuples(), BDiJetModule::FillVertexMap(), FilterEvents::get_dca(), PHTrackClusterAssociator::getCluster(), IsolatedTrackAnalysis::getTracks(), KshortReconstruction::getVertex(), BDiJetModule::MakeGenFitTrack(), SVReco::MakeGenFitTrack(), PHActsGSF::makePerigee(), SVReco::MakeSvtxTrack(), PHGenFitTrkFitter::MakeSvtxTrack(), ActsPropagator::makeTrackParams(), KFParticle_Tools::makeVertex(), HFTrigger::makeVertex(), HFTriggerMVA::makeVertex(), ActsPropagator::makeVertexSurface(), psTOFTimezeroEval::printOutputInfo(), SvtxEvaluatorHaiwang::printOutputInfo(), TrkrNtuplizer::printOutputInfo(), SvtxEvaluator::printOutputInfo(), PHSiliconTruthTrackSeeding::Process(), PHHybridSeeding::Process(), SvtxSimPerformanceCheckReco::process_event(), SimpleTrackingAnalysis::process_event(), QAG4SimulationVertex::process_event(), BJetModule::process_event(), PHGenFitTrkFitter::process_event(), TpcPrototypeGenFitTrkFitter::ReFitTrack(), and PHGenFitTrkFitter::ReFitTrack().
virtual float SvtxVertex::get_y () const inline override virtual
Reimplemented from Vertex.
Reimplemented in SvtxVertex_v1, and SvtxVertex_v2.
Definition at line 42 of file SvtxVertex.h.
View newest version in sPHENIX GitHub at line 42 of file SvtxVertex.h
Referenced by PHG4TrackFastSimEval::fill_vertex_tree(), psTOFTimezeroEval::fillOutputNtuples(), SvtxEvaluatorHaiwang::fillOutputNtuples(), EventEvaluator::fillOutputNtuples(), BDiJetModule::FillVertexMap(), PHTrackClusterAssociator::getCluster(), IsolatedTrackAnalysis::getTracks(), KshortReconstruction::getVertex(), BDiJetModule::MakeGenFitTrack(), SVReco::MakeGenFitTrack(), PHActsGSF::makePerigee(), SVReco::MakeSvtxTrack(), PHGenFitTrkFitter::MakeSvtxTrack(), ActsPropagator::makeTrackParams(), KFParticle_Tools::makeVertex(), HFTrigger::makeVertex(), HFTriggerMVA::makeVertex(), ActsPropagator::makeVertexSurface(), psTOFTimezeroEval::printOutputInfo(), SvtxEvaluatorHaiwang::printOutputInfo(), TrkrNtuplizer::printOutputInfo(), SvtxEvaluator::printOutputInfo(), PHSiliconTruthTrackSeeding::Process(), PHHybridSeeding::Process(), SvtxSimPerformanceCheckReco::process_event(), SimpleTrackingAnalysis::process_event(), QAG4SimulationVertex::process_event(), PHGenFitTrkFitter::process_event(), TpcPrototypeGenFitTrkFitter::ReFitTrack(), and PHGenFitTrkFitter::ReFitTrack().
virtual float SvtxVertex::get_z () const inline override virtual
Reimplemented from Vertex.
Reimplemented in SvtxVertex_v1, and SvtxVertex_v2.
Definition at line 45 of file SvtxVertex.h.
View newest version in sPHENIX GitHub at line 45 of file SvtxVertex.h
Referenced by PHG4TrackFastSimEval::fill_vertex_tree(), psTOFTimezeroEval::fillOutputNtuples(), SvtxEvaluatorHaiwang::fillOutputNtuples(), EventEvaluator::fillOutputNtuples(), BDiJetModule::FillVertexMap(), PHTrackClusterAssociator::getCluster(), IsolatedTrackAnalysis::getTracks(), KshortReconstruction::getVertex(), BDiJetModule::MakeGenFitTrack(), SVReco::MakeGenFitTrack(), PHActsGSF::makePerigee(), SVReco::MakeSvtxTrack(), PHGenFitTrkFitter::MakeSvtxTrack(), ActsPropagator::makeTrackParams(), KFParticle_Tools::makeVertex(), HFTrigger::makeVertex(), HFTriggerMVA::makeVertex(), ActsPropagator::makeVertexSurface(), psTOFTimezeroEval::printOutputInfo(), SvtxEvaluatorHaiwang::printOutputInfo(), TrkrNtuplizer::printOutputInfo(), SvtxEvaluator::printOutputInfo(), PHSiliconTruthTrackSeeding::Process(), PHHybridSeeding::Process(), SvtxSimPerformanceCheckReco::process_event(), SimpleTrackingAnalysis::process_event(), QAG4SimulationVertex::process_event(), GlobalVertexReco::process_event(), jetrtrack::process_event(), PHGenFitTrkFitter::process_event(), TpcPrototypeGenFitTrkFitter::ReFitTrack(), and PHGenFitTrkFitter::ReFitTrack().
void SvtxVertex::identify (std::ostream & os = std::cout) const inline override virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from PHObject.
Reimplemented in SvtxVertex_v1, and SvtxVertex_v2.
Definition at line 20 of file SvtxVertex.h.
View newest version in sPHENIX GitHub at line 20 of file SvtxVertex.h
References os.
Referenced by PHActsVertexFinder::fillVertexMap(), psTOFTimezeroEval::printInputInfo(), SvtxEvaluatorHaiwang::printInputInfo(), TrkrNtuplizer::printInputInfo(), and SvtxEvaluator::printInputInfo().
virtual void SvtxVertex::insert_track (unsigned int) inline override virtual
Reimplemented from Vertex.
Reimplemented in SvtxVertex_v1, and SvtxVertex_v2.
Definition at line 66 of file SvtxVertex.h.
View newest version in sPHENIX GitHub at line 66 of file SvtxVertex.h
Referenced by SVReco::GFRVVtxToSvtxVertex(), and Conversion::PHG4VtxPointToSvtxVertex().
int SvtxVertex::isValid () const inline override virtual
isValid returns non zero if object contains vailid data
Reimplemented from PHObject.
Reimplemented in SvtxVertex_v1, and SvtxVertex_v2.
Definition at line 25 of file SvtxVertex.h.
View newest version in sPHENIX GitHub at line 25 of file SvtxVertex.h
virtual void SvtxVertex::set_chisq (float) inline override virtual
Reimplemented from Vertex.
Reimplemented in SvtxVertex_v1, and SvtxVertex_v2.
Definition at line 49 of file SvtxVertex.h.
View newest version in sPHENIX GitHub at line 49 of file SvtxVertex.h
Referenced by SVReco::GFRVVtxToSvtxVertex(), Conversion::PHG4VtxPointToSvtxVertex(), and PHTruthVertexing::Process().
virtual void SvtxVertex::set_error (unsigned int , unsigned int , float) inline override virtual
Reimplemented from Vertex.
Reimplemented in SvtxVertex_v1, and SvtxVertex_v2.
Definition at line 58 of file SvtxVertex.h.
View newest version in sPHENIX GitHub at line 58 of file SvtxVertex.h
Referenced by SVReco::GFRVVtxToSvtxVertex(), Conversion::PHG4VtxPointToSvtxVertex(), and PHTruthVertexing::Process().
virtual void SvtxVertex::set_id (unsigned int) inline override virtual
Reimplemented from Vertex.
Reimplemented in SvtxVertex_v1, and SvtxVertex_v2.
Definition at line 31 of file SvtxVertex.h.
View newest version in sPHENIX GitHub at line 31 of file SvtxVertex.h
Referenced by PHTruthVertexing::Process().
virtual void SvtxVertex::set_ndof (unsigned int) inline override virtual
Reimplemented from Vertex.
Reimplemented in SvtxVertex_v1, and SvtxVertex_v2.
Definition at line 52 of file SvtxVertex.h.
View newest version in sPHENIX GitHub at line 52 of file SvtxVertex.h
Referenced by SVReco::GFRVVtxToSvtxVertex(), Conversion::PHG4VtxPointToSvtxVertex(), and PHTruthVertexing::Process().
virtual void SvtxVertex::set_position (unsigned int , float) inline override virtual
Reimplemented from Vertex.
Reimplemented in SvtxVertex_v1, and SvtxVertex_v2.
Definition at line 55 of file SvtxVertex.h.
View newest version in sPHENIX GitHub at line 55 of file SvtxVertex.h
Referenced by SVReco::GFRVVtxToSvtxVertex().
virtual void SvtxVertex::set_t (float) inline override virtual
Reimplemented from Vertex.
Reimplemented in SvtxVertex_v1, and SvtxVertex_v2.
Definition at line 37 of file SvtxVertex.h.
View newest version in sPHENIX GitHub at line 37 of file SvtxVertex.h
Referenced by PHTruthVertexing::Process(), and set_t0().
virtual void SvtxVertex::set_t0 (float t0) inline override virtual
Reimplemented from Vertex.
Reimplemented in SvtxVertex_v1.
Definition at line 34 of file SvtxVertex.h.
View newest version in sPHENIX GitHub at line 34 of file SvtxVertex.h
References set_t().
Referenced by Conversion::PHG4VtxPointToSvtxVertex().
virtual void SvtxVertex::set_x (float) inline override virtual
Reimplemented from Vertex.
Reimplemented in SvtxVertex_v1, and SvtxVertex_v2.
Definition at line 40 of file SvtxVertex.h.
View newest version in sPHENIX GitHub at line 40 of file SvtxVertex.h
Referenced by Conversion::PHG4VtxPointToSvtxVertex(), PHTruthVertexing::Process(), and PHActsVertexFitter::updateSvtxVertex().
virtual void SvtxVertex::set_y (float) inline override virtual
Reimplemented from Vertex.
Reimplemented in SvtxVertex_v1, and SvtxVertex_v2.
Definition at line 43 of file SvtxVertex.h.
View newest version in sPHENIX GitHub at line 43 of file SvtxVertex.h
Referenced by Conversion::PHG4VtxPointToSvtxVertex(), and PHTruthVertexing::Process().
virtual void SvtxVertex::set_z (float) inline override virtual
Reimplemented from Vertex.
Reimplemented in SvtxVertex_v1, and SvtxVertex_v2.
Definition at line 46 of file SvtxVertex.h.
View newest version in sPHENIX GitHub at line 46 of file SvtxVertex.h
Referenced by Conversion::PHG4VtxPointToSvtxVertex(), and PHTruthVertexing::Process().
virtual size_t SvtxVertex::size_tracks () const inline override virtual
Reimplemented from Vertex.
Reimplemented in SvtxVertex_v1, and SvtxVertex_v2.
Definition at line 65 of file SvtxVertex.h.
View newest version in sPHENIX GitHub at line 65 of file SvtxVertex.h
Referenced by PHG4TrackFastSimEval::fill_vertex_tree(), psTOFTimezeroEval::fillOutputNtuples(), SvtxEvaluatorHaiwang::fillOutputNtuples(), EventEvaluator::fillOutputNtuples(), BDiJetModule::FillVertexMap(), KFParticle_Tools::getTracksFromVertex(), SVReco::MakeGenFitTrack(), SvtxSimPerformanceCheckReco::process_event(), SimpleTrackingAnalysis::process_event(), QAG4SimulationVertex::process_event(), SecondaryVertexFinder::process_event(), TpcPrototypeGenFitTrkFitter::ReFitTrack(), and PHGenFitTrkFitter::ReFitTrack().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/globalvertex/SvtxVertex.h
coresoftware/blob/master/offline/packages/globalvertex/SvtxVertex.cc