Analysis Software: acts.examples.Sequencer.FpeMask Class Reference
acts.examples.Sequencer.FpeMask Class Reference
Public Member Functions
def fromFile
def fromYaml
def fromDict
Static Public Member Functions
def toDict
def parse_loc
Static Public Attributes
dictionary out {}
string loc_str "{mask.file}:"
Static Private Attributes
dictionary _fpe_types_to_enum {v.name: v for v in acts.FpeType.values}
Detailed Description
Definition at line 382 of file __init__.py.
View newest version in sPHENIX GitHub at line 382 of file __init__.py
Member Function Documentation
def acts.examples.Sequencer.FpeMask.fromDict (cls, d)
Definition at line 439 of file __init__.py.
View newest version in sPHENIX GitHub at line 439 of file __init__.py
def acts.examples.Sequencer.FpeMask.fromFile (cls, file)
Definition at line 384 of file __init__.py.
View newest version in sPHENIX GitHub at line 384 of file __init__.py
References print().
Referenced by physmon_ckf_tracking.run_ckf_tracking(), and physmon_vertexing.run_vertexing().
def acts.examples.Sequencer.FpeMask.fromYaml (cls, file)
Definition at line 396 of file __init__.py.
View newest version in sPHENIX GitHub at line 396 of file __init__.py
def acts.examples.Sequencer.FpeMask.parse_loc (loc) static
Definition at line 424 of file __init__.py.
View newest version in sPHENIX GitHub at line 424 of file __init__.py
def acts.examples.Sequencer.FpeMask.toDict (masks) static
Definition at line 408 of file __init__.py.
View newest version in sPHENIX GitHub at line 408 of file __init__.py
Member Data Documentation
dictionary acts.examples.Sequencer.FpeMask._fpe_types_to_enum {v.name: v for v in acts.FpeType.values} static private
Definition at line 404 of file __init__.py.
View newest version in sPHENIX GitHub at line 404 of file __init__.py
string acts.examples.Sequencer.FpeMask.loc_str "{mask.file}:" static
Definition at line 412 of file __init__.py.
View newest version in sPHENIX GitHub at line 412 of file __init__.py
dictionary acts.examples.Sequencer.FpeMask.out {} static
Definition at line 410 of file __init__.py.
View newest version in sPHENIX GitHub at line 410 of file __init__.py
The documentation for this class was generated from the following file:
acts/blob/sPHENIX/Examples/Python/python/acts/examples/__init__.py