Analysis Software: test_reader Namespace Reference
test_reader Namespace Reference
Functions
def test_root_particle_reader
def test_csv_particle_reader
def test_root_reader_interface
def test_root_material_track_reader
def test_csv_meas_reader
def test_csv_simhits_reader
def test_csv_clusters_reader
def generate_input_test_edm4hep_simhit_reader
def test_edm4hep_simhit_reader
def test_edm4hep_measurement_reader
def test_edm4hep_particle_reader
def test_edm4hep_tracks_reader
Function Documentation
def test_reader.generate_input_test_edm4hep_simhit_reader (input, output)
Definition at line 340 of file test_reader.py.
View newest version in sPHENIX GitHub at line 340 of file test_reader.py
def test_reader.test_csv_clusters_reader (tmp_path, fatras, conf_const, trk_geo, rng)
Definition at line 276 of file test_reader.py.
View newest version in sPHENIX GitHub at line 276 of file test_reader.py
References conftest.conf_const(), and str.
def test_reader.test_csv_meas_reader (tmp_path, fatras, trk_geo, conf_const)
Definition at line 169 of file test_reader.py.
View newest version in sPHENIX GitHub at line 169 of file test_reader.py
References conftest.conf_const(), and str.
def test_reader.test_csv_particle_reader (tmp_path, conf_const, ptcl_gun)
Definition at line 79 of file test_reader.py.
View newest version in sPHENIX GitHub at line 79 of file test_reader.py
References conftest.conf_const(), conftest.ptcl_gun(), and str.
def test_reader.test_csv_simhits_reader (tmp_path, fatras, conf_const)
Definition at line 237 of file test_reader.py.
View newest version in sPHENIX GitHub at line 237 of file test_reader.py
References conftest.conf_const(), and str.
def test_reader.test_edm4hep_measurement_reader (tmp_path, fatras, conf_const)
Definition at line 395 of file test_reader.py.
View newest version in sPHENIX GitHub at line 395 of file test_reader.py
References conftest.conf_const(), and str.
def test_reader.test_edm4hep_particle_reader (tmp_path, conf_const, ptcl_gun)
Definition at line 443 of file test_reader.py.
View newest version in sPHENIX GitHub at line 443 of file test_reader.py
References conftest.conf_const(), conftest.ptcl_gun(), and str.
def test_reader.test_edm4hep_simhit_reader (tmp_path)
Definition at line 359 of file test_reader.py.
View newest version in sPHENIX GitHub at line 359 of file test_reader.py
References acts.examples.odd.getOpenDataDetector(), common.getOpenDataDetectorDirectory(), and str.
def test_reader.test_edm4hep_tracks_reader (tmp_path)
Definition at line 492 of file test_reader.py.
View newest version in sPHENIX GitHub at line 492 of file test_reader.py
References truth_tracking_kalman.runTruthTrackingKalman(), and str.
def test_reader.test_root_material_track_reader (material_recording)
Definition at line 144 of file test_reader.py.
View newest version in sPHENIX GitHub at line 144 of file test_reader.py
References str.
def test_reader.test_root_particle_reader (tmp_path, conf_const, ptcl_gun)
Definition at line 36 of file test_reader.py.
View newest version in sPHENIX GitHub at line 36 of file test_reader.py
References conftest.conf_const(), conftest.ptcl_gun(), and str.
def test_reader.test_root_reader_interface (reader, conf_const, tmp_path)
Definition at line 128 of file test_reader.py.
View newest version in sPHENIX GitHub at line 128 of file test_reader.py
References conftest.conf_const(), and str.