Analysis Software: Acts::WeightedComponentReducerLoop Struct Reference
Acts::WeightedComponentReducerLoop Struct Reference
Reducer struct for the Loop MultiEigenStepper which reduces the multicomponent state to simply by summing the weighted values.
#include <acts/blob/sPHENIX/Core/include/Acts/Propagator/MultiEigenStepperLoop.hpp>
Static Public Member Functions
template<typename component_range_t >
static Vector3 toVector3 (const component_range_t &comps, const FreeIndices i)
template<typename stepper_state_t >
static Vector3 position (const stepper_state_t &s)
template<typename stepper_state_t >
static Vector3 direction (const stepper_state_t &s)
template<typename stepper_state_t >
static ActsScalar qOverP (const stepper_state_t &s)
template<typename stepper_state_t >
static ActsScalar absoluteMomentum (const stepper_state_t &s)
template<typename stepper_state_t >
static Vector3 momentum (const stepper_state_t &s)
template<typename stepper_state_t >
static ActsScalar charge (const stepper_state_t &s)
template<typename stepper_state_t >
static ActsScalar time (const stepper_state_t &s)
template<typename stepper_state_t >
static FreeVector pars (const stepper_state_t &s)
template<typename stepper_state_t >
static FreeVector cov (const stepper_state_t &s)
Detailed Description
Reducer struct for the Loop MultiEigenStepper which reduces the multicomponent state to simply by summing the weighted values.
Definition at line 50 of file MultiEigenStepperLoop.hpp.
View newest version in sPHENIX GitHub at line 50 of file MultiEigenStepperLoop.hpp
Member Function Documentation
template<typename stepper_state_t > static ActsScalar Acts::WeightedComponentReducerLoop::absoluteMomentum (const stepper_state_t & s) inline static
Definition at line 83 of file MultiEigenStepperLoop.hpp.
View newest version in sPHENIX GitHub at line 83 of file MultiEigenStepperLoop.hpp
References root_event_diff_np::cmp(), Acts::eFreeQOverP, physmon_simulation::s, and sum().
template<typename stepper_state_t > static ActsScalar Acts::WeightedComponentReducerLoop::charge (const stepper_state_t & s) inline static
Definition at line 105 of file MultiEigenStepperLoop.hpp.
View newest version in sPHENIX GitHub at line 105 of file MultiEigenStepperLoop.hpp
References root_event_diff_np::cmp(), Acts::eFreeQOverP, physmon_simulation::s, and sum().
template<typename stepper_state_t > static FreeVector Acts::WeightedComponentReducerLoop::cov (const stepper_state_t & s) inline static
Definition at line 133 of file MultiEigenStepperLoop.hpp.
View newest version in sPHENIX GitHub at line 133 of file MultiEigenStepperLoop.hpp
References root_event_diff_np::cmp(), and sum().
template<typename stepper_state_t > static Vector3 Acts::WeightedComponentReducerLoop::direction (const stepper_state_t & s) inline static
Definition at line 67 of file MultiEigenStepperLoop.hpp.
View newest version in sPHENIX GitHub at line 67 of file MultiEigenStepperLoop.hpp
References Acts::eFreeDir0.
template<typename stepper_state_t > static Vector3 Acts::WeightedComponentReducerLoop::momentum (const stepper_state_t & s) inline static
Definition at line 93 of file MultiEigenStepperLoop.hpp.
View newest version in sPHENIX GitHub at line 93 of file MultiEigenStepperLoop.hpp
References root_event_diff_np::cmp(), Acts::eFreeDir0, Acts::eFreeQOverP, physmon_simulation::s, and sum().
template<typename stepper_state_t > static FreeVector Acts::WeightedComponentReducerLoop::pars (const stepper_state_t & s) inline static
Definition at line 124 of file MultiEigenStepperLoop.hpp.
View newest version in sPHENIX GitHub at line 124 of file MultiEigenStepperLoop.hpp
References root_event_diff_np::cmp(), and sum().
template<typename stepper_state_t > static Vector3 Acts::WeightedComponentReducerLoop::position (const stepper_state_t & s) inline static
Definition at line 62 of file MultiEigenStepperLoop.hpp.
View newest version in sPHENIX GitHub at line 62 of file MultiEigenStepperLoop.hpp
References Acts::eFreePos0.
template<typename stepper_state_t > static ActsScalar Acts::WeightedComponentReducerLoop::qOverP (const stepper_state_t & s) inline static
Definition at line 74 of file MultiEigenStepperLoop.hpp.
View newest version in sPHENIX GitHub at line 74 of file MultiEigenStepperLoop.hpp
References root_event_diff_np::cmp(), Acts::eFreeQOverP, and sum().
template<typename stepper_state_t > static ActsScalar Acts::WeightedComponentReducerLoop::time (const stepper_state_t & s) inline static
Definition at line 115 of file MultiEigenStepperLoop.hpp.
View newest version in sPHENIX GitHub at line 115 of file MultiEigenStepperLoop.hpp
References root_event_diff_np::cmp(), Acts::eFreeTime, and sum().
template<typename component_range_t > static Vector3 Acts::WeightedComponentReducerLoop::toVector3 (const component_range_t & comps, const FreeIndices i) inline static
Definition at line 52 of file MultiEigenStepperLoop.hpp.
View newest version in sPHENIX GitHub at line 52 of file MultiEigenStepperLoop.hpp
References root_event_diff_np::cmp(), i, and sum().
The documentation for this struct was generated from the following file:
acts/blob/sPHENIX/Core/include/Acts/Propagator/MultiEigenStepperLoop.hpp