Analysis Software: Jetscape::JetScapeXML Class Reference
Jetscape::JetScapeXML Class Reference
#include <JETSCAPE/blob/main/src/framework/JetScapeXML.h>
Public Member Functions
tinyxml2::XMLElement * GetXMLRootMaster ()
tinyxml2::XMLDocument & GetXMLDocumentMaster ()
tinyxml2::XMLElement * GetXMLElementMaster (std::initializer_list< const char * > &path)
void SetXMLMasterFileName (string m_name)
std::string GetXMLMasterFileName ()
bool IsMasterFileOpen ()
void OpenXMLMasterFile ()
void OpenXMLMasterFile (string m_name)
tinyxml2::XMLElement * GetXMLRootMain () const
tinyxml2::XMLDocument & GetXMLDocumentMain ()
tinyxml2::XMLElement * GetXMLElementMain (std::initializer_list< const char * > &path)
void SetXMLMainFileName (string m_name)
std::string GetXMLMainFileName () const
bool IsMainFileOpen () const
void OpenXMLMainFile ()
void OpenXMLMainFile (string m_name)
tinyxml2::XMLElement * GetXMLRootUser ()
tinyxml2::XMLDocument & GetXMLDocumentUser ()
tinyxml2::XMLElement * GetXMLElementUser (std::initializer_list< const char * > &path)
void SetXMLUserFileName (string m_name)
std::string GetXMLUserFileName ()
bool IsUserFileOpen ()
void OpenXMLUserFile ()
void OpenXMLUserFile (string m_name)
tinyxml2::XMLElement * GetElement (std::initializer_list< const char * > path, bool isRequired=true)
std::string GetElementText (std::initializer_list< const char * > path, bool isRequired=true)
int GetElementInt (std::initializer_list< const char * > path, bool isRequired=true)
double GetElementDouble (std::initializer_list< const char * > path, bool isRequired=true)
Static Public Member Functions
static JetScapeXML * Instance ()
Private Member Functions
JetScapeXML ()
JetScapeXML (JetScapeXML const &)
Private Attributes
tinyxml2::XMLElement * xml_root_main
tinyxml2::XMLDocument xml_doc_main
std::string xml_main_file_name
bool xml_main_file_open
tinyxml2::XMLElement * xml_root_user
tinyxml2::XMLDocument xml_doc_user
std::string xml_user_file_name
bool xml_user_file_open
Static Private Attributes
static JetScapeXML * m_pInstance = NULL
Detailed Description
Definition at line 39 of file JetScapeXML.h.
View newest version in sPHENIX GitHub at line 39 of file JetScapeXML.h
Constructor & Destructor Documentation
Jetscape::JetScapeXML::JetScapeXML () inline private
Definition at line 99 of file JetScapeXML.h.
View newest version in sPHENIX GitHub at line 99 of file JetScapeXML.h
References xml_main_file_name, xml_main_file_open, xml_user_file_name, and xml_user_file_open.
Jetscape::JetScapeXML::JetScapeXML (JetScapeXML const &) inline private
Definition at line 105 of file JetScapeXML.h.
View newest version in sPHENIX GitHub at line 105 of file JetScapeXML.h
Member Function Documentation
tinyxml2::XMLElement * JetScapeXML::GetElement (std::initializer_list< const char * > path, bool isRequired = true)
Definition at line 216 of file JetScapeXML.cc.
View newest version in sPHENIX GitHub at line 216 of file JetScapeXML.cc
References JSWARN.
Referenced by Jetscape::JetScapeModuleBase::GetXMLElement().
double JetScapeXML::GetElementDouble (std::initializer_list< const char * > path, bool isRequired = true)
Definition at line 269 of file JetScapeXML.cc.
View newest version in sPHENIX GitHub at line 269 of file JetScapeXML.cc
References fixGDML::element, tinyxml2::XMLElement::QueryDoubleText(), and value.
Referenced by Jetscape::JetScapeModuleBase::GetXMLElementDouble(), and Jetscape::CausalLiquefier::Init().
int JetScapeXML::GetElementInt (std::initializer_list< const char * > path, bool isRequired = true)
Definition at line 254 of file JetScapeXML.cc.
View newest version in sPHENIX GitHub at line 254 of file JetScapeXML.cc
References fixGDML::element, tinyxml2::XMLElement::QueryIntText(), and value.
Referenced by Jetscape::JetScapeModuleBase::GetXMLElementInt(), and Jetscape::JetScapeWriterFinalStateStream< T >::WriteEvent().
std::string JetScapeXML::GetElementText (std::initializer_list< const char * > path, bool isRequired = true)
Definition at line 241 of file JetScapeXML.cc.
View newest version in sPHENIX GitHub at line 241 of file JetScapeXML.cc
References fixGDML::element, and tinyxml2::XMLElement::GetText().
Referenced by Jetscape::JetScapeModuleBase::GetXMLElementText().
tinyxml2::XMLDocument& Jetscape::JetScapeXML::GetXMLDocumentMain () inline
Definition at line 62 of file JetScapeXML.h.
View newest version in sPHENIX GitHub at line 62 of file JetScapeXML.h
References xml_doc_main.
Referenced by Jetscape::JetScapeWriterStream< T >::WriteInitFileXMLMain().
tinyxml2::XMLDocument& Jetscape::JetScapeXML::GetXMLDocumentMaster () inline
Definition at line 48 of file JetScapeXML.h.
View newest version in sPHENIX GitHub at line 48 of file JetScapeXML.h
References xml_doc_main.
tinyxml2::XMLDocument& Jetscape::JetScapeXML::GetXMLDocumentUser () inline
Definition at line 76 of file JetScapeXML.h.
View newest version in sPHENIX GitHub at line 76 of file JetScapeXML.h
References xml_doc_user.
Referenced by Jetscape::JetScapeWriterStream< T >::WriteInitFileXMLUser().
tinyxml2::XMLElement * JetScapeXML::GetXMLElementMain (std::initializer_list< const char * > & path)
Definition at line 138 of file JetScapeXML.cc.
View newest version in sPHENIX GitHub at line 138 of file JetScapeXML.cc
References tinyxml2::XMLNode::FirstChildElement(), tinyxml2::XMLElement::Name(), path, and VERBOSE.
tinyxml2::XMLElement * JetScapeXML::GetXMLElementMaster (std::initializer_list< const char * > & path)
Definition at line 130 of file JetScapeXML.cc.
View newest version in sPHENIX GitHub at line 130 of file JetScapeXML.cc
References JSWARN.
tinyxml2::XMLElement * JetScapeXML::GetXMLElementUser (std::initializer_list< const char * > & path)
Definition at line 177 of file JetScapeXML.cc.
View newest version in sPHENIX GitHub at line 177 of file JetScapeXML.cc
References tinyxml2::XMLNode::FirstChildElement(), tinyxml2::XMLElement::Name(), path, and VERBOSE.
std::string Jetscape::JetScapeXML::GetXMLMainFileName () const inline
Definition at line 67 of file JetScapeXML.h.
View newest version in sPHENIX GitHub at line 67 of file JetScapeXML.h
References xml_main_file_name.
Referenced by Jetscape::JetScapeWriterStream< T >::WriteInitFileXMLMain().
std::string Jetscape::JetScapeXML::GetXMLMasterFileName () inline
Definition at line 53 of file JetScapeXML.h.
View newest version in sPHENIX GitHub at line 53 of file JetScapeXML.h
References xml_main_file_name.
tinyxml2::XMLElement* Jetscape::JetScapeXML::GetXMLRootMain () const inline
Definition at line 61 of file JetScapeXML.h.
View newest version in sPHENIX GitHub at line 61 of file JetScapeXML.h
References xml_root_main.
Referenced by Jetscape::JetScape::CompareElementsFromXML().
tinyxml2::XMLElement* Jetscape::JetScapeXML::GetXMLRootMaster () inline
Definition at line 47 of file JetScapeXML.h.
View newest version in sPHENIX GitHub at line 47 of file JetScapeXML.h
References xml_root_main.
tinyxml2::XMLElement* Jetscape::JetScapeXML::GetXMLRootUser () inline
Definition at line 75 of file JetScapeXML.h.
View newest version in sPHENIX GitHub at line 75 of file JetScapeXML.h
References xml_root_user.
Referenced by Jetscape::JetScape::CompareElementsFromXML(), Jetscape::JetScape::DetermineTaskListFromXML(), Jetscape::JetScape::DetermineWritersFromXML(), and HybridHadronization::Init().
std::string Jetscape::JetScapeXML::GetXMLUserFileName () inline
Definition at line 81 of file JetScapeXML.h.
View newest version in sPHENIX GitHub at line 81 of file JetScapeXML.h
References xml_user_file_name.
Referenced by Jetscape::JetScapeWriterStream< T >::WriteInitFileXMLUser().
JetScapeXML * JetScapeXML::Instance () static
Definition at line 26 of file JetScapeXML.cc.
View newest version in sPHENIX GitHub at line 26 of file JetScapeXML.cc
References JSINFO.
Referenced by Jetscape::JetScape::CompareElementsFromXML(), Jetscape::JetScape::DetermineTaskListFromXML(), Jetscape::JetScape::DetermineWritersFromXML(), Jetscape::JetScapeModuleBase::GetXMLElement(), Jetscape::JetScapeModuleBase::GetXMLElementDouble(), Jetscape::JetScapeModuleBase::GetXMLElementInt(), Jetscape::JetScapeModuleBase::GetXMLElementText(), HybridHadronization::Init(), Jetscape::JetScape::Init(), Jetscape::JetScapeModuleBase::Init(), Jetscape::CausalLiquefier::Init(), Jetscape::JetScapeWriterFinalStateStream< T >::WriteEvent(), Jetscape::JetScapeWriterStream< T >::WriteInitFileXMLMain(), and Jetscape::JetScapeWriterStream< T >::WriteInitFileXMLUser().
bool Jetscape::JetScapeXML::IsMainFileOpen () const inline
Definition at line 68 of file JetScapeXML.h.
View newest version in sPHENIX GitHub at line 68 of file JetScapeXML.h
References xml_main_file_open.
bool Jetscape::JetScapeXML::IsMasterFileOpen () inline
Definition at line 54 of file JetScapeXML.h.
View newest version in sPHENIX GitHub at line 54 of file JetScapeXML.h
References xml_main_file_open.
bool Jetscape::JetScapeXML::IsUserFileOpen () inline
Definition at line 82 of file JetScapeXML.h.
View newest version in sPHENIX GitHub at line 82 of file JetScapeXML.h
References xml_user_file_open.
void JetScapeXML::OpenXMLMainFile ()
Definition at line 41 of file JetScapeXML.cc.
View newest version in sPHENIX GitHub at line 41 of file JetScapeXML.cc
References JSINFO, JSWARN, and VERBOSE.
Referenced by Jetscape::JetScape::Init().
void JetScapeXML::OpenXMLMainFile (string m_name)
Definition at line 90 of file JetScapeXML.cc.
View newest version in sPHENIX GitHub at line 90 of file JetScapeXML.cc
void JetScapeXML::OpenXMLMasterFile ()
Definition at line 36 of file JetScapeXML.cc.
View newest version in sPHENIX GitHub at line 36 of file JetScapeXML.cc
References JSWARN.
void JetScapeXML::OpenXMLMasterFile (string m_name)
Definition at line 84 of file JetScapeXML.cc.
View newest version in sPHENIX GitHub at line 84 of file JetScapeXML.cc
References JSWARN.
void JetScapeXML::OpenXMLUserFile ()
Definition at line 96 of file JetScapeXML.cc.
View newest version in sPHENIX GitHub at line 96 of file JetScapeXML.cc
References JSINFO, JSWARN, and VERBOSE.
Referenced by Jetscape::JetScape::Init().
void JetScapeXML::OpenXMLUserFile (string m_name)
Definition at line 123 of file JetScapeXML.cc.
View newest version in sPHENIX GitHub at line 123 of file JetScapeXML.cc
void Jetscape::JetScapeXML::SetXMLMainFileName (string m_name) inline
Definition at line 66 of file JetScapeXML.h.
View newest version in sPHENIX GitHub at line 66 of file JetScapeXML.h
References m_name(), and xml_main_file_name.
void Jetscape::JetScapeXML::SetXMLMasterFileName (string m_name) inline
Definition at line 52 of file JetScapeXML.h.
View newest version in sPHENIX GitHub at line 52 of file JetScapeXML.h
References m_name(), and xml_main_file_name.
void Jetscape::JetScapeXML::SetXMLUserFileName (string m_name) inline
Definition at line 80 of file JetScapeXML.h.
View newest version in sPHENIX GitHub at line 80 of file JetScapeXML.h
References m_name(), and xml_user_file_name.
Member Data Documentation
JetScapeXML * JetScapeXML::m_pInstance = NULL static private
Definition at line 105 of file JetScapeXML.h.
View newest version in sPHENIX GitHub at line 105 of file JetScapeXML.h
tinyxml2::XMLDocument Jetscape::JetScapeXML::xml_doc_main private
Definition at line 112 of file JetScapeXML.h.
View newest version in sPHENIX GitHub at line 112 of file JetScapeXML.h
Referenced by GetXMLDocumentMain(), and GetXMLDocumentMaster().
tinyxml2::XMLDocument Jetscape::JetScapeXML::xml_doc_user private
Definition at line 121 of file JetScapeXML.h.
View newest version in sPHENIX GitHub at line 121 of file JetScapeXML.h
Referenced by GetXMLDocumentUser().
std::string Jetscape::JetScapeXML::xml_main_file_name private
Definition at line 114 of file JetScapeXML.h.
View newest version in sPHENIX GitHub at line 114 of file JetScapeXML.h
Referenced by GetXMLMainFileName(), GetXMLMasterFileName(), JetScapeXML(), SetXMLMainFileName(), and SetXMLMasterFileName().
bool Jetscape::JetScapeXML::xml_main_file_open private
Definition at line 115 of file JetScapeXML.h.
View newest version in sPHENIX GitHub at line 115 of file JetScapeXML.h
Referenced by IsMainFileOpen(), IsMasterFileOpen(), and JetScapeXML().
tinyxml2::XMLElement* Jetscape::JetScapeXML::xml_root_main private
Definition at line 111 of file JetScapeXML.h.
View newest version in sPHENIX GitHub at line 111 of file JetScapeXML.h
Referenced by GetXMLRootMain(), and GetXMLRootMaster().
tinyxml2::XMLElement* Jetscape::JetScapeXML::xml_root_user private
Definition at line 120 of file JetScapeXML.h.
View newest version in sPHENIX GitHub at line 120 of file JetScapeXML.h
Referenced by GetXMLRootUser().
std::string Jetscape::JetScapeXML::xml_user_file_name private
Definition at line 123 of file JetScapeXML.h.
View newest version in sPHENIX GitHub at line 123 of file JetScapeXML.h
Referenced by GetXMLUserFileName(), JetScapeXML(), and SetXMLUserFileName().
bool Jetscape::JetScapeXML::xml_user_file_open private
Definition at line 124 of file JetScapeXML.h.
View newest version in sPHENIX GitHub at line 124 of file JetScapeXML.h
Referenced by IsUserFileOpen(), and JetScapeXML().
The documentation for this class was generated from the following files:
JETSCAPE/blob/main/src/framework/JetScapeXML.h
JETSCAPE/blob/main/src/framework/JetScapeXML.cc