Analysis Software: ActsExamples::Options Namespace Reference
ActsExamples::Options Namespace Reference
Namespaces
namespace detail
Classes
struct Interval
class Reals
struct VariableReals
class Integers
struct VariableIntegers
Typedefs
using Description = ::boost::program_options::options_description
using Variables = ::boost::program_options::variables_map
Functions
template<typename aopt_t >
void addMaterialMappingOptions (aopt_t &opt)
Material mapping options, specially added.
void addPropagationOptions (boost::program_options::options_description &opt)
PropagationAlgorithm options.
ActsExamples::PropagationAlgorithm::Config readPropagationConfig (const boost::program_options::variables_map &vm)
void from_json (const nlohmann::json &j, ActsExamples::Options::Interval &interval)
Read config for options interval.
void to_json (nlohmann::json &j, const ActsExamples::Options::Interval &interval)
Write config for options interval.
std::istream & operator>> (std::istream &is, Interval &interval)
std::ostream & operator<< (std::ostream &os, const Interval &interval)
Print an interval as lower:upper.
template<size_t kSize>
std::istream & operator>> (std::istream &is, Reals< kSize > &values)
std::istream & operator>> (std::istream &is, VariableReals &values)
template<size_t kSize>
std::ostream & operator<< (std::ostream &os, const Reals< kSize > &values)
Print a fixed number of doubles as x:y:z.
std::ostream & operator<< (std::ostream &os, const VariableReals &values)
Print a variable number of doubles as x:y:z:....
template<size_t kSize>
std::istream & operator>> (std::istream &is, Integers< kSize > &values)
std::istream & operator>> (std::istream &is, VariableIntegers &values)
template<size_t kSize>
std::ostream & operator<< (std::ostream &os, const Integers< kSize > &values)
Print a fixed number of integers as x:y:z.
std::ostream & operator<< (std::ostream &os, const VariableIntegers &values)
Print a variable number of integers as x:y:z:....
void addObjWriterOptions (boost::program_options::options_description &opt)
ActsExamples::ObjTrackingGeometryWriter::Config readObjTrackingGeometryWriterConfig (const boost::program_options::variables_map &vm)
read the evgen options and return a Config file
boost::program_options::options_description makeDefaultOptions (const std::string &caption=std::string())
void addSequencerOptions (boost::program_options::options_description &opt)
Add sequencer options, e.g. number of events.
void addRandomNumbersOptions (boost::program_options::options_description &opt)
Add random number options such as the global seed.
void addGeometryOptions (boost::program_options::options_description &opt)
Add common geometry-related options.
void addMaterialOptions (boost::program_options::options_description &opt)
Add common material-related options.
void addInputOptions (boost::program_options::options_description &opt)
Add common input-related options.
void addOutputOptions (boost::program_options::options_description &opt, OutputFormat format)
Add common output-related options.
boost::program_options::variables_map parse (const boost::program_options::options_description &opt, int argc, char *argv[])
Acts::Logging::Level readLogLevel (const boost::program_options::variables_map &vm)
Read the log level.
Sequencer::Config readSequencerConfig (const boost::program_options::variables_map &vm)
Read the sequencer config.
RandomNumbers::Config readRandomNumbersConfig (const boost::program_options::variables_map &vm)
ActsExamples::CsvParticleReader::Config readCsvParticleReaderConfig (const Variables &vm)
Read the CSV particle reader config.
ActsExamples::CsvSimHitReader::Config readCsvSimHitReaderConfig (const Variables &vm)
Read the CSV sim hit reader config.
ActsExamples::CsvSpacePointReader::Config readCsvSpacePointReaderConfig (const Variables &vm)
Read the CSV space point reader config.
ActsExamples::CsvMeasurementReader::Config readCsvMeasurementReaderConfig (const Variables &vm)
Read the CSV measurement reader config.
ActsExamples::CsvPlanarClusterReader::Config readCsvPlanarClusterReaderConfig (const Variables &vm)
Read the CSV particle reader config.
void addCsvWriterOptions (Description &desc)
ActsExamples::CsvParticleWriter::Config readCsvParticleWriterConfig (const Variables &vm)
Read the CSV particle writer options.
ActsExamples::CsvSimHitWriter::Config readCsvSimHitWriterConfig (const Variables &vm)
Read the CSV sim hit writer options.
ActsExamples::CsvPlanarClusterWriter::Config readCsvPlanarClusterWriterConfig (const Variables &vm)
Read the CSV planar cluster writer options.
ActsExamples::CsvMeasurementWriter::Config readCsvMeasurementWriterConfig (const Variables &vm)
Read the CSV measurement writer options.
ActsExamples::CsvTrackingGeometryWriter::Config readCsvTrackingGeometryWriterConfig (const Variables &vm)
Read the CSV tracking geometry writer config.
void addDigitizationOptions (Description &desc)
template<typename options_t >
void addEmptyGeometryOptions (options_t &opt)
template<typename options_t >
void addGenericGeometryOptions (options_t &opt)
void addJsonWriterOptions (Description &desc)
ActsExamples::JsonSurfacesWriter::Config readJsonSurfacesWriterConfig (const Variables &vm)
Read the Json tracking geometry writer config.
void addMagneticFieldOptions (Description &desc)
Add magnetic field options with a bf- prefix.
void setupMagneticFieldServices (const Variables &vars, Sequencer &seq)
Setup any additional services required for the magnetic field.
std::shared_ptr
< Acts::MagneticFieldProvider > readMagneticField (const Variables &vars)
Read and create the magnetic field from the given user variables.
void addNuclearInteractionOptions (Description &desc)
ActsFatras::detail::MultiParticleNuclearInteractionParametrisation readParametrisations (const std::string &fileName)
Reads the parametrisation and provides the parametrisation.
std::string readNuclearInteractionConfig (const boost::program_options::variables_map &variables)
template<typename simulator_t >
void setNuclearInteractionParametrisations (const std::string &nuclearInteractionParametrisation, simulator_t &simulator)
void addParticleGunOptions (Description &desc)
Add options for a particle-gun-like event generator.
EventGenerator::Config readParticleGunOptions (const Variables &vars)
Create the event generator config from particle-gun options.
void addParticleSelectorOptions (Options::Description &desc)
ActsExamples::ParticleSelector::Config readParticleSelectorConfig (const Options::Variables &vars)
void addParticleSmearingOptions (Description &desc)
Add particle smearing options with a smearing- prefix.
ParticleSmearing::Config readParticleSmearingOptions (const Options::Variables &vars)
Read options.
void addSpacePointMakerOptions (Description &desc)
SpacePointMaker::Config readSpacePointMakerConfig (const Variables &variables)
void addTrackFindingOptions (Description &desc)
TrackFindingAlgorithm::Config readTrackFindingConfig (const Variables &variables)
void addFittingOptions (boost::program_options::options_description &opt)
Add common fitted related options.
void addTruthSeedSelectorOptions (Options::Description &desc)
ActsExamples::TruthSeedSelector::Config readTruthSeedSelectorConfig (const Options::Variables &vars)
void addVertexingOptions (Description &desc)
template<typename aopt_t >
void addDD4hepOptions (aopt_t &opt)
the particle gun options, the are prefixes with gp
template<typename amap_t >
ActsExamples::DD4hep::DD4hepGeometryService::Config readDD4hepConfig (const amap_t &vm)
read the particle gun options and return a Config file
void addFatrasOptions (Options::Description &desc)
ActsExamples::FatrasSimulation::Config readFatrasConfig (const Options::Variables &vars)
void addGeant4Options (Description &desc)
Geant4 specific options.
void addPythia8Options (Description &desc)
Add options for a Pythia8-based event-generator.
EventGenerator::Config readPythia8Options (const Variables &vars, Acts::Logging::Level lvl)
void addHepMC3WriterOptions (Description &desc)
HepMC3AsciiWriter::Config readHepMC3WriterOptions (const Variables &variables)
void addHepMC3ReaderOptions (Description &desc)
HepMC3AsciiReader::Config readHepMC3ReaderOptions (const Variables &variables)
Typedef Documentation
using ActsExamples::Options::Description = typedef ::boost::program_options::options_description
Definition at line 20 of file OptionsFwd.hpp.
View newest version in sPHENIX GitHub at line 20 of file OptionsFwd.hpp
using ActsExamples::Options::Variables = typedef ::boost::program_options::variables_map
Definition at line 21 of file OptionsFwd.hpp.
View newest version in sPHENIX GitHub at line 21 of file OptionsFwd.hpp
Function Documentation
void ActsExamples::Options::addCsvWriterOptions (Description & desc)
Definition at line 16 of file CsvOptionsWriter.cpp.
View newest version in sPHENIX GitHub at line 16 of file CsvOptionsWriter.cpp
Referenced by processGeometry(), runDigitizationExample(), and runRecCKFTracks().
template<typename aopt_t > void ActsExamples::Options::addDD4hepOptions (aopt_t & opt)
the particle gun options, the are prefixes with gp
Definition at line 28 of file DD4hepDetectorOptions.hpp.
View newest version in sPHENIX GitHub at line 28 of file DD4hepDetectorOptions.hpp
References Acts::UnitConstants::e.
Referenced by ActsExamples::DD4hepDetectorWithOptions::addOptions(), and main().
void ActsExamples::Options::addDigitizationOptions (Description & desc)
Add Digitization options.
Parameters
desc The options description to add options to
Definition at line 23 of file DigitizationOptions.cpp.
View newest version in sPHENIX GitHub at line 23 of file DigitizationOptions.cpp
References value.
Referenced by runDetectorAlignment(), runDigitizationConfigExample(), runDigitizationExample(), runHoughExample(), runRecCKFTracks(), runRecTruthTracks(), and runSeedingExample().
template<typename options_t > void ActsExamples::Options::addEmptyGeometryOptions (options_t & opt)
The empty geometry options, the are prefixes with geo-generic
Template Parameters
options_t Type of the options object (bound to boost API)
Parameters
opt The provided object, where root specific options are attached
Definition at line 27 of file EmptyDetectorOptions.hpp.
View newest version in sPHENIX GitHub at line 27 of file EmptyDetectorOptions.hpp
Referenced by EmptyDetector::addOptions().
void ActsExamples::Options::addFatrasOptions (Options::Description & desc)
Definition at line 22 of file FatrasOptions.cpp.
View newest version in sPHENIX GitHub at line 22 of file FatrasOptions.cpp
References value.
Referenced by runFatras().
void ActsExamples::Options::addFittingOptions (boost::program_options::options_description & opt)
Add common fitted related options.
Definition at line 15 of file TrackFittingOptions.cpp.
View newest version in sPHENIX GitHub at line 15 of file TrackFittingOptions.cpp
Referenced by runDetectorAlignment(), runRecCKFTracks(), and runRecTruthTracks().
void ActsExamples::Options::addGeant4Options (Description & desc)
Geant4 specific options.
Parameters
desc The option descrion forward
Definition at line 17 of file Geant4Options.cpp.
View newest version in sPHENIX GitHub at line 17 of file Geant4Options.cpp
References value.
Referenced by main().
template<typename options_t > void ActsExamples::Options::addGenericGeometryOptions (options_t & opt)
The generic geometry options, the are prefixes with geo-generic
Template Parameters
options_t Type of the options object (bound to boost API)
Parameters
opt The provided object, where root specific options are attached
Definition at line 30 of file GenericDetectorOptions.hpp.
View newest version in sPHENIX GitHub at line 30 of file GenericDetectorOptions.hpp
Referenced by ActsExamples::GenericDetectorWithOptions::addOptions(), and ActsExamples::AlignedDetectorWithOptions::addOptions().
void ActsExamples::Options::addGeometryOptions (boost::program_options::options_description & opt)
Add common geometry-related options.
Definition at line 66 of file CommonOptions.cpp.
View newest version in sPHENIX GitHub at line 66 of file CommonOptions.cpp
Referenced by main(), MakeActsGeometry::makeGeometry(), materialValidationExample(), processGeometry(), propagationExample(), runDetectorAlignment(), runDigitizationConfigExample(), runDigitizationExample(), runFatras(), runHoughExample(), runMaterialMapping(), runMeasurementsToSP(), runRecCKFTracks(), runRecTruthTracks(), and runSeedingExample().
void ActsExamples::Options::addHepMC3ReaderOptions (Description & desc)
Add HepMC3 specific reader options.
Parameters
desc The option description forward
Definition at line 37 of file HepMC3Options.cpp.
View newest version in sPHENIX GitHub at line 37 of file HepMC3Options.cpp
References value.
Referenced by main().
void ActsExamples::Options::addHepMC3WriterOptions (Description & desc)
Add HepMC3 specific writer options.
Parameters
desc The option description forward
Definition at line 17 of file HepMC3Options.cpp.
View newest version in sPHENIX GitHub at line 17 of file HepMC3Options.cpp
References value.
Referenced by main().
void ActsExamples::Options::addInputOptions (boost::program_options::options_description & opt)
Add common input-related options.
Definition at line 141 of file CommonOptions.cpp.
View newest version in sPHENIX GitHub at line 141 of file CommonOptions.cpp
References value.
Referenced by main(), runDetectorAlignment(), runDigitizationExample(), runHoughExample(), runMaterialMapping(), runMeasurementsToSP(), runRecCKFTracks(), runRecTruthTracks(), and runSeedingExample().
void ActsExamples::Options::addJsonWriterOptions (Description & desc)
Definition at line 13 of file JsonOptionsWriter.cpp.
View newest version in sPHENIX GitHub at line 13 of file JsonOptionsWriter.cpp
Referenced by processGeometry().
void ActsExamples::Options::addMagneticFieldOptions (Description & desc)
Add magnetic field options with a bf- prefix.
Definition at line 29 of file MagneticFieldOptions.cpp.
View newest version in sPHENIX GitHub at line 29 of file MagneticFieldOptions.cpp
References value.
Referenced by main(), MakeActsGeometry::makeGeometry(), materialValidationExample(), propagationExample(), runDetectorAlignment(), runDigitizationExample(), runFatras(), runHoughExample(), runMeasurementsToSP(), runRecCKFTracks(), runRecTruthTracks(), and runSeedingExample().
template<typename aopt_t > void ActsExamples::Options::addMaterialMappingOptions (aopt_t & opt)
Material mapping options, specially added.
Template Parameters
aopt_t Type of the options object (API bound to boost)
Parameters
[in] opt_t The options object where the specific digitization options are attached to
Definition at line 31 of file MaterialMappingOptions.hpp.
View newest version in sPHENIX GitHub at line 31 of file MaterialMappingOptions.hpp
Referenced by runMaterialMapping().
void ActsExamples::Options::addMaterialOptions (boost::program_options::options_description & opt)
Add common material-related options.
Definition at line 78 of file CommonOptions.cpp.
View newest version in sPHENIX GitHub at line 78 of file CommonOptions.cpp
Referenced by main(), MakeActsGeometry::makeGeometry(), materialValidationExample(), processGeometry(), propagationExample(), runDetectorAlignment(), runDigitizationConfigExample(), runDigitizationExample(), runFatras(), runHoughExample(), runMaterialMapping(), runMeasurementsToSP(), runRecCKFTracks(), runRecTruthTracks(), and runSeedingExample().
void ActsExamples::Options::addNuclearInteractionOptions (Description & desc)
Add Fatras options.
Parameters
desc The options description to add options to
Definition at line 122 of file NuclearInteractionOptions.cpp.
View newest version in sPHENIX GitHub at line 122 of file NuclearInteractionOptions.cpp
References value.
void ActsExamples::Options::addObjWriterOptions (boost::program_options::options_description & opt)
Common obj writing options
Template Parameters
aopt_t Type of the options object (from BOOST)
Parameters
opt The options object, where string based options are attached
Definition at line 26 of file ObjWriterOptions.hpp.
View newest version in sPHENIX GitHub at line 26 of file ObjWriterOptions.hpp
References value.
Referenced by processGeometry().
void ActsExamples::Options::addOutputOptions (boost::program_options::options_description & opt, OutputFormat format)
Add common output-related options.
Definition at line 103 of file CommonOptions.cpp.
View newest version in sPHENIX GitHub at line 103 of file CommonOptions.cpp
References ACTS_CHECK_BIT.
Referenced by main(), materialValidationExample(), processGeometry(), propagationExample(), runDetectorAlignment(), runDigitizationExample(), runFatras(), runHoughExample(), runMaterialMapping(), runMeasurementsToSP(), runRecCKFTracks(), runRecTruthTracks(), and runSeedingExample().
void ActsExamples::Options::addParticleGunOptions (Description & desc)
Add options for a particle-gun-like event generator.
Definition at line 19 of file ParticleGunOptions.cpp.
View newest version in sPHENIX GitHub at line 19 of file ParticleGunOptions.cpp
References Acts::eMuon, physmon_ckf_tracking::u, and value.
Referenced by ActsExamples::Simulation::addInputOptions(), and main().
void ActsExamples::Options::addParticleSelectorOptions (Options::Description & desc)
Definition at line 19 of file ParticleSelectorOptions.cpp.
View newest version in sPHENIX GitHub at line 19 of file ParticleSelectorOptions.cpp
References value.
Referenced by ActsExamples::Simulation::addInputOptions(), and main().
void ActsExamples::Options::addParticleSmearingOptions (Description & desc)
Add particle smearing options with a smearing- prefix.
Definition at line 11 of file ParticleSmearingOptions.cpp.
View newest version in sPHENIX GitHub at line 11 of file ParticleSmearingOptions.cpp
References value.
Referenced by main(), runDetectorAlignment(), runRecCKFTracks(), and runRecTruthTracks().
void ActsExamples::Options::addPropagationOptions (boost::program_options::options_description & opt) inline
PropagationAlgorithm options.
Template Parameters
aopt_t Type of the options class from boost
Definition at line 28 of file PropagationOptions.hpp.
View newest version in sPHENIX GitHub at line 28 of file PropagationOptions.hpp
References value.
Referenced by materialValidationExample(), propagationExample(), and runMaterialMapping().
void ActsExamples::Options::addPythia8Options (Description & desc)
Add options for a Pythia8-based event-generator.
Definition at line 22 of file Pythia8Options.cpp.
View newest version in sPHENIX GitHub at line 22 of file Pythia8Options.cpp
References Acts::eProton, physmon_ckf_tracking::u, and value.
Referenced by main().
void ActsExamples::Options::addRandomNumbersOptions (boost::program_options::options_description & opt)
Add random number options such as the global seed.
Definition at line 60 of file CommonOptions.cpp.
View newest version in sPHENIX GitHub at line 60 of file CommonOptions.cpp
References physmon_ckf_tracking::u.
Referenced by main(), materialValidationExample(), propagationExample(), runDetectorAlignment(), runDigitizationExample(), runFatras(), runHoughExample(), runMeasurementsToSP(), runRecCKFTracks(), runRecTruthTracks(), and runSeedingExample().
void ActsExamples::Options::addSequencerOptions (boost::program_options::options_description & opt)
Add sequencer options, e.g. number of events.
Definition at line 48 of file CommonOptions.cpp.
View newest version in sPHENIX GitHub at line 48 of file CommonOptions.cpp
Referenced by main(), materialValidationExample(), processGeometry(), propagationExample(), runDetectorAlignment(), runDigitizationConfigExample(), runDigitizationExample(), runFatras(), runHoughExample(), runMaterialMapping(), runMeasurementsToSP(), runRecCKFTracks(), runRecTruthTracks(), and runSeedingExample().
void ActsExamples::Options::addSpacePointMakerOptions (Description & desc)
Add SpacePointMaker options.
Parameters
desc The options description to add options to
Definition at line 17 of file SpacePointMakerOptions.cpp.
View newest version in sPHENIX GitHub at line 17 of file SpacePointMakerOptions.cpp
References value.
Referenced by runHoughExample(), runRecCKFTracks(), and runSeedingExample().
void ActsExamples::Options::addTrackFindingOptions (Description & desc)
Add TrackFinding options.
Parameters
desc The options description to add options to
Definition at line 18 of file TrackFindingOptions.cpp.
View newest version in sPHENIX GitHub at line 18 of file TrackFindingOptions.cpp
References value.
Referenced by runRecCKFTracks().
void ActsExamples::Options::addTruthSeedSelectorOptions (Options::Description & desc)
Definition at line 19 of file TruthSeedSelectorOptions.cpp.
View newest version in sPHENIX GitHub at line 19 of file TruthSeedSelectorOptions.cpp
References value.
Referenced by runDetectorAlignment(), and runRecTruthTracks().
void ActsExamples::Options::addVertexingOptions (Description & desc)
Add vertexing options.
Parameters
desc The options description to add options to
Definition at line 22 of file VertexingOptions.cpp.
View newest version in sPHENIX GitHub at line 22 of file VertexingOptions.cpp
References value.
Referenced by main().
void ActsExamples::Options::from_json (const nlohmann::json & j, ActsExamples::Options::Interval & interval)
Read config for options interval.
Definition at line 61 of file JsonTGeoDetectorConfig.hpp.
View newest version in sPHENIX GitHub at line 61 of file JsonTGeoDetectorConfig.hpp
References ActsExamples::Options::Interval::lower, and ActsExamples::Options::Interval::upper.
boost::program_options::options_description ActsExamples::Options::makeDefaultOptions (const std::string & caption = std::string())
Construct the options description with minimal default options.
Parameters
caption Optional help text caption
Definition at line 22 of file CommonOptions.cpp.
View newest version in sPHENIX GitHub at line 22 of file CommonOptions.cpp
Referenced by main(), materialValidationExample(), processGeometry(), propagationExample(), runDetectorAlignment(), runDigitizationConfigExample(), runDigitizationExample(), runFatras(), runHoughExample(), runMaterialMapping(), runMeasurementsToSP(), runRecCKFTracks(), runRecTruthTracks(), and runSeedingExample().
std::ostream & ActsExamples::Options::operator<< (std::ostream & os, const Interval & interval)
Print an interval as lower:upper.
Definition at line 54 of file Options.cpp.
View newest version in sPHENIX GitHub at line 54 of file Options.cpp
References ActsExamples::Options::Interval::lower, os, and ActsExamples::Options::Interval::upper.
template<size_t kSize> std::ostream& ActsExamples::Options::operator<< (std::ostream & os, const Reals< kSize > & values) inline
Print a fixed number of doubles as x:y:z.
Definition at line 117 of file Options.hpp.
View newest version in sPHENIX GitHub at line 117 of file Options.hpp
References os, ActsExamples::Options::detail::printDoubles(), and Acts::Test::values.
std::ostream& ActsExamples::Options::operator<< (std::ostream & os, const VariableReals & values) inline
Print a variable number of doubles as x:y:z:....
Definition at line 123 of file Options.hpp.
View newest version in sPHENIX GitHub at line 123 of file Options.hpp
References os, ActsExamples::Options::detail::printDoubles(), and ActsExamples::Options::VariableReals::values.
template<size_t kSize> std::ostream& ActsExamples::Options::operator<< (std::ostream & os, const Integers< kSize > & values) inline
Print a fixed number of integers as x:y:z.
Definition at line 157 of file Options.hpp.
View newest version in sPHENIX GitHub at line 157 of file Options.hpp
References os, and ActsExamples::Options::detail::printIntegers().
std::ostream& ActsExamples::Options::operator<< (std::ostream & os, const VariableIntegers & values) inline
Print a variable number of integers as x:y:z:....
Definition at line 164 of file Options.hpp.
View newest version in sPHENIX GitHub at line 164 of file Options.hpp
References os, ActsExamples::Options::detail::printIntegers(), and ActsExamples::Options::VariableIntegers::values.
std::istream & ActsExamples::Options::operator>> (std::istream & is, Interval & interval)
Extract an interval from an input of the form 'lower:upper'.
An input of the form lower: or :upper sets just one of the limits. Any other input leads to an unbounded interval.
Note
The more common range notation uses lower-upper but the - separator complicates the parsing of negative values.
Definition at line 24 of file Options.cpp.
View newest version in sPHENIX GitHub at line 24 of file Options.cpp
References ActsExamples::Options::Interval::lower, Acts::Test::pos, and ActsExamples::Options::Interval::upper.
template<size_t kSize> std::istream& ActsExamples::Options::operator>> (std::istream & is, Reals< kSize > & values) inline
Extract a fixed number of doubles from an input of the form 'x:y:z'.
Note
If the values would be separated by whitespace, negative values and additional command line both start with - and would be undistinguishable.
Definition at line 100 of file Options.hpp.
View newest version in sPHENIX GitHub at line 100 of file Options.hpp
References ActsExamples::Options::detail::parseDoublesFixed().
std::istream& ActsExamples::Options::operator>> (std::istream & is, VariableReals & values) inline
Extract a variable number of doubles from an input of the form 'x:y:...'.
Note
If the values would be separated by whitespace, negative values and additional command line both start with - and would be undistinguishable.
Definition at line 110 of file Options.hpp.
View newest version in sPHENIX GitHub at line 110 of file Options.hpp
References ActsExamples::Options::detail::parseDoublesVariable(), and ActsExamples::Options::VariableReals::values.
template<size_t kSize> std::istream& ActsExamples::Options::operator>> (std::istream & is, Integers< kSize > & values) inline
Extract a fixed number of integers from an input of the form 'x:y:z'.
Note
If the values would be separated by whitespace, negative values and additional command line both start with - and would be undistinguishable.
Definition at line 140 of file Options.hpp.
View newest version in sPHENIX GitHub at line 140 of file Options.hpp
References ActsExamples::Options::detail::parseIntegersFixed().
std::istream& ActsExamples::Options::operator>> (std::istream & is, VariableIntegers & values) inline
Extract a variable number of integers from an input of the form 'x:y:...'.
Note
If the values would be separated by whitespace, negative values and additional command line both start with - and would be undistinguishable.
Definition at line 150 of file Options.hpp.
View newest version in sPHENIX GitHub at line 150 of file Options.hpp
References ActsExamples::Options::detail::parseIntegersVariable(), and ActsExamples::Options::VariableIntegers::values.
boost::program_options::variables_map ActsExamples::Options::parse (const boost::program_options::options_description & opt, int argc, char * argv[]) noexcept
Parse options and return the resulting variables map.
Automatically prints the help text if requested.
Returns
Empty variables map if help text was shown.
Definition at line 160 of file CommonOptions.cpp.
View newest version in sPHENIX GitHub at line 160 of file CommonOptions.cpp
References check_smearing_config::args, end, ckf::options, utils::run, store, and physmon_ckf_tracking::u.
Referenced by odbc::Date::Date(), main(), MakeActsGeometry::makeGeometry(), materialValidationExample(), processGeometry(), propagationExample(), runDetectorAlignment(), runDigitizationConfigExample(), runDigitizationExample(), runFatras(), runHoughExample(), runMaterialMapping(), runMeasurementsToSP(), runRecCKFTracks(), runRecTruthTracks(), runSeedingExample(), odbc::Time::Time(), and odbc::Timestamp::Timestamp().
ActsExamples::CsvMeasurementReader::Config ActsExamples::Options::readCsvMeasurementReaderConfig (const Variables & vm)
Read the CSV measurement reader config.
Definition at line 41 of file CsvOptionsReader.cpp.
View newest version in sPHENIX GitHub at line 41 of file CsvOptionsReader.cpp
References cfg, and ActsExamples::CsvMeasurementReader::Config::inputDir.
Referenced by runDigitizationExample(), and setupMeasurementReading().
ActsExamples::CsvMeasurementWriter::Config ActsExamples::Options::readCsvMeasurementWriterConfig (const Variables & vm)
Read the CSV measurement writer options.
Definition at line 59 of file CsvOptionsWriter.cpp.
View newest version in sPHENIX GitHub at line 59 of file CsvOptionsWriter.cpp
References cfg, and ActsExamples::CsvMeasurementWriter::Config::outputDir.
Referenced by runDigitizationExample().
ActsExamples::CsvParticleReader::Config ActsExamples::Options::readCsvParticleReaderConfig (const Variables & vm)
Read the CSV particle reader config.
Definition at line 14 of file CsvOptionsReader.cpp.
View newest version in sPHENIX GitHub at line 14 of file CsvOptionsReader.cpp
References cfg, and ActsExamples::CsvParticleReader::Config::inputDir.
Referenced by main(), and setupParticleReading().
ActsExamples::CsvParticleWriter::Config ActsExamples::Options::readCsvParticleWriterConfig (const Variables & vm)
Read the CSV particle writer options.
Definition at line 28 of file CsvOptionsWriter.cpp.
View newest version in sPHENIX GitHub at line 28 of file CsvOptionsWriter.cpp
References cfg, ActsExamples::CsvParticleWriter::Config::outputDir, and ActsExamples::CsvParticleWriter::Config::outputPrecision.
ActsExamples::CsvPlanarClusterReader::Config ActsExamples::Options::readCsvPlanarClusterReaderConfig (const Variables & vm)
Read the CSV particle reader config.
Definition at line 50 of file CsvOptionsReader.cpp.
View newest version in sPHENIX GitHub at line 50 of file CsvOptionsReader.cpp
References cfg, and ActsExamples::CsvPlanarClusterReader::Config::inputDir.
ActsExamples::CsvPlanarClusterWriter::Config ActsExamples::Options::readCsvPlanarClusterWriterConfig (const Variables & vm)
Read the CSV planar cluster writer options.
Definition at line 48 of file CsvOptionsWriter.cpp.
View newest version in sPHENIX GitHub at line 48 of file CsvOptionsWriter.cpp
References cfg, ActsExamples::CsvPlanarClusterWriter::Config::outputDir, and ActsExamples::CsvPlanarClusterWriter::Config::outputPrecision.
ActsExamples::CsvSimHitReader::Config ActsExamples::Options::readCsvSimHitReaderConfig (const Variables & vm)
Read the CSV sim hit reader config.
Definition at line 23 of file CsvOptionsReader.cpp.
View newest version in sPHENIX GitHub at line 23 of file CsvOptionsReader.cpp
References cfg, and ActsExamples::CsvSimHitReader::Config::inputDir.
Referenced by setupSimHitReading().
ActsExamples::CsvSimHitWriter::Config ActsExamples::Options::readCsvSimHitWriterConfig (const Variables & vm)
Read the CSV sim hit writer options.
Definition at line 39 of file CsvOptionsWriter.cpp.
View newest version in sPHENIX GitHub at line 39 of file CsvOptionsWriter.cpp
References cfg, and ActsExamples::CsvSimHitWriter::Config::outputDir.
ActsExamples::CsvSpacePointReader::Config ActsExamples::Options::readCsvSpacePointReaderConfig (const Variables & vm)
Read the CSV space point reader config.
Definition at line 32 of file CsvOptionsReader.cpp.
View newest version in sPHENIX GitHub at line 32 of file CsvOptionsReader.cpp
References cfg, and ActsExamples::CsvSpacePointReader::Config::inputDir.
ActsExamples::CsvTrackingGeometryWriter::Config ActsExamples::Options::readCsvTrackingGeometryWriterConfig (const Variables & vm)
Read the CSV tracking geometry writer config.
Definition at line 70 of file CsvOptionsWriter.cpp.
View newest version in sPHENIX GitHub at line 70 of file CsvOptionsWriter.cpp
References cfg, ActsExamples::CsvTrackingGeometryWriter::Config::outputDir, ActsExamples::CsvTrackingGeometryWriter::Config::outputPrecision, physmon_ckf_tracking::u, and ActsExamples::CsvTrackingGeometryWriter::Config::writePerEvent.
template<typename amap_t > ActsExamples::DD4hep::DD4hepGeometryService::Config ActsExamples::Options::readDD4hepConfig (const amap_t & vm)
read the particle gun options and return a Config file
Definition at line 55 of file DD4hepDetectorOptions.hpp.
View newest version in sPHENIX GitHub at line 55 of file DD4hepDetectorOptions.hpp
References Acts::arbitrary, Acts::equidistant, ActsExamples::DD4hep::DD4hepGeometryService::Config::logLevel, and ActsExamples::DD4hep::sortFCChhDetElements().
Referenced by main().
ActsExamples::FatrasSimulation::Config ActsExamples::Options::readFatrasConfig (const Options::Variables & vars)
Definition at line 44 of file FatrasOptions.cpp.
View newest version in sPHENIX GitHub at line 44 of file FatrasOptions.cpp
References cfg.
ActsExamples::HepMC3AsciiReader::Config ActsExamples::Options::readHepMC3ReaderOptions (const Variables & variables)
Read the HepMC3 reader options and
Returns
a HepMC3ReaderAscii::Config
Parameters
variables is the parameter map for the options
Returns
a Config object for the HepMC3ReaderAscii
Definition at line 48 of file HepMC3Options.cpp.
View newest version in sPHENIX GitHub at line 48 of file HepMC3Options.cpp
References ActsExamples::HepMC3AsciiReader::Config::inputDir, and ActsExamples::HepMC3AsciiReader::Config::inputStem.
Referenced by main().
ActsExamples::HepMC3AsciiWriter::Config ActsExamples::Options::readHepMC3WriterOptions (const Variables & variables)
Read the HepMC3 writer options and
Returns
a HepMC3WriterAscii::Config
Parameters
variables is the parameter map for the options
Returns
a Config object for the HepMC3WriterAscii
Definition at line 28 of file HepMC3Options.cpp.
View newest version in sPHENIX GitHub at line 28 of file HepMC3Options.cpp
References ActsExamples::HepMC3AsciiWriter::Config::outputDir, and ActsExamples::HepMC3AsciiWriter::Config::outputStem.
Referenced by main().
ActsExamples::JsonSurfacesWriter::Config ActsExamples::Options::readJsonSurfacesWriterConfig (const Variables & vm)
Read the Json tracking geometry writer config.
Definition at line 34 of file JsonOptionsWriter.cpp.
View newest version in sPHENIX GitHub at line 34 of file JsonOptionsWriter.cpp
References cfg, ActsExamples::JsonSurfacesWriter::Config::outputDir, ActsExamples::JsonSurfacesWriter::Config::outputPrecision, ActsExamples::JsonSurfacesWriter::Config::writeApproach, ActsExamples::JsonSurfacesWriter::Config::writeBoundary, ActsExamples::JsonSurfacesWriter::Config::writeLayer, ActsExamples::JsonSurfacesWriter::Config::writeOnlyNames, and ActsExamples::JsonSurfacesWriter::Config::writeSensitive.
Referenced by processGeometry().
Acts::Logging::Level ActsExamples::Options::readLogLevel (const boost::program_options::variables_map & vm)
Read the log level.
Definition at line 201 of file CommonOptions.cpp.
View newest version in sPHENIX GitHub at line 201 of file CommonOptions.cpp
Referenced by main(), materialValidationExample(), processGeometry(), propagationExample(), readSequencerConfig(), runDetectorAlignment(), runDigitizationExample(), runHoughExample(), runMaterialMapping(), ActsExamples::runMaterialRecording(), runMeasurementsToSP(), runRecCKFTracks(), runRecTruthTracks(), runSeedingExample(), setupDigitization(), ActsExamples::Simulation::setupInput(), setupMeasurementReading(), ActsExamples::Simulation::setupOutput(), setupParticleReading(), setupParticleSmearing(), and setupSimHitReading().
std::shared_ptr< Acts::MagneticFieldProvider > ActsExamples::Options::readMagneticField (const Variables & vars)
Read and create the magnetic field from the given user variables.
Definition at line 104 of file MagneticFieldOptions.cpp.
View newest version in sPHENIX GitHub at line 104 of file MagneticFieldOptions.cpp
References ACTS_ERROR, ACTS_INFO, ACTS_LOCAL_LOGGER, bins, ckf::field, file, Acts::getDefaultLogger(), Acts::Logging::INFO, centProxy::interval, Acts::SolenoidBField::Config::length, ActsExamples::HepMC3Event::lengthUnit(), test_detectors::lower, ActsExamples::makeMagneticFieldMapRzFromRoot(), ActsExamples::makeMagneticFieldMapRzFromText(), ActsExamples::makeMagneticFieldMapXyzFromRoot(), ActsExamples::makeMagneticFieldMapXyzFromText(), Acts::UnitConstants::mm, testing::internal::move(), perf_headwind::name, nbins, path, Acts::solenoidFieldMap(), Acts::UnitConstants::T, tree, parse_cmake_options::type, physmon_ckf_tracking::u, test_detectors::upper, and Acts::Test::values.
Referenced by main(), MakeActsGeometry::makeGeometry(), materialValidationExample(), propagationExample(), runDetectorAlignment(), runDigitizationExample(), ActsExamples::runGeant4Simulation(), runHoughExample(), runMeasurementsToSP(), runRecCKFTracks(), runRecTruthTracks(), and runSeedingExample().
std::string ActsExamples::Options::readNuclearInteractionConfig (const boost::program_options::variables_map & variables)
Read Fatras options to create the algorithm config.
Parameters
variables the variables to read from
Definition at line 132 of file NuclearInteractionOptions.cpp.
View newest version in sPHENIX GitHub at line 132 of file NuclearInteractionOptions.cpp
ActsExamples::ObjTrackingGeometryWriter::Config ActsExamples::Options::readObjTrackingGeometryWriterConfig (const boost::program_options::variables_map & vm)
read the evgen options and return a Config file
Definition at line 61 of file ObjWriterOptions.hpp.
View newest version in sPHENIX GitHub at line 61 of file ObjWriterOptions.hpp
References ActsExamples::ObjTrackingGeometryWriter::Config::containerView, ActsExamples::ObjTrackingGeometryWriter::Config::gridView, Acts::ViewConfig::lineThickness, Acts::ViewConfig::offset, ActsExamples::ObjTrackingGeometryWriter::Config::outputPrecision, ActsExamples::ObjTrackingGeometryWriter::Config::outputScalor, ActsExamples::ObjTrackingGeometryWriter::Config::passiveView, and ActsExamples::ObjTrackingGeometryWriter::Config::sensitiveView.
Referenced by processGeometry().
ActsFatras::detail::MultiParticleNuclearInteractionParametrisation ActsExamples::Options::readParametrisations (const std::string & fileName)
Reads the parametrisation and provides the parametrisation.
Definition at line 139 of file NuclearInteractionOptions.cpp.
View newest version in sPHENIX GitHub at line 139 of file NuclearInteractionOptions.cpp
References ActsFatras::detail::NuclearInteractionParameters::hardMultiplicity, i, it, ActsFatras::detail::NuclearInteractionParameters::momentum, ActsFatras::detail::NuclearInteractionParameters::nuclearInteractionProbability, Dataset::parameters, ActsFatras::detail::NuclearInteractionParameters::pdgMap, ActsFatras::detail::NuclearInteractionParameters::softInteractionProbability, ActsFatras::detail::NuclearInteractionParameters::softMultiplicity, and material_mapping_optimisation::target.
Referenced by setNuclearInteractionParametrisations().
ActsExamples::EventGenerator::Config ActsExamples::Options::readParticleGunOptions (const Variables & vars)
Create the event generator config from particle-gun options.
Definition at line 54 of file ParticleGunOptions.cpp.
View newest version in sPHENIX GitHub at line 54 of file ParticleGunOptions.cpp
References Acts::MultiIndex< uint64_t, 12, 12, 16, 8, 16 >::bits(), cfg, Acts::ePos0, Acts::ePos1, Acts::ePos2, Acts::eTime, centProxy::interval, test_detectors::lower, testing::internal::move(), perf_headwind::name, and test_detectors::upper.
Referenced by main(), ActsExamples::runMaterialRecording(), and ActsExamples::Simulation::setupInput().
ActsExamples::ParticleSelector::Config ActsExamples::Options::readParticleSelectorConfig (const Options::Variables & vars)
Definition at line 43 of file ParticleSelectorOptions.cpp.
View newest version in sPHENIX GitHub at line 43 of file ParticleSelectorOptions.cpp
References cfg, centProxy::interval, test_detectors::lower, perf_headwind::name, and test_detectors::upper.
Referenced by main(), and ActsExamples::Simulation::setupInput().
ActsExamples::ParticleSmearing::Config ActsExamples::Options::readParticleSmearingOptions (const Options::Variables & vars)
Read options.
Definition at line 32 of file ParticleSmearingOptions.cpp.
View newest version in sPHENIX GitHub at line 32 of file ParticleSmearingOptions.cpp
References cfg, Acts::UnitConstants::degree, Acts::UnitConstants::GeV, Acts::UnitConstants::ns, and Acts::UnitConstants::um.
Referenced by setupParticleSmearing().
ActsExamples::PropagationAlgorithm::Config ActsExamples::Options::readPropagationConfig (const boost::program_options::variables_map & vm) inline
Read the pgropagator options and return a Config file
Template Parameters
vmap_t is the Type of the Parameter map to be read out
propagator_t is the Type of the Propagator used
Returns
a Config object for the PropagationAlgorithm
Material interaction behavior
Create the config for the Extrapoaltion algorithm
The covariance transport
Set the covariance transport to true
Set the covariance matrix
Some pre-defined values (non-trivial helical correlations)
Definition at line 95 of file PropagationOptions.hpp.
View newest version in sPHENIX GitHub at line 95 of file PropagationOptions.hpp
References Acts::eBoundLoc0, Acts::eBoundLoc1, Acts::eBoundPhi, Acts::eBoundQOverP, Acts::eBoundTheta, Acts::eBoundTime, ActsExamples::PropagationAlgorithm::Config::energyLoss, and physmon_ckf_tracking::u.
Referenced by propagationExample().
ActsExamples::EventGenerator::Config ActsExamples::Options::readPythia8Options (const Variables & vars, Acts::Logging::Level lvl)
Create the event generator config from Pythia8 options.
This builds a full event generator with separate hard scatter and pileup. Not just the Pythia8 process generators to simplify the handling.
Definition at line 57 of file Pythia8Options.cpp.
View newest version in sPHENIX GitHub at line 57 of file Pythia8Options.cpp
References cfg, ActsExamples::Pythia8Generator::Config::cmsEnergy, Acts::ePos0, Acts::ePos1, Acts::ePos2, Acts::eTime, physmon_track_finding_ttbar::npileup, ActsExamples::Pythia8Generator::Config::pdgBeam0, ActsExamples::Pythia8Generator::Config::pdgBeam1, ActsExamples::Pythia8Generator::Config::settings, and physmon_ckf_tracking::u.
Referenced by main().
ActsExamples::RandomNumbers::Config ActsExamples::Options::readRandomNumbersConfig (const boost::program_options::variables_map & vm)
Definition at line 223 of file CommonOptions.cpp.
View newest version in sPHENIX GitHub at line 223 of file CommonOptions.cpp
References cfg, and ActsExamples::RandomNumbers::Config::seed.
Referenced by main(), materialValidationExample(), propagationExample(), runDetectorAlignment(), runDigitizationExample(), runFatras(), ActsExamples::runGeant4Simulation(), runHoughExample(), ActsExamples::runMaterialRecording(), runMeasurementsToSP(), runRecCKFTracks(), runRecTruthTracks(), and runSeedingExample().
ActsExamples::Sequencer::Config ActsExamples::Options::readSequencerConfig (const boost::program_options::variables_map & vm)
Read the sequencer config.
Definition at line 206 of file CommonOptions.cpp.
View newest version in sPHENIX GitHub at line 206 of file CommonOptions.cpp
References cfg, ActsExamples::Sequencer::Config::events, ActsExamples::Sequencer::Config::logLevel, ActsExamples::Sequencer::Config::numThreads, ActsExamples::Sequencer::Config::outputDir, readLogLevel(), and ActsExamples::Sequencer::Config::skip.
Referenced by main(), materialValidationExample(), processGeometry(), propagationExample(), runDetectorAlignment(), runDigitizationExample(), runFatras(), ActsExamples::runGeant4Simulation(), runHoughExample(), runMaterialMapping(), ActsExamples::runMaterialRecording(), runMeasurementsToSP(), runRecCKFTracks(), runRecTruthTracks(), and runSeedingExample().
ActsExamples::SpacePointMaker::Config ActsExamples::Options::readSpacePointMakerConfig (const Variables & variables)
Read SpacePointMaker options to create the algorithm config.
Parameters
variables The variables to read from
Definition at line 27 of file SpacePointMakerOptions.cpp.
View newest version in sPHENIX GitHub at line 27 of file SpacePointMakerOptions.cpp
References cfg, ActsExamples::SpacePointMaker::Config::geometrySelection, path, and ActsExamples::readJsonGeometryList().
Referenced by runHoughExample(), runRecCKFTracks(), and runSeedingExample().
ActsExamples::TrackFindingAlgorithm::Config ActsExamples::Options::readTrackFindingConfig (const Variables & variables)
Read TrackFinding options to create the algorithm config.
Parameters
variables The variables to read from
Definition at line 39 of file TrackFindingOptions.cpp.
View newest version in sPHENIX GitHub at line 39 of file TrackFindingOptions.cpp
References cfg, and Acts::Test::values.
Referenced by runRecCKFTracks().
ActsExamples::TruthSeedSelector::Config ActsExamples::Options::readTruthSeedSelectorConfig (const Options::Variables & vars)
Definition at line 40 of file TruthSeedSelectorOptions.cpp.
View newest version in sPHENIX GitHub at line 40 of file TruthSeedSelectorOptions.cpp
References cfg, centProxy::interval, test_detectors::lower, perf_headwind::name, and test_detectors::upper.
Referenced by runDetectorAlignment(), and runRecTruthTracks().
template<typename simulator_t > void ActsExamples::Options::setNuclearInteractionParametrisations (const std::string & nuclearInteractionParametrisation, simulator_t & simulator)
Read the parametrisations.
Template Parameters
simulator_t type of the simulation kernel
Parameters
[in] nuclearInteractionParametrisation File name of the parametrisations
[in,out] simulator The simulation kernel
Definition at line 46 of file NuclearInteractionOptions.hpp.
View newest version in sPHENIX GitHub at line 46 of file NuclearInteractionOptions.hpp
References readParametrisations().
void ActsExamples::Options::setupMagneticFieldServices (const Variables & vars, Sequencer & seq)
Setup any additional services required for the magnetic field.
Definition at line 93 of file MagneticFieldOptions.cpp.
View newest version in sPHENIX GitHub at line 93 of file MagneticFieldOptions.cpp
References ActsExamples::Sequencer::addContextDecorator(), Acts::Logging::INFO, and ActsExamples::ScalableBFieldService::Config::scalor.
Referenced by materialValidationExample(), propagationExample(), runDigitizationExample(), runHoughExample(), runMeasurementsToSP(), and runSeedingExample().
void ActsExamples::Options::to_json (nlohmann::json & j, const ActsExamples::Options::Interval & interval)
Write config for options interval.
Definition at line 68 of file JsonTGeoDetectorConfig.hpp.
View newest version in sPHENIX GitHub at line 68 of file JsonTGeoDetectorConfig.hpp
References ActsExamples::Options::Interval::lower, and ActsExamples::Options::Interval::upper.