Analysis Software: Eventplaneinfo Class Reference
Eventplaneinfo Class Reference
#include <coresoftware/blob/master/offline/packages/eventplaneinfo/Eventplaneinfo.h>
Public Member Functions
~Eventplaneinfo () override
void identify (std::ostream &os=std::cout) const override
PHObject * CloneMe () const override
Virtual copy constructor.
virtual void set_qvector (std::vector< std::pair< double, double >>)
virtual void set_shifted_psi (std::vector< double >)
virtual std::pair< double, double > get_qvector (int) const
virtual double get_psi (int) const
virtual double get_shifted_psi (int) const
virtual double GetPsi (const double, const double, const unsigned int) const
Public Member Functions inherited from PHObject
PHObject ()
ctor
~PHObject () override
dtor
virtual PHObject * clone () const final
PHObject * Clone (const char *newname="") const final
void Copy (TObject &object) const final
virtual void Reset ()
Clear Event.
virtual int isValid () const
isValid returns non zero if object contains vailid data
virtual int Integrate () const
virtual int Integrate (PHObject *)
virtual void CopyFrom (const PHObject *obj)
Protected Member Functions
Eventplaneinfo ()
Private Member Functions
ClassDefOverride (Eventplaneinfo, 1)
Detailed Description
Definition at line 11 of file Eventplaneinfo.h.
View newest version in sPHENIX GitHub at line 11 of file Eventplaneinfo.h
Constructor & Destructor Documentation
Eventplaneinfo::~Eventplaneinfo () inline override
Definition at line 14 of file Eventplaneinfo.h.
View newest version in sPHENIX GitHub at line 14 of file Eventplaneinfo.h
Eventplaneinfo::Eventplaneinfo () inline protected
Definition at line 32 of file Eventplaneinfo.h.
View newest version in sPHENIX GitHub at line 32 of file Eventplaneinfo.h
Member Function Documentation
Eventplaneinfo::ClassDefOverride (Eventplaneinfo , 1) private
PHObject* Eventplaneinfo::CloneMe () const inline override virtual
Virtual copy constructor.
Reimplemented from PHObject.
Reimplemented in Eventplaneinfov1.
Definition at line 21 of file Eventplaneinfo.h.
View newest version in sPHENIX GitHub at line 21 of file Eventplaneinfo.h
virtual double Eventplaneinfo::get_psi (int) const inline virtual
Reimplemented in Eventplaneinfov1.
Definition at line 26 of file Eventplaneinfo.h.
View newest version in sPHENIX GitHub at line 26 of file Eventplaneinfo.h
virtual std::pair<double, double> Eventplaneinfo::get_qvector (int) const inline virtual
Reimplemented in Eventplaneinfov1.
Definition at line 25 of file Eventplaneinfo.h.
View newest version in sPHENIX GitHub at line 25 of file Eventplaneinfo.h
virtual double Eventplaneinfo::get_shifted_psi (int) const inline virtual
Reimplemented in Eventplaneinfov1.
Definition at line 27 of file Eventplaneinfo.h.
View newest version in sPHENIX GitHub at line 27 of file Eventplaneinfo.h
virtual double Eventplaneinfo::GetPsi (const double , const double , const unsigned int) const inline virtual
Reimplemented in Eventplaneinfov1.
Definition at line 28 of file Eventplaneinfo.h.
View newest version in sPHENIX GitHub at line 28 of file Eventplaneinfo.h
Referenced by EventPlaneReco::process_event().
void Eventplaneinfo::identify (std::ostream & os = std::cout) const inline override virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from PHObject.
Reimplemented in Eventplaneinfov1.
Definition at line 16 of file Eventplaneinfo.h.
View newest version in sPHENIX GitHub at line 16 of file Eventplaneinfo.h
References os.
Referenced by EventPlaneReco::process_event().
virtual void Eventplaneinfo::set_qvector (std::vector< std::pair< double, double >>) inline virtual
Reimplemented in Eventplaneinfov1.
Definition at line 23 of file Eventplaneinfo.h.
View newest version in sPHENIX GitHub at line 23 of file Eventplaneinfo.h
Referenced by EventPlaneReco::process_event().
virtual void Eventplaneinfo::set_shifted_psi (std::vector< double >) inline virtual
Reimplemented in Eventplaneinfov1.
Definition at line 24 of file Eventplaneinfo.h.
View newest version in sPHENIX GitHub at line 24 of file Eventplaneinfo.h
Referenced by EventPlaneReco::process_event().
The documentation for this class was generated from the following file:
coresoftware/blob/master/offline/packages/eventplaneinfo/Eventplaneinfo.h