Analysis Software: RawHitSet Class Reference
RawHitSet Class Reference
Container for storing RawHit's.
#include <coresoftware/blob/master/offline/packages/trackbase/RawHitSet.h>
Public Types
using Vector = std::vector< RawHit * >
using VectorTpc2D = std::vector< std::vector< uint8_t >>
using ConstIterator = Vector::const_iterator
using ConstRange = std::pair< ConstIterator, ConstIterator >
Public Member Functions
void identify (std::ostream &=std::cout) const override
TObject functions.
void Reset () override
Clear Event.
virtual void setHitSetKey (const TrkrDefs::hitsetkey)
Set the key for this object.
virtual TrkrDefs::hitsetkey getHitSetKey () const
Get the key for this object.
virtual void addHit (RawHit *)
Add a hit to this container using a specific key.
virtual void setTpcPhiBins (unsigned short phibins)
virtual ConstRange getHits () const
Remove a hit using its key.
virtual unsigned int size () const
Get the number of hits stored.
virtual unsigned int tpcphibins () const
Public Member Functions inherited from PHObject
PHObject ()
ctor
~PHObject () override
dtor
virtual PHObject * CloneMe () const
Virtual copy constructor.
virtual PHObject * clone () const final
PHObject * Clone (const char *newname="") const final
void Copy (TObject &object) const final
virtual int isValid () const
isValid returns non zero if object contains vailid data
virtual int Integrate () const
virtual int Integrate (PHObject *)
virtual void CopyFrom (const PHObject *obj)
Protected Member Functions
RawHitSet ()=default
ctor, not to be called
Private Member Functions
ClassDefOverride (RawHitSet, 1)
Detailed Description
Container for storing RawHit's.
Container object which stores a set of RawHit objects. A single RawHitSet is meant to represent a geometric detector object which bounds clustering. Therefore, a RawHitSet should contain all RawHits which could belong the the same cluster.
Definition at line 30 of file RawHitSet.h.
View newest version in sPHENIX GitHub at line 30 of file RawHitSet.h
Member Typedef Documentation
using RawHitSet::ConstIterator = Vector::const_iterator
Definition at line 36 of file RawHitSet.h.
View newest version in sPHENIX GitHub at line 36 of file RawHitSet.h
using RawHitSet::ConstRange = std::pair<ConstIterator, ConstIterator>
Definition at line 37 of file RawHitSet.h.
View newest version in sPHENIX GitHub at line 37 of file RawHitSet.h
using RawHitSet::Vector = std::vector<RawHit*>
Definition at line 34 of file RawHitSet.h.
View newest version in sPHENIX GitHub at line 34 of file RawHitSet.h
using RawHitSet::VectorTpc2D = std::vector<std::vector<uint8_t>>
Definition at line 35 of file RawHitSet.h.
View newest version in sPHENIX GitHub at line 35 of file RawHitSet.h
Constructor & Destructor Documentation
RawHitSet::RawHitSet () protected default
ctor, not to be called
Member Function Documentation
void RawHitSet::addHit (RawHit *) virtual
Add a hit to this container using a specific key.
Parameters
[in] key Hit key
[in] hit Hit to be added.
NOTE: This RawHitSet takes ownership of the passed RawHit pointer and will delete it in the Reset() method.
Reimplemented in RawHitSetv1.
Definition at line 14 of file RawHitSet.cc.
View newest version in sPHENIX GitHub at line 14 of file RawHitSet.cc
Referenced by TpcRawWriter::process_event().
RawHitSet::ClassDefOverride (RawHitSet , 1) private
RawHitSet::ConstRange RawHitSet::getHits () const virtual
Remove a hit using its key.
Parameters
[in] key to be removed Get a specific hit based on its index.
key of the desired hit
[out] Pointer to the desired hit. nullptr if no hit.
Get a desired hit based on its key. Get all hits
Parameters
[out] Pair of iterator to vector begin and end
Reimplemented in RawHitSetv1.
Definition at line 24 of file RawHitSet.cc.
View newest version in sPHENIX GitHub at line 24 of file RawHitSet.cc
Referenced by InttClusterizer::ClusterLadderCellsRaw(), and MvtxClusterizer::ClusterMvtxRaw().
virtual TrkrDefs::hitsetkey RawHitSet::getHitSetKey () const inline virtual
Get the key for this object.
Parameters
[out] object key
Reimplemented in RawHitSetv1.
Definition at line 60 of file RawHitSet.h.
View newest version in sPHENIX GitHub at line 60 of file RawHitSet.h
Referenced by RawHitSetContainerv1::addHitSet(), InttClusterizer::ClusterLadderCellsRaw(), MvtxClusterizer::ClusterMvtxRaw(), and RawHitSetContainerv1::removeHitSet().
void RawHitSet::identify (std::ostream & = std::cout) const inline override virtual
TObject functions.
Reimplemented from PHObject.
Reimplemented in RawHitSetv1.
Definition at line 40 of file RawHitSet.h.
View newest version in sPHENIX GitHub at line 40 of file RawHitSet.h
Referenced by InttClusterizer::ClusterLadderCellsRaw(), and MvtxClusterizer::ClusterMvtxRaw().
void RawHitSet::Reset () inline override virtual
Clear Event.
Reimplemented from PHObject.
Reimplemented in RawHitSetv1.
Definition at line 44 of file RawHitSet.h.
View newest version in sPHENIX GitHub at line 44 of file RawHitSet.h
virtual void RawHitSet::setHitSetKey (const TrkrDefs::hitsetkey) inline virtual
Set the key for this object.
Parameters
key
Reimplemented in RawHitSetv1.
Definition at line 52 of file RawHitSet.h.
View newest version in sPHENIX GitHub at line 52 of file RawHitSet.h
void RawHitSet::setTpcPhiBins (unsigned short phibins) virtual
Reimplemented in RawHitSetv1.
Definition at line 20 of file RawHitSet.cc.
View newest version in sPHENIX GitHub at line 20 of file RawHitSet.cc
virtual unsigned int RawHitSet::size (void) const inline virtual
Get the number of hits stored.
Parameters
[out] number of hits
Reimplemented in RawHitSetv1.
Definition at line 107 of file RawHitSet.h.
View newest version in sPHENIX GitHub at line 107 of file RawHitSet.h
virtual unsigned int RawHitSet::tpcphibins () const inline virtual
Reimplemented in RawHitSetv1.
Definition at line 111 of file RawHitSet.h.
View newest version in sPHENIX GitHub at line 111 of file RawHitSet.h
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/trackbase/RawHitSet.h
coresoftware/blob/master/offline/packages/trackbase/RawHitSet.cc