Analysis Software: RawTowerGeomContainer Class Reference
RawTowerGeomContainer Class Reference
base class to describe calorimeter geometries
#include <coresoftware/blob/master/offline/packages/CaloBase/RawTowerGeomContainer.h>
Public Types
typedef std::map
< RawTowerDefs::keytype,
RawTowerGeom * > Map
typedef Map::iterator Iterator
typedef Map::const_iterator ConstIterator
typedef std::pair< Iterator,
Iterator > Range
typedef std::pair
< ConstIterator, ConstIterator > ConstRange
Public Member Functions
~RawTowerGeomContainer () override
default constructor for ROOT IO
void identify (std::ostream &os=std::cout) const override
virtual void set_calorimeter_id (RawTowerDefs::CalorimeterId)
8-bit calorimeter ID
virtual RawTowerDefs::CalorimeterId get_calorimeter_id () const
virtual ConstIterator add_tower_geometry (RawTowerGeom *geo)
go through all towers
virtual RawTowerGeom * get_tower_geometry (RawTowerDefs::keytype)
virtual ConstRange get_tower_geometries (void) const
return all tower geometries
virtual Range get_tower_geometries (void)
virtual unsigned int size () const
virtual double get_radius () const
virtual double get_thickness () const
virtual int get_phibins () const
virtual int get_etabins () const
virtual std::pair< double, double > get_phibounds (const int) const
virtual std::pair< double, double > get_etabounds (const int) const
virtual double get_etacenter (const int) const
virtual double get_phicenter (const int) const
virtual int get_etabin (const double) const
virtual int get_phibin (const double) const
virtual void set_radius (const double)
virtual void set_thickness (const double)
virtual void set_phibins (const int)
virtual void set_etabins (const int)
virtual void set_etabounds (const int, const std::pair< double, double > &)
virtual void set_phibounds (const int, const std::pair< double, double > &)
Public Member Functions inherited from PHObject
PHObject ()
ctor
~PHObject () override
dtor
virtual PHObject * CloneMe () const
Virtual copy constructor.
virtual PHObject * clone () const final
PHObject * Clone (const char *newname="") const final
void Copy (TObject &object) const final
virtual void Reset ()
Clear Event.
virtual int isValid () const
isValid returns non zero if object contains vailid data
virtual int Integrate () const
virtual int Integrate (PHObject *)
virtual void CopyFrom (const PHObject *obj)
Protected Member Functions
RawTowerGeomContainer ()
this class is not for use. Base class only
Detailed Description
base class to describe calorimeter geometries
Definition at line 21 of file RawTowerGeomContainer.h.
View newest version in sPHENIX GitHub at line 21 of file RawTowerGeomContainer.h
Member Typedef Documentation
typedef Map::const_iterator RawTowerGeomContainer::ConstIterator
Definition at line 26 of file RawTowerGeomContainer.h.
View newest version in sPHENIX GitHub at line 26 of file RawTowerGeomContainer.h
typedef std::pair<ConstIterator, ConstIterator> RawTowerGeomContainer::ConstRange
Definition at line 28 of file RawTowerGeomContainer.h.
View newest version in sPHENIX GitHub at line 28 of file RawTowerGeomContainer.h
typedef Map::iterator RawTowerGeomContainer::Iterator
Definition at line 25 of file RawTowerGeomContainer.h.
View newest version in sPHENIX GitHub at line 25 of file RawTowerGeomContainer.h
typedef std::map<RawTowerDefs::keytype, RawTowerGeom *> RawTowerGeomContainer::Map
Definition at line 24 of file RawTowerGeomContainer.h.
View newest version in sPHENIX GitHub at line 24 of file RawTowerGeomContainer.h
typedef std::pair<Iterator, Iterator> RawTowerGeomContainer::Range
Definition at line 27 of file RawTowerGeomContainer.h.
View newest version in sPHENIX GitHub at line 27 of file RawTowerGeomContainer.h
Constructor & Destructor Documentation
RawTowerGeomContainer::~RawTowerGeomContainer () inline override
default constructor for ROOT IO
Definition at line 31 of file RawTowerGeomContainer.h.
View newest version in sPHENIX GitHub at line 31 of file RawTowerGeomContainer.h
RawTowerGeomContainer::RawTowerGeomContainer () inline protected
this class is not for use. Base class only
Definition at line 140 of file RawTowerGeomContainer.h.
View newest version in sPHENIX GitHub at line 140 of file RawTowerGeomContainer.h
Member Function Documentation
RawTowerGeomContainer::ConstIterator RawTowerGeomContainer::add_tower_geometry (RawTowerGeom * geo) virtual
go through all towers
Reimplemented in RawTowerGeomContainerv1.
Definition at line 14 of file RawTowerGeomContainer.cc.
View newest version in sPHENIX GitHub at line 14 of file RawTowerGeomContainer.cc
References DummyMap, and PHOOL_VIRTUAL_WARN.
Referenced by PHG4OHCalDetector::AddGeometryNode(), PHG4IHCalDetector::AddGeometryNode(), PHG4OuterHcalDetector::AddGeometryNode(), PHG4InnerHcalDetector::AddGeometryNode(), PHG4SpacalDetector::AddTowerGeometryNode(), CaloGeomMapping::CreateGeomNode(), RawTowerBuilder::CreateNodes(), RawTowerCombiner::CreateNodes(), Prototype2RawTowerBuilder::InitRun(), HcalRawTowerBuilder::InitRun(), and RawTowerBuilderByHitIndex::ReadGeometryFromTable().
virtual RawTowerDefs::CalorimeterId RawTowerGeomContainer::get_calorimeter_id () const inline virtual
Reimplemented in RawTowerGeomContainerv1.
Definition at line 37 of file RawTowerGeomContainer.h.
View newest version in sPHENIX GitHub at line 37 of file RawTowerGeomContainer.h
References RawTowerDefs::NONE, and PHOOL_VIRTUAL_WARN.
Referenced by RawClusterBuilderTemplate::InitRun(), RawClusterBuilderTemplate::process_event(), and DumpRawTowerGeomContainer::process_Node().
RawTowerGeomContainer::Range RawTowerGeomContainer::get_tower_geometries (void) const virtual
return all tower geometries
Reimplemented in RawTowerGeomContainerv1.
Definition at line 20 of file RawTowerGeomContainer.cc.
View newest version in sPHENIX GitHub at line 20 of file RawTowerGeomContainer.cc
References DummyMap, and PHOOL_VIRTUAL_WARN.
Referenced by EventEvaluator::fillOutputNtuples(), RawClusterBuilderTemplate::InitRun(), RawTowerDigitizer::process_event(), DumpRawTowerGeomContainer::process_Node(), and RawTowerBuilderByHitIndex::ReadGeometryFromTable().
virtual Range RawTowerGeomContainer::get_tower_geometries (void) virtual
Reimplemented in RawTowerGeomContainerv1.
virtual RawTowerGeom* RawTowerGeomContainer::get_tower_geometry (RawTowerDefs::keytype) inline virtual
Reimplemented in RawTowerGeomContainerv1.
Definition at line 45 of file RawTowerGeomContainer.h.
View newest version in sPHENIX GitHub at line 45 of file RawTowerGeomContainer.h
References PHOOL_VIRTUAL_WARN.
Referenced by PHG4OHCalDetector::AddGeometryNode(), PHG4IHCalDetector::AddGeometryNode(), PHG4OuterHcalDetector::AddGeometryNode(), PHG4InnerHcalDetector::AddGeometryNode(), DISKinematicsReco::AddGlobalCalorimeterInformation(), PHG4SpacalDetector::AddTowerGeometryNode(), CaloGeomMapping::CreateGeomNode(), RawTowerBuilder::CreateNodes(), RawClusterBuilderTopo::export_clusters(), EpFinderEval::fill_tree(), Calib::fill_tree(), CaloEvaluator::fillOutputNtuples(), sPHAnalysis::Get_CAL_e3x3(), TowerJetInput::get_input(), TrackProjectionTools::getE33Forward(), HcalRawTowerBuilder::InitRun(), RawClusterBuilderGraph::process_event(), RawClusterDeadHotMask::process_event(), TowerInfoDeadHotMask::process_event(), RawTowerDeadTowerInterp::process_event(), RawTowerCalibration::process_event(), ClusterIso::process_event(), SubtractTowers::process_event(), CopyAndSubtractJets::process_event(), RetowerCEMC::process_event(), ParticleFlowReco::process_event(), caloTowerEmbed::process_event(), CaloTriggerSim::process_event(), DetermineTowerBackground::process_event(), TruthCaloTree::process_event(), LiteCaloEval::process_event(), sPHAnalysis::process_event_notracking(), sPHAnalysis_calo::process_event_test(), CaloAna::process_towers(), and pi0EtaByEta::process_towers().
void RawTowerGeomContainer::identify (std::ostream & os = std::cout) const override virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from PHObject.
Reimplemented in RawTowerGeomContainerv1, and RawTowerGeomContainer_Cylinderv1.
Definition at line 9 of file RawTowerGeomContainer.cc.
View newest version in sPHENIX GitHub at line 9 of file RawTowerGeomContainer.cc
Referenced by PHG4OHCalDetector::AddGeometryNode(), PHG4IHCalDetector::AddGeometryNode(), PHG4OuterHcalDetector::AddGeometryNode(), PHG4InnerHcalDetector::AddGeometryNode(), PHG4SpacalDetector::AddTowerGeometryNode(), RawTowerDeadTowerInterp::CreateNodes(), RawTowerBuilder::CreateNodes(), RawTowerCombiner::CreateNodes(), RawTowerCalibration::CreateNodes(), RawTowerDigitizer::CreateNodes(), EMCalCalib::eval_photon_proj(), EMCalAna::eval_trk_proj(), QAG4SimulationCalorimeterSum::eval_trk_proj(), HcalRawTowerBuilder::InitRun(), and DumpRawTowerGeomContainer::process_Node().
virtual void RawTowerGeomContainer::set_calorimeter_id (RawTowerDefs::CalorimeterId) inline virtual
8-bit calorimeter ID
Reimplemented in RawTowerGeomContainerv1.
Definition at line 36 of file RawTowerGeomContainer.h.
View newest version in sPHENIX GitHub at line 36 of file RawTowerGeomContainer.h
References PHOOL_VIRTUAL_WARN.
virtual unsigned int RawTowerGeomContainer::size (void) const inline virtual
Reimplemented in RawTowerGeomContainerv1.
Definition at line 55 of file RawTowerGeomContainer.h.
View newest version in sPHENIX GitHub at line 55 of file RawTowerGeomContainer.h
References PHOOL_VIRTUAL_WARN.
Referenced by QAG4SimulationCalorimeter::process_event_Tower(), DumpRawTowerGeomContainer::process_Node(), and RawTowerBuilderByHitIndex::ReadGeometryFromTable().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/CaloBase/RawTowerGeomContainer.h
coresoftware/blob/master/offline/packages/CaloBase/RawTowerGeomContainer.cc