Analysis Software: Acts::TGeoParser Struct Reference
Acts::TGeoParser Struct Reference
TGeoParser is a helper struct that walks recursively through a TGeometry and selects by string comparison the TGeoNodes that match the criteria.
#include <acts/blob/sPHENIX/Plugins/TGeo/include/Acts/Plugins/TGeo/TGeoParser.hpp>
Classes
struct Options
Nested configuration struct.
struct SelectedNode
struct State
Nested state struct.
Public Types
using ParseRange = std::pair< double, double >
Static Public Member Functions
static void select (State &state, const Options &options, const TGeoMatrix &gmatrix=TGeoIdentity("ID"))
Detailed Description
TGeoParser is a helper struct that walks recursively through a TGeometry and selects by string comparison the TGeoNodes that match the criteria.
It also buils up the global transform for the conversion into an ACTS Surface
Definition at line 33 of file TGeoParser.hpp.
View newest version in sPHENIX GitHub at line 33 of file TGeoParser.hpp
Member Typedef Documentation
using Acts::TGeoParser::ParseRange = std::pair<double, double>
Definition at line 34 of file TGeoParser.hpp.
View newest version in sPHENIX GitHub at line 34 of file TGeoParser.hpp
Member Function Documentation
void Acts::TGeoParser::select (State & state, const Options & options, const TGeoMatrix & gmatrix = TGeoIdentity("ID")) static
The parsing module, it takes the top Volume and recursively steps down
Parameters
state [out] The parsing state configuration, passed through
options [in] The parsing options as requiremed
gmatrix The current built-up transform to global at this depth
Definition at line 23 of file TGeoParser.cpp.
View newest version in sPHENIX GitHub at line 23 of file TGeoParser.cpp
References Acts::VectorHelpers::cast(), check_fpe_masks::check(), dy, dz, Acts::TGeoPrimitivesHelper::makeTransform(), Acts::TGeoPrimitivesHelper::match(), Acts::TGeoParser::State::node, Acts::TGeoParser::State::onBranch, Acts::TGeoParser::Options::parseRanges, Acts::TGeoParser::State::selectedNodes, shape(), t, Acts::TGeoParser::Options::targetNames, Acts::Test::transform, translation(), Acts::TGeoParser::Options::unit, Acts::TGeoParser::State::volume, Acts::TGeoParser::Options::volumeNames, ambiguity_solver_full_chain::x, y, and physmon_track_finding_ttbar::z.
Referenced by Acts::Test::BOOST_AUTO_TEST_CASE(), and Acts::TGeoLayerBuilder::buildLayers().
The documentation for this struct was generated from the following files:
acts/blob/sPHENIX/Plugins/TGeo/include/Acts/Plugins/TGeo/TGeoParser.hpp
acts/blob/sPHENIX/Plugins/TGeo/src/TGeoParser.cpp