Analysis Software: Acts::EDM4hepUtil Namespace Reference
Acts::EDM4hepUtil Namespace Reference
Namespaces
namespace detail
Functions
template<typename track_container_t , typename track_state_container_t , template< typename > class holder_t>
void writeTrack (const Acts::GeometryContext &gctx, Acts::TrackProxy< track_container_t, track_state_container_t, holder_t, true > track, edm4hep::MutableTrack to, double Bz, const Logger &logger=getDummyLogger())
template<typename track_container_t , typename track_state_container_t , template< typename > class holder_t>
void readTrack (const edm4hep::Track &from, Acts::TrackProxy< track_container_t, track_state_container_t, holder_t, false > track, double Bz, const Logger &logger=getDummyLogger())
Variables
static constexpr std::int32_t EDM4HEP_ACTS_POSITION_TYPE = 42
Function Documentation
template<typename track_container_t , typename track_state_container_t , template< typename > class holder_t> void Acts::EDM4hepUtil::readTrack (const edm4hep::Track & from, Acts::TrackProxy< track_container_t, track_state_container_t, holder_t, false > track, double Bz, const Logger & logger = getDummyLogger())
Definition at line 173 of file EDM4hepUtil.hpp.
View newest version in sPHENIX GitHub at line 173 of file EDM4hepUtil.hpp
References ACTS_ERROR, Acts::ACTS_VERBOSE(), Acts::EDM4hepUtil::detail::convertTrackParametersFromEdm4hep(), Acts::EDM4hepUtil::detail::Parameters::covariance, i, mask, Acts::MeasurementFlag, Acts::EDM4hepUtil::detail::Parameters::surface, Acts::EDM4hepUtil::detail::unpackCovariance(), and Acts::EDM4hepUtil::detail::Parameters::values.
Referenced by BOOST_AUTO_TEST_CASE(), and ActsExamples::EDM4hepTrackReader::read().
template<typename track_container_t , typename track_state_container_t , template< typename > class holder_t> void Acts::EDM4hepUtil::writeTrack (const Acts::GeometryContext & gctx, Acts::TrackProxy< track_container_t, track_state_container_t, holder_t, true > track, edm4hep::MutableTrack to, double Bz, const Logger & logger = getDummyLogger())
Definition at line 69 of file EDM4hepUtil.hpp.
View newest version in sPHENIX GitHub at line 69 of file EDM4hepUtil.hpp
References Acts::ACTS_VERBOSE(), Acts::EDM4hepUtil::detail::convertTrackParametersToEdm4hep(), Acts::EDM4hepUtil::detail::Parameters::covariance, Acts::MeasurementFlag, Acts::EDM4hepUtil::detail::packCovariance(), filter::state, Acts::EDM4hepUtil::detail::Parameters::surface, and Acts::EDM4hepUtil::detail::Parameters::values.
Referenced by BOOST_AUTO_TEST_CASE(), and ActsExamples::EDM4hepTrackWriter::writeT().
Variable Documentation
constexpr std::int32_t Acts::EDM4hepUtil::EDM4HEP_ACTS_POSITION_TYPE = 42 static
Definition at line 39 of file EDM4hepUtil.hpp.
View newest version in sPHENIX GitHub at line 39 of file EDM4hepUtil.hpp
Referenced by ActsExamples::EDM4hepUtil::writeMeasurement().