Analysis Software: JetProbeInput Class Reference
JetProbeInput Class Reference
#include <coresoftware/blob/master/offline/packages/jetbase/JetProbeInput.h>
Public Member Functions
JetProbeInput (PHCompositeNode *node=nullptr)
~JetProbeInput () override
void identify (std::ostream &os=std::cout) override
Jet::SRC get_src () override
std::vector< Jet * > get_input (PHCompositeNode *topNode) override
Public Member Functions inherited from JetInput
virtual ~JetInput ()
virtual int Verbosity () const
virtual void Verbosity (int i)
Public Attributes
float phi { -100. }
float eta { -100. }
float pt { -100. }
Additional Inherited Members
Protected Member Functions inherited from JetInput
JetInput ()
Detailed Description
Definition at line 14 of file JetProbeInput.h.
View newest version in sPHENIX GitHub at line 14 of file JetProbeInput.h
Constructor & Destructor Documentation
JetProbeInput::JetProbeInput (PHCompositeNode * node = nullptr)
Definition at line 22 of file JetProbeInput.cc.
View newest version in sPHENIX GitHub at line 22 of file JetProbeInput.cc
References eta, Jet::get_eta(), Jet::get_phi(), Jet::get_pt(), JetContainer::get_UncheckedAt(), phi, PHWHERE, and pt.
JetProbeInput::~JetProbeInput () inline override
Definition at line 18 of file JetProbeInput.h.
View newest version in sPHENIX GitHub at line 18 of file JetProbeInput.h
Member Function Documentation
std::vector< Jet * > JetProbeInput::get_input (PHCompositeNode * topNode) override virtual
Reimplemented from JetInput.
Definition at line 42 of file JetProbeInput.cc.
View newest version in sPHENIX GitHub at line 42 of file JetProbeInput.cc
References Jet::get_e(), Jet::get_px(), Jet::get_py(), Jet::get_pz(), JetContainer::get_UncheckedAt(), PHWHERE, Jet::set_e(), Jet::set_px(), Jet::set_py(), Jet::set_pz(), and JetInput::Verbosity().
Jet::SRC JetProbeInput::get_src () inline override virtual
Reimplemented from JetInput.
Definition at line 24 of file JetProbeInput.h.
View newest version in sPHENIX GitHub at line 24 of file JetProbeInput.h
void JetProbeInput::identify (std::ostream & os = std::cout) override virtual
by default, JetProbeInput process all truth primary particle. However, it can be configured to read only one or more embedded stream via add_embedding_flag()
Reimplemented from JetInput.
Definition at line 37 of file JetProbeInput.cc.
View newest version in sPHENIX GitHub at line 37 of file JetProbeInput.cc
Member Data Documentation
float JetProbeInput::eta { -100. }
Definition at line 30 of file JetProbeInput.h.
View newest version in sPHENIX GitHub at line 30 of file JetProbeInput.h
Referenced by JetProbeInput().
float JetProbeInput::phi { -100. }
Definition at line 29 of file JetProbeInput.h.
View newest version in sPHENIX GitHub at line 29 of file JetProbeInput.h
Referenced by JetProbeInput().
float JetProbeInput::pt { -100. }
Definition at line 31 of file JetProbeInput.h.
View newest version in sPHENIX GitHub at line 31 of file JetProbeInput.h
Referenced by JetProbeInput().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/jetbase/JetProbeInput.h
coresoftware/blob/master/offline/packages/jetbase/JetProbeInput.cc