Analysis Software: MultiArray< T > Class Template Reference
MultiArray< T > Class Template Reference
#include <coresoftware/blob/master/calibrations/tpc/generator/AnnularFieldSim.h>
Public Member Functions
MultiArray (int a=0, int b=0, int c=0, int d=0, int e=0, int f=0)
MultiArray (const MultiArray &)=delete
delete copy ctor and assignment opertor (cppcheck)
MultiArray & operator= (const MultiArray &)=delete
~MultiArray ()
void Add (int a, int b, int c, T in)
void Add (int a, int b, int c, int d, int e, int f, T in)
T Get (int a=0, int b=0, int c=0, int d=0, int e=0, int f=0)
T * GetPtr (int a=0, int b=0, int c=0, int d=0, int e=0, int f=0)
T * GetFlat (int a=0)
int Length ()
void Set (int a, int b, int c, T in)
void Set (int a, int b, int c, int d, int e, int f, T in)
void SetAll (T in)
Public Attributes
int dim
int n [6]
long int length
T * field
Static Public Attributes
static const int MAX_DIM = 6
Detailed Description
template<class T>
class MultiArray< T >
Definition at line 15 of file AnnularFieldSim.h.
View newest version in sPHENIX GitHub at line 15 of file AnnularFieldSim.h
Constructor & Destructor Documentation
template<class T> MultiArray< T >::MultiArray (int a = 0, int b = 0, int c = 0, int d = 0, int e = 0, int f = 0) inline
Definition at line 21 of file MultiArray.h.
View newest version in sPHENIX GitHub at line 21 of file MultiArray.h
template<class T> MultiArray< T >::MultiArray (const MultiArray< T > &) explicit delete
delete copy ctor and assignment opertor (cppcheck)
template<class T> MultiArray< T >::~MultiArray () inline
Definition at line 51 of file MultiArray.h.
View newest version in sPHENIX GitHub at line 51 of file MultiArray.h
Member Function Documentation
template<class T> void MultiArray< T >::Add (int a, int b, int c, T in) inline
Definition at line 56 of file MultiArray.h.
View newest version in sPHENIX GitHub at line 56 of file MultiArray.h
Referenced by MultiArray< TVector3 >::Add(), ChargeMapReader::AddChargeInBin(), AnnularFieldSim::load_analytic_spacecharge(), and AnnularFieldSim::sum_local_field_at().
template<class T> void MultiArray< T >::Add (int a, int b, int c, int d, int e, int f, T in) inline
Definition at line 62 of file MultiArray.h.
View newest version in sPHENIX GitHub at line 62 of file MultiArray.h
template<class T> T MultiArray< T >::Get (int a = 0, int b = 0, int c = 0, int d = 0, int e = 0, int f = 0) inline
Definition at line 80 of file MultiArray.h.
View newest version in sPHENIX GitHub at line 80 of file MultiArray.h
Referenced by AnnularFieldSim::analyticFieldIntegral(), AnnularFieldSim::fieldIntegral(), ChargeMapReader::FillChargeHistogram(), AnnularFieldSim::GetBFieldAt(), ChargeMapReader::GetChargeInBin(), AnnularFieldSim::GetFieldAt(), AnnularFieldSim::interpolatedFieldIntegral(), AnnularFieldSim::populate_highres_lookup(), AnnularFieldSim::save_phislice_lookup(), AnnularFieldSim::sum_field_at(), AnnularFieldSim::sum_full3d_field_at(), AnnularFieldSim::sum_local_field_at(), AnnularFieldSim::sum_nonlocal_field_at(), and AnnularFieldSim::sum_phislice_field_at().
template<class T> T* MultiArray< T >::GetFlat (int a = 0) inline
Definition at line 119 of file MultiArray.h.
View newest version in sPHENIX GitHub at line 119 of file MultiArray.h
Referenced by AnnularFieldSim::AnnularFieldSim(), AnnularFieldSim::load_analytic_spacecharge(), AnnularFieldSim::setFlatFields(), and AnnularFieldSim::sum_local_field_at().
template<class T> T* MultiArray< T >::GetPtr (int a = 0, int b = 0, int c = 0, int d = 0, int e = 0, int f = 0) inline
Definition at line 102 of file MultiArray.h.
View newest version in sPHENIX GitHub at line 102 of file MultiArray.h
template<class T> int MultiArray< T >::Length () inline
Definition at line 129 of file MultiArray.h.
View newest version in sPHENIX GitHub at line 129 of file MultiArray.h
Referenced by AnnularFieldSim::AnnularFieldSim(), AnnularFieldSim::load_analytic_spacecharge(), AnnularFieldSim::setFlatFields(), and AnnularFieldSim::sum_local_field_at().
template<class T> MultiArray& MultiArray< T >::operator= (const MultiArray< T > &) delete
template<class T> void MultiArray< T >::Set (int a, int b, int c, T in) inline
Definition at line 134 of file MultiArray.h.
View newest version in sPHENIX GitHub at line 134 of file MultiArray.h
Referenced by AnnularFieldSim::load_phislice_lookup(), AnnularFieldSim::populate_fieldmap(), AnnularFieldSim::populate_full3d_lookup(), AnnularFieldSim::populate_highres_lookup(), AnnularFieldSim::populate_lowres_lookup(), AnnularFieldSim::populate_phislice_lookup(), ChargeMapReader::RegenerateCharge(), MultiArray< TVector3 >::Set(), and ChargeMapReader::SetChargeInBin().
template<class T> void MultiArray< T >::Set (int a, int b, int c, int d, int e, int f, T in) inline
Definition at line 140 of file MultiArray.h.
View newest version in sPHENIX GitHub at line 140 of file MultiArray.h
template<class T> void MultiArray< T >::SetAll (T in) inline
Definition at line 158 of file MultiArray.h.
View newest version in sPHENIX GitHub at line 158 of file MultiArray.h
Referenced by ChargeMapReader::RegenerateCharge(), ChargeMapReader::SetOutputBins(), ChargeMapReader::SetOutputBounds(), and ChargeMapReader::SetOutputParameters().
Member Data Documentation
template<class T> int MultiArray< T >::dim
Definition at line 16 of file MultiArray.h.
View newest version in sPHENIX GitHub at line 16 of file MultiArray.h
Referenced by MultiArray< TVector3 >::Add(), MultiArray< TVector3 >::Get(), MultiArray< TVector3 >::GetPtr(), MultiArray< TVector3 >::MultiArray(), and MultiArray< TVector3 >::Set().
template<class T> T* MultiArray< T >::field
Definition at line 19 of file MultiArray.h.
View newest version in sPHENIX GitHub at line 19 of file MultiArray.h
Referenced by MultiArray< TVector3 >::Add(), MultiArray< TVector3 >::Get(), MultiArray< TVector3 >::GetFlat(), MultiArray< TVector3 >::GetPtr(), MultiArray< TVector3 >::MultiArray(), MultiArray< TVector3 >::Set(), MultiArray< TVector3 >::SetAll(), and MultiArray< TVector3 >::~MultiArray().
template<class T> long int MultiArray< T >::length
Definition at line 18 of file MultiArray.h.
View newest version in sPHENIX GitHub at line 18 of file MultiArray.h
Referenced by MultiArray< TVector3 >::GetFlat(), MultiArray< TVector3 >::Length(), MultiArray< TVector3 >::MultiArray(), and MultiArray< TVector3 >::SetAll().
template<class T> const int MultiArray< T >::MAX_DIM = 6 static
Definition at line 15 of file MultiArray.h.
View newest version in sPHENIX GitHub at line 15 of file MultiArray.h
Referenced by MultiArray< TVector3 >::MultiArray().
template<class T> int MultiArray< T >::n[6]
Definition at line 17 of file MultiArray.h.
View newest version in sPHENIX GitHub at line 17 of file MultiArray.h
Referenced by MultiArray< TVector3 >::Add(), MultiArray< TVector3 >::Get(), MultiArray< TVector3 >::GetPtr(), MultiArray< TVector3 >::MultiArray(), and MultiArray< TVector3 >::Set().
The documentation for this class was generated from the following files:
coresoftware/blob/master/calibrations/tpc/generator/AnnularFieldSim.h
coresoftware/blob/master/calibrations/tpc/generator/MultiArray.h