Analysis Software: Acts::ConvexPolygonBoundsBase Class Reference
Acts::ConvexPolygonBoundsBase Class Reference
base class for convex polygon bounds
#include <acts/blob/sPHENIX/Core/include/Acts/Surfaces/ConvexPolygonBounds.hpp>
Public Member Functions
std::ostream & toStream (std::ostream &sl) const final
std::vector< double > values () const final
Public Member Functions inherited from Acts::PlanarBounds
virtual std::vector< Vector2 > vertices (unsigned int lseg=1) const =0
virtual const RectangleBounds & boundingBox () const =0
Public Member Functions inherited from Acts::SurfaceBounds
virtual ~SurfaceBounds ()=default
virtual BoundsType type () const =0
virtual bool inside (const Vector2 &lposition, const BoundaryCheck &bcheck) const =0
Static Protected Member Functions
template<typename coll_t >
static RectangleBounds makeBoundingBox (const coll_t &vertices)
template<typename coll_t >
static void convex_impl (const coll_t &vertices) noexcept(false)
Additional Inherited Members
Public Types inherited from Acts::SurfaceBounds
enum BoundsType : int {
eCone = 0, eCylinder = 1, eDiamond = 2, eDisc = 3,
eEllipse = 4, eLine = 5, eRectangle = 6, eTrapezoid = 7,
eTriangle = 8, eDiscTrapezoid = 9, eConvexPolygon = 10, eAnnulus = 11,
eBoundless = 12, eOther = 13
}
Detailed Description
base class for convex polygon bounds
This class serves as a base class for the actual bounds class. The only deriving type is the templated ConvexPolygonBounds.
Definition at line 33 of file ConvexPolygonBounds.hpp.
View newest version in sPHENIX GitHub at line 33 of file ConvexPolygonBounds.hpp
Member Function Documentation
template<typename coll_t > void Acts::ConvexPolygonBoundsBase::convex_impl (const coll_t & vertices) static protected noexcept
Calculates whether a set of vertices forms a convex polygon. This is generic over the number of vertices, so it's factored out of the concrete classes and into this base class.
Parameters
vertices A collection of vertices. throws a logic error if this is not the case
Definition at line 12 of file ConvexPolygonBounds.ipp.
View newest version in sPHENIX GitHub at line 12 of file ConvexPolygonBounds.ipp
References KFPMath::a, KFPMath::b, Acts::PhysicalConstants::c, i, j, k, N, check_smearing_config::ref, value, and ActsExamples::HepMC3Event::vertices().
template<typename coll_t > Acts::RectangleBounds Acts::ConvexPolygonBoundsBase::makeBoundingBox (const coll_t & vertices) static protected
Return a rectangle bounds instance that encloses a set of vertices.
Parameters
vertices A collection of vertices to enclose.
Returns
Enclosing rectangle.
Definition at line 52 of file ConvexPolygonBounds.ipp.
View newest version in sPHENIX GitHub at line 52 of file ConvexPolygonBounds.ipp
References i.
std::ostream & Acts::ConvexPolygonBoundsBase::toStream (std::ostream & sl) const final virtual
Output Method for std::ostream
Parameters
sl is the ostream to be written into
Implements Acts::SurfaceBounds.
Definition at line 14 of file ConvexPolygonBounds.cpp.
View newest version in sPHENIX GitHub at line 14 of file ConvexPolygonBounds.cpp
References i, and Acts::PlanarBounds::vertices().
std::vector< double > Acts::ConvexPolygonBoundsBase::values () const final virtual
Return the bound values as dynamically sized vector
Returns
this returns a copy of the internal values
Implements Acts::SurfaceBounds.
Definition at line 28 of file ConvexPolygonBounds.cpp.
View newest version in sPHENIX GitHub at line 28 of file ConvexPolygonBounds.cpp
References Acts::Test::values, and ActsExamples::HepMC3Event::vertices().
Referenced by Acts::Test::BOOST_AUTO_TEST_CASE().
The documentation for this class was generated from the following files:
acts/blob/sPHENIX/Core/include/Acts/Surfaces/ConvexPolygonBounds.hpp
acts/blob/sPHENIX/Core/include/Acts/Surfaces/ConvexPolygonBounds.ipp
acts/blob/sPHENIX/Core/src/Surfaces/ConvexPolygonBounds.cpp