Analysis Software: Acts::CuboidVolumeBuilder::SurfaceConfig Struct Reference
Acts::CuboidVolumeBuilder::SurfaceConfig Struct Reference
This struct stores the data for the construction of a single PlaneSurface.
#include <acts/blob/sPHENIX/Core/include/Acts/Geometry/CuboidVolumeBuilder.hpp>
Public Attributes
Vector3 position
RotationMatrix3 rotation = RotationMatrix3::Identity()
std::shared_ptr< const
RectangleBounds > rBounds = nullptr
std::shared_ptr< const
ISurfaceMaterial > surMat = nullptr
double thickness = 0.
std::function
< DetectorElementBase *(const
Transform3 &, std::shared_ptr
< const RectangleBounds >
, double)> detElementConstructor
Detailed Description
This struct stores the data for the construction of a single PlaneSurface.
Definition at line 46 of file CuboidVolumeBuilder.hpp.
View newest version in sPHENIX GitHub at line 46 of file CuboidVolumeBuilder.hpp
Member Data Documentation
std::function<DetectorElementBase*(const Transform3&, std::shared_ptr<const RectangleBounds>, double)> Acts::CuboidVolumeBuilder::SurfaceConfig::detElementConstructor
Definition at line 61 of file CuboidVolumeBuilder.hpp.
View newest version in sPHENIX GitHub at line 61 of file CuboidVolumeBuilder.hpp
Referenced by Acts::Test::BOOST_AUTO_TEST_CASE(), Acts::CuboidVolumeBuilder::buildSurface(), Acts::EventDataView3DTest::createDetector(), and Acts::Test::makeToyDetector().
Vector3 Acts::CuboidVolumeBuilder::SurfaceConfig::position
Definition at line 48 of file CuboidVolumeBuilder.hpp.
View newest version in sPHENIX GitHub at line 48 of file CuboidVolumeBuilder.hpp
Referenced by Acts::Test::BOOST_AUTO_TEST_CASE(), Acts::CuboidVolumeBuilder::buildSurface(), Acts::CuboidVolumeBuilder::buildVolume(), Acts::EventDataView3DTest::createDetector(), and Acts::Test::makeToyDetector().
std::shared_ptr<const RectangleBounds> Acts::CuboidVolumeBuilder::SurfaceConfig::rBounds = nullptr
Definition at line 52 of file CuboidVolumeBuilder.hpp.
View newest version in sPHENIX GitHub at line 52 of file CuboidVolumeBuilder.hpp
Referenced by Acts::Test::BOOST_AUTO_TEST_CASE(), Acts::CuboidVolumeBuilder::buildSurface(), Acts::CuboidVolumeBuilder::buildVolume(), Acts::EventDataView3DTest::createDetector(), and Acts::Test::makeToyDetector().
RotationMatrix3 Acts::CuboidVolumeBuilder::SurfaceConfig::rotation = RotationMatrix3::Identity()
Definition at line 50 of file CuboidVolumeBuilder.hpp.
View newest version in sPHENIX GitHub at line 50 of file CuboidVolumeBuilder.hpp
Referenced by Acts::Test::BOOST_AUTO_TEST_CASE(), Acts::CuboidVolumeBuilder::buildSurface(), Acts::CuboidVolumeBuilder::buildVolume(), Acts::EventDataView3DTest::createDetector(), and Acts::Test::makeToyDetector().
std::shared_ptr<const ISurfaceMaterial> Acts::CuboidVolumeBuilder::SurfaceConfig::surMat = nullptr
Definition at line 54 of file CuboidVolumeBuilder.hpp.
View newest version in sPHENIX GitHub at line 54 of file CuboidVolumeBuilder.hpp
Referenced by Acts::Test::BOOST_AUTO_TEST_CASE(), Acts::CuboidVolumeBuilder::buildSurface(), Acts::EventDataView3DTest::createDetector(), and Acts::Test::makeToyDetector().
double Acts::CuboidVolumeBuilder::SurfaceConfig::thickness = 0.
Definition at line 56 of file CuboidVolumeBuilder.hpp.
View newest version in sPHENIX GitHub at line 56 of file CuboidVolumeBuilder.hpp
Referenced by Acts::Test::BOOST_AUTO_TEST_CASE(), Acts::CuboidVolumeBuilder::buildSurface(), Acts::EventDataView3DTest::createDetector(), and Acts::Test::makeToyDetector().
The documentation for this struct was generated from the following file:
acts/blob/sPHENIX/Core/include/Acts/Geometry/CuboidVolumeBuilder.hpp