Analysis Software: PHActsSiliconSeeding Class Reference
PHActsSiliconSeeding Class Reference
#include <coresoftware/blob/master/offline/packages/trackreco/PHActsSiliconSeeding.h>
Public Member Functions
PHActsSiliconSeeding (const std::string &name="PHActsSiliconSeeding")
int Init (PHCompositeNode *topNode) override
int InitRun (PHCompositeNode *topNode) override
int process_event (PHCompositeNode *topNode) override
int End (PHCompositeNode *topNode) override
Called at the end of all processing.
void setunc (float unc)
void useTruthClusters (bool useTruthClusters)
Set seeding with truth clusters.
void seedAnalysis (bool seedAnalysis)
Output some diagnostic histograms.
void setRPhiSearchWindow (const float win)
void cleanSeeds (bool cleanSeeds)
void rMax (const float rMax)
void rMin (const float rMin)
void zMax (const float zMax)
void zMin (const float zMin)
void deltaRMax (const float deltaRMax)
void cotThetaMax (const float cotThetaMax)
void gridFactor (const float gridFactor)
void sigmaScattering (const float sigma)
void maxPtScattering (const float pt)
void sigmaError (const float sigma)
void zalign (const float z)
void ralign (const float r)
void tolerance (const float tolerance)
void helixcut (const float cut)
void largeGridSpacing (const bool spacing)
void set_track_map_name (const std::string &map_name)
void iteration (int iter)
void searchInIntt ()
Public Member Functions inherited from SubsysReco
~SubsysReco () override
virtual int EndRun (const int)
Called at the end of each run.
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
void Print (const std::string &="ALL") const override
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Private Member Functions
int getNodes (PHCompositeNode *topNode)
int createNodes (PHCompositeNode *topNode)
GridSeeds runSeeder (std::vector< const SpacePoint * > &spVec)
void configureSeeder ()
void configureSPGrid ()
Acts::SeedFilterConfig configureSeedFilter ()
void makeSvtxTracks (GridSeeds &seedVector)
Take final seeds and fill the TrackSeedContainer.
SpacePointPtr makeSpacePoint (const Surface &surf, const TrkrDefs::cluskey, TrkrCluster *clus)
Create a seeding space point out of an Acts::SourceLink.
std::vector< const SpacePoint * > getSiliconSpacePoints (Acts::Extent &rRangeSPExtent)
Get all space points for the seeder.
void printSeedConfigs (Acts::SeedFilterConfig &sfconfig)
std::vector< TrkrDefs::cluskey > findInttMatches (std::vector< Acts::Vector3 > &clusters, TrackSeed &seed)
std::vector< TrkrDefs::cluskey > matchInttClusters (std::vector< Acts::Vector3 > &clusters, TrackSeed &seed, const double xProj[], const double yProj[], const double zProj[])
void createHistograms ()
void writeHistograms ()
double normPhi2Pi (const double phi)
Private Attributes
ActsGeometry * m_tGeometry = nullptr
TrackSeedContainer * m_seedContainer = nullptr
TrkrClusterContainer * m_clusterMap = nullptr
PHG4CylinderGeomContainer * m_geomContainerIntt = nullptr
Acts::SeedFinderConfig
< SpacePoint > m_seedFinderCfg
Configuration classes for Acts seeding.
Acts::SpacePointGridConfig m_gridCfg
Acts::SpacePointGridOptions m_gridOptions
Acts::SeedFinderOptions m_seedFinderOptions
bool m_searchInIntt = false
boolean whether or not to include the intt in the acts search windows
float m_minSeedPt = 100 * Acts::UnitConstants::MeV
float m_uncfactor = 3.18
int m_maxSeedsPerSpM = 1
float m_rMax = 200. * Acts::UnitConstants::mm
Limiting location of measurements (e.g. detector constraints)
float m_rMin = 23. * Acts::UnitConstants::mm
float m_zMax = 500. * Acts::UnitConstants::mm
float m_zMin = -500. * Acts::UnitConstants::mm
float m_helixcut = 1
misalignment parameters
float m_tolerance = 1.1 * Acts::UnitConstants::mm
float m_ralign = 0
float m_zalign = 0
float m_maxPtScattering = 10
float m_sigmaScattering = 5.
float m_sigmaError = 5
float m_gridFactor = 2.3809
float m_deltaRMax = 15 * Acts::UnitConstants::mm
max distance between two measurements in one seed
float m_deltaRMin = 1. * Acts::UnitConstants::mm
float m_cotThetaMax = 2.9
Cot of maximum theta angle.
float m_impactMax = 20 * Acts::UnitConstants::mm
Maximum impact parameter allowed in mm.
int m_numPhiNeighbors = 1
float m_bField = 1.4 * Acts::UnitConstants::T
std::vector< std::pair< int,
int > > zBinNeighborsTop
std::vector< std::pair< int,
int > > zBinNeighborsBottom
int nphineighbors = 1
std::shared_ptr< const
Acts::BinFinder< SpacePoint > > m_bottomBinFinder
std::shared_ptr< const
Acts::BinFinder< SpacePoint > > m_topBinFinder
int m_event = 0
double m_maxSeedPCA = 2.
Maximum allowed transverse PCA for seed, cm.
double m_nInttLayerRadii [m_nInttLayers] = {0}
double m_rPhiSearchWin = 0.1
Search window for phi to match intt clusters in cm.
bool m_useTruthClusters = false
Whether or not to use truth clusters in hit lookup.
bool m_cleanSeeds = false
int m_nBadUpdates = 0
int m_nBadInitialFits = 0
TrkrClusterIterationMapv1 * _iteration_map = nullptr
int m_nIteration = 0
std::string _track_map_name = "SiliconTrackSeedContainer"
ClusterErrorPara _ClusErrPara
bool m_seedAnalysis = false
TFile * m_file = nullptr
TH2 * h_nInttProj = nullptr
TH1 * h_nMvtxHits = nullptr
TH1 * h_nInttHits = nullptr
TH1 * h_nMatchedClusters = nullptr
TH2 * h_nHits = nullptr
TH1 * h_nSeeds = nullptr
TH1 * h_nActsSeeds = nullptr
TH1 * h_nTotSeeds = nullptr
TH1 * h_nInputMeas = nullptr
TH1 * h_nInputMvtxMeas = nullptr
TH1 * h_nInputInttMeas = nullptr
TH2 * h_hits = nullptr
TH2 * h_zhits = nullptr
TH2 * h_projHits = nullptr
TH2 * h_zprojHits = nullptr
TH2 * h_resids = nullptr
Static Private Attributes
static const unsigned int m_nInttLayers = 4
Doesn't change, we are building the INTT this way.
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = std::numeric_limits<int>::max() - 10
}
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Detailed Description
This class runs the Acts seeder over the MVTX measurements to create track stubs for the rest of the stub matching pattern recognition. The module also projects the MVTX stubs to the INTT to find possible matches in the INTT to the MVTX triplet.
Definition at line 41 of file PHActsSiliconSeeding.h.
View newest version in sPHENIX GitHub at line 41 of file PHActsSiliconSeeding.h
Constructor & Destructor Documentation
PHActsSiliconSeeding::PHActsSiliconSeeding (const std::string & name = "PHActsSiliconSeeding")
Definition at line 51 of file PHActsSiliconSeeding.cc.
View newest version in sPHENIX GitHub at line 51 of file PHActsSiliconSeeding.cc
Member Function Documentation
void PHActsSiliconSeeding::cleanSeeds (bool cleanSeeds) inline
For each MVTX+INTT seed, take the best INTT hits and form 1 silicon seed per MVTX seed
Definition at line 69 of file PHActsSiliconSeeding.h.
View newest version in sPHENIX GitHub at line 69 of file PHActsSiliconSeeding.h
References cleanSeeds(), and m_cleanSeeds.
Referenced by cleanSeeds().
void PHActsSiliconSeeding::configureSeeder () private
Configure the seeding parameters for Acts. There are a number of tunable parameters for the seeder here
these are default values that used to be set in Acts
Limiting location of measurements (e.g. detector constraints)
Min/max distance between two measurements in one seed
Limiting collision region in z
Average radiation length traversed per seed
Maximum impact parameter must be smaller than rMin
Configurations for dealing with misalignment
Definition at line 834 of file PHActsSiliconSeeding.cc.
View newest version in sPHENIX GitHub at line 834 of file PHActsSiliconSeeding.cc
References Acts::SeedFinderOptions::bFieldInZ, Acts::SeedFinderOptions::calculateDerivedQuantities(), Acts::UnitConstants::cm, m_bField, m_cotThetaMax, m_deltaRMax, m_deltaRMin, m_helixcut, m_impactMax, m_maxPtScattering, m_maxSeedsPerSpM, m_minSeedPt, m_ralign, m_rMax, m_rMin, m_seedFinderCfg, m_seedFinderOptions, m_sigmaError, m_sigmaScattering, m_tolerance, m_zalign, m_zMax, m_zMin, Acts::UnitConstants::mm, and Acts::SeedFinderOptions::toInternalUnits().
Referenced by Init().
Acts::SeedFilterConfig PHActsSiliconSeeding::configureSeedFilter () private
Definition at line 827 of file PHActsSiliconSeeding.cc.
View newest version in sPHENIX GitHub at line 827 of file PHActsSiliconSeeding.cc
References filter::config, m_maxSeedsPerSpM, and Acts::SeedFilterConfig::maxSeedsPerSpM.
Referenced by Init().
void PHActsSiliconSeeding::configureSPGrid () private
Definition at line 811 of file PHActsSiliconSeeding.cc.
View newest version in sPHENIX GitHub at line 811 of file PHActsSiliconSeeding.cc
References Acts::SpacePointGridOptions::bFieldInZ, Acts::SpacePointGridConfig::cotThetaMax, Acts::SpacePointGridConfig::deltaRMax, Acts::SpacePointGridConfig::impactMax, m_bField, m_cotThetaMax, m_deltaRMax, m_gridCfg, m_gridFactor, m_gridOptions, m_impactMax, m_minSeedPt, m_numPhiNeighbors, m_rMax, m_zMax, m_zMin, Acts::SpacePointGridConfig::minPt, Acts::SpacePointGridConfig::phiBinDeflectionCoverage, Acts::SpacePointGridConfig::rMax, Acts::SpacePointGridConfig::toInternalUnits(), Acts::SpacePointGridOptions::toInternalUnits(), Acts::SpacePointGridConfig::zMax, and Acts::SpacePointGridConfig::zMin.
Referenced by Init().
void PHActsSiliconSeeding::cotThetaMax (const float cotThetaMax) inline
Definition at line 82 of file PHActsSiliconSeeding.h.
View newest version in sPHENIX GitHub at line 82 of file PHActsSiliconSeeding.h
References cotThetaMax(), and m_cotThetaMax.
Referenced by cotThetaMax().
void PHActsSiliconSeeding::createHistograms () private
Definition at line 973 of file PHActsSiliconSeeding.cc.
View newest version in sPHENIX GitHub at line 973 of file PHActsSiliconSeeding.cc
References h_hits, h_nActsSeeds, h_nHits, h_nInputInttMeas, h_nInputMeas, h_nInputMvtxMeas, h_nInttHits, h_nInttProj, h_nMatchedClusters, h_nMvtxHits, h_nSeeds, h_nTotSeeds, h_projHits, h_resids, h_zhits, and h_zprojHits.
Referenced by Init().
int PHActsSiliconSeeding::createNodes (PHCompositeNode * topNode) private
Definition at line 917 of file PHActsSiliconSeeding.cc.
View newest version in sPHENIX GitHub at line 917 of file PHActsSiliconSeeding.cc
References _track_map_name, PHCompositeNode::addNode(), Fun4AllReturnCodes::EVENT_OK, PHNodeIterator::findFirst(), and m_seedContainer.
Referenced by InitRun().
void PHActsSiliconSeeding::deltaRMax (const float deltaRMax) inline
Definition at line 80 of file PHActsSiliconSeeding.h.
View newest version in sPHENIX GitHub at line 80 of file PHActsSiliconSeeding.h
References deltaRMax(), and m_deltaRMax.
Referenced by deltaRMax().
int PHActsSiliconSeeding::End (PHCompositeNode *) override virtual
Called at the end of all processing.
Reimplemented from SubsysReco.
Definition at line 165 of file PHActsSiliconSeeding.cc.
View newest version in sPHENIX GitHub at line 165 of file PHActsSiliconSeeding.cc
References Fun4AllReturnCodes::EVENT_OK, m_nBadInitialFits, m_nBadUpdates, m_seedAnalysis, Fun4AllBase::Verbosity(), and writeHistograms().
std::vector< TrkrDefs::cluskey > PHActsSiliconSeeding::findInttMatches (std::vector< Acts::Vector3 > & clusters, TrackSeed & seed) private
Projects circle fit to INTT radii to find possible INTT clusters belonging to MVTX track stub
Diagnostic
Project the seed to the INTT to find matches
If there are no real solutions to the intersection, skip
Figure out which solution is correct based on the position of the last layer in the mvtx seed
Definition at line 420 of file PHActsSiliconSeeding.cc.
View newest version in sPHENIX GitHub at line 420 of file PHActsSiliconSeeding.cc
References TrackFitUtils::circle_circle_intersection(), TrackSeed::get_qOverR(), TrackSeed::get_slope(), TrackSeed::get_X0(), TrackSeed::get_Y0(), TrackSeed::get_Z0(), h_hits, h_projHits, h_zhits, h_zprojHits, layer, Acts::UnitConstants::m, m_nInttLayerRadii, m_nInttLayers, m_seedAnalysis, matchInttClusters(), Acts::IntegrationTest::R, square(), Fun4AllBase::Verbosity(), X0, and Y0.
Referenced by makeSvtxTracks().
int PHActsSiliconSeeding::getNodes (PHCompositeNode * topNode) private
Definition at line 883 of file PHActsSiliconSeeding.cc.
View newest version in sPHENIX GitHub at line 883 of file PHActsSiliconSeeding.cc
References Fun4AllReturnCodes::ABORTEVENT, Fun4AllReturnCodes::EVENT_OK, m_clusterMap, m_geomContainerIntt, m_tGeometry, m_useTruthClusters, and PHWHERE.
Referenced by InitRun().
std::vector< const SpacePoint * > PHActsSiliconSeeding::getSiliconSpacePoints (Acts::Extent & rRangeSPExtent) private
Get all space points for the seeder.
Definition at line 755 of file PHActsSiliconSeeding.cc.
View newest version in sPHENIX GitHub at line 755 of file PHActsSiliconSeeding.cc
References _iteration_map, Acts::Extent::extend(), TrkrClusterContainer::getClusters(), TrkrDefs::getHitSetKeyFromClusKey(), TrkrClusterContainer::getHitSetKeys(), TrkrClusterIterationMapv1::getIteration(), ActsSurfaceMaps::getSiliconSurface(), h_nInputMvtxMeas, TrkrDefs::inttId, m_clusterMap, m_nIteration, m_searchInIntt, m_seedAnalysis, m_tGeometry, makeSpacePoint(), ActsGeometry::maps(), TrkrDefs::mvtxId, writeMapConfig::surface, and Fun4AllBase::Verbosity().
Referenced by runSeeder().
void PHActsSiliconSeeding::gridFactor (const float gridFactor) inline
Definition at line 84 of file PHActsSiliconSeeding.h.
View newest version in sPHENIX GitHub at line 84 of file PHActsSiliconSeeding.h
References gridFactor(), and m_gridFactor.
Referenced by gridFactor().
void PHActsSiliconSeeding::helixcut (const float cut) inline
Definition at line 98 of file PHActsSiliconSeeding.h.
View newest version in sPHENIX GitHub at line 98 of file PHActsSiliconSeeding.h
References m_helixcut.
int PHActsSiliconSeeding::Init (PHCompositeNode *) override virtual
Called during initialization. Typically this is where you can book histograms, and e.g. register them to Fun4AllServer (so they can be output to file using Fun4AllServer::dumpHistos() method).
Reimplemented from SubsysReco.
Definition at line 56 of file PHActsSiliconSeeding.cc.
View newest version in sPHENIX GitHub at line 56 of file PHActsSiliconSeeding.cc
References configureSeeder(), configureSeedFilter(), configureSPGrid(), createHistograms(), Fun4AllReturnCodes::EVENT_OK, m_bottomBinFinder, m_file, m_seedAnalysis, m_seedFinderCfg, m_topBinFinder, Fun4AllBase::Name(), nphineighbors, printSeedConfigs(), Acts::SeedFilterConfig::toInternalUnits(), Fun4AllBase::Verbosity(), zBinNeighborsBottom, and zBinNeighborsTop.
int PHActsSiliconSeeding::InitRun (PHCompositeNode *) override virtual
Called for first event when run number is known. Typically this is where you may want to fetch data from database, because you know the run number.
Reimplemented from SubsysReco.
Definition at line 85 of file PHActsSiliconSeeding.cc.
View newest version in sPHENIX GitHub at line 85 of file PHActsSiliconSeeding.cc
References Fun4AllReturnCodes::ABORTEVENT, createNodes(), Fun4AllReturnCodes::EVENT_OK, PHG4CylinderGeomContainer::get_begin_end(), getNodes(), i, m_geomContainerIntt, and m_nInttLayerRadii.
void PHActsSiliconSeeding::iteration (int iter) inline
Definition at line 107 of file PHActsSiliconSeeding.h.
View newest version in sPHENIX GitHub at line 107 of file PHActsSiliconSeeding.h
References m_nIteration.
Referenced by Tracking_Reco_TrackSeed_pass1().
void PHActsSiliconSeeding::largeGridSpacing (const bool spacing)
A function to run the seeder with large (true) or small (false) grid spacing
Definition at line 1010 of file PHActsSiliconSeeding.cc.
View newest version in sPHENIX GitHub at line 1010 of file PHActsSiliconSeeding.cc
References m_cotThetaMax, m_gridFactor, m_maxSeedPCA, and m_rMax.
SpacePointPtr PHActsSiliconSeeding::makeSpacePoint (const Surface & surf, const TrkrDefs::cluskey key, TrkrCluster * clus) private
Create a seeding space point out of an Acts::SourceLink.
The space point requires only the variance of the transverse and longitudinal position. Reduce computations by transforming the covariance directly from local to r/z.
compute Jacobian from global coordinates to r/z
    r = sqrt(x + y)
dr/d{x,y} = (1 / sqrt(x + y)) * 2 * {x,y} = 2 * {x,y} / r dz/dz = 1
Definition at line 687 of file PHActsSiliconSeeding.cc.
View newest version in sPHENIX GitHub at line 687 of file PHActsSiliconSeeding.cc
References Acts::UnitConstants::cm, Acts::UnitConstants::cm2, Acts::ePos0, Acts::ePos1, Acts::ePos2, ActsGeometry::geometry(), ActsTrackingGeometry::getGeoContext(), TrkrCluster::getLocalX(), TrkrCluster::getLocalY(), TrkrCluster::getRPhiError(), TrkrCluster::getZError(), m_tGeometry, m_uncfactor, physmon_track_finding_ttbar::r, Fun4AllBase::Verbosity(), ambiguity_solver_full_chain::x, y, and physmon_track_finding_ttbar::z.
Referenced by getSiliconSpacePoints().
void PHActsSiliconSeeding::makeSvtxTracks (GridSeeds & seedVector) private
Take final seeds and fill the TrackSeedContainer.
Loop over grid volumes
Loop over actual seeds in this grid volume
if acts found a triplet in the INTT only it is likely a bad seed
Project to INTT and find matches
Add possible matches to cluster list to be parsed when Svtx tracks are made
Circle fit again to take advantage of INTT lever arm
The Acts z projection has better resolution than the circle fit
Definition at line 249 of file PHActsSiliconSeeding.cc.
View newest version in sPHENIX GitHub at line 249 of file PHActsSiliconSeeding.cc
References Acts::UnitConstants::cm, TrkrClusterContainer::findCluster(), findInttMatches(), ActsGeometry::getGlobalPosition(), TrkrDefs::getTrkrId(), h_nActsSeeds, h_nSeeds, TrackSeedContainer::identify(), TrackSeedContainer::insert(), TrkrDefs::inttId, m_clusterMap, m_maxSeedPCA, m_nBadInitialFits, m_searchInIntt, m_seedAnalysis, m_seedContainer, m_tGeometry, telescope_simulation::positions, seed, TrackSeedContainer::size(), Fun4AllBase::Verbosity(), and physmon_track_finding_ttbar::z.
Referenced by process_event().
std::vector< TrkrDefs::cluskey > PHActsSiliconSeeding::matchInttClusters (std::vector< Acts::Vector3 > & clusters, TrackSeed & seed, const double xProj[], const double yProj[], const double zProj[]) private
Check that the projection is within some reasonable amount of the segment to reject e.g. looking at segments in the opposite hemisphere. This is about the size of one intt segment (256 * 80 micron strips in a segment)
Diagnostic
Z strip spacing is the entire strip, so because we use fabs we divide by two
Cache INTT global positions with seed
Definition at line 510 of file PHActsSiliconSeeding.cc.
View newest version in sPHENIX GitHub at line 510 of file PHActsSiliconSeeding.cc
References _iteration_map, TrackSeed::begin_cluster_keys(), INTTVtxZ::dphi, TrackSeed::end_cluster_keys(), TrkrClusterContainer::getClusters(), ActsGeometry::getGlobalPosition(), TrkrClusterContainer::getHitSetKeys(), TrkrClusterIterationMapv1::getIteration(), TrkrDefs::getLayer(), PHG4CylinderGeomContainer::GetLayerGeom(), ActsSurfaceMaps::getSiliconSurface(), h_hits, h_nInttProj, h_nMatchedClusters, h_resids, h_zhits, TrkrDefs::inttId, it, layer, m_clusterMap, m_geomContainerIntt, m_nInttLayers, m_nIteration, m_rPhiSearchWin, m_searchInIntt, m_seedAnalysis, m_tGeometry, ActsGeometry::maps(), square(), surf(), and Fun4AllBase::Verbosity().
Referenced by findInttMatches().
void PHActsSiliconSeeding::maxPtScattering (const float pt) inline
Definition at line 88 of file PHActsSiliconSeeding.h.
View newest version in sPHENIX GitHub at line 88 of file PHActsSiliconSeeding.h
References m_maxPtScattering, and physmon_track_finding_ttbar::pt.
double PHActsSiliconSeeding::normPhi2Pi (const double phi) private
Definition at line 1002 of file PHActsSiliconSeeding.cc.
View newest version in sPHENIX GitHub at line 1002 of file PHActsSiliconSeeding.cc
References ActsTests::PropagationDatasets::phi.
void PHActsSiliconSeeding::printSeedConfigs (Acts::SeedFilterConfig & sfconfig) private
Definition at line 1021 of file PHActsSiliconSeeding.cc.
View newest version in sPHENIX GitHub at line 1021 of file PHActsSiliconSeeding.cc
References Acts::SeedFinderOptions::beamPos, Acts::SpacePointGridOptions::bFieldInZ, Acts::SeedFinderOptions::bFieldInZ, Acts::SeedFilterConfig::compatSeedLimit, Acts::SeedFilterConfig::compatSeedWeight, Acts::SpacePointGridConfig::cotThetaMax, Acts::SeedFilterConfig::deltaInvHelixDiameter, Acts::SpacePointGridConfig::deltaRMax, Acts::SeedFilterConfig::deltaRMin, Acts::SpacePointGridConfig::impactMax, Acts::SeedFilterConfig::impactWeightFactor, m_gridCfg, m_gridOptions, m_seedFinderCfg, m_seedFinderOptions, Acts::SeedFilterConfig::maxSeedsPerSpM, Acts::SeedFinderOptions::minHelixDiameter2, Acts::SpacePointGridConfig::minPt, Acts::SeedFilterConfig::numSeedIncrement, Acts::SpacePointGridConfig::phiBinDeflectionCoverage, Acts::SeedFinderOptions::pT2perRadius, Acts::SeedFinderOptions::pTPerHelixRadius, Acts::SpacePointGridConfig::rMax, Acts::SeedFilterConfig::seedWeightIncrement, Acts::SeedFinderOptions::sigmapT2perRadius, Acts::SpacePointGridConfig::zMax, Acts::SpacePointGridConfig::zMin, and Acts::SeedFilterConfig::zOriginWeightFactor.
Referenced by Init().
int PHActsSiliconSeeding::process_event (PHCompositeNode *) override virtual
Called for each event. This is where you do the real work.
Reimplemented from SubsysReco.
Definition at line 108 of file PHActsSiliconSeeding.cc.
View newest version in sPHENIX GitHub at line 108 of file PHActsSiliconSeeding.cc
References _iteration_map, Fun4AllReturnCodes::ABORTEVENT, Fun4AllReturnCodes::EVENT_OK, m_event, m_nIteration, makeSvtxTracks(), PHWHERE, runSeeder(), and Fun4AllBase::Verbosity().
void PHActsSiliconSeeding::ralign (const float r) inline
Definition at line 94 of file PHActsSiliconSeeding.h.
View newest version in sPHENIX GitHub at line 94 of file PHActsSiliconSeeding.h
References m_ralign, and physmon_track_finding_ttbar::r.
void PHActsSiliconSeeding::rMax (const float rMax) inline
Definition at line 72 of file PHActsSiliconSeeding.h.
View newest version in sPHENIX GitHub at line 72 of file PHActsSiliconSeeding.h
References m_rMax, and rMax().
Referenced by rMax().
void PHActsSiliconSeeding::rMin (const float rMin) inline
Definition at line 74 of file PHActsSiliconSeeding.h.
View newest version in sPHENIX GitHub at line 74 of file PHActsSiliconSeeding.h
References m_rMin, and rMin().
Referenced by rMin().
GridSeeds PHActsSiliconSeeding::runSeeder (std::vector< const SpacePoint * > & spVec) private
Covariance converter functor needed by seed finder
variable middle SP radial region of interest
Definition at line 183 of file PHActsSiliconSeeding.cc.
View newest version in sPHENIX GitHub at line 183 of file PHActsSiliconSeeding.cc
References Acts::binR, Acts::Test::cov, Acts::SeedFinder< external_spacepoint_t, platform_t >::createSeedsForGroup(), getSiliconSpacePoints(), grid(), h_nInputMeas, m_bottomBinFinder, m_gridCfg, m_gridOptions, m_seedAnalysis, m_seedFinderCfg, m_seedFinderOptions, m_topBinFinder, SpacePoint::m_varianceR, SpacePoint::m_varianceZ, testing::internal::move(), position, sigmaError(), filter::state, SpacePoint::x, SpacePoint::y, and SpacePoint::z.
Referenced by process_event().
void PHActsSiliconSeeding::searchInIntt () inline
Definition at line 108 of file PHActsSiliconSeeding.h.
View newest version in sPHENIX GitHub at line 108 of file PHActsSiliconSeeding.h
References m_searchInIntt.
Referenced by Tracking_Reco_TrackSeed_pass1().
void PHActsSiliconSeeding::seedAnalysis (bool seedAnalysis) inline
Output some diagnostic histograms.
Definition at line 56 of file PHActsSiliconSeeding.h.
View newest version in sPHENIX GitHub at line 56 of file PHActsSiliconSeeding.h
References m_seedAnalysis, and seedAnalysis().
Referenced by seedAnalysis().
void PHActsSiliconSeeding::set_track_map_name (const std::string & map_name) inline
Definition at line 106 of file PHActsSiliconSeeding.h.
View newest version in sPHENIX GitHub at line 106 of file PHActsSiliconSeeding.h
References _track_map_name.
Referenced by Tracking_Reco_TrackSeed_pass1().
void PHActsSiliconSeeding::setRPhiSearchWindow (const float win) inline
Definition at line 60 of file PHActsSiliconSeeding.h.
View newest version in sPHENIX GitHub at line 60 of file PHActsSiliconSeeding.h
References m_rPhiSearchWin.
void PHActsSiliconSeeding::setunc (float unc) inline
Definition at line 50 of file PHActsSiliconSeeding.h.
View newest version in sPHENIX GitHub at line 50 of file PHActsSiliconSeeding.h
References m_uncfactor.
void PHActsSiliconSeeding::sigmaError (const float sigma) inline
Definition at line 90 of file PHActsSiliconSeeding.h.
View newest version in sPHENIX GitHub at line 90 of file PHActsSiliconSeeding.h
References m_sigmaError, and sigma.
Referenced by runSeeder().
void PHActsSiliconSeeding::sigmaScattering (const float sigma) inline
Definition at line 86 of file PHActsSiliconSeeding.h.
View newest version in sPHENIX GitHub at line 86 of file PHActsSiliconSeeding.h
References m_sigmaScattering, and sigma.
void PHActsSiliconSeeding::tolerance (const float tolerance) inline
Definition at line 96 of file PHActsSiliconSeeding.h.
View newest version in sPHENIX GitHub at line 96 of file PHActsSiliconSeeding.h
References m_tolerance, and tolerance().
Referenced by tolerance().
void PHActsSiliconSeeding::useTruthClusters (bool useTruthClusters) inline
Set seeding with truth clusters.
Definition at line 52 of file PHActsSiliconSeeding.h.
View newest version in sPHENIX GitHub at line 52 of file PHActsSiliconSeeding.h
References m_useTruthClusters, and useTruthClusters().
Referenced by useTruthClusters().
void PHActsSiliconSeeding::writeHistograms () private
Definition at line 950 of file PHActsSiliconSeeding.cc.
View newest version in sPHENIX GitHub at line 950 of file PHActsSiliconSeeding.cc
References h_hits, h_nActsSeeds, h_nHits, h_nInputInttMeas, h_nInputMeas, h_nInputMvtxMeas, h_nInttHits, h_nInttProj, h_nMatchedClusters, h_nMvtxHits, h_nSeeds, h_nTotSeeds, h_projHits, h_resids, h_zhits, h_zprojHits, and m_file.
Referenced by End().
void PHActsSiliconSeeding::zalign (const float z) inline
Definition at line 92 of file PHActsSiliconSeeding.h.
View newest version in sPHENIX GitHub at line 92 of file PHActsSiliconSeeding.h
References m_zalign, and physmon_track_finding_ttbar::z.
void PHActsSiliconSeeding::zMax (const float zMax) inline
Definition at line 76 of file PHActsSiliconSeeding.h.
View newest version in sPHENIX GitHub at line 76 of file PHActsSiliconSeeding.h
References m_zMax, and zMax().
Referenced by zMax().
void PHActsSiliconSeeding::zMin (const float zMin) inline
Definition at line 78 of file PHActsSiliconSeeding.h.
View newest version in sPHENIX GitHub at line 78 of file PHActsSiliconSeeding.h
References m_zMin, and zMin().
Referenced by zMin().
Member Data Documentation
ClusterErrorPara PHActsSiliconSeeding::_ClusErrPara private
Definition at line 239 of file PHActsSiliconSeeding.h.
View newest version in sPHENIX GitHub at line 239 of file PHActsSiliconSeeding.h
TrkrClusterIterationMapv1* PHActsSiliconSeeding::_iteration_map = nullptr private
Definition at line 236 of file PHActsSiliconSeeding.h.
View newest version in sPHENIX GitHub at line 236 of file PHActsSiliconSeeding.h
Referenced by getSiliconSpacePoints(), matchInttClusters(), and process_event().
std::string PHActsSiliconSeeding::_track_map_name = "SiliconTrackSeedContainer" private
Definition at line 238 of file PHActsSiliconSeeding.h.
View newest version in sPHENIX GitHub at line 238 of file PHActsSiliconSeeding.h
Referenced by createNodes(), and set_track_map_name().
TH2* PHActsSiliconSeeding::h_hits = nullptr private
Definition at line 254 of file PHActsSiliconSeeding.h.
View newest version in sPHENIX GitHub at line 254 of file PHActsSiliconSeeding.h
Referenced by createHistograms(), findInttMatches(), matchInttClusters(), and writeHistograms().
TH1* PHActsSiliconSeeding::h_nActsSeeds = nullptr private
Definition at line 249 of file PHActsSiliconSeeding.h.
View newest version in sPHENIX GitHub at line 249 of file PHActsSiliconSeeding.h
Referenced by createHistograms(), makeSvtxTracks(), and writeHistograms().
TH2* PHActsSiliconSeeding::h_nHits = nullptr private
Definition at line 247 of file PHActsSiliconSeeding.h.
View newest version in sPHENIX GitHub at line 247 of file PHActsSiliconSeeding.h
Referenced by createHistograms(), and writeHistograms().
TH1* PHActsSiliconSeeding::h_nInputInttMeas = nullptr private
Definition at line 253 of file PHActsSiliconSeeding.h.
View newest version in sPHENIX GitHub at line 253 of file PHActsSiliconSeeding.h
Referenced by createHistograms(), and writeHistograms().
TH1* PHActsSiliconSeeding::h_nInputMeas = nullptr private
Definition at line 251 of file PHActsSiliconSeeding.h.
View newest version in sPHENIX GitHub at line 251 of file PHActsSiliconSeeding.h
Referenced by createHistograms(), runSeeder(), and writeHistograms().
TH1* PHActsSiliconSeeding::h_nInputMvtxMeas = nullptr private
Definition at line 252 of file PHActsSiliconSeeding.h.
View newest version in sPHENIX GitHub at line 252 of file PHActsSiliconSeeding.h
Referenced by createHistograms(), getSiliconSpacePoints(), and writeHistograms().
TH1* PHActsSiliconSeeding::h_nInttHits = nullptr private
Definition at line 245 of file PHActsSiliconSeeding.h.
View newest version in sPHENIX GitHub at line 245 of file PHActsSiliconSeeding.h
Referenced by createHistograms(), and writeHistograms().
TH2* PHActsSiliconSeeding::h_nInttProj = nullptr private
Definition at line 243 of file PHActsSiliconSeeding.h.
View newest version in sPHENIX GitHub at line 243 of file PHActsSiliconSeeding.h
Referenced by createHistograms(), matchInttClusters(), and writeHistograms().
TH1* PHActsSiliconSeeding::h_nMatchedClusters = nullptr private
Definition at line 246 of file PHActsSiliconSeeding.h.
View newest version in sPHENIX GitHub at line 246 of file PHActsSiliconSeeding.h
Referenced by createHistograms(), matchInttClusters(), and writeHistograms().
TH1* PHActsSiliconSeeding::h_nMvtxHits = nullptr private
Definition at line 244 of file PHActsSiliconSeeding.h.
View newest version in sPHENIX GitHub at line 244 of file PHActsSiliconSeeding.h
Referenced by createHistograms(), and writeHistograms().
TH1* PHActsSiliconSeeding::h_nSeeds = nullptr private
Definition at line 248 of file PHActsSiliconSeeding.h.
View newest version in sPHENIX GitHub at line 248 of file PHActsSiliconSeeding.h
Referenced by createHistograms(), makeSvtxTracks(), and writeHistograms().
TH1* PHActsSiliconSeeding::h_nTotSeeds = nullptr private
Definition at line 250 of file PHActsSiliconSeeding.h.
View newest version in sPHENIX GitHub at line 250 of file PHActsSiliconSeeding.h
Referenced by createHistograms(), and writeHistograms().
TH2* PHActsSiliconSeeding::h_projHits = nullptr private
Definition at line 256 of file PHActsSiliconSeeding.h.
View newest version in sPHENIX GitHub at line 256 of file PHActsSiliconSeeding.h
Referenced by createHistograms(), findInttMatches(), and writeHistograms().
TH2* PHActsSiliconSeeding::h_resids = nullptr private
Definition at line 258 of file PHActsSiliconSeeding.h.
View newest version in sPHENIX GitHub at line 258 of file PHActsSiliconSeeding.h
Referenced by createHistograms(), matchInttClusters(), and writeHistograms().
TH2* PHActsSiliconSeeding::h_zhits = nullptr private
Definition at line 255 of file PHActsSiliconSeeding.h.
View newest version in sPHENIX GitHub at line 255 of file PHActsSiliconSeeding.h
Referenced by createHistograms(), findInttMatches(), matchInttClusters(), and writeHistograms().
TH2* PHActsSiliconSeeding::h_zprojHits = nullptr private
Definition at line 257 of file PHActsSiliconSeeding.h.
View newest version in sPHENIX GitHub at line 257 of file PHActsSiliconSeeding.h
Referenced by createHistograms(), findInttMatches(), and writeHistograms().
float PHActsSiliconSeeding::m_bField = 1.4 * Acts::UnitConstants::T private
B field value in z direction bfield for space point grid neds to be in kiloTesla
Definition at line 210 of file PHActsSiliconSeeding.h.
View newest version in sPHENIX GitHub at line 210 of file PHActsSiliconSeeding.h
Referenced by configureSeeder(), and configureSPGrid().
std::shared_ptr<const Acts::BinFinder<SpacePoint> > PHActsSiliconSeeding::m_bottomBinFinder private
Definition at line 215 of file PHActsSiliconSeeding.h.
View newest version in sPHENIX GitHub at line 215 of file PHActsSiliconSeeding.h
Referenced by Init(), and runSeeder().
bool PHActsSiliconSeeding::m_cleanSeeds = false private
Definition at line 232 of file PHActsSiliconSeeding.h.
View newest version in sPHENIX GitHub at line 232 of file PHActsSiliconSeeding.h
Referenced by cleanSeeds().
TrkrClusterContainer* PHActsSiliconSeeding::m_clusterMap = nullptr private
Definition at line 155 of file PHActsSiliconSeeding.h.
View newest version in sPHENIX GitHub at line 155 of file PHActsSiliconSeeding.h
Referenced by getNodes(), getSiliconSpacePoints(), makeSvtxTracks(), and matchInttClusters().
float PHActsSiliconSeeding::m_cotThetaMax = 2.9 private
Cot of maximum theta angle.
Definition at line 199 of file PHActsSiliconSeeding.h.
View newest version in sPHENIX GitHub at line 199 of file PHActsSiliconSeeding.h
Referenced by configureSeeder(), configureSPGrid(), cotThetaMax(), and largeGridSpacing().
float PHActsSiliconSeeding::m_deltaRMax = 15 * Acts::UnitConstants::mm private
max distance between two measurements in one seed
Definition at line 196 of file PHActsSiliconSeeding.h.
View newest version in sPHENIX GitHub at line 196 of file PHActsSiliconSeeding.h
Referenced by configureSeeder(), configureSPGrid(), and deltaRMax().
float PHActsSiliconSeeding::m_deltaRMin = 1. * Acts::UnitConstants::mm private
Definition at line 197 of file PHActsSiliconSeeding.h.
View newest version in sPHENIX GitHub at line 197 of file PHActsSiliconSeeding.h
Referenced by configureSeeder().
int PHActsSiliconSeeding::m_event = 0 private
Definition at line 217 of file PHActsSiliconSeeding.h.
View newest version in sPHENIX GitHub at line 217 of file PHActsSiliconSeeding.h
Referenced by process_event().
TFile* PHActsSiliconSeeding::m_file = nullptr private
Definition at line 242 of file PHActsSiliconSeeding.h.
View newest version in sPHENIX GitHub at line 242 of file PHActsSiliconSeeding.h
Referenced by Init(), and writeHistograms().
PHG4CylinderGeomContainer* PHActsSiliconSeeding::m_geomContainerIntt = nullptr private
Definition at line 156 of file PHActsSiliconSeeding.h.
View newest version in sPHENIX GitHub at line 156 of file PHActsSiliconSeeding.h
Referenced by getNodes(), InitRun(), and matchInttClusters().
Acts::SpacePointGridConfig PHActsSiliconSeeding::m_gridCfg private
Definition at line 160 of file PHActsSiliconSeeding.h.
View newest version in sPHENIX GitHub at line 160 of file PHActsSiliconSeeding.h
Referenced by configureSPGrid(), printSeedConfigs(), and runSeeder().
float PHActsSiliconSeeding::m_gridFactor = 2.3809 private
Value tuned to provide as large of phi bins as possible. Increases the secondary finding efficiency
Definition at line 193 of file PHActsSiliconSeeding.h.
View newest version in sPHENIX GitHub at line 193 of file PHActsSiliconSeeding.h
Referenced by configureSPGrid(), gridFactor(), and largeGridSpacing().
Acts::SpacePointGridOptions PHActsSiliconSeeding::m_gridOptions private
Definition at line 161 of file PHActsSiliconSeeding.h.
View newest version in sPHENIX GitHub at line 161 of file PHActsSiliconSeeding.h
Referenced by configureSPGrid(), printSeedConfigs(), and runSeeder().
float PHActsSiliconSeeding::m_helixcut = 1 private
misalignment parameters
Definition at line 183 of file PHActsSiliconSeeding.h.
View newest version in sPHENIX GitHub at line 183 of file PHActsSiliconSeeding.h
Referenced by configureSeeder(), and helixcut().
float PHActsSiliconSeeding::m_impactMax = 20 * Acts::UnitConstants::mm private
Maximum impact parameter allowed in mm.
Definition at line 202 of file PHActsSiliconSeeding.h.
View newest version in sPHENIX GitHub at line 202 of file PHActsSiliconSeeding.h
Referenced by configureSeeder(), and configureSPGrid().
float PHActsSiliconSeeding::m_maxPtScattering = 10 private
Definition at line 187 of file PHActsSiliconSeeding.h.
View newest version in sPHENIX GitHub at line 187 of file PHActsSiliconSeeding.h
Referenced by configureSeeder(), and maxPtScattering().
double PHActsSiliconSeeding::m_maxSeedPCA = 2. private
Maximum allowed transverse PCA for seed, cm.
Definition at line 220 of file PHActsSiliconSeeding.h.
View newest version in sPHENIX GitHub at line 220 of file PHActsSiliconSeeding.h
Referenced by largeGridSpacing(), and makeSvtxTracks().
int PHActsSiliconSeeding::m_maxSeedsPerSpM = 1 private
How many seeds a given hit can be the middle hit of the seed MVTX can only have the middle layer be the middle hit
Definition at line 174 of file PHActsSiliconSeeding.h.
View newest version in sPHENIX GitHub at line 174 of file PHActsSiliconSeeding.h
Referenced by configureSeeder(), and configureSeedFilter().
float PHActsSiliconSeeding::m_minSeedPt = 100 * Acts::UnitConstants::MeV private
Configurable parameters seed pt has to be in MeV
Definition at line 169 of file PHActsSiliconSeeding.h.
View newest version in sPHENIX GitHub at line 169 of file PHActsSiliconSeeding.h
Referenced by configureSeeder(), and configureSPGrid().
int PHActsSiliconSeeding::m_nBadInitialFits = 0 private
Definition at line 235 of file PHActsSiliconSeeding.h.
View newest version in sPHENIX GitHub at line 235 of file PHActsSiliconSeeding.h
Referenced by End(), and makeSvtxTracks().
int PHActsSiliconSeeding::m_nBadUpdates = 0 private
Definition at line 234 of file PHActsSiliconSeeding.h.
View newest version in sPHENIX GitHub at line 234 of file PHActsSiliconSeeding.h
Referenced by End().
double PHActsSiliconSeeding::m_nInttLayerRadii[m_nInttLayers] = {0} private
Definition at line 224 of file PHActsSiliconSeeding.h.
View newest version in sPHENIX GitHub at line 224 of file PHActsSiliconSeeding.h
Referenced by findInttMatches(), and InitRun().
const unsigned int PHActsSiliconSeeding::m_nInttLayers = 4 static private
Doesn't change, we are building the INTT this way.
Definition at line 223 of file PHActsSiliconSeeding.h.
View newest version in sPHENIX GitHub at line 223 of file PHActsSiliconSeeding.h
Referenced by findInttMatches(), and matchInttClusters().
int PHActsSiliconSeeding::m_nIteration = 0 private
Definition at line 237 of file PHActsSiliconSeeding.h.
View newest version in sPHENIX GitHub at line 237 of file PHActsSiliconSeeding.h
Referenced by getSiliconSpacePoints(), iteration(), matchInttClusters(), and process_event().
int PHActsSiliconSeeding::m_numPhiNeighbors = 1 private
Only used in seeding with specified z bin edges, which is more configuration than we need
Definition at line 206 of file PHActsSiliconSeeding.h.
View newest version in sPHENIX GitHub at line 206 of file PHActsSiliconSeeding.h
Referenced by configureSPGrid().
float PHActsSiliconSeeding::m_ralign = 0 private
Definition at line 185 of file PHActsSiliconSeeding.h.
View newest version in sPHENIX GitHub at line 185 of file PHActsSiliconSeeding.h
Referenced by configureSeeder(), and ralign().
float PHActsSiliconSeeding::m_rMax = 200. * Acts::UnitConstants::mm private
Limiting location of measurements (e.g. detector constraints)
Definition at line 177 of file PHActsSiliconSeeding.h.
View newest version in sPHENIX GitHub at line 177 of file PHActsSiliconSeeding.h
Referenced by configureSeeder(), configureSPGrid(), largeGridSpacing(), and rMax().
float PHActsSiliconSeeding::m_rMin = 23. * Acts::UnitConstants::mm private
Definition at line 178 of file PHActsSiliconSeeding.h.
View newest version in sPHENIX GitHub at line 178 of file PHActsSiliconSeeding.h
Referenced by configureSeeder(), and rMin().
double PHActsSiliconSeeding::m_rPhiSearchWin = 0.1 private
Search window for phi to match intt clusters in cm.
Definition at line 227 of file PHActsSiliconSeeding.h.
View newest version in sPHENIX GitHub at line 227 of file PHActsSiliconSeeding.h
Referenced by matchInttClusters(), and setRPhiSearchWindow().
bool PHActsSiliconSeeding::m_searchInIntt = false private
boolean whether or not to include the intt in the acts search windows
Definition at line 165 of file PHActsSiliconSeeding.h.
View newest version in sPHENIX GitHub at line 165 of file PHActsSiliconSeeding.h
Referenced by getSiliconSpacePoints(), makeSvtxTracks(), matchInttClusters(), and searchInIntt().
bool PHActsSiliconSeeding::m_seedAnalysis = false private
Definition at line 241 of file PHActsSiliconSeeding.h.
View newest version in sPHENIX GitHub at line 241 of file PHActsSiliconSeeding.h
Referenced by End(), findInttMatches(), getSiliconSpacePoints(), Init(), makeSvtxTracks(), matchInttClusters(), runSeeder(), and seedAnalysis().
TrackSeedContainer* PHActsSiliconSeeding::m_seedContainer = nullptr private
Definition at line 154 of file PHActsSiliconSeeding.h.
View newest version in sPHENIX GitHub at line 154 of file PHActsSiliconSeeding.h
Referenced by createNodes(), and makeSvtxTracks().
Acts::SeedFinderConfig<SpacePoint> PHActsSiliconSeeding::m_seedFinderCfg private
Configuration classes for Acts seeding.
Definition at line 159 of file PHActsSiliconSeeding.h.
View newest version in sPHENIX GitHub at line 159 of file PHActsSiliconSeeding.h
Referenced by configureSeeder(), Init(), printSeedConfigs(), and runSeeder().
Acts::SeedFinderOptions PHActsSiliconSeeding::m_seedFinderOptions private
Definition at line 162 of file PHActsSiliconSeeding.h.
View newest version in sPHENIX GitHub at line 162 of file PHActsSiliconSeeding.h
Referenced by configureSeeder(), printSeedConfigs(), and runSeeder().
float PHActsSiliconSeeding::m_sigmaError = 5 private
Definition at line 189 of file PHActsSiliconSeeding.h.
View newest version in sPHENIX GitHub at line 189 of file PHActsSiliconSeeding.h
Referenced by configureSeeder(), and sigmaError().
float PHActsSiliconSeeding::m_sigmaScattering = 5. private
Definition at line 188 of file PHActsSiliconSeeding.h.
View newest version in sPHENIX GitHub at line 188 of file PHActsSiliconSeeding.h
Referenced by configureSeeder(), and sigmaScattering().
ActsGeometry* PHActsSiliconSeeding::m_tGeometry = nullptr private
Definition at line 153 of file PHActsSiliconSeeding.h.
View newest version in sPHENIX GitHub at line 153 of file PHActsSiliconSeeding.h
Referenced by getNodes(), getSiliconSpacePoints(), makeSpacePoint(), makeSvtxTracks(), and matchInttClusters().
float PHActsSiliconSeeding::m_tolerance = 1.1 * Acts::UnitConstants::mm private
Definition at line 184 of file PHActsSiliconSeeding.h.
View newest version in sPHENIX GitHub at line 184 of file PHActsSiliconSeeding.h
Referenced by configureSeeder(), and tolerance().
std::shared_ptr<const Acts::BinFinder<SpacePoint> > PHActsSiliconSeeding::m_topBinFinder private
Definition at line 215 of file PHActsSiliconSeeding.h.
View newest version in sPHENIX GitHub at line 215 of file PHActsSiliconSeeding.h
Referenced by Init(), and runSeeder().
float PHActsSiliconSeeding::m_uncfactor = 3.18 private
Definition at line 170 of file PHActsSiliconSeeding.h.
View newest version in sPHENIX GitHub at line 170 of file PHActsSiliconSeeding.h
Referenced by makeSpacePoint(), and setunc().
bool PHActsSiliconSeeding::m_useTruthClusters = false private
Whether or not to use truth clusters in hit lookup.
Definition at line 230 of file PHActsSiliconSeeding.h.
View newest version in sPHENIX GitHub at line 230 of file PHActsSiliconSeeding.h
Referenced by getNodes(), and useTruthClusters().
float PHActsSiliconSeeding::m_zalign = 0 private
Definition at line 186 of file PHActsSiliconSeeding.h.
View newest version in sPHENIX GitHub at line 186 of file PHActsSiliconSeeding.h
Referenced by configureSeeder(), and zalign().
float PHActsSiliconSeeding::m_zMax = 500. * Acts::UnitConstants::mm private
Definition at line 179 of file PHActsSiliconSeeding.h.
View newest version in sPHENIX GitHub at line 179 of file PHActsSiliconSeeding.h
Referenced by configureSeeder(), configureSPGrid(), and zMax().
float PHActsSiliconSeeding::m_zMin = -500. * Acts::UnitConstants::mm private
Definition at line 180 of file PHActsSiliconSeeding.h.
View newest version in sPHENIX GitHub at line 180 of file PHActsSiliconSeeding.h
Referenced by configureSeeder(), configureSPGrid(), and zMin().
int PHActsSiliconSeeding::nphineighbors = 1 private
Definition at line 213 of file PHActsSiliconSeeding.h.
View newest version in sPHENIX GitHub at line 213 of file PHActsSiliconSeeding.h
Referenced by Init().
std::vector<std::pair<int, int> > PHActsSiliconSeeding::zBinNeighborsBottom private
Definition at line 212 of file PHActsSiliconSeeding.h.
View newest version in sPHENIX GitHub at line 212 of file PHActsSiliconSeeding.h
Referenced by Init().
std::vector<std::pair<int, int> > PHActsSiliconSeeding::zBinNeighborsTop private
Definition at line 211 of file PHActsSiliconSeeding.h.
View newest version in sPHENIX GitHub at line 211 of file PHActsSiliconSeeding.h
Referenced by Init().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/trackreco/PHActsSiliconSeeding.h
coresoftware/blob/master/offline/packages/trackreco/PHActsSiliconSeeding.cc