Analysis Software: analysis/blob/master/AndersonAnalysisModules/TrackStudies/SDeltaPtCutStudy/macros/CheckDeltaPtWithBoundaryMasks.cxx File Reference
CheckDeltaPtWithBoundaryMasks.cxx File Reference
#include <array>
#include <string>
#include <vector>
#include <utility>
#include <iostream>
#include <TH1.h>
#include <TH2.h>
#include <TF1.h>
#include <TFile.h>
#include <TError.h>
#include <TNtuple.h>
#include <TDirectory.h>
#include <ROOT/RDataFrame.hxx>
#include <ROOT/RDF/HistoModels.hxx>
Typedefs
using TH1Mod = ROOT::RDF::TH1DModel
using TH2Mod = ROOT::RDF::TH2DModel
using RH1Ptr = ROOT::RDF::RResultPtr<::TH1D >
using RH2Ptr = ROOT::RDF::RResultPtr<::TH2D >
using THBins = tuple< size_t, double, double >
using TH1Def = tuple< string, string, THBins >
using TH2Def = tuple< string, string, THBins, THBins >
using Leaves = pair< string, string >
Functions
void CheckDeltaPtWithBoundaryMasks ()
Variables
static const size_t NSectors = 12
Typedef Documentation
using Leaves = pair<string, string>
Definition at line 41 of file CheckDeltaPtWithBoundaryMasks.cxx.
View newest version in sPHENIX GitHub at line 41 of file CheckDeltaPtWithBoundaryMasks.cxx
using RH1Ptr = ROOT::RDF::RResultPtr<::TH1D>
Definition at line 34 of file CheckDeltaPtWithBoundaryMasks.cxx.
View newest version in sPHENIX GitHub at line 34 of file CheckDeltaPtWithBoundaryMasks.cxx
using RH2Ptr = ROOT::RDF::RResultPtr<::TH2D>
Definition at line 35 of file CheckDeltaPtWithBoundaryMasks.cxx.
View newest version in sPHENIX GitHub at line 35 of file CheckDeltaPtWithBoundaryMasks.cxx
using TH1Def = tuple<string, string, THBins>
Definition at line 39 of file CheckDeltaPtWithBoundaryMasks.cxx.
View newest version in sPHENIX GitHub at line 39 of file CheckDeltaPtWithBoundaryMasks.cxx
using TH1Mod = ROOT::RDF::TH1DModel
Definition at line 32 of file CheckDeltaPtWithBoundaryMasks.cxx.
View newest version in sPHENIX GitHub at line 32 of file CheckDeltaPtWithBoundaryMasks.cxx
using TH2Def = tuple<string, string, THBins, THBins>
Definition at line 40 of file CheckDeltaPtWithBoundaryMasks.cxx.
View newest version in sPHENIX GitHub at line 40 of file CheckDeltaPtWithBoundaryMasks.cxx
using TH2Mod = ROOT::RDF::TH2DModel
Definition at line 33 of file CheckDeltaPtWithBoundaryMasks.cxx.
View newest version in sPHENIX GitHub at line 33 of file CheckDeltaPtWithBoundaryMasks.cxx
using THBins = tuple<size_t, double, double>
Definition at line 38 of file CheckDeltaPtWithBoundaryMasks.cxx.
View newest version in sPHENIX GitHub at line 38 of file CheckDeltaPtWithBoundaryMasks.cxx
Function Documentation
void CheckDeltaPtWithBoundaryMasks ()
Definition at line 50 of file CheckDeltaPtWithBoundaryMasks.cxx.
View newest version in sPHENIX GitHub at line 50 of file CheckDeltaPtWithBoundaryMasks.cxx
References KFPMath::a, KFPMath::b, bins, cd(), Close(), configureMap::data, add_histos::hist, std::tr1::make_tuple(), mask, perf_headwind::name, ActsTests::PropagationDatasets::phi, tracks(), and Write().
Variable Documentation
const size_t NSectors = 12 static
Definition at line 44 of file CheckDeltaPtWithBoundaryMasks.cxx.
View newest version in sPHENIX GitHub at line 44 of file CheckDeltaPtWithBoundaryMasks.cxx
Referenced by PHG4TpcDetector::add_geometry_node().