Analysis Software: Getters
Getters
Functions
virtual RawClusterDefs::keytype RawCluster::get_id () const
cluster ID
virtual float RawCluster::get_energy () const
total energy
virtual size_t RawCluster::getNTowers () const
Tower operations.
virtual TowerConstRange RawCluster::get_towers () const
virtual const TowerMap & RawCluster::get_towermap () const
return tower map for c++11 range-based for-loop
virtual CLHEP::Hep3Vector RawCluster::get_position () const
virtual float RawCluster::get_phi () const
access to intrinsic cylindrical coordinate system
virtual float RawCluster::get_r () const
virtual float RawCluster::get_z () const
virtual float RawCluster::get_x () const
access Cartesian coordinate system
virtual float RawCluster::get_y () const
virtual float RawCluster::get_ecore () const
virtual float RawCluster::get_chi2 () const
reduced chi2 for EM shower
virtual float RawCluster::get_prob () const
cluster template probability for EM shower
virtual float RawCluster::get_et_iso () const
isolation ET default
virtual float RawCluster::get_et_iso (const int, bool, bool) const
isolation ET the radius and hueristic can be specified
RawClusterDefs::keytype RawClusterv1::get_id () const override
cluster ID
float RawClusterv1::get_energy () const override
total energy
size_t RawClusterv1::getNTowers () const override
Tower operations.
RawCluster::TowerConstRange RawClusterv1::get_towers () const override
const TowerMap & RawClusterv1::get_towermap () const override
return tower map for c++11 range-based for-loop
CLHEP::Hep3Vector RawClusterv1::get_position () const override
cluster position in 3D
float RawClusterv1::get_phi () const override
access to intrinsic cylindrical coordinate system
float RawClusterv1::get_r () const override
float RawClusterv1::get_z () const override
float RawClusterv1::get_x () const override
access Cartesian coordinate system
float RawClusterv1::get_y () const override
float RawClusterv1::get_ecore () const override
float RawClusterv1::get_chi2 () const override
reduced chi2 for EM shower
float RawClusterv1::get_prob () const override
cluster template probability for EM shower
float RawClusterv1::get_et_iso () const override
isolation ET default
float RawClusterv1::get_et_iso (const int radiusx10, bool subtracted, bool clusterTower) const override
isolation ET the radius and hueristic can be specified
Detailed Description
is RawCluster::get_eta() ?
get_eta() is retired! eta does not have meaning for cluster unless user choose a vertex, which is totally up to user in case of multiple collision, and therefore not an intrinsic property of clusterizer. The goal is to force people to calculate it based on r/z and the vertex of choice.There is a utility to help you calculate, a concise example is here to get energy 3-vector: https://www.phenix.bnl.gov/WWW/sPHENIX/doxygen/html/dc/d23/ClusterJetInput_8C_source.html#l00045 Or this one if you only interest in eta: https://www.phenix.bnl.gov/WWW/sPHENIX/doxygen/html/d7/daf/CaloEvaluator_8C_source.html#l00487Older code is commented out here://! convert cluster location to psuedo-rapidity given a user chosen z-location virtual float get_eta() const { PHOOL_VIRTUAL_WARN("get_eta()"); return NAN; } //! convert cluster E_T given a user chosen z-location virtual float get_et() const { PHOOL_VIRTUAL_WARN("get_et()"); return NAN; }
Function Documentation
float RawClusterv1::get_chi2 () const inline override virtual
reduced chi2 for EM shower
Reimplemented from RawCluster.
Definition at line 64 of file RawClusterv1.h.
View newest version in sPHENIX GitHub at line 64 of file RawClusterv1.h
References RawClusterv1::get_property_float(), and RawCluster::prop_chi2.
virtual float RawCluster::get_chi2 () const inline virtual
reduced chi2 for EM shower
Reimplemented in RawClusterv1.
Definition at line 148 of file RawCluster.h.
View newest version in sPHENIX GitHub at line 148 of file RawCluster.h
References PHOOL_VIRTUAL_WARN.
Referenced by TreeMaker::CopyAndMakeClusters(), RawClusterZVertexRecorrect::process_event(), Photons::process_event(), Pi0MassAnalysis::process_event(), CaloCalibEmc_Pi0::process_event(), ElectronID::process_event(), PairMaker::process_event_test(), CaloAna::process_towers(), CaloValid::process_towers(), and pi0EtaByEta::process_towers().
float RawClusterv1::get_ecore () const inline override virtual
access additional optional properties cluster core energy for EM shower
Reimplemented from RawCluster.
Definition at line 62 of file RawClusterv1.h.
View newest version in sPHENIX GitHub at line 62 of file RawClusterv1.h
References RawClusterv1::get_property_float(), and RawCluster::prop_ecore.
virtual float RawCluster::get_ecore () const inline virtual
access additional optional properties cluster core energy for EM shower
Reimplemented in RawClusterv1.
Definition at line 142 of file RawCluster.h.
View newest version in sPHENIX GitHub at line 142 of file RawCluster.h
References PHOOL_VIRTUAL_WARN.
Referenced by TreeMaker::CopyAndMakeClusters(), CaloEvaluator::fillOutputNtuples(), RawClusterUtility::GetECoreVec(), RawClusterUtility::GetETCore(), DISKinematicsReco::InsertCandidateFromCluster(), FilterEventsUpsilon::MatchClusterCEMC(), FilterEvents::MatchClusterCEMC(), sPHAnalysis::MatchClusterCEMC(), RawClusterPositionCorrection::process_event(), FilterEvents::process_event(), FilterEventsUpsilon::process_event(), Photons::process_event(), CaloCalibEmc_Pi0::process_event(), singlePhotonClusterAna::process_event(), ElectronID::process_event(), pythiaEMCalAna::process_event(), sPHAnalysis::process_event_notracking(), PairMaker::process_event_test(), sPHAnalysis_calo::process_event_test(), sPHAnalysis::process_event_test(), and sPHAnalysis::process_event_upsilons().
float RawClusterv1::get_energy () const inline override virtual
total energy
Reimplemented from RawCluster.
Definition at line 34 of file RawClusterv1.h.
View newest version in sPHENIX GitHub at line 34 of file RawClusterv1.h
References RawClusterv1::_energy.
Referenced by RawClusterv1::identify().
virtual float RawCluster::get_energy () const inline virtual
total energy
Reimplemented in RawClusterv1.
Definition at line 51 of file RawCluster.h.
View newest version in sPHENIX GitHub at line 51 of file RawCluster.h
References PHOOL_VIRTUAL_WARN.
Referenced by ExclusiveReco::AddInvariantMassInformation(), DISKinematicsReco::CollectEmCandidatesFromCluster(), cemcReco::coneSum(), PhotonJet::ConeSum(), TreeMaker::CopyAndMakeClusters(), CaloEvaluator::fillOutputNtuples(), EventEvaluator::fillOutputNtuples(), JetRecoEval::get_energy_contribution(), ClusterJetInput::get_input(), STACalorimeterCharacterization::get_ordered_clusters(), TreeMaker::GetClusters(), IsolatedTrackAnalysis::getClusters(), RawClusterUtility::GetET(), RawClusterUtility::GetEVec(), DISKinematicsReco::InsertCandidateFromCluster(), CaloEvaluator::printOutputInfo(), CaloRecoUtility::ProbCorrsZVertex(), RawClusterZVertexRecorrect::process_event(), RawClusterPositionCorrection::process_event(), STACalorimeterCharacterization::process_event(), PHGenFitTrackProjection::process_event(), Pi0MassAnalysis::process_event(), pythiaEMCalAna::process_event(), QAG4SimulationCalorimeter::process_event_Cluster(), QAG4SimulationCalorimeterSum::process_event_Cluster(), PairMaker::process_event_test(), sPHAnalysis::process_event_test(), CaloRecoUtility::ShowerDepthCorrZVertex(), and TreeMaker::UseFastJet().
float RawClusterv1::get_et_iso () const inline override virtual
isolation ET default
Reimplemented from RawCluster.
Definition at line 68 of file RawClusterv1.h.
View newest version in sPHENIX GitHub at line 68 of file RawClusterv1.h
References RawClusterv1::get_property_float(), and RawCluster::prop_et_iso_calotower_R03.
float RawClusterv1::get_et_iso (const int radiusx10 = 3, bool subtracted = false, bool clusterTower = true) const override virtual
isolation ET the radius and hueristic can be specified
Reimplemented from RawCluster.
Definition at line 259 of file RawClusterv1.cc.
View newest version in sPHENIX GitHub at line 259 of file RawClusterv1.cc
References RawClusterv1::get_property_float(), PHOOL_VIRTUAL_WARN, RawCluster::prop_et_iso_calotower_R01, RawCluster::prop_et_iso_calotower_R02, RawCluster::prop_et_iso_calotower_R03, RawCluster::prop_et_iso_calotower_R04, RawCluster::prop_et_iso_calotower_sub_R01, RawCluster::prop_et_iso_calotower_sub_R02, RawCluster::prop_et_iso_calotower_sub_R03, RawCluster::prop_et_iso_calotower_sub_R04, physmon_track_finding_ttbar::r, and to_string().
virtual float RawCluster::get_et_iso () const inline virtual
isolation ET default
Reimplemented in RawClusterv1.
Definition at line 160 of file RawCluster.h.
View newest version in sPHENIX GitHub at line 160 of file RawCluster.h
References PHOOL_VIRTUAL_WARN.
Referenced by DISKinematicsReco::InsertCandidateFromCluster().
virtual float RawCluster::get_et_iso (const int , bool , bool) const inline virtual
isolation ET the radius and hueristic can be specified
Reimplemented in RawClusterv1.
Definition at line 166 of file RawCluster.h.
View newest version in sPHENIX GitHub at line 166 of file RawCluster.h
References PHOOL_VIRTUAL_WARN.
RawClusterDefs::keytype RawClusterv1::get_id () const inline override virtual
cluster ID
Reimplemented from RawCluster.
Definition at line 32 of file RawClusterv1.h.
View newest version in sPHENIX GitHub at line 32 of file RawClusterv1.h
References RawClusterv1::clusterid.
Referenced by RawClusterv1::identify().
virtual RawClusterDefs::keytype RawCluster::get_id () const inline virtual
cluster ID
Reimplemented in RawClusterv1.
Definition at line 45 of file RawCluster.h.
View newest version in sPHENIX GitHub at line 45 of file RawCluster.h
References PHOOL_VIRTUAL_WARN.
Referenced by ResonanceJetTagging::addClusters(), TreeMaker::CopyAndMakeClusters(), CaloEvaluator::fillOutputNtuples(), ClusterJetInput::get_input(), DISKinematicsReco::InsertCandidateFromCluster(), CaloEvaluator::printOutputInfo(), RawClusterBuilderGraph::process_event(), RawClusterDeadHotMask::process_event(), CaloCalibEmc_Pi0::process_event(), and pythiaEMCalAna::process_event().
float RawClusterv1::get_phi () const inline override virtual
access to intrinsic cylindrical coordinate system
Reimplemented from RawCluster.
Definition at line 47 of file RawClusterv1.h.
View newest version in sPHENIX GitHub at line 47 of file RawClusterv1.h
References RawClusterv1::_phi.
Referenced by RawClusterv1::get_x(), RawClusterv1::get_y(), and RawClusterv1::identify().
virtual float RawCluster::get_phi () const inline virtual
access to intrinsic cylindrical coordinate system
Reimplemented in RawClusterv1.
Definition at line 83 of file RawCluster.h.
View newest version in sPHENIX GitHub at line 83 of file RawCluster.h
References PHOOL_VIRTUAL_WARN.
Referenced by cemcReco::coneSum(), PhotonJet::ConeSum(), TreeMaker::CopyAndMakeClusters(), CaloEvaluator::fillOutputNtuples(), EventEvaluator::fillOutputNtuples(), TrackProjectionTools::FindClosestTrack(), TrackProjectionTools::getCluster(), IsolatedTrackAnalysis::getClusters(), DISKinematicsReco::InsertCandidateFromCluster(), VtxTest::numUnique(), CaloEvaluator::printOutputInfo(), PHGenFitTrackProjection::process_event(), Pi0MassAnalysis::process_event(), TrackProjectorPlaneECAL::project_track(), TruthConversionEval::recordConversion(), and TreeMaker::UseFastJet().
CLHEP::Hep3Vector RawClusterv1::get_position () const inline override virtual
cluster position in 3D
Reimplemented from RawCluster.
Definition at line 42 of file RawClusterv1.h.
View newest version in sPHENIX GitHub at line 42 of file RawClusterv1.h
References RawClusterv1::get_x(), RawClusterv1::get_y(), and RawClusterv1::get_z().
virtual CLHEP::Hep3Vector RawCluster::get_position () const inline virtual
Reimplemented in RawClusterv1.
Definition at line 76 of file RawCluster.h.
View newest version in sPHENIX GitHub at line 76 of file RawCluster.h
References PHOOL_VIRTUAL_WARN.
Referenced by RawClusterUtility::GetAzimuthAngle(), RawClusterUtility::GetECoreVec(), RawClusterUtility::GetET(), RawClusterUtility::GetETCore(), RawClusterUtility::GetEVec(), RawClusterUtility::GetPolarAngle(), RawClusterUtility::GetPseudorapidity(), and QAG4SimulationCalorimeter::process_event_Cluster().
float RawClusterv1::get_prob () const inline override virtual
cluster template probability for EM shower
Reimplemented from RawCluster.
Definition at line 66 of file RawClusterv1.h.
View newest version in sPHENIX GitHub at line 66 of file RawClusterv1.h
References RawClusterv1::get_property_float(), and RawCluster::prop_prob.
virtual float RawCluster::get_prob () const inline virtual
cluster template probability for EM shower
Reimplemented in RawClusterv1.
Definition at line 154 of file RawCluster.h.
View newest version in sPHENIX GitHub at line 154 of file RawCluster.h
References PHOOL_VIRTUAL_WARN.
Referenced by TreeMaker::CopyAndMakeClusters(), DISKinematicsReco::InsertCandidateFromCluster(), VtxTest::numUnique(), Photons::process_event(), Pi0MassAnalysis::process_event(), RecoConversionEval::process_event(), ElectronID::process_event(), PairMaker::process_event_test(), sPHAnalysis::process_event_test(), and TruthConversionEval::recordConversion().
float RawClusterv1::get_r () const inline override virtual
Reimplemented from RawCluster.
Definition at line 48 of file RawClusterv1.h.
View newest version in sPHENIX GitHub at line 48 of file RawClusterv1.h
References RawClusterv1::_r.
Referenced by RawClusterv1::get_x(), RawClusterv1::get_y(), and RawClusterv1::identify().
virtual float RawCluster::get_r () const inline virtual
Reimplemented in RawClusterv1.
Definition at line 88 of file RawCluster.h.
View newest version in sPHENIX GitHub at line 88 of file RawCluster.h
References PHOOL_VIRTUAL_WARN.
Referenced by TreeMaker::CopyAndMakeClusters(), TrackProjectionTools::FindClosestTrack(), TrackProjectionTools::getCluster(), IsolatedTrackAnalysis::getClusters(), DISKinematicsReco::InsertCandidateFromCluster(), FilterEventsUpsilon::MatchClusterCEMC(), FilterEvents::MatchClusterCEMC(), sPHAnalysis::MatchClusterCEMC(), FilterEventsUpsilon::process_event(), FilterEvents::process_event(), and TreeMaker::UseFastJet().
const TowerMap& RawClusterv1::get_towermap () const inline override virtual
return tower map for c++11 range-based for-loop
Reimplemented from RawCluster.
Definition at line 39 of file RawClusterv1.h.
View newest version in sPHENIX GitHub at line 39 of file RawClusterv1.h
References RawClusterv1::towermap.
virtual const TowerMap& RawCluster::get_towermap () const inline virtual
return tower map for c++11 range-based for-loop
Reimplemented in RawClusterv1.
Definition at line 69 of file RawCluster.h.
View newest version in sPHENIX GitHub at line 69 of file RawCluster.h
References dummy, and PHOOL_VIRTUAL_WARN.
Referenced by TrackProjectionTools::FindClosestTrack(), and RawClusterBuilderGraph::process_event().
RawCluster::TowerConstRange RawClusterv1::get_towers () const inline override virtual
Reimplemented from RawCluster.
Definition at line 37 of file RawClusterv1.h.
View newest version in sPHENIX GitHub at line 37 of file RawClusterv1.h
References RawClusterv1::towermap.
virtual TowerConstRange RawCluster::get_towers () const inline virtual
Reimplemented in RawClusterv1.
Definition at line 62 of file RawCluster.h.
View newest version in sPHENIX GitHub at line 62 of file RawCluster.h
References dummy, and PHOOL_VIRTUAL_WARN.
Referenced by ExclusiveReco::AddInvariantMassInformation(), CaloRawClusterEval::all_truth_hits(), CaloRawClusterEval::all_truth_primary_showers(), cemcReco::calculateTSP(), CaloEvaluator::fillOutputNtuples(), TrackProjectorPlaneECAL::get_detector_from_cluster(), CaloRawClusterEval::get_energy_contribution(), STACalorimeterCharacterization::get_ordered_towers(), DISKinematicsReco::InsertCandidateFromCluster(), CaloRecoUtility::ProbCorrsZVertex(), RawClusterDeadHotMask::process_event(), RawClusterPositionCorrection::process_event(), CaloCalibEmc_Pi0::process_event(), CaloAna::process_towers(), and pi0EtaByEta::process_towers().
float RawClusterv1::get_x () const inline override virtual
access Cartesian coordinate system
Reimplemented from RawCluster.
Definition at line 57 of file RawClusterv1.h.
View newest version in sPHENIX GitHub at line 57 of file RawClusterv1.h
References RawClusterv1::get_phi(), and RawClusterv1::get_r().
Referenced by RawClusterv1::get_position(), and RawClusterv1::identify().
virtual float RawCluster::get_x () const inline virtual
access Cartesian coordinate system
Reimplemented in RawClusterv1.
Definition at line 129 of file RawCluster.h.
View newest version in sPHENIX GitHub at line 129 of file RawCluster.h
References PHOOL_VIRTUAL_WARN.
Referenced by CaloEvaluator::fillOutputNtuples(), TrackProjectionTools::FindClosestTrack(), TrackProjectorPlaneECAL::get_best_state(), TrackProjectorPlaneECAL::get_best_track(), DISKinematicsReco::InsertCandidateFromCluster(), FilterEventsUpsilon::MatchClusterCEMC(), FilterEvents::MatchClusterCEMC(), sPHAnalysis::MatchClusterCEMC(), VtxTest::numUnique(), CaloEvaluator::printOutputInfo(), CaloRecoUtility::ProbCorrsZVertex(), FilterEvents::process_event(), FilterEventsUpsilon::process_event(), sPHAnalysis::process_event_notracking(), sPHAnalysis_calo::process_event_test(), TrackProjectorPlaneECAL::project_track(), TruthConversionEval::recordConversion(), and CaloRecoUtility::ShowerDepthCorrZVertex().
float RawClusterv1::get_y () const inline override virtual
Reimplemented from RawCluster.
Definition at line 58 of file RawClusterv1.h.
View newest version in sPHENIX GitHub at line 58 of file RawClusterv1.h
References RawClusterv1::get_phi(), and RawClusterv1::get_r().
Referenced by RawClusterv1::get_position(), and RawClusterv1::identify().
virtual float RawCluster::get_y () const inline virtual
Reimplemented in RawClusterv1.
Definition at line 134 of file RawCluster.h.
View newest version in sPHENIX GitHub at line 134 of file RawCluster.h
References PHOOL_VIRTUAL_WARN.
Referenced by CaloEvaluator::fillOutputNtuples(), TrackProjectionTools::FindClosestTrack(), TrackProjectorPlaneECAL::get_best_state(), TrackProjectorPlaneECAL::get_best_track(), DISKinematicsReco::InsertCandidateFromCluster(), FilterEventsUpsilon::MatchClusterCEMC(), FilterEvents::MatchClusterCEMC(), sPHAnalysis::MatchClusterCEMC(), VtxTest::numUnique(), CaloEvaluator::printOutputInfo(), CaloRecoUtility::ProbCorrsZVertex(), FilterEvents::process_event(), FilterEventsUpsilon::process_event(), sPHAnalysis::process_event_notracking(), sPHAnalysis_calo::process_event_test(), TrackProjectorPlaneECAL::project_track(), TruthConversionEval::recordConversion(), and CaloRecoUtility::ShowerDepthCorrZVertex().
float RawClusterv1::get_z () const inline override virtual
Reimplemented from RawCluster.
Definition at line 49 of file RawClusterv1.h.
View newest version in sPHENIX GitHub at line 49 of file RawClusterv1.h
References RawClusterv1::_z.
Referenced by RawClusterv1::get_position(), and RawClusterv1::identify().
virtual float RawCluster::get_z () const inline virtual
Reimplemented in RawClusterv1.
Definition at line 93 of file RawCluster.h.
View newest version in sPHENIX GitHub at line 93 of file RawCluster.h
References PHOOL_VIRTUAL_WARN.
Referenced by cemcReco::coneSum(), PhotonJet::ConeSum(), TreeMaker::CopyAndMakeClusters(), CaloEvaluator::fillOutputNtuples(), TrackProjectionTools::FindClosestTrack(), TrackProjectorPlaneECAL::get_best_state(), TrackProjectorPlaneECAL::get_best_track(), TrackProjectionTools::getCluster(), IsolatedTrackAnalysis::getClusters(), DISKinematicsReco::InsertCandidateFromCluster(), FilterEventsUpsilon::MatchClusterCEMC(), FilterEvents::MatchClusterCEMC(), sPHAnalysis::MatchClusterCEMC(), VtxTest::numUnique(), CaloEvaluator::printOutputInfo(), CaloRecoUtility::ProbCorrsZVertex(), RawClusterZVertexRecorrect::process_event(), FilterEventsUpsilon::process_event(), FilterEvents::process_event(), sPHAnalysis::process_event_notracking(), sPHAnalysis_calo::process_event_test(), TrackProjectorPlaneECAL::project_track(), TruthConversionEval::recordConversion(), CaloRecoUtility::ShowerDepthCorrZVertex(), and TreeMaker::UseFastJet().
size_t RawClusterv1::getNTowers () const inline override virtual
Tower operations.
Reimplemented from RawCluster.
Definition at line 36 of file RawClusterv1.h.
View newest version in sPHENIX GitHub at line 36 of file RawClusterv1.h
References RawClusterv1::towermap.
Referenced by RawClusterv1::identify().
virtual size_t RawCluster::getNTowers () const inline virtual
Tower operations.
Reimplemented in RawClusterv1.
Definition at line 57 of file RawCluster.h.
View newest version in sPHENIX GitHub at line 57 of file RawCluster.h
References PHOOL_VIRTUAL_WARNING.
Referenced by CaloEvaluator::fillOutputNtuples(), EventEvaluator::fillOutputNtuples(), DISKinematicsReco::InsertCandidateFromCluster(), CaloEvaluator::printOutputInfo(), and caloTreeGen::process_event().