Analysis Software: Acts::TrackSelector::EtaBinnedConfig Struct Reference
Acts::TrackSelector::EtaBinnedConfig Struct Reference
#include <acts/blob/sPHENIX/Core/include/Acts/TrackFinding/TrackSelector.hpp>
Public Member Functions
std::size_t nEtaBins () const
EtaBinnedConfig ()
EtaBinnedConfig (double etaMin)
EtaBinnedConfig & addCuts (const std::function< void(Config &)> &callback={})
std::size_t binIndex (double eta) const
const Config & getCuts (double eta) const
Public Attributes
std::vector< Config > cutSets = {}
Cut sets for each eta bin.
std::vector< double > absEtaEdges = {}
Eta bin edges for varying cuts by eta.
absEtaEdges {{0, inf}} {}
Friends
std::ostream & operator<< (std::ostream &os, const EtaBinnedConfig &cfg)
Detailed Description
Main config object for the track selector. Combines a set of cut configurations and corresponding eta bins
Definition at line 104 of file TrackSelector.hpp.
View newest version in sPHENIX GitHub at line 104 of file TrackSelector.hpp
Constructor & Destructor Documentation
Acts::TrackSelector::EtaBinnedConfig::EtaBinnedConfig () inline
Construct an empty (accepts everything) configuration. Results in a single cut set and one abs eta bin from 0 to infinity.
Definition at line 117 of file TrackSelector.hpp.
View newest version in sPHENIX GitHub at line 117 of file TrackSelector.hpp
Acts::TrackSelector::EtaBinnedConfig::EtaBinnedConfig (double etaMin) inline
Constructor to create a config object that is not upper-bounded. This is useful to use the "fluent" API to populate the configuration.
Parameters
etaMin Minimum eta bin edge
Definition at line 122 of file TrackSelector.hpp.
View newest version in sPHENIX GitHub at line 122 of file TrackSelector.hpp
Member Function Documentation
TrackSelector::EtaBinnedConfig & Acts::TrackSelector::EtaBinnedConfig::addCuts (const std::function< void(Config &)> & callback = {}) inline
Add a new eta bin with an upper bound of +infinity.
Parameters
callback Callback to configure the cuts for this eta bin
Returns
Reference to this object
Definition at line 277 of file TrackSelector.hpp.
View newest version in sPHENIX GitHub at line 277 of file TrackSelector.hpp
Referenced by BOOST_AUTO_TEST_CASE().
std::size_t Acts::TrackSelector::EtaBinnedConfig::binIndex (double eta) const inline
Get the index of the eta bin for a given eta
Parameters
eta Eta value
Returns
Index of the eta bin
Definition at line 301 of file TrackSelector.hpp.
View newest version in sPHENIX GitHub at line 301 of file TrackSelector.hpp
References distance(), and index.
const TrackSelector::Config & Acts::TrackSelector::EtaBinnedConfig::getCuts (double eta) const inline
Get the cuts for a given eta
Parameters
eta Eta value
Returns
Cuts for the given eta
Definition at line 312 of file TrackSelector.hpp.
View newest version in sPHENIX GitHub at line 312 of file TrackSelector.hpp
References nEtaBins.
Referenced by Acts::TrackSelector::isValidTrack().
std::size_t Acts::TrackSelector::EtaBinnedConfig::nEtaBins () const inline
Get the number of eta bins
Returns
Number of eta bins
Definition at line 113 of file TrackSelector.hpp.
View newest version in sPHENIX GitHub at line 113 of file TrackSelector.hpp
References absEtaEdges.
Referenced by Acts::TrackSelector::TrackSelector().
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & os, const EtaBinnedConfig & cfg) friend
Print this configuration to an output stream
Parameters
os Output stream
cfg Configuration to print
Returns
Reference to the output stream
Definition at line 317 of file TrackSelector.hpp.
View newest version in sPHENIX GitHub at line 317 of file TrackSelector.hpp
Member Data Documentation
std::vector<double> Acts::TrackSelector::EtaBinnedConfig::absEtaEdges = {}
Eta bin edges for varying cuts by eta.
Definition at line 109 of file TrackSelector.hpp.
View newest version in sPHENIX GitHub at line 109 of file TrackSelector.hpp
Referenced by Acts::TrackSelector::isValidTrack(), nEtaBins(), Acts::operator<<(), and Acts::TrackSelector::TrackSelector().
Acts::TrackSelector::EtaBinnedConfig::absEtaEdges {{0, inf}} {}
Definition at line 117 of file TrackSelector.hpp.
View newest version in sPHENIX GitHub at line 117 of file TrackSelector.hpp
std::vector<Config> Acts::TrackSelector::EtaBinnedConfig::cutSets = {}
Cut sets for each eta bin.
Definition at line 106 of file TrackSelector.hpp.
View newest version in sPHENIX GitHub at line 106 of file TrackSelector.hpp
Referenced by BOOST_DATA_TEST_CASE(), Acts::TrackSelector::isValidTrack(), Acts::operator<<(), and Acts::TrackSelector::TrackSelector().
The documentation for this struct was generated from the following file:
acts/blob/sPHENIX/Core/include/Acts/TrackFinding/TrackSelector.hpp