Analysis Software: PHG4EPDetector Class Reference
PHG4EPDetector Class Reference
#include <coresoftware/blob/master/simulation/g4simulation/g4epd/PHG4EPDetector.h>
Public Member Functions
PHG4EPDetector (PHG4Subsystem *subsys, PHCompositeNode *node, PHParametersContainer *params, std::string const &name)
void ConstructMe (G4LogicalVolume *world) override
bool contains (G4VPhysicalVolume *) const
uint32_t module_id_for (int32_t index, int32_t slice, int32_t side)
uint32_t module_id_for (G4VPhysicalVolume *volume)
void SuperDetector (std::string const &name)
const std::string SuperDetector () const
Public Member Functions inherited from PHG4Detector
PHG4Detector ()=delete
constructor
PHG4Detector (PHG4Subsystem *subsys, PHCompositeNode *Node, const std::string &nam)
virtual ~PHG4Detector (void)
destructor
virtual void Construct (G4LogicalVolume *world) final
construct method
virtual void PostConstruction ()
Optional PostConstruction call after all geometry is constructed.
virtual void Verbosity (const int v)
virtual int Verbosity () const
virtual G4UserSteppingAction * GetSteppingAction ()
virtual std::string GetName () const
virtual void OverlapCheck (const bool chk)
virtual bool OverlapCheck () const
virtual void Print (const std::string &what="ALL") const
virtual int DisplayVolume (G4VSolid *volume, G4LogicalVolume *logvol, G4RotationMatrix *rotm=nullptr)
virtual int DisplayVolume (G4LogicalVolume *checksolid, G4LogicalVolume *logvol, G4RotationMatrix *rotm=nullptr)
virtual PHCompositeNode * topNode ()
virtual PHG4Subsystem * GetMySubsystem ()
Private Member Functions
G4ExtrudedSolid * construct_block (int32_t index)
Private Attributes
std::map< G4VPhysicalVolume
*, uint32_t > m_volumes
std::string superdetector
double m_z_position
Detailed Description
Definition at line 21 of file PHG4EPDetector.h.
View newest version in sPHENIX GitHub at line 21 of file PHG4EPDetector.h
Constructor & Destructor Documentation
PHG4EPDetector::PHG4EPDetector (PHG4Subsystem * subsys, PHCompositeNode * node, PHParametersContainer * params, std::string const & name)
Definition at line 26 of file PHG4EPDetector.cc.
View newest version in sPHENIX GitHub at line 26 of file PHG4EPDetector.cc
References PHParameters::get_double_param(), PHParametersContainer::GetParameters(), m_z_position, and pars.
Member Function Documentation
G4ExtrudedSolid * PHG4EPDetector::construct_block (int32_t index) private
Definition at line 135 of file PHG4EPDetector.cc.
View newest version in sPHENIX GitHub at line 135 of file PHG4EPDetector.cc
References coordinates, double(), dz, i, index, graph_fancy::label, Acts::UnitConstants::mm, nlohmann::to_string(), x, and y.
Referenced by ConstructMe().
void PHG4EPDetector::ConstructMe (G4LogicalVolume * world) override virtual
Implements PHG4Detector.
Definition at line 36 of file PHG4EPDetector.cc.
View newest version in sPHENIX GitHub at line 36 of file PHG4EPDetector.cc
References Acts::UnitConstants::cm, construct_block(), i, k, graph_fancy::label, M_PI, m_volumes, m_z_position, material, module_id_for(), PHG4Detector::OverlapCheck(), rotate::rotate(), nlohmann::to_string(), and Acts::Test::volume.
bool PHG4EPDetector::contains (G4VPhysicalVolume * volume) const
Definition at line 83 of file PHG4EPDetector.cc.
View newest version in sPHENIX GitHub at line 83 of file PHG4EPDetector.cc
References m_volumes.
Referenced by PHG4EPSteppingAction::UserSteppingAction().
uint32_t PHG4EPDetector::module_id_for (int32_t index, int32_t slice, int32_t side)
Definition at line 88 of file PHG4EPDetector.cc.
View newest version in sPHENIX GitHub at line 88 of file PHG4EPDetector.cc
Referenced by ConstructMe(), and PHG4EPSteppingAction::UserSteppingAction().
uint32_t PHG4EPDetector::module_id_for (G4VPhysicalVolume * volume)
Definition at line 94 of file PHG4EPDetector.cc.
View newest version in sPHENIX GitHub at line 94 of file PHG4EPDetector.cc
References m_volumes, and Acts::Test::volume.
void PHG4EPDetector::SuperDetector (std::string const & name) inline
Definition at line 36 of file PHG4EPDetector.h.
View newest version in sPHENIX GitHub at line 36 of file PHG4EPDetector.h
References name, and superdetector.
Referenced by PHG4EPDSubsystem::InitRunSubsystem(), and PHG4EPSteppingAction::SetInterfacePointers().
const std::string PHG4EPDetector::SuperDetector () const inline
Definition at line 37 of file PHG4EPDetector.h.
View newest version in sPHENIX GitHub at line 37 of file PHG4EPDetector.h
References superdetector.
Member Data Documentation
std::map<G4VPhysicalVolume*, uint32_t> PHG4EPDetector::m_volumes private
Definition at line 42 of file PHG4EPDetector.h.
View newest version in sPHENIX GitHub at line 42 of file PHG4EPDetector.h
Referenced by ConstructMe(), contains(), and module_id_for().
double PHG4EPDetector::m_z_position private
Definition at line 46 of file PHG4EPDetector.h.
View newest version in sPHENIX GitHub at line 46 of file PHG4EPDetector.h
Referenced by ConstructMe(), and PHG4EPDetector().
std::string PHG4EPDetector::superdetector private
Definition at line 44 of file PHG4EPDetector.h.
View newest version in sPHENIX GitHub at line 44 of file PHG4EPDetector.h
Referenced by SuperDetector().
The documentation for this class was generated from the following files:
coresoftware/blob/master/simulation/g4simulation/g4epd/PHG4EPDetector.h
coresoftware/blob/master/simulation/g4simulation/g4epd/PHG4EPDetector.cc