Analysis Software: macros/blob/master/CaloProduction/Fun4All_Year1.C File Reference
Fun4All_Year1.C File Reference
#include <caloreco/CaloTowerBuilder.h>
#include <caloreco/CaloTowerCalib.h>
#include <caloreco/CaloTowerStatus.h>
#include <caloreco/CaloWaveformProcessing.h>
#include <caloreco/DeadHotMapLoader.h>
#include <caloreco/RawClusterBuilderTemplate.h>
#include <caloreco/RawClusterDeadHotMask.h>
#include <caloreco/RawClusterPositionCorrection.h>
#include <caloreco/TowerInfoDeadHotMask.h>
#include <mbd/MbdReco.h>
#include <globalvertex/GlobalVertexReco.h>
#include <ffamodules/CDBInterface.h>
#include <ffamodules/FlagHandler.h>
#include <ffamodules/HeadReco.h>
#include <ffamodules/SyncReco.h>
#include <fun4allraw/Fun4AllPrdfInputManager.h>
#include <fun4all/Fun4AllDstInputManager.h>
#include <fun4all/Fun4AllDstOutputManager.h>
#include <fun4all/Fun4AllInputManager.h>
#include <fun4all/Fun4AllRunNodeInputManager.h>
#include <fun4all/Fun4AllServer.h>
#include <fun4all/Fun4AllUtils.h>
#include <fun4all/SubsysReco.h>
#include <phool/recoConsts.h>
#include <centrality/CentralityReco.h>
#include <calotrigger/MinimumBiasClassifier.h>
#include <calovalid/CaloValid.h>
Macros
#define FUN4ALL_YEAR1_C
Functions
void Fun4All_Year1 (const std::string &fname="/sphenix/lustre01/sphnxpro/commissioning/aligned_prdf/beam-00021774-0000.prdf", int nEvents=10)
Macro Definition Documentation
#define FUN4ALL_YEAR1_C
Definition at line 2 of file Fun4All_Year1.C.
View newest version in sPHENIX GitHub at line 2 of file Fun4All_Year1.C
Function Documentation
void Fun4All_Year1 (const std::string & fname = "/sphenix/lustre01/sphnxpro/commissioning/aligned_prdf/beam-00021774-0000.prdf", int nEvents = 10)
Definition at line 50 of file Fun4All_Year1.C.
View newest version in sPHENIX GitHub at line 50 of file Fun4All_Year1.C
References Fun4AllInputManager::AddFile(), CaloValid::apply_vertex_cut(), CaloTowerDefs::CEMC, RawClusterBuilderTemplate::Detector(), TowerInfoDeadHotMask::detector(), RawClusterDeadHotMask::detector(), DeadHotMapLoader::detector(), Fun4AllServer::End(), CaloWaveformProcessing::FAST, INTTVtxZ::fname, Fun4AllUtils::GetRunSegment(), CDBInterface::getUrl(), CaloTowerDefs::HCALIN, CaloTowerDefs::HCALOUT, recoConsts::instance(), CDBInterface::instance(), Fun4AllServer::instance(), CaloTowerDefs::kPRDFWaveform, CaloTowerDefs::kWaveformTowerv2, RawClusterBuilderTemplate::LoadProfile(), out, add_histos::outfile, CDBInterface::Print(), Fun4AllServer::PrintTimer(), Fun4AllServer::registerInputManager(), Fun4AllServer::registerOutputManager(), Fun4AllServer::registerSubsystem(), Fun4AllServer::run(), runnumber, Acts::Test::segment(), CaloTowerBuilder::set_builder_type(), CaloTowerBuilder::set_detector_type(), CaloTowerCalib::set_detector_type(), CaloTowerStatus::set_detector_type(), CaloTowerCalib::set_inputNodePrefix(), CaloTowerBuilder::set_nsamples(), CaloTowerCalib::set_outputNodePrefix(), CaloTowerBuilder::set_outputNodePrefix(), CaloTowerBuilder::set_processing_type(), CaloTowerBuilder::set_softwarezerosuppression(), PHFlag::set_StringFlag(), RawClusterBuilderTemplate::set_threshold_energy(), CaloTowerStatus::set_time_cut(), CaloValid::set_timing_cut_width(), PHFlag::set_uint64Flag(), RawClusterBuilderTemplate::set_UseTowerInfo(), RawClusterPositionCorrection::set_UseTowerInfo(), CaloValid::set_vertex_cut(), CaloWaveformProcessing::TEMPLATE, Fun4AllBase::Verbosity(), and CaloTowerDefs::ZDC.