Analysis Software: JetReco Class Reference
JetReco Class Reference
jet reco with user def inputs and algos
#include <coresoftware/blob/master/offline/packages/jetbase/JetReco.h>
Public Types
enum TRANSITION { JET_CONTAINER, JET_MAP, BOTH, PRETEND_BOTH }
Public Member Functions
JetReco (const std::string &name="JetReco", TRANSITION _which_fill=JET_CONTAINER)
~JetReco () override
int InitRun (PHCompositeNode *topNode) override
int process_event (PHCompositeNode *topNode) override
void add_input (JetInput *input)
void add_algo (JetAlgo *algo, std::string output)
void set_algo_node (const std::string &algonode)
void set_input_node (const std::string &inputnode)
JetAlgo * get_algo (unsigned int which_algo=0)
Public Member Functions inherited from SubsysReco
~SubsysReco () override
virtual int End (PHCompositeNode *)
Called at the end of all processing.
virtual int EndRun (const int)
Called at the end of each run.
virtual int Init (PHCompositeNode *)
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
void Print (const std::string &="ALL") const override
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Private Member Functions
int CreateNodes (PHCompositeNode *topNode)
void FillJetNode (PHCompositeNode *topNode, int ialgo, std::vector< Jet * > jets)
void FillJetContainer (PHCompositeNode *topNode, int ialgo, std::vector< Jet * > &jets)
std::string JC_name (std::string name)
Private Attributes
std::vector< JetInput * > _inputs
std::vector< JetAlgo * > _algos
std::string _algonode
std::string _inputnode
std::vector< std::string > _outputs
TRANSITION which_fill
bool use_jetcon
bool use_jetmap
Additional Inherited Members
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Detailed Description
jet reco with user def inputs and algos
This module can be used to reconstruct truth jets and will get me started on filling some jet nodes and getting source material for jet evaluation
Definition at line 31 of file JetReco.h.
View newest version in sPHENIX GitHub at line 31 of file JetReco.h
Member Enumeration Documentation
enum JetReco::TRANSITION
Enumerator:
JET_CONTAINER
JET_MAP
BOTH
PRETEND_BOTH
Definition at line 34 of file JetReco.h.
View newest version in sPHENIX GitHub at line 34 of file JetReco.h
Constructor & Destructor Documentation
JetReco::JetReco (const std::string & name = "JetReco", TRANSITION _which_fill = JET_CONTAINER)
Definition at line 32 of file JetReco.cc.
View newest version in sPHENIX GitHub at line 32 of file JetReco.cc
JetReco::~JetReco () override
Member Function Documentation
void JetReco::add_algo (JetAlgo * algo, std::string output) inline
Definition at line 49 of file JetReco.h.
View newest version in sPHENIX GitHub at line 49 of file JetReco.h
References _algos, and _outputs.
Referenced by Fun4All_Analysis(), Fun4All_Condor(), Fun4All_JetBkgd(), Fun4All_JetSub(), Fun4All_JetVal(), Fun4All_testEtIso_Hijing(), Fun4All_testEtIso_Pythia(), Fun4AllPythia(), G4_HIJetReco(), HIJetReco(), Jet_FwdReco(), Jet_Reco(), ParticleFlow(), and run_macro().
void JetReco::add_input (JetInput * input) inline
Definition at line 48 of file JetReco.h.
View newest version in sPHENIX GitHub at line 48 of file JetReco.h
References _inputs.
Referenced by Fun4All_Analysis(), Fun4All_Condor(), Fun4All_JetBkgd(), Fun4All_JetSub(), Fun4All_JetVal(), Fun4All_testEtIso_Hijing(), Fun4All_testEtIso_Pythia(), G4_HIJetReco(), HIJetReco(), Jet_FwdReco(), Jet_Reco(), ParticleFlow(), and run_macro().
int JetReco::CreateNodes (PHCompositeNode * topNode) private
void JetReco::FillJetContainer (PHCompositeNode * topNode, int ialgo, std::vector< Jet * > & jets) private
void JetReco::FillJetNode (PHCompositeNode * topNode, int ialgo, std::vector< Jet * > jets) private
JetAlgo* JetReco::get_algo (unsigned int which_algo = 0)
int JetReco::InitRun (PHCompositeNode *) override virtual
Called for first event when run number is known. Typically this is where you may want to fetch data from database, because you know the run number.
Reimplemented from SubsysReco.
std::string JetReco::JC_name (std::string name) inline private
Definition at line 75 of file JetReco.h.
View newest version in sPHENIX GitHub at line 75 of file JetReco.h
References perf_headwind::name, and which_fill.
int JetReco::process_event (PHCompositeNode *) override virtual
Called for each event. This is where you do the real work.
Reimplemented from SubsysReco.
void JetReco::set_algo_node (const std::string & algonode) inline
Definition at line 55 of file JetReco.h.
View newest version in sPHENIX GitHub at line 55 of file JetReco.h
References _algonode.
Referenced by Fun4All_Analysis(), Fun4All_Condor(), Fun4All_JetBkgd(), Fun4All_JetSub(), Fun4All_JetVal(), Fun4All_testEtIso_Hijing(), Fun4All_testEtIso_Pythia(), Fun4AllPythia(), G4_HIJetReco(), HIJetReco(), Jet_FwdReco(), Jet_Reco(), ParticleFlow(), and run_macro().
void JetReco::set_input_node (const std::string & inputnode) inline
Definition at line 56 of file JetReco.h.
View newest version in sPHENIX GitHub at line 56 of file JetReco.h
References _inputnode.
Referenced by Fun4All_Analysis(), Fun4All_Condor(), Fun4All_JetBkgd(), Fun4All_JetSub(), Fun4All_JetVal(), Fun4All_testEtIso_Hijing(), Fun4All_testEtIso_Pythia(), Fun4AllPythia(), G4_HIJetReco(), HIJetReco(), Jet_FwdReco(), Jet_Reco(), ParticleFlow(), and run_macro().
Member Data Documentation
std::string JetReco::_algonode private
Definition at line 68 of file JetReco.h.
View newest version in sPHENIX GitHub at line 68 of file JetReco.h
Referenced by set_algo_node().
std::vector<JetAlgo *> JetReco::_algos private
Definition at line 67 of file JetReco.h.
View newest version in sPHENIX GitHub at line 67 of file JetReco.h
Referenced by add_algo().
std::string JetReco::_inputnode private
Definition at line 69 of file JetReco.h.
View newest version in sPHENIX GitHub at line 69 of file JetReco.h
Referenced by set_input_node().
std::vector<JetInput *> JetReco::_inputs private
Definition at line 66 of file JetReco.h.
View newest version in sPHENIX GitHub at line 66 of file JetReco.h
Referenced by add_input().
std::vector<std::string> JetReco::_outputs private
Definition at line 70 of file JetReco.h.
View newest version in sPHENIX GitHub at line 70 of file JetReco.h
Referenced by add_algo().
bool JetReco::use_jetcon private
Definition at line 80 of file JetReco.h.
View newest version in sPHENIX GitHub at line 80 of file JetReco.h
bool JetReco::use_jetmap private
Definition at line 81 of file JetReco.h.
View newest version in sPHENIX GitHub at line 81 of file JetReco.h
TRANSITION JetReco::which_fill private
Definition at line 79 of file JetReco.h.
View newest version in sPHENIX GitHub at line 79 of file JetReco.h
Referenced by JC_name().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/jetbase/JetReco.h
coresoftware/blob/master/offline/packages/jetbase/JetReco.cc