Analysis Software: Acts::FullBilloirVertexFitter< input_track_t, linearizer_t > Class Template Reference
Acts::FullBilloirVertexFitter< input_track_t, linearizer_t > Class Template Reference
Vertex fitter class implementing the Billoir vertex fitter.
#include <acts/blob/sPHENIX/Core/include/Acts/Vertexing/FullBilloirVertexFitter.hpp>
Classes
struct Config
struct State
Public Types
using InputTrack_t = input_track_t
using Propagator_t = typename linearizer_t::Propagator_t
using Linearizer_t = linearizer_t
Public Member Functions
template<typename T = input_track_t, std::enable_if_t< std::is_same< T, BoundTrackParameters >::value, int > = 0>
FullBilloirVertexFitter (const Config &cfg)
Constructor used if input_track_t type == BoundTrackParameters.
extractParameters (func)
Result< Vertex< input_track_t > > fit (const std::vector< const input_track_t * > &paramVector, const linearizer_t &linearizer, const VertexingOptions< input_track_t > &vertexingOptions, State &state) const
Fit method, fitting vertex for provided tracks with constraint.
Private Attributes
Config m_cfg
Configuration object.
std::function
< BoundTrackParameters(input_track_t)> extractParameters
Function to extract track parameters, input_track_t objects are BoundTrackParameters by default, function to be overwritten to return BoundTrackParameters for other input_track_t objects.
Detailed Description
template<typename input_track_t, typename linearizer_t>
class Acts::FullBilloirVertexFitter< input_track_t, linearizer_t >
Vertex fitter class implementing the Billoir vertex fitter.
This class implements the Billoir vertex fitter from Ref. (1). It is also useful to have a look at Ref. (2). Note that the Billoir vertex fitter outputs one 4D vertex position and nTrack momenta at this very point.
Ref. (1): Fast vertex fitting with a local parametrization of tracks. Author(s) Billoir, P ; Qian, S In: Nucl. Instrum. Methods Phys. Res., A 311 (1992) 139-150 DOI 10.1016/0168-9002(92)90859-3
Ref. (2): Pattern Recognition, Tracking and Vertex Reconstruction in Particle Detectors. Author(s) Fruehwirth, R ; Strandli, A
Template Parameters
input_track_t Track object type
linearizer_t Track linearizer type
Definition at line 43 of file FullBilloirVertexFitter.hpp.
View newest version in sPHENIX GitHub at line 43 of file FullBilloirVertexFitter.hpp
Member Typedef Documentation
template<typename input_track_t , typename linearizer_t > using Acts::FullBilloirVertexFitter< input_track_t, linearizer_t >::InputTrack_t = input_track_t
Definition at line 48 of file FullBilloirVertexFitter.hpp.
View newest version in sPHENIX GitHub at line 48 of file FullBilloirVertexFitter.hpp
template<typename input_track_t , typename linearizer_t > using Acts::FullBilloirVertexFitter< input_track_t, linearizer_t >::Linearizer_t = linearizer_t
Definition at line 50 of file FullBilloirVertexFitter.hpp.
View newest version in sPHENIX GitHub at line 50 of file FullBilloirVertexFitter.hpp
template<typename input_track_t , typename linearizer_t > using Acts::FullBilloirVertexFitter< input_track_t, linearizer_t >::Propagator_t = typename linearizer_t::Propagator_t
Definition at line 49 of file FullBilloirVertexFitter.hpp.
View newest version in sPHENIX GitHub at line 49 of file FullBilloirVertexFitter.hpp
Constructor & Destructor Documentation
template<typename input_track_t , typename linearizer_t > template<typename T = input_track_t, std::enable_if_t< std::is_same< T, BoundTrackParameters >::value, int > = 0> Acts::FullBilloirVertexFitter< input_track_t, linearizer_t >::FullBilloirVertexFitter (const Config & cfg) inline
Constructor used if input_track_t type == BoundTrackParameters.
Parameters
cfg Configuration object
Definition at line 73 of file FullBilloirVertexFitter.hpp.
View newest version in sPHENIX GitHub at line 73 of file FullBilloirVertexFitter.hpp
Member Function Documentation
template<typename input_track_t , typename linearizer_t > Acts::FullBilloirVertexFitter< input_track_t, linearizer_t >::extractParameters (func) inline
Definition at line 85 of file FullBilloirVertexFitter.hpp.
View newest version in sPHENIX GitHub at line 85 of file FullBilloirVertexFitter.hpp
template<typename input_track_t , typename linearizer_t > Acts::Result< Acts::Vertex< input_track_t > > Acts::FullBilloirVertexFitter< input_track_t, linearizer_t >::fit (const std::vector< const input_track_t * > & paramVector, const linearizer_t & linearizer, const VertexingOptions< input_track_t > & vertexingOptions, State & state) const
Fit method, fitting vertex for provided tracks with constraint.
Parameters
paramVector Vector of track objects to fit vertex to
linearizer The track linearizer
vertexingOptions Vertexing options
state The state object
Returns
Fitted vertex
Definition at line 60 of file FullBilloirVertexFitter.ipp.
View newest version in sPHENIX GitHub at line 60 of file FullBilloirVertexFitter.ipp
References Acts::VertexingOptions< input_track_t >::constraint, Acts::Test::cov, E, Acts::eBoundLoc0, Acts::eBoundLoc1, Acts::eBoundPhi, Acts::eBoundQOverP, Acts::eBoundTheta, Acts::eBoundTime, Acts::eFreeTime, Acts::VertexingOptions< input_track_t >::geoContext, Acts::FullBilloirVertexFitter< input_track_t, linearizer_t >::State::linearizerState, m_cfg(), Acts::VertexingOptions< input_track_t >::magFieldContext, testing::internal::move(), nIter, Acts::detail::normalizePhiTheta(), ActsTests::PropagationDatasets::phi, position, Acts::Vertex< input_track_t >::setFitQuality(), Acts::Vertex< input_track_t >::setFullCovariance(), Acts::Vertex< input_track_t >::setFullPosition(), Acts::Vertex< input_track_t >::setTracksAtVertex(), ActsTests::PropagationDatasets::theta, and Acts::VertexingOptions< input_track_t >::useConstraintInFit.
Referenced by ActsExamples::VertexFitterAlgorithm::execute().
Member Data Documentation
template<typename input_track_t , typename linearizer_t > std::function<BoundTrackParameters(input_track_t)> Acts::FullBilloirVertexFitter< input_track_t, linearizer_t >::extractParameters private
Function to extract track parameters, input_track_t objects are BoundTrackParameters by default, function to be overwritten to return BoundTrackParameters for other input_track_t objects.
Definition at line 109 of file FullBilloirVertexFitter.hpp.
View newest version in sPHENIX GitHub at line 109 of file FullBilloirVertexFitter.hpp
template<typename input_track_t , typename linearizer_t > Config Acts::FullBilloirVertexFitter< input_track_t, linearizer_t >::m_cfg private
Configuration object.
Definition at line 103 of file FullBilloirVertexFitter.hpp.
View newest version in sPHENIX GitHub at line 103 of file FullBilloirVertexFitter.hpp
The documentation for this class was generated from the following files:
acts/blob/sPHENIX/Core/include/Acts/Vertexing/FullBilloirVertexFitter.hpp
acts/blob/sPHENIX/Core/include/Acts/Vertexing/FullBilloirVertexFitter.ipp