Analysis Software: TowerInfo Class Reference
TowerInfo Class Reference
#include <coresoftware/blob/master/offline/packages/CaloBase/TowerInfo.h>
Public Member Functions
TowerInfo ()=default
~TowerInfo () override=default
void Reset () override
Clear Event.
virtual void set_time (short)
virtual short get_time ()
virtual void set_energy (float)
virtual float get_energy ()
virtual void copy_tower (TowerInfo *)
virtual void set_time_float (float)
virtual float get_time_float ()
virtual void set_chi2 (float)
virtual float get_chi2 ()
virtual void set_pedestal (float)
virtual float get_pedestal ()
virtual void set_isHot (bool)
virtual bool get_isHot () const
virtual void set_isBadTime (bool)
virtual bool get_isBadTime () const
virtual void set_isBadChi2 (bool)
virtual bool get_isBadChi2 () const
virtual void set_isNotInstr (bool)
virtual bool get_isNotInstr () const
virtual void set_isNoCalib (bool)
virtual bool get_isNoCalib () const
virtual bool get_isGood () const
virtual uint8_t get_status () const
virtual void set_status (uint8_t)
virtual int get_nsample () const
virtual int16_t get_waveform_value (int) const
virtual void set_waveform_value (int, int16_t)
Public Member Functions inherited from PHObject
PHObject ()
ctor
~PHObject () override
dtor
virtual PHObject * CloneMe () const
Virtual copy constructor.
virtual PHObject * clone () const final
PHObject * Clone (const char *newname="") const final
void Copy (TObject &object) const final
virtual void identify (std::ostream &os=std::cout) const
virtual int isValid () const
isValid returns non zero if object contains vailid data
virtual int Integrate () const
virtual int Integrate (PHObject *)
virtual void CopyFrom (const PHObject *obj)
Private Member Functions
ClassDefOverride (TowerInfo, 1)
Detailed Description
Definition at line 8 of file TowerInfo.h.
View newest version in sPHENIX GitHub at line 8 of file TowerInfo.h
Constructor & Destructor Documentation
TowerInfo::TowerInfo () default
TowerInfo::~TowerInfo () override default
Member Function Documentation
TowerInfo::ClassDefOverride (TowerInfo , 1) private
virtual void TowerInfo::copy_tower (TowerInfo *) inline virtual
Reimplemented in TowerInfov2, TowerInfov1, and TowerInfov3.
Definition at line 19 of file TowerInfo.h.
View newest version in sPHENIX GitHub at line 19 of file TowerInfo.h
Referenced by CaloTowerCalib::process_event().
virtual float TowerInfo::get_chi2 () inline virtual
Reimplemented in TowerInfov2.
Definition at line 24 of file TowerInfo.h.
View newest version in sPHENIX GitHub at line 24 of file TowerInfo.h
Referenced by TowerInfov2::copy_tower(), CaloTowerStatus::process_event(), DumpTowerInfoContainer::process_Node(), HCalCalibTree::process_towers(), CaloAna::process_towers(), and CaloValid::process_towers().
virtual float TowerInfo::get_energy () inline virtual
Reimplemented in BbcPmtInfoV1, and TowerInfov1.
Definition at line 18 of file TowerInfo.h.
View newest version in sPHENIX GitHub at line 18 of file TowerInfo.h
Referenced by TowerInfov1::copy_tower(), TowerInfov2::copy_tower(), MinimumBiasClassifier::FillMinimumBiasInfo(), HCalJetPhiShift::FillTTree(), TowerJetInput::get_input(), MultiDetectorMultiplicity::getEMCalTotalEnergy(), MultiDetectorMultiplicity::getIHCalTotalEnergy(), MultiDetectorMultiplicity::getOHCalTotalEnergy(), MultiDetectorMultiplicity::getsEPDTotalEnergy(), RawClusterBuilderTemplate::IsAcceptableTower(), PHG4InnerHcalSteppingAction::NoHitSteppingAction(), PHG4OuterHcalSteppingAction::NoHitSteppingAction(), PHG4IHCalSteppingAction::NoHitSteppingAction(), PHG4OHCalSteppingAction::NoHitSteppingAction(), PHG4SpacalSteppingAction::NoHitSteppingAction(), BbcCheck::process_emcal(), RawTowerBuilder::process_event(), RawClusterDeadHotMask::process_event(), G4RawTowerTTree::process_event(), RawClusterBuilderTemplate::process_event(), G4ScintillatorTowerTTree::process_event(), Emcal_Tower_Masking::process_event(), RawClusterPositionCorrection::process_event(), RawTowerDeadTowerInterp::process_event(), HcalRawTowerBuilder::process_event(), EventPlaneReco::process_event(), RawClusterBuilderTopo::process_event(), CaloTowerCalib::process_event(), RawTowerCalibration::process_event(), G4TowerNtuple::process_event(), ClusterIso::process_event(), SubtractTowers::process_event(), RawTowerDigitizer::process_event(), CopyAndSubtractJets::process_event(), RetowerCEMC::process_event(), CaloTriggerSim::process_event(), caloTowerEmbed::process_event(), DetermineTowerBackground::process_event(), PHGenFitTrackProjection::process_event(), JetNconstituents::process_event(), JetBkgdSub::process_event(), LiteCaloEval::process_event(), JetValidation::process_event(), EMJetVal::process_event(), sPHAnalysis_calo::process_event_data(), BbcCheck::process_ihcal(), DumpTowerInfoContainer::process_Node(), BbcCheck::process_ohcal(), HCalCalibTree::process_towers(), CaloAna::process_towers(), CaloValid::process_towers(), pi0EtaByEta::process_towers(), BbcCheck::process_zdc(), RawTowerDigitizer::simple_photon_digitization(), RawTowerDigitizer::sipm_photon_digitization(), and TowerInfov1::TowerInfov1().
virtual bool TowerInfo::get_isBadChi2 () const inline virtual
Reimplemented in TowerInfov2.
Definition at line 32 of file TowerInfo.h.
View newest version in sPHENIX GitHub at line 32 of file TowerInfo.h
Referenced by RawClusterBuilderTemplate::IsAcceptableTower(), CaloAna::process_towers(), CaloValid::process_towers(), and pi0EtaByEta::process_towers().
virtual bool TowerInfo::get_isBadTime () const inline virtual
Reimplemented in TowerInfov2.
Definition at line 30 of file TowerInfo.h.
View newest version in sPHENIX GitHub at line 30 of file TowerInfo.h
Referenced by RawClusterBuilderTemplate::IsAcceptableTower(), and DumpTowerInfoContainer::process_Node().
virtual bool TowerInfo::get_isGood () const inline virtual
Reimplemented in TowerInfov2.
Definition at line 37 of file TowerInfo.h.
View newest version in sPHENIX GitHub at line 37 of file TowerInfo.h
Referenced by LiteCaloEval::process_event(), DumpTowerInfoContainer::process_Node(), and CaloValid::process_towers().
virtual bool TowerInfo::get_isHot () const inline virtual
Reimplemented in TowerInfov2.
Definition at line 28 of file TowerInfo.h.
View newest version in sPHENIX GitHub at line 28 of file TowerInfo.h
Referenced by RawClusterBuilderTemplate::IsAcceptableTower(), and DumpTowerInfoContainer::process_Node().
virtual bool TowerInfo::get_isNoCalib () const inline virtual
Reimplemented in TowerInfov2.
Definition at line 36 of file TowerInfo.h.
View newest version in sPHENIX GitHub at line 36 of file TowerInfo.h
virtual bool TowerInfo::get_isNotInstr () const inline virtual
Reimplemented in TowerInfov2.
Definition at line 34 of file TowerInfo.h.
View newest version in sPHENIX GitHub at line 34 of file TowerInfo.h
Referenced by RawClusterBuilderTemplate::IsAcceptableTower(), and DumpTowerInfoContainer::process_Node().
virtual int TowerInfo::get_nsample () const inline virtual
Reimplemented in TowerInfov3.
Definition at line 41 of file TowerInfo.h.
View newest version in sPHENIX GitHub at line 41 of file TowerInfo.h
Referenced by DumpTowerInfoContainer::process_Node().
virtual float TowerInfo::get_pedestal () inline virtual
Reimplemented in TowerInfov2.
Definition at line 26 of file TowerInfo.h.
View newest version in sPHENIX GitHub at line 26 of file TowerInfo.h
Referenced by TowerInfov2::copy_tower(), and DumpTowerInfoContainer::process_Node().
virtual uint8_t TowerInfo::get_status () const inline virtual
Reimplemented in TowerInfov2.
Definition at line 38 of file TowerInfo.h.
View newest version in sPHENIX GitHub at line 38 of file TowerInfo.h
Referenced by TowerInfov2::copy_tower(), DumpTowerInfoContainer::process_Node(), and CaloValid::process_towers().
virtual short TowerInfo::get_time () inline virtual
Reimplemented in TowerInfov1, and TowerInfov2.
Definition at line 16 of file TowerInfo.h.
View newest version in sPHENIX GitHub at line 16 of file TowerInfo.h
Referenced by TowerInfov1::copy_tower(), TowerJetInput::get_input(), BbcCheck::process_emcal(), RawClusterBuilderTemplate::process_event(), Emcal_Tower_Masking::process_event(), SubtractTowers::process_event(), RetowerCEMC::process_event(), DetermineTowerBackground::process_event(), sPHAnalysis_calo::process_event_data(), BbcCheck::process_ihcal(), DumpTowerInfoContainer::process_Node(), BbcCheck::process_ohcal(), CaloAna::process_towers(), CaloValid::process_towers(), BbcCheck::process_zdc(), and TowerInfov1::TowerInfov1().
virtual float TowerInfo::get_time_float () inline virtual
Reimplemented in TowerInfov2.
Definition at line 22 of file TowerInfo.h.
View newest version in sPHENIX GitHub at line 22 of file TowerInfo.h
Referenced by TowerInfov2::copy_tower(), CaloTowerStatus::process_event(), DumpTowerInfoContainer::process_Node(), CaloAna::process_towers(), and CaloValid::process_towers().
virtual int16_t TowerInfo::get_waveform_value (int) const inline virtual
Reimplemented in TowerInfov3.
Definition at line 42 of file TowerInfo.h.
View newest version in sPHENIX GitHub at line 42 of file TowerInfo.h
Referenced by TowerInfov3::copy_tower(), CaloWaveformSim::process_event(), DumpTowerInfoContainer::process_Node(), and CaloTowerBuilder::process_sim().
void TowerInfo::Reset () inline override virtual
Clear Event.
Reimplemented from PHObject.
Reimplemented in TowerInfov1, BbcPmtInfoV1, TowerInfov3, and TowerInfov2.
Definition at line 13 of file TowerInfo.h.
View newest version in sPHENIX GitHub at line 13 of file TowerInfo.h
virtual void TowerInfo::set_chi2 (float) inline virtual
Reimplemented in TowerInfov2.
Definition at line 23 of file TowerInfo.h.
View newest version in sPHENIX GitHub at line 23 of file TowerInfo.h
Referenced by CaloTowerBuilder::process_event(), and CaloTowerBuilder::process_sim().
virtual void TowerInfo::set_energy (float) inline virtual
Reimplemented in BbcPmtInfoV1, and TowerInfov1.
Definition at line 17 of file TowerInfo.h.
View newest version in sPHENIX GitHub at line 17 of file TowerInfo.h
Referenced by PHG4InnerHcalSteppingAction::NoHitSteppingAction(), PHG4OuterHcalSteppingAction::NoHitSteppingAction(), PHG4IHCalSteppingAction::NoHitSteppingAction(), PHG4OHCalSteppingAction::NoHitSteppingAction(), PHG4SpacalSteppingAction::NoHitSteppingAction(), RawTowerBuilder::process_event(), TowerInfoDeadHotMask::process_event(), Emcal_Tower_Masking::process_event(), RawTowerDeadTowerInterp::process_event(), HcalRawTowerBuilder::process_event(), PHG4EPDModuleReco::process_event(), CaloTowerBuilder::process_event(), RawTowerCalibration::process_event(), SubtractTowers::process_event(), RawTowerDigitizer::process_event(), RetowerCEMC::process_event(), caloTowerEmbed::process_event(), CaloTowerBuilder::process_sim(), RawTowerDigitizer::simple_photon_digitization(), and RawTowerDigitizer::sipm_photon_digitization().
virtual void TowerInfo::set_isBadChi2 (bool) inline virtual
Reimplemented in TowerInfov2.
Definition at line 31 of file TowerInfo.h.
View newest version in sPHENIX GitHub at line 31 of file TowerInfo.h
Referenced by CaloTowerStatus::process_event().
virtual void TowerInfo::set_isBadTime (bool) inline virtual
Reimplemented in TowerInfov2.
Definition at line 29 of file TowerInfo.h.
View newest version in sPHENIX GitHub at line 29 of file TowerInfo.h
Referenced by CaloTowerStatus::process_event().
virtual void TowerInfo::set_isHot (bool) inline virtual
Reimplemented in TowerInfov2.
Definition at line 27 of file TowerInfo.h.
View newest version in sPHENIX GitHub at line 27 of file TowerInfo.h
Referenced by CaloTowerStatus::process_event().
virtual void TowerInfo::set_isNoCalib (bool) inline virtual
Reimplemented in TowerInfov2.
Definition at line 35 of file TowerInfo.h.
View newest version in sPHENIX GitHub at line 35 of file TowerInfo.h
virtual void TowerInfo::set_isNotInstr (bool) inline virtual
Reimplemented in TowerInfov2.
Definition at line 33 of file TowerInfo.h.
View newest version in sPHENIX GitHub at line 33 of file TowerInfo.h
Referenced by CaloTowerBuilder::process_event(), and CaloTowerBuilder::process_sim().
virtual void TowerInfo::set_pedestal (float) inline virtual
Reimplemented in TowerInfov2.
Definition at line 25 of file TowerInfo.h.
View newest version in sPHENIX GitHub at line 25 of file TowerInfo.h
Referenced by CaloTowerBuilder::process_event(), and CaloTowerBuilder::process_sim().
virtual void TowerInfo::set_status (uint8_t) inline virtual
Reimplemented in TowerInfov2.
Definition at line 39 of file TowerInfo.h.
View newest version in sPHENIX GitHub at line 39 of file TowerInfo.h
Referenced by CaloTowerStatus::process_event().
virtual void TowerInfo::set_time (short) inline virtual
Reimplemented in TowerInfov1, and TowerInfov2.
Definition at line 15 of file TowerInfo.h.
View newest version in sPHENIX GitHub at line 15 of file TowerInfo.h
Referenced by TowerInfoDeadHotMask::process_event(), Emcal_Tower_Masking::process_event(), CaloTowerBuilder::process_event(), SubtractTowers::process_event(), RetowerCEMC::process_event(), and CaloTowerBuilder::process_sim().
virtual void TowerInfo::set_time_float (float) inline virtual
Reimplemented in TowerInfov2.
Definition at line 21 of file TowerInfo.h.
View newest version in sPHENIX GitHub at line 21 of file TowerInfo.h
Referenced by CaloTowerBuilder::process_event(), and CaloTowerBuilder::process_sim().
virtual void TowerInfo::set_waveform_value (int , int16_t) inline virtual
Reimplemented in TowerInfov3.
Definition at line 43 of file TowerInfo.h.
View newest version in sPHENIX GitHub at line 43 of file TowerInfo.h
Referenced by CaloTowerBuilder::process_event(), CaloWaveformSim::process_event(), and CaloTowerBuilder::process_sim().
The documentation for this class was generated from the following file:
coresoftware/blob/master/offline/packages/CaloBase/TowerInfo.h