Analysis Software: ActsExamples::CsvMultiTrajectoryWriter Class Reference
ActsExamples::CsvMultiTrajectoryWriter Class Reference
#include <acts/blob/sPHENIX/Examples/Io/Csv/include/ActsExamples/Io/Csv/CsvMultiTrajectoryWriter.hpp>
Classes
struct Config
struct trackInfo
Struct for brief trajectory summary info.
Public Types
using HitParticlesMap = ActsExamples::IndexMultimap< ActsFatras::Barcode >
Public Member Functions
CsvMultiTrajectoryWriter (const Config &config, Acts::Logging::Level level=Acts::Logging::INFO)
const Config & config () const
Readonly access to the config.
Public Member Functions inherited from ActsExamples::WriterT< TrajectoriesContainer >
WriterT (std::string objectName, std::string writerName, Acts::Logging::Level level)
std::string name () const override
Provide the name of the writer.
ProcessCode write (const AlgorithmContext &context) override
Read the object and call the type-specific member function.
ProcessCode finalize () override
No-op default implementation.
Public Member Functions inherited from ActsExamples::IWriter
ProcessCode internalExecute (const AlgorithmContext &context) final
ProcessCode initialize () override
Fulfil the algorithm interface.
Public Member Functions inherited from ActsExamples::SequenceElement
virtual ~SequenceElement ()=default
const std::vector< const
DataHandleBase * > & writeHandles () const
const std::vector< const
DataHandleBase * > & readHandles () const
Protected Member Functions
ProcessCode writeT (const AlgorithmContext &context, const TrajectoriesContainer &trajectories) override
Write method called by the base class.
Protected Member Functions inherited from ActsExamples::WriterT< TrajectoriesContainer >
const Acts::Logger & logger () const
Private Attributes
Config m_cfg
Nested configuration struct.
ReadDataHandle< HitParticlesMap > m_inputMeasurementParticlesMap
Detailed Description
Write out the tracks reconstructed using Combinatorial Kalman Filter in comma-separated-value format.
This writes one file per event into the configured output directory. By default it writes to the current working directory. Files are named using the following schema
event000000001-tracks_{algorithm_name}.csv
event000000002-tracks_{algorithm_name}.csv
and each line in the file corresponds to one track.
Definition at line 49 of file CsvMultiTrajectoryWriter.hpp.
View newest version in sPHENIX GitHub at line 49 of file CsvMultiTrajectoryWriter.hpp
Member Typedef Documentation
using ActsExamples::CsvMultiTrajectoryWriter::HitParticlesMap = ActsExamples::IndexMultimap<ActsFatras::Barcode>
Definition at line 51 of file CsvMultiTrajectoryWriter.hpp.
View newest version in sPHENIX GitHub at line 51 of file CsvMultiTrajectoryWriter.hpp
Constructor & Destructor Documentation
CsvMultiTrajectoryWriter::CsvMultiTrajectoryWriter (const Config & config, Acts::Logging::Level level = Acts::Logging::INFO)
constructor
Parameters
config is the configuration object
level is the output logging level
Definition at line 38 of file CsvMultiTrajectoryWriter.cpp.
View newest version in sPHENIX GitHub at line 38 of file CsvMultiTrajectoryWriter.cpp
References ActsExamples::ReadDataHandle< T >::initialize(), ActsExamples::CsvMultiTrajectoryWriter::Config::inputMeasurementParticlesMap, ActsExamples::CsvMultiTrajectoryWriter::Config::inputTrajectories, m_cfg, and m_inputMeasurementParticlesMap.
Member Function Documentation
const Config& ActsExamples::CsvMultiTrajectoryWriter::config () const inline
Readonly access to the config.
Definition at line 73 of file CsvMultiTrajectoryWriter.hpp.
View newest version in sPHENIX GitHub at line 73 of file CsvMultiTrajectoryWriter.hpp
References m_cfg().
ProcessCode CsvMultiTrajectoryWriter::writeT (const AlgorithmContext & context, const TrajectoriesContainer & trajectories) override protected virtual
Write method called by the base class.
Parameters
[in] context is the algorithm context for consistency
[in] tracks is the track collection
Implements ActsExamples::WriterT< TrajectoriesContainer >.
Definition at line 50 of file CsvMultiTrajectoryWriter.cpp.
View newest version in sPHENIX GitHub at line 50 of file CsvMultiTrajectoryWriter.cpp
References ACTS_WARNING, Acts::MultiTrajectoryHelpers::TrajectoryState::chi2Sum, Acts::VectorHelpers::eta(), ActsExamples::AlgorithmContext::eventNumber, ActsExamples::CsvMultiTrajectoryWriter::Config::fileName, ActsExamples::CsvMultiTrajectoryWriter::trackInfo::fittedParameters, ActsExamples::identifyContributingParticles(), check_smearing_config::lhs, m_cfg, m_inputMeasurementParticlesMap, Acts::MeasurementFlag, ActsExamples::CsvMultiTrajectoryWriter::trackInfo::measurementsID, momentum, Acts::MultiTrajectoryHelpers::TrajectoryState::NDF, Acts::MultiTrajectoryHelpers::TrajectoryState::nHoles, RecoTrackInfo::nMajorityHits, ActsExamples::CsvMultiTrajectoryWriter::trackInfo::nMajorityHits, Acts::MultiTrajectoryHelpers::TrajectoryState::nMeasurements, ActsExamples::CsvMultiTrajectoryWriter::Config::nMeasurementsMin, Acts::MultiTrajectoryHelpers::TrajectoryState::nOutliers, Acts::MultiTrajectoryHelpers::TrajectoryState::nSharedHits, Acts::MultiTrajectoryHelpers::TrajectoryState::nStates, ActsExamples::CsvMultiTrajectoryWriter::Config::onlyTruthMatched, out, ActsExamples::CsvMultiTrajectoryWriter::Config::outputDir, ActsExamples::CsvMultiTrajectoryWriter::Config::outputPrecision, ActsExamples::CsvMultiTrajectoryWriter::trackInfo::particleId, path, ActsExamples::perEventFilepath(), Acts::VectorHelpers::perp(), Acts::VectorHelpers::phi(), graph_fancy::pT, ActsExamples::CsvMultiTrajectoryWriter::Config::ptMin, check_smearing_config::rhs, Acts::Experimental::detail::BlueprintHelper::sort(), filter::state, SUCCESS, ActsExamples::CsvMultiTrajectoryWriter::trackInfo::trackId, ActsExamples::CsvMultiTrajectoryWriter::trackInfo::trackType, Acts::MultiTrajectoryHelpers::trajectoryState(), ActsExamples::CsvMultiTrajectoryWriter::trackInfo::truthMatchProb, and ActsExamples::CsvMultiTrajectoryWriter::Config::truthMatchProbMin.
Member Data Documentation
Config ActsExamples::CsvMultiTrajectoryWriter::m_cfg private
Nested configuration struct.
Definition at line 83 of file CsvMultiTrajectoryWriter.hpp.
View newest version in sPHENIX GitHub at line 83 of file CsvMultiTrajectoryWriter.hpp
Referenced by CsvMultiTrajectoryWriter(), and writeT().
ReadDataHandle<HitParticlesMap> ActsExamples::CsvMultiTrajectoryWriter::m_inputMeasurementParticlesMap private
Initial value:
{
      this, "InputMeasurementParticlesMap"}
Definition at line 85 of file CsvMultiTrajectoryWriter.hpp.
View newest version in sPHENIX GitHub at line 85 of file CsvMultiTrajectoryWriter.hpp
Referenced by CsvMultiTrajectoryWriter(), and writeT().
The documentation for this class was generated from the following files:
acts/blob/sPHENIX/Examples/Io/Csv/include/ActsExamples/Io/Csv/CsvMultiTrajectoryWriter.hpp
acts/blob/sPHENIX/Examples/Io/Csv/src/CsvMultiTrajectoryWriter.cpp