Analysis Software: JetDefinition Class Reference
JetDefinition Class Reference
#include <JETSCAPE/blob/main/external_packages/fjcore.hh>
Classes
class DefaultRecombiner
class Plugin
class Recombiner
Public Member Functions
JetDefinition (JetAlgorithm jet_algorithm_in, double R_in, RecombinationScheme recomb_scheme_in=E_scheme, Strategy strategy_in=Best)
JetDefinition (JetAlgorithm jet_algorithm_in, RecombinationScheme recomb_scheme_in=E_scheme, Strategy strategy_in=Best)
JetDefinition (JetAlgorithm jet_algorithm_in, double R_in, double xtra_param_in, RecombinationScheme recomb_scheme_in=E_scheme, Strategy strategy_in=Best)
JetDefinition (JetAlgorithm jet_algorithm_in, double R_in, const Recombiner *recombiner_in, Strategy strategy_in=Best)
JetDefinition (JetAlgorithm jet_algorithm_in, const Recombiner *recombiner_in, Strategy strategy_in=Best)
JetDefinition (JetAlgorithm jet_algorithm_in, double R_in, double xtra_param_in, const Recombiner *recombiner_in, Strategy strategy_in=Best)
JetDefinition ()
JetDefinition (const Plugin *plugin_in)
JetDefinition (JetAlgorithm jet_algorithm_in, double R_in, RecombinationScheme recomb_scheme_in, Strategy strategy_in, int nparameters_in)
JetDefinition (JetAlgorithm jet_algorithm_in, double R_in, Strategy strategy_in, RecombinationScheme recomb_scheme_in=E_scheme, int nparameters_in=1)
template<class L >
std::vector< PseudoJet > operator() (const std::vector< L > &particles) const
void set_recombination_scheme (RecombinationScheme)
void set_recombiner (const Recombiner *recomb)
void set_recombiner (const JetDefinition &other_jet_def)
void delete_recombiner_when_unused ()
const Plugin * plugin () const
void delete_plugin_when_unused ()
JetAlgorithm jet_algorithm () const
JetAlgorithm jet_finder () const
double R () const
double extra_param () const
Strategy strategy () const
RecombinationScheme recombination_scheme () const
void set_jet_algorithm (JetAlgorithm njf)
void set_jet_finder (JetAlgorithm njf)
void set_extra_param (double xtra_param)
const Recombiner * recombiner () const
bool has_same_recombiner (const JetDefinition &other_jd) const
bool is_spherical () const
std::string description () const
std::string description_no_recombiner () const
Static Public Member Functions
static std::string algorithm_description (const JetAlgorithm jet_alg)
static unsigned int n_parameters_for_algorithm (const JetAlgorithm jet_alg)
Static Public Attributes
static const double max_allowable_R = 1000.0
Private Attributes
JetAlgorithm _jet_algorithm
double _Rparam
double _extra_param
parameter whose meaning varies according to context
Strategy _strategy
const Plugin * _plugin
SharedPtr< const Plugin > _plugin_shared
DefaultRecombiner _default_recombiner
const Recombiner * _recombiner
SharedPtr< const Recombiner > _shared_recombiner
Detailed Description
Definition at line 1032 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 1032 of file fjcore.hh
Constructor & Destructor Documentation
JetDefinition::JetDefinition (JetAlgorithm jet_algorithm_in, double R_in, RecombinationScheme recomb_scheme_in = E_scheme, Strategy strategy_in = Best) inline
Definition at line 1036 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 1036 of file fjcore.hh
References JetDefinition().
JetDefinition::JetDefinition (JetAlgorithm jet_algorithm_in, RecombinationScheme recomb_scheme_in = E_scheme, Strategy strategy_in = Best) inline
Definition at line 1042 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 1042 of file fjcore.hh
References JetDefinition().
JetDefinition::JetDefinition (JetAlgorithm jet_algorithm_in, double R_in, double xtra_param_in, RecombinationScheme recomb_scheme_in = E_scheme, Strategy strategy_in = Best) inline
Definition at line 1048 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 1048 of file fjcore.hh
References JetDefinition(), and set_extra_param().
JetDefinition::JetDefinition (JetAlgorithm jet_algorithm_in, double R_in, const Recombiner * recombiner_in, Strategy strategy_in = Best) inline
Definition at line 1056 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 1056 of file fjcore.hh
References _recombiner, external_scheme, and JetDefinition().
JetDefinition::JetDefinition (JetAlgorithm jet_algorithm_in, const Recombiner * recombiner_in, Strategy strategy_in = Best) inline
Definition at line 1063 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 1063 of file fjcore.hh
References _recombiner, external_scheme, and JetDefinition().
JetDefinition::JetDefinition (JetAlgorithm jet_algorithm_in, double R_in, double xtra_param_in, const Recombiner * recombiner_in, Strategy strategy_in = Best) inline
Definition at line 1069 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 1069 of file fjcore.hh
References _recombiner, external_scheme, and JetDefinition().
JetDefinition::JetDefinition () inline
Definition at line 1077 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 1077 of file fjcore.hh
References undefined_jet_algorithm.
Referenced by JetDefinition().
JetDefinition::JetDefinition (const Plugin * plugin_in) inline
Definition at line 1080 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 1080 of file fjcore.hh
References _extra_param, _jet_algorithm, _plugin, _Rparam, _strategy, E_scheme, plugin_algorithm, plugin_strategy, JetDefinition::Plugin::R(), and set_recombination_scheme().
JetDefinition::JetDefinition (JetAlgorithm jet_algorithm_in, double R_in, RecombinationScheme recomb_scheme_in, Strategy strategy_in, int nparameters_in)
JetDefinition::JetDefinition (JetAlgorithm jet_algorithm_in, double R_in, Strategy strategy_in, RecombinationScheme recomb_scheme_in = E_scheme, int nparameters_in = 1) inline
Definition at line 1094 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 1094 of file fjcore.hh
References JetDefinition().
Member Function Documentation
string JetDefinition::algorithm_description (const JetAlgorithm jet_alg) static
Definition at line 3424 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 3424 of file fjcore.cc
References antikt_algorithm, cambridge_algorithm, cambridge_for_passive_algorithm, ee_genkt_algorithm, ee_kt_algorithm, genkt_algorithm, kt_algorithm, perf_headwind::name, plugin_algorithm, and undefined_jet_algorithm.
void JetDefinition::delete_plugin_when_unused ()
Definition at line 3479 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 3479 of file fjcore.cc
void JetDefinition::delete_recombiner_when_unused ()
Definition at line 3471 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 3471 of file fjcore.cc
string JetDefinition::description () const
Definition at line 3389 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 3389 of file fjcore.cc
References perf_headwind::name, plugin_algorithm, and undefined_jet_algorithm.
string JetDefinition::description_no_recombiner () const
Definition at line 3402 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 3402 of file fjcore.cc
References cambridge_for_passive_algorithm, perf_headwind::name, plugin_algorithm, Acts::IntegrationTest::R, and undefined_jet_algorithm.
double JetDefinition::extra_param () const inline
Definition at line 1117 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 1117 of file fjcore.hh
References _extra_param.
bool JetDefinition::has_same_recombiner (const JetDefinition & other_jd) const
Definition at line 3465 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 3465 of file fjcore.cc
References external_scheme.
bool JetDefinition::is_spherical () const
Definition at line 3380 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 3380 of file fjcore.cc
References ee_genkt_algorithm, ee_kt_algorithm, and plugin_algorithm.
Referenced by operator()().
JetAlgorithm JetDefinition::jet_algorithm () const inline
Definition at line 1114 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 1114 of file fjcore.hh
References _jet_algorithm.
JetAlgorithm JetDefinition::jet_finder () const inline
Definition at line 1115 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 1115 of file fjcore.hh
References _jet_algorithm.
unsigned int JetDefinition::n_parameters_for_algorithm (const JetAlgorithm jet_alg) static
Definition at line 3440 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 3440 of file fjcore.cc
References ee_genkt_algorithm, ee_kt_algorithm, and genkt_algorithm.
template<class L > std::vector< PseudoJet > JetDefinition::operator() (const std::vector< L > & particles) const
Definition at line 1647 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 1647 of file fjcore.hh
References ClusterSequence::delete_self_when_unused(), ClusterSequence::inclusive_jets(), is_spherical(), sorted_by_E(), and sorted_by_pt().
const Plugin* JetDefinition::plugin () const inline
Definition at line 1112 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 1112 of file fjcore.hh
References _plugin.
double JetDefinition::R () const inline
Definition at line 1116 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 1116 of file fjcore.hh
References _Rparam.
RecombinationScheme JetDefinition::recombination_scheme () const inline
Definition at line 1119 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 1119 of file fjcore.hh
References _default_recombiner, and JetDefinition::DefaultRecombiner::scheme().
const Recombiner* JetDefinition::recombiner () const inline
Definition at line 1124 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 1124 of file fjcore.hh
References _default_recombiner, and _recombiner.
void JetDefinition::set_extra_param (double xtra_param) inline
Definition at line 1123 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 1123 of file fjcore.hh
References _extra_param.
Referenced by JetDefinition().
void JetDefinition::set_jet_algorithm (JetAlgorithm njf) inline
Definition at line 1121 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 1121 of file fjcore.hh
References _jet_algorithm.
void JetDefinition::set_jet_finder (JetAlgorithm njf) inline
Definition at line 1122 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 1122 of file fjcore.hh
References _jet_algorithm.
void JetDefinition::set_recombination_scheme (RecombinationScheme recomb_scheme)
Definition at line 3448 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 3448 of file fjcore.cc
Referenced by JetDefinition().
void JetDefinition::set_recombiner (const Recombiner * recomb) inline
Definition at line 1105 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 1105 of file fjcore.hh
References _default_recombiner, _recombiner, _shared_recombiner, external_scheme, and SharedPtr< T >::reset().
void JetDefinition::set_recombiner (const JetDefinition & other_jet_def)
Definition at line 3454 of file fjcore.cc.
View newest version in sPHENIX GitHub at line 3454 of file fjcore.cc
References assert, and external_scheme.
Strategy JetDefinition::strategy () const inline
Definition at line 1118 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 1118 of file fjcore.hh
References _strategy.
Member Data Documentation
DefaultRecombiner JetDefinition::_default_recombiner private
Definition at line 1177 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 1177 of file fjcore.hh
Referenced by recombination_scheme(), recombiner(), and set_recombiner().
double JetDefinition::_extra_param private
parameter whose meaning varies according to context
Definition at line 1173 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 1173 of file fjcore.hh
Referenced by extra_param(), JetDefinition(), and set_extra_param().
JetAlgorithm JetDefinition::_jet_algorithm private
Definition at line 1171 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 1171 of file fjcore.hh
Referenced by jet_algorithm(), jet_finder(), JetDefinition(), set_jet_algorithm(), and set_jet_finder().
const Plugin* JetDefinition::_plugin private
Definition at line 1175 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 1175 of file fjcore.hh
Referenced by JetDefinition(), and plugin().
SharedPtr<const Plugin> JetDefinition::_plugin_shared private
Definition at line 1176 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 1176 of file fjcore.hh
const Recombiner* JetDefinition::_recombiner private
Definition at line 1178 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 1178 of file fjcore.hh
Referenced by JetDefinition(), recombiner(), and set_recombiner().
double JetDefinition::_Rparam private
Definition at line 1172 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 1172 of file fjcore.hh
Referenced by JetDefinition(), and R().
SharedPtr<const Recombiner> JetDefinition::_shared_recombiner private
Definition at line 1179 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 1179 of file fjcore.hh
Referenced by set_recombiner().
Strategy JetDefinition::_strategy private
Definition at line 1174 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 1174 of file fjcore.hh
Referenced by JetDefinition(), and strategy().
const double JetDefinition::max_allowable_R = 1000.0 static
Definition at line 1103 of file fjcore.hh.
View newest version in sPHENIX GitHub at line 1103 of file fjcore.hh
The documentation for this class was generated from the following files:
JETSCAPE/blob/main/external_packages/fjcore.hh
JETSCAPE/blob/main/external_packages/fjcore.cc