Analysis Software: Acts::GeometryView3D Struct Reference
Acts::GeometryView3D Struct Reference
#include <acts/blob/sPHENIX/Core/include/Acts/Visualization/GeometryView3D.hpp>
Static Public Member Functions
static void drawPolyhedron (IVisualization3D &helper, const Polyhedron &polyhedron, const ViewConfig &viewConfig=s_viewVolume)
static void drawSurface (IVisualization3D &helper, const Surface &surface, const GeometryContext &gctx, const Transform3 &transform=Transform3::Identity(), const ViewConfig &viewConfig=s_viewSensitive)
static void drawSurfaceArray (IVisualization3D &helper, const SurfaceArray &surfaceArray, const GeometryContext &gctx, const Transform3 &transform=Transform3::Identity(), const ViewConfig &sensitiveConfig=s_viewSensitive, const ViewConfig &passiveConfig=s_viewPassive, const ViewConfig &gridConfig=s_viewGrid, const std::string &outputDir=".")
static void drawVolume (IVisualization3D &helper, const AbstractVolume &volume, const GeometryContext &gctx, const Transform3 &transform=Transform3::Identity(), const ViewConfig &viewConfig=s_viewVolume)
static void drawPortal (IVisualization3D &helper, const Experimental::Portal &portal, const GeometryContext &gctx, const Transform3 &transform=Transform3::Identity(), const ViewConfig &connected=ViewConfig({0, 255, 0}), const ViewConfig &disconnected=ViewConfig({255, 0, 0}))
static void drawDetectorVolume (IVisualization3D &helper, const Acts::Experimental::DetectorVolume &volume, const GeometryContext &gctx, const Transform3 &transform=Transform3::Identity(), const ViewConfig &connected=ViewConfig({0, 255, 0}), const ViewConfig &unconnected=ViewConfig({255, 0, 0}), const ViewConfig &viewConfig=s_viewSensitive)
static void drawLayer (IVisualization3D &helper, const Layer &layer, const GeometryContext &gctx, const ViewConfig &layerConfig=s_viewPassive, const ViewConfig &sensitiveConfig=s_viewSensitive, const ViewConfig &gridConfig=s_viewGrid, const std::string &outputDir=".")
static void drawTrackingVolume (IVisualization3D &helper, const TrackingVolume &tVolume, const GeometryContext &gctx, const ViewConfig &containerView=s_viewVolume, const ViewConfig &volumeView=s_viewVolume, const ViewConfig &layerView=s_viewPassive, const ViewConfig &sensitiveView=s_viewSensitive, const ViewConfig &gridView=s_viewGrid, bool writeIt=true, const std::string &tag="", const std::string &outputDir=".")
static void drawSegmentBase (IVisualization3D &helper, const Vector3 &start, const Vector3 &end, int arrows=0, double arrowLength=0., double arrowWidth=0., const ViewConfig &viewConfig=s_viewLine)
static void drawSegment (IVisualization3D &helper, const Vector3 &start, const Vector3 &end, const ViewConfig &viewConfig=s_viewLine)
static void drawArrowBackward (IVisualization3D &helper, const Vector3 &start, const Vector3 &end, double arrowLength, double arrowWidth, const ViewConfig &viewConfig=s_viewLine)
static void drawArrowForward (IVisualization3D &helper, const Vector3 &start, const Vector3 &end, double arrowLength, double arrowWidth, const ViewConfig &viewConfig=s_viewLine)
static void drawArrowsBoth (IVisualization3D &helper, const Vector3 &start, const Vector3 &end, double arrowLength, double arrowWidth, const ViewConfig &viewConfig=s_viewLine)
Detailed Description
Definition at line 40 of file GeometryView3D.hpp.
View newest version in sPHENIX GitHub at line 40 of file GeometryView3D.hpp
Member Function Documentation
void Acts::GeometryView3D::drawArrowBackward (IVisualization3D & helper, const Vector3 & start, const Vector3 & end, double arrowLength, double arrowWidth, const ViewConfig & viewConfig = s_viewLine) static
Convenience function : arrow pointing back
Parameters
[in,out] helper The visualization helper
start The start point
end The end point
arrowLength wrt thickness
arrowWidth wrt thickness
viewConfig The drawing configuration for this segment
Definition at line 444 of file GeometryView3D.cpp.
View newest version in sPHENIX GitHub at line 444 of file GeometryView3D.cpp
Referenced by Acts::EventDataView3D::drawBoundTrackParameters(), and Acts::PrimitivesView3DTest::run().
void Acts::GeometryView3D::drawArrowForward (IVisualization3D & helper, const Vector3 & start, const Vector3 & end, double arrowLength, double arrowWidth, const ViewConfig & viewConfig = s_viewLine) static
Convenience function : arrow pointing forward
Parameters
[in,out] helper The visualization helper
start The start point
end The end point
arrowLength wrt thickness
arrowWidth wrt thickness
viewConfig The drawing configuration for this segment
Definition at line 450 of file GeometryView3D.cpp.
View newest version in sPHENIX GitHub at line 450 of file GeometryView3D.cpp
Referenced by Acts::Test::BOOST_AUTO_TEST_CASE(), Acts::EventDataView3D::drawBoundTrackParameters(), and Acts::PrimitivesView3DTest::run().
void Acts::GeometryView3D::drawArrowsBoth (IVisualization3D & helper, const Vector3 & start, const Vector3 & end, double arrowLength, double arrowWidth, const ViewConfig & viewConfig = s_viewLine) static
Convenience function : arrow pointing both directions
Parameters
[in,out] helper The visualization helper
start The start point
end The end point
arrowLength wrt thickness
arrowWidth wrt thickness
viewConfig The drawing configuration for this segment
Definition at line 456 of file GeometryView3D.cpp.
View newest version in sPHENIX GitHub at line 456 of file GeometryView3D.cpp
Referenced by Acts::PrimitivesView3DTest::run().
void Acts::GeometryView3D::drawDetectorVolume (IVisualization3D & helper, const Acts::Experimental::DetectorVolume & volume, const GeometryContext & gctx, const Transform3 & transform = Transform3::Identity(), const ViewConfig & connected = ViewConfig({0, 255, 0}), const ViewConfig & unconnected = ViewConfig({255, 0, 0}), const ViewConfig & viewConfig = s_viewSensitive) static
Helper method to draw DetectorVolume objects
Parameters
[in,out] helper The visualization helper
volume The DetectorVolume to be drawn
gctx The geometry context for which it is drawn
transform An option additional transform
connected The config for connected portals
unconnected The config for unconnected portals
viewConfig The drawing configuration
Definition at line 208 of file GeometryView3D.cpp.
View newest version in sPHENIX GitHub at line 208 of file GeometryView3D.cpp
References Acts::Experimental::DetectorVolume::portals(), writeMapConfig::surface, Acts::Experimental::DetectorVolume::surfaces(), and Acts::Experimental::DetectorVolume::volumes().
Referenced by ActsExamples::MockupSectorBuilder::drawSector().
void Acts::GeometryView3D::drawLayer (IVisualization3D & helper, const Layer & layer, const GeometryContext & gctx, const ViewConfig & layerConfig = s_viewPassive, const ViewConfig & sensitiveConfig = s_viewSensitive, const ViewConfig & gridConfig = s_viewGrid, const std::string & outputDir = ".") static
Helper method to draw AbstractVolume objects
Parameters
[in,out] helper The visualization helper
layer The tracking layer to be drawn
gctx The geometry context for which it is drawn
layerConfig The drawing configuration for passive surfaces
sensitiveConfig The drawing configuration for sensitive surfaces
gridConfig The drawing configuration for grid display
outputDir Directory to write to
Definition at line 230 of file GeometryView3D.cpp.
View newest version in sPHENIX GitHub at line 230 of file GeometryView3D.cpp
References ActsExamples::joinPaths(), outputDir, Acts::ViewConfig::outputName, Acts::Layer::representingVolume(), Acts::Layer::surfaceArray(), Acts::Layer::surfaceRepresentation(), and Acts::ViewConfig::visible.
void Acts::GeometryView3D::drawPolyhedron (IVisualization3D & helper, const Polyhedron & polyhedron, const ViewConfig & viewConfig = s_viewVolume) static
Helper method to draw Polyhedron objects
Parameters
[in,out] helper The visualization helper
polyhedron The surface to be drawn
viewConfig The drawing configuration
Definition at line 67 of file GeometryView3D.cpp.
View newest version in sPHENIX GitHub at line 67 of file GeometryView3D.cpp
References Acts::ViewConfig::color, Acts::Polyhedron::faces, Acts::Polyhedron::triangularMesh, Acts::ViewConfig::triangulate, Acts::Polyhedron::vertices, and Acts::ViewConfig::visible.
Referenced by Acts::Test::BOOST_AUTO_TEST_CASE(), and Acts::EventDataView3D::drawCovarianceCartesian().
void Acts::GeometryView3D::drawPortal (IVisualization3D & helper, const Experimental::Portal & portal, const GeometryContext & gctx, const Transform3 & transform = Transform3::Identity(), const ViewConfig & connected = ViewConfig({0, 255, 0}), const ViewConfig & disconnected = ViewConfig({255, 0, 0})) static
Helper method to draw portals objects
Parameters
[in,out] helper The visualization helper
portal The portal to be drawn
gctx The geometry context for which it is drawn
transform An option additional transform
connected The config for connected portals
disconnected The config for disconnected portals
Definition at line 191 of file GeometryView3D.cpp.
View newest version in sPHENIX GitHub at line 191 of file GeometryView3D.cpp
References Acts::Experimental::Portal::detectorVolumeUpdators(), writeMapConfig::surface, and Acts::Experimental::Portal::surface().
void Acts::GeometryView3D::drawSegment (IVisualization3D & helper, const Vector3 & start, const Vector3 & end, const ViewConfig & viewConfig = s_viewLine) static
Convenience function : line
Parameters
[in,out] helper The visualization helper
start The start point
end The end point
viewConfig The drawing configuration for this segment
Definition at line 438 of file GeometryView3D.cpp.
View newest version in sPHENIX GitHub at line 438 of file GeometryView3D.cpp
Referenced by Acts::PrimitivesView3DTest::run().
void Acts::GeometryView3D::drawSegmentBase (IVisualization3D & helper, const Vector3 & start, const Vector3 & end, int arrows = 0, double arrowLength = 0., double arrowWidth = 0., const ViewConfig & viewConfig = s_viewLine) static
Helper method to draw lines - base for all lines
Parameters
[in,out] helper The visualization helper
start The start point
end The end point
arrows [ -1 | 0 | 1 | 2 ] = [ start | none | end | both ]
arrowLength wrt halflength
arrowWidth wrt thickness
viewConfig The drawing configuration for this segment
Definition at line 346 of file GeometryView3D.cpp.
View newest version in sPHENIX GitHub at line 346 of file GeometryView3D.cpp
References alpha, Acts::ViewConfig::color, end, line, Acts::ViewConfig::lineThickness, Acts::makeCurvilinearUnitVectors(), and thickness.
void Acts::GeometryView3D::drawSurface (IVisualization3D & helper, const Surface & surface, const GeometryContext & gctx, const Transform3 & transform = Transform3::Identity(), const ViewConfig & viewConfig = s_viewSensitive) static
Helper method to draw Surface objects
Parameters
[in,out] helper The visualization helper
surface The surface to be drawn
gctx The geometry context for which it is drawn
transform An option additional transform
viewConfig The drawing configuration
Definition at line 80 of file GeometryView3D.cpp.
View newest version in sPHENIX GitHub at line 80 of file GeometryView3D.cpp
References Acts::Polyhedron::move(), Acts::ViewConfig::nSegments, and Acts::Surface::polyhedronRepresentation().
Referenced by Acts::Python::addObj(), Acts::Test::Layers::BOOST_AUTO_TEST_CASE(), Acts::Test::BOOST_AUTO_TEST_CASE(), Acts::EventDataView3D::drawBoundTrackParameters(), Acts::EventDataView3D::drawMultiTrajectory(), Acts::PrimitivesView3DTest::run(), and Acts::SurfaceView3DTest::run().
void Acts::GeometryView3D::drawSurfaceArray (IVisualization3D & helper, const SurfaceArray & surfaceArray, const GeometryContext & gctx, const Transform3 & transform = Transform3::Identity(), const ViewConfig & sensitiveConfig = s_viewSensitive, const ViewConfig & passiveConfig = s_viewPassive, const ViewConfig & gridConfig = s_viewGrid, const std::string & outputDir = ".") static
Helper method to draw SurfaceArray objects
Parameters
[in,out] helper The visualization helper
surfaceArray The surface to be drawn
gctx The geometry context for which it is drawn
transform An option additional transform
sensitiveConfig The drawing configuration for sensitive surfaces
passiveConfig The drawing configuration for passive surfaces
gridConfig The drawing configuration for grid
outputDir Directory to write to
Definition at line 93 of file GeometryView3D.cpp.
View newest version in sPHENIX GitHub at line 93 of file GeometryView3D.cpp
References Acts::SurfaceArray::binningValues(), Acts::binPhi, Acts::binR, Acts::binZ, Acts::Extent::extend(), Acts::SurfaceArray::getAxes(), ActsExamples::joinPaths(), Acts::ViewConfig::lineThickness, Acts::Extent::medium(), Acts::ViewConfig::nSegments, Acts::ViewConfig::offset, Acts::CylinderVolumeBounds::orientedSurfaces(), outputDir, Acts::ViewConfig::outputName, ActsTests::PropagationDatasets::phi, Acts::Test::phiValues, Acts::IntegrationTest::R, physmon_track_finding_ttbar::r, Acts::SurfaceArray::surfaces(), thickness, and physmon_track_finding_ttbar::z.
Referenced by Acts::Test::BOOST_FIXTURE_TEST_CASE().
void Acts::GeometryView3D::drawTrackingVolume (IVisualization3D & helper, const TrackingVolume & tVolume, const GeometryContext & gctx, const ViewConfig & containerView = s_viewVolume, const ViewConfig & volumeView = s_viewVolume, const ViewConfig & layerView = s_viewPassive, const ViewConfig & sensitiveView = s_viewSensitive, const ViewConfig & gridView = s_viewGrid, bool writeIt = true, const std::string & tag = "", const std::string & outputDir = ".") static
Helper method to draw AbstractVolume objects
Parameters
[in,out] helper The visualization helper
tVolume The tracking volume to be drawn
gctx The geometry context for which it is drawn
containerView The drawing configuration for a container volume
volumeView The drawing configuration for the navigation level volume
layerView The drawing configuration for passive surfaces
sensitiveView The drawing configuration for sensitive surfaces
gridView The drawing configuration for grid display
writeIt The prescription to write it or not
tag The (optional) additional output tag
outputDir Directory to write to
Definition at line 262 of file GeometryView3D.cpp.
View newest version in sPHENIX GitHub at line 262 of file GeometryView3D.cpp
References Acts::BinnedArray< T >::arrayObjects(), Acts::TrackingVolume::boundarySurfaces(), Acts::TrackingVolume::confinedLayers(), Acts::TrackingVolume::confinedVolumes(), gctx, Acts::GeometryObject::geometryId(), i, test_examples::ids, ActsExamples::joinPaths(), Acts::TrackingVolume::motherVolume(), Acts::ViewConfig::nSegments, outputDir, add_histos::outputName, Acts::ViewConfig::outputName, AlignmentDefs::tl, to_string(), Acts::GeometryIdentifier::volume(), and Acts::TrackingVolume::volumeName().
Referenced by Acts::TrackingGeometryView3DTest::run(), and ActsExamples::ObjTrackingGeometryWriter::write().
void Acts::GeometryView3D::drawVolume (IVisualization3D & helper, const AbstractVolume & volume, const GeometryContext & gctx, const Transform3 & transform = Transform3::Identity(), const ViewConfig & viewConfig = s_viewVolume) static
Helper method to draw AbstractVolume objects
Parameters
[in,out] helper The visualization helper
volume The volume to be drawn
gctx The geometry context for which it is drawn
transform An option additional transform
viewConfig The drawing configuration for boundary surfaces
Definition at line 179 of file GeometryView3D.cpp.
View newest version in sPHENIX GitHub at line 179 of file GeometryView3D.cpp
References Acts::AbstractVolume::boundarySurfaces(), gctx, and Acts::Test::transform.
Referenced by Acts::VolumeView3DTest::run().
The documentation for this struct was generated from the following files:
acts/blob/sPHENIX/Core/include/Acts/Visualization/GeometryView3D.hpp
acts/blob/sPHENIX/Core/src/Visualization/GeometryView3D.cpp