Analysis Software: PHG4EICMvtxDetector Class Reference
PHG4EICMvtxDetector Class Reference
#include <coresoftware/blob/master/simulation/g4simulation/g4mvtx/PHG4EICMvtxDetector.h>
Public Member Functions
PHG4EICMvtxDetector (PHG4Subsystem *subsys, PHCompositeNode *Node, const PHParametersContainer *_paramsContainer, const std::string &dnam)
constructor
~PHG4EICMvtxDetector () override
destructor
void ConstructMe (G4LogicalVolume *world) override
construct
int IsActive (int lyr) const
int IsAbsorberActive (int lyr) const
int IsBlackHole (int lyr) const
void SuperDetector (const std::string &name)
const std::string SuperDetector () const
void Detector (const std::string &name)
const std::string Detector () const
int get_layer (int stv_index) const
int get_stave (int stv_index) const
volume accessors
int IsInMvtx (G4VPhysicalVolume *, int &layer, int &stave) const
int IsSensor (G4VPhysicalVolume *) const
Public Member Functions inherited from PHG4Detector
PHG4Detector ()=delete
constructor
PHG4Detector (PHG4Subsystem *subsys, PHCompositeNode *Node, const std::string &nam)
virtual ~PHG4Detector (void)
destructor
virtual void Construct (G4LogicalVolume *world) final
construct method
virtual void PostConstruction ()
Optional PostConstruction call after all geometry is constructed.
virtual void Verbosity (const int v)
virtual int Verbosity () const
virtual G4UserSteppingAction * GetSteppingAction ()
virtual std::string GetName () const
virtual void OverlapCheck (const bool chk)
virtual bool OverlapCheck () const
virtual void Print (const std::string &="ALL") const
virtual int DisplayVolume (G4VSolid *volume, G4LogicalVolume *logvol, G4RotationMatrix *rotm=nullptr)
virtual int DisplayVolume (G4LogicalVolume *checksolid, G4LogicalVolume *logvol, G4RotationMatrix *rotm=nullptr)
virtual PHCompositeNode * topNode ()
virtual PHG4Subsystem * GetMySubsystem ()
Private Member Functions
void AddGeometryNode ()
int ConstructMvtx (G4LogicalVolume *sandwich)
int ConstructMvtx_Layer (int layer, G4AssemblyVolume *stave, G4LogicalVolume *&trackerenvelope)
void SetDisplayProperty (G4AssemblyVolume *av)
void SetDisplayProperty (G4LogicalVolume *lv)
void FillPVArray (G4AssemblyVolume *av)
void FindSensor (G4LogicalVolume *lv)
double get_phistep (int lay) const
Private Attributes
PHG4MvtxDisplayAction * m_DisplayAction
const PHParametersContainer * m_ParamsContainer
std::set< G4VPhysicalVolume * > m_SensorPV
std::map< G4VPhysicalVolume
*, std::tuple< int, int > > m_StavePV
std::array< int, n_Layers > m_IsLayerActive {}
std::array< int, n_Layers > m_IsLayerAbsorberActive {}
std::array< int, n_Layers > m_IsBlackHole {}
std::array< int, n_Layers > m_N_staves {}
std::array< double, n_Layers > m_nominal_radius {}
std::array< double, n_Layers > m_nominal_phitilt {}
std::array< double, n_Layers > m_nominal_phi0 {}
std::string m_Detector
std::string m_SuperDetector
std::string m_StaveGeometryFile
Static Private Attributes
static constexpr int n_Layers = 3
Additional Inherited Members
Static Public Member Functions inherited from PHG4Detector
static G4Material * GetDetectorMaterial (const std::string &name, const bool quit=true)
static G4Element * GetDetectorElement (const std::string &name, const bool quit=true)
Detailed Description
Definition at line 23 of file PHG4EICMvtxDetector.h.
View newest version in sPHENIX GitHub at line 23 of file PHG4EICMvtxDetector.h
Constructor & Destructor Documentation
PHG4EICMvtxDetector::PHG4EICMvtxDetector (PHG4Subsystem * subsys, PHCompositeNode * Node, const PHParametersContainer * _paramsContainer, const std::string & dnam)
constructor
Definition at line 52 of file PHG4EICMvtxDetector.cc.
View newest version in sPHENIX GitHub at line 52 of file PHG4EICMvtxDetector.cc
References Acts::UnitConstants::cm, PHParameters::get_double_param(), PHParameters::get_int_param(), PHParametersContainer::GetParameters(), m_IsBlackHole, m_IsLayerAbsorberActive, m_IsLayerActive, m_N_staves, m_nominal_phi0, m_nominal_phitilt, m_nominal_radius, m_ParamsContainer, Acts::UnitConstants::mm, n_Layers, and PHG4Detector::Verbosity().
PHG4EICMvtxDetector::~PHG4EICMvtxDetector () inline override
destructor
Definition at line 30 of file PHG4EICMvtxDetector.h.
View newest version in sPHENIX GitHub at line 30 of file PHG4EICMvtxDetector.h
Member Function Documentation
void PHG4EICMvtxDetector::AddGeometryNode () private
Definition at line 378 of file PHG4EICMvtxDetector.cc.
View newest version in sPHENIX GitHub at line 378 of file PHG4EICMvtxDetector.cc
References Acts::active, PHG4CylinderGeomContainer::AddLayerGeom(), PHCompositeNode::addNode(), Acts::UnitConstants::cm, PHNodeIterator::findFirst(), get_phistep(), PHG4CylinderGeomContainer::identify(), m_Detector, m_IsLayerActive, m_N_staves, m_nominal_phi0, m_nominal_phitilt, m_nominal_radius, m_SuperDetector, n_Layers, Acts::UnitConstants::rad, PHG4Detector::topNode(), and PHG4Detector::Verbosity().
Referenced by ConstructMe().
void PHG4EICMvtxDetector::ConstructMe (G4LogicalVolume * world) override virtual
construct
Implements PHG4Detector.
Definition at line 161 of file PHG4EICMvtxDetector.cc.
View newest version in sPHENIX GitHub at line 161 of file PHG4EICMvtxDetector.cc
References AddGeometryNode(), ConstructMvtx(), and PHG4Detector::Verbosity().
int PHG4EICMvtxDetector::ConstructMvtx (G4LogicalVolume * sandwich) private
Definition at line 179 of file PHG4EICMvtxDetector.cc.
View newest version in sPHENIX GitHub at line 179 of file PHG4EICMvtxDetector.cc
References ConstructMvtx_Layer(), FillPVArray(), m_IsLayerActive, m_StaveGeometryFile, n_Layers, summary::reader, SetDisplayProperty(), and PHG4Detector::Verbosity().
Referenced by ConstructMe().
int PHG4EICMvtxDetector::ConstructMvtx_Layer (int layer, G4AssemblyVolume * stave, G4LogicalVolume *& trackerenvelope) private
Definition at line 223 of file PHG4EICMvtxDetector.cc.
View newest version in sPHENIX GitHub at line 223 of file PHG4EICMvtxDetector.cc
References double(), get_phistep(), layer, m_N_staves, m_nominal_phi0, m_nominal_phitilt, m_nominal_radius, PHG4Detector::OverlapCheck(), Ra, and PHG4Detector::Verbosity().
Referenced by ConstructMvtx().
void PHG4EICMvtxDetector::Detector (const std::string & name) inline
Definition at line 46 of file PHG4EICMvtxDetector.h.
View newest version in sPHENIX GitHub at line 46 of file PHG4EICMvtxDetector.h
References m_Detector, and perf_headwind::name.
Referenced by PHG4EICMvtxSubsystem::InitRunSubsystem().
const std::string PHG4EICMvtxDetector::Detector () const inline
Definition at line 47 of file PHG4EICMvtxDetector.h.
View newest version in sPHENIX GitHub at line 47 of file PHG4EICMvtxDetector.h
References m_Detector.
void PHG4EICMvtxDetector::FillPVArray (G4AssemblyVolume * av) private
Definition at line 417 of file PHG4EICMvtxDetector.cc.
View newest version in sPHENIX GitHub at line 417 of file PHG4EICMvtxDetector.cc
References FindSensor(), get_layer(), get_stave(), i, it, layer, m_StavePV, std::tr1::make_tuple(), and PHG4Detector::Verbosity().
Referenced by ConstructMvtx().
void PHG4EICMvtxDetector::FindSensor (G4LogicalVolume * lv) private
Definition at line 461 of file PHG4EICMvtxDetector.cc.
View newest version in sPHENIX GitHub at line 461 of file PHG4EICMvtxDetector.cc
References i, m_SensorPV, and PHG4Detector::Verbosity().
Referenced by FillPVArray().
int PHG4EICMvtxDetector::get_layer (int stv_index) const
Definition at line 136 of file PHG4EICMvtxDetector.cc.
View newest version in sPHENIX GitHub at line 136 of file PHG4EICMvtxDetector.cc
References m_N_staves.
Referenced by FillPVArray().
double PHG4EICMvtxDetector::get_phistep (int lay) const inline private
Definition at line 61 of file PHG4EICMvtxDetector.h.
View newest version in sPHENIX GitHub at line 61 of file PHG4EICMvtxDetector.h
References m_N_staves.
Referenced by AddGeometryNode(), and ConstructMvtx_Layer().
int PHG4EICMvtxDetector::get_stave (int stv_index) const
Definition at line 149 of file PHG4EICMvtxDetector.cc.
View newest version in sPHENIX GitHub at line 149 of file PHG4EICMvtxDetector.cc
References index, and m_N_staves.
Referenced by FillPVArray().
int PHG4EICMvtxDetector::IsAbsorberActive (int lyr) const inline
Definition at line 42 of file PHG4EICMvtxDetector.h.
View newest version in sPHENIX GitHub at line 42 of file PHG4EICMvtxDetector.h
References m_IsLayerAbsorberActive.
int PHG4EICMvtxDetector::IsActive (int lyr) const inline
Definition at line 41 of file PHG4EICMvtxDetector.h.
View newest version in sPHENIX GitHub at line 41 of file PHG4EICMvtxDetector.h
References m_IsLayerActive.
Referenced by PHG4EICMvtxSteppingAction::UserSteppingAction().
int PHG4EICMvtxDetector::IsBlackHole (int lyr) const inline
Definition at line 43 of file PHG4EICMvtxDetector.h.
View newest version in sPHENIX GitHub at line 43 of file PHG4EICMvtxDetector.h
References m_IsBlackHole.
Referenced by PHG4EICMvtxSteppingAction::UserSteppingAction().
int PHG4EICMvtxDetector::IsInMvtx (G4VPhysicalVolume * volume, int & layer, int & stave) const
Definition at line 112 of file PHG4EICMvtxDetector.cc.
View newest version in sPHENIX GitHub at line 112 of file PHG4EICMvtxDetector.cc
References m_StavePV, and PHG4Detector::Verbosity().
Referenced by PHG4EICMvtxSteppingAction::UserSteppingAction().
int PHG4EICMvtxDetector::IsSensor (G4VPhysicalVolume * volume) const
Definition at line 94 of file PHG4EICMvtxDetector.cc.
View newest version in sPHENIX GitHub at line 94 of file PHG4EICMvtxDetector.cc
References m_SensorPV, and PHG4Detector::Verbosity().
Referenced by PHG4EICMvtxSteppingAction::UserSteppingAction().
void PHG4EICMvtxDetector::SetDisplayProperty (G4AssemblyVolume * av) private
Definition at line 320 of file PHG4EICMvtxDetector.cc.
View newest version in sPHENIX GitHub at line 320 of file PHG4EICMvtxDetector.cc
References i, and it.
Referenced by ConstructMvtx(), and SetDisplayProperty().
void PHG4EICMvtxDetector::SetDisplayProperty (G4LogicalVolume * lv) private
Definition at line 338 of file PHG4EICMvtxDetector.cc.
View newest version in sPHENIX GitHub at line 338 of file PHG4EICMvtxDetector.cc
References PHG4MvtxDisplayAction::AddVolume(), i, m_DisplayAction, SetDisplayProperty(), and PHG4Detector::Verbosity().
void PHG4EICMvtxDetector::SuperDetector (const std::string & name) inline
Definition at line 44 of file PHG4EICMvtxDetector.h.
View newest version in sPHENIX GitHub at line 44 of file PHG4EICMvtxDetector.h
References m_SuperDetector, and perf_headwind::name.
Referenced by PHG4EICMvtxSubsystem::InitRunSubsystem(), and PHG4EICMvtxSteppingAction::SetInterfacePointers().
const std::string PHG4EICMvtxDetector::SuperDetector () const inline
Definition at line 45 of file PHG4EICMvtxDetector.h.
View newest version in sPHENIX GitHub at line 45 of file PHG4EICMvtxDetector.h
References m_SuperDetector.
Member Data Documentation
std::string PHG4EICMvtxDetector::m_Detector private
Definition at line 80 of file PHG4EICMvtxDetector.h.
View newest version in sPHENIX GitHub at line 80 of file PHG4EICMvtxDetector.h
Referenced by AddGeometryNode(), and Detector().
PHG4MvtxDisplayAction* PHG4EICMvtxDetector::m_DisplayAction private
Definition at line 64 of file PHG4EICMvtxDetector.h.
View newest version in sPHENIX GitHub at line 64 of file PHG4EICMvtxDetector.h
Referenced by SetDisplayProperty().
std::array<int, n_Layers> PHG4EICMvtxDetector::m_IsBlackHole {} private
Definition at line 74 of file PHG4EICMvtxDetector.h.
View newest version in sPHENIX GitHub at line 74 of file PHG4EICMvtxDetector.h
Referenced by IsBlackHole(), and PHG4EICMvtxDetector().
std::array<int, n_Layers> PHG4EICMvtxDetector::m_IsLayerAbsorberActive {} private
Definition at line 73 of file PHG4EICMvtxDetector.h.
View newest version in sPHENIX GitHub at line 73 of file PHG4EICMvtxDetector.h
Referenced by IsAbsorberActive(), and PHG4EICMvtxDetector().
std::array<int, n_Layers> PHG4EICMvtxDetector::m_IsLayerActive {} private
Definition at line 72 of file PHG4EICMvtxDetector.h.
View newest version in sPHENIX GitHub at line 72 of file PHG4EICMvtxDetector.h
Referenced by AddGeometryNode(), ConstructMvtx(), IsActive(), and PHG4EICMvtxDetector().
std::array<int, n_Layers> PHG4EICMvtxDetector::m_N_staves {} private
Definition at line 75 of file PHG4EICMvtxDetector.h.
View newest version in sPHENIX GitHub at line 75 of file PHG4EICMvtxDetector.h
Referenced by AddGeometryNode(), ConstructMvtx_Layer(), get_layer(), get_phistep(), get_stave(), and PHG4EICMvtxDetector().
std::array<double, n_Layers> PHG4EICMvtxDetector::m_nominal_phi0 {} private
Definition at line 78 of file PHG4EICMvtxDetector.h.
View newest version in sPHENIX GitHub at line 78 of file PHG4EICMvtxDetector.h
Referenced by AddGeometryNode(), ConstructMvtx_Layer(), and PHG4EICMvtxDetector().
std::array<double, n_Layers> PHG4EICMvtxDetector::m_nominal_phitilt {} private
Definition at line 77 of file PHG4EICMvtxDetector.h.
View newest version in sPHENIX GitHub at line 77 of file PHG4EICMvtxDetector.h
Referenced by AddGeometryNode(), ConstructMvtx_Layer(), and PHG4EICMvtxDetector().
std::array<double, n_Layers> PHG4EICMvtxDetector::m_nominal_radius {} private
Definition at line 76 of file PHG4EICMvtxDetector.h.
View newest version in sPHENIX GitHub at line 76 of file PHG4EICMvtxDetector.h
Referenced by AddGeometryNode(), ConstructMvtx_Layer(), and PHG4EICMvtxDetector().
const PHParametersContainer* PHG4EICMvtxDetector::m_ParamsContainer private
Definition at line 65 of file PHG4EICMvtxDetector.h.
View newest version in sPHENIX GitHub at line 65 of file PHG4EICMvtxDetector.h
Referenced by PHG4EICMvtxDetector().
std::set<G4VPhysicalVolume*> PHG4EICMvtxDetector::m_SensorPV private
Definition at line 68 of file PHG4EICMvtxDetector.h.
View newest version in sPHENIX GitHub at line 68 of file PHG4EICMvtxDetector.h
Referenced by FindSensor(), and IsSensor().
std::string PHG4EICMvtxDetector::m_StaveGeometryFile private
Definition at line 82 of file PHG4EICMvtxDetector.h.
View newest version in sPHENIX GitHub at line 82 of file PHG4EICMvtxDetector.h
Referenced by ConstructMvtx().
std::map<G4VPhysicalVolume*, std::tuple<int, int> > PHG4EICMvtxDetector::m_StavePV private
Definition at line 69 of file PHG4EICMvtxDetector.h.
View newest version in sPHENIX GitHub at line 69 of file PHG4EICMvtxDetector.h
Referenced by FillPVArray(), and IsInMvtx().
std::string PHG4EICMvtxDetector::m_SuperDetector private
Definition at line 81 of file PHG4EICMvtxDetector.h.
View newest version in sPHENIX GitHub at line 81 of file PHG4EICMvtxDetector.h
Referenced by AddGeometryNode(), and SuperDetector().
constexpr int PHG4EICMvtxDetector::n_Layers = 3 static private
Definition at line 63 of file PHG4EICMvtxDetector.h.
View newest version in sPHENIX GitHub at line 63 of file PHG4EICMvtxDetector.h
Referenced by AddGeometryNode(), ConstructMvtx(), and PHG4EICMvtxDetector().
The documentation for this class was generated from the following files:
coresoftware/blob/master/simulation/g4simulation/g4mvtx/PHG4EICMvtxDetector.h
coresoftware/blob/master/simulation/g4simulation/g4mvtx/PHG4EICMvtxDetector.cc