Analysis Software: JETSCAPE/blob/main/external_packages/googletest/googlemock/test/gmock_test.cc File Reference
gmock_test.cc File Reference
#include "gmock/gmock.h"
#include <string>
#include "gtest/gtest.h"
Functions
template<typename Char , int M, int N>
void TestInitGoogleMock (const Char *(&argv)[M], const Char *(&new_argv)[N], const ::std::string &expected_gmock_verbose)
TEST (InitGoogleMockTest, ParsesInvalidCommandLine)
TEST (InitGoogleMockTest, ParsesEmptyCommandLine)
TEST (InitGoogleMockTest, ParsesSingleFlag)
TEST (InitGoogleMockTest, ParsesUnrecognizedFlag)
TEST (InitGoogleMockTest, ParsesGoogleMockFlagAndUnrecognizedFlag)
TEST (WideInitGoogleMockTest, ParsesInvalidCommandLine)
TEST (WideInitGoogleMockTest, ParsesEmptyCommandLine)
TEST (WideInitGoogleMockTest, ParsesSingleFlag)
TEST (WideInitGoogleMockTest, ParsesUnrecognizedFlag)
TEST (WideInitGoogleMockTest, ParsesGoogleMockFlagAndUnrecognizedFlag)
TEST (FlagTest, IsAccessibleInCode)
Function Documentation
TEST (InitGoogleMockTest , ParsesInvalidCommandLine)
Definition at line 65 of file gmock_test.cc.
View newest version in sPHENIX GitHub at line 65 of file gmock_test.cc
References GMOCK_FLAG, TestInitGoogleMock(), and verbose.
TEST (InitGoogleMockTest , ParsesEmptyCommandLine)
Definition at line 77 of file gmock_test.cc.
View newest version in sPHENIX GitHub at line 77 of file gmock_test.cc
References GMOCK_FLAG, TestInitGoogleMock(), and verbose.
TEST (InitGoogleMockTest , ParsesSingleFlag)
Definition at line 91 of file gmock_test.cc.
View newest version in sPHENIX GitHub at line 91 of file gmock_test.cc
References TestInitGoogleMock().
TEST (InitGoogleMockTest , ParsesUnrecognizedFlag)
Definition at line 106 of file gmock_test.cc.
View newest version in sPHENIX GitHub at line 106 of file gmock_test.cc
References GMOCK_FLAG, TestInitGoogleMock(), and verbose.
TEST (InitGoogleMockTest , ParsesGoogleMockFlagAndUnrecognizedFlag)
Definition at line 122 of file gmock_test.cc.
View newest version in sPHENIX GitHub at line 122 of file gmock_test.cc
References TestInitGoogleMock().
TEST (WideInitGoogleMockTest , ParsesInvalidCommandLine)
Definition at line 139 of file gmock_test.cc.
View newest version in sPHENIX GitHub at line 139 of file gmock_test.cc
References GMOCK_FLAG, TestInitGoogleMock(), and verbose.
TEST (WideInitGoogleMockTest , ParsesEmptyCommandLine)
Definition at line 151 of file gmock_test.cc.
View newest version in sPHENIX GitHub at line 151 of file gmock_test.cc
References GMOCK_FLAG, Acts::IntegrationTest::L, TestInitGoogleMock(), and verbose.
TEST (WideInitGoogleMockTest , ParsesSingleFlag)
Definition at line 165 of file gmock_test.cc.
View newest version in sPHENIX GitHub at line 165 of file gmock_test.cc
References Acts::IntegrationTest::L, and TestInitGoogleMock().
TEST (WideInitGoogleMockTest , ParsesUnrecognizedFlag)
Definition at line 180 of file gmock_test.cc.
View newest version in sPHENIX GitHub at line 180 of file gmock_test.cc
References GMOCK_FLAG, Acts::IntegrationTest::L, TestInitGoogleMock(), and verbose.
TEST (WideInitGoogleMockTest , ParsesGoogleMockFlagAndUnrecognizedFlag)
Definition at line 196 of file gmock_test.cc.
View newest version in sPHENIX GitHub at line 196 of file gmock_test.cc
References Acts::IntegrationTest::L, and TestInitGoogleMock().
TEST (FlagTest , IsAccessibleInCode)
Definition at line 216 of file gmock_test.cc.
View newest version in sPHENIX GitHub at line 216 of file gmock_test.cc
References dummy, GMOCK_FLAG, and verbose.
template<typename Char , int M, int N> void TestInitGoogleMock (const Char *(&) argv[M], const Char *(&) new_argv[N], const ::std::string & expected_gmock_verbose)
Definition at line 49 of file gmock_test.cc.
View newest version in sPHENIX GitHub at line 49 of file gmock_test.cc
References ASSERT_EQ, EXPECT_EQ, EXPECT_STREQ, GMOCK_FLAG, i, testing::InitGoogleMock(), N, and verbose.
Referenced by TEST().