Analysis Software: analysis/blob/master/dNdEta_Run2023/analysis_INTT/src/INTTVtxZ.cxx File Reference
INTTVtxZ.cxx File Reference
#include <cmath>
#include <fstream>
#include <iostream>
#include <sstream>
#include <string>
#include <vector>
#include <TCanvas.h>
#include <TF1.h>
#include <TFile.h>
#include <TH1F.h>
#include <TH2F.h>
#include <TKDE.h>
#include <TRandom.h>
#include "Math/DistFunc.h"
#include <TLegend.h>
#include <TLine.h>
#include <TMath.h>
#include <TObjString.h>
#include <TProfile.h>
#include <TRandom3.h>
#include <TText.h>
#include <TTree.h>
#include <TTreeIndex.h>
#include "Hit.h"
#include "Utilities.h"
#include "Vertex.h"
Functions
double gaus_func (double *x, double *par)
void draw_demoplot (TH1F *h, TF1 *f, float dcacut, TString plotname)
int main (int argc, char *argv[])
Variables
int NevtToPlot = 10
float degreetoradian = TMath::Pi() / 180.
float radianstodegree = 180. / TMath::Pi()
Function Documentation
void draw_demoplot (TH1F * h, TF1 * f, float dcacut, TString plotname)
Definition at line 45 of file INTTVtxZ.cxx.
View newest version in sPHENIX GitHub at line 45 of file INTTVtxZ.cxx
References Acts::PhysicalConstants::c, and leg.
Referenced by main().
double gaus_func (double * x, double * par)
Definition at line 36 of file INTTVtxZ.cxx.
View newest version in sPHENIX GitHub at line 36 of file INTTVtxZ.cxx
Referenced by main().
int main (int argc, char * argv[])
TO BE FIXED
Definition at line 74 of file INTTVtxZ.cxx.
View newest version in sPHENIX GitHub at line 74 of file INTTVtxZ.cxx
References KFPMath::b, VtxData::Centrality_bimp, VtxData::Centrality_impactparam, VtxData::Centrality_mbd, VtxData::Centrality_mbdquantity, CleanVec(), INTTVtxZ::dca, Acts::Test::debug, deltaPhi(), draw_demoplot(), event, VtxData::event, f, std::tr1::f1, gaus_func(), i, configureMap::ibin, index, VtxData::isdata, j, layer, Acts::UnitConstants::m, runCondor_recovtxz::makedemoplot, mean(), VtxData::NClusLayer1, NevtToPlot, VtxData::NTruthVtx, add_histos::outfile, pname(), VtxData::PV_x, VtxData::PV_y, VtxData::PV_z, radianstodegree, Hit::SetEdge(), SetsPhenixStyle(), SetVtxMinitree(), t, VtxData::TruthPV_x, VtxData::TruthPV_y, VtxData::TruthPV_z, and physmon_track_finding_ttbar::z.
Variable Documentation
float degreetoradian = TMath::Pi() / 180.
Definition at line 33 of file INTTVtxZ.cxx.
View newest version in sPHENIX GitHub at line 33 of file INTTVtxZ.cxx
int NevtToPlot = 10
Definition at line 32 of file INTTVtxZ.cxx.
View newest version in sPHENIX GitHub at line 32 of file INTTVtxZ.cxx
Referenced by main().
float radianstodegree = 180. / TMath::Pi()
Definition at line 34 of file INTTVtxZ.cxx.
View newest version in sPHENIX GitHub at line 34 of file INTTVtxZ.cxx
Referenced by main().