Analysis Software: testing::gmock_more_actions_test::Foo Class Reference
testing::gmock_more_actions_test::Foo Class Reference
Public Member Functions
Foo ()
int Nullary () const
short Unary (long x)
string Binary (const string &str, char c) const
int Ternary (int x, bool y, char z)
int SumOf4 (int a, int b, int c, int d) const
int SumOfLast2 (Unused, Unused, int a, int b) const
int SumOf5 (int a, int b, int c, int d, int e)
int SumOf6 (int a, int b, int c, int d, int e, int f)
string Concat7 (const char *s1, const char *s2, const char *s3, const char *s4, const char *s5, const char *s6, const char *s7)
string Concat8 (const char *s1, const char *s2, const char *s3, const char *s4, const char *s5, const char *s6, const char *s7, const char *s8)
string Concat9 (const char *s1, const char *s2, const char *s3, const char *s4, const char *s5, const char *s6, const char *s7, const char *s8, const char *s9)
string Concat10 (const char *s1, const char *s2, const char *s3, const char *s4, const char *s5, const char *s6, const char *s7, const char *s8, const char *s9, const char *s10)
Private Attributes
int value_
Detailed Description
Definition at line 180 of file gmock-more-actions_test.cc.
View newest version in sPHENIX GitHub at line 180 of file gmock-more-actions_test.cc
Constructor & Destructor Documentation
testing::gmock_more_actions_test::Foo::Foo () inline
Definition at line 182 of file gmock-more-actions_test.cc.
View newest version in sPHENIX GitHub at line 182 of file gmock-more-actions_test.cc
Member Function Documentation
string testing::gmock_more_actions_test::Foo::Binary (const string & str, char c) const inline
Definition at line 188 of file gmock-more-actions_test.cc.
View newest version in sPHENIX GitHub at line 188 of file gmock-more-actions_test.cc
References Acts::PhysicalConstants::c.
Referenced by testing::gmock_more_actions_test::TEST().
string testing::gmock_more_actions_test::Foo::Concat10 (const char * s1, const char * s2, const char * s3, const char * s4, const char * s5, const char * s6, const char * s7, const char * s8, const char * s9, const char * s10) inline
Definition at line 222 of file gmock-more-actions_test.cc.
View newest version in sPHENIX GitHub at line 222 of file gmock-more-actions_test.cc
Referenced by testing::gmock_more_actions_test::TEST().
string testing::gmock_more_actions_test::Foo::Concat7 (const char * s1, const char * s2, const char * s3, const char * s4, const char * s5, const char * s6, const char * s7) inline
Definition at line 204 of file gmock-more-actions_test.cc.
View newest version in sPHENIX GitHub at line 204 of file gmock-more-actions_test.cc
Referenced by testing::gmock_more_actions_test::TEST().
string testing::gmock_more_actions_test::Foo::Concat8 (const char * s1, const char * s2, const char * s3, const char * s4, const char * s5, const char * s6, const char * s7, const char * s8) inline
Definition at line 210 of file gmock-more-actions_test.cc.
View newest version in sPHENIX GitHub at line 210 of file gmock-more-actions_test.cc
Referenced by testing::gmock_more_actions_test::TEST().
string testing::gmock_more_actions_test::Foo::Concat9 (const char * s1, const char * s2, const char * s3, const char * s4, const char * s5, const char * s6, const char * s7, const char * s8, const char * s9) inline
Definition at line 216 of file gmock-more-actions_test.cc.
View newest version in sPHENIX GitHub at line 216 of file gmock-more-actions_test.cc
Referenced by testing::gmock_more_actions_test::TEST().
int testing::gmock_more_actions_test::Foo::Nullary () const inline
Definition at line 184 of file gmock-more-actions_test.cc.
View newest version in sPHENIX GitHub at line 184 of file gmock-more-actions_test.cc
References value_.
Referenced by testing::gmock_more_actions_test::TEST().
int testing::gmock_more_actions_test::Foo::SumOf4 (int a, int b, int c, int d) const inline
Definition at line 192 of file gmock-more-actions_test.cc.
View newest version in sPHENIX GitHub at line 192 of file gmock-more-actions_test.cc
References value_.
Referenced by testing::gmock_more_actions_test::TEST().
int testing::gmock_more_actions_test::Foo::SumOf5 (int a, int b, int c, int d, int e) inline
Definition at line 198 of file gmock-more-actions_test.cc.
View newest version in sPHENIX GitHub at line 198 of file gmock-more-actions_test.cc
References Acts::UnitConstants::e.
Referenced by testing::gmock_more_actions_test::TEST().
int testing::gmock_more_actions_test::Foo::SumOf6 (int a, int b, int c, int d, int e, int f) inline
Definition at line 200 of file gmock-more-actions_test.cc.
View newest version in sPHENIX GitHub at line 200 of file gmock-more-actions_test.cc
References f.
Referenced by testing::gmock_more_actions_test::TEST().
int testing::gmock_more_actions_test::Foo::SumOfLast2 (Unused , Unused , int a, int b) const inline
Definition at line 196 of file gmock-more-actions_test.cc.
View newest version in sPHENIX GitHub at line 196 of file gmock-more-actions_test.cc
References KFPMath::b.
Referenced by testing::gmock_more_actions_test::TEST().
int testing::gmock_more_actions_test::Foo::Ternary (int x, bool y, char z) inline
Definition at line 190 of file gmock-more-actions_test.cc.
View newest version in sPHENIX GitHub at line 190 of file gmock-more-actions_test.cc
References value_, and physmon_track_finding_ttbar::z.
Referenced by testing::gmock_more_actions_test::TEST().
short testing::gmock_more_actions_test::Foo::Unary (long x) inline
Definition at line 186 of file gmock-more-actions_test.cc.
View newest version in sPHENIX GitHub at line 186 of file gmock-more-actions_test.cc
References value_, and ambiguity_solver_full_chain::x.
Referenced by testing::gmock_more_actions_test::TEST().
Member Data Documentation
int testing::gmock_more_actions_test::Foo::value_ private
Definition at line 230 of file gmock-more-actions_test.cc.
View newest version in sPHENIX GitHub at line 230 of file gmock-more-actions_test.cc
Referenced by Nullary(), SumOf4(), Ternary(), and Unary().
The documentation for this class was generated from the following file:
JETSCAPE/blob/main/external_packages/googletest/googlemock/test/gmock-more-actions_test.cc