Analysis Software: PHG4CylinderCellReco Class Reference
PHG4CylinderCellReco Class Reference
#include <coresoftware/blob/master/simulation/g4simulation/g4detectors/PHG4CylinderCellReco.h>
Public Member Functions
PHG4CylinderCellReco (const std::string &name="CYLINDERRECO")
~PHG4CylinderCellReco () override
int InitRun (PHCompositeNode *topNode) override
module initialization
int process_event (PHCompositeNode *topNode) override
event processing
int ResetEvent (PHCompositeNode *topNode) override
Clean up after each event.
void SetDefaultParameters () override
void Detector (const std::string &d)
void cellsize (const int i, const double sr, const double sz)
void etaphisize (const int i, const double deltaeta, const double deltaphi)
void checkenergy (const int i=1)
void OutputDetector (const std::string &d)
double get_timing_window_min (const int i)
double get_timing_window_max (const int i)
void set_timing_window (const int detid, const double tmin, const double tmax)
Public Member Functions inherited from SubsysReco
~SubsysReco () override
virtual int End (PHCompositeNode *)
Called at the end of all processing.
virtual int EndRun (const int)
Called at the end of each run.
virtual int Init (PHCompositeNode *)
virtual int Reset (PHCompositeNode *)
Reset.
void Print (const std::string &="ALL") const override
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Public Member Functions inherited from PHParameterContainerInterface
PHParameterContainerInterface (const std::string &name)
PHParameterContainerInterface (const PHParameterContainerInterface &)=delete
PHParameterContainerInterface & operator= (PHParameterContainerInterface const &)=delete
virtual ~PHParameterContainerInterface ()
void set_name (const std::string &name)
void set_double_param (const int id, const std::string &name, const double dval)
double get_double_param (const int id, const std::string &name) const
void set_int_param (const int id, const std::string &name, const int ival)
int get_int_param (const int id, const std::string &name) const
void set_string_param (const int id, const std::string &name, const std::string &sval)
std::string get_string_param (const int id, const std::string &name) const
void UpdateParametersWithMacro ()
void CreateInitialize (const int detid)
void SaveToNodeTree (PHCompositeNode *runNode, const std::string &nodename)
void PutOnParNode (PHCompositeNode *parNode, const std::string &nodename)
int ExistDetid (const int detid) const
Protected Member Functions
void set_size (const int i, const double sizeA, const double sizeB)
int CheckEnergy (PHCompositeNode *topNode)
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Protected Member Functions inherited from Fun4AllBase
Fun4AllBase (const std::string &name="NONAME")
Protected Member Functions inherited from PHParameterContainerInterface
void set_default_double_param (const std::string &name, const double dval)
void set_default_int_param (const std::string &name, const int ival)
void set_default_string_param (const std::string &name, const std::string &sval)
void InitializeParameters ()
const PHParametersContainer * GetParamsContainer ()
PHParametersContainer * GetParamsContainerModify ()
const PHParameters * GetDefaultParameters ()
Protected Attributes
std::map< int, int > binning
std::map< int, std::pair
< double, double > > cell_size
std::map< int, std::pair
< double, double > > zmin_max
std::map< int, double > phistep
std::map< int, double > etastep
std::set< int > implemented_detid
std::string detector
std::string outdetector
std::string hitnodename
std::string cellnodename
std::string geonodename
std::string seggeonodename
std::map< int, std::pair< int,
int > > n_phi_z_bins
std::map< unsigned long long,
PHG4Cell * > cellptmap
std::map< unsigned long long,
PHG4Cell * >::iterator it
std::map< int, std::pair
< double, double > > tmin_max
std::map< int, double > m_DeltaTMap
int nbins [2]
int chkenergyconservation = 0
double sum_energy_before_cuts = 0.
double sum_energy_g4hit = 0.
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = std::numeric_limits<int>::max() - 10
}
Detailed Description
Definition at line 18 of file PHG4CylinderCellReco.h.
View newest version in sPHENIX GitHub at line 18 of file PHG4CylinderCellReco.h
Constructor & Destructor Documentation
PHG4CylinderCellReco::PHG4CylinderCellReco (const std::string & name = "CYLINDERRECO") explicit
Definition at line 40 of file PHG4CylinderCellReco.cc.
View newest version in sPHENIX GitHub at line 40 of file PHG4CylinderCellReco.cc
References nbins, and SetDefaultParameters().
PHG4CylinderCellReco::~PHG4CylinderCellReco () inline override
Definition at line 23 of file PHG4CylinderCellReco.h.
View newest version in sPHENIX GitHub at line 23 of file PHG4CylinderCellReco.h
Member Function Documentation
void PHG4CylinderCellReco::cellsize (const int i, const double sr, const double sz)
Definition at line 873 of file PHG4CylinderCellReco.cc.
View newest version in sPHENIX GitHub at line 873 of file PHG4CylinderCellReco.cc
References binning, PHParameterContainerInterface::set_double_param(), and PHG4CellDefs::sizebinning.
Referenced by CEMC_Cells(), and Svtx_Cells().
void PHG4CylinderCellReco::checkenergy (const int i = 1) inline
Definition at line 39 of file PHG4CylinderCellReco.h.
View newest version in sPHENIX GitHub at line 39 of file PHG4CylinderCellReco.h
References chkenergyconservation, and i.
int PHG4CylinderCellReco::CheckEnergy (PHCompositeNode * topNode) protected
Definition at line 911 of file PHG4CylinderCellReco.cc.
View newest version in sPHENIX GitHub at line 911 of file PHG4CylinderCellReco.cc
References cellnodename, Acts::UnitConstants::e, PHG4CellContainer::getCells(), Fun4AllBase::Name(), sum_energy_before_cuts, sum_energy_g4hit, and Fun4AllBase::Verbosity().
Referenced by process_event().
void PHG4CylinderCellReco::Detector (const std::string & d)
Definition at line 980 of file PHG4CylinderCellReco.cc.
View newest version in sPHENIX GitHub at line 980 of file PHG4CylinderCellReco.cc
References outdetector, and OutputDetector().
Referenced by CEMC_Cells(), Fun4All_G4_Clusters(), and Svtx_Cells().
void PHG4CylinderCellReco::etaphisize (const int i, const double deltaeta, const double deltaphi)
Definition at line 885 of file PHG4CylinderCellReco.cc.
View newest version in sPHENIX GitHub at line 885 of file PHG4CylinderCellReco.cc
References binning, PHG4CellDefs::etaphibinning, and PHParameterContainerInterface::set_double_param().
Referenced by Fun4All_G4_Clusters().
double PHG4CylinderCellReco::get_timing_window_max (const int i) inline
Definition at line 43 of file PHG4CylinderCellReco.h.
View newest version in sPHENIX GitHub at line 43 of file PHG4CylinderCellReco.h
References i, and tmin_max.
double PHG4CylinderCellReco::get_timing_window_min (const int i) inline
Definition at line 42 of file PHG4CylinderCellReco.h.
View newest version in sPHENIX GitHub at line 42 of file PHG4CylinderCellReco.h
References i, and tmin_max.
int PHG4CylinderCellReco::InitRun (PHCompositeNode * topNode) override virtual
module initialization
Reimplemented from SubsysReco.
Definition at line 55 of file PHG4CylinderCellReco.cc.
View newest version in sPHENIX GitHub at line 55 of file PHG4CylinderCellReco.cc
References PHG4CylinderCellGeomContainer::AddLayerCellGeom(), PHCompositeNode::addNode(), binning, cell_size, cellnodename, detector, Acts::UnitConstants::e, etamax, etamin, PHG4CellDefs::etaphibinning, etastep, Fun4AllReturnCodes::EVENT_OK, PHParameterContainerInterface::ExistDetid(), PHNodeIterator::findFirst(), geonodename, PHG4CylinderGeomContainer::get_begin_end(), PHParameterContainerInterface::get_double_param(), PHG4Utils::get_eta(), PHG4CylinderGeom::get_layer(), PHG4CylinderGeom::get_radius(), PHG4CylinderGeom::get_thickness(), PHG4CylinderGeom::get_zmax(), PHG4CylinderGeom::get_zmin(), PHParameterContainerInterface::GetParamsContainer(), PHParameterContainerInterface::GetParamsContainerModify(), hitnodename, i, PHG4CylinderCellGeom::identify(), PHG4CylinderGeomContainer::identify(), implemented_detid, layer, m_DeltaTMap, n_phi_z_bins, Fun4AllBase::Name(), PHParametersContainer::Name(), nbins, outdetector, MATSCAN::phibins, MATSCAN::phimin, phistep, PHWHERE, PHParameterContainerInterface::SaveToNodeTree(), seggeonodename, PHG4CylinderCellGeom::set_binning(), PHG4CylinderCellGeom::set_etabins(), PHG4CylinderCellGeom::set_etamin(), PHG4CylinderCellGeom::set_etastep(), PHG4CylinderCellGeom::set_layer(), PHParametersContainer::set_name(), PHG4CylinderCellGeom::set_phibins(), PHG4CylinderCellGeom::set_phimin(), PHG4CylinderCellGeom::set_phistep(), PHG4CylinderCellGeom::set_radius(), set_size(), PHG4CylinderCellGeom::set_thickness(), PHG4CylinderCellGeom::set_zbins(), PHG4CylinderCellGeom::set_zmin(), PHG4CylinderCellGeom::set_zstep(), G4HCALOUT::size_z, PHG4CellDefs::sizebinning, tmin_max, PHParameterContainerInterface::UpdateParametersWithMacro(), Fun4AllBase::Verbosity(), and zmin_max.
void PHG4CylinderCellReco::OutputDetector (const std::string & d) inline
Definition at line 40 of file PHG4CylinderCellReco.h.
View newest version in sPHENIX GitHub at line 40 of file PHG4CylinderCellReco.h
References outdetector.
Referenced by Detector().
int PHG4CylinderCellReco::process_event (PHCompositeNode * topNode) override virtual
event processing
Reimplemented from SubsysReco.
Definition at line 364 of file PHG4CylinderCellReco.cc.
View newest version in sPHENIX GitHub at line 364 of file PHG4CylinderCellReco.cc
References PHG4Cell::add_edep(), PHG4Cell::add_light_yield(), PHG4Cell::add_shower_edep(), PHG4CellContainer::AddCell(), CKF_timing_vs_mu::ax, binning, cell_size, cellnodename, cellptmap, CheckEnergy(), chkenergyconservation, dy, KF_timing::etabin, PHG4CellDefs::etaphibinning, Fun4AllReturnCodes::EVENT_OK, PHG4CellDefs::SizeBinning::genkey(), PHG4CellDefs::EtaPhiBinning::genkey(), PHG4Cell::get_edep(), PHG4CylinderCellGeom::get_etabin(), PHG4CellDefs::EtaPhiBinning::get_etabin(), PHG4CylinderCellGeom::get_etacenter(), PHG4Utils::get_etaphi(), PHG4CylinderCellGeom::get_etastep(), PHG4CylinderCellGeom::get_phibin(), PHG4CellDefs::SizeBinning::get_phibin(), PHG4CellDefs::EtaPhiBinning::get_phibin(), PHG4CylinderCellGeom::get_phicenter(), PHG4CylinderCellGeom::get_phistep(), PHG4CylinderCellGeom::get_zbin(), PHG4CellDefs::SizeBinning::get_zbin(), PHG4CylinderCellGeom::get_zcenter(), PHG4CylinderCellGeom::get_zstep(), PHG4HitContainer::getHits(), PHG4CylinderCellGeomContainer::GetLayerCellGeom(), PHG4HitContainer::getLayers(), hitnodename, i, implemented_detid, Acts::PlanarHelper::intersect(), it, layer, PHG4Utils::line_and_rectangle_intersect(), m_DeltaTMap, n_phi_z_bins, Fun4AllBase::Name(), ActsTests::PropagationDatasets::phi, phistep, PHWHERE, PHG4Hit::prop_light_yield, seggeonodename, sum_energy_before_cuts, sum_energy_g4hit, tmin_max, Acts::Test::tmp(), Fun4AllBase::Verbosity(), vz, physmon_track_finding_ttbar::z, and zmin_max.
int PHG4CylinderCellReco::ResetEvent (PHCompositeNode *) override virtual
Clean up after each event.
Reimplemented from SubsysReco.
Definition at line 48 of file PHG4CylinderCellReco.cc.
View newest version in sPHENIX GitHub at line 48 of file PHG4CylinderCellReco.cc
References Fun4AllReturnCodes::EVENT_OK, sum_energy_before_cuts, and sum_energy_g4hit.
void PHG4CylinderCellReco::set_size (const int i, const double sizeA, const double sizeB) protected
Definition at line 898 of file PHG4CylinderCellReco.cc.
View newest version in sPHENIX GitHub at line 898 of file PHG4CylinderCellReco.cc
References cell_size, and i.
Referenced by InitRun().
void PHG4CylinderCellReco::set_timing_window (const int detid, const double tmin, const double tmax)
Definition at line 904 of file PHG4CylinderCellReco.cc.
View newest version in sPHENIX GitHub at line 904 of file PHG4CylinderCellReco.cc
References PHParameterContainerInterface::set_double_param().
void PHG4CylinderCellReco::SetDefaultParameters () override virtual
Implements PHParameterContainerInterface.
Definition at line 992 of file PHG4CylinderCellReco.cc.
View newest version in sPHENIX GitHub at line 992 of file PHG4CylinderCellReco.cc
References PHParameterContainerInterface::set_default_double_param().
Referenced by PHG4CylinderCellReco().
Member Data Documentation
std::map<int, int> PHG4CylinderCellReco::binning protected
Definition at line 50 of file PHG4CylinderCellReco.h.
View newest version in sPHENIX GitHub at line 50 of file PHG4CylinderCellReco.h
Referenced by cellsize(), etaphisize(), InitRun(), and process_event().
std::map<int, std::pair<double, double> > PHG4CylinderCellReco::cell_size protected
Definition at line 51 of file PHG4CylinderCellReco.h.
View newest version in sPHENIX GitHub at line 51 of file PHG4CylinderCellReco.h
Referenced by InitRun(), process_event(), and set_size().
std::string PHG4CylinderCellReco::cellnodename protected
Definition at line 59 of file PHG4CylinderCellReco.h.
View newest version in sPHENIX GitHub at line 59 of file PHG4CylinderCellReco.h
Referenced by CheckEnergy(), InitRun(), and process_event().
std::map<unsigned long long, PHG4Cell *> PHG4CylinderCellReco::cellptmap protected
Definition at line 63 of file PHG4CylinderCellReco.h.
View newest version in sPHENIX GitHub at line 63 of file PHG4CylinderCellReco.h
Referenced by process_event().
int PHG4CylinderCellReco::chkenergyconservation = 0 protected
Definition at line 69 of file PHG4CylinderCellReco.h.
View newest version in sPHENIX GitHub at line 69 of file PHG4CylinderCellReco.h
Referenced by checkenergy(), and process_event().
std::string PHG4CylinderCellReco::detector protected
Definition at line 56 of file PHG4CylinderCellReco.h.
View newest version in sPHENIX GitHub at line 56 of file PHG4CylinderCellReco.h
Referenced by InitRun().
std::map<int, double> PHG4CylinderCellReco::etastep protected
Definition at line 54 of file PHG4CylinderCellReco.h.
View newest version in sPHENIX GitHub at line 54 of file PHG4CylinderCellReco.h
Referenced by InitRun().
std::string PHG4CylinderCellReco::geonodename protected
Definition at line 60 of file PHG4CylinderCellReco.h.
View newest version in sPHENIX GitHub at line 60 of file PHG4CylinderCellReco.h
Referenced by InitRun().
std::string PHG4CylinderCellReco::hitnodename protected
Definition at line 58 of file PHG4CylinderCellReco.h.
View newest version in sPHENIX GitHub at line 58 of file PHG4CylinderCellReco.h
Referenced by InitRun(), and process_event().
std::set<int> PHG4CylinderCellReco::implemented_detid protected
Definition at line 55 of file PHG4CylinderCellReco.h.
View newest version in sPHENIX GitHub at line 55 of file PHG4CylinderCellReco.h
Referenced by InitRun(), and process_event().
std::map<unsigned long long, PHG4Cell *>::iterator PHG4CylinderCellReco::it protected
Definition at line 64 of file PHG4CylinderCellReco.h.
View newest version in sPHENIX GitHub at line 64 of file PHG4CylinderCellReco.h
Referenced by process_event().
std::map<int, double> PHG4CylinderCellReco::m_DeltaTMap protected
Definition at line 66 of file PHG4CylinderCellReco.h.
View newest version in sPHENIX GitHub at line 66 of file PHG4CylinderCellReco.h
Referenced by InitRun(), and process_event().
std::map<int, std::pair<int, int> > PHG4CylinderCellReco::n_phi_z_bins protected
Definition at line 62 of file PHG4CylinderCellReco.h.
View newest version in sPHENIX GitHub at line 62 of file PHG4CylinderCellReco.h
Referenced by InitRun(), and process_event().
int PHG4CylinderCellReco::nbins[2] protected
Definition at line 68 of file PHG4CylinderCellReco.h.
View newest version in sPHENIX GitHub at line 68 of file PHG4CylinderCellReco.h
Referenced by InitRun(), and PHG4CylinderCellReco().
std::string PHG4CylinderCellReco::outdetector protected
Definition at line 57 of file PHG4CylinderCellReco.h.
View newest version in sPHENIX GitHub at line 57 of file PHG4CylinderCellReco.h
Referenced by Detector(), InitRun(), and OutputDetector().
std::map<int, double> PHG4CylinderCellReco::phistep protected
Definition at line 53 of file PHG4CylinderCellReco.h.
View newest version in sPHENIX GitHub at line 53 of file PHG4CylinderCellReco.h
Referenced by InitRun(), and process_event().
std::string PHG4CylinderCellReco::seggeonodename protected
Definition at line 61 of file PHG4CylinderCellReco.h.
View newest version in sPHENIX GitHub at line 61 of file PHG4CylinderCellReco.h
Referenced by InitRun(), and process_event().
double PHG4CylinderCellReco::sum_energy_before_cuts = 0. protected
Definition at line 71 of file PHG4CylinderCellReco.h.
View newest version in sPHENIX GitHub at line 71 of file PHG4CylinderCellReco.h
Referenced by CheckEnergy(), process_event(), and ResetEvent().
double PHG4CylinderCellReco::sum_energy_g4hit = 0. protected
Definition at line 72 of file PHG4CylinderCellReco.h.
View newest version in sPHENIX GitHub at line 72 of file PHG4CylinderCellReco.h
Referenced by CheckEnergy(), process_event(), and ResetEvent().
std::map<int, std::pair<double, double> > PHG4CylinderCellReco::tmin_max protected
Definition at line 65 of file PHG4CylinderCellReco.h.
View newest version in sPHENIX GitHub at line 65 of file PHG4CylinderCellReco.h
Referenced by get_timing_window_max(), get_timing_window_min(), InitRun(), and process_event().
std::map<int, std::pair<double, double> > PHG4CylinderCellReco::zmin_max protected
Definition at line 52 of file PHG4CylinderCellReco.h.
View newest version in sPHENIX GitHub at line 52 of file PHG4CylinderCellReco.h
Referenced by InitRun(), and process_event().
The documentation for this class was generated from the following files:
coresoftware/blob/master/simulation/g4simulation/g4detectors/PHG4CylinderCellReco.h
coresoftware/blob/master/simulation/g4simulation/g4detectors/PHG4CylinderCellReco.cc