Analysis Software: sigslot::_connection0< dest_type, mt_policy > Class Template Reference
sigslot::_connection0< dest_type, mt_policy > Class Template Reference
#include <JETSCAPE/blob/main/external_packages/sigslot.h>
Public Member Functions
_connection0 ()
_connection0 (dest_type *pobject, void(dest_type::*pmemfun)())
virtual _connection_base0
< mt_policy > * clone ()
virtual _connection_base0
< mt_policy > * duplicate (has_slots< mt_policy > *pnewdest)
virtual void emit ()
virtual has_slots< mt_policy > * getdest () const
Public Member Functions inherited from sigslot::_connection_base0< mt_policy >
virtual ~_connection_base0 ()
Private Attributes
dest_type * m_pobject
void(dest_type::* m_pmemfun)()
Detailed Description
template<class dest_type, class mt_policy>
class sigslot::_connection0< dest_type, mt_policy >
Definition at line 1523 of file sigslot.h.
View newest version in sPHENIX GitHub at line 1523 of file sigslot.h
Constructor & Destructor Documentation
template<class dest_type, class mt_policy> sigslot::_connection0< dest_type, mt_policy >::_connection0 () inline
Definition at line 1526 of file sigslot.h.
View newest version in sPHENIX GitHub at line 1526 of file sigslot.h
template<class dest_type, class mt_policy> sigslot::_connection0< dest_type, mt_policy >::_connection0 (dest_type * pobject, void(dest_type::*)() pmemfun) inline
Definition at line 1532 of file sigslot.h.
View newest version in sPHENIX GitHub at line 1532 of file sigslot.h
References sigslot::_connection0< dest_type, mt_policy >::m_pmemfun, and sigslot::_connection0< dest_type, mt_policy >::m_pobject.
Member Function Documentation
template<class dest_type, class mt_policy> virtual _connection_base0<mt_policy>* sigslot::_connection0< dest_type, mt_policy >::clone () inline virtual
Implements sigslot::_connection_base0< mt_policy >.
Definition at line 1538 of file sigslot.h.
View newest version in sPHENIX GitHub at line 1538 of file sigslot.h
template<class dest_type, class mt_policy> virtual _connection_base0<mt_policy>* sigslot::_connection0< dest_type, mt_policy >::duplicate (has_slots< mt_policy > * pnewdest) inline virtual
Implements sigslot::_connection_base0< mt_policy >.
Definition at line 1543 of file sigslot.h.
View newest version in sPHENIX GitHub at line 1543 of file sigslot.h
References sigslot::_connection0< dest_type, mt_policy >::m_pmemfun.
template<class dest_type, class mt_policy> virtual void sigslot::_connection0< dest_type, mt_policy >::emit () inline virtual
Implements sigslot::_connection_base0< mt_policy >.
Definition at line 1548 of file sigslot.h.
View newest version in sPHENIX GitHub at line 1548 of file sigslot.h
References sigslot::_connection0< dest_type, mt_policy >::m_pmemfun, and sigslot::_connection0< dest_type, mt_policy >::m_pobject.
template<class dest_type, class mt_policy> virtual has_slots<mt_policy>* sigslot::_connection0< dest_type, mt_policy >::getdest () const inline virtual
Implements sigslot::_connection_base0< mt_policy >.
Definition at line 1553 of file sigslot.h.
View newest version in sPHENIX GitHub at line 1553 of file sigslot.h
References sigslot::_connection0< dest_type, mt_policy >::m_pobject.
Member Data Documentation
template<class dest_type, class mt_policy> void(dest_type::* sigslot::_connection0< dest_type, mt_policy >::m_pmemfun)() private
Definition at line 1560 of file sigslot.h.
View newest version in sPHENIX GitHub at line 1560 of file sigslot.h
Referenced by sigslot::_connection0< dest_type, mt_policy >::_connection0(), sigslot::_connection0< dest_type, mt_policy >::duplicate(), and sigslot::_connection0< dest_type, mt_policy >::emit().
template<class dest_type, class mt_policy> dest_type* sigslot::_connection0< dest_type, mt_policy >::m_pobject private
Definition at line 1559 of file sigslot.h.
View newest version in sPHENIX GitHub at line 1559 of file sigslot.h
Referenced by sigslot::_connection0< dest_type, mt_policy >::_connection0(), sigslot::_connection0< dest_type, mt_policy >::emit(), and sigslot::_connection0< dest_type, mt_policy >::getdest().
The documentation for this class was generated from the following file:
JETSCAPE/blob/main/external_packages/sigslot.h