Analysis Software: ActsExamples::Geant4::Geant4Detector Struct Reference
ActsExamples::Geant4::Geant4Detector Struct Reference
#include <acts/blob/sPHENIX/Examples/Detectors/Geant4Detector/include/ActsExamples/Geant4Detector/Geant4Detector.hpp>
Classes
struct Config
Nested configuration struct.
Public Types
using DetectorElements = std::vector< std::shared_ptr< Acts::Geant4DetectorElement >>
using DetectorPtr = std::shared_ptr< Acts::Experimental::Detector >
using Surfaces = std::vector< std::shared_ptr< Acts::Surface >>
using ContextDecorators = std::vector< std::shared_ptr< ActsExamples::IContextDecorator >>
using TrackingGeometryPtr = std::shared_ptr< const Acts::TrackingGeometry >
Public Member Functions
std::tuple< DetectorPtr,
ContextDecorators,
DetectorElements > constructDetector (const Config &cfg, const Acts::Logger &logger)
Construct an Acts::Detector from a Geant4 world volume.
std::tuple
< TrackingGeometryPtr,
ContextDecorators,
DetectorElements > constructTrackingGeometry (const Config &cfg, const Acts::Logger &logger)
Construct a TrackingGeometry from a Geant4 world volume using the KDTreeTrackingGeometryBuilder builder.
Private Member Functions
std::tuple< Surfaces,
DetectorElements > convertGeant4Volumes (const Config &cfg, const Acts::Logger &logger) const
Convert Geant4VPhysicalVolume objects into Acts components.
Detailed Description
Definition at line 38 of file Geant4Detector.hpp.
View newest version in sPHENIX GitHub at line 38 of file Geant4Detector.hpp
Member Typedef Documentation
using ActsExamples::Geant4::Geant4Detector::ContextDecorators = std::vector<std::shared_ptr<ActsExamples::IContextDecorator>>
Definition at line 45 of file Geant4Detector.hpp.
View newest version in sPHENIX GitHub at line 45 of file Geant4Detector.hpp
using ActsExamples::Geant4::Geant4Detector::DetectorElements = std::vector<std::shared_ptr<Acts::Geant4DetectorElement>>
Definition at line 40 of file Geant4Detector.hpp.
View newest version in sPHENIX GitHub at line 40 of file Geant4Detector.hpp
using ActsExamples::Geant4::Geant4Detector::DetectorPtr = std::shared_ptr<Acts::Experimental::Detector>
Definition at line 41 of file Geant4Detector.hpp.
View newest version in sPHENIX GitHub at line 41 of file Geant4Detector.hpp
using ActsExamples::Geant4::Geant4Detector::Surfaces = std::vector<std::shared_ptr<Acts::Surface>>
Definition at line 42 of file Geant4Detector.hpp.
View newest version in sPHENIX GitHub at line 42 of file Geant4Detector.hpp
using ActsExamples::Geant4::Geant4Detector::TrackingGeometryPtr = std::shared_ptr<const Acts::TrackingGeometry>
Definition at line 46 of file Geant4Detector.hpp.
View newest version in sPHENIX GitHub at line 46 of file Geant4Detector.hpp
Member Function Documentation
auto ActsExamples::Geant4::Geant4Detector::constructDetector (const Config & cfg, const Acts::Logger & logger)
Construct an Acts::Detector from a Geant4 world volume.
Parameters
cfg the configuration of the Geant4 detector
logger a logger instance
Returns
a tuple of an Acts::Detector object, a ContextDecorator & the created detector elements
Definition at line 25 of file Geant4Detector.cpp.
View newest version in sPHENIX GitHub at line 25 of file Geant4Detector.cpp
References ACTS_INFO, cfg, itk::decorators, and logger().
auto ActsExamples::Geant4::Geant4Detector::constructTrackingGeometry (const Config & cfg, const Acts::Logger & logger)
Construct a TrackingGeometry from a Geant4 world volume using the KDTreeTrackingGeometryBuilder builder.
Parameters
cfg the configuration of the Geant4 detector
kdtCfg the configuration of the KDTreeTrackingGeometryBuilder
logger a logger instance
Returns
a tuple of an Acts::TrackingGeometry object, a ContextDecorator & the created detector elements
Definition at line 46 of file Geant4Detector.cpp.
View newest version in sPHENIX GitHub at line 46 of file Geant4Detector.cpp
References ACTS_INFO, cfg, Acts::Logger::clone(), filter::Config, itk::decorators, Acts::CylinderVolumeHelper::Config::layerArrayCreator, logger(), Acts::LayerCreator::Config::surfaceArrayCreator, Acts::KDTreeTrackingGeometryBuilder::Config::surfaces, tContext, and digitization_config::trackingGeometry.
auto ActsExamples::Geant4::Geant4Detector::convertGeant4Volumes (const Config & cfg, const Acts::Logger & logger) const private
Convert Geant4VPhysicalVolume objects into Acts components.
Parameters
cfg the configuration of the Geant4 detector
logger a logger instance
Returns
a tuple of surfaces and detector elements
Definition at line 106 of file Geant4Detector.cpp.
View newest version in sPHENIX GitHub at line 106 of file Geant4Detector.cpp
References ACTS_INFO, cfg, Acts::Geant4DetectorSurfaceFactory::construct(), Acts::Geant4DetectorSurfaceFactory::Cache::convertedMaterials, Acts::UnitConstants::e, Acts::Geant4DetectorSurfaceFactory::Cache::matchedG4Volumes, Acts::Geant4DetectorSurfaceFactory::Cache::passiveSurfaces, physmon_simulation::s, and Acts::Geant4DetectorSurfaceFactory::Cache::sensitiveSurfaces.
The documentation for this struct was generated from the following files:
acts/blob/sPHENIX/Examples/Detectors/Geant4Detector/include/ActsExamples/Geant4Detector/Geant4Detector.hpp
acts/blob/sPHENIX/Examples/Detectors/Geant4Detector/src/Geant4Detector.cpp