Analysis Software: Acts::BoostTrackBuilding Exception Reference
Acts::BoostTrackBuilding Exception Reference final
#include <acts/blob/sPHENIX/Plugins/ExaTrkX/include/Acts/Plugins/ExaTrkX/BoostTrackBuilding.hpp>
Public Member Functions
BoostTrackBuilding (std::unique_ptr< const Logger > logger)
std::vector< std::vector< int > > operator() (std::any nodes, std::any edges, std::any edge_weights, std::vector< int > &spacepointIDs, int deviceHint=-1) override
Public Member Functions inherited from Acts::TrackBuildingBase
virtual ~TrackBuildingBase ()=default
Private Member Functions
const auto & logger () const
Private Attributes
std::unique_ptr< const
Acts::Logger > m_logger
Detailed Description
Definition at line 18 of file BoostTrackBuilding.hpp.
View newest version in sPHENIX GitHub at line 18 of file BoostTrackBuilding.hpp
Constructor & Destructor Documentation
Acts::BoostTrackBuilding::BoostTrackBuilding (std::unique_ptr< const Logger > logger) inline
Definition at line 20 of file BoostTrackBuilding.hpp.
View newest version in sPHENIX GitHub at line 20 of file BoostTrackBuilding.hpp
Member Function Documentation
const auto& Acts::BoostTrackBuilding::logger () const inline private
Definition at line 30 of file BoostTrackBuilding.hpp.
View newest version in sPHENIX GitHub at line 30 of file BoostTrackBuilding.hpp
References m_logger.
std::vector< std::vector< int > > Acts::BoostTrackBuilding::operator() (std::any nodes, std::any edges, std::any edgeWeights, std::vector< int > & spacepointIDs, int deviceHint = -1) override virtual
Perform track building
Parameters
nodes Node tensor with shape (n_nodes, n_node_features)
edges Edge-index tensor with shape (2, n_edges)
edgeWeights Edge-weights of the previous edge classification phase
spacepointIDs IDs of the nodes (must have size=n_nodes)
deviceHint Which GPU to pick. Not relevant for CPU-only builds
Returns
tracks (as vectors of node-IDs)
Implements Acts::TrackBuildingBase.
Definition at line 48 of file BoostTrackBuilding.cpp.
View newest version in sPHENIX GitHub at line 48 of file BoostTrackBuilding.cpp
References ACTS_DEBUG, Acts::ACTS_VERBOSE(), ACTS_WARNING, assert, edges, CKF_timing_vs_mu::label, Acts::Experimental::detail::BlueprintHelper::sort(), and Acts::zip().
Member Data Documentation
std::unique_ptr<const Acts::Logger> Acts::BoostTrackBuilding::m_logger private
Definition at line 29 of file BoostTrackBuilding.hpp.
View newest version in sPHENIX GitHub at line 29 of file BoostTrackBuilding.hpp
Referenced by logger().
The documentation for this exception was generated from the following files:
acts/blob/sPHENIX/Plugins/ExaTrkX/include/Acts/Plugins/ExaTrkX/BoostTrackBuilding.hpp
acts/blob/sPHENIX/Plugins/ExaTrkX/src/BoostTrackBuilding.cpp