Analysis Software: ODBCPreparedStatement Class Reference
ODBCPreparedStatement Class Reference
#include <RDBC/blob/master/odbc/ODBCPreparedStatement.h>
Public Member Functions
virtual ~ODBCPreparedStatement ()
void SetNull (Int_t parameterIndex, Int_t sqlType)
void SetBoolean (Int_t parameterIndex, Bool_t x)
void SetByte (Int_t parameterIndex, Char_t x)
void SetShort (Int_t parameterIndex, Short_t x)
void SetInt (Int_t parameterIndex, Int_t x)
void SetLong (Int_t parameterIndex, Long_t x)
void SetFloat (Int_t parameterIndex, Float_t x)
void SetDouble (Int_t parameterIndex, Double_t x)
void SetString (Int_t parameterIndex, const TString &x)
void SetBytes (Int_t parameterIndex, const TArrayC &x)
void SetDate (Int_t parameterIndex, const TSQLDate &x)
void SetTime (Int_t parameterIndex, const TSQLTime &x)
void SetTimestamp (Int_t parameterIndex, const TSQLTimestamp &x)
void SetAsciiStream (Int_t parameterIndex, TBuffer *x, Int_t length)
void SetBinaryStream (Int_t parameterIndex, TBuffer *x, Int_t length)
void SetObject (Int_t parameterIndex, TObject *x)
void ClearParameters ()
virtual Bool_t Execute (const TString &sql="")
virtual TSQLResultSet * ExecuteQuery (const TString &sql="")
virtual Int_t ExecuteUpdate (const TString &sql="")
TSQLResultSet * GetResultSet ()
Bool_t GetMoreResults ()
void Close ()
void Cancel ()
Int_t GetMaxFieldSize ()
void SetMaxFieldSize (Int_t max)
Int_t GetMaxRows ()
void SetMaxRows (Int_t max)
Bool_t GetEscapeProcessing ()
void SetEscapeProcessing (Bool_t enable=kTRUE)
Int_t GetQueryTimeout ()
void SetQueryTimeout (Int_t seconds)
Int_t GetUpdateCount ()
void SetCursorName (const TString &name)
void AddBatch (const TString &sql)
void ClearBatch ()
Int_t * ExecuteBatch ()
Int_t GetFetchDirection ()
void SetFetchDirection (Int_t direction)
Int_t GetFetchSize ()
void SetFetchSize (Int_t rows)
Int_t GetResultSetConcurrency ()
Int_t GetResultSetType ()
Public Member Functions inherited from TSQLPreparedStatement
virtual ~TSQLPreparedStatement ()
Public Member Functions inherited from TSQLStatement
virtual void Execute (const char *, const char *, int *)
virtual void Execute (TMethod *, TObjArray *, int *)
virtual ~TSQLStatement ()
TSQLConnection * GetConnection () const
Public Member Functions inherited from TSQL
TSQL (void *imp=0)
virtual ~TSQL ()
virtual void Throw (TSQLException *e)
TList * GetWarnings () const
void ClearWarnings ()
virtual Bool_t IsValid () const
Protected Member Functions
ODBCPreparedStatement (TSQLConnection *con, void *imp=0)
Protected Member Functions inherited from TSQLPreparedStatement
TSQLPreparedStatement (TSQLConnection *con, void *imp=0)
Protected Member Functions inherited from TSQLStatement
TSQLStatement (TSQLConnection *con, void *imp=0)
Private Attributes
std::vector< boost::shared_ptr
< std::istream > > _vec_str_buf
Friends
class ODBCConnection
Additional Inherited Members
Static Public Member Functions inherited from TSQL
static Bool_t SetHandler (const TString &handler)
static Bool_t UnsetHandler (const TString &handler="")
Protected Attributes inherited from TSQLStatement
TList * fBatches
TSQLResultSet * fCurrentResult
TSQLConnection * fConnection
Detailed Description
Definition at line 21 of file ODBCPreparedStatement.h.
View newest version in sPHENIX GitHub at line 21 of file ODBCPreparedStatement.h
Constructor & Destructor Documentation
ODBCPreparedStatement::ODBCPreparedStatement (TSQLConnection * con, void * imp = 0) protected
ODBCPreparedStatement::~ODBCPreparedStatement () virtual
Definition at line 89 of file ODBCPreparedStatement.cxx.
View newest version in sPHENIX GitHub at line 89 of file ODBCPreparedStatement.cxx
References Acts::UnitConstants::e, TSQL::fImp, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), ODBCXX_STRING_CSTR, and TSQL::Throw().
Member Function Documentation
void ODBCPreparedStatement::AddBatch (const TString & sql) virtual
Implements TSQLStatement.
Definition at line 1304 of file ODBCPreparedStatement.cxx.
View newest version in sPHENIX GitHub at line 1304 of file ODBCPreparedStatement.cxx
void ODBCPreparedStatement::Cancel () virtual
Implements TSQLStatement.
Definition at line 1070 of file ODBCPreparedStatement.cxx.
View newest version in sPHENIX GitHub at line 1070 of file ODBCPreparedStatement.cxx
References odbc::Statement::cancel(), Acts::UnitConstants::e, TSQL::fImp, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), ODBCXX_STRING_CSTR, and TSQL::Throw().
void ODBCPreparedStatement::ClearBatch () virtual
Implements TSQLStatement.
Definition at line 1319 of file ODBCPreparedStatement.cxx.
View newest version in sPHENIX GitHub at line 1319 of file ODBCPreparedStatement.cxx
void ODBCPreparedStatement::ClearParameters () virtual
Implements TSQLPreparedStatement.
Definition at line 586 of file ODBCPreparedStatement.cxx.
View newest version in sPHENIX GitHub at line 586 of file ODBCPreparedStatement.cxx
References odbc::PreparedStatement::clearParameters(), Acts::UnitConstants::e, TSQL::fImp, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), ODBCXX_STRING_CSTR, and TSQL::Throw().
void ODBCPreparedStatement::Close () virtual
Implements TSQLStatement.
Definition at line 1093 of file ODBCPreparedStatement.cxx.
View newest version in sPHENIX GitHub at line 1093 of file ODBCPreparedStatement.cxx
References Acts::UnitConstants::e, TSQL::fImp, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), ODBCXX_STRING_CSTR, and TSQL::Throw().
Bool_t ODBCPreparedStatement::Execute (const TString & sql = "") virtual
Implements TSQLStatement.
Definition at line 654 of file ODBCPreparedStatement.cxx.
View newest version in sPHENIX GitHub at line 654 of file ODBCPreparedStatement.cxx
References TSQL::ClearWarnings(), Acts::UnitConstants::e, odbc::PreparedStatement::execute(), odbc::Statement::execute(), TSQL::fImp, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), ODBCXX_STRING_C, ODBCXX_STRING_CSTR, and TSQL::Throw().
Int_t * ODBCPreparedStatement::ExecuteBatch () virtual
Implements TSQLStatement.
Definition at line 1331 of file ODBCPreparedStatement.cxx.
View newest version in sPHENIX GitHub at line 1331 of file ODBCPreparedStatement.cxx
TSQLResultSet * ODBCPreparedStatement::ExecuteQuery (const TString & sql = "") virtual
Implements TSQLStatement.
Definition at line 614 of file ODBCPreparedStatement.cxx.
View newest version in sPHENIX GitHub at line 614 of file ODBCPreparedStatement.cxx
References TSQL::ClearWarnings(), Acts::UnitConstants::e, odbc::PreparedStatement::executeQuery(), odbc::Statement::executeQuery(), TSQL::fImp, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), ODBCXX_STRING_C, ODBCXX_STRING_CSTR, and TSQL::Throw().
Int_t ODBCPreparedStatement::ExecuteUpdate (const TString & sql = "") virtual
Implements TSQLStatement.
Definition at line 703 of file ODBCPreparedStatement.cxx.
View newest version in sPHENIX GitHub at line 703 of file ODBCPreparedStatement.cxx
References TSQL::ClearWarnings(), Acts::UnitConstants::e, odbc::PreparedStatement::executeUpdate(), odbc::Statement::executeUpdate(), TSQL::fImp, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), ODBCXX_STRING_C, ODBCXX_STRING_CSTR, and TSQL::Throw().
Bool_t ODBCPreparedStatement::GetEscapeProcessing () virtual
Implements TSQLStatement.
Definition at line 983 of file ODBCPreparedStatement.cxx.
View newest version in sPHENIX GitHub at line 983 of file ODBCPreparedStatement.cxx
References Acts::UnitConstants::e, TSQL::fImp, odbc::SQLException::getErrorCode(), odbc::Statement::getEscapeProcessing(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), ODBCXX_STRING_CSTR, and TSQL::Throw().
Int_t ODBCPreparedStatement::GetFetchDirection () virtual
Implements TSQLStatement.
Definition at line 1183 of file ODBCPreparedStatement.cxx.
View newest version in sPHENIX GitHub at line 1183 of file ODBCPreparedStatement.cxx
Int_t ODBCPreparedStatement::GetFetchSize () virtual
Implements TSQLStatement.
Definition at line 1219 of file ODBCPreparedStatement.cxx.
View newest version in sPHENIX GitHub at line 1219 of file ODBCPreparedStatement.cxx
References Acts::UnitConstants::e, TSQL::fImp, odbc::SQLException::getErrorCode(), odbc::Statement::getFetchSize(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), ODBCXX_STRING_CSTR, and TSQL::Throw().
Int_t ODBCPreparedStatement::GetMaxFieldSize () virtual
Implements TSQLStatement.
Definition at line 843 of file ODBCPreparedStatement.cxx.
View newest version in sPHENIX GitHub at line 843 of file ODBCPreparedStatement.cxx
References Acts::UnitConstants::e, TSQL::fImp, odbc::SQLException::getErrorCode(), odbc::Statement::getMaxFieldSize(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), ODBCXX_STRING_CSTR, and TSQL::Throw().
Int_t ODBCPreparedStatement::GetMaxRows () virtual
Implements TSQLStatement.
Definition at line 902 of file ODBCPreparedStatement.cxx.
View newest version in sPHENIX GitHub at line 902 of file ODBCPreparedStatement.cxx
References Acts::UnitConstants::e, TSQL::fImp, odbc::SQLException::getErrorCode(), odbc::Statement::getMaxRows(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), ODBCXX_STRING_CSTR, and TSQL::Throw().
Bool_t ODBCPreparedStatement::GetMoreResults () virtual
Implements TSQLStatement.
Definition at line 809 of file ODBCPreparedStatement.cxx.
View newest version in sPHENIX GitHub at line 809 of file ODBCPreparedStatement.cxx
References Acts::UnitConstants::e, TSQL::fImp, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::Statement::getMoreResults(), odbc::SQLException::getSQLState(), ODBCXX_STRING_CSTR, and TSQL::Throw().
Int_t ODBCPreparedStatement::GetQueryTimeout () virtual
Implements TSQLStatement.
Definition at line 1016 of file ODBCPreparedStatement.cxx.
View newest version in sPHENIX GitHub at line 1016 of file ODBCPreparedStatement.cxx
References Acts::UnitConstants::e, TSQL::fImp, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::Statement::getQueryTimeout(), odbc::SQLException::getSQLState(), ODBCXX_STRING_CSTR, and TSQL::Throw().
TSQLResultSet * ODBCPreparedStatement::GetResultSet () virtual
Implements TSQLStatement.
Definition at line 742 of file ODBCPreparedStatement.cxx.
View newest version in sPHENIX GitHub at line 742 of file ODBCPreparedStatement.cxx
References Acts::UnitConstants::e, TSQL::fImp, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::Statement::getResultSet(), odbc::SQLException::getSQLState(), ODBCXX_STRING_CSTR, and TSQL::Throw().
Int_t ODBCPreparedStatement::GetResultSetConcurrency () virtual
Implements TSQLStatement.
Definition at line 1250 of file ODBCPreparedStatement.cxx.
View newest version in sPHENIX GitHub at line 1250 of file ODBCPreparedStatement.cxx
References Acts::UnitConstants::e, TSQL::fImp, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::Statement::getResultSetConcurrency(), odbc::SQLException::getSQLState(), ODBCXX_STRING_CSTR, and TSQL::Throw().
Int_t ODBCPreparedStatement::GetResultSetType () virtual
Implements TSQLStatement.
Definition at line 1276 of file ODBCPreparedStatement.cxx.
View newest version in sPHENIX GitHub at line 1276 of file ODBCPreparedStatement.cxx
References Acts::UnitConstants::e, TSQL::fImp, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::Statement::getResultSetType(), odbc::SQLException::getSQLState(), ODBCXX_STRING_CSTR, and TSQL::Throw().
Int_t ODBCPreparedStatement::GetUpdateCount () virtual
Implements TSQLStatement.
Definition at line 778 of file ODBCPreparedStatement.cxx.
View newest version in sPHENIX GitHub at line 778 of file ODBCPreparedStatement.cxx
References Acts::UnitConstants::e, TSQL::fImp, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), odbc::Statement::getUpdateCount(), ODBCXX_STRING_CSTR, and TSQL::Throw().
void ODBCPreparedStatement::SetAsciiStream (Int_t parameterIndex, TBuffer * x, Int_t length) virtual
Implements TSQLPreparedStatement.
Definition at line 484 of file ODBCPreparedStatement.cxx.
View newest version in sPHENIX GitHub at line 484 of file ODBCPreparedStatement.cxx
References Acts::UnitConstants::e, TSQL::fImp, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), ODBCXX_STRING_CSTR, physmon_simulation::s, odbc::PreparedStatement::setAsciiStream(), and TSQL::Throw().
void ODBCPreparedStatement::SetBinaryStream (Int_t parameterIndex, TBuffer * x, Int_t length) virtual
Implements TSQLPreparedStatement.
Definition at line 522 of file ODBCPreparedStatement.cxx.
View newest version in sPHENIX GitHub at line 522 of file ODBCPreparedStatement.cxx
References KFPMath::a, Acts::UnitConstants::e, TSQL::fImp, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), ODBCXX_STRING_CSTR, physmon_simulation::s, odbc::PreparedStatement::setBinaryStream(), and TSQL::Throw().
void ODBCPreparedStatement::SetBoolean (Int_t parameterIndex, Bool_t x) virtual
Implements TSQLPreparedStatement.
Definition at line 136 of file ODBCPreparedStatement.cxx.
View newest version in sPHENIX GitHub at line 136 of file ODBCPreparedStatement.cxx
References Acts::UnitConstants::e, TSQL::fImp, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), ODBCXX_STRING_CSTR, odbc::PreparedStatement::setBoolean(), and TSQL::Throw().
void ODBCPreparedStatement::SetByte (Int_t parameterIndex, Char_t x) virtual
Implements TSQLPreparedStatement.
Definition at line 163 of file ODBCPreparedStatement.cxx.
View newest version in sPHENIX GitHub at line 163 of file ODBCPreparedStatement.cxx
References Acts::UnitConstants::e, TSQL::fImp, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), ODBCXX_STRING_CSTR, odbc::PreparedStatement::setByte(), and TSQL::Throw().
void ODBCPreparedStatement::SetBytes (Int_t parameterIndex, const TArrayC & x) virtual
Implements TSQLPreparedStatement.
Definition at line 354 of file ODBCPreparedStatement.cxx.
View newest version in sPHENIX GitHub at line 354 of file ODBCPreparedStatement.cxx
References Acts::UnitConstants::e, TSQL::fImp, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), ODBCXX_BYTES_C, ODBCXX_STRING_CSTR, odbc::PreparedStatement::setBytes(), and TSQL::Throw().
void ODBCPreparedStatement::SetCursorName (const TString & name) virtual
Implements TSQLStatement.
Definition at line 1125 of file ODBCPreparedStatement.cxx.
View newest version in sPHENIX GitHub at line 1125 of file ODBCPreparedStatement.cxx
References Acts::UnitConstants::e, TSQL::fImp, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), ODBCXX_STRING_C, ODBCXX_STRING_CSTR, odbc::Statement::setCursorName(), and TSQL::Throw().
void ODBCPreparedStatement::SetDate (Int_t parameterIndex, const TSQLDate & x) virtual
Implements TSQLPreparedStatement.
Definition at line 384 of file ODBCPreparedStatement.cxx.
View newest version in sPHENIX GitHub at line 384 of file ODBCPreparedStatement.cxx
References Acts::UnitConstants::e, TSQL::fImp, TSQLDate::GetDay(), odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), TSQLDate::GetMonth(), odbc::SQLException::getSQLState(), TSQLDate::GetYear(), ODBCXX_STRING_CSTR, odbc::PreparedStatement::setDate(), and TSQL::Throw().
void ODBCPreparedStatement::SetDouble (Int_t parameterIndex, Double_t x) virtual
Implements TSQLPreparedStatement.
Definition at line 298 of file ODBCPreparedStatement.cxx.
View newest version in sPHENIX GitHub at line 298 of file ODBCPreparedStatement.cxx
References Acts::UnitConstants::e, TSQL::fImp, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), ODBCXX_STRING_CSTR, odbc::PreparedStatement::setDouble(), and TSQL::Throw().
void ODBCPreparedStatement::SetEscapeProcessing (Bool_t enable = kTRUE) virtual
Implements TSQLStatement.
Definition at line 954 of file ODBCPreparedStatement.cxx.
View newest version in sPHENIX GitHub at line 954 of file ODBCPreparedStatement.cxx
References Acts::UnitConstants::e, TSQL::fImp, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), ODBCXX_STRING_CSTR, odbc::Statement::setEscapeProcessing(), and TSQL::Throw().
void ODBCPreparedStatement::SetFetchDirection (Int_t direction) virtual
Implements TSQLStatement.
Definition at line 1162 of file ODBCPreparedStatement.cxx.
View newest version in sPHENIX GitHub at line 1162 of file ODBCPreparedStatement.cxx
References TSQL::fImp.
void ODBCPreparedStatement::SetFetchSize (Int_t rows) virtual
Implements TSQLStatement.
Definition at line 1201 of file ODBCPreparedStatement.cxx.
View newest version in sPHENIX GitHub at line 1201 of file ODBCPreparedStatement.cxx
References TSQL::fImp.
void ODBCPreparedStatement::SetFloat (Int_t parameterIndex, Float_t x) virtual
Implements TSQLPreparedStatement.
Definition at line 271 of file ODBCPreparedStatement.cxx.
View newest version in sPHENIX GitHub at line 271 of file ODBCPreparedStatement.cxx
References Acts::UnitConstants::e, TSQL::fImp, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), ODBCXX_STRING_CSTR, odbc::PreparedStatement::setFloat(), and TSQL::Throw().
void ODBCPreparedStatement::SetInt (Int_t parameterIndex, Int_t x) virtual
Implements TSQLPreparedStatement.
Definition at line 217 of file ODBCPreparedStatement.cxx.
View newest version in sPHENIX GitHub at line 217 of file ODBCPreparedStatement.cxx
References Acts::UnitConstants::e, TSQL::fImp, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), ODBCXX_STRING_CSTR, odbc::PreparedStatement::setInt(), and TSQL::Throw().
void ODBCPreparedStatement::SetLong (Int_t parameterIndex, Long_t x) virtual
Implements TSQLPreparedStatement.
Definition at line 244 of file ODBCPreparedStatement.cxx.
View newest version in sPHENIX GitHub at line 244 of file ODBCPreparedStatement.cxx
References Acts::UnitConstants::e, TSQL::fImp, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), ODBCXX_STRING_CSTR, odbc::PreparedStatement::setLong(), and TSQL::Throw().
void ODBCPreparedStatement::SetMaxFieldSize (Int_t max) virtual
Implements TSQLStatement.
Definition at line 874 of file ODBCPreparedStatement.cxx.
View newest version in sPHENIX GitHub at line 874 of file ODBCPreparedStatement.cxx
References Acts::UnitConstants::e, TSQL::fImp, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), ODBCXX_STRING_CSTR, odbc::Statement::setMaxFieldSize(), and TSQL::Throw().
void ODBCPreparedStatement::SetMaxRows (Int_t max) virtual
Implements TSQLStatement.
Definition at line 930 of file ODBCPreparedStatement.cxx.
View newest version in sPHENIX GitHub at line 930 of file ODBCPreparedStatement.cxx
References Acts::UnitConstants::e, TSQL::fImp, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), ODBCXX_STRING_CSTR, odbc::Statement::setMaxRows(), and TSQL::Throw().
void ODBCPreparedStatement::SetNull (Int_t parameterIndex, Int_t sqlType) virtual
Implements TSQLPreparedStatement.
Definition at line 109 of file ODBCPreparedStatement.cxx.
View newest version in sPHENIX GitHub at line 109 of file ODBCPreparedStatement.cxx
References Acts::UnitConstants::e, TSQL::fImp, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), ODBCXX_STRING_CSTR, odbc::PreparedStatement::setNull(), and TSQL::Throw().
void ODBCPreparedStatement::SetObject (Int_t parameterIndex, TObject * x) virtual
Implements TSQLPreparedStatement.
Definition at line 563 of file ODBCPreparedStatement.cxx.
View newest version in sPHENIX GitHub at line 563 of file ODBCPreparedStatement.cxx
References KFPMath::b.
void ODBCPreparedStatement::SetQueryTimeout (Int_t seconds) virtual
Implements TSQLStatement.
Definition at line 1045 of file ODBCPreparedStatement.cxx.
View newest version in sPHENIX GitHub at line 1045 of file ODBCPreparedStatement.cxx
References Acts::UnitConstants::e, TSQL::fImp, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), ODBCXX_STRING_CSTR, odbc::Statement::setQueryTimeout(), and TSQL::Throw().
void ODBCPreparedStatement::SetShort (Int_t parameterIndex, Short_t x) virtual
Implements TSQLPreparedStatement.
Definition at line 190 of file ODBCPreparedStatement.cxx.
View newest version in sPHENIX GitHub at line 190 of file ODBCPreparedStatement.cxx
References Acts::UnitConstants::e, TSQL::fImp, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), ODBCXX_STRING_CSTR, odbc::PreparedStatement::setShort(), and TSQL::Throw().
void ODBCPreparedStatement::SetString (Int_t parameterIndex, const TString & x) virtual
Implements TSQLPreparedStatement.
Definition at line 325 of file ODBCPreparedStatement.cxx.
View newest version in sPHENIX GitHub at line 325 of file ODBCPreparedStatement.cxx
References Acts::UnitConstants::e, TSQL::fImp, odbc::SQLException::getErrorCode(), odbc::SQLException::getMessage(), odbc::SQLException::getSQLState(), ODBCXX_STRING_C, ODBCXX_STRING_CSTR, odbc::PreparedStatement::setString(), and TSQL::Throw().
void ODBCPreparedStatement::SetTime (Int_t parameterIndex, const TSQLTime & x) virtual
Implements TSQLPreparedStatement.
Definition at line 416 of file ODBCPreparedStatement.cxx.
View newest version in sPHENIX GitHub at line 416 of file ODBCPreparedStatement.cxx
References Acts::UnitConstants::e, TSQL::fImp, odbc::SQLException::getErrorCode(), TSQLTime::GetHour(), odbc::SQLException::getMessage(), TSQLTime::GetMinute(), TSQLTime::GetSecond(), odbc::SQLException::getSQLState(), ODBCXX_STRING_CSTR, odbc::PreparedStatement::setTime(), and TSQL::Throw().
void ODBCPreparedStatement::SetTimestamp (Int_t parameterIndex, const TSQLTimestamp & x) virtual
Implements TSQLPreparedStatement.
Definition at line 448 of file ODBCPreparedStatement.cxx.
View newest version in sPHENIX GitHub at line 448 of file ODBCPreparedStatement.cxx
References Acts::UnitConstants::e, TSQL::fImp, TSQLTimestamp::GetDay(), odbc::SQLException::getErrorCode(), TSQLTimestamp::GetHour(), odbc::SQLException::getMessage(), TSQLTimestamp::GetMinute(), TSQLTimestamp::GetMonth(), TSQLTimestamp::GetNanos(), TSQLTimestamp::GetSecond(), odbc::SQLException::getSQLState(), TSQLTimestamp::GetYear(), ODBCXX_STRING_CSTR, odbc::PreparedStatement::setTimestamp(), and TSQL::Throw().
Friends And Related Function Documentation
friend class ODBCConnection friend
Definition at line 23 of file ODBCPreparedStatement.h.
View newest version in sPHENIX GitHub at line 23 of file ODBCPreparedStatement.h
Member Data Documentation
std::vector< boost::shared_ptr<std::istream> > ODBCPreparedStatement::_vec_str_buf private
Definition at line 81 of file ODBCPreparedStatement.h.
View newest version in sPHENIX GitHub at line 81 of file ODBCPreparedStatement.h
The documentation for this class was generated from the following files:
RDBC/blob/master/odbc/ODBCPreparedStatement.h
RDBC/blob/master/odbc/ODBCPreparedStatement.cxx