Analysis Software: PHActsTrackPropagator Class Reference
PHActsTrackPropagator Class Reference
#include <coresoftware/blob/master/offline/packages/trackreco/PHActsTrackPropagator.h>
Public Types
using BoundTrackParam = const Acts::BoundTrackParameters
using BoundTrackParamResult = ActsPropagator::BTPPairResult
using SurfacePtr = std::shared_ptr< const Acts::Surface >
using Trajectory = ActsExamples::Trajectories
Public Member Functions
PHActsTrackPropagator (const std::string &name="PHActsTrackPropagator")
~PHActsTrackPropagator () override
int Init (PHCompositeNode *topNode) override
int InitRun (PHCompositeNode *topNode) override
int process_event (PHCompositeNode *topNode) override
int End (PHCompositeNode *topNode) override
Called at the end of all processing.
void Print (const std::string &what="ALL") const override
void setPropagationLayer (unsigned int layer)
Public Member Functions inherited from SubsysReco
~SubsysReco () override
virtual int EndRun (const int)
Called at the end of each run.
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Private Member Functions
int getNodes (PHCompositeNode *topNode)
BoundTrackParamResult propagateTrack (const Acts::BoundTrackParameters &params)
void convertsPHENIXLayerToActsLayer (unsigned int &actsvolume, unsigned int &actslayer)
void addTrackState (BoundTrackParamResult &params, SvtxTrack *svtxTrack)
Private Attributes
ActsGeometry * m_tGeometry = nullptr
Objects containing the Acts track fit results.
SvtxTrackMap * m_trackMap = nullptr
SvtxVertexMap * m_vertexMap = nullptr
unsigned int m_sphenixLayer = std::numeric_limits<unsigned int>::max()
Additional Inherited Members
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Detailed Description
Definition at line 27 of file PHActsTrackPropagator.h.
View newest version in sPHENIX GitHub at line 27 of file PHActsTrackPropagator.h
Member Typedef Documentation
using PHActsTrackPropagator::BoundTrackParam = const Acts::BoundTrackParameters
Definition at line 31 of file PHActsTrackPropagator.h.
View newest version in sPHENIX GitHub at line 31 of file PHActsTrackPropagator.h
using PHActsTrackPropagator::BoundTrackParamResult = ActsPropagator::BTPPairResult
Definition at line 32 of file PHActsTrackPropagator.h.
View newest version in sPHENIX GitHub at line 32 of file PHActsTrackPropagator.h
using PHActsTrackPropagator::SurfacePtr = std::shared_ptr<const Acts::Surface>
Definition at line 33 of file PHActsTrackPropagator.h.
View newest version in sPHENIX GitHub at line 33 of file PHActsTrackPropagator.h
using PHActsTrackPropagator::Trajectory = ActsExamples::Trajectories
Definition at line 34 of file PHActsTrackPropagator.h.
View newest version in sPHENIX GitHub at line 34 of file PHActsTrackPropagator.h
Constructor & Destructor Documentation
PHActsTrackPropagator::PHActsTrackPropagator (const std::string & name = "PHActsTrackPropagator")
Definition at line 30 of file PHActsTrackPropagator.cc.
View newest version in sPHENIX GitHub at line 30 of file PHActsTrackPropagator.cc
PHActsTrackPropagator::~PHActsTrackPropagator () override
Definition at line 36 of file PHActsTrackPropagator.cc.
View newest version in sPHENIX GitHub at line 36 of file PHActsTrackPropagator.cc
Member Function Documentation
void PHActsTrackPropagator::addTrackState (BoundTrackParamResult & params, SvtxTrack * svtxTrack) private
Definition at line 75 of file PHActsTrackPropagator.cc.
View newest version in sPHENIX GitHub at line 75 of file PHActsTrackPropagator.cc
References Acts::UnitConstants::cm, ActsGeometry::geometry(), ActsTrackingGeometry::getGeoContext(), i, SvtxTrack::insert_state(), j, m_sphenixLayer, m_tGeometry, momentum, out, ActsTransformations::rotateActsCovToSvtxTrack(), SvtxTrackState_v1::set_error(), SvtxTrackState_v1::set_px(), SvtxTrackState_v1::set_py(), SvtxTrackState_v1::set_pz(), SvtxTrackState_v1::set_x(), SvtxTrackState_v1::set_y(), SvtxTrackState_v1::set_z(), and Fun4AllBase::Verbosity().
Referenced by process_event().
void PHActsTrackPropagator::convertsPHENIXLayerToActsLayer (unsigned int & actsvolume, unsigned int & actslayer) private
int PHActsTrackPropagator::End (PHCompositeNode *) override virtual
Called at the end of all processing.
Reimplemented from SubsysReco.
Definition at line 123 of file PHActsTrackPropagator.cc.
View newest version in sPHENIX GitHub at line 123 of file PHActsTrackPropagator.cc
References Fun4AllReturnCodes::EVENT_OK.
int PHActsTrackPropagator::getNodes (PHCompositeNode * topNode) private
Definition at line 134 of file PHActsTrackPropagator.cc.
View newest version in sPHENIX GitHub at line 134 of file PHActsTrackPropagator.cc
References Fun4AllReturnCodes::ABORTEVENT, Fun4AllReturnCodes::EVENT_OK, m_tGeometry, m_trackMap, m_vertexMap, and PHWHERE.
Referenced by InitRun().
int PHActsTrackPropagator::Init (PHCompositeNode *) override virtual
Called during initialization. Typically this is where you can book histograms, and e.g. register them to Fun4AllServer (so they can be output to file using Fun4AllServer::dumpHistos() method).
Reimplemented from SubsysReco.
Definition at line 41 of file PHActsTrackPropagator.cc.
View newest version in sPHENIX GitHub at line 41 of file PHActsTrackPropagator.cc
References Fun4AllReturnCodes::EVENT_OK.
int PHActsTrackPropagator::InitRun (PHCompositeNode *) override virtual
Called for first event when run number is known. Typically this is where you may want to fetch data from database, because you know the run number.
Reimplemented from SubsysReco.
Definition at line 47 of file PHActsTrackPropagator.cc.
View newest version in sPHENIX GitHub at line 47 of file PHActsTrackPropagator.cc
References getNodes().
void PHActsTrackPropagator::Print (const std::string & what = "ALL") const override virtual
Print out some info about this module.
Parameters
what can be used to specify what to print exactly.
Reimplemented from SubsysReco.
Definition at line 129 of file PHActsTrackPropagator.cc.
View newest version in sPHENIX GitHub at line 129 of file PHActsTrackPropagator.cc
int PHActsTrackPropagator::process_event (PHCompositeNode *) override virtual
Called for each event. This is where you do the real work.
Reimplemented from SubsysReco.
Definition at line 55 of file PHActsTrackPropagator.cc.
View newest version in sPHENIX GitHub at line 55 of file PHActsTrackPropagator.cc
References addTrackState(), Fun4AllReturnCodes::EVENT_OK, m_tGeometry, m_trackMap, m_vertexMap, ActsPropagator::makeTrackParams(), and propagateTrack().
PHActsTrackPropagator::BoundTrackParamResult PHActsTrackPropagator::propagateTrack (const Acts::BoundTrackParameters & params) private
Definition at line 114 of file PHActsTrackPropagator.cc.
View newest version in sPHENIX GitHub at line 114 of file PHActsTrackPropagator.cc
References m_sphenixLayer, m_tGeometry, ActsPropagator::propagateTrack(), Fun4AllBase::Verbosity(), and ActsPropagator::verbosity().
Referenced by process_event().
void PHActsTrackPropagator::setPropagationLayer (unsigned int layer) inline
Definition at line 48 of file PHActsTrackPropagator.h.
View newest version in sPHENIX GitHub at line 48 of file PHActsTrackPropagator.h
References layer, and m_sphenixLayer.
Member Data Documentation
unsigned int PHActsTrackPropagator::m_sphenixLayer = std::numeric_limits<unsigned int>::max() private
Definition at line 64 of file PHActsTrackPropagator.h.
View newest version in sPHENIX GitHub at line 64 of file PHActsTrackPropagator.h
Referenced by addTrackState(), propagateTrack(), and setPropagationLayer().
ActsGeometry* PHActsTrackPropagator::m_tGeometry = nullptr private
Objects containing the Acts track fit results.
Definition at line 60 of file PHActsTrackPropagator.h.
View newest version in sPHENIX GitHub at line 60 of file PHActsTrackPropagator.h
Referenced by addTrackState(), getNodes(), process_event(), and propagateTrack().
SvtxTrackMap* PHActsTrackPropagator::m_trackMap = nullptr private
Definition at line 61 of file PHActsTrackPropagator.h.
View newest version in sPHENIX GitHub at line 61 of file PHActsTrackPropagator.h
Referenced by getNodes(), and process_event().
SvtxVertexMap* PHActsTrackPropagator::m_vertexMap = nullptr private
Definition at line 62 of file PHActsTrackPropagator.h.
View newest version in sPHENIX GitHub at line 62 of file PHActsTrackPropagator.h
Referenced by getNodes(), and process_event().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/trackreco/PHActsTrackPropagator.h
coresoftware/blob/master/offline/packages/trackreco/PHActsTrackPropagator.cc