Analysis Software: macros/blob/master/common/G4_Pipe.C File Reference
G4_Pipe.C File Reference
#include <GlobalVariables.C>
#include <g4detectors/PHG4ConeSubsystem.h>
#include <g4detectors/PHG4CylinderSubsystem.h>
#include <g4main/PHG4Reco.h>
Namespaces
namespace Enable
namespace G4PIPE
Macros
#define MACRO_G4PIPE_C
Functions
void PipeInit ()
double Pipe (PHG4Reco *g4Reco, double radius)
Variables
bool Enable::PIPE = false
bool Enable::PIPE_ABSORBER = false
bool Enable::PIPE_OVERLAPCHECK = false
int Enable::PIPE_VERBOSITY = 0
double G4PIPE::be_pipe_radius = 2.00025
double G4PIPE::be_pipe_thickness = 0.0762
double G4PIPE::be_pipe_length = 120.015
double G4PIPE::be_pipe_zshift = -41.1639
double G4PIPE::al_pipe_radius = 2.00025
double G4PIPE::al_pipe_thickness = 0.1397
double G4PIPE::al_pipe_south_length = 101.486
double G4PIPE::al_pipe_north_length = 61.51
double G4PIPE::al_pipe_north_ext_length = 123.393
double G4PIPE::flange_thickness = 6.934/2 - (al_pipe_radius + al_pipe_thickness)
double G4PIPE::flange_length = 1.2825
double G4PIPE::outer_pipe_precone_length = 22.86
double G4PIPE::outer_pipe_precone_radius = 2.00025
double G4PIPE::outer_pipe_thickness = 0.1397
double G4PIPE::outer_pipe_cone_length = 38.1
double G4PIPE::outer_pipe_ext_radius = 3.81
double G4PIPE::outer_pipe_ext_length = 100.
double G4PIPE::max_z
Macro Definition Documentation
#define MACRO_G4PIPE_C
Definition at line 2 of file G4_Pipe.C.
View newest version in sPHENIX GitHub at line 2 of file G4_Pipe.C
Function Documentation
double Pipe (PHG4Reco * g4Reco, double radius)
Definition at line 59 of file G4_Pipe.C.
View newest version in sPHENIX GitHub at line 59 of file G4_Pipe.C
References Enable::ABSORBER, G4PIPE::al_pipe_north_ext_length, G4PIPE::al_pipe_north_length, G4PIPE::al_pipe_radius, G4PIPE::al_pipe_south_length, G4PIPE::al_pipe_thickness, G4PIPE::be_pipe_length, G4PIPE::be_pipe_radius, G4PIPE::be_pipe_thickness, G4PIPE::be_pipe_zshift, G4PIPE::flange_length, G4PIPE::flange_thickness, no_overlapp, G4PIPE::outer_pipe_cone_length, G4PIPE::outer_pipe_ext_length, G4PIPE::outer_pipe_ext_radius, G4PIPE::outer_pipe_precone_length, G4PIPE::outer_pipe_precone_radius, G4PIPE::outer_pipe_thickness, PHG4DetectorSubsystem::OverlapCheck(), Enable::OVERLAPCHECK, Enable::PIPE_ABSORBER, Enable::PIPE_OVERLAPCHECK, Enable::PIPE_VERBOSITY, PHG4Reco::registerSubsystem(), PHG4DetectorSubsystem::set_double_param(), PHG4DetectorSubsystem::set_int_param(), PHG4DetectorSubsystem::set_string_param(), PHG4DetectorSubsystem::SetActive(), PHG4ConeSubsystem::SetMaterial(), PHG4ConeSubsystem::SetPlaceZ(), PHG4ConeSubsystem::SetR1(), PHG4ConeSubsystem::SetR2(), PHG4ConeSubsystem::SetZlength(), PHG4DetectorSubsystem::SuperDetector(), verbosity, and Enable::VERBOSITY.
void PipeInit ()
Definition at line 52 of file G4_Pipe.C.
View newest version in sPHENIX GitHub at line 52 of file G4_Pipe.C
References BlackHoleGeometry::max_radius, G4PIPE::max_z, BlackHoleGeometry::max_z, Acts::UnitConstants::min, BlackHoleGeometry::min_z, no_overlapp, G4PIPE::outer_pipe_ext_radius, and G4PIPE::outer_pipe_thickness.