Analysis Software: HybridHadronization::HHhadron Class Reference
HybridHadronization::HHhadron Class Reference
Public Member Functions
HHhadron ()
int par (int i)
void add_par (int i)
int col (int i)
void add_col (int i)
double x ()
double y ()
double z ()
double x_t ()
double px ()
double py ()
double pz ()
double e ()
bool is_excited ()
bool is_shsh ()
bool is_shth ()
bool is_thth ()
bool is_recohad ()
bool is_strhad ()
bool is_final ()
int orig ()
int parstr ()
int parh ()
double mass ()
FourVector pos ()
FourVector P ()
int id ()
int status ()
void x (double val)
void y (double val)
void z (double val)
void x_t (double val)
void pos (FourVector val)
void px (double val)
void py (double val)
void pz (double val)
void e (double val)
void P (FourVector val)
void is_excited (bool val)
void is_shsh (bool val)
void is_shth (bool val)
void is_thth (bool val)
void is_recohad (bool val)
void is_strhad (bool val)
void is_final (bool val)
void orig (int val)
void parstr (int val)
void parh (int val)
void mass (double val)
void id (int val)
void status (int val)
FourVector boost_P (FourVector B)
FourVector boost_P (double vx, double vy, double vz)
FourVector boost_pos (FourVector B)
FourVector boost_pos (double vx, double vy, double vz)
Public Member Functions inherited from Jetscape::Hadron
Hadron (int label, int id, int stat, const FourVector &p, const FourVector &x)
Hadron (int label, int id, int stat, double pt, double eta, double phi, double e, double *x=0)
Hadron (int label, int id, int stat, const FourVector &p, const FourVector &x, double mass)
Hadron (const Hadron &srh)
Hadron & operator= (Hadron &c)
Hadron & operator= (const Hadron &c)
void set_decay_width (double width)
double decay_width ()
bool CheckOrForceHadron (const int id, const double mass=0)
bool has_no_position ()
Returns true when all x entries of the hadrons are (close to) 0.
Public Member Functions inherited from Jetscape::JetScapeParticleBase
void reset_momentum (const double px, const double py, const double pz, const double e)
void reset_momentum (const FourVector &p)
fjcore::PseudoJet GetPseudoJet () const
No implicit cast to PseudoJet is allowed, provide a conversion.
JetScapeParticleBase ()
JetScapeParticleBase (int label, int id, int stat, const FourVector &p, const FourVector &x)
JetScapeParticleBase (int label, int id, int stat, double pt, double eta, double phi, double e, double *x=0)
JetScapeParticleBase (int label, int id, int stat, const FourVector &p, const FourVector &x, double mass)
JetScapeParticleBase (const JetScapeParticleBase &srp)
virtual ~JetScapeParticleBase ()
void clear ()
void set_label (int label)
void set_id (int id)
void set_stat (int stat)
void set_x (double x[4])
void init_jet_v ()
void set_jet_v (double v[4])
void set_jet_v (FourVector j)
bool SetController (string controller="")
void UnsetController ()
const int pid () const
const int pstat () const
const int plabel () const
const double time () const
std::vector< JetScapeParticleBase > parents ()
const FourVector p_in () const
const FourVector & x_in () const
const FourVector & jet_v () const
const double restmass ()
const double p (int i)
double pl ()
const double nu ()
const double t_max ()
virtual JetScapeParticleBase & operator= (JetScapeParticleBase &c)
virtual JetScapeParticleBase & operator= (const JetScapeParticleBase &c)
string GetController () const
bool GetControlled () const
Public Attributes
std::vector< int > parents
std::vector< int > cols
Protected Attributes
bool is_excited_
bool is_shsh_
bool is_shth_
bool is_thth_
bool is_recohad_
bool is_strhad_
bool is_final_
int orig_
int parstr_
int parh_
double alt_mass_
Protected Attributes inherited from Jetscape::Hadron
double width_
Protected Attributes inherited from Jetscape::JetScapeParticleBase
int pid_
particle id
int pstat_
status of particle
int plabel_
the line number in the event record
double mass_
rest mass of the particle
FourVector x_in_
position of particle
FourVector jet_v_
jet four vector, without gamma factor (so not really a four vector)
bool controlled_ = false
check whether a module claimed responsibility of this particle
string controller_ = ""
Additional Inherited Members
Static Public Attributes inherited from Jetscape::JetScapeParticleBase
static Pythia8::Pythia InternalHelperPythia
Protected Member Functions inherited from Jetscape::JetScapeParticleBase
void set_restmass (double mass_input)
shouldn't be called from the outside, needs to be consistent with PID
Detailed Description
Definition at line 185 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 185 of file HybridHadronization.h
Constructor & Destructor Documentation
HybridHadronization::HHhadron::HHhadron () inline
Definition at line 198 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 198 of file HybridHadronization.h
Member Function Documentation
void HybridHadronization::HHhadron::add_col (int i) inline
Definition at line 215 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 215 of file HybridHadronization.h
Referenced by HybridHadronization::recomb().
void HybridHadronization::HHhadron::add_par (int i) inline
Definition at line 208 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 208 of file HybridHadronization.h
Referenced by HybridHadronization::recomb(), and HybridHadronization::set_spacetime_for_pythia_hadrons().
FourVector HybridHadronization::HHhadron::boost_P (FourVector B) inline
Definition at line 247 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 247 of file HybridHadronization.h
FourVector HybridHadronization::HHhadron::boost_P (double vx, double vy, double vz) inline
Definition at line 248 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 248 of file HybridHadronization.h
FourVector HybridHadronization::HHhadron::boost_pos (FourVector B) inline
Definition at line 249 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 249 of file HybridHadronization.h
FourVector HybridHadronization::HHhadron::boost_pos (double vx, double vy, double vz) inline
Definition at line 250 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 250 of file HybridHadronization.h
int HybridHadronization::HHhadron::col (int i) inline
Definition at line 214 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 214 of file HybridHadronization.h
References i.
Referenced by item.Item::__eq__(), and item.Item::__hash__().
double HybridHadronization::HHhadron::e () inline
Definition at line 219 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 219 of file HybridHadronization.h
Referenced by HybridHadronization::set_spacetime_for_pythia_hadrons().
void HybridHadronization::HHhadron::e (double val) inline
Definition at line 237 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 237 of file HybridHadronization.h
int HybridHadronization::HHhadron::id () inline
Definition at line 226 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 226 of file HybridHadronization.h
Referenced by HybridHadronization::DoHadronization(), HybridHadronization::set_baryon_id(), HybridHadronization::set_meson_id(), HybridHadronization::set_spacetime_for_pythia_hadrons(), and HybridHadronization::stringprep().
void HybridHadronization::HHhadron::id (int val) inline
Definition at line 244 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 244 of file HybridHadronization.h
bool HybridHadronization::HHhadron::is_excited () inline
Definition at line 220 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 220 of file HybridHadronization.h
Referenced by HybridHadronization::recomb().
void HybridHadronization::HHhadron::is_excited (bool val) inline
Definition at line 240 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 240 of file HybridHadronization.h
bool HybridHadronization::HHhadron::is_final () inline
Definition at line 221 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 221 of file HybridHadronization.h
Referenced by HybridHadronization::set_spacetime_for_pythia_hadrons().
void HybridHadronization::HHhadron::is_final (bool val) inline
Definition at line 241 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 241 of file HybridHadronization.h
bool HybridHadronization::HHhadron::is_recohad () inline
Definition at line 221 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 221 of file HybridHadronization.h
Referenced by HybridHadronization::recomb(), HybridHadronization::set_spacetime_for_pythia_hadrons(), and HybridHadronization::stringprep().
void HybridHadronization::HHhadron::is_recohad (bool val) inline
Definition at line 241 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 241 of file HybridHadronization.h
bool HybridHadronization::HHhadron::is_shsh () inline
Definition at line 220 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 220 of file HybridHadronization.h
Referenced by HybridHadronization::recomb(), and HybridHadronization::set_spacetime_for_pythia_hadrons().
void HybridHadronization::HHhadron::is_shsh (bool val) inline
Definition at line 240 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 240 of file HybridHadronization.h
bool HybridHadronization::HHhadron::is_shth () inline
Definition at line 220 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 220 of file HybridHadronization.h
Referenced by HybridHadronization::recomb(), HybridHadronization::set_spacetime_for_pythia_hadrons(), and HybridHadronization::stringprep().
void HybridHadronization::HHhadron::is_shth (bool val) inline
Definition at line 240 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 240 of file HybridHadronization.h
bool HybridHadronization::HHhadron::is_strhad () inline
Definition at line 221 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 221 of file HybridHadronization.h
Referenced by HybridHadronization::set_spacetime_for_pythia_hadrons().
void HybridHadronization::HHhadron::is_strhad (bool val) inline
Definition at line 241 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 241 of file HybridHadronization.h
bool HybridHadronization::HHhadron::is_thth () inline
Definition at line 220 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 220 of file HybridHadronization.h
void HybridHadronization::HHhadron::is_thth (bool val) inline
Definition at line 240 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 240 of file HybridHadronization.h
double HybridHadronization::HHhadron::mass () inline
Definition at line 223 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 223 of file HybridHadronization.h
Referenced by HybridHadronization::DoHadronization(), HybridHadronization::recomb(), HybridHadronization::set_spacetime_for_pythia_hadrons(), and HybridHadronization::stringprep().
void HybridHadronization::HHhadron::mass (double val) inline
Definition at line 243 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 243 of file HybridHadronization.h
int HybridHadronization::HHhadron::orig () inline
Definition at line 222 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 222 of file HybridHadronization.h
Referenced by HybridHadronization::DoHadronization().
void HybridHadronization::HHhadron::orig (int val) inline
Definition at line 242 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 242 of file HybridHadronization.h
FourVector HybridHadronization::HHhadron::P () inline
Definition at line 225 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 225 of file HybridHadronization.h
Referenced by HybridHadronization::DoHadronization(), HybridHadronization::recomb(), and HybridHadronization::stringprep().
void HybridHadronization::HHhadron::P (FourVector val) inline
Definition at line 238 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 238 of file HybridHadronization.h
int HybridHadronization::HHhadron::par (int i) inline
Definition at line 207 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 207 of file HybridHadronization.h
References i.
int HybridHadronization::HHhadron::parh () inline
Definition at line 222 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 222 of file HybridHadronization.h
Referenced by HybridHadronization::set_spacetime_for_pythia_hadrons().
void HybridHadronization::HHhadron::parh (int val) inline
Definition at line 242 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 242 of file HybridHadronization.h
int HybridHadronization::HHhadron::parstr () inline
Definition at line 222 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 222 of file HybridHadronization.h
void HybridHadronization::HHhadron::parstr (int val) inline
Definition at line 242 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 242 of file HybridHadronization.h
FourVector HybridHadronization::HHhadron::pos () inline
Definition at line 224 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 224 of file HybridHadronization.h
Referenced by HybridHadronization::DoHadronization(), HybridHadronization::recomb(), and HybridHadronization::stringprep().
void HybridHadronization::HHhadron::pos (FourVector val) inline
Definition at line 233 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 233 of file HybridHadronization.h
References Jetscape::FourVector::t(), Jetscape::FourVector::x(), Jetscape::FourVector::y(), and Jetscape::FourVector::z().
double HybridHadronization::HHhadron::px () inline
Definition at line 219 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 219 of file HybridHadronization.h
Referenced by HybridHadronization::set_spacetime_for_pythia_hadrons().
void HybridHadronization::HHhadron::px (double val) inline
Definition at line 234 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 234 of file HybridHadronization.h
References Acts::UnitConstants::e.
double HybridHadronization::HHhadron::py () inline
Definition at line 219 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 219 of file HybridHadronization.h
Referenced by HybridHadronization::set_spacetime_for_pythia_hadrons().
void HybridHadronization::HHhadron::py (double val) inline
Definition at line 235 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 235 of file HybridHadronization.h
References Acts::UnitConstants::e.
double HybridHadronization::HHhadron::pz () inline
Definition at line 219 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 219 of file HybridHadronization.h
Referenced by HybridHadronization::set_spacetime_for_pythia_hadrons().
void HybridHadronization::HHhadron::pz (double val) inline
Definition at line 236 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 236 of file HybridHadronization.h
References Acts::UnitConstants::e.
int HybridHadronization::HHhadron::status () inline
Definition at line 226 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 226 of file HybridHadronization.h
References train_ambiguity_solver::pid.
void HybridHadronization::HHhadron::status (int val) inline
Definition at line 244 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 244 of file HybridHadronization.h
double HybridHadronization::HHhadron::x () inline
Definition at line 218 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 218 of file HybridHadronization.h
Referenced by HybridHadronization::set_spacetime_for_pythia_hadrons().
void HybridHadronization::HHhadron::x (double val) inline
Definition at line 229 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 229 of file HybridHadronization.h
References t, y, and physmon_track_finding_ttbar::z.
double HybridHadronization::HHhadron::x_t () inline
Definition at line 218 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 218 of file HybridHadronization.h
Referenced by HybridHadronization::set_spacetime_for_pythia_hadrons().
void HybridHadronization::HHhadron::x_t (double val) inline
Definition at line 232 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 232 of file HybridHadronization.h
References ambiguity_solver_full_chain::x, y, and physmon_track_finding_ttbar::z.
double HybridHadronization::HHhadron::y () inline
Definition at line 218 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 218 of file HybridHadronization.h
Referenced by HybridHadronization::set_spacetime_for_pythia_hadrons().
void HybridHadronization::HHhadron::y (double val) inline
Definition at line 230 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 230 of file HybridHadronization.h
References t, ambiguity_solver_full_chain::x, and physmon_track_finding_ttbar::z.
double HybridHadronization::HHhadron::z () inline
Definition at line 218 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 218 of file HybridHadronization.h
Referenced by HybridHadronization::set_spacetime_for_pythia_hadrons().
void HybridHadronization::HHhadron::z (double val) inline
Definition at line 231 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 231 of file HybridHadronization.h
References t, ambiguity_solver_full_chain::x, and y.
Member Data Documentation
double HybridHadronization::HHhadron::alt_mass_ protected
Definition at line 192 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 192 of file HybridHadronization.h
std::vector<int> HybridHadronization::HHhadron::cols
Definition at line 211 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 211 of file HybridHadronization.h
bool HybridHadronization::HHhadron::is_excited_ protected
Definition at line 187 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 187 of file HybridHadronization.h
bool HybridHadronization::HHhadron::is_final_ protected
Definition at line 187 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 187 of file HybridHadronization.h
bool HybridHadronization::HHhadron::is_recohad_ protected
Definition at line 187 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 187 of file HybridHadronization.h
bool HybridHadronization::HHhadron::is_shsh_ protected
Definition at line 187 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 187 of file HybridHadronization.h
bool HybridHadronization::HHhadron::is_shth_ protected
Definition at line 187 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 187 of file HybridHadronization.h
bool HybridHadronization::HHhadron::is_strhad_ protected
Definition at line 187 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 187 of file HybridHadronization.h
bool HybridHadronization::HHhadron::is_thth_ protected
Definition at line 187 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 187 of file HybridHadronization.h
int HybridHadronization::HHhadron::orig_ protected
Definition at line 190 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 190 of file HybridHadronization.h
std::vector<int> HybridHadronization::HHhadron::parents
Definition at line 204 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 204 of file HybridHadronization.h
Referenced by HybridHadronization::recomb().
int HybridHadronization::HHhadron::parh_ protected
Definition at line 190 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 190 of file HybridHadronization.h
int HybridHadronization::HHhadron::parstr_ protected
Definition at line 190 of file HybridHadronization.h.
View newest version in sPHENIX GitHub at line 190 of file HybridHadronization.h
The documentation for this class was generated from the following file:
JETSCAPE/blob/main/src/hadronization/HybridHadronization.h