Analysis Software: RDBC/blob/master/test/RDBCTestMetaData/RDBCTestMetaData.C File Reference
RDBCTestMetaData.C File Reference
#include <TError.h>
#include <TString.h>
#include <RDBC/TSQLDriverManager.h>
#include <RDBC/TSQLConnection.h>
#include <RDBC/TSQLDatabaseMetaData.h>
#include <RDBC/TSQLResultSet.h>
#include <RDBC/TSQLResultSetMetaData.h>
#include <RDBC/TSQLPreparedStatement.h>
#include <RDBC/TSQLCallableStatement.h>
#include <RDBC/TSQLTypes.h>
#include <string>
#include <stdlib.h>
Functions
Int_t RDBCTestMetaData (const Text_t *dsn, const Text_t *schema, const Text_t *usr="", const Text_t *pwd="")
void Catch (TSQLException *e)
Function Documentation
void Catch (TSQLException * e)
Definition at line 311 of file RDBCTestMetaData.C.
View newest version in sPHENIX GitHub at line 311 of file RDBCTestMetaData.C
References TSQLException::GetMessage(), printf(), and str.
Int_t RDBCTestMetaData (const Text_t * dsn, const Text_t * schema, const Text_t * usr = "", const Text_t * pwd = "")
Definition at line 24 of file RDBCTestMetaData.C.
View newest version in sPHENIX GitHub at line 24 of file RDBCTestMetaData.C
References TSQLDatabaseMetaData::AllProceduresAreCallable(), TSQLDatabaseMetaData::AllTablesAreSelectable(), TSQLConnection::Close(), TSQLConnection::CreateStatement(), TSQLDatabaseMetaData::DataDefinitionCausesTransactionCommit(), TSQLDatabaseMetaData::DataDefinitionIgnoredInTransactions(), TSQLDatabaseMetaData::DoesMaxRowSizeIncludeBlobs(), TSQLStatement::ExecuteQuery(), TSQLDatabaseMetaData::GetCatalogSeparator(), TSQLDatabaseMetaData::GetCatalogTerm(), TSQLResultSetMetaData::GetColumnCount(), TSQLResultSetMetaData::GetColumnName(), TSQLResultSetMetaData::GetColumnTypeName(), TSQLDriverManager::GetConnection(), TSQLDatabaseMetaData::GetDatabaseProductName(), TSQLDatabaseMetaData::GetDatabaseProductVersion(), TSQLDatabaseMetaData::GetDefaultTransactionIsolation(), TSQLDatabaseMetaData::GetDriverMajorVersion(), TSQLDatabaseMetaData::GetDriverMinorVersion(), TSQLDatabaseMetaData::GetDriverName(), TSQLDatabaseMetaData::GetDriverVersion(), TSQLDatabaseMetaData::GetExtraNameCharacters(), TSQLDatabaseMetaData::GetIdentifierQuoteString(), TSQLDatabaseMetaData::GetMaxBinaryLiteralLength(), TSQLDatabaseMetaData::GetMaxCatalogNameLength(), TSQLDatabaseMetaData::GetMaxCharLiteralLength(), TSQLDatabaseMetaData::GetMaxColumnNameLength(), TSQLDatabaseMetaData::GetMaxColumnsInGroupBy(), TSQLDatabaseMetaData::GetMaxColumnsInIndex(), TSQLDatabaseMetaData::GetMaxColumnsInOrderBy(), TSQLDatabaseMetaData::GetMaxColumnsInSelect(), TSQLDatabaseMetaData::GetMaxColumnsInTable(), TSQLDatabaseMetaData::GetMaxConnections(), TSQLDatabaseMetaData::GetMaxCursorNameLength(), TSQLDatabaseMetaData::GetMaxIndexLength(), TSQLDatabaseMetaData::GetMaxProcedureNameLength(), TSQLDatabaseMetaData::GetMaxRowSize(), TSQLDatabaseMetaData::GetMaxSchemaNameLength(), TSQLDatabaseMetaData::GetMaxStatementLength(), TSQLDatabaseMetaData::GetMaxStatements(), TSQLDatabaseMetaData::GetMaxTableNameLength(), TSQLDatabaseMetaData::GetMaxTablesInSelect(), TSQLDatabaseMetaData::GetMaxUserNameLength(), TSQLConnection::GetMetaData(), TSQLResultSet::GetMetaData(), TSQLDatabaseMetaData::GetNumericFunctions(), TSQLDatabaseMetaData::GetProcedureTerm(), TSQLDatabaseMetaData::GetSchemaTerm(), TSQLDatabaseMetaData::GetSearchStringEscape(), TSQLDatabaseMetaData::GetSQLKeywords(), TSQLResultSet::GetString(), TSQLDatabaseMetaData::GetStringFunctions(), TSQLDatabaseMetaData::GetSystemFunctions(), TSQLDatabaseMetaData::GetTables(), TSQLDatabaseMetaData::GetTableTerm(), TSQLDatabaseMetaData::GetTimeDateFunctions(), TSQLDatabaseMetaData::GetUserName(), i, TSQLDatabaseMetaData::IsCatalogAtStart(), TSQLDatabaseMetaData::IsReadOnly(), TSQLResultSet::Next(), TSQLDatabaseMetaData::NullPlusNonNullIsNull(), TSQLDatabaseMetaData::NullsAreSortedAtEnd(), TSQLDatabaseMetaData::NullsAreSortedAtStart(), TSQLDatabaseMetaData::NullsAreSortedHigh(), TSQLDatabaseMetaData::NullsAreSortedLow(), printf(), TSQLDatabaseMetaData::StoresLowerCaseIdentifiers(), TSQLDatabaseMetaData::StoresLowerCaseQuotedIdentifiers(), TSQLDatabaseMetaData::StoresMixedCaseIdentifiers(), TSQLDatabaseMetaData::StoresMixedCaseQuotedIdentifiers(), TSQLDatabaseMetaData::StoresUpperCaseIdentifiers(), TSQLDatabaseMetaData::StoresUpperCaseQuotedIdentifiers(), TSQLDatabaseMetaData::SupportsAlterTableWithAddColumn(), TSQLDatabaseMetaData::SupportsAlterTableWithDropColumn(), TSQLDatabaseMetaData::SupportsANSI92EntryLevelSQL(), TSQLDatabaseMetaData::SupportsANSI92FullSQL(), TSQLDatabaseMetaData::SupportsANSI92IntermediateSQL(), TSQLDatabaseMetaData::SupportsCatalogsInDataManipulation(), TSQLDatabaseMetaData::SupportsCatalogsInIndexDefinitions(), TSQLDatabaseMetaData::SupportsCatalogsInPrivilegeDefinitions(), TSQLDatabaseMetaData::SupportsCatalogsInProcedureCalls(), TSQLDatabaseMetaData::SupportsCatalogsInTableDefinitions(), TSQLDatabaseMetaData::SupportsColumnAliasing(), TSQLDatabaseMetaData::SupportsConvert(), TSQLDatabaseMetaData::SupportsCoreSQLGrammar(), TSQLDatabaseMetaData::SupportsCorrelatedSubqueries(), TSQLDatabaseMetaData::SupportsDataDefinitionAndDataManipulationTransactions(), TSQLDatabaseMetaData::SupportsDataManipulationTransactionsOnly(), TSQLDatabaseMetaData::SupportsDifferentTableCorrelationNames(), TSQLDatabaseMetaData::SupportsExpressionsInOrderBy(), TSQLDatabaseMetaData::SupportsExtendedSQLGrammar(), TSQLDatabaseMetaData::SupportsFullOuterJoins(), TSQLDatabaseMetaData::SupportsGroupBy(), TSQLDatabaseMetaData::SupportsGroupByBeyondSelect(), TSQLDatabaseMetaData::SupportsGroupByUnrelated(), TSQLDatabaseMetaData::SupportsIntegrityEnhancementFacility(), TSQLDatabaseMetaData::SupportsLikeEscapeClause(), TSQLDatabaseMetaData::SupportsLimitedOuterJoins(), TSQLDatabaseMetaData::SupportsMinimumSQLGrammar(), TSQLDatabaseMetaData::SupportsMixedCaseIdentifiers(), TSQLDatabaseMetaData::SupportsMixedCaseQuotedIdentifiers(), TSQLDatabaseMetaData::SupportsMultipleResultSets(), TSQLDatabaseMetaData::SupportsMultipleTransactions(), TSQLDatabaseMetaData::SupportsNonNullableColumns(), TSQLDatabaseMetaData::SupportsOpenCursorsAcrossRollback(), TSQLDatabaseMetaData::SupportsOpenStatementsAcrossCommit(), TSQLDatabaseMetaData::SupportsOpenStatementsAcrossRollback(), TSQLDatabaseMetaData::SupportsOrderByUnrelated(), TSQLDatabaseMetaData::SupportsOuterJoins(), TSQLDatabaseMetaData::SupportsPositionedDelete(), TSQLDatabaseMetaData::SupportsPositionedUpdate(), TSQLDatabaseMetaData::SupportsSchemasInDataManipulation(), TSQLDatabaseMetaData::SupportsSchemasInIndexDefinitions(), TSQLDatabaseMetaData::SupportsSchemasInPrivilegeDefinitions(), TSQLDatabaseMetaData::SupportsSchemasInProcedureCalls(), TSQLDatabaseMetaData::SupportsSchemasInTableDefinitions(), TSQLDatabaseMetaData::SupportsSelectForUpdate(), TSQLDatabaseMetaData::SupportsStoredProcedures(), TSQLDatabaseMetaData::SupportsSubqueriesInComparisons(), TSQLDatabaseMetaData::SupportsSubqueriesInExists(), TSQLDatabaseMetaData::SupportsSubqueriesInIns(), TSQLDatabaseMetaData::SupportsSubqueriesInQuantifieds(), TSQLDatabaseMetaData::SupportsTableCorrelationNames(), TSQLDatabaseMetaData::SupportsTransactions(), TSQLDatabaseMetaData::SupportsUnion(), TSQLDatabaseMetaData::SupportsUnionAll(), tableName, TSQLDatabaseMetaData::UsesLocalFilePerTable(), and TSQLDatabaseMetaData::UsesLocalFiles().