Analysis Software: acts/blob/sPHENIX/Examples/Run/Reconstruction/Common/HoughExample.cpp File Reference
HoughExample.cpp File Reference
#include "Acts/Definitions/Units.hpp"
#include "Acts/Geometry/TrackingGeometry.hpp"
#include "ActsExamples/Detector/IBaseDetector.hpp"
#include "ActsExamples/Framework/Sequencer.hpp"
#include "ActsExamples/Geometry/CommonGeometry.hpp"
#include "ActsExamples/Io/Csv/CsvParticleReader.hpp"
#include "ActsExamples/Io/Csv/CsvSimHitReader.hpp"
#include "ActsExamples/Io/Performance/SeedingPerformanceWriter.hpp"
#include "ActsExamples/Io/Performance/TrackFinderPerformanceWriter.hpp"
#include "ActsExamples/Io/Root/RootTrackParameterWriter.hpp"
#include "ActsExamples/Options/CommonOptions.hpp"
#include "ActsExamples/Options/CsvOptionsReader.hpp"
#include "ActsExamples/Options/DigitizationOptions.hpp"
#include "ActsExamples/Options/MagneticFieldOptions.hpp"
#include "ActsExamples/Options/SpacePointMakerOptions.hpp"
#include "ActsExamples/Reconstruction/ReconstructionBase.hpp"
#include "ActsExamples/TrackFinding/DefaultHoughFunctions.hpp"
#include "ActsExamples/TrackFinding/HoughTransformSeeder.hpp"
#include "ActsExamples/TrackFinding/SpacePointMaker.hpp"
#include "ActsExamples/TrackFinding/TrackParamsEstimationAlgorithm.hpp"
#include "ActsExamples/TruthTracking/TruthSeedSelector.hpp"
#include "ActsExamples/Utilities/Options.hpp"
#include "ActsExamples/Utilities/Paths.hpp"
#include <memory>
#include <boost/program_options.hpp>
Functions
int runHoughExample (int argc, char *argv[], const std::shared_ptr< ActsExamples::IBaseDetector > &detector)
Function Documentation
int runHoughExample (int argc, char * argv[], const std::shared_ptr< ActsExamples::IBaseDetector > & detector)
Object 'prototracks' does not exists
Definition at line 40 of file HoughExample.cpp.
View newest version in sPHENIX GitHub at line 40 of file HoughExample.cpp
References ActsExamples::Sequencer::addAlgorithm(), ActsExamples::Sequencer::addContextDecorator(), ActsExamples::Options::addDigitizationOptions(), ActsExamples::Options::addGeometryOptions(), ActsExamples::Options::addInputOptions(), ActsExamples::Options::addMagneticFieldOptions(), ActsExamples::Options::addMaterialOptions(), ActsExamples::Options::addOutputOptions(), ActsExamples::Options::addRandomNumbersOptions(), ActsExamples::Options::addSequencerOptions(), ActsExamples::Options::addSpacePointMakerOptions(), ActsExamples::Sequencer::addWriter(), ActsExamples::Geometry::build(), ActsExamples::ensureWritableDirectory(), ActsExamples::TruthSeedSelector::Config::etaMax, ActsExamples::TruthSeedSelector::Config::etaMin, ActsExamples::DefaultHoughFunctions::fieldCorrectionDefault(), ActsExamples::HoughTransformSeeder::Config::fieldCorrector, ActsExamples::TrackFinderPerformanceWriter::Config::filePath, ActsExamples::SeedingPerformanceWriter::Config::filePath, ActsExamples::RootTrackParameterWriter::Config::filePath, ActsExamples::DefaultHoughFunctions::findLayerIDDefault(), Acts::Test::geometry, ActsExamples::HoughTransformSeeder::Config::geometrySelection, ActsExamples::HoughTransformSeeder::Config::hitExtend_x, ActsExamples::HoughTransformSeeder::Config::houghHistSize_x, ActsExamples::HoughTransformSeeder::Config::houghHistSize_y, ActsExamples::TrackFinderPerformanceWriter::Config::inputMeasurementParticlesMap, ActsExamples::SeedingPerformanceWriter::Config::inputMeasurementParticlesMap, ActsExamples::TruthSeedSelector::Config::inputMeasurementParticlesMap, ActsExamples::RootTrackParameterWriter::Config::inputMeasurementParticlesMap, ActsExamples::SpacePointMaker::Config::inputMeasurements, ActsExamples::HoughTransformSeeder::Config::inputMeasurements, ActsExamples::RootTrackParameterWriter::Config::inputMeasurementSimHitsMap, ActsExamples::TrackFinderPerformanceWriter::Config::inputParticles, ActsExamples::SeedingPerformanceWriter::Config::inputParticles, ActsExamples::TruthSeedSelector::Config::inputParticles, ActsExamples::RootTrackParameterWriter::Config::inputParticles, physmon_simulation::inputParticles, ActsExamples::TrackFinderPerformanceWriter::Config::inputProtoTracks, ActsExamples::RootTrackParameterWriter::Config::inputProtoTracks, ActsExamples::SeedingPerformanceWriter::Config::inputSeeds, ActsExamples::TrackParamsEstimationAlgorithm::Config::inputSeeds, ActsExamples::RootTrackParameterWriter::Config::inputSimHits, ActsExamples::SpacePointMaker::Config::inputSourceLinks, ActsExamples::HoughTransformSeeder::Config::inputSourceLinks, ActsExamples::HoughTransformSeeder::Config::inputSpacePoints, ActsExamples::RootTrackParameterWriter::Config::inputTrackParameters, ActsExamples::DefaultHoughFunctions::inSliceDefault(), ActsExamples::HoughTransformSeeder::Config::kA, ActsExamples::HoughTransformSeeder::Config::layerIDFinder, ActsExamples::HoughTransformSeeder::Config::localMaxWindowSize, telescope_simulation::logLevel, ActsTests::PropagationDatasets::magneticField, ActsExamples::TrackParamsEstimationAlgorithm::Config::magneticField, ActsExamples::Options::makeDefaultOptions(), ActsExamples::TruthSeedSelector::Config::nHitsMin, ActsExamples::HoughTransformSeeder::Config::nLayers, outputDir, ActsExamples::TruthSeedSelector::Config::outputParticles, ActsExamples::HoughTransformSeeder::Config::outputProtoTracks, ActsExamples::HoughTransformSeeder::Config::outputSeeds, ActsExamples::SpacePointMaker::Config::outputSpacePoints, ActsExamples::TrackParamsEstimationAlgorithm::Config::outputTrackParameters, ActsExamples::Options::parse(), ActsExamples::TruthSeedSelector::Config::ptMin, ActsExamples::Options::readLogLevel(), ActsExamples::Options::readMagneticField(), ActsExamples::Options::readRandomNumbersConfig(), ActsExamples::Options::readSequencerConfig(), ActsExamples::Options::readSpacePointMakerConfig(), physmon_simulation::rnd, ActsExamples::Sequencer::run(), setupDigitization(), ActsExamples::Options::setupMagneticFieldServices(), setupParticleReading(), setupSimHitReading(), Acts::GeometryIdentifier::setVolume(), ActsExamples::HoughTransformSeeder::Config::sliceTester, ActsExamples::HoughTransformSeeder::Config::subRegions, Acts::tGeometry, ActsExamples::HoughTransformSeeder::Config::threshold, ActsExamples::SpacePointMaker::Config::trackingGeometry, ActsExamples::TrackParamsEstimationAlgorithm::Config::trackingGeometry, ActsExamples::HoughTransformSeeder::Config::trackingGeometry, ActsExamples::RootTrackParameterWriter::Config::treeName, ActsExamples::HoughTransformSeeder::Config::xMax, ActsExamples::HoughTransformSeeder::Config::xMin, ActsExamples::HoughTransformSeeder::Config::yMax, and ActsExamples::HoughTransformSeeder::Config::yMin.
Referenced by main().