Analysis Software: PHHepMCGenEvent Class Reference
PHHepMCGenEvent Class Reference
#include <coresoftware/blob/master/generators/phhepmc/PHHepMCGenEvent.h>
Public Member Functions
PHHepMCGenEvent ()
PHHepMCGenEvent (const PHHepMCGenEvent &event)
PHHepMCGenEvent & operator= (const PHHepMCGenEvent &event)
~PHHepMCGenEvent () override
void identify (std::ostream &os=std::cout) const override
void Reset () override
Clear Event.
int isValid () const override
isValid returns non zero if object contains vailid data
PHObject * CloneMe () const override
Virtual copy constructor.
HepMC::GenEvent * getEvent ()
const HepMC::GenEvent * getEvent () const
int get_embedding_id () const
void set_embedding_id (int id)
bool is_simulated () const
whether this event has been processed in Geant4 simulation
void is_simulated (bool v)
whether this event has been processed in Geant4 simulation
const HepMC::FourVector & get_collision_vertex () const
collision vertex position in the Hall coordinate system, use PHENIX units of cm, ns
void set_collision_vertex (const HepMC::FourVector &v)
collision vertex position in the Hall coordinate system, use PHENIX units of cm, ns
virtual const HepMC::ThreeVector & get_boost_beta_vector () const
boost beta vector for Lorentz Transform, part of composition of a LorentzRotation to translate from hepmc event frame to lab frame
virtual void set_boost_beta_vector (const HepMC::ThreeVector &)
boost beta vector for Lorentz Transform, part of composition of a LorentzRotation to translate from hepmc event frame to lab frame
virtual const HepMC::ThreeVector & get_rotation_vector () const
rotation axis vector, part of composition of a LorentzRotation to translate from hepmc event frame to lab frame
virtual void set_rotation_vector (const HepMC::ThreeVector &)
rotation axis vector, part of composition of a LorentzRotation to translate from hepmc event frame to lab frame
virtual double get_rotation_angle () const
rotation angle, part of composition of a LorentzRotation to translate from hepmc event frame to lab frame
virtual void set_rotation_angle (const double)
rotation angle, part of composition of a LorentzRotation to translate from hepmc event frame to lab frame
virtual CLHEP::HepLorentzRotation get_LorentzRotation_EvtGen2Lab () const
LorentzRotation to translate from hepmc event frame to lab frame.
virtual CLHEP::HepLorentzRotation get_LorentzRotation_Lab2EvtGen () const
LorentzRotation to translate from lab frame to hepmc event frame.
bool addEvent (HepMC::GenEvent *evt)
host an HepMC event
bool addEvent (HepMC::GenEvent &evt)
bool swapEvent (HepMC::GenEvent *&evt)
void clearEvent ()
virtual void moveVertex (double x, double y, double z, double t=0)
move the collision vertex position in the Hall coordinate system, use PHENIX units of cm, ns
virtual int size (void) const
virtual int vertexSize (void) const
void print (std::ostream &os=std::cout) const
void PrintEvent ()
Public Member Functions inherited from PHObject
PHObject ()
ctor
~PHObject () override
dtor
virtual PHObject * clone () const final
PHObject * Clone (const char *newname="") const final
void Copy (TObject &object) const final
virtual int Integrate () const
virtual int Integrate (PHObject *)
virtual void CopyFrom (const PHObject *obj)
Protected Attributes
int _embedding_id
Embedding ID for this generated event positive ID is the embedded event of interest, e.g. jetty event from pythia negative IDs are backgrounds, .e.g out of time pile up collisions Usually, ID = 0 means the primary Au+Au collision background.
bool _isSimulated
whether this event has been processed in Geant4 simulation
HepMC::FourVector _collisionVertex
collision vertex position in the Hall coordinate system, use PHENIX units of cm, ns
HepMC::GenEvent * _theEvt
The HEP MC record from event generator. Note the units are recorded in GenEvent.
Detailed Description
Definition at line 19 of file PHHepMCGenEvent.h.
View newest version in sPHENIX GitHub at line 19 of file PHHepMCGenEvent.h
Constructor & Destructor Documentation
PHHepMCGenEvent::PHHepMCGenEvent ()
Definition at line 20 of file PHHepMCGenEvent.cc.
View newest version in sPHENIX GitHub at line 20 of file PHHepMCGenEvent.cc
Referenced by CloneMe().
PHHepMCGenEvent::PHHepMCGenEvent (const PHHepMCGenEvent & event)
Definition at line 28 of file PHHepMCGenEvent.cc.
View newest version in sPHENIX GitHub at line 28 of file PHHepMCGenEvent.cc
References _theEvt, and getEvent().
PHHepMCGenEvent::~PHHepMCGenEvent () override
Definition at line 52 of file PHHepMCGenEvent.cc.
View newest version in sPHENIX GitHub at line 52 of file PHHepMCGenEvent.cc
References _theEvt.
Member Function Documentation
bool PHHepMCGenEvent::addEvent (HepMC::GenEvent * evt)
host an HepMC event
Definition at line 76 of file PHHepMCGenEvent.cc.
View newest version in sPHENIX GitHub at line 76 of file PHHepMCGenEvent.cc
References _theEvt.
Referenced by addEvent(), PHHepMCGenHelper::insert_event(), Fun4AllHepMCPileupInputManager::InsertEvent(), and sPHAnalysis::process_event_hepmc().
bool PHHepMCGenEvent::addEvent (HepMC::GenEvent & evt)
Definition at line 95 of file PHHepMCGenEvent.cc.
View newest version in sPHENIX GitHub at line 95 of file PHHepMCGenEvent.cc
References addEvent().
void PHHepMCGenEvent::clearEvent ()
Definition at line 100 of file PHHepMCGenEvent.cc.
View newest version in sPHENIX GitHub at line 100 of file PHHepMCGenEvent.cc
References _theEvt.
PHObject* PHHepMCGenEvent::CloneMe () const inline override virtual
Virtual copy constructor.
Reimplemented from PHObject.
Reimplemented in PHHepMCGenEventv1.
Definition at line 34 of file PHHepMCGenEvent.h.
View newest version in sPHENIX GitHub at line 34 of file PHHepMCGenEvent.h
References PHHepMCGenEvent().
virtual const HepMC::ThreeVector& PHHepMCGenEvent::get_boost_beta_vector () const inline virtual
boost beta vector for Lorentz Transform, part of composition of a LorentzRotation to translate from hepmc event frame to lab frame
Reimplemented in PHHepMCGenEventv1.
Definition at line 64 of file PHHepMCGenEvent.h.
View newest version in sPHENIX GitHub at line 64 of file PHHepMCGenEvent.h
References PHOOL_VIRTUAL_WARNING.
Referenced by PHHepMCGenHelper::HepMC2Lab_boost_rotation_translation().
const HepMC::FourVector& PHHepMCGenEvent::get_collision_vertex () const inline
collision vertex position in the Hall coordinate system, use PHENIX units of cm, ns
Definition at line 58 of file PHHepMCGenEvent.h.
View newest version in sPHENIX GitHub at line 58 of file PHHepMCGenEvent.h
References _collisionVertex.
Referenced by PHHepMCGenHelper::HepMC2Lab_boost_rotation_translation(), HepMCNodeReader::process_event(), HFMLTriggerInterface::process_event(), PHG4ScoringManager::process_event(), DumpPHHepMCGenEventMap::process_Node(), and PHG4ParticleGeneratorBase::ReuseExistingVertex().
int PHHepMCGenEvent::get_embedding_id () const inline
embedding ID for the event positive ID is the embedded event of interest, e.g. jetty event from pythia negative IDs are backgrounds, .e.g out of time pile up collisions Usually, ID = 0 means the primary Au+Au collision background
Definition at line 43 of file PHHepMCGenEvent.h.
View newest version in sPHENIX GitHub at line 43 of file PHHepMCGenEvent.h
References _embedding_id.
Referenced by DecayFinder::checkIfCorrectHepMCParticle(), DecayFinder::findDecay(), IsolatedTrackAnalysis::getHepMCTruth(), HeadReco::process_event(), HepMCNodeReader::process_event(), JetHepMCLoader::process_event(), DumpPHHepMCGenEventMap::process_Node(), DecayFinder::searchGeant4Record(), and DecayFinder::searchHepMCRecord().
virtual CLHEP::HepLorentzRotation PHHepMCGenEvent::get_LorentzRotation_EvtGen2Lab () const inline virtual
LorentzRotation to translate from hepmc event frame to lab frame.
Reimplemented in PHHepMCGenEventv1.
Definition at line 96 of file PHHepMCGenEvent.h.
View newest version in sPHENIX GitHub at line 96 of file PHHepMCGenEvent.h
Referenced by HepMCNodeReader::process_event().
virtual CLHEP::HepLorentzRotation PHHepMCGenEvent::get_LorentzRotation_Lab2EvtGen () const inline virtual
LorentzRotation to translate from lab frame to hepmc event frame.
Reimplemented in PHHepMCGenEventv1.
Definition at line 99 of file PHHepMCGenEvent.h.
View newest version in sPHENIX GitHub at line 99 of file PHHepMCGenEvent.h
virtual double PHHepMCGenEvent::get_rotation_angle () const inline virtual
rotation angle, part of composition of a LorentzRotation to translate from hepmc event frame to lab frame
Reimplemented in PHHepMCGenEventv1.
Definition at line 86 of file PHHepMCGenEvent.h.
View newest version in sPHENIX GitHub at line 86 of file PHHepMCGenEvent.h
References PHOOL_VIRTUAL_WARNING.
Referenced by PHHepMCGenHelper::HepMC2Lab_boost_rotation_translation().
virtual const HepMC::ThreeVector& PHHepMCGenEvent::get_rotation_vector () const inline virtual
rotation axis vector, part of composition of a LorentzRotation to translate from hepmc event frame to lab frame
Reimplemented in PHHepMCGenEventv1.
Definition at line 75 of file PHHepMCGenEvent.h.
View newest version in sPHENIX GitHub at line 75 of file PHHepMCGenEvent.h
References PHOOL_VIRTUAL_WARNING.
Referenced by PHHepMCGenHelper::HepMC2Lab_boost_rotation_translation().
HepMC::GenEvent * PHHepMCGenEvent::getEvent ()
Definition at line 66 of file PHHepMCGenEvent.cc.
View newest version in sPHENIX GitHub at line 66 of file PHHepMCGenEvent.cc
References _theEvt.
Referenced by ExclusiveReco::AddInvariantMassInformation(), FermimotionAfterburner::AddpF(), LeptoquarksReco::AddTrueTauTag(), DISKinematicsReco::AddTruthEventInformation(), DISKinematicsReco::CollectEmCandidatesFromTruth(), Fun4AllDstPileupMerger::copy_background_event(), EpFinderEval::fill_tree(), EventEvaluator::fillOutputNtuples(), TruthTrackerHepMC::FindBeamHadron(), TruthTrackerHepMC::FindBeamLepton(), DecayFinder::findDecay(), ResonanceJetTagging::findMCTaggedJets(), TruthTrackerHepMC::FindMissingPt(), TruthTrackerHepMC::FindParticle(), AntiTrigger::findParticle(), TruthTrackerHepMC::FindScatteredLepton(), HFTrackEfficiency::findTracks(), BuildResonanceJetTaggingTree::getGenEventFromNode(), KFParticle_truthAndDetTools::getHepMCInfo(), AnaTutorial::getHEPMCTruth(), IsolatedTrackAnalysis::getHepMCTruth(), BuildResonanceJetTaggingTree::getMother(), isValid(), QAG4SimulationKFParticle::makeHepLV(), PHHepMCGenEventv1::operator=(), operator=(), PHHepMCGenEvent(), HeadReco::process_event(), HepMCFlowAfterBurner::process_event(), HIJINGFlipAfterburner::process_event(), HepMCNodeReader::process_event(), ReactionPlaneAfterburner::process_event(), PHHepMCParticleSelectorDecayProductChain::process_event(), HFJetTruthTrigger::process_event(), Quarkonia2LeptonsMC::process_event(), BJetModule::process_event(), HFMLTriggerHepMCTrigger::process_event(), DirectPhotonPythia::process_event(), HFFastSim::process_event(), HFMLTriggerInterface::process_event(), SynRadAna::process_event(), TruthPhotonJet::process_event(), PhotonJet::process_event(), TruthJetTagging::process_event(), JetHepMCLoader::process_event(), FullJetFinder::process_event(), DumpPHHepMCGenEventMap::process_Node(), and Fun4AllHepMCOutputManager::Write().
const HepMC::GenEvent * PHHepMCGenEvent::getEvent () const
Definition at line 71 of file PHHepMCGenEvent.cc.
View newest version in sPHENIX GitHub at line 71 of file PHHepMCGenEvent.cc
References _theEvt.
void PHHepMCGenEvent::identify (std::ostream & os = std::cout) const override virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from PHObject.
Reimplemented in PHHepMCGenEventv1.
Definition at line 130 of file PHHepMCGenEvent.cc.
View newest version in sPHENIX GitHub at line 130 of file PHHepMCGenEvent.cc
References _collisionVertex, _embedding_id, _isSimulated, size(), and vertexSize().
Referenced by PHHepMCGenHelper::HepMC2Lab_boost_rotation_translation(), PHHepMCGenEventv1::identify(), print(), HepMCNodeReader::process_event(), PHG4ScoringManager::process_event(), JetHepMCLoader::process_event(), and PHG4ParticleGeneratorBase::ReuseExistingVertex().
bool PHHepMCGenEvent::is_simulated () const inline
whether this event has been processed in Geant4 simulation
Definition at line 52 of file PHHepMCGenEvent.h.
View newest version in sPHENIX GitHub at line 52 of file PHHepMCGenEvent.h
References _isSimulated.
Referenced by HepMCNodeReader::process_event(), and DumpPHHepMCGenEventMap::process_Node().
void PHHepMCGenEvent::is_simulated (bool v) inline
whether this event has been processed in Geant4 simulation
Definition at line 55 of file PHHepMCGenEvent.h.
View newest version in sPHENIX GitHub at line 55 of file PHHepMCGenEvent.h
References _isSimulated, and testSigmaEff::v.
int PHHepMCGenEvent::isValid () const inline override virtual
isValid returns non zero if object contains vailid data
Reimplemented from PHObject.
Reimplemented in PHHepMCGenEventv1.
Definition at line 30 of file PHHepMCGenEvent.h.
View newest version in sPHENIX GitHub at line 30 of file PHHepMCGenEvent.h
References getEvent().
void PHHepMCGenEvent::moveVertex (double x, double y, double z, double t = 0) virtual
move the collision vertex position in the Hall coordinate system, use PHENIX units of cm, ns
Definition at line 105 of file PHHepMCGenEvent.cc.
View newest version in sPHENIX GitHub at line 105 of file PHHepMCGenEvent.cc
References _collisionVertex, t, ambiguity_solver_full_chain::x, y, and physmon_track_finding_ttbar::z.
Referenced by PHHepMCGenHelper::HepMC2Lab_boost_rotation_translation(), Fun4AllHepMCPileupInputManager::InsertEvent(), and PHHepMCGenHelper::move_vertex().
PHHepMCGenEvent & PHHepMCGenEvent::operator= (const PHHepMCGenEvent & event)
Definition at line 39 of file PHHepMCGenEvent.cc.
View newest version in sPHENIX GitHub at line 39 of file PHHepMCGenEvent.cc
References _embedding_id, _isSimulated, _theEvt, getEvent(), and Reset().
void PHHepMCGenEvent::print (std::ostream & os = std::cout) const
Definition at line 142 of file PHHepMCGenEvent.cc.
View newest version in sPHENIX GitHub at line 142 of file PHHepMCGenEvent.cc
References identify().
void PHHepMCGenEvent::PrintEvent ()
Definition at line 147 of file PHHepMCGenEvent.cc.
View newest version in sPHENIX GitHub at line 147 of file PHHepMCGenEvent.cc
References _theEvt.
void PHHepMCGenEvent::Reset () override virtual
Clear Event.
Reimplemented from PHObject.
Reimplemented in PHHepMCGenEventv1.
Definition at line 57 of file PHHepMCGenEvent.cc.
View newest version in sPHENIX GitHub at line 57 of file PHHepMCGenEvent.cc
References _collisionVertex, _embedding_id, _isSimulated, and _theEvt.
Referenced by operator=(), and PHHepMCGenEventv1::Reset().
virtual void PHHepMCGenEvent::set_boost_beta_vector (const HepMC::ThreeVector &) inline virtual
boost beta vector for Lorentz Transform, part of composition of a LorentzRotation to translate from hepmc event frame to lab frame
Reimplemented in PHHepMCGenEventv1.
Definition at line 72 of file PHHepMCGenEvent.h.
View newest version in sPHENIX GitHub at line 72 of file PHHepMCGenEvent.h
References PHOOL_VIRTUAL_WARNING.
Referenced by PHHepMCGenHelper::HepMC2Lab_boost_rotation_translation().
void PHHepMCGenEvent::set_collision_vertex (const HepMC::FourVector & v) inline
collision vertex position in the Hall coordinate system, use PHENIX units of cm, ns
Definition at line 61 of file PHHepMCGenEvent.h.
View newest version in sPHENIX GitHub at line 61 of file PHHepMCGenEvent.h
References _collisionVertex, and testSigmaEff::v.
Referenced by PHHepMCGenHelper::generate_vertx_with_bunch_interaction().
void PHHepMCGenEvent::set_embedding_id (int id) inline
embedding ID for the event positive ID is the embedded event of interest, e.g. jetty event from pythia negative IDs are backgrounds, .e.g out of time pile up collisions Usually, ID = 0 means the primary Au+Au collision background
Definition at line 49 of file PHHepMCGenEvent.h.
View newest version in sPHENIX GitHub at line 49 of file PHHepMCGenEvent.h
References _embedding_id, and train_ambiguity_solver::id.
Referenced by PHHepMCGenEventMap::insert_active_event(), PHHepMCGenEventMap::insert_background_event(), and PHHepMCGenEventMap::insert_event().
virtual void PHHepMCGenEvent::set_rotation_angle (const double) inline virtual
rotation angle, part of composition of a LorentzRotation to translate from hepmc event frame to lab frame
Reimplemented in PHHepMCGenEventv1.
Definition at line 93 of file PHHepMCGenEvent.h.
View newest version in sPHENIX GitHub at line 93 of file PHHepMCGenEvent.h
References PHOOL_VIRTUAL_WARNING.
Referenced by PHHepMCGenHelper::HepMC2Lab_boost_rotation_translation().
virtual void PHHepMCGenEvent::set_rotation_vector (const HepMC::ThreeVector &) inline virtual
rotation axis vector, part of composition of a LorentzRotation to translate from hepmc event frame to lab frame
Reimplemented in PHHepMCGenEventv1.
Definition at line 83 of file PHHepMCGenEvent.h.
View newest version in sPHENIX GitHub at line 83 of file PHHepMCGenEvent.h
References PHOOL_VIRTUAL_WARNING.
Referenced by PHHepMCGenHelper::HepMC2Lab_boost_rotation_translation().
int PHHepMCGenEvent::size (void) const virtual
Definition at line 113 of file PHHepMCGenEvent.cc.
View newest version in sPHENIX GitHub at line 113 of file PHHepMCGenEvent.cc
References _theEvt.
Referenced by identify().
bool PHHepMCGenEvent::swapEvent (HepMC::GenEvent *& evt)
Definition at line 87 of file PHHepMCGenEvent.cc.
View newest version in sPHENIX GitHub at line 87 of file PHHepMCGenEvent.cc
References _theEvt, and swap().
int PHHepMCGenEvent::vertexSize (void) const virtual
Definition at line 121 of file PHHepMCGenEvent.cc.
View newest version in sPHENIX GitHub at line 121 of file PHHepMCGenEvent.cc
References _theEvt.
Referenced by identify().
Member Data Documentation
HepMC::FourVector PHHepMCGenEvent::_collisionVertex protected
collision vertex position in the Hall coordinate system, use PHENIX units of cm, ns
Definition at line 129 of file PHHepMCGenEvent.h.
View newest version in sPHENIX GitHub at line 129 of file PHHepMCGenEvent.h
Referenced by get_collision_vertex(), identify(), moveVertex(), Reset(), and set_collision_vertex().
int PHHepMCGenEvent::_embedding_id protected
Embedding ID for this generated event positive ID is the embedded event of interest, e.g. jetty event from pythia negative IDs are backgrounds, .e.g out of time pile up collisions Usually, ID = 0 means the primary Au+Au collision background.
Definition at line 123 of file PHHepMCGenEvent.h.
View newest version in sPHENIX GitHub at line 123 of file PHHepMCGenEvent.h
Referenced by get_embedding_id(), identify(), PHHepMCGenEventv1::operator=(), operator=(), Reset(), and set_embedding_id().
bool PHHepMCGenEvent::_isSimulated protected
whether this event has been processed in Geant4 simulation
Definition at line 126 of file PHHepMCGenEvent.h.
View newest version in sPHENIX GitHub at line 126 of file PHHepMCGenEvent.h
Referenced by identify(), is_simulated(), PHHepMCGenEventv1::operator=(), operator=(), and Reset().
HepMC::GenEvent* PHHepMCGenEvent::_theEvt protected
The HEP MC record from event generator. Note the units are recorded in GenEvent.
Definition at line 132 of file PHHepMCGenEvent.h.
View newest version in sPHENIX GitHub at line 132 of file PHHepMCGenEvent.h
Referenced by addEvent(), clearEvent(), getEvent(), PHHepMCGenEventv1::operator=(), operator=(), PHHepMCGenEvent(), PrintEvent(), Reset(), size(), swapEvent(), vertexSize(), and ~PHHepMCGenEvent().
The documentation for this class was generated from the following files:
coresoftware/blob/master/generators/phhepmc/PHHepMCGenEvent.h
coresoftware/blob/master/generators/phhepmc/PHHepMCGenEvent.cc