Analysis Software: Acts::Experimental::NavigationState Struct Reference
Acts::Experimental::NavigationState Struct Reference
A navigation state struct that is holding the current navigation information.
#include <acts/blob/sPHENIX/Core/include/Acts/Navigation/NavigationState.hpp>
Classes
struct SurfaceCandidate
A surface candidate and its intersection.
Public Types
using SurfaceCandidates = std::vector< SurfaceCandidate >
Public Attributes
Vector3 position = Vector3(0., 0., 0.)
The current position.
Vector3 direction = Vector3(0., 0., 0.)
The current direction.
ActsScalar absMomentum = 0.
The current absolute momentum.
ActsScalar absCharge = 0.
The current absolute charge.
Vector3 magneticField = Vector3(0., 0., 0.)
The current magnetic field.
const Detector * currentDetector = nullptr
The current detector in processing.
const DetectorVolume * currentVolume = nullptr
The current volume in processing, i.e. the position is inside.
const Surface * currentSurface = nullptr
The current surface, i.e the position is on surface.
const Portal * currentPortal = nullptr
The current portal, i.e the position is on portal.
SurfaceCandidates surfaceCandidates = {}
That are the candidate surfaces to process.
SurfaceCandidates::const_iterator surfaceCandidate = surfaceCandidates.cend()
BoundaryCheck surfaceBoundaryCheck = true
Boundary directives for surfaces.
ActsScalar overstepTolerance = -0.1
An overstep tolerance.
std::any auxiliary
Auxiliary attached information.
Detailed Description
A navigation state struct that is holding the current navigation information.
It relies on Surfaces and Portals, all navigation entities have to be described in these terms.
Definition at line 34 of file NavigationState.hpp.
View newest version in sPHENIX GitHub at line 34 of file NavigationState.hpp
Member Typedef Documentation
using Acts::Experimental::NavigationState::SurfaceCandidates = std::vector<SurfaceCandidate>
Surface candidate vector alias, this allows to use e.g. boost_small vector or other stl like containers
Definition at line 52 of file NavigationState.hpp.
View newest version in sPHENIX GitHub at line 52 of file NavigationState.hpp
Member Data Documentation
ActsScalar Acts::Experimental::NavigationState::absCharge = 0.
The current absolute charge.
Definition at line 64 of file NavigationState.hpp.
View newest version in sPHENIX GitHub at line 64 of file NavigationState.hpp
ActsScalar Acts::Experimental::NavigationState::absMomentum = 0.
The current absolute momentum.
Definition at line 61 of file NavigationState.hpp.
View newest version in sPHENIX GitHub at line 61 of file NavigationState.hpp
Referenced by Acts::Experimental::DetectorNavigator::fillNavigationState().
std::any Acts::Experimental::NavigationState::auxiliary
Auxiliary attached information.
Definition at line 92 of file NavigationState.hpp.
View newest version in sPHENIX GitHub at line 92 of file NavigationState.hpp
const Detector* Acts::Experimental::NavigationState::currentDetector = nullptr
The current detector in processing.
Definition at line 70 of file NavigationState.hpp.
View newest version in sPHENIX GitHub at line 70 of file NavigationState.hpp
Referenced by BOOST_AUTO_TEST_CASE(), Acts::Experimental::IndexedDetectorVolumeExtractor::extract(), Acts::Experimental::Detector::findDetectorVolume(), Acts::Experimental::DetectorNavigator::initializeTarget(), Acts::Experimental::RootVolumeFinder::update(), and Acts::Experimental::AllPortalsAndSurfacesImpl::update().
const Portal* Acts::Experimental::NavigationState::currentPortal = nullptr
The current portal, i.e the position is on portal.
Definition at line 79 of file NavigationState.hpp.
View newest version in sPHENIX GitHub at line 79 of file NavigationState.hpp
const Surface* Acts::Experimental::NavigationState::currentSurface = nullptr
The current surface, i.e the position is on surface.
Definition at line 76 of file NavigationState.hpp.
View newest version in sPHENIX GitHub at line 76 of file NavigationState.hpp
const DetectorVolume* Acts::Experimental::NavigationState::currentVolume = nullptr
The current volume in processing, i.e. the position is inside.
Definition at line 73 of file NavigationState.hpp.
View newest version in sPHENIX GitHub at line 73 of file NavigationState.hpp
Referenced by BOOST_AUTO_TEST_CASE(), Acts::Experimental::AllPortalsExtractor::extract(), Acts::Experimental::IndexedSurfacesExtractor::extract(), Acts::Experimental::IndexedSubVolumesExtractor::extract(), Acts::Experimental::DetectorVolumeFiller::fill(), Acts::Experimental::Detector::findDetectorVolume(), Acts::Experimental::DetectorNavigator::initializeTarget(), Acts::Experimental::LinkToVolumeImpl::link(), Acts::Experimental::RootVolumeFinder::update(), Acts::Experimental::EndOfWorldImpl::update(), Acts::Experimental::AllPortalsImpl::update(), Acts::Experimental::TrialAndErrorVolumeFinder::update(), Acts::Experimental::SingleDetectorVolumeImpl::update(), Acts::Experimental::AllPortalsAndSurfacesImpl::update(), Acts::Experimental::Portal::updateDetectorVolume(), Acts::Experimental::DetectorVolume::updateNavigationState(), and Acts::Experimental::DetectorNavigator::volInfo().
Vector3 Acts::Experimental::NavigationState::direction = Vector3(0., 0., 0.)
The current direction.
Definition at line 58 of file NavigationState.hpp.
View newest version in sPHENIX GitHub at line 58 of file NavigationState.hpp
Referenced by BOOST_AUTO_TEST_CASE(), Acts::Experimental::DetectorNavigator::fillNavigationState(), Acts::Experimental::MultiLayerSurfacesUpdatorImpl< grid_t, path_generator >::update(), Acts::Experimental::updateCandidates(), and Acts::Experimental::Portal::updateDetectorVolume().
Vector3 Acts::Experimental::NavigationState::magneticField = Vector3(0., 0., 0.)
The current magnetic field.
Definition at line 67 of file NavigationState.hpp.
View newest version in sPHENIX GitHub at line 67 of file NavigationState.hpp
Referenced by Acts::Experimental::DetectorNavigator::fillNavigationState().
ActsScalar Acts::Experimental::NavigationState::overstepTolerance = -0.1
An overstep tolerance.
Definition at line 89 of file NavigationState.hpp.
View newest version in sPHENIX GitHub at line 89 of file NavigationState.hpp
Vector3 Acts::Experimental::NavigationState::position = Vector3(0., 0., 0.)
The current position.
Definition at line 55 of file NavigationState.hpp.
View newest version in sPHENIX GitHub at line 55 of file NavigationState.hpp
Referenced by BOOST_AUTO_TEST_CASE(), Acts::Experimental::DetectorNavigator::fillNavigationState(), Acts::Experimental::Detector::findDetectorVolume(), Acts::Experimental::DetectorNavigator::initializeTarget(), Acts::Experimental::RootVolumeFinder::update(), Acts::Experimental::MultiLayerSurfacesUpdatorImpl< grid_t, path_generator >::update(), Acts::Experimental::TrialAndErrorVolumeFinder::update(), Acts::Experimental::IndexedUpdatorImpl< VariableBoundIndexGrid1, DetectorVolumesCollection, DetectorVolumeFiller >::update(), Acts::Experimental::updateCandidates(), and Acts::Experimental::Portal::updateDetectorVolume().
BoundaryCheck Acts::Experimental::NavigationState::surfaceBoundaryCheck = true
Boundary directives for surfaces.
Definition at line 86 of file NavigationState.hpp.
View newest version in sPHENIX GitHub at line 86 of file NavigationState.hpp
Referenced by Acts::Experimental::SurfacesFiller::fill().
SurfaceCandidates::const_iterator Acts::Experimental::NavigationState::surfaceCandidate = surfaceCandidates.cend()
Definition at line 83 of file NavigationState.hpp.
View newest version in sPHENIX GitHub at line 83 of file NavigationState.hpp
Referenced by Acts::Experimental::DetectorNavigator::initializeTarget(), and Acts::Experimental::DetectorVolume::updateNavigationState().
SurfaceCandidates Acts::Experimental::NavigationState::surfaceCandidates = {}
That are the candidate surfaces to process.
Definition at line 82 of file NavigationState.hpp.
View newest version in sPHENIX GitHub at line 82 of file NavigationState.hpp
Referenced by BOOST_AUTO_TEST_CASE(), Acts::Experimental::SurfacesFiller::fill(), Acts::Experimental::PortalsFiller::fill(), Acts::Experimental::DetectorNavigator::initializeTarget(), Acts::Experimental::AllPortalsImpl::update(), Acts::Experimental::AllPortalsAndSurfacesImpl::update(), Acts::Experimental::updateCandidates(), and Acts::Experimental::DetectorVolume::updateNavigationState().
The documentation for this struct was generated from the following file:
acts/blob/sPHENIX/Core/include/Acts/Navigation/NavigationState.hpp