Analysis Software: JETSCAPE/blob/main/external_packages/gtl/tests/my_test.cc File Reference
my_test.cc File Reference
#include <iostream>
#include <GTL/graph.h>
#include <GTL/bellman_ford.h>
#include <GTL/edge_map.h>
#include <GTL/node_map.h>
Classes
class my_graph
class parton
class shower
Functions
int main (int argc, char *argv[])
Function Documentation
int main (int argc, char * argv[])
Definition at line 79 of file my_test.cc.
View newest version in sPHENIX GitHub at line 79 of file my_test.cc
References Acts::UnitConstants::e, graph::edges_begin(), graph::edges_end(), end, G, my_graph::GetEdgeValue(), shower::GetEdgeValue(), my_graph::GetNodeValue(), shower::GetNodeValue(), release::git, it, graph::make_directed(), n, graph::new_edge(), graph::new_node(), my_graph::new_parton(), shower::new_parton(), my_graph::new_vertex(), shower::new_vertex(), graph::nodes_begin(), graph::nodes_end(), merge_hashes::p, parton(), and S().