Analysis Software: PomsMainFrame Class Reference
PomsMainFrame Class Reference
#include <OnlMon/blob/main/poms/Poms.h>
Public Member Functions
virtual ~PomsMainFrame ()
void StopLoop ()
void SetMacroPath (const char *path)
virtual void CloseWindow ()
virtual Bool_t ProcessMessage (Long_t msg, Long_t parm1, Long_t)
void Draw ()
void AlignRight ()
void TileCanvases (TList *canvasList)
void CascadeCanvases (TList *canvasList)
void TileAllCanvases ()
UInt_t GetRootWidth ()
UInt_t GetRootHeight ()
const std::string & GetMacroPath ()
SubSystem * RegisterSubSystem (const char *name, const char *prefix, int addDefaultActions=1, int loadLibrary=1)
SubSystem * RegisterSubSystem (SubSystem *subSystem)
Static Public Member Functions
static PomsMainFrame * Instance ()
Private Member Functions
TGShutter * BuildShutter ()
int HandleButtonPoms (Long_t parm1)
void LoopDiLoop ()
PomsMainFrame (const TGWindow *p, UInt_t w, UInt_t h)
Private Attributes
std::string _macroPath
int looping
UInt_t _rootWidth
UInt_t _rootHeight
UInt_t _rootHorizPad
UInt_t _rootVertPad
UInt_t _windowPad
TGButton * _closeButton
TGMenuBar * _menuBar
TGPopupMenu * _menuFile
TGPopupMenu * _menuWindow
TGShutter * _shutter
TGButton * startloop
TGButton * stoploop
SubSystemList _subSystemList
Static Private Attributes
static PomsMainFrame * _instance = nullptr
Detailed Description
Definition at line 75 of file Poms.h.
View newest version in sPHENIX GitHub at line 75 of file Poms.h
Constructor & Destructor Documentation
PomsMainFrame::PomsMainFrame (const TGWindow * p, UInt_t w, UInt_t h) private
Definition at line 69 of file Poms.cc.
View newest version in sPHENIX GitHub at line 69 of file Poms.cc
References _macroPath, _menuBar, _menuFile, _menuWindow, _rootHeight, _rootWidth, _shutter, M_FILE_EXIT, M_WINDOW_ALIGNRIGHT, M_WINDOW_TILEALL, and POMS_VER.
Referenced by Instance().
PomsMainFrame::~PomsMainFrame () virtual
Definition at line 161 of file Poms.cc.
View newest version in sPHENIX GitHub at line 161 of file Poms.cc
References _closeButton, _instance, _menuBar, _menuFile, _menuWindow, and _shutter.
Member Function Documentation
void PomsMainFrame::AlignRight ()
Definition at line 346 of file Poms.cc.
View newest version in sPHENIX GitHub at line 346 of file Poms.cc
References _rootHeight, _rootHorizPad, _rootVertPad, _rootWidth, Resize(), width, ambiguity_solver_full_chain::x, and y.
Referenced by Draw(), ProcessMessage(), and TileCanvases().
TGShutter * PomsMainFrame::BuildShutter () private
Definition at line 297 of file Poms.cc.
View newest version in sPHENIX GitHub at line 297 of file Poms.cc
References _subSystemList, parse_cmake_options::action, container, and POMS_VER.
Referenced by Draw().
void PomsMainFrame::CascadeCanvases (TList * canvasList)
Definition at line 404 of file Poms.cc.
View newest version in sPHENIX GitHub at line 404 of file Poms.cc
Referenced by SubSystem::CascadeCanvases().
void PomsMainFrame::CloseWindow () virtual
Definition at line 176 of file Poms.cc.
View newest version in sPHENIX GitHub at line 176 of file Poms.cc
Referenced by ProcessMessage().
void PomsMainFrame::Draw ()
Definition at line 132 of file Poms.cc.
View newest version in sPHENIX GitHub at line 132 of file Poms.cc
References _shutter, AlignRight(), BuildShutter(), OnlMonClient::GetDisplaySizeX(), OnlMonClient::GetDisplaySizeY(), OnlMonClient::instance(), POMS_VER, OnlMonClient::SetDisplaySizeX(), and OnlMonClient::SetDisplaySizeY().
Referenced by StartPoms().
const std::string& PomsMainFrame::GetMacroPath () inline
Definition at line 132 of file Poms.h.
View newest version in sPHENIX GitHub at line 132 of file Poms.h
References _macroPath.
Referenced by SubSystem::SubSystem().
UInt_t PomsMainFrame::GetRootHeight () inline
Definition at line 131 of file Poms.h.
View newest version in sPHENIX GitHub at line 131 of file Poms.h
References _rootHeight.
UInt_t PomsMainFrame::GetRootWidth () inline
Definition at line 130 of file Poms.h.
View newest version in sPHENIX GitHub at line 130 of file Poms.h
References _rootWidth.
int PomsMainFrame::HandleButtonPoms (Long_t parm1) private
Definition at line 249 of file Poms.cc.
View newest version in sPHENIX GitHub at line 249 of file Poms.cc
References parse_cmake_options::action, SubSystemAction::Execute(), SubSystemAction::FindById(), and SUBSYSTEM_ACTION_ID_BEGIN.
Referenced by ProcessMessage().
PomsMainFrame * PomsMainFrame::Instance () static
Definition at line 61 of file Poms.cc.
View newest version in sPHENIX GitHub at line 61 of file Poms.cc
References _instance, and PomsMainFrame().
Referenced by SubSystem::CascadeCanvases(), StartPoms(), SubSystem::SubSystem(), and SubSystem::TileCanvases().
void PomsMainFrame::LoopDiLoop () private
Bool_t PomsMainFrame::ProcessMessage (Long_t msg, Long_t parm1, Long_t) virtual
Definition at line 185 of file Poms.cc.
View newest version in sPHENIX GitHub at line 185 of file Poms.cc
References AlignRight(), CloseWindow(), HandleButtonPoms(), M_FILE_EXIT, M_WINDOW_ALIGNRIGHT, M_WINDOW_TILEALL, POMS_VER, utils::status, and TileAllCanvases().
SubSystem * PomsMainFrame::RegisterSubSystem (const char * name, const char * prefix, int addDefaultActions = 1, int loadLibrary = 1)
Definition at line 265 of file Poms.cc.
View newest version in sPHENIX GitHub at line 265 of file Poms.cc
References _subSystemList, SubSystem::AddDefaultActions(), POMS_VER, and str.
Referenced by StartPoms().
SubSystem * PomsMainFrame::RegisterSubSystem (SubSystem * subSystem)
Definition at line 290 of file Poms.cc.
View newest version in sPHENIX GitHub at line 290 of file Poms.cc
References _subSystemList, SubSystem::GetName(), and POMS_VER.
void PomsMainFrame::SetMacroPath (const char * path)
Definition at line 127 of file Poms.cc.
View newest version in sPHENIX GitHub at line 127 of file Poms.cc
References _macroPath, and path.
void PomsMainFrame::StopLoop ()
void PomsMainFrame::TileAllCanvases ()
Definition at line 408 of file Poms.cc.
View newest version in sPHENIX GitHub at line 408 of file Poms.cc
References _subSystemList, and TileCanvases().
Referenced by ProcessMessage().
void PomsMainFrame::TileCanvases (TList * canvasList)
Definition at line 358 of file Poms.cc.
View newest version in sPHENIX GitHub at line 358 of file Poms.cc
References _rootHeight, _rootHorizPad, _rootVertPad, _rootWidth, _windowPad, AlignRight(), i, j, POMS_VER, and width.
Referenced by TileAllCanvases(), and SubSystem::TileCanvases().
Member Data Documentation
TGButton* PomsMainFrame::_closeButton private
Definition at line 93 of file Poms.h.
View newest version in sPHENIX GitHub at line 93 of file Poms.h
Referenced by ~PomsMainFrame().
PomsMainFrame * PomsMainFrame::_instance = nullptr static private
Definition at line 78 of file Poms.h.
View newest version in sPHENIX GitHub at line 78 of file Poms.h
Referenced by Instance(), and ~PomsMainFrame().
std::string PomsMainFrame::_macroPath private
Definition at line 81 of file Poms.h.
View newest version in sPHENIX GitHub at line 81 of file Poms.h
Referenced by GetMacroPath(), PomsMainFrame(), and SetMacroPath().
TGMenuBar* PomsMainFrame::_menuBar private
Definition at line 94 of file Poms.h.
View newest version in sPHENIX GitHub at line 94 of file Poms.h
Referenced by PomsMainFrame(), and ~PomsMainFrame().
TGPopupMenu* PomsMainFrame::_menuFile private
Definition at line 95 of file Poms.h.
View newest version in sPHENIX GitHub at line 95 of file Poms.h
Referenced by PomsMainFrame(), and ~PomsMainFrame().
TGPopupMenu* PomsMainFrame::_menuWindow private
Definition at line 96 of file Poms.h.
View newest version in sPHENIX GitHub at line 96 of file Poms.h
Referenced by PomsMainFrame(), and ~PomsMainFrame().
UInt_t PomsMainFrame::_rootHeight private
Definition at line 87 of file Poms.h.
View newest version in sPHENIX GitHub at line 87 of file Poms.h
Referenced by AlignRight(), GetRootHeight(), PomsMainFrame(), and TileCanvases().
UInt_t PomsMainFrame::_rootHorizPad private
Definition at line 88 of file Poms.h.
View newest version in sPHENIX GitHub at line 88 of file Poms.h
Referenced by AlignRight(), and TileCanvases().
UInt_t PomsMainFrame::_rootVertPad private
Definition at line 89 of file Poms.h.
View newest version in sPHENIX GitHub at line 89 of file Poms.h
Referenced by AlignRight(), and TileCanvases().
UInt_t PomsMainFrame::_rootWidth private
Definition at line 86 of file Poms.h.
View newest version in sPHENIX GitHub at line 86 of file Poms.h
Referenced by AlignRight(), GetRootWidth(), PomsMainFrame(), and TileCanvases().
TGShutter* PomsMainFrame::_shutter private
Definition at line 97 of file Poms.h.
View newest version in sPHENIX GitHub at line 97 of file Poms.h
Referenced by Draw(), PomsMainFrame(), and ~PomsMainFrame().
SubSystemList PomsMainFrame::_subSystemList private
Definition at line 102 of file Poms.h.
View newest version in sPHENIX GitHub at line 102 of file Poms.h
Referenced by BuildShutter(), RegisterSubSystem(), and TileAllCanvases().
UInt_t PomsMainFrame::_windowPad private
Definition at line 90 of file Poms.h.
View newest version in sPHENIX GitHub at line 90 of file Poms.h
Referenced by TileCanvases().
int PomsMainFrame::looping private
Definition at line 83 of file Poms.h.
View newest version in sPHENIX GitHub at line 83 of file Poms.h
TGButton* PomsMainFrame::startloop private
Definition at line 99 of file Poms.h.
View newest version in sPHENIX GitHub at line 99 of file Poms.h
TGButton* PomsMainFrame::stoploop private
Definition at line 100 of file Poms.h.
View newest version in sPHENIX GitHub at line 100 of file Poms.h
The documentation for this class was generated from the following files:
OnlMon/blob/main/poms/Poms.h
OnlMon/blob/main/poms/Poms.cc