Analysis Software: SvtxPHG4ParticleMap Class Reference
SvtxPHG4ParticleMap Class Reference
#include <coresoftware/blob/master/offline/packages/trackbase_historic/SvtxPHG4ParticleMap.h>
Public Types
typedef std::map< float,
std::set< int > > WeightedTruthTrackMap
Reco->Truth map with structure <reco track key, std::map< weight, std::set<g4part id>>>
typedef std::map< unsigned int,
WeightedTruthTrackMap > Map
typedef std::map< unsigned int,
WeightedTruthTrackMap >
::const_iterator ConstIter
typedef std::map< unsigned int,
WeightedTruthTrackMap >
::iterator Iter
Public Member Functions
~SvtxPHG4ParticleMap () override
void identify (std::ostream &os=std::cout) const override
int isValid () const override
isValid returns non zero if object contains vailid data
PHObject * CloneMe () const override
Virtual copy constructor.
void Reset () override
Clear Event.
virtual bool empty () const
virtual std::size_t size () const
virtual std::size_t count (const unsigned int) const
virtual void clear ()
virtual bool processed () const
virtual void setProcessed (const bool)
virtual const
WeightedTruthTrackMap & get (const unsigned int) const
virtual WeightedTruthTrackMap & get (const unsigned int)
virtual WeightedTruthTrackMap insert (const unsigned int, const WeightedTruthTrackMap)
virtual std::size_t erase (const unsigned int)
virtual ConstIter begin () const
virtual ConstIter find (const unsigned int) const
virtual ConstIter end () const
virtual Iter begin ()
virtual Iter find (const unsigned int)
virtual Iter end ()
Public Member Functions inherited from PHObject
PHObject ()
ctor
~PHObject () override
dtor
virtual PHObject * clone () const final
PHObject * Clone (const char *newname="") const final
void Copy (TObject &object) const final
virtual int Integrate () const
virtual int Integrate (PHObject *)
virtual void CopyFrom (const PHObject *obj)
Protected Member Functions
SvtxPHG4ParticleMap ()
Private Member Functions
ClassDefOverride (SvtxPHG4ParticleMap, 1)
Detailed Description
Definition at line 10 of file SvtxPHG4ParticleMap.h.
View newest version in sPHENIX GitHub at line 10 of file SvtxPHG4ParticleMap.h
Member Typedef Documentation
typedef std::map<unsigned int, WeightedTruthTrackMap>::const_iterator SvtxPHG4ParticleMap::ConstIter
Definition at line 16 of file SvtxPHG4ParticleMap.h.
View newest version in sPHENIX GitHub at line 16 of file SvtxPHG4ParticleMap.h
typedef std::map<unsigned int, WeightedTruthTrackMap>::iterator SvtxPHG4ParticleMap::Iter
Definition at line 17 of file SvtxPHG4ParticleMap.h.
View newest version in sPHENIX GitHub at line 17 of file SvtxPHG4ParticleMap.h
typedef std::map<unsigned int, WeightedTruthTrackMap> SvtxPHG4ParticleMap::Map
Definition at line 15 of file SvtxPHG4ParticleMap.h.
View newest version in sPHENIX GitHub at line 15 of file SvtxPHG4ParticleMap.h
typedef std::map<float, std::set<int> > SvtxPHG4ParticleMap::WeightedTruthTrackMap
Reco->Truth map with structure <reco track key, std::map< weight, std::set<g4part id>>>
Definition at line 14 of file SvtxPHG4ParticleMap.h.
View newest version in sPHENIX GitHub at line 14 of file SvtxPHG4ParticleMap.h
Constructor & Destructor Documentation
SvtxPHG4ParticleMap::~SvtxPHG4ParticleMap () inline override
Definition at line 19 of file SvtxPHG4ParticleMap.h.
View newest version in sPHENIX GitHub at line 19 of file SvtxPHG4ParticleMap.h
SvtxPHG4ParticleMap::SvtxPHG4ParticleMap () inline protected
Definition at line 51 of file SvtxPHG4ParticleMap.h.
View newest version in sPHENIX GitHub at line 51 of file SvtxPHG4ParticleMap.h
Member Function Documentation
SvtxPHG4ParticleMap::ConstIter SvtxPHG4ParticleMap::begin (void) const virtual
Reimplemented in SvtxPHG4ParticleMap_v1.
Definition at line 21 of file SvtxPHG4ParticleMap.cc.
View newest version in sPHENIX GitHub at line 21 of file SvtxPHG4ParticleMap.cc
References DummySvtxPHG4ParticleMap.
SvtxPHG4ParticleMap::Iter SvtxPHG4ParticleMap::begin (void) virtual
Reimplemented in SvtxPHG4ParticleMap_v1.
Definition at line 36 of file SvtxPHG4ParticleMap.cc.
View newest version in sPHENIX GitHub at line 36 of file SvtxPHG4ParticleMap.cc
References DummySvtxPHG4ParticleMap.
SvtxPHG4ParticleMap::ClassDefOverride (SvtxPHG4ParticleMap , 1) private
virtual void SvtxPHG4ParticleMap::clear () inline virtual
Reimplemented in SvtxPHG4ParticleMap_v1.
Definition at line 32 of file SvtxPHG4ParticleMap.h.
View newest version in sPHENIX GitHub at line 32 of file SvtxPHG4ParticleMap.h
PHObject* SvtxPHG4ParticleMap::CloneMe () const inline override virtual
Virtual copy constructor.
Reimplemented from PHObject.
Reimplemented in SvtxPHG4ParticleMap_v1.
Definition at line 27 of file SvtxPHG4ParticleMap.h.
View newest version in sPHENIX GitHub at line 27 of file SvtxPHG4ParticleMap.h
virtual std::size_t SvtxPHG4ParticleMap::count (const unsigned int) const inline virtual
Reimplemented in SvtxPHG4ParticleMap_v1.
Definition at line 31 of file SvtxPHG4ParticleMap.h.
View newest version in sPHENIX GitHub at line 31 of file SvtxPHG4ParticleMap.h
virtual bool SvtxPHG4ParticleMap::empty () const inline virtual
Reimplemented in SvtxPHG4ParticleMap_v1.
Definition at line 29 of file SvtxPHG4ParticleMap.h.
View newest version in sPHENIX GitHub at line 29 of file SvtxPHG4ParticleMap.h
SvtxPHG4ParticleMap::ConstIter SvtxPHG4ParticleMap::end (void) const virtual
Reimplemented in SvtxPHG4ParticleMap_v1.
Definition at line 31 of file SvtxPHG4ParticleMap.cc.
View newest version in sPHENIX GitHub at line 31 of file SvtxPHG4ParticleMap.cc
References DummySvtxPHG4ParticleMap.
SvtxPHG4ParticleMap::Iter SvtxPHG4ParticleMap::end (void) virtual
Reimplemented in SvtxPHG4ParticleMap_v1.
Definition at line 46 of file SvtxPHG4ParticleMap.cc.
View newest version in sPHENIX GitHub at line 46 of file SvtxPHG4ParticleMap.cc
References DummySvtxPHG4ParticleMap.
virtual std::size_t SvtxPHG4ParticleMap::erase (const unsigned int) inline virtual
Reimplemented in SvtxPHG4ParticleMap_v1.
Definition at line 40 of file SvtxPHG4ParticleMap.h.
View newest version in sPHENIX GitHub at line 40 of file SvtxPHG4ParticleMap.h
SvtxPHG4ParticleMap::ConstIter SvtxPHG4ParticleMap::find (const unsigned int) const virtual
Reimplemented in SvtxPHG4ParticleMap_v1.
Definition at line 26 of file SvtxPHG4ParticleMap.cc.
View newest version in sPHENIX GitHub at line 26 of file SvtxPHG4ParticleMap.cc
References DummySvtxPHG4ParticleMap.
SvtxPHG4ParticleMap::Iter SvtxPHG4ParticleMap::find (const unsigned int) virtual
Reimplemented in SvtxPHG4ParticleMap_v1.
Definition at line 41 of file SvtxPHG4ParticleMap.cc.
View newest version in sPHENIX GitHub at line 41 of file SvtxPHG4ParticleMap.cc
References DummySvtxPHG4ParticleMap.
const SvtxPHG4ParticleMap::WeightedTruthTrackMap & SvtxPHG4ParticleMap::get (const unsigned int) const virtual
Reimplemented in SvtxPHG4ParticleMap_v1.
Definition at line 6 of file SvtxPHG4ParticleMap.cc.
View newest version in sPHENIX GitHub at line 6 of file SvtxPHG4ParticleMap.cc
References emptyTruthMap.
Referenced by SvtxTrackEval::all_truth_particles(), SvtxPHG4ParticleMap_v1::get(), and SvtxTrackEval::max_truth_particle_by_nclusters().
SvtxPHG4ParticleMap::WeightedTruthTrackMap & SvtxPHG4ParticleMap::get (const unsigned int) virtual
Reimplemented in SvtxPHG4ParticleMap_v1.
Definition at line 11 of file SvtxPHG4ParticleMap.cc.
View newest version in sPHENIX GitHub at line 11 of file SvtxPHG4ParticleMap.cc
References emptyTruthMap.
void SvtxPHG4ParticleMap::identify (std::ostream & os = std::cout) const inline override virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from PHObject.
Reimplemented in SvtxPHG4ParticleMap_v1.
Definition at line 21 of file SvtxPHG4ParticleMap.h.
View newest version in sPHENIX GitHub at line 21 of file SvtxPHG4ParticleMap.h
References os.
Referenced by SvtxTruthRecoTableEval::ResetEvent().
SvtxPHG4ParticleMap::WeightedTruthTrackMap SvtxPHG4ParticleMap::insert (const unsigned int , const WeightedTruthTrackMap) virtual
Definition at line 16 of file SvtxPHG4ParticleMap.cc.
View newest version in sPHENIX GitHub at line 16 of file SvtxPHG4ParticleMap.cc
References emptyTruthMap.
Referenced by SvtxTruthRecoTableEval::fillRecoMap(), and FillTruthRecoMatchMap::process_event().
int SvtxPHG4ParticleMap::isValid () const inline override virtual
isValid returns non zero if object contains vailid data
Reimplemented from PHObject.
Reimplemented in SvtxPHG4ParticleMap_v1.
Definition at line 26 of file SvtxPHG4ParticleMap.h.
View newest version in sPHENIX GitHub at line 26 of file SvtxPHG4ParticleMap.h
virtual bool SvtxPHG4ParticleMap::processed () const inline virtual
Reimplemented in SvtxPHG4ParticleMap_v1.
Definition at line 34 of file SvtxPHG4ParticleMap.h.
View newest version in sPHENIX GitHub at line 34 of file SvtxPHG4ParticleMap.h
Referenced by SvtxTrackEval::all_truth_particles(), and SvtxTrackEval::max_truth_particle_by_nclusters().
void SvtxPHG4ParticleMap::Reset () inline override virtual
Clear Event.
Reimplemented from PHObject.
Reimplemented in SvtxPHG4ParticleMap_v1.
Definition at line 28 of file SvtxPHG4ParticleMap.h.
View newest version in sPHENIX GitHub at line 28 of file SvtxPHG4ParticleMap.h
virtual void SvtxPHG4ParticleMap::setProcessed (const bool) inline virtual
Reimplemented in SvtxPHG4ParticleMap_v1.
Definition at line 35 of file SvtxPHG4ParticleMap.h.
View newest version in sPHENIX GitHub at line 35 of file SvtxPHG4ParticleMap.h
Referenced by SvtxTruthRecoTableEval::fillRecoMap().
virtual std::size_t SvtxPHG4ParticleMap::size (void) const inline virtual
Reimplemented in SvtxPHG4ParticleMap_v1.
Definition at line 30 of file SvtxPHG4ParticleMap.h.
View newest version in sPHENIX GitHub at line 30 of file SvtxPHG4ParticleMap.h
Referenced by DumpSvtxPHG4ParticleMap::process_Node().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/trackbase_historic/SvtxPHG4ParticleMap.h
coresoftware/blob/master/offline/packages/trackbase_historic/SvtxPHG4ParticleMap.cc